### ISSUE TITLE
[BUG] browser needs to be launched with the global proxy while connectOverCDP

### ISSUE THREAD

**Issue by vadkt** [microsoft/playwright#10008]
- Playwright Version: 16.2
- Operating System:  Windows
- Node.js version: 14.18.1
- Browser: Chrome

```javascript
const {chromium, webkit, firefox} = require('playwright');

let browser = await chromium.connectOverCDP({wsEndpoint: 'wss', timeout: 20000});
let context = await browser.newContext({proxy});
```

The main goal is to connect to existing browser via wss and than create new contexts with different proxies. On new context I have such error:

**browser.newContext: Browser needs to be launched with the global proxy. If all contexts override the proxy, global proxy will be never used and can be any string, for example "launch({ proxy: { server: 'per-context' } })**
Do not have such error on Linux, just on Windows machine

**Comment by mxschmitt** [comment]
This is an upstream Chromium limitation, thats what such a workaround is needed. Closing since this is not a Playwright bug.

**Comment by throw5way** [comment]
@mxschmitt Could you please elaborate? What is the limitation? Why does it affect playwright? How users can fix it?

**Comment by mxschmitt** [comment]
See https://github.com/microsoft/playwright/issues/17252

You can workaround it by setting any value as a global proxy and using the one on the context level instead.
