### ISSUE TITLE
[BUG]cmdline error

### ISSUE THREAD

**Issue by tagMatrix4** [microsoft/playwright#10005]
in .\packages\playwright-core\src\utils\processLauncher.ts
export async function launchProcess(options: LaunchProcessOptions): Promise<LaunchResult> {
  const stdio: ('ignore' | 'pipe')[] = options.stdio === 'pipe' ? ['ignore', 'pipe', 'pipe', 'pipe', 'pipe'] : ['pipe', 'pipe', 'pipe'];
  options.log(`<launching> ${options.command} ${options.args ? options.args.join(' ') : ''}`);
  const spawnOptions: childProcess.SpawnOptions = {
    // On non-windows platforms, `detached: true` makes child process a leader of a new
    // process group, making it possible to kill child process tree with `.kill(-pid)` command.
    // @see https://nodejs.org/api/child_process.html#child_process_options_detached
    detached: process.platform !== 'win32',
    env: (options.env as {[key: string]: string}),
    cwd: options.cwd,
    shell: options.shell,
    stdio,
    windowsVerbatimArguments: true, **// add new**
  };
  
  os: win10
  see: https://github.com/microsoft/playwright-dotnet/issues/1810
  see node api: https://nodejs.org/api/child_process.html
  please update the file

**Comment by mxschmitt** [comment]
Please not create additional issues, since there is already https://github.com/microsoft/playwright-dotnet/issues/1810

**Comment by tagMatrix4** [comment]
> Please not create additional issues, since there is already [microsoft/playwright-dotnet#1810](https://github.com/microsoft/playwright-dotnet/issues/1810)

This is not a new issues, it is a solution....
Is my description incorrect?

**Comment by aslushnikov** [comment]
works as intended!
