### ISSUE TITLE
[BUG] Cannot override ListReporter PW 1.16.3 like in 1.15.0

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#10006]
**Context:**
- Playwright Version: [1.16.3]
- Operating System: [Windows]
- Node.js version: [14.17.6]
- Browser: [All]

Hello, i have custom reporter based on ListReporter.
(repo with bug example https://github.com/Gornostalev/playwright_issue10006_custom-reporter)

**Code Snippet**

```typescript
import { TestCase, TestResult } from '@playwright/test/reporter';
import ListReporter from '@playwright/test/lib/test/reporters/list';

class CustomListReporter extends ListReporter {
  onTestEnd(test: TestCase, result: TestResult): void {
    console.log('override onTestEnd on standart ListReporter')
  }
}

export default CustomListReporter;

```

```typescript
#declare.d.ts
declare module '@playwright/test/lib/test/reporters/list';
```

and on Playwright 1.15.0 was working correct, but after update and run:

```powershell
npm install @playwright/test@1.16.3
npx playwright test --config=playwright.config.ts
```
i got this error:

**Error [ERR_PACKAGE_PATH_NOT_EXPORTED] [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/test/reporters/list' is not defined by "exports" in J:\repository\job\reporterIssue\playwright_issue_custom-reporter\node_modules\@playwright\test\package.json**

btw i know about this documentation https://playwright.dev/docs/test-reporters#custom-reporters
but i want override only onTestEnd handler in ListReporter because it shows information about the current test very cool ♥

**Comment by mxschmitt** [comment]
The internal reporters were never designed to get imported/extended manually. If you have suggestions for our list reporter, let us know! Since we can add additional configurations per reporter if needed.

**Comment by Gornostalev** [comment]
@mxschmitt, yes i have. For now i use onTestEnd for ignore failed test if his error it is a logged error on our team foundation server, I check it with REST API

**Comment by mxschmitt** [comment]
For that we'd recommend to copy our reporter (in your case list) into your project and not inherit from our reporter, since we might change our implementation / where files are located over time.

**Comment by Gornostalev** [comment]
@mxschmitt, ok, got it, thank you!
