### ISSUE TITLE
[Question] How to send HTTP Delete request method with body

### ISSUE THREAD

**Issue by anht3889** [microsoft/playwright#10013]
Hi Playwright team,

Currently, I need to test an HTTP Delete request method with request body, but `body` is not supported in `delete` method. Is there any workaround to achieve this or do we have a plan to add `body` into `delete` method in the next version?

Thank you!

**Comment by yury-s** [comment]
Assuming you're talking about [request.delete()](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-delete) it's not currently possible to provide body. We'll fix that.

**Comment by anht3889** [comment]
> Assuming you're talking about [request.delete()](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-delete) it's not currently possible to provide body. We'll fix that.

Yeah that's it. Thank you so much!
