### ISSUE TITLE
[Question] How to get browser name in a test?

### ISSUE THREAD

**Issue by billyvg** [microsoft/playwright#10026]
I've scoured through the docs and I can't seem to find where to get the current browser name inside of a test.

e.g. I'm trying to do something like the following...

```javascript
test('test', async ({page}) => {
page.screenshot({ path: `screenshot-${browserName}` });
});
```

**Comment by yury-s** [comment]
```js
test('test', async ({page, browserName}) => {
  page.screenshot({ path: `screenshot-${browserName}` });
});
```

Note that [toMatchSnapshot](https://playwright.dev/docs/test-snapshots) will add that automatically.

**Comment by billyvg** [comment]
Ah thanks! Note I was searching with `browser name` and not `browsername`, the latter being much more relevant.

**Comment by laciferin2024** [comment]
> ```js
> test('test', async ({page, browserName}) => {
>   await page.screenshot({ path: `screenshot-${browserName}` });
> });
> ```
> 
> Note that [toMatchSnapshot](https://playwright.dev/docs/test-snapshots) will add that automatically.

Getting mime type cannot be null, 

Working version as of 2024:

```
test('test', async ({page, browserName}) => {
  await page.screenshot({ path: `screenshot-${browserName}.jpg` });
});
```
