### ISSUE TITLE
[Feature]IgnoreOnly

### ISSUE THREAD

**Issue by alanstronach** [microsoft/playwright#10021]
As useful as ForbidOnly is, it would also be nice for Playwright to have the option to ignore Only and let the suite run. Even nicer would be to have this supplemented in the run log to list the tests where Only was found ( a bit like we have for slow tests)

**Comment by mxschmitt** [comment]
What is the use-case of it? So you want to have it inverted - e.g. you mark 2 tests as `test.only` and 2 not which results when you execute it with your new flag `--ignore-only` that the 2 normal tests will run?

**Comment by klhex** [comment]
@alanstronach Would feature request #7786 also satisfy your needs? If so, please upvote. 👍

**Comment by alanstronach** [comment]
No Max I wasn't looking for an invertion. I want the full suite to run if IgnoreOnly is true i.e. ignore the fact that some tests may be marked as only. To me this would be an alternative action to ForbidOnly, which aborts the test run if some tests are marked as only

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
