### ISSUE TITLE
[Feature] Add forEachStep / afterEachStep actions to steps

### ISSUE THREAD

**Issue by Automation-Luch** [microsoft/playwright#10037]
I have very long form and test looks like this :

    await test.step('Directors', async () => {
      await kycForms.fillAuthorityForm()
      await click(kyc.buttons.NEXT, page)
    })
    await test.step('Tax ', async () => {
      await kycForms.fillTaxDeclarationForm()
      await click(kyc.buttons.NEXT, page)
    })
    await test.step('Investor', async () => {
      await kycForms.fillInvestor()
      await click(kyc.buttons.NEXT, page)
    })
    await test.step('Investor Second', async () => {
      await kycForms.fillInvestorSecond()
      await click(kyc.buttons.NEXT, page)
    })

if I could move the  "await click(kyc.buttons.NEXT, page)" line to the afterEachStep it will be very useful

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
