### ISSUE TITLE
[BUG] alternate test failing when running tests in firefox

### ISSUE THREAD

**Issue by KkuanChee** [microsoft/playwright#10032]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows
- Node.js version: v14.15.1
- Browser: firefox

**Code Snippet**
```
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {

  testDir: 'tests',

  use: {
    headless: true,
    viewport: { width: 1280, height: 1024 },
    browserName: 'firefox',
  },
};
export default config;
```

```
//browser.test.ts
import {test} from '@playwright/test';

test('basic test', async ({ page }) => {
  console.log("test 1......");
  await page.goto('http://google.com/');
});

test('basic test2', async ({ page }) => {
  console.log("test 2......");
  await page.goto('http://google.com/');
});

test('basic test3', async ({ page }) => {
  console.log("test 3......");
  await page.goto('http://google.com/');
});

test('basic test4', async ({ page }) => {
  console.log("test 4......");
  await page.goto('http://google.com/');
});
```

**Describe the bug**

Execute tests above with the given playwright config.
first and third will pass.
second and third tests failed with the following error

    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://google.com/", waiting until "load"
    ============================================================

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
