### ISSUE TITLE
[Question] How to use babel?

### ISSUE THREAD

**Issue by axelthat2** [microsoft/playwright#10034]
So in root of my project I have following `babel.config.js`,

```
module.exports = {
  presets: ["babel-preset-vite"]
}
```

Now, how do I tell playwright to use the babel config?

**Comment by mxschmitt** [comment]
Playwright does not do anything special there. Do you consume it as a library or is this question Playwright Test (`@playwright/test`) specific?

What are you trying to archive? Be aware that Playwright is a Node.js library, you can't consume it from the web, because it requires operating system interaction, e.g. launching processes, writing files etc.

**Comment by axelthat2** [comment]
It's just that I can't use `import.meta` in Playwright so I thought of using [babel-preset-vite](https://github.com/OpenSourceRaidGuild/babel-vite). which basically transforms `import.meta.env` to `process.env`.

**Comment by mxschmitt** [comment]
How do you plan to consume Playwright? Inside your web application? Since Vite is a frontend bundler, this won't work if I understand Vite correctly.

**Comment by axelthat2** [comment]
Well I use nodejs `npx playwright test`. But `import.meta` is not vite exclusive though if I'm not mistaken. Is it possible to support `import.meta` in playwright?

**Comment by mxschmitt** [comment]
There is no relation between npx playwright test and Vite. With Playwright Test `import.meta` gets filled if you use the `.mjs` extension. Does this work for you or what are you trying to achieve?

**Comment by axelthat2** [comment]
Oh it requires `.mjs` extension. Didn't know that. But shouldn't it work for Typescript files? I get this error in `setup-test.ts` which is globalSetup file for Playwright,

```
console.log(import.meta);
                   ^^^^

SyntaxError: Cannot use 'import.meta' outside a module
```

This is my `tsconfig.json`,
```
{
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "module": "esnext",
    "moduleResolution": "node",
    "strict": true,
    "jsx": "preserve",
    "sourceMap": true,
    "resolveJsonModule": true,
    "esModuleInterop": true,
    "lib": ["esnext", "dom"],
    "baseUrl": ".",
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "setup-test.ts",
    "src/**/*.ts",
    "src/**/*.d.ts",
    "src/**/*.tsx",
    "src/**/*.vue"
  ]
}
```

**Comment by aslushnikov** [comment]
We don't use tsconfig to compile typescript, but there's a metabug about it: https://github.com/microsoft/playwright/issues/7121

**Comment by axelthat2** [comment]
I see

**Comment by gazpachu** [comment]
I'm also interested about this. Using `.mjs` fixes the `import.meta` issue, but then then we get this other error on `<App />`:

```
JSX not allowed in files with extension '.mjs'
```

This happens just on the sample test from the docs: https://playwright.dev/docs/test-components

```
import { expect, test } from '@playwright/experimental-ct-react';

import { App } from './App';

test.use({ viewport: { width: 500, height: 500 } });

test('should work', async ({ mount }) => {
  const component = await mount(<App />);
  await expect(component).toBeVisible();
});

```
