### ISSUE TITLE
[Question] Running Playwright test cases in batches on different test agents

### ISSUE THREAD

**Issue by softleo-llc** [microsoft/playwright#10049]
We are having around 200 test cases in Playwright-Jest. We were having custom logic to create batches of test cases using jest `listTests` and then creating a batches of test cases. Then we are running these batch of test cases on different test agents using Azure Build Pipelines. Here is code snippet we are using:

`function getTestMatchFiles() {
	let parallelism = null;
	const envs = [
		{
			index: "CI_PARALLEL_INDEX",
			parallel: "CI_PARALLEL_RUNS",
			tests: "PLAYWRIGHT_TEST_SUITE",
		},
	];
	let testFiles = playwrightTestsJson["default"];

	const testSuite = process.env.PLAYWRIGHT_TEST_SUITE;
	if (testSuite) {
		console.log("Running tests from test suite: ", testSuite);
		testFiles = playwrightTestsJson[testSuite];
	}

	console.log("Discovering the test suites to run from manifest file: ", testFiles);

	let maybeNum = (val) => {
		let num = parseInt(val, 10);
		return Number.isNaN(num) ? null : num;
	};

	// Split array of tests into N equal number of arrays to run in parallel
	let chunks = function grouper(array, index, cols) {
		if (index >= cols) {
			console.log("##vso[task.logissue type=error]Please provide valid index.");
			process.exit(1);
		}
		function split(array, cols) {
			if (cols == 1) return array;
			var size = Math.ceil(array.length / cols);
			return array
				.slice(0, size)
				.concat([null])
				.concat(split(array.slice(size), cols - 1));
		}

		var arr = split(array, cols);
		var groups = [];
		var group = [];
		for (var i = 0; i < arr.length; i++) {
			if (arr[i] === null) {
				groups.push(group);
				group = [];
				continue;
			}
			group.push(arr[i]);
		}
		groups.push(group);
		return groups[index];
	};

	for (let env of envs) {
		let index = maybeNum(process.env[env.index]);
		let parallel = maybeNum(process.env[env.parallel]);
		if (index !== null && parallel !== null) {
			parallelism = { index, parallel };
			break;
		}
	}

	if (parallelism) {
		testFiles = chunks(testFiles, parallelism.index, parallelism.parallel);
		console.log("Running test on agent # ", parallelism.index + 1);
	}

	console.log("Running test suites from manifest file: ", testFiles);

	return testFiles;
}
`

We call the above function in `TestMatch` attribute in Jest config file.

Then we have separate logic to run each batch on different test agent.

So we would like to know if there is any way we can run playwright test cases on multi-agent configuration like **VsTest** task provides.

**Comment by mxschmitt** [comment]
We only provide support for Playwright and Playwright's own test-runner (`@playwright/test`) and are unfortunately not familiar with Jest internals. If you're about to migrate, we're happy to help since we also offer a setting which allows you to create different projects and feed them with different inputs and run them either separately or multiple times: https://playwright.dev/docs/test-advanced#projects

For more information, see here: https://playwright.dev/docs/intro

**Comment by softleo-llc** [comment]
I have simple question: How we can split playwright tests into chunks (batches) and running these chunks on separate agents (multi-agent configuration)?

**Comment by mxschmitt** [comment]
This is called sharding, see here: https://playwright.dev/docs/test-parallel#shard-tests-between-multiple-machines
