### ISSUE TITLE
[Feature] Add examples folder with playwright test examples

### ISSUE THREAD

**Issue by remorses** [microsoft/playwright#10044]
I can't find any examples of tests taht use the `@playwright/test` package, it would be cool to have some examples in the `playwright` repository in an "examples" root folder.

**Comment by mxschmitt** [comment]
If you bootstrap projects with `npm init playwright my-project` or for existing projects with `npm init playwright` you'll get examples, let us know if you miss important ones there. Thanks!

**Comment by remorses** [comment]
Thank you for the tip!

Still, it would be nice to have an examples folder so people that are evaluating playwright can see some test examples quickly

**Comment by mxschmitt** [comment]
We're soon adding `npm init playwright` to the docs, then we'll refer to the examples that way.

Closing by that and thank you for the suggestion!
