### ISSUE TITLE
[BUG] launchPersistent returns only browserContext

### ISSUE THREAD

**Issue by Sue9445** [microsoft/playwright#1004]
Hi,

firefox.launchPersistent returns default browserContext, How do I create a new context when it is this way?

**Comment by pavelfeldman** [comment]
Please refer to [release notes](https://github.com/microsoft/playwright/releases) that describes launch modes while we are updating our docs.

**Comment by Sue9445** [comment]
How can I set context options (userAgent,viewport, ...) with clean profile directory?

**Comment by pavelfeldman** [comment]
This is not currently supported. Could you share more about your use case?

**Comment by Sue9445** [comment]
I working with different proxies.I am trying to run the code in this link.

https://github.com/microsoft/playwright/issues/917#issuecomment-584555120

**Comment by pavelfeldman** [comment]
The link above is saying works with v0.11. Please reopen if there is more to address.

**Comment by Sue9445** [comment]
I mentioned that the navigation problem is solved with v0.11 in this link, but when I execute the code I shared there as i mentioned here, I can’t launch firefox with newly created user data dir.

I can launch when I edit launchPersistent function to return the server object instead of the context object.
