### ISSUE TITLE
[Feature] Pipe browser logs to test runner logs

### ISSUE THREAD

**Issue by sidharthv96** [microsoft/playwright#10042]
A flag to enable console logs from browser to be piped to the test runner.
This would be useful for debugging as browser logs tend to zoom past unless we use slowmo (which slows everything down, so long tests are a pain).
Browsers also timeout when stopped.

If a flag is added, we can just run the tests headless and check logs in the runner.

Current workaround suggested by @pavelfeldman `page.on('console', console.log)`

**Comment by mxschmitt** [comment]
I could imagine adding this to the [`--debug` mode](https://playwright.dev/docs/test-cli#reference).

**Comment by sidharthv96** [comment]
Instead of bundling with `--debug` a new flag (like `--browerLogs` or `--pipeLogs`) might be appropriate as it'll pollute the debug output if it's enabled by default in debug.

Yup, aware of the limitations of logging to console, my use case was to track down a race condition, so I was logging some values to console and working off of that.

More rich debugging can always be done with the trace viewer.
