### ISSUE TITLE
[Question] Want to execute a test multiple times without CLI commands?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10046]
Hi, 
as the title may suggest, I'm trying to implement a button capable of running a test multiple times (either it has failed or passed the previous times, it doesn't matter) without typing the commands on the CLI. Just imagine a simple client server app. The only process I launch is the server. I was just reading the code behind and I managed to export the runner function "run" with all the parameters it wants, e.g. the configuration file ecc...
What I don't understand is why it prints me "no tests found" the second time I try to re-run the test. Indeed, the first time I manage to run the test, but even if it pass or fail (e.g. I force the abort) Then I cannot re-run it without restarting the process.
Of course, in this condition, I don't want to exit from the process because it would stop the server from working and receiving click events. Is there something I'm missing about? Any advice?

Thanks.

**Comment by mxschmitt** [comment]
You are probably interested in #8971 if you're about to instruct the test-runner. Let us know what kind of API you need and what your use-case case is.

Do you mean with _process_ the browser window, so you want to re-use the page when running tests?

**Comment by DvDream** [comment]
My use-case is the following:

1- I run a Express.js server with npm, in the client-side I have a html button which is in charge of running a test.
2 - Pressing the button DOES NOT "spawn" a command line interface with the command "npx playwright test --headed". Instead, it runs the function:

```
async function runTests(args, opts) {
 const overrides = {
    forbidOnly: undefined,
    globalTimeout: undefined,
    grep: undefined,
    grepInvert: undefined,
    maxFailures: undefined,
    outputDir: undefined,
    quiet: undefined,
    repeatEach: undefined,
    retries: undefined,
    reporter: undefined,
    shard: undefined,
    timeout: undefined,
    updateSnapshots: undefined,
    workers: undefined
  };
  if (opts.headed || opts.debug || opts.reuseContext) overrides.use = {
    headless: false
  };
  if (opts.debug || opts.reuseContext) {
    overrides.maxFailures = 1;
    overrides.timeout = 0;
    overrides.workers = 1;
  }
  await (0, _profiler.startProfiling)();
  const loader = new _loader.Loader(defaultConfig, overrides);
  const loadedConfig = await loader.loadConfigFile('C:\\Users\\admin\\Desktop\\svelte-projects\\my-svelte-project\\playwright.config.js');
const filePatternFilters = args.map(arg => {
    const match = /^(.*):(\d+)$/.exec(arg);
    return {
      re: forceRegExp(match ? match[1] : arg),
      line: match ? parseInt(match[2], 10) : null
    };
  });
  const runner = new _runner.Runner(loader);
  //if (process.env.PLAYWRIGHT_DOCKER) runner.addInternalGlobalSetup(launchDockerContainer);
  const result = await runner.run(!!opts.list, filePatternFilters, opts.project || undefined);
  await (0, _profiler.stopProfiling)(undefined);
};
```

which takes some parts of the function in here: https://github.com/microsoft/playwright/blob/62a01a41c68330d26851a46b65df6a1c4d5fddf9/packages/playwright-test/src/cli.ts#L171

3 - The test in this way has launched but then I decide to make it fail, just closing the browser window. 
4 - Now, I want to re-launch the test once again. THe server is keeping running, so I click again on the html button: I'd like the test to be retrieved, to open again the browser window just like before and to make the test run. 

This last point is not happening, since it prints me "no tests found", and I don't understand why.

Hope I made myself more clear :)

**Comment by mxschmitt** [comment]
Yeah definitely you made it more clear. Since this not how it should get consume as of today, I'm merging it into https://github.com/microsoft/playwright/issues/8971. There we track our API for launching the test-runner programmatically.

**Comment by DvDream** [comment]
Hi, I reopen this question as I got a little step further. I just cleared the require cache from the "test.ts" file and the "no tests found" message does not appear anymore. However, the browser won't open and you can see from the video that there's a sort of loop with a creation/deletion of the worker. I tried to debug it and I found that maybe the reason is the run function of the dispatcher object and I'm not understanding why.. Maybe you developers can explain me better :)

https://user-images.githubusercontent.com/45291289/141319843-0d85578e-a6f4-491f-8010-a4564c1cb213.mp4

**Comment by DvDream** [comment]
I found the "problem". It's here: 

https://github.com/microsoft/playwright/blob/80da0f7b692464645423a439ddad46a1f7ff1403/packages/playwright-test/src/testType.ts#L70

Commenting this line the tests can be run programmatically twice without any problem. Now.. I'd like to know from you developers what is this line for and the side effects that would be caused by commenting it :) Thanks for your patience!
