### ISSUE TITLE
[BUG] docker integration: make sure docker version is 20.04+ on linux

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#10050]
we use a 20.04+ specific feature
- https://stackoverflow.com/questions/48546124/what-is-linux-equivalent-of-host-docker-internal/61001152

Maybe we can either not use it, or make sure that a proper version of docker is running.

**Comment by aslushnikov** [comment]
For the record: docker integration depends on global fixtures, so moving them forward.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
