### ISSUE TITLE
Feature: page.text()

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1005]
Oftentimes one want to wait for a certain piece of text (an exact match or regex match) to appear on a page. As an example, imagine a login page you are testing that has a 1 sec delay for faulty login attempts (to prevent brute force), presenting the text "Unauthorized" upon login failure. The text "Unauthorized" shows up underneath the "Submit" button after 1 sec.

This can be [done in a few](https://stackoverflow.com/questions/46825300/wait-for-text-to-appear-when-using-puppeteer), not optimal, ways as far as I am aware. Here is a mix of ways to achieve this:

```javascript
await page.waitForFunction('document.querySelector(".info:").inner‌​Text.length == 7');
await page.waitForSelector('.info:not(:empty)');
await page.waitForXPath("//*[@class='info' and contains(., 'Expected text')]");
```

It would be nicer if there was a `page.text(selector, 'text_string_or_regex', [, options])` or similar to achieve this that had a few options, such as waiting for X amount of seconds for some text to appear somewhere, or maybe an array that it should first be X, then Y, then Z. I don't know, just brainstorming here.

I think it would simplify the code and usage a bit for these scenarios to have a function like this.

**Comment by dgozman** [comment]
Perhaps [text](https://github.com/microsoft/playwright/blob/master/docs/selectors.md#text) selector might help?

```js
// find 'Expected text' anywhere on the page:
await page.waitForSelector('text="Expected text"');

// find 'Unauthorized' inside '.info' section:
await page.waitForSelector('css=.info >> text="Unauthorized"');
```

Note that [waitForSelector](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectorselector-options) already has a `timeout` option.

**Comment by thernstig** [comment]
That might definitely work. Is having a default page.text() not a good idea then though? I was thinking that it would be a common enough scenario to use in e2e testing.

**Comment by thernstig** [comment]
Maybe [this](https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#working-with-selectors) is good enough, which seems to be supported:

```javascript
// converted to 'text="foo"'
const handle = await page.$('"foo"');
```
