### ISSUE TITLE
[BUG] docker: make sure docker is installed

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#10051]
If docker is not installed, there's no named pipe / unix socket

![image](https://user-images.githubusercontent.com/746130/140394361-902ec90a-067d-4a45-ad13-35bed2b475c8.png)

**Comment by aslushnikov** [comment]
For the record: docker integration depends on global fixtures, so moving them forward.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
