### ISSUE TITLE
[Feature] add `connection()` to `CDPSession` to maintain parity with Puppeteer

### ISSUE THREAD

**Issue by tyler-graham-ck** [microsoft/playwright#10068]
Today I was messing around with the new [Lighthouse User Flow api](https://web.dev/lighthouse-user-flows/) which is written to use puppeteer. 

I managed to hack things together to the point where it would work (note I've only tried `flow.navigate`) and one of the things I ran into was the lack of `connection()` on `CDPSession`. I'm sure there's a good reason why it's not there but for my own sanity I wish it were 😅 

The discussion I had with the lighthouse folks has more details on what was required to get things to work
- https://github.com/GoogleChrome/lighthouse/discussions/13326

[pptr `Connection` class](https://github.com/puppeteer/puppeteer/blob/main/src/common/Connection.ts)
[pptr `connection()` doc](https://pptr.dev/#?product=Puppeteer&version=v11.0.0&show=api-cdpsessionconnection)

**Comment by unlikelyzero** [comment]
I'm currently working on the same type of problem. I'm considering two paths:
1. Use `jest-playwright` and `jest-puppeteer` to maintain two configurations of puppeteer and playwright in a "sane" config.
2. Import the `lighthouse` library and capture and record measurements in a not-yet-determined data format.

**Comment by aslushnikov** [comment]
> I'm sure there's a good reason why it's not there but for my own sanity I wish it were 😅

@tyler-graham-ck yeah there's no connection, and there are no plans to expose any at this moment.

**Comment by tyler-graham-ck** [comment]
Are you saying that the concept of connection in puppeteer is extraneous?

**Comment by JoelEinbinder** [comment]
You can launch the browser yourself and connect playwright with [connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp). We don't want to be in the business of managing CDP connections for you, as they can get very complicated and browser specific.

**Comment by tyler-graham-ck** [comment]
When you run `page.context().newCDPSession(page)` is that now creating a connection that playwright is managing? I feel like there is some dot I'm not connecting here 🤔

**Comment by cliffordfajardo** [comment]
@tyler-graham-ck  @unlikelyzero  - were you able to get lighthouse working with playwright?

**Comment by xbhoneybee** [comment]
@cliffordfajardo  Same question to you, can you share anything😂 thanks in advance

**Comment by unlikelyzero** [comment]
@cliffordfajardo I am not using Lighthouse User Flows. My plan is to use playwright/test to get to interesting points in time and then leverage the lighthouse package as described in https://www.checklyhq.com/learn/headless/basics-performance/#additional-performance-libraries

```js
const chromeLauncher = require('chrome-launcher')
const { chromium } = require('playwright')
const lighthouse = require('lighthouse')
const request = require('request')
const util = require('util')

;(async () => {
  const chrome = await chromeLauncher.launch()

  const resp = await util.promisify(request)(
    `http://localhost:${chrome.port}/json/version`
  )
  const { webSocketDebuggerUrl } = JSON.parse(resp.body)
  const browser = await chromium.connect({ wsEndpoint: webSocketDebuggerUrl })

  const { lhr } = await lighthouse(
    'https://danube-web.shop/',
    { port: chrome.port },
    null
  )

  console.log('Report complete for', lhr.finalUrl)

  console.log(`
    Time To Interactive - Score: ${lhr.audits.interactive.score},
    Value: ${lhr.audits.interactive.numericValue} ${lhr.audits.interactive.numericUnit}
  `)

  await browser.close()
  await chrome.kill()
})()
```

**Comment by lakshbhutani** [comment]
@unlikelyzero is there a way to share auth state between a micro front-end architecture since I also want to calculate lighthouse score for logged in routes?
