### ISSUE TITLE
[BUG] @playwright/test with third-party imports unexpectedly fails with cryptic ERR_UNKNOWN_FILE_EXTENSION

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10067]
**Context:**
- Playwright Version: `@playwright/test@1.16.3`

**Code Snippet**

See https://github.com/rwoll/playwright-unknown-file-extension-repro for repro instructions and code.

**Description**

I added an unused import of node-fetch in base test class, and now running the test immediately errors with a cryptic ERR_UNKNOWN_FILE_EXTENSION error.

**Comment by jriddy** [comment]
I had the same issue GI believe, with `@playwright/test@1.15.2`

Issue for me was with a line,
```typescript
import { urlJoin } from `@ctr/url-join`;
```

Was using `@ctrl/url-join@2.0.0`

**Comment by rwoll** [comment]
Linking in Slack convo for history: https://playwright.slack.com/archives/C01AG7QGW2F/p1636082924154400?thread_ts=1636059263.147200&channel=C01AG7QGW2F&message_ts=1636082924.154400 for some discussion of underlying issue.

**Comment by rwoll** [comment]
@JoelEinbinder Just looked through GitHub issues and realize this is likely a dupe of https://github.com/microsoft/playwright/issues/9344. If so, please feel free to close this issue and I'll watch the other. Thanks!

**Comment by mxschmitt** [comment]
Folding into #9344.
