### ISSUE TITLE
[BUG] Empty test-results folder when all tests pass

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#10072]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 12.22
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
//pw.config.js
use: {
    screenshot: 'only-on-failure',
},
projects: [
    {
      name: 'Desktop Chrome',
      use: { browserName: 'chromium' },
    },
];
//foo.spec.js
const { test, expect } = require("@playwright/test");
test.describe('Test me', () => {
  test('Passed', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Fast and/);
  });
});
```

**Describe the bug**
Empty `test-results` is created when the test passes.

Expected: No folder is created if all the tests passed i.e. no artifacts saved

**Comment by mxschmitt** [comment]
Currently this is expected. Does this cause any issues for you?

**Comment by Nav-2d** [comment]
Okay thanks for confirming. One more question: sorry trying to wrap my head around the whole artifacts things. An updated config file:
```
use: {
    screenshot: 'only-on-failure',
},
reporter: [
    ['html', { outputFolder: 'src/tests/e2e/test-results' }],
],
```

Now, if the tests fail, there are two folders created one: `./test-results` and other one: `src/tests/e2e/test-results`. Is this expected too?

**Comment by mxschmitt** [comment]
Yes, since the `outputDir` is used for artifacts and the html reporter `outputFolder` for visualisation purposes. The latter one can be used to get uploaded on some server and see the actual report in your browser.
