### ISSUE TITLE
[Question] connectOverCDP on Windows machine with proxy

### ISSUE THREAD

**Issue by vadkt** [microsoft/playwright#10077]
Hi there. I'm using script, which running real chrome, connect to it via connectOverCDP and use different proxies for contexts.
 ```
await exec(`chrome --remote-debugging-port=${process.env.REAL_BROWSER_PORT}`)
let browser = await chromium.connectOverCDP({wsEndpoint: .wsRealEndpoint, timeout: 20000});
contextOptiopns['proxy'] = proxy
let context = browser.newContext(contextOptiopns);
```
This code works well on Linux but have error message on Windows: 
**browser.newContext: Browser needs to be launched with the global proxy. If all contexts override the proxy, global proxy will be never used and can be any string, for example "launch({ proxy: { server: 'per-context' } })**
I tried to add --proxy-server to exec command or set proxy globally for system, browser uses proxy - checked it via ip checker. But it does not help me to solve that issue on playwright.
Can you advise something?

**Comment by mxschmitt** [comment]
Linking #10008
