### ISSUE TITLE
[Question] Inquiries about selenium grid

### ISSUE THREAD

**Issue by namilkimfree** [microsoft/playwright#10074]
Normal operation when running on local selenium hud/node

When proceeding from a remote selenium hub/node, a node is assigned through the hub but does not proceed

`
Internally, Playwright connects to the browser using Chrome DevTools Protocol websocket. This requires Selenium Grid nodes to be directly accessible from the machine that runs Playwright.
`
hub server vm: 192.168.0.1
node server vm: 192.168.1.17

Node Server '192.168.1.17'
What I need to allow the ports firewall?   or 

--remote-debuggging-port=xxxx?

It works on localhost grid, but

Doesn't work on grids on remote servers.

Playwright
Try chrome remote debuugin on localhost:port when attaching to grid on remote server. 

https://github.com/microsoft/playwright/issues/9758  same issue

**Comment by mxschmitt** [comment]
Version 1.18 includes fixes for Selenium 3 and 4. See [here](https://playwright.dev/docs/selenium-grid) for documentation and please file new bug reports if you still encounter bugs.
