### ISSUE TITLE
[BUG] Can not upload files( .pdf, .png) into Outlook in headless mode. Error code 400

### ISSUE THREAD

**Issue by OlegRomaniuck** [microsoft/playwright#10075]
**Context:**
- Playwright Version: 1.16
- Operating System: MacOS ( Catalina)
- Node.js version : v14.16.1
- Browser: Chromium

Info: npx envinfo --preset playwright --markdown
## System:
 - OS: macOS 10.15.7
 - Memory: 811.82 MB / 16.00 GB
## Binaries:
 - Node: 14.16.1 - /usr/local/bin/node
 - npm: 6.14.12 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
Browsers:
    Chrome: 95.0.4638.69
    Firefox: 88.0.1
    Safari: 14.1

Description: 
1. I was able to successfully load the files in visible mode
2. was able to successfully load the files using puppeteer in headless mode 
3. Got an error using any approach

**Code Snippet**
1) I tried this =>
```javascript
this.page.on('filechooser', async (filechooser) => {
            await filechooser.setFiles(resources);
        });
await this.page.click('button[name="Attach"]');
await this.page.click('button[name="Browse this computer"]');
await this.page.waitForResponse(resp => resp.url().includes('owa/service.svc?action=GetDlpPolicyTip'), { timeout: 40000 });
await this.page.waitForResponse(resp => resp.url().includes('https://outlook.office.com/owa/service.svc/CreateAttachmentFromLocalFile'), { timeout: 40000 });
await this.page.waitForResponse(resp => resp.url().includes('action=GetAttachmentPreviews'), { timeout: 40000 });
```
2)  I tried this =>
```javascript
const locators = await this.page.$$('//input[@type="file" and not(@accept="image/*")]');
await locators[0].setInputFiles(resources);
```
3)  I tried this =>
```javascript
 await this.page.setInputFiles('//input[@type="file" and not(@accept="image/*")]', {
        name: 'sample.pdf',
        mimeType: 'application/pdf',
        buffer: Buffer.from(resources),
       });
```
In any case I got an error  code 400 on this request https://outlook.office.com/owa/service.svc/CreateAttachmentFromLocalFile
Bug: 
Server response code 400 in case I used playwright in headless: true
Manually using the same account - work fine
Puppeteer in visible mode - work fine
Playwright in visible mode - work fine
If you need some additional information please let me know, I try to add it
I add 2 screenshots: one with error and other in case upload finish successfully 
![Screenshot 2021-11-04 at 14 14 18](https://user-images.githubusercontent.com/11087838/140475520-1e7092be-358e-469c-b4ef-8cfe3a528a29.png)
![Screenshot 2021-11-05 at 09 47 45](https://user-images.githubusercontent.com/11087838/140476240-a060b1c3-f57b-450d-abf2-6717c6be2800.png)
![Screenshot 2021-11-05 at 09 48 00](https://user-images.githubusercontent.com/11087838/140476247-cdafd21b-373a-4e6f-a38d-435813fb025a.png)
![Screenshot 2021-11-05 at 09 48 32](https://user-images.githubusercontent.com/11087838/140476249-3edf5886-3c84-4c80-877e-ae9ef6f808df.png)

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
So it works in headful but not in headless? Usually this is because the applications have some kind of bot protection. I'd recommend to use the debugging tools to find out what exactly does go wrong so you can pin point the error better: https://playwright.dev/docs/debug

**Comment by kenhosr** [comment]
Oleg mentioned upload file worked in puppeteer headless mode. But not playwright headless mode.

Running in debug mode will always pass since it is also running in headful mode.

**Comment by mxschmitt** [comment]
You can also just enable the verbose API logs to understand better what the problem is: https://playwright.dev/docs/debug/#verbose-api-logs

Using a trace might also help.

**Comment by khvirtru** [comment]
We've found the reason, essentially we need to set userAgent to workaround this issue.

This is probably some protection from application side. Thanks @mxschmitt !

**Comment by kenhosr** [comment]
We've found the reason, essentially we need to set userAgent to workaround this issue.

This is probably some protection from application side. Thanks @mxschmitt !
