### ISSUE TITLE
[BUG] Report slow tests considers all tests in one test file as one test

### ISSUE THREAD

**Issue by olesiaMartushkanova** [microsoft/playwright#10073]
**Context:**
- Playwright Version: 1.16
- Operating System: [Mac]
- Node.js version: [v16.9.1]
- Browser: [All]

**Pre-setup:**
in `playwright.config.ts`:
```
reportSlowTests: { max: 0, threshold: 60001 },
```

**Steps to reproduce:**
1. Create multiple `test` inside one `test.describe()` 
2. Add `test.describe.parallel`
3. Run tests

**Expected behaviour:**
1. Report slow tests feature should check how much time for each  individual `test` takes to pass even if they live in one `test.test.ts` file.

**Actual behaviour:**
 Report slow tests feature checks how much time for ALL `tests` inside test file takes to pass.

-----
**My tests:**

```
test.describe.parallel('open session from dashboard', () => {
  test.use({ storageState: BROWSER_STORAGE_STATE_FILE });

  test('open session through full view tool button', async ({ page }) => {
    CODE HERE
  });

  test('open session through default visible grid', async ({ page }) => {
    CODE HERE
  });

  test('open session through load more button', async ({ page }) => {
    CODE HERE
  });
});

```

**RESULTS:**
![Screen Shot 2021-11-05 at 3 14 48 PM](https://user-images.githubusercontent.com/48032815/140447690-8e44be59-e196-4964-b1e0-f91d16952a12.png)

**Comment by mxschmitt** [comment]
@dgozman this looks as expected right now but the docs seem sometimes mention tests but we mean actual test files if I understood this correctly.

**Comment by olesiaMartushkanova** [comment]
I think, from a user perspective, we should be able to report slow `tests`, not slow `test files` @mxschmitt , @dgozman

**Comment by dgozman** [comment]
@olesiaMartushkanova This information should be actionable. You can split slow test files and improve total run time when running in parallel. If we were to report slow tests, what would the user do? If you have a nice suggestion of what to do with a slow test, we can definitely consider it!

**Comment by olesiaMartushkanova** [comment]
I don't understand then what's the point to have `test.describe.parallel` feature if Playwright still considers that `1 Test file === 1 Test`? @dgozman

**Comment by dgozman** [comment]
> Playwright still considers that `1 Test file === 1 Test`?

I don't think this is the case.

> I don't understand then what's the point to have `test.describe.parallel` feature

Good point that current "slow tests" feature does not work well for `describe.parallel` case! That said, most users do not run with `describe.parallel` so it still makes sense. If you have any ideas about improving "slow tests" in this particular case, please let us know 😄

**Comment by olesiaMartushkanova** [comment]
I do have an idea: is there a way Playwright can use this time to report slow tests ? @dgozman :
![140447690-8e44be59-e196-4964-b1e0-f91d16952a12](https://user-images.githubusercontent.com/48032815/140817193-0d53b9fd-0571-414f-817b-055b1874ccc1.png)

**Comment by dgozman** [comment]
I do not think this is actionable though - there is no obvious way to make a single test faster, without a time-consuming debugging session. Therefore, if we put this information in the prominent place, it won't help that many users.

In the screenshot above, if you split a single file into three separate ones, you'll immediately get faster execution when running with at least three workers. That's something we expect many users will be able to do.

**Comment by bhushantbn** [comment]
@dgozman i have face same problem for slow test using Page Object model.

```TYPESCRIPT
  public async navigateToCheckout() {
    await this.getMenuLink.click();
    await this.productLink.click();
    await this.addToCart.click();
    await this.shoppingCartLink.click();
    await expect(async()=>{
      await this.proceedToCheckOut.click()
      await expect(this.page).toHaveTitle("Checkout")
  }).toPass()
  ```
```TYPESCRIPT
import { test as base, expect, Page } from "@playwright/test";
import { m2d1_Assertions } from "../pages/Assertions/m2d1_Assertions.ts";
import { globalSetup } from "../config/globalSetup.ts";

const test = base.extend<{ page: Page }>({
  page: async ({ page }, use) => {
    const webUrl = process.env.WEB_URL?.split(",")[0];

    if (!webUrl) {
      throw new Error("Please provide the web url");
    }
    await page.goto(webUrl);
    const title = page.title();
    expect(title).not.toContain("error");
    await use(page);
  },
});
 test.only("navigate To Checkout page", async () => {
    await m2d1.navigateToCheckout();
  });
```
I have only execute 1 test using playwright VS Code extension still it becomes slow. then what is the use of parallelism. Please give better idea on this matter.
  
![image](https://github.com/microsoft/playwright/assets/5806834/5cd1c989-5d01-41be-91f5-fa7cb1531ed5)

**Comment by bhushantbn** [comment]
Context:

Playwright Version: 1.44
Operating System: Ubuntu 22
Node.js version: [v18.20.2]
Browser: [All]
