### ISSUE TITLE
[BUG] isplaywrightready repository not accessible

### ISSUE THREAD

**Issue by waldyrious** [microsoft/playwright#1007]
The webpage at https://aslushnikov.github.io/isplaywrightready/ (linked from the README and from the release notes) has a GitHub banner pointing to the [aslushnikov/isplaywrightready](https://github.com/aslushnikov/isplaywrightready) repository, but visiting that URL shows a 404 error. Maybe the repository is set to private? If that's intentional, then the link should be removed from the website.

**Comment by aslushnikov** [comment]
Ah, indeed! Made it public now, thanks for reporting
