### ISSUE TITLE
[Question] Multiple expect in one testcase

### ISSUE THREAD

**Issue by r1kkk** [microsoft/playwright#10086]
Greetings. I wanted to know if you have a solution in playwright to check all expect in one testcase.

E.G: You have four expect, but the first one is failling. I would like to check if number 2,3,4 is green, yet number 1 is red. 
       
Example from JUNIT:

          public void shouldTellIfPrime(){
              Assertions.assertAll(
                      () -> assertTrue(isPrime(2)),
                      () -> assertFalse(isPrime(4))
              );
          }
instead of doing this:

          public void shouldTellIfPrime(){
              Assertions.assertTrue(isPrime(2));
              Assertions.assertFalse(isPrime(4));
          }

I

**Comment by mxschmitt** [comment]
Are you using Playwright in Java? (if so, I'd move to issue over to the Java issue tracker).

**Comment by r1kkk** [comment]
No sorry, it was just a example code for you to understand what i mean. I am using TS & playwright test runner

**Comment by r1kkk** [comment]
My question is: Can i tell playwright to execute all expect cases, even if one of them is failing?

**Comment by mxschmitt** [comment]
Your request sounds similar to https://github.com/microsoft/playwright/issues/7819

**Comment by r1kkk** [comment]
Yep, thats exactly what i meant.
