### ISSUE TITLE
[Feature] Allow access to `sessionStorage` for `about:blank`

### ISSUE THREAD

**Issue by kierangilliam** [microsoft/playwright#10088]
Attempting to access `sessionStorage` or `localStorage` results in the following exception: `Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.` when on `about:blank`. As discussed in other issues, chrome does this for security reasons.

My workflow is splicing code into a page, and _not_ loading a URL:

```javascript
const playwright = require('playwright');
const example = (code = "") => {
  const browser = await playwright.chromium.launch({ headless });
  const ctx = await browser.newContext();
  const page = await ctx.newPage();

  await page.setContent(
    `
      <body>
        <script>
          ${code}
          // localStorage.setItem('uncomment this', 'to reproduce error');
        </script>
      </body>
    `,
    { waitUntil: 'domcontentloaded' },
  );
}
```

My temporary solution is to first run `await page.goto('http://example.com')` before `page.setContent`.
However, I am worried that first navigating to `http://example.com` may result in unintended side effects during testing.

Is there a way to explicitly allow access to `sessionStorage` while on `about:blank`?

**Comment by mxschmitt** [comment]
It's not possible to access the session storage from another host, its a browser security feature so you need to navigate to it beforehand. If you want to navigate to it without side effects, you can e.g. mock the response so you are ending up on the host but no JavaScript gets evaluated. It would something like that:

```javascript
const handler = route => route.fulfill({ body: `<html></html>`, contentType: 'text/html' });
await page.route("*/**", handler);
await page.evaluate(...)
await page.unroute("**/*", handler);
```
