### ISSUE TITLE
[Feature] api to disable rendering

### ISSUE THREAD

**Issue by kapouer** [microsoft/playwright#1008]
Some browser engines have the ability to disable rendering to avoid unnecessary calculations.
Typical use case:
- DOM crawling
- Server-Side-(Pre)Rendering

Chrome headless (no clue about api) has it, and [soon wpewebkit](https://bugs.webkit.org/attachment.cgi?id=390757&action=diff).

**Comment by pavelfeldman** [comment]
Playwright aims at being a testing driver, SSR is not a priority for us at the moment.

Headless Chrome allows manual begin frame (vsync) control, but it only works with special compositing mode and in combination with the virtual time for rafs to work. I would not want to go there. WPE patch you refer to seems to be about media pause upon active dom objects getting suspended, does not really disable rendering.

But I get the idea, we might experiment with triggering the occlusion to prevent rafs and animations. Or we can slow down the headless vsync to generate less animation frames. This is unlikely to happen within the v1 timeframe though.

**Comment by pavelfeldman** [comment]
Closing as per above.
