### ISSUE TITLE
[BUG] `playwright test` cannot work for tweets on macOS without the `--headed` flag for chromium

### ISSUE THREAD

**Issue by imWildCat** [microsoft/playwright#10107]
**Context:**
- Playwright Version: `1.16.3`
- Operating System: `macOS 12.0.1 (21A559)`
- Browser: Chromium
- Extra: including macOS 12.x and 11.x, both M1 and x86.

### System:
 - OS: macOS 11.6
 - Memory: 2.85 GB / 32.00 GB
### Binaries:
 - Node: 16.3.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.7.6 - /usr/local/bin/npm
### Languages:
 - Bash: 5.1.4 - /usr/local/bin/bash

**Code Snippet**

```ts
import { expect, test } from '@playwright/test';

async function delay(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}
test('twitter', async ({page}) => {
  await page.goto('https://twitter.com/dan_abramov/status/1086215004808978434');

  await delay(5000);

  const title = await page.evaluate(() => document.title);
  const text = await page.evaluate(() => document.body.textContent);

  console.log('[trace] title:', title);
  expect(title.startsWith('Dan on Twitter')).toBeTruthy();
  console.log('[trace] text:', text);
});
```

**Describe the bug**

`yarn playwright test ./src/t.spec.ts --browser chromium` will fail. However, `yarn playwright test ./src/t.spec.ts --browser webkit --headed` can pass.

I also tested other browsers (webkit, firefox). They can work.

Also tested both headless / non-headless on Ubuntu 20.04 (amd64), it worked well.

**Comment by mxschmitt** [comment]
You could record a trace in your case to find out the reason why its not working or follow the other debugging methods: https://playwright.dev/docs/debug

The main reason why its failing is that Twitter will say: "this browser is not supported" see here:

![twitter](https://user-images.githubusercontent.com/17984549/140653294-3707c865-ee93-4343-9a37-020df4c87879.png)

With using the correct user-agent it works, see the following config:

```
// playwright.config.ts
import { PlaywrightTestConfig, devices } from '@playwright/test';
import path from 'path';

// Reference: https://playwright.dev/docs/test-configuration
const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'Mobile Safari',
      use: devices['Desktop Firefox'],
    },
    {
      name: 'Mobile Safari',
      use: devices['iPhone 12 Pro Max'],
    },
  ],
};
export default config;

```

**Comment by mxschmitt** [comment]
Closing since its answered. Please refer to traces / debugging in the future.
