### ISSUE TITLE
[Feature] set Proxy per request

### ISSUE THREAD

**Issue by eliavm** [microsoft/playwright#10109]
Currently one can set proxy per browser or per context. It is very useful to be able to route only some of the requests during a page load via a proxy. Proxies are expensive in terms of both speed and cost so the usage should be limited to minimum. Been able to set rules for specific requests may create greater flexibility for developers.

**Comment by mxschmitt** [comment]
You can make the requests on your own and respond with its Response to it using Playwright's network interception. So you register a network handler via context.route and then execute the requests yourself see here: https://playwright.dev/docs/network#handle-requests

**Comment by viponedream** [comment]
> Currently one can set proxy per browser or per context. It is very useful to be able to route only some of the requests during a page load via a proxy. Proxies are expensive in terms of both speed and cost so the usage should be limited to minimum. Been able to set rules for specific requests may create greater flexibility for developers.

Do you find the solutions yet?

**Comment by vkruoso** [comment]
For this purpose you can simply bypass some URLs, for instance:

```
proxy: {
  server: `http://localhost:8888`,
  bypass: '*.gvt1.com;avatars.githubusercontent.com;cdnjs.cloudflare.com',
}
```

If you want to have a finer control, probably the best solution is to use the `context.route` as stated above.
