### ISSUE TITLE
[REGRESSION]: 

### ISSUE THREAD

**Issue by hugomrdias** [microsoft/playwright#1010]
**Context:**
- GOOD Playwright Version: 0.10.0
- BAD Playwright Version: 0.11.0
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // in 0.10.0 i could do this to create a normal or incognito context
  if (this.options.incognito) {
      this.context = await this.browser.newContext();
  } else {
      this.context = this.browser.defaultContext();
  } 
  // in 0.11.0 it always opens 2 windows and the one controlled is always in incognito
  this.page = await this.browser.newPage();
})();
```

**Describe the bug**
In 0.11.0 how can i get a non-incognito page ? Check the Snippet above for an example.

I ran into this in the context of creating this https://github.com/hugomrdias/playwright-test a browser unit tests runner. 

Update: extension handling also not working https://github.com/hugomrdias/playwright-test/blob/v0.2.0/src/runner.js#L84-L87

**Comment by pavelfeldman** [comment]
Please refer to [release notes](https://github.com/microsoft/playwright/releases) that describes `browser.launchPersistent` while we are updating the docs.

**Comment by hugomrdias** [comment]
@PavelBansky thank you for the answer go it to work, but still have problems with extension handling.

from browser.launchPersistent how do i get a browser instance so i can
```js
const targets = await this.browser.targets();
const backgroundPageTarget = targets.find(target => target.type() === 'background_page');
```
?

i can do it with browser.launch but then im in incognito mode which makes it harder/impossible to open the background_page devtool window programmatically.

**Comment by 12masta** [comment]
@hugomrdias did you find a way to handle it?
