### ISSUE TITLE
[Feature] async test.attach({…}) API that Automagically Handles Temporary Paths

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10113]
This is a follow up to [this Slack thread](https://playwright.slack.com/archives/C01AG7QGW2F/p1636232194179300?thread_ts=1636148004.173400&cid=C01AG7QGW2F). Please read that message for background on how I messed up (hehe) and why this proposal is useful (IMO)! We're in the middle of consolidating UI tests and API tests into @playwright/test that used to be in a mix of JS test runner and Python pytest. 

I'd like to propose adding:

```
test.attach: ({ name: string; contentType: string; path?: string; body?: … }, { move: boolean = False }) => Promise<void>;
```

so it can be explicitly awaited in a test, and the Playwright Test Runner internally can (1) confirm the intended attachment exists, and (2) copies (by default or moves, explicit setting) the attachment to a location that the reporters are guaranteed to have access to even after the test finishes and potentially cleans up temporary directories.

This would help ensure issues with attachments, which might only be looked at when tests suddenly start failing, are surfaced very early in authoring tests…not just when you debug a failing test months later!

The current implementation and reporters swallow errors around attachments and requires knowing about `testInfo.createTestOutput` and combining it with `testInfo.attachments.push`, but even with that there is room to accidentally mess up.

Let me know your thoughts! I'd be happy to contribute this or iterate on an alternative…even if it's just adding a warning log in the HTML Reporter about using `testInfo.testOutput` in the case of files not found! Ultimately, I'd like to surface issues with attachments as soon as possible to the user to ensure they are in fact there when the user thinks they will be!

🎉 Thanks, as always, for these awesome tools! We ❤️  the new HTML Report…you don't want to see what our legacy reports look like! 😄

**Comment by rwoll** [comment]
From [Slack message](https://playwright.slack.com/archives/C01AG7QGW2F/p1636242586180300?thread_ts=1636148004.173400&cid=C01AG7QGW2F):

>  @pavelfeldman  22 minutes ago
> this all makes sense, we can make it a method

so I'll try to prioritize working on an MR this week! 🎉

**Comment by aslushnikov** [comment]
> so I'll try to prioritize working on an MR this week! 🎉

@rwoll awesome, I'll assign you then!
