### ISSUE TITLE
[Question] Best way to structure interdependent tests

### ISSUE THREAD

**Issue by TroutZen** [microsoft/playwright#10114]
Hi there,
Enjoying playwright, so thanks for all the hard work! I have a scenario that I wanted feedback on.

I have a feature and want to test various workflows in that feature. I want isolation where needed, but don't want to repeat myself if necessary. Supposed I have a `page` class called `FeaturePage` that abstracts a lot of feature interactions.

`feature-page.ts`
```
class FeaturePage {
  page: Page;

  constructor(page) {
    this.page = page;
  }

  doThingA() {}
  doThingB() {}
  doThingC() {}
}
```

Let's also say that thing `C` depends on `B` depends on `A`. If I were to test these in isolation it would look something like.

```
test('Does thing A', ({ page }) => {
  const featurePage = new FeaturePage(page);
  await featurePage.doThingA();
});

test('Does thing B', ({ page }) => {
  const featurePage = new FeaturePage(page);
  await featurePage.doThingA();
  await featurePage.doThingB();
});

test('Does thing C', ({ page }) => {
  const featurePage = new FeaturePage(page);
  await featurePage.doThingA();
  await featurePage.doThingB();
  await featurePage.doThingC();
});
```

Note that each step that I want to test in isolation expressed a dependency and requires a repeating of the things tested in another isolated test case. I could also do a a serial test.

```
test.describe.serial('FeaturePage', () => {
  let page;
  let featurePage;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    featurePage = new FeaturePage(page);
  });

  test('Does thing A', ({ page }) => {
    await featurePage.doThingA();
  });
  
  test('Does thing B', ({ page }) => {
    await featurePage.doThingB();
  });
  
  test('Does thing C', ({ page }) => {
    await featurePage.doThingC();
  });
})
```

These tests are interdependent, so I lose isolation. What I like is that dependent flows don't need to be repeated in other tests. I know that `serial` mode is not recommended, but I find myself with a lot of experiences that I am testing that have dependencies like this, where serial seems a logical fit.

Is this just about finding the right balance or are there other suggestions for handling this dependency pattern? Do you tend to prefer isolation and repetition vs. no isolation and no repetition (serial)?

**Comment by mxschmitt** [comment]
Both scenarios are valid solutions. You could also consider using test isolation but use `test.step` inside of it: https://playwright.dev/docs/api/class-test#test-step

I personally would use a single test with multiple tests steps there.

**Comment by TroutZen** [comment]
@mxschmitt - Thanks for the suggestion, I like that approach as well!
