### ISSUE TITLE
[BUG] Documentation example does not work

### ISSUE THREAD

**Issue by BrunoQuaresma** [microsoft/playwright#10119]
I tried to run the following doc example and it didn't work. Here is the related documentation section https://playwright.dev/docs/verification#page-errors

```
await page.goto('data:text/html,<script>throw new Error("Test")</script>');
```

<img width="1282" alt="Screen Shot 2021-11-07 at 20 10 15" src="https://user-images.githubusercontent.com/3165839/140665384-2f5bab57-6b0a-4d00-8116-6d365d78b1dc.png">

**Comment by mxschmitt** [comment]
What exactly does not work there? In this example you register an event handler for page errors and then navigate to a page which throws such an example page error.

**Comment by BrunoQuaresma** [comment]
My bad, the script is not executed. You can change the throw by an alert to reproduce.

**Comment by mxschmitt** [comment]
Dialogs are automatically dismissed if there is no event listener attached, see here: https://playwright.dev/docs/api/class-dialog

I guess thats what you mean that the script is not getting executed?

```typescript
// @ts-check
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on('dialog', dialog => {
      console.log("Dialog incoming", dialog.message())
      dialog.accept()
    });

    // Navigate to a page with an exception.
    await page.goto('data:text/html,<script>alert("Test")</script>');
    await browser.close();
  }
})();
```
