### ISSUE TITLE
[Question] Screenshot and video reporter create subfolders?

### ISSUE THREAD

**Issue by rvanbrakelisah** [microsoft/playwright#10125]
Goodday,

First of all I want to mention we are very happy wih using Playwright and its features!

On default when an outputDir is provided the screenshot and video reporter will create a subfolder in the test-results folder where the video and screenshot files are stored.
Is there any posibility to not create this subfolder?

This creates some problems for us in our process.

Instead of: 

> test-results
>> src.app-shows-menu
>>> screenshot.jpg

We would like:
> test-results
>> src.app-shows-menu.jpg

Thanks in advance!

**Comment by aslushnikov** [comment]
> This creates some problems for us in our process.

@rvanbrakelisah out of curiosity, what kind of issues?

> Is there any posibility to not create this subfolder?

Not at the moment, but you can post-process the output folder however you like!
