### ISSUE TITLE
[Feature] Add selector attribute to Locators

### ISSUE THREAD

**Issue by kumaraditya303** [microsoft/playwright#10126]
When passing an instance of locator, I want to get the selector from the locator, hence a getter attribute would be great.

**Comment by pavelfeldman** [comment]
What is your use case?

**Comment by kumaraditya303** [comment]
I want to create locator from a locator by passing an instance and log the current locator selector for introspection afterwards.

**Comment by TimeInvestor** [comment]
@kumaraditya303 do you mean this #10178

**Comment by pavelfeldman** [comment]
The locator is more than just a selector, today it is a frame as well, so exposing selector becomes too much of a commitment for us. We need a real world use case to consider it. It looks like your use case is better addressed via `toString` and `[(util.inspect as any).custom]()`.
