### ISSUE TITLE
[Question] Playwright reporters with Jest runner

### ISSUE THREAD

**Issue by lViardMi** [microsoft/playwright#10131]
Hi,

I use [Jest ](https://github.com/playwright-community/jest-playwright) with playwright in my project. We also use [Jest reporter](https://github.com/Hazyzh/jest-html-reporters).
I wanted to know if it's possible to use the [Playwright reporter](https://github.com/microsoft/playwright/releases/tag/v1.16.0) with the Jest runner.
I don't think it's possible because Jest use "it(...)" for reporter messages but I wanted to be sure.

Kind regards

**Comment by aslushnikov** [comment]
Nope, its not possible. Please use Playwright Test instead of jest for this: https://playwright.dev/docs/intro#installation
