### ISSUE TITLE
[BUG]Footer not displayed

### ISSUE THREAD

**Issue by Ashok8388** [microsoft/playwright#10130]
**Context:**
- Playwright Version: 1.16
- Operating System: Windows 10
- Node.js version: 14.16.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment].

Hi,
I am using latest version of playwright test . I am unable to find the footer when the display resolution of my laptop is 150[recommended ] but when I change the display resolution to 125 I am able to see the footer. Does playwright work on specific resolution of laptop? Attaching screenshots with different display resolution. And also I see when display resolution is set to 125 white space in the right side? Please let me on this if I need to do something with configuration. Setting it to 125 is just a work around I believe. 

![displayresolution150](https://user-images.githubusercontent.com/64917404/140767274-42a6cd63-becf-46bd-9902-221384b02172.PNG)
![Inkedfooter150_LI](https://user-images.githubusercontent.com/64917404/140767984-c4ca1f7f-3b61-40fe-9dfd-94b66fc14a3f.jpg)
![Inkedfooter125_LI](https://user-images.githubusercontent.com/64917404/140768007-ff4ac371-eb0c-4e39-a6a9-9778c4fb634d.jpg)

![screenresolution125](https://user-images.githubusercontent.com/64917404/140767294-a87cacb0-11d1-4d17-9bd6-03e62129b086.PNG)

Regards,
Ashok

**Comment by aslushnikov** [comment]
> Does playwright work on specific resolution of laptop?

@Ashok8388  Playwright works on all of them! 

> I am unable to find the footer when the display resolution of my laptop is 150[recommended ] but when I change the display resolution to 125 I am able to see the footer

I don't follow - do you not see it visually, or is it missing in page's DOM altogether?

**Comment by Ashok8388** [comment]
It is available in DOM but visually cannot be seen. Only after I change Display resolution of my laptop to 125 I can see it. Codegen also cannot identify it. Here I had to set screen resolution to minimum also to see if its hidden or truncated but it dint help. Only work around i could do is change the display resolution of my laptop to 125%. Kindly help

**Comment by aslushnikov** [comment]
@Ashok8388 It looks like you need to force viewport DPI for the browser. Can you share your Playwright configuration file?

**Comment by Ashok8388** [comment]
module.exports = {
  testDir: './e2e/scripts/',
  use: {
    headless: false,
    launchOptions: {
    viewport: { width: 400, height: 400 },
    screenshot:"only-on-failure",
     
      slowMo: 100,
 
    },
    testMatch: ["lead.spec.js"],
    retries: 0,
    // // Artifacts
    // screenshot: 'only-on-failure',
    // video: 'retry-with-video'
  },
  timeout: 100000,
 
  reporter: [
    ['list'],
   ['json', { outputFile: 'results.json' }]
  ],
 
  projects: [
    {
      name: 'Chromium',
      use: {
        // Configure the browser to use.
        browserName: 'chromium',
 
        // Any Chromium-specific options.
        // viewport: { width: 600, height: 800 },
      },
    },
 
  ],
};

**Comment by aslushnikov** [comment]
Try using ` deviceScaleFactor: 2,` in the `use:{}` block:

```
module.exports = {
  testDir: './e2e/scripts/',
  use: {
    headless: false,
    deviceScaleFactor: 2,
    launchOptions: {
      viewport: { width: 400, height: 400 },
      screenshot:"only-on-failure",
      slowMo: 100,
 
    },
    testMatch: ["lead.spec.js"],
    retries: 0,
    // // Artifacts
    // screenshot: 'only-on-failure',
    // video: 'retry-with-video'
  },
  timeout: 100000,
 
  reporter: [
    ['list'],
   ['json', { outputFile: 'results.json' }]
  ],
 
  projects: [
    {
      name: 'Chromium',
      use: {
        // Configure the browser to use.
        browserName: 'chromium',
 
        // Any Chromium-specific options.
        // viewport: { width: 600, height: 800 },
      },
    },
 
  ],
};
```

**Comment by Ashok8388** [comment]
@aslushnikov - Nope this is not working.

**Comment by aslushnikov** [comment]
What's not working? Can you scroll to the footer? Also, if the footer is not shown, it means it won't be shown for certain users - so that's also a bug on the website.

**Comment by Ashok8388** [comment]
I cannot see the footer after I add deviceScaleFactor: 2,. Same issue .

Website you mean the application issue here?

Also as a work around i have set display resolution to 125 . I see footer but when i try to click on it or check if its visible. It is not identifying the element. It tries for several times and throw out an error. Following is what i get

 retrying click action, attempt #184
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and 
stable
      scrolling into view if needed   
      done scrolling
      checking that element receives pointer events at (1151.35,684)        
      <button type="button" class="sap-crm-btn sap-crm-btn--md…>…</button> from <span _ngcontent-rpq-c1="" id="crm-create-view">…</span> subtree intercepts pointer events

**Comment by aslushnikov** [comment]
> Website you mean the application issue here?

Yeah, something we can use to try reproduce this.

**Comment by Ashok8388** [comment]
Thanks for that. I Shall check with team internally here and revert. But is there any way we can get into call and I can demo it to you? I am not suppose to record video and send as this are new screens which are not released yet.
Let me know if there is any medium?

**Comment by aslushnikov** [comment]
> But is there any way we can get into call and I can demo it to you? 

@Ashok8388 we don't have this kind of support.

**Comment by Ashok8388** [comment]
OK . I Shall check with team here and revert

**Comment by MsLolita** [comment]
And how did someone fix this bug?

**Comment by sontakkevishal** [comment]
Facing same issue, how to fix it?

**Comment by sontakkevishal** [comment]
Hi, facing exactly the same issue and same error on click event of button.
How to fix it?

**Comment by bineet-exact** [comment]
Hi,
I was facing same issue with the fixed footer not displaying(Playwright .Net). But the same was displaying when using Selenium, for the same page.

Workaround is to not use ViewportSize. Changed my code from:
_context = await _browser.NewContextAsync(new BrowserNewContextOptions { StorageStatePath = "state.json", ViewportSize = **new ViewportSize() { Width = screenWidth, Height = screenHeight }** });

to
_context = await _browser.NewContextAsync(new BrowserNewContextOptions { StorageStatePath = "state.json"});

Though by not using it, I cannot set the browser's length and width.

**Comment by xiang-deng** [comment]
@aslushnikov I faced the same issue and one way to reproduce is opening the shopping cart on https://www.instacart.com/, the checkout button won't appear with viewport set, but it exists in the dom tree. As mentioned in other comments remove the viewport size constraint and let it use the default 1280*720 size would work.

**Comment by hinacerta** [comment]
I am also facing the same issue, tried with the given conversation but could not resolve it. Any solution?

**Comment by rajanigupta1980** [comment]
I am facing the same issue. Did anyone resolve this? please help

**Comment by rajanigupta1980** [comment]
> o facing the same issue, tried with the given conversation but could not resolve it. Any solution?

did you get the solution?

**Comment by rajanigupta1980** [comment]
> Hi, facing exactly the same issue and same error on click event of button. How to fix it?

did it resolve?

**Comment by NishaK99** [comment]
I am also facing same issue. Footer is not display while executing script using playwright. I have tried Chrome, Chromium, Webkit all browser options. Kindly help me with solution.

<img width="957" alt="Image" src="https://github.com/user-attachments/assets/c1fa34b4-91a9-4cd6-92b7-9b6ed7ae56e5" />

**Comment by cozyloon** [comment]
> I am also facing same issue. Footer is not display while executing script using playwright. I have tried Chrome, Chromium, Webkit all browser options. Kindly help me with solution.
> 
> <img width="957" alt="Image" src="https://github.com/user-attachments/assets/c1fa34b4-91a9-4cd6-92b7-9b6ed7ae56e5" />

Did you able to fix this? Same issue is here.

**Comment by CHN-STUDENT** [comment]
I get same issue when using playwright,could someone give me some advice?

Update: i use gpt tell me how to set browser dpi by settings. It seems work

```
    def setup_browser(self):
        """初始化浏览器 - 专门解决高分屏DPI缩放问题"""
        if self.browser is None:
            try:
                self.playwright = sync_playwright().start()

                # 关键：强制DPI缩放设置的浏览器启动参数
                launch_args = [
                    '--start-maximized',
                    '--disable-web-security',

                    # 🔑 核心DPI缩放修复参数
                    '--force-device-scale-factor=1',  # 强制设备缩放因子为1，忽略系统缩放
                    '--high-dpi-support=1',  # 启用高DPI支持
                    '--force-color-profile=srgb',  # 强制颜色配置文件
                    '--disable-features=VizDisplayCompositor',  # 禁用可能导致缩放问题的功能

                    # 🔑 Windows特定的DPI处理
                    '--disable-gpu-sandbox',  # 禁用GPU沙盒
                    '--disable-software-rasterizer',  # 禁用软件光栅化
                    '--disable-background-timer-throttling',  # 禁用后台定时器节流

                    # 🔑 强制屏幕分辨率（覆盖系统设置）
                    '--window-size=1920,1080',  # 强制窗口大小
                    '--screen-resolution=1920x1080',  # 强制屏幕分辨率

                    # 🔑 禁用可能干扰的缩放功能
                    '--disable-dev-shm-usage',
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                ]

                self.browser = self.playwright.chromium.launch(
                    headless=self.config.get('headless', False),
                    args=launch_args)

                # 🔑 创建上下文时明确设置设备参数（覆盖系统DPI设置）
                context_options = {
                    # 强制视口大小（不受系统缩放影响）
                    'viewport': {
                        'width': 1920,  # 明确指定，不使用系统检测值
                        'height': 1080
                    },
                    # 强制屏幕分辨率（覆盖系统值）
                    'screen': {
                        'width': 1920,
                        'height': 1080
                    },
                    # 🔑 关键：强制设备缩放因子为1（忽略Windows的125%/150%缩放）
                    'device_scale_factor':
                    1,

                    # 其他设置
                    'ignore_https_errors':
                    True,
                    'java_script_enabled':
                    True,

                    # 🔑 用户代理（确保与标准桌面浏览器一致）
                    'user_agent':
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36'
                }

                self.context = self.browser.new_context(**context_options)
                self.page = self.context.new_page()

                # 🔑 页面加载后立即设置视口（双重保险）
                self.page.set_viewport_size({'width': 1920, 'height': 1080})

                # 设置页面超时
                self.page.set_default_timeout(30000)

                # 🔑 注入CSS来确保页脚可见（解决缩放导致的页脚隐藏问题）
                self.page.add_init_script("""
                    // 强制重置CSS缩放和变换
                    document.addEventListener('DOMContentLoaded', function() {
                        // 重置所有可能的缩放设置
                        document.body.style.zoom = '1';
                        document.body.style.transform = 'scale(1)';
                        document.documentElement.style.zoom = '1';
                        document.documentElement.style.transform = 'scale(1)';

                        // 确保页脚等底部元素可见
                        const style = document.createElement('style');
                        style.textContent = `
                            * {
                                box-sizing: border-box !important;
                            }
                            body, html {
                                zoom: 1 !important;
                                transform: scale(1) !important;
                                min-height: 100vh !important;
                            }
                            /* 确保页脚和分页组件可见 */
                            footer, .pagination, .page-footer, .btn-next, .page-nav {
                                visibility: visible !important;
                                display: block !important;
                                opacity: 1 !important;
                                position: relative !important;
                                z-index: 999 !important;
                            }
                        `;
                        document.head.appendChild(style);
                    });
                """)

                self.logger.info("🎯 浏览器初始化完成 - 高DPI缩放修复已应用")
                self.logger.info(f"   - 视口: 1920x1080 (强制)")
                self.logger.info(f"   - 缩放因子: 1 (忽略系统缩放)")
                self.logger.info(f"   - DPI修复: 已启用")

            except Exception as e:
                self.logger.error(f"浏览器初始化失败: {e}")
                raise

```
