### ISSUE TITLE
[Feature] [Internal Tooling] Add command to preview current checkout as Playwright Site

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10149]
It would be nice if I could run some npm command in a checkout of this repo (microsoft/playwright), that would preview the playwright.dev site to debug doc syntax in realtime.

When adding to the markdown files, I'm never sure if I have the Playwright-specific syntax correct (`:::note`, references to other methods, etc.), so it would be nice to get a preview of the site as quickly and easily as:

```
$ npm run preview-docs
```

from within the main repo without independently setting up and learning the workflow described in https://github.com/microsoft/playwright.dev.

**Comment by pavelfeldman** [comment]
This is a tricky one, there is no preview without the workflow in playwright.dev...

**Comment by aslushnikov** [comment]
Yeah It'd be nice, but it's not pressing that much the team yet. I'd close this for now since there's no plan to advance here.

**Comment by rwoll** [comment]
Sounds good! Thanks for the response! This was more for external contributors like myself 😄 but as is, I've made do and likely not worth changing unless it was a quick change (but doesn't sound like it is).
