### ISSUE TITLE
[Feature] HTML Reporter Time-Series

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10158]
We're moving more and more of our testing into @playwright/test—and not just UI tests! It would be great to have a reporter/viewer that was aware of multiple HTML Reports and Test Runs, and get an overview over time of pass/fail/flake (like @aslushnikov's Flakiness 2 dashboard).

For instance, it'd sweet to be able to do something like:

```
npx playwright show-report /directory/to/serveral/report/files
```

Where that dir has a bunch or reports in it from that past hour/days/weeks/etc.

We have some e2e suites that run 4 times an hour, while others are hourly/daily, so seeing some timeseries data would be great (test speed, passes/fails, etc.)

Please reach out as I'd love to talk more about what would be useful for us to see (along with how we'd deploy such a thing in our companies testing environments for viewing in the browser)!

**Comment by rwoll** [comment]
Related https://github.com/microsoft/playwright/issues/10437

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
