### ISSUE TITLE
How to close popup window ?

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#10152]
### Your question

![QQ图片20211108011715](https://user-images.githubusercontent.com/16624529/140654927-eaf6f030-e367-4931-b2f7-e88fa1c446e5.png)

 page.on("popup",  self.handle_popup)

it doesn't work.

**Comment by aslushnikov** [comment]
> any idea how to catch it and close it with own function?

@viponedream Here are the python docs for this: https://playwright.dev/python/docs/multi-pages/#handling-popups

**Comment by bogdan192** [comment]
Both links are dead
