### ISSUE TITLE
[REGRESSION]: webkit tests fails on travis

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#1016]
**Context:**
- GOOD Playwright Version: [0.10.0]
- BAD Playwright Version: [0.11.0]
- Operating System: [Linux]
- Extra: [Travis]

**Code Snippet**

```javascript
// this a Jest test
test('should close webkit - playwright issue v0.11.0', async (): Promise<void> => {
    // Given
    const browser = await webkit.launch({ headless: false });
    const browserContext = await browser.newContext({ viewport: null });
    const page = await browserContext.newPage();
    await page.goto('https://google.com');

    // When
    await sleep(1000);
    const previousConnectedStatus = browser.isConnected();
    await browser.close();
    await sleep(1000);
    const afterCloseConnectedStatus = browser.isConnected();

    // Then
    expect(browser).toBeDefined();
    expect(previousConnectedStatus).toBe(true);
    expect(afterCloseConnectedStatus).toBe(false);
  });
```

**Describe the bug**

Error message, for all tests that launch a webkit browser, is:

```sh
Failed to launch browser!
    TROUBLESHOOTING: https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md
      at onClose (node_modules/playwright-core/lib/server/processLauncher.js:139:20)
      at Interface.helper_1.helper.addEventListener (node_modules/playwright-core/lib/server/processLauncher.js:132:65)
```

For more details, you can look at:
[travis build](https://travis-ci.org/hdorgeval/playwright-controller/jobs/650670348)
[repo](https://github.com/hdorgeval/playwright-controller)
[source test file](https://github.com/hdorgeval/playwright-controller/blob/master/src/controller/tests/close/close.test.ts)

Thank you for your help.

**Comment by aslushnikov** [comment]
Thanks! New webkit requires `libvpx5` to be installed in the environment; we've updated our `.travis.yml`

**Comment by hdorgeval** [comment]
Hi @aslushnikov , thank you very much for having solved this so fast 🥇  👍 
It works now fine on my side and travis build is green.
