### ISSUE TITLE
[Feature] Reporters Should Include Error Message or Indication of Attachment Failure

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10166]
See https://github.com/microsoft/playwright/pull/10121#issuecomment-963798669.

If a reporter can't attach a file (e.g. it doesn't exist, etc.), we should make it more obvious in the reporter output. Currently (at least in the HTML Reporter) we have a silent catch.

cc: @dgozman

**Comment by aslushnikov** [comment]
(speculatively assigning to Dmitry and scheduling for the next release)
