### ISSUE TITLE
[Question] How to reduce size of Docker image for Playwright ( focal )

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#10168]
First of all, thanks for the awesome tool. Playwright has made life so much easier for the JS devs and testing of JS/SPA apps in general.

One thing, that I would like to ask is how to reduce the size of the Docker image that gets created using ` mcr.microsoft.com/playwright:focal` as the base image.

I have the following dependencies in my  `package.json` file, 
```

"devDependencies": {
    "@cucumber/cucumber": "^7.0.0",
    "@cucumber/pretty-formatter": "^1.0.0-alpha.0",
    "chai": "^4.2.0",
    "cucumber-html-reporter": "^5.3.0",
    "playwright": "^1.16.2"
  },
  "dependencies": {
    "rimraf": "^3.0.2"
  }
```
And I have a simple Dockerfile, 

```
FROM mcr.microsoft.com/playwright:focal
USER root
WORKDIR /automation

COPY package.json ./
RUN npm install

COPY . ./
RUN chown -R pwuser /automation
USER pwuser
CMD [ "npm","run","test" ]
```
However, if I do a `docker images` and list the built image, then the size of the image shows as `1.94 GB` which I think is too much.

<img width="903" alt="Screenshot 2021-11-09 at 10 50 46 AM" src="https://user-images.githubusercontent.com/8002297/140867137-df6d6304-8412-47b7-a28f-963ee1ebb144.png">

This works fine on a local machine with a lot of HDD and no issues with space, however in ci-cd systems, where there are main-slave configs, and the slaves do not have much space, this creates issues for us. 

Is there any way to optimise the image, so that the image size can be managed better.

**Comment by aslushnikov** [comment]
@zac11 The first thing you can do is uninstall Python that is bundled with our image:

https://github.com/microsoft/playwright/blob/4e90eb9406b4a2f3e666a5f81071d7f1b0700947/utils/docker/Dockerfile.focal#L22-L26

This will shave off ~600MB from the image size. 

Next, do you run your tests in Chrome, Firefox and WebKit? If not, you can drop some of the browsers you don't use.

**Comment by aslushnikov** [comment]
@zac11 one good alternative is to actually build image from scratch. A minimal image would look like this:

```
FROM ubuntu:focal

# Install node16
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs
```

You can then clone your app, and run `npx playwright install --with-deps chromium` to install only chromium and its dependnices.

**Comment by itamud** [comment]
> 

@aslushnikov I'm following your suggestion to build my own docker image, I found that in the `npx playwright install --with-deps chromium` step, Playwright will install all those dependencies here, right?
https://github.com/microsoft/playwright/blob/0f359b9840df7a9e2af5da3624899f42abcb2e3c/packages/playwright-core/src/utils/nativeDeps.ts#L229-L270
But in my case, I just need to run chromium in headless mode. Could you tell me which of the dependencies are **_required_** to run chromium in headless only on Ubuntu 20.04, please?

And by the way, is there any plan to publish an official docker image on Alpine Linux?

**Comment by aslushnikov** [comment]
@itamud it depends on your needs. For example, we install lots of fonts for a beautiful web content rendering. Do you need these? Maybe you can drop them.

To get only the absolutely necessary requirements, you can run `ldd` against all the binaries inside `chromium` folder. This way you'll get the list of missing `.so` files that are absolutely needed to run the binary.

**Comment by usersina** [comment]
I was facing the exact same problem, I just wanted to automate some thing in headless mode on a server without any of the testing stuff and here's how I did it.

First, since playwright is only officially supported by ubuntu, I had to create a custom Docker image as follows:

`node-ubuntu` Dockerfile:
```Dockerfile
FROM ubuntu:20.04
RUN apt-get update -y && \
    apt-get install -y curl && \
    # Add nodejs to repo
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \ 
    # Add yarn to repo
    curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list && \
    # Cleanup packages and update the repos
    apt-get remove -y --purge cmdtest && \
    apt-get update && \
    # Install the packages
    apt-get install -y nodejs && \
    apt-get install -y --no-install-recommends yarn && \
    # Smoke tests
    node --version && \
    npm --version && \
    yarn --version && \
    # remove useless files from the current layer
    rm -rf /var/lib/apt/lists/* && \
    rm -rf /var/lib/apt/lists.d/* && \
    apt-get autoremove && \
    apt-get clean && \
    apt-get autoclean

CMD ["node"]
```

Ofc you then have to build the image
```BASH
docker build -t node-ubuntu:16 .
```

With that done, here's an example that's actually using the image in a NodeJS app
```Dockerfile
FROM node-ubuntu:16
WORKDIR /usr/src/app

COPY package.json yarn.lock ./
RUN yarn install && \
    npx playwright install --with-deps firefox # <========== This right here is what is not supported by the node image

COPY . .
CMD [ "yarn", "start" ]
```

I still don't understand why [dockerhub's node image](https://hub.docker.com/_/node) doesn't have an official ubuntu image. The image is not even that big in size, it's merely an `80 MiB` when compressed and node works great on ubuntu...

You can even lower the image size further to approx. `60MiB` when compressed but that makes the `node-ubuntu` Dockerfile bigger (ironically)
<details>
  <summary>A scarier node-ubuntu Dockerfile</summary>

Please note that this is mostly copy-pasted from the [official node's slim version,](https://github.com/nodejs/docker-node/blob/6e8f32de3f620833e563e9f2b427d50055783801/16/bullseye-slim/Dockerfile) but I did add an execute permission to the `docker-entrypoint.sh` file since I kept getting errors in a pipeline.
  
  ```Dockerfile
FROM ubuntu:20.04

RUN groupadd --gid 1000 node \
    && useradd --uid 1000 --gid node --shell /bin/bash --create-home node

ENV NODE_VERSION 16.14.2

RUN ARCH= && dpkgArch="$(dpkg --print-architecture)" \
    && case "${dpkgArch##*-}" in \
    amd64) ARCH='x64';; \
    ppc64el) ARCH='ppc64le';; \
    s390x) ARCH='s390x';; \
    arm64) ARCH='arm64';; \
    armhf) ARCH='armv7l';; \
    i386) ARCH='x86';; \
    *) echo "unsupported architecture"; exit 1 ;; \
    esac \
    && set -ex \
    # libatomic1 for arm
    && apt-get update && apt-get install -y ca-certificates curl wget gnupg dirmngr xz-utils libatomic1 --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && for key in \
    4ED778F539E3634C779C87C6D7062848A1AB005C \
    141F07595B7B3FFE74309A937405533BE57C7D57 \
    94AE36675C464D64BAFA68DD7434390BDBE9B9C5 \
    74F12602B6F1C4E913FAA37AD3A89613643B6201 \
    71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 \
    8FCCA13FEF1D0C2E91008E09770F7A9A5AE15600 \
    C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 \
    C82FA3AE1CBEDC6BE46B9360C43CEC45C17AB93C \
    DD8F2338BAE7501E3DD5AC78C273792F7D83545D \
    A48C2BEE680E841632CD4E44F07496B3EB3C1762 \
    108F52B48DB57BB0CC439B2997B01419BD92F80A \
    B9E2F5981AA6E0CD28160D9FF13993A75599653C \
    ; do \
    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
    done \
    && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/node-v$NODE_VERSION-linux-$ARCH.tar.xz" \
    && curl -fsSLO --compressed "https://nodejs.org/dist/v$NODE_VERSION/SHASUMS256.txt.asc" \
    && gpg --batch --decrypt --output SHASUMS256.txt SHASUMS256.txt.asc \
    && grep " node-v$NODE_VERSION-linux-$ARCH.tar.xz\$" SHASUMS256.txt | sha256sum -c - \
    && tar -xJf "node-v$NODE_VERSION-linux-$ARCH.tar.xz" -C /usr/local --strip-components=1 --no-same-owner \
    && rm "node-v$NODE_VERSION-linux-$ARCH.tar.xz" SHASUMS256.txt.asc SHASUMS256.txt \
    && apt-mark auto '.*' > /dev/null \
    && find /usr/local -type f -executable -exec ldd '{}' ';' \
    | awk '/=>/ { print $(NF-1) }' \
    | sort -u \
    | xargs -r dpkg-query --search \
    | cut -d: -f1 \
    | sort -u \
    | xargs -r apt-mark manual \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    && ln -s /usr/local/bin/node /usr/local/bin/nodejs \
    # smoke tests
    && node --version \
    && npm --version

ENV YARN_VERSION 1.22.18

RUN set -ex \
    && savedAptMark="$(apt-mark showmanual)" \
    && apt-get update && apt-get install -y ca-certificates curl wget gnupg dirmngr --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && for key in \
    6A010C5166006599AA17F08146C2130DFD2497F5 \
    ; do \
    gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys "$key" || \
    gpg --batch --keyserver keyserver.ubuntu.com --recv-keys "$key" ; \
    done \
    && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz" \
    && curl -fsSLO --compressed "https://yarnpkg.com/downloads/$YARN_VERSION/yarn-v$YARN_VERSION.tar.gz.asc" \
    && gpg --batch --verify yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
    && mkdir -p /opt \
    && tar -xzf yarn-v$YARN_VERSION.tar.gz -C /opt/ \
    && ln -s /opt/yarn-v$YARN_VERSION/bin/yarn /usr/local/bin/yarn \
    && ln -s /opt/yarn-v$YARN_VERSION/bin/yarnpkg /usr/local/bin/yarnpkg \
    && rm yarn-v$YARN_VERSION.tar.gz.asc yarn-v$YARN_VERSION.tar.gz \
    && apt-mark auto '.*' > /dev/null \
    && { [ -z "$savedAptMark" ] || apt-mark manual $savedAptMark > /dev/null; } \
    && find /usr/local -type f -executable -exec ldd '{}' ';' \
    | awk '/=>/ { print $(NF-1) }' \
    | sort -u \
    | xargs -r dpkg-query --search \
    | cut -d: -f1 \
    | sort -u \
    | xargs -r apt-mark manual \
    && apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false \
    # smoke test
    && yarn --version

# Note that this path is relative to where the build command is executed
# In this case the root of the project (from the Makefile)
COPY ./src/16-slim/docker-entrypoint.sh /usr/local/bin/

RUN ["chmod", "+x", "/usr/local/bin/docker-entrypoint.sh"]
ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]

CMD [ "node" ]

  ```
  
I might release this on GitHub and keep it up to date with renovate, but feel free to do so ;)
</details>

**Comment by reconzo-muhafiz** [comment]
@aslushnikov How can we reduce the size for jammy  
Base image I have is: mcr.microsoft.com/playwright:v1.54.0-jammy
I am not running any test but doing some browser automation tasks and using only chromium.

**Comment by revoltez** [comment]
@reconzo-muhafiz have you found any way?
