### ISSUE TITLE
Trying to check a option in the Microsoft fluentui component ChoiceGroup

### ISSUE THREAD

**Issue by khowling** [microsoft/playwright#10176]
Using the Microsoft fluentui ChoiceGroup component, managed to create data-testid on each of the rendered inputs - but playwright reports `the element is visible, enabled and stable`, but fails after 52 attempts.

Playwright script 
```
  await page.check('input[data-testid=cluster-systempool-none]')
```

ChoiceGroup rendered DOM
```
<div role="radiogroup">
 <div class="ms-ChoiceField root">
  <div class="ms-ChoiceField-wrapper">
   <input id="ChoiceGroup62-none" type="radio" name="ChoiceGroup62" data-testid="cluster-systempool-none">
   <label for="ChoiceGroup62-none" ><span id="ChoiceGroupLabel63-none" >Text</span></label>
  </div>
 </div>
 ....
 </div>
```

Any guidance to help debug?

**Comment by aslushnikov** [comment]
@khowling any chance we can repro this locally? Maybe you can provide us with a [trace file](https://playwright.dev/docs/next/trace-viewer)?

**Comment by chadsowald** [comment]
I'm also running into this.  It seems Fluent UI renders an <i> element inside its checkbox label, but that <i> is positioned where the actual input element is.  I assume it's doing this to have a custom-looking checkbox.  When Playwright tries to check it, this <i> receives the click event rather than the <input> because of this positioning.  Playwright then refuses to click/check it.

I'm not sure what to this of the issue.  Fluent is doing what it wants for styling reasons and Playwright is doing what it wants for actionability reasons.  

Any suggestions what's the best way to handle this?  Ideally, I still want the checks Playwright does to ensure that the checkbox actually changes state, rather than having to write that myself.

Fluent UI Checkbox control: https://developer.microsoft.com/en-us/fluentui?fabricVer=8#/controls/web/checkbox

**Comment by ltsuda** [comment]
Hi @chadsowald, I think I have a similar behavior but with a React application.

Here a checkbox HTML I have:
```html
<div class="field">
    <div class="ui checkbox">
        <input class="hidden" readonly="" tabindex="0" type="checkbox" value="">
        <label>Don't show next time </label>
    </div>
</div>
```

if I try the `locator('.ui.modal .hidden').setChecked(True)` where `.hidden` is in the subtree of a `.ui.modal` modal, I got the following error:

I've tried multiple other ways but or I select an element that is not a Checkbox/Radio or I select the input itself but the `label` intercepts the action of the `setChecked()` and fails.

```bash
E       playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for selector ".ui.modal >> .hidden"
E         selector resolved to visible <input readonly value="" tabindex="0" class="hidden" ty…/>
E       attempting click action
E         waiting for element to be visible, enabled and stable
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         performing click action
E         <label>Don't show next time </label> intercepts pointer events
E       retrying click action, attempt #1
```

So, the way I check the checkbox is the following, by using `.click()` method, but this way I lose the automatically validation if element is already checked performed by the `.setChecked()` method (https://playwright.dev/docs/api/class-locator#locator-set-checked). You might need I logic to validate if element is already checked before clicking it and the other way around too to uncheck.

``` javascript
await page.locator('.ui.modal .hidden').click() // this works
```

**Comment by chadsowald** [comment]
@ltsuda My HTML ends up as the following.  I'm also on React but using the Fluent React library. 

```
<div class="ms-Checkbox is-enabled root-99">
	<input
		type="checkbox"
		class="input-100"
		id="checkbox-32"
		aria-disabled="false"
		aria-label="My option text"
		aria-checked="false"
	/>
	<label class="ms-Checkbox-label label-101" for="checkbox-32">
		<div class="ms-Checkbox-checkbox checkbox-102">
			<i
				data-icon-name="CheckMark"
				aria-hidden="true"
				class="ms-Checkbox-checkmark checkmark-105"
				>
			</i>
		</div>
    	<span aria-hidden="true" class="ms-Checkbox-text text-104">My option text</span>
	</label>
</div>
```

I got mine working with this reliably.  Not a huge fan of it, but a small price to pay for reliable tests:
```
export const toggleCheckbox = async (labelText: string) => {
	const checkbox = `input[aria-label="${labelText}"]`;
	const label = `label >> text=${labelText}`;

	//Fluent UI checkboxes don't seem to consistently work well with Playwright without this
	await page.waitForTimeout(100);

	const isChecked = await page.isChecked(checkbox);

	// force param is required - https://github.com/microsoft/playwright/issues/2360
	// other troubles with checkboxes - https://github.com/microsoft/playwright/issues/10176
	await (isChecked ? page.uncheck(label, {force: true}) : page.check(label, {force: true}));
	
	//Fluent UI checkboxes don't seem to consistently work well with Playwright without this
	await page.waitForTimeout(100);
};
```
