### ISSUE TITLE
[Feature] Acces to the locator selector

### ISSUE THREAD

**Issue by dz1dz1on** [microsoft/playwright#10178]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Hey,

we would like to have access to the selector of our locator. Thanks to that solution we can create methods which can enhance/modify our base selector.

**Example**
![image](https://user-images.githubusercontent.com/62831238/140916601-5c7b9ef0-e3e3-4d03-8a33-c38235b00a0a.png)

and then we can implement such thing:
```
class Header extends PageObjectComponent {
    $ = {
        button: this.page.locator('[e2e-target=button]'),
    }
    constructor(page) {
        super(page, page.locator('[e2e-target="header"]'))
    }

    async hoverOnHeader(): Promise<void> {
        await this.parentElement.hover()
    }
}

class LandingPage extends PageObject {
    $ = {
        footer: new Footer(this.page),
        header: new Header(this.page),
    }

    constructor(page) {
        super(page, landingPageUrl)
    }

    async waitForPageLoad(): Promise<void> {
        await this.$.header.hoverOnHeader()
    }
    
    async clickConfirmButton Promise(): void {
        const baseSelector: string = this.$.header.$.button.selector
        await this.page.locator(`${baseSelector}[e2e-target-name="confirm"]`).click()
    }
}
```

**Comment by Evilweed** [comment]
@pavelfeldman i think it would be still useful to be able to create selectors that cannot be created with `.withAttribute()`

For example to create equivalents of:
`withText()`
`withExactText()`

Seems like `.withAttribute()` is easier to use, but this seems to be more powerful:
```
const baseSelector: string = this.$.header.$.button.selector
await this.page.locator(`${baseSelector}[e2e-target-name="confirm"]:contains("some text")`).click()
```

**Comment by pavelfeldman** [comment]
Selector is an implementation detail of the locator, we can't create locator from selector in the general case. But we can try amending conditions like you attribute. I'll close this one in favor of withAttribute. We already have text and exact text matching via adding `locator('text=Hello')`.

**Comment by Evilweed** [comment]
@pavelfeldman if you are implementing only withAttribute() then i need to open new feature requests for withText() and withExactText() (or withText with regexp support).

This is because withAttribute() and your suggested `.locator('text=Hello')` does not solve my problem entirely :) 

withAttribute() already exists too, it is `.locator([attribute-name="someValue"])` so in theory anyone could use this, but what we need is to be able to extend current locator instead of searching for new thing within parent locator.

So much easier to create DRY code like that:
```
$ = {
  countries: this.page.locator('option')
  disabledCountries: this.$.countries.withAttribute('e2e-which', 'disabled')
  country: (name: string | Regexp) => this.$.countries.withText(name)
  disabledCountry: (name: string | Regexp) => this.$.disabledCountries.withText(name)
}
```

Than this:
```
const countryOptionCssSelector = 'option'
const disabledCountryOptionCssSelector = 'option'
const pageObject1 = {
  $ = {
    countries: this.page.locator(countryOptionCssSelector)
    disabledCountries: this.page.locator(`${countryOptionCssSelector}${disabledCountryOptionCssSelector}`)
    country: (name: string | Regexp) => this.page.locator(`${countryOptionCssSelector} text=${name}`)
    disabledCountry: (name: string | Regexp) => this.page.locator(`${countryOptionCssSelector}${disabledCountryOptionCssSelector} text=${name}`)
  }
}

# Not to mention that sometimes you are passing parentElement to nested page objects, or you need to reuse/extend selector from other page object and it gets even less nice
# It's harder to maintain code and you need to keep track where you have all of those CssSelectors defined.

import countryOptionCssSelector from ...
import disabledCountryOptionCssSelector from ...

const pageObject2 = {
  $ = {
    something: this.page.locator(`${countryOptionCssSelector}${disabledCountryOptionCssSelector} ...`)
  }
}
```
