### ISSUE TITLE
[BUG] Installing firefox fails because maintenanceservice.exe gets flagged as malware

### ISSUE THREAD

**Issue by ealap** [microsoft/playwright#10173]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows Server 2019 (17763.2268)
- Node.js version: v16.13.0
- Browser: Firefox
- Extra: System has Bitdefender Endpoint Security Tools installed

**Code Snippet**

```powershell
❯ playwright install firefox
Removing unused browser at ~~redacted~~\pw_browsers\firefox-1297
Downloading Playwright build of firefox v1297 - 74 Mb [====================] 100% 0.0s
Failed to install browsers
Error: Failed to download firefox v1297, caused by
Error: EPERM: operation not permitted, open '~~redacted~~\pw_browsers\firefox-1297\firefox\maintenanceservice.exe'
```

**Describe the bug**

Since Firefox-1297, I was unable to complete the installation for Firefox binaries because Bitdefender is flagging it as malware. I didn't have this problem in binary packages Firefox-1295 and earlier.

To further verify this issue, I grabbed the maintenanceservice binary from another system with no Bitdefender and uploaded it to VirusTotal, and the [results](https://www.virustotal.com/gui/file/109e1bb86f1e2793efdfea1267792cfb42851bdc83b3d53e21644f4eb2304d5e/detection) show it is flagged by 9 other antiviruses as `Gen:Variant.Razy` malware.

I also tried sending the similar binary from the actual Firefox installation and the [results](https://www.virustotal.com/gui/file/333196c33bae6a2b513e39e24bf2404a77bf93c470d685c1e2e43a0351026b67) are clean.

It looks like a case of false-positive detection, but are there options where I can verify the integrity of the downloaded binaries? I would need it to make a case to our IT security that it is fine to whitelist this file/folder.

**Comment by aslushnikov** [comment]
@ealap well, our firefox builds aren't supposed to auto-update ever, so maybe we can not ship it at all. Let me look into this

**Comment by aslushnikov** [comment]
> It looks like a case of false-positive detection, but are there options where I can verify the integrity of the downloaded binaries?

@ealap We don't publish hashes for the archives that we download - but we should. I'll schedule this for the next release.

**Comment by brtsmrtn** [comment]
Same problem here, just with '..\firefox-1297\firefox\firefox.exe' file. Thanks ahead @aslushnikov for looking for solution. I will investigate more and add some more info eventually.
