### ISSUE TITLE
[REGRESSION]: WebWorker evaluated in main context, violating CSP

### ISSUE THREAD

**Issue by kyranjamie** [microsoft/playwright#10171]
**Context:**
- GOOD Playwright Version: `1.12.3`
- BAD Playwright Version: `1.16.3`
- Operating System: macOS (but affects all)

I'm working on a [Web Extension](https://github.com/hirosystems/stacks-wallet-web) using Playwright for our tests. It uses Argon2, a key stretching library, that uses WASM. The extension has a strict CSP.

Argon2 uses wasm eval, so a `wasm-eval` CSP exception is needed, [_unless_ it's loaded inside a WebWorker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#content_security_policy), which in our case it is. Upgrading to the latest version of Playwright, the tests error with the CSP violation error:

```
  console.error
    Error [RuntimeError]: abort(CompileError: WebAssembly.instantiate(): Wasm code generation disallowed by embedder). Build with -s ASSERTIONS=1 for more info.
        at abort (chrome-extension://eecnpiikplhmnkkfjdnlmhjfhalcnohl/decryption-worker.js:18:7620)
        at chrome-extension://eecnpiikplhmnkkfjdnlmhjfhalcnohl/decryption-worker.js:18:9491
```

[An example test run can be seen here.](https://github.com/hirosystems/stacks-wallet-web/runs/4149143515?check_suite_focus=true).

As the eval violation takes place _within_ a worker, we should not expect this error. Could Playwright have made some changes whereby the contents of the worker script, is evaluated in the browser's main context?

**Comment by aslushnikov** [comment]
@kyranjamie This is a regression in chromium itself: https://bugs.chromium.org/p/chromium/issues/detail?id=1268576&q=%22Wasm%20code%20generation%20disallowed%20by%20embedder%22&can=2

It'll be fixed with the new chrome that will be released with Playwright 1.17 in a few days.
Alternatively, you can try using Playwright@next:

```bash
$ npm i @playwright/test@next
```
