### ISSUE TITLE
[Feature] Add promise retry mechanism to expect

### ISSUE THREAD

**Issue by Evilweed** [microsoft/playwright#10187]
Hey there. Resilient, stable tests are holy grail. What was cool in TestCafe framework was auto retry mechanism built into `expect` (some of the promises you have provided inside use this mechanism, and there is a task to expend it to all promises or to some custom promise that can be passed to expect which will allow retries).

Let's see example (this one is super basic, but there might be more advanced use cases):
```
const errorMessageLength = loginModal.$.errorMessage.textContent().then((text) => `${text}`.length)
await expect(errorMessageLength).toBeGreaterThan(5)
```

### Currently, this code fails as unhandled Promise rejection:
![CleanShot 2021-11-09 at 17 20 30@2x](https://user-images.githubusercontent.com/5477821/140963080-59006acd-2ace-460b-bba2-eb4b165b5525.png)

### What we would like to happen:
1. expect takes the promise and tries to resolve it and to compare using compare function (in our case `toBeGreaterThan`)
2. if expect fails, then expect tries to resolve same promise again and compare using compare function
3. this continues until comparison/check passes or until timeout

### Timeout example
```
const errorMessageLength = loginModal.$.errorMessage.textContent().then((text) => `${text}`.length)
await expect(errorMessageLength).toBeGreaterThan(5, { timeout: 3000 })
```

### Or with custom promise that would allow that
```
const errorMessageLength: RetryPromise = new RetryPromise(loginModal.$.errorMessage.textContent().then((text) => `${text}`.length))
await expect(errorMessageLength).toBeGreaterThan(5, { timeout: 3000 })
```

**Comment by aslushnikov** [comment]
> Resilient, stable tests are holy grail. What was cool in TestCafe framework was auto retry mechanism built into expect (some of the promises you have provided inside use this mechanism, and there is a task to expend it to all promises or to some custom promise that can be passed to expect which will allow retries).

@Evilweed Playwright has this in a form of [web-first assertions](https://playwright.dev/docs/next/test-assertions/#expectlocatortohavetextexpected-options)

So to assert certain text on the page:

```js
await expect(page.locator('.error-message')).toContainText('error happened');
```

You can also combine it with a regex to assert text length to be larger or equal 5 characters:

```js
await expect(page.locator('.error-message')).toHaveText(/.{5}/);
```

**Comment by Evilweed** [comment]
@aslushnikov thank you for the tip with Regexp - completely forgot that I can use it.

That being said - what i am trying to say is that this mechanism is awesome, but there are cases where Framework Users would like to benefit from this mechanism in their custom actions that can't be accomplished by built in methods (because it is not possible to have everything as separate easy to access method like toHaveText()).

I agree that currently provided example is not the best but truth be told, we just started to rewrite all tests to Playwright and didn't get to the more complicated cases. 😅

Maybe something like that?
```
expect(page.locator('[e2e-target="summary-cost"]').getAttribute('e2e-data').then((value: string): number => Number(value))).greaterThan(1000)
```

If it's not convincing, then you can close the ticket. I'll try to gather find some more examples during our rewrite of E2E tests. 👍

**Comment by PandaMagnus** [comment]
I second this. I have a scenario with a client where, upon clicking a button, sometimes a certain div does not appear. We'd like to be able to script the test to retry *just* the click, as we suspect that may solve the flakiness while we do further investigation if it's a problem with our test runner or an actual bug with the website. If we could do something like the RetryPromise @Evilweed described above, that would be awesome.

**Comment by aslushnikov** [comment]
Ok, I filed this as a feature request separately: https://github.com/microsoft/playwright/issues/10235

Please upvote to get it prioritized! Closing this in favor of https://github.com/microsoft/playwright/issues/10235
