### ISSUE TITLE
[BUG] New page.frameLocator doesn't allow URL object as selector

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#10186]
**Context:**
- Playwright Version: [1.17.0-next-1636430928000]
- Operating System: [Mac]
- Node.js version: [16.12.0]
- Browser: [Chromium]
- Extra: [N/A]

**Code Snippet**

Working
```javascript
const { test, expect } = require('@playwright/test');
test('test', async ({ page }) => {
    await page.goto('https://www.way2automation.com/way2auto_jquery/frames-and-windows.php');
    await page.click('text=Open Seprate New Window');
    const [page1] = await Promise.all([
        page.waitForEvent('popup'),
        page.frame({
            url: 'https://www.way2automation.com/way2auto_jquery/frames-windows/defult2.html'
        }).click('text=Open New Seprate Window')
    ]);
});

```

Not Working
```javascript

const { test, expect } = require('@playwright/test');
test('test', async ({ page }) => {
    await page.goto('https://www.way2automation.com/way2auto_jquery/frames-and-windows.php');
    await page.click('text=Open Seprate New Window');
    let frmElm = page.frameLocator({url: 'https://www.way2automation.com/way2auto_jquery/frames-windows/defult2.html'}
    ).locator('text=Open New Seprate Window');
    const [page1] = await Promise.all([
        page.waitForEvent('popup'),
        frmElm.click()
    ]);
});

```

**Describe the bug**

I'm exploring the new **page.frameLocator** to be released in 1.17

Existing page.frame supports URL object but new page.frameLocator doesn't support URL object.
```javascript
Failed to execute 'querySelectorAll' on 'Document': '[object Object]' is not a valid selector.
```
<img width="653" alt="Screen Shot 2021-11-09 at 8 09 10 AM" src="https://user-images.githubusercontent.com/22808594/140961021-a6824200-88c6-4ac5-82f3-ef9094bf5758.png">

<img width="541" alt="Screen Shot 2021-11-09 at 8 08 56 AM" src="https://user-images.githubusercontent.com/22808594/140961065-ee15f241-49fd-4a95-be5d-49b405efa3cf.png">

Kindly let me know if my expectation is incorrect.

**Comment by pavelfeldman** [comment]
You can use following if your `src` is static:

```js
page.frameLocator('[src*="https://www.way2automation.com/way2auto_jquery"]')
    .locator('text=Open New Separate Window');
```

**Comment by pavelfeldman** [comment]
Closing as we don't intend to support location-based selectors. Attribute selectors should work for src though!
