### ISSUE TITLE
Cannot find module 'playwright-core/lib/utils/registry' on git npm install

### ISSUE THREAD

**Issue by SaranshBS** [microsoft/playwright#10185]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.16.3
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] 12.20
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Describe the bug**

Clone the repo, run npm install.

or try installing the lib directly via github `npm install 'microsoft/playwright#master'`. Prepare script is triggered resulting in the above mentioned error.

**Comment by mxschmitt** [comment]
Its not supported to install via Git. If you want to use the latest tip-of-tree changes you can use the next NPM tag: `npm install @playwright/test@next`.

**Comment by SaranshBS** [comment]
This also comes when we just clone the repo and run npm install on it

**Comment by aslushnikov** [comment]
@SaranshBS make sure to have NPM 8 to install & build playwright.
