### ISSUE TITLE
[BUG] mouse.wheel doesn't work with Mobile Safari on Linux

### ISSUE THREAD

**Issue by akselikap** [microsoft/playwright#10183]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Linux inside Docker container (Host OS is Mac, docker container is based on mcr.microsoft.com/playwright:v1.16.3-focal)
- Node.js version: 14.7
- Browser: WebKit Mobile
- Extra:

**Code Snippet**

```javascript
test.only('test scrolling', async ({ page }) => {
    await page.goto('/');
    await page.mouse.move(200, 300);
    const originalY = await page.evaluate(() => window.pageYOffset);
    await page.mouse.wheel(0, 1000);
    await page.waitForTimeout(1000);
    const newY = await page.evaluate(() => window.pageYOffset);
    expect(newY).toBeGreaterThan(originalY);
});
```

**Describe the bug**

I'm testing whether the page is actually scrolled or not and I have no issues when running my tests on Mac but when running them on Linux environment mobile Safari/Webkit doesn't scroll at all which leads to failing tests. I would expect the page to scroll regularly on Linux as well. The scrolling works with chrome, mobile chrome, firefox and safari on Linux as well.

**Comment by yury-s** [comment]
Debugging notes: WebFrameLoaderClient::transitionToCommittedForNewPage() in case of fixed layout mode in GTK/WPE sets scrollbars to be [always hidden](https://wksearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fwebkit%2FSource%2FWebKit%2FWebProcess%2FWebCoreSupport%2FWebFrameLoaderClient.cpp&line=1523). Later on, when scroll event is handled in FrameView::handleWheelEventForScrolling it will bail if [canHaveScollbars](https://wksearch.azurewebsites.net/#path=%2Fhome%2Fjoe%2Fwebkit%2FSource%2FWebCore%2Fpage%2FFrameView.cpp&line=5239) is false. This is opposite to the effect that we want to achieve dispatching the wheel event with mobile emulation.
