### ISSUE TITLE
[Feature] expect(response).toBeOk() to print http response status and body

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10189]
### Discussed in https://github.com/microsoft/playwright/discussions/10175

<div type='discussions-op-text'>

<sup>Originally posted by **AndyGBC** November  9, 2021</sup>
Hi all, below is a code snippet that will use the APIContextRequest to make a post request and create a company.  This works fine, though I am sure someone could help improve this, if so, feel free :)

My question is, if this fails and returns a 403 status, the expect on the status will obviously catch it and fail, but how can I go about getting more information about why it failed?

By this I mean, if after the POST request has been made, I can console.log the response.json() which would show me some details about the failure but that won't appear in the HTML report which is what I would like to see if possible.

Any help appreciated.

`async createCompany(name: string, shortName: string, description: string): Promise<string> {

        expect(name.trim().length != 0).toBeTruthy();
        
        const response = await this.baseAPI.context.post(`https://some.endpoint/create`, { 
            headers:{
                'X-BC-JWT': this.baseAPI.api.getToken()
            },
            data: {
                kind: 'company',
                name: name,
                short_name: shortName,
                descr: description,
            }
        });

        expect(response.status()).toEqual(200);
        expect(await response.json()).toHaveProperty('artifact');

        let companyUri: string = '';

        await response.json().then(data => {
            companyUri = data.artifact;
        });

        expect(companyUri.length != 0).toBeTruthy();
        return companyUri;
    }`
</div>

**Comment by yury-s** [comment]
@AndyGBC when the server returns 403 do you want to see the response body in the report or status text would be enough?

**Comment by AndyGBC** [comment]
@yury-s Ideally the response body if possible as that would give us the fastest feedback on the failure.

Thank you :)
