### ISSUE TITLE
[BUG] New page.frameLocator doesn't work if navigation, popup or download events are fired after button click

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#10191]
**Context:**
- Playwright Version: [1.17.0-next-1636430928000]
- Operating System: [Mac]
- Node.js version: [16.12.0]
- Browser: [Chromium]
- Extra: [N/A]

**Code Snippet**

**Working Code**
```javascript
const { test, expect } = require('@playwright/test');
test.use({
    acceptDownloads: true
});
test('test', async ({ page }) => {
    await page.goto('https://jsfiddle.net/jsuser21/j1fqdare/4/',{waitUntil: "networkidle"});
    const [download] = await Promise.all([
        page.waitForEvent('download'),
        page.frame({
            name: 'testFrame'
        }).click('a:has-text("Download")')
    ]);
});
```

**Not Working Code**
```javascript

const { test, expect } = require('@playwright/test');
test.use({
    acceptDownloads: true
});
test('test', async ({ page }) => {
    await page.goto('https://jsfiddle.net/jsuser21/j1fqdare/4/',{waitUntil: "networkidle"});
    let frmElm = await page.frameLocator('[name="testFrame"]').locator('a:has-text("Download")');
    const [download] = await Promise.all([
        page.waitForEvent('download'),
        frmElm.click()
    ]);
});

```

```javascript
  Timeout of 30000ms exceeded.

    Pending operations:
      - locator.click at test/bug3.js:11:16

    page.waitForEvent: Page closed
    =========================== logs ===========================
    waiting for event "download"
    ============================================================

       8 |     let frmElm = await page.frameLocator('[name="testFrame"]').locator('a:has-text("Download")');
       9 |     const [download] = await Promise.all([
    > 10 |         page.waitForEvent('download'),
         |              ^
      11 |         frmElm.click()
      12 |     ]);
      13 | });

```

**Describe the bug**

I'm exploring the new page.frameLocator to be released in 1.17

Noticed, after page.frameLocator('frame').locator('button').click(), events like waitForNavigation, waitForEvent('download'), waitForEvent('popup') not working.

**Comment by pavelfeldman** [comment]
There is another frame (jsfiddle's one) along the way. This will work:

```js
  await page.goto('https://jsfiddle.net/jsuser21/j1fqdare/4/');
  let frmElm = await page.frameLocator('[name="result"]').frameLocator('[name="testFrame"]').locator('a:has-text("Download")');
  const [download] = await Promise.all([
      page.waitForEvent('download'),
      frmElm.click()
  ]);
```

**Comment by vsravuri** [comment]
OK. I'll retest and share the code from my application privately. Could you please share your email id?

**Comment by vsravuri** [comment]
This is how my DOM looks like.

<img width="1079" alt="Screen Shot 2021-11-09 at 12 25 41 PM" src="https://user-images.githubusercontent.com/22808594/141000605-8bcb6eef-346c-4704-95cf-8a91e7234493.png">

This is my existing code works fine with frame navigation.
```javascript
let elm_SubMainFrame = await this.page.frames().find(frame => frame.name() === submainframe);
        const [response] = await Promise.all([
            elm_SubMainFrame.waitForNavigation(),
            elm_SubMainFrame.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
```

When i modify the code to work with page.frameLocator, it doesn't work while waiting for navigation either with page.waitForNavigation or frameLocator.waitForNavigation

```javascript
let frmElm = await this.page.frameLocator('[name="mainframe"]').frameLocator('[name="submainframe"]');
        const [response] = await Promise.all([
            //this.page.waitForNavigation(),
            frmElm.waitForNavigation(), //  TypeError: frmElm.waitForNavigation is not a function
            frmElm.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
```

Could you please help me how can i handle waitForNavigation successfully using frameLocator

**Comment by pavelfeldman** [comment]
Could you share on why navigation is happening and why you need to await for it? I assume that the `selectOption` call worked?

**Comment by vsravuri** [comment]
@pavelfeldman Yes, `selectOption` call worked. If i don't handle the navigation, after selecting drop down, i evaluate the drop-down value, that's when it fails because of `Execution context was destroyed, most likely because of a navigation`

```javascript
let frmElm = await this.page.frameLocator('[name="mainframe"]').frameLocator('[name="submainframe"]');
        const [response] = await Promise.all([
            frmElm.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
return frmElm.locator(this.elm_DdlKbSelOpt).evaluate(el => el.text.trim());

```
<img width="1150" alt="Screen Shot 2021-11-09 at 3 23 34 PM" src="https://user-images.githubusercontent.com/22808594/141022098-53b71681-acc8-4d23-a430-b5839ef3043d.png">

**Comment by pavelfeldman** [comment]
Could it be that selecting the element initiates a navigation? You start evaluating, but the frame navigates under your feet.

**Comment by vsravuri** [comment]
Yes, you are right

**Comment by pavelfeldman** [comment]
So what are your expectations in this case? I don't see a bug here, should I close it?

**Comment by vsravuri** [comment]
Thanks for looking into this issue.

This is my existing code that works fine, able to handle frame navigation after selecting drop down value`elm_SubMainFrame.waitForNavigation()`

```javascript
let elm_SubMainFrame = await this.page.frames().find(frame => frame.name() === submainframe);
        const [response] = await Promise.all([
            elm_SubMainFrame.waitForNavigation(),
            elm_SubMainFrame.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
return frmElm.locator(select[name="kb"]).evaluate(el => el.text.trim());
```

If i modify the code to use frameLocator like this, it fails as the context is destroyed and recreated by the time i evaluate the drop down. I would like to know how to handle waitForNavigation in this scenario.

```javascript
let frmElm = await this.page.frameLocator('[name="mainframe"]').frameLocator('[name="submainframe"]');
        const [response] = await Promise.all([
            frmElm.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
return frmElm.locator(select[name="kb"]).evaluate(el => el.text.trim());
```

Appreciate if you could provide me a solution

**Comment by pavelfeldman** [comment]
The way you should structure the test for this is following:

```js
const frmElm = await this.page.frameLocator('[name="mainframe"]').frameLocator('[name="submainframe"]');
await frmElm.locator('select[name="kb"]').selectOption({label: 'kb'});
await expect(frmElm.locator(select[name="kb"])).toHaveText('Expected');
```

**Comment by vsravuri** [comment]
I tried you suggestion, didn't work well with my application. I frequently see error 'Cannot find context with specified id'. I have nested frames 6 to 7 level deep.

I modified the code and i can get around the previous error.

```javascript
const [response] = await Promise.all([
            this.page.waitForLoadState("networkidle"),
            this.page.waitForResponse(/default/),
            frmElm.locator('select[name="kb"]').selectOption({label: 'kb'})
        ]);
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
