### ISSUE TITLE
[Feature Request] Dragslider

### ISSUE THREAD

**Issue by jayson-labarrete** [microsoft/playwright#10211]
A dragslider would be really awesome to have as a feature. 

Mostly similar to codeceptjs - https://codecept.io/helpers/Playwright/#dragslider

But should be able to accept elements too. 
.dragslider(`locator`, number position to drag)
.dragslider(`element`,number position to drag)

discussed in slack: https://playwright.slack.com/archives/CSUHZPVLM/p1636512849162200

**Comment by dgozman** [comment]
`await page.locator('#my-slider').fill('42')` should work in the next release.

**Comment by jayson-labarrete** [comment]
@dgozman Thank you so much!
