### ISSUE TITLE
[Question] how to filter array of selectors with same ID by text

### ISSUE THREAD

**Issue by Yurii397** [microsoft/playwright#10210]
I have the case where elements have the same data-test-id. Instead of using hardcoded indexes, I would like to get and then use the needed element by text.  

I'm using the following code but filtering doesn't work, get back the same array of elements with ElementHandlers 

```js
/// Util class
  async getElementsById(
    id,
    option: ElementContext = {
      locator: id,
      context: this.page,
    }
  ):Promise<Array<ElementHandle>>{
    return await option.context.$$(`[data-test-id=${option.locator}]`)
  }

/// Page object
 megaNavItem = async () =>
        await this.getElementsById('mega-nav-level-1-item')
        
  filterElements = async (expectedItem: string) =>
    await this.megaNavItem().then(el =>
      el.find(async e => (await e.innerText()) === expectedItem)
    )
```
  
Unfortunately, can't understand what is the reason. I see that text is not extracting (innerText() doesn't work ) to make correct filtering. Would appreciate any help with this case.

**Comment by Yurii397** [comment]
For easier understanding can simplify it like this 

```
  findElement = async (expectedItem: string) =>
      this.page.$$("[data-test-id='mega-nav-level-1-item']").then(e => e.filter(async e => await e.innerText() === expectedItem))
```
actually, this part doesn't work

**Comment by aslushnikov** [comment]
> I have the case where elements have the same data-test-id. Instead of using hardcoded indexes, I would like to get and then use the needed element by text.

@Yurii397 you can use a selector that combines both:

```js
const elements = page.locator(`[data-test-id='mega-nav-level-1-item'] >> text=MyText`);
```

(more info on locators: https://playwright.dev/docs/api/class-locator)

**Comment by Yurii397** [comment]
@aslushnikov thanks appreciate your help.
Still curious and keen to know why the kind of filtering that I'm doing above doesn't work, just to avoid similar cases in the Future. 
Is that something related to Playwright architecture how it's built under the hood?

**Comment by aslushnikov** [comment]
@Yurii397 it looks like you got tripped with promises. Your `filter` function uses async predicate, which won't work. You'll need to use a sync predicate, and use `Promise.all()` construct beforehand or a manual iteration to fetch contents.

Something like this would work:

```ts
/// Util class
async function getElementsById(id, option) {
  return await option.context.$$(`[data-test-id=${option.locator}]`)
}

/// Page object
megaNavItem = async () => await this.getElementsById('mega-nav-level-1-item')

filterElements = async (expectedItem: string) => {
  const elements = await this.megaNavItem();
  const result = [];
  for (const element of elements) {
    const text = await element.innerText();
    if (text === expectedItem)
      result.push(element);
  }
  return result;
}
```

**Comment by Yurii397** [comment]
@aslushnikov thank you for the guide!
