### ISSUE TITLE
[BUG] Playwright clicks on an element that is not in the viewing area of ​​the web page.

### ISSUE THREAD

**Issue by LevBoichenko** [microsoft/playwright#10212]
**Context:**
- Playwright Version: [1.15]
- Operating System: [Mac]
- Node.js version: [14.15.1]
- Browser: [Chromium]
- Extra: [N/A]

**Describe the bug**

Web interface (web page) has some element, button.
When I execute test manually this element (button) doesn't exist in viewport of web interface, that's why I can't click on it.
When I execute my test using playwright and native test runner, somehow playwright click on the element (button) and test passed after that, but this behavior not correct, because original element not in viewport of the web page.

How I can verify element exist or doesn't exist in viewport?
P.S. state visible doesn't work.

<img width="316" alt="Screenshot at Nov 10 14-05-04" src="https://user-images.githubusercontent.com/73170453/141110688-bd68103a-7e73-4a28-9216-05caf2f1c083.png">
<img width="252" alt="Screenshot at Nov 10 14-05-24" src="https://user-images.githubusercontent.com/73170453/141110700-ee602f9d-69b5-4ec8-a169-937ccde7dec1.png">

**Comment by pavelfeldman** [comment]
Playwright scrolls the page, as the user would.

**Comment by LevBoichenko** [comment]
> Playwright scrolls the page, as the user would.

this page without ay scrolling

**Comment by aslushnikov** [comment]
@LevBoichenko would you mind share a link to the page? Or maybe a trace?
