### ISSUE TITLE
[BUG] Follow the best practices in the published Docker container

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10223]
Customers on Slack were suggesting various improvements to the Docker spec. This is a placeholder bug for those improvements.

We currently add dev features like ssh and vnc to the published container. It looks like there is a general interest in the spec that makes Playwright work, yet does not expose those. Please comment below if you have the same or additional requirements.

**Comment by rwoll** [comment]
We rolled our own container (based off the official, but could not use a FROM directive using the official base) so we could drop some of the dev tooling we don't need/want in our dynamic container/browser test backend.

Having a minimal image would be great! Luckily, the playwright CLI handles the hard work, so rolling our own image was pretty straightforward.

**Comment by aslushnikov** [comment]
> Having a minimal image would be great! Luckily, the playwright CLI handles the hard work, so rolling our own image was pretty straightforward.

@rwoll Thanks for the input! Thanks to Playwright CLI, the minimum base Docker image for Playwright is just Ubuntu + Node.js:

```
FROM ubuntu:focal

# Install node16
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get install -y nodejs
```

I'm not sure it's worth publishing it though. If (when) we support Debian, we'd simply be able to use node.js debian image.

**Comment by rwoll** [comment]
@aslushnikov that's essentially what ours looks like plus one more line with playwright CLI preinstalling the browsers/deps.

**Comment by aslushnikov** [comment]
This one was addressed by https://github.com/microsoft/playwright/pull/10260

I'll cherry-pick it to 1.17 as well once I make sure that tests pass.

**Comment by aslushnikov** [comment]
This is fixed.
