### ISSUE TITLE
[Feature] Add optional call type (eg POST, GET) to page.waitForResponse(urlOrPredicate[, options])

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#10229]
Hi

I love using `page.waitForResponse(urlOrPredicate[, options])` to make our tests more deterministic but I'd love to be able to specify what type of request the response came for.

For example

```
        await page.waitForResponse('/api/accounts', { type: 'POST' });
        await page.waitForResponse('/api/accounts', { type: 'GET' });
```

**Comment by aslushnikov** [comment]
@alisterscott you can use predicate for this right now:

```js
await page.waitForResponse(r => r.url().includes('/api/accounts') && r.request().method() === 'GET')
```

would it work for you?

**Comment by alisterscott** [comment]
Perfect, thanks
