### ISSUE TITLE
[Question] Advice for using playwright without including it in a yarn/npm project

### ISSUE THREAD

**Issue by codex-zaydek** [microsoft/playwright#1022]
I’m currently using the Netlify web app to push deploys of my site, but I noticed that deploys are taking longer than usual because Netlify is actually downloading the entire yarn project, building it, and shipping the build folder. This process *includes* playwright, which is not necessary for simple deploys, and adds at least a dozen seconds to the process.

Does someone have advice for using playwright without tying it to a project? I would use the Netlify CLI but [there’s an open issue preventing the current version of the command-line tool from working](https://github.com/netlify/cli/issues/667) right now.

**Comment by aslushnikov** [comment]
> Does someone have advice for using playwright without tying it to a project?

@codex-zaydek can you please explain more (for someone who hasn't touched netlify)?

**Comment by codex-zaydek** [comment]
It’s more of a general concern than anything. Playwright isn’t a small dependency and sometimes requires special handling to initialize for the first time (e.g. `npm install` to download the browser binaries). So at the time I posted this, I was more looking for a simple pattern for extracting my e2e tests from my frontend code.

I’ve since started authoring separate repos for e2e tests like Playwright and Cypress:

- https://github.com/codex-src/codex-playwright
- https://github.com/codex-src/codex-cypress

This way my frontend can stay light and dependency-shy. Netlify specifically has this feature (that I don’t like) where they can build your repo per branch push. This means they, from what I can tell, are downloading your repo from GitHub, installing it, compiling, and shipping the `build` folder, for example. Unless I’m missing something, the more and bigger the dependencies, the longer Netlify will take which will lead to slower deploys. **Netlify also bills you for longer deploys, ‘build minutes’, so this was a concern of mine.**

This isn’t a problem for me anymore since I’ve extracted the relevant code and stopped shipping to Netlify, but I wanted to ask if anyone was doing something similar.

**Comment by aslushnikov** [comment]
@codex-zaydek Ah, I see! Thanks for explaining. I don't have experience with netlify per se, but we do know that browsers are somewhat heavy and take time to download.

Certain services do let you setup custom caches; for example, on circle CI we cache all browser downloads: https://github.com/microsoft/playwright/blob/8c532bd8da2f91d5ce3a88a6fd124d94bc04f5b1/.circleci/config.yml#L15-L20
Maybe this is something available on netlify? 🤷‍♂ 

Also, we work on #1102 that should allow re-using browser binaries and save considerable amount of time if you have many projects that all depend on playwright. 

Might any of these help with this kind of scenarios?

**Comment by codex-zaydek** [comment]
Sure! For me the easiest thing to do is just extract Puppeteer out of my frontend so it’s not a concern I have to think about or remember going forward. I didn’t know about the caching feature for Circle CI so I’ll keep that in mind.

Feel free to close this, and thank you for following up!

**Comment by pavelfeldman** [comment]
Closing it for now, please feel free to reopen or file a new issue!
