### ISSUE TITLE
[BUG]Installation 

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#10236]
centos7
playwright install chrome

+ apt-get install -y ./google-chrome-stable_current_amd64.deb
/root/PlaywrightDemo/bin/Debug/net6.0/.playwright/package/bin/reinstall_chrome_stable_linux.sh: line 25: apt-get: command not found
Failed to install browsers
Error: Failed to install chrome

**Comment by aslushnikov** [comment]
CentOS is not supported; please upvote https://github.com/microsoft/playwright/issues/9199
