### ISSUE TITLE
[Feature] Dry run mode for install-deps

### ISSUE THREAD

**Issue by jawnsy** [microsoft/playwright#10232]
When running Playwright tests in a containerized environment, it is helpful to build a custom image with native dependencies preinstalled. It is possible to do this by manually examining the list of dependencies in the nativeDeps.ts file: https://github.com/microsoft/playwright/blob/d34f9972abf3e412c9a73ee7b524e529a89136f8/packages/playwright-core/src/utils/nativeDeps.ts#L228-L242

However, it would be convenient if there were a way to list all the dependencies that playwright would install, without actually running the install command. It looks like we can do this by separating the dependency list generation and installation commands, for example, create a function that returns uniqueLibraries and a separate function that accepts that as input, then spawns apt-get: https://github.com/microsoft/playwright/blob/d34f9972abf3e412c9a73ee7b524e529a89136f8/packages/playwright-core/src/utils/dependencies.ts#L49-L72

I'd be happy to create a pull request if this is a feature you'd consider! I'd propose something like `npx playwright install-deps --dry-run` to return the package list for the current system

**Comment by aslushnikov** [comment]
@jawnsy so what is the usecase, once again? Why don't you just run `npx playwright install-deps` as a step during container build?

**Comment by jawnsy** [comment]
We pin the playwright version in our `packages.json`, and our container build doesn't have our source code.

I suppose that we could use `npx playwright install-deps` to install all the deps for the latest version, but we didn't want to rely on Playwright's dependencies being backward-compatible (that is, installing playwright deps for 1.16.3 might not be the right deps for 1.15.2)

I suppose that we could mount the packages.json and use npx as an alternative

**Comment by JoelEinbinder** [comment]
While you generally you should run `npx playwright install-deps` from the package.json folder, if you dont have it and know the playwright version you can do:

```
npx --package=playwright-core@1.16.3 playwright install-deps
```

Which will install the deps for that specific version. Seems like a better solution for you than manually copying the list of dependencies as they update.
