### ISSUE TITLE
A new page opens after clicking, but it seems like context.pages doesn't record it.

### ISSUE THREAD

**Issue by MrDust0** [microsoft/playwright#10239]
Hi
i don't know if it is a bug, but i fisrt open a page, then click one button, which opens another page on a new tag. There suppose to be 2 pages, but `context.pages` returns only 1. The weird thing is, when i use `context.new_page()` to open one more page, `context.pages` returns 3.

i thought it happens because the page loading has not finished. i wait for seconds but it doesn't work still.

Here is my program.
![image](https://user-images.githubusercontent.com/56252828/141281466-266285f7-1857-4cf5-b066-6e8c4d602ba2.png)

thanks a lot if anyone helps!

**Comment by aslushnikov** [comment]
@MrDust0 it takes some time to open a page, so you need to click the link while expecting the upcoming `page` event: https://playwright.dev/python/docs/api/class-browsercontext/#browser-context-wait-for-event

```python
with context.expect_event("page") as event_info:
    loc.click("button")
len(context.pages)
```

**Comment by MrDust0** [comment]
> @MrDust0 it takes some time to open a page, so you need to click the link while expecting the upcoming `page` event: https://playwright.dev/python/docs/api/class-browsercontext/#browser-context-wait-for-event
> 
> ```python
> with context.expect_event("page") as event_info:
>     loc.click("button")
> len(context.pages)
> ```

hah, it works! thanks for that!
But why couldn't it get that by my former way, even i wait for long enough? (i've put off `headless`, and i can see that page shows in chromium.

**Comment by aslushnikov** [comment]
> But why couldn't it get that by my former way, even i wait for long enough?

Probably you weren't waiting long enough! 🙃

**Comment by MrDust0** [comment]
> > But why couldn't it get that by my former way, even i wait for long enough?
> 
> Probably you weren't waiting long enough! 🙃

Uh, alright... Anyway, thanks for helping! :)
