### ISSUE TITLE
[Feature] Add Microsoft Edge to list of browsers in playwright config files

### ISSUE THREAD

**Issue by ngaitonde** [microsoft/playwright#10233]
In order to make it easy to automate with Edge, could you update documentation at https://playwright.dev/docs/intro/#creating-a-configuration-file to add a browser configuration for Edge? Thanks.

**Comment by pavelfeldman** [comment]
This would be a change to `npm init playwright` and our configuration docs to include example of 'msedge' next to the example with 'chrome'.
