### ISSUE TITLE
[Question] How to select sibling element?

### ISSUE THREAD

**Issue by axelthat2** [microsoft/playwright#10241]
So I want to select `.invalid-feedback` next to `.form-control`.

I tried doing `.form-control:right-of(.invalid-feedback)` or `.form-control:near(.invalid-feedback)`. Both doesn't work. In JS, I would do `document.querySelector('.invalid-feedback').nextElementSibling`. So how do I select the next sibling?

Reproduction: https://codesandbox.io/s/inspiring-sun-x9rph or https://github.com/axelthat2/playwright-bug-2

**Comment by DvDream** [comment]
What kind of tag do they have? Maybe you can try something like `*tag_name*.form-control:right-of(*tag_name*.invalid-feedback)`

**Comment by aslushnikov** [comment]
> I tried doing .form-control:right-of(.invalid-feedback) or .form-control:near(.invalid-feedback)

@axelthat2 these should work. Do you have a page URL where I can try too?

**Comment by axelthat2** [comment]
@aslushnikov Edited the question to add the reproduction link. Please have a look.

**Comment by aslushnikov** [comment]
> Reproduction: https://codesandbox.io/s/inspiring-sun-x9rph or https://github.com/axelthat2/playwright-bug-2

@axelthat2 I cloned the repo, tried it locally, and the selector does work. The subsequent `expect()` statement does fail, but that's because `<input>` doesn't have any inner text!

**Comment by axelthat** [comment]
@aslushnikov But the selector `input.form-control:near(div.invalid-feedback)` refers to `.invalid-feedback` isn't it? How does it refer to `<input>`?.

**Comment by axelthat2** [comment]
@aslushnikov But the selector `input.form-control:near(div.invalid-feedback)` refers to `.invalid-feedback` isn't it? How does it refer to `<input>`?.

**Comment by DvDream** [comment]
> @aslushnikov But the selector `input.form-control:near(div.invalid-feedback)` refers to `.invalid-feedback` isn't it? How does it refer to `<input>`?.

Because in this way you are selecting a tag giving the indication of its position with respect to another one, but the selected tag should be the first, i.e. the input one. Check the doc here: https://playwright.dev/docs/selectors#selecting-elements-based-on-layout

**Comment by axelthat2** [comment]
Oh haha my bad. Thanks a lot for your help. 

For future readers, this works: `div.invalid-feedback:near(input.form-control)`
