### ISSUE TITLE
--disable-infobars  doesnot work

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#10254]
### Your question

i use all these args. 
but infobars still appears.

    args = [f"--disable-extensions-except={chrome_extension}",
            f"--load-extension={chrome_extension}",
            f'--start-maximized',  # fullscreen 全屏  maximized 最大化
            f'--disable-infobars',
            "--enable-automation=False",
            "--disable-blink-features=AutomationControlled",
            '--disable-gpu',
            '--disable-bundled-ppapi-flash',
            '--mute-audio',
            '--no-sandbox',
            '--disable-setuid-sandbox',
            ]

![111](https://user-images.githubusercontent.com/16624529/141363384-749be617-0490-44e3-8a63-77ad1b541747.png)

**Comment by aslushnikov** [comment]
@viponedream does the infobar appear if you don't use all these arguments?
