### ISSUE TITLE
[Feature] button to launch the inspector from the browser

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#10270]
this could be accomplished with a chrome extension i think, but it would be really useful if there was a button in the browser you could click to open the inspector

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
