### ISSUE TITLE
[BUG] page.screenshot(path="*.png", full_page=True),  “full_page”  invalid . I still get the currently visible viewport

### ISSUE THREAD

**Issue by flatShoes** [microsoft/playwright#10273]
**Context:**
- Playwright Version:  1.16.1
- Operating System: Mac(M1)
- Node.js version: v17.0.1
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
page.screenshot(path="*.png", full_page=True),

**Describe the bug**

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
I tried the following which works for me:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("https://sinusbot.com")
    page.screenshot(path="example.png", full_page=True)
    browser.close()
```

Can you provide us a full example?

**Comment by aslushnikov** [comment]
Please re-file with a repro for us!
