### ISSUE TITLE
[BUG] No cookies in headless mode & specific browser parameters not working

### ISSUE THREAD

**Issue by infonline** [microsoft/playwright#10279]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows 10
- Node.js version: node 17.01, npm 8.1.0
- Browser: Firefox Nightly 93.0, Chromium 97.0.4666.0 (Developer-Build) (64-Bit)
- Extra: -

**Code Snippet**

Below you will find the configuration we use:

```javascript
const config = {
  testDir: 'e2e/tests',
  webServer: {
    command: 'npm run serve',
    port: 8080,
    reuseExistingServer: !process.env.CI,
  },
  use: {
    locale: 'de-DE',
    ignoreHTTPSErrors: true,
    headless: true,
    launchOptions: {
      args: [
        '--disable-features=ImprovedCookieControls,ImprovedCookieControlsForThirdPartyCookieBlocking,SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure',
      ],
      firefoxUserPrefs: {
        'security.ssl.errorReporting.automatic': false,
        'security.tls.version.min': 1,
      },
    },
  },
};
```

**Describe the bug**

1. We are using chromium for testing, our webpage sets a third party cookie. This cookie gets set in debug mode with headful browser, but it doesn't get set in headless mode. What might be responsible for this different behaviour with actually the same setup, except headless mode?

2. If we are using the global playwright config with these settings for multiple browser (firefox and chromium), then Firefox get's started with the Chrome parameters, also. Which leads to Firefox trying to open the whole args as as website. Is this the way launchOptions are treated? Also, it seems that the args for chrome get ignored.

**Comment by yury-s** [comment]
> * We are using chromium for testing, our webpage sets a third party cookie. This cookie gets set in debug mode with headful browser, but it doesn't get set in headless mode. What might be responsible for this different behaviour with actually the same setup, except headless mode?

The feature flags that you pass might be treated differently in headless vs. headful browsers, see relevant discussion in #8940

> * If we are using the global playwright config with these settings for multiple browser (firefox and chromium), then Firefox get's started with the Chrome parameters, also. Which leads to Firefox trying to open the whole args as as website. Is this the way launchOptions are treated? Also, it seems that the args for chrome get ignored.

You can put browser-specific options under corresponding projects:

```js

const config = {
  ...
  use: {
    locale: 'de-DE',
    ignoreHTTPSErrors: true,
    headless: true,
  },
  
  projects: [
    {
      name: 'Desktop Firefox',
      use: {
        browserName: 'firefox',
        launchOptions: {
          firefoxUserPrefs: {
            'security.ssl.errorReporting.automatic': false,
            'security.tls.version.min': 1,
          },
        },
      },
    },
    {
      name: 'Desktop Chromium',
      use: {
        browserName: 'chromium',
        launchOptions: {
          args: [
            '--disable-features=ImprovedCookieControls,ImprovedCookieControlsForThirdPartyCookieBlocking,SameSiteByDefaultCookies,CookiesWithoutSameSiteMustBeSecure',
          ],
        }
      },
    },
  ],
};
```
