### ISSUE TITLE
[BUG] After a download, the page.url() returns the downloaded link, not the current url in the navigation bar

### ISSUE THREAD

**Issue by amunhoz** [microsoft/playwright#10278]
## System:
 - OS: Linux 5.4 Ubuntu 18.04.4 LTS (Bionic Beaver)
 - Memory: 584.59 MB / 15.24 GB
 - Container: Yes
## Binaries:
 - Node: 12.20.0 - /usr/bin/node
 - Yarn: 1.22.11 - /usr/bin/yarn
 - npm: 6.14.8 - /usr/bin/npm
## Languages:
 - Bash: 4.4.20 - /bin/bash
## npmPackages:
 - playwright: ^1.16.3 => 1.16.3 

```javascript

(async () => {
    const { firefox } = require("playwright");
    const browser = await firefox.launchPersistentContext("/tmp/firefox3", {});
    const page = browser.pages()[0]  
    setInterval(async ()=>{
        console.log('current url!', page.url())
     },5000)
    await page.goto('https://speed.hetzner.de/');   
})();
```

**Describe the bug**
Start the code, download a file, then check the current url.
I think the return of url function should be the current url in navigation bar, however it is returning the url of the last downloaded file.

**Comment by yury-s** [comment]
This behavior varies between browsers, [this test](https://github.com/microsoft/playwright/blob/master/tests/download.spec.ts#L53-L77) reflects current state.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
