### ISSUE TITLE
[Question]Getting below warning while using test.slow and test gets skipped

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#10271]
Using page object model in playwright test

Getting below warning while using test.slow and test gets skipped

without annotation slow test is running fine.

just wanted to mark the test as slow,

even after getting the warning, if i tried to run the test,test gets skipped.

![Screen Shot 2021-11-12 at 2 21 12 pm](https://user-images.githubusercontent.com/42768797/141404432-2d157eb2-e757-4714-b644-a5365093e977.png)

```No overload matches this call.
  Overload 1 of 5, '(condition: boolean, description: string): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type 'boolean'.
  Overload 2 of 5, '(callback: (args: PlaywrightTestArgs & PlaywrightTestOptions & { shopifyAdminPage: ShopifyAdminPage; afterpayLoginPage: AfterpayLoginPage; afterpayAdminPage: AfterpayAdminPage; storePage: StorePage; consumerPage: ConsumerPage; } & PlaywrightWorkerArgs & PlaywrightWorkerOptions) => boolean, description: string): void', gave the following error.
    Argument of type 'string' is not assignable to parameter of type '(args: PlaywrightTestArgs & PlaywrightTestOptions & { shopifyAdminPage: ShopifyAdminPage; afterpayLoginPage:
```

**Comment by ltsuda** [comment]
`test.slow()` should be used inside a `test` block or at the root level of the test file. 

I hope this helps.

https://playwright.dev/docs/api/class-test#test-slow

**Comment by jithinjosejacob** [comment]
Here is the structure i used, hope i am in root level .```test.slow(My root)
{ 
  test.step(1)
  test.step(2)
  test.step(3)
}
```

**Comment by mxschmitt** [comment]
No it should be inside your tests, see here: https://playwright.dev/docs/api/class-test#test-slow

**Comment by jithinjosejacob** [comment]
Thanks
