### ISSUE TITLE
[Feature] Warning about the CI performance impact of video and trace recording

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#10281]
While setting up the playwright tests to run on Circle CI, I noticed that my tests were regularly timing out if I enabled 'trace' and 'video' on a Circle CI agent side 'Medium'. Increasing the default timeout and setting each of those configurations to 'on-first-retry' fixed the flakiness, but it might be worth updating the documentation so that users are aware of the performance implications in a CI environment.

**Comment by aslushnikov** [comment]
@unlikelyzero Yeah, all of these naturally add load to the system.

We do [recommend `'on-first-retry'` by default](https://playwright.dev/docs/next/trace-viewer#recording-a-trace). So where would you expect to see the notice about resource usage?

**Comment by unlikelyzero** [comment]
@aslushnikov I think there should be note either on https://playwright.dev/docs/ci/#circleci or -- better yet -- somewhere in the general CI documentation. Maybe even include an example of how to manage a "CI Profile" and a local execution profile in `playwright.config.js`?

I've always had to create a "CI profile" for running e2e tests, but I think the `video` and `trace` limitations are likely due to the new "medium" size CircleCI agents.

**Comment by JoelEinbinder** [comment]
Not sure exactly what kind of warning you would want. PRs welcome.
