### ISSUE TITLE
[Feature] Support opening multiple browser windows and positioning them

### ISSUE THREAD

**Issue by cebaa** [microsoft/playwright#10299]
Right now, `browserContext.newPage()` opens a new tab. That tab can be manually detached into a separate window. It would be useful to support launching detached tabs programmatically or allowing a tab to be programmatically detached after creation. It would also be good if windows could be positioned / resized as needed.

My use case is having the main app that I can control in one window, while using the second window for various secondary functions such as adding various controls that can be used to steer the controller towards different parts of the main app. The windows should not overlap, which suggests changing position / size would be needed as well.

Example: primary window is an online shopping site, secondary window contains a list of products I want to visit. Clicking on various products in the secondary window would cause primary window to be updated as needed (e.g. invoke the search function of the site).

**Comment by JoelEinbinder** [comment]
We do not/will not support position windows because it does not make sense for us in headless modes or with all of our different kinds of browsers. Sorry.
