### ISSUE TITLE
[Feature] Provide additional information for project suites

### ISSUE THREAD

**Issue by DavertMik** [microsoft/playwright#10306]
When building a custom reporter I found out that projects declared in playwright config are treated as top-level suites.
However, there is no way to indicate that this suite has a special meaning.

A suite, as I understand it, is a collection of tests. While a project is a set of tests executed in a specific environment.

Let's see take a look at this as an example. I have 2 projects:

```
  projects: [
    {
      name: 'Desktop Chrome',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'Desktop Safari',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
```
The data I receive in test reports contains Desktop Chrome or Desktop Safari as a suite:

```
  title: 'basic test',
  _only: false,
  results: [
    {
      retry: 0,
      workerIndex: 0,
      duration: 1607,
      startTime: 2021-11-12T23:14:20.903Z,
      stdout: [],
      stderr: [],
      attachments: [],
      status: 'passed',
      steps: [Array],
      error: undefined
    }
  ],
  parent: Suite {
    title: 'example.spec.ts',
    _only: false,
    _requireFile: '/home/davert/demos/playwright-demo/new-project/e2e/example.spec.ts',
    suites: [],
    ...
    },
    parent: Suite {
      title: 'Desktop Chrome',
      _only: false,
      _requireFile: '',
      suites: [Array],
      tests: [],
      location: undefined,
      parent: [Suite],
```

However, I can't understand if Desktop Chrome is a regular suite name or a project.
If Desktop Chrome and Desktop Safari are different on browsers, how can I obtain this information?

My suggestions:

* add to project suites property `project: true`
* include project suites to add `use:` property where information on `use` config is stored.

**Comment by JoelEinbinder** [comment]
Why do you need this distinction? We consider every way in which a test could be run to be unique.

**Comment by DavertMik** [comment]
@JoelEinbinder This distinction affects how reporting tools can analyze this information

It should be understandable if this was the same test executed in different environments or different tests with the same name executed in different suites.

If this was the same test executed in different environments it would be nice to collect all information about its execution in one place.

**Comment by dgozman** [comment]
There is a `Suite.project()` API for this: https://playwright.dev/docs/api/class-suite#suite-project.
