### ISSUE TITLE
[Question]Can we use custom reports along with built in reports? if Yes, how should the playwright config look ?

### ISSUE THREAD

**Issue by Palak-Jethwani** [microsoft/playwright#10315]
We have custom reporter implemented which we want to use only for console log printing and using built-in and third party reporters for html reports. I am not able to use custom reporters along with others. How can use both ?

`reporter: [
        ["dot"], 
        ["json", { outputFile: "test-result.json" }],
        ['experimental-allure-playwright'],
    ],
    //reporter: './utils/Listeners/TestListener.ts',`

**Comment by DavertMik** [comment]
Works for me even with config options to be passed into constructor:

```
  reporter: [
    ['list'],
    ['/home/myname/projects/playwright-reporter/lib/adapter/playwright.js', {
      configOpt: 111,
    }]
  ],
```

**Comment by Palak-Jethwani** [comment]
Thanks.. let me try

**Comment by Palak-Jethwani** [comment]
`reporter: [
        ['dot'], 
        // ["json", { outputFile: "test-result.json" }],
        // ['experimental-allure-playwright'],
        ['./utils/Listeners/TestListener.ts']
    ],`

updated as above and this is working.
