### ISSUE TITLE
[Feature] show timeout value & countdown timer in the inspector

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#10311]
it would be nice if this showed a countdown timer so you know how much longer it's going to wait

![image](https://user-images.githubusercontent.com/57028336/141711403-2a28c369-f456-48f8-bde2-2c917d61b8bf.png)

**Comment by JoelEinbinder** [comment]
Ooh I like this! Maybe it should appear after 3 seconds to avoid being noisy

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by DetachHead** [comment]
@pavelfeldman could you please clarify what "handfull of upvotes" means? is there a specific amount of upvotes an issue needs to stay open?

either way, issues shouldn't be closed just because of that imo. while i understand marking them as low priority if they don't get much attention, all closing them does is prevent them from gaining any more upvotes in the future because i'd have to "open a new issue and link this one", which basically just resets the upvote counter
