### ISSUE TITLE
[BUG] inspector pauses on `goto`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#10313]
**Context:**
- Playwright Version: 1.16.1
- Operating System: windows 10
- Node.js version: 16.9.1
- Browser: chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage()
  await page.goto('https://google.com/')
})();
```

**Describe the bug**

when running playwright with `PWDEBUG=1`, it pauses on `page.goto` even though no breakpoint is set

![image](https://user-images.githubusercontent.com/57028336/141713894-e7c0f3b3-17a1-4daf-8aa1-18c2de872bd2.png)

Add any other details about the problem here.

**Comment by yury-s** [comment]
This is intentional behavior, the inspector will stop on the first action in your test so that you can continue stepping from there on (in the example above it happens to be goto). See also this feature request: https://github.com/microsoft/playwright/issues/7008
