### ISSUE TITLE
Why page.isVisible() would fail?

### ISSUE THREAD

**Issue by mtt87** [microsoft/playwright#10319]
I have a page with a `Skip` Button that's visible and if I pause the test and use the Explore feature I can see it can be correctly highlighted but for some reason `page.isVisible()` returns `false`, what could possibly be the reason?

![Screenshot 2021-11-15 at 11 46 31](https://user-images.githubusercontent.com/2150927/141777653-9a8cf48f-1901-4e24-9fad-32f26ba7d712.png)

I've checked other issues not sure if this is related but the only thing I can think about is that the "modal" library is creating a fixed div on top of the page that's transparent, could it interfere with Playwright understanding the visibility?
![Screenshot 2021-11-15 at 11 49 37](https://user-images.githubusercontent.com/2150927/141778624-44e8fe0f-0e0d-4f0a-a3d0-6634c073152f.png)
?

**Comment by casr** [comment]
In case you've not seen, there is this note on the documentation about `isVisible`

> `locator.isVisible([options])` does not wait for the element to become visible and returns immediately.

i.e. you need to make sure that the element you're looking for is stable by the point you check for it.

**Comment by mtt87** [comment]
I believe it is, according to https://playwright.dev/docs/actionability/#stable
Visually the buttons are there even before I check for the 2 input above
```js
await page.waitForSelector('[data-testid="full_name"]')
await page.waitForSelector('[data-testid="email"]')
```
So I would expect that after waiting for the 2 inputs to appear, the buttons are stable in the same position.
I can try adding a timeout to see if it changes behaviour 😄

**Comment by yury-s** [comment]
We recommend using [`expect().toBeVisible()`](https://playwright.dev/docs/test-assertions#expectlocatortobevisibleoptions) which will wait for the element to be in the visible state if it fails will print log of the checks and why they failed. You can also enable logging via `DEBUG=pw:api` to see why the element is considered not visible.

If it is still doesn't work please open a new issue with a repro.
