### ISSUE TITLE
[BUG] [PW 1.8.0] [Chromium] Error: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by dipiash** [microsoft/playwright#10316]
Hello! Our team have the same issue (https://github.com/microsoft/playwright/issues/4764). 

Local test pass. Remote test (on the https://aerokube.com/moon/) fail because can't wait when page loaded.

Tests was start for the same page: https://dasreda.ru/

**Context:**
Playwright Version: 1.16.3  (the same behavior on 1.8.0)
Operating System: Windows
Node.js version: v14.18.1
Browser: chromium
Extra: codeceptjs (3.0.4 / the same behavior on 3.1.3)

**Code Snippet**
Simple launching a browser and navigating to a page.

**LOGs**
Success (local) - [local-log.log](https://github.com/microsoft/playwright/files/7536956/local-log.log)
Error (Remote) - [remote-moon-log.log](https://github.com/microsoft/playwright/files/7536958/remote-moon-log.log)

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one with a repro script and link to this issue when you get back to it! Please also make sure that you are using most recent Playwright version (we don't release bug fixes for 1.8.0 anymore).

**Comment by dipiash** [comment]
@yury-s thanks for your attention! I was create new issue and repo example - https://github.com/microsoft/playwright/issues/10552
