### ISSUE TITLE
Playwright misreports test results when one of the tests has a bad fixture

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10324]
### Discussed in https://github.com/microsoft/playwright/discussions/10310

<div type='discussions-op-text'>

<sup>Originally posted by **andrejs-ps** November 14, 2021</sup>
**Note**: I am aware of how to use the correct fixtures, and I am not asking to fix the code. Rather, I am reporting that Playwright's behavior/reporting may be misleading if the code is set up wrong and the person is trying to figure out why. I stumbled upon this while experimenting.

See the below code. One test is `test.only()`, the other is provided with a non-existing fixture (imagine a new user not fully familiar with the API). When you run this, Playwright says that it is running only one test (expected), but then still checks and complains about a non-existing fixture (unexpected, given the `test.only()`), and then fails the `test.only()` that is by itself correct. Without a second test with the wrong fixture, the first test passes.

Expected behavior: 
1) (maybe) don't make playwright check for fixture correctness that are not included in the `test.only()`
2) playwright shouldn't fail the first test, which is correct by itself

```
const { test } = require('@playwright/test');

test.only('Playwright: top-level object', async ({ playwright }) => {

    const browserType = await playwright.firefox.launch();
    const ctx = await browserType.newContext();
    const page = await ctx.newPage();
    
    await page.goto('http://localhost:3000/'); // or other
});


// the below should be ignored, but Playwright still checks it and makes the above test fail
// ✘  tests\m8-configuration\_1fixtures-fail.test.js:3:6 › Playwright: top-level object (0ms)
// 1) tests\m8-configuration\_1fixtures-fail.test.js:3:6 › Playwright: top-level object =============
//   Error: Test has unknown parameter "browserType".
// Test defined at tests\m8-configuration\_1fixtures-fail.test.js:18:1
test('BrowserType - not a fixture', async ({ browserType }) => {

    // ..
});
```</div>

**Comment by dgozman** [comment]
Fixed by #10328.
