### ISSUE TITLE
[BUG] Fetching webgl2 canvas context does not work in Firefox headless mode

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#1032]
**Context:**
- Playwright Version: 0.10.0
- Operating System: Mac

**Code Snippet**

Running within a page:

```javascript
// Should be non-null on Firefox
canvas.getContext('webgl2');
```

**Describe the bug**

Fetching the `webgl2` context of a canvas returns null when Firefox is running in headless mode but not when running with the window displayed. This prevents me from running the webgl renderer tests of [xterm.js](https://github.com/xtermjs/xterm.js) on firefox.

Note that it happens always on webkit [but that's expected](https://caniuse.com/#search=webgl2).

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
