### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#10327]
**Context:**
- Playwright Version: 16 latest today
- Operating System: Linux
- Node.js version: 14.17.6
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
// MDXLocators.IMAGE_IMG = ".ant-image .ant-image-img";
const countImg = await this.locator(MDXLocators.IMAGE_IMG).count();
await test.step('Count loaded images', async () => {
await expect(this.locator(MDXLocators.IMAGE_IMG)).toHaveCount(this.counters.image, { timeout: 0 });
const imgExtensionRegexp = new RegExp(".+\.(png|img|ico|gif|jpe?g|tiff?|webp|bmp)$", "i");

for (let index = 0; index < countImg; index++) {
     const elementImg = this.locator(MDXLocators.IMAGE_IMG).nth(index);
     await expect(elementImg).toHaveAttribute("src", imgExtensionRegexp, {timeout: 0});
   }
});
```

**Describe the bug**

I'm using parameter **timeout: 0** in method toHaveAttribute, but it's not working, because test execute 10 seconds when it fails.

in config I have timeout's:

```typescript
const config: PlaywrightTestConfig = {
  timeout: 10000, // default 30000
  use: {
    ignoreHTTPSErrors: true,
  },
  reporter: [
    ['allure-playwright'],
    ['dot'],
  ],
  projects: [
    {
      name: 'Chrome',
      use: {
        browserName: 'chromium',
        channel: 'chrome',
      },
      expect: {
        timeout: 3000, // default 5000
      }
    },
  ],
};
```

**Comment by cardinalX** [comment]
Screenshots of bug https://playwright.slack.com/archives/CSUHZPVLM/p1636994516289900
![Uploading Снимок экрана 2021-11-15 в 19.39.46.png…]()

**Comment by pavelfeldman** [comment]
> timeout: 10000, // default 30000

You tell test to timeout after 10 seconds, so it does.

**Comment by cardinalX** [comment]
Logically, the value passed by the parameter should override the value in the config for a specific check, isn't it? If not, then it is at least more convenient

**Comment by cardinalX** [comment]
> > timeout: 10000, // default 30000
> 
> You tell test to timeout after 10 seconds, so it does.

Logically, the value passed by the parameter should override the value in the config for a specific check, isn't it? If not, then it is at least more convenient.

This is also logical, as if the passed parameter overrides the default value of 30 seconds. The only difference is that I redefined the standard value in the config from 30 to 10
@pavelfeldman

**Comment by JoelEinbinder** [comment]
This is working as intended. The timeout inside expect is for that expect. The timeout for the test is for the whole test. You need to disable both if you want both to never timeout.
