### ISSUE TITLE
[Feature] Parametrization API for Playwright Test

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#10325]
### Discussed in https://github.com/microsoft/playwright/discussions/10283

<div type='discussions-op-text'>

<sup>Originally posted by **andrejs-ps** November 12, 2021</sup>
Currently, there is no API to parametrize individual tests. 

To pass in a single parameter, one would use a for loop, as suggested in the documentation (https://playwright.dev/docs/test-parameterize)

```
const people = ['Alice', 'Bob'];
for (const name in people) {
  test(`testing with ${name}`, async () => {
    // ...
  });
}
```

For two parameters, one can iterate over keys and values of a map.
This isn't exactly a clean solution, but it gets harder for 3+ parameters

```
for (const [a, b, c] of [["a", 1, 2], ["b", 3, 4], ["c", 5, 6]]) {
    test(`testing with ${a}  ${b} ${c}`, async () => {
        console.log(a, b, c);
    });
}
```

I believe Playwright would benefit from a parametrization API, similar to Java's TestNG or JUnit.
Example from JUnit:

```
@ParameterizedTest
@CsvSource({"a,1", "b,2", "foo,3"})
```

Given that Playwright has:

`test.use({ viewport: { width: 600, height: 900 } });`

Playwright could have as below for a single test or a group of tests

`test.parameters("a,1", "b,2", "foo,3"});`
</div>

**Comment by mxschmitt** [comment]
Linking https://github.com/microsoft/playwright/issues/7036 and thats the [Pytest way](https://docs.pytest.org/en/6.2.x/parametrize.html) for inspiration

**Comment by TimeInvestor** [comment]
Would like to see this feature gets implemented very much 👍

**Comment by pheeel** [comment]
We're looking forward to this.

**Comment by p01** [comment]
One aspect that would super useful is if we could create the `test(description, method)` based on the result of a `test.beforeAll(...)` or even better of a `globalSetup.ts` script.

My main idea and concern is to ensure that Playwright Test uses the most appropriate number of workers.

**Comment by dgozman** [comment]
> One aspect that would super useful is if we could create the `test(description, method)` based on the result of a `test.beforeAll(...)` or even better of a `globalSetup.ts` script.

You can do this with `globalSetup.ts` - just write some data to a file in the `globalSetup`, and then read it in your test file.

```ts
// example.spec.ts

const testCases = require('./generated-by-global-setup.json');
for (const { title, url } of testCases) {
  test(title, async ({ page }) => {
    await page.goto(url);
    expect(await page.screenshot()).toMatchSnapshot('default.png');
  });
}
```

**Comment by pavelfeldman** [comment]
Closing as per above.

**Comment by xelact** [comment]
> > One aspect that would super useful is if we could create the `test(description, method)` based on the result of a `test.beforeAll(...)` or even better of a `globalSetup.ts` script.
> 
> You can do this with `globalSetup.ts` - just write some data to a file in the `globalSetup`, and then read it in your test file.
> 
> ```ts
> // example.spec.ts
> 
> const testCases = require('./generated-by-global-setup.json');
> for (const { title, url } of testCases) {
>   test(title, async ({ page }) => {
>     await page.goto(url);
>     expect(await page.screenshot()).toMatchSnapshot('default.png');
>   });
> }
> ```

After this change #12018 in v1.19, it is no longer possible to dynamically create test cases based on some data written in the `globalSetup.ts` as the global setup runs after listing the test cases, is there any workaround?

**Comment by dgozman** [comment]
@xelact No workaround for now. I'd suggest a separate step before `npm run test`, something like `npm run generate-tests`.
