### ISSUE TITLE
[Feature] - Integrate with ADO (Test Cases)

### ISSUE THREAD

**Issue by MitchMcCoy502** [microsoft/playwright#10321]
Add the ability to integrate test results with ADO similar to how xUnit/nUnit work with C# by linking a ADO test case to a test through the test explorer in Visual Studio

**Comment by MitchMcCoy502** [comment]
This is what I am referring to. This would allow more seamless integration with ADO 

![image](https://user-images.githubusercontent.com/88807661/142200500-010ea20d-ceb6-48ad-8e62-3fcfcd31b95b.png)

![image](https://user-images.githubusercontent.com/88807661/142200553-eb6fea7a-ebbe-4d9f-a1d5-44c74a8ff8d3.png)

**Comment by PandaMagnus** [comment]
Wouldn't you still be able to do this if you're writing your Playwright tests in C# using xUnit/nUnit/MSTest? Are you writing your tests in TS/JS or Python? As a work-around you might be able to use a C# unit test method to invoke a test with TS/JS or Python. I've worked on teams in the past that did that for Java-based tests.

Granted, philosophically I have some issues with this approach as it _tends_ to get abused by teams that don't understand the pros and cons of automated tests vs manual tests. But if you're using this purely to surface results in more transparent ways, I could see the value here.

**Comment by MitchMcCoy502** [comment]
Yes, I am using TypeScript.

My hope is that there would be a seamless integration with ADO/Playwright. I would prefer to not create a 'hacky' solution

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
