### ISSUE TITLE
[BUG] cannot select playback time on html report video

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#10333]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 17.0.1
- Browser: Chromium

**Code Snippet**

```typescript
import { test } from "@playwright/test";

test("example", async ({ page }) => {
	await page.goto("https://www.google.com");
	const s = page.locator("input[name=q]");
	await s.fill("example");
	await page.waitForTimeout(5000);
	await s.fill("overwritten");
	await page.waitForTimeout(5000);
});

```

**Describe the bug**

When trying to select other times (rewind/forward) on the video, the clip continues to play from its current location.

When I play the video in `test-results`, I can rewind/forward it as expected

https://user-images.githubusercontent.com/20273647/141875252-7d8f47fe-f6d7-474b-83fb-fa12174f9dae.mp4

**Comment by mxschmitt** [comment]
I was able to repro, reason for that is that our web-server does not support range requests.
