### ISSUE TITLE
[BUG] HTML report served from file:// url and trace attachments

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#10336]
- configure tracing as `on`
- generate an HTML report
- open html report as a static HTML, navigating to its `file://` url
- try opening trace attachment in the HTML report

Expected: trace viewer is opened, or maybe navigated to online viewer?
Actual: blank screen

**Comment by MartinP-Autopilot** [comment]
We are having similar problems although we are downloading the trace.zip from CICD and opening locally via `npx playwright show-trace <path to zip>\trace.zip`.

When I look at the devtools for the trace viewer, I see we're getting a 404 for http://127.0.0.1:9322/trace/manifest.webmanifest.

I am on Playwright 1.16.2

**Comment by michalkrupiarz** [comment]
Same here for C# and Java. I`m getting error while loading manifest file in console. Files with data are in the zip. Those are simply not loaded. Only thing that is visible are screenshots.

**Comment by pavelfeldman** [comment]
Missing manifest is not an issue, does Trace Viewer not work for you?

Btw, you can try using https://trace.playwright.dev as well.

**Comment by michalkrupiarz** [comment]
@pavelfeldman 
Hello. Trave viewer is starting but is showing no data. Only screenshots. Take a look:
![image](https://user-images.githubusercontent.com/11883254/143194859-0dd6d276-ff92-4dcc-ac36-2378fd13ff0d.png)

Same file loaded to your link: 
![image](https://user-images.githubusercontent.com/11883254/143195183-233a6623-a3f2-4981-90d6-a3393afc7e4b.png)

**Comment by pavelfeldman** [comment]
Ok, so I believe this will self-fix with 1.17 that is about to go live tomorrow. You can already give it a try with @1.17.0-rc1. Please let us know if it does not work for you!

**Comment by MartinP-Autopilot** [comment]
@pavelfeldman , we are now on 1.17 and still having the same issue (both in local trace viewer and https://trace.playwright.dev

**Comment by wuweikd** [comment]
The 1.19.2 have the same issue  at my docker, bug the 1.18.1 at my macos wroker well
