### ISSUE TITLE
[Question]How can we use browserType.launch([options]) in Playwright Test Config

### ISSUE THREAD

**Issue by Palak-Jethwani** [microsoft/playwright#10348]
Scenario : Fake camera device for the test scenario

Query: In order to be able to suppress camera permissions and use fake camera for video stream in stead of live video we need to set following firefox preferences : 
`"media.navigator.streams.fake": true, 
"media.navigator.permission.disabled": true`

in my current framework implementation, I am using playwright test config to launch browser with certain options and permissions. I am able to launch chromium with these config and conduct my test successfully and wish to do the same for firefox and webkit but i get error as browserType.lauch([options]) is not PlaywrightTestOptions. So how can i achieve this ? I don't want to create browser every time before running each test.

Here is the my current config:

```ts
import { PlaywrightTestConfig } from "@playwright/test";
import * as playwright from "playwright";

const config: PlaywrightTestConfig = {
    
    use: {
        headless: true,
        screenshot: "on",
        trace: "retain-on-failure",      
        acceptDownloads : true,       
    },
    projects:[
        {
            name:"chrome",
            use:{
                browserName:"chromium",
                permissions:["camera"],
                launchOptions:{
                    args:[
                        "--no-sandbox",
                        "--disable-setuid-sandbox",
                        "--use-fake-device-for-media-stream",
                        "--use-fake-ui-for-media-stream",
                        "--use-file-for-fake-video-capture=./data/fakeCameraCapureDP.y4m"
                    ]
                }
            }
        },
        {
            name:"firefox",
            use:{
                browserName:"firefox",
                launchOptions:{
                    args:[
                        "--quiet",
                        "--use-test-media-devices" 
                    ]
                }               
            },
        },
        {
            name:"safari",
            use:{
                browserName:"webkit"
            }
        }
    ],
    retries: 0,
    timeout: 1000000,
    reporter: [["dot"], ["json", { outputFile: "test-result.json" }],
    ['experimental-allure-playwright']],
    testDir : 'test',
}
export default config;

```

**Comment by JoelEinbinder** [comment]
This config looks right to me. Inside firefox id do something like
```js
        {
            name:"firefox",
            use:{
                browserName:"firefox",
                launchOptions:{
                    args:[
                        "--quiet",
                        "--use-test-media-devices" 
                    ],
                    firefoxUserPrefs: { "media.navigator.streams.fake": true, "media.navigator.permission.disabled": true }
                }               
            },
        },

```

Can you please provide the exact error message you are receiving? Thanks!

**Comment by Palak-Jethwani** [comment]
> This config looks right to me. Inside firefox id do something like
> 
> ```js
>         {
>             name:"firefox",
>             use:{
>                 browserName:"firefox",
>                 launchOptions:{
>                     args:[
>                         "--quiet",
>                         "--use-test-media-devices" 
>                     ],
>                     firefoxUserPrefs: { "media.navigator.streams.fake": true, "media.navigator.permission.disabled": true }
>                 }               
>             },
>         },
> ```
> 
> Can you please provide the exact error message you are receiving? Thanks!

Thanks @JoelEinbinder - worked for me now. I did spelling mistake - was using firefoxUserPref instead of Pref**s**
