### ISSUE TITLE
[Question] Having issue using es2020 operator chaining with playwright docker

### ISSUE THREAD

**Issue by galzunited** [microsoft/playwright#10344]
While running it in the container I'm getting the following:

11:38:00  You may need an additional loader to handle the result of these loaders.
11:38:00  | 
11:38:00  |     getLockedParam() {
11:38:00  >       return this.lockedParams?.get(this.param.name);
11:38:00  |     }
11:38:00  | 
11:38:00  

I'm using playwright docker image which is using node v14.18.1.

**Comment by mxschmitt** [comment]
This error does not look like its coming from Playwright or Playwright's test-runner `@playwright/test`. When using Playwright's own test-runner you can use the optional chaining operator which works out of the box.

**Comment by galzunited** [comment]
When I run it locally it works fine with with "playwright": "^1.16.1", but when I run it in docker container on ubuntu I am getting this error. That is why I suspect it is related to playwright docker image somehow.

**Comment by JoelEinbinder** [comment]
This looks like a webpack error. Doesn't sound like this bug is related to playwright.

**Comment by galzunited** [comment]
Will look into it. Thanks.
