### ISSUE TITLE
[Question] What permissions are required by android-driver.apk and android-driver-target.apk and in which scenarios does this apk gets installed? 

### ISSUE THREAD

**Issue by karanshah-browserstack** [microsoft/playwright#10342]
What permissions are required by android-driver.apk and android-driver-target.apk as I cannot find on my mobile device?
What is the scenario does these apk's gets installed? 
Which apk gets installed on the mobile device?

**Comment by JoelEinbinder** [comment]
The android driver is used to automate content outside of the webview, using the [AndroidDevice](https://playwright.dev/docs/api/class-androiddevice) api. They are installed by playwright automatically whenever it is used. If you provide the error message you are receiving I can try to help further.
