### ISSUE TITLE
[Question] Running global setup as headless/non-debug when using PWDEBUG=1?

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#10359]
Hi

I've been using global config to create login state for 3 different types of users which each test reuses - this is awesome

I am wondering how to go about not running the global setup as non-debug mode when using PWDEBUG=1?

Since it uses 3 browsers it's a little bit annoying to have to "continue" each browser before getting to the actual test to debug.

As a workaround I use a custom npm task defined as:        

`"debug": "npx playwright test --headed --timeout=0",`

so I can run `npm run debug` which doesn't show the global setup as headed - is there a way to use PWDEBUG instead?

Thanks again for your great work on Playwright

**Comment by aslushnikov** [comment]
@alisterscott do I understand correctly that you don't like the inspector windows that pops up for your globalsetup browser?

**Comment by alisterscott** [comment]
> do I understand correctly that you don't like the inspector windows that pops up for your globalsetup browser?

yes

**Comment by JoelEinbinder** [comment]
You can work around this by setting `process.env.PWDEBUG` manually in your tests or in your globalSetup. It is a bit of a hack though.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
