### ISSUE TITLE
[Feature] expanding toHaveCount (greaterThan, greaterThanOrEqual, lessThan, lessThanOrEqual)

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#10367]
To expand on https://github.com/microsoft/playwright/issues/8725

The reason why `toHaveCountGreaterThan`, and its variants, are important, is that I may not know how many exactly I am expecting.

For example:

If I have filtered a table, and currently have 3 results. When I click on the "reset" button, I would expect to have more than 3 results (we definitely don't expect results that are less than 3), but won't necessarily be sure how many exactly.

This scenario would apply to testing in UAT (where I would not have full control over the data, and would not be able to create as consistent of a state).

**Comment by Jovan27** [comment]
I would also love to have this feature, migrating from cypress to playwright would be much easier.

**Comment by pavelfeldman** [comment]
Starting with Playwright 1.21 you'll be able to

```js
await expect poll(() => locator.count()).toBeGreaterThan(3);
```
