### ISSUE TITLE
[BUG] Assertion error without message on any action probably when page uses webSockets

### ISSUE THREAD

**Issue by Evilweed** [microsoft/playwright#10375]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Mac
- Node.js version: v16.13.0
- Browser: Chromium
- Extra: ---

## System:
 - OS: macOS 11.6
 - Memory: 23.66 MB / 16.00 GB
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - Yarn: 1.22.15 - /usr/local/bin/yarn
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Sadly this bug occurs in Admin panel of our app. We cannot provide public access to it. But... **Can we get on a call with any of your employees to debug this, or can we send over the email access to our server (it will be a short lived access - like 1-2 days, for security reasons.)**

**Describe the bug**
We believe that Playwright errors out with "Assertion Error" and without any additional information when page uses webSocket. In our case it is Rails Cable https://guides.rubyonrails.org/action_cable_overview.html .

We really need this to be debugged and fixed, and we are willing to help with the reproduction case, but it is our admin panel so we need to do this in secure way.

Here are screenshots of debug info (had to obfruscate part of the output for security reasons):
![CleanShot 2021-11-17 at 12 37 54@2x](https://user-images.githubusercontent.com/5477821/142193926-fca2619c-d3d5-4b62-a178-4dc74818e9c8.png)

![CleanShot 2021-11-17 at 12 40 42@2x](https://user-images.githubusercontent.com/5477821/142194555-6e37447d-8ac9-4453-bd9c-b0ea7a65ba12.png)

![CleanShot 2021-11-17 at 12 47 02@2x](https://user-images.githubusercontent.com/5477821/142195342-10099822-96ab-43f0-b3d1-04a3b3eca729.png)

**Comment by aslushnikov** [comment]
> Can we get on a call with any of your employees to debug this, or can we send over the email access to our server (it will be a short lived access - like 1-2 days, for security reasons.)

@Evilweed could you create a minimal reproducible for us so that we can look into this in our own time?

**Comment by Evilweed** [comment]
@aslushnikov we can create smallest testcase that reproduce the issue, and add basic auth credentials to our server just for your team to be able to run the test, but we cannot share those here publicly because it is our Admin Panel app. And we would prefer to book specific dates when basic auth will be set for you guys. 

How can we communicate privately?

**Comment by JoelEinbinder** [comment]
> @aslushnikov we can create smallest testcase that reproduce the issue, and add basic auth credentials to our server just for your team to be able to run the test, but we cannot share those here publicly because it is our Admin Panel app. And we would prefer to book specific dates when basic auth will be set for you guys.
> 
> How can we communicate privately?

If the small test case involves connecting to your server than it is not small. We need code we can run and study on our own machines otherwise there is simply too much surface area for us to look at.

**Comment by dgozman** [comment]
@Evilweed If you could run with `DEBUG=pw:protocol,pw:channel*` and send us the logs (note that it may contain some private information), there would be a small-ish chance that we can figure out the issue. You can send the logs to dgozman [at] microsoft [dot] com.

**Comment by Evilweed** [comment]
@JoelEinbinder sadly we do not have any developer to create Ruby on Rails app with Cable endpoint from scratch that would run on your machines

**Comment by Evilweed** [comment]
@dgozman you should have the debug file in your email - sent just now.

**Comment by digideon** [comment]
Hi, looks like I have run into the same issue, with Playwright Version 1.16.3
![image](https://user-images.githubusercontent.com/93126380/143459832-926abc16-bf94-41d4-8b6a-e07298607451.png)

Is the fix in version 1.16.3 please?
