### ISSUE TITLE
[Question] Duplication of information in the log

### ISSUE THREAD

**Issue by Gornostalev** [microsoft/playwright#10370]
Hello 🖐, can i reduce the amount of duplicate information in the log?
 ``` code snippet 
Error: expect(received).not.toBeVisible()
Call log:
- waiting for selector "//div[div[@class="eos-date-picker-wrapper"]] >> .SvgDot"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
-   selector resolved to <svg width="1em" height="1em" class="SvgDot" font-siz…>…</svg>
-   unexpected value "true"
427 |       await control.datePickerInput.click();
```
Thank you for Playwright♥

**Comment by vsravuri** [comment]
I believe the `unexpected value "true"` is written each time the locator retry until it times out.

**Comment by dgozman** [comment]
@Gornostalev What would you like to see - just two lines in this case? Is there anything else that would be useful for you in the log?

**Comment by Gornostalev** [comment]
@dgozman, Yes, I think 2 lines would be a great option, at the moment this is the only suggestion

**Comment by DavertMik** [comment]
Please take a look at referenced issue.

There are few more things that can be improved:

* text diffs on failure could be more useful
* error messages to not contain special characters

But again, thanks for making and improving playwright!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
