### ISSUE TITLE
[Question] Adding browser console error logs into HTML Reporter?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10373]
Hi, is it possible to store on the HTML report the errors from the browser console when a test fails? I've read how to consol.log the errors from it, but I think it would be useful to understand what happened to the test not only from a "selector POV" from the selector as well. Thank you :)

**Comment by aslushnikov** [comment]
@DvDream [playwright tracing](https://playwright.dev/docs/trace-viewer) already does this and much more. Would it work for you?

**Comment by vsravuri** [comment]
I'll vote for this feature without enabling Trace. Enabling Trace increase my test duration significantly.

**Comment by DvDream** [comment]
> @DvDream [playwright tracing](https://playwright.dev/docs/trace-viewer) already does this and much more. Would it work for you?

Thank youuu!! I've never noticed that tab on the trace because I never needed it, but Is really cool actually!
By the way, for what concern a possible new feature, I was thinking something like let all those errors directly  appearing on the Error tab on the report view. Maybe in that case trying to debug for the point where an error was thrown could be worse though. I don't know, I'm just thinking out loud ahahah

Thank you again! :D
