### ISSUE TITLE
[BUG] - Folder with name Reports does not execute any tests in that folder

### ISSUE THREAD

**Issue by eugeniuszG** [microsoft/playwright#10377]
**Context:**
- Playwright Version: 1.16
- Operating System: Windows
- Node.js version: 14.16

**Describe the bug**
When folder have name of "Reports" playwright does not see any tests inside these folder.
![image](https://user-images.githubusercontent.com/41344500/142220235-6ea2b209-e094-494c-8a6b-656444d6cb3f.png)
File has 8 tests but playwright does not see it.
![image](https://user-images.githubusercontent.com/41344500/142220022-45d059f7-0a99-47c4-9109-2e578e6ea6e6.png)

**Comment by aslushnikov** [comment]
@eugeniuszG could you please clarify? I don't follow what's wrong here

**Comment by eugeniuszG** [comment]
Please pay attention to name of the folder. But in the folder I have some tests.
![image](https://user-images.githubusercontent.com/41344500/142268222-7ec419fc-9468-447c-badd-644ce6e0306d.png)
![image](https://user-images.githubusercontent.com/41344500/142268292-c508615c-1dd2-42f1-9377-5238f46420df.png)

**Comment by eugeniuszG** [comment]
@aslushnikov
UPD: I've noticed that folder with name "Reports" was in .gitignore file
So I assume any folder which listed in .gitignore and contain tests - they are does not executed.

**Comment by JoelEinbinder** [comment]
We indeed skip anything in the `.gitignore`. This is working as intended.
