### ISSUE TITLE
[Question] Use a more popular screen resolution as default viewport?

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#1037]
Looking at [statcounter](https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide) it seems that the top 3 desktop screen resolutions are:

```
1366x768 - 23.09%
1920x1080 - 21.04%
1536x864 - 7.05%
```

Would it be better to use 1366x768 as the default viewport size, instead of 800x600?

**Comment by pavelfeldman** [comment]
How about 1280x720? Rationale is that it is already 16x9 and it is close to the non-maximized browser window taking most of the screen.

**Comment by arjun27** [comment]
yeah, I also prefer the wholeness of 1280 vs 1366.

**Comment by JoelEinbinder** [comment]
960 is the default width on mobile when displaying desktop sites.

**Comment by pavelfeldman** [comment]
@JoelEinbinder we emulate desktop by default, so I don't think 960 is relevant there. We should default desktop to popular desktop size and default mobile to popular mobile size. Neither one is 960. If mobile is true and site has no viewport config - 960 happens on its own.
