### ISSUE TITLE
[BUG] Firefox ignores testOptions.trace = 'retain-on-failure'

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#10397]
**Context:**
- Playwright Version:1.16.2
- Operating System: Windows and Linux
- Node.js version: 14.17.3
- Browser: Firefox
- Extra: browser created from BrowserType.launch, not from built-in fixture (not sure if that is relevant)

**Code Snippet**

```//// @ts-check
///** @type {import('@playwright/test').PlaywrightTestConfig} */

import {PlaywrightTestConfig} from '@playwright/test';

const config = {
  testDir: 'tests',
  use: {
    headless: false,
    viewport: {width: 1920, height: 1080},
    video: 'on-first-retry',
    trace: 'retain-on-failure',
  },
  reporter: 'html',
};

module.exports = config;
```

**Describe the bug**

When I set `trace: 'retain-on-failure'` either in the config as per above, or in `test.use` in the spec, I get traces for failed tests when I use Chromium, but not if I use Firefox.

I _can_ get traces for Firefox with the API strategy defined on https://playwright.dev/docs/api/class-tracing/ (which information is misleading as it needs to be wrapped in a `try/catch/finally` block to work), but that is far from ideal.

**Comment by JoelEinbinder** [comment]
Can you please show your code that you are using to launch your chromium and firefox browsers? Thanks.

**Comment by MartinP-Autopilot** [comment]
Hi @JoelEinbinder,

This is basically it - 

```import {chromium, firefox, webkit, BrowserType, Browser, LaunchOptions} from '@playwright/test';

export default class BrowserFactory {
  static async getBrowser(): Promise<Browser> {
    const reqdBrowser = process.env.BROWSER ? process.env.BROWSER.toLowerCase() : 'chromium';
    let browserType: BrowserType;
    let launchOptions: LaunchOptions = {};
    switch (reqdBrowser) {
      case 'chromium':
        browserType = chromium;
        launchOptions.args = ['--disable-dev-shm-usage'];
        break;
      case 'firefox':
        browserType = firefox;
        break;
      case 'webkit':
        browserType = webkit;
        break;
      default:
        browserType = chromium;
        break;
    }
    console.log(`browserType.executablePath(): ${browserType.executablePath()}`);
    let browser = await browserType.launch(launchOptions);
    console.log(`browser.version(): ${browser.version()}`);
    return browser;
  }
}
```
