### ISSUE TITLE
[BUG] ElementHandle swallows errors received when initializing previews

### ISSUE THREAD

**Issue by sax** [microsoft/playwright#10391]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 16.5.0
- Browser: Chromium
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

We regularly see flaky failures in our tests using Playwright, specifically around `querySelectorAll`, with the selector of `css=div`. We then receive a message such as: 
```json
{"guid": "browser-context@3d8a2dbb722b6de31105d9c0849dfde6", "method": "__create__", "params": {"guid": "handle@5ddd5bc571daab6b1402099cb1e14304", "initializer": {"preview": "JSHandle@node"}, "type": "ElementHandle"}}
```

More often than not, this is followed by a `previewUpdated` message.

We noticed that `ElementHandle` catches errors here: https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/dom.ts#L118, so we changed the code as follows:

```javascript
  constructor(context, objectId) {
    super(context, 'node', undefined, objectId);
    this._page = void 0;
    this._page = context.frame._page;

    this._initializePreview().catch(e => {
      console.error("error!", objectId, e)
      // throw e
    });
  }
```

and see the following message:

```
error! -1346053277188783200.4.5 Error: Execution context was destroyed, most likely because of a navigation.
```

We traced this to here: https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/chromium/crExecutionContext.ts#L107-L118, which we then changed to the following:

```javascript
if (!js.isJavaScriptErrorInEvaluate(error) && !(0, _protocolError.isSessionClosedError)(error)) {
    console.error("error!", error)

    throw new Error('Execution context was destroyed, most likely because of a navigation.');
  }
```

This shows us the original error:

```
error! ProtocolError: Protocol error (Runtime.callFunctionOn): Could not find object with given id
```

This seems to be generated in Chromium in this file: https://chromium.googlesource.com/chromium/blink/+/72fef91ac1ef679207f51def8133b336a6f6588f/Source/core/inspector/InjectedScriptSource.js?autodive=0%2F%2F%2F

We have tried calling `waitUntil: "load"` and `waitUntil: "domcontentloaded"` in our navigation, but the flakiness remains. We're still not sure if this is a bug in our usage of playwright, or if it's a bug in playwright or chromium. At the very least, though, it seems like this error should not be swallowed by the `ElementHandle`—it should either throw or bubble up the error message to client.

Is there a reason why these errors are caught here and not propagated? We recognize that there might be a reason for this that we don't understand.

/cc @eahanson @coreyti

**Comment by aslushnikov** [comment]
> Is there a reason why these errors are caught here and not propagated?

@sax `ElementHandle` objects are prone to all kinds of races; this particular issue in your script seems to be a symptom of the execution context being destroyed, probably due to a subsequent main frame navigation. These kind of issues are what makes Element Handles tricky to work with, and that's why we have **locators** now.

So first and foremost: almost all automations these days should switch to [locators](https://playwright.dev/docs/api/class-locator):
- documentation: https://playwright.dev/docs/api/class-locator
- video introduction: https://youtu.be/LczBDR0gOhk?t=323
- slides introduction: https://docs.google.com/presentation/d/1B6PZZ-6fC96uBpA-4FMhiIxksKqmw5HotE76Tb0VOgI/edit?usp=sharing

So I'd recommend switching to locators!

**Comment by dgozman** [comment]
Closing since there is no action item for Playwright project here.
