### ISSUE TITLE
[BUG] POST request reporting 403 instead of 200

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#10393]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 12.22

**Describe the bug**
Considering PW request is similar `cy.request`, I am seeing a discrepancy when a POST request is made. PW is producing a status code of 403 while cypress is producing a status code of 200. The request has same headers and same body. Here are the sample repos I created to reproduce the issue:
https://github.com/Nav-2d/PW-request
https://github.com/Nav-2d/cypress-request
My assumption is because cypress bypasses CORS and that is the reason it works. Is PW API request different in this aspect? Happy to share more information and thank you!

**Comment by yury-s** [comment]
> I created to reproduce the issue: https://github.com/Nav-2d/PW-request

We need a repro with actual credentials and url, it works perfectly fine in small tests.

> My assumption is because cypress bypasses CORS and that is the reason it works.

The request is made from nodejs so it's not a subject to the browser CORS policies.

**Comment by yury-s** [comment]
@Nav-2d I tried with the credential that you shared with Pavel and both tests pass meaning that response status is 403 in both cases. What is not working?

**Comment by Nav-2d** [comment]
@yury-s I am getting `403` in PW repo and `200` in cypress repo. 😕

**Comment by yury-s** [comment]
Looks like cypress persists cookies between the request calls, try removing `~/.config/Cypress/` (or wherever the config is stored on your platform) and run the test again.

**Comment by yury-s** [comment]
Yep, confirmed that on the first run in fresh installation of cypress there is no cookie and the server returns 403. Once the cookie is received once it gets persisted between test runs and app launches which is probably a bug on their side.

**Comment by Nav-2d** [comment]
Thank you @yury-s for confirming and looking into the issue.
