### ISSUE TITLE
[Feature] expose existing CDP session used

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#10408]
Could you expose the existing CDP session used to control Chomium-type browsers? I know there is browserContext.newCDPSession(page) but that creates a new session. Thanks.

**Comment by mxschmitt** [comment]
Could you tell us why you need it and what your use-case for that is?

**Comment by JoelEinbinder** [comment]
We are not going to expose the existing session. Everything you could want to do is supported by creating a new session, which is does not introduce any overhead. Exposing our internal session would only lead to instability.
