### ISSUE TITLE
[BUG] Retry doesn't work with global timeout 

### ISSUE THREAD

**Issue by sb-michal-murray** [microsoft/playwright#10405]
**Context:**
- Playwright Version: 1.17
- Operating System: Linux
- Node.js version: 14.16
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test('Some test', async ({ page }) => {
  await page.goto(someUrl)
})

const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'Tests',
      use: {
        channel: 'chrome',
        viewport: { width: 1920, height: 1080 },
        ignoreHTTPSErrors: true,
        launchOptions: {
          slowMo: 50,
        },
        acceptDownloads: true,
        video: 'retain-on-failure',
      },
      timeout: 120_000
    },
  retries: 2,
  workers: 8,
```

**Describe the bug**
This test doesn't retry when `goto()` method failed. The video shows it's waiting for 120 s and then throws timeout which is totally unexpected here. It should fail after 30 s wait for page to fire `load` state and retry the test.

**Comment by dgozman** [comment]
[Here](https://playwright.dev/docs/next/test-timeouts) is an overview of various timeouts in Playwright Test.
