### ISSUE TITLE
page.bringToFront()

### ISSUE THREAD

**Issue by wolf002** [microsoft/playwright#1040]
Does this library have such a function as page.bringToFront()

Instead i use

```
await page.waitForSelector('title');
await page.click('body');
```

I know that this is not quite right, but how else to make a new tab become active after opening it, I don’t understand

**Comment by pavelfeldman** [comment]
Could you elaborate on your scenario? All the pages we create for testing think they are active and focused.

**Comment by wolf002** [comment]
There is a page with a list of links
If you follow the links through a href
then the page is really active and in focus
but if I get her link through
`let href = await page1.evaluate (() => document.querySelector ('a'). getAttribute ('href'));`
and then I open this link through
```
let page2 = await context.newPage ();
await page2 .goto (href);
```
then the second page no longer opens as active and I need to manually focus it somehow

**Comment by pavelfeldman** [comment]
Could you follow the template and specify the Playwright version, your OS and the browser type you are using?

**Comment by pavelfeldman** [comment]
Headless versions of the browsers think that all their pages are always active and focused. Are you working with the headful browsers?

**Comment by aslushnikov** [comment]
Closing since the discussion staled
