### ISSUE TITLE
[Feature] Add rich failure information when code in before hook failed

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#10402]
Currently the failure message for any failure in before hook e.g. beforeAll is very simple, usually is just `Timeout of xxx exceeded in beforeAll hook.` We would like to see rich failure information as faiure in `test` block.

Example:
```typescript
import { test, Page, expect } from '@playwright/test';

test.describe('Test failure in beforeAll hook', async () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await page.goto('https://www.google.com');
    // following line will fail
    await page.waitForSelector('element-does-not-exist');
  });

  test('test case #1', async () => {
    await page.type('input[title="Search"]', 'Playwright is great');
    await page.keyboard.press('Enter');
  });
});
```

Console log:
![image](https://user-images.githubusercontent.com/4818798/142348465-010904a1-10a3-4261-84e0-c842748dbe64.png)

**Comment by mxschmitt** [comment]
I can repro:

```js
import { test, Page, expect } from '@playwright/test';

test.describe('Test failure in beforeAll hook', async () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
    await page.waitForSelector('element-does-not-exist');
  });

  test('test case #1', async () => {
  });
});
```

when the `waitForSelector` happens inside the actual test it gets shown in a more meaningful way.

**Comment by dgozman** [comment]
@TimeInvestor As a workaround, you can put `page.goto` and `page.waitForSelector` in a separate first test and call it something like "setup page". This way you'll get all test goodies.

**Comment by TimeInvestor** [comment]
@dgozman Thanks for the tip on the workaround.
