### ISSUE TITLE
[Question] Force playwright to use downloaded browser versions

### ISSUE THREAD

**Issue by grybykm** [microsoft/playwright#10410]
Hello, I'm running tests in the latest `mcr.microsoft.com/playwright:focal` with the latest playwright version `"@playwright/test": "^1.16.3"`.

The issue is every time playwright or docker image updates I have to run `npx playwright install` to install another version of browsers.

Example (docker build log):

```
Step 7/7 : RUN npx playwright install
 ---> Running in c9e7279b08d5

Removing unused browser at /ms-playwright/chromium-939194
Removing unused browser at /ms-playwright/firefox-1304
Removing unused browser at /ms-playwright/webkit-1578

Playwright build of chromium v930007 downloaded to /ms-playwright/chromium-930007
Playwright build of firefox v1297 downloaded to /ms-playwright/firefox-1297
Playwright build of webkit v1564 downloaded to /ms-playwright/webkit-1564
```

Is it possible force playwright use browsers shipped in the image instead of downloading them again?
If not, can you please suggest an alternative?

Thank you!

**Comment by mxschmitt** [comment]
It's recommended to use the specific Docker image tag with the Playwright version which you are using, then the browser versions of the image will match with the browsers your Playwright NPM library will expect see [here](https://playwright.dev/docs/docker).

For example: `docker pull mcr.microsoft.com/playwright:v1.16.3-focal`

**Comment by grybykm** [comment]
Alright, I'll try that, thank you!

**Comment by erfanimani** [comment]
I just want to pop by and say that this was very useful.

Locking Playwright's versions in package.json and keeping it in sync with the image tag also fixed this issue for me.

There are three ways to prevent a download on every build:

* In your build, always call `npx install playwright`, but also cache the download/install location for the browsers (https://playwright.dev/docs/browsers/#managing-browser-binaries on Linux it would be ~/.cache)
* Create your own image and call `npx install playwright` as part of your Dockerfile
* Ensure NPM file and image are in sync by using the right combination of image and NPM versions (as suggested in this issue)

Probably the last method is preferred, correct me if I'm wrong.
