### ISSUE TITLE
[Feature] Add Firefox and Webkit dependencies to troubleshooting guide

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#1041]
When the browser fails to launch you get redirected here:

https://github.com/Microsoft/playwright/blob/master/docs/troubleshooting.md

After some looking around I found https://github.com/microsoft/playwright/blob/master/.github/workflows/tests.yml that contains some dependencies on how to run firefox and webkit. I only managed to get firefox running on Azure Pipelines though, webkit still failed when I installed these packages:

https://github.com/microsoft/playwright/blob/e65897844f3925c5fb5577d15d455d8ae550fa67/.github/workflows/tests.yml#L84-L88

You can see the steps I went through in this PR: https://github.com/xtermjs/xterm.js/pull/2722

**Comment by arjun27** [comment]
Thanks for the suggestion @tyriar, we should definitely add this. For now you could use [this list](https://github.com/arjun27/playwright-github-actions/blob/master/Dockerfile#L8). I've verified it to work for the 3 browsers, for Ubuntu 18.04 and Playwright 0.11.1.

**Comment by Tyriar** [comment]
Hm, that didn't seem to work 😕 

https://github.com/xtermjs/xterm.js/pull/2725
https://dev.azure.com/xtermjs/xterm.js/_build/results?buildId=3063&view=logs&j=a5202df1-cd2a-5288-9447-1453cf8875c8&t=5fc218d6-0ed8-555d-8192-8ac67e3288b5

**Comment by arjun27** [comment]
Taking a look at it! Any chance we could add `{ dumpio: true }` to the browser launch method? That will report the missing dependencies.

**Comment by Tyriar** [comment]
@arjun27 thanks, figured it out with `dumpio`. That should definitely be mentioned in troubleshooting too. Created https://github.com/microsoft/playwright/pull/1051 which I recommend doing across the public API to make the lib nicer to user.
