### ISSUE TITLE
[Feature] why it is not include disconnect method like puppeteer 

### ISSUE THREAD

**Issue by zhbn** [microsoft/playwright#10415]
in my case ,i do not want to close browser when the code ended,but even i do not use browser.close method ,the browser is closed

**Comment by mxschmitt** [comment]
Could you elaborate more on your use-case?

You can use e.g. [connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp) to connect and disconnect to existing Chromium based browser instances but I probably don't understand your end goal fully.

**Comment by JoelEinbinder** [comment]
You can use a [BrowserServer](https://playwright.dev/docs/api/class-browserserver) or launch the browser yourself and use [connectOverCDP](https://playwright.dev/docs/api/class-browsertype/#browser-type-connect-over-cdp) as Max suggests. We do not support directly disconnecting from the browsers we launch, as doing so is often not a good pattern.
