### ISSUE TITLE
[Question]: AttributeError: 'NoneType' object has no attribute 'inner_html'

### ISSUE THREAD

**Issue by cloudgedti** [microsoft/playwright#10413]
### Your question

Hi, I'm having this error in certain piece of my code, I was wondering if it's a bug or I'm doing something wrong. Here's the code:

```
table = await page.query_selector("#grvPedidos")
time.sleep(3)
print(await table.inner_html())
```

Result:

```
AttributeError: 'NoneType' object has no attribute 'inner_html'
```

But I'm absolutely sure that this table exists and has content, if I go through Selenium it recognizes normal, I want to know what's going wrong.

**Comment by mxschmitt** [comment]
> table = await page.query_selector("#grvPedidos")

it does not wait that the element will appear on the page. We recommend to use Locators instead, they wait automatically and are basically re-usable Element handles, see here: https://playwright.dev/python/docs/api/class-locator/

> time.sleep(3)

time.sleep is not recommended and won't work, see here: https://playwright.dev/python/docs/intro#known-issues
