### ISSUE TITLE
[BUG]  Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found

### ISSUE THREAD

**Issue by Cyrus-d** [microsoft/playwright#1042]
**Context:**
- Playwright Version: [0.11.1]
- Operating System: [Windows]
- Browser: [browserless/chrome inside docker with websockert]

![Untitled](https://user-images.githubusercontent.com/4041334/74608305-28351b00-50f5-11ea-973e-00796d9cea9d.png)

**Code Snippet**

```javascript
        await page.waitFor('button');
        const button = await page.$('button');
        await button?.click();
```

**Describe the bug**

After updating from 0.10.0 to 0.11.1 receiving following error:

`Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found`

everything else works fine, but whenever I am using 'click' method the above error thrown.

Reverted to package 0.10.0 all works fine.

**Comment by pavelfeldman** [comment]
Do you manually point to your chromium installation or do you use the one Playwright installed?

**Comment by Cyrus-d** [comment]
Yes, it could be the browser version because I am manually point it to chromium, sorry for wasting your time, should read the document more carefully.
