### ISSUE TITLE
[Question]Can not generate test code when start with android device emulator

### ISSUE THREAD

**Issue by gengyang1986** [microsoft/playwright#10430]
Context:
Playwright Version: [what Playwright version do you use?]1.16.3
Operating System: [e.g. Windows, Linux or Mac] Mac
Node.js version: [e.g. 12.22, 14.6] v16.13.0
Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
npx version : 8.1.0

_npx playwright codegen --device="Nexus 10" https://www.google.com
page.goto: net::ERR_TOO_MANY_REDIRECTS at https://www.google.com/
=========================== logs ===========================
navigating to "https://www.google.com/", waiting until "load"
============================================================
    at openPage (/Users/remark/vue-workspace/webtestservice/node_modules/playwright-core/lib/cli/cli.js:397:16) {
  name: 'Error'
}_

But if  I remove the --device, it works.

**Comment by mxschmitt** [comment]
This is fixed with version 1.17-rc0 which you can install with `npm install @playwright/test@rc` or `npm install playwright@rc` (depending how you consume Playwright).

Folding into #10376
