### ISSUE TITLE
[BUG] page.goto() stalls for waitUntil: "load" on page with redirect

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#10435]
## System:
 - OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa) (WSL2 on Windows)
 - Memory: 21.65 GB / 24.84 GB
 - Container: Yes
## Binaries:
 - Browser: Chromium
 - Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
 - npm: 8.0.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.18.0-alpha-nov-18-2021 => 1.18.0-alpha-nov-18-2021

**Code Snippet**

```ts
import { chromium } from "playwright-core";

main();

async function main() {
  const browser = await chromium.launch();

  const context = await browser.newContext();

  const page = await context.newPage();

  const documentURL = `https://www.cookibot.com/en/`;

  const pageResponse = (await page.goto(documentURL, { waitUntil: "load" }))!;

  console.log("stuck here??"); // 🤔

  await page.close()
  await context.close();
  await browser.close();
}
```

**Describe the bug**

Page gets stuck loading until timeout.

(Maybe we could have a boolean option `followRedirects`, so the Promise could get rejected if the page doesn't load?)

**Comment by JoelEinbinder** [comment]
Is this the correct URL? Because it times out when I try to access it manually. Can you please provide a [trace](https://playwright.dev/docs/api/class-tracing). Thanks!

**Comment by mindplay-dk** [comment]
Yeah, it times out here as well now - something must have changed, I can't recreate the problem anymore.

Let's close this - I will reopen if the problem resurfaces.
