### ISSUE TITLE
[Question] Do you have any plans to provide Python bindings?

### ISSUE THREAD

**Issue by ivanistheone** [microsoft/playwright#1043]
I've been using https://github.com/miyakogi/pyppeteer to automate some aspects of Chrome browser, but I'm very interested in playwright since it can handle all browsers.

The asyncio APIs are very similar to js, so maybe it could be a thin wrapper that is auto-generated from the js code?

> Do you think others might benefit from this as well?

The python ecosystem will surely welcome a new browser automation. I can think of scraping, web archival, and behaviour testing tasks.

**Comment by JoelEinbinder** [comment]
We don't have any concrete plans at the moment. If someone from the community wants to make pyplaywright that would be really cool!

**Comment by joeyfromnijmegen** [comment]
https://github.com/microsoft/playwright-python
