### ISSUE TITLE
[Feature] Support traces in `beforeAll` and `afterAll` test hooks

### ISSUE THREAD

**Issue by jriddy** [microsoft/playwright#10440]
## Description

Currently, traces don't seem to cover what happens in `beforeAll` or `afterAll` hooks. This is frustrating if you put actions that may fail in these hooks, as you're left wondering what went wrong without the benefit of tracing facilities to help you out. 

I suppose this makes sense as these hooks don't even have a browser context available to them by default, and it's really possible that I'm abusing them to create state in the application that I need multiple tests to use. But since there's also no other option for file-level or `test.describe`-level fixtures, this seems to be the only way to do that.

## Workaround

I've cobbled together a clunky function to do run traces during these functions and save traces on errors. It seems to make the test runner take much more time between tests though, so it's certainly possible I'm doing something suboptimal here.

```typescript
export type WithTracingOpts = {
  browser?: Browser;
  context?: BrowserContext;
  pathPrefix?: string;
}

/**
 * Permits trace saving on errors in hooks.
 *
 * Within a test function, tracing respects the global issues.  But we don't trace if we
 * never get to a test because a pre-test hook fails.  This function helps fill that gap.
 *
 * @param opts options for the tracing. If a context is passed it will be used, else we need
 *    a browser to create a new browser context
 * @param fn function to be called with the context. If there is an error, a trace will be recorded.
 */
async function withTracingOnFailure(opts: WithTracingOpts, fn: (ctx: BrowserContext) => Promise<void>) {
  const ctx = opts.context || await opts.browser.newContext();
  const tracing = ctx.tracing;
  // TODO: it would be better if we respected user options here rather than hard-coding
  await tracing.start({ screenshots: true, snapshots: true });
  await tracing.startChunk();
  try {
    await fn(ctx);
    // Don't save if we get the service running successfully
    await tracing.stopChunk();
  } catch (e) {
    // Save a trace of the creation failure if it doesn't work
    const prefix = opts.pathPrefix || '';
    const path = prefix + (prefix ? '/' : '') + 'trace.zip';
    await tracing.stopChunk({ path });
    throw(e);
  }
}
```

**Comment by JoelEinbinder** [comment]
It's hard to know what to do here, because you have a solution and you are kind of working against the test runner. How would you want the api to look?

@dgozman do we turn on tracing in browsers launched from `@playwright/test` if their config has tracing on?

**Comment by pavelfeldman** [comment]
I think this should already work since beforeAll is just a test inside and if you enabled tracing, beforeAll and all the browsers / contexts / pages created there will be traced. Waiting for confirmation from @dgozman.

**Comment by dgozman** [comment]
This is technically possible today, but we did not work out all the details yet - where to save the trace, how to report it to the user, etc.

**Comment by jriddy** [comment]
If it helps to understand why I need this, I can elaborate on our use case.

We're testing a web frontend for cloud-backed services. So the web UI is actually telling our backend to go create VMs and install software on them, get things running etc. Because this can take quite a bit of time, we need to be able to share these services between tests, even at the expense of some test isolation.

I tried at first to use worker fixtures to achieve this but ran into a lot of trouble and felt like I was fighting against the system trying to do UI stuff inside worker fixture setups. Then I stumbled on using `beforeAll` and `afterAll` hooks to do the same thing, and just built a small abstraction around that.

That's why this is needed, because we need to be able to investigate failures during the creation of these services.
----
On another note, my workaround seems to be resulting in large, empty traces being left by the tests, e.g.:
```
-rw-r--r--. 1 jreed jreed 2.2M Nov 19 11:48 trace-1.zip
-rw-r--r--. 1 jreed jreed 318M Nov 19 11:48 trace.zip
```
where `trace.zip` contains nothing despite being 318 MB. If I try to stop tracing on the context I create in my workaround code (which I call from `beforeAll`, I get an error that `startChunk()` can't be called before `start()` once the test starts, so it seems like this context (which I created in `beforeAll`) is being re-used in the test itself.

**Comment by refactoreric** [comment]
I would also appreciate trace files for the beforeAll. When/if we migrate our Protractor/Mocha tests to @playwright/test I'm afraid initially we will choose the [reuse-the-signed-in-page-in-multiple-tests](https://playwright.dev/docs/test-auth#reuse-the-signed-in-page-in-multiple-tests) route. Just because making all existing individual tests isolated is a massive undertaking.

Trace files are an important differentiator from (for example) webdriver.io. It makes troubleshooting so much more efficient. So it would be a big plus for Playwright if we can have complete trace files (including the beforeAll/login) from the start/initial/rough conversion.

P.S. At least in 1.17-rc1, some tracing is already taking place in beforeAll, but it leads to inconsistent trace files of the first test. When following the reuse-the-signed-in-page-in-multiple-tests recipe, the filmstrip of the first test contains only the screenshots of the beforeAll/login, but the actions only show the actions by the test itself. It looks very strange/inconsistent.

![playwright-rc-1-17-beforeall-trace-filmstrip](https://user-images.githubusercontent.com/94195748/143688662-cc5a9bb5-b37b-421f-a68d-8ce96bc3a9d7.PNG)

**Comment by refactoreric** [comment]
Wow, made my day :) 🎉

**Comment by sbartsa** [comment]
There's a case where we run tests on Buildkite CI and when the the tests fail on the beforeAll hook the traces are not being genrated. They are generated for the rest of the tests but not for the ones failing at this hook. (ps. the 'retain-on-failure' is the trace option)
Any ideas @dgozman ??
