### ISSUE TITLE
Where can I find a standalone trace-viewer (web app)

### ISSUE THREAD

**Issue by slang25** [microsoft/playwright#10455]
@pavelfeldman @JoelEinbinder I'm super impressed with playwright and the trace viewer.

I'm looking to bundle up the viewer with my build artifacts to make viewing the traces seamless (CORS & Auth on my artifacts make the public app tricky). I cannot seem to find an up-to-date version.

The [trace folder on this repo](https://github.com/microsoft/playwright.dev/tree/f8a938e805108e7c66a2bb00596b6431cc6cf7e8/trace) seems to be an outdated version.

Thanks! Stu

**Comment by slang25** [comment]
The more I think this over, the more I think my request here is for you to add `Access-Control-Allow-Origin: *` to the `https://trace.playwright.dev` site and the cli self-hosted version.

Otherwise the `?trace=https://some-otherhost/my-trace.zip` functionality will never be useful.

**Comment by slang25** [comment]
I've taken a look at this again, it looks like this header is being set in the cli hosted version and on `https://trace.platwright.dev/', however I'm getting the request blocked when the service worker is making the request.

I've done a bit of reading about services workers with CORS, however I still don't really understand why this isn't working.

![image](https://user-images.githubusercontent.com/1341446/142838230-1c2ac83f-facf-414f-8608-74e9658cbbfc.png)

The context endpoint returns a 500 with:
> error: "Could not load trace from https://myhost/mytrace.zip. Make sure a valid Playwright Trace is accessible over this url."

The request made by the service worker looks like this in devtools:
![image](https://user-images.githubusercontent.com/1341446/142837990-18897f29-0ce7-4760-8a2c-813f088ac273.png)

**Comment by pavelfeldman** [comment]
CORS works the other way around, Access-Control-Allow-Origin is a response header that specifies origins that can access your zip files. So your server should return

`Access-Control-Allow-Origin: https://trace.playwright.dev`

That way when trace viewer reaches for the trace files, it can get them.

**Comment by pavelfeldman** [comment]
Here is another workaround for you: every time we make an html report, we bundle the trace viewer with it. So:
- Make sure your test produces traces
- Run it with --reporter=html

in the playwright-report, you'll get a trace folder with the deployed version of the trace viewer. We can consider exposing `npx playwright deploy-trace-viewer` that does it directly.

**Comment by slang25** [comment]
Thanks!

Ah 🤦  my bad, I thought it was the other way around. At the moment I have `Access-Control-Allow-Origin: *` from my server, however I'll try calling out the playwright doman explicitly 😄 

I'm using playwright-dotnet, so I presume that rules out the reporter option for now. I'd love to have a way to have a static file dumped into our CI artifacts, I was using the version linked to in the OP but it wasn't working as it was outdated.

**Comment by slang25** [comment]
For anyone finding this issue, I finally figured out what I was doing wrong. If you are serving your own trace files and want to view them via https://trace.playwright.dev, you will need:
- To serve your files with a `Access-Control-Allow-Origin: https://trace.playwright.dev` header (or `*`)
- To allow HEAD requests, and to have the above CORS header on this response
- A Content-Length header on the HEAD reponse.

The last 2 points took me a while to figure out.

**Comment by slavaGanzin** [comment]
@pavelfeldman Hi there, so is there any way to host trace viewer on my own infrastructure?

Can I just serve trace folder with nginx, for example?

**Comment by monkekode** [comment]
@pavelfeldman Hi. I have a similar issue that a self-hosted trace viewer would solve - I have a trace file accessible over HTTP - it's in on a VPN, so there is encryption still. I can only load trace.playwright.dev over https, but then I have a mixed-content error since I can't download the http trace file from a https page.

**Comment by alisterscott** [comment]
Wow this works with Github Pages files no config changes needed :)

https://trace.playwright.dev/?trace=https://alisterscott.github.io/media/trace.zip

**Comment by plessbd** [comment]
Dont mean to resurrect an old thread, but I needed this for an internal project as well.

I was able to get something working by:

1. checkout `github.com:microsoft/playwright`
1. `npm i`
1. `npm run build`
2. serve up `packages/playwright-core/lib/webpack/traceViewer`
    * `docker run -p 127.0.0.1:8080:80 -v packages/playwright-core/lib/webpack/traceViewer:/usr/share/nginx/html nginx` 

**Note** You will need to serve up as https if you are not using looalhost due to the use of webworkers

**Comment by d-colwell** [comment]
> Dont mean to resurrect an old thread, but I needed this for an internal project as well.
> 
> I was able to get something working by:
> 
> 1. checkout `github.com:microsoft/playwright`
> 2. `npm i`
> 3. `npm run build`
> 4. serve up `packages/playwright-core/lib/webpack/traceViewer`
>    
>    * `docker run -p 127.0.0.1:8080:80 -v packages/playwright-core/lib/webpack/traceViewer:/usr/share/nginx/html nginx`
> 
> **Note** You will need to serve up as https if you are not using looalhost due to the use of webworkers

Minor update, in the latest version, you should run
* `docker run -p 127.0.0.1:8080:80 -v packages/playwright-core/lib/vite/traceViewer:/usr/share/nginx/html nginx`

since the build for this component is no longer with Webpack. The webpack dir is still there tho which creates some confusion
