### ISSUE TITLE
[BUG] initiators missing from Chrome Debug Protocol messages

### ISSUE THREAD

**Issue by mindplay-dk** [microsoft/playwright#10464]
## System:
 - Browser: Chromium
 - OS: Linux 5.10 Ubuntu 20.04.3 LTS (Focal Fossa) (WSL2 on Windows)
 - Memory: 21.72 GB / 24.84 GB
 - Container: Yes
## Binaries:
 - Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
 - npm: 8.0.0 - ~/.nvm/versions/node/v14.17.6/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.18.0-alpha-nov-18-2021 => 1.18.0-alpha-nov-18-2021 

## Code Snippet

```ts
import express from "express";
import type { Server } from "http";
import { chromium } from "playwright-core";

const options = {
  port: 5051,
};

main();

async function main() {
  const browser = await chromium.launch();

  const context = await browser.newContext();

  const server = await createTestServer();

  // return; // 👈 uncomment this to run the test-server stand-alone

  const page = await context.newPage();

  const session = await context.newCDPSession(page);

  await session.send("Network.enable");

  session.on("Network.requestWillBeSent", payload => {
    console.log(payload);
  });

  await page.goto(`http://localhost:${options.port}/test`, { waitUntil: "load" });

  await new Promise(resolve => setTimeout(resolve, 2000)); // wait for image to load
  
  await page.close()
  await context.close();
  await browser.close();

  await new Promise(resolve => server.close(resolve));
}

const PAGE = `<!DOCTYPE html>
<head>
  <title>Image cookies test page</title>
</head>
<body>
  <h3>Setting a <code>hello_script</code> cookie using a script to set the <code>src</code> property.</h3>
  <img data-src="https://via.placeholder.com/200x100">

  <script>
    window.addEventListener("load", () => {
      document.querySelectorAll("img[data-src]").forEach(img => {
        img.src = img.getAttribute("data-src");
      });
    });
  </script>
</body>
`;

async function createTestServer(): Promise<Server> {
  return new Promise(resolve => {
    const app = express();

    // Serve a test page:

    app.get("/test", (req, res) => {
      res.setHeader("Content-Type", "text/html");

      res.send(PAGE);
    });

    // Launch the server:

    const server = app.listen(options.port, () => resolve(server));
  });
}
```

Note that the script requires an `npm install express` for the test-server.

## Bug Report

It appears Playwright is doing something that alters the normal behavior/results of CDP `Network` messages.

I encountered this while monitoring pages that lazy-load images - having `<img>` tags with no `src`-attribute is rather common in scripts that lazy-load images, and the test-script provided here is a minimal script demonstrating the problem, which occurs when an `<img>` tag is on the page at load-time, while the `src`-property gets initialized by a script at run-time.

If you run the test-script above, the payload of the second `Network.requestWillBeSent` message (from loading the image) is missing the initiator information:

![image](https://user-images.githubusercontent.com/103348/142840933-ebe2aa9b-0a56-4ef0-bb19-ae7aa1418fb5.png)

If you uncomment the `return` statement near the beginning of the script, you can open the page `http://localhost:5051/test` in a browser, where you can use Protocol Monitor to inspect the same events - here, the result is as expected, with detailed information about the initiator, including a stack-trace:

![image](https://user-images.githubusercontent.com/103348/142843323-2d046ca9-3041-41f9-9e1e-cac3a6060079.png)

As noted, I'm on Windows WSL2 myself - since I can't open Playwright's Chromium fork in headed mode, I created this screenshot using Chrome proper, but I also had a friend open your fork in headed mode, and this works correctly.

So the issue is not caused by some change to your fork, and it's not caused by running headless either.

Perhaps Playwright is meddling with the run-time environment somehow?

Or perhaps the loading sequence or timing is somehow different when Playwright issues commands from `page.goto`?

It appears `newCDPSession` does not in fact create a *new* session, but might reuse an existing session? If the CDP session I'm getting is not in fact a dedicated session, but a shared reference to Playwright's internal CDP session, perhaps the issue is that Playwright's facilities are somehow issuing commands that cause the CDP session to behave differently?

These are all the clues I could think of... I hope this is helpful. 🙂

**Comment by yury-s** [comment]
> Perhaps Playwright is meddling with the run-time environment somehow?
> 

Playwright starts browser with certain command line flags, you can see those if running with `DEBUG=pw:browser`. Other than that it should be the same as if you started it manually. Also the protocol exposed via newCDPSession is exactly what browser sends to playwright, you can see the raw messages by starting playwright with `DEBUG=pw:protocol`.

> Or perhaps the loading sequence or timing is somehow different when Playwright issues commands from `page.goto`?
> 

I'm not sure what you compare it to here. Loading sequence should be the same as if a user typed the url in the url bar.

> It appears `newCDPSession` does not in fact create a _new_ session, but might reuse an existing session? 

It does [create a new session](https://github.com/microsoft/playwright/blob/daae8d4863109e0e0e84b977a0280de2ad9c3f48/packages/playwright-core/src/server/chromium/crBrowser.ts#L526) connected to the same target, but the session is different from the one that playwright uses internally.

> If the CDP session I'm getting is not in fact a dedicated session, but a shared reference to Playwright's internal CDP session, perhaps the issue is that Playwright's facilities are somehow issuing commands that cause the CDP session to behave differently?
> 
This is unlikely. It might be just a bug (perhaps race) in the browser instrumentation. CDP is not a part of playwright, we just expose an access to the session, so it may be better to open an issue in Chromium if you feel like there is a bug in the protocol.

I'm closing this issue. Feel free to file a new one if the problem can be reproduced via Playwright APIs rather than CDP.

**Comment by mindplay-dk** [comment]
> It might be just a bug (perhaps race) in the browser instrumentation. CDP is not a part of playwright, we just expose an access to the session, so it may be better to open an issue in Chromium if you feel like there is a bug in the protocol.

But I've already confirmed that's not the case?

As per the description, the issue cannot be recreated in-browser - not with your fork, or with Chrome proper.

> Feel free to file a new one if the problem can be reproduced via Playwright APIs rather than CDP.

Sorry, but I don't understand what you mean?

I already posted a code sample showing that the issue happens only with Playwright's CDP integration - I can't recreate the problem in any other way.

It works within Chromium, using their own Protocol Monitor, which also emits raw messages.

If this is not an issue with Playwright's use of the CDP protocol, what is your theory?

**Comment by mindplay-dk** [comment]
I hope I don't come off as facetious - I'm genuinely trying to understand how I could possible posit this to the Chromium team as an issues with CDP, when apparently the only way to recreate it is via Playwright?

If you're saying you think this issue could be recreated *without* Playwright, I would be really grateful for any suggestion on how to isolate and demonstrate a problem with CDP itself?

**Comment by eliassorensen** [comment]
I have investigated this, and it seems like it's a combination of different things. Could be an issue in Chromium, but ultimately, the problem seem to occur with the series of CDP messages sent by Playwright.

I've managed to isolate the problem to using [chrome-remote-interface](https://github.com/cyrus-and/chrome-remote-interface
) and sending some of the CDP messages that Playwright (monitored using `DEBUG=pw:protocol`):
```
const CDP = require('chrome-remote-interface');
async function example() {
    let client;
    try {
        // connect to endpoint
        client = await CDP({
            port: 9222
        });

        const {Network, Page, Target, Browser, Log, Runtime, Emulation} = client;
        
        await Target.setAutoAttach({"autoAttach":true,"waitForDebuggerOnStart":true,"flatten":true});

        // setup handlers
        Network.requestWillBeSent((params) => {
            console.log(params);
        });

        // enable events then start!
        await Page.enable();
        await Page.getFrameTree();
        await Log.enable();
        await Page.setLifecycleEventsEnabled({enabled:true});
        await Runtime.enable({});
        await Network.enable();
        await Emulation.setFocusEmulationEnabled({enabled:true});
        
        // 👇 REMOVING THIS LINE MAKES IT WORK
        await Emulation.setDeviceMetricsOverride({"mobile":false,"width":1280,"height":720,"screenWidth":1280,"screenHeight":720,"deviceScaleFactor":1,"screenOrientation":{"angle":90,"type":"landscapePrimary"}}); // <-- THIS
        
        await Browser.setWindowBounds({"windowId":1,"bounds":{"width":1288,"height":805}});
        await Emulation.setEmulatedMedia({"media":"","features":[{"name":"prefers-color-scheme","value":"light"},{"name":"prefers-reduced-motion","value":"no-preference"},{"name":"forced-colors","value":"none"}]});
        await Runtime.runIfWaitingForDebugger();
        await Page.navigate({url: 'http://localhost:5051/test'});
        await Page.loadEventFired();
    } catch (err) {
        console.error(err);
    } finally {
        if (client) {
            await client.close();
        }
    }
}

example();
```

I also tried running the example code from @mindplay-dk while having removed `setDeviceMetricsOverride` (just returning immediately in `crPage` -> `_updateViewport` ), but that doesn't seem to fix it. It still shows initiator as `other`.

However, when running with devTools opened and waiting just before creating a new CDP session, it get's the correct result:

```
....
async function main() {
  const browser = await chromium.launch({
      headless: false, // 👈
      devtools: true // 👈
  });
.....
  await new Promise(resolve => setTimeout(resolve, 1000)); // 👈

  const session = await context.newCDPSession(page);

  await session.send("Network.enable");
```

Now gets me the correct result:
![image](https://user-images.githubusercontent.com/1552175/143032252-297ec2d1-b0e1-4cd4-ae84-49d97a984daf.png)

@yury-s , I really would like your opinion on how to proceed from here.

**Comment by eliassorensen** [comment]
Tried out in Puppeteer as well, and it also shows "Other" as initiator with this code:
```const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();

  const client = await page.target().createCDPSession();
  await client.send('Network.enable');

  client.on('Network.requestWillBeSent', payload => {
    console.log(payload);
  });

  await page.goto('http://localhost:5051/test', {waitUntil: "load"});
  await new Promise(resolve => setTimeout(resolve, 2000));
  await browser.close();
})();
```

So unfortunately I think there is something wrong in how Chromium does CDP. 

Where do we go from here?

**Comment by eliassorensen** [comment]
Okay, I now understand why opening DevTools makes it work.

DevTools sends `Debugger.enable` to CDP. This, and having the correct async callstack depth makes it work.

Now, I wonder why opening DevTools "fixes" the CDP session we create in Playwright. As far as I understood, those two sessions should not affect each other?

Adding the following fixed the initiator to correctly show the callstack instead of "other":
```
await session.send('Debugger.enable');
await session.send("Debugger.setAsyncCallStackDepth", {maxDepth:32});
```

**Comment by mindplay-dk** [comment]
I can confirm, sending the `Debugger` messages fixes the problem.

Odd, since the `Network` messages are in a different category.

So yeah, definitely a Chrome or CDP bug.

**Comment by eliassorensen** [comment]
I have created the following ticket on Chromium's end: https://bugs.chromium.org/p/chromium/issues/detail?id=1273075
