### ISSUE TITLE
[Question]  Error: userDataDir option is not supported in `browserType.launch`.

### ISSUE THREAD

**Issue by wolf002** [microsoft/playwright#1046]
I have two computer both on windows 10 x64
On the first of them, such code does not cause any errors
```
const args = [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-infobars',
        '--window-position=0,0',
        '--ignore-certifcate-errors',
        '--ignore-certifcate-errors-spki-list',
];
const options = {
            args,
            headless: false,
            ignoreHTTPSErrors: true,
            userDataDir: './tmp'
        };      
    const browser = await chromium.launch(options);
```
And on the second I get an error

(node:6208) UnhandledPromiseRejectionWarning: Error: userDataDir option is not supported in `browserType.launch`. Use `browserType.launchPersistent` instead
    at Chromium.launch (C:\nodejs\telegram\node_modules\playwright-core\lib\server\chromium.js:44:19)

**Comment by jozsi** [comment]
See https://github.com/microsoft/playwright/pull/974:
> userDataDir option is not supported in `browserType.launch`. Use `browserType.launchPersistent` instead

**Comment by wolf002** [comment]
You can show an example of how to use .launchPersistent with option userDataDir
I try to replace 
`const browser = await chromium.launch(options);`
to this
```
const browser = await chromium.launchPersistent('./tmp', options);
const context = await browser.newContext();
```
and I get follow error
(node:11252) UnhandledPromiseRejectionWarning: TypeError: browser.newContext is not a function

**Comment by jozsi** [comment]
`launchPersistent` returns a context, so actually it is:
```js
const context = await chromium.launchPersistent('./tmp', options);
const page = await context.newPage();
```

**Comment by B20DCCN728** [comment]
Tkank all for solution
