### ISSUE TITLE
[Feature] Add clickable link in HTML report for .goto()

### ISSUE THREAD

**Issue by bamanczak** [microsoft/playwright#10463]
In my project, we frequently open long dynamic urls with multiple query parameters. Thus when debugging failed tests we need to reopen the links manually. However in HTML report the links get truncated and we need to check the source to copy the full URL.

I believe it would be cool to have a clickable link instead.
<img width="935" alt="goto" src="https://user-images.githubusercontent.com/8224947/142842785-b191527e-c9a2-4be2-88c0-e5b4379f0166.png">

I also believe that this would be widely used by other users of html reports too.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
