### ISSUE TITLE
[Feature] How to keep headed browser open on fail ?

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#10478]
### Discussed in https://github.com/microsoft/playwright/discussions/10470

<div type='discussions-op-text'>

<sup>Originally posted by **benwiley4000** November 22, 2021</sup>
One thing I like about Cypress is that you can keep the browser open after the test fails so you can explore the DOM state where the test failed. It would be nice to be able to do the same with Playwright. Is there a flag I can pass to allow this ?</div>

**Comment by anking** [comment]
Any update on this? Seem very annoying that you have to manually set breakpoint of failing code when you need to stop at certain point

**Comment by mike-czarnota** [comment]
Yeah, it would be great to have such feature 🙂

**Comment by saylestyler** [comment]
+1!!!! would love this feature

**Comment by pavelfeldman** [comment]
This is now possible if you are using the VS Code extension!

**Comment by blessanm86** [comment]
Are there any plans for adding this feature for UI mode?

**Comment by dmwyatt** [comment]
@pavelfeldman And what if we're not using the VS Code extension...or not using VS Code at all?

**Comment by parkuman** [comment]
Pretty ridiculous that you can't do this without VSCode!

**Comment by nathanaelmayne** [comment]
Something like this has worked for me while debugging:

```
try
{
    ... test code
}
catch (Exception)
{
    while (true)
        await Page.WaitForTimeoutAsync(1000);

    throw;
}
```

Was just a temporary solution for me, but something similar could be implemented at a higher level to catch any failure and keep the browser open

**Comment by SimonStorlSchulke** [comment]
> This is now possible if you are using the VS Code extension!

This is NOT a solution. Not everyone uses VS Code. Honestly it's quite frustrating when a test failed and you want to analyze why for the browser to just close.

**Comment by alxndrsn** [comment]
This fixture seems to work:

```js
import { expect, test as testBase } from '@playwright/test';

const test = testBase.extend({
  keepBrowserOpenOnFailure: [
    async ({ page }, use, testInfo) => {
      await use();

      const { error, project, status } = testInfo;

      const { headless } = project.use;
      if(headless) return;

      switch(status) {
        case 'failed':
        case 'timedOut':
          console.log(`Pausing browser after test failure (${status}): ${error.stack}`);
          await page.pause();
      }
    },
    { auto:true },
  ],
});

test('this one should pass', async ({ page }) => {
  await page.goto('http://example.com');
  await expect(page.locator('a', { hasText:'Learn more' }))
      .toBeVisible();
});

test('this one should fail', async ({ page }) => {
  await page.goto('http://example.com');
  await expect(page.locator('a', { hasText:'Learn less' }))
      .toBeVisible({ timeout:1 });
});
```
