### ISSUE TITLE
[Feature] Better error messages/print selector

### ISSUE THREAD

**Issue by benwiley4000** [microsoft/playwright#10471]
When I have a line in my test that fails when something doesn't go right with a page selector, I'd like to know exactly what selector failed. If my selector is composed using a template string, I want to know what the final string was, not the name of the variable I interpolated.

For example with this error message:

![2021-11-22_11-08](https://user-images.githubusercontent.com/13558253/142895617-c0d9a77a-ec80-44a3-a6bb-0738290ac27b.png)

One question I have is, was something wrong with the `duplicateName` variable I interpolated ? If I could have the information about which selector failed above the failed line printout, then I could determine that much more quickly.

For example if my variable was `duplicateName: 'My Duplicate'` then I could receive the error message:

```console
Expected locator "text=My Duplicate" to be visible.
```

**Comment by benwiley4000** [comment]
I'm now seeing that the call log does often print this out, but not always. Not completely clear why.

**Comment by yury-s** [comment]
I can reproduce the problem, if I have the following statement in the code:
```js
expect(await page.locator(`row="row"]`).isVisible()).toBeTruthy();
```
I'll get  `locator.isVisible: Unknown engine "row" while parsing selector row="row"]` exception, whereas if I do
```js
expect(await page.locator(`row="row"]`)).toBeVisible();
```
I get quite obscure message:
```
Error: expect(received).toBeVisible()

Call log:
  - 
```

**Comment by benwiley4000** [comment]
Exactly! This would help.

**Comment by benwiley4000** [comment]
Thank you!!

Le lun. 29 nov. 2021 20 h 13, Pavel Feldman ***@***.***> a
écrit :
