### ISSUE TITLE
[Question] How to add a custom test option?

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#10487]
How can I add a custom test option e.g. **_port_** to `TestOption` so that I can config the option via TestProject in `playwright.config.ts`.

**Comment by yury-s** [comment]
[This example](https://playwright.dev/docs/test-parameterize#parametrized-projects) explains how to add custom field `person` and have it configured per project, you can do the same for `port`.

**Comment by TimeInvestor** [comment]
Thanks for the info.
But I still cannot figure out how to use the `port` in my global-setup.ts.

![image](https://user-images.githubusercontent.com/4818798/142977033-c421c228-19b4-4afd-b4fc-16c85cd04184.png)
It shows error `Property 'port' does not exist on type 'UseOptions<PlaywrightTestOptions, PlaywrightWorkerOptions>'.`

**Comment by TimeInvestor** [comment]
@yury-s any advice?
