### ISSUE TITLE
[BUG] apiRequestContext.fetch missing proxy when used with connectOverCDP

### ISSUE THREAD

**Issue by adigaboy** [microsoft/playwright#10490]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Linux
- Node.js version: v16.13.0
- Browser: Chromium

**Code Snippet**

```javascript
const playwright = require('playwright')
const puppeteer = require('puppeteer')

const browser = await puppeteer.launch({ args: ['--proxy-server=http://IP:PORT'] })
const pupp_page = (await browser.pages())[0]
await pupp_page.goto('https://wtfismyip.com/json')
console.log(await pupp_page.content())   // result: proxy IP

const playwright_browser = await playwright.chromium.connectOverCDP(browser.wsEndpoint())
const context = playwright_browser.contexts()[0]
const playwright_page = context.pages()[0]
await playwright_page.goto('https://wtfismyip.com/json')
console.log(await playwright_page.content())   // result: proxy IP
await context.route('**', async (route, request) => {
    const response = await context.request.fetch(request)
    await route.fulfill({
        response: response,
    })
})
await playwright_page.goto('https://wtfismyip.com/json')
console.log(await playwright_page.content())   // result: server IP
```

**Describe the bug**

playwright page is not using the proxy that I have set up in the puppeteer server and we get the IP of the server.

Expected result: all cases should return the proxy IP.

**Comment by dgozman** [comment]
@adigaboy The `connectOverCDP` method does not pick up many settings in your pre-launched browser. This is intended - all the features in Playwright are guaranteed to work with the browser entirely controlled by Playwright from the start. When you `connectOverCDP` to something else, there is no way Playwright understands anything you did to the browsers by your own means, and therefore things like this will not work. Sorry for the inconvenience.
