### ISSUE TITLE
[BUG] playwright can't be launched successfully in Ubuntu 20.04

### ISSUE THREAD

**Issue by playwright2021** [microsoft/playwright#10506]
**Context:**
- Playwright Version: Version 1.16.3
- Operating System: Ubuntu 20.04
- Node.js version: v10.19.0
- Browser:  All, Chromium, Firefox, WebKit
- Extra: 

> root@ubuntu-playwright:~/playwright-e2e# cat /etc/*-release
> DISTRIB_ID=Ubuntu
> DISTRIB_RELEASE=20.04
> DISTRIB_CODENAME=focal
> DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
> NAME="Ubuntu"
> VERSION="20.04.1 LTS (Focal Fossa)"
> ID=ubuntu
> ID_LIKE=debian
> PRETTY_NAME="Ubuntu 20.04.1 LTS"
> VERSION_ID="20.04"
> HOME_URL="https://www.ubuntu.com/"
> SUPPORT_URL="https://help.ubuntu.com/"
> BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
> PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
> VERSION_CODENAME=focal
> UBUNTU_CODENAME=focal
> 

 **npx playwright test** 

Using config at /root/playwright-e2e/playwright.config.ts
{ browserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium-930007/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at globalSetup (/root/playwright-e2e/config/global-setup.ts:7:40)
    at Runner._run (/root/playwright-e2e/node_modules/@playwright/test/lib/runner.js:241:134) name: 'Error' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! playwright-e2e@1.0.0 test: `npx playwright test `
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the playwright-e2e@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-11-24T05_11_10_983Z-debug.log

 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle playwright-e2e@1.0.0~pretest: playwright-e2e@1.0.0
6 info lifecycle playwright-e2e@1.0.0~test: playwright-e2e@1.0.0
7 verbose lifecycle playwright-e2e@1.0.0~test: unsafe-perm in lifecycle true
8 verbose lifecycle playwright-e2e@1.0.0~test: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/playwright-e2e/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle playwright-e2e@1.0.0~test: CWD: /root/playwright-e2e
10 silly lifecycle playwright-e2e@1.0.0~test: Args: [ '-c', 'npx playwright test ' ]
11 silly lifecycle playwright-e2e@1.0.0~test: Returned: code: 1  signal: null
12 info lifecycle playwright-e2e@1.0.0~test: Failed to exec test script
13 verbose stack Error: playwright-e2e@1.0.0 test: `npx playwright test `
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid playwright-e2e@1.0.0
15 verbose cwd /root/playwright-e2e
16 verbose Linux 5.4.0-90-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "test"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error playwright-e2e@1.0.0 test: `npx playwright test `
22 error Exit status 1
23 error Failed at the playwright-e2e@1.0.0 test script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Code Snippet:     at globalSetup (/root/playwright-e2e/config/global-setup.ts:7:40 highligthed)**

import { chromium, firefox, FullConfig } from '@playwright/test';
import {ENV} from './envConfig';

async function globalSetup(config: FullConfig) {
  // const { baseURL, storageState } = config.projects[0].use;
  **const chromeBrowser = await chromium.launch({** 
    args: [
      '--ignore-certificate-errors'
    ]
  });

**Describe the bug**

all browsers can not be launched with, await crhomium.launch ....

**Comment by mxschmitt** [comment]
Like the error message says, you need to install the browsers by executing `npx playwright install`.

Also it might be useful to install dependencies using: `npx playwright install --with-deps`.

**Comment by playwright2021** [comment]
thanks, mxschmitt
the problem is solved by upgrading chrome to pointed version ms-playwright/**chromium-930007,** by default above setting, the **chromium-920619** is installed.

**Comment by daytonn** [comment]
```> @carsdotcom/epiphany@2.1.0 test
> web-test-runner

> Running in locally configured browsers: chromium

src/components/modal/ep-modal.test.ts:

 ❌ ep-modal > layout > stretches to an 100vh max-height on small screens
      AssertionError: expected 760 to equal 800
      + expected - actual
      
      -760
      +800
      
      at o.<anonymous> (src/components/modal/ep-modal.test.ts:191:39)

Chromium: |██████████████████████████████| 48/48 test files | 307 passed, 1 failed, 2 skipped

Finished running tests in 5.2s with 1 failed tests.
```
