### ISSUE TITLE
[Question] Proper way to wait for the passing of a callback in evaluate

### ISSUE THREAD

**Issue by rdmurphy** [microsoft/playwright#10504]
Hello! 👋 

I've been struggling with this for a bit and may have found a hack solution (that could be the right answer!) but I wanted to see if there's perhaps something I'm missing.

I have a library I'm using `playwright` to test that has [its own event listener mechanism](https://github.com/rdmurphy/scroller/blob/b0922f8a694bbbbb0c3d7dba8b9c455f6e5f46a3/src/index.js#L37-L55). However, I've been struggling to find a way to dynamically create a listener that I then trigger with `playwright`. Without some hoop jumping (or the discouraged `waitForTimeout`) I've struggled to [successfully set up a listener](https://github.com/rdmurphy/scroller/blob/b0922f8a694bbbbb0c3d7dba8b9c455f6e5f46a3/test/test.spec.js#L60-L70) before Playwright moves on to the next step that'd trigger it. Sometimes Playwright is definitely getting to the trigger step too quickly and the test times out.

I ended up using [`page.evaluate` to wrap around a Promise + requestAnimationFrame](https://github.com/rdmurphy/scroller/blob/b0922f8a694bbbbb0c3d7dba8b9c455f6e5f46a3/test/helpers.js#L43-L45) to fake a "tick." It's working so I have no real complaints! 😅 But it did make me wonder if there's more official trick I'm missing.

Thank you!

**Comment by dgozman** [comment]
@rdmurphy Your Promise + raf solution seems great! I do not know the details of this particular custom event listener mechanism, but if it requires an animation frame to activate, waiting for one tick is great. Not sure how we can help here 😄

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
