### ISSUE TITLE
[Command line flag that runs all "failures" from the last run]

### ISSUE THREAD

**Issue by ddemoss222** [microsoft/playwright#10500]
Whenever I have a failure in playwright it is very expedient to use the --debug flag, however combing through the list of successful tests is time consuming and writing out the specific test on the command line is also tedious. I could write a shell script to handle something like this, but I assume it would be useful for others as well. 

I could imagine it operating something like this:
```
3 failed
20 passed
npx playwright test --debug --failures
```
Then debug mode is initialized using only the failed tests. 

Another implementation could be a "last" flag which could accept ["failures", "flaky", "success", ?] to enable wider functionality and room to grow for new use cases. The "last" would be a reference to the last test run.

**Comment by rsouthpaw** [comment]
isn't this a use case for the `retries` config option? This will re-attempt failed tests, hence there should ideally be no need for this `--failures` argument.

**Comment by ddemoss222** [comment]
> isn't this a use case for the `retries` config option? This will re-attempt failed tests, hence there should ideally be no need for this `--failures` argument.

"Retries" does not allow for code modification since it only retries immediately after failure. A "failures" flag would be a quality of life enhancement for local development. Skipping all tests that passed would expedite read-eval-print cycles common with hands on playwright usage.

**Comment by rwoll** [comment]
We'd also find this feature useful!

From Slack:

> Is there an idiomatic way to re-run just failed tests (but only after a full test run) across multiple invocations of the test CLI? For example, we change something in our service under test, I do npx playwright test 5 / 100 tests fail. They are never going to pass unless I fixup the test (so --retries doesn’t make sense). I fix the 5 tests manually. Now, I want to just do something like npx playwright test --re-run-last-set-of-failure  and just run the 5 / 100 that failed from the last run to see if my fixes to the tests worked without having to wait on all 100.
>
> (For now, I just enable json reporter and have a magic cat report.json | jq … | xargs playwright test alias to achieve this. I had been using test.only but that became tedious to clean off after the changes before check in.)

Happy to contribute an PR in the coming weeks if it's helpful!

**Comment by unlikelyzero** [comment]
This is something that is incredibly speeds up triage time

**Comment by dimas7** [comment]
Really needed feature. It's hard to re-run failed tests from the suit manually

**Comment by unlikelyzero** [comment]
https://playwrightsolutions.com/whats-the-easiest-way-to-only-re-run-failures-after-the-playwright-test-is-finished/

**Comment by Marviel** [comment]
This would be incredibly helpful.
