### ISSUE TITLE
[BUG] .toBeVisible(), .toHaveAttribute() not working as expected consistently

### ISSUE THREAD

**Issue by judithhartmann** [microsoft/playwright#10517]
**Context:**
- Playwright Version: 1.16.3
- Operating System:Mac
- Node.js version: 16.0.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```typescript

// toBeVisible
test("Verify headline is visible", async () => {
    const pageTitle = page.locator('h1:has-text("Headline")');
    expect(await pageTitle.isVisible()).toBe(true); // this works always
    expect(pageTitle).toBeVisible(); // this does not
});
```

```typescript
// toHaveAttribute
test("Verify menu item is selected", async () => {
    const menuItem = page.locator('#menuItem1');
    expect(await menuItem.getAttribute("aria-current")).toEqual("page"); // this works always
    expect(menuItem).toHaveAttribute("aria-current", "page"); // this does not
 });
```

**Describe the bug**

Matchers fail, when doing the check manually works.

Logger output is the following
```
  Error: expect(received).toBeVisible()

    Call log:
      - waiting for selector "h1:has-text("Headline")"

  Error: expect(received).toHaveAttribute(expected)

    Expected string: "page"
    Received string: ""

```

**Comment by mxschmitt** [comment]
` expect(pageTitle).toBeVisible()` is an asynchronous matcher like all the Playwright assertions: https://playwright.dev/docs/test-assertions

So you need to add an await statement before: `await expect(menuItem).toHaveAttribute("aria-current", "page");`

**Comment by judithhartmann** [comment]
Oh wow. Can't believe i missed that in the docs. 
Thank you!
