### ISSUE TITLE
[Question]: How to perform drag and drop operation on Playwright Headfull tests

### ISSUE THREAD

**Issue by nkulkarni8** [microsoft/playwright#10513]
Hi,
I'm new to Playwright and trying to write a Automated Test on Chrome.
I tried the page.dragAnddrop method and passed the source location & destination location but that doesn't seem to work for me.

Is there any way if I can perform a drag and drop on a web application.
Please suggest

**Comment by dgozman** [comment]
@nkulkarni8  `page.dragAndDrop` should work. If it does not, perhaps there's a bug somewhere? Could you please provide a repro script/scenario so that we can reproduce the issue and fix it?

**Comment by nkulkarni8** [comment]
@dgozman - thanks for your response
it will be tricky to share the repo as we are not allowed to do so within our firm.
My use case is very simple. There is a draggable element which I need to drag and drop to a area on a webpage.
What I see while running my playwright is that - it does not give any error and also the source element is highlighted once, but post that nothing happens.

my code is:
page.dragAndDrop("//source_xpath","//destination_xpath")  -- Do we need to add any more parameters?

**Comment by mxschmitt** [comment]
This should work. What kind of drag'n drop libraries are you using? Would it be possible to create a small repro of it which you are allowed to share? Otherwise it's hard for us to figure out whats going wrong.

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
