### ISSUE TITLE
[Feature] Add ability to register request/response interceptors for `request` fixture

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#10511]
During API testing I would like to collect request/response data. 

Eventually I would want to see something like this
```
#   ==================================================
#   REQUEST: 9h43nzbxlff | 11/23/2021, 10:59:20 PM  <-- Unique identifier of request and time when it started
#   TOKEN: Bearer xwykAEQfgHl7uqXA3vmDC6TaW01cMsm25P
#   METHOD: get
#   URL: /v1/accounts/2e1499e9-d69b-4fd9-9df4-3a41a7eedf10/software-updates
#   ==================================================

#   ==================================================
#   RESPONSE: 9h43nzbxlff | 11/23/2021, 10:59:21 PM <-- Unique identifier of request and time when response was received
#   TIME: 0.603 sec <-- Duration
#   STATUS: 200
#   { }   <-- body of the response
#  ==================================================
```

This is done with [axios interceptors](https://axios-http.com/docs/interceptors) .
Would be nice to have something similar.

**Comment by dgozman** [comment]
We had an idea about exposing `request`-produced network traffic in the HAR format, similar to [`recordHar` option](https://playwright.dev/docs/next/api/class-browser#browser-new-context-option-record-har). Would that work for you?

**Comment by yury-s** [comment]
Merging into https://github.com/microsoft/playwright/issues/10585

**Comment by MindaugasMateika** [comment]
> Merging into #10585

By merging, do you consider these feature requests similar? I was following this issue and I'd like to have interceptor functionality in addition to my feature request 😄 

Personally, for me, interceptors would come in handy for retrying API requests.

**Comment by yury-s** [comment]
> By merging, do you consider these feature requests similar?

Yes, we don't want to expose `request/response/requestfinished` events for APIRequest calls but would like to surface them in the trace viewer for debugging. This is about observing internals of APIRequest flow.

> I was following this issue and I'd like to have interceptor functionality in addition to my feature request smile
> 
> Personally, for me, interceptors would come in handy for retrying API requests.

We didn't plan to add interception for APIRequests as you already have full control over what is sent to the server. We debated adding `retry` option in the past and it seemed rather rare so we omitted it. Can you say more about the retry scenario that you have in mind?

**Comment by MindaugasMateika** [comment]
I was thinking just for a generic retry mechanism. Sometimes backend returns an error so it would be beneficial if the request was retried and it would give more control for it, maybe retry once, maybe retry several times with different intervals. But I suppose someone would find use for let's say token refreshing as well which is quite easy to do with axios interceptors - https://thedutchlab.com/blog/using-axios-interceptors-for-refreshing-your-api-token

**Comment by cunhabruno** [comment]
I am running some tests that creates an API endpoint on the server and when I call the created endpoint to actually test it, the endpoint hasn't been created yet, so a retry mechanism would be handy for this scenario I am doing.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
