### ISSUE TITLE
[Feature] Add an optional parameter to page.fill(...) and page.type(...) to allow users to suppress/obfuscate sensitive data from the logs e.g. passwords

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#10526]
It would be really nice if Playwright had an extra set of optional parameters made available to `page.fill`/ `page.type`

For example:

`await page.locator('[name=password]').type('mysecretpassword',{suppressFromLogs: true})`

Will result in ...

`waiting for selector "input[name=password]"`
`selector resolved to visible <input value="" type="password" name="password" data-lp…/>`
`elementHandle.fill("*******").`     **<< password masked in the logs**
`waiting for element to be visible, enabled and editable`
`element is visible, enabled and editable`

Alternatively, we could have an option to partially obfuscate the value.  This will result in the following entry in the logs:

`waiting for selector "input[name=password]"`
`selector resolved to visible <input value="" type="password" name="password" data-lp…/>`
`elementHandle.fill("sec12****").`     **<< password partially masked in the logs**
`waiting for element to be visible, enabled and editable`
`element is visible, enabled and editable`

PW v1.16.2

**Comment by mxschmitt** [comment]
From where do you want to hide it? Continuous integration logs, Playwright trace viewer, or something else? This would help us to prioritise this feature.

**Comment by ryanrosello-og** [comment]
hey @mxschmitt, for our purpose we would like to suppress from the trace viewer but if its not too much of an effort, it would be nice to extend this to the integration logs as well.

**Comment by AndyGBC** [comment]
I agree with @ryanrosello-og that it would be great to suppress from the trace viewer as this would help us too.

**Comment by pavelfeldman** [comment]
You can only share trace with trusted party, regardless of whether you hide / obfuscate the password. Typically, the password is used to obtain a logged-in token, that is delivered to the browser in a network response and typically stored in the cookie jar. Regardless of whether you've successfully hidden the password, malicious user can use this token to simulate the logged-in behavior. Trace also contains all the network responses that potentially contain sensitive data.

**Comment by myieye** [comment]
FWIW, it's not too hard to mask traces yourself after the fact: https://github.com/microsoft/playwright/issues/19992#issuecomment-1776877071.
