### ISSUE TITLE
[Feature] Set File.path property when uploading files with Electron

### ISSUE THREAD

**Issue by alphabiz-se4** [microsoft/playwright#10527]
My application uses the q-file feature of the quasar framework.[here](https://quasar.dev/vue-components/file-picker#qfile-api) is the q-file link. When a file is uploaded, it gets the path parameter of the file in the files object array to find the local address where the file is located.
This is the file object printed in Developer tools after I uploaded the file manually, you can see the properties 'path' is not empty
![hand](https://user-images.githubusercontent.com/92558550/143387942-2d76574f-a011-41ef-962c-1a7a4b7d674a.jpg)
I uploaded the file using setInputFiles() and 'path' is empty.
`
await window.locator('input[type="file"]').setInputFiles(path.resolve(__dirname, '../cypress/fixtures/samples/GoneNutty.avi'))
`
![1637820410(1)](https://user-images.githubusercontent.com/92558550/143388617-f120a9fa-8084-4eef-8aa9-faab6d85b272.jpg)
I know setInputFiles() has only 3parameters,can I still use other methods to achieve passing 'path',if you see my problem I hope you can help me,thanks a lot.

**Comment by mxschmitt** [comment]
Web File APIs usually don't contain the full path see [here](https://developer.mozilla.org/en-US/docs/Web/API/File/Using_files_from_web_applications). Could you provide us a repro with the component which logs the path? Curious how it does it.

When using the normal file upload via the q-file component it does not contain the path, see here: https://codepen.io/mxschmitt/pen/zYdgPdd?editors=1010

**Comment by alphabiz-se4** [comment]
I forgot to tell you that I was using playwright's Electron() method to test our electron version of the app. i found some information on the electron website and they had added a path attribute to the File interface. see [here](https://www.electronjs.org/docs/latest/api/file-object)

**Comment by mxschmitt** [comment]
Did a first investigation, seems like we need upstream changes [here](https://github.com/electron/electron/blob/3834aaf4e98d7b826afa7113f12e8783b75e27dd/patches/chromium/blink_file_path.patch#L28). My suggested approach would be to add a `path` argument to the `FilePropertyBag` options to have it inside the [File.h](https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/core/fileapi/file.h#L186) object.

**Comment by monica-xu** [comment]
hi, @mxschmitt how about this function now, I met the same issue about the file path being empty in electron, did the playwright already solve it?

**Comment by eliw00d** [comment]
Any progress on this?

I came up with a workaround since we need E2E tests that upload files for our Electron application:

main.js
```
ipcMain.handle('FIND_E2E_FIXTURE', (event, filename) =>
  new Promise((resolve, reject) => {
    glob(`${process.cwd()}/e2e/fixtures/**/${filename}`, { absolute: true }, (error, matches) => {
      if (error) {
        reject(error)
      } else {
        resolve(matches[0])
      }
      })
    })
)
```

preload.js
```
contextBridge.exposeInMainWorld('electronApi', {
  findE2EFixture: (filename) => ipcRenderer.invoke('FIND_E2E_FIXTURE', filename),
})
```

fileUpload.jsx (with react-dropzone)
```
  const handleDrop = async (droppedFiles) => {
    const newFiles = await Promise.all(
      droppedFiles.map(async (file) => file.path || (await window.electronApi.findE2EFixture(file.name)))
    )
    // do stuff with newFiles as normal
  }
```

It at least works as a fallback until this issue gets resolved.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by mxschmitt** [comment]
Looks like this is fixed, I was not able to reproduce it using the following:

```ts
test('should upload the file', async ({ newWindow, server, asset }) => {
  const window = await newWindow();
  await window.goto(server.PREFIX + '/input/fileupload.html');
  const input = window.locator('input[type=file]');
  await input.setInputFiles(asset('file-to-upload.txt'));
  expect(await input.evaluate((e: HTMLInputElement) => e.files[0].name)).toBe('file-to-upload.txt');
  expect(await input.evaluate((e: HTMLInputElement) => {
    const reader = new FileReader();
    const promise = new Promise(fulfill => reader.onload = fulfill);
    reader.readAsText(e.files[0]);
    return promise.then(() => reader.result);
  })).toBe('contents of the file');
  // Electron special case: make sure that the 'path' attribute is set.
  expect(await input.evaluate((e: HTMLInputElement) => e.files[0].path)).toBe(asset('file-to-upload.txt'));
});
```

feel free to re-file / mention this issue if its still happening.
