### ISSUE TITLE
[Feature] Sample folder structure and a test file during playwright installation

### ISSUE THREAD

**Issue by MPonraj** [microsoft/playwright#10530]
Can you please suggest a folder structure for Playwright?
During Cypress installation by default, it creates a sample folder structure and a test file. 
Reference link - https://docs.cypress.io/guides/core-concepts/writing-and-organizing-tests#Folder-structure
Thanks in advance

**Comment by mxschmitt** [comment]
Playwright does not require any specific folder structure. Usually you only have a `tests` folder where all your tests are placed in. If you have a lot of tests, you can create in there more sub-folders. Regarding naming of the files, we either recommend `foo.spec.ts` or `foo.test.ts`.

See e.g. the NPM init package and its outcome: `npm init playwright` which will create a couple of tests and examples.
