### ISSUE TITLE
[Question] Configure webServer to have a https baseURL

### ISSUE THREAD

**Issue by DanieleDiLucido** [microsoft/playwright#10535]
Hi, I'm using the WebServer configuration to serve my page and run the test against it. 
> webServer: {
    command: "yarn watch",
    port: 3333,
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
  },

I'd like to run my test under https but the baseURL returned by Playwright is HTTP only.  Is it possible to have it under https?

Cheers

**Comment by mxschmitt** [comment]
You should be able to do something like this:

```ts
webServer: {
    command: "yarn watch",
    port: 3333,
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
},
use: {
    baseURL: 'https://localhost:3333',
}
```

**Comment by DanieleDiLucido** [comment]
It works 🎉  Thank you for the help 😄
