### ISSUE TITLE
[Question] Is there any built in function to assert list of elements ?

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#10537]

**Comment by mxschmitt** [comment]
- [`await expect(locator).toHaveText(['Text 1', 'Text 2', 'Text 3']);`](https://playwright.dev/docs/test-assertions#expectlocatortohavetextexpected-options)
- [`await expect(locator).toContainText(['Text 1', 'Text 4', 'Text 5']);`](https://playwright.dev/docs/test-assertions/#expectlocatortocontaintextexpected-options)

does this help? both accept also regular expressions.

**Comment by Amrkamel1** [comment]
this will help, but i was thinking to provide a list of elements not list of expected result

**Comment by A-ZC-Lau** [comment]
why can't you just for loop the elements then?

**Comment by bsteffensTempus** [comment]
You can use promise.all to make sure n elements come back. I have a situation where elements load async with unpredictable load times.

```typescript
 async expectAllCards() {
    await Promise.all([
      this.page.waitForSelector(elements.cards.assessments),
      this.page.waitForSelector(elements.cards.cancerDiagnosis),
      this.page.waitForSelector(elements.cards.curatedMolecular),
      this.page.waitForSelector(elements.cards.demographics),
    ]);
  }
}
```

**Comment by pavelfeldman** [comment]
> this will help, but i was thinking to provide a list of elements not list of expected result

Could you give us an idea on when this is useful?

> You can use promise.all to make sure n elements come back. I have a situation where elements load async with unpredictable load times.

This would be a strong anti-pattern.

**Comment by bsteffensTempus** [comment]
> > You can use promise.all to make sure n elements come back. I have a situation where elements load async with unpredictable load times.
> 
> This would be a strong anti-pattern.

----

What is the preferred way to wait for these? The elements I'm waiting for are divs representing graphs in a grafana type dashboard. There are maybe 10 of them and their containers and contents display in 5-60 seconds.

**Comment by bsteffensTempus** [comment]
> > this will help, but i was thinking to provide a list of elements not list of expected result
> 
> Could you give us an idea on when this is useful?
> 
> > You can use promise.all to make sure n elements come back. I have a situation where elements load async with unpredictable load times.
> 
> This would be a strong anti-pattern.

----

What is the preferred way to wait for these? The elements I'm waiting for are divs representing graphs in a grafana type dashboard. There are maybe 10 of them and their containers and contents display in 5-60 seconds.

**Comment by pavelfeldman** [comment]
That depends on what exactly you are waiting for. For example, they can all appear as 'loading...' and only after some time turn into something sensible. That's why `await expect(locator).toHaveText(['Text 1', 'Text 2', 'Text 3']);` is considered the only reliable pattern when testing (as opposed to scraping). Tell us more about your use case!

**Comment by Amrkamel1** [comment]
> why can't you just for loop the elements then?

yes I was doing it like that but If first assertion fail it will break the loop

**Comment by Amrkamel1** [comment]
@pavelfeldman  okay, let's say we have a scenario that we are filling some form then submitting it, after that, we need to assert some values that are matching what we have submitted in the form 

using for loop, will work but it will break the loop once the first assertion fails hence you didn't know whats the status of other values.

using multiple assertion 
expect()..
expect()..

will give the same result, it will through an error once any assertion fails without going to the next one.

so I was checking if there is a way to don't make PW through an error and terminate the test before finishing all assertions in the test.

**Comment by dgozman** [comment]
@Amrkamel1 Sounds like you'd like #7819.

**Comment by vishal7788** [comment]
Hi, can anyone please help me on which assertion I can use to test the below scenario.

I have a list in view mode which gets updated when an item is added from a drawer (angular material). The process takes around 200 to 500 ms to display the new item added to the list.

Here I need to assert whether the newly added item is successfully added to the list. And below is the pseudo steps I'm performing

1. navigate to the page
2. open a drawer
3. select an item
4. click on add button
5. expect('list').toContain(item)

Here the issue I'm facing is that the expect step is getting executed before an item is added to the list thus it is failing. I tried below combination but not of them are working.

1. expect(locator.allInnerText()).toContain(item) => This is also executing before an item is added to the list. Here using await in front of expect does not do anything
2. await expect(locator).toHaveText(item) => This throws an error 'strict mode violation' for finding multiple elements. And if I use locator.allInnerText() to get a list then it does not let me use toHaveText() which uses await.
3. await expect(locator).toContainText(item) => This throws an error 'strict mode violation' for finding multiple elements
4. expect(page.$$('list).toContain(item) => This is also executing before an item is added to the list. Here using await in front of expect does not do anything

So which assertion I can use which will wait for the list to be updated with the newly added item. 

Also please note that I'm already using waitForAngular() to finish all the http calls and waitForLoadState('networkidle') and waitForLoadState('domcontentloaded') as well before executing the assertion, but none of the working.

**Comment by joelkd** [comment]
> > this will help, but i was thinking to provide a list of elements not list of expected result
> 
> Could you give us an idea on when this is useful?
> 
> > You can use promise.all to make sure n elements come back. I have a situation where elements load async with unpredictable load times.
> 
> This would be a strong anti-pattern.

Why is Promise.all() considered a strong anti-pattern? I am looking for a solid reason as to use it or not for tests with multiple assertions.
