### ISSUE TITLE
[Feature] Is it possible to show ElementHandle selector on waitForSelector failure?

### ISSUE THREAD

**Issue by manuman94** [microsoft/playwright#10533]
Hi,

I've been working with Playwright ElementHandle to interact with the page elements. The problem comes when Playwright tries to get some element and the waitForSelector fails showing this message:

```
Error: elementHandle.click: Element is not attached to the DOM
        =========================== logs ===========================
        attempting click action
          waiting for element to be visible, enabled and stable
          element is visible, enabled and stable
        ============================================================
```

The error is self-explanatory, which is nice to us. But we find that it would be more deterministic if the locator of the element (or some descriptive information about it) is printed so we can debug what ElementHandle is searching for.

We come from Protractor, and this kind of errors were printed like this:

```
NoSuchElementError: No element found using locator: By(css selector, *[id="myPageNav_MENU_ELEMENT_1_CHILD_1"])
```
With this message we knew that the problem was related with the element with id=myPageNav_MENU_ELEMENT_1_CHILD_1

Is this possible using ElementHandle? 

Thank you.

**Comment by mxschmitt** [comment]
We usually discourage ElementHandles, since they target a specific node on the page (often web frameworks re-render and then they fail) and recommend Locators instead see [here](https://playwright.dev/docs/api/class-elementhandle).

When using locators, the selector gets printed.

**Comment by manuman94** [comment]
Hi @mxschmitt! Okay, we will need to migrate our projects to use Locators. We experienced some errors and they might be related to that (as our products work with Angular).

And regarding the "descriptive error" issue: if Locators solve that problem we are fine with that.

Thank you!

**Comment by mxschmitt** [comment]
Closing then!

(feel free to create further issues about Locators with your use-cases)
