### ISSUE TITLE
[BUG] Unable to use waitFor to get the required response code

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#10540]
**Context:**
- Playwright Version: 1.16.2
- Operating System: Mac
- Node.js version: 14
- Browser: any

**Code Snippet**

```
    async clickOnSaveButton() {
        await this.saveButton.click()
        await this.page.waitForResponse(res => res.status() === 200 && res.url() === `${configList.baseURL}/users/me`)
        return this;
    }
```
output 

```
    Timeout of 20000ms exceeded.

    page.waitForResponse: Page closed
```

**Describe the bug**

Unable to wait for for response status and the URL

**Comment by Nav-2d** [comment]
Maybe a race condition? Would the example mentioned here in the docs help? https://playwright.dev/docs/api/class-page#page-wait-for-response

**Comment by Amrkamel1** [comment]
yes it's working, please disregard i have a typo in the URL endpoint.
