### ISSUE TITLE
[BUG] File not uploaded via the setInputFiles() function

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10543]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows
- Node.js version: 14.6
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await this.page.setInputFiles(this.fileNameTextFieldLocator, resourceFileToUpload);
```

**Describe the bug**

I'm trying to upload the file via page.setInputFiles() function. 
The locator is the following:
![image](https://user-images.githubusercontent.com/52656401/143475081-135321c2-4b36-4450-8849-d3141c4c9572.png)

It is an input element. But the function doesn't work for me. 

P.S. Maybe it is related to the fact that the input field is defined as a readonly? 

P.S.2 The icon is not defined as input - can it be used in some way in the function? According to documentation  - the function setInputFiles() can be used only with input elements.

**Comment by vsravuri** [comment]
You may need to locate the upload button next to the File Name input field to upload file. If i understood correctly, after you choose the file name using the upload button, file name will be displayed in the File Name filed.

**Comment by AlexKomanov** [comment]
@vsravuri 
If I try to locate the upload icon and use it for the uploading - I get the following error:
![image](https://user-images.githubusercontent.com/52656401/143491887-8c75e9fc-46c9-406a-ab68-b2903e711883.png)

The locator of the icon in the DOM:
![image](https://user-images.githubusercontent.com/52656401/143492031-306fbdf3-15ca-457c-bb0d-832495edbcf1.png)

**Comment by vsravuri** [comment]
@AlexKomanov
Apologize, my suggestion won't work as the locator is a button. I would suggest use codegen and try to upload the file manually. It will capture the correct locator for you to do file upload.

`npx playwright codegen`

**Comment by AlexKomanov** [comment]
@vsravuri 
According to the documentation - the way with input element - should work. Thats why I want to understand the reason that it isn’t.

**Comment by vsravuri** [comment]
Your input should be of type="file", it should be somewhere in the DOM.

**Comment by AlexKomanov** [comment]
@vsravuri Thanks. I will check.

**Comment by AlexKomanov** [comment]
@vsravuri 
The solution provided by you - worked as well. 
After handling the correct input element - the file was uploaded as well.
See the attached screenshot.
![image](https://user-images.githubusercontent.com/52656401/143757491-d5c51f22-17b8-42b0-942a-7c53710a601f.png)

Another solution that worked for me is the following:
![image](https://user-images.githubusercontent.com/52656401/143759362-3254b75e-c2e6-448f-aebe-b429f0fc2517.png)
In that way I provided the selector of the upload icon element and path to the file.

**Comment by pavelfeldman** [comment]
Just an advice, you call your selector `this.fileNameTextFieldLocator`, which confuses me because I think you are using Locator object.

**Comment by pavelfeldman** [comment]
Looks like it worked for you though, so closing.

**Comment by AlexKomanov** [comment]
@pavelfeldman 
It’s just a selector that founded in the DOM. We use the pattern:
textFieldLocator - just stores a selector in the DOM.
textFieldElement - element it self (of any type).
