### ISSUE TITLE
[Feature] Finalizing integration with Allure

### ISSUE THREAD

**Issue by cardinalX** [microsoft/playwright#10549]
Already a large number of people use playwright for testing in real projects. 
And one of the important tools for convenient analysis of results is allure reports. But Playwright, unlike Java + Selenide, still lacks some functionality in Allure. 

**Please implement the ability to add links, descriptions, the severity of the bug**

https://github.com/allure-framework/allure-js/issues/332

There is even a PR already https://github.com/allure-framework/allure-js/pull/408

**Comment by pavelfeldman** [comment]
I reviewed the change in allure repo, it looks good!

**Comment by arturmkr** [comment]
@pavelfeldman 
There is allure-playwright for JS:
https://www.npmjs.com/package/allure-playwright

Is it going to be allure-playwright for Python, Java, .NET?
