### ISSUE TITLE
[Question] How do I take a screenshot of the address bar?

### ISSUE THREAD

**Issue by DisJarp** [microsoft/playwright#10546]
Hello everyone, there was a problem. I need to take a screenshot of the page and capture the address bar at the same time. In the documentation and on the Internet, I could not find an answer on how to do this. Other means also fail, since the execution takes place without starting the browser. Can someone tell me how this can be implemented?

**Comment by mxschmitt** [comment]
This is not possible, a screenshot only contains the actual content of the page. What people usually do is:

a) assert the URL via await [`await expect(page).toHaveURL("/foo/bar")`](https://playwright.dev/docs/test-assertions#expectpagetohaveurlurl-options)
b) assert the screenshot via [toMatchSnapshot](https://playwright.dev/docs/test-snapshots)

Does this work for your use-case?
