### ISSUE TITLE
[BUG]  browserType.launch: Chromium distribution 'chrome' is not found (circleci)

### ISSUE THREAD

**Issue by shelganov-qs** [microsoft/playwright#10541]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Linux
- Node.js version: v16.13.0
- Browser: Chromium
- Extra: @playwright/test, CircleCi - run playwright with docker-compose

**Code Snippet**

I'm using the following dockerfile for the playwright:

```
FROM mcr.microsoft.com/playwright:focal
WORKDIR /usr/e2e
COPY package.json yarn.lock ./
RUN yarn install
RUN apt-get update && apt-get install -y wget
RUN npx playwright install chrome // why this command doesn't help?
COPY . ./
RUN yarn build
```

Playwright config:
```
const config = {
  use: {
    baseURL: process.env.REACT_APP_URL || 'http://localhost:3000',
    viewport: viewport,
    ignoreHTTPSErrors: true,
  },
  globalSetup: require.resolve('./playwright/global.ts'),
  projects: [
    {
      name: 'Chrome Stable',
      use: {
        browserName: 'chromium',
        channel: 'chrome',
      },
    },
    {
      name: 'Desktop Safari',
      use: {
        browserName: 'webkit',
      },
    },
    {
      name: 'Desktop Firefox',
      use: {
        browserName: 'firefox',
      },
    },
  ],
  retries: 2,
}
```

**Describe the bug**

I'm not sure is it a playwright problem or circleci but anyway..

When i start playwright locally - everything is good, tests are completed successfully. When I run tests in the docker-compose in circleci with caching option `docker_layer_caching: true` - get the error (without this option tests finish successfully):

```
browserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome
    Run "npx playwright install chrome"
```

Everything worked in the previous months, but this error began to appear **a few weeks ago**. Safari and firefox work well.

Tried suggestions from [https://github.com/microsoft/playwright/issues/9858](#9858) - it didn't help.

Any ideas? Maybe someone has faced such a problem?

**Comment by mxschmitt** [comment]
> Everything worked in the previous months, but this error began to appear a few weeks ago

This is most likely because your Docker image is not pinned. So focal just got updated to the most recent one. I'd recommend to pin it to a specific Docker image tag. For example:

- `mcr.microsoft.com/playwright:v1.17.0-rc1-focal`
- `mcr.microsoft.com/playwright:v1.16.3-focal`
- `mcr.microsoft.com/playwright:v1.15.2-focal`

Let us know which one was working and which one not.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by worph** [comment]
FYI Having this issue with mcr.microsoft.com/playwright:v1.21.0-focal

**Comment by mxschmitt** [comment]
> FYI Having this issue with mcr.microsoft.com/playwright:v1.21.0-focal

You are using channels. Channels need to be installed manually using npx playwright install chrome

**Comment by snigdhadeb** [comment]
Was facing the same problem with 1.21.0-focal. Now working fine after shifting from channels to desktop chrome. 
`{
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },`
