### ISSUE TITLE
[BUG] Clicking an Electron Menu item doesn't pass expected types

### ISSUE THREAD

**Issue by Nokel81** [microsoft/playwright#10554]
**Context:**
- Playwright Version: 1.15.2
- Operating System: macOS
- Node.js version: 14.16.1
- Browser: Electron 13.6.1

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

I register a menu using the following `MenuItemConstructorOptions`

```javascript
{
    label: "Command Palette...",
    accelerator: "Shift+CmdOrCtrl+P",
    id: "command-palette",
    click(_m, _b, event) {
      /**
       * Don't broadcast unless it was triggered by menu iteration so that
       * there aren't double events in renderer
       */
      if (!event.triggeredByAccelerator) {
        broadcastMessage("command-palette:open");
      }
    },
  },
```

```javascript
const { ElectronApplication, Page } = require('playwright');

(async () => {
  const app = await electron.launch({ ... });
  
  // The following throws
  await app.evaluate(async ({ app }) => {
    await app.applicationMenu
      .getMenuItemById("view")
      .submenu.getMenuItemById("command-palette")
      .click(undefined, undefined, {
        triggeredByAccelerator: true,
      });
  });
})();
```

**Describe the bug**

Even though I try to pass in a fake `Electron.KeyboardEvent` into the `click()` call. It does not get routed to my application.

**Comment by jjeff** [comment]
Check out the [clickMenuItemById() function](https://github.com/spaceagetv/electron-playwright-example/blob/96bb12d1372c624ee3bb74485db27e8db51bc1a8/e2e-tests/electron-playwright-helpers.ts#L11-L24) in my [Electron Playwright Example repository](https://github.com/spaceagetv/electron-playwright-example). Seems like it does what you want to do.

**Comment by Nokel81** [comment]
@jjeff That is actually what I am doing, this bug report is about calling that function not passing to the application the correct data.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
