### ISSUE TITLE
[BUG] [PW 1.16.3] [Chromium] Error: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by dipiash** [microsoft/playwright#10552]
Hello! Our team have the same issue (https://github.com/microsoft/playwright/issues/4764). It's reopen: https://github.com/microsoft/playwright/issues/10316

Local test pass. Remote test (on the https://aerokube.com/moon/) fail because can't wait when page loaded.

Tests was start for the same page: https://dasreda.ru/

**Context:**
Playwright Version: 1.16.3  (the same behavior on 1.8.0)
Operating System: Windows
Node.js version: v14.18.1
Browser: chromium
Extra: codeceptjs (3.0.4 / the same behavior on 3.1.3)

**Code Snippet**
Simple launching a browser and navigating to a page.

**LOGs**
Success (local) - [local-moon-log.log](https://github.com/microsoft/playwright/files/7608293/local-moon-log.log)
Error (Remote) - [remote-moon-log.log](https://github.com/microsoft/playwright/files/7608294/remote-moon-log.log)
 
**Code Snippet**

Example repo: https://github.com/dipiash/codecept-playwrite-bug-report

**Comment by mxschmitt** [comment]
This has most likely something to do with Moon or conceptJS and maybe a version miss match of the browsers/Playwright versions.

I'd suggest to file an issue on their end or create a repro without moon/codeceptJS so its easier for us to investigate since we are not familiar with them.

**Comment by dipiash** [comment]
@mxschmitt thank you for your attention. I think that you are right that problem with Moon or CodeceptJS. If I start tests in a container (for [example](https://github.com/dipiash/codecept-playwrite-bug-report/blob/main/Dockerfile)) - all right.

I will gonna go to open new issues in Moon/CodeceptJS repos.

**Comment by mxschmitt** [comment]
Closing then. 👍

**Comment by dipiash** [comment]
Problem was solved: https://github.com/aerokube/moon/issues/299#issuecomment-982504424

**Comment by DiMiTriFrog** [comment]
Same issue with Python https://github.com/microsoft/playwright-python/issues/1316
