### ISSUE TITLE
[BUG] Final request URL is malformed when using request path prefixed with just slash

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#10557]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 16.3.0
- Browser: All

**Code Snippet**

```
Base URL: https://playwright.dev/api/v2
Request URL: /users
Merged URL: https://playwright.dev/users

Base URL: https://playwright.dev/api/v2/
Request URL: users
Merged URL: https://playwright.dev/api/v2/users
```

**Describe the bug**

When using base URL which doesn't end with `/` and request URL which starts `/` merged URL is malformed and loses a path.

This was somewhat solved in slack and using `./` solves this problem. But I suppose it has some place for improvements.
Also, examples in docs seems to be wrong in this regard for not using `./` - https://playwright.dev/docs/test-api-testing/#using-request-context

**Comment by pavelfeldman** [comment]
Keeping this open to explain this in the docs. While web people are used to the baseURL logic, frameworks like postman use prefix variables instead, hence the confusion.

**Comment by aslushnikov** [comment]
Note to self: add to docs a note about trailing slash for `baseURL`
