### ISSUE TITLE
[Feature] Pass Locator into page.waitForFunction to wait custom condition

### ISSUE THREAD

**Issue by AndreyMelnichenko** [microsoft/playwright#10559]
Provide possible to pass Locator into page.waitForFunction function to wait custom condition on page
Example:
`await page.waitForFunction(async (loc: Locator) => { return await loc.isVisible() === false }, locator, { timeout: this.timeout })
`

In general it possible replace eval/evaluate functionality and be more clear for people who migrate from other frameworks and programming languages.

For example simple way to understand released in WDIO7
`https://webdriver.io/docs/api/browser/waitUntil`

**Comment by dgozman** [comment]
We can do something like `locator.waitForFunction(el => el.childNodes.length === 5)`. Note that the page function does not have access to the `Locator` object, but accepts a dom `Element` instead.

**Comment by AndreyMelnichenko** [comment]
@dgozman 
How about create something more generate methods? Like 
`await page.waitUntil(function(), options)`
and `waitUntil` will wait `function` return `true`, and pool it each `timeout` from `options` object 
Does it make sense?
**Full example:**
`await page.waitUntil(async(el) => { return await locator.innerText() === 'Apply button'}, {pool: 100})`

**Comment by dgozman** [comment]
@AndreyMelnichenko This sounds like some generic retry, not too specific for Playwright. Here is a workaround, let me know if that works for you.

```js
const myPredicate = async locator => { return await locator.innerText() === 'Apply button' };
while (true) {
  const result = await myPredicate();
  if (result)
    break;
  await page.waitForTimeout(100);
}
```

**Comment by pavelfeldman** [comment]
Playwright v1.21 will have this: https://playwright.dev/docs/next/test-assertions#polling
