### ISSUE TITLE
[Question]Is v1.17 not released yet?

### ISSUE THREAD

**Issue by sungjuyea** [microsoft/playwright#10551]
Greetings everyone!
I have a brief question about the latest version(1.17).

[The official docs](https://playwright.dev/docs/intro) tells me that v1.16 is old and I should get the new one(1.17rc).

However, when I check this repo, I only see 1.16.3 is the latest, so I could not use the new features in 1.17([the locator class](https://playwright.dev/docs/api/class-locator#locator-locator), for example).

So is it reliable now to install and use v1.17? (like `yarn add playwright@1.17`)

If I am seriously missing something and a bit ignorant to ask such a question, I would be glad to acknowledge my mistake.

Have a nice day!

<img width="699" alt="Screen Shot 2021-11-26 at 7 26 05 PM" src="https://user-images.githubusercontent.com/81574859/143566483-b0d3b061-a99f-45c1-9d1a-a10a250fb70a.png">

<img width="261" alt="Screen Shot 2021-11-26 at 7 26 31 PM" src="https://user-images.githubusercontent.com/81574859/143566540-ead7751f-76b1-4f29-a294-c91f27bae84f.png">

**Comment by mxschmitt** [comment]
We'll release version 1.17.0 next week, you can try out the release candidate today via: `npm install @playwright/test@1.17.0-rc1` (or just `playwright` if you use the library.)

Sorry for the confusion currently, this warning in the docs is definitely misleading.

**Comment by sungjuyea** [comment]
Thank you for your reply! I appreciate your kindness.

I close this issue as the problem would be soon resolved.
