### ISSUE TITLE
[Question] How to manage multiple environments with multiple URLs in Playwright?

### ISSUE THREAD

**Issue by DanielStoica85** [microsoft/playwright#10553]
Is there a recommended way to handle multiple environment configs in Playwright? 

So for example let's assume we have QA environment and a STAGING environment. But for each of these environments we have two different "baseUrls", not one. Any ideas on how to handle that?

**Comment by mxschmitt** [comment]
Usually people inject `BASE_URL` as an environment variable into Playwright Test and set it in the `playwright.config.ts`. There you could also have a mapping, so only the name of the environment is necessary. 

If you want to run both environment in a single Playwright Test test-run, you can parameterise them, see here: https://playwright.dev/docs/test-parameterize/#parametrized-projects

**Comment by metalcamp** [comment]
I've split config into base, frontend and admin. Both frontend and admin extend base config and all env specific stuff is read from env variables using dotenv-extended.

Base
```
import { PlaywrightTestConfig, devices } from '@playwright/test';

require('dotenv-extended').load({
  errorOnMissing: true,
  errorOnExtra: true,
  errorOnRegex: true,
});

const config: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 2 : undefined,
  use: {
    headless: !!process.env.CI,
    // trace: 'retain-on-failure',
    // screenshot: 'only-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: {
          width: 1920,
          height: 1080,
        },
      },
    },
  ],
};

export default config;
```

Frontend

```
import { PlaywrightTestConfig } from '@playwright/test';
import baseConfig from '../../playwright.config';

const { use, ...rest } = baseConfig;

const config: PlaywrightTestConfig = {
  use: {
    ...use,
    baseURL: process.env.FRONTEND_APP_URL,
  },
  ...rest,
};

export default config;
```

Admin

```

import { PlaywrightTestConfig } from '@playwright/test';
import baseConfig from '../../playwright.config';

const { use, ...rest } = baseConfig;

const config: PlaywrightTestConfig = {
  use: {
    ...use,
    baseURL: process.env.ADMINX_URL,
    ignoreHTTPSErrors: true,
  },
  ...rest,
};

export default config;
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
