### ISSUE TITLE
[Question] How to get browser instance from launchPersistent

### ISSUE THREAD

**Issue by hugomrdias** [microsoft/playwright#1056]
When handling extensions im having troubles with the new launch api.

from browser.launchPersistent how do i get a browser instance so i can
```js
const targets = await this.browser.targets();
const backgroundPageTarget = targets.find(target => target.type() === 'background_page');
```
?

i can do it with browser.launch but then im in incognito mode which makes it harder/impossible to open the background_page devtool window programmatically.

**Comment by hugomrdias** [comment]
With `chromium.launchPersistence` we now we get a context instead of a browser instance, so i can't actually access the `background_page` target.

The only way to get a browser instance now is with `launch` but then in incognito mode i can't programmatically open the devtool window like this

```js
const targets = await this.browser.targets();
const backgroundPageTarget = targets.find(target => target.type() === 'background_page');
this.page = await backgroundPageTarget.page();
// Open extension devtools window
// open a new tab in the extension options page
const extPage = await this.context.newPage();
await extPage.goto(`chrome://extensions/?id=${backgroundPageTarget._targetInfo.url.split('/')[2]}`);
// select the developer mode toggle
const buttonHandle = await extPage.evaluateHandle('document.querySelector("body > extensions-manager").shadowRoot.querySelector("extensions-toolbar").shadowRoot.querySelector("#devMode")');
// click the toggle to activate developer mode
await buttonHandle.click();
// select the background_page link
const backgroundPageLink = await extPage.evaluateHandle('document.querySelector("body > extensions-manager").shadowRoot.querySelector("#viewManager > extensions-detail-view").shadowRoot.querySelector("#inspect-views > li:nth-child(2) > a")');
// click the link to open the background_page devtools
await backgroundPageLink.click();
```

because there is not background page link in incognito mode.

**Comment by pavelfeldman** [comment]
Makes sense. We'll figure it out.

**Comment by dgozman** [comment]
With #1089, targets are currently available on `ChromiumBrowserContext`:

```
const persistentContext = await chromium.launchPersistent(userDataDir);
const targets = await persistentContext.targets();
const backgroundPageTarget = targets.find(target => target.type() === 'background_page');
```

That said, targets api will change soon, becoming partially cross-browser. I will post again here with a new snippet. Thank you for your patience while we figure this out 😄

**Comment by hugomrdias** [comment]
thank you for your help @dgozman 
FYI in tested the snippet with 0.11.1-next.1183 and targets doesn't have a background_page.

looking forward for the new api changes :)

**Comment by dgozman** [comment]
In the next release, persistent Chromium browser context will expose `backgroundPages()`. See [this test](https://github.com/microsoft/playwright/blob/27eb25acef756c437c7389528f4e901d04e286fe/test/chromium/launcher.spec.js#L80-L91) for a code snippet.

Closing for now, please reopen if you find any issues.
