### ISSUE TITLE
[BUG] codegen seems to trip over elements with namespace prefixes

### ISSUE THREAD

**Issue by refactoreric** [microsoft/playwright#10561]
**Context:**
- Playwright Version: 1.17.0-rc1
- Operating System: Windows
- Node.js version: v17.0.1
- Browser: Chromium
- Extra: Frontend with mixture of AngularJS (Legacy) and React

**Describe the bug**
When using Playwright codegen, I can log in successfully on our application, and that's recorded properly, but as soon as the main frontend is loaded, a lot of the elements generate errors in the console when hovering over them. Also such elements are not marked/highlighted, and when clicking, the wrong element is recorded, and the wrong element receives the event (usually resulting in nothing happening in the frontend).

I think it's related to elements with namespace prefixes. Examples of such elements are ng:switch, cr:desktop-view, twf:app-search-container, ui:icon, etc.

The error in the JavaScript console is: Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': 'twf:app-search-container' is not a valid selector.

Unfortunately I don't have an easy way to describe a reproduction scenario since the application (and more importantly, the credentials) is private.
If needed, I might be able to arrange demo credentials though.

![playwright-rc-1-17-codegen-console-errors](https://user-images.githubusercontent.com/94195748/143685080-b07f9e42-97d3-41bc-a899-421e8b8a5bd1.PNG)

**Comment by mxschmitt** [comment]
Was able to repro. URL: https://code.angularjs.org/0.9.9/docs-0.9.9/index.html#!angular.widget.ng:switch

**Comment by refactoreric** [comment]
Thank you, that works a whole lot better!
