### ISSUE TITLE
[BUG] Viewport reset when I click on element

### ISSUE THREAD

**Issue by andreirogal** [microsoft/playwright#10579]
**Context:**
- Playwright Version: 1.16.3
- Operating System: uname -a    
Linux darkflame 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux 
- Node.js version: v16.13.0
- Browser: Chromium

## System:
 - OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 917.78 MB / 14.98 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**
https://github.com/andreirogal/playwright-viewport-bug

**Describe the bug**
Viewport reset when I click on element. See more https://github.com/andreirogal/playwright-viewport-bug
![2021-11-29_13-59](https://user-images.githubusercontent.com/42994950/143858050-c26b7fb7-998c-4753-868c-d5182ad23319.png)
![2021-11-29_13-57](https://user-images.githubusercontent.com/42994950/143858055-fadb282d-4bcf-45e8-99ce-0d1e9da45f72.png)

**Comment by 2gury** [comment]
Guys, I'm also reproducing, how can I fix it?

**Comment by andreirogal** [comment]
@pavelfeldman THANK YOU SO MUCH! This solved the problem! I wrote in more detail in the last comment https://github.com/andreirogal/playwright-viewport-bug/commit/357fcbc1d92551496cc1a5a26b5c53bf213abc72

I propose to include this in the documentation https://playwright.dev/docs/intro#configuration-file: Do not use together ...devices and browserName)))
