### ISSUE TITLE
[Question] wait for console debug event using Firefox browser

### ISSUE THREAD

**Issue by cunhabruno** [microsoft/playwright#10575]
Using the below code, I am waiting for a console message in **debug level** to be displayed in the browser, when I run with Chrome it works fine, but when I run with firefox, the console messages that are on debug level are not captured, is there any specific configuration I need to do, to be able to listen for debug level console messages using Firefox browser?

``` js
        try {
            await this.page.waitForEvent('console', {
                predicate: async (consoleMessage: ConsoleMessage) => {
                    return consoleMessage.text() === message
                },
                timeout: timeout
            })
        } catch (e) {
            throw new Error(`error waiting for message "${message}" Cause: ${e}`)
        }
```

**Comment by mxschmitt** [comment]
Could you provide a full example including the code where you call console.debug? I've tested a few cases with Firefox and all are working fine for me.

**Comment by cunhabruno** [comment]
Hello @mxschmitt thanks for the quick reply!

Actually, the `console.debug ` is called in the application side, not on my Playwright tests. On the Playwright side I am just using the code I provided in the previous message, to wait for the debug message. I have executed the tests using `PWDEBUG=1` and I could see the message in Firefox devtools, but Playwright wasn’t able to find the message.

**Comment by mxschmitt** [comment]
My guess is that the `console.debug()` call happened already before calling waitForEvent. So you can do either:

````ts
const waitForYourSpecificConsoleEvent = page.waitForEvent('console');
// .... your logic which triggers the console event
await waitForYourSpecificConsoleEvent
```

or something like:

```ts
await Promise.all([
  page.waitForEvent('console'),
  page.click(".."), // replace with your logic which triggers the event
])
```

(Without a full repro its hard to debug)

**Comment by cunhabruno** [comment]
I have tried using both approaches, I will try to come up with some better example to repro it and get back here once I have it :)

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
