### ISSUE TITLE
[Question] Is there a way to use the locator method via ElementHandle Object?

### ISSUE THREAD

**Issue by cjydayang** [microsoft/playwright#10571]
Example as:

![image](https://user-images.githubusercontent.com/24446099/143835781-740bca15-da7f-4d4a-ba30-be7950fe2deb.png)

but use query_selector works well

![image](https://user-images.githubusercontent.com/24446099/143835914-c767193c-515d-4332-9721-4740c645655a.png)

**Comment by pavelfeldman** [comment]
No and you should not need it. There are multiple ways of achieving what you are trying to do:

```js
page.locator('div:nth-child(5) > label >> .. >> div.add_user');
```

Not sure what 'AddUser' is going to select though.

**Comment by cjydayang** [comment]
@pavelfeldman 

Thanks for your reply.
I use this method in order to achieve the following steps:

1. locate a element by using page.locator (such as page.locator('text=Log in') )
2. Locate its parentNode by executing javascript (Why not locate directly by locator because some element's css selector is hard to find)
3. then use page.locator to find other element

If not, do you have any other suggestions

**Comment by s3naid** [comment]
I would like to know how to handle this case?

In my own scenario where the only way to get dropdown is to use label above (there are multiple dropdowns). 
```
<div>
    <div class=dropdown-holder>
        <label>Select Item</label>
        <div class=dropdown>.....</div>
    </div>
    <div class=dropdown-holder>
   ......
   </div>
</div>
```

This way I get parent `<div>` and then i click on dropdown inside it.

So I have something like this:
`const loc = await page.locator('*css=.dropdown-holder >> text=Select Item').elementHandle()`
and the in the next line:
`await ( await loc.$('.dropdown')).click()`


What is the best approach to handle this ?
I could use `page.$` and it should be easy.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
