### ISSUE TITLE
[Question] Is framenavigated event guaranteed to fire on reload?

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#10578]
Hello,

I'm a bit confused whether [`framenavigated` event](https://playwright.dev/docs/api/class-page/#page-event-frame-navigated) is designed to be fired on page reload or not. Its descriptions, in the website and [in this repo](https://github.com/microsoft/playwright/blob/f7da3c31f90c5becb5f6193efa6c0cc0f6ae81ce/docs/src/api/class-frame.md), state that it is fired when the page navigates to a new, different URL. However, in practice, it will also be emitted on page reload, in all three browsers.

I didn't file this as a bug instead a question because if it is not expected to be fired on reload, there seems no easy way to listen page reload events anymore. I considered `page.on('load')` but it fires for all frames and is hard to distinguish the main frame's one. But again broswing the test cases there seems no test for this "reload" case. So it's just confusing. Could you please clarify its behavior here? If it is not expected to be fired on reload, I'm willing to file a bug report then.

Thanks!

**Comment by pavelfeldman** [comment]
> I didn't file this as a bug instead a question because if it is not expected to be fired on reload

Page reload is equivalent to navigating to the same URL again. So `framenavigated` will be fired and once page loads, `load` is fired.

> I considered page.on('load') but it fires for all frames

This should not be the case, load event only fires for main frame.

**Comment by PaperStrike** [comment]
> This should not be the case, load event only fires for main frame.

Yes, playwright won't listen on the child frames for this, but still it can't be used to distinguish the main frame's reloads, as child frames' load events affects the main frame's ones, in all three browsers. 😟

```js
const playwright = require('playwright');
['chromium', 'firefox', 'webkit'].reduce(async (last, browserName) => {
  await last;
  console.log(`=== test start ${browserName} ===`);

  const browser = await playwright[browserName].launch();
  const page = await browser.newPage();

  page.on('load', () => {
    console.log('load event');
    page.evaluate(() => {
      const frame = document.createElement('iframe');
      frame.src = '/any-path-valid-or-invalid';
      document.body.append(frame);
    }).catch(() => {});
  });
  await page.reload();

  await page.evaluate(() => new Promise((resolve) => setTimeout(resolve, 100)));
  await browser.close();

  console.log(`=== test end ${browserName} ===`);
}, Promise.resolve());
```

Thanks for clarifying the `framenavigated` event's behavior! So now I know it is safe to use for reload navigations!
