### ISSUE TITLE
[BUG] module not found, when running test (works fine when running my app)

### ISSUE THREAD

**Issue by thepuzzlemaster** [microsoft/playwright#10574]
**Context:**
- Playwright Version: ^1.15.0
 - OS: macOS 12.0.1
 - Memory: 5.02 GB / 32.00 GB
 - Node: 17.0.1 - /opt/homebrew/bin/node
 - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
 - npm: 8.1.0 - /opt/homebrew/bin/npm
 - Bash: 3.2.57 - /bin/bash

**Repro**
I've created a minimal repro here using the next/playwright boilerplate starter code.

https://github.com/thepuzzlemaster/playwright-defect-repro
 - `yarn install`
 - `yarn build`
 - `yarn start`
 - `yarn test:e2e`

**Describe the bug**
I had initially created [this discussion](https://github.com/microsoft/playwright/discussions/10564) trying to get some help with my issue. But once I was able to create a minimal repro, it felt more appropriate to create a bug report for it.

I haven't been able to wrap my head around what's going on here. But when I run my playwright test, I get a "module not found" error when it tries to compile (I think). The app runs fine outside of running the tests. There seems to be a problem with the re-exporting of MyModule in `modules/MyModule/index.ts`.

Anyone have some insight into what's going wrong here?

**Comment by mxschmitt** [comment]
The reason is that it's a `TSX` file, Playwright Test does not support TSX / component testing see #7148.

You could transpile your TypeScript yourself see this guide: https://playwright.dev/docs/test-typescript then it should work or avoid importing TSX files.

**Comment by thepuzzlemaster** [comment]
Ahhhh, thanks for the explanation. That makes some sense (although I'm surprised I couldn't find any other instances of issues like this in all my searching). As I'm not actually using tsx in my test file, but it is up the dependency chain, so I would have expected more people to run into something like this before given the popularity of the library. 

Anyways, I'll give that self-transpilation a try and see if that unblocks me. 

Thank you!
