### ISSUE TITLE
[Question] How to calculate the total number of elements available for a xpath in playwright

### ISSUE THREAD

**Issue by AmanDaharwal** [microsoft/playwright#10584]
Trying to capture multiple elements using below xpath
`const elements = "xpath=//*[text()='Table']/parent::*//tbody//tr";
`
getting a total of 50 element for the above xpath in inspect window.

Trying to store all these element using 
```
let value = await this.page.$$(txtBillingRoasterTableRows);
console.log("value length is ",value.length);
```
but getting value.length as 1.
How can I get the expected total of 50?

**Comment by pavelfeldman** [comment]
You are probably calling it too early. Also $$ is discouraged, use locators instead. See https://playwright.dev/docs/api/class-page#page-query-selector-all.

**Comment by AmanDaharwal** [comment]
Thanks it worked.
Added additional wait time before looking for elements

**Comment by pavelfeldman** [comment]
You should not wait for the time, you should wait for elements:

```js
await page.locator('tr').first().waitFor();
console.log(await page.locator('tr').count());
```

**Comment by noumanshahid12** [comment]
> You should not wait for the time, you should wait for elements:
> 
> ```js
> await page.locator('tr').first().waitFor();
> console.log(await page.locator('tr').count());
> ```

What is output of this code?

**Comment by noxify** [comment]
> What is output of this code?

the number of rows 😏

**Comment by noumanshahid12** [comment]
> You should not wait for the time, you should wait for elements:
> 
> ```js
> await page.locator('tr').first().waitFor();
> console.log(await page.locator('tr').count());
> ```

but it not print all rows it print few rows

**Comment by noxify** [comment]
All rows which are visible on the current page, yes.
The snippet contains also the row inside the `thead` ( if there is any ).
To make sure that you get only the "data rows", it would be better to use `tbody > tr`

**Comment by noumanshahid12** [comment]
> 
It is not giving me the right answer if the total row of the table is 84 but it is giving 90

 await page.waitForSelector('tbody');
        const tableRows = 'tbody tr';
        let rowCount = await page.$$eval(tableRows, rows => rows.length);
        console.log(rowCount);

**Comment by noxify** [comment]
> > 
> 
> It is not giving me the right answer if the total row of the table is 84 but it is giving 90
> 
> await page.waitForSelector('tbody'); const tableRows = 'tbody tr'; let rowCount = await page.$$eval(tableRows, rows => rows.length); console.log(rowCount);

to be honest, without more information about the page structure, it's hard to help ;)

Anyway... here an short example: https://github.com/noxify/playwright-issue-10584

1. clone it
2. run `npm install`
3. run `npm run test`

**Comment by noumanshahid12** [comment]
https://github.com/noumanshahid12/Playwright/blob/main/tests/JobOrderStatus.test.ts

**Comment by noxify** [comment]
@noumanshahid12 - thanks - i tried to get it running locally, but I get an timeout.

Could you please provide a running example or some steps to get it running?

**Comment by SalahAdDin** [comment]
> You should not wait for the time, you should wait for elements:
> 
> ```js
> await page.locator('tr').first().waitFor();
> console.log(await page.locator('tr').count());
> ```

It would be good if it also use `findAll` or something like that.

**Comment by jesseaf** [comment]
> You should not wait for the time, you should wait for elements:
> 
> ```js
> await page.locator('tr').first().waitFor();
> console.log(await page.locator('tr').count());
> ```

I found 31 tr records, how can I get the <td> of each of them?

**Comment by ltsuda** [comment]
> > You should not wait for the time, you should wait for elements:
> > ```js
> > await page.locator('tr').first().waitFor();
> > console.log(await page.locator('tr').count());
> > ```
> 
> I found 31 tr records, how can I get the of each of them?

Does is it help https://playwright.dev/docs/locators#rare-use-cases?

**Comment by dveerl01** [comment]
very useful and worked for me as well
