### ISSUE TITLE
[BUG] console.timeEnd output is different in Firefox when running a playwright test

### ISSUE THREAD

**Issue by redfave** [microsoft/playwright#10580]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows 10
- Node.js version: 16.6.2
- Browser: Firefox

I have built an application and added some timers with [console.time()](https://developer.mozilla.org/en-US/docs/Web/API/console/timeEnd#examples) to measure the loading time of specific stages. Now I'm building a benchmark with playwright to run the application in different browsers and save the timing into a CSV file.
The issue I stumbled on is that in the playwright test, the console output in Firefox is different as usual and only the timer label is printed, but not the time it took. Hence, I can't parse the console output correctly for Firefox and my CSV file for Firefox stays empty.

Console output when running the application in Firefox:
`Importing packages used in python scripts.: 2274ms - timer ended`

Console output when playwright runs Firefox:
`Importing packages used in python scripts.`

This issue is not regarded to the Firefox Nightly build, which playwright is shipping as the console output is correct, when I launch Firefox Nightly manually from `%USERPROFILE%\AppData\Local\ms-playwright\firefox-1297\firefox` and use it to access my application. Therefore, it must be some configuration issue when playwright launches Firefox. 
With Chromium everything works as expected.

playwright.config.js:
```javascript
const {devices} = require('@playwright/test');

const time_out = 1000 * 60 * 10;
const config = {
    webServer: {
        command: 'npm run serve',
        port: 8080,
        timeout: time_out
    },
    timeout: time_out,
    forbidOnly: !!process.env.CI,
    retries: process.env.CI ? 2 : 0,
    projects: [
        {name: 'firefox', use: {...devices['Desktop Firefox']},},
        {name: 'chromium', use: {...devices['Desktop Chrome']},},
        // {name: 'webkit', use: {...devices['Desktop Safari']},}, no WASM support on windows in playwright webKit
    ],
    workers: 1,
    use: {
        trace: 'on-first-retry',
        headless: false,
    },
};
module.exports = config;
```

benchmark.spec.ts
```javascript
import { createObjectCsvWriter }from 'csv-writer';
import {test, expect} from '@playwright/test';

const csvHeader = [
    {id: 'state', title: 'STATE'},
    {id: 'duration', title: 'DURATION'}
]

let csvWriter: any

interface recordInterface {
    state: string,
    duration: string
}

const records: Array<recordInterface> = [];

test.describe.serial.only('group', () => {
    test('benchmark run', async ({page, baseURL, browserName }) => {

        csvWriter = createObjectCsvWriter({
            path: `src/bench/bench_${browserName}.csv`,
            header: csvHeader
        });

        await page.goto(baseURL);
        const title = page.locator('h1')
        await expect(title).toHaveText('WASM Pyodide + ONNX-Runtime-Web demo');

        page.on('console',  msg => {
            if (msg.type() === 'timeEnd' || msg.type() === 'timeLog') { // no timeLog support available yet :(
                const startSeparator = msg.text().lastIndexOf(':');
                const endSeparator = msg.text().lastIndexOf('ms');
                const recordState = msg.text().substring(0, startSeparator - 1);
                const recordDuration = msg.text().substring(startSeparator + 1, endSeparator);
                records.push({state: recordState, duration: recordDuration});
            }

        });
        await page.waitForSelector('button:not([disabled])', {timeout: 0});
        await csvWriter.writeRecords(records);
    });

});
```

**Comment by mxschmitt** [comment]
Seems like the formatting logic happens somewhere else in devtools land:

https://github.com/mozilla/gecko-dev/blob/21f0bb70ce5747d18625ad1c67f03ed2af7f9c56/devtools/client/webconsole/utils/messages.js#L178-L205

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
