### ISSUE TITLE
[Question] I want to create a thread to handle the popup problem

### ISSUE THREAD

**Issue by wangzyh** [microsoft/playwright#10598]
Due to the instability of the test environment, When the script is running, various pop-up boxes will occasionally pop up, causing the test to fail.
So is it possible to start a thread to monitor the page, when a pop-up appears, enter the thread to process the pop-up, click OK or cancel and other buttons.
I consider using `worker_threads` to create `workers` for processing, but it cannot be used to transfer `page` objects
![image](https://user-images.githubusercontent.com/31379713/144010716-55b2fe44-1a9b-4302-a8ab-40b1cd5b21bf.png)

So is there a ready-made solution for `playwright`?

type of popup like this:
![image](https://user-images.githubusercontent.com/31379713/144023108-bdc6d93a-a58c-4fa9-8031-47638ea84671.png)

**Comment by yury-s** [comment]
There is no generic way of handling such overlay dialogs. Usually, you'd know that it may pop up after a certain user action and can wait for either the dialog to show up or another condition to be triggered (say page navigated to your app landing page) and then have a branch in your code that handles the dialog overlay before proceeding.

**Comment by pavelfeldman** [comment]
You don't need threads in Node, you do:

page.on('popup', async () => {
   // this essentially is like a separate thread that handles new popups
});
