### ISSUE TITLE
[BUG] page.on('response') modified headers are missing in the request

### ISSUE THREAD

**Issue by adigaboy** [microsoft/playwright#10599]
**Context:**
- Playwright Version: 1.13.1 & 1.16.3
- Operating System: Linux
- Node.js version: v16.13.0
- Browser: chromium
- Extra: nothing

**Code Snippet**

```Javascript
        const browser = await playwright.chromium.launch()

        const page = await browser.newPage()
        await page.route('**/*', async (route) => {
            const headers = await route.request().allHeaders()
            headers['new-header'] = 'hello-world'
            route.continue({ headers })
        })

        page.on('response', async (response) => {
            console.log(await response.request().allHeaders())
        })
        await page.goto('https://httpbin.org/headers/')
```

**Describe the bug**

Added headers to modified request are not in the response event.

Version 1.13.1: I see the header that I have added. (using headers() instead of allHeaders())
Version 1.16.3: I do not see the header that I have added.

was there a change in behaviour? I didn't find anything in the release logs.

**Comment by pavelfeldman** [comment]
I don't think we've ever expected to see the modified headers in the event. You have the original request that page does, it's headers are available, then you modify them as the request is being sent (transient change). So maybe while migrating to allHeaders we fixed a bug that was mutating a live object that led to the side effect you observe.

**Comment by adigaboy** [comment]
Thanks for your answer, I would like to disagree on the expected behavior here is why:
The responses original request is no longer relevant because of the changes that had happened in the modifying event.
Furthermore the request that goes out is also the modified one so I don't see the point of having the original request related to the response in the event.

**Comment by adigaboy** [comment]
OK I see it's not getting priority or being addressed, I guess I'll have to save the modified request and load it in the response event.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
