### ISSUE TITLE
[BUG] playwright inspector color are bad 

### ISSUE THREAD

**Issue by WaliAblikim** [microsoft/playwright#10602]
**Context:**
- Playwright Version: [1.16.3]
- Operating System: [Linux ]
- Node.js version: [14.18.1]
- Browser: [ Chromium, Firefox]
- chrome version:  Version 97.0.4666.0 (Developer Build) (64-bit)
- Firefox : 93.0
- 

**Describe the bug**
I recently upgrade my package version and playwright inspector color getting bad 

**if I use playwright + chromium both of them color is bad** 
![image](https://user-images.githubusercontent.com/78089343/144024240-fb618951-596f-4166-a24f-8dbd4b9cb0f0.png)

**if I use playwright + Firefox ,  browser color is good playwright inspector color is bad** 
![image](https://user-images.githubusercontent.com/78089343/144024429-4f16a091-104f-481b-8b08-070460768605.png)

* * * * * * * * * * * * * * * * * 
same  bug I have submitted a month  ago   here : https://github.com/microsoft/playwright/issues/9122
but I don't think it is chromium problem , because if I use Firefox, browser color is good playwright inspector color is bad,    

so guys did anyone has some problem here

**Comment by pavelfeldman** [comment]
This looks like a problem with your system (Malware / FS corruption, etc). Previous bug suggests that the problem was the same without Playwright, just with Chrome, so it was closed. My understanding is that nothing changed since then, so closing this.

**Comment by WaliAblikim** [comment]
@pavelfeldman  but when I use Firefox, browser color is good, playwright inspector is bad,      what about this mate ?  
one more thing  now I use chromium without playwright color is good, 
Previous bug suggestion not fully explain the problem , that's why I have created new one.
