### ISSUE TITLE
[Question] Is there a way to work with insecure https connection?

### ISSUE THREAD

**Issue by Niyarlatotep** [microsoft/playwright#1060]
When I run test it fails because of insecure ssl, can I allow insecure cert for testing cases? Is there any option?

**Comment by pavelfeldman** [comment]
Check out `ignoreHTTPSErrors` option in [browser.newContext](https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#browsernewcontextoptions).

**Comment by pavelfeldman** [comment]
Please feel free to reopen if my response did not address your issue!

**Comment by Niyarlatotep** [comment]
@pavelfeldman Thank you! It works

**Comment by raghureddy5518** [comment]
@pavelfeldman can you please give the syntax for the same.?

**Comment by pelegshr** [comment]
will this work with playwright API ?

**Comment by PeterBorisenko** [comment]
where should I place `ignoreHTTPSErrors = true`?

**Comment by pelegshr** [comment]
In the browser Context 
Example : 
                self._browser_context = await browser.new_context(storage_state=storage_state, no_viewport=True,
                                                                  ignore_https_errors=True, viewport=viewport)
