### ISSUE TITLE
[BUG] console.count/countEnd event has wrong args in chromium/webkit, wrong text in firefox, and wrong type in webkit

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#10604]
**Context:**
- Playwright Version: 1.18.0-alpha-nov-29-2021
- Operating System: Windows, Linux
- Node.js version: 14.18.0, 16.13.0
- Browser: All
- Extra: N/A

**Code Snippet**

```javascript
const playwright = require('playwright');

['chromium', 'firefox', 'webkit'].reduce(async (last, browserName) => {
  await last;
  console.log(`=== test start ${browserName} ===`);

  const browser = await playwright[browserName].launch();
  const page = await browser.newPage();

  let lastPrint;
  page.on('console', (message) => {
    lastPrint = Promise.all([
      message.args()[0]?.jsonValue(),
      lastPrint,
    ]).then(([firstArg]) => {
      console.log(message.type(), message.text(), firstArg);
    });
  });
  await page.evaluate(() => {
    console.count('alice');
    console.count('alice');
    console.count('bob');
    console.count('alice');
    console.count('bob');
    console.countReset('bob');
    console.count('bob');
    console.countReset('alice');
  });
  await browser.close();

  console.log(`=== test end ${browserName} ===`);
}, Promise.resolve());
```

**Describe the bug**

Running the snippet produces:

```
=== test start chromium ===
count alice: 1 alice: 1
count alice: 2 alice: 2
count bob: 1 bob: 1
count alice: 3 alice: 3
count bob: 2 bob: 2
count bob: 1 bob: 1
=== test end chromium ===
=== test start firefox ===
count alice alice
count alice alice
count bob bob
count alice alice
count bob bob
countReset bob bob
count bob bob
countReset alice alice
=== test end firefox ===
=== test start webkit ===
debug alice: 1 undefined
debug alice: 2 undefined
debug bob: 1 undefined
debug alice: 3 undefined
debug bob: 2 undefined
debug bob: 1 undefined
=== test end webkit ===
```

* For chromium, the argument passed should be `'alice'`/`'bob'`, not the one with counts. The same applies to `.timeLog`/`.timeEnd`, but you seem to resolving it in #10580.
* For firefox, the text has no generated counts, possibly related to #10580, too.
* For webkit, console count events are received as console debug events with no arguments.

**Comment by pavelfeldman** [comment]
Setting P3 as this is a low priority. If someone fixes it, we will consider merging the patch.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
