### ISSUE TITLE
[BUG] console.timeLog event only caught in WebKit

### ISSUE THREAD

**Issue by redfave** [microsoft/playwright#10614]
**Context:**
- Playwright Version: 1.16.3
- Operating System: MacOS 11.4 BigSur
- Node.js version: 16.13.0
- Browser:  WebKit

This bug is probably related to #10580 and #10604.

On Windows/Linux on Chrome and Firefox only the console.timeEnd event is caught, but not console.timeLog. On MacOS on WebKit console.timeLog is also caught, even when the [documentation states](https://playwright.dev/docs/api/class-consolemessage#console-message-type) that only console.timeEnd is supported.
This leads to fail the following test on MacOS and WebKit as ` if (msg.type() === 'timeEnd' || msg.type() === 'timeLog') ` is more often truthy in this case and `expect(records.length).toBe(6);` fails as the array is bigger than expected.

```javascript

import {createObjectCsvWriter} from 'csv-writer';
import {test, expect} from '@playwright/test';


const csvHeader = [
    {id: 'state', title: 'STATE'},
    {id: 'duration', title: 'DURATION'}
]

let csvWriter: any

interface recordInterface {
    state: string,
    duration: string
}

const records: Array<recordInterface> = [];

    test('benchmark run', async ({page, baseURL, browserName}) => {

        csvWriter = createObjectCsvWriter({
            path: `src/bench/bench_${browserName}.csv`,
            header: csvHeader
        });

        page.on('console', msg => {
            if (msg.type() === 'timeEnd' || msg.type() === 'timeLog') { // no timeLog support available yet :(
                const startSeparator = msg.text().lastIndexOf(':');
                const endSeparator = msg.text().lastIndexOf('ms');
                const recordState = msg.text().substring(0, startSeparator - 1);
                const recordDuration = Math.round(parseFloat(msg.text().substring(startSeparator + 1, endSeparator).trim())).toString();
                records.push({state: recordState, duration: recordDuration});
            }
        });

        await page.goto(baseURL);
        const title = page.locator('h1')
        await expect(title).toHaveText('WASM Pyodide + ONNX-Runtime-Web demo');

        const btnSelector = 'button:not([disabled])';
        await page.waitForSelector(btnSelector, {timeout: 0});
        records.forEach( (record: recordInterface) => {
            expect(record.state).not.toBe('');
            expect(record.duration).not.toBe('');
        });
        expect(records.length).toBe(6);
        await csvWriter.writeRecords(records);
    });

```

**Comment by pavelfeldman** [comment]
Marking as P3 in case there are any takers, does not look like a priority for Playwright testing atm.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
