### ISSUE TITLE
[BUG] trailing zero width whitespace fails toHaveText

### ISSUE THREAD

**Issue by jtgober** [microsoft/playwright#10620]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows
- Node.js version: 14.18.1
- Browser: chromium
- Extra: n/a

```
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.locator('text=Get started').click();
  await expect(page.locator('#installation')).toHaveText("Installation​");
});

```

The issue has to do with the expect statement when this is ran, it fails the test. However, see the expected v.s. the received

    Error: expect(received).toHaveText(expected)

    Expected string: "Installation"
    Received string: "Installation​"

What is bizarre, is if I were to copy/paste the **Received string: "Installation**​" into the toHaveText field, it comes back successful, although there are no changes. 

https://user-images.githubusercontent.com/57597859/144140333-a5089300-5939-4e6e-acaf-9474a213dc92.mp4

**Comment by pavelfeldman** [comment]
Looks like a real bug. There is a trailing zero width space in the end of the actual string. toHaveText should have been forgiving and should have accepted it as a proper value.
