### ISSUE TITLE
[BUG] HTTP requests to localhost not going through proxy with Chrome

### ISSUE THREAD

**Issue by thomascube** [microsoft/playwright#10631]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac and Linux
- Node.js version: v12.20.0
- Browser: Chromium
- Extra: Proxy configuration to test with OWASP

**Code Snippet**

I'm setting the proxy options in the `use` section of `playwright.config.js` like this:

```javascript
// playwright.config.js
import { PlaywrightTestConfig, devices } from '@playwright/test';

const proxyHost = process.env.LOCAL_PROXY_HOST || 'localhost';
const proxyPort = process.env.LOCAL_PROXY_PORT || '8080';

const config: PlaywrightTestConfig = {
  testDir: 'tests',
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  globalSetup: require.resolve('./global-setup'),
  use: {
    baseURL: 'http://localhost:4200',
    viewport: { width: 1280, height: 1580 },
    ignoreHTTPSErrors: true,
    trace: 'on-first-retry',
    storageState: 'auth-state.json',
    proxy = {
      server: `http://${proxyHost}:${proxyPort}`
    }
  },
  webServer: {
    command: 'npx ng serve',
    port: 4200,
    timeout: 120 * 1000,
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    }
  ],
};
export default config;
```

**Describe the bug**

When running playwright with a simple Angular application that is served from `localhost:4200`, requests to `localhost` are not going through the configured proxy (they are not logged in the proxy) but all other requests do. This problem only occurs with a Chromium browser, it works as expected with Firefox where I can see all requests logged in the proxy.

Is this a known behavior or are there any additional options we could set to enforce proxy for localhost? Browserstack has similar options (`forceProxy`).

**Comment by thomascube** [comment]
Great, with that option it now works! Thanks a lot for your help.
Would it be worth to mention that trick somewhere in the [docs](https://playwright.dev/docs/api/class-testoptions#test-options-proxy)?

**Comment by rwoll** [comment]
@mxschmitt do you want me to re-open this MR and with just the doc edits? https://github.com/microsoft/playwright/pull/8245

I'd even go further, if PW team doesn't think it would break anyone, to auto add the special loopback bit by default behind the scenes. This one bit me too!

**Comment by pavelfeldman** [comment]
@rwoll: why didn't we do it last time? Looks like an ok thing to have by default.

**Comment by rwoll** [comment]
@pavelfeldman didn't think enough people had hit it, since it just looked like me at that point hehe. Now that someone else hit it, let me add it 😀
