### ISSUE TITLE
[Feature] Improve handling of invalid browser arguments

### ISSUE THREAD

**Issue by Tyriar** [microsoft/playwright#1063]
I was having problems diagnosing why webkit would not launch, it turns out I was using this which works in puppeteer but not playwright/webkit:

```
args: [`--window-size=${width},${height}`]
```

It would be nice if this case would handles explicitly to avoid users needing to manually investigate the problem.

https://github.com/xtermjs/xterm.js/pull/2725/commits/a18bac7380d832d82aceabc63c47becee16fd9b0

Related discussion: https://github.com/microsoft/playwright/issues/1041

**Comment by pavelfeldman** [comment]
This would be great to achieve. It is a little tricky since we need to potentially list all valid Chromium, WebKit and Firefox flags. For now we assume user knows which params they pass to the engine. I'm sure that you figured the `viewport` param in the [`browser.newContext`](https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#browsernewcontextoptions). We'd like all the important testing options to end up there.

**Comment by Tyriar** [comment]
@pavelfeldman you could also check if the browser said the args were invalid in the stdout and pass that along? You'd need to hardcode and maintain the args error but that might be preferable to doing it for all cli args?

**Comment by pavelfeldman** [comment]
I don't think they yell at you for unknown args, at least Chrome did not!

**Comment by Tyriar** [comment]
@pavelfeldman my main reason for creating the issue was only because webkit yelled at me and the output was suppressed as dumpio was false that it was a pain to figure out what was going wrong. Alternatively, when the browser errors out, always show at least the last part of the browser's output?

**Comment by aslushnikov** [comment]
>  my main reason for creating the issue was only because webkit yelled at me and the output was suppressed as dumpio

@Tyriar I think this is no longer the case in 2021. I just tried with Playwright v1.9.0 and the following worked perfectly:

```js
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch({args: ['--window-size=100,100']});
    const context = await browser.newContext()
    const page = await context.newPage();
    await page.goto('https://aslushnikov.com');
    console.log(await page.evaluate(() => 7 * 8));
    await browser.close();
})();
```

> Alternatively, when the browser errors out, always show at least the last part of the browser's output?

And we also do this nowadays :) So I'll close the issue. Feel free to re-submit if I'm wrong!
