### ISSUE TITLE
[BUG] Unable to interact with visible element

### ISSUE THREAD

**Issue by Amrkamel1** [microsoft/playwright#10633]
**Context:**
- Playwright Version: 1.16.2
- Operating System: MaC
- Node.js version: 14
- Browser: CHROME
- Extra: [any specific details about your environment]

**Code Snippet**

    get editIcon() { return this.page.locator('(//li[text()="Edit"])[1]') }

    async clickOnEditIcon(feature: string) {
        await this.editIcon.click()
        return this;
    }

<img width="830" alt="Screenshot 2021-12-01 at 10 19 24" src="https://user-images.githubusercontent.com/32042806/144207054-2ce76278-4442-49d0-8fe4-6ed1e6706e39.png">

```
    locator.click: Target closed
    =========================== logs ===========================
    waiting for selector "//li[text()="Edit"] >> nth=0"
      selector resolved to hidden <li tabindex="-1" role="menuitem" class="MuiMenuItem…>…</li>
    attempting click action
      waiting for element to be visible, enabled and stable
        element is not visible - waiting...
```

**Describe the bug**

Unable to interact with an element from multiple elements, however I have defined it to be the first of the list, but still not able to interact with.

**Comment by Amrkamel1** [comment]
@pavelfeldman 

clicking on the highlighted icon should show a small menu 

<img width="1440" alt="Screenshot 2021-12-02 at 09 58 21" src="https://user-images.githubusercontent.com/32042806/144390146-596e8e60-19f0-4fbf-8e38-2f1413325f91.png">


the small menu is displayed but unable to interact with any element inside it, however, it exists in the dom 

<img width="1440" alt="Screenshot 2021-12-02 at 09 55 11" src="https://user-images.githubusercontent.com/32042806/144389924-63d86c53-246f-426d-ac94-7ee6cc31d0e9.png">

**Comment by AlexKomanov** [comment]
@Amrkamel1 
You get the violation error.
It is because you are trying to use a locator element that finds more than one matching element.
https://playwright.dev/docs/api/class-locator

**Comment by Amrkamel1** [comment]
> @Amrkamel1 
> You get the violation error.
> It is because you are trying to use a locator element that finds more than one matching element.
> https://playwright.dev/docs/api/class-locator
> 
> According to your screenshot, it finds 10 elements. 
> You should focus on one of them. 
> You can use last(), first(), nth() options.

I have used index as well already  but still unable to interact with the element.

**Comment by AlexKomanov** [comment]
@Amrkamel1 
Can you please share the trace of this scenario?

**Comment by Amrkamel1** [comment]
im really confused, now its working fine and I didn't change anything, 

get editIcon() { return this.page.locator('(//li[text()="Edit"])[1]') } is working or remove the index in xpath and use .first() is working as well

we can close this ticket maybe there is other way to reproduce this issue.
