### ISSUE TITLE
[BUG]frame click function resolve the promise when that click function finish which is too late 

### ISSUE THREAD

**Issue by songyuantai** [microsoft/playwright#10639]
**Context:**
- Playwright Version: [1.17.0]
- Operating System: [Windows]
- Node.js version: [14.17.5]
- Browser: [Chromium]
- Extra: [any specific details about your environment]

C:\Program Files\nodejs\node.exe .\app.js
(node:24236) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'click' of null
    at d:\JjPolice\JjPolice.Mei\main\mei_test\app.js:31:5
    at runNextTicks (internal/process/task_queues.js:60:5)
    at processImmediate (internal/timers.js:437:9)
    at process.callbackTrampoline (internal/async_hooks.js:131:17)
(Use `node --trace-warnings ...` to show where the warning was created)
node_modules/_signal-exit@3.0.6@signal-exit/index.js:197
(node:24236) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
node_modules/_signal-exit@3.0.6@signal-exit/index.js:197
(node:24236) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
```html
<!-- index.html -->
<iframe id="frame" src="frame.html" width="1024" height="768">
</iframe>

<!-- frame.html -->
<button class="btn btn-primary" id="btn">
    Close
</button>
    <script>
        $(function () {
            $('#btn').click(function () {
                $('#frame', parent.document).remove();
            })
        })
    </script>
```

```javascript
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({
    headless: false
  });
  const context = await browser.newContext({
    viewport: {
      width: 1920,
      height: 1080
    }
  });
  // Open new page
  const page = await context.newPage();

  await page.goto('index.html');

  await page.frame({
    name: 'frame'
  }).click('text=Close');

  await context.close();
  await browser.close();
})();
```

**Describe the bug**
the bug not appear on version 1.16

**Comment by pavelfeldman** [comment]
```html
<iframe id="frame" src="frame.html" width="1024" height="768">
</iframe>
```

I don't see the `name` argument here.

**Comment by songyuantai** [comment]
okay, i create a compelely exsample for u in there `https://github.com/songyuantai/my_playwright_test.git`
result is there
`C:\Program Files\nodejs\node.exe .\index.js
Server running at http://127.0.0.1:8000/
index.js:21
false
index.js:40
(node:20772) UnhandledPromiseRejectionWarning: frame.click: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "text=Close"
============================================================
    at d:\test\index.js:43:15
(Use `node --trace-warnings ...` to show where the warning was created)
node_modules/playwright/node_modules/signal-exit/index.js:197
(node:20772) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
node_modules/playwright/node_modules/signal-exit/index.js:197
(node:20772) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.` 

>
