### ISSUE TITLE
[BUG] Installation from package.json that contains playwright 1.16.3 version installs 1.17.0 ?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10646]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows
- Node.js version: 14.6

**Code Snippet**

```javascript
"devDependencies": {
    "@playwright/test": "^1.16.3",
    "@types/faker": "^5.5.9",
    "allure-playwright": "^2.0.0-beta.14",
    "playwright": "^1.16.3"
  },
```

**Describe the bug**

It looks like the installation from the package.json file contains a dependency version of 1.16.3 - actually triggers the installation of the 1.17.0 version:

![image](https://user-images.githubusercontent.com/52656401/144254266-d5159983-b8bd-4bef-87cd-901ae414bf9e.png)

**Comment by mxschmitt** [comment]
This is how NPM works. If you don't pin the dependencies with `=`, use `npm install` or don't have a `package-lock.json` it will use the latest version which satisfies the given range from the `package.json`.

In your scenario you might want `npm ci` instead. See here: https://docs.npmjs.com/cli/v8/commands/npm-ci/

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thank you!
