### ISSUE TITLE
[Feature] Make video rewindable in Html report

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10647]
It would be convenient to rewind video back and force to see the issue. Now it is required to download video to do so. Allure report support this, would be nice to have it in Html report.

**Comment by mxschmitt** [comment]
Seems like a duplicate of #10333. Could you please install `npm install @playwright/test@next`? Thanks!

**Comment by mxschmitt** [comment]
Closing then, since it's fixed and gets released in 1.18 next month.
