### ISSUE TITLE
[BUG] Html report is opening despite option open: "never"

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10643]
**Context:**
Playwright Version: [1.16.3]
Operating System: [Windows]
Node.js version: [v16.13.0]
Browser: [Chromium]

```javascript
import type { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
    use: {
        headless: true,
        viewport: { width: 1920, height: 1080 },
        ignoreHTTPSErrors: true,
        video: "retain-on-failure",
        trace: "retain-on-failure",
        baseURL: "http://localhost:3000/",
    },
    expect: {
        toMatchSnapshot: { threshold: 0.2 },
        timeout: 10000
    },
    testDir: "./tests",
    outputDir: "./test-results",
    retries: 0,
    reporter: [["line"], ["html", { open: "never" }]],
    workers: 1,
};
export default config;
```

**Describe the bug**

Whenever test fails playwright automatically opens html report in browser despite option  open: "never" both ih headless and headful mode.

**Comment by mxschmitt** [comment]
You need to upgrade to Playwright v1.17.0 to use this feature.

**Comment by Kremliovskyi** [comment]
@mxschmitt Thank you, it is working in 1.17.0, but 1.17.0 is bugged for now. May I ask you whether it is possible to make video in html report scrollable ? Should I report as a feature or it is impossible to do so?

**Comment by Kremliovskyi** [comment]
Will open feature request. Closing this ticket.

**Comment by ltsuda** [comment]
@Kremliovskyi do you mean select the video playback time? like selecting/clicking at the video progressbar?

If so, it's duplicated with  
https://github.com/microsoft/playwright/issues/10647#issuecomment-983727490 -> https://github.com/microsoft/playwright/issues/10333
