### ISSUE TITLE
[Question] Is there way to iterate the Locator elements?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10648]
Hi all,

I would like to iterate the Locator elements while using the 'of' operator. 
For example, if I found several same elements with a page.locator function - is there way to check each of them through the loop iteration:
```javascript
let arrayOfLocators = page.locator('element);
for (let singleLocator of arrayOfLocators) {
    const textOfElement = await singleLocator.innerText();
}
```
Seems like it is not possible with Locator elements and can be very useful!

**Comment by ltsuda** [comment]
`let arrayOfLocators = page.locator('element);` doesn't evaluate all items at this moment

Maybe you could do:

```
const arrayOfLocators = page.locator('some-selector');
const elementsCount = await arrayOfLocators.count();
let texts = [];

for (var index= 0; index < elementsCount ; index++) {
    const element = await arrayOfLocators.nth(index);
    const innerText = await element.innerText();
    texts.push(innerText);
}
```

I didn't test myself, I don't know a better way of doing this at this time.

**Comment by AlexKomanov** [comment]
@ltsuda 
I tested it in the past.
If I remember - it can be a little problem with this option due to the asynchronous methods of Playwright vs synchronous of the for loop.

**Comment by pavelfeldman** [comment]
If your list is static, you can do the iteration as suggested above. If your list is dynamic, depending on your expectations, your could do locator.evaluateAll and atomically process all elements on the page side.

**Comment by AlexKomanov** [comment]
@pavelfeldman 
But in case of the locator.evaluateAll - each element will not be of a Locator type. Is any way to iterate with every Locator element in the array?

**Comment by pavelfeldman** [comment]
> But in case of the locator.evaluateAll - each element will not be of a Locator type. Is any way to iterate with every Locator element in the array?

It would not fit the locators ideology. Locator is 'a way to locate an element'. Array of those would be artificial. evaluateAll would process DOM nodes, which is very powerful.

**Comment by AlexKomanov** [comment]
Thanks @pavelfeldman !

**Comment by DanielStoica85** [comment]
I just encountered the same problem. I have a list of checkboxes and I need to click on all of them. Depending on some factors, the list count can differ, but the locator will be the same for all checkboxes. How do I iterate over them so I can click each one?

**Comment by 0xIslamTaha** [comment]
@DanielStoica85 
I managed to solve it with the following code 
```ts
test('user can check multiple radio ', async ({ page }) => {
  const radios = await page.locator('[type="radio"]');
  const count = await radios.count();
  for (let i = 0; i < count; i++) {
    await radios.nth(i).click();
  }
})
```

**Comment by dhochman-kroger** [comment]
When you write a test for multiple elements, I recommend that you also verify that at least 1 element was selected, just in case the selector was misspelled or the page structure changed.  Otherwise, the test will pass because it's not testing anything. For example, between setting `count` and the `for` loop, add:
```javascript
expect(count).toBeGreaterThan(0); // Verify something was selected.
```

**Comment by DetachHead** [comment]
you could make a generator
```ts
async function* iterateLocator(locator: Locator): AsyncGenerator<Locator> {
    for (let index= 0; index < await locator.count(); index++) {
        yield locator.nth(index)
    }
}
```

now you can iterate over them with a `for await` loop:
```ts
for await (const locator of iterateLocator(page.locator('some-selector'))) {
    console.log(locator)
}
```

**Comment by danielrob** [comment]
Another option - more repetition, but less setup. isVisible considers zero results to be false. 

```ts
while (await page.isVisible('some-selector')) {
  const locator = await page.locator('some-selector')
  console.log(locator)
} 
```

**Comment by eikowagenknecht** [comment]
As of [Playwright v1.29.0](https://github.com/microsoft/playwright/releases/tag/v1.29.0), this is now supported natively with the [new .all() method](https://playwright.dev/docs/api/class-locator#locator-all).

**Comment by abalbastrem** [comment]
Not even all() is saving me.

`const highlightedTextElements = await page.locator('span[style="background-color: rgba(0, 90, 80, 0.35);"] > span').all();
        var highlightedTextArray = [];
        for (const highlightedTextElement of highlightedTextElements) {
            hlText = await highlightedTextElement.innerText();
            console.log(hlText);
            await highlightedTextElement.click({modifiers:['Alt']});
        }`

It only gets the innerText and clicks on the first element. Then starts infinitely looping without doing anything aside from scrolling the webpage downwards. Same as it happened with locator and a for i loop with nth(i). However, the scrolling suggests it's trying to do something, just not succeeding.

**Comment by co510** [comment]
> Not even all() is saving me.
> 
> ```
> const highlightedTextElements = await page.locator('span[style="background-color: rgba(0, 90, 80, 0.35);"] > span').all();
> var highlightedTextArray = [];
> for await (const highlightedTextElement of highlightedTextElements) {
>     hlText = await highlightedTextElement.innerText();
>     console.log(hlText);
>     await highlightedTextElement.click({modifiers:['Alt']});
> }
> ```
> 
> It only gets the innerText and clicks on the first element. Then starts infinitely looping without doing anything aside from wiggling the webpage up and down. Putting more or fewer awaits does not help either. Same as it happened with locator and a for i loop with nth(i). However, the wiggling suggests it's looping over the same element over and over again, but doing nothing of substance after the very first iteration.
> 
> UPDATE: Turns out if I comment out the last line about clicking, it works perfectly. Somehow click, even without a modifier, is messing everything up. I DO need to click though.


@abalbastrem could you try writing it like this?  I'm not familiar with modifiers but this is generally how I setup these kind of loops.
`
const highlightedTextElements = page.locator('span[style="background-color: rgba(0, 90, 80, 0.35);"] > span');
await expect(highlightedTextElements.first()).toBeVisible();
let highlightedTextArray = [];

for (const highlightedTextElement of await highlightedTextElements.all()) {
    hlText = await highlightedTextElement.innerText();
    console.log(hlText);
    await highlightedTextElement.click({modifiers:['Alt']});
}
`

**Comment by rejectozaur** [comment]
And what would you recommend for a case when all the checkboxes have their unique data-test-ids, but you want to click through collections of them? My collections are diviced to: positiveValues, negativeValues, contradictoryValues, since it's all about filling a Tax related document.

Here's my case with PageObjects:
`import { Page, Locator, expect } from '@playwright/test'

export class TaxFillPage{
    readonly page: Page;                                      

    readonly oneTwelveth: Locator;                                          
    readonly oneTwentyFourth: Locator;                                     
    readonly oneThirtySixth: Locator;   
                                        
    readonly employeeRevenueCostsWithdrawFirst: Locator;   
                
    ...dozens of such...
    
     constructor(page: Page) {
           this.page = page;
    
            this.oneTwelveth = page.getByTestId('oneTwelveth');               
            this.oneTwentyFourth = page.getByTestId('OneTwentyfourth');        
            this.oneThirtySixth = page.getByTestId('OneThirtysixth');         
            this.employeeRevenueCostsWithdrawFirst = page.getByTestId(      
            'EmployeeRevenueCostsWithdraw >> nth=0',
        );
    
    async employeeChoosesDesiredOptions(optionsList) {
        const positiveOptionsList = [
            this.oneTwelveth,
            this.oneTwentyFourth,
            etc...
       ]
       
         const withdrawalOptionsList = [
            this.employeeRevenueCostsWithdrawFirst,
            etc.
       ]
       
       optionsList == 'positiveValues'
            ? optionsList = positiveOptionsList
            : optionsList == 'withdrawalValues' ? optionsList = withdrawalOptionsList
            : optionsList == 'selfContradictoryValues' ? optionsList = selfContradictoryOptionsList
            : "Please choose one of the valid arguments' names";

        const optionsListLength = optionsList.length;
        for (let el = 0; el < optionsListLength; el++) {
            await this.page.check(optionsListLength[el]); // here I've got a problem, because check expects a string, and it gets and object, when you want to utilise page objects
            await expect(this.page.isChecked(optionsListLength[el])).toBeTruthy(); 
        }`
        
       Any recommendations?

**Comment by levickane** [comment]
this was my solution after following one of the solutions from above. I'm using Bootstrap and have a `form-select`.
It iterates through each selection and has some clicks for each index.

`const arrayOfLocators = await page.getByTestId("neighborhoodDropdown")
  const elementsCount = await page.getByTestId("option").count()

  for (let index = 2; index < elementsCount; index++) {
    await arrayOfLocators.selectOption({ index: index })
    await page.getByRole("button", { name: "Condo" }).click()
    await page.waitForTimeout(800)
    await page.getByRole("button", { name: "Single Family (Detached)" }).click()
    await page.waitForTimeout(800)
    await page.getByRole("button", { name: "Multi-Family" }).click()
    await page.waitForTimeout(800)
    }`
    
    I hope this helps somebody!

**Comment by AlexKomanov** [comment]
Thanks. But you have the locator.all() function that was implemented in one of the latest versions.

**Comment by skumar09** [comment]
```
// get all the elements using all() method
const elements = await page.locator('.className').all();

// then uses Promise.all() to create a new Promise that resolves to an array of resolved promises for each element in the
// elements Array. The .map() function iterates over the elements array and for each element, it returns a promise 
// that resolves to the element.
const elementsArray = await Promise.all(elements.map(async (el) => el));
        for (const ele of elementsArray ) {
          const ele1= await ele .locator('.classname');
          const ele2= await ele .locator('.classname');
         ....
        ...

        }
```

**Comment by rajaniusaindia** [comment]
Hi I can get to the href value easily using the following code written in VUE:
const rows = await page.locator('//nav/div/ul/li/a');
    const count = await rows.count();
    console.log('Total number of header links', count);

    for (let i = 0; i < count; ++i) {
      const hrefs = await rows.nth(i).getAttribute('href');
      console.log(i + 1, ':', hrefs);
    }

But how do I get the same thing done in RECT with using GetByRole?
const navigation = page.getByRole('navigation', {
      name: /navigation top/i,
    });
const homelink = navigation.getByRole('link', { name: /w3 home/i });
const h = homelink.getAttribute('href');

//Does not get me the href attribute value.

**Comment by rajaniusaindia** [comment]
This is my HTML that I am getting as part of my Locator when I try to do
const innerHTML = await navigation.innerHTML();

TOP Navigation
innerHTML Navigation =  

<div class="ds-nav-container”>
<ul class="ds-nav-list ds-nav-top-level">
<li class="ds-nav-item ds-selected”>

<a aria-current="page" href="#/" class="router-link-active router-link-exact-active ds-nav-link" title="w3 Home" id="nav_home" role="link">Home</a>

<!— Child navigation --></li>
<li class="ds-nav-item”>
<a href="#/people" class="ds-nav-link" title="People" id="nav_people" role="link">People</a>

<!— Child navigation --></li>
<li class="ds-nav-item"><a href="#/news" class="ds-nav-link" title="News" id="tourStep3" role="link">News</a>
</li>

<li class="ds-nav-item">
<a href="#/apps/category/recommended" class="ds-nav-link" title="Apps" id="nav_apps" role="link">Apps</a>
</li>

<li class="ds-nav-item”>
<a href="#/support" class="ds-nav-link" title="IT Support" id="nav_support" role="link">IT Support</a>
</li>

**Comment by wuqianrui** [comment]
This is my solution, and I use node 

It took me a long time to write it.
This is an example of getting multiple <a> dom 's href attr .

```javascript
            var  matchSelectorTag = "#Profile-posts > a"
            var aDoms = await page.locator(matchSelectorTag);
            var linkUrlCount = await page.locator(matchSelectorTag).count();
            var linkUrls = await Promise.all( [...Array(linkUrlCount).keys()].map(async (count)=>{ var aDom = await aDoms.nth(count); return await aDom.getAttribute('href'); }) );
            console.log(linkUrls);
```

**Comment by carcigenicate** [comment]
The problem with `.all()` is, it's live. If I want to get every unchecked checkbox and then check them all, using `all()` will cause every second to be checked. I'm assuming it's because it's doing `.nth(i)` internally, and once it checks the first checkbox at index `0`, that box no longer matches the locator, so `.nth(1)` matches the second currently unchecked element instead of the next one.

I instead needed to use `elementHandles` instead to "freeze" the list to iterate over prior to iterating:

```typescript
const handles = await disabledToggleLocators.elementHandles();

for (const disabledToggle of handles) {
  await disabledToggle.click();
}
```

And, I also added a wait before this to ensure that all the elements are loaded first.

**Comment by FranciscoG** [comment]
I've tried most of these solutions and the only one that worked from the answers above was the `elementHandles()` solution, but then the documentation discourages it. So I figured out another way.  

```js
while ((await page.locator('.your-selector')).count() > 0) { 
  await page.locator('.your-selector').first().click()
}
```

This worked for me and solved the dynamic issue if you have less of `.your-selector` elements after each click

**Comment by fipy-immediate** [comment]
https://jqcode.space/questions/modify-the-css-class-dynamically-by-clicking-a-button-using-class-names-stored-in-an-array See this answer for details
