### ISSUE TITLE
[BUG] setDefaultNavigationTimeout is overriden by globalTimeout

### ISSUE THREAD

**Issue by CapsE** [microsoft/playwright#10645]
**Context:**
## System:
 - OS: Linux 5.11 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 648.62 MB / 15.32 GB
 - Container: Yes
## Binaries:
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.0/bin/yarn
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm

playwright.config.js
```javascript
const config = {
    ignoreHTTPSErrors: true,
    timeout: 2000,
    navigationTimeout: 30000,
    use: {
        browserName: "firefox",
        screenshot: 'only-on-failure',
    },
};

module.exports = config;
```

timeout-test.spec.js
```javascript
const { test } = require('@playwright/test');

test('test', async ({ page }) => {
    page.setDefaultNavigationTimeout(30000);
    page.setDefaultTimeout(2000);

    await page.goto(`http://localhost:3000/timeout`);
});
```

express-server.js
```javascript
app.get('/timeout', (req, res) => {
    setTimeout(() => {
        res.send("Timeout");
    }, 60000);
});
```
The test above fails after which ever timeout is shorter. I assumed it would fail after the defaultNavigationTimeout. I have an application where I'm quite certain that if a selector hasn't shown up after 2 seconds it won't show up ever. This is true for everything except intial page loading. It would be great to allow a bigger timeout for page loading and early fails while "clicking through" the already loaded page. After some testing I found that removing timeout from playwright.config.js resolves this issue.

**Comment by pavelfeldman** [comment]
You specified timeout: 2000 in your config. If the test is taking more than 2 seconds, it is now terminated, no matter what you do inside that test.

**Comment by metalcamp** [comment]
What if you set

```
test.setTimeout(60000)
```

in the test itself? Would that solve the issue?

**Comment by pavelfeldman** [comment]
There already are two suggestions, closing this as a part of triage.
