### ISSUE TITLE
[BUG] JavaScript Alert is getting closed while debugger is open

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#10657]
**Context:**
- Playwright Version: 1.15
- Operating System: Mac
- Node.js version: 16.11.1
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

https://www.loom.com/share/979a5e034104438cabbde21f2b4dedad

Loom video attached

**Describe the bug**

_**2 Issues can be observed here**_

1) A new chrome window is getting opened while clicking on debugger 

2) Js Alert for warning message is not getting opened properly and is getting closed.

**Comment by Nav-2d** [comment]
First one is similar to this: https://github.com/microsoft/playwright/issues/9434

**Comment by jithinjosejacob** [comment]
See video while doing the same actions as a user 
https://www.loom.com/share/34ec3c2e5667488eb08c79aa41162f7c

**Comment by dgozman** [comment]
[Here is a guide](https://playwright.dev/docs/dialogs) about handling dialogs. I'd suggest to record your actions with [Test Generator](https://playwright.dev/docs/codegen) to see an example of how to handle dialogs.

> Js Alert for warning message is not getting opened properly and is getting closed.

This is intended behavior. If you are not handling the dialog in your test, Playwright auto-dismisses all dialogs.
