### ISSUE TITLE
[BUG] https://playwright.dev/ is defaulting to an old version

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#10668]
**Context:**
- Chrome Latest Stable, macOS

**Describe the bug**

https://playwright.dev/ is defaulting to an old version (1.15) (unless I manually change it). If I open an incognito tab, it is correctly pointed at 1.17 by default. Looks like there's some "sticky" state that I would not expect. See screenshots:

<img width="854" alt="Screen Shot 2021-12-01 at 10 40 27 PM" src="https://user-images.githubusercontent.com/11915034/144371495-ef5e7a91-4c33-4ed3-ba5f-4e10c8453477.png">

**Comment by rwoll** [comment]
The top photo is default chrome user profile, the second is incognito window.

**Comment by mxschmitt** [comment]
Yeah docusaurus saves which version you selected the last time, see here when it got introduced: https://github.com/facebook/docusaurus/pull/3543

**Comment by rwoll** [comment]
Feel free to close. Upon further thinking/use, it seems like it's a feature. (Especially since it looks like it has a giant yellow box telling you you can jump to latest that I somehow missed in that moment… 🤦 )
