### ISSUE TITLE
[BUG/REGRESSION]: visible/hidden chromium

### ISSUE THREAD

**Issue by yavorski** [microsoft/playwright#10674]
**Context:**
- Playwright Version: 1.17.1
- Operating System: All
- Node.js version: 16.13.1 LTS
- Browser: Chromium, Firefox

----

Hi, 

I think `getBoundingClientRect` api received some changes in the recent 97/98 versions of chromium.
Here is a failing test in chromium, but passing in firefox, it was also working fine with chromium 96.

```js
import { test, expect } from '@playwright/test';

test.describe('hidden/visible in chromium/firefox', () => {
  test('hidden/visible', async ({ page }) => {
    await page.goto('https://example.com');
    await page.waitForLoadState('domcontentloaded');

    expect (await page.locator('body > div > h1').innerText()).toBe('Example Domain');

    await page.locator('body > div').evaluate(div => {
      const html = `
        <details>
          <summary>click to open</summary>
          <ul>
            <li>hidden item 1</li>
            <li>hidden item 2</li>
            <li>hidden item 3</li>
          </ul
        </details>
      `;
      div.innerHTML = html;
    });

    await expect(page.locator('details > ul')).toBeHidden();
  });
});
```

Save the file as `test.js` and run with: 

* `npx playwright test --browser firefox test.js`
* `npx playwright test --browser chromium test.js`

**Comment by pavelfeldman** [comment]
Looks like a Chromium bug indeed:

data:text/html,<details><summary>click to open</summary><ul><li>hidden item 1</li><li>hidden item 2</li><li>hidden item 3</li></ul></details>

gives non-0 $0.getBoundingClientRect() on ul.

**Comment by yavorski** [comment]
Hi, 10x for the applied patch. Linking the issue in chromium repo here for visibility and further reference https://bugs.chromium.org/p/chromium/issues/detail?id=1276028
