### ISSUE TITLE
[BUG] Test Reporter API: Property 'suite' does not exist on type 'TestCase'

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#10677]
**Context:**
- Playwright Version: v1.17.1
- Operating System: Linux
- Node.js version: v14.17.6
- Browser: N/A
- Extra: GitHub Codespaces

**Code Snippet**

```ts
import { TestCase } from "@playwright/test/reporter";

declare const c: TestCase;
console.log(c.suite);
```

**Describe the bug**

The [Test Reporter API documentation states that a `TestCase` has a `suite` property](https://playwright.dev/docs/api/class-testcase#test-case-suite)

![image](https://user-images.githubusercontent.com/193136/144475461-0daf6cc8-1fa6-4ab2-a434-59d5165cc93f.png)

However, when I try to use it, I get an error: `Property 'suite' does not exist on type 'TestCase'.ts(2339)`

![image](https://user-images.githubusercontent.com/193136/144475541-5703a841-b1e8-46cb-b8cf-8247c823eb2f.png)

Workaround: Access the suite via `c.parent`, but it is an undocumented property.

**Comment by dgozman** [comment]
@dtinth There is a mismatch indeed. It should be `TestCase.parent` - I'll update the docs.
