### ISSUE TITLE
[BUG] unable to create LocatorAssertions (missing class: "com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat")

### ISSUE THREAD

**Issue by emakaay** [microsoft/playwright#10675]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 8 64 bit
- Node.js version: 14
- Browser: included in playwright
- Extra: na

```javascript
na
```

**Describe the bug**
I'm trying to use LocatorAssertions (as descibed on https://playwright.dev/java/docs/api/class-locatorassertions)
But i'm unable to find the required class "com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat"

Is there a reason for this. I use the following maven dependency:
<dependency>
    <groupId>com.microsoft.playwright</groupId>
    <artifactId>playwright</artifactId>
    <version>1.17.1</version>
</dependency>

**Comment by yury-s** [comment]
> Is there a reason for this. I use the following maven dependency:

As described [here](https://playwright.dev/java/docs/api/class-playwrightassertions#playwright-assertions-assert-that-locator) you need to add 
```xml
<dependency>
  <groupId>com.microsoft.playwright</groupId>
  <artifactId>assertions</artifactId>
  <version>1.17.0</version>
</dependency>
```
The assertions are distributed in its own module.

**Comment by emakaay** [comment]
I missed that completely.

Thanks for that
