### ISSUE TITLE
[Feature] Allow to evaluate scripts on frameLocator

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#10683]
Let us know what functionality you'd like to see in Playwright and what your use case is.
We use PW to test MFEs that comes from SystemJS importmaps. There is a possibility to override importmap and serve local app as if it was deployed to server. So before test I need to apply the override which looks like the following
```typescript
window.importMapOverrides.addOverride(app, url);
```
So I don't need an element for that, just a frame.
Currently I do something like
```typescript
const frameLocator = page.frameLocator('some selector');

frameLocator.locator('body').evaluate(() => {})
```

Would like to do something like
```typescript
const frameLocator = page.frameLocator('some selector');

frameLocator.evaluate(() => {})
```

Do you think others might benefit from this as well?
Probably...

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
