### ISSUE TITLE
[BUG] Pressing F12 will cause the browser to close, when the browser is started with the `--single-process` parameter

### ISSUE THREAD

**Issue by wangzyh** [microsoft/playwright#10692]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Windows
- Node.js version: v14.18.1
- Browser: All

Startup parameters: --single-process

**Comment by pavelfeldman** [comment]
--single-process is not guaranteed to work, even eithout Playwright, it clearly states so in the browser UI when you use it.
