### ISSUE TITLE
[BUG]  browserType.launch: No executable path is specified. Pass "executablePath" option directly.

### ISSUE THREAD

**Issue by Yurii397** [microsoft/playwright#10693]
**Context:**
- Playwright Version: 1.16.3
- Operating System:  macOS Monterey Version 12.0.1 (21A559)
- Node.js version: 16.2.0
- Browser: Chromium,  but the same with others - Firefox, WebKit
- Extra:  uisng  "jest-playwright-preset": "1.6.0",  processor Intel, Comand Line Tool: Verion 13.1.0.0.1.1633545042,
Chrome Version 96.0.4664.55 (Official Build) (x86_64)

Error when running tests
![image](https://user-images.githubusercontent.com/46851143/144569015-562a6477-ea70-4e40-851b-cc6c85e236ab.png)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
  browser = await chromium.launch({
    headless: true,
    slowMo: 50,
    devtools: false,
  })
```

**Describe the bug**

After upgrading the macOS from Big Sur to Monterey I got this issue,  tried to pass 'executablePath' into lunch options but nothing helped 
https://user-images.githubusercontent.com/46851143/144419366-4a333e96-eacf-41bb-bd1d-c6d93c435ad3.png

Other teammates who work in the same codebase with me but have macOS version, not Monterey still run tests well. 

Also tried to upgrade Playwright to "1.18.0-alpha-dec-3-2021" but no luck

**Comment by Captain1653** [comment]
Hi @Yurii397 !

I had the same problem. I have the same operation system. Did you try version `1.17.1` ? It was released yesterday. It solved my problem.

Kind regards

**Comment by Yurii397** [comment]
@Captain1653 thanks for  the suggestion, just tried  Playwright `1.17.1` but didn't help 

I'm using following dependencies 
![image](https://user-images.githubusercontent.com/46851143/144589647-24a60364-3b1e-4a02-bc06-4c2f4b9af77d.png)

if that helps somehow

**Comment by Yurii397** [comment]
@Captain1653 have found solution - "jest-playwright-preset" needed to be updated to "1.7.0",

**Comment by Yurii397** [comment]
will close issue if you don't mind
