### ISSUE TITLE
How to intercept response for file upload via filechooser/

### ISSUE THREAD

**Issue by indapublic** [microsoft/playwright#10699]
Website uploads file immediately on file change. I want to intercept JSON response of this upload. Is it possible?

```
page.on("filechooser", (fileChooser: FileChooser) => {
	fileChooser.setFiles(["/Volumes/Data/Dropbox/Public/111.jpg"]);
});
await page.click('input[name="up[]"]');
```

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/network#modify-responses

**Comment by indapublic** [comment]
Thanks @pavelfeldman for your quick answer.

Yes, I'm tried with

```
await this._page.route("**/*", async (route) => {
	console.log(route.request().url());
	route.continue();
});

this._page.on("filechooser", (fileChooser: FileChooser) => {
	fileChooser.setFiles(["/Volumes/Data/Dropbox/Public/111.jpg"]);
});

await this._page.click('input[name="up[]"]');
```

But request with uploading is not catched. This upload is issued by JS (via AJAX), can be a reason?

**Comment by dgozman** [comment]
@indapublic This is not expected. If you could share a repro with us, we'll investigate.

**Comment by indapublic** [comment]
Thanks @dgozman Found that library works as expected on clean demo. So probably problem inside my project somewhere. Closing. Thanks again @dgozman and @pavelfeldman

**Comment by indapublic** [comment]
One question related to this subject, so I will ask in closed thread.

From [here](https://playwright.dev/docs/next/network/#modify-responses)

```const response = await page.request.fetch(route.request());```

How it should be modified for multipart data? Or probably I can get json of complete response already?

**Comment by indapublic** [comment]
Ok, solved with 

```
this._page.on("response", async (response) => {
	if ("url what i needed" === response.url()) {
		console.log(await response.json());
	}
});
```
