### ISSUE TITLE
[Feature] Allow CDP connection with custom `downloadsPath`

### ISSUE THREAD

**Issue by tmarenko** [microsoft/playwright#10700]
Currently when I'm trying to connect browser over CDP, Playwright always uses temp folder:
https://github.com/microsoft/playwright/blob/f802c27d0983ed40a0d678a61897e85c872bd076/packages/playwright-core/src/server/chromium/chromium.ts#L66
https://github.com/microsoft/playwright/blob/f802c27d0983ed40a0d678a61897e85c872bd076/packages/playwright-core/src/server/chromium/chromium.ts#L93

I wish to pass custom folder for `downloadsPath` in order to achieve access for downloaded files from Selenoid container. 
This is available only if download path is equals to `"/home/selenium/Downloads"` ([docs](https://aerokube.com/selenoid/latest/#_downloading_files_in_different_browsers)) which I can't set in Playwright right now.

Additionally, it would be nice if Playwright could store UUID of saved file, same as `suggestedFilename` property.
That would help to find a particular file via Selenoid API ([docs](https://aerokube.com/selenoid/latest/#_accessing_files_downloaded_with_browser))

**Comment by pavelfeldman** [comment]
This is unlikely to be addressed because only the launcher of the browser has control over the download folder for security reason. Raise this against Selenoid and they can come to us for options.

**Comment by tmarenko** [comment]
I'm not sure that I'm understanding correctly the security reason.
If I hardcode the path to:
```javascript
    const artifactsDir = '/home/selenium/Downloads';
```
then it works and downloads files as intended.

I've tried to pass `Browser.setDownloadBehavior` at launch and after launch with custom `downloadPath` but seems Playwright always uses temp folder for downloads over CDP:
https://github.com/microsoft/playwright/blob/f802c27d0983ed40a0d678a61897e85c872bd076/packages/playwright-core/src/server/browser.ts#L84

I'm using Python's package of Playwright so I can't easily edit source code of the problem because it's on JS server side.
Any chances that feature could be done with new optional paramater or you still think that it's Selenoid's issue?

**Comment by tmarenko** [comment]
I've made these example commits to show what I've meant:
https://github.com/tmarenko/playwright-python/commit/0743e8eec52b35e0aa263c40f603e3568268d604
https://github.com/tmarenko/playwright/commit/297d4c61070a70773c20d31d8f36dc9e9f7ee6da

With these kind of changes I can easily gain access to downloaded file:
```python
connection = playwright.chromium.connect_over_cdp(endpoint_url=f'ws://{SELENOID}/devtools/{browser.session_id}',
                                                  downloads_path="/home/selenium/Downloads")
page = connection.new_page(accept_downloads=True)
with page.expect_download() as download:
    page.click_on(download_locator)

with open(download.value.uuid, 'wb') as download_file:
    response = requests.get(f"http://{SELENOID}/download/{browser.session_id}/{download.value.uuid}")
    download_file.write(response.content)
```

**Comment by tmarenko** [comment]
@pavelfeldman 
sorry to bothering you but could you review my last two comments and reply what you think about it?
I'm really struggling to understand the security reason behind the Selenoid itself (if it has such).

**Comment by tmarenko** [comment]
@pavelfeldman
any chances that you could review this again?
