### ISSUE TITLE
[BUG] Experimental React Selectors doesn't work on react apps in Iframe.

### ISSUE THREAD

**Issue by akgupta0777** [microsoft/playwright#10718]
**Context:**
- Playwright Version: **1.16.3**
- Operating System: [e.g. Windows, Linux or Mac] **Windows**
- Node.js version: [e.g. 12.22, 14.6] **16.13.0**
- Browser: [e.g. All, Chromium, Firefox, WebKit] **Chromium**
- Extra: [any specific details about your environment] 

**Code Snippet**

```javascript
test.describe('Clicking react components', () => {
  let page, frameElementHandle, frame;
  test.beforeAll(async ({browser}) => {
    page = await browser.newPage();
    await page.goto('http://localhost:8080/', {waitUntil: 'domcontentloaded'});
    await page.waitForSelector('iframe#target');
    frameElementHandle = await page.$('#target');
    frame = await frameElementHandle.contentFrame();
  });
  test('click on component named DeepHooks', async () => {
    await frame.click('_react=DeepHooks');
    expect(true).toEqual(true); // Intentional for passing test
  });
})
```

**Describe the bug**

It can't find the component with the selector. Timeout Error of 30 seconds showed up 
```
 Timeout of 30000ms exceeded.

    page.click: Target closed
    =========================== logs ===========================
    waiting for selector "_react=DeepHooks"
    ============================================================
```

Also, the source is not minified.

I am totally using react selectors for the first time so sorry if I did something wrong.

Thank You

**Comment by dgozman** [comment]
@akgupta0777 Your code looks fine. If you could provide a repro scenario for us to run locally, we might be able to help.

**Comment by akgupta0777** [comment]
@dgozman Thanks for looking into this. Soon i will come with a repro.

**Comment by dgozman** [comment]
@akgupta0777 Any chance for a repro?

**Comment by akgupta0777** [comment]
Sorry for keeping you waiting for so long. Actually I am stuck in work commitments. 
Can you wait for 2-3 days more for a repro.

For context I am writing tests for [React-devtools-shell package](https://github.com/facebook/react/tree/main/packages/react-devtools-shell) . You can write a small test for this package with experimental react selectors and it will fail because all the apps in package renders on iframe.

**Comment by mxschmitt** [comment]
Closing for now since we don't have a repro. Please create a new issue if you still encounter issues.
