### ISSUE TITLE
[Question]How to switch tabs using playwright 

### ISSUE THREAD

**Issue by AmanDaharwal** [microsoft/playwright#10714]
Scenario: Script is clicking 'Submit Request' button on Request page, on click, user is navigated to next page ( aka Confirmation page) and app will download PDF file and open in new tab automatically( as playwright browser pop blocker is on by default)

So to execute further verification steps in Confirmation page, need to switch browser tab back to Tab1( where confirmation page is opened). As, currently the pdf tab is opened, script is unable to perform the further verification steps on Confirmation page.

Work-Around for this can be : to disable the pop up blocker settings while launching browser( if possible with playwright)

**Comment by s3naid** [comment]
Use `page.on('popup')` to capture Request page:

```
const [popup] = await Promise.all([
  page.waitForEvent('popup'),
  page.evaluate(() => window.open('https://example.com')),
]);
```
Also `browserContext.pages()` will return all pages as array.
You can than use this page as You want

**Comment by AmanDaharwal** [comment]
Thanks, this workaround works

**Comment by dgozman** [comment]
@AmanDaharwal Take a look at documentation as well: https://playwright.dev/docs/pages/#multiple-pages.
