### ISSUE TITLE
[Question] Is this a resource utilization issue?

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#10717]
At my work we are using playwright at scale to perform automation/scraping workloads, and occasionally we run into a bunch of errors like this:

`browserContext.newPage: Browser closed. ==================== Browser output: ==================== <launching> /opt/google/chrome/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --auto-open-devtools-for-tabs --no-sandbox --proxy-server=http://per-context --no-sandbox --disable-setuid-sandbox --ignore-certificate-errors --disable-infobars --disable-blink-features=AutomationControlled --start-maximized --disable-dev-shm-usage --disk-cache-size=1 --disable-gpu --user-data-dir=/tmp/playwright_chromiumdev_profile-tnAWf2 --remote-debugging-pipe --no-startup-window <launched> pid=1276 [pid=1276][err] [1276:1380:1204/100632.160616:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1276:1380:1204/100632.160816:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1276:1380:1204/100632.183342:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1276:1380:1204/100632.183396:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1483:1483:1204/100632.190001:ERROR:gpu_init.cc(453)] Passthrough is not supported, GL is swiftshader, ANGLE is [pid=1276][err] [1276:1535:1204/100632.221263:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files [pid=1276][err] [1276:1535:1204/100632.221624:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files [pid=1276][err] [1276:1535:1204/100632.222108:ERROR:object_proxy.cc(642)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files [pid=1276][err] [1276:1380:1204/100644.652437:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1276:1380:1204/100644.652513:ERROR:bus.cc(392)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") [pid=1276][err] [1276:1480:1204/100644.693764:ERROR:zygote_communication_linux.cc(143)] Did not receive ping from zygote child [pid=1276][err] [1317:1317:1204/100644.693755:ERROR:zygote_linux.cc(607)] Zygote could not fork: process_type renderer numfds 5 child_pid -1 [pid=1276][err] [1317:1317:1204/100644.694163:ERROR:zygote_linux.cc(271)] Unexpected real PID message from browser [pid=1276][err] [6827:6827:1204/100644.694134:ERROR:platform_thread_posix.cc(147)] pthread_create: Resource temporarily unavailable (11) [pid=1276][err] [1204/100644.705004:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2) [pid=1276][err] [1204/100644.705112:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2) [pid=1276][err] [1276:1480:1204/100644.708202:ERROR:zygote_communication_linux.cc(143)] Did not receive ping from zygote child [pid=1276][err] [1317:1317:1204/100644.708202:ERROR:zygote_linux.cc(607)] Zygote could not fork: process_type renderer numfds 5 child_pid -1 [pid=1276][err] [1276:1276:1204/100644.708362:ERROR:platform_thread_posix.cc(147)] pthread_create: Resource temporarily unavailable (11) [pid=1276][err] [1317:1317:1204/100644.708396:ERROR:zygote_linux.cc(271)] Unexpected real PID message from browser [pid=1276][err] [1204/100644.789674:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq: No such file or directory (2) [pid=1276][err] [1204/100644.789707:ERROR:file_io_posix.cc(144)] open /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq: No such file or directory (2) [pid=1276] <process did exit: exitCode=null, signal=SIGSEGV> [pid=1276] starting temporary directories cleanup`

Everything up to ` [pid=1276][err] [1276:1480:1204/100644.693764:ERROR:zygote_communication_linux.cc(143)] Did not receive ping from zygote child` is stuff I usually see when launching chrome on the system. But the rest seems to me like an indication that the system is seeing a sudden resource utilization spike, probably caused by a ton of chromes being launched at the same time. Is that a fair assessment?

**Comment by dgozman** [comment]
@nicoandmee Yep, that sounds fair. The following line suggests that browser wasn't able to create a new process for itself:

```log
[1317:1317:1204/100644.693755:ERROR:zygote_linux.cc(607)] Zygote could not fork: process_type renderer numfds 5 child_pid -1
```

Perhaps you have leftover browser contexts and pages that you did not close. If that's not the case, I'd suggest to restart the browser once in a while.
