### ISSUE TITLE
[BUG] Trace Viewer cannot view the traces generated by flaky test

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#10713]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 14.18.0
- Browser: Chromium

**Describe the bug**
I have some flaky test, which restarts browser two times. First run generates a trace that Trace Viewer cannot open, and shows 

```
Could not load trace from .\trace.zip. Make sure a valid Playwright Trace is accessible over this url.
```
Here is the trace generated by PW [trace.zip](https://github.com/microsoft/playwright/files/7653725/trace.zip).

**Comment by dgozman** [comment]
@creage This trace is indeed corrupted. Would it be possible to share the repro config/test? That would help us find the issue.

**Comment by creage** [comment]
I've tried to create one, but the trace corruption appears very randomly. I couldn't get a stable corruption :)

What I also notice, is that  some of traces are stored in wrong folders. Like a trace of test A gets stored in folder of trace of test B - which is even more confusing...

**Comment by mxschmitt** [comment]
Closing since we can't act on this without a repro. Please create a new issue if you have a repro, thanks!
