### ISSUE TITLE
[BUG] WebKit: new BrowserContexts share same proxy

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#10728]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 14.18.2
- Browser: WebKit

**Describe the bug**
Starting a new **WebKit** BrowserContext should be isolated from the rest of contexts, **same as it does for Chromium and Firefox**. 

Currently it is not in WebKit, but it is in Chromium and Firefox.

1. Launch Webkit
2. Create new context **A**, with proxy server set to `PROXY_A`
3. Create another context **B**, with proxy server set to `PROXY_B`
4. Switch to context **A**, run a request.

Expected: Requests should go through `PROXY_A`
Actual: Requests for both of contexts run through `PROXY_B`

**Comment by dgozman** [comment]
@yury-s Could you please take a look?

**Comment by yury-s** [comment]
@creage can you upload a repro script?

**Comment by creage** [comment]
Well, it would be hard to provide a short version of it, I'll try to create a repo with example code.

P.S. We were using `jest-playwright-preset` before, and this runner didn't had that issue. Once we switched to Playwright Test - Webkit started to share the proxies between contexts - the last one used wins for all of active contexts. And, what I can see from `jest-playwright-preset`'s code, is that it launches a new browser every time we ask it for a new context. Does that ring a bell?

**Comment by creage** [comment]
@yury-s I can confirm now, that `broswer = webkit.launch()` before doing `broswer.newContext()` solves the isolation issue.

```js
const proxy = await AppComponent.startNewNtlmProxyForUser(user);

if ((browser as unknown as Record<string, unknown>)._name === 'webkit') {
    browser = await webkit.launch();
}

const context = await browser.newContext({
    ...contextOptions,
    proxy: {
        server: proxy.address
    }
});

context.on('close', async () => proxy.stop());
```

**Comment by yury-s** [comment]
If you launch a new browser instance they proxy settings will certainly be isolated, you can use i as a workaround for now. The proxy settings are supposed to be isolated between the browser contexts though. There may be a bug/limitation in our windows implementation, I'll need to boot into Windows to check.
