### ISSUE TITLE
[Question] connectOverCDP open non incognito mode

### ISSUE THREAD

**Issue by vadkt** [microsoft/playwright#10725]
I launch chrome in regular mode and then attempt to connect to it over CDP. Every time I run `newContext` - the new window in incognito mode has opened. As I know, to open non incognito mode, I need to use `launchPersistentContext`. But what should I do in that situation? Is it possible to run browser in non incognito mode with connectOverCDP? Thx in advance.

**Comment by dgozman** [comment]
There is no ability to open multiple contexts that are not incognito. If you'd like to connect to a single persistent context in the browser, you can do something like this:

```js
await chromium.launchPersistentContext(userDataDir, { args: ['--remote-debugging-port=1234'] });
// ...
await chromium.connectOverCDP('http://localhost:1234');
```

Let me know whether this works for you.
