### ISSUE TITLE
[BUG] Sometimes, HTML report doesn't present a failed step in case one of entire sub-steps is failed

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#10729]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 14.6
- Browser: Chrome

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await element.click({trial: true});
```

**Describe the bug**

The HTML report presents that a test was failed and presents the location of the issue in the test:

![image](https://user-images.githubusercontent.com/52656401/144848700-c29a94ba-5907-4320-bd7a-4ada61177426.png)

In the steps, it doesn't present the failed step, but we can see that one of the entire sub-steps was failed:

![image](https://user-images.githubusercontent.com/52656401/144848876-53c8a3eb-2536-4a35-b627-112305b0af20.png)

The test was actually failed on the click({trial: true}) function. Maybe this one triggers a problem with the correct record in the report?

**Comment by dgozman** [comment]
Interesting! So the entire test did timeout, but we did not mark the last timed-out step as failed.
