### ISSUE TITLE
[Feature] Allow to work with multiple elements that match the same locator

### ISSUE THREAD

**Issue by RockMinsk** [microsoft/playwright#10726]
As example, I have list of elements that match the same locator.
- Use case 1: elements are in the DOM but can be hidden or shown after some action and I'd like to wait until all of them hidden / visible
- Use case 2: there is some table or grid with headers, each header has title and I'd like to save all titles in array. For now I can do it like this:

```
const headers: Locator = page.locator(`some locator`);
const headerTitles: string[] = await headers.evaluateAll((els: HTMLElement[]) => els.map((el: HTMLElement) => el.innerHTML));
```
But I cannot do it for each locator's element using innerText() for example.
Sure there are a lot of other ways (using ElementHandle[] and so on) but I think it will be useful (for different cases) to have possibility to iterate multiple elements that match the same locator, something like this:
```
const headers: Locator = page.locator(`some locator`);
const headerTitles: string[] = await headers.each((els: Locator[]) => els.map((el: Locator) => el.innerText()));
```

**Comment by dgozman** [comment]
Here are possible solutions. Let me know whether they work for you or not.

> Use case 1: elements are in the DOM but can be hidden or shown after some action and I'd like to wait until all of them hidden / visible

```js
// Wait for all elements to be hidden
await expect(page.locator('my-locator').locator('visible=true')).toHaveCount(0);

// Wait for all elements to be visible
await expect(page.locator('my-locator').locator('visible=false')).toHaveCount(0);
```

Documentation for [`expect(locator).toHaveCount()`](https://playwright.dev/docs/test-assertions#expectlocatortohavecountcount-options)

> Use case 2: there is some table or grid with headers, each header has title and I'd like to save all titles in array

```js
// Using an existing method
const title = await page.locator('my-locator').allInnerTexts();

// Manually
const titles = await page.locator('my-locator').evaluateAll(els => els.map((el: Locator) => el.innerText));
```

Documentation for [`locator.allInnerTexts`](https://playwright.dev/docs/api/class-locator#locator-all-inner-texts)
Documentation for [`locator.evaluateAll`](https://playwright.dev/docs/api/class-locator#locator-evaluate-all)

**Comment by RockMinsk** [comment]
Thank you for answers.
> Use case 1: elements are in the DOM but can be hidden or shown after some action and I'd like to wait until all of them hidden / visible

You suggestion:
```typescript
// Wait for all elements to be hidden
await expect(page.locator('my-locator').locator('visible=true')).toHaveCount(0);
```
Note: we migrate our project to Playwright and don't use for now @playwright/test. So some solution in @playwright will be good for us. But ok, we use some workaround and this is not a problem for us now.

> Use case 2: there is some table or grid with headers, each header has title and I'd like to save all titles in array
You suggestion:
```typescript
// Using an existing method
const title = await page.locator('my-locator').allInnerTexts();
```
Note: this is work, thanks. But in case of some

**Comment by RockMinsk** [comment]
@dgozman, based on your answer and my last comment I think you can close the ticket if there are no any plans to enhance work with Locator matches with multiple elements.
As example I provided in Slack general channel the following Protractor method: https://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.each.
So the concept was to have possibility to iterate all matched elements within Locator and perform any action available for the single locator for each of them :)

**Comment by dgozman** [comment]
> Note: we migrate our project to Playwright and don't use for now @playwright/test. So some solution in @playwright will be good for us.

Web-first assertions is one of the many reasons to use @playwright/test 😄 

> Note: this doesn't work with error Type 'SVGElement | HTMLElement' is not assignable to type 'Locator'.

My bad! It should be without a bad type:
```js
const titles = await page.locator('my-locator').evaluateAll(els => els.map(el => el.innerText));
```

> As example I provided in Slack general channel the following Protractor method: https://www.protractortest.org/#/api?view=ElementArrayFinder.prototype.each.

Thank you for the suggestion. I am wary of adding such a method, because it is inherently racy - elements in the page can change concurrently to the function you run. However, if that's not the problem for you (e.g. the list of elements is always static), you can workaround like this:

```js
const count = await locator.count();
for (let i = 0; i < count; i++) {
  const itemText = await locator.nth(i).textContent();
  // ...
}
```

**Comment by RockMinsk** [comment]
Yes, I'm already using such workaround for waiting of all elements in the list :)
So ok, I close the ticket. Thank you for feedback and clarifications.
