### ISSUE TITLE
[Question] Page closed before field is filled

### ISSUE THREAD

**Issue by bruce-at-events** [microsoft/playwright#10722]
Hi there, I'm new to playwright and here's what happened:

1. navigate to page 1, fill in the form and click submit button, this one works perfectly
2. now after submission it's on page 2 - try to fill the form and it closes the page prematurely.

It's our staging server so there's no public access but the code is as follows:

```
test(`T2"`, async ({ page }) => {
        await page.goto('https://staging.iru.com/')
        await page.waitForLoadState()
        await fullScreenShot(page, 'staging-before')
        
        // verify it's loaded - the first h2 in a should be Test Reservation
        await expect(page.locator('a h2 >> nth=0')).toHaveText('Test Reservation')
        await page.fill('#subBookings_0__BookingRate_RatePlan', 'MIN2M')
        await fullScreenShot(page, 'staging-after')

        // click submit of page 1
        await page.click('button >> nth=0')
        await page.waitForLoadState()
        await fullScreenShot(page, 'atural-booking-before-fill')
        await expect(page.locator('h1.mb-3')).toHaveText('Atura Blacktown')
       // -- up till here it works fine - and now we are already on page 2
      
        // fill in the page - it breaks right here
        await page.locator('#cardholder-name').fill('Test Name')

    })
```

Error is:

locator.fill: Target closed
=========================== logs ===========================
waiting for selector "#cardholder-name"
============================================================

I've searched everywhere but there's no solution to this one... can anyone please help? Thanks!

**Comment by dgozman** [comment]
@bruce-at-events Perhaps your whole test times out? Could you please provide a repro config+test, so that we can run locally and figure out the issue?

**Comment by bruce-at-events** [comment]
Thanks Dmitry - i found out, it was caused by frames it’s all good now.
________________________________
