### ISSUE TITLE
[Question] how to blur an element

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#10724]
Is there a function that's the opposite of `focus()`? Looking for some way to easily unfocus an element

**Comment by dgozman** [comment]
There is no such API. The workaround would be:
```js
await page.locator('my-locator').evaluate(e => e.blur());
```

**Comment by A-ZC-Lau** [comment]
Okay. Maybe a `blur` command would be good then.

**Comment by fwextensions** [comment]
Should this workaround still be working?  My test clicks a checkbox, tries to blur it, and then takes a screenshot.  However, the focus ring around the checkbox is still visible in the screenshot.  I've tried waiting 2s before taking the screenshot, to no avail.

**Comment by raray** [comment]
Why is there a `focus()` but no `blur()`?

**Comment by rwwagner90** [comment]
Seems like there should definitely be a `blur` if there is a `focus`.
