### ISSUE TITLE
[Feature] Run only changed tests for playwright test runner

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#10720]
I'm thinking about a possible feature that could be really useful for people using playwright during development - run only tests which code was changed. It would help people save time in case of changes that affect a higher number of tests. Let say that you are changing two methods which are used in 30 tests. As your whole test suite contains over 100 tests you don't want to run all of them to just check how change influences them, but just to run tests that were affected by this change. In theory, you can dig and list all tests that were affected but in the case of a higher number of tests, this is time-consuming. Ability to run tests in which code was changed since the last test run would be really helpful.

**Comment by dgozman** [comment]
Merging into #7035.
