### ISSUE TITLE
Cannot handle input of type color [BUG]

### ISSUE THREAD

**Issue by majid4466** [microsoft/playwright#10737]
Trying to `fill` an input of type color results in an error:
```javascript
const { test, expect } = require('@playwright/test');
test('Test with error', async ({page}) => {
  await page.goto('https://output.jsbin.com/suhepigeve/1');

  await page.fill('#color-code', '#33d136'); // causes the error

  await page.click('#read-color');
  await expect(page.locator('#color-value')).toHaveText('#33d136');
});
```
**Error**
>  page.fill: Error: Input of type "color" cannot be filled

Trying `type` we would not get an error, but the value will not be assigned:
```javascript
const { test, expect } = require('@playwright/test');
test('Failing test', async ({page}) => {
  await page.goto('https://output.jsbin.com/suhepigeve/1');

  await page.type('#color-code', '#33d136'); // value of the input remains #ffffff

  await page.click('#read-color');
  await expect(page.locator('#color-value')).toHaveText('#33d136');
});
```
**Test failure report**
> Error: expect(received).toHaveText(expected)
>    Expected string: "#33d136"
>    Received string: "#000000"

**Workaround**
What works for now (courtesy of Dmitry Gozman in Playwright Slack) is to evaluate js on the element to assign the value to it:
```javascript
const { test, expect } = require('@playwright/test');
test('Workaround', async ({page}) => {
  await page.goto('https://output.jsbin.com/suhepigeve/1');

  await page.locator('#color-code').evaluate(input => input.value = '#33d136'); // works fine
  
  await page.click('#read-color');
  await expect(page.locator('#color-value')).toHaveText('#33d136');
});
```

**Context:**
- Playwright Version: @playwright/test": "^1.17.1
- Operating System: Linux (Xubuntu 18.04)
- Node.js version: 12.22.7
- Browser: Chromium

**Comment by dgozman** [comment]
`await page.fill('#color-code', '#33d136');` should work in the next release.
