### ISSUE TITLE
[BUG] trace always looks partial given screenshots are cut

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#10731]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Mac
- Node.js version: 12.x

We produce traces during our CI runs for VSCode and when I look at them, I often feel like they are cut off at the end:

![image](https://user-images.githubusercontent.com/900690/144885600-b030e883-4b10-418f-8894-41eb415bf5cd.png)

I have attached a sample trace:

[playwright-trace-2.zip](https://github.com/microsoft/playwright/files/7662180/playwright-trace-2.zip)

**Comment by dgozman** [comment]
When I open the attached trace, I get a different picture. Perhaps your screenshot is from a different trace file? Also, what exactly do you mean by "cut off" - some screenshots are missing, images are cropped, something else?

<img width="1280" alt="Screen Shot 2021-12-06 at 4 45 13 PM" src="https://user-images.githubusercontent.com/9881434/144945464-ec9b9ab9-ab0f-4b20-8977-ff55deed9893.png">

**Comment by bpasero** [comment]
@dgozman oh yeah sorry, this seems to be related to my 125% zoom that makes the last screenshot drop out, making it look as if there are more screenshots. Try with 125% zoom.

**Comment by bpasero** [comment]
Thanks!
