### ISSUE TITLE
[BUG] Electron `recordVideo` option outputs zero-length webm files

### ISSUE THREAD

**Issue by jjeff** [microsoft/playwright#10735]
**Context:**
- System:
  - OS: macOS 10.15.7
  - Memory: 828.63 MB / 32.00 GB
-  Binaries:
  - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
  - Yarn: 1.22.10 - /usr/local/bin/yarn
  - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
-  Languages:
  - Bash: 3.2.57 - /bin/bash
- npmPackages:
  - playwright: ^1.17.1 => 1.17.1 
  - playwright-core: ^1.17.1 => 1.17.1 

**Code Snippet**

I've created a test project to show the problem:
https://github.com/spaceagetv/electron-playwright-example/tree/video-recording

specifically, here's the test file:
https://github.com/spaceagetv/electron-playwright-example/blob/81b8ddc3c4c78888d129892a02b7e1a205443d7a/e2e-tests/main.spec.ts#L21-L25

**Describe the bug**

When enabling the `recordVideo: {dir: 'out/test-results'}` option in the `electron.launch()` options, .webm video files are created for each test (as expected), however they are all zero-length (empty) files.

**Comment by Reed88** [comment]
I had this same issue until I put in a custom size as well as the directory. I went with `recordVideo: {dir: './/captures', size: {width: 1280, height: 720}}`

**Comment by Reed88** [comment]
@dgozman Will that change also fix an issue I am having where await page.video().path() is returning null? I'd like to try this out, how often do you cut alpha releases?

**Comment by dgozman** [comment]
Try `npm i @playwright/test@next` tomorrow - there should be a new alpha release.
