### ISSUE TITLE
[Feature]: More features for touchscreen

### ISSUE THREAD

**Issue by Henry12116** [microsoft/playwright#10740]
### Feature request

Hello,

It would be great if there was more functionality behind `touchscreen`. As per the documentation, right now we can only call `tap`. The ability to press and hold, press and drag, simulate multi finger gestures, etc would be very useful for automating testing on mobile sites that support this type of input.

Thank you!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
