### ISSUE TITLE
[Question] Access browser name / type in test

### ISSUE THREAD

**Issue by bruce-at-events** [microsoft/playwright#10744]
Hi there,

I'm busting my head trying to figure this out but there's no docs on this one, or maybe i'm just ignorant :D 

So i was doing a test with 3 browsers enabled, see config:

```
// config file
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: 'on-first-retry',
    // screenshot: 'only-on-failure',
    screenshot: 'on'
  },
  reporter: [ ['html', { output: 'never' }] ],
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Safari'] },
    },
  ],
};
export default config;
```

And in the code, I'm doing a screenshot at each stage, and I wanted a full screen one:
```
    let browserName = page.context().browser().version()
    page.screenshot({
        path: `./screenshots/${name}-${browserName}-${Date.now()}.png`,
        fullPage: true
    })
```
My problem is, I can't get browser name from this one - and the version always returns the same value.

I also tried to use `page.context().browser()._name` and I get chromium all the time, but the test did run on 3 browser types.

Is there a way to get the browser name and so I can make 3 different screenshots per browser?

Thanks,
Bruce

**Comment by dgozman** [comment]
Are you looking for the [`browserName` fixture](https://playwright.dev/docs/api/class-fixtures#fixtures-browser-name)?

```js
test('my test', async ({ page, browserName }) => {
  // ...
  await page.screenshot({
    path: `./screenshots/${browserName}-${Date.now()}.png`,
    fullPage: true
  });
});
```

In your code you get `"chromium"` all the time because there are no devices named "Chrome", "Firefox" or "Safari". You can take a look at all [available devices here](https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/deviceDescriptorsSource.json), or print it yourself with `console.log(Object.keys(devices))`. Take a look at [our recommended devices](https://playwright.dev/docs/intro#configuration-file).

Let me know whether this helps.

**Comment by bruce-at-events** [comment]
> Are you looking for the [`browserName` fixture](https://playwright.dev/docs/api/class-fixtures#fixtures-browser-name)?
> 
> ```js
> test('my test', async ({ page, browserName }) => {
>   // ...
>   await page.screenshot({
>     path: `./screenshots/${browserName}-${Date.now()}.png`,
>     fullPage: true
>   });
> });
> ```
> 
> In your code you get `"chromium"` all the time because there are no devices named "Chrome", "Firefox" or "Safari". You can take a look at all [available devices here](https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/deviceDescriptorsSource.json), or print it yourself with `console.log(Object.keys(devices))`. Take a look at [our recommended devices](https://playwright.dev/docs/intro#configuration-file).
> 
> Let me know whether this helps.

Sorry I didn't make it clear - I already set up the tests so it will test in 3 different browsers, see example result below:
![image](https://user-images.githubusercontent.com/87623471/144973099-76b8b9b3-3508-4f81-b8e7-e54f717782a6.png)
my problem is, when I take screenshots within the tests, how can I put the browser type(chromium/firefox/webkit) as part of the path for the screenshot, i.e. 
say I want to take a screenshot at step #1, so I name it as `step1.png`, and since I'm testing on 3 devices, so I would like to separate the screenshots by device, and name them `step1-chromium.png`, `step1-webkit.png` and `step1-firefox.png`.

Is there a way to get the device name in the test('xxx', ...) block?

I tried your `browserName` fixture in there however it always says `chromium` for all 3 devices, so despite the test results saying 3 tests altogether (1 on each device), I only get one screenshot named `step1-chromium.png` :(

Thanks for your help.
Bruce

**Comment by dgozman** [comment]
@bruce-at-events The `browserName` fixture should work. Could you please share your complete config and the test so we can reproduce the issue locally?

**Comment by bruce-at-events** [comment]
Sorry for the late response, please see below for details:

in playwright.config.ts​

// config file
import { PlaywrightTestConfig, devices } from ***@***.***/test';

const config: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    trace: 'on-first-retry',
    // screenshot: 'only-on-failure',
    screenshot: 'on'
  },
  reporter: [ ['html', { output: 'never' }] ],
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Safari'] },
    },
  ],
};
export default config;

the actual test spec.js:

/**
 * test screenshot
 */
import { test, expect } from ***@***.***/test'

const fullScreenShot = async (page, name, browserName) => {
    page.screenshot({
        path: `./screenshots/${name}-${browserName}.png`,
        fullPage: true
    })
}

test('test', async ({ page, browserName }) => {
    console.log(browserName)

    await page.goto('https://www.google.com')
    await page.waitForLoadState()
    // screenshot start of it
    fullScreenShot(page, 'start-page', browserName)
})

And the result:

[cid:e24bfd74-e47e-47d2-90a9-e30c075d118f]

As you can see, the log shows chromium all the time. but if I run the report:

[cid:74d5811b-8c37-4580-8a16-125b8fd7cf48]
all 3 were run.

I'm really confused.

Thanks,
B




________________________________

**Comment by dgozman** [comment]
@bruce-at-events So the problem is with the devices you use. There are no devices named "Chrome", "Firefox" or "Safari". You can take a look at all [available devices here](https://github.com/microsoft/playwright/blob/master/packages/playwright-core/src/server/deviceDescriptorsSource.json), or print them yourself with `console.log(Object.keys(devices))`. Take a look at [our recommended devices](https://playwright.dev/docs/intro#configuration-file) as well.

You see "chromium/firefox/webkit" in the report because you named your projects like this, but it still runs Chromium only. You can see for yourself in the headed mode:
```js
npx playwright test --headed
```

**Comment by bruce-at-events** [comment]
Thanks so much Dmitry!

Now I see the problem, sorry for one more question: is it possible to use the device name for screenshots? is it exposed somewhere in the fixtures?

Thanks and have a great weekend,
Bruce
________________________________

**Comment by dgozman** [comment]
> is it possible to use the device name for screenshots? is it exposed somewhere in the fixtures?

Unfortunately, no. We've never thought about such a usecase.
