### ISSUE TITLE
[Question] Firefox - Aborting only the first request with page.route

### ISSUE THREAD

**Issue by eft24** [microsoft/playwright#1074]
Hi,

In the old version (page.setRequestInterception(true), I could only abort the first request.

When I try to abort in the current release, I'm geting NS_ERROR_ABORT and NS_ERROR_ABORT_BINDING errors when the second request occurs

Thanks.

**Comment by pavelfeldman** [comment]
Could you share a code snippet? New naming is just the sugar, it should not have affected the functionality.

**Comment by pavelfeldman** [comment]
Please reopen this with a snippet - we can't repro it.
