### ISSUE TITLE
[Question] Are there other ways to locate elements when running on Android.

### ISSUE THREAD

**Issue by wangzyh** [microsoft/playwright#10745]
I am running specific software on Android, but there is no way to locate elements other than `id`.
The positioning method in the example is only `id`.
![88f912d202823ae13fbe5b15af23812](https://user-images.githubusercontent.com/31379713/144959325-9f6003c8-1e25-436e-b384-a0073546265a.png)
element like this:
`<div class="inputWrap"`

**Comment by dgozman** [comment]
@wangzyh Do you have a WebView there? You can use the full Playwright API once you call `webview.page()` as in the example above, including all kinds of selectors and locators available.

**Comment by wangzyh** [comment]
> @wangzyh你那里有 WebView 吗？您可以在调用`webview.page()`上述示例后使用完整的 Playwright API ，包括各种可用的选择器和定位器。

Yes, there is indeed a webview here, and it can be obtained with `const webview = await device.webView({ pkg:'com.ctrip.ct:business' });`, but when I use the command `webview.page() When `get `page`, the program will get stuck here.

**Comment by dgozman** [comment]
I guess we'll need a full repro scenario to be able to help.
