### ISSUE TITLE
[BUG] playwright waitForNavigation problem with firefox [headless, headed] but is working via [firefox-mode-debug, chromium, webkit]

### ISSUE THREAD

**Issue by AngelLopezBellmont** [microsoft/playwright#10752]
**Context:**
- Playwright Version: 1.1632
- Operating System: Windows, cicd(azure)
- Node.js version: 15.0.1
- Browser: **error only in firefox: [headless, headed], no error in firefox --debug, chromium,webkit**
- Extra: keycloak auth tool

**login_standard.js**

```javascript
const {test}      = require('@playwright/test');
const auth_storage_path   = 'storage_auth.json';
const {Login}             = require('../../main-test/pageObjects/login_page.js');

test('simple login', async ({page}) => {
  const login = new Login(page);
  await login.visit_baseurl();
  await login.method_login();
  await login.saveAuth(auth_storage_path);
  await login.print_url_tenant();
  await login.print_browser();
  await login.check_login_success();

});

login_page.js:

const { expect, firefox} = require('@playwright/test');
const uaParser = require("ua-parser-js");

exports.Login = class Login {

  /**
   * @param {import('@playwright/test').Page} page
   */

  constructor(page) {
    this.page = page;
  }

  async visit_baseurl () {
    await this.page.goto("/");
  }

async method_login() {
    const usernameId    = '[id="username"]';
    const passwordId    = '[id="password"]';
    const idLogin       = '[id="fc-login-button"]';
    const usernameValue = 'xxxxxxxxxxxx';
    const passwordValue = 'yyyyyyyyyyy';

    await this.page.click(usernameId);
    await this.page.fill(usernameId, usernameValue);
    await this.page.click(passwordId);
    await this.page.fill(passwordId, passwordValue);

    await Promise.all([
      //this.page.waitForNavigation({url: '/'}),                                       //works in:[chromium,webkit, firefox-mode-debug]. Problems in firefox:[headless, headed].
      this.page.waitForNavigation({url: '/', waitUntil:"load"}),                    //works in:[chromium,webkit, firefox-mode-debug]. Problems in firefox:[headless, headed].
      //this.page.waitForNavigation({url: '/', waitUntil:"domcontentloaded"}),        //works in:[chromium,webkit, firefox-mode-debug]. Problems in firefox:[headless, headed].
      //this.page.waitForNavigation({url: '/', waitUntil:"networkidle"}),             //works in:[chromium]. Problems in:[webkit, firefox] in all modes.

      this.page.click(idLogin)
    ]);

  }

  async check_login_success() {
    const search_button = 'button[data-ui-test="ticketPoolSearchButton"]';
    await this.page.waitForSelector(search_button);                 //problem in: firefox headless and headed (but not in --debug mode, in chromium,webkit ok in all mode!!)
    await expect(this.page.locator(search_button)).toBeEnabled();   //problem in: firefox headless and headed (but not in --debug mode, in chromium,webkit ok in all mode!!)
    await expect(this.page.locator(search_button)).toBeVisible();   //problem in: firefox headless and headed (but not in --debug mode, in chromium,webkit ok in all mode!!)
    //console.log('Successfully login');
  }


  async saveAuth(auth_storage_path) {
    const myContext = this.page.context();
    process.env.STORAGE = null;
    const storage = await myContext.storageState({ path: auth_storage_path });
    process.env.STORAGE = JSON.stringify(storage);
    JSON.parse(process.env.STORAGE);
  }

  async get_browser_name() {
    const getUA = await this.page.evaluate(() => navigator.userAgent);
    const userAgentInfo = uaParser(getUA);
    return userAgentInfo.browser.name;
  }

  async print_browser() {
    console.log('browser: '+ await this.get_browser_name())
  }

}
```

**Error to login via firefox , but is working in: [chromium,webkit, firefox-mode-debug]. Problems in firefox: [headless, headed]**

It is a strange behavior, it works --browser=firefox --debug but not firefox [headless, headed]. In chrmomium and webkit is working ok.

Lookslike is a problem with **waitForNavigation**. I have been trying with different options waitForNavigation({waitUntil: ""}) 

- load                         -> //works in:[chromium,webkit, firefox-mode-debug]. Problems in firefox:[headless, headed]
- domcontentloaded ->   //works in:[chromium,webkit, firefox-mode-debug]. Problems in firefox:[headless, headed].
- networkidle             ->    //works in:[chromium]. Problems in:[webkit, firefox] in all modes.

How can it be, that is working this simple login-test  --browser=firefox --debug and not headless??

Regards

**Comment by dgozman** [comment]
@AngelLopezBellmont Thank you for the issue. Unfortunately, we cannot run the code above because it is incomplete, so we cannot see the problem ourselves.

Please describe your issue in more details:
- What exactly "does not work"?
- What do you expect to happen?
- Does it hang?
- Does it show any errors?
- Could you [record a trace](https://playwright.dev/docs/trace-viewer) and send us?
- Could you provide a full repro with config+test file?

**Comment by AngelLopezBellmont** [comment]
it is not working when I run the simple login-test locally (and in cicd as well)

-  npx playwright test mydemos/login_standard.spec.js --browser=firefox   (DOESN'T work)

 when I do 

-   npx playwright test mydemos/login_standard.spec.js --browser=webkit   (it works)
-   npx playwright test mydemos/login_standard.spec.js --browser=chromium   (it works)

`playwright.config.js

/** @type {import('@playwright/test').PlaywrightTestConfig} */

const config = {
  use: {
    baseURL: 'https://papa.fieldcode.rocks',

  },

};

module.exports = config;
`

**Comment by dgozman** [comment]
@AngelLopezBellmont I still don't understand what exactly is not working? Do you have some screenshots or output from the terminal to share?

**Comment by AngelLopezBellmont** [comment]
I will close this issie and open a new one without pageObject . And I will paste the terminal information there

**Comment by AngelLopezBellmont** [comment]
#https://github.com/microsoft/playwright/issues/10832
