### ISSUE TITLE
[Question] Are aborted requests able to set cookies?

### ISSUE THREAD

**Issue by eckhards** [microsoft/playwright#10755]
I am using Playwright Python as part of my own SaaS product to inspect web pages. On the following URL a Youtube video is embedded, and the consent management software Usercentrics is in place to block loading the video until the user has given their consent:

https://www.phoenix-mecano.ch/de/produkte/fahrerlose-transportsysteme-fts/fahrerlose-transportsysteme-fts.html/779

Usercentrics aborts the network request to Youtube using some JS code. When loading this page in a "real" Chrome browser and watching the devtools network tab, the reqest is sometimes highlighted in red with the status "aborted". The request does in no case set any cookies.

When loading the page with Playwright, one can detect that the request is aborted in 100% of all test runs (see the example code). However, in about 50% of the test runs I do, I can see multiple cookies from the domain youtube.com. There is no other request to Youtube, so apparently this aborted request manages to set cookies. How is this possible, this seems to me like a bug in Playwright? Wether cookies are set or not is a crucial result in my (data protection related) SaaS product.

```
import asyncio
from playwright.async_api import async_playwright
from random import randrange

async def main():
	async with async_playwright() as p:
		for browser_type in [p.chromium]:
			browser = await browser_type.launch()
			page = await browser.new_page()
			page.on("requestfailed", lambda request: print("request failed",request.url,request.failure))
			await page.goto(url='https://www.phoenix-mecano.ch/de/produkte/fahrerlose-transportsysteme-fts/fahrerlose-transportsysteme-fts.html/779',wait_until = 'networkidle')
			cookies = await page.context.cookies()
			for cookie in cookies:
				print("cookie",cookie['name'],cookie['domain'])
			await browser.close()
asyncio.get_event_loop().run_until_complete(main())
```

**Comment by pavelfeldman** [comment]
I don't see where in the snippet you are aborting the requests and how.

Playwright does not modify the browser, so what you see is happening to a real fresh Chrome instance when user visits that page.

**Comment by eckhards** [comment]
I do not actively abort them in my code, the website (or better: the consent management tool "Usercentrics") aborts the request. Please see the screenshot, the request is marked as aborted in devtools (german "abgebrochen" == aborted)

![screen1](https://user-images.githubusercontent.com/22469899/145166949-5e4c8a76-6d6f-4d66-8cc4-f273cb3df8cd.png)

In the second screenshot you can see what the above Playwright script displays when running twice. In the first run you see the message from page.on("requestfailed") marked (1.) and the list of cookies, none from youtube.com, marked (2.). In the second run you see that the request has been aborted as well, but this time there are cookies from youtube (even though the request has failed, so no response headers "set-cookie" should be in place. 

![screen2](https://user-images.githubusercontent.com/22469899/145166935-0a083f10-efb4-4b8b-b365-44b5147c3192.png)

Any idea what is happening here?

**Comment by dgozman** [comment]
@eckhards I guess you have found a bug on the site? I'd assume there was another successful request that ended up with youtube cookies. Try [recording a trace](https://playwright.dev/docs/trace-viewer) and look at the network tab - maybe you'll spot the request right away.

**Comment by dgozman** [comment]
Not sure how we can help here without a repro. If you have a repro that we can run, please open a new bug.

**Comment by eckhards** [comment]
@dgozman I fully understand - tried to make it reproducable with a trace but with no avail, even though the effect still persists when using a Chrome on my Macbook. I will keep trying to set up a repro and will follow up. Thanks!

**Comment by eckhards** [comment]
Hey @dgozman , I was unable to produce a repro that reliably shows the effect. I presume this is some race conditions related thing going on. We might close this ticket because it is not repdoducible, in case I find a repro I will open a new ticket. Thanks so far!
