### ISSUE TITLE
[BUG] Locator .type will prefix the existing text (after page load) rather than appending to the end

### ISSUE THREAD

**Issue by liamdocherty10** [microsoft/playwright#10753]
**Context:**
- Playwright Version: @playwright/test 1.16.2
- Operating System: Mac
- Node.js version: 14.17.0
- Browser: All
- Extra: N/A

**Code Snippet**

```javascript
import { expect, test } from "@playwright/test";

test("Test", async ({ page }) => {
  await page.goto("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_value");
  await page.locator("#accept-choices").click();
  const iframe = page.frame("iframeResult");
  const firstNameInput = iframe.locator("#fname");
  await firstNameInput.type(" aaa");
  await firstNameInput.type(" bbb");
  // Test will fail with actual value of " aaa bbbJohn"
  expect(await firstNameInput.inputValue()).toBe("John aaa bbb");
});
```

**Describe the bug**

I would expect that using `.type()` would append the supplied text to any text already in the element however it prefixes it if the text exists on page load.

There is a different behaviour if you perform `.type()` multiple times after page load. In this case, the text will prefix the original text but come after any `.type`'d text

See the screenshot below.

Thanks.

![image](https://user-images.githubusercontent.com/45755433/145021574-c6478771-4920-46bf-a75a-05cc034db192.png)

**Comment by dgozman** [comment]
@liamdocherty10 That's how Playwright decided to handle this. The main point here is the consistency between browsers and platforms. We cannot change this behavior now, because many existing tests will break.

I'd suggest to use [`locator.fill()`](https://playwright.dev/docs/api/class-locator#locator-fill) instead:
```js
const existingValue = await firstNameInput.inputValue();
await firstNameInput.fill(existingValue + ' aaa');
```

**Comment by liamdocherty10** [comment]
@dgozman I'm pretty early into using Playwright but I'm working on a central team trying to develop some generic 'wrapper' methods so that each consumer team can use a more tool agnostic implementation e.g.
```
async enterText(element: Locator, text: string) {
  await element.type(text);
}
```

If we switch to using `.fill` like your suggestion, are there any scenarios you are aware of where I'd need to use some conditional check based on the tag e.g.:
```
async enterText(element: Locator, text: string) {
  const tag = ... // I'd need to look up how to get the element tag
  switch(tag) {
    case "input":
    case "textarea":
      const existingValue = await element.inputValue();
      await element.fill(existingValue + text);
    break;
    case ...
    case ...
  }
}
```

Or do you expect `.inputValue()` + `.fill()` to cover all scenarios?

**Comment by dgozman** [comment]
> Or do you expect `.inputValue()` + `.fill()` to cover all scenarios?

I do. However, if you encounter an edge case where this is not sufficient, don't hesitate to file an issue. Easy input actions is one of the high priority areas for Playwright.

**Comment by adiel** [comment]
Came here looking for this, which works fine:

https://github.com/microsoft/playwright/issues/17295#issuecomment-1245506293

> That's how Playwright decided to handle this. The main point here is the consistency between browsers and platforms.

Can't say I understand this reasoning, prepending text in an input is very much the edge case, not appending.

> We cannot change this behavior now, because many existing tests will break.

Sure. If one was to propose either new methods to append when typing/pressing on `Locator` & `ElementHandle` or a new option on `LocatorTypeOptions` & `ElementHandlePressOptions` would that be welcomed? Which would be preferred?

**Comment by kamil-czornyj** [comment]
Anything happened in this topic? I've just started to use playwright and it's so frustrating to type before existing text, why there are no FillOptions for that?
