### ISSUE TITLE
[Feature] HTML Report: add links to navigate back to the home page

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#10750]
For now, once we go into details of a test in the HTML report, there is no link to navigate back to the home page except click back button in browser. It causes more issue when the HTML report is views on some CI platform e.g. Jenkins bcs clicking browser back button means moving away from the current Jenkins job run instead of going back to Playwright HTML report home page.

Some suggestion is to add link to the highlighted elements as in the screenshot

![image](https://user-images.githubusercontent.com/4818798/145006410-e6179ab5-de61-48a4-b0b0-c89f5a008c42.png)

**Comment by pavelfeldman** [comment]
Is there a link we could try? Are you opening report in an iframe?

**Comment by TimeInvestor** [comment]
> Is there a link we could try? Are you opening report in an iframe?

Since our Jenkins is protected so I cannot share any link. It is a standard Jenkins [HTML Publisher plugin](https://plugins.jenkins.io/htmlpublisher/). So I expect many users who run Playwright tests on Jenkins CI will be benefit from this.

Thanks 👍
