### ISSUE TITLE
page screenshot timeout 

### ISSUE THREAD

**Issue by jdedwards3** [microsoft/playwright#10765]
Here is the Dockerfile I am using:

```
FROM mcr.microsoft.com/playwright:focal

ENV NODE_ENV=production

WORKDIR /usr/app

COPY index.js package.json ./

RUN npm install

RUN npx playwright install

RUN npx playwright install-deps

EXPOSE 3000

CMD ["node", "index.js"]
```

I am using this on AWS lightsail with Amazon Linux OS and 2GB memory, 1 core processor. I am using it to run an Express v4.17.1 web api application.

The relevant portion of the code running in the Express server is: 

```js
const stream = require("stream");
const express = require("express");
const app = express();
const playwright = require("playwright");

app.post("/route/", async (req, res) => {
  const browser = await playwright["chromium"].launch({ timeout: 60000 });

  try {
    const browserContext = await browser.newContext();

    const page = await browserContext.newPage();

    await page.goto("https://css-tricks.com/snippets/css/media-queries-for-standard-devices/", {
      waitUntil: "load",
      timeout: 60000,
    });

    const buffer = await page.screenshot({ timeout: 60000, fullPage: true });

    await browser.close();

    stream.Readable.from(buffer).pipe(res);
  } catch (error) {
    await browser.close();
    res.sendStatus(500);
  }
});

app.listen(3000);
```

I am getting a timeout at "page.screenshot({...})" even when bumping the timeout up to 120000. Other(smaller) pages are working fine and the screenshot is generated. Please let me know if more information would be helpful.

**Comment by dgozman** [comment]
Well, I just took this screenshot - it is 1264x84306 pixels. I guess your environment is too constrained to handle that. Not sure we can do anything about that 😄

I can suggest to split page into parts and take multiple screenshots:

```js
  // Make sure viewport height is 1000px.
  await page.setViewportSize({ width: 1280, height: 1000 });
  for (let i = 0; i < 85; i++) {
    await page.screenshot({ path: `screenshots/part-${i}.png` });
    await page.evaluate(() => window.scrollBy(0, 1000));
  }
```

**Comment by jdedwards3** [comment]
@dgozman Thank you for responding to this so promptly! 

I see the [system requirements](https://playwright.dev/docs/library/#system-requirements) for playwright, although there is no mention of minimum requirements, in terms of memory or processor. 

Is there a suggested minimum system configuration?

**Comment by dgozman** [comment]
> Is there a suggested minimum system configuration?

Nope - it depends on what you are doing. As we just saw, capturing a full-page screenshot of some large page is pretty heavy on memory (and probably also cpu + gpu if there is any), while doing some casual goto+click can be done on very light machines. It is also very much browser-dependent. Here is what [Google Chrome has to say](https://support.google.com/chrome/a/answer/7100626?hl=en) about system requirements.
