### ISSUE TITLE
[Feature] Missing dependencies in Pop_os (Ubuntu derivative)

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#10776]
In Pop_os, running

```
sudo npx playwright install-deps                                                                                                         
```

results in

```
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
```

and so we see:

```
Error: 
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-deps                       ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
```

**Comment by dgozman** [comment]
@trusktr Playwright does not officially support Pop_os, but if you have a nice solution, contributions are welcome.

**Comment by maxnewbould** [comment]
Pop_os 20.10 runs playwright after installing the below (not officially supported so YMMV):

http://archive.ubuntu.com/ubuntu/pool/main/i/icu/libicu66_66.1-2ubuntu2.1_amd64.deb 

http://archive.ubuntu.com/ubuntu/pool/universe/e/enchant/libenchant1c2a_1.6.0-11.3build1_amd64.deb

**Comment by trusktr** [comment]
Why does Playwright use specific versions of lib files, unlike most other projects? Every other headless browser runner I've tried has always worked in every Linux distro I've used. Playwright is the only one that chooses to depend on specific versions of lib files, making it hard to install anywhere but in the docker container.

**Comment by trusktr** [comment]
`libenchant1c2a`: is that a commit hash?
