### ISSUE TITLE
[Feature]getTableContents and fetch api

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#10777]
https://resources.sahipro.com/docs/sahi-apis/fetch-apis.html#_getTableContents
The more is fetch api:

https://resources.sahipro.com/docs/sahi-apis/fetch-apis.html

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
