### ISSUE TITLE
[Docs] the signatures for event listeners don't specify the arguments or types correctly

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#10780]
This is super confusing because the displayed signature is completely different to it's actual signature, and the examples are very sparse (not not even use the function, like `page.on('popup')`)
![image](https://user-images.githubusercontent.com/65446343/145141378-d4a0e29c-3463-4778-9274-7785aa080388.png)

But it's not is it, it's actually :
# page.on('console', listener)
- `listener`: <function(ConsoleMessage)> Function to be evaluated when the event is emitted
- returns: \<Page>

**Comment by dgozman** [comment]
@KotlinIsland This is a common practice in Node.js world. Note that it says "type" and not "second argument" or "listener" 😄  Do you have an example of some other project that handles this better? We are open to improvements.

**Comment by DetachHead** [comment]
most projects i've seen have a separate section for events ([example](https://abal.moe/Eris/docs/0.16.1/Client#event-callCreate)), instead of listing them as signatures of the `on` method, which looks misleading imo

**Comment by KotlinIsland** [comment]
@dgozman I came from the python docs and it's so just so extremely unintuitive, I presumed that there had been some mixup and the wrong documentation was generated. These functions are presented alongside the rest of the api to do distinction.

I would think a different section "Event handling" explaining whats going on, as @DetachHead suggested would be a good one.

I wouldn't mind whipping together something when I have time.

**Comment by dgozman** [comment]
@KotlinIsland Looking forward for any improvements!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
