### ISSUE TITLE
[BUG] Test is randomly failing without showing errors in the test output

### ISSUE THREAD

**Issue by amrsalem1** [microsoft/playwright#10786]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 14
- Browser: all

**Code Snippet**

```
    async addNewTestStory(title: string) {
        await this.addTestStoryButton.first().waitFor({ state: "attached" })
        await this.addTestStoryButton.first().click()
        await this.storyTitleInput.waitFor()
        await this.storyTitleInput.type(title)
        await Promise.all([
            this.page.waitForResponse(response =>
                response.status() === 201),
            this.submitTestStory.click()
        ])
        return this;
    }
```
`await feature.alertOf('Saved').waitFor()`

**Describe the bug**

The test is failing without showing any error log, after checking the trace folder found this below 

<img width="1439" alt="Screenshot 2021-12-08 at 12 40 32" src="https://user-images.githubusercontent.com/89022647/145370031-6ce2aaa2-9cda-4988-90f5-7c10f9cdad02.png">

<img width="615" alt="Screenshot 2021-12-08 at 12 42 53" src="https://user-images.githubusercontent.com/89022647/145370121-14c4ceb1-6509-4d1c-a8fb-c267e38f34cd.png">

**Comment by dgozman** [comment]
@amrsalem1 We need more information to help you.
- What is this report? It does not look like a built-in Playwright Test report.
- Did you open the trace file? What does it show?
- What do you see in the terminal?
- Could you please share the repro config + test?

**Comment by amrsalem1** [comment]
@dgozman 
-its allure report, but also in the terminal output no any error is shown, its just show that test has failed 
- I have added a screenshot of failed step from trace viewer.  ```await feature.alertOf('Saved').waitFor()``` 
after I have added timeout for waitFor I didn't see the error again, but still some error should have been displayed in terminal

my configs 

```
const configList = {
    workers: 10,
    headless: process.env.CI ? true : false,
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    baseURL: process.env.CI ? 'http://localhost:3000' : 'http://63.10.5.54:3000',
    browser: 'chrome',
    testDir: '../src/specs',
    reporter: [
        ['list'],
        ['experimental-allure-playwright']
    ],
    timeout: 20000,
    retries: 0,
    acceptDownloads: false,
    specs: process.env.CI ? ['*'] :
        [
            'tests/src/specs/Login/1.Login.test.ts',
        ],
    devtools: true,
};

```

**Comment by dgozman** [comment]
I don't think we'll be able to fix the issue, unless we have a full repro that we can run locally.

**Comment by ltsuda** [comment]
As @dgozman said, they need a way to reproduce the issue on their side but just some observations:

- You are using an older version of allure-playwright, please use an updated version
  - https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md
- On the right-side menu of the Trace Viewer there's a `1` on the Console tab, what does it have there?
- Is this alert animated, like slides from the right or something like that?
  - Maybe you could try using the `.elementHandle()` from the alert locator and then await for `.waitForElementState("stable")`

```
const handle = await feature.alertOf('Saved').elementHandle()
await handle.waitForElementState("stable")
```

- About the list reporter, you should have the error output on your terminal, at least is working on my side/test code.

**Comment by amrsalem1** [comment]
> I don't think we'll be able to fix the issue, unless we have a full repro that we can run locally.

unfortunately its private project, but will try to find another way to reproduce it in some public domain

**Comment by amrsalem1** [comment]
> 

yes its somehow animated, will try to use the method u have provided

**Comment by mxschmitt** [comment]
@amrsalem1 are you able to create a small repro for us? Otherwise we can't act on it and we would have to close it.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
