### ISSUE TITLE
[BUG] Playwright Node.js does not remove temp downloads as advertised

### ISSUE THREAD

**Issue by andrejs-ps** [microsoft/playwright#10785]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 14.18.1
- Browser: Tried Chromium (but probably all)

**Code Snippet**

```javascript
test.only('Download Test', async () => {

    const browser = await chromium.launch({ headless: false, slowMo: 2000 });
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();

    await page.goto('any page with a downloadable file');

    const [download] = await Promise.all([
        page.waitForEvent('download'),
        page.click('selector to download')
    ]);
	
    const path = await download.path();
    console.log("The temp path is: " + path);
    
    context.close(); // optional?
});
```

**Describe the bug**

The documentation (https://playwright.dev/docs/downloads/) states that 

> "Downloaded files are deleted when the browser context that produced them is closed"

This is true in Java binding (tried in 1.14 and 1.17), however this is not the case for NodeJs implementation. It keeps the artifacts and lets them accumulate (On Windows in AppData\Local\Temp). Invoking  context.close(); explicitly has no effect, though I assume it is not necessary as at the end of the test the context should be destroyed.

**Comment by dgozman** [comment]
@andrejs-ps Are you using @playwright/test? I'd highly recommend that.

> though I assume it is not necessary as at the end of the test the context should be destroyed.

Since you create context yourself, you should also close it explicitly. In the code you are missing await in `await context.close()`. You also should close the browser that you've launched.

```js
    const browser = await chromium.launch({ headless: false, slowMo: 2000 });
    const context = await browser.newContext({ acceptDownloads: true });
    const page = await context.newPage();

    await page.goto('any page with a downloadable file');

    const [download] = await Promise.all([
        page.waitForEvent('download'),
        page.click('selector to download')
    ]);
	
    const path = await download.path();
    console.log("The temp path is: " + path);
    
    await context.close();
    await browser.close();
```

Let me know if that does not help. When I await both, it works for me locally.

**Comment by andrejs-ps** [comment]
@dgozman - do you mean one should use the fixture like so? 

```
test('Test ', async ({browser}) => {
const context = await browser.newContext({ acceptDownloads: true });
...
}
```

The above works and Playwright cleans up the temp download without having to explicitly `await context.close();`.

But how do I create a single self-contained test that runs in headed mode AND acceptsDownloads? (I'm aware of test.use() method and global config json file).

There's not `browserType` fixture, so the only way I see is to explicitly type out `chromium.launch({headless: false})`

**Comment by dgozman** [comment]
> The above works and Playwright cleans up the temp download without having to explicitly await context.close();

That's because built-in `browser` does a proper close for you.

> But how do I create a single self-contained test that runs in headed mode AND acceptsDownloads? (I'm aware of test.use() method and global config json file).

`test.use()` is scoped per describe block, so just wrap your test in a describe like this:

```js
test.describe('my single test with specific options', () => {
  test.use({ acceptDownloads: true });
  test('my test', async ({ page }) => {
    // ...
  });
});
```

If you also need this single test to be headed (why though?), you'll need a separate file.

```js
test.use({ headless: false, acceptDownloads: true });
test('my test', async ({ page }) => {
  // ...
});
```

**Comment by andrejs-ps** [comment]
@dgozman - thank you, this answers my question.

To anyone reading this, a small note: `headless` is nested inside `launchOptions` like so:

test.use({
    launchOptions: { headless: true}, 
    acceptDownloads: true
});
