### ISSUE TITLE
[Question]How to verify the a file is downloaded successfully or not using playwright JS

### ISSUE THREAD

**Issue by AmanDaharwal** [microsoft/playwright#10788]
Scenario: App has a download file button, on click, the app sends a get request to BE and if response is 2xx, pdf file is downloaded else if  response is 4xx/5xx, pdf file is not downloaded.

Script to Verify : File is download successfully or not (true/false) after clicking on download file button.

**Comment by dgozman** [comment]
Take a look at our [downloads guide](https://playwright.dev/docs/downloads).
