### ISSUE TITLE
[Feature] CLI options to run / ignore matching tests

### ISSUE THREAD

**Issue by orihomie** [microsoft/playwright#10784]
I'd like to have ability to tag test and then, when I run my tests to be able to choose which tests would be launched or ignored.
- the tags for tests
- and the ability for runner to take / skip tests by that tags

**Comment by Nav-2d** [comment]
Are you looking for this? https://playwright.dev/docs/test-annotations#tag-tests

**Comment by dgozman** [comment]
Let us know if the link above does not help.

**Comment by orihomie** [comment]
Thanks!
