### ISSUE TITLE
[BUG] Cannot launch my end 2 end tests with docker-compose using codeceptjs/playwright

### ISSUE THREAD

**Issue by herrouhajar** [microsoft/playwright#10793]
Hello,

Im facing an issue while running my e2e test with docker-compose, cmd : **docker-compose run node npx codeceptjs run**  
im getting this error : 

** browserType.launchPersistentContext: Failed to launch: Error: spawn /home/node/.cache/ms-playwright/chromium-920619/chrome-linux/chrome ENOENT
=========================== logs ===========================
<launching> /home/node/.cache/ms-playwright/chromium-920619/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-backg
round-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disab
le-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter --a
llow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --for
ce-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --user-data-dir=/tmp/playwright-tmp --
remote-debugging-pipe --no-sandbox --ignore-certificate-errors --no-sandbox about:blank
[pid=N/A] starting temporary directories cleanup
[pid=N/A] finished temporary directories cleanup
============================================================
**

this is my codeceptjs.conf file : 

helpers: {
    Playwright: {
      url,
      show: true,
      browser: "firefox",
      /*chromium: {
        userDataDir: '/tmp/playwright-tmp',
        args: ['--ignore-certificate-errors', '--no-sandbox']
      },*/
      fullPageScreenshots: true,
      windowSize: "1520x750",
      //restart: true,
      waitForNavigation: "domcontentloaded",
      waitForAction: 500,

    },

@yury-s  please this is so urgent, could you take a look ?

**Comment by dgozman** [comment]
@herrouhajar Looks like the browser executable is missing. Did you run `npx playwright install`? Overall, this question belongs to codeceptjs issues.

**Comment by herrouhajar** [comment]
@dgozman yeah i did, but the issue still took place when i run : 
`docker-compose run node npx codeceptjs run`

**Comment by dgozman** [comment]
@herrouhajar I am sorry, but we do not know what codeceptjs does, so we are unlikely to be able to help.
