### ISSUE TITLE
[BUG] PrintDeps.exe ran in visible console window

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#10802]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: 16
- Browser: Firefix

**Describe the bug**

Running some script that uses Firefox, headless, as admin user in Windows 10, and this makes playwrite pop up visible console windows running PrintDeps.exe on the screen like 10 times when a new browser is opened. I'll try to investigate further, but you might know why. Perhaps something around the util.spawnAsync() function.

**Comment by 54995610** [comment]
Hello Team, 

We are using Playwright with Javascript for our UI automation where we are also establishing a connection to IBM Data base by using following two :-  

When I am executing the script I am getting 8 different PrintDeps.exe bad image pop-ops where I have to close all those 8 pop-ups manually and that's when the execution is starting.

We are using version :- "@playwright/test": "^1.40.1".

Any help is much appreciated. 

Images which we are getting 
![Bad image Print deps](https://github.com/microsoft/playwright/assets/104173297/1c23fc65-59f1-44a1-bf76-de6f69961907)
