### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1080]
**Context:**
- Playwright Version: 0.11.1
- Operating System: macOS
- Extra: Node 12.16.1

**Code Snippet**

```javascript
const { chromium, webkit, firefox } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto('https://cdpn.io/celeryclub/debug/RwPogLo/GnAnbOZXLOnA');
  await page.click('a');

  const pages = await browser.pages();
  console.log(pages.length)
  // console.log(pages[0]);
  await pages[0].bringToFront();

  // just so we can see what happened before the browser closes
  await page.waitFor(2000);

  await browser.close();
})();
```

**Describe the bug**

I'm trying to click a link that opens in a new tab, then re-focus the original tab. The code above works in Puppeteer, but in Playwright I get the following error: `TypeError: browser.pages is not a function`.

I think this is probably a dupe of https://github.com/microsoft/playwright/issues/1040, but that issue was lacking info so I decided to file this anyway.

Thanks for looking!

**Comment by arjun27** [comment]
For multi-page workflows, we recommend creating a [new browser context](https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#browsernewcontextoptions). The `pages()` method exists on BrowserContext. I've also added a quick wait for the new page to be created in the snippet below.

```js
//@ts-check
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://cdpn.io/celeryclub/debug/RwPogLo/GnAnbOZXLOnA');
  await Promise.all([
    page.click('a'),
    new Promise(resolve => page.once('popup', resolve)),
  ]);

  const pages = await context.pages();
  console.log(pages.map(p => p.url()));

  await browser.close();
})();
```

Also, if you are using VS Code, I would recommend adding `//@ts-check` to the start of the file to ensure the editor can type-check your code.

**Comment by celeryclub** [comment]
Ah right. This was definitely me not reading the docs carefully enough. :) Thanks so much for clarifying @arjun27.

It doesn't appear that pw has any sort of `bringToFront` function like puppeteer does. Is that correct? In my case that's fine because I can call `await popup.close()` and accomplish what I'm trying to do.

**Comment by arjun27** [comment]
that's right, `bringToFront` does not exist at this point.
