### ISSUE TITLE
[BUG] Cascaded selector is not working with registered selector

### ISSUE THREAD

**Issue by Krata4** [microsoft/playwright#10800]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 
- Browser: Chromium

Iam using registered selector like:
async function registerMySelector(page, args, log, playwright) {
    playwright.selectors.register("menu", () => ({
        // Returns all elements matching given selector in the root's subtree.
        queryAll(root, selector) {
          let results = [];
          let query = document.evaluate('//*[@aria-label="' + selector + '"]', document,
              null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
          for (let i = 0, length = query.snapshotLength; i < length; ++i) {
              results.push(query.snapshotItem(i));
          }
          return results;
        }
    }));
    return 1;
    }

    exports.__esModule = true;
    exports.registerMySelector = registerMySelector;

my HTML page is:
![image](https://user-images.githubusercontent.com/70528301/145259767-f15b4edf-0257-4884-b059-7cb22d721e68.png)

so I would like use cascaded selector like:
await page.click('menu=Lead Form >> menu="Details");
but it does not work.

working for me:
await page.click('menu=Lead Form >> [aria-label="Details"]);

not work (because more elements with aria-label=Details on my page - but combination with Lead Form is one element only):
await page.click('[aria-label="Lead Form"] >> menu=Detail);

From my point of you - rgistered locator is parsed only on first position before >>. In case other position (after >>), everything before is not used and parsed - only registered locator is usend unfortunatly.

**Comment by dgozman** [comment]
@Krata4 This is because you start your xpath evaluation from the document.

```js
let query = document.evaluate('//*[@aria-label="' + selector + '"]', document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
```

Replace the line above with the following:

```js
let query = document.evaluate('//*[@aria-label="' + selector + '"]', root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
```

Let us know if you need more help.

**Comment by Krata4** [comment]
Hello,

still not work:
async function registerMySelector(page, args, log, playwright) {
    playwright.selectors.register("menu", () => ({
        // Returns all elements matching given selector in the root's subtree.
        queryAll(root, selector) {
          let results = [];
          let query = document.evaluate('//*[@aria-label="' + selector + '"]', root, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
          for (let i = 0, length = query.snapshotLength; i < length; ++i) {
              results.push(query.snapshotItem(i));
          }
          return results;
        }
    }));
    return 1;
    }

work: 
await page.click('menu=Lead Form >> [aria-label="Details"]');

not work:
await page.click('[aria-label="Lead Form"] >> menu=Details');
await page.click('menu=Lead Form >> menu=Details');

**Comment by dgozman** [comment]
@Krata4 The code looks fine, so need to debug it. If you have a repro with a script and a web page, we'll be able to take look.

**Comment by Krata4** [comment]
with css locationg it is working:
        
queryAll(root, selector) {
            return Array.from(root.querySelectorAll('[aria-label="' + selector + '"]'));
        }

Can you help me how to implement for XPATH please?

Thanks

**Comment by Krata4** [comment]
sorry, I do not have :-(

**Comment by dgozman** [comment]
Take a look at xpath engine implementation: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/xpathSelectorEngine.ts.

**Comment by Krata4** [comment]
it looks same as my code :-( I do not know where is problem :-(

**Comment by Krata4** [comment]
I tried to write it as xpath engine:
        queryAll(root, selector) {
          let results = [];
          let query = document.evaluate('//*[@aria-label="' + selector + '"]', root, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);
          for (let node = query.iterateNext(); node; node = query.iterateNext()) {
            if (node.nodeType === Node.ELEMENT_NODE)
              results.push(node);
          }
          return results;
        }

but same issue

**Comment by Krata4** [comment]
with this - same issue:

        queryAll(root, selector) {
          let results = [];
          const document = root instanceof Document ? root : root.ownerDocument;
          let query = document.evaluate('//*[@aria-label="' + selector + '"]', root, null, XPathResult.ORDERED_NODE_ITERATOR_TYPE);
          for (let node = query.iterateNext(); node; node = query.iterateNext()) {
            if (node.nodeType === Node.ELEMENT_NODE)
              results.push(node);
          }
          return results;
        }

**Comment by Krata4** [comment]
oooooh.
solved

dot before //
so xpath must start with dot like ".//" and it is working :)))). 
Thank you very much
