### ISSUE TITLE
[Question] Running tests on Azure

### ISSUE THREAD

**Issue by mdemenko** [microsoft/playwright#10818]
I'm running tests on Azure pipeline and have several questions:
1. Currently HTML report is displayed after clicking HTML Viewer tab for pipeline run. But empty page is displayed after clicking failed tests (any details, screenshot, etc.). Test results artifact is generated and can be downloaded (with html folder). So is this PW issue or it should be configured in Azure separately?
![Azure Devops](https://user-images.githubusercontent.com/8157779/145374732-7a3be556-a814-4dac-a2af-64ddced0fc6e.png)

2. Video files are recorded with other resolution that specified in config (viewport: { width: 1920, height: 1080 }). Only last second is recorded with 1920x1080. Issue isn't reproducible locally.

**Comment by dgozman** [comment]
> Currently HTML report is displayed after clicking HTML Viewer tab for pipeline run. But empty page is displayed after clicking failed tests (any details, screenshot, etc.). Test results artifact is generated and can be downloaded (with html folder). So is this PW issue or it should be configured in Azure separately?

Playwright does not do anything special for Azure pipelines. This seems to be Azure pipelines picking something up from your test output? I'd look in their documentation first.

> Video files are recorded with other resolution that specified in config (viewport: { width: 1920, height: 1080 }). Only last second is recorded with 1920x1080. Issue isn't reproducible locally.

Video defaults to 800x450, unless you specify the video size. [See here](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-video) for more details. For some reason, [video option](https://playwright.dev/docs/api/class-testoptions#test-options-video) does not document this - we'll fix that.

**Comment by mdemenko** [comment]
I've checked with next config:
`   timeout: 45000,
    workers: 6,
    use: {
        headless: false,
        viewport: { width: 1920, height: 1080 },
        browserName: "chromium",
        screenshot: "only-on-failure",
        video: "retain-on-failure",
        storageState: "state.json",
        acceptDownloads: true,
        trace: "retain-on-failure",
        contextOptions: {
            recordVideo: {
                dir: "test-results/videos",
                size: {
                    width: 1920,
                    height: 1080,
                },
            },`
and there are my expectations:
- video is recorded only for beforeAll hook, test video isn't opened with error "Can't play because the item's file format isn't supported. Check the store to see if this item is available there. 0xc00d3e8c"
- as I understood recordVideo setting will record video for all tests if it's populated in global test config. How I can extend video: "retain-on-failure" setting and record failed tests with particular size? Also as I said before: currently failed videos are recorded according viewport setting, but on CI - with default size.

**Comment by mdemenko** [comment]
Thanks @ltsuda for the link. This is what I was looking for.

**Comment by dgozman** [comment]
@mdemenko You should not mix `contextOptions: { recordVideo: ... }` and `video: "retain-on-failure"` because they conflict. Following @ltsuda's link you can configure just the `video` option and it should work. Let us know if something does not work.
