### ISSUE TITLE
Chromium/Windows test is failing in the latest roll

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#10811]
- range: https://chromium.googlesource.com/chromium/src/+log/640cff72368a6e743ac36f1cb8a5e842a2592167..6a7b36500c7e0313dc479b2c28371485b08fc198
- probably this commit: https://chromium.googlesource.com/chromium/src/+/9250cb6111ebfa5f751141ae5c5443552b097cf2 
- caseq stamped it: https://chromium-review.googlesource.com/c/chromium/src/+/3313465
- thats the test which is failing: `defaultbrowsercontext-2.spec.ts:130:1 › should restore cookies from userDataDir`
- See #10747 for bot logs

**Comment by dgozman** [comment]
Upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1278119
