### ISSUE TITLE
Wrong path to fail screenshot in html report [BUG]

### ISSUE THREAD

**Issue by Avol-V** [microsoft/playwright#10816]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Linux
- Node.js version: 14.18.0
- Browser: All
- Extra: Only in CI (TeamCity)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
export function pathFromRoot(path: string) {
    return resolve(__dirname, '..', path);
}

{
    reporter: [
        [process.env.CI ? 'list' : 'line'],
        ['html', {
            open: process.env.CI ? 'never' : 'on-failure',
            outputFolder: pathFromRoot('playwright-report'),
        }],
    ],
}
```

**Describe the bug**

Path to fail screenshot in Screenshots section — is absolute path in file system to the test-results folder, not the path to the copy in data dir in playwright-report directory.
```html
<img src="/opt/buildagent/work/…/test-results/full-test-name--Chrome/test-failed-1.png">
```

Looks like it happens when there is no source screenshot (but why file not exists?).

**Comment by pavelfeldman** [comment]
I can't repro it:

![screenshot](https://user-images.githubusercontent.com/883973/147981685-4f700829-5aab-4fb3-b858-aaced1111f4c.png)

**Comment by aslushnikov** [comment]
Please re-file with a good repro that we can run locally & debug!
