### ISSUE TITLE
[Feature] Screenshot of specific element (with selector for example) instead of whole page

### ISSUE THREAD

**Issue by indapublic** [microsoft/playwright#10822]
If I missed this functionality please tell me.

I need to capture screenshot of specific element (mostly images with dynamic url like captcha). Is it possible?

I know that `screenshot` method contains `clip` attribute but it's some tricky I guess.

**Comment by dgozman** [comment]
[`Locator.screenshot()`](https://playwright.dev/docs/api/class-locator#locator-screenshot.) does that.
