### ISSUE TITLE
[Feature] Connect to remote running Playwright via local browser

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1082]
As an example, TestCafe has this implementation: https://devexpress.github.io/testcafe/documentation/recipes/test-on-remote-computers-and-mobile-devices.html

Imagine you are developing on a remote VM via ssh. VS Code Remote supports such a case, and it is [going mainstream](https://visualstudio.microsoft.com/services/visual-studio-online/). Now imagine you start Playwright on the remote VM, but you want to view the test in a local browser, by starting Playwright in headfull (i.e. non headless) mode. This is exactly what TestCafe support, and it would be cool if there was a way to do this with Playwright as well.

If you are working with Windows and VS Code, it is possible to achieve this via X11 (e.g. Xming) or a VNC solution (e.g. TigerVNC) to view the remote browser. But it would be much more elegant if you fire up the local Windows Chrome and connect to an IP remotely to view what was going. I.e. exactly how TestCafe does this.

Not to mention, if we look a bit in our crystal ball, I am sure @microsoft is aiming to supply Azure-based test plans using Playwright. I.e. "e2e testing in the cloud" so companies do not have to invest in their own testing infrastructure, [just like VS Code](https://visualstudio.microsoft.com/services/visual-studio-online/). In such a scenario users would love to be able to open their local browser to re-play failing test cases that were run in the cloud.

It'd be an amazing feature :)

**Comment by pavelfeldman** [comment]
Playwright requires specific versions of the browsers that are not installed on the client machine. So the client won't be able to debug locally. Screen cast would be the easiest way to make it work for now.

**Comment by thernstig** [comment]
I created the feature request in the hopes that it could be a long-term vision, I understand it's not feasible right now. Was hoping that maybe some thinking outside of the box could eventually come up with a proper solution. So I was hoping the issue could stay open till you figured something out, granted you even think this is a cool idea of course.

**Comment by thernstig** [comment]
I created the feature request in the hopes that it could be a long-term vision, I understand it's not feasible right now. Was hoping that maybe some thinking outside of the box could eventually come up with a proper solution. So I was hoping the issue could stay open till you figured something out, granted you even think this is a cool idea of course.

**Comment by thernstig** [comment]
@aslushnikov @pavelfeldman Is this something that can re-considered? It'd be a great feature for debugging purposes witH VS Code remote ssh.

**Comment by thernstig** [comment]
Testing to ping @dgozman for feedback

**Comment by dgozman** [comment]
@thernstig I do not think we'll support something like this in the near future. We assume the browser version and rely on it being colocated (on the same machine) as the playwright code itself.

If you are willing to run Playwright locally, look into [`launchServer`](https://playwright.dev/docs/api/class-browsertype/#browsertypelaunchserveroptions). With this, it should be possible to run the server locally, and connect to it from the remote Playwright. That said, the page url would have to be available to the locally running browser, as opposite to the remote VM.

**Comment by thernstig** [comment]
Ok, thanks for the answer!

**Comment by nicooprat** [comment]
Sorry to bump this one, is there anything new regarding this feature? I'm looking to migrate our E2E tests from Cypress to Playwright which offer a simpler API thanks to `await`. 

We currently run our app on VMs which we access through SSH with VScode remote. For now we have to code our tests locally because of Cypress UI ; so we code in two different environments and VScode windows...

Being able to code our tests directly on the same machine (and access the launched browser through SSH) would be a great DX improvement for our use case.

I took a look at https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server but I don't understand what we are supposed to use it :)

Thanks!

**Comment by 205g0** [comment]
> I do not think we'll support something like this in the near future.

@dgozman remote dev machines are not just the future but the current status for a huge part of us, so you should really go into this again. This is highly relevant especially for MS where web dev on native Windows isn't on eye level to dev on WSL2/macOS/Ubuntu. Starting some clunky xserver browser can'& be the solution.

Looking fwd to your feedback!

**Comment by 205g0** [comment]
@dgozman or as @nicooprat suggested: could you give us some basic hints how to use `launchServer`? That'd be great, thanks!

**Comment by eric-burel** [comment]
@dgozman The thing is that you may not have playwright installed on the machine that opens the browser. I've tried to run `chromium --remote-debugging-port=9222` but somehow I couldn't make it work on my machine... Accessing `localhost:9222` via browser gives nothing
I wish this was better documented, setting up debugging in VS Code or via remote connections feels difficult, and the API changes every other year so each project is a new start...

**Comment by LazioKarisma** [comment]
hi @eric-burel , did you have documentation on Java language ?Thank you.
