### ISSUE TITLE
[Question] New Context start in  SSO only

### ISSUE THREAD

**Issue by Krata4** [microsoft/playwright#10824]
Hello,

I have problem, that start of the new context is still in SSO not in incognito mode.
This is happaned on server only. On my laptom with same code it is working. 

Can you help me what can be different on the server site please?

Thanks
Jirka

**Comment by Krata4** [comment]
When I added argument on new browser --auth-server-whitelist="_"  it started work. 
Is it bug on Playwright?

**Comment by dgozman** [comment]
@Krata4 It is hard to understand what's going on. Do you have a repro script to share?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
