### ISSUE TITLE
[Question] Run tests in --headed mode through Docker container?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10831]
Hi everyone! 
I'm really new to Docker and I'm trying to run my playwright tests by building a Docker image using this Dockerfile:

```
# Prebuilt MS image
FROM mcr.microsoft.com/playwright:focal

WORKDIR ./

COPY package.json package-lock.json ./

RUN npm install

RUN  npx playwright install

COPY . .

CMD ["npx", "playwright", "test"]

```
and I'm trying to run my tests in --headed mode and I didn't quite understand how to set it from the docs. Could someone help me?

I'm running Docker Desktop into Windows 10, FYI.

**Comment by aslushnikov** [comment]
@DvDream just change your last line to use `xvfb-run`:

```
CMD ["xvfb-run", "npx", "playwright", "test"]
```

**Comment by DvDream** [comment]
Done but it doesn't work.. won't appear anything. I'm just running 

`docker run -it docker_example`

**Comment by dgozman** [comment]
@DvDream You won't see any browser window displayed when running in the docker, unless you set up some kind of "remote desktop" in the docker.
