### ISSUE TITLE
[Feature] Ability to register browsers

### ISSUE THREAD

**Issue by cameronhunter** [microsoft/playwright#10838]
Hi! At Netflix we have a custom "browser" named [Gibbon](https://youtu.be/5sETJs2_jwo?t=182) that runs on smart TVs, games consoles, set top boxes etc. Would it be possible to add the ability to register a custom `BrowserType`? Something along the lines of `registerBrowser(name: string, browserType: BrowserType): void` allowing usage such as:

```ts
import { registerBrowser } from 'playwright';
import gibbon from '@netflix/playwright-gibbon';
import { test } from '@playwright/test';

registerBrowser('gibbon', gibbon);

test.use({ browserName: 'gibbon' });

test('Gibbon test', async ({ page }) => {
  // Test assertions
});
```

**Comment by yury-s** [comment]
Is Gibbon based one of the tree major engines? If not then registering a new browser type for it would entail supporting another remote debugging protocol in Playwright. Public API for that would likely be bigger than current Playwright API (look at browser-specific bits for e.g. [WebKit](https://github.com/microsoft/playwright/tree/main/packages/playwright-core/src/server/webkit)) which would be a huge maintenance burden for the project.

**Comment by cameronhunter** [comment]
Thanks for the response @yury-s! Gibbon does support CDP connections. Ideally the BrowserType implementation would be owned and maintained by us and we'd dynamically register it with playwright.

**Comment by pavelfeldman** [comment]
As long as you are using the @playwright/test, you don't need changes to the library. You can [override](https://playwright.dev/docs/test-fixtures#overriding-fixtures) the browserType fixture and return your own fixture.

**Comment by cameronhunter** [comment]
@pavelfeldman this is interesting! I'll check into doing that and get back to you.

**Comment by pavelfeldman** [comment]
I'm not sure this helps you much though, but I'm not sure what your goals are either. If you'd like to reuse the logic that we use in our internal browser/context/page/expect, you'd need to clone the repo - all of that is the implementation detail, there is no contract there.

**Comment by cameronhunter** [comment]
There's a lot of context! We currently use an in-house functional testing framework for Gibbon but to bring us closer to the wider community functional testing approach, we've implemented `puppeteer-gibbon`. So far, this has been a successful but requires a lot of reimplementation of ecosystem packages such as `jest-environment-puppeteer` since they directly require `puppeteer` (vs our implementation).

With Playwright's first-class multi-browser support I was hoping that I'd be able to hook into it somehow and avoid this issue. My primary goal is to be able to use `@playwright/test` and other surrounding tools (and documentation!) off the shelf as much as possible.

I completely understand that adding different browsers is a very specialized use-case, but it can't hurt to ask :D

**Comment by mxschmitt** [comment]
Closing, for adding additional browsers a fork of Playwright might be the best solution for now.
