### ISSUE TITLE
[BUG] Context menu ("Shift+F10") triggers context menu on chromium, not on firefox

### ISSUE THREAD

**Issue by prushforth** [microsoft/playwright#10833]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: v13.13.0
- Browser: Firefox
- Extra: We're using jest-playwright, with jest describe/expect, playwright for e2e automation

Here's the test html:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Playwright Firefox ContextMenu bug</title>
    <meta charset="UTF-8">
    <script>
window.oncontextmenu = (e) => {
  e.preventDefault();
  document.querySelector('#mydiv').focus();
}    
    </script>
  </head>
  <body>
    <div id="mydiv" tabindex="0">This is a test</div>
  </body>
</html>
```

Here's the jest-playwright test that fails on firefox only, works on chromium:

```javascript
describe("Playwright Firefox Context Menu bug", () => {
  beforeAll(async () => {
    await page.goto(PATH + "playwright-contextmenu-firefox-bug.html");
  });

  afterAll(async function () {
    await context.close();
  });

  test("Context menu focus on keyboard shortcut", async () => {
    await page.pause();
    await page.keyboard.press("Shift+F10");
    const activeElementText = await page.evaluate(`document.activeElement.textContent`);
    await expect(activeElementText).toEqual("This is a test");
  });
});
```

**Describe the bug**
The bug is that the contextmenu event is not triggered by playwright on windows on firefox when using the "Shift+F10" keypress.  

As far as I can tell, the string "ContextMenu" should trigger the browser context menu as well, but it does not do so on either chromium or firefox.

If you run the above test you should get something like:

$ jest --verbose --noStackTrace

PASS browser: chromium E2E Testing test/e2e/mapml-viewer/playwrightFirefoxContextMenuBug.test.js (64.847 s)
  Playwright Firefox Context Menu bug
    √ Context menu focus on keyboard shortcut (56261 ms)

FAIL browser: firefox E2E Testing test/e2e/mapml-viewer/playwrightFirefoxContextMenuBug.test.js (17.354 s)
  Playwright Firefox Context Menu bug
    × Context menu focus on keyboard shortcut (9202 ms)

  ● Playwright Firefox Context Menu bug › Context menu focus on keyboard shortcut

    expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 4

    - This is a test
    +
    +     This is a test
    +   
    +

Thanks!  Really enjoying learning playwright.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
