### ISSUE TITLE
[Question] Is there any way to make better video quality?

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10855]
My viewport is 1920x1080 which is said to be default video size but there is scaling to 800x800, I can barely see what data is typed in input fields. Is there any way to make better video quality?

**Comment by ltsuda** [comment]
I think this relates to this comment here https://github.com/microsoft/playwright/issues/10818#issuecomment-989891583

**Comment by Kremliovskyi** [comment]
@ltsuda Thank you, it is working like this 
`const config: PlaywrightTestConfig = {
    use: {
        headless: true,
        viewport: { width: 1920, height: 1080 },
        ignoreHTTPSErrors: true,
        video: {
            mode: "retain-on-failure",
            size: { width: 1920, height: 1080 }
        },`

I suggest to add to documentation https://playwright.dev/docs/test-configuration#record-video or leave a link there to https://playwright.dev/docs/api/class-testoptions/#test-options-video

**Comment by dgozman** [comment]
> I suggest to add to documentation https://playwright.dev/docs/test-configuration#record-video or leave a link there to https://playwright.dev/docs/api/class-testoptions/#test-options-video

Great idea!
