### ISSUE TITLE
[BUG] Playwright requires manual install of browsers

### ISSUE THREAD

**Issue by Keeady** [microsoft/playwright#1085]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Mac

**Code Snippet**

```javascript
const { chromium } = require('playwright'); 

chromium.launch().then((browser: any) => {
      console.log("launched")
})
  .catch((e: any) => console.log(e))
```

**Describe the bug**
After installing playwright for the first time, I tried to run it and got the error
**Error: Chromium revision is not downloaded. Run "npm install"**

I am in a yarn exclusive environment so I am unable to run npm install. However, yarn install or yarn add do not resolve the issue.

Only way to solve it was 
**node node_modules/playwright/install.js**

**Comment by JoelEinbinder** [comment]
I cannot repro this with yarn v1.22.0, playwright v0.11.1

If you create a new project does it still happen? Maybe your node_modules got corrupted somehow.

**Comment by Xiphe** [comment]
I had the same issue but missed to note the `yarn` version I was on. Fixed it installing latest yarn `npm i -g yarn@1` (currently v1.22.0) and running `yarn install --force` in the project

**Comment by Xiphe** [comment]
After I `--force` installed, I installed another package using latest yarn. That caused the downloaded browsers to disappear and I needed to `--force`-install again.

**Comment by JoelEinbinder** [comment]
> After I `--force` installed, I installed another package using latest yarn. That caused the downloaded browsers to disappear and I needed to `--force`-install again.

Interesting! That is indeed a major issue. I’ll try to repro tomorrow.

Just to be clear, by latest yarn you mean 1.22, not 2.0 aka berry?

**Comment by Xiphe** [comment]
> Just to be clear, by latest yarn you mean 1.22, not 2.0 aka berry?

Yes that was misleading. I'm on yarn v1.22.0

### Quickfix:

Copy the `.local-*` folders somewhere else and link them after each install.

```
  ln -s ~/.local-chromium ./node_modules/playwright-core/.local-chromium
  ln -s ~/.local-firefox ./node_modules/playwright-core/.local-firefox
  ln -s ~/.local-webkit ./node_modules/playwright-core/.local-webkit
```
