### ISSUE TITLE
[Question]page.goto: net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by emyly** [microsoft/playwright#10851]
**Context:**
- Playwright Version:1.15.0
- Operating System: [ Mac]
- Node.js version: [14.18.1]
- Browser: [Chromium]
- 
![image](https://user-images.githubusercontent.com/26674260/145551200-703e021d-60a2-4376-bd32-703fa44276d6.png)

**Describe the bug**
Occasionally, run-to-end access to the test site fails, but the actual site is reachable，An error page. Goto: net: : ERR_CONNECTION_TIMED_OUT，sometimes there is no such problem，I wonder what the reason is, is it a network related problem？

**Comment by dgozman** [comment]
@emyly This `ERR_CONNECTION_TIMED_OUT` comes straight from the browser (Chromium in this case), and is indeed a network related problem.

**Comment by emsales** [comment]
@emyly have you solved this problem?

**Comment by libp** [comment]
@emyly  have you solved this problem?
