### ISSUE TITLE
[BUG] Retain retry history in Playwright Html report

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#10859]
I am running same test for 5-10 times in a row to make sure it is not flaky --repeat-each 5. When it is flaky and it fails few times then passes Playwright Html report stores video only of the last successfull run and the same with steps. It shows that 2 out 4 failed when you click on the failed you see all steps passed. Please store the results of each test run dont clear them, I can not debug flake))

**Comment by Nav-2d** [comment]
Related #10437

**Comment by dgozman** [comment]
I can repro this with the following test when running with `--repeat-each=5`. Seems to be an html reporter issue.

```js
test.only('sample', async ({}, testInfo) => {
  if (testInfo.repeatEachIndex === 2)
    throw new Error('oh my');
});
```
