### ISSUE TITLE
[Question] locator.click - Timed out even if only run for a millisecond?

### ISSUE THREAD

**Issue by thorleifjaocbsen** [microsoft/playwright#10856]
Sometimes it fails on a stupid selector like this:

Is there something I've done wrong? The "Save" button is there, but it times out? Default timeout is on 30 seconds is what I read in docs. is there a way to see what the actual timeout is?

![image](https://user-images.githubusercontent.com/8550684/145569475-04ac56ac-3b19-444a-8840-3dc7cd2b10d8.png)

**Comment by dgozman** [comment]
@thorleifjaocbsen Looks strange indeed. Here is [an overview](https://playwright.dev/docs/test-timeouts) of various timeouts in Playwright Test. If you could share a repro script, we'll be able to run ourselves and debug the issue.

**Comment by thorleifjaocbsen** [comment]
I found out that adding a timeout option to the buttons options actually worked. So I guess somewhere the timeout was set to sub ms? We have global timeout and timeout at "0" maybe somewhere it does not take that as indefinite? Well my problem is closed so we can probably close this. Must be a user-error.
