### ISSUE TITLE
[Feature]: Add description for elements 

### ISSUE THREAD

**Issue by arturmkr** [microsoft/playwright#10857]
### Feature request

In Selenide, it's possible to add description to the elements:
<img width="874" alt="Screenshot 2021-12-10 at 10 15 57" src="https://user-images.githubusercontent.com/14920279/145540900-aeb6fb9c-6516-44e0-a6e7-454b9acedbf4.png">

So, if using Allure Selenide ( https://mvnrepository.com/artifact/io.qameta.allure/allure-selenide ) in the report would be:
<img width="568" alt="Screenshot 2021-12-10 at 10 18 13" src="https://user-images.githubusercontent.com/14920279/145541044-953f33a8-ba76-4764-95e5-0368ac84bbc2.png">

I suggest to add ability to set description of Playwright elements  - Locator, ElementHandle, List[ElementHandle] , so Allure report would be able to use it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
