### ISSUE TITLE
[Question] Reporter with Playwright

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#10860]
Hi,

Is that possible to use Reporter capabilities with Playwright as a lib and not using @playwright/test ?
Indeed, we are moving our code to Playwright and we are still using cucumber-html-reporter. To simplify everything, I would like to remove cucumber-html-reporter.

Thank you

**Comment by dgozman** [comment]
@kamelbou Playwright reporters implement APIs specific to `@playwright/test`. I don't think you can use them with any other test runner.
