### ISSUE TITLE
[BUG] 1.17.1-focal dependency problems

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#10877]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Ubuntu focal
- Browser: Chrome
- Extra: 
- Images used:
    build: mcr.microsoft.com/playwright@sha256:fc2e1ab48b8fbabc940c0e6b6cdea0b54f03d109e564e03ac591ab6a7a994887

**Error**

```
+ apt-get install -y ./google-chrome-stable_current_amd64.deb
Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 google-chrome-stable : Depends: xdg-utils (>= 1.0.2) but it is not installable
                        Recommends: libu2f-udev but it is not installable
E: Unable to correct problems, you have held broken packages.
Failed to install browsers
Error: Failed to install chrome
```

**Describe the bug**

I get an error in bitbucket pipeline when using v1.17.1-focal (mcr.microsoft.com/playwright:v1.17.1-focal), however it was working with v.1.16.3-focal (mcr.microsoft.com/playwright:v1.16.3-focal)

**Comment by mxschmitt** [comment]
Adding `apt-get update` before installing the browsers should workaround it.

Relates #10615 which we might should release under 1.17.2.
