### ISSUE TITLE
[Feature] add locator method to return center point

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#10871]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

While, it is quite easy to implement locally, this can be a nice feature: Return the center point of an element. 

```
const elCenter: {x: number, y:number } = page.locator('div.some-class').centerPoint();
```
return the middle point of the bounding box.
Can be useful in emulate swiping.

**Comment by pavelfeldman** [comment]
For now, there is an easy workaround with `await page.locator('div.some-class').boundingBox();`. Let me keep it open and collect upvotes.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
