### ISSUE TITLE
[Question] how to use same request header from browser into the API request ?

### ISSUE THREAD

**Issue by amrsalem1** [microsoft/playwright#10884]
I there a method through which I can use the same request header in the browser session in my API request by default, I have used the method below but still not authorized however the token is correct

```
var token = await page.evaluate(() => {
            return 'Bearer ' + localStorage.accessToken
        });
        console.log(token);
        const _res = await request.post(`${baseURL}/feature`,
            {
                headers: {
                    Authorization: token
                },
                data: {
                    "name": D.featureName}
            });
```

**Comment by yury-s** [comment]
Your code looks correct, it will add `Authorization` header to the request. Perhaps the server expects some other headers too? Can you log the request that works and see what headers are there, maybe that will give you a clue?

**Comment by amrsalem1** [comment]
@yury-s  yes u are correct it was solved by adding some other header contents. now I'm in stucking in other issue 

how to get readable res.body() now I'm getting some output of bytes instead of json object

<img width="215" alt="Screenshot 2021-12-14 at 11 38 22" src="https://user-images.githubusercontent.com/89022647/145983090-6363c804-5cd1-41a8-a513-734d38b67b3b.png">

**Comment by amrsalem1** [comment]
update, its solved seems i have to use ,json() instead of body
