### ISSUE TITLE
[Question] Cannot generate Allure reports whithin Docker container?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#10885]
Hi, 
I'm trying to use Docker to run tests and generate reports , either Playwright native or Allure reports. When my "create allure report script" run the following command:

`npx allure generate /public/allure-reports/${date}-report/allure-results --clean -o /public/allure-reports/${date}-report/allure-report`

it throws me an error:

`ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.`

`Please set the JAVA_HOME variable in your environment to match the location of your Java installation. `

And this is not happening when I'm not using Docker. Here's my Dockerfile:

``` 
FROM mcr.microsoft.com/playwright:focal

WORKDIR ./

COPY package.json package-lock.json ./

RUN npm install npm@8.3.0

RUN npm install 

COPY . .

CMD ["npm", "run", "dev"]
```

how can I solve the problem? Thanks :)

**Comment by ltsuda** [comment]
As `allure-playwright` is a third-party reporter (https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md), you will probably need to install Allure2 and its dependencies on your Dockerfile.

Please, first try installing only `openjdk-8-jdk`. If this not work, take a look, at the documentation below.

https://github.com/allure-framework/allure2
https://docs.qameta.io/allure-report/gettingstarted/quickstart

**Comment by ltsuda** [comment]
As `allure-playwright` is a third-party reporter (https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md), you will probably need to install Allure2 and its dependencies on your Dockerfile.

Please, first try installing only `openjdk-8-jdk`. If not work, take a look, at the documentation below.

https://github.com/allure-framework/allure2
https://docs.qameta.io/allure-report/gettingstarted/quickstart

**Comment by mxschmitt** [comment]
Allure requires Java as @Ltsuda said. Also for Allure related questions, please file them against their repository since the code does not live in this repository: https://github.com/allure-framework/allure-js/issues
