### ISSUE TITLE
[BUG] Show the retry number in the list/line reporter (for the live view - not the error view)

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#10888]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: v16.13.0
- Browser: All

**Code Snippet**

```
test("Test 3: Failure Scenario - Navigate to Google page", async({ page }) => {
        // Navigate to google page.
        await page.goto("https://google.com");

        // Validate Google keyword is shown - Will fail as given wrong selector.
        await page.locator("[alt='GoogleId']").waitFor();
    })
```

In `playwright.config.test`, please set the retries more than `0` - Like - `retries: 1`

**Describe the bug**

**Issue - 1:** 
Console log doesn't show about any info regarding retry attempt for the failure test.

![image](https://user-images.githubusercontent.com/64302433/145869454-8d80b629-a82b-4b70-9e83-99916ace6456.png)

If we consider this scenario - here the test is failed in the first attempt but passed in the next attempt. But log doesn't show anything about retry attempt. And after all the test execution is completed, failure info is shown for the first attempt.
![image](https://user-images.githubusercontent.com/64302433/145869886-ec824a18-8e5f-4814-8850-6786bca3a44d.png)

**Issue 2:**
Failure logs are not shown in the console, when the tests are getting failing at the moment instead failure details are showing only when all the tests run execution is getting completed. So we have to wait for all the tests run completion to get the test failure log details.

![image](https://user-images.githubusercontent.com/64302433/145870766-8a79ed90-9deb-4314-866e-ed07281fb655.png)

**Comment by mxschmitt** [comment]
Regarding issue 1, what are your expectations? Retry does mean that it tries it X times, and if it succeeds in one of the following retries, it gets considered as a `flaky` test. Compared to the first screenshot, which is failing in both retries, it will consider it as `failing`, since in the following retries it's failing as well.

For the issue 2, using a different reporter like `--reporter line` should lead to a different behaviour. You can also use `--max-failures=0` to exit once the first error appears. Also usually you have `retries: process.env.CI ? 2 : undefined` inside your configs, so you locally don't have to deal with retries while debugging / writing tests.

**Comment by ukdas** [comment]
> Regarding issue 1, what are your expectations? Retry does mean that it tries it X times, and if it succeeds in one of the following retries, it gets considered as a `flaky` test. Compared to the first screenshot, which is failing in both retries, it will consider it as `failing`, since in the following retries it's failing as well.
> 
> For the issue 2, using a different reporter like `--reporter line` should lead to a different behaviour. You can also use `--max-failures=0` to exit once the first error appears. Also usually you have `retries: process.env.CI ? 2 : undefined` inside your configs, so you locally don't have to deal with retries while debugging / writing tests.

Thanks @mxschmitt  for looking into it and explanation in details. It's fine with test runner execution process & reporting method.

We are expecting to have the console's log as below - 

**Issue 1:** 
Where **Retry #number** will be shown in the log before performing retry attempt as below. Otherwise we need to compare the test title every time to check if the same test's retries happen in the next. And also by looking at the console's log, anyone can under stand it's a retry attempt execution performed.
![image](https://user-images.githubusercontent.com/64302433/145946339-e41850e4-7b7e-4d01-b08f-39f5e1c4615c.png)
