### ISSUE TITLE
[BUG] onResponse Handler Not Picking Up 404 Errors on Invalid Ajax URLs

### ISSUE THREAD

**Issue by flying59** [microsoft/playwright#10894]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Windows 10 (dev) and Windows Server 2019 (test)
- Node.js version: None
- Browser: Firefox (headed)
- Extra: Sencha UI with Java backend

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```html
<!DOCTYPE html>
<html>
<body>

<div id="demo">

<h2>Ajax Test</h2>

<button type="button" onclick="loadDoc('mySite/missing.css', myFunction)">Run Ajax
</button>
</div>

<script>
function loadDoc(url, xFunction) {
  const xhttp=new XMLHttpRequest();
  xhttp.onload = function() {xFunction(this);}
  xhttp.open("GET", url);
  xhttp.send();
}

function myFunction(xhttp) {
  document.getElementById("demo").innerHTML =  xhttp.responseText;
}
</script>
</body>
</html>
```

**Describe the bug**

I am using Playwright to perform "smoke tests" across multiple web pages. These smoke tests check for javascript errors, and potential ajax issues due to missing CSS or javascript files and ajax errors caused by missing or inop web services (404 or 500 errors). The page.onResponse handler successfully detects any 500 errors but is not finding 404 errors generated when an invalid CSS or javascript URL is passed in an ajax call (as shown in the code sample above).

**Comment by mxschmitt** [comment]
I tried the following test which works fine for me:

```java
package org.example;

import com.microsoft.playwright.*;
import java.nio.file.Paths;

public class Test {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.webkit().launch();
      Page page = browser.newPage();
      page.navigate("https://example.org/");
      page.onResponse(response -> System.out.println("<<" + response.status() + " " + response.url()));
      page.evaluate("const xhr = new XMLHttpRequest();" +
        "xhr.open('GET', '/foobar');" +
        "xhr.send();");
      page.waitForTimeout(5000);
    }
  }
}
```

do you have any URL or a full snippet which you can share with us?

**Comment by flying59** [comment]
Thanks for the quick reply!
Our dev environment is isolated but I think I can give you a sample that hopefully mimics our ajax call. I have created a Sencha fiddle that is representative of our invalid Ajax calls. The Sencha fiddle URL is https://fiddle.sencha.com/fiddle/3hgc. (Note: To view the Sencha fiddle editor with the embedded ajax code you can go to https://fiddle.sencha.com/#view/editor&fiddle/3hgc). The Ajax attempts to run an invalid web service causing a 404 error. Here's an untested code snippet that is similar to what we're attempting:
```
package org.example;

import com.microsoft.playwright.*;
import java.nio.file.Paths;

public class Test {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.firefox.launch(new BrowserType.LaunchOptions().setHeadless(false));
      Page page = browser.newPage();
      page.navigate("https://fiddle.sencha.com/fiddle/3hgc");
      page.onResponse(response -> {
         if (response.status() == 404) {
            System.out.println("Error: " + response.status() + " " + response.statusText());
         }
      }
    }
  }
}
```

**Comment by yury-s** [comment]
You are adding listener after the navigation finished and the script has already started running try adding it earlier:

```java
package org.example;

import com.microsoft.playwright.*;
import java.nio.file.Paths;

public class Test {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.firefox.launch(new BrowserType.LaunchOptions().setHeadless(false));
      Page page = browser.newPage();
      // Add response listener before starting the navigation
      page.onResponse(response -> {
         if (response.status() == 404) {
            System.out.println("Error: " + response.status() + " " + response.statusText());
         }
      });
      page.navigate("https://fiddle.sencha.com/fiddle/3hgc");
    }
  }
}
```

**Comment by flying59** [comment]
Thank you for the suggestion Yury. Moving the onResponse call earlier did successfully find 404 errors caused by Ajax URLs pointing to invalid/missing CSS and javascript files. However, it still does not find the 404 errors caused by ajax attempting to call an invalid web service for example. 

Just curious if you are able to successfully run the code snippet above? The URL https://fiddle.sencha.com/fiddle/3hgc sets up an ajax call to a web service on the sencha fiddle page that doesn't exist. The onResponse handler appears not to pick up the resulting 404 error on my dev environment.

**Comment by yury-s** [comment]
> Just curious if you are able to successfully run the code snippet above? The URL https://fiddle.sencha.com/fiddle/3hgc sets up an ajax call to a web service on the sencha fiddle page that doesn't exist. The onResponse handler appears not to pick up the resulting 404 error on my dev environment.

The test finishes before the response is received (the failing request is apparently sent after the navigation finishes). You can wait for that particular url using [waitForResponse](https://playwright.dev/java/docs/api/class-page#page-wait-for-response):

```java
      Response response = page.waitForResponse("https://fiddle.sencha.com/sample/DoesntExist*",
        () -> page.navigate("https://fiddle.sencha.com/fiddle/3hgc"));
      System.out.println(response.url() + " => " + response.status());
```
