### ISSUE TITLE
[BUG] undocking dev tools to a separate window freezes chrome when paused on a breakpoint

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#10897]
**Context:**
- Playwright Version: 1.17.1
## System:
 - OS: Windows 10 10.0.18363
 - Memory: 653.33 MB / 15.78 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

**Code Snippet**

**Describe the bug**

1. create a playwright script eg.
    ```javascript
    await page.goto('https://google.com/')
    await page.click('asdf')
    ```
2. set a breakpoint in your IDE on the `page.click` line
3. run the script in headed mode
4. once it hits the breakpoint, hit f12 in chrome
5. select the undock button
    ![image](https://user-images.githubusercontent.com/57028336/145906311-ab63ac1a-a6a9-4f35-a756-ff7325c7ec5f.png)

chrome will then freeze

**Comment by mxschmitt** [comment]
This is a known limitation, we intercept DevTools inside Playwright and you debug the Node.js process which halts the entire event loop so no communication can happen on that end. Marking as p3 and collecting feedback for now.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
