### ISSUE TITLE
[Feature] Add ergonomic randomness to selecting an option on <select>.

### ISSUE THREAD

**Issue by spartanatreyu** [microsoft/playwright#10906]
[locator.selectOption(values[, options])](https://playwright.dev/docs/api/class-locator#locator-select-option) allows developers to test the selection of a dropdown in a `<select>` element.

Using the following html:

```html
<select class="select" name="personal-title" id="personal-title" aria-label="Personal Title">
	<option selected="" disabled="">Personal Title</option>
	<option value="mr">Mr</option>
	<option value="ms">Ms</option>
	<option value="mrs">Mrs</option>
	<option value="mx">Mx</option>
</select>
```

We can choose which option is selected with something like:

```ts
test('Registered user can access and complete questionnaire', async ({ page }) => {
    // register account
    // ...
    await page.locator('#personal-title').selectOption({'value': 'mr'});
    // ...
    
    // access questionnaire
    // ...
    
    // complete questionnaire
    // ...
});
```

Currently `values` can be set to:

- `value` <string> Matches by option.value. Optional.
- `label` <string> Matches by option.label. Optional.
- `index` <number> Matches by the index. Optional.

---

For some tests, it can be helpful to select a random item in the dropdown as a kind of fuzz-test.

To select a random option, we need some `Math.random()` logic and we need to know how many options exist for the `<select>` element. It can certainly be done, but not in a neat single line that's easy to understand at a glance.

I propose adding something new to `values`:

- `random`: `'any' | selectRandomOptions`.

## `'random': 'any'`

To set the `<select>` element to any selectable option (i.e. those that are not disabled), set the following:

```ts
await page.locator('#personal-title').selectOption({ 'random': 'any' });
```

To set the `<select>` element to any option (regardless of selectability/clickability), set the following:

```ts
await page.locator('#personal-title').selectOption({ 'random': 'any' }, { 'force': true });
```

In the above example there should be a 1 in 5 chance that the first option (Personal Title) remains the selected option.

## `'random': selectRandomOptions`

To select multiple options simultaneously, the developer can use `'random': selectRandomOptions` with selectRandomOptions being defined as:

```ts
type selectRandomRangeOptions = { minSelected?: number, maxSelected?: number };
type selectRandomSelectionOptions = { minIndex?: number, maxIndex?: number };
type selectRandomOptions = { chance?: number, range?: selectRandomRangeOptions, selection?: selectRandomSelectionOptions };
```

- `minIndex?: number` Select a random element with an index greater than `minIndex`. Negative values count backwards from the last child like `Array.at()`. Default value: `-1`.
- `maxIndex?: number` Select a random element with an index less than `maxIndex`. Negative values count forwards from first child like `Array.at() with positive numbers`. Default value: number of child `<option>` elements.
- `minSelected?: number` Ensure at least `minSelected` options have been selected. Default `0`.
- `maxSelected?: number` Ensure no more than `maxSelected` options have been selected. Default value: number of child `<option>` elements, or `1` when the `<select>` element does not have the `multiple` attribute.
- `chance?: number` Gives each child `<option>` element a 1 in n chance of being selected. Default value: number of child `<option>` elements.

These options can be combined for multiple useful purposes. All examples are using the following example html:

```html
<select id="countries" name="countries" multiple>
    <option value="AF">Afghanistan</option>
    <!-- ... -->
    <!-- about 200 other country options -->
    <!-- ... -->
    <option value="ZW">Zimbabwe</option>
</select>
```

To select five different countries:

```ts
await page.locator('#countries').selectOption({ random: { minSelected: 5 } });
```

To select five different countries from within the first 10 options:

```ts
await page.locator('#countries').selectOption({ random: { minSelected: 5, maxIndex: 10 } });
```

To select five different countries from within the first 10 options after the first:

```ts
await page.locator('#countries').selectOption({ random: { minSelected: 5, minIndex: 1, maxIndex: 11 } });
```

To give each of the first 10 options after the first option a 1 in 10 chance of being selected:

_Note:_ This can result in all or none of the first 10 options after the first option becoming selected

```ts
await page.locator('#countries').selectOption({ random: { chance: 10, minIndex: 1, maxIndex: 11 } });
```

To give each of the first 10 options after the first option a 1 in 10 chance of being selected with at least one option being selected:

_Note:_ This can result in all of the first 10 countries after the first becoming selected, but not none of them.

```ts
await page.locator('#countries').selectOption({ random: { chance: 10, minIndex: 1, maxIndex: 11, minSelected: 1 } });
```

---

**P.S.** I'm not set on any of this, I just want an easier way to "_fuzz_-test" some big forms.

**Comment by pavelfeldman** [comment]
You can do that in 2 lines. First line returns all values, second picks random and passes it into select. That way you have a flexible way of specifying the random strategy!
