### ISSUE TITLE
Nested Selectors

### ISSUE THREAD

**Issue by nate-buck** [microsoft/playwright#10910]
Can I nest pseudo-class selectors? For example is

`div.myCssClass:has(li:text-is('some text'))`

a valid selector? If so, am I correct to assume the resulting element locator/handle would represent the (first) matching div element with the class 'myCssClass'?

**Comment by nate-buck** [comment]
If the above is valid, would chaining also be valid within the pseudo-class? E.g., is

`div.myCssClass:has(ul >> li:text-is('some text'))`

a valid selector?

**Comment by pavelfeldman** [comment]
Pseudo selectors (:foo) are a part of the CSS selector language, you can only use them in the css selectors.

https://playwright.dev/docs/selectors

**Comment by pavelfeldman** [comment]
You can use capture to mix selector engines and achieve similar results.

https://playwright.dev/docs/selectors#intermediate-matches

**Comment by nate-buck** [comment]
Thanks for your answers, Pavel.

**Comment by mxschmitt** [comment]
Closing since its answered. For further questions, please open a new issue, thanks!
