### ISSUE TITLE
[Question] Problem with locator.allInnerTexts

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#10916]
I find this peculiar. We changed some code to use locators and `allInnerTexts` in a function called `headers()` which retrieves all header elements in a table (left side in picture). Previously we used `Promise.all(...header.innerText())` (right side in picture)

![image](https://user-images.githubusercontent.com/30827238/146045994-0e062f92-b284-427f-ac7e-f7299e58cf1d.png)

Before locators, it worked to match e.g. using this:

```js
// Works without locators (right side in picture)
expect(headers).toStrictEqual(['Name', 'Value']);

// Does not work with locators (left side in picture)
expect(headers).toStrictEqual(['Name', 'Value']);

// but this works with locators (left side in picture)
expect(headers).toEqual(['Name', 'Value']);
```

Why would `toStrictEqual` fail with `locator.allInnerTexts()` but by getting each elements innerText() separately? Is it a bug?

Printing the array shows now difference.

**Comment by pavelfeldman** [comment]
You should use web assertions:

```js
await expect(locator).toHaveText(['a', 'b']);
```

**Comment by thernstig** [comment]
We are not using Playwright Test yet, but expect to soon. But since we are using locators, I cannot see the difference between the two options explained above. Why would `locator.allInnerTexts()` behave differently?

**Comment by mxschmitt** [comment]
I'd recommend to migrate to Playwright Test. Regarding the difference between `toEqual` and `toStrictEqual` see here: https://jestjs.io/docs/expect#tostrictequalvalue

Also using a debugger like Visual Studio Code would help to find out how the actual array of `allInnerTexts ` looks like.

**Comment by thernstig** [comment]
> I'd recommend to migrate to Playwright Test. 

We intend to do this. But we still use a Page Obejct Model kind of API, where we wrap a table component in it. We have a function getHeaders which returns headers. So the actual expect() statement would still be receiving an array and not a locator.

I am going to close this then as it was more of a question of if there is a known difference not documented. But there is not I'll ask the developer working on this for more diligent work to find out. The contents of the array has been simplify console.logged and she saw no difference, hence the confusion.

(unfortunately I have just been a proxy in writing this issue and I'd have checked this more closely myself if I had suspected it to be a bug)
