### ISSUE TITLE
[Question] How to delete cookie by name ?

### ISSUE THREAD

**Issue by vsravuri** [microsoft/playwright#10919]
Currently Playwright supports deleting all the cookies **_browserContext.clearCookies()_**.

In my test, i have a use case to delete a cookie by name.

Appreciate if you could provide a JS example.

**Comment by mxschmitt** [comment]
There is a feature request for it already, folding into https://github.com/microsoft/playwright/issues/10143

**Comment by rszabo50** [comment]
const cookies: Cookie[] = (await this.page!.context().cookies()).filter((cookie) => {
      return cookie.name !== cookieName;
    });
    await this.page!.context().clearCookies();
    await this.page!.context().addCookies(cookies);

**Comment by MuzammilCareaxiom** [comment]
const cookieName = 'lastActivity';
    const cookies = (await this.page.context().cookies()).filter(cookie => cookie.name !== cookieName);
    await page.context().clearCookies();
    await page.context().addCookies(cookies);
    
    JS Example

**Comment by mxschmitt** [comment]
@drilon241 please file a separate issue. We'll triage it separately.
