### ISSUE TITLE
Request: Equivalent of the Cypress Clock function

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#10939]
With Cypress, you can manipulate the browser time in a test via the clock() function. This is very useful for testing time based logic such as idle logout messages etc.

For example, you can speed up time by calling it like so: 

```
cy.clock(new Date());
cy.tick(600*1000);
//assert some logic for when browser session is idle for 10 mins
```

I just wondered if there were any plans to add something like this to Playwright? Right now, it feels like one of the killer features of Cypress Playwright currently lacks.

**Comment by Kremliovskyi** [comment]
I asked the same question they answered me here is a feature request https://github.com/microsoft/playwright/issues/6347
This is working for me
```
async function fakeTime(context: BrowserContext) {
    await context.addInitScript({
        path: path.join(__dirname, "../node_modules/sinon/pkg/sinon.js"),
    });
    await context.addInitScript(() => {
        // @ts-expect-error __clock does not exist
        window.__clock = sinon.useFakeTimers({
            now: new Date(2021, 10, 1).getTime(),
        });
    });
}
```

**Comment by mxschmitt** [comment]
Closing and folding into #6342
