### ISSUE TITLE
[BUG] Frame methods does not respect test.slow() 

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#10932]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: 14.18.0
- Browser: All?

**Code Snippet**

```javascript
test('Some slow test', async ({ browser }) => {

    test.slow();

    const frameElement = await page.waitForSelector(PDFTronSelectors.PDFTronAppFrame);

    const PDFTRON = await frameElement.contentFrame();

    await Promise.all([
	PDFTRON.waitForSelector(PDFTronSelectors.progress),
	PDFTRON.waitForLoadState()
    ]);

    await PDFTRON.waitForSelector(PDFTronSelectors.progress, {
	state: 'hidden'
    });
});
```

**Describe the bug**

We have some test that sometimes take more time to load, especially in Firefox and Webkit, so we mark it as `test.slow()`, which, according to docs, should triple the default timeouts. But it still fails with log:
```
frame.waitForSelector: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector "[data-element="progressModal"]" to be hidden
      selector resolved to visible <div data-element="progressModal" class="Modal Progre…>…</div>
    ============================================================
``` 
So, the timeout somehow does not work for `frame` instances.

**Comment by mxschmitt** [comment]
@creage could you create a small repro for us with your expectations and whats not working as intended?

I tired with the following but was not able to replicate it:

```ts
import { Page, test} from '@playwright/test'

test.describe.serial('use the same page', () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('runs first', async () => {
    test.slow()
    await page.setContent('<iframe src="https://example.com"></iframe>');
    const iframe = await page.$('iframe');
    const content = await iframe.contentFrame();
    await content.waitForSelector("text=mario") // leads to a timeout here, because 90 seconds is reached. (30 * 3 = 90)
  });
});
```

**Comment by creage** [comment]
@mxschmitt Could it be because I'm waiting for element to disappear, and not just usual `visible` state? 
```js
await PDFTRON.waitForSelector(PDFTronSelectors.progress, {
    state: 'hidden'
});
```
Because this is the line where PW exists after 30 seconds.

**Comment by mxschmitt** [comment]
I'd recommend to use web-first assertions with frame locators instead of all the custom waitForSelector logic, this should simplify your tests and probably get rid of some potential races, see here:

```ts
const iframe = page.frameLocator(PDFTronSelectors.PDFTronAppFrame);
const progress = iframe.locator(PDFTronSelectors.progress);
await expect(progress).toBeVisible();
await expect(progress).toBeHidden();
```

See here:

- https://playwright.dev/docs/api/class-framelocator
- https://playwright.dev/docs/api/class-locator
- https://playwright.dev/docs/test-assertions

**Comment by creage** [comment]
@mxschmitt this is all great, but how does it help with tripling the timeouts? 😉

**Comment by mxschmitt** [comment]
Yeah we need a repro, otherwise we can't act on it - with using `state: hidden` it also works as expected for me. Can you provide us a repro in form of a GitHub repo / or a small script so we are able to run it on our machine? Thanks!

**Comment by yury-s** [comment]
I cannot reproduce it either (with `state: 'hidden'`). We need more information to act on this report. Please file a new bug report once you have a repro and link to this issue.

**Comment by creage** [comment]
@mxschmitt @yury-s Well, it still doesn't work for me here.

I'm using my locators in the **separate** .ts file that I'm importing in the test file, and selectors in that **imported file** are still using default, 30 seconds, timeout.

The only way I was able to make them respect slowness is by explicitly defining
```js
test.use({ timeout: 90000 });
```
in the top of my test file.

@mxschmitt 
Using `expect().toBeVisible()` is even worse, as these assertions are defaulted to 5 seconds ONLY - they don't respect default `actionTimeout` at all!
