### ISSUE TITLE
[Feature] Junit Reporter - Adding custom testsuite properties

### ISSUE THREAD

**Issue by JuanCruzTrinidad** [microsoft/playwright#10942]
Hi! This time we come to propose custom properties in test suite return to xml file.
Use the fixture in jest-junit reporter. 
https://www.npmjs.com/package/jest-junit
![image](https://user-images.githubusercontent.com/53027244/146187765-086f3fd2-ff81-4e6f-8ce7-77ca9d17679d.png)

My team use datadog for ci analytics test and they read properties in suite and properties for test case.

https://docs.datadoghq.com/continuous_integration/setup_tests/junit_upload/#providing-metadata-through-property-elements

![image](https://user-images.githubusercontent.com/53027244/146209058-d661ffeb-0d9b-4b2f-b785-ad3bb04f963c.png)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
