### ISSUE TITLE
[BUG] Can't install due to playwright.azureedge.net being down

### ISSUE THREAD

**Issue by ImportTaste** [microsoft/playwright#10959]
https://playwright.azureedge.net is currently down, I checked to make sure it wasn't just me using https://downforeveryoneorjustme.com

Without being able to reach it, the command to install playwright fails.

**Comment by mxschmitt** [comment]
The CDN is not down, maybe your connection/firewall/proxy does prevent accessing it?
https://playwright.azureedge.net/builds/index.html works for me.

What kind of error do you get?

**Comment by ImportTaste** [comment]
It's back up.

**Comment by alshakero** [comment]
It is down now.

**Comment by ybongard** [comment]
yup all network down ^^ 

https://azure.status.microsoft/en-gb/status

`sudo ifdown -a`
