### ISSUE TITLE
[BUG] waitForNavigation([options]) isn't working correctly 

### ISSUE THREAD

**Issue by dssnoha** [microsoft/playwright#10967]
**Context:**
- Playwright Version: 1.15.2
- Operating System: Windows
- Node.js version: 16.7.0
- Browser: All

with headless tests i have a test that checks if any of the responses fails but i have a page where you get to click and wait for navigation even though the page has a response that fails the test still pass when i use debug the test fails. I tried using this and it's didn't work out 

```
await page.waitForNavigation({timeout : 1000});
```

i also used this but it didn't work out as well 
```
await page.waitForNavigation({waitUntil: 'networkidle'});
```
it's like waitForNavigation not listing to the options ?

**Comment by mxschmitt** [comment]
Usually you combine `waitForNavigation` with a `Promise.all` and some interaction, e.g. `page.click` see here: https://playwright.dev/docs/api/class-page#page-wait-for-navigation

Would it be possible that you can share with us a repro to demonstrate the issue?

**Comment by dssnoha** [comment]
is it possible to do it without having to use any kind of interaction ? because i only need to check the page response after navigation and that's it!

**Comment by yury-s** [comment]
> is it possible to do it without having to use any kind of interaction ?

What will trigger the navigation in that case?

> because i only need to check the page response after navigation and that's it!

Please share your test case, otherwise we can only guess what it does and may give you wrong advise.
