### ISSUE TITLE
[Docs] Suggestion for clarification of the beforeAll behaviour when combined with .parallel

### ISSUE THREAD

**Issue by mauricedoepke** [microsoft/playwright#10966]
The [docs for the beforeAll](https://playwright.dev/docs/api/class-test#test-before-all) hook state that it is run once for the whole test group:

> Declares a beforeAll hook that is executed once before all tests. When called in the scope of a test file, runs before all tests in the file. When called inside a test.describe(title, callback) group, runs before all tests in the group.

It turns out, that this statement has an exception. If the beforeAll hook is combined with ".parallel", the beforeAll hook seems to behave the same as the beforeEach hook. The [parallel docs](https://playwright.dev/docs/api/class-test#test-describe-parallel) mention this very briefly.

> Each of the parallel tests executes all relevant hooks.

To me this is unintuitive and it also caused me quite some headache, when debugging my tests.
I would propose to mention this a bit more explicitely, both in the ".parallel" and in the beforeAll part of the documentation.
I would proprose the following changes:
> Declares a beforeAll hook that is executed once before all tests. When called in the scope of a test file, runs before all tests in the file. 
When called inside a test.describe(title, callback) group, runs before all tests in the group. 
**When called inside a test.describe.parallel(title, callback) however, runs before each tests in the group, like a beforeEach hook.**

> Each of the parallel tests executes all relevant hooks. **This means that a beforeAll hook will behave like a beforeEach hook in this situation.**

Note: The bold part just highlights my additions, I do not propose to make it bold in the docs.

**Comment by mxschmitt** [comment]
Seems like it was already clarified by #10446 so closing for now.
