### ISSUE TITLE
[BUG] Cannot start electron application with devtools enabled

### ISSUE THREAD

**Issue by josh-thompson13** [microsoft/playwright#10964]
**Context:**

- Playwright Version: 1.16.2
- Operating System: MACos Big Sur 11.4
- Node.js version: Node.js v14.17.6, 
- Browser: Electron
- Extra: This is an electron application

**Code Snippet**

```
// Initialise
const process = require('process');
const { _electron: electron } = require('playwright');
const { waitForDebugger } = require('inspector');

(async () => {
    // Launch Electron app.
    const electronApp = await electron.launch({executablePath:'/Users/james/Electron_Testing/tashelix.app/Contents/MacOS/tashelix'});
    
    // Evaluation expression in the Electron context.
    const appPath = await electronApp.evaluate(async ({ app }) => {
    // This runs in the main Electron process, parameter here is always
    // the result of the require('electron') in the main app script.
    return app.getAppPath();
  });
  console.log(appPath);

  // Get the first window that the app opens, wait if necessary.
  const window = await electronApp.firstWindow();
  // Print the title.
  console.log(await window.title());
```
**Describe the bug**

I cannot launch the application with dev tools enabled. I have tried to launch with args and env when I use electron.launch, which launches the application with devtools enabled, but then test steps do not get executed. I just need to be able to launch with dev tools and have steps execute.

I get this bug when code is started with dev tools enabled. Waiting for selector "[placeholder="Enter Customer Code *"]".

Here is the **Code Snippet** that launches the application with devtools enabled. 

```
const electronApp = await electron.launch({env:{'HELIX_TEST':'true'},executablePath:'/Users/james/Electron_Testing/tashelix.app/Contents/MacOS/tashelix'});
```

Thanks!

**Comment by dgozman** [comment]
@josh-thompson13 We won't be able to help without a full repro. Could you share your electron app (or some reduced version of it) in addition to the Playwright script?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by dominic-simplan** [comment]
We had the same issue.
In our case, `electronApp.firstWindow()` sometimes returned the DevTools window, sometimes the actual main window. If the DevTools window is returned, the test waits indefinitely for the selector.

We worked around this problem by opening the DevTools manually afterwards:

```
const browserWindow = await electronApp.browserWindow(window);
browserWindow.evaluate(async (app: BrowserWindow) => {
   app.webContents.openDevTools();
}); 
```

Not sure if this is something which could be fixed in playwright...?
