### ISSUE TITLE
Can I get the system date and format accordingly in Playwright typescript

### ISSUE THREAD

**Issue by tmazumder** [microsoft/playwright#10971]

**Comment by mxschmitt** [comment]
Playwright with TypeScript, runs Node.js so you can leverage the `Date` object there. See here for reference: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date#examples

`console.log(new Date().toString())`

**Comment by tmazumder** [comment]
Using the above, we get the output as in this form - Fri Dec 17 2021 01:18:59 GMT+0530 (India Standard Time)
can we do date formatting like - 17 Dec, 2021 01:18 PM

**Comment by mxschmitt** [comment]
See here for some resources:
- https://www.w3schools.com/js/js_date_formats.asp
- https://date-fns.org/v2.27.0/docs/format

Closing since this is not about Playwright.
