### ISSUE TITLE
[BUG] page supplied by playwright test does not use recordVideo config

### ISSUE THREAD

**Issue by foneandrew** [microsoft/playwright#10980]
Context:

Playwright Version: 1.17.1
Operating System: Mac
Node.js version: 16.4.0
Browser: All

(I tried using a few older versions, and it seems that the issue first appeared in v 1.14.0)

Relevant config snippet from `playwright.config.ts`:

```js
projects: [
    {
      name: 'Chrome',
      use: {
        browserName: 'chromium',
        headless: true,
        contextOptions: {
          storageState: 'sessionState.json',
          recordVideo: { dir: `output/Chrome/recordings/unnamed` }
        }
      },
    },
```

On versions before 1.14.0 this would result in videos being recorded to `output/Chrome/recordings/unnamed` (which would then be moved to a different folder by some other code). After 1.14.0 videos are recorded to `./test-results/` instead.

We were using the page object provided by the playwright test runner

```js
test('Does a thing', async ({ page }, testInfo) => {
  // ...
});
```

When we ditch the supplied page and create our own (using the supplied contextOptions) recording starts saving to the correct directory (`output/Chrome/recordings/unnamed`) again:

```js
test('Does a thing', async ({ browser, contextOptions }, testInfo) => {
  const context = await browser.newContext(contextOptions);
  const page = await context.newPage();

  // ...
});
```

Seems like there is a bug to do with the provided page not using contextOptions properly? Although interestingly storageState seems to be working as the tests still pass (they rely on the storageState for the login tokens).

**Comment by ltsuda** [comment]
I might be wrong, but I think you're mixing two different video configurations. One is the `recordVideo` from the `BrowserContext` options and the other is the Record Video using the configuration file.

If you want to change the video output repository, you should use the `contextOptions` creating a `newContext` like your last piece of code. But if you want to use the provided Page fixture, you need to use the `use: { video: "option" }` (see the last link of this comment).

Please see the difference on the links below:

Here you can change the video output directory. Maybe you could use a global setup or override the Page/Context fixtures to setup a custom directory for the videos. The guys from Playwright team should be able to give you a good example.
https://playwright.dev/docs/api/class-browser#browser-new-context
https://playwright.dev/docs/videos
 
Here is the record video using the playwright's configuration file that saves on the `test-results` directory for each project/browser type (chrome/firefox/webkit) in individual sub directories.
https://playwright.dev/docs/test-configuration#record-video
https://playwright.dev/docs/test-configuration

**Comment by foneandrew** [comment]
Ah thanks you nailed it.

Yes we had some extra config tucked away at the bottom of the config file. Removing the `video: 'on'` fixed everything.

```js
{
  // ..
  use: {
    video:  'on'
  }
}
```

Thanks again for you help!
