### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#10989]
**Context:**
- Playwright Version: ToT
- Operating System: macOS
- Node.js version: 16
- Browser: All

**Describe the bug**

When using `--repeat-each 100` the test-case hashes get calculated incorrectly and by the entires get merged inside the HTML report. 

e.g. when there are 99 passing and 1 failing, you won't be able to view the 1 failing since they all get the same ID assigned.

Maybe re-use test case ID which already contains the repeat index: https://github.com/microsoft/playwright/blob/0d54afab9c5e4bafff185c7ea7f8fff0013bf59a/packages/playwright-test/src/project.ts#L81

HTML reporter does its own soup: https://github.com/microsoft/playwright/blob/0d54afab9c5e4bafff185c7ea7f8fff0013bf59a/packages/playwright-test/src/reporters/raw.ts#L198

**Comment by pavelfeldman** [comment]
This has been fixed earlier today.
