### ISSUE TITLE
[Feature] Steps without explicit body?

### ISSUE THREAD

**Issue by btd** [microsoft/playwright#10994]
Hi, thanks for great lib.

We are migrating our E2E projects now to @playwright/test from CodeceptJs and one of our test engineers asked if it is possible to write `test.step` without body (because of previous `I.say` syntax).

Something like:
```ts
test("Test title", async ({ page }) => {
   step('Step 1');
  .....


   step('Step 2');
 ....
})
```

I could imagine this to be working in the similar way it is now. Not sure it is possible to determine body steps.
By idea body is everything between two `step` calls. On event `step` call we can await [complete](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/testType.ts#L197) of previous step in current test.

**Comment by mxschmitt** [comment]
It is not possible, each step needs to be awaited (you have a missing await) and has a body, otherwise it would never show which step it is running since its going instantly going through it. See here for more information: https://playwright.dev/docs/api/class-test#test-step

**Comment by mxschmitt** [comment]
Closing since answered.
