### ISSUE TITLE
[BUG] Locator/ Text Selector  fails to consider leading and trailing spaces in text

### ISSUE THREAD

**Issue by gopi19** [microsoft/playwright#10997]
**Context:**
- Playwright Version: 1.17
- Operating System: Windows
- Node.js version:12.19.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: None

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();

  // Click text=Add widget
  await page.click('text= Add widget ');


  // ...
})();
```

**Describe the bug**
![image](https://user-images.githubusercontent.com/27012616/146569825-4ed10d71-b8b9-4731-b161-1d4eeb03d135.png)

I am trying to find an element with text but the text found to have leading and trailing spaces. Due to this the locator fails to find the element.

**Comment by pavelfeldman** [comment]
The following test works for me, could you clarify what's expected vs what is happening?

```js
it.only('should work with leading and trailing spaces', async ({ page }) => {
  await page.setContent(`<button> Add widget </button>`);
  await expect(page.locator('text=Add widget')).toBeVisible();
  await expect(page.locator('text= Add widget ')).toBeVisible();
});
```

**Comment by aslushnikov** [comment]
I'll close this for now; feel free to re-file with a good repro!
