### ISSUE TITLE
[BUG] Using certain mp4 video sources causes webkit to crash

### ISSUE THREAD

**Issue by trotzig** [microsoft/playwright#11009]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac OS Monterey 12.0.1
- Node.js version: 16.13.0
- Browser: Webkit

**Code Snippet**

Here's a repo that reproduces the issue: https://github.com/happo/playwright-webkit-crash-repo

```javascript
const { test } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.evaluate(`
    document.body.innerHTML = \`
    <video playsinline autoplay style="width:320px;height:320px;">
      <source src="https://www.html5rocks.com/en/tutorials/video/basics/devstories.mp4" type='video/mp4;codecs="avc1.42E01E, mp4a.40.2"'/>
    </video>
    \`;
  `);
  await new Promise(p => setTimeout(p, 2000));
  await page.evaluate('document.querySelector("video")');
});
```

**Describe the bug**

When injecting a `<video>` that has an mp4 video `<source>` element in webkit, the browser crashes with this error in the debug logs: 

```
pw:browser [pid=56713][err] 2021-12-18 12:22:11.259 com.apple.WebKit.GPU.Development[56724:3338674] *** Terminating app due to uncaught exception 'NSInvalid
ArgumentException', reason: '-[WebCoreNSURLSessionTaskTransactionMetrics _privacyStance]: unrecognized selector sent to instance 0x7feaeb10ade0' +0ms
```

This seems to only happen in webkit on a Mac. I've got linux instances in CI that has no problem processing this scenario. 

If I switch to a different source, e.g. `webm`, the video plays fine and there is no crash. Also, loading the video in a regular Safari window will not cause a crash (Video can be found here: https://www.html5rocks.com/en/tutorials/video/basics//) -- however the video isn't played. Opening the video directly in Safari makes it play however, just enter this url in the location bar: https://www.html5rocks.com/en/tutorials/video/basics/devstories.mp4

**Comment by mxschmitt** [comment]
Looks related to https://github.com/microsoft/playwright/issues/10892

**Comment by yury-s** [comment]
Doesn't crash on Catalina (10.15) but always fails on Monterey (12.0.1) for me.

**Comment by yury-s** [comment]
Looks like https://github.com/WebKit/WebKit/commit/0dd1d952a98728e65b76b7b91356f6bc901d854c added `WebCoreNSURLSessionTaskTransactionMetrics _privacyStance` to [CFNetworkSPI](https://github.com/WebKit/WebKit/commit/0dd1d952a98728e65b76b7b91356f6bc901d854c#diff-ea69972d63b32da0207a87f06d2d7a419500a53b7ec5e5228122406098171ccb) which is enabled at compile time if the OS version >=12. Since we don't build on macOS 12 today the property is missing on the instance but apparently some OS code tries to access it which causes the error.

**Comment by aslushnikov** [comment]
build for monterey is tracked here: https://github.com/microsoft/playwright/issues/11031
