### ISSUE TITLE
slowMo option exercised through command line or in playwright.config ?

### ISSUE THREAD

**Issue by sunjeet-khokhar** [microsoft/playwright#11005]
Hey folks, 

This is regarding a debugging use-case ..
for debugging purposes I want to control the replay speed "globally" for a test run ( rather than from within the test file) , either through the command line or from the config file , but I this does not seem to be allowed  

Is it even possible ? 

e.g. --> 
if on the command line i try to do " npx playwright test --slowMo=2000
i get the unknown option error 

and can not seem to do this in the playwirght.config file either 

![image](https://user-images.githubusercontent.com/15244739/146618621-5b5fe53f-c0ef-4134-bd5e-fa3ea1cd3dde.png)

**Comment by gopi19** [comment]
![image](https://user-images.githubusercontent.com/27012616/146629954-a428d6fe-af13-4f27-bcd6-dff980b65902.png)

**Comment by mxschmitt** [comment]
You need to put it inside launch options, see here: https://playwright.dev/docs/test-configuration#more-browser-and-context-options

**Comment by sunjeet-khokhar** [comment]
thanks for that , yes i was missing put it inside the launch options ! 
so this config works now ...

![image](https://user-images.githubusercontent.com/15244739/146655875-f623407f-776b-47af-b8d2-05e6fbc952d9.png)

**Comment by mrwwalmsley** [comment]
Is there any reason why it couldn't be made available as a command line parameter?

There are often times when I'm running tests and it would be nice to be able to try different speeds without having to go in an edit the config.

**Comment by aljorhythm** [comment]
> Is there any reason why it couldn't be made available as a command line parameter?
> 
> There are often times when I'm running tests and it would be nice to be able to try different speeds without having to go in an edit the config.

you can read values from environment variables

```
    use: {
        locale: "en-GB",
        trace: "on-first-retry",
        headless: !!process.env.CI,
        launchOptions: {
            slowMo: process.env.PLAYWRIGHT_SLOW_MO || 0,
        },
    },
```

run 
`make PLAYWRIGHT_SLOW_MO=300 test-e2e`
