### ISSUE TITLE
[Question] Selecting Children of an Element

### ISSUE THREAD

**Issue by DhairyaBahl** [microsoft/playwright#11011]
### Description 

I am unable to get the count of number of child elements of a DOM element. I would like to know that how can I get the count when I get the reference to that element using ```page.$('selector')``` ! How to use this to access its child elements ?

### What I tried 

I tried using using evaluate f() on page but I don't think it is the right way ! There must be some way to do the same using ElementHandle or using Locator !

**Comment by ltsuda** [comment]
```javascript
const parent = page.locator('parent-selector')
const child = parent.locator('child-selector')
const countChild = await child.count()
or 
const countChild = await parent.locator('child-selector').count()
```

**Comment by DhairyaBahl** [comment]
> ```js
> const parent = page.locator('parent-selector')
> const child = parent.locator('child-selector')
> const countChild = await child.count()
> or 
> const countChild = await parent.locator('child-selector').count()
> ```

I will try this next time. This time I managed with evaluate. Thanks. 😄
