### ISSUE TITLE
How can I use the browser library to interact with iframe and tinymice

### ISSUE THREAD

**Issue by Lanre-Ikuesan** [microsoft/playwright#11018]
I am new to robotframework-browser. I am trying to write a test to select frame and then type text into the text area as shown in the screenshot below. I easily would have used the select frame keyword if i was using selenium library. Please I need some help with this.  I will be really grateful.
<img width="646" alt="Issue" src="https://user-images.githubusercontent.com/92743286/146738198-6134fb16-563c-4582-95de-124e5d23019f.PNG">

**Comment by dgozman** [comment]
See #8943 for an example, and a related issue.
