### ISSUE TITLE
[Question] Change screenshot directory for visual comparisons

### ISSUE THREAD

**Issue by dipanshubhanot** [microsoft/playwright#11017]
Instead of storing the screenshots next to the .spec.ts file, I wanted all the screenshots to be placed in a separate folder ([project-root]/tests/screenshots). 

Is such a configuration possible?

**Comment by mxschmitt** [comment]
There is `snapshotDir`: https://playwright.dev/docs/api/class-testconfig#test-config-snapshot-dir

**Comment by mxschmitt** [comment]
Closing since answered
