### ISSUE TITLE
[BUG] route.fulfill causes missing responseReceivedExtraInfo events

### ISSUE THREAD

**Issue by eliassorensen** [microsoft/playwright#11019]
## System:
 - OS: Linux 5.15 Pop!_OS 21.10
 - Memory: 17.39 GB / 31.10 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.2 - /usr/bin/node
 - npm: 6.14.15 - /usr/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/bin/bash
## npmPackages:
 - playwright: 1.17.1 (but same in 1.18.0-alpha-dec-20-2021)

**Code Snippet**

```import { chromium } from "playwright";

(async () => {

  const browser = await chromium.launch();

  const context = await browser.newContext();

  await context.route("**/*", async route => {
    const response = await context.request.fetch(route.request());


    let body = await response.text();
    
    //await route.continue(); // 👈 Using this instead of route.fulfill will work as expected

    route.fulfill({
      response,
      body,
      headers: {
        ...response.headers()
      }
   });
  });

  const page = await context.newPage();
  const session = await context.newCDPSession(page);
  await session.send("Network.enable");
  session.on("Network.responseReceivedExtraInfo", payload => {
    console.log('responseReceivedExtraInfo', payload);
  });
  
  await page.goto("https://example.com", { waitUntil: "load" });

  await page.close();
  await context.close();
  await browser.close();
})();
```

**Describe the bug**

When using `route.fulfill` we no longer receive any `responseReceivedExtraInfo` events from CDP. We use this to monitor set-cookie headers and refer them back to specific requests / initiators using CDP events.

If you try to remove the commented out route.continue(), you can see that it will then work, and log the correct events.

If fulfilling the route causes no `responseReceivedExtraInfo` to be received, how can we then modify the request body and still keep those?

**Comment by eliassorensen** [comment]
Just to illustrate - it also causes the `headersArray` in the page response to not contain the `set-cookie` header.

```
import { chromium } from "playwright";

(async () => {

  const browser = await chromium.launch();

  const context = await browser.newContext();

  await context.route("**/*", async route => {
    const response = await context.request.fetch(route.request());


    let body = await response.text();
    
    // await route.continue(); // 👈 Using this instead of route.fulfill will work as expected

    route.fulfill({
      response,
      body,
      headers: {
        ...response.headers()
      }
   });
  });

  const page = await context.newPage();

  page.on("response", async page => {
      // 👇 this should contain the set-cookie header, but only does if we're not using route.fulfill
      console.log(await page.headersArray());
  });
  
  await page.goto("https://srnsn.com/tests/set-cookie.php", { waitUntil: "load" });

  await page.close();
  await context.close();
  await browser.close();
})();
```

With `route.fulfill`, above code returns:
```
[
  { name: 'date', value: 'Mon, 20 Dec 2021 08:48:59 GMT' },
  { name: 'content-type', value: 'text/html; charset=UTF-8' },
  { name: 'transfer-encoding', value: 'chunked' },
  { name: 'connection', value: 'close' },
  { name: 'x-powered-by', value: 'PHP/7.4.27' },
  { name: 'vary', value: 'User-Agent' },
  { name: 'cf-cache-status', value: 'DYNAMIC' },
  {
    name: 'expect-ct',
    value: 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
  },
  {
    name: 'report-to',
    value: '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=qgJqVyaSegELWDGmqKRchA%2FWEzvSKposcMwR12Fvbby%2B67XkulUk0k62atXGox%2FSE61fXhZbByumqvY72OD43eWrzcok33w23hkMZIbjjSger3mTTwdwPWv2uwM%3D"}],"group":"cf-nel","max_age":604800}'
  },
  {
    name: 'nel',
    value: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
  },
  { name: 'server', value: 'cloudflare' },
  { name: 'cf-ray', value: '6c079d66799a4a55-FRA' },
  { name: 'content-encoding', value: 'br' },
  {
    name: 'alt-svc',
    value: 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400'
  }
]
```

Without `route.fulfill`:
```
[
  { name: 'date', value: 'Mon, 20 Dec 2021 08:52:35 GMT' },
  { name: 'content-type', value: 'text/html; charset=UTF-8' },
  { name: 'x-powered-by', value: 'PHP/7.4.27' },
  { name: 'set-cookie', value: 'Hello=World' }, 👈👈👈👈
  { name: 'vary', value: 'User-Agent' },
  { name: 'cf-cache-status', value: 'DYNAMIC' },
  {
    name: 'expect-ct',
    value: 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"'
  },
  {
    name: 'report-to',
    value: '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=OyWEEEbTqTk0bt53jhl%2BkLJRZQ%2FG%2FKyV5hL1lpBYKDSHE167eCNNynaAmkvH8t4B0KXvBS3HUDFBw1BoQv0Nhq8OFnO9ShMGbxZzLolGKMY%2FQmCaPR0C%2BX8On9U%3D"}],"group":"cf-nel","max_age":604800}'
  },
  {
    name: 'nel',
    value: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}'
  },
  { name: 'server', value: 'cloudflare' },
  { name: 'cf-ray', value: '6c07a2aa0da16925-FRA' },
  { name: 'content-encoding', value: 'br' },
  {
    name: 'alt-svc',
    value: 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400'
  }
]
```

**Comment by yury-s** [comment]
> When using route.fulfill we no longer receive any responseReceivedExtraInfo events from CDP. 

CDP is not a part of Playwright. Please file a bug in Chromium if you want to change the behavior.

> Just to illustrate - it also causes the `headersArray` in the page response to not contain the `set-cookie` header.

There was a change in how cookies are handled in chromium in v1.15 (see [release notes](https://github.com/microsoft/playwright/releases/tag/v1.15.0)). Now to get all headers you need to use [Response.allHeaders()](https://playwright.dev/docs/api/class-response#response-all-headers), it will contain `set-cookie` headers too.

**Comment by eliassorensen** [comment]
@yury-s 

> > When using route.fulfill we no longer receive any responseReceivedExtraInfo events from CDP.
> 
> CDP is not a part of Playwright. Please file a bug in Chromium if you want to change the behavior.

I know that I should probably not have mentioned that I use CDP directly at first - but it it still a problem _without_ using CDP (I know you're using it internally as well, but for a normal user, it is abstracted away behind your own API).

I will probably create a new ticket for the actual problem in Playwright.
 
> > Just to illustrate - it also causes the `headersArray` in the page response to not contain the `set-cookie` header.
> 
> There was a change in how cookies are handled in chromium in v1.15 (see [release notes](https://github.com/microsoft/playwright/releases/tag/v1.15.0)). Now to get all headers you need to use [Response.allHeaders()](https://playwright.dev/docs/api/class-response#response-all-headers), it will contain `set-cookie` headers too.

The release notes you link to is not mentioning that `headersArray` should not be used. On the contrary, it just lists it as a new helper function together with `allHeaders`.

Your docs also doesn't mention anything about `headersArray` not will contain set-cookie headers.[ It explicitly says](https://playwright.dev/docs/api/class-response#response-headers-array) that it does, but they are not lower cased compared to `allHeaders`:

> An array with all the request HTTP headers associated with this response. Unlike response.allHeaders(), header names are NOT lower-cased. Headers with multiple entries, such as Set-Cookie, appear in the array multiple times.

And again: Using `route.fulfill` will NOT return any set-cookies headers in responses. No matter if I use `headersArray` or `allHeaders`. It is not documented anywhere that `route.fulfill` would cause these to not be set correctly, so either it's a bug, otherwise it's missing documentation.

Will post a new issue and link from this.

**Comment by eliassorensen** [comment]
Created this: https://github.com/microsoft/playwright/issues/11035

**Comment by yury-s** [comment]
> The release notes you link to is not mentioning that `headersArray` should not be used. On the contrary, it just lists it as a new helper function together with `allHeaders`.
> 
Sorry for the confusion, I meant `response.headers()` is deprecated, `response.headersArray` is one of the new methods and should contain all headers. There is a bug regarding set-cookie handling though: https://github.com/microsoft/playwright/issues/4987 and looking at the test it seems that it is still a problem in webkit (not in chromium though).

> And again: Using `route.fulfill` will NOT return any set-cookies headers in responses. No matter if I use `headersArray` or `allHeaders`. It is not documented anywhere that `route.fulfill` would cause these to not be set correctly, so either it's a bug, otherwise it's missing documentation.
> 
> Will post a new issue and link from this.

Thank you, let's continue there.
