### ISSUE TITLE
[BUG] checkbox check/uncheck fails if page reloads once checkbox state changes

### ISSUE THREAD

**Issue by grybykm** [microsoft/playwright#11026]
**Context:**
- Playwright Version: 1.17.1

**Describe the bug**

Check/uncheck method fails with `Element is not attached to the DOM` exception if page reloads on checkbox state changes.

**Log**

```
waiting for selector "[data-testid="select-all"] label[for="select-all"]"
selector resolved to visible <label for="select-all" class="checkbox-label" data-tes…>…</label>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
checking that element receives pointer events at (502.79,246.15)
element does receive pointer events
performing click action
click action done
waiting for scheduled navigations to finish
navigations have finished
Element is not attached to the DOM
```

**Comment by grybykm** [comment]
The element is not removed from a user point of view, it takes less than 100ms to reload the page and the checkbox appears in appropriate state.
I can't see why playwright can't wait for the element to exist instead of throwing an exception immediately.

I've built my own implementation of the checkbox temporary that works and doesn't throw an exception 
```
export class CheckboxElement {
    readonly label: Locator
    readonly input: Locator

    constructor(label: Locator, input?: Locator) {
        this.label = label
        this.input = input || label.locator('input[type="checkbox"]')
    }

    async setChecked(checked: boolean) {
        await this.label.waitFor({ state: 'visible' })
        await this.input.waitFor({ state: 'attached' })

        await waitUntil(async () => { // a simple waitUntil function
            if ((await this.isChecked()) !== checked) {
                await this.label.click()
                return false
            }
            return true
        })
    }

    async check() {
        await this.setChecked(true)
    }

    async uncheck() {
        await this.setChecked(false)
    }

    async isChecked() {
        return this.input.isChecked()
    }
}
```

**Comment by yury-s** [comment]
> The element is not removed from a user point of view, it takes less than 100ms to reload the page and the checkbox appears in appropriate state.

Depending on the machine load and the hardware performance I can image a situation where it takes significantly longer than 100ms. This is different from the current assumption that `setChecked` in Playwright makes which is that the checkbox must be checked right after the click. We can add some heuristics in the future if there is high demand for this kind of scenarios but for the time being the recommendation is to use `click()` instead and then have custom logic that validates if the checkbox gets into the checked state soon enough.

**Comment by yury-s** [comment]
We could introduce an option that would adjust how long the method waits for the element to become checked.

**Comment by Octopus134** [comment]
nearly same problem for me: the dropdown with the checkbox closes immediately after checking intentionally, so the test afterwards fails.
I can use click(), but the charme of having check()/uncheck() is that the result is clear other than by click() - even if not tested afterwards. So I like to have an option to disable the after-unchecking check.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
