### ISSUE TITLE
[Feature] support global installation of browsers

### ISSUE THREAD

**Issue by Xiphe** [microsoft/playwright#1102]
I'm currently working on different projects where I play around with playwright. Downloading the latest browser versions for each single project is slowing me down and also uses a lot of disk-space.

~~Due to https://github.com/microsoft/playwright/issues/1085 I also need to re-download the browsers over and over again whenever I update my node_modules.~~ (Update: is fixed)

I like [the way Cypress manages binary installs](https://docs.cypress.io/guides/getting-started/installing-cypress.html#Advanced) by allowing configuration through environment variables.

I'd be happy to investigate further and propose an API/implementation if you think this is a good idea.

**Comment by pavelfeldman** [comment]
You will be able to set up interception and initial scripts on the browser context. So all the popups and click navigations that open in new pages will share interception, initial scripts and emulation parameters.

Will this work for you?

**Comment by Xiphe** [comment]
Another use-case would be pre-build docker containers / orbs for CircleCI. Where the browser binaries (+ deps) come with the container and it's exposing a Environment Variable so that when i `npm install playwright` it just uses the bins from the container.

**Comment by hugomrdias** [comment]
Until pw has support for this you can do a little wrapper like this https://github.com/hugomrdias/playwright-test/blob/master/src/utils.js#L172
And use 'env-paths' package to find the system's cache folder.
