### ISSUE TITLE
[Feature] Taking full page screenshots on test failures

### ISSUE THREAD

**Issue by antpingelli** [microsoft/playwright#11029]
I am currently using the `screenshot: 'only-on-failure',` configuration but that does not take full page screenshots, so I am having trouble seeing some aspects of my UI that are helpful for debugging. Is there another way to easily take a screenshot when a test fails? I see the configuration does not allow the option to take a full page screenshot

https://github.com/microsoft/playwright/blob/93ad12978ce97bb03db4129cab64caf93d6e02b0/packages/playwright-test/src/index.ts#L243-L250

**Comment by yury-s** [comment]
This is not currently possible via the test config even though we have [fullPage](https://playwright.dev/docs/api/class-page#page-screenshot-option-full-page) option in `page.screenshot`. Converting this report to a feature request.

**Comment by yury-s** [comment]
Merging this request into https://github.com/microsoft/playwright/issues/9983
