### ISSUE TITLE
[BUG] HTMLReport does not show test details when using an inlined sourcemaps

### ISSUE THREAD

**Issue by flunderpero** [microsoft/playwright#11028]
**Context:**
## System:
 - OS: macOS 12.0.1
 - Memory: 1.89 GB / 64.00 GB
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
 - npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: 1.18.0-alpha-dec-20-2021 => 1.18.0-alpha-dec-20-2021

**Describe the bug**

This is a follow-up to #10732 .

This [repo](https://github.com/flunderpero/playwright-bug-10732) demonstrates the bug. I tried to simplify our code and test setup as much as possible. Run the tests with `npm install && npm run build && npm run test`.

The problem is two-fold (see the comments in the code) and involves tests using `test.step`. We use esbuild to transpile our Typescript code. If we use `sourcemap: "inline"` then tests that are inside a `test.describe` will not show up in the HTML report details (you get a JS error), tests (including test steps) outside any `test.describe` work as expected.

If you use external sourcemaps , the test details are available, but the the stack traces don't show the actual TS source code but the transpiled code.

We use inline sourcemaps and the esbuild transpilation for everything we do with Typescript (running production Node services, WebdriverIO tests, Jest tests, etc.) and it works really well. If you spot something we might be doing wrong, I would really appreciate your input.

**Comment by yury-s** [comment]
Can reproduce it. Clicking first test (with describe) opens blank page with exception in the console:

![image](https://user-images.githubusercontent.com/9798949/146843897-f7f3d394-2ec9-4097-984e-ea6f128c498d.png)

**Comment by flunderpero** [comment]
Could you point me in some direction where to look to fix this?
