### ISSUE TITLE
[Question]What's the best thing to do if I want to synchronize operations between multiple browsers?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#11023]
I want to access browser A. For example, I enter my account password and log in. My other browsers B and C all repeat the operations of my browser A. what should I do?

**Comment by yury-s** [comment]
You can run the commands on each of the browser instances in turn:

```js
  const pages = [pageA, pageB, pageC];
  async function forAllPages(action) {
    for (const page of pages)
      await action(page);
  }
  await forAllPages(page => page.fill('id=username', 'my_user'));
  await forAllPages(page => page.fill('id=password', 'my_password'));
```

**Comment by bbhxwl** [comment]
> You can run the commands on each of the browser instances in turn:
> 
> ```js
>   const pages = [pageA, pageB, pageC];
>   async function forAllPages(action) {
>     for (const page of pages)
>       await action(page);
>   }
>   await forAllPages(page => page.fill('id=username', 'my_user'));
>   await forAllPages(page => page.fill('id=password', 'my_password'));
> ```

If I want to open the browser and operate in the browser, another browser will change. It's hard, isn't it? At present, this situation is to operate all pages in full code.
