### ISSUE TITLE
[Feature] Allow launching chromium with different dev-tools placement / location

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#11025]
Personally, it's a little annoying for me that dev-tools are launched on the right side. Although it's a low priority feature but it would be great that in the future there would be an option to launch chromium with different dev-tools dock location. 

Similarly to what apparently puppeteer allows: https://github.com/puppeteer/puppeteer/issues/1797#issuecomment-629704019

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by MariuzM** [comment]
I want this also
