### ISSUE TITLE
[BUG] Unable to navigate pressing Enter on ubereats

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#11022]
**Context:**
- Playwright Version: 1.7.1
- Operating System: macOS
- Node.js version: 14
- Browser: Chromium
- Extra: [any specific details about your environment]

I was taking a look at [this question on StackOverflow](https://stackoverflow.com/questions/70415952/why-does-playwright-not-change-url-once-button-is-clicked-on-uber-eats)

```
await page.goto('https://www.ubereats.com/ca');
await page.fill('#location-typeahead-home-input', 'address');
await page.keyboard.press('Enter');
```

Although there are many workarounds to suggest, if you press enter, that will trigger a navigation, and that doesn't happen if you do `press('Enter')` (or `page.press`). 

`codegen` generates this code that doesn't work either.

```
// Go to https://www.ubereats.com/ca
await page.goto('https://www.ubereats.com/ca');
// Click [placeholder="Enter delivery address"]
await page.click('[placeholder="Enter delivery address"]');
// Fill [placeholder="Enter delivery address"]
await page.fill('[placeholder="Enter delivery address"]', 'address');
// Press Enter
await Promise.all([
  page.waitForNavigation(/*{ url: 'https://www.ubereats.com/ca/feed?pl=JTdCJTIyYWRkcmVzcyUyMiUzQSUyMkFkZHJlc3MlMjBCZWFjaCUyMFJlc29ydCUyMiUyQyUyMnJlZmVyZW5jZSUyMiUzQSUyMkNoSUpJWlVFQTFnVFh6NFJZS3JOdV9aY2wyZyUyMiUyQyUyMnJlZmVyZW5jZVR5cGUlMjIlM0ElMjJnb29nbGVfcGxhY2VzJTIyJTJDJTIybGF0aXR1ZGUlMjIlM0EyNS4wNzIxMiUyQyUyMmxvbmdpdHVkZSUyMiUzQTU1LjEyNjkzNDIlN0Q%3D' }*/),
  page.press('[placeholder="Enter delivery address"]', 'Enter')
]);
```

**Comment by Pavel-2004** [comment]
I have came up with a solution to this issue in my stackoverflow thread please check it out. 
[https://stackoverflow.com/questions/70415952/why-does-playwright-not-change-url-once-button-is-clicked-on-uber-eats?noredirect=1#comment124485567_70415952](url)

**Comment by yury-s** [comment]
The page loads something asynchronously and if 'Enter' is pressed to quickly it will fail to navigate. So this is an actual bug on the web page. To confirm that, just insert a pause before pressing 'Enter' and it will successfully navigate:

```js
  await page.goto('https://www.ubereats.com/ca');
  await page.fill('#location-typeahead-home-input', 'address');
  await new Promise(r => setTimeout(r, 1000));
  await page.keyboard.press('Enter');
```
