### ISSUE TITLE
[REGRESSION]: No longer able to import formatters from @playwright/test/lib/test/reporters/base

### ISSUE THREAD

**Issue by esaminu** [microsoft/playwright#11024]
Hey guys, thanks for the great library.

I'd like to report a possible regression. I was previously able to import `formatTestTitle` and `formatFailure` from `@playwright/test/lib/reporters/test/base` and I am no longer able to do so. Is this intentional or is there now a new way to do this?

**Context:**
- GOOD Playwright Version: 1.13.1
- BAD Playwright Version: 1.14.0
- Operating System: Mac OS

**Code Snippet**

```javascript

const { formatTestTitle, formatFailure } = require("@playwright/test/lib/test/reporters/base");
```

**Comment by pavelfeldman** [comment]
Our base formatters are an implementation detail. Once we could annotate them as such in package.json, we did it.

**Comment by yury-s** [comment]
Closing per the comment above, the formatters are not a part of the public API and can change / be removed any moment. Please file a feature request if you need particular functionality to be added to the public API.
