### ISSUE TITLE
[Question] How to prevent new tabs not loading while debugging?

### ISSUE THREAD

**Issue by vasyop** [microsoft/playwright#11027]
I'm debugging this snippet with VS code:

```
const { chromium, firefox, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });  // Or 'firefox' or 'webkit'.
  const page = await browser.newPage();
  await page.goto('http://example.com');
  // other actions...
  await browser.close();
})();
```

While execution is paused by the debugger (just before `await browser.close();`), if I use the browser manually to navigate to another address, it works as expected. However, if I open a new tab, it never loads. Similarly, if I attach to a running chrome instance via `connectOverCDP`, the already opened tabs work as expected, but new tabs, don't. Also, opening any electron window (including dev tools) doesn't work. 

This can be worked around by freeing the event loop. (stepping over something like `await new Promise(r => setTimeout(r, 1000))` will unstuck the new tab.

**Comment by yury-s** [comment]
I can reproduce this. When the browser is controlled by Playwright, every time a new page (tab) is created (whether manually or programmatically) it is initially paused and will wait for an explicit command from Playwright to resume (`Runtime.runIfWaitingForDebugger` in CDP). Before Playwright sends that command the page will remain unusable. When Playwright script itself is paused none of such commands are handled and the newly created pages will remain paused. Once Playwright is resumed it will resume all the new pages as well.

I'm closing this report as there are no plans on changing this behavior.
