### ISSUE TITLE
[BUG] route.fulfill causes missing set-cookie headers on responses

### ISSUE THREAD

**Issue by eliassorensen** [microsoft/playwright#11035]
## System:
 - OS: Linux 5.15 Pop!_OS 21.10
 - Memory: 17.39 GB / 31.10 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.2 - /usr/bin/node
 - npm: 6.14.15 - /usr/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/bin/bash
## npmPackages:
 - playwright: 1.17.1 (but same in 1.18.0-alpha-dec-20-2021)

**Code Snippet**

```javascript
import { chromium } from "playwright";

(async () => {

  const browser = await chromium.launch();

  const context = await browser.newContext();

  await context.route("**/*", async route => {
    const response = await context.request.fetch(route.request());


    let body = await response.text();
    
     //await route.continue(); // 👈 Using this instead of route.fulfill will work as expected

    route.fulfill({
      response,
      body,
      headers: {
        ...response.headers()
      }
   });
  });

  const page = await context.newPage();

  page.on("response", async page => {
      console.log(await page.allHeaders());
  });
  
  await page.goto("https://srnsn.com/tests/set-cookie.php", { waitUntil: "load" });

  await page.close();
  await context.close();
  await browser.close();
})();
```

**Describe the bug**

When using `route.fulfill`, set-cookie headers are no longer returned in the response. 

If I'm using just `route.continue`, I correctly get the `'set-cookie': 'Hello=World',` header returned. The moment I use `route.fulfill` this is no longer present.

Using firefox instead of Chrome works perfectly, and will return the set-cookie header no matter whether I'm using `route.fulfill` or not.

**Comment by eliassorensen** [comment]
Logging `response.headers()` right above `route.fulfill` correctly shows the set-cookie header. 

The cookie is also set in the browser. Even though `page.allHeaders` is not showing the cookie..

**Comment by yury-s** [comment]
Related issue: https://github.com/microsoft/playwright/issues/4987

**Comment by eliassorensen** [comment]
Hi there,

Are there any updates on this one? We are really in a broken state on some parts of our application using `route.fulfill`, not getting set-cookies headers on the responses.

**Comment by mindplay-dk** [comment]
The comment [here](https://github.com/microsoft/playwright/issues/11035#issuecomment-998552157) seems to point to a CDP issue? Can you confirm whether that's the case?

If so, should we file an issue with Chromium or will you?

**Comment by eliassorensen** [comment]
I've made a test on our end using Chromium (Playwright), Firefox and Chrome stable.

It works perfectly in Firefox, but in Chromium and Chrome, it does _not_. The cookie set in `route.fulfill` is not present in the response.

Weird thing is, that using `context.cookies()`, the cookie is indeed set _in_ the browser. 

I'm using this code to `route.fulfill`:
```
await page.route('**/*', async route => {
    await route.fulfill({
        status: 200,
        headers: {
            'set-cookie': 'a=b', // Sets a=b in the response. So it should come up in response headers,
            'bogus-header': 'hello'
        },
        contentType: 'text/plain',
        body: ''
    });
});
```

And making the request like this:
```
const response = (await page.goto(`http://localhost:${options.port}/`, { waitUntil: "load" }))!;
const headers = await response.allHeaders();

let browserCookies = await context.cookies();
console.log('Browser cookies after request:', detailed(browserCookies));
console.log('Response headers', detailed(headers))
```

Getting the following test results:
```
-----[ can return set-cookie header in route.fulfill (chromium) ]-----
Version: 99.0.4812.0
Browser cookies after request: [
  {
    sameSite: 'Lax',
    name: 'a',
    value: 'b',
    domain: 'localhost',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false
  }
]
Response headers { 'bogus-header': 'hello', 'content-type': 'text/plain' }

-----[ can return set-cookie header in route.fulfill (firefox) ]-----
Version: 95.0
Browser cookies after request: [
  {
    name: 'a',
    value: 'b',
    domain: 'localhost',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false,
    sameSite: 'None'
  }
]
Response headers {
  'set-cookie': 'a=b',
  'bogus-header': 'hello',
  'content-type': 'text/plain'
}

-----[ can return set-cookie header in route.fulfill (chrome-stable) ]-----
Version: 97.0.4692.99
Browser cookies after request: [
  {
    sameSite: 'Lax',
    name: 'a',
    value: 'b',
    domain: 'localhost',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false
  }
]
Response headers { 'bogus-header': 'hello', 'content-type': 'text/plain' }
```

As you can see, the cookie is set in all browsers. But only in Firefox, it's present in the response headers. 

However, the weird thing is, that the `bogus-header` is getting into all browsers' response headers.

@yury-s we would like to figure out how to deal with this. Is it a known issue? Is it something that will be fixed? If not, please update your documentation, as your API gives different results across different browsers.

**Comment by mindplay-dk** [comment]
I should add that I've actually tested this in Chrome Canary (Windows, desktop) which did *not* have this issue.

Using Protocol Monitor, I was able to confirm that the "Local override" feature in DevTools does use the CDP interception feature - I was able to set a local override for a request that returns a `Set-Cookie` header, which I had then expected would *not* display in the "Network" tab, but it *does*.

I was able to see the `Set-Cookie` header in the CDP message using "Protocol monitor" in DevTools as well, even with the local override performing request interception.

So it would appear this is not (or at least not always) a bug in Chrome. Something is causing the missing header. If I had to guess, a possible cause could be different configuration - whether DevTools is sending a command that causes it work, or Playwright is sending a command that causes it to fail.

Another possible cause could be modifications you made to your Chromium fork - or it could be a difference between Chrome and Chromium. That seems unlikely, but maybe someone could try what I explained here in Chromium. I'm on Windows, so I can't launch the modified Chromium from Playwright in headed mode, but maybe someone could try it there as well, see if we can't pinpoint the source of this problem?

**Comment by eliassorensen** [comment]
@mindplay-dk it is definitely still a problem in Canary.

Try this in Protocol Monitor:

1. `Network.enable`
2. `Fetch.enable`
3. Load a URL
4. In Protocol Monitor, there is now a `Fetch.requestPaused` event. Take the requestId from this, and put in the following request:
```
{
    "command": "Fetch.fulfillRequest",
    "parameters": {
        "requestId": "interception-job-1.0",
        "responseCode": 200,
        "body": "test",
        "responseHeaders": [
            {
                "name": "set-cookie",
                "value": "a=b"
            },
            {
                "name": "bogus-header",
                "value": "hello"
            }
        ]
    }
} 
```
You can now see in the response, that only the `bogus-header` appears. The `set-cookie` header is nowhere to be found in any events. However, it's still being set in the browser.

**Comment by mindplay-dk** [comment]
Taking a closer look at what happens in Chrome Canary, it turns out, it does *not* use the `Fetch` API over local overrides - instead, it's still using the deprecated `Network` API.

So the difference is very likely a bug in the new `Fetch` API, which DevTools doesn't seem to use yet.

Sorry for the confusion - I falsely assumed Playwright was using the same API as DevTools!

I wonder why DevTools isn't using the `Fetch` API yet? Perhaps because it's not reliable yet?

**Comment by eliassorensen** [comment]
Have reported this issue on crbugs as well: https://bugs.chromium.org/p/chromium/issues/detail?id=1292450

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
