### ISSUE TITLE
[Feature] Implement HTMLSelectElement as a additional type for the evaluate function

### ISSUE THREAD

**Issue by dz1dz1on** [microsoft/playwright#11039]
Hey, I would like to take text from the selected option in select element by using eval:

```
private async getValueFromSelect(locator: Locator): Promise<string> {
        const selectValue = await locator.evaluate(
            (sel: HTMLSelectElement) => sel.options[sel.selectedIndex].textContent
        )
        return selectValue === null ? '' : selectValue
    }
```
Right now  `sel` can be type of `SVGElement | HTMLElement`.

Adding this type would allow us to manipulate much easier the data (in TS) taken from select for expect function

**Comment by yury-s** [comment]
You need to manually downcast it to `HTMLSelectElement` when you know that the element is a select:

```ts
private async getValueFromSelect(locator: Locator): Promise<string> {
  const selectValue = await locator.evaluate(
    (el) => {
      const sel = el as HTMLSelectElement;
      return sel.options[sel.selectedIndex].textContent;
    }
  )
  return selectValue === null ? '' : selectValue
}
```

**Comment by yury-s** [comment]
Ok, we should be able to update change the callback type from
`evaluate<R>(pageFunction: PageFunctionOn<SVGElement | HTMLElement, void, R>)`
to something like 
`evaluate<R, E extends SVGElement | HTMLElement = SVGElement | HTMLElement>(pageFunction: PageFunctionOn<E, void, R>`
which should make your code work.
