### ISSUE TITLE
[Question] Why isn't Chromium updating?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#11038]
Hi, I'm on Windows 10 and I don't understand why my Chromium version is not updating when I run `npm i -D playwright` and then `npx playwright install`.
If I read well, the actual supported version is the r952821, right? Because is not appearing on the `ms-playwright` folder.

Also, I was wondering if in this version the reproduction of H264 codec is supported like the first Chromium version in this page: 

https://chromium.woolyss.com

Thank you :)

**Comment by MindaugasMateika** [comment]
You need nightly version for r952821; `npm i -D playwright@next`

**Comment by yury-s** [comment]
> Hi, I'm on Windows 10 and I don't understand why my Chromium version is not updating when I run `npm i -D playwright` and then `npx playwright install`.

It means that you already have required browser versions installed locally.

> If I read well, the actual supported version is the r952821, right? Because is not appearing on the `ms-playwright` folder.

It depends on which Playwright version you use. For 1.17 which is the latest release it i[s r939194](https://github.com/microsoft/playwright/blob/112fe3ae0d5395d807a60a1434d85f24d36cba09/packages/playwright-core/browsers.json#L6)

For @next version it is [r952597](https://github.com/microsoft/playwright/blob/f5304e3bdaa375d1bb21dfa28cbfa08cdffdb5d0/packages/playwright-core/browsers.json#L6).

> Also, I was wondering if in this version the reproduction of H264 codec is supported like the first Chromium version in this page:

No, Chromium build doesn't include proprietary codecs. They are only available in the proprietary browsers like Google Chrome  or MS Edge.
