### ISSUE TITLE
[Feature] container recipes for all major frameworks aka UnhandledPromiseRejectionWarning: Error: Failed to launch browser!

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#1103]
We should publish containers / spects for Docker, GH Actions, Travis, AppVeyor, etc.

**Comment by aslushnikov** [comment]
As of today, we run our tests first-hand on many CIs and maintaining configs to run Playwright

Set of up-to-date configs:
- [Github Actions](https://github.com/microsoft/playwright/blob/master/.github/workflows/tests.yml)
- [Travis CI](https://github.com/microsoft/playwright/blob/master/.travis.yml)
- [Appveyor](https://github.com/microsoft/playwright/blob/master/.appveyor.yml)
- [Circle CI](https://github.com/microsoft/playwright/blob/master/.circleci/config.yml)
- [Dockerfile](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic)

@arjun27 you mentioned a "getting started" guide - does this info belong there?
