### ISSUE TITLE
[Question] Is it possible to record heap snapshots?

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#11042]
Are there any APIs or Is it possible to record memory/heap [snapshots](https://developer.chrome.com/docs/devtools/memory-problems/#identify_js_heap_memory_leaks_with_allocation_timelines) programatically after opening a page with playwright?

**Comment by yury-s** [comment]
You can create [CDPSession](https://playwright.dev/docs/api/class-cdpsession) and take snapshots by sending CDP commands to the heap profiler. There is no generic/more user-friendly API in Playwright for the task currently.
