### ISSUE TITLE
[Feature] Capture `console` and `error` messages from Electron main process

### ISSUE THREAD

**Issue by jjeff** [microsoft/playwright#11045]
While there are methods for 
* [`page.on('pageerror')`](https://playwright.dev/docs/api/class-page#page-event-page-error`) and
* [`page.on('console'`)](https://playwright.dev/docs/api/class-page#page-event-console)

It sure would be nice if there were methods for
* `electronApplication.on('error')` and
* `electronApplication.on('console')`

This would allow Playwright to capture launch errors and output from Electron's main process in the same way that it allows us to capture them in the renderer processes.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/5905
