### ISSUE TITLE
[Question] Can be this framework used for automated tasks?

### ISSUE THREAD

**Issue by ninja-pinky** [microsoft/playwright#11043]
We have daily some tasks that need to be automated, e.g. fill some forms that have multiple inputs with data from our database in some websites that don't offer any API service.

Can be Playwright used for automated tasks or is it designed just for testing?

**Comment by yury-s** [comment]
Playwright can and is used for the browser automation that has nothing to do with testing. You can use [playwright library](https://playwright.dev/docs/next/library) which provides generic automation interface not bound to particular testing scenarios.
