### ISSUE TITLE
[BUG] Full page screenshots​ doesn't work on Electron application

### ISSUE THREAD

**Issue by nabil-brn** [microsoft/playwright#11041]
**Context:**
- Playwright Version: 1.17.0
- Operating System: Windows, Linux and Mac
- Node.js version: 14.18.1
- Browser: Chromium (Electron)
- Extra: N/A

**Code Snippet**

```javascript
import test from "../fixtures/common";
import { expect } from "@playwright/test";
import { OnboardingPage } from "../models/OnboardingPage";

test("Onboarding", async ({ page }) => {
  const onboardingPage = new OnboardingPage(page);

  await test.step("Get started", async () => {
    expect(await onboardingPage.getStartedButton).toBeVisible();
    expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(`getstarted.png`);
  });
})
```

**Describe the bug**
On Electron application, I unfortunately can't take a screenshot of the full page.
https://playwright.dev/docs/screenshots#full-page-screenshots

**Comment by yury-s** [comment]
Can you share minimal repro? I've tried with the attached app and it works just fine
[test.zip](https://github.com/microsoft/playwright/files/7758849/test.zip)
.

**Comment by nabil-brn** [comment]
Hello @yury-s,

We're using electron version 13.5.2, it could come from our app, I guess?

**Comment by aslushnikov** [comment]
@nabil-brn this is unfortunately not actionable without a repro that we can run & debug locally. Please feel free to resubmit once there's a repro!

**Comment by davej** [comment]
Just FYI in case anybody comes across this, the problem with the original is that there was no window selected to screenshot. I made the same mistake.

```diff
-    expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(`getstarted.png`);
+    expect(await onboardingPage.screenshot({ fullPage: true })).toMatchSnapshot(`getstarted.png`);
```
