### ISSUE TITLE
[BUG] Electron multiple windows issues

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [microsoft/playwright#11059]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 14.6
- Browser: Electron

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

const loadWindow = async (windowToCheck, electronApp) => {
  const windowState = await electronApp.evaluate(async ({ BrowserWindow }, windowToCheck) => {
    const selectedWindow = BrowserWindow.fromId(windowToCheck)

    const getState = () => ({
      isVisible: selectedWindow.isVisible(),
      id: selectedWindow.id,
      title: selectedWindow.getTitle(),
      isDevToolsOpened: selectedWindow.webContents.isDevToolsOpened(),
      isCrashed: selectedWindow.webContents.isCrashed()
    })

    return new Promise(resolve => {
      if (selectedWindow.isVisible()) {
        resolve(getState())
      } else {
        selectedWindow.once('ready-to-show', () => setTimeout(() => resolve(getState()), 0))
      }
    })
  }, windowToCheck)
  return windowState
}

const loadMainWindow = async () => {
  let electronApp
  let windowState

   electronApp = await electron.launch({ args: ['.'] })
   windowState = await loadWindow(1, electronApp) // get main window state
   page = electronApp.windows()[2] // it's our main window on front-end side
}
```

**Describe the bug**

We've multiple BrowserWindows in electron but in our case first window is not our main window. So if we use below code to get firstWindow it doesn't work:
```javascript
const page = await electronApp.firstWindow();
```
We also tried to get our main window by using `electronApp.windows()[windowToGet]`, but problem is that `electronApp.windows()` doesn't return the windows in same sequence always (It's different according to OS, and it also varies machine wise).

**PS:** Our one window (loading window) get destroyed after sometime when our main windows is ready to show.

**Comment by yury-s** [comment]
You can get access to already opened windows via [`windows()`](https://playwright.dev/docs/api/class-electronapplication#electron-application-windows) and listen to the window creation events via [`on('window')` ](https://playwright.dev/docs/api/class-electronapplication#electron-application-event-window) event and then detect desired window using the Page properties.

**Comment by stoefln** [comment]
@yury-s  what's still unclear to me is how to identify windows. If the window ID is not consistent, do we have to identify windows by their title?

**Comment by yury-s** [comment]
`title()`, [`url()`](https://playwright.dev/docs/api/class-page#page-url) or just evaluate custom js code in the page to identify it. If you don't control from the playwright end when the windows created and in which order you'll need to figure out which window is which nor relying on the order of those events or the window ids as they may change from run to run, see e.g. #6748

**Comment by ahmedmukhtar1133** [comment]
@yury-s Do we've any listener inside the evaluate function?
Same problem is there windows order is not consistent and we've to find the specific window.
```
await electronApp.evaluate(async ({ app }) => {
    // This runs in the main Electron process, parameter here is always
    // the result of the require('electron') in the main app script.
    return app.getAppPath();
  });
```

**Comment by ahmedmukhtar1133** [comment]
@yury-s 
I tried this code for getting desired page, but it's only getting fired for first window which is not desired page:
```  
const window = await electronApp.waitForEvent('window', async window => {
      console.log('title', await window.title())
      if ((await window.title()) === 'Repeato') return true
      return false
    })
```

If I just remove the `await` before `electronApp.waitForEvent` then it fires for each window but in that case next code will fail unless we've desired page.

Also tried like this but no success:
```
  const window = await electronApp.waitForEvent('window', {
      predicate: async window => {
        console.log('title', await window.title())
        if ((await window.title()) === 'Repeato') return false
        return false
      },
      timeout: 100000
    })
```
