### ISSUE TITLE
[Question] Handle multiple alerts in Playwright

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#11052]
I have a project scenario, where i need to handle multiple js alerts
When i click on refundViaAfterpay button, a Js alert gets created which asks user for refund confirmation.
When user clicks ok(accepts dialog), another Js alert gets generated
I need to capture second alert text as well as accept the second Js alert

With the below script i am able to get alert text from first Js alert only. 
i am unable to handle second Js alert nor get the second Js alert.
How can this be handled

```    
     this.page.on('dialog', async (dialog)  => {
        console.log(dialog.message());
        this.page.on('dialog', async dialog2 => {
            console.log('In here');
            console.log(dialog2.message());
            await dialog2.accept();
        });
        await dialog.accept();
    });
    await this.page.click(refundViaAfterpay);

```

**Comment by yury-s** [comment]
With your code you will accept second dialog twice which is not allowed and will lead to `"dialog.accept: Cannot accept dialog which is already handled"` exception. You can get away with a single listener:

```js
test('second alert', async ({page}) => {
  let dialogNum = 0;
  page.on('dialog', dialog => {
    ++dialogNum;
    if (dialogNum === 2)
      console.log(dialog.message());
    dialog.accept();
  });  
  await page.evaluate(() => {
    alert('uno');
    alert('dos');
  });
});
```
