### ISSUE TITLE
[Question]  Error: ["..."] selector engine has been already registered

### ISSUE THREAD

**Issue by petetnt** [microsoft/playwright#11058]
As background, we are in progress of migrating our Cypress + Testing Library based scripts to Playwright.

We've been trying out a custom selector engine based on `testing-library` defined in here https://gist.github.com/sebinsua/205682c7af6966fdadc103b4e15d0d8b, which works great! Trying to register the selector in multiple files errors with ` Error: "role" selector engine has been already registered`. The cause is pretty obvious, multiple files trying to register the same selector equals fail, especially when running with a single worker. This can be remedied by wrapping them to try/catch, but that's not exactly optional.

However, it's not quite obvious where exactly should custom selector engines be registered in? [In the documentation](https://playwright.dev/docs/api/class-selectors#selectors-register), they are just registered inline in a script: 

```ts
const { selectors, firefox } = require('playwright');  // Or 'chromium' or 'webkit'.

(async () => {
  // Must be a function that evaluates to a selector engine instance.
  const createTagNameEngine = () => ({
    // Returns the first element matching given selector in the root's subtree.
    query(root, selector) {
      return root.querySelector(selector);
    },

    // Returns all elements matching given selector in the root's subtree.
    queryAll(root, selector) {
      return Array.from(root.querySelectorAll(selector));
    }
  });

  // Register the engine. Selectors will be prefixed with "tag=".
  await selectors.register('tag', createTagNameEngine);

  ...
})();
```

which will result in the same issue when running with Playwright Test.

I tried registering them in `globalSetup`, but seemingly that doesn't work either, at least the selectors didn't work anymore after that while no errors were raised. In my mind I guess those registrations could be added eg. to something like playwright.config.ts, as something like:

```
selectors: [...myCustomSelectors]
``` 

where `myCustomSelectors` would be `(name, (): SelectorEngine)[]` that would be passed to `selectors.register`. Or there might be something obvious that I am missing, coming into Playwright fresh from Cypress.

**Comment by yury-s** [comment]
> I tried registering them in `globalSetup`, but seemingly that doesn't work either, at least the selectors didn't work anymore after that while no errors were raised. In my mind I guess those registrations could be added eg. to something like playwright.config.ts, as something like:

This doesn't work because `globalSetup` runs in the main test runner node process while tests are executed in [worker processes](https://playwright.dev/docs/test-parallel#worker-processes).

What you need is an [automatic](https://playwright.dev/docs/next/test-fixtures#automatic-fixtures) worker [fixture](https://playwright.dev/docs/test-fixtures#worker-fixtures) that would register the selectors once in each worker process:

```ts
// customSelectors.ts
import { test as base, selectors } from '@playwright/test';

export const test = base.extend<{}, { registerSelectors: void }>({
  registerSelectors: [async ({}, use) => {
    const createTagNameEngine = () => ({
      query(root, selector) {
        return root.querySelector(selector);
      },
      queryAll(root, selector) {
        return Array.from(root.querySelectorAll(selector));
      }
    });
    await selectors.register('tag', createTagNameEngine);
    await use();
  }, { scope: 'worker', auto: true }],
});
export { expect } from '@playwright/test';
```

**Comment by petetnt** [comment]
Awesome, thanks Yury!

**Comment by RobinTTY** [comment]
@yury-s I think it would be great to note this in the documentation somewhere, stumbled over this myself.
