### ISSUE TITLE
[BUG] When i run my test in different browsers Chrome, Firefox and Webkit only Chrome get pass. The rest fails

### ISSUE THREAD

**Issue by ermi1968** [microsoft/playwright#11056]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.17.1
- Operating System: [e.g. Windows, Linux or Mac] Windows 10
- Node.js version: [e.g. 12.22, 14.6] v14.18.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test('Wright Normal test ', async ({ page }) => {
  const pageObject = new PageObject(page);
  await pageObject.goto();
  await page.click('id=WrightNormal');
  await page.getAttribute("id=WrightNormal","Normal");
  const locator = page.locator("id=WrightNormal");
  await expect(locator).toContainText('Normal');
  }),
  
  ----
  
  const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
};
```

**Describe the bug**
When i run my test with all browsers, the test gets pass for chrome but it fails for firefox and webkit. 
Add any other details about the problem here.

**Comment by yury-s** [comment]
What exactly is failing? You can collect [traces](https://playwright.dev/docs/api/class-testoptions#test-options-trace) to see what's the difference in the behavior between the browsers.

**Comment by aslushnikov** [comment]
@ermi1968 this is not actionable without a repro that we can run & debug locally. Please feel free to resubmit once there's a good repro!

**Comment by bubafinder** [comment]
The same thing is happening to me right now. 
When the test is run for all three browsers, only the Chrome test passes. If Firefox and Webkit tests are run separately, they are passing.
Some specs that are specific for this test:
- we are using a separate playwright config project to save user session and reuse it in tests
- the step where the test is failing is when the baseUrl is changed, navigating from one app to another
