### ISSUE TITLE
[BUG] Edge is not installed as a part of all browsers

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#11061]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Linux
- Node.js version: 14.8.2
- Browser: Edge

npx playwright install command is not installing edge browser.
 Because of that tests that are running on edge stable channel throwing error:
  ```
browserType.launch: Chromium distribution 'msedge' is not found at /opt/microsoft/msedge/msedge
    Run "npx playwright install msedge"
```

**Comment by ltsuda** [comment]
Playwright's install process only installs Chromium, Firefox and Webkit by default.

As the error message said, you have to run the `npx playwright install msedge` after the regular `npx playwright install` to install it.

See the second bullet item from the link below.
https://playwright.dev/docs/release-notes#ubuntu-arm64-support--more

Here's how to manage Browsers' installation
https://playwright.dev/docs/browsers#installing-browsers

**Comment by szamacz** [comment]
Thanks for qreply.  Maybe I should pharse this a little bit differently - What's the point of having a command which installs all the browsers but not Edge? If I would like to install only Edge I will use command mentioned by you but this seems to be quite strange to use one command to install all browsers but not edge and then the second command to install only edge. When setting up tests on CI pipeline is just additional step - which In my opinion doesn't make too much sense.

**Comment by ltsuda** [comment]
If you only need Edge, you can skip the installation of the other ones during the first command as said in the link below, then you can install only the edge with the install msedge command.


https://playwright.dev/docs/browsers#skip-browser-downloads

**Comment by yury-s** [comment]
> Thanks for quick reply. Maybe I should phrase this a little bit differently - What's the point of having a command which installs all the browsers but not Edge?

By default playwright installs only open source browsers. All proprietary ones including Edge and Chrome have to be installed manually.

**Comment by szamacz** [comment]
That's the answer I was looking for, thank you
