### ISSUE TITLE
[Question] Selenium Grid Issue

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#11065]
Hi guys, I am trying to connect to a running selenium grid we are using by following the docs in v1.17 (https://playwright.dev/docs/selenium-grid/)

I am getting this error when running the test by lunching the browser:
 `const browser = await playwright.chromium.launch({ headless: false, channel: "Chrome" });`
 
I have tried it without specifying any channel as well. 

I have also checked that the grid is up and running.

Any suggestions ?
Thanks!

browserType.launch: connect ECONNREFUSED 127.0.0.1:44563
=========================== logs ===========================
< connecting to selenium > http://my-grid:4444/wd/hub/
< connected to selenium > sessionId=2c855bc4b2203b4e658f547b1334be0e

![image](https://user-images.githubusercontent.com/17011557/147149670-32a8cb14-b332-4ce4-9b81-483dc443c542.png)

**Comment by aslushnikov** [comment]
@dgozman could you please take a look? (assigning 1.18 for visibility so that Dmitry takes a look when he's back from vacation)

**Comment by imartinflores** [comment]
Hi @aslushnikov , quick update, I have deployed a Selenium Grid 4 and it seems to be picking up the test, however now, looks like it is not executing any action after opening the browser session, not even navigating to a page.

I am executing just this:
`await page.goto("www.google.com")`

And when I explore the session in the grid, it just shows the chrome opened but in blank:
![image](https://user-images.githubusercontent.com/17011557/149511627-915b79ba-0f98-4e0a-ae62-da1dee7e6a75.png)

I will keep looking at it.
Thanks!

**Comment by dgozman** [comment]
@imartinflores Try running the alpha version `@playwright/test@next` - there have been some changes recently. If things do not work,  run with `DEBUG=pw:browser*` - that will give some logging information that might help.

**Comment by imartinflores** [comment]
@dgozman thanks, will try as soon as I can and provide feedback. Thank you!

**Comment by kellis-scottlogic** [comment]
I'm also seeing a similar issues, but with the browser launch timing out. I can see that the connection to the grid is successful and it is getting a WS url but we are using Grid 3 at the moment, so I wonder if this is to be expected and requires an upgrade to grid 4.

```
    const browser = await chromium.launch({ channel: "chrome" });
    const page = await browser.newPage();
```


```
browserType.launch: connect ETIMEDOUT 172.17.0.7:43834
=========================== logs ===========================
<selenium> connecting to http://10.245.121.57:4444/wd/hub/
<selenium> connected to sessionId=950615a63b854a9701899ccd06b66aaf
<selenium> using selenium v3
<selenium> retrieved endpoint http://localhost:43834 for sessionId=950615a63b854a9701899ccd06b66aaf
<selenium> resolved endpoint ip http://172.17.0.7:43834/ for sessionId=950615a63b854a9701899ccd06b66aaf
<ws preparing> retrieving websocket url from http://172.17.0.7:43834/
<selenium> disconnecting from sessionId=950615a63b854a9701899ccd06b66aaf
<selenium> disconnected from sessionId=950615a63b854a9701899ccd06b66aaf
```

**Comment by imartinflores** [comment]
Hi @dgozman, tried it with @playwright/test@next, could see it working on Selenium Grid 4. I have noticed with the Live Session feature from Sel 4, that there is an opened browser, but my test opens a new browser anyways, not sure if it should attach to that browser session. I will see if that's related to my test, but it is working fine anyways. Thanks a lot.
Nacho

**Comment by mxschmitt** [comment]
Version 1.18 includes fixes for Selenium 3 and 4. See [here](https://playwright.dev/docs/selenium-grid) for documentation and please file new bug reports if you still encounter bugs.

**Comment by CkumarGitHub** [comment]
@dgozman @aslushnikov: I am facing a similar issue (Playwright with Java) with Selenium GRID 4.
My GRID is up and running. 
Error:

com.microsoft.playwright.PlaywrightException: Error {
  message='WebSocket error: connect ETIMEDOUT 172.18.0.3:4444
=========================== logs ===========================
<selenium> connecting to http://localhost:4444/wd/hub/
<selenium> connected to sessionId=4c7eff48a2541efaa96b2d5e509f5691
<selenium> using selenium v4
<selenium> retrieved endpoint ws://172.18.0.3:4444/session/4c7eff48a2541efaa96b2d5e509f5691/se/cdp for sessionId=4c7eff48a2541efaa96b2d5e509f5691
<ws connecting> ws://172.18.0.3:4444/session/4c7eff48a2541efaa96b2d5e509f5691/se/cdp
<ws error> error connect ETIMEDOUT 172.18.0.3:4444
<ws connect error> ws://172.18.0.3:4444/session/4c7eff48a2541efaa96b2d5e509f5691/se/cdp connect ETIMEDOUT 172.18.0.3:4444
<ws disconnected> ws://172.18.0.3:4444/session/4c7eff48a2541efaa96b2d5e509f5691/se/cdp code=1006 reason=
<selenium> disconnecting from sessionId=4c7eff48a2541efaa96b2d5e509f5691
<selenium> disconnected from sessionId=4c7eff48a2541efaa96b2d5e509f5691
============================================================
  name='Error
  stack='Error: WebSocket error: connect ETIMEDOUT 172.18.0.3:4444

**Comment by Husain-Syedali** [comment]
I am also not able to connect to selenium grid from playwright Java running on Kubernetese setup 
<selenium> connecting to http://127.0.0.1:64022/
============================================================
    at ProgressController.run (/private/var/folders/1f/9018b4cn4g797f403prw7pm80000gn/T/playwright-java-8774773340304412021/package/lib/server/progress.js:88:26)
    at Chromium.launch (/private/var/folders/1f/9018b4cn4g797f403prw7pm80000gn/T/playwright-java-8774773340304412021/package/lib/server/browserType.js:63:38)
    at BrowserTypeDispatcher.launch (/private/var/folders/1f/9018b4cn4g797f403prw7pm80000gn/T/playwright-java-8774773340304412021/package/lib/server/dispatchers/browserTypeDispatcher.js:35:40)
    at DispatcherConnection.dispatch (/private/var/folders/1f/9018b4cn4g797f403prw7pm80000gn/T/playwright-java-8774773340304412021/package/lib/server/dispatchers/dispatcher.js:312:46)

**Comment by arr121** [comment]
I too facing similar issue while executing with selenium 4 . Could you confirm if there is any solution identified for this issue.

Thank you,
Ranga
