### ISSUE TITLE
Connect to Selenium Grid

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#11062]
Is there any documentation on how to connect to a Selenium Grid ? or is it not supported ? If it is not, is it something on the roadmap to be added ?

Thanks!

**Comment by ltsuda** [comment]
I hope this helps

https://playwright.dev/docs/selenium-grid

**Comment by imartinflores** [comment]
@ltsuda thanks a lot, yes, it really helps, have not seen it before!

**Comment by imartinflores** [comment]
@ltsuda  have you tried it before ? should it be executed directly from the terminal ?
Just getting this when trying it.

The term 'SELENIUM_REMOTE_URL=http://mygrid.grid:4444/wd/hub' is not recognized as the name of a cmdlet

**Comment by ltsuda** [comment]
I'm sorry, I've never used before.

I think it should be run from the terminal, but the syntax in the docs looks like from Bash terminal. It might be good to provide more information about your OS, if it is Windows or Linux, if you are using Playwright@Test or Playwright Library, node version, etc.

With this information, the team from Playwright could help with better/correct infos.

**Comment by imartinflores** [comment]
Cool, no problem. Yeah, I am running it on Windows, using Playwright@Test . Node version @ 8.3.0 . Ill try to find something else!
Thanks a lot!

**Comment by ltsuda** [comment]
No problem.

I think this should help.

There is a Powershell or Batch syntax tab on some of the code blocks, as you are using Windows, this is the correct way to set environment variables. The page is just to show the syntax example.
https://playwright.dev/docs/browsers#managing-browser-binaries

**Comment by imartinflores** [comment]
Cool, that works. I am having issues executing the test on the grid now, but thats something different. 
Thanks for helping. Ill close it!

Regards,
Nacho
