### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by aposiker** [microsoft/playwright#11063]
It would be cool to have access to ```testInfo``` methods not only inside the tests. My use case was adding attachments via TS decorators.  I have a decorator in my test project, that I use to log methods calls from Page Objects as test steps, and here I was trying to add all arguments that were passed to the method as an attachment, but as I understood from the docs `testInfo` methods (```testInfo.attachments.push()``` is what I was looking for in particular) only can be called inside the tests.
Feel free to drop some comments if there will be needed any additional info or code examples.

**Comment by yury-s** [comment]
Merging into https://github.com/microsoft/playwright/issues/9417, please thumb up that request instead.
