### ISSUE TITLE
[BUG] frame.fill: Protocol error (Page.insertText): error in channel "content::page"

### ISSUE THREAD

**Issue by amotl** [microsoft/playwright#11074]
Hi again,

coming from #11073, we would like to share this observation with you.

With kind regards,
Andreas.

## Version and context information
- Playwright Version: 1.17.1
- Operating System: macOS and Linux, both native and via Docker
- Node.js version: 17.3.0 (macOS) and 16.13.1 (Docker)
- Browser: Mozilla Firefox 94.0.1

## Bug description

```
1) [firefox] › testdrive.spec.ts:116:3 › Main › Messenger: Sending a message ========================

frame.fill: Protocol error (Page.insertText): error in channel "content::page": exception while running method "insertText" in namespace "page": Component returned failure code: 0xc1f30001 (NS_ERROR_NOT_INITIALIZED) [nsITextInputProcessor.commitCompositionWith] _insertText@chrome://juggler/content/content/PageAgent.js:786:32
_onMessage@chrome://juggler/content/SimpleChannel.js:165:37
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
 _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42

=========================== logs ===========================
waiting for selector "div[role="textbox"]"
  selector resolved to visible <div dir="auto" tabindex="0" role="textbox" aria-mult…>…</div>
elementHandle.fill("e2e-bot 2021-12-22T19:40:51.654Z")
  waiting for element to be visible, enabled and editable
  element is visible, enabled and editable
============================================================

  133 |
  134 |     // Set message content.
> 135 |     await frameContent.fill('div[role="textbox"]', `${settings.message_content}`)
      |                        ^
  136 |
  137 |     // Submit message.
  138 |     await page.keyboard.press('Enter')

    at /Users/amo/dev/testdrive/sources/e2e-tests/tests/testdrive.spec.ts:135:24
```
</details>

As reflected with all the other friends of this issue, as outlined in the "Further research" section, this problem only happens occasionally, and only when using Firefox so far.

## Background
We are automating a basic navigation on an [Element Web](https://matrix.org/docs/projects/client/element/) page, loaded into an iframe. Specifically, we are choosing a recipient from the roster, and send them a message. When trying to fill in the corresponding text message, the croaking on the `fill` action kicks in.

## Further research
After searching the issue tracker, we discovered that this issue has a longstanding history already. It can easily be tracked by [searching for `NS_ERROR_NOT_INITIALIZED`](https://github.com/microsoft/playwright/search?q=NS_ERROR_NOT_INITIALIZED&type=issues), the specific tickets are #7186, #8136, #8374, #9776 and #10681, all having been converged into the discussion at #5460.

Apparently, after looking out for a repro for quite some time (https://github.com/microsoft/playwright/issues/7186#issuecomment-862942114), @canonic-epicure finally delivered one per #9776. The issue was able to be mitigated by @aslushnikov only recently through #10238. Thanks!

## Outlook
Apparently, there might still be edge cases around this topic. Like @Tomm1ch did at https://github.com/microsoft/playwright/issues/5460#issuecomment-855284470, we will be happy to share the recipe with you, which can not be made public in its current form.

/cc @aslushnikov, @JoelEinbinder, @dgozman

**Comment by amotl** [comment]
For what it's worth, we can share the corresponding test case right away. It took some minutes to figure this out as newcomers to Playwright, but after conceiving it, we are deeply impressed by its conciseness, preciseness and effectiveness. Thanks again for conceiving this great framework!

As it mostly works, it would be so sweet if we could figure out the reason for the `NS_ERROR_NOT_INITIALIZED`-related error together somehow.

Maybe you are already seeing a spot where we are obviously doing things in a wrong way?

```typescript
/**
 * Proof that sending a message works.
 *
 * This essentially automates testing a huge part of the underlying machinery,
 * specifically that the whole Matrix/Elements software stack is alive and that
 * all corresponding components are properly integrated.
 */
test('Messenger: Sending a message', async ({ settings }) => {

  // Navigate to the Messenger.
  await page.waitForSelector('button:has-text("Messenger")')
  await page.click('button:has-text("Messenger")')
  await page.waitForLoadState('domcontentloaded')

  // Drill down to Matrix/Elements iFrame.
  const frameHandle = await page.$('#matrix')
  await frameHandle.waitForElementState('visible')

  const frameContent = await frameHandle.contentFrame()
  await frameContent.waitForLoadState('domcontentloaded')

  // Set recipient.
  await frameContent.click(`div[aria-label="${settings.message_recipient}"]`)

  // Set message content.
  await frameContent.fill('div[role="textbox"]', `${settings.message_content}`)

  // Submit message.
  await page.keyboard.press('Enter')

})
```

**Comment by yury-s** [comment]
> We are automating a basic navigation on an [Element Web](https://matrix.org/docs/projects/client/element/) page, loaded into an iframe. Specifically, we are choosing a recipient from the roster, and send them a message. When trying to fill in the corresponding text message, the croaking on the `fill` action kicks in.

Would it be possible for you to provide a page that does what you describe (with the iframe that loads the component) ?

**Comment by aslushnikov** [comment]
@amotl some variation of this issue was fixed a while ago; but apparently there's another one that hits you.

However, without a good repro, this is not actionable.

But! If you have a repro that we can run locally and see the behavior, please file a new issue with the repro! Once there's a repro, we'll be happy to fix it.
