### ISSUE TITLE
[REGRESSION]: Official Docker Containers and Node Unhandled Rejections Crash

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#11078]
This is not really a regression in PW, but an informational note. This may be helpful for others debugging why some Playwright scripts start crashing hard without any changes to the scripts themselves. (This doesn’t have to do specifically with PW, but since it becomes relevant with the official containers and how your scripts are written that are running in them, I’m adding it here.)

The Node version in the official PW Docker images (e.g. mcr.microsoft.com/playwright:v1.17.1-focal) changed from Node v14 to v16 when upgrading from the PW 1.16 to PW 1.17 image.

The upgrade of Node brought with it a (surprising) change w.r.t. to Unhandled Promise Rejections: https://nodejs.org/api/cli.html#--unhandled-rejectionsmode

It changed from a default of _warn_ to _throw_ so existing scripts started failing hard without any changes to them themselves. (In PW scripts, it’s fairly common to hit rejections of Target closed and the like, so as folks upgrade to new versions of Node, it’s important to add code into scripts utilizing PW to handle these rejections if they might occur. NB: In most testing code written with PW, I don’t expect to hit these, but they are sometimes hit when handling third-party code and frames one cannot control.)

To fix this: either handle the rejections explicitly (or with some catchall unhandled rejections hook) or opt back into the old Node behavior with `NODE_OPTIONS='--unhandled-rejections=warn'`.

**Comment by rwoll** [comment]
While this isn't really an issue with PW, perhaps it is worthwhile to call out major NodeJS version upgrades in PW release notes. 

(I don't expect the PW team to track every Node change that may impact users, so simply a line like "Official Docker Containers have switched from using Node Version X to Y. Please review the Node release notes for relevant changes." might be helpful to users without adding more work on the PW team.)

**Comment by mxschmitt** [comment]
Closing for now since it's too late anyway!
