### ISSUE TITLE
[Question]How to enable all third party cookies

### ISSUE THREAD

**Issue by ynjacobs** [microsoft/playwright#11072]
Thanks for this wonderful library.

I have been searching for a way to enable 3rd party cookies in chrome settings using playwright

I have tested enabling and blocking in non playwright incognito and non incognito window and seems when cookies are blocked I cannot access the page I need and when they are enable then I can.

So I'm wondering how I can do this in playwright? I have tried manually changing the settings once a playwright chrome window has been opened but that did not help, I'm still being blocked.

Is there something similar to Webdriver's: `network.cookie.cookieBehavior `? Or some other way to enable 3rd party cookies before the page opens?

For reference I have looked at:
https://github.com/microsoft/playwright/issues/8940
https://github.com/microsoft/playwright/issues/2072

Thanks!

**Comment by yury-s** [comment]
> So I'm wondering how I can do this in playwright? I have tried manually changing the settings once a playwright chrome window has been opened but that did not help, I'm still being blocked.

Why do you think you are blocked because of third-party cookies? Perhaps the web site doesn't like that the browser is controlled by an automation tool.

**Comment by ynjacobs** [comment]
@yury-s thanks for your reply.
Sorry I should have clarified in my question, I am able to use playwright for the first site I am accessing with no problems. I have an iframe with another site that is refusing to connect and it is showing in the network of dev tools that cookies are being blocked for 3rd party requests.
 The same behaviour happens when I block 3rd party cookies in non playwright browser.

**Comment by yury-s** [comment]
> I have an iframe with another site that is refusing to connect and it is showing in the network of dev tools that cookies are being blocked for 3rd party requests.

Can you share the link? When I go to https://www.whatismybrowser.com/detect/are-third-party-cookies-enabled using playwright it shows 'Yes'

**Comment by ynjacobs** [comment]
I'm using incognito mode

![Screenshot (103)(2)](https://user-images.githubusercontent.com/49129946/147177671-abb9c08b-acdf-412d-acb8-c72a6cfa4a92.jpg)




I was just using inspect tools and going to Network tab (didn't use an external link to test)

![Screenshot (104)](https://user-images.githubusercontent.com/49129946/147177271-396b4d55-4052-41d9-9aed-af72421aa57e.jpg)

**Comment by pavelfeldman** [comment]
We don't have a feature that enables all cookies in Chrome, we only use default settings.
