### ISSUE TITLE
[BUG] tracing.stopChunk: ENOENT: no such file or directory, open '.../page@xxx-0000000002.jpeg'

### ISSUE THREAD

**Issue by amotl** [microsoft/playwright#11073]
Dear Playwright developers,

first things first: Thanks a stack for conceiving this excellent program. We started to use it just recently and are really like "This is actually what we have been expecting from Selenium since ages".

We observed a minor problem and wanted to report it back to you. Please let us know if you need further information about this report. Unfortunately, we haven't been able to find time to build a concise and short repro yet.

Keep up the spirit and with kind regards,
Andreas.

---

## Version and context information
- Playwright Version: 1.17.1
- Operating System: macOS and Linux, both native and via Docker
- Node.js version: 17.3.0 (macOS) and 16.13.1 (Docker)
- Browser: Mozilla Firefox 94.0.1

## Bug description

Like outlined at #9201 and #10826, we are receiving an `ENOENT` error from `tracing.stopChunk`, when trying to write(?) the `.jpeg` file. In the very same manner, the outcome is indeterministic: While it mostly succeeds, it croaks occasionally. The screenshot below within the "Background" section illustrates this well.

```
tracing.stopChunk: ENOENT: no such file or directory, open '/var/folders/06/w9pzygdj7vx53n_0l9q_lhph0000gn/T/playwright-artifacts-4pcrDS/resources/page@8a52a7dace93e95e4d829d0806bdd4f6-0000000002.jpeg'
```

Our configuration is like

```typescript
const config: PlaywrightTestConfig = {
    use: {
        trace: 'on',
        screenshot: 'on',
        video: 'on',
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        },
        {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
        },
        {
            name: 'safari',
            use: { ...devices['Desktop Safari'] },
        },
    ],
};
```

## Background

We are running a Playwright recipe as an Icinga2 sensor, being invoked each three minutes, with a runtime of about 45 seconds each. The screenshot attached below clearly demonstrates the flakyness and roughly outlines the dropout rate.

<details>
<summary>Screenshot: History over two hours running a Playwright recipe as an Icinga2 sensor</summary>

![image](https://user-images.githubusercontent.com/453543/147143127-7cabd976-25da-4191-9eac-42281499d592.png)

</details>

**Comment by amotl** [comment]
Hi again,

we are not completely sure about this, but when removing the `trace`, `screenshot` and `video` settings, we are occasionally getting errors like the ones outlined at #11074. One the one hand, this might indicate we will have to compensate for some timing-related details within our recipe. On the other hand, it might also indicate that the `ENOENT` error might have masked the other error somehow, or vice versa?

With kind regards,
Andreas.

**Comment by yury-s** [comment]
> Like outlined at #9201 and #10826, we are receiving an `ENOENT` error from `tracing.stopChunk`, when trying to write(?) the `.jpeg` file.

There were some fixes to `tracing.stopChunk` recently. They are not yet released but maybe you could give them a try in the @next version of playwright and see if the problem persists?

> On the other hand, it might also indicate that the ENOENT error might have masked the other error somehow, or vice versa?

It might be the case. We'll have a look at the other report.

**Comment by aslushnikov** [comment]
I'll close this for now. Feel free to re-file if it is not fixed yet!
