### ISSUE TITLE
[BUG] Page title is not returned for newly opened pages in Headless mode

### ISSUE THREAD

**Issue by dshaplyko** [microsoft/playwright#11087]
**Context:**
- Playwright Version: 1.17.1
- Operating System: MacOS
- Node.js version: 14.17.6
- Browser: Chromium

Hi colleagues!

I'm trying to implement a simple test scenario:
1. Open the app
2. Click some link (new browser tab should be opened after it)
3. Switch to the new browser tab
4. Validate the title/url of the newly opened tab

*Actual result:* I receive "chrome-error://chromewebdata/" as a page url and "" as a title in **Headless** mode. **It works perfectly in the Headed one**

Here is the example of my test:

**Code Snippet**
```javascript
test("should open Blockchain Explorer in a new browser tab @criticalPath", async ({
    portfolioPage, context
  }) => {
    await portfolioPage.header.profileButton.click();
    const [newPage] = await Promise.all([
      context.waitForEvent("page"),
      portfolioPage.profile.blockchainExplorerLink.click(), // Opens a new tab
    ]);
    await newPage.waitForLoadState();
    await expect(newPage).toHaveTitle(/anxexplorer.com/);
  });
```

[trace.zip](https://github.com/microsoft/playwright/files/7768543/trace.zip)

**Comment by yury-s** [comment]
> _Actual result:_ I receive "chrome-error://chromewebdata/" as a page url and "" as a title in **Headless** mode. **It works perfectly in the Headed one**

"chrome-error://chromewebdata/" means that you tried to navigate to a non existent url or there was a network error during the navigation. It's a chrome page for network errors. If it doesn't happen in headful then either your code navigates to a different url in headless or the server behaves differently depending on whether the request is from headless browser. Can you share a repro that we can run locally?

**Comment by yury-s** [comment]
Unfortunately failed network requests are not captured in the trace at the moment, I filed a feature request for that: https://github.com/microsoft/playwright/issues/11092

**Comment by aslushnikov** [comment]
Looks like this issue is explained, and a follow-up is filed by Yury.

**Comment by yuhymuk** [comment]
I caught the same issue. URL for head-on and headless modes the same

**Comment by nitzanashi** [comment]
it happens to me as well, sudendly out of nowhere after about a year that I haven't touched my test
