### ISSUE TITLE
[Feature] waitForFunction, but NOT in page context

### ISSUE THREAD

**Issue by 1aerostorm** [microsoft/playwright#11086]
Let we need to wait for some console logging. We can use `'console'` event.

There is `waitForEvent`, but it will be too complicated if there are many console logs and we need to wait for each log within a loop.

So, we can use `page.on()` and store message into a variable:
```js
let flag;
page.on('console'), message => {
     const text = message.text();
     if (/* text matches some conds */) {
          flag = text;
     }
});
```

But how to wait until "flag" variable will be initialized?

At current moment we have to store the variable in a page context, or use some another dirty workaround.

Or reinvent `waitForFunction` by ours own:

```js
async function waitForFunc(func, arg) {
    let waited = 0;
    while (true) {
        if (waited >= 3000) throw 'waitForFunc timeouted';
        const ret = await func(waited, arg);
        if (ret) {
            return ret;
        }
        const delay = 250;
        await new Promise(resolve=>setTimeout(resolve, delay));
        waited += delay;
    }
}
```

Now we can wait for our flag:

```js
await waitForFunc(() => flag);
```

Also, before test, we can check that such log message don't appears already (without action which should trigger it):

```js
await waitForFunc(waited => {
    if (flag) throw 'flag is already set! ' + flag;
    if (waited >= 2500) return true; // tricky, but works
});
```

**Comment by yury-s** [comment]
You can specify custom [predicate](https://playwright.dev/docs/api/class-page#page-wait-for-event-option-options-or-predicate) and `timeout` as options of `waitForEvent`:
```ts
  const message = await page.waitForEvent('console', {
    predicate: (message) => {
      const text = message.text();
      if (/* text matches some conds */) {
        return true;
      }
      return false;
    },
    timeout: 3_000
  });
```

**Comment by 1aerostorm** [comment]
@yury-s Okay, but:

1. It is complicated if we want to check it few times:
```js
const yourWait = async () => {
  await page.waitForEvent('console', {
    predicate: (message) => {
      const text = message.text();
      if (/* text matches some conds */) {
        return true;
      }
      return false;
    },
    timeout: 3_000
  });
};
...
await yourWait();
...
await yourWait();
```

Compare it with:
```js
let flag;
page.on('console'), message => {
     const text = message.text();
     if (/* text matches some conds */) {
          flag = text;
     }
});
...
await waitForFunc(() => { return flag; });
...
await waitForFunc(() => { return flag; });
```

1.1. One of problems is what my waiter implementation uses 3000 msec by default and `waitForEvent` uses 30000 msec by default, so we should to specify timeout forcely.
Actually, 30000 msec is too big timeout for testing, as well as for "debugging" tests.

2. Usage of `waitForEvent` for detecting that there is NO such message yet is too complicated.

**Comment by bitjson** [comment]
Now supported: https://github.com/microsoft/playwright/pull/12815
