### ISSUE TITLE
[BUG] Test is failed with the "Protocol error ..." when making a screenshot of the full page on mobile 'Webkit' browser

### ISSUE THREAD

**Issue by Jothny** [microsoft/playwright#11089]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Linux Ubuntu 18.04.6 LTS
- Node.js version: v12.20.0
- Browser: WebKit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {test, expect} = require('@playwright/test');

test('Custom Software Development page', async ({ page }) => {
  await page.goto('https://playwright.dev/')

  // scroll page at the bottom
  await page.evaluate(async () => {
    await new Promise(resolve => {
      let totalHeight = 0
      const distance = 100
      const timer = setInterval(() => {
        const scrollHeight = document.body.scrollHeight
        window.scrollBy(0, distance)
        totalHeight += distance

        if (totalHeight >= scrollHeight) {
          clearInterval(timer)
          resolve()
        }
      }, 100)
    })
  })

  await page.waitForTimeout(1000)

  expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(
    `Playwright-mobile-test.png`
  )
})
```
playwright.config.js file
```
const {devices} = require('@playwright/test');
module.exports = {
  projects: [
    {
      name: 'test',
      use: { browserName: 'webkit', ...devices['iPhone 6'] }
    }
  ]
}
```
**Describe the bug**

Test is failed with the message ```page.screenshot: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}] ``` when making a screenshot of the full page on a mobile device with the 'Webkit' browser

**Comment by aslushnikov** [comment]
@Jothny I unfortunately cannot reproduce this inside ubuntu 18.04 docker container. Does it repro reliably for you? Does it repro in a docker container?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by Jothny** [comment]
@aslushnikov With the test shown in my example, it failed to reproduce in docker.
I launched my file with tests and settings in docker - it was reproduced, albeit to the very last test on Webkit mobile.

Tried to adapt my settings to some opened resource - failed again. Conducted various tests, failed to reproduce again.

I can share a screenshot of the settings, maybe this will help you understand what is the reason.
http://i.imgur.com/SpV5GQA.png
http://i.imgur.com/yQrCzOo.png

**Comment by tsharma-indeed** [comment]
We are also getting this error consistently:

page.screenshot: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]
                =========================== logs ===========================
                taking page screenshot
                ============================================================
                    at screenshot (/builds/QJziGgzc/5/acme/yoyo/e2e/src/lib.ts:78:39)
                    at tryCatch (/builds/QJziGgzc/5/acme/yoyo/node_modules/regenerator-runtime/runtime.js:63:40)
                    at Generator.invoke [as _invoke] (/builds/QJziGgzc/5/acme/yoyo/node_modules/regenerator-runtime/runtime.js:294:22)
                    at Generator.throw (/builds/QJziGgzc/5/acme/yoyo/node_modules/regenerator-runtime/runtime.js:119:21)
                    at asyncGeneratorStep (/builds/QJziGgzc/5/acme/yoyo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
                    at _throw (/builds/QJziGgzc/5/acme/yoyo/node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)
