### ISSUE TITLE
Chaining of assertions (or Debugging selectors)

### ISSUE THREAD

**Issue by 1aerostorm** [microsoft/playwright#11098]
We can check:
```js
await expect(page.locator('.image-btn')).toBeVisible();
```

And it will fail if button is not visible.
Also, it will fail if no button at all (and yes, it will print a proper error message).

But what if there are... 2 buttons due some bug? :)
Or what if we forgot what there are 2 '.image-btn', and testing wrong button?

Yes, we can do:
```js
const imageBtn = page.locator('.image-btn');
await expect(imageBtn).toHaveCount(1);
await expect(imageBtn).toBeVisible();
```

But why we can't do:
```js
await expect(page.locator('.image-btn')).toHaveCount(1).toBeVisible();
```
or
```js
await expect(page.locator('.image-btn')).toHaveCount(1).and.toBeVisible();
```
or, at least,
```js
await (await expect(page.locator('.image-btn')).toHaveCount(1)).toBeVisible();
```
?

(I know what you are using Jest expect library.
But what about:
```js
.toHaveVisibleOne(options)
.toHaveVisibles(count, options = { exact: true, )) // BTW, what about "exact" option? "exact = false" can mean "at least"
.toHaveInvisibleOne(options)
.toHaveInvisibles(count, options = { exact: true, })
```

The large amount of checks will use `.toHaveVisibleOne()` because it is better than just `.toBeVisible()`.

### Alternative

Yes, we can do that:
```js
await expect(page.locator('.image-btn:visible')).toHaveCount(1);
```
But if selector fails, we don't know if there are no `.image-btn` at all, or there are no visible `.image-btn`.
So, we need "debugging" of selectors, e.g.:
```
selecting .image-btn...        1 found
   selecting :visible...       FAIL
```

**Comment by aslushnikov** [comment]
Forwarding this to Dmitry and marking this as 1.18 so that Dmitry takes a look once he's from vacation.

**Comment by pavelfeldman** [comment]
Locators are strict, it means that the check

```js
await expect(imageBtn).toHaveCount(1);
```

is not necessary, it is done automatically.

**Comment by 1aerostorm** [comment]
@pavelfeldman what do you meaning?
```js
await expect(imageBtn).toBeVisible(); // is same as await expect(imageBtn).toHaveCount().toBeVisible();?
```
No. If there are 2 pcs of imageBtn, we don't know about that, but that is a bug. Please read issue again.

**Comment by yury-s** [comment]
> No. If there are 2 pcs of imageBtn, it will not fail (both buttons are visible), but that is a bug. Please read issue again.
> ```

If the selector resolves to 2 elements you'll get 
```
expect.toBeVisible: Error: strict mode violation: ".image-btn" resolved to 2 elements:
```

**Comment by dgozman** [comment]
> But if selector fails, we don't know if there are no `.image-btn` at all, or there are no visible `.image-btn`. So, we need "debugging" of selectors, e.g.:
> 
> ```
> selecting .image-btn...        1 found
>    selecting :visible...       FAIL
> ```

I like this proposal. All the information is there, we just need a way to nicely present it.

**Comment by gajus** [comment]
There is https://github.com/mattphillips/jest-chain which could be a helpful building block for this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
