### ISSUE TITLE
[Question] How to get desired window inside electronApp.evaluate and using electronApp.on('window')

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [microsoft/playwright#11095]
**Using electronApp.waitForEvent('window'):**
I tried this code for getting desired page, but it's only getting fired for first window which is not desired page (then timeout):

```
const window = await electronApp.waitForEvent('window', async window => {
      console.log('title', await window.title())
      if ((await window.title()) === 'Repeato') return true
      return false
    })
```
If I just remove the await before electronApp.waitForEvent then it fires for each window but in that case next code will fail unless we've desired page.

Also tried like this but no success:
```
  const window = await electronApp.waitForEvent('window', {
      predicate: async window => {
        console.log('title', await window.title())
        if ((await window.title()) === 'Repeato') return true
        return false
      },
      timeout: 100000
    })
  ``` 
  
   **Inside electronApp.evaluate:**
   Same problem is there windows order is not consistent and we've to find the specific window.

```
await electronApp.evaluate(async ({ BrowserWindow }) => {
       // need to find desired window here
       const selectedWindow = BrowserWindow.fromId(windowToCheck)
       // above solution work sometimes but not all the time
  }, windowToCheck));
  ```
 Tried to use `BrowserWindow.getAll()` and then filter by title it didn't work, in some cases were having same titles for different windows.

**Comment by aslushnikov** [comment]
> Tried to use BrowserWindow.getAll() and then filter by title it didn't work, in some cases were having same titles for different windows.

@ahmedmukhtar1133 so how exactly do you want to differentiate windows?

**Comment by ahmedmukhtar1133** [comment]
@aslushnikov I belive only option to filter windows is using title but `BrowserWindow.getAll().map(async w => await w.title()` in some cases doesn't have the correct titles. Sometimes it has one missing title for a window or repeated.
*Expected output:*
['Loading', 'Main', 'Worker']

But getting:
['Loading', 'Loading', 'Worker'] OR ['Main', 'Main', 'Worker']

**Comment by ahmedmukhtar1133** [comment]
@aslushnikov  How can I use waitForEvent for getting my desired window for playwright page?

**Comment by pavelfeldman** [comment]
Could you elaborate on what you mean by 'get desired window'? Do you need BrowserWindow instance? or Playwright page? What is your scenario?

**Comment by ahmedmukhtar1133** [comment]
@pavelfeldman Please check my above messages, I want to get both Playwright page, and BrowserWindow as well to click and verify electron menu items.

Problem statement is mentioned in ticket.

**Comment by dgozman** [comment]
@ahmedmukhtar1133 Your snippets look good. Perhaps, page title changes dynamically in one or more of your pages? If you could share a full repro with us, we can take a look. Otherwise, you'll have to debug yourself.

**Comment by ahmedmukhtar1133** [comment]
I'll setup another repo for you to take a look.

**Comment by ahmedmukhtar1133** [comment]
Meanwhile I'm setting up different repo for you.
Can someone let me know, what is wrong with below code.

```
const electronApp = await electron.launch({ args: ['.'] })
  let count = 0
  await electronApp.waitForEvent('window', {
    predicate: window => {
      count++
      console.log('count', count)
      if (count === 3) return true
      return false
    },
    timeout: 100000
  })
```
  
  I want to just wait till all window loaded, but waitForEvent is getting fired only once and then timeout.

**Comment by dgozman** [comment]
@ahmedmukhtar1133 This code looks good. It should call the predicate for each new window. Perhaps the first/second window is shown immediately after launch, so it is too late to call `waitForEvent`? You can check all existing windows with `electronApp.context().pages()`.

**Comment by ahmedmukhtar1133** [comment]
No, it's not too late because my 2nd and 3rd window load bit late.

If I just remove `await` before `electronApp.waitForEvent` then it get fired for each window.

I can't use `electronApp.context.pages` because it don't provide all the windows at very start. I've mentioned reason above 2nd and 3rd window take sometime.

**Comment by ahmedmukhtar1133** [comment]
Here is the sample repo:
https://github.com/ahmedmukhtar1133/playwright-electron-sample

Take a look at `tests/App.test.js` file `startApp` function. I tried to use `waitForEvent` it didn't work, also tried with `electronApp.on('window')` but it's only getting fired but i've 3 windows.

**Comment by ahmedmukhtar1133** [comment]
On some systems it work but on some machines it doesn't work.

**Comment by ahmedmukhtar1133** [comment]
@dgozman Did you check my repo?

**Comment by jim-docker** [comment]
We are experiencing a similar issue for our integration tests. It's only happening on windows, and only since we tried to upgrade our app to use Electron 14.2.4 (from 13.6.1). Our app opens a splash window followed by our main window. Our tests  wait for the main window to appear: https://github.com/lensapp/lens/blob/18ec1432627cd1ff1246dfe0897ddd2dca59f0cf/integration/helpers/utils.ts#L27

We've tried `ElectronApplication.windows()`, `ElectronApplication.context().pages()` and `waitForEventWindow('window', ...)`. Sometimes they detect our main window, sometimes they don't. Tried playwright versions 1.15.2, 1.17.1, 1.18.0.

**Comment by pavelfeldman** [comment]
I looked at the repo, but could not follow the logic there. Could you explain what you are trying to do or send a snippet with clear steps to follow, expected and actual behavior? You can't be calling waitForEvent w/o testing the windows() array first - there is a race that makes you miss windows sometimes. It'd be nice to understand what you are actually trying to do.

**Comment by aslushnikov** [comment]
I'll close this for now. Please feel free to re-open with a good repro!

**Comment by 2BC-Wasabi** [comment]
I don't know if you still need this, this is how i assign windows, 
i have class with static members to save the pages to
i use pages urls as ids so maybe it will also help you 

`

    class ElectronAppController {

      static electronApp: ElectronApplication;
    
      static firstWindow: Page;
    
      static secondWindow: Page;
    
      static thirdWindow: Page;

      static async launchApp() {
        ElectronAppController.electronApp = await electron.launch({
          executablePath: path,
        });
        ElectronAppController.electronApp.on('window', async (page) => {
          ElectronAppController.assignWindows(page);
        });
        mywindows =
          await ElectronAppController.electronApp.windows();
        for (
          let index = 0, l =mywindows.length;
          index < l;
          index += 1
        ) {
          ElectronAppController.assignWindows(
            mywindows[index]
          );
        }
      }
      private static assignWindows(page: Page) {
        const myurl = path.basename(page.url());
        if (myurl === 'window1.html') {
          ElectronAppController.firstWindow= page;
        }
        if (myurl === 'window2.html') {
          ElectronAppController.secondWindow= page;
        }
        if (myurl === 'window3.html') {
          ElectronAppController.thirdWindow= page;
        }
        return true;
      }
    }
`
