### ISSUE TITLE
[BUG] mouse.wheel not working for webkit mobile devices on Docker containers

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#11101]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 12.22
- Browser: Webkit (iPhone12)
- Extra: Run the below test on Docker container

**Code Snippet**

```javascript
//playwright.config.js
use: {
  screenshot: 'on',
},
projects: [
  {
      name: 'Mobile Safari',
      use: devices['iPhone 12'],
  },
 ],
};
  
// sample.spec.js
const { test } = require('@playwright/test');

test(`mouse wheel doesn't work on iPhone12 device on Docker`, async ({ page }) => {
  await page.goto('https://playwright.dev/docs/api/class-mouse');
  await page.mouse.wheel(0, 600);
});
```

**Describe the bug**
Run the above snippet locally and observe the screenshot. It is noticed that the mouse.wheel actually happened and the page scrolled.

Now run the above snippet in docker container and observe the screenshot. **It is noticed that the mouse.wheel didn't happen and the page is not scrolled**. Only happening on webkit mobile devices (in my case iPhone12). Works fine on Pixel5, desktop chrome, desktop webkit.

**Comment by aslushnikov** [comment]
This looks very similar to https://github.com/microsoft/playwright/issues/10183. Can you please try on tip of tree to see if it's working? 

```
npm install @playwright/test@next
```

**Comment by Nav-2d** [comment]
Hi @aslushnikov - I tried the tip of tree as well but same issue. Looking at this [PR](https://github.com/microsoft/playwright/pull/10946/files), it seems like it is not supported in mobile webkit or am I wrong here?

**Comment by aslushnikov** [comment]
Ah indeed! Let's wait for Yury to come back from vacation. He's been looking into this

**Comment by yury-s** [comment]
Mouse wheel is not supported in mobile webkit, after #10946 you should get an exception saying that if wheel api is accessed with mobile emulation on.

**Comment by Nav-2d** [comment]
@yury-s - Just a followup question: The `await page.mouse.wheel(0, 600);` used to work on local OS and used to fail on Docker containers in `1.17.2`. 

In `1.18.0`, it will throw an error `Mouse wheel is not supported in mobile WebKit` running both locally as well as docker. Is it due to webkit engine changes? If yes, what is the alternative you suggest to scroll? Thanks!
