### ISSUE TITLE
[Question]: Firefox performance issue on running WebAssembly modules.

### ISSUE THREAD

**Issue by ryanking13** [microsoft/playwright#11102]
### Your question

First of all, thanks for the amazing project.

In [Pyodide](https://github.com/pyodide/pyodide), we are considering a migration of our test framework from Selenium to Playwright. Pyodide runs the CPython interpreter in the browser through WebAssembly, so our tests require running complex jobs using WASM.

However, when I tried to use Playwright's firefox browser for WASM testing, the total running time significantly (2-4x) increased compared to the Selenium firefox driver(geckodriver) that we originally used.

I found that there is a performance issue on the firefox([playwright#1396](https://github.com/microsoft/playwright/issues/1396)), but that is about closing the browser and making new pages, not about evaluating JS or WASM codes, so I think this is a separate issue.

Note that we are not experiencing this performance issue in chromium.
(Running same complex WASM task with Selenium chromedriver or with Playwright chromium takes almost same time)

## How to reproduce

```python
# Playwright-python
import time
from playwright.sync_api import sync_playwright

def run(page):
    page.evaluate("""
        WebAssembly.instantiateStreaming(fetch("loop.wasm"))
        .then(function(results) {
            let run_loop = results.instance.exports.run_loop;
            run_loop(987_654_321_0n);
        })
    """)


with sync_playwright() as p:
    firefox = p.firefox.launch()
    page = firefox.new_page()
    page.goto("http://localhost:8000")
    st = time.time()
    run(page)
    ed = time.time()
    print(ed - st)
```

```python
# Selenium

import time
from selenium.webdriver import Firefox
from selenium.webdriver.firefox.options import Options

def run(driver):
    driver.execute_async_script("""
        (async () => {
            var callback = arguments[arguments.length - 1];
            WebAssembly.instantiateStreaming(fetch("loop.wasm"))
            .then(function(results) {
                let run_loop = results.instance.exports.run_loop;
                callback(run_loop(987_654_321_0n));
            })
        })()
    """)


options = Options()
options.add_argument("--headless")
firefox = Firefox(executable_path="geckodriver", options=options)
firefox.set_script_timeout(60)
firefox.get("http://localhost:8000")
try:
    st = time.time()
    run(firefox)
    ed = time.time()
    print(ed - st)
finally:
    firefox.quit()
```

__result__

```
Playwright: 32.482 (sec)
Selenium: 4.523 (sec)
```

  <details>
    <summary>Versions</summary>

- OS: Ubuntu 18.04 (Also tested in Windows 10)
- Playwright-python: 1.17.2
- Selenium: 4.1.0
- Selenium Firefox: 95.0.2
- Selenium Geckodriver: 0.30.0

  </details>

run_loop() function in `loop.wasm` simply runs loop inside WASM with the amount of given parameter. (See: [loop.wat](https://github.com/ryanking13/selenium-playwright-firefox/blob/main/loop.wat))

[This repository](https://github.com/ryanking13/selenium-playwright-firefox) contains a little more information and binaries.

Thanks, in advance!

**Comment by aslushnikov** [comment]
Thank you for the repro, I'll take a look

**Comment by aslushnikov** [comment]
@ryanking13 turns out this happens due to Playwright using firefox's debugger functionality.

You can reproduce the same behavior using stable Firefox, opening devtools, and navigating to the page:

```html
<!-- index.html -->
<!DOCTYPE html>

<script>
async function log(text) {
  const p = document.createElement('p');
  p.textContent = text;
  document.body.append(p);
}
async function run() {
  const loadMs = Date.now();
  const results = await WebAssembly.instantiateStreaming(fetch("loop.wasm"));
  log('loadMs: ' + (Date.now() - loadMs));
  const run_loop = results.instance.exports.run_loop;
  const computeMs = Date.now();
  run_loop(987_654_321_0n);
  log('computeMs: ' + (Date.now() - computeMs));
}
run();
</script>
<h1>yo</h1>

```
