### ISSUE TITLE
[Question] How do I trigger custom events from Playwright test?

### ISSUE THREAD

**Issue by guillermoarellano** [microsoft/playwright#11109]
Hi,

I am having trouble firing a custom event and dispatching it via the window object. Can somebody help me resolve this issue?

I am getting the following error: `ReferenceError: CustomEvent is not defined`

This is my test script:

```typescript
import { test, expect } from '@playwright/test';


function fireCustomEvent(response: any) {
  var event = new CustomEvent('payment.success', {
    detail: response,
    bubbles: true,
    cancelable: true
  });
  window.dispatchEvent(event);
}

test.only('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');

 fireCustomEvent();

  await expect(title).toHaveText('Playwright');
});

```

**Comment by aslushnikov** [comment]
@guillermoarellano the test itself is run inside node.js - check out the explanation in our documentation [here](https://playwright.dev/docs/evaluating). And consequently, node.js doesn't have a `CustomEvent` class.

To dispatch event on the window inside page, you should use [`page.evaluate()`](https://playwright.dev/docs/evaluating) method:

```ts
import { test, expect } from '@playwright/test';

function fireCustomEvent(response: any) {
  var event = new CustomEvent('payment.success', {
    detail: response,
    bubbles: true,
    cancelable: true
  });
  window.dispatchEvent(event);
}

test.only('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await page.evaluate(fireCustomEvent); //                            << Notice this page.evaluate call

  await expect(title).toHaveText('Playwright');
});
```

**Comment by guillermoarellano** [comment]
@aslushnikov This worked flawlessly. Thank you very much for teaching me and helping resolve the problem. I wish you a Happy New Year!

Best wishes,
Guillermo Arellano
