### ISSUE TITLE
operate multiple browsers in headless:false mode [Question]

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright#11106]
Hi,
I need to operate multiple browsers n headless:false mode at the same time.While I am operating a browser, other browsers will enter the background. However, I need to operate other browsers. What parameters do I need to set for the browser?

**Comment by shirshak55** [comment]
what do you mean by other browser goes to the background?

**Comment by guillermoarellano** [comment]
The other browsers will open and run overlapped on top of each other. This is done because the tests are running in parallel, to speed up test suite completion. Are you looking to run in non-headless mode and have each of the browser tests run in sequence? What is the requirement?

**Comment by aslushnikov** [comment]
Please re-file with a clearer description!
