### ISSUE TITLE
[Question] Is there a way to disable timeout logs in Playwright ?

### ISSUE THREAD

**Issue by suchcodemuchwow** [microsoft/playwright#11117]
Yes sometimes these are necessary but in my usecase it just pollutes the output. Is there a way to prevent logging timeout errors specific to locator or globally ? 

```
locator.isEnabled: Timeout 200ms exceeded.
=========================== logs ===========================
waiting for selector "text=Start messaging"
============================================================ 6620439
```

**Comment by aslushnikov** [comment]
@suchcodemuchwow you can pass 0 to the method timeout or set it up as default value per context: https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-timeout

**Comment by davidbielik** [comment]
Hi @aslushnikov is there a way to disable the logs without modifying any of the timeout values?
