### ISSUE TITLE
[BUG]playwright launches default context also when we use own context in tests

### ISSUE THREAD

**Issue by lakibm77** [microsoft/playwright#11110]
test('Login to the application3', async ({browser , page}) => {   
        
        const context = await browser.newContext();
        page = await context.newPage();
        const loginpage = new _loginPage(page)

             })

I am defining my own context in generalised way to serve some benefits but it launches 2 instances of the browser one being the default context with blank browser. its quite annoying to see extra browser for all test cases

**Comment by aslushnikov** [comment]
@lakibm77 you're destructuring `page` in your test arguments, so a default page is created for you. Remove the page from test arguments, like this:

```js
test('Login to the application3', async ({browser}) => {   
    const context = await browser.newContext();
    const page = await context.newPage();
    const loginpage = new _loginPage(page)
});
```
