### ISSUE TITLE
[Feature] I want to handle multiple environments and pass env name from CLI.

### ISSUE THREAD

**Issue by lakibm77** [microsoft/playwright#11128]
i have defined .env file like below

```
QA_App_Url = https://****************************.com
QA_email = example@something.com
QA_Password = ******************
```

and a class to initialize those variables.

```
require('dotenv').config()
export default class TestBase{
    public static App_Url = process.env.Enviroment +'_App_Url';
    public static Email = process.env.Enviroment+'_email';
    public static Password = process.env.Enviroment+'_password';

}
```

now, i should have an option to pass Environment as variable from CLI. i am using below but Environment value is taking undefined.
```
npx playwright test .\tests\paralleldemo\Envdemo.spec.ts --reporter=line,allure-playwright --project='iPhone 11' cross-env Enviroment=QA
```

can some one help me if there already a way to achive this.

**Comment by aslushnikov** [comment]
cross-env should go before the command:

```sh
cross-env Enviroment=QA npx playwright test .\tests\paralleldemo\Envdemo.spec.ts --reporter=line,allure-playwright --project='iPhone 11' 
```

**Comment by lakibm77** [comment]
Thank you so much for the resolution. however, it works only the below way and when i give the command directly from power shell/cmd it says cross-env not recognised..
"scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "testsmoke": "npx playwright test tests/test.spec.ts --project=chromium",
    "Testenv": "cross-env Enviroment=QA npx playwright test /tests/paralleldemo/Envdemo.spec.ts --project=chromium"
  },

**Comment by aslushnikov** [comment]
@lakibm77 ah, right! It should be `npx cross-env` if you're in powershell / cmd:

```
npx cross-env Enviroment=QA npx playwright test .\tests\paralleldemo\Envdemo.spec.ts --reporter=line,allure-playwright --project='iPhone 11' 
```

**Comment by lakibm77** [comment]
Thank you so much this works fine....

**Comment by Vinodkomeershetty** [comment]
@lakibm77 

> i have defined .env file like below
> 
> ```
> QA_App_Url = https://****************************.com
> QA_email = example@something.com
> QA_Password = ******************
> ```
> 
> and a class to initialize those variables.
> 
> ```
> require('dotenv').config()
> export default class TestBase{
>     public static App_Url = process.env.Enviroment +'_App_Url';
>     public static Email = process.env.Enviroment+'_email';
>     public static Password = process.env.Enviroment+'_password';
> 
> }
> ```
> 
> now, i should have an option to pass Environment as variable from CLI. i am using below but Environment value is taking undefined.
> 
> ```
> npx playwright test .\tests\paralleldemo\Envdemo.spec.ts --reporter=line,allure-playwright --project='iPhone 11' cross-env Enviroment=QA
> ```
> 
> can some one help me if there already a way to achive this.

I was able to try the above approach , But I see i am unable to initialise the class variable with env variable am i missing anything here,

**Comment by kollasrujana** [comment]
"([a-zA-Z0-9]+)":\s*"([^"]+)"
