### ISSUE TITLE
[Question] trx reporter in Azure pipeline

### ISSUE THREAD

**Issue by onno-amsterdam** [microsoft/playwright#11121]
Hi Playwright, 

Currently I'm refactoring my Playwright framework to use the Playwright test runner instead of Jest. I run my tests in an Azure pipeline and use trx format for reporting - currently using the jest-trx-results-processor package as reporter.

I'm looking into how to do trx reporting in Azure when using the Playwright test runner but can't find anything on this subject. Is there a solution for reporting in Azure pipeline? Can you point me into the right direction?

My project is in Node and Typescript.

Thank you! 

Regards, 
Onno

**Comment by aslushnikov** [comment]
Hey @onno-amsterdam,

There's no built-in trx reporter, but you can create your own reporter using the [reporter API](https://playwright.dev/docs/api/class-reporter).

**Comment by mxschmitt** [comment]
Feature request was moved to #11143

**Comment by jwalakom** [comment]
@aslushnikov 

We want to generate videos as attachments for the failed functional test cases on our ADO Pipelines using Playwright. Can you please let me know if there is any other way to do this? Especially using the reporter API. Thanks!
