### ISSUE TITLE
[Question] is it possible to turn tracking prevention on ?

### ISSUE THREAD

**Issue by dssnoha** [microsoft/playwright#11120]
is it possible to turn tracking prevention on during headless tests ?

**Comment by aslushnikov** [comment]
@dssnoha what browser are we talking about?

**Comment by dssnoha** [comment]
all types of browser that are available  in playwright.

**Comment by aslushnikov** [comment]
@dssnoha we don't do anything special regarding this feature on Playwright side, so browsers are run with whatever their defaults are. What makes you think it's off by default?

**Comment by dssnoha** [comment]
@aslushnikov it's the default in all my browsers even when i used the debugger in playwright headless tests it was the same.

**Comment by aslushnikov** [comment]
@dssnoha I still don't follow what's going on and how we can help. So can you please explain in details what's the expected behavior, what you do, what you observer, and why it's not what you expect?

I'd love to follow your steps locally and see it all for myself.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
