### ISSUE TITLE
[Feature] API Testing: Easy Opt-Out of Platform Name in Snapshots

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#11134]
We use Playwright Test for API testing and make heavy use of snapshots on textual data that's been normalized from JSON API responses.

Currently, Playwright Test will embed the platform name by default in the snapshot, but this doesn't make sense for API Testing.

I stumbled a bit trying to find out how to disable it. (I saw `snapshotDir` could be overriden in the playwright.config.ts, but not `snapshotSuffix`.)

Ultimately, I figured out to use a `beforeEach` hook and/or an `auto: true` fixture. However, it would be nice to have an easy/ergonomic way to opt out of the platform-embedding behavior globally.

**Comment by rwoll** [comment]
Just posted https://github.com/microsoft/playwright/pull/11132 in case the team wants to make it a top-level config. The work around (`auto` hook works for now, but it took my digging through playwright's own internal tests to see that was viable option).

**Comment by aslushnikov** [comment]
Thanks Ross! Let's wait for the folks to come back so that we can discuss this.

As usual, I'll assign 1.18 and Dmitry to this so that we don't loose track :-)

**Comment by rwoll** [comment]
Thanks! Sounds good! The PR introduces it into the public API 👻 , so it def warrants a discussion. 😄  The workaround works for now so this is **not** blocking anything FWIW. 

Perhaps there is also a more holistic way of solving and thinking about API Testing. For example, when doing API testing (i.e. non-browser testing) w/ Playwright Test, maybe there are other preset configs, fixtures, etc. that would be nice, so maybe there is a `testingMode: "browser" | "api" | …` config that sets these by default (or something like the Device Emulation usage `{...PRESETS["api"], // rest of pw config changes}`). I don't know what else would go there other than snapshotSuffix atm., but that at least hopefully inspires a discussion on what does API Testing look like with Playwright and what might be helpful to have in there.

Regardless, some of the test cases I can break out and merge independently as they test current documented, but untested behavior of snapshots. (I'll wait until folks are back to see if that's necessary.)

Cheers! 🎉

**Comment by ronnyhaase** [comment]
I have a similar issue, may I ask how exactly the workaround looks like @rwoll? Thanks!

**Comment by rwoll** [comment]
@ronnyhaase See below for an example related to this specific issue. For more general information on auto-fixtures, see https://playwright.dev/docs/test-fixtures#automatic-fixtures.

```ts
// base.ts
import { test as _test } from "@playwright/test";

export const apiTest = _test.extend<{ _autoSnapshotSuffix: void }>({
    _autoSnapshotSuffix: [async ({ }, use, testInfo) => {
        testInfo.snapshotSuffix = "";
        await use();
    }, { auto: true }]
});
```

```ts
// example.spec.ts
import { expect } from "@playwright/test";
import { apiTest } from "../base";

apiTest("it works", () => {
  expect("a").toMatchSnapshot("example.txt");
});
```

Let me know if this works for you!

NB: Exported the test def as `apiTest` since we have multiple test variants defined in `base.ts` (e.g. `adminUserTest`, `uiTest`, etc.), but if your project just has one type of test you could call it `test` instead of `apiTest`.

**Comment by ronnyhaase** [comment]
Thanks a lot @rwoll !

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by kevin940726** [comment]
Just an FYI, it should be trivial with the new [`snapshotPathTemplate`](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template) option now.
