### ISSUE TITLE
[Question] The usage problem in centos system

### ISSUE THREAD

**Issue by oushu1haojianqiang1** [microsoft/playwright#11138]
I'm running Playwright in centos with headless mode. I specified in the task to skip downloading browsers and provide a local browser directory, but a new browser is downloaded every time.I am very worry.

**Comment by aslushnikov** [comment]
> I'm running Playwright in centos with headless mode. I specified in the task to skip downloading browsers and provide a local browser directory, but a new browser is downloaded every time.I am very worry.

@oushu1haojianqiang1 could you please show what exactly is your configuration?

**Comment by oushu1haojianqiang1** [comment]
npm 6.14.6
npx  6.14.8
playwright 1.17.1
chromepath = ~/.cache/ms-playwright/chromium-939194/chrome-linux/chrome
I run it using Java programs

![image](https://user-images.githubusercontent.com/83932262/147722298-97480137-aaad-4a0f-a9c2-c1e54f98c910.png)

Are these?

My English is not good, may have impolite tone, forgive me

**Comment by oushu1haojianqiang1** [comment]
![image](https://user-images.githubusercontent.com/83932262/147722509-d14258c2-cfeb-45e9-b70d-c343448855ba.png)
Even though browser-skipping download is set, some process is still downloading it

**Comment by aslushnikov** [comment]
> Even though browser-skipping download is set, some process is still downloading it

@oushu1haojianqiang1 how do you set browser skipping?

**Comment by oushu1haojianqiang1** [comment]
![image](https://user-images.githubusercontent.com/83932262/147722971-6491f4b8-6432-40aa-987c-aff2092d99cf.png)
set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

**Comment by aslushnikov** [comment]
Ah! You should set in the powershell instead:

```powershell
set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 java myapp.java
```

**Comment by oushu1haojianqiang1** [comment]
ok,thanks

**Comment by oushu1haojianqiang1** [comment]
![image](https://user-images.githubusercontent.com/83932262/147726163-66c60585-e7e6-4cbb-9f20-3305ff64d6b9.png)

like this?

**Comment by oushu1haojianqiang1** [comment]
It's in the ~/.bashrc file

**Comment by oushu1haojianqiang1** [comment]
But it didn't work

![image](https://user-images.githubusercontent.com/83932262/147726415-3bbd9025-5e01-4c16-8515-4588d6b7d116.png)

Still downloading the browser kernel

**Comment by oushu1haojianqiang1** [comment]
One last question, playwright is version 1.17.0, can the nodeJS version use 12.x ？

**Comment by oushu1haojianqiang1** [comment]
![image](https://user-images.githubusercontent.com/83932262/147737204-5a4ff416-26eb-49d5-bff5-c399ad8efdeb.png)
Now I have a new discovery

**Comment by aslushnikov** [comment]
> It's in the ~/.bashrc file

@oushu1haojianqiang1 I'm confused. Is this CentOS, windows, or Ubuntu? 

In case of CentOS like stated in the original question, then Playwright doesn't support it out-of-the-box. You might try installing Chrome separately from official sources, but this is not an officially supported workflow. 

If this is windows & Powershell, then you should not use `.bashrc`. 

In case of ubuntu, bashrc is the right thing!

**Comment by oushu1haojianqiang1** [comment]
Thank you for your answer,This is a centos system
感谢
