### ISSUE TITLE
[Question]how to locate several elements at once?

### ISSUE THREAD

**Issue by brzssh** [microsoft/playwright#11148]
is there something similar  to find_by_element**s**(in selenium).

i would like to locate several elements and iterate over them

i tried to 

```
    tooltips = page.locator('//*[@class="dropdown-header"]//*[@class="dropdown-menu-label"]')
```

but got error:
playwright._impl._api_types.Error: Error: strict mode violation: "xpath=//*[@class="dropdown-header"]//*[@class="dropdown-menu-label"]" resolved to 2 elements:
    1) <div class="dropdown-menu-label">User</div> aka playwright.$("text=User")
    2) <div class="dropdown-menu-label">Role</div> aka playwright.$("text=Role")

or is there a way to unstrict it?

**Comment by Nav-2d** [comment]
Maybe this can help - https://playwright.dev/docs/next/locators#lists
