### ISSUE TITLE
[Question]: How can playwright achieve an effect like 'ActionChains(driver).move_to_element(element).click(element).perform()'?

### ISSUE THREAD

**Issue by photkey** [microsoft/playwright#11142]
### Your question

I'm trying to get familiar with playwright today, and tried to put it on my work. The thing is that the website I tested has an element which needs to hovering for a while before it changed color and can be clicked. I used to use selenium to achieve that, which is `ActionChains(driver).move_to_element(element).click(element).perform()`. But in playwright, I have tried clicked directly or hovered before that.
So how can I achieve the same effect with playwright? Thanks a alot!

**Comment by aslushnikov** [comment]
> But in playwright, I have tried clicked directly or hovered before that.

@photkey Playwright's click (i.e. [`page.click()`](https://playwright.dev/python/docs/api/class-page#page-click)) moves mouse over the element first and then clicks the element. So what exactly didn't work for you?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
