### ISSUE TITLE
[Question] Is it possible to use playwright.config.ts webServer for multiple servers?

### ISSUE THREAD

**Issue by leobastiani** [microsoft/playwright#11141]
I wish I could be able to use a server for each worker and available then for each port.
For example:

```typescript
const config: PlaywrightTestConfig = {
  webServer: {
    command: `PORT=${8000 + workerIndex} docker-compose up`,
    port: 8000 + workerIndex,
  }
}
```

Is it possible?

**Comment by aslushnikov** [comment]
@leobastiani Not possible yet; there's a feature request for this though: https://github.com/microsoft/playwright/issues/8206

Please upvote to stay in the loop!

**Comment by leobastiani** [comment]
Thank you, it's a bit different from what I see in this PR although it's still related
