### ISSUE TITLE
[Feature] Allow to register selector engine dependencies in addition to selector engine function itself

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1114]
Problem: I would like to register a custom selector engine that relies on a js library.

I use `page.evaluate` and `page.evaluateOnNewDocument` to inject this library and set it on the `window`. When I try to access this within the custom selector engine, I cannot because it seems to run in a separate playwright utility world context.

How do you recommend registering a custom selector engine that relies on a js library?

**Comment by jperl** [comment]
After inspecting the code it seems you use webpack to bundle the selector library for the browser. So it seems I can just depend on it, and it should be bundled. I'll reopen if that approach does not work.

**Comment by jperl** [comment]
It seems I could hack it by appending to  [`selectors._sources]( https://github.com/microsoft/playwright/blob/05d4746eb5e31963545843f076584831206a57b5/src/selectors.ts#L37-L40) 

https://github.com/microsoft/playwright/blob/d97ea708046066810b364056bc67904c4355a16b/src/dom.ts#L90

I will try that 🙏

**Comment by dgozman** [comment]
We currently use [webpack](https://github.com/microsoft/playwright/blob/master/src/injected/zsSelectorEngine.webpack.config.js) for built-in engines - it bundles all dependencies to a single eval string.

**Comment by jperl** [comment]
It does not seem to bundle referenced code. Example:

```
const playwright = require("playwright");

const myHelper = () => true;

const createMySelectorEngine = () => {
  return {
    name: "my",

    create(root, target) {
      return undefined;
    },

    // Returns the first element matching given selector in the root's subtree.
    query(root, selector) {
      if (myHelper()) {
        return root.querySelector("body");
      }

      return null;
    },

    queryAll(root, selector) {
      return undefined;
    }
  };
};

(async () => {
  await playwright.selectors.register(createMySelectorEngine);

  const browser = await playwright.chromium.launch({ headless: false });
  const page = await browser.newPage();

  await page.$("my=something");
})();
```

```
(node:68662) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: myHelper is not defined
    at Object.query (__playwright_evaluation_script__:739:7)
    at Injected.querySelector (__playwright_evaluation_script__:252:33)
    at __playwright_evaluation_script__:1:42
    at CRExecutionContext.evaluate (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/chromium/crExecutionContext.js:85:19)
    at async FrameExecutionContext._$ (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/dom.js:77:24)
    at async Frame.$ (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/frames.js:475:24)
    at async /Users/jon/dev/examples/playwright-repros/selector-engine.js:34:3
  -- ASYNC --
    at Frame.<anonymous> (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/helper.js:54:23)
    at Page.$ (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/page.js:129:33)
    at Page.<anonymous> (/Users/jon/dev/examples/playwright-repros/node_modules/playwright-core/lib/helper.js:55:31)
    at /Users/jon/dev/examples/playwright-repros/selector-engine.js:34:14
(node:68662) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:68662) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jperl** [comment]
I am able to hack around this with this line: `playwright.selectors._sources.push(`window.myHelper = () => true`);`

Can an API to include external helper scripts be supported? The selector logic we have is more complex than what would fit well inside those functions.

**Comment by dgozman** [comment]
API for adding dependencies is not obvious to me yet. Let me change this to a feature request. 

Meanwhile, I suggest to pass a string to `selectors.register` and compile a string in advance, like we do for our built-in selectors. See [webpack config](https://github.com/microsoft/playwright/blob/master/src/injected/zsSelectorEngine.webpack.config.js) we use.

**Comment by jperl** [comment]
Ah I overlooked that selectors.register supports passing a string. That should suffice.
