### ISSUE TITLE
[Question] Run playwright docker using Apple Silicon (M1) macs

### ISSUE THREAD

**Issue by jay-espiritu** [microsoft/playwright#11150]
System: macOS Monterey (12.1)

I am struggling to try and run playwright docker. Based on this #7723, it should run when v1.17 is out. but for some reason, it keeps failing when trying to install chrome dependencies (see error below). Am I missing something? Is there documentation to run playwright docker specifically for M1 macs?

**Dockerfile**

``` Dockerfile
FROM mcr.microsoft.com/playwright:bionic-arm64

WORKDIR /app

RUN npm i -D @playwright/test
RUN npx playwright install chrome

COPY package.json package-lock.json ./
COPY . .
```

**Error**

<img width="1010" alt="Screen Shot 2022-01-03 at 20 05 00" src="https://user-images.githubusercontent.com/21213499/147914385-be723d66-1fac-4004-97cf-4bb87209c146.png">

**Comment by aslushnikov** [comment]
@jay-espiritu `npx playwright install chrome` doesn't work on Ubuntu arm64 since there's no officially distributed build of Chrome for ubuntu on arm64. The latest 1.17.1 version of Playwright has a descriptive error for this

**Comment by jay-espiritu** [comment]
Ahh. Thanks @aslushnikov ! I switched to `npx playwright install firefox` and it started working fine.

**Comment by aslushnikov** [comment]
Looks like it's solved then!

**Comment by oliverlockwood** [comment]
A note for "future me" as much as anyone else: in June 2026, on the latest Playwright, running e.g.
`docker run -it --entrypoint /bin/bash mcr.microsoft.com/playwright:v1.50.0-noble` on a Mac M1, and then
`npm install -g @playwright/test` and `npx playwright install chrome` shows that Chrome  is still not supported on `Linux Arm64` as of today.
