### ISSUE TITLE
[Question] Why android test is not running until i manually run adb devices in cmd ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#11154]
I'm not sure if this is a bug or expected behavior that I'm unable to run the android test unless I manually run "adb devices" command in terminal 

![image](https://user-images.githubusercontent.com/32042806/147958631-f1e6eba9-2160-44cc-b56a-6046586dd957.png)

**Comment by dgozman** [comment]
@amrsa1 This is expected. Playwright connects to an Android device through adb, so you have to ensure it's running. Let me know if this does not answer your question.

**Comment by amrsa1** [comment]
Yes i understand, but it might be better to if playwright itself, initializing the the adb server automatically to eliminate the manual intervention.

**Comment by dgozman** [comment]
Let me keep this open then.

**Comment by ShanmukhaGajula** [comment]
> t might be better to if playwright itself, ini

upvote!

**Comment by ShanmukhaGajula** [comment]
> Yes i understand, but it might be better to if playwright itself, initializing the the adb server automatically to eliminate the manual intervention.

upvote!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
