### ISSUE TITLE
[BUG] browserContext.storageState: net::ERR_BLOCKED_BY_CLIENT

### ISSUE THREAD

**Issue by akarabach** [microsoft/playwright#11157]
**Context:**
- Playwright Version: ^1.17.1
- Operating System: Windows
- Node.js version: v14.16.1
- Browser: Chromium
- Extra: Windows 11

**
## System:
 - OS: Windows 10 10.0.22000
 - Memory: 18.48 GB / 31.90 GB
## Binaries:
 - Node: 14.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.12 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
     if (pageNumber % 3 === 0) {
        await context.storageState({path: 'state.json'})
        await page.close()
        await context.close()
        await browser.close()
        browser = await chromium.launch(launchOptions)
        context = await browser.newContext({storageState: 'state.json'})
        page = await context.newPage()
      }
```

**Describe the bug**

```saving context error Error: browserContext.storageState: net::ERR_BLOCKED_BY_CLIENT at site.com```

**Comment by aslushnikov** [comment]
@akarabach could you please provide a repro that we can run locally to reproduce this issue?

**Comment by aslushnikov** [comment]
Please re-file with a good repro that we can run locally & debug!
