### ISSUE TITLE
npx playwright install-deps fails on self-hosted runner

### ISSUE THREAD

**Issue by AlexShemeshWix** [microsoft/playwright#11165]
I have configured github action self hosted runner in my cluster.
My tests failed with 
browserType.launch: 
```
╔════════════════════════════════════════════════════════════╗
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-deps                       ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
```
Ive put
```
- name: install playwright-deps
   run: npx playwright install-deps
```
step into my workflow file
it fails 
```
Run npx playwright install-deps
  npx playwright install-deps
  shell: /usr/bin/bash -e {0}
  env:
    NO_BAIL: true
    NPM_CONFIG_USERCONFIG: /home/docker/actions-runner/_work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
Installing Ubuntu dependencies...
Password: su: Authentication failure
```

What am i doing wrong?

**Comment by aslushnikov** [comment]
@AlexShemeshWix installing dependencies requires root access / sudo. If you have `sudo` on your self-hosted runner, you can just run `sudo npx playwright install-deps` and it should work.

**Comment by TheBlueMatt** [comment]
I'm seeing this error while running as root. It seems `install-deps` should do a root check before it calls out to `su`/`sudo`.

**Comment by mxschmitt** [comment]
Seems like it's already fixed on the `master` branch (see https://github.com/microsoft/playwright/pull/10640), could you check `npm install @playwright/test@next`?

**Comment by TheBlueMatt** [comment]
`npm i -D playwright@next` followed by `install-deps` still seems to have the same issue, but it looks like even beyond that the apt-get line `install-deps` calls is Ubuntu-specific and doesn't support Debian (which I need cause Debian's Rust/C/LLVM WASM toolchain work together and are much better supported), so I'm just manually `apt-get`int which seems to work.

**Comment by aslushnikov** [comment]
@TheBlueMatt Yes, among Linux distributions we only support Ubuntu officially today.

**Comment by andresesfm** [comment]
For reference, I used: 
```wget http://mirrors.kernel.org/ubuntu/pool/main/i/icu/libicu70_70.1-2_amd64.deb 
sudo dpkg -i libicu70_70.1-2_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/universe/libf/libffi7/libffi7_3.3-5ubuntu1_amd64.deb
sudo dpkg -i libffi7_3.3-5ubuntu1_amd64.deb
wget http://mirrors.kernel.org/ubuntu/pool/universe/x/x264/libx264-163_0.163.3060+git5db6aa6-2build1_amd64.deb
sudo dpkg -i libx264-163_0.163.3060+git5db6aa6-2build1_amd64.deb```
to install them
