### ISSUE TITLE
[Question] how to punctual reduce test speed. Problem login with firefox because is too fast (with chromium and webkit no problem)

### ISSUE THREAD

**Issue by AngelLopezBellmont** [microsoft/playwright#11167]
Hi,
We have a problem in firefox because the login page fills up to fast in firefox, and we get error (it does´t happend in chromium, webkit)
**So we want to reduce test speed just in the login part. How can we do it, without reducing the speed in the rest of tests after login?**

- playwright version: 1.16.3
- operating system: locally-> windows, cicd -> azure
- node version: 15.0.1
- npm version: 7.9.0
- browser: error only in firefox: [headless, headed], no error in firefox --debug, chromium,webkit
- auth tool: keycloak

I can login only via [firefox-mode-debug, chromium, webkit] but not via firefox [headless, headed]:

url: https://dmitrygozman.fieldcode.com/
user: dgozman.demo@gmail.com
pass: Dgozman123

```javascript
// @ts-check
const { test } = require('@playwright/test');

test.use({
  headless: false,
  browserName: 'firefox'
});

const baseurl = 'https://dmitrygozman.fieldcode.com/';

test('login', async ({page}) => {
  await page.goto('https://dmitrygozman.fieldcode.com/');
  const field_username  = '[id="username"]';
  const field_password  = '[id="password"]';
  const button_login    = '[id="fc-login-button"]';
  const value_username  = 'dgozman.demo@gmail.com';
  const value_password  = 'Dgozman123';

  await page.click(field_username);
  await page.fill(field_username, value_username);
  await page.click(field_password);
  await page.fill(field_password, value_password);

  await Promise.all([
     page.waitForURL(baseurl),
     page.click(button_login),
  ]);

  console.log('DONE.');
});
```

**Comment by AngelLopezBellmont** [comment]
https://github.com/microsoft/playwright/issues/10832

**Comment by aslushnikov** [comment]
@AngelLopezBellmont Well, this test passes for me, maybe I have a slower machine than yours... However, if you want to type slower, you can use [`page.type()`](https://playwright.dev/docs/api/class-page#page-type) instead of `page.fill`: there's a `delay` option in `page.type` that will wait certain type before each key press.

**Comment by AngelLopezBellmont** [comment]
@aslushnikov it is still not working to me :( . 
I changed fill for type with delay and the same error locally and in cicd  (and again is working in chromium and webkit), btw i add delay as well in click(buttton)
I tryed with different delay times: 100, 200, 500..etc. Always error :( why? 


Error:
```
      25 |
      26 |   await Promise.all([
    > 27 |     page.waitForURL(baseurl),
         |          ^
      28 |     page.click(button_login),
      29 |   ]);
      30 |
```


```javascript
//@ts-check
const { test } = require('@playwright/test');

test.use({
  headless: true,
  browserName: 'firefox'
  //browserName: 'chromium'
  //browserName: 'webkit'
});

test('login', async ({page}) => {
  const baseurl             = 'https://dmitrygozman.fieldcode.com/';
  const field_username      = '[id="username"]';
  const field_password      = '[id="password"]';
  const button_login        = '[id="fc-login-button"]';

  const value_username      = 'dgozman.demo@gmail.com';
  const value_password      = 'Dgozman123';

  await page.goto(baseurl);
  await page.click(field_username);
  await page.type(field_username, value_username,{delay:500});
  await page.click(field_password);
  await page.type(field_password, value_password,{delay:500});

  await Promise.all([
    page.waitForURL(baseurl),
    page.click(button_login, {delay:500})
  ]);

  console.log('DONE.');
});
```

error

**Comment by AngelLopezBellmont** [comment]
@aslushnikov  this is working in the 3 browsers , without waitForURL.
So I guess the problem is 

```javascript
  await Promise.all([
    page.waitForURL(baseurl),
    page.click(button_login, {delay:500})
  ]);
```


```javascript
// @ts-check
const {test} = require('@playwright/test');

test.use({
  headless: true,
  browserName: 'firefox'
  //browserName: 'chromium'
  //browserName: 'webkit'
});

test('login', async ({page}) => {
  const baseurl = 'https://dmitrygozman.fieldcode.com/';
  const field_username = '[id="username"]';
  const field_password = '[id="password"]';
  const button_login = '[id="fc-login-button"]';

  const value_username = 'dgozman.demo@gmail.com';
  const value_password = 'Dgozman123';

  await page.goto(baseurl);
  await page.click(field_username);
  await page.type(field_username, value_username, {delay: 100});
  await page.click(field_password);
  await page.type(field_password, value_password, {delay: 100});
  await page.click(button_login, {delay: 100})

  console.log('DONE.');
});
```

**Comment by aslushnikov** [comment]
@AngelLopezBellmont Ah oh, yes! My bad, I didn't notice this call in your snippet. Indeed you don't need to do any `waitForURL` calls - navigations that happen due to clicks are auto-awaited - check out the description for [`page.click()`](https://playwright.dev/docs/api/class-page#page-click)
