### ISSUE TITLE
[Question] About temporary files

### ISSUE THREAD

**Issue by MrDust0** [microsoft/playwright#11161]
Hi

Lately, i've been trying to deploy Playwright to  my project, but it comes some problems.

When initializing, with code
```
def initial(self):
    browser = self.playwright.chromium.launch(args=['--blink-settings=imagesEnabled=false'],headless=self.headless,executable_path=self.EXECUTABLE_PATH)
    context = browser.new_context(ignore_https_errors=True)
    page = context.new_page()
    return browser, context, page
```
, it hangs when creating page. But it didn't happen before.

Then i checked /tmp/, there are lots of files such like

![image](https://user-images.githubusercontent.com/56252828/148003568-86e88f27-7d01-4723-8465-57a0cdfe9453.png)

i removed that files manually, but it didn't work.

i am asking:
1. why the page can not be created?
2. is there a way to change the directory for the temporary files so that easy to manage?

thanks in advance!

**Comment by aslushnikov** [comment]
> 1. why the page can not be created?

@MrDust0 this is unclear! Does the very first and simple playwright script work (i.e. try launching browser without the custom flags you pass)? What's your operating system? What's your playwright version? When did things stop working? 

If there's still a mystery, can you please run your program with `DEBUG=*` log and send it to us?

> 2. is there a way to change the directory for the temporary files so that easy to manage?

Sure, you can use [`chromium.launch_persistent_context`](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context) instead to specify user data directory.

**Comment by MrDust0** [comment]
@aslushnikov 

my playwright version is 1.16, the os is linux -- i can't tell what exactly it is since it is the custom system of my firm.

Here is my snippet:
```
class Chromium:
    def __init__(self,logger):
        self.playwright = sync_playwright().start()
        self.logger = logger
        self.browser,self.context,self.page = self.initial()
        self.logger.info('browser initialized')

    def initial(self):
        browser = self.playwright.chromium.launch(args=['--blink-settings=imagesEnabled=false'],headless=self.headless,executable_path=self.EXECUTABLE_PATH)
        context = browser.new_context(ignore_https_errors=True)
        page = context.new_page()
        return browser, context, page
```

I want to create a thread of Chromium, and assign some jobs to it. In fact, I keep testing in other parts, i.e., this thread was just created, held on, then closed. The first several times, it could be created -- the log recorded. After many times, i don't exactly know how many, page could not be created. So i don't think it was caused by custom flags.

Well forgive me, i don't know how to use DEBUG mode...

When it occurs, i use this to test: 
```
>>> crm = Chromium(logger)
```
it hangs. Then i abort by Ctrl + C, here is the error message:
![image](https://user-images.githubusercontent.com/56252828/148163505-09c610be-189e-480c-86cd-a5ade6deea5d.png)

If you need more details, please tell me how to get them. ( i am new in programming

thanks!

**Comment by MrDust0** [comment]
It is because that too many chromes open at the same time?
![image](https://user-images.githubusercontent.com/56252828/148199541-e2bfd521-9166-4c3f-af37-16d3263fb9d8.png)
Actually, there should be 10 threads, but 6 recorded. 3 of them created page successfully, and 2 created context, but no page.

**Comment by aslushnikov** [comment]
> It is because that too many chromes open at the same time?

@MrDust0 Very much can be. Try running one browser at a time. If things work there, then yes, the system is starting to starve and thus pages cannot be opened.

**Comment by MrDust0** [comment]
@aslushnikov I see. Then what about these `playwright-artifacts-*` files, can I change their directory? I don't want them be so mess on /tmp :)

**Comment by MrDust0** [comment]
@aslushnikov Well, I am confused.
That case happened, then I close all the threads -- `ps aux` got no chromes. When I tested it again with only one script, it waited still, until I blocked by Ctrl+C
![image](https://user-images.githubusercontent.com/56252828/148347524-755669c5-74e6-4dfb-b909-6929f70224f5.png)
![image](https://user-images.githubusercontent.com/56252828/148348480-c71c96d8-14dd-4dac-8794-8e5bc5dec14c.png)

Please help! -- it is really important for me!

**Comment by MrDust0** [comment]
I've solved this by adding a argument `--disable-gpu` when opening chromium. Now it works well. If anyone meets this, have it a try. ( i don't know why this works
