### ISSUE TITLE
Selecting text nodes or attributes with the XPath selecter does not work

### ISSUE THREAD

**Issue by jezsung** [microsoft/playwright#11174]
When working with `Locator` with XPath expressions, the below syntax seems not to return the correct value.
```
//a/@href
//div/text()
```

Not only the below code's `attr` parameter has the wrong type, but also the actual value is not attribute. 
``` typescript
await page.locator(`//a/@href`).evaluate((attr) => {});
```
Is XPath not fully supported?

**Comment by pavelfeldman** [comment]
Locators only locate elements. What is your use case?

**Comment by jezsung** [comment]
I wanted to fetch data from text nodes or attribute nodes. I know I can do it with other selectors, and `getAttribute` or other helpful functions, it's going to be much easier to be able to select what I want with XPath.

**Comment by pavelfeldman** [comment]
You would typically do

```js
const link = page.locator('a');
await expect(link).toHaveText('Expected');
await expect(link).toHaveAttribute('href', /fragment/);
```

These methods will wait for the expected value or will fail.
