### ISSUE TITLE
Missing dependencies on AWS EC2 linux instance

### ISSUE THREAD

**Issue by jadenmazzone** [microsoft/playwright#11175]
After installing:
```
python -m playwright install
```
Then running an API that uses playwright I was given the following "missing dependencies" error: 

```
playwright._impl._api_types.Error: Host system is missing dependencies!

  Install missing packages with:
      sudo apt-get install gstreamer1.0-libav

  Missing libraries we didn't find packages for:
      libnotify.so.4
      libicui18n.so.66
      libicuuc.so.66
      libwoff2dec.so.1.0.2
      libgcrypt.so.20
      libjpeg.so.8
      libpng16.so.16
      libwebpdemux.so.2
      libwebp.so.6
      libenchant.so.1
      libhyphen.so.0
      libevdev.so.2
      libgudev-1.0.so.0
```

Is it possible to install playwright on an EC2 instance? If so, how do I install the missing dependencies?

**Comment by aslushnikov** [comment]
What's the operating system? Please note that Playwright only supports Ubuntu 18.04 and 20.04.

**Comment by jadenmazzone** [comment]
> microsoft/playwright-python

it's linux-gnu. Seperate question now: are you saying playwright wouldn't work on macOS?

**Comment by jadenmazzone** [comment]
It's linux-gnu. Separate question now: are you saying that playwright wouldn't work on macOS?

**Comment by aslushnikov** [comment]
@jadenmazzone works well on MacOS and Windows. Linux availability depends on linux distribution; Ubuntu 18.04 and 20.04 are officially supported. 

> It's linux-gnu.

So, it depends on what kind of linux-gnu it is.

**Comment by jadenmazzone** [comment]
@aslushnikov here is the OS information:

`NAME="Amazon Linux"
VERSION="2"
ID="amzn"
ID_LIKE="centos rhel fedora"
VERSION_ID="2"
PRETTY_NAME="Amazon Linux 2"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2"
HOME_URL="https://amazonlinux.com/"`

**Comment by aslushnikov** [comment]
@jadenmazzone Looks like it's based on Red Hat Enterprise Linux, which is not officially supported. Feel free to file a feature-request for its support; we'll do it if there's plenty of demand!

**Comment by Ahmed-Soli** [comment]
I know this issue is a bit old, but I recently faced the same problem and managed to get it working on Amazon Linux 2023 by installing the necessary dependencies.

My OS details:

```
Amazon Linux release 2023.6.20250107 (Amazon Linux)
cpe:2.3:o:amazon:amazon_linux:2023
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023.6.20250107"
```

To fix the issue, I installed the following packages:

```bash
sudo dnf install -y libXcomposite libXcursor libXdamage libXext libXi libXtst cups-libs \
libXScrnSaver libXrandr gtk3 pango alsa-lib atk at-spi2-atk at-spi2-core libdrm \
libxkbcommon nss xorg-x11-server-Xvfb libgbm
```

Then I ran:

```bash
playwright install chromium
```

Don't worry if you see warnings like this:

```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
```

That’s expected — Amazon Linux 2023 isn’t officially supported by Playwright, so it defaults to Ubuntu 20.04 builds. In most cases, this fallback works just fine as long as all required system libraries are present — which the above install command covers.

Hope this helps someone else!
