### ISSUE TITLE
[BUG] Web Worker not created when electron app started from playwright

### ISSUE THREAD

**Issue by Bilb** [microsoft/playwright#11189]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Linux 
- Node.js version: 14.16.0
- Browser: Chromiu
- Extra: Electron

```javascript
class WorkerInterface {
  constructor(path, timeout = WORKER_TIMEOUT) {
    this._utilWorker = new Worker(path);
[...] 
```

Web worker is not loaded by the Worker constructor when the electron app is started from playwright.
The only error I get is 

```
utilWorkerPath [...]/contribs/desktop/js/util_worker.js

[...]desktop/js/util_worker.js:1 Failed to load resource: net::ERR_INVALID_ARGUMENT
```

Any idea from where this issue can come? The filepath is fine for both of the env.
I couldn't find any config to enable web workers on playwright, I tried `bypassCSP: true,` too

Thanks for your help

**Comment by pavelfeldman** [comment]
Playwright does not alter the way Electron runs. If you have a repro where Worker starts in Electron app, but does not start when the same app runs using Playwright, please let us know!

**Comment by aslushnikov** [comment]
Please re-file with a good repro that we can run locally & debug!
