### ISSUE TITLE
How to explicit wait for Alert in Playwright .Net

### ISSUE THREAD

**Issue by VinitMeharwal** [microsoft/playwright#11198]
Hi,
I have a scenario where alert will appear after sometime of click.
Where my test is failing as its not able to get alert text.
can you please tell me how i can add explicit wait for alert to present in .Net.

Regards,
Vinit Kumar

**Comment by aslushnikov** [comment]
@VinitMeharwal Please check out these docs: https://playwright.dev/dotnet/docs/dialogs#alert-confirm-prompt-dialogs

**Comment by VinitMeharwal** [comment]
@aslushnikov I have gone through IDialog api doc, there is no way to explicit wait for alert or waitfoEventAsyn(). It's giving information only to accept, dismiss and Message of Alerts

**Comment by pavelfeldman** [comment]
Could you share more about your scenario? It is most likely that your dialog shows up as a result as your own action. Dialogs are modal and blocking, so waiting for them is not a good idea - you can't do anything other than consuming them once they show. You can always create a manual Task and fulfill it from the dialog event.

**Comment by VinitMeharwal** [comment]
Yes, i am automating "https://demoqa.com/" web automation practice side.
there is some alerts action to automate where one alert popup comes after 5 second.
Step to follow -:

1. Navigate to "https://demoqa.com/" 
2. Select "Alerts, Frame & Windows" card
3. Select Alerts Tab from left vertical Menu
4. Click on 2nd "Click Me"
Alerts will popup after 5 second

**Comment by pavelfeldman** [comment]
```cs
var dialogMessage = new TaskCompletionSource<string>();
page.Dialog += (_, dialog) =>
{
    dialog.AcceptAsync();
    dialogMessage.TrySetResult(dialog.Message);
}
await page.ClickAsync("button");
await dialogMessage;
```

**Comment by VinitMeharwal** [comment]
### Tried with your solution, its not working getting same error.

 ```
var dialogBoxMessage = new TaskCompletionSource<string>();
            _page.Dialog += async (_, dilog) =>
            {
                _message = dilog.Message;
                _typeValue = dilog.Type;
                try
                {
                    await dilog.AcceptAsync("Vinit Kumar");
                    dialogBoxMessage.TrySetResult(_message);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Ignored Exception :{ex.Message}");
                }
            };
            await _page.ClickAsync($"#{AlertID}");
            Console.WriteLine(dialogBoxMessage);
            /*if (AlertID.Equals("timerAlertButton"))
            {
                await _page.WaitForTimeoutAsync(6000);
            }*
```

**Comment by dgozman** [comment]
@VinitMeharwal Replace `Console.WriteLine(dialogBoxMessage)` with `Console.WriteLine(await dialogBoxMessage.Task)` to actually wait for the dialog to appear.

**Comment by VinitMeharwal** [comment]
Thank you Team, its working fine now.

**Comment by VinitMeharwal** [comment]
@dgozman In case of Alerts is not popping out, its wating infinitely and execution getting stuck at that point.

**Comment by dgozman** [comment]
@VinitMeharwal That's expected, since you are explicitly waiting for the alert. You have to decide whether you wait for the alert and expect some text there, or you don't 😄

**Comment by VinitMeharwal** [comment]
@dgozman Opps, is there any way to wait for specific time so it will check alert in given time else exit from execution.

**Comment by dgozman** [comment]
```c#
if (await Task.WhenAny(dialogBoxMessage.Task, Task.Delay(5000)) == dialogBoxMessage.Task) {
    Console.WriteLine(await dialogBoxMessage.Task);
} else { 
    Console.WriteLine("No alert in 5 seconds!");
}
```

**Comment by mxschmitt** [comment]
Closing since its answered!
