### ISSUE TITLE
[Question] Webkit versions

### ISSUE THREAD

**Issue by davilo61** [microsoft/playwright#11197]
I see two webkit versions in my local cache:  webkit-1580 and webkit-1578. Will playwright use the more recent versionand should I delete the lower version (1530) ?

**Comment by aslushnikov** [comment]
> Will playwright use the more recent version

@davilo61 every Playwright version uses a particular version of browser and only it. See https://playwright.dev/docs/browsers for details

> should I delete the lower version (1530) ?

It'll be removed automatically when it's no longer needed, e.g. you removed the project that has installed playwright that requires this browser version. See details here: https://playwright.dev/docs/browsers#stale-browser-removal
