### ISSUE TITLE
Not able to launch Chromium

### ISSUE THREAD

**Issue by anjalivaswani86** [microsoft/playwright#11191]
**Context:** : Getting the error :  Failed to install browsers
Error: Failed to download chromium v939194, caused by
Error: Download failed: server returned code 407. URL: https://playwright.azureedge.net/builds/chromium/939194/chromium-win64.zip

playwright = Playwright.create();
	browser = playwright.chromium().launch();

- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ...
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by aslushnikov** [comment]
@anjalivaswani86 HTTP 407 means that you're behind some proxy. See https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy
