### ISSUE TITLE
[Question] Webkit rendering in playwright

### ISSUE THREAD

**Issue by davilo61** [microsoft/playwright#11199]
The installed webkit browser does not render the target drop-down lists in my target SUT as expected. See the attached screenshots that show it displaying 00:00 in the dropdown lists.  I'm using windows 10 with playwright version 1.17.1  I was able to repro the issue using a mac but had to revert back to the macOS Catalina with the safari browser 13.1 using the BrowserStack tools.  I guess I'm looking for advice on next steps to take.  The time ddl renders as expected in chrome and firefox.

I attached a screenshot of the issue using the Browserstack tools and two mp4 videos showing the expected rendering in chrome vs the rendering in the webkit browser

![2022-01-05_rendertimeddlcatalina_safari13_1](https://user-images.githubusercontent.com/15095846/148239634-4090928c-15bb-44f2-8f03-6c9634a050bc.png)

https://user-images.githubusercontent.com/15095846/148239761-a667d6dc-eab0-45cf-9382-66213b2de219.mp4

https://user-images.githubusercontent.com/15095846/148239795-aa73652c-d4d2-47b2-a1f8-5a07cf04011a.mp4

**Comment by pavelfeldman** [comment]
You are looking at the `<input type=date></input>`, it does not have a drop down list, it is rather a native Date picker. Different browsers on different platforms will have different native treatment for them. If you are running WebKit on non-macOS, you can't get the native macOS date picker. If you are running on macOS, you'll see it.

You don't need to open the list to automate it, it is just an `<input>`, so the standard `page.locator('input').fill('10/10/2000')` will work on it.

**Comment by davilo61** [comment]
Thanks for the background information.
