### ISSUE TITLE
[BUG]  Please be more explicit in the documentation for page.waitFor...

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#11208]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: 4.17.3
- Browser: Chromium

Although the documentation _does_ provide examples of the use of (e.g.) [waitForNavigation](https://playwright.dev/docs/api/class-page#page-wait-for-navigation) where waitForNavigation is in a Promise.all _before_ a click, it is not explicitly stated that this order is important.

We recently changed the order of these in our code due to the fact that it was bit confusing in the trace files.  It was not until we started getting some weird behaviour with things like "target closed" for operations in those areas that we realised the importance of the order.

Also, although the documentation for waitForNavigation states that it "resolves when the page navigates to a new URL or reloads" it does not explicitly state whether it also waits for the load state or not.

**Comment by pavelfeldman** [comment]
> waitForNavigation is in a Promise.all before a click, it is not explicitly stated that this order is important.

We explicitly call it out in our navigation guide: https://playwright.dev/docs/navigations#asynchronous-navigation. We rarely see `waitForNavigation` being used, `waitForURL` is idempotent and does not require `Promise.all`, hence we suggest using it instead.

*It is not us, it is JavaScript - we assume certain level of familiarity with Promises, so if one wants to add a listener and perform the action, depending on whether listener is added before or after the action, it'll be registered in the listener or not.*

> Also, although the documentation for waitForNavigation states that it "resolves when the page navigates to a new URL or reloads" it does not explicitly state whether it also waits for the load state or not.

I can see it documented here: https://playwright.dev/docs/api/class-page#page-wait-for-navigation-option-wait-until

**Comment by MartinP-Autopilot** [comment]
@pavelfeldman, thanks for the response.  I agree about the latter bit about the waitForNavigation documentation - it obviously _does_ mention the waiting for load state, I just missed it.  Apologies.

As for the order of operations in a Promise.all, I am very familiar with them, it is the fact that the waitForNavigation is adding a listener that should be registered prior to the click that is actually implementation specific.  

In hindsight, it is obvious what is happening.  But, when you are working with other devs and building a new framework, asking for the operations to be in the opposite order so that the trace is less confusing seems a trivial change and you don't really think about waitForNavigation adding a listener that needs to be in place prior to the event occurring, you're just thinking about the fact that Promise.all won't resolve until all the returned promises resolve.

Even in https://playwright.dev/docs/navigations#asynchronous-navigation (which you would have to look for rather than being linked to in the details of the operation that you're reading about), it does not explicitly state that the order is important.

I agree that it should be obvious but, even though that is the case, I am sure that pointing it out will save some frustration for your users.

**Comment by MartinP-Autopilot** [comment]
@pavelfeldman, in reviewing our code to see if there are other similar problems that I need to fix, I noticed several usages of things like [page.waitForSelector](https://playwright.dev/docs/api/class-page#page-wait-for-selector).

I am not sure of the implementation for this method but I suspect that you're not injecting a listener.  So, calling this method _after_ the element that matches the selector has been added to the DOM should work.

The thing is that this is one of many "page.waitFor..." methods.  Several of them do not care about order of operations.  It just happens that several of them _do_ care about order of operations and you cannot glean this fact from a consistency point of view, you have to take an educated guess at the implementation.

Again, it would be good to just explicitly state which ones care about order of operations.

**Comment by pavelfeldman** [comment]
@MartinP-Autopilot do you want to take a stab at it? All the docs are in this repo!

**Comment by neongreen** [comment]
> We rarely see waitForNavigation being used, waitForURL is idempotent and does not require Promise.all, hence we suggest using it instead.

Btw I didn't know this. When I started using playwright I was relying exclusively `playwright codegen` and it was outputting the `Promise.all([...])` pattern so I thought it was the recommended way to do it even though it seemed a bit clumsy.

**Comment by dgozman** [comment]
Fixed by #11379.
