### ISSUE TITLE
intercept response and redirect

### ISSUE THREAD

**Issue by codeman5000** [microsoft/playwright#11207]
Hello i'm using python in playwright and would like to wait for a response url and then redirect to another url.

so when the pages sends a response lets say www.google.be
i would like to redirect to another url, lets say www.apple.com

is this possible?

i can't find any working code for it.

**Comment by pavelfeldman** [comment]
what do you mean  response url, do you mean 'response contains a redirect to google.be'?

**Comment by codeman5000** [comment]
I mean, if u receive this response from clicking a button:

Response: https://www.google.be
---
from this code: page[i].on("response", lambda response: print("Response: " + response.request.url))
---
i would like to not go to www.google.be but to go to an url i defined.

**Comment by pavelfeldman** [comment]
There is no such thing as a Response: https://google.be. It can be a success response, or a redirect response. Are you trying to intercept a redirect? You can only intercept entire requests in Playwright, but you can intercept them, perform request yourself, parse response and navigate to where you like using page.goto.

**Comment by codeman5000** [comment]
It’s actually when I press a button I would like to be redirected to another page. I don’t know how to intercept that and to navigate to another url. What class in playwright do I have to use? Do you have an example?

**Comment by pavelfeldman** [comment]
Unfortunately, it is unclear what you are trying to do. I'd suggest that you refer to https://playwright.dev for docs. There are guides about clicking, handling network requests, navigating, etc!
