### ISSUE TITLE
[BUG] trace output isn't rendering page correctly

### ISSUE THREAD

**Issue by kbfirebreather** [microsoft/playwright#11200]
**Context:**
- Playwright Version: 1.14.1
- Operating System:  Windows 10 10.0.19042
- Node.js version: 14.16.1
- Browser: Chromium
- Extra: SPA built with webpack

**Code Snippet**

N/A

**Describe the bug**

I'm using playwright trace, in a custom runner. Enabling trace from the context, https://playwright.dev/docs/api/class-tracing#tracing-start, but my trace output snapshots are blank. 

Here is a screenshot of what it looks like in the trace-viewer

![image](https://user-images.githubusercontent.com/3360138/148241191-3f57f25b-d1c9-4ca3-b981-22d41e1940ed.png)

**Comment by aslushnikov** [comment]
@kbfirebreather we'd need more details to tackle this. Idealy, can you provide us with a repro script that yields this result?

**Comment by kbfirebreather** [comment]
Okay, I'll work on putting something together that will replicate it.

**Comment by pavelfeldman** [comment]
You can also share a trace with us

**Comment by imartinflores** [comment]
I have a quite a similar issue with the Trace. I have configured it on the playwright.config.ts , but when a test fails it only shows this:

![image](https://user-images.githubusercontent.com/17011557/148544596-1e619c94-134c-466f-8e6c-d5ccc3239522.png)

**Comment by aslushnikov** [comment]
I'll close this for now; please re-file with a good repro that we can run locally & debug!
