### ISSUE TITLE
[Feature] retry until fail

### ISSUE THREAD

**Issue by benmccann** [microsoft/playwright#11203]
There is a [retries flag](https://playwright.dev/docs/test-retries#retries) that will retry a failing test until it passes. What I would like to see is the opposite - a flag such as `--retries-to-failure` that will retry a passing test until it fails. The use case for this is that I have a few tests that are flaky. I want to debug them by continually retrying the flaky test locally until I can get a trace of the failure.

**Comment by aslushnikov** [comment]
@benmccann the way we do it is a combination of `--retry-each 1000` and `--max-failures 1` flags, together with [`taskset`](https://twitter.com/aslushnikov/status/1311568184764321792) on linux

**Comment by benmccann** [comment]
Thank you. What is the strange symbol after `taskset -c` in the screenshot in your tweet? I'm not sure how to type it or what it does

**Comment by aslushnikov** [comment]
that's zero :)

**Comment by pavelfeldman** [comment]
You don't need task-set, just set --workers=1 and it'll sequentially repeat each test.

**Comment by benmccann** [comment]
Thanks for the help!

Leaving the whole command here for anyone who comes across this later:
```
taskset -c 0 npx playwright test --repeat-each 1000 --max-failures 1 -g "accepts a Request **object"
```

Or:
```
npx playwright test --workers=1 --repeat-each 1000 --max-failures 1 -g "accepts a Request object"
```
