### ISSUE TITLE
[BUG] Elements with display:contents are considered invisible

### ISSUE THREAD

**Issue by basilgood** [microsoft/playwright#11202]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Linux 
- Node.js version: 14.18.1
- Browser: Chromium

**Code Snippet**
I have a repro: https://github.com/basilgood/pw-repro

**Describe the bug**
A checkbox, when is checked a text (paragraph) appear in the footer with text ```Checkbox is CHECKED!```
The footer it's a parent selector with ```display: none``` style.
The paragraph is the child of the footer and has ```display: contents```

Test: ```npx playwright test --headed```
```js
  await page.goto('http://localhost:3000/');
  await page.click('#myCheck');
  await page.waitForSelector('"Checkbox is CHECKED!"');
```
It works well, the footer with text appear so the text is visible in page.
The bug it's that waitForSelector fails to find it.
```
waiting for selector ""Checkbox is CHECKED!"" to be visible
  selector resolved to hidden <p>Checkbox is CHECKED!</p>
```
The same behavior is if I change ```waitForSelector``` with ```click```
Surprisingly is that the test pass with:
```js
await page.waitForSelector('"Checkbox is CHECKED!"', { state: 'hidden' });
```
```waitForSelector``` behave like the text (selector) it's hidden and find it.
It also pass with ```{ state: "attached" }``` , that makes me think of: #5949

**Comment by pavelfeldman** [comment]
Minimal repro:

```js
  await page.setContent(`
    <div>
      <p style="display:contents">DISPLAY CONTENTS</p>
    </div>
    </html>`);
  await page.waitForSelector('"DISPLAY CONTENTS"');
```
