### ISSUE TITLE
[BUG] Click action stuck on scheduled navigation check (WebKit)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#11219]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 12.22
- Browser: WebKit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Shared the test with @pavelfeldman  privately to reproduce the issue.

**Describe the bug**
Performing a click action on webkit is stuck on `waiting for scheduled navigations to finish` check. Loading the trace file shows that the click actually happened but it is still processing some actionability check.

Logs:
```
selector resolved to visible <span class="ng-tns-c10-0">…</span>
attempting click action
waiting for element to be visible, enabled and stable
element is visible, enabled and stable
scrolling into view if needed
done scrolling
checking that element receives pointer events at (1185.15,27.48)
element does receive pointer events
performing click action
click action done
waiting for scheduled navigations to finish
```

**Comment by aslushnikov** [comment]
> enable it('should not stall on JS navigation link', async ({ page, browserName }) => {

**Comment by nvarghese7** [comment]
I am getting the same error on clicking a submit button in Chrome browser.

Error log:
Error in uploading PriceSheet locator.click: Timeout 60000ms exceeded.
Call log:
  - waiting for locator('input[value="Upload"]')
  -   locator resolved to <input name="submit" type="submit" value="Upload" initvalue="Upload"/>
  - attempting click action
  -   waiting for element to be visible, enabled and stable
  -   element is visible, enabled and stable
  -   scrolling into view if needed
  -   done scrolling
  -   performing click action
  -   click action done
  -   waiting for scheduled navigations to finish
