### ISSUE TITLE
[BUG] locator.click: Protocol error (DOM.scrollIntoViewIfNeeded): Cannot find context with specified id

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#11221]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: 4.17.3
- Browser: Chromium

Hi, I am occasionally getting an error `locator.click: Protocol error (DOM.scrollIntoViewIfNeeded): Cannot find context with specified id`, and I believe that the `Cannot find context with specified id` bit is coming directly from the DevTools API that Playwright is using to interact with the DOM.

From my understanding, a [Locator.click](https://playwright.dev/docs/api/class-locator#locator-click) will -
1. get the NodeId (using something like [DOM.querySelector](https://chromedevtools.github.io/devtools-protocol/tot/DOM/#method-querySelector))
2. use the NodeId to perform [actionability checks](https://playwright.dev/docs/actionability)
3. use the NodeId to scroll the element into view
4. use the NodeId to get the position of the element so that it can be clicked on

So, to be getting the above error, the element that the NodeId is referencing must be being removed from the DOM and being replaced (we're using React and the element still seems to be there after this error but I am assuming that React must be removing it and re-adding during a render operation or something like that), and that must be happening between steps 1 and 3 above.

The thing is that I thought that was the whole reason that we're using Locators instead of ElementHandles, to avoid the above problem.  I would have thought that the click method would be able to manage the error from DevTools and go back to step 1.

Is it supposed to be doing this?

**Comment by AndyGleed** [comment]
I also hit the same issue yesterday with v1.17.
