### ISSUE TITLE
[Question] How to use one `page` and load website page only once for tests in the same test file

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#11223]
If following the example in Playwright official doc, one would add serveral `test` blocks in a test file
```
test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```
My understainding is that the `page` fixture will cause each test open its own page.

How can I write a test file with serveral tests but I want to just load my website page once and all `test` will do verifications without opening new page and load my site again?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/test-retries#serial-mode

this is a discouraged practice though!

**Comment by TimeInvestor** [comment]
Thanks for the information.
However, the doc says

> Use test.describe.serial(title, callback) to group dependent tests to ensure they will always run together and in order. If one of the tests fails, ***all subsequent tests are skipped***.

In my case, I don't want subsequent tests to be skipped if one previous case failed.
How can I achieve this?

**Comment by pavelfeldman** [comment]
Well, if a previous test fails, your page is most likely busted, there is no point in continuing. Remove .serial and it won't be failing subsequent tests, but that's even more discouraged. It is only Ok to use new page for each test.

**Comment by TimeInvestor** [comment]
Sorry, but I don't quite agree on the statement `if a previous test fails, your page is most likely busted`.
I can check a value in UI component #1 in test #1 and another value in UI component #2 in test #2.
So a wrong value in UI component #1 does not mean the other value in UI component #2 is also invalid.

**Comment by TimeInvestor** [comment]
I am thinking it would be nice if there a config to control the behaviour in serial mode.
Let users to choose whether to fail subsequent tests or not.

**Comment by klhex** [comment]
@TimeInvestor Would an option to declare a test as optional and thereby always continue test execution after it be helpful in your use case? See https://github.com/microsoft/playwright/issues/7786.

**Comment by TimeInvestor** [comment]
Thanks @klhex.
Setting my tests as optional is a walk around. But I would have too many tests to set. Besides, in terms of test report readability `test.optional` can be easily misunderstood when shows up in case a test failed.
So I think a global config would work better for my case.

**Comment by dgozman** [comment]
@TimeInvestor If `describe.serial` behavior does not work for you, use regular `describe`. You can still share the page as [described here](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests), but we usually see more flakiness in this case.

I don't think there is any action item for Playwright Test here. Please comment if you see some kind of improvement that would be helpful.
