### ISSUE TITLE
[Feature Request] Snapshot Storage/Layout: Default Layout and Auto Uniquify Names Per-Test

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#11226]
Playwright's default behavior with naming snapshots makes it easy to accidentally
have your tests within a file overwrite eachother (especially if you have more than
a screenful of tests in one file):

```ts
// Broken - the two tests in this file will overwrite eachothers snapshots
import { test, expect } from "@playwright/test";

test("a", async () => {
  expect("a").toMatchSnapshot("example.txt");
});

test("b", async () => {
  expect("b").toMatchSnapshot("example.txt");
});
```

While you can think more intentionally about the names within a test and across the whole file, for now,
we've found it easier to think less and just auto add the title into the suffix so
you can use generic names in your snapshot tests without thinking of other tests
in the file:

```ts
// Works - we auto prefix with the test title so you only have to keep snapshot
// names unique within a single test, but not across the whole file.
// When doing screenshots, it's sometimes nice to just be able to name things: `screenshot.png`,
// but that creates conflicts without this workaround.
import os from "os";
import { test as _test, expect } from "@playwright/test";

const test = _test.extend<{ _autoSuffix: void }>({
  _autoSuffix: [
    async ({}, use, testInfo) => {
      testInfo.snapshotSuffix = `${testInfo.title}-${os.platform()}`;
      await use();
    },
    { auto: true },
  ],
});

test("a", async () => {
  expect("a").toMatchSnapshot("example.txt");
});

test("b", async () => {
  expect("b").toMatchSnapshot("example.txt");
});
```

There are alternative snapshot layouts/naming conventions from this auto fixture that probably make sense,
but this fixture for now works.

Overall, I think changing the **default behavior** so tests in the same file
don't overwrite eachother's snapshots would be a net-positive. (We hit it once, were very confused for a second, solved it poorly, then solved it mostly once and for all with an auto fixture but coming from some other snapshot libraries, I was caught off guard by the current default.)

I don't love our fixture workaround, I'd probably do something with directories. e.g. put snapshots for each test in a different directory so the names don't get so long and preserve the naming hierchy in the dir layout itself instead of the name (plus it keeps things from clashing):

```
snapshots/
  example.spec.ts/
    a/
      example.txt <- if platform indepdendent
      darwin/ <- if platform dependent
        screenshot.png
      …
    b/
      example.txt
      …
```

(not sure where Project Name would fit in, but it would either nest under `a/b` or diretly under `snapshots/`)

Additionally, I'd also like to make the **default location** of snapshots a sibling of `playwright.config.ts`
instead of deeply nested in the test tree (which of course can be done by `snapshotDir` already today). I find this makes it easier to work with snapshots as they are (1) easier to spot in the file browser, (2) easy to remove en-masse (`rm -rf snapshots/`), (3) all snapshots sort together in `git diff/status` output instead of being interspersed with the test file diffs, and (4) makes it easier to see snapshots have changed in git diff output before checking them in.

I'd be happy to talk through and iterate more on some of these proposals and contribue PRs where appropriate! (I thought about makine seperate issues, but I think they make sense to talk through as one unit of design.)

Thanks! As always, I so appreciate y'all's time and this amazing tool! ❤️

**Comment by bellindj** [comment]
We would love this feature. I just started converting my setup from the playwright package with a custom setup using jest-image-snapshot over to @playwright/test. With jest-image-snapshot, you just call .toMatchImageSnapshot() and it automatically creates the image name using the test path+title, adding together the describes down to the test name.

**Comment by aslushnikov** [comment]
> Playwright's default behavior with naming snapshots makes it easy to accidentally
have your tests within a file overwrite eachother 

@rwoll As of 1.20 we now support anonymous snapshots and we encourage everybody to use them. This should solve this!

```js
// anonymous snapshot!
expect('foo bar').toMatchSnapshot();
```

> Additionally, I'd also like to make the default location of snapshots a sibling of playwright.config.ts
instead of deeply nested in the test tree (which of course can be done by snapshotDir already today).

The new `expect.toHaveScreenshot` (probably coming in 1.21) defaults to this model of screenshot management!

> Overall, I think changing the default behavior so tests in the same file
don't overwrite eachother's snapshots would be a net-positive.

Sounds legit, let's me fix it!

**Comment by aslushnikov** [comment]
> Overall, I think changing the default behavior so tests in the same file
don't overwrite eachother's snapshots would be a net-positive.

Oh actually, anonymous snapshots should address this all! Closing this then
