### ISSUE TITLE
[Question] Does waitFor() throw an error when the element is not present on the page after default timeout?

### ISSUE THREAD

**Issue by lambrevalora** [microsoft/playwright#11239]
We are using locator().waitFor() and expect an error to be thrown after the default timeout. Instead the test hangs and does not complete.

await page.locator('div[role="dialog"]').waitFor();

**Comment by aslushnikov** [comment]
@lambrevalora could you share a small snippet that we can run locally to reproduce this issue?

Also, what's your Playwright version?

**Comment by lambrevalora** [comment]
@aslushnikov ,

I'm trying to locate dialog which I know that won't be presented but the test never goes through the step with waitFor(). Here is the code that I have written:

`await page.locator('//div[contains(text(),"Administration Dashboard")]').waitFor(); // wait all elements to be presented
    const mainTabs = await page.$$('//span//div//span'); // find all main tabs
    for (let i = 0; i < mainTabs.length; i++) {
        const riskTab = await mainTabs[i].innerText();
        if (riskTab !== 'Risk & Fraud') {
            await mainTabs[i].click(); // click on each main tab
            let b = await page.$$('//a[@class="_30z54mY06ml4zdRETQp-kC _1Q_dLtCRdZf1gQFyTOS16n"]'); // locate all options in the clicked mainTab
            for (let y = 0; y < b.length; y++) {
                b = await page.$$('//a[@class="_30z54mY06ml4zdRETQp-kC _1Q_dLtCRdZf1gQFyTOS16n"]');
                await b[y].click(); // click on each under mainTab option
                await page.locator('div[role="dialog"]').waitFor();
                const error = await page.isVisible('div[role="dialog"] div div span:has-text("Error")');
                if (error) {
                    const tab = await b[y].innerText();
                    throw new Error('Error on tab: ' + tab);
                }
                await page.$('//tbody/tr[1]/td[2]/li[1]'); // verify that the new tab is opened
                await page.click('//tbody/tr[1]/td[2]/li[1]/a[1]/div[1]/div[1]'); // close the opened tab
                await mainTabs[i].click(); // click on the current mainTab to make option attached to the DOM
            }
        }
    }`

**Comment by aslushnikov** [comment]
> Instead the test hangs and does not complete. 

@lambrevalora Could it be that you change default timeout somewhere else? 

> Here is the code that I have written:

This code I can't run locally and thus can't debug your issue. Do you have a repro that I can run to see it for myself?

**Comment by lambrevalora** [comment]
> @lambrevalora Could it be that you change default timeout somewhere else?

I tried to set timeout only for the current waitFor() but is was not working. I have write it that way :

```await page.locator('div[role="dialog"]').waitFor({timeout: 0});```

> This code I can't run locally and thus can't debug your issue. Do you have a repro that I can run to see it for myself?

Unfortunately, I don't have public repo so you can not try it by yourself.

**Comment by aslushnikov** [comment]
```js
await page.locator('div[role="dialog"]').waitFor({timeout: 0});
```

@lambrevalora Setting timeout equal to zero makes it an infinite timeout, so it'll hang forever. Could it be this is what you observed & described in the bug?

**Comment by lambrevalora** [comment]
> @lambrevalora Setting timeout equal to zero makes it an infinite timeout, so it'll hang forever. Could it be this is what you observed & described in the bug?

This is not my case. The test never ends when I did not specify anything as timeout. In the doc I read that the default is 30 seconds but more time than that nothing happens.

**Comment by aslushnikov** [comment]
@lambrevalora can you run your script with the `DEBUG=pw:api` environment variable? It'll log all calls to Playwright API and we'll see for sure where it gets stuck

**Comment by lambrevalora** [comment]
> @lambrevalora can you run your script with the `DEBUG=pw:api` environment variable? It'll log all calls to Playwright API and we'll see for sure where it gets stuck

@aslushnikov it is working when I pass `DEBUG=pw:api` . The 30 seconds timeout is reached and the test failed. My question is why it is not working without debug. Here are my launch file and my config file. 

launch.json

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "node",
            "request": "launch",
            "name": "Launch Program",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "program": "${workspaceRoot}/node_modules/@playwright/test/cli.js"
        },
        {
            "name": "Launch this Playwright test",
            "request": "launch",
            "runtimeArgs": [
              "playwright",
              "test",
              "--headed"
            ],
            "env": {
                "baseURL": "http://localhost:5000",
                "PWDEBUG": "console"
            },
            "runtimeExecutable": "npx",
            "skipFiles": ["<node_internals>/**"],
            "type": "pwa-node",
            "outputCapture": "std", // or "console" 
          }
    ]
}
```

playwright.config.js

```
// playwright.config.js
// @ts-check
const { devices } = require('@playwright/test');

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
    // forbidOnly: !!process.env.CI,
    // retries: process.env.CI ? 2 : 0,
    // reporter: [['html', { open: 'always' }]],
    // timeout: 60000,
    testDir: 'tests',
    // globalSetup: require.resolve('./loginPAP'),
    use: {
        // trace: 'on',
        headless: true,
        baseURL: 'http://localhost:5000',
        storageState: 'loginPAP.json',
        launchOptions: {
            slowMo: 20
        }
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] }
        }
        // ,
        // {
        //     name: 'firefox',
        //     use: { ...devices['Desktop Firefox'] }
        // }
    ]
};

module.exports = config;

```

**Comment by aslushnikov** [comment]
> @aslushnikov it is working when I pass DEBUG=pw:api . The 30 seconds timeout is reached and the test failed. My question is why it is not working without debug? Here are my launch file and my config file.

@lambrevalora interesting! `DEBUG` env variable shouldn't change much in the program. Overall, this behavior looks like a bug in Playwright. But to fix it, we'll need a way to reproduce it locally.

Any chance you can make a small reproduction that illustrates the issue and that we can run & debug locally?

**Comment by lambrevalora** [comment]
> Any chance you can make a small reproduction that illustrates the issue and that we can run & debug locally?


Here is the code I was able to reproduce it with:

```
const { test, chromium } = require('@playwright/test');

test.only('basic test', async() => {
    const browser = await chromium.launch();
    const page = await browser.newPage();

    await page.goto('https://www.google.com/search?q=google&rlz=1C1CHBF_enBG944BG944&oq=goo&aqs=chrome.0.0i355i512j46i199i465i512j0i512l2j69i60l3j69i65.471j0j7&sourceid=chrome&ie=UTF-8');
    await Promise.all([
        page.waitForNavigation(/*{ url: 'https://www.google.com/?gws_rd=ssl' }*/),
        page.click('button:has-text("I agree")')
      ]);
    const mainTabs = await page.$$('//div[@class="hdtb-mitem"]'); // find all main tabs
    for (let i = 0; i < mainTabs.length; i++) {
        const tabs = await mainTabs[i].innerText();
        if (tabs !== 'Images') {
            await mainTabs[i].click(); // click on each main tab
            let b = await page.$$('//a[@role="button"]'); // locate all options in the clicked mainTab
            for (let y = 0; y < b.length; y++) {
                b = await page.$$('//a[@role="button"]');
                await page.locator('div[role="dialog1"]').waitFor();
            }
        }
    }
});
```

**Comment by aslushnikov** [comment]
@lambrevalora this script does terminate for me with the `Timeout of 30000ms exceeded.` error.

Do you run it from-inside VSCode? Could you please try running this test from a plain terminal instead?

**Comment by lambrevalora** [comment]
> Do you run it from-inside VSCode? Could you please try running this test from a plain terminal instead?

@aslushnikov when I try npx playwright test --headed, the test failed with Timeout of 30000ms exceeded.

But my case is when running the test with launch config from the above. Please try to repro with the files given above for launch configuration and playwright config.

**Comment by lambrevalora** [comment]
> > Do you run it from-inside VSCode? Could you please try running this test from a plain terminal instead?
> 
> @aslushnikov when I try `npx playwright test --headed`, the test failed with Timeout of 30000ms exceeded.
> 
> But my case is when running the test with launch config from the above. Please try to repro with the files given above for launch configuration and playwright config.

**Comment by mxschmitt** [comment]
I extracted the bug report out to #11520 with some technical description.
