### ISSUE TITLE
[BUG] Failing tests for array as expected values in LocatorAssertions.hasClass

### ISSUE THREAD

**Issue by beelzebufo** [microsoft/playwright#11244]
**Context:**
- Playwright Version: 1.17.0
- Operating System: Windows
- Browser: All
- Extra: PlaywrightAssertions also Version 1.17.0

**Describe the bug**

Given the following HTML element with 3 classes _class1, class2, class3_:

```html
<h1 id="firstHeading" class="class1 class2 class3">Hello</h1>
```
When using LocatorAssertions.hasClass() , acording to the API Notes, _if array is passed as an expected value, entire lists can be asserted:_
```java
assertThat(page.locator("#firstHeading")).hasClass(new String[]{"class1", "class2", "class3"});
```
The array makes sense if I'm expecting, well, three classes (class1, class2, class3), however, the test fails with:
```
Expected :[class1, class2, class3]
Actual   :[class1 class2 class3]
```
This means, in order for the tests to pass, I only need an array with only one whole string `String[]{"class1 class2 class3"}` or no array at all, as I can also just call
`assertThat(page.locator("#firstHeading")).hasClass("class1 class2 class3");` 

The description with array as expected value on the official website makes no sense, as one would normally expect different behavior with arrays.

**Comment by pavelfeldman** [comment]
> if array is passed as an expected value, entire lists can be asserted:

It means "entire lists of elements can be asserted". I'll update the docs. It works like toHaveText/toContainText, etc. I.e. you can use it on lists.
