### ISSUE TITLE
[Question] Testing for sensitive data leakage

### ISSUE THREAD

**Issue by neongreen** [microsoft/playwright#11243]
I'd like to test that certain user properties (e.g. `passwordHash`) aren't returned either in the page body or any requests made while the test is running. Does Playwright provide a way to check for this?

**Comment by aslushnikov** [comment]
@neongreen Sure, just subscribe to all the page responses using [`page.on('response')`](https://playwright.dev/docs/api/class-page#page-event-response) and then use the [`response.text()`](https://playwright.dev/docs/api/class-response#response-text) method

**Comment by neongreen** [comment]
Thanks!

I am currently trying to do this, but `page.on()` expects a `=> void` and `response.text()` returns a Promise. Should I just put all those responses into an array and `Promise.all()` it at the end of the test? Or what's the best way to deal with this?

**Comment by aslushnikov** [comment]
If you want to track all responses during page navigation, you can do something like this:

```js
// demo.mjs
import { chromium } from 'playwright';

const browser = await chromium.launch();
const page = await browser.newPage();

const responses = [];
page.on('response', response => responses.push(response));
await page.goto('https://playwright.dev');
const bodies = await Promise.all(responses.map(response => response.text()));
console.log(bodies.length);
// analyse bodies...
await browser.close();
```

**Comment by neongreen** [comment]
Alright, great. Thanks again!

**Comment by neongreen** [comment]
Note to anyone else seeing this issue: if the body is large (several megabytes), `expect(body).not.toMatch(...)` will get stuck.

I ended up doing this:

```typescript
  for (const response of await Promise.all(responses)) {
    const matches = (await response.text()).match(/(passwordHash|...)/g)
    if (matches) {
      console.error(`The response for ${response.request().url()} leaks data: ${matches}`)
      expect(true).toBeFalsy()
    }
  }
```

(Can be made nicer with a custom `expect` matcher.)

**Comment by neongreen** [comment]
Hm, I'd expect this to work better because the response can't be discarded until route.fulfill() is called explicitly. (But even then, I got at least four different errors re/ failing to get the response body.)

```typescript
    // eslint-disable-next-line @typescript-eslint/no-misused-promises
    await page.route(() => true, async route => {
      try {
        const response = await page.request.fetch(route.request())
        let body = await response.text()
        requests.push([route.request(), body])
        await route.fulfill({ response })
      } catch (error) {
        const re = /(Response has been disposed|Request context disposed|Failed to find browser context|browser has been closed)/g
        // @ts-ignore
        if (error.message.match(re)) return; else throw error
      }
    })
```

**Comment by aslushnikov** [comment]
@neongreen interesting! Could you please file it as a separate issue? We'll look into this

**Comment by neongreen** [comment]
@aslushnikov My understanding is that it's expected behavior, given that Playwright has explicit errors/handlers for those cases. If `page.route()` is genuinely supposed to maintain the invariant that the response body will always be available for inspection, then sure, I'll file an issue.
