### ISSUE TITLE
[Question] use firefox old version to playwright

### ISSUE THREAD

**Issue by yeucodonvn** [microsoft/playwright#11245]
Playwright Version: 1.17.0
Operating System: Windows
Browser: firefox

i want to use firefox old version ( 56.0.2) to playwright
I using .executablePath = 'firefox/firefox.exe';

browserType.launch: Protocol error (Browser.enable): Browser closed.

this is code 
https://pastebin.com/4i5WJdwQ

**Comment by pavelfeldman** [comment]
This scenario is not support. Learn more at https://playwright.dev/docs/next/browsers
