### ISSUE TITLE
[BUG] The Locator count() function fails with a TypeError

### ISSUE THREAD

**Issue by smeierhofer** [microsoft/playwright#11254]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: v14.18.1
- Browser: Chromium
- Extra: None

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 8.06 GB / 31.73 GB
## Binaries:
 - Node: 14.18.1 - C:\nodejs\node.EXE
 - Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.14.11 - C:\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

**Code Snippet**

```typescript
const count = await this.page.locator('#searchResultTableDiv .x-grid3-row').count();
```

The Locator count function fails. I see the following in the Playwright debugger:
```
locator.count
(#searchResultTableDiv .x-grid3-row)
— 4ms
TypeError: r.set is not a function
    at b._querySelectorRecursively (<anonymous>:3:50248)
    at b.querySelectorAll (<anonymous>:3:50693)
    at eval (eval at evaluate (:3:2389), <anonymous>:5:23)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44)
```

**Comment by pavelfeldman** [comment]
We'll fix it, but your page hides the standard JavaScript Map type, which does not sound great!

**Comment by pavelfeldman** [comment]
Locator.count is implemented on the client side, so this would need ports:

- [ ] Node
- [ ] Python
- [ ] Java
- [ ] .Net

**Comment by smeierhofer** [comment]
Thanks for responding and fixing so quickly. I hadn't realized that our app hides the standard JavaScript Map type. Just to give some perspective on why the Map type is overridden/hidden. 

Some of our app has a lot of legacy and pre-dates the time when Map and Set were included with JavaScript. So... We implemented our own Map type and now, years later, that still exists and hides the browser's Map type. As we build new features today we are no longer using our legacy JavaScript stack but starting out on a new front-end stack. We are using Playwright to automate e2e tests for this new work, but the tests need to do some testcase setup work by running the old UIs and that's where we have run into the Map object being hidden by our legacy implementation of Map. I'll look at options such as adding the set() function to our Map prototype or unhiding the browser's Map type.
