### ISSUE TITLE
[Feature] Provide integration with Angular CLI

### ISSUE THREAD

**Issue by asterium** [microsoft/playwright#11258]
Hi 
Is it possible to add integration of Playwright with Angular CLI, so that playwright tests could be run as a part of `ng e2e` command?

Given Protractor is deprecated at the end of 2022, there are a lot of teams out there looking for a better alternative. The ability to integrate the testing tool into Angular build process could be one of the decisive factors for them. 

Available integrations from [Cypress](https://github.com/cypress-io/cypress/tree/develop/npm/cypress-schematic) and [Webdriver.io](https://github.com/webdriverio/webdriverio-schematics) could be used as a reference.

**Comment by pavelfeldman** [comment]
@pkozlowski-opensource ^^

**Comment by pkozlowski-opensource** [comment]
@asterium I've started to discuss the idea of such integration (in practical terms - a CLI schematic) with the Playwright team _just_ this week :-) Stay tuned, we should have a good story here!

**Comment by asterium** [comment]
@pkozlowski-opensource, sorry for bugging you, but are there any updates on the matter?

**Comment by pkozlowski-opensource** [comment]
Yep! We are close to finishing a schematic that adds Playwright support for Angular CLI project. It should have integration level comparable to the one with Protractor (ex. running tests with the `ng e2e` command). 

Stay tuned!

**Comment by Lusey77** [comment]
Any movement on this, my team is also adopting playwright, however, integrating with Angular CLI has been a pain thus far. Thanks for your work on this!

**Comment by doggy8088** [comment]
@pkozlowski-opensource Are you going to release a beta for this soon? We are ready to be a tester. 😊

**Comment by Abildtoft** [comment]
I'm also very interested in this - any way to be of help?

**Comment by d-koppenhagen** [comment]
same here, I would be happy to beta-test this.

**Comment by camsteffen** [comment]
Does anyone have a workaround for a command to serve the app and run e2e tests?

**Comment by liamdocherty10** [comment]
@camsteffen we use https://www.npmjs.com/package/start-server-and-test e.g.
```json
"e2e": "start-server-and-test start:e2e http://localhost:4200 e2e:run",
"e2e:install": "playwright install chromium --with-deps",
"e2e:run": "playwright test --config e2e/playwright.config.ts",
"start:e2e": "ng serve",
```

**Comment by camsteffen** [comment]
I ended up using the [webServer option](https://playwright.dev/docs/test-advanced#launching-a-development-web-server-during-the-tests).

**Comment by robertIsaac** [comment]
> same here, I would be happy to beta-test this.

+1

**Comment by randallmeeker** [comment]
We are using `http-server` when running in CI

playwright.config.ts
```.ts
const runsOnCI = process.env.RUNS_ON_CI === "yes";
const angularConfig = require("./angular.json");

    webServer: runsOnCI
        ? {
              command: `http-server -p 4800 --proxy "http://localhost:4800?" ./dist/${angularConfig.defaultProject}`,
              port: 4800,
          }
        : null,
```

**Comment by Ibrizic** [comment]
Hiya everyone, any updates on this?  👼

**Comment by jfgreffier** [comment]
Hi @pkozlowski-opensource I'm sorry it couldn't be completed. Do you have by any chances a repo with the work that was done so far ?

**Comment by selangley-wa** [comment]
Playwright looks like it's missing out in this comparison with other testing frameworks that have implemented a migration schematic for Protractor.
https://blog.angular.io/protractor-deprecation-update-august-2023-2beac7402ce0
![2023-09-27_15-30-51](https://github.com/microsoft/playwright/assets/43478262/a6943afa-4a92-4483-8fd0-b061831b2d8e)

**Comment by selangley-wa** [comment]
And here is the source for Puppeteer's angular schematic:
https://github.com/puppeteer/puppeteer/tree/main/packages/ng-schematics

**Comment by jfgreffier** [comment]
Hi !
I've created an Angular schematics for Playwright, it's still new but functional.
It adds Playwright Test to your Angular project, can install browsers, and helps you to generate your firsts end-to-end tests.
https://www.npmjs.com/package/playwright-ng-schematics

**Comment by jfgreffier** [comment]
Playwright is now available as e2e choice in Angular CLI. See https://angular.dev/tools/cli/end-to-end

This issue can now be closed, thanks @Skn0tt
