### ISSUE TITLE
[Question] Disable loading of Images in Firefox

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#11251]
(This is Python) 
I wanted to use this
[Playwright Docs](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-option-firefox-user-prefs)
Based of this
[Stackoverflow](https://stackoverflow.com/a/31581387)
to disable image-loading. I also searched up the feature on Firefox´s _about:config_ , and there _profile.managed_default_content_settings.images_ is listed.

So i coded up this:
```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    brow = p.firefox.launch(headless=False, firefox_user_prefs={"profile.managed_default_content_settings.images": 2})
    browser = brow.new_context()
    page = browser.new_page()
    page.goto("https://google.com/")
    input()
```
But it didnt work and the Page ended up loading images anyway.
So now im wondering how i can disable Image-Loading with PLaywright-Python Firefox?

**Comment by pavelfeldman** [comment]
Will this work for you: https://playwright.dev/docs/network#abort-requests ?

**Comment by Vinyzu** [comment]
Thanks, this worked out perfectly!
