### ISSUE TITLE
[BUG] test.skip description is not reflected in reports

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#11266]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.17.1
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] v14.17.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] any
- Extra: [any specific details about your environment]

**Code Snippet**

```typescript
import { test } from '@playwright/test';

test.skip(() => true, 'Some description');
test('Some test', async () => {
    test.expect(true).toBe(true);
});
```

**Describe the bug**
According to [docs](https://playwright.dev/docs/api/class-test#test-skip-4) the descriptions should be displayed in the report.
Here's an output of default (line) reported: 
```bash
Running 1 test using 1 worker

  -  e2e/test.spec.ts:4:1 › Some test


  1 skipped

```

Here's html report 

---
<img width="1054" alt="Screenshot 2022-01-09 at 0 09 29" src="https://user-images.githubusercontent.com/6705391/148661625-13a31499-b76c-411c-97d9-a0b1c4d9821c.png">

---
<img width="1056" alt="Screenshot 2022-01-09 at 0 09 36" src="https://user-images.githubusercontent.com/6705391/148661626-17af2c82-96ac-4b13-bf2e-7fc63eda425d.png">

---
The feature is quite nice to add explanations on why test was skipped, some links to bug tracking systems, etc.

Also tried with junit reporter - all the same.

**Comment by Nav-2d** [comment]
I believe it is fixed in this ticket: https://github.com/microsoft/playwright/issues/10669

You should be able to see this in the next version by installing `@playwright/test@next`
