### ISSUE TITLE
[Question]: I want to remotely manage browsers on multiple servers. Is there a better solution?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#11263]
### Your question

Do you need to write your own logic to manage multiple server browsers? Or is there any existing scheme?

**Comment by aslushnikov** [comment]
> Do you need to write your own logic to manage multiple server browsers? Or is there any existing scheme?

@bbhxwl Playwright doesn't provide anything to manage multiple server browsers. I'm not aware of any existing scheme.
