### ISSUE TITLE
[Feature] Remove dependency on color.js

### ISSUE THREAD

**Issue by lilithium-hydride** [microsoft/playwright#11272]
color.js' maintainer had a fit and sabotaged the package, and it will now print out the American flag, Abraham Lincoln, and an endless stream of zalgo text (see: `https://github.com/Marak/colors.js/commit/074a0f8ed0c31c35d13d28632bd8a049ff136fb6`, `https://github.com/Marak/colors.js/issues/285`). I have avoided linking them directly as to avoid having this issue bombed.

This is problematic and should probably be rectified.

See https://github.com/Marak/colors.js/issues/285

**Comment by DABH** [comment]
Please see https://github.com/Marak/colors.js/issues/285#issuecomment-1008212640 for latest update - thanks

**Comment by sindresorhus** [comment]
If you're looking to switch to a well-maintained coloring package you can trust. Check out [Chalk](https://github.com/chalk/chalk). I'm one of the maintainers.

**Comment by btd** [comment]
Marak added change to color/safe, so every install now affected

**Comment by pavelfeldman** [comment]
> If you're looking to switch to a well-maintained coloring package you can trust. Check out Chalk. I'm one of the maintainers.

@sindresorhus that'd be nice, is there a way for us to use it from our TS code? Import is compiled into require('chalk'), which fails due to ESM vs CommonJS. I was going to raise the issue w/ question in your repo, but it won't let me.

**Comment by pavelfeldman** [comment]
Fixed in #11274

**Comment by sindresorhus** [comment]
> is there a way for us to use it from our TS code? 

TS is lagging behind on ESM support, so for now, you can just use [version 4](https://github.com/chalk/chalk/tree/v4.1.2) (which has been stable for years). TS is scheduled to fully support ESM in TS 4.6 which will be out in February.
