### ISSUE TITLE
[Feature] Enable both config and testDir for @playwright/test CLI

### ISSUE THREAD

**Issue by digitalclubb** [microsoft/playwright#11286]
**Let us know what functionality you'd like to see in Playwright and what your use case is.**

I have a monorepo with multiple applications. I want these applications to have their own tests but use a shared global config.

```
- playwright.config.ts
- apps
-- app1
--- tests/functional
-- app2
--- tests/functional
```

Using the CLI, it seems you can either pass a directory for tests without a config file (--config <dir>), or a config file (--config <file>).

I would like to enable both of these options so I can run `playwright test` from within a single application, with a shared global configuration but application specific tests.

Imagine:

`playwright test --config=../../playwright.config.ts --test-dir=tests/functional`

Currently I have to have a configuration file in each application which imports/exports the shared global one:

```
import config from '../../playwright.config';
export default config;
```

**Do you think others might benefit from this as well?**

For anyone working within a monorepo that would like to have a single config file - this could be very beneficial.

**Comment by dgozman** [comment]
@digitalclubb Your solution that re-exports a common config is a great one if it works for you.

That said, you can take advantage of [test projects](https://playwright.dev/docs/test-advanced#projects), specifically [`TestProject.testDir`](https://playwright.dev/docs/api/class-testproject#test-project-test-dir):

```js
const config = {
  projects: [
    {
      name: 'app1',
      testDir: './app1/tests/functional',
    },
    {
      name: 'app2',
      testDir: './app2/tests/functional',
    },
  ],
};
export default config;
```

Then you run one or multiple projects:
```bash
# one project
npx playwright test --project=app1
# all projects
npx playwright test
```

[Learn more](https://playwright.dev/docs/test-advanced#projects) about projects.

**Comment by digitalclubb** [comment]
Hi @dgozman - thanks for taking the time to look over this. Reading more about projects, it does seem to offer the functionality to help. My team and I use Playwright for all of our testing including functional, smoke, accessibility (axe-playwright) and visual differences so I've now updated the repo to utilise projects. That's a great feature:

```
projects: [
		{
			name: 'chromium',
			use: { browserName: 'chromium' },
		},
		{
			name: 'webkit',
			use: { browserName: 'webkit' },
		},
		{
			name: 'accessibility',
			testDir: 'tests/accessibility',
			use: { browserName: 'chromium' },
		},
		{
			name: 'smoke',
			testDir: 'tests/smoke',
			use: { browserName: 'chromium' },
		},
		{
			name: 'visual',
			testDir: 'tests/visual',
			use: { browserName: 'chromium' },
		},
	],
```

In terms of adding the different applications as projects - I don't feel like this will scale as well as re-exporting a configuration file. We offer a small CLI to create a new application and I would be hesitant to add the complexity to modify the shared config file rather than just copy across the small individual re-exported configs. 

Regardless of that, I now have a better understanding of the concept behind projects so I appreciate the input.

Happy to close this feature request - thanks for your input!
