### ISSUE TITLE
playwright.config.js implementation for non JS bindings

### ISSUE THREAD

**Issue by sunjeet-khokhar** [microsoft/playwright#11280]
https://playwright.dev/docs/test-configuration 
The use for config file for the node.JS implementation is very effective & flexible ( e.g. to run tests across multiple browsers just through a config file) 

![image](https://user-images.githubusercontent.com/15244739/148728773-6e456cf9-22d6-49cc-a495-8e6b9e2bd527.png)

However, the docs dont seem to have an equivalent config file examples for other binding e.g. .NET 
Does this exist ?

If yes, are there any examples on how to implement it for .NET ?

Thanks

**Comment by aslushnikov** [comment]
> However, the docs dont seem to have an equivalent config file examples for other binding e.g. .NET
Does this exist ?

@sunjeet-khokhar Playwright config is a part of the Playwright Test runner that is only available in JavaScript / TypeScript. So no, it does not exist for .NET.

In .NET, we recommend using NUnit as a test runner; read more: https://playwright.dev/dotnet/docs/test-runners
