### ISSUE TITLE
[Feature] export enum with availble key names

### ISSUE THREAD

**Issue by owenpearson** [microsoft/playwright#1128]
selenium-js [exports a Key object](https://www.selenium.dev/selenium/docs/api/javascript/module/selenium-webdriver/index_exports_Key.html) which has all of the available key names as constants rather than having to pass in bare strings. as far as i can tell playwright doesn't do the same.

i think it would be nice if playwright did the same. that way i wouldn't have to use [that usKeyboardLayout file](https://github.com/microsoft/playwright/blob/master/src/usKeyboardLayout.ts) for reference when simulating keypresses. it would also be useful if you could use that enum to type API methods which accept key names so that developers get a typescript error if they try to send an invalid key.

**Comment by dgozman** [comment]
We should do this as a part of #6. Thank you for the issue!

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1128
