### ISSUE TITLE
[Question] webServer -> http-server -> timeout

### ISSUE THREAD

**Issue by andreabisello** [microsoft/playwright#11287]
hi,
i installed https://www.npmjs.com/package/http-server to serve an http server on my vue-cli application
the web server can be up and running with this command

_http-server dist 8080 --cors -a localhost_

![image](https://user-images.githubusercontent.com/2149815/148759777-f7c93293-f6cf-4d6e-8299-647d53cefed9.png)

using this configuration file

```
import { PlaywrightTestConfig } from '@playwright/test'

const config: PlaywrightTestConfig = {
    webServer: {
        command: 'http-server dist 8080 -a localhost',
        port: 8080,
        timeout: 10 * 1000
    },
    testDir: './tests/playwright',
    retries: 0,
    use: {
        trace: 'off',
        ignoreHTTPSErrors:true,
        headless:false
    },
    expect: {
        toMatchSnapshot: { threshold: 1 },
    },
}

export default config

```

but executing

npx playwright test

a timeout occur

```
PS C:\src\new-firma-certa> npx playwright test
Using config at C:\src\new-firma-certa\playwright.config.ts
Error: Timed out waiting 10000ms from config.webServer.
    at WebServer._waitForAvailability (C:\src\new-firma-certa\node_modules\@playwright\test\lib\webServer.js:118:25)
    at WebServer._waitForProcess (C:\src\new-firma-certa\node_modules\@playwright\test\lib\webServer.js:104:5)
    at Function.create (C:\src\new-firma-certa\node_modules\@playwright\test\lib\webServer.js:62:7)
    at Runner._run (C:\src\new-firma-certa\node_modules\@playwright\test\lib\runner.js:244:51)
PS C:\src\new-firma-certa>
```

any suggestion please?

thanks

**Comment by dgozman** [comment]
@andreabisello It says "timed out". Try increasing `webServer.timeout` option and see whether that helps. Alternatively, if you could share a full repro with us, we can take a look.

**Comment by andreabisello** [comment]
@dgozman increasing timeout to 180000 changed nothing. http-server launch time is near to zero . we are going to prepare an example repository , thanks

**Comment by andreabisello** [comment]
problem was in http-server due the hack of colours.js , updating to the latest release of 23 hours ago, web server works again
