### ISSUE TITLE
[Feature] Programmatically access Native File System

### ISSUE THREAD

**Issue by judofyr** [microsoft/playwright#11288]
I'd like to see support for programmatically choosing which files/directories will be used by the Native File System API. I think it would make sense to re-use the `FileChooser`-type for this.

Proposed example:

```javascript
const { chromium } = require("playwright");

async function main() {
  let browser = await chromium.launch();
  let page = await browser.newPage();
  page.on('filechooser', async (fileChooser) => {
    await fileChooser.setFiles('/tmp/hello');
  });
  await page.goto("https://www.google.com/");
  let dirName = await page.evaluate(async () => {
    let dir = await window.showDirectoryPicker();
    return dir.name;
  });
  console.log({ dirName });
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
```

**Comment by yury-s** [comment]
We consider providing a way to mock showDirectoryPicker and other page APIs, it is tracked in https://github.com/microsoft/playwright/issues/11670

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by mxschmitt** [comment]
New feature request is https://github.com/microsoft/playwright/issues/18267.
