### ISSUE TITLE
[Question] `npx playwright install` command in a self hosted npm environment

### ISSUE THREAD

**Issue by cenkiravul** [microsoft/playwright#11298]
I want to utilize playwright as a part of our testing framework. My employer maintains its internal npm repository due to security assurance and the only way to use a package is to get it added to that repo. (This goes for all package installers, even app store, etc. are disabled and instead we use the internally managed alternatives)

I have made my case to get playwright an internal approval, however `npx playwright install` installs 4 packages from Microsoft's CDN. I am aware that one can pass an environment variable to install from an artifact repository, but still having the option of not passing the environment variable is the concern for the security department. The only option so far is to fork the repo and modify https://github.com/microsoft/playwright/blob/eaf2507ec1322401e5fb05c976a0d2a4d1c438f9/packages/playwright-core/src/utils/registry.ts#L599 to hardcode our internal endpoint, but it's not preferred either to avoid extra maintenance.

Would there be any other solutions to this, or a way to change the dependency installation mechanism?
All suggestions are welcome.

Thanks in advance.

**Comment by aslushnikov** [comment]
> I am aware that one can pass an environment variable to install from an artifact repository, but still having the option of not passing the environment variable is the concern for the security department. 

@cenkiravul usually security teams maintain a proxy / firewall to prohibit downloads from untrusted endpoints. Is it not the case in your case?

> The only option so far is to fork the repo and modify <...> to hardcode our internal endpoint, but it's not preferred either to avoid extra maintenance.

This still would be error prone since running `npx playright install` outside of the NPM package will fetch latest upstream Playwright repository and download browsers from our CDN.

> Would there be any other solutions to this, or a way to change the dependency installation mechanism?

What would you suggest?

**Comment by mxschmitt** [comment]
Closing since it seems answered and stale. Please open a new issue for further questions and reference to this one.

**Comment by cruwe** [comment]
Please excuse bumping old threads, but stumbling across in search for a solution found elsewhere:

The desired behaviour may be achieved setting `PLAYWRIGHT_DOWNLOAD_HOST` in the environment.
