### ISSUE TITLE
[Feature] Browser context serialization to support local storage

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#1129]
The `browserContext.cookies` and `browserContext.setCookies` methods make it possible for users to serialize cookies and load them into a new context. This enables loading a new context with authentication state before running tests.

Some apps use local storage to maintain their authentication state, and we should have similar methods for local storage.

Additionally, it might be worth evaluating whether we want to create a higher-level abstraction ("browser context state" maybe?) that covers all such storage (cookies, local storage, indexed db, etc). That way, users will not need to know which storage type they want to serialize and load over. In many cases, users are building applications where authentication is third-party (SSO etc) and therefore knowing which state type is used by auth is not possible.

**Comment by jperl** [comment]
We built this in [playwright-utils](https://github.com/qawolf/playwright-utils), will be shipped in next version (cookies, localStorage, sessionStorage, not indexed db yet)

**Comment by vrknetha** [comment]
I would use this to save the state so that I don't need to redo the steps for login and some other authentication

**Comment by arjun27** [comment]
We now have a [guide for sharing authentication state](https://playwright.dev/#version=v1.4.0&path=docs%2Fauth.md&q=) across browser contexts (using APIs for cookies and local storage). We could evolve this into a unified API for all "browser context state" based on user feedback. Please share your user scenarios and help us identify what's missing :)

**Comment by pavelfeldman** [comment]
This is now implemented via https://playwright.dev/#version=master&path=docs%2Fapi.md&q=browsernewpageoptions--options-storagestate

**Comment by joshpzero** [comment]
@pavelfeldman Is there any reason this doesn't save sessionStorage?

**Comment by joshpzero** [comment]
@pavelfeldman Can we please get sessionStorage included in this? It seems odd that it wouldn't be considered part of the storage state, even if it is less frequently used.

**Comment by yury-s** [comment]
@joshpzero can you file a separate feature request for this? There are some questions like what to do if there are two pages from the same origin in the same context that have different sessionStorage states, otherwise it's doable.
