### ISSUE TITLE
Playwright Advance Conf - Projects [] - Run only a selected number of tests

### ISSUE THREAD

**Issue by fasatrix** [microsoft/playwright#11309]
Hi,
We are setting up a playwright multi-project using different devices like for instance the following 
import { PlaywrightTestConfig, devices } from '@playwright/test';

```
const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'iPhone 11',
      use: { ...devices['iPhone 11 Pro'] },
    },
  ],
};
export default config;
```

However, we do not want to run all tests against the iPhone but only a selected number of them. What is the best/cleaner way to achieve this? 

Thanks in advance for the answer

**Comment by dgozman** [comment]
@fasatrix

- **Option 1**. Put your iPhone tests in a separate directory, and use [`TestProject.testDir`](https://playwright.dev/docs/api/class-testproject#test-project-test-dir):
  ```js
  {
      name: 'iPhone 11',
      use: { ...devices['iPhone 11 Pro'] },
      testDir: './iphone-tests',
  },
  ```

- **Option 2**. Name your iPhone tests differently, for example `my-test.iphone.spec.ts` and use [`TestProject.testMatch`](https://playwright.dev/docs/api/class-testproject#test-project-test-match):
  ```js
  {
      name: 'iPhone 11',
      use: { ...devices['iPhone 11 Pro'] },
      testMatch: /.*iphone\.spec.*/,
  },
  ```
Let me know whether this helps.

**Comment by fasatrix** [comment]
@dgozman Awesome, Thanks a lot that would work!
