### ISSUE TITLE
[Feature] Amazon linux 2 (Red Hat Enterprise Linux)

### ISSUE THREAD

**Issue by jadenmazzone** [microsoft/playwright#11307]
I'd like to see support for Amazon Linux 2 which is the Linux operating system used for Amazon Web Services (AWS) such as EC2 and lambda. After installing playwright currently, I get a missing dependency error on my EC2 instance: #11175

**Comment by mxschmitt** [comment]
For Linux only Ubuntu 18.04 and Ubuntu 20.04 is officially supported see here: https://playwright.dev/docs/library#linux

We'd recommend to use this or use Docker to have the same set of dependencies available.
