### ISSUE TITLE
[Feature] firefox: instrument file:// process in firefox

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#1131]
Firefox opens `file://` urls in a special process. As of #1110, we disable this behavior (and unfortunately reduce sandboxing level for content process). Ideally, we should instrument file process and restore the original sandboxing level.

For the record: this is a somewhat related code in the firefox devtools https://github.com/aslushnikov/juggler/blob/30bfd1bb33f1b3e780a83d8e30e43f3cbcac85c8/devtools/server/actors/process.js#L14

**Comment by pavelfeldman** [comment]
Fixed
