### ISSUE TITLE
[Question]Can I set cookies?

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#11317]
If I log in manually with a browser, get a cookie, and then set it in playwright, can I?

**Comment by dgozman** [comment]
Yes, take a look at [`browserContext.cookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies) and [`browserContext.addCookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies).
