### ISSUE TITLE
[Question] Playwright/test runner with test generator function

### ISSUE THREAD

**Issue by Flunt1k** [microsoft/playwright#11329]
Hi all! 
I'm trying to create function for simplify test generation in my project

Function looks like this

```javascript
import {chromium, test} from '@playwright/test';
export const getRunner = ({config, isTestSuite}) => {

    const runner = isTestSuite ? test : test.describe;

    if (config.only) {
        return runner.only;
    }

    if (config.skip) {
        return test.skip;
    }

    return runner;
};

export function createTest(config, options) {
    config.browserList.forEach((browserName) => {
        const runner = getRunner({config, isTestSuite: false});

        runner(config.title, () => {
            test.beforeAll(async () => {
                // logic based on config
            });

            test.afterAll(async () => {
                // logic based on config
                await browser.close();
            });

            test.afterEach(async () => {
                // logic based on config
                await page.close();
            });

            config.suites.forEach((singleTest) => {
                const testRunner = getRunner({config: singleTest, isTestSuite: true});

                testRunner(config.testTitle, async () => {
                    try {
                        await singleTest.testFunction();
                    } catch (error) {
                        throw error
                    }
                });
            });
        });
    });
}
```

Then I want to call this function in `myTest.test.js` file
And then when I call it i expect this output in reporter
`myTest.test.js > testGroupName > testName'

But unfortunately I receive `../../../createTest.js > testGroupName > testName`. 

Is it possible to get expected behaviour for reporters? It's important especially html reporter since it thinks that I've run only one test and assigns the same `testId` for the all suites. And I'm not able to look at test trace.

**Comment by dgozman** [comment]
This looks very similar to #11126. I'd suggest to read the discussion there for more details, but we recommend playing together with the framework and calling test/describe directly, using helpers/fixtures inside the test itself to share common functionality.

Please comment/reopen if I misunderstood the question.

**Comment by Flunt1k** [comment]
> we recommend playing together with the framework and calling test/describe directly, using helpers/fixtures inside the test itself to share common functionality.

I've tried to add my func to the fixture, it looks like

```javascript
export const myRunner = test.extend({
      createTest: async ({}, use) => {
          await use(createTest)
      }
});
```

Then I'm trying to call it inside the test. 

```javascript
import {myRunner} from './my-runner

myRunner('test_name', ({createTest}) => {
    createTest(config, options)
});
```

And I've got the error that I'm able to use describe only in test file. Since I'm using describe in my `createTest` function.  If i remove it and leave only part that works only with particular case `config.suites`, I'm receiving that ` beforeAll hook can only be called in a test file`.

Is it possible to generate full test (describe and tests inside) by helper and still have right path to the test file?

**Comment by hananmalka** [comment]
Happens to me as well when I'm overriding test fixture. 
I'm trying to extend test fixture and in the test file I'm getting the error:
`describe() can only be called in a test file`
