### ISSUE TITLE
[BUG] chromuim page crashes in docker on macOS 12

### ISSUE THREAD

**Issue by d-alexandrov** [microsoft/playwright#11322]
**Context:**
- Playwright Version: 1.17.2 (bug first encountered on 1.8.1);
- Operating System: macOS 12.1 Monterey
- Node.js version: 12.22.7
- Browser: chromium
- Extra: using Playwright in Docker via mcr.microsoft.com/playwright:v1.17.2-bionic with jest-playwright-preset

**Code Snippet**

```javascript
module.exports = {
  launchOptions: {
    headless: true
  },
  contextOptions: {
    ignoreHTTPSErrors: true,
    viewport: {
      width: 1920,
      height: 1080
    }
  },
  browsers: ['chromium'],
  devices: []
};
```

**Describe the bug**

After upgrading from macOS Big Sur to macOS Monterey, I've started to encounter a lot of fails in my test suites, all related to target page crashing while navigating:

```
page.goto: Navigation failed because page crashed!
uikit-tests_1  |     =========================== logs ===========================
uikit-tests_1  |     navigating to "....", waiting until "load"
uikit-tests_1  |     ============================================================page.goto: Navigation failed because page crashed!
```

Nothing changed environmentally but the OS version. I've also confirmed with my colleague that all suites continue to work normally on Big Sur. 

We've used Playwright 1.8.1, upgrade to 1.17.2 did not solve our problem.

Thank you in advance!

**Comment by mxschmitt** [comment]
Would it be possible to create a small repro for us which demonstrates the Chromium crash?

You can also try setting the `DEBUG=pw:browser` environment variable to see if this gives you a more detailed stack-trace.
