### ISSUE TITLE
[BUG] Whitespace in HTML is considered as text

### ISSUE THREAD

**Issue by StevenDenman** [microsoft/playwright#11325]
**Context:**
- Playwright Version: 1.17
- Operating System: Windows

**Code Snippet**
```cs
using Microsoft.Playwright;
using System;
using System.Threading.Tasks;

namespace PlaywrightTest
{
    public class Program
    {
        static async Task Main()
        {
            var playwright = await Playwright.CreateAsync();

            var options = new BrowserTypeLaunchOptions
            {
                Headless = false
            };

            var browser = await playwright.Chromium.LaunchAsync(options);

            var context = await browser.NewContextAsync();

            var page = await context.NewPageAsync();
            context.SetDefaultTimeout(3000);

            await page.GotoAsync("https://codepen.io/StevenDenman/pen/VwMEBZq");

            var frame = page.FrameLocator("#result").First;

            var tds = frame.Locator("td");

            for (int i = 0; i < 5; i++)
            {
                Console.WriteLine($"Text for {i} = '{await tds.Nth(i).TextContentAsync()}'");
            }
        }
    }
}
```

**Describe the bug**

The table in that CodePen is:

```
<table>
  <tbody>
    <tr>
      <td><pre>Line1</pre></td>
    </tr>
    <tr>
      <td>
        <pre>Line2</pre></td>
    </tr>
    <tr>
      <td><pre>      Line3</pre</td>
    </tr>
    <tr>
      <td><p>Line4</p</td>
    </tr>
    <tr>
      <td><p>
        Line5
        </p</td>
    </tr>
  </tbody>
</table>
```  

**Expected:**
Whitespace outside of the `<pre>` tags is ignored in HTML, so I would expect `TextContentAsync()` to honour that.

```
Text for 0 = 'Line1'
Text for 1 = 'Line2'
Text for 2 = '      Line3'
Text for 3 = 'Line4'
Text for 4 = 'Line5'
```

**Actual:**
```
Text for 0 = 'Line1'
Text for 1 = '
        Line2'
Text for 2 = '      Line3
    '
Text for 3 = 'Line4
    '
Text for 4 = '
        Line5

    '
```

**Issues**
1. The whitespace in-between the `<td>` and `<pre>` (including the new line at the start) was returned in Line2
2. The whitespace inside `<p>` (as well as most other tags) was returned in Line5
2. A new line has been added to the end of Line3 and Line4 which doesn't exist anywhere in the HTML

**Comment by dgozman** [comment]
We follow the web spec for [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent). Will trimming the string work for you?

**Comment by StevenDenman** [comment]
No, you should keep returning what the JS does.

What I am thinking of was innerText, this works as expected, not sure if the docs could make this clear as someone who hasn't done much JS would not be aware of the subtlety!
