### ISSUE TITLE
[Question] APIRequestContext in as test steps

### ISSUE THREAD

**Issue by btd** [microsoft/playwright#11328]
Hi,

is it possible to display APIRequestContext calls (http calls) in reporter steps? Like for example some step with special category?
I tried with basic posts and searched in code but did not found anything

Thank you

**Comment by dgozman** [comment]
@btd Are you using `page.request.get()` or `playwright.newRequest()`? Mind sharing a short snippet?

**Comment by btd** [comment]
I did simplified:
```ts
 test.beforeEach(async ({ page, request }) => {
    const userId = await loginWithRandomUser(request, page);
});

const loginWithRandomUser = async (
  request: APIRequestContext,
  userId: number
) => {
  // some code there
  await request.post(
    `url`
  );
  // some code there
};

```

**Comment by dgozman** [comment]
@btd Thank you, this makes sense.

**Comment by btd** [comment]
@dgozman thanks a lot
