### ISSUE TITLE
[Question] headless mode cant waitForSelector correctly

### ISSUE THREAD

**Issue by bugisfeature** [microsoft/playwright#11323]
## Context:
Playwright Version: 1.17.2 
Operating System: macOS 10.15.7
Node.js version: 14.17.0
Browser:chrome

## case: 
   later I will append a demo repo.

## Desc:
   I use 1.17.2 to test my WebRTC application,  when join room success ,it will create ` <video />` and play stream on it. I find when set `headless = false`, the test case can get `<video />` correctly, but  if set `headless =true` , `page.waitForSelector('video', 'attached'/*or 'visible'*/ )`, it will timeout.
   I don't know whether the config is wrong :)

Thank you in advance!

**Comment by dgozman** [comment]
Try using [debugging tools](https://playwright.dev/docs/debug), for example record a trace in headless mode and see what's going on. If you have a repro, share it with us, and we'll be able to take a look.

Also note that Chromium (bundled in Playwright by default) might be missing some codecs for the video. See [documentation](https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to) for more details.

**Comment by bugisfeature** [comment]
thanks for your replay. I find that if I set browserType.launch options with fake device, it will work correctly in headless mode.
```
 const browser = await chromium.launch({
    args: [
         '--use-fake-device-for-media-stream',
         '--use-fake-ui-for-media-stream',
        ],
  });

  const context = await browser.newContext();

  context.grantPermissions(['camera', 'microphone']);
  const page1 = await context.newPage();
 
// ....tests 
```
thank u again 😊
