### ISSUE TITLE
[BUG] Playwright report text not readable in Safari in dark mode

### ISSUE THREAD

**Issue by vthommeret** [microsoft/playwright#11333]
**Context:**
- Playwright Version: 1.17.1
- Operating System: macOS 12.1
- Node.js version: 17.3.0
- Browser: Safari 15.2
- Extra: Using dark mode on Mac

**Describe the bug**

When viewing the Playwright report in dark mode on Safari the text is not readable. In this image, Safari is below, Chrome is on top:

<img width="807" alt="Screen Shot 2022-01-11 at 1 45 42 PM" src="https://user-images.githubusercontent.com/42359/149026391-57d55f17-5c04-482d-b3e2-3bf2ac726e73.png">

Taking a very cursory look, it seems like no color is explicitly set for the main body text and Chrome sets it to white by default for dark mode, but Safari doesn't.

**Comment by Nav-2d** [comment]
Firefox dark mode is hard to read too. The numbers on the filter chips are not readable and hover makes the whole row dark.

![Screen Shot 2022-01-11 at 5 30 36 PM](https://user-images.githubusercontent.com/22205721/149047908-aaccd9f1-89a8-45f3-917d-05307de699ce.png)
