### ISSUE TITLE
[Feature] Headed Browser to Open in the monitor you're running the test from 

### ISSUE THREAD

**Issue by tallyw00d** [microsoft/playwright#11331]
Often times I run my tests from one of my 3 monitors, but I click on to another monitor right away to work on other things while my tests run.  When I do this, the headed browser opens up where I'm working instead of the monitor I was working on before, which means I have to stop and move the browser back to the screen I wanted it to.  If I run the test from the terminal on monitor 1, that's where I would like it to stay. 

I believe others would benefit as most developers are using 2+ monitors.

**Comment by dgozman** [comment]
@tallyw00d I think this would be very hard to do, because it involves a) determining the display that you run your terminal on and b) forcing a particular display for the browser. I'll leave the issue open to collect feedback, but I wouldn't set my expectations high.

**Comment by AllanMedeiros** [comment]
One solution for this is to run your tests within a Docker container, then you can watch the tests using VNC and you place the VNC window wherever you want.
But when running locally is more complicated, I believe you could find some values for --window-position flag that works for you, then you would have one X,Y combination for each monitor.

**Comment by rasoulcpp** [comment]
@JoelEinbinder wrote a solution [here](https://github.com/microsoft/playwright/issues/4943#issuecomment-758113586) and you can also set negative values for x and y.
```ts
const browser = await chromium.launch({
		...
		args: ['--window-position=x,y'],
		...
	});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by ramdjaram** [comment]
> Often times I run my tests from one of my 3 monitors, but I click on to another monitor right away to work on other things while my tests run. When I do this, the headed browser opens up where I'm working instead of the monitor I was working on before, which means I have to stop and move the browser back to the screen I wanted it to. If I run the test from the terminal on monitor 1, that's where I would like it to stay.
> 
> I believe others would benefit as most developers are using 2+ monitors.

Just make a main display from one you want to run your tests on :)

**Comment by AllieVoATK** [comment]
@ramdjaram that's the issue. It doesn't stay with your main display but each test jumps to whichever one you are currently using, meaning you are constantly interrupted or have to be completely idle while the tests run

**Comment by Zweih** [comment]
> Just make a main display from one you want to run your tests on :)

@ramdjaram I believe the issue is that people don't want to run the tests on their main display, they use their main display primarily for content that is actively being worked on.

**Comment by ramdjaram** [comment]
Yeah, I'm aware of that but in absence of a solution this is a workaround.

**Comment by AllieVoATK** [comment]
@ramdjaram not sure if you've noticed but your workaround doesn't work. wherever you are typing, the test will jump to that screen and take it over. It's very disruptive

**Comment by rob-smallshire** [comment]
As @AllieVoATK says, the `--window-position=x,y` workaround does not work, on macOS at least.

**Comment by ma225tq** [comment]
For anyone on Linux, you can use Xephyr to run the PW tests in a virtual display. (Unfortunately this seems to only work when running tests in Chromium.)

`sudo apt install -y xserver-xephyr`

example of script for running PW headed in Xephyr:

`test-pw-a": "Xephyr :100 -screen 1280x720 & sleep 2 && DISPLAY=:100 npx playwright test --headed`
