### ISSUE TITLE
[BUG] Can't get the root scope for Locator element

### ISSUE THREAD

**Issue by MikeShysh** [microsoft/playwright#11332]
**Context:**
- Playwright Version: 1.17.2 JS
- Operating System: Linux 
- Node.js version: v14.18.1
- Browser: Chromium

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {

  await page.goto('');
    const chbox = page.locator('[helpid="product.search_results"] >> .tr:has-text("Super Product") >> mat-checkbox');
    await chbox.locator('.mat-checkbox-inner-container').click();
    await chbox.locator(':scope.mat-checkbox-checked').waitFor({ state: 'attached' });  <<<< FAILED, NOT FOUND
});
```

**Describe the bug**

I pass Locator to the object comstructor. In scope of internal object methods I need to check the attribute of the root element identified by Locator. It's impossible to do with current implementation of Locator
Here is HTML:
![mat-checkbox](https://user-images.githubusercontent.com/13480390/149017939-5a063606-cf32-42dc-b86b-7bec1a72682d.jpeg)

 await chbox.locator(':scope.mat-checkbox-checked') or  await chbox.locator('.mat-checkbox-checked:scope') does not work.

If :scope does not suit here please consider the abovementioned use-case. Maybe there is another way to get the root scope of the Locator.  
Maybe its worth creating internal method in playwright to modify chain of Locators. For example,
I see that locators joins just by >> . It would be perfect to implement method to change the logic of locators join
```javascript
    const chbox = page.locator('[helpid="product.search_results"] >> .tr:has-text("Super Product") >> mat-checkbox');
    await chbox.rootLocator('.mat-checkbox-checked >> div')  // or in could be named rootScope / ancestorScope etc
});
```
As a result we get a locator ```[helpid="product.search_results"] >> .tr:has-text("Super Product") >> mat-checkbox.mat-checkbox-checked >> div ```
instead of default 
```[helpid="product.search_results"] >> .tr:has-text("Super Product") >> mat-checkbox >> .mat-checkbox-checked >> div ```

**Comment by dgozman** [comment]
Thank you for filing. The `:scope` example should work, so there is indeed a bug. Additionally, let us think about extending the API.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to file a new issue for any outstanding requests.
