### ISSUE TITLE
[Question] Profile test execution

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#11346]
We've moved our tests from Jest to Playwright Test, and we experience our execution times increase drastically. 

We have 30 tests that were completing in **20 minutes** when executed by Jest, and now, same tests, on the same environment - take almost **2 hours**.

We've also converted our tests to TypeScript, but that shouldn't add that much of time to the execution, I believe.

So I wonder if there are any ways to profile the tests execution, so we can see where do we spend the most time?

**Comment by dgozman** [comment]
@creage Try running with `PWTEST_PROFILE_DIR=/path/to/some/empty/dir npx playwright test` and load profile files in Chrome DevTools Performance panel. That's our internal workflow, and I would be very interested whether it will work for you. Most likely, though, Playwright is just waiting for the browser to load the page, so this won't give much insights.

**Comment by mxschmitt** [comment]
Closing since its answered. It most likely increases because Playwright Test does create a new context for each test and jest-playwright re-uses the page/context for each test.

If you have a concrete repro if something is slow or miss-behaving, we're happy to dig into it.
