### ISSUE TITLE
[Feature] Display meaningful name in html report

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/playwright#11347]
Now html report showing it like below

locator.type([name=userName], sudhakar)

This is actually showing technical details about the executed steps. But the idea of a html report is to share with non technical members. Otherwise we could've simply used logs.
It is better to add meaningful element name while defining locator like below and show it in html report.
Example: page.locator("[id=userName]", 'username textbox')
Show "username textbox" in html report

<img width="437" alt="playwright report" src="https://user-images.githubusercontent.com/24471190/149123790-b96acfbc-9f6f-4d7f-b16f-c8d3e76b5da4.png">

**Comment by dgozman** [comment]
Closing in favor of #10857 that asks for the same feature.
