### ISSUE TITLE
Adblocker for Chromium

### ISSUE THREAD

**Issue by Draconic07** [microsoft/playwright#11348]
Hello,
I've made some research on internet and people tell that there's no way to use chromium extensions with headless mode, but I need to use adblocker on Chromium with Python. Because the website  want to automate requires ads to be closed by clicking close button to navigate to different pages on it. I can still use with headed mode, but I want to hide the browser. Also I can switch to the different browsers if they have ability to adblock on headless mode. Please help me with this issue.
Thanks in advance.

**Comment by dgozman** [comment]
@Draconic07 Chrome extensions are only supported in the headed mode, there is no way to run them headless. The way to hide browser window is to run in headless mode though. Not sure how we can help here. Just in case, here is [documentation about extensions](https://playwright.dev/docs/chrome-extensions).
