### ISSUE TITLE
[Question] Headless mode use a deprecated browser

### ISSUE THREAD

**Issue by Facundojs** [microsoft/playwright#11354]
Right now, I'm using playwright to scrap a page and obtain some info. Without using the headless mode, it works perfectly. The thing is, when I use the headless mode, the context is using an obsolete browser version that the page doesn't support and I can't go further.

Is there a way to change the browser/use a newer version only in headless mode? Repeating myself, the headfull mode is doing its work, but the headless mode isn't.

I tried changing the user agent and the browser path and it didn't work either.

### Here is the info about my execution enviroment.
```
Playwright Version: 1.17.2. Also tried with same version of playwright-chromium.
Operating System: Ubuntu 21.10 Desktop
Distributor ID: Ubuntu
Description:  Ubuntu 21.10
Release:  21.10
Node.js versions tried: 14.0.0 and 14.18.1
Browser: Default Chromium and Microsoft Edge
```
Thank you for your attention.

**Comment by dgozman** [comment]
@Facundojs Headless and headed browsers have exactly the same version. You can check it by `console.log(browser.version())`. The site probably checks user agent string and refuses to work in the headless browser. That's their choice, and Playwright cannot help with that.

**Comment by Facundojs** [comment]
Is there a possibility to use a kind of user agent that hides the headless mode?
I tried using the one that i get in this site
- https://developers.whatismybrowser.com/useragents/parse/?analyse-my-user-agent=yes

And the one that i get using `navigator.userAgent`
