### ISSUE TITLE
[BUG] iframe is stuck loading

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#11355]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: 16.13.1
- Browser: Chromium
- Extra: N/A

**Code Snippet**
I am trying to do a checkout on a ecommerce website and there is a section with the payment and billing information which uses an iframe to display the credit card data which needs an input like name, credit card number and cvv
I tried to debug it and what happens is that it just hangs there when loading the iframe for some reason. It is stuck in this infinite loop of loading the iframe. I don't know why.  
This is a screenshot from the debug window. I am using everything as expected regarding the iframes at least to my knowledge 

![Screenshot_11](https://user-images.githubusercontent.com/6464981/149195134-9c93a204-bebe-4afa-9cf3-620b202ee867.png)   

**Describe the bug**

So the issue is that my iframe is stuck loading for some reason, even though I am using proper calls.
Let me know if I can provide more info. 

Can you please help :D

**Comment by dgozman** [comment]
Try using [debugging tools](https://playwright.dev/docs/debug), for example record a trace and see what's going on. Perhaps the iframe does not load? Other than that, we'll need a repro to be able to help you.

**Comment by mareru** [comment]
@dgozman Thanks for the reply,
I am already using Playwright inspector and all I can see it loads there for ever.
Could the issue be the fact that my iframe is nested inside the another iframe?
How to deal with the nested iframes in proper way?
Since this is actual client site and the data are confidential, I can't share the repo with you.
But is there a possibility to have like one time short debug session in order to check with me what could be the issue? Just asking if this is something you can offer as well :D

**Comment by mareru** [comment]
That was the issue. I needed to target first the parent iframe and then target the inner iframe. 
Thanks a lot for reaching out and I think we can close this one.
I am just gonna leave a code snippet which helped with this. Maybe it helps someone struggling with the same issue.
Sorry for the inconvenience.
 
```
 const frame = page.frameLocator('#xiFrameHosted');

  const innerFrame = frame.frameLocator('#xieCommFrame');

  await innerFrame.locator('input[name="c-chn"]').fill('test');
```
