### ISSUE TITLE
[Question] Headless mode not working well

### ISSUE THREAD

**Issue by EnzoPujol** [microsoft/playwright#11364]
Hello people, I'm trying to use playwright to get some page info and it's doing it in headfull mode, but the page is not supporting the browser if I do it in headless mode. I know already that the version is the same in both modes, so it's kinda strange from my point of view. I tried using some user agents and another browser (Microsoft Edge) but it's no use.

I was thinking maybe the page knows that I'm scrapping it and refuses the operation, but if that's the case, is there a way to not tell the page that I'm entering with a scrapping application? 

### I'm setting my user agent to use headless mode like this at the moment:

```
    const browser = await chromium.launch({
      headless: true,
    });

    const context = await browserr.newContext({
      userAgent: 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.71 Safari/537.36',
    })
    const contextBrowser = context.browser()
    response.setBrowser(browser);
    const page = await browser.newPage();
```

Here is the info about my execution enviroment, just in case.

- Playwright Version: 1.17.2. Also tried with same version of playwright-chromium.
- Operating System: Ubuntu 21.10 Desktop
- Distributor ID: Ubuntu
- Description:  Ubuntu 21.10
- Release:  21.10
- Node.js versions tried: 14.0.0 and 14.18.1
- Browser: Chromium and Microsoft Edge

_Thank you for answering!_ 🙏

**Comment by aslushnikov** [comment]
> I was thinking maybe the page knows that I'm scrapping it and refuses the operation, but if that's the case, is there a way to not tell the page that I'm entering with a scrapping application?

@EnzoPujol Different evasion techniques of these kind fall outside of the scope of Playwright project so we don't give any advice here. There should be plenty of resources online though!
