### ISSUE TITLE
[BUG]  playwright test 1.18.0-alpha with ESM: Page type incompatibility

### ISSUE THREAD

**Issue by laurentpayot** [microsoft/playwright#11378]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Ubuntu 21.10
- Node.js version: 17.3.0
- Browser: All
- Extra:  **@playwright/test 1.18.0-alpha-jan-10-2022**

Related to #7121. I’m using ESM with TypeScript. [The alpha release fix](https://github.com/microsoft/playwright/issues/7121#issuecomment-1009140849) is working great for now, except for this type issue.

In my helper files I used to import the `Page` type this way:
```typescript
import type { Page } from 'playwright'
```

Using the alpha release of playwright/test, I get:
```
Argument of type 'import("/home/laurent/projects/myproject/node_modules/@playwright/test/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/home/laurent/projects/myproject/node_modules/playwright-core/types/types").Page'.ts(2345)
```

So now I have to import the `Page` type like so:
```typescript
import type { Page } from '@playwright/test/node_modules/playwright-core'
```

**Comment by dgozman** [comment]
Do you have a different version of `playwright-core` somewhere in your dependencies? Note the difference between two paths in the error message:
```log
"/home/laurent/projects/myproject/node_modules/@playwright/test/node_modules/playwright-core/types/types"
vs
"/home/laurent/projects/myproject/node_modules/playwright-core/types/types"
```

I'd suggest to remove any other playwright dependencies from your package.
