### ISSUE TITLE
[Question] When executed Playwright tests are executed with only one worker in github actions

### ISSUE THREAD

**Issue by kuladeep-journey** [microsoft/playwright#11373]
We have defined workers: 5 in playwright.config.js.
When executed locally, test are executed in parallel using maximum workers applicable.
However, when executed using github actions, it always uses only 1 worker to execute all tests.

Is this known issue or do I need to add any additional settings to my project?

**Comment by kuladeep-journey** [comment]
I figured out one difference i.e if we are creating automation suite as npm package and runn ing using github actions or local it will always run with 1 worker only.

**Comment by dgozman** [comment]
@kuladeep-journey Something's definitely working not as you'd expect. However, it is hard to help you without seeing the code/errors/logs/etc. Please provide more details.

**Comment by kuladeep-journey** [comment]
Hi,

we have created npm package of our automation scripts using github actions and in other repo (users of automation) we have installed automation npm package and run the command npm run test which triggers the command "npx playwright test" defined in automation package.json script. Everything till here works fine.

However the number of workers in playwright.conf.js is defined as 5 but while execution we see only one worker is used for tests execution.

As the automation we are doing on our client confidential project, I cannot share the code. Logs from github actions is as below:

```sh
cd node_modules/@journeyai/automation-remotebyjourney
  npm install
  npm run test
  shell: /bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /Users/runner/actions-runner/_work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX

> playwright@1.17.2 install /Users/runner/actions-runner/_work/QA_DEMO/QA_DEMO/node_modules/@journeyai/automation-remotebyjourney/node_modules/playwright
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
added 192 packages from 186 contributors and audited 192 packages in 4.055s

16 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


> @journeyai/automation-remotebyjourney@1.0.1 test /Users/runner/actions-runner/_work/QA_DEMO/QA_DEMO/node_modules/@journeyai/automation-remotebyjourney
> playwright test --max-failures 0


Running 28 tests using 1 worker

```

**Comment by kuladeep-journey** [comment]
@dgozman if we overwrite the workers from command line and run the tests with option workers, it is using max workers to run parallel tests.

```sh
npx playwright test --workers=5
```

Now it looks like if the workers >1 and it is npm package of our automation scripts, parallel testing is limiting to 1 worker only.

**Comment by dgozman** [comment]
@kuladeep-journey Since your config is not called `playwright.config.js`, you have to specify the name of your config when running tests: `npx playwright test --config=path/tp/playwright.config.js`. The way you currently run the tests, it seem like your config file is not used at all.

**Comment by kuladeep-journey** [comment]
Hi @dgozman,
Even after specifying the config path, it is using only one worker. Logs are as below:
$npm test --config=/Users/kuladeep/Desktop/experiment/qa_demo/qa_demo/node_modules/@myorg/automation-xxxxxxx/playwright.config.js

> @journeyai/automation-remotebyjourney@1.0.1 test /Users/kuladeep/Desktop/experiment/qa_demo/qa_demo/node_modules/@myorg/automation-xxxxxxx
> playwright test --max-failures 0

Using config at /Users/kuladeep/Desktop/experiment/qa_demo/qa_demo/node_modules/@myorg/automation-xxxxxxx/playwright.config.js

Running 28 tests using 1 worker

--------------------------------------------------------------------------------

Execution started for the testsuite :

**Comment by dgozman** [comment]
@kuladeep-journey If you have a dedicated automation project with a separate `package.json`, you can make it a regular or a dev dependency. It should work in both cases.

**Comment by gauravkrp** [comment]
I'm still facing this issue, my config file is called `playwright.config.ts` 
On GitHub actions, it just uses only one worker, while on local it uses 4 or 5 or 6 workers.
My GitHub action file (generated by playwright) is as below:- 

<img width="489" alt="Screenshot 2023-02-23 at 6 22 03 PM" src="https://user-images.githubusercontent.com/12250556/220911657-a1e95325-f9ac-4dcb-8cd7-673712123a5f.png">

**Comment by shinaBR2** [comment]
> workers: 5 in playwright.config.js. When executed locally, test are executed in parallel using maximum workers applicable. However, when executed using github actions, it always uses only 1 worker to execute all tests.
> 
> Is this known issue or do I need to add any additional settings to my project?

@gauravkrp I think here is the answer, I got the same issu
https://github.com/microsoft/playwright/issues/19408#issuecomment-1347341819
