### ISSUE TITLE
[BUG] browserType.launch: No executable path is specified. Pass "executablePath" option directly.

### ISSUE THREAD

**Issue by sohsPat** [microsoft/playwright#11376]
**Context:**
- Playwright Version: 1.10.0
- Operating System: MacOs Monterrey
- Node.js version: 14.6.1
- Browser: Chromium

I get this error whether trying to run tests through visual studio code or the command line using yarn run test where the browser fails to launch.  This error was happening prior to updating macOs to latest version, and thought it might be related to that but is still occurring after update as well.  There have been no updates made to our test project since the last time I successfully was able to run tests.

Looks similar to the error in issue 5561.

**Comment by dgozman** [comment]
@sohsPat What is your Playwright version? I don't see such an error in v1.17 source. It is hard to say what's going on - could you provide more details? Even better, update to the latest Playwright version to get a more descriptive error message.

**Comment by sohsPat** [comment]
We were using playwright version 1.10.0, I just updated it to 1.17.2 but have received the same error message.  Attempting to run the tests with a yarn command, the full error message I receive back is: 
"before all" hook: beforeAll in "{root}":
     browserType.launch: No executable path is specified. Pass "executablePath" option directly."

**Comment by dgozman** [comment]
@sohsPat Could you share your test config and some test snippet? Full error output would help as well.

**Comment by mxschmitt** [comment]
> but have received the same error message.

The message has changed in recent versions, so probably you are still using an old version. I'd recommend to remove node_modules or run `npm ci` to re-install your NPM modules.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by sohsPat** [comment]
> > but have received the same error message.
> 
> The message has changed in recent versions, so probably you are still using an old version. I'd recommend to remove node_modules or run `npm ci` to re-install your NPM modules.


Hey, sorry for not updating, that was the issue and was resolved after the update was installed.
