### ISSUE TITLE
[BUG] Can't start cookies' name with underscore

### ISSUE THREAD

**Issue by StarWayMan** [microsoft/playwright#11372]
**Context:**
- Playwright Version: 1.14.0
- Operating System: Mac
- Node.js version: v16.10.0
- Browser: All

**Code Snippet**

```
await context.addCookies([
	{
		name: '__Secure-user-id',
		path: '/',
		domain: extractDomain(baseURL),
		value: '2',
	},
]);
```

**Describe the bug**
Whenever I try to add cookies with underscore in it's name, I get an error
` browserContext.addCookies: Protocol error (Storage.setCookies): Invalid cookie fields`

It seems that this bug was also present in puppeteer. However in puppeteer solution was to add `__Secure-` at the beginning. This trick does not help with playwright.

**Comment by dgozman** [comment]
From [MDN article](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie):

```txt
__Secure- prefix: Cookies with names starting with __Secure- (dash is part of the prefix) must be set with the secure flag from a secure page (HTTPS).
```

So, the following works for me (note the secure flag):
```js
  await context.addCookies([
    {
      name: '__Secure-user-id',
      path: '/',
      domain: 'example.com',
      value: '2',
      secure: true,
    },
  ]);
```

Also, to the original question, the following works for me:
```js
  await context.addCookies([
    {
      name: '_user-id',
      path: '/',
      domain: 'example.com',
      value: '2',
    },
  ]);
  console.log(await context.cookies());
```

Could you please share a full repro script where things works unexpectedly?

**Comment by StarWayMan** [comment]
My bad, totally forgot about secure flag. Thank you very much for a fast response!
