### ISSUE TITLE
[BUG] WebServer fails to start, no stdout to troubleshoot

### ISSUE THREAD

**Issue by MarcusFelling** [microsoft/playwright#11383]
Reported on Twitter: https://twitter.com/Rich_Harris/status/1481723023690694658

"WebServer fails to start, but playwright swallows the stdout, meaning all you see is this (screenshot below). This makes CI failures impossible to diagnose. Is there a config option somewhere I can fiddle with?"

![image](https://user-images.githubusercontent.com/6855361/149407057-c97aa3d1-d323-490a-a3d5-85c22f9b023c.png)

**Comment by Rich-Harris** [comment]
This is straightforward to reproduce. Ideally (IMHO!) `npm test` would cause the useful diagnostic information in stdout to be printed when the server fails to start, but only the stderr gets logged. Perhaps it could be enabled via an option?

### package.json

```json
{
  "devDependencies": {
    "@playwright/test": "^1.17.2"
  },
  "type": "module",
  "scripts": {
    "start": "node server.js",
    "test": "playwright test"
  }
}
```

### playwright.config.js

```js
/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
  webServer: {
    command: 'npm start',
    port: 3000
  }
};

export default config;
```

### server.js

```js
console.log('useful diagnostic information that will never be printed');
throw new Error('error message that will be printed');
```
