### ISSUE TITLE
[Question] Click on a button not working

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#11380]
Hello,  
I am doing automation of the checkout process for the eCommerce site.  
This is the way I click on a button on the checkout page.  
`await page.locator('#cmdSubmit2').click();`

But it doesn't click the button for some reason while running it in headed mode.
If I use playwright inspector, then it shows in the logs that the button is clicked. 
Like this:
![image](https://user-images.githubusercontent.com/6464981/149383624-7d2dfd18-21f1-45a3-ae57-e3f17f317f59.png)

But actually, the button is not clicked on the page since the request to process credit card data by the payment service provider is not done.

If I run it step by step in a slower manner then it gets clicked.  
So I am puzzled why is this happening. This shouldn't be the case and with the new 1.17.2 version of the playwright, we shouldn't have a need anymore for explicit waits in most cases. 
I don't want to have pauses in my test for this case.  
Do you have any idea what could cause this strange behavior?

Just for reference, this is the setup I use:  
-  Playwright Version: 1.17.1
- Operating System: Windows 10
- Node.js version: 16.13.1
- Browser: Chromium

**Comment by dgozman** [comment]
@mareru Most likely, the page is not fully loaded at the time you click. For example, many pages only add event listeners after making a request for fresh data, or something like that. I'd suggest to `waitForResponse` for some particular response to ensure that page is ready. You can look for such a response either in browser Developer Tools, or in the [Playwright trace](https://playwright.dev/docs/trace-viewer).

**Comment by mareru** [comment]
@dgozman Thanks. It seems like `page.waitForNavigation()` worked for me at the end.
I used this one:  
 ```
 await Promise.all([
    page.waitForNavigation(/*{url: 'https://my-site/en/checkout/multi/payment-method/add'}*/),
    // triggerers the navigation
    page.locator('#deliveryMethodSubmit').click(),
  ]);
```
This is based on the code generated by the recorder for some other similar case.  
Can you please explain what does this argument mean that the method waitForNavigation takes?  
Is it a regex? or something else, it seems a bit different than what the documentation describes.  
Thanks!

**Comment by dgozman** [comment]
@mareru Here the argument is commented out.
```js
page.waitForNavigation(/*{url: 'https://my-site/en/checkout/multi/payment-method/add'}*/)
```

If you are expecting navigation to this particular url, uncomment it. In this case, it will wait for a navigation to a particular url, instead of just "next navigation".
```js
page.waitForNavigation({url: 'https://my-site/en/checkout/multi/payment-method/add'})
```

**Comment by mareru** [comment]
Thanks a lot. 
I am so silly. I didn't expect that to be a comment for some reason. Maybe because it was embedded like that in the method parameters. I feel so like facepalm needed over my face :D
Thanks again for your time and patience.

**Comment by dgozman** [comment]
@mareru No problem! I'm glad that everything worked out in the end 🎉
