### ISSUE TITLE
[BUG] API request removes "/api" from URL's path

### ISSUE THREAD

**Issue by Ernst-D** [microsoft/playwright#11386]
**Context:**
- Playwright Version: [1.17.2]
- Operating System: [Windows]
- Node.js version: [16.13.1]
- Browser: [Chromium]
- 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect} = require('@playwright/test');
const chance = require("chance").Chance;

const apiUrl = "https://reqres.in/api";

test.use({
    baseURL:apiUrl
})

test('Create user', async ({ request }) => {
    let name = chance().name();
    let job = chance().word();
    let response = await request.post('/users',{
        data:{
            "name": name,
            "job": job
        }
    });
    console.log((await response.json()));
    console.log(response.status())
    expect(response.ok()).toBeTruthy();
});
```

**Describe the bug**

Hi, Playwright team! Could you please tell is that a valid behaviour for API testing?

I have apiUrl:
`apiUrl = "https://reqres.in/api"`

It is set as baseUrl in pw-config

```
test.use({
    baseURL:apiUrl
})
```

 When I do request
 ```
 await request.post('/users',{
        data:{
            "name": name,
            "job": job
        }
    });
 ```
 
 It is makes request not to the  "https://reqres.in/api/users", but removes /api from URL's path

![image](https://user-images.githubusercontent.com/80358262/149423511-71c0dae1-7c18-4e0e-9cf7-75527629d9f2.png)

**Comment by dgozman** [comment]
This is how relative URL resolution works on the web. You can try it yourself in browser developer tools with [`new URL()`](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL).

In this particular case, use `"https://reqres.in/api/"` as a base url, and `"users"` or `"./users"` as a relative url.

Closing in favor of identical #10557.
