### ISSUE TITLE
[BUG] page.waitForResponse times out when in --debug mode

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#11387]
**Context:**
- Playwright Version: 17.1

**Code Snippet**

```typescript
import { test } from "@playwright/test";



test("step through", async ( { page }) => {
	async function STEPS () {
		await page.locator("input[name=q]").type("playwright");
		await page.keyboard.press("Enter");
	}

	await page.goto("https://github.com");
	await page.pause();
	const [response] = await Promise.all([
		page.waitForResponse(/^https:\/\/github.com\/search\/count/),
		STEPS(),
	]);
});

```

**Describe the bug**

When using `--debug` mode, `page.waitForResponse` can still timeout when slowly stepping through the tests (20s).

![Screen Shot 2022-01-14 at 2 33 47 pm](https://user-images.githubusercontent.com/20273647/149447262-40e8f1f6-4fdc-4e72-a386-52125cd2c65d.png)

**Comment by dgozman** [comment]
This was fixed by #10958, and will be available in v1.18.
