### ISSUE TITLE
[Feature] IPage to support getting the cookies applicable to the open page

### ISSUE THREAD

**Issue by StevenDenman** [microsoft/playwright#11404]
Currently the only way to get the cookies is to use the browser context and filtering out the domain.

It would be nice if the IPage had a CookiesAsync function that automatically returned the cookies applicable to the Page.Url value so that the tests only need an IPage and don't need to also track the IBrowserContext to get them

**Comment by dgozman** [comment]
@StevenDenman It is unlikely that this API will be introduced, but I'll leave the issue open just in case.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
