### ISSUE TITLE
[Feature] Add jq dependency to playwright container images

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#11412]
This might be something I can implement myself, but I'd like to have jq included in the base playwright focal images if possible. It's a stable and minimal package that has a lot of utility. I believe it's included in the base circleci and github actions runner images.

If you can point me to it, I can make the change myself.

**Comment by dgozman** [comment]
@aslushnikov What do you think of this?

**Comment by unlikelyzero** [comment]
@dgozman @aslushnikov I'm not sure where else you'd like to put it, but I included a PR here https://github.com/microsoft/playwright/pull/11530

**Comment by aslushnikov** [comment]
Hey @unlikelyzero,

> I believe it's included in the base circleci and github actions runner images.

I'm not familiar that much with circleCi, but github actions has [tons of pre-installed software](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-Readme.md). Following them isn't feasible – the image will become too heavy.

I'd suggest a pragmatic approach: let's keep this open for some time and see if there's enough demand for the `jq`. We'll add it if it makes substantial amount of people happy! 

Meanwhile, could you just install jq as a first line of your automation? It's tiny, so it should be fast.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
