### ISSUE TITLE
[Question] what factors might affect screenshot results in different environments?

### ISSUE THREAD

**Issue by owenpearson** [microsoft/playwright#1141]
i've written a screenshot regression test which takes a screenshot of a div on my page using jest-image-snapshot but the resulting screenshots appear slightly different on my colleagues' machines and the test fails, particularly when the screenshot includes text. any idea what might be causing this or any way to ensure that screenshots are exactly the same in different environments? i've only tested using .png screenshots since jest-image-snapshot doesn't support jpeg.

**Comment by pavelfeldman** [comment]
Could you share more about your use case? Are you comparing the screenshots between different OSs (Linux, MacOS, Windows), different browser vendors (Chromium, WebKit, Firefox)?

There is no universal solution that would make screenshots made from different vendors look the same. And even within the vendor, fonts are different on operating systems. You/we can reduce variability via using web fonts, but this is unlikely to solve it in its entirety. In either case, would be great to know what approach you are taking to testing.

**Comment by owenpearson** [comment]
ok so my use case is that i'm working on a react app and i want to take screenshots of my components in various states and pass them in to jest-image-snapshot so that i can find out if i've introduced a visual regression, and so that i have images of my components in source control so that i can use them for documentation etc.

my tests all look something like...

```
// some playwright code
const elem = page.waitForSelector(selector);
expect(await elem.screenshot()).toMatchImageSnapshot();
```

where 'toMatchImageSnapshot' is a jest expect extension imported from 'jest-image-snapshot' which saves the screenshot alongside the test and then takes a new screenshot each time the test runs, compares it to the existing screenshot, and fails the test if the screenshots don't match.

i initially ran the tests on my machine, the screenshots looked fine and i ran a few times and tests passed every time. i then pushed up my branch so i could make sure that other people working on the project could run in their environments. i tried two different colleague's machines and both of them consistently failed, with screenshots that look pretty much identical but if you zoom in there are differences in how text appears. we are all using windows 10 machines and i'm only running tests in chromium at the moment so it's same vendor, same os. i can't really give steps to reproduce since i have no idea what differences in our environments are causing the issue.

the app doesn't use webfonts at the moment, just a font-family css property for the whole app. i can try putting a webfont in and see if that resolves the issue if you think it's worth a shot, although i'm not sure if i'd be happy with introducing a webfont just for testing purposes to be honest.

**Comment by arjun27** [comment]
It might also be worth exploring the `blur` [config option](https://github.com/americanexpress/jest-image-snapshot#%EF%B8%8F-api) in jest-image-snapshot.

> blur: (default 0) Applies Gaussian Blur on compared images, accepts radius in pixels as value. Useful when you have noise after scaling images per different resolutions on your target website, usually setting it's value to 1-2 should be enough to solve that problem.

**Comment by owenpearson** [comment]
thanks for the suggestion. i did try playing around with the `blur` and `threshold` options but unfortunately we agreed that the amount i had to increase each of them to get the tests passing was so much that the tests didn't really have much value anymore.

**Comment by pavelfeldman** [comment]
Could you share a couple of images that don't match? You can dm those to me over the slack if they are sensitive.

**Comment by aslushnikov** [comment]
(closing this since discussion has staled; feel free to write back here though - we keep track of our notifications!)
