### ISSUE TITLE
[BUG] Playwright launch works on windows locally, but launch fails in docker linux.

### ISSUE THREAD

**Issue by guilhermebentomarques** [microsoft/playwright#11419]
**Context:**
- Playwright Version: [1.17.2]
- Operating System: [Linux]
- Node.js version: [12.15.0]
- Browser: [Firefox]
- Extra: [Docker container]

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {
 const browser = await firefox.launch({
      headless: true,
    });
})();
```

Docker File

```
# base image
FROM node:12.15-alpine

# ENV CHROME_BIN="/usr/bin/chromium-browser"\
#     PUPPETEER_SKIP_CHROMIUM_DOWNLOAD="true"
########## 
## Update and Install packages
##########
RUN set -x \
    && apk update \
    && apk upgrade \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/testing" > /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/community" >> /etc/apk/repositories \
    && echo "http://dl-cdn.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
    # add the packages
    ## g++: used to install NodeJS related packages
    ## chromium: used to run Puppeteer
    && apk add --no-cache g++ firefox 

WORKDIR /scripts
WORKDIR /app

RUN apk add --no-cache curl bash
#RUN npm install -g ts

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH
```

**Describe the bug**

The error only happen on Docker with linux, it doesnt happen on Windows, in a local solution.

The folder exists on docker component

![image](https://user-images.githubusercontent.com/10928446/149619493-552b77c3-0903-49ea-beda-8fcb9b3f0909.png)

This is the error message when I try to launch

![image](https://user-images.githubusercontent.com/10928446/149619486-6b40b184-cf92-4b0b-9105-301b13b1df14.png)

**Comment by mxschmitt** [comment]
Playwright only works on Ubuntu 18 and 20 linux distributions, in your case you are using Alpine which is not supported see [here](https://playwright.dev/docs/library#system-requirements). There we can't provide support.

We have a pre-built Docker image which you can use for running it inside Docker: https://playwright.dev/docs/docker
