### ISSUE TITLE
[BUG]Docker/Firefox Error

### ISSUE THREAD

**Issue by JakeStevenson** [microsoft/playwright#1142]
**Context:**
- Playwright Version: [Latest]
- Operating System: [.ci/DockerFile] (node:12)

```DockerFile
FROM node:12

RUN apt-get update && \
    apt-get -y install xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
      libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
      libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
      libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
      libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget 
RUN rm -rf /var/lib/apt/lists/*

# Add user so we don't need --no-sandbox.
RUN groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser \
    && mkdir -p /home/pwuser/Downloads \
    && chown -R pwuser:pwuser /home/pwuser

# Run everything after as non-privileged user.
USER pwuser

WORKDIR /home/pwuser
RUN npm install playwright

COPY test.js .
CMD ["node", "test.js"]
```

```javascript 
const playwright = require('playwright');

(async () => {
    const browserType = 'firefox';
    const browser = await playwright[browserType].launch(
        {
            dumpio: true
        });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await browser.close();
    console.log(browserType + " - end");
})();
```

**Describe the bug**
I used the slightly modified DockerFile from the .ci folder in this repository, then added one of the sample scripts from the README.  But running that script shows that it cannot launch firefox.

I get the following error:

> [0227/160756.645998:ERROR:devtools_pipe_handler.cc(90)] Connection terminated while reading from pipe
XPCOMGlueLoad error for file /home/pwuser/node_modules/playwright-core/.local-firefox/linux-1029/firefox/libxul.so:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /home/pwuser/node_modules/playwright-core/.local-firefox/linux-1029/firefox/libxul.so)
Couldn't load XPCOM.

**Comment by jeshan** [comment]
I'm trying to use it in Docker too to no success. Try installing these: `libxcb-dri3-0 libdrm-dev libgbm-dev libxt-dev`

**Comment by arjun27** [comment]
Thanks for the report. Please refer to [this working dockerfile](https://github.com/arjun27/playwright-github-actions/blob/master/Dockerfile#L8) (based on Ubuntu 18.04) while we update our docs with more examples.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1103
