### ISSUE TITLE
[BUG] Incorrect link in Documentation

### ISSUE THREAD

**Issue by apotrebin** [microsoft/playwright#11422]
**Describe the bug**
- Navigate to https://playwright.dev/docs/release-notes#version-118
- Click link http://aka.ms/playwright/samples  in page block  **Testing Scenarios Cookbook**

**result:** 404 Page not found on GitHub
![Loom Message - 16 January 2022](https://user-images.githubusercontent.com/7914938/149635533-5d3bab56-5024-4f8b-b911-3112c2dc1ea9.gif)

**Comment by MarcusFelling** [comment]
fixed
