### ISSUE TITLE
Not able to open Playwright inspector tool 

### ISSUE THREAD

**Issue by rahulhonashetty** [microsoft/playwright#11439]
I am able to see the Inspector Window but not able to open the tool 
Find the attachment below 

![image](https://user-images.githubusercontent.com/84901337/149784618-2d83b894-e8a1-4ce2-9314-dc52ad161ad9.png)

Please help me with this issue 
Thanks in advance

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/5696

**Comment by rahulhonashetty** [comment]
Not able to resolve my issue can u please guide me further @mxschmitt

**Comment by rahulhonashetty** [comment]
@abubelinha, Go to display setting, set scale and layout to 100%. It will work 
Its a resolution issue

**Comment by abubelinha** [comment]
Thanks @rahulhonashetty , but 100% was already the scale of my display (resolution 1024 x 768).
Although if I set my screen resolution to something which is wider (i.e. 1280 x 768), then the inspector appears.

But I don't think that can be considered a solution at all.
Why should users be forced to change their screen resolution depending on the running application?
That would mean I cannot use two applications at the same time, if they need different resolutions to avoid issues like this.
