### ISSUE TITLE
Can't save HAR file (it hangs)

### ISSUE THREAD

**Issue by StevenDenman** [microsoft/playwright#11435]
### Your question

Following on from [my bug](https://github.com/microsoft/playwright-dotnet/issues/1841) Sometimes (more so on longer tests with lots of UI interaction) when I directly close the browser context to save the HAR, it hangs.

When I specifically close the IPage beforehand it works fine.

The documentation only states to close the BrowserContext, so should we also close the IPage before or is there a bug there?

**Comment by andreabisello** [comment]
@mxschmitt  on playwright 1.20 or 1.21 electron seems to have the same problem: running the same test both on browser and on Electron, electron hangs closing the context. when he timeout occurs, test fails, and the har file is anyway created. Should i open a new test? it's difficult for me to provide a reproducible test due the the presence of the electron app.

**Comment by mxschmitt** [comment]
> @mxschmitt on playwright 1.20 or 1.21 electron seems to have the same problem: running the same test both on browser and on Electron, electron hangs closing the context. when he timeout occurs, test fails, and the har file is anyway created. Should i open a new test? it's difficult for me to provide a reproducible test due the the presence of the electron app.

yes please file a new issue.
