### ISSUE TITLE
[Question] got errors after clone tihs repo and npm install 

### ISSUE THREAD

**Issue by xupea** [microsoft/playwright#11430]
Hi, i follow the [contribute doc](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md) ,failed at `npm install`.

branch: current main branch

node version: 16.0.0

![image](https://user-images.githubusercontent.com/4531660/149651355-93ebf64e-8dbc-4709-ab28-5323d565d99e.png)

it seems playwright-core(the dependency) is not installed in playwright-chromium before running its `install`

**Comment by mxschmitt** [comment]
This should work without any issues, since our GitHub Actions jobs do it a few hundreds times per day. Could you make sure to use Node.js 16+, NPM 8+ and maybe "npm ci" instead of "npm install"?

**Comment by mxschmitt** [comment]
Closing since this is working for us and is most likely an issue of your Node.js / NPM configuration.
