### ISSUE TITLE
[BUG] Typeorm cannot be imported to typescript test because of experimental decorators

### ISSUE THREAD

**Issue by jawil003** [microsoft/playwright#11444]
**Context:**
- Playwright Version: 1.17.2
- Operating System: MacOS Monterey
- Node.js version: 14.18.2
- Browser: All
- TypeORM: 0.2.41
## System:
 - OS: macOS 12.1
 - Memory: 21.42 MB / 16.00 GB
## Binaries:
 - Node: 14.18.2 - ~/.nvm/versions/node/v14.18.2/bin/node
 - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
 - npm: 8.3.0 - ~/.nvm/versions/node/v14.18.2/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```typescript
@Entity()
export class Example {
  @PrimaryGeneratedColumn()
  id: number;

  @Column()
  firstName: string;

  @Column()
  lastName: string;

  @Column()
  age: number;
}
```

```typescript
test("basic test", async ({ page }) => {
  const manager = await getManager();

  await manager.find(Example, { where: { id: 1 } });
});
```

Link to repository: https://github.com/jawil003/puppeteertypeorm-example

**Describe the bug**

I use typeorm with the playwright test executor and I always got this issue: 

```SyntaxError: /Users/jannik/Desktop/playwright-typeorm-example/typeorm/example.ts: Support for the experimental syntax 'decorators-legacy' isn't currently enabled (3:1):```. This seems to have something to do with babel config used to transpile typescript, but this is something it seems like cannot be changed because a .babelrc in root has no effect on this.

**Comment by mxschmitt** [comment]
Since its about the same issue, I'm folding it into #11440.
