### ISSUE TITLE
[Question] Is it possible to override the typescript config and the babel config used?

### ISSUE THREAD

**Issue by jawil003** [microsoft/playwright#11440]
I have a proble I use an external libary which used experimental decorators. But it seems like the babel parser used by playwright doesn't understand them in its default config.

Any possibility to override the config here?

**Comment by mxschmitt** [comment]
Playwright 1.18-rc1 has support for a custom tsconfig, see here: https://github.com/microsoft/playwright/releases/tag/v1.18.0-rc1 and [here](https://github.com/microsoft/playwright/issues/7121#issuecomment-1009140849).

Having a custom Babel config is not supported, what you can do is compile the tests yourself with your custom Babel and run them afterwards with Playwright: https://playwright.dev/docs/next/test-typescript

**Comment by nickofthyme** [comment]
@mxschmitt Are there any plans to continue improving the typescript support? I see the support for `baseUrl` and `paths` or transpiling then running tests.

But ideally we could just point playwright to a custom `tsconfig.json`. Is this end goal, if not what is preventing this commonly used flow?

**Comment by jacobmischka** [comment]
If we can't customize the babel config, could it be updated? In particular, it doesn't seem to support private class fields, despite that being included in `@babel/preset-env` and a stage 4 proposal now.

```
$ playwright test
Using config at /home/mischka/projects/interval2/web/playwright.config.ts

SyntaxError: /home/mischka/projects/interval2/sdk-js/src/index.ts: Class private methods are not enabled.
  81 |   }
  82 |
> 83 |   get #log() {
     |   ^
  84 |     return this.#logger
  85 |   }
  86 |
```

**Comment by mxschmitt** [comment]
Please file new GitHub issues for it as feature requests.
