### ISSUE TITLE
[BUG] Unstable behavior if system goes to sleep

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#1145]
**Context:**
- Playwright Version: 0.11.1
- Operating System: OSX 10.15.2

**Code Snippet**
Gist: https://gist.github.com/VikramTiwari/34c0a1a47008f3ccbc33b563219c02b9

**Describe the bug**
If system goes to sleep during a run of playwright, then various errors happen.

Add any other details about the problem here.
Similar issue (https://github.com/puppeteer/puppeteer/issues/5463) and gist (https://gist.github.com/VikramTiwari/8aea5e523a4380a5bfd28fe12ebcf64d) for puppeteer

**Comment by dgozman** [comment]
If both processes run on the same computer, perhaps you could use `browserType.launch()` instead?

**Comment by pavelfeldman** [comment]
Closing this as out of scope for now.
