### ISSUE TITLE
[Question] Is page.locator used for html element existence check ?

### ISSUE THREAD

**Issue by suchcodemuchwow** [microsoft/playwright#11452]
I have a usecase which might or might not have "remove" button. Historically I was using page.$(selector) to check existence of element and then I was using click method on ElementHandle return value. I have been trying to adopt Locator api but as far as I see in order to check element existence I need to explicitly give timeout value(or wait 30 sec) and catch the error. As far as I see from Locator apis documentation there is no existence check for Locator api which made me think, we need to use Locator only if we are sure that element is gonna be attached to dom at some point and have explicit error handling. 

```javascript
// Earlier
const removeButton = await page.$(selector);
if (removeButton) {
  await removeButton.click();
}
// Now
const removeButton = page.locator(selector);
try {
  await removeButton.click({ timeout: 0 });
} catch (e) {}
```

**Comment by mxschmitt** [comment]
You can do something like that:

```ts
import { Locator } from '@playwright/test';

const locatorExists = async (locator: Locator) => (await locator.waitFor({ timeout: 5000 }).catch((e: Error) => e)) instanceof Error;
const exists = await locatorExists(page.locator('foo'));
```

This will wait a maximum of 5 seconds to the locator element to appear on the page. If it does appear it resolves, but since it's not an error it's false. If it's not on the page it throws a timeout error, which is an instance of an error and by that true.
