### ISSUE TITLE
[Question] Intercept test execution before start.

### ISSUE THREAD

**Issue by emarf** [microsoft/playwright#11454]
Good afternoon. When i execute my tests, i get results(for example 2 failed and 2 passed). I save results of this tests in .json and after this i need to execute only failed tests. Can i read file with test results(sync or async) and after that reject tests that passed before and execute only failed?Maybe i can do it in custom reporter?

**Comment by creage** [comment]
@emarf Playwright Test can do that for you already. Please check [Test retires](https://playwright.dev/docs/test-retries).

**Comment by emarf** [comment]
@creage Maybe i do something wrong, but `retries` only execute failed tests depending of value. i need to execute bunch of tests, get all information and when i execute bunch of tests again, need to filter and execute only failed tests with help of previous test information

**Comment by emarf** [comment]
I need to intercept process of starting tests and pass the necessary information there (which tests to run)

**Comment by mxschmitt** [comment]
Folding into #10500
