### ISSUE TITLE
[BUG] getComputedStyle doesn't return shorthand property value in Firefox

### ISSUE THREAD

**Issue by zhelvis** [microsoft/playwright#11460]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Windows
- Node.js version: 16.13.2
- Browser: Firefox

**Code Snippet**

```javascript
const { test, expect } = require("@playwright/test");

test("Get computed style shorthand property", async ({ page }) => {
  await page.goto("https://example.org");

  const bodyLocator = page.locator("body");

  // returns "" in firefox
  const margin = await bodyLocator.evaluate((body) => {
    return window.getComputedStyle(body).margin;
  });

  expect(margin).toBe("0px");
});

```

**Describe the bug**

This bug is reproduced only with the patched firefox instance. In original browser `getComputedStyle` works with shorthand `margin` property as expected.

Repo with reproduction of this bug:
https://github.com/zhelvis/playwright-computed-style-bug

**Comment by mxschmitt** [comment]
I verified that this is fixed once https://github.com/microsoft/playwright/pull/11459 is merged. This was most likely a bug in firefox 95.0 or the revision which we picked since we don't modify this part of the browser.

**Comment by mxschmitt** [comment]
Closing since this is fixed in our tip-of-tree version. You can use `npm install @playwright/test@next` for the beta version until it reached stable.

**Comment by zhelvis** [comment]
Yes, the bug is reproduced in firefox version 95.0. The update solved the problem. Thanks a lot!
