### ISSUE TITLE
[Feature] Command to export _single_ trace as a html bundle (outside of HTML Report)

### ISSUE THREAD

**Issue by neil-morrison44** [microsoft/playwright#11475]
Related to **but distinct from** https://github.com/microsoft/playwright/issues/4967

We can't use Playwright Test since our tests are written as [cucumber](https://cucumber.io/) scripts, with Playwright providing the browser integration layer. The runner will change but I imagine this set up is approximately the same for everyone who started using Playwright prior to Playwright Test.

When there's a failure on a PR and I want to check the trace with the current set up, as I understand it, I'd need to:
- Find the right trace file (in my build artefacts or similar)
- Download the trace file
- Either: use https://trace.playwright.dev/ to view the trace, or the command line tools

Ideally I'd want to:
- Click a link my workflow has added to the PR, see the trace (it's uploaded to S3 or similar)

The volume of tests we have in the current style prevents us from moving to Playwright Test (it looks nice though), but we'd still like this part of the functionality.

---

As a "nice to have" on top of it - building a HTML bundle for a _collection_ of traces then allowing selection via URL param / an index page would be *very* nice.

**Comment by mxschmitt** [comment]
What you can do is specify the trace file URL inside the URL, for example like this:

`https://trace.playwright.dev/?trace=https://demo.playwright.dev/reports/todomvc/data/cb0fa77ebd9487a5c899f3ae65a7ffdbac681182.zip`

this then points to your storage bucket where you have uploaded the file from your CI run. Would that work for you?

**Comment by neil-morrison44** [comment]
Sounds like there's the potential for some CORS issues with that, but assuming that can be worked out then yeah I think that would give me what I'm looking for

**Comment by mxschmitt** [comment]
Yup, your web-site / storage server needs to allow external CORS access. 

Closing then and we'll follow-up with adding this to the docs in #11505.
