### ISSUE TITLE
[Docs] Custom matchers type declarations

### ISSUE THREAD

**Issue by xWiiLLz** [microsoft/playwright#11482]
**Context:**
The documentation for custom matchers is missing a declaration for types to work properly.

The [docs states](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend) to add the following code for Typescript usage:
```ts
// global.d.ts
declare namespace PlaywrightTest {
  interface Matchers<R> {
    toBeWithinRange(a: number, b: number): R;
  }
}
```

However, it seems to me that a `declare global` is required for this to work (tested in my Typescript repo):
```ts
// global.d.ts
declare global {
  declare namespace PlaywrightTest {
    interface Matchers<R> {
      toBeWithinRange(a: number, b: number): R;
    }
  }
}
```

**Comment by pavelfeldman** [comment]
We are slow on this because we are still thinking if we want to commit to supporting jest expect's extensions. Probably best to update the docs for now.
