### ISSUE TITLE
[Question] Config variable instead of ConfigFile?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#11480]
Hi! I'd like to know if there is a solution to a problem I've been struggling with for a long time.

I'm trying to build a client-server application capable of programmaticaly running Playwright tests. This cause not to use CLI commands to run them. Moreover, since all the tests I run depend on parameters (strings, integers etc...) that I can change whenever I want from the playwright.config.ts file, now I realized that I need to "transform" this config file into a variable that I'd like to set on the server side.
I read a lot of the code behind the scenes (loaders, workers etc...) inside the node_modules folder, and what I realized is that all the test runs depend upon the existance of this config file from which take all the settings of the case. Is there a possibility to set all the info contained in this file inside an object variable that I can pass to the "loader object" without modifying the inner library? 

Thank you for your attention, if you have question I can explain better my situation of course :)

**Comment by mxschmitt** [comment]
What kind of parameters are these? Usually if these are environment specific parameters or secrets they get passed as environment variables. If they are more feature rich, we recommend something like `node getData.js && npx playwright test` (and you write and read a json file) or you do your data fetching inside `beforeAll` / a [worker fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures).

**Comment by DvDream** [comment]
> What kind of parameters are these? Usually if these are environment specific parameters or secrets they get passed as environment variables. If they are more feature rich, we recommend something like `node getData.js && npx playwright test` (and you write and read a json file) or you do your data fetching inside `beforeAll` / a [worker fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures).

For example:

```
import { PlaywrightTestConfig } from '@playwright/test';

const config : PlaywrightTestConfig = {
    testDir: './',
    //globalSetup: './login.ts',
    testMatch: 'test.ts',
    timeout: 120000,
    projects: [        
        {
            name: 'Chromium-webservice',
            use:{ 
                    baseURL: 'https://website.com/signin',
                    channel: 'chromium',
                    param1: 'param1',
                    param2: 'param2',
                    param3: 'param3',
                    // etc.....
```

and I would use them in a test in this way:


```
test('test', async({page, param1, param2, param3}) => {

    await page.click(selector);
    await page.fill(`selector, `${param2}`);
    await page.click(`selector:has-text("${param1}")`);

   // stuff ....

    expect(page.locator(`selector:has-text("${param3}")`)).toBeVisible();
})
```

they are just parameters that I set in the config and that in case I can change without modifying all the tests.
The fact is that I would like to be able not to depend on the playwright.config.ts file to do that, instead on a variable which resemble it and that I can modify whenever I want, without going inside each test to modify stuff. 
Anyway I did not quite undestand "how to do your data fetching inside beforeAll / a worker fixture" for my case. 
Hope I made myself clearer now :)

**Comment by mxschmitt** [comment]
This looks like you want this: https://playwright.dev/docs/test-parameterize#parameterized-projects

"how to do your data fetching inside beforeAll / a worker fixture" with that I meant that sometimes people want to fetch data e.g. from a data base or an external source. But that seems not the case in your example.

**Comment by DvDream** [comment]
> This looks like you want this: https://playwright.dev/docs/test-parameterize#parameterized-projects
> 
> "how to do your data fetching inside beforeAll / a worker fixture" with that I meant that sometimes people want to fetch data e.g. from a data base or an external source. But that seems not the case in your example.

Yes I've already read this guide page, But it seems like then I need to include them also in the config file like in https://playwright.dev/docs/test-parameterize#:~:text=Now%2C%20we%20can%20run%20tests%20in%20multiple%20configurations%20by%20using%20projects.

if I understood well.
If there was the possibility to omit those parameters from the config file, it could be useful. I need to check maybe

**Comment by mxschmitt** [comment]
You can also read them off a JSON file inside if that works for you better. It's very flexible, since its just Node.js which gets executed.

Seems like you are interested in #7275.

**Comment by DvDream** [comment]
And how would I pass this read JSON file to Playwright?

**Comment by mxschmitt** [comment]
Since it's Node.js you can read it either via `const yourInput = require("./foo.json")` or `const yourInput = JSON.parse(fs.readFileSync("input.json"))`.

Closing then since all questions seem answered and it's quite related to #7275.
