### ISSUE TITLE
[Feature] page.waitForXPath

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#1149]
By a quick scan of API docs, I see that currently there's a way to do this for selector but nothing for xpath. Maybe selector one works for xpath as well. If not, could we also make sure that other related xpath based methods are also present. Mainly `page.$x`.

**Comment by arjun27** [comment]
xpath is a [built-in selector](https://github.com/microsoft/playwright/blob/master/docs/selectors.md#xpath), and will work with `waitForSelector` and other methods that accept a selector

**Comment by VikramTiwari** [comment]
Fantastic! Thanks!
