### ISSUE TITLE
[Question] How to select vue component's data property

### ISSUE THREAD

**Issue by AbhimanyuAryan** [microsoft/playwright#11495]
I have a slider element QSlider which has `data` -> `model` equal to 8. I have selected the component using 
```
sliders = page.query_selector_all("_vue=QSlider")
sliders[0]
```

but not sure how can I get `model` value and modify it. Would appreciate any kind of help thanks 

<img width="555" alt="Screenshot 2022-01-20 at 3 25 26 AM" src="https://user-images.githubusercontent.com/8083613/150220448-692823e2-3d77-4e18-a4b9-5024600cd7d8.png">

**Comment by AbhimanyuAryan** [comment]
sorry for tagging you @aslushnikov but the Vue selector section wasn't very clear. I saw you have lot of VueJS contribution thought you might be the best person to help :)

**Comment by protozoo** [comment]
Extendig @AbhimanyuAryan 's question:
The goal here is to be able to have access to a DOM element to check some of its properties. Analogous to doing something like this:

```
function checkVueElementProperty(){
  let expectedValue = 55;
  let myVueEnabledDOMElement = document.getElementById( "myComponentX" );
  let elementVueInstance = myVueEnabledDOMElement.__vue__;
  let checkedPropertyValue = elementVueInstance.counter;
  return checkedPropertyValue == expectedValue;
}
```

So, in summary, how to get "direct" access to a DOM element and then to its JS properties.
This isn't necessarily restricted to Vue cases, although in our case we are interested in testing Vue components internal state.

Thanks!

**Comment by AbhimanyuAryan** [comment]
@mxschmitt is this feature not available in `v1.18`? I see you added `v1.19` tag

**Comment by aslushnikov** [comment]
> The goal here is to be able to have access to a DOM element to check some of its properties. Analogous to doing something like this:

@protozoo You can do this already using [`locator.evaluate`](https://playwright.dev/docs/api/class-locator#locator-evaluate):

```js
const handle = page.locator(`_vue=QSlider`);
const isGood = await handle.evaluate(myVueEnabledDOMElement => {
  let elementVueInstance = myVueEnabledDOMElement.__vue__;
  let checkedPropertyValue = elementVueInstance.counter;
  return checkedPropertyValue == expectedValue;
});
```

As far as I understand, this should address your needs!

**Comment by AbhimanyuAryan** [comment]
@mxschmitt what do you think is the python analogous of this example? I'm confused with this javascript arrow function.

**Comment by AbhimanyuAryan** [comment]
Ok so basically you can wrap js functions inside `evaluate`. If there's a better way let me know. Thanks a lot for all the help :) 

```python
  value = aslider.evaluate("""myVueEnabledDOMElement => {
    let elementVueInstance = myVueEnabledDOMElement.__vue__;
    let checkedPropertyValue = elementVueInstance.counter;
    return checkedPropertyValue == 5;
  }""")
```

**Comment by protozoo** [comment]
> > The goal here is to be able to have access to a DOM element to check some of its properties. Analogous to doing something like this:
> 
> @protozoo You can do this already using [`locator.evaluate`](https://playwright.dev/docs/api/class-locator#locator-evaluate):
> 
> ```js
> const handle = page.locator(`_vue=QSlider`);
> const isGood = await handle.evaluate(myVueEnabledDOMElement => {
>   let elementVueInstance = myVueEnabledDOMElement.__vue__;
>   let checkedPropertyValue = elementVueInstance.counter;
>   return checkedPropertyValue == expectedValue;
> });
> ```
> 
> As far as I understand, this should address your needs!

We'll try that, thank you!

**Comment by aslushnikov** [comment]
Awesome! Closing this then. Feel free to file another issue if things don't work!
