### ISSUE TITLE
[Question] How to find child vue components

### ISSUE THREAD

**Issue by AbhimanyuAryan** [microsoft/playwright#11496]
I want to access QSelect's child element QMenu. I using _vue selector to find JSHandle for Select 

```selects = page.query_selector_all("_vue=QSelect")```

<img width="584" alt="QItem" src="https://user-images.githubusercontent.com/8083613/150225416-03c17a4c-5372-4c8c-be72-10ab56ce2bc5.png">

**Comment by AbhimanyuAryan** [comment]
@aslushnikov can you please help with this. I saw you have vue pull requests :)

**Comment by mxschmitt** [comment]
Something like this should work: `_vue=QSelect >> _vue=QMenu`. What do you want to achieve?

**Comment by AbhimanyuAryan** [comment]
@mxschmitt I basically want to test `vue components`. Loop though list of elements see the changes rendered. Also get `data values` of components as mentioned here: https://github.com/microsoft/playwright/issues/11495

Thanks for quick reply

**Comment by AbhimanyuAryan** [comment]
@mxschmitt these are Quasar components: https://quasar.dev/vue-components/select#qselect-api

**Comment by mxschmitt** [comment]
You can use Locators and loop through them see here: https://playwright.dev/docs/locators#lists

I'm closing this issue, since it seems answered, lets continue in the other issue for further questions.

**Comment by AbhimanyuAryan** [comment]
sure thanks @mxschmitt 😍
