### ISSUE TITLE
[BUG]geolocation is not working

### ISSUE THREAD

**Issue by allgrowsm** [microsoft/playwright#11503]
**Describe the bug**
- I am trying to set geolocation, but, it always points to China even I change the different geolocation.

Here is my program.
```javascript
          const context = await browser['chromium'].newContext({
            geolocation: { latitude: 35.60472, longitude:140.12333,accuracy :1},
              permissions: ['geolocation']
          });
```

Chrome version: 939194
Playwright: 1.17.2

Here is screen shot.

![image](https://user-images.githubusercontent.com/19646090/150313525-9227b6da-37c2-45f0-92dd-e6256db70447.png)

Do you have any suggestion for this?

regards,

**Comment by mxschmitt** [comment]
Google does get your geolocation as they say by your IP address. If you want to change that you need to use e.g. a proxy.

The geolocation emulation does only emulate the gelocation APIs, which are used in e.g. Google Maps.

**Comment by allgrowsm** [comment]
@mxschmitt 
Thanks for your comment.
The  server in not in China.
That is in Japan.

Then, why it says in China?

Also, previous version of playwright could change the geolocation.

See here.
![image](https://user-images.githubusercontent.com/19646090/150327709-31ba40af-53cd-4faa-bbec-dc9561ebb1b1.png)

Could you explain why this is happening?

Regards,

**Comment by mxschmitt** [comment]
Then maybe Google has changed how they determine it. As I said, Playwright does only emulate Geolocation APIs, websites often use IP based geolocation tracking as well, e.g. Netflix.

**Comment by msaus** [comment]
@mxschmitt 
But, why it points to China even the server is in Japan?
I am just curious...

**Comment by mxschmitt** [comment]
Ask Google :)

**Comment by msaus** [comment]
@mxschmitt 
Well...I will try to use old chromium.

**Comment by msaus** [comment]
@mxschmitt 
Finally, I found the issue.
incognito mode dose not change the geolocation.
So, I just click on update geolocation in the bottom.
Thanks.
