### ISSUE TITLE
[Question] Type method mixing up order of word

### ISSUE THREAD

**Issue by aw1875** [microsoft/playwright#11519]
It seems like the `type` method is mixing up the order of the word I'm asking it to type. Am I doing something wrong? My code looks like this:

```javascript
await page.goto(loginURL, { waitUntil: "networkidle" });
await page.type(selectors.get("username"), "aw1875", { strict: true })
```
For whatever reason its typing in 5aw187 rather than aw1875 and I'm not sure why. I've been using playwright for testing for a while now and never had this issue so I'm super confused.

Edit: `selectors` is a map containing all the selectors for the items on the page I'm testing. There is no issue with playwright getting the correct selector using this method.

**Comment by mxschmitt** [comment]
Maybe a bug inside the state handling of the application? Try `await page.fill(selectors.get("username"), "aw1875", { strict: true })` instead which is made for input elements.

**Comment by aw1875** [comment]
@mxschmitt Thought I tried this and it wasn't working also but I just tried again and it seems to work perfectly. Appreciate the help!
