### ISSUE TITLE
[BUG] Locator Timeout not overriding Playwright Config 

### ISSUE THREAD

**Issue by tallyw00d** [microsoft/playwright#11528]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Linux
- Node.js version: 12.22.2,
- Browser: Chromium
- Extra: Headless Remote Linux Version 

**Code Snippet**
Playwright Config File Looks like:
`const config: PlaywrightTestConfig = {
	testDir: './integration-test',

	/* Maximum time one test can run for. */
	timeout: 30 * 1000,

	expect: {
		/**
		 * Maximum time expect() should wait for the condition to be met.
		 * For example in `await expect(locator).toHaveText();`
		 */
		timeout: 5000,
	},`

`const notebookRunning = page.locator('[data-integration-tests="notebook-state-Running"]');
await notebookRunning.waitFor( { timeout: 300000 } );`

The bug:

The Timeout I have in my locator.waitFor is not overriding my config file.   As a result the test is timing out in 30 seconds when I need a waitFor of about 5 minutes. 

```Timeout of 30000ms exceeded.

    locator.waitFor: Target closed
    =========================== logs ===========================
    waiting for selector "[data-integration-tests="notebook-state-Running"]" to be visible
    ============================================================

      84 |
      85 |              const notebookRunning = page.locator('[data-integration-tests="notebook-state-Running"]');
    > 86 |              await notebookRunning.waitFor( { timeout: 300000 } ); // milliseconds * seconds * minutes)
```

**Comment by mxschmitt** [comment]
Would it be possible that you create a small github repo so we can run it ourselves?  Otherwise too many pieces seem missing.
