### ISSUE TITLE
[BUG] Locator.locator ignores intermediate matches

### ISSUE THREAD

**Issue by zyulyaev** [microsoft/playwright#11522]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Mac
- Node.js version: v16.13.1
- Browser: All

**Code Snippet**

In this example I want to find a row by its content, and then find another element within this row:

```typescript
import { v4 as uuid } from 'uuid'
import { beforeEach, createMeeting, describe, expect, test } from '../helpers'

describe('Meetings', () => {
  beforeEach(async ({ signIn }) => {
    await signIn()
  })

  test('should be able to delete a meeting', async ({ page }) => {
    const meetingName = await createMeeting()

    await page.goto('/meetings')
    const row = page.locator(`*role=row >> text=${meetingName}`)
    await row.locator('label=/menu/i').click()
    await row.locator('*[role=menuitem] >> text=delete').click()
    await expect(row).toBeHidden()
  })
})
```

**Describe the bug**

API documentation states that `locator` method finds an element matching specified selector in the `Locator`'s **subtree**, which is not true in case you use intermediate matches. So if you have the following selector `*A >> B`, and if you then apply another selector `C` using `locator` method, you end up having `*A >> B >> C` instead of `(*A >> B) >> C`.

**Comment by GPITRTD** [comment]
I have the same issue on my application. Why is this not picked up? There are a lot of web applications with tables etc.

**Comment by dgozman** [comment]
The workaround for now is to not use `*` in the parent locator. For example, use ```page.locator(`role=row`, { hasText: meetingName })``` instead of ```page.locator(`*role=row >> text=${meetingName}`)```.

**Comment by GPITRTD** [comment]
> The workaround for now is to not use `*` in the parent locator. For example, use `` page.locator(`role=row`, { hasText: meetingName }) `` instead of `` page.locator(`*role=row >> text=${meetingName}`) ``.

Thanks for the tip!

**Comment by aaltat** [comment]
I think I have the same problem, when I am trying to move from elementsHandles to locators. When my test page looks like this:
```html
<html lang="en">
<head>
</head>
<body>
<button> 
    <h3>namegoeshere</h3>
    <p>42</p>
    <p>24</p>
</button>
</body>
</html>
```
When writing test with using elementhandles, it looks like this:
```typescript
test('test with elements', async ({ page }) => {
  await page.goto('file:///Users/tatuaalto/workspace/tmp/static.html');
  const button_element = await page.$('*xpath=//button >> text="namegoeshere"');
  const p_element = await button_element.$('xpath=//p[1]');
  const text1 = await p_element.innerText();
  console.log(text1); 
});
```
Then in the console I see `42`, which is what I did expect. But when I am trying to convert same test to use locators: 
```typescript
test('test with locators', async ({ page }) => {
  await page.goto('file:///Users/tatuaalto/workspace/tmp/static.html');
  const button_locator = await page.locator('*xpath=//button >> text="namegoeshere"');
  const p_locator = await button_locator.locator('xpath=//p[1]');
  console.log(await p_locator.allTextContents());
  console.log(await p_locator.allInnerTexts());
  console.log(await p_locator.textContent());
});
```
Then in the console I see:
```
[]
[]


  1) tests/example.spec.ts:11:1 › test with locators ===============================================

    Timeout of 30000ms exceeded.

    Pending operations:
      - locator.textContent at tests/example.spec.ts:17:31

    locator.textContent: Target closed
    =========================== logs ===========================
    waiting for selector "*xpath=//button >> text="namegoeshere" >> xpath=//p[1]"
    ============================================================

      15 |   console.log(await p_locator.allTextContents());
      16 |   console.log(await p_locator.allInnerTexts());
    > 17 |   console.log(await p_locator.textContent());
         |                               ^
      18 | });
```
Which is not what I did expect. I did, at least one of the methods, to return me the text content of the `p` element which has text 42.

**Comment by dgozman** [comment]
As a workaround, avoid `*` in the locator for now:

```js
const button_locator = await page.locator('*xpath=//button >> text="namegoeshere"');
// Replace with:
const button_locator = await page.locator('xpath=//button', { hasText: 'namegoeshere' });
```

**Comment by aaltat** [comment]
That you for the proposal, but unfortunately that does not work for me, at least yet. Because I am one of the maintainers of Robot Framework [Browser library](https://github.com/MarketSquare/robotframework-browser) which exposes playwright API as high level keywords. But currently we do not yet support `hasText` when selecting elements. We are somewhat lacing behind in features. But this looks like prime candidate to start thinking how to support `hasText`. 

But in any case, this looks like a bug and it would be nice to get the Intermediate matches on selectors working.

**Comment by GP-QA** [comment]
Hi @dgozman, the provided workaround with hasText doesn't work if you need to check the text of multiple columns of a table, since you can only use this once. It would be nice if this bug is picked up on the next version of Playwright.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
