### ISSUE TITLE
[Feature] We request a feature for getting recording result automatically.

### ISSUE THREAD

**Issue by 970263611** [microsoft/playwright#11538]
Our enviroment:
    electron: 16.0.7
    nodejs: 16.0
    playwright:1.18.0
Our purpose: We planned to build an automatic testing tool with electron and playwright.
Our question is: 
    1.We invoked electronApplication with eletron render process using the sample that playwright provided. The recording result was not saved to the foleder that we selected after pressing the record button. 
    2.The feature that we need is that we could control the entire recording processes by our code without the recording frame provided by playwright within eletron render process. 
    We want to know wheather the we haven't use it in the right way or playwright doesn't provided these features. 
    Looking forward to your reply!
    Thank you！

**Comment by mxschmitt** [comment]
what do you want to record, save and which record button do you mean?

**Comment by 970263611** [comment]
thanks for your reply.
We want to record the clicks on the page. For now if we want to call out the recording window through codegen, we need to click the record button on the upper left corner of the window to start recording. After recording the click operations and generate the codes, we need to copy the codes by ourselves. With python version we can specified the location where the generated files are stored through playwright command: codegen -o. But the js version does not have such a function. We need this function and we also need to read this file and repeat the user's operation through the electron rendering process. We have not found a supported api for this function for now. Do you have any suggestions? 
And there is another question, which is the playwright command codegen -o can only invoke the browser, is there any way to invoke an electron application?
Thanks a lot for your time.

**Comment by mxschmitt** [comment]
Playwright codegen is currently not made to re-use it by external processes in form of an API. Playwright for Node.js allows you to set an output file, see this example:

```
npx playwright codegen --output foo.js --target javascript
```

By default Playwright codegen does not work with Electron, since it does not install it by default. What you could do is leverage the custom setup via page.pause() see here: https://playwright.dev/docs/cli#codegen-with-custom-setup

**Comment by xujizhong** [comment]
我也遇到了相同的问题，请问你这个问题解决了吗？
