### ISSUE TITLE
[Feature] HTML report bottom margin is too narrow (almost 0)

### ISSUE THREAD

**Issue by TimeInvestor** [microsoft/playwright#11533]
I am using Playwright v.18.0.

The HTML report generated with bottom margin is almost 0.

![image](https://user-images.githubusercontent.com/4818798/150450435-81c85de3-46ac-4bc8-bffd-b676426d4de3.png)

Please help add some botton margin.

**Comment by NaincyKumariKnoldus** [comment]
Hey @TimeInvestor Can I do this please?

**Comment by Nav-2d** [comment]
Which browser and OS are you using? I see `20px` padding-bottom on Windows (Chrome)

**Comment by NaincyKumariKnoldus** [comment]
> Which browser and OS are you using? I see `20px` padding-bottom on Windows (Chrome)

using ubuntu linux and chrome.

**Comment by TimeInvestor** [comment]
> Hey @TimeInvestor Can I do this please?

Yes. Go ahead.

**Comment by TimeInvestor** [comment]
> Hey @TimeInvestor Can I do this please?

Yes. Go ahead.

**Comment by TimeInvestor** [comment]
> Which browser and OS are you using? I see `20px` padding-bottom on Windows (Chrome)

I am using Windows 10.
Browser for viewing the report is Edge. Same for Chrome.
