### ISSUE TITLE
[Feature] Introduce beforestep and afterstep

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/playwright#11543]
We have to automate the testcases which are not independent.

1) Login
2) Order Creation
3) Order Checking
4) Order Editing
5) Order Deleting
All these testcase execution status should get updated in Jira.

As we have to capture status for each case and also when using POM we can use the extend feature to initialize pages, so we have created individual tests works with different pages. But the problem is, the page instance will not carry forward to next test. That's the playwright test architecture. If page instance is preserved then there's no problem. Because we are updating testcase status in jira using aftereach.

To overcome this we are using test.step as we can use the same page instance across different steps. But there's no afterstep method to update execution status in jira. As an alternative we have used custom reporter onstepend. But there's is a defect in it and I just raised.

In these kind off scenarios where the testcases are dependent but not required to execute dependent functionality again, we must have to preserve page instance for next tests. This is not working in serial tests as well.

If there's no plan to provide single page instance across one describe block, then better to introduce before and after step which will be helpful to many.

**Comment by qtpsudhakar** [comment]
Cypress is having similar kind of feature to preserve page instance for next tests
beforeEach(() => {
  // Preserve cookie in every test
  Cypress.Cookies.defaults({
    preserve: (cookie) => {
      return true;
    }
  })
});

**Comment by mxschmitt** [comment]
Playwright has a serial mode re-use page example, which will re-use the page instance. This enables you to leverage afterEach for your custom reporting logic: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests

But since reporting already mentions reporting, it might make sense to more post-process that rather than doing it during the runtime. This means that a custom reporter might be a better place for such a logic.

**Comment by qtpsudhakar** [comment]
This reuse page example is similar to all other test frameworks. But playwright gives a great advantage in form of extending test. That's a very good feature where page instances can be passed to tests directly. Below is the sample

//BaseTest.ts

import { test as baseTest } from '@playwright/test';
import { BasePage } from '../pages/BasePage';
import { HomePage } from '../pages/HomePage';
import { LoginPage } from '../pages/LoginPage';

const test = baseTest.extend<{
    loginPage: LoginPage;
    basePage: BasePage;
    homePage: HomePage;
}>({
    loginPage: async ({ page }, use) => {
        await use(new LoginPage(page));
    },
    basePage: async ({ page }, use) => {
        await use(new BasePage(page));
    },
    homePage: async ({ page }, use) => {
        await use(new HomePage(page));
    }

});

export default test;

'******************************
'using page instances in test
'******************************

// test.ts
import test from '../lib/BaseTest';
import data from "./../data/smoke.json"

test('login Test', async ({basePage, loginPage }) => {
	await basePage.navigateToApplication()
        await loginPage.loginToApplication();
});

This type page initialization is not possible in serial mode. But continuing execution with same page instance is not possible here. Again in new test open browser, login and create order. That's like repetitive.

There's a big advantage with playwright-test and POM pattern. But the advantage becomes useless in this situation. I understand that you think about individual tests. But you should also think about testcases vs end to end scenarios.

**Comment by aslushnikov** [comment]
> If there's no plan to provide single page instance across one describe block, then better to introduce before and after step which will be helpful to many.

@qtpsudhakar you can do like this:

```js
// example.spec.ts

import { test, Page } from '@playwright/test';

test.describe.serial('use the same page', () => {
  let page: Page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
  });

  test.afterAll(async () => {
    await page.close();
  });

  test.beforeEach(async ({  }) => {
    // update jira status
  });

  test('runs first', async () => {
    await page.goto('https://playwright.dev/');
  });

  test('runs second', async () => {
    await page.click('text=Get Started');
  });
});
```

**Comment by qtpsudhakar** [comment]
I know this. This technique is available in all frameworks. But my point is we cannot use text.extend feature here.

**Comment by aslushnikov** [comment]
That's right, but there are no plans to support it for now. Let's wait for more demand for this feature.
