### ISSUE TITLE
[Feature] Option to run every test per project, rather then all tests per project

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#11557]
Currently, having multiple browsers(projects), and multiple tests - Playwright Test executes **all of tests** per **browser**.

This gives us an overview of our product stability per browser.

What we'd like to have - is an ability to test a feature per browser.

We want to run every test per browser, so we can focus on a particular test/feature, if it fails.

This will help us to avoid situation when we have

* **100** tests and **3** browsers
* and the test `t1` is failing on the browser `b3` - leading us to
* wait for **100** (browser `b1` - **all** green) + **100** (browser `b2` -  **all** green) + **1** (browser `b3` - `t1` test fails) tests to run 

rather then 

* test `t1` on browser `b1` - *pass*
* test `t1` on browser `b2`  - *pass*
* test `t1` on browser `b3`  - **FAIL**

The feedback in the second approach is much faster.

I don't want to run the rest of tests since my product is not stable enough - period.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
