### ISSUE TITLE
[Feature] Add support for JavaScript functional/composition/fluent selector syntax

### ISSUE THREAD

**Issue by CharlieDigital** [microsoft/playwright#11554]
At current, Playwright's selectors are string based.  

This has several downsides from a usability perspective.

- It is less ergonomic to use
- The functionality is less discoverable when coding (fine when using `codegen`)
- It is easier to make mistakes when writing, tuning, or refactoring selectors in code

For example, in Playwright, one might write the following activity:

```js
await page.click('button:right-of(:text("Email Address"))');
```

Taiko, as an example, does this differently:

```js
await click(button(toRightOf("Email Address")));
```

*See the Taiko docs for more examples: https://docs.taiko.dev/api/reference/*

By using JavaScript functional selector composition (or alternative), it streamlines the authoring experience when working directly in code as there are dev-time hints (docs, intellisense, missing parens, etc.).

A solution may be to simply generate a subset of the string based selectors using a functional/fluent syntax.

**Comment by creage** [comment]
ehm...
```js
function async click(selector) {
    return page.click(selector);
}

function button(selector) {
    return `button:${selector}`;
}

function toRightOf(selector) {
    return `right-of(:text("${selector}"))`);
}

await click(button(toRightOf("Email Address")));
```
?

**Comment by CharlieDigital** [comment]
@creage yes, exactly this, but it would be great as part of the library itself rather than reinventing the wheel.  I think it would make adoption easier as well.

**Comment by creage** [comment]
It is not about reinventing the wheel, rather adapting a tool to your personal needs...

You can copy that code to your repo an use it right away 😄

**Comment by CharlieDigital** [comment]
Of course, but I think that it's utility and the model chosen by the Taiko team significantly improves the DX for new developers and those that are not working with the `codegen` that a more complete implementation should be considered as a core part of Playwright.

**Comment by creage** [comment]
Well, I definitely got your point, but I'm still not convinced enough to implement every API every single developer finds useful, as a part of core API.

PW has great options to extend it with any API you might require - you can just go with it.

How about releasing a Taiko adapter to Playwright?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
