### ISSUE TITLE
[Question] Does Playwright have built-in reporter when using with .Net?

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11561]
I am using Playwright with .Net and running tests with xUnit. Does Playwright offer any built in reporter for my situation or do I need to go with 3rd party libraries?

**Comment by mxschmitt** [comment]
There are no official reporter's for xunit available.

Also xunit is not recommended see here: https://playwright.dev/dotnet/docs/test-runners#xunit-support

If you want to write tests in . net, we recommend nunit.

**Comment by awrightCADGS** [comment]
Hi mxschmitt, I found this old thread when searching for the same question. You said Playwright .NET has no official reporters for XUnit. Does it have an official reporter for NUnit, or should we use a third party reporter?
