### ISSUE TITLE
[BUG] npx playwright install-deps fails as npx not available to sudo

### ISSUE THREAD

**Issue by SteveALee** [microsoft/playwright#11567]
**Context:**
- Playwright Version: current
- Operating System: ubuntu 20.04.3 on WSL (windows 11 version)
- Node.js version: [e.g. 12.22, 14.6] 16.13.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] n/a
- Extra: [any specific details about your environment] pretty much standard WSL Ubuntu - though been on my machine a long time

In a new empty folder I did:
- npm init playwright (chose default false for os deps install)
- npx playwright test
- sudo npx playwright install-deps

get `sudo: npx: command not found`

Which seems reasonable given node/npm not ever used via sudo

What should be done?

**Comment by SteveALee** [comment]
PS lastest node install will have been via nvm - is that what is not compatible with your instructions?

**Comment by SteveALee** [comment]
hmm, works perfectly WITHOUT the sudo!

Installs a tonne of stuff though :(

**Comment by mxschmitt** [comment]
This depends on your environment and seems like npx is not correctly installed for your root user. Setting the right ports might help. It's expected that install-deps will install a lot of dependencies, since browsers have a lot of dependencies.

Closing since the npx problem is not a Playwright issue.

**Comment by SteveALee** [comment]
@mxschmitt OK, bu I can't thinking you are making invalid assumptions about how npx is always installed. Why should it be installed for the sudo user on all systems?
