### ISSUE TITLE
[Question] Does Playwright have built-in parallel running feature with .Net?

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11562]
I am using Playwright with .Net and xUnit. In this case, does Playwright offer any built-in parallel execution capability or do I rely on whichever test runner (xUnit) I am using to set up my tests to run in parallel?

**Comment by mxschmitt** [comment]
Xunit is not recommended since their parallel strategy does not match well with whats needed with Playwright. See here for explanation: https://playwright.dev/dotnet/docs/test-runners#xunit-support

Nunit is what's officially recommended which also includes a nunit binding.

**Comment by p10344646** [comment]
https://playwright.dev/dotnet/docs/test-runners#running-tests-in-parallel now (2025-07-03) has examples for MSTest, NUnit & XUnit.
XUnit appears to have the following recommendation:

> We recommend xUnit 2.8+ which uses the [conservative parallelism algorithm](https://xunit.net/docs/running-tests-in-parallel.html#algorithms) by default.
