### ISSUE TITLE
[BUG] page.keyboard.press('Backspace') behaves differently in WebKit.

### ISSUE THREAD

**Issue by fserb** [microsoft/playwright#11571]
**Context:**
- Playwright Version: 1.18.0
- Operating System: macOS 12.1
- Node.js version: 17.4.0
- Browser: WebKit

**Code Snippet**

```js
page.keyboard.press('Backspace');
```

In Chromium and Firefox, this behaves as expected (as if the user is pressing backspace on the page) and gets captured by `keydown`/`keyup` events.

In WebKit it navigates back to `about:blank`. This depends on which site I use to goto(). My site has handlers for both keydown and keyup with `preventDefault` and `stopPropagation`.

```javascript
import {test, expect} from '@playwright/test';

test('backspace', async ({page}) => {
  await page.goto("https://mysite");
  await page.keyboard.press('Backspace');
  await.page.pause();
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
