### ISSUE TITLE
[REGRESSION]: page.goto worked fine on 1.8, times out on 1.17

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#11570]
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?] 1.8
- BAD Playwright Version: [what Playwright version doesn't work any more?] 1.17
- Operating System: [e.g. Windows, Linux or Mac] Linux
- Extra: [any specific details about your environment] playwright docker image

**Code Snippet**

My code does

```js
    await page.goto('http://127.0.0.1:3001/docs/index.html#/');
```

and it was working until I updated. I'm not sure what the root cause is, maybe it isn't page.goto's issue, but that's how I encounter it.

**Describe the bug**

On 1.8, this work fine. on 1.17, it times out.

**Comment by mxschmitt** [comment]
Would it be possible that you provide us a repro for this (localhost web-server)? Otherwise we can't act on that.

**Comment by aslushnikov** [comment]
Please re-file with a good repro!

**Comment by trusktr** [comment]
We're moving too fast. Someone updated playwright in our project and even moved from jest-playwright to playwright's official test runner. I'll just close since there's no repro, and we'll move along with that latest setup.

**Comment by mxschmitt** [comment]
> We're moving too fast. Someone updated playwright in our project and even moved from jest-playwright to playwright's official test runner. Good to close, and we'll move along with that latest setup.

AMAZING! 🎉
