### ISSUE TITLE
[BUG] Page.FillAsync().Wait() not working as expected

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11586]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Windows
- Node.js version: v14.17.4
- Browser: Chromium
- Extra: using Playwright with .Net

**Code Snippet**

```
signInWindow.FillAsync(OktaUserName, UserName).Wait();
signInWindow.WaitForTimeoutAsync(1000);
signInWindow.FillAsync(OktaPassword, Password).Wait();

```

**Describe the bug**

Here is the scenario:
1. I navigate to home page url
2. It automatically pops up a login window (okta)
3. Login credentials are entered in login window in the order of username first and then password

In the above code, `signInWindow` is type `IPage` referencing the login window. When I run my tests in the headless mode, for some reason, it intermittently enters Password to the Username field by adding it at the end of the Username and this causes the login window giving an error. I noticed this by taking the screenshot (attached below). 
It continues to happen intermittently even though I added 1 second timeout in between, when indeed `Page.FillAsync().Wait()` should be taking care of the wait issue. (Fails once out of every 4-5 runs). If I don't put the wait it fails even more frequently.

![image](https://user-images.githubusercontent.com/84137824/150736652-a5dc6e1f-0a66-4334-9f8f-33442d28a1b7.png)

Is this a bug or is there some other dynamic wait I have to use? How do I ensure mouse switches over to the password field after the username is filled? Tests are passing fine when I run it with `headless : false`

**Comment by aslushnikov** [comment]
@davidhprotective First thing first, why's there no `.Wait()` in the end of your `signInWindow.WaitForTimeoutAsync(1000);`? 

> Is this a bug or is there some other dynamic wait I have to use?

Hard to say! Would you mind share a script or snippet that we can run locally to investigate?

**Comment by davidhprotective** [comment]
I can put .Wait() but my question is more about why do we need to use a WaitForTimeOutAsync() since Page.FillAsync() should have auto wait. Or am I wrong here? Do I have to use some other explicit wait?

Unfortunately I can't share a script since it involves our company internal application and this doesn't fail all the time, especially with the wait it fails about once in every 4-5 runs.

**Comment by aslushnikov** [comment]
@davidhprotective out of curiosity, does your login page use react?

**Comment by aslushnikov** [comment]
I'll close this for now. Next time, please file an issue with a good repro that we can run locally and debug it!
