### ISSUE TITLE
[Question] If it possible to take a screenshot with full browser window (including address bar)?

### ISSUE THREAD

**Issue by rimus** [microsoft/playwright#11589]
Hi everyone,

So, we have the parameter `fullPage` for taking a screenshot with a full scrollable page.

Do we have some similar parameter for capturing a page with full browser view especially including address bar?

Thank you in advance.

**Comment by mxschmitt** [comment]
Something like this is not possible, since a screenshot only reflects the rendered DOM. The URL part is not part of that and on e.g. headless not available.
