### ISSUE TITLE
[Feature] `addInitScript` context option in `playwright.config.ts`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11585]
i'm trying to work around https://github.com/microsoft/playwright/issues/7008#issuecomment-927175899 as that solution no longer works, so i'm trying an init script instead:
```ts
test('test', async ({ page, context }) => {
    await context.addInitScript(() => window._playwrightResume())
    await page.goto('https://google.com/')
})
```
this doesn't work, i assume because the `page` was created before the `context` was given the init script.

this works however, but it's not ideal because it creates a new `Page` when `@playwright/test` has already created one

```ts
test('test', async ({ context }) => {
    await context.addInitScript(() => window._playwrightResume())
    const page = await context.newPage()
    await page.goto('https://google.com/')
})
```

**Comment by aslushnikov** [comment]
@DetachHead you can always [override default `page` fixture](https://playwright.dev/docs/test-fixtures#overriding-fixtures) with your implementation. Would it work?

**Comment by DetachHead** [comment]
yeah that works thanks, though i believe it's still creating two `page` objects when it only needs one, but that's not the end of the world

**Comment by aslushnikov** [comment]
> yeah that works thanks, though i believe it's still creating two page objects when it only needs one, but that's not the end of the world

@DetachHead Why does it create two pages?

**Comment by DetachHead** [comment]
```ts
export const test = base.extend({
  page: async ({ context, page /*old page*/ }, use) => {
    await context.addInitScript(() => window._playwrightResume())
    const newPage = await context.newPage()
    await use(newPage)
  }
})
```

**Comment by aslushnikov** [comment]
well, this does not override the `page` fixture. You can do so that the `page /* old page */` is actually your page with a proper init script. Check out the [docs I referred to](https://playwright.dev/docs/test-fixtures#overriding-fixtures) – this way you'll have only one page created for your needs.

**Comment by DetachHead** [comment]
are you referring the `storageState` example? does that not still create two `storageState`s?

```ts
import { test as base } from '@playwright/test';

export const test = base.extend({
  storageState: async ({ storageState /*the original unused one */ }, use) => {
    const cookie = await getAuthCookie();
    await use({ cookies: [cookie] }); //the newly created one
  },
});
```

as i said i don't consider it a big deal either way, just trying to understand how exactly this functionality works

**Comment by aslushnikov** [comment]
Nah, so I mean something like this:

```js
// example.spec.ts
import { test as base, expect } from '@playwright/test';

const test = base.extend({
  // override `context` fixture to add init script
  context: async ({ context }, use) => {
    await context.addInitScript(() => window._playwrightResume())
    await use(context);
  },
});

test('my test', async ({ page }) => {
  // `page` will be created off the context, so it'll be initialized
  await page.goto('https://example.com');
});
```
