### ISSUE TITLE
[Feature] Able to set retries on a spec/test level (test.use)

### ISSUE THREAD

**Issue by MartinP-Autopilot** [microsoft/playwright#11584]
We currently have our "API only" tests running in the same pipeline as the GUI based tests.  We run with `--retries=1` in the CLI.  However, although it might make sense to do a retry for a GUI based test (as the UI might be a bit slow in the first try), it does not make sense for "API only" tests.

We _could_ split the tests up into different pipelines, but it would be better to just declare `test.use({retries:0})` in each "API only" spec.

**Comment by pavelfeldman** [comment]
Folding into #10825
