### ISSUE TITLE
Config file for executing tests on real android device

### ISSUE THREAD

**Issue by kevanous** [microsoft/playwright#11583]
What would I need in a config file to be able to execute a spec file on a real android device? I am hoping that I can execute a spec file in an emulator via an emulator config file and also execute that same exact spec file in a real android device (via ADB and USB connection) via an android config file. I already have the emulator config file but I have no idea how to set up a config file for the real android device execution. I see the examples on the playwright documentation website are for spec files which are set up for only real android device execution. But I do not want to have separate spec files for running tests in an emulator and another set of spec files for android devices. Is this even possible?

**Comment by aslushnikov** [comment]
@kevanous you need to [create a new fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture) (e.g. called `androidContext`) that follows steps [from our android documentation](https://playwright.dev/docs/api/class-android). After that, you'll be able to open pages there and run tests.

**Comment by kevanous** [comment]
@aslushnikov Thank you for the advice and I am now attempting to do that since, in our project, we do not use any fixture. We just use the config file to control the general setup. Please forgive my lack of understanding, but wouldn't using a fixture limit a spec file to always use that particular fixture? Would this mean that I can not use the same spec file for a physical android test and an emulator test? Any sample to get me going on the right path would be hugely appreciated!

**Comment by aslushnikov** [comment]
> Please forgive my lack of understanding, but wouldn't using a fixture limit a spec file to always use that particular fixture?

@kevanous nah, it'll be only used if you use it in your test. You're free to use any combination of fixtures in any of your tests. See https://playwright.dev/docs/intro#using-test-fixtures

**Comment by aslushnikov** [comment]
I'll close this for now. Feel free to file a new issue as questions arise!
