### ISSUE TITLE
Open new tab in same window for Webkit

### ISSUE THREAD

**Issue by anils92** [microsoft/playwright#11595]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Windows
- Node.js version: 16.13.1
- Browser: WebKit

**Describe the bug**
When a user tries to perform a "ctrl + click" on a link or open a link/URL in a new tab, playwright WebKit opens that link in the same tab instead of opening a new tab. It creates a problem for crossbrowser testing.

It is also visible in attached screenshot that there is no option for new tab.
![Playwright](https://user-images.githubusercontent.com/98236911/150832795-467a7625-547e-4c04-9511-19abd1645944.JPG)

**Comment by aslushnikov** [comment]
Cmd-Click doesn't work as well for me. @yury-s, could you please take a look?

**Comment by yury-s** [comment]
This is a known issue and we have tests documenting this: https://github.com/microsoft/playwright/blob/e10cb4a619ca8975b25af97f6162b2ced196299f/tests/browsercontext-page-event.spec.ts#L160-L189 Having said that we can probably fix it in wk.
