### ISSUE TITLE
[BUG] page/interception.spec.ts fails in Chromium since r960211

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#11593]
Failing test: page/interception.spec.ts:108:1 › should intercept network activity from worker 2.
Range: https://chromium.googlesource.com/chromium/src/+log/812012f22436491447bf6a2c0d1a5a50a8593cf9..c8900237101eff877c5eee2c1b17928c7f1abab9
Related patch: https://chromium.googlesource.com/chromium/src/+/c8900237101eff877c5eee2c1b17928c7f1abab9

**Comment by dgozman** [comment]
See #10048 for previous breakage.

**Comment by aslushnikov** [comment]
Looks like new roll should fix this.
