### ISSUE TITLE
[BUG] page.type types on focused area

### ISSUE THREAD

**Issue by qtpsudhakar** [microsoft/playwright#11590]
**Context:**
- Playwright Version: 1.18
- Operating System: Windows
- Node.js version: 16.x
- Browser: Chromium
**Code Snippet**
await page.type("//div[@class='CodeMirror-lines']", "data");

It should type text on the located element. But it types on the focused area.
I had to add await page.click("//div[@class='CodeMirror-lines']"); before the type statement to make it work.

The element what I am working on is not input. It's div element. Another point is it's there in the page but not in visible area. It auto scroll to element on clicking.

**Comment by pavelfeldman** [comment]
That is how CodeMirror works. It has hidden input behind the scenes that it uses to understand what is types. If you want to simulate user with CodeMirror, you should use clicks and page.keyboard.

**Comment by qtpsudhakar** [comment]
Then what is the role of selector in that step. If it failed to type text, the step should fail. Instead it is entering text on focused area. Please think from tester angle. It's a false pass step.
