### ISSUE TITLE
[Question]trace analysis生成 case

### ISSUE THREAD

**Issue by wangzhatian** [microsoft/playwright#11608]
Hello, I would like to edit the ourselves recorded use case twice.  
The plan is to parse the trace.zip generated by ourselves show-trace, obtaining page information, API information, and further generating test cases.  
But NOW I don't know what the trace.zip parsing rule is. Can you help me

**Comment by aslushnikov** [comment]
@wangzhatian The internal structure of `trace.zip` is not documented - there are no guarantees it will be consistent from release to release. You can reverse-engineer it, but you'll have to maintain this code every time the format changes.

Overall, I'd recommend against this approach!

**Comment by wangzhatian** [comment]
Is there any other way to reconvert recorded scripts into test cases
