### ISSUE TITLE
[BUG] Unable to install chrome on Amazon Linux

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/playwright#11615]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Amazon Linux
- Node.js version: 14.18.2
- Browser: Chrome
- Extra: AWS Amplify

**Code Snippet**
amplify.yml
```
npx playwright install chrome
npx playwright test --config=tests/playwright.config.ts
```

**Bug**
When I execute these commands on Amazon Linux, I get the following errors in the console:

```
[WARNING]: 2022-01-25 16:16:25 (253 MB/s) - ‘google-chrome-stable_current_amd64.deb’ saved [90862320/90862320]
[WARNING]: + apt-get install -y ./google-chrome-stable_current_amd64.deb
[WARNING]: /codebuild/output/src200775475/src/adventure5-liveops/node_modules/playwright-core/bin/reinstall_chrome_stable_linux.sh: line 30: apt-get: command not found
[INFO]: Failed to install browsers
                                 Error: Failed to install chrome
[ERROR]: !!! Test execution failed, one or more tests are not passing
```

**Comment by aslushnikov** [comment]
Yes, Amazon Linux is not officially supported; we only download browser channels on Ubuntu right now.

**Comment by anastasiyamazheika** [comment]
Hey @aslushnikov, thanks for the update. Is there any plan to support it?

**Comment by aslushnikov** [comment]
No plans to support it yet! If you'd like us to consider, feel free to file a feature request. If it accumulates enough traction, we'll do it!

**Comment by KevinGhadyani-Okta** [comment]
Unless I'm not understanding, doesn't Playwright work with Chrome Headless? Is this request different from that?
