### ISSUE TITLE
[BUG] Tests can't find Chrome in Playwright 1.18 when Chrome is installed manually

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/playwright#11616]
**Context:**
- Playwright Version: 1.18
- Operating System: Amazon Linux
- Node.js version: 14.18.2
- Browser: Chrome
- Extra: AWS Amplify

**Describe the bug**

As I can't install chrome with Playwright command (described in this bug https://github.com/microsoft/playwright/issues/11615) I was installing Chrome manually with the following script:

```
wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
yum install -y ./google-chrome-stable_current_*.rpm
```

And I execute tests with the following command: 
`npx playwright test --config=tests/playwright.config.ts
`

Today I decided to upgrade from **1.17.1** to **1.18** version and my tests started failing with the following error:

`browserType.launch: Chromium distribution 'chrome' is not found at /opt/google/chrome/chrome`

Once I roll back to **1.17.1** everything starts working again.

**Comment by aslushnikov** [comment]
@anastasiyamazheika Interesting! I don't recall any changes in this part. Let me try to reproduce.

**Comment by aslushnikov** [comment]
@@anastasiyamazheika I tried inside the AmazonLinux docker container, but it works for me.

Could you help me with a docker image that would repro this?

**Comment by anastasiyamazheika** [comment]
Hello @aslushnikov we use amazonlinux:2

**Comment by aslushnikov** [comment]
@anastasiyamazheika The following works for me:

```
$ docker run --platform linux/amd64 --rm -it amazonlinux:2 /bin/bash
$ yum install -y wget tar
$ wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
$ yum install -y ./google-chrome-stable_current_*.rpm
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
$ . ~/.nvm/nvm.sh
$ nvm install node
$ cd /root
$ npm init -y
$ npm i @playwright/test
$ cat <<EOF>a.mjs
> import {chromium} from '@playwright/test';
> const browser = await chromium.launch({channel: 'chrome'});
> await browser.close();
> EOF
$ node a.mjs
```

Could you please try it as well?

**Comment by mxschmitt** [comment]
Closing since this is stale. Please create a new issue if you still encounter this!
