### ISSUE TITLE
[Question] Does Playwright have support WCAG 2.0 testing?

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11621]
While using with .Net, does Playwright have built-in support for Web Accessibility Testing (WCAG 2.0)? Or is there a 3rd party library that Playwright works well with?

**Comment by aslushnikov** [comment]
@davidhprotective you can get AX information right from the browser using Playwright's AX api's: https://playwright.dev/dotnet/docs/api/class-accessibility
