### ISSUE TITLE
[Question] Should launched webservers close after auto viewing html report?

### ISSUE THREAD

**Issue by Relequestual** [microsoft/playwright#11647]
I'm new to playwright, so just getting started, but I seem to have run into an issue, and I don't know if it's a bug or not.

I'm running the first test provided by the auto setup tool and as per the getting started guide, checking the title.

This fails (as expected) on my app because the title is different.

I have set in the config for a web server to start, which works as expected.

However, when a test fails and an HTML report is created, which automatically opens... when closing the report, and ending the test process as instructed, it doesn't tear down the web server it spun up. This blocks the port, and so the tests cannot be re-run.

As a work around, I've set the html reporter to never open, as I can open it manually if required.

Is this expected behaviour or an oversight?
I'd have expected that when the report is generated, the web server would be shut down, unless `reuseExistingServer` is set.

I had to manually kill the node processes for the server to free up the port.

**Comment by aslushnikov** [comment]
@Relequestual I can repro!
