### ISSUE TITLE
[BUG]”connect_over_cdp“ accept_downloads option defaults to Flase.can't be downloaded

### ISSUE THREAD

**Issue by liuyazhou1991** [microsoft/playwright#11649]
**Context:**
- Playwright Version:1.18.1
- Operating System: Windows
- Browser:  Chromium
- Python version: 3.7 x86

**Code Snippet**

```py
from playwright.sync_api import sync_playwright

def run(playwright):

    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")
    page = browser.contexts[0].pages[0]
    page.goto("https://www.python.org/downloads/release/python-3102/")
    page.click('//*[@id="content"]/div/section/article/table/tbody/tr[5]/td[1]/a')
    page.close()

with sync_playwright() as playwright:
    run(playwright)
```
**Describe the bug**

it can't be downloaded

**Comment by aslushnikov** [comment]
You should create a page with an `accept_downloads` option:
https://playwright.dev/python/docs/api/class-browser#browser-new-page-option-accept-downloads

**Comment by liuyazhou1991** [comment]
@aslushnikov Thank you for your advice.Sorry, there is a section of my code that is not wrong, but it is.
‘’‘
from playwright.sync_api import sync_playwright

def run(playwright):

    browser = playwright.chromium.connect_over_cdp("http://localhost:9222")
    page = browser.contexts[0].pages[0]
    page.goto("https://www.python.org/downloads/release/python-3102/")
    page.click('//*[@id="content"]/div/section/article/table/tbody/tr[5]/td[1]/a')
    page.close()

with sync_playwright() as playwright:
    run(playwright)
’‘’

 "Accept_downloads" can be defined for the new context and page. However, I can't create a new page because I can't log in and fast debugging. I can only receive the existing page downloads. Before version 1.18.1, I thought I couldn't do it. I saw the release notes of version 1.18, in which "accept_downloads option now defaults to true.", I think it should be possible to no longer define accept_ Downloads, in fact, needs to be defined.

**Comment by pavelfeldman** [comment]
You can't affect the accept_downloads option from the client side, your server needs to allow downloads because they are landing on the server side. So this change did not relate to the CDP operation.

**Comment by liuyazhou1991** [comment]
> You can't affect the accept_downloads option from the client side, your server needs to allow downloads because they are landing on the server side. So this change did not relate to the CDP operation.

When I was debugging, I found that before using "playwright.chromium.connect_over_cdp('http://localhost:9222')", the browser has the download function. When you manually click the link, you can download the file. Once you run "playwright.chromium.connect_over_cdp('http://localhost:9222')", you can manually click the link to refresh the web page but will not download the file. The browser has no download function. I think "connect_over_cdp" makes the browser lose the download function. I can't use "connect_over_cdp" because I can't download. If I don't use "connect_over_cdp", I can't log in to the system.
