### ISSUE TITLE
[BUG] - Weird behaviour in window blur event

### ISSUE THREAD

**Issue by FROD-Neotys** [microsoft/playwright#11645]
**Context:**
- Playwright Version: Java 1.17.2
- Operating System: Windows
- Node.js version: [e.g. 12.22, 14.6]
- Browser: All
- Extra: 

**Describe the bug**

1. I'm using _context.exposeFunction("someFunctionName", callback)_ on the Java side. 
1. On my opened page, I call that function inside a blur event listener : _window.addEventListener("blur", (e) => someFunctionName())_

Someway, the blur event is never triggered when I click outside the browser **until** I open the DevTools. After that, the blur event is triggered as expected each time I click outside the browser, even when I close the DevTools afterwards.

I fail to see how these two relate, and would expect my blur events to be triggered independently of that first opening of the DevTools.

Probably linked to that, trying to evaluate _document.hasFocus()_ showed the same behaviour, returning always true until the DevTools are opened. Then it alternates true and false as expected when I click inside or outside the browser.

What do you think?

**Comment by aslushnikov** [comment]
@FROD-Neotys all the pages consider themselves "focused" all the time. This is because pages in background get all kinds of bad treatment by browsers: their timers are throttled, RAFs deprioritized e.t.c.

The reason this changes with DevTools being opened is because DevTools reset this emulation.

Can you share your use case? What kind of testing do you do?

**Comment by aslushnikov** [comment]
I'll close this for now. Please feel free to re-file with a use case and referring to this issue!

**Comment by sandeepdroid** [comment]
@aslushnikov 
I am also facing this issue for one my cases.

**Case**: In it the page does some work when the page "goes out of focus/hidden" (when the event `blur`/`visibilitychange` etc is triggered). 

From what I understood by your explanation, seems it is not possible to do this the usual way.
Is there any other way to do the same, may be like trigger the event directly from playwright to simulate it.
