### ISSUE TITLE
[Question] When creating a new Page in beforeAll to share between tests, how to get the correct recording behaviour

### ISSUE THREAD

**Issue by patroza** [microsoft/playwright#11644]
Relevant playwright config settings
```json
    video: "retain-on-failure",
    screenshot: "only-on-failure",
```

These settings however don't apply to new pages I create:
```ts
  let page
  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage()
  })
  test.afterAll(async () => {
    await page.close()
  })
```

how to get the same behaviour?

**Comment by aslushnikov** [comment]
@patroza videos don't record and that's a known limitation; screenshots should work though! Don't they for you?

**Comment by ltsuda** [comment]
@aslushnikov do you think is the same case solved here https://github.com/microsoft/playwright/issues/10980#issuecomment-996282890 ?

As the video doesn't record on `beforeAll` when setting the playwright.config, maybe @patroza could create a new context there with the `recordVideo` option.

**Comment by aslushnikov** [comment]
> do you think is the same case solved here #10980 (comment) 

@ltsuda Might or might not be! Hard to say without further clarifications.

**Comment by aslushnikov** [comment]
To sum up, the expected behavior is:
- video recording is not supported in the global page pattern
- screenshots are supported in the global page pattern

I'll close this for now. Please feel free to re-file if things don't work for you!

**Comment by afarooqs** [comment]
Would love to see this implemented.
