### ISSUE TITLE
[Feature] Support Amazon Linux

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/playwright#11640]
Hello, 
Right now Playwright doesn't support Amazon Linux - https://github.com/microsoft/playwright/issues/11615. It could be nice to support it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by kyle-uc** [comment]
definitely also want this

**Comment by tchiaspko** [comment]
Could we keep the issue open to collect more votes? Otherwise the votes are scatter as new issue is open and then closed due to insufficient interest.

**Comment by jenvareto** [comment]
@pavelfeldman would you consider reopening this? I started using playwright recently and I definitely would like Amazon Linux support. A closed issue implies that this suggestion has been rejected and dissuade people who want Amazon Linux support from voting.

**Comment by BagchiMB** [comment]
@yury-s any plans of picking this up? Also why is this issue closed? 😭😭
