### ISSUE TITLE
Using alias in tsconfig.json for paths causes "Could not resolve" error when executing tests the first time. No error shows up after that!

### ISSUE THREAD

**Issue by kevanous** [microsoft/playwright#11656]
**Context:**
- Playwright Version: 1.18
- Operating System: Mac
- Node.js version: v14.15.5
- Browser: All
- Extra: using alias for imports via paths in tsconfig

**Code Snippet**
```javascript

# tsconfig.json file
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "paths": {
      "@page-objects/*": ["qe/page-objects/*"],
      "@utils/*": ["qe/utils/*"]
    },
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "module": "es2020",
    "moduleResolution": "node",
    "importHelpers": true,
    "target": "es2015",
    "typeRoots": ["node_modules/@types"],
    "lib": ["es2018", "dom"]
  }
}

# header-validation.spec.ts file
import { test, expect } from "@playwright/test";
import { Products } from "@page-objects/products";

let productsPage: Products;

test.describe.parallel.only("Create New Person", () => {
  test.use({
    storageState: "./qe/session-storage/standard-user-credentials.json",
  });

  test.beforeEach(async ({ page }) => {
    productsPage = new Products(page);
    await productsPage.goto();
  });

  test("Page header is as expected", async () => {
    await expect(productsPage.header).toHaveText("Products");
  });
});
```

**Describe the bug**

When using the alias with version 1.18(as based on release notes: "Playwright Test now respects tsconfig.json's baseUrl and paths, so you can use aliases") it works as expected but the first run gives an error saying "Could not resolve ....." but interestingly the tests do get executed properly like there was no error. And even more interestingly, the second and any subsequent execution will not have that error message ever again. Not a problem in local execution but in pipeline, it will result in stage failing even if all tests passed and there it will be liking running first time every time.

**Comment by aslushnikov** [comment]
This is already fixed on tip-of-tree and the fix will be released in 1.18.1!
