### ISSUE TITLE
[BUG] selector tool in the inspector window doesn't work when execution is paused on a breakpoint

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11668]
**Context:**
## System:
 - OS: Windows 10 10.0.18363
 - Memory: 862.73 MB / 15.78 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

**Code Snippet:**
```ts
test('test', async ({ page }) => {
  await page.goto('https://google.com')
  await page.pause()
  await page.click('foo')
})
```
**Describe the bug**

1. set a breakpoint in your code as well as a `page.pause()`, eg:
   ![image](https://user-images.githubusercontent.com/57028336/151279135-4da58c96-beaf-45f0-a11d-fa2d72fa6b28.png)
2. run a test in debug mode (so the inspector appears) `playwright test --debug`
3. when it hits the `page.pause()`, attempt to use the selector explorer (it works)
4. resume the execution until it hits the breakpoint
5. attempt to use the selector explorer again (it doesn't work)

**Comment by DetachHead** [comment]
this is probably caused by the the same issue as https://github.com/microsoft/playwright/issues/10897#issuecomment-994182694, however i believe this is a much higher priority as it renders debugging playwright scripts using breakpoints pretty much useless.

if it helps, a workaround to this limitation could be to move the element inspector to a chrome extension or something such that you can use it within the browser independently of the playwright code running in nodejs.

**Comment by pavelfeldman** [comment]
If you use the VS Code extension, moving cursor to the selector will highlight it. There is no need to use inspector now if you are using VSCode. I've heard that webstorm extension is also going to be fixed to allow this. See https://github.com/microsoft/playwright-vscode.

**Comment by DetachHead** [comment]
@pavelfeldman this doesn't work when you're using a language other than js/ts (eg. python), or when you aren't using `@playwright/test` (ie. only using the playwright library).
