### ISSUE TITLE
[Feature] browser API mocks

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#11670]
In some cases (e.g. #7339, #11580, #11288) the clients may want to call into experimental browser APIs which normally don't instrument until they become standard and supported by all browser vendors. In cases like that where Playwright doesn't provide dedicated testing API out of the box the clients would benefit from a mechanism that allows adding javascript stubs for such APIs and mocking them.

**Comment by judofyr** [comment]
Interesting. Would these mocks actually be able to support the real functionality (i.e. accessing the host file system)?
