### ISSUE TITLE
[Feature]: css selector pseudoclass that works like `innerText`

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11673]
re-raising #7978
### Feature request

the current pseudoclasses for matching text, from my understanding, do the following:
- `:has-text` - matches every node which contains the specified text
- `:text` - matches the lowest node which contains the specified text
- `:text-is` - matches the lowest node with the exact specified text

what i want is a pseudoclass that works like the `innerText` method on element handles, which would allow you to match every node with exact text

additionally, the names of these pseudoclasses and the documentation doesn't really make it clear how they behave. the existence of `:has-text` and `:text-is` makes the behaviour of `:text` a complete mystery that isn't really explained in the docs

### use case
when attempting to select checkboxes that don't have an attached label or any other reliable identifying elements, the only reliable way to identify them consistently is to first identify the **highest element** with the given innertext, then identify the checkbox within said element:
![image](https://user-images.githubusercontent.com/57028336/151285871-a08f2fed-2527-45cd-9b57-a5f1ecf80e59.png)

doing so seems to be impossible with the current selectors:
- `:has-text` - will match every element up the tree
- `:text` - only matches the lowest element, not including the checkbox & can cause false because it's not a full match
- `:text-matches` - only matches the lowest element, not including the checkbox
- `:text-is` - only matches the lowest element, not including the checkbox

therefore i have to fallback to using xpath, meanning i cannot use features like regex:
```xpath
//*[.='foo']//div[@role='checkbox']
```

**Comment by aslushnikov** [comment]
>  identify the highest element with the given innertext, then identify the checkbox within said element:

@DetachHead technically this would always be `html` element

> doing so seems to be impossible with the current selectors:

How about using [layout selectors](https://playwright.dev/docs/selectors#selecting-elements-based-on-layout)?

```
input:left-of(:text("foo"))
```

**Comment by DetachHead** [comment]
> @DetachHead technically this would always be `html` element

sorry i meant the highest element with the given **exact** innertext. for example, given the following html:
```html
<html>
    <div id="1">
        <label>foo</label>
    </div>
    <div id="2">
        <label>bar</label>
    </div>
</html>
```
in this case, the "highest element" with the exact innertext "foo" is the `div id="1"`. any higher elements will make the innertext "foobar", preventing them from matching this hypothetical "innertext" selector

**Comment by dgozman** [comment]
@DetachHead I think you can use the `:text-matches` for this.

```js
// This locator will select an element that has exactly "foo" combined text inside.
// In the example above, that's <label>foo</label>
page.locator(`:text-matches("^foo$")`)

// This locator will select a <div> containing the element from previous selector.
// In the example above, that's <div id=1>
page.locator(`div:has( :text-matches("^foo$") )`)
```

Let me know when this does not work. Overall, we'd like to keep the number of selectors small to avoid confusion. Documentation could definitely be improved though 😄

**Comment by DetachHead** [comment]
unfortunately that still matches every ancestor div, because they all have the element with the exact innertext "foo" in them, but those ancestors themselves do not have the exact innertext "foo".

to make my example more convoluted (and more like the site i'm testing), hopefully this makes it more clear:
```html
<html>
<div> <!--- incorrectly matches (innertext is "foobar") --->
    <div> <!--- incorrectly matches (innertext is "foobar") --->
        <div> <!--- correctly matches (innertext is "foo")  --->
            <div> <!--- matches (innertext is "foo", though this doesn't matter because the match above is the element i'm looking for) --->
                <div> <!--- matches, same as above --->
                    <label>foo</label>
                </div>
            </div>
            <input type='checkbox'/>
        </div>
        <div>
            <div>
                <label>bar</label>
            </div>
            <input type='checkbox'/>
        </div>
    </div>
</div>
</html>
```

in this case i want to select a checkbox based on the label next to it, but there's no guarantee how many divs nested both the checkbox or its label are, which is why matching the highest element with the exact innertext "foo" is useful

**Comment by yury-s** [comment]
> unfortunately that still matches every ancestor div, because they all have the element with the exact innertext "foo" in them, but those ancestors themselves do not have the exact innertext "foo".

You can restrict it to direct parents only:
```js
// This will only match div which has label as its child
page.locator(`div:has( > :text-matches("^foo$"))`)
```

Does this solve your problem?

> i want to select a checkbox based on the label next to it

Note that you can pass selector of a `<label>` and in most cases Playwright will automatically retarget click/fill etc actions to the associated input element.

**Comment by DetachHead** [comment]
> You can restrict it to direct parents only:
> 
> ```js
> // This will only match div which has label as its child
> page.locator(`div:has( > :text-matches("^foo$"))`)
> ```
> 
> Does this solve your problem?

that still only gets the parent, but not the highest ancestor with that exact innertext. in my example, it would select this div:
![image](https://user-images.githubusercontent.com/57028336/152460502-bc19e477-e601-431d-8e48-1f5288909a8f.png)

which i can't use to get the associated checkbox (which may or may not be further up or down the tree). basically i'm trying to make a selector as generic as possible, because the application i'm testing has many different kinds of inputs with a completely arbitrary path between them and their labels

> Note that you can pass selector of a `<label>` and in most cases Playwright will automatically retarget click/fill etc actions to the associated input element.

most of the time they don't have a `for` attribute or aren't even `label`s. would this work in those cases?

-----------------

here is a more in depth example:
```html
<div>
    <div>
        <div>
            <div>foo</div>
        </div>
    </div>
    <input type='checkbox'>
</div>
<div>
    <div>
        <div>
            <div>bar</div>
        </div>
        <input type='checkbox'>
    </div>
</div>
<div>
    <div>
        <div>
            <div>
                <div>baz</div>
            </div>
            <div>
                <div>
                    <div><input type='checkbox'></div>
                </div>
            </div>
            <div>
            </div>
            <div>
                <div>
                    <div>
                        <div>
                            <div><input type='checkbox'></div>
                        </div>
                    </div>
                    <div>
                        <div>qux</div>
                    </div>
                    <div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```
i need a selector that can replace the xpath in this function, it needs to work on all of those checkboxes
```ts
async function setCheckbox(label: string) {
  await page.click(`xpath=//*[normalize-space(.)='${label}']//input[type='checkbox']`)
}
```

ideally so that i can use regex to select one (eg. `setCheckbox(/fo.*/)`, which isn't possible with xpath)

**Comment by yury-s** [comment]
> which i can't use to get the associated checkbox (which may or may not be further up or down the tree)

The following selector will match an input in immediate sibling div of the label's ancestor div:
```js
page.locator(`div:has(label:text-matches("foo")) + div input`)
```
You can construct [a list](https://playwright.dev/docs/selectors#css-selector-list) of selectors to cover more cases that you have in the example.

> most of the time they don't have a for attribute or aren't even labels. would this work in those cases?

No.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
