### ISSUE TITLE
[BUG] Firefox networkIdle gets stuck on NS_BINDING_ABORTED requests

### ISSUE THREAD

**Issue by ThaDaVos** [microsoft/playwright#11677]
**Context:**
- Playwright Version: [what Playwright version do you use?] playwright@1.18.0
- Operating System: [e.g. Windows, Linux or Mac] WSL 2 Ubuntu 18.04.06 LTS
- Node.js version: [e.g. 12.22, 14.6] v16.13.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Firefox
- Extra: [any specific details about your environment]

## System:
 - OS: Linux 5.10 Ubuntu 18.04.6 LTS (Bionic Beaver)
 - Memory: 16.96 GB / 23.48 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/n/bin/node
 - Yarn: 1.22.15 - ~/n/bin/yarn
 - npm: 8.1.4 - ~/n/bin/npm
## Languages:
 - Bash: 4.4.20 - /bin/bash
## npmPackages:
 - playwright: ^1.18.0 => 1.18.0

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext(); // We're using this as we need a clean page each time
  const page = await context.newPage();
  await page.goto('http://haskerkroon.nl', { waitUntil: 'networkidle', timeout: 60 * 1000 }); // This one times out as there are NS_BINDING_ABORTED requests
  // ...
})();
```

**Describe the bug**
If a requests answers with `NS_BINDING_ABORTED` it seems it's not handled correctly and the page just stalls until timeout - as this error isn't preventable as it can be caused by many reasons - one cannot handle them easily

Add any other details about the problem here.
I tried the following gist script instead of networkIdle - I enabled debug and saw the `NS_BINDING_ABORTED` requests while running the browser non-headless to be the ones it keeps on waiting - if networkIdle does the same, than it's logical the site gets stuck:
https://gist.github.com/dgozman/d1c46f966eb9854ee1fe24960b603b28

**Comment by aslushnikov** [comment]
Oh wait, I cannot reproduce this with the following snippet.

```js
// a.mjs
import {firefox} from '@playwright/test';

const browser = await firefox.launch();
const context = await browser.newContext();
const page = await context.newPage();
await page.goto('http://haskerkroon.nl', { waitUntil: 'networkidle', timeout: 60 * 1000 }); 
await browser.close();
```

I'm loading from United States though; where are you located?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
