### ISSUE TITLE
[Question] Is there a way of capturing browser console logs

### ISSUE THREAD

**Issue by YudhistarN** [microsoft/playwright#11682]
Hi,
I am using Playwright with .Net for automating tests of our web application. When a failure occurs, we are currently capturing screenshot and video. But these are not sufficient to debug an issue. So, good to have the browser console logs also captured (if any errors, warnings). Playwright documentation indicates such flexibility for node.js (https://playwright.dev/docs/api/class-logger) but not for .Net. Any inputs is much appreciated.

**Comment by unlikelyzero** [comment]
@YudhistarN it is possible with https://playwright.dev/dotnet/docs/api/class-page#page-event-console
