### ISSUE TITLE
[Issue] page.click() don't work correctly in chromium

### ISSUE THREAD

**Issue by SydAnderson** [microsoft/playwright#11684]
Context: 
playwright: 1.16.3
OS: Windows 10
Typescript

HTML: 
```html
<div class="account_buttons">
        <a href="https://automationstore.onlineweb.shop" data-lang="true">Back to Store</a>
        <a href="javascript:void();" data-lang="true" onclick="javascript:LogOut();">Log Out</a>
</div>
```
I need click  the first <a> (Back to Store) 

My code work correctly in firefox, webkit, mobile webkit, but in chromium don't working. 

I try diffrent methods, but ever fails in chromium only.

TS Code:
```ts
await page.locator('//div[@class="account_buttons"]/a[contains(@href,"https://automationstore.onlineweb.shop")]').click()
await page.click('//div[@class="account_buttons"]/a[contains(@href,"https://automationstore.onlineweb.shop")]');
await page.locator('a:has-text("Back to Store")').click
```

The only way it worked was when I added an sleep before click the tag -> await page.waitForTimeout(3000);
I try use the waitFor method, but it doesn't work either.

Again, this work corrrectly in other browsers.
I don't know what is going on.

**Comment by aslushnikov** [comment]
Hey @SydAnderson,

There's not enough information to see what's going on. What we need is a repro that we can run locally that reproduces the issue, so that we can debug it. Would you be able to share this?

**Comment by SydAnderson** [comment]
hey @aslushnikov thx for response. now I add the information you need.

the page I use is a dummy page for automation. I create a user that you can use. It is in the code. 

**index.spec.ts**

`import { test, expect } from '@playwright/test';

test('basic WishList', async ({ page }) => {

  await page.goto('https://automationstore.onlineweb.shop/');
  await page.click('#account');

  //login
  await page.fill('#account_login_register_email', 'test-git@example.com');
  await page.fill('#account_login_register_login_password', 'test1234');
  await page.click('#account_login_register_button_login');

  //goto Home -> press button Back to Store with Xpath
  // only work if add this line before clicking -> await page.waitForTimeout(2000);
  await page.click('//div[@class="account_buttons"]/a[contains(@href,"https://automationstore.onlineweb.shop")]');
  
  //fill search with "tomato"
  await page.fill('#txtQuickSearch', 'tomatoes');
  await page.locator('//button[@aria-label="search"]').click();
`

**playwright.config.ts**

`
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
use:{
    baseURL: "https://automationstore.onlineweb.shop/",
    },
projects: [
    {
        name: 'chromium',
        use: { 
            ...devices['Desktop Chrome'],
            video: 'retain-on-failure' 
            }
    },
    {
        name: 'firefox',
        use: { ...devices['Desktop Firefox'] },
    },
    {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
    }
    ]

}

export default config;
`

the part of HTML I need clicking

`<div class="account_buttons">
        <a href="https://automationstore.onlineweb.shop" data-lang="true">Back to Store</a>
        <a href="javascript:void();" data-lang="true" onclick="javascript:LogOut();">Log Out</a>
</div>`

the version is: playwright: 1.16.3

The problem:
In firefox and webkit the test pass correctly, but in chromium don't pass. 

I don't use page object model yet because is the first dummy test. Later I would refactor it.

I hope this will help.

**Comment by Radli007** [comment]
I have similar problem, only chromium

problem if div is empty 
`<span id="printMain.sex" />`
`await page.click('#printMain.sex')`  - ERROR

if it is not empty, then there is no problem
`<div id="printMain.sex">man</div>`
`await page.click('#printMain.sex')`  - THAT'S OK

```typescript
const test_url = 'https://t0wwp.csb.app/';

test('editSelect', async ({ page }) => {
  const def_sex = {"value": "Мужской", "key": "1" };
  await page.goto(test_url);

  await page.click('[id="docEdit"]');
  await page.click('label[role="radio"]:has-text("Администратор")');

  await page.waitForSelector('[id="printMain\\.sex"]')
  await page.click('[id="printMain\\.sex"]');
  await page.waitForTimeout(1000);
  await page.click('text='+def_sex.value);

  await page.click('[id="docJson"]');

  const jsontext = await page.evaluate(el => el.innerText, await page.$('#jsontext'))
  const js = JSON.parse(jsontext);
  await expect(js['sex'].key).toMatch(def_sex.key);

  await page.waitForTimeout(100);
});
```

error:

```
Timeout of 30000ms exceeded.
Pending operations:
  - page.click at tests\example.spec.ts:36:14

page.click: Target closed
=========================== logs ===========================
waiting for selector "[id="printMain\.sex"]"
  selector resolved to visible <span id="printMain.sex" contenteditable="true"> </span>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is not visible
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is not visible
  ...
```

But, That's OK:

```typescript
const test_url = 'https://t0wwp.csb.app/';

test('editDIV', async ({ page }) => {
  const def_fio = 'ABCDEF';

  await page.goto(test_url);

  await page.click('[id="docEdit"]');
  await page.click('label[role="radio"]:has-text("Администратор")');

  await page.waitForSelector('[id="printMain\\.fio"]')
  await page.click('[id="printMain\\.fio"]');
  await page.keyboard.type(def_fio);
  await page.waitForTimeout(1000);

  await page.click('[id="docJson"]');

  const jsontext = await page.evaluate(el => el.innerText, await page.$('#jsontext'))
  const js = JSON.parse(jsontext);
  await expect(js['fio']).toBe(def_fio);

  await page.waitForTimeout(100);
});
```

** printMain\\.sex - UnVisible after Click, and Visible other element with id = printMain\\.sex **
printMain\\.sex isn't visible after click anymore but another element with the same id (printMain\\.sex) become visible

Tests: https://gitlab.com/komtek-front/form-doc-test/-/blob/main/tests/example.spec.ts
Components: https://gitlab.com/komtek-front/form-doc

**Comment by yury-s** [comment]
@SydAnderson look at the trace, the click on  'Back to Store' happens while you are still on the login page:

![image](https://user-images.githubusercontent.com/9798949/152451803-4003362e-709d-4aa3-847c-ef2053cef979.png)

after that you the navigation ends up on this page which doesn't have the search box:

![image](https://user-images.githubusercontent.com/9798949/152451917-05a3e055-1a7c-4d66-b8cc-08a782cf0201.png)

so your test script hangs waiting a selector on this line: ` await page.fill('#txtQuickSearch', 'tomatoes');` which is not there. This is working as expected. Or what is the issue you are facing?

**Comment by yury-s** [comment]
> after that you the navigation ends up on this page which doesn't have the search box:

Some more details: I believe there is a race between the navigation which is triggered by the click on 'Back to Store' link and the navigation that is triggered after clicking on the login button. 'Back to Store' navigation gets replaced by the navigation that login flow triggers. So you need to find a way to wait for the login flow to finish, [waitForUrl](https://playwright.dev/docs/api/class-page#page-wait-for-url) may help.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
