### ISSUE TITLE
[Question]: How to open Inspector when ConnectOverCDPAsync is used.

### ISSUE THREAD

**Issue by joostvz** [microsoft/playwright#11685]
### Your question

Is there a way to open the Playwright Inspector when it is started via the `ConnectOverCDPAsync` method?

I have a .NET 6 WPF app which contains a BlazorWebView component (WebView2). I'm able to connect Playwright to the app using `ConnectOverCDPAsync`, but I can't find a way to open the Inspector. Both setting the environment variable `PWDEBUG` and calling `page.PauseAsync()` didn't open the Inspector.

**Comment by mxschmitt** [comment]
Was able to repro on Node.js

```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.connectOverCDP("http://localhost:1234");
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("https://example.com");
  await page.pause();
  await browser.close();
})()
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
