### ISSUE TITLE
[Question] How to assert redirect based on statuscode?

### ISSUE THREAD

**Issue by UltraCakeBakery** [microsoft/playwright#11698]
I'm trying to validate an endpoint that returns a `302` + `Location` header. How can I prevent playwright from following the redirect so I can assert the `302` status code?

**Comment by aslushnikov** [comment]
@UltraCakeBakery you can use new [Request API](https://playwright.dev/docs/api/class-apirequestcontext)

Here's a short example on how to use `page.request.get()`:

```js
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
const context = await browser.newContext();
const page = await context.newPage();
const response = await page.request.get('https://aslushnikov.com');
console.log(response.status()); 
await browser.close();
```

**Comment by UltraCakeBakery** [comment]
This does not work because playwright follows the request. I can't validate the 302 status. This returns a 200. I also do this test in the context of `test.describe(() => test({ request }))`

**Comment by pavelfeldman** [comment]
Closing as per above, you should be able to follow and assert the redirect chain.

**Comment by NullVoxPopuli** [comment]
I find this isn't sufficient, because I want to block redirects in my test and assert what the redirect would have been.

This is essential for external redirects.

So far, I've tried all of the above -- and learned about routes, but even with trying to block all non-localhost requests, 
```js
await page.route(`**`, (route) => {
  if (!route.request().url().includes('localhost')) {
    return route.abort();
  }
  return route.continue();
});
```
the external pages still render
