### ISSUE TITLE
setupProxy.js doesn't seems to be handled during the webserver start.

### ISSUE THREAD

**Issue by stepan-lysenko** [microsoft/playwright#11693]
Hello gents, I have the following setup:
- create-react-app based application
- setupProxy.js file with a set of rules in order to use API from staging environment (with WebSockets support in it)
- `playwright.config.mjs` with the following piece of config inside
```
  webServer: {
    command: 'yarn start',
    port: 3000,
    timeout: 2 * 60 * 1000,
    reuseExistingServer: !process.env.CI,
  },
```

Unfortunately, not a single request to API is getting proxied. Is there any option to solve my issue?

**Comment by aslushnikov** [comment]
@stepan-lysenko do you [configure proxy](https://playwright.dev/docs/api/class-testoptions#test-options-proxy) to be used in browsers?

**Comment by stepan-lysenko** [comment]
> @stepan-lysenko do you [configure proxy](https://playwright.dev/docs/api/class-testoptions#test-options-proxy) to be used in browsers?
It does not want I'm looking for because of a few reasons.
1. I don't like the idea to copy part of my environment setup to playwright config.
2. `TextOptions.proxy` doesn't provide the same palette of possibilities as setupProxy.js. I don't even see the way to proxy all requests from `localhost:3000/apigw` to `my.real.domain/apigw` (and doesn't touch other requests to `localhost:3000`).

**Comment by stepan-lysenko** [comment]
Sorry for the buzz, I found the issue on my side. Working as charm, thanks for the amazing product.
