### ISSUE TITLE
[BUG] Playwright is not running tests on Selenium Grid + Docker

### ISSUE THREAD

**Issue by CctavioMoreira** [microsoft/playwright#11692]
**Context:**
- Playwright Version: 8.1.2
- Operating System: Linux (5.10.60.1-microsoft-standard-WSL2)
- Node.js version: 16.13.2
- Selenium Grid version: 4.1.1
- Browser: Chrome (v.97.0)
- Extra: The operating system is an image of Linux on Docker Desktop version 4.4.3 (73365) running through Windows 10.

**Bug description**

I'm trying to run some Playwright (Node.js) tests on Docker through Selenium Grid, but the tests are failing because of timeout. Chrome is apparently not starting. Locally without Docker everything is fine.

According to the [Playwright documentation](https://playwright.dev/docs/selenium-grid), it would be enough to run the tests using the following command:

> SELENIUM_REMOTE_URL=http://localhost:4444/wd/hub npx playwright test

But that is not working.

I'm building the **environment in Docker** by running the following file through Powershell:

```
$maxNodes = 1

function GetImages()
{
    docker pull selenium/hub:latest
    docker pull selenium/node-chrome:latest
}

function CreateGrid()
{
    docker network create grid
}

function CreateHub()
{
   docker run -d -p 4442-4444:4442-4444 --net grid --name hub selenium/hub:latest
}

function CreateNodes()
{
    $nodes = 1

    while($nodes -le $maxNodes)
    {
        docker run -d -P --net grid -e SE_EVENT_BUS_HOST=hub -e SE_EVENT_BUS_PUBLISH_PORT=4442 -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 -e SE_NODE_SESSION_TIMEOUT=120 selenium/node-chrome:latest
        $nodes++
    }    
}

cls
GetImages
CreateGrid
CreateHub
CreateNodes
cls
Write-Host "HUB AND NODES CREATED!!"
```

The config from playwright.config.ts is:

```
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  timeout: 20000,
  workers:1,  
  use: {
    baseURL: 'https://www.google.com',
    viewport: { width: 1280, height: 720 },
    browserName: "chromium",
    channel: "chrome",
    headless: false    
  }
};
export default config;
```

And the test running is:

```
test('Acessar Google', async ({ page }) => {

   await page.goto('/');

   const length = await page.locator('input[type=submit]').count();
   expect(length >= 1).toBeTruthy(); 
});
```

In Docker Selenium Grid, the following is displayed:

![image](https://user-images.githubusercontent.com/67709760/151409949-8a439351-1aff-455f-bc3b-55ab88c1374e.png)

The session is "empty" with nothing running. The browser has a blank page.

![image](https://user-images.githubusercontent.com/67709760/151409967-097ee502-7477-4673-901c-a76189ff8ecf.png)

After running the tests using the above mentioned command, the result is as follows.

![image](https://user-images.githubusercontent.com/67709760/151408387-8ca7473a-6bd0-4b81-bccd-48295b564628.png)

I think this is a bug. If anyone can help, I'd be grateful.

**Comment by dgozman** [comment]
@CctavioMoreira Could you get logs from inside the docker where you run Selenium? Also, please run your tests with `DEBUG=pw:browser* SELENIUM_REMOTE_URL=... npx playwright test` and post the logs here.

**Comment by CctavioMoreira** [comment]
> @CctavioMoreira Could you get logs from inside the docker where you run Selenium? Also, please run your tests with `DEBUG=pw:browser* SELENIUM_REMOTE_URL=... npx playwright test` and post the logs here.

Course!

The logs from inside Docker:

**selenium/hub:latest**

```
2022-01-28 12:41:24,354 INFO Included extra file "/etc/supervisor/conf.d/selenium-grid-hub.conf" during parsing

2022-01-28 12:41:24,356 INFO supervisord started with pid 8

2022-01-28 12:41:25,359 INFO spawned: 'selenium-grid-hub' with pid 10

12:41:25.734 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

2022-01-28 12:41:25,736 INFO success: selenium-grid-hub entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

12:41:25.739 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

12:41:25.819 INFO [BoundZmqEventBus.<init>] - XPUB binding to [binding to tcp://*:4442, advertising as tcp://172.18.0.2:4442], XSUB binding to [binding to tcp://*:4443, advertising as tcp://172.18.0.2:4443]

12:41:25.854 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://172.18.0.2:4442 and tcp://172.18.0.2:4443

12:41:25.869 INFO [UnboundZmqEventBus.<init>] - Sockets created

12:41:26.870 INFO [UnboundZmqEventBus.<init>] - Event bus ready

12:41:27.311 INFO [Hub.execute] - Started Selenium Hub 4.1.1 (revision e8fcc2cecf): http://172.18.0.2:4444

12:41:28.689 INFO [Node.<init>] - Binding additional locator mechanisms: name, relative, id

12:41:29.044 INFO [LocalDistributor.add] - Added node 0f9f8f26-85b7-4b96-a708-2748cc2dd9d8 at http://172.18.0.3:5555. Health check every 120s

12:41:29.053 INFO [GridModel.setAvailability] - Switching node 0f9f8f26-85b7-4b96-a708-2748cc2dd9d8 (uri: http://172.18.0.3:5555) from DOWN to UP

12:42:52.023 INFO [LocalDistributor.newSession] - Session request received by the distributor: 

 [Capabilities {browserName: chrome, goog:chromeOptions: {args: [--disable-background-networ..., --enable-features=NetworkSe..., --disable-background-timer-..., --disable-backgrounding-occ..., --disable-breakpad, --disable-client-side-phish..., --disable-component-extensi..., --disable-default-apps, --disable-dev-shm-usage, --disable-extensions, --disable-features=Improved..., --allow-pre-commit-input, --disable-hang-monitor, --disable-ipc-flooding-prot..., --disable-popup-blocking, --disable-prompt-on-repost, --disable-renderer-backgrou..., --disable-sync, --force-color-profile=srgb, --metrics-recording-only, --no-first-run, --enable-automation, --password-store=basic, --use-mock-keychain, --no-service-autorun, --export-tagged-pdf, --no-sandbox, --remote-debugging-port=0]}}]

12:42:52.803 INFO [LocalDistributor.newSession] - Session created by the distributor. Id: 739c3e172730c213a3d39f8bdd420b78, Caps: Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 97.0.4692.99, chrome: {chromedriverVersion: 97.0.4692.71 (adefa7837d02a..., userDataDir: /tmp/.com.google.Chrome.JkGk0z}, goog:chromeOptions: {debuggerAddress: localhost:33691}, networkConnectionEnabled: false, pageLoadStrategy: normal, platformName: linux, proxy: {}, se:cdp: ws://172.18.0.3:4444/sessio..., se:cdpVersion: 97.0.4692.99, se:vnc: ws://172.18.0.3:4444/sessio..., se:vncEnabled: true, se:vncLocalAddress: ws://172.18.0.3:7900, setWindowRect: true, strictFileInteractability: false, timeouts: {implicit: 0, pageLoad: 300000, script: 30000}, unhandledPromptBehavior: dismiss and notify, webauthn:extension:credBlob: true, webauthn:extension:largeBlob: true, webauthn:virtualAuthenticators: true}

12:43:58.736 INFO [LocalSessionMap.lambda$new$0] - Deleted session from local session map, Id: 739c3e172730c213a3d39f8bdd420b78
```

**selenium/node-chrome:latest**

```
2022-01-28 12:41:25,763 INFO Included extra file "/etc/supervisor/conf.d/selenium.conf" during parsing

2022-01-28 12:41:25,764 INFO supervisord started with pid 9

2022-01-28 12:41:26,766 INFO spawned: 'xvfb' with pid 11

2022-01-28 12:41:26,767 INFO spawned: 'vnc' with pid 12

2022-01-28 12:41:26,768 INFO spawned: 'novnc' with pid 13

2022-01-28 12:41:26,769 INFO spawned: 'selenium-node' with pid 14

2022-01-28 12:41:26,784 INFO success: xvfb entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-01-28 12:41:26,784 INFO success: vnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-01-28 12:41:26,784 INFO success: novnc entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

2022-01-28 12:41:26,784 INFO success: selenium-node entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)

Generating Selenium Config

Configuring server...

Setting up SE_NODE_HOST...

Setting up SE_NODE_PORT...

Setting up SE_NODE_GRID_URL...

Selenium Grid Node configuration: 

[events]

publish = "tcp://hub:4442"

subscribe = "tcp://hub:4443"


[node]

session-timeout = "60"

override-max-sessions = false

detect-drivers = false

max-sessions = 1


[[node.driver-configuration]]

display-name = "chrome"

stereotype = '{"browserName": "chrome", "browserVersion": "97.0", "platformName": "Linux"}'

max-sessions = 1


Starting Selenium Grid Node...

12:41:27.461 INFO [LoggingOptions.configureLogEncoding] - Using the system default encoding

12:41:27.464 INFO [OpenTelemetryTracer.createTracer] - Using OpenTelemetry for tracing

12:41:27.513 INFO [UnboundZmqEventBus.<init>] - Connecting to tcp://hub:4442 and tcp://hub:4443

12:41:27.533 INFO [UnboundZmqEventBus.<init>] - Sockets created

12:41:28.535 INFO [UnboundZmqEventBus.<init>] - Event bus ready

12:41:28.596 INFO [NodeServer.createHandlers] - Reporting self as: http://172.18.0.3:5555

12:41:28.605 INFO [NodeOptions.getSessionFactories] - Detected 16 available processors

12:41:28.640 INFO [NodeOptions.report] - Adding chrome for {"browserVersion": "97.0","browserName": "chrome","platformName": "Linux","se:vncEnabled": true} 1 times

12:41:28.646 INFO [Node.<init>] - Binding additional locator mechanisms: relative, name, id

12:41:28.747 INFO [NodeServer$1.start] - Starting registration process for node id 0f9f8f26-85b7-4b96-a708-2748cc2dd9d8

12:41:28.748 INFO [NodeServer.execute] - Started Selenium node 4.1.1 (revision e8fcc2cecf): http://172.18.0.3:5555

12:41:28.750 INFO [NodeServer$1.lambda$start$1] - Sending registration event...

12:41:29.048 INFO [NodeServer.lambda$createHandlers$2] - Node has been added

Starting ChromeDriver 97.0.4692.71 (adefa7837d02a07a604c1e6eff0b3a09422ab88d-refs/branch-heads/4692@{#1247}) on port 33960

Only local connections are allowed.

Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.

[C1h6r4o3m3e7D3r7i7v2e.r1 1w0a]s[ SsEtVaErRtEe]d:  sbuicncde(s)s ffualillye.d

: Cannot assign requested address (99)

12:42:52.785 INFO [ProtocolHandshake.createSession] - Detected dialect: W3C
```

The result running with _DEBUG=pw:browser*_ is:

![image](https://user-images.githubusercontent.com/67709760/151550732-baca6c6f-03a5-4bee-9d5a-fb2eb7e9b7a4.png)

**Comment by JontyMC** [comment]
I am also seeing issues with playwright not working in docker. I'm using latest (1.19). I tried reverting back through versions and 1.17 works.

**Comment by satya081** [comment]
> I am also seeing issues with playwright not working in docker. I'm using latest (1.19). I tried reverting back through versions and 1.17 works.

i am facing below issue while connecting to selenium grid from playwright.
https://github.com/microsoft/playwright/issues/12666

Could you please help to fix this issue?

**Comment by JontyMC** [comment]
> > I am also seeing issues with playwright not working in docker. I'm using latest (1.19). I tried reverting back through versions and 1.17 works.
> 
> i am facing below issue while connecting to selenium grid from playwright. #12666
> 
> Could you please help to fix this issue?

Did you try with 1.17?

**Comment by satya081** [comment]
> > > I am also seeing issues with playwright not working in docker. I'm using latest (1.19). I tried reverting back through versions and 1.17 works.
> > 
> > 
> > i am facing below issue while connecting to selenium grid from playwright. #12666
> > Could you please help to fix this issue?
> 
> Did you try with 1.17?

Yes I tried with 1.17 as well buts it not working.I raised on bug #12666

**Comment by vishnuramvs29** [comment]
I am also facing the same issue as [CctavioMoreira](https://github.com/CctavioMoreira). For me v17 works good with Selenium Grid. Please provide a fix for latest versions.

**Comment by John-Yue-Deltatre** [comment]
Hi, @CctavioMoreira @aslushnikov @dgozman 

I also meet very similar problem as yours, I can see my test case is sent to the hub and a session was established. but a browser with empty URL was launched and test case wasn't executed at node.  :

From the following logs, it seems that the problem is due to the fact that the cdp connection between hub and node was not able to established:

2022-06-08T05:33:32.190Z pw:browser <selenium> connecting to http://10.0.0.14:4444/wd/hub/
2022-06-08T05:33:33.170Z pw:browser <selenium> connected to sessionId=5bd420411877d19c1426cd5d47f97ddb
2022-06-08T05:33:33.171Z pw:browser <selenium> using selenium v4
2022-06-08T05:33:33.173Z pw:browser <selenium> retrieved endpoint ws://172.18.0.3:4444/session/5bd420411877d19c1426cd5d47f97ddb/se/cdp for sessionId=5bd420411877d19c1426cd5d47f97ddb
2022-06-08T05:33:33.229Z pw:browser <ws connecting> ws://172.18.0.3:4444/session/5bd420411877d19c1426cd5d47f97ddb/se/cdp
2022-06-08T05:33:41.919Z pw:browser <ws error> [object Object]
2022-06-08T05:33:41.921Z pw:browser <ws connect error> ws://172.18.0.3:4444/session/5bd420411877d19c1426cd5d47f97ddb/se/cdp connect ECONNREFUSED 172.18.0.3:4444
2022-06-08T05:33:41.922Z pw:browser <ws disconnected> ws://172.18.0.3:4444/session/5bd420411877d19c1426cd5d47f97ddb/se/cdp code=1006 reason=
2022-06-08T05:33:41.925Z pw:browser <selenium> disconnecting from sessionId=5bd420411877d19c1426cd5d47f97ddb
2022-06-08T05:33:42.145Z pw:browser <selenium> disconnected from sessionId=5bd420411877d19c1426cd5d47f97ddb

Finally, I solve this problem by these:
1. Assigning a node port to the node and exposing it(or you can alternatively expose the default port 5555)
2. add environment variable: "-e SE_NODE_GRID_URL=http://IPADDRESS:4445/wd/hub

So based on above 2 points, the node container should be created like this:

$ docker run -d -p 4445:4444 \
    -e SE_EVENT_BUS_PUBLISH_PORT=4442 \
    -e SE_EVENT_BUS_SUBSCRIBE_PORT=4443 \
    -e SE_NODE_PORT=4444 \
    -e SE_NODE_GRID_URL=http://IPADDRESS:4445/wd/hub \
    selenium/node-docker:4.2.1-20220531

Note: when executing playwright test, the URL there should still points to the hub's URL, Not the node grid url:
$ SELENIUM_REMOTE_URL=http://10.0.0.14:4444/wd/hub mvn test

**Comment by JontyMC** [comment]
+1 would like to see a fix for latest version so we can upgrade

**Comment by snackattas** [comment]
+1 would like to see a fix for latest version so we can upgrade

**Comment by Nagam-Naidu** [comment]
+1 facing the same issue.

**Comment by cian-sheehy** [comment]
+1 facing the same issue

**Comment by BalajiMoorthy12** [comment]
@John-Yue-Deltatre As mentioned i added the my selenium grid url under the SE_NODE_GRID_URL=http://ipaddress:port/wd/hub.
This resolves the problem and everything is cleared. 
Thanks

**Comment by Nagam-Naidu** [comment]
We were facing the same issue. We have updated the below environment variable in our docker-compose.yaml file.

`- SE_NODE_GRID_URL=http://localhost:4444/`

After adding above variable, tests are running on selenium grid 4 with playwright.

Can we add this in the new version of selenium grid.  ??

https://newreleases.io/project/github/SeleniumHQ/docker-selenium/release/4.1.1-20211217

**Comment by naveenanimation20** [comment]
Updated docker-compose.yaml file, just add one more environment variable:
      **- SE_NODE_GRID_URL=http://localhost:4444/**

> this will solve the issue. 

version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.3.0-20220726
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
      - SE_NODE_OVERRIDE_MAX_SESSIONS=true
      - SE_NODE_GRID_URL=http://localhost:4444/


  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"

**Comment by ngavrish** [comment]
Still having same issue with selenium 4.7. Playwright is not starting in selenium at all
