### ISSUE TITLE
[BUG] Video is not shown/played on the page

### ISSUE THREAD

**Issue by dimaBondarenko** [microsoft/playwright#11694]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Ubuntu 20.04
- Node.js version: v14.18.3
- Browser: Playwright Chromium (Version 99.0.4812.0 (Developer Build) (64-bit)) **&** Chromium (Version 99.0.4840.0 (Official Build) snap (64-bit))

**Describe the bug**

I got a page-under-the-test that has a video playing in the background. 
When I open the page in standard Chromium, the video is shown and played well.
When I open the page in the Playwright Chromium, nothing's going on.

I had a look at the network tab and it turned out the video in the Playwright Chromium is not downloaded fully - the response size is ~100KB, compared to expected 3.5MB.

Since I am not allowed to share the product I tried to find the site with the similar layout: This one https://demodern.com/ has nearly the same outcome . Please see comparison below:
![2022-01-27_19-15-40](https://user-images.githubusercontent.com/31986966/151413223-b9240ce6-6039-46f0-8fdd-c3538359feea.png)

![2022-01-27_19-35-47](https://user-images.githubusercontent.com/31986966/151413234-cc9e235b-99cb-4057-ae45-042b09c95ab7.png)

**Comment by dimaBondarenko** [comment]
Not sure I dug in the right direction 🤔but this inconsistency looks suspicious

**Comment by aslushnikov** [comment]
>  Chromium (Version 99.0.4840.0 (Official Build) snap (64-bit))

@dimaBondarenko When you say "official chromium", do you actually mean Google Chrome? See [Chromium vs Chrome](https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to)

**Comment by dimaBondarenko** [comment]
@aslushnikov I mean Chromium
![2022-01-27_23-53-06](https://user-images.githubusercontent.com/31986966/151450024-15e2f696-7688-4667-be86-029887174ac4.png)

**Comment by aslushnikov** [comment]
@dimaBondarenko I just downloaded official Chromium build from https://www.googleapis.com/download/storage/v1/b/chromium-browser-snapshots/o/Mac_Arm%2F965870%2Fchrome-mac.zip?generation=1643754818851911&alt=media and loaded the website - it still doesn't play video for me.

Google Chrome does play it, though. So this looks like a codecs issue that we describe here: https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to

**Comment by dimaBondarenko** [comment]
@aslushnikov I see your Chromium comes from `Mac_Arm` source. Could it be different from my Chromium for Ubuntu that comes from the snap package manager https://snapcraft.io/chromium?

**Comment by aslushnikov** [comment]
> Could it be different from my Chromium for Ubuntu that comes from the snap package manager https://snapcraft.io/chromium?

@dimaBondarenko i looked at this; and turns out it is different! Canonical builds their own Chromium with a bunch of patches atop: https://git.launchpad.net/~chromium-team/chromium-browser/+git/snap-from-source/tree/build?h=stable

To sum up my findings:
- the video on the website is using H264 codec
- Canonical licensed H264 codec: https://www.mpegla.com/programs/avc-h-264/licensees/

So that explains how this works!

**Comment by aslushnikov** [comment]
Closing this wrt to findings!

**Comment by sagarrajput** [comment]
@dimaBondarenko @aslushnikov, Is there way, I can still play video in Chromium?

**Comment by eggei** [comment]
I have a similar problem, I don't see the video in the main view but it is there in the timeline view above. I have some custom elements on the video that I can get during the tests and they are being tested however, none is shown in the main preview.

Why is this?

<img width="1312" alt="Screenshot 2024-07-22 at 2 48 15 PM" src="https://github.com/user-attachments/assets/0206f8e0-de14-48b5-bd03-18c1e5a490e4">
<img width="1403" alt="Screenshot 2024-07-22 at 2 48 25 PM" src="https://github.com/user-attachments/assets/57f2765a-35eb-4a4a-b86b-2117c3935bd3">
