### ISSUE TITLE
[Question] how can i just run one test?

### ISSUE THREAD

**Issue by Zack921** [microsoft/playwright#11696]
hi,I want to debug the project, but I don't want to run all tests.
how can I just run one test?
![image](https://user-images.githubusercontent.com/32858043/151415552-b667c83c-7635-412e-a771-d56c717a1f5f.png)

**Comment by ltsuda** [comment]
Do you know the name of the test? If yes, you can use the `--grep "My test" CLI parameter. https://playwright.dev/docs/test-cli#reference

Or you can use `test.only` and run you npm script as usual, just remember to remove the `.only` after you finish the debug. https://playwright.dev/docs/api/class-test#test-only
