### ISSUE TITLE
[BUG] Origin automatically appended when setting background image url with JS

### ISSUE THREAD

**Issue by scriptify** [microsoft/playwright#1170]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Windows 10
- Extra: PowerShell, Node v13.7.0, Custom TypeScript Webpack setup

**Code Snippet**

```javascript
<!-- index.html -->
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
  </head>
  <body>
    <div style="height: 100px; width: 500px; background-image: url(images/pic01.jpg);"></div>
    <div id="bgImg" style="height: 100px; width: 500px;"></div>
    <img id="testImg"></img>
    <script>
      setTimeout(() => {
        document.querySelector(
          '#bgImg',
        ).style.backgroundImage = `url(images/pic01.jpg)`;

        document.querySelector(
          '#testImg',
        ).src = 'images/pic01.jpg'
      }, 3000);
    </script>
  </body>
</html>
```

**Describe the bug**

When I start a http server hosting this HTML file and open it in Chrome under `http://localhost:8080`, the resulting markup after 3 seconds, as expected, looks like this:
![image](https://user-images.githubusercontent.com/20152692/75625788-f0999900-5bf3-11ea-9fdc-03852a636e75.png)

Opening the same page with Playwright adds the origin to the dynamically set background image URL at the beginning of the string for some reason:
![image](https://user-images.githubusercontent.com/20152692/75625813-2b033600-5bf4-11ea-8062-241ff67fca79.png)

The only option I am setting is `{ headless: false }`
Is this a bug or a feature? Am I missing something?

I am writing some sort of webscraper where this behaviour forces me to replace those URLs with Regex which can lead to unexpected errors at huge HTML payloads.

Awesome work by the way!

**Comment by aslushnikov** [comment]
@scriptify hmm it doesn't repro for me.

1. Got your `index.html`
2. Served it at `localhost:1234`
3. Ran the following pw script:

```js
const pw = require('playwright');

(async() => {
  const b = await pw.chromium.launch({headless: false});
  const page = await b.newPage();
  await page.goto('http://localhost:1234');
})();
```

And still ended up with an expected result:

![image](https://user-images.githubusercontent.com/746130/75745947-a684e600-5ccd-11ea-878c-0cfffcf182d9.png)


@scriptify can you share your playwright script as well?

**Comment by scriptify** [comment]
Oh my bad, have forgotten to mention that I'm using webkit.

```javascript
const PAGE_URL = 'http://localhost:8080/';
  const browser = await playwright.webkit.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(PAGE_URL);
```

It works with Chromium though. Must be an issue with webkit then.
Still strange behaviour.
