### ISSUE TITLE
[Question] How to start playwright programtically through npm api function ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#11718]
Was wondering what the function of playwright that I can use, to run it within js project "npm api" something similart to what cypress have

```
await cypress.run({
      spec: `./**/test.suite.js`,
      browser: "chrome",
      headless: false
})
```

**Comment by aslushnikov** [comment]
There's no such api yet; you can always use `child_process.spawn` to run an npm command.

For the API, follow this issue: https://github.com/microsoft/playwright/issues/7275
