### ISSUE TITLE
feature: support "microphone" and "camera" permissions for WebKit

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#11714]
**Context:**
- Playwright Version: 1.18.1
- Operating System: mac
- Node.js version: 16.13.1
- Extra: project - mobile safari

**Code Snippet**

```typescript
test("basic test", async ({ page, context }) => {
  await page.goto("https://webcammictest.com/check-mic.html");
  await context.grantPermissions(["microphone", "camera"]);
});
```

**Describe the bug**

When trying to give microphone and camera permissions on mobile Safari I get the following error
![image](https://user-images.githubusercontent.com/42112796/151524865-dec3faad-28b5-4036-9994-767f40b855ad.png)

Step to repreduce:

1. run `npm init playwright my-test` command to generate new project
2. go to playwright.config.ts and change the `projects` to 
```
 {
      name: "Mobile Safari",
      use: {
        ...devices["iPhone 12"],
      },
    },
```
3. try to give permissions

**Comment by aslushnikov** [comment]
Neither microphone nor camera are supported for webkit yet; marked as "collecting feedback"!

**Comment by bryce-milkey** [comment]
This seems to be an issue for Firefox as well. 
If you want to automate tests that need **camera** and **microphone** permissions through PlayWright, it can only be ran against Chrome.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by bjoshi-codal** [comment]
Do we still have any solution for this ? Any support added in playwright for camera and microphone for firefox and safari browsers ?

**Comment by marco-mn** [comment]
is there no workaround at all that somebody can share?
