### ISSUE TITLE
[Question] @playwright/test - Ignore .tsx files when running tests

### ISSUE THREAD

**Issue by tylucaskelley** [microsoft/playwright#11720]
Asking this as a question rather than a bug report, as I hope I'm just doing something wrong in my configuration here. Was previously running Playwright tests via Jest, and am trying to switch to the official test runner. However, when executing `npx playwright test`, it fails with an `SyntaxError: Unexpected token '<'` when it attempts to parse a `.tsx` file that contains a React component. The tests themselves do not use or import React components, they just happen to be in same codebase.

All of my e2e-related code is consolidated under a `test/e2e/` directory. Will try to share all of the relevant information that I can.

## Environment

Our app is a Next.js app - React/TypeScript on the front-end, Express/TypeScript on server-side, all in one repo.

1. OS - Fedora 35
2. Node.js version - 16.13.0
3. Playwright - `@playwright/test` 1.18.1

### .babelrc

```json
{
  "env": {
    "local": {
      "presets": ["next/babel"],
      "plugins": []
    },
    "development": {
      "presets": ["next/babel"],
      "plugins": []
    },
    "production": {
      "presets": ["next/babel"],
      "plugins": []
    },
    "test": {
      "presets": [["next/babel", { "preset-env": { "modules": "commonjs" } }]],
      "plugins": []
    }
  },
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }]
  ]
}
```

### playwright.config.ts

```typescript
import { PlaywrightTestConfig } from "@playwright/test";
import { ENV_URLS } from "./server/constants";

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve("test/e2e/setup"),
  use: {
    baseURL: ENV_URLS.local,
  },
  // have tried with/without these last two, no difference in error
  testMatch: "test/e2e/**/*.test.ts",
  testDir: "test/e2e", 
};

export default config;
```

### package.json

```json
{
   ...,
   "scripts": {
       ...,
       "test:e2e": "playwright test"
    }
}
```

### tsconfig.json

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "target": "es6",
    "module": "esnext",
    "jsx": "preserve",
    "allowJs": true,
    "moduleResolution": "node",
    "noUnusedParameters": true,
    "allowSyntheticDefaultImports": true,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "paths": {
      "*": [
        "types/*"
      ]
    },
    "lib": [
      "dom",
      "es2016"
    ],
    "strict": false,
    "forceConsistentCasingInFileNames": true,
    "noEmit": false,
    "noUnusedLocals": true,
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "outDir": ".next/tsc-cache/",
    "incremental": true,
    "experimentalDecorators": true
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx"
  ],
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by pavelfeldman** [comment]
Could you share entire exception / error message? This should not be happening, of you don't have tsx files and don't import them from your tests, it should all work. My guess would be that there is some import in one of the tests.

**Comment by henriquemotaesteves** [comment]
@pavelfeldman maybe I can help with more information. What @tylucaskelley is facing could be similar to the issue that I am facing now. I have a library that has models and components.  I use only the models in my tests because they are very useful. Components are not used at all. If I import my models using the index file at the root of the library, what export the models and the components, I got the same error because the components are imported indirectly. The solution is to import the models via a hardcoded path, which is inconvenient. The best option would be to support jsx/tsx files, even they are not used in the tests, or to have some kind of workaround to ignore these files.

**Comment by pavelfeldman** [comment]
@henriquemotaesteves, this makes sense. Try running your tests with the environment variable `PW_COMPONENT_TESTING=1` set and let me know if it helps.

**Comment by tylucaskelley** [comment]
Will try that! Thank you. I think what @henriquemotaesteves described sounds similar to what we have going on.

**Comment by tylucaskelley** [comment]
Maybe I'm missing something, but is that environment variable documented on https://playwright.dev anywhere? Search showed up nothing so it could be a useful FAQ/troubleshooting item

**Comment by pavelfeldman** [comment]
This isn't anything documented, it is a part of the component testing story we have not shared yet.

**Comment by tylucaskelley** [comment]
Great - yeah I will report back when I'm able to test on the branch we have set up to move from Jest to Playwright for our test runner!

**Comment by tylucaskelley** [comment]
So, @pavelfeldman setting that env var does indeed get us past the parsing issue with the TSX files! Unfortunately just leads to another error, also related to some code not being directly imported by the test suite. Proabbly not super helpful, but the error and relevant code snippet it's yelling about:

```
export const defaultRoomCatalog: { [type in RoomType]: RoomAttributes } = {
  MASTER_BED: roomAttributesNew({
    roomType: RoomType.MASTER_BED,
    roomClass: RoomClass.INTERIOR,
    roomEnclosure: RoomEnclosure.CONDITIONED,
    name: "Owners",
    shortName: "Ownr Bd",
    windowType: BuiltinWindowId.T1,
    bedroomCount: 1,
    hasBaseTrimMolding: true,
  }),
```

```typescript
export const defaultRoomCatalog: { [type in RoomType]: RoomAttributes } = {
  MASTER_BED: roomAttributesNew({
    roomType: RoomType.MASTER_BED,
    roomClass: RoomClass.INTERIOR,
    roomEnclosure: RoomEnclosure.CONDITIONED,
    name: "Owners",
    shortName: "Ownr Bd",
    windowType: BuiltinWindowId.T1,
    bedroomCount: 1,
    hasBaseTrimMolding: true,
  }),
  ...
};
```

**Comment by pavelfeldman** [comment]
Is that a regular .ts file or is this constant defined in the TSX file?

**Comment by tylucaskelley** [comment]
> Is that a regular .ts file or is this constant defined in the TSX file?

It's a regular TS file!

**Comment by tylucaskelley** [comment]
Yes! Will make a note to do so when I get some free time. Will try to set up a test repo w/ our configuration + a file that hopefully causes the error

**Comment by pavelfeldman** [comment]
Keeping the issue tracker healthy, so closing this one. Please feel free to open a new issue if this does not cover your use case and link this one.

**Comment by henriquemotaesteves** [comment]
@pavelfeldman e @tylucaskelley just a feedback. Using the environment variable PW_COMPONENT_TESTING solved my problem.

**Comment by henriquemotaesteves** [comment]
@pavelfeldman e @tylucaskelley

Using the variable `PW_COMPONENT_TESTING` fixed the error:

`SyntaxError: Unexpected token '<'`

But now I am facing the following error:

`TypeError: X is not a constructor`

If I use the hardcoded path to importing X instead of an index file the problem disappears.

Is there any chance that `PW_COMPONENT_TESTING` is causing this new problem?

**Comment by colin-c6** [comment]
This is still an issue for us using 1.40. It means we cannot reuse the methods used to setup test data in integration tests (using jest) for our e2e tests, as playwright returns `SyntaxError: Unexpected token '<'` when it attempts to parse .svg 
 or .tsx files.

Does anyone have a solution to this?
