### ISSUE TITLE
[Question]how to debug the playwright?

### ISSUE THREAD

**Issue by Zack921** [microsoft/playwright#11727]
Hi,I want to know how the awesome project work.However, when I changed some code for api of fill, I found It doesn't work after rebuild.
![image](https://user-images.githubusercontent.com/32858043/151652686-4967ed73-813c-4c00-8202-4c1065cdd6ef.png)
![image](https://user-images.githubusercontent.com/32858043/151652713-2a6278db-b815-4c46-b58f-89e4d9532158.png)
Is there any analysis or artical about how the playwright work?

**Comment by aslushnikov** [comment]
@Zack921 There's no article on the internals, but we have a [CONTRIBUTING.md](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md). 

Feel free to explore the codebase and the commits team members do!
