### ISSUE TITLE
Error: browserType.launch: Browser closed.

### ISSUE THREAD

**Issue by gvr-kumar** [microsoft/playwright#11724]
We are trying to run our tests on docker container image through Jenkins Job (successfully installed all dependencies like libraries, node.js using pipeline script). Using the following "RobotFramework-Browser" docker image: 

https://github.com/MarketSquare/robotframework-browser/blob/main/docker/Dockerfile 

**Context:**

Playwright Version: 1.18.0
Operating System: Linux (Docker Container)
Node.js version: 16.x
Browser Engine: Chromium
Jenkins Pipeline

**But getting the below error.**

```
Error: Tried to take screenshot, but no page was open.
| FAIL |
Error: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /usr/local/lib/python3.8/dist-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/chromium-939194/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-QoKuZ3 --remote-debugging-pipe --no-startup-window
<launched> pid=365
```

**Comment by aslushnikov** [comment]
@gvr-kumar can you show more of the error? As a wild guess, do you run browsers in a headed mode? If so, make sure to run through XVFB.

**Comment by gvr-kumar** [comment]
HI Aslushnikov, 

Does this work?

Error: Tried to take screenshot, but no page was open.
| FAIL |
Error: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /usr/local/lib/python3.8/dist-packages/Browser/wrapper/node_modules/playwright-core/.local-browsers/chromium-939194/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-R3SBO0 --remote-debugging-pipe --no-startup-window
<launched> pid=246
[pid=246][err] [246:246:0128/161228.372231:ERROR:filesystem_posix.cc(62)] mkdir : No such file or directory (2)

**Comment by yury-s** [comment]
> Yes I run in headed mode. **where exactly should I try this?: XVFB**

You can prepend `xvfb-run` to your test runner command, e.g. `xvfb-run npx playwright test` but it would be easier to run in headless mode since the docker container doesn't have a display.

**Comment by yury-s** [comment]
Something like this should work:
```sh
sh 'xvfb-run python3 -m robot -d Results Tests/'
```

**Comment by gvr-kumar** [comment]
Thankyou so much Yury. It worked both headless and head mode.

**Comment by Pythonic2** [comment]
i am having this problem also but i am using playwright helpe-me please
