### ISSUE TITLE
[Question] Is there option to run tests via xml suites?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#11739]
Hi there great Playwright team!

Our team uses the Java + Selenium project in one of our applications. We run Selenium tests via the suites that contain related tests. Something like this:
![image](https://user-images.githubusercontent.com/52656401/151711316-0939fa54-a354-4634-a068-a05a5ba0acfd.png)

How can I use something similar in the **"@playwright/test"** framework? 
I tried options like --grep or --project, but it is more complex for maintenance and not so intuitive as a plain XML file.

Thanks a lot,

**Comment by aslushnikov** [comment]
@AlexKomanov so if I understand correctly, you have a single XML file that lists all the tests that you want to run. You can simulate a similar thing with [`testMatch`](https://playwright.dev/docs/api/class-testconfig#test-config-test-match) option in configuration file:

```ts
import { PlaywrightTestConfig, devices } from '@playwright/test';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {

  testMatch: [
    '*/tests/a.spec.ts',
    '*/tests/b.spec.ts',
    '*/tests/c.spec.ts',
  ],

  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
};
export default config;
```

**Comment by AlexKomanov** [comment]
@aslushnikov 
Not so.
In Java project I have a lot of XML files that I want them to contain several groups of tests and run simultaneously several files, or just to have option to store tests from different directories in the tests part and be able to run the tests by calling the xml file, like we can do it in MAVEN for example:
`mvn clean test -DsuiteXmlFile="<nameOfFile>.xml`
Thats what I mean.

**Comment by yury-s** [comment]
In addition to what Andrey said you have the following options:
- the config file may contain several project definitions, each having its own `testMatch` filter. You can then run only selected projects similar to maven: `npx playwright test --project p1 p2 p4` (looks like you already tried that and didn't like for some reason)
- you can have multiple config files and then specify one of them via --config option: `npx playwright test --config ./module1/playwright.config.ts`
- `testMatch` filter may be computed dynamically based on e.g. environment variable: 

```js

const suites = {
  'suite1': [
    '*/tests/a.spec.ts',
    '*/tests/b.spec.ts',
    '*/tests/c.spec.ts',
  ],
  'suite2': [
    '*/e2e/a.spec.ts',
    '*/fe/b.spec.ts',
    '*/foo/c.spec.ts',
  ],
  'all': ['**/*.spec.ts']
};

const config: PlaywrightTestConfig = {
  testMatch:  filters[process.env.SUITE || 'all']

...
}
```

**Comment by AlexKomanov** [comment]
@yury-s 
Thanks!
How can I use **cosnt **suite**** as a parameter for a run?

**Comment by yury-s** [comment]
> How can I use **cosnt **suite**** as a parameter for a run?

Just set desired suite name to the environment variable when running the tests, something like this:
```sh
SUITE=suite2 npx playwright test
```
