### ISSUE TITLE
[REGRESSION]: Project options stopped working in 1.18.1, worked in 1.17.2

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#11737]
**Context:**
- GOOD Playwright Version: 1.17.2
- BAD Playwright Version: 1.18.1
- Operating System: Windows
- Extra: Reproducible testcases and readme in pw-regression.zip attached.

**Describe the bug**
I just found a regression by comparing the behavior of Playwright 1.18.1 to 1.17.2
I am using the projects feature described in https://playwright.dev/docs/test-parameterize#parameterized-projects

[pw-regression.zip](https://github.com/microsoft/playwright/files/7964438/pw-regression.zip)

Ping me if you need more info. Thanks!

**Comment by aslushnikov** [comment]
@khtan  definitely need more info! Can you share what exactly was working and stopped working?

**Comment by khtan** [comment]
I have submitted a working testcase in a zip file with readme instructions.
Please take a look. I will be happy to answer more questions once you can
reproduce the problem for yourself using the testcase I provided.

**Comment by dgozman** [comment]
@khtan There was indeed a breaking change in the version 1.18. It requires a minimal migration - every fixture that is intended to be configurable in the config file should have `option: true`.

- 1.17 and below:
  ```js
  test.extend({
    myOption: 'defaultValue',
  })
  ```

- 1.18 and above:
  ```js
  test.extend({
    myOption: ['defaultValue', { option: true }],
  })
  ```

Sorry for the trouble! We did a poor job communicating this change. There is more information in the [release notes](https://playwright.dev/docs/release-notes#breaking-change-custom-config-options).

**Comment by khtan** [comment]
Cool! Thanks for the solution. I will fix my configuration as suggested.
