### ISSUE TITLE
[Feature] save tracing to in-memory streams

### ISSUE THREAD

**Issue by KagamiChan** [microsoft/playwright#11731]
Hi, our team is running Playwright tests on Azure Functions, and we'd like to benefit from tracing for debugging flaky tests as the Azure Function env is more or less different than local dev machines. 

Then the blocker is: Azure Function's file system is readonly, we cannot save to tracing file onto the FS and do the upload.

Although there's some workaround like File Share mounts which I haven't given a try, I think it would be handy that if we'll be able to get the tracing data from some in-memory objects without the FS layer. Also I think this would make customized naming possible, and this could be helpful in other scenarios

**Comment by unlikelyzero** [comment]
@Kagamichan what about running an azure function for browserless.io (or some-other chrome-as-a-service) via `playwright.chromium.connect()`? That's what we're doing and should work for your case.

**Comment by KagamiChan** [comment]
Thanks @unlikelyzero for sharing such services, I did not know it before. My team however would like to take more ownership of the infra in our desired solution :)

**Comment by KagamiChan** [comment]
Update: we investigated the error on Azure Functions, actually the trace file was saved to writable `/tmp` folder and the error happened on copying to read-only local folder. So the workaround is to also save that trace file onto `/tmp` folder

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
