### ISSUE TITLE
[BUG] Hide unsupported expect methods

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#11734]
`toBeCalledWith`, `toBeCalledTimes`, etc.

**Comment by dgozman** [comment]
We should probably have an explicit list of supported methods.

**Comment by adrianbienias** [comment]
On doc page https://playwright.dev/docs/test-assertions it says 

> Playwright Test uses [expect](https://jestjs.io/docs/expect) library for test assertions

But some Jest assertions don't work e.g. `expect.assertions(number)`
