### ISSUE TITLE
[Feature] Add TestResult information to custom reporters onEnd event

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#11747]
[Custom reporter](https://playwright.dev/docs/test-reporters#custom-reporters) has a lot of functions like `onTestBegin` `onTestEnd` etc. and most of them receive the `TestResult` object which contains useful information like retry number

I would be nice to get the `TestResult` object on the `onEnd` event (today we receive the `FullResult` interface which contains only the status of the run)

my use case is simple: when the tests failed I want to send a slack message with the number of retries

**Comment by yury-s** [comment]
All information you need is already available in `onTestBegin/End` you can maintain custom state based on those signals in your recorder. Each recorder has its own requirements and many of them don't need such aggregated result. There are not plans to extend the TestResult API to inlcude all test results.

> my use case is simple: when the tests failed I want to send a slack message with the number of retries

If you want to send the message only after max retries you can compare [TestCase.retries](https://playwright.dev/docs/api/class-testcase#test-case-retries) with [TestResult.retry](https://playwright.dev/docs/api/class-testresult#test-result-retry)

**Comment by dgozman** [comment]
@israelKusayev

All tests are available in the `suite` that is passed to `onBegin`. You can examine all the results from this suite in `onEnd` and collect any kind of statistics. For example:

```js
class MyReporter {
  onBegin(config, suite) {
    this.suite = suite;
  }

  onEnd(fullResult) {
    const failedTests = this.suite.allTests().filter(test => !test.ok());
    for (const test of failedTests) {
       console.log(test.title, 'max retries: ', test.retries);
       console.log('actual attempts: ', test.results.length);
    }
  }
}
```

**Comment by anjireddy5817** [comment]
Could you, please provide code snippet for failed testcase also
