### ISSUE TITLE
[BUG] "'Log in'" form of selector fails with labels

### ISSUE THREAD

**Issue by SteveALee** [microsoft/playwright#11740]
**Context:**
- Playwright Version: 1.18
- Operating System: Windows WSL
- Node.js version: 16.13.0
- Browser: Ffx

**Code Snippet**

```html
<label for="name1" >Name 1 is here</label>
<input type="text" id="name1" name="name1"/>

<label>Name 2 is here
<input type="text" name="name2"/>
</label>
```

```javascript
const URI = "http://localhost:8888/test";

test("labels should work", async ({ page }) => {
  await page.goto(URI);
  await page.fill("text=Name 1 is here", "Name 1"); // works
  await page.fill("text=1", "Name 1 2"); // works
  await page.fill('"Name 1 is here"', "Name 1 3"); // works
  await page.fill('"1"', "Name 1 4"); // fails
});
```

**Describe the bug**

It's great that selecting a label allows page actions to work on the related control. But it doesn't always work. The last action above fails. I initially found found a wrapped checkbox failed to matched and used a css selector [1]. I decided to get to the bottom of it and the above explains the problem hit.

Incidently, when tried to use inspector it hung completely on the timed-out match. SO much so I could not close the GUI windows, ^C out kill with task manager. I had to reboot.

1: 'label:text("The information I provided is correct") > input[type="checkbox"]' - I guess `:text()` always works like `text=`

**Comment by aslushnikov** [comment]
So the reason it fails is the following:

* the `text=foo` (**without** quotes) matches by substring
* the `text="foo"` (**with** quotes) matches by exact match
* the `"foo"` selector is the same as `text="foo"` selector

These rules are outlined in the [documentation](https://playwright.dev/docs/selectors#text-selector).

Now, in your case, the `"1"` selector is the same as `text="1"` selector which looks for exact match. So it fails.
