### ISSUE TITLE
[Question] What config changes & default behavior is playwright overriding while debugging in vscode?

### ISSUE THREAD

**Issue by keithbentrup** [microsoft/playwright#11741]
It seems the playwright project overrides some unknown amount of my explicit configuration and expected behavior while debugging in vscode. Where can I find a definitive list of those overrides/changes if one exists?

Here's what I found so far: it seems the `testInfo.timeout` is set to 0 while debugging in vscode. How do I prevent this override? The default reporter is changed. How do I get (more) consistent output in the terminal & debug console? `console.log` is not sent to the debug console. How do I send output to the debug console while developing/debugging?

I'm sure there's others, but rather than guess and endlessly poke around when I'm seeing something different in the terminal vs the debug console, maybe someone can shed some light on what's happening.

I'm relatively new to the project, but this is one of the few projects that I've used where I can't reliably replicate what would actually happen in my terminal while debugging in vscode. It's frustrating because I have to develop & test my tests differently, it makes it harder to wrap & test playwright functionality into custom scripts, and it took me awhile to figure out that some of my explicit config was being ignored/changed.

Running on macOS Monterey (12.1)
VSCode 1.63.2
Node v16.13.2
Playwright 1.18

sample test:
```javascript
const {test} = require('@playwright/test')

test('mytest', async ({ page }, testInfo) => {
  console.log('testInfo.timeout', testInfo.timeout)
})
```

sample playwright config:
```javascript
const config = {
  timeout: 30000,
  projects: [
    {
      name: 'new',
      use: {
        browserName: 'chromium',
        headless: false
      },
    },
  ],
}

module.exports = config
```

sample launch.json
```json
    {
      "type": "node",
      "request": "launch",
      "name": "Run mytest",
      "skipFiles": [
        "<node_internals>/**"
      ],
      "program": "${workspaceRoot}/node_modules/@playwright/test/cli.js",
      "args": [
        "test",
        "-g",
        "mytest",
        "-c",
        "playwright.dev.js"
      ]
    }
```

Use these samples in the terminal vs vscode debugging and see some of the differences described.

**Comment by pavelfeldman** [comment]
We recommend using the vscode extension (https://github.com/microsoft/playwright-vscode) instead of the launch configuration. The default overrides that were in place while running w/ Node debugger were removed.
