### ISSUE TITLE
[BUG] HTML reporter fails to open test details for test cases if they're imported in other files

### ISSUE THREAD

**Issue by vkolova** [microsoft/playwright#11742]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux, Windows and Mac
- Node.js version: 16.13, 14.17.1
- Browser: All
- Extra: -

**Code Snippet**

```javascript
// playwright.config.js
module.exports = {
    testMatch: '*.list.js',
    reporter: [['list'], ['html', { open: 'always' }]]
};
```

```javascript
// feature-a.spec.js
const { test } = require('@playwright/test');

test.describe('Feature A', () => {
    test('example test', async ({ page }) => {});
});

// feature-b.spec.js
const { test } = require('@playwright/test');

test.describe('Feature B, wont work either', () => {
    test('example test', async ({ page }) => {});
});
```

```javascript
// test-a.list.js
const { test } = require('@playwright/test');

test.describe('This works', () => {
    test('example test', async ({ page }) => {});
});

// test-b.list.js
const { test } = require('@playwright/test');

test.describe('But those will not open', () => {
    require('./feature-a.spec');
});

require('./feature-b.spec'); // that won't work either
```

**Describe the bug**

In our project, I'm trying to build a folder-like structure of the test names. You'll gree that having files with thousands of lines of tests, just so that the tests share one root describe is not ideal, so I broke down the different sections and features into smaller .spec.js files and tried to require them into .list.js files, like in `test-b.list.js` in the example I added. List reporter looks great, everything works, but the HTML reporter won't open any details about those tests. I followed the instructions in the [Use a "test list" file](https://playwright.dev/docs/test-parallel#use-a-test-list-file) section of the documents.

![image](https://user-images.githubusercontent.com/5569382/151751793-965e49b1-1df4-4122-96f8-7136e2a133e3.png)

This is what happens when you try to open details for one of the "required" .spec.js files:
![Screenshot from 2022-01-31 09-08-07](https://user-images.githubusercontent.com/5569382/151752305-7a87cd9b-e53c-4ad1-91bd-1425787bd9fa.png)

**Comment by aslushnikov** [comment]
@vkolova thank you for the great description, i can repro!
