### ISSUE TITLE
[BUG] svelte + 1.18.0-alpha: SyntaxError: The requested module '@playwright/test' does not provide an export named 'PlaywrightTestConfig'

### ISSUE THREAD

**Issue by bbigras** [microsoft/playwright#11755]
**Context:**
- Playwright Version: @playwright/test@1.18.0-alpha-jan-10-2022
- Operating System: Linux
- Node.js version: v16.13.2
- Browser: <didn't reach this part>
- Extra: 

## System:
 - OS: Linux 5.15 NixOS 22.05 (Quokka) 22.05 (Quokka)
 - Memory: 740.97 MB / 15.51 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.2 - /nix/store/1s5l90kdzz5ii4bafi2dnyzv3smziq49-nodejs-16.13.2/bin/node
 - npm: 8.1.2 - /nix/store/1s5l90kdzz5ii4bafi2dnyzv3smziq49-nodejs-16.13.2/bin/npm
## Languages:
 - Bash: 5.1.12 - /run/current-system/sw/bin/bash

**Code Snippet**

```sh
# Skeleton project, Typescript, Eslint, Prettier
npm init svelte@next svelte-playwright
cd svelte-playwright
npm install

# Typescript, "tests", true, false
npm init playwright
npx playwright test
```

I get: `Error: playwright.config.ts: Cannot import a typescript file from an esmodule.`

try 1.18.0-alpha:
```
npm i --save-dev @playwright/test@1.18.0-alpha-jan-10-2022
PW_EXPERIMENTAL_TS_ESM=1 npx playwright test
```

I get:
```
(node:62468) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
Using config at /home/bbigras/dev/svelte-playwright/playwright.config.ts
file:///home/bbigras/dev/svelte-playwright/playwright.config.ts:1
import { PlaywrightTestConfig, devices } from '@playwright/test';
         ^^^^^^^^^^^^^^^^^^^^
SyntaxError: The requested module '@playwright/test' does not provide an export named 'PlaywrightTestConfig'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at Loader._requireOrImport (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/loader.js:260:28)
    at Loader.loadConfigFile (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/loader.js:77:18)
    at loadConfig (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/runner.js:91:24)
    at loadConfigFromDirectory (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/runner.js:98:24)
    at Runner.loadConfigFromFile (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/runner.js:107:22)
    at runTests (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/cli.js:148:18)
    at Command.<anonymous> (/home/bbigras/dev/svelte-playwright/node_modules/@playwright/test/lib/cli.js:73:7)
```

**Describe the bug**

maybe related to #7121

Same thing with v1.18.1

**Comment by pavelfeldman** [comment]
Typescript and ESM are not yet best friends, replace first line with:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
```

**Comment by bbigras** [comment]
It works. Thank you very much.

Should this issue be closed?

**Comment by pavelfeldman** [comment]
We'll probably want to make npm init playwright to generate esm-friendly code, so leaving open.

**Comment by pavelfeldman** [comment]
new `npm init playwright` is published.

**Comment by DvDream** [comment]
> Typescript and ESM are not yet best friends, replace first line with:
> 
> ```ts
> import type { PlaywrightTestConfig } from '@playwright/test';
> ```

Hi, I've just updated playwright to "@playwright/test": "^1.18.1" and I got the same configuration error since then:
``` Error: playwright.config.ts: Cannot import a typescript file from an esmodule.```

and your suggestion is not working for me :(

**Comment by qk0106** [comment]
I got that as well.

**Comment by DvDream** [comment]
> I got that as well. [#11755 (comment)](https://github.com/microsoft/playwright/issues/11755#issuecomment-1032413506)

Hi, check if in your `package.json` file you have the field `type:'module'`. I got that maybe for previous "trial and error" tests and deleting it I solved the problem. Hope that'll solve yours as well :)

**Comment by qk0106** [comment]
> > I got that as well. [#11755 (comment)](https://github.com/microsoft/playwright/issues/11755#issuecomment-1032413506)
> 
> Hi, check if in your `package.json` file you have the field `type:'module'`. I got that maybe for previous "trial and error" tests and deleting it I solved the problem. Hope that'll solve yours as well :)

I have `type:'module'` in package.json for other necessary purposes. Besides it was working fine with version 1.17.2. How come version 1.18.0 and 1.18.1 requires to remove `type:'module'`? That doesn't make sense to me.

**Comment by mrbrianevans** [comment]
I had the same error:
```
> playwright test

Using config at C:\Users\...\lib-testing\playwright.config.ts
Error: playwright.config.ts: Cannot import a typescript file from an esmodule.
```
with `"type": "module"` in package.json (because I am using es modules in the project).

Removing `"type": "module"` did indeed solve this problem with playwright, but as @qk0106 points out, there may be other necessary reasons for having `"type": "module"` in your package json. Seems strange that its incompatible with playwright?

**Comment by bbigras** [comment]
Maybe try nodejs 16 or earlier.

The fix and using `PW_EXPERIMENTAL_TS_ESM=1` didn't work for me with nodejs 14.

**Comment by asdf23** [comment]
I am now receiving this error after upgrading from 1.17.2 to 1.19.2

**Comment by rauleite** [comment]
Update to the 1.21 (alpha version).

`pnpm up @playwright/test@next`
`pnpm exec playwright install`

**Comment by jprinaldi** [comment]
> Update to the 1.21 (alpha version).
> 
> `pnpm up @playwright/test@next` `pnpm exec playwright install`

Upgrading to this version fixed this issue for me.

**Comment by silasabbott** [comment]
I updated to version **1.21.1** and also **1.22.0-alpha-apr-20-2022** and neither fixed this for me:

Node 16.14.2

using a fresh install of playwright with the example test throws:
```bash
Error: tests/example.spec.ts: Cannot import a typescript file from an esmodule.
```

**Comment by rauleite** [comment]
> I updated to version **1.21.1** and also **1.22.0-alpha-apr-20-2022** and neither fixed this for me:
> 
> Node 16.14.2
> 
> using a fresh install of playwright with the example test throws:
> 
> ```shell
> Error: tests/example.spec.ts: Cannot import a typescript file from an esmodule.
> ```
=/

I updated to 1.22.0-alpha-apr-9-2022 version and it still working.

**Comment by silasabbott** [comment]
Hmm... must be different problem then? Maybe in my `tsconfig.json`. Here's my environment:

- Node.js: **16.14.2** — *same issue in 16.11.x too*
- Typescript: **4.6.3**

#### tests/example.spec.ts
```ts
import { test, expect } from '@playwright/test'

...
```

#### package.json
```json
{
  "name": "app",
  "version": "0.1.4",
  "type": "module",
  "scripts": {

  },
  "devDependencies": {

  },
  "dependencies": {

  }
}
```

#### tsconfig.json — *generated by SvelteKit*
```json
{
  "compilerOptions": {
    "moduleResolution": "node",
    "module": "es2020",
    "lib": [
      "es2020",
      "DOM"
    ],
    "target": "es2020",
    "importsNotUsedAsValues": "error",
    "preserveValueImports": true,
    "isolatedModules": true,
    "resolveJsonModule": true,
    "sourceMap": true,
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true,
    "baseUrl": ".",
    "allowJs": true,
    "checkJs": true,
  },
  "include": [
    "./src/**/*.js",
    "./src/**/*.ts",
    "./src/**/*.svelte"
  ],
  "exclude": [
    "./node_modules/**",
    "./.svelte-kit/**"
  ]
}
```

**Comment by rauleite** [comment]
I think its not the tsconfig, the mine is auto generated by svelte-kit too. However I can see the generated tsconfig tomorrow morning, but if you want to see my repo, is this: https://github.com/rauleite/svelte-anime

It's basic starter project, created with `pnpm init vite@latest` and added some boilerplates to it.

**Comment by silasabbott** [comment]
So, I added a very basic `playwright.config.ts` and everything works perfectly now:
```ts
/** @type {import('@playwright/test').PlaywrightTestConfig} */

const config = { testDir: './tests/e2e' }
export default config
```

**Comment by asdf23** [comment]
I had this issue. My situation/resolution was the following. I had a
package.json with a setting of type=module. This didn't annoy playwright
and was compatible with other scripts in my directory. Some update in
playwright starting regarding this setting differently. So I changed my
other scripts and removed  the type parameter.
