### ISSUE TITLE
[Feature] - Show launch errors in dot reporter

### ISSUE THREAD

**Issue by ddoice** [microsoft/playwright#11751]
The dot reporter is the default for CI environments, but it does not show browser launch errors like this one :
![image](https://user-images.githubusercontent.com/14946058/151838642-6ac6a634-c2a7-4033-9945-35123fbd18e7.png)

These errors are vital to track down and resolve the root cause of the problem, otherwise you may spend hours wondering why some test are failing but Playwright does not save any artifacts.

**Comment by yury-s** [comment]
@ddoice can you share a same project where it reproduces? I tried a few examples and I do see the exception thrown from the dependency validator.

**Comment by ddoice** [comment]
@yury-s you are right, in our config the reporter was html not dot, I tried with the dot reporter and it shows the launch errors.

Anyway, in my humble opinion this release errors should be shown by all reporters, here's a public repo:

[Run with the html reporter](https://github.com/ddoice/playwright-dot-reporter-launch-errors/runs/5018103148?check_suite_focus=true) (error not shown)

[Run with the dot reporter](https://github.com/ddoice/playwright-dot-reporter-launch-errors/runs/5018136785)

**Comment by yury-s** [comment]
> @yury-s you are right, in our config the reporter was html not dot, I tried with the dot reporter and it shows the launch errors.

The html report should contain information about the error, you just need to save it as an artifact to access after CI run. We intentionally suppress extra output when running on CI. You can override this behavior by explicitly configuring reporters you want to run on CI, e.g. specify both dot and html:

```js
const config = {
  reporter: process.env.CI ? [['dot'], ['html']], 'html',
...

```
