### ISSUE TITLE
screenshot on failure capturing passing specs as well

### ISSUE THREAD

**Issue by CThompsonLifeTime** [microsoft/playwright#11757]
Hello, we are trying to capture screenshots automatically on failure.  This works but seems to also capture screenshots from other (passing) specs which are running in parallel.  We have 10 workers but seem to consistently get 6 other screenshots (of non-failing specs) along with the intended screenshot of our (temporarily purposefully) failing spec.

Is this a known issue or are we perhaps doing something wrong?  The only addition we made to light this up is the line in the config per to the docs:
`screenshot: 'only-on-failure'`

Thanks!

**Comment by yury-s** [comment]
This sounds like a bug, can you share a repro that we can try locally? Also what playwright version/os are you on?

**Comment by yury-s** [comment]
This looks normal, any chance you can share you repo or CI logs?

**Comment by CThompsonLifeTime** [comment]
Oh, my bad - we are actually on "playwright": "^1.18.1".  I'll look into the logs - doubtful we can share the repo unfortunately.  This behavior isn't blocking as we do get the screenshot of the failing spec (we just get others included as well).

**Comment by TimeInvestor** [comment]
Hi @CThompsonLifeTime 
It is because you create the page manually via
`page = await browser.newPage();` instead of using the page fixture. 
The solution is to close the page manually by calling `await page.close()` after each test.

**Comment by yury-s** [comment]
Yeah, that's a good point. You could do something like this if you don't want to write a fixture with proper tear down logic:

```js
test.beforeEach(async ({ page }) => {
  myPage = new FooPage(page);
  await myPage.goto();
})
```
Otherwise `await browser.newPage();` creates a new page in a new context before every test run and it will only be closed when the test worker shuts down and closes the browser.

**Comment by CThompsonLifeTime** [comment]
This solved our problem - thank you very much.
