### ISSUE TITLE
[Question] - Auto-Display HTML Report on CI

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#11773]
Hello guys, I was trying to execute some tests on azure pipelines, and noticed that the HTML Report "Show" was executed automatically   and immediately after the tests run, if something fails, that makes that job to hang, as the report is being generated on the server. Is there anyway to avoid this or is my configuration wrong ?
I just run npm test to execute: "npm run clean && npx playwright test"
And this is on my playwright.config.ts:
`reporter: ['html']`

Then if a test fails, it hangs showing this on CI

"Serving HTML report at http://127.0.0.1:9323. Press Ctrl+C to quit."

Any suggestion ? or what am I doing wrong ?
Thanks!

**Comment by mxschmitt** [comment]
Which CI are you using? Your CI does probably not set the common `CI=1` environment variable, if you set this one, it does not open.

Alternatively you can do: `reporter: [ ['html', { open: 'never' }] ],`

**Comment by imartinflores** [comment]
Hi @mxschmitt ,  I am using Azure Pipelines. I will try that and will see if it still happening. Thanks a lot for the suggestion!
Really appreciate it!

**Comment by israelKusayev** [comment]
`CI=true` Should solve it

**Comment by yury-s** [comment]
Please file a new issue and reference this one if CI=1 doesn't help.

**Comment by ranjCS** [comment]
I know it is late to ask a question, but I face the same issue, and I am using Azure pipeline. My question is where in azure pipleine I should write CI=1 to solve the problem?

**Comment by ilorwork** [comment]
`CI=1` or `CI=true` solves this problem

**Comment by calebq2010** [comment]
@ilorwork if you do not mind me asking where exactly did you add this value for CI=1?

**Comment by Sarkoutmahmoud** [comment]
For anyone wondering, the documentation on CI configuration can be found here: 

https://playwright.dev/docs/ci
