### ISSUE TITLE
[BUG] if using playwright.chromium.connect_over_cdp() and then calling page.route() about 30% of the time the function never returns/hangs forever

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright#11776]
**Context:**
- Playwright Version: 1.17.2
- Operating System: Windows
- 3.10.1
- Browser: Chromium

**Code Snippet**
```python
import re

from playwright.sync_api import sync_playwright
from string import ascii_letters
from random import choice

def block(route, request):
    route.abort()

with sync_playwright() as p:
    browser = playwright.chromium.connect_over_cdp(endpoint_url=ws, timeout=60000, slow_mo=20)
    context = browser.contexts[0]
    page = context.pages[0] if context.pages else context.new_page()
    page.route(re.compile("http(s)?://google.com/.*", block)
    page.wait_for_timeout(5000)
```

**Describe the bug**
It happens often, around 30% of the times - When calling page.route the function never returns and hangs there forever. Whatever is going wrong - for sure a timeout is missing there that should throw after an amount of time. - Sadly if this happens its also almost impossible to get back control.

EDIT: Meanwhile tested with sync and async version, happens with both.

**Comment by yury-s** [comment]
Looks related to https://github.com/microsoft/playwright/issues/10376.

@sla-te can you share full repro, including the page where it happens?

**Comment by sla-te** [comment]
@yuri-s The page does not matter in this case - It happens when connecting to an existing browser via websocket.

**Comment by yury-s** [comment]
I've run the following example with no issues:

```py
import re

from playwright.sync_api import sync_playwright

def block(route, request):
    print('block ' + request.url)
    route.abort()

with sync_playwright() as p:
    browser = p.chromium.connect_over_cdp(endpoint_url='ws://127.0.0.1:8192/devtools/browser/a253cef8-3022-48fa-becd-50d9ea04d1fa', timeout=60000, slow_mo=20)
    print('connected')
    context = browser.contexts[0]
    page = context.pages[0] if context.pages else context.new_page()
    page.route(re.compile("http(s)?://www.google.com/.+"), block)
    page.goto('https://www.google.com/')
    print('finished')
    page.wait_for_timeout(5000)
```

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
