### ISSUE TITLE
[Feature] Record tests in F#

### ISSUE THREAD

**Issue by xperiandri** [microsoft/playwright#11782]
It would be nice to be able to record tests in F# the same way as in C#. 
https://mcode.it/blog/2021-07-16-playwright/
Just substituting `await` with `do!` or `let!` and removing semicolons would be enough.
So the generator modifications look to be simple.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
