### ISSUE TITLE
[BUG] Html reporter is failing to open stderr

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#11780]
**Context:**
- Playwright Version: 1.18.1
- Operating System: mac
- Node.js version: 16
- Browser: chrome

https://user-images.githubusercontent.com/42112796/151983708-ec3b6833-2a59-4ad2-ac69-5b065df6fbd7.mov

**Comment by yury-s** [comment]
Can you share a report where it happens?

**Comment by israelKusayev** [comment]
[Playwright Test Report.html.zip](https://github.com/microsoft/playwright/files/7981867/Playwright.Test.Report.html.zip)


Inside the zip, there is an HTML file, click on the first failed test and you'll see it

**Comment by israelKusayev** [comment]
[Playwright Test Report.html.zip](https://github.com/microsoft/playwright/files/7981880/Playwright.Test.Report.html.zip)


Inside the zip, there is an HTML file, click on the first failed test and you'll see it

**Comment by israelKusayev** [comment]
sometimes I see double `stderr` 
![image](https://user-images.githubusercontent.com/42112796/152799863-5f1fbbc6-8ed2-4442-957b-2202b8847664.png)

**Comment by pavelfeldman** [comment]
Your zip file only contains one html file. You should zip entire `playwright-report` folder when you are sharing reports. They have data files for traces, output, etc. Without those files report does not work.

**Comment by israelKusayev** [comment]
I’m afraid that I’m not allowed to share these files
I’ll try to reproduce it in a new test project

**Comment by dgozman** [comment]
@israelKusayev Any luck with a repro?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
