### ISSUE TITLE
[Question] Can we pull dependecies for specific version of Playwright?

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#11783]
I am building a docker container to run playwright tests (written in .Net) from a clean ubuntu image to keep memory usage low. When I run `npx playwright install --with-deps chromium` is there a way to add a specific version to the end of that command like `--v 1.18.x` so that it downloads only browsers/dependencies matching the version I provided? This will allow me to avoid to keep tracking if my version of playwright matches with dependencies being downloaded.

**Comment by yury-s** [comment]
You can add version to the package name, e.g. `npx playwright@1.18.1 install --with-deps chromium`
