### ISSUE TITLE
[BUG] Position of element after scroll seems determined not correctly

### ISSUE THREAD

**Issue by btd** [microsoft/playwright#11804]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Mac
- Node.js version: 14.18
- Browser: Firefox and Chromium
- Extra: We are trying to test the same component in desktop and mobile version of site, mobile works fine but desktop failed. Only the difference is desktop version require scrolling

Sorry i tried to make reproducible test but failed.

**Describe the bug**

I attached traces for both mobile and desktop (sorry desktop too big to add there). 

When we run tests in headed mode in desktop it scrolls browser up and down and dies with timeout, we tried to reduce intercepting area, but it still point red dot on last entry of trace not in correct place.

[mobile.zip](https://github.com/microsoft/playwright/files/7985258/mobile.zip)
[desktop.zip](https://drive.google.com/file/d/1EZyLBfFNQOCFTIRaklLrJBT-noBE_7q_/view?usp=sharing)

I will still try to make reproducible example

**Comment by btd** [comment]
I tried to add { force: true } to the desktop .click and it helped. So to me it seems issue with scrolling

**Comment by yury-s** [comment]
In your log there is "<div class="TotalCostsGraphLabel TotalCostsGraph-labe…>…</div> intercepts pointer events", it looks like another element overlays the element you are trying to click (it's hard to tell which exact element is on the way maybe you can figure it out inspecting the page). You can adjust the point where playwright is trying to click by providing custom [position](https://playwright.dev/docs/api/class-locator#locator-click-option-position), will that work?

**Comment by btd** [comment]
@yury-s thanks for looking on this. I was trying to make reproducible example and found a real reason. 
Whole chart is a svg and icons where added via <image> tag, but 2 specific we tried to test were embedded as sub svg in <g> this caused container elements to expand and determine not correct position.
