### ISSUE TITLE
[BUG] `press` method should take a union of valid keys instead of a string

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11801]
https://github.com/microsoft/playwright/blob/b0daa7754fe257b08466662f6e43d3de523be61d/packages/playwright-core/types/types.d.ts#L2749-L2785

```ts
type FunctionKey = `F${1|2|3|4|5|6|7|8|9|10|11|12}`
type DigitKey = `Digit${1|2|3|4|5|6|7|8|9}`
type LetterKey = `Key${'A'|'B'|'C'|'D'|'E'|'F'|'G'|'H'|'I'|'J'|'K'|'L'|'M'|'N'|'O'|'P'|'Q'|'R'|'S'|'T'|'U'|'V'|'W'|'X'|'Y'|'Z'}`

type Key = FunctionKey | DigitKey | LetterKey | 'Backquote'| 'Minus'| 'Equal'| 'Backslash'| 'Backspace'| 'Tab'|
  'Delete'| 'Escape'| 'ArrowDown'| 'End'| 'Enter'| 'Home'| 'Insert'| 'PageDown'| 'PageUp'| 'ArrowRight'| 'ArrowUp'
```
i was going to make a PR and fix this myself, but as it seems this file is generated i'm not sure how

**Comment by mxschmitt** [comment]
How should this work if you can also combine keys like `await page.press('body', 'Shift+O')`?

Keep in mind that we need to stay TypeScript backwards compatible.

**Comment by DetachHead** [comment]
> How should this work if you can also combine keys like `await page.press('body', 'Shift+O')`?

```ts
type Keys<T extends string> = T extends Key ? T : T extends `${infer Head}+${infer Rest}` ? `${Head}+${Keys<Rest>}` : never

declare const press: <T extends string>(key: Keys<T>) => Promise<void>

press('F1')
press('Shift+KeyO')
press('invalid') //error
press('F1+invalid') //error
```

[playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYgrgOwMbAJYHsEGkIigXigAMYASAbwEYoAfKAJlqgGYmAWJgViYDYmB2JgA4mATiaUADBOp1K9AL5EAUKEhQAIqgDmqYDjyEiW3cAqyGTVnQ51udPnUF0RdUUtXhoAGQjBgEABOBgTEBhQA5ACCEUwRAEKxdBEAwklQERrpEQCi2TDZAOLZABLZAJLZAFLZWNne2QCy2QBy2QDy2QAK2QCK2QBK2QDK2QAq2QCq2QBq2QDq2QAa2QCa2QBaER6e6iGE8MhomCF0JnqnUL7+QZcJAIZIANYAjnDoAU2oCHAAztk5N73AA22Xijyev2B91+AAswRDfmBHhBxvcAEZJZRQHEZDQQYF+VFxHK-JD3SDZKKBQLoADuGnpCABCAAJiyAoFSugALbE5LlBC-ILAbr3bQQRl05lxLriiCTMBUmn0gY6WGiuLU2l0xURZS7aAGX4AHjGUAgAA8AmzflBfsBAt9tAA+ULmq021l2kIAfig5oAXAGLdaILbiBRvgAzIJQEoQe6shQAaijCFjgSgAwgDqUUH9RAoCaTqYoxpNOYdLvzwYQEAAbkEDayIEhoYFoEhMA6oGBO79fsGzaGvXaHU6EK6ABRPXDBitjF0ASgIbq6tJ5qGFJob6FQrJdBv7ud+04iMEoEWXyhPg-Pw1hqGjwBTBk6N7vZ4i3wbIIP15QAA9EBQS0oEt4Dt+l4pr+-7squIFgeggRAA)


> Keep in mind that we need to stay TypeScript backwards compatible.

we can use [`typesVersions`](https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#version-selection-with-typesversions) to maintain compatibility with old versions of typescript while still adopting features from later versions

**Comment by mxschmitt** [comment]
Yeah thats not worth the complexity and what the users get from it. Closing it by that.

**Comment by DetachHead** [comment]
i don't really think this is all that complicated. features like template literal types and recursive conditional types were designed for situations like this. i think it's a waste not to take advantage of them because they're some of the most impressive aspects of the language.

there are plenty of widely used libraries that use them in much more complex ways than this, like [express](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/express-serve-static-core/index.d.ts#L106-L120)
![image](https://user-images.githubusercontent.com/57028336/152455294-a50c16d6-47e7-461f-a953-0359933d798b.png)
