### ISSUE TITLE
[Question] Way to skip global setup for selective tests?

### ISSUE THREAD

**Issue by AmareshKulkarni** [microsoft/playwright#11809]
My application has account signup workflow and a number of workflows after user logs in. Following the documentation, I was able to use global setup for authentication and re-use across all tests. However, I don't need authentication for the actual account signup flow.

Is there a way to skip global setup that involves login for the account signup tests or conditionally execute global setup if the test being run is account signup related?

**Comment by yury-s** [comment]
> Is there a way to skip global setup that involves login for the account signup tests or conditionally execute global setup if the test being run is account signup related?

Global setup runs once before all tests. Do you run authentication and signup flows in one and the same project?

You can try something [like this](https://playwright.dev/docs/test-auth#multiple-signed-in-roles) to only load authenticated state in the tests that require authentication and not load it for signup ones. Will it work?

**Comment by AmareshKulkarni** [comment]
Thank you for the quick turnaround. I can run them (signup and sign-in) in separate _playwright projects_, but they are both in the same codebase. Is there a way to configure the global setup per playwright project? That should help my scenario.

The link provided looks like is for a situation when a user needs to be logged in multiple times (per role), but in my case, it is more like the user may not even exist. They will start with the sign-up, and then move onto login to perform various other functions.

**Comment by yury-s** [comment]
It is one `globalSetup` per config currently. No per-project options and project name is not available to the globalSetup (note that you single playwright run may execute multiple projects). You could split your config into two with two different global setups, it is somewhat inconvenient though.

**Comment by AmareshKulkarni** [comment]
Thank you. I will for now use a different configuration file for signup flow

_-c <file> or --config <file>: Configuration file. If not passed, defaults to playwright.config.ts or playwright.config.js in the current directory._

**Comment by aslushnikov** [comment]
@dgozman global fixtures should help here.

**Comment by evanfuture** [comment]
I did it this way:
```
const context = await browser.newContext({ storageState: { cookies: [], origins: [] } });
  const page = await context.newPage();
  await page.goto('/');
// auth context removed
```

**Comment by evanfuture** [comment]
Found an even easier way, just drop this into your describe block or above your tests:
```test.use({ storageState: { cookies: [], origins: [] } });```

**Comment by sowji-elligo** [comment]
This worked for me, Thanks!

**Comment by DanielStoica85** [comment]
> Found an even easier way, just drop this into your describe block or above your tests: `test.use({ storageState: { cookies: [], origins: [] } });`

But this will still run the globalSetup once before your tests, no? Just that it won't use what's inside `stirageState.json` file anymore.

**Comment by Camo30** [comment]
@yury-s
Is there a reason why

```TS
test.use({ storageState: undefined });
```

does not act like

```TS
test.use({ storageState: { cookies: [], origins: [] } });
```

I thought the first would also override the storage state from global configuration but that does not work. I would prefer the first one because it is even shorter. Are there other use cases for `undefined`?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by Silverium** [comment]
I have another case that could be studied.

### Environment
- I have 3 different accounts with different roles.
- I use the vsCode extension
### Flow
I run a specific test for the first time, which has as a dependency the `auth.setup.ts` file. It saves the needed `storageState` for each of the three roles.

Second time I run the specific test, the `storageState` could be reused, and all `auth.setup.ts` tests are in fact overwriting the existing files. 

### Expected
Conditionally run the `auth.setup.ts` if `storageState` files are already present. Or at least in some way to be able to skip them from the vsCode interface.

### Workaround
Of course, we could setup an env file to add or remove the dependency:
```ts
// playwright.config.ts
  projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: !!process.env.SKIP_SETUP? [] : ['setup'],
    },
...
```
But maybe there is some more elegant way to do that?

**Comment by dgozman** [comment]
@Silverium You can manually check that `fs.existsSync(storageStateFilePath)` in the `auth.setup.ts` and just return from the test function. If that does not work, please file a new issue so that we can take a look.

**Comment by Silverium** [comment]
> @Silverium You can manually check that `fs.existsSync(storageStateFilePath)` in the `auth.setup.ts` and just return from the test function. If that does not work, please file a new issue so that we can take a look.

That's indeed faster and a less messy DX.

Now when the developer wants to re-write the files generated in the `auth.setup.ts`, it will be enough to delete the `.auth` folder (with the files inside) or any of the generated files.

**Comment by alkhachatryan** [comment]
> Found an even easier way, just drop this into your describe block or above your tests: `test.use({ storageState: { cookies: [], origins: [] } });`

Briliant!
