### ISSUE TITLE
[Question] Can I require a npm module where the module itself is a fixture?

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#11817]
Hi,

I'm new with npm modules development so, maybe this question just describing a tech-gap. 
Anyway, I would appreciate your help:

I would like to develop a module for some tool I'm building (Hopefully it can be useful when finished to the PW community) 
The module is basically a fixture (overriding the page fixture).

I would like to require this module (as npm module) in my project. 

It looks like this:
```
// npm module name: check-coverage

// fixture.js
const base = require('@playwright/test');
exports.test = base.test.extend({
  page: async ({ page }, use) => {
    await page.addInitScript({ content:`${scriptContent}` });
    await use(page);
}

// index.js
module.exports = require('./fixture.js');
```

In **my project** (where I want to require this module) I'm using it like this:
```

// baseFixture.js
const { test } = require("check-coverage");  //Pay attention to the module name
exports.test = test.extend({
  todoPage: async ({ page }, use) => {.   //Here I expect that the page is the override page fixture I created in the npm module 
    const todoPage = new TodoPage(page);
    await use(todoPage);
  },
});

```

When I'm trying to execute my tests, I'm getting the following error:

```
Error: Requiring @playwright/test second time,
First:
Error
```

I do require @playwright/test in other files in my project but I'm getting this error only when trying to require my npm module.
I would really appreciate any assistance

**Comment by yury-s** [comment]
You have two versions of `@playriwright/test` one inside `check-coverage` module and the other inside the one that uses it. You need to make sure that only one is used (currently one is imported in playwright.config.js and the other in the fixture.js). Once you publish the extension and import it from the second module the error should disappear as you will have only one copy of `@playwright/test`

**Comment by hananmalka** [comment]
Thanks for the response @yury-s 

Few questions: 

1. Is it just versions in-compatible? Let's say both are the same version - will it work?
2. How It is going to be solved when I will publish the extension? I will still import `@playwright/test` in the npm module.
3. How can I control that only one is used?

Thanks again

**Comment by yury-s** [comment]
> 1. Is it just versions in-compatible? Let's say both are the same version - will it work?

No, even if it's the same version only one instance should be used the exception will be thrown even for the same version imported from two different places.

> 2. How It is going to be solved when I will publish the extension? I will still import `@playwright/test` in the npm module.

Your module `check-coverage` should only have `@playwright/test` in its `devDependencies`. The module which contains the tests and depends on check-coverage will specify both as its dependencies, so `@playwright/test` will be a peer dependency. (you could also add it as `peerDependency` to the `check-coverage` but it may just make things more complicated).

> 3. How can I control that only one is used?
> 

You don't add it to `dependencies` section of package.json in `check-coverage`

**Comment by hananmalka** [comment]
Thanks @yury-s 
Following your instructions, this is how my files looks like now but it's still not working with the same error. 
Please help me know what am I doing wrong? 

> Your module `check-coverage` should only have `@playwright/test` in its `devDependencies`. The module which contains the tests and depends on check-coverage will specify both as its dependencies, so `@playwright/test` will be a peer dependency and will also be available to `check-coverage` (you might also add it as `peerDependency` to the `check-coverage` but it may just make things more complicated).
> 
> >

```
// check-coverage module

// package.json
"devDependencies": {
    "@playwright/test": "^1.18.1"
  }

// fixture.js
const base = require('@playwright/test');  // I must require base as I extending "test"
exports.test = base.test.extend({
  page: async ({ page }, use) => {
    await page.addInitScript({ content:`${scriptContent}` });
    await use(page); 
  } 
})
```

In my project: 

```
// package.json
"dependencies": {
    "@playwright/test": "^1.18.1",
    "check-coverage": "file:../check-coverage"
}

// baseFixture.js
const { test } = require("check-coverage");  //I'm not requiring @playwright/test here but in other files in my project
exports.test = test.extend({
  todoPage: async ({ page }, use) => {
    const todoPage = new TodoPage(page);
    await use(todoPage);
  },
});
```

> You don't add it to `dependencies` section of package.json in `check-coverage`

I tried also this one as well, but I got an error in my project said: "base" is not defined.

**Comment by pavelfeldman** [comment]
This works for me just fine!

**Comment by hananmalka** [comment]
@pavelfeldman, I'm getting with the above case the following error:
`describe() can only be called in a test file`

See #11889.

**Comment by pavelfeldman** [comment]
You are only getting this error if you have more than one playwright installed. Try creating a self-contained example with what you are describing and it'll work. You probably have some stale `node_modules` folder inside your check-coverage module.

**Comment by hananmalka** [comment]
Tried that. Unfortunately I'm still getting this error.
I even deleted the node_modules directory in both check-coverage module and in my project and re-run `npm install`, but the same error still exist.

I tried to require the check-coverage module in other project I'm using - Still same error: 
`describe() can only be called in a test file`

**Comment by pavelfeldman** [comment]
Mind sharing a .zip file or an example repo wth your reproduction?

**Comment by hananmalka** [comment]
@pavelfeldman 
Attached .zip file with my reproduction - 
[ExamplesForFixtureRequire.zip](https://github.com/microsoft/playwright/files/8054435/ExamplesForFixtureRequire.zip)

Few notes:

1. Project name is: playwright-ex
2. Custom module name: my-custom-module-pw
3. I used playwright version 1.19.0 (The error still happens there)
4. Running `npx playwright test` from the project should provide the mentioned error

Please let me know if you manage to reproduce.

**Comment by hananmalka** [comment]
Hi @pavelfeldman

Did you have the chance to reproduce it?

**Comment by dgozman** [comment]
@hananmalka This happens because you use relative path for the module, and both `playwright-ex` and `my-custom-module-pw` have a copy of `@playwright/test` in their own `node_modules` folder.

Presumably, you've installed `my-custom-module-pw` with `npm install ../my-custom-module-pw`. I'd recommend to do the following:
```bash
cd my-custom-module-pw
npm pack
cd ../playwright-ex
npm i ../my-custom-module-pw/my-custom-module-pw-1.0.0.tgz
```

This way, you'll get a copy of `my-custom-module-pw` like your end users would, and it will share `@playwright/test` with the `playwright-ex` package like it would in the real life.

**Comment by hananmalka** [comment]
Thank you very much @dgozman - It does works!
Amazing support for an amazing framewrok

**Comment by BenZionHasidaNice** [comment]
> @hananmalka This happens because you use relative path for the module, and both `playwright-ex` and `my-custom-module-pw` have a copy of `@playwright/test` in their own `node_modules` folder.
> 
> Presumably, you've installed `my-custom-module-pw` with `npm install ../my-custom-module-pw`. I'd recommend to do the following:
> 
> ```shell
> cd my-custom-module-pw
> npm pack
> cd ../playwright-ex
> npm i ../my-custom-module-pw/my-custom-module-pw-1.0.0.tgz
> ```
> 
> This way, you'll get a copy of `my-custom-module-pw` like your end users would, and it will share `@playwright/test` with the `playwright-ex` package like it would in the real life.

@dgozman In this solution, we need also update the module in the package.json?

**Comment by msieorbus** [comment]
> @hananmalka This happens because you use relative path for the module, and both `playwright-ex` and `my-custom-module-pw` have a copy of `@playwright/test` in their own `node_modules` folder.
> 
> Presumably, you've installed `my-custom-module-pw` with `npm install ../my-custom-module-pw`. I'd recommend to do the following:
> 
> ```shell
> cd my-custom-module-pw
> npm pack
> cd ../playwright-ex
> npm i ../my-custom-module-pw/my-custom-module-pw-1.0.0.tgz
> ```
> 
> This way, you'll get a copy of `my-custom-module-pw` like your end users would, and it will share `@playwright/test` with the `playwright-ex` package like it would in the real life.

just question, do you install @playwright/test as a "normal" dependency or dev ?

**Comment by pfteter** [comment]
it works in a hoisted monorepo with for example npm workspaces or as a exported package but not with lerna / symlinks or hard links
