### ISSUE TITLE
[Feature] open report in a new port

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#11818]
Is it possible to give the option to open the report on a new port when there is another report running on the default port?

(Something similar like create react app)

<img width="650" alt="34147F4D-EA2D-42A4-AC52-DB1585B870EF" src="https://user-images.githubusercontent.com/42112796/152232858-5bcb2702-43b2-4fce-9c1a-534014bb089e.png">

**Comment by yury-s** [comment]
No, there is no. We suggest you load traces in the web viewer (https://trace.playwright.dev/) if you need  to see more than one.

**Comment by israelKusayev** [comment]
I’m talking about the html reporter, not just the trace viewer
This is a slightly different case

**Comment by yury-s** [comment]
Oh, i see

**Comment by AmsterGet** [comment]
It would be nice to be able to confidurate this to avoid port collisions for multiple reporters.

**Comment by A-ZC-Lau** [comment]
Would be nice to configure it in `plawright.config` so we can have multiple reports for multiple repos

**Comment by eoinomeara11** [comment]
Adding to playwright config would allow different ports to be used for normal testing and experimental component testing

**Comment by jaward916** [comment]
Just hit a scenario where I needed this exact feature, got a couple of newbies learning Playwright and doing so on a remote server, when running their tests they are clashing with each other on the reports trying to run, would be great to be able to configure this so they can't clash!

**Comment by zepatrik** [comment]
I am not sure if you are all talking about `npx show-report` but that apparently got a flag to specify the port: https://github.com/microsoft/playwright/commit/c3cff485d11979da8ba65f6fc3bf8bb03249c9f4

I recommend to run `npx playwright show-report --port 0` for anyone who does not yet know that trick, as the port `0` is some random free port determined by the system.

**Comment by mxschmitt** [comment]
closing as per above. `port=0` is the recommended way.
