### ISSUE TITLE
[Question] How to pass data from a test to a custom reporter?

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#11813]
I am using playwright-test, and have a custom reporter setup, trying to get some data from the test and use it for inserting into a Database.
Is it possible to pass data from the test to onTestEnd hook of the reporter?

**Comment by yury-s** [comment]
You can use [testInfo.attachments](https://playwright.dev/docs/api/class-testinfo#test-info-attach) to save some information in tests and then read it from [testResult.attachments](https://playwright.dev/docs/api/class-testresult#test-result-attachments) in the test reporter.
