### ISSUE TITLE
`request.isNavigationRequest()​` gives `true` for html request in `object` tag

### ISSUE THREAD

**Issue by aromalanil** [microsoft/playwright#11828]
### Discussed in https://github.com/microsoft/playwright/discussions/11827

<div type='discussions-op-text'>

<sup>Originally posted by **aromalanil** February  3, 2022</sup>
Was trying to block all html requests other than the html request for mainframe. 

So, as per the docs I used `request.isNavigationRequest()` to identify if it is a request for mainframe or not. If not, that request was blocked.

But some how one page had an `object` tag with data attribute pointing to an html document. The request for that html document gave `true` for `request.isNavigationRequest()`

I just wanted to know why is this happening and is this a default behaviour. If yes, how can I solve this issue.</div>

**Comment by yury-s** [comment]
`isNavigationRequest()` will return true for iframe navigation requests (not only main frame), if you want to check that this is the main frame navigation request you can additionally compare [request.frame()](https://playwright.dev/docs/api/class-request#request-frame) with the page's main frame object.

**Comment by AraCoders** [comment]
Hi @yury-s,
as per the docs: "Some navigation requests are issued before the corresponding frame is created, and therefore do not have request.frame() available." at https://playwright.dev/docs/api/class-request#request-frame 
so if we tried to compare request.frame() it will throw error. so how can we handle this? 
should we just assume that it's always NOT a main frame navigation ? or adding a delay until frame is attached?
any suggestion ?
