### ISSUE TITLE
[Feature] Allow set a user-agent in playwright config file

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#11829]
It will be nice if we can pass userAgent in PW config file, instead of only passing it within newContext

`        context = await browser.newContext({userAgent: ''});
`

**Comment by yury-s** [comment]
It is already possible via [contextOptions](https://playwright.dev/docs/api/class-testoptions#test-options-context-options):

```js
const config = {
  ...
  use: {
    contextOptions: {
      userAgent: 'Foo'
    },
  }
};

```
