### ISSUE TITLE
[Question] Tests do not run on Electron 16,17

### ISSUE THREAD

**Issue by takashikatayama2021** [microsoft/playwright#11823]
I use Playwright for e2e testing of applications developed with Electron + vue.
Up to Electron15 I was able to run the test without any problems
Tests can no longer be run after Electron16.
I suspect it's probably because the Chrome version went up to 96, but are there any possible causes and remedies?
I am in trouble because there is no error log.

■ Current environment
Node : 16.9.1
Electron: 16.0.8
vue : 2.6
playwright: 1.16,1.17,1.18(The problem has been reproduced in all versions)

■ Test configuration
Use two consoles
Launch Electron headless on one console
>vue-cli-service electron: serve --headless --mode development

Launch e2e tests implemented with Playwright on two consoles
This will bring up the application window
The e2e test implemented by Playwright is executed.

■ Implementation on the Playwright side
>const app = await electron.launch ({{
> args: ['dist_electron'],
> timeout: 0,
>});

**Comment by yury-s** [comment]
> Tests can no longer be run after Electron16.

Can you clarify what exactly is not working?

A few examples I tried all work in Electron 16.0.8 we need full reproduction scenario which we could repeat locally, otherwise it's hard to give a meaningful advice. Perhaps something changes in Electron and that broke your app?

> Use two consoles
> Launch Electron headless on one console

Why is this important, do you connect to it remotely?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
