### ISSUE TITLE
[Feature] show warning when opening trace in different browser to the one it was recorded in

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#11825]
when testing a site that's only accessible on a local network, the snapshots in the trace files are often quite useless due to css/fonts/etc being no longer accessible.

this is especially a problem when using https://trace.playwright.dev, as CORS prevents loading any of these resources regardless:
![image](https://user-images.githubusercontent.com/57028336/152277735-050a5648-68f6-4c61-819e-64b25a85fb17.png)

**Comment by yury-s** [comment]
Can you provide an example page where this is happening?

**Comment by yury-s** [comment]
Playwright will save into the trace file fonts and css files that the page actually loaded. It may happen that you record trace on one machine/platform where the code path loading the fonts from the log is not triggered but then you open the trace file and the same page tries to load missing fonts as the host platform is now different (it might be that the page loads different fonts depending on different DPI, host platform etc).

Are you opening the trace on the same machine where you record it?

**Comment by DetachHead** [comment]
> Can you provide an example page where this is happening?

Unfortunately i can only reproduce it on the internal site i'm testing, which i can't share publicly

> Are you opening the trace on the same machine where you record it?

yeah. however would that apply when opening the trace on trace..playwright.dev as well as with the `playwright show-trace` command?

**Comment by yury-s** [comment]
Web version will have similar problem, if the browser runs on a different platform than where the trace was recorded then the page may lack some of the fonts for that platform and will start downloading them (this is because we save only actually downloaded resources not everything that the page could potentially load).

**Comment by DetachHead** [comment]
ah i see now. i was opening the trace in firefox but ran the test in chrome. when opening it with the same brower the test ran on  everything seems to load fine

thanks

**Comment by DetachHead** [comment]
actually, perhaps the trace viewer could show a warning if the trace was opened with a different browser?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
