### ISSUE TITLE
[Question] Page size does not follow browser window changes?

### ISSUE THREAD

**Issue by CodingOctocat** [microsoft/playwright#11832]
As shown in the picture:

![微信截图_20220203201904](https://user-images.githubusercontent.com/7220248/152341663-da90bfe7-bde7-451f-bbbb-3878359ba9a3.png)
![微信截图_20220203201953](https://user-images.githubusercontent.com/7220248/152341666-4c4a7883-4c10-402c-ab5e-0f55fca5f15d.png)

**Comment by yury-s** [comment]
Playwright emulates viewport and the emulated size is preserved even if you resize the window. You pass desired size to the [`newContext`](https://playwright.dev/docs/api/class-browser#browser-new-context) or call [`page.setViewportSize`](https://playwright.dev/docs/api/class-page#page-set-viewport-size) to change the it later.
