### ISSUE TITLE
[BUG] Test steps in page objects cause failures in global setup

### ISSUE THREAD

**Issue by justinebateman** [microsoft/playwright#11835]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Mac
- Node.js version: 14.17.3
- Browser: Chromium

**Code Snippet**

```javascript
async clickLoginButton(): Promise<void> {
    await test.step("Click Login button in header", async () => {
      await this.page.locator("button[aria-label='Click to login']").click();
    });
  }
```

**Describe the bug**

Test steps in page objects work great when used inside a test. However, we use our page objects inside a global setup to login and set storage state for the tests. 

```javascript
async function e2eGlobalSetup(config: FullConfig): Promise<void> {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  if (baseURL != null) {
    await page.goto(baseURL);
  }
  const homePage = new HomePage(page);
  await homePage.header.clickLoginButton();
  // other steps...
}
```

If we use the function inside our global setup we get an error 

```
test.step() can only be called from a test
```

which is understandable. To work around this error is it possible to check if the testInfo is null/undefined and if it is then just execute the action and don't log the step?

The error is thrown here - https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/testType.ts#L208

It would save us having to duplicate our selectors and steps outside our page objects

Thank you!

**Comment by yury-s** [comment]
This would hide potential bugs where `test.step` is misused, also there is no point in using test.step inside `globalSetup` as it doesn't log anywhere. If you'd like to avoid duplicate selectors you could wrap the code into `test.step` in the POM methods conditionally on whether it's in a worker ([`process.env.TEST_WORKER_INDEX`](https://playwright.dev/docs/api/class-testinfo#test-info-worker-index) is defined) or in the global setup:

```js

async clickLoginButton(): Promise<void> {
    const doClick = async () => {
      await this.page.locator("button[aria-label='Click to login']").click();
    }
    if (process.env.TEST_WORKER_INDEX)
      await test.step("Click Login button in header", doClick);
    else
      await doClick();
  }
```

Or just extract the callback you pass into test.step into a separate method and call it from the globalSetup:

```js
async clickLoginButton(): Promise<void> {
      await test.step("Click Login button in header", () => this.clickLoginButtonImpl());
}

// globalSetup should call this method
async clickLoginButtonImpl(): Promise<void> {
      await this.page.locator("button[aria-label='Click to login']").click();
}
```

Will this work 

I'm closing the request as we are not planning to change this behavior.

**Comment by justinebateman** [comment]
Thank you! I can work with your suggestions ⭐
