### ISSUE TITLE
[Question] Is there an option to choose element by providing an array of text values?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#11836]
Hi there.

I have a table element that contains rows.
Each row (tr element) contains cells (td element).

![image](https://user-images.githubusercontent.com/52656401/152353238-abbdc709-5994-496d-8bba-d5a7b1bc82a0.png)

Is there an option to choose a row by providing an array of text in cells in the same row?

For example: 
`await page.locator('tr', {hasText: 'text1', hasText: 'text2'}).click()`

**Comment by yury-s** [comment]
You can concatenate the strings, playwright will automatically match the text across child nodes: `await page.locator('tr', {hasText: 'text1 text2'}).click()`, e.g.:

```js
test('should work across cells', async ({ page }) => {
  await page.setContent(`<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
  </tr>
  <tr id=2>
    <td>Peter</td>
    <td>Griffin</td>
  </tr>
  <tr id=3>
    <td>Lois</td>
    <td>Griffin</td>
  </tr>
</table>
`);

  expect(await page.locator('tr', { hasText: 'Peter    Griffin' }).evaluate(e => e.id)).toBe('2');
});

```
