### ISSUE TITLE
[BUG] https://itogo.ru/ does not opened with webkit 

### ISSUE THREAD

**Issue by SpiderZZZ** [microsoft/playwright#11837]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Node.js version: 14.17.3
- Browser: WebKit 1596

**Describe the bug**

https://itogo.ru/ does not opened in WebKit. Console log:
![image](https://user-images.githubusercontent.com/18137237/152356249-63ab38df-c4b5-41bc-a603-3d7daa2229fc.png)
TypeError: The SVHElement onload getter can only be used on instances of SVGElement

Chrome, firefox worked fine

**Comment by yury-s** [comment]
I can reproduce it, looks like something is not working in WebKit Windows (I can open the page on macOS and Linux in WebKit just fine). @fujii maybe you know off top of your head?

**Comment by fujii** [comment]
I have no idea. Filed the bug in the upstream WebKit Bugzilla. Any patches or hints are welcome.
https://bugs.webkit.org/show_bug.cgi?id=236097

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/12823
