### ISSUE TITLE
[Feature] opt-out of element state check after click in page.(un)check()

### ISSUE THREAD

**Issue by Octopus134** [microsoft/playwright#11842]
I use `page.uncheck().`
according to docu this does: ... 7.Ensure that the element is now unchecked. If not, this method throws. ...

If the dropdown with the checkbox closes immediately after checking intentionally, then the test (of the page,uncheck()) afterwards fails.
I can use click() instead, but the charme of having check()/uncheck() is that the result is defined other than by click() - even if not tested afterwards. So I like to have an option to disable the after-unchecking check.

**Comment by yury-s** [comment]
Related issue: #11026

**Comment by yury-s** [comment]
This is an edge case and I'd recommend you just use click to bypass the check. Will keep the request open to see if there is more interest in this feature.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
