### ISSUE TITLE
[Feature] Option to set the host for playwright show-report

### ISSUE THREAD

**Issue by ashwinmenkudle** [microsoft/playwright#11846]
If you are using playwright in wsl2 environment then the playwright show-report command does not work as expected.
The browser running on windows 11 will not reach the page at http://127.0.0.1:9323.
Either server should start with 0.0.0.0 host or the show-report should have the option to set host
![wsl2-issue](https://user-images.githubusercontent.com/5318013/152412294-4da11971-d388-4235-b44d-255815403f5e.gif)
.

**Comment by yury-s** [comment]
Please tell us more about your setup. Do you run playwright tests under Linux container in wsl2 and then want to see the report on the host Windows machine? If so and the report files are available on the host filesystem then it should just work, you might have a firewall blocking the local port.

**Comment by ashwinmenkudle** [comment]
Setup: Windows 11 running wsl2 with ubuntu os.
I am running test inside wsl2 environment.

show-report command I guess just serve static pages and the server starts with host 121.0.0.1.
Traffic from the ubuntu will be able to reach server. From windows machine this will not be reachable.

**Comment by yury-s** [comment]
`show-report` starts the local server and opens the browser on the machine where you run the command. The error means that the localhost port is not accessible to the browser running on the same OS.

It looks like you are running `show-report` in the host machine and the port is just blocked by firewall there, can you check that?

**Comment by ltsuda** [comment]
try using `http://localhost:9323` instead of loopback IP (127.0.0.1)

**Comment by ashwinmenkudle** [comment]
@ltsuda `http://localhost:9323` address worked did work for me.

Is that possible to detect OS and open the http://localhost:9323 address instead of `http://127.0.0.1:9323/`

**Comment by yury-s** [comment]
Merging into #11568
