### ISSUE TITLE
[BUG] expect.assertions() and expect.hasAssertions() Not Working

### ISSUE THREAD

**Issue by Zehua-Chen** [microsoft/playwright#11845]
**Context:**
- Playwright Version: 1.18.0
- Operating System: Mac
- Node.js version: v16.13.0
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from "@playwright/test";

test.describe("foo", () => {
  test("boo", () => {
    expect.hasAssertions();
  });
});

test("boo", () => {
  expect.assertions(2);
});
```

**Describe the bug**

In `Jest`, `expect.assertions` and `expect.hasAssertions` can be used to ensure at least a number of assertions is performed. This is especially helpful for playwright, as many `Page`'s API is in the form of `page.on("event", () => {})`. 

However, these APIs do not work in playwright. The couple of tests above should trigger errors but do not trigger any errors.

**Comment by yury-s** [comment]
Merging into #11734
