### ISSUE TITLE
[Feature] playwright init should support a non-interactive mode with arguments specified on the command line.

### ISSUE THREAD

**Issue by EvanCarroll** [microsoft/playwright#11843]
* `npm init playwright` runs an interactive program that initializes a playwright project.
* CI doesn't work well with interactive prompts
* There is no supported method to run `npm init` without interactivity.

It would be nice if

* users could run `npx create-playwright --lang TypeScript --dir tests --github --install-deps` to specify or override all the default options explicitly in the command line.
* users could run `npx create-playwright -y` or `--yes` (which is the convention for [`npm init`](https://docs.npmjs.com/cli/v8/commands/npm-init)) to disable interactive prompting and accept all the defaults

**Comment by bitdeft** [comment]
And updates on this?

**Comment by deviantintegral** [comment]
I ran into this working on integrating Playwright with ddev. For tests, we need to commit a playwright skeleton as a fixture instead of initializing it from latest. I would have preferred to have the option to run `npm init` at least in HEAD tests to know if anything has broken upstream.

https://github.com/deviantintegral/ddev-playwright/pull/1

**Comment by dmoughabghab** [comment]
Agree we need this

**Comment by mxschmitt** [comment]
This is already there, see:

```
Usage: npx create-playwright@latest [options] [rootDir]
    Available options are:
      --help: print this message
      --browser=<name>: browsers to use in default config (default: 'chromium,firefox,webkit')
      --no-browsers: do not download browsers (can be done manually via 'npx playwright install')
      --install-deps: install dependencies (default: false)
      --next: install @next version of Playwright
      --beta: install @beta version of Playwright
      --ct: install Playwright Component testing
      --quiet: do not ask for interactive input prompts
      --gha: install GitHub Actions
      --lang=<js>: language to use (default: 'TypeScript'. Potential values: 'js', 'TypeScript')
```

We use it e.g. for the VSCode integration when creating projects: `npm init playwright -- --quiet --install-deps --gha --browser chromium`

**Comment by deviantintegral** [comment]
I could have sworn I looked for CLI parameters before, but this doesn't look to be a new feature... so 🤷 ? Thanks for the update.

But I have a thought. Even with a parameter, you have to specify `--quiet` for a question to be ignored.

```
❯ npx create-playwright@latest --lang=TypeScript
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
? Do you want to use TypeScript or JavaScript? …
❯ TypeScript
  JavaScript

# Hangs here...
```

I think I probably read `--quiet` without reading the description. Usually `--quiet` means to suppress logging output, not to change anything in terms of interactivity.

@mxschmitt shall I file a new issue with details?

**Comment by andy-lcm** [comment]
I agree with @deviantintegral   `--quiet` seems wrong here. Suggestion: `--defaults` should provide non-interactive mode, accepting defaults for all values which were not specified on the command line. `--quiet` should reduce the amount of output in some way.
