### ISSUE TITLE
[Feature] Locator.waitFor should be chainable

### ISSUE THREAD

**Issue by tirli** [microsoft/playwright#11847]
Currently `locator.waitFor` returns void therefore it is not possible to chain several calls.
Right now I have a code like this:
```js
const button = page.locator('button')
await button.waitFor()
expect(await button.isVisible()).toBeTruthy()
```
But I would rather have it like this:
```js
expect(await page.locator('button').waitFor().isVisible()).toBeTruthy()
```

Or is there a reason why `waitFor` doesn't return anything?

P.S. I don't use `@playwright/test` therefore I cannot just use `expect(locator).toBeVisible()`. And even with it having `waitFor` on a separate row is required.

**Comment by yury-s** [comment]
> Or is there a reason why `waitFor` doesn't return anything?

You usually don't need `waitFor`, most of the methods (click etc) will wait automatically. For others if you expect the condition to become true eventually we recommend web-first [assertions](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible) which will wait until the condition is satisfied.

> And even with it having `waitFor` on a separate row is required.

The idea is that `toBeVisible` will automatically wait and throw if the condition is not met within timeout. This is our recommended approach for uses cases like you described.

Closing this request as it is covered by [web-first assertions](https://playwright.dev/docs/test-assertions).

**Comment by yury-s** [comment]
> Since it is announced that it is possible to use only the library, I don't think that coverage in another package could be a solution.

It is possible to use library separately but some of the features are only a part of playwright test. Similarly some of the features are not available in other languages.
