### ISSUE TITLE
[BUG] `launchServer()` works inconsistently across Playwright versions

### ISSUE THREAD

**Issue by rinogo** [microsoft/playwright#11855]
## Context
- Playwright Version: Various (See Issue)
- Operating System: Linux
- Node.js version: 14.19.0
- Browser: Chromium

## Bug

In our application, we start up **four** Playwright "servers" using `launchServer()`. Each of these servers is configured with different behavior for our application:

```
this.browserServer = await this.playwright["chromium"].launchServer(settings);
wsEndpoint = this.browserServer.wsEndpoint();
```

Then elsewhere, to connect:
```
this.browser = await this.playwright["chromium"].connect({ wsEndpoint });
```

This worked great in `1.9.2`. However, I recently attempted to update to `1.18.1` and found that `launchServer()` would only work for two servers. Specifically, the third server's `launchServer()` would consistently time out:
```
(node:15086) UnhandledPromiseRejectionWarning: TimeoutError: Timeout 30000ms exceeded.
    at ProgressController.run (/home/account/project/node_modules/playwright/node_modules/playwright-core/lib/server/progress.js:96:26)
    at Chromium.launch (/home/account/project/node_modules/playwright/node_modules/playwright-core/lib/server/browserType.js:81:38)
    at BrowserServerLauncherImpl.launchServer (/home/account/project/node_modules/playwright/node_modules/playwright-core/lib/browserServerImpl.js:60:57)
    at BrowserType.launchServer (/home/account/project/node_modules/playwright/node_modules/playwright-core/lib/client/browserType.js:94:33)
    at Base.init (/home/account/project/inc/Base.js:177:61)
    at async Function.factory (/home/account/project/inc/Base.js:230:3)
    at async /home/account/project/run-server.js:9:10
(Use `node --trace-warnings ...` to show where the warning was created)
(node:15086) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:15086) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Puzzled, I proceeded to repeat this test on the latest patch version of every minor version since `1.9.2`. My findings:
 - `1.18.1` - Only two servers work at a time
 - `1.17.2` - Only two servers work at a time
 - `1.16.3` - Doesn't work at all
 - `1.15.2` - Doesn't work at all
 - `1.14.1` - Only two servers work at a time
 - `1.13.1` - Only two servers work at a time
 - `1.12.3` - Only two servers work at a time
 - `1.12.0` - Only two servers work at a time
 - `1.11.1` - Works! (Four servers work at a time)
 - `1.10.0` - Works! (Four servers work at a time)
 - `1.9.2` - Works! (Four servers work at a time)

The "two servers work" condition of `1.12.0` through `1.14.1` and `1.17.2`+ is particularly odd to me. In these situations, once I have two of the servers running, attempting to start third one will result in `launchServer()` generating a timeout. At that point, if I kill one of the existing servers and try to start that same server again, it will succeed. This suggests to me that perhaps there's some kind of limiter built into Playwright or a dependency that's deliberately causing this behavior.

However, then there's also the issue of the versions (`1.15.2` - `1.16.3`) in which `launchServer()` doesn't seem to work at all - it simply generates a timeout.

I started diving into the diffs between versions, but there's too much going on for me to effectively find the issue.

Any idea what could be causing this behavior? I know a repro would certainly be helpful - at this point I don't have one available - I'm curious what you might think at a conceptual level. Have there been changes throughout recent Playwright history that could account for this inconsistency?

**Comment by yury-s** [comment]
> I'm curious what you might think at a conceptual level. Have there been changes throughout recent Playwright history that could account for this inconsistency?

No, nothing obvious.

> Any idea what could be causing this behavior? 

Can it be insufficient resource issue? Try running with DEBUG=pw:browser to see if the browser crashes or something. If there is nothing obvious, could you run with `DEBUG=pw:browser,pw:protocol` and share the log with us?

It's hard to tell what's going on without a repro.

**Comment by rinogo** [comment]
Thanks, @yury-s! I have the logs you requested available - do you have a private channel I can send them to you? I don't want to accidentally expose anything sensitive.

**Comment by yury-s** [comment]
Do you pass the same port value as argument for all servers? In that case you should see port already used error. When runnin with `DEBUG=pw:browser`, I get the following error on the second instance:

```
yurys:~/sandbox/pw$ DEBUG=pw:browser node serve.js
Starting server.
  pw:browser <launching> /Users/yurys/Library/Caches/ms-playwright/chromium-956323/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --remote-debugging-port=9222 --user-data-dir=/var/folders/7q/m_spf7h54vl_wh1ypnf8xt2r0000gn/T/playwright_chromiumdev_profile-2zup1G --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=7674 +5ms
  pw:browser [pid=7674][err] [0207/103816.507609:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48) +132ms
  pw:browser [pid=7674][err]  +0ms
  pw:browser [pid=7674][err] DevTools listening on ws://[::1]:9222/devtools/browser/28f3258a-772b-4a72-a7cc-03e5e9a5df82 +0ms
Server started.

```

and this one on the third (and the test eventually times out):

```
...
  pw:browser [pid=8078][err] [0207/103949.397452:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48) +193ms
  pw:browser [pid=8078][err] [0207/103949.397533:ERROR:socket_posix.cc(150)] bind() failed: Address already in use (48) +0ms
  pw:browser [pid=8078][err] [0207/103949.397580:ERROR:devtools_http_handler.cc(297)] Cannot start http server for devtools. +0ms
```

This is working as intended, passing unused port number should help.

**Comment by rinogo** [comment]
Makes sense, @yury-s ! For what it's worth, this behavior wasn't consistent across Playwright versions (as you can see from the original Issue text). I'm not sure if there might be something else going on that should be looked into.

Also, for what it's worth, I think throwing an exception immediately would be better developer experience than waiting and then timing out with a generic timeout message.

Regardless, yes, you're right - to fix the issue, we can use different ports or simply remove the debugging parameter unless it's actively in use.

Thanks for your continued contribution to such an incredible project! 🙌

**Comment by yury-s** [comment]
I don't know why the behavior varied between versions, most likely it was just different timing as there is a race during the port allocation. 

> Also, for what it's worth, I think throwing an exception immediately would be better developer experience than waiting and then timing out with a generic timeout message.

It'd be definitely better but unfortunately we don't know if the browser hung or if it's just taking longer to start because of resource pressure etc. Usually for debugging browser launch issue we recommend looking into the browser logs: https://playwright.dev/docs/ci#debugging-browser-launches In this case it's very easy for a human to figure out what's wrong but is difficult to do programmatically in general. What we could do to improve the experience is include browser logs into the timeout exception here.
