### ISSUE TITLE
Handling conditional visible Modals

### ISSUE THREAD

**Issue by JavToscano** [microsoft/playwright#11853]
Hello,

I'm testing a SAAS web app that has different features based on the customer brands.
One of them has a modal that appears based on some conditions (The backend controls this), and i need to press on a button in order to continue with the flow.

How i can handle this modal?

So far i tried with `waitForSelector` and `locator` but it fails if modal doesn't show up.

```javascript
    const button = await this.page.locator('text=Seguir buscando');
    if (button) await button.click();
```

```javascript
    const button = this.waitForSelector('text=Seguir buscando', { timeout: 5000 });
    if (button) await button.click();
```

The problem with this is that the test finish if the modal doesn't open, but i need to continue the test flow on both cases.

**Comment by markomaestral** [comment]
You can try this way.
```JavaScript
const button = await this.page.$('text=Seguir buscando');
if (button) {
  await button.click();
}
```

**Comment by yury-s** [comment]
Assuming that if the modal doesn't appear another element will show up on the page you can do something like this:

```js
  await Promise.race([
    page.locator('text=Seguir buscando').waitFor(),
    page.locator('text=Alternative element').waitFor()
  ]);
  if (await page.locator('text=Seguir buscando').isVisible()) {
    // Accept the modal etc.
  } else {
    // Do something when there is no modal
  }
```
The alternative condition may also be something other than locator.waitFor, e.g. [waitForFunction](https://playwright.dev/docs/api/class-page#page-wait-for-function)

**Comment by rhyeen** [comment]
Thank you @yury-s!  I've expanded on your answer by catching the waitFor errors and not having to wait for a timeout in the conditional logic: https://stackoverflow.com/a/74403846/6090140
