### ISSUE TITLE
[Question] How to identify several elements with the same locator and click on each of them?

### ISSUE THREAD

**Issue by DanielStoica85** [microsoft/playwright#11865]
I have a list of checkboxes and I need to click on all of them. Depending on some factors, the list count can differ, but the locator will be the same for all checkboxes (`'input[aria-label="Select All"]'`). 

How do I iterate over them so I can click each one?

**Comment by markomaestral** [comment]
This should work.
```JavaScript
const checkboxes = await page.$$('input[aria-label="Select All"]');
    
for (let index = 0; index < checkboxes.length; index++) {
  await checkboxes[index].click()
}
```

**Comment by DanielStoica85** [comment]
I am not sure `await` is gonna work fine inside of a `for` loop. Will it? I will try.

**Comment by markomaestral** [comment]
Absolutely, you can use `await` in the `for` loop.

**Comment by DanielStoica85** [comment]
I added this method in a page object class and for some reason it doesn't work when I call it. It just skips it.

**Comment by markomaestral** [comment]
Maybe you forgot to call the `page` with `this`?

```JavaScript
const checkboxes = await this.page.$$('input[aria-label="Select All"]');
```

**Comment by DanielStoica85** [comment]
I did, initially. But then I fixed it and got the same result. Very strange.

**Comment by markomaestral** [comment]
You should also check that the length is greater than zero.
```JavaScript
console.log(checkboxes.length);
```

**Comment by yury-s** [comment]
Please use [locators](https://playwright.dev/docs/api/class-locator) instead of element handles as the latter are more error prone. Assuming that the set of check-boxes stays static while you are checking individual items, you can implement it like this:

```js
  // Locator will resolve to all elements matching the selector
  const checkboxes = page.locator('input[aria-label="Select All"]');
  const promises = [];
  // Get current number of elements in the page a click each of them concurrently
  for (let index = 0; index < await (checkboxes.count()); index++)
    promises.push(checkboxes.nth(index).click());
  // Wait for all clicks to finish
  await Promise.all(promises);
```

**Comment by DanielStoica85** [comment]
@yury-s Should such an example be added to the documentation? I could not find it and I think this is a pretty common use case.
