### ISSUE TITLE
[Feature] dragAndDrop should have `steps` option available

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#11860]
It would be nice to be able to fine-tune the `steps` option for the `mouse.move` triggers in the `dragAndDrop` method.

Because for some reason my drag and drop behavior requires `steps` param to be set to at least 5.

**Comment by yury-s** [comment]
We can add `steps` param but we'd like to make sure that it's not just a timing issue in your case. Can you share the code with 5 steps which made it work?

> Because for some reason my drag and drop behavior requires `steps` param to be set to at least 5.

Can you try doing drag in one step but with extra delays between mouse down, move and up, like this and see if it also solves the problem?

```js
   await this._page.mouse.move(startX, statrY);
   await this._page.mouse.down();
   await new Promise(r => setTimeout(r, 100));
   await this._page.mouse.move(endX, endY);
   await new Promise(r => setTimeout(r, 100));
   await this._page.mouse.up();

```

**Comment by baptisteArno** [comment]
You are right, it was an underlying "issue" with my mouse move events. I managed to make it work 👍

**Comment by yury-s** [comment]
Ok, closing this request for now. We'll reconsider adding steps if more people ask for this.
