### ISSUE TITLE
[BUG] TestId Selector with regex does not find elements

### ISSUE THREAD

**Issue by damevi** [microsoft/playwright#11864]
**Context:**
- Playwright Version: 1.18.1
- Operating System: MacOS
- Node.js version: 16.13.1
- Browser: All

**Code Snippet**

```javascript
test.only("should find testid with regex inside", async ({ page }) => {
  await page.setContent(`<section data-testid="foo-09:00" >43543</section>`);
  await page.setContent(`<section data-testid="foo-14:00" >43543</section>`);

  const regex = new RegExp(`foo-[0-9]+:[0-9]+$`);
  const locator = await page.locator(`data-testid=${regex}`).count();
  console.log("locator count", locator); // returns 0
});
```

**Describe the bug**

I have a case with calendar component which has hour elements where some are disabled and some are not and I am trying to find first one that is not disabled. This works fine in Cypress, yet for Playwright returns 0 for the counts. Am I perhaps missing something?

Kind regards,
Damevi

**Comment by ltsuda** [comment]
Can you try 
```js
const locator = await page.locator(`data-testid=/${regex}/`).count();
```

Search for the regex example here, you need the forward-slashes to use regex `/regex/`.
https://playwright.dev/docs/selectors#text-selector

**Comment by damevi** [comment]
@ltsuda no it still doesn't work and I tried building the testId without `new Regexp` before, so ```.locator(`data-testid=/foo-[0-9]+:[0-9]+$/`)``` doesn't work either

**Comment by ltsuda** [comment]
Understood, I'm sorry then. Let's wait for someone from playwright's team.

**Comment by yury-s** [comment]
Regular expressions currently don't work for `data-testid` matcher, only text.

**Comment by TheDuckGoesQuark** [comment]
This would be really useful. I'd like to select elements matching some id pattern before doing an operation and I can't think of a way of doing it with the tools currently available

**Comment by giladmp1978** [comment]
Hi,
any chance we will have regex in data-test?
this is really missing for me

**Comment by landoephan** [comment]
need that, too!

**Comment by simplywondrous** [comment]
Also chiming in that this would be helpful if it were available!

**Comment by ChillyBots** [comment]
You can use this:

 `[data-testid^="first-part"]`

to select data-testids such as:

`<div data-testid="first-part-of-a-selector"></div>`

It's no regex, but if you have control over your ids, it might help

**Comment by landoephan** [comment]
> You can use this:
> 
> `[data-testid^="first-part"]`
> 
> to select data-testids such as:
> 
> `<div data-testid="first-part-of-a-selector"></div>`
> 
> It's no regex, but if you have control over your ids, it might help

I'm getting an error when I try this:
`Unexpected token "^=" while parsing selector "data-test^=section_"`

I use it like that
`page.locator(`data-test^=${selector}`)`

**Comment by amado-saladino** [comment]
I encountered such a situation and I found it is better to go away from highly depending on `playwright` functionality in this point, I used some other way to get the days that are _not disabled_:

```
const days_allowed = page.locator('td > span:not(.p-disabled)')
```
You can then use `.nth()` method or `.first()` to get the first or any element at a specific index, you can also implement another method to return a random index within the these days.

For sure, the class names may vary depending on how the application is built.

I know this solution is a little unusual but it could save your time :)

Thank you

**Comment by eghernqvist** [comment]
If anyone came here using playwright in a React environment like I did, you can do this as a workaround:
https://playwright.dev/docs/selectors#react-selectors:~:text=_react%3D%5Bauthor%20%3D%20/Steven(%5C%5Cs%2BKing)%3F/i%5D

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by rob4629** [comment]
Just for anyone coming to this issue after it's been closed - it looks like Playwright now allows for RegEx for [Locators and getByTestId](https://playwright.dev/docs/api/class-page#page-get-by-test-id).

**Comment by jasony07** [comment]
> Just for anyone coming to this issue after it's been closed - it looks like Playwright now allows for RegEx with [Locators and getByTestId](https://playwright.dev/docs/api/class-page#page-get-by-test-id).

Is there way to find element by id with regex? I got a list like this 'id=creative-item-176110', but I cannot figure out a way to locate them. I can only get one with xpath. That's frustrating.

**Comment by rawboy** [comment]
Try CSS Attribute Selector if your ids start/end/contain with a specified value. 

locator("[id^=starts]").click()
locator("[id$=ends]").click()
locator("[id*=contains]").click()

https://www.w3schools.com/css/css_attribute_selectors.asp

**Comment by jasony07** [comment]
> Try CSS Attribute Selector if your ids start/end/contain with a specified value.
> 
> locator("[id^=starts]").click() locator("[id$=ends]").click() locator("[id*=contains]").click()
> 
> https://www.w3schools.com/css/css_attribute_selectors.asp

This works. Thanks.
