### ISSUE TITLE
[Question] How can I clear the report from playwright actions (like locator.fill) 

### ISSUE THREAD

**Issue by Mictim** [microsoft/playwright#11871]
Hi, 
I have a question,

How can I prevent writing to the report playwright actions like locator.click(), locator.fill() etc as sub-steps?

![image](https://user-images.githubusercontent.com/10655772/152577225-c44d2793-fe15-48f6-87fa-a9828938b7f7.png)

**Comment by yury-s** [comment]
What reporter are you using? In the built-in html reporter the steps are collapsed by default and you don't see the actions unless you click on the steps, can you tell us a bit more why you also want to omit the actions from the report?

**Comment by Mictim** [comment]
I'm using allure-playwright (2.0.0-beta.15) for CI and html-report for local.
The reason why I want to omit actions in reports is that such reports are used not only by automation engineers.

Is possible to use something like quiet used for stdout or stderr?

**Comment by hananmalka** [comment]
@Mictim - You can wrap the description in the allure report by using `test.step`
By that, you can customize the steps description and create hierarchy of the steps where the "original" playwright steps will collapsed (It's not exactly what you want but it might be useful as well)

Example:

await test.step("Filling Username Input", async ()=> {
       await page.locator('#username').fill("user name content");
});


Then the reporter will look like this:

- Filling Username Input

> - locator.fill('#username') -  Will be hidden unless you will expand the step

**Comment by Mictim** [comment]
Hi @hananmalka,

Thank you for your solution.

I've implemented it already, but there is an issue - if I have a lot of controls, I should create a wrapper for each such step (click, fill, select etc). 
But I prefer to have some logical steps.

**Comment by pavelfeldman** [comment]
You should file this with Allure in their repository!

**Comment by VibhanshuSrivastava** [comment]
> You should file this with Allure in their repository! Also check out our HTML report!

Is there any way to remove page.locator() and page.click() from html report?
