### ISSUE TITLE
Please provide easy-to-reach instructions on Chromium build revision within Playwright documentation . Thank you .

### ISSUE THREAD

**Issue by projektorius96** [microsoft/playwright#11872]
Puppeteer explains clearly on its FAQ sections , i.e. :

1.1) go to [revisions.ts](https://github.com/puppeteer/puppeteer/blob/main/src/revisions.ts) & copy-paste value for chromium
1.2) go to this page [OmahaProxy CSV](https://omahaproxy.appspot.com/) lookup for **Find Release** (_at the very bottom of page_) & by filling in copied chromium revision number (from step 1.1) with preceding letter "r" e.g. at the time of writing this @latest for Puppeteer is **r961656** –> subsequently redirected with result of stable version "99.0.4844.0"

---

Now in terms of Playwright, which is unlike puppeteer's case , the playwrights documentation is brilliant in generally, although when it comes about information for Chromium build, well you have to be sneaky for this . Let's eavesdrop a bit into (luckily) open-source code of playwright `playwright/browser_patches/chromium/BUILD_NUMBER`, oh here it goes [REVISION_NUMBER](https://github.com/microsoft/playwright/blob/main/browser_patches/chromium/BUILD_NUMBER) : at the time of writing it's "r966993" –> repeating steps as above we would get "100.0.4869.0" . Nice, you made it , Playwright 💯  ! 

---

**Self-question arises** : why should I care about this ? Well I do consume Electron.js, yes I am consumer, in case you interested, I needed to write a test for [Electron's bug #32682](https://github.com/electron/electron/issues/32682) I've issued recently . I've checked Spectron is at the dead road, so I decided to follow Electron documentation using Playwright's test-runner which I'd like to use without installing extra Chromium . As per [reference of Electron for Playwright](https://www.electronjs.org/docs/latest/tutorial/automated-testing) , it's highlighted that last version for Chromium build within which test documentation provided was 1.16.3 , I've double checked with OmahaProxy & playwright provided [realease](https://github.com/microsoft/playwright/releases?q=1.16.3&expanded=true) , guess what , it came to true .  Someone may ask me "where is the problem" – I'd say lack of clarity . I need to make sure I have correct version of Chrome/standalone built Chromium for best compatibility of Playwright to run its test-runners on my Electron units . For this, I either have to go to GitHub releases or ask Puppeteer documentation to teach my how should I act upon looking up same information in case of Playwright .

I am highly suggesting to revise documentation for the sake of clarity .
Thank you

**Comment by yury-s** [comment]
There is no exact version requirement for electron today, we [recently added](https://github.com/microsoft/playwright/pull/11792) list of the minimal required versions to the documentation and the will show up on playwright.dev when the docs are rolled out. You are free to use Playwright with any Electron that meets those requirements. Will that work for you?

**Comment by projektorius96** [comment]
I'd expected [the link](https://github.com/microsoft/playwright/pull/11792/commits/5f33b475452cc8d4a6d5d2b4a5d1c95f7c73c14c) rather the one you gave me , plus it would work (_not only for my but for others as well_) if the following information would be visible on Playwright docs at Getting Started  i.e.:

```diff
**Supported Electron versions are:**
* v12.2.0+
* v13.4.0+
* v14+
```

Thank you .

**Comment by pavelfeldman** [comment]
@projektorius96: would you consider sending a PR with the update to our docs? Our support for Electron is experimental, but we welcome contributor patches.

**Comment by yury-s** [comment]
@projektorius96 we don't have getting started guide dedicated to Electron in particular, supported versions are now available on https://playwright.dev/docs/next/api/class-electron . If you have a better place in mind feel free to send an update to our docs as Pavel suggested.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
