### ISSUE TITLE
[BUG] Error "describe() can only be called in a test file" when running a fixture inside another fixture 

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#11889]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Mac
- Node.js version: 14.18.2
- Browser: Chromium

### my-custom-module
```javascript

//fixture.js - set as main in package.json
const base = require("@playwright/test");

exports.test = base.test.extend({
  page: async ({ page }, use) => {
    await page.addInitScript({ content:`${scriptContent}` })
    await use(page);
  }
});

exports.expect = base.expect;
```

### Other project - requires "my-custom-module"
```javascript
//baseFixture.js
const { test, expect } = require("my-custom-module");

exports.test = test.extend({
  todoPage: async ({ page }, use) => {  // page fixture here should be the override fixture I set in "my-custom-module"
    const todoPage = new TodoPage(page);
    await use(todoPage);
  }
}

//Using the fixture
//myTest.spec.js
const { test, expect } = require("baseFixture.js");

test.describe("Sanity tests", () => {
  test(async ({ todoPage }) => {
    await todoPage.navigate()
    await todoPage.waitForLoadingPage();
    ...
    ...
  });

```

**Describe the bug**

In my custom module I'm overriding the page fixture as I want it to implement some logic for the page.
I'm using it in a separate module since I want it to be used in many projects, and maybe later by playwright community. 

In my project, I created some custom fixtures which suppose to use in the override page fixture I created in my module. 
When I'm running the test, I'm getting the following error:

` describe() can only be called in a test file
`

I tried to search for similar errors but found only #11329 and #10616 which I'm not sure does really help solving this issue. 

I would appreciate any help with this.

**Comment by pavelfeldman** [comment]
You are likely to have a non-dev Playwright dependency in `my-custom-module`. As a result, your helper and your end-user code have different versions of Playwright. The solution is to make surer `@playwright/test` dependency is only in the leaf module, while all the helpers are specifying it as a dev dependency.

**Comment by pavelfeldman** [comment]
Leaving is open, we should mention this in the error message since I've seen this confusion before!

**Comment by hananmalka** [comment]
@pavelfeldman 
I'm not sure I got all technical expressions so I want to share how my package.json files looks like, both in `my custom module` and in the other project. 
I would appreciate if you can elaborate what are the "helpers" and "end-user-code" 

**Note: When I first opened this issue, the `@playwright/test` in `my-custom-module` was under `dependencies` (Which you described as wrong)
I've just changed it to be under `devDependencies` following your response (Hopefully I got it right)**

And still, with the below - I'm still getting the error: `describe() can only be called in a test file`

### my-custom-module
```javascript
"devDependencies": {
    "fs-extra": "^10.0.0",
    "@playwright/test": "^1.18.1"
  }
```

### Other project  (requires my-custom-module)
```javascript
"devDependencies": {
...
    "@playwright/test": "^1.18.1",
    "my-custom-module": "file:../my-custom-module"
...
}
```

**Comment by hananmalka** [comment]
By the way, with the above configuration, when I'm using `allure-playwright` in my project (not in my-cutstom-module) as one of the reporters, I'm getting the following error:

`Error: Requiring @playwright/test second time,`

Where the second time is in: `/allure-playwright/src/helpers.ts`

**Comment by Forfold** [comment]
@hananmalka were you ever able to resolve the issue of requiring playwright a second time in your custom package? I'm seeing the same thing over in issue #15349
