### ISSUE TITLE
I'm trying to use waitForResponse, everytime test kept failing with the timeout error

### ISSUE THREAD

**Issue by cmsqa** [microsoft/playwright#11885]
test('API', async ({ page }) => {
  await page.goto('https://letcode.in/elements');
  await Promise.all([
    await page.waitForResponse(res => res.url() === 'https://api.github.com/users/ortonikc' && res.status === 200),
    await page.fill("input[name='username']", 'ortonikc'),
    await page.click('button'),
  ]);
});
Here is result
  Timeout of 30000ms exceeded.

    page.waitForResponse: Page closed

      54 |   await page.goto('https://letcode.in/elements');
      55 |   await Promise.all([
    > 56 |     await page.waitForResponse(res => res.url() === 'https://api.github.com/users/ortonikc' && res.status === 200),
         |                ^
      57 |     await page.fill("input[name='username']", 'ortonikc'),
      58 |     await page.click('button'),
      59 |   ]);
Do i need anything specific for it rum?
Can you please help me resolve this issue?

**Comment by s3naid** [comment]
try it without await inside promise:
`     await page.goto('https://letcode.in/elements');

     await Promise.all([

      page.waitForResponse(res => res.url() === 'https://api.github.com/users/ortonikc' && res.status() === 200),

      page.fill("input[name='username']", 'ortonikc'),

      page.click('button'),
    ]);`

**Comment by cmsqa** [comment]
thanks, I tried did not work. This is actual scenario i was checking in our app but it always timeout#
<img width="1054" alt="Screen Shot 2022-02-07 at 2 03 51 PM" src="https://user-images.githubusercontent.com/86015071/152854655-d3bfc987-e122-4dbb-832e-c92e56c49ea1.png">

**Comment by cmsqa** [comment]
thanks for the suggestion but it did not work. this is scenario i was trying to wait for but it times-out
<img width="863" alt="Screen Shot 2022-02-07 at 2 08 53 PM" src="https://user-images.githubusercontent.com/86015071/152855304-7976d1f9-ca1f-4f1f-927d-f69b9e98b5fb.png">

**Comment by vsravuri** [comment]
Try this, it works for me in Chrome.

```javascript
await page.goto('https://letcode.in/elements');
    await page.fill("input[name='username']", 'ortonikc');
        await Promise.all([
            page.waitForResponse(res => res.url() === 'https://api.github.com/users/ortonikc' && res.status() === 200),
            page.click('button')
        ]);]);`
```

**Comment by ulken** [comment]
> thanks for the suggestion but it did not work. this is scenario i was trying to wait for but it times-out <img alt="Screen Shot 2022-02-07 at 2 08 53 PM" width="863" src="https://user-images.githubusercontent.com/86015071/152855304-7976d1f9-ca1f-4f1f-927d-f69b9e98b5fb.png">

@cmsqa  Necro, but FYI: in contrast to the shorthand of simply feeding a pathname to `page.waitForResponse()`, `response.url()` returns the complete URL string (including protocol and domain etc.).

So, either you would need to compare to that (e.g. `http(s)://yourdomain.xyz/api/documents`) or wrap it in a `URL` object and compare to its `pathname` (e.g. `new URL(response.url()).pathname === "/api/documents"`). **Note** the initial `/`.

**Comment by rj-wowza** [comment]
@ulken i think you could do `response.url().includes('/path/')`

**Comment by ulken** [comment]
> @ulken i think you could do `response.url().includes('/path/')`

Sure, you could, but it would not be as explicit. Potentially matching more routes than desired.

**Comment by rufi0h** [comment]
In your code here, this is waiting for both the url to match the string and for the status to be 200, so if the URL matches, but the response isn't 200, it just waits for the timeout. If you use promise chaining on the waitForResponse the test should fail right away when the status doesn't match. 

example: 

await page.goto('https://letcode.in/elements',{waitUntil: "networkidle"});

    await page.fill("input[name='username']", 'ortonikc');
    
        await Promise.all([
            page.waitForResponse(res => res.url() === 'https://api.github.com/users/ortonikc')
		     .then(resp => res.status() === 200 ? true : process.exit(1)),
            page.click('button')
        ]);]);
