### ISSUE TITLE
Cannot keep Electron window opened: CLI --headed option does not work !

### ISSUE THREAD

**Issue by projektorius96** [microsoft/playwright#11886]
**Context:**
- Playwright Version: [what Playwright version do you use?] <br> 
    - 1.18.1
- Operating System: [e.g. Windows, Linux or Mac] <br> 
    - Windows Home 10 Windows Feature Experience Pack 120.2212.3920.0
- Node.js version: [e.g. 12.22, 14.6]
    - 16.13.2
- Browser: [e.g. All, Chromium, Firefox, WebKit]
    - Chromium built with default Electron installation from npm
- Extra: [any specific details about your environment]
    - Electron version: 16.0.7

**Code Snippet**

I use Playwright test runner with default **playwright.config.js** . Within `npx playwright test` test runner works fine, but I cannot make **headed mode** for my Electron test, whenever test runs through (passes) Electron window stays open just for a second or two , so neither `--headed`, nor `--debug` seems to work . <br>
You can see clearly from my code I know what I am doing, I even provide some lines with the code snippet provided below :

```javascript
const { _electron: electron } = require('playwright')
const { test, expect } = require('@playwright/test')

// Herein we mount local configs onto test function :
test.use({
    headless: false, // hereby we overwrite headless option inbound from playwright.config.js (if any)
})

test('example1', async () => {

    const electronApp = await electron.launch({ args: ['main.js']})
    
    const isPackaged = await electronApp.evaluate(async ({ app }) => {
    return app.isPackaged;
    });

    expect(isPackaged).toBe(false); // [PASSED]

    // PAY ATTENTION LINES BELOW

    // close app : line below deliberately commented out 
    // await electronApp.close() // # if headless: false, please close in terminal by Ctrl + C ; NOTE : this approach works in Puppeteer
});
```

**Describe the bug**

As you saw in the code snippet above, even if I try to stay per-local-configuration explicitly declaring <br> 
```javascript
test.use({
    headless: false,
})
```

Nor local-over-global configuration , nor `--headed` for `headless: false` on CLI helps me out to keep Electron window opened after all . I even deliberately commented out `await electronApp.close()` . I event tried Infinite setTimeout, sadly none of them worked out . 

I have enough evidence to consider it as a potential bug . Thank you .

**Comment by projektorius96** [comment]
Hi, sorry for taken so long, although I've experienced some buggy behaviour last days with Playwright, even issued a potential bug [#11886](https://github.com/microsoft/playwright/issues/11886) . Here is a reproduced code with minimum testing codebase, please refer to /README.md & /tests/COVERAGE.md for guidelines . 

Here is a [case reproduction](https://github.com/projektorius96/electron-dynamic-import-bug) for a follow-up .

Thank you.

**Comment by pavelfeldman** [comment]
None of our fixtures in `@playwright/test` are affecting Electron. We also don't have headless mode for Electron.

**Comment by projektorius96** [comment]
@pavelfeldman well that's something , but then let me ask you politely how to write a test keeping Electron window opened after test is done ? Maybe I just follow a wrong approach . If no test for Electron written, Electron windows stays opened till manually close or so, but using the Playwright/test persists only within period test runs, once finished Electron window closed immediately . Am I missing a point somewhere , I just need to be put on a right track , well, would appreciate that . Thank you :)
