### ISSUE TITLE
firefox remote profile path error

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright#11883]
**Context:**
- Playwright Version: 1.16.0
- Operating System:mac 
- Node.js version: 16
- Browser: Firefox
I created a smb service on a computer. If I use windows to create playwright, firefox browser, and the profile path is the smb address, it can run correctly.
I created playwright and firefox browser with mac computer, the the profile   path is smb address, and the following error occurs.

![image](https://user-images.githubusercontent.com/1261933/152642203-058e81f0-e6c6-48ee-aa95-f1657477e7ae.png)

How do I handle this on MAC?

**Comment by pavelfeldman** [comment]
It seems like this is a Firefox on macOS limitation, does not look related to Playwright!
