### ISSUE TITLE
Expose type of Storage State

### ISSUE THREAD

**Issue by aromalanil** [microsoft/playwright#11896]
## Issue
Currently the type of `Storage State` is like this

<img width="498" alt="Screenshot 2022-02-07 at 2 52 31 PM" src="https://user-images.githubusercontent.com/49222186/152760454-20a4dc43-3891-414b-afe2-af0e8c922c2c.png">

- This makes it very difficult to create custom interface / type with storageState as one of it's entries.
- It is also hard to declare a variable for storageState before getting the value.

## Request
My request is to create a custom type / interface for `Storage State` and expose it directly from "playwright" library so that we can import and use it like this

```js
const { StorageState } from "playwright";

. . .

let storageState : StorageState;

. . . 

storageState = await context.storageState();
```

## Note
I really like this project and would like to give my contribution. Please let me know if this proposal is acceptable and if yes, I can work on this.

**Comment by aromalanil** [comment]
Our repo prevent the use of any. We are enforsing this rule using ESlint for better typescript. 

I believe, If a library supports typescript, It should expose all possible types used in that library.

Coming to my usecase, I am creating a context object which have many other data including this `StorageState`. I want to prevent something other than `StorageState` to be assigned to that position. Even though I am not modifying the StorageState, I am modifying this context object.

**Comment by pavelfeldman** [comment]
Sounds good. I'm marking this as p3. It means we are open to PRs with the fix and/or collecting upvotes for this issue.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by codesman** [comment]
Anybody getting caught up on this, there is no reason to require StorageState to be exposed. Defining it as `storageState: string` is how to pass it around without resorting to `any`.  The `storageState` property that playwright exposes publicly is a an optional path, which is `string` type and can be cast to string or passed to a String constructor.  Whatever shape that becomes internally is able to be inferred, but not consumed.
