### ISSUE TITLE
[BUG] Parallelization within a single file combines times for slow file detection

### ISSUE THREAD

**Issue by brandonson** [microsoft/playwright#11897]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux
- Node.js version: 16.2
- Browser: At least Chromium, Firefox (probably all)

**Describe the bug**

I've got three `spec.ts` test files that run the same set of tests, each with a different parameter. The actual test code is contained in a function within a shared util file, and all the test files do is call it. The idea here was to achieve parallelization, since the set of tests is reasonably quick, but when run several times it was too slow.

However, the slow test file detection reports false positives for the shared util file. It seems that the time is recorded for the util file rather than the calling file.

It also causes shared test paths in the line reporter (seems it doesn't report the spec file's name, just the test source line). The HTML reporter's display correctly reports the spec file filename, and then the util file/line per test. Both reporters have the `Slow test file:` warning in the console output.

I think the right thing here is probably to report slow files based on the caller file - after all, my entire goal with splitting the tests out was to parallelize the test sets, and I did! But it still warns that it's "slow".

## Line Report

```
yarn run v1.22.11
$ playwright test city-special-points
Using config at /workspace/eighty-days/playwright-tests/playwright.config.ts

Running 9 tests using 3 workers

  ✓  tests/city-special-points/city-special-points-framework.ts:68:3 › should display the enter marker (3s)
  ✓  tests/city-special-points/city-special-points-framework.ts:68:3 › should display the exit marker (3s)
  ✓  tests/city-special-points/city-special-points-framework.ts:68:3 › should display the stay-at marker (3s)
  ✓  tests/city-special-points/city-special-points-framework.ts:80:3 › should allow centering on the enter point (6s)
  ✓  tests/city-special-points/city-special-points-framework.ts:80:3 › should allow centering on the stay-at point (6s)
  ✓  tests/city-special-points/city-special-points-framework.ts:80:3 › should allow centering on the exit point (6s)
  ✓  tests/city-special-points/city-special-points-framework.ts:116:3 › should hide the delete icon for the stay-at point (1s)
  ✓  tests/city-special-points/city-special-points-framework.ts:116:3 › should hide the delete icon for the exit point (1s)
  ✓  tests/city-special-points/city-special-points-framework.ts:116:3 › should hide the delete icon for the enter point (1s)

  Slow test file: tests/city-special-points/city-special-points-framework.ts (31s)
  Consider splitting slow test files to speed up parallel execution

  9 passed (11s)
Done in 10.78s.
```

Note the impossible time results, a 31s test file obviously did not manage to run in just under 11s.

## HTML Report
![image](https://user-images.githubusercontent.com/1870695/152765389-f16619af-c573-473f-ab02-b3a22d6f6cc8.png)

**Comment by pavelfeldman** [comment]
Your tests are registered in the shared function, so we would actually consider html reporter to be confused in this case. We report tests where they are registered... Did you consider using https://playwright.dev/docs/test-parameterize#parameterized-projects?

**Comment by brandonson** [comment]
I did consider that, but it doesn't seem right. They're pretty basic parameters - sort of like if you had a queue class and wanted to test it with 0, 1, and 5 items. I'm not aware of any blockers for using parameterized projects if that's what I need to do, but it feels wrong to me.

If it were possible to parameterize within a single file and get per-parameter workers, that'd be great, but I don't believe that's directly possible right now. `test.describe.parallel` might work, but my understanding is it parallelizes each individual test, which is slightly different. (I'm also not sure if the slow test report would disappear- I'll have to check)

For reporter differences, I see what you're saying, but the HTML reporter still looks right to me. Individual tests are reported where they're registered, but the full suite is reported using the file that created the job/task/test set. The list reporter isn't 'wrong' either, it just doesn't report that job/task/test set file info.

**Comment by brandonson** [comment]
I've since had a chance to confirm that parallelizing via `test.describe.parallel` sort of works in this specific case - but still reports the total in the slow file check. I'm not sure if that's intentional, but I suspect not - as far as I'm aware there's no benefit to splitting up a file that uses `test.describe.parallel`

```
yarn run v1.22.11
$ playwright test city-special-points
Using config at /workspace/eighty-days/playwright-tests/playwright.config.ts

Running 9 tests using 9 workers

  ✓  tests/city-special-points/city-special-points.spec.ts:81:5 › special point enter › should allow centering on the enter point (9s)
  ✓  tests/city-special-points/city-special-points.spec.ts:81:5 › special point exit › should allow centering on the exit point (9s)
  ✓  tests/city-special-points/city-special-points.spec.ts:69:5 › special point enter › should display the enter marker (4s)
  ✓  tests/city-special-points/city-special-points.spec.ts:118:5 › special point enter › should hide the delete icon for the enter point (5s)
  ✓  tests/city-special-points/city-special-points.spec.ts:69:5 › special point stay-at › should display the stay-at marker (5s)
  ✓  tests/city-special-points/city-special-points.spec.ts:118:5 › special point exit › should hide the delete icon for the exit point (5s)
  ✓  tests/city-special-points/city-special-points.spec.ts:69:5 › special point exit › should display the exit marker (5s)
  ✓  tests/city-special-points/city-special-points.spec.ts:81:5 › special point stay-at › should allow centering on the stay-at point (9s)
  ✓  tests/city-special-points/city-special-points.spec.ts:118:5 › special point stay-at › should hide the delete icon for the stay-at point (5s)

  Slow test file: tests/city-special-points/city-special-points.spec.ts (54s)
  Consider splitting slow test files to speed up parallel execution

  9 passed (9s)
Done in 9.48s.
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
