### ISSUE TITLE
[BUG] Waiting for filechooser crashes the page

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#11899]
**Context:**
- Playwright Version: 1.1.8.1
- Operating System: bitbucket pipelines
- Node.js version: 16.13
- Device: iPhone 13 Pro
- Extra: running tests in parallel inside bitbucket pipelines (Running 26 tests using 4 workers)

Sometimes the page crashes when waiting for `filechooser` (Happens only on mobile IOS not on chromium)
code

```typescript
const [fileChooser] = await Promise.all([this.page.waitForEvent('filechooser'), this.page.locator(this.#uploadButton).click()]);
await fileChooser.setFiles(path.resolve('src/images/2mb_sample.png'));
```

Html reporter errors
![image](https://user-images.githubusercontent.com/42112796/152770843-43267ab2-80a0-48e6-94cd-17b76d22eac5.png)

Html reporter test steps
![image](https://user-images.githubusercontent.com/42112796/152770802-c5167687-226a-4b2f-ad81-662b7832288f.png)

Trace file
![image](https://user-images.githubusercontent.com/42112796/152771070-f85015d6-df7b-4403-a318-1088bf338b12.png)
and
![image](https://user-images.githubusercontent.com/42112796/152771134-92ed33f3-a7bc-49d6-9993-98b1b02aeb63.png)

playwright config
```typescript
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
	testDir: './src/tests',
	globalSetup: './src/tests/setup/globalSetup.ts',
	timeout: 240 * 1000,
	expect: {
		timeout: 5000
	},
	forbidOnly: !!process.env.CI,
	retries: process.env.CI ? 2 : 0,

	reporter: [['html'], ['list'], ['./src/reporters/slack-PD-reporter.ts'], ['./src/reporters/elastic-reporter.ts']],

	use: {
		launchOptions: {
			// slowMo: 20
		},
		actionTimeout: 0,

		trace: 'on-first-retry',
		video: 'retain-on-failure',
		screenshot: 'only-on-failure'
	},

	projects: [
		{
			name: 'chromium',
			use: {
				...devices['Desktop Chrome']
			}
		},
		{
			name: 'IOS',
			use: {
				...devices['iPhone 13 Pro']
			}
		}
	]
};
export default config;

```

**Comment by pavelfeldman** [comment]
Thank you for the report! Could you run the same with `DEBUG=pw:browser*` env variable? It'll tell us why WebKit crashes.

**Comment by israelKusayev** [comment]
Hi I tried running with `DEBUG=pw:browser*` as for now I can't reproduce the bug, I'll update when I encounter it again

**Comment by israelKusayev** [comment]
@pavelfeldman I reproduced. the only log I see it

    2022-02-09T14:21:44.915Z pw:browser <launching> /ms-playwright/webkit-1596/pw_run.sh --inspector-pipe --headless --no-startup-window
    2022-02-09T14:21:44.927Z pw:browser <launched> pid=3932

**Comment by pavelfeldman** [comment]
Your code looks good and the trace looks clean, as in it does not say anything about the crashed page. Is there a chance you could provide a reduced test case that we can try?

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
