### ISSUE TITLE
[Question] how to call test case

### ISSUE THREAD

**Issue by shaoxiangwu** [microsoft/playwright#11895]
It would be nice if we could call the written use test cases

``` javascript
  test('test-case-A', async () => {
    XXXX
    XXXXX
    XXXX
    do something..
  });

  test('test-case-B', async () => {
    // rely on  test('test-case-A')
    call test('test-case-A')
    XXXX
    do something..
  });
```

**Comment by lmlikota** [comment]
I think the whole idea of parallelism to avoid dependency between tests so each must be designed without dependency as a test case. And that's not that easy when you have a complex application without a lot of parent child relationships between main application objects. 

I know, I'm also struggling with this a lot. In my case calling a test case would be useful.

**Comment by pavelfeldman** [comment]
Playwright is just a program!

```js
  async function helper() {
    XXXX
    XXXXX
    XXXX
    do something..
  });

  test('test-case-A', async () => {
    await helper();
  });

  test('test-case-B', async () => {
    await helper();
    XXXX
    do something..
  });
```
