### ISSUE TITLE
Running test which imports shared code from other test file results in wrong test running and wrong test reported as run

### ISSUE THREAD

**Issue by JonGinty** [microsoft/playwright#11904]
**Context:**
 - Playwright Version: 1.18.1
 - Operating System: Windows 10
 - Node.js Version: 16.13.2
 - Browser: Chromium

**Issue**
When running a test which imports a module from a different file which also contains a test, the test on the imported file is run *instead of* the test from the expected test file.

**Code**
*package.json*
```JSON
{
  "name": "playwright-test-issue",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "npx playwright test"
  },
  "type": "module",
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.18.1"
  }
}
```

*test1.spec.js*
```JavaScript
import { test } from "@playwright/test";

test("test 1", async ({page}) => {
	console.log("running test 1");
})

export function utilityFunction() {
	console.log("running utility function");
}
```

*test2.spec.js*
```JavaScript
import { test } from "@playwright/test";
import { utilityFunction } from "./test1.spec.js";

test("test 2", async ({page}) => {
	utilityFunction();
	console.log("running test 2");
})
```

**Output**
Upon running the command ```npm run test``` we get the following output
```
> playwright-test-issue@1.0.0 test
> npx playwright test


Running 2 tests using 2 workers

  ok test1.spec.js:3:1 › test 1 (2s)
  ok test2.spec.js:4:1 › test 2 (2s) 
running test 1
running test 1

  2 passed (3s)
```
It is clear that the output above is reporting that test2 has been run. If this was actually the case, we wouldn't see ```running test 1``` repeated twice in the output.

**Expected Output**
```
> playwright-test-issue@1.0.0 test
> npx playwright test


Running 2 tests using 2 workers

  ok test1.spec.js:3:1 › test 1 (2s)
  ok test2.spec.js:4:1 › test 2 (2s) 
running test 1
running test 2
running utility function

  2 passed (3s)
```

**Notes**
I'm aware that this isn't exactly a good way to structure a project, and I was able to side-step this by refactoring utility functions into their own files which don't contain tests. My main issue here was that the incorrect reporting of which tests had been run made this difficult to diagnose.

Apologies if this is a duplicate, I had a look and couldn't find anything like this. 

Also I appreciate all of the hard work you all do for this project, playwright is an absolute joy to work with and this is the only *issue* I've encountered in my whole time working with it.

**Comment by pavelfeldman** [comment]
To outline what is happening:

- we traverse files and require them in the runner process. we discover `test1` and `test2`
- we then run 2 workers to parallel-run these files.
- first worker runs test1 as expected
- second worker is also told to run the first test it discovers
- but the first test that is registered is `test1` there as well
