### ISSUE TITLE
Connecting and seeing codegen against WebView2 within Winforms

### ISSUE THREAD

**Issue by BasketGolfer** [microsoft/playwright#11900]
Have a WebView2 instance in a winform. (.Net Framework 4.7.2)
Playwright connects successfully to the WebView2 instance using:
public IPlaywright playwright { get; private set; }
public IBrowser browser { get; private set; }
public IBrowserContext context { get; private set; }
public IPage page { get; set; }
...
playwright = await Playwright.CreateAsync();
browser = await playwright.Chromium.ConnectOverCDPAsync("http://localhost:" + CDPport);
context = browser.Contexts[0];
page = context.Pages[0];

But I am not able to get this example to do anything - it doesn't error, but nothing happens that I can see
https://playwright.dev/docs/cli#codegen-with-custom-setup
The docs made it sound like I just needed to this (since I've already got a browser/context/page from the above)

await context.RouteAsync("**/*", route => route.ContinueAsync());
await page.PauseAsync();

But I am obviously misunderstanding something very fundamental.

Thanks in advance!

**Comment by pavelfeldman** [comment]
We don't support codegen over the remote connection, it only works for the local scenarios.

**Comment by BasketGolfer** [comment]
Thanks for the fast reply! 

Questions just for my education:

1. To make sure I'm clear on terminology. Using ConnectOverCDPAsync is by definition "remote"? It doesn't matter if the browser is on the same machine or not.

2. I am making the correct assumption that CodeGen is a function of the browser drivers themselves, which is why it is impossible to ever get CodeGen using ConnectOverCDPAsnyc?

If #2 is correct, are there plans for incorporating WebView2?

**Comment by pavelfeldman** [comment]
> To make sure I'm clear on terminology. Using ConnectOverCDPAsync is by definition "remote"? It doesn't matter if the browser is on the same machine or not.

Yes, connect means remote, does not matter same machine or not.

> I am making the correct assumption that CodeGen is a function of the browser drivers themselves, which is why it is impossible to ever get CodeGen using ConnectOverCDPAsnyc?

There are no browser drivers in Playwright. CodeGen is only working when running a local (non-connect) scenarios.

>  If 2 is correct, are there plans for incorporating WebView2?

There are no immediate plans to implement codegen against WebView2, we assume you can generate the script while running against a web page opened in a regular browser. Please feel free to file a feature request for the codegen started from WebView2, there are no technical limitations, but it would be a subject to prioritization.

**Comment by dgozman** [comment]
@BasketGolfer I just tried this myself in v1.19 against Chromium launched with `--remote-debugging-port=9222`, and it works. What is your Playwright version?

Note that you use `browser.Contexts[0]` and `context.Pages[0]`. This means that WebView2 should have a default page in the default context - I do not know exactly whether that's the case. Other than that, pausing the page brings up the Playwright Inspector and codegen.

**Comment by yaoweilei** [comment]
> @BasketGolfer I just tried this myself in v1.19 against Chromium launched with `--remote-debugging-port=9222`, and it works. What is your Playwright version?
> 
> Note that you use `browser.Contexts[0]` and `context.Pages[0]`. This means that WebView2 should have a default page in the default context - I do not know exactly whether that's the case. Other than that, pausing the page brings up the Playwright Inspector and codegen.

could you share this related codegen code?

**Comment by mxschmitt** [comment]
We also have a guide for it: https://playwright.dev/docs/webview2
