### ISSUE TITLE
[Question] How to end webserver

### ISSUE THREAD

**Issue by YousefED** [microsoft/playwright#11907]
We're using `PlaywrightTestConfig` with the `webServer` parameter to make sure our local react app starts before testing (command is `npm start`).

After running `npx playwright test` (and exiting that), the webserver is still running.

How do we close the webserver process?

**Comment by pavelfeldman** [comment]
The web server process is terminated on Playwright exit. Please provide the steps to reproduce: your OS and a simple config that demonstrates the problem.

**Comment by aslushnikov** [comment]
@YousefED also, can you please try with @playwright/test@next? we recently fixed a bug related to this.

**Comment by aslushnikov** [comment]
@YousefED This one sounds new! Could you please file a new one with a repro?

**Comment by YousefED** [comment]
> @YousefED This one sounds new! Could you please file a new one with a repro that uses @playwright/test@next?

I tried to reproduce this but have been unable to do so unfortunately. I'll close this issue and reopen it if I run into it again

**Comment by erayerdin** [comment]
While it shuts down the regular dev server, Playwright cannot kill Firebase emulator.

This is my package.json script:

```
"firebase:emulators:run": "firebase emulators:start --only functions,storage,firestore,auth"
```

The project is a Vite + React + Typescript project.

This is how I configured the `webServer`:

```typescript
webServer: [
    {
      command: "npm run dev -- --host 127.0.0.1 --port 19940",
      url: "http://127.0.0.1:19940",
      reuseExistingServer: !process.env.CI,
      timeout: 10 * 1000,
      stderr: "pipe",
    },
    {
      command: "npm run firebase:emulators:run",
      url: "http://127.0.0.1:9099",
      reuseExistingServer: !process.env.CI,
      timeout: 60 * 1000,
      stderr: "pipe",
    },
  ],
```

After tests run, the `java` process still runs. Maybe the reason why Playwright cannot kill Firebase Emulator is because how Java works?

**Comment by mifrej** [comment]
This is still a problem. Webservers are not shot down after test suite runs.
I needed to add the script to kill the servers, it is so annoying.

**Comment by mununki** [comment]
If a test fails, the test server doesn't terminate and remains running. This is very annoying. If you want to reuse the test server, keeping the process alive would be nice, but isn't it possible to disable it by default?

"@playwright/test": "^1.55.0"

**Comment by mununki** [comment]
I figure it out with option:

```
reporter: [
    ["json", {open: process.env.CI ? "never": "on-failure"}]
  ]
```
