### ISSUE TITLE
[Feature] Do not require waiting for navigation upon click

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#1190]
The following pattern needs to go before we hit v1.0

```js
const [response] = await Promise.all([
  page.waitForNavigation(waitOptions),
  page.click(selector, clickOptions),
]);
```

it should be simply

```js
await page.click(selector, clickOptions);
```

**Comment by jperl** [comment]
I assume this will be true for all action methods (type, etc)?

**Comment by pavelfeldman** [comment]
Yes, action methods on `page`, `frame` and `elementHandle` and even `evaluate`. Not the `page.keyboard` / `page.mouse` ones though.

**Comment by pavelfeldman** [comment]
No plans for `waitUntil` for now - we consider waiting until certain load phase overvalued - it does not give much. It might change though and we fall back to having it.

**Comment by jperl** [comment]
A lot of times you press enter to submit a form (log in etc). It would be nice to auto-wait for press("Enter").

**Comment by pavelfeldman** [comment]
This is now done, with `waitUntil` as @jperl was suggesting. I also pulled press into [`page.press()`](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagepressselector-key-options) for convenience.

**Comment by thernstig** [comment]
@pavelfeldman Should this change warrant an update in this example, so people are not fooled into thinkin this pattern is still needed? See  https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitfornavigationoptions
