### ISSUE TITLE
[BUG] Cannot depend on playwright-core@next

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1191]
**Context:**
- Playwright Version: next

**Code Snippet**

playwright-utils requires playwright-core. playwright-core is a peerDependency and playwright is a devDependency.

To publish a version for the upcoming playwright I [tried to depend on playwright-core@next](https://github.com/qawolf/playwright-utils/pull/2/commits/7e722033b644e28b36b16b6df73f082053ace6a1).

It says [“Chromium revision is not downloaded”](https://github.com/qawolf/playwright-utils/runs/482969428)

When I [require playwright@next](https://github.com/qawolf/playwright-utils/pull/2/commits/02e01f2231b65dad3830d916f233f515d4bc1efb) instead of playwright-core [it works](https://github.com/qawolf/playwright-utils/runs/482973224).

**Comment by jperl** [comment]
Thank you for publishing @next packages, this is very helpful for developing third party libraries that depend on upcoming features 🙏.

**Comment by aslushnikov** [comment]
On 0.11.1, both `playwright-core` and `playwright` download browsers and look for browsers in the same location - at the `playwright-core` folder. So when you install `playwright`, it has `playwright-core` as a dependency, and downloads browsers in the `//node_modules/playwright-core/.local-{chromium,firefox,webkit}`.

However, this broke some caching assumptions that yarn does, namely we can't modify package contents after it's install scripts are run. (see #1085). So we changed this, and now playwright
and playwright-core download browsers into different locations:
- playwright: `//node_modules/playwright/.local-{chromium,firefox,webkit}`
- playwright-core: `//node_modules/playwright-core/.local-{chromium,firefox,webkit}`

To install the browsers for `playwright-core`, you'd need to get an `install.js` script in your package which calls `browserType.downloadBrowserIfNeeded()` method.

**Comment by jperl** [comment]
Makes sense, thanks for the explanation. In that case we will make playwright a peer dependency instead, since users will likely depend on playwright and we would not want them to download two copies of the browsers.

However this will prevent us from supporting to skip browser downloads with environment variables. Perhaps that functionality is worth reconsidering for the playwright package. https://github.com/microsoft/playwright/issues/823
