### ISSUE TITLE
Playwright Math.round does not work on Firefox and Safari browsers

### ISSUE THREAD

**Issue by dinosaurL** [microsoft/playwright#11911]
**Context:**
- Playwright Version:  1.17.1
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: Issue only happens on Firefox /Safari browsers
- Extra: [any specific details about your environment]

**Code Snippet**
Seems that the Safari and Firebox browsers have issues with rounding-up decimal places.
both the attributes: `flex-basis` and `max-width` are calculated by this expression , via Styled Components,  
```javascript
  Math.round((4 / 12) * 10e7) / 10e5;
```
and this test succeeds in Chrome , and Firefox, but fails in Sarfari:
```javascript
    test.only('should span a third of 12 columns on large breakpoint', async ({
      page,
    }) => {
      await page.setViewportSize({ width: 1026, height: 500 });
      await expect(testDiv).toHaveCSS('padding-left', '16px');
      await expect(testDiv).toHaveCSS('flex-basis', '33.3333%');
      await expect(testDiv).toHaveCSS('max-width', '33.3333%');
    });
```
Rounding up succeeds in Chrome , but fails in Safari browser  ( in other tests, fails for Firefox too):
![Screenshot 2022-02-07 at 17 35 42](https://user-images.githubusercontent.com/5711250/152841864-f5a686d1-723c-4920-b869-17b5b3611e6a.png)

**DIAGNOSIS:**
Unless I'm mistaken, looks like it won't round-up to 4 decimal figures for both Firefox and Safari browsers within Playwright test env.

**Comment by dinosaurL** [comment]
We have decided to use RegExp for now:
`
await expect(testDiv).toHaveCSS('flex-basis', /33\.33.*%/);
`
So, if this IS the correct way to do it, rather than trying to tackle every browser's quirk in rounding up decimal figures of CSS attribute, I think this ticket can be closed.

**Comment by dgozman** [comment]
[dinosaurL](https://github.com/dinosaurL) That's right, Playwright just exposes browsers as they are with their own quirks. Using a regex seems like a good fit.
