### ISSUE TITLE
[Feature] blackout certain elements while making screenshots

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#11913]
<EOM>

**Comment by unlikelyzero** [comment]
@aslushnikov this functionality is available in the applitool's api to some extent. On a previous project of mine, we went with Applitools over other visual tools specifically for this functionality. 

https://applitools.com/docs/api/eyes-sdk/classes-gen/class_checksettings/method-checksettings-ignoreregions-playwright-javascript.html?Highlight=ignoreregion

**Comment by aslushnikov** [comment]
@unlikelyzero Sweet, thank you for the pointer!

**Comment by aslushnikov** [comment]
@@unlikelyzero do you find it most convenient to hide elements using element handles, selectors, or plain screenshot rectangles?

**Comment by aslushnikov** [comment]
(Merging this into https://github.com/microsoft/playwright/issues/7820)
