### ISSUE TITLE
[Question] How to change the default policy of the built-in browser(ms-edge or chrome) used by playwright?

### ISSUE THREAD

**Issue by cjydayang** [microsoft/playwright#11927]
I want to disable the [externalprotocoldialogshowalwaysopencheckbox](https://docs.microsoft.com/en-us/DeployEdge/microsoft-edge-policies#externalprotocoldialogshowalwaysopencheckbox) policy ，but there are no related folders in the windows registry.
Is there any way to do this?

**Comment by pavelfeldman** [comment]
I don't think we support anything like this.
