### ISSUE TITLE
[BUG] The Value of `navigator.userAgent` Is Not Always Correlated With `navigator.platform`

### ISSUE THREAD

**Issue by christopher-o-toole** [microsoft/playwright#11928]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows 10 10.0.19044
- Node.js version: v16.13.2
- Browser: WebKit

**Describe the bug**

To reproduce the bug, open any page in Playwright's WebKit browser. For example, `www.google.com` can be opened by running the following command in a directory where Playwright is installed:

```cmd
npx playwright wk www.google.com
```

Then evaluate `navigator.userAgent` and `navigator.platform` using Playwright's built-in web inspector tool. The following output is from the first page load on my Windows machine:

![image](https://user-images.githubusercontent.com/22433652/152914027-90bc24c7-3122-47e3-ab21-00f6aff0b0a7.png)

The highlighted text emphasizes the fact that the platform reported by the userAgent field is *Macintosh instead of Windows*. If I refresh the page, I get the following output:

![image](https://user-images.githubusercontent.com/22433652/152914468-633f7682-f122-4f4f-b36d-7f4e2500c268.png)

`navigator.platform` does not change, but `navigator.userAgent` now reports that the platform is *Windows rather than Macintosh*.

**Why does this matter?**

Some libraries rely on `navigator.platform` and some libraries rely on `navigator.userAgent` for localization purposes. In the context of input localization, `navigator.platform` and `navigator.userAgent` disagreeing on the host platform can lead to cases in which one library expects Mac shortcuts while the other library expects Windows shortcuts. In fact, the aforementioned issue has resulted in a myriad of WebKit test failures for the team I work on.

**Comment by kycutler** [comment]
Linking #8406 since it would close this issue.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by fluxx030** [comment]
is this support added , if not then is there any other way to chage value of navigator.platform ?

i am trying using evaluate method but its not working , if you have any other idea please let me know 

here is my code ::

```
const { firefox } = require("playwright");

(async () => {
  const context = await firefox.launchPersistentContext('userDataDir', {
    stealth: true,
    headless: false,
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/108.0",
    bypassCSP: true


  });
  const page = await context.newPage();
  
  await page.evaluate(() => 
    Object.defineProperty(navigator, 'platform', {
      value: 'Win32',
      configurable: true,
    })
  );
  await page.waitForTimeout(2000);
  console.log(`Navigator platform: ${platform}`);
  await page.goto('https://abrahamjuliot.github.io/creepjs/');
  const platform = await page.evaluate(() => navigator.platform);




  // await context.close();
})();
```
