### ISSUE TITLE
[BUG] Python API Doc sample code for async page.expect_response is wrong

### ISSUE THREAD

**Issue by sthemeow** [microsoft/playwright#11929]
**Context:**
- **API Documentation**
- Playwright Version: 1.18 (and other versions, too)
- Operating System: All
- Browser: Chromium

In the Python API documentation [Page.expect_response](https://playwright.dev/python/docs/next/api/class-page#page-expect-response)

Below the sample code does not work, because the highlighted two lines are short of the keyword "await". (expect_resquest sample code has the correct syntax though)
![image](https://user-images.githubusercontent.com/58959183/152963034-661ec483-3235-4b79-b91f-4c9d9b604874.png)

The correct code should be as follows:
![image](https://user-images.githubusercontent.com/58959183/152962889-c82818a7-aa85-4b76-9c41-3dd6dde2d153.png)

This is not very important but could be a hassle for people who are new to Playwright.

**Comment by pavelfeldman** [comment]
Thanks! Fixed in 3a898c285ecbe9c1fe6ac4f6ccef8d4fefca3b93
