### ISSUE TITLE
[BUG] electron.launch: Process failed to launch on Ubuntu github action

### ISSUE THREAD

**Issue by cawa-93** [microsoft/playwright#11932]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Ubuntu 20.04.3
- Node.js version: 16
- Browser: Electron
- Extra: Github action https://github.com/cawa-93/vite-electron-builder/runs/5109754099?check_suite_focus=true

**Describe the bug**

I'm trying to run a simple electron test on different platforms. The test works on Windows (In GH action and on the local machine), on macos in GH action but does not work on Ubuntu in GH action. Unfortunately, I do not have the ability to test this on Ubuntu on a local machine.

```
Error: electron.launch: Process failed to launch!
 ❯ tests/e2e.spec.ts:10:31
      8| 
      9| beforeAll(async () => {
     10|   electronApp = await electron.launch({args: ['.']});
       |                               ^
     11| });
     12| 
```

**Comment by pavelfeldman** [comment]
What is your Electron version?

**Comment by cawa-93** [comment]
I tested only the last few versions:
- 17.0.0
- 16.0.8
- 16.0.7 
- 16.0.6

I observe the described problem in each of them

**Comment by pavelfeldman** [comment]
Try setting `DEBUG=pw:browser*` env variable and see what it fails with.

**Comment by cawa-93** [comment]
```node
2022-02-08T20:22:15.786Z pw:browser <launching> /home/runner/work/vite-electron-builder/vite-electron-builder/node_modules/electron/dist/electron --inspect=0 --remote-debugging-port=0 .
2022-02-08T20:22:15.805Z pw:browser <launched> pid=1787
2022-02-08T20:22:15.932Z pw:browser [pid=1787][err] Debugger listening on ws://127.0.0.1:43203/0ba29638-8674-4f02-86b3-192a66ef6044
2022-02-08T20:22:15.932Z pw:browser [pid=1787][err] For help, see: [nodejs.org/en/docs/inspector](https://nodejs.org/en/docs/inspector)
2022-02-08T20:22:15.932Z pw:browser <ws connecting> ws://127.0.0.1:43203/0ba29638-8674-4f02-86b3-192a66ef6044
2022-02-08T20:22:15.944Z pw:browser <ws connected> ws://127.0.0.1:43203/0ba29638-8674-4f02-86b3-192a66ef6044
2022-02-08T20:22:15.946Z pw:browser [pid=1787][err] Debugger attached.
2022-02-08T20:22:16.264Z pw:browser <ws disconnected> ws://127.0.0.1:43203/0ba29638-8674-4f02-86b3-192a66ef6044
2022-02-08T20:22:16.267Z pw:browser [pid=1787] <process did exit: exitCode=null, signal=SIGTRAP>
2022-02-08T20:22:16.268Z pw:browser [pid=1787] starting temporary directories cleanup
2022-02-08T20:22:16.273Z pw:browser [pid=1787] finished temporary directories cleanup
```

**Comment by pavelfeldman** [comment]
Hm, I'm not sure what is happening here. signal=SIGTRAP suggests a breakpoint :/. We have our Electron tests running on the GHA, on all 3 platforms: https://github.com/microsoft/playwright/runs/5118344471?check_suite_focus=true

**Comment by andreabisello** [comment]
@cawa-93 i have a similar problem on container running the playwright official image https://hub.docker.com/_/microsoft-playwright . sometime i obtain electron.launch: Process failed to launch! with no debug informations , as you can see in the screenshot.

![image](https://user-images.githubusercontent.com/2149815/160383645-e6a55997-a21b-478d-b1d2-ca06f3332b05.png)


Some time if i destroy the container and i run again with the same commands , electron work.
I think the problem is related with electron, not with playwright, but i'm calling for your help about this row

`
 run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e

`

maybe the problem is related with xvfb , what about these parameters? i run tests with

npx playwright test

how i can pass to it?

thanks

**Comment by andreabisello** [comment]
@pavelfeldman not working for me,
using electron 18.2.0 running on a linux docker container,
even using the solution proposed by @cawa-93 
that is, for me:

`xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" -- npx playwright test
`

often, not every time, i got this


```
playwright                |   pw:browser [pid=432] <process did exit: exitCode=255, signal=null> +22ms
playwright                |   pw:browser [pid=432] starting temporary directories cleanup +0ms
playwright                |   pw:browser [pid=194] <kill> +5ms
playwright                |   pw:browser [pid=194] <will force kill> +0ms
playwright                |   pw:browser [pid=194] starting temporary directories cleanup +1ms
playwright                |   pw:browser [pid=194] finished temporary directories cleanup +35ms
playwright                |   pw:browser [pid=301] <kill> +0ms
playwright                |   pw:browser [pid=301] <will force kill> +0ms
playwright                |   pw:browser [pid=301] starting temporary directories cleanup +0ms
playwright                |   pw:browser [pid=301] finished temporary directories cleanup +0ms
playwright                |
playwright                |
playwright                |   1) cades_sign.spec.ts:26:14 › Start the sign › Electron - sign a document with cades =============
playwright                |
playwright                |     electron.launch: Process failed to launch!
playwright                |

```

any suggestion?

thanks

**Comment by ncaq** [comment]
I solve to env of extends.

~~~ts
env: { ...process.env, NODE_ENV: 'development' },
~~~

**Comment by fchretienow** [comment]
Same problem here, @ncaq : where do you add this code?

**Comment by ncaq** [comment]
@fchretienow 

```ts
  const electronApp = await electron.launch({
    args: ['app/main.js'],
    env: {
      // 環境変数を完全に改変してしまうとX11関係のセッションも消滅してしまうため引き継ぐ必要がある。
      ...process.env,
      // REDUX Toolkitなどの警戒度を上げるために開発モードで起動する。
      NODE_ENV: 'development',
    },
  });
```
