### ISSUE TITLE
Requesting support for  test.use({storageState: }) when using physical Android device

### ISSUE THREAD

**Issue by kevanous** [microsoft/playwright#11939]
In our project, we would like to test on actual physical android devices (mobile and tablets). Our tests we have currently uses storageStage to login as different users (permission levels) and those are determined on the spec file using `test.use({storageState: 'path of the cookie json file'})`
This is great way to do what we need. But if we want to do similar for the tests in android, we cannot do that. This is a big blocker for us. 
I think adding the same reauth feature for android device that we already have for desktop/emulator runs makes sense as its adds consistency for us users and I am sure many would be taking advantage of this. 
If not using a fixture, I can see the spec file looking like this if this feature is added:

```
test.describe(
  'Going to Sauce Demo in Physical Android Device connected via USB and ADB',
  () => {
    test.use({
      storageState: './qe-ui/session-storage/standard-user-credentials.json',
    });
    test('Page header is as expected in android', async () => {
      const [device] = await android.devices();
      const context = await device.launchBrowser();
      const page = await context.newPage();
      await page.goto('https://www.saucedemo.com/inventory.html');
      await expect(page.locator('span.title')).toHaveText('Products');
    });
  }
);
```

**Comment by pavelfeldman** [comment]
You can run `context.addCookies` and pass the auth cookies, similarly you can use `context.addInitScript` to populate local storage, depending on what you need.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
