### ISSUE TITLE
[Feature] Optionally take a full page screenshot when test run is failed

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#11947]
How to take full page screenshot when test run is failed? i can see it is able to take the screenshot of viewable page. but it would be more helpful if we have full page option as well.

**Comment by pavelfeldman** [comment]
You can add an afterEach hook that would look at the testInfo and if the testInfo has errors, capture the page screenshot.

**Comment by 1996phani** [comment]
okay, thank you. But instead, if we can have it as a config that would be a great option other than user handling that explicitly.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by frasu** [comment]
Isn't that the solution? https://github.com/microsoft/playwright/issues/9983
