### ISSUE TITLE
[Question] - Timeout while waiting for event "response"page.waitForResponse in AWS instance 

### ISSUE THREAD

**Issue by selvakumarram** [microsoft/playwright#11957]
I am using the below line to validate network calls. Always passed in our local machine but its getting timeout in AWS instance  with the below error: 

**TimeoutError: page.waitForResponse: Timeout while waiting for event "response"page.waitForResponse: Timeout while waiting for event "**

const [joinResponse] = await Promise.all([
      await page.waitForResponse(
        (res) =>
          res.status() == 202 &&
          res.url().endsWith('example/session')
      ),
    ]);

Please clarify my query

**Comment by pavelfeldman** [comment]
Promise.all only makes sense when ran with array of elements, you are missing an action that actually triggers the request itself. Promise.all also accepts promises, not objects. Please refer to our docs: https://playwright.dev/docs/network#network-events.
