### ISSUE TITLE
Does Playwright support react hybrid app automation in mobile?

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#11963]
Does Playwright support Hybrid app automation?
we have a use case where need to test the hybrid app in an Electron container on a desktop as well as in a hybrid mobile app. I haven't seen anything related to this in the documentation.  Could you please confirm?

**Comment by keshavmunagala** [comment]
Do we have this feature in playwright ?

**Comment by pavelfeldman** [comment]
No such feature! Please file a feature request with the steps we could follow and we'll put it into the P3-collecting-feedback incubator. Once there are enough upvotes, we'll prioritize it!
