### ISSUE TITLE
[Question] How to maintenance test with a big number of users

### ISSUE THREAD

**Issue by Marcin3** [microsoft/playwright#11968]
Hello, 

I am looking for any advice on how to run the test in this configuration.

- 1 environment
- 20 groups of tests - all in different folders. Some groups use more than 2 users to login
- 20 scripts for run test in package json.

I think about having one `global-setup.ts `and the start all test form `test.use({ storageState: 'adminStorageState.json' });` like it is describe here  https://playwright.dev/docs/test-auth#multiple-signed-in-roles.
Problem is that we will run method login a lot of time in `global-setup.ts` and this will slow down the execution. We could add some flag and then if else or switch but I am not sure if it is the best idea.
Any idea how we could fix this problem? 

I asked this question also on the slack channel but there was zero response. Maybe here I will have more luck

**Comment by pavelfeldman** [comment]
We have a doc for you: https://playwright.dev/docs/test-auth#reuse-signed-in-state
