### ISSUE TITLE
[BUG] exit code 1 when throwing error in event handler

### ISSUE THREAD

**Issue by YousefED** [microsoft/playwright#11989]
**Context:**
- Playwright Version: 1.18.1
- Operating System: github actions (ubuntu)
- Node.js version: 16
- Browser: chromium

**Code Snippet**

fixture: 
```typescript
export function addFilterToBrowserContext(context: BrowserContext) {
  const listener = (request) => {
    if(request.url().includes("google.com")) {
        throw new Error("should not have requests to google");
    }
  };
  // make sure tests don't do requests to production environment
  context.on("request", listener);
}

// A fixture that overrides the built-in
// context and browser options
// to make sure no network requests are made against certain domains
export const test = base.extend({
  browser: async ({ browser }, use) => {
    const oldFunc = browser.newContext;
    browser.newContext = async (options?: BrowserContextOptions) => {
      const ret = await oldFunc.call(browser, options);
      addFilterToBrowserContext(ret);
      return ret;
    };
    await use(browser);
  },
  context: async ({ context }, use) => {
    addFilterToBrowserContext(context);
    await use(context);
  },
});

export { expect } from "@playwright/test";
```

test:
```typescript

test("block request to google", async ({ context }) => {
   test.fail();
   const page = await context.newPage();
   await page.goto("https://www.google.com");
   await page.close();
});
```

**Describe the bug**

I've created this fixture to make sure my app does not make any requests to my production URL (but you could use it to validate whether your app doesn't make any requests to an external party, etc.).

Issue: 

The test validates whether the filter works correctly. I use `test.fail()` for this, and this works. The test passes. However, playwright exits with code 1, causing the CI to fail

**Comment by pavelfeldman** [comment]
You are throwing an unhandled exception and we have no idea whether you did this on purpose or something went wrong. Negative tests are still supposed to behave, i.e. they are supposed to fail, but in their own control flow, not with a stray unhandled exception.

Starting with v1.19 (live in a couple of days), you can do
```js
expect(request.url()).not.toContain("google.com")
```

in the event listener. This gives us enough clues to consider the failure intended. Before that, you could store all invalid requests in array and then assert that array is empty in the end of the test. That way you are failing the test's own control flow.

**Comment by YousefED** [comment]
> Starting with v1.19 (live in a couple of days), you can do
> 
> ```js
> expect(request.url()).not.toContain("google.com")
> ```

That's great to hear! Afaik, this would have the unintended consequence of polluting the logs with a lot of passed assertions in case nothing is wrong. Is there a way to silence this specific assertions?

> Before that, you could store all invalid requests in array and then assert that array is empty in the end of the test.

That's a smart solution. Only disadvantage is that it the app will still continue hitting "wrong" URLs for a bit, but it might be an acceptable trade-off.

---
Related: does my approach to override browser and context make sense, in order to kind of implement a "global request handler"?

**Comment by pavelfeldman** [comment]
> That's great to hear! Afaik, this would have the unintended consequence of polluting the logs with a lot of passed assertions in case nothing is wrong. Is there a way to silence this specific assertions?

Should not pollute the logs, but yes, those show up in the report. No way to mute those atm.

> That's a smart solution. Only disadvantage is that it the app will still continue hitting "wrong" URLs for a bit, but it might be an acceptable trade-off.

That would be after the test ended, so should not be an issue?

> Related: does my approach to override browser and context make sense, in order to kind of implement a "global request handler"?

Context fixture override is perfect. `browser.newContext = ` isn't pretty, but I don't have a better solution for you. I've seen a request for `browser.on('context')` before, but it did not get traction. You have a valid use case for it, so you can file this feature request again. If you feel like contributing the PR, it wouldn't need to wait - otherwise our backlog is full...

**Comment by dgozman** [comment]
It seems like everything is resolved here.
