### ISSUE TITLE
[Question] - how to add custom informations to configuration choosing from command line ? e.g. test - production

### ISSUE THREAD

**Issue by andreabisello** [microsoft/playwright#11983]
i would like o execute the same test in different environment, for example, in test environment before a production deploy and in production environment after a production deploy. [globalSetup](https://playwright.dev/docs/test-advanced#global-setup-and-teardown) looks like what i need, but it looks like to shot a fly with a cannon.

i need to be able to "switch" the configuration file by command line, and the only way i'm finding is to create two different playwright.config.ts file, choose the one i need, and in the playwright.config.ts file load a globalSetup file that load the right configuration in someway.

another example,

i simply need to store username - password of differents users in differens environment, but test still the same. i need to select theme with a command line options.

Any help or suggestion?

thanks

**Comment by pavelfeldman** [comment]
You can either use environment (process.env) or parametrize project as in https://playwright.dev/docs/test-parameterize.

**Comment by dgozman** [comment]
To expand on the `process.env` solution:

```ts
// playwright.config.ts
const config = {
  globalSetup: process.env.MODE === 'test' ? './test-global-setup.ts' : './production-global-setup.ts',
};
export default config;
```

Run it like this:
```bash
MODE=production npx playwright test
```

**Comment by andreabisello** [comment]
i will try. then maybe i will try to improve documentation with a pull rquest. thanks.

**Comment by dgozman** [comment]
@fede1911 If you just have some helper function like this `configFunction()`, you can put it to any helper file, e.g. `config-helper.ts`. Then, import it from anywhere with `import { configFunction } from './config-helper.ts'` - from the global setup, from the `playwright.config`, from a test file.

**Comment by andreabisello** [comment]
@dgozman so global-setup can be used to load a configuration from external file once, export it as a module, and import it where necessary, right?


thanks
