### ISSUE TITLE
whenever I run in debug mode windows are displayed outside my screen

### ISSUE THREAD

**Issue by xpillons** [microsoft/playwright#11987]
**Context:**
- Playwright Version: 1.18
- Operating System: Windows 11
- Node.js version: 14.19
- Browser: Chromium
- Extra: Running in Ubuntu 20.04 in WSL2 from VSCode

```
## System:
 - OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
 - Memory: 2.36 GB / 7.73 GB
 - Container: Yes## System:
 - OS: Linux 5.10 Ubuntu 20.04.2 LTS (Focal Fossa)
 - Memory: 2.36 GB / 7.73 GB
 - Container: Yes
## Binaries:
 - Node: 14.19.0 - /usr/bin/node
 - npm: 8.4.1 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
## Binaries:
 - Node: 14.19.0 - /usr/bin/node
 - npm: 8.4.1 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
 ```

** config **

```
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
//    testDir: './tests',
    /* Maximum time one test can run for. */
    timeout: 30 * 1000,
    /* Retry on CI only */
    retries: process.env.CI ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : undefined,
    globalTimeout: 60 * 60 * 1000,
    snapshotDir: './snapshots',
    reporter: process.env.CI ? 'html' : 'dot',
    use: {
        headless: true,
        baseURL: process.env.AZHOP_FQDN,
        viewport: { width: 1600, height: 900 },
        screenshot: 'only-on-failure',
        httpCredentials: {
            username: process.env.AZHOP_USER,
            password: process.env.AZHOP_PASSWORD
        },
        trace: 'on-first-retry',
    },
};
export default config;

```

**Describe the bug**

if I run my test in debug mode I can see the browser and the inspector windows in the task bar, but they can't be moved or displayed on my screen. I'm using a dual screen, and even on a single screen it's the same. 

How to force the viewport to always start at the same position on the screen ?

**Comment by pavelfeldman** [comment]
I don't think we support GUI when running on win under WSL2.

**Comment by xpillons** [comment]
this is using X Windows and was working on Windows 10. now on Windows 11 it works one time as I was able to run in debug an record actions. But when I tried a second time in the exact same context, these windows appears as icons on my task bar.

**Comment by xpillons** [comment]
@pavelfeldman got it to work.
Here what is needed :

- Setup X-Server on Windows, like explained here https://medium.com/javarevisited/using-wsl-2-with-x-server-linux-on-windows-a372263533c3
- Retrieve the IP address of WSL : ipconfig will tell you
- Start X-Server
- export DISPLAY=<WSL IP>:0

Now you can run your tests using the Windows GUI ;-)

**Comment by pkerschbaum** [comment]
WSL 2 has "native" GUI support for some time, it is called "WSLg", see [microsoft/wslg](https://github.com/microsoft/wslg).  
I use Playwright quite successfully with it, but the issue that the Window is not visible (even though the icon appears in the Windows taskbar) has also occured to me sometimes.

But **this also happened with Cypress**. I am pretty sure it is a WSLg issue, also considering that the workaround of @xpillons above switches from WSLg to a X-Server.  
There are many issues regarding Window positioning/appearance in the [microsoft/wslg](https://github.com/microsoft/wslg) repository, I think WSLg still just has some rough edges...

**Comment by kbarendrecht** [comment]
I understand this doesn't help anyone with this issue, but for the sake of providing feedback: It works out the box for me with WSLg on Windows 11 👍🏻

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
