### ISSUE TITLE
[BUG] resource timing is inconsistent on webkit for loadingFinished

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#11986]
See [this comment](https://github.com/microsoft/playwright/pull/8668#issuecomment-916631273):

> Tried debugging this on webkit, event.timestamp values were wrong for the `loadingFinished` event. Even though the `responseReceived` fires before the `loadingFinished`, the event timestamp value for `responseReceived` is higher than that of `loadingFinished`. 
>
> ```
> // relative to request timestamp value. 
> _onResponseReceived -  43.539 ms
> _onDataReceived  - 44.039 ms
> _onLoadingFinished -  42.445 ms
> ```
>
> Should we skip this test on webkit? 

And the test in the PR that exposes this: https://github.com/microsoft/playwright/pull/8668

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
