### ISSUE TITLE
[Question] How to wait until all matching elements disappear

### ISSUE THREAD

**Issue by hornta** [microsoft/playwright#11988]
I need to wait until all elements for a matching locator disappears. Is this possible?

```js
const locator = page.locator("input");
await locator.count(); // 12
// wait until there are no <input>
await locator.count(); // 0
```

EDIT:
I solved it by doing this but it feels quite hacky and ugly. Also I would need some timeout so it doesn't end up in an infinite loop? Is there a nicer way?
```js
while(await spinners.count() > 0) {}
```

**Comment by pavelfeldman** [comment]
This will wait:

```js
await expect(locator).toHaveCount(0);
```

**Comment by pavelfeldman** [comment]
Closing this as resolved, check out more assertions here: https://playwright.dev/docs/test-assertions
