### ISSUE TITLE
[Question] is parallelism and sharding available for java based playwright?

### ISSUE THREAD

**Issue by Divine1** [microsoft/playwright#12002]
i was looking into the docs and i came across `parallelism and sharding` feature for nodejs based version of playwright.
is `parallelism and sharding` feature available for java based version of playwright? i'm not able to find details related to it in docs.
Where can i find it?

![image](https://user-images.githubusercontent.com/10482177/153398817-c839c6a4-86dc-4925-9c83-a4ba5a3a6aee.png)

**Comment by ltsuda** [comment]
This is specifically to Playwright's Test Runner, not the library itself, so only for Node.

For Java, depends on the test runner but I think this page should help.
https://playwright.dev/java/docs/test-runners#running-tests-in-parallel
