### ISSUE TITLE
[BUG] : Video and Trace shows empty screen when run via chrome@latest:Windows 10@browserstack

### ISSUE THREAD

**Issue by fa66-coder** [microsoft/playwright#12001]
**Context:**
- Playwright Version:     "playwright": "^1.17.2",
- Operating System: windows
- Node.js version: v12.15.0
- Browser: chrome@latest:Windows 10@browserstack

**Describe the bug**

I can see the trace.zip and video file generated, when tried to open it shows the traceview screen with no details on it ( all blank white, refer the screenshot below).

![image](https://user-images.githubusercontent.com/23632073/153361215-fe048111-1bf7-4882-a1ac-a9a2bc4ec71d.png)

**Code Snippet**

// playwright.config.ts
import { PlaywrightTestConfig, devices } from '@playwright/test';
const ENV = process.env.ENV;

const config = {
  //if you pass forbidOnly, then you are not allowed to run focused tests
  forbidOnly : !!process.env.CI,
  testDir: 'tests',
  testMatch: '**/*.spec.ts',
  // Use globalSetup & globalTearedown only if browserstack.local = true
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: require.resolve('./global-teardown'),
  actionTimeout : 60000,
  timeout: 6*60*1000,
  reporter: [['html', {open: 'never' }]],
  use:{
    navigationTimeout :  4*60*1000,
    screenshot: 'on',
    video:'on',
    trace: 'on',
  },
  projects: [
    // -- BrowserStack Projects --
    // name should be of the format browser@browser_version:os os_version@browserstack
    {
      name: 'chrome@latest:Windows 10@browserstack',
      use: {
        browserName: 'chromium',
        viewport: { width: 1920, height: 1080 },  // This option will ensure that the viewport uses the entire screen
      },
    }
  ],
  expect: {
    timeout: 60000,
    toMatchSnapshot: {
      threshold: 1,
    },
  }
};
export default config;

**whereas the below lines records the trace properly when added in the test case:**

  const vBrowser = await chromium.connect(
          `wss://cdp.browserstack.com/playwright?caps=` +
          `${encodeURIComponent(JSON.stringify(caps))}`,);
        const context = await vBrowser.newContext();
      const vPage = await context.newPage();
    await context.tracing.start({ screenshots: true, snapshots: true });
      await use(vPage);
      const testResult = {
        action: 'setSessionStatus',
        arguments: {
          status: testInfo.status,
          reason: nestedKeyValue(testInfo, ['error', 'message'])
        },
      };
      await vPage.evaluate(() => {},
      `browserstack_executor: ${JSON.stringify(testResult)}`);
  const resp:any = await vPage.evaluate(_ => {}, `browserstack_executor: ${JSON.stringify({action: 'getSessionDetails'})}`);
   await context.tracing.stop({ path: 'trace.zip' });
      await vPage.close();
      await context.close();
      await vBrowser.close();
   
   And one more issue with the above line is path is not working if I give a path ./tests-results/trace.zip

**Comment by pavelfeldman** [comment]
Please file it with Browserstack!

**Comment by fa66-coder** [comment]
@pavelfeldman -  But my concern is if there is an issue from BrowserStack trace.zip then outside the test-results directory should also appear empty but I am able to see the recording in trace.zip with the same setting outside the test-results dir

And also mentioned an another issue in the description about the path in trace.zip

**Comment by tilwinjoy** [comment]
I have the same issue as well!
