### ISSUE TITLE
[BUG] exposeBinding does not work with content scripts in Chromium

### ISSUE THREAD

**Issue by Banou26** [microsoft/playwright#12017]
**Context:**
- Playwright Version: ^1.18.0
- Operating System: Windows
- Node.js version: 17.1.0
- Browser: Chromium

**Code Snippet**

```javascript
// index.js
(async () => {
  const { chromium } = require('playwright')
  const pathToExtension = require('path').join(__dirname, './ext')
  const userDataDir = require('path').join(__dirname, './tmp/test-user-data-dir')
  const browserContext = await chromium.launchPersistentContext(userDataDir, {
    headless: false,
    args: [
      `--disable-extensions-except=${pathToExtension}`,
      `--load-extension=${pathToExtension}`
    ]
  })
  const page = await browserContext.newPage()

  await page.exposeBinding('foo', async (_, data) => {
    console.log('data', data)
  })
  await page.goto('https://google.com')
  await browserContext.close()
})()
```

Having the extension content-script context code call exposed functions doesn't work
```javascript
// content-script.js
foo() // throws Uncaught Error: Invalid arguments: should be exactly one string.
foo({}) // throws Uncaught Error: Invalid arguments: should be exactly one string.
foo(1) // throws Uncaught Error: Invalid arguments: should be exactly one string.

foo('') // crashes Playwright
```

**Describe the bug**

Calling exposed functions from an extension context doesn't work as expected.
It either throws `Uncaught Error: Invalid arguments: should be exactly one string.`

or crashes playwright by throwing
```
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Function.dispatch (C:\Users\Banou\Desktop\playwright-ext\node_modules\playwright-core\lib\server\page.js:579:14)
    at Page._onBindingCalled (C:\Users\Banou\Desktop\playwright-ext\node_modules\playwright-core\lib\server\page.js:251:23)
    at FrameSession._onBindingCalled (C:\Users\Banou\Desktop\playwright-ext\node_modules\playwright-core\lib\server\chromium\crPage.js:849:37)
```

**Comment by gsidsid** [comment]
+1 Have been waiting for a fix on this as well

**Comment by LanderBeeuwsaert** [comment]
We're experiencing this too when we try to change from launching our tests & playwright with:
"node --experimental-loader esbuild-node-loader ./parallel-test.ts"
to
"npx tsx ./parallel-test.ts"
when calling in the browser javascript code the exposed binding it gives the error

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by James4Ever0** [comment]
+1

**Comment by sebastiancarlos** [comment]
+1 for reopening too
