### ISSUE TITLE
[Question] Playwright redirects instead of opening accordion

### ISSUE THREAD

**Issue by trufa** [microsoft/playwright#12013]
I'm trying to automate the google login process for an app that's not yet verified hence I'm trying to click on the following link:

[![enter image description here][1]][1]

Which opens the accordion so:

[![enter image description here][2]][2]

I'm doing:

    await popup.click('[jsname="BO4nrb"]');

Google's html is:

    <a href="#" jsname="BO4nrb" class="xTI6Gf vh6Iad">Advanced</a>

Unlike the native browser behaviour when I run the tests (with `--headed`) the accordion doesn't open but instead I'm redirected to https://accounts.google.com/#.

For some reason google's `onclick` javascript is not firing when simulated by playwright and I'm being redirected to `#`

I don't really care to simulate this properly since this is a temporary situation so any hacky solution will also do.

Thanks in advance!

  [1]: https://i.stack.imgur.com/HBCHOm.png
  [2]: https://i.stack.imgur.com/wd31am.png

**Comment by pavelfeldman** [comment]
Google login process is designed specifically in a way that it can't be automated:

https://support.google.com/accounts/answer/7675428?hl=en
