### ISSUE TITLE
[BUG] full page screenshot is not full

### ISSUE THREAD

**Issue by sqandrew** [microsoft/playwright#12028]
the same issue described here https://github.com/microsoft/playwright/issues/5487 reproduced in the last release (we updated the playwright feb 09 2022)

iPhone 12 (< 800 px height) - full screen is not full
iPhone X (> 800 px height) - full screen (2724 px height) is OK

**Comment by pavelfeldman** [comment]
Could you provide steps to reproduce?

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
