### ISSUE TITLE
[BUG] Chromium '--window-position=0,0' flags cause Firefox to open an invalid window

### ISSUE THREAD

**Issue by henrydzung** [microsoft/playwright#12029]
- Playwright Version: v1.18.1
- Operating System: Windows
- Node.js version: v16.13.1
- Browser: Firefox

**Code Snippet**

``` typescript
import test from '@playwright/test';

test.use({
  headless: false,
  launchOptions: {
    args: ['--window-position=0,0'],
  },
});

test('bug test', async ({ page }) => {
  await page.goto('https://example.com');
});
```

**Describe the bug**

If I use `--window-*something*=0,0` chromium flag and run with Firefox. It will open an additional window and navigate to an invalid URL.

![image](https://user-images.githubusercontent.com/49341662/153601994-63e2cf3e-e807-437f-aea7-e8416a5b37cd.png)

**Comment by pavelfeldman** [comment]
> If I use --window-*something*=0,0 chromium flag and run with Firefox. It will open an additional window and navigate to an invalid URL.

Please don't use Chromium flags with Firefox!
