### ISSUE TITLE
[BUG] Video file is locked after closing when combined with a screenshot in chromium

### ISSUE THREAD

**Issue by hornta** [microsoft/playwright#12032]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows 10 & Ubuntu 20
- Node.js version: v16.10.0
- Browser: Chromium, Not WebKit or Firefox

**Code Snippet**

```javascript
import { rm } from "fs/promises";
import { chromium } from "playwright";

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    recordVideo: { dir: "myFolder" },
  });
  const page = await context.newPage();
  await page.goto("https://github.com/");
  await page.screenshot({
    path: "myFolder/myScreenshot.png",
  });
  await browser.close();

  await rm("./myFolder", { recursive: true });
})();
```

**Describe the bug**

When a screenshot is taken in combination with a video for a playwright session the video file seems to be locked after closing the browser instance which causes operations on the video file to fail. The bug doesn't occur when I only record a video. It doesn't matter if the screenshot is placed in the same directory as the video. This seems to be only a problem with Chromium. I've tested Webkit and Firefix.

```
[Error: EBUSY: resource busy or locked, unlink 'xxxxxxx\myFolder\d6de40214921ed4c689024904e2adfdc.webm'] {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'unlink',
  path: 'xxxxxxx\\myFolder\\d6de40214921ed4c689024904e2adfdc.webm'
}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
