### ISSUE TITLE
[Question] How to mirror the default CDN?

### ISSUE THREAD

**Issue by SK-415** [microsoft/playwright#12035]
The default CDN used to download browser zips sometimes really slow under the GFW and it could be a challenge for some of my users to prepare their own proxy. So I'm planning to make a mirror site for playwright browser zips, but I couldn't find a page which shows all available versions of browser zips.
Is there an easier way to get download links for all the versions and platforms browser zips at once? Otherwise I had to collect the links from each version of the packages.

**Comment by pavelfeldman** [comment]
There is no central location with the links, so collecting them like you do is the only way at the moment.
[packages/playwright-core/src/utils/registry.ts](https://cs.github.com/microsoft/playwright/blob/7e7996a7b717830356531856496c78ffdb4d5d46/packages/playwright-core/src/utils/registry.ts?q=packages%2Fplaywright-core%2Fsrc%2Futils%2Fregistry.ts#L54) has a list of templates that you can use to make sure you pick browsers for each platform.

**Comment by SK-415** [comment]
Thanks for the quick reply, the templates helps a lot!
It would still be nice if the central links page could be a new feature. Therefore, some more professional organizations may take over the job. :D
