### ISSUE TITLE
[Question] Can Playwright connect to existing running Firefox browser over Juggler protocol?

### ISSUE THREAD

**Issue by janeyaoag** [microsoft/playwright#12044]
Hi there,

I am trying to use Playwright to test a browser extension in Firefox and I'm having some issues connecting Playwright to the Firefox browser. I have got the extension loaded into the browser using:
```
  await webExt.cmd.run(
    {
      sourceDir: pathToExtension,
      firefox: playwright.firefox.executablePath(),
      args: [`-juggler=1234`, `--remote-debugging-port`],
    },
    {
      shouldExitProgram: false,
    }
  );
})();
```
as recommended by [this post](https://github.com/microsoft/playwright/issues/2644#issuecomment-647842059).
When this is run, a new Firefox window is open with the extension loaded, but fails when it attempts to connect Playwright to Firefox using `playwright.firefox.connect({ wsEndpoint });` where `wsEndpoint` is the address from the "Juggler listening on" message Firefox outputs. I am then unable to start driving the browser.

**Is there a better way to connect a websocket endpoint to an existing Firefox page using Playwright?** [This post](https://github.com/microsoft/playwright-python/issues/183#issuecomment-687521938) mentions that Playwright will be switching to its own RPC, would this mean that Playwright would not be able to connect websocket endpoints with browsers?

I also played around with Playwright's `.launchServer()` which seems to be using an internal server hosted by Playwright, and was able to create a `wsEndpoint` which I used with `.connect()` to connect to the browser and start driving in a new context. So it looks like there should be a way of using `.connect()` in our case with the extension loaded by perhaps doing what `.launchServer()` is doing behind the scenes, but just not quite sure which pieces to put together.

Any help would be great! Thanks in advance :heart:

**Comment by pavelfeldman** [comment]
Unfortunately that method no longer works. If there is no way to run Firefox w/ extension from command line, we can'd do anything about it. @aslushnikov

**Comment by aslushnikov** [comment]
Closing this in favor of https://github.com/microsoft/playwright/issues/7297
