### ISSUE TITLE
[internal] MS Edge Dev on Win/Linux is failing

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12059]
https://github.com/microsoft/playwright/runs/5165363419?check_suite_focus=true

Repro:

1. `$env:PWTEST_CHANNEL="msedge-dev"`
2. `npm run ctest -- page-check --max-failures 1`

**Comment by aslushnikov** [comment]
This is dupe of https://github.com/microsoft/playwright/issues/11754

**Comment by mxschmitt** [comment]
Ubuntu: 100.0.1163.1-1
Mac: 100.0.1167.0
Windows: 100.0.1163.1

Seems like we just have to wait that they release a new version.

**Comment by mxschmitt** [comment]
fixed!
