### ISSUE TITLE
[Question] Best Azure Hosting Option?

### ISSUE THREAD

**Issue by tonymuu** [microsoft/playwright#12057]
Hi, I was wondering what's the best hosting option on Azure is, for a Playwright web scraper job, written in .NET 6? I tried using the Azure Web Jobs, but was running a lot of issues with running the browser. I searched around and found some docs for deploying to Azure function with a custom docker image. Is that the best way to do so? Or would I need to rewrite the project using Node.js? Much thanks!

**Comment by mxschmitt** [comment]
This should fit very well and is not depending on the language: https://azure.microsoft.com/en-us/services/container-apps/
