### ISSUE TITLE
[BUG] Right click when using recorder does not record the event

### ISSUE THREAD

**Issue by joeapinder** [microsoft/playwright#12058]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Windows
- Node.js version16.13.2
- Browser: [Chrome]
- Extra: Running against angular application

**Describe the bug**

If you run the recorder and you right click in a browser that event does not appear in the recorder code output window

**Comment by dgozman** [comment]
@joeapinder Right-click usually opens a context menu that Playwright does not interact with. Do you have some scenario in mind? Perhaps you could share a page url where you'd like to record the right click?
