### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by kumars3** [microsoft/playwright#12069]
I am using cucumber.js for BDD tests with Playwright and typescript. The following global configuration **PlaywrightTestConfig** attributes are not picked up during test run. My all tests are in Gherkin language (GIVEN, WHEN, THEN).  As cucumber is a very popular tool. It would be nice if the global configuration are integrate with cucumber.js test runner.

import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    video: 'on',
    screenshot: 'on',
    viewport: { width: 720, height: 1200 },
  },
  testDir: 'tests',
  timeout: 45000,
  outputDir: './test-results',
};
export default config;

**Comment by dgozman** [comment]
@kumars3 Could you share more details? How exactly do you run tests with cucumber.js? Perhaps you could share a repro with all files?

**Comment by kumars3** [comment]
@dgozman
Looks like this issue is being faced by many people. We are using playwright as browser automation tool, page object model as test design pattern and most importantly “**Cucumber.js**”( https://www.npmjs.com/package/@cucumber/cucumber)  as “test runner” which is also being used to write tests/features in BDD style (Gherkin – **GIVEN**, **WHEN**, **THEN**). This feature file is integrated back to step definition file where the logic to call page classes are written and where actions on the page/assertions are performed.
Example:
Feature file:
**Given Go to the playwright website**
Step definition:
**Given ('Go to the playwright website'**, async function (this: ICustomWorld)
{
//do something here
}

The point to be noted here is that the step name (GIVEN, WHEN, THEN) in feature file should match with their corresponding step name in step definition file otherwise the feature file will not be linked to step definition file and test will not run.
To run test, we simply run nmp run test where test = cucumber-js (please see the package.json in below repo)
The issue with PlaywrightTestConfig and possibly other features which works on ‘**test**’ block (imported from @**playwright/test**) like mobile emulation, geolocation, visual comparison(toMatchSnapshot()) etc is that these work with ‘test’ block which is in playwright test runner and which we can’t use as we are using **cucumber-js test runner**.
Inshort, we playwright script which works on ‘test’ block cannot be called through ‘cucumber.js’ test runner because these work on ‘playwright’ test runner at the moment. Also, we can’t run tests written in ‘cucumber.js’ framework using ‘playwright’ test runner.
So, playwright would be game changer in test automation world if this supports BDD/cucumber integration also.

Detailed files are in **Tally Barak**(@tallyb) playwright-cucumber repo at:
**https://github.com/Tallyb/cucumber-playwright**

Please let me know if you need more information.

cc: @aslushnikov; @mxschmitt

**Comment by mxschmitt** [comment]
It's expected that your cucumberJS does not read the playwright.config.{js,ts}. This is because the playwright.config.ts is only loaded inside the `@playwright/test` test-runner.

Closing since we can't act on it. If you're interested in an official cucumber Playwright adapter, I'd recommend to file a separate issue as a feature request.
