### ISSUE TITLE
[BUG] request.newContext doesn't take base url when is has the same origin as page.goto

### ISSUE THREAD

**Issue by israelKusayev** [microsoft/playwright#12064]
**Context:**
- Playwright Version: 1.19.0
- Operating System: mac
- Node.js version: 16.13.1
- Browser: All

I created a repo with an example https://github.com/israelKusayev/url-bug

In this repo the PAGE URL is `https://en.wikipedia.org/wiki/AA`
and the API URL is `https://en.wikipedia.org/w/api.php`

so when I try to create a request context with the API URL as the baseUrl it still sends the request to the PAGE URL

FYI I had this bug in playwright version 18 as well

**Comment by dgozman** [comment]
This is similar to #10557. URL resolution on the web works differently, not just concatenating two strings. You can try it yourself in browser developer tools with [new URL()](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), or look closely at [the docs](https://playwright.dev/docs/api/class-apirequest#api-request-new-context).

In this particular example, I'd suggest to set `baseURL` to  `https://en.wikipedia.org/w/`, and make your requests use a url like `./api.php?action=opensearch...`.

Sorry for confusion. If you have any ideas on how to improve the documentation, PRs are welcome!
