### ISSUE TITLE
[Feature] Project Setup

### ISSUE THREAD

**Issue by ddemoss222** [microsoft/playwright#12063]
In the case of API testing of multiple user types, I have run into a number of puzzling issues that seem to largely stem from initialization order issues, and found it difficult to resolve. 
In essence, I am declaring project variables "email" and "password". What I would like to do is to be able to run multiple projects and initialize the authentication to be reused within the project. 
However, when I attempt to set extraHTTPHeaders within a fixture, it fails to override the existing config. Example code:
```
  headers: [async({user}, use) => {
    const auth = JSON.parse(fs.readFileSync('authStorage.json'))

    const header = {
      extraHTTPHeaders: {
        'Authorization': `Bearer ${auth.token}`,
        'Group-Access': `ID:${auth.id},Type:All Access`
      }
    }
    await use({...header})
  }, { auto: true}],
```
So, I have as a workaround a "setup" fixture that runs ahead of each project, and at the top of the file I overwrite the existing config using
```
import { apiHeaders } from './apiHeaders'
test.use({extraHTTPHeaders: apiHeaders()})
```
The problem with this approach is I will always get flaky tests in transition, since the apiHeader() runs BEFORE processing the new authentication request. 

Ultimately it's only a small bother to be deprived of the all green dopamine hit, but I have spent far more time than I would like to admit combing through the API spec looking for alternative approaches, and I keep coming up short. It's possible/likely I missed a solution here, but a straightforward approach IMO would be "Project Setup" that runs identically to the "global setup" concept except that it also has project variables exposed and available so that I could initialize each project independently and then run them in parallel. 

It's possible too that there is an implementation issue with use @ fixtures in my case. Thanks.

**Comment by dgozman** [comment]
@demoss222 Could you please share more details? I do understand how your `test.use()` example overrides `extraHTTPHeaders`, but I am not sure how the `headers` fixture is supposed to override `extraHTTPHeaders`.

A few ideas anyway:
- Did you try to override the `extraHTTPHeaders` fixture itself? [See here](https://playwright.dev/docs/test-fixtures#overriding-fixtures) for an example.
- Did you follow the [parameterize projects](https://playwright.dev/docs/test-parameterize#parameterized-projects) guide?

**Comment by ddemoss222** [comment]
Thank you, your response was extremely helpful. Here is how I wrote it to function as intended in case anyone stumbles onto this:
```
export const test = base.extend({
  user: [{email: defaultEmail, password: defaultPassword}, { option: true }],

  extraHTTPHeaders: ({ user }, use) => {
    const authRaw = fs.readFileSync(`${user.email}.json`);
    const auth = JSON.parse(authRaw);

    const extraHTTPHeaders = {
      'Authorization': `Bearer ${auth.token}`,
      'Group-Access': `ID:${auth.id},Type:All Access`,
    }
    use(extraHTTPHeaders)
  }
})
```
Then, I established credentials at the global file.
```
async function globalSetup(config: FullConfig) {
  ...
  for (const e of emails) {
    const response = await requestContext.post(`${baseURL}/api/tokens/authentication`, {
      data: {
        ....
      }
    });
    const rb = await response.json()
    fs.writeFileSync(`${e}.json`, JSON.stringify({
      ....
    }))
  }
}
```
I will close the issue as this solve my problem.
