### ISSUE TITLE
[Question]  Error "Download Canceled" when Im trying to add extension to chromium playwright browser.

### ISSUE THREAD

**Issue by dimag32** [microsoft/playwright#12079]
Hi all,
Does anybody familiar with issue to add extension to chromium playwright browser: "Download Canceled" .

steps to reproduce:
1. open playwright browser with extension code:
https://playwright.dev/docs/chrome-extensions

2. extension Im trying to load : https://chrome.google.com/webstore/detail/simpo-plus-for-chrome/akgcbhfodokmijcidikjeegkbjmjhaia?hl=en

error i got:
![image](https://user-images.githubusercontent.com/95757204/153895351-42e81065-f13f-412e-b7f5-c9a1ffaaa866.png)

**Comment by dgozman** [comment]
@dimag32 Could you please share a repro script?

**Comment by dimag32** [comment]
Hi,

please see below the script,
the extension finally loaded , but I if im trying to do it add it via the chrome store Im still got the error.
  
public async loadExtension(): Promise<BrowserContext> {
    const pathToExtension = require("path").join(
      __dirname,
      "../../Simpo-Plus-for-Chrome"
    );
    let context: BrowserContext;
    const userDataDir = require("path").join(__dirname, "../../UserData");
    context = await chromium.launchPersistentContext(userDataDir, {
      headless: false,
      devtools: false,
      args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`,
      ],
    });
    return context;
  }

**Comment by dgozman** [comment]
@dimag32 Thank you for the snippet. Unfortunately, I still don't understand the issue. 

> the extension finally loaded

Does that mean that your snippet works?

> if im trying to do it add it via the chrome store Im still got the error.

How do you do that? Could you please provide a code snippet? I am not even sure such a scenario is supported.

**Comment by dimag32** [comment]
Hi,
let me to summarize the status,
the snippet  working and loaded succesfully .

only doubt I have is that its seems like actually the extension is still
with option add to chrome in chrome store  ,but it seems it working
properly now.

Thanks,
Dima
