### ISSUE TITLE
Documentation failure for playwright.dev Authentication section

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12085]
The section "Automate logging in" on https://playwright.dev/docs/auth shows a sample script:

```
const page = await context.newPage();
await page.goto('https://github.com/login');

// Interact with login form
await page.click('text=Login');
await page.fill('input[name="login"]', USERNAME);
await page.fill('input[name="password"]', PASSWORD);
await page.click('text=Submit');
// Verify app is logged in
```

But when run you get the `ReferenceError: USERNAME is not defined` error. Please fix the documentation; (it would be good to have a user feedback option at the bottom of these pages as I have a lot).

**Comment by unlikelyzero** [comment]
@alanbqs  that's allowing you to specify those variables as command line variables (pass at runtime) or as env variables

**Comment by alanbqs** [comment]
Thanks - but/so how do I pass in command line variables?

**Comment by unlikelyzero** [comment]
https://nodejs.dev/learn/how-to-read-environment-variables-from-nodejs

@alanbqs there are a few ways, but you should never include the actual inside of the code since they can be checked in accidentally.

**Comment by mxschmitt** [comment]
Closing since its answered.
