### ISSUE TITLE
[FEATURE] Cookies not supported with Electron

### ISSUE THREAD

**Issue by taniarascia** [microsoft/playwright#12096]
I'm using Playwright to run end-to-end tests for an Electron app. I have a use case for cookies, but it appears none of the cookies commands exist on the BrowserContext with Electron.

- [BrowserContext documentation](https://playwright.dev/docs/api/class-browsercontext)
- [electronApplication.context documentation](https://playwright.dev/docs/api/class-electronapplication#electron-application-context)

I assumed they would have the same API, but upon trying to get cookies:

```js
const context = await app.context()
await context.cookies()
```

I get this error:

```
browserContext.cookies: Protocol error (Storage.getCookies): Browser context management is not supported.
```

Is cookies not supported for Electron + Playwright, or is there a workaround?

**Comment by dgozman** [comment]
@taniarascia Indeed, some feature are not working with Electron, that's why it is still experimental 😄  I don't think there is an easy workaround today.

**Comment by ShanmukhaGajula** [comment]
upvote for electron support!

**Comment by EliveltonRepolho** [comment]
upvote for electron support!

**Comment by Stratoscop** [comment]
upvote for electron support!

**Comment by RADDEV** [comment]
upvote for electron support!

**Comment by apankov1** [comment]
Upvote

**Comment by jevasco** [comment]
upvote for electron support.
echoing above, is there a work around for setting cookies?

**Comment by jevasco** [comment]
👋 @dgozman , is there a doc that list these limitations for Playwright support to Electron app that we can use for evaluation purposes?

**Comment by dgozman** [comment]
@jevasco There is no such doc today, unfortunately. You can look at [tests that are skipped](https://cs.github.com/microsoft/playwright?q=isElectron) for Electron as a guess.

**Comment by jevasco** [comment]
Thanks @dgozman , is there a place i could look into to see progress on making Playwright fully support Electron app like new feature support implementation or roadmap?

**Comment by dgozman** [comment]
@jevasco There is no roadmap, sorry.

**Comment by lixingxing1231** [comment]
Upvote

**Comment by rjwaltz** [comment]
upvote for electron support!

**Comment by mxschmitt** [comment]
**Update:**

This is fixed after https://github.com/electron/electron/pull/41718 - which gets backported to v30, v29, v28. Note: Its **not** released yet. See here for the backports:

- https://github.com/electron/electron/pull/41738
- https://github.com/electron/electron/pull/41739
- https://github.com/electron/electron/pull/41740
