### ISSUE TITLE
[BUG] did something change on APIRequest/Response APIs ?

### ISSUE THREAD

**Issue by ltsuda** [microsoft/playwright#12090]
**Context:**
- Playwright Version: 1.19 is failing some tests, <=1.18 works
- Operating System: WSL2 Ubuntu 20.04 (Windows)
- Node.js version: v16.13.0
- Browser: None

**Describe the bug**
After updating https://github.com/ltsuda/playwright-serverest to **Playwright@Test 1.19**, some of the test cases are failing with error `SyntaxError: Unexpected end of JSON input` because the api response is empty, which shouldn't be.

I couldn't find the error as in `1.18` everything works and on `1.19` the response content is empty.

Please, see both branches below for `1.18` and `1.19`. There's a HTML from playwright's report, a `*.txt` with the pw:api calls during the tests.
[v118 branch](https://github.com/ltsuda/playwright-serverest/commit/f6733965d72686cd0974348bdd407de00974eebd) line 107 shows the response json
[v119 branch](https://github.com/ltsuda/playwright-serverest/commit/8d3bebcee342f4fd7ab494c1b208c351b80d3ddc) line 107 shows an empty response

If you guys want to run, just clone the repo + change to `v118` or `v119` branch, `npm install -D` and run `DEBUG=pw:api MATCH="@x" npm run test:match` to one of the failing tests.

**Comment by yury-s** [comment]
> After updating https://github.com/ltsuda/playwright-serverest to Playwright@Test 1.19, some of the test cases are failing with error SyntaxError: Unexpected end of JSON input because the api response is empty, which shouldn't be.

It's likely related to this change: https://github.com/microsoft/playwright/commit/401cd9c0ee8d9cc58c00157d9374df9e122e886a Successful PUT, HEAD and TRACE responses don't have body according to the spec, so we don't read the body anymore. In your tests the response status is  400 which is an error, in this case we should be reading the body, it's a bug. I'll prepare a fix.

**Comment by ltsuda** [comment]
Understood, thanks for the quick answer :) 

In this specific test with tag "@x" as seen in the link below, the response is 200 as I'm editing a product with all correct fields.

https://github.com/ltsuda/playwright-serverest/commit/8d3bebcee342f4fd7ab494c1b208c351b80d3ddc#diff-be7cee1d03aa9153eec3b151802fdd580fac02ca3ca955adecc683d9bba4cdc0R338

Here's the PUT request
https://github.com/ltsuda/playwright-serverest/commit/8d3bebcee342f4fd7ab494c1b208c351b80d3ddc#diff-17712cf03bf5f95c60e2cb710a28e3af5004415afd51f9ec5d450f95a3db1707R84

and the respective response
https://github.com/ltsuda/playwright-serverest/commit/8d3bebcee342f4fd7ab494c1b208c351b80d3ddc#diff-17712cf03bf5f95c60e2cb710a28e3af5004415afd51f9ec5d450f95a3db1707R91

Also, this is a repository for study purpose, so for me it's not an emergency.

Thanks again.

**Comment by yury-s** [comment]
For 'HEAD', 'PUT' and 'TRACE' requests we don't read response body as they don't have one according to the spec, so the response text is empty in this case even if the server returned something.

**Comment by ltsuda** [comment]
oooh, I understood now. My bad :P

Thanks again ❤️
