### ISSUE TITLE
[Feature] Provide an option to view the jsonData parameters and the return value within the console

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#12104]
Currently the jsonData parameters and the return value included in the trace files generated by PW api calls are difficult to read.  It would be nice we had some option to easily view this data (maybe even copy to the clipboard)

![2022-02-15_12-31-07](https://user-images.githubusercontent.com/50574915/153982800-5eac2171-194e-4eb6-8077-abcdd3b23551.png)

PW v1.18.1

**Comment by ryanrosello-og** [comment]
Optionally, this output can be done in the UI too but not sure if we have enough space for hence why I'm suggesting logging to the console (since some responses could get huge)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
