### ISSUE TITLE
route.fulfill triggering re-authentication for an already authenticated SharePoint Page.

### ISSUE THREAD

**Issue by jwalakom** [microsoft/playwright#12100]
### Discussed in https://github.com/microsoft/playwright/discussions/12098

<div type='discussions-op-text'>

<sup>Originally posted by **jwalakom** February 14, 2022</sup>
Hello,

We are using the `route.fulfill ` to Mock an API response in an authenticated SharePoint page, to test an application flow. However we noticed when we use `route.fulfill ` the browser is redirecting to an authentication page. This only happens in Chromium Edge in Windows PC but works fine in Chromium Edge in MacOS.

Looking forward to a response on this. Thanks!</div>

**Comment by dgozman** [comment]
@jwalakom We need more details to act on this. Could you please share a repro that we can run locally?

**Comment by jwalakom** [comment]
@dgozman Here is the code that we use to mock an HTTP 500 error. 

- ```
   public async mockApiResponse(url: string, response: string, statusCode: number = 200): Promise<void> {
    const headers = this.getCorsHeaders();
    await this.dashboard.Browser.route(url, (route) =>
      route.fulfill({
        status: statusCode,
        headers: headers,
        body: response,
      })
    );
  }

We pass the different `statusCode`'s to mock the corresponding application flows. Only when we mock these API's our page redirects to authentication. This is breaking the functional test case flow.

Please let me know if you need more details.

**Comment by dgozman** [comment]
@jwalakom Thank you for the snippet. Unfortunately, this does not help much, because we cannot run this code locally. We would need a page url, and some snippet that triggers the exact issue to start debugging.

Alternatively, if you could pin-point the issue on your end, for example `route.fulfill()` is missing a cookie compared to non-routed response, or something like that, we will be able to look into that particular problem.

**Comment by jwalakom** [comment]
@dgozman Thank you for your response! If possible, can I please connect with you on Microsoft Teams? I believe this would be much faster this way. But if you really prefer discussing the issue here, I will post a more detailed version.  Please let me know. Thanks!

**Comment by mxschmitt** [comment]
@jwalakom any chance for a repro which we can run locally? Otherwise we'd have to close it since we can't act on it.

We don't provide any private support over Microsoft teams.

**Comment by jwalakom** [comment]
@mxschmitt  I have updated the PlayWright to the latest version (which supports Tracing ) and I will share the Trace file soon! Thanks!

**Comment by mxschmitt** [comment]
Awesome, closing for now. If you still encounter any bugs or weird behaviour, feel free to create a new issue.
