### ISSUE TITLE
[Question] How can I use a proxy and codegen at the same time?

### ISSUE THREAD

**Issue by freesiafreesia** [microsoft/playwright#12108]
Hi,

I have a proxy with http authentication and I want to use codegen at the same time.
I assume that it will be the case that I have to use [codegen-with-custom-setup](https://playwright.dev/docs/cli#codegen-with-custom-setup) like below.

```
const { chromium } = require('playwright');
(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext(proxy={
  "server": "http://myproxy:8080",
  "username": "myname",
  "password": "mypass"
});
  await context.route('**/*', route => route.continue());

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.pause();
})();
```

If I were right, how can I run it?

**Comment by dgozman** [comment]
`npx playwright codegen --help` shows `--proxy-server` option. So, you can just run it like `npx playwright codegen --proxy-server="http://myproxy:8080"`, but that does not support username/password.

As for running the snippet above, save it as `codegen.js` and then run with `node codegen.js`. Does that work?

**Comment by freesiafreesia** [comment]
Thank you @dgozman.
I saved it as `codegen.js` and hit `node codegen.js`, but following error was shown.
```
C:\Users\user\Desktop\node-v16.13.2-win-x64>node codegen.js
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'playwright'
Require stack:
- C:\Users\user\Desktop\node-v16.13.2-win-x64\codegen.js
[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:778:27)[39m
[90m    at Module.require (node:internal/modules/cjs/loader:1005:19)[39m
[90m    at require (node:internal/modules/cjs/helpers:102:18)[39m
    at Object.<anonymous> (C:\Users\user\Desktop\node-v16.13.2-win-x64\codegen.js:1:22)
[90m    at Module._compile (node:internal/modules/cjs/loader:1101:14)[39m
[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)[39m
[90m    at Module.load (node:internal/modules/cjs/loader:981:32)[39m
[90m    at Function.Module._load (node:internal/modules/cjs/loader:822:12)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: [
    [32m'C:\\Users\\user\\Desktop\\node-v16.13.2-win-x64\\codegen.js'[39m
  ]
}
```

'MODULE_NOT_FOUND' ?
I checked global paths to make sure that I've installed playwright properly.
`C:\Users\user\Desktop\node-v16.13.2-win-x64>node`
`> global.module.paths`

it includes the path I installed playwright.
`  'C:\\Users\\user\\Desktop\\node-v16.13.2-win-x64\\node_modules',`

But I found that the error was right.
There is no `playwright` folder in the `node_modules` folder.
There is only `playwright-core` folder instead of `playwright` folder.

What I did to install Playwright was this.
```
npm i -D @playwright/test
npx playwright install
```

Anyway, I changed the first line of the code. 
```
const { chromium } = require('playwright-core');
(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext(proxy={
  "server": "http://myproxy:8080",
  "username": "myname",
  "password": "mypass"
});
  await context.route('**/*', route => route.continue());

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.pause();
})();
```

After I hit `node codege.js`, blank browser and Playwright Inspecter windows are shown!
This is a giant leap for me but the browser asks me to enter my proxy password after I enter an external url into the address bar.
My question is, shouldn't it be possible to show an external url without entering proxy password with the code above?

Also, I've tried this code. Adding `page.goto` just before `page.pause()`.
```
const { chromium } = require('playwright-core');
(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext(proxy={
  "server": "http://myproxy:8080",
  "username": "myname",
  "password": "mypass"
});
  await context.route('**/*', route => route.continue());

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.goto("https://playwright.dev/docs/codegen");
  await page.pause();
})();
```

The result is here.
```
C:\Users\user\Desktop\node-v16.13.2-win-x64>node codegen.js
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

page.goto: net::ERR_INVALID_AUTH_CREDENTIALS at https://playwright.dev/docs/codegen
=========================== logs ===========================
navigating to "https://playwright.dev/docs/codegen", waiting until "load"
============================================================
    at C:\Users\user\Desktop\node-v16.13.2-win-x64\codegen.js:17:14 {
  name: 'Error'
}
```

Am I wrong at somewhere?
Thank you for reading this to the end.

**Comment by dgozman** [comment]
@freesiafreesia Great analysis!

> There is no `playwright` folder in the node_modules folder.
> There is only `playwright-core` folder instead of playwright folder.

Right, since you installed `@playwright/test`, it should be `const { chromium } = require('@playwright/test');`. Seems like docs are not clear there.

> My question is, shouldn't it be possible to show an external url without entering proxy password with the code above?

Yes, it should be as long as the proxy you specify works. Note that your snippet seems like not valid javascript, it should probably be like this:

```js
// ....
const context = await browser.newContext({ proxy: {
  "server": "http://myproxy:8080",
  "username": "myname",
  "password": "mypass"
}});
```

Also, you don't really need this line:
```js
await context.route('**/*', route => route.continue());
```

If things still don't work, try opening browser developer tools and look at the network requests - something's not working with the proxy? Alternatively, [record a trace](https://playwright.dev/docs/api/class-tracing) and attach it here for us to take a look.

**Comment by freesiafreesia** [comment]
Since I'm new to Node.js and javascript, seems like I didn't know what I was doing.
I wrapped things up as code shown below, save it as `codegen.js`, then hit `node codegen.js`.

``` javascript
const { chromium } = require('@playwright/test');

(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({
    headless: false,
    proxy: {
      server: 'http://myproxy:8080',
      username: 'myname',
      password: 'mypass'
    }
  });

  // Setup context however you like.
  const context = await browser.newContext({ });

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.goto("https://playwright.dev/docs/codegen");
  await page.pause();
})();
```
It worked as I expected.
Thank you @dgozman !
