### ISSUE TITLE
[Question] don't see the `source` option in the trace viewer

### ISSUE THREAD

**Issue by ls-bruno-biesemans** [microsoft/playwright#12111]
I'm already using 1.18 with python but don't see the source option in the trace viewer
do we need to set extra parameters to have it?

**Comment by mxschmitt** [comment]
When starting a trace with `tracing.start(sources=True)` you need to specify `sources=True` see here: https://playwright.dev/python/docs/api/class-tracing#tracing-start

**Comment by ls-bruno-biesemans** [comment]
👍 thanks, maybe also add this to the following page https://playwright.dev/python/docs/trace-viewer
