### ISSUE TITLE
[Question] Is there is any built in feature to send test results by email

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#12112]
Hi, I can see many of the built-in features that are being supported by the playwright that doesn't exist in other tools. Which is impressive and hence I wanted to check if there is any feature to send test results by email. just like below.
![image](https://user-images.githubusercontent.com/21192877/154057523-81acf90f-dbd7-41d4-aae2-51179a5c4a31.png)

**Comment by dgozman** [comment]
@ShanmukhaGajula There's nothing built-in, but you can send [html report](https://playwright.dev/docs/test-reporters#html-reporter) if you'd like.
