### ISSUE TITLE
How to handle asynchronous event in playewright test cases[Question]

### ISSUE THREAD

**Issue by RajaTheKing826** [microsoft/playwright#12118]
In my use case, after clicking on a button an API call will hit the server, after resolving that API call I have to click on some text which is coming from the first API response. So when I tried to click on the response I am getting an error that is text not found, because the API is still is in a progressive state. So here I have to do the page. click-action after resolving the first promise only. How can I do it?

setTimeout or waitForTimout or hacks won't work all the time.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
