### ISSUE TITLE
[Question] Questions about page.locator('  ', {hasText()}) feature?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#12110]
Hi, I'm trying to improve my tests using new locator's features, but I don't understand an issue I'm having:

I want to click an Ok button (which is visible and clickable):

`    await page.locator('div.modal.fade.in div.modal-dialog div.modal-footer button span', { hasText: 'Ok' }).click();
`

but when I debug it I obtain this error:

```   35 |     await page.pause();
      36 |     //TO FIX
    >37 |     await page.locator('div.modal.fade.in div.modal-dialog div.modal-footer button span', { hasText: 'Ok' }).click();
           |                                                                                                              ^
      38 | });
      39 |
      40 |```

```waiting for selector "div.modal.fade.in div.modal-dialog div.modal-footer button span >> :scope:has-text("Ok")"
Unexpected token "" while parsing selector ""
Error: Unexpected token "" while parsing selector ""
    at a (<anonymous>:3:3196)
    at v (<anonymous>:3:5131)
    at <anonymous>:3:4150
    at w (<anonymous>:3:4314)
    at y (<anonymous>:3:3815)
    at t.parseCSS (<anonymous>:3:5246)
    at <anonymous>:3:21085
    at Array.map (<anonymous>)
    at s (<anonymous>:3:20956)
    at S.parseSelector (<anonymous>:3:55061)

 =========================== logs ===========================
    waiting for selector "div.modal.fade.in div.modal-dialog div.modal-footer button span >> :scope:has-text("Ok")"
      Unexpected token "" while parsing selector ""
    ============================================================
```

what's the problem here? Am I missing something?

I don't think is a problem of the new feature because I obtain the same error also in the "old" way

**Comment by dgozman** [comment]
@DvDream Interesting! Could you share a page url so that we can debug locally?

**Comment by mxschmitt** [comment]
@DvDream any chance that you could share the URL with us? Probably they modify some standard APIs which we use and it would be great to fix that.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
