### ISSUE TITLE
[Question] page.isVisible: Target closed

### ISSUE THREAD

**Issue by holyaleks** [microsoft/playwright#12117]
Hi, I am faced with a problem, I have the next code:
![image](https://user-images.githubusercontent.com/44750553/154091713-6d30c49b-3888-4a5f-8eed-0983f02454fd.png)

and this code is failed on the ' let isVisible = await this.page.isVisible(this.selector);' line of code with the error - page.isVisible: Target closed
=========================== logs ===========================
  checking visibility of "input[name="email"]";
![image](https://user-images.githubusercontent.com/44750553/154091897-4ae9bfc7-2c01-4f29-b16c-b9dc67a5a80e.png)

the HTML DOM is 
![image](https://user-images.githubusercontent.com/44750553/154092125-d16bc769-b04c-4216-baf9-e4230a122681.png)

what can be wrong in that case?

**Comment by dgozman** [comment]
@holyaleks Most likely, your test times out and test runner closes the page in the browser. What test error do you get?

**Comment by holyaleks** [comment]
@dgozman Thanks for replying. I thought the root cause of this issue in the <form> tag. Because I tried to do the same with another element outside this tag and I hit the brick wall. The bottom line is that the issue occurs only when I try to do action with element in this html tag. There is exception is thrown upon the invoke page.isVisible() method.

**Comment by dgozman** [comment]
@holyaleks `Target closed` error is independent from the DOM markup you are working with. I would look elsewhere. If you could share the test with us, we might be able to help.

**Comment by holyaleks** [comment]
@dgozman ok, I got it. There is a part of my code:
test:
```js
const { TestLogs } = require("../../tools/test-logs/test-logs-tools");
const { test, expect } = require('@playwright/test');
const { PagesList } = require("../../pages/pagesList");
const email = 'rrrr';
const password = 'rrrr';
const title = 'Iniciar sesión';

test('Log In', async ({ page }) => {
    TestLogs.logSteps("Open login page");
    const pagesList = new PagesList(page);
    await pagesList.openLoginPage();

    TestLogs.logSteps("Check title");
    let titleText = await pagesList.LoginPage.Title.getInnerText();
    expect(titleText).toBe(title);

    TestLogs.logSteps("Fill login form");
    pagesList.LoginPage.Actions.fillLoginForm(email, password);
});
```
fillLoginForm(email, password) method:
```js
const { LoginPage } = require("../loginPage");

exports.LoginPageActions = class LoginPageActions {
    constructor(pageElements = LoginPage) {
        this.pageElements = pageElements;
    }

    async fillLoginForm(email, password) {
        if (email !== undefined || email !== null) {
            await this.pageElements.Email.inputValue(email);
        }
        else if (password !== undefined || password !== null) {
            await this.pageElements.Password.inputValue(password);
        }

        await this.pageElements.LogIn.clickOnElement();
    }
}
```
inputValue(email) method:
```js
const { TestLogs } = require("../tools/test-logs/test-logs-tools");
const { Control } = require("./control");

exports.ControlInput = class ControlInput extends Control {
    constructor(selector, elementName, page) {
        super(selector, elementName, page);
    }

    async inputValue(value) {
        try {
            if (await this.isElementVisible()) {
                TestLogs.logTrace(`Try to input ${value} value in ${this.elementName}`);
                await this.page.fill(this.selector, value);
            }
        }
        catch (e) {
            TestLogs.logError(e.message)
            throw e.message;
        }
    }
}
```
isElementVisible() method:
```js
const { TestLogs } = require('../tools/test-logs/test-logs-tools');

exports.Control = class Control {
    /**
     * @param {import('@playwright/test').Page} page
     */
    constructor(selector, elementName, page) {
        this.page = page;
        this.selector = selector;
        this.elementName = elementName;
    }

    async isElementVisible() {
        try {
            TestLogs.logTrace(`Check if the ${this.elementName} is visible`);
            let isVisible = await this.page.isVisible(this.selector);
            TestLogs.logTrace(`The ${this.elementName} is visible: '${isVisible}'`);
            return isVisible;
        }
        catch (e) {
            TestLogs.logError(e.message);
            throw e.message;
        }
    }

    async clickOnElement() {
        try {....
```

There is a debugging process: 
![image](https://user-images.githubusercontent.com/44750553/154214313-d629e609-0e74-4ed0-a945-8a30f119430c.png)

![image](https://user-images.githubusercontent.com/44750553/154214370-b2a44b00-bf00-473a-9453-e46ce9a38c1e.png)

![image](https://user-images.githubusercontent.com/44750553/154214438-f6b7a4ed-e12a-4194-a34b-1f3e2abf06bd.png)

![image](https://user-images.githubusercontent.com/44750553/154214499-d9b6f1ad-4c1b-4f66-8dc7-ff71d6cf62d2.png)

![image](https://user-images.githubusercontent.com/44750553/154215164-5410d501-7b83-49d1-9a11-96e769219f3e.png)

The test is failed with the error taken from the HTML reporter:

![image](https://user-images.githubusercontent.com/44750553/154215347-6b69a7e7-d96c-43d2-af01-69a7d140a9bb.png)

![image](https://user-images.githubusercontent.com/44750553/154215396-a4fd3bff-fc0c-4667-8735-a6e0883b954e.png)

`[STP] 2/16/2022, 9:17:32 AM --------------------------- Open login page
[STP] 2/16/2022, 9:17:32 AM --------------------------- Check title
[STP] 2/16/2022, 9:17:32 AM --------------------------- Fill login form
[LOG] 2/16/2022, 9:17:32 AM --------------------------- Check if the Email is visible
[ERR] 2/16/2022, 9:17:32 AM --------------------------- page.isVisible: Target closed
=========================== logs ===========================
  checking visibility of "input[name="userNameOrEmailAddress"]"
============================================================
[ERR] 2/16/2022, 9:17:32 AM --------------------------- undefined`

**Comment by holyaleks** [comment]
@dgozman god, seems I found the issue. I should have invoked this part of code with await:
```js
TestLogs.logSteps("Fill login form");
await pagesList.LoginPage.Actions.fillLoginForm(email, password);
```
:)

**Comment by mxschmitt** [comment]
Yup, this is commonly the reason for such errors.
