### ISSUE TITLE
[Question] testInfo.describe.title?

### ISSUE THREAD

**Issue by fredboyle** [microsoft/playwright#12128]
How can we retrieve the full title path name of a test?
By path name I mean the complete hierarchy of titles from the test to the top level describe.

In the example below it would be nice to be able to have `testInfo.hierarchicalTitle` to retrieve "Buttons » Primary".

Example: 
```js
test.describe('Buttons', () => {
  test('Primary', ({page}) => { ... });
});
```

**Comment by dgozman** [comment]
Use [`testInfo.titlePath`](https://playwright.dev/docs/api/class-testinfo#test-info-title-path) for this.

**Comment by fredboyle** [comment]
@dgozman Thanks for the info, I was aware of this. However `testInfo.titlePath` is an object, which includes the filename, and doesn't directly output something pretty. Was hoping for something that did require manipulation for legible display.

Any plans for something requiring less manipulation for display of something as I described in my original post? 

Or perhaps we can use the same function that the test runner uses to output things to the console with the ability to omit the filename & path?

**Comment by dgozman** [comment]
We prefer to expose the data, and let you format the title to your liking. Here is a snippet that drops the file name and joins  parts nicely:

```js
testInfo.titlePath.slice(1).join(' › ')
```
