### ISSUE TITLE
[Question] UserAgent / Proxy with APIRequestContext.fetch

### ISSUE THREAD

**Issue by NetLuiz** [microsoft/playwright#12122]
Hello,

How can I use UserAgent/Proxy with page.request.fetch() function?

I'm using http-proxy-agent module with node-fetch. But I couldn't figure out how to use it with APIRequestContext request. I tried to add User-Agent header but it gave error because it expects a string, http-proxy-agent gives object.

**Comment by dgozman** [comment]
`page.request.fetch()` uses the same User-Agent and Proxy as the `page` itself. If you want different settings when you make a request, look into [`request` fixture](https://playwright.dev/docs/api/class-fixtures#fixtures-request) or [`playwright.request.newContext()`](https://playwright.dev/docs/api/class-apirequest#api-request-new-context) instead. There is also a useful guide for [API testing](https://playwright.dev/docs/test-api-testing#using-request-context) covering this.

**Comment by NetLuiz** [comment]
Thank you very much for quick reply. I want to use different settings so I will use newContext(). Thanks!
