### ISSUE TITLE
[BUG] Screenshots on failure not working in Electron

### ISSUE THREAD

**Issue by UndefinedOffset** [microsoft/playwright#12125]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Windows 10 (21H1)
- Node.js version: 14.18.3
- Browser: Electron 17.0.0

**playwright.config.js**
```javascript
// @ts-check

/** @type {import('@playwright/test').PlaywrightTestConfig} */

const config = {
    outputDir: './test-results',
    use: {
        screenshot: 'only-on-failure',
    },
};

module.exports = config;
```

**Describe the bug**

When playwright is configured either with screenshots set to `on` or `only-on-failure` nothing seems to happen. There are no screenshots placed in the `test-results` folder as I would expect on failure for example. However they do seem to be taken if I deliberately call `await window.screenshot({ path: 'screenshot.png' });` for example.

Sample test:
```javascript
const { _electron: electron } = require('playwright');
const { test, expect } = require('@playwright/test');

test('Sample test', async () => {
    const electronApp = await electron.launch({ args: ['.'] });

    // Wait for the window
    const window = await electronApp.firstWindow();


    expect(await window.content()).toContain('something not contained in the window');


    // Close App
    await electronApp.close();
});
```

**Comment by dgozman** [comment]
@UndefinedOffset Indeed, integration of some testing features with electron is missing.

**Comment by CodeStrikerr** [comment]
Even I am planning to use playwright for electron application. It would be great if support can be extended for the same

**Comment by ShanmukhaGajula** [comment]
upvote!

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright/issues/8208
