### ISSUE TITLE
[BUG] Electron not running in GitHub actions CI for ubuntu-latest (electron.launch: Process failed to launch!)

### ISSUE THREAD

**Issue by taniarascia** [microsoft/playwright#12139]
Electron is failing to launch in GitHub action for `ubuntu-latest`.

## Binaries:
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
## npmPackages:
 - playwright: ^1.18.1 => 1.18.1

I passed `DEBUG: pw:browser*` and got:

```
2022-02-15T23:41:17.849Z pw:browser [pid=12798] <process did exit: exitCode=null, signal=SIGILL>
```

I tried running `xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npm run test:e2e` or just `npm run test:e2e` which maps to `npx playwright test`. 

Everything working fine in macOS locally. I put `headless: true` in Playwright config. What is missing?

**Comment by dgozman** [comment]
@taniarascia If Electron app fails to launch, I am not sure how Playwright can help there. Just in case, we can take a look if you provide a full repro (test script + config if any + the electron app + package.json + GHA workflow if possible).

**Comment by taniarascia** [comment]
Electron only fails to launch in the `ubuntu-latest` environment on a GitHub action. There is another issue for this but it doesn't seem to have a resolution: https://github.com/microsoft/playwright/issues/11932

It is the Playwright electron that is failing to launch in this environment.

```js
const {_electron: electron} = require('playwright')

exports.startApplication = async () => {
  // Launch Electron app
  return await electron.launch({
    args: ['./main.js'],
    env: {
      IS_TEST_ENV: true,
    },
  })
}
```

The entire flow plus running the tests works locally in macOS, and every step in the pipeline for building Electron works just fine in the Ubuntu pipeline as well. Only upon running the Playwright tests in this environment does it fail, with no additional debugging information.

**Comment by dgozman** [comment]
Perhaps, similarly to #11932, you need `xvfb-run` because Electron is a GUI application and requires a display?

```js
# replace "npx playwright test" with your test command
xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- npx playwright test
```

Without any logs with `DEBUG=pw:browser*`, we have no insights into what's happening with that Electron process. If it were to output some error or stack trace, that would be something, but otherwise I am not sure how to help.

**Comment by taniarascia** [comment]
I mentioned in the original message that I've tried running both the original test command and the `xvfb-run` command, and both of them result in the same `electron.launch: Process failed to launch!` command.

I have changed the github action to `runs-on: macos-latest` to isolate the issue, and have confirmed the `failed to launch` message no longer appears, and the tests run, confirming that the issue is not in the code itself or a problem with Electron, but the `ubuntu-latest` seeming to have some sort of issue with Electron + Playwright.

**Comment by dgozman** [comment]
> I mentioned in the original message that I've tried running both the original test command and the `xvfb-run` command

Sorry, missed that!

> not in the code itself or a problem with Electron, but the `ubuntu-latest` seeming to have some sort of issue with Electron + Playwright

Note that Electron itself has very different binaries on different operating systems, so you are not actually running the same program on macos vs ubuntu.

I am still not sure how to help here. We run our tests with Electron on `ubuntu-20.04`, [here is the action](https://github.com/microsoft/playwright/blob/7ee35ae30dd4bf0480ee27b422ba13c838a38aa1/.github/workflows/tests_secondary.yml#L692) that works. We are using [Electron 12.2.1](https://github.com/microsoft/playwright/blob/7ee35ae30dd4bf0480ee27b422ba13c838a38aa1/package.json#L81). Perhaps you could compare it with your own config?

**Comment by taniarascia** [comment]
Thanks for the follow up. I tried with `ubuntu-20.04` and `electron 12.2.1` just to ensure all the config is the same, but still end up with the failed to launch error 😞 I'll move forward with using the `macos-latest` image. Not sure if you want to close this issue or leave it open.

**Comment by dgozman** [comment]
I'll close since we cannot follow up. If you ever get more logs/insights into the problem, please open a new issue and we'll gladly help!

**Comment by tanishqkancharla** [comment]
I was running into this same issue, and it seems the most likely issue is the electron process failing on startup immediately. If you're piping your logs somewhere else (which is common for electron apps), you might not see the logs that lead to the failure. 

For me specifically, the autoupdater was failing; it seems the autoupdater can't work on unsigned Electron builds. So I had to disable the autoupdater on CI.

**Comment by Atomic-Germ** [comment]
This issue still occurs on ubuntu-latest

**Comment by Aetherinox** [comment]
Currently stuck on this issue as well. No solutions anywhere.
