### ISSUE TITLE
[BUG] Specific websites breaks exposeBinding

### ISSUE THREAD

**Issue by Banou26** [microsoft/playwright#12134]
**Context:**
- Playwright Version: ^1.18.0
- Operating System: Windows
- Node.js version: 17.1.0
- Browser: Chromium

**Code Snippet**

```javascript
import * as playwright from 'playwright'

const browser = await playwright.chromium.launch({ headless: false, devtools: true })
console.log('browser')
const page = await browser.newPage()
console.log('page')
await page.goto('https://link.springer.com/chapter/10.1007/978-3-642-69767-8_51')
console.log('pageloaded')
await page.exposeBinding('foobarbaz', async () => {}) // never resolves
console.log('exposedBinding') // never logs as promise hangs
await browser.close()
```

**Describe the bug**

When trying to call `exposeBinding` on specific websites(e.g https://link.springer.com/chapter/10.1007/978-3-642-69767-8_51), the promise never returns

This end up making our test throw:
```
    Timeout of 90000ms exceeded.

    Pending operations:
      - page.exposeBinding at ../test.js:73:16
```

This isn't a unique case, we have a few websites on our testing list on which it happens

**Comment by dgozman** [comment]
@Banou26 I can repro this, but only in headed mode.

`page.exposeBinding` could timeout if one of the frames on the page is busy and not responding, which is the case here. I'd suggest to swap the calls instead, to make it reliably work:

```js
await page.exposeBinding('foobarbaz', async () => {})
await page.goto('https://link.springer.com/chapter/10.1007/978-3-642-69767-8_51')
```

**Comment by Banou26** [comment]
@dgozman I have another page on which `page.goto` hangs when navigating to it, so your workaround doesn't work in this case.
The page is https://scoutsmarts.com/personal-fitness-merit-badge-exercise-program-req-7-8/
This should be an issue that should be fixed instead of worked around.

**Comment by dgozman** [comment]
The following snippet works for me, both in headed and headless. Could you please provide the snippet that does not work?

```js
await page.exposeBinding('foobarbaz', async () => {})
await page.goto('https://scoutsmarts.com/personal-fitness-merit-badge-exercise-program-req-7-8/')
```
