### ISSUE TITLE
[BUG] `TestInfo.attach` does not create a file with the line reporter when passing a Buffer.

### ISSUE THREAD

**Issue by mskelton** [microsoft/playwright#12130]
**Context:**
- Playwright Version: 1.19
- Operating System: macOS
- Node.js version: 16
- Browser: Chromium

**Reproduction repo**

https://github.com/mskelton/pw-attach-buffer

**Code Snippet**

```javascript
test("should allow me to add todo items", async ({}, testInfo) => {
  await testInfo.attach("report.json", {
    body: Buffer.from('{"test": "test"}', "utf-8"),
    contentType: "application/json",
  });

  expect(true).toBe(false);
});
```

**Describe the bug**

The default line reporter does not write test attachments created using `TestInfo.attach` to the results folder.

<img width="908" alt="Screen Shot 2022-02-15 at 2 39 32 PM" src="https://user-images.githubusercontent.com/25914066/154145663-5c2210b0-a0c9-4f55-84db-4d3e765912f9.png">

As you can see, it displays there is an attachment, but it does not display a file path, nor is the file written to disk.

**Comment by dgozman** [comment]
@mskelton That's right, buffer attachments are kept as is, available for the reporters to consume in some way. For example, terminal reporters just mention that there is an attachment (without printing the contents), while html reporter bundles them in the report.

There was no intention to create a file on disk for such attachments. Do you have a particular scenario in mind? How would you like to consume the attachment?

**Comment by mskelton** [comment]
I guess more of a misunderstanding perhaps then on my part, so not an issue in that case.

> Do you have a particular scenario in mind? How would you like to consume the attachment?

My use case is I've been updating expect-axe-playwright which provides an expect matcher for accessibility testing.  When it fails, I generate a detailed report which I then want to save as an attachment.  Since I have the file in memory, I thought that providing a Buffer would write the file to disk, but saw it didn't.  It's not a huge deal to write it to disk, let it get copied, and then delete it.

That said, I'm kind of breaking the rules anyway since I'm directly pushing to `TestInfo.attachments` since I don't like the fact that the copied files have a hashed filename making them really hard to know which is which.  I opened https://github.com/microsoft/playwright/discussions/12129 to discuss that behavior.
