### ISSUE TITLE
[Question] Unable to find PLAYWRIGHT_BROWSERS_PATH in .npmrc

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12136]
I have set this `PLAYWRIGHT_BROWSERS_PATH=https://../repository/google-storage-chromium-browser` in my `.npmrc` file but still getting error `cannot download chromium`. I checked Jenkins logs and path is getting set correctly. For some reasons, playwright is not picking up the path. Can someone please help?

**Comment by dgozman** [comment]
`PLAYWRIGHT_BROWSERS_PATH` is a local path where the browser is available (or should be downloaded to). Do you actually need `PLAYWRIGHT_DOWNLOAD_HOST` or `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD ` instead? Take a look at [this guide](https://playwright.dev/docs/browsers).

**Comment by gauravgandhi1315** [comment]
I need to give path in my company registry to download browser from. So should I use `PLAYWRIGHT_DOWNLOAD_HOST` instead?

**Comment by dgozman** [comment]
Yes, `PLAYWRIGHT_DOWNLOAD_HOST ` is where the browser will be downloaded from.

**Comment by gauravgandhi1315** [comment]
@dgozman I am still seeing the same error with `PLAYWRIGHT_DOWNLOAD_HOST`

**Comment by dgozman** [comment]
@gauravgandhi1315 Please provide as much details as possible. At the minimum, copy the full error here. The more details you give, the more likely we'll be able to help.

**Comment by gauravgandhi1315** [comment]
@dgozman it is happening with npm version 6.14.15 only. It’s unable to download from given path.

**Comment by gauravgandhi1315** [comment]
Version 8 works fine
