### ISSUE TITLE
[Feature] Locator support `text` parameter.

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#12149]
The `locator("button", { hasText: "Click me" })` API is great, but we would sometimes want to do exact text matching.

Something like:
`locator("button", { text: "Click me" })`

It should be trivial to implement this, and the `hasText` API could just call this one behind the scenes (converting strings to Regex to get the `has` behaviour.

This is currently possible using the `':text("Click me")'` selector, but that API is clumsy and not type-safe.

**Comment by dgozman** [comment]
I think you can do this today with `someLocator.locator('text=Click me')` that will resolve to the element with "Click me" text inside `someLocator`.

**Comment by Meemaw** [comment]
Still, I think the object oriented API is preferred, and its harder to do the mistakes with. As soon as I also want to add the element selector, e.g. `button`, I need to start thinking about quotes, e.g..>

```js
someLocator.locator('button:(text="Click me"')
```

Its easier to do mistakes with this API imo.

**Comment by mxschmitt** [comment]
Two ways of achieving it as of today as written above:
1) via regex: `page.locator('h1', { hasText: /^Exact match$/ })`
2) via the text selector engine: `someLocator.locator('text=Click me')`

See here: https://playwright.dev/docs/selectors#text-selector

Would that work for you?

**Comment by mxschmitt** [comment]
Closing for now, please file a new issue if you still have questions.
