### ISSUE TITLE
Why does `TestInfo.attach` hash the filename?

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#12145]
### Discussed in https://github.com/microsoft/playwright/discussions/12129

<div type='discussions-op-text'>

<sup>Originally posted by **mskelton** February 15, 2022</sup>
When passing a file to [`TestInfo.attach`](https://playwright.dev/docs/api/class-testinfo#test-info-attach), it will copy it to `test-results/attachments` and hash the filename.  The hashed filename is not a great user experience as it looses context of where it came from or what it is.  Could it instead use the provided filename with a postfix?  For example:

```
my-report.json
```

becomes

```
my-report-3eba252.json
```

Or even a full hash.</div>

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
