### ISSUE TITLE
[Feature] Hide TestInfo. attach console logging

### ISSUE THREAD

**Issue by serembon** [microsoft/playwright#12154]
When using a `TestInfo. attachments `  in a reporter, such as `allure-playwright` or `html`, after the tests are finished, attachments logs appear in the console. Such information is not very useful for the end-user.

```bash
  Running 5 tests using 5 workers
  
    1) tests/incomingPackage.test.ts:4:1 › Package monitoring ===

    Some test results data....

    attachment #1: allure-metadata.json (application/vnd.allure.metadata+json) ---------------------
    ------------------------------------------------------------------------------------------------

    attachment #2: allure-metadata.json (application/vnd.allure.metadata+json) ---------------------
    ------------------------------------------------------------------------------------------------

    attachment #3: screenshot (image/png) ----------------------------------------------------------
    allure-results/tests-monitoring-incomingPackage-Package-Monitoring/test-failed-1.png
    ------------------------------------------------------------------------------------------------
```

Propose to remove the output of information about attachments to the console.

**Comment by dgozman** [comment]
@serembon Why is `allure-metadata.json` an attachment and not an annotation? Would that work for you?

**Comment by serembon** [comment]
This type of content was suggested by Allur's maintainers during the [merge request #408](https://github.com/allure-framework/allure-js/pull/408)

Can you provide an example of how this can be implemented through an annotation?

**Comment by dgozman** [comment]
@pavelfeldman Perhaps we can hide attachments that do not have a file path nor the text content?
