### ISSUE TITLE
is there a way to use process.env.PROJECT so, i wanted to skip some test cases based on project name passed in cmd line

### ISSUE THREAD

**Issue by lakibm77** [microsoft/playwright#12156]
is there a way to use process.env.PROJECT so, i wanted to skip some test cases based on project name passed in cmd line

**Comment by dgozman** [comment]
There is not `process.env.PROJECT`, but you can use [`TestInfo`](https://playwright.dev/docs/api/class-testinfo) to get a lot of information about the current test.
Let me know if the following snippet does not work for you.

```js
test('example', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name === 'some project');
  // ...
});
```

**Comment by lakibm77** [comment]
its working, amazing!!,, thank you so much
