### ISSUE TITLE
[Question] Error: Failed to download ffmpeg v1007

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12159]
Im running playwright scripts with version 1.19.0. Chromium was download by using `playwright_chromium_download_host` successfully but getting this error `Error: Failed to download ffmpeg v1007`. Anyone know about this error?

**Comment by youyuxun** [comment]
> Im running playwright scripts with version 1.19.0. Chromium was download by using `playwright_chromium_download_host` successfully but getting this error `Error: Failed to download ffmpeg v1007`. Anyone know about this error?
Hi，i have the same problem, can you solve it?
