### ISSUE TITLE
[BUG] Viewport reset when I click on element. Part 2.

### ISSUE THREAD

**Issue by andreirogal** [microsoft/playwright#12151]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux darkflame 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Node.js version: 16.13.0
- Browser: Chromium

## System:
 - OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 911.43 MB / 14.98 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Describe the bug**
This bug is similar to https://github.com/microsoft/playwright/issues/10579 But a different device is being used.
```
import {devices, PlaywrightTestConfig} from '@playwright/test';

const config: PlaywrightTestConfig = {
    use: {
        ...devices['Galaxy S8']
    }
};
export default config;
```
See more https://github.com/andreirogal/playwright-viewport-bug/tree/bug-viewport-2

OK
![image](https://user-images.githubusercontent.com/42994950/154252625-cbdef9ae-ca3b-4219-ad88-310ef535525d.png)

FAIL
![image](https://user-images.githubusercontent.com/42994950/154252681-c48563a8-d1fe-4af5-927b-b5f5662fb075.png)

**Comment by 2gury** [comment]
is it possible to fix it somehow?

**Comment by dgozman** [comment]
I can repro with a simpler script. Depending on the timeout in the middle, it either prints "360, 360" or "360, 1030".

```js
    await page.goto('https://www.banki.ru/products/hypothec/catalogue/ipoteka_mnogodetnyim_semyam/');
    console.log(await page.evaluate(() => window.innerWidth));
    await page.waitForTimeout(5000);
    await page.goto('https://www.banki.ru/products/hypothec/catalogue/refinansirovanie_ipoteki/city/moskva/');
    console.log(await page.evaluate(() => window.innerWidth));
```

**Comment by andreirogal** [comment]
@mxschmitt Please tell me when it is planned to fix this bug? Thanks!

**Comment by andreirogal** [comment]
Retest on version 1.20.0 The result is the same. This bug is reproducible.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
