### ISSUE TITLE
[BUG] Blinking browser (Mobile, WebKit)

### ISSUE THREAD

**Issue by andreirogal** [microsoft/playwright#12153]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux darkflame 5.13.0-28-generic #31~20.04.1-Ubuntu SMP Wed Jan 19 14:08:10 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
- Node.js version: 16.13.0
- Browser: WebKit

## System:
 - OS: Linux 5.13 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 911.43 MB / 14.98 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Describe the bug**
See more https://github.com/andreirogal/playwright-viewport-bug/tree/bug-blinking-browser

See video

https://user-images.githubusercontent.com/42994950/154259503-7f137501-2ebb-46aa-9e65-2ba36556eb4d.mp4

**Comment by yury-s** [comment]
> See more https://github.com/andreirogal/playwright-viewport-bug/tree/bug-blinking-browser

I cannot reproduce it on my linux box. Are you running it with a different playwright.config?

**Comment by yury-s** [comment]
This is the video that I get: 
[video.zip](https://github.com/microsoft/playwright/files/8165573/video.zip)

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue once you can repro!
