### ISSUE TITLE
[BUG] Error on attempt to unzip artifact with results that contain long test name

### ISSUE THREAD

**Issue by Xotabu4** [microsoft/playwright#12160]
![image](https://user-images.githubusercontent.com/3033972/154291569-5ea97cd2-ace8-47e7-b925-01a2dc492118.png)

**Context:**
- Playwright Version: 1.19
- Operating System: Report generated on linux, unzipped on Windows 10 (file system NTFS)
- Node.js version: 16
- Browser: chromium

**Describe the bug**
NTFS allows each path component (directory or filename) to be 255 characters long.
This is not playwright itself bug. But probably having some kind of hard limit for file/folder name in this case might prevent error.

**Comment by dgozman** [comment]
@Xotabu4 Hmm... We trim file names down to [100 characters](https://github.com/microsoft/playwright/blob/51344c69244f61425722188391dc0c43e887b163/packages/playwright-test/src/testInfo.ts#L120). Do you have a repro by any chance? Mind sharing your folders/files structure and describes/tests structure?

**Comment by Xotabu4** [comment]
@dgozman sure

my longest folder name:
`functional-regression-AccountSettings-BAA-growthHack-baaMarketingInfoFreeAccount-BAA-Marketing-Info-for-Free-Account-BAA---Mark-706d8--is-Disabled-Free-account-C22597-regression-retry1`

it contains one screenshot:
`test-failed-1.png`
[dev_regression-regression_adeptus.zip](https://github.com/microsoft/playwright/files/8095383/dev_regression-regression_adeptus.zip)
