### ISSUE TITLE
Windows Screen scaling appears to be ignored for browser windows

### ISSUE THREAD

**Issue by SteveALee** [microsoft/playwright#12178]
In Windows I have a UHD monitor with 200% scaling set. The provided Firefox Browser is very small so I expect it is ignoring the scaling

![image](https://user-images.githubusercontent.com/618922/154473164-f7f558c1-1b0a-4612-9e97-1426c9be7d04.png)

Not a deal breaker, and in some cases is quite useful if only want a thumbnail view of what is happening  :)

**Comment by nathanECP** [comment]
To answer this, create a `.wslgconfig` file in your root Windows user directory ie `/Users/user/.wslgconfig`:

```env
[system-distro-env]
WESTON_RDP_DISABLE_FRACTIONAL_HI_DPI_SCALING=false
WESTON_RDP_FRACTIONAL_HI_DPI_SCALING=true
```

And then restart WSL with `wsl --shutdown`, and then `wsl`
