### ISSUE TITLE
How avoid the next error "SyntaxError: Invalid or unexpected token"

### ISSUE THREAD

**Issue by Sapendo** [microsoft/playwright#12183]
Hi. This problem is very difficult to reproduce in the playground, so I try to describe it in words. When I run the test I receive the error
![image](https://user-images.githubusercontent.com/24610132/154483582-b808a851-bf0c-4137-9333-420ccab9f71f.png)

If I add the empty line in the test for example
![image](https://user-images.githubusercontent.com/24610132/154484322-15b41693-9ff2-4e47-af74-c461a7880072.png)
Everything works fine.

Do you have any ideas about what I do wrong?

**Comment by YMykhalko** [comment]
I've faced the same issue as well

**Comment by dgozman** [comment]
@Sapendo Do you write TypeScript or JavaScript? It could an issue with TypeScript handling. If you could share just this file, that would be great!

**Comment by Sapendo** [comment]
I write TypeScript. Unfortunately, I cannot share this file. What kind of information do you need?

**Comment by dgozman** [comment]
@Sapendo I have no idea what triggers this - it's a strange issue that we've not seen before. Clearly, the issue is triggered by the specific source you have, because event empty lines matter. So if you could give us the source, we can try debugging the issue locally. Otherwise, I am not sure how to help, unfortunately.

**Comment by mxschmitt** [comment]
@Sapendo @YMykhalko which version of Playwright are you using? Could you try 1.19.1?

Also does it happen when creating a new project with `npm init playwright new-project`?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
