### ISSUE TITLE
[BUG] PlaywrightTestConfig leads to errors when tsconfig > exactOptionalPropertyTypes is used

### ISSUE THREAD

**Issue by ayroblu** [microsoft/playwright#12181]
**Describe the bug**

Super basic type error so didn't fill in the template, but can do so if it helps, should be self explanatory, I got it downloading everything today. You either need to make the workers type: `workers?: number | undefined` or use something special in your generated `playwright.config.ts`

<img width="737" alt="image" src="https://user-images.githubusercontent.com/4915682/154162793-04f5833e-e1ba-46b1-9750-84e8e646c02a.png">

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by BorisZubchenko** [comment]
Fast fix:
```ts
export default defineConfig({
    ...(process.env.CI ? { workers: 1 } : {}),
})
```
