### ISSUE TITLE
[Question] Call app.quit() in Electron but process sticks around

### ISSUE THREAD

**Issue by luke-webdev** [microsoft/playwright#12189]
We are testing our Electron app's exit functionality.

It seems when we call `app.quit` in Electron, the UI closes, but the electron processes sticks around.

We are wondering if we need to handle the Electron close event on the Playwright side and close the application explicitly as well.

Edit: Trying to handle the `close` event with `electronApplication.on('close', callback)` when `app.quit()` is called does not trigger the callback.

**Comment by dgozman** [comment]
@luke-webdev I am not sure we thought about this case, so it could totally be that you have to call `electronApplication.close()` after you `app.quit` in your test. Perhaps we should fix that.

**Comment by jasonlor** [comment]
I'm seeing the same issue

**Comment by pavelfeldman** [comment]
Fixed in https://github.com/microsoft/playwright/commit/8232497c884e16d8846c6a8585c27691969c7739
