### ISSUE TITLE
How to create a browser profile in firefox?[Question]

### ISSUE THREAD

**Issue by SHADR1N** [microsoft/playwright#12197]
Hi.
You have the option to create a browser profile in firefox and chromium "launch_persistent_context", but then you can't add "firefox_user_prefs"!

How to be in such a situation? And why was it not provided immediately?

**Comment by dgozman** [comment]
If you use a persistent profile in Firefox, you can change anything you'd like in `about:config` page and it will be saved in the profile. Launching with that same profile next time will get all the settings you have. Does this answer your question?

**Comment by shirshak55** [comment]
@dgozman I think we can directly set those prefs programmatically when we do launch_persistent_context. He is probably facing the issue that the prefs used in launchPersistentContext is not being used.

**Comment by SHADR1N** [comment]
a rather bad solution, in my tasks to create 100 ... profiles, and it would not be convenient to do each one by hand, I found a solution, but it would be cool to add the parameter "firefox_user_prefs"

For those who need an answer to this:

After creating the profile folder, I add the user.js file to which I write down all the necessary browser parameters in the format:
'user_pref("media.volume_scale", false);'

This is the official solution from firefox

**Comment by wanghaisheng** [comment]
@SHADR1N selenium can pass profile save path like this
```
webdriver.Firefox(options=firefoxoptions,
                                            firefox_profile=firefox_profile, executable_path=executable_path)
                         
```
do you mean we need manually read from dir and set para to firefox_user_prefs?
@dgozman
