### ISSUE TITLE
[BUG] Android APP Testing: androidWebView.page: tracesDir

### ISSUE THREAD

**Issue by manuman94** [microsoft/playwright#12214]
**Context:**
- Playwright Version: v1.19.1
- Operating System: Linux
- Node.js version: v14.18
- Browser: Android APP

## System:
 - OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 196.99 MB / 15.45 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.0 - /usr/local/bin/node
 - Yarn: 1.22.5 - /usr/bin/yarn
 - npm: 8.5.0 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.17 - /bin/bash

**Code Snippet**

```typescript
async () => {
    // Connect to the device.
    const [device] = await android.devices();
    console.log(`Model: ${device.model()}`);
    console.log(`Serial: ${device.serial()}`);

    // --------------------- WebView -----------------------

    // Launch an application with WebView.
    const app_package = 'com.my.app_package';
    await device.shell(`am force-stop ${app_package}`);
    await device.shell(`am start ${app_package}/.MainActivity`);
    // Get the WebView.
    const webview = await device.webView({ pkg: app_package }); // <- Error: androidWebView.page: tracesDir must be specified for BrowserContext

    // Work with WebView's page as usual.
    const page = await webview.page();
    console.log(await page.title()); 
}
```

**Describe the bug**

Well, we are working with the experimental Android feature. The aim is to test an Ionic APP (webview) and we are getting this error:

```
Error: androidWebView.page: tracesDir must be specified for BrowserContext
```

Following the trace we got into the `/node_modules/playwright-core/lib/server/android/android.js` file, line 285. It seems like a validation requires the tracesDir value filled in the BrowserOptions object, but in that file [(line 280)](https://github.com/microsoft/playwright/blob/1215057ca1cf756f35e045a34fd340838bee81d8/packages/playwright-core/src/server/android/android.ts#L267) was setted an empty value hardcoded.

If we fill that variable with some value in that file (inside node_modules), even if the folder doesn't exist the tests are working properly. The APP is launched in the physical device and we can use the `page` object to interact with the webview page. But we don't find any way to pass it from outside as its value is hardcoded.

Is there anything we are missing?

Note: we are not using any kind of trace recording, at least to our knowledge hehe

Thank you so much.

**Comment by manuman94** [comment]
Hi! @mxschmitt , thank you for this fix.

Where can we find it until you release the v1.20? Is there a release candidate at the npm repository?

Thank you, greetings.

**Comment by mxschmitt** [comment]
> Hi! @mxschmitt , thank you for this fix.
> 
> Where can we find it until you release the v1.20? Is there a release candidate at the npm repository?
> 
> Thank you, greetings.

`npm i playwright@next` or `@playwright/test@next` depending on your system and package you use.

**Comment by manuman94** [comment]
Hi, @mxschmitt 
I tested the fix by using a mobile phone connected by USB to my local PC and it worked perfectly using the @next version.

But when I try to run the tests through the network to a remote android device (we have a few mobile devices used remotely for testing) I'm getting the same error (empty tracesDir). This is what is shown by the logcat of the mobile:

```
channel '9440f05  com.my.package/com.my.package.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed
```
_(this error multiple times)_

![image](https://user-images.githubusercontent.com/6721904/155519907-d1a8bdd0-aa71-4c1f-a9d2-de8cb86de392.png)

The only difference between them is:
- The working one is directly connected to the mobile phone by USB connection.
- The one that is not working is connected by using `adb connect MOBILE_HOST_IP:PORT`

Do you have any idea of what is going on there? Sorry but I can't find what is the difference.

I found that the problem is at the page() function, the next one to awaiting the webview event.

Thank you.

**Comment by mxschmitt** [comment]
Works for me! Maybe the Android devices has a too little android sdk version. Please open a separate issue, since I think the original issue has been solved.

**Comment by manuman94** [comment]
Sure! I will create a new issue.

Thank you for your help!
