### ISSUE TITLE
[Feature] Providing test filepaths with CLI

### ISSUE THREAD

**Issue by neutraali** [microsoft/playwright#12217]
In my use-case I have **Playwright** set up in one folder (including `config`) and then my test files outside that folder elsewhere in the file system. Using `@playwright/test@1.19.1` it doesn't seem possible to provide the `testDir` directly via the CLI.

**Using CLI directly:**
```
/example/folder$ npx playwright test /path/to/different/folder/example.spec.js // Does not work
/example/folder$ npx playwright test ../path/to/different/folder/example.spec.js // Does not work
```

**Altering playwright.config.js:**
```
testDir: /path/to/different/folder // Works!
testDir: ../path/to/different/folder // Works!
```

I would expect providing the test file/folder would work equally well through the CLI as it does through `config.testDir`.

**Comment by ltsuda** [comment]
Can you try passing your config file when using full filepath?

```bash
/example/folder$ npx playwright test -c playwright.config.js /path/to/different/folder/example.spec.js
```

**Comment by dgozman** [comment]
@neutraali `testDir` defaults to the directory containing the `playwright.config` file. If your tests are outside of this dir, you have to specify the `testDir` in the config. 

Passing paths to the command line is just a test filter, it does not control the `testDir`. This is what `npx playwright test --help` says:
```log
Arguments [test-filter...]:
  Pass arguments to filter test files. Each argument is treated as a regular expression.
```

If you have an idea on how to improve the documentation to make this clear, that would be great!

**Comment by dwalleck** [comment]
Last week, one of my teammates asked me a similar question about running tests from something other than the default test directory. The solution I gave them was still using one test directory but having sub-directories as needed. In their case, this was probably enough, but I gave it some more thought this weekend. I see a few options for this scenario.

1. [Projects](https://playwright.dev/docs/test-advanced#projects) appear to allow you to provide a test directory per project
2. Set up your `playwright.config.ts` to optionally take an environment variable as an override for the test directory
3. Add a new command-line argument to allow you to specify the test directory explicitly (ex: `npx playwright test --test-dir visual-regression/`)

**Comment by neutraali** [comment]
@dgozman IMO it would make more sense intuitively to actually have the `test-filter...` -arguments (renamed to just `files...`, for example)  actually target the files and/or directories specified, rather than acting as a filter.

@dwalleck We're going with the second option currently. Feels kinda dirty to use environment variables, but as `playwright` has no **NodeJS API** we're hacking the config file itself and it works for now.

**Comment by yury-s** [comment]
Closing the issue per the [comment above](https://github.com/microsoft/playwright/issues/12217#issuecomment-1045002921). We don't have current plans to allow providing test locations except for the config.

**Comment by mykhailo-kobylianskyi** [comment]
> 3\. --test-dir visual-regression/

I've tried to use third  option, which would be perfect for me. Although it's not working. 
`playwright test --config=main.config.ts --test-dir tests/project1` OR  `playwright test --config=main.config.ts --test-dir=tests/project1`  neither  seems good. 

Could you specify are there special preconditions needed? b/c I keep getting `error: unknown option '--test-dir'`
