### ISSUE TITLE
[Feature] Configurable listen time for isVisible() and related helpers

### ISSUE THREAD

**Issue by timbrinded** [microsoft/playwright#12224]
When executing scenarios, there may need to be conditional logic based on the presence of certain page elements rendered. E.g.
```
const switch = await page.locator(".className").isVisible()
switch ? truthyLogic() : falsyLogic()
```

However `isVisible()` can return a false determination too quickly. In pages I've tested, some elements only are visible on re-render, which can happen a few seconds after initial render completes. 

It would be a very helpful feature to be able to specify a listen time for `isVisible()` so that it only returns a false after a specific period of time of waiting.

**Comment by mxschmitt** [comment]
seems like something like this would solve it:

```js
const locatorExists = async (locator: Locator) => (await locator.waitFor({ timeout: 5000 }).catch((e: Error) => e)) instanceof Error;
const exists = await locatorExists(page.locator('foo'));
```

Might make sense to add a similar API to Playwright, since I've seen such requests often in the past.

**Comment by ShanmukhaGajula** [comment]
True, that would help me too..

**Comment by pavelfeldman** [comment]
You should instead use `await exepct(locator).toBeVisible({ timeout? })`

**Comment by privorotskii** [comment]
> You should instead use await exepct(locator).toBeVisible({ timeout? })

Hey @pavelfeldman, that's not really what was looked for in that issue, can we reopen that?

`expect().toBeVisible` is an assertion which marks test as failed, throws an exception, it doesn't provide a way to just check whether there's some content on page.

`isVisible` provides such possibility, but there's no option to set timeout to wait for element to appear (or not appear).

There's an issue https://github.com/microsoft/playwright/issues/12275 where it's visible that such feature is in demand, can we add it?

**Comment by co510** [comment]
+1 to the comment by @privorotskii.  There are times when I want a test to fail if something isn't visible on page, and there are times I simply want to know whether an element's visible or not so I can dictate what the test pattern should be going forward.

In general it's not great practice to be try{} catching() all over your code :)

**Comment by venka66** [comment]
It would be extremely helpful to specify a wait time for the `isVisible()` method. Otherwise `Task.Delay` needs to be relied upon for an explicit wait before the element's presence can be determined to proceed with the rest of the test, especially in pages where the elements are not rendered as fast as the method call.

**Comment by hcura-qa** [comment]
> seems like something like this would solve it:
> 
> ```js
> const locatorExists = async (locator: Locator) => !((await locator.waitFor({ timeout: 1000 }).catch((e: Error) => e)) instanceof Error);
> 
> const exists = await locatorExists(page.locator('foo'));
> ```
> 
> Might make sense to add a similar API to Playwright, since I've seen such requests often in the past.

It works as expected on the test flow, but unfortunately, when the locator is not present, the test got a fail flag.
A similar API on Playwright would be much appreciated!

**Comment by heygarrett** [comment]
> A simple example of this is a notification blocking the screen for some users who haven't filled in a new form. Whenever testing begins as a test user, if there is a notification within the first 5000 milliseconds, we want to close it. Whether or not the notification appears is not a reason to pass/fail any tests.

There's an experimental method, `addLocatorMethod`, for this type of scenarios as of version 1.42:  
https://playwright.dev/docs/api/class-page#page-add-locator-handler
