### ISSUE TITLE
[BUG] WebKit / Chromium setting a cookie with expiration does not work

### ISSUE THREAD

**Issue by rado-o** [microsoft/playwright#12226]
**Context:**
- Playwright Version: 1.19.0
- Browser: WebKit
- CI/CD: GitLab (Docker image: playwright:focal)
- [Failed pipeline run](https://gitlab.com/radomir_oravec/plawright_webkit_error/-/pipelines/474482630)

**Code Snippet**
[Sample test](https://gitlab.com/radomir_oravec/plawright_webkit_error/-/blob/main/tests/inventory_page.spec.ts)

**Describe the bug**
Running the sample test on GitLab CI/CD (Docker) fails only in WebKit - not reproducible for Firefox/Chrome.
The issue is not reproducible when running the test in WebKit locally (Windows 10, Node.js : v16.13.2)
```
browserContext.addCookies: Protocol error (Playwright.setCookies): Internal error: no network storage [{"code":-[32](https://gitlab.com/user/plawright_webkit_error/-/jobs/2111581501#L32)000,"message":"Internal error: no network storage"}]
      14 |             secure: false
      15 |         }];
    > 16 |         await context.addCookies(validCookieSession);
         |                       ^
      17 |     });
      18 |
      19 |     test('Inventory Page - Navigate', async({page}) => {
        at /builds/user/plawright_webkit_error/tests/inventory_page.spec.ts:16:23
```

**Comment by rado-o** [comment]
Hi @dgozman,

yes, the error is thrown in each test executed in WebKit (Gitlab CI/CD) when the cookies are being set up directly (context.addCookies(cookies)). In the shared project I provided a dummy test executed on a public test website.

I added the environment variable to the script: [pipeline run](https://gitlab.com/radomir_oravec/plawright_webkit_error/-/pipelines/474878565)

Logs:
```
pw:browser <launching> /ms-playwright/webkit-1609/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=239 +5ms
  pw:browser [pid=239] <gracefully close start> +198ms
  pw:browser [pid=239] <process did exit: exitCode=0, signal=null> +5ms
  pw:browser [pid=239] starting temporary directories cleanup +1ms
  pw:browser [pid=239] finished temporary directories cleanup +9ms
  pw:browser [pid=239] <gracefully close end> +1ms
  1) [Desktop WebKit] › inventory_page.spec.ts:19:5 › Inventory Page Suite › Inventory Page - Navigate 
    browserContext.addCookies: Protocol error (Playwright.setCookies): Internal error: no network storage [{"code":-32000,"message":"Internal error: no network storage"}]
      14 |             secure: false
      15 |         }];
    > 16 |         await context.addCookies(validCookieSession);
         |                       ^
      17 |     });
      18 |
      19 |     test('Inventory Page - Navigate', async({page}) => {
        at /builds/user/plawright_webkit_error/tests/inventory_page.spec.ts:16:23
```

**Comment by mxschmitt** [comment]
Very helpful repro @rado-o, thank you! Was able to repro, it's caused by the `expiration` property. As a workaround you could change it to `-1` until its getting fixed.

**Comment by rado-o** [comment]
Hi @mxschmitt 
thank you for the hint: I've just made the suggested adjustment and the pipeline passed :)
[Pipeline run](https://gitlab.com/radomir_oravec/plawright_webkit_error/-/commit/276abd2dbfb888cab994a8c8ea0f36b74556726b)
