### ISSUE TITLE
[BUG] screenshot closes <select> list

### ISSUE THREAD

**Issue by TimWillis** [microsoft/playwright#12229]
**Context:**
- Playwright Version:1.19.1
- Operating System: Win 10
- Node.js version: v13.7.0
- Browser: edge/chrome
- Extra: NA

const run_on_click_event_from_client = () => {
     const buffer = await recorded_page.screenshot().catch((e) => {
            console.log("error getting screenshot", e);
        });
}
I trigger this code with an event from the client sent via sockets. So the user clicks a <select> tag, the client sends a message to the playwright "server", which calls the above function. The screenshot closes the <select> list. Which should not close the select list. 

Another weirdness is that it works for private browsing, but not for the launchPersistentContext

Because the screenshot closes the select the user cannot choose an option in the select...

**Comment by dgozman** [comment]
@TimWillis Could you please share the full script we can run to repro? If not, please at least share the page url that has this select and exhibits the problem.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by sergzak022** [comment]
Hey @dgozman, @mxschmitt , to reproduce this issue you can use https://www.opentable.com/ web site that has uses `select` HTML tag for dropdown selector.

When playwright.js takes a screenshot, it closes a dropdown for `<select>` tag

Can we reopen this issue please? Thank you in advance

**Comment by agn-7** [comment]
any update?
same issue
