### ISSUE TITLE
[Feature] need mouseWheel MouseEvent

### ISSUE THREAD

**Issue by salisbury-espinosa** [microsoft/playwright#1222]
spec: https://github.com/chromium/chromium/blob/master/third_party/blink/public/devtools_protocol/browser_protocol.pdl#L3332

need patch for file : https://github.com/microsoft/playwright/blob/master/src/chromium/crInput.ts#L72

**Comment by pavelfeldman** [comment]
Could you share more about the scenario you'd like to support? We are well aware of all the CDP methods since we added them there at the first place, but with Playwright we are trying to start with the testing user stories.

**Comment by dgozman** [comment]
Could you please continue the discussion in #1115, which already has more context?
