### ISSUE TITLE
[BUG] Still present: browserContext.close: tracing.stopChunk: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by awmcclain** [microsoft/playwright#12238]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.17.1
## System:
 - OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 2.06 GB / 15.63 GB
 - Container: Yes
## Binaries:
 - Node: 14.19.0 - /usr/local/share/nvm/versions/node/v14.19.0/bin/node
 - Yarn: 1.22.17 - /usr/bin/yarn
 - npm: 6.14.16 - /usr/local/share/nvm/versions/node/v14.19.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Describe the bug**

Happens during a flaky timeout error, only when running multiple test suites.

We're also seeing behavior where the test fails without this error, but the trace is still corrupted.

Is there any way to see which tests are running concurrently? That might help us narrow this down.

**Comment by mxschmitt** [comment]
Do you have a repro for us? Do you manually stop the trace? Are you using @playwright/test?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
