### ISSUE TITLE
[Question] How to check if backward / forward navigation is currently possible ?

### ISSUE THREAD

**Issue by niranjan94** [microsoft/playwright#12257]
In browsers, the backward/forward navigation buttons are disabled/enabled depending on whether navigation in that direction is possible. Is there any way this information can be obtained from within playwright ?

**Comment by mxschmitt** [comment]
This is not possible as of today, but you could manually keep track of the history with the frame navigated event, but has probably its limitations.

```js
// @ts-check
const playwright = require('playwright');

(async () => {
    const browser = await playwright.chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    page.on("framenavigated", f => console.log("navigated: " + f.url()))
    await page.goto('http://whatsmyuseragent.org/');
    await page.goto('http://github.com');
    await page.goBack()
    await page.goBack()
    await page.goForward()
    await browser.close();
})();
```

**Comment by mxschmitt** [comment]
Closing for now since it's answered, please file a new issue for further questions.
