### ISSUE TITLE
[Feature] Make socks5 support with authorization

### ISSUE THREAD

**Issue by SHADR1N** [microsoft/playwright#12252]

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/10567

**Comment by b5414** [comment]
@mxschmitt hello, why is it closed? 

I still see: `browserType.launch: Browser does not support socks5 proxy authentication` with `playwright 1.22.0-alpha-1652115973000`

**Comment by b5414** [comment]
@mxschmitt hello, why is it closed? 

I still see: `browserType.launch: Browser does not support socks5 proxy authentication` with `playwright 1.22.0-alpha-1652115973000`

**Comment by mxschmitt** [comment]
Because the feature request for it is in https://github.com/microsoft/playwright/issues/10567
