### ISSUE TITLE
[Question] Sub-Locators

### ISSUE THREAD

**Issue by cebaa** [microsoft/playwright#12251]
Simplified motivating example in case this is a XY-problem:

```
<div class="item">
  <span class="type">type_a</span>
  <div>
    <span class="data">data_a</span>
    <span class="data">data_a_unwanted</span>
  </div>
</div>

<div class="item">
  <span class="type">type_b</span>
  <div>
    <span class="data">data_b_unwanted</span>
    <span class="data">data_b</span>
  </div>
</div>
```

I'm looking to gather all wanted `data`s for all `item`s and then perform additional actions (e.g. click on) `items`s based on their `data`. So in the above example, get `data_a` and `data_b`, but not `data_a_unwanted` and `data_b_unwanted`. The processing depends on the `type` and external information (i.e. information outside of the web page - think `type` → selector mapping).

To put it another way, in the above example, I don't know which of the `data_X` and `data_X_unwanted` is actually unwanted from the page itself. The layout is rather complicated, so sub-selectors would help a lot compared to manual iterating. The selectors are dynamic and not a fixed set, though they can be generated on startup.

To me, the logical way to do this would be:

- Locate all `item`s and their `type`
- Using the external mapping, look up the selector based on the `type`
- (Sub-)locate with that selector on that `item` only
- Perform required actions on `items` depending on the contents of their respective `data`

I guess I'm at least partially after something like this https://playwright.dev/docs/selectors#chaining-selectors, i.e. I should be able to make a string selector for each of the type, but I'm looking for something more type-safe if that exists. I think the `querySelector` analogue on that page is what I'm after.

**Comment by mxschmitt** [comment]
I think what you actually need are locators: https://playwright.dev/docs/locators

You can loop over them: https://playwright.dev/docs/locators#lists

and you can create a locator based on another locator: https://playwright.dev/docs/api/class-locator#locator-locator

**Comment by cebaa** [comment]
> and you can create a locator based on another locator: https://playwright.dev/docs/api/class-locator#locator-locator

Thanks @mxschmitt - that's exactly what I was looking for!
