### ISSUE TITLE
[Question] How to log/print some custom message in html report?

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#12261]
hi, How to log/print some custom message in html report? probably under a step

**Comment by mxschmitt** [comment]
What kind of message do you want to print? You can use annotations if you have something per test basis like that:

```js
  test.info().annotations.push({ type: 'something', description: 'some description' });
```

Also console.logs should get reflected in the stdout section. For grouping, you can use test steps: https://playwright.dev/docs/api/class-test#test-step

**Comment by mxschmitt** [comment]
Closing since its answered, for further questions please file new issues.

**Comment by ShanmukhaGajula** [comment]
Thank you for your response.
