### ISSUE TITLE
[BUG] Firefox: White video when trace + video is enabled

### ISSUE THREAD

**Issue by rado-o** [microsoft/playwright#12266]
**Context:**
- Playwright Version: 1.19.1
- Environments:
_GitLab CI/CD:_
-- running in the docker image: mcr.microsoft.com/playwright:focal
- _Local:_
-- Windows 10
-- Node.js version: 16.13.2
- Browser: Firefox (headless)

**Code Snippet**
[Sample Test](https://gitlab.com/radomir_oravec/playwright_firefox_error/-/blob/main/tests/inventory_page.spec.ts)

**Describe the bug**
Blank videos are being recorded when running the tests in Firefox - headless mode. Reproduced in: GitLab CI/CD & running locally.
Not reproduced in Firefox - headfull mode (locally).
Not reproduced for Chromium/WebKit - headless mode.
See report examples (with videos):
[Firefox (blank video)](https://radomir_oravec.gitlab.io/-/playwright_firefox_error/-/jobs/2116969937/artifacts/report/index.html)
[Chromium (OK)](https://radomir_oravec.gitlab.io/-/playwright_firefox_error/-/jobs/2116969917/artifacts/report/index.html)
[WebKit (OK)](https://radomir_oravec.gitlab.io/-/playwright_firefox_error/-/jobs/2116969941/artifacts/report/index.html)

**Comment by mxschmitt** [comment]
Thank you for the repro! Very helpful :)

I made a more minimal repro case:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './tests',
  reporter: [
    ['html', { open: 'never', outputFolder: './report' }],
    ['list'],
  ],
  use: {
    trace: 'on',
    video: 'on'
  },
  projects: [
    {
      name: 'Firefox',
      use: {
        browserName: 'firefox'
      },
    },
  ],
};

export default config;
```

```ts
import { test } from '@playwright/test';

test('Inventory Page - Navigate', async ({ page }) => {
    await page.goto('https://example.com');
    await page.waitForTimeout(2000);
})
```

-> when `trace` and `video` is enabled, Firefox ends up in a white video.

**Comment by p01** [comment]
A partner team is onboarding to Playwright 1.19, I recommended to `use: { "trace": "retain-on-failure", "video": "retain-on-failure", }` but strangely they only get traces. No video at all.

**Comment by ivanrosvimi** [comment]
Any update on this? It is still happening in version 1.22.1

**Comment by AdiRishi** [comment]
This is still present in playwright `1.25.2`. Any updates?

**Comment by MasterOdin** [comment]
We're seeing this error on playwright `1.27.1`.

**Comment by hmajid2301** [comment]
Still seeing this error on` 1.30.0-alpha-jan-5-2023` (`@playwright/test` package)
