### ISSUE TITLE
[BUG] selectors in trace viewer unnecessarily truncated when there's enough room to show the full selector

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#12278]
**Context:**
## System:
 - OS: Windows 10 10.0.18363
 - Memory: 1.11 GB / 15.78 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

**Code Snippet**

```javascript
await page.click("//some/very/long/selector/asdfasdfasdfsdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf");
```

**Describe the bug**

when the sidebar on the right of the trace viewer is expanded to make room to display the selector, it is unnecessarily truncated:
![image](https://user-images.githubusercontent.com/57028336/155037149-031f60e7-72ad-4275-b841-1fed5caacfe6.png)

it already gets correctly truncated when the sidebar is too small, so there's no need to truncate the actual value
![image](https://user-images.githubusercontent.com/57028336/155037268-1b2e48f7-c4b8-4702-9032-5aad103efb3a.png)

**Comment by mxschmitt** [comment]
I can't repro, which Playwright version are you using?
