### ISSUE TITLE
[Question] Click retries might leave the page in a fixed scrolled state

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#12270]
I found that in some pages (well, one page), the different `scrollIntoView` retries might leave the page "scrolled" but with no scrollbars.

For instance:

```js
const browser = await playwright.chromium.launch({headless: false});
let page = await browser.newPage();
await page.goto('https://sph.synxis.com/pms-web-ui/login');
await page.evaluate(el => {
  const div = document.createElement('div');
  div.style=' position: fixed;width: 100%; height: 100%; top: 0;left: 0;right: 0;bottom: 0;background-color: rgba(0,0,0,0.01);;z-index: 200;cursor: pointer;'
  document.body.appendChild(div)
});
await page.click('text=Username (Required)', {timeout: 400});
await page.pause();
await browser.close();
```

The page might be left on this scenario:

<img width="1283" alt="image" src="https://user-images.githubusercontent.com/2198466/154982984-19b3908b-45b5-4d16-b2ab-8d7834d977c5.png">

Also, if we increase the click timeout, we would see the page shaking a lot trying to get the element into view.

### Thoughts/Questions
* I don't get that "shake" on the amazon login. Do you know what's on this HTML that would produce this "shake"?

```
await page.goto('https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_custrec_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&');
await page.evaluate(el => {
    const div = document.createElement('div');
    div.style=' position: fixed;width: 100%; height: 100%; top: 0;left: 0;right: 0;bottom: 0;background-color: rgba(0,0,0,0.01);;z-index: 200;cursor: pointer;'
    document.body.appendChild(div)
  });
await page.click('#ap_email', {timeout: 3000});
```

* Do you think that scrolling into view, when we could know that the element is inside the viewport, is the right strategy there? (real question, not retorical :))

This is not a blocker, it's more like it would be nice to have a different behavior.

**Comment by dgozman** [comment]
> I found that in some pages (well, one page), the different scrollIntoView retries might leave the page "scrolled" but with no scrollbars.

This is very unfortunate, I agree. Usually, this just means a bad page with some kind of `overflow:hidden` but large content below the fold. 

In most cases, selecting some text and then shift+down many times could actually scroll the `overflow:hidden` container and leave the page in the same state. That said, on `https://sph.synxis.com/pms-web-ui/login` I was not able to interact in any way, so I am not sure 😄 

If you have any ideas on how to improve things here, that would be nice. I don't see an easy solution right now.

> Do you think that scrolling into view, when we could know that the element is inside the viewport, is the right strategy there?

Yes, this strategy allows to scroll from under the sticky/fixed overlays. Like in your example, if you make the overlay div just 200px high (or so), it would be possible to click on the email input once you scroll the page, but not from the start. Does that make sense?

Does this bring any issues, apart from visual shaking that's usually unexpected when running headed?

**Comment by kblok** [comment]
Thank you for taking a look at it @dgozman.
It was in fact due to an `overflow:hidden` on a `spark-splash-screen` class. Good eye! :)

> If you have any ideas on how to improve things here, that would be nice. I don't see an easy solution right now. 

I was thinking whether we should try to scroll back to the original location if we don't get an actionable element. That was what I thought we were doing :p, till I set some more specific timeout to reproduce the error.
But in this case, it wouldn't work, because that `overflow` will leave the page quite broken.

> Does this bring any issues, apart from visual shaking that's usually unexpected when running headed?

The main issue here would be the screenshot you'd get after this failed step. But no more than that.
Feel free to close this issue. I just wanted to bring the team's attention to this. And thank you again :)

**Comment by dgozman** [comment]
> That was what I thought we were doing :p, till I set some more specific timeout to reproduce the error.

Heh 😄  That would be an ok solution, but technically challenging, because we might scroll many containers, natively in the browser, and also not have enough time to scroll back before timing out, etc. So, maybe in the distant future?

> But no more than that. Feel free to close this issue.

Ok, so let me close the issue. Thanks for filing though! It's always nice to hear from you, Darío 😃

**Comment by kblok** [comment]
@dgozman would you buy an option to disable extra `scrollIntoView` options? 
Basically limiting the `forceScrollOptions` to the first element of `scrollOptions`.
I've got another case where the page ends up in an unusable state if I fail to click on one element.

**Comment by dgozman** [comment]
@kblok Not sure right now. Let me reopen and see whether that would be a popular request. When testing, failed click usually means that test fails and so it does not matter in which state the page is left. Thus, I don't expect a lot of demand for this, unfortunately.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
