### ISSUE TITLE
[Question] Is it possible to do an "if ( found )" type logic?

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12275]
I want to have PW delete a record if it is detected in a list on the page. If the record does not exist then the test should complete without failure. Is this possible?

e.g.

         await test.step('Step #x - Look for a specific record in the list ', async () => {

                  await page.locator('.list_field_classname', {hasText:'XXX' });
                  if ( found ) {      <------------------------------------------------------------------ how to do this?
                      await page.dblclick('.list_field_classname', { hasText: 'XXX' });  // Open the page record

                      await expect(page).toHaveURL('http://yyyyyy');
                      await expect('#UID-Field-Id').toBe('XXX'); // check the record has been opened
                  
                      await page.click('button_delete'); // click on the delete button to delete it
                  }
            });

**Comment by mxschmitt** [comment]
Yes, you can do: `if (await page.locator('....').isVisible()) {`

Related to https://github.com/microsoft/playwright/issues/12224

**Comment by mxschmitt** [comment]
Seems like the element is then not on the page if its not entering the if block.

**Comment by alanbqs** [comment]
When running in --debug I can see the console log as expected - but when running without it I do not.

I've added an ```else console.log('Find ABC')``` to the if, and I see this when running without --debug, but I see "Found ABC" when running with --debug.

**Comment by mxschmitt** [comment]
Then you need to wait for the element to appear, either but using locator.waitFor() but then you'll always be sure that the element is there. Try using the helper method which I created in https://github.com/microsoft/playwright/issues/12224#issuecomment-1044786896. I think thats exactly what you want. "Wait up to X milliseconds for the element to appear"

**Comment by alanbqs** [comment]
This does sound valid - each of my screens have a pre-loader/pre-finisher overlay shown while filters, etc are  added and adjusted - adding maybe up to 1 second to the presentation of the final screen - but having adjusted the code to read as follows - I still do not get the "Found ABC" message

```
                  console.log('Looking for ABC');

                  const locatorExists = async (locator: Locator) => (await locator.waitFor({ timeout: 5000 }).catch((e: Error) => e)) instanceof Error;
                  const exists = await locatorExists(page.locator('.listcol_fieldnm', { hasText: 'ABC' }));

                  console.log('Looking for ABC');
                  if ( exists ) {
                        await page.screenshot({ path: "tests/screenshots/listscreen." + workerInfo.project.name + ".png" });
                        console.log('Found ABC');

                        await page.dblclick('.listcol_fieldnm', { hasText: 'ABC' }); // Open the edit screen behind the list row....

                        await expect(page).toHaveURL('http://.......');
                        await expect('#FieldNm').toBe('ABC');

                  }
                  else {
                        console.log('Did not find ABC');
                        await page.screenshot({ path: "tests/screenshots/listscreen." + workerInfo.project.name + ".png" });
                  }
```

**Comment by alanbqs** [comment]
.. running this in --debug it looks like the script jumps straight from the ```const locatorExists =``` line onto the ```console.log('Did not find...')``` without allowing me to see what the exception is.  How can I adjust this to see what the error might be (assuming there is one there)?

**Comment by alanbqs** [comment]
The locatorExists above was not quite right and should have been

```
const locatorExists = async (locator: Locator, timeout: number = 1000) => !((await locator.waitFor({ timeout }).catch((e: Error) => e)) instanceof Error);
```

See https://github.com/microsoft/playwright/issues/12382#issuecomment-1054170876
