### ISSUE TITLE
[Question] I am not able to click a submit button when an ads is appear over this button. 

### ISSUE THREAD

**Issue by shubhamkgupta14** [microsoft/playwright#12282]
### Task - To fill the sample form and verify the same after submit the form.

**Issue - I am not able to click the submit button when an ads appear over the submit button element.**

**Context:**

Playwright Version: 1.17.1
Operating System: Windows
JavaSE - 1.8
Browser: Chromium

Here is the sample code snippet -

```
public class AppTest {
	Playwright playwright;
	BrowserType browserType;
	Browser browser;
	BrowserContext browserContext;
	Page page;

        @Test
	public void sampleTest() {
		browser = Playwright.create().chromium().launch(new BrowserType.LaunchOptions().setHeadless(false));
		browserContext = browser.newContext();
		page = browserContext.newPage();
		page.navigate("https://demoqa.com/");
		
		page.click(".category-cards > div:nth-child(1) > div");
		page.click(".left-pannel > div > div:nth-child(1)  .menu-list > li:nth-child(1)");
		
		page.fill("#userName", "Full Name");
		page.fill("#userEmail", "user@gemail.com");
		page.fill("#currentAddress", "cur Addr");
		page.fill("#permanentAddress", "per Addr");
		page.click("//button[@id='submit']");      // On this line I have the issue.
		assertEquals("Name:Full Name", page.textContent("#output > div > p#name"));
	}
}
```

I have the issue on 20th line - ``` page.click("//button[@id='submit']"); ```

Please help me to solve this issue.

**Comment by mxschmitt** [comment]
> Issue - I am not able to click the submit button when an ads appear over the submit button element.

A user is also not possible to click this button otherwise. :)

You can try `page.click("//button[@id='submit']",  new Page.ClickOptions().setForce(true))` but most likely it won't work so you need to close the ad first.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
