### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by eoinomeara11** [microsoft/playwright#12289]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Windows 10
- Node.js version: 16.13.2
- Browser: [e.g. Chromium, Edge

**Describe the bug**

When debugging long visual regression tests in playwright test --debug some snapshots are highlighted in blue while others are not. I am taking snapshots of a complicated canvas element after it has been drawn (vis.js network). The highlight does not appear consistently. I feel the highlight should not be in the snapshot at all as it is only a convenience for debugging and should not be in any snapshots. The highlight also is a barrier to sharing snapshot images between debug and normal testing.

**Comment by mxschmitt** [comment]
Could you provide us some example screenshots and a link to an example vis.js network which demonstrates it?

Something like that? https://visjs.github.io/vis-network/examples/network/basic_usage/standalone.html

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
