### ISSUE TITLE
[BUG] `page.screenshot` does not have a snapshot

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#12280]
**Context:**
## System:
 - OS: Windows 10 10.0.18363
 - Memory: 3.04 GB / 15.78 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE

**Code Snippet**

```javascript
await page.screenshot()
```

**Describe the bug**
`page.screenshot` doesn't have a snapshot, which means it doesn't show in the trace file.

it doesn't make sense to not include a snapshot on `page.screenshot` because chances are the user wants to see the screen when calling this method

![image](https://user-images.githubusercontent.com/57028336/155067592-1a8234c9-37ec-4b2d-a6f5-ddd6e81bf74a.png)

**Comment by mxschmitt** [comment]
I can repro:

```js
import { test } from '@playwright/test'

test("fooo", async ({ page }) => {
  await page.screenshot();
})
```
