### ISSUE TITLE
[BUG] Inconsistency when taking screenshot in headed mode vs headless mode

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#12287]
**Context:**
- Playwright Version: 1.19.1
- Operating System: mac
- Node.js version: 14
- Browser: chromium and firefox , webkit is fine
- Extra: [any specific details about your environment]

**Code Snippet**

```
const config = {
    workers: configList.workers,
    use: {
        trace: 'retain-on-failure',
        headless: true,
        viewport: null,
    },
    projects: [{ name: 'Desktop Chrome', use: { browserName: 'chromium' } }, { name: 'Desktop Firefox', use: { browserName: 'firefox' } }, { name: 'Desktop Safari', use: { browserName: 'webkit', viewport: { width: 1280, height: 720 } } }],
}
```

```
    test('test', async ({ browserName }) => {
        expect(await publicSearch.headerScreenshot()).toMatchSnapshot(`${browserName}-header-EN.png`);
    });

```

**Describe the bug**
Im running certain test cases to assert snapshot of an element, all tests are passing in headed mode against the three browsers chromium, firefox and webkit, but when running same tests in headless mode chromium and firefox are failing however configs are the same

**Comment by mxschmitt** [comment]
Can you provide us an example how the expected, actual, diff looks like in your scenario? @aslushnikov is working on it and it might be already fixed.

**Comment by amrsa1** [comment]
@mxschmitt yes sure

the screenshot below was running on headed mode, all passed
<img width="162" alt="Screenshot 2022-02-23 at 11 55 57" src="https://user-images.githubusercontent.com/32042806/155306165-de6f4e08-b7f2-4b62-9281-fb133dbfad2c.png">

same tests executed again  but headless mode all fail except safari 
<img width="857" alt="image" src="https://user-images.githubusercontent.com/32042806/155307703-3ef1d7c5-b658-4fea-9fa0-c2157250423c.png">

**Comment by amrsa1** [comment]
@mxschmitt  i have tried the same scenario but with full screen snapshot and i got same result passing on one mode but not the other, also it seems there is always this 15px difference between snapshot taken in headless and one taken in headed mode

`Sizes differ; expected image 1280px X 1505px, but got 1265px X 1505px.  `

**Comment by aslushnikov** [comment]
@amrsa1 just to validate, can you try launch chromium like this?

```
const browser = await chromium.launch({
	headless: true,
	ignoreDefaultArgs: ['--hide-scrollbars']
});
```

**Comment by amrsa1** [comment]
@aslushnikov same result working in headless but not in headed, the only difference that now which i check the difference between the actual and expected result they are identical but still failing, as u can below there is not difference between the two picture in allure report and also there is not any log showing the sizes differ as before

<img width="1158" alt="Screenshot 2022-02-24 at 09 55 23" src="https://user-images.githubusercontent.com/32042806/155491813-e4b6c472-2a79-40eb-bd79-ee3d6bf16995.png">

**Comment by aslushnikov** [comment]
@amrsa1 peculiar. Any chance you can share a website + script so that I can reproduce this locally?

**Comment by amrsa1** [comment]
im afraid i cant share the website :(

but i think its failing for any website you can try, steps are pretty simple configs i put in description, then run the following test one time in headless and one time in headed , if you fail to reproduce it maybe i can show it to you privately.
        expect(await publicSearch.headerScreenshot()).toMatchSnapshot(`${browserName}-header-EN.png`);

**Comment by sahmeepee** [comment]
I have also seen this bug in recent versions. My assumption was that the images differed by the width of the vertical scrollbar on the right hand side of the browser. In win10 & chromium I was finding it was 17px so the screenshot widths were 1280px vs 1263px.

**Comment by aslushnikov** [comment]
Merging this to a broader headless vs headful discussion: https://github.com/microsoft/playwright/issues/12683
