### ISSUE TITLE
[BUG] Using .jsonValue() inside page.on('console') listener produces inconsistent output

### ISSUE THREAD

**Issue by Sid200026** [microsoft/playwright#12281]
**Context:**
- Playwright Version: 1.9.1
- Operating System: Windows
- Node.js version: 16.13.2
- Browser: Chromium, Firefox, WebKit
- Extra: NA

**Code Snippet**

Snippet taken from [Playwright Page Docs](https://playwright.dev/docs/api/class-page#page-event-console)

```javascript
test("Console Repro Test", async ({ page }) => {
  page.on("console", async (msg) => {
    const values = [];
    for (const arg of msg.args()) values.push(await arg.jsonValue());
    console.log(...values);
  });
  await page.evaluate(() => console.log("hello", 5, { foo: "bar" }));
});

```
**Error Stack**
```js
> console-repro@1.0.0 test
> playwright test

Running 1 test using 1 worker

✘ sample.spec.js:3:1 › Console Repro Test (808ms)

1. sample.spec.js:3:1 › Console Repro Test =======================================================


    jsHandle.jsonValue: Target closed

      4 |   page.on("console", async (msg) => {
      5 |     const values = [];
    > 6 |     for (const arg of msg.args()) values.push(await arg.jsonValue());
        |                                                         ^
      7 |     console.log(...values);
      8 |   });
      9 |   await page.evaluate(() => console.log("hello", 5, { foo: "bar" }));
```
**Describe the bug**

The above code snippet produces an inconsistent output. It fails or passes depending on the time when the page is closed. An alternative solution is to use `msg.text()` but it fails to convert objects or arrays to strings. For example the `msg.text()` for the following code snippet cannot parse objects or arrays.

```js
console.log("hello", [{ a: 1 }, 2, 3], 5, { foo: "bar" })
```

Webkit - `hello [,2,3] 5 {foo: bar}`
Chromium - `hello [Object,2,3] 5 {foo: bar}`
Firefox - `hello Array 5 JSHandle@object`

Is there any alternate or proper ways in which we can tap into the console logs?

**Comment by mxschmitt** [comment]
> `jsHandle.jsonValue: Target closed`

You need to call it before the page is closed, or use e.g. `page.waitForEvent('console')`.

See the following example:

```js
  const [message] = await Promise.all([
    page.waitForEvent('console'),
    page.evaluate(() => console.log("hello", 5, { foo: "bar" }))
  ])
  const values = [];
  for (const arg of message.args()) values.push(await arg.jsonValue());
    console.log(...values);
```

It's a known problem that `text()` is inconsistent.

**Comment by Sid200026** [comment]
> You need to call it before the page is closed, or use e.g. `page.waitForEvent('console')`.

Suppose we want to know whether a particular webpage has any console logs or not, and if it has any console events, we need to capture them. The `page.waitForEvent('console')` waits till it gets a console event. However in a scenario, where there isn't any console events, the test times out since it continuously waits for the event. Is there any work around for this scenario?

**Comment by mxschmitt** [comment]
There are multiple workarounds for that, the easiest is probably to race it with the page.on("close", ()=> ...) event.

**Comment by Sid200026** [comment]
Promise.race() looks like an easy work around. Thanks for your help

**Comment by manoraj** [comment]
> Promise.race() looks like an easy work around. Thanks for your help

Hi @Sid200026 I ran into this problem recently and would be a great help if you can share the code snippet you tried?
