### ISSUE TITLE
[BUG] `npx envinfo --preset playwright --markdown` doesn't include the playwright version

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#12286]
the issue template tells you to run this command, but it doesn't output the playwright version

![image](https://user-images.githubusercontent.com/57028336/155138288-58ca664c-3bd0-42e1-85b7-5e3bd83af9fd.png)
![image](https://user-images.githubusercontent.com/57028336/155138213-efa8d05f-46a4-4c93-898f-5d10ccc6cbb5.png)

**Comment by mxschmitt** [comment]
I've created https://github.com/tabrindle/envinfo/pull/220 for it.

**Comment by mxschmitt** [comment]
Closing for now since this the PR is being created.
