### ISSUE TITLE
[BUG] Trace Viewer's action dot moves as you scroll the image

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright#12288]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.18.0
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] N/A 
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]: 

```
width: 1920
height: 1080
is mobile: false
```

**Describe the bug**

The action dot in the trace viewer moves as you scroll the image.  This makes the action dot misleading as it moves and could be on an element where the action didn't happen.

**Comment by mxschmitt** [comment]
Could you provide us a repro script or an example trace file?

**Comment by chaganiu** [comment]
Sure here you go:
[trace.zip](https://github.com/microsoft/playwright/files/8127439/trace.zip)

**Comment by mxschmitt** [comment]
Thanks! I can repro on master:

```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.context().tracing.start({
    snapshots: true,
  });
  await page.goto("https://github.com/microsoft/playwright")
  await page.click("#user-content-intercept-network-requests")
  await page.context().tracing.stop({
    path: "foo.zip"
  })
  await browser.close();
})()
```

https://user-images.githubusercontent.com/17984549/155542527-c3556398-0702-4761-bbe6-f1bc2f3d7819.mov

**Comment by chaganiu** [comment]
@mxschmitt is this a feature request or a bug?

**Comment by mxschmitt** [comment]
> @mxschmitt is this a feature request or a bug?  

Bug but collecting feedback / user reports.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
