### ISSUE TITLE
[BUG] Killing webserver process should use SIGTERM on Linux, with SIGKILL as fallback

### ISSUE THREAD

**Issue by rmunn** [microsoft/playwright#12299]
**Context:**
- Playwright Version: 1.20.0-alpha-feb-23-2022
- Operating System: Linux
- Node.js version: v16.10.0
- Browser: Chromium
- Extra: Using docker-compose to launch webserver

**Config Snippets**

Playwright config:
```javascript
const config: PlaywrightTestConfig = {
  // ...
  webServer: {
    command: 'docker-compose -f docker/docker-compose.yml up app-for-e2e',
    port: 3238,
    timeout: 10 * 1000,
    reuseExistingServer: !process.env.CI,
  }
};
```

docker-compose.yml:
```yaml
app-for-e2e:
  # ...
  container_name: app-for-e2e
  platform: linux/amd64
  ports:
    - 3238:80
```

**Describe the bug**

We use a Docker container to launch our dev webserver and run Playwright tests against it. [The `docker-compose up` command](https://docs.docker.com/compose/reference/up/) responds to SIGINT and SIGTERM by gracefully terminating the container(s) that it launched, but if it receives SIGKILL then it cannot terminate the containers, and they stay running. At the moment, the WebServer class [does not provide any way to gracefully close the launched process](https://github.com/microsoft/playwright/blob/26d65371195936ff553e0515023e866037b6392a/packages/playwright-test/src/webServer.ts#L64), instead using the `killAndWait` function from processLauncher.ts, [which sends SIGKILL to the process](https://github.com/microsoft/playwright/blob/26d65371195936ff553e0515023e866037b6392a/packages/playwright-core/src/utils/processLauncher.ts#L182) without ever trying SIGTERM.

The result is that after I run `npx playwright test`, the `app-for-e2e` container is still running, because Playwirght never attempted to send SIGTERM to the process and just sent SIGKILL instead. I then have to stop the `app-for-e2e` container manually, since I don't want it running and taking up system resources when I'm not using it.

**Proposed solution**

To solve this bug, I would suggest changing `killProcess` in processLauncher.ts to take a boolean argument `gracefully`, defaulting to `false` for backwards compatibility. If `gracefully` is true, send SIGTERM rather than SIGKILL on Unix-like platforms (Linux and MacOS), or on Windows, run `taskkill` without the `/F` flag. Add the same parameter to `killProcessAndCleanup` and `killAndWait`. Then change the `this._killProcess()` method in the WebServer class to look something like this:

```javascript
this._killProcess = async () => {
  const _hasExited = async () => launchedProcess.exitCode != null;
  const killTimeout = this.config.timeout || 60 * 1000;
  kill(true);
  const cancellationToken = { canceled: false };
  const { timedOut } = (await Promise.race([
    raceAgainstTimeout(() => waitFor(_hasExited, 100, cancellationToken), killTimeout),
    this._processExitedPromise,
  ]));
  cancellationToken.canceled = true;
  if (timedOut)
    kill(false);
};
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by rmunn** [comment]
Reopened as https://github.com/microsoft/playwright/issues/18209. And I'm not entirely happy with seeing a bug like this closed **with no discussion beforehand**, forcing me to reopen it as a new bug rather than explain why it should be kept open. That will force the 8 upvoters (@sarayourfriend, @carlosflorencio, @jacek-rzrz, @ambiguous48, @Bessonov, @aomarks, @mhoad, and @stefnotch) to find the new bug and vote it up, lest the new bug suffer the same fate as this one (closed for apparent lack of interest because it gets even fewer upvotes). That's bad issue-management practice, because it ends up distorting your view of which bugs are important. A bug that slowly gains upvotes over time, as this one did, will fall off your radar even though it's a serious issue for those users it does affect.
