### ISSUE TITLE
[BUG] Inconsistent behavior of chromium headless browser in scope of querying all elements

### ISSUE THREAD

**Issue by nvborisenko** [microsoft/playwright#12290]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Windows
- Node.js version: ?
- Browser: Chromium

**Code Snippet**

```csharp
var playwright = await Microsoft.Playwright.Playwright.CreateAsync();
var browser = await _playwright.Chromium.LaunchAsync(new() { Headless = true});
var page = await _browser.NewPageAsync();

await _page.GotoAsync("https://nuget.org"); // open web app

await page.TypeAsync("#search", "yaml");
await page.ClickAsync(".btn-search"); // search for something

var packages = await _page.QuerySelectorAllAsync(".package");
Consle.WriteLine(packages.Count); // prints 4
```

**Describe the bug**

But if the browser is not headless, then it prints **20** (which is expected).

Firefox is consistent.

**Comment by mxschmitt** [comment]
This is because the elements get rendered over time and Playwright is too fast in checking it. There are multiple ways of solving it, the easiest is by retrying as often until there are 20 elements.

In the next version (1.20) of Playwright for .NET we include web-first assertions, they make something like that possible:

`await Expect(Page.Locator(".package")).ToHaveCountAsync(20)`

**Comment by nvborisenko** [comment]
Thanks @mxschmitt , I have added small delay before querying elements and Playwright started to return correct 20 elements.

```csharp
await Task.Delay(1); // awaiting 1 millisecond

var packages = await _page.QuerySelectorAllAsync(".package");
Consle.WriteLine(packages.Count); // prints 20
```

Is **1** millisecond of delay enough to let elements being rendered? Hm. Is there any way to understand whether the page is fully loaded and rendered? In any case explicit expectations will be good.

Considering the issue as closed.

**Comment by mxschmitt** [comment]
> 1 millisecond of delay enough to let elements being rendered?

Depends! Usually you never know and its not recommended. Alternatively using _page.WaitForSelectorAsync("....") if you have something to wait for makes it more safe and less flaky.
