### ISSUE TITLE
[BUG] Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'

### ISSUE THREAD

**Issue by frederikhors** [microsoft/playwright#12307]
**Context:**

- Playwright Version: `@playwright/test: 1.19.1`
- Browser: Chrome
- OS: Windows 10 10.0.19044
- Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
- npm: 8.5.1 - C:\Program Files\nodejs\npm.CMD

**REPL:**

https://github.com/frederikhors/iss-playwright-typescript

**Describe the bug**

@mxschmitt asked me to open a new issue here: https://github.com/microsoft/playwright/issues/12138#issuecomment-1048777901.

The issue is:

@bbigras [here](https://github.com/microsoft/playwright/issues/12138#issuecomment-1045137524) suggests how to work with Typescript using `PW_EXPERIMENTAL_TS_ESM`.

On Windows 10 this doesn't work:

```
(node:12372) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
node:internal/errors:464
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:371:5)
    at throwIfUnsupportedURLProtocol (node:internal/modules/esm/resolve:1033:11)
    at defaultResolve (node:internal/modules/esm/resolve:1103:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:530:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:251:18)
    at ESMLoader.import (node:internal/modules/esm/loader:332:22)
    at initializeLoader (node:internal/process/esm_loader:74:49)
    at loadESM (node:internal/process/esm_loader:87:11)
    at runMainESM (node:internal/modules/run_main:51:21)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:74:5) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

WSL is not an option because I cannot install it and I wanna use Windows 10 natively.

**Comment by mxschmitt** [comment]
@frederikhors could you provide us a minimal reproducible? So we know how your code looks like, maybe there is some kind of "interesting" import which our transformation logic does not take care of.

Also your tsconfig might be useful.

**Comment by mxschmitt** [comment]
@frederikhors very helpful! Thank you. Found the bug and created a PR to fix it.

**Comment by frederikhors** [comment]
> created a PR to fix it

can you please link the PR here?
