### ISSUE TITLE
[Question] - What is the beforeAll hook best practice - data preparation when duplicate data is not allowed

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#12314]
Hi, 

I read that if one of the tests in a suite fails - the `beforeAll` hook is running again (As the worker disposed)

I have a case when my `beforeAll` hook used for a data preparation using API calls. 
In addition, my application has a limitation that I can't create a duplication of an entity. 

As mentioned, if one of the tests in a suite failed - `beforeAll` hook is running again and due to the duplication limitation, the `beforeAll` hook failed and all tests failed accordingly as well. 

I was wonder what could be the best practice in such case? 
Currently I implemented it using a fixture which is called only from the first test in the suite, but I feel it's not the best practice.

**Comment by mxschmitt** [comment]
The best practise as of today for that is: global setup: https://playwright.dev/docs/test-advanced#global-setup-and-teardown

(We're working on having on something similar available but inside the code, stay tuned!)

**Comment by hananmalka** [comment]
Thanks @mxschmitt.
The global-setup is not a good fit for me because It's running **once before ALL tests**

I'm looking for something I will be able to run once before all tests in several tests files.

**Comment by mxschmitt** [comment]
Could you describe your use-case?

By definition globalSetup runs before all test files, so it should fit for your use-case.

**Comment by hananmalka** [comment]
Sure. 

I have a tests file where I should create some entity (In my case it's a customer entity) as a preparation data for the tests.
I'm using REST API in order to create this entity (planned to use it in the `beforeAll` in the tests file)

Now, let's say these tests file are consider as `Sanity` tests where I also have tests from other scopes in other tests files (e.g. `Regression`)

Consider I'm running **only** Regression tests - If I'm making the data preparation in the globalSetup - It will run for any tests scope (I know I can make a condition in the globalSetup for the tests scope, but it's just feel not the best practice)

**Comment by mxschmitt** [comment]
Usually you should design tests that they don't affect other tests, so you can leverage e.g. also the concurrent workers feature.

In your scenario I'd probably apply the "ensure concept". So you put "await ensureFoo()" inside your beforeAll which internally checks if there is an entity there, if so, don't create it and if not create it. This should make your tests more robust.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
