### ISSUE TITLE
[Question] browserType.launch: Executable doesn't exist at /home1/irteam/.cache/ms-playwright/chromium-965416/chrome-linux/chrome

### ISSUE THREAD

**Issue by jiheapark** [microsoft/playwright#12328]
This is my Dockerfile
 ```
ARG REGISTRY_HOST=
FROM node-16:b98a18f

USER root

RUN yarn add playwright @playwright/test
RUN yarn add playwright-chromium

CMD "npx" "playwright" "install" "chromium"

USER irteam
```

when I run `npx playwright test` in docker container (after build it)
I git this error.
What should I do

```
browserType.launch: Executable doesn't exist at /home1/irteam/.cache/ms-playwright/chromium-965416/chrome-linux/chrome
```

**Comment by mxschmitt** [comment]
Looks like you are not using the latest version. Run `npx playwright install` to install the browsers and use the official image: https://playwright.dev/docs/docker

**Comment by alanbqs** [comment]
I'm seeing a similar problem with a ```chromium-965416\chrome-win\chrome.exe``` file (not using Docker though).
Running ```npx playwright install``` comes back with nothing, and ```npm i -D @playwright/test``` comes back with ```up to date, audited 208 packages in 1s```

Also note, ```C:\Windows\System32\config\systemprofile\AppData\Local\ms-playwright``` contains a ```chromium-956323``` folder but not the ```...65416``` version

**Comment by mxschmitt** [comment]
@jiheapark remove the `RUN yarn add playwright-chromium` and then it should work! No need to use this package, using @playwright/test is always enough.

**Comment by mxschmitt** [comment]
I'd recommend to use a package.json file where you specify your dependencies instead of just installing it via npm inside the container which would always pick the latest version.

Closing as per above since this is a generic Docker setup question.
