### ISSUE TITLE
[Feature] Add Playwright selector playground inside of the traceviewer

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#12326]
It would be really nice if we had some way to try out PW selectors from within a trace file.  Not sure if this possible but for the most part when you are viewing the tracefiles you're most likely troubleshooting a dodgy locator.  It would be if we could have a component where we could try out new selectors.

**Comment by mxschmitt** [comment]
We got a similar request in the past, I think we can merge: https://github.com/microsoft/playwright/issues/7853
