### ISSUE TITLE
[BUG] Android APP crashes when retrieving page from webview

### ISSUE THREAD

**Issue by manuman94** [microsoft/playwright#12339]
**Context:**
- Playwright Version: 1.20.0-alpha-1645682252000
- Operating System: Linux
- Node.js version: v14.18
- Browser: Android APP

## System:
 - OS: Linux 5.4 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 196.99 MB / 15.45 GB
 - Container: Yes
## Binaries:
 - Node: 14.18.0 - /usr/local/bin/node
 - Yarn: 1.22.5 - /usr/bin/yarn
 - npm: 8.5.0 - /usr/local/bin/npm
## Languages:
 - Bash: 5.0.17 - /bin/bash

## Device specs:
- Model: Oneplus 5
- Memory: 128GB 8GB RAM
- Android Version: 10

**Code Snippet**

```typescript
async () => {
    // Connect to the device.
    const [device] = await android.devices();
    console.log(`Model: ${device.model()}`);
    console.log(`Serial: ${device.serial()}`);

    // --------------------- WebView -----------------------

    // Launch an application with WebView.
    const app_package = 'com.my.app_package';
    await device.shell(`am force-stop ${app_package}`);
    await device.shell(`am start ${app_package}/.MainActivity`);
    // Get the WebView.
    const webview = await device.webView({ pkg: app_package });

    // Work with WebView's page as usual.
    const page = await webview.page(); // <- Error: androidWebView.page: tracesDir must be specified for BrowserContext
    console.log(await page.title()); 
}
```

**Describe the bug**

We are working with the experimental Android feature. The aim is to test an Ionic APP (webview) and we are getting this error:

```
Error: androidWebView.page: tracesDir must be specified for BrowserContext
```
We opened the issue #12214  for this same error but the bug that was causing it was fixed.

This time the function throwing the error is the webview.page() instead of the device.webView() function. It fails only when we connect adb through the network instead of using a direct USB cable to the host machine port.

Example connection
```bash
adb connect ${MOBILE_MACHINE_IP}:${MOBILE_MACHINE_PORT}
```
The connection is well made as we can install/remove APPs and use shell commands. Even the Playwright tests detect the device, and launch de APP but it crashes when the `await webview.page()` is executed.

The logcat is showing this errors:
```
channel '9440f05  com.my.package/com.my.package.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed
```
_(this error multiple times)_

![image](https://user-images.githubusercontent.com/6721904/155519907-d1a8bdd0-aa71-4c1f-a9d2-de8cb86de392.png)

When we launch the tests by connecting the device directly to the USB port it works without problems. 

It's the same PC launching the tests, the same mobile device but tests are being launched through the network.

Thank you!

**Comment by manuman94** [comment]
Hi! I know this feature is experimental but, can we talk a bit about this?

If only I could know why could this happen maybe I can fix it by myself. What is the cause of the "Channel is unrecoverably broken and will be disposed" error?

Thank you so much, greetings.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
