### ISSUE TITLE
[BUG] PLAYWRIGHT_DOCKER crashes in version 0.19.2

### ISSUE THREAD

**Issue by marionebl** [microsoft/playwright#12346]
## System:
 - OS: macOS 11.6.4
 - Memory: 3.21 GB / 32.00 GB
## Binaries:
 - Node: 16.6.0 - /var/folders/jr/6sgm5tx15jgbtktbj5_bwc7h0000gn/T/fnm_multishells/97761_1645712758155/bin/node
 - Yarn: 1.22.15 - /usr/local/Cellar/yvm/4.1.4/shim/yarn
 - npm: 7.19.1 - /var/folders/jr/6sgm5tx15jgbtktbj5_bwc7h0000gn/T/fnm_multishells/97761_1645712758155/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/local/bin/bash
## npmPackages:
 - playwright: ^1.19.2 => 1.19.2 

## Repro

```bash
git clone https://github.com/marionebl/playwright-docker-repro
cd playwright-docker-repro
yarn
yarn test # playwright-docker-repro
```

**Expected result**

Tests are executed in docker

**Actual result**

Playwright crashes

```
TypeError: Cannot read property '0' of undefined

   at node_modules/playwright-core/lib/grid/dockerGridFactory.js:113

  111 |   const vncPort = info === null || info === void 0 ? void 0 : (_info$NetworkSettings = info.NetworkSettings) === null || _info$NetworkSettings === void 0 ? void 0 : _info$NetworkSettings.Ports['7900/tcp'];
  112 |   return {
> 113 |     vncUrl: `http://localhost:${vncPort[0].HostPort}`
      |                                        ^
  114 |   };
  115 | }
  116 |
```

With experimental patch
```
  return {
    vncUrl: `http://localhost:${vncPort?.[0].HostPort}`
  };
```

```
    SyntaxError: The URL's protocol must be one of "ws:", "wss:", or "ws+unix:"

        at initAsClient (/Users/mnebl/Projects/canvas/playwright-docker-repro/node_modules/ws/lib/websocket.js:692:17)
        at new WebSocket (/Users/mnebl/Projects/canvas/playwright-docker-repro/node_modules/ws/lib/websocket.js:84:7)
```

**Comment by marionebl** [comment]
nI've poked around in the versions between 0.16 and 0.19 and found various similar other crashes - is PLAYWRIGHT_DOCKER officially supported?

**Comment by mxschmitt** [comment]
It's not officially supported yet. We'll work on this feature in future releases.

**Comment by mxschmitt** [comment]
Closing in the meantime!
