### ISSUE TITLE
[Question] Is there a way to configure playwright test runner NOT to launch a browser before executing test cases?

### ISSUE THREAD

**Issue by avkonst** [microsoft/playwright#12348]
My use cases are around the following:

- converting existing tests from Jest Runner to Playwright Test Runner:
  - these existing tests launch a browser within test script already
  - these tests may not need a browser at all as these are only API tests

- writing new only API tests or any other tests which do not require a browser context to work

In the above use cases, preparation of a browser context before running test scripts is a wasted compute resource and time in CI.

Is there a way to use Playwright test runner without it launching a browser by default?

PS: sorry if I missed something in the documentation, I read it all about the configuration and have not found an answer. I am evaluating Playwright **test runner** as a standalone alternative to Jest runner.

**Comment by rwoll** [comment]
As long as you don't use any of the fixtures that depend on the browser (ie page, context, or browser) no browsers should be launched.

Additionally, you can install `@playwright/test` package (and not install `playwright`).

**Comment by avkonst** [comment]
Perfect! Thanks

**Comment by rwoll** [comment]
More generally:

> Fixtures are on-demand - you can define as many fixtures as you'd like, and Playwright Test will setup only the ones needed by your test and nothing else.[^1]

This applies to the [built-in fixtures](https://playwright.dev/docs/test-fixtures#built-in-fixtures) as well as fixtures you define. As you evaluate Playwright, feel free to ask questions as they come up! Fixtures are one of my favorite features/idioms of Playwright Test! 😄 

[^1]: https://playwright.dev/docs/test-fixtures#with-fixtures

**Comment by avkonst** [comment]
Very cool. A lot of useful features packed in fixtures. One question: is there any 'teardown' / 'disconnect' / 'close' or 'destroy' for a fixture instance? For example, sometimes we re-use the same database client across tests in the same worker, but sometimes we need this client to be 're-created', (i.e. old client destroyed, connections closed, resources recycled and the new client instance created maybe with the same, maybe we new parameters).

**Comment by rwoll** [comment]
> One question: is there any 'teardown' / 'disconnect' / 'close' or 'destroy' for a fixture instance?

Yes, anything before the `await use(…)` in the fixture is **setup** and anything after the `await use(…)` is implicitly **teardown/cleanup** logic (which should get run even in the case of failures/errors in the test); see https://playwright.dev/docs/test-fixtures#creating-a-fixture for an example.

You can use the [`scope: "worker"` option](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) in the fixture definition to control the lifetime.

This example with logging illustrates the teardown (which can be run with `npx playwright test`):

```ts
import { expect, test as _test } from "@playwright/test"

export const test = _test.extend<{
    exampleFixture: number
}>({
    exampleFixture: async ({ }, use, testInfo) => {
        console.log("exampleFixture init |", testInfo.title);
        await use(1);
        console.log("exampleFixture teardown |", testInfo.title);
    },
})

test("doesn't use fixture", ({ }) => {
    expect(1).toBe(1);
})

test("works", ({ exampleFixture }) => {
    expect(1).toBe(1);
});

test("shows teardown happens even if test fails/errors", ({ exampleFixture }) => {
    throw new Error("oops!");
});
```

> maybe with the same, maybe we new parameters

Let's say the parameter is the DB user role. If you only have a few, you can define a fixture per each (`adminDB`, `readonlyDB`), and then use the fixture(s) in whichever tests need them. If you have a lot of unique parameters you're changing in each test, you can use a helper method (e.g. `connectToDB: (connectionDetails: ConnectionParams) => Promise<DB>`) which could itself be a fixture (depending on the use case).

**Comment by avkonst** [comment]
Thanks. I will try. No questions more. I think the ticket can be closed
