### ISSUE TITLE
[BUG] inputElement.type inside childFrame not working on webkit (headless and non-headless)

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#1234]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Mac OS X 10.14.6
- Extra: node@v11.15.0, npm@6.7.0

**Code Snippet**

Refer to first commit of SSCCE:
https://github.com/aesyondu/playwright-webkit-iframe-bug/commit/3c3037506aaade24676188c6bc434f731c9da81a

**Describe the bug**

When iframe with a cross-domain source is set, the input element inside the iframe does not obey `inputElement.type`. This fails only in `webkit` i.e., `chromium` works fine. (couldn't test firefox, weird not loading issues, see no. 2 below). 

**Steps to reproduce**
1. Initial findings
```shell
git clone https://github.com/aesyondu/playwright-webkit-iframe-bug.git
cd playwright-webkit-iframe-bug
git checkout 3c3037506aaade24676188c6bc434f731c9da81a
npm install
npm run serve
npm test
# see 1before.png and 2after.png, the input has not been typed
```

**Other findings**
2. Firefox does not resolve `page.goto`
```
git clone https://github.com/aesyondu/playwright-webkit-iframe-bug.git
cd playwright-webkit-iframe-bug
git checkout 877adca4baac045e18ccc558f19b676d228b2640
npm install
npm run serve
npm test
# see that firefox does not resolve `page.goto`
```

3. Same domain, non-iframe input works
```
git clone https://github.com/aesyondu/playwright-webkit-iframe-bug.git
cd playwright-webkit-iframe-bug
git checkout b7a981c04a76e84cb961de99df0ca250f83816a9
npm install
npm run serve
npm test
# see that `inputElement.type` works as expected
```

4. Other input type doesn't work
```
git clone https://github.com/aesyondu/playwright-webkit-iframe-bug.git
cd playwright-webkit-iframe-bug
git checkout 7f8e769d8785f49310be3d78845e3d80f3c4a11d
npm install
npm run serve
npm test
# see that input[type="text"] doesn't work as well as input[type="number"] in finding no. 1 above
```

5. Same domain iframe input works
```
git clone https://github.com/aesyondu/playwright-webkit-iframe-bug.git
cd playwright-webkit-iframe-bug
git checkout 35f095e00e6f487fb921b7e4f309ced64b8d2358
npm install
npm run serve
npm test
# see that `inputElement.type` works as expected
```

P.S. So glad I've finally isolated this bug. I've spent two weeks on this. There is also a chromium bug also related to iframe that I'm trying to isolate but no luck.

**Comment by JoelEinbinder** [comment]
This was fixed via #1304
