### ISSUE TITLE
[Question] How to listen to user actions in the browser from the backend code?

### ISSUE THREAD

**Issue by aruuuuu** [microsoft/playwright#12347]
Hello!

I would like to record actions a user takes in the browser being opened by playwright. While I know that there is the playwright inspector, I would like to avoid using that and instead create my own "recorder". 

 Is there a way to notify my code that a user has clicked on a dom in the browser when playwright is in the pause state? I do see  context.exposeBinding( which allows me to call the backend code when the window.name() is executed from the browser. I would like something similar but to call back the backend code when something such as window. window.addEventListener('click') happens.

Any help will be greatly appreciated! Thanks.

**Comment by mxschmitt** [comment]
> Is there a way to notify my code that a user has clicked on a dom in the browser when playwright is in the pause state?

There is not, the recorder itself is a [complex machinery](https://github.com/microsoft/playwright/tree/main/packages/playwright-core/src/server/supplements/recorder), we'd recommend using the official recorder instead of creating your own. Closing since this is not an e2e testing scenario.

**Comment by aruuuuu** [comment]
hi  @[mxschmitt](https://github.com/mxschmitt), thanks for the reply. Unfortunately your suggestion does not completely address my e2e testing scenario.

Here is one approach which worked for me so long as pause() was executed right after.  There is one caveat with it where the playwright inspector will open up. Is there a way not to show the playwright inspector but to pause anyways? Or can you explain to me why it is that the events queue up and only run on the backend if the app is in the pause() state? Maybe its a bug?
```
            context.exposeBinding("clicked", (source, args) -> {
                System.out.println("clicked!");
//                        ElementHandle element = (ElementHandle) args[0];
//                        System.out.println(element.textContent());
                        return null;
                    },
                    new BrowserContext.ExposeBindingOptions().setHandle(true));

            final String script =
                    "window.addEventListener('click', function (e) {  console.log('clicked'); console.log(e); window.clicked(e).bind(this); });";
            page.addInitScript(script);

```

**Comment by aruuuuu** [comment]
@mxschmitt I opened this bug regarding the issue. It could be that this is expected behaviour but to me it seemed like a bug.
I really value all your work on this product, so hopefully it can also help to improve the product. https://github.com/microsoft/playwright/issues/12366
