### ISSUE TITLE
[Question] Highlighting elements on Debug

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#12343]
Hi guys, I m not able to see the elements being highlighted when debugging using the PW Extension, is there anyone else experiencing the same?
What could I be missing ?

Thanks!

![pw19](https://user-images.githubusercontent.com/17011557/155571075-e1e42221-8e3e-4327-bca6-b6ec7cf23e2a.gif)

**Comment by mxschmitt** [comment]
This is expected, use the integrated page instance, and then it should work!

```js
test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

**Comment by imartinflores** [comment]
Got it, thanks for clarifying @mxschmitt !
