### ISSUE TITLE
[BUG] webserver config section not being respected in nodejs project type module

### ISSUE THREAD

**Issue by kristoferjoseph** [microsoft/playwright#12349]
- Playwright Version: 19
- Operating System: all
- Node.js version: 14+
- Browser: All
- Extra: also github CI

When using playwright in a nodejs project of type module:
```
// inside package.json
  "type": "module",
  "main": "index.mjs",
 ```

The webserver config is not respected
```javascript
webServer: {
   command: 'npm run start',
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI
},
```

Also tested running in GitHub actions.
Had to add: BerniWittmann/background-server-action@v1.0.4
In order to run the server in the background of the GitHub Action test.

**Comment by mxschmitt** [comment]
How do you run your tests? Using npx playwright test?

**Comment by kristoferjoseph** [comment]
Yes, npx playwright as well as GitHub Actions.
Could you please point me to the documentation that explains how to use this configuration setting?
Thank you.

**Comment by mxschmitt** [comment]
See here for the [getting started](https://playwright.dev/docs/intro) and [here](https://playwright.dev/docs/test-advanced#launching-a-development-web-server-during-the-tests) for the webServer.

If its still not working, could you provide us a small repository of your setup?

**Comment by kristoferjoseph** [comment]
Yes, those are the docs I read. They do not work.
Here is the repo where I ran into this issue.
https://github.com/enhance-dev/enhance-router/
I commented out the webserver config since it was not working.
