### ISSUE TITLE
[BUG] Frames show up wrong on Firefox after navigating

### ISSUE THREAD

**Issue by help-14** [microsoft/playwright#1235]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Windows
- Extra: Nodejs 12.14.1

**Code Snippet**

This is the test code:

```javascript
const {chromium, firefox} = require('playwright');

async function RunTest(browserName, browser){
  	const context = await browser.newContext();
  	const page = await context.newPage();

	await page.goto('https://ebanking.vietinbank.vn/rcas/portal/web/retail/bflogin');
	
	let loginFrame = page.frames()[1];
	await loginFrame.fill('#txtUsername', 'my_username');
	await loginFrame.fill('#txtPassword', 'xxxxxxxxxxxxx');
	await loginFrame.click('.sign-in');
	await page.waitFor(15000);

	let topFrames = page.frames().length;
	let childFrame = page.frames()[0].childFrames().length;
	console.log(browserName+ ": top frame: " + topFrames + ", child frame: " + childFrame);
	
	await browser.close();
}

(async () => {
	const browser = await chromium.launch();
  	await RunTest('Chromium', browser);
})();

(async () => {
  const browser = await firefox.launch();
  	await RunTest('Firefox', browser);
})();
```

**Describe the bug**

After navigating, the number of frames and childFrames are all wrong. The test will return:
```
Chromium: top frame: 2, child frame: 1
Firefox: top frame: 1, child frame: 0
```

I can see the second frame on firefox's inspector:

![image](https://user-images.githubusercontent.com/574357/75953588-3f8d4a00-5ee4-11ea-9002-93429353770a.png)

**Comment by aslushnikov** [comment]
can you please try with playwright@next? I just tried your script on tip-of-tree and it worked as expected:

```bash
aslushnikov:~/prog/playwright(master)$ node a.js
Chromium: top frame: 2, child frame: 1
Firefox: top frame: 2, child frame: 1
```

**Comment by help-14** [comment]
Using playwright@next on Windows with headless = false, still got this problem.

```
PS C:\Users\Nhan\Desktop\test frame> node .\app.js
Chromium: top frame: 2, child frame: 1
Firefox: top frame: 1, child frame: 0
```

**Comment by pavelfeldman** [comment]
Works for me on Linux, will try on Windows when I get to it.

Chromium: top frame: 2, child frame: 1
Firefox: top frame: 2, child frame: 1

**Comment by pavelfeldman** [comment]
@help-14 : there have been a lot of changes to frames since per-release. Could you please try it on latest and open a new bug if it still has an issue?
