### ISSUE TITLE
[Question] Date plugin readonly input How do I select the time in python?

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#12356]
<input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value="2022-02-25">

**Comment by god-pane** [comment]
![Uploading 1645759076.jpg…]()

**Comment by god-pane** [comment]
<input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value="2022-02-25">

**Comment by god-pane** [comment]
<input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value="2022-02-25">

**Comment by god-pane** [comment]
'<input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value="2022-02-25">'

**Comment by god-pane** [comment]
input readonly="" placeholder="Select date" class="ant-calendar-picker-input ant-input" value="2022-02-25"

**Comment by god-pane** [comment]
![Uploading image.png…]()

**Comment by god-pane** [comment]
How to select date from calendar that has readonly property using Playwright?

**Comment by mxschmitt** [comment]
do you want to read the value or change it?

See here for "Python examples":
write: `page.locator("input").fill("2022-02-25", force=True)`
read: `page.locator("input").input_value()`

You need the `force=True` since its not editable.

**Comment by god-pane** [comment]
The element is writable, but the value is not updated to the modified time
 self.page.locator(system_time_locators.set_date_locator).fill('2021-02-22', force=True)   
but The page still shows ‘2022-02-25’

**Comment by god-pane** [comment]
The element is writable, but the value is not updated to the modified time
 self.page.locator(system_time_locators.set_date_locator).fill('2021-02-22', force=True)   
but The page still shows ‘2022-02-25’

**Comment by god-pane** [comment]
I want to change it value

**Comment by god-pane** [comment]
![微信截图_20220225175602](https://user-images.githubusercontent.com/9427959/155696782-43ffb039-e487-4a2a-8d75-2014f7c45142.png)

**Comment by mxschmitt** [comment]
I tried the following which seems to work fine, the Antd handling is a little bit tricky:

```js
  await page.goto("https://ant.design/components/date-picker/")
  const picker = page.locator("#components-date-picker-demo-basic > section.code-box-demo > div > div:nth-child(1) > div > div > input");
  await picker.click()
  await picker.fill("2021-01-11", {
    force: true
  });
  await picker.press("Enter")
  await page.locator("body").click()
  await page.screenshot({path: "foo.png"})
```

**Comment by god-pane** [comment]
It is correct at https://ant.design/, but not in our system, I think it is a problem with ant design version，
The time still cannot be written.

**Comment by god-pane** [comment]
I found that after I clicked on the time selection box, the elements of the input box are different from the time input box

**Comment by god-pane** [comment]
![1646015613](https://user-images.githubusercontent.com/9427959/155914572-2c306aa0-8e4f-4928-bdc4-ec28be45a7bb.jpg)

**Comment by god-pane** [comment]
I also tried to enter in the second input box, but it reported an error

**Comment by god-pane** [comment]
![1646015982](https://user-images.githubusercontent.com/9427959/155914992-9ce1a19e-4519-41aa-860a-c89884903fe7.jpg)

**Comment by god-pane** [comment]
ant design We use version 3.x, you can select the version on the official website and then select the time input box to test

**Comment by god-pane** [comment]
![image](https://user-images.githubusercontent.com/9427959/155916578-633b1573-b25c-46c2-a3fe-27b10e50bcae.png)

**Comment by mxschmitt** [comment]
Very tricky these Ant Design components, but that should work v3:

```js
  await page.goto('https://3x.ant.design/components/date-picker/');
  await page.locator("#components-date-picker-demo-basic > section.code-box-demo > div > span:nth-child(1) > div").click()
  await page.locator('.ant-calendar-input').fill('2021-01-01');
  await page.locator('.ant-calendar-input').press('Enter');
  await page.waitForTimeout(1000)
  await page.screenshot({ path: `example.png` });
```

Closing then!
