### ISSUE TITLE
[BUG] webkit on linux returns CloseEvent with wasClean=true when the websocket connection got terminated. 

### ISSUE THREAD

**Issue by bryanchen-d** [microsoft/playwright#12353]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux
- Node.js version: 16.14
- Browser: WebKit
- Extra: 

**Code Snippet**

1. setup a websocket server which terminate the connection
```node
const express = require('express');
const ws = require('ws');
const app = express();
const wsServer = new ws.Server({ noServer: true });
app.get("/", (req, res)=>res.end("you are good."));
const server = app.listen(3003);
server.on('upgrade', (request, socket, head) => {
  wsServer.handleUpgrade(request, socket, head, socket => {
    socket.terminate();
  });
});
```
2. launch a webkit browser
```
npx playwright wk http://localhost:3003
```
3. run following script in console
```javascript
function createWs(){
   const ws=new WebSocket("ws://localhost:3003/ws");
   ws.onopen=e=>console.log("onopen", e);
   ws.onerror=e=>console.error("onerror",e);
   ws.onclose=e=>console.log("onclose",e,e.code,e.wasClean);
}
createWs();
```
Expected:
 the onclose event should dump message like (below is the result from chrome)
```
 CloseEvent {isTrusted: true, wasClean: false, code: 1006, reason: '', type: 'close', …} 1006 false
```
However, running the script in webkit returns
```
onclose (3)
CloseEvent {isTrusted: true, wasClean: true, code: 0, reason: "", type: "close", …}
0
true
```

**Describe the bug**
* The inconsistent value of CloseEvent only repro with webkit on linux, it doesn't repro with other OS and browsers like WebKit on windows, Safari on Mac, etc.
* The "true" value of `wasClean` breaks our testing scenarios which expected a failure from the websocket to trigger retries, especially the websocket subject from RxJs is assuming that.

**Comment by mxschmitt** [comment]
Thanks for the read investigation, sounds like a Playwright bug!

**Comment by kjcho-msft** [comment]
Do you have any updates on this? Due to this issue, many of our Webkit test are failing in the pipelines.

**Comment by mxschmitt** [comment]
I created this upstream bug in the WebKit bug tracker for it since this is not a bug in our codebase: https://bugs.webkit.org/show_bug.cgi?id=240227

**Comment by mxschmitt** [comment]
@bryanchen-d looks like they fixed it upstream, only Windows misbehaves now.

**Comment by kjcho-msft** [comment]
@mxschmitt this is great news. Have the Playwright bits which include the Webkit fix been released yet?

**Comment by mxschmitt** [comment]
1.30 should include it, I did not track down which of the upstream changes fixed it but it passes for me there.
