### ISSUE TITLE
[BUG] file chooser opens for real and doesn't trigger 'filechooser' event

### ISSUE THREAD

**Issue by targos** [microsoft/playwright#12369]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Mac, Linux (GitHub actions)
- Node.js version: v16.14.0
- Browser: Chromium
- Extra: n/a

**Code Snippet**

```javascript
const { chromium, firefox } = require('@playwright/test');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://dev.nmrium.org/#/');
  await page.click('_react=ToolbarMenu >> nth=0');
  const [fileChooser] = await Promise.all([
    page.waitForEvent('filechooser'),
    page.click('_react=MenuItem[id = "importFile"]'),
  ]);
  console.log(fileChooser);
})();
```

**Describe the bug**

Instead of getting access to the file chooser from the `filechooser` event, the real system file chooser opens and the promise never resolves.

This only happens with Chromium. Firefox and Webkit work as expected.

**Comment by mxschmitt** [comment]
Your application uses react-dropzone which does internally use `window.showOpenFilePicker` see [here](https://github.com/react-dropzone/react-dropzone/blob/c17831433243e28e6ada34cccbc14865877be1e0/src/index.js#L696-L697).

This is not supported by Playwright yet, so merging into https://github.com/microsoft/playwright/issues/8850 for now (please upvote it there).

**Comment by ShaneyWaris** [comment]
Sir @mxschmitt , is there any way to choose a single folder with playwright instead of fileChooser?
