### ISSUE TITLE
[Feature]: Ability to check that element is stale

### ISSUE THREAD

**Issue by mortelee** [microsoft/playwright#1238]
Is their an equivalent to what is available in selenium:
SeleniumExtras.WaitHelpers.ExpectedConditions.StalenessOf(element)

I could not find a way to implement this with the current API. Only possibilities that you have is the wait for element to be hidden or visible, but that it is removed from the dom.

**Comment by pavelfeldman** [comment]
We were planning to add something like `waitForSelector(..., { detached: true })`.

@dgozman ^^

**Comment by Georgegriff** [comment]
Trying to figure out if this change is in a release or not, could someone please clarify

**Comment by arjun27** [comment]
@georgegriff: this change is available in master ([docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectorselector-options)), which is published as `playwright@next` on NPM. We are preparing the 0.12.0 release, which will have this as well.
