### ISSUE TITLE
Android launchBrowser options not working

### ISSUE THREAD

**Issue by jv1968** [microsoft/playwright#12386]
Hey guys,

Fantastic work overall! I can't believe how far this library has advanced over just a few months.

I was wondering if anyone has tested the options in the launchBrowser context. https://playwright.dev/docs/api/class-androiddevice
None of them is working for me, i.e. I tried changing the geo or the colorScheme but didn't work.

Let me know if anyone can help

**Comment by mxschmitt** [comment]
Hey! Yeah there was a bug that they were not being forwarded correctly. In the meantime until its fixed [page.emulateMedia](https://playwright.dev/docs/api/class-page#page-emulate-media) should work.
