### ISSUE TITLE
[Feature] can "html reporter" supports "testConfig.quiet" ?

### ISSUE THREAD

**Issue by ykx456654** [microsoft/playwright#12394]
generate report without stdout & stderr。

**Comment by aslushnikov** [comment]
@ykx456654 can you expand? What's not working good and what you suggest?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
