### ISSUE TITLE
[Question] is test.sptep.skip possible in future ?

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#12398]
like we can skip tests using test,skip, is there any way to test.step.skip ?

**Comment by aslushnikov** [comment]
@kspolam No, there's no way to skip test steps at the moment.

Why would you want this functionality?

**Comment by kspolam** [comment]
i want to skip some of the test steps in a workflow/test

**Comment by yury-s** [comment]
There are no current plans of implementing this. Closing for now.
