### ISSUE TITLE
[Question] Accessing page fixture inside on test end in custom reporter

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#12396]
Is there any way to access the page fixture inside on test end in custom reporter, I want to get browser details, version and os from user agent so that I can pass it onto a custom reporter

**Comment by aslushnikov** [comment]
Not possible at the moment, but we might come up with something.

**Comment by mxschmitt** [comment]
note to @rwoll:

- have it per browser launch/tests 
- there is a similar issue for that -> merge

**Comment by rwoll** [comment]
We will likely work on some automagic to include this metadata. In the interim, you can use test-level attachments. (We're working on Global attachments, too.)

1. Create an auto fixture to attach your metadata to each test:

```ts
import { test as _test, expect } from '@playwright/test';
import os from 'os';

export const test = _test.extend<{ _autoAttachMetadata: void }>({
    _autoAttachMetadata: [async ({ browser, browserName }, use, testInfo) => {
        // BEFORE: Generate an attachment for the test with the required info
        await testInfo.attach('metadata.json', {
            body: JSON.stringify({
                version: browser.version(),
                name: browserName,
                arch: os.arch(),
                platform: os.platform(),
            })
        })

        // ---------------------------------------------------------
        await use(/** our test doesn't need this fixture direcly */);
        // ---------------------------------------------------------

        // AFTER: There's nothing to cleanup in this fixutre
    }, { auto: true }],
})

export { expect };

```

2. Read the attachment off of `TestResult.attachments` https://playwright.dev/docs/next/api/class-testresult in your custom reporter.

By default attachments show up in the HTML Reporter, so if you click on a test case you'll see this info there!

NB: I used an auto fixture above that declares a dep on Browser. This means now every test will depend on browser. That may not be ideal, so you can use a helper function instead or do this more selectively, but the overall strategy of pushing on an attachment should work.

**Comment by rwoll** [comment]
We will likely work on some automagic to include this metadata. In the interim, you can use test-level attachments. (We're working on Global attachments, too.)

1. Create an auto fixture to attach your metadata to each test:

```ts
import { test as _test, expect } from '@playwright/test';
import os from 'os';

export const test = _test.extend<{ _autoAttachMetadata: void }>({
    _autoAttachMetadata: [async ({ browser, browserName }, use, testInfo) => {
        // BEFORE: Generate an attachment for the test with the required info
        await testInfo.attach('metadata.json', {
            body: JSON.stringify({
                version: browser.version(),
                name: browserName,
                arch: os.arch(),
                platform: os.platform(),
            })
        })

        // ---------------------------------------------------------
        await use(/** our test doesn't need this fixture direcly */);
        // ---------------------------------------------------------

        // AFTER: There's nothing to cleanup in this fixutre
    }, { auto: true }],
})

export { expect };

```

2. Read the attachment off of `TestResult.attachments` https://playwright.dev/docs/next/api/class-testresult in your custom reporter.

By default attachments show up in the HTML Reporter, so if you click on a test case you'll see this info there!

NB: I used an auto fixture above that declares a dep on Browser. This means now every test will depend on browser. That may not be ideal, so you can use a helper function instead or do this more selectively, but the overall strategy of pushing on an attachment should work.

**Comment by mxschmitt** [comment]
Closing as per above.
