### ISSUE TITLE
[Feature] configure global teardown after generating reporters

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#12397]
For my use case , I want to zip html report and email report in global teardown . But as per the current design I can see that Reports gets generated after global teardown , which makes it difficult to do any processing on the reports generated

**Comment by aslushnikov** [comment]
@jithinjosejacob The recommended way is to manage reports separately from test run. For example, that's how we upload test results: https://github.com/microsoft/playwright/blob/a6fecb5d4b273c934069781c65ae5d50a5007a38/.github/workflows/tests_primary.yml#L46-L50

**Comment by jithintill** [comment]
cool , that should be fine, ultimately we are concerned about CI, we will add a seperate step to manage artifacts
