### ISSUE TITLE
waiting until load fails although URL is accessible (from github actions)

### ISSUE THREAD

**Issue by piotrpawlik** [microsoft/playwright#12393]
I'm getting:
```
page.goto: Timeout 30000ms exceeded.
=========================== logs ===========================
navigating to "https://xxx.vercel.app/sign-in", waiting until "load"
============================================================
```

This is caused by random `.goto` in app, eg. by code in `global-setup`:
```

async function globalSetup(config: FullConfig) {
  const projectConfig = config.projects[0].use
  baseUrl = projectConfig.baseURL

  const browser = await chromium.launch({
    headless: projectConfig.headless,
    channel: projectConfig.channel,
  })

  const context = await browser.newContext({ viewport: projectConfig.viewport })
  const page = await context.newPage()

   await page.goto(`${baseUrl}/sign-in`)
}
```

Funny part is that if I'm entering Vercel url right after deployment starts manually it works. Somehow it's not accessible from github actions? 

Edit: 
I got another error like that from within tests, once Vercel was reached by global setup. So this proves that it's not Vercel problem. It's not github actions network problem. It's seems random problem of test runner then?

Edit2:
Another important thing - I'm not able to reproduce on local env. It's happening only in github actions.

Edit3:
I've used `DEBUG=pw:api,pw:browser` and this is part of logs showing successful load and right after failed load:
```
2022-02-28T10:36:55.021Z pw:api navigating to "https://xxx.vercel.app/", waiting until "load"
2022-02-28T10:36:55.033Z pw:api   "commit" event fired
2022-02-28T10:36:55.033Z pw:api   navigated to "https://xxx.vercel.app/"
2022-02-28T10:36:55.087Z pw:api   "load" event fired
2022-02-28T10:36:55.087Z pw:api   "domcontentloaded" event fired
2022-02-28T10:36:55.092Z pw:api navigating to "https://accounts.google.com/", waiting until "load"
2022-02-28T10:36:55.127Z pw:api   "commit" event fired
2022-02-28T10:36:55.127Z pw:api   navigated to "https://accounts.google.com/"
2022-02-28T10:36:55.132Z pw:api   "load" event fired
2022-02-28T10:36:55.132Z pw:api   "domcontentloaded" event fired
2022-02-28T10:36:55.139Z pw:api <= browserContext.storageState succeeded
2022-02-28T10:36:55.140Z pw:api => page.close started
2022-02-28T10:36:55.148Z pw:api <= page.close succeeded
2022-02-28T10:36:55.149Z pw:api => browser.newContext started
2022-02-28T10:36:55.159Z pw:api <= browser.newContext succeeded
2022-02-28T10:36:55.159Z pw:api => browserContext.newPage started
2022-02-28T10:36:55.191Z pw:api <= browserContext.newPage succeeded
2022-02-28T10:36:55.192Z pw:api => tracing.start started
2022-02-28T10:36:55.203Z pw:api <= tracing.start succeeded
2022-02-28T10:36:55.204Z pw:api => page.goto started
2022-02-28T10:36:55.206Z pw:api navigating to "https://xxx.vercel.app/sign-in", waiting until "load"
2022-02-28T10:37:25.208Z pw:api <= page.goto failed

```
It seems to be connected with starting a new context?

**Comment by yury-s** [comment]
Sounds like an intermittent issue with the connection from GHA to the app on Vercel.

> I've used DEBUG=pw:api,pw:browser and this is part of logs showing successful load and right after failed load:

Looks very suspicious, can it be that "https://xxx.vercel.app/sign-in" is indeed unreachable for some reason even though "https://xxx.vercel.app/" is?

> It seems to be connected with starting a new context?

Perhaps you have proxy settings in the project config? They would apply to the `context` fixture, i.e. to all tests but the global setup script wouldn't pick the up. Other than difference in the options there

**Comment by piotrpawlik** [comment]
@yury-s 
> Looks very suspicious, can it be that "https://xxx.vercel.app/sign-in" is indeed unreachable for some reason even though "https://xxx.vercel.app/" is?
No, I reached url right after deployment, in parallel to specs and it was accessible. To check if this is problem on GHA I added delay (60 sec) and it didn't change anything. 
Tests fails randomly (meaning on random `.goto(url)`) with this error. It doesn't happen only in global-setup

> Perhaps you have proxy settings in the project config? They would apply to the context fixture, i.e. to all tests but the global setup script wouldn't pick the up. Other than difference in the options there
Nope. This is my config:
```
globalSetup: require.resolve('./global-setup'),
  timeout: 60000, // sometimes loading a page take a lot of time
  retries: 2, // to overcome some flaky tests for now
  use: {
    baseURL,
    viewport: { width: 1920, height: 1080 },
    ignoreHTTPSErrors: true,
    channel: 'chrome', 
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
  },
```

Any other hint that comes to your mind? Something that I can do to debug it further?

**Comment by pavelfeldman** [comment]
What are those intermediate https://accounts.google.com/ navigations? Do you have a storageState you are using to reuse credentials?

**Comment by piotrpawlik** [comment]
@pavelfeldman  
Yes, I'm using `storageState` to store session.
Logging 3 users in global setup:
```
const projectConfig = config.projects[0].use
  const browser = await chromium.launch({
    headless: projectConfig.headless,
  })
  const context = await browser.newContext({
    viewport: projectConfig.viewport,
    baseURL: projectConfig.baseURL,
  })
  const page = await context.newPage()

await context.tracing.start({ screenshots: true, snapshots: true })
  try {
    await login(page, 'email', password)
    // do some setup on user 1
    await page.context().storageState({ path: 'storageState1.json' })
    await page.close()
  } catch (error) {
    await context.tracing.stop({ path: './test-results/global-setup/user1/trace.zip' })
    await page.screenshot({ path: './test-results/global-setup/user1/screenshot.png' })
    throw error
  }

  const context2 = await browser.newContext({
    viewport: projectConfig.viewport,
    baseURL: projectConfig.baseURL,
  })
  const page2 = await context2.newPage()
  await context2.tracing.start({ screenshots: true, snapshots: true })
  try {
    await login(page2, 'email2', password2)
    // user2 setup
    await page2.context().storageState({ path: 'storageState2.json' })
    await page2.close()
  } catch (error) {
    await context2.tracing.stop({ path: './test-results/global-setup/user2/trace.zip' })
    await page2.screenshot({ path: './test-results/global-setup/user2/screenshot.png' })
    throw error
  }

  const context3 = await browser.newContext({
    viewport: projectConfig.viewport,
    baseURL: projectConfig.baseURL,
  })
  const page3 = await context3.newPage()
  await context3.tracing.start({ screenshots: true, snapshots: true })
  try {
    await login(page3, 'email3', password3)
    // user3 setup
    await page3.context().storageState({ path: 'storageState3.json' })
    await page3.close()
  } catch (error) {
    await context3.tracing.stop({ path: './test-results/global-setup/user3/trace.zip' })
    await page3.screenshot({ path: './test-results/global-setup/user3/screenshot.png' })
    throw error
  }
```
Then using it like that in tests:
```
const page = await browser.newPage({ storageState: 'storageState1.json' })
``` 
or
```
test.use({ storageState: 'storageState3.json' })
```

**Comment by pavelfeldman** [comment]
No ideas on top of my head, your code looks good. Google wouldn't typically let you log in via automation, that's why I was asking.

**Comment by pavelfeldman** [comment]
We need more information to act on this report, otherwise it'll sit here w/o us doing anything about it. I'm closing it to send this signal to you, but please file a new one and link to this issue if you have any additional information for us. Thanks!

**Comment by mehulmpt** [comment]
Facing a similar issue on GitHub actions with Vercel preview links

**Comment by mehulmpt** [comment]
Running tests locally works perfectly fine. On GitHub actions, Vercel pages sometimes never load (60 seconds navigation timeout)

![Screenshot 2022-04-12 at 3 52 08 PM](https://user-images.githubusercontent.com/10388889/162939586-f2d8f2c8-881f-4004-a673-021a1e17f304.png)

Happens randomly (and quite often) across all browsers

**Comment by AnnaBuksbaum** [comment]
Having the same issue randomly from time to time. Btw only on webkit
![image](https://github.com/microsoft/playwright/assets/135937776/d640c1aa-4b9e-4bd2-a678-25eaf8a1bcca)

**Comment by jfbn** [comment]
Experiencing similar problems, only when running tests on GHA.

**Comment by gurleen2022** [comment]
Facing similar issue only when running tests on Circle CI.

**Comment by linh-eureka** [comment]
This issue still persists when I try to navigate to this simple page: https://www.w3schools.com/html/html_iframe.asp

**Comment by BartVanRaemdonck** [comment]
I also have this issue when I try to reload a page with `await this.page.reload();`

Error: page.reload: Test timeout of 90000ms exceeded.
Call log:
  - waiting for navigation until "load"

**Comment by schmijos** [comment]
I'm coming from SemaphoreCI to this issue. Running the tests locally works fine.

**Comment by c4chuan** [comment]
facing this issue too, when goto http://localhost:9980, which is the address of a docker website

**Comment by denissteinhorst** [comment]
I ran into a similar issue on my Ubuntu 24.04 machine - every WebKit call failed, even though I had all the dependencies installed and the other browser tests (Chromium, Firefox) worked fine.

Error:
>navigating to "https://domain.tld", waiting until "load"

Playwright was basically unable to open any page using WebKit, regardless of whether it was a local or public URL.

--- 

**For me, the solution was to install VS Code directly from the .deb package instead of via Snap.**

My guess is that Snap's sandboxing restricts how environment variables are handled and how the app accesses libraries and dependencies, a restriction that isn't there when you install VS Code directly from the .deb package.

Hope this helps you too!

_Edit: Formatting, typo fix & added issue description for better findability.._
