### ISSUE TITLE
[BUG] `browser.newPage` not working with Opera browser

### ISSUE THREAD

**Issue by mesolido** [microsoft/playwright#12399]
**Context:**
- Playwright Version: [1.18.1]
- Operating System: [Linux and Mac]
- Node.js version: [14.17.2, 17.6.0]
- Browser: [Opera]
- Extra: []

**Code Snippet**

```javascript
const playwright = require('playwright');


(async () => {
	let browser = await playwright.chromium.launch({
		executablePath: '/usr/bin/opera',
		headless: false
	});
	let page  = await browser.newPage()
	await page.goto('https://twitter.com')
	setTimeout(process.exit, 30000);
}) ();

```

**Describe the bug**
Just wanted to use Playwright with Opera.

`browser.newPage` fails by raising an exception `Error browser.newPage: Browser closed`. We adapted the code on Mac with `playwright.webkit.launch` and Opera app path, but the same exception was raised. Note that the same error was found with Puppeteer.

**Comment by aslushnikov** [comment]
@mesolido which version of Opera are you using?

**Comment by mesolido** [comment]
Version 84.0.4316.21 on Fedora 34 and Version 83.0.4254.27 on Mac

**Comment by mxschmitt** [comment]
I tried on mac and it works for me.

**Comment by mesolido** [comment]
I still have this issue in my case. However, I found a workaround: 
- When Opera launches, it automatically opens a  tab (page)
- I get a reference to this initial page via `browser.pages()`  and from its context (`pages[0].evaluate`), I navigate URLs with `window.open`
- Then I setup listeners on the `browser` to get notified when the page loads (`ontargetcreated`)
So far this is sufficient for what I am doing.

**Comment by pavelfeldman** [comment]
Closing as per above.
