### ISSUE TITLE
[BUG] page.waitForSelector('text="something"'); flaky

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1239]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Linux

**Code Snippet**

```javascript
    await page.type('#username', 'foo');
    await page.type('#password', 'foo);
    await page.click('#login');
    await page.waitForSelector('text="Please provide a new password"');
```

**Describe the bug**

The above snippet times out at `page.waitForSelector()`. The element looks like below. I've verified that removing the `""` for the `text=` selector does not work either, and also even just doing a subset of the text like "new". I've run in headful mode to verify the text is there.

Unfortunately the code is private, so I cannot share, but can if necessary potentially try to create a minimum repro. I'm writing here first in the hopes that maybe you might already know what the problem might be?

I can attest to that I've run `page.waitForSelector('text=` earlier in the code and in that case it _does_ work, so I am stumped as to why it would be flaky.

```html
<div class="field" id="message" style="color: rgb(242, 242, 242);">Please provide a new password.</div>
```

**Comment by pavelfeldman** [comment]
Could you clarify if this text is within any iframes or shadow dom?

**Comment by thernstig** [comment]
The text is not within an iframe nor in a shadow dom. But the text is first hidden, and then immediately displayed after clicking the button with the id `#login`.

I even tried to do `await page.waitForSelector('text="You');` after the click on the button, but that "You" text is always visible (before and after click of button).

**Comment by aslushnikov** [comment]
@thernstig also, it looks like the element has a trailing "." - you should have it as your text selector!

```js
await page.waitForSelector('text="Please provide a new password."');
```

Alternatively, you can use regex to match with substring:

```js
await page.waitForSelector('text=/new password/');
```

**Comment by thernstig** [comment]
@aslushnikov I misread the docs. I read it as `test=Login` would also match `Login.`, when it in reality only removes trailing/leading whitespace and is case-insenstive.

I was thinking it would make more sense for it to be like `String.includes()`, but with the addition of also being case-insensitive. My experience in testing is that tests become flaky due to adding a period or not to matchers, as not everyone uses them. Would it make sense that `test=Login` thus is more similar to `String.includes()` + case-insensitive? I assume one would want the default to be the one most commonly used, and `text=` without double-quotes is the default per the docs.

In addition, is the docs incorrect [here](https://github.com/microsoft/playwright/blob/master/docs/api.md#working-with-selectors) and [here](https://github.com/microsoft/playwright/blob/master/docs/selectors.md#examples)? They both read:

> selector starting with " is assumed to be text=selector

But the example shows:

```javascript
// converted to 'text="foo"'
const handle = await page.$('"foo"');
```

Notice how it says converted to `text="foo"` with double-quotes, which is the opposite of what the quoted text says.

(I assume this issue now turned into both a semantic question + a docs bug 😄 )

**Comment by thernstig** [comment]
@aslushnikov Is my above assumption about docs correct? I.e. that they should be updated?

**Comment by aslushnikov** [comment]
> Is my above assumption about docs correct? I.e. that they should be updated? I can even send a PR myself, but I need confirmation.

@thernstig ah, sorry for the late reply. I clarified the docs in https://github.com/microsoft/playwright/commit/13c2f6571b3c6fad2d1633e13af3d21e8f2d3b47

> My second question about how test=Login could work instead is of course more opinionated/another topic. I could open a new issue for that if you feel it is a feature request you think you want to implement.

This sounds good - let's change this!

**Comment by aslushnikov** [comment]
Closing this in favor of #1341

**Comment by thernstig** [comment]
@aslushnikov #1341 sounds good - it solves one thing.

But I am not sure the docs are correct still. Let me try to be more explicit. All my assumptions is taken from this text: https://github.com/microsoft/playwright/blob/master/docs/selectors.md#text (first and second bullet regarding double-quotes).

Your change says:

> Selector starting with `"` is assumed to be `text=selector`. Example: `page.click('"foo"')` is converted to `page.click('text="foo"')`.

When I think it should say:

> Selector starting with `"` is assumed to be `text=selector`. Example: `page.click('"foo"')` is converted to `page.click('text=foo')`.

**OR**

> Selector starting with `"` is assumed to be `text="selector"`. Example: `page.click('"foo"')` is converted to `page.click('text="foo"')`.

Notice the missing double-quotes in my example of `page.click('text=foo')`?

If the docs are incorrect, it needs to be updated in multiple locations:

https://github.com/microsoft/playwright/blob/master/docs/api.md#working-with-selectors
https://github.com/microsoft/playwright/blob/master/docs/selectors.md#selector-syntax
https://github.com/microsoft/playwright/blob/master/docs/selectors.md#examples

**Comment by aslushnikov** [comment]
> Your change says:
> > Selector starting with " is assumed to be text=selector. 

@thernstig I see what you mean and how it might be confusing. The definition is technically correct - double-quotes are a **part of selector**. Let me break down the example that we have in the docs:
1. consider `page.click('"foo"')` (notice how there are single-quotes that wrap double-quotes)
2. in this case, selector is `"foo"`.
3. selector starts with `"`, so it is transformed into the form of `text=selector`
4. substituting selector with its value, getting `text="foo"`
5. which gets us to `page.click('text="foo"')`

**Comment by thernstig** [comment]
Thank you for that explanation, it did make things better. My natural follow-up question is the, should `'"foo"'` be better converted to 'text=foo'? Reason I am asking is the same logic as for https://github.com/microsoft/playwright/issues/1341, that I as a user would fint it more natural maybe to use `"foo"` to just do partial matches, as I _assume_ that is what most users expect. No data to back it up of course ;)

Thanks for being awesome @aslushnikov
