### ISSUE TITLE
Firefox Desktop device failing on Github action, but not locally.

### ISSUE THREAD

**Issue by altruisticsoftware** [microsoft/playwright#12405]
Hey there, thanks so much for this project!

We've already added [this test](https://github.com/code4recovery/tsml-ui/blob/main/e2e/tests/controls.spec.ts) in our repo with all devices listed in [our current config](https://github.com/code4recovery/tsml-ui/blob/main/playwright.config.ts) and that works great, but after submitting a PR with [this additional test](https://github.com/code4recovery/tsml-ui/pull/207/files), the `Firefox Desktop` device specifically can't seem to find the target based on [the logs](https://github.com/code4recovery/tsml-ui/runs/5280170705?check_suite_focus=true). 

Everything passes locally, so I'm not sure exactly how to pin down what differences are happening here. Any thoughts?

**Comment by mxschmitt** [comment]
Please use `npx playwright install --with-deps` instead of the GitHub Action, this is the recommended way. 

Closing for now, please file a new issue if you still encounter issues.
