### ISSUE TITLE
[Question]: Getting bounding boxes for visible text

### ISSUE THREAD

**Issue by LucidHal** [microsoft/playwright#12404]
### Your question

Hello,

Is it possible to get all the visible text blocks on a page and get bounding boxes for them like we can for visible inputs/textareas?

**Comment by aslushnikov** [comment]
@LucidHal there's nothing out-of-the-box. Could you describe your usecase? Maybe we still can help somehow.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
