### ISSUE TITLE
[BUG] Failed to launch firefox browser on Linux

### ISSUE THREAD

**Issue by zhanghua000** [microsoft/playwright#12406]
**Context:**
- Playwright Version: 1.19.0.post3+g0ffc788
- Operating System: Arch Linux
- Python version: 3.10.2
- Browser: Firefox
- Extra: None

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    b=p.firefox.launch()
    b.new_page().goto('https://bing.com')
    b.close()
```
**Describe the bug**

when runs code above, there will raise this Exception:
```
Traceback (most recent call last):
  File "/home/zhanghua/VisualStudioCode/test.py", line 5, in <module>
    b.new_page().goto('https://bing.com')
  File "/usr/lib/python3.10/site-packages/playwright/sync_api/_generated.py", line 7328, in goto
    self._sync(
  File "/usr/lib/python3.10/site-packages/playwright/_impl/_sync_base.py", line 111, in _sync
    return task.result()
  File "/usr/lib/python3.10/site-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: NS_ERROR_PROXY_CONNECTION_REFUSED
=========================== logs ===========================
navigating to "https://bing.com/", waiting until "load"
============================================================
```
Both sync and async APIs are tested and they are same.

**Comment by aslushnikov** [comment]
@zhanghua000 The error you're getting is: `NS_ERROR_PROXY_CONNECTION_REFUSED`

Looks like you're using some proxy, and it doesn't work any more. So things time out trying to navigate!

**Comment by zhanghua000** [comment]
@aslushnikov I don't think so. Because I have never pass `proxy` argument in the code above or set any transparent proxy on my system. What's more, if I launch chromium by replacing `p.firefox` with `p.chromium` in the code, everything works as expected.

**Comment by aslushnikov** [comment]
@zhanghua000 weird! If you could build a repro for us (using Docker), we'd look into that!

**Comment by zhanghua000** [comment]
Ah, finally I find it is my mistake,there is a gtk setting which contains custom proxy and I forgot to check it because I am using KDE. Sorry to bother you.

**Comment by megahomyak** [comment]
> there is a gtk setting which contains custom proxy and I forgot to check it because I am using KDE

Could you please tell where that setting is? I'm in exactly the same situation and I haven't tried the setting yet, I cannot find it
