### ISSUE TITLE
apiRequestContext params doesnt allow an array

### ISSUE THREAD

**Issue by marina-mosti** [microsoft/playwright#12428]
### Discussed in https://github.com/microsoft/playwright/discussions/12364

<div type='discussions-op-text'>

<sup>Originally posted by **marina-mosti** February 25, 2022</sup>
Hello, I'm trying to send out an api request that sets a params as follows:

```js
const result = await request.get('/url', {
      params: {
        properties: ['myProp']
      }
    })
```

This however malforms the url query into `url?properties=myProp`.

https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get
I noticed that the docs don't explicitly say that an array is allowed, so I managed to bypass this restriction by doing:

```js
const result = await request.get('/url', {
      params: {
        'properties[]': 'myProp'
      }
    })
```

This is less than ideal since I now have to do some parsing to handle array properties on calls.
Is there any particular reason why query params are not allowed for arrays? This seems very odd, and im not sure if its a design desition or a bug :)</div>

**Comment by yury-s** [comment]
[The docs](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get) clearly say that each param value can be one of `string|number|boolean`, the reason for that is that all of them can be unambiguously converted to string. Currently if you pass anything but those types the value will be converted to string using `String(value)`. If you want to change that behavior you can serialize it manually the way you like, e.g.:

```js
const result = await request.get('/url', {
      params: {
        properties: JSON.stringify(['myProp'])
      }
})
```

**Comment by marina-mosti** [comment]
Thanks for the workaround

**Comment by svella-at-nice** [comment]
This is definitely a bug - yes working as designed and documented, but the design is flawed because multiple query parameters (or headers, for that matter), with the same name is a thing and an http client that can't represent that is broken.

**Comment by DanielAlbavera** [comment]
If it's helpful for someone.

my GET request needs to pass an array as queryParam like this:

example:
{
   string: 'abc',
   boolean: true,
   array : [1, 2, 3]
}

The way I bypass this in TypeScript:
```
const response: APIResponse = await request.get('/endpoint`, {
params: {
      'string': 'abc,
      'boolean': true,
      'array[0]': 0,
      'array[1]': 1,
      'array[2]': 2
   }
});
```
