### ISSUE TITLE
[Question] Should APIrequestcontexts share cookie state with each other?

### ISSUE THREAD

**Issue by awmcclain** [microsoft/playwright#12424]
I'm able to successfully authenticate using `browserContext.request` withing `playwright.test` (where a set-cookie header is sent back from the server), and future requests from within the page send the cookies along.

However, if I make another request using `browserContext`, no cookies are sent in the headers of the request. Am I missing something?

```
const resp = await context.request.post('/api/1/test/')

console.log(resp.headers())
// {
//  'content-type': 'application/json; charset=utf-8',
//  'set-cookie': 'foo=MTY0NjExMTAyOXxEdi1CQkFFQ180SUFBUkFCRUFBQUhfLUNBQUVHYzNSeWFXNW5EQWtBQjNWelpYSmZhV1FFZFdsdWRBWUNBQTQ9fKxaqpGPQXDLX7S_TpcnZ9Fd0KsBB4YTXSnsJOyqtCWf; Path=/; Expires=Thu, 31 Mar 2022 05:03:49 GMT; Max-Age=2592000; Secure; SameSite=None',
//  vary: 'Origin',
//  date: 'Tue, 01 Mar 2022 05:03:49 GMT',
//  'content-length': '33',
// }

  const page = await context.newPage();
  await page.goto('/')
// incoming headers to server: map[
//  Accept:[application/json] 
//  Accept-Encoding:[gzip, deflate, br]
//  Accept-Language:[en-US] Connection:[keep-alive] Content-Type:[application/json] 
//  Cookie [foo=MTY0NjExNDE5OXxEdi1CQkFFQ180SUFBUkFCRUFBQUhfLUNBQUVHYzNSeWFXNW5EQWtBQjNWelpYSmZhV1FFZFdsdWRBWUNBQTQ9fCce32G5mqLKF6ViuAdJboejDerHQcNYBn9YbHRygFSO] 
//  Referer:[http://localhost:8080/] Sec-Ch-Ua:[] Sec-Ch-Ua-Mobile:[?0] Sec-Ch-Ua-Platform:[] Sec-Fetch-Dest:[empty] Sec-Fetch-Mode:[cors] Sec-Fetch-Site:[same-origin] 
//  User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4863.0 Safari/537.36]]

  const resp2 = await context.request.get('/api/1/users/identity')
// incoming headers to server: map[Accept:[*/*] Accept-Encoding:[gzip,deflate,br] Connection:[close] User-Agent:[Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/100.0.4863.0 Safari/537.36]]

**Comment by yury-s** [comment]
This is expected to work (the cookies should be stored on the context and later passed along with the requests). What is the base url? Note that the response contains `Secure` cookie so it will only be sent with https requests. You can call [`context.cookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies) to get all cookies from the context and check if the expected one is there.

**Comment by awmcclain** [comment]
baseurl is http://localhost:8080

The cookie exists in `context.cookies()`, it's just not being attached to the headers.

Perhaps this is due to the special-casing of localhost, where chromium attaches secure cookies over http but playwright isn't?

**Comment by yury-s** [comment]
Once the cookie is in the context storage it's up to Chromium whether they are sent along with the requests, Plyawright doesn't tamper with that. Can you share a small repro?

**Comment by yury-s** [comment]
Nevermind, this is indeed in the api request, it doesn't make an exception for localhost when handling `Secure` cookies. I'll prepare a fix.
