### ISSUE TITLE
[Feature] ARM Support

### ISSUE THREAD

**Issue by JBDCE** [microsoft/playwright#1243]
Im trying to get software running on a raspberry pi and getting into issues regarding arm7 compatibility. 
Is there a workaround to this already? 
I would love to contribute to this if someone could help me to get started.

**Comment by aslushnikov** [comment]
So if you have browsers that work for you on ARM, then Playwright will just work.

ARM-state for the browsers:
- For Chromium, i know you can compile for ARM manually. Related discussion: https://github.com/puppeteer/puppeteer/issues/550
- For WebKit, I know you can cross-compile GTK for ARM: https://trac.webkit.org/wiki/BuildingGtk. We do rely on WPE for headless, and I'm not sure if ARM is supported there
- For Firefox, you can cross-compile for ARM as well: https://developer.mozilla.org/en-US/docs/Mozilla/Developer_guide/Build_Instructions/Cross-compiling_Mozilla

ATM we don't plan to build and provide browsers binaries for ARM devices.

> I would love to contribute to this if someone could help me to get started.

The best way to contribute here is to set up a third-party storage somewhere that will have the ARM builds of browsers. If you do one, we'd be happy to feature it in our docs!
