### ISSUE TITLE
[Question] How to get browser version when launching browser in launchPersistentContext

### ISSUE THREAD

**Issue by rai-gaurav** [microsoft/playwright#12433]
I have few test scenario where I have to do performance test and for that the first condition is the browser should not be running in incognito mode(as for this scenario the end-user will be using the browser in default mode).
I am able to launch persistence context as mentioned [here](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) and able to do everything.
One issue I am facing with launching persistent context is I am not able to get browser version (since the return value is browser context).
In my all other scenario I am using `browser.version()` to get browsers version. I am not able to get similar function like that anywhere is doc.

Is there any function available to get the browser version when launching the browser in persistent context or is there nay way we can get that for all the browsers ?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by DvDream** [comment]
I would need this feature too pleaseeee, thanks :)
