### ISSUE TITLE
[Feature] add describe.skip

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#12453]
Can we add `describe.skip`, since we already have `describe.only`?

**Comment by dgozman** [comment]
We also have `describe.parallel` and `describe.serial`, and I don't really want to introduce `describe.parallel.skip` and `describe.serial.skip`.

**Comment by A-ZC-Lau** [comment]
curious, what's wrong with adding `describe.serial.skip` when we also have `test.describe.serial.only`
