### ISSUE TITLE
[BUG]  Trace File is not showing the proper view 

### ISSUE THREAD

**Issue by Nhc007** [microsoft/playwright#12458]
**Context:**
- Playwright Version: [1.19]
- Operating System: [Windows]
- Node.js version: [14.17.3]
- Browser: [Chrome]

I'm facing the problem in debugging with assistance of the trace file.

https://user-images.githubusercontent.com/100747950/156347961-b39f173c-1dc6-43d0-9fec-bee9598481b3.mp4

I've attached the video of trace, Initially the trace was showing the proper view and after some action, the trace view isn't appearing properly. It happens so often, I'm confused, what makes that happen particularly pointing to the distorted view of web in trace.  Also it show the proper view  of website in top timeline view. 

It cost us test failure: May be because the location of the selector changes a bit, also see the referenced video when the red pointer, points to different location(far from element).

![image](https://user-images.githubusercontent.com/100747950/156349623-f3f239d1-476f-488c-a0d4-20cacab680a8.png)

**Comment by FahadRS** [comment]
We are also experiencing the same issue, some times the trace log images are not appearing the correctly in the trace viewer how ever the images top timeline are correct

**Comment by aslushnikov** [comment]
Looks like Service Worker is misbehaving. Any chance you have a reliable repro that we can use?

**Comment by FahadRS** [comment]
we don't have any exact steps to produce this, we have around 110 tests which run 4 times in a day and this problem occurs at least once in a day
we are running these tests on the windows server in the CI/CD pipelines

**Comment by mxschmitt** [comment]
We had some related fixes for that included in the last release. Let us know if you still encounter issues with a clear repro, thanks!

**Comment by kristiyanplpeev** [comment]
In my company we are currently experiencing similar issue, for the last two weeks we don't see some of our elements in the trace viewer (even sometimes clicking on the steps in the left panel "Actions" doesn't change the screen preview), however, similarly to @FahadRS the images in the timeline viewer in the top are correct. Did you guys find any solutions to that?

Version:
    "@playwright/test": "^1.52.0",
    "@reportportal/agent-js-playwright": "^5.1.11",
