### ISSUE TITLE
[Question] Worker process exited unexpectedly

### ISSUE THREAD

**Issue by kspolam** [microsoft/playwright#12457]
Test failed  and reason is --  'Worker process exited unexpectedly'
What can be the reasons form above error and how to overcome this

**Comment by kspolam** [comment]
Thank you for the reply

What causes the process.exit,  is it playwright or the application under
test?

**Comment by aslushnikov** [comment]
> is it playwright or the application under
test?

That's the application under test!

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by oa-bcbs** [comment]
I'm seeing this error when I run tests in azure pipeline.
@playwright/test@1.38.0
Everything works as expected in local, but in pipeline it shows error `Internal error: worker process exited unexpectedly (code=null, signal=SIGSEGV)` . I tried to wrap whole test with try catch but it didn't help. is there any better way to debug or identify the issue?
