### ISSUE TITLE
[Feature] Provide a meaningful error message instead of "Context was closed"

### ISSUE THREAD

**Issue by kettanaito** [microsoft/playwright#12462]
Hi! Thank you for a great testing tool!

Can we please get a more descriptive error message than `Context was closed`? 

This honestly reads like an internal exception leak instead of a meaningful error message for developers. Every time I have to debug this there's always a reason behind that closure. 

I propose Playwright:

- Exposes a meaningful error message when the context is closed/destroyed.
- Propagates any page exceptions and errors alongside that meaningful error message.

## Expected behavior

I want to see error messages like this:

```
PageError: Failed to execute "page.[command]" because the browser quit unexpectedly.

Here's a runtime exception thrown in the browser that may be relevant to this problem:

  Error: Cannot read property "ABC" of undefined
    /stack/trace/file.js@1:12

We've also found errors printed in the browser's console:

  console.error "Something went wrong"
```

**Comment by aslushnikov** [comment]
@kettanaito could you please paste an actual error message, or better - a small code snippet that illustrates the issue?

**Comment by kettanaito** [comment]
Hey, @aslushnikov. Sharing some of the error messages below.

## Example 1: Target page, context or browser has been closed

```sh
  ● Test suite failed to run
    Error: page.goto: Target page, context or browser has been closed
```

Expected:

- Mention what address Playwright attempted to `goto`.
- Include the message of the actual error thrown (even if internal).
- Be more specific what failed (page, or context, or browser—these are three vastly different areas with different things that may cause issues).

## Example 2: Target closed

```sh
    console.error
      page.evaluate: Target closed
```

Expected:

- What was the code snippet Playwright attempted to `page.evaluate`?
- What is "Target" in this context? A page? A browser? Something else?
- Include any relevant error messages, including runtime messages from the browser's console. I'm 99% certain this particular failing test has a runtime error in the console. 

Let me know if those are sufficient to illustrate my point. Also, thanks for such a swift reply!

**Comment by kettanaito** [comment]
I'm raising this because Playwright often behaves differently on CI than it does locally. The lack of critical information in the error messages makes it a stroll in the dark to debug, as these errors do not happen locally.

**Comment by pavelfeldman** [comment]
All good suggestions, but we don't have enough hands to cover those. It might also be not that trivial to tell closed page apart from closed context.

**Comment by kettanaito** [comment]
I don't mind addressing this if you can help me with getting around the code base and reviewing my pull request. Does this sound fair?

**Comment by torleifhalseth** [comment]
I dont know if this is totally related @kettanaito, but i received same error when running our tests in vscode with the plugin setting reuseBrowser set to true. This is the default setting. When i changed it to false all our tests run as expected.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by murilozilli** [comment]
this would be awesome to have
