### ISSUE TITLE
[Question] How do you know how long did this page run

### ISSUE THREAD

**Issue by LFYSec** [microsoft/playwright#12482]
Hello, I want to know how long did the page run, so that I cam make a page automatically quit after running into fixed length of time, how to know the length or set the timeout of a page?

**Comment by aslushnikov** [comment]
Not sure what do you mean by "page run", but you can specify a custom test timeout via [`test.setTimeout()`](https://playwright.dev/docs/api/class-test#test-set-timeout) call: 

```js
import { test, expect } from '@playwright/test';

test('very slow test', async ({ page }) => {
  test.setTimeout(120000);
  // ...
});
```

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
