### ISSUE TITLE
Error: playwright.config.ts: Cannot import a typescript file from an esmodule

### ISSUE THREAD

**Issue by jordevorstenbosch** [microsoft/playwright#12487]
Decided to create a new issue after seeing the one referenced below

having `"type": "module"` in `package.json` causes this error. And it seems it's still supposed to work even with that in there.

The 'fix' below does indeed work.

-----

I am now receiving this error after upgrading from 1.17.2 to 1.19.2

If I alter file `node_modules/@playwright/test/lib/loader.js`

```
  isModule = false;    // <---  force this to false
  if (isModule) {
    return await esmImport(); 
  }
```

then it starts working again.

Also using the generated playwright.config.ts file does not resolve this issue.

_Originally posted by @asdf23 in https://github.com/microsoft/playwright/issues/11755#issuecomment-1048380805_

**Comment by Robert-Nickel** [comment]
Same issue. The manual "fix" you proposed "worked". I just started out experimenting with playwright in my existing SvelteKit project - with this issue causing a not so great experience tbh.

**Comment by leanne1** [comment]
Same issue in a new project. Would be keen to see a fix or this!

**Comment by pavelfeldman** [comment]
Could someone share a repro with me?

**Comment by DawidKNS** [comment]
@pavelfeldman 
I have this problem "playwright.config.ts: Cannot import a typescript file from an esmodule"
My playwright.config.ts:
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
import { ProjectsSettings } from './page-object/TestFixtures';

```
const config: PlaywrightTestConfig<ProjectsSettings> = {
  forbidOnly: !!process.env.CI,
  workers: 1,
  testDir: './tests',
  timeout: 20000,
  outputDir: 'test-results/',
  expect: {
    toMatchSnapshot: { threshold: 0.2 },
    timeout: 20000
  },
  reporter: [
    [ 'list' ],
    [ 'junit', { outputFile: 'results.xml' } ]
  ],
  use: {
    headless: true,
    locale: 'en-EN',
    browserName: 'chromium',
    viewport: { width: 1280, height: 720 },
  },
 projects: [
    {}]
};
export default config;
```

tsconfig:
```
{
    "compilerOptions": {
        "target": "ES2020",
        "module": "ESNext",
        "moduleResolution": "node",
        "types": [
            "jest",
            "node"
          ],
        "esModuleInterop": true,
        "resolveJsonModule": true,
        "forceConsistentCasingInFileNames": true
    }
}

```
in package.json i have added 
  "type": "module"
hov i can resolved this problem?

**Comment by jordevorstenbosch** [comment]
> Could someone share a repro with me?

I've made one for you here:

https://github.com/jordevorstenbosch/sk-pw-issue


> sk-pw-issue@0.0.1 test
> playwright test

```bash
Error: playwright.config.ts: Cannot import a typescript file from an esmodule.
    at errorWithFile (/Users/jorde/projects/private/sk-pw-issue/node_modules/@playwright/test/lib/util.js:194:10)
    at Loader._requireOrImport (/Users/jorde/projects/private/sk-pw-issue/node_modules/@playwright/test/lib/loader.js:253:119)
    at Loader.loadConfigFile (/Users/jorde/projects/private/sk-pw-issue/node_modules/@playwright/test/lib/loader.js:75:18)
    at runTests (/Users/jorde/projects/private/sk-pw-issue/node_modules/@playwright/test/lib/cli.js:174:39)
    at Command.<anonymous> (/Users/jorde/projects/private/sk-pw-issue/node_modules/@playwright/test/lib/cli.js:79:7)
```

**Comment by pavelfeldman** [comment]
`PW_EXPERIMENTAL_TS_ESM=1 npm run test` ran for me without errors.

**Comment by IanVS** [comment]
I'm just trying out playwright for the first time, and ran through the `npm init playwright@latest` flow.  I hit the error referenced in this issue, and so used `PW_EXPERIMENTAL_TS_ESM=1 npx playwright test`, but now I see:

```
import { test, expect, Page } from '@playwright/test';
                       ^^^^
SyntaxError: The requested module '@playwright/test' does not provide an export named 'Page'
```

I'm using node v16.13.1 and playwright 1.20.1.

**Comment by wvhulle** [comment]
> sed -i 's/if (isModule)/if (false)/g' node_modules/@playwright/test/lib/loader.js

What is the permanent solution?

**Comment by IanVS** [comment]
@wvhulle are you using `PW_EXPERIMENTAL_TS_ESM=1`?  That's working fine for me in the latest playwright with up-to-date node version without changing my node_modules.

**Comment by pavelfeldman** [comment]
@IanVS you probably figured it out:
```js
import { test, expect, type Page } from '@playwright/test';
```

**Comment by pavelfeldman** [comment]
This should be working, please reopen with the steps to repro if it still does not work for you!

**Comment by dragonworx** [comment]
I was trying Playwright with Vite and TypeScript. I used the [vanilla-ts](https://stackblitz.com/edit/vitejs-vite-gdvang?file=index.html&terminal=dev) project sample and followed the [intro docs](https://playwright.dev/docs/intro) for Playwright but when I tried to run the example test with:

```bash
npx playwright test
```

I received this error:

```bash
TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /Users/alichamas/Github/playwright-test/playwright.config.ts
    at new NodeError (internal/errors.js:322:7)
    at Loader.defaultGetFormat [as _getFormat] (internal/modules/esm/get_format.js:71:15)
    at Loader.getFormat (internal/modules/esm/loader.js:105:42)
    at Loader.getModuleJob (internal/modules/esm/loader.js:243:31)
    at Loader.import (internal/modules/esm/loader.js:177:17)
    at Loader._requireOrImport (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/loader.js:287:28)
    at Loader._requireOrImportDefaultObject (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/loader.js:302:18)
    at Loader.loadConfigFile (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/loader.js:79:20)
    at Runner.loadConfigFromResolvedFile (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/runner.js:96:12)
    at runTests (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/cli.js:153:27)
    at Gr.<anonymous> (/Users/alichamas/Github/playwright-test/node_modules/@playwright/test/lib/cli.js:70:7) {
  code: 'ERR_UNKNOWN_FILE_EXTENSION'
}
```

Turns out having `"type": "module"` in my `package.json` was causing the issue. This was part of the default Vite setup but it seems you can swap this with `"type": "commonjs"` and then Playwright will run, as well as Vite building and hot-reloading fine.

**Comment by wvhulle** [comment]
> @wvhulle are you using `PW_EXPERIMENTAL_TS_ESM=1`? That's working fine for me in the latest playwright with up-to-date node version without changing my node_modules.

Sorry that still doesn't work with version 1.25, I will make a reproduction.

**Comment by FuriouZz** [comment]
@wvhulle Which node version do you use? I got the issue when I was using `node 16.6.1`. I upgraded to `node 18.10.0` and the issue disappeared. I suppose the problem may come with [installTransform](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/loader.ts#L316) which override module resolver. Maybe a change in node module resolution solved the issue.
