### ISSUE TITLE
How can solve this error 'Connection closed 

### ISSUE THREAD

**Issue by yogikanojia** [microsoft/playwright#12483]
Hi, 
I am getting this error **Connection closed (Cannot read incomplete UTF-16 JSON text as string with missing low surrogate.)** when read the value html page. 
my string is **_I have seen so far! 👏👏👏_**

Anyone know the solution of this issue.
Thanks in advance.

**Comment by aslushnikov** [comment]
@yogikanojia we can't help if there's no good repro! Please re-file with a good repro so that we can see and debug the error locally.

Thanks!
