### ISSUE TITLE
[BUG] page.waitForResponse and page.route don't work in conjunction

### ISSUE THREAD

**Issue by isaac-scarrott** [microsoft/playwright#12484]
## System:
 - OS: macOS 11.6.2
 - Memory: 345.82 MB / 16.00 GB
## Binaries:
 - Node: 12.22.8 - ~/.nvm/versions/node/v12.22.8/bin/node
 - Yarn: 1.22.17 - ~/.nvm/versions/node/v12.22.8/bin/yarn
 - npm: 6.14.15 - ~/.nvm/versions/node/v12.22.8/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

## Code Snippet

```javascript
const waitForNextGraphQLResponse = (page: Page) => page.waitForResponse('**/graphql');

test.beforeEach(async ({ page }) => {
  page.on('console', msg => console.log(msg.text()));
  page.route('**', (route, request) => {
    console.log(request.url());
    route.continue();
  });
});


// In test block
await Promise.all([waitForNextGraphQLResponse(page), locator.click()]);

```

## Describe the bug

When using the function I made `waitForNextGraphQLResponse` which uses `page.waitForResponse` and `page.route` in conjunction the graphql requests never get logged and the  `page.waitForResponse` promise is never fulfilled. I just get a timeout error. Seems like these two functions cancel each other out.

**Comment by mxschmitt** [comment]
I tried the following which was working for me, could you provide us a full repro of e.g. a demo GraphQL application?

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.route("**", route => {
    console.log(route.request().url())
    route.continue()
  })

  await Promise.all([
    page.waitForResponse('**/toc.json'),
    page.goto('https://docs.microsoft.com/en-us/samples/azure-samples/azure-sql-db-prisma/azure-sql-db-prisma/'),
  ]);
  await browser.close();
})();
```

**Comment by isaac-scarrott** [comment]
Apologies, I've just looked into it more and it turns out the request was wrapped in a service worker and it says in Playwright docs that `page.route` cannot be used with a service worker.

**Comment by mxschmitt** [comment]
We're working on it, stay tuned!

**Comment by isaac-scarrott** [comment]
Thanks, is there any way around this `await context.addInitScript(() => delete window.navigator.serviceWorker);` doesn't seem to work?

**Comment by isaac-scarrott** [comment]
After some playing around this is the working solution I have come to:

```
export const disableServiceWorkers = (page: Page) =>
  page.addInitScript(() => (navigator.serviceWorker.register = () => Promise.resolve(null) as any));
```

Using the method I mentioned above, the `window.navigator.serviceWorker` got reinstantiated.
