### ISSUE TITLE
[Question] Is there any assertion method can be used for UrlContains ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#12486]
I saw that we have an assertion for your ToHaveUrl, i was wondering if we can have something to use to assert that url contains certain substring.

**Comment by ltsuda** [comment]
You can use RegExp in this assertion method.

See an example here https://github.com/microsoft/playwright/issues/12438#issuecomment-1057289372

**Comment by amrsa1** [comment]
@ltsuda i have checked it, didnt work for me.

I have the following url 

`"https://example.comh/en/test/buy/search?locations=cc8b-41b4-9ba4-717a9ea12333"`

how to assert it contains `https://example.com/en/test/buy/search?locations=`

**Comment by ltsuda** [comment]
Do you need to assert that the URL starts with `https://example.com/en/test/buy/search?locations=` ?

I escaped the `?` as this is used by regexp, so I added `\?`

```javascript
await expect(page).toHaveURL(new RegExp('^https://example.com/en/test/buy/search\?locations='));

#or contains could be

await expect(page).toHaveURL(new RegExp('.*https://example.com/en/test/buy/search\?locations=.*'));
```

**Comment by amrsa1** [comment]
Not working 
<img width="1079" alt="Screenshot 2022-03-03 at 16 11 10" src="https://user-images.githubusercontent.com/32042806/156593054-1a7c1433-bfc0-40e1-b67c-e6219f3ab3de.png">


aslo have tried it like this 
`await expect(page).toHaveURL('/en/properties/buy/search?locations=' + new RegExp('.*'));`

didnt work as well

**Comment by ltsuda** [comment]
Sorry to hear that. I will have to test it here to try and find the correct usage, give me few moments.

Maybe someone from Playwright's team have the correct answer.

**Comment by ltsuda** [comment]
@amrsa1 try adding `\\?` in the RegExp.

https://stackoverflow.com/a/32376171

```javascript
await expect(page).toHaveURL(new RegExp('^https://example.com/en/test/buy/search\\?locations='));

#or contains could be

await expect(page).toHaveURL(new RegExp('.*https://example.com/en/test/buy/search\\?locations=.*'));
```

**Comment by amrsa1** [comment]
@itsuda its working thank you :)

`await expect(page).toHaveURL(new RegExp('/en/test/buy/search\\?locations=.*'));`

but have a method like UrlContains will be very useful for sake of simplicity

**Comment by aslushnikov** [comment]
Looks like the issue is resolved!
