### ISSUE TITLE
[BUG]: Playwright not working on Windows 11

### ISSUE THREAD

**Issue by vicradon** [microsoft/playwright#12481]
**Context:**
- Playwright Version: @playwright/test: ^1.19.2
- Operating System: Windows 11
- Node.js version:  v14.17.4
- Browser: All
- Extra: 

**Code Snippet**

```javascript
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
});
```

**Describe the bug**

When I try to run Playwright on my project, I get this error
```
Running 0 test using 0 worker


Error: src\stuff.test.js:3:1: test() can only be called in a test file

   at node_modules\@playwright\test\lib\util.js:193

  191 |
  192 | function errorWithLocation(location, message) {     
> 193 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  194 | }
  195 |
  196 | function expectType(receiver, type, matcherName) { 
```
I tried creating a fresh project but still got the error.

**Comment by cakmakfatih** [comment]
Your test file should be located inside `tests` directory instead of `src\`.

**Comment by vicradon** [comment]
@cakmakfatih I changed the directory but that didn't help. Here's the error I got.

```
npx playwright test tests/stuff.spec.js
Error: tests\stuff.spec.js:3:1: test() can only be called in a test file
    at errorWithLocation (C:\Users\DELL\Documents\codes\vaunt\vaunt-frontend-v2\node_modules\@playwright\test\lib\util.js:159:10)
```

**Comment by aslushnikov** [comment]
@vicradon This looks very similar to https://github.com/microsoft/playwright/issues/9193

Have you seen that issue?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
