### ISSUE TITLE
[Question] How to click on a <a> found on the same table row as a specific column?

### ISSUE THREAD

**Issue by alanbqs** [microsoft/playwright#12492]
I need to double click on an ```<a onClick=''><i>open_in_new</i></a>``` that sits on the same row as a specific column/row where the  ```<td class='col_d'>``` has a value of ```BBB```?

e.g.
<table>
<tr><td class='col_a'>1</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>xxx</td><td class='col_d'>AAA</td></tr>
<tr><td class='col_a'>2</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>yyy</td><td class='col_d'>BBB</td></tr>
<tr><td class='col_a'>3</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>zzz</td><td class='col_d'>CCC</td></tr>
</table>

```
<table>
<tr><td class='col_a'>1</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>xxx</td><td class='col_d'>AAA</td></tr>
<tr><td class='col_a'>2</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>yyy</td><td class='col_d'>BBB</td></tr>
<tr><td class='col_a'>3</td><td class='col_b'><a onClick='dosomething(this)'><i>open_in_new</i></a></td><td class='col_c'>zzz</td><td class='col_d'>CCC</td></tr>
</table>
```

I have tried await ```await page.click("a(:text('open_in_new'):left-of(:text('.col_d', { hasText: 'BBB' }))");``` but I don't think it's working. (Also, is there a way to test drive locators via the debugger or something?)
                        
I can see there is a left-of option in page.locator (see https://playwright.dev/python/docs/selectors#selecting-elements-based-on-layout), but I can't see examples that might do what I need

**Comment by aslushnikov** [comment]
> I need to double click on an <a onClick=''><i>open_in_new</i></a> that sits on the same row as a specific column/row where the <td class='col_d'> has a value of BBB?

@alanbqs or, using Playwright v1.19+:

```js
await page.locator('tr', { hasText: 'BBB' })
          .locator('text=open_in_new')
          .click();
```
