### ISSUE TITLE
[Question] Can I install chromium at particular location? and How to find current Chromium location on mac?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12496]
My Jenkins is on Linux env and chromium default location is `/usr/bin/chromium-browser` and I have this path setup in `executablePath` as well. So when I run my scripts locally, I have to remove this path and then it picks it chromium from my local mac location.

Is there any way to install chromium on same path `/usr/bin/chromium-browser` locally so my scripts works both on mac and linux?  Also, how can I find where is chromium installed on my local Mac machine?

**Comment by aslushnikov** [comment]
> Is there any way to install chromium on same path /usr/bin/chromium-browser locally so my scripts works both on mac and linux?

Not really; instead, I'd recommend configuring jenkins with `CR_EXECUTABLE_PATH` env variable and use it when you launch chromium.

Since you won't have this env variable locally, it'll just use the defualt PW bundled chromium instance. Will it work for you?

**Comment by shirshak55** [comment]
If you are using edge browser you can use this package: edge-paths (github.com:shirshak55/edge-paths.git), There is chrome-paths too. but that doesn't seem to be maintained. I will create chrome/brave/vivaldi paths in coming week.

And for now you can also use platform detection code to and branch the code. 


Disclaimer: I am the author of edge-paths

**Comment by gauravgandhi1315** [comment]
> > Is there any way to install chromium on same path /usr/bin/chromium-browser locally so my scripts works both on mac and linux?
> 
> Not really; instead, I'd recommend configuring jenkins with `CR_EXECUTABLE_PATH` env variable and use it when you launch chromium.
> 
> Since you won't have this env variable locally, it'll just use the defualt PW bundled chromium instance. Will it work for you?

@aslushnikov Ok thanks! Is there any way to find the chromium path on my mac?

**Comment by pavelfeldman** [comment]
Here is where Playwright stores its browsers, check out that entire doc page because it is written for people with scenarios like yours. As to where you have your Chrome installed on a mac, you should google it!
