### ISSUE TITLE
[BUG] Screenshots in headful mode have scrollbars

### ISSUE THREAD

**Issue by leonidx86** [microsoft/playwright#12494]
**Context:**

- Playwright Version: 1.19.2
- Operating System: Linux
- Node.js version: 17.6.0
- Browser: Chromium, Firefox

**Code Snippet**

```javascript
const playwright = require('playwright');
(async () => {
    const browser = await playwright.chromium.launch({ headless: false });
    const page = await browser.newPage();
    await page.goto('https://github.com/microsoft/playwright', { waitUntil: 'load', timeout: 10000 });
    await page.screenshot({ path: 'screenshot.png' });
    await page.close();
    await browser.close();
})();
```

**Describe the bug**

Screenshots taken in headful mode have a scrollbar, while in headless there is none (as it should be). Tested in Firefox and Chromium.
The only difference in test code to take both screenshots was to set `headless` to `true` or `false`.
I have also tried manually adding `--hide-scrollbars` Chromium launch arg with no effect.
Maybe this is related to #12287 
Same test in Puppeteer does not have this problem.

| Chromium Headless  | Chromium Headful |
| ------------- | ------------- |
| ![screenshot_headless](https://user-images.githubusercontent.com/6142178/156630517-5bbe7d79-d0e8-41a4-a4a7-46a90f36217c.png)  | ![screenshot_headful](https://user-images.githubusercontent.com/6142178/156630509-bf9b0cc8-6ed5-493f-a757-b13197db052a.png)  |

**Comment by aslushnikov** [comment]
Thank you for reporting! We have a bug wrt scrollbar management in headful and headless: https://github.com/microsoft/playwright/issues/4295

Merging this in there.

**Comment by leonidx86** [comment]
@aslushnikov Is there a workaround in the meantime? Or at least any idea if this issue will be addressed anytime soon? Thanks.

**Comment by aslushnikov** [comment]
@leonidx86 So far this is pretty low on our list since we don't understand the usecase. Specifically, why would you want to compare headless vs headful screenshots? Could you please share in the #4295 why this hits you?
