### ISSUE TITLE
[Feature] Randomise test execution order

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#12512]
Would be great if `playwright` had an option to randomise test order execution (even across filed). This is great for ensuring that tests are idempotent and don't rely on each other.

Moreover, this would be very helpful when using `--shard=1/x`. If execution time of your tests varies a lot, and quick tests all get scheduled on 1 shard, you will get an uneven distribution & un-optimal run times. Randomisation would alleviate those problems on a big enough dataset.

**Comment by mxschmitt** [comment]
Sounds similar to https://github.com/microsoft/playwright/issues/9297
