### ISSUE TITLE
[Question] about Microsoft log-in proccess

### ISSUE THREAD

**Issue by Maciejjy** [microsoft/playwright#12515]
Hello 

I have a simple test in which I have to log in to application through Microsoft system.
Test will pass 90% but sometimes log in proccess will fail because Playwright is doing actions too quickly (my assumption).

It can fail on two steps:
- input username
- input password

and result is always the same:
Input field (either username or password) looks empty.

I think it is because these input fields "float" into screen (little animation) so Playwright discovers them and perform input action but in reality input field is not ready yet. 
This is why test fail message is that Playwright could not locate element that should be visible in next test step. 

Test:
```

let USERNAME_FIELD = "#i0116";
let PASSWORD_FIELD = "#i0118";

async provideUsername() {
        await page.waitForSelector(USERNAME_FIELD);
        await page.fill(USERNAME_FIELD, "#{login}#");
        await page.click("#idSIButton9");
    }
```

    async provideUserPassword() {
        await page.waitForSelector(PASSWORD_FIELD);
        await page.fill(PASSWORD_FIELD, "#{password}#");
        await page.click("#idSIButton9");
    }

I don't have any issues with any test within application when I get there but log in proccess sometimes fail. 
I really don't want to implement any additional, hardcoded waits since I think it's very bad practice.

**Comment by shirshak55** [comment]
I have been using playwright for years and yes this is a  common problem. And, the easiest solution is to add delay in my opinion and use proper state checking like whether the button is visible or not.

And understanding the app is very important. Sometimes JavaScript can trigger and clear the form. Like in some react websites the form might be doing some validation step and might not accept the input etc while the playwright is typing the form.

And, sometimes the app expects you to not click that rapidly like some internal code might only allow you to input on other fields on required fields are valid.

In addition to the above example, I would like to present another example, the button might be initially in disabled status. Playwright enters the emails and tries to click the button. The solution is to use state visible here etc.

How about you try this:

```
await page.waitForSelector(PASSWORD_FIELD,{state:"visible"});
```

**Comment by Maciejjy** [comment]
I am doing double-check already for inputs fields.

First step is: 

await page.waitForSelector(PASSWORD_FIELD);

and second is:

await page.fill(PASSWORD_FIELD, "#{password}#");

According to documentation page.fill will wait until locator state is: attached, visible, enabled, editable
[https://playwright.dev/docs/actionability](url)

If that was correct I shouldn't even put waitForSelector step before filling this input field. 
page.fill should be enough.

I will try to add "visible" option to waitForSelector line, but I guess it's already visible because test never failed on that step.

**Comment by shirshak55** [comment]
@Maciejjy 

Yea, In such scenerio what I do is always check whether the input is filled or not. Something like this:

while(true)
   // check if form is filled. If yes break
  // delay by 100ms (just so it doesn't use too much cpu

Click the button.

**Comment by Maciejjy** [comment]
Ok but in my scenario input field will never be filled since this step already heppened. Problem is that Input field not "registered" this action because in reality it was not ready yet to be populated. 
That is why this step for test runner is marked as "passed" and it proceed to next test step but input field is still empty.

I assume that putting simple timeout for 1000ms would solve this but this is bad practice and to be honest I pick up Playwright after I read that it handles auto-waits perfectly..
Logging through Microsoft seems really common action for many applications so I would expect this to work unless I am doing something worng (which is why I created this topic).

**Comment by shirshak55** [comment]
@Maciejiy You check the content of the field. Like document.querySelector("node").value and compare it with real value. Its not a playwright problem as far as I know. Webpage JS seems to be culprit.

**Comment by Maciejjy** [comment]
@shirshak55 it is basic authentication proccess that can be viewed for example here:
[https://www.youtube.com/watch?v=lLc3QZyEA_Q&t=165s](url)
As you can see both username form and password form are floating to the center of the screen from right side. It's small animation, but I think it is enough for test runner to proceed with input action sometimes and not to wait enough until form is really ready.

> Playwright filled the form and lets say js is loaded and clears the form after it is loaded?

I don't think that this is issue strictly with input fields because there is another form after password asking "do you want to always remember password" with just two buttons YES and NO and sometimes test also fail on that step. I think this is because robot will click on the button but the button is not in place yet. In that case robot will not wait for YES/NO button but error is that element from next step is not visible. That means that click on YES/NO button was marked as "passed" step but in fact the form is still there.

I am not sure what kind of script you would like to see. There is only few simple steps which was mentioned before.

**Comment by ltsuda** [comment]
I don't know if this works or is the best way to do it but in my study repo, the page has an animated side menu and trying to click at some option there was failing. Then the only way to work was to wait for the element to be `stable`. 

Here's your example with the piece of code I have.

```javascript
let USERNAME_FIELD = "#i0116";
let PASSWORD_FIELD = "#i0118";

async provideUsername() {
        const userLocator = await page.locator(USERNAME_FIELD);
        const userHandle= await userLocator.elementHandle();
        await userHandle.waitForElementState("stable");
        await page.fill(USERNAME_FIELD, "#{login}#");
        await page.click("#idSIButton9");
    }
```

As we can see in the link below, the `fill` method doesn't wait for the element to be `stable`
https://playwright.dev/docs/actionability

**Comment by Maciejjy** [comment]
@ltsuda sounds like a great idea. I will definitely try this and inform about results.

**Comment by Maciejjy** [comment]
@ltsuda Unfortunately that did not help.
Robot will not wait for input field to "stabilize". 
Even for passed tests I can see on test recording that in the moment "password field" is sliding from right side, it has already ********** so password is there before this field finish animation.
For failed tests I always end up with empty password field and red message "please input password". I checked it manually and you ronly get that message when input field is ampty and you click SUBMIT button. 
Clicking this SUBMIT button is next step in test so for robot previous step (filling up password field) is finished and no error was registered for that action.

**Comment by yury-s** [comment]
Playwright only waits for the element to be visible and actionable before filling in the value. It doesn't guarantee that all js listeners have been added / all the logic that sets up the form has finished running. Unfortunately there is no generic way for Playwright to know that. It was very well described above. If you don't have better signals based on the page logic you can check if the input element contains expected value after it was filled and if for some reason it doesn't then retry.

> Even for passed tests I can see on test recording that in the moment "password field" is sliding from right side, it has already ********** so password is there before this field finish animation.

You can wait for the animation to finish via `await handle.waitForElementState("stable");` as suggested above and fill in the value after that.

**Comment by Maciejjy** [comment]
> You can wait for the animation to finish via `await handle.waitForElementState("stable");` as suggested above and fill in the value after that.

@yury-s like I said above, this does not help. Still some tests fail on auth proccess.

> If you don't have better signals based on the page logic you can check if the input element contains expected value after it was filled and if for some reason it doesn't then retry.

This is rather workaround. Putting loops in tests only for passing basic logging action. Also like I mentioned before there is one more form with two buttons after password form that works exactly the same (also with animation) so I cannot do it that way. For robot button is there ready to click, but it's not in place yet.
I think right now only way to deal with that issue is add small pause in tests but this is not good "solution".

**Comment by pavelfeldman** [comment]
Can we get a complete repro for this one? In 95% of cases like this, the bug is in the page that hydrates late / does not have listeners installed while Playwright is already interested with it. These are all real bugs that can be reproduced if you enable Slow 3G emulation in DevTools and interact with the page immediately after you've seen the controls.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
