### ISSUE TITLE
Ignoring Tests that are inside .gitignore.

### ISSUE THREAD

**Issue by jonkarrer** [microsoft/playwright#12519]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Mac
- Node.js version: 17.5
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```zsh
npx playwright test tests/API
```

**Describe the bug**

When I run the standard npx playwright test tests/API, I get -->

``zsh
Running 0 test using 0 worker

=================
 no tests found.
=================
```
However, these test files exist. This only happened after I added these files to my .gitignore.

**Comment by yury-s** [comment]
Are those ignored files  *.js compiled from corresponding *.ts or why do you want to not commit them? If that's the case then you should simply set [testMatch](https://playwright.dev/docs/api/class-testconfig#test-config-test-match) in the project config to something like `/.*\.ts$/` to match only typescript files.

See also #11060

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
