### ISSUE TITLE
[Feature] Retry failed test on the particular browser that has been failed on ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#12514]
if i'm running a test against 3 different browser and it failed in one of them, retry option will retry the test again against the 3 browsers.

it would be great if we can have an option to rerun it again but only against the failed one

**Comment by yury-s** [comment]
Can you share the project where it happens? I cannot reproduce it with a simple test below:

```js
test('test retries', async ({ browserName }) => {
  console.log('browserName ' + browserName );
  expect(browserName !== 'webkit').toBeTruthy();
})
```
With `retries: 2` in the config only `webkit` is retried.

**Comment by pavelfeldman** [comment]
Playwright will only retry the exact test (on the exact browser) it failed.

We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
