### ISSUE TITLE
[BUG] Html report only allow first trace to be viewable link, and remaining traces are download links

### ISSUE THREAD

**Issue by toannguyen83** [microsoft/playwright#12517]
**Context:**
- Playwright Version: 1.19.2
- Browser: Chromium

## System:
 - OS: Windows 10 10.0.19044
 - Memory: 20.10 GB / 31.91 GB
## Binaries:
 - Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

Sample test file code

```typescript
import test, { expect } from "@playwright/test";

test("create test that can generate multiple tracing files", async ({
  page,
  request,
}) => {
  // perform api request to a page, this will create a separate trace
  const response = await request.get("https://playwright.dev/");
  await expect(response).toBeOK();

  // perform UI test will also create a separate trace
  await page.goto("https://playwright.dev/");
  await expect(page).toHaveURL("https://playwright.dev/");
});

```

**Describe the bug**
I noticed this is happening on latest version 1.19.2. In earlier version I was able to view the report and click on each of the trace link and it opens to a trace viewer. But recent version, only first trace can be viewed, but when I click on sub-sequent trace link, it downloads the trace file instead of open the viewer. 

See screenshot
![image](https://user-images.githubusercontent.com/2815878/156785317-54b79016-fb8a-41f2-97f4-b3be2ce751d9.png)

**Sample Code**
[playwright-report-issue.zip](https://github.com/microsoft/playwright/files/8186690/playwright-report-issue.zip)
- open command line to the test folder, run the following commands:
  ```cmd
  npm install
  npx playwright test
  npx playwright show-report
  ```
- check the html report

**Comment by toannguyen83** [comment]
On a side note, I noticed now that the top trace on the report seems like a consolidated trace (which is good I think I like this). It has all the UI trace + any api requests. I used to have to open each trace file one by one to see the details. So perhaps downloaded trace link is intentional?

**Comment by yury-s** [comment]
This is intentional, if you click on the screenshot it will open trace viewer with all traces loaded (context trace(s) and API request traces will be shown together). The download links underneath correspond to individual BrowserContext and APIRequestContext traces and you normally shouldn't need them.

**Comment by toannguyen83** [comment]
Thank you!
