### ISSUE TITLE
[Feature] Allow to start external proxy server

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#12523]
Currently there is an option to start an external web server before the tests are executed, see: https://playwright.dev/docs/test-advanced#launching-a-development-web-server-during-the-tests

I would like to propose to offer a similar functionality or maybe a best practice documentation item, to allow to start an external proxy server which then can be leveraged by browser instances created by Playwright. 

The idea to have a proxy server can useful when you want to execute Playwright tests against remote targets that are protected behind Google Identity-Aware Proxy or maybe Azure AD Application Proxy.

**Comment by yury-s** [comment]
Would it help if we allowed configuring multiple web servers (tracked in https://github.com/microsoft/playwright/issues/8206) ? Is there anything specific to the proxy functionality that would make the config different from web servers (I assume you can always specify proxy configuration in the browser config) ?

**Comment by weyert** [comment]
Yeah, that works for me! Nothing specific for the proxy server; maybe allow a way to exchange the opened port so the proxy can be configured accordingly in Playwright

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/8206
