### ISSUE TITLE
[BUG] "Must use import to load ES Module" when importing lodash-es into Playwright test

### ISSUE THREAD

**Issue by CheapeOne** [microsoft/playwright#12536]
**Update**: I created a minimal test repo that reproduces my problem, if that helps. https://github.com/CheapeOne/testapp .

**Context:**
- Playwright Version: 1.19.2
- Operating System: Mac
- Node.js version: v12.22.9
- Browser: All
- Extra: 
  - lodash-es v4.17.21
  - typescript v4.4.3
  - yarn v1.22.17

**Code Snippet**

Sample test file:

```typescript
// test.spec.ts
import { test } from '@playwright/test';
import { range } from 'lodash-es';

test('example', async ({page}) => {
  await page.goto('https://wikipedia.org');
  console.log(range);
});
```

Running:
`npx playwright test --headed`

Results in:

```
Error [ERR_REQUIRE_ESM] [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/asdf/testapp/node_modules/lodash-es/lodash.js
require() of ES modules is not supported.
require() of /Users/asdf/testapp/node_modules/lodash-es/lodash.js from /Users/asdf/testapp/playwright/test.spec.ts is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename lodash.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/asdf/testapp/node_modules/lodash-es/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1015:13)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/asdf/testapp/playwright/test.spec.ts:2:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._compile (/Users/asdf/testapp/node_modules/pirates/lib/index.js:136:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .ts] (/Users/asdf/testapp/node_modules/pirates/lib/index.js:141:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Loader._requireOrImport (/Users/asdf/testapp/node_modules/@playwright/test/lib/loader.js:269:14)
```

**Describe the bug**

My actual problem is I'm trying to import some mocks which themselves use `lodash-es`, but could reproduce the same error by simply trying to import `lodash-es` in a test file. This same error seems to happen even if I downgrade lodash-es version. I also tied using `PW_EXPERIMENTAL_TS_ESM=1 npx playwright test --headed` but the same result.

Here's my `tsconfig.json` if that helps. I'm curious if there's a problem there, playwright's test runner, or a problem with lodash-es.

```json
{
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "assumeChangesOnlyAffectDirectDependencies": true,
    "baseUrl": ".",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "lib": ["dom", "dom.iterable", "esnext"],
    "module": "esnext",
    "moduleResolution": "node",
    "noEmit": true,
    "resolveJsonModule": true,
    "skipLibCheck": true,
    "strict": true,
    "target": "esnext"
  }
}
```

Lastly I've tried manually compiling tests (suggested in the docs [here](https://playwright.dev/docs/test-typescript)) but same result.

**Comment by pavelfeldman** [comment]
I guess you are using config-less mode. Add `playwright.config.ts` with following content:

```js
export default {};
```

and run it as `PW_EXPERIMENTAL_TS_ESM=1 npx playwright test`.

**Comment by CheapeOne** [comment]
thanks for taking a look @pavelfeldman , I do actually have a playwright config. I created a minimal test repo that reproduces my problem, if that helps. https://github.com/CheapeOne/testapp . 

I'll add that lodash-es does indeed have `"type": "module"` in it's package json, but it may be a quirk of the underlying lodash _not_ being ESM.

**Comment by pavelfeldman** [comment]
I don't see `"type": "module"` in your test project's `package.json`. You can only import modules from modules.

**Comment by pavelfeldman** [comment]
Works for me, yes, experimental esm loaders are only supported on Node 16+.

```
~/tmp$ git clone https://github.com/CheapeOne/testapp
~/tmp$ cd testapp
~/tmp/testapp$ npm i
~/tmp/testapp$ PW_EXPERIMENTAL_TS_ESM=1 npx playwright test
(node:25323) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 1 test using 1 worker

  ✓  test.spec.ts:3:1 › example (2s)
[Function (anonymous)]


  1 passed (3s)
pfeldman@pfeldman-hp:~/tmp/testapp$ 
```

**Comment by CheapeOne** [comment]
Oh sweet, and I see you used `npm` and not `yarn`, I had included a yarn.lock file but if it's succeeding with a totally fresh install i think i need to regenerate that. Thanks for the help, I'll close this.

**Comment by red17electro** [comment]
I am encountering the same issue in the app of NX project, while importing a typescript utility functions file into my playwright test. That file has a `lodash-es` import, which leads to an error when I run the tests. Any suggestions how can I fix it? For now the solution for me was to move the functions that I need in the test into another utility file that does not contain that `lodash-es` import.

**Comment by fregante** [comment]
Having the same exact issue: switched from lodash to lodash-es in my monorepo and this error started appearing. But I already have plenty other ESM-only packages in the project so I'm not sure why this one particularly is failing.

What is turning my imports into `require` exactly? My tsconfig is set to leave imports unchanged:

```json
    "module": "esnext",
    "target": "es2023",
    "moduleResolution": "bundler",
```

**Comment by fregante** [comment]
@namukang the error just manifested itself in the opposite direction now that I swapped to ``"type": "module"` in the package.json

```
SyntaxError: The requested module 'lodash' does not provide an export named 'isPlainObject'
```

I fixed this one by using `lodash-es` in one of my dependencies as well (monorepo)

So the issue is likely because Playwright tries to read the test files as CJS due to the lack of `"type": "module"`
