### ISSUE TITLE
[Feature] Update Codegen to not use waitForNavigation()

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#12532]
Hello, I have noticed that when generating tests using Codegen, the navigation are mostly done with `waitForNavigation()` which could be noisy and I was wondering if we could it with just a click (since it will auto-wait): `page.locator('span:has-text("Issues")').click()` to make it more cleaner. Again, I could be wrong here but would like to hear some thoughts. Thank you!

```
import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  await page.goto('https://github.com/microsoft/playwright/');
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://github.com/microsoft/playwright/issues' }*/),
    page.locator('span:has-text("Issues")').click()
  ]);
  await Promise.all([
    page.waitForNavigation(/*{ url: 'https://github.com/microsoft/playwright/pulls' }*/),
    page.locator('span:has-text("Pull requests")').click()
  ]);
});
```

**Comment by yury-s** [comment]
`waitForNavigation` is only added for asynchronous navigation, e.g. for a simple click on `<a href>` link only `locator.click` is generated. If there is any navigation started within [5 seconds](https://github.com/microsoft/playwright/blob/e3e29e25beec3c6a95d111e992f4d7ae3b9774b4/packages/playwright-core/src/server/supplements/recorderSupplement.ts#L520-L523) after the click the recorder will add `waitForNavigation` call assuming that the navigation was triggered by the click. There is no easy way for the generator to figure out if the script should wait for that navigation or no so it errs on the side of always waiting for it, you can manually edit generated code based on your knowledge of the tested logic.

**Comment by Nav-2d** [comment]
Thank you for the explanation. Fair point!
