### ISSUE TITLE
[BUG]full xpath copy from chrome   playwright._impl._api_types.Error: Unexpected token "/" while parsing selector 

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright#12544]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
        page.wait_for_selector("/html/body/div[1]/div/div[2]/div/div/div[4]/div[1]/div[1]/div[1]/span", timeout=5000)  # 等待元素出现

```

**Describe the bug**
```
 return await self.inner_send(method, params, False)
  File "D:\Program Files\anaconda3\lib\site-packages\playwright\_impl\_connection.py", line 54, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Unexpected token "/" while parsing selector "/html/body/div[1]/div/div[2]/div/div/div[4]/div[1]/div[1]/div[1]/span"
```
Add any other details about the problem here.

**Comment by ltsuda** [comment]
You need to start the selector either with `//html/...` or `xpath=//html...`. You need `//` at the start so Playwright converts to xpath.

https://playwright.dev/docs/selectors#xpath-selectors

**Comment by wanghaisheng** [comment]
works like a charm  thanks for you
