### ISSUE TITLE
[Feature] Allow downloads with default context when connectOverCDP is used

### ISSUE THREAD

**Issue by lvyaoyu** [microsoft/playwright#12543]
playwright = sync_playwright().start()
executable_path = playwright.chromium.executable_path
logger.debug(f'executable_path：{executable_path}')
server = subprocess.Popen(f"{executable_path} --remote-debugging-port=9002")
time.sleep(2)
print(f'server：{server.pid}')
browser = playwright.chromium.connect_over_cdp(
    endpoint_url=f"http://localhost:9002",
)
# 如何给这个context 赋予accept_downloads属性
context = browser.contexts[0]
# 重新new的context可以赋予accept_downloads属性
context1 = browser.new_context(accept_downloads=True)

**Comment by mxschmitt** [comment]
```python
browser = playwright.chromium.connect_over_cdp(
  endpoint_url=f"http://localhost:9002/",
)
context = browser.new_context(accept_downloads=True)
page = context.new_context()
```
does this work for you?

Please formulate your issue in english, otherwise we can't support you.

**Comment by lvyaoyu** [comment]
When I used connect_over_CDP to generate a browser object, I used the browser's original context, but this context could not be used to pass a value to the accept_downloads parameter, so the file could not be downloaded

**Comment by lvyaoyu** [comment]
> 
When I used connect_over_CDP to generate a browser object, I used the browser's original context, but this context could not be used to pass a value to the accept_downloads parameter, so the file could not be downloaded

**Comment by lvyaoyu** [comment]
When I used connect_over_CDP to generate a browser object, I used the browser's original context, but this context could not be used to pass a value to the accept_downloads parameter, so the file could not be downloaded




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/playwright"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月7日(星期一) 晚上6:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [microsoft/playwright] [Question]使用connect_over_cdp创建的browser的默认context如何设置accept_downloads属性 (Issue #12543)





 browser = playwright.chromium.connect_over_cdp(   endpoint_url=f"http://localhost:9002/", ) context = browser.new_context(accept_downloads=True) page = context.new_context()
 
does this work for you?
 
Please formulate your issue in english, otherwise we can't support you.
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mxschmitt** [comment]
Which version are you using? Playwright by default now accepts downloads, so it should just work fine when you use the default context.

**Comment by lvyaoyu** [comment]
> Which version are you using? Playwright by default now accepts downloads, so it should just work fine when you use the default context.
我已经使用了最新的1.19版本，但还是不行，python版本3.8.5，win10系统，代码如下：
import os
import subprocess
import time
from loguru import logger
from playwright.sync_api import sync_playwright, Page, Download

DOWNLOADS_PATH = './data'


def _intercept_download(download: Download):
    file_name = download.suggested_filename
    file_path = os.path.join(DOWNLOADS_PATH, file_name)
    logger.debug(f'file_path：{file_path}')
    download.save_as(file_path)

def _binding_page(page: Page):
    page.on('download', _intercept_download)


playwright = sync_playwright().start()
executable_path = playwright.chromium.executable_path
logger.debug(f'executable_path：{executable_path}')
server = subprocess.Popen(f"{executable_path} --remote-debugging-port=9002")
time.sleep(2)
print(f'server：{server.pid}')
browser = playwright.chromium.connect_over_cdp(
    endpoint_url=f"http://localhost:9002",
)

context = browser.contexts[0]
context.on('page', _binding_page)
page = context.pages[0]
page.goto('http://127.0.0.1:8001/')
# Click to trigger the download event
page.click('//a[text()="PycharmProjects.rar"]')
page.wait_for_timeout(10000)
playwright.stop()
server.kill()

**Comment by rai-gaurav** [comment]
+1 for this. I have a similar scenario where I have to do performance test by uploading/downloading of files by attaching Playwright to an existing browser instance to replicate user behavior. Currently I am getting error asking to make `accept_downloads` as True for download to work.
But there is no such param in `connect_over_cdp`
