### ISSUE TITLE
[Question] install playwright to centos

### ISSUE THREAD

**Issue by jiheapark** [microsoft/playwright#12548]
I want to install playwright to centos7.

I used 
```
npx playwright install
npx playwright install-deps
```

but when I tried to test by playwright, (`npx playwright test`) I got this error.
<img width="834" alt="스크린샷 2022-03-07 오후 2 33 19" src="https://user-images.githubusercontent.com/26865541/156973988-d40132f9-2d5f-490d-883b-b57ca542b554.png">

what should I do?

And is there any way to install playwright by curl???

**Comment by mxschmitt** [comment]
CentOS is not officially supported, only Ubuntu 18/20, MacOS and Windows. 

Folding it into https://github.com/microsoft/playwright/issues/9199

**Comment by Im-Midi** [comment]
Fuck

**Comment by dulestar** [comment]
Fuck +1
