### ISSUE TITLE
[BUG] timezoneId setting do not work

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#12547]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Windowsde -
- Node.js version: 17.0.1
- Browser: Chromium

**Code Snippet**

timezone.spec.ts
```typescript
import { test } from "@playwright/test";

test("timezone", async ({ page, timezoneId }) => {
	console.log(timezoneId);
	await page.goto("https://www.google.com/");
	await page.locator("input[name=q]").fill("my timezone");
	await page.keyboard.press("Enter");
	await test.expect(page.locator("div.card-section")).toContainText("Central Europe");
});
```
```typescript
import { PlaywrightTestConfig } from "@playwright/test";
const config : PlaywrightTestConfig = {
	use : {
		acceptDownloads : true,
		actionTimeout : 20000,
		baseURL : "http://localhost:3000",
		headless : true,
		screenshot : "only-on-failure",
		timezoneId : "Europe/Berlin",
		trace : "on",
		video : "on",
	},
};
export default config;
```

**Describe the bug**
timezoneId setting don't seem to have an effect, as it still shows my local timezone (Australia)

Note: Change timezoneId and expected output to a different place if you are in Berlin timezone.

I think this may be related to an error message I am getting in one of my tests
![Screen Shot 2022-03-07 at 1 21 37 pm](https://user-images.githubusercontent.com/20273647/156956924-fedfbfb7-8aee-4c5f-b9b8-b320d6cb5023.png)

**Comment by mxschmitt** [comment]
Google does the detection by the IP - emulating timezone does not help there.

If you evaluate manually something it JavaScript it will work as expected:

```
await page.evaluate(() => new Date().toString()
-> Mon Mar 07 2022 13:49:32 GMT+0300 (East Africa Time)
```

**Comment by A-ZC-Lau** [comment]
But if I do it manually in chrome, I can get the effect.

Steps

1. Open developer console
2. Open "Sensors" in "More tools"
3. Change the Location override
4. Close the developer console
5. Type "my timezone" in google and search
![sensor](https://user-images.githubusercontent.com/20273647/157046919-b45331a0-cf31-4a5d-9d98-7d6221c28122.png)
![moscow](https://user-images.githubusercontent.com/20273647/157046923-bee5f171-de91-4a81-8655-c368d788ad2f.png)

**Comment by mxschmitt** [comment]
This is geolocation emulation, see here: https://playwright.dev/docs/emulation#geolocation

You can also set it inside your playwright.config.ts.
