### ISSUE TITLE
[BUG] Ignore SSL no longer works

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#12559]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.19.2
- Operating System: [e.g. Windows, Linux or Mac] LINUX And Windows
- Node.js version: [e.g. 12.22, 14.6] 17
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

**Describe the bug**

After upgrading, the ignore SSL no longer works. The chromium upstream team has made some radical changes that gives warning like "You are loading insecure link on https and this wont work".

**Comment by mxschmitt** [comment]
Which version was a good version and which one was a bad version of Playwright?

Do you have a screenshot or upstream bug where this might be reflected in?

**Comment by shirshak55** [comment]
@mxschmitt

I was using 1.13.1 and yesterday I upgraded it to 19. <img src="http://localhost/hello.png"> used to work properly. But after upgrading to playwright v19 it is saying we can't load the HTTP thing. (It gives a warning in the console though).


I don't know which upstream bug is causing this issue because the version range is pretty wide. I will see if I can give minimal reproduction issue.

**Comment by mxschmitt** [comment]
It would already help if you could try creating a smaller range of Playwright versions. Also it would help us if you could share what kind of webserver you are using, so we can try it out locally.

I'm curious because the resource link you shared is http:// but the error is about https://?

**Comment by shirshak55** [comment]
@mxschmitt 

Lets say you open https://google.com. And you inserted element <img src="http://localhost:8888/hello.png" />. The issue now is google chrome is showing issue related to http links aren't allowed in https website etc.. In past, there was no such error. 

The webserver is simple express js webserver. 


![image](https://user-images.githubusercontent.com/8097377/158026242-363507eb-902d-4b71-a1dc-013213b70750.png)


This bug is a very subtle bug, which I don't like.

Reproduction repo:
https://github.com/shirshak55/playwright-https-bug


Anyway, I can get around this issue by using self signed ca and https. If you think this should be fixed feel free to reopen it.

**Comment by mxschmitt** [comment]
Ah this is actually not an error, this is just a warning! Seems like a won't fix then.

**Comment by shirshak55** [comment]
@mxschmitt Well the image doesn't load because of https error. So, I consider it as a bug. The old playwright (probably due to old chromium) had no issues. And, what would be best way to load such image without going through hassles of installing own CA etc?

**Comment by mxschmitt** [comment]
That's a web browser issue rather than a playwright issue. Since in the real world it also would never work. It's a mixed content type error, so probably expected but we can reopen and wait for other users to run into it.
