### ISSUE TITLE
[BUG] Test fails when running headed mode

### ISSUE THREAD

**Issue by RamiAl** [microsoft/playwright#12552]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Windows
- Node.js version: 14.15.1
- Browser: Chromium

**Code Snippet**
```javascript
    await page.waitForSelector('#downloadRoutinesBtn')
    const [newPage] = await Promise.all([
      page.context().waitForEvent('page'),
      page.click('#downloadRoutinesBtn') // Opens a new tab
    ])

    await newPage.waitForLoadState()
    expect(newPage.url()).toContain('blob:')
  })
```

**Describe the bug**
downloadRoutinesBtn will open new tab which will contain PDF document. This code will run successfully when the `headless` mode is set to false, but will fails when it's true. The `newPage.url()` will return just `:` (the new tab's url), while when `headless` mode is false the same function will return `blob:http://localhost:3000/....`. Any idea why the url is `:` when the `headless` mode is set to true

**Comment by michelebyman** [comment]
I have the same issue

**Comment by yury-s** [comment]
Can you attach a page where this is reproducible? On a simple example the pdf is opened in the builtin viewer in headful and downloaded to a file in headless ( there is not pdf viewer in headless):

```js
test('should click pdf link', async ({ browserType, server }) => {
  const browser = await browserType.launch({ headless: false });
  const page = await browser.newPage();
  await page.setContent(`<button>Hello</button><a target=_blank href="${server.PREFIX}/empty.pdf">empty.pdf</a>`);
  const [popup] = await Promise.all([
    Promise.race([
      page.waitForEvent('popup'),
      page.waitForEvent('download')
    ]),
    page.click('a')
  ]);
  console.log(popup.url());
  await browser.close();
});
```

**Comment by Mone71** [comment]
Thanks
