### ISSUE TITLE
[internal] firefox 98 does not start under linux arm64

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12557]
https://github.com/microsoft/playwright-internal/runs/5446852781?check_suite_focus=true

**Comment by aslushnikov** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1757571

**Comment by aslushnikov** [comment]
Fixed with the roll to M97. I'll move this to 1.21 so that we keep track of the upstream work to fix firefox 98.

**Comment by aslushnikov** [comment]
Upstream seems to be fixed!
