### ISSUE TITLE
[Feature] Combine different selectors to locate elements

### ISSUE THREAD

**Issue by PeterHevesi** [microsoft/playwright#12553]
I would really love, if Playwright could combine selectors of different kinds or selectors of same kind. Because I would like to simplify writing selectors. 

For example, all navigation links on our website has class called "nav-link", and I also want to make sure they aren't hidden for example. So I would really love to create a class called NavigationLink, which has selector:
"xpath=//a[contains(@class, 'nav-link') and not(contains(@class, 'dg-hidden'))]"

Now I would just write something like:
var someNavigationLink = new NavigationLink(id='hello')

And it would combine that kinda long selector I defined in my class NavigationLink that would be used for all navigation links, and it would then be super easy to just define what else I know about some concrete navigation link like id=´'hello' or name='hello' or any other selector, but there would be no need to define that long selector over and over again, because it would be combined together. Now this was just an example to illustrate what I would really love to achieve, but you could imagine even more complicated selectors that I know about some element types. 

But I don't think it's possible to do with Playwright right now.  
There is fantastic operator >> that can combine multiple selectors like selector_1 >> selector_2, but in a way, that selector_2 looks in a subtree of selector_1. I would like to have some operator like selector_1 && selector_2, which would do intersection of elements found with selector_1 and elements found with selector_2.

This && operator would allow me to define that long selector in the class, and ask for another supplementary selector in constructor, and inside this class I would be able to combine them.

But there is also another use case: If anybody wants to just simply combine different selector types (selector engines) in selector, like: "css='input:enabled' && name='hello' && text='world'". It's just a normal simple selector, but thanks to this && operator, I would be able to beautifully combine different selector engines.

Thank you very much for any replies and if you consider implementing it, I would greatly greatly appreciate it :) 
Because I really do believe, that this feature could be super cool and also could be very useful.

**Comment by ddaypunk** [comment]
Could you get them all and then just filter out `dg-hidden` ones? Just trying to get more details as to reason and use of the feature.

You could also have the component class take in a boolean for hidden and apply that in the constructor (depending on the language being used)

**Comment by PeterHevesi** [comment]
I am not sure what you suggest. Surely I am thinking about implementing it myself, but I don't think it's that easy, even one of Playwright guys Max Schmitt told me, that it's not that easy.

And I tried so hard to explain use case of this feature as clearly as I could :D 
But to make it simple and clear, this feature would allow a huge simplification of complicated selectors that are used for many elements on a website. If it's only one element, I totally don't care, but when I have many elements with complicated selectors, it's kinda huge pain to maintain them. So I want to extract some common part of these complicated selectors into a base class, and then all these elements I need to use would be able to have much simpler selectors. But it's not possible to combine selectors, so I am not able to achieve this extraction into base class.

**Comment by azad-derakhshani-GS** [comment]
You could just write your own helper function that achieves what you want:

```
    async getNavigationLinkByAttribute(attribute, value) {
        let navigationLink = await this.page.locator(`xpath=//a[contains(@Class, 'nav-link') and not(contains(@Class, 'dg-hidden')) and contains(@${attribute}, '${value}')]`);
        return navigationLink;
    }
```

So from there it would be pretty straightforward and easy to use To use your example from above:

`let someNavigationLink = await this.getNavigationLinkByAttribute('id','hello');`

**Comment by PeterHevesi** [comment]
And in Playwright, they probably got inspired by my idea and created that Filter function in version 1.22, so thank you very much 🥇:)

**Comment by azad-derakhshani-GS** [comment]
Hehe yeah I also had to create a lot of infrastructure to deal with certain issues. :D 
Yeah I get what you mean, although xpath also supports `starts-with` and `ends-with`, so you could do `ends-with(@class, 'someClass')` for example.

That's a good idea actually, adding the other operators to PW!

I've been using other CSS combinators too, not just >>, but also > (child) and + (adjacent sibling) for example. But they are quite limited, unlike Xpath they don't offer ancestors, parents etc.

**Comment by PeterHevesi** [comment]
I am glad you like my idea 😊
And I didn't know about > (child) and + (adjacent sibling) operators, so thank you for this tip 🙂
And I also prefer Xpath, which is much more powerful than CSS.

**Comment by azad-derakhshani-GS** [comment]
Yeah I only found them here a few months ago, hadn't used CSS that much before either:
https://www.w3schools.com/css/css_combinators.asp

Also found this helpful since it provides things like "starts with" etc:
https://www.w3schools.com/css/css_attribute_selectors.asp

**Comment by dgozman** [comment]
This issue seems to be covered by `Locator.filter`, CSS `>` and `>>` combinators and XPath syntax. Please file a new issue if you are missing some specific usecase.
