### ISSUE TITLE
[BUG] explicitly prohibit maxDiffPixels from toMatchSnapshot

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#12564]

**Comment by kirill-konshin** [comment]
Why is this a bug?

This option appears in documentation: https://playwright.dev/docs/test-snapshots and https://playwright.dev/docs/release-notes#highlights

https://github.com/americanexpress/jest-image-snapshot allows two thresholds: per pixel and overall, I presume, overall is driven by `maxDiffPixelRatio` in Playwright? `maxDiffPixels` could be actually useful too...

**Comment by aslushnikov** [comment]
@kirill-konshin we had some second thoughts regarding these options, but this patch got reverted.

As of 1.20, both `maxDiffPixels` and `maxDiffPixelRatio` are live and ready for your use.

**Comment by kirill-konshin** [comment]
@aslushnikov That's great, these options are useful!

Some rationale: in my case we have some drawings & texts on canvas, and those ~20-40 loose pixels are the difference between Mac and Linux rendering of text. We do run tests in Docker on Mac as well, as recommended in PW docs, but sometimes it's hard to debug when tests are launched this way.
