### ISSUE TITLE
[Question] Render Japanese or Arabic fonts

### ISSUE THREAD

**Issue by BrunoQuaresma** [microsoft/playwright#12571]
Hey folks, I'm trying to render some pages containing Arabic or Japanese fonts but even loading the NotoSans font provided by Google fonts, it is being rendered as squares. 

Image screenshot:
![image](https://user-images.githubusercontent.com/3165839/157132832-e38d4e71-43ac-453f-806d-91d18f4bd35e.png)

Font:
[Noto_Sans (1).zip](https://github.com/microsoft/playwright/files/8201383/Noto_Sans.1.zip)

I'm running Playwright on Vercel using this library https://github.com/JupiterOne/playwright-aws-lambda.

Thanks in advance.

**Comment by yury-s** [comment]
Can you attach a full repro? Also does it render well without Playwright?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
