### ISSUE TITLE
[Question] close blank tab when start firefox

### ISSUE THREAD

**Issue by yeucodonvn** [microsoft/playwright#12584]
Playwright Version: [what Playwright version do you use?]
1.19
Operating System: [e.g. Windows, Linux or Mac]
Windows Home 10
Node.js version: [e.g. 12.22, 14.6]
v14.18.0
i launch firefox but when start. it creates new windows blank. i using  conect.pages() to count all pages but not detect it
![image](https://user-images.githubusercontent.com/18210504/157217215-fd34eeb1-2fab-4282-bab8-c6c654cd053b.png)

**Comment by yury-s** [comment]
Can you try it with the recent (1.19.2) playwright?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
