### ISSUE TITLE
Support 'force' as an option on locator.scrollIntoViewIfNeeded

### ISSUE THREAD

**Issue by jaywhar** [microsoft/playwright#12580]
Currently there's no way of ignoring the actionability checks when calling scrollIntoViewIfNeeded on a locator.

I'm working on a learning site where we require the user to answer questions by clicking buttons that are permanently animated (bouncing) to make them more visually apparent. Additionally, sometimes the answer button is outside the viewport and so the user has to scroll around the page to find them.

Since the button is always animating, we have to force a click - but this skips the actionability checks and so for the answers where the button is outside the viewport the action fails.

If we had the ability to scroll the button into view even though it is always animating then we could separate the scrolling and the forced click

**Comment by yury-s** [comment]
You can call HTML method [`Element.scrollIntoView()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView) in this case:
```js
  await page.locator('button').evaluate(e => e.scrollIntoView());
```
Will that work for you?

**Comment by jaywhar** [comment]
thanks - it doesn't work for my case, but that might be because we're doing some odd scrolling / panning behaviour.
Happy to close
