### ISSUE TITLE
[BUG] Playwright Test for VSCode doesn't run headed when debugging

### ISSUE THREAD

**Issue by ElineH** [microsoft/playwright#12588]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Windows
- Node.js version: 14.16
- Browser: Chromium

**playwright.config.json**

```js
const config = {
    globalSetup: require.resolve(`./base/global-setup`),
    use: {
        baseURL: 'http://localhost:8080',
        storageState: `state.json`,
        browserName: 'chromium',
        headless: true,
        screenshot: 'only-on-failure'
    }, 
    workers: 1,
    reporter: [ ['junit', { 
        outputFile: 'test-results/playwright-test-result.xml' 
    }], ['dot'] ], 
}
module.exports = config
```

**Code snippet of the test**
```js
import { test, expect, chromium, Page } from '@playwright/test';

let page: Page;

test.beforeAll(async ({ baseURL }) => {
    const browser = await chromium.launch();
    const context = await browser.newContext({ storageState: `state.json`, strictSelectors: true });
    page = await context.newPage();
    await page.goto(baseURL);
});

test.afterAll(async () => {
    await page.close();
});

test(`Create new rolling forecast test`, async() => {
    // Open scenario management
    const scenarioMngmtDropDown = page.locator(`id=standardDropDownList_scenarioManagment`);
    await scenarioMngmtDropDown.click()
.....
```

**Describe the bug**

Expected Playwright Test for VSCode to run the test headed (even when set to headless in config) when using the debug option. Doesn't seem to do that, no error as I can see. Runs as with regular debugging in VSCode.

**Comment by yury-s** [comment]
You  launch chromium manually so it doesn't pick up config from the test runner, use builtin browser/context/page fixtures instead and it will start in headful mode when debugging:

```js
import { test, expect, chromium, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
    await page.goto('/');
});

test(`Create new rolling forecast test`, async({page}) => {
    // Open scenario management
    const scenarioMngmtDropDown = page.locator(`id=standardDropDownList_scenarioManagment`);
    await scenarioMngmtDropDown.click()
.....
```

If you want to reuse the same page instance between tests use [serial mode](https://playwright.dev/docs/test-retries#serial-mode).

**Comment by ElineH** [comment]
Thx! Was able to get it to work.

**Comment by villesau** [comment]
@yury-s how does it work with the global setups like this: https://playwright.dev/docs/test-advanced#global-setup-and-teardown ? It manually spawns the instance. Can I get access to the managed browser there?

**Comment by EDjur** [comment]
+1 on @villesau 's comment on how it works with the global setup.

Any word on that @yury-s ?
