### ISSUE TITLE
[Feature] Test attachments in for test file and seen in HTML report

### ISSUE THREAD

**Issue by JuanCruzTrinidad** [microsoft/playwright#12586]
Test attachments only valid in test scope.
Created attachments in test file, for example attach screenshot in before all navigation or video record.

It is great idea seen attachments test file in HTML report, video reproductor by the suite and screenshots or json files evidence.

**Comment by JuanCruzTrinidad** [comment]
Exactly my request is the ability to attach files to a test suite or test archive. And that these are visible from the HTML report.

**Comment by pavelfeldman** [comment]
It is unclear what you mean by that, you can already use `test.info().attach` for that. Please feel free to open a new issue if this does not address your use case!

**Comment by shashankkvs309668** [comment]
Why iam getting this error as Missing attachment "screenshot" when executing this
![image](https://user-images.githubusercontent.com/89392342/189129828-b31e8226-9a06-4a40-a194-cb8769b9efc4.png)

**Comment by VijayUsingGitHub** [comment]
Any update on shashankkvs309668 issue. am also facing same problem.
