### ISSUE TITLE
[REGRESSION]: Chromium page will not close after opening session

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1258]
**Context:**
- GOOD Playwright Version: .local-chromium/linux-745253
- BAD Playwright Version: 0.11.1-next.1583455961750 .local-chromium/mac-747023 .local-chromium/linux-747023
- Operating System: Mac & Linux

**Code Snippet**

```javascript
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch();

  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto("http://example.org");

  const session = await context.createSession(page);

  await session.detach();
  console.log("session detached");

  // never resolves
  await page.close();
})();
```

**Describe the bug**

Page will not close when you open a session, browser will close.

**Comment by yury-s** [comment]
Thanks for the report! I managed to reproduce it, will work on a fix.
