### ISSUE TITLE
[Question]: is possible to hide inspector window, but show selector indicator

### ISSUE THREAD

**Issue by coader** [microsoft/playwright#12594]
### Your question
 is possible to hide inspector window, but show selector indicator
![image](https://user-images.githubusercontent.com/3700498/157200459-e8dd1365-bcbe-4510-ac92-5f357f174532.png)

like above, but do not show inspector window

**Comment by yury-s** [comment]
You can use [`locator.highlight`](https://playwright.dev/docs/next/api/class-locator#locator-highlight) which is already available in @next version and will be released in 1.20 soon.
