### ISSUE TITLE
[Question] How is the snapshot path built?

### ISSUE THREAD

**Issue by mdugue** [microsoft/playwright#12617]
I am having issues understanding how the path of the snapshot files is created when calling `toMatchSnapshot`. In my example 

- I have a test file called **pages.spec.ts** and another one called **detailsSlideover.spec.ts**
- when running all tests and calling `toMatchSnapshot` inside of **pages.spec.ts** the snapshot is stored in **.../detailsSlideover.spec.ts-snapshots**. See image below. 

Unfortunately this is not "stable", so if I only run tests for the one file explicitly, its snapshots are stored in a folder with the "correct" name.

Any hints on this? Am I missing an important configuration path, is it a race condition in playwright, is it on purpose?

![snapshotpath](https://user-images.githubusercontent.com/894149/157430213-8cff623b-1f0a-4719-ba01-38882d59abe2.jpg)

### some context:

- My configuration resembles https://github.com/vercel/next.js/tree/canary/examples/with-playwright. 
- I call `pnpm playwright test`  & `pnpm playwright test pages` to execute the tests, though regular "npm run" does not seem to make any difference
- `@playwright/test` is used in version 1.19.2
- this happens as well on MacOs as on Docker in CI

**Comment by yury-s** [comment]
The snapshot should be inside `.../pages.spec.ts-snapshots/` in your case. Will you be able to share a reproduction scenario that we could run locally?

**Comment by aslushnikov** [comment]
@mdugue do you require `pages.spec.ts` from `detailsSlideover.spec.ts` or vice versa?

**Comment by mdugue** [comment]
WOW, @aslushnikov, you are incredible. Yes, I shared some mock-data in that way. Thanks a lot! Extracting that mock-data to a dedicated module solves it. 

Is that behaviour on purpose? Maybe we could explain this behaviour in the docs in case or fix it somehow otherwise?

@yury-s , sorry I missed your response

**Comment by aslushnikov** [comment]
@mdugue I *think* we fixed this bug on tip-of-tree. Could you please try installing `npm i @playwright/test@next` and see if it works for you?

**Comment by mdugue** [comment]
Hey @aslushnikov sure. I fixed it already the way you pointed me to, but will checkout the old commit later on to provide feedback
