### ISSUE TITLE
[Question] is there any way to add new attribute to hide/remove element

### ISSUE THREAD

**Issue by dimag32** [microsoft/playwright#12618]
Hi, Im trying to create use case that removes specific  element from dom ,
I tried to add new attribute to element to make the element hidden but without success,is there any way to do such a scenario via elementHandle?
or some other solution to remove the element from vsibility?

Thanks,
Dima

**Comment by yury-s** [comment]
You can use [Locator.evaluate](https://playwright.dev/docs/api/class-locator#locator-evaluate) or [Locator.evaluateAll](https://playwright.dev/docs/api/class-locator#locator-evaluate-all) if there are multiple element and then you can pass a function that would modify the element to you liking in the page context, e.g.

```js
await page.locator('#myelement').evaluate(e => e.setAttribute('hidden', true));
```
