### ISSUE TITLE
[BUG] Locator.count() with _vue selector

### ISSUE THREAD

**Issue by yuvalkarif** [microsoft/playwright#12623]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Windows 10
- Node.js version: 16.13.0
- Browser: Chromium
- Site is using Nuxt 2 SSR 

**Code Snippet**

```javascript
// Doesn't work correctrly
const colorSelectorVue = await this.page.locator('_vue=NbwColorSelector >> visible=true')
const colorSelectorVueCount = await colorSelectorVue.count()

// output: colorSelectorVueCount=0

// Works as intended (class and _vue point to the same dom element)
const colorSelector = await this.page.locator('.color-selector')
const colorSelectorCount = await colorSelector.count()

// output: colorSelectorCount=3

```
![image](https://user-images.githubusercontent.com/34835592/157474787-2b449a18-c682-4d57-86bc-1b31adb0a177.png)

**Describe the bug**

As you can see the count() method on the locator doesn't work on locators that use the _vue selector, the interesting part is that the locator indeed locates the right element in the debugging tools. also using a class locator counts the elements fine.
Elements are not hidden (as they may appear in the screenshot) and fully working. Also I'm pretty sure this used to work in an earlier version but I cannot confirm for sure.

**Comment by yury-s** [comment]
Can you share a repro?

**Comment by yury-s** [comment]
Also have you tried [toHaveCount](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-count) as it may well be that the elements are not ready yet?

```js
await expect(colorSelectorVue).toHaveCount(3);
```

**Comment by yuvalkarif** [comment]
Hey, creating a repro is hard for me as I am not familiar with creating small projects for the purpose for recreation.
The project I am working on is a huge internal project. I tried your advice and `toHaveCount()` seems to be working as expected!
Too bad it is not covering all of the use cases for such a thing as I am using it also as a Boolean flag to continue and as iterator for going over all the elements that match the selection.
If there is a way for me to log anything for you guys or maybe if you have some kind of repro guide that I could use it would be amazing.
![image](https://user-images.githubusercontent.com/34835592/158060597-9eaa9859-f576-46af-a2ad-ad7ea1a1b80b.png)
(count = 0 vs toHaveCount = 1, should be 1)

**Comment by pavelfeldman** [comment]
We would really need a repro. It could be that the prod / tested version of the page has debug information stripped and _vue selectors simply don't exist / work there.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
