### ISSUE TITLE
[Question] Is there a way to wrap custom matchers as test steps similar to built in asserts to view in reports

### ISSUE THREAD

**Issue by vigneshrajsb** [microsoft/playwright#12639]
Hi
With custom matchers implemented, they are not reported as test steps in the reports.  Looking at builtin matcher implementation, they are wrapped here to be test steps.
https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/expect.ts#L186-L264

### Repo
https://github.com/vigneshrajsb/playwright-custom-matcher-sample
_the custom matcher here is implemented per official docs [here]([here](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend))_

### Screensnip
![image](https://user-images.githubusercontent.com/13482555/157574149-e03fccc3-3643-4b6a-90d0-ae62f98e18f4.png)

Could you please help me figure out if there is a way for custom matchers implemented to use this?

**Comment by yury-s** [comment]
This is not currently possible.

**Comment by vigneshrajsb** [comment]
thank you @yury-s.. any plans to make this available in a future release?
