### ISSUE TITLE
[Question] How to avoid unnecessary statements in html report

### ISSUE THREAD

**Issue by ShanmukhaGajula** [microsoft/playwright#12630]
expect.soft(await this.eleTotalPaymentsValue.textContent(),'eleTotalPaymentsValue').toMatch('0.00')
expect.soft(await this.eleBeginningBalancevalue.textContent(),'eleBeginningBalancevalue').toMatch('0.00')
expect.soft(await this.eleTotalEarningsvalue.textContent(),'eleTotalEarningsvalue').toMatch('0.00)
expect.soft(await this.eleEndingBalancevalue.textContent(),'eleEndingBalancevalue').toMatch('0.00')

above code give 8 lines of data in the HTML report how can we avoid unnecessary lines like getting textcontent which is not necessary or already part of except statement. because report looks clumsy. Please suggest.

![image](https://user-images.githubusercontent.com/21192877/157528484-ca68b8eb-f3f2-4b58-8b2a-508da49bae06.png)

**Comment by rwoll** [comment]
For these examples, you can use Web-First Assertions instead of manually querying for the content:

```diff
-expect.soft(await this.eleTotalPaymentsValue.textContent(),'eleTotalPaymentsValue').toMatch('0.00')
+await expect.soft(this.eleTotalPaymentsValue).toHaveText('0.00')
```

More info and assertions: https://playwright.dev/docs/test-assertions#expectlocatortohavetextexpected-options

**Comment by rwoll** [comment]
NB: In the example above, the leading `await` is necessary, and I'm assuming `this.eleTotalPaymentsValue` is a [Locator](https://playwright.dev/docs/locators). Web-First Assertions (like `toHaveText`) and Locators are recommended and produce a more concise log in the HTML Report.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
