### ISSUE TITLE
[BUG] firefox screenshots differ between headless and headed

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#12637]
Here is an example from the tests: https://github.com/microsoft/playwright/blob/5f1188d195c07318228795fc4b3757a08378893c/tests/screenshot.spec.ts#L23

From my local testing on MacOS, headed screenshots are correct when using `deviceScaleFactor: 2.5`, and headless screenshots are wrong.

**Comment by aslushnikov** [comment]
Merging into https://github.com/microsoft/playwright/issues/12683

**Comment by amrsa1** [comment]
When this fix could be released
