### ISSUE TITLE
[Feature] Option to not automatically hide caret in screenshots

### ISSUE THREAD

**Issue by ssams** [microsoft/playwright#12643]
Version 1.19 contained the great contribution to automatically hide blinking carets in screenshots (https://github.com/microsoft/playwright/pull/11854). Had a similar workaround with overriding styles for the `caret-color` in a project before, the generic integration avoids to manually disable it for visual tests and simplifies the tests a lot.

However I'd still like to request an option to *not* automatically hide blinking carets via CSS, ideally via a [TestOption](https://playwright.dev/docs/api/class-testoptions). The reason for this is that in particular for Firefox, a more powerful option to get similar results exists:

```typescript
const config: PlaywrightTestConfig = {
  use: {
    launchOptions: {
      firefoxUserPrefs: { 'ui.caretBlinkTime': 0 },
    },
  },
};
```

Instead of hiding the caret, this just disables the blink, thus also guaranteeing a stable screenshot, but with the added value that the caret is still visible. This allows to verify caret styling in visual tests, or check its position, etc., at least in Firefox. Thus, if an option to avoid insertion of the CSS would be available, one could setup projects where it remains visible but doesn't blink in Firefox, but is removed in other browsers.

**Comment by aslushnikov** [comment]
> Instead of hiding the caret, this just disables the blink, thus also guaranteeing a stable screenshot, but with the added value that the caret is still visible

@ssams Very fancy!

**Comment by ssams** [comment]
maybe naming such an option "static" (instead of "show") would make its effect even clearer.

Of course having it work in all three browsers is the nicest option. When I integrated it in our project I also stumble across the linked code parts during my research, problem was that it seems impossible to change it in Chromium + WebKit without making changes to the code and recompiling. Hence it wasn't an option for a quick solution in the project. Firefox has the advantage that it's changeable with the user preference, which can be controlled in the current (unmodified) version of Playwright already. But when integrating such functionality into Playwright properly, I assume the required code modifications are technically not a problem as the engines are custom builds anyway and can be patched as needed?

I guess it may take a while to fully implement this though? In the meantime, maybe a two-step approach for implementing this may work to allow gradually improving the available options:

1. add an option `caret: undefined | 'hide' `-> `undefined` does not change anything (i.e. behavior like it was before 1.19),  `hide` completely hides it (i.e. behavior introduced in 1.19).
    This allows to manually configure user preferences for Firefox (`undefined` + config from the initial comment), whilst hiding it for other browsers via the  `hide` option, or any other custom functionality added by a user. Basically `undefined` would give you the choice to handle it however you want again.
2. implement control of the blink interval for other/remaining browsers and then introduce an new option value `static` for the `caret` option -> should be a backwards compatible change, options from step 1 are unaffected

**Comment by aslushnikov** [comment]
@ssams so far we agreed on this two-step approach, but we'll have another API review before release.
