### ISSUE TITLE
[Question] Is it possible to run one test in last only after all the tests(running in parallel) are completed?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12656]
I have a requirement where I want to run one test(delete data) after all the tests running in parallel are completed. Is it possible to do that? I think `afterAll` won't work because Target page, context or browser will be closed.

**Comment by yury-s** [comment]
This is not currently possible, parallel tests will run in separate workers and each of them will run `afterAll` once the tests finished. The closest to this behavior would be to put the logic into [globalTeardown](https://playwright.dev/docs/api/class-testconfig#test-config-global-teardown) which will run once all tests (including others) are finished. Will that work for you?

**Comment by gauravgandhi1315** [comment]
@yury-s Do I need to mention my script name under `globalTeardown` in config file?

**Comment by gauravgandhi1315** [comment]
@yury-s I tried but seeing this error  `globalTeardown file must export a single function.`

```
test.describe('Direct Mail', () => {
  let verification, verifyActions;
  test('Submit - delete', async (page) => {
    verification = new NewSimEligibility(page);
    verifyActions = new VerifyActions(page);
    // Go to the application url
    console.log("gaurav testing parallel")
    await verifyActions.openURL(TestData.urlPath);
    await verifyActions.refreshPage();
    await verifyActions.clickOnElement("[title='HOME']");
  });
  });
```

**Comment by gauravgandhi1315** [comment]
@yury-s It works for me. Thanks for your help!
