### ISSUE TITLE
[BUG] A specific test not running on Docker (mobile safari)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#12667]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Mac
- Node.js version: 12.22
- Browser: Mobile Safari [iPhone 12]
- Extra: Docker image PW v1.19.2

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// foo.spec.js
test('test', async ({ page }) => {
    await page.goto(<MY_URL>);
});

// config.js
projects: [
 {
    name: 'Mobile Safari',
    use: devices['iPhone 12'],
 },
],
```

**Describe the bug**
The above test is passing locally when I run it using `npx playwright test`. Ran it 100 times and it worked 100 times. The test is simple which is navigating to an URL and waiting for the load event.

Running the same test on Playwright focal image 1.19.2, it fails. The logs:
```
Timeout of 30000ms exceeded.
....
    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "<MY_URL>", waiting until "load"
```

The same tests runs fine locally and on docker using projects like "Desktop Chrome", "Desktop Safari", and "Mobile Chrome" (Pixel 5)

Note: Shared `MY_URL` with @pavelfeldman privately

**Comment by nhe23** [comment]
I'm facing the exact same error when running my playwright tests inside the `mcr.microsoft.com/playwright:focal` container inside AzurePipelines. All tests for 'Mobile Safari' are failing with the same message @Nav-2d is getting. All the other browser work inside the pipeline. Locally all browsers work.

**Comment by yury-s** [comment]
@Nav-2d can you collect a trace and see if there is a particular request hanging in mobile safari version? Also I'd appreciate if you could share the url with me.

**Comment by Nav-2d** [comment]
@yury-s Shared the trace and URL with you on Slack

**Comment by Nav-2d** [comment]
@yury-s The issue seems to be resolved since this morning and the test is working fine on Docker (mobile safari). Not sure on the root cause yet. I am going to keep this ticket open to see if @nhe23 is still the issue.

**Comment by nhe23** [comment]
After some investigation I found out that Mobile Safari tests are working inside the Docker container but they are much more likely to timeout and fail compared to for example Mobile Chrome tests. This paired with the not so great performance of AzurePipelines lead to all Mobile Safari tests failing inside the pipeline.

**Comment by pavelfeldman** [comment]
Closing as per above
