### ISSUE TITLE
[Question] the docker need install playwhright again?

### ISSUE THREAD

**Issue by wuweikd** [microsoft/playwright#12674]
HI,

I had got the docker:  mcr.microsoft.com/playwright.

But when I use it, i need install playwright again. If i run `npx playwright install` , it will work. But why i need install again?

**Comment by mxschmitt** [comment]
If your Docker image version matches with the installed Playwright version, then you don't need to install the browsers or OS deps again.

e.g. `docker pull mcr.microsoft.com/playwright:v1.19.2-focal`

**Comment by kellis-scottlogic** [comment]
I am also experiencing this issue in 2 different pipeline configurations 

The docker image we use if pinned to the  `1.19.1` image

The Playwright version in package..json is also pinned to `1.19.1`

Yet when running the test in the pipeline, I am getting the message that Playwright was just installed or updated, and that `npx playwright install` must be run

**Comment by mxschmitt** [comment]
Maybe you have multiple versions of Playwright installed? Having a repro for that with logs would be very useful.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
