### ISSUE TITLE
[Question] why was `isVisible` and `isHidden`'s `timeout` deprecated?

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#12672]
as far as i can tell there's no easy way to simply check if an element is visible with a timeout.

is the best method now to just do something like this?
```ts
async function isVisible(selector: string, timeout: number) {
  try {
    await page.waitForSelector(selector, { timeout, state: 'visible' })
    return true
  } catch (e) {
    return false
  }
}
```

**Comment by mxschmitt** [comment]
I filed https://github.com/microsoft/playwright/issues/20033 for it, seems like our docs site has a bug.
