### ISSUE TITLE
[Question]specific URL cannot be opened in the  Chromium, but can open in firefox

### ISSUE THREAD

**Issue by Taoli96** [microsoft/playwright#12686]
specific url : http://43.248.49.97/ (I can access it through my browser)

code:

browser = playwright.chromium.launch(headless=False)
context = browser.newContext()
page = context.newPage()
page.goto(url)

The browser will prompt you with a 400 error

but,If I change browser type

browser = playwright.firefox.launch(headless=False)

Everything will be fine.

error have to do with browser types

**Comment by mxschmitt** [comment]
This site uses some obfuscated protection against browser automation. The first request is a 412 status code, then it loads some obfuscated JS and based on that it probably detects some automation.

Closing since we can't act on such individual use-cases.
