### ISSUE TITLE
[BUG] Assertion toHaveAttribute or method locator.getAttribute does not include options in locator

### ISSUE THREAD

**Issue by agataDeviniti** [microsoft/playwright#12684]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Mac
- Node.js version: v17.0.1
- Browser: Chromium (the others were not checked)

**Code Snippet**

```javascript
import { test } from '@playwright/test';

test('Playwright issue', async ({ page }) => {
    await test.step(
        'Navigate to Page',
        async () => {
            await page.goto('https://deviniti.com/#contact');
        },
    );
    await test.step(
        'Click on field',
        async () => {
            const parentLocator = '[class^="hs_firstname"]';
            const childLocator = 'input[id^="firstname"]';
            await page.locator(parentLocator, { hasText: 'Name', has: page.locator('label') }).click();

            const attributeWithoutOption = await page.locator(
                childLocator,
            ).getAttribute('placeholder');
            console.log(`attributeWithoutOption: ${attributeWithoutOption}`); //return attribute (correct behavior)

            const attributeWithOption = await page.locator(
                parentLocator,
                { hasText: 'Name', has: page.locator('label') },
            ).getAttribute('placeholder');
            console.log(`attributeWithOption: ${attributeWithOption}`); //return null (incorrect behavior)
        },
    );
});

```

**Describe the bug**

Assertion toHaveAttribute or method locator.getAttribute does not include options in locator, when provided.
I am using locator with options`hasText:` and `has:` as provided below:
`'[class^="hs_firstname"]', { hasText: 'Name', has: page.locator('label') })'`
It seems that method _locator.getAttribute_ does not include those options when looking for attribute. I have noticed the same problem with assertion _toHaveAttribute_.
I have also provided the part of code which contains correct behavior (locator child without options) and incorrect (locator parent with options). 

Feel free to ask me in case of any questions.

**Comment by yury-s** [comment]
`parentSelector` selects a `div` ('#hsForm_9ff0d26d-64a3-416a-84f1-4ae8d553682c > fieldset:nth-child(1) > div')  which doesn't have the attribute. You need to refine the selector to select input contained in it:

```js
            const attributeWithOption = await page.locator(
                parentLocator,
                { hasText: 'Name', has: page.locator('label') },
            ).locator('input').getAttribute('placeholder');
```

**Comment by agataDeviniti** [comment]
Hi @yury-s , thank you for I response, but I would like to clarify this case. I've just corrected the code provided above from 'label' to 'input' (my fault) :( 
But... I assumed that if I add  _"has:"_ option to my parentLocator it will find the same as childLocator. Am I right?
That is why I don't understand this behavior:  
-> When using .click() for parentLocator with _"has:"_ option -> it clicks childLocator -> correct
-> When using .getAttribute() for parentLocator with _"has:"_ option -> it finds atrribute for parentLocator (does not count  _"has:"_ -> it is not what I expect

Could you please claryify such behavior, that .click() counts with _":has"_ option, but .hasAttribute(), not? 
Thanks in advance :)
