### ISSUE TITLE
[Feature] expect(page).to_contain_title('...')

### ISSUE THREAD

**Issue by AutomationPanda** [microsoft/playwright#12692]
Currently, the Python binding has the following assertion for page titles:

```python
expect(page).to_have_title('panda at DuckDuckGo')
```

I'd love to have an assertion to check if a title *contains* a string. Sometimes, titles are long, and pieces may be arbitrary. Checking if a title contains a string would be useful in those cases. The code could look like this:

```python
expect(page).to_contain_title('panda')
```

I'm sure this would be useful in other language bindings, too.

**Comment by pavelfeldman** [comment]
@AutomationPanda how do you feel about adding it? :)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
