### ISSUE TITLE
[REGRESSION] Page.screenshot hangs on some sites

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12711]
**Context:**
- Playwright Version: ToT
- Operating System: Mac
- Node.js version: 16
- Browser: Chromium
- Extra: [any specific details about your environment]

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless:false,
  });
  const page = await browser.newPage()
  await page.goto("https://www.sina.com.cn/", {
    waitUntil: 'networkidle'
  })
  await page.screenshot({
    path: 'foo.png'
  })
  await browser.close();
})();
```

**Describe the bug**

Page.screenshot does not resolved.

**Comment by mxschmitt** [comment]
Probably the same as https://bugs.chromium.org/p/chromium/issues/detail?id=1121612 and https://bugs.chromium.org/p/chromium/issues/detail?id=1121612

**Comment by pavelfeldman** [comment]
I can repro with

```js
test('screenshot', async ({ page }) => {
  await page.goto('https://www.sina.com.cn/');
  await page.screenshot();
});
```
