### ISSUE TITLE
[Question] Gitlab doesn't recognize the failed status of the test run?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#12716]
**Context:**
- Playwright Version:1.18.0
- Operating System: Windows 
- Node.js version: 14.18.1
- Browser: Chrome
- Extra: GitLab CI/CD

**Describe the bug**

It seems like the GitLab runner doesn't recognize the failed status of the test run (in case we have a little amount of the tests).

For example,  I have several jobs in GitLab that have failed tests:
![image](https://user-images.githubusercontent.com/52656401/158060263-be69b3b8-298e-4138-9b36-455041224f87.png)

It can be also seen from the log of the runner:

![image](https://user-images.githubusercontent.com/52656401/158060326-82bde1ae-adf3-4b46-ba47-5939fe16762f.png)
![image](https://user-images.githubusercontent.com/52656401/158060339-aa4502e7-bac5-4b14-9646-bbf18a176958.png)

But the job of the GitLab passed in this case:
![image](https://user-images.githubusercontent.com/52656401/158060371-222b5f65-ab0e-4cf3-a744-880b11ec2816.png)
![image](https://user-images.githubusercontent.com/52656401/158060399-5a609c60-f5ca-4b17-a534-16d2a3baf2a1.png)

I know that every tool, such a GitLab, has a lot of configurations. Our jobs that contain bigger amount of the tests - fail as well in case we have failed tests.
Maybe our great Playwright team will have some idea about the reasons to this confusing thing?

**Comment by jithinjosejacob** [comment]
CI pipeline mostly looks at exit code of last script run to determine the exit code. It seems like even though your tests failed in a previous task , your artifact upload and cleanup task succeeded. This could be the reason why your job succeeded. Try removing the artifact upload and cleanup task and see if you are getting proper status

**Comment by pavelfeldman** [comment]
Yes, closing as per above! Make sure exit code is correct!
