### ISSUE TITLE
[BUG] Chaining a locator after a text selector that includes quote causes locator to fail

### ISSUE THREAD

**Issue by liamdocherty10** [microsoft/playwright#12719]
**Describe the bug**

This was originally raised under #12655 but the issue was quickly closed. I attempted to have it re-opened with no luck.

In the [text selectors documentation](https://playwright.dev/docs/selectors#text-selector) the first example is using `'text=Log in'` to achieve a partial case-insensitive match.

I want to achieve the same thing however I need to account for the text string having quotes in it.

I can successfully achieve this **until** I then want to chain an additional locator from it e.g. using `.nth()` to ensure I get the first. I'm looking for a generic solution rather than a specific fix for one scenario because I'm building some wrapper code around Playwright for our internal users.

For now I am using `:has-text()` as a workaround however it has a couple of drawbacks over `text=`:
1. I want the 'lowest' element that matches the text, whereas `has-text()` returns the 'highest' child
2. `has-text()` only 'searches' within child elements not at the same level as passed in so I can't for example locate a number of `<span>` elements and find the `<span>` that matches

The examples below aren't my real use case, simply a public example.

**Context:**
- Playwright Version: 1.19.1
- Browsers: All
- OS: macOS 12.2.1
- Memory: 1.33 GB / 16.00 GB
- Node: 14.17.0 - /usr/local/bin/node
- npm: 6.14.13 - /usr/local/bin/npm
- Bash: 3.2.57 - /bin/bash

**Code Snippet**
```javascript
import { test, expect } from "@playwright/test";

test("Demo", async ({ page }) => {
  await page.goto(
    "https://js.devexpress.com/Demos/WidgetsGallery/Demo/Menu/Overview/Angular/Light/"
  );
  await page.locator(".dx-loadpanel-indicator").waitFor({ state: "detached" });
  const iframe = page.frame({ name: "demo-frame" });
  await iframe.locator("dx-menu >> xpath=./div/ul/li/div >> nth=2").click();
  const subMenu = iframe.locator(".dx-submenu");
  const items = subMenu.locator(".dx-menu-item-has-submenu");

  // PASS (exact match including " but no chain)
  expect(await items.locator(`text=19"`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
  // PASS (partial match including " but no chain)
  expect(await items.locator(`text=9"`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
  // PASS (partial match leaving out " - chained with nth)
  expect(await items.locator(`text=19 >> nth=0`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
  // PASS (partial match leaving out " - chained with xpath)
  expect(
    await items.locator(`text=19`).locator("xpath=..").getAttribute("class", { timeout: 2000 })
  ).toBe("dx-item-content dx-menu-item-content");
  // FAIL (exact match including " - chained with nth)
  expect(await items.locator(`text=19" >> nth=0`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
  // FAIL (exact match including " - chained with xpath)
  expect(
    await items.locator(`text=19"`).locator("xpath=..").getAttribute("class", { timeout: 2000 })
  ).toBe("dx-item-content dx-menu-item-content");
});
```

```bash
    locator.getAttribute: Timeout 2000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".dx-submenu >> .dx-menu-item-has-submenu >> text=19" >> nth=0"
    ============================================================

      20 |   );
      21 |   // FAIL (when including ")
    > 22 |   expect(await items.locator(`text=19" >> nth=0`).getAttribute("class", { timeout: 2000 })).toBe(
         |                                                   ^
      23 |     "dx-menu-item-text"
      24 |   );
      25 | });
```

**Comment by pavelfeldman** [comment]
Looks like the expectations are that we escape trailing `"`.
For now you can work around it via `text="19\""` or `text=/19"/`

**Comment by liamdocherty10** [comment]
@pavelfeldman yes I believe that the `"` should be escaped.

Thanks for the suggestions however neither of those give me the exact solution I need. I need a partial match and to be able to chain an additional locator from it.

Fails because using double quotes looks for an exact match:
```
  expect(await items.locator(`text="9\"" >> nth=0`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
```

Fails with an error `SyntaxError: Invalid flags supplied to RegExp constructor 'i >> nth=0'`;
```
  expect(await items.locator(`text=/9"/i >> nth=0`).getAttribute("class", { timeout: 2000 })).toBe(
    "dx-menu-item-text"
  );
```
