### ISSUE TITLE
[Question]Can't provide an official method of context management. 

### ISSUE THREAD

**Issue by 2855512675** [microsoft/playwright#12713]
Can't provide an official method of context management. Because sometimes I need to run continuously on a page and load data by constantly sliding. I want a way without context management. Because I often encounter JS memory overflow. This makes me feel bad. I use this command page = context new_ Page () creates a separate page to run the program, and there will still be JS overflow. I hope the government can provide a plan.

**Comment by pavelfeldman** [comment]
It does not look like you scenarios is testing-related. We currently only focus on the testing scenarios!
