### ISSUE TITLE
[Feature] Let bundled WebKit MiniBrowser link to not a specified version of icu

### ISSUE THREAD

**Issue by shirok1** [microsoft/playwright#12717]
On Linux, MiniBrowser is linked to icu 66.
```
~/.cache/ms-playwright/webkit-1609/minibrowser-gtk/bin/MiniBrowser: error while loading shared libraries: libicui18n.so.66: cannot open shared object file: No such file or directory
```
I'm using Manjaro Linux, my icu version is 70. I guest that MiniBrowser is linked to icu 66 because that's the version on Ubuntu, which most CI container runs, but this only makes development on other Linux distro harder.
In my opinion, MiniBrowser should either link to dyn lib without specifying edition like just `libicui18n.so` (at lest it *may* work on distro with other icu version, rather than just break down), or ship with its own dependency (this can be an additional browser channel).

**Comment by pavelfeldman** [comment]
We only support Ubuntu atm, please feel free to send a PR that fixes it and we'll review it!

**Comment by pavelfeldman** [comment]
Marking this as closed to send a wont-fix signal.
