### ISSUE TITLE
[BUG]can't visit fedex tracking page

### ISSUE THREAD

**Issue by coader** [microsoft/playwright#12712]
https://www.fedex.com/fedextrack/?trknbr=270302988381

I  run playwright with headless=false
input url by manual, and always get error:
![image](https://user-images.githubusercontent.com/3700498/158041840-2aba4777-550d-4540-b386-1a2d1b4c77ba.png)

then i run chrome in incagotino mode, it's work fine, so what problem?

**Comment by coader** [comment]
just use headless=false to show chrome window, and input url by manual:https://www.fedex.com/fedextrack/?trknbr=270302988381
I have tried in other computer, also get this error

**Comment by pavelfeldman** [comment]
I can repro, I'm seeing:
```
Access to XMLHttpRequest at 'https://api.fedex.com/track/v2/shipments' from origin 'https://www.fedex.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

Caused by `--enable-automation`.

**Comment by pavelfeldman** [comment]
Fedex is making a check if browser is being controlled by the automation, and if it is, refuses to service information. You should raise this issue with them! 
`navigator[_acxj[40]]` stands for `navigator.webdriver` in the code. As a testing software, we are also setting this flag, to make sure we are in line with the target site requirements.

**Comment by coader** [comment]
sometimes we need playwright as rpa tools to reduce user's nosense input,

**Comment by digital-marketing-engineer** [comment]
Maybe Fedex is checking user-agent, or they have any checking for the header.
Try to imitate the request header that is used by normal browser.

**Comment by dav72** [comment]
> https://www.fedex.com/fedextrack/?trknbr=270302988381
> 
> I run playwright with headless=false input url by manual, and always get error: ![image](https://user-images.githubusercontent.com/3700498/158041840-2aba4777-550d-4540-b386-1a2d1b4c77ba.png)
> 
> then i run chrome in incagotino mode, it's work fine, so what problem [fedex tracking](url="https://usps-track.us/fedex/")?


They have placed a delayed script which detected makes difference between real user vs scraper headless. If you are real user then only load this page for
