### ISSUE TITLE
[BUG] Incorrect status in afterAll

### ISSUE THREAD

**Issue by caribou-code** [microsoft/playwright#12728]
**Context:**
- Playwright Version: 1.17.1
- Operating System: Mac
- Node.js version: 14.18.1
- Browser: Chromium

**Code Snippet**

```typescript
import { test } from '@playwright/test';

test.describe.serial('Foo', async () => {
  test.afterAll(async ({}, { expectedStatus, status }) => {
    console.log({ expectedStatus });
    console.log({ status });
  });

  test('Bar', async () => {
    expect(true).toBe(false);
    throw new Error('Baz');
  });
});
```

**Describe the bug**

In the above example both `expectedStatus` and `status` log as `Passed` but I would expect `status` to be `Failed`.

**Comment by dgozman** [comment]
This was fixed for 1.21 in #12518.
