### ISSUE TITLE
[BUG]React selectors Component name contains Special characters

### ISSUE THREAD

**Issue by mchudie** [microsoft/playwright#12722]
### Your question

React selectors Unable to select components containing special characters
![](https://user-images.githubusercontent.com/7105278/158152835-4744508a-b5ac-4b9d-9801-c87b8a227a83.png)
![](https://user-images.githubusercontent.com/7105278/158153212-354c349c-4d22-4390-810a-1dbae587dec1.png)

**Comment by pavelfeldman** [comment]
Please provide steps to repro, your expectations and actual results!

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
