### ISSUE TITLE
[BUG] Online traceviewer random 404s

### ISSUE THREAD

**Issue by slang25** [microsoft/playwright#12725]
I've created a sample trace that I've been sharing to show off how cool Playwright is, however people are reporting that things like image thumbnails are randomly failing. After a little digging I can see that some of the service worker requests result in 404s.

You can try this yourself by refreshing this sample a few times and watching the service worker network requests:
https://trace.playwright.dev/?trace=https://pw-trace-demo.s3.eu-west-1.amazonaws.com/Search_For_DotNet_Core_chromium_macos_2022-03-08-00-24-44.zip

I'm unsure where exactly the problem lies, it could be in zip.js for example 🤔 Could be worth upgrading to the latest as there are a couple of fixes (not sure if they would resolve what we are seeing here).

![image](https://user-images.githubusercontent.com/1341446/158172138-614de0c1-4460-426d-a622-8eb6705be4fd.png)
![image](https://user-images.githubusercontent.com/1341446/158172157-8d891514-1f86-459e-a00e-c8ff848ded2b.png)

**Comment by pavelfeldman** [comment]
I can repro it via reloading several times and then scrubbing the preview.
