### ISSUE TITLE
[BUG] :text() selector documentation issue

### ISSUE THREAD

**Issue by dajunhuo** [microsoft/playwright#12732]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Windows
- .NET
- Browser: Chromium

**Code Snippet**

```javascript
#nav-bar :text("Home")
```

**Describe the bug**

The documentation for text selectors as seen in the URL https://playwright.dev/dotnet/docs/selectors#text-selector only worked for me if I remove the space between the element and the colon e.g.
```javascript
#nav-bar:text("Home")
```

Here's an example of what I was trying to select (with text censored)
![image](https://user-images.githubusercontent.com/51913090/158191950-30657f25-151e-4022-9bf1-9bba0172ab6d.png)

**Comment by pavelfeldman** [comment]
`#nav-bar:text("Home")` and `#nav-bar :text("Home")` are two different selectors with different semantics. First is looking for an element nav-bar that has given text, another is looking for nested elements inside navbar that have text.

You would typically say `#nav-bar:hasText("Home")` instead, or better yet `page.locator('#nav-bar', { hasText: 'Home' })`.
