### ISSUE TITLE
[Feature] Element screenshot crop option - stabilize visual regression by removing not important elements.

### ISSUE THREAD

**Issue by dz1dz1on** [microsoft/playwright#12730]
So I would like to have additional option in screenshot method which could add us possibility to crop a screenshot.
***Example***
- we are taking screenshot of the modal
- button on the modal has spinning animations in the time of the loading
- we don't care about button but we are interested in the content of the modal 
- problem is that our tool for screen comparison shows the difference between versions of the screenshots (master vs actual branch) because of the animation.

So it would help other people to stabilize visual regression tests by removing not important elements from the screenshot.

<img width="396" alt="image" src="https://user-images.githubusercontent.com/62831238/158187829-eeb2d82d-112c-4ff7-b83b-af376e3a2e3d.png">

It could be implemented similarly like test cafe did:
https://testcafe.io/documentation/402676/reference/test-api/testcontroller/takeelementscreenshot#header

It could look like that: 
```await page.locator('.header').screenshot({ path: 'screenshot.png' , crop: {top: number, left: number, right: number, bottom: number}});```

Where crop takes coordinate associated within an element.

**Comment by pavelfeldman** [comment]
Note that v1.20 will release today and it can do `page.screenshot({ mask: locator })` that hides elements with given locator.

**Comment by aslushnikov** [comment]
@dz1dz1on would the new `mask` API work for you?

**Comment by dz1dz1on** [comment]
@aslushnikov In this particular example I think it will work.

**Comment by aslushnikov** [comment]
> but when I have gallery of pictures and I want to have only 3 pics out of lets say 5 it would be easier with a crop option.

@dz1dz1on the `crop` option is identical to our [`clip` option](https://playwright.dev/docs/next/api/class-page#page-screenshot-option-clip)

Additionally:
- you can use both `mask` and `clip` options
- you can also use [`locator.screenshot()`](https://playwright.dev/docs/next/api/class-locator#locator-screenshot) to take a screenshot of the element you like. `mask` is also supported there

**Comment by dz1dz1on** [comment]
@aslushnikov Thanks. It will help for sure.
