### ISSUE TITLE
[Question] page.evaluate: Execution context was destroyed, most likely because of a navigation.

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#12737]
Hi, I need to load a token into indexedDB. I stored this token inside a .json file and now I need to load it inside my test page in order to skip authentication. I'm doing in this way:

```
        const auth = JSON.parse(await fse.readFile('auth.json','utf8')); 
        const browser = await chromium.launch({args: ['--allow-file-access-from-files']});
        const context = await browser.newContext(); 
        const page = await  context.newPage();
        await page.goto('*site URL*');

        await page.evaluate(async ({auth}) => {

            let worker = {};
            const JWTTOKENS = "jwtTokens";
            worker.jwt = new Promise((resolve, reject) => {
                const db = window.indexedDB.open("jwt", 10);
                db.onblocked = reject;
                db.onerror = reject;
                db.onupgradeneeded = event => event.target.result.createObjectStore(JWTTOKENS, { keyPath: "jti"});
                db.onsuccess = event => resolve(event.target.result);
            });

            return await new Promise(async (resolve, reject) => {
                const transaction = (await worker.jwt).transaction([JWTTOKENS], "readwrite");
                transaction.onerror = reject;
                transaction.objectStore(JWTTOKENS).put(auth).onsuccess = resolve;
            });
        }, auth);

```

but I'm getting this error:

`    page.evaluate: Execution context was destroyed, most likely because of a navigation.`

With `await page.goto('*site URL*');` I'm trying to access the login page in order to load the token. Then, without inserting anything,  just to have a try, I'd manually reload the page to see if the token has been loaded and to see if I'd be redirected to the home page (already logged in)

what could be the problem? Thank you..

**Comment by pavelfeldman** [comment]
Your page navigates concurrently while you are navigating. There is no easy way of injecting indexed db tokens for authentication due to the async nature of indexed db. Following will work, but it somewhat involved:

```js
// Stub network
await page.route('**/*', route => route.fulfill({ body: '<html></html>' });
// Navigate to the desired origin, it'll be blank due to above
await page.goto(myUrl);
// Inject IndexedDB tokens as in your script
await page.evaluate(...)
// Restore network
await page.unroute('**/*');
// Navigate for real
await page.goto(myUrl);
```

**Comment by DvDream** [comment]
Thank you for the hint! Actually, I noticed that I was not waiting enough to make the evaluate function, and since before the evaluation I didn't notice that there was a redirect, the error occurred.
