### ISSUE TITLE
[Question] Unable to copy into clipboard programmatically

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#12736]
**Context:**
- Playwright Version: 1.19.2
- Operating System: mac
- Node.js version: 14.6
- Browser: all

**Code Snippet**

```
        contextOptions: {
            permissions: ['clipboard-read']
        },
```

```
    test.only('Share property link', async ({ page }) => {
        await expect(await page.evaluate(() => navigator.clipboard.readText()))
            .toEqual("Some text");
    });
```

**Describe the bug**

```
    Error: expect(received).toEqual(expected) // deep equality

    - Expected  - 1
    + Received  + 8

    - Some text
    +     test.only('Share property link', async ({ page, propertyDetails }) => {
    +         await propertyDetails.clickOnCopyLink()
    +         await expect(await page.evaluate(() => navigator.clipboard.readText()))
    +             .toEqual("Some text");
    +     });

      42 |         await propertyDetails.clickOnCopyLink()
      43 |         expect(await page.evaluate(() => navigator.clipboard.readText()))
    > 44 |             .toEqual("Some text");
         |              ^
      45 |     });
      46 |
      47 |
```

**Comment by amrsa1** [comment]
update when i add in the config file the following

```
const config: PlaywrightTestConfig = {
    use: {
        baseURL: configList.baseURL,
        contextOptions: {
            userAgent: configList.userAgent,
            permissions: ['clipboard-read','clipboard-write','accessibility-events']
        },
    },
}

export default config;
```

i got output like that 

<img width="582" alt="Screenshot 2022-03-14 at 17 27 44" src="https://user-images.githubusercontent.com/32042806/158217047-4f2101fe-548d-4ddd-a2b9-277db1a766d9.png">

**Comment by pavelfeldman** [comment]
The fact that you see Received: "accessibility-events" suggests that it reads the value just fine (that's what was in your clipboard as you were updating the permissions value). But it fails to copy it. How do you copy value into the cilpboard?

**Comment by amrsa1** [comment]
Just click on the element that supposed to copy the url 


<img width="430" alt="Screenshot 2022-03-14 at 20 59 48" src="https://user-images.githubusercontent.com/32042806/158251386-956cda62-1217-4cd2-9005-9f02f6a858d0.png">

**Comment by pavelfeldman** [comment]
We need a self-contained repro that we can turn into a test in order to be able to act on this!

**Comment by amrsa1** [comment]
@pavelfeldman fixed by adding await before expect, and inside 

```
        await expect(await page.evaluate(() => navigator.clipboard.readText()))
            .toEqual(page.url());
    });
```
