### ISSUE TITLE
[Feature] add new option on junit reporter to use CDATA sections to encode content

### ISSUE THREAD

**Issue by bitcoder** [microsoft/playwright#12741]
Provide a new option on the junit reporter to control whether to use CDATA sections to encode text content in the JUnit XML elements.
This provides a safe mechanism to add content on elements, such as `<system-out>` and other that use inner text, where we don't control what the users provide. Parsers usually skip (i.e., don't pase) the contents of CDATA sections, taking out the start and ending CDATA sections delimiters.

**Comment by pavelfeldman** [comment]
Would you be open to sending a PR for this?

**Comment by bitcoder** [comment]
@pavelfeldman on its way, resolving a conflict

**Comment by bitcoder** [comment]
ready for review @pavelfeldman 
(note: I'm just waiting from a formal email from my org so I can sign the CLA; should come soon)

**Comment by pavelfeldman** [comment]
Assigning to Yury who is reviewing this PR.
