### ISSUE TITLE
[Question] Failing to open url with webkit in docker

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#12754]
Hello !

I'm trying to run playwright test in docker. It works well with Firefox and Chromium but not with webkit.

- Playwright: docker image mcr.microsoft.com/playwright:focal
- Operating System: [Linux - Ubuntu 20.04.4 LTS]
- Node.js version: [16.14.0]
- Browser: [Webkit]

It's a little test opening just a URL:

In my Before step:

```javascript
const playwright = require("playwright");

Before(async function () {
    const browserName = this.parameters.browser;

    this.browser = await playwright[browserName].launch({ headless: false, });

    const context = await this.browser.newContext({
        ignoreHTTPSErrors: true,
        viewport: null,
    });

    this.page = await context.newPage();
});
```

Then in my test:

```javascript
await this.page.goto(`https://${this.url}/workspace-application`);
```

**steps**:

Dockerfile:

```
FROM mcr.microsoft.com/playwright:focal

ENV {set_proxy}

COPY {some_files} app/

WORKDIR /app

RUN npm install

RUN npx playwright install-deps
```

```
docker build --tag playwright-docker .
docker run -it -d --name playwright-container playwright-docker /bin/bash
docker exec -it playwright-container /bin/bash
```

run tests inside
```
xvfb-run --auto-servernum npm run test-webkit
```

And I have this error:

`✖ Given I open login page on "10.135.253.114" # node_modules/....
       page.goto: Unknown error on connect
       =========================== logs ===========================
       navigating to "https://10.135.253.114/workspace-application", waiting until "load"`

**Comment by pavelfeldman** [comment]
It is hard for us to tell anything without an example that we can reproduce.

**Comment by kamelbou** [comment]
> It is hard for us to tell anything without an example that we can reproduce.

Ok. Let me try to setup something that you can use to reproduce the issue. Thanks a lot!

**Comment by kamelbou** [comment]
I close this issue as it's works well with version 1.20.0. Thank you !
