### ISSUE TITLE
[BUG] Unable to load a URL in version 1.20

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#12756]
**Context:**
- GOOD Playwright Version: 1.19.2
- BAD Playwright Version: 1.20.0
- Operating System: Mac

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test('example test', async ({ page }) => {
  await page.goto(<MY_URL>); //can share the url privately
});
```

**Describe the bug**
Navigating to MY_URL times out and reports the following error:
`Timeout of 20000ms exceeded while shutting down environment`

Note: Only happens with one specific URL(i.e. endpoint) and works fine for other endpoint.

**Comment by pavelfeldman** [comment]
User-provided log:

```
  pw:browser <launched> pid=75363 +320ms
  pw:browser [pid=75363][err] [0314/170609.932734:ERROR:ssl_client_socket_impl.cc(999)] handshake failed; returned -1, SSL error code 1, net_error -201 +13s
  pw:browser [pid=75363][err] [0314/170614.794563:ERROR:gl_utils.cc(319)] [.WebGL-0x4c06454000]GL Driver Message (OpenGL, Performance, GL_CLOSE_PATH_NV, High): GPU stall due to ReadPixels +5s
```

**Comment by aslushnikov** [comment]
@Nav-2D are you running on a M1 mac?

**Comment by Nav-2d** [comment]
@aslushnikov - Intel

**Comment by pavelfeldman** [comment]
Is this still happening? We don't see other reports on it.

**Comment by Nav-2d** [comment]
Hi Pavel, yes still seeing the same issue - local as well as docker

**Comment by Nav-2d** [comment]
Maybe related #11805 (same error)

**Comment by pavelfeldman** [comment]
@Nav-2d on Windows, same `GPU stall due to ReadPixels` error?

**Comment by Nav-2d** [comment]
@pavelfeldman - yes same GPU stall error

**Comment by pavelfeldman** [comment]
Nope, does not repro for me.

**Comment by Nav-2d** [comment]
Unable to reproduce GPU stall error but getting a new error which is tracked here: https://github.com/microsoft/playwright/issues/12930
