### ISSUE TITLE
[BUG] playwright errors out for elements that are not in the scope of execution

### ISSUE THREAD

**Issue by mahesh-narvar** [microsoft/playwright#12769]
**Context:** The Playwright is used with Jest
- Playwright Version: [what Playwright version do you use?] 1.17.2
- Operating System: [e.g. Windows, Linux or Mac] - Mac
- Node.js version: [e.g. 12.22, 14.6] - 14.6
- Browser: [e.g. All, Chromium, Firefox, WebKit] - Chromium
- Extra: [any specific details about your environment]

```
if (orderNumber) {
    console.log("Order Number is ",orderNumber);
    await this.updateOrderNumber(orderNumber);
    await this.doingScience();
    await this.page.waitForSelector(Constants.errorMessage);
    let errorMessagePresent = await this.page.locator(Constants.errorMessage).isVisible();
    console.log('Error Message Presense: ',errorMessagePresent);
    expect(errorMessagePresent).toBe(false);
    console.log('Successfully configured the Order Number');
}
```
**
In the test code, the orderNumber is set to an empty string which means I do not want this loop to be processed. When run I do not expect playwright+jest to process this loop and content within it. Constants.errorMessage is a locator that gets validated in this case when the code is run.

locator.isVisible: Target closed
=========================== logs ===========================
checking visibility of "div.VisualizationErrorstyled__QueryErrorIcon-rf96yi-1.glUaZz"

The visibility it is trying to check is of the locator declared in Constants.errorMessage. If the loop itself is not getting executed, why should Playwright/Jest error out for what is not in the scope of execution?
**

Any suggestions here would help.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
