### ISSUE TITLE
[Question] Requires a shared context ，communication by storage

### ISSUE THREAD

**Issue by rr13k** [microsoft/playwright#12767]
I want to open two browsers, their pages need to share session, how to do this? need to trigger between them
window.addEventListener("storage"

i try to lock --user-data-dir,but it not work.

'\n==================== Browser output: ====================\n<launching> /Users/renran/Library/Caches/ms-playwright/chromium-976882/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm…ent --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --enable-use-zoom-for-dsf=false --no-sandbox --remote-debugging-pipe --no-startup-window\n<launched> pid=24293\n[pid=24293][out] 正在现有的浏览器会话中打开。'

help me.

**Comment by pavelfeldman** [comment]
Sorry, it is unclear what you need. Please provide a short repro in code or some pseudo code, along with your expectations and actual results!

**Comment by rr13k** [comment]
I need to open both browsers, and they will open the same page. In a normal browser, their pages can communicate by listening for `storage` changes. Now,  we can't do that because  `playright`  each browser uses a different `user-data-dir` path.
If you delete the specified `user-data-dir` when starting the browser, you get the above error

**Comment by rr13k** [comment]
The expected result is that two browsers are opened and can communicate with each other through the `Listener storage`

**Comment by rr13k** [comment]
```js
//@ts-check
import { chromium } from 'playwright';

(async () => {
  const context1 = await chromium.launchPersistentContext('/Users/renran/work/test', {
    args: ['--remote-debugging-port=9222'],
    headless: false,
    userAgent: 'Some Overriden User Agent',
  });

  const pageOne = await context1.newPage();
  await pageOne.goto('https://baidu.com');


  const context2 = await chromium.launchPersistentContext('/Users/renran/work/test', {
    args: ['--remote-debugging-port=9222'],
    headless: false,
    userAgent: 'Some Overriden User Agent',
  });

  const pageTwo = await context2.newPage();
  await pageTwo.goto('https://baidu.com');

  // await browser2.close();
  // await context1.close();
})();
```

Expect code that works, but it's not hard

any help，thank you

**Comment by pavelfeldman** [comment]
You can't open two browsers using the same profile. It will look like you opened them, but in reality it is the same browser. So no need to open twice. Also no need to use persistent profile, just use two pages in the same context. See https://playwright.dev/docs/pages#multiple-pages.

**Comment by rr13k** [comment]
hi, I need to access two pages persistently, but one of them must be hidden, I want to hide one of them through two browsers, if it is a page, can I hide it?

**Comment by rr13k** [comment]
<img width="962" alt="截屏2022-03-17 上午10 13 30" src="https://user-images.githubusercontent.com/45162461/158722854-d5a04565-3494-46a1-9a36-979491eb9b6c.png">
Any way to hide the page？
this options is miss

**Comment by pavelfeldman** [comment]
No way to hide it, no. Let me fold your request into an existing feature request: https://github.com/microsoft/playwright/issues/3570
