### ISSUE TITLE
[Question] How to get Total, Passed, Failed, Skipped test cases count in custom reporter.

### ISSUE THREAD

**Issue by shubhamkgupta14** [microsoft/playwright#12768]
Hello Team

I have a question while generating the custom reporter. I have create a custom reporter class - MyReporter.ts

"playwright": "^1.20.0"
"typescript": "^4.6.2"

`
  onEnd(result): void {
    console.log("\nFinished the run : " + result.status + "\n"`);
  }
`

I want to print Total, Pass, Fail and Skip counts at the end of running i.e onEnd() function.

Thanks

**Comment by Nav-2d** [comment]
You can do something along these lines:
```
onBegin(config, suite) {
    this.config = config;
    this.suite = suite;
}
async onEnd() {
    let passedCount = 0;
    let passedTestsList = [];
    const projectSuites = this.suite.suites;
    projectSuites.forEach((project) => {
      project.allTests().forEach((test) => {
        test.results.forEach((result) => {
          console.log(result.status);
            passedCount = passedCount + 1;
            ....
            ....
```

**Comment by deepthymahalingam1** [comment]
@pavelfeldman @Nav-2d How will this work when there are test retries? I have my tests running on ci, no. of retries is 3. My custom report shows inaccurate numbers when there are retries, every retry failure adds to the count.

**Comment by Nav-2d** [comment]
@deepthymahalingam1 - You probably want to handle the logic for retry runs. For example:

```
 if (result.retry < test.retries) {
      totalCount++;
}
```
```
if (result.retry < test.retries) {
       retryCount = retryCount + 1;
} 
```
Ref: https://playwright.dev/docs/api/class-testcase#test-case-retries and https://playwright.dev/docs/api/class-testresult#test-result-retry
