### ISSUE TITLE
[BUG] Playwright cannot find executables for all browsers in test runs this morning; no code changed over several days.

### ISSUE THREAD

**Issue by ShaneYu** [microsoft/playwright#12772]
**Context:**
- Playwright Version: 1.20.0
- Operating System: Windows and Linux (via docker container)
- Node.js version: 16.13.0
- Browser: All

## System:
 - OS: Windows 10 10.0.19043
 - Memory: 12.32 GB / 31.73 GB
## Binaries:
 - Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
 - npm: 8.1.3 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

No code snippet required, bug appears to be related to Playwright and it's browsers that are installed; not a code bug.

**Describe the bug**

We have many UI projects that use Playwright to do integration and end-to-end testing that were fine up until sometime this morning. No code changes what so ever, just building existing code as it stood over the last several days.

This morning all of the UI builds (which use your Playwright docker images) are failing, stating it cannot find executable for the browser, see below...

```
1) [chromium] › app.spec.ts:64:1 › Example form integration ======================================
--
  |  
  | browserType.launch: Executable doesn't exist at /ms-playwright/chromium-965416/chrome-linux/chrome
  | ╔═════════════════════════════════════════════════════════════════════════╗
  | ║ Looks like Playwright Test or Playwright was just installed or updated. ║
  | ║ Please run the following command to download new browsers:              ║
  | ║                                                                         ║
  | ║     npx playwright install                                              ║
  | ║                                                                         ║
  | ║ <3 Playwright Team                                                      ║
  | ╚═════════════════════════════════════════════════════════════════════════╝
  |  
  |  
  |  
  |  
  | 2) [firefox] › app.spec.ts:64:1 › Example form integration =======================================
  |  
  | browserType.launch: Executable doesn't exist at /ms-playwright/firefox-1316/firefox/firefox
  | ╔═════════════════════════════════════════════════════════════════════════╗
  | ║ Looks like Playwright Test or Playwright was just installed or updated. ║
  | ║ Please run the following command to download new browsers:              ║
  | ║                                                                         ║
  | ║     npx playwright install                                              ║
  | ║                                                                         ║
  | ║ <3 Playwright Team                                                      ║
  | ╚═════════════════════════════════════════════════════════════════════════╝
  |  
  |  
  |  
  |  
  | 3) [webkit] › app.spec.ts:64:1 › Example form integration ========================================
  |  
  | browserType.launch: Executable doesn't exist at /ms-playwright/webkit-1609/pw_run.sh
  | ╔═════════════════════════════════════════════════════════════════════════╗
  | ║ Looks like Playwright Test or Playwright was just installed or updated. ║
  | ║ Please run the following command to download new browsers:              ║
  | ║                                                                         ║
  | ║     npx playwright install                                              ║
  | ║                                                                         ║
  | ║ <3 Playwright Team                                                      ║
  | ╚═════════════════════════════════════════════════════════════════════════╝
```

When running the tests locally with `npx playwright test` without using your Playwright docker images, it still fails the same way. I attempted to run `npx playwright install` as suggested in the error messages above, following this Chromium and Firefox work fine, however webkit fails all tests stating that it is unable to fine elements (running it headed, the page is blank and nothing is loading).

Unable to find any issues relating to this issue I want to know if there is ongoing problems being resolved as we speak, how long that will be and if there are any work around(s) at the moment?

**Comment by ShaneYu** [comment]
It is worth noting that I was able to downgrade the version of Playwright to 1.19.2 and everything works find again. So my work around at the moment locally is to use 1.19.2 and will use a older version of the docker image.

Was there anything breaking that was not detailed in the latest release notes?

**Comment by llam15** [comment]
+1, we used the `focal` image yesterday at 5pm ET, which worked. Nothing has changed since then and it failed today at 10m ET

**Comment by pavelfeldman** [comment]
It is trying to tell you what happened, you are now on Playwright v1.20 and you need new browsers every time Playwright is updated.

<img width="549" alt="Screen Shot 2022-03-15 at 11 12 12 AM" src="https://user-images.githubusercontent.com/883973/158444195-85fb6886-4ce4-423b-bbbf-0e3ff1c97f86.png">

**Comment by aslushnikov** [comment]
What docker images do you use? Do you use versioned docker images?

For playwright v1.20.0, you should use docker image `mcr.microsoft.com/playwright:v1.20.0-focal`

**Comment by llam15** [comment]
We are running in Circle CI with the following image:
```
docker:
      - image: mcr.microsoft.com/playwright:focal
```

previously we have never needed to run any update commands on this docker image?

**Comment by pavelfeldman** [comment]
My understanding is that this depends on your docker registry cache. If you have 1.19 cached, it'll be serving it and you'll be getting the mismatch.

**Comment by ShaneYu** [comment]
> mcr.microsoft.com/playwright

We've been using the image `mcr.microsoft.com/playwright` with no version or `focal` etc. I've looked into it and we do cache the docker images, however I am told that it is meant to pull and re-cache when there is a newer version; I am looking into this now to make sure that is indeed the case.

Is there a particular reason you would want to use a `focal` one over just `mcr.microsoft.com/playwright`?

**Comment by ShaneYu** [comment]
Just in case it helps, we use [JFrog Artifactory](https://jfrog.com/artifactory/) when getting our docker images which then caches them if they've not been fetched before; we do this mainly due to the limitations Docker have put in place that prevents too many pulls within a given time window; being a business using docker containers for most of our projects we obviously hit that limit quickly.

I switched the container to use the  `playwright:focal` one and it's no longer complaining about browser executable(s) not existing; it looks as though we've not pulled the focal image tag prior to now, so we could have a caching issue as you've suggested.

The only issue I am facing now is the other point I mentioned in my original post(s) whereby webkit fails ALL tests but Chrome and Firefox are fine (again no code change, yet it fails now); assume this should be treated as a separate issue so happy to raise one for it rather than polluting this one?

**Comment by llam15** [comment]
> My understanding is that this depends on your docker registry cache. If you have 1.19 cached, it'll be serving it and you'll be getting the mismatch.

Possibly but looking at the circle ci logs, it looks to be pulling different images

Failing builds are using SHA `9a72a2ef95fdca5317f62d5c5bd8ed7d6ae9231691a12b8f5d4b8b4a2e0828f4`
```
Starting container mcr.microsoft.com/playwright:focal
  image cache not found on this host, downloading mcr.microsoft.com/playwright:focal
focal: Pulling from playwright

88808835: Already exists 
92e537a3: Pulling fs layer 
8623e2ae: Pulling fs layer 
Digest: sha256:9a72a2ef95fdca5317f62d5c5bd8ed7d6ae9231691a12b8f5d4b8b4a2e0828f4.5MB/521.5MBB
Status: Downloaded newer image for mcr.microsoft.com/playwright:focal
mcr.microsoft.com/playwright:focal:
  using image mcr.microsoft.com/playwright@sha256:9a72a2ef95fdca5317f62d5c5bd8ed7d6ae9231691a12b8f5d4b8b4a2e0828f4
  pull stats: download 650.5MiB in 4.139s (157.1MiB/s), extract 650.4MiB in 12.775s (50.91MiB/s)
  time to create container: 941ms
Time to upload agent and config: 391.219005ms
Time to start containers: 398.938778ms
```

Passing builds were using SHA `3d36197320f4f77b062a7973e99406d10a436e11706eddebde6be08836bfe5d1`
```

Starting container mcr.microsoft.com/playwright:focal
  image cache not found on this host, downloading mcr.microsoft.com/playwright:focal
focal: Pulling from playwright

1a0ec47e: Already exists 
c6b55191: Pulling fs layer 
f0e50188: Pulling fs layer 
Digest: sha256:3d36197320f4f77b062a7973e99406d10a436e11706eddebde6be08836bfe5d1.2MB/516.2MBB
Status: Downloaded newer image for mcr.microsoft.com/playwright:focal
mcr.microsoft.com/playwright:focal:
  using image mcr.microsoft.com/playwright@sha256:3d36197320f4f77b062a7973e99406d10a436e11706eddebde6be08836bfe5d1
  pull stats: download 641.8MiB in 10.85s (59.15MiB/s), extract 641.8MiB in 11.337s (56.61MiB/s)
  time to create container: 5.987s
```

**Comment by llam15** [comment]
I re-ran the CircleCI Job with SSH to check out what's going on, but it looks like the chromium version that playwright is looking for does not match what is installed in the docker container (Note we also tried running `playwright install`, and that did not do anything)

Specifically, the error message states
```
Executable doesn't exist at /ms-playwright/chromium-965416/chrome-linux/chrome
```

And running `ls /ms-playwright` in the docker container returns
```
chromium-978106  ffmpeg-1007  firefox-1319  webkit-1616
```

**Comment by llam15** [comment]
Looks like the directory in the image is just named incorrectly, if we rename the `/ms-playwright/chromium-978106` directory to  `/ms-playwright/chromium-965416`  then the tests run properly

**Comment by dangayle** [comment]
We ran into this same issue today on localhost builds of the Dockerfile using `mcr.microsoft.com/playwright:focal`

**Comment by pavelfeldman** [comment]
Please make sure you always pin your docker images like so:

`mcr.microsoft.com/playwright:v1.20.0-focal`

**Comment by dangayle** [comment]
> Please make sure you always pin your docker images like so:
> 
> `mcr.microsoft.com/playwright:v1.20.0-focal`

Could the docs be updated then?

**Comment by Arianna2028** [comment]
In case any future readers are wondering, I'd like to document here what was never actually stated in the short responses to this issue.

Each Docker image includes browsers in a unique location, e.g. `/ms-playwright/chromium-965416` for one version, or `/ms-playwright/chromium-1000` for another.

Each version of the Playwright package seems hardcoded to point to that particular location.

Because of this, your installed Playwright package version _must_ match your Docker image version. If it doesn't, when the tests are run, they will use the wrong location for the browser, and it will not be found.

Pinning the Docker image is the solution here to ensure those two versions don't accidentally become out of sync.

**Comment by dangayle** [comment]
Thank you! This is a far more useful answer. Can we have this added to the
documentation?
