### ISSUE TITLE
[Question] Downloading pdf file

### ISSUE THREAD

**Issue by VinayKumarBM** [microsoft/playwright#12777]
In the application that I'm testing, when I click a 'Finish' button it opens pdf file in the pdf viewer instead of directly downloading.

The navigated URL will look like this: [http://01.27.103.32:8080/ream/reports/Report?Id=300215&saveAsAttachment=n&bin](http://01.27.103.32:8080/ream/reports/Report?Id=300215&saveAsAttachment=n&bin)

I have gone through few of the issues that was opened before and tried to implement it, but with no luck. 

I have tried to merge all the options that I have tried for this in below code. 
Can you please let me know where I'm going wrong.

`await page.$eval('text=Finish', (el) => {
    el.setAttribute('download', 'download');
  });`
  `const [download] = await Promise.all([`
`    page.waitForEvent('download'),`
`    //await page.route('**\/**', route => route.abort()), <--- This blocked the opening in pdf viewer, but it did not download the file `
`    await page.locator('text=Finish').click({ modifiers: ["Alt",] }),
  ]);`

**Comment by pavelfeldman** [comment]
Check out this page for workarounds: https://github.com/microsoft/playwright/issues/6342#issuecomment-929112605

**Comment by VinayKumarBM** [comment]
@pavelfeldman : I looked into the workaround but that issue was for headless mode, I'm running in headed mode and I get pdf viewer. I want to avoid that and instead it should download the file. As I need to validate the content of pdf file.

Do we have any option to block pdf viewer from coming. In Selenium we can use plugins.always_open_pdf_externally chrome option to do that. Can we do something similar to that in Playwright?

**Comment by JotFe** [comment]
Hello @VinayKumarBM! Maybe this can help you  [https://github.com/microsoft/playwright/issues/3509?](url):
If you find a solution for Python please let me know ;)

**Comment by chen1tian** [comment]
you can download file using 'ALT + click link', so we can create a html file to download, like thie:

```python
from playwright.sync_api import Page
import os
from pyclbr import Function


def download_urls(page: Page, urls: [], tmp_dir: str = '/tmp/', tmp_file_name: str = 'tmp_download.html',
             on_downloaded: Function = None):
    # gen tmp html file
    html_links = []
    for url in urls:
        html_links.append(f'<a href="{url}">{url}</a>')
    tmp_html = f"""<html><body>{''.join(html_links)}</body></html>"""

    file = os.path.realpath(__file__)
    tmp_dir = os.path.dirname(os.path.realpath(file)) + tmp_dir
    if not os.path.exists(tmp_dir):
        os.mkdir(tmp_dir)
    filename = tmp_file_name
    tmpfile_path = tmp_dir + filename
    with open(tmpfile_path, 'w', encoding='utf8') as f:
        f.write(tmp_html)

    # use tmp html to download
    page.goto("file://" + tmpfile_path)

    for link in page.query_selector_all('//a'):
        url = link.get_attribute('href')
        print('download starting:', url)
        with page.expect_download() as download_info:
            link.click(modifiers=["Alt", ])

        download = download_info.value

        download_dir = os.path.dirname(download.path())
        download_filename = download.url.split('/')[-1]

        download_filepath = os.path.join(download_dir, download_filename)
        os.rename(download.path(), download_filepath)

        print('download saved to:', download_filepath)

        if on_downloaded is not None:
            on_downloaded(download_filepath, url)

```

**Comment by imodoiepale** [comment]
**1. run playwright code generator on your terminal**
```powershell
playwright codegen
``` 
**2.click the button you are using to download the pdf in the code generator**

**3.from the codegenerator- choose your language and copy the role of the button/ **Simply use the Selector from Inspection****

**4. append the modifier..in this case**
```powershell
{modifiers: ['Alt']}
``` 

**5. save the download with name and specific path**
```powershell
await download.saveAs("file.pdf")
``` 

```javascript
//  Function to save pdf download

await page.getByRole('link', { name: 'Print Receipt' }).click({modifiers: ['Alt']});
const downloadPromise = page.waitForEvent("download")
const downloadedFile = await downloadPromise;

//Save the downloaded document
await download.saveAs("file.pdf");
``` 

> @pavelfeldman : I looked into the workaround but that issue was for headless mode, I'm running in headed mode and I get pdf viewer. I want to avoid that and instead it should download the file. As I need to validate the content of pdf file.
> 
> Do we have any option to block pdf viewer from coming. In Selenium we can use plugins.always_open_pdf_externally chrome option to do that. Can we do something similar to that in Playwright?

**Comment by yonglee7015** [comment]
> In the application that I'm testing, when I click a 'Finish' button it opens pdf file in the pdf viewer instead of directly downloading.
> 
> The navigated URL will look like this: [http://01.27.103.32:8080/ream/reports/Report?Id=300215&saveAsAttachment=n&bin](http://01.27.103.32:8080/ream/reports/Report?Id=300215&saveAsAttachment=n&bin)
> 
> I have gone through few of the issues that was opened before and tried to implement it, but with no luck. 
> 
> I have tried to merge all the options that I have tried for this in below code. 
> Can you please let me know where I'm going wrong.
> 
> `await page.$eval('text=Finish', (el) => {
>     el.setAttribute('download', 'download');
>   });`
>   `const [download] = await Promise.all([`
> `    page.waitForEvent('download'),`
> `    //await page.route('**\/**', route => route.abort()), <--- This blocked the opening in pdf viewer, but it did not download the file `
> `    await page.locator('text=Finish').click({ modifiers: ["Alt",] }),
>   ]);`

Have you finally get your code worked, I have the same issue

**Comment by SomeBottle** [comment]
This blog post is really helpful: https://pixeljets.com/blog/how-do-download-pdf-in-playwright/  

And there are also similar APIs from python playwright package: https://playwright.dev/python/docs/api/class-page
