### ISSUE TITLE
[BUG]   TypeError: _Component.Component is not a constructor

### ISSUE THREAD

**Issue by klassm** [microsoft/playwright#12770]
**Context:**
- Playwright Version: 1.20.0
- Operating System: Linux, Mac
- Node.js version: Node 16.13.0
- Browser: Only tried on Chrome

## System:
 - OS: macOS 12.2.1
 - Memory: 23.14 GB / 64.00 GB
## Binaries:
 - Node: 16.13.0 - /var/folders/rr/421993y578z70672kx_rj2m80000gn/T/fnm_multishells/50867_1647329804086/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.1.0 - /var/folders/rr/421993y578z70672kx_rj2m80000gn/T/fnm_multishells/50867_1647329804086/bin/npm
## Languages:
 - Bash: 5.1.12 - /usr/local/bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
  guiTest.only('bla', async ({ page }) => {
    console.log(Abc);
    new Abc(page);
  });
```

**Describe the bug**

Since Playwright 1.20.0 we get weird behaviour when importing external classes (no matter whether they are exposing a default export or just export the class itself). 
For some classes we suddenly get `TypeError: _Abc.Abc is not a constructor`. The interesting part is - this does not happen for all classes. Usually it just works. We also tried to figure out the difference on when it works or not - but we failed. Even when copying the exact same content to a different file, it suddenly starts working.

With Playwright 1.19.2 this still worked...

Maybe you have an idea what could be the reason?

Thanks

**Comment by jk-clarabridge** [comment]
@klassm did you find a solution to this? I'm having this exact same issue but you closed it without any notes 🤣
