### ISSUE TITLE
[Question] Using WebSockets 

### ISSUE THREAD

**Issue by guillaumemeunier** [microsoft/playwright#12771]
In the documentation, I can see that Playwright has a Websocket class (https://playwright.dev/docs/api/class-websocket) but I can't figure out how to use it as there is no example provided. 

What I'm trying to do is to execute a test with two browser sessions and one session would wait for a certain WebSocket before performing some actions. I would prefer to use Websocket to avoid any flakiness. Do you have some examples of a test showing how to listen/wait for some WebSockets?

**Comment by guillaumemeunier** [comment]
Thank you @pavelfeldman , I will check that out 😌

**Comment by pavelfeldman** [comment]
Closing as per above!
