### ISSUE TITLE
[BUG] Multiple type commands in one Promise.all do not resolve correctly

### ISSUE THREAD

**Issue by kapros** [microsoft/playwright#12776]
**Context:**
- Playwright Version: 1.91.1
- Operating System: all
- Node.js version: 14.17.6, possibly all
- Browser: chromium
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
        const  browser = chromium.launch( { headless: false });
        const page = await browser.newPage();
        await page.goto('https://sentry.io/auth/login/');
        await Promise.all([
            page.locator('button').first().click(),
            page.locator('[name="username"]').fill('user'),
            page.locator('[name="password"]').fill('pass')
        ]);
})();
```

**Describe the bug**

It appears that if one Promise.all holds many promises that use the `fill` command, they do not resolve correctly and only one, in this case the password fill command, is successfully types the content into the field. No errors are thrown, it's just the content is never typed. It appears to be specific to `type` because the `click` command works in this example.

**Comment by pavelfeldman** [comment]
It would be as if 3 people connected 2 keyboards and 1 mouse to the computer and started clicking and typing simultaneously. You are observing the result of this team work!
