### ISSUE TITLE
[Feature] Open the same HTML report window instead of a new one all the time

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12778]
```
const x = require("react-dev-utils/openBrowser")

x("https://demo.playwright.dev/")
```

magic: https://github.com/facebook/create-react-app/blob/main/packages/react-dev-utils/openBrowser.js

**Comment by pavelfeldman** [comment]
I'm not sure we want this, you sometimes want to compare previous result to the last one.
