### ISSUE TITLE
playwright how to connect chrome remote-debugging-port [Question]

### ISSUE THREAD

**Issue by PalaChen** [microsoft/playwright#12782]
chrom
```
chrome.exe --remote-debugging-port=9222 --user-data-dir="H:\selenium"
```
playwright how to connect to chrome.exe 

i need to test playwright,but now playwright finish task,close browser
test next task, need restart open browser and login, if i not save cookie

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp
