### ISSUE TITLE
[internal] Firefox sends events twice sometimes

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#12789]
Repro:

```py
from twisted.web import server, resource, http
from twisted.internet import reactor

class Simple(resource.Resource):
    isLeaf = True
    def render_GET(self, request: http.Request):
        print(f"{request.method} {request.uri}")
        if request.uri == b"/":
            request.setHeader(b"content-type", b"text/html")
            return b"<link rel='stylesheet' href='./one-style.css'>"
        elif request.uri == b"/one-style.css":
            request.setHeader(b"content-type", b"text/css")
            return b"body { background: red; }"
        else:
            request.setResponseCode(404)
            return b"404"

site = server.Site(Simple())
reactor.listenTCP(8080, site)
reactor.run()
```

`pip install twisted`

https://pypi.org/project/Twisted/

Confirmed on Firefox Nightly too.

**Comment by aslushnikov** [comment]
Upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1759738

**Comment by aslushnikov** [comment]
Upstream bug is confirmed so nothing to do on our side now. Once it's fixed upstream we'll roll to a new version!

**Comment by hsivonen** [comment]
> Upstream bug is confirmed so nothing to do on our side now.

If you want to avoid the extra request right now, you can add the `charset` parameter. E.g. `request.setHeader(b"content-type", b"text/html; charset=utf-8")` (if your encoiding is actually UTF-8).

**Comment by emilio** [comment]
To be clear, just `<meta charset=utf-8>` in the HTML would also work.
