### ISSUE TITLE
[BUG] `popup` is not emitted when parent closes early

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#12805]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Linux
- Node.js version: v16.13.0
- Browser: Chromium, Firefox

I'm storing some data per main page in a `WeakMap`. All the descendants point to the opener's data as well. Due to this bug, the opener is missing hence the data is inaccessible.

**Code Snippet**

```javascript
const playwright = require('playwright');

require('http').createServer((request, response) => {
        response.end(`
                <script>
                const lt = String.fromCharCode(60);
                const gt = String.fromCharCode(62);

                let w = window.open();
                w.document.open();
                w.document.write(
                        lt + "script" + gt +
                        "window.open('https://www.google.com/')" +
                        lt + "/script" + gt
                );
                w.document.close();
                w.close(); // comment this and popup gets emitted twice as expected
                </script>
        `);
}).listen(8888);

(async () => {
        const browser = await playwright.chromium.launchPersistentContext('', {
                headless: false,
        });

        browser.on('page', (page) => {
                console.log('page', page.url(), page._opener && page._opener.url());

                page.on('popup', (popup) => {
                        console.log('popup', popup.url(), popup._opener && popup._opener.url());
                });
        });

        const page = await browser.newPage();
        await page.goto('http://localhost:8888/');
})();
```

**Describe the bug**

I found an edge case - if we open a new window (which opens another one) and immediately close it, the another one will not be emitted as `popup` (opener is missing).

**Expected**

```diff
page about:blank null
page about:blank http://localhost:8888/
popup about:blank http://localhost:8888/
page https://www.google.com/ about:blank
+popup https://www.google.com/ about:blank
```

**Actual**

```diff
page about:blank null
page about:blank http://localhost:8888/
popup about:blank http://localhost:8888/
-page https://www.google.com/ null
+page https://www.google.com/ about:blank
```

**Comment by pavelfeldman** [comment]
If you add 
```js
                page.on('close', (page) => {
                        console.log('close', page.url());
                });
```
into your script, you'll see that Popup1 is closed before Popup2 is created.

- window.open('https://www.google.com/'); - schedules the navigation (async)
- w.close() - immediately closes the window (sync)

What would be your expectations?

**Comment by pavelfeldman** [comment]
I guess you are missing the opener in this google popup and we could try returning the closed about:blank page instance in that case for you to be able to restore the connection. As you can see from the code, we can expose sync opener, we just did not have a use case for that.

**Comment by szmarczak** [comment]
> I guess you are missing the opener in this google popup

Yes, sorry for not clarifying this earlier. My use case is to assign data to pages on-the-go via a WeakMap. `context.newPage` is one of the many ways to create pages, but `window.open` (which can be ran by a script) is another etc.

**Comment by pavelfeldman** [comment]
Would you be open to taking a stab at it? We are unlikely to prioritize it, but happy to review the patch.

**Comment by pavelfeldman** [comment]
Closing to send a signal that it won't be fixed by the core team!
