### ISSUE TITLE
[BUG] Infinite loop when calling `storageState` on page close

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#12809]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Linux
- Node.js version: v16.13.0
- Browser: Chromium, Firefox

**Code Snippet**

```javascript
const playwright = require('playwright');

require('http').createServer((request, response) => {
        response.end('');
}).listen(8888);

(async () => {
        const browser = await playwright.chromium.launchPersistentContext('', {
                headless: false,
        });

        browser.on('page', (page) => {
                page.on('close', async () => {
                        const state = await browser.storageState();

                        // console.log(state);
                });
        });

        const page = await browser.newPage();
        await page.goto('http://localhost:8888/');
        await page.close();
})();
```

**Describe the bug**

New pages keep opening and closing indefinitely. That's because of the current implementation: https://github.com/microsoft/playwright/blob/964eeba0dc3934f0d57f7ed0e209992c53ba9027/packages/playwright-core/src/server/browserContext.ts#L349

**Comment by pavelfeldman** [comment]
Looks like a real bug. It sounds like you are implementing some kind of har-alike recorder. Check out our har implementation, maybe it works for you out of the box.
