### ISSUE TITLE
[BUG] E2E test is failing in pipeline and Trace is not loading

### ISSUE THREAD

**Issue by shahabkhan12342** [microsoft/playwright#12819]
**Context:**
- Playwright Version: [1.19]
- Operating System: [Windows]
- Node.js version: [14.17.3]
- Browser: [Chrome]

I am facing this problem , whenever I run E2E tests in a pipeline, some of them fails in beginning while loading the application in first attempt and then passed in second attempt and that test becomes flaky, As you can see in below screenshot of trace file, trace file is also not loading and showing "Action does not have snapshots".

![tttt](https://user-images.githubusercontent.com/46971803/158576134-9a979c36-dd40-4e61-873b-932add345755.png)

Trace File is also attached below:

[traceFile.zip](https://github.com/microsoft/playwright/files/8261554/traceFile.zip)

**Comment by pavelfeldman** [comment]
Do you use `storageState`? We would also need some kind of repro to act on it.

**Comment by shahabkhan12342** [comment]
@pavelfeldman yes we do use 'storageState' using  identifyService.continueLoginIfStateExists()
         public continueLoginIfStateExists(){

        if (FileService.fileExistsSync("state.json")){           
           test.use({ storageState: 'state.json' });
        }      
    }

and also we have extended test configuration for it as below:
let test = base.extend<{},TestInfo>({
  page: async ({page, browser,  viewport, contextOptions }, use ,testInfo ) => {
    Driver.testInfo = testInfo;    
    Driver.browser = browser;      
    Driver.browserOptions = contextOptions;  
    
    await ContextService.initialize();        
    await use(page);
  }, 


Also we use Driver class for where we access our common methods, syntax of driver class is shown below:

export class Driver {
public static async mouseClick(x:number,y:number)
    {
        await Driver.getPage().mouse.click(x,y);
    } 
}

**Comment by Nhc007** [comment]
We are also facing same issues sometime while executing the tests in pipeline we also work on same principles and patters as you are using.

**Comment by piotrpawlik** [comment]
I'm facing same issue most probably. We are also using `storageState`. 
When running this test:
```
test.use({ storageState: 'storageState1.json' })

for (let i = 0; i < 100; i++) {
  test(`reach url for ${i} time`, async ({ page }) => {
    console.log(`reach url for ${i} time`)
    await page.goto('/')
    expect(page.url()).toMatch('outDomain.com')
  })
}
```
with and without `test.use({ storageState: 'storageState1.json' })` it always fails ~2-3 times when using `storageState` and never fails when not using it.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
