### ISSUE TITLE
[Question] Select option not working for below dom

### ISSUE THREAD

**Issue by jithintill** [microsoft/playwright#12813]
**Context:**
- Playwright Version: 1.20

DOM 
![Screen Shot 2022-03-16 at 5 14 44 pm](https://user-images.githubusercontent.com/98723817/158528927-5c3cfb12-071c-406f-8e56-72bc028408a4.png)

```javascript
await page.selectOption('select#paymentType', 'Debit');
 

```

**Describe the bug**

I have tried to use selectOption as shown above for the above dom as per the doc
https://playwright.dev/docs/input#select-options

it didn't worked, finally i have to type in the specific option as shown below to select an option.
Is this an issue or the specific select option i am using is wrong

paymentOption = this.page.locator(`select#paymentType`)
await this.paymentOption.type('Debit')

**Comment by pavelfeldman** [comment]
```js
await page.selectOption('select#paymentType', { label: 'Debit' });
```

as per the docs if you want to select by the label.
