### ISSUE TITLE
[Feature] Configurable Default Timeout for Web-First Assertions

### ISSUE THREAD

**Issue by uchagani** [microsoft/playwright#12824]
With node we are able to set the default timeout for web-first assertions via [config](https://playwright.dev/docs/test-timeouts#set-expect-timeout-in-the-config).  This is not possible in other language bindings.  We would like to be able to configure the default timeout.

Use case:

By default, playwright waits 30 seconds for a locator to be ready.  This implicit timeout is enough for most cases.  However when using these same locators in a web-first assertion with a default timeout of the current 5 seconds, the tests will fail and the implicit locator timeout is ignored.  

Workarounds:

1.  Add timeout to every assertion.  This is cumbersome and leads to a poor developer experience.

```java
// Wait 10 seconds for the locator to show up.
assertThat(someLocator).isVisible(new LocatorAssertions.IsVisibleOptions().setTimeout(10000));
```

2.  Call `waitFor()` before every assertion.  This again leads to a poor developer experience and in some cases leads to double testing the same thing.  if `waitFor` fails the assertion is never executed and if `waitFor` succeeds then the assertion will also succeed.  

```java
someLocator.waitFor();
assertThat(someLocator).isVisible();
```

I took a shot at [implementing](https://github.com/microsoft/playwright-java/pull/855) this for Java but I understand it needs to be applicable to the rest of the language bindings too.

**Comment by pavelfeldman** [comment]
This makes sense. Web-first assertions are language-specific, so we don't need to track them from a single location, you can proceed with your Java work and someone could pick it up / mirror it in other ports.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
