### ISSUE TITLE
[Question] How to clear all the data in the text field?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#12828]
I have been trying to clear all the data in the text field. `await this.page.keyboard.press('Backspace');` works for me but it deletes only one character. Is there any other way to clear the whole field? OR Do i need to run this `backspace` in a loop to clear characters one by one?

**Comment by gauravgandhi1315** [comment]
It would be good to have `.clear`

**Comment by pavelfeldman** [comment]
.fill('') clears it

**Comment by gauravgandhi1315** [comment]
> I tried it but didn't work me. `''` didn't fill anything

**Comment by gauravgandhi1315** [comment]
@unlikelyzero Is it possible to select all text using playwright? I didn't know. I tried to google but didn't find anything.

**Comment by pavelfeldman** [comment]
As stated above, you should use `await locator.fill('')`, it'll work.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by fibo** [comment]
@pavelfeldman I tried locator.fill('') or at least what I understood.

I could not find something related in documentation. This issue should be reopen, it is not clear for the users (like me).

**Comment by 1RossFisher1** [comment]
I am not able to use await locator.fill('')

**Comment by snetch-gym** [comment]
+1 ^^

**Comment by hex0cter** [comment]
`await locator.fill('')` seems flakey. :(

**Comment by 1RossFisher1** [comment]
I managed to get a workaround where I click on the text field twice before running await locator.fill(''). This seems to work for me.

**Comment by gauravgandhi1315** [comment]
This works for me 
`await page.keyboard.press('Backspace');`

**Comment by gauravgandhi1315** [comment]
I am just adding a loop in the above to delete the number of characters

`  async clearTextField(numOfTimes) {
    for (let i = 0; i <= numOfTimes; i++) {
      await page.keyboard.press('Backspace');
    }`

**Comment by hex0cter** [comment]
I am surprised that this ticket is closed while many people still have the same issue. Maybe it should be re-opened? @pavelfeldman

**Comment by icbita** [comment]
having same issue, filling in '' text in text field  adds nothing and I try to add other text will be added next to existing text

**Comment by gauravgandhi1315** [comment]
@icbita Try this https://github.com/microsoft/playwright/issues/12828#issuecomment-1254087006 before adding text.

**Comment by bvaughn** [comment]
> As stated above, you should use await locator.fill(''), it'll work.

Just chiming in to add that `fill('')` does not work for text areas (in my experience), at least with v 1.26.1. It does not seem to do anything.

**Comment by akcvarma** [comment]
Well, its quite easy to handle this if I am not wrong. Below code in java have worked fine for me.


Page.locator(x-path/CSS).selecttext(); // This will select the existing text in the textbox, even you have more than 2 words like "Pages of book"
page.keyboard().press("Backspace");// This would hit back space once and this action should clear the selected text.

Remember, using a double click instead  of selecttext() would only select one word when you have more than one word with a space in the text box. So this will only clear one word and you will still have rest of the string left in the text box.

**Comment by sandi3ai** [comment]
I used 
```
await page.click(selector, {clickCount: 3});
await page.keyboard.press('Backspace');
```

Worked for me

**Comment by RyanJeavo** [comment]
Would be awesome to have this as a feature in Playwright. Is this not something that could be added simply?

**Comment by rovmak** [comment]
This worked for me:
.press('Backspace') - clearing the data. You can do multiple .press('Backspace');

` await page.(selector).press('ArrowRight').click();`
 `await page.(selector).press('ArrowRight').press('ArrowRight');`
` await page.(selector).press('ArrowRight').press('Backspace');`

https://playwright.dev/docs/api/class-keyboard#keyboard-down

**Comment by gauravgandhi1315** [comment]
@rovmak Better way to do is

```
  async clearTextField(locator) {
    // click on the text field
    await this.clickOnElement(locator);
    await this.page.keyboard.press("Meta+A");
    await this.page.keyboard.press('Backspace');
  }
```

**Comment by dsebata** [comment]
I had the same on Playwright .Net. The documentation states;

> [FillAsync
](https://playwright.dev/dotnet/docs/api/class-locator#locator-fill)
> Added in: v1.14
> This method waits for [actionability](https://playwright.dev/dotnet/docs/actionability) checks, focuses the element, fills it and > triggers an input event after filling. Note that you can pass an empty string to clear the input field.

Ended up going with below after numerous attempts.
```cs
public async static Task ClearAndFillAsync(this ILocator locator, string value)
{
    await locator.ClearAsync();
    await locator.FillAsync(value);
}
```

**Comment by RamyaYellappa** [comment]
i had the same issue , we can follow these lines ,it worked for me 

        ElementHandle element = page.querySelector("pre[role='presentation']");
        element.focus();
        page.keyboard().press("Control+A");
        Thread.sleep(2000);
        page.keyboard().press("Backspace");

**Comment by shavemi** [comment]
This seems like an obvious missing feature.  

await locator.fill('') 

does nothing for me.

**Comment by bbstilson** [comment]
> [@rovmak](https://github.com/rovmak) Better way to do is
> 
> ```
>   async clearTextField(locator) {
>     // click on the text field
>     await this.clickOnElement(locator);
>     await this.page.keyboard.press("Meta+A");
>     await this.page.keyboard.press('Backspace');
>   }
> ```

An even better way is:

```js
async clearTextField(locator) {
  // click on the text field
  await this.clickOnElement(locator);
  await this.page.keyboard.press("ControlOrMeta+A");
  await this.page.keyboard.press('Backspace');
}
```
