### ISSUE TITLE
[Question] How to authenticate through VPN on an SSO login page using Global Setup

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#12822]
I set up a test that logged into the site I am testing and checked the URL. No issues there. Then I moved the login portion of it to a global-setup file as seen below:
```
// global-setup.js
const { chromium } = require('@playwright/test');

module.exports = async (config) => {
  const { storageState } = config.projects[0].use;
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto([redacted]);
  await page.screenshot({ path: 'screenshot.png' });
  await page.locator('[placeholder="User name"]').fill([redacted]);
  await page.locator('[placeholder="Password"]').fill([redacted]);
  await Promise.all([
    page.waitForNavigation( [redacted]),
    page.locator('text=Sign In').click()
  ]);
  await page.context().storageState({ path: storageState });
  await browser.close();
};
```

When doing the logging in from the global config file, the login page gets an error. Yet doing the login through the test works fine. I am wondering if there is something with SSO that it could be having an issue with. I know Cypress test is limited to visiting domains of the same origin and it made the login page have the same type of error. 

So, my question is - does authenticating using global-setup work differently than authenticating in test; and, if so, what would I need to do to get it to work? Below is the test where I login (for reference):

```
const { test, expect } = require('@playwright/test');
test('Assessments: Browse Pagez', async ({ page }) => {
  await page.goto([redacted]);
  await page.locator('[placeholder="User name"]').fill([redacted]);
  await page.locator('[placeholder="Password"]').fill([redacted]);
  await Promise.all([
    page.waitForNavigation([redacted]),
    page.locator('text=Sign In').click()
  await expect(page).toHaveURL(new RegExp(await expect(page).toHaveURL(new RegExp('Browse/Questionnaires$'));));
  ]);
```

**Comment by eatonjl** [comment]
I found the solution to the issue. There seems to be a difference in the Chromium being used. 
The issue was that the Chromium instance being used in global-setup does not have a set locale. The application I am testing requires the browser language to be set. Setting the locale in the global-setup fixed the issue.
Apparently, the Chromium instance being used by Playwright test has locale set, whereas the Chromium instance used by global-setup does not. I am not sure if that is bug or oversight, but it does seem to function differently.

**Comment by ycswaves** [comment]
> I found the solution to the issue. There seems to be a difference in the Chromium instance being used. The issue was that the Chromium instance being used in global-setup does not have a set locale. The application I am testing requires the browser language to be set. Setting the locale in the global-setup fixed the issue. Apparently, the Chromium instance being used by Playwright test has locale set, whereas the Chromium instance used by global-setup does not. I am not sure if that is bug or oversight, but it does seem to function differently.

Hi @eatonjl , could you share with me where you set the locale in the global-setup? Thanks!

**Comment by eatonjl** [comment]
You need to add "locale: 'en-us'," in the context.
It looks like this: 
```
async function globalSetup(config: FullConfig) {
	const { baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;
	const browser = await chromium.launch();
	const context = await browser.newContext({
		locale: 'en-us',
		ignoreHTTPSErrors,
	});
	const page = await context.newPage();
...
```
