### ISSUE TITLE
[BUG] Chromium: Cannot click, element intercepts pointer events

### ISSUE THREAD

**Issue by creage** [microsoft/playwright#12821]
**Context:**
- Playwright Version: 1.20.0
- Operating System: Windows10
- Node.js version: LTS 16
- Browser: Chromium only

**Describe the bug**
Trying to click on the ElementHandle, located by ElementHandle.waitForSelector() - fails in Chroimum with error
```
attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      <span class="selection">…</span> intercepts pointer events
```

Works fine in Webkit and Firefox, was working fine in all browsers before 1.20.0 upgrade.

**Comment by pavelfeldman** [comment]
Thanks for your report. Is there a page we could repro it on?

**Comment by jnizet** [comment]
I have the same problem. A test that passed with 1.19 now fails with 1.20. Here are some additional details:

I have a link looking like this:

```html
<a href="/activities/42"><h3>Foo</h3></a>
```

Using `await page.click('text=Foo');` fails on chromium, but passes on the other browsers.

Changing it to `await page.click('text=Foo', { force: true });` makes it pass on chromium, but then fails on webkit.

Changing it to `await page.click('a:has-text("Foo")');` makes it pass everywhere.

To make things even more confusing, the failure on webkit happens on Github actions (Ubuntu VM), but doesn't happen locally (macOS).

**Comment by dgozman** [comment]
@jnizet Any chance for a repro script/test with the page url?

**Comment by jnizet** [comment]
Hi @dgozman 

Here's a repro for the chromium issue. 
Steps to reproduce:

- unzip the repro.zip file. It contains an index.html and some assets that have been generated by exporting a page of my actual Angular-based application.
- cd into playwright-repro
- run a web server serving files in that directory, on port 8080 (I use the `http-server` NPM package)
- execute the following test file (with playwright 1.20). The first test fails on chromium only. The other two are workarounds to make the test pass.

```ts
import { test } from '@playwright/test';

test.describe('Activities', () => {
  test('should click activities', async ({ page }) => {
    await page.goto('http://localhost:8080/index.html');
    const romimineCard = page.locator('.card', { hasText: 'Romimine' });
    await test.expect(romimineCard.locator('h3')).toHaveText('Romimine');

    await page.click('text=Romimine');
  });

  test('should click activities with force', async ({ page }) => {
    await page.goto('http://localhost:8080/index.html');
    const romimineCard = page.locator('.card', { hasText: 'Romimine' });
    await test.expect(romimineCard.locator('h3')).toHaveText('Romimine');

    await page.click('text=Romimine', { force: true });
  });

  test('should click activities with a', async ({ page }) => {
    await page.goto('http://localhost:8080/index.html');
    const romimineCard = page.locator('.card', { hasText: 'Romimine' });
    await test.expect(romimineCard.locator('h3')).toHaveText('Romimine');

    await page.click('a:has-text("Romimine")');
  });
});
```

[repro.zip](https://github.com/microsoft/playwright/files/8282124/repro.zip)

**Comment by dgozman** [comment]
Investigation notes:
- `document.elementsFromPoint()` returns elements in the different order for some reason. Previously it was `[h3.card-title.fs-4, a, ...]`, now it is `[a, h3.card-title.fs-4, ...]`.
- Bisected Chromium down to https://chromium.googlesource.com/chromium/src/+log/f571b4214647f380beaf90bdf04bb97689e23d40..53508758bcbeb7e0fb70e87a7bed02de277bd602. Suspecting this change: https://chromium.googlesource.com/chromium/src/+/4a76c96d2a4021257e691058c1fe1fb60d9d8327
- Filed https://bugs.chromium.org/p/chromium/issues/detail?id=1307458.

**Comment by joecuevasjr** [comment]
I'm experiencing a similar(or the same) issue as the original poster on Playwright .NET v1.20.1, with the same error on Chromium. I did not experience the issue on 1.19.0.  However, Firefox and WebKit continue to work.

My issue originates on a call to .Locator().ClickAsync();
Downgrading back to v1.19 resolves my issue.

Thanks!

**Comment by jnizet** [comment]
Thanks for the investigation and the workaround @dgozman. 
It fills me with joy to have "Romimine", which is the name we gave to the cat living in our garden, now part of the codebase of Playwright and used to fix an issue in chromium. 😂

**Comment by Tallyb** [comment]
@dgozman  - thx for the fix. However, we still encounter the issue when there are multiple shadow roots, like in the attached dom:
![Screen Shot 2022-03-24 at 14 35 13](https://user-images.githubusercontent.com/7386255/159917383-1b6b5be1-d809-458f-9c5e-9b5b7c1a5c2d.png)
(sorry for the image, but I cannot copy all html). 

selector: `' yoo-form-input-container:has(.top-container:has-text("Completion Rate")) >> .outer-container >> .color-container'`

The clicked log: 
```
 performing click action
         <yoo-form-color-field clearable="" size="medium" class="hydrated" inpu…></yoo-form-color-field> intercepts pointer events
```

**Comment by dgozman** [comment]
@Tallyb Unfortunately, shadow roots mess up with the current workaround. However, the issue was fixed upstream in Chromium, so I expect next v1.21 release to work regardless. Sorry for the inconvenience!

**Comment by Tallyb** [comment]
@dgozman - yes, thought that would be the case. I figured out it is important to report, as others may encounter the same issue. We will have to wait for 1.21.

**Comment by rr13k** [comment]
hi ,  {   "name": "chromium",
        "revision": "1001",}  
There are still problems， Are you?

**Comment by creage** [comment]
@dgozman 1.21 still has this issue. So, the 1.19.2 is the last working version for us here.

**Comment by LSViana** [comment]
Is this issue still happening? I'm using `@playwright/test` at `1.24.0` and I see something similar on Chromium browsers only.

When trying to click on a `button` that's wrapped in a `span`, I noticed that the Inspector shows me this:

```
...
<span>...</span> intercepts pointer events
retrying click action, attempt #1
...
```

And it retries until it times out. I noticed that if I add `display: inline-block` to the `span` that wraps the `button` then the click operation works as expected.

**Comment by nadiaquraishi** [comment]
Was there any fix for this? I'm trying to run a script on one of our websites with shadow roots and it fails on Chromium browsers, but not Firefox. My current version of Chromium is 1.36... seeing as this thread hasn't been updated in a while my hopes are slim, but I guess it doesn't hurt to try and ask if anyone got around this issue.

This is the error I receive:
![image](https://github.com/microsoft/playwright/assets/147441883/2f42f6c7-cc08-40ee-8d06-ee6fed0a250d)

**Comment by cek-cek** [comment]
As others have already observed, invoking the `click()` on the ancestor that listens to the mouse event seems to work around the issue.

Instead of figuring out complicated selectors, you might as well select your favorite element in your preferred way and then use XPath get to the interactive ancestor:

`await page.locator('.myclass').first().locator('xpath=../..').click();` - in this example, I'm clicking the element two levels above the "myclass" element

Definitely not a solution, but hopefully saves someone's precious time.

**Comment by kanian** [comment]
For those who read the thread till this point, as of `"@playwright/test": "^1.28.1"`,  using the { force: true } option with the click method solves this issue:
`const nextButton = page.getByRole('button', { name: 'Suivant' });
 await expect(nextButton).toBeEnabled();
 await nextButton.click({ force: true});`
