### ISSUE TITLE
[BUG] `npx playwright install-deps` and `npx playwright install` does not install necessary dependencies for 1.19.2 after 1.20 released

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#12835]
I debated whether I should file this as a bug or question, so I'll include both statements :)

[Bug] Is it possible for the  `npx playwright install` to be backwards compatible with N-1 installs to reduce the overall problem of dependency management while teams "vet" each new release?

[Question] is there a way we could reduce our playwright dependency bumps to a single referenced of a given playwright version? I think we're looking for guidance on how to better manage the dependency changes across our different CI systems and projects.

**Context:**
- Playwright Version: 1.19.2 _after_ 1.20 was released
- Operating System: ubuntu/mac11.6/windows
- Node.js version: 12/14/16 @lts
- Browser: Chromium
- Extra: CircleCI and Github Actions

**Describe the bug**

When playwright/test@1.20 was released, we were still on 1.19.2. It is no longer possible to perform a `npx playwright install` or `npx playwright install-deps` on `ubuntu-latest` or `windows-latest`.

We have been riding N-1 for some time now just due to rapid pace of development on playwright and will likely never run in an unpinned, bleeding edge version.

Because we want to use windows and mac OS installations for running playwright tests on github actions, we are using `npx playwright install-deps` on `macos-latest` and `windows-latest` instead of the base `:focal` images. We **do** use the versioned `:focal` images in Circle CI.

Keeping our systems up to date with playwright/test changes now involve the following:
**Open Source**
1. Update playwright/test dependency in package.json
2. Update playwright base image in circle ci
**Downstream Closed Source**
1. Update playwright/test dependency in package.json
2. Update playwright base image in CI

**Now we will need to add:**
3. Update `npx playwright install` in 2/3 different GHA Files.

**Comment by pavelfeldman** [comment]
Interesting, I already answered this one, but I don't see my reply.

> When playwright/test@1.20 was released, we were still on 1.19.2. It is no longer possible to perform a npx playwright install or npx playwright install-deps on ubuntu-latest or windows-latest.

Could you elaborate on what is no longer possible?

> We have been riding N-1 for some time now just due to rapid pace of development on playwright and will likely never run in an unpinned, bleeding edge version.

This sounds reasonable.

> Because we want to use windows and mac OS installations for running playwright tests on github actions, we are using npx playwright install-deps on macos-latest and windows-latest instead of the base :focal images. We do use the versioned :focal images in Circle CI.

This sounds reasonable.

> Keeping our systems up to date with playwright/test changes now involve the following:

I'm not sure I follow the 1-4. I would imagine that for GHA it would be just a dependency bump and for Circle CI it would be container + package.json dependency bump.

**Comment by unlikelyzero** [comment]
> > When playwright/test@1.20 was released, we were still on 1.19.2. It is no longer possible to perform a npx playwright install or npx playwright install-deps on ubuntu-latest or windows-latest.

> Could you elaborate on what is no longer possible?

Sorry, after re-reading my edits, I realize that it's not clear what the initial problem was.
Basically we had been running the following scripts in GHA:
```
npx playwright install-deps
npm install
npm run playwright scripts
```

When 1.20 was released, the `npm run playwright` step would fail with a recommendation to `npx playwright install`. Our fix was to pin the version of @playwright/test within the package.json.
```
npx playwright@1.19.2 install-deps
npm install
npm run playwright scripts
```

**Comment by unlikelyzero** [comment]
It's likely a secondary effect of https://github.com/microsoft/playwright/issues/12772

**Comment by pavelfeldman** [comment]
I think this is the opposite of #12772 with a similar reason. You are using npx playwright@1.19.2, but the container you picked now has browsers for 1.20. You should always pin the container version to match Playwright or call `npx playwright install` to install necessary browsers.

**Comment by unlikelyzero** [comment]
@pavelfeldman so in that case, I think this _is_ a bug. I shouldn't have to npx playwright@version install-deps with a `@version` (I tried both install and install-deps)

package.json
```
@playwright/test: 1.19.2
```

Github Action
```
jobs:
  playwright:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npx playwright install-deps
      - run: npm install
      - run: npm run test
```
This fails on the npm run test line with


```
browserType.launch: Executable doesn't exist at /home/runner/.cache/ms-playwright/chromium-9[65](https://github.com/nasa/openmct/runs/5576533019?check_suite_focus=true#step:6:65)416/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

**Comment by pavelfeldman** [comment]
`npx playwright install-deps` - this installs system dependencies only, you still need `npx playwright install` to install the browsers. Those are separate for flexibility, but you can do a combo of a form `npx playwright install-with-deps`.

See https://playwright.dev/docs/intro#installation

**Comment by unlikelyzero** [comment]
@pavelfeldman updated title to reflect the fact that this does not work with `npx playwright install` (as well as `npx playwright install-deps`

**Comment by unlikelyzero** [comment]
@pavelfeldman i created a non-reproducer here: https://github.com/microsoft/playwright/pull/12893/files

I wonder if it's caching related?

**Comment by pavelfeldman** [comment]
I'm sorry, I'm not following at all. What does the `non-reproducer` mean? It is not installing deps, so it isn't guaranteed to work. Could we make a step back and discuss it in the following framework:

1. Steps to perform
2. Expected behavoir
3. Actual behavior

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by unlikelyzero** [comment]
@dgozman @pavelfeldman filed here https://github.com/microsoft/playwright/issues/13188
