### ISSUE TITLE
[REGRESSION]: Playwright is not recognising the browsers that are pre-baked into Docker image

### ISSUE THREAD

**Issue by kellis-scottlogic** [microsoft/playwright#12843]
https://github.com/microsoft/playwright/issues/12674 originally raised here

Experiencing issue with version `1.17.2 `and `1.19.1`
Operating Systems: CircleCI and Jenkins linux based pipelines

I maintain 2 different pipelines that have been using the pre-built Playwright docker images and until recently both these configurations were working without any issue, but since last week I am now experiencing an issue where we are being prompted to install playwright again in order to download new browsers.

![image](https://user-images.githubusercontent.com/91476997/158779847-2882fd54-99a6-4b25-be43-8c27b7721771.png)

Both pipelines and the respective projects are pinned to the same Playwright version, here is an example from one of the projects:

from package.json:
![image](https://user-images.githubusercontent.com/91476997/158781519-2e94beea-72d0-44b1-8008-9942d7590312.png)

from CircleCI config - commented out lines are what I have had too add as a temp workaround. But removing these steps results in the error shown in the image above
![image](https://user-images.githubusercontent.com/91476997/158781442-847dadb3-4753-46a7-924b-c332ef8e5665.png)

As I mentioned before, until last week this config was working absolutely fine. The only change I have made is the added steps to install the browsers.

I have checked the docker images and the browser files are present in both the `1.17.2-focal` and `1.19.1-focal` versions

**Comment by aslushnikov** [comment]
@kellis-scottlogic could you please help me reproduce this? Could you please create a small gitlab repository that illustrates the problem?

**Comment by kellis-scottlogic** [comment]
@aslushnikov sure thing, may take me a few days to get it sorted around other work commitments but will post up here again once I have something for you

**Comment by pavelfeldman** [comment]
We think that you pinned docker image to 1.17, but your package.json uses 1.19. This is due to the error requesting Chromim 965416 (used in 1.19).

**Comment by aslushnikov** [comment]
@kellis-scottlogic any chance you might come up with a repro? It'll help drastically to understand what's going on!

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
