### ISSUE TITLE
[Question] Action was interrupted

### ISSUE THREAD

**Issue by wuweikd** [microsoft/playwright#12846]
<img width="1278" alt="image" src="https://user-images.githubusercontent.com/34428646/158790370-26024c9f-f3dd-40d9-b8f8-18eac5d091a8.png">

Hi
 When the code run `await locator.click()` at docker,  I get  "Action was interrupted",  I think the reason is that the element is overridden.But it is ok when at mac os. And  i have set the config： `use:{actionTimeout: 20000}`,Is there any way to wait for this loading to close before judging that the click fails?

**Comment by pavelfeldman** [comment]
Looks like you added this timeout to the config and now you are asking how to neutralize it. You should remove `use:{actionTimeout: 20000}` from the config, you should only set it in rare cases.

**Comment by wuweikd** [comment]
It's just a click event, why am I getting this error?

**Comment by pavelfeldman** [comment]
It isn't a click event, Playwright ways for element to be actionable: https://playwright.dev/docs/actionability
