### ISSUE TITLE
[Question] Want to run test in docker, but missing random dependencies

### ISSUE THREAD

**Issue by Kirill29** [microsoft/playwright#12845]
**Hello i want to run tests in docker, in docker file write something like this:**

> RUN apt-get update && apt-get install -y --no-install-recommends npm
> RUN npm i playwright@1.14.0 && npx playwright install
> RUN npx playwright install-deps
> RUN apt-get remove nodejs -y

**when build image and run, tests fails with:**

>  Host system is missing dependencies!
>   Missing libraries are:
>       libgobject-2.0.so.0
>       libglib-2.0.so.0
>       libnss3.so
>       libnssutil3.so
>       libsmime3.so
>       libnspr4.so
>       libatk-1.0.so.0
>       libatk-bridge-2.0.so.0
>       libgio-2.0.so.0
>       libcups.so.2
>       libdrm.so.2
>       libdbus-1.so.3
>       libxcb.so.1
>       libxkbcommon.so.0
>       libX11.so.6
>       libXcomposite.so.1
>       libXdamage.so.1
>       libXext.so.6
>       libXfixes.so.3
>       libXrandr.so.2
>       libgbm.so.1
>       libpango-1.0.so.0
>       libcairo.so.2
>       libasound.so.2
>       libatspi.so.0
>       libxshmfence.so.1

**when i change my docker file and add this dependencies:**

> RUN apt-get update && apt-get install -y --no-install-recommends \
>     libglib2.0 \
>     libnss3 \
>     libnspr4 \
>     libatk1.0 \
>     libatk-bridge2.0 \
>     libgio2.0 \
>     libcups2 \
>     libdrm2 \
>     libdbus-1-3 \
>     libxcb1 \
>     libxkbcommon0 \
>     libx11-6 \
>     libxcomposite1 \
>     libxdamage1 \
>     libxext6 \
>     libxfixes3 \
>     libxrandr2 \
>     libgbm1 \
>     libpango-1.0 \
>     libcairo2 \
>     libasound2 \
>     libatspi2.0-0 \
>     libxshmfence1 \
>     npm
> RUN npm i playwright@1.14.0 && npx playwright install
> RUN npx playwright install-deps
> RUN apt-get remove nodejs -y

**After this i get this, another dependencies is missing**
> Host system is missing 
> dependencies!
> 
>   Missing libraries are:
>       libgtk-3.so.0
>       libgdk-3.so.0
>       libXcursor.so.1
>       libpangocairo-1.0.so.0
>       libcairo-gobject.so.2
>       libgdk_pixbuf-2.0.so.0
>       libdbus-glib-1.so.2
>       libpangoft2-1.0.so.0

**why RUN npx playwright install-deps is not enough and how can i install all dependencies?**

**Comment by pavelfeldman** [comment]
Did you pick a wrong base for your image?

**Comment by Kirill29** [comment]
Yes, sorry we were using 6.0.201-bullseye-slim-amd64, 6.0-bullseye-slim-amd64, 6.0.201-bullseye-slim, 6.0-bullseye-slim, 6.0.201, 6.0 on Debian as base image
https://hub.docker.com/_/microsoft-dotnet-nightly-sdk/

I have read what playwright not support Debian, will switch to Ubuntu

Thanks!
