### ISSUE TITLE
[Question]How to simulate long press or click and hold action using playwright Java?

### ISSUE THREAD

**Issue by gvsharshavardhan** [microsoft/playwright#12841]
below is my code but **no luck!!**

**Approach 1:**
`page.click("xpath=//button[@id='isDisabled' and contains(@class,'is-primary')]",new Page.ClickOptions().setDelay(5));`

**Approach 2:**
```
page.focus("xpath=//button[@id='isDisabled' and contains(@class,'is-primary')]");
        page.mouse().down();
        page.waitForTimeout(3);
        page.mouse().up();
```

**Comment by gvsharshavardhan** [comment]
The below code also did not work!

`page.mouse().move(holdButton.boundingBox().x+holdButton.boundingBox().width/2,holdButton.boundingBox().y+holdButton.boundingBox().height/2);
        page.mouse().down();
        page.waitForTimeout(3);
        page.mouse().down();`

**Comment by pavelfeldman** [comment]
Maybe 3 milliseconds is not enough?

**Comment by gvsharshavardhan** [comment]
right!! I was under the assumption that the time is in seconds. Thanks for the clarification !!

**Comment by pavelfeldman** [comment]
@gvsharshavardhan by the way, check this out: https://playwright.dev/docs/api/class-elementhandle#element-handle-click-option-delay
