### ISSUE TITLE
[BUG] ts compilerOptions.paths with * in middle of value are not being resolved properly

### ISSUE THREAD

**Issue by ivankoleda** [microsoft/playwright#12851]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Mac
- Node.js version: v16.14.0

**Description**

[Recently added](https://github.com/microsoft/playwright/issues/7121#issuecomment-1009140849) support of typescript `compilerOptions.paths` config property doesn't work for values with `*` char in the middle. 
Example:

```
"paths": {
  "@company/prefix-*": [
    "packages/prefix-*/src"
  ]
}
```

The config above with error:

```sh
$ playwright test

Running 0 test using 0 worker


Error: Cannot find module '<path-to-project>project/packages/prefix-*/src'
Require stack:
...
```

Current support of paths works fine for values like `foo/*` or `foo`. But not for cases like `foo-*/bar`. However `tsc` is able to handle cases like this one.

**Reproduction repo**

https://github.com/ivankoleda/playwright-ts-paths-bug-reproduction

**Comment by pavelfeldman** [comment]
If this works in tsc, this looks like an undocumented capability:
- https://www.typescriptlang.org/tsconfig
- https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

I don't see anything about non-prefix matching there...

**Comment by ivankoleda** [comment]
Looks like it is not covered in public doc, but seems to be expected according to this comment in typescript repo:

> `If pattern contains '*' then to match pattern "<prefix>*<suffix>" module name must start with the <prefix> and end with <suffix>.`

https://github.com/microsoft/TypeScript/blob/main/src/compiler/moduleNameResolver.ts#L1049

**Comment by pavelfeldman** [comment]
Yup. But lots of other tools interpret tsconfig as well and they don't do this magic. Would you be interested in contributing a patch that fixes it? Open to a fix, but can't prioritize it internally.

**Comment by ivankoleda** [comment]
I may try implementing a fix for this case over the next couple weeks/month. I started implementing the fix before, but couldn't make it quickly.
