### ISSUE TITLE
[Feature] extend assertion to include toHaveURLContains instead of using regex

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#12856]
extend assertion to include toHaveURLContains instead of using regex

**Comment by pavelfeldman** [comment]
Why?

**Comment by pavelfeldman** [comment]
The difference would be:

```js
await expect(page).toHaveURL(/substring/);
vs
await expect(page).toContainURL('substring');
```

Which is marginal, so I'd keep it as is!

**Comment by amrsa1** [comment]
@pavelfeldman 

mm it didnt work like that with me  not sure if im missing something, i have to match the entire path 

```
    test.only('test', async () => {
        await expect(interestRatePage).toHaveURL(`/the-simplest-way/form/?price=${info.price}`);
    });
```
<img width="848" alt="Screenshot 2022-03-18 at 12 03 15" src="https://user-images.githubusercontent.com/32042806/158991868-6f6c5a49-b3f7-4b83-aafb-f3c925d54304.png">
