### ISSUE TITLE
[Question] Is there a way to un-focus a tab in browser?

### ISSUE THREAD

**Issue by archlichking** [microsoft/playwright#12858]
One of our tests needs to verify an event from our website which is triggered only if the page is unfocused and refocused again. Manual reproduce steps are click a link on the page to open a new tab, and we click on the previous tab to bring it upfront. Per https://playwright.dev/docs/pages#multiple-pages, all tabs in a browser are treated as focused. In our test we cannot get this refocus event triggered due to the above findings. I wonder if there is a way to do the refocus test in playwright.

**Comment by pavelfeldman** [comment]
No such feature yet, folding into https://github.com/microsoft/playwright/issues/3570
