### ISSUE TITLE
[Question] - How to get performance insights with webkit?

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/playwright#12861]
Hello,

We run Playwright in our Azure Pipelines on macOS build agents to test various aspects of our site. I notice that some of our tests are flakey and after digging into it (I can provide traces but cannot be shared publicly) I notice that our tests seem to be moving super slow. 

For example we have a line where we do `locator.type(query, { delay: 100 })` and each letter typed into the input box takes multiple seconds to complete causing our tests to timeout. I suspect it has something to do with cpu/memory constraints? We are running the tests on the Microsoft Azure macOS public agents and are using 4 workers. 
Is there a way to get performance insights to see why Playwright is taking so long?
Is it Playwright of Webkit?

I really appreciate any guidance here as it is causing flakiness when trying to merge PRs. Thank you so much!

**Comment by pavelfeldman** [comment]
Side question: what's the reason behind type + delay and not fill()?

No great answer here. In general you should check how many cores your agents have, divide it by 2 and use that as a number of workers.

**Comment by AAAstorga** [comment]
@pavelfeldman The docs made it sound like it mimics user behavior better but I switched it to fill and also did # cpu cores / 2 which ends up being 2 workers on the macOS build agents and I see a huge improvement. Thank you!
