### ISSUE TITLE
How to verify text containing <br> tag

### ISSUE THREAD

**Issue by fa66-coder** [microsoft/playwright#12869]
html element : `<span data-qa-id="test-param">Doc.<br>Test</span>`
I would like to verify [data-qa-id="test-param"] has the text Doc. Test and verify whether it is displayed or not at the same. I am not able to do as the text contains <br> tag in it.

Can someone help me how to address the scenario?

Thanks!

**Comment by ltsuda** [comment]
Do you think this is what you want?

https://playwright.dev/docs/api/class-page#page-locator
 https://playwright.dev/docs/test-assertions#locator-assertions-to-be-visible
 
```javascript
const testLocator = page.locator('[data-qa-id="test-param"]', {hasText: 'Doc.Test'}) 
// as the <br> breakes the line after "Doc.", there is no space in "Doc.Test"
await expect(testLocator).toBeVisible()
 ```
 
 or 
 
 ```javascript
const testLocator  = page.locator('[data-qa-id="test-param"]')
await expect(testLocator).toContainText('Doc.Test')
 ```

**Comment by fa66-coder** [comment]
> ```js
> const testLocator  = page.locator('[data-qa-id="test-param"]')
> await expect(testLocator).toContainText('Doc.Test')
> ```

@ltsuda - 

I was adding space in place of `<br>` assuming it will add space but it was not, the above mentioned approach works for me. Thanks!

**But I have a few questions regarding hasText :**
1. Does this verify the text of an element's descendant by just passing the root element selector?

e.g. `<span data-qa-id="test-param"><span><div>Doc.<br>Test</div></span</span>`
page.locator('[data-qa-id="test-param"]', {hasText: 'Doc.Test'}) 

2. Does this matches the text partially ?

e.g.
`<span data-qa-id="test-param"><span><div>Doc.<br>Testmoretext</div></span</span>`
page.locator('[data-qa-id="test-param"]', {hasText: 'Doc.Test'})

**Comment by pavelfeldman** [comment]
`hasText: 'Doc.Test'` is a new syntax of the old `:has-text` pseudo selector. You can read more about it here: https://playwright.dev/docs/selectors#text-selector

**Comment by pavelfeldman** [comment]
Keeping this issue open to update the docs.
