### ISSUE TITLE
[BUG] Screenshots don't work.

### ISSUE THREAD

**Issue by JuanCruzTrinidad** [microsoft/playwright#12863]
**Context:**
- Playwright Version:1.20.0
- Operating System: Linux
- Node.js version: 14.8
- Browser: Chromium

When updating to version 1.20.0 an error occurs when taking screenshots.
We use fixtures that encompass the navigation of the pages, to generate full page screenshots at the end of the suites, these fail in 50% of the cases.
Also, using the matchSnapshot option does not take the initial snapshot, which should then be used for comparison.
These same tests work in version 1.16.3

**Comment by pavelfeldman** [comment]
Could you share a reproducible scenario?

**Comment by JuanCruzTrinidad** [comment]
I will now explain the architecture of the projects we work with:
- We have a Core project where we implement the fixtures, with differences to use them in api-only tests and browser tests with navigation.
- We have a "Utilities" project where we manage generic functions used in different projects, within this project we also define describe callbacks with basic tests inside, which we use in different projects.

We update the version of playwrigth in all our libraries (Core, Utilities) and implement them in the application's own project. This error occurs when trying to make screenshots from a description brought from the utilities project.

Additionally, the "test-failed" screenshots also fail on some occasions, which I understand are automatic by configuration once the tests fail.

Debugging I was able to get to this screenshot where it seems you can see the function that "never ends" (because it stays there checked at that point for more than 10 minutes without advancing).

I hope this data will help you solve the problem.

![debug](https://user-images.githubusercontent.com/53027244/159022170-b8ba9867-9d9c-4ebd-85a4-2265b71e6ca0.png)

**Comment by pavelfeldman** [comment]
Ah, thanks for these details! This looks like https://github.com/microsoft/playwright/issues/12711. It is already fixed, will be published as v1.20.1 on Monday. Folding this issue into the existing one.
