### ISSUE TITLE
Can't paste from browser

### ISSUE THREAD

**Issue by TobiFarore** [microsoft/playwright#12876]
I'm clicking a copy button and I want to paste the copied text and assert on the result.. Please help!

```
  var click =  await Page.EvaluateAsync("document.querySelectorAll('span.copy-icon')[0].click();");
  await Page.Context.GrantPermissionsAsync(new[] { "clipboard-read" });
  var text = Page.EvaluateAsync<string>("navigator.clipboard.readText()").Result;
```

**Comment by pavelfeldman** [comment]
You are performing programmatic click using evaluate. Browsers are not interacting with the clipboard when doing programmatic clicks due to security reasons. Otherwise any page could clear your system clipboard. Try doing this instead:

```cs
await Page.Locator('span.copy-icon').ClickAsync();
```

**Comment by TobiFarore** [comment]
@pavelfeldman  the element only displays when you hover over it, so I could use ClickAsync().. any suggestions?

**Comment by dgozman** [comment]
@TobiFarore Do a hover first, and then click. You'll probably need a separate locator for the "element that shows copy button upon hover".

```c#
await Page.Locator('.shows-copy-button-on-hover').HoverAsync();
await Page.Locator('span.copy-icon').ClickAsync();
```

**Comment by TobiFarore** [comment]
@dgozman I tried that the suggestion above and I was able to click the copy button but the paste funtion didn't work even after permission was granted.. I attempted to copy from chromium manually while debugging but that also didn't work

` public async Task GrantCopyPermission()
        {
            await Page.Context.GrantPermissionsAsync(new[] { "clipboard-read", "clipboard-write" });
        }

        public void DownloadLogFile()
        {
           
            var ele =  Page.Locator("[class='object-key-val']").Nth(0);
            ele.HoverAsync();
            
            var copy =  Page.Locator("span.copy-icon").Nth(0);
            copy.ClickAsync();
            var text = Page.EvaluateAsync<string>("navigator.clipboard.readText()").Result;

        }`

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by lvd1999** [comment]
Hi

Is there a way to assert the copied text without pasting it somewhere?
