### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ezrover** [microsoft/playwright#12878]
**Context:**
- Playwright Version:"playwright-chromium": "^1.20.0",
- Operating System: Mac and Linux
- Node.js version: v17.6.0
- Browser: All
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 11.6.4
 - Memory: 31.03 GB / 64.00 GB
## Binaries:
 - Node: 17.6.0 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.5.1 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright-chromium: ^1.20.0 => 1.20.0 

Testing the login feature from the hamburger menu of the home page. Navigation to the menu item on the hamburger menu is successful but google tag manager is injecting scripts into the site as each page loads and the navigation is stolen by one of the injected analytics scripts! This occurs randomly in different tests. The sample below is just an example: we click on a button to take action and expect it to navigate to a certain location instead. Playwright gets stuck and the last messages you see in the log. Is there any way to prevent google tag manager or any of its injected scripts from loading while testing?

  pw:api <= page.goto succeeded +1ms
[chromium] › US/pages/home/hamburger.spec.mjs:43:3 › Hamburger links work › Sign in
  pw:api => tracing.stop started +2ms
  pw:api <= tracing.stop succeeded +2ms
  pw:api => browser.newContext started +0ms
  pw:api <= browser.newContext succeeded +6ms
  pw:api => tracing.stop started +2ms
  pw:api <= tracing.stop succeeded +2ms
  pw:api => browserContext.newPage started +1ms
  pw:api <= browserContext.newPage succeeded +138ms
Hamburger links work correctly beforeEach 
  pw:api => page.waitForNavigation started +0ms
  pw:api waiting for navigation until "load" +3ms
  pw:api   "commit" event fired +666ms
  pw:api   navigated to "https://match.adsrvr.org/track/upb/?adv=*********" +0ms
  pw:api   "domcontentloaded" event fired +83ms
  pw:api   "commit" event fired +144ms
  pw:api   navigated to "https://match.adsrvr.org/track/cmf/rubicon?gdpr=0" +0ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "commit" event fired +81ms
  pw:api   navigated to "https://match.adsrvr.org/track/cmf/appnexus?ttd=1&anid=*********" +0ms
  pw:api   "domcontentloaded" event fired +1ms
  pw:api   "load" event fired +1ms
  pw:api   "networkidle" event fired +1s
  **_pw:api <= page.waitForNavigation failed +2m_**

**Code snippet:**

`import { test, expect } from '@playwright/test';

test.describe.parallel('Hamburger links work', () => {

  let page;

  test.beforeAll(async ({ browser, baseURL }) => {

    console.log(`beforeAll: `);

    page = await browser.newPage();
    await page.goto('/');

  });

  test.afterAll(async () => {
    await page.close();
  });

  test.beforeEach(async ({ page, baseURL }) => {

    //await page.goto('/');

    await page.waitForNavigation('/');

    await page.waitForTimeout(5000);

    // Check if cookies is still visible
    if(await page.isVisible("text='Accept Cookies'")){
      console.log('Accept Cookie was visible!!!');
      await page.locator('text=Accept Cookies').click();
    }
  });

  test.afterEach(async ({ page }) => {
  });

  test('Sign in', async ({ page, baseURL }) => {
    await page.locator('[aria-label="Menu"]').click();

    await page.locator('text=Sign In').nth(1).click()
    await page.waitForNavigation('/portal/login/');

    await page.locator('[placeholder="Email \\*"]').click();
    await page.locator('[placeholder="Email \\*"]').fill('xyz');
    await page.locator('[placeholder="Password \\*"]').click();
    await page.locator('[placeholder="Password \\*"]').fill('123');
    await page.locator('input:has-text("Login")').click();

    await page.waitForNavigation('/portal/designs');
    await expect(page).toHaveURL('/portal/designs');

  });
`

**Comment by pavelfeldman** [comment]
Your tests are unclear:
- You don't need to create a page in beforeAll and the page that you use in your beforeEach / test are different
- You should not wait for timeout

Your test should be like this:

```js
test.beforeEach(async ({ page }) => {
  await page.goto('/');
  // Always wait for the dialog.
  await page.locator('text=Accept Cookies').click();
});

test('Sign in', async ({ page }) => {
  await page.locator('[aria-label="Menu"]').click();
  await page.locator('text=Sign In').nth(1).click();
  await page.locator('[placeholder="Email \\*"]').fill('xyz');
  await page.locator('[placeholder="Password \\*"]').fill('123');
  await page.locator('input:has-text("Login")').click();
  await expect(page).toHaveURL('/portal/designs');
});
```

**Comment by ezrover** [comment]
Thank you, that is how it was at first, we were just experimenting to find
a way to not let the navigation get hijacked by inject analytics scripts.
Why does Playwright navigate to the analytics urls?!

**Comment by pavelfeldman** [comment]
It does not navigate to any analytics urls, but it emits events when navigations happen in iframes.

**Comment by dgozman** [comment]
Looks like everything works as expected.
