### ISSUE TITLE
[BUG] Locator.count() with _vue selector with Repro

### ISSUE THREAD

**Issue by yuvalkarif** [microsoft/playwright#12887]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Windows
- Node.js version: v16.13.0
- Browser: Chromium
- Nuxt: 2.15.8
- Vue: 2.6.14

#12623 

Managed to create a repro in this basic Nuxt project [repo](https://github.com/yuvalkarif/nuxt-pr-repro).
Simply created three Vue components, using a `Locator` with `_vue` selector I try to log their count and the output is indeed `0`.
`expect.toHaveCount()` still works as intended.

**Comment by mxschmitt** [comment]
I can repro:

```diff
diff --git a/tests/page/selectors-vue.spec.ts b/tests/page/selectors-vue.spec.ts
index 239632404..6f47ad518 100644
--- a/tests/page/selectors-vue.spec.ts
+++ b/tests/page/selectors-vue.spec.ts
@@ -30,10 +30,12 @@ for (const [name, url] of Object.entries(vues)) {
 
     it('should work with single-root elements @smoke', async ({ page }) => {
       expect(await page.$$eval(`_vue=book-list`, els => els.length)).toBe(1);
+      expect(await page.locator(`_vue=book-list`).count()).toBe(1);
       expect(await page.$$eval(`_vue=book-item`, els => els.length)).toBe(3);
+      expect(await page.locator(`_vue=book-item`).count()).toBe(3);
       expect(await page.$$eval(`_vue=book-list >> _vue=book-item`, els => els.length)).toBe(3);
+      expect(await page.locator(`_vue=book-list >> _vue=book-item`).count()).toBe(3);
       expect(await page.$$eval(`_vue=book-item >> _vue=book-list`, els => els.length)).toBe(0);
     });
 
     it('should work with multi-root elements (fragments)', async ({ page }) => {
```

Reason is probably that `toHaveCount` is using the `main` world and in `locator.count()` we are [using the utility context](https://github.com/microsoft/playwright/blob/f587a43932119fb50e3b81700b7f5eb89b266628/packages/playwright-core/src/server/selectors.ts#L94-L100).
