### ISSUE TITLE
[BUG] - Error: net::ERR_INVALID_AUTH_CREDENTIALS

### ISSUE THREAD

**Issue by pauloventurab** [microsoft/playwright#12890]
**Context:**
- Playwright Version: [Version 1.20.0]
- Operating System: [Windows]
- Python version: [Python 3.9.1]
- Browser: [Chromium,webkit,firefox]

**Code Snippet**
```
    browser = p.chromium.launch(headless=False)
    page2 = browser.new_page()
    page2.goto("**https://wfrstdiis35.webhelp.local/**")
    page2.screenshot(path="example.png")
```

**Describe the bug**

Hello everyone,

I'm facing an issue on playwright.
After successfully being able to download a file from a page on internet (a client tool). Now I'm trying to upload the file again in our server ( **https://wfrstdiis35.webhelp.local/** ), is a page where we track some files between departments inside the company.

But always when I try to run the Script, I get this error : playwright._impl._api_types.Error: net::ERR_INVALID_AUTH_CREDENTIALS at https://wfrstdiis35.webhelp.local/

This error doesn't happen if I go to another page on internet, just this one that is online just if you access our VPN.

So yes the question is: If this website is not online, is just on the server side we access this after access also the VPN, can I connect to it? We have more than 20 websites that just connect if the VPN is connected, and I would like to use playwright to do it.

Thank you.

**Comment by pavelfeldman** [comment]
I guess this sites requires you to authenticate?

**Comment by pauloventurab** [comment]
Yes, when I access the website in a normal way I see a modalbox asking to login, but with playwright the screenshot is now showing this option.

**Comment by mxschmitt** [comment]
https://playwright.dev/python/docs/network#http-authentication

this should help!

**Comment by pauloventurab** [comment]
You are awesome, your boss know it? <3

I read almost all the documentation, but I don't know why I didn't see this one! My fault? No, your skill to solve problems! Clapsss
