### ISSUE TITLE
[Feature] changing visibilityState

### ISSUE THREAD

**Issue by kapouer** [microsoft/playwright#1290]
Being able to change `document.visibilityState` (and consequently `document.hidden`) would be nice:
- to test what some code does when hidden, prerender or visible
- to test `visibilitychange` events and how code behave w.r.t. those properties

**Comment by kapouer** [comment]
It should work with
`Object.defineProperty(document, 'visibilityState', {get() { return "prerender";}})`
i don't know why i opened that issue.
Closing.

**Comment by abhayp5** [comment]
@kapouer  can you please put the snap of the code where you implemented this. Need to do same.

**Comment by kapouer** [comment]
@abhayp5 https://github.com/kapouer/express-dom/blob/ef720a5b84e834ff951b9241788b63285c00e59b/lib/plugins.js#L98-L105
[but there are tons of examples like that](https://github.com/search?l=JavaScript&o=desc&q=defineProperty+document+visibilityState&s=&type=Code)

**Comment by abhayp5** [comment]
thank you it really helped. able to achieve using page.evaluateHandle() function.

**Comment by nowayX** [comment]
Can you tell me how you changed the visibilityState with some code please
