### ISSUE TITLE
[Question] Tests failing because of CORS Errors

### ISSUE THREAD

**Issue by jithintill** [microsoft/playwright#12902]
Issue : Tests failing because of CORS Errors

I have started seeing a subset of tests failing in my regression suite with CORS errors as given below.

I am using Playwright Test Runner with bypassCSP turned on

It mainly happens in Adding a user and a payment flow functionality

But the same test passes on retry successfully, its kind of a flaky scenario. In few runs it triggers a CORS error and fails execution but passes in retry

Scenario
1) Add name
2) Add email
3) Click on submit button

Actual Result
Once user clicks on submit button, network call times out and throws network error as shown below

<img width="1072" alt="Screen Shot 2022-03-19 at 4 32 04 pm" src="https://user-images.githubusercontent.com/98723817/159108581-d8c6c18c-1762-46b4-a3cd-64ff011a4145.png">

Just wanted to identify , whether its from the app or from the playwright

I can share the trace file privately if required

**Comment by dgozman** [comment]
@jithintill This seems to be an app issue. You have a page from one domain that issues a request to another domain (the difference is in `paybylink.` vs `api-gateway.` Usually, you should configure the server to accept requests from your frontend domain.

Here is a nice write-up about CORS [on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS).

**Comment by jithintill** [comment]
thanks for clarifying
