### ISSUE TITLE
[Feature] Option to not follow redirects in the requests API

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#12911]
The `request` fixture methods seems to follow the redirects by default. It would be great if there was an option to disable this behaviour.

```js
const response = await request.get('http://localhost:3000/url', { followRedirects: false })
expect(response.status()).toBe(302)
expect(response.headers()['Location']).toBe('/login')
```

**Comment by mxschmitt** [comment]
@Meemaw what is the use-case for it?

**Comment by Meemaw** [comment]
@mxschmitt We're using Playwright to test an application with server side rendering. Some of the tests are testing that our server correctly redirects you based on your permissions (e.g redirection to `/login` when you visit some authenticated page).

We could test that by just navigating to that page using `page.goto`, but that is not the same. That would have passed even if the navigation client side. In our case, we want to test the server returns status code 302 and appropriate redirect. There tests are also much "cheaper" as there might be a lot of them.

**Comment by raimohanska** [comment]
We have a similar use case and would greatly appreciate this. We mostly use `page.request` which is an `APIRequestContext` object.

**Comment by franzvezuli** [comment]
One use case that I use is:

-- Inspect the first call has a status of 302
-- Inspect the `location` header is correct

**Comment by vincenzo-gasparo** [comment]
I have similar use cases too, I often need to check the redirect location for some auth routes and this feature would be very useful. Currently we are using another request module to handle this use case.

**Comment by jessfraz** [comment]
Yes want to check the set-cookie header on a 302 redirect to intercept it and set it via playwright since chromium blocks third-party cookies in incognito mode (aka playwright default settings)

**Comment by mcdehaan** [comment]
Same as the people above me. I'm testing for the 302 status, location in the header and correct cookies. My workaround is using Axios but I try to replace it entirely with Playwright.
