### ISSUE TITLE
[BUG] Firefox Headless: Material DatePicker Component fails to load in full

### ISSUE THREAD

**Issue by ddemoss222** [microsoft/playwright#12914]
**Context:**
- Playwright Version: [1.20]
- Operating System: [Linux]
- Node.js version: [17.7.1]
- Browser: [Firefox]
## System:
 - OS: Linux 5.15 Manjaro Linux
 - Memory: 4.59 GB / 15.63 GB
 - Container: Yes
## Binaries:
 - Node: 17.7.1 - /usr/bin/node
 - Yarn: 1.22.17 - /usr/bin/yarn
 - npm: 8.5.4 - /usr/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```jsx
const Date:FC = (props) => {
return <LocalizationProvider dateAdapter={AdapterDateFns} locale={enLocale}>
        <DatePicker
          value={selectedDate}
          onChange={(newDate) => {
            handleDateChange(newDate)
          }}
          error={errors && errors.length > 0}
          renderInput={props => <TextField maxRows={4} {...props} name={name} label={display}/> }
          minDate={ Date.parse(new Date().getFullYear() - 3) } 
          inputFormat="MM/dd/yyyy"
        />
   </LocalizationProvider>
}
```
![image](https://user-images.githubusercontent.com/25989271/159185722-d85e4b11-fb01-40ba-b37b-8cebd117c148.png)
Critically, the action button is missing that opens the datePicker UI.
![image](https://user-images.githubusercontent.com/25989271/159185813-981def52-9994-4c6e-8cac-6b02b77ea723.png)
The UI correctly loads in headed mode

**Comment by dgozman** [comment]
@ddemoss222 Unfortunately, we cannot help you without a full repro, and this script misses some components, dependencies, css, etc.

Did you try [recording a trace](https://playwright.dev/docs/trace-viewer)? Perhaps, there are some errors in the page that could explain the issue?

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
