### ISSUE TITLE
[Bug] device* media queries are not triggered with viewport emulation

### ISSUE THREAD

**Issue by tomgallagher** [microsoft/playwright#1291]
If you want to test sites with media queries, setting the viewport is not enough.

I've found that I also need to change the window size to accommodate media queries and accurately reflect what a user would see with certain screen sizes

`await chromium.launch({args: [ `--window-size=${someWidth},${someHeight}`]});`

That's easy enough thanks to your helpful device dictionary.

Am I missing something here?

Is it possible to change the default window size on all browser instances launched by Playwright?

Failing that, are there comparable flags for Firefox and Webkit?

**Comment by aslushnikov** [comment]
> If you want to test sites with media queries, setting the viewport is not enough.

@tomgallagher to the best of my knowledge, viewport emulation should be enough :thinking: can you give an example?

**Comment by tomgallagher** [comment]
Hi, thanks for getting back

By way of an example, go to this [site](https://turbobrowser.eu/)

There's a sub-header banner that has the following media rule 

```
@media screen and (max-width: 767px) {
    .installButtonSegment {
        display: none;
        width: 100vw;
    }
}

```

It does not show in retrieved screenshot when the viewport is set and browser context confirmed as:

```
viewport: {
      width: 1366,
      height: 768,
      deviceScaleFactor: 1,
      isMobile: false
}
```

But it shows when launching the browser with:

`chromium.launch({args: ['--no-sandbox', `--window-size=1366,768] });
`

**Comment by aslushnikov** [comment]
@tomgallagher thank you for the great repro! This is fixed on Chromium now; the `viewport` now emulates screen sizes as well so screenshots are consistent.

We'll fix this in other browsers as well!

**Comment by tomgallagher** [comment]
Good stuff! :smile:

**Comment by dgozman** [comment]
#1565 fixed this for Firefox.

**Comment by dgozman** [comment]
I believe this is now fixed in all browsers 🎉
