### ISSUE TITLE
[Question] waitForURL() 

### ISSUE THREAD

**Issue by SusieIndeed** [microsoft/playwright#12926]
Hi I have problem when using this method:
page.waitForURL(expectedURL);
I can see it is waiting until the URL is changed to expectedURL, but seems the page is not loaded. What I want is, after the page navigate to the expected URL, I need check one content on the page. Any method to make sure the page is fully loaded?

**Comment by dgozman** [comment]
@SusieIndeed The `page.waitForURL()` method waits for the `"load"` event by default. If the page is not ready, it must be doing some async loading after that. It is usually the best to wait for something visual on the page that loads last, for example:

```js
await page.waitForURL(expectedURL);
await page.locator('text=Last item that loads').waitFor();
```

Let me know if that helps.

**Comment by swapnabhaskarun** [comment]
page.navigate("https://stage.slingshot.service.savagebeast.com/slingshot/force_sfdc_sync/"+ oppID); 
page.waitForURL("**/orderplan");

I am using the above code using Java but i keep seeing the timeout error of 30000ms
Please let me know how i can extend the wait until the URL changes to what i expect and also the loading gets finished

**Comment by swapnabhaskarun** [comment]
how can i keep the browser open without getting closed. I am not using page.close or browser.close but the window still closes
