### ISSUE TITLE
[Question] Custom request-classes (ApiRequestContext)

### ISSUE THREAD

**Issue by Tobias-08** [microsoft/playwright#12921]
Hi,
is it possible to implement custom request-classes (ApiRequestContext) with custom configuration/options and what is the best approach to do so? Is the approach the same like for page-fixtures? Is there a sample (could not find anything in the docs)?

Thanks!

**Comment by dgozman** [comment]
Look at [this guide](https://playwright.dev/docs/test-api-testing). It shows how to use [`request.newContext()`](https://playwright.dev/docs/api/class-apirequest#api-request-new-context) that creates a context with a lot of settings.

**Comment by Tobias-08** [comment]
Thanks, that helped!
