### ISSUE TITLE
[Question] Playwright java docker issues

### ISSUE THREAD

**Issue by filipe-j-delgado** [microsoft/playwright#12923]
Hi,

I'm trying to use playwright java docker image (mcr.microsoft.com/playwright/java:v1.20.0-focal) on a Jenkins pipeline and I'm getting this error:

```
_31mcom.microsoft.playwright.PlaywrightException: Error {
  message='Protocol error (Browser.enable): Browser closed.
==================== Browser output: ====================
<launching> /ms-playwright/firefox-1316/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-d74VhH -juggler-pipe -silent
<launched> pid=361
[pid=361][err] Error: no DISPLAY environment variable specified
[pid=361] <process did exit: exitCode=1, signal=null>
[pid=361] starting temporary directories cleanup
=========================== logs ===========================
<launching> /ms-playwright/firefox-1316/firefox/firefox -no-remote -wait-for-browser -foreground -profile /tmp/playwright_firefoxdev_profile-d74VhH -juggler-pipe -silent
<launched> pid=361
[pid=361][err] Error: no DISPLAY environment variable specified
[pid=361] <process did exit: exitCode=1, signal=null>
[pid=361] starting temporary directories cleanup
============================================================
  name='Error
  stack='Error: Protocol error (Browser.enable): Browser closed._`

```
Jenkinsfile:

```
 pipeline {
    environment {
      gitCredentialId = 'git'      
    }
    agent { docker { image 'mcr.microsoft.com/playwright/java:focal' } }

    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }

    stages {
        stage('Build') {
            steps {
                // Get some code from a GitHub repository
                git(url: 'https://github.com/xxxxxxx/xxxxxxxx.git', credentialsId: gitCredentialId)             
                
                // Run Maven on a Unix agent.
                sh "mvn -Dmaven.test.failure.ignore=true clean compile test"\
            }

            post {
                // If Maven was able to run the tests, even if some of the test
                // failed, record the test results and archive the jar file.
                success {
                    junit '**/target/surefire-reports/TEST-*.xml'
                    archiveArtifacts 'target/*.jar'
                }
            }
        }
    }
}
```

Can you help please?

Thanks.

**Comment by mxschmitt** [comment]
You need to either start the browser `headless: true` / `setHeadless(true)` or use `xvfb-run` so that a virtual x-server is there.

**Comment by yury-s** [comment]
Can you reproduce it in Docker without Jenkins?

**Comment by spursbob** [comment]
I'm getting the same issue here with "mcr.microsoft.com/playwright:v1.20.1-focal" using Jenkins. The project is set to headless too

`    {
        name: 'firefox',
        use: {
            headless: true,
            ...devices['Desktop Firefox'],
        },
    },`

**Comment by mxschmitt** [comment]
Maybe Jenkins is injecting some custom environment variables? For us it would be important to be able to reproduce it on "plain Docker" or have reproducible steps.

**Comment by spursbob** [comment]
> Maybe Jenkins is injecting some custom environment variables? For us it would be important to be able to reproduce it on "plain Docker" or have reproducible steps.

It's not a reintroduction of this? - https://github.com/microsoft/playwright/issues/12075

**Comment by mxschmitt** [comment]
Pretty sure no, since the issue is fixed. I tried to reproduce it but for me it was working as expected.

The original issue might be caused by it tho, since the Docker image is not pinned. 

-> Make sure that the Docker image and the Playwright version matches. For example:

`mcr.microsoft.com/playwright:v1.20.1-focal`

or in Java: `mcr.microsoft.com/playwright/java:v1.20.1-focal`

**Comment by spursbob** [comment]
> 



> Pretty sure no, since the issue is fixed. I tried to reproduce it but for me it was working as expected.
> 
> The original issue might be caused by it tho, since the Docker image is not pinned.
> 
> -> Make sure that the Docker image and the Playwright version matches. For example:
> 
> `mcr.microsoft.com/playwright:v1.20.1-focal`
> 
> or in Java: `mcr.microsoft.com/playwright/java:v1.20.1-focal`

My bad. My tests run fine against Chrome and Safari but fail against Firefox. The only info the stacktrace provides is, "Timeout of 80000ms exceeded." I have gradually increased that timeout from 30 seconds to 80 seconds with no joy. I then added the --debug flag to try and get more info and I guess --debug runs in headed mode which is why I was seeing the same error reported here.

**Comment by spursbob** [comment]
Now I am at the same point as @filipe-j-delgado :

    [38;5;45;1mpw:api [0m=> browserType.launch started [38;5;45m+0ms[0m
    [30;1mpw:browser [0m<launching> /ms-playwright/firefox-1319/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-PEmJm5 -juggler-pipe -silent [30m+0ms[0m
    [30;1mpw:browser [0m<launched> pid=500 [30m+4ms[0m
    [30;1mpw:browser [0m[pid=500][err] *** You are running in headless mode. [30m+30ms[0m
    [30;1mpw:browser [0m[pid=500][err] Error: Access was denied while trying to open files in your profile directory. [30m+1ms[0m

I logged into the Kubernetes environment that Jenkins is using and ran "kubectl run playwright -it --restart=Never --rm --image mcr.microsoft.com/playwright:v1.20.2-focal -- bash" the test ran successfully. 

The pertinent errors coming from Jenkins seem to be:

    [30;1mpw:browser [0m[pid=500][err] Error: Access was denied while trying to open files in your profile directory. [30m+1ms[0m
    .
    .
    .
    [30;1mpw:browser [0m[pid=500][err] Unable to revert mtime: /ms-playwright/firefox-1319/firefox/fonts [30m+30ms[0m
    [30;1mpw:browser [0m[pid=500][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+66ms[0m

**Comment by APAODUQS** [comment]
> Now I am at the same point as @filipe-j-delgado :
> 
> ```
> [38;5;45;1mpw:api [0m=> browserType.launch started [38;5;45m+0ms[0m
> [30;1mpw:browser [0m<launching> /ms-playwright/firefox-1319/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-PEmJm5 -juggler-pipe -silent [30m+0ms[0m
> [30;1mpw:browser [0m<launched> pid=500 [30m+4ms[0m
> [30;1mpw:browser [0m[pid=500][err] *** You are running in headless mode. [30m+30ms[0m
> [30;1mpw:browser [0m[pid=500][err] Error: Access was denied while trying to open files in your profile directory. [30m+1ms[0m
> ```
> 
> I logged into the Kubernetes environment that Jenkins is using and ran "kubectl run playwright -it --restart=Never --rm --image mcr.microsoft.com/playwright:v1.20.2-focal -- bash" and the test ran successfully in there.
> 
> The pertinent errors coming from Jenkins seem to be:
> 
> ```
> [30;1mpw:browser [0m[pid=500][err] Error: Access was denied while trying to open files in your profile directory. [30m+1ms[0m
> .
> .
> .
> [30;1mpw:browser [0m[pid=500][err] Unable to revert mtime: /ms-playwright/firefox-1319/firefox/fonts [30m+30ms[0m
> [30;1mpw:browser [0m[pid=500][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+66ms[0m
> ```

I got this:
```
[](http://localhost:8081/job/playwright-demo/job/main/145/console#)Run Tests
[Pipeline] sh
+ DEBUG=pw:api,pw:browser npx playwright test --config=playwright.config.ts --project Firefox --grep @playwright

Running 1 test using 1 worker

[1A[2K
[1A[2K[Firefox] › example.spec.ts:13:3 › My tests set › Get started with Playwright @playwright
  [38;5;45;1mpw:api [0m=> browserType.launch started [38;5;45m+0ms[0m

[1A[2K  [30;1mpw:browser [0m<launching> /ms-playwright/firefox-1319/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-7i2bQF -juggler-pipe -silent [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m<launched> pid=345 [30m+5ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] *** You are running in headless mode. [30m+428ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.670878) [GFX1-]: glxtest: libpci missing [30m+243ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.670878) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.670963) [GFX1-]: glxtest: Unable to open a connection to the X server [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.670878) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.670963) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.670981) [GFX1-]: glxtest: libEGL initialize failed [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: libpci missing (t=0.670878) |[1][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.670963) |[2][GFX1-]: glxtest: libEGL initialize failed (t=0.670981) |[3][GFX1-]: No GPUs detected via PCI (t=0.671006) [GFX1-]: No GPUs detected via PCI [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] Unable to revert mtime: /ms-playwright/firefox-1319/firefox/fonts [30m+93ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+224ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+10ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+7ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+3ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] JavaScript error: resource://gre/modules/XULStore.jsm, line 66: Error: Can't find profile directory. [30m+36ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+60s[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:49.932: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+2ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:49.933: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:49.933: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:49.934: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+5ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:49.939: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+1ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+482ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:50.421: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:50.422: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:50.422: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+1ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err]  [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345][err] (firefox:345): dconf-CRITICAL **: 20:14:50.422: unable to create directory '/.cache/dconf': Permission denied.  dconf will not work properly. [30m+0ms[0m

[1A[2K[1/1] [Firefox] › example.spec.ts:13:3 › My tests set › Get started with Playwright @playwright
[1A[2K  1) [Firefox] › example.spec.ts:13:3 › My tests set › Get started with Playwright @playwright =====

    [31mTimeout of 90000ms exceeded.[39m


[1A[2K  [30;1mpw:browser [0m[pid=345] <kill> [30m+29s[0m

[1A[2K  [30;1mpw:browser [0m[pid=345] <will force kill> [30m+0ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345] starting temporary directories cleanup [30m+1ms[0m

[1A[2K  [30;1mpw:browser [0m[pid=345] finished temporary directories cleanup [30m+7ms[0m

[1A[2K  Slow test file: [Firefox] › example.spec.ts (2m)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [Firefox] › example.spec.ts:13:3 › My tests set › Get started with Playwright @playwright ======
```

**Comment by spursbob** [comment]
@mxschmitt is it possible to override "-profile" folder in file "playwright.config.js"? I'm wondering if setting it to a path within the Jenkins workspace will allow the profile content to be created. It appears to me that Jenkins doesn't have permission to write to the default "/tmp" path.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/13230 see there the last few comments.
