### ISSUE TITLE
[BUG] Service Workers are flaky

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#1292]
`ChromiumBrowserContext should create a worker from a service worker` times out sometimes. So far I've only repro'd this on windows. It looks like an upstream bug.

The service worker is created, and we attach to it, but we don't receive a `Target.attachedToTarget` message?! Instead, we just start getting messages from the service worker on a new sessionId, starting with `Inspector.targetReloadedAfterCrash`.

Later, when closing the browserContext/test, we get the missing attachedToTarget. Nothing is dumped to stderr. I'm confused.

**Comment by JoelEinbinder** [comment]
`Inspector.targetReloadedAfterCrash` might be a red herring. It seems to occur even if everything succeeds.

**Comment by yury-s** [comment]
The spurious targetReloadedAfterCrash event issue has been fixed upstream.
