### ISSUE TITLE
[BUG] Click inside an iframe does not work correctly

### ISSUE THREAD

**Issue by haramchang** [microsoft/playwright#12932]
**Context:**
- Playwright Version: "playwright-chromium": "^1.20.0"
- Operating System: Mac
- Node.js version: v17.6.0
- Browser: all
- Extra: [any specific details about your environment]

I'm testing a 'Join Waitlist' button inside of an iframe on a particular page. The button is visible and clickable but for some reason it times out while waiting for the navigation - as if the button click did not happen at all. 

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test.describe.parallel.only('Join Waitlist button works', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('/air/configure', { waitUntil: 'networkidle'});
  });

  test.afterEach(async ({ page }) => {
    await page.close();
  });

  test('Join waitlist button', async ({ page }) => {
    await page.locator('text=Accept Cookies').click();

    await Promise.all([
      page.waitForNavigation({ url: '/air/reserve/?trim=dream_edition&shortcode=EN1Z46&LUCID_EXT_COLOR=ZL_P001&configurator=zl_3d&configuratorMode=web'}),
      page.frameLocator('#cookiePadding').locator('text=Join Waitlist').click()
    ]);

    await expect(page).toHaveURL('/air/reserve/?trim=dream_edition&shortcode=EN1Z46&LUCID_EXT_COLOR=ZL_P001&configurator=zl_3d&configuratorMode=web');
    });

});

```

**LOGS**: 
```
  pw:api <= page.goto succeeded +1ms
  pw:api => locator.click started +1ms
  pw:api waiting for selector "text=Accept Cookies" +2ms
  pw:api   selector resolved to visible <button id="onetrust-accept-btn-handler">Accept Cookies</button> +12ms
  pw:api attempting click action +3ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +23ms
  pw:api   scrolling into view if needed +1ms
  pw:api   done scrolling +0ms
  pw:api   performing click action +4ms
  pw:api   click action done +22ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +1ms
  pw:api <= locator.click succeeded +0ms
  pw:api => page.waitForNavigation started +1ms
  pw:api => locator.click started +4ms
  pw:api waiting for navigation to "/air/reserve/?trim=dream_edition&shortcode=EN1Z46&LUCID_EXT_COLOR=ZL_P001&configurator=zl_3d&configuratorMode=web" until "load" +1ms
  pw:api   waiting for frame "#cookiePadding" +2ms
  pw:api   selector resolved to visible <iframe dir="ltr" id="cookiePadding" class="Configurator…></iframe> +4ms
  pw:api waiting for selector "#cookiePadding >> control=enter-frame >> text=Join Waitlist" +4ms
  pw:api   selector resolved to visible <button class="Button-sc-1boce5r-0 hnOhqw">Join Waitlist</button> +12ms
  pw:api attempting click action +2ms
  pw:api   waiting for element to be visible, enabled and stable +0ms
  pw:api   element is visible, enabled and stable +27ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +0ms
  pw:api   performing click action +4ms
  pw:api   click action done +4ms
  pw:api   waiting for scheduled navigations to finish +0ms
  pw:api   navigations have finished +0ms
  pw:api <= locator.click succeeded +0ms
  pw:api   "commit" event fired +3s
  pw:api   navigated to "about:blank" +0ms
  pw:api   "load" event fired +2ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api   "networkidle" event fired +501ms
```

**Comment by dgozman** [comment]
@haramchang Perhaps the does not navigate to the expected url? Try commenting out `page.waitForNavigation()` and `expect(page).toHaveURL()` lines. If that works, [record a trace](https://playwright.dev/docs/trace-viewer) to see what's happening.

**Comment by haramchang** [comment]
@dgozman I recorded the trace and it just showed the click and no navigation to any URL. 
I think the reason why it wasn't working was cause there's a delay in the actionability of the button when you hover over it, so when I changed the code to this it worked when running the test on my laptop:

```
  test('Join waitlist button', async ({ page }) => {
    await page.locator('text=Accept Cookies').click();
    await page.frameLocator('#cookiePadding').locator('button:has-text("Join Waitlist")').hover();
    await timeout(2000);
    await page.frameLocator('#cookiePadding').locator('text=Join Waitlist').click();
    await expect(page).toHaveURL(/.*air\/reserve\/\?trim=dream_edition*/);
  });
```

I ran the test multiple times just to make sure and it always passed. However, what I don't understand is why when running on gitlab I get this error:

```
locator.hover: Target closed
=========================== logs ===========================
  waiting for frame "#cookiePadding"
  selector resolved to visible <iframe dir="ltr" id="cookiePadding" class="Configurator…></iframe>
waiting for selector "#cookiePadding >> control=enter-frame >> button:has-text("Join Waitlist")"
============================================================

```

Any insights would be much appreciated!

**Comment by dgozman** [comment]
@haramchang This error is usually either a page crash (browser crashed trying to show the page), or the timed out test closes the page at the end.

**Comment by haramchang** [comment]
@dgozman Tried upping the timeouts by a substantial amount to see if it passes, but to no avail.

**Comment by Nhc007** [comment]
@haramchang We also faced that issue while interacting with iframes elements, but we fixed that by switching to iframe first, and use it as active frame. Hope so this will fix the issues.

''

**Comment by haramchang** [comment]
@Nhc007 Hi! Would you mind sharing your snippet of code? I tried making changes to reflect what you did but I'm not sure I'm doing it right haha it keeps failing!

**Comment by haramchang** [comment]
@Nhc007 Thank you!

**Comment by mxschmitt** [comment]
closing since it seems stale. Feel free to file a new issue with a repro.

**Comment by HinaSharma16** [comment]
@Nhc007 w.r.t your comment above "_We also faced that issue while interacting with iframes elements, but we fixed that by switching to iframe first, and use it as active frame and then just normally interact with it but do remember that, once you are done with interacting with iframe change the activeFrame back to page. Hope so this will fix the issues."_

Could you please confirm how were you able to switch to iframe and then continue. As far as I understand, we need to click the elements in the iframe with framelocator  everytime.  I could not find a way to switch into iframe and then progress with active iframe.  Need your help on how o work activate an iframe in playwright. I am using python as the language.

**Comment by DivyamMyAnatomy** [comment]
> @dgozman I recorded the trace and it just showed the click and no navigation to any URL. I think the reason why it wasn't working was cause there's a delay in the actionability of the button when you hover over it, so when I changed the code to this it worked when running the test on my laptop:
> 
> ```
>   test('Join waitlist button', async ({ page }) => {
>     await page.locator('text=Accept Cookies').click();
>     await page.frameLocator('#cookiePadding').locator('button:has-text("Join Waitlist")').hover();
>     await timeout(2000);
>     await page.frameLocator('#cookiePadding').locator('button:has-text("Join Waitlist")').click();
>     await expect(page).toHaveURL(/.*air\/reserve\/\?trim=dream_edition*/);
>   });
> ```
> 
> timeout is a custom function I created. I ran the test multiple times just to make sure and it passed every time. However, what I don't understand is why when running on gitlab I get this error:
> 
> ```
> locator.hover: Target closed
> =========================== logs ===========================
>   waiting for frame "#cookiePadding"
>   selector resolved to visible <iframe dir="ltr" id="cookiePadding" class="Configurator…></iframe>
> waiting for selector "#cookiePadding >> control=enter-frame >> button:has-text("Join Waitlist")"
> ============================================================
> ```
> 
> Any insights would be much appreciated.#23748 
@haramchang Would you mind sharing the code of the timeout function that you created?I am also facing same issue.
