### ISSUE TITLE
[Question] Retrieve parent from child text content ?

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#12936]
Hello !

I have this DOM structure:

```html
<div id='work-item-0'><div><span>toto</span></div></div>
<div id='work-item-1'><div><span>toto2</span></div></div>
<div id='work-item-2'><div><span>toto3</span></div></div>
```

The event allowing me to click on the element is attached to the first div (work-item level). 
I have a text box where I search toto, it gives me 3 results and I would like to click on `toto`. But, before to search for toto, I don't know how many results I will have so I cannot target work-item with a specific number (I mean work-item-0 for this example, toto could be work-item-11). So, using Locator, how can I find the id of the parent (work-item) containing toto and only toto.

Thanks for your help

**Comment by dgozman** [comment]
```js
await page.locator('[id*="work-item"]', { hasText: /^toto$/ }).click();
// alternatively
await page.locator('[id*="work-item"]', { has: page.locator('text=/^toto$/') });
```

Here are guides for [locator options](https://playwright.dev/docs/api/class-page#page-locator) and [selectors](https://playwright.dev/docs/selectors).
