### ISSUE TITLE
[Question] page.screenshot  'encoding' option has been dismissed?

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#1294]
The `page.screenshot()` method used to have an `encoding` option.
I saw that this option has been removed, but there is one test that may indicate that this 'encoding' option is a non documented feature:

`screenshot.spec.js`

```js
it('should return base64', async({page, server}) => {
      await page.setViewportSize({width: 500, height: 500});
      await page.goto(server.PREFIX + '/grid.html');
      const screenshot = await page.screenshot({
        encoding: 'base64'
      });
      expect(Buffer.from(screenshot, 'base64')).toBeGolden('screenshot-sanity.png');
    });
```
So my question is: is this test obsolete, or is the `encoding` option a non documented feature?

**Comment by aslushnikov** [comment]
@hdorgeval yeah this is a stray test; there's no more option any more.

If you need the option, It is easily polifilable:
```js
const base64 = (await page.screenshot()).toString('base64');
```

I'll follow-up with test removal

**Comment by hdorgeval** [comment]
Hi @aslushnikov, thank you very much for your feedback.
