### ISSUE TITLE
Please join to us #standwithukraine

### ISSUE THREAD

**Issue by id-dan** [microsoft/playwright#12945]
Please support Ukraine, more infos here: https://github.com/vshymanskyy/StandWithUkraine

**Comment by aslushnikov** [comment]
Official Microsoft statement: https://blogs.microsoft.com/on-the-issues/2022/02/28/ukraine-russia-digital-war-cyberattacks/

**Comment by id-dan** [comment]
Hi, @aslushnikov 
I mean to show banner on repo for other people, then they can use link to donate
