### ISSUE TITLE
[Feature] Root Hooks in playwright test

### ISSUE THREAD

**Issue by baleshkoijam** [microsoft/playwright#12954]
Referring the documentation provided by playwright, seems like the hooks (example: afterAll / beforeAll) can be used only inside a spec/ test file as below:

// example.spec.ts
import { test, expect } from '@playwright/test';

test.beforeAll(async () => {
  console.log('Before tests');
});

test.afterAll(async () => {
  console.log('After tests');
});

test('my test', async ({ page }) => {
  // ...
});

My question: is there any support where there can be only one AfterAll() or beforeAll() hook  in one single file which will be called for every test files ? the piece of code that i want to have inside the afterAll and beforeAll is common for all the test/ specs files and i dont want to have the same duplicated in all the spec files/ test file.
Any suggestion or thoughts on this?

TIA
Allen

**Comment by dgozman** [comment]
Are you looking for [`globalSetup`](https://playwright.dev/docs/test-advanced#global-setup-and-teardown)?

**Comment by gauravgandhi1315** [comment]
@baleshkoijam I had the same scenario in my application. There is no way to use `beforeAll` and `afterAll` in one single file for all your tests. But I fixed it by using `global-setup(beforeAll)` and `global-teardown(afterAll)`

check here https://github.com/microsoft/playwright/issues/12656

**Comment by baleshkoijam** [comment]
@dgozman  and @gauravgandhi1315  thanks for the suggestion. I am able to use the globalSetup to achieve the same.
