### ISSUE TITLE
[BUG] browserContext.cookies() doesn't return all cookies

### ISSUE THREAD

**Issue by dossy** [microsoft/playwright#12967]
**Context:**
- Playwright Version: 1.20.0
- Operating System: macOS 11.6.2
- Node.js version: 16.13.1
- Browser: Chromium

**Code Snippet**

```javascript
// globalSetup.js
const { chromium } = require("@playwright/test");

module.exports = async (config) => {
  const browser = await chromium.launch();

  const context = await browser.newContext({
    baseURL: config.projects[0].use.baseURL,
    ignoreHTTPSErrors: true,
  });

  const page = await context.newPage();

  await page.goto("/login");
  await page.fill('input[name="email"]', "EMAIL_ADDRESS");
  await page.fill('input[name="password"]', "PASSWORD");
  await page.check("text=Remember me");
  await page.click("text=Sign in");

  const cookies = await context.cookies();

  for (const cookie of cookies) {
    console.log(JSON.stringify(cookie));
  }

  await page.context().storageState({ path: "e2e/state/admin.json" });
}
```

**Describe the bug**

To avoid various browser and local security differences, a host definition for `local.domain.com` pointing at `127.0.0.1` is created, and the server is using a self-signed SSL certificate on port 7443.  Therefore, `baseURL` in this case looks like:

`https://local.domain.com:7443`

At the end of the steps above, there are 3 cookies set:

- one cookie set as `domain=.domain.com; path=/; expires=2023-04-21T08:34:43.000Z; secure; SameSite=None`
- one cookie set as `domain=.domain.com; path=/; expires=2022-03-22T23:04:43.000Z; secure; SameSite=None`
- one cookie set as `domain=local.domain.com; path=/; expires=2023-03-22T05:24:34.526Z; httpOnly; secure; SameSite=Lax`
 
For context, it is currently `2022-03-22T22:49:06.360Z` so none of these cookies have expired, yet.

The code above only outputs the first two cookies.  Similarly, the `e2e/state/admin.json` file has the data for the first two cookies.

What do I need to do to get that third cookie, so I can persist it/reuse it?

Naturally, for security reasons, cookies that are `httpOnly` and `secure` are, by design, not supposed to be accessible by client-side scripts.  I don't know if Playwright has some way of circumventing this extra security for the purposes of persisting these cookies, because if it does, documenting how to use it would be really helpful here.

I've also tried changing the line:

```
  const cookies = await context.cookies();
```

to:

```
  const cookies = await context.cookies(config.projects[0].use.baseURL);
```

which made no observable difference, outputting only the first two cookies, still.

Is this supposed to be possible?  Or is this just a hard limitation of the browser security and something Playwright can't do anything about?

**Comment by dossy** [comment]
Closing this issue as the problem was on my end:

Apparently, there were two elements on the page that contained the text "Sign in" (an `h2` and a `button` ... 🤦), so `await page.click("text=Sign in");` was silently failing, which is why only two of the three cookies were set.  The third cookie would be set in response to a successful click of the button ...

Is there a reason `page.click()` silently eats this error while `page.locator()` followed by `locator.click()` tells me right away that there was a "strict mode violation" error?

Anyway, maybe this will come in handy for someone who runs into the same issue.

FWIW, this was the fix, changing:

```
  await page.click("text=Sign in");
```

to:

```
  await page.click("button >> text=Sign in");
```

**Comment by eugene-galaxy** [comment]
I think the main problem is due to the "@playwright/test" version.
