### ISSUE TITLE
[BUG] fullPage screenshot does not work when scrollable content does not scroll on the body

### ISSUE THREAD

**Issue by liamdebeasi** [microsoft/playwright#12962]
**Context:**
- Playwright Version: 1.20.0
- Operating System: macOS 12.1
- Node.js version: 16.11.1
- Browser: All

**Code Snippet**

GitHub repo: https://github.com/liamdebeasi/playwright-screenshot-repro

**Describe the bug**

Taking a screenshot with `fullPage: true` does not take a full page screenshot when the scrollable content scrolls on a non-body element. Full page screenshots are taken correctly when the scrollable content scrolls on the body.

I would expect that the screenshot is full page regardless of where the scrollable content is.

**Steps to reproduce**

1. Clone the included repo.
2. Run `npm install`.
3. Run `npx playwright test`.
4. Open both screenshots in `tests/example.spec.ts-snapshots/`.
5. Observe that the screenshot for the test that loads the body scrollable content is full size.
6. Observe that the screenshot for the test that loads non-body scrollable content is not full size.

The source HTML files can be found in `dist`. In the case of the broken sample, the scrollable content is in a div that has `position: absolute`.

The GitHub repo only runs screenshots in Safari, but I am also able to reproduce this when taking screenshots in Chrome and Firefox.

**Comment by dgozman** [comment]
@liamdebeasi Thank you for filing the issue!

The behavior you describe is expected. Full page screenshots do not expand any scrollable container in the page. Instead, they render the full scrollable content of the document itself. In your case, document is of the fixed size, but happens to have a scrollable container that has a lot of content.

Note that you should be able to screenshot the [container element](https://playwright.dev/docs/api/class-locator#locator-screenshot) instead:
```js
await page.locator('.container').screenshot();
```

**Comment by liamdebeasi** [comment]
I was able to find a pretty easy workaround. I will post it here for anyone else who has the same question I did.

For my use case, I have a Shadow DOM component called `ion-content`. The content I want to take a screenshot of scrolls on a `.inner-scroll` element inside of the `ion-content` Shadow DOM.

To take fullpage screenshots of this content, I resized the page viewport so that the document is large enough to show all of the scrollable content.

I created a custom `test` fixture to do this:

```ts
import { test as base } from '@playwright/test';

export const test = base.extend({
  page: async ({ page }, use) => {

    page.setIonViewport = async () => {
      const currentViewport = await page.viewportSize();

      const pixelAmountRenderedOffscreen = await page.evaluate(() => {
        const content = document.querySelector('ion-content');
        const innerScroll = content.shadowRoot.querySelector('.inner-scroll');

        return innerScroll.scrollHeight - content.clientHeight;
      });

      await page.setViewportSize({
        width: currentViewport.width,
        height: currentViewport.height + pixelAmountRenderedOffscreen
      })
    }

    await use(page);
  },
});
```

From here, I was able to call `await page.setIonViewport()` and then `await page.screenshot({ fullPage: true })`.

Thanks again for the help!

**Comment by m-balagangadharan** [comment]
I'm interested in adopting this workaround for a situation where we have a modal/overlay kind of a window displayed with a scroll bar. But I'm using Java. If you can let me know if this work around applies for this situation too, I would really appreciate.

**Comment by karpikpl** [comment]
I'm getting similar issue and struggle to find a solution.
The click action works on element that's not visible, but full page screenshot is cut at where scroll starts.
Container screenshot has the correct size, but it's empty where element should be...

![screenshot-custom-aad-chromium-container](https://github.com/microsoft/playwright/assets/3539908/16fffd76-5d01-45ff-9918-c19cbd69118c)

**Comment by NoelToy** [comment]
I am using Playwright 1.43.0 the latest version available still the issue persist. Ideally speaking the framework should have a feature to take screenshot of an entire element which has a inner scroll this has been actually handled in Puppeteer(drawback it's only available in node.js). Could you provide some details on why it's not able to take full screenshot of an html element that having an inner scroll?

**Comment by afsal-backer** [comment]
I got around this with:

```
      await page.setViewportSize({ width: 4880, height: 2559 }); // Zoom out to fit the full page
      await page.waitForLoadState('domcontentloaded')
      await expect(page).toHaveScreenshot("pricing-full-page.png", {fullPage: true})
```

**Comment by awenirbanL** [comment]
> I got around this with:
> 
> ```
>       await page.setViewportSize({ width: 4880, height: 2559 }); // Zoom out to fit the full page
>       await page.waitForLoadState('domcontentloaded')
>       await expect(page).toHaveScreenshot("pricing-full-page.png", {fullPage: true})
> ```

This is not a proper solution unfortunately as certain pages can have a scrollbar even with that viewport size.

**Comment by madnancp** [comment]
`playwright==1.55.0`
Using in python, this bug hitting even now. 
Guys have any tips ?

**Comment by madnancp** [comment]
> I got around this with:
> 
> ```
>       await page.setViewportSize({ width: 4880, height: 2559 }); // Zoom out to fit the full page
>       await page.waitForLoadState('domcontentloaded')
>       await expect(page).toHaveScreenshot("pricing-full-page.png", {fullPage: true})
> ```

Going with this, But i cant use a fixed size in a general term. Any new way please lemme know
