### ISSUE TITLE
[Feature] Add option to ignoreHTTPSErrors in webServer

### ISSUE THREAD

**Issue by szamacz** [microsoft/playwright#12976]
I noticed that playwright cannot correctly specify if the server is running or not and starts tests too fast when there are problems with https. When I have added check for URL and port using opening new window and ignoring HTTPS errors it works fine, so adding an option to ignoreHTTPSErrors in webserver config would do the job.

**Comment by dgozman** [comment]
You can specify `url` instead of `port` to ensure https is ready. That said, it will probably fail with SSL certificate error as you expect.

```ts
webServer: {
    command: 'npm start',
    url: 'https://localhost:4200',
    timeout: 240 * 1000,
    reuseExistingServer: !process.env.CI
},
```

**Comment by tscislo** [comment]
It fails with SSL cert errors with url param just as you mentioned. **Expected behavior is to add option to ignore ssl cert errors and keep checking if the dev server is running or not.**
