### ISSUE TITLE
[BUG] Webkit forces https on localhost

### ISSUE THREAD

**Issue by maxibri** [microsoft/playwright#12975]
**Context:**

- Playwright Version: 1.20.0
- Operating System: Ubuntu 20.04
- Node.js version: v14.19.0
- Browser: Webkit

**Code Snippet**

Here is my webkit config
```
//playwright.config.js

const config = {
// ...
  projects: [
      {
        name: 'safari',
        use: {
          ...devices['Desktop Safari'],
          bypassCSP: true,
          headless: false,
          ignoreHTTPSErrors: true,
        },
      },
  ],
// ...
}
```

**Describe the bug**

When running tests on Webkit, i get the following errors:
![webkit_tls_error](https://user-images.githubusercontent.com/68642402/159657134-f5c8dc03-73db-4985-a306-cfead30e99be.png)
I don't use SSL on localhost. It seems like Webkit automatically forces HTTPS. All other browsers are working fine.

**Comment by dgozman** [comment]
@maxibri Could you please share more details? What is the page url you use in `page.goto()`? Looking at the screenshot, it is `https://localhost:3000`, and I guess it should not be? Sharing the config/test would be ideal, so we can reproduce the issue locally.

**Comment by maxibri** [comment]
Hi @dgozman,
inside my `*.spec.js` files i'm using the `beforeEach()` hook with HTTP:
```
test.beforeEach(async ({ page }) => {
  await page.goto(`http://localhost:3000/stories`);
});
``` 

Webkit also routes correctly to `http://localhost:3000`, but then tries to load the assets with HTTPS
![image](https://user-images.githubusercontent.com/68642402/159868796-41bc664e-c844-436d-af84-65bc4e4a206a.png)

**Comment by dgozman** [comment]
This seems like webkit-specific behavior. Here is a similar [StackOverflow question](https://stackoverflow.com/questions/46394682/safari-keeps-forcing-https-on-localhost).

**Comment by janbrasna** [comment]
For anyone running into this issue — check you're not actually setting `upgrade-insecure-requests` Content Security Policy in your app, as WebKit will insist on that even for localhost: https://bugs.webkit.org/show_bug.cgi?id=250776

**Comment by paulschuetz** [comment]
> For anyone running into this issue — check you're not actually setting `upgrade-insecure-requests` Content Security Policy in your app, as WebKit will insist on that even for localhost: https://bugs.webkit.org/show_bug.cgi?id=250776

you are my hero for today 💚
