### ISSUE TITLE
[REGRESSION]: test.setTimeout(0) no longer works

### ISSUE THREAD

**Issue by alisterscott** [microsoft/playwright#12973]
**Context:**
- GOOD Playwright Version: 1.19.2
- BAD Playwright Version: 1.20.0
- Operating System: MacOS

**Code Snippet**

```javascript
  test.only('can help with manual testing', async ({ page }) => {
    test.setTimeout(0) // no timeout
    await page.goto('https://playwright.dev/')
    await page.pause()
  })
```

**Describe the bug**

A timeout of 0 is great for using a Playwright test to launch a browser to do some actions. This doesn't work in 1.20.0 as the browser always closes after 30 seconds

**Comment by dgozman** [comment]
I think this is #12974. Actually closes after a minute, and only with inspector window on MacOS. Updating to v1.20.1 should fix the issue. Thank you for filing!

**Comment by benjamin-thomas** [comment]
> I think this is #12974. Actually closes after a minute, and only with inspector window on MacOS. Updating to v1.20.1 should fix the issue. Thank you for filing!

I was on `Ubuntu 20.04.4 LTS` btw.

v1.20.1 works perfectly for me indeed. Thanks @dgozman!
