### ISSUE TITLE
[BUG] The "Control+V" step in the test does not work when the headless mode is on

### ISSUE THREAD

**Issue by IgorKoryapin** [microsoft/playwright#12977]
**Context:**
- Playwright Version: [1.20.0]
- Operating System: [Windows]
- Node.js version: [v14.15.4.]
- Browser: [Chromium]
- Extra: [Windows 10 Pro 64]

**Code Snippet**
 `await page.keyboard.press("Control+V");`
```

**Describe the bug**

Play steps:
1. enable headless mode ("headless: true") in the config file
2. run the test with the step "Control+V"

**Comment by dgozman** [comment]
Closing in favor of #8114.
