### ISSUE TITLE
[BUG] Playwright try to parse a file which is not related to test

### ISSUE THREAD

**Issue by hungdao-testing** [microsoft/playwright#12990]
**Context:**
- "playwright": "^1.20.0",
    "typescript": "^4.5.5"
- Operating System: Window 11
- Node.js version: 14.18

**Code Snippet**
Running command line
```ts
> npx cross-env NODE_ENV=local playwright test --project=api


Running 0 test using 0 worker


TypeError: Cannot read property 'ADMIN' of undefined

   at src\main\models\user.model.ts:40

  38 |     enum: {
  39 |       values: [
> 40 |         UserRoles.ADMIN,
     |                   ^
  41 |         UserRoles.GUIDE,
  42 |         UserRoles.LEAD_GUIDE,
  43 |         UserRoles.USER,

=================
 no tests found.
=================
```

```javascript
import { test, expect } from '@playwright/test'
import { UserRoles } from '../../../typing/app.type'
import { getUserByRole } from '../../fixtureHandler'

test.describe('Login', () => {
   // test code  
})
```

**Describe the bug**

The Playwright inspect the import file and get error when reading the the file `app.type`, and not sure why the Playwright jumps to src/user.model to read  even though I don't use the imported file in the test code?

If I removed the import statement, the test file runs okie

For more details, please refer to repo
https://github.com/hungdao-testing/playwright

The repo is using mongodb and mongoose is db-driver.

Please follow the step to run project
1. open the ./config/local.env:
a. Update the DB_CONN_STRING: change the dbName from "natours_local" to whatever you want
b. Update DB_USERNAME
c. Update DB_PASSWORD

2. Run: npm run local
3. Run test: npm run test:local:api

**Comment by dgozman** [comment]
I see that test imports `fixtureHandler` that imports the model: https://github.com/hungdao-testing/playwright/blob/main/src/tests/fixtureHandler.ts#L3, so working as expected.

**Comment by hungdao-testing** [comment]
Thanks for spotting it @dgozman . Just would like to why Playwright jumps into model file and get confused by it although I already set the testMatch is `.spec.ts` (playwright config), and think the other `.ts` are compiled/understood by ts-node / or internal Playwright typescript

**Comment by dgozman** [comment]
@hungdao-testing Playwright does read your typescript files itself, and uses some specific ts configuration for this, which does not include enum support.

**Comment by hungdao-testing** [comment]
Could I bypass it by declare `require ('mongoose')` (which is the library control enum in src.model`  file); @dgozman

**Comment by dgozman** [comment]
@hungdao-testing I guess you should try it out and see.

I looked into this a bit more, and there is a dependency cycle: 
- [`user.model.ts` imports `app.type.ts'](https://github.com/hungdao-testing/playwright/blob/main/src/main/models/user.model.ts#L4)
- [`app.type.ts` imports `user.model.ts`](https://github.com/hungdao-testing/playwright/blob/main/src/typing/app.type.ts#L4)

Depending on the luck and import order, this could easily lead to some objects being undefined and produce `TypeError: Cannot read property 'ADMIN' of undefined`. I'd suggest to restructure your project to avoid dependency cycles.
