### ISSUE TITLE
[Question] Where do you run the install Command?

### ISSUE THREAD

**Issue by Luz5020** [microsoft/playwright#12996]
I'm encountering an error when trying to run "playwright install", something along the lines of "playwright is not a command"
So I'm wondering, is the issue that I'm using the wrong terminal? I'm using PowerShell to pip install playwright and pip tells me that playwright is installed, when I try to run playwright install I get an error, however. So am I on the wrong architecture, should I run this with bash or something else? I just keep failing at the very first step and I can't find explicit mention of what command line to run it in.

**Comment by mxschmitt** [comment]
I guess you are using Python?

If your PIP is configured correctly inside the `PATH`, then this works out of the box: `playwright install` if not `python -m playwright install`.

**Comment by Luz5020** [comment]
Okay, yeah python -m fixed it, thanks for the help
