### ISSUE TITLE
[Question] How to get the context of a browser window that is opened by the electron app? 

### ISSUE THREAD

**Issue by tdNelsonPires** [microsoft/playwright#13014]
Hi team,

I'm struggling a bit in finding a way to get the context of a browser window that my electron application triggers to do a Login.

```
test("Launch electron app", async () => {

  let window: Page, cleanup: () => Promise<void>;
  let app: ElectronApplication;

  ({app, window, cleanup} = await start());
  await window.dblclick(workspace.login.inputAccount);
  await window.fill(workspace.login.inputAccount, 'helios');
  await window.click(workspace.login.btnContinue)

  //A chrome browser window is opened after clicking the button btnContinue. 
  //The login credentials are requested on that browser window.

});
```

Any help? 🙏

**Comment by dgozman** [comment]
@tdNelsonPires Do you need to have a handle to the second opened window? [Documentation](https://playwright.dev/docs/api/class-electronapplication#electron-application-wait-for-event) suggests:

```js
const [secondWindow] = await Promise.all([
  electronApp.waitForEvent('window'),
  window.click(workspace.login.btnContinue),
]);
```

**Comment by tdNelsonPires** [comment]
@dgozman thanks for the quick response.
I've tried that before, but it doesn't work in this case. The window I'm talking about is a window on the chrome browser, it's not another electron window.

```
electronApplication.waitForEvent: Timeout 30000ms exceeded while waiting for event "window"

      58 |
      59 |   const [secondWindow] = await Promise.all([
    > 60 |     app.waitForEvent('window'),
         |         ^
      61 |     window.click(workspace.login.btnContinue)
      62 |   ]);
      63 |
```

**Comment by dgozman** [comment]
@tdNelsonPires Let me check whether I understand the issue correctly:
- Use Playwright to automate electron app;
- At some point electron opens a page in the Chrome browser that is installed on the same machine;
- You'd like to automate this new page in the browser.

If this description is correct, then there is no way to do that. Playwright can only automate a browser that was launched with automation enabled, and default browser on the computer is never launched that way. Sorry!

**Comment by tdNelsonPires** [comment]
Yes, that is exactly it. I'll try to find out a way to go around it. Thanks anyway 🙏
