### ISSUE TITLE
[BUG] page.pause() not working in VSCode

### ISSUE THREAD

**Issue by dfdumaresq** [microsoft/playwright#13015]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Node.js version: v14.17.3
- Browser:All
- Extra: Typescript, VS Code
Version: 1.65.2 (Universal)
Commit: c722ca6c7eed3d7987c0d5c3df5c45f6b15e77d1
Date: 2022-03-10T14:33:49.188Z (1 wk ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

**Code Snippet**

```javascript
import { test, expect, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
});

const TODO_ITEMS = [
  'buy some cheese',
  'feed the cat',
  'book a doctors appointment'
];

test.describe('New Todo', () => {
  test('should allow me to add todo items', async ({ page }) => {
    // Create 1st todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');

    // Make sure the list only has one todo item.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0]
    ]);

    // Create 2nd todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[1]);
    await page.locator('.new-todo').press('Enter');

    await page.pause();

    // Make sure the list now has two todo items.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[1]
    ]);

    await checkNumberOfTodosInLocalStorage(page, 2);
  });

});

async function checkNumberOfTodosInLocalStorage(page: Page, expected: number) {
  return await page.waitForFunction(e => {
    return JSON.parse(localStorage['react-todos']).length === e;
  }, expected);
}

```

`$ npx playwright test --project=chromium --headed`

**Describe the bug**

When run inside a VSCode integrated terminal, the test does not pause. When run inside a terminal it does.

**Comment by dgozman** [comment]
This works for me with VSCode Version 1.65.2 on macOS. The test is paused, I see the Playwright Inspector window and can successfully resume. Perhaps something's up with your VSCode setup?

**Comment by dfdumaresq** [comment]
Hmm, thanks! - I see that it does work with VS Code Insiders v1.66.0. But I've disabled all extensions, closed the workspace. Any suggestions on ways to reset/initialize/clear caches? in vscode?

**Comment by dfdumaresq** [comment]
I've removed my settings.json and that fixed my issue. 
`$HOME/Library/Application Support/Code/User/settings.json`
I'll check with the vscode folks about what might be the cause.

**Comment by connor4312** [comment]
The user was running Playwright under the debugger and hitting this code path:

https://github.com/microsoft/playwright/blob/84a0aaaaff813f8d48dc597dea97742304be3e3d/packages/playwright-core/src/client/page.ts#L699-L702
