### ISSUE TITLE
[BUG] xpath  css selector all dont work

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright#13012]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

full code here
```
    const page = await browser.newPage();


    await page.goto('https://www.merchantgenius.io/')
    // console.log(await page.content())
    const yuefen1 =  await page.locator('xpath=//html/body/main/div/div[2]/a')
    console.log('1-',await yuefen1.length)
    const yuefen2 =  await page.locator('div.container > a')
    console.log('2-',await yuefen2.length)

```
it give me underfined,am i missing something

**Comment by ltsuda** [comment]
Locator is not async, so there's no need `await`. Also, to get the number of elements found using the Locator API, use the `.count()` method.

https://playwright.dev/docs/locators
https://playwright.dev/docs/api/class-locator#locator-count

```javascript
    await page.goto("https://www.merchantgenius.io/")
    // console.log(await page.content())
    const yuefen1 = page.locator("xpath=//html/body/main/div/div[2]/a")
    console.log("1-", await yuefen1.count())
    const yuefen2 = page.locator("div.container > a")
    console.log("2-", await yuefen2.count())
```

```bash
❯ npx playwright test

Running 1 test using 1 worker
[chromium] › example.spec.js:3:1 › basic test
1- 523
2- 523

  1 passed (5s)
```

**Comment by dgozman** [comment]
Thank you @ltsuda!

**Comment by wanghaisheng** [comment]
@ltsuda 
sir  for iterating list ,why it tell me get attribute is not a function
    // <a href="/shop/date/2020-08-29"
    const filename = await yuefen.nth(i).get_attribute('href').split('/')[-1]
