### ISSUE TITLE
[Feature] Single cross platform snapshot for non-image content

### ISSUE THREAD

**Issue by ritz078** [microsoft/playwright#13028]
As [mentioned in the documentation](https://playwright.dev/docs/test-snapshots), we can use `.toMatchSnapshot` to create snapshots of text and other content types. In those scenarios, I am aware that the content isn't going to be different on different platforms. In those cases, it becomes helpful if we have a single snapshot for all browsers and operating systems.

**Comment by dgozman** [comment]
Closing in favor of #11134.

**Comment by trusktr** [comment]
@dgozman does disabling the snapshot platform name cause the snapshot to be used for all platforms?

**Comment by dgozman** [comment]
@trusktr For now, you can work around the issue by setting `snapshotSuffix` to an empty string like this:

https://github.com/microsoft/playwright/blob/cdb68448e15f848ebb3f31834c2431e7bd8b681b/tests/playwright-test/golden.spec.ts#L24-L29

**Comment by trusktr** [comment]
Thank you! I see, it matches by file name, regardless of platform since platform is not in the name.
