### ISSUE TITLE
[FEATURE] Provide a way to get the test status after all workers are done 

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13029]
I want to execute a function in the tear down only if the test is failed/passed, is there any func/ fixture that can be passed that will return the test status after all workers?

i.e
```
async function globalSetup(testResult: Status) {
if(testResult == 'Fail') { //do something}
}
```

**Comment by dgozman** [comment]
This is not possible today, but this makes sense as a feature request.

**Comment by amrsa1** [comment]
> This is not possible today, but this makes sense as a feature request.

Yes it would be really interesting feature, should i create a feature request for it or this ticket is enough.

**Comment by dgozman** [comment]
This ticket is a good one already.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
