### ISSUE TITLE
[Question] 'playwright' is not recognized as...

### ISSUE THREAD

**Issue by FrankWizard** [microsoft/playwright#13024]
When I tried to download playwright everything went smoothly until I executed `playwright install`
It threw this error: `'playwright' is not recognized as an internal or external command,
operable program or batch file.` 
Any help on what should I do?

**Comment by hungdao-testing** [comment]
Could you try command `npx playwright install` at the root project folder

**Comment by mxschmitt** [comment]
I guess you are using Python? Or which language binding are you using?

If your PIP is configured correctly inside the `PATH`, then this works out of the box: `playwright install` if not `python -m playwright install`.

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by sounddrill31** [comment]
> I guess you are using Python? Or which language binding are you using?
> 
> If your PIP is configured correctly inside the `PATH`, then this works out of the box: `playwright install` if not `python -m playwright install`.

This worked, thanks!

**Comment by victoramorim-king** [comment]
> I guess you are using Python? Or which language binding are you using?
> 
> If your PIP is configured correctly inside the `PATH`, then this works out of the box: `playwright install` if not `python -m playwright install`.

This worked for me, Thanks!

**Comment by vetab** [comment]
In case if you are using python3 then the command would be **python3 -m playwright install.**

**Comment by dearirshad2** [comment]
In my case i had to do **sudo -s** then **pip3 install playwright** and **playwright install**

**Comment by SrRoc** [comment]
> Eu acho que você está usando Python? Ou qual ligação de idioma você está usando?
> 
> Se o seu PIP estiver configurado corretamente dentro do `PATH`, então isso funciona imediatamente: `playwright install`se não `python -m playwright install`.

isso funcionou pra mim em pleno 2024

**Comment by spragginsdesigns** [comment]
> I guess you are using Python? Or which language binding are you using?
> 
> If your PIP is configured correctly inside the `PATH`, then this works out of the box: `playwright install` if not `python -m playwright install`.

Thank you! This worked like a charm. I always forgot the -m parameter.

**Comment by ritik112** [comment]
Organisation's proxy setup doesn't allow to run these commands that download files from some place, is there a way to download these browsers manually and setup to use with python
