### ISSUE TITLE
[Question] Playwright test acts differently in headless mode.

### ISSUE THREAD

**Issue by shahiakriti** [microsoft/playwright#13025]
Hi guys,

I am trying to automate a program with dragging and dropping using the dragTo() function in playwright. My tests work fine when I run them in headed mode but no dragging and dropping happens when I run it headless mode. Any idea as to what is causing this issue?

thanks!

**Comment by dgozman** [comment]
@shahiakriti Try [recording a trace](https://playwright.dev/docs/trace-viewer) and explore it to see what's going on.

**Comment by dgozman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
