### ISSUE TITLE
[Question]  why im getting  browser.newContext: Target page, context or browser has been closed

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13038]
sometimes my test is failing due to the following 
 browser.newContext: Target page, context or browser has been closed
 
 is there specific reason behind it, or anything to do to avoid it also i notice that its happening with firefox

**Comment by dgozman** [comment]
@amrsa1 Do you have a repro we can run locally? It is hard to help without any details.

**Comment by amrsa1** [comment]
@dgozman here are some more details, I don't have anything special just regular test cases, this error is appearing randomly causing some flakiness in my test but it is always likely to happen with firefox, not sure if its related to afterEach hook

```
import { fixtures as test } from '../../pages/fixture';

test.describe('Landing page Test Suite', () => {

    test.beforeEach(async ({ page, landingPage }) => {
        await page.goto(path.en.landingPage, { waitUntil: "load", timeout: 30000 })
        await landingPage.waitForText('Log in')
    });

    test.afterEach(async ({ page }) => {
        await page.close()
    });

    test.only('test', async ({ browserName, page }) => {
        expect(await page.screenshot({ fullPage: true, timeout: 4000 })).toMatchSnapshot(`${browserName}-EN.png`);
    });
    
    });
```

**Comment by amrsa1** [comment]
actually not related to afterEach hook it's still happening even after removing afterEach hook, 
<img width="1116" alt="Screenshot 2022-03-24 at 22 22 43" src="https://user-images.githubusercontent.com/32042806/160012528-88e13cc9-9197-445b-8772-70007afcae0b.png">

**Comment by dgozman** [comment]
@amrsa1 Interesting! Did you try [recording a trace](https://playwright.dev/docs/trace-viewer)? Perhaps someone closes the page somewhere? If that does not help, run with `DEBUG=pw:browser*` and post logs here.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by amrsa1** [comment]
<img width="1020" alt="Screenshot 2022-04-04 at 09 32 50" src="https://user-images.githubusercontent.com/32042806/161495250-d2883709-0c4f-46cf-bc0c-69debf9c9bf4.png">

**Comment by afaheyguideline** [comment]
I am seeing this issue as well It happens randomly and I can not reproduce. 
  browser.newContext: Browser closed.

**Comment by denis23x** [comment]
+

**Comment by mkbdes** [comment]
Passando para dizer que o problema persiste com maior frequência no navegador firefox

**Comment by kiranmai-perili** [comment]
Hi, 
I am facing the same issue while I am testing my application frequently with firefox. Pls,
![Screenshot (334)](https://user-images.githubusercontent.com/115471627/205635338-e984debe-9f37-417e-a6fb-c0ff61d08238.png)
 give me a solution to this. It was needy for me

**Comment by marycodes92** [comment]
I am also facing this issue and it happens randomly as well without more details. For me it happens only when I run ci but when I try to run on debugger mode I don't get this error. I use chrome.

**Comment by danystatic** [comment]
I was in a hurry trying to look for an answer, but me too. Why would it close itself? there's no apparent reason. hmmm... checking more tomorrow. Love playwright but these little issues are kinda of a hastle.

**Comment by sharm49** [comment]
Does anyone able to solve this issue?

**Comment by antanas-sukevicius** [comment]
in 'playwright.config.ts' check maximum time for test, and increase it if needed.

`
export default defineConfig({
  testMatch: ["*spec.ts"],
  /* Maximum time one test can run for. */
  timeout: 5 * 60 * 1000, //this is five minutes
`

**Comment by MatyPelemene** [comment]
Any other solution?

**Comment by roguestroke** [comment]
I have this problem _Error: browser.newContext: Target page, context or browser has been closed._  
I checked my code, open and close all contexts, according to the documentation. 
It happens randomly. Оn the same test. If I remove the test or skip, the error will start to occur in another test. 
There is only one drop during the entire run, and if you run many tests at once. There is no local problem in the test.
![image](https://github.com/microsoft/playwright/assets/55460819/62dcd703-a40f-464d-ab84-9b7f0f0d6272)
Please open issue and fix it. This makes my test flacky.
PW version 1.35.0

**Comment by flpms** [comment]
Even with 5 minutes timeout I'm still receiving this kind of error when running in VSCode.
![image](https://github.com/microsoft/playwright/assets/4911643/a1f512b4-b51e-4677-a18e-508484d1b15d)

Running with terminar and ui option active I receive the following result:
![image](https://github.com/microsoft/playwright/assets/4911643/c559454d-71ba-4a6e-a23b-9ee11e88d8ec)

Follow my configuration
![image](https://github.com/microsoft/playwright/assets/4911643/d6768124-892e-41c6-97b6-4a1e8c2758f2)

**Comment by amrsa1** [comment]
Hi @mxschmitt i would advice this ticket to be reopened since it seems happening so often

**Comment by mxschmitt** [comment]
We don't monitor closed issues. Please file a new issue with a reproduction. Usually this is caused by missing awaits. 

Make also sure to follow our best practices, especially the linting part.

https://playwright.dev/docs/best-practices

Thanks for your understanding.
