### ISSUE TITLE
[Question]Run Multiple browsers for one project?

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#13046]
Tried my best to find an answer before asking here so I apologize if it already exists. I'm wondering if in playwright you are able to use multiple browsers for the same project?
For example:
```
{
          name: 'Regression',
          grep: /@regg/,
          testDir: './tests',
          retries: 0,
          use: {
            ...devices['Desktop Firefox'],
          }          
        },
```
Let's say I have some tests marked with a '@regg' and I want to run all those tests across all browsers. Is there a way to stack the "...devices" inside the use? or do I have to create multiple projects with the same stuff but change the ...devices as needed?
Ideally I thought I could do something like this:
```
{
          name: 'Regression',
          grep: /@regg/,
          testDir: './tests',
          retries: 0,
          use: {
            ...devices['Desktop Firefox'],
            ...devices['Desktop Chrome'],
            ...devices['Desktop Safari']
          }          
        },
```

If you cannot do this, thanks for your time answering and maybe it can be a possible feature?

**Comment by dgozman** [comment]
@bshostak This is not supported, and most likely will never be supported. That said, you can just copy your project three times to achieve the same:
```js
        {
          name: 'Regression',
          grep: /@regg/,
          testDir: './tests',
          retries: 0,
          use: {
            ...devices['Desktop Firefox'],
          }          
        },
        {
          name: 'Regression',
          grep: /@regg/,
          testDir: './tests',
          retries: 0,
          use: {
            ...devices['Desktop Chrome'],
          }          
        },
        {
          name: 'Regression',
          grep: /@regg/,
          testDir: './tests',
          retries: 0,
          use: {
            ...devices['Desktop Safari'],
          }          
        },
```

**Comment by bshostak** [comment]
@dgozman no problem. Thank you!

**Comment by hwride** [comment]
For any other reasons another option is to specify `--project` multiple times, like
```
npx playwright test --project chromium --project safari
```

From: https://github.com/microsoft/playwright/issues/9108#issuecomment-925831731

**Comment by reharik** [comment]
Why will this never be supported.  If I have say 4 projects and I want them all to run on three browsers   it's just giant mess.  I don't know what language is reading the config files, but I would guess it's js or ts, seems some basic code reuse would be pretty simple here.

**Comment by jaktestowac** [comment]
Should be opened for discussion - overriding project even with just command line can be so useful:
`npx playwright test --project end-to-end --devices ['Desktop Chrome', 'Desktop Safari']`

**Comment by GermanJablo** [comment]
+1 to this.

This would allow us to use the same login dependency for different browsers. Currently this is the way to configure it:

```typescript
  projects: [
    { name: 'setup-chrome', use: { ...devices["Desktop Chrome"] }, testMatch: /.*\.setup\.ts/ },
    { name: "chromium", use: { ...devices["Desktop Chrome"], storageState: 'playwright/.auth/user.json' }, dependencies: ['setup-chrome'] },
    { name: "firefox", use: { ...devices["Desktop Firefox"], storageState: 'playwright/.auth/user.json' }, dependencies: ['setup-chrome'] },
    { name: "webkit", use: { ...devices["Desktop Safari"], storageState: 'playwright/.auth/user.json' }, dependencies: ['setup-chrome'] },
  ],
```

But `npx playwright test --project="chromium" --project="safari" --project="webkit"` run 3 times "setup-chrome" when in fact I want to use the same login:

```typescript
  projects: [
    { name: 'setup-chrome', use: { ...devices["Desktop Chrome"] }, testMatch: /.*\.setup\.ts/ },
    { name: "chromium", use: {
            ...devices['Desktop Firefox'],
            ...devices['Desktop Chrome'],
            ...devices['Desktop Safari']
          } , storageState: 'playwright/.auth/user.json' }, dependencies: ['setup-chrome'] },
  ],
```

**Comment by berkayalparslan** [comment]
i will up this because I find it necessary to implement! :)
