### ISSUE TITLE
[Feature] Option for pdfs not to have clickable links

### ISSUE THREAD

**Issue by jasonparallel** [microsoft/playwright#13049]
When using playwrite to create a pdf would it be possible to have an option not to create clickable links in the pdf from html hyperlinks?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
