### ISSUE TITLE
[Question] Unable to execute a function at the teardown 

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13053]
I'm wondering why function running inside setTimeout will not be executed, also I have the following example as well is not being executed at the teardown

```
import * as nodemailer from 'nodemailer'
const transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: "test@tes.com",
      pass: "ex"
    }
  });
  
  async function globalSetup(config: FullConfig) {
 
            transporter.sendMail(mailOptions, (error, info) => {
                if (error) {
                  console.log(error);
                } else {
                  console.log("Email sent!");
                }
              }); 
}


export default globalSetup;
```

**Comment by mxschmitt** [comment]
This is the same underlying issue as your previous issue (https://github.com/microsoft/playwright/issues/12922#issuecomment-1075378374). JavaScript is an asynchronous, it never blocks except when its a sync API call.

In your case you either need to wrap it in a promise or use their sync variants (there is no sync variant). Luckily nodemailer has also an async API, it automatically returns a promise if you don't specify a callback, see here: https://nodemailer.com/usage/

So something like that should work: `await transporter.sendMail(mailOptions)`

**Comment by amrsa1** [comment]
@mxschmitt it works yes when i have it `await transporter.sendMail(mailOptions)` but not working if it was part of another function 

```
async function findDirAndArchieved() {
    fs.access(test, async (error) => {
        if (error && numberOfRetrials++ < 4) {
            console.log(`-->> Ops!, something went wrong ${error}, try number:${numberOfRetrials}`);
            findDirAndArchieved();
        } else {
            console.log(`-->> √ Report ${report_dir} Dir has been found!`);
            execSync('zip -r playwright-report.zip playwright-report', {
                cwd: './',
            });
            console.log('-->> √ Report has been archived!');
         await transporter.sendMail(mailOptions)
        }
    })
};

async function globalSetup(config: FullConfig) {
    await findDirAndArchieved()
}



export default globalSetup;
```

**Comment by mxschmitt** [comment]
This is because you are in a callback of `fs.access` which is directly returning and not waiting for the callback Promise to resolve.

Use `fs.accessSync` and get rid of that callback then it will work: https://nodejs.org/api/fs.html#fsaccesssyncpath-mode

**Comment by mxschmitt** [comment]
Closing as per above.

**Comment by amrsa1** [comment]
@mxschmitt 
I have tried many solutions, but seems that main issue is that reporting is part of the worker so im unable to get the playwright-report using teardown function and the directory will be generated after teardown is being executed
