### ISSUE TITLE
[BUG] page does not return functions through evaluate

### ISSUE THREAD

**Issue by hatufacci** [microsoft/playwright#13059]
**Context:**
- Playwright Version: 1.19.0
- Operating System: Mac
- Node.js version: 12.19.0
- Browser:  Chromium

 i m trying execute script in browser, this script return function, and it return undefined for function result
```
 await page.evaluate(() => window.utui.service.post);
```
if run it in browser console:
<img width="1079" alt="Screen Shot 2022-03-22 at 15 00 50" src="https://user-images.githubusercontent.com/4963181/160069465-407afb2b-266a-4a46-99d0-ad73039c5c10.png">

**Comment by dgozman** [comment]
Playwright does not return functions from the browser to the node, because you cannot call them in the node context. Here is a [guide](https://playwright.dev/docs/evaluating) about evaluating JavaScript.

If you'd like a handle to a function that you can call later, do the following:
```js
// Get the handle to a specific function.
const postHandle = await page.evaluateHandle(() => window.utui.service.post);
// Later on, call this function with some arguments.
await postHandle.evaluate((post, args) => post(...args), ['arg1', 'arg2', 'arg3']);
```
