### ISSUE TITLE
[BUG] Fix doc typo: request.respond() -> request.fulfill()

### ISSUE THREAD

**Issue by h2non** [microsoft/playwright#1306]
Minor issue in this doc method not consistent with the actual API:
https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#requestfulfillresponse

It should change `request.respond()` with `request.fulfill()` as the API changed from Puppeteer.

Also, great work with Playwright. Very promising!

**Comment by aslushnikov** [comment]
We'd be very happy with a pull request for this! :)

**Comment by mayankkt9** [comment]
Can I raise a PR ?

**Comment by aslushnikov** [comment]
@mayankkt9 please do!

**Comment by h2non** [comment]
It seems to be fixed now.

**Comment by mxschmitt** [comment]
@h2non looks like it's fixed or not?

**Comment by h2non** [comment]
The linked PR was not merged, and I still see the type in `master`.

**Comment by mxschmitt** [comment]
> The linked PR was not merged, and I still see the typo in `master`.

Hm, are you sure that you took a look on master? The link in your issue description is pinned to the `v0.11.1` tag.
That's for master: https://github.com/microsoft/playwright/blob/master/docs/api.md

**Comment by h2non** [comment]
Gotcha! Closing now!
