### ISSUE TITLE
[BUG] Intermittent net::ERR_NETWORK_CHANGED error when running in kubernetes cluster.

### ISSUE THREAD

**Issue by FeargusOG** [microsoft/playwright#13062]
**Context:**
- Playwright Version: 1.20.0
- Operating System: Linux container (`mcr.microsoft.com/playwright/python:v1.20.0-focal`)
- Python version: 3.8.10
- Browser: Chromium
- Extra: Linux container running in a kubernetes cluster in AWS.

**Code Snippet**

```python
def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    context.set_default_timeout(60000)

    # Open new page
    page = context.new_page()

    # Go to the stack endpoint
    logging.info("Probing endpoint "+endpoint)
    page.goto(endpoint)
```

**Describe the bug**

I intermittently (maybe 50:50 chance) see the following stacktrace thrown when running the above code (in the official `mcr.microsoft.com/playwright/python` image) in a kubernetes cluster:

```
INFO:root:Probing endpoint https://<redacted>/
Traceback (most recent call last):
  File "catchpoint-replica.py", line 79, in <module>
    run(playwright)
  File "catchpoint-replica.py", line 36, in run
    page.goto(endpoint)
  File "/usr/local/lib/python3.8/dist-packages/playwright/sync_api/_generated.py", line 7344, in goto
    self._sync(
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_page.py", line 487, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/usr/local/lib/python3.8/dist-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: net::ERR_NETWORK_CHANGED at https://<redacted>/
=========================== logs ===========================
navigating to "https://<redacted>/", waiting until "load"
============================================================
```

I have yet to see it when running the script on my local machine (MacOS).

Any ideas what is causing this or how to fix it? Thanks!

**Comment by dgozman** [comment]
Sounds like your docker is switching between networks (perhaps you have Wi-Fi plumbed through to the docker). [Here is](https://stackoverflow.com/questions/44678168/docker-and-chromium-neterr-network-changed) a similar StackOverflow question.

**Comment by FeargusOG** [comment]
@dgozman thanks for the reply. It's a pretty vanilla k8s cluster running in AWS - I don't think there should be anything particularly unusual about the network in the cluster. I also do not think disabling docker will be an option either.

**Comment by mxschmitt** [comment]
Playwright does not do anything fancy with the network stack. The network requests are coming from the browser, so maybe Chromium has some interesting behaviour included which causes that.

Seems related to when the IP of the DNS entry has changed:
- https://stackoverflow.com/questions/44854296/neterr-network-changed-on-chrome-on-https-socket-connection
- https://superuser.com/questions/747735/regularly-getting-err-network-changed-errors-in-chrome
- https://github.com/kyma-project/kyma/issues/2705

this seems like a workaround: https://github.com/kyma-project/kyma/issues/2705#issuecomment-468241797

Closing since this is not caused by Playwright and is more browser behaviour/a configuration issue.

**Comment by zifter** [comment]
I'm getting the same error time to time:

For anyone, how is looking more information:
Playwright Version: 1.32.1
Operating System: Linux container (custom Image based on python:v1.32.1-jammy)
Python version: 3.10.7
Browser: Chromium
Extra: Linux container running in a kubernetes cluster in GCP (GKE).

Playwright container run by podman inside pod, which is running by containerd (default container runtime in GKE).

**Comment by feliche93** [comment]
I am also seeing this error now. Didn't happen before. @zifter did you find any solution to fix it?

**Comment by zifter** [comment]
Hi, @feliche93 ! Unfortunately, no, I still have that error issue. 

So, I fix it with other point of view.

I'm using playwright for e2e tests.

The error happens only once per test run and only for first test in the order, so I simply added retry policy for the failed tests. On the second retry issue does not repeat any more.

I'm using pytest for running tests, so package 
https://pypi.org/project/pytest-rerunfailures/  adds that behaviour very easy.

It makes tests very stable to that kind of network error and any other network errors like that.

**Comment by forelock7** [comment]
I also faced with the same issue. It happens all the time sporadically in different tests mostly after changing page. 
Web application is deployed in Kubernetes with SSL.
"@playwright/test": "^1.35.0"
devices['Desktop Chrome']
ignoreHTTPSErrors: true

**Comment by jan-osch** [comment]
For anyone experiencing this issue: you should try adding a short sleep to your pods, after they become ready, but before starting the playwright workload. The EKS VPC CNI is applying some changes to the pod after it becomes ready, which is causing the NETWORK_CHANGED error. Try adding a sleep of 10s before starting your playwright workload, to see if it resolves the issue, and then look for an optimal lower value using a bi-sect.

**Comment by ribbles** [comment]
4 years later and still experiencing this intermittently.
