### ISSUE TITLE
[Feature] Add total time of the whole run to the Playwright report

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#13069]
The Playwright report has a summary of a run of each file.
![image](https://user-images.githubusercontent.com/52656401/160172537-cc50c2e2-64bf-4564-88f4-c06e88047db9.png)

I think adding the summary of the whole run - will be useful too.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
