### ISSUE TITLE
[Question] Getting-started more details for use existing browser needed

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#13080]
## Where am i stuck?

On [use existing browser channel](https://playwright.dev/docs/browsers) it says

> Playwright's Firefox version matches the recent [Firefox Stable](https://www.mozilla.org/en-US/firefox/new/) build.

This will likely not work for our company because we use firefox esr (and very often an older version). The [section google-chrome or microsoft-edge](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) states

> Playwright ... can operate against the stock Google Chrome and Microsoft Edge browsers available on the machine

This sounds promising. 

 - Could you elaborate where the provided configuration lines (see code below) have to be put?
 - How to proceed from here?

```
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    channel: 'chrome',
  },
};
export default config;
```

The reading of the following lines is optional and just to give you the full context of my previous steps and the current state of affairs. 

## What happened before - read is optional

Under windows 10 using node v14.16.0 and npm 6.14.11 on a non-elevated node-js command prompt i entered this command

    C:\dev\webtest>npm init playwright@latest play-hello

this was partly succesfull 

```
npx: installed 1 in 2.07s
Getting started with writing end-to-end tests with Playwright:
Initializing project in 'play-hello'
√ Do you want to use TypeScript or JavaScript? · TypeScript
√ Where to put your end-to-end tests? · tests
√ Add a GitHub Actions workflow? (Y/n) · false
Initializing NPM project (npm init -y)…
Wrote to C:\dev\webtest\play-hello\package.json:
....
Installing Playwright Test (npm install --save-dev @playwright/test)…
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN play-hello@1.0.0 No description
npm WARN play-hello@1.0.0 No repository field.

+ @playwright/test@1.20.1
added 190 packages from 184 contributors in 19.739s
```
But installing  browsers / chromium failed

```
Downloading browsers (npx playwright install)…
Failed to install browsers
Error: Failed to download chromium v978106, caused by
Error: connect ETIMEDOUT 13.107.213.45:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Error: Command failed: npx playwright install
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at executeCommands 
        (C:\Users\...\AppData\Roaming\npm-cache\_npx\135796\node_modules\create-playwright\lib\index.js:4519:39)
    at Generator.run 
        (C:\Users\...\AppData\Roaming\npm-cache\_npx\135796\node_modules\create-playwright\lib\index.js:4593:5)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async C:\Users\...\AppData\Roaming\npm-cache\_npx\135796\node_modules\create-playwright\lib\index.js:4770:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 30724,
  stdout: null,
  stderr: null
}
```
Based on #9858 i wondered if using an elevated nodes.js command-prompt would solve this issue but even with an elevated node-prompt i did run into the same issue.  I guess that our proxy / firewall blocks the URI to the browser files?!

But [Playwright getting started](https://playwright.dev/docs/intro#installation) also mentions: 

> You can optionally install only selected browsers, see [install browsers](https://playwright.dev/docs/cli#install-browsers) for more details. Or you can install no browsers at all and use existing [browser channels](https://playwright.dev/docs/browsers).

Continue at top.

**Comment by surfmuggle** [comment]
format added

**Comment by ltsuda** [comment]
I didn't try to reproduce but if you think it's a proxy issue, can you try the following?

https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy

**Comment by surfmuggle** [comment]
Using powershell as an admin 

 - was able to set the proxy  `$env:HTTPS_PROXY="https://192.0.2.1"` and

- was able to install the files `npx playwright install` 

Powershell

```
PS C:\WINDOWS\system32> $env:HTTPS_PROXY="https://192.0.2.1"
PS C:\WINDOWS\system32> npx playwright install
Downloading Playwright build of chromium v978106 - 103.8 Mb [====================] 100% 0.0s
Downloading Playwright build of ffmpeg v1007 - 1.4 Mb [====================] 100% 0.0s
Downloading Playwright build of firefox v1319 - 75.7 Mb [====================] 100% 0.0s
Downloading Playwright build of webkit v1616 - 56.3 Mb [====================] 100% 0.0s
```

They are located under `C:\Users\<myUser>\AppData\Local\ms-playwright`. 

Using the node command prompt did result in the same problem as above. 
So i tried powershell elevated (run as admin) and instead of typescript i picked javascript. 

```
PS C:\dev\webtest> npm init playwright@latest play-hello-powershell-admin
npx: installed 1 in 2.438s
Getting started with writing end-to-end tests with Playwright:
Initializing project in 'play-hello-powershell-admin'
√ Do you want to use TypeScript or JavaScript? · JavaScript
√ Where to put your end-to-end tests? · tests
√ Add a GitHub Actions workflow? (Y/n) · false
Initializing NPM project (npm init -y)…
Wrote to C:\dev\webtest\play-hello-powershell-admin\package.json:

{ "name": "play-hello-powershell-admin", "version": "1.0.0",   "description": "",  "main": "index.js",  
"scripts": {  "test": "echo \"Error: no test specified\" && exit 1" }, "keywords": [], "author": "", "license": "ISC"}


Installing Playwright Test (npm install --save-dev @playwright/test)…
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN play-hello-powershell-admin@1.0.0 No description
npm WARN play-hello-powershell-admin@1.0.0 No repository field.

+ @playwright/test@1.20.1
added 190 packages from 184 contributors in 33.352s

16 packages are looking for funding
  run `npm fund` for details

Downloading browsers (npx playwright install)…
Writing play-hello-powershell-admin\playwright.config.js.
Writing play-hello-powershell-admin\tests\example.spec.js.
Writing play-hello-powershell-admin\package.json.
✔ Success! Created a Playwright Test project at C:\dev\webtest\play-hello-powershell-admin
```
So this seems to work. 

Thanks for you help. 
Any hints how i can use the path `existing browser` without installing the apps  above?

**Comment by ltsuda** [comment]
Cool!

I didn't find anywhere how to use existing browsers, I'm sorry. Also, do you mean existing on your system right? Not installed by playwright.

I think might exist an issue about Firefox ESR not being supported, I'm not sure but it might be a good idea search in the issues

**Comment by ltsuda** [comment]
Here, there's this argument `executable_path` for existing browsers

https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch

**Comment by dgozman** [comment]
Firefox ESR is not supported, sorry.

If you follow the [Getting Started](https://playwright.dev/docs/intro#configuration-file) guide, it explains the configuration file. When you run `npm init playwright`, it printed the line that shows where you can find the config file. Explore it to see how `channel: chrome` is used.
```
Writing play-hello-powershell-admin\playwright.config.js.
```
