### ISSUE TITLE
Cannot run any Playwright test

### ISSUE THREAD

**Issue by ckmoga** [microsoft/playwright#13092]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows 10
- Node.js version: 16.13.0]
- Browser: All
- Extra:

**Describe the bug**

A fresh installation of Playwright and attempting to run example spec produces this error:

```
$ npx playwright test

Running 0 test using 0 worker


Error: tests\example.spec.ts:5:12: Playwright Test did not expect test.beforeEach() to be called here.
Most common reasons include:
- You are calling test.beforeEach() in a configuration file.
- You are calling test.beforeEach() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependenices in your package.json depends on @playwright/test.

   at ..\node_modules\@playwright\test\lib\util.js:198

  196 |
  197 | function errorWithLocation(location, message) {
> 198 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  199 | }
  200 |
  201 | function expectType(receiver, type, matcherName) {

    at errorWithLocation (C:\projects\virtonomy\web_platform_main\e2e\node_modules\@playwright\test\lib\util.js:198:10)
    at TestTypeImpl._ensureCurrentSuite (C:\projects\virtonomy\web_platform_main\e2e\node_modules\@playwright\test\lib\testType.js:78:41)
    at TestTypeImpl._hook (C:\projects\virtonomy\web_platform_main\e2e\node_modules\@playwright\test\lib\testType.js:129:24)
    at Function.beforeEach (C:\projects\virtonomy\web_platform_main\e2e\node_modules\@playwright\test\lib\transform.js:253:12)
    at Object.<anonymous> (C:\projects\virtonomy\web_platform_main\e2e\tests\example.spec.ts:5:12)
    at Module._compile (C:\Projects\virtonomy\web_platform_main\e2e\node_modules\pirates\lib\index.js:136:24)
    at Object.newLoader (C:\Projects\virtonomy\web_platform_main\e2e\node_modules\pirates\lib\index.js:141:7)

=================
 no tests found.

To open last HTML report run:

  npx playwright show-report

```

package.json
```
{
  "name": "e2e",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.20.1"
  }
}
```

**Comment by ckmoga** [comment]
Turned out the problem is related to Git Bash. Tests run fine when executed in Windows CMD. I think it has to do with double global.ts

**Comment by fisnikbatusha** [comment]
I also had this issue. In my case the problem was I was executing `npx playwright test` from root directory and not inside `tests` repository.

**Comment by gokul-sol** [comment]
Hi I too have the same error, when using Playwright version 1.22.2 with saucelabs .. any help would be appreciated, thanks in advance
```
$ saucectl run
Error: tests\*.spec.ts:9:12: Playwright Test did not expect test.describe() to be called here.
Most common reasons include:
- You are calling test.describe() in a configuration file.
- You are calling test.describe() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependenices in your package.json depends on @playwright/test.

   at ..\node_modules\@playwright\test\lib\util.js:221

  219 |
  220 | function errorWithLocation(location, message) {
> 221 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  222 | }
  223 |
  224 | function expectTypes(receiver, types, matcherName) {

    at errorWithLocation (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\util.js:221:10)
    at TestTypeImpl._ensureCurrentSuite (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:79:41)
    at TestTypeImpl._describe (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\testType.js:106:24)
    at Function.describe (D:\sauce-playwright-runner\2.9.0\bundle\__project__\node_modules\@playwright\test\lib\transform.js:269:12)
    at Object.<anonymous> (D:\sauce-playwright-runner\2.9.0\bundle\__project__\tests\casesearchtest.spec.ts:9:12)

```

**Comment by qwertie** [comment]
I am having this problem also. My configuration is in playwright.config.ts but Playwright is ignoring it.

~~~
C:\...\UI>npx playwright test --project=chromium

Running 0 test using 0 worker


Error: ui-tests\scenario.spec.ts:32:12: Playwright Test did not expect test.beforeAll() to be called here.
~~~

The same code **is** working on the machine of the developer who originally wrote our playwright scripts. We are using `yarn install` (with yarn.lock in source control), so presumably it's not that we have different node_modules...

The advice above didn't work but I found a workaround: the _Playwright Test for VSCode (ms-playwright.playwright)_ extension **is** able to run and debug our tests.

**Comment by rgripper** [comment]
@qwertie In my case I had multiple packages of a monorepo with different versions of `@playwright/test`. As soon as I updated devDepencencies of each package to the same version, it started working. I was using pnpm exactly to _not have_ these version collisions, but here I am 👎 .

**Comment by qwertie** [comment]
Yeah, I forgot to mention that only one version of @playwright/test is installed in my case.

**Comment by glvno** [comment]
> Turned out the problem is related to Git Bash. Tests run fine when executed in Windows CMD. I think it has to do with double global.ts

I'm also using git bash, and in my case I had CDed into a directory with incorrect casing, e.g. `myplaywrightdir` instead of `myPlaywrightDir`.

**Comment by prushforth** [comment]
> I'm also using git bash, and in my case I had CDed into a directory with incorrect casing, e.g. myplaywrightdir instead of myPlaywrightDir. Going up a directory and then cding back down into the dir with the correct casing fixed the problem for me.

I encountered this problem when I used lowercase paths to cd with powershell to the project directory.  When I navigated from c:\ into the full directory path with the correct casing, the problem disappeared.

**Comment by andyhinds** [comment]
This happened to me as well. I changed the casing of my folder names in Windows Explorer, but MS Code was still "using" the original casing in the terminal window, and it failed to run the tests. Navigating out and back into the folder in Code using the correct casing resolved the issue.

**Comment by jpaxtonrs** [comment]
@gokul-sol Did you ever figure out the issue when wanting to run your Playwright tests in Saucelabs?

**Comment by sfc-gh-pleszczewicz** [comment]
> 

@jpaxtonrs for me adding `node_modules` to `.sauceignore` did the trick. if you have some packages that you need i believe [this](https://docs.saucelabs.com/web-apps/automated-testing/playwright/yaml/#npm) part of config should work

**Comment by abhay-ranjan-hitachi** [comment]
I avoided using tab to complete file path in terminal. I used npx playwright test ./tests/example.spec.js and it worked

**Comment by abhishek747400** [comment]
> I also had this issue. In my case the problem was I was executing `npx playwright test` from root directory and not inside `tests` repository.

This was indeed the problem for me. Thanks a lot

**Comment by aah-alex** [comment]
> > Turned out the problem is related to Git Bash. Tests run fine when executed in Windows CMD. I think it has to do with double global.ts
> 
> I'm also using git bash, and in my case I had CDed into a directory with incorrect casing, e.g. `myplaywrightdir` instead of `myPlaywrightDir`. Going up a directory and then cding back down into the dir with the correct casing fixed the problem for me.

This fixed for me. Why is that an issue however?

**Comment by ThinhVD7** [comment]
I got this issue when run the feature file XD it just suddenly appear, everything rung well yesterday

**Comment by noahbaron91** [comment]
I had this issue when using yarn workspaces and having the e2e tests in a non root folder.

Adding: `"workspaces": {
    "nohoist": [
      "**"
    ]
  }` to packages/e2e/package.json was able to resolve the error for me

**Comment by ridplace** [comment]
same problem. I'm on windows

**Comment by ChristinaNT** [comment]
I had vitest in my package dev and dependencies and that helped to solve the problem for me

**Comment by acapro** [comment]
I had the same problem with **pnpm**. It was resolved by using `pnpm exec playwright` test instead of `pnnpm dlx playwright test`.

**Comment by czibbelvin** [comment]
> I had the same problem with **pnpm**. It was resolved by using `pnpm exec playwright test` instead of `pnnpm dlx playwright test`.

In case anyone else is searching: Same goes for **yarn**. It wasn't working for me with `yarn dlx playwright test` but did with `yarn exec playwright test`.

**Comment by pelly-ryu** [comment]
None of above worked but `pnpm rm playwright`, `pnpm i` solved my problem.
( https://stackoverflow.com/a/73856094 )

my case: pnpm workspace. only 1 playwright in the workspace.

**Comment by asdf23** [comment]
I'm not sure if this is related but it seems to be.
If I run playwright in a batch file the line after npx.. will not run:

```
echo PlayWright %DATE% %TIME% >> log.txt
npx playwright test
:: this will never run
echo Node %DATE% %TIME% >> log.txt
node index.js
```

---

Instead this will work

```
::batch1.bat
CALL batch2.bat
CALL batch3.bat
```

```
::batch2.bat
npx playwright test
```

```
::batch3.bat
node index.js
```

It's cumbersome, but I need this to work and move on. I believe this to be a bug with how playwright exits.

**Comment by 0xIslamTaha** [comment]
```bash
yarn remove playwright
yarn create playwright
yarn install playwright
```

**Comment by Jordan466** [comment]
Just adding my 2c since I'm getting this as well.

My tests won't run in powershell or bash suddenly, but _will_ run in command prompt. 
Changing package managers and node versions changes nothing.

**Comment by skasimova** [comment]
> I also had this issue. In my case the problem was I was executing `npx playwright test` from root directory and not inside `tests` repository.

Thanks a lot!! It turned out to be my issue too

**Comment by daleyjem** [comment]
> > I had the same problem with **pnpm**. It was resolved by using `pnpm exec playwright test` instead of `pnnpm dlx playwright test`.
> 
> In case anyone else is searching: Same goes for **yarn**. It wasn't working for me with `yarn dlx playwright test` but did with `yarn exec playwright test`.

Playwright already registers it's own `package.json` `bin` attribute. Just `yarn playwright test` seemed to work for me.

**Comment by LironHazan** [comment]
I'm still having such issue, using pnpm 9.6.0 (running on mac)
Unfortunately non of the above worked for me, tried upgrading to @playwright/test 1.45.3 as well 

```dependencies:
@estruyf/github-actions-reporter 1.8.0
└── @playwright/test 1.44.1 peer

devDependencies:
@playwright/test 1.44.1```

**Comment by AngelTest2004** [comment]
I had the same issue. My solution is :
The playwright.config.ts defines testDir, update it. This makes sense to me.

**Comment by s1nistr4** [comment]
Couldn't we have like, an actual error output of where specifically the error is? Instead of just test() can't be called here and nothing to work with?

**Comment by SritamKuRout** [comment]
Hi when I am creating new spec.js file it is not running in the terminal but default files are executed on terminal using npz playwright test command
