### ISSUE TITLE
[BUG] Video embeds don't render

### ISSUE THREAD

**Issue by palewire** [microsoft/playwright#13093]
If I screenshot NYTimes.com when there's a video in the main section, as there is now, the video does not render. Do I need to do something with dependencies for chromium?
![20220326_082030](https://user-images.githubusercontent.com/9993/160246108-42fefedf-56a1-4113-b6e8-ca4f504d6c87.jpg)

**Comment by rwoll** [comment]
See https://playwright.dev/docs/browsers#when-to-use-google-chrome--microsoft-edge-and-when-not-to. The page is likely using a Media codec not available in Chromium. You can try testing with the Chrome channel instead. (Search for `channel` in the docs search, and you'll see different ways of using channels depending on your use case/setup.)

**Comment by rwoll** [comment]
Per above, closing for now, but feel free to open a new issue if the issue persists (or if all video embeds are broken for you regardless of website).

Thanks!

**Comment by palewire** [comment]
Thanks for this tip. I made some [downstream changes](https://github.com/simonw/shot-scraper/pull/52) to the shot-scraper derivative tool I'm using to allow for usage of Chrome (as well as Firefox). After those changes shipped I was able to upgrade my news homepage bot at [palewire/news-homepages](https://github.com/palewire/news-homepages)

The result is that our shots now like this instead. Thank you for your help, @rwoll.

![nytimes-after](https://user-images.githubusercontent.com/9993/160511732-408c631c-76a0-4b5b-93ec-69e3048c0961.jpg)

You can see it shining on Twitter [here](https://twitter.com/newshomepages/status/1508608446274449410)
