### ISSUE TITLE
[Question] chromeUserData and browserContext relationship

### ISSUE THREAD

**Issue by nicoandmee** [microsoft/playwright#13098]
I'm curious how playwright handles the chrome user data/profile directory in relation to browser contexts. If I have multiple contexts, does each have its own directory? If not, is there no way at all to determine which directory was used when context is launched with `newContext()`? I assume it is stored somewhere, so that playwright knows which directory to cleanup on exit.

**Comment by rwoll** [comment]
> If I have multiple contexts, does each have its own directory?

Without getting into implementation details, you can think of each context as an isolated Incognito profile. Each context has Its own cookies, local storage, etc. The actual user data directory is considered part of the implementation detail, so should be opaque to the user.

However, for curiosities sake, you can see what's happening under the hood by setting `DEBUG=pw:*` and running:

```js
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch();
    await browser.newContext();
    await browser.newContext();
    await browser.newContext();
    await browser.close();
})()
```

There you'll see there's actually only one User Data Directory (specified at browser launch), and then https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createBrowserContext are issued to create and back each Playwright Context.

> If not, is there no way at all to determine which directory was used when context is launched with newContext()?

You can use https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context if you want to specify the `userDataDir` (and know where the data will be).


Can you elaborate on your use case for needing visibility into the User Data Directory?

**Comment by rwoll** [comment]
Closing, but feel free to comment after, or re-open if there's still an issue! Thanks!

**Comment by DeHby** [comment]
> Closing, but feel free to comment after, or re-open if there's still an issue! Thanks!

Is it possible to use Browser.launch while supporting custom settings for the userdata directory? 
I noticed that the default directory is generated inside %TEMP%
Or is this not part of the CDP category? I noticed that the folder name is a custom prefix
