### ISSUE TITLE
[Feature] mouse position

### ISSUE THREAD

**Issue by Rumatoid** [microsoft/playwright#13109]
How I can get current mouse position?

**Comment by rwoll** [comment]
This is not currently supported via an explicit Playwright API.

We assume you're interacting with the page more abstractly (i.e. `page.locator('.my-element').click()`) so you don't need the actual coordinates; or (rarely) explicitly moving the mouse (via https://playwright.dev/docs/api/class-mouse#mouse-move) where the coordinates are known to you.

Depending on your use case, you can:
1. Get the cursor position via JS in the page: https://playwright.dev/docs/evaluating
2. Get the position of an element https://playwright.dev/docs/api/class-locator#locator-bounding-box

Can you share more about your use-case?

**Comment by Rumatoid** [comment]
Its very sadly

**Comment by Misha31** [comment]
page.evaluate("document.addEventListener('mousemove', event => {window.pageX = event.clientX; window.pageY = event.clientY})")
position = page.evaluate(
                    """() => {
                      return {
                        x: window.pageX,
                        y: window.pageY,
                      }
                    }"""
                )
print(position)

**Comment by hkfsc** [comment]
@Misha31 
page.mouse.move(1, 1)

page.evaluate("document.addEventListener('mousemove', event => {window.pageX = event.clientX; window.pageY = event.clientY})")
position = page.evaluate(
                    """() => {
                      return {
                        x: window.pageX,
                        y: window.pageY,
                      }
                    }"""
                )
print(position)

Will not be 1,1
> print(position)

**Comment by hkfsc** [comment]
@Misha31 
```
page.mouse.move(1, 1)

page.evaluate("document.addEventListener('mousemove', event => {window.pageX = event.clientX; window.pageY = event.clientY})")
position = page.evaluate(
                    """() => {
                      return {
                        x: window.pageX,
                        y: window.pageY,
                      }
                    }"""
                )
print(position)
```

Result will not be 1,1

**Comment by hkfsc** [comment]
> ```
> page.evaluate("document.addEventListener('mousemove', event => {window.pageX = event.clientX; window.pageY = event.clientY})")
> position = page.evaluate(
>                     """() => {
>                       return {
>                         x: window.pageX,
>                         y: window.pageY,
>                       }
>                     }"""
>                 )
> print(position)
> ```

Injecting js is a bad idea for implementing such things, you will know later...
And playwright should not inject any scripts by itself, otherwise why CDP exists?
Currently I think, we need to wait upstream CDP support this function, then playwright can add this.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by PuruVJ** [comment]
Really need this feature

**Comment by TomasHubelbauer** [comment]
To get mouse position following an action method that changes the mouse position, like `hover`, this is what I ended up using to mimic a relative drag (since `mouse.move` takes absolute coordinates):

```
const bounds = await locator.boundingBox();
expect(bounds).not.toBe(null);

// Help TypeScript understand the `expect` ensure `bounds` is not `null`
if (!bounds) {
  throw new Error('Bounds are null');
}

// Note that mouse events in Playwright also send pointer events
await page.mouse.down();

// Note that Playwright does not expose the mouse position but we know the
// `hover` will hover the center of the element (verifiable in `--ui` mode)
const mouseX = bounds.x + bounds.width / 2;
const mouseY = bounds.y + bounds.height / 2;

// Note that these coordinates are absolute not relative to the moused element
await page.mouse.move(mouseX + x, mouseY + y);
await page.mouse.up();
```
