### ISSUE TITLE
[BUG] Cannot remove header in `route.continue`

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#13106]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Linux
- Node.js version: 17.8.0
- Browser: Chromium

**Code Snippet**

```javascript
const playwright = require('playwright');

require('http').createServer((request, response) => {
        response.end('');
}).listen(8888);

(async () => {
        const browser = await playwright.chromium.launchPersistentContext('', {
                headless: false,
        });

        const page = await browser.newPage();

        await page.route('**/*', (route, request) => {
          // Override headers
          const headers = {
            ...request.headers(),
            foo: 'bar', // set "foo" header
            origin: undefined, // remove "origin" header
          };
          route.continue({headers});
        });

        await page.goto('http://localhost:8888/', { waitUntil: 'load' });
})();
```

**Describe the bug**

The example https://playwright.dev/docs/next/api/class-route#route-continue is broken.

```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

route.continue: headers[7].value: expected string, got undefined
    at RouteHandler.handler (/home/szm/Desktop/cache/bug6.js:21:18)

Node.js v17.8.0
```

**Comment by rwoll** [comment]
Thanks for the report! I repro'd locally. 

Does using `delete` built-in before passing along the headers work for your use case?

```
const headers = {
  ...request.headers(),
  foo: 'bar'
};

delete headers['x-some-header'];
…
```

Regardless, we'll either update the docs or make the doc example work!

---

Note from repro: The error is likely from our protocol type def: https://github.com/microsoft/playwright/blob/1471bb71776cf84223190e1552ee4e055db1547a/packages/playwright-core/src/protocol/protocol.yml#L2442

**Comment by szmarczak** [comment]
> Does using delete built-in before passing along the headers work for your use case?

It doesn't. I guess the headers are merged.

**Comment by Horsty80** [comment]
I opened an issue #13527 , maybe it's the same issue than here with the `route.continue()`

**Comment by yury-s** [comment]
> It doesn't. I guess the headers are merged.

I can only reproduce it in WebKit, the `origin` header is deleted fine in Chromium and Firefox, adding a test for that.

Can you share a code snippet that reproduces it in Chromium with `delete headers['origin']`?

**Comment by szmarczak** [comment]
@yury-s Please note that I'm removing the `origin` header

**Comment by yury-s** [comment]
> @yury-s Please note that I'm removing the `origin` header

This is being addressed separately (setting a field to undefined will be treated as deleting it, currently it throws 'route.continue: headers[5].value: expected string, got undefined'). You mentioned above that calling `delete` didn't work for you, did we get it wrong?

**Comment by szmarczak** [comment]
Pardon me, `delete headers.origin` works like a charm. For some reason I was testing `delete headers['user-agent']` instead.

So yeah, this issue is just about the `undefined` error.

**Comment by yury-s** [comment]
Thanks for confirming. Setting to `undefined` should now delete headers. I looked at WebKit implementation and there is no simple way to make it remove/update origin header, I've filed a separate issue for that (https://github.com/microsoft/playwright/issues/13886) and will wait until there is more demand for this before implementing any suboptimal solutions.

**Comment by szmarczak** [comment]
Thank you!
