### ISSUE TITLE
[Question] Using For.. await with PlayWright test (TypeScript)

### ISSUE THREAD

**Issue by chrisreddington** [microsoft/playwright#13102]
Hi there,

I have begun building out a Test Suite for my blog cloudwithchris.com. It is built using the Hugo Static Site Generator, so I know what content should be available ahead of time. I plan to read through all of the markdown files (e.g. blog posts, podcast episodes), and check that certain data is in place (e.g. Titles, Banner Images, SEO Metadata, etc.)

I am trying to optimise the execution of the tests before I invest too much time into building further tests, but hitting an issue.

I am trying to use the [For... await pattern](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) in JavaScript to allow the tests to be executed asynchronously.

As soon as I put the ``await`` keyword before a test, e.g. ``await test('Check title is correct:.....')``, it will then fail with the below error;

```
Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
```

Is this because test returns a void, as per https://playwright.dev/docs/api/class-test#test-call ? Are there any patterns to achieve similar (e.g. looping through a series of objects, that have been generated from a directory list).

I have seen the CSV file scenario, but cannot quite map it to what I'm looking for. A work in progress example of what I'm working on is available at https://github.com/CloudWithChris/cloudwithchris.com/blob/preview/action-test/tests/example.spec.ts

Any insights appreciated - This is my first time using Playwright, so I have no doubt I'm missing something obvious :)

**Comment by rwoll** [comment]
We assume your tests are generated synchronously, so `await…for` will not work to generate them.

Assuming you have a list of tests to generate, you can do:

```
import { test } from '@playwright/test';
test.describe.configure({ mode: 'parallel' });

for (const [{ actual, expected, title }] of MY_CASES)
    test(title, async ({ page }) => { … });
```

You could replace MY_CASES with `generateCases(…)` as long as `generateCases()` is a synchronous function.

If you need to generate them in an async way, generate the data required to build the test first to a CSV or JSON file out-of-band, then read it in. Like:

```
// generated-tests.spec.ts
import { test } from '@playwright/test';
import fs from 'fs';
const cases = JSON.parse(fs.readFileSync('./case.json'));

test.describe.configure({ mode: 'parallel' });
for (const case of cases)
    test(case.title, async ({ … }) => { … })
```

Does this work for your use case? In order to give more concrete tips, please include a sample of the Playwright code you are currently debugging.

**Comment by rwoll** [comment]
> though I thought Playwright parallelised by default.

We run files in parallel by default, but if you want everything in parallel without having to include that snippet above, add the (new) `fullyParallel` config option: https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel. Also available as a command line switch; see `npx playwright test --help`.

> The sample is available at https://github.com/CloudWithChris/cloudwithchris.com/blob/preview/action-test/tests/example.spec.ts - Appreciate your tips and insights :)

Ah, looks close! Skip the `runTests` wrapper and just do something like:

```
for (const record of getFiles(…))
    testTitle(record);
```

(assuming you delete everything below [Line 45](https://github.com/CloudWithChris/cloudwithchris.com/blob/ebeaab215943867a29d1c1642c753b73d0638d0d/tests/example.spec.ts#L45) and make `getFiles(…)` synchronously return an array.

You don't need to `await test(…)`, just call `test(…, async () = {…})`. This doesn't yet run the `test`; it merely registers the test (and its closure—the second argument—that contains the test code) to the runner to eventually execute. The test runner itself will await your code in the closure when it needs to.

Does that make sense?

**Comment by rwoll** [comment]
NB: If generating your test cases is expensive, you can break these steps up and run like:

```
$ npm run generate-test-cases # drops a JSON file on disk with the relevant bits, can be an arbitrary Node script, including async 
$ npx playwright test # reads in the JSON file to generate the test cases.
```

**Comment by chrisreddington** [comment]
Makes complete sense @rwoll - Thank you! I think I made some false assumptions on the parallelism of the tests (even though I read that very doc, about tests within a file being ran in-order by default).

Code refactored based upon our above discussion, and also configured to use the fullyParallel config file. Appreciate your help here, thank you so much!
