### ISSUE TITLE
[Question] - is PlaywrightTestConfig -> use -> video -> <videoMode> working?

### ISSUE THREAD

**Issue by andreabisello** [microsoft/playwright#13107]
Hi
thanks for this awesome project.
i'm using since playwright 1.18.
the video recording feature is awesome.

i'm able to use it in a Electron application,  with this property in the launcOptions
```

recordVideo: {
        dir:"./electron-test-run-videos",
        size:{
            width:1280,
            height:720
        }
    }

```
i'm able to use it in a browser application, with this property in the newContext options
```

const browserContext = await webBrowser.newContext({
            recordVideo: {
                dir: 'browser-videos/',
                size: { width: 640, height: 480 },
            }
        })

```

but NOT able to work if i remove these configurations and put on [playwrightTestConfig](https://playwright.dev/docs/test-configuration#record-video)  , video is never recorder.

i tried both with this syntax

```

const config: PlaywrightTestConfig = {
    testDir: './tests/e2e',
    timeout: 60000,
    retries: 0,
    use: {
        locale: 'en-GB',
        ignoreHTTPSErrors: true,
        video: {
            mode:"on",
            size:{
                width:1280,
                height:720
            }
        }
    },
    webServer: {
        command: 'http-server dist -p 8080 -a localhost',
        port: 8080,
        timeout: 120 * 1000,
    },
    expect: {
        toMatchSnapshot: { threshold: 1 },
        timeout: 5 * 1000,
    }
}

```

or also with this one
```

const config: PlaywrightTestConfig = {
    testDir: './tests/e2e',
    timeout: 60000,
    retries: 0,
    use: {
        locale: 'en-GB',
        ignoreHTTPSErrors: true,
        video: "on"
    },
    webServer: {
        command: 'http-server dist -p 8080 -a localhost',
        port: 8080,
        timeout: 120 * 1000,
    },
    expect: {
        toMatchSnapshot: { threshold: 1 },
        timeout: 5 * 1000,
    }
}

```

but nothing changed, so at the end i'm able only to record everytime a video *forcing in the electron launchOptions or in the browser Context*, not only if a test fails.

this is my test
```

    test("tempative to record a video " , async () => {
        const webBrowser = await chromium.launch({ headless: true })
        const browserContext = await webBrowser.newContext()
        const page = await browserContext.newPage()
        await page.goto("https://www.google.com")
        await browserContext.close()
        await webBrowser.close()
    })


```
someone know if this functionality is working?

thanks

**Comment by rwoll** [comment]
Playwright Test has built-in fixtures, and many of the configs will only work if you use the built-in fixtures: https://playwright.dev/docs/test-fixtures#built-in-fixtures

The built-in fixtures will be set up properly based on your configs, and you will not need to manually close the page/context/browser as the built-in fixtures will take care of that after your test code runs. 

Your test above can simply be written as:

```
test("tempative to record a video " , async ({ page }) => {
    await page.goto("https://www.google.com");
});
```

Does this work for you?

**Comment by andreabisello** [comment]
@rwoll it works like a charm, thanks :)
can i make a pull request updating the documentation with something like this?
![image](https://user-images.githubusercontent.com/2149815/160351279-6acddb62-b1ca-461a-bb56-cbfb14f9b2cb.png)


due my application use both web and electron, maybe for electron i can create a custom fixture, what do you think?

thanks for your help

**Comment by rwoll** [comment]
It should be better once https://github.com/microsoft/playwright/issues/13104#issuecomment-1081019968 is resolved! As the video settings will even be applied if you do:

```
test('…', async ({ context }) => {
    await context.newPage();
…
});
```

Let's hold off adding a note to the docs until the linked issue is resolved as it may quickly fix the situation.

Cheer! 🎉
