### ISSUE TITLE
[Feature] Plugin Support like Puppeteer (captcha solving etc)

### ISSUE THREAD

**Issue by Anydex** [microsoft/playwright#13103]
Hello, when will playwright have a library where it will allow automated solving of recaptcha or hcaptcha using a captcha solving service such as capmonster.cloud or [2captcha.com](http://2captcha.com/). Puppeteer already has such support by using the [puppeteer-extra-plugin-recaptcha](https://github.com/MikhailGlv/puppeteer-extra-plugin-recaptcha-custom) plugin.

**Comment by rwoll** [comment]
Playwright is focused on end-to-end testing, so we assume you have control of the page under test and can therefore disable any captcha blocks when under test.

We're Open Source, so feel free to author a similar plug in, but we don't have any plans to add a captcha solver.
