### ISSUE TITLE
[BUG] Site doesn't load on Windows webkit

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#13113]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows 10
- Node.js version: 12.22
- Browser: Webkit
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test('example test', async ({ page }) => {
  await page.goto(<MY_URL>); //Can share the url privately on slack 
  await.page.pause();
});

//config.js
{
  name: 'Desktop Safari',
  use: { browserName: 'webkit' },
},
```

**Describe the bug**
I have site that doesn't load properly on Windows-webkit. Only a chat button is loaded and login form doesn't render at all. Works fine on Mac webkit.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/12823
