### ISSUE TITLE
[Docs]: https://playwright.dev/docs/test-api-testing Page not found for PYTHON

### ISSUE THREAD

**Issue by pppillai** [microsoft/playwright#13110]
Hello!

I was navigating to the following URL: https://playwright.dev/docs/test-api-testing and it resulted in a 404 error, for PYTHON

**Comment by rwoll** [comment]
Thanks for the report! 

That particular guide is written around Playwright Test (which is only available for Node.js). However, the concepts still apply to Python. (See https://playwright.dev/python/docs/api/class-apirequestcontext for docs on making Playwright Requests in Python, and https://playwright.dev/python/docs/test-runners for our recommended Python test runner plugin).

Please add a thumbs up react to this comment to help us prioritize writing a Python version of that guide.

**Comment by mxschmitt** [comment]
thats the python guide: https://playwright.dev/python/docs/api-testing
