### ISSUE TITLE
[Feature] Case sensitive text matcher

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#13121]
From the documentation:

https://playwright.dev/docs/selectors#text-selector
```
text=Log in - default matching is case-insensitive and searches for a substring. For example, text=Log matches <button>Log in</button>.
```

It would be great to support a case sensitive matching as well.

**Comment by rwoll** [comment]
Oops! Our docs are a little subtle here. Add quotes around the text to do an exact—including case-sensitive—match: `text=Log in` -> `text="Log in"`.

I've opened https://github.com/microsoft/playwright/pull/13136 to clarify in the docs!
