### ISSUE TITLE
[Question] How to access the page window in custom selector

### ISSUE THREAD

**Issue by ashwinmenkudle** [microsoft/playwright#1312]
I was trying to implement the custom selector for the OpenUI5 framework.
I need to execute the javascript function which is available in the test application.
Is there any way to access the page window object?

**Comment by aslushnikov** [comment]
Curerently selector engines run in a "secondary world" - this is similar to a content script. There's a feature request to run them in the main world: #1316

Feel free to upvote and follow #1316!
