### ISSUE TITLE
[BUG] waitFor({ state: 'hidden' }) does not work if element animates out of the viewport

### ISSUE THREAD

**Issue by martindzejky** [microsoft/playwright#13131]
**Context:**
- Playwright Version: `1.20.0`
- Operating System: Mac
- Node.js version: `16.14.2`
- Browser: Chrome

System:
 - OS: macOS 12.0.1
 - Memory: 164.48 MB / 16.00 GB

Binaries:
 - Node: 16.14.2
 - npm: 8.5.5

**Describe the bug**

I have an app where the sidebar animates out of the viewport when it is collapsed using CSS, something similar to this:

```
.sidebar {
  position: fixed
  left: 0
  transition: all .5s
  transform: translateX(-100%) // moves the sidebar out of the viewport on the left
}

.sidebar-trigger:hover .sidebar {
  transform: translateX(0) // when the user hovers near the left edge, animate the sidebar in
}
```

I'm trying to test this behavior using Playwright. The test looks something like this:

```
await page.locator('.sidebar-trigger').hover()
await page.locator('.sidebar').waitFor({ state: 'visible' })

await page.locator('.something-else').hover() // sidebar looses hover and animates away
await page.locator('.sidebar').waitFor({ state: 'hidden' }) // this FAILS even though the sidebar is no longer visible
```

The `waitFor({ state: 'hidden' })` part always times out, even though I can clearly see that the sidebar animates out of the viewport and is no longer visible.

I'm very new to Playwright so I can't tell, is this a bug or by design? If the latter, how am I supposed to test this behavior properly?

Thanks!

**Comment by rwoll** [comment]
After reviewing this further, per the visibility spec on https://playwright.dev/docs/next/actionability#visible:

> Element is considered visible when it has non-empty bounding box and does not have visibility:hidden computed style. Note that elements of zero size or with display:none are not considered visible.

✅ non-empty bounding box
✅ does not have visibility:hidden

Given the above conditions are satisfied, the locator is considered visible.

https://github.com/microsoft/playwright/issues/8740 proposes something like isInViewport() that would be better suited for checking if an element is offscreen, so please follow that issue to see if that gets implemented.

If you believe this was closed in error, please open a new issue referencing this issue #.

Thanks!

**Comment by martindzejky** [comment]
Thank you! I wasn't sure whether this is a bug or a feature request, indeed because I read through the docs and there isn't anything stating that the element has to be in the viewport to be considered "visible" (and "hidden" otherwise). I was confused because in Cypress (where I'm migrating my tests from), this is the case - in other words, a test asserting that an element is hidden passes when the element is outside of the viewport.

In my specific use case, as a workaround, I can change the test to check for a class on the sidebar element. But, is there any other recommended way to test this behaviour using Playwright? I can see a suggestion in #8740, is that the way to go for now?
