### ISSUE TITLE
[Docs]: Page not found /python/docs/api/class-electron

### ISSUE THREAD

**Issue by NotNils** [microsoft/playwright#13149]
Hello!

I was navigating to the following URL: https://playwright.dev/python/docs/api/class-electron and it resulted in a 404 error.

**Comment by MarkoNaumovic** [comment]
Unfortunately, there is no DOC for the python, java, and .NET APIs....

**Comment by rwoll** [comment]
Thanks for the report! As of now, Electron support is considered experimental so it hasn't been ported to the other languages.

For Python, you can upvote this issue: https://github.com/microsoft/playwright-python/issues/379
