### ISSUE TITLE
[BUG] WebGL fail in firefox browser

### ISSUE THREAD

**Issue by StanislavLebedenko** [microsoft/playwright#13146]
**Context:**
- Playwright Version: 1.16
- Operating System: Linux
- Browser: Firefox
- Java: 11

**Code Snippet**

used options:

BrowserType.LaunchOptions:
 - headless: false;
 - timeout: 60000.0
 - proxy:
   - server: "http://mock"

Browser.NewContextOptions:
- locale: ru-RU,ru;q=0.8,en-US;q=0.5,en;q=0.3
- proxy:
   - server: [server]:[port]
   - username: [name]
   - password: [pass]
- screenSize:
   - width: 1920
   - height: 1080
- storageState: {"cookies":[],"origins":[]}
- timezoneId: Europe/Kiev
- userAgent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/93.0

Other parameters is null.

Also I run the script (page.addInitScript):
`Object.defineProperty(navigator, 'deviceMemory', {
        get: () => 12
});
Object.defineProperty(navigator, 'hardwareConcurrency', {
        get: () => 6
});
Object.defineProperty(navigator, 'appCodeName', {
        get: () => "Mozilla"
});
Object.defineProperty(navigator, 'appName', {
        get: () => "Netscape"
});
Object.defineProperty(navigator, 'appVersion', {
        get: () => "5.0 (X11; Fedora; Linux x86_64; rv:97.0) Gecko/20100101 Firefox/97.0"
});
Object.defineProperty(navigator, 'platform', {
        get: () => "Linux x86_64"
});`

**About issue**
After Firefox have run I found that WebGL does not work. If I run browser manual, WebGL works fine.
I am using the browser Playwright ships with.
I add the files with info from about:support.
[run manual.txt](https://github.com/microsoft/playwright/files/8368569/run.manual.txt)
[run with playwright.txt](https://github.com/microsoft/playwright/files/8368570/run.with.playwright.txt)

I think that some setting break WebGL.

**Comment by rwoll** [comment]
> WebGL does not work

What are the symptoms indicating this? Can you include screenshot or logs of expected vs. actual (including any error messages). Please set `DEBUG='pw:*'` to generate the logs.

**Comment by StanislavLebedenko** [comment]
check on https://get.webgl.org/
![webGL_screen](https://user-images.githubusercontent.com/87444639/160780451-0940e7cd-1c12-4794-83b2-9cc4152dd903.png)
checks on https://webglreport.com/?v=1 / https://webglreport.com/?v=2
![webGL1_screen](https://user-images.githubusercontent.com/87444639/160781024-633b3aec-2b89-45be-8fe8-7e2ab3778136.png)
![webGL2_screen](https://user-images.githubusercontent.com/87444639/160781034-f71357c4-2201-4602-84ff-960624e3d374.png)
about:support info:
[run manual.txt](https://github.com/microsoft/playwright/files/8379518/run.manual.txt)

All this is when I run playwright nightly manual.
And I run nightly which I have downloaded from ftp.mozilla.org.
WebGL is working
![webGL_works_screen](https://user-images.githubusercontent.com/87444639/160810812-471a84ab-871e-4f8f-be23-6058938ee9cf.png)

about:support info:
[run official nightly.txt](https://github.com/microsoft/playwright/files/8379635/run.official.nightly.txt)

About logs: can you clarify where i need to use DEBUG='pw:*'

**Comment by StanislavLebedenko** [comment]
I try to use Playwright under Ubuntu and Windows 10 - it works fine, WebGL works normally. Maybe some OS were excluded from your build?

**Comment by rwoll** [comment]
Playwright WebGL support varies by platform and browser. Can you share more about your use case to help us prioritize?

Also, please try running your without your addInitScript bits overwriting `navigator`.

**Comment by mxschmitt** [comment]
WebGL is only available in Firefox headed. This means you need to use `xvfb-run node foo.js`. See here for the upstream issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1375585
