### ISSUE TITLE
[BUG] page.goto doesn't work on headed mode 

### ISSUE THREAD

**Issue by christophebe** [microsoft/playwright#13156]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac OS 12.3
- Node.js version: 16.14.1
- Browser: Chromium
- Extra: Mac M1

**Code Snippet**

It doesn't work on my M1. The url is just an example. There are other urls that don't work.

```javascript
const browser = await chromium.launch({ headless: false })
const page = await browser.newPage()

  try {
    await page.goto('https://www.belfius.be/', { waitUntil: 'networkidle' })
    console.log('seems to be ok')
  } catch (error) {
    console.log(error)
  } finally {
    browser.close()
  }
```

In headless mode, it works

```javascript
const browser = await chromium.launch({ headless: true })
  const page = await browser.newPage()

  try {
    await page.goto('https://www.belfius.be/', { waitUntil: 'networkidle' })
    console.log('seems to be ok')
  } catch (error) {
    console.log(error)
  } finally {
    browser.close()
  }
```

**Describe the bug**
In the headed mode, I got a time out : 
page.goto: Timeout 30000ms exceeded.

**Comment by rwoll** [comment]
Thanks for your report!

Never use `networkidle`! It depends on network conditions and timing, and is therefore flaky. (I ran your tests above 60 times on an M1, and they all worked.)

Playwright will auto wait, so just skip to the bits where you interact with the page:

```
await page.goto('https://www.belfius.be/');
await page.locator('text=My Button').click();
```

If you need to gate things more manually (or don't want to click), you can wait for specific elements via https://playwright.dev/docs/api/class-locator#locator-wait-for or specific network calls via https://playwright.dev/docs/api/class-page#page-wait-for-request.

Does that resolve your issue? If not, please let us know and include more context on your use case.

**Comment by christophebe** [comment]
Hi, 

Thanks for your answer ! removing networkidle doesn't solve the issue. I still have a timeout only when headless = false. 
If true, it works fine with Chromium.  

I tested with Firefox instead of Chromium and it works fine with the same site when headless = false
I don't understand :-)

Maybe a Chromium config ? 

Thanks

**Comment by christophebe** [comment]
I got exactly the same issue in Python. With the same site and with headless=False

```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()
    page.goto("https://www.belfius.be/")
    print(page.title())
    browser.close()

```

I don't understand why is working for some sites and not for others.

**Comment by rwoll** [comment]
@christophebe Since it's hitting a live page there could be a lot of factors at play. Can you please reproduce with `DEBUG=pw:*` API set. It should print out logs. Please share the logs and we can help debug further!

(You can also try using the Trace Viewer to debug: https://playwright.dev/docs/trace-viewer)

**Comment by rwoll** [comment]
Thanks! After that initial `Network.requestWillBeSent` it looks like the browser isn't getting data back from the site.

I can't reproduce; can you share some other sites you aren't able to test in hopes of me repro'ing? Please also include a cloneable repo so we can see the full setup of your repro.

**Comment by christophebe** [comment]
I cleared the browsing data in Chromium and now it works fine with the headless=false
I am going to continue my tests and we will see :-)

Thanks
