### ISSUE TITLE
[BUG] Firefox not able to open pdfs anymore

### ISSUE THREAD

**Issue by mauricedoepke** [microsoft/playwright#13157]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Occurs on Mac and Linux
- Node.js version: 16.14.0
- Browser: Firefox

**Describe the bug**
We use playwright together with firefox to check whether pdfs are generated correctly. Because firefox converts them to html for rendering we were able to use the regular playwright selectors to check whether the contents are fine.

The problem is that with the newest playwright version firefox ist not able to open pdf's anymore.
When opening them by script (via page.goto("https://...../test.pdf")), the page just stays empty.
When manually opening, when in debug mode, via rightclick and "open in new tab" in only offers to download it, despite the server sending the content-disposition inline header.
The normal non playwright firefox still works fine with pdfs, when used manually. So this does not seem to be a general firefox error on first sight.

**Here is a reproduction repo:**
https://github.com/mauricedoepke/playwright-firefox-pdf-bug

Just do a `npm install` and a `npm test`

**Comment by rwoll** [comment]
Thanks for the repro! I was able to reproduce. @playwright/test@1.19.2 would show FF's built in PDF previewer; 1.20.1 no longer does.

**Comment by rwoll** [comment]
Adding the https://github.com/microsoft/playwright/labels/P3-collecting-feedback label. If you find a workaround, please comment!

The built-in PDF viewers in the browsers are not part of the Web platform, so behavior around this case is undefined.

**Comment by aslushnikov** [comment]
We explicitly disabled the PDFjs viewer for firefox to align PDF treatment across browsers. This is done via the `pdfjs.disabled` configuration option, so theoretically you should be able to override it like this:

```js
await firefox.launch({
  firefoxUserPrefs: {
    'pdfjs.disabled': false,
  }
});
```

**Comment by mauricedoepke** [comment]
Thanks for your fast responses. 

I tried @aslushnikov proposal, but encountered two problems with it.
I added the following to the playwright.config.ts:
```
launchOptions: {
    firefoxUserPrefs: {
        "pdfjs.disabled": false,
    },
},
```
(I also added it to the reproduction repo https://github.com/mauricedoepke/playwright-firefox-pdf-bug for you to easily try out)

When launching the browser with this option and then manually going to "about:config", the option `pdfjs.disabled` is still set to true, so somehow the firefoxUserPrefs don't work. Neither in the general `use` section, nor within the projects `use` section, nor if directly used with `firefox.launch` function.

Also it does not solve the pdf problem.
Even if I manually go into the about:config and set pdfjs.disabled there to false via the ui, the pdf functionality is still not working.

**Comment by rwoll** [comment]
> I added the following to the playwright.config.ts:

I don't think it will work there as firefoxUserPrefs overrides are only supported with persistent contexts (so try launchPersistentContext instead of launch).

Testing contents of PDFs is not in scope for PW at the moment since PDF viewers are different/undefined per-browser/platform.

**Comment by singhsukhman** [comment]
how to set password on pdf while using puppeter
