### ISSUE TITLE
[Question] Why are some tests getting skipped even though it hasn’t exceeded global timeout?

### ISSUE THREAD

**Issue by brandonfillpot** [microsoft/playwright#13162]
When I open up my playwright reports it never shows more than 2 failed tests and there’s always tests getting skipped as well. When I look into those skipped tests it shows that the before hooks are run, but there’s an assertion timeout that’s been exceeded. Why does playwright not consider this a “failed” test but instead decides to skip it? How come it doesn’t retry the test? These skipped tests look exactly the same as the failed ones (the failed ones fail because of timeouts).

When running on CI, the tests usually finishes running under 5 minutes and I have my global timeout set to 10 minutes so I don’t know why it’s not using the remaining time to retry those ‘skipped’ tests.

Here are my timeout configurations:

{    globalTimeout: 600000,

    timeout: 180000,

    expect: {

        timeout: 180000

    },

    use: {

    actionTimeout: 180000,

    navigationTimeout: 180000

    }

}

**Comment by rwoll** [comment]
Thanks for the report! To best help, can you create a small repro repo that shows the problem? Ideally, it's something we can clone and run locally to better understand.

**Comment by rwoll** [comment]
Per-above, closing—but please re-open if you have a small repo so we can follow up!
