### ISSUE TITLE
[Playwright]:Is any direct solution exist to wait for Function until it return truthy

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#13179]
Exploring this feature in playwright ,to wait for function till it return truthy value.Is any direct function available to support this? same like below tool

 WendriverIO **
browser.waitUntil(condition, { timeout, timeoutMsg, interval })** as well in 

**Protractor example**
 browser.wait(function() {
       return ptor.isElementPresent(waitLoading);
   }, 8000);

**Comment by rwoll** [comment]
What are you trying to wait for (i.e. an element to be visible, or some arbitrary condition)? Most of the Playwright APIs have waiting built-in; more arbitrary conditional polls are likely coming in the next release (1.21), but no guarantees!

**Comment by saurabh4888** [comment]
@rwoll  Thanks for the info 

Actually trying to wait until my condition return truthy 

Example Scenario : For particular element need to wait for Opacity Value (CSS Value) to changes from 0.2 to 1 and for that in protractor or  in webdriver direct way of implementation

Like for protractor shown below, we call for condition  and set the timeout, and it's going to wait for function to return the truthy  until the timeout occur .

**async function waitForCondition(func: () => Promise<boolean>, timeout: number, message: string): Promise<boolean> {
  return browser.wait(async () => {
    try {
      return func();
    } catch (error) {
      return false;
    }**
  }, timeout, message);
}

So the query is the same way implementation can also be achieved in Playwright?

**Comment by rwoll** [comment]
Thanks for the additional info. You can use https://playwright.dev/docs/api/class-page#page-wait-for-function.

An expectation variant (expect.poll(…)) will also be introduced via https://github.com/microsoft/playwright/issues/10235

**Comment by awhisler** [comment]
@rwoll this doesn't seem to work for my use case. I basically am adding a filter on a list page and I want to 'wait until there is a change on the page' - I am doing that through a count and it fails:
![image](https://github.com/microsoft/playwright/assets/2396250/8182463d-db8f-49b2-b2db-54ce5f28d119)

What am I doing wrong? Or is this not possible?
