### ISSUE TITLE
[Feature] Add "slider" diff to HTML-report

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#13176]
There are cases where the slider is more convenient than the pixel highlighting method, especially when the length of the expected and actual screenshots differs. 

<img src="https://user-images.githubusercontent.com/35337277/160599426-30f635c7-e147-45b8-aff8-e0b6d44cae8b.png" width="71" height="401" /> <img src="https://user-images.githubusercontent.com/35337277/160599455-6ea3a507-0af7-4ebe-aa65-7082ecdc6e50.png"  width="71" height="401" /> <img src="https://user-images.githubusercontent.com/35337277/160599452-c684ead6-1dd6-4a22-af1b-0fa468fe95c4.png" width="71" height="401" />

It would be possible to implement one more optional tab in the report by analogy with Diff/Actual/Expected?

<img width="400" alt="report sample" src="https://user-images.githubusercontent.com/35337277/160600478-80146cc7-7222-453b-8a1a-f10b935d8330.png"> <img width="400" alt="report sample" src="https://user-images.githubusercontent.com/35337277/160926048-748733db-56a5-40b7-ac75-a700b80e86f6.png">

Or you could display all 3 states on one tab in the report (as it looks in the attachments of this comment). This is not a slider, but it will help speed up and simplify the analysis of fallen visual regression tests.

**Comment by rwoll** [comment]
Awesome idea! Collecting upvotes to help prioritize!

**Comment by bezyakina** [comment]
In which pw package version can I test this feature?

**Comment by aslushnikov** [comment]
@bezyakina should be released in 1.21 (that was released yesterday)!
