### ISSUE TITLE
[Question] How to log information when a test fails or skips?

### ISSUE THREAD

**Issue by totsuka1** [microsoft/playwright#13171]
I want to print the entire DOM HTML when a test fails or skips. Right now I’m using an afterEach hook to print the dom for every single test but it’s way too many unnecessary logs and since gitlab stops logging after a certain amount of bytes, there’s a good chance I might not get the DOM output for the tests that actually fail/skip.I found this code online:

```
const playwright = require("playwright");
(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  const errorLogs = []
  page.on("console", (message) => {
    if (message.type() === "error") {
      errorLogs.push(message.text())
    }
  })
  await page.evaluate(() => {
    console.error("hello from the browser")
  })
  console.log(errorLogs)
  await browser.close();
})();
```

And tried using it in my beforeEach hooks (with some of the lines deleted) but it didn’t work. I’m not entirely sure where that code snippet is even supposed to be placed but using them directly in my test files didn’t work.

**Comment by rwoll** [comment]
Playwright Test has tracing built in which includes DOM Snapshots. Check out https://playwright.dev/docs/trace-viewer#recording-a-trace for information on the options as well as how to view the traces!

Let us know if that works for you!

**Comment by totsuka1** [comment]
Thanks, I have used the trace viewer and while it takes a screenshot of the DOM, it wasn't particularly helpful in helping me see the non-visible attributes like id, class of multiple elements on failure. I know I can always use assertions, but it would be a pain to have to write multiple ones for each of my tests when I have hundreds. Which is why I just wanted to see if there was a way to console.log the entire DOM only on failure/skips.

**Comment by rwoll** [comment]
If you right-click on the image (directly under the Action / Before / After header) in the trace viewer, you click View Frame Source and it will show the DOM.

> I know I can always use assertions, but it would be a pain to have to write multiple ones for each of my tests when I have hundreds.

Playwright will provide the best experience and debugging if you use the [built in assertions](https://playwright.dev/docs/test-assertions). Can you include a sample of your tests? What are you currently using for assertions?

**Comment by mauricedoepke** [comment]
@totsuka1 you can do a rightlight and within the trace viewer and then click "inspect" which opens the regular developer tools there you can see all your html including id's and classes.

**Comment by namikim665** [comment]
@totsuka1 If you want I think you can use this logger https://github.com/hoangtaiki/playwright-smart-logger
