### ISSUE TITLE
[Feature] Request to add allure.step() API

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#13172]
Hi, amazing team!

We have a lot of useful APIs with the **allure** object.

It will be great to get an API for **allure.step** in order to customize the allure report.
For example, it will allow an option to provide some custom names of elements to the allure step in the report:
```javascript

    private page: Page;
    private locator: string;
    private allureAnnotation: string


    constructor(page: Page, locator: string, allureAnnotation: string) {
        this.page = page;
        this.locator = locator;
        this.allureAnnotation = allureAnnotation;
    }

    async click() {
        const element = this.page.locator(this.locator);
        await element.waitFor();
        await element.click();
        allure.step(`Clicking on ${this.allureAnnotation} element`)
    }

```

**Comment by rwoll** [comment]
The allure reporter is a 3rd-party reporter (https://playwright.dev/docs/test-reporters#third-party-showcase), so this would likely need to be implemented as part of that project and be imported from a third-party package.
