### ISSUE TITLE
[BUG] Cannot click button after granting permissions

### ISSUE THREAD

**Issue by hanagejet** [microsoft/playwright#13178]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: Chrome
- Extra: none

**Code Snippet**

```javascript
import { test } from '@playwright/test';

test('test', async ({ page, context }) => {
  await page.goto('http://localhost:9001/');
  await page.locator('text=Page').click();
  const frame = page.frame('storybook-preview-iframe');
  if (frame === null) {
    return;
  }
  await context.grantPermissions(['microphone']);
  await frame.click('#button');
  // It's not supposed to be clicked.
});

```

**Describe the bug**

I'm testing in Storybook. I manually click the button and it is clicked. (At this time `await frame.click('#button');` is comment out, then add `await page.pause();`)

**Comment by rwoll** [comment]
Try with [FrameLocator](https://playwright.dev/docs/api/class-framelocator) instead of page.frame. Locators will re-resolve each time an action is taken.

If that doesn't work, please re-open this issue and include the error that is printed.

**Comment by hanagejet** [comment]
Thank you, it works.
