### ISSUE TITLE
[BUG]  Need to monitor WindowSize change 

### ISSUE THREAD

**Issue by rr13k** [microsoft/playwright#13177]
When I need to record, when the user adjusts the browser window size and listens to change the page view size, I can't find a way to do it

link [issue 11832](https://github.com/microsoft/playwright/issues/11832)

**Comment by rr13k** [comment]
``` js
window.onresize = ()=>{console.log(11)}
```
The above code works in normal browsers, but not in "Chromium" evoked by recording

"Chromium revision": "983172"
Is that a problem

**Comment by rwoll** [comment]
I repro'd. Will get back to you!

**Comment by rwoll** [comment]
> Is that a problem

Updated https://github.com/microsoft/playwright/issues/13177#issuecomment-1083466971, and confirmed the event **not** firing via manual changing of the window in Chromium is intended.

We do viewport emulation, so unless you are explicitly resizing via the Playwright API (`page.setViewport(…)`), the 'resize' event behavior is undefined.
