### ISSUE TITLE
[Question] - Why does waiting until "load" comes when tests are executed on jenkins

### ISSUE THREAD

**Issue by jatin-karla11** [microsoft/playwright#13174]
Everything works fine on local, also I have set a default timeout of 35seconds which is more than enough, but still when tests are executed on jenkins some of the tests show navigating to url(any site), waiting until "load"

**Comment by rwoll** [comment]
CI environments usually have less CPU and different network speeds. Try reducing your worker count to 1 to see if that fixes it. You can also use https://playwright.dev/docs/trace-viewer to record a view traces for failed tests to see what's going on.

**Comment by jatin-karla11** [comment]
yes reducing the count to one solves the issue, thanks got it!

**Comment by jatin-karla11** [comment]
I checked the trace of test cases failing by resulting waiting until "load", it says frame gets detached and this occurs. But my test cases are working fine in local PC, also we have increased the resources for jenkins, but still the issue is persisting, please help me out

**Comment by jatin-karla11** [comment]
even now with single worker also 1 or 2 test cases out of 50 are showing waiting until load, and same the trace says frame is getting detached at the starting, and these 1 or 2 test cases which are failing are totally random

**Comment by jatin-karla11** [comment]
@rwoll

**Comment by rwoll** [comment]
> and these 1 or 2 test cases which are failing are totally random

This sounds like a flaky test that could be a result of the backend or the test composition itself. Without more information about the test itself and the app under test, it's hard to know. Can you enable tracing and share a trace of a failing run? https://playwright.dev/docs/trace-viewer#recording-a-trace

Thanks!

**Comment by rwoll** [comment]
Closing as part of triage! If you have a repro or trace, please file a new issue referencing this one, so we can help debug! Cheers!

**Comment by jatin-karla11** [comment]
https://github.com/microsoft/playwright/issues/12182
please check this @rwoll

**Comment by jatin-karla11** [comment]
this issue is very important
