### ISSUE TITLE
[Question] Is it possible to scroll to the left or right?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#13189]

**Comment by rwoll** [comment]
Can you elaborate on your use case?

There's a few ways to achieve scrolling depending on what you are trying to achieve:
1. https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed
2. https://playwright.dev/docs/api/class-mouse#mouse-wheel

**Comment by gauravgandhi1315** [comment]
@rwoll Thanks. This `mouse.wheel(deltaX, deltaY)` helps. I wanted to scroll horizontally.

**Comment by rwoll** [comment]
Awesome! 🎉
