### ISSUE TITLE
[BUG] Unable to use test.BeforeAll when using text fixture with auto: true to run before every test

### ISSUE THREAD

**Issue by cheytan86** [microsoft/playwright#13186]
created a sample test with fixtures Refer the code below:

```ts
import { test as baseTest, expect} from '@playwright/test'

const test = baseTest.extend<{
    sampleFixture: void
}>({
    sampleFixture: [async({page}, use) => {
        console.log('before each')
        await use();
        console.log('after each')
    }, {auto: true}]
})

test.beforeAll(async({}) => {
    console.log('test before all')
})


test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
    console.log('test')
});
```

on executing the above code getting the following error:
Error: "context" and "page" fixtures are not supported in beforeAll. Use browser.newContext() instead.

Note: but there is no "page" and "context" used in the  beforeAll.
 

Playwright Version : 1.20.1

**Comment by rwoll** [comment]
Thanks for the report! I repro'd. I don't have a workaround (or a fix), but I'll update this issue accordingly!

---

Debug Notes: Based on the existing test, it looks like we run test-scoped auto fixtures even in preperation for beforeAll: https://github.com/microsoft/playwright/blob/f45656aa5dbf5f6ca96c762de1b137945a2dd4ec/tests/playwright-test/fixtures.spec.ts#L315

**Comment by xv-chetan-m** [comment]
hi Ross,
please let me know if there is a workaround for it in case it takes time to get fixed.

**Comment by rwoll** [comment]
Unfortunately no workaround atm. Any work/changes will be linked to this issue, so make sure to follow it!

**Comment by mxschmitt** [comment]
@dgozman might be something where we just need to improve the error message. If not, feel free to move to 1.22.
