### ISSUE TITLE
[Question] Is it possible to append value to a header?

### ISSUE THREAD

**Issue by frbk** [microsoft/playwright#13183]
I tried using `extraHTTPHeaders` and `setExtraHTTPHeaders` but both options overwrite all of the other header so the page ends up with a lot of broken elements on it. Is it possible to append custom headers when using `goto()`. I have looked at the docs and cant find anything.

**Comment by frbk** [comment]
@rwoll Thanks for getting back to me. It does not include any default headers after I add much header. This causes CORS errros and some css and javascript files dont load anymore. Modifying requests looks promising. I will give it a shot and update shortly. Let me know if you have any other questions. I can post examples of headers if that helps.

**Comment by rwoll** [comment]
Yes, if it doesn't work, please share a link to a repo with a small example showing the problem and your setup. Ideally, it's something we can clone and run locally. Please re-open if it doesn't work out!

**Comment by rwoll** [comment]
It looks like https://github.com/microsoft/playwright/issues/12929 was just resolved, so if you hit CORS errors when intercepting, be sure to try out playwright@next (`npm i @playwright@next`)
