### ISSUE TITLE
[BUG] "Cannot import a typescript file from an esmodule"

### ISSUE THREAD

**Issue by jeremytenjo** [microsoft/playwright#13191]
**Context:**
- Playwright Version: [1.20.1]
- Operating System: [ Mac]
  System:
    OS: macOS 12.3
    Memory: 115.30 MB / 16.00 GB
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Describe the bug**

Getting `Cannot import a typescript file from an esmodule` when running ` npx playwright test`

This issue only happens on version `1.20.1`.  I fix it by going back to version `1.20.0`

**Comment by rwoll** [comment]
Can you link to a repo that we can clone and run and observe the error? This will ensure we are debugging based on the correct information/package.json.

---

This might be related to https://github.com/microsoft/playwright/issues/13078 which was recently resolved on main branch.

You can try with the upcoming version by doing:

```
$ npm i @playwright/test@next && npx playwright install && npx playwright test
```

Let us know how it goes!

**Comment by rwoll** [comment]
Does it work if you do:

```
$ npm i @playwright/test@next && npx playwright install && npx playwright test
```

**Comment by DoisKoh** [comment]
Hello, sorry for the late reply.

Yes it does work. Note: It requires the playwright.config.js file to be renamed to playwright.config.ts (which thankfully, is mentioned in the output upon execution).

**Comment by rwoll** [comment]
Thanks for the update! `1.20.2` will be released soon, and [it will include the fix](https://github.com/microsoft/playwright/pull/13160). In the interim, you can stay on 1.20.0 or depend on the `@next` version that worked for you.

**Comment by jeremytenjo** [comment]
Fixed for me as well. Thanks for the help! @rwoll

**Comment by khaki32** [comment]
I created a new project using `npm init svelte` and I'm still getting this error when running the test command, despite the playwright version being 1.22.2

**Comment by rwoll** [comment]
@khaki32 Can you file a new issue to be triaged? Please include a link to a repo of your test project we can clone and download to observe the error! Thanks!
