### ISSUE TITLE
[BUG] Recording a trace in Java throws an method undefined error on .setSources(true));

### ISSUE THREAD

**Issue by Sriram-Kumar1** [microsoft/playwright#13209]
Playwright is awesome!!.. trying to setup for the first time

**Context:**

- Playwright Version: [what Playwright version do you use?] 1.20.0, fails in 1.17
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] Java 17
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium 
- Extra: [any specific details about your environment] 

**Code Snippet**

   Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
        .setHeadless(false));
      BrowserContext context = browser.newContext();
      context.tracing().start(new Tracing.StartOptions()
            .setScreenshots(true)
            .setSnapshots(true)
            .setSources(true));
  

**Describe the bug**

java.lang.Error: 
Unresolved compilation problems: 
        The method setSources(boolean) is undefined for the type Tracing.StartOptions
        Paths cannot be resolved

        at com.automation.AppTest.LogintestWithTrace(AppTest.java:54)

Add any other details about the problem here.

Removing the line seems to work.

**Comment by Sriram-Kumar1** [comment]
class StartOptions class does not seem to have a boolean variable called sources nor a setter method called setSources. 
not sure if this helps

**Comment by rwoll** [comment]
Does it work if you set `PLAYWRIGHT_JAVA_SRC ` env var? https://playwright.dev/java/docs/api/class-tracing#tracing-start-option-sources

**Comment by uchagani** [comment]
> fails in 1.17

`setSources` was introduced in 1.18: https://github.com/microsoft/playwright-java/releases/tag/v1.18.0

**Comment by rwoll** [comment]
Thanks @uchagani! That's correct—setSources for Java was introduced in 1.18.

> 1.20.0, fails in 1.17

@Sriram-Kumar1 Can you clarify which version(s) you're having trouble with?

It is expected to fail in 1.17 since it was not a feature yet. Running on 1.20 with the `PLAYWRIGHT_JAVA_SRC` environment variable set should work, so if this is not working for you in 1.20 then this is an issue.

**Comment by Sriram-Kumar1** [comment]
hello @rwoll 

I started with 1.17 in my pom.xml but upgraded to 1.20. I am trying with 1.20 now

<dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.20.0</version>
    </dependency>

  </dependencies> 

VS code is showing that it is not able to resolve the method.  environment variable PLAYWRIGHT_JAVA_SRC was not set earlier but setting also does not seem to help

**Comment by rwoll** [comment]
> VS code is showing that it is not able to resolve the method. 

You might have to clear a maven cache and/or restart VSCode depending on how you are managing deps. If it doesn't work, please share a link to a repo with minimal project/source code (including the pom.xml) as well as the commands you are running.

**Comment by Sriram-Kumar1** [comment]
thank you @rwoll 

I tried clearing mvn cache (purge local repo) and restarted VS code. seems to be still same.

**Comment by rwoll** [comment]
Thanks for the update—please share a link to a repo that we can clone to be debug. Please include the exact commands (and any environment variables you are setting). This doesn't need to be your actual project; it should be a smallest example/code that exhibits the problem you are seeing.

**Comment by Sriram-Kumar1** [comment]
have uploaded pom.xml and the apptest.java in git. 

https://github.com/Sriram-Kumar1/playwright-source-tracing/tree/main

**Comment by rwoll** [comment]
Thanks @uchagani! That example if working for me as well.

@Sriram-Kumar1 Please let us know the exact commands (maven?) you are typing to setup and build your project. Please include the raw logs/errors.

**Comment by Sriram-Kumar1** [comment]
Hello @rwoll and @uchagani 

After a total restart of the machine and a mvn clean and regeneration seems to be working now. looks like some issue on myside. happy to close the ticket,

appreciate your suppiort.
