### ISSUE TITLE
[Feature] Export reporters' return types such as JSONReport

### ISSUE THREAD

**Issue by wjureczka** [microsoft/playwright#13208]
Hey!

Thanks for your work! I would like to suggest a feature. I need reporters' return types exported. 

Use case:
After the test, I generate a JSON report. After that, I load this JSON file in my `slack-notifier.ts` like this:
```

    const testResultPath = path.resolve(__dirname, '../test-report/data/report.json');

    try {
        const rawData = fs.readFileSync(testResultPath).toString();
        const testResult: JSONReport = JSON.parse(rawData);
        ...
    }

```

I would like to have the variable testResult typed properly to make it more maintainable. What do you think about the idea?

Moreover, after bumping the Playwright, useful property from JSONReport disappeared. There was an object called `stats` where we could easily get to know if any test has failed.

Cheers.

**Comment by rwoll** [comment]
Since https://playwright.dev/docs/test-reporters#json-reporter is public, this makes sense! Would you be interested in sending a patch?

**Comment by wjureczka** [comment]
I have created pull request with the patch @rwoll  :)

**Comment by rwoll** [comment]
Thanks @wjureczka! Assigning this issue to me, to track your PR through!
