### ISSUE TITLE
[Feature] Export request option parameter types

### ISSUE THREAD

**Issue by camargo** [microsoft/playwright#13215]
Right now request `option` parameter types are defined inline for their function (post, put, get, etc.). 
We would like to use these types in our own functions. For example api-specific wrapper functions that take a request `option` as a parameter. This feature request is to export these `option` parameter types to make them available to clients.

Example: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/types/types.d.ts#L12379

**Comment by rwoll** [comment]
For now, you can use a workaround like:

```ts
// @filename: types.ts
export type PostOptions = Parameters<typeof page['request']['post']>[1]
```

Would you be interested in sending a patch to expose it more properly?

**Comment by mxschmitt** [comment]
Closing as per above.
