### ISSUE TITLE
[BUG] Different behaviour in globalTear down when using PW recent versions

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13210]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac
- Node.js version: 14.6
- Browser: any
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
async function globalSetup(config: FullConfig) {
    console.log("Report path " + config.rootDir);

    const reportPath = "./playwright-report";
    console.log("Report path: " + reportPath);
    var zip = new AdmZip();

    zip.addLocalFolder(reportPath, "./playwrightReport");
    zip.writeZip("./report.zip")

}


export default globalSetup;
```

**Describe the bug**

i have noticed that global tear down feature is working differently with the recent version >= 1.19, as with the newer version global teardown function is executed after the tests but not after the session itself, for example i need to zip the playwright-report folder after the execution, currently i can not do that since the teardown function will be executed after the test and before the report is being generated, playwright will wait for global tear down function to be executed then generate the report as shown below.
v 1.20.1
<img width="1434" alt="Screenshot 2022-03-31 at 12 47 31" src="https://user-images.githubusercontent.com/32042806/161038820-2911f029-249e-44b6-b28d-639cbb7d37ba.png">
<img width="1155" alt="Screenshot 2022-03-31 at 12 50 18" src="https://user-images.githubusercontent.com/32042806/161038861-2210e668-2e8c-4dee-b9ef-8f504ca50dd6.png">

unlike the case with the previous version such as 1.17, the tear down function was being executed after the report is being generated which make more sense, except if it could be possible to make global tear down after worker, and global tear down after session

V 1.17
<img width="1146" alt="Screenshot 2022-03-31 at 12 42 26" src="https://user-images.githubusercontent.com/32042806/161037267-8e8465b2-aca7-4364-bb35-c464eaa3ffb0.png">

**Comment by amrsa1** [comment]
Hye @mxschmitt this related to the previous ticket that i post as a question https://github.com/microsoft/playwright/issues/13053#issue-1180066902

**Comment by vsravuri** [comment]
@amrsa1 The behaviour of globalSetup & globalTeardown changed in 1.19. Refer to https://github.com/microsoft/playwright/issues/11841 & https://github.com/microsoft/playwright/issues/12018

**Comment by amrsa1** [comment]
@vsravuri  hmm i see, but to over come such situation with the current behaviour

**Comment by vsravuri** [comment]
@amrsa1 I do zip the the test results after execution in globalTeardown, able to overcome the limitation with the inputs provided by Pavel.

**Comment by amrsa1** [comment]
@vsravuri I see that Pavel has suggested using one event and moving this process inside, does it means I have to customize my own reporter then?

also could you please share a code snippet of this solution

**Comment by vsravuri** [comment]
@amrsa1 Yes, Here is the code

playwright.config
```javascript
reporter: [
            ['list'],
            ['html', {outputFolder: process.env.PLAYWRIGHT_HTML_REPORT, open: "never"}],
            ['./pw_reporter.js']
        ],
```

custom reporter.js
```javascript
// pw-reporter.js
// @ts-check

const fs = require('fs');
const path = require('path');
const {exec} = require('child_process');
const zipAFolder = require('zip-a-folder');
const waitOn = require('wait-on');

/** @implements {import('@playwright/test/reporter').Reporter} */
class CustomReporter {

   async onEnd(result) {
        console.log(`Finished the run: ${result.status}`);
        let htmlResDir = path.resolve(process.env.PLAYWRIGHT_HTML_REPORT);

       const opts = {
           resources: [
               allureResultsDir,
               htmlResDir
           ],
           delay: 1000, // initial delay in ms, default 0
           interval: 250, // poll interval in ms, default 250ms
           simultaneous: 1, // limit to 1 connection per resource at a time
           timeout: 60000, // timeout in ms, default Infinity
       };

       try {
           await waitOn(opts);
           // once here, all resources are available
       } catch (err) {
           console.log(err);
       }

       if (fs.existsSync(htmlResDir)) {
           let zip =  await this.fn_LocTmplName(htmlResDir);
           console.log("Custom Reporter : HTML Results directory exist. HTML Results directory is compressed");
       } else {
           console.log("Custom Reporter : HTML Results directory doesn't exist. HTML Results directory not compressed");
       }

    }

    async fn_LocTmplName(htmlResDir) {
        await zipAFolder.zip(htmlResDir,  process.env.htmlZip);
        return process.env.htmlZip;
    }

}

module.exports = CustomReporter;
```

**Comment by rwoll** [comment]
@vsravuri Thanks for clarifying and including a sample!

@amrsa1 using a [Custom Reporter](https://playwright.dev/docs/test-reporters#custom-reporters) (and processing the results in `onEnd` is currently the recommended approach:

> Similarly, globalTeardown was running after all the reporters have finished processing the test results. If you'd like to post-process the reporters' output, you should define your own reporter that collects the data produced by the previously declared ones.

(Source: https://github.com/microsoft/playwright/issues/12018)

Let us know how it goes!

**Comment by amrsa1** [comment]
Awesome, thank you guys so much.

OnEnd event solved my issue, and thanks @vsravuri for the code snippet it helped me alot.
