### ISSUE TITLE
accessing element inside <frameset><frame>

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13213]
Hi 
In the application that we are testing , we use frameset and frames. The content within the HTML pagewhich has a html page inside a frame. we were using elementHandle.contentFrame() to return the locator for the frame. Post this, we were using the frame locator to find our elements within the Frame. 

With the introduction of FrameLocator, we are no longer able to return the  locator of type Frame. this warrants tremendous changes to our framework since the frame element (of type Frame) is not returned. 

are there any methods within FrameLocator which would return an object of type Frame please?

**Comment by liuxingbaoyu** [comment]
`var frame = await (await page.frameLocator("#frame").locator("#ele").elementHandle()).ownerFrame()`
try it

**Comment by harir5** [comment]
Thank you very much @liuxingbaoyu. it worked just fine !
