### ISSUE TITLE
Is there a function similar to onTestBegin in Reporter interface which runs once before any test starts in a describe function?

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#13217]
**onTestBegin** in the Reporter interface is a hook that is declared globally once and runs before every test. This is useful as we can declare the common code in one place which keeps running for every test instead of having this common code in test.beforeEach() of each test file.

I was looking for a similar one for the test.beforeAll(). Now let's say I have a common code that needs to be run once for each test.describe(). I would usually do this in test.beforeAll() of each file, but is there a way to do this once globally similar to **onTestBegin**.

**Comment by rwoll** [comment]
Let me make sure I understand the desired behavior.

Given the following spec file:

```ts
// @filename: example.spec.ts
test.describe('suite a', () => {
   test('1', () => { expect(1).toBe(1); });
});

test.describe('suite b', () => {
   test('2', () => { expect(1).toBe(1); });
   test('3', () => { expect(1).toBe(1); });
});
```

How many times do you want your hook to run?

**Comment by rwoll** [comment]
There's not a built in `beforeDescribe`, so you can do:

```
// @filename: utils.ts
const setup = () => {…};
```

```
// @filename: example.spec.ts
test.describe('suite a', () => {
   test.beforeAll(setup);
   
   test('1', () => { expect(1).toBe(1); });
});

test.describe('suite b', () => {
   test.beforeAll(setup);
   
   test('2', () => { expect(1).toBe(1); });
   test('3', () => { expect(1).toBe(1); });
});
```

**Comment by autTestUser** [comment]
Ok, I understand. But in the above code, we are again declaring test.beforeAll() in each test.describe(). That is what I want to avoid such that I don't need to have it declared in each test file. Is there a possibility to add a onSuiteBegin() function in Reporter interface so that I can run a piece of code once for each suite similar to onTestBegin() which runs for each test.

**Comment by rwoll** [comment]
Playwright does not have a built in `describe` hook, so some repetition is required (but the above at least shows moving some of the repeated bits into a helper called `setup`), but—yes, it still requires lots of `test.beforeAll(setup)` statements. Furthermore, such a hook might have limited use since you can have nested describes.

The closest thing we have are fixtures which can be test- or worker-scoped (without repeating in multiple places): https://playwright.dev/docs/test-fixtures

> Is there a possibility to add a onSuiteBegin() function in Reporter interface so that I can run a piece of code once for each suite similar to onTestBegin() which runs for each test.

To help us make sure we are trying to solve the correct problem, can you elaborate on your use case? Please include a sample of your Playwright code and the code you want to run in this `onSuiteBegin` hook.

**Comment by autTestUser** [comment]
For a simple example, let's just say I want to display a message in my console as "Started executing suite "suite_name". This suite_name is the current suite being run, so during the start of each suite, I want to display this message. My console might look something like below by using suiteStart, testStart, testEnd, suiteEnd. Let's say I have a test1 in suite1 and a test2 in suite2.


*****Started executing suite suite1******
*****Started executing test test1******
*****Ended executing test test1******
*****Ended executing suite suite1******
*****Started executing suite suite2******
*****Started executing test test2******
*****Ended executing test test2******
*****Ended executing suite suite2******

**Comment by rwoll** [comment]
Thanks for the clarification. So based on this example, you are interested purely in Reporters, and not trying to setup a page or support code for your tests themselves. Is that correct?

While there isn't a onSuiteBegin/onSuiteEnd, you can accomplish this today with some bookkeeping. Here's some sample code for inspiration:

```
class SuiteReporter implements Reporter {
    private _startedSuites: Set<Suite> = new Set();
    private _startedTests: Set<TestCase> = new Set();

    onTestBegin(test: TestCase) {
        const started = []

        if (!this._startedTests.has(test)) {
            this._startedTests.add(test);
            started.unshift('BEGAN: ', test.titlePath().join(' > '));
        }

        let parent = test.parent;
        while (parent) {
            if (!this._startedSuites.has(parent)) {
                this._startedSuites.add(parent);
                started.unshift('BEGAN: ', parent.titlePath().join(' > '));
            }
            parent = parent.parent;
        }

        for (const s of started)
            console.log(s);
    }

…
}
```

There's some edge cases and/or tricky logic, so you'll need to experiment around to write a robust reporter.

The edge cases include (but are not limited to 😄 ):
- skipped tests
- retries
- --repeat-each
- parallelism (on file and test level)
- determining suite end (given retries and related cases can still be running)

**Comment by autTestUser** [comment]
I'll try this and let you know.

**Comment by mxschmitt** [comment]
Closing as per above!
