### ISSUE TITLE
[BUG] page.pause() does not stop

### ISSUE THREAD

**Issue by andrisi** [microsoft/playwright#13219]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Win 10 pro
- Node.js version: 16.13.1
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await this.page.pause()
```

**Describe the bug**

page.pause() stopped stopping and just steps forward, so no way to access the inspector and the recorder. No option changed, and been like this v18 I think. Is there an option to disable the pause() call?

**Comment by andrisi** [comment]
`set PWDEBUG=1` does not help either. Inspector appears, but code does not stop at pause()

**Comment by rwoll** [comment]
Can you link to a repro we can clone and run to observe the issue?

I tried briefly reproing with:

``` 
test('pauses', async ({ page }) => {
  await page.goto('https://example.com');
  await page.pause();
});
```

but it's behaving as expected.

**Comment by rwoll** [comment]
Do you have another JS Debugger attached while trying to use page.pause()? (Possibly related: https://github.com/microsoft/playwright/pull/11926)

**Comment by andrisi** [comment]
@rwoll yes, running scripts from Vscode. It's still useful in this case as compared to getting paused in the debugger, the browser is still usable, so you can "help out" the script by clicking here or there.

**Comment by pavelfeldman** [comment]
> the browser is still usable, so you can "help out" the script by clicking here or there.

Same should happen when you have a debugger; statement or when on a breakpoint. So if you are using vscode, it should be easier to use debugger; instead. page.pause() does not play nicely with breakpoint debugging so we disabled it there.

**Comment by DetachHead** [comment]
using `debugger` doesn't really replace `page.pause` because it's effectively the exact same as a breakpoint. i use `page.pause` when i want to pause the execution without halting the event loop (ie. to work around issues like #10897 and #11668).

another use case is:
```ts
await page.route('**/foo*', async (route) => {
    const request = route.request()
    doSomethingWith(request) //BREAKPOINT HERE
})
await page.goto('https://google.com')
await page.waitForLoadState('networkidle')
await page.pause()
```

here, i want to pause execution once the site loads so i can manually poke around and hit the brekpoint in `page.route` once a matching request is intercepted. if i replace that `await page.pause()` with a `debugger` statement, i can't do anything because navigation hangs until the event loop resumes

now i have to resort to something like `await page.waitForTimeout(9999999)` which isn't ideal

**Comment by mxschmitt** [comment]
Closing as per above since this behaviour is intentional. You can either use the VS Code debugger (or any other debugger) or the Playwright Inspector. Having both in parallel is contra productive.

**Comment by DetachHead** [comment]
why? this makes debugging even more of a pain than it already was.

**Comment by andrisi** [comment]
@DetachHead I did another run, and @mxschmitt is right. If you use PWDEBUG=1, you can still set breakpoints in VSCode, and interact with the browser when the script is stopped at a breakpoint. You need to resume the script tough if you want to be able to break on routes, that's true.

**Comment by DetachHead** [comment]
i know, that's the issue. whenever i pause using breakpoints i run into so many problems like that, but i still want to be able to use breakpoints alongside `page.pause`, because there are use cases for both.

**Comment by andrisi** [comment]
I agree. It's useful functionality, and not clear why remove it. You can name it something else, make it work when a flag is set, etc. Playwright is an excellent project from Microsoft, along with Vscode, but this feels like Windows 11 dropping the vertical talkbar. Some people like it that way... :-)

**Comment by damianobarbati** [comment]
@andrisi did you find a solution for this? page.pause method is not working for me neither

**Comment by asdf23** [comment]
I am Not using VS Code, nor any debugger.   I am however:

```
		this.page.on("pageerror", err => {
			this.onJSError(err);
		});
```

I'd like to get .pause() working again

**Comment by andrisi** [comment]
@damianobarbati sorry for the late reply. Just tried now... pause() still does not work, but you can play with the browser when the debugger is stopped on a line, and it will execute clicks at the next step you do with F10, so you might create your own version of pause() perhaps with some logic.

**Comment by neongreen** [comment]
`pause.pause()` was also broken for me, but `await page.waitForTimeout(999999)` worked fine.

**Comment by mxschmitt** [comment]
@asmyshlyaev177 @neongreen please file separate bugs.
