### ISSUE TITLE
[Question] Not appear popup to allow use camera 

### ISSUE THREAD

**Issue by Nerijus123** [microsoft/playwright#13211]
Hello, I started using Playwright on my projects and am stuck with the problem, when I can’t do anything further until the camera is allowed. 

![image](https://user-images.githubusercontent.com/29463426/161057203-96a9e4ea-7546-4e9c-91be-9f835f981cb7.png)

when I run tests in Chromium headed mode (npx playwright test --headed --project=Chromium) this popup does not even appear in window and nothing can be done further. I tried record test with playwright test recorder in Chromium window and this popup appears and when i click allow nothing is recorded to the file.  
Also I tried run test on different browsers and with Webkit was same, but with Firefox this popup appears, but I don't know how to click allow button. 
Maybe someone had already had such a situation and can offer the best way deal with camera popups?
Thank you :) 

- Playwright Version: 1.20.0
- Operating System: Windows 11
- Node.js version: v16.13.2
- Browser: Chromium, Webkit, Firefox

**Comment by mxschmitt** [comment]
You can pass the following Chromium/WebKit flag to use a fake camera: [`--use-fake-device-for-media-stream`](https://peter.sh/experiments/chromium-command-line-switches/#use-fake-device-for-media-stream)

see here: https://github.com/microsoft/playwright/issues/2525#issuecomment-1034641391

For firefox granting permissions via context.grantPermissions might be enough.

**Comment by Nerijus123** [comment]
Ok, thank you.

**Comment by mxschmitt** [comment]
Closing as per above.
