### ISSUE TITLE
[BUG] slow body snapshot

### ISSUE THREAD

**Issue by bodinsamuel** [microsoft/playwright#13225]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Linux
- Node.js version: 16.14.0
- Browser: Chromium
- Extra: https://github.com/algolia/renderscript v2.1.11

**Describe the bug**

Add any other details about the problem here.

**Code Snippet**

Hello we have been testing Playwright in prod and we have noticed some weird things when snapshotting the body of a page.
When using `page.content()` it ranges between 50ms to 20seconds, which seems weird.
Doesn't seems to happen in macOs, only in a container (GKE).
I don't have a URL for repro at the moment.

```javascript
const start = Date.now();
await page.content();
console.log('total', Date.now() - start);
```

Here is a sample of what we track
```json
{
  "metrics": {
    "timings": {
      "context": 436,
      "goto": 8378,
      "equiv": 1129,
      "ready": 10077,
      "minWait": null,
      "serialize": 25451, // This is the snap
      "close": 64,
      "total": 45535
    },
    "renderingBudget": {
      "max": 20000,
      "consumed": 45471
    },
  },
}
```

> Others samples for the same URL
As you can see from `18ms to 23138ms`
```json
{"timings":{"context":1070,"goto":10711,"equiv":2298,"ready":5923,"minWait":null,"serialize":8428,"close":89,"total":28519}
{"timings":{"context":83,"goto":2177,"equiv":595,"ready":8859,"minWait":null,"serialize":37,"close":28,"total":11780}
{"timings":{"context":905,"goto":6109,"equiv":1366,"ready":10799,"minWait":null,"serialize":20,"close":19,"total":19218}
{"timings":{"context":391,"goto":6085,"equiv":1292,"ready":12311,"minWait":null,"serialize":28138,"close":347,"total":48577}
{"timings":{"context":545,"goto":2894,"equiv":561,"ready":16018,"minWait":null,"serialize":113,"close":82,"total":20213}
{"timings":{"context":63,"goto":1237,"equiv":256,"ready":7514,"minWait":932,"serialize":19,"close":18,"total":10040}
{"timings":{"context":69,"goto":1096,"equiv":351,"ready":8359,"minWait":125,"serialize":18,"close":22,"total":10040}
```

Is there anything I can do? Maybe it's not the right method?
Thanks,

cc @mxschmitt that already take a look at our code

edit:
avg in blue
p95 in dotted purple
<img width="1105" alt="Screenshot 2022-04-01 at 00 39 51" src="https://user-images.githubusercontent.com/1637651/161161257-14015afe-1ea9-4c4d-afa8-97d2cabe6e45.png">

**Comment by rwoll** [comment]
Can you include a full script/repo that can be run like `node ./test-perf.js`? Thanks!

**Comment by bodinsamuel** [comment]
I think I have managed to find the issue, at least it does not happen again after removing `<base>` injection.
This specific code https://github.com/algolia/renderscript/blob/master/src/lib/helpers/injectBaseHref.ts

I don't have much time to debug this in particular, I'll close to not waste your time ☺️
