### ISSUE TITLE
[Question] Is there a simpler way to modify the user agent without launching a new page?

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13227]
Hi, on puppeteer I can get the browser's `userAgent` without having to launch a page:

```javascript
// example of removing "Headless" from the user agent:
const userAgent = await browser.userAgent().replace(/Headless/i, '');
page.setUserAgent( userAgent )
```

In playwright, is the only way to do this to make a new page, evaluate the `userAgent`, and then create a separate context with the modified `userAgent`?

```
 const browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  const userAgent = await page.evaluate(() => {
    return navigator.userAgent;
  });
  const context = browser.newContext({
    userAgent: userAgent.replace(/Headless/i, ''),
  });
```

**Comment by rwoll** [comment]
To my knowledge, no. But you can explicitly set the userAgent and use one of the common UAs from the `devices` like `devices['Desktop Chrome'].userAgent`.

See https://playwright.dev/docs/emulation#devices.

**Comment by davidbielik** [comment]
Thanks so much!

**Comment by himat** [comment]
Is there any way to get that devices field when using Playwright and not Playwright Test?
