### ISSUE TITLE
[REGRESSION]: `_electron.launch({...})` stops working after upgrading to macOS Monterey

### ISSUE THREAD

**Issue by ericpromislow** [microsoft/playwright#13235]
**Context:**
Running Playwright version: 1.19.1, node v16.13.1, npm 8.1.2, electron 16.0.5
- GOOD: Used to run on macOS Big Sur
- BAD: No longer runs on macOS Monterey - everything else held the same
- Operating System: Mac: the problem occurs after I upgrade to Monterey
- Extra: [any specific details about your environment]

**Code Snippet**
```javascript
...
test.beforeAll(async() => {
    electronApp = await _electron.launch({
      args: [
        path.join(__dirname, '../'),
        '--disable-gpu',
        '--whitelisted-ips=',
        '--disable-dev-shm-usage',
      ]
    });
```
**Describe the bug**

Result:
```
electron.launch: Timeout 30000ms exceeded.
      61 |     createDefaultSettings();
      62 |
    > 63 |     electronApp = await _electron.launch({
         |                                   ^
```

Add any other details about the problem here.

It's open source. To reproduce:
```
$ mkdir testdir
$ cd testdir
$ git clone https://github.com/rancher-sandbox/rancher-desktop.git
$ npm i
$ npm run test:e2e -- e2e/kubectl.e2e.spec.ts
```

**Comment by mxschmitt** [comment]
I was able to repro it. After upgrading Electron to 16.2.1 then it was working for me. so most likely something which got fixed on the Electron side end: https://www.electronjs.org/releases/stable?version=16

**Comment by ericpromislow** [comment]
Thanks, I'll give that a try.

**Comment by ericpromislow** [comment]
And it worked.
