### ISSUE TITLE
[Feature] improved typescript definitions for `BrowserContext.addCookies`

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13237]
[`BrowserContext.addCookies`][1] does not have a typed parameter for what it accepts as a cookie.

The existing `Cookie` definition requires more fields than necessary:
* path
* httpOnly
* expires
* secure
* sameSite

It would be helpful to introduce a definition to more closely match `addCookies` as well as a type for `sameSite`

Current definition is: https://github.com/microsoft/playwright/blob/7d7fe3c618464fd6d9d01afd4e679ba336ddd1ac/packages/playwright-core/types/types.d.ts#L6515

```typescript
interface {
    name: string;

    value: string;

    /**
     * either url or domain / path are required. Optional.
     */
    url?: string;

    /**
     * either url or domain / path are required Optional.
     */
    domain?: string;

    /**
     * either url or domain / path are required Optional.
     */
    path?: string;

    /**
     * Unix time in seconds. Optional.
     */
    expires?: number;

    /**
     * Optional.
     */
    httpOnly?: boolean;

    /**
     * Optional.
     */
    secure?: boolean;

    /**
     * Optional.
     */
    sameSite?: "Strict"|"Lax"|"None";
  }
```

[1]: https://github.com/microsoft/playwright/blob/7d7fe3c618464fd6d9d01afd4e679ba336ddd1ac/packages/playwright-core/types/types.d.ts#L6515

**Comment by mxschmitt** [comment]
I see no difference between the current implementation and your proposed changes in https://github.com/microsoft/playwright/pull/13238. What is the use-case or what are you trying to achieve?

**Comment by davidbielik** [comment]
@mxschmitt I have a function I use to get cookies that are meant to be set on a given page:

```typescript
export default function getPageCookies(
  domain: string
): { domain: string; path: string; name: string; value: string }[] {
   return [
       { domain: domain, path: "/", name: "auth", value: "value" }
   ]
}
```

I would prefer to instead type the return value as something like `playwright.Cookie[]` but that type is intended for reading cookies (since it requires `expires, httpOnly, secure, sameSite` which are optional for `addCookie`).

Happy to close this as it's a minor inconvenience and falls under: 

> Avoid adding "sugar" API (API that is trivially implementable in user-space) unless they're very common.

**Comment by mxschmitt** [comment]
You can do the following, would that work for you?

```ts
import {BrowserContext }from  '@playwright/test'
type Cookie = Parameters<BrowserContext['addCookies']>[0][number];

```
reference: https://www.typescriptlang.org/docs/handbook/utility-types.html#parameterstype

**Comment by davidbielik** [comment]
Oh that's perfect thanks so much - I appreciate your help here. I wasn't aware of using `Parameters`.
