### ISSUE TITLE
[BUG] When GlobalSetup fails the tests still continue

### ISSUE THREAD

**Issue by loganromero** [microsoft/playwright#13244]
**Context:**
- Playwright Version: 1.20
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: Chromium

**Describe the bug**

Throwing an error in the globalsetup does not work as expected and prevent the tests from continuing.

Adding the below image from a thread in the Playwright Slack:
<img width="836" alt="image" src="https://user-images.githubusercontent.com/50672017/161266087-241b2fab-7824-4ade-b4f4-92a71cf36939.png">
 

Add any other details about the problem here.

**Comment by rwoll** [comment]
Can you include your (1) config, (2) the output you are seeing (including what specifically makes you think the tests ran)?

I believe this is working as intended. I've added a test case here: https://github.com/microsoft/playwright/pull/13255

NB: The default mode will output:

```
Running 2 tests using 1 worker


Error: failure in global setup!

   at globalSetup.ts:5

  3 |   
  4 |           module.exports = () => {
> 5 |             throw new Error('failure in global setup!');
    |                   ^
  6 |           };
  7 |         

    at module.exports (/Users/rosswollman/code/microsoft/playwright/test-results/global-setup-default-mode-globalSetup-error-should-prevent-tests-from-executing-playwright-test/globalSetup.ts:5:19)

  2 skipped
```

This is from the linked test case, so if the test ran we'd see the log line that's in the test case.

**Comment by rwoll** [comment]
> I believe this is working as intended.

To clarify, I don't see the tests actual run when the global setup throws. This is the expected behavior.
