### ISSUE TITLE
[Feature] Expose type definition and docs for `request._guid` to uniquely identify a request ID

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13246]
Hi, in `puppeteer` there was a `request._requestId` which gave a unique ID to each network request. Does something similar exist in playwright?

I've tried making my own using `${request.utl()}-${request.timing().startTime}` but realize that `startTime` seems to be `0` within `page.on('request')` but has a timestamp on `page.on('response')`.

My use case is that I want to keep track of all requests, and later associate the responses accordingly, so that I can maintain a list of which requests were attempted, finished, and unable to finish in the given timeout.

**Comment by davidbielik** [comment]
After snooping through the code it looks like I can use `request._guid`.  I'll rename this to a feature request!

**Comment by rwoll** [comment]
It's currently an implementation detail. You can continue using it at your own risk 😄 (There's an ID that shows up in the HAR as `_requestref`; this is also to be used only at your own risk.)

Adding P3-collecting-feedback to gauge other's interest and use cases. Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
