### ISSUE TITLE
[BUG] Electron flaky tests and frozen inspector

### ISSUE THREAD

**Issue by Gregoor** [microsoft/playwright#13243]
**Context:**
- Playwright Version: 1.20
- Operating System: Mac & Linux
- Node.js version: 17.8.0
- Browser: Electron 16.0.8

**Describe the bug**

We are noticing tests passing only every nth run with our Electron setup, and otherwise failing for timeout reasons. This problem seems to also persist when opening the test in debug mode, as the inspectors controls are disabled. Simultaneously I can see the selector working in the inspector. So there is something off there.

<img width="974" alt="image" src="https://user-images.githubusercontent.com/4051932/161250982-347420cc-7dd2-469f-a5ab-1d8e86236997.png">

Our setup is quite involved, so I don't have a minimal repro but I'm of course happy to supply any other kind of info that could be useful.

**Comment by mxschmitt** [comment]
If you are able to reduce the scope of the issue but e.g. making a smaller demo app, this would help us a lot! 

Without that its more guessing, but for debugging you can set the `DEBUG=pw:api,pw:protocol,pw:browser` env vars, maybe we'll see directly something.

**Comment by Gregoor** [comment]
Thanks for the pointer!

[Here's a (quite long) log with those DEBUG flags set on](https://gist.github.com/Gregoor/675e3208c14ece5e30d70ece30998f4f).

I'll see if I manage to put a small repro together these days.

**Comment by yury-s** [comment]
It does look like there is a real bug here, but it is very hard to understand what's going on from the log alone. Feel free to open a new issue with a repro script.
