### ISSUE TITLE
[Feature] Prioritise input label during test generation

### ISSUE THREAD

**Issue by Mikoz93** [microsoft/playwright#13259]
Hello,

I've discovered playwright very recently and it's a fantastic tool so thanks! One thing I've noticed during test generation is that when interacting with an input field with an associated `<label />`,  the generated output either selects the placeholder (if available) or defaults to input's `name`. Given the recommended best practices of this tool, would it be possible to target the element using its label, when available?

Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
