### ISSUE TITLE
[Question] how to ensure caching if `browserContext.route` is used?

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13250]
The documentation states: `Enabling routing disables http cache.`

Is there a way to ensure caching for times where `route.continue()` is called?

In my use case I want to block certain requests from loading, but when other scripts are loaded (i.e. jQuery) I want it to use a cache from the same browserContext to avoid waiting for it to download again while on a different URL.

**Comment by rwoll** [comment]
> avoid waiting for it to download again while on a different URL

What are the two URLs of the pages that are loading jQuery? If they are different origins, the cache's are isolated.

> The documentation states: Enabling routing disables http cache.
> Is there a way to ensure caching for times where route.continue() is called?

No, it's part of the implementation details of request interception, and I don't think it's likely to change.

(Code pointer: https://github.com/microsoft/playwright/blob/356fc35b851977c3104ec85625b5702531c0194d/packages/playwright-core/src/server/chromium/crNetworkManager.ts#L106)

You could intercept the jQuery request and fulfill it with content you store in memory, but I don't suggest this!

**Comment by davidbielik** [comment]
makes sense, thanks again! (i assume it was via https://developer.chrome.com/blog/http-cache-partitioning/ which makes this a moot point)
