### ISSUE TITLE
[Feature] Make some fields in trace viewer easily copyable

### ISSUE THREAD

**Issue by joshuacc** [microsoft/playwright#13251]
I often end up copying fields in trace viewer for further use in another tool, and it would be nice to be able to do that without fiddling around to get my selection exactly right. The three fields I most commonly do this with are:

* Call -> Parameters -> Selector:
  * in order to paste it into the dev tools console
* Network -> Request -> Request Body:
  * In order to view it in a text editor with full formatting and collapse/expand support for JSON
* Network -> Request -> Response Body:
  *  In order to view it in a text editor with full formatting and collapse/expand support for JSON/HTML

Here's a quick example of what that might look like for selector.

![image](https://user-images.githubusercontent.com/171086/161289349-6a5926aa-16f1-4834-abee-150ce947073f.png)

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright/issues/9372
