### ISSUE TITLE
[Feature] expose `child_process` from electron launch

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#13267]
We need the `child_process` of the electron main process to ensure the process has terminated in our smoke test launches and to install some diagnostic related listeners.

//cc @pavelfeldman

**Comment by pavelfeldman** [comment]
Which one? Could you share a snippet?

**Comment by bpasero** [comment]
@pavelfeldman snippet:

```ts
const electron = playwright._electron.launch();

electron.process.stdout?.on('data', data => logger.log(`[${type}] stdout: ${data}`));
electron.process.stderr?.on('data', error => logger.log(`[${type}] stderr: ${error}`));

electron.process.once('exit', (code, signal) => {
	logger.log(`[${type}] Process terminated (pid: ${process.pid}, code: ${code}, signal: ${signal})`);

	instances.delete(instance);
});
```

Mainly for reliability of smoke tests we have our own hooks to make sure there are no stray processes around in case of issues. For example:

* we tear down all running instances when main CLI process dies ([here](https://github.com/microsoft/vscode/blob/fdbaabd571ab518243a2cd84e4800d74d755ba12/test/automation/src/code.ts#L68-L70))
* we `tree-kill` the main process to ensure not even child processes of the main process survive (such as our extension host which is a child process) - [here](https://github.com/microsoft/vscode/blob/fdbaabd571ab518243a2cd84e4800d74d755ba12/test/automation/src/code.ts#L220-L223)

Without this level of access, I have to rely on `playwright` that `Browser.close()` is properly terminating the Electron process. We already rely on that for the browser based smoke tests because there we also do not get hold off the process that is launched. But when testing in the browser, all our heavy lifting is from a server process that we also spawn, and there again we `tree-kill` it to cleanup on shutdown.

**Comment by bpasero** [comment]
Looks like we need this:

![image](https://user-images.githubusercontent.com/900690/161415162-aed534a2-14c6-4a65-8112-758d4e4a45bd.png)

**Comment by pavelfeldman** [comment]
Got it. I was confused by the "`child_process` of the electron main process" request, it sounded like you wanted a module, but you actually want the electron main process exposed.

**Comment by bpasero** [comment]
Yeah, this would even be useful for the non-electron launch when we start a browser. 

Nevertheless, disregard my above screenshot, I think another issue on my end triggered that.

To clarify: what does `Browser.close()` actually do in the Electron case? We have an internal method to quit VSCode and I am triggering that from our smoke tests to have an orderly shutdown but I noticed that the app icon was not removed from the dock unless I was calling `Browser.close()`. Wondering whether playwright is possibly preventing a tested app from quitting normally?

**Comment by pavelfeldman** [comment]
> Yeah, this would even be useful for the non-electron launch when we start a browser, just in case close() was not terminating properly.

That's Playwright's core responsibility, its takes care of closing the browsers.

> Wondering whether playwright is possibly preventing a tested app from quitting normally?

Node keeps the process running to let all the debuggers detach, you've probably seen this message many times: 'Waiting for the debugger to disconnect...'. I'll handle it to detach immediately and that way the process will exit.

> we tear down all running instances when main CLI process dies

This code should work in the test setting once I detach from debugger.

> we tree-kill the main process to ensure not even child processes of the main process survive (such as our extension host which is a child process)

Everybody has a variation of that code, ours is [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/processLauncher.ts#L167).

---

There is a slight hesitation towards exposing process on ElectronApp, but I think it is justified. The reason behind the hesitation is that Playwright is cross-language and we could theoretically allow Python users test Electron App. It is also client-server, so we could let Playwright run on one machine while running Electron on another. These both are theoretically possible today. But don't really make much sense for Electron, so I'm ok with making a shortcut and exposing the process right way.

**Comment by bpasero** [comment]
> Node keeps the process running to let all the debuggers detach

Ok good it, so my understanding is that this flow should be fine when using playwright:
* we ask VSCode to terminate which will trigger a few close handlers internally to clean up and persist state and will eventually trigger `app.quit` from Electron
* however this will not terminate electron because debuggers are attached
* we then call `Browser.close()` via playwright API
* this will now properly shutdown the process

> so I'm ok with making a shortcut and exposing the process right way.

Cool thanks!

**Comment by bpasero** [comment]
👏
