### ISSUE TITLE
My test fail when I run them in headed mode but pass in headless mode.

### ISSUE THREAD

**Issue by ssgajjar** [microsoft/playwright#13269]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Linux
- Node.js version: 16.3.0
- Browser:  Chromium

**Code Snippet**

// Click [data-test="search_button"]
  await page.locator('[data-test="search_button"]').click();
  await expect(page).toHaveURL('https://app.XXX.XXX.io/search?q=Advances%20in%20Structural%20Engineering&f=SO');

  // Click [data-test="search-result-0"] button:has-text("Read") >> nth=0
  const [page1] = await Promise.all([
    page.waitForEvent('popup'),
    page.locator('[data-test="search-result-0"] button:has-text("Read")').first().click()
  ]);
  await browser.close();
  // Go to https://0g10r4gx4-y-https-journals-sagepub-com.proxy.XXX.io/doi/pdf/10.1177/13694332211065187
  await page1.goto('https://0g10r4gx4-y-https-journals-sagepub-com.proxy.XXX.io/doi/pdf/10.1177/13694332211065187');

NOTE: This url I have modified with 'XXX' so might not work
**Bug Description**

My code is working fine in headless mode, but in headed mode it is failing 
I am getting below error
![Screenshot from 2022-04-02 16-44-45](https://user-images.githubusercontent.com/29515937/161383931-3034ae12-e07c-4c7d-83e8-e426144e2543.png)
 when it open the second url in new tab when it click on read button, second page which is opening it is in logged out mode when i run them with headed mode. 
I checked same scenario manully after performing same steps it is behaving well and i am able to see that second page after clicking on read button. so there is no issue from app. our that other page.
It looks like playwright headed mode issue to me. can you check.

**Comment by rwoll** [comment]
> ```
> // Click [data-test="search-result-0"] button:has-text("Read") >> nth=0
> const [page1] = await Promise.all([
> page.waitForEvent('popup'),
> page.locator('[data-test="search-result-0"] button:has-text("Read")').first().click()
> ]);
> await browser.close();
> // Go to https://0g10r4gx4-y-https-journals-sagepub-com.proxy.xxx.io/doi/pdf/10.1177/13694332211065187
> await page1.goto('https://0g10r4gx4-y-https-journals-sagepub-com.proxy.xxx.io/doi/pdf/10.1177/13694332211065187');
```

In your sample, you call `browser.close()`, and then in the final line you try to use a `page`. Once browser is closed, none of the contexts or pages are valid.
