### ISSUE TITLE
[Question]: Getting locator from coordinate and screenshot offsets

### ISSUE THREAD

**Issue by LucidHal** [microsoft/playwright#13273]
### Your question

Hello,

I was wondering if it was possible to get the HTML element locator at a given provided coordinate using playwright. Also, do the provided locator bounding boxes in playwright correspond to the same pixel offsets that you get when a screenshot of the browser is taken?

Thanks!

**Comment by mxschmitt** [comment]
> I was wondering if it was possible to get the HTML element locator at a given provided coordinate using playwright.

This is not yet possible, what is the use-case for it?

> Also, do the provided locator bounding boxes in playwright correspond to the same pixel offsets that you get when a screenshot of the browser is taken?

Yes they do.

**Comment by LucidHal** [comment]
> This is not yet possible, what is the use-case for it?

@mxschmitt The intended use is to be able to have some sort of connection between rendered page screenshots and the underlying HTML DOM. My company is thinking of adding some tests based on screenshots and it would be essential to have a way to connect image areas to elements in the webpage.

**Comment by mxschmitt** [comment]
So you want to use it for reporting when e.g. something in an image has changed, you want to log that e.g. selector "div.fooo" is different now? this is an interesting use-case!

**Comment by LucidHal** [comment]
Yes, that's one possible use-case. Another use-case could be scraping image urls of cats from the internet, and you could do this by passing each webpage screenshot through an object detection model and getting the image src for each element tagged with the bounding box of a cat. Having a way to connect images to corresponding HTML can prove to be quite useful for such cases.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by nicolasmendonca** [comment]
I request to re-open this issue! I have a similar requirement and locating an element based on coordinates would solve a lot of my problems. I'd love to use playwright to solve this.

**Comment by GincyAG** [comment]
I also request in re-open this issue, since the HTML text and css altering anytime, sometimes the coordinates locator will be handful..Please provide feature for locator using coordinates!

**Comment by gladyshcodes** [comment]
I also request to re-open this issue

**Comment by AzizStark** [comment]
Requesting to re-open this issue @pavelfeldman
