### ISSUE TITLE
[Question] How to locate parent element with exact child text without using RegExp? 

### ISSUE THREAD

**Issue by agataDeviniti** [microsoft/playwright#13286]
Hi, I have problem with locating element containg text. What is important, I don't want to search for child element, but I would like to find div, which one of the child element contains defined text. Let's assume I have 2 elements:
`<div><label>Playwright</label></div>`
`<div><label>Playwright is cool</label></div>`

I would like to find element _div_ with exact text "Playwright".
When looking for: playwright.locator('div >> text="Playwright"') -> it found _label_
When looking for: playwright.locator('div:has-text("Playwright")') -> it found div, but both 2 elements :(

I know I can look for: playwright.locator('div:text-matches("Playwright","gm")'), but I would like not to use RegExp (if possible)

Is there any possibility I could search for this element without using RegExp? Or maybe is there a locator allowing me to look for parent? Then I could found `<label>Playwright</label>`, and  based on this find parent(div)?

**Comment by dgozman** [comment]
Try the following snippet. Note the double quotes in the `text=` selector - these insist on the strict match. Learn more [in this guide](https://playwright.dev/docs/selectors#text-selector).

```js
page.locator('div', { has: page.locator('text="Playwright"') })
```

**Comment by Zoltanpetrik** [comment]
> Try the following snippet. Note the double quotes in the `text=` selector - these insist on the strict match. Learn more [in this guide](https://playwright.dev/docs/selectors#text-selector).
> 
> ```js
> page.locator('div', { has: page.locator('text="Playwright"') })
> ```

This does not seem to be working when the elements are in the shadow dom.

Is there a solution for that use case?

**Comment by dgozman** [comment]
@Zoltanpetrik This should pierce shadow dom like any other selector. Could you please file an issue with a repro?

**Comment by Zoltanpetrik** [comment]
@dgozman You are correct, I realized I have a completely different issue.

**Comment by mxschmitt** [comment]
Closing as per above since the main issue is answered.
