### ISSUE TITLE
[BUG] electron tracing with `snapshot: true` not very functional

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#13289]
**Context:**
- Playwright Version: `1.20.2`
- Operating System: macOS
- Node.js version: `16.x`
- Browser: `Chromium`

**Code Snippet**

This is from our use of playwright in VSCodes Electron smoke tests, so I cannot really share a snippet. We setup playwright for Electron here (not using `snapshot: true`, `sources: true` in that link, but had it enabled for the attached trace): 

https://github.com/microsoft/vscode/blob/2ada17080cd3e351e093e5fce40d36f16db3124a/test/automation/src/playwrightElectronDriver.ts#L30-L61

**Describe the bug**

See attached trace and open it on https://trace.playwright.dev/. Try to operate in the DOM and notice how that is not possible. Screenshots seem to work fine though.

![image](https://user-images.githubusercontent.com/900690/161510142-04f84491-d0e6-4a69-91fb-35b28befae1e.png)

[playwright-trace-1-searches_for_body___checks_for_correct_result_number.zip](https://github.com/microsoft/playwright/files/8408238/playwright-trace-1-searches_for_body___checks_for_correct_result_number.zip)

//cc @pavelfeldman

**Comment by pavelfeldman** [comment]
@bpasero what's the easiest for me to run VS Code as a Node/Electron process so that I could repro it, I hope there is an easy fix.

**Comment by pavelfeldman** [comment]
@bpasero try dropping this trace at https://trace.playwright.dev/next/

**Comment by bpasero** [comment]
@pavelfeldman yes much better, very cool!
