### ISSUE TITLE
[Question] How specifies the base URL to use for all relative URLs?

### ISSUE THREAD

**Issue by A-kirami** [microsoft/playwright#13293]
Hello, 
I want to know how specifies the base URL to use for all relative URLs in playwright? Just like the effect of [\<base\>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) in HTML.
I tried to use the `base_url` parameter of `browser.new_page`, but it didn't work.
Can I know what the right way is?
Thank you :)

**Comment by mxschmitt** [comment]
For what do you want to use the base URL? When you set it inside Playwright in the context options, it gets reflected in waitForRequest, waitForResponse, goto etc.

**Comment by A-kirami** [comment]
> For what do you want to use the base URL? When you set it inside Playwright in the context options, it gets reflected in waitForRequest, waitForResponse, goto etc.

Because I need to point the resources in the web page to my local resources. 
I render templates in different paths through jinja2, and then mount them to the public route. Therefore, I need to set base URL for each template to ensure that the resources in it can be loaded correctly.
I tried to set base URL in the context option, and the results were frustrating. Those resources didn't load correctly.😢

**Comment by A-kirami** [comment]
> The Playwright base url has nothing to do with the actual base URL from the page. The Playwright baseURL is for goto, waitForRequest, waitForResponse etc. If you want to set the base URL in the page, you can do it e.g. like that:
> 
> ```python
> page.evaluate("""
> const element = document.createElement('base');
> element.href = 'http://www.example.com';
> document.head.append(element);
> """)
> ```
> 
> If you need to repoint some resources, page.route might be something for you: [playwright.dev/python/docs/network#modify-requests](https://playwright.dev/python/docs/network#modify-requests)

OK, thank you for taking the time to answer the question. Wish you a happy life.
