### ISSUE TITLE
[Question] Unable to wait for or block images added to the page after page load

### ISSUE THREAD

**Issue by ericmatthys** [microsoft/playwright#13291]
I have a test that loads a page, enters a query into a search input, and then takes a screenshot of the search suggestions in a popover. No matter what I've tried, at least some of the images in the search suggestions appear to load, but not reliably 100% of the images. To work around this, I've used the `mask` option to mask the images.

```js
await page.route('**/*', (route) => {
  return route.request().resourceType() === 'image'
    ? route.abort()
    : route.continue();
});
```

Aborting the image requests does not appear to affect images added to the page after page load. The images in the initial page document appear to be aborted consistently, but not the images in the search suggestions. I've tried awaiting this function call before the `page.goto` and before the `page.fill`.

```js
await page.goto('/', { waitUntil: 'networkidle' });
```

`waitUntil: 'networkidle'` is useful for waiting for images to load consistently in the initial page document, but there doesn't appear to be a way to wait until network idle again after the initial page load when text is entered into the search input and the page changes.

**Comment by mxschmitt** [comment]
Would it be possible that you share a repro for us? This would help a lot to dig into it. If not, using Chrome DevTools, finding the related network requests you want to abort (images) and digging into them might also help (response headers, and resource type there).

> Aborting the image requests does not appear to affect images added to the page after page load.

Make sure to call `page.route` before you navigate or search, then the route handler should be active and all the requests should go through it.

There can be various reasons why it's not working, the actual resourceType detection happens inside the "browser land" so if the images get returned in a non-standard way, e.g. returned as base64 the browser does not recognise them as images.

**Comment by ericmatthys** [comment]
This appears to be related to MSW mocking with a service worker, even though the images are not explicitly mocked the requests are still going through the service worker. When the service worker is enabled, image responses appear as served from the service worker. When disabled, the images requests are appropriately aborted.

Closing in favor of https://github.com/microsoft/playwright/issues/1090
