### ISSUE TITLE
[Question] how to diagnose seemingly failing electron launches

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#13297]
/cc @pavelfeldman 

I enabled playwright based Electron smoke tests for VSCode today but had to quickly disable that again and make it not fail the build because esp. on Windows I see cases of a VSCode launch not finishing.

To clarify: we start VSCode for almost every test on a fresh user data dir, so VSCode will start 10-20 times per run. 

The glue-code is quite straightforward:

https://github.com/microsoft/vscode/blob/2ada17080cd3e351e093e5fce40d36f16db3124a/test/automation/src/playwrightElectronDriver.ts#L30-L61

```ts
const electron = await measureAndLog(playwright._electron.launch({
	executablePath: configuration.electronPath,
	args: configuration.args,
	env: configuration.env as { [key: string]: string }
}), 'playwright-electron#launch', logger);

const window = await measureAndLog(electron.firstWindow(), 'playwright-electron#firstWindow', logger);

const context = window.context();

if (tracing) {
	try {
		await measureAndLog(context.tracing.start({ screenshots: true, /* remaining options are off for perf reasons */ }), 'context.tracing.start()', logger);
	} catch (error) {
		logger.log(`Failed to start playwright tracing: ${error}`); // do not fail the build when this fails
	}
}

window.on('pageerror', async (error) => logger.log(`Playwright ERROR: page error: ${error}`));
window.on('crash', () => logger.log('Playwright ERROR: page crash'));
window.on('close', () => logger.log('Playwright: page close'));
window.on('response', async (response) => {
	if (response.status() >= 400) {
		logger.log(`Playwright ERROR: HTTP status ${response.status()} for ${response.url()}`);
	}
});
```

One of the very first things we do before running the tests is to check for `.monaco-workbench` DOM element. This is our signal that we need before we consider the window as healthy. 

A lot of cases on Windows timeout on this check and we use the method:

```
await code.driver.page.locator('.monaco-workbench').waitFor({ timeout: 40000 })
```

And then we sometimes get (Windows): 

```
  1) VSCode Smoke Tests (Electron)
       Multiroot
         "before all" hook for "shows results from all folders":
     locator.waitFor: Timeout 40000ms exceeded.
=========================== logs ===========================
waiting for selector ".monaco-workbench" to be visible
============================================================
      at Application.checkWindowReady (D:\a\_work\1\s\test\automation\src\application.ts:149:56)
      at Application._start (D:\a\_work\1\s\test\automation\src\application.ts:98:4)
      at Application.start (D:\a\_work\1\s\test\automation\src\application.ts:75:3)
      at Context.<anonymous> (src\utils.ts:92:3)
```

This is mainly an ask what to do next. Enable tracing? Enable more logging? Launching Electron is done by playwright now so we do not really know what happens to the process when this occurs.

Thanks!

**Comment by bpasero** [comment]
The log when this happens:

```
[2022-04-04T14:58:31.713Z] Starting operation 'playwright-electron#launch...
[2022-04-04T14:58:32.111Z] Finished operation 'playwright-electron#launch' successfully after 398ms
[2022-04-04T14:58:32.113Z] Starting operation 'playwright-electron#firstWindow...
[2022-04-04T14:58:32.672Z] Finished operation 'playwright-electron#firstWindow' successfully after 559ms
[2022-04-04T14:58:32.673Z] Starting operation 'context.tracing.start()...
[2022-04-04T14:58:32.675Z] Finished operation 'context.tracing.start()' successfully after 2ms
[2022-04-04T14:58:32.675Z] Finished operation 'launch playwright (electron)' successfully after 1042ms
[2022-04-04T14:58:32.675Z] checkWindowReady: begin
[2022-04-04T14:58:32.675Z] getWindowIds
[2022-04-04T14:59:12.681Z] exitApplication
[2022-04-04T14:59:12.682Z] Starting operation 'stop tracing...
[2022-04-04T14:59:12.682Z] Starting operation 'driver.exitApplication()...
[2022-04-04T14:59:12.684Z] Finished operation 'stop tracing' successfully after 2ms
[2022-04-04T14:59:12.684Z] _evaluateWithDriver
[2022-04-04T14:59:12.684Z] _getDriverHandle
[2022-04-04T14:59:12.685Z] Starting operation 'driver.exitApplication()...
[2022-04-04T14:59:12.692Z] Finished operation 'driver.exitApplication()' with error Error: page.evaluate: TypeError: Cannot read properties of undefined (reading 'exitApplication')
    at eval (eval at evaluate (:3:2389), <anonymous>:1:22)
    at t.default.evaluate (<anonymous>:3:2412)
    at t.default.<anonymous> (<anonymous>:1:44) after 7ms
```

There is a 40s gap after `getWindowIds` which indicates when the locator gave up. And the fact that there is a `TypeError` on exit indicates to me that our `window.driver` property is not accessible in the DOM. We use it to orderly quit VSCode.

**Comment by pavelfeldman** [comment]
Try running it with the DEBUG=pw:browser env set. It should print stdio of the main process, maybe there is something obvious. If that does not help, we'll need to try reproducing it. Traces won't help much if we fail to run the electron process.

**Comment by pavelfeldman** [comment]
https://github.com/pavelfeldman/vscode-test - a super-small demo of Playwright Test-based harness for VS Code tests.

**Comment by bpasero** [comment]
👍 , based on the last 24h test run I have:
* enabled playwright smoke tests for Linux and macOS because there I could not see these timeout flakiness issues
* on Windows add more tracing and logging as you suggested and keep it for `continueOnError` for now until we got to the bottom

It would also be great to get a new release for the changes around getting hold of the Electron child process.

**Comment by bpasero** [comment]
Btw one thing I noticed is that it seems more common to enable tracing only on the first retry of a test and not from the beginning, while we enable it always from the beginning. However we have somewhat a no-retry rule for our tests because the need for a retry indicates a flaky test to begin with.

**Comment by pavelfeldman** [comment]
> It would also be great to get a new release for the changes around getting hold of the Electron child process.

Our release cadence is monthly, but you can always try `@playwright/test@next` for nightly.

> Btw one thing I noticed is that it seems more common to enable tracing only on the first retry of a test and not from the beginning.

This is what we recommend to save the CPU cycles. It is actually not about flakiness, it is about a post-mortem story of the reliably failing tests.

> However we have somewhat a no-retry rule for our tests because the need for a retry indicates a flaky test to begin with.

That's a good rule to have, but we've learned that retries give richer outlook on the flakiness dashboard. We will report the test was flaky and you can interpret the result as you'd like, by either considering it passing or failing. We will return status 0 from the overall test run containing the flaky tests, but we can make it configurable, or you can add a 2 liner --reporter that would say write a file indicating that you need to consider the run as failed.

**Comment by bpasero** [comment]
@pavelfeldman 

> Our release cadence is monthly, but you can always try @playwright/test@next for nightly.

In the spirit of reducing flakiness in our tests I would not want to switch to nightlies. Maybe an alternative for me would be to depend on a commit that is a branch off `1.20.2` with the change to get access to the Electron process?

**Comment by pavelfeldman** [comment]
> Maybe an alternative for me would be to depend on a commit that is a branch off 1.20.2 with the change to get access to the Electron process?

We don't backport fixes like this, we keep users waiting instead. But v1.21 will cut this week.

**Comment by bpasero** [comment]
This turned out to be an issue with Electron where a IPC message on startup was not received / delivered.
