### ISSUE TITLE
Clicking on a button inside an angular modal dialog no longer works

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13307]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Mac and Windows
- Node.js version: 16.14.0
- Browser: Chromium

When my test attempts to click on an element inside the modal dialog, the click operation fails after successive attempts and the test fails as a result.
```
const modalDialogButton = page.locator('text=Okay');
await modalDialogButton.click();
```

The following is a log entry for the same :
  ```
selector resolved to visible <button variant="primary" class="dialog-button…> Okay </button>
   attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
  <dialog-content class="ng-star-inserted">…</dialog-content> intercepts pointer events
```

This was working earlier in playwright v1.18. this particular piece of code is failing post playwright upgrade to v1.20.1

I am using playwright's evaluate() feature to click on the button as a temporary workaround : 

`await okayButton.evaluate((button:HTMLElement)=>button.click())`

**Comment by mxschmitt** [comment]
Are you able to share a repro with us so we can run it locally?

**Comment by mxschmitt** [comment]
Could you try using `npm install @playwright/test@next` a recent Chromium version has some related bug fixes included.

**Comment by harir5** [comment]
Hi @mxschmitt - Thank you very much for the solution.

i will install the update and check it up. Just a small query on this particular installation as well - we run cross browser tests on Browserstack using playwright test. will our version change impact test runs in Browserstack please?

regd. the repro - I am afraid i cannot share the repro with you currently since i need to get required permissions from my project team. I will keep you posted on that front. 

By the way, just thought of letting you guys know that i find playwright really awesome and i love working with this automation tool ! it is simply amazing !! You/Your team does really amazing work ! :) Thank you !!

**Comment by mxschmitt** [comment]
> will our version change impact test runs in Browserstack please?

Not sure, since we don't use browser stack. It definitely could be, the alternative would be to wait for 1.21 which should get released in 1-2 weeks.

(keep in mind that the click workaround which you are using is not very elegant, since it passes all the accessibility checks which Playwright does by default)

Glad to hear! Thank you :)

**Comment by mxschmitt** [comment]
Closing as per above!

**Comment by eliBlooma** [comment]
Happens to me too in Angular 15 with playwright `1.37.0`
