### ISSUE TITLE
[BUG] Timout after navigation because "load" never fires

### ISSUE THREAD

**Issue by tillschander** [microsoft/playwright#13314]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Linux
- Node.js version: 12.22.5
- Browser: Chromium

**Code Snippet**

```js
await Promise.all([
    page.waitForNavigation({ url: 'login' }),
    page.goto('login')
]);
```
```
page.waitForNavigation: Navigation failed because page was closed!
=========================== logs ===========================
waiting for navigation until "load"
============================================================
```
```js
await page.goto('search');
await page.goto('product/123456');
await expect(page.locator('h1')).toContainText('Product Title');
```
```
page.goto: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "http://localhost:3000/product/123456", waiting until "load"
============================================================

```

**Describe the bug**

It seems like there is a bug that prevents the "load" event from firing after a navigation. It could also be that the event is fired but playwright somehow misses it. 

Unfortunately it's quite hard to reproduce this bug reliably as it's only occurring every other time in seemingly random tests.
But it happens so often that this issue is reported again and again:

https://github.com/microsoft/playwright/issues/3151
https://github.com/microsoft/playwright/issues/9028
https://github.com/microsoft/playwright/issues/9418
https://github.com/microsoft/playwright/issues/11570
https://github.com/microsoft/playwright/issues/12182
https://github.com/microsoft/playwright/issues/13027

**Comment by mxschmitt** [comment]
Are you able to share a repro with us? Already something which triggers 1/10 times would help us a lot.

A lot of the linked issues seem unrelated tho.

**Comment by tillschander** [comment]
Unfortunately the project I am working on is an internal application. So I can't share it.

I spent the last couple of hours to reproduce the issue with public websites and even built a reduced version of the internal application. But I wasn't able to reproduce the bug  :(

You can close this issue if you want to until I or someone else can reproduce the bug.

**Comment by liuxingbaoyu** [comment]
#12182 has just been fixed, it should not be the same problem, because that one fails 100%

**Comment by tillschander** [comment]
Ok I managed to find the cause for my bug:

The application i was testing uses a service worker. That service worker has a versioned filename (e.g. service-worker.a3109443.js). Due to a bug with the dev server that i was testing against that version in the filename changed with every request. Therefore a new service worker got registered on each pageload. This service worker registration hickup somehow caused the missing load event in playwright. Removing the versioning from the service worker fixed the random failing tests.

It is still a mystery to me how exactly the service worker registration caused the missing load event. Especially since it only happened sometimes. So there might still be a bug with chromium or playwright. But since it's such a niche problem it's probably not worth exploring.
