### ISSUE TITLE
[Question] Error Unable to click on a button

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#13323]
I have been trying to click on a button in my application but seeing this error `subtree intercepts pointer events, retrying click action, attempt #1` 

I have generated screenshot as well and button is visible on the page but for some reason, playwright unable to click on it

Using `page.click(locator)`

Anyone has any suggestion?

**Comment by gauravgandhi1315** [comment]
@mxschmitt Sorry I won't be able to share the repo. But it works fine locally on my machine but failing on linux machine(Jenkins). I tried to use `ElementHandle` but same issue

**Comment by gauravgandhi1315** [comment]
@mxschmitt This works for me

`await this.page.evaluate(selector => {
      return document.querySelector(selector).click();}, selector);`

**Comment by mxschmitt** [comment]
@gauravgandhi1315 Could you try using `npm install @playwright/test@next` a recent Chromium version has some related bug fixes included.
