### ISSUE TITLE
I am trying to use storeagestates  to sign in but does not work 

### ISSUE THREAD

**Issue by sohail1981** [microsoft/playwright#13322]
**Following playwright guidelines i am trying to Automate logging in before my each test

i have** 
// global-setup.js
const { chromium } = require('@playwright/test');

module.exports = async config => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://www.netflix.com/browse');
  await page.fill('[data-uia="login-field"]',' something')
  await page.fill('[data-uia="password-field"]',something')
  await page.click('[data-uia="login-submit-button"]')
  //Save signed-in state to 'storageState.json'.
  await page.context().storageState({ path: 'abc.json' });
  //await browser.close();
};

**this is what i have in playwright.config.js**

 @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
    
 
    globalSetup:require.resolve('./global-setup.js')
    
  module.exports = config;

**these are my tests** 
test.use({ storageState: 'abc.json'});
test('test', async ({ page }) => {
  await page.goto('https://www.netflix.com/browse');

});

Test always stop on netflix login page and does not proceed, when i debug i can see it always start from global-setting file , and sign in there when it reach  est('test', async ({ page }) => {
  await page.goto('https://www.netflix.com/browse');

});
 
it does not sign in 

anyone who is expert , please help me out i am kind of new :)

**Comment by liuxingbaoyu** [comment]
```
await page.click('[data-uia="login-submit-button"]')
await page.waitForTimeout(10000);//sleep
//Save signed-in state to 'storageState.json'.
await page.context().storageState({ path: 'abc.json' });
```

Maybe a little sleep will help?
Just guessing, as there is a wait to navigate through after clicking the login button.
If sleep works fine, you can use other waits, such as `waitFor` a post-login element.

**Comment by sohail1981** [comment]
> ```
> await page.click('[data-uia="login-submit-button"]')
> await page.waitForTimeout(10000);//sleep
> //Save signed-in state to 'storageState.json'.
> await page.context().storageState({ path: 'abc.json' });
> ```
> 
> Maybe a little sleep will help? Just guessing, as there is a wait to navigate through after clicking the login button. If sleep works fine, you can use other waits, such as `waitFor` a post-login element.

Thanks a lot , problem solved

**Comment by sohail1981** [comment]
adding wait before storagestate solved the issue
