### ISSUE TITLE
[Question] How to pass data from global setup to tests?

### ISSUE THREAD

**Issue by maheshsundaram** [microsoft/playwright#13337]
The documentation [1] states that

> You can pass data such as port number, authentication tokens, etc. from your global setup to your tests using environment.

Is there a more concrete example of how to do this? The example given is just for using stored authentication state. I would like to be able to pass arbitrary data that is dynamically generated in the global setup, so it can't go in the config.

Thank you! Playwright is really enjoyable to use, thank you to all the developers working on it.

[1] https://github.com/microsoft/playwright/blob/4bb563b01557b1ee2a2c43503895eb10394b697e/docs/src/test-advanced-js.md#global-setup-and-teardown

**Comment by mxschmitt** [comment]
By environment we mean you can set it as environment variables. For example inside your global setup:

`process.env.FOOOOOOO = 123`

or a more complicated data structure as JSON:

`process.env.FOOOOOOO = JSON.stringify(something)`

and inside the tests you can read it based on that:

`console.log(process.env.FOOOOOOO)`

or:

`console.log(JSON.parse(process.env.FOOOOOOO).foobar)`

**Comment by maheshsundaram** [comment]
Aha OK, thank you for explaining! I created a PR for you to consider that I think could clarify this for others - https://github.com/microsoft/playwright/pull/13397

**Comment by cre8** [comment]
In case your object is not a string, you can use `globalThis` to pass it from globalSetup to the spec files. Eg:

```typescript

export type gt = typeof globalThis;

export interface KeycloakGlobalThis extends gt {
  keycloak: Keycloak;
}

keycloak = (globalThis as KeycloakGlobalThis).keycloak;
```

**Comment by chayes-scottlogic** [comment]
@mxschmitt Hi Max, I am having this issue too. I am trying to use the globalThis to store a reference to an electron application which is initialised during global setup and then passed to the fixture file, wherein the applicable widget would be opened and passed to the tests as a page object. 

I can see my object fine in the set up code but it is undefined in the fixture, are you able to offer any advice?

**Comment by cre8** [comment]
> @mxschmitt Hi Max, I am having this issue too. I am trying to use the globalThis to store a reference to an electron application which is initialised during global setup and then passed to the fixture file, wherein the applicable widget would be opened and passed to the tests as a page object.
> 
> I can see my object fine in the set up code but it is undefined in the fixture, are you able to offer any advice?

For me the approach only worked when I reduced the amount of workers to 1. Otherwise only one worker has access to the memory storage of globalThis, all others will return undefined.

Since I need multiple workers I ended up in this:
- every object that I need in before and after is passed via globalThis
- string that are needed in the workers are passed via process.env

**Comment by chayes-scottlogic** [comment]
@cre8 Thank you so much for your reply. I tried storing an electronApplication instance in globalThis and, while it had a value when my setup code ran, it was undefined when my fixture tried to use it. I am using 1 worker too, here is my playwright.config:
`export default defineConfig({
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: require.resolve('./global-teardown'),
  testDir: './tests/',
  fullyParallel: false,
  workers: 1,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  reporter: [['junit', { outputFile: 'test-results/junit-results.xml' }]],
  use: {
    trace: 'on-first-retry',
    //storageState: ".auth/user.json",
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        //storageState: ".auth/user.json"
      },
    },
  ],
});`

Right now, I am trying to store an instance of the electron app in a static class to see whether that works. Here's the code:

`import { ElectronApplication } from "@playwright/test";

// Static class used to store an instance of the Electron Application for the tests.
export default class ElectronApplicationInstance {
  public static electronApplicationInstance: ElectronApplication | undefined;
}`

and then using it in the global set up: ElectronApplicationInstance.electronApplicationInstance = await initializeElectronApp() before then referencing it in the fixtures. Extract here:
`import { ElectronApplication, Page, test as base, expect } from '@playwright/test';
import { LoginPage } from '../page-objects/login-page';
import { OrderBook } from '../page-objects/orderbook';
import { initDesktop, waitForAppToLoad } from '../helper-methods/interopHelpers';
import { teardownElectronApplication } from './fixtureUtilities';
import ElectronApplicationInstance from '../electronApplicationInstance';
export { expect } from '@playwright/test';

type Fixtures = {
  loginPage: LoginPage,
  orderBook: OrderBook,
  electronApplication: ElectronApplicationInstance,
  machPlus: Page
};

console.log('Fixture file hit');

export const test = base.extend<Fixtures>({
  loginPage: async ({ }, use) => {
    const electronApp = ElectronApplicationInstance.electronApplicationInstance;
    console.log("loginPage fixture");
    if (!electronApp) throw new Error("Electron app is not initialized");

    const launchpad = await waitForAppToLoad("tc-launchpad", electronApp);
    //Initialize the `@interopio/desktop` library.
    const io = await initDesktop(launchpad.page);

    // Start MACH+
    io.appManager.application("MACHplus").start();

    var machPlus = await waitForAppToLoad("machPLUS", electronApp);

    const loginPage = new LoginPage(machPlus.page);
    await loginPage.verifyLoginPageIsDisplayed();
    await use(loginPage);
  },
`
Package,json:
`{
  "name": "machplus",
  "version": "1.0.0",
  "description": "TODO: Give a short introduction of your project. Let this section explain the objectives or the motivation behind this project.",
  "main": "index.js",
  "directories": {
    "doc": "docs"
  },
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.45.3",
    "@types/node": "^20.12.11"
  },
  "dependencies": {
    "@azure/identity": "^4.4.1",
    "@interopio/desktop": "^6.5.1",
    "dotenv": "^16.4.5",
    "otpauth": "^9.3.1"
  }
}
`
@mxschmitt do you have any thoughts? I would be so grateful for any guidance at this point!

**Comment by mxschmitt** [comment]
@chayes-scottlogic Playwright uses multiple workers to run tests, hence creating a static instance somewhere doesn't work. Your global setup might run in a different thread compared to your tests.

Usually for testing electron applications, customers use [serial mode](https://playwright.dev/docs/test-retries#serial-mode) and have a electron instance per file = per worker.

**Comment by chayes-scottlogic** [comment]
@mxschmitt Thank you for your reply. I have Playwright configured to use one worker but will add in serial mode. Are people using beforeAll, beforeEach, etc in each spec file?

Also, does your advice change in any way if the application under test is also using interop.io (Glue42)?

I really appreciate your help, thank you!

**Comment by mxschmitt** [comment]
Depends on how the application is structured or how you want to test it. If you want to make it reusable, folks also tend to put their launch of the electron application inside worker fixtures: https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures

> Also, does your advice change in any way if the application under test is also using interop.io (Glue42)?

I'm not familiar with that, so unfortunately I can't answer that.

**Comment by JonWallsten** [comment]
@mxschmitt: What would be the approach when you use the `--ui` flag? Then it's separate processes, so the process.env cannot be used. I guess that also applies for the globalThis that someone suggested.

**Comment by chayes-scottlogic** [comment]
@mxschmitt Apologies, I just saw your reply (thank you!).

Right now we are using beforeAll() and afterAll() to handle launching the application, completing both Azure and market authentication, and creating instances of all the widgets under test (which are themselves web apps). For context, Glue42 / Interop.io is an interoperability framework which allows the widgets to pass data between them. We mostly don't need to care about it but do need to use their api to open the widgets under test, e.g.:

` await ioInstance.appManager.application(appName)?.start();
   const widget = await waitForAppToLoad(appName, electronApp);`

How would using a worker defined fixture differ from the test.beforeAll() / afterAll() approach? 
Is there any way to pass any state between spec files?

I appreciate your help! Thank you.
