### ISSUE TITLE
[Feature] Statically parse selectors before executing tests

### ISSUE THREAD

**Issue by IanVS** [microsoft/playwright#13332]
This is just an idea, but I found that sometimes I have a small typo in a selector, and it doesn't error until playwright actually tries to execute it, then I get a parse error.  It might be nice to perform a static analysis of the selectors up-front, to fail fast.  This might not always be possible (e.g. if the selectors aren't just string literals), but it might be useful at least as a "best effort" attempt.

**Comment by mxschmitt** [comment]
Could you share with us what kind of typos you mean?

**Comment by enricopolanski** [comment]
I guess something malformed as `locator(foo[bar=baz)`.

**Comment by IanVS** [comment]
Exactly.  I think I had an extra `]` somewhere.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-vscode/issues/61

**Comment by IanVS** [comment]
I think there could be value to others who do not use vscode if this were done at the very start of the test run itself, but I do use vscode, so I won't complain.  :).
