### ISSUE TITLE
[BUG] Unable to set viewport width and capture fullpage screenshot

### ISSUE THREAD

**Issue by sarayourfriend** [microsoft/playwright#13339]
**Context:**
- Playwright Version: 1.20.2
- Operating System: Linux (running inside the Playwright docker container)
- Node.js version: 16
- Browser: All

**Code Snippet**

```javascript
// @ts-check
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'webkit', 'firefox']) {
    /** @type {import('playwright').Browser} */
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext({ viewport: { width: 320, height: 1000 }});
    const page = await context.newPage();
    await page.goto('https://playwright.dev');
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```

Reproduction link on Playwright playground: https://try.playwright.tech/?l=javascript&s=hmy3u0h

Note that the screenshots have the `https://playwright.dev` page cut off and it does not show the full page.

**Describe the bug**

It seems that setting the viewport explicitly disallows taking full page screenshots. As far as I can tell this means it's not possible to take full page screenshots at any viewport width than the default. There's no way to _not_ pass a width to the `viewport` option of `test.use` (Playwright will throw an error about expecting `undefined` to be a `number`).

No warning or anything will happen but the screenshot generated will be the height passed to `test.use` rather than the full page.

**Comment by sarayourfriend** [comment]
Sorry, my reproduction was incorrect, I forgot the `fullPage: true` argument in the reproduction :facepalm: It seems to work fine in the Playwright playground, but does not work in the context of `test.use({ viewport ... })` locally inside the docker container.

I'm not sure why it doesn't work for me in our current set up, but it appears to be an issue with our set up and not Playwright. Or it could be with `@playwright/test` and `test.use` in particular :shrug: I'll keep debugging and open an new issue or update this one if I find an actual reproduction.

**Comment by sarayourfriend** [comment]
This turned out to be an issue with the way our page was structured in particular. We had some `overflow: hidden` set on elements that wrapped the entire page that caused the full page screenshots to fail.

**Comment by mnpenner** [comment]
@sarayourfriend Did you find a workaround? I have `overflow: hidden` on my `body` element but I need it to prevent double scrollbars because of how my page is structured.

Neither

```ts
await page.screenshot({path: testInfo.outputPath('before-save.png'), fullPage: true})
```

Nor

```ts
await page.locator('#page-content').screenshot(({path: testInfo.outputPath('before-save.png')}))
```

Works for me, the screenshots are always cut off to only show what was in the viewport.

**Comment by sarayourfriend** [comment]
The workaround we used was to remove the `overflow: hidden` before calling `screenshot`. Here's the utility function we wrote to ease that: https://github.com/WordPress/openverse-frontend/blob/32ce30625757aaab6e0c50cb3655e683f1a4730f/test/playwright/utils/page.ts#L3-L13

However, I think we might not need it any more. A few months ago we significantly restructured the HTML of our app ([here's one of the PRs that was involved in that, not sure if it would be helpful](https://github.com/WordPress/openverse-frontend/pull/1257)) and managed to remove the fixed height (or something?). Sorry, it's been a while since we addressed the issue so I don't remember exactly, but it did take quite a bit of working as you can see in the PR. It's probably pretty application specific in the end :confused:

**Comment by mnpenner** [comment]
Thanks! I think I found a workaround for my use-case. Instead of removing the `overflow: hidden` I just stretch the viewport:

```ts
async function screenshotFullPage(page: Page, path: string) {
    return screenshotElement(page.locator('.page-wrap'), path)
}

async function screenshotElement(locator: Locator, path: string) {
    const page = locator.page()
    const height = await locator.evaluate(el => el.scrollHeight)
    const viewportSize = page.viewportSize()
    const needsResize = height > viewportSize.height
    if(needsResize) {
        await page.setViewportSize({width: viewportSize.width, height: Math.ceil(height)})
    }
    await locator.screenshot(({path}));
    if(needsResize) {
        await page.setViewportSize(viewportSize)
    }
}
```

My `.page-wrap` is basically

```css
.page-wrap {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    overflow-y: scroll;
}
```

So I figure I need to stretch that element before I can screenshot it properly.

**Comment by maxisam** [comment]
feel like we shouldn't close this one, it is still an issue. fullpage : true actually change the viewport and i can't let it take screenshot full page for certain width
