### ISSUE TITLE
[BUG] Default viewport but actual page in 800x600

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1334]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Linux

**Code Snippet**

```javascript
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium']) {
    const browser = await playwright[browserType].launch({
      headless: false,
      slowMo: 250,
    });
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await browser.close();
  }
})();
```

**Describe the bug**

When running the above test, the actual viewport is [the default](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions) `1280x720`, but the actual page ends up inside a frame just `800x600`.

![viewport](https://user-images.githubusercontent.com/30827238/76413290-73a9b480-6395-11ea-8f18-ff0e68981731.png)

**Comment by aslushnikov** [comment]
> When running the above test, the actual viewport is the default 1280x720, but the actual page ends up inside a frame just 800x600.

@thernstig is this visually unpleasant, or there's some functional change that happens and fails tests?

**Comment by jperl** [comment]
This is visually unpleasant for us too and confusing for users. We would like to use the default new context in our template w/o configuring it since it is less code/simpler, but probably cannot unless this is changed.

**Comment by JoelEinbinder** [comment]
> This is visually unpleasant for us too and confusing for users. We would like to use the default new context in our template without configuring it since it is less code/simpler, but probably should not unless this is changed.

What are you doing instead of the default?

**Comment by jperl** [comment]
In the past, we used this since it is the most common desktop size https://gs.statcounter.com/screen-resolution-stats/desktop/worldwide. However I think 1280x720 is fine too.

```
viewport: {
  width: 1366,
  height: 768,
  deviceScaleFactor: 1,
  isMobile: false
}
```

**Comment by JoelEinbinder** [comment]
Oooh! I think I see what is going on. We changed the viewport in the upcoming release. 0.11.1 is still on 800x600. See https://github.com/microsoft/playwright/blob/v0.11.1/docs/api.md#browsernewcontextoptions vs https://github.com/microsoft/playwright/blob/master/docs/api.md#browsernewcontextoptions

The next release should fix this.

**Comment by jperl** [comment]
I’ll double check when I get home but I think this issue is in playwright@next.

**Comment by thernstig** [comment]
Oh, so this should be closed? That's good news.
