### ISSUE TITLE
How to compare snapshots in Jenkins environment

### ISSUE THREAD

**Issue by fa66-coder** [microsoft/playwright#13349]
Currently, I have added **"npx playwright test --update-snapshots"** in the **Jenkins pipeline** to update the snapshots if they are not there.
In my scenario, I am taking a screenshot of a table with 3 columns and comparing the snapshot, In local if snapshots are missing we will update snapshots in the next run and continue and those snapshots will be saved and used for future runs.

But in Jenkins, for each run snapshots will always be missing and it will update new snapshots, what if the test case captured the wrong data and update the snapshot, In this case how could we know that the data captured is wrong but the test case got passed as there is no snapshot and wrong snapshot got updated.

May I know how to handle such scenarios in Jenkins?

Thanks!

**Comment by mxschmitt** [comment]
Usually you update the snapshots on your local machine, you need to ensure that the correct data is shown by doing e.g. page.locator('text=Foo').waitFor(); and then updating the snapshot.

Does your Jenkins server automatically update them when a PR was created into your Git repository?

**Comment by fa66-coder** [comment]
I am adding "npx playwright test --update-snapshots" in the Jenkins pipeline which is updating the snapshots, it is not picking the snapshots from locally saved one as in Jenkins snapshot names are suffixed with Linux env

**Comment by mxschmitt** [comment]
If your Jenkins server and your local machines have a different operating system, you can set the snapshotSuffix to nothing or something different: https://playwright.dev/docs/next/api/class-testinfo#test-info-snapshot-suffix

`test.info().snapshotSuffix = ''`

Keep in mind that browsers can still produce different screenshots, because their rendering engine logic differs per platform.

(If I understand your question correctly)

**Comment by fa66-coder** [comment]
@mxschmitt  - My local machine runs on windows and Jenkins runs on Linux , if I put snapshotsuffix = "" then as you said the browser can still produce different screenshots, could you please guide me on how to address this scenario as this comparison is a core part of my test cases. It will be very helpful if you could provide me with a workaround or any best solution to address the scenario.

Thanks!

**Comment by aslushnikov** [comment]
@fa66-coder you need to take the screenshots that were generated by your Jenkins run and commit them to your repository.
