### ISSUE TITLE
[BUG] webkit: page.waitForNavigation() runs into timeout

### ISSUE THREAD

**Issue by vekunz** [microsoft/playwright#13346]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Linux (official playwright docker image)
- Node.js version: (from official docker image)
- Browser: WebKit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await firstMovieCard.locator('[data-testid=movieName]').click();
await page.waitForNavigation({waitUntil: 'networkidle'});
```

**Describe the bug**

We have a single-page application with SvelteKit and the .click() triggers a single-page navigation. Because of some timing issues, we have to use .waitForNavigation() to wait, until the single-page navigation is ready. In Chrome and Firefox, this works fine, but in WebKit, this seems to fail sometimes. It fails not every time, but often (sometimes more often, sometimes less often).

```
    Timeout of 30000ms exceeded.

    page.waitForNavigation: Navigation failed because page was closed!
    =========================== logs ===========================
    waiting for navigation until "networkidle"
    ============================================================

      10 |
      11 |     await firstMovieCard.locator('[data-testid=movieName]').click();
    > 12 |     await page.waitForNavigation({waitUntil: 'networkidle'});
         |                ^
      13 |
      14 |     await expect(page.locator('h1')).toHaveCount(1);
      15 |     await expect(page.locator('h1')).toHaveText(movieTitle);

```

**Comment by tillschander** [comment]
The timeout could be due to a race condition. The docs recommend to wrap navigation caused by events (e.g. click) with Promise.all(): https://playwright.dev/docs/api/class-page#page-wait-for-navigation

Try this:
```js
await Promise.all([
  page.waitForNavigation({waitUntil: 'networkidle'}),
  firstMovieCard.locator('[data-testid=movieName]').click()
]);
```

**Comment by vekunz** [comment]
It seems that this fixed the issue. I run the tests more than 20 times and they didn't failed.

**Comment by mxschmitt** [comment]
cool, feel free to file a new bug if you still encounter it.
