### ISSUE TITLE
[Question] How do i set up variables that can be used in other test files

### ISSUE THREAD

**Issue by aisabel** [microsoft/playwright#13347]
I would like to create a random variable in a test file, and then use this variable as parameter in another file. 
Would you please let me know how to do that?

**Comment by mxschmitt** [comment]
This is not recommended, since workers gets re-created and then a new Node.js worker gets spawned see [here](https://playwright.dev/docs/test-parallel).

What kind of data do you want to share? A fixture might work for you use-case: https://playwright.dev/docs/test-fixtures
