### ISSUE TITLE
[Question] WebKit for Windows: Color Profile (Display P3) and Color Scheme (Dark Mode) Support

### ISSUE THREAD

**Issue by fuweichin** [microsoft/playwright#13350]
I want to try Display P3 color in CSS, but nowdays there is no Mac by my side, I use a Windows PC and a 4K HDR retina monitor.

Chrome can recognize the monitor as HDR so `color-gamut: p3` maches, but it doesn't support [CSS Color Module Level 4](https://www.w3.org/TR/css-color-4/) yet so it doesn't support `color: color(display-p3 1 1 1)`.

Playwright WebKit (Win) supports CSS Color Module Level 4, but it cannot recognize the monitor as HDR. it cannot recognize  Dark Mode so `prefers-color-scheme: dark` doesn't match. 😭 

| Feature \\ Detected/Recognized \\ Browser  | Chrome (Win) | Safari (iOS) | Playwright WebKit (Win) |
| -------------------------------- | ------------ | ------------ | ----------------------- |
| Media Query                      |              |              |                         |
| `color-gamut: p3`                | Yes          | Yes          | No                      |
| `prefers-color-scheme: dark`     | Yes          | Yes          | No                      |
| CSS supports                     |              |              |                         |
| `color: color(display-p3 1 1 1)` | No           | Yes          | Yes                     |

Will Playwright WebKit (for Windows) add some basic OS integration and device detection thus I can use it as sort of "Safari for Windows"?

**Comment by mxschmitt** [comment]
Would emulating color-gamut work for you? Detecting it from the system is most likely not gonna be added to WebKit for Windows, since the WebKit for Windows implementation has not that many OS integrations and we mostly use it for emulation.

**Comment by mxschmitt** [comment]
Closing as per above. If you are interested in emulating color-gamut, please file a separate feature request!
