### ISSUE TITLE
snapshot captures incomplete render on chromium and Firefox.  Requires await timeout to work correctly.

### ISSUE THREAD

**Issue by john-w-cole** [microsoft/playwright#13357]
**Context:**
- Playwright Version: 1.20.2
- Operating System: Mac or Linux
- Node.js version: 16.14.2
- Browser: Chromium and Firefox
- Extra: Occurs running locally or using the playwright docker image

## System:
 - OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 5.59 GB / 9.73 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.2 - /usr/bin/node
 - Yarn: 1.22.18 - /usr/bin/yarn
 - npm: 8.5.0 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
 - 
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { test, expect } = require("@playwright/test");

test("storybook cno checkbox", async ({ page }, { title }) => {
  await page.goto("http://localhost:6006/iframe.html?id=cno-checkbox--checkbox&args=&viewMode=story");

  const firstCheckbox = await page.locator(
    "label[for='check1']"
  );

  const input = await page.locator("input#check1");

  await expect(input).toBeChecked();

  await firstCheckbox.click();

  await expect(input).toBeChecked({ checked: false });

  await firstCheckbox.click();

  await expect(input).toBeChecked();

  // const label = await page.locator('h4').first();
  // await label.waitFor({ state: "visible" });

  const input2 = await page.locator("input#check2");
  await input2.focus();

  await page.waitForTimeout(3000);
  await expect(await page.screenshot({ animations: "disabled" })).toMatchSnapshot(`${title}.png`);
});
```

When creating screenshots, a `await page.waitForTimeout(3000);` is required for Chromium and Firefox to render all of the page elements.  Webkit seems to work every time.  This causes random elements to disappear in the snapshot tests, which fails the test.

Without the timeout:
![storybook-cno-checkbox-firefox-linux](https://user-images.githubusercontent.com/91089547/162036713-44b4ae20-24f1-45a6-b9c2-2bb45ef5d6bc.png)

With the timeout:
![storybook-cno-checkbox-actual](https://user-images.githubusercontent.com/91089547/162036806-d68ba176-b019-452b-b230-d14361072297.png)

playwright.config.js

```javascript
// playwright.config.js
// @ts-check
const { devices } = require("@playwright/test");

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
  globalSetup: "./tests/e2e/setup.js",
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  testDir: "tests/e2e",
  use: {
    trace: "on-first-retry"
    // ignoreHTTPSErrors: true,
  },
  projects: [
    {
      name: "chromium",
      use: { browserName: "chromium", ...devices["Desktop Chrome"] }
    },
    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"], headless: true }
    },
    {
      name: "webkit",
      use: {
        browserName: "webkit",
        ...devices["Desktop Safari"],
        colorScheme: "light"
      }
    },
    {
      name: "webkit-dark",
      use: {
        browserName: "webkit",
        ...devices["Desktop Safari"],
        colorScheme: "dark"
      }
    },
    // "Pixel 4" tests use Chromium browser.
    {
      name: "Pixel 4",
      use: {
        browserName: "chromium",
        ...devices["Pixel 4"]
      }
    },
    // "iPhone 11" tests use WebKit browser.
    {
      name: "iPhone 13",
      use: {
        browserName: "webkit",
        ...devices["iPhone 13"]
      }
    }
  ]
};

module.exports = config;
```

**Comment by mxschmitt** [comment]
Random elements should not disappear, are we talking about the red "Error" element? Would be good to have a repro for that, this would help us to dig into it. Depending on how the control is implemented it might or might not be a Playwright issue.

**Comment by john-w-cole** [comment]
The error element _and_ the headings are missing without a timeout to wait.  The controls are very basic, and simpler controls have the same issue.  I'll see about putting an example repo together.

**Comment by aslushnikov** [comment]
@john-w-cole It looks like the page is slow to render. 

Usually you'll have to await preconditions before taking screenshot; make sure to use something like

```js
await expect(page.locator('text=Error')).toBeVisible();
await expect(page.locator('h1', { hasText: 'Basic' })).toBeVisible();
```

However, this is just speculation; hard to say without an actual repro. I'll close for now; feel free to re-file if you have a repro for us to debug!
