### ISSUE TITLE
Unable to run playwright test on windows 10 through jenkins

### ISSUE THREAD

**Issue by yuvals41** [microsoft/playwright#13355]
**Context:**
- Playwright Version: [1.20.2]
- Operating System: [Windows]
- Node.js version: [v16.14.2]
- Browser: [Chromium]
- Extra: [any specific details about your environment]

error in jenkins:
`19:00:27 > playwright test
19:00:27 
19:00:31 Build step 'Execute Windows batch command' marked build as failure
19:00:32 Finished: FAILURE`

**Describe the bug**

We tried running` playwright test` and `npx playwright test` (with different arguments) on **windows 10** through **jenkins**, but the job exits and doesn't do anything, doesn't provide any log or stdout, we have no clue to why this is happening, we tried setting different env variables (like `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD`, `PLAYWRIGHT_BROWSERS_PATH`) but nothing changed, but the program does work locally, but through the jenkins it fails

any idea to why this is happening

**Comment by mxschmitt** [comment]
Could you share your Jenkinsfile with us?

**Comment by yuvals41** [comment]
we are using freestyle job
the bat commands we run are:
```
set NODE_ENV=stg
npm i
npx playwright install
npx playwright test
```

**Comment by mxschmitt** [comment]
Hmm this does not help much. Is there any other output shown? Try to set the `DEBUG=pw:api,pw:browser` environment variable which should yield to more output.

**Comment by yuvals41** [comment]
Our bad the logs where turned off we didnt see why the job was failing
