### ISSUE TITLE
[Feature] context.useStorageState(state)

### ISSUE THREAD

**Issue by rai-gaurav** [microsoft/playwright#13353]
I have few performance scenarios where I have to connect to existing browser which I am able to do with `connect_over_cdp`
Also I am planning to reuse the authentication state to speed up the test.
I followed - https://playwright.dev/python/docs/auth#reuse-authentication-state and able to do it perfectly fine for new_context.
But for an existing browser I am not able to find any details in documentation.

For an existing browser session I am able to use `context.storage_state()` to save the state after attaching playwright to it.
Similarly is there any function from which I can pass the saved storage state using context (e.g. `context.use_storage_state(storage_state)`)?
Since `connect_over_cdp` return the context, I can't use `new_context`.

I am using the python flavor but not able to find something in node also, hence asking the question here.

**Comment by mxschmitt** [comment]
This is not yet possible, I'll convert it into a feature request. Please upvote above for others.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
