### ISSUE TITLE
Any way to have playwright use our own set of browsers by default?

### ISSUE THREAD

**Issue by derwerner95** [microsoft/playwright#1336]
Hello,

I work as part of a team where we want to implement qawolf which uses playwright library for a continuous integration project. Our idea is to have dedicated "workers" who only need an initial setup on expert level which then can be called and issued different tests from our own web application.

Is there any simple way to install my own set of browsers into the playwright library which playwright will try to call by default?

I would appreciate all kinds of advice and suggestions!

**Comment by aslushnikov** [comment]
> Is there any simple way to install my own set of browsers into the playwright library which playwright will try to call by default?

@derwerner95 what browsers are you looking to install? Playwright currently ships [modified webkit & firefox](https://github.com/microsoft/playwright#q-what-browser-versions-does-playwright-use), so it's only possible to use these atm.

**Comment by derwerner95** [comment]
@aslushnikov I'm mainly looking at Firefox ESR and chromium for now.

**Comment by aslushnikov** [comment]
> I'm mainly looking at Firefox ESR and chromium for now, but modified installations.

@derwerner95 by "modified installations" - do you mean that you want to install browsers separately from the library?

**Comment by derwerner95** [comment]
Either that, or install them into the library - whatever works would be fine for me.

**Comment by pavelfeldman** [comment]
Please refer to the installation docs on how to specify the browsers to use [here](https://playwright.dev/#version=v1.1.1&path=docs%2Finstallation.md&q=). Not that Playwright only works with the browsers it bundles. Feel free to file bugs for the remaining issues!
