### ISSUE TITLE
[Question]How to implement code coverage to playwright project with nodjs

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#13378]
Hi, We are using NodeJS with playwright. We want to implement code coverage in our project. I have browsed this "https://github.com/mxschmitt/playwrighttestcoverage"  repo but here they are using it locally. But we need to do qa environment or prod environment so I don't know how to do it, can you help me. Thank you in advance.

**Comment by mxschmitt** [comment]
Tracking code coverage out of the box is not supported yet, see here for a feature request: https://github.com/microsoft/playwright/issues/9208

For further questions I'd file an issue in their repository.
