### ISSUE TITLE
[Feature]: Save screenshots as WebP and AVIF

### ISSUE THREAD

**Issue by janosh** [microsoft/playwright#13385]
This works in `puppeteer`

```js
await page.screenshot({ path: 'test.webp' })
```

but raises in Playwright

```js
Error: path: unsupported mime type "image/webp"
```

Would be great if Playwright supported saving screenshots in WebP and AVIF format.

Related Puppeteer issues:
- AVIF: https://github.com/puppeteer/puppeteer/issues/6963 
- WebP: https://github.com/puppeteer/puppeteer/issues/5348

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
