### ISSUE TITLE
[Question] Dashboard service for monitoring

### ISSUE THREAD

**Issue by KevinCocquyt39** [microsoft/playwright#1338]
Dear,

We have been looking into this service (https://flood.io/) to setup (performance) monitoring by executing certain automated UI tests, and I was wondering if there are any plans to have a similar product in the future? One that supports 'playwright' (NodeJS) scripts, or does this already exist?

Kind regards,
Kevin Cocquyt

**Comment by aslushnikov** [comment]
>  I was wondering if there are any plans to have a similar product in the future? 

@KevinCocquyt39 We currently don't have plans for anything like this, put we think about this from time to time. We'll see how it goes :)

**Comment by danm** [comment]
Any more thoughts?!

**Comment by punkpeye** [comment]
I am working on this! :-)
