### ISSUE TITLE
[BUG] waitFor set timeout doesn't work in headless mode but does work in headed mode

### ISSUE THREAD

**Issue by exkungen** [microsoft/playwright#13383]
**Context:**
- Playwright Version: ^1.18.1
- Operating System: Linux
- Node.js version: v16.13.1
- Browser: Chromium

**Code Snippet**

```javascript
test('2.4 - Delete a new sandbox', async ({ page }) => {
  page.setDefaultTimeout(600000);
  const APP = 'baseline-sandbox-delete';
  const SANDBOX = 'development';

  const applicationPage = new ApplicationPage(page);
  await expect(applicationPage.getApplicationTitle(APP)).toBeVisible();
  const sandbox = await applicationPage.getSandboxOrBranchElement(SANDBOX);
  const sandboxExists = (await sandbox.count()) > 0;
  if (!sandboxExists) {
    await applicationPage.createSandbox(SANDBOX);
    await expect(applicationPage.creatingSandboxOrBranchText).toBeVisible();
    const loading = applicationPage.creatingSandboxOrBranchText;
    await loading.waitFor({ state: 'hidden', timeout: 600000 });
  }
  await applicationPage.deleteSandbox(SANDBOX);
  await expect(sandbox).toHaveCount(0);
});
```

**Describe the bug**

Wen running the test as described above in headed mode with `PWDEBUG=1` I can see that the test pauses until the loading element disappears and then continues with the deletion part which is what I expect. However when running the test in headless mode it seems to ignore the timeout thus resulting in the test to fail because the loading state is still visible at that time.

Error:

`Timeout of 30000ms exceeded.

    Pending operations:
      - locator.waitFor at tests/applications/applications.spec.ts:87:19

    locator.waitFor: Target closed
    =========================== logs ===========================
    waiting for selector "p:has-text("%")" to be hidden
      selector resolved to visible <p class="sc-TBWPX joiGzv">0%</p>
    ============================================================

      85 |     await expect(applicationPage.creatingSandboxOrBranchText).toBeVisible();
      86 |     const loading = applicationPage.creatingSandboxOrBranchText;
    > 87 |     await loading.waitFor({ state: 'hidden', timeout: 600000 });
         |                   ^
      88 |   }
      89 |   await applicationPage.deleteSandbox(SANDBOX);
      90 |   await expect(sandbox).toHaveCount(0);
`

**Comment by mxschmitt** [comment]
Could you share your playwright config with us? Maybe you have a timeout there configured which might explain the 30 seconds test timeout.

**Comment by exkungen** [comment]
Sure this is my config:
```
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./tests/global-setup'),
  use: {
    // Tell all tests to load signed-in state from 'storageState.json'.
    storageState: 'storageState.json',
    locale: 'cimode',
  },
  retries: 2,
};
export default config;
```

**Comment by aslushnikov** [comment]
@exkungen you have lots of POM's used here and there, they all might have some 30 seconds timeout inside. Could you please create a repro that illustrates the issue and that we can run locally?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by yaml-ns** [comment]
Same problem. Code works headed mode but doesn't in headless mode.  

- Playwright Version: 1.23.0
- Operating System: Linux / Windows
- Python : 3.7
- Browser: Chromium

```
response = page.goto(source)
page.wait_for_selector('a[href="' + url + '"]')
result = bout_scrap(page.content(), url)
```



```
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "a[href="https://portail-scpi.fr/"]"
============================================================

```

**Comment by emircanerkul** [comment]
@pavelfeldman Information was provided but why did you close this issue?

Could you please open it again?

The same problem again both chrome and msedge have this issue.

`"@playwright/test": "^1.29.2"` was used while observing this error.

## Sample Code:
```js
const browser = await chromium.launch({
    headless: true,
    channel: "msedge"
});

const page = await browser.newPage();
await page.goto(path);
await page.waitForSelector('.put-something'); // Observe the problem
```

Thank you.

**Comment by real-zony** [comment]
For me, this solution resolved my issue: https://github.com/puppeteer/puppeteer/issues/1922#issuecomment-594607547
![image](https://github.com/microsoft/playwright/assets/3907132/53810efb-43c3-4e1d-b7e1-2f009d6ed9b4)
