### ISSUE TITLE
[Feature] waitForFocusChange

### ISSUE THREAD

**Issue by farens** [microsoft/playwright#13388]
Context:
I am currently working on a web app which is used on TVs only. The navigation works with the TV's remote only. Instead of clicking around with the mouse, the focus moves by using arrow keys.

Current issue:
I want to wait for the focus to have changed after a down arrow navigation to the next element. But currently i use waitForTimeout(200) which is ugly(potentially flaky) and probably takes longer than necessary. As a lot navigation happens, these milliseconds add up as our tests grow.

Feature request:
Similarly to waitForNavigation, i'd like to have a waitForFocusChange() which waits for a locator ":focus" to point to a different target than it pointed before i pressed the down arrow.

Alternatively i was hoping that the upcoming expect.poll would help me, but as long as it won't provide the interval as an option it wouldn't make it quicker. If poll would have an interval option, i'll try to use 20ms as interval and 500ms as timeout.

Would it be possible to build one of these two features/ideas or did i miss something and i could have done it somehow already?

Thanks in advance :)

**Comment by mxschmitt** [comment]
You can do it yourself, since its not very common. Would that work for you?

```ts
  // ...
  setTimeout(() => {
    page.focus("text=Twitter").catch(console.log)
  }, 2000)
  // after 2 seconds this will resolve since the focus has changed.
  await waitForFocusChange(page);
  // ...

async function waitForFocusChange(page) {
  const currentActiveElementHandle = await page.evaluateHandle(() => document.activeElement)
  await page.waitForFunction((currentActiveElementHandle) => currentActiveElementHandle !== document.activeElement, currentActiveElementHandle);
}
```
