### ISSUE TITLE
[REGRESSION]: screenshots of XML files have CSS styles appended at the end

### ISSUE THREAD

**Issue by twbryan** [microsoft/playwright#13394]
**Context:**
- GOOD Playwright Version: 1.18
- BAD Playwright Version: 1.19, 1.20
- Operating System: Linux, Mac
- Extra: (using chromium)

**Code Snippet**

```javascript
const { chromium } = require("playwright-chromium");

(async () => {
  const browser = await chromium.launch({
    headless: true,
  });
  const context = await browser.newContext();

  const page = await context.newPage();
  await page.goto("https://gentle-monstera-87881e.netlify.app/f.xml");
  let ss = await page.screenshot({ path: "screenshot.png" });

  await context.close();
  await browser.close();
})();
```

**Describe the bug**

Screenshots of XML files have playwright CSS styles appended to the end of them. In 1.18 and prior, you'd get a clean screenshot of the XML file. In 1.19 and beyond you see styles at the end. Example screenshot:

![screenshot](https://user-images.githubusercontent.com/48530494/162268954-49be0446-f34f-4081-a498-1af32dc9dafb.png)

**Comment by dgozman** [comment]
In v1.21, you will be able to just pass `caret: 'initial'` option to the `page.screenshot()` call. Since screenshotting XMLs is not an intended usecase, I think that should be a good-enough workaround.

**Comment by twbryan** [comment]
sounds reasonable, thanks for the quick turnaround
