### ISSUE TITLE
[Question] Are cookies set with context.addCookie expected to be immutable?

### ISSUE THREAD

**Issue by neongreen** [microsoft/playwright#13390]
I am setting an auth cookie with context.addCookie() and then making a request (/logout) that should result in the cookie being unset. However, the cookie remains. If I login and do the logout manually, the cookie is unset properly.

Is this expected behavior?

**Comment by liuxingbaoyu** [comment]
Check the `domain` and other parameters, maybe it will help.
```
export type SetNetworkCookieParam = {
  name: string,
  value: string,
  url?: string,
  domain?: string,
  path?: string,
  expires?: number,
  httpOnly?: boolean,
  secure?: boolean,
  sameSite?: 'Strict' | 'Lax' | 'None'
};
```

**Comment by liuxingbaoyu** [comment]
Check the `domain` and other parameters, maybe it will help.
```
export type SetNetworkCookieParam = {
  name: string,
  value: string,
  url?: string,
  domain?: string,
  path?: string,
  expires?: number,
  httpOnly?: boolean,
  secure?: boolean,
  sameSite?: 'Strict' | 'Lax' | 'None'
};
```

**Comment by neongreen** [comment]
Nevermind, apparently I was setting a cookie for `foo.com` and I should have been setting a cookie for `.foo.com`.
