### ISSUE TITLE
[Feature] Native Apps Mobile Automation

### ISSUE THREAD

**Issue by Agustin-DeLuca** [microsoft/playwright#13402]
I am aware that native apps have nothing to do with web apps, but, having worked with Selenium/Appium, I just discovered playwright and fell in love with it. It would be wonderful to have an alternative to Appium with all the things that Playwright has to offer.
I want to ask if it is planned to develop such a thing for Playwright or if it's only intended for web apps.

**Comment by mxschmitt** [comment]
Playwright has experimental integration with Android see here: https://playwright.dev/docs/api/class-android

This includes automating some of the UI elements. For iOS see the tracking issue: https://github.com/microsoft/playwright/issues/1122

As you said, Playwright focuses primarily on automating web applications, so for Android we recommend using Chrome/ium or WebViews.

**Comment by LeviticusMB** [comment]
https://github.com/microsoft/playwright/issues/1122#issuecomment-1094312892 might be of interest, even though it definitely does not provide "all the things that Playwright has to offer" ...?
