### ISSUE TITLE
[Question] Playwright HTML report - Missing trace and presence of allure-metadata.json

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#13419]
Hi, I have a bunch of questions.
Yesterday I run a 7 hour long single test to trace a possible bug in a web application. Once the test has finished, I wanted to open the playwright report I generated and inspect the trace. Unfortunately I see only this:

![image](https://user-images.githubusercontent.com/45291289/162384131-a2172f68-7366-4df6-bf4e-2f77e2b3e857.png)

and I got the trace:'on' on my test config. Infact, since I also use allure-report, I get a trace when I inspect the report but once I download it and try to load it I get this error:

![image](https://user-images.githubusercontent.com/45291289/162384396-2d5e071b-e970-4522-b2f0-d3674390b77c.png)

What is going on? Can you help me on this one? Also, why Am I seeing all that allure-metadata.json file in my playwright report? Never happened before :/ Thank you!

EDIT: I saw that the allure-metadata.json files contain attachment such as what the labels and tags I add to my allure report. Nevermind for that

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

**Comment by DvDream** [comment]
Not really unfortunately, the test I'm doing is really web-app specific. 
However, The same test today run for 2.30 hours and in this case the trace has been generated (1.60 GB), I could seen it in the HTML report but then in the trace viewer I got the following (after waiting for the trace to be loaded).

![image](https://user-images.githubusercontent.com/45291289/162964517-de3971ae-5082-4ce7-ab3c-48c9f9a9b25d.png)

Is it possible that for really long test and large traces there are problem on the trace generation/reading?

**Comment by aslushnikov** [comment]
> Is it possible that for really long test and large traces there are problem on the trace generation/reading?

Very much could be! We haven't experimented with opening 1.6GB traces, but I'd expect them to deal issues. I'd recommend against recording such large traces.
