### ISSUE TITLE
[Question]  TypeError: Cannot read property 'path' of undefined

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#13427]
Im trying to print the download file path but seeing this error ` TypeError: Cannot read property 'path' of undefined`

```js
const [ download ] = await Promise.all([
        await this.verify.clickOnElement(LandingPage.LandingPageNav.uploadWizardDownloadFiles(1))
      ]);
      const path = await download.path();
      console.log("Gaurav : " + path);
```

Can someone please help?

**Comment by gauravgandhi1315** [comment]
This works for me ` this.page.on('download', download => download.path().then(console.log));`

**Comment by mxschmitt** [comment]
Click does not return any value. So this is working as intended. I'd recommend to use TypeScript, which would have shown you that the method does not exist.

For further usage for downloads, see this guide: https://playwright.dev/docs/next/downloads
