### ISSUE TITLE
[Visual Regression Test]: Full Page screenshot misguided in release note

### ISSUE THREAD

**Issue by goyalshweta017** [microsoft/playwright#13420]
- Playwright Version: 1.20.2
- Operating System: Windows
- Node.js version: 16.14.0
- Browser: Chromium

I am working on regression Visual Testing for my product and plan to use the playwright for same. when i were running playwright test and adding expect(await page.screenshot()).toMatchSnapshot(), Its not taking the full page screenshot( not scrollable view). after going through the Playwright doc and recent release note - https://playwright.dev/docs/release-notes#highlights
It has asked to use 
expect(await page.screenshot()).toMatchSnapshot({
  fullPage: true, // take a full page screenshot
  maxDiffPixels: 27, // allow no more than 27 different pixels.
});
when i have used same,  code is not compiled as "Object literal may only specify known properties, and 'fullPage' does not exist in type 'ImageComparatorOptions & { name?: string | string[] | undefined; }'"

further investigation confirmed that ImageComparatorOptions does not have this property as FullPage.

Is this misguided in release note? how can we use playwright visual test with full screenshot?

**Code Snippet**
     expect(await page.screenshot()).toMatchSnapshot({
        fullPage: true, // take a full page screenshot
        maxDiffPixels: 27 // allow no more than 27 different pixels.
      });

`

**Comment by mxschmitt** [comment]
We fixed it his docs issue already, will go live in 1.21.
