### ISSUE TITLE
[BUG] getElementStates gives "strict mode violation" error without a reason with some selectors

### ISSUE THREAD

**Issue by ssallmen-pro** [microsoft/playwright#13432]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows
- Node.js version: v16.14.0
- Browser: Chrome
- Extra: Using Playwright via Robot Framework Browser Library (Python) v12.3.0

**Code Snippet**

Unfortunately I have not found a way to reproduce the error with any simpler solution, and the page I am getting this error on is company confidential and requires login.

**Describe the bug**

I am testing in Salesforce using Robot Framework with Browser Library, which utilizes Playwright. I contacted Browser Library developers but it is evident that the bug lies in Playwright. For evidence I am attaching [a snippet of Playwright debug level log](https://github.com/microsoft/playwright/files/8454097/playwright.log) and below I am explaining what I am trying to do in those steps that can be seen in the attached log.

1. Call to `getElement` with selector `div.isModal >> //label[@lightning-combobox_combobox][text()="Lead Source"]`. I get one element, just like it should be.
2. Call to `getElementStates` with exactly the same selector as in previous call to `getElement` to get the states of the element. Now, I am getting an error and wondering how is that possible when I have just called getElement, which should give the same error if there would be more than one element found with the selector. And there really are no more than one element with that selector on the page. Here is a short snippet of that error seen in the log:
```
locator.isVisible: Error: strict mode violation: "div.isModal >> xpath=//label[@lightning-combobox_combobox][text()="Lead Source"]" resolved to 2 elements:
    1) <label for="combobox-button-261" lightning-combobox_com…>…</label> aka playwright.$("text=*Lead Source")
    2) <label for="combobox-button-261" lightning-combobox_com…>…</label> aka playwright.$("text=*Lead Source")
```

3. Call to `getElementStates` with selector `//div[contains(@class, " isModal ")] >> //label[@lightning-combobox_combobox][text()="Lead Source"]`, which is essentially the same selector as the previous, but using xpath also in the first part of the chained selector. Naturally it is not exactly the same selector, but in this case it will match exactly the same element. That call is is successful and return the element statuses.

So, it looks like if I use a selector with both css and xpath part as a selector, it will not work, but gives the wrong error, but if I chain only only xpath selectors, it will give me the element statuses successfully.

**Comment by aslushnikov** [comment]
@ssallmen-pro This does look like a bug. However, it's impossible to fix unless we have a repro.

Any chance you can record a trace and attach it here?

**Comment by aslushnikov** [comment]
I'll close this for now since my triaging shift has ended; please re-file with a repro if/when you get one!
