### ISSUE TITLE
[Question] How do we execute tests in parallel across different projects

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13447]
I have a playwright config file that spans different 'groups' of tests in various projects 

example :
```
 projects: [
     {
      name: 'Chrome - Sanity Tests',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'Firefox - Sanity Tests',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'Safari - Sanity Tests',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
```
i would like to run the tests in all these projects simultaneously. i understand setting workers (workers =2 for example) runs the tests concurrently; is there a way to allow workers to pick up tests from each project please ?

for instance, if workers = 3 is specified, worker 1 should execute tests from project 1, worker 2 should pick tests from project 2 etc.

**Comment by mxschmitt** [comment]
A worker is always working on a specific file unless fully-parallel is enabled. In your case it depends how many files you have, if you have 3 files per project and 3 workers, then it will run the 3 files in parallel with all the browsers.

See here for more information: https://playwright.dev/docs/next/test-parallel

What is the reason you want to have this specific parallelism strategy?

**Comment by harir5** [comment]
Hi @mxschmitt,

We have several tests for different projects which we are clubbing together and grouping as a project. We would like to run all these tests in parallel in the pipeline so as to achieve wider coverage in terms of number of tests run. In the example above,  if i have a few tests for chrome, some for FF and some for Safari - we would ideally want all tests to run in parallel.

**Comment by aslushnikov** [comment]
@harir5 there's lots of ways to configure test parallelism:
- by default, tests in different files run in parallel; so one can split tests into multiple files to have "natural parallelism"
- use [`describe.parallel`](https://playwright.dev/docs/api/class-test#test-describe-parallel) to run tests in the same suite in parallel
- use [`describe.configure({mode: 'parallel'})`](https://playwright.dev/docs/api/class-test#test-describe-configure) to run all tests in file in parallel
- use [`--fully-parallel`](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) mode to run all tests across all files in parallel

I'd suggest either using the "natural parallelism" or "--fully-parallel" mode.

**Comment by noumanshahid12** [comment]
> @harir5 there's lots of ways to configure test parallelism:
> 
> * by default, tests in different files run in parallel; so one can split tests into multiple files to have "natural parallelism"
> * use [`describe.parallel`](https://playwright.dev/docs/api/class-test#test-describe-parallel) to run tests in the same suite in parallel
> * use [`describe.configure({mode: 'parallel'})`](https://playwright.dev/docs/api/class-test#test-describe-configure) to run all tests in file in parallel
> * use [`--fully-parallel`](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) mode to run all tests across all files in parallel
> 
> I'd suggest either using the "natural parallelism" or "--fully-parallel" mode.

How can I condition two locators one for Iphone and one for web browser((Chromium))?
Run parallel

**Comment by sushmithasv** [comment]
Does Playwright will read the configuration file for each worker?
