### ISSUE TITLE
[BUG] Playwright debug indicators interfere with snapshot screenshots

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#13445]
**Context:**
- Playwright Version:  `playwright@1.20.2`, `@playwright/test@1.19.2`
- Operating System: Windows
- Node.js version: 17.1.0
- Browser: Chromium
- Extra: 

```
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 48.63 GB / 63.75 GB
## Binaries:
 - Node: 17.1.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
```

**Code Snippet**

```javascript
expect(await page.screenshot()).toMatchSnapshot('autoscale-canvas-panned')
```

**Describe the bug**

It appears that while in debug mode, to verify visually that initial snapshot images will look as expected, playwright also captures visual debug indicators. For example, here is a snapshot that shows the red dot that playwright draws during debug mode:

![autoscale-canvas-prepan-expected](https://user-images.githubusercontent.com/297678/162551215-9ac44735-6892-462f-af1d-f549c4668f01.png)

**Comment by aslushnikov** [comment]
@trusktr I tried getting the following script:

```js
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.goto('https://google.com');
  await page.click('input');
  expect(await page.screenshot()).toMatchSnapshot();
});
```

and debugging it with

```bash
npx playwright test --debug
```

Yet, my screenshot was still without the red dot. How do I repro this then?
