### ISSUE TITLE
[Question] How to read complete URL

### ISSUE THREAD

**Issue by dchennaraidu** [microsoft/playwright#13458]
I'm trying to read `page.url()` in a Angular SPA application, but after click navigation to another route, `page.url()` is not updated

Need something like `window.location.pathname`

**Comment by mxschmitt** [comment]
Sometimes the click is asynchronous and it takes time to navigate to your specific route? For that we recommend `await expect(page).toHaveURL('**/foo.html')` for example, which automatically waits and asserts that you are on the specified URL. See [here](https://playwright.dev/docs/next/test-assertions) for more assertions.

Alternatively you can use `page.waitForURL()`.
