### ISSUE TITLE
[BUG] `page.pause()` doesn't work when running with nodejs debugger

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#13455]
**Context:**
## System:                                        
 - OS: Windows 10 10.0.19042
 - Memory: 3.00 GB / 15.78 GB
## Binaries:
 - Node: 16.9.1 - C:\Program Files\nodejs\node.EXE
 - npm: 7.24.1 - C:\Program Files\nodejs\npm.CMD  
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE    
## npmPackages:
 - playwright: ^1.20.2 => 1.20.2

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
import { test } from '@playwright/test'

test.only('foo', async ({ page }) => {
    await page.goto('https://google.com/')
    await page.pause()
})
```

**Describe the bug**

if you run the test with the nodejs debugger:

![image](https://user-images.githubusercontent.com/57028336/162596300-943a3ba5-c1f2-4e58-bebd-00095aa8be60.png)

it skips the `page.pause()`

perhaps this is intentional as you'd normally use breakpoints when running with the debugger? however sometimes i want to use `page.pause` to work around issues like #10897 and #11668

**Comment by mxschmitt** [comment]
The change itself is intentional, it was made recently, since having two debuggers attached, where you can step through is mostly not beneficial.

I'll assign it to Pavel, who made the change (currently ooo) - he might be able to assist if you tell us about your specific use-case.

**Comment by mxschmitt** [comment]
Ah was already answered here, so folding into https://github.com/microsoft/playwright/issues/13219#issuecomment-1088962864
