### ISSUE TITLE
[Question]How to pass parameters to the text selectors?

### ISSUE THREAD

**Issue by SanRak987** [microsoft/playwright#13453]
example:
async abc(cancelBtn:string)
{
await this.page.locator(text=cancelBtn).click
}

**Comment by Nav-2d** [comment]
You can do this: `await this.page.locator(`text=${cancelBtn}`).click();`

**Comment by SanRak987** [comment]
> You can do this: `` await this.page.locator(`text=${cancelBtn}`).click(); ``

does it work for (locator:has-text("cacelBtn")) as well, it did not seem to work for me

**Comment by mxschmitt** [comment]
See here how string templating is working in JavaScript: https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Template_literals

For further selector engines and examples see here: https://playwright.dev/docs/next/selectors

(We can't act on such issues without a clear question)
