### ISSUE TITLE
aoyagidiesel@grace.ocn.ne.jp

### ISSUE THREAD

**Issue by aoyagibisel** [microsoft/playwright#13459]
### Discussed in https://github.com/microsoft/playwright/discussions/13454

<div type='discussions-op-text'>

<sup>Originally posted by **Nav-2d** April 10, 2022</sup>
Hello,

I had one scenario: I have an element that is `enabled and attached to DOM` but not `visible`. So , to click it I have to scroll to the element using:
await page.evaluate((loc) => document.querySelector(loc)?.scrollIntoView(), loc);
I can't use `scrollIntoViewIfNeeded()` either since it depends on element to be visible. I was wondering is my above solution the best or I can use something else? 

Thanks!</div>

**Comment by aoyagibisel** [comment]
``

**Comment by mxschmitt** [comment]
This looks like opened by mistake.
