### ISSUE TITLE
CodeCoverage using Playwright Any tools

### ISSUE THREAD

**Issue by vijaymogali** [microsoft/playwright#13452]
Hi There,I got a request as below from one of my managers to do a CodeCoverage using Playwright for existing scripts for which they're using Clov... I got one link "https://github.com/mxschmitt/playwright-test-coverage" looking into that but wanted to check if I am doing the right thing...

" all we need is for Playwright to emit coverage reports in any format supported by Codecov: (https://docs.codecov.com/docs/supported-report-formats). Currently, we use lcov format using Cypress 
![CodeCove_Report](https://user-images.githubusercontent.com/96084092/162587784-4e871971-4c0b-4c47-898d-8fd305976688.png)
<https://docs.cypress.io/guides/tooling/code-coverage#E2E-and-unit-code-coverage>

There is no free replacement for _`Codecov`_. What they do is store all of our coverage reports in order to let us track coverage on our repos over time - that storing, aggregating, and serving of metrics analytics via a UI has real server costs for them that they pass on to us, and then we pay a premium over the raw costs for the analytics, ease of use, zero maintenance, etc. They also integrate with our GitHub account in order to post coverage diffs as comments in PRs.

`instanbul/nyc` is pretty much the gold standard and the only game in town for JS coverage reporting. That’s what Cypress uses for its front-end coverage instrumentation. This is pretty simple, you just call `nyc yarn` test instead of the `yarn` test. That instruments the code before the tests start. (you have to configure some things first, but mechanically that’s all there is to it)

`simplecov` is already in place for our rails backend coverage reporting. You just need to tell it to an instrument when the rails server is started. We already do this in branch_path/rails_helper.rb as(if ENV['CI'] || ENV['COVERAGE']).

Since it is controlled via an environment variable, you might even be able to just set that when you start the server for the tests COVERAGE=true rails server and have it “just work” as is.

the harder part here should be handing the back-end coverage reports back to playwright, since it is executing in a browser context. the way that cypress does this is by exposing an API endpoint, like /api/v1/test/__coverage__, which response to a GET request with the coverage report contents. So if you use a global after Each or afterAll hook to hit that endpoint, the tests themselves never have to worry about their own coverage. the test runner framework just handles it for you for all of your tests. "

Please let me know if you need any further information.

**Comment by vijaymogali** [comment]
Any guidance with this is highly appreciated.

**Comment by mxschmitt** [comment]
Playwright does not provide any coverage integration out of the box. Adding coverage does not require much boilerplate, thats what the https://github.com/mxschmitt/playwright-test-coverage example demonstrates. If your application already provides istanbul coverage, then this repo will automatically collect it and store it on the file system with the lcov format.

Have you tried it?

Seems like we can fold it into https://github.com/microsoft/playwright/issues/9208.

**Comment by vijaymogali** [comment]
Thanks, Max this is really helpful and Thanks a Lot . Closing this issue for now if needed will contact you.

**Comment by thaynarbo** [comment]
> Playwright does not provide any coverage integration out of the box. Adding coverage does not require much boilerplate, thats what the https://github.com/mxschmitt/playwright-test-coverage example demonstrates. If your application already provides istanbul coverage, then this repo will automatically collect it and store it on the file system with the lcov format.
> 
> Have you tried it?
> 
> Seems like we can fold it into #9208.

Helllo @mxschmitt , I implemented the lib on my project but my setup is a bit different. I already extend test because I have Page object models integrated with fixtures. In this case do you believe it matters the order I add the context property? I get 0 but I have plenty of tests
![image](https://github.com/user-attachments/assets/82abcce2-d80e-43f9-821d-0237b911c431)

**Comment by nishanthan9316** [comment]
how should do code coverage remix with react router project
with playwright...
Can anyone please share example codes

**Comment by soroushm** [comment]
> how should do code coverage remix with react router project with playwright... Can anyone please share example codes

playwright by default dosnt Collect per-test coverage you need an thirdparty setup to collect e2e covrage and aggregate it into an lcov report

try this pckage
https://soroush.tech/playwright-coverage
