### ISSUE TITLE
[Feature] Enable video and screenshot saving on global setup

### ISSUE THREAD

**Issue by Martin-Hogge** [microsoft/playwright#13468]
I have a configuration file where video and screenshot saving are retained on failure. In this config file I also set up a `globalSetup` file that will basically open the application and do some stuff in it before saving the `storageState.json` file.

I correctly have my video and screenshot when the failure happen on the test level but if the failure happen on `globalSetup` level then the video and the screenshot is not saved.

Is their a way to enable this feature for both test level and global setup level ?

Here is my current configuration file:
```ts
import { devices, PlaywrightTestConfig } from '@playwright/test';
import dotenv from 'dotenv';

// Read from default ".env" file.
dotenv.config();

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./src/test-definitions/global-setup'),
  reporter: [
    ['junit', { outputFile: 'test-result.xml' }]
  ],
  use: {
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    storageState: 'storageState.json',
    headless: process.env.HEADLESS === "true",
  },
  workers: 1, // Disable parallelism
  timeout: 90000, // 1min30 to run a single test.
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
};

export default config;
```

And my `global-setup` file starts with launching a chromium browser:
```ts
async function globalSetup(config: Config) {
  const browser = await chromium.launch({ headless: process.env.HEADLESS === "true" });
  const page = await browser.newPage();
  // Do stuff that can fail
}
```

Thank you.

**Comment by Martin-Hogge** [comment]
I actually managed to have a video of my global setup but this is recording in every scenario, failure or not. I think it would be great that either the `browser` created through `global-setup` take the default configuration or to have an option to configure it in the configuration file.

I'm sharing what I've done for those who are interested.
I didn't read the documentation enough but it's possible to start a video on the fly. See https://playwright.dev/docs/videos.

In my `global-setup.ts` script:

```ts
  const browser = await chromium.launch({ headless: process.env.HEADLESS === "true" });
  const context = await browser.newContext({ recordVideo: { dir: 'test-results/global-setup-video/' }});
  const page = await context.newPage();

  try {
    // Do stuff that can fail
  } catch (e) {
    // Close the browser in order to get the video.
    await browser.close();
    throw e;
  }

  // Finally close the browser in case of success.
  await browser.close();
```

**Comment by aslushnikov** [comment]
@Martin-Hogge so to re-iterate, it'd be nice to have a tracing & video support for `globalSetup` that launches browser to initialize storage state.

There's no support out-of-the-box for this, yet. Your approch is DIY and should work, though. I'll mark this as P3, we might improve it one day.

**Comment by johnjv** [comment]
having a similar issue as @Martin-Hogge and am also interested in seeing this feature

**Comment by clabough** [comment]
You can get screenshots and snapshots by using 

```   const browser = await chromium.launch({ headless: process.env.HEADLESS === "true" });
  const context = await browser.newContext({ recordVideo: { dir: 'test-results/global-setup-video/' }});
  const page = await context.newPage();

  try {
    await context.tracing.start({ screenshots: true, snapshots: true });

    // Do stuff that can fail

    // Finally close the browser in case of success.
    await browser.close();
  } catch (e) {
    await context.tracing.stop({
      path: './failed-setup-trace.zip',
    });
    // Close the browser in order to get the video.
    await browser.close();
    throw e;
  }
```

I haven't figured out how to do the same for video.

**Comment by tomoyachen** [comment]
> You can get screenshots and snapshots by using
> 
> ```
>   const context = await browser.newContext({ recordVideo: { dir: 'test-results/global-setup-video/' }});
>   const page = await context.newPage();
> 
>   try {
>     await context.tracing.start({ screenshots: true, snapshots: true });
> 
>     // Do stuff that can fail
> 
>     // Finally close the browser in case of success.
>     await browser.close();
>   } catch (e) {
>     await context.tracing.stop({
>       path: './failed-setup-trace.zip',
>     });
>     // Close the browser in order to get the video.
>     await browser.close();
>     throw e;
>   }
> ```
> 
> I haven't figured out how to do the same for video.

My guess is that more than 1 cases must be executed to complete the video recording.

**Comment by aslushnikov** [comment]
As of Playwright 1.31, the project dependencies feature is just a better "globalSetup" with fixtures, traces and screenshots. See https://playwright.dev/docs/auth for details!

**Comment by cbrenner04** [comment]
For anyone who ends up here, like me, and asks how the new auth setup paradigm helps in any way... it's that the setup is just being run as a test and that test is being set to a separate project that the other projects (and their tests) depend on. Should be pretty straightforward for most people to augment their code without changing much at all.
