### ISSUE TITLE
[BUG] `test.step(title, body)` actually returns `Promise`, not `void` like the documentation claims

### ISSUE THREAD

**Issue by dossy** [microsoft/playwright#13463]
**Context:**
- Playwright Version: 1.20

**Describe the bug**

The [documentation for `test.step(title, body)`](https://playwright.dev/docs/api/class-test#test-step) claims that this returns `void`, but it actually returns a `Promise` and should be `await'`ed on, otherwise the test case will end while the test step is still executing.

<img width="425" alt="image" src="https://user-images.githubusercontent.com/65378/162632316-3e0c48e4-d74a-474f-8f6a-5d690dba8ce9.png">

**Comment by dossy** [comment]
This isn't the first time I was tripped up by this when writing tests and scratching my head as to why the steps were executing in a funny order, and I kept believing the documentation to be correct, until I realized it wasn't.

**Comment by rwoll** [comment]
Thanks for catching this! Sorry for any inconvenience it may have caused! Will be fixed with #13464

**Comment by dossy** [comment]
@rwoll - Thanks for updating the docs.  Hopefully it'll keep me in the future from leaving off the `await` and then wondering why my tests are misbehaving.  :)

**Comment by rwoll** [comment]
@dossy There's an unofficial community ESLint plugin that can help out (for test.step and elsewhere): https://github.com/playwright-community/eslint-plugin-playwright#missing-playwright-await-
