### ISSUE TITLE
Can't connect to the database while doing an assertion

### ISSUE THREAD

**Issue by hager-yousri** [microsoft/playwright#13460]
- Playwright Version: [1.20.1]
- Operating System: [Windows]
- Node.js version: [16.13]
- Browser: [All]
- Use MSsql to connect to the database https://www.npmjs.com/package/mssql: [8.1.0]

**Code Snippet**
1- javascript file which contains database  details

```js
const sql = require('mssql');

const sqlConfig = {
  user: '',
  password: '',
  server: '', 
  database: '', // name of database
  options: {
    encrypt: true,
    trustServerCertificate: true,
  },
};

exports.DB = class DB {
  async connectDb(query) {
    try {
      await sql.connect(sqlConfig);
      await sql.query(query);
    } catch (err) {
      console.log(err);
    }
  }
};
```

2- test file which use database javascript file

```js
const { DB } = require('../../pages/db_connection');
const db = new DB();

// test case steps
//doing assertion like
expect(0).toEqual(0);
db.connectDb("select * from users");
```

**Describe the bug**

I use MSSQL to connect to the database and execute queries
The db connection and query execution work successfully as long as there is no assertion in the test case but once I put an assertion like the example above the connection to the database doesn't work and I don't get any error message

could you please clarify why this may work without assertion and doesn't work with assertion?
Is there a better way to connect to the database?

**Comment by mxschmitt** [comment]
Playwright Test runs inside Node.js so there are no limitations on what JavaScript you can run. Maybe you forgot to await the db.connectDb? Connecting to the DB is an async operation.

**Comment by hager-yousri** [comment]
oh it works thanks
