### ISSUE TITLE
[Question] It's not clear how to record videos

### ISSUE THREAD

**Issue by d-ryabtsev** [microsoft/playwright#13472]
I have battled this for a couple of days now and here are the issues I am facing.

It isn't immediately clear how to record videos when the test file is re-using the same context/page. Consider this test file:

```
let model = null

describe
---
beforeAll(() => {
  model = new Class(await getPage()) --- where get page returns a page from a new context
})

test('Test 1', () => {
 model.page.goto('a')
 expect(stuff)
})

test('Test 2', () => {
 model.page.goto('b')
 expect(stuff)
})

test('Test 1', () => {
 model.page.goto('c')
 expect(stuff)
})
```

I am unsure where to put await context.close() in this scenario? Whereever I put it, it seems that the videos that are being generated are corrupted. On top of that I get 5 videos even though I only have 3 test files. Some of the videos are fine.

Is it possible that I am running into this issue because I am collating 2 test files in 1? For example we want the tests to run in parallel but some of the files we want to group together. I am working around this issue by doing this

![image](https://user-images.githubusercontent.com/16368445/162770721-05a771c5-47ff-4797-874c-54f0724d5b20.png)

I could not find anything in the documentation about being able to run files sequentially without completely turning off parallelisation.

**Comment by d-ryabtsev** [comment]
Looks like my issue could be linked to https://github.com/microsoft/playwright/issues/7144

I must say this whole concept of having to use the same page/context per test is a massive limitation of this framework. Some single page applications take some time to load and there is no other choice but having to reuse the same page between tests otherwise you would be taking a hit on performance.

**Comment by aslushnikov** [comment]
> I could not find anything in the documentation about being able to run files sequentially without completely turning off parallelisation.

@d-ryabtsev You can run tests in serial using `describe.serial` - read more: https://playwright.dev/docs/next/test-retries#serial-mode

However, in this mode you won't have videos for tests. This is a known limitation - see https://github.com/microsoft/playwright/issues/9002

But you still get [traces](https://playwright.dev/docs/next/trace-viewer), and traces include videos, DOM snapshots, network, console, and much more. We'd recommend trying out tracing instead of videos.

**Comment by d-ryabtsev** [comment]
> > I could not find anything in the documentation about being able to run files sequentially without completely turning off parallelisation.
> 
> @d-ryabtsev You can run tests in serial using `describe.serial` - read more: https://playwright.dev/docs/next/test-retries#serial-mode
> 
> However, in this mode you won't have videos for tests. This is a known limitation - see #9002
> 
> But you still get [traces](https://playwright.dev/docs/next/trace-viewer), and traces include videos, DOM snapshots, network, console, and much more. We'd recommend trying out tracing instead of videos.

I am not sure that this serial mode achieves quite what I need. Does it not just run tests in a single file sequentially?

I have files `a.spec.js`, `b.spec.js` and `c.spec.js`. I would like to run files `a` and `b` one after the other (irrelevant what the order the tests inside of these files run in) and file `c` in parallel with `a`/`b`. Essentially some tests require grouping in such fashion because their database data setup would be changing the same SQL tables so you can't run them in parallel - the SQL and the tests will trip over each other. But in general I want to run all files in parallel.

**Comment by aslushnikov** [comment]
> I would like to run files a and b one after the other (irrelevant what the order the tests inside of these files run in) and file c in parallel with a/b

I'd recommend merging tests in file `a` and `b` together; tests in the same file run sequentially, and they'll be run in parallel with `c`.

Alternatively, you can do the following:

1. rename `a.spec.js` to `a.js` and `b.spec.js` to `b.js`
2. create file `group.spec.js` with the following content:
  ```js
  require('./a.js');
  require('./b.js');
  ```
3. keep `c.spec.js` as-is.

As a result, tests in `group.spec.js` will run one after another, and in parallel with `c.spec.js`.

**Comment by aslushnikov** [comment]
(closing as per above)
