### ISSUE TITLE
[playwright]: using expect to match array  return from allTextContent() method throws error

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#13477]
On Using  Expect to match array  return from allTextContent() method  ,but it throws error 

```
await expect(actual, customMessage).toEqual(expected)
```

Passing in argument of expect

**actual**: returning from locator.allTextContents()
**expected**:[value]

Error throwing 
     **- Expected  - 1
    + Received  + 1

      Array [
    -   "New Snippet",
    +   "New Snippet",
      ]**

Not sure what exactly the difference between Expected and Received

**Comment by aslushnikov** [comment]
@saurabh4888 there might be some special character that did not render yet is different. Can you share a snippet so that we can repro this locally?

**Comment by aslushnikov** [comment]
> what exactly required ,the script ?

@saurabh4888 Yep, something that I can run locally to see the issue and debug it.

**Comment by aslushnikov** [comment]
I'll close this for now since my triaging shift has finished; please re-file with a repro if/when you get one!
