### ISSUE TITLE
[Question] Playwright API Test - Bearer token

### ISSUE THREAD

**Issue by adam-syson** [microsoft/playwright#13473]
I am trying to convert an API Test from Postman to Playwright and am having an issue using the Bearer token.
I have attempted multiple different syntax without any luck, the GET call always results in a 401 error.  (The call works successfully in Postman).
My code:

```js
test("Get Something", async ({request}) => {
const _response = await request.get('https://_weblink_', {
headers: {
    'Authorization': `Bearer ${_token_}`,
    'Content-Type': 'application/json'
    }
});
expect(_response.status()).toBe(200)
console.log(await _response.json());
})
```

Any suggestions would be greatly appreciated.

**Comment by aslushnikov** [comment]
@adam-syson any chance you can dump headers that your test sends to the API endpoint in both Playwright Test and Postman? It might be that some headers are missing.

Also, if there's a repro that we can run locally - that'll help a lot!

**Comment by adam-syson** [comment]
@aslushnikov Thanks for the tip on the headers!  I was actually missing a Location Subdomain header, which I found in the debug console for Postman.  I've added this to my headers in Playwright and now the test is running successfully.  Thanks again for pointing me in the right direction.
