### ISSUE TITLE
[BUG] 'referer' set via 'extra_http_headers' and 'referer' set via `page.goto()` give different behavior

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright#13481]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Lubuntu 20.04
- Python version: 3.10
- Browser: Firefox

# Problem

The working way to set 'referer' is like `page.goto(url, referer=referer)`. Otherwise, if someone set 'referer' via 'extra_http_headers', then some redirection problems may occur.

This is bad:
```python
context = await browser.new_context(
    extra_http_headers={
        "referer": "https://google.com/"  # You may have problems with JavaScript and redirects
    }
)
page = await context.new_page()
await page.goto(url)
```

This is good:
```python
context = await browser.new_context()
page = await context.new_page()
await page.goto(url, referer="https://google.com/")  #  This will work fine
```

A real use case is that JavaScript check can not redirect the page further if 'referer' is via 'extra_http_headers', but the browser JavaScript check passes and redirects a page further to the website if the 'referer' was set in `page.goto()`.

**Comment by aslushnikov** [comment]
@AIGeneratedUsername so the action item would be to disable setting `referrer` header via extra http headers?

**Comment by AIGeneratedUsername** [comment]
> so what is the problem, exactly? 

I test it as a real user may access my website. This code waits for my website JavaScript protection check and redirects to the my website main page:
```python
await page.goto(url, referer="https://google.com/")
```
**Page A** _-- redirect -->_ **Page B**

---

And this code redirects forever in a loop the same protection page:
```python
context = await browser.new_context(
    extra_http_headers={
        "referer": "https://google.com/"  # You may have problems with JavaScript and redirects
    }
)
page = await context.new_page()
await page.goto(url)
```
**Page A** _-- redirect --> **Page A** _-- redirect --> **Page A** _-- redirect --> **Page A** ....

---

> so what is the problem, exactly? 


My guess is that setting the `referer` in a browser context makes redirecting to be broken. I do not know exactly. Maybe a website tries to set a different referer, but can not. Or something else goes wrong.

---

I can not share my website, so I think I will open this issue again when I will find another sample URL.
