### ISSUE TITLE
[BUG] Playwright doesn't work (gets stuck) when using yarn pnp and pnpEnableEsmLoader: true

### ISSUE THREAD

**Issue by lsdebianchi** [microsoft/playwright#13485]
**Context:**
- Playwright Version: 1.20.2
- Operating System: Mac OSX 11.6
- Node.js version: v14.17.0
- Browser: not relevant.
- Extra: [any specific details about your environment]
- Yarn: 3.2.0

Here a simple repo to easily reproduce the bug: https://github.com/lsdebianchi/BUG-pnp-playwright-esm

**Describe the bug:**

HOW TO REPORDUCE

On a barebone project (see repo linked above) while running `Node v14` and `Yarn v3` in `PNP` mode, and having `pnpEnableEsmLoader: true` in the  `.yarnrc.yml`, run any test with the command `yarn playwright test`.

WHAT HAPPENS

Playwright gets stuck forever at the first test. It neither fails nor passes. It remains stuck without printing any logs or erros in the terminal.

WHAT WAS EXPECTED

Playwright should manage to execute the test.

**NOTE**

This bug happens on node v14.7.0
Trying on node v16 or above the problem does not occur.

**Comment by aslushnikov** [comment]
> This bug happens on node v14.7.0
> Trying on node v16 or above the problem does not occur.

@lsdebianchi So it works on Node 16+, and active support for node.js 14 has ended a while ago, and Node 14 will be EOL in one year. Given these inputs, the issue doesn't look pressing enough to spend time investigating, so I'll close.

Thank you for filing though! It might help others.
