### ISSUE TITLE
[BUG] Error running xvfb-run in docker

### ISSUE THREAD

**Issue by jhanpiier** [microsoft/playwright#13483]
**Context:**
- Playwright Version: [^1.20.2]
- Operating System: [Ubuntu]
- Node.js version: [16]
- Docker version [20]
- Browser: [Chromium]
- Extra: [any specific details about your environment]

I try to run the command from docker xvfb-run --auto-servernum --server-num=1 node index.js, but it throws me the following error . . .Help me plss

<img width="910" alt="Captura de Pantalla 2022-04-11 a la(s) 13 40 07" src="https://user-images.githubusercontent.com/13308854/162798552-4c7cb3eb-abd6-44d9-aa2c-7748d89d22b9.png">

Code Docker 

```
FROM node:16

WORKDIR /app

COPY package*.json ./

RUN npm install

RUN npm install discord.js

RUN npm install fs

RUN npm install node-cron

RUN npm install playwright

RUN npm install -g supervisor

COPY . .

EXPOSE 4000

CMD [ "xvfb-run", "--auto-servernum", "--server-num=1", "node", "index.js" ]
```

**Comment by aslushnikov** [comment]
@jhanpiier two things right away:

- you did not install XVFB so i there's nothing to run
- you use `node:16` as a base layer, which is based on Debian Buster, which is not officially supported by Playwright. Please use `mcr.microsoft.com/playwright:v1.20-focal` instead. See [our docs](https://playwright.dev/docs/next/docker) for details.
