### ISSUE TITLE
[Question] Modify Context Options with launchPersistent 

### ISSUE THREAD

**Issue by ghost** [microsoft/playwright#1349]
Hi, 

When i use browserType.launchPersistent with userDataDir option, i cannot modify context options because it returns context object, In this case, how can I access the browser object for modify the context options?

My problem can be resolved shortly when the browser object is returned instead of the context object.

If the browser object is returned, I can use it as in my sample code

```javascript
const pw = require('playwright');
const os = require('os');
const path = require('path');
const fs = require('fs');

const userDataDir = `${os.tmpdir()}/testProfile-1/`;

(async () => {
  const browser = await pw.firefox.launchPersistent(userDataDir, {
    ignoreHTTPSErrors: true,
    headless: false,
  });

  const context = await browser.newContext({
    userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0',
    viewport: {
        width: 1920,
        height: 1040,
    },
    permissions: { 'https://www.google.com': ['geolocation'] }
  });

  const page = await context.newPage();

  await page.goto('https://www.google.com');
  await page.screenshot({ path: 'test.png' });
  await browser.close();
})();
```

**Comment by aslushnikov** [comment]
@eft24 is there a reason you use `launchPersistent` instead of `launch()`?

**Comment by eft24** [comment]
@aslushnikov 

I forgot to specify it in the code I shared above, but I have to specify the userDataDir parameter so that I can start with firefox preferences.

For example, when I need to use a proxy, I create a folder and write the firefox proxy preferences into the prefs.js and user.js file.

Just as you mentioned here: https://github.com/microsoft/playwright/issues/810#issuecomment-581580703

**Comment by Coriou** [comment]
Hey

Joining in here because I'd also like to know this. I've explained another use case related to manipulating the browser / defaultContext in https://github.com/microsoft/playwright/issues/651#issuecomment-599221259

**Comment by ngduc** [comment]
@eft24 with your code, I got this  error:

```(node:32313) UnhandledPromiseRejectionWarning: TypeError: browser.newContext is not a function
    at Object.<anonymous> (/Users/duc/Documents/downloads/_lab/jordan-plays-with-playwright/dist/index.js:20:35)```

also tried "launchPersistentContext" but it is undefined.
anybody got it working?

**Comment by eft24** [comment]
@ngduc 
Hi, you got this error because launchPersistentContext does not return the browser object.

@pavelfeldman 
Can you help us?

**Comment by pavelfeldman** [comment]
`launchPersistentContext` now supports the same set of options as `newContext`. See the [api reference](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchpersistentcontextuserdatadir-options--options)
