### ISSUE TITLE
[BUG] Screenshot fails (sometimes silently) in headed mode when screenshot is larger than 16384 pixels high

### ISSUE THREAD

**Issue by spartanatreyu** [microsoft/playwright#13496]
**Context:**

- `"@playwright/test": "^1.20.2"`

> ## System:
>  - OS: macOS 12.3.1
>  - Memory: 4.22 GB / 32.00 GB
> ## Binaries:
>  - Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
>  - npm: 8.3.0 - ~/.nvm/versions/node/v16.13.1/bin/npm
> ## Languages:
>  - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```typescript
import { test } from '@playwright/test';

test('broken screenshot example', async({page}) => {
	await page.goto('https://en.wikipedia.org/wiki/2021');
	await page.screenshot({ path: 'broken-screenshot-example.png', fullPage: true });
	
	// Note: test must be run in headed mode to see bug
});

```

**Headed mode screenshot bug:**

An issue occurs where large screenshots appear truncated and repeated/tiled. The tiling occurs every 16384 pixels.

That number (16384) is the positive half of a signed `short`. I'm guessing there's a buffer that's `short` long which is used to capture or output the image and it's overflowing back to the start.

Curiously, the issue **only** seems to occur while the test is running in [headed mode](https://playwright.dev/docs/debug#run-in-headed-mode).

I have used the page: <https://en.wikipedia.org/wiki/2021>, to show the tiling below.

---
(screenshot has been recompressed to fit under github's 10mb file upload limit, but image dimensions have remained untouched)

Broken result: 

<details>
<summary>Broken Result</summary>

![broken-screenshot-example](https://user-images.githubusercontent.com/3240456/162862505-6e173404-a594-4072-9907-96534325a3c6.jpg)

 </details>

**Comment by aslushnikov** [comment]
this is chromium issue - https://bugs.chromium.org/p/chromium/issues/detail?id=770769
Feel free to star that one.

I'll close in favor of upstream issue.
