### ISSUE TITLE
[BUG] Screenshot is not found when running on CI

### ISSUE THREAD

**Issue by haramchang** [microsoft/playwright#13505]
**Context:**
- Playwright Version: ^1.20.1
- Operating System: Mac
- Node.js version: v17.3.0.
- Browser: chromium
- Extra:

**Code Snippet**
```js
test.describe.parallel('Grand Touring Page looks correct', () => {

  test.beforeEach(async ({ page }) => {
    await page.goto('lucidmotors.com/air-grand-touring');
    await page.locator('#onetrust-accept-btn-handler').click();
  });

  test('Stats module', async ({ page }) => {
    await page.mouse.wheel(0, 5000);
    await page.waitForTimeout(5000);
    await expect(page.locator('p:has-text("Relentless range. Supercar speed. Lavish luxury. Lucid Air Grand Touring and Grand Touring Performance are here — pushing the limits of efficiency and exhilaration while surrounding you in style and comfort.")')).toBeVisible();
    expect(await page.locator('div[data-theme="black"] >> nth=0').screenshot()).toMatchSnapshot('AGT-stats.png', { threshold: 0.4 });
  });
});
```

Hi, when running the test locally everything is fine and the test passes but when running on CI it's looking for a snapshot with a different name. I get this error on CI: 
`Error: /builds/lucid.com/lucid-web-2e2-tests/playwright/US/pages/air-grand-touring/index.spec.mjs-snapshots/AGT-stats-chromium-linux.png is missing in snapshots.`

The snapshot name is AGT-stats-chromium-darwin.png but it's looking for this name instead: `AGT-stats-chromium-darwin.png`

**Comment by Nav-2d** [comment]
Related: https://github.com/microsoft/playwright/discussions/12729
