### ISSUE TITLE
[BUG] Unable to select the value in dropdown using Playwright in Java

### ISSUE THREAD

**Issue by harshith-rm** [microsoft/playwright#13502]
This is the DOM Structure :
```
<div .......>
    <label .......>
           "Text"
    <span ........>*<>
    </label>
    <Select>
```

Xpath used : `//span[text()='*']/parent::label[text()='Text']/parent::div/select`

Java Code Used to select the value : 
```java
public void selectFromDropdown(String xpath, String value) {
        Locator dropdown = page.locator(xpath);
        dropdown.selectOption(value);
}
```

Tried with below code too : 
```java
public void selectFromDropdown(String xpath, String value) {
        page.selectOption(xpath, value);
}
```
I am able to find the xpath, but not sure why playwright is not selecting the value from dropdown

**Comment by aslushnikov** [comment]
@harshith-rm It looks like there's no option with a given value. Try running the script with `DEBUG=pw:api` env variable to see more details.
