### ISSUE TITLE
[Question]: how to set webrtc policy 

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright#13518]
### Your question

Hello team,

How to set webrtc IP policy in playwright? , like force-webrtc-ip-handling-policy=default_public_interface_only , so far we have tried everything and we still cant figure out how to set the IP handling policy for webrtc, please let us know.

Thanks

**Comment by aslushnikov** [comment]
Dupe of https://github.com/microsoft/playwright/issues/13516
