### ISSUE TITLE
[Question] Selecting an item from a dropdown using partial text

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13514]
I have a select dropdown in my application which has this particular layout : 
```
<select>
<option value='1'>Order Number : 1234 (purchased on 10/01/2022)</option>
<option value='2'>Order Number : 4567 (purchased on 02/03/2022)</option>
</select>
```
I would like to select an element based on partial text like so:
```
const dropdown = await page.locator('//select');
await dropdown.click();
const optionToSelect = await dropdown.locator('//option[contains(text(),'4567')]);
await optionToSelect.click();
```

this seems to not be working. i get a console message stating that the option element is hidden.

is there a simpler way to find an item by partial text please ? 

Please note : the value attributes have dynamic strings and the _option label_  is not static as well(except for the order number within it).

**Comment by harir5** [comment]
Additionally, if the element in question were not a select but an angular form control like <mat-select> how would one go about selecting an option from the element please.

**Comment by aslushnikov** [comment]
@harir5 so you can do this in 2 steps.

1. Get an option value
2. Use [`locator.selectOption`](https://playwright.dev/docs/api/class-locator#locator-select-option) API to select by text content.

Overall, the following snippet worked for me:

```js
import { chromium } from '@playwright/test';

const browser = await chromium.launch({
  headless: false,
});
const page = await browser.newPage();
await page.setContent(`
  <select>
    <option value='1'>Order Number : 1234 (purchased on 10/01/2022)</option>
    <option value='2'>Order Number : 4567 (purchased on 02/03/2022)</option>
  </select>
`);

// Get option text that we want to select. You can use xpath as well, but this is probably
// more readable!
const optionToSelect = await page.locator('option', { hasText: '4567' }).textContent();
// Use option text to select
await page.locator('select').selectOption({ label: optionToSelect });
```

**Comment by harir5** [comment]
@aslushnikov - thank you very much ! it worked ! :)

**Comment by harir5** [comment]
@aslushnikov  - with regards to the element not being a html select but something like a <mat-select>, how would this work pls ?

**Comment by aslushnikov** [comment]
These are select-like widgets, you can automate them exactly the same way a user would do:
- click the widget, using `locator.click`
- then click the option you want to select, using `locator.click`
