### ISSUE TITLE
[BUG] ESM: imports don't work [ERR_MODULE_NOT_FOUND] and [ERR_UNSUPPORTED_DIR_IMPORT]

### ISSUE THREAD

**Issue by ebeloded** [microsoft/playwright#13515]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Mac
- Node.js version: 16
- New empty project created with `create-playwright`
- set type="module" in package.json

**Code Snippet**

```typescript
// import from ./file.ts
import { b } from './file' // [ERR_MODULE_NOT_FOUND]
// import from a folder/index.ts
import { a } from './folder' // [ERR_UNSUPPORTED_DIR_IMPORT]
```

**Describe the bug**

In ESM project (TypeScript) imports don't work

Reproduction repo: https://github.com/ebeloded/playwright-13515

**Comment by dgozman** [comment]
@ebeloded You should either `import { b } from './file.ts'` or `import { b } from './file.js'`. Refer to [this comment](https://github.com/microsoft/playwright/issues/13078#issuecomment-1082271101) for more details. Let us know whether this works for you.
