### ISSUE TITLE
[Question] How to set webrtc IP policy in playwright?

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright#13516]
Hello team,

How to set webrtc IP policy in playwright? , like force-webrtc-ip-handling-policy=default_public_interface_only , so far we have tried everything and we still cant figure out how to set the IP handling policy for webrtc, please let us know.

Thanks

**Comment by ahmwai** [comment]
Hello @aslushnikov 

No it's not working through the command line, usually, such a ip policy will work only if we set it in Chrome user preferences.

so can we do something for this?, as the webrtc leaking the IP

**Comment by aslushnikov** [comment]
> No it's not working through the command line, usually, such a ip policy will work only if we set it in Chrome user preferences.

@ahmwai That's surprising! We don't have much experience with WebRTC testing, so we can recommend much. Sorry!
