### ISSUE TITLE
[BUG] Custom playwright reporter error output adds control characters & colour, no way to disable.

### ISSUE THREAD

**Issue by add1ct3dd** [microsoft/playwright#13522]
**Context:**
- Playwright Version: 1.20.0
- Operating System:  Windows
- Node.js version: 14.18
- Browser: All
- Extra: n/a

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```js
// my-awesome-reporter.ts
import { Reporter } from '@playwright/test/reporter';

class MyReporter implements Reporter {
  onBegin(config, suite) {
    console.log(`Starting the run with ${suite.allTests().length} tests`);
  }

  onTestBegin(test) {
    console.log(`Starting test ${test.title}`);
  }

  onTestEnd(test, result) {
    console.log(`Finished test ${test.title}: ${result.status}`);
    // Both of these have control characters and colour codes in, with seemingly no way to disable them.
    if (result.status === 'failed') {
        console.log(result.error?.message);
        console.log(result.error?.stack);
    }
  }

  onEnd(result) {
    console.log(`Finished the run: ${result.status}`);
  }
}
export default MyReporter;
```

As above, a custom reporter seems to have control codes and colours forced within the output of the error items (this is the only output we use as we're reporting failures to testrail, and obviously passes we dont need the stack), but we're forced to strip out the control codes and colours from all of the messages. I tried to use 'printsToStdio' which I thought would maybe help, but with this set to true or false it makes no difference, in my eyes this is either a bug or a feature that requires the ability to turn off this formatting.

**Comment by aslushnikov** [comment]
@add1ct3dd this happens to come from the `expect` library that Playwright Test uses. It respects the `FORCE_COLOR` env variable, so you can disable colors via the `FORCE_COLOR=false` env variable.

You can actually bake it in the reporter:

```js
// my-awesome-reporter.ts
import { Reporter } from '@playwright/test/reporter';

process.env.FORCE_COLOR = 'false';

// ...
```

**Comment by add1ct3dd** [comment]
@[aslushnikov](https://github.com/aslushnikov) thanks for the reply, that will disable color for all reporting though right, not just this? The console color is useful, just not in the custom reporter :)

**Comment by aslushnikov** [comment]
> @[aslushnikov](https://github.com/aslushnikov) thanks for the reply, that will disable color for all reporting though right, not just this?

It will disable colors in the test runner process only. You mentioned you don't use any other reporters, so I guess it should be fine?

**Comment by add1ct3dd** [comment]
@[aslushnikov](https://github.com/aslushnikov) we use multiple reporters unfortunately, all of the others are the standard built-in ones :)

**Comment by aslushnikov** [comment]
@add1ct3dd Oh well. In this case, I'd recommend a crude solution to strip-out ANSI from the `result.error` fields.

```js
const ansiRegex = new RegExp('[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[-a-zA-Z\\d\\/#&.:=?%@~_]*)*)?\\u0007)|(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PR-TZcf-ntqry=><~]))', 'g');
export function stripAnsi(str: string): string {
  return str.replace(ansiRegex, '');
}
```

and usage later:

```js
  onTestEnd(test, result) {
    console.log(`Finished test ${test.title}: ${result.status}`);
    // Both of these have control characters and colour codes in, with seemingly no way to disable them.
    if (result.status === 'failed') {
        console.log(stripAnsi(result.error?.message ?? ''));
        console.log(stripAnsi(result.error?.stack ?? ''));
    }
  }
```

**Comment by aslushnikov** [comment]
(closing as per above)
