### ISSUE TITLE
[Question] electron app launch with executablePath timeout, but app already launched

### ISSUE THREAD

**Issue by monica-xu** [microsoft/playwright#13524]
**Context:**
- Playwright Version: 1.16.3
- Operating System: Windows
- Node.js version:14
- Browser: Electron

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

Before({ timeout: 3000000 }, async function(this: World) {
    console.log('before ');
    electronApp = await electron.launch({ args: [path.join(__dirname, '../../../../dist/apps/offline-tool/main.js')], executablePath: path.join(__dirname, '../../../../dist/executables/offline-tool') });
    console.log('after ');
    offlineToolFirstWindow = await electronApp.firstWindow();
});
```
```
get error 
  Scenario: check available
before
    × failed
      electron.launch: Timeout 30000ms exceeded.
          at World.<anonymous> (C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:54:65)
          at step (C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:33:23)
          at Object.next (C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:14:53)
          at C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:8:71
          at __awaiter (C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:4:12)
          at World.<anonymous> (C:\work\CUwebem\trunk\webem\apps\vcu-offline-e2e\src\supports\hooks.ts:49:12)
```
**Describe the bug**

our team need to test electronApp.exe by playwright, but use 
`electronApp = await electron.launch({ args: [path.join(__dirname, '../../../../dist/apps/offline-tool/main.js')]})` will test pass, but when use  `electronApp = await electron.launch({ executablePath: path.join(__dirname, '../../../../dist/executables/offline-tool') })` to test offline-tool.exe will timeout with actually already launched the exe

**Comment by lswnsn** [comment]
@aslushnikov what's this progress now?

**Comment by dan-cooke** [comment]
Same thing happens when specifying `recordVideo` option

**Comment by RajeshKumarMahto** [comment]
What is the update on above?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
