### ISSUE TITLE
[Feature] Add timeout for screenshot comparison

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13526]
Seems that the matchSnapshot feature is failing when the picture is not fully rendered, it would be nice to include a timeout so PW can keep comparing the snapshot for a specific time before it fails it 

```
        test('search header is loading properly IT lang', async ({ page, browserName, publicSearch }) => {
            await page.goto(path.it.zurichCity, { waitUntil: "load" })
            expect(await publicSearch.headerScreenshot()).toMatchSnapshot(`${browserName}-header-IT.png`);
        });
```

**Comment by aslushnikov** [comment]
Note to self: this will be addressed with `toHaveScreenshot()` API
