### ISSUE TITLE
[BUG] chrome.runtime is undefined when testing chrome extension

### ISSUE THREAD

**Issue by josteph** [microsoft/playwright#13529]
**Context:**
- Playwright Version: 1.20.2
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: Chromium (Headless mode)

**Code Snippet**

```typescript
import { BrowserContext, chromium, Page } from 'playwright';

const setup = async () => {
  const browser = await chromium.launch({
     args: [`--disable-extensions-except=${pathToExtension}`, `--load-extension=${pathToExtension}`],

     // Extensions only work in Chrome / Chromium in non-headless mode.
     headless: false,
  });

  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goTo('https://www.google.com');

  return [browser, page];
};

let browser: BrowserContext
let page: Page

test.beforeAll(async () => {
  [browser, page] = await setup()
})

test.afterAll(async () => {
  if (browser) {
    await browser.close()
  }
})

test('hello world', async () => {
  // this button will trigger a function that calls `chrome.runtime.sendMessage`
  await page.locator('text=Trigger').click()
});
```

**Describe the bug**

<img width="1277" alt="Screen Shot 2022-04-13 at 17 59 19" src="https://user-images.githubusercontent.com/13672022/163166340-376c443d-bcce-4892-bacf-e6eb8ba0c66e.png">

It seems the `chrome.runtime` will not be present unless a new tab is opened **manually**. 

https://user-images.githubusercontent.com/13672022/163166378-f06833c0-98c7-4edc-ad31-8d9e7978db6d.mov

Also, if a new tab opened due to `page` event called by `window.open('https://www.google.com', '_blank')`, the `chrome.runtime` will also be `undefined` too.

**Comment by josteph** [comment]
For now I can trigger the reload for workaround:

```
await Promise.all([
    page.waitForURL(guideUrl, {
      waitUntil: 'networkidle'
    }),

    // Trigger reload as workaround
    page.reload({
      waitUntil: 'networkidle'
    })
])
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the bugs based on the upvotes, recency and our ability to act. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by derevnjuk** [comment]
@pavelfeldman I'm still encountering the same issue, even using v1.45.3 and Chrome v127. Any ideas why it happens? Using `Page.reload` is not an option.

**Comment by josteph** [comment]
Closing an issue using vote numbers as excuse does not make the community any better, it's similar to rejecting public's opinion. Considering that the issue was closed without any effort to reproduce while the steps are clearly stated in the issue description.
