### ISSUE TITLE
[BUG] npm init playwright fails

### ISSUE THREAD

**Issue by einarpersson** [microsoft/playwright#13533]
Hi! I am new here. Trying to get started with Playwright in one of my projects. 

**Context:**
- Playwright Version: 1.21.0
- Operating System: Ubuntu 20.04.4 LTS running under WSL2, Windows 10 Pro, 21H2, 19044.1586
- Node.js version: v16.13.1
- Browser: All
- Extra: 

**Code Snippet**

```
npm init playwright
```

**Describe the bug**

```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libegl-mesa0 : Depends: libgbm1 (= 21.2.6-0ubuntu0.1~20.04.1) but 21.2.6-0ubuntu0.1~20.04.2 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
Failed to install browsers
Error: Installation process exited with code: 100
Error: Command failed: npx playwright install --with-deps
    at checkExecSyncError (node:child_process:826:11)
    at execSync (node:child_process:900:15)
    at executeCommands (/home/einar/.npm/_npx/d40a10098bccdd29/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/home/einar/.npm/_npx/d40a10098bccdd29/node_modules/create-playwright/lib/index.js:4593:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/einar/.npm/_npx/d40a10098bccdd29/node_modules/create-playwright/lib/index.js:4770:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 9825,
  stdout: null,
  stderr: null
}
npm ERR! code 1
```

Where to go from here? Am I doing something wrong? Is this a common error? If so, please add to docs / getting started...

**Comment by aslushnikov** [comment]
@einarpersson we don't officially support running on WSL2 at the moment, so YMMV there. Can you try installing Playwright with powershell / cmd?

**Comment by einarpersson** [comment]
I just ran Playwright in WSL2 successfully in another context (using the `npm init svelte`) so at least **that** works. Worth mentioning that I have previously set up [VcXSrv](https://sourceforge.net/projects/vcxsrv/) to be able to use Cypress and Puppeteer in WSL2 (although looking forward to WSLg so I can skip that step)

So it seems it is rather **create-playwright** (`npm init playwright`) that does not support WSL2, rather than Playwright itself.

--
Switching dev environment completely to Powershell-land is not an option. WSL2 is my dev environment.

**Comment by einarpersson** [comment]
Also if you indeed for now not support WSL2 that should be clarified in the docs, since then I'd would have seen that immediately and not bothered. But I hope that you'll support WSL2 since that is a great solution from Microsoft (if we now only could get [WSLg support in Windows 10](https://github.com/microsoft/wslg/issues/347)...)

![image](https://user-images.githubusercontent.com/6043691/163214509-c908cc00-3123-4520-9c43-486aa1edb748.png)

**Comment by einarpersson** [comment]
Alright. I cleaned my apt cache, ran `apt update` and `apt upgrade`. Then I run `npm init playwright@latest` and after that `sudo npx playwright install-deps`.

Now it works! 🎉 

**Detail:** running `npx playwright show-report` does not work out of the box, but if I change the url to localhost it does. Probably something wsl2-related but nvm. 

Closing. Thanks for your response(s)
