### ISSUE TITLE
[REGRESSION]: Pull request #12877 prevents the library from being used on any linux distro that is not Ubuntu

### ISSUE THREAD

**Issue by vladfrangu** [microsoft/playwright#13530]
**Context:**
- GOOD Playwright Version: < 1.21.0 (1.20.2, etc)
- BAD Playwright Version: 1.21.0
- Operating System: Linux
- Extra: while we are using Docker images based on buster slim, this is applicable to any Linux distro that isn't ubuntu based (debian, possibly arch too)

**Code Snippet**

Run `npx playwright install-deps chrome` in a non-ubuntu environment (debian for instance)

**Describe the bug**

https://github.com/microsoft/playwright/pull/12877 was merged in order to "solve" issues related to users of Debian that couldn't install the required dependencies due to missing packages (usually fonts which can be solved by including the debian non-free source list), however this prevents any users of a Linux distro that is not ubuntu based from using the library.

I believe the PR should be reverted or changed to emit an actual warning instead of a hard error, or a way to ignore the check should be added, as artificially limiting the library just for Ubuntu/Linux Mint users doesn't sound right.

**Comment by aslushnikov** [comment]
@vladfrangu first of all, the `npx playwright install-deps chrome` would only install a bunch of fonts & xvfb on the machine. Is this a desired behavior?

**Comment by aslushnikov** [comment]
@vladfrangu let me see. Taking `debian:buster-slim` and installing node.js + playwright@1.20 inside:

```bash
aslushnikov:~$ docker run --rm -it debian:buster-slim /bin/bash
root@a0c33bfb83b7:/# apt-get update && apt-get install -y curl
root@a0c33bfb83b7:/# curl -fsSL https://deb.nodesource.com/setup_17.x | bash -
root@a0c33bfb83b7:/# apt-get install -y nodejs
root@a0c33bfb83b7:/# cd
root@a0c33bfb83b7:~# npm init -y && npm i @playwright/test@1.20.0
```

Dry-run prints the command that Playwright would run. Here's what it prints for `npx playwright install-deps chrome`:

```bash
root@a0c33bfb83b7:~# npx playwright install-deps chrome --dry-run
sh -c "apt-get update&& apt-get install -y --no-install-recommends xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-liberation fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family"
```

These are only fonts and XVFB. If you were to isntall dependencies for **chromium** instead, you'll get a very different list:

```bash
root@a0c33bfb83b7:~# npx playwright install-deps chromium --dry-run
sh -c "apt-get update&& apt-get install -y --no-install-recommends fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family"
```

--- 

Now, neither of this commands work for me in Debian Buster.

This is what happens for `chrome`:

```bash
root@a0c33bfb83b7:~# npx playwright install-deps chrome
Installing Ubuntu dependencies...
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 https://deb.nodesource.com/node_17.x buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate
Failed to install browser dependencies
Error: Installation process exited with code: 100
```

And here's for `chromium`: 

```bash
root@a0c33bfb83b7:~# npx playwright install-deps chromium
Installing Ubuntu dependencies...
Hit:1 http://security.debian.org/debian-security buster/updates InRelease
Hit:2 http://deb.debian.org/debian buster InRelease
Hit:3 http://deb.debian.org/debian buster-updates InRelease
Hit:4 https://deb.nodesource.com/node_17.x buster InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate
Failed to install browser dependencies
Error: Installation process exited with code: 100
```

So how come it was working for you before? Am I missing something?

**Comment by vladfrangu** [comment]
Here's our dockerfile (I forgot to add this in the initial report and also mention the fact its node's buster-slim) https://github.com/apify/apify-actor-docker/blob/master/node-playwright-chrome/Dockerfile

Before #12877 all of our images built fine with the `npx playwright install-deps` command, and now they don't. I'm also surprised you didn't get the error thrown when running the command... Could it be a node image difference?

**Comment by aslushnikov** [comment]
> I'm also surprised you didn't get the error thrown when running the command... Could it be a node image difference?

@vladfrangu hah, I explicitly installed 1.20 where we didn't guard against non-ubuntu :)

> Here's our dockerfile (I forgot to add this in the initial report and also mention the fact its node's buster-slim) https://github.com/apify/apify-actor-docker/blob/master/node-playwright-chrome/Dockerfile

Sweet, let me play with it!

**Comment by aslushnikov** [comment]
So this is a debian with an extra sourceList:

```
echo "deb http://ftp.us.debian.org/debian buster main non-free" >> /etc/apt/sources.list.d/fonts.list
```

This one adds the missing `ttf-ubuntu-font-family` font. Besides this font, all other dependencies are installable for both Chromium & Firefox; both browsers also seem to be functioning well.

**Comment by aslushnikov** [comment]
@vladfrangu revert has landed; we'll publish a 1.21.1 with the revert by the end of the week. For now, you can use

```bash
npx playwright@1.20 install-deps chrome chromium
```

as a work-around.

Thanks for the heads-up!

**Comment by knaitas** [comment]
Still receiving this in 1.21.0:

image: ubuntu:latest

```
$ npx playwright install-deps
npm WARN exec The following package was not found and will be installed: playwright
Installing Ubuntu dependencies...
Hit:1 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:2 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont
E: Package 'ttf-unifont' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browser dependencies
```

**Comment by knaitas** [comment]
:facepalm: totally forgot ubuntu released 22 recently... Thanks!!

**Comment by david-engelmann** [comment]
this seems to just have started happening mainly around "E: Package 'xfonts-cyrillic' has no installation candidate"

**Comment by aslushnikov** [comment]
@david-engelmann please file a new issue with details to help us reproduce & debug.

**Comment by david-engelmann** [comment]
I'm not sure if this the right repo, but this issue seemed relevant to it. basically google-chrome is failing to install

**Comment by alex-sukhanov-mtv** [comment]
@david-engelmann @aslushnikov 

we got this issue a few hours ago. Was the new issue created?

**Comment by maquchizi** [comment]
I also just started seeing this for a bunch of fonts. Here's the relevant output:
```
#19 0.556 Installing dependencies...
#19 0.592 Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
#19 0.600 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
#19 0.600 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#19 0.656 Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
#19 0.757 Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [21.8 kB]
#19 1.761 Fetched 9173 kB in 1s (7766 kB/s)
#19 1.761 Reading package lists...
#19 2.286 Reading package lists...
#19 2.298 Building dependency tree...
#19 2.400 Reading state information...
#19 2.404 Package ttf-ubuntu-font-family is not available, but is referred to by another package.
#19 2.404 This may mean that the package is missing, has been obsoleted, or
#19 2.404 is only available from another source
#19 2.404 
#19 2.404 Package ttf-unifont is not available, but is referred to by another package.
#19 2.404 This may mean that the package is missing, has been obsoleted, or
#19 2.404 is only available from another source
#19 2.404 However the following packages replace it:
#19 2.404   fonts-unifont
#19 2.404 
#19 2.404 Package xfonts-cyrillic is not available, but is referred to by another package.
#19 2.404 This may mean that the package is missing, has been obsoleted, or
#19 2.404 is only available from another source
#19 2.404 
#19 2.406 E: Package 'ttf-unifont' has no installation candidate
#19 2.406 E: Package 'xfonts-cyrillic' has no installation candidate
#19 2.406 E: Package 'ttf-ubuntu-font-family' has no installation candidate
#19 2.407 Failed to install browser dependencies
#19 2.407 Error: Installation process exited with code: 100
```
Looking for workarounds...

**Comment by Nyaaa** [comment]
The repo above helps with chromium, but webkit cannot be installed:

`#10 16.20 E: Unable to locate package libicu66
#10 16.20 E: Package 'libjpeg-turbo8' has no installation candidate
#10 16.20 E: Unable to locate package libvpx6`

**Comment by david-engelmann** [comment]
I was able to remove xfonts-cyrillic from my install list and the new error message included the new packages I needed to include to build chrome

**Comment by stefaneg** [comment]
Encountering this issue building from the official node:18 image, which I would think is an image in widespread use.

**Comment by david-engelmann** [comment]
> Encountering this issue building from the official node:18 image, which I would think is an image in widespread use. 
> 

`FROM buildpack-deps:bookworm` looks like the update to bookworm caused the issue
