### ISSUE TITLE
[Question] - `fullyParallel` is significantly than 1 worker (164 tests)

### ISSUE THREAD

**Issue by cliffordfajardo** [microsoft/playwright#13532]
Hi Playwright team,

I wanted to share a real production results from our playwright test suite;
Currently we're observering that 1 worker is in most cases significantly faster than multiple workers (with `fullyParallel:true`  - https://github.com/remix-run/remix/pull/2772
  
  
## Case Study 1: Github Actions workflow inside `remix/run` repo (164 tests)
**Test 1  `fullyParallel: true, workers:2`:**
Result: 72s for integration test

**Test 2  `fullyParallel: false, workers:1`:**
Result: 73s for integration test

![CleanShot 2022-04-13 at 06 42 34@2x](https://user-images.githubusercontent.com/6743796/163194261-670cd5c0-d086-4a03-8af6-927f547c2cbd.png)

![CleanShot 2022-04-13 at 06 48 03@2x](https://user-images.githubusercontent.com/6743796/163195195-722e1b5e-0669-46b8-93b8-30e3461c7a24.png)

  
 Given that this feature was relatively new & added in the release 2 weeks ago, i thought maybe it could be a bug

**Questions(s)**
- is there "sweet spot" for the number of tests before the `fullyParallel` option show noticeable gains or over 1 worker? 
- this is our playwright config file: https://github.com/remix-run/remix/blob/b4a0afa3fafd7c54ad098fcb9cd49efce1685c0d/integration/playwright.config.ts

Maybe it could be the way are tests are setup that are not effective?
We tried to split everything across separate individual files:
 https://github.com/remix-run/remix/tree/b4a0afa3fafd7c54ad098fcb9cd49efce1685c0d/integration
 
 
<img  height="600" alt="CleanShot 2022-04-13 at 06 59 47@2x" src="https://user-images.githubusercontent.com/6743796/163197479-3621c59b-eccb-4e7f-8f02-a78b2b1a4e2b.png">

## Case Study 2: Github Actions workflow with Apple M1 Max Laptop
**Test 1  `fullyParallel: false, workers:1`:**
Result: 19s

**Test 2  `fullyParallel: false, workers:5`:**
Result: 37s
![image](https://user-images.githubusercontent.com/6743796/163198726-159694de-17ce-45d1-8a85-dc10735a589a.png)

## Case Study 3: Github Actions workflow with Apple Intel laptop (2019)
**Test 1  `fullyParallel: false, workers:1`:**
- Result: 27s (1st run) && 34s (2nd run)

**Test 2  `fullyParallel: true, workers:8`:**
Result: 1m (1st run) && 1m (2nd run)

**Comment by cliffordfajardo** [comment]
> > Test 1 fullyParallel: true, workers:1:
> > Result: 19s
> > Test 2 fullyParallel: false, workers:5:
> > Result: 37s
> 
> @cliffordfajardo I wonder how come you have fully-parallel enabled with just 1 worker? Is this a typo in your description or an actual behavior?
> 
> Besides that, running tests in parallel makes sense if you have lots of CPUs. On my M1 Max, running fully-parallel speeds up things considerably; running on Github Actions though not so much since they have just 2 vCPUs available.

Whoops typo, when there is only 1 worker `fullyParallel` doesnt come into play; updating description ^^

**Comment by aslushnikov** [comment]
> If anyone else stumbled upon this message, consider cloning the remix repository 🙏
The code in question lives in the dev branch of the remix repository: https://github.com/remix-run

@cliffordfajardo thanks, I cloned. The reason is that `--fully-parallel` results in the `createFixture` function being called multiple times. You can think of it as if each test is run in its out process, so they run `beforeAll` multiple times. (in reality, the scheduler is more clever than this, but this might be a nice model).

As a rule of thumb, the `--fully-parallel` mode works well if you don't have any heavy `beforeAll` steps; otherwise, the defaults are working way better! That's why we didn't roll `--fully-parallel` by default for everybody.

**Comment by aslushnikov** [comment]
Also, note that by default Playwright runs tests in different files in parallel. This way `beforeAll` hooks can be efficiently shared. 

With this, I'll close this :) feel free to file more questions / issues!
