### ISSUE TITLE
[BUG] Playwright ignores proxy settings when running through playwright runner in gitlab CI

### ISSUE THREAD

**Issue by goldenox777** [microsoft/playwright#13543]
Hello, we've been working for a couple of months with playwright and must say you guys have done such a great job.
Everything has been going well until we tried setting up playwright to run in our gitlab CI.
I really do hope someone is able to give us a direction / fix as the idea of rewriting all this work is just horrible.

Thank you and please let me know if there's any other info I can provide.

**Context:**
- Playwright Version: 1.20.0
- Operating System: gitlab-runner 14.8.2
- Node.js version: v16.13.0
- Browser: Chromium, Firefox
- Extra: using playwright image "mcr.microsoft.com/playwright:v1.20.0"

So far, we have been building our framework with POM and running the tests with the playwright runner.
This is how a test looks like:
![image](https://user-images.githubusercontent.com/36566995/163253385-128566d0-b9ac-4457-8038-6016da5b1e94.png)

Then, our test continues like this:
![image](https://user-images.githubusercontent.com/36566995/163251987-92fa05f0-97d1-4d66-9f48-d981017b675e.png)

In playwright.config.ts we generally have the default settings which came out of the box, the only thing we added was different settings for the different projects
![image](https://user-images.githubusercontent.com/36566995/163252400-7b50c2a6-23b1-4fad-b2d7-b758452936f3.png)

When pushing this to git, the CI starts doing its job

- it pulls the image that we specified

<img width="872" alt="image" src="https://user-images.githubusercontent.com/36566995/163252980-c5994d55-b9e4-4d63-a47e-b995f74f9ecd.png">

- and eventually runs the tests
<img width="870" alt="image" src="https://user-images.githubusercontent.com/36566995/163254912-d189194f-17fe-4fa5-9b10-0f80093270dd.png">

- This is the point where we figured, maybe it needs proxy.
![image](https://user-images.githubusercontent.com/36566995/163256324-00c6c232-c982-4b1d-9d78-3eb703257cf9.png)
![image](https://user-images.githubusercontent.com/36566995/163256390-df3f4e53-f8bb-41de-9b3e-10c6cd7825cf.png)

- We ended up trying to set proxy on multiple levels, global and test, playwright (or chrome/firefox) are simply not able to reach the website

Eventually, someone came up with the idea of not using the playwright test runner, and voila, this way it works!!!
![image](https://user-images.githubusercontent.com/36566995/163255457-a077d24a-4f96-447d-a910-685cd0380d0c.png)

<img width="624" alt="image" src="https://user-images.githubusercontent.com/36566995/163255638-62069e30-1942-430f-a8a5-ea2780e8ce24.png">

Any kind of help would be appreciated because we really love how the playwright runner is doing things!

THANKS!

**Comment by aslushnikov** [comment]
@goldenox777 so first of all, you can specify proxy as [launch options](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options):

```js
// playwright.config.ts
export default {
  projects: [
    name: 'chromium',
    use: {
      // ... all the options
      launchOptions: {
        proxy: {
          server: '..',
        }
      }
    }
  },
};
``` 

Could you please try this and see if it works?

Also, is gitlab-runner a linux or windows machine?

**Comment by goldenox777** [comment]
Hello @aslushnikov thanks for your reply!
I have tried what you suggested above.
"page.goto: Timeout 10000ms exceeded"

* I will find that out tomorrow
Question: would launchOptions (or something) show up as arguments for chrome when setting DEBUG=pw:browser:* ?
Is there a way to see if the argument actually reaches Chrome?

Many thanks!

**Comment by aslushnikov** [comment]
@goldenox777 can you add the following to the beginning of your `playwright.config.ts`:

```
console.log('http_proxy:', process.env.http_proxy);
console.log('no_proxy:', process.env.no_proxy);
```

Does it output something? We suspect that the environment variables are initialized after the config is read.

**Comment by goldenox777** [comment]
@aslushnikov 
![image](https://user-images.githubusercontent.com/36566995/163275652-c797ce04-d3d2-4f77-8dcd-fbd92c321ccb.png)


Executing "step_script" stage of the job script
Using docker image sha256:b399b07a5d21fcc24294da120c8c09fb7b50d1d1e74538f5f2f181fa8ebc2bc9 for mcr.microsoft.com/playwright:v1.20.0 with digest mcr.microsoft.com/playwright@sha256:9a72a2ef95fdca5317f62d5c5bd8ed7d6ae9231691a12b8f5d4b8b4a2e0828f4 ...
$ export http_proxy=http://webproxy.bru3.dqs.webpage.com:3128/; export https_proxy=$http_proxy; export no_proxy=.webpage.com
$ cd frontend/e2e
$ npm install
added 270 packages, and audited 271 packages in 6s
31 packages are looking for funding
  run `npm fund` for details
found 0 vulnerabilities
$ npx playwright install chromium
$ npx playwright test --grep @critical
http_proxy: http://webproxy.bru3.dqs.webpage.com:3128/
no_proxy: .webpage.com
Running 4 tests using 1 worker
http_proxy: http://webproxy.bru3.dqs.webpage.com:3128/
no_proxy: .webpage.com
[1/4] [chrome] › ui/generic/Generic.desktop.spec.ts:43:3 › Generic tests @regression @critical @desktop › Single passenger navigating through the funnel reaching Payments page @critical @desktop
http_proxy: http://webproxy.bru3.dqs.webpage.com:3128/
no_proxy: .webpage.com
[2/4] [chrome] › ui/generic/Generic.desktop.spec.ts:43:3 › Generic tests @regression @critical @desktop › Single passenger navigating through the funnel reaching Payments page @critical @desktop (retry #1)
http_proxy: http://webproxy.bru3.dqs.webpage.com:3128/
no_proxy: .webpage.com
[3/4] [chrome] › ui/generic/Generic.desktop.spec.ts:43:3 › Generic tests @regression @critical @desktop › Single passenger navigating through the funnel reaching Payments page @critical @desktop (retry #2)
  1) [chrome] › ui/generic/Generic.desktop.spec.ts:43:3 › Generic tests @regression @critical @desktop › Single passenger navigating through the funnel reaching Payments page @critical @desktop 
    page.goto: Timeout 20000ms exceeded.

**Comment by aslushnikov** [comment]
@goldenox777 to re-iterate:

- when you put proxy configuration in `playwright.config.ts`, proxy doesn't work
- when you put proxy configuration as part of the manually-launched browser, proxy does work

Is this the case?

If so, could you please help 2 tests side-by-side:
- one that uses test configuration either via `test.use` and tries to navigate to the page
- second that uses manually launched browser with proxy settings and navigates that page

It'd be helpful if you also don't use any of the POMs; something like this:

```js
// debugproxy.spec.ts
import { test, expect, chromium } from '@playwright/test';

test.describe('with proxy config', () => {
  test.use({
    proxy: {
      server: process.env.http_proxy,
      bypass: process.env.no_proxy,
    },
  });
  test('should work with proxy config', async ({ page }) => {
    await page.goto('https://example.com');
    console.log('pw proxy config:', await page.title());
  });
});

test('should work with manually launched browser', async () => {
  const browser = await chromium.launch({
    proxy: {
      server: process.env.http_proxy,
      bypass: process.env.no_proxy,
    },
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  console.log('manual browser launch:', await page.title());
  await browser.close();
});
```

**Comment by goldenox777** [comment]
@aslushnikov in my observation, as long as the test is within the "test..." block of playwright, it doesn't work
![image](https://user-images.githubusercontent.com/36566995/163324513-74fcd80f-b594-419f-935b-22085c68b589.png)

$ npx playwright test --grep @custom
http_proxy: http://webproxy.fab4.dqs.webpage.com:3128/
no_proxy: .webpage.com
Running 2 tests using 1 worker
http_proxy: http://webproxy.fab4.dqs.webpage.com:3128/
no_proxy: .webpage.com
[1/2] [chrome] › ui/bugs/empty.desktop.spec.ts:11:3 › with proxy config @custom › should work with proxy config
http_proxy: http://webproxy.fab4.dqs.webpage.com:3128/
no_proxy: .webpage.com
[2/2] [chrome] › ui/bugs/empty.desktop.spec.ts:11:3 › with proxy config @custom › should work with proxy config (retry #1)
http_proxy: http://webproxy.fab4.dqs.webpage.com:3128/
no_proxy: .webpage.com
[3/2] (retries) [chrome] › ui/bugs/empty.desktop.spec.ts:11:3 › with proxy config @custom › should work with proxy config (retry #2)
  1) [chrome] › ui/bugs/empty.desktop.spec.ts:11:3 › with proxy config @custom › should work with proxy config 
    page.goto: net::ERR_ADDRESS_UNREACHABLE at https://flights.dqs.webpage.com/
    =========================== logs ===========================
    navigating to "https://flights.dqs.webpage.com/", waiting until "load"
    ============================================================
      10 |   });
      11 |   test('should work with proxy config', async ({ page }) => {
    > 12 |     await page.goto('https://flights.dqs.webpage.com');
         |                ^
      13 |     console.log('pw proxy config:', await page.title());
      14 |   });
      15 | });
        at /builds/npd/flights/frontend/e2e/tests/ui/bugs/empty.desktop.spec.ts:12:16

**Comment by goldenox777** [comment]
as an observation, with the last example you suggested, the error is different 
page.goto: net::ERR_ADDRESS_UNREACHABLE
instead of
page.goto: Timeout 20000ms exceeded.

**Comment by aslushnikov** [comment]
@goldenox777 I don't see the `manual browser launch` in your output. Did it run the `should work with manually launched browser` test?

**Comment by goldenox777** [comment]
Hello @aslushnikov 
after a stroke of "luck", I have stumbled on a pipeline for which both your tests passed.
After many more attempts and retries, I suspect gitlab-runner spawns different docker images (based on which is the next one available).
It turns out that on certain images the tests work and on some others they don't.

Therefore I don't believe this is a playwright issue. It's something with the docker images being used.
Many thanks for the help and keep up the good work!

If there's one thing I could mention is that throughout this process several of us had the same comment "there's 3 lines in the documentation in regards to proxy".
Maybe it could be extended.

Thanks!
