### ISSUE TITLE
[BUG] the page.url() function returning incorrect url when navigation happens

### ISSUE THREAD

**Issue by alexkyrylenkoproven** [microsoft/playwright#13547]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- 1.20.1
- Operating System: [e.g. Windows, Linux or Mac]
- Mac
- Node.js version: [e.g. 12.22, 14.6]
- 16.14.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

gist https://gist.github.com/alexkyrylenkoproven/1223e393b4345249a410f40b016451da

**Describe the bug**
When navigating through multiple pages by clicking links and buttons, at some point page.url() returns the value for one of the previous urls instead of the one that is displayed in the browser

**Comment by Nfactor26** [comment]
I just ran in to this issue with .net bindings as well.

Playwright Version: [what Playwright version do you use?]
1.20.2
Operating System: [e.g. Windows, Linux or Mac]
Windows
Browser: [e.g. All, Chromium, Firefox, WebKit]
Chromium
Extra: [any specific details about your environment]
Navigation happens from a server side asp.net page to a blazor wasm page after login action.

**Comment by marlonmarcello** [comment]
I have the same issue, in my case I have a dropdown that when changed updates the search param on url and `page.url` is returning the outdated value

- Playwright Version: 1.20.2
- Operating System: Mac
- Node.js version: v17.0.1
- Browser:  Chromium

**Comment by marlonmarcello** [comment]
In my case the search param update is immediate, but still I tried `page.waitForNavigation()` and all it's variations and nothing worked.

**Comment by aslushnikov** [comment]
@alexkyrylenkoproven thanks for the repro; I looked into the snippet but didn't debug yet. Will do later.

@marlonmarcello can you share your snippet too? Maybe that's a different problem

**Comment by yury-s** [comment]
@alexkyrylenkoproven I tried your example and I'm getting this:
```
 pw:api element was detached from the DOM, retrying +115ms
 pw:api waiting for selector "div.src-components-quiz-inputs-select-input-container-___select-input-container__label-container___2RsPZ:nth-child(2)" +1ms
```
so the first click gets stuck because the element disappears so there is clearly a race. Looking at `DEBUG=pw:api` logs the page itself navigates to `https://www.provenskincare.com/`:

```
  pw:api attempting click action +5ms
  pw:api   waiting for element to be visible, enabled and stable +1ms
  pw:api   navigated to "https://www.provenskincare.com/" +61ms
```
you need to ensure that the url is stable if the page can trigger multiple navigations. Try [toHaveUrl](https://playwright.dev/docs/test-assertions#page-assertions-to-have-url) which will wait for specified URL.

**Comment by yury-s** [comment]
@marlonmarcello  please file a separate report with your example it may well be something different.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by bkrmadtya** [comment]
> @alexkyrylenkoproven I tried your example and I'm getting this:
> 
> ```
>  pw:api element was detached from the DOM, retrying +115ms
>  pw:api waiting for selector "div.src-components-quiz-inputs-select-input-container-___select-input-container__label-container___2RsPZ:nth-child(2)" +1ms
> ```
> 
> so the first click gets stuck because the element disappears so there is clearly a race. Looking at `DEBUG=pw:api` logs the page itself navigates to `https://www.provenskincare.com/`:
> 
> ```
>   pw:api attempting click action +5ms
>   pw:api   waiting for element to be visible, enabled and stable +1ms
>   pw:api   navigated to "https://www.provenskincare.com/" +61ms
> ```
> 
> you need to ensure that the url is stable if the page can trigger multiple navigations. Try [toHaveUrl](https://playwright.dev/docs/test-assertions#page-assertions-to-have-url) which will wait for specified URL.

Thanks, `toHaveUrl` worked for me.
