### ISSUE TITLE
Log screenshot to buffer on test failure

### ISSUE THREAD

**Issue by daanklijn** [microsoft/playwright#13557]
Hey Folks 👋  

According to the documentation automatic screenshots can be captured when a test failure happens. This can be done by using a config like this:

```js
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    screenshot: 'only-on-failure',
  },
};
export default config;
```
These screenshots are then saved in a directory called `test-results`
For my use case it is difficult to retrieve these files, as the tests are running on a  remote machine.
It would therefore be easier, if the screenshots would just be logged to the buffer / console instead.

To resolve this,  I propose to allow for this kind of behaviour via another config setting.
Something along the lines of this would do:

```js
import { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    screenshot: 'only-on-failure',
    screenshotHandler: 'log-to-console',
  },
};
export default config;
```

**Comment by aslushnikov** [comment]
@daanklijn A few questions?

1. How do you log images to the console? That's a fancy terminal!
2. You mention you run tests on remote machine. Do you use any kind of conventional CI like github actions? In this case, we recommend uploading the `test-results` folder as a run artifact. Alternatively, you can add a step in your workflow after the test run to log the images to the terminal.

**Comment by daanklijn** [comment]
Hey @aslushnikov 

1. Good point, I maybe was a bit to vague 😄 I actually meant logging the base64 of the image to the console. We were already doing this in some scenarios, using the code provided in the Playwright docs:
<img width="843" alt="image" src="https://user-images.githubusercontent.com/27863547/163579811-3993f9fb-abb0-431f-9330-19b3b1b5ab4c.png">

2. No we actually use Buildkite / Jenkins, but at this point I do not have easy access to the configuration of this build pipeline, and can therefore not easily add the `test-results` folder to the build artifacts. Logging the base64 seemed to be a quick way to set up a MVP. As I noticed the docs were doing something similar to that when making screenshots during a test, I figured it might also be useful to support it for the `only-on-failure` feature.

**Comment by aslushnikov** [comment]
> s I noticed the docs were doing something similar to that when making screenshots during a test, I figured it might also be useful to support it for the only-on-failure feature.

@daanklijn I see, but the use case is pretty specific, so adding a new API for that doesn't worth it.

You can use `globalTeardown` for this: just write a small script there that iterates over screenshots in test results folder and logs their results.

**Comment by aslushnikov** [comment]
(closing as per above)
