### ISSUE TITLE
[Question] why im unable to use try and catch for waitForNavigation

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13556]
for some cases, my tests are stalling during navigation so I have decided to do the following :

```
async handleNavigation() {
        try {
            await this.page.waitForNavigation({ timeout: 40000 })            
        } catch  {
            console.log('Navigation is timedout, page will be reloaded!')
            await this.page.reload({ waitUntil: "load" })                        
        }
    }

    async clickApplyButton() {
        await Promise.all([
            this.applyButton.click(),
            this.handleNavigation()
        ]);
        return this;
    }
```

but seems not working since once `await this.page.waitForNavigation({ timeout: 40000 })`, fails  the page is closed as shown below

<img width="990" alt="Screenshot 2022-04-14 at 14 12 45" src="https://user-images.githubusercontent.com/32042806/163388528-2de82c89-e195-4f4d-8dc9-25200f9e73cb.png">

<img width="552" alt="Screenshot 2022-04-14 at 14 14 09" src="https://user-images.githubusercontent.com/32042806/163388552-b47b9367-7cf1-4962-9105-55646a2810a5.png">

**Comment by aslushnikov** [comment]
@amrsa1 hard to say from this description; anything we can run locally to try it out?

**Comment by aslushnikov** [comment]
I'll close this for now since my triaging shift has finished; please re-file with a repro if/when you get one!

**Comment by amrsa1** [comment]
@aslushnikov 

Unfortunately can not share my repo, but basically you easily reproduce it for any domain, just wrap waitForNavigation and add very small timeout, to ensure failure then you will get the error i shared above


```
async handleNavigation() {
        try {
            await this.page.waitForNavigation({ timeout: 40000 })            
        } catch  {
            console.log('Navigation is timedout, page will be reloaded!')
            await this.page.reload({ waitUntil: "load" })                        
        }
    }
```
