### ISSUE TITLE
[Question]: Codegen Timeout In Playwright Version 1.20.1 , Net6.0

### ISSUE THREAD

**Issue by yangbocheng** [microsoft/playwright#13553]
### Your question

I have a question about codegen, when i use "pwsh .\playwright.ps1 codegen" or "playwright codegen" ,  allways failed because of Timeout in Version 1.20.1
![image](https://user-images.githubusercontent.com/32633109/159421816-c5cc768e-f427-4081-aba3-39fc37ff2e14.png)
![image](https://user-images.githubusercontent.com/32633109/159422032-0b38bb68-fd6b-4068-b979-61b172813097.png)

I don't know how to deal with it.
//here is info
But if run codegen with playwright - 1.17.3 ,  chorme will start and record operation correctly after 10s.
And if i  test playwright in c#code, then chorme auto start correctly both in version 1.17.3 and 1.20.1
```csharp
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
      Headless = false,
});
//other codes....
```

**Comment by mxschmitt** [comment]
I'll fold this one into a meta bug https://github.com/microsoft/playwright/issues/13631.

**Comment by mxschmitt** [comment]
@yangbocheng does it work for you if you start it with Administrator rights?

**Comment by yangbocheng** [comment]
@mxschmitt  thanks, but now everything just run well. I have test version 1.20.2 again and version 1.21.0 with Net 5.0 and Net 6.0 , the codegen just start quickly well(i don't konw why) .
If I can reproduce the problem, I'll report back

Thanks for your work, the version 1.21.0 is really good,

**Comment by BilalMohammad5** [comment]
Codegen Timeout In @playwright/test": "^1.21.1
![image](https://user-images.githubusercontent.com/42165960/167299611-442d1360-4b23-411b-a01c-0f8617280bb1.png)

**Comment by mxschmitt** [comment]
> Codegen Timeout In @playwright/test": "^1.21.1
> ![image](https://user-images.githubusercontent.com/42165960/167299611-442d1360-4b23-411b-a01c-0f8617280bb1.png)
> 

You can increase it with `--timeout=30000`
