### ISSUE TITLE
[docs] Debugging tools for non nodejs sdk

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13565]
All of the pages about the debugging tools show the same screenshots of a nodejs script being debugged.

nodejs - https://playwright.dev/docs/debug

dotnet - https://playwright.dev/dotnet/docs/debug
java - https://playwright.dev/java/docs/debug
python - https://playwright.dev/python/docs/debug

it's not clear if these debugging tools work with any programming language or just with the nodejs version

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
