### ISSUE TITLE
[Question] Modifying only response headers 

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13564]
I'm wondering if it would be possible to add metadata to the original response without intercepting it and buffering into memory the response object.

for example - modifying a response header of a 1GB file will force us to buffer all of the response in order to add a response header.

This might be an indicator that the test scenario is not an optimal one and should be optimized, I'm not sure about this :)

**Comment by yury-s** [comment]
This is not currently possible, the [only way](https://playwright.dev/docs/network#modify-responses) to modify response headers today is to get the original response and then call `route.fulfill()` with modified response, so you'll need to buffer it.

What's your use case?

**Comment by Meir017** [comment]
@yury-s The scenario is intercepting a request with a large response that I do not want to modify, just the headers of the response, and doing this without buffering the entire response into memory would be more efficient here.

I have no concrete scenario for this, I was just wondering about what's possible and the limitations

**Comment by yury-s** [comment]
Closing the issue as the question was answered above and currently there are no plans for adding extra support for large response interception.
