### ISSUE TITLE
[BUG]  unable to download playwright by the command npx playwright install

### ISSUE THREAD

**Issue by marcArisen** [microsoft/playwright#13578]
**Context:**
- Playwright Version: -
- Operating System: Windows
- Node.js version: v16.14.2
- Browser:  All
- Extra: [any specific details about your environment]

**Code Snippet**

I cannot install playwright through the command 'npx playwright install'. When I typed 'npx playwright install',  it started to download, but when it reached to 99% it stuck there (like in the picture below)
![image](https://user-images.githubusercontent.com/78196937/163543913-1a633d8e-c4e5-4df4-8eb5-79108d600d80.png)

**Comment by aslushnikov** [comment]
@marcArisen Please wait a bit and try one more time. Looks like some network instability!

Also, where are you located geographically?

**Comment by marcArisen** [comment]
sorry to ask this super dumb question, but how can I know where that is located?

**Comment by aslushnikov** [comment]
I mean, where are **you** located? Depending on your geographical location, we might use different CDNs to serve  browsers. So I was curious to know where you are located.

**Comment by marcArisen** [comment]
I am in Thailand (Is that what you asked for?, sorry but my understanding of it is pretty poor).

**Comment by Massukio** [comment]
I got the similar issue that failed to download playwright no matter how I tried.

Is there any way to check what CDN did I use to download playwright?
I am in Taiwan which is close to reporter's location. Maybe the Asia server is down?

**Comment by aslushnikov** [comment]
I just tried via a Singapore VPN and it downloaded browsers for me. Does the issue persist?

**Comment by TimmyLin-Avancevl** [comment]
Issue is fixed along with https://github.com/microsoft/playwright/issues/13530
I can download playwright properly now.
