### ISSUE TITLE
[Question] When could we expect 'toMatchSnapshot' also for Java, C# 

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#13573]
Hi all,

I see that you put great efort for adding new features concerning visual comparison of screenshots.

Unfortunalety I was not able to find this comparison feature for all other langusges. 

Is there a chance we get the toMatchSnapshot also for Java, this would very much help us with our testing?

Thank you!

**Comment by ltsuda** [comment]
I'm not part of the team but as this feature is for the `Playwright@Test` runner, I don't know if this feature will be available for Java, C# or even for Python as they have their own test runners not develop by Playwright's team. I could be wrong about this, though.

Look at this page below, the Visual Comparisons feature is under `Playwright Test` which is the test runner.

https://playwright.dev/docs/test-snapshots

**Comment by yury-s** [comment]
This is currently specific to the test runner and we did have immediate plans to port it add it in other languages. Let's collect feedback on this request to see if we need to reprioritize.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.
