### ISSUE TITLE
[Question] Locating an optional element

### ISSUE THREAD

**Issue by hornta** [microsoft/playwright#13579]
I'm using Playwright to scrape websites and I've come across a situation where an element exists in some page but not all so I want to write some code to allow the element to not exist without crashing the flow.

I've wrote some code for it to wait at a maximum of 3 seconds until it decides the element isn't showing up because 30 seconds  are just too long for me. 

My question is now: Can I write this in some other way? Do Playwright have functions for this already?
```ts
let description: string | undefined;
try {
  const locator = page.locator(".svtmat_recipe__preamble");
  await locator.waitFor({ timeout: 3000 });
  description = (await locator.textContent()) ?? undefined;
} catch {}
```

**Comment by aslushnikov** [comment]
> My question is now: Can I write this in some other way? Do Playwright have functions for this already?

@hornta No, you did it right! There's no other support for this atm.
