### ISSUE TITLE
[BUG] electronApp.firstWindow never returns any windows

### ISSUE THREAD

**Issue by ahadcove** [microsoft/playwright#13575]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Mac
- Node.js version: 16.5
- Browser: Electron

**Code Snippet**

```javascript
import { _electron as electron } from 'playwright';
import { test } from '@playwright/test';

test('Launch electron app', async () => {
	const electronApp = await electron.launch({ args: ['out/mac/MyApp.app/Contents/Resources/app.asar/dist/main/index.cjs'], executablePath: './out/mac/MyApp.app/Contents/MacOS/MyApp' });
	const window = await electronApp.firstWindow();
	console.log(await window.title());
	await electronApp.close();
});
```

**Describe the bug**

`await electronApp.firstWindow` never resolves with the window even though the window is indeed open

**Comment by aslushnikov** [comment]
@ahadcove what's your app? How do I repro?

**Comment by ahadcove** [comment]
> @ahadcove what's your app? How do I repro?

I've been trying to make another repo to reproduce the issue all day. I can't seem to figure out what causes the no windows to show even though the window is open. The issue repo is a private one. I'm still working on finding the trigger as to what causes the issue

**Comment by aslushnikov** [comment]
@ahadcove ah I see. There's not much I can say without a repro, so I'll close this for now. Feel free to re-file with a repro!

**Comment by ahadcove** [comment]
@aslushnikov i still haven't been able to reproduce this on a repo outside of mine. Any idea why playwright wouldn't be able to see the app opening a window when the app is signed and packaged?

**Comment by aslushnikov** [comment]
@ahadcove no ideas. I'd recommend slowly iterating from a basic working app towards your complicated non-working to find out the culprit.

**Comment by damonsmith** [comment]
Found it! If you specify the executablePath it never gets window created events.
