### ISSUE TITLE
[BUG] yarn dlx playwright install --help displays incorrect options

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/playwright#13586]
Version: 1.20.2

**Code Snippet**

```shell
yarn dlx playwright install --help
```

**Describe the bug**
Running that command prints out that one of the arguments is `--force`, but when trying to run `yarn dlx playwright install chrome msedge webkit --with-deps --force`, there is an failure with an error stating "force is an unknown command".

**Comment by aslushnikov** [comment]
@AAAstorga the `--force` option was introduced in Playwright v1.21, so you should be using a wrong version of Playwright.

**Comment by AAAstorga** [comment]
Apologies! The issue can be closed.
