### ISSUE TITLE
[BUG] disabled attribute set to "disabled" string

### ISSUE THREAD

**Issue by jasonatball** [microsoft/playwright#13583]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Windows
- Node.js version: 16.13.0
- Browser: All
- Extra: [any specific details about your environment]

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 13.64 GB / 31.88 GB
## Binaries:
 - Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.15 - C:\Program Files\nodejs\yarn.CMD
 - npm: 7.7.6 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright-test-coverage: ^1.0.2 => 1.0.3

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div data-v-17f8ae01="" disabled="disabled">Test Disabled</div>
  `);

  await expect(page.locator("text=Test Disabled")).toBeDisabled();
})();
```

**Describe the bug**

I'm using Vuetify and they mark a menu item as disabled with the "disabled" attribute set to "disabled" (instead of true). I was able to work around with this: `await expect(page.locator("text=Test Disabled")).toHaveAttribute("disabled", "disabled")` but was hoping this could be part of the build-in playwright test for `toBeDisabled()`. Thanks!

**Comment by yury-s** [comment]
`toBeDisabled` returns false for the `div` because it's not a form control element such as button, input etc, browser will simply ignore such attribute. If you want to mark the div element as disabled you can set `aria-disabled` attribute on it, in that case `toBeDisabled()` will return true.

**Comment by jasonatball** [comment]
Thanks for the explanation. Since we're using the Vuetify framework we're not really in control of the attributes and behavior but the `toHaveAttribute` method worked great.

I don't suppose there's anyway to overload the included methods like `toBeDisabled` to add additional checks like the check for that disabled attribute?

**Comment by yury-s** [comment]
> I don't suppose there's anyway to overload the included methods like `toBeDisabled` to add additional checks like the check for that disabled attribute?

No, there is no such mechanism.

**Comment by jasonatball** [comment]
@yury-s I have additional information from vuetify:

> aria-disabled [...] indicates to assistive technologies that the element upon which it is set and **all focusable descendants** are disabled

"If playwright isn't counting the v-list-item-title element as disabled based on a parent having aria-disabled then either that's a bug in playwright or you need to alter your test to select the interactive v-list-item element instead."

My markup looks like this:
```
<div data-v-6ca33932="" tabindex="-1" aria-disabled="true" id="list-item-672" class="v-list-item v-list-item--disabled theme--dark">
  <div data-v-6ca33932="" class="v-list-item__icon">
    <i data-v-6ca33932="" aria-hidden="true" class="v-icon notranslate v-icon--disabled mdi mdi-format-list-numbered theme--dark">
    </i>
  </div>
  <div data-v-6ca33932="" disabled="disabled" class="v-list-item__title" style="cursor: pointer; opacity: 0.2;">Show Call Stack</div>
</div>
```
So I can see that the parent does indeed have `aria-disabled=true` but the child div is what is getting matched by playwright with `page.locator("text=Show Call Stack")`. Can you confirm that all focusable descendants like my div should be marked as disabled?

**Comment by jasonatball** [comment]
#5209 says:

> This would be disabled:
> `<button aria-disabled="true">Click</button>`
> so would this:
> `<div role="button" aria-disabled="true">Ok</div>`
> but this would not be disabled:
> `<div aria-disabled="true">Enabled</button>`

So maybe this is back to Vuetify? They seem to think that any parent element with `aria-disabled="true"` (which in their case is a styled div) will mark it and the children as disabled.
