### ISSUE TITLE
How to solve this senario? can someone help me

### ISSUE THREAD

**Issue by CodarMonkey** [microsoft/playwright#13589]
how to solve this scenario?
      
```
<div class="input-field-wrapper"> 
            <span class="label">Quantia</span>
            <input type="number" class="input-field" value="">
 </div>
```

I Tried

       `page.type('[type="number"]', 1.5)`

but i get this error

       `playwright._impl._api_types.Error: text: expected string, got number`

**Comment by mxschmitt** [comment]
Try `page.type('[type="number"]', '1.5')` which should work.

**Comment by CodarMonkey** [comment]
could you give me an example of reusing authentication state?

I already have a .json that I generated, but I am not able to use this state.

thanks for the help and previous answer

**Comment by CodarMonkey** [comment]
thank you very much, it works great now
