### ISSUE TITLE
[BUG] Expect validator not allow elements that extend Locator or Page interface

### ISSUE THREAD

**Issue by RomanIovlev** [microsoft/playwright#13593]
If I have an element that extends the Locator or Page interface like
`export class UIElement implement Locator { ... }`
Then it is not possible to use it in methods like 
`await expect(myElement).toBeVisisble();`
The problem is in this validation function
```
export function expectTypes(receiver: any, types: string[], matcherName: string) {
  if (typeof receiver !== 'object' || !types.includes(receiver.constructor.name)) {
```
You need to check there that the element suits the Locator/Page interface but not "class have name"
Possible solution:
1) Add discriminator to interfaces like 
```
export interface Locator {
  discriminator: 'Playwright Locator Interface';

export interface Page{
  discriminator: 'Playwright Page Interface';
```
2) Add guards for Page/Locator
```
export const isPage = (object: any): object is Page => {
  return object.discriminator === 'Playwright Page Interface';
}

export const isLocator = (object: any): object is Locator => {
  return object.discriminator === 'Playwright Locator Interface';
}
```
3) Validate if elements meet Guards then return
```
export function expectTypes(receiver: any, types: string[], matcherName: string) {
  if (types.includes('Locator') && isLocator(receiver) || types.includes('Page') && isPage(receiver)) {
    return;
  }
...
```

**Comment by pavelfeldman** [comment]
We don't expect Locators or Pages to be extended, how do you create those UIElement objects?

**Comment by RomanIovlev** [comment]
Locator is an interface, so I just implement all its methods using page.locator() element
If it is an interface, I expect that all functions like expect will work with any element that implements this interface (that is what typically expected from interface)
Isn't it?

**Comment by yury-s** [comment]
> If it is an interface, I expect that all functions like expect will work with any element that implements this interface (that is what typically expected from interface)
Isn't it?

The interface just defines public API of the Locator and Page that we commit to maintain long term (as opposed to some internal implementation methods on the same classes) but we don't expect clients to implement those interfaces. Playwright expects only its own implementation of the interfaces and will fail if you try to pass your own object even if it implements all the methods.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
