### ISSUE TITLE
[Feature] Platform: Add Debian support

### ISSUE THREAD

**Issue by mhsdesign** [microsoft/playwright#13591]
currently it says that only ubuntu is supported: https://playwright.dev/docs/library#linux

related issue? https://github.com/microsoft/playwright/issues/3167

**Comment by aslushnikov** [comment]
Please upvote https://github.com/microsoft/playwright/issues/3167 !

**Comment by jpzbkk** [comment]
It was working perfectly until about a month ago... This is extremely frustrating!

**Comment by aslushnikov** [comment]
Debian 11 Bullseye is supported since Playwright v1.24!
