### ISSUE TITLE
do several tests using the same inquiring from the browser

### ISSUE THREAD

**Issue by CodarMonkey** [microsoft/playwright#13595]
Good evening everyone.
I have a doubt. I can somehow open a browser and repeat the same tests on it without closing the browser via script. so I would have a .py file that would start the browser to wait for a certain event so that it repeats the test without having to close the browser? it would be possible? could you give me an example of how this would work?

I don't know if I understood

open browser
wait for event
run event
wait for event
run event

without closing the browser, reusing the instance and the logged in session.

it's possible?

these events are sent from the robot that listens to the telegram.

when a message is received, it handles the message, takes the necessary information and runs it in the browser.

**Comment by aslushnikov** [comment]
There are multiple ways to organize this; the easiest is to have your script running and waiting for some input to process.

However, this is a general programming question and not a Playwright question per se; I'd recommend asking on Stackoverflow or other similar forums!
