### ISSUE TITLE
[BUG] warn user when oversharding tests

### ISSUE THREAD

**Issue by nickofthyme** [microsoft/playwright#13592]
## System:
 - OS: macOS 12.2
 - Memory: 71.11 MB / 32.00 GB
## Binaries:
 - Node: 16.11.1 - ~/.nvm/versions/node/v16.11.1/bin/node
 - Yarn: 1.22.17 - /opt/homebrew/bin/yarn
 - npm: 7.10.0 - ~/Documents/repo/node_modules/.bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

// A few basic tests to run
test('test 1', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});

test('test 2', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});

test('test 3', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

```bash
npx playwright test --shard="2/3"
```

```bash
Running 4 tests using 0 worker, shard 2 of 3

To open last HTML report run:

  npx playwright show-report report
```

**Describe the bug**

I noticed when using the `--shard` flag on a small number of tests, all the tests are run on the first shard run and the rest are run skipping all the tests. This is most certainly an edge case and not sure how many people will come across this but it may also happen with a lot of tests but rediculous shard count. The current behavior just says running `Running 4 tests using 0 worker` and exits without error but really all the tests are run in the first shard.

It would be nice to prompt when the shard count is too high such that some shards are not running any tests, not sure if this should throw an error or not.

**Comment by pavelfeldman** [comment]
I'm not sure such an error is going to be actionable. Your --shard=2/3 is likely hardcoded on your ci/cd and there is no error handler that would do anything about it. You can try fully parallel mode if you'd like tests within the same file to run in parallel btw.

**Comment by nickofthyme** [comment]
Yeah true maybe not an error but I could see someone oversharding their tests in CI/CD and never realize they have empty shard executions wasting compute resources. In this case the only visibility would come from throwing an error. Just a thought if you see this as a non-issue, feel free to close.

**Comment by yury-s** [comment]
This should not be a problem with large enough number of tests with a few tests sharding may be redundant but the behavior is going to be correct. Closing this issue for now, we may revisit if there are more complaints.
