### ISSUE TITLE
[Question]How to Page.getResouceContent

### ISSUE THREAD

**Issue by wideweide** [microsoft/playwright#13602]
In Puppeteer，I use some code to get js/css/jpg from opened page, not to download or request again. 
Is there better unified metod to do this in all browser  such as firefox and other...

```
async function getResourceContent(page, url) {
    try {
        let { content, base64Encoded } = await page._client.send(
            'Page.getResourceContent',
            { frameId: String(page.mainFrame()._id), url },
        );
        return content
    } catch (error) {
        return ''
    }
}
```

**Comment by aslushnikov** [comment]
@wideweide you should subscribe to the [`page.on('response')`](https://playwright.dev/docs/api/class-page#page-event-response) event and use [`response.body()`](https://playwright.dev/docs/api/class-response#response-body) method.
