### ISSUE TITLE
[Question] Disable verbose logging

### ISSUE THREAD

**Issue by davidbielik** [microsoft/playwright#13607]
How can I disable these logs?

```
=========================== logs ===========================
navigating to "http://localhost:6112/", waiting until "load"
============================================================
```

**Comment by aslushnikov** [comment]
Where do you get them?

**Comment by davidbielik** [comment]
They appear in errors:

```
try {
   const navigationPromise = await page.goto(`http://localhost:${port}`, {
      timeout: 50,
    });
} catch(e){
   console.log(e);
}

```
page.goto: Timeout 1000ms exceeded.
=========================== logs ===========================
navigating to "http://localhost:8011/", waiting until "load"
============================================================
    at /path/to/test.js:47:42 {
  name: 'TimeoutError'
}
```

**Comment by aslushnikov** [comment]
Ah, yes, there's no way today. If they do bother you a lot, I'd recommend post-processing error messages and cutting it out
