### ISSUE TITLE
how to check browser

### ISSUE THREAD

**Issue by CodarMonkey** [microsoft/playwright#13604]
how to check if the browser is already open

**Comment by aslushnikov** [comment]
There are two methods that you might find helpful:
- [`browser.isConnected`](https://playwright.dev/docs/api/class-browser#browser-is-connected)
- [`page.isClosed`](https://playwright.dev/docs/api/class-page#page-is-closed)

```js
// a.mjs
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
console.log(browser.isConnected()); // true
await browser.close();
console.log(browser.isConnected()); // false
```
