### ISSUE TITLE
[BUG] Playwright.js waitForRequest times out when running on Azure Function Linux

### ISSUE THREAD

**Issue by tonymuu** [microsoft/playwright#13600]
**Context:**
- Playwright Version: 1.19.1
- Operating System: Linux
- Node.js version: 12 LTS
- Browser: Chronium
- Extra: Running on Azure Function Runtime version 3 Linux consumption plan

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Navigation code:
```javascript
async () => {
  const promises = [];
  if (waitUntil) promises.push(waitUntil(page));
  promises.push(page.goto(urlStr));
  await Promise.all(promises);
}
```

`waitUntil` is one of the following:
```javascript
const waitForSomeRequest = page => page.waitForRequest(req => req.url().includes("SomeQuery"), { timeout: 5000 });
const waitForNetworkIdle = page => page.waitForLoadState("networkidle", { timeout: 5000 });
```

**Describe the bug**

So I am writing a scraper that scrapes about 3k pages daily. I create 10 browser pages to batch scrape 10 things at the same time. The code runs beautifully on Windows with node version v12.22.10, but when deployed to the `Azure Function Linux Consumption` plan, I'm getting a lot of time outs on practically all waitFor statements (see the logs below). I have setup retries (5 times), but almost all of the waitFor checkpoints are timing out, some are timing out over 30 seconds. What would be the cause of this? Again, the code runs perfectly fine on my local Windows OS (with the same node/function version), but when deployed to the Azure Function it fails.

![image](https://user-images.githubusercontent.com/10318596/163752066-ff3a5594-0b47-49db-bc35-b2e83ff52bee.png)

![image](https://user-images.githubusercontent.com/10318596/163752126-ffcbb66a-5c03-4f3b-a887-3830fb44ef5e.png)

**Comment by tonymuu** [comment]
Also, I have 3 functions under the same Azure Function app plan. They run consecutively (not in parallel). Could the limit on resources be the reason why this is happening?

**Comment by aslushnikov** [comment]
> The code runs beautifully on Windows with node version v12.22.10, but when deployed to the Azure Function Linux Consumption plan, I'm getting a lot of time outs on practically all waitFor statements (see the logs below). <...> What would be the cause of this?

@tonymuu It doesn't look like an issue with Playwright since code runs fine locally. And we don't have much experience with Azure functions, so we can't suggest much here!
