### ISSUE TITLE
[BUG] Playwright stalls before half of the test finished.

### ISSUE THREAD

**Issue by StfBauer** [microsoft/playwright#13611]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Mac
- Node.js version: v14.19.0
- Browser: All
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.3.1
 - Memory: 14.22 GB / 64.00 GB
## Binaries:
 - Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.5.5 - ~/.nvm/versions/node/v14.19.0/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/local/bin/bash

**Code Snippet**

```javascript
// @ts-check
const {
  test,
  expect
} = require('@playwright/test');

const path = require('path');

const patternTool = require('../tools/get-test');
const patternsToTest = patternTool.getPatterns();
const testConfigJson = require('./localStorage.json');

let currentPattern;

const currentTheme = 'yellow'


test.beforeEach(async ({
  page
}) => {

  await page.goto(`${currentPattern.path}`);

  await page.addInitScript(value => {
    window.localStorage.setItem('availableThemes', value);
    window.sessionStorage.setItem('currentTheme', currentTheme);
  }, testConfigJson);

});



for (const currentTest in patternsToTest) {
  // console.log(currentPattern);

  currentPattern = patternsToTest[currentTest];

  test.describe(`Theme ${currentTheme}`, () => {

    test(`Test: ${currentTest} - ${currentPattern.name}`, async ({
      page
    }) => {

      // await page.waitForLoadState('domcontentloaded');

      const screenshotPath = `./screenshots/${currentTheme}/${path.basename(currentPattern.path, '.html')}.png`

      expect(await page.screenshot()).toMatchSnapshot(screenshotPath, {
        threshold: 0.01,
        maxDiffPixelRatio: 0.1
      });

    });


  });

};
```

**Describe the bug**

After nearly having the test seems to stall and I can wait for hours. Nothing moving forward anymore.

<img width="684" alt="Screenshot 2022-04-18 at 18 15 46" src="https://user-images.githubusercontent.com/5503835/163838812-1792b646-d9e3-4a12-b82f-0ad70cb13caf.png">

Is the bug on my side or is it really a bug.

Try to test a style guide and various themes. The style guide is based on https://patternlab.io
Assets I like to test can be found here: https://lab.n8d.studio/htwoo/htwoo-core/?p=all

**Comment by yury-s** [comment]
> After nearly having the test seems to stall and I can wait for hours. Nothing moving forward anymore.

Are you running with timeout disabled?

>    `window.sessionStorage.setItem('currentTheme', currentTheme);`

Note that this code throws as `currentTheme` is not defined in the init script scope.


> Is the bug on my side or is it really a bug.

It's hard to tell as there is quite a few things missing in the example. Can you share a reproducible scenario that we could run locally?

**Comment by StfBauer** [comment]
thank you for your support. I published everything to the testing branch.
https://github.com/n8design/htwoo/tree/testing

So you should be able to run it from there.

Session storage as a storage event receiver on the web frontend that changes to theme color.

It works fine to some point as far as I can see and then it starts to stall.

**Comment by yury-s** [comment]
> From htwoo-core you should be able to run:

I checked out 'testing' branch, npm test fails with this:

```
Error: Cannot find module '/home/yurys/sandbox/htwoo/htwoo-core/public/styleguide/data/patternlab-data.cjs'
Require stack:
- /home/yurys/sandbox/htwoo/htwoo-core/tools/get-test.js
- /home/yurys/sandbox/htwoo/htwoo-core/tests/theme.yellow.spec.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/@playwright/test/lib/loader.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/@playwright/test/lib/runner.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/@playwright/test/lib/cli.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/playwright-core/lib/cli/cli.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/playwright-core/cli.js
- /home/yurys/sandbox/htwoo/htwoo-core/node_modules/@playwright/test/cli.js

   at ../tools/get-test.js:3

  1 | const fs = require('fs');
  2 | const path = require('path');
> 3 | const patterns = require(path.join(__dirname, '../public/styleguide/data/patternlab-data.cjs'));
    |                  ^
  4 |
  5 | const allPatterns = [];
  6 |

    at Object.<anonymous> (/home/yurys/sandbox/htwoo/htwoo-core/tools/get-test.js:3:18)
    at Object.<anonymous> (/home/yurys/sandbox/htwoo/htwoo-core/tests/theme.yellow.spec.js:9:21)
```

**Comment by StfBauer** [comment]
@yury-s sorry forgot to check in the public folder because it is normally in the .gitignore and not needed in the repo or will automatically get created.

For easier testing, I checked it now for you into the repo.

So you should be fine now.

**Comment by yury-s** [comment]
I can reproduce it, investigating.

**Comment by yury-s** [comment]
The problem is that [`getPatterns`](https://github.com/n8design/htwoo/blob/f5e345adc428a50b4c72139233916bc44d6fc0a2/htwoo-core/tools/get-test.js#L46) is not idempotent, on each call it will increase number of entries in `allPatterns`. For 4 files it is called 4 times in the test runner and for each file it generates 163, 2*163, 3*163, 4*163 tests. But when worker picks up the same file it will run `getPatterns ` in a fresh context and it will always return 163 tests. We should definitely fix it on the playwright side and provide a clear error message instead of hanging. On your end you can simply move https://github.com/n8design/htwoo/blob/f5e345adc428a50b4c72139233916bc44d6fc0a2/htwoo-core/tools/get-test.js#L49-L63 outside of the function to make sure it runs only once.

**Comment by StfBauer** [comment]
Awesome - Thank you very much I will try this.

**Comment by StfBauer** [comment]
Worked perfectly now. Pumped up the test and this is the result.

<img width="590" alt="Screenshot 2022-04-21 at 01 53 05" src="https://user-images.githubusercontent.com/5503835/164343132-a269441b-b87c-448a-a68f-15d124e90415.png">

Thank you @yury-s 🙏
