### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mdkgr** [microsoft/playwright#13614]
![image](https://user-images.githubusercontent.com/5529044/163857796-aba746f4-74f2-4b58-9e55-26989e533940.png)

While JetBrains WebStorm IDE runs scripts normally, it can't recognize the methods for some reason...

Tried reinstalling playwright, WebStorm, using older Playwright versions....

Playwright methods show up and run just fine on VS Code...

Any ideas? 

Thanks for your time!!

**Comment by yury-s** [comment]
Playwright does provide type definitions for those methods (otherwise VS Code would complain too). Please ask this question in WebStorm support forum.
