### ISSUE TITLE
[BUG] Got response of an earlier request (unexpected)

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright#13630]
**Context:**
- Playwright Version: 1.20.1
- Operating System: Windows
- .NET version: .NET 5
- Browser: Chromium
- Extra: this is an open id connect flow

**Code Snippet**

```cs
var response = await page.GotoAsync("https://mysite/overzicht", new PageGotoOptions { WaitUntil = WaitUntilState.NetworkIdle });
var responseUrl = response!.Url;
var responseHeaders = await response.AllHeadersAsync();
```

**Describe the bug**
Going to this url will do 4 requests:

![image](https://user-images.githubusercontent.com/5808377/163566282-ac9ddeee-d30e-447b-8868-0c6885a0fcd2.png)

**Expected**
- Get the URL and headers of the **last** request. [The docs](https://playwright.dev/dotnet/docs/api/class-page#page-goto) also say 
   > Returns the main resource response. In case of multiple redirects, the navigation will resolve with the response of the **last** redirect.

**Current**
- The page is on "overzicht" (the last request) - that's good!
- The _responseUrl_  and the _responseHeaders_  are of the 2nd request - "authorize".

**Comment by yury-s** [comment]
> Besides the doc change - how could I get the response of the latest? For now, I only see the option by listing to the [Page.Request](https://playwright.dev/dotnet/docs/api/class-page#page-event-request) event?

Since the second navigation is triggered by the page, listening for Page.Request events is your best bet.
