### ISSUE TITLE
[Question] Does playwright support multiple workers when using MS edge ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13633]
I was wondering if its a bug or not a supported feature since I'm unable to run multiple workers using MS edge

`projects:  [{ name: 'Edge', use: { channel: 'msedge' } }]
` 
<img width="294" alt="Screenshot 2022-04-19 at 17 40 50" src="https://user-images.githubusercontent.com/32042806/164042572-6f24dae5-5b4d-4723-8fff-49172d722b40.png">

<img width="416" alt="Screenshot 2022-04-19 at 17 40 04" src="https://user-images.githubusercontent.com/32042806/164042377-c8e69d24-bfb6-4737-8689-b3c1e7e1e85d.png">

**Comment by yury-s** [comment]
It should work just like with any other browsers. Can you tell us more about your scenario or maybe share a repro?

**Comment by amrsa1** [comment]
please disregard, i had a typo
