### ISSUE TITLE
[Question] How to access the currently chosen browser in globalSetup?

### ISSUE THREAD

**Issue by neongreen** [microsoft/playwright#13643]
I have code like this in my global setup (copied from the docs):

```typescript
import { chromium, FullConfig } from '@playwright/test'

async function globalSetup(config: FullConfig) {
  const browser = await chromium.launch()
  ...
  await browser.close()
}

export default globalSetup
```

This means that Chromium has to be installed regardless of the actual browser I've specified in `playwright test --browser=${browser}`.

Is there a way to `.launch()` the browser chosen via `--browser=`?

**Comment by neongreen** [comment]
Note: if there are many "current" browsers (e.g. a test matrix specified in the playwright config), I don't mind which gets chosen. Could be Chrome, could be the first one on the list, etc.

**Comment by yury-s** [comment]
This is not currently possible. globalSetup only receives FullConfig but not the project filter. See also these requests: https://github.com/microsoft/playwright/issues/12084, https://github.com/microsoft/playwright/issues/11809

**Comment by yury-s** [comment]
Folding this issue into https://github.com/microsoft/playwright/issues/13648
