### ISSUE TITLE
[Feature] docs - Migrate puppeteer to playwright

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13646]
similar to #13608

Having docs for migrating from puppeteer to playwright and handling common scenarios would be helpful
some scenarios can be taken from the official puppeteer docs to show the API change.

for example:
```ts
import * as playwright from 'playwright';
import * as puppeteer from 'puppeteer';

async function puppeteerMain() {
    const browser = await puppeteer.launch(); // defaults to chrome
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await page.screenshot({ path: 'example.png' });

    await browser.close();
}

async function playwrightMain() {
    const browser = await playwright.chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await page.screenshot({ path: 'example.png' });

    await browser.close();
}
```

**Comment by SimonSiefke** [comment]
I believe this would be a great addition to the docs! Having used puppeteer before, most of my code intuitively looked like this: 

```js
// delete file
await page.click('text=file1.txt', {
  button: 'right',
})
await page.click('text=delete')
await page.waitForFunction(
  // @ts-ignore
  () => !document.querySelector('[title="/file1.txt"]')
}
```


After some time using playwright, I have refactored my code to this: 

```js
// delete file
const file1 = page.locator('text=file1.txt')
await file1.click({
  button: 'right',
})
const deleteMenuItem = page.locator('text=delete')
await deleteMenuItem.click()
await expect(file1).toBeHidden()
```

So maybe something like a side-by-side comparison between `traditional code with page.click, page.waitForSelector` and `code using playwrights locator api` would also be useful for some people.

**Comment by Meir017** [comment]
@SimonSiefke I started a repository for these comparisons https://github.com/Meir017/web-testing-frameworks more scenarios coming up...

**Comment by jfgreffier** [comment]
@Meir017 I've created a pull request, don't hesitate to give feedback on it !
