### ISSUE TITLE
How to add and save cookies.

### ISSUE THREAD

**Issue by goranti-maneesh** [microsoft/playwright#13647]
When I try to add the cookies, it is not being saved in the browser. But, when I logged the cookies i.e `console.log(await context.cookies())` the cookies are displayed in the console.

Code
```
const arr = [
    {
      name: "cookie1",
      value: "p5kqRCNJPjUMF8zgB7b4hVE",
      domain: ".some_url",
      path: "/",
    },
    {
      name: "cookie2",
      value: "ak0yxigDT790otvvXPWIfgkFlzzpgU",
      domain: ".some_url",
      path: "/",
    }
  ]

 const browser = await chromium.launch();
 const context = await browser.newContext();
 await context.addCookies([...arr])
 console.log(await context.cookies())
```

Can anyone help me to resolve the issue.

**Comment by yury-s** [comment]
> When I try to add the cookies, it is not being saved in the browser.

What do you mean by that, the cookies are not sent with a request, not available on document.cookie or something else? Can you share the code which is failing?

**Comment by goranti-maneesh** [comment]
Thank you for responding. 

When I try to add cookies in the browser using `await context.addCookies([...arr])`, then the cookies are not saved in the **application tab** in the developer tools.

But, when I am trying to log the added cookies using `console.log(await context.cookies())`, then the added cookies are displayed in the console.

Once check the code provided in the above discussion.

**Comment by yury-s** [comment]
What is the url you navigate to and inspect in the application tab, can you share complete example?

**Comment by goranti-maneesh** [comment]
> What is the url you navigate to and inspect in the application tab, can you share complete example? My hunch is that the url you navigate to doesn't match the cookies.

URL navigating to - https://URL.Domain_url.in
Cookies Domain name - .Domain_url.in

**Comment by goranti-maneesh** [comment]
> What is the url you navigate to and inspect in the application tab, can you share complete example? My hunch is that the url you navigate to doesn't match the cookies.

Navigating URL - https://localhost:3000.Domain_url.in
Cookies Domain - .Domain_url.in

**Comment by goranti-maneesh** [comment]
> What is the url you navigate to and inspect in the application tab, can you share complete example? My hunch is that the url you navigate to doesn't match the cookies.

goto URL - https://test.example.com
cookies domain - .example.com

**Comment by pavelfeldman** [comment]
It works for me, could you provide a snippet that you are running?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by bhargavcp** [comment]
Hi @pavelfeldman @yury-s , is it possible to set cookies for a domain that is different than the one that the tests would be running in?

E.g. the base url of my app is "www.example.com", but can I do something like this:
```
await this.context.addCookies([
      {
        name: "my-cookie",
        value: "some-value",
        domain: ".another-domain.com",
        path: "/",
      },
    ]);
```

I tried doing that but I don't see the cookies being available under www.example.com
