### ISSUE TITLE
[BUG] The "Navigation interrupted by another one" error happens randomly when calling `page.goto(url)` to open a URL

### ISSUE THREAD

**Issue by AIGeneratedUsername** [microsoft/playwright#13651]
# Context
- Playwright Version: 1.20
- Operating System: Lubuntu 20.04
- Python 3.10.4
- Browser: Firefox

# Log

Too large for GitHub to copy/paste, so full DEBUG log is attached as a file [playwright_log.tar.gz](https://github.com/microsoft/playwright/files/8520653/playwright_log.tar.gz)

Here is only the end of the log:
```
Traceback (most recent call last):
  File "/home/ujio/PycharmProjects/client/_local.py", line 46, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ujio/PycharmProjects/client/_local.py", line 25, in main
    await page.goto(url, timeout=120_000)
  File "/home/ujio/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 7581, in goto
    await self._async(
  File "/home/ujio/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/home/ujio/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/home/ujio/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/ujio/.cache/pypoetry/virtualenvs/client-NboAmZt6-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Navigation interrupted by another one
=========================== logs ===========================
navigating to "https://www.citilink.ru/catalog/karty-pamyati", waiting until "load"
============================================================
 
Process finished with exit code 1
```

# Steps to reproduce
The error happens randomly for random URLs, so there is no specific URL example.
```python
from playwright.async_api import async_playwright

async with async_playwright() as p:
        browser = await p.firefox.launch()
        page = await browser.new_page()
        for url in my_urls_list:
            await page.goto(url)
        await browser.close()
```

**Comment by yury-s** [comment]
The error message is pretty clear there is another navigation (most likely started by the page itself) that interferes with `page.goto("https://www.citilink.ru/catalog/karty-pamyati")`. If you have reason to believe it's not the case please reopen this or file a new issue with a repro , we'll need urls that cause that.

**Comment by konflic** [comment]
How to avoid this issue? I know that navigation interrupted< but consider this is ok and I dont need this error.

**Comment by niculicchio** [comment]
I have exactly the same issue. My page.goto() trigger a redirection (it's wanted, for a keycloak login).

Everything was ok with PW 1.45.
After updated to v1.49, I'm now randomly facing this problem...

```
Error: page.goto: Navigation to 'https://website1.xxx' is interrupted by another navigation to 'https://website2.xxx/auth/realms/xxxxx'

Call log:
  - navigating to "https://website1.xxx", waiting until "load"

   at pages/loginPage.js:13

  11 |
  12 |     async gotoLoginPage() {
> 13 |         await this.page.goto('https://website1.xxx');
     |                         ^
  14 |     }
```

Can you help me?

**Comment by avramukk** [comment]
I am also facing this problem right now. We are using auth0, and I am trying to use a global setup for saving storageState. It works in ~50% of cases, but the rest have an error about interruption by another navigation (I don't know why; it's some auth0 stuff).
![Image](https://github.com/user-attachments/assets/5a99e99b-4b8b-42df-b79a-fb47a85b8be8)

**Comment by 378210331** [comment]
I have exactly the same issue . happen when i upgrade playwright version from 1.42 to 1.49  . chromium version  123 -> 131 .  and then i rollback the upgrade and it seems to be fine .

**Comment by 378210331** [comment]
finally I got the answer, don't use the page object at twice , create page at each request and then close at last.

**Comment by niculicchio** [comment]
> finally I got the answer, don't use the page object at twice , create page at each request and then close at last.

that's not a solution. Not to use POM is not a viable solution for Playwright. The issue has to be solved.

**Comment by niculicchio** [comment]
> finally I got the answer, don't use the page object at twice , create page at each request and then close at last.

and by the way, your tip isn't solving the problem. I'm having the same error even by using _page.goto()_ directly in my test and not in POM

**Comment by niculicchio** [comment]
Please can someone give a check about this issue ? It's driving me crazy...

**Comment by pschroeder89** [comment]
Any luck on this @niculicchio ?

**Comment by Groschenroman** [comment]
Just to make sure, @niculicchio: are you 100% sure that there is no `await` somewhere in your test?

I had the same issue just now and weirdly enough, Firefox passed the test successfully but Chrome and Webkit failed with this navigation error. So I duckduckgoed ( 😬 ) and came across this comment by @aslushnikov [in a similar Github issue](https://github.com/microsoft/playwright/issues/16686#issuecomment-1222957602) and where asked this very question about possibly missing `await` statements that could cause overlapping timing issues between promises.
So I meticulously looked through every line of code in my test (as well as the custom fixture and a helper function that it uses) and found some unawaited promises indeed. Now the test passes successfully for all browsers.

**Comment by niculicchio** [comment]
@Groschenroman , in my case the issue came on a "one line" action (simply _await this.page.goto('https://website1.xxx');_ ), so no need to check for missing await...

The solution that seems solve it, for me, was to use an expect() .toPass() : 

`async gotoLoginPage() {
        await expect(async () => {
            await this.page.goto('https://website1.xxx');
        }).toPass();
    }`
