### ISSUE TITLE
[Question] Ubuntu 20.04 webkit headless H264

### ISSUE THREAD

**Issue by aquacode** [microsoft/playwright#13659]
I read that Ubuntu 20.04 is support for all browsers:

Playwright requires Node.js version 12 or above. The browser binaries for Chromium, Firefox and WebKit work across the 3 platforms (Windows, macOS, Linux):

I'm running an Ubuntu 20.04 Docker container.
However, I'm having difficulty using WebKit headless with H264. 

I've compiled the source from cisco/openh264 and installed the resulting libraries (perhaps incorrectly) but still I observe when loading a page that requires H264 the WebKit headless browser is not able to detect the codecs are present. 
Is this not supported, or should I not expect it work, or is it the case that I've got something wrong?

**Comment by yury-s** [comment]
Our WebKit build doesn't include  proprietary codecs such as h264 (see related bug regarding Chromiun https://github.com/microsoft/playwright/issues/11694).
