### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'includes')

### ISSUE THREAD

**Issue by SimonSiefke** [microsoft/playwright#13652]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Linux 
- Node.js version: 17
- Browser: Electron
- Extra:

**Code Snippet**

**Describe the bug**

```
locator.hover: TypeError: Cannot read properties of undefined (reading 'includes')
    at parseSelectorString (<anonymous>:1291:17)
    at parseSelector (<anonymous>:1197:18)
    at InjectedScript.parseSelector (<anonymous>:3790:20)
    at makeStrict (<anonymous>:3450:43)
    at cssFallback (<anonymous>:3494:54)
    at generateSelector (<anonymous>:3303:40)
    at InjectedScript.generateSelector (<anonymous>:3797:83)
    at <anonymous>:4443:22
    at Array.map (<anonymous>)
    at InjectedScript.strictModeViolationError (<anonymous>:4441:63)
```

**Repository to reproduce the issue**
https://github.com/SimonSiefke/playwright-bug-13652

Steps: 

- `uniqueCssSelector` returns undefined here https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/selectorGenerator.ts#L230
- The result (undefined) is passed to the makeStrict function here https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/selectorGenerator.ts#L290
- There is the exclamation mark (!) to suppress the typescript error https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/injected/selectorGenerator.ts#L290 since makeStrict only accepts strings
- The actual exception occurs in parseSelectorString(selector:string) https://github.com/microsoft/playwright/blob/845e32cbb8b8e3809eb4f0dbc2b6a5607c715a80/packages/playwright-core/src/server/isomorphic/selectorParser.ts#L171

**Comment by yury-s** [comment]
Can you share example where it occurs?

**Comment by SimonSiefke** [comment]
I've now added a repository to reproduce the issue ([SimonSiefke/playwright-bug-13652](https://github.com/SimonSiefke/playwright-bug-13652))

**Comment by yury-s** [comment]
> I've now added a repository to reproduce the issue ([SimonSiefke/playwright-bug-13652](https://github.com/SimonSiefke/playwright-bug-13652))

Tried to run it but getting [this error](https://gist.github.com/yury-s/2940bb31034d3ceee125602f7cfc1105).

**Comment by SimonSiefke** [comment]
Apologies, it was my mistake, vscode package.json path is different on macos. Please check again :)

**Comment by yury-s** [comment]
Thank you, I can reproduce it now.

**Comment by yury-s** [comment]
The selector that causes the problem is `html body .enable-motion div div div div:nth-child(2) div div:nth-child(3) div .monaco-split-view2.horizontal div:nth-child(2) div div:nth-child(2) [id="workbench\.parts\.sidebar"] .content [id="workbench\.view\.explorer"] .monaco-pane-view .monaco-split-view2 div:nth-child(2) div:nth-child(3)`
