### ISSUE TITLE
[Question] Where is firefox being downloaded from

### ISSUE THREAD

**Issue by AviFix** [microsoft/playwright#13663]
Hi

I would like to use PlaywRight with a specific version of firefox.

How can I do it?

Where does the firefox being downloaded from?

**Comment by yury-s** [comment]
> I would like to use PlaywRight with a specific version of firefox.
> 
> How can I do it?

This is not currently possible, Playwright doesn't work with stock Firefox as it doesn't provide required debugging protocol.

You can only run Playwright with the bundled build of Firefox.

**Comment by AviFix** [comment]
> > I would like to use PlaywRight with a specific version of firefox.
> > How can I do it?
> 
> This is not currently possible, Playwright doesn't work with stock Firefox as it doesn't provide required debugging protocol.
> 
> You can only run Playwright with the bundled build of Firefox.

My Project needs to use firefox-1304  current firefox being installed is firefox-1319


How can I get it to install firefox-1304?

**Comment by yury-s** [comment]
You should install playwright version that comes with that version of firefox, we don't provide other means to download as Firefox  protocol is in general only compatible with the Playwright version it is released with. For 1304 you'll need Playwright [1.18.*](https://github.com/microsoft/playwright/blob/v1.18.0/packages/playwright-core/browsers.json)

**Comment by AviFix** [comment]
> You should install playwright version that comes with that version of firefox, we don't provide other means to download as Firefox protocol is in general only compatible with the Playwright version it is released with. For 1304 you'll need Playwright [1.18.*](https://github.com/microsoft/playwright/blob/v1.18.0/packages/playwright-core/browsers.json)

Tanks a lot
that solved my problom
