### ISSUE TITLE
[Question] How to get the Element Content?

### ISSUE THREAD

**Issue by yflako1** [microsoft/playwright#13660]
Hi there,

Sorry I have been a manual tested for a few years and started using Playwright which it is amazing.
I am trying to get the number 2001266 from the element below and store it into a variable so I can later use to compare it with another value, any idea how can I get this number?

`<span data-test="Number">2001266</span>`

Thanks in advanced!
Gerardo

**Comment by yury-s** [comment]
Use [Locator.textContent()](https://playwright.dev/docs/api/class-locator#locator-text-content):
```js
const text = await page.locator('span[data-test="Number"]').textContent();
```

**Comment by yflako1** [comment]
Thank you Yury! I am able to get the value now.
