### ISSUE TITLE
[Question] How to test emails with Playwright?

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#13661]
Do you have some kind of documentation on how to test emails with Playwright?
For example, the registration email received looks good; the order confirmation email received and the content is correct, etc.
Is there some standard way to do it?
Which email clients would you recommend to use for testing it? Gmail? Mailosaur? Maybe some other free options ...?

**Comment by yury-s** [comment]
This choice is up to you and you should decide based on your requirements, Playwright provides means for testing and automation of web apps and will work with any web email client.

**Comment by mareru** [comment]
Ok, but do you have some kind of examples on how to do it with e.g. Gmail?
Sorry to say this, but this comment is not very constructive :/ imho

**Comment by yury-s** [comment]
We don't have any examples specific for gmail. Playwright assumes some knowledge of web technologies and JavaScript/TypeScript and doesn't provide educational resources in those areas, you should look elsewhere for that. Like I said above testing / automating web-based email client is not much different from automating other web applications and all playwright methods should work but they assume at least basic understanding of web applications.

**Comment by hampsterx** [comment]
use an email API provider such as https://www.mailslurp.com and then set your test user to that email box,  pull out the email during the test and use `page.setContent(html)` with the html email content. We create two per email at 920px and 520px (eg `page.setViewportSize()` to simulate desktop and mobile clients.
