### ISSUE TITLE
[BUG] intellisinse treats chromium launch channel as string

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13676]
## System:
 - OS: Windows 10 10.0.19043
 - Memory: 5.91 GB / 15.83 GB
## Binaries:
 - Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 8.1.4 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.3.48 - C:\Windows\System32\bash.EXE
## npmPackages:
 - playwright: ^1.21.1 => 1.21.1

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const playwright = require('playwright');

playwright.chromium.launch({
    channel: "test"
});
```

![image](https://user-images.githubusercontent.com/9786571/164431818-fc66e925-f9ff-471c-8046-58ac9460f31b.png)

**Describe the bug**

Using an invalid channel value should be reported as an error

**Comment by yury-s** [comment]
It used to be an enum but we switched to a string in [this PR](https://github.com/microsoft/playwright/pull/6738/files#diff-98f0d704b0e4df307f4d90213bc415ce208d333a4b000524a8426ca733dd35a2) to have more flexibility to change allowed values. The string passed as the channel is still validated in runtime and the method will throw if the value is not supported.
