### ISSUE TITLE
[BUG] Cannot connect to Android Emulator

### ISSUE THREAD

**Issue by linhanh512** [microsoft/playwright#13671]
**Context:**
- Playwright Version: 1.21.0
- Operating System: MAC 12.3.1
- Node.js version: 8.6.0
- Browser: Chrome

**Code Snippet**
Here is my sample script for Android Chrome

```typescript
/**
 * Example automation on Android with WebView
 * @see https://playwright.dev/docs/api/class-android
 */
 import {_android as android, test} from '@playwright/test';

test.use({
  /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
  actionTimeout: 0,

  /* Base URL to use in actions like `await page.goto('/')`. */
  baseURL: process.env.BASEURL,

  /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
  trace: 'on',

  acceptDownloads: true,
});

test.describe('Run native Android tests', async () => {
  test('WebView', async () => {
    // Connect to the device.
    const [device] = await android.devices();
    console.log(`Model: ${device.model()}`);
    console.log(`Serial: ${device.serial()}`);
    // Take screenshot of the whole device.
    await device.screenshot({path: 'device.png'});
    // Launch an application with WebView.
    await device.shell('am force-stop org.chromium.webview_shell');
    await device.shell('am start org.chromium.webview_shell/.WebViewBrowserActivity');
    // Get the WebView.
    const webview = await device.webView({pkg: 'org.chromium.webview_shell'});

    // Fill the input box.
    await device.fill({res: 'org.chromium.webview_shell:id/url_field'}, 'github.com/microsoft/playwright');
    await device.press({res: 'org.chromium.webview_shell:id/url_field'}, 'Enter');

    // Work with WebView's page as usual.
    const page = await webview.page();
    console.log(await page.title());

    // Close the device.
    await device.close();
  });
});
```

**Describe the bug**
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/42484209/164407307-3f953c4b-101f-4540-aa1e-cc44044081f8.png">

I already install android emulator via Android Studio as well as successfully start Google Chrome via adb shell command on terminal. However, my script returns error as image above when I run my script. Can anyone support me on this?

**Comment by linhanh512** [comment]
I have just upgrade my Node to 17+ though, it returned the same error. Please see my VS terminal for my Node update
<img width="1380" alt="Screen Shot 2022-04-21 at 23 10 05" src="https://user-images.githubusercontent.com/42484209/164504683-cc280e45-1bbb-48e2-acf6-69b41b5a4837.png">

**Comment by yury-s** [comment]
> I have just upgrade my Node to 17+ though, it returned the same error.

The error is introduced by changes in Node 17, the workaround Max suggested is to downgrade to Node 16 or earlier. Can you give it a try with Node 16?

**Comment by linhanh512** [comment]
have downgraded Node JS and run script successfully. Thanks guys <3
