### ISSUE TITLE
[BUG] The global PlaywrightTestConfig "viewport" setting is not applied

### ISSUE THREAD

**Issue by sevgeek** [microsoft/playwright#13673]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows
- Node.js version: 14.17.3
- Browser: Chromium

**Code Snippets**

My `PlaywrightTestConfig`:

```javascript
const config: PlaywrightTestConfig = {
  testDir: "./tests",
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: "html",
  use: {
    actionTimeout: 0,
    baseURL: process.env.PLAYWRIGHT_BASE_URL,
    browserName: "chromium",
    headless: true,
    trace: "on-first-retry",
    /* Set viewport settings for each tests */
    viewport: { width: 2000, height: 1000 },
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    }
  ],
};
```

My simple test:

```javascript
import { test, expect } from "@playwright/test";

test("Visit home page", async ({ page }) => {
  await page.goto("/");
  const h1 = await page.locator("h1");
  await expect(h1).toHaveText("Header");
});
```

**Describe the bug**

The global setting of `viewport` in `PlaywrightTestConfig` does not affect my test. 
My test also runs in a standard viewport of 1280 x 720.
If I set viewport setting inside my test, the test is running in installed viewport, as expected.
```javascript
test.use({ viewport: { width: 2000, height: 1000 } });
```
Screenshot of incorrect behavior:
![image](https://user-images.githubusercontent.com/60958933/164421454-fc3bfe69-b54c-4935-8dd2-73bec8742964.png)

Please help solve the problem of applying the `PlaywrightTestConfig` `viewport` setting! Thanks!

**Comment by yury-s** [comment]
`devices["Desktop Chrome"]` contains `viewport` definition which overrides your global config value, change the config to this:

```js
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 2000, height: 1000 },
      },
    }
  ],
```

**Comment by jmk0317** [comment]
If the 'global' setting for viewport should be applied to all 'projects' then this is still considered a bug. Why was it closed? Because a 'workaround' was suggested? The 'global' setting does now work in my tests using playwright version 1.22.2.

**Comment by ktxxt** [comment]
@jmk0317 

> If the 'global' setting for viewport should be applied to all 'projects' then this is still considered a bug. Why was it closed? Because a 'workaround' was suggested? The 'global' setting does now work in my tests using playwright version 1.22.2.

Totally agree!

I used this approach for if you have multiple `projects` ->


```js
// Global setting
const viewport = {
  width: 1920,
  height: 1080,
}

const config = { 
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
}

config.projects.forEach((project) => {
  project.use = {
    ...project.use,
    viewport,
  }
})

module.exports = config
```

It will add the defined `viewport` to all projects.

**Comment by ammoradi** [comment]
I confirm the issue still exists (using `"@playwright/test": "1.43.0"`) and needs some attention.

**Comment by AlexanderHritsun** [comment]
Relevant for 1.45 also. In my case that workaround: 
projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 2000, height: 1000 },
      },
    }
  ],
  
  doesn't work!

**Comment by AlexanderHritsun** [comment]
> Relevant for 1.45 also. In my case that workaround:
> 
> ```
> projects: [
>     {
>       name: "chromium",
>       use: {
>         ...devices["Desktop Chrome"],
>         viewport: { width: 2000, height: 1000 },
>       },
>     }
>   ],
> ```
> 
> doesn't work!

Aha, so my tests require to open a new browser page, and this page always opens in the small window! This is my config:

```
use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.BASE_URL || 'https://develop.icnow.app/',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'retain-on-failure',
    actionTimeout: 15 * 1000,
    viewport: { width: 2000, height: 1000 }
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], viewport: { width: 2000, height: 1000 } }
    }]

```

**Comment by tibioneh** [comment]
Again, why is this issue closed as it's clearly valid?

**Comment by vdineva** [comment]
I'm still having this issue with v1.52.0 of playwright

**Comment by alexandermirzoyan** [comment]
https://playwright.dev/docs/emulation#viewport

Attaching documentation link to configure viewports per device.
