### ISSUE TITLE
[BUG] Global options not working with simple test case

### ISSUE THREAD

**Issue by Marcelo00** [microsoft/playwright#13683]
**Context:**
- Playwright Version: 1.21
- Operating System: Linux
- Node.js version: v16.14.1
- Browser: Chromium

## System:
 - OS: Linux 5.17 openSUSE Tumbleweed 20220404
 - Memory: 4.66 GB / 15.29 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.1 - /usr/bin/node
 - npm: 8.5.0 - /usr/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Code Snippet**

I have the following three files in a `src` folder:

test-main.test.ts
```typescript
import { test } from "@playwright/test";

test("basic test", async ({ context }) => {
  const page = await context.newPage();
  await page.goto("https://google.com");
  await page.waitForTimeout(31 * 1000);
});
```

playwright.config.ts
```typescript
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  reporter: "list",
  testDir: "./src",
  timeout: 60 * 1000,
  globalSetup: require.resolve("./global-setup"),
};
export default config;
```

global-setup.ts
```typescript
import { chromium, FullConfig } from "@playwright/test";

async function globalSetup(config: FullConfig) {
  const baseURL = "http://google.de//";
  const storageStatepath = "storageState.json";
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto(baseURL);
  await page.click("#gksS1d");
  await page.fill("#identifierId", id);
  await page.click("#identifierNext");
  await page.fill("#password", password);
  await page.click("#passwordNext");
  await page.context().storageState({ path: storageStatepath });
  await browser.close();
}

export default globalSetup;
```

**Describe the bug**

I should not need to authenticate in the test case as I use the global setup to do so (see https://playwright.dev/docs/test-advanced#global-setup-and-teardown).  However, the pop up for log in still occur in the test case.

This bug is may be related to https://github.com/microsoft/playwright/issues/13681

**Comment by yury-s** [comment]
> I should not need to authenticate in the test case as I use the global setup to do so (see https://playwright.dev/docs/test-advanced#global-setup-and-teardown). However, the pop up for log in still occur in the test case.

You should also specify in the config that the contexts should be initialized with the saved storage state, something along these lines:

```js
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  reporter: "list",
  testDir: "./src",
  timeout: 60 * 1000,
  globalSetup: require.resolve("./global-setup"),
  use: {
    storageState: 'storageState.json', // This has to point to the storage state prepared in the global setup.
  },
};
export default config;
```

**Comment by Marcelo00** [comment]
I changed the` global-setup.ts` to match the the documentation:
```typescript
import { chromium, FullConfig } from "@playwright/test";

async function globalSetup(config: FullConfig) {
  const { baseURL, storageState } = config.projects[0].use;
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto(baseURL);
  await page.click("#L2AGLb");
  await page.context().storageState({ path: storageState as string });
  await browser.close();
}

export default globalSetup;
```

The `playwright.config.ts` is:
```typescript
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  reporter: "list",
  testDir: "./src",
  timeout: 60 * 1000,
  globalSetup: require.resolve("./global-setup"),
  use: {
    storageState: "storageState.json",
    baseURL: "https://google.com",
  },
};
export default config;
```

The `test-main.test.ts` is:
```typescript
import { test } from "@playwright/test";

test("basic test", async ({ page }) => {
  await page.goto("https://google.com");
  await page.waitForTimeout(31 * 1000);
});
```
However, this does not work as intended. In the test case, the `div` for accapting the cookies should not occur as we already accepted it in the global options.

**Comment by yury-s** [comment]
> However, this does not work as intended. In the test case, the `div` for accepting the cookies should not occur as we already accepted it in the global options.

**Comment by Marcelo00** [comment]
I also tested this with a `beforeAll`-function:
```typescript
let storageState;

test.beforeAll(async ({}) => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto("https://google.com");
  await page.click("#L2AGLb");
  storageState = await page.context().storageState();
  await browser.close();
});

test("basic test", async ({ context }) => {
  context.addCookies(storageState.cookies);
  const page = await context.newPage();
  await page.goto("https://google.com");
});
```

In this case, the test itself worked perfectly and the `div` did not occur. Thus, I would say that something is not working with the global setup. 

It also seems that it is not executed at the first place as I have a logging statement which is not getting printed.

**Comment by yury-s** [comment]
> It also seems that it is not executed in the first place as I have a logging statement which is not getting printed.
> 
> The problem also occurs with a different site I need to work with.

If it's not executed then there will be no storage state saved. I tried your example above and it did work (global setup was executed). May be the problem is around `globalSetup: require.resolve("./global-setup"),` line and your project file structure, try replacing it with `globalSetup: "./global-setup",`

**Comment by Marcelo00** [comment]
This unfortunately does not help. The usage of `require.resolve()` is also in the [docs](https://playwright.dev/docs/test-advanced#global-setup-and-teardown).

**Comment by pavelfeldman** [comment]
There is at least one bug in the config:

```js
use: {
    storageState: 'storageState.json', // Short name is relative to config.
}
```

```js
await page.context().storageState({ path: storageState as string }); // Short name is relative to cwd.
```

If those don't match it won't work. You can always check your filesystem for this storage and validate it.

**Comment by Marcelo00** [comment]
Thanks @pavelfeldman :)

I moved the config file from the src folder to the root folder and it worked as expected. Also the problem with the timeout in #13681 is solved with this small fix. 

It would be great if the explanation could be mentioned in the docs.

**Comment by pavelfeldman** [comment]
I believe we docent that short paths in config are resolved relative to the config and the rest is default Node behavior. I'll think about the ways we can improve the docs!
