### ISSUE TITLE
[BUG] Global timeout not working for simple test case

### ISSUE THREAD

**Issue by Marcelo00** [microsoft/playwright#13681]
**Context:**
- Playwright Version: 1.21
- Operating System: Linux
- Node.js version: v16.14.1
- Browser: Chromium

## System:
 - OS: Linux 5.17 openSUSE Tumbleweed 20220404
 - Memory: 4.66 GB / 15.29 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.1 - /usr/bin/node
 - npm: 8.5.0 - /usr/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Code Snippet**

I have the following two files in a `src` folder:

test-main.test.ts
```typescript
import { test } from "@playwright/test";

test("basic test", async ({ context }) => {
  const page = await context.newPage();
  await page.goto("https://google.com");
  await page.waitForTimeout(31 * 1000);
});
```

playwright.config.ts
```typescript
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  reporter: "list",
  testDir: "./src",
  timeout: 60 * 1000,
};
export default config;
```

**Describe the bug**

The global timeout is not applied to the test. Running `npx playwright test` will lead to the error `Timeout of 30000ms exceeded.`. 

This bug is may be related to https://github.com/microsoft/playwright/issues/13683

**Comment by yury-s** [comment]
Global timeout is set via [`globalTimeout`](https://playwright.dev/docs/api/class-testconfig#test-config-global-timeout) option, [`timeout`](https://playwright.dev/docs/api/class-testconfig#test-config-timeout) controls per-test time budget, see [this page](https://playwright.dev/docs/test-timeouts) for consolidated information about all timeout options that playwright test supports.

**Comment by Marcelo00** [comment]
I meant the timeout option specified in the config above - the per-test timeout. The term `globalTimeout` was not correctly used, sorry. 
There is no default `globalTimeout`. Consequently,  the error would suggest that it fails due to the per-test timeout is exceeded. This should not be the case with above config.
