### ISSUE TITLE
[Feature]Case conversion between different languages

### ISSUE THREAD

**Issue by includeios** [microsoft/playwright#13698]
We all know , A very powerful feature of playwright is that it supports multiple languages, which allows developers in different roles to choose the language they most familiar with to write the case.  so i think Is it possible to have a compiler, let javascript's case become python's case, so on.

The background is that one of our engineering, frontend team and testing teams each maintain a playwright project because we have a different focus on the case and a different familiar language, but we hope our cases can be used each other to some extent. so i raised such an issue, thank you

**Comment by yury-s** [comment]
Closing the bug as there are no plans to support such conversion.
