### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by michelebyman** [microsoft/playwright#13699]
**Context:**
- Playwright Version: 1.14.1
- Operating System: Mac
- Node.js version: 16.14.0
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

const cookieObj = {
  name: "Bearer",
  value: token,
  url: "http://localhost:4000",
}

test.beforeAll(async ({ browser }) => {
  const page = await browser.newPage()
  const context = await browser.newContext()
  await context.addCookies([cookieObj])

  await page.goto(`/#/`, { waitUntil: "networkidle", timeout: 60 * 1000 })

})
```

**Describe the bug**

I try to set a cookie but it does not show up in dev tools 
I have tried this:
console.log(await context.cookies())
and it logs the cookie

**Comment by yury-s** [comment]
What is the full url your are navigating to?

**Comment by michelebyman** [comment]
> What is the full url your are navigating to?

"https://localhost:4000"

**Comment by michelebyman** [comment]
``` TypeScript
const cookieObj = {
  name: "Bearer",
  value: token,
  domain: "localhost",
  path: "/",
}

 const context = await browser.newContext()
  const page = await context.newPage()
  await context.addCookies([cookieObj])
```

This solved the problem and now I see the cookie in dev tools

**Comment by yury-s** [comment]
> ```ts
>  const context = await browser.newContext()
>  const page = await context.newPage()
>  await context.addCookies([cookieObj])
> ```
> 
> This solved the problem and now I see the cookie in dev tools

Oh, it makes sense, I missed the fact that you create the page using browser.newPage, that method is a shortcut for creating a new page in a new context, so the code before was equivalent to:

```js
test.beforeAll(async ({ browser }) => {
  const context1 = await browser.newContext()
  const page = await context1.newPage()

  const context = await browser.newContext()
  await context.addCookies([cookieObj])

  await page.goto(`/#/`, { waitUntil: "networkidle", timeout: 60 * 1000 })

})
```
i.e. the cookies were added to a different context.

**Comment by michelebyman** [comment]
@yury-s do you mind renaming the issue for future references, 'how to add cookie in playwright' ?
