### ISSUE TITLE
[Question] Playwright using real Chrome via Selenium Grid 4 via Docker compose

### ISSUE THREAD

**Issue by aquacode** [microsoft/playwright#13692]
I set up a Selenium Grid version 4 running Chrome browsers in order to leverage the native Chrome browser media codecs.

Based on this page https://playwright.dev/docs/selenium-grid I used version 4 since version 3 stated that "Selenium 4 hub exposes this capability, while Selenium 3 does not.

This means that Selenium 3 is supported in a best-effort manner, where Playwright tries to connect to the grid node directly. Grid nodes must be directly accessible from the machine that runs Playwright."

I read the above to mean that my local Playwright script will connect directly to the Selenium node running the browser if I use Selenium 3, but will access via the Selenium hub if I use version 4.

However, it seems that in spite of the above document Playwright is establishing a ws connection directly to the Selenium node (Chrome) that the hub allocates.

I'm writing to confirm that all Selenium nodes must be public hosts/IPs in order to interact with a Selenium node/browser or do I perhaps have something misconfigured?

I'm running my Selenium grid via a Docker compose script where the hub and all nodes are on the same, very robust, host machine.

**Comment by yury-s** [comment]
Playwright will connect to whatever Selenium Grid Hub returns in `se:cdp` capability. From [this comment](https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392) it looks like it may need to be configured on the hub end to make it return hub address instead of direct node endpoint.

**Comment by aquacode** [comment]
Thank you, the link you shared [here](https://github.com/SeleniumHQ/selenium/issues/9202#issuecomment-799435392) has the solution
