### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by kommuswamy** [microsoft/playwright#13709]
Can we continue execution even after one test fail. With dependent tests.
Where i created page thro4 browser on test.beforeall block

**Comment by kommuswamy** [comment]
test.beforeAll(async ({ browser }) => {
  const page = await context.newPage();
  await page.goto('https://example.com');
});

**Comment by yury-s** [comment]
> Can we continue execution even after one test fail. With dependent tests.

No, once a test fails the worker that ran it is closed and other tests will never use it, see [this description](https://playwright.dev/docs/next/test-retries). When new worker starts running (or retrying) a test it will run [beforeAll](https://playwright.dev/docs/next/api/class-test#test-before-all) again if  it hasn't run in that worker yet.
