### ISSUE TITLE
[Question] What does the PLAYWRIGHT_DOWNLOAD_HOST address need to return

### ISSUE THREAD

**Issue by hangboss1761** [microsoft/playwright#13718]
I want to use `PLAYWRIGHT_DOWNLOAD_HOST="192.0.2.1"` configuration. 

What does `192.0.2.1` need to return to work properly

**Comment by rwoll** [comment]
Browsers (specific to your platform) and some supporting libraries (ffmpeg). `192.0.2.1` in the docs (https://playwright.dev/docs/browsers#download-from-artifact-repository) is just a sample address. If you're using the `PLAYWRIGHT_DOWNLOAD_HOST` env var, you'd likely want to point it at an internal artifact repository that mirrors/caches what's being download from `https://playwright.azureedge.net`.

For most users this environment variable is not needed as it's fine to download the browsers from the default, Microsoft CDN. What's your use case?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by nagamanickamm** [comment]
@pavelfeldman : Could you please let us know, if we can create an upstream for https://playwright.azureedge.net in internal azure artifacts and playwright install will pull from my azure url?
