### ISSUE TITLE
[BUG] PWDEBUG doesn't disable timeout

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [microsoft/playwright#13715]
**Context:**

## System:
 - OS: Windows 10 10.0.22000
 - Memory: 47.35 GB / 63.87 GB
## Binaries:
 - Node: 14.19.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.17 - C:\Program Files\nodejs\yarn.CMD
 - npm: 6.14.16 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\Windows\system32\bash.EXE
## npmPackages:
 - playwright: 1.21.0 => 1.21.0

**Code Snippet**

```
cross-env PWDEBUG=1 yarn playwright test playwright-chrome
```

**Describe the bug**

Running and pausing playwright like this results in a timeout. Setting timeout to 0 manually works.

Parts of the docs that say that it shouldn't be like this:
https://playwright.dev/docs/inspector#open-playwright-inspector
https://playwright.dev/docs/debug#run-in-debug-mode

**Comment by yury-s** [comment]
Did you try without `cross-env`? Can you share the code that we can run to reproduce it?

**Comment by s-h-a-d-o-w** [comment]
I just tried to reproduce it using your example project (`npm init playwright@latest new-project`) but couldn't.

In my project, showing the inspector (or not) works, it's only the timeout that's a problem. That's why I assumed that it's definitely a bug.
My bad...
