### ISSUE TITLE
[Question]page.goto: SSL connect error And  browserType.launch: Browser closed.

### ISSUE THREAD

**Issue by PRT-weixuejian** [microsoft/playwright#13726]
$ node -v16.14.2
$ npm -v8.5.0
"@playwright/test": "^1.21.1"
Operating System: Windows

I just do this on cmd:
1. npm init playwright@latest new-project
Getting started with writing end-to-end tests with Playwright:
Initializing project in 'new-project'
√ Do you want to use TypeScript or JavaScript? · TypeScript
√ Where to put your end-to-end tests? · tests
√ Add a GitHub Actions workflow? (Y/n) · true

2. cd new-project
3. npx playwright test

will result in the following error
Running 75 tests using 3 workers
  1) [webkit] › example.spec.ts:14:3 › New Todo › should allow me to add todo items ================

    page.goto: SSL connect error
    =========================== logs ===========================
    navigating to "https://demo.playwright.dev/todomvc", waiting until "load"
    ============================================================

      2 |
      3 | test.beforeEach(async ({ page }) => {
    > 4 |   await page.goto('https://demo.playwright.dev/todomvc');
        |              ^
      5 | });
      6 |
      7 | const TODO_ITEMS = [

        at C:\Users\xxxxxxxx\Desktop\TEST2\new-project\tests\example.spec.ts:4:14

  2) [chromium] › example.spec.ts:14:3 › New Todo › should allow me to add todo items ==============

    browserType.launch: Browser closed.
    ==================== Browser output: ====================
    <launching> C:\Users\xxxxxxxx\AppData\Local\ms-playwright\chromium-1000\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\xxxxxxxx\AppData\Local\Temp\playwright_chromiumdev_profile-t57l5T --remote-debugging-pipe --no-startup-window
    <launched> pid=11092
    =========================== logs ===========================
    <launching> C:\Users\xxxxxx\AppData\Local\ms-playwright\chromium-1000\chrome-win\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\xxxxxxxx\AppData\Local\Temp\playwright_chromiumdev_profile-t57l5T --remote-debugging-pipe --no-startup-window
    <launched> pid=11092
    ============================================================

is something wrong with my computer settings? how to fix it

**Comment by PRT-weixuejian** [comment]
thank you for your answer
1.it maybe caused by the proxy, have any idea?
C:\Users\xxxxx>curl https://demo.playwright.dev/todomvc
curl: (4) Unsupported proxy 'https://xxxxx:xxxxx!@xxxxx.co.jp:8080', libcurl is built without the HTTPS-proxy support.

2.test is fail, i do nothing, just excute:
npm init playwright@latest new-project    →  success
cd new-project
npx playwright test      →  fail :   meassage is write before(browserType.launch: Browser closed...,browserType.launch: Browser closed.)

**Comment by pavelfeldman** [comment]
Could you be behind some corporate proxy?

**Comment by PRT-weixuejian** [comment]
I need to apply, is it enough to add some proxy? could you tell me the proxy.

**Comment by pavelfeldman** [comment]
I was asking if your network is behind some proxy already.
