### ISSUE TITLE
How can I define the timeout for waitForSelector globally?

### ISSUE THREAD

**Issue by leonheess** [microsoft/playwright#13723]
I know you can pass a timeout to `waitForSelector` and the default should be `30_000`. How can I define in my `playwright.config.ts` that the timeout for all `waitForSelector`-calls should be x?

I can do `page.setDefaultTimeout(timeout)` but that isn't global enough.

**Comment by pavelfeldman** [comment]
`{ use: { actionTimeout: 10000 } }`, see https://playwright.dev/docs/next/test-timeouts

**Comment by leonheess** [comment]
It wasn't clear from the documentation that `setDefaultTimeout` is targeting the same timeout value as `actionTimeout`. Thank you!
