### ISSUE TITLE
[Question] test timeout

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#13721]
In tools like testcafe, we are able to run a test that runs till its completion without specifying a test timeout. is there a specific configuration that we can set in playwright to ensure that the test runs till completion without specifying timeouts please ? the reason for asking this question is because we are trying to automate a legacy application using playwright and page load times are indeterminate. Ideally we would like the tests to run until they either complete/pass or fail. 

Could you kindly help ?

**Comment by pavelfeldman** [comment]
These are the timeout settings: https://playwright.dev/docs/next/test-timeouts. Most of the time, passing 0 will disable timeout. I'm not sure it'll work for you, because Playwright is waiting for elements to be actionable and if you remove all the timeouts, it'll wait forever. So the test will not complete or pass, it'll just hang forever.

**Comment by pavelfeldman** [comment]
So I would suggest to increase the default test timeout instead.

**Comment by harir5** [comment]
@pavelfeldman - thank you for your comment. if i increase the timeout to say 2 mins as opposed to 30 seconds, playwright would still wait for 2 minutes if the locator is not visible and the test would therefore wait for 2 mins (for example, on a non-existant/hidden element) before failing due to a timeout. is there a way to fail the test if the locator is not found and thereby fail the test immediately please?

**Comment by pavelfeldman** [comment]
> is there a way to fail page.locator() if the element is not found and thereby fail the test immediately please

you could ```expect(await page.locator('...').isVisible());```. isVisible does not wait, it'll return true or false right away and expect will make the test fail. Do not confuse with `await expect().toBeVisible()` - that one would be waiting.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
