### ISSUE TITLE
[BUG] WebKit crash

### ISSUE THREAD

**Issue by PascalvdHoek** [microsoft/playwright#13722]
**Context:**
- Playwright Version:1.20 1.21
- Operating System: Mac M1
- Node.js version: IDK, its about the docker image. Local is 16.13.0
- Browser: WebKit
- Extra: [any specific details about your environment]

**Describe the bug**
We are using playwright on a large project, currently for e2e tests and visual regression. The screenshots are test in the docker environments of Playwright. Since version 1.20 my m1 macbook crashes on the webkit steps.  As you see below. Our fix was to downgrade to v1.19 again. But I think its a bug. 

Some details maybe help, 
The devices we are testing on are: iphone-11-webkit, desktop-webkit desktopchrome and iphone-11-chrome(custom). All webkit ones crashes and chrome are fine. 

![image](https://user-images.githubusercontent.com/56636556/165034240-89f66ef4-6c2e-48a2-8a9b-86aa30b1ce9a.png)

**Comment by yury-s** [comment]
Can you share a project with a test that crashes webkit?

**Comment by pavelfeldman** [comment]
... or if you could tr-run the same tests on 1.21 with env variable `DEBUG=pw:browser` it would also help.

**Comment by PascalvdHoek** [comment]
The Debug=Pw:browser command gives an error. 
`"start-server-and-test 'nx run storybook-bundle:build  && http-server dist/storybook/storybook-bundle -s -p 4400' 4400 'docker run --rm --name playwright-vr -it -p 4400:4400 -v $(pwd):/work/ -w /work/ mcr.microsoft.com/playwright:v1.21.1-focal DEBUG=pw:browser npx playwright test libs/components/ui-tag/src/lib/visual-regression/*.vr-spec.ts --config=playwright.config.ts`

And the error is:  
`Error: Command failed with exit code 127: docker run --rm --name playwright-vr -it -p 4400:4400 -v $(pwd):/work/ -w /work/ mcr.microsoft.com/playwright:v1.21.1-focal DEBUG=pw:browser npx playwright test libs/components/ui-tag/src/lib/visual-regression/*.vr-spec.ts --config=playwright.config.ts
    at makeError (/Users/pascalvandenhoek/valk-nx/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/Users/pascalvandenhoek/valk-nx/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  shortMessage: 'Command failed with exit code 127: docker run --rm --name playwright-vr -it -p 4400:4400 -v $(pwd):/work/ -w /work/ mcr.microsoft.com/playwright:v1.21.1-focal DEBUG=pw:browser npx playwright test libs/components/ui-tag/src/lib/visual-regression/*.vr-spec.ts --config=playwright.config.ts',
  command: 'docker run --rm --name playwright-vr -it -p 4400:4400 -v $(pwd):/work/ -w /work/ mcr.microsoft.com/playwright:v1.21.1-focal DEBUG=pw:browser npx playwright test libs/components/ui-tag/src/lib/visual-regression/*.vr-spec.ts --config=playwright.config.ts',
  escapedCommand: '"docker run --rm --name playwright-vr -it -p 4400:4400 -v $(pwd):/work/ -w /work/ mcr.microsoft.com/playwright:v1.21.1-focal DEBUG=pw:browser npx playwright test libs/components/ui-tag/src/lib/visual-regression/*.vr-spec.ts --config=playwright.config.ts"',
  exitCode: 127,
  signal: undefined,
  signalDescription: undefined,
  stdout: undefined,
  stderr: undefined,
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false`

**Comment by pavelfeldman** [comment]
This all does not look like Playwright output, I'm not sure what `Error: Command failed with exit code 127` is and what is throwing it. I assume everything works locally and only fails in Docker?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
