### ISSUE TITLE
[Feature] Support Ubuntu 22.04

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#13738]
Blocked by:
- https://github.com/actions/virtual-environments/issues/5428

Requires the following changes so far:
- [x] Chromium
- [x] WebKit
- [x] Firefox
- [x] Docs changes that we support it https://github.com/microsoft/playwright/pull/14588
- [x] Regenerate required dependencies https://github.com/microsoft/playwright/pull/14588
- [x] Add tests on e.g. GitHub Actions https://github.com/microsoft/playwright/pull/14741
- [x] Evaluate if we want to add Ubuntu 22 Docker images as well
- [x] add Docker image arm64 amd64 tests
- [x] ~~don't suggest focal in the docs anymore, suggest 22.~~
- [x] Support GitHub Action on Ubuntu 22 https://github.com/microsoft/playwright-github-action/pull/66

**Comment by jgilbert2017** [comment]
fyi- ubuntu 22.x install-deps fails. it seems as some packages were renamed:

ttf-unifont -> fonts-unifont
ttf-ubuntu-font-family -> fonts-freefont-ttf

that's as far as i get before the script aborts.

**Comment by ddelange** [comment]
For the failures on jammy (22.04LTS):

```
#15 7.794 E: Unable to locate package libenchant1c2a
#15 7.794 E: Unable to locate package libicu66
#15 7.794 E: Unable to locate package libvpx6
#15 7.794 E: Unable to locate package libwebp6
#15 7.794 E: Package 'ttf-unifont' has no installation candidate
#15 7.794 E: Package 'ttf-ubuntu-font-family' has no installation candidate
```

I did some digging:

libenchant1c2a [>](https://packages.ubuntu.com/search?suite=jammy&arch=any&searchon=names&keywords=libenchant) libenchant-2-2
libicu66 [>](https://packages.ubuntu.com/search?suite=jammy&arch=any&searchon=names&keywords=libicu) libicu70
libvpx6 [>](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=libvpx&searchon=names) libvpx7
libwebp6 [>](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=libwebp&searchon=names) libwebp7
ttf-unifont [>](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=unifont&searchon=names) fonts-unifont
ttf-ubuntu-font-family [>](https://packages.ubuntu.com/search?suite=jammy&section=all&arch=any&keywords=sans+serif+font+set&searchon=all) fonts-ubuntu *discrepancy from @jgilbert2017, matched here on package description

**Comment by mxschmitt** [comment]
Thats done! For further issues, please file new issues on GitHub. It gets released in 1.23.

**Comment by mwxxhdb** [comment]
When will version 1.23 be released? Or is there a way to run playwright on Ubuntu 22.04 ahead of time?

**Comment by mxschmitt** [comment]
> When will version 1.23 be released? Or is there a way to run playwright on Ubuntu 22.04 ahead of time? I can't wait to try out such a great framework. 🙂

`npm i @playwright/test@next`

or

`npm i playwright@next`

We'll release in 1-2 weeks I guess.

**Comment by sdwvit** [comment]
If you are like me googling for your error, here is what helped me (I am on 22.04.1 lts based kde neon which playwright reports as unsupported OS):
https://github.com/microsoft/playwright/issues/11122#issuecomment-1426622416

**Comment by AnthonyPhan** [comment]
I'm still receiving the following errors when running `npx playwright install --with-deps` inside a Github action on Ubuntu-latest (22.04.2).

```
Run npx playwright install --with-deps
  npx playwright install --with-deps
  shell: /usr/bin/bash -e {0}
Installing dependencies...
Switching to root user to install dependencies...
Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Get:[2](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:2) http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Get:[3](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:3) http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [107 kB]
Get:[4](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:5) http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:[5](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:6) https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [30[6](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:7)5 B]
Get:6 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [948 kB]
Get:[7](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:8) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [205 kB]
Get:[8](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:9) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [13.7 kB]
Get:[9](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:10) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [684 kB]
Get:[10](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:11) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [107 kB]
Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [890 kB]
Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [177 kB]
Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [18.1 kB]
Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [24.1 kB]
Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [6312 B]
Hit:16 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [692 kB]
Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [142 kB]
Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [8832 B]
Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [642 kB]
Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [100 kB]
Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [710 kB]
Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [115 kB]
Get:24 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [13.8 kB]
Get:25 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [19.4 kB]
Get:26 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [4068 B]
Get:27 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [55.2 kB]
Get:28 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [[11](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:12).7 kB]
Get:29 https://packages.microsoft.com/ubuntu/[22](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:23).04/prod jammy/main armhf Packages [63[24](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:25) B]
Fetched 59[30](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:31) kB in 1s (4750 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package libicu66 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-unifont' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libenchant1c2a
E: Package 'libicu66' has no installation candidate
E: Unable to locate package libvpx6
E: Unable to locate package libwebp6
Failed to install browsers
Error: Installation process exited with code: 100
Error: Process completed with exit code 1.
```

**Comment by mxschmitt** [comment]
> I'm still receiving the following errors when running `npx playwright install --with-deps` inside a Github action on Ubuntu-latest (22.04.2).
> 
> 
> 
> ```
> 
> Run npx playwright install --with-deps
> 
>   npx playwright install --with-deps
> 
>   shell: /usr/bin/bash -e {0}
> 
> Installing dependencies...
> 
> Switching to root user to install dependencies...
> 
> Hit:1 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
> 
> Get:[2](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:2) http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
> 
> Get:[3](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:3) http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease [107 kB]
> 
> Get:[4](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:5) http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
> 
> Get:[5](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:6) https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease [30[6](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:7)5 B]
> 
> Get:6 http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [948 kB]
> 
> Get:[7](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:8) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [205 kB]
> 
> Get:[8](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:9) http://azure.archive.ubuntu.com/ubuntu jammy-updates/main amd64 c-n-f Metadata [13.7 kB]
> 
> Get:[9](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:10) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [684 kB]
> 
> Get:[10](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:11) http://azure.archive.ubuntu.com/ubuntu jammy-updates/restricted Translation-en [107 kB]
> 
> Get:11 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [890 kB]
> 
> Get:12 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [177 kB]
> 
> Get:13 http://azure.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 c-n-f Metadata [18.1 kB]
> 
> Get:14 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [24.1 kB]
> 
> Get:15 http://azure.archive.ubuntu.com/ubuntu jammy-updates/multiverse Translation-en [6312 B]
> 
> Hit:16 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
> 
> Get:17 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [692 kB]
> 
> Get:18 http://azure.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [142 kB]
> 
> Get:19 http://azure.archive.ubuntu.com/ubuntu jammy-security/main amd64 c-n-f Metadata [8832 B]
> 
> Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [642 kB]
> 
> Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [100 kB]
> 
> Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [710 kB]
> 
> Get:23 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [115 kB]
> 
> Get:24 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 c-n-f Metadata [13.8 kB]
> 
> Get:25 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [19.4 kB]
> 
> Get:26 http://azure.archive.ubuntu.com/ubuntu jammy-security/multiverse Translation-en [4068 B]
> 
> Get:27 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main amd64 Packages [55.2 kB]
> 
> Get:28 https://packages.microsoft.com/ubuntu/22.04/prod jammy/main arm64 Packages [[11](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:12).7 kB]
> 
> Get:29 https://packages.microsoft.com/ubuntu/[22](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:23).04/prod jammy/main armhf Packages [63[24](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:25) B]
> 
> Fetched 59[30](https://github.com/AnthonyPhan/StaticAppCiTest/actions/runs/4460629175/jobs/7833935853?pr=11#step:5:31) kB in 1s (4750 kB/s)
> 
> Reading package lists...
> 
> Reading package lists...
> 
> Building dependency tree...
> 
> Reading state information...
> 
> Package ttf-ubuntu-font-family is not available, but is referred to by another package.
> 
> This may mean that the package is missing, has been obsoleted, or
> 
> is only available from another source
> 
> 
> 
> Package ttf-unifont is not available, but is referred to by another package.
> 
> This may mean that the package is missing, has been obsoleted, or
> 
> is only available from another source
> 
> However the following packages replace it:
> 
>   fonts-unifont
> 
> 
> 
> Package libicu66 is not available, but is referred to by another package.
> 
> This may mean that the package is missing, has been obsoleted, or
> 
> is only available from another source
> 
> 
> 
> E: Package 'ttf-unifont' has no installation candidate
> 
> E: Package 'ttf-ubuntu-font-family' has no installation candidate
> 
> E: Unable to locate package libenchant1c2a
> 
> E: Package 'libicu66' has no installation candidate
> 
> E: Unable to locate package libvpx6
> 
> E: Unable to locate package libwebp6
> 
> Failed to install browsers
> 
> Error: Installation process exited with code: 100
> 
> Error: Process completed with exit code 1.
> 
> ```

Try to upgrade Playwright.

**Comment by AnthonyPhan** [comment]
Im running playwright in a Github action that does not have a pre-existing install of PlayWright (see workflow example below).

Doesnt `npx playwright install --with-deps` install the latest version?

``` yaml
end_to_end_test:
    name: End to End Test
    # Runs on an ubuntu runner
    needs: [build_and_deploy_job]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright@1.31.2 install --with-deps
    - name: Build production build
      run: npm run build
    - name: Run your tests
      run: npm run playwright_test
```

**Comment by AnthonyPhan** [comment]
apologies, it looks like the issue was I had playwright defined in my package.json as well so when running playwright it was using the old version in there that does not support the the latest ubuntu

**Comment by aghasemi** [comment]
Hello,

Now with Ubuntu 24.04 around the corner, may I ask please if there is already a plan or roadmap for when we can have it in a Playwright workflow?
Many thanks

**Comment by AvantGov** [comment]
I was still hitting a similar issue above, where the installation fails shortly after what appears to be the output of a `sudo apt upgrade` from the `sudo npx install playwright --with-deps` running. Installation failed: exited with error code 1. Found that removing the `--with-deps` flag allowed browsers to install correctly. Would it be possible to update the documentation to reflect this use case?
