### ISSUE TITLE
[BUG] Screenshot from locator or full page does not show scrollbars even with --hide-scrollbars ignored

### ISSUE THREAD

**Issue by philiphendry** [microsoft/playwright#13734]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Windows 10 
- .NET version: .NET 6.0
- Browser: Chrome

**Code Snippet**

I've used the following code in a .net 6.0 console app to demonstrate the problem :

```cs
using Microsoft.Playwright;
using System.Threading.Tasks;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions { 
    IgnoreDefaultArgs = new[] { "--hide-scrollbars" } 
});
var page = await browser.NewPageAsync();
await page.GotoAsync(@"c:\temp\demo.html");
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "page-screenshot.png" });
await page.ScreenshotAsync(new PageScreenshotOptions { Path = "full-page-screenshot.png", FullPage = true });
var locator = page.Locator("main");
await locator.WaitForAsync();
await locator.ScreenshotAsync(new LocatorScreenshotOptions { Path = "locator-screenshot.png" });
```

and the following demo.html:

```html
<html>
    <head>
        <style>
            .child {
                background-color: lightgreen;
                width: 100px;
                height: 400px;
            }

            main {
                display: flex;
                height: 4000px;
            }
            
            .container {
                display: flex;
                height: 200px;
                padding: 10px;
                overflow-y: auto;
            }
        </style>
    </head>
    <body>
        <main>
            <div class="container">
              <div class="child">First</div>
            </div>
            <div class="container">
              <div class="child">Second</div>
            </div>
          </main>
    </body>
</html>
```

**Describe the bug**

I've specified `--hide-scrollbars` in the `IgnoreDefaultArgs` options so that scrollbars are captured in the screenshots. The test page contains two scrolling divs and the page itself is very long and scrolls in order to replicate the issues I'm having with our own screenshotting of production code (specifically we render components multiple times in a style guide that tests our CSS is applying correctly.) I've then captured a screenshot of the page, full page and a specific area of the page. The page screenshot captures exactly what I expect and all three scrollbars can be seen:

![image](https://user-images.githubusercontent.com/705830/165104179-11bfd308-cd5c-4913-b3c4-cd9a73586009.png)

However, I'm expecting that both the full page and locator screenshots will contain two scrollbars (one on each scrolling region) but they're missing. This is a problem in our tests as we use a locator to isolate a specific portion of a page and screenshot and this captures the full height of the page under test.

**Comment by philiphendry** [comment]
Is this related in anyway to #4295? Is this confirmed as a bug or on the backlog as a feature request?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
