### ISSUE TITLE
[BUG] postinstall script does not work in mono repo

### ISSUE THREAD

**Issue by leonheess** [microsoft/playwright#13730]
**Context:**
- Playwright Version: 1.17.0
- Operating System: Windows
- Node.js version: LTS

We use a postinstall-script to install playwright like so:

    "postinstall": "playwright install"

It works fine until we integrate the package into a mono repo built with yarn workspaces. When using `yarn` globally it correctly installs the package but then the postinstall is called it results in:

```
error C:\monorepo\node_modules\@mic\e2e-tests: Command failed.
Exit code: 1
Command: playwright install
Arguments:
Directory: C:\monorepo\node_modules\@mic\e2e-tests
Output:
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'C:\monorepo\node_modules\node_modules\@playwright\test\cli.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)  
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
```

However, if I install globally and then go inside the package and manually call the postinstall, it works fine.

**Comment by pavelfeldman** [comment]
Could you create a sample repository where we could reproduce it? I've seen people use Playwright with the workspaces w/o issues. Also, please update to at least 1.21.1!

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
