### ISSUE TITLE
[Feature] ability to use try and catch with waitForNavigation

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#13733]
its would be nice if we can use try and catch for waitForNavigation, the current behaviour now that if waitForNavigation timedout the session will be terminated so test will not move to the catch block 

```
    async handleNavigation() {
        try {
            await this.page.waitForNavigation({ timeout: 40000 })            
        } catch  {
            console.log('Navigation is timedout, page will be reloaded!')
            await this.page.reload({ waitUntil: "load" })                        
        }
    }

    async clickApplyButton() {
        await Promise.all([
            await this.applyButton.click(),
            await this.handleNavigation()
        ]);
        return this;
    }
```

<img width="599" alt="Screenshot 2022-04-25 at 16 24 26" src="https://user-images.githubusercontent.com/32042806/165109253-1418ff82-7a79-436e-9686-a9cf846d3807.png">

steps to reproduce:

set very short timeout to ensure failure and wrap waitForNavigation in try and catch block

**Comment by pavelfeldman** [comment]
You seem to have extra awaits inside your Promise.all

**Comment by amrsa1** [comment]
> You seem to have extra awaits inside your Promise.all

Yea have tried also without, got same result

**Comment by pavelfeldman** [comment]
You should first start waiting for the event and then click, like described here: https://playwright.dev/docs/next/navigations#asynchronous-navigation

```js
await Promise.all([
    this.handleNavigation()
    this.applyButton.click(),
]);
```

the order of calls and whether you await them changes the semantics of your program.

**Comment by pavelfeldman** [comment]
The logic of you app is also confusing a little - you wait for 40 seconds for click to perform navigation (can something else in your script trigger the navigation?), but more importantly you are reloading your page while clicking if 40 seconds timed out, which is an unusual user scenario. I wonder if there is a better solution to what you are solving.

**Comment by amrsa1** [comment]
> 

yes i have tried this as well.

why im using this logic, because i have found that sometimes PW stall and page keep loading for infinite time, so thats why i wanted to add try and catch block so when waitForNavigation timed out due to this stall, catch block will force reload the page, i think the problem that waitForNavigation will terminate the browser if it fail without doing reload in the catch block

**Comment by pavelfeldman** [comment]
> why im using this logic, because i have found that sometimes PW stall and page keep loading for infinite time,

That would be highly unusual, can you file it as a bug instead?

Otherwise, there is no point in reloading the page if waitForNavigation did not happen - it simply means that there was no navigation, so waitForNavigation is sitting there waiting for it. Are you sure there is a navigation? Also, it is very rare that you need that waitForNavigation at all, try removing it and seeing if your script runs.

**Comment by amrsa1** [comment]
> > why im using this logic, because i have found that sometimes PW stall and page keep loading for infinite time,
> 
> That would be highly unusual, can you file it as a bug instead?
> 
> Otherwise, there is no point in reloading the page if waitForNavigation did not happen - it simply means that there was no navigation, so waitForNavigation is sitting there waiting for it. Are you sure there is a navigation? Also, it is very rare that you need that waitForNavigation at all, try removing it and seeing if your script runs.

Yes basically its a submit button , once i click it some query parameters are bieng set and page is reloaded 

I have found in codegen tool, whenever there is mavigation waitForNavigation is added in promise anyway will try to remove it, for now its flaky some time it work sometimes not

**Comment by pavelfeldman** [comment]
You don't need `waitForNavigation` in general, sorry our codegen tool confused you.

**Comment by amrsa1** [comment]
> You don't need `waitForNavigation` in general, sorry our codegen tool confused you.

Actually its needed, if i disable it PW will be to fast, so it will keep clicking on the other item without waiting page to navigate.

in my scenario each click on certain button will add a query params to the url which will cause re-rendering for the page, so i guess wait for navigation is needed, but the problem sometimes the page stall and not making the navigation so thats why i need to use try and catch block, i have noticed it in many occasion with different repos

**Comment by pavelfeldman** [comment]
Making waitForNavigation not wait in comes cases will be an uphill battle. You can try using `waitForURL` - it is idempotent and is much easier to deal with, you just call it after you clicked and expect the url / pattern that should take place.
