### ISSUE TITLE
[BUG]TypeError: Cannot read properties of undefined (reading 'locator')Error occurs in async method where locator is awaited in class methods.When the same lines of code runned on test.spec.ts it works perfectly. Unless the method is statically defined

### ISSUE THREAD

**Issue by oytunerdd** [microsoft/playwright#13751]
**Context:**
- Playwright Version: [1.19- 1.21]
- Operating System: [Windows]
- Node.js version: [v16.14.0]

**Code Snippet**
 example:

```async benefitMethod() {
const text = await this.page.locator('element').textContent();
console.log(text);
```

**Comment by DvDream** [comment]
What is element?

**Comment by oytunerdd** [comment]
Some selector which is not hard to find as I said. If you use these lines under TestScenario.spec.ts it works but if you use this as method under a class and summon it in TestScenario.spec.ts then it throws the TypeError.
So i mean it is not related with the selector string.

**Comment by oytunerdd** [comment]
A different approach I tried after thinking from another perspective,

I defined the method under Member.ts as a static async function and gave the page object as a parameter to the method, as below and 
```
static async  benefitListContains(page) {
const text= await this.page.locator("//section[@id='benefits']//loadable/div[1]/benefit-list-loadable/benefit-list//benefit-overview/div[@Class='container-fluid py-2']/div/div[3]").textContent();
console.log("TEXT FAILS = "+ text); 
return text;
}
```

and call it on Test.spec.ts;

```
const text = Member.benefitListContains(page);
console.log("TEXT PASS" + text); ==> this way it works // TEXT PASS value

```

**Comment by pavelfeldman** [comment]
> Cannot read properties of undefined (reading 'locator')

This would typically mean that the `page` in `page.locator()` is a promise that you did not await.

> I am not a fan of using these types of long locators

You are using long XPath selectors that among other things traverse dom and use children ordinals. These selectors are going again the selector [best practices](https://playwright.dev/docs/selectors#best-practices) and won't be resilient.

**Comment by oytunerdd** [comment]
Hello Pavel, 

The same locator is working under Test.spec.ts file (Playwright test file ) which is the test it self but when it is used in a class method dynamically it doesn't. The static version of that method works as well for this specific inquiry.

**Comment by oytunerdd** [comment]
Hi @pavelfeldman 
You are right, I made a mistake while transfering here, but I seem to have found why this is happening.
In my class ;

```
import { Page } from 'playwright';


export class Member {

  page:Page;


 constructor(page) {
    this.page = page;
  }
// here using page as parameter internally
  async benefitListContains(page) {
  const text = await page.locator("//section[@id='benefits']//loadable/div[1]/benefit-list-loadable/benefit-list//benefit-overview/div[@class='container-fluid py-2']/div/div[3]").textContent();
       console.log("TEXT 123 = "+  text);//const frame =await this.page.locator("[title='Benefits'] loadable").textContent();
    return text;
}

// here this.page ( class variable ) is used then the error is occuring
  async benefitListContains() {
    const text = await this.page.locator("//section[@id='benefits']//loadable/div[1]/benefit-list-loadable/benefit-list//benefit-overview/div[@class='container-fluid py-2']/div/div[3]").textContent();
    console.log("TEXT 123 = "+  text);//const frame =await this.page.locator("[title='Benefits'] loadable").textContent();
return text;
}
}
```



Is this still about page object assignment ?

**Comment by pavelfeldman** [comment]
You probably have another bug and you pass good `page` object into the method `benefitListContains(page)`, but you pass a bad `page` object when you do `new Member(page)`.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by oytunerdd** [comment]
Hello @pavelfeldman,

As you said that a bug in code. I guess you are right what I have been skipping is this test definitions are like acting as methods as well.

```
let member;

test.beforeAll(async ({backendURL,baseURL, browser}) => {
  member  = new Member();
});


test("Should successfully create a benefit entity on membership overview", async ({ }) => {  
    // member  = new Member();  should be used in here 
    console.log("Text will not be printed " + await member.benefit(page));
});

```
Here in this block for some other languages, first define the variable later initialize and then on an other scope, use methods etc. would work. That is why the error message is a TypeError. But in Playwright communication between test methods is not allowed. 
I had the thought of an idea where this usage is handled as globals. Global definition I can't use in here. Maybe giving them in test definitions as parameters would work.

Thank you for your support for me to figure out.

**Comment by anilpujaraofficial** [comment]
import { test } from "@playwright/test";
import { LoginPage } from "../../pages/login/login";
let loginP = new LoginPage();
test.describe("Login Module", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("");
  });
  test.only("Valid login", ({ page }) => {
    loginP.login("superadmin", "Midas@123");
  });
  test("Invalid login", ({ page }) => {
    loginP.login("superadmin", "Midas@123###");
  });
});

import { expect, Page } from "@playwright/test";
import { Commands } from "../../helpers/commands";
let commands = new Commands();
export class LoginPage {
  private page: Page;
  // xpath
  private username: string = "#username";
  private password: string = "#password";

  button(val: string) {
    return `button[data-cy='${val}']`;
  }

  login(username: string, password: string) {
    commands.inputField(this.username, username);
    commands.inputField(this.password, password);
    commands.clickButton(this.button("Submit"));
  }
}

import { Page } from "@playwright/test";

export class Commands {
  private page: Page;

  async inputField(xpath: string, value: string): Promise<void> {
    await this.page.locator(xpath).fill(value); // Interact with the page
  }

  async clickButton(xpath: string): Promise<void> {
    await this.page.locator(xpath).click(); // Interact with the page
  }
}
TypeError: Cannot read properties of undefined (reading 'locator') how can solve this problem @playwrightmachine
