### ISSUE TITLE
[Question] How to access iPhone 13 Pro Max screen in Playwright tests

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#13758]
How to access iPhone 13 Pro Max screen in Playwright tests

I am trying to run few webkit tests in  iPhone 13 Pro Max device.

I have raised a feature request previously, https://github.com/microsoft/playwright/issues/9150

But i can unable to see any devices in https://github.com/microsoft/playwright/blob/7ccdc5176ded3e76566b6f7981b6136cfcadd7b0/src/server/deviceDescriptors.ts

Below snippet opens the tests in fullscreen instead of iPhone13ProMax screen

@playwright/test": "^1.21.1"

```
// mobile.config.js

const { devices } = require('@playwright/test');

module.exports = {
  timeout: 40000,
  workers: 5,
  projects: [
    // iPhone 13 Pro Max tests use WebKit browser.
    {
      name: 'iPhone13ProMax',
      use: {
        browserName: 'webkit',
        headless: false,
        ...devices['iPhone 13 Pro Max'],
      },
    },

    // Galaxy tests use Chromium browser.
    {
      name: 'GalaxyNote3',
      use: {
        browserName: 'chromium',
        headless: false,
        ...devices['Galaxy Note 3 landscape'],
      },
    },

  ],
};



```

**Comment by MindaugasMateika** [comment]
Is this really a full config? Maybe you set screen size somewhere else? The device is defined in the descriptor - https://github.com/microsoft/playwright/blob/release-1.21/packages/playwright-core/src/server/deviceDescriptorsSource.json#L756-L770

**Comment by pavelfeldman** [comment]
> But i can unable to see any devices in https://github.com/microsoft/playwright/blob/7ccdc5176ded3e76566b6f7981b6136cfcadd7b0/src/server/deviceDescriptors.ts

You are looking at a revision from 1.5 years ago. It is there now...

**Comment by jithinjosejacob** [comment]
thanks,my bad i was looking at the old link, i have added the device name as per the latest change, and is working fine
