### ISSUE TITLE
[Question] Reuse api context across tests for API Testing

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#13755]
Can we create a api context in global setup for api and then reuse the context across tests/spec files for api 
testing .

**Actual**

currently i need to initialise the apiContext for every test/spec file.

test1 - create an apiContext1 - run api tests
test2 - create an apiContext2 - run api tests

**Expected**

Global setup - Initial context with the token/authentication (apiContext)

test1 - use apiContext
test2 - use apiContext
test3 - use apiContext

https://playwright.dev/docs/test-api-testing#sending-api-requests-from-ui-tests (edited)

**Comment by pavelfeldman** [comment]
There are several strategies of reusing the signed-in state, explained here: https://playwright.dev/docs/test-auth#reuse-signed-in-state

**Comment by jithinjosejacob** [comment]
Thanks, I could use - Sign in via API request for my use case as well.
