### ISSUE TITLE
[BUG] iPhone 11 Pro device on macOS renders too narrow in default size to show address bar

### ISSUE THREAD

**Issue by Llois41** [microsoft/playwright#13752]
**Context:**
- Playwright Version: 1.20.2
- Operating System: macOS
- Node.js version: 16.13.1
- Browser: Webkit (iPhone 11 Pro)

## System:
 - OS: macOS 12.3.1
## Binaries:
 - Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
 - Yarn: 3.1.1 - ~/.nvm/versions/node/v16.13.1/bin/yarn
 - npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm

`yarn playwright open --device="iPhone 11 Pro"`

**Describe the bug**

I want to open an iPhone Browser by running `yarn playwright open --device="iPhone 11 Pro"`.  On Windows and Linux it seems to work fine. On my Mac it will open, but it has just a too small width to show the address bar so I can't navigate to any URL unless I resize my window, which then will leave me with a browser wider than an `iPhone 11 Pro`. Using `iPhone 11` works fine. 

Why is that the case on Mac? I tested with M1 and Intel Mac and they both show the same behaviour.

iPhone 11 Pro default sized (Mac):
![image](https://user-images.githubusercontent.com/37102755/165251165-b4c324cd-5f55-4685-a111-9ee92070ea36.png)

iPhone 11 default sized (Mac):
<img width="415" alt="image" src="https://user-images.githubusercontent.com/37102755/165251311-d31f1c06-fcd7-4af7-aff0-873f2c56caef.png">

iPhone 11 Pro default sized (Linux):
![image](https://user-images.githubusercontent.com/37102755/165253958-c0b16d0b-454f-47ea-8624-25157c68e234.png)

**Comment by pavelfeldman** [comment]
While we are fixing it, you can pass url as a command line argument.

**Comment by Llois41** [comment]
> While we are fixing it, you can pass url as a command line argument.

Yeah I know, but this is not my use case of the browser. Thanks for the quick reply and hopefully the quick fix ;)
