### ISSUE TITLE
error Command "nx" not found while running webserver?

### ISSUE THREAD

**Issue by scharph** [microsoft/playwright#13763]
i try to use playwright with nx. Storybook is needed for running ui tests

My config:

```ts
webServer: {
    command:  'yarn nx run app:storybook --port 4201',
    timeout: 1500000,
    url: 'http://localhost:4201',
  },
```

When i run test with extensions, i get

```
Running 2 tests using 2 workers

[WebServer] warning package.json: No license field
[WebServer] error Command "nx" not found.
```
Error: Process from config.webServer was not able to start. Exit code: 1

Also "Execute Using Profile" isn't working 

any idea?

**Comment by pavelfeldman** [comment]
It appears that `nx` is not installed globally or locally?

**Comment by scharph** [comment]
local

```
yarn list | grep nx                                                                                   
- nx@13.10.2
```

global
```
❯ yarn global list
yarn global v1.22.18
info "nx@14.0.3" has binaries:
   - nx
Done in 0.12s.
```

**Comment by pavelfeldman** [comment]
Do other things work when you put them in `command`? Does `yarn nx run app:storybook --port 4201` work if you run it in the config folder?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by pauleustice** [comment]
I had the same issue. For future reference of anyone else that runs into this:

- `node_modules/.bin/nx your-command` (or variants with a relative root e.g. `../../`) doesn't work
- `cd ../../node_modules/.bin && nx your-command` doesn't work
- `npm run nx your-command` does work (you just need `"nx": "nx",` in your `package.json` scripts)
