### ISSUE TITLE
HTML reporter does not show errors on the stdout/stderr

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#13761]
Currently no output is shown at all.

**Comment by pavelfeldman** [comment]
Could you clarify what happens vs what's expected?

**Comment by mxschmitt** [comment]
I had a offline discussion with @dgozman that if you currently only use the `html` reporter and tests are failing nothing is shown at all inside the console, this is confusing and we had internal logic in place which then automatically added a reporter (IIRC dot) to display the console errors on the stderr.

(Debbie ran into that and our default config on create-playwright only adds the `html` reporter.)
