### ISSUE TITLE
[Question] - test.nofail(...)

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/playwright#13770]
Is it possible to mark a test as one that won't cause the CI to fail but you still want to run it.

For example, I am setting up some tests to run Lighthouse using the [playwright-lighthouse package](https://www.npmjs.com/package/playwright-lighthouse). Our site is not optimized yet so we get some bad scores in Lighthouse. I want to write our tests with the ability to have expectations of what our goal is. I want these tests to run during CI but I don't want them to fail the whole suite.

For example I would like to write a test that measures our Layout shifts score and do something like `expect(layoutShiftScore).toBeLessThan(0.1)`. Right now that test will fail but I still want to run it to start gathering data. 

I think I want something similar to Soft Assertions but I don't want the test to be marked as failed or the ability to mark a failed test as not contributing to if the suite as a whole passed or failed.

I couldn't find this feature. Is there a way to accomplish this today?

**Comment by rwoll** [comment]
Does `test.fail()` do what you want? It'll run the test, and expect the test to fail. If it suddenly starts passing (e.g. you fixed your lighthouse score), the runner will yell at you to remove the `.fail()`.

https://playwright.dev/docs/api/class-test#test-fail-1
