### ISSUE TITLE
[Question] always 401 Unauth on request.get

### ISSUE THREAD

**Issue by dadamsGS** [microsoft/playwright#13772]
I might be missing something with my api testing. This is testing that will take place on a backend repo.

I have a globalSetup retrieving an auth token from AWS Cognito (I have also written [a Medium post](https://medium.com/@dadamschi/preserve-authenticated-aws-cognito-state-in-playwright-822d01817989) around this). The auth token is saved to an environment variable. I verified the config is set correctly when my `use` config looks like the following:
```
use: {
    trace: 'retain-on-failure',
    // All requests we send go to this API endpoint.
    baseURL: `${process.env.BASE_URL}`,
    extraHTTPHeaders: {
      // Add authorization token to all requests.
      'Authorization': `Bearer ${process.env.API_TOKEN}`,
      'organization': `${process.env.TEST_ORG}`,
      'office': `${process.env.TEST_YARD}`
    },
  },
```
by adding `console.log(config)` in my test.

When I make the `request.get()` the response is 401 Unauthorized. I have similar requests in another (frontend) repo that do work with the extraHTTPHeaders added to a newContext; which is something I think I should not have to do when using just the request object like this:
```
test.describe('Create New Ticket', () => {
    test('using an existing customer', async ({ request }) => {
      const results = await request.get(`/tickets`);
      console.log(results)
    });
  });
```

What _is_ working is saving auth tokens to a storageState.json file then parsing that file in a beforeAll and is the alternate approach mentioned above:
```
import { test } from '@playwright/test';
const fs = require('fs')
  
test.describe('Create New Ticket', () => {
  test.beforeAll(async () => {
    let rawdata = fs.readFileSync('storageState.json');
    let storageState = JSON.parse(rawdata);
    storageState.origins[0].localStorage.forEach(object => {
      if(object.name.endsWith('idToken')) {
        global.idToken = object.value;
      }
    });
  });

  test('using an existing customer', async({request}) => {
    const results = await request.get(`/tickets`, {headers: {
        'Authorization': `Bearer ${global.idToken}`,
        'organization': 'flintstones',
        'office': 'barney'
      }});
    console.log(results)
  });
});
```

I am not a fan of this and am expecting extraHTTPHeaders to be applied to all requests such that I do not need to inline the headers object in the request.

Any help/guidance would be appreciated.

**Comment by dadamsGS** [comment]
I am having the same issue using a request.newContext() so I'll close this issue and assume it's my config/setup. For now.

**Comment by pavelfeldman** [comment]
Your global setup runs after your config is read, so the value ${process.env.API_TOKEN} that you specify in config is empty.

**Comment by dadamsGS** [comment]
Ah. Interesting. 

Can I get the config to read after globalSetup? Or is there a script that can be executed prior to the config being read?

**Comment by pavelfeldman** [comment]
I actually think I lied to you. So the sequence of the things is currently like this:
- config is read and global setup is executed.
- `process.env.API_TOKEN` is assigned in global setup
- tests start running in worker processes. they also import config and pick values from use: {}
- because those worker processes are child processes, they inherit the `process.env.API_TOKEN`, so they should read it fine.

Let's figure out what's broken here!

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by rmunn** [comment]
@dgozman - I believe #16005 is the same issue. I've included a repro which I managed to get boiled down to the bare minimum, so it should hopefully be pretty simple to isolate the cause and fix it.

**Comment by rmunn** [comment]
On further investigation, this may not have the same cause as #16005. But it's worth using the same technique (running a simple HTTP echo service) to investigate whether the `extraHTTPHeaders` from the config are actually being added to the request in `request.get`, or whether they're being ignored the way `httpCredentials` is being ignored in #16005.
