### ISSUE TITLE
[Question] Issue with Github actions and page initiated in BeforeAll

### ISSUE THREAD

**Issue by guillaumemeunier** [microsoft/playwright#13771]
I'm running a test where I'm going through three different URLs and then run the same kind of test on each page. I'm initiating the page in a beforeAll. 

When I run this test locally, it works like a charm. However, when it goes through Github actions, it fails on the second test but then work on a retry.

This is how the test looks like (I simplified it to reproduce the issue)

```
urlList.map(async (url: string) => {
  test.describe.only(`Review ${url}`, () => {
    test.beforeAll(async ({ browser }) => {
      context = await browser.newContext()
      page = await context.newPage()
      await page.goto(url, { timeout: 0 })
    })

    test('Reaching the page', async () => {
      await expect(page.locator('#hero')).toBeVisible()
    })
  })
})
```

Any idea of what could be triggering that weird behaviour?
This is the error I'm getting on Github:
`page.goto: net::ERR_TIMED_OUT at myURL`

<img width="1083" alt="image" src="https://user-images.githubusercontent.com/17547727/165347223-7a5c0a20-4db3-47c1-9978-0289adcf747f.png">

**Comment by pavelfeldman** [comment]
`net::ERR_TIMED_OUT` suggests that the underlying network connection timed out waiting for the response. The timeout that you pass only controls how long to wait for the page to load, if the underlying TCP connection times out, the navigation is considered unrecoverable. Something strange is happening to your network, could it be that the server has not been started yet?

**Comment by guillaumemeunier** [comment]
The first test / url works so I would assume the server started, it always fail on the second one @pavelfeldman , which makes the issue very odd.
Also, it does not happen if I don't use a beforeAll() to set up the page.

**Comment by guillaumemeunier** [comment]
@pavelfeldman I was able to figure out what causes this even though I am not sure to understand why this happened in the first place. 

I simplified my test to only use `page = await browser.newPage() ` instead of setting up the context and then the page and it works. 🤔

**Comment by pavelfeldman** [comment]
`page = await browser.newPage()` is the same as what you had, so that is weird indeed. Looks like some intermittent network issue on the host environment to me.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
