### ISSUE TITLE
[Feature] Allow to define an interval / wait period between expect.poll assertions

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#13775]
In one of the latest versions of Playwright the `expect.poll`-function was introduced to allow to poll for a specific assertion. This is really a great addition to Playwright. 

Only I would like to request an enhancement to this functionality to delay a breathing period between assertion checks. For example, when you are querying for a status change via an API endpoint then it can be beneficial to wait a short period between assertion checks to not hit the API server too often or it might not beneficial to continuously execute this assertion.

In my case I would like to check if a revocation of permissions has completed, and it doesn't make sense to check the assertion of a period of 60 seconds continuously. A bit of breathing or waiting time of like 5 seconds would help to ease everything

**Comment by mstepin** [comment]
Is there any easy way to tell which Playwright version any given fix or change was released in? I'm assuming this one is part of 1.22.X?? I have no easy way to determine this

**Comment by mxschmitt** [comment]
This should be part of 1.22 yes.

**Comment by mstepin** [comment]
Thanks for that @mxschmitt . Is there any easy way to tell which PRs / Fixes are in which version? I couldn't find any version tags anywhere.
