### ISSUE TITLE
no tests shown when not destructured

### ISSUE THREAD

**Issue by alexn-s** [microsoft/playwright#13784]
## meta data

npm versions
```json
 "playwright": "^1.21.1"
 "@playwright/test": "^1.21.1",
```

extension version `v0.2.3`

os `windows 11`

vscode info:
```txt
Version: 1.66.2 (user setup)
Commit: dfd34e8260c270da74b5c2d86d61aee4b6d56977
Date: 2022-04-11T07:46:01.075Z
Electron: 17.2.0
Chromium: 98.0.4758.109
Node.js: 16.13.0
V8: 9.8.177.11-electron.0
OS: Windows_NT x64 10.0.22000
```

## description
when destructuring the object in the test the extension finds the tests and displays them in the sidebar & displays the play icons to start the test.

however, when i than dont destructure the object and refresh the playwright tests (cmd -> Tests: Playwright Refresh Tests) no tests at all are shown in that file

### does not work
```ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});


// test('basic test - second', async ({page}) => {
test('basic test - second', async (args) => {
  const { page } = args;

  // args.screenshot = 'on';

  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

![image](https://user-images.githubusercontent.com/60710873/165471811-9386d54e-33a8-4412-88ad-68eae7ab6e5e.png)

### works

```ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});


test('basic test - second', async ({page}) => {
// test('basic test - second', async (args) => {
  // const { page } = args;

  // args.screenshot = 'on';

  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

![image](https://user-images.githubusercontent.com/60710873/165472750-92b90e36-ba83-4e30-ae83-59fe924ec469.png)

**Comment by pavelfeldman** [comment]
Yeah, that's how Playwright works. Fixtures must be destructured.

**Comment by alexn-s** [comment]
so its by design? i have never encountered something to my knowledge where it was mandatory.
thanks

**Comment by pavelfeldman** [comment]
Yes, by design, we use it to be able to tell which fixtures need to be set up!
