### ISSUE TITLE
[Question]How Do I Specify chromium --user-data-dir --remote-debugging-pipe When the Codegen Recordes a Script?

### ISSUE THREAD

**Issue by cuinima** [microsoft/playwright#13783]
How Do I Specify chromium --user-data-dir --remote-debugging-pipe When the Codegen Recordes a Script?
>python -m playwright codegen created a whole new environment, which was not what I wanted.
I still need to remove --disable-extensions.

**Comment by pavelfeldman** [comment]
You can't. What's your use case?
