### ISSUE TITLE
[BUG] possible bug in polling? Or we're using it wrong

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [microsoft/playwright#13789]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows
- Node.js version: 16
- Browser: Chromium
- Extra: none

I've drilled it down to the most basic test with expect.poll but I can't get that one working either.
If I do:

    await expect.poll(() => {
      return 200;
    }, {
      // Custom error message
      message: 'make sure mathematics work', // custom error message
      // Poll for 10 seconds; defaults to 5 seconds. Pass 0 to disable timeout.
      timeout: 10000,
    }).toBe(200);

I get a fail and as output:

Error: expect(received).toBe(expected) // Object.is equality

Expected: 200
Received: [Function anonymous]
single test --- Error: expect(received).toBe(expected) // Object.is equality

Expected: 200
Received: [Function anonymous]

so the received is a function? I'm not following. Probably I'm missing something basic?

**Comment by pavelfeldman** [comment]
The error above suggests that you ran

```
await expect(() => { return 200; }).toBe(200);
```

there is no custom message, no polling. Could it be that you are using some other version of expect? Could you provide a self-contained test?

**Comment by LanderBeeuwsaert** [comment]
I've made a minimal test file:

![image](https://user-images.githubusercontent.com/1098243/165673390-d262bd6b-c1f1-46e1-824c-1288ba4cdf36.png)

gives as output:
![image](https://user-images.githubusercontent.com/1098243/165673458-ea4d2019-c2e2-472a-95f6-cbdb6ceb764b.png)

**Comment by LanderBeeuwsaert** [comment]
So IMO I'm using the playwright jest expect? Maybe it's something with the ESM Loading?

**Comment by pavelfeldman** [comment]
Ah, you are using expect outside the test, it won't work that way.

**Comment by LanderBeeuwsaert** [comment]
ah ok, that explains it then. Any technical limitation why this is not possible? Or this is just something that is not in scope?
