### ISSUE TITLE
apiRequestContext.post: getaddrinfo ENOTFOUND per-context

### ISSUE THREAD

**Issue by DemBackfisch** [microsoft/playwright#13785]
Hello,
I am using Playwright v1.19.1 and had the following issue: `apiRequestContext.post: getaddrinfo ENOTFOUND per-context`.
The URL I am making the POST request to is totally fine and should be easily resolvable.
Not sure if this is important, but the error occured with node v14.16.1, however with v16.10.0 I didnt get that issue, but might just be a coincidence.
Please let me know, what this issue could be caused by.
Thank you!

**Comment by pavelfeldman** [comment]
It looks like you are using per-context proxy for your browser and you specified `per-context` as a proxy. API testing picked it up and does not know what to do with it. If you specify `per-context` in your settings, you should always provide proxy value every time you create context.

**Comment by DemBackfisch** [comment]
Ah yea that makes sense, wasn´t setting it always but yea there was a bug. Thank you for your help!
