### ISSUE TITLE
APIRequestContext features

### ISSUE THREAD

**Issue by i23591326** [microsoft/playwright#13795]
It would be great to have following features at APIRequest

1.  generics for APIRequestContext methods and for APIResponse, like `APIRequestContext.get<T>(url, options): Promise<APIResponse<T>>` since it's often much more convenient than using assert or casting `any` to desired type manually
2. ability to set default value for `failOnStatusCode` globally, in beforeEach block or per context instance, since it's often to be used with .json() in order to get JS response body, and json conversion would often get xml error and throw error trying to parse it with not informative message like `SyntaxError: Unexpected token < in JSON at position 0` instead of actuial API error description  
3. introduce APIRequestContext methods overloads. It's quite often for testing we don't care about post response except it successful, but when we do we often want to get response body, and it's not quite convenient additionally `await APIResponse.json()`. So it might be useful to be able to define what kind of response do we want to get. For example, Angular httpClient uses  options.observe property for this purpose https://github.com/angular/angular/blob/master/packages/common/http/src/client.ts#L1209

sorry if some feature requests duplicate, originally I was looking only for failOnStatusCode, but got a little carried away 🙂

**Comment by pavelfeldman** [comment]
> generics for APIRequestContext methods and for APIResponse, like APIRequestContext.get<T>(url, options): Promise<APIResponse<T>> since it's often much more convenient than using assert or casting any to desired type manually

Where would be T used?

> ability to set default value for `failOnStatusCode` globally, in beforeEach block or per context instance

We can add that, we can use this issue to track it.

> introduce APIRequestContext methods overloads.

You can always introduce a helper method on your side that would do get + json, so you are suggesting that we include it into the library, is that correct?

**Comment by i23591326** [comment]
>Where would be T used?

T would be the response body, i.e. APIResponse.json(): Promise<T> 

>... so you are suggesting that we include it into the library, is that correct?

yep, it seems to me that this feature would be used quite often, so it would be great to have this out of the box

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
