### ISSUE TITLE
[BUG] Target closed on click

### ISSUE THREAD

**Issue by jasonatball** [microsoft/playwright#13799]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Linux
- Node.js version: 14
- Browser: Firefox
- Extra: Run in github action

**Describe the bug**
Selector was found according to the log but it was never clicked and I get a 'Target closed'.

Original run was here: https://github.com/BallAerospace/COSMOS/actions/runs/2234549674/attempts/1

**Comment by jasonatball** [comment]
This is the trace.trace file. I think the full zip is too big for Github.
[trace.txt](https://github.com/microsoft/playwright/files/8575521/trace.txt)

**Comment by jasonatball** [comment]
![image](https://user-images.githubusercontent.com/28577787/165595251-383c6459-524f-499c-816d-0e67aa4ca9fc.png)

**Comment by jasonatball** [comment]
I have a PlaywrightTestConfig timeout set to 120000. Is that the issue here? Is playwright closing my test? I'm a little confused as to this timeout because sometimes my tests are allowed to run longer than that and sometimes not. How is that enforced?

**Comment by pavelfeldman** [comment]
Typically this means that the test timed out while trying to click. You can see that your test took exactly 2 minutes (on timeline), so yes, it was terminated after 120000ms (also 3 minutes).

**Comment by jasonatball** [comment]
Ok sorry for the noise. I assume I use `slow()` (https://playwright.dev/docs/test-timeouts#set-timeout-for-a-single-test) to increase this?

**Comment by jasonatball** [comment]
Also perhaps you could add a message to the log indicating the timeout was reached. That would help debug an issue like this. Thanks for playwright!
