### ISSUE TITLE
How to select element within parent element containing text[Question]

### ISSUE THREAD

**Issue by pietraniktx** [microsoft/playwright#13791]
Hi, 

So I run into a problem with selecting an element within another element that contains text.

I have a list item, within the list item i have a link with a text and a button. So I try to do this like:

```
const listItem = this.page.locator('data-test-id=list-item:has-text('someText')') 
const button = listItem.locator("data-test-id=button")
await button.click()
 
```
But it does not seem to work. I tried looking for a similar case but with not many results. Could anyone help?

**Comment by pavelfeldman** [comment]
`data-test-id=list-item:has-text('someText')` is not a valid selector. has-text is only supported with CSS selectors. Also, data-test-id should be unique and you are suggesting it is the same for multiple list entries.

You can do this:
`page.locator('li', { hasText: 'someText' }).locator('button')`

This would select button in the row that has someText.

**Comment by pietraniktx** [comment]
Hey, it works! Thank you very much
