### ISSUE TITLE
[BUG] Unable to import typescript interfaces when es modules are used

### ISSUE THREAD

**Issue by domsew** [microsoft/playwright#13798]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows 10
- Node.js version: 16.13.0

**Describe the bug**

Setting`"type": "module"` in `package.json` causes import errors in typescript files. When I use `import { test, expect, Page } from '@playwright/test';` then I get `SyntaxError: The requested module '@playwright/test' does not provide an export named 'Page'`. A workaround is to use `import type { Page } from '@playwright/test';` but this is inconvinient.

**Comment by pavelfeldman** [comment]
That's how Typescript interoperates with ESM. You can also do:

`import { test, expect, type Page } from '@playwright/test'`

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
