### ISSUE TITLE
adding support to run tests on android chrome and ios safari

### ISSUE THREAD

**Issue by pandey-shubh** [microsoft/playwright#13792]
we need to test our application running on android chrome and ios safari by when could we expect this to happen? This feature would be helping everybody trying to make use of playwright

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1122. There is no timeline on this.

**Comment by WaliAblikim** [comment]
@pavelfeldman  after this ticket closed, it means that playwright can be run test in mobile (android chrome and IOS safari ),
am i understanding is right?
