### ISSUE TITLE
[Question] Github Actions: `webServer` config for localhost?

### ISSUE THREAD

**Issue by fredboyle** [microsoft/playwright#13796]
We're attempting to setup CI automation for Playwright in Github Actions. However there appears to be issues with starting a localhost server when in the Github Actions context.

What is the recommended setup for starting a localhost web server for Playwright to access when in the Github Actions context?

Thanks.

**Comment by pavelfeldman** [comment]
We do that in most of our tests, it should just work. What are the issues with starting a localhost server on GHA?

**Comment by fredboyle** [comment]
@pavelfeldman Tests always fail, on every run for all browsers.

No reports of being unable to find the existing snapshot files, only failure of `toMatchSnapshot`.
Trace reports show successful rendering of the test.

Attaching report bundle from latest attempt.
[playwright-report.zip](https://github.com/microsoft/playwright/files/8577424/playwright-report.zip)

**Comment by pavelfeldman** [comment]
This means you did not add the snapshot files into the repo...

**Comment by fredboyle** [comment]
They are in the repo, which is why this is confusing.

![Screen Shot 2022-04-27 at 13 33 49](https://user-images.githubusercontent.com/32829/165626204-b99ba9ae-e86c-4e42-a09c-b776e4aff7f2.png)

**Comment by pavelfeldman** [comment]
It is saying that `src/components/close-button/close-button.spec.js-snapshots/close-button-default-chromium-linux.png` is missing, your screenshot is truncated, are sure it is there?

**Comment by fredboyle** [comment]
Ugh I'm a dodo bird. I completely spaced on the platform specific file naming convention.

Which now means I need to generate new baseline snapshot in one OS (macOS) that will be run on another (linux). How do I do that or remove the whole platform specific nature of snapshots and make them OS agnostic?

**Comment by pavelfeldman** [comment]
OS agnostic will mismatch, you should run them on the same platform all the time. We are working on utilities that would help you generate those expectations remotely. But for now, you can either do it manually (run your workflow, archive generated expectations and commit them), or use Docker to achieve consistent environment. Thats a lot of work, but that is how cross-platform screenshot tests work.

**Comment by fredboyle** [comment]
@pavelfeldman Thanks for your help in clearing my dodo brain. 👍
