### ISSUE TITLE
[Question] Playwright 1.20.2 - Keep updated browsers versions without updating playwright?

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#13790]
Hi, at the moment I have Playwright 1.20.2 installed . I need to keep all the browsers I may need updated to the most recent version offered by the most recent version of Playwright, without changing Playwright version. How could I achieve that? Is there any command I can use? thanks :)

**Comment by MindaugasMateika** [comment]
Browser binaries are tied to the Playwright version. You can't have the latest browser binaries with the older Playwright version. Reference - https://playwright.dev/docs/browsers

**Comment by pavelfeldman** [comment]
Closing as per above.
