### ISSUE TITLE
[BUG] fixture failures in tests using `fixme` is reported as failed though on retry fixture executed without errors

### ISSUE THREAD

**Issue by vigneshrajsb** [microsoft/playwright#13805]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Mac
- Node.js version: 16.14.2
- Browser: All

**Code Snippet**

**Repo to replicate:** https://github.com/vigneshrajsb/playwright-fixme-report-issue

```
npm install 
npx playwright test
```

**Describe the bug**

When a test uses `test.fixme()` at the beginning, the execution immediately stops and exits but the fixtures are executed(as expected).

When a test with `setup` fixture fails in the first run but passes in a retry for a `fixme` test, the HTML report still reports the test as failure.

**Expected:**
On retry as the fixture execution was successful, the reporter should flag the test as `flaky` similar to tests without `fixme`

<img width="996" alt="image" src="https://user-images.githubusercontent.com/13482555/165646732-dcc8b128-00a7-45f3-bb2c-dff40e1bd4e3.png">
<img width="1046" alt="image" src="https://user-images.githubusercontent.com/13482555/165646738-a0dcc7d8-372a-4405-ae8f-a612d05eaa48.png">

Should the reporter flag this test as `flaky`?

**Comment by pavelfeldman** [comment]
I actually don't think we should have retried the fixme test. It has failed, but that's ok since it has a fixme.

**Comment by dgozman** [comment]
The issue here is that execution failed before the `test.fixme()` call had a chance to run. This makes the test a proper "failure". Try using [this variant of `test.fixme`](https://playwright.dev/docs/api/class-test#test-fixme-1) to avoid the problem and let me know if that helps.

**Comment by vigneshrajsb** [comment]
thank you @dgozman @pavelfeldman !

**Comment by vigneshrajsb** [comment]
something to note when using `test.fixme('name', async () =>` is `eslint` seems to think its not a test block

```
test.fixme("a test to fix", async ()  => {
  expect(1).toBe(1)
})
```

has error
```
Expect must be inside of a test block.eslint[jest/no-standalone-expect](https://github.com/jest-community/eslint-plugin-jest/blob/v23.20.0/docs/rules/no-standalone-expect.md)
```

we can add the ignore rules for this but I guess this test with fixme should be identified as a test block ideally

**Comment by dgozman** [comment]
It seems like you are using jest-specific rules (`jest/no-standalone-expect`), so I'm not surprised it does not work with Playwright 😄

**Comment by vigneshrajsb** [comment]
ah!! gotchu!! apologies.. yeah i think it makes sense now.. we will override the lint rules for the playwright tests
