### ISSUE TITLE
[BUG] Default viewport config doesn't set viewport to selected size

### ISSUE THREAD

**Issue by Torvaldi** [microsoft/playwright#13815]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows & ArchLinux
- Node.js version: 16.14.2
- Browser: Chromium, Firefox

**Code Snippet**

```typescript
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";

const config: PlaywrightTestConfig = {
  testDir: "./tests",
  timeout: 30 * 1000,
  expect: {
    timeout: 5000,
  },
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [["junit", { outputFile: "results.xml" }]],
  use: {
    actionTimeout: 0,
    baseURL: "localhost",

    trace: "on",

    video: {
      mode: "on",
      size: {
        width: 1920,
        height: 1080,
      },
    },
    viewport: {
      width: 1920,
      height: 1080,
    },
  },

  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },

    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },
  ],
};

export default config;
```

**Describe the bug**

Hello,
I'm trying to set a default viewport for my test to 1920x1080, but when i'm putting this configuration into `playwright.config.ts` file, the current viewport is always 800x800. The unique workaround I found is to set manualy the viewport size of each page on my test file by doing `await page.setViewportSize({ width: 1920, height: 1080 });`. 

Did I miss something?

**Comment by Torvaldi** [comment]
I thought global viewport size set the default viewport size, but I should have put it in project configuration like this:
```typescript
  projects: [
    {
       name: "firefox",
       use: {
         ...devices["Desktop Firefox"],
         viewport: {
           width: 1920,
           height: 1080,
         },
       },
     },
  ],
```
Anyway, what is the purpose of the global viewport size?

**Comment by pavelfeldman** [comment]
Global viewport size is the default value to use for all the projects. The problem here is that the following code in your project overwrites it (device includes viewport size):

```js
use: {
  ...devices["Desktop Chrome"],
}
```

You can replace `...devices` with `browserName: 'firefox'` if you only want to set the browser and not define the whole preset that includes browser, user agent, viewport. etc/

**Comment by Torvaldi** [comment]
> Global viewport size is the default value to use for all the projects. The problem here is that the following code in your project overwrites it (device includes viewport size):
> 
> ```js
> use: {
>   ...devices["Desktop Chrome"],
> }
> ```
> 
> You can replace `...devices` with `browserName: 'firefox'` if you only want to set the browser and not define the whole preset that includes browser, user agent, viewport. etc/

Oh, I see! Thank you very much for this explanation.

**Comment by fwextensions** [comment]
For a Playwright newbie like myself, this is very confusing, as the default `playwright.config.js` file that's installed spreads the full device object.  Yet the docs show an example of setting the viewport globally.  The default config therefore guarantees this will be ignored, leading to lots of frustrating searching for a fix.

**Comment by tsvetkovamaria** [comment]
Maybe it's worth mentioning it in the docs, as it took me a while to figure out the reason of viewport not applied.

**Comment by blitzd** [comment]
Spent several hours yesterday trying to resolve this. +1 for mentioning it in the docs.

**Comment by ProxiBlue** [comment]
You can just override the devices viewports in your projects as well....by placing them after devices.

```
use: {
        ...devices['Desktop Chrome'],
        viewport: {
          width: 1920,
          height: 1080,
        },
      },
```

**Comment by helloromero** [comment]
Not sure what I am doing wrong 😂

1: Following [the docs](https://playwright.dev/docs/api/class-page#page-set-viewport-size) and setting page.setViewportSize() like this:

```
const page = await browser.newPage();
await page.setViewportSize({
  width: 640,
  height: 480,
});
await page.goto('https://example.com');
````

takes screenshots at random sizes like 560 × 1000.

2: Following [the docs](https://playwright.dev/docs/api/class-testoptions#test-options-viewport) and updating playwright.config.js with the viewport property like this:

```
 viewport: {
    width: 1920,
    height: 1080,
},
```

takes screenshots at random sizes like 1820 × 2011.

What's actually going on? I just want it to follow the width's I set

**Comment by user1568891** [comment]
> Global viewport size is the default value to use for all the projects. The problem here is that the following code in your project overwrites it (device includes viewport size):
> 
> use: {
>   ...devices["Desktop Chrome"],
> }
> You can replace `...devices` with `browserName: 'firefox'` if you only want to set the browser and not define the whole preset that includes browser, user agent, viewport. etc/

So should the new code be this?

use: {
   browserName: 'firefox',
 }
