### ISSUE TITLE
[BUG] The locator shoudln't fail if the dom isn't as it expects.

### ISSUE THREAD

**Issue by tchaton** [microsoft/playwright#13813]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

```
(Pdb) locator = view_page.frame_locator("iframe").locator('img')
(Pdb) locator.wait_for(timeout=1 * 1000)
*** playwright._impl._api_types.Error: DOMException: Failed to execute 'querySelectorAll' on 'Document': '.example.cursor-pointer.p-2.rounded.bg-gray-50.dark:bg-gray-700' is not a valid selector.
    at query (<anonymous>:1589:41)
    at <anonymous>:1599:7
    at SelectorEvaluatorImpl._cached (<anonymous>:1387:20)
    at SelectorEvaluatorImpl._queryCSS (<anonymous>:1586:17)
    at SelectorEvaluatorImpl._querySimple (<anonymous>:1463:19)
    at <anonymous>:1421:29
    at SelectorEvaluatorImpl._cached (<anonymous>:1387:20)
    at SelectorEvaluatorImpl.query (<anonymous>:1416:19)
    at Object.query (<anonymous>:1621:44)
    at <anonymous>:1579:21
```

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
Your code uses valid selectors `"iframe"` and `"img"`.
```py
locator = view_page.frame_locator("iframe").locator('img')
locator.wait_for(timeout=1 * 1000)
```

But the error is complaining about a malformed selector:

`".example.cursor-pointer.p-2.rounded.bg-gray-50.dark:bg-gray-700"`

It looks like somewhere in your code you are creating a locator with this malformed selector. It does not come from Playwright.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
