### ISSUE TITLE
[Feature] Built-in jQuery

### ISSUE THREAD

**Issue by Luxusio** [microsoft/playwright#13811]
I want playwright has an built-in auto-wait jQuery.

If you use playwright's selector to test code written using jQuery, you won't be able to reuse existing jQuery code.
In the case of Cypress, it has built-in jQuery, making it easy to reuse existing jQuery code.
I want built-in jQuery to be added to Playwright so that I can reuse existing jQuery code.

**Comment by pavelfeldman** [comment]
In the modern web, the browsers included most of the original jQuery capabilities. I don't think we'll be including jQuery. Please file explicit requests for the actual features you are missing and we'll consider adding them!
