### ISSUE TITLE
[Question] Handling H.264 codec while running tests on pipelines (Firefox/WebKit)

### ISSUE THREAD

**Issue by CybulskiARC** [microsoft/playwright#13819]
Hello all!

My team and I are using Playwright for our test automation. A big part of our app is a video player and we are struggling with test automation of watching a video. Basically, we are missing H.264 codec while running it on chromium, WebKit, and Firefox.

As there is an easy way to work around it on chromium (basically running the test through a pre-installed chrome channel), I'm not sure if we can do the same stuff (or similar) for WebKit and Firefox on a pipeline.

Do you have any ideas on how we can handle it? Is there anyway we can force this codec to be used on WebKit/Firefox? Is it even possible?

I would much appreciate any insight on the issue!

Thanks in advance!

**Comment by pavelfeldman** [comment]
I would think it should be there in Firefox and in WebKit on a Mac. H.264 is not free, so it is only available if browser vendor included it or if it is available in the OS media stack.
