### ISSUE TITLE
[Question] Property 'poll' does not exist on type 'Expect'

### ISSUE THREAD

**Issue by mdemenko** [microsoft/playwright#13816]
**Context:**

- Playwright Version: 1.21.1
- Operating System: Windows 10
- Node.js version: 16.14.2
- Browser: Chromium

I've updated to the latest PW version 1.21.1 but 'poll' property doesn't exist. Seems Expect library doesn't have the latest version. Could you please suggest how I can resolve it?

**Comment by pavelfeldman** [comment]
I don't think your update worked, try a clean setup.

**Comment by mxschmitt** [comment]
Closing as per above, try a clean install (`npm ci`). and make sure that you don't use Jest or other test runners, since expect.poll and its friends are only available with the `@playwright/test` test-runner.
