### ISSUE TITLE
[Feature] Use retries when execution fails during a setup fixture

### ISSUE THREAD

**Issue by z0n** [microsoft/playwright#13823]
Hi, I have a fixture which sets up things before some tests. I also have the `retries` option set to 3 as my tests are flaky sometimes.
Unfortunately, the setup fixture can be flaky as well and throw an error. In that case, Playwright 1.21.1 currently fails the test immediately on the first try.
I'd expect the test to be retried as specified in the config.

**Comment by pavelfeldman** [comment]
It should be retried. Could you share a snippet I could use to repro?
