### ISSUE TITLE
Parallel execution- timeout error when used more than 2 workers. Only one usage of each socket address (protocol/network address/port) is normally permitted

### ISSUE THREAD

**Issue by sumitsg004** [microsoft/playwright#13820]
I am trying to execute Playwright cucumber tests in parallel. Providing number of parallel runs (workers) in cucumber.js file

```
let runCucumber = [
  `--parallel 3`, // Specify number of parallel workers
  tags,
```

It runs fine with 2 workers, but with more than 2 workers- two browser instance launch and run successfully, but third test throws error -

"browserType.launch: Timeout 30000ms exceeded. returned an error: Only one usage of each socket address (protocol/network address/port) is normally permitted Cannot start http server for devtools"

Can someone help with this issue.

**Comment by pavelfeldman** [comment]
Looks unrelated to Playwright. I'd suggest searching for "Only one usage of each socket address" on stackoverflow. Something is wrong with your server setup!

**Comment by sumitsg004** [comment]
thanks Pavel

**Comment by joychester** [comment]
The similar issue happens on my end too with setup simple parallel tests(only adjust the worker number):
For example, there is total n test files(n>=3) under a test folder, always success with maximum 2 workers, if the worker above 2, there will be n-2 tests hanging there(forever), unfortunately without any Error message return back or maybe i did not wait too long, except forcing quit the test:
```
 1) [chromium] › TestInParallel/parallel-3.spec.js:34:1 › Parallel_Test3 ==========================
^C
    Test was interrupted.

    Fixture "browser" timeout of 0ms exceeded.
```
And the failed tests are randomly, not sure if this is the same issue happened with @sumitsg004 , but the Phenomenon is quite the same

**Comment by joychester** [comment]
I am doing more isolation test just now, the issue seems coming out of **line 174 under /node_modules/@playwright/test/lib/index.js** , I am using version **1.28.1** and chromium + MacOS : 
```
_browserOptions: [async ({
    playwright,
    headless,
    channel,
    launchOptions,
    connectOptions
  }, use) => {

    const options = {
      handleSIGINT: false,
      timeout: 0,
      ...launchOptions
    };
    if (headless !== undefined) options.headless = headless;
    if (channel !== undefined) options.channel = channel;
    for (const browserType of [playwright.chromium, playwright.firefox, playwright.webkit]) {
      browserType._defaultLaunchOptions = options;
      browserType._defaultConnectOptions = connectOptions;
    }
    // All Workers Reached here :)
    await use(options);
    // Only 2 Workers Reached here :(
    for (const browserType of [playwright.chromium, playwright.firefox, playwright.webkit]) {
      browserType._defaultLaunchOptions = undefined;
      browserType._defaultConnectOptions = undefined;
    }
  },```

**Comment by joychester** [comment]
some update to this issue from my end, found the root cause of why it is just launching 2 chromium on my local, since i **added additional launchOptions**, it may be restrictions there but lack of helpful logging is hard to troubleshoot at the beginning:
```
use: {
......
  launchOptions: {
        //slowMo: 100,
        // for lighthouse usage: https://playwright.dev/docs/test-configuration#more-browser-and-context-options
        args: ["--remote-debugging-port=9222"],
      },
......
},
```
after removing the **--remote-debugging-port** option , it works fine for me now!

**Comment by robintel** [comment]
Hey @joychester ,

This was exactly my problem, as well, and your solution worked perfectly, thank you!
