### ISSUE TITLE
[BUG]- Unable to open the Playwright Inspector

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#13830]
**Context:**

- Playwright Version: [1.17.1]
- Operating System: [Windows-10]
- Browser: [All, Chromium, Firefox]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**JAVA**

Playwright playwright=Playwright.create();
LaunchOptions lp= new LaunchOptions();
lp.setChannel("msedge");
lp.setHeadless(false);
		
Browser browser= playwright.chromium().launch(lp);
Page page= browser.newPage();
page.navigate("https://d28eejm9iuuhtp.cloudfront.net/login");
String title=page.title();
System.out.println("Page title is "+ title);

 **Describe the bug**
Once i start running the script, the playwright inspector window lies on the bottom of tool bar. Clicking on it, the window disappears to the right of the screen and not able to do any action after it.

![image](https://user-images.githubusercontent.com/77335200/165829183-cca196a9-b27b-456c-a2b8-6d36d6f6975a.png)

**Comment by pavelfeldman** [comment]
This has been addressed in the newer versions of Playwright, 1.17 was 4 versions ago.

**Comment by mandeepmm1** [comment]
Can you please guide me how to update the Playwright version from 1.17 to 1.21.
Please send me the steps
