### ISSUE TITLE
[Question] React Selector with Descendant combinator

### ISSUE THREAD

**Issue by hirohe** [microsoft/playwright#13842]
for react base project, it is easiest way to locate a specific element by React Selector.

but I can no find how to locate react component in descendant combinator

e.g
```jsx
// component structure
<div>
   <Modal>
    <ModalBody />
    <Button />
  </Modal>

  <Button />
</div>
```

how to locate the `Button` inside `Modal` specifically ? the [document](https://playwright.dev/docs/selectors#react-selectors) didn't show such example

```js
// chaining two react selector seems not working
await page.locator('_react=Modal').locator('_react=Button');
```

### I was looking for something like that

```js
// locator syntax like this ?
await page.locator('_react=Modal Button');
```

maybe there's something like [testcafe-react-selectors](https://github.com/DevExpress/testcafe-react-selectors)
```js
ReactSelector('Modal Button');
```

**Comment by pavelfeldman** [comment]
Chaining them as you are showing should totally work!

**Comment by hirohe** [comment]
> Chaining them as you are showing should totally work!

You are right, chaining them is work, it should be the problem with my project 😂
