### ISSUE TITLE
[Question] Playwright have a per-shard test case limit?

### ISSUE THREAD

**Issue by jsjji89** [microsoft/playwright#13844]
Hello, we make E2E testcase with Playwright.
And we will use shard configuration and Jenkins as CI.
So now we are testing it and here we have a question.
Does playwright have a per-shard test case limit?
If there is a limit, is there an option to control the limit?
Please check the above question.
Thank you in advance.

**Comment by pavelfeldman** [comment]
No limit, tests are distributed between all shards as per documentation.

**Comment by jsjji89** [comment]
Thank you for answer.
