### ISSUE TITLE
[Question] How to disable web security for Webkit on Windows

### ISSUE THREAD

**Issue by testgitdl** [microsoft/playwright#13843]
I want to run my Playwright tests with Webkit on Windows but my application does not load in webkit. I get the following error: "security Error: Blocked a frame with origin "http://localhost:3000" from accesing a cross-origin frame. Protocols, domains and ports must match"
How can this be fixed? I've tried  "--disable-web-security" but does not work.

**Comment by pavelfeldman** [comment]
There is no such capability.

**Comment by testgitdl** [comment]
@pavelfeldman What could I then do to get webkit to work on Windows? Could you help out? Thank you!

**Comment by pavelfeldman** [comment]
It is not about Windows, the page you are trying to open violates same origin policy and won't open in Safari.
