### ISSUE TITLE
[BUG] Chrome/Chromium with HTTP proxy with authentication fails to load page fully and freezes

### ISSUE THREAD

**Issue by jlplenio** [microsoft/playwright#13848]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Windows 10
- Python version: Python 3.8
- Browser: [Chromium, Chrome]
- Extra: HTTP Proxy with authentication

**Code Snippet**

I am trying to run a chromium or chrome(channel='chrome') browser with HTTP proxy with authentication.
The proxy connection initially seems to work, the page is loaded either fully or partly (some content is missing).

```python
import asyncio
import time
from playwright.async_api import async_playwright

async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(
            proxy={"server": "per-context"},
            headless=False,
            channel='chrome'
        )
        context = await browser.new_context(
            ignore_https_errors=True,
            proxy={'server': 'http://1.1.1.1:1337', 'username': 'username', 'password': 'password'})
        page = await context.new_page()
        await page.goto("https://vimeo.com/336812686")
        time.sleep(30)
        await browser.close()


if __name__ == "__main__":
    asyncio.run(main())
```

**Describe the bug**

After the partial or fully page load, the entire page is unresponsive, content remains missing, and button clicks have no effect.
I chose Vimeo as an example because even if you get the video to stream, it will quickly stop as the buffering breaks.
Without a proxy connection, everything works fine. Firefox works flawlessly with the same settings/proxies.
I may recall having this problem before with selenium. So maybe the culprit is chrome/chromium and not playwright.
I tested multiple proxies from different providers.

Any ideas?

**Comment by pavelfeldman** [comment]
time.sleep is a problem, see https://playwright.dev/python/docs/intro#known-issues
