### ISSUE TITLE
Bug: importing Worker from playwright fails

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13849]
## System:
 - OS: Windows 10 10.0.19043
 - Memory: 4.63 GB / 15.83 GB
## Binaries:
 - Node: 14.17.5 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 7.18.1 - D:\Playground\Playground.Js\node_modules\.bin\npm.CMD
## Languages:
 - Bash: 4.3.48 - C:\Windows\System32\bash.EXE
## npmPackages:
 - playwright: ^1.21.0 => 1.21.0

follow-up on https://github.com/microsoft/playwright-test/issues/220

**Code Snippet**
The following code works:

```ts
import { test as testBase } from '@playwright/test';
import type { Worker } from '@playwright/test';

interface TestContext {
  worker: Worker
}

const test = testBase.extend<TestContext>({
  worker: async ({ page }, runTest) => {
    await page.goto('https://en.wikipedia.org/wiki/Main_Page');
    await page.route(url => url.href.includes('/sw.js'), route => route.fulfill({
      body: 'var a = 6',
      contentType: 'text/javascript',
      status: 200
    }));
    const [worker] = await Promise.all([
      page.waitForEvent('worker'),
      page.evaluate(() => {
        myWorker = new Worker('https://en.wikipedia.org/sw.js')
      })
    ]);

    await runTest(worker);
  }
});

test.describe('worker', function () {
  test('should work', async ({ worker }) => {  })
});
```

**Describe the bug**

changing the code to 
```diff
+import { test as testBase, Worker } from '@playwright/test';
-import { test as testBase } from '@playwright/test';
-import type { Worker } from '@playwright/test';
```

results with the following error:
![image](https://user-images.githubusercontent.com/9786571/165935028-ddaecf46-44f6-424c-aed6-dd7de6ec9b9c.png)

**Comment by pavelfeldman** [comment]
That's an interesting use case, since we compile the entire script, it thinks that your evaluate uses the imported Worker instead of the web one. `new window.Worker` fixes it. There isn't much we can do here - your intent of importing Worker as a function is clear and TS compiler respects it.

**Comment by Meir017** [comment]
@pavelfeldman is this something you think might be beneficial to have in the official docs? How to handle importing the `Worker` type and using the browser's Worker in the same file?
