### ISSUE TITLE
Excessive locator duration in Firefox

### ISSUE THREAD

**Issue by jasonatball** [microsoft/playwright#13853]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Linux
- Node.js version: 14
- Browser: Firefox
- Extra: Github action

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
  <div data-v-e3bb7458="" role="menu" class="v-menu__content theme--dark v-menu__content--fixed menuable__content__active" style="min-width: 89px; top: 50px; left: 337px; transform-origin: left top; z-index: 8;">
    <div data-v-e3bb7458="" class="v-list v-sheet theme--dark">
      <div data-v-e3bb7458="" class="v-input ma-0 pa-0 v-input--hide-details v-input--dense theme--dark v-input--selection-controls v-input--radio-group v-input--radio-group--column">
        <div class="v-input__control">
          <div class="v-input__slot" style="height: auto;">
            <div role="radiogroup" aria-labelledby="input-437" class="v-input--radio-group__input">
              <div data-v-e3bb7458="" tabindex="0" data-test="limits-monitor-file-show-ignored" role="menuitem" id="list-item-438" class="v-list-item v-list-item--link theme--dark">
                <div data-v-e3bb7458="" class="v-list-item__title" style="cursor: pointer;">Show Ignored</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  `);
  await page.locator('text=Show Ignored').click()
})();
```

**Describe the bug**
I have a Vuetify.js menu which I open using a a data-test attribute. It displays and is visible in the trace. However, playwright takes 20 or 30 seconds to click on it. This is happening in many other places where an element is displayed and playwright is taking double digit seconds to locate an item and click on it. The overall effect is that our tests are timing out because we're exceeding our (already extended) 5 minute test timeout.

This [run](https://github.com/BallAerospace/COSMOS/actions/runs/2246284666) the chromium execution took 13m and firefox took 27m.

**Comment by pavelfeldman** [comment]
Firefox takes longer to start, so the first test will be slower on Firefox. I modified a script to add one line:

```js
  const browser = await firefox.launch();
  await new Promise(f => setTimeout(f, 5000));
```

These are my measurements for this click on Linux:
chromium: 106.298ms
firefox: 118.705ms
webkit: 88.883ms

Could it be that you are starting too many workers? Or if your tests are failing frequently, we'll be restarting workers for you. Every time new worker starts it launches the browser and since Firefox startup is significantly slower, it might affect things.

**Comment by jasonatball** [comment]
I allow up to [3 workers](https://github.com/BallAerospace/COSMOS/blob/master/playwright/playwright.config.ts#L33) on CI/CD. What's strange is that it doesn't appear to be a startup issue. It just seems like the locator is taking a long time to find items on the page. Frequently double digit and up to 30s to locate an item. I can see it very clearly in the trace so not sure why. Is there a way to specify the Firefox version to use to try to debug?

**Comment by mxschmitt** [comment]
@jasonatball do you have a repro which you can share with us?

Did you try to set the `DEBUG=pw:api` env var, to see the actual time stamps / time differences between the calls?
