### ISSUE TITLE
[BUG] dragAndDrop is not working with react-beautiful-dnd

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [microsoft/playwright#13855]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Mac
- Node.js version: 14
- Browser: Desktop Electron App (Electron version 13)
- Extra: Maybe issue is with this library - [react-beautiful-dnd](https://www.npmjs.com/package/react-beautiful-dnd)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript 
  await page.dragAndDrop(`#Test123`, `#test124`)
```

**Describe the bug**
Element is not dropped at the target location, but I do see some kind of fluctuation at source element.
See attached video for reference.

https://www.loom.com/share/fd512a9448774a729cd8a1caeaa4fe01

**Comment by pavelfeldman** [comment]
Could you share a snippet or a repo with a minimal reproduction?

**Comment by mxschmitt** [comment]
@ahmedmukhtar1133 Can you share the site with us / create a minimal reproducible so we can run it locally?

**Comment by emanuellarini** [comment]
For those who might search for this... I have a working solution... keep in mind that you mind need to make adjustments in X and Y coordinates depending on your needs.

```
const dragAndDrop = (page, subjectSelector, targetSelector) => {
    const subjectElement = await page.waitForSelector(subjectSelector);
    const targetElement = await page.waitForSelector(targetSelector);
    
    const subjectElementBound = await subjectElement.boundingBox();
    const targetElementBound = await targetElement.boundingBox();

    await page.mouse.move(
      subjectElementBound.x,
      subjectElementBound.y,
      { steps: 10 } // this is the most important part!
    );

    await page.dispatchEvent(
      subjectSelector,
      'mousedown',
      {
        button: 0,
        force: true
      }
    );
   
    // the x and y below is up to you to determine, in my case it was a checkers game so I needed to calculate a bit
    // if you are using with lists, you might try and consider the numbers below.. 
   
    const x = targetElementBound.x + targetElementBound.width / 2;
    const y = targetElementBound.y + targetElementBound.height / 2;

    // steps are needed here as well
    await page.mouse.move(x, y, { steps: 10 }); 

    await page.dispatchEvent(targetSelector, 'mouseup', {
      button: 0
    });
}
```

**Comment by ryanweiler92** [comment]
> For those who might search for this... I have a working solution... keep in mind that you mind need to make adjustments in X and Y coordinates depending on your needs.
> 
> ```js
> const dragAndDrop = (page, subjectSelector, targetSelector) => {
>     const subjectElement = await page.waitForSelector(subjectSelector);
>     const targetElement = await page.waitForSelector(targetSelector);
>     
>     const subjectElementBound = await subjectElement.boundingBox();
>     const targetElementBound = await targetElement.boundingBox();
> 
>     await page.mouse.move(
>       subjectElementBound.x,
>       subjectElementBound.y,
>       { steps: 10 } // this is the most important part!
>     );
> 
>     await page.dispatchEvent(
>       subjectSelector,
>       'mousedown',
>       {
>         button: 0,
>         force: true
>       }
>     );
>    
>     // the x and y below is up to you to determine, in my case it was a checkers game so I needed to calculate a bit
>     // if you are using with lists, you might try and consider the numbers below.. 
>    
>     const x = targetElementBound.x + targetElementBound.width / 2;
>     const y = targetElementBound.y + targetElementBound.height / 2;
> 
>     // steps are needed here as well
>     await page.mouse.move(x, y, { steps: 10 }); 
> 
>     await page.dispatchEvent(targetSelector, 'mouseup', {
>       button: 0
>     });
> }
> ```

An amazing solution, thank you for this. For those searching, this is also a working solution for `react-draggable`.

**Comment by rubberTres** [comment]
Typescript implementation


``` 
const dragAndDrop = async (page: Page, subjectSelector: string, targetSelector: string) => {
	const subjectElement = await page.waitForSelector(subjectSelector);
	const targetElement = await page.waitForSelector(targetSelector);

	const subjectElementBound = {
		x: await subjectElement.boundingBox().then(bound => bound?.x ?? 0),
		y: await subjectElement.boundingBox().then(bound => bound?.y ?? 0),
		width: await subjectElement.boundingBox().then(bound => bound?.width ?? 0),
		height: await subjectElement.boundingBox().then(bound => bound?.height ?? 0),
	};

	const targetElementBound = {
		x: await targetElement.boundingBox().then(bound => bound?.x ?? 0),
		y: await targetElement.boundingBox().then(bound => bound?.y ?? 0),
		width: await targetElement.boundingBox().then(bound => bound?.width ?? 0),
		height: await targetElement.boundingBox().then(bound => bound?.height ?? 0),
	};

	await page.mouse.move(
		subjectElementBound.x,
		subjectElementBound.y,
		{ steps: 10 } // this is the most important part!
	);

	await page.dispatchEvent(
		subjectSelector,
		'mousedown',
		{
			button: 0,
			force: true
		}
	);

	// the x and y below is up to you to determine, in my case it was a checkers game so I needed to calculate a bit
	// if you are using with lists, you might try and consider the numbers below..

	const x = targetElementBound.x + targetElementBound.width / 2;
	const y = targetElementBound.y + targetElementBound.height / 2;

	// steps are needed here as well
	await page.mouse.move(x, y, { steps: 10 });

	await page.dispatchEvent(targetSelector, 'mouseup', {
		button: 0
	});
}
```

**Comment by rubberTres** [comment]
Typescript implementation

``````typescript
const dragAndDrop = async (page: Page, subjectSelector: string, targetSelector: string) => {
	const subjectElement = await page.waitForSelector(subjectSelector);
	const targetElement = await page.waitForSelector(targetSelector);

	const subjectElementBound = {
		x: await subjectElement.boundingBox().then(bound => bound?.x ?? 0),
		y: await subjectElement.boundingBox().then(bound => bound?.y ?? 0),
		width: await subjectElement.boundingBox().then(bound => bound?.width ?? 0),
		height: await subjectElement.boundingBox().then(bound => bound?.height ?? 0),
	};

	const targetElementBound = {
		x: await targetElement.boundingBox().then(bound => bound?.x ?? 0),
		y: await targetElement.boundingBox().then(bound => bound?.y ?? 0),
		width: await targetElement.boundingBox().then(bound => bound?.width ?? 0),
		height: await targetElement.boundingBox().then(bound => bound?.height ?? 0),
	};

	await page.mouse.move(subjectElementBound.x, subjectElementBound.y, { steps: 10 });

	await page.dispatchEvent(subjectSelector, 'mousedown', { button: 0, force: true });

	const x = targetElementBound.x + targetElementBound.width / 2;
	const y = targetElementBound.y + targetElementBound.height / 2;

	await page.mouse.move(x, y, { steps: 10 });

	await page.dispatchEvent(targetSelector, 'mouseup', { button: 0 });
}

**Comment by elhambanan** [comment]
Hello, thanks for sharing. I tried this solution for my e2e  test in Playwright, all is good locally, but it is not stable on CI!
Do you have any idea?

**Comment by bubuluxWork** [comment]
> For those who might search for this... I have a working solution... keep in mind that you mind need to make adjustments in X and Y coordinates depending on your needs.
> 
> const dragAndDrop = (page, subjectSelector, targetSelector) => {
>     const subjectElement = await page.waitForSelector(subjectSelector);
>     const targetElement = await page.waitForSelector(targetSelector);
>     
>     const subjectElementBound = await subjectElement.boundingBox();
>     const targetElementBound = await targetElement.boundingBox();
> 
>     await page.mouse.move(
>       subjectElementBound.x,
>       subjectElementBound.y,
>       { steps: 10 } // this is the most important part!
>     );
> 
>     await page.dispatchEvent(
>       subjectSelector,
>       'mousedown',
>       {
>         button: 0,
>         force: true
>       }
>     );
>    
>     // the x and y below is up to you to determine, in my case it was a checkers game so I needed to calculate a bit
>     // if you are using with lists, you might try and consider the numbers below.. 
>    
>     const x = targetElementBound.x + targetElementBound.width / 2;
>     const y = targetElementBound.y + targetElementBound.height / 2;
> 
>     // steps are needed here as well
>     await page.mouse.move(x, y, { steps: 10 }); 
> 
>     await page.dispatchEvent(targetSelector, 'mouseup', {
>       button: 0
>     });
> }

Still works in 2026 with the fork pangea-dnd, much luv
