### ISSUE TITLE
[Feature] Be able to map over list of locators

### ISSUE THREAD

**Issue by sarut0bi** [microsoft/playwright#13850]
Currently, I am unable to map over a list of locator ...function like `.all()` would be very greateful !

If I take your example about using locators https://playwright.dev/docs/locators#lists, it should add a 4th way to do:

// Locate elements, this locator points to a list.
const rows = page.locator('table tr');

_// Pattern 1: use locator methods to calculate text on the whole list.
const texts = await rows.allTextContents();

// Pattern 2: do something with each element in the list.
const count = await rows.count()
for (let i = 0; i < count; ++i)
  console.log(await rows.nth(i).textContent());

// Pattern 3: resolve locator to elements on page and map them to their text content.
// Note: the code inside evaluateAll runs in page, you can call any DOM apis there.
const texts = await rows.evaluateAll(list => list.map(element => element.textContent));_

**// Pattern 4: resolve locator to elements on page and map them into playwright context:
const texts = await Promise.all(rows.all().map(async (element) => await element.innerText()));**

**Comment by mxschmitt** [comment]
Sounds similar to https://github.com/microsoft/playwright/issues/12336

**Comment by sarut0bi** [comment]
True ! Close it now !
