### ISSUE TITLE
[Question] How to ignore CLI arguments for certain projects or how not to enforce CLI priority

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#13852]
My use case:

Projects, goes into `playwright.config.ts`

```
export const playwrightProjects: Project[] = [
  {
    name: 'production-chromium',
    grepInvert: /Sandbox test/,
    use: {
      baseURL: 'https://www.production-url.com',
      ...chromiumConfig
    }
  },
  {
    name: 'sandbox-chromium',
    grep: /Sandbox test/,
    use: {
      baseURL: 'https://sandbox-url.com',
      ...chromiumConfig
    }
  },
  ```
  
  Tests
  ```
  test('Production test @smoke', async ({ }) => {
  //
})

test('Another production test @whatever', async ({ }) => {
  //
})

test('Sandbox test', async ({ }) => {
  //
})
```

My goal is to achieve a test command via CLI to run `Production test @smoke` and `Sandbox test` tests. However, when given `npx playwright test --project production-chromium sandbox-chromium --grep @smoke` command it also tries to execute production tests on the sandbox project because the command line arguments takes priority over `grep` and `grepInvert` configurations in the file.

**Comment by pavelfeldman** [comment]
CLI has greater priority than config by design. You should split your execution into two runs or add another project for @smoke. Note that you are missing --project before sandbox-chromium in your command line example.
