### ISSUE TITLE
[Feature] support emulating user agent metadata

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#13861]
Similar to the puppeteer feature https://pptr.dev/#?product=Puppeteer&version=v13.5.2&show=api-pagesetuseragentuseragent-useragentmetadata
![image](https://user-images.githubusercontent.com/9786571/166121665-4af4ef45-7d4c-4f53-95a4-7c62616ed6fc.png)

this would probably translate to something like this:
```diff
const context = await browser.newContext({
-  userAgent: 'My user agent'
+  userAgent: 'My user agent', 
+  userAgentMetadata: {
+    architecture: 'My1',
+    mobile: false,
+    model: 'Mybook',
+    platform: 'MyOS',
+    platformVersion: '3.1',
+  }
});
```

**Comment by pavelfeldman** [comment]
What is your use case for those?

**Comment by Meir017** [comment]
testing how different responses render based on user-agent headers, not just the User-Agent request header

**Comment by pavelfeldman** [comment]
Could you be more specific than that? Like "Our server uses navigator.platform to do this and that, and we need to make sure that users that come from platform X have one experience and users coming from platform Y have another experience". The reason I ask is that this capability was originally added based on the requests from scrapers. We would not want to support or encourage this kind of behavior among Playwright users. if we see a real testing story behind the request, we'll leave it open.

**Comment by Meir017** [comment]
@pavelfeldman I don't have a concrete scenario for this, it just made sense to me to add this in playwright since it already exists in puppeteer

**Comment by pavelfeldman** [comment]
The reason it is in pptr is to avoid scraper detection. Since it is outside of the scope for Playwright, I'll close this request. Please feel free to reopen should you encounter a testing scenario that requires it.

**Comment by Meir017** [comment]
https://chromestatus.com/feature/5704553745874944 Feature: Reduce User Agent string information

It's not clear how chromium browsers will deprecate the User-Agent header but I think this would affect the current device emulation feature
