### ISSUE TITLE
[Built In Chrome Extension Enable] : How to enable built-in extensions in playwright chrome or any browser

### ISSUE THREAD

**Issue by raiajithkumarr** [microsoft/playwright#13869]
While working with Playwright >> "@playwright/test": "^1.21.1" we observed that extension tab is disabled.
And as per for UI testing we need to enable few extensions like "Windows Accounts" and "Google Docs Offline" like this.

How we can enable these extension in playwright browsers/ channels

Please guide here with some sample example.

**Comment by dgozman** [comment]
Here is a [guide for launching a Chrome Extension](https://playwright.dev/docs/chrome-extensions). There is no built-in support for extension in Playwright Test Runner, so you'll have to launch the browser yourself.

**Comment by raiajithkumarr** [comment]
Hi @dgozman 
In that document they are taking about custom extension not built-in extension for example "**Windows Accounts**" extension want install while running test cases.
Could you provide information related to it.
