### ISSUE TITLE
[Question] Playwright with JS or Java

### ISSUE THREAD

**Issue by anilgsk** [microsoft/playwright#13863]
Hello Team, I have few doubts in start Playwright for my project.
 Can we use Playwright with Java for an Angular and ReactJS application with no flaky tests.
 If I use Playwright with Java Script what are the advantages over playwright with Java.

**Comment by pavelfeldman** [comment]
Use the one you like, if you don't care - use JavaScript version - it comes with a test runner that augments Playwright capabilities and makes things easier to set up.
