### ISSUE TITLE
Timeout Error - Playwright displays 3000ms exceeded error if the page/element does not load within 4-5 secs

### ISSUE THREAD

**Issue by SanRak987** [microsoft/playwright#13877]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Mac
- Node.js version: 14.17.5
- Browser: All

**Code Snippet**

const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
await this.page.login();
await this.page.locator('#create application").click()
await this.page.loactor('#name").fill('abc')
await this.page.locator('#owners).click()
await this.page.locator('#confirm').click()
**await this.page.waitForSelector('text=Saved project successfully');**

**Describe the bug**

when the alert containing the above text shows up by 4-5 sec, I get a 30000ms timeout error. This happens even the application loads for status changes and reload functionality

**Comment by dgozman** [comment]
@SanRak987 Could you please provide a full repro that we can run locally? Unfortunately, we cannot help you based on this description alone.

**Comment by SanRak987** [comment]
I think the issue is similar to https://github.com/microsoft/playwright/issues/13940, I was able to run my script successfully in local but not on Jenkins
