### ISSUE TITLE
[Feature] Add Browser.BrowserTypeName method

### ISSUE THREAD

**Issue by jgilbert2017** [microsoft/playwright#13882]
I would like to be able to get the browser type name back from the `IBrowser` instance so I don't have track myself (I need it so I can do some browser specific logic).

Would it be possible to add a call `string IBrowser.BrowserTypeName { get; }` to the api?

**Comment by 1234Brian** [comment]
👍

**Comment by regseb** [comment]
[`download.page()`](https://playwright.dev/docs/api/class-download#download-page) ⇒ [`page.context()`](https://playwright.dev/docs/api/class-page#page-context) ⇒ [`browserContext.browser()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-browser). The next step would be **`browser.browserType()`**.

You can have the name of the browser with `browser.browserType().name()`. The executable path with `browser.browserType().executablePath()`. And if other properties are added in the `BrowserType` class, they will be accessible from a `Browser` instance.

This method must be added to [`browser.ts`](https://github.com/microsoft/playwright/blob/release-1.22/packages/playwright-core/src/client/browser.ts#L34):

```JavaScript
  browserType(): BrowserType {
    return this._browserType;
  }
```
