### ISSUE TITLE
[BUG] Runner is failed if some dynamic names are used as a test name

### ISSUE THREAD

**Issue by VolodymyrDmytriukhinDevPro** [microsoft/playwright#13892]
**Context:**
- Playwright Version: 1.21.1
- Operating System:  Mac
- Node.js version: 16.5.0
- Browser: Chromium

**Code Snippet**
```javascript
test('123'.padEnd(51, Math.round(Math.random() * 10000).toString()), () => {
    console.log();
  });
```

**Describe the bug**

Runner is failed if some dynamic names are used as a test name.
the test execution can be stopped in this way

**Comment by dgozman** [comment]
@VolodymyrDmytriukhinDevPro That is expected. Test names should be predictable, so that we can run them over and over in multiple workers. What is your usecase?

**Comment by VolodymyrDmytriukhinDevPro** [comment]
@dgozman thank you for your quick response - but sometimes I need to use DataProvider pattern for test cases when the tests are generated dynamically - so that I don't want to use the same name for all tests - but every test should have unique name - so I wan't to pass some part of test name dynamically

**Comment by dgozman** [comment]
@VolodymyrDmytriukhinDevPro Can you make them dynamic but stable? Use some kind of id for each test case? It you share more details, perhaps we can suggest something.

**Comment by VolodymyrDmytriukhinDevPro** [comment]
@dgozman here is an example of the test - here we want to fill different values to the input and validate it's behavior
We don't want to hard code values to add some randomization to the test case and want to have this value in the test title

```
import { expect, test } from '@playwright/test';


test.describe('Test', () => {
  [
    {
      textInput: '123'.padEnd(10, Math.round(Math.random() * 10000).toString())
    },
    {
      textInput: '0.123'.padEnd(10, Math.round(Math.random() * 10000).toString())
    },
    {
      textInput: '-123'.padEnd(10, Math.round(Math.random() * 10000).toString())
    }
  ].forEach(testCase => {
    test(`verify input behavior with value "${testCase.textInput}"`, async () => {
      // assume we make some action with given value
      // locator.fill(testCase.textInput);
      expect(true).toBe(true);
    });
  });
});
```

**Comment by dgozman** [comment]
Thank you for the example, this makes sense. Unfortunately, I don't think this is the usecase we'll be able to support going forward. I'd suggest to hardcode a few values instead of randomizing them all the time. Sorry for the inconvenience!
