### ISSUE TITLE
[Question]  regex no-text-selector, is possible?

### ISSUE THREAD

**Issue by AngelLopezBellmont** [microsoft/playwright#13902]
Hi,
How can I use regex inside a non-text-selector?
I have a problem to find the selector 
const selector_description = 'div[role="dialog"] >> textarea[name="Description*"]';

Sometime it comes with single star and other with double :   `Description* or Description** `

**Comment by dgozman** [comment]
@AngelLopezBellmont For CSS attribute selectors, there are quite a few [standard options available](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#syntax). These are not regular expressions, but should help in your particular case. More generally, css does not support regular expressions.

**Comment by AngelLopezBellmont** [comment]
@dgozman thanks super Dmitry :)
