### ISSUE TITLE
[Question] How to export an untagged PDF?

### ISSUE THREAD

**Issue by heku** [microsoft/playwright#13917]
I noted the PDF file exported via playwright is much larger than expected, I think it's because the playwright by default export the **tagged** PDF, which seems introduced since [chrome 85](https://www.visualistan.com/2020/07/chrome-85-will-come-with-tagged-pdf.html).

However, the tagged PDF is dozens of times larger than the untagged one, which is not acceptable to us.

I found if I save a html page to PDF via Edge (or Chrome) browser manualy, if the `Save as PDF` is the default option and if I don't touch this drop down, then the browser creates a **tagged PDF**, but if I change the drop down to any other option, then change it back,  then it will create a **untagged PDF**. 

Inferred from this result, I think there must be an option inside Edge/Chrome/Chromium to determine whether generate tagged or untagged PDF.

Now the quesiton is, does any of you know what this option is? How can I export a untagged PDF always via playwright?

![image](https://user-images.githubusercontent.com/3367199/166622186-352486c8-ba4d-40a2-a838-bce466f80658.png)

![image](https://user-images.githubusercontent.com/3367199/166622545-33f24fb5-e2d1-426c-bfec-989781fa673b.png)

**Comment by dgozman** [comment]
@heku Indeed, [this place](https://source.chromium.org/chromium/chromium/src/+/main:headless/lib/renderer/headless_print_render_frame_helper_delegate.cc;l=25-28;drc=adfe4659ed3661a61722948054c8f0ab427effcf;bpv=0;bpt=1) suggests that we always generate tagged pdfs.

**Comment by heku** [comment]
@dgozman thx, however our app users dont think so, a 20M+ size pdf (80 pages) is not acceptable to them. As comparsion, the untagged pdf is smaller than 1M.
Even tagged pdf has many benifits, it is better to have a  option for tagged/untagged.

**Comment by dgozman** [comment]
See https://bugs.chromium.org/p/chromium/issues/detail?id=1309963 for upstream Chromium issue.

**Comment by heku** [comment]
Thx, glad to know that the chromium team had noticed the issue, but I'm just curious why manually change the drop down to other option then back could lead to generate a untagged PDF, very interesting.

**Comment by kapouer** [comment]
@dgozman upstream chromium added the `--disable-pdf-tagging` switch in version 104.0.5101.0.
Not super cool as I guess it's not an option that can be set when calling playwright's `page.pdf()` method.

**Comment by heku** [comment]
Thx @kapouer

**Comment by Visheshmongia** [comment]
Hello @dgozman @kapouer ,
When using playwright to convert url/webpage/html to pdf it always creates tagged pdf even on passing (--disable-pdf-tagging) as an argument to chromium. Could you please let us know how can we generate untagged PDF using playwright?

**Comment by kapouer** [comment]
I don't know. If you really need to optimize the pdf I suggest you use ghostscript on top of it.
See how it's done in https://github.com/kapouer/express-dom-pdf

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by kapouer** [comment]
This issue was actually fixed by version 1.42: https://playwright.dev/docs/api/class-page#page-pdf-option-tagged
