### ISSUE TITLE
[BUG] - test case fails even before running the test case code/statements for Automatic fixtures

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#13920]
**Context:**
- Playwright Version: 1.20.0
- Operating System: Windows
- Node.js version: 14.6.1
- Browser: Chromium/Chrome

**Code Snippet**

```javascript
export const test = base.extend<{ testFixture: void }>({

    testFixture: [async ({}, use) => {
        await use();
        throw new Error('MyError')
    }, { auto: true }],

});
```

**Describe the bug**

For the code snippet given, the automatic fixture doesn't work correctly. If I use *throw new Error()" it fails the test cases even before executing the contents/code in the "test" block. The test.beforeAll() or test.afterAll() would run, but the test itself fails without running the code inside it. Of course, the failure of the test case is expected, but it should not fail in the beginning, instead, it should fail after the test ends. Instead of an automatic fixture, if I use a normal fixture, then it works. Meaning, that the test case fails after executing the code inside the "test" block.

**Comment by dgozman** [comment]
@autTestUser Could you please share the whole test? I think this could be related to exact hooks (`beforeAll` and others) that you have, so sharing a repro will help greatly!

**Comment by autTestUser** [comment]
> @autTestUser Could you please share the whole test? I think this could be related to exact hooks (`beforeAll` and others) that you have, so sharing a repro will help greatly!

import { test } from "../../fixture";

let page: Page;
let myInstance;

test.describe("describeName", () => {

    test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();
		myInstance= await new MyDefaultPage(page)
    });
	
    test.afterAll(async () => {
        await page.close()
    });

    test.beforeEach(async () => {
        myInstance.common()
    });

    test('menu displayed', async () => {     
		myInstance.isMenuDisplayed()

    });

});

**Comment by autTestUser** [comment]
@dgozman When I ran the exact code you shared, I'm getting below output. Notice that "test works?" is not displayed and "will throw right here" is displayed twice. Also, the error/exception is thrown twice.

```
npx playwright test a.spec.ts

Running 1 test using 1 worker

will throw right here
will throw right here
  x  a.spec.ts:26:5 › describeName › menu displayed (0ms)


  1) a.spec.ts:26:5 › describeName › menu displayed ================================================

    Error: MyError

       6 |         await use();
       7 |         console.log('will throw right here');
    >  8 |         throw new Error('MyError');
         |               ^
       9 |     }, { auto: true }],
      10 | });
      11 |

        at Object._test.test.extend.testFixture.auto [as fn] (D:\Git_Repos\sequencer_playwright\a.spec.ts:8:15)

    Error: MyError

       6 |         await use();
       7 |         console.log('will throw right here');
    >  8 |         throw new Error('MyError');
         |               ^
       9 |     }, { auto: true }],
      10 | });
      11 |

        at Object._test.test.extend.testFixture.auto [as fn] (D:\Git_Repos\sequencer_playwright\a.spec.ts:8:15)


  1 failed
    a.spec.ts:26:5 › describeName › menu displayed =================================================
```

**Comment by dgozman** [comment]
> @dgozman Which version of Playwright did you try this on?

Good point! I have just tried with 1.20.2 (same output as you get) and 1.21.1 (the issue is fixed). So, good news is you can update the version and the problem should disappear. Let us know if that does not help.

**Comment by autTestUser** [comment]
@dgozman Yes, after changing the version, it works, but there are still issues with fixtures I think. For the below code snippet, beforeAll and afterAll is executed for each test. Also for test1, "before testFixture" and "after testFixture" is printed twice. I have added the console output.

```
// a.spec.ts
import { test as base, expect, Page } from '@playwright/test';

const test = base.extend<{ testFixture: void }>({
    testFixture: [async ({}, use) => {
        console.log('before testFixture');
        await use();
        console.log('after testFixture');
        throw new Error('MyError');
    }, { auto: true }],
    // testFixture: async ({}, use) => {
    //     console.log('before testFixture');
    //     await use();
    //     console.log('after testFixture');
    //     throw new Error('MyError');
    // }
});

let page: Page;

test.describe("describeName", () => {
    test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();
        console.log('inside beforeAll');
    });

    test.afterAll(async () => {
        await page.close()
        console.log('inside afterAll');
    });

    test.beforeEach(async () => {
        console.log('inside beforeEach');
    });

    test.afterEach(async () => {
        console.log('inside afterEach');
    });

    test('test1', async () => {
        console.log('inside test1');
    });

    test('test2', async () => {
        console.log('inside test2');
    });
});
```

**Console Output**

```npx playwright test a.spec.ts

Running 2 tests using 1 worker

  ✘  a.spec.ts:40:5 › describeName › test1 (1s)
before testFixture
inside beforeAll
inside beforeEach
inside test1
inside afterEach
after testFixture
before testFixture
inside afterAll
after testFixture
  ✘  a.spec.ts:44:5 › describeName › test2 (1s)
before testFixture
inside beforeAll
inside beforeEach
inside test2
inside afterEach
inside afterAll
after testFixture


  1) a.spec.ts:40:5 › describeName › test1 =========================================================

    Error: MyError

       7 |         await use();
       8 |         console.log('after testFixture');
    >  9 |         throw new Error('MyError');
         |               ^
      10 |     }, { auto: true }],
      11 |     // testFixture: async ({}, use) => {
      12 |     //     console.log('before testFixture');

        at Object._test.test.extend.testFixture.auto [as fn] (D:\Git_Repos\sequencer_playwright\a.spec.ts:9:15)

  2) a.spec.ts:44:5 › describeName › test2 =========================================================

    Error: MyError

       7 |         await use();
       8 |         console.log('after testFixture');
    >  9 |         throw new Error('MyError');
         |               ^
      10 |     }, { auto: true }],
      11 |     // testFixture: async ({}, use) => {
      12 |     //     console.log('before testFixture');

        at Object._test.test.extend.testFixture.auto [as fn] (D:\Git_Repos\sequencer_playwright\a.spec.ts:9:15)


  2 failed
    a.spec.ts:40:5 › describeName › test1 ==========================================================
    a.spec.ts:44:5 › describeName › test2 ==========================================================

```

**Comment by dgozman** [comment]
@autTestUser This is expected behavior, although it's not entirely intuitive. The order of events is:

1. Auto fixture setup.
2. `beforeAll`
3. `beforeEach`
4. test
5. `afterEach`
6. Here we should normally proceed to the second test. We teardown the auto fixture, so that we can setup it again for the second test.
7. Auto fixture teardown crashes. This means we should cleanup the worker without running the second test. This requires running `afterAll`.
8. Auto fixture is setup again for the `afterAll`. This is the most unexpected bit. Depending on the fixture, you might expect it to be run for hooks, or not. I think the situation here is not ideal.
9. `afterAll`
10. Auto fixture teardown.

I hope this helps!

**Comment by autTestUser** [comment]
@dgozman Why the Auto fixture is not set up again for the afterAll of the second test?

**Comment by dgozman** [comment]
> Why the Auto fixture is not set up again for the afterAll of the second test?

That's because it was not teared down. Instead, `afterAll` runs immediately after the test, and then all fixtures are teared down.

**Comment by autTestUser** [comment]
With or without fixtures, usually, the beforeAll and afterAll should only run once per describe, right?

**Comment by dgozman** [comment]
> With or without fixtures, usually, the beforeAll and afterAll should only run once per describe, right?

That's right. Unless there were test failures. See [this doc](https://playwright.dev/docs/test-retries#failures) for details.

**Comment by dgozman** [comment]
As I said, the situation here is not ideal, but I don't have a nice solution yet.

**Comment by autTestUser** [comment]
> > With or without fixtures, usually, the beforeAll and afterAll should only run once per describe, right?
> 
> That's right. Unless there were test failures. See [this doc](https://playwright.dev/docs/test-retries#failures) for details.

One more question: Shouldn't an automatic fixture and a normal fixture work the same way when it comes to the order of execution? For a success scenario with two test blocks, below is the output I'm getting 

**With automatic fixture**
```
npx playwright test a.spec.ts

Running 2 tests using 1 worker

  ok a.spec.ts:26:5 › describeName › test1 (2s)
before testFixture
inside beforeAll
inside beforeEach
inside test1
envValue
inside afterEach
after testFixture
  ok a.spec.ts:31:5 › describeName › test2 (10ms)
before testFixture
inside beforeEach
inside test2
inside afterEach
inside afterAll
after testFixture
```
**With normal fixture**
```
npx playwright test a.spec.ts

Running 2 tests using 1 worker
  ok a.spec.ts:26:5 › describeName › test1 (2s)
inside beforeAll
inside beforeEach
before testFixture                    
inside afterEach
after testFixture
  ok a.spec.ts:31:5 › describeName › test2 (10ms)
inside beforeEach
before testFixture
inside test2
inside afterEach
inside afterAll
after testFixture
```

**Comment by dgozman** [comment]
Normal fixture is instantiated on the first use. It looks like in your example it is first used in `test1` or `afterEach`, but not in before hooks.

**Comment by autTestUser** [comment]
> Normal fixture is instantiated on the first use. It looks like in your example it is first used in `test1` or `afterEach`, but not in before hooks.

ok, got it.
