### ISSUE TITLE
Got timeout in context.waitForEvent("page"), in POM Playwright.

### ISSUE THREAD

**Issue by ButeoButeo** [microsoft/playwright#13926]
Hi, I got timeout in context.waitForEvent("page"), in POM Playwright. The new page was loaded but test stop, like  waiting for something, for a while.... Any Tip?

**Comment by dgozman** [comment]
@ButeoButeo Here is [a guide for popups](https://playwright.dev/docs/pages#handling-popups). Other than that, please share a test/config/script that we can run locally to reproduce the issue, and we'll certainly take a look.

**Comment by ButeoButeo** [comment]
Popup works but is not stable, sometimes happen the following:
page.waitForEvent: Page closed
=========================== logs ===========================
waiting for event "popup"
============================================================

**Comment by ButeoButeo** [comment]
await this.page.locator('#merchants > div.row.mb-4 > div:nth-child(1) > div > div').isVisible()
      await this.page.waitForSelector('#merchants > div.row.mb-4 > div:nth-child(1) > div > div')
      // between clicking and waiting for the popup.
      const [popup] = await Promise.all([
        // It is important to call waitForEvent before click to set up waiting.
        this.page.waitForEvent('popup'),
         // Opens popup.
        this.amazon.click()
       ]);
      await popup.waitForLoadState();
      await popup.waitForSelector("#root > div > div:nth-child(1) > div > div.ant-select.ant-select-single.ant-select-show-arrow.ant-select-show-search > div > span.ant-select-selection-placeholder")
      await popup.bringToFront()
      await popup.locator('#rc_select_0').click()
      await popup.locator('body > div:nth-child(6) > div > div > div > div.rc-virtual-list > div.rc-virtual-list-holder > div > div > div:nth-child(3) > div').click()
      await popup.locator('#root > div > div:nth-child(1) > div > button > span').click()
      await popup.close()

**Comment by dgozman** [comment]
> Thanks! Sometimes the popup doesn't open and stays waiting for the event("popup"), in debug mode, popup always open:

The code looks good. When you say "sometimes the popup doesn't open" - is that expected? If so, waiting for it is meaningless 😄  If you are not sure whether popup will open or not, you can try the following:

```js
// Give popup 5 seconds to appear.
const [popup] = await Promise.all([
  this.page.waitForEvent('popup', { timeout: 5000 }).catch(error => null),
  this.amazon.click()
]);

if (popup) {
  // Do something with popup when it opens in 5 seconds.
} else {
  // There was no popup.
}
```

**Comment by ButeoButeo** [comment]
Thanks!🙏🏻 Yes, Works for popups! But the popup open in some browsers, others are not opening...I don't understand why😅..... As the following image: 
<img width="1111" alt="image" src="https://user-images.githubusercontent.com/16030612/167252090-8eaed525-e7fb-4a20-a87b-95d48178d672.png">

**Comment by dgozman** [comment]
@ButeoButeo Seems to be related to OSX vs Windows? Perhaps your page is just different on different OSes? I don't think we can help further here without a full repro, sorry. I hope you'll find the issue 😄

**Comment by victorikeokoro6** [comment]
The issue is the function, you wrote is used for handling blanks (opening in a new tab)
Check this out
