### ISSUE TITLE
[BUG] Error: Protocol error (Target.setDiscoverTargets): Target closed.

### ISSUE THREAD

**Issue by aljaz823** [microsoft/playwright#1392]
**Context:**
- Playwright Version: 0.11.1
- Operating System: Ubuntu 18.04
- Extra: Ubuntu running on WSL2

**index.js:**
```
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.google.com/');
  await page.screenshot({ path: `example-${browserType}.png` });
  await browser.close();
})();
```

**Run with:**

```
node index.js
```

**Whole error message:**
```
(node:1500) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setDiscoverTargets): Target closed.
    at /home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
    at new Promise (<anonymous>)
    at CRSession.send (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at Function.connect (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crBrowser.js:51:38)
    at Chromium.launch (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/server/chromium.js:46:53)
    at async /home/aljaz/codeProjects/playwright-demo/index.js:4:19
(node:1500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Describe the bug**

I'm not sure how to tackle this problem. It's my first time posting an issue and first time using Playwright. Basically I'm just trying it out but it throws an error on the very first attempt to do so.

Environment is completely fresh, only playwright installed and only the included code snippet is run.

**Comment by danielfazlijevic** [comment]
I am having a similar issue when I try to run it in docker.

**Comment by mxschmitt** [comment]
> I am having a similar issue when I try to run it in docker.

which docker Image are you using?

**Comment by mxschmitt** [comment]
> **Context:**
> 
> * Playwright Version: 0.11.1
> * Operating System: Ubuntu 18.04
> * Extra: Ubuntu running on WSL2
> 
> **index.js:**
> 
> ```
> const playwright = require('playwright');
> 
> (async () => {
>   const browser = await playwright.chromium.launch();
>   const context = await browser.newContext();
>   const page = await context.newPage();
>   await page.goto('https://www.google.com/');
>   await page.screenshot({ path: `example-${browserType}.png` });
>   await browser.close();
> })();
> ```
> 
> **Run with:**
> 
> ```
> node index.js
> ```
> 
> **Whole error message:**
> 
> ```
> (node:1500) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setDiscoverTargets): Target closed.
>     at /home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
>     at new Promise (<anonymous>)
>     at CRSession.send (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
>     at Function.connect (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/chromium/crBrowser.js:51:38)
>     at Chromium.launch (/home/aljaz/codeProjects/playwright-demo/node_modules/playwright-core/lib/server/chromium.js:46:53)
>     at async /home/aljaz/codeProjects/playwright-demo/index.js:4:19
> (node:1500) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:1500) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> ```
> 
> **Describe the bug**
> 
> I'm not sure how to tackle this problem. It's my first time posting an issue and first time using Playwright. Basically I'm just trying it out but it throws an error on the very first attempt to do so.
> 
> Environment is completely fresh, only playwright installed and only the included code snippet is run.

Be sure to install all the required dependencies which are documented here: https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-linuxwsl

**Comment by aljaz823** [comment]
@mxschmitt 
Thanks for the fast response, it's working after manually installing all of the required dependencies.

**Comment by danielfazlijevic** [comment]
> 
> 
> > I am having a similar issue when I try to run it in docker.
> 
> which docker Image are you using?
> 
> Try to use this one until the official one will be distributed over the Microsoft Docker hub account: https://hub.docker.com/r/aslushnikov/playwright

I've managed to run it sucessfully using the following Dockerfile:

```
FROM ubuntu:bionic

RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs

# Install browser deps, starting with webkit
RUN apt-get install -y libwoff1 \
                       libopus0 \
                       libwebp6 \
                       libwebpdemux2 \
                       libenchant1c2a \
                       libgudev-1.0-0 \
                       libsecret-1-0 \
                       libhyphen0 \
                       libgdk-pixbuf2.0-0 \
                       libegl1 \
                       libnotify4 \
                       libxslt1.1 \
                       libevent-2.1-6 \
                       libgles2 \
                       libgl1 \
                       libvpx5 \
                       # for chromium
                       libnss3 \
                       libxss1 \
                       libasound2 \
                       # for firefox
                       libdbus-glib-1-2 \
                       libxt6


ENV NODE_ENV production
WORKDIR /usr/src/app


COPY ["package.json", "package-lock.json*", "npm-shrinkwrap.json*", "./"]
RUN npm install
COPY . .

CMD node index.js
```
