### ISSUE TITLE
[Question] Why is using ElementHandle discouraged?

### ISSUE THREAD

**Issue by cameron-martin** [microsoft/playwright#13930]
The docs state:

> The use of ElementHandle is discouraged, use [Locator](https://playwright.dev/docs/api/class-locator) objects and web-first assertions instead.

Why is usage of `ElementHandle` discouraged? Is it only due to not having retrys built in like Locators do, or are there other reasons to avoid this?

**Comment by dgozman** [comment]
Here is a [nice explanation](https://playwright.dev/docs/locators#locator-vs-elementhandle).
