### ISSUE TITLE
[Question] Is it possible to verify hover text?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#13933]

**Comment by dgozman** [comment]
@gauravgandhi1315 Could you please provide more details? Ideally, a page url and a thorough explanation of what you try to achieve.

**Comment by gauravgandhi1315** [comment]
@dgozman I want to verify mouseover text on a button. Not sure if it can achieved through playwright

**Comment by gauravgandhi1315** [comment]
I tried to use `page.hover(selector)` but it highlights that button and text doesn't show up.

**Comment by dgozman** [comment]
@gauravgandhi1315 That's probably a `title` attribute. You can verify it with [`expect(locator).toHaveAttribute('title', 'Avery...')`](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-attribute).
