### ISSUE TITLE
[BUG] Tests work locally but timeout in GitHub Action

### ISSUE THREAD

**Issue by nerdyman** [microsoft/playwright#13940]
### Discussed in https://github.com/microsoft/playwright/discussions/13800

Hi, I've created this issue based on the discussion linked above. I thought it was maybe just how I had Playwright set up but others are having the same issue.

**Context:**
- Playwright Version: `^1.21.1`
- Operating System: macOS and Linux for GitHub Action (Ubuntu)
- Node.js version: 14 lts and 16 lts
- Browser: `Chromium`
- Extra: 
	- Works fine locally on macOS but timesout it GitHub Action
	- Also able to repro locally using [`act`](https://github.com/nektos/act)
	- Using `pnpm@6.32.9`

## System:
 - OS: macOS 12.3.1
 - Memory: 83.73 MB / 16.00 GB
## Binaries:
 - Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
 - npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
 - pnpm 6.32.9 - ~/.nvm/versions/node/v16.15.0/bin/pnpm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright-core: ^1.21.1 => 1.21.1 

**Code Snippet**

The easiest way to repro is probably to clone the repo and run `act`.

```sh
git clone git@github.com:nerdyman/react-image-turntable.git && \
cd react-image-turntable && \
npm run dx && \
act
```

**Describe the bug**

Add any other details about the problem here.

[Original post](https://github.com/microsoft/playwright/discussions/13800):

<div type='discussions-op-text'>

<sup>Originally posted by **nerdyman** April 27, 2022</sup>
Hi! Apologies if this is an obvious fix, I'm new to Playwright.

I've got my tests running OK locally, but they timeout when running in a GitHub action. I've enabled debug logs but can't see anything that might identify the issue.

![image](https://user-images.githubusercontent.com/4908432/165601783-b2bcdaf8-bcb0-4088-92ef-c9cc85c9eaa7.png)

[This is the job definition](https://github.com/nerdyman/react-image-turntable/blob/main/.github/workflows/main.yml#L35) and [this is one of the failed jobs](https://github.com/nerdyman/react-image-turntable/runs/6199135985?check_suite_focus=true#step:7:465). Also, the [tests are available in the test folder in the repo](https://github.com/nerdyman/react-image-turntable/blob/main/test/ExampleRepo.spec.ts).

Any help would be awesome 🙌</div>

**Comment by dgozman** [comment]
@nerdyman Shouldn't you await `injectAxe()` and other axe methods, [for example here](https://github.com/nerdyman/react-image-turntable/blob/main/test/ExampleRepo.spec.ts#L12)? Perhaps that could explain the issue? Another reason could be that perhaps your dev server behaves differently? Also, I'm not familiar enough with pnpm, but you have some pnpm caching that is only applicable to GHA, but not local.

**Comment by nerdyman** [comment]
@dgozman ah yeah my bad, I should be awaiting `injectAxe()`. That hasn't resolved the issue though, even if I take the axe function calls out leaving only the `page.goto()` it still times out. 

In the snippet below it never gets to `console.info('[!!] after goto');`

```ts
test.beforeEach(async ({ page }) => {
    console.info('[!!] before goto');
    await page.goto('http://localhost:3000/?debug');
    console.info('[!!] after goto');
});
```

I'll take a look at the dev server and caching set up too.

**Comment by nerdyman** [comment]
I did a bit more digging and found that it only happens when `page.goto` is in `test.beforeEach`.

If I do my own custom `beforeEach` and call it myself everything is OK.

```ts
const beforeEach = async (page: Page) => {
    await page.goto('http://localhost:3000/?debug');
    await injectAxe(page);

    configureAxe(page, {
      checks: [{ id: 'page-has-heading-one', enabled: false }],
    });

    await checkA11y(page);
  };

test('Should generate correct aria attributes', async ({ page }) => {
    await beforeEach(page);
   // ...
});
```

I'll try and get a repro with a simpler set up.

**Comment by nerdyman** [comment]
This was something to do with how the dev build for my with pnpm (`pnpm -r --stream run start`) it was streaming both tasks together but the CI doesn't seem to like the dev task of the library so I changed the Playwright command to build the library and then run the dev server for the example repo (`pnpm run build && pnpm run start --filter "./example"`).

Thanks for your help @dgozman! I'll close the issue.

**Comment by SHREYANSH1814** [comment]
Still getting the same issue on gha

**Comment by wangtianlun** [comment]
> Still getting the same issue on gha

+1

**Comment by aryaniyaps** [comment]
I'm still facing this issue on github actions
