### ISSUE TITLE
[Question] Same Test Case With Different Value 

### ISSUE THREAD

**Issue by Nerijus123** [microsoft/playwright#13955]
Hey I just thinking Is there a possibility in Playwright - Typescript,  to do the same as is possible with other tools pass different values on one test run? Or something like that, what could I do with Selenium, NUnit, C#? 

![image](https://user-images.githubusercontent.com/29463426/166883872-8f93e46f-a0ab-4ebd-82cd-10a8e313fe48.png)

**Comment by rwoll** [comment]
See https://playwright.dev/docs/test-parameterize#parameterized-tests for info on parameterized tests.
