### ISSUE TITLE
[Question] Can the default steps be disabled from allure reports?

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#13965]
We would like to add our own steps in allure reports using "test.step" instead of having the built-in detailed steps which are already added by the playwright for every browser action performed. Is there a way to disable it?

**Comment by dgozman** [comment]
This is technically possible, but you should file an [issue for allure reporter](https://github.com/allure-framework/allure-js/issues) instead.

**Comment by autTestUser** [comment]
The issue is raised at https://github.com/allure-framework/allure-js/issues/437
