### ISSUE TITLE
[Feature] Support static folder without server

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/playwright#13968]
I recently got a pull request which added tests using Playwright, which is great.

However, this also included code to launch a static file server. I think it would be nice if Playwright supports this out of the box.

```diff
  // eslint-disable-next-line @typescript-eslint/consistent-type-imports
  import type { PlaywrightTestConfig } from '@playwright/test';

  const config: PlaywrightTestConfig = {
    reporter: 'html',
    webServer: {
-     command: 'node test/serve.js',
-     port: 3000,
-     reuseExistingServer: !process.env.CI,
+     directory: 'test',
    },
  };
  export default config;
```

Under the hood Playwright could just start a static file server on an open port.

**Comment by 1234Brian** [comment]
👍

**Comment by gmullerb** [comment]
Instead of using `webServer` configuration field, You can **use `baseURL` configuration field with a `file://` URL value**.

e.g.
`playwright.config.ts`:

```
import type { PlaywrightTestConfig } from '@playwright/test'
import path from 'path'

const config: PlaywrightTestConfig = {
  use: {
    baseURL: `file://${path.join(__dirname, `./build/www/`)}`
  },
};
export default config;  
```
and then in the test:
`some.test.ts`

```
import { test, expect, type Page } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('index.html')
});
```

or

`playwright.config.ts`:

```
import type { PlaywrightTestConfig } from '@playwright/test'
import path from 'path'

const config: PlaywrightTestConfig = {
  use: {
    baseURL: `file://${path.join(__dirname, `./build/www/index.html`)}`
  },
};
export default config;  
```

and then in the test:
`some.test.ts`

```
import { test, expect, type Page } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('')
});
```

**Comment by 1234Brian** [comment]
Ok got it👍 perfect string

**Comment by TommasoAmici** [comment]
While using a file path will work well in some cases, it won't work in others.

For example, when working with a server whose CORS policy only allows `localhost:3000` it'd be helpful to be able to serve the build directory on port 3000.

In Cypress this is possible by adding this to the config:

```ts
e2e: {
    port: 3000,
    fileServerFolder: "build",
}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by ruifigueira** [comment]
A trick to run a static file server is to use [browserContext.route](https://playwright.dev/docs/api/class-browsercontext#browser-context-route).

To give it a try, just create an `hello.html` file with `<div>Hello World!</div>` and, in the same folder, run the following test:

```ts
import path from 'path';
import { test as baseTest, expect } from '@playwright/test';

const test = baseTest.extend({
  context: async ({ context }, run) => {
    await context.route('**/*', (route, request) => route.fulfill({ path: path.join(__dirname, new URL(request.url()).pathname) }));
    await run(context);
  },
});

test('test webserver', async ({ page }) => {
  await page.goto(`http://localhost:3333/hello.html`);
  await expect(page.locator('div')).toHaveText('Hello World!');
});
```
