### ISSUE TITLE
[BUG] Large file upload failing in Firefox

### ISSUE THREAD

**Issue by italodeandra** [microsoft/playwright#13975]
This release https://github.com/microsoft/playwright/releases/tag/v1.21.0 has the following:

> Playwright now supports large file uploads (100s of MBs) via [Locator.setInputFiles](https://playwright.dev/docs/api/class-locator#locator-set-input-files) API.

But according to the PR https://github.com/microsoft/playwright/pull/12860 only Chrome is supported:

> Chromium only, other browsers to follow

It took me a while to figure out why Firefox wasn't working, because the error wasn't helpful.

Is it a good idea to add a warning somewhere?

**Comment by rwoll** [comment]
There was a follow-up PR that added support for the other browsers: https://github.com/microsoft/playwright/pull/12937 (except for very specific mac+wk conditions https://github.com/microsoft/playwright/blob/058f32caff961914948c29299c65263c6aa2114a/tests/page/page-set-input-files.spec.ts#L41).

Based on checking out the git v1.21.0 tag, it looks like that was in there, so it should be working on 1.21.0 and 1.21.1 for most scenarios.

Can you share a repro and/or more info about what's not working (including version number of Playwright, platform, platform version)? Thanks!

**Comment by italodeandra** [comment]
**Playwright version:** 1.21.1
**Platform:** Firefox
**Platform version:** Playwright build of firefox v1322

**Error:**
```
elementHandle.setInputFiles: Protocol error (Page.setFileInputFiles): error in channel "content::page": exception while running method "setFileInputFiles" in namespace "page":  _setFileInputFiles/nsFiles<@chrome://juggler/content/content/PageAgent.js:449:66
   _setFileInputFiles@chrome://juggler/content/content/PageAgent.js:449:45
   _onMessage@chrome://juggler/content/SimpleChannel.js:165:37
   receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
    _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
   receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
    - elementHandle.setInputFiles: Protocol error (Page.setFileInputFiles): error in channel "content::page": exception while running method "setFileInputFiles" in namespace "page":  _setFileInputFiles/nsFiles<@chrome://juggler/content/content/PageAgent.js:449:66
   _setFileInputFiles@chrome://juggler/content/content/PageAgent.js:449:45
   _onMessage@chrome://juggler/content/SimpleChannel.js:165:37
   receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
    _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
   receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
   
       at async YouTube.upload (webpack-internal:///(api)/./src/youtube/YouTube.ts:122:13)
       at async uploadVideoOnYoutube (webpack-internal:///(api)/./pages/api/youtube/upload.ts:203:30)
       at async handler (webpack-internal:///(api)/./pages/api/youtube/upload.ts:336:24) +11s
```

**Code:**
```ts
await page.goto("https://www.youtube.com/upload");
const [fileChooser] = await Promise.all([
  page.waitForEvent("filechooser", {
    timeout: ms("5 minutes"),
  }),
  // Select files button
  page.click("#select-files-button"),
]);
await fileChooser.setFiles(filePath);
```

PS: It works normally with Chromium.

**Comment by italodeandra** [comment]
Should I convert this issue to a bug instead? 
Like you corrected me, the support was indeed implemented but just not working for me 😢

**Comment by rwoll** [comment]
Converted—thanks! Out of curiosity, how big is the file you are trying to upload? Does it work with a file that's 200MB (which is what the test uses)?

We will need to debug regardless.

**Comment by italodeandra** [comment]
> how big is the file you are trying to upload?

One was 919MB and another one was 10GB. Both worked in Chromium.

> Does it work with a file that's 200MB (which is what the test uses)?

I'll test.

**Comment by rwoll** [comment]
Adding some notes for myself.

---

Debugging Notes:

1. https://github.com/microsoft/playwright/blob/5a3fae4c5a0703399f5dd8a59076a5e15d361871/tests/page/page-set-input-files.spec.ts#L40 passes for me when i do `git checkout v1.21.0 && npm run clean && npm ci && npm run build && npm run test -- --grep 'should upload large file'`
2. I can repro the issue with a fresh project that depends on `@playwright/test@1.21.1`:

```
$ git clone git@github.com:rwoll/playwright-large-file-uploads-repro.git
$ cd repro
$ npm i
$ npx playwright install
$ npm run test
> large-file-repro@1.0.0 test
> npx playwright test


Running 3 tests using 3 workers

[WebServer] Server listening…
  ✘  [firefox] › tests/example.spec.ts:3:1 › uploads (1s)
  ✘  [chromium] › tests/example.spec.ts:3:1 › uploads (1s)
  ✘  [webkit] › tests/example.spec.ts:3:1 › uploads (723ms)


  1) [chromium] › tests/example.spec.ts:3:1 › uploads ==============================================

    page.waitForEvent: Page crashed
    =========================== logs ===========================
    waiting for event "response"
    ============================================================

       9 |   await fileChooser.setFiles('./large_file');
      10 |   const [resp] = await Promise.all([
    > 11 |     page.waitForEvent('response'),
         |          ^
      12 |     page.locator('css=input[type=submit]').click(),
      13 |   ]);
      14 |

        at …/repro/tests/example.spec.ts:11:10

  2) [firefox] › tests/example.spec.ts:3:1 › uploads ===============================================

    elementHandle.setInputFiles: Protocol error (Page.setFileInputFiles): error in channel "content::page": exception while running method "setFileInputFiles" in namespace "page":  _setFileInputFiles/nsFiles<@chrome://juggler/content/content/PageAgent.js:449:66
    _setFileInputFiles@chrome://juggler/content/content/PageAgent.js:449:45
    _onMessage@chrome://juggler/content/SimpleChannel.js:165:37
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
     _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42


       7 |     page.locator('text=File').click(),
       8 |   ]);
    >  9 |   await fileChooser.setFiles('./large_file');
         |   ^
      10 |   const [resp] = await Promise.all([
      11 |     page.waitForEvent('response'),
      12 |     page.locator('css=input[type=submit]').click(),

        at …/repro/tests/example.spec.ts:9:3

  3) [webkit] › tests/example.spec.ts:3:1 › uploads ================================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 64000000
    Received: 0

      15 |   const { size } = await resp.json();
      16 |
    > 17 |   expect(size).toBe(64000000);
         |                ^
      18 | });
      19 |

        at …/repro/tests/example.spec.ts:17:16


  3 failed
    [chromium] › tests/example.spec.ts:3:1 › uploads ===============================================
    [firefox] › tests/example.spec.ts:3:1 › uploads ================================================
    [webkit] › tests/example.spec.ts:3:1 › uploads =================================================
```

If I upgrade to latest, it works.

**Comment by rwoll** [comment]
@italodeandra I was able to workaround the errors above. In 1.22+ we resolve setInputFiles paths internally to make sure everything works end-to-end with the browsers; however, prior to https://github.com/microsoft/playwright/commit/11179982fca60537022e503c1fb7e869e4a8bbd1, we did not do this. To workaround either:

1. install the @ next version of Playwright. (`npm i playwright@next` XOR `npm i @playwright/test@next` depending on which package you currently depend on)
2. XOR wrap your path in `path.resolve('<file to upload>')` to make it absolute for `setInputFiles`

Please try your code on @ next and let me know if it works out for you.

---

Debugging Notes:

Following up with the repro in https://github.com/microsoft/playwright/issues/13975#issuecomment-1118988471.

Bisected to the following npm releases:

broken: `@playwright/test@1.22.0-alpha-apr-14-2022`
working: `@playwright/test@1.22.0-alpha-apr-15-2022`

Changes: https://github.com/microsoft/playwright/compare/20dcc45...2f570fa

Commit that likely intro'd fix: https://github.com/microsoft/playwright/commit/11179982fca60537022e503c1fb7e869e4a8bbd1

Trying workaround:

```patch
diff --git a/tests/example.spec.ts b/tests/example.spec.ts
index 87023f4..57ce0b7 100644
--- a/tests/example.spec.ts
+++ b/tests/example.spec.ts
@@ -1,4 +1,5 @@
 import { expect, test } from '@playwright/test';
+import path from 'path';
 
 test('uploads', async ({ page }) => {
   await page.goto("/form");
@@ -6,7 +7,7 @@ test('uploads', async ({ page }) => {
     page.waitForEvent('filechooser'),
     page.locator('text=File').click(),
   ]);
-  await fileChooser.setFiles('./large_file');
+  await fileChooser.setFiles(path.resolve('./large_file'));
   const [resp] = await Promise.all([
     page.waitForEvent('response'),
     page.locator('css=input[type=submit]').click(),
```

passes the test. NB: This is not needed in 1.22+ since we do it internally (per https://github.com/microsoft/playwright/commit/11179982fca60537022e503c1fb7e869e4a8bbd1).

**Comment by rwoll** [comment]
(NB: I also tried the workaround with 10GB file (instead of just the 64MB file) and it appears to work, too. 🎉  )

**Comment by rwoll** [comment]
Closing per-above, but if you find the workaround does not work for you or if it's not working after upgrade (to either @ next or 1.22 when it comes out), please open a new issue referencing this issue #.

Cheers! 🎉

**Comment by italodeandra** [comment]
`@next` its working for me. 🎉
