### ISSUE TITLE
[Question] Conditionals in Playwright

### ISSUE THREAD

**Issue by Aenz99** [microsoft/playwright#13970]
hello guys,
I'm a newbie in Playwright
I am practicing conditionals with the Playwright page and cannot make it work.
What I want to do is to do something if the title has a text "Playwright" and do something else if not.
This is my code:

```
const { test, expect } = require('@playwright/test');

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');

   const titulo = await expect(page.locator('.navbar__inner .navbar__title')).toHaveText('Playwright')

   if (titulo) {
         console.log('it says Playwright');
}
    else{console.log('Not Playwright')}

    await page.pause();
});
```
Result: "not playwright"

Playwright understand this as "false"
Why the expect is not evaluated as "true" when "titulo" does indeed have the text "Playwright"?
I also tried with "toBeVisible" "toContainText", etc.
I tried also not using the "expect", just used the locator, it didn't work either.

I hope you can help me.
Thanks in advance
Cheers

**Comment by MindaugasMateika** [comment]
`.toHaveText (https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text) or any other assert on this matter doesn't return any values.

Take a look at textContent (https://playwright.dev/docs/api/class-locator#locator-text-content) or something similar which will return the value.

**Comment by rwoll** [comment]
Thanks @MindaugasMateika for the clarifications!

Closing this per the above recommendations, but feel free to re-open @Aenz99

**Comment by suryansh-bhatnagar** [comment]
Not working for me
