### ISSUE TITLE
[Question] run some tests parallel, others serially

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#13984]
I have some tests in a file which I would like to run parallel, while others would wait for those parallel tests to finish.

As an example, I have this

```
test.describe.parallel("parallel", function () {
	test("upload 1", async function () {});
	test("upload 2", async function () {});
});
test("check uploads", async function () {});
```

I would like the "parallel" tests to run, then "check uploads". However what happens is that 2 workers are spawned and it runs like this:

```
upload 1
check uploads
```

how do I get this
```
upload 1
upload 2
```

**Comment by unlikelyzero** [comment]
@A-ZC-Lau we've done this in other projects by way of annotations. 

We just label the serialized tests, in the case of playwright/test, that's as simple as adding a `@serial` annotation to the test name.
Run parallelized tests on CI Worker Pool A with something like `npm run tests:e2e:parallel`
Run serialized tests on CI Worker B with `npm run tests:e2e:serial`

Then, in your final stage of the pipeline, combine junit results.

**Comment by pavelfeldman** [comment]
Closing as per above.
