### ISSUE TITLE
[Question] How to switch the windows from one tab to another tab in same context.

### ISSUE THREAD

**Issue by Lakshmi-Yaswanth** [microsoft/playwright#13989]
Here  We are using two pages so called 
1.Common Page.
2.Login page.
In Common page we have written code for Switch tabes.
```
`async switchToWindow(locator: Locator, windowNumber: number) {
        const [multipage] = await Promise.all([
            this.page.waitForEvent('popup'),
            locator.click()
        ])
        await multipage.waitForLoadState();
        console.log(await multipage.title());
        const allwindows = this.page.context().pages();
        console.log("no.of windows: " + allwindows.length);
        allwindows.forEach(page => {
            console.log(page.url());
        });
        await allwindows[1].bringToFront();
        console.log(await allwindows[1].title());

    };`
```
This was used to Swift the tabs in  chrome.

Tests pages
```
test.describe("Validation for HomePage", () => {
    test("login as Vp_user", async ({ login, home, common }) => {
        await test.step('To verify user navigate to signup url', async () => {
            await common.coreAppInitialize();
            await common.loginIntoCore(environment.manageBatchTrainingAdmin, environment.password);
            await common.clickOnCaliberMenu(1);
        });
        await test.step('TC_018,TC_034 To verify Home page', async () => {
            await login.validationCaliberVPPage();
            await home.validateHomePage();
        });
});
});
```
Error  is:
RevaturePro | Batches
  1) [Caliber] › tests\home.test.ts:4:5 › Validation for HomePage › login as Vp_user ===============

    locator.waitFor: Timeout 100000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#home-link" to be visible
    ============================================================
First  test.step was passed when Shifting to next  test.step we have got failure.

Please can any one help me. Thank u .

**Comment by Lakshmi-Yaswanth** [comment]
For Example
![Screenshot (130)](https://user-images.githubusercontent.com/61179075/167287783-fe3e4c77-ad2d-45c3-8a17-fe4cadd3378b.png)
Here we have 2 tabs. When running script  we will click on Button that will open to new tab in  browser.
Here we have to pages such as page1 ,page2;
When running  the script in page1 it was working. But when shifting to page2 it was getting failed.
how to make this.page object == page2 which is another page.

**Comment by dgozman** [comment]
> how to make this.page object == page2 which is another page.

Just make two POM instances, e.g. `const login1 = new Login(page1); const login2 = new Login(page2);`. If you show us more code (your POM classes and custom fixtures), we'll be able to be more specific.

**Comment by Lakshmi-Yaswanth** [comment]
okk @dgozman 

Please look the code below: 

`Fixture.ts`
const test = baseTest.extend<{
    common: Common;
    login: LoginPage;
    home: HomeMenu;
}>({
    common: async ({ page }, use) => {
        await use(new Common(page));
    },
    login: async ({ page }, use) => {
        await use(new LoginPage(page));
    },
    home: async ({ page }, use) => {
        await use(new HomeMenu(page));
    }
});
`common.ts
 public async clickOnCaliberMenu(windowNumber: number) {
    const [multipage] = await Promise.all([
      this.page.waitForEvent('popup'),
      this.caliberBtn.click()
    ])
    await multipage.waitForLoadState();
    console.log(await multipage.title());
    const allwindows = this.page.context().pages();
    console.log("no.of windows: " + allwindows.length);
    allwindows.forEach(page => {
      console.log(page.url());
    });
    await allwindows[windowNumber].bringToFront();
    console.log(await allwindows[windowNumber].title());
    await allwindows[windowNumber].waitForTimeout(5000);
    return allwindows[windowNumber];
  };`
  `home.ts`
```
public async validateHomePage() {
        await this.assertTrue(this.canvasgraph);
        await this.assertTrue(this.locationdropdown);
        await this.assertTrue(this.missingGradingReport);
        await this.assertTrue(this.weekDisplay);
        await this.assertTrue(this.removeWeek.first());
    };
```
`home.test.ts`
```
test.describe("Validation of new Page", () => {
    test("ltest script ", async ({ login, home, common }) => {
        await test.step('First step', async () => {
            await common.clickOnCaliberMenu(1);
        });
        await test.step('Second Step', async () => {
            await login.validationCaliberVPPage();
            await home.validateHomePage();
        });
});
});
```

This is our project POM. 
We are able to switch to new tab using the first step. 
Issue:
We are unable to use the elements in the new tab/ New page opened in the second step. 
Is there anything we have to modify in fixtures.ts page to work on new tab.

**Comment by Lakshmi-Yaswanth** [comment]
@dgozman @mxschmitt  can anyone help me to overcome this problem. Thank you in regards

**Comment by mxschmitt** [comment]
Whats the reason you are bringing one page to the front or want to "switch pages"? In Playwright you don't need to switch, you can interact with pages and contexts in parallel.

**Comment by rwoll** [comment]
Closing per-above.
