### ISSUE TITLE
[BUG]: Unable to click web element though element is visible and stable 

### ISSUE THREAD

**Issue by prasadthakurnice** [microsoft/playwright#13990]
**Context:**
- Playwright Version: [latest]
- Operating System: [Windows]
- Node.js version: [16.14.2]
- Browser: [ Chromium]

Logs :
waiting for selector "//*[@id="root"]/div/main/div/div/div/div/button/p"
      selector resolved to visible <p class="MuiTypography-root MuiTypography-body1 cs…>Log In</p>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      <div class="makeStyles-loginContainer-11">…</div> intercepts pointer events
    retrying click action, attempt #1

**Code Snippet**

 */
      50 |   async ClickLoginButton() {
    > 51 |     await this.page.click(this._cxoneLoginButton);
         |                     ^
      52 |   }
      53 |

**Describe the bug**

Playwright is unable to click button though element is visible and stable as xpath given is  correct 
Code works on other machine but give error on my machine

**Comment by dgozman** [comment]
@prasadthakurnice Well, Playwright tells you that some element (should be described right before "intercepts pointer events" in the logs) does not allow to click on the target. I'd suggest to [record a trace](https://playwright.dev/docs/trace-viewer) and see yourself. If you believe there is a bug in Playwright, please provide a full repro that we can run locally to diagnose the issue.
