### ISSUE TITLE
[Question] Can not use decorator in playwright

### ISSUE THREAD

**Issue by jizhekai** [microsoft/playwright#13996]
I use decorator in my code, but get the error:  Support for the experimental syntax 'decorators-legacy' isn't currently enabled (9:3)

how can I fix it?

**Comment by vitalics** [comment]
@jizhekai please provide examples and use cases for recieving extended answer for your question.

**Comment by dgozman** [comment]
@jizhekai Decorators are not supported by Playwright, because there is no agreement between various decorator implementations for JavaScript. Perhaps it will make a way into the spec at some point?

For now, I'd suggest to not use decorators in the tests. Sorry for the inconvenience!

**Comment by ffMathy** [comment]
@dgozman decorators are heavily used with dependency injection. We can't use Playwright right now because we can't reference any of our existing code, since it has classes with `@injectable()` decorators.

Can we re-open this and track it?
