### ISSUE TITLE
[BUG] Firefox & Webkit not getting locator inside frame

### ISSUE THREAD

**Issue by garciallorente-fer** [microsoft/playwright#14000]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows
- Node.js version: 16.13.0
- Browser: Firefox & Webkit

**Code Snippet**

```javascript
const frameLocator = this.page.frameLocator('[id="card-number-element"] iframe');
const locator = frameLocator.locator('input[type=text][name=cardnumber]');
await locator.fill('some text'); // Fails ONLY in FIREFOX & WEBKIT
```

**Describe the bug**
I have a test case in which I work with elements inside frames, and the test works in Chromium but not in Firefox or Webkit

When doing await page.frameLocator(frameSelector).locator(frameElementSelector).fill() (or any other action) it works in Chromium but not in Firefox
Firefox getting next error:
With the trace on this is the information I get from it:

```
Action was interrupted
locator.fill
TIME
wall time: 04/05/2022, 17:43:19
duration: Timed Out
PARAMETERS
selector: "[id="card-number-element"] iframe >> control=enter-frame >> input[type=text][name=cardnumber]"
strict: true
value: "4000 0000 0000 0002"
LOG
waiting for frame "[id="card-number-element"] iframe"
selector resolved to visible <iframe scrolling="no" frameborder="0" allowtransparency…></iframe>
waiting for selector "[id="card-number-element"] iframe >> control=enter-frame >> input[type=text][name=cardnumber]"
```

**Comment by garciallorente-fer** [comment]
https://github.com/microsoft/playwright/issues/13351

**Comment by dgozman** [comment]
@garciallorente-fer Did you try to inspect the [snapshot](https://playwright.dev/docs/trace-viewer#snapshots) in the trace? You can right-click and choose "Inspect" to open Developer Tools for it - see what's inside, and why the element in question is not available. If you share the full repro with us, we can also take a look.

**Comment by garciallorente-fer** [comment]
Hello @dgozman , thanks for your reply, I did inspect the element to make sure it is there, and it is, it looks like the element should be available in Firefox & Webkit the same as it is available in Chromium, nothing seems different.

```
<div _ngcontent-mxh-c82="" id="card-number-element" class="stripe-input StripeElement StripeElement--empty">
  <div class="__PrivateStripeElement" style="margin: 0px !important; padding: 0px !important; border: medium none !important; display: block !important; background: transparent none repeat scroll 0% 0% !important; position: relative !important; opacity: 1 !important;">
    <iframe __playwright_src__="/snapshot/frame@af6ef9de26c904bcf355f0eb7cf12d27" name="__privateStripeFrame3765" allowtransparency="true" scrolling="no" title="Secure card number input frame" style="border: medium none !important; margin: 0px !important; padding: 0px !important; width: 1px !important; min-width: 100% !important; overflow: hidden !important; display: block !important; user-select: none !important; transform: translate(0px) !important; color-scheme: normal !important; height: 26px;" frameborder="0" src="http://127.0.0.1:9322/trace/snapshot/frame@af6ef9de26c904bcf355f0eb7cf12d27?trace=trace.zip&amp;name=after%40call%4010"></iframe>
    <input class="__PrivateStripeElement-input" aria-hidden="true" aria-label=" " autocomplete="false" maxlength="1" style="border: medium none !important; display: block !important; position: absolute !important; height: 1px !important; top: -1px !important; left: 0px !important; padding: 0px !important; margin: 0px !important; width: 100% !important; opacity: 0 !important; background: transparent none repeat scroll 0% 0% !important; pointer-events: none !important; font-size: 16px !important;">
  </div>
</div>
```

```
<div class="CardNumberField-input-wrapper">
  <span class="InputContainer" data-max="4242 4242 4242 4242 4240">
    <input class="InputElement is-empty Input Input--empty" autocomplete="cc-number" autocorrect="off" spellcheck="false" type="tel" name="cardnumber" data-elements-stable-field-name="cardNumber" aria-label="Credit or debit card number" placeholder="1234 1234 1234 1234" aria-invalid="false" value="">
  </span>
</div>
```

**Comment by mxschmitt** [comment]
Are you able to share with us a minimal repro? You can also try setting the `DEBUG=pw:api` env which might yield to more verbose logs.

**Comment by annervisser** [comment]
I'm experiencing the same issue. Haven't been able to make a simple repro.
The situation is angular -> iframe -> angular
I don't seem to be able to select *anything* within the iframe in firefox. but only on this specific page

**Comment by kachkaev** [comment]
Same issue here (Firefox, Playwright 1.24.0). My code looks somewhat like this:

```ts
  const frame = page.frameLocator("iframe[title='title']");
  await expect(frame.locator("input")).toBeVisible({ timeout: 10000 });
```

We raised the timeout to 10 and then 30 seconds hoping to avoid race condition but this did not help. The probability of a failure is about ≈5-10% and it seem to happen randomly.

When I open Trace Viewer for a failed test, snapshots look as if the iframe has not loaded. This hints on a problem with the app:

![Screenshot 2022-08-02 at 15 18 10 copy](https://user-images.githubusercontent.com/608862/182398434-9b7c13bd-43fd-4e52-80f1-30e0ac8ccde9.jpg)

However, if I hover timeline thumbnails, iframe contents show up in them 🤯:

https://user-images.githubusercontent.com/608862/182398776-6abdece1-d4d1-4cac-b908-dcfbe76adb58.mp4

Can it be an issue with Playwright? I only observed the problem in FF, not Webkit.

**Comment by dgozman** [comment]
@kachkaev Perhaps there is a bug in snapshot code that we would be happy to debug. How can I run this test locally to reproduce the issue?

**Comment by kachkaev** [comment]
Thanks for your reply @dgozman! I tried crafting more or less reliable repro steps in https://github.com/blockprotocol/blockprotocol/pull/483 but failed so far. CI fails after adding `--repeat-each 100` and focusing on just one test case. However, I can’t reproduce a trace in which I’ve see an input in a mini-screenshot, but a failed `frame.locator("input")`. 

This situation happened locally a couple of times, but the repro case was not reliable enough. I’ll keep watching CI results and update you here if I have any new findings.

Thanks again for your attention to this mystery! Playwright is awesome! 😍
