### ISSUE TITLE
[Question] subtree intercepts pointer events retrying click action

### ISSUE THREAD

**Issue by xflihaibo** [microsoft/playwright#14011]
--- 
waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  checking that element receives pointer events at (459.32,89)
  <input type="text" placeholder="请选择" class="el-cascader…/> from <div class="el-cascader__tags">…</div> 
  subtree intercepts pointer events
retrying click action, attempt #1
----

The element is in the visible area, but it has timed out all the time

**Comment by dgozman** [comment]
@xflihaibo Well, it says that `<input type="text" placeholder="请选择" class="el-cascader…/>` is on top of your target element and intercepts the click. Try looking for it in Developer Tools and see what's going on. You can also use [inspector](https://playwright.dev/docs/inspector) for easier debugging.
