### ISSUE TITLE
[BUG] CRBrowserContext does not fully close

### ISSUE THREAD

**Issue by b5414** [microsoft/playwright#14024]
**Context**
- Playwright Version: `1.21.1`
- Operating System: win
- Node.js version: 18
- Browser: chromium
- Extra: `"p-map": "4.0.0"`

**Code Snippet**

https://github.com/b5414/nodejs_playwright_memleak

**Describe the bug**

Probably - memory leak https://imgur.com/hlLEZdV

I don't know, maybe I'm stupid(and I'm closing the browser somehow wrong), but my technical task is to open 40 browsers (each with different parameters - for example), 10 at a time(thanks `pMap`), then repeat this cycle endlessly... 

So after ~500 browsers, I get 15MB of junk in RAM, and **this is with the empty code** 😿

**Comment by mxschmitt** [comment]
I think thats the same as https://github.com/microsoft/playwright-dotnet/issues/2132 and it gets fixed by https://github.com/microsoft/playwright/pull/13991.

**Comment by mxschmitt** [comment]
Thank you for your repro! I was verifying that before https://github.com/microsoft/playwright/pull/13991 it was the following:

```
[init] start
[cycle] creds length 50
[init] garbage collector, now 14.4144 (was 19.4218) MB
[cycle] creds length 50
[init] garbage collector, now 16.0379 (was 19.4051) MB
[cycle] creds length 50
[init] garbage collector, now 17.7495 (was 26.6036) MB
[cycle] creds length 50
[init] garbage collector, now 19.3720 (was 30.3394) MB
[cycle] creds length 50
[init] garbage collector, now 20.9473 (was 29.0183) MB
[init] done
```

And after https://github.com/microsoft/playwright/pull/13991 it was the following:

```
[init] start
[cycle] creds length 50
[init] garbage collector, now 11.9158 (was 14.8264) MB
[cycle] creds length 50
[init] garbage collector, now 12.0643 (was 19.7745) MB
[cycle] creds length 50
[init] garbage collector, now 12.1064 (was 13.1100) MB
[cycle] creds length 50
[init] garbage collector, now 12.1105 (was 22.7396) MB
[cycle] creds length 50
[init] garbage collector, now 12.1183 (was 22.3495) MB
[init] done
```

So it got already much better, the rest we could fix separately in different issues. You can consume the beta version via `npm install playwright@next`.

**Comment by b5414** [comment]
Thank you very much ❤
