### ISSUE TITLE
[BUG] API Page.fill() or Page.type() turns out a wrong result in input[number] element

### ISSUE THREAD

**Issue by KeisukeeLee** [microsoft/playwright#14028]
**Context:**
- Playwright Version: 1.21
- Operating System: Windows
- Python version: [3.10.1]
- Browser: [WebKit]
- Extra: [When I use Page.fill() or Page.type() API to fill a <input type="number"> element, the value changed to the maximum value of the element, rather the string value I set to it]

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
# The final result is the maximum value of the element --> 60, rather than -->20 
days = page.locator("//input[@type='number']").nth(0).fill("20")
```

**Describe the bug**

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Can you share a repro with us which we can run locally? Maybe there is user-land code involved which does it?
