### ISSUE TITLE
Playwright MS Docker image - webkit headless browser not launching with correct locale (en-GB) causing invalid dates

### ISSUE THREAD

**Issue by ptorrsmith** [microsoft/playwright#14029]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Ubuntu 20.04.4 LTS
- Node.js version: v16.14.2
- Browser: WebKit (headless)
- Extra: running `mcr.microsoft.com/playwright:v1.21.1-focal` docker image for headless testing and snapshot generation

```
## System:
 - OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 6.65 GB / 7.68 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.2 - /usr/bin/node
 - Yarn: 1.22.18 - /usr/bin/yarn
 - npm: 8.5.0 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
```

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {webkit} = require('playwright');

let page

// test.beforeAll(async ({ browser }) => {
  const context = await browser.newContext(
    {
        locale: 'en-GB',
    }
  );
  page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      <!-- some HTML/code to show the browser locale, sets a date such as `24/03/2022` and it shows correctly. This will be an invalid date if the locale is the default (en-US) -->
    </div>
  `);

  await page.locator(…);
})();
```

**Describe the bug**

We have a date picker which accepts a date in the format of the browser's locale.
We notice it would reject UK (NZ) dates (e.g. `24/03/2022` unless the browser's locale is set correctly (en-GB is good).
We have configured the playwright.config to configure the browser projects for each of the 3 browser types with the en-GB locale:
```
 {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
        locale: 'en-GB',
      },
    }
```

This means we can run the Playwright tests over a headless webkit browser locally on my MacBook (darwin) and our tests pass that the date is set correctly.
`yarn playwright test --project=webkit`

However, when running the test in the MS Playwright docker container, the test fails as the date is not considered valid.

We have configured our Dockerfile to install `locales` on the image and to set the LANG and LANGUAGE to en_GB.  
```
ENV LANG=en_GB.UTF-8
RUN apt-get install -y locales && \
    sed -i -e "s/# $LANG.*/$LANG UTF-8/" /etc/locale.gen && \
    dpkg-reconfigure --frontend=noninteractive locales && \
    update-locale LANG=$LANG
ENV LANG en_GB.UTF-8
ENV LANGUAGE en_GB.UTF-8
ENV LC_ALL en_GB.UTF-8

```
and when we run up the docker container and query `locale` we get the locale looking as expected
```
root@docker-desktop:/work# locale
LANG=en_GB
LANGUAGE=en_GB
LC_CTYPE="en_GB"
LC_NUMERIC="en_GB"
LC_TIME="en_GB"
LC_COLLATE="en_GB"
LC_MONETARY="en_GB"
LC_MESSAGES="en_GB"
LC_PAPER="en_GB"
LC_NAME="en_GB"
LC_ADDRESS="en_GB"
LC_TELEPHONE="en_GB"
LC_MEASUREMENT="en_GB"
LC_IDENTIFICATION="en_GB"
LC_ALL=en_GB
```

However when we run the playwright test with this container, it fails as it appears the headless webkit/safari browser is being created and not having the locale set to en_GB 

manually while running the container,
`yarn playwright test --project=webkit`

or scripted

`docker run --rm --network host -v $(pwd):/work/ -w /work/ -p 9323:9323 -it testing-automation_app-playwright /bin/bash -c 'yarn install && yarn playwright install && yarn playwright test --project=webkit'`

Add any other details about the problem here.

We can see the date picker failing in the video recordings Playwright generates. We used to see this fail in the videos in our local runs before we explicitly set the browser.newContext to `{ locale: 'en-GB' }` which fixed that, but not in the playwright image container)

**Comment by mxschmitt** [comment]
Can you share with us which date picker component you are using or which JS Date functions this component is using?

**Comment by ptorrsmith** [comment]
> Can you share with us which date picker component you are using or which JS Date functions this component is using?

Hi there.  We are using `"react-date-range": "1.0.0-beta"` (https://www.npmjs.com/package/react-date-range).

Works sweet headless (and headed) on webkit on local/darwin, just not on linux playwright docker image.  FYI, works headless on linux playwright docker image for chromium and firefox.

**Comment by mxschmitt** [comment]
I was able to repro that its not working inside Docker with WebKit, but since the library is quite big and it takes time to dig into it, I p3 it for now until we have a full minimal reproducible.

**Comment by akamud** [comment]
I'm having the same issue using Playwright's image on GitHub Action, but with Chromium browser. It is not setting the locale. I did all the `locales` installation in my container as mentioned in the original issue. The only difference is that I'm using `pt_BR` instead.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by akamud** [comment]
I fear that waiting to act on an issue reporting incorrect locale only when a required number of votes is reported is very prone to survivorship bias, people having this issue may not speak English at all in order to report the issue here.

The comment above states that a reproduction is easily available. I ask you to please reconsider closing this issue based on this, because this issue will probably never be fixed if we have to wait for a big vote count.
