### ISSUE TITLE
[BUG] E2E tests are getting slow after upgrading the latest Chrome Version 100 and above when the trace in ON in the configuration file

### ISSUE THREAD

**Issue by FahadRS** [microsoft/playwright#14037]
**Context:**

> Playwright Version: [1.21.1]
> Operating System: [Windows]
> Node.js version: [14.15.1]
> Browser: [Chrome]
> Chrome version: [Version 101.0.4951.54]

**Code Snippet**

    test('Demo Test Scenario:', async ({ page }) => { 
      await page.goto('https://usk.enterprisetube.com/');     
      await page.waitForSelector('[data-e2e-span="vidizmo-app"]', { state :  "attached" });     
      await page.click('[data-e2e-link="LoginSignInButton"]');     
      await page.fill('[data-e2e-input="emailAddress"]', 'fahad@sharklasers.com');     
      await page.fill('[data-e2e-input="Password"]', 'Admin@123');     
      await page.click('[data-e2e-btn="signIn"]');     
      await page.waitForSelector('[data-e2e-heading="MashupsMostMostRecent"]')               
      await page.click('[data-e2e-link="selectMenuBar"]');     
      await page.click('[data-e2e-link="MediaManager"]');          
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
      await page.click('[data-e2e-btn="toggleFilters"]');
    });  

**Describe the bug**
If we run the above code when the trace is on in the config then it completes within the 30-40 seconds, if the trace is off then it completes in the 7-8 seconds in the latest chrome version but in the chrome version 95 in both cases time is same 
following are the results of the test

**Chrome Version : Version 101.0.4951.54**
-------------------------------------------------------------------------------------------------------------------------------------------------
Trace **On** in config
takes **30-40** Seconds

Trace **off** in config
takes **7** Seconds

**Chrome Version : Version 95**
-------------------------------------------------------------------------------------------------------------------------------------------------
Trace **On** in config
takes **7** Seconds

Trace **off** in config
takes **7-8** Seconds

Configuration file 

    const config: PlaywrightTestConfig = {
      testDir: './tests',
      timeout: 30 * 1000,
      expect: {
        timeout: 5000
      },
      forbidOnly: !!process.env.CI,  
      workers: process.env.CI ? 1 : undefined,
      reporter: 'html',
      use: {
        actionTimeout: 0,
        channel : "chrome",
        trace: 'off',
      },
    };  
    export default config;

I can also provide the sample github repository if needed

This issue is related to following Bug #13498

**Comment by pavelfeldman** [comment]
My Linux bisect:
r963762 was GOOD
r963770 was BAD

https://chromium.googlesource.com/chromium/src/+log/28a843522cff38babad270c348b036bff58b8efe..a57dcff294d67641ad953cf4a008ce4133e96a4f

---

Mac+Linux
r963769 was GOOD
r963770 was BAD

---

r963770 is https://chromium.googlesource.com/chromium/src/+/a57dcff294d67641ad953cf4a008ce4133e96a4f

**Comment by pavelfeldman** [comment]
Bad profile: [bad_click.zip](https://github.com/microsoft/playwright/files/8665648/bad_click.zip)
Good profile: [good_click.zip](https://github.com/microsoft/playwright/files/8665649/good_click.zip)

**Comment by pavelfeldman** [comment]
Offender?: https://chromium.googlesource.com/chromium/src/+/f5101995acd21bd1d1bd8447087112e09bacfcbb
Review: https://chromium-review.googlesource.com/c/chromium/src/+/3416279
