### ISSUE TITLE
[Question] Have problem running tests in folder outside Playwright directory

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#14039]
Hi,

I am filing this as a question to seek clarification.

I am interested in running Playwright with the tests located in another directory outside of the playwright installation. I found the option called --config {dir} that seems to describe what I need.

In the description of the cli, https://playwright.dev/docs/test-cli there are 2 options with the same name:

A) -c {file} or --config {file}: Configuration file. If not passed, defaults to playwright.config.ts or playwright.config.js in the current directory.
B) -c {dir} or --config {dir}: Directory with the tests to run without configuration file.

I had assumed that Playwright would check for the type of argument, file or directory, to distinguish between
those 2 uses.

However, when I want to get the (B) functionality, and use --config {dir}, it seems to be interpreted as a configuration file and therefore fails with syntax error in the configuration file.

There are several possible reasons :
1) This is a documentation error
2) Maybe --config {dir} option can be exposed with a different name, say --tconfig.

Hope someone in the team can take a look and provide clarification.
Thanks for all your hard work!

**Comment by mxschmitt** [comment]
How do you pass the config directory over to the Playwright Test CLI? I was checking the code and both options are supported. Internally we check if the passed path is a file or directory on the file system.

**Comment by khtan** [comment]
Hi, I realized that I mischaracterized the problem and have updated the title. In the next comment, I will put the problem description and a zip file to reproduce the problem.

**Comment by khtan** [comment]
# Table of Contents

1.  [Q) Have problems running tests in folder outside playwright directory](#orgea53318)
    1.  [Transcripts](#orgc0493f7)
        1.  [Unable to run outside folder ..\pw4tests folder ( using backslashed relative paths )](#org1961409)
        2.  [Unable to run outside folder ../pw4tests folder ( using forward slashed relative paths )](#orgfe8fcce)
        3.  [Able to run local 'test2' directory using &#x2013;config <file> and &#x2013;config <dir>](#org9198980)
        4.  [Able to run local 'test' directory by default](#orgf87d703)


<a id="orgea53318"></a>

# Q) Have problems running tests in folder outside playwright directory

In the description of the cli, <https://playwright.dev/docs/test-cli>, I can specify a test directory independently
with -c {dir} or &#x2013;config {dir}: Directory with the tests to run without configuration file.

In this reproProblem folder, I have the Playwright setup in "pw4" and the tests in "pw4tests/tests".
There are local test directories 'pw4/test', 'pw4/test2', and one outside the repo folder '../pw4tests/tests'

The tree command shows this in a better way : 

c:\cprojects\github\khtan-private\LearningPlaywright\ts\reproProblem>tree /f .

    Folder PATH listing
    Volume serial number is 00000001 22B2:40C1
    C:\CPROJECTS\GITHUB\KHTAN-PRIVATE\LEARNINGPLAYWRIGHT\TS\REPROPROBLEM
    │   readme.org
    │
    ├───pw4
    │   │   package-lock.json
    │   │   package.json
    │   │   playwright.config.ts
    │   │
    │   ├───tests
    │   │       example.spec.ts
    │   │
    │   └───tests2
    │           example2.spec.ts
    │
    └───pw4tests
        └───tests
                example.spec.ts

In all cases, I use both &#x2013;config {file} to point to the configuration file and &#x2013;config {dir} to point to the
test directory.


<a id="orgc0493f7"></a>

## Transcripts


<a id="org1961409"></a>

### Unable to run outside folder ..\pw4tests folder ( using backslashed relative paths )

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ..\pw4tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================


<a id="orgfe8fcce"></a>

### Unable to run outside folder ../pw4tests folder ( using forward slashed relative paths )

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ../pw4tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================
    
    
    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ../pw4tests/tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================


<a id="org9198980"></a>

### Able to run local 'test2' directory using &#x2013;config <file> and &#x2013;config <dir>

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config tests2
    
    Running 1 test using 1 worker
    
      ✓  [chromium] › example2.spec.ts:14:3 › New2 › should clear text input field when an item is added (1s)
    
    
      1 passed (2s)


<a id="orgf87d703"></a>

### Able to run local 'test' directory by default

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts
    
    Running 1 test using 1 worker
    
      ✓  [chromium] › example.spec.ts:14:3 › New1 › should allow me to add todo items (995ms)
    
    
      1 passed (2s)
[reproProblem.zip](https://github.com/microsoft/playwright/files/8693985/reproProblem.zip)

**Comment by khtan** [comment]
# Table of Contents

1.  [Q) Have problems running tests in folder outside playwright directory](#orgb0305fb)
    1.  [Transcripts](#orge26534a)
        1.  [Unable to run outside folder ..\pw4tests folder ( using backslashed relative paths )](#org632a006)
        2.  [Unable to run outside folder ../pw4tests folder ( using forward slashed relative paths )](#org533bbdc)
        3.  [Able to run local 'test2' directory using &#x2013;config {file} and &#x2013;config {dir}](#org926d160)
        4.  [Able to run local 'test' directory by default](#org29e6818)


<a id="orgb0305fb"></a>

# Q) Have problems running tests in folder outside playwright directory

In the description of the cli, <https://playwright.dev/docs/test-cli>, I can specify a test directory independently
with -c {dir} or &#x2013;config {dir}: Directory with the tests to run without configuration file.

In this reproProblem folder, I have the Playwright setup in "pw4" and the tests in "pw4tests/tests".
There are local test directories 'pw4/test', 'pw4/test2', and one outside the repo folder '../pw4tests/tests'

The tree command shows this in a better way : 

c:\cprojects\github\khtan-private\LearningPlaywright\ts\reproProblem>tree /f .

    Folder PATH listing
    Volume serial number is 00000001 22B2:40C1
    C:\CPROJECTS\GITHUB\KHTAN-PRIVATE\LEARNINGPLAYWRIGHT\TS\REPROPROBLEM
    │   readme.org
    │
    ├───pw4
    │   │   package-lock.json
    │   │   package.json
    │   │   playwright.config.ts
    │   │
    │   ├───tests
    │   │       example.spec.ts
    │   │
    │   └───tests2
    │           example2.spec.ts
    │
    └───pw4tests
        └───tests
                example.spec.ts

In all cases, I use both &#x2013;config {file} to point to the configuration file and &#x2013;config {dir} to point to the
test directory.


<a id="orge26534a"></a>

## Transcripts


<a id="org632a006"></a>

### Unable to run outside folder ..\pw4tests folder ( using backslashed relative paths )

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ..\pw4tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================


<a id="org533bbdc"></a>

### Unable to run outside folder ../pw4tests folder ( using forward slashed relative paths )

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ../pw4tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================
    
    
    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config ../pw4tests/tests
    
    Running 0 test using 0 worker
    
    
    Error: Cannot find module '@playwright/test'
    Require stack:
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\loader.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\runner.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\lib\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\lib\cli\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\playwright-core\cli.js
    - c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4\node_modules\@playwright\test\cli.js
    
        at Object.<anonymous> (c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4tests\tests\example.spec.ts:1:1)
    
    =================
     no tests found.
    =================


<a id="org926d160"></a>

### Able to run local 'test2' directory using &#x2013;config {file} and &#x2013;config {dir}

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts --config tests2
    
    Running 1 test using 1 worker
    
      ✓  [chromium] › example2.spec.ts:14:3 › New2 › should clear text input field when an item is added (1s)
    
    
      1 passed (2s)


<a id="org29e6818"></a>

### Able to run local 'test' directory by default

    c:\cprojects\github\khtan-private\LearningPlaywright\ts\pw4>npx playwright test --browser chromium --config playwright.config.ts
    
    Running 1 test using 1 worker
    
      ✓  [chromium] › example.spec.ts:14:3 › New1 › should allow me to add todo items (995ms)
    
    
      1 passed (2s)
[reproProblem.zip](https://github.com/microsoft/playwright/files/8693997/reproProblem.zip)

**Comment by khtan** [comment]
Apologies, I accidentally closed this ticket and had to re-open it again. Hope it did not trigger too many notifications.

**Comment by mxschmitt** [comment]
This seems the same as https://github.com/microsoft/playwright/issues/14181, so folding into it.

**Comment by khtan** [comment]
Q1) Can both options be used at the same time?
Q2) Does it matter whether the directory is outside the working folder?

I will retest this weekend and report back. Hope the delay will not close
this ticket.

Thanks,
