### ISSUE TITLE
[internal] WebKit on Mac 12.2 with ARM is failing

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#14030]
Last good (https://github.com/microsoft/playwright/commit/c9429283d736ff7a53200b9a94bb01b42b4e49a7): https://github.com/microsoft/playwright-internal/runs/6298555941?check_suite_focus=true
First bad (https://github.com/microsoft/playwright/commit/969e6f2ada09122f43fe832ad83c5898f92afed7): https://github.com/microsoft/playwright-internal/runs/6298760117?check_suite_focus=true

Diff: https://github.com/microsoft/playwright/compare/c9429283d736ff7a53200b9a94bb01b42b4e49a7..969e6f2ada09122f43fe832ad83c5898f92afed7

So between WebKit revision 1632 and 1637.

Error: `Symbol not found: __CFURLStorageSessionDisableCache`.

**Comment by aslushnikov** [comment]
Yep, this seems to be due to using xcode 13.3 for webkit; I'll fallback to 13.2.

**Comment by aslushnikov** [comment]
Fixed with 1641 build

**Comment by mxschmitt** [comment]
@damaon we only support the latest minor releases. This means you need to update to 12.6.8 or 13.5.1 as of today.

Having an up to date system is important to have all the security patches installed.
