### ISSUE TITLE
[BUG] navigation to about:blank in headed hangs

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#14047]
Repro steps:

1. ```npm init -y && npm i playwright@1.22.0-alpha-1652115973000```

2. ```vim test.mjs```

```js
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto('about:blank');
  await browser.close();
})();
```

3. ```node test.mjs```

Bisect: https://chromium.googlesource.com/chromium/src/+log/c932654a16474815d92f582dd474386cc28770c3..2ec610f785e814658ed1ddef125bca1decc523c7

Offending: https://chromium.googlesource.com/chromium/src/+/4a5fef2495c176ca02e73fbc98a7787e5d5bde44

Review: https://chromium-review.googlesource.com/c/chromium/src/+/3341866

**Comment by Kolic822** [comment]
I still have this problem with    "@playwright/test": "^1.29.2" in chromium
