### ISSUE TITLE
[Feature] :has-exact-text("text")

### ISSUE THREAD

**Issue by nico-olivares** [microsoft/playwright#14044]
One of the most useful text selectors is :has-text("text").
It lets me select larger components based on any inner text no matter how far down the tree it may be. It is extremely useful.
There are times though when being able to use this feature with exact text would be even more powerful. I haven't been able to find a different way of accomplishing this.
For example:
```
<div class="outer">
   <p>Id</p>
   <svg />
</div>
<div class="outer">
   <p>Ideal</p>
   <svg />
</div>
```
Currently grabbing the <div> with text="Id" is possible, but not easy.
Grabbing the one with text="Ideal" on the other hand is very easy.

`let idealDiv = page.locator('.outer:has-text("Ideal")')`

It would be great to have the same functionality with an exact match.
Something like:

`let idDiv = page.locator('.outer:has-exact-text("Id")')`

That way you could grab exactly the component you want, and then have access to each svg for example, which is why I use this feature so much.

**Comment by ltsuda** [comment]
Please, could try the following?

```javascript
const _id = page.locator('.outer:text-is("Id")')
// or
const _id = page.locator('.outer', { hasText: /Id/ } )
// or
const _id = page.locator('.outer').locator('text="Id"')  // pay attention to the double quotes around the text Id
```
https://playwright.dev/docs/selectors#text-selector
https://playwright.dev/docs/api/class-page#page-locator

**Comment by nico-olivares** [comment]
None of those worked for me. I'll try more tests tomorrow.
`:text-is` is supposed to do what I am requesting, but it has never worked for me. The documentation isn't very clear about what level of the tree is captured, if the smallest element or the one preceding the `:text-is`. If it is the one preceding the command then this is it, but I have tried it before and it doesn't work for me. It doesn't capture anything. Again, I'll try again tomorrow. Thanks for the ideas.

**Comment by ltsuda** [comment]
I'm sorry, I did send you the wrong way to use it some of them. I didn't test before, the following code is tested :)

```javascript
        let outerTextIs = page.locator('.outer :text-is("Id")')  // it was missing a space between ".outer" and ":text-is"
        await expect(outerTextIs).toHaveText("Id")

        let outerHasText = page.locator(".outer", { has: page.locator('text="Id"') }) // see edited comment before
        await expect(outerHasText).toHaveText("Id")

        let outerText = page.locator(".outer").locator('text="Id"') // this was correct in the comment before
        await expect(outerText).toHaveText("Id")
``` 

```javascript
// test.spec.js

const { test, expect } = require("@playwright/test")

test.describe("Testing", () => {
    test("new testing", async ({ page }) => {
        await page.setContent(`
                <div class="outer">
                    <p>Id</p>
                    <svg />
                </div>
                <div class="outer">
                    <p>Ideal</p>
                    <svg />
                </div>
        `)
        let outerTextIs = page.locator('.outer :text-is("Id")')
        await expect(outerTextIs).toHaveText("Id")
        console.log(await outerTextIs.count())

        let outerHasText = page.locator(".outer", { has: page.locator('text="Id"') })
        await expect(outerHasText).toHaveText("Id")
        console.log(await outerHasText.count())

        let outerText = page.locator(".outer").locator('text="Id"')
        await expect(outerText).toHaveText("Id")
        console.log(await outerText.count())
    })
})
```

```bash
❯ npx playwright test

Running 1 test using 1 worker
[chromium] › example.spec.js:6:5 › Testing › new testing
1
1
1

  1 passed (441ms)

To open last HTML report run:

  npx playwright show-report
```

**Comment by wozprzemek** [comment]
Hello, I also ran into this issue myself and the solutions provided here, while helpful, didn't fully work for me.

I would be willing to take up the task of implementing this feature, could this issue be reopened?

**Comment by sergtimosh** [comment]
Why not use regex to match exact element?

```ts
 outerByExactText = (text: string) => page.locator( ".outer", { hasText: new RegExp(`^${text}$`) });
```
