### ISSUE TITLE
[Question] How can i use this HTML report in python?

### ISSUE THREAD

**Issue by kisscelia** [microsoft/playwright#14046]
really love this HTML report which generated by playwright.
how can i use it in python?
:)

**Comment by ltsuda** [comment]
The HTML reporter is exclusive for the Playwright@Test runner (Node).

There might be some HTML reporter for python/pytest, like Allure Report but I think you will need to customize the pytest output to attach any screenshot into the report.

**Comment by kisscelia** [comment]
> The HTML reporter is exclusive for the Playwright@Test runner (Node).
> 
> There might be some HTML reporter for python/pytest, like Allure Report but I think you will need to customize the pytest output to attach any screenshot into the report.

Thanks for your reply.
Yes, I can use allure, but i can't add the report as an attachment when i send email. And pytest-html's CSS is simple.  :(

**Comment by mxschmitt** [comment]
The HTML report is not available in Python. If you are interested in a html report, I recommend filing a feature request for it here: https://github.com/microsoft/playwright-python

**Comment by kisscelia** [comment]
> 

OK, Thanks.
