### ISSUE TITLE
[Question] Persist Auth from Session Storage?

### ISSUE THREAD

**Issue by taigi100** [microsoft/playwright#14062]
I have seen the docs on this: [https://playwright.dev/docs/auth#session-storage](https://playwright.dev/docs/auth#session-storage).

However, I am a bit lost at the location I should add the hook for `addInitScript`.

I have tried adding it in: `beforeAll`, the test itself, overriding the context fixture. However, none seem to work.
Where would be the proper place to place this hook? 

```
const test = base.extend({
  // override `context` fixture to add init script
  context: async ({ context }, use) => {
    await context.addInitScript(() => {
      const entries = JSON.parse(process.env.SESSION_STORAGE);
      for (const [key, value] of Object.entries(entries)) {
         window.sessionStorage.setItem(key, value);
      }
    });
    await use(context);
  },
});
```

This is the attempt with overriding. If I add a `console.log` inside the `initScript fn` it doesn't show anything, if I add it outside, it works.
Also, the session storage seems to have values, it's just that they are all set on `null`. The value from the environmental variable is correct.

**Comment by mxschmitt** [comment]
The `process.env. SESSION_STORAGE` can't be inside the addInitScript, it needs to be outside, since addInitScript runs inside the browser JavaScript engine and you want to have it inside the Node.js one.

The reason why console log there is not working is because it runs inside the browser JS engine, this means like logs stay there, you can redirect them with `page.on("console", console.log)` or just open Chrome DevTools.

using override fixtures is actually a good place to put it, if you want to have it for all of your tests.

See here: https://playwright.dev/docs/evaluating

**Comment by Citronex** [comment]
> Thanks a bunch, it is exactly what I needed!

Would you mind sharing how you did it? I'm having a similar issue. Thank you!

**Comment by taigi100** [comment]
@Citronex 
Not sure if this is best practices, it works.
In every test suite I have, on a `beforeAll` I do a login and save the session in an environmental variable as per the docs:
```
export async function loginAndSaveSession(browser: Browser) {
  const page = await browser.newPage();
  const context = await browser.newContext();
  await login(page);
  await saveSession(page);
  await context.close();
  await page.close();
}
```
Then, to properly load the session on every test, I override the fixture:
```
export const test = base.extend({
  // override `context` fixture to add init script
  context: async ({ context }, use) => {
    const sessionStorage = process.env.SESSION_STORAGE;
    await context.addInitScript((storage: string) => {
      const entries = Object.entries(JSON.parse(storage));
      for (let i = 0; i < entries.length; i += 1) {
        const [key, value]: [key: string, value: any] = entries[i];
        window.sessionStorage.setItem(key, value);
      }
    }, sessionStorage);
    await use(context);
  },
});
```
