### ISSUE TITLE
Playwright test command is not working when we pass less than 3 arguments

### ISSUE THREAD

**Issue by raiajithkumarr** [microsoft/playwright#14070]
Hi Team,
While working on E2E with playwright and running test by passing arguments  as mentioned below.

yarn playwright test "securekey1" or npx playwright test "securekey1" is not working as expected and it is showing result as shown below.

Running 0 test using 0 worker
=================
 no tests found.
=================

But if we pass more than or equal 3 arguments it is working fine  for example : 
**yarn playwright test "securekey1" "1" "2"** or **npx playwright test "securekey1" "1" "2"**

please let me know what might be the reason for this behavior.

**Comment by gauravgandhi1315** [comment]
may be try with `npx playwright test "tests/securekey1"`

**Comment by raiajithkumarr** [comment]
Here  I am passing arguments to tests and those values are set at global level for example

yarn playwright test -- "url" "username" "password" like this here if we pass 3 argument more than 1 character or any number it is not working.

**Comment by mxschmitt** [comment]
Passing arguments in the sense that you can use them inside your tests is not working like that. You need to pass them as environment variables. See here for that feature request: https://github.com/microsoft/playwright/issues/10337

If you pass CLI arguments after `npx playwright test` it will act as a filter for file names, see here: https://playwright.dev/docs/test-cli

**Comment by raiajithkumarr** [comment]
Yes Max Schmitt thank for information and just for your information, I have done some thing earlier.
And also I was exploring this argument type.
