### ISSUE TITLE
[Feature] Load custom selectors automatically within Trace Viewer

### ISSUE THREAD

**Issue by nzacca** [microsoft/playwright#14086]
Hello!

Would it be possible to somehow automatically load custom selectors within the Trace Viewer environment so that we can use the `playwright.locator` helper from dev tools with our custom selectors? We often use devtools during the debugging process to troubleshoot selectors and since our custom selectors are not loaded automatically, it makes it cumbersome to query a selector that is failing.

Thank you!

**Comment by mxschmitt** [comment]
Sounds very similar to https://github.com/microsoft/playwright/issues/7853 but you use Chrome DevTools to find out selectors if I understand it correctly?

**Comment by nzacca** [comment]
@mxschmitt 

Ya, that would work for us if the `Explore` input can resolve custom selectors. We use devtools in the Trace Viewer because there's nothing currently there to help us debug selectors. I'll close this out and upvote the other one.

Thank you!
