### ISSUE TITLE
[Question] how to navigate to back and forward in browser using Playwright?

### ISSUE THREAD

**Issue by shivkumar-jirwankar** [microsoft/playwright#14089]
Is there any function available in Playwright which allows to navigate back and forward in browser? Or any function which performs the click operation on back, forward, reload button of browser?

**Comment by geromegrignon** [comment]
Hi @shivkumar-jirwankar,

You can use `page.goBack()` and `page.goForward()`.

[Documentation](https://playwright.dev/docs/api/class-page#page-go-back)

**Comment by shivkumar-jirwankar** [comment]
Thank you @geromegrignon , I guess I somehow did not spot this in the documentation :)
