### ISSUE TITLE
global-setup possible issue 

### ISSUE THREAD

**Issue by ThomasAK** [microsoft/playwright#14082]
i am trying to use global set up to initialize a oracle db pool.  It looks like the global set up does run the init but when i try to use the pool it says pool alias not found.  Now if i init the pool at the beginning of my test then i am able to use the pool alias i initialized.  So it looks like it is initializing it in the global set up but then it disappears and is not useable.

**Comment by bshostak** [comment]
FYI, this relates to #12785

**Comment by mxschmitt** [comment]
Playwright is just a program, it'll run globalSetup, then it'll run tests and then it'll run globalTeardown. If running setup or teardown fails, it would be failing the test run. So I'd suggest that you manually run globalSetup /teardown in a standalone program to make sure your script works:

```js
// main.js
const globalSetup = require('./global-setup');
const globalTeardown = require('./global-teardown');
async(() => {
  await globalSetup();
  await globaTeardown();
});
```

`node script.js`

It is likely to fail with the same error.
