### ISSUE TITLE
[Feature] Scrape URLs directly using Sitemap.XML

### ISSUE THREAD

**Issue by deadcoder0904** [microsoft/playwright#1408]
I’d like to scrape directly using `sitemap.xml` just like I can do by using Python’s [Scrapy](https://scrapy.org).

I think this should be built-in to Playwright since it’s such a common thing to do when it comes to scraping :)

**Comment by mxschmitt** [comment]
I don't think, that such niece things should be added to Playwright itself. It's basically just fetching the sitemap.xml, parsing it and looping over it which can be done for example by using this library: https://github.com/seantomburke/sitemapper

**Comment by deadcoder0904** [comment]
Yep, I got it working with `sitemapper` itself but I do think that it’s so common that it should be built-in like Scrapy

**Comment by lupinhex** [comment]
if you wold like to scrape directly using sitemap.xml, you know beforehand the website support it or  must check it first, then parse the xml using any nodejs library and create a list to iterate using page.goto(). I don't think it's a good idea to add features for things are easy to add externally and avoid keeping code that only people who use crawlers are interested. I see playwright or puppeteer as an automation framework not as an end tool for things like that.

**Comment by deadcoder0904** [comment]
Oh, okay makes sense. Cool, I’ll close this one then :)
