### ISSUE TITLE
[BUG] Screenshot comparison fails randomly because of some invisible difference. Diff shows a red line across the Screenshot. 

### ISSUE THREAD

**Issue by Basti098765** [microsoft/playwright#14094]
**Context:**
- Playwright Version: 1.21.1
- Browser: All

Hello,
I have an issue with the visual comparison. We have quite a few visual tests that usually run without a problem but since the last update I have seen some strange behavior in some of those tests. At some point the test fails and shows a difference of a few hundred pixels. If I compare the screenshots I don't see anything different between _expected_ and _actual_. In the diff I see a random red line spanning across the screenshot but there is no change visible there. I have noticed those failures in various tests across different browsers and I can't find anything in common with all the failing tests. Most of the time the change is gone after a rerun. But those things keep appearing randomly throughout the tests. 
Actual: 
![opening-closing-opening-actual](https://user-images.githubusercontent.com/36666181/167840755-643ddb30-4841-4377-af27-d347f5d50caf.png)
Diff:
![opening-closing-opening-diff](https://user-images.githubusercontent.com/36666181/167840759-6b094a10-6108-4a3c-9ff8-b9327fc246b9.png)
Expected:
![opening-closing-opening-expected](https://user-images.githubusercontent.com/36666181/167840761-543fa282-9756-435c-a95c-67dce3f689fe.png)

**Comment by mxschmitt** [comment]
> last update

do you mean between 1.21 and 1.22?

---

Are you able to share a minimal reproducible with us which we can run locally? this would help us a lot to dig into that issue.

**Comment by Basti098765** [comment]
> > last update
> 
> do you mean between 1.21 and 1.22?
> 
> Are you able to share a minimal reproducible with us which we can run locally? this would help us a lot to dig into that issue.

It worked fine on Playwright 1.19.2 but since 1.21.1 those test fails keep popping up. 
 
Its really hard to find a reproducible piece of code where it comes up consistently. I run around 400 visual tests on various components and after every second or third run in the CI another random Test fails with an error because the screenshots do not match and it shows a red line like above in the diff. I have seen it on very basic tests where it is mostly just styled text and the test is a simple 
```
page.goto(pageUrl);  
const screenshot = await page.locator(scTarget).screenshot(screenshotOptions);
expect(screenshot).toMatchSnapshot('${testInfo.title}.png');
```
But it also happens on really complex tests with overlay containers and other stuff.

I think it happens more often when there are many pipelines running the tests at the same time but maybe I just see them more often then so not sure. And I see it more frequently in Firefox although it happens in chrome as well form time to time. Sorry that I cannot provide more info.

**Comment by mxschmitt** [comment]
toHaveScreenshot should also be a solution for it, since it has automatic retries included.

Browser rendering is not always deterministic :/

**Comment by Basti098765** [comment]
`toHaveScreenshot` improved the Situation. Have not seen those fails since the change.
