### ISSUE TITLE
[BUG] headless option inside test function argument always undefined, even with --headed parameter

### ISSUE THREAD

**Issue by stijnvanderlaan** [microsoft/playwright#14099]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Mac
- Node.js version: v16.13.0
- Browser: All

**Code Snippet**

```javascript

import { test, expect } from '@playwright/test'

test('Happy flow', async ({ page, context, headless, launchOptions }) => {
  console.log("headless", headless, launchOptions.headless)
  if (headless) {
    expect(await page.screenshot()).toMatchSnapshot()
  }
})
```

**Describe the bug**

I like to detect if the browser is running in headed mode, but headless is always undefined when not set in playwright.config.js, even if you run it with the --headed argument:
```
npx playwright test  --headed
```

**Comment by pavelfeldman** [comment]
Following works for me:

```js
test('test', async ({ page, headless }) => {
  console.log(headless);
});
```
