### ISSUE TITLE
[Question] How to fix "page.goto:  Couldn't resolve proxy name" for webkit under windows?

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#14119]
For `webkit-1630` i get the error message

```
page.goto:  Couldn't resolve proxy name
```
The others browsers `chromium-1000` and `firefox-1322` are working fine.  All browsers are saved under `%userprofile%\AppData\Local\ms-playwright`

## Question 

 1. What has to be done so that webkit under windows can read the proxy variable (`PS C:\> $env:HTTPS_PROXY`)?

### Workaround

For a quick fix i changed  the playwright.config.js file inside the test-project. 

```
  projects: [
        { name: 'chromium', use: { ...devices['Desktop Chrome'], }, },
        { name: 'firefox', use: { ...devices['Desktop Firefox'], }, },
        // { name: 'webkit', use: { ...devices['Desktop Safari'], }, },  <-- webkit removed 
```

As you can see i added a comment in front of `webkit` inside `playwright.config.js`. Running  `PS C:\dev\webtest\new-project> npx playwright test`  works without any errors now.

### Screenshot  of error message

![image](https://user-images.githubusercontent.com/1271555/168075415-a4cb950f-fa3f-435c-8ec9-7e4894ff4b2d.png)

**Comment by mxschmitt** [comment]
So you have a proxy server set and the proxy server requires to be resolved I guess? (so its not an IP)

**Comment by surfmuggle** [comment]
Yes the connection from my pc is routed through a proxy that requires user authentication. 
Based on other issues 
 - [GO: proxyconnect tcp: tls: first record does not look like a TLS handshake](https://stackoverflow.com/questions/77206983) and 
 - [Deno: failed to add platform cert to root cert store: InvalidCertificate BadEncoding](https://github.com/denoland/deno/issues/20709)

i assume that the root cause is that the the connection between my pc, the proxy and the target server is flawed / not correctly established to meet TLS requirements.
