### ISSUE TITLE
[BUG] Allure reporter screenDiff plugin doesn't work with Playwright version higher than 1.20.2

### ISSUE THREAD

**Issue by ivan-krupskyi** [microsoft/playwright#14127]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows and Mac
- Node.js version: v16.14.2
- Browser: any
- Extra: "allure-playwright": "^2.0.0-beta.16", "allure-commandline": "^2.17.2"

Hi guys!

Since moving from version 1.20.2 to 1.21.1 my allure reports broke and **screenDiff plugin for allure report stopped working.**
On version 1.20.2 everything was working fine out of the box. Now it doesn't.
I have tried to switch between versions of all packages (allure-commandline, allure-playwright, @playwright/test) and identified that **the problem is @playwright/test**

My playwright.config.js contains this:
- reporter: [['list'], ['allure-playwright']],

My package.json has next dependencies:
- "@playwright/test": "^1.20.2",
- "allure-commandline": "^2.17.2",
- "allure-playwright": "^2.0.0-beta.16",
- "jest-expect-message": "^1.0.2"

My test:
`test('Visual comparison of winners page @visual-regression', async ({page}) => 
{
        await page.goto('/pages/winners', {timeout: 15000, waitUntil: 'networkidle'});
        expect(await page.screenshot({fullPage: true})).toMatchSnapshot();
    });`

Running allure report with next command:
- npx allure generate ./allure-results --clean && npx allure open ./allure-report

Here is screenshot of screenDiff on Playwright version 1.20.2 :
![Screen Shot 2022-05-12 at 16 49 40](https://user-images.githubusercontent.com/102296081/168116560-9d1cf3ba-0e09-4bb2-84b2-64b7b145cf25.png)

Here is screenshot for Playwright 1.21.1 : 
![Screen Shot 2022-05-12 at 16 51 34](https://user-images.githubusercontent.com/102296081/168116924-18c7a1c6-4f5d-4c17-b69e-99c96ecd0e4f.png)

**I can provide more info if you need**, but reproducing this is very easy. Just run a basic visual-comparison test with allure reporter. To see the difference, first run your test on Playwright 1.20.2, and then on Playwright 1.21.1

Thank you!

**Comment by ivan-krupskyi** [comment]
Playwright 1.20.2 Allure-Results folder:
[allure-results.zip](https://github.com/microsoft/playwright/files/8680783/allure-results.zip)

Playwright 1.21.1 Allure-Results folder:
[allure-results-2.zip](https://github.com/microsoft/playwright/files/8680792/allure-results-2.zip)

**Comment by mxschmitt** [comment]
Analysation: This is probably broken since https://github.com/microsoft/playwright/pull/13202 and inside the playwright-allure reporter we add the image diff only if the attachment name `=== 'diff'`. This needs to be fixed inside the Allure plugin.

https://github.com/allure-framework/allure-js/blob/e3618fafe28220602521a3c6366ec1c0ab9cc48b/packages/allure-playwright/src/index.ts#L152-L154

**Comment by ivan-krupskyi** [comment]
@mxschmitt,
actually, I have applied the change to the source code in npm_modules (from you fix)
And issue is still there.

What happens is, "screenshotDiff" label is added now, BUT for screenDiff plugin to work, attachment names should have next "name" property - "actual", "expected" and "diff" - which is not the case even with your fix:

the ones that are highlighted must be named as: "actual", "expected" and "diff", but they are not, they only have that suffix
<img width="834" alt="Screen Shot 2022-05-12 at 23 01 30" src="https://user-images.githubusercontent.com/102296081/168177495-13e9900c-316b-4079-93b0-261d17d1dac4.png">


allure screenDiff https://github.com/allure-framework/allure2/tree/master/plugins/screen-diff-plugin
<img width="706" alt="Screen Shot 2022-05-12 at 23 04 31" src="https://user-images.githubusercontent.com/102296081/168177505-c2a93991-2d64-46cb-8931-4437324810c2.png">


So there must be some other breaking change there, not only https://github.com/microsoft/playwright/pull/13202

**Comment by ivan-krupskyi** [comment]
@mxschmitt, if you add this, than it would work as expected (I have tested it):
<img width="763" alt="Screen Shot 2022-05-12 at 23 37 53" src="https://user-images.githubusercontent.com/102296081/168178888-e0a96ed1-983f-4d61-b896-3da0740bd28f.png">

**Comment by ivan-krupskyi** [comment]
@mxschmitt, do you have any update on this one please?

**Comment by mxschmitt** [comment]
@ivan-krupskyi we usually can't provide any etas, I'm sorry!

**Comment by pavelfeldman** [comment]
It does not look like the action item is on Playwright side, should we close this bug and suggest filing it against Allure?

**Comment by pavelfeldman** [comment]
I'll close this issue because I believe it is being followed up on in the allure repo!
