### ISSUE TITLE
chrome-1005 seems to be corrupted

### ISSUE THREAD

**Issue by gkontopidis** [microsoft/playwright#14139]
My tests no longer run after updating playwright. I found out that chrome version is chrome-1005. If you try to open the included browser you get a windows error: Windows cannot access the specified device, path, or file. You may not have the appropriate permissions to access the item. The error in the logs after executing a test is: browserType.launch: spawn EPERM

**Comment by aslushnikov** [comment]
@gkontopidis it looks like you're running on Windows. What's the playwright version you updated to?

**Comment by gkontopidis** [comment]
Version 1.22.0

**Comment by aslushnikov** [comment]
@gkontopidis does it work if you revert back to the previous version?

**Comment by gkontopidis** [comment]
It seems that chrome-1005 was updated in the server so it works now. Thanks
