### ISSUE TITLE
[BUG] PW says element is outside of the viewport when it's not

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14133]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Manjaro Linux (and Windows 11)
- Node.js version: v16.14.2
- Browser: Chromium

**Code Snippet**

My element:
`this.studentProfileDropdown = page.locator("//div[contains(@class,'dropdown')]");`
I checked with Xpather and it is unique on that page: 
![image](https://user-images.githubusercontent.com/98180468/168319118-1934415d-6fb5-4b56-9dea-dfdf20cc5d99.png)

It fails right at the first click event here:
```
async goToStudentProfile(WebAppStudentProfilePersonalPage){
        await this.studentProfileDropdown.click();
        await this.studentProfileDropdownProfileLink.click();
        await expect(this.page).toHaveURL(WebAppStudentProfilePersonalPage.url);
    }
```

PW keeps retrying 89 times and it actually finds the element as you can see here, but wrongly claims that it's outside of the viewport:
```
retrying click action, attempt #88
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  element is outside of the viewport
retrying click action, attempt #89
  waiting 500ms
```

**Description**
PW claims that the element is outside of the viewport, but actually it is inside the viewport as you can see in the screenshot. It's this dropdown in the top right corner:

![bf6168190e1b4f320df775d67a18b69f58ea4954](https://user-images.githubusercontent.com/98180468/168162477-6cdcab4c-d2fc-4d26-af54-2a00baadbfa6.png)

And it is the only element with that class on that page, so PW is definitely selecting the right element.
I've had the same issue on a different page a few months ago, that element was also a dropdown in the top right corner, but well inside the viewport.
So it would seem to me that PW is interpreting/defining the viewport wrong, as in: smaller than it should be.
FYI I don't have any specific viewport defined in my config so it just used PW's default viewport.

If needed I could also provide the traces, however I don't think I can post them publicly here.

**Comment by mxschmitt** [comment]
Having a trace for that would be very helpful. Feel free to send it to `m a x` ` s c h m i t t@microsoft.com`

**Comment by azad-derakhshani-GS** [comment]
Actually, earlier today I decided to change that part, now I'm clicking the profile picture instead since it also opens the dropdown.

Upon further investigation right now, I realized that the `dropdown` element was actually not the arrow I was trying to click yesterday, but rather the list in the dropdown.
While that still doesn't mean it was outside of the viewport, it does mean it has kind of a hidden state (even though it's always included in the DOM and its CSS is set to `visibility: visible;`).
![image](https://user-images.githubusercontent.com/98180468/168320119-ac58e6c6-9eb8-4e68-bc2a-f81d6d07941c.png)

So while the error put out by PW is still not accurate, it turns out I was selecting the wrong element, that was my bad. 😅
I still think it would be helpful if the error message said something different in cases like this, but my (self-inflicted) issue is fixed, so I'd be fine with closing the issue if you want to.

**Comment by rwoll** [comment]
Thanks for the follow up! I'm going to close for now, but if we see other issues with similar errors and imprecise error message, we can follow up and differentiate these states.

**Comment by metealp** [comment]
I was having the same problem, evaluating some styles to make the input visible solved the issue. If the element does not have width, height or appearance set to none, then the element is considered as invisible. Here is the snippet;

`
            VISIBLE_CHECKBOX_STYLES = """(element) => {element.style.appearance='unset';element.style.width='5px';element.style.height='5px';}"""

            confirmation_checkbox = page.locator("#baustrom-search__confirmation-checkbox")
            confirmation_checkbox.evaluate(VISIBLE_CHECKBOX_STYLES)
            confirmation_checkbox.check(force=True)
`

**Comment by BoharSingh91** [comment]
getting same issue while hovering to the element, actually that element is on top right corner have style as Postion: relative and top;-48px and also Display:block

 elementHandle.hover: Element is outside of the viewport
       =========================== logs ===========================
       attempting hover action
         waiting for element to be visible and stable
           forcing action
         element is visible and stable
         scrolling into view if needed
         done scrolling
