### ISSUE TITLE
[Question] Linking test results to test cases in Azure Devops

### ISSUE THREAD

**Issue by joeflan** [microsoft/playwright#14130]
We're developing a suite of test cases to run on our Azure Devops Pipelines and we'd like to link them to some of our existing manual test cases. We're writing out our tests in Typescript but it looks like the JUnit results don't support linking to AzDo Test Case work items. 

[https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops#q-what-types-of-tests-are-supported](https://docs.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops#q-what-types-of-tests-are-supported)

Reading to documentation it's clear JavaScript tests aren't supported, but I'm wondering if there's any plan to add this support or if anyone has a workaround/extension we could use in the meantime.

**Comment by mxschmitt** [comment]
Does Azure DevOps already provide an integration for the junit reporter where you can set some test-case IDs? If not, then it's probably more an issue which needs to be resolved on their side first.

**Comment by joeflan** [comment]
Yeah I agree. I opened an issue with Microsoft so this issue is closed, since it isn't an actual issue on Playwrights end
