### ISSUE TITLE
[BUG] Click event fails because PW says it's waiting for the selector but has already clicked it

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14146]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Manjaro Linux
- Node.js version: v16.14.2
- Browser: Chromium

**Code Snippet**

```
this.genderDropdownArrowButton = page.locator('.session-select__dropdown-indicators').first();  

...  

await this.genderDropdownArrowButton.click();
```

**Describe the bug**

During a locator.click() event, Playwright says it's still waiting for the selector (and eventually times out), but actually PW has already clicked the element.
How can it even still be waiting for the element when it has already succeeded in clicking it?
From my understanding it could've only successfully performed the click if it already found the selector, so something seems off here.

The element in question is the arrow next to the dropdown, clicking it opens the dropdown. As you can see, the dropdown is opened which means the click was successful.
![PW waiting for selector already clicked](https://user-images.githubusercontent.com/98180468/168306837-01dcf195-1cfb-4221-908f-a6c75fb1ba79.png)

I even ran the test through the PW Inspector just to confirm that the dropdown is not somehow opened before.

**Comment by SmeHantout-Vungle** [comment]
I'm having a similar problem, but when I turn off parallelism with `workers=1`, tests will no longer fail.
Is that also the case for you?

**Comment by azad-derakhshani-GS** [comment]
Interesting!
I don't think it applies to me, because I was just running one test (while working on it) on one worker when this happened.
Just out of curiosity I set `workers: 1` in my config instead of the default setting `workers: process.env.CI ? 1 : undefined` (I never changed it), but as expected the outcome stayed the same.

**Comment by mxschmitt** [comment]
@azad-derakhshani-GS are you able to share a minimal repro with us? This would help a ton, so we can dig into it. Thanks.

**Comment by azad-derakhshani-GS** [comment]
Hey @mxschmitt, sorry I was off work for a few days, but I'll try to provide one next week!

**Comment by oytunerdd** [comment]
Hello, 
The process of locating the element might have been finished after click event finished because await is not used.
Try awaiting the selector in the first place, this way the element is located and be ready to click then await clicking.

`this.genderDropdownArrowButton = await page.locator('.session-select__dropdown-indicators').first();  

await this.genderDropdownArrowButton.click();`

this should correct your unless there is no error on the selector.

**Comment by azad-derakhshani-GS** [comment]
@oytunerdd That's not possible, you can't use await in a constructor:

![Screenshot_20220523_144904](https://user-images.githubusercontent.com/98180468/169822880-a2d5d650-4299-44fa-83cd-8eb92e2e4b52.png)

**Comment by azad-derakhshani-GS** [comment]
Ah sorry, I thought that was clear since it's standard to define locators as class variables and not function variables. 😅

But anyway it turned out the issue was caused by a faulty component on our side, so we can close this ticket.
