### ISSUE TITLE
[Question] using storageState in playwright test

### ISSUE THREAD

**Issue by vitalics** [microsoft/playwright#14141]
Hi team, 
my question is about best practice about using `storageState` in my tests
the test is consist the next steps:
1) login to app
2) proceed with loggined user

As for test runner I use `@playwright/test`
for better understanding - I extend base fixture

``` ts
// base.ts
import { test as base } from '@playwright/test';

type Props = {
  login(): void;
};

export const test = base.extend<Props>({
  login: async ({ browser, context, page }, use) => {
    try {
      // use storateState if available
      const state = require('./auth.json');
      context = await browser.newContext({ storageState: state });
      page = await context.newPage();
      await page.goto(baseURL!);
    } catch {
      // no state. Login as usual and save state
      console.log('no context');
      await manualLogin();
    }
    await use(async () => { });
  },
});

export default test;

// test.ts

import { test } from './base';

test('user do smth', async ({ login, page, baseURL }) => {
  await login();

  // proceed with user
  await page.goto(baseURL); // error Navigation failed because page was closed!
})
```

The error happens when using existing storageState, since in my example I define a new reference to the page.
The question: How to manage such cases in the right way?

**Comment by mxschmitt** [comment]
The right way of doing it putting your storageState either inside the config under use or inside the test with `test.use({storageState: './foo.json'})` see [here](https://playwright.dev/docs/next/test-auth#reuse-signed-in-state).

**Comment by vitalics** [comment]
@mxschmitt thanks. it's better to update documentation about using state for the `@playwright/test`.

**Comment by vitalics** [comment]
Let's close the issue, since it linked on #14147
