### ISSUE TITLE
[Question] Why should we (or should we not) use Babel in Playwright?

### ISSUE THREAD

**Issue by jamesmortensen** [microsoft/playwright#14142]
There's documentation for adding Babel support to Playwright (and other popular JavaScript UI test automation frameworks) but I haven't seen a need for a transpiler in this use case.

My understanding of Babel is this:  A development team wants to use the latest JavaScript features in their app.  When running in Chrome and Firefox, all is well, but when running in IE11, the app cannot run because that browser uses a much older JavaScript engine.  The Babel transpiler is then able to convert the more modern JavaScript code into code that the older browser can understand.  For instance, `const myvar = 1;` would be converted to `var myvar = 1;`.  As a web developer, I understand where Babel can be valuable in the browser when supporting legacy browsers.

But for a Node.js application, isn't it safe to say that all the engineers can use the latest supported version of Node.js?  I'm hoping someone can help me understand what JavaScript features they were missing that led to their decision to use a Babel transpiler for JavaScript code.  

My reason for asking the question is that transpilers can introduce another layer of complexity that must be maintained and updated.  If there's a need for a missing feature, we should add it, assuming the cost of maintaining Babel is less than the benefit of the new features.  For the purposes of this question, let's just focus on JavaScript.  Typescript requires a transpiler because it's a different language altogether, but what about JavaScript?  What are the missing features that lead folks to need Babel in Playwright?  Thank you!

P.S.  I tried to ask in Slack, but the invite link is no longer active. Sorry if this isn't the right place for this question.

**Comment by mxschmitt** [comment]
If you talk about Playwright with the test-runner, then there is no need for babel on the Node.js level. It already uses it and makes sure that you can use fancy JavaScript inside your tests which gets transformed correctly for the Node.js host.

If you mean like more on the web-application level, then it depends on your web-application. Most common web frameworks nowadays already have bundlers which automatically do that for you with browserlist support.

If you have concrete questions, let us know!

**Comment by jamesmortensen** [comment]
@mxschmitt Thanks for the reply.  I'll check if we're using the test runner or not.  That seems like a much better solution to go with the defaults.

**Comment by mxschmitt** [comment]
(Just FYI, with test-runner I meant the `@playwright/test` package.)

**Comment by rwoll** [comment]
Closing as part of triage! After you've given the test runner a try or have more specific questions, please re-open or open new issues as appropriate referencing this issue.

Thanks!
