### ISSUE TITLE
[BUG] PW always ignores the specified viewport

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14148]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Manjaro Linux, Windows 10/11
- Node.js version: v16.14.2
- Browser: Chromium, Chrome
- Monitor resolutions: 2560x1600 and 1920x1080

**Code Snippet**
Here's the relevant part from my config:

```
use: {

    headless: false,
    launchOptions: {
      //slowMo: 100
    },
    screenshot: 'on',
    trace: 'on',
    video: {mode:'on', size: {width: 1920, height: 1080}},
    viewport: { width: 1920, height: 1080 },
  },

  projects: [
    {
      name: 'chromium',

      /* Project-specific settings. */
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          headless: false,
          //args: ["--start-maximized", '--window-size=1920,1080'],
          //args: ["--start-maximized"],
        },
      },
    },
```

FYI the `args:` are commented out because they don't work. Playwright simply ignores them too and always opens a non-maximized window in 1280x720 instead.

**Describe the bug**
Despite defining the viewport as 1920x1080, Playwright always ignores this setting and instead opens a browser window of the size 1730x1052 with a viewport of 1731x942.
Yes the viewport is really slightly wider than the top part of the browser with the address bar and browser tabs, see here:
![image](https://user-images.githubusercontent.com/98180468/168316436-d3a5dc68-435e-4949-8577-f9b465b4feab.png)

I've also tried putting the viewport into either of the `launchOptions` blocks, but then my IDE complains that *'viewport' does not exist in type 'LaunchOptions'*.

Funnily enough, the `video` testoption actually puts out a 1920x1080 video, but with black bars around it because the viewport is smaller.

**Comment by rwoll** [comment]
```
 ...devices['Desktop Chrome'],
```

has viewport defined in it, so you are overriding your top-level definition.

Try editing your project.config like so: 

```
      /* Project-specific settings. */
      use: {
        ...devices['Desktop Chrome'], // this includes a viewport (you can `console.log(devices['Desktop Chrome'])` to see what it's adding
        viewport: { width: 1920, height: 1080 }, // override what's coming in through the spread from above
      },
```

**Comment by rwoll** [comment]
Closing per-above. Feel free to re-open if this does not solve the issue for you.

**Comment by azad-derakhshani-GS** [comment]
Oh wow, why does the Chrome device already define a viewport? That's very unintuitive and illogical!
I think we should actually change that in a future feature request.

But your config suggestion actually works, so it finally works in fullscreen, thank you so much!

**Comment by rwoll** [comment]
> why does the Chrome device already define a viewport?

Your code doesn't just ask for chromium, it asks for `devices['Desktop Chrome']` i.e. emulate the **Desktop** version of **Chrome**; this includes overrides for viewport, user agent, etc. so it more accurately emulates the device. This is a bit confusing out of context, but if you say `devices['iPhone 11']` the implication is a little more clear: you want to use safari/webkit, a user agent that an iphone uses, and mobile sized viewport that matches an iPhone 11 instead of the default large PW size.

If you don't care about the user agent and other bits, you can just specify just the `browserName` https://playwright.dev/docs/api/class-testproject#test-project-use

**Comment by azad-derakhshani-GS** [comment]
Ah yeah, I've always wondered why Desktop Chrome was a device in the first place, since it makes more sense for actual devices like the iPhone 11 you mentioned, for example.

Actually I wasn't using it to _emulate_ Chrome but rather to run the tests in my installed Desktop Chrome.
The Chrome 'device' was just what I found when I looked into that a while ago, I didn't know you can also launch your installed Chrome instance via `browserName`.

**Comment by azad-derakhshani-GS** [comment]
Yeah exactly, I had used the executablePath option, but I've since switched back to Chromium for now.

Anyway, thanks for all your help and insights, really appreciate it!
