### ISSUE TITLE
[Feature] support Vue 2 in component testing

### ISSUE THREAD

**Issue by Aaron-Pool** [microsoft/playwright#14143]
It looks like the current Vue component testing plugin targets Vue 3 only. It would be nice to have a Vue 2 version as well. Vue 3 only became the default version in the past 6 months or so, so I would venture that the majority of Vue apps are still on Vue 2. That ratio will, of course, begin to shift over the next few years, but to see significant Vue user adoption right now will probably need Vue 2 support.

**Comment by unlikelyzero** [comment]
We also won't be able to migrate to vue3 for some time.

**Comment by AlexanderMykulych** [comment]
Had the same question.
Here is my attempt to use vite-plugin-vue2. All is good so far:
https://github.com/AlexanderMykulych/playwright/blob/main/packages/playwright-ct-vue2/registerSource.mjs

**Comment by pavelfeldman** [comment]
Tomorrow at this time, you'll be able to give it a try via installing `npm i --save-dev @playwright/experimental-ct-vue2@next`

**Comment by AlexanderMykulych** [comment]
@pavelfeldman Great work, thank you!
There is only one missing point for me. Maybe you could clarify.
I need to pass vuex store to the Vue instance:
```js
const mounted = new Vue({
    render: h => render(component, h),
    //here
    store,
  }).$mount();
```
Any ideas?

**Comment by hangboss1761** [comment]
> Tomorrow at this time, you'll be able to give it a try via installing `npm i --save-dev @playwright/experimental-ct-vue2@next`

Where can i find a demo about how to use it ?
