### ISSUE TITLE
[Question] Do the afterAll/beforeAll hooks behave slightly differently since version 1.21?

### ISSUE THREAD

**Issue by KilianCM** [microsoft/playwright#14145]
Hello,
I'm using the `afterAll` hook to teardown some data created by my tests. But since the 1.21 version, I got some errors triggered by my tests (some web requests fail because of missing data). I noticed that the data was deleted before the end of the test. I don't have these problems when I run my tests with 1.20.2 version.

Trying to understand the problem, I wrote a standalone test with a good old debug with console.log:

```
import { test } from '@playwright/test';

test.beforeAll(async () => {
  console.log(Date.now() + ' - Before all');
});

test('After all is running too early', async ({ page }) => {

  for(let i = 1; i <= 5; i++) {
    await test.step(`Step ${i}`, async () => {
      console.log(Date.now() + ` - Start Step ${i}`);
      await new Promise(f => setTimeout(f, 1000));
      console.log(Date.now() + ` - End Step ${i}`);
    });
  }
});

test.afterAll(async () => {  
  console.log(Date.now() + ' - After all');
});
```

And I noticed a different behaviour in the outputs:

**1.20 output** - hooks seem to be running in a group, with a small delay between the last step and the afterAll hook
```
[test] › after-all-test.spec.ts:3:6 › beforeAll
1652449820860 - Before all
[test] › after-all-test.spec.ts:7:1 › After all is running too early
1652449821625 - Start Step 1
1652449822638 - End Step 1
1652449822638 - Start Step 2                                                                                                        
1652449823644 - End Step 2
1652449823644 - Start Step 3                                                                                                        
1652449824654 - End Step 3
1652449824654 - Start Step 4                                                                                                        
1652449825664 - End Step 4
1652449825665 - Start Step 5                                                                                                        
1652449826680 - End Step 5
[test] › after-all-test.spec.ts:18:6 › afterAll
1652449826886 - After all
```

**1.22 output** - hooks are running as a step, and the afterAll right after the last step *(same for 1.21)*
```
Running 1 test using 1 worker
[test] › after-all-test.spec.ts:7:1 › After all is running too early
1652449055992 - Before all
1652449056532 - Start Step 1
1652449057541 - End Step 1
1652449057542 - Start Step 2                                                                                                        
1652449058548 - End Step 2
1652449058548 - Start Step 3                                                                                                        
1652449059555 - End Step 3
1652449059556 - Start Step 4                                                                                                        
1652449060571 - End Step 4
1652449060571 - Start Step 5                                                                                                        
1652449061583 - End Step 5
1652449061585 - After all                                                                                                           
[1/1] [test] › after-all-test.spec.ts:7:1 › After all is running too early
```

**Did you change something in the hooks that can explain this difference?** If yes, do you have a recommendation to get back to the previous behaviour? 

I didn't find anything in the changelogs.

_(nb: I tried to wait for the end of requests before to do the teardown but with no success)._

Thanks

**Comment by mxschmitt** [comment]
> I noticed that the data was deleted before the end of the test.

what kind of data, do you mean Playwright Test related data?

Would be curious to understand first what is not working anymore.

**Comment by KilianCM** [comment]
> what kind of data, do you mean Playwright Test related data?

No, I delete some application related data, that has nothing related to playwright. But as the afterAll seems to be slighty different since 1.21, my application data is deleted too early and it triggers errors in the web requests done in the last actions of my test.

Maybe I missed something or I'm not using correctly the afterAll hook, but all my tests have the same structure as in the standalone test I put in this issue.

**Comment by mxschmitt** [comment]
Can you share a repro with us which we can run locally? From the logs above its not directly visible whats right or wrong there.

**Comment by mxschmitt** [comment]
How does your config look like, are you using `fullyParallel: true` there? This would explain that the afterAll/beforeAll hooks run multiple times.

With fullyParallel I observe that the hooks are run multiple times, without I observe that beforeAll runs before test1 and afterAll after test2.

My test:

```ts
import { test, expect, Page } from '@playwright/test';

test.beforeAll(() => {
  console.log("beforeAll")
})

test.afterAll(() => {
  console.log("afterAll")
})

test("something 1", async() => {
  console.log("before stetps")
  await test.step("step 1", async () => {
    console.log("step 1")
  })
  await test.step("step 2", async () => {
    console.log("step 2")
  })
  console.log("after steps")
});

test("something 2", async() => {
  console.log("before stetps")
  await test.step("step 1", async () => {
    console.log("step 1")
  })
  await test.step("step 2", async () => {
    console.log("step 2")
  })
  console.log("after steps")
});

```

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
