### ISSUE TITLE
[BUG] Query param is not added upon navigation

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#14150]
**Context:**
- Playwright Version: 1.19.2
- Operating System: Mac
- Node.js version: 14.6
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test.only('test', async ({ page }) => {
  await page.goto('https://rdc-search-alpha.x.realtor.com/realestateandhomes-search/Los-Angeles_CA');
  await page.locator('[data-testid="cancel"]').click();
  await page.locator('[data-testid="Search\\ Box"] [data-testid="input-element"]').click();
  await page.locator('[data-testid="Search\\ Box"] [data-testid="input-element"]').fill('#20211234');
  await Promise.all([
    page.waitForNavigation({ url: 'https://rdc-search-alpha.x.realtor.com/realestateandhomes-search?mlslid=20211234' }), //The issue is here: the url never adds mls as query param.
    page.locator('text=#20211234').click(),
  ]);
});
```

**Describe the bug**

I have scenario where I enter a MLS id in the search box to load results for that MLS. This triggers a navigation to a different url that is basically adding the MLS id as query param.

**Comment by pavelfeldman** [comment]
I can repro. Could this be layout shift prevention? The reactions to manual and Playwright clicks are different.

**Comment by pavelfeldman** [comment]
I replaced

```js
await page.locator('[data-testid="Search\\ Box"] [data-testid="input-element"]').fill('#20211234');
```

with

```js
await page.locator('[data-testid="Search\\ Box"] [data-testid="input-element"]').type('#20211234');
```

and it passed. I believe the page detects if the number has been entered using keyboard vs pasted and behaves differently.
