### ISSUE TITLE
[Feature] Support for Component Tests in Angular apps

### ISSUE THREAD

**Issue by jhanink** [microsoft/playwright#14153]
Please support Component Testing for Angular.

In v1.22.0, there is experimental support for react, vue, and svelte Component Tests
> https://github.com/microsoft/playwright/releases/tag/v1.22.0

![F997E557-0366-4AF7-BB76-1BCDA37C0611](https://user-images.githubusercontent.com/2761400/168394637-703c79ff-b0d4-4977-9e22-1c4336ae90e7.jpeg)

**Comment by vitalics** [comment]
@jhanink please provide how your see API in ideal world for component testing angular app.

**Comment by vitalics** [comment]
@mxschmitt @jhanink I thing is a good idea to support angular applications. But let me put some notes.

React/vue has a simple API (aka `ReactDOM.render` function) to put the component in your DOM node. Angular applications has not such API. The minimal repro:

index.html
``` html
<body>
  <app-root></app-root>
// angular runtime
<script src="runtime.js" type="module"></script> 
<script src="polyfills.js" type="module"></script>
// compiled app
<script src="main.js" type="module"></script>
</body>
```

main.ts
``` ts
import { platformBrowserDynamic } from '@angular/platform-browser-dynamic';
import { NgModule, Component } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  template:'<span>{{ title }} app is running!</span>' 
})
export class AppComponent {
  title = 'my-app';
}

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }


platformBrowserDynamic().bootstrapModule(AppModule)
```

**Comment by tytusplanck-8451** [comment]
Does Angular v14 help resolve and make this simpler? With standalone components coming I think this could be similar to the React/Vue/Svelte examples.

[RFC from Anular](https://github.com/angular/angular/discussions/43784) for context.

**Comment by ExFlo** [comment]
> Does Angular v14 help resolve and make this simpler? With standalone components coming I think this could be similar to the React/Vue/Svelte examples.
> 
> [RFC from Anular](https://github.com/angular/angular/discussions/43784) for context.

About the new setup [angular docs](https://angular.io/guide/standalone-components#bootstrapping-an-application-using-a-standalone-component)

**Comment by Tallyb** [comment]
That will be great.
In order for this to work with traditional component (read: not standalone), you will need to do something like Testbed which is the compilation context for an angular component. Only that will give you a renderable component. You might want to look at storybook angular library, which is dealing with the same thing basically (render a single component in isolation).

**Comment by e-oz** [comment]
Playwright is so amazing that I want to replace all our e2e tests, including tests in libraries, with Playwright.
Would be amazing to have Angular components support, at least standalone components.

**Comment by Waterstraal** [comment]
Support for Angular would be great! [Cypress has proven it is technically possible](https://docs.cypress.io/guides/component-testing/testing-angular), even without standalone components, if I'm not mistaken :).

**Comment by sand4rt** [comment]
Another obstacle is that Playwright transpiles the components with Vite and Angular has no Vite support as far as i know.

**Comment by yjaaidi** [comment]
Just released Angular support here: https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular
but you'll have to follow the [Versatile Angular Style](https://marmicode.io/blog/versatile-angular): standalone, `inject()`, inline templates & styles.

**Comment by e-oz** [comment]
I hope PW team will not postpone this feature because of previous comment :)

**Comment by yjaaidi** [comment]
While the current implementation only works with Versatile Angular Style. 
Using this angular vite plugin might help supporting most use cases. https://github.com/analogjs/analog/tree/main/packages/vite-plugin-angular

**Comment by yjaaidi** [comment]
I also opened an issue to merge efforts.

**Comment by sand4rt** [comment]
@brandonroberts May I ask if you think it is realistic/desirable to use your awesome Vite plugin for Angular? Saw you said something about it earlier in: https://github.com/analogjs/analog/issues/20#issuecomment-1221413098 😄

**Comment by brandonroberts** [comment]
@sand4rt yes, it's possible to use it. I've tested a working solution with Playwright Component Tests and Angular using the Vite plugin. Supports inline/external styles and constructor DI

**Comment by sand4rt** [comment]
Awesome!

**Comment by brandonroberts** [comment]
I don't have the solution I worked on before, but I remember the steps to get it working. I'll recreate it and push up a repo and we can decide what to do from there

**Comment by brandonroberts** [comment]
Here's the repo! https://github.com/brandonroberts/analog-playwright-component-tests

**Comment by sand4rt** [comment]
Need play with it for a while but this is great so far! Curious what other people and the Playwright team thoughts are on this!

**Comment by sand4rt** [comment]
Hi all, i'm also building a library for testing Angular components with Playwright due to the absence of @yjaaidi. It is still work in progress: https://github.com/sand4rt/playwright-ct-angular. If you have any feedback or want to help, let me know!

**Comment by edbzn** [comment]
> Hi all, i'm also building a library for testing Angular components with Playwright due to the absence of @yjaaidi.

@sand4rt Why have you not opened issues against our repository? We could have joined the effort instead of splitting the work with multiple community solutions.

**Comment by sand4rt** [comment]
@edbzn I was on it for a while before @yjaaidi released the lib. Tried to collaborate and combine efforts several times without luck: see https://github.com/microsoft/playwright/pull/19395 for example. So then i decided to publish a separate one.

**Comment by yjaaidi** [comment]
Hi @sand4rt, I was off for a while and catching up now.
As mentioned by @edbzn, we were ok with merging efforts in Playwright, not another library. In addition to this, I am not the only maintainer of `@jscutlery/devkit` and @edbzn could have helped.

**Comment by sand4rt** [comment]
Wish it had gone differently but if you ask me, i think that's a bit late now after ~5 months. I also put a lot of effort into it and i don't want that to be unseen as well. I'm still open to collaborate on a version hosted in Playwright..

> Also, we are sad to see that there is no credit for our work in your library.

Where do you think i should have give credit? The library i made looks/works nothing like yours, right?

**Comment by the-ult** [comment]
Any news on combining/merging any of the above Angular Component Testing solutions in Playwright?

**Comment by yjaaidi** [comment]
Hey! Sorry everyone for catching up so late. 
I just had a quick chat with @sand4rt, and we definitely have to provide official Angular support.

@sand4rt would you be willing to recreate a fresh PR?

Also, I have a couple of suggestions concerning the integration and customization of analog's vite plugin.

@sand4rt @mxschmitt what would be the most efficient approach?
1. Start the PR and discuss the details on the PR? _(my favorite)_
2. Discuss the details on @sand4rt's repo?
3. Create a playwright-community repo? _(that would be temporary and act as an incubator because Angular plugin deserves its place next to its fellow libs/fmwks)_

**Comment by Tallyb** [comment]
I think official Vite support is coming to Angular 17 next month.

**Comment by the-ult** [comment]
That would be awesome news... counting down to the 6th of november!

**Comment by sand4rt** [comment]
> Hey! Sorry everyone for catching up so late. I just had a quick chat with @sand4rt, and we definitely have to provide official Angular support.
> 
> @sand4rt would you be willing to recreate a fresh PR?
> 
> Also, I have a couple of suggestions concerning the integration and customization of analog's vite plugin.
> 
> @sand4rt @mxschmitt what would be the most efficient approach?
> 
> 1. Start the PR and discuss the details on the PR? _(my favorite)_
> 2. Discuss the details on @sand4rt's repo?
> 3. Create a playwright-community repo? _(that would be temporary and act as an incubator because Angular plugin deserves its place next to its fellow libs/fmwks)_

Would like to create a PR, but it is up to the Playwright team. It's also an option to discuss it at my repo or create a community repo, all fine with me :)

**Comment by yjaaidi** [comment]
@pavelfeldman @mxschmitt can we go ahead and open a PR?

**Comment by brandonroberts** [comment]
> I think official Vite support is coming to Angular 17 next month.

@Tallyb was this discussed somewhere? Official support would be great.

**Comment by yjaaidi** [comment]
> I think official Vite support is coming to Angular 17 next month.

Yes @Tallyb! Actually, you can already opt-in to vite since v16 by replacing `@angular-devkit/build-angular:browser` with `@angular-devkit/build-angular:browser-esbuild`

That said, this doesn't change things concerning the integration with Playwright etc... as Angular will not expose a vite plugin yet.
But Brandon is here to bridge the gap.

**Comment by yjaaidi** [comment]
@brandonroberts I think that @Tallyb meant that Angular 17 has official vite support.

**Comment by brandonroberts** [comment]
> @brandonroberts I think that @Tallyb meant that Angular 17 has official vite support.

Ahh, ok

**Comment by mxschmitt** [comment]
> Would like to create a PR, but it is up to the Playwright team. It's also an option to discuss it at my repo or create a community repo, all fine with me :)

We discussed it in our team meeting. We are interested in landing the Angular support inside the Playwright repository if its like the other frameworks covered with tests/does not depend on a lot of external dependencies. Thanks!

**Comment by sand4rt** [comment]
Awesome! The repo i currently have is like the other frameworks, covered with tests and no external dependencies other than Angular and @brandonroberts's Vite plugin. Will create an PR ASP so we can attack it from multiple angles:)

**Comment by sand4rt** [comment]
Hi all, see the PR above. Curious to hear what you all think! I'll go through it again as well later on this week.

**Comment by yjaaidi** [comment]
Cool! Thx @sand4rt!

**Comment by kddsultan** [comment]
> I think official Vite support is coming to Angular 17 next month.

How is that support relevant for this discussion/issue? Thanks

**Comment by muhamedkarajic** [comment]
> > I think official Vite support is coming to Angular 17 next month.
> 
> How is that support relevant for this discussion/issue? Thanks

Its cause Playwright is using vite under the hood thats why Angular is not able to run with it.

**Comment by muhamedkarajic** [comment]
Any update on this, I would be really interested to give it a try in the production?

**Comment by Waterstraal** [comment]
@yjaaidi @pavelfeldman @mxschmitt @sand4rt Kindly requesting an update on this issue. Is this still expected to land somewhere this year? 

Thank you!

**Comment by yjaaidi** [comment]
Hey @Waterstraal! we are working on that 😊

**Comment by SerkanSipahi** [comment]
> we are working on that 😊

@yjaaidi this is awesome, thanks. What is the current status?

**Comment by yjaaidi** [comment]
Everything's ready here https://github.com/sand4rt/playwright/pull/5
We're just waiting for any feedback from @sand4rt and eventually the merge and the review by the team.

**Comment by zargham-leanix** [comment]
@yjaaidi is there any way to try this out locally ?

**Comment by yjaaidi** [comment]
Hey @zargham-leanix, if you just want to play around with it you can clone this https://github.com/yjaaidi/playwright/tree/hello-angular-ct, head to `tests/components/ct-angular` and run `npm test`.

Otherwise, you can `cd packages/playwright-ct-angular; npm link` then `npm link @playwright/playwright-ct-angular` to use it wherever you want.

**Comment by muhamedkarajic** [comment]
> Everything's ready here [sand4rt#5](https://github.com/sand4rt/playwright/pull/5) We're just waiting for any feedback from @sand4rt and eventually the merge and the review by the team.

OMG. Finally!

**Comment by muhamedkarajic** [comment]
> npm test

I am not able to get it working by following those instructions. I get 
```
Error: Cannot find module '/Users/muhamedkarajic/GitHub/playwright/node_modules/@playwright/experimental-ct-core/lib/program.js'
```

**Comment by muhamedkarajic** [comment]
> Hey @zargham-leanix, if you just want to play around with it you can clone this https://github.com/yjaaidi/playwright/tree/hello-angular-ct, head to `tests/components/ct-angular` and run `npm test`.
> 
> Otherwise, you can `cd packages/playwright-ct-angular; npm link` then `npm link @playwright/playwright-ct-angular` to use it wherever you want.

> npm test

I am not able to get it working by following those instructions. I get the following error:
```
Error: Cannot find module '/Users/muhamedkarajic/GitHub/playwright/node_modules/@playwright/experimental-ct-core/lib/program.js'
```

**Comment by yjaaidi** [comment]
Hi @muhamedkarajic, it seems that the library was not built first.
Try running `npm run build`. _(I just updated my previous comment to add the command, so you didn't miss it 😉)_

**Comment by CosminGramada** [comment]
Hi @yjaaidi 

Just to confirm, this is still waiting for review and merge, correct?

**Comment by muhamedkarajic** [comment]
When will this be finally merged?

**Comment by muhamedkarajic** [comment]
And when will this be finally merged? Asked he again.

**Comment by tomczakmarcel** [comment]
> And when will this be finally merged? Asked he again.

+1

**Comment by idgMaciej** [comment]
> Hi @muhamedkarajic, it seems that the library was not built first. Try running `npm run build`. _(I just updated my previous comment to add the command, so you didn't miss it 😉)_

Hi @yjaaidi 
I would like to learn more about component tests with Angular and since official PR stuck for weeks now I wanted to try your solution. Unfortunately I cannot run it. After:
- cloning repo
- switch to "hello-angular-ct" branch (`tests/components/ct-angular` is not there on main)
- npm install
 I have executed `npm run build && cd packages/playwright-ct-angular && npm link` as you mentioned above from root dir. That was without any issues. But then I cannot run `npm link @playwright/playwright-ct-angular` because there is no "playwright-ct-angular":

npm ERR! 404 Not Found - GET https://registry.npmjs.org/@playwright%2fplaywright-ct-angular - Not found
 '@playwright/playwright-ct-angular@*' is not in this registry.

not sure which step I have missed.
Can you please take a look or point me to some other repo that I can give a shot with component tests before (hopefully) Playwright officially support this?

**Comment by jhanink** [comment]
This has been a fun ride over the past 2.5 years

The good news is - it might be ready to ship soon.
The bad news is - it might not be ready to ship soon.
😜

**Comment by pfteter** [comment]
There is no roadmap for this ?

**Comment by muhamedkarajic** [comment]
Who are we? Angular devs. What do we want?! Playwright component testing built in for Angular!

**Comment by kolkov** [comment]
What's your good news for us?
