### ISSUE TITLE
[BUG] html report stats duration incorrect when use parallelism

### ISSUE THREAD

**Issue by alexneo2003** [microsoft/playwright#14159]
**Context:**
- Playwright Version: 1.22.0
- Operating System: any
- Node.js version: v16.13.2
- Browser: all

**Code Snippet**
Using standart setup 
`npm init playwright@latest
`

change some config parameters
`playwright.config.ts`
```javascript
  workers: 4,
  fullyParallel: true,
  reporter: [['list'], ['html']],
```

run tests
`npx playwright test
`

**Describe the bug**

At list report result duration - 9s ([calculating](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/base.ts#L105) as difference between end and start time)
At html - 31.s ([calculated](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/html.ts#L296) as the sum of the times of all tests and files)
in my case with real duration of tests time about 1 hour html report says it took more than 2.5 hours

<img width="952" alt="Screenshot 2022-05-14 at 10 23 46" src="https://user-images.githubusercontent.com/11705902/168415528-3ebde274-c817-49aa-b0d4-37956ee0d098.png">

<img width="1001" alt="Screenshot 2022-05-14 at 10 24 46" src="https://user-images.githubusercontent.com/11705902/168415566-54ad8a36-b8c4-40b6-8402-79c6389c15e9.png">

**Comment by Nav-2d** [comment]
Related #11334
