### ISSUE TITLE
[Question] Evaluating top level awaits in the VS Code debug console (with the test runner)

### ISSUE THREAD

**Issue by jdavis61** [microsoft/playwright#14151]
It is possible to evaluate top level awaits in the VSCode debug console? I do not mean get a value of a statement that is currently stopped on a break point. What I am looking for is the ability to type something like `const a = await page.locator('#test').textContent()` into the debug console and get the text value of this element.

This may be done using the node repl, not sure if there is a way using the Playwright test runner / VSCode debug console?

**Steps to evaluate top level awaits using node repl**
1. Open terminal window, e.g. git bash.
2. ` mkdir pw_test && cd pw_test && npm init -y && npm install playwright`
3. Save the following file in `pw_test` as `run.js`.
```
const { chromium } = require('playwright');
const browser = await chromium.launch({ headless: false });
const page = await browser.newPage();
await page.goto('http://example.com');
```
4. Type `node` to open the node repl, make sure you are using a most recent version.
5. `.load run.js`. Wait for chromium to open.
6. Type `await page.locator('h1').textContent();`  'Example Domain' prints.

**Playwright test runner - VSCode debug console**
 `await page.locator('h1').textContent();` returns the below. Hoping someday to see `Example Domain` printed.
 
![image](https://user-images.githubusercontent.com/16749810/168389296-7244f008-8352-4e2b-800c-552d4043a3c9.png)

**Comment by pavelfeldman** [comment]
That would be a request to a Node debugger, not Playwright and not event to the VS Code...

**Comment by jdavis61** [comment]
Thank you @pavelfeldman;

**Comment by sudharsan-selvaraj** [comment]
@jrdavismaine If you're looking for a more visual way to write, run, and debug your Playwright tests, you might want to check out **Playcraft**.

It's a new open-source tool I've been working on—a visual IDE for Playwright with a built-in code editor, live browser preview, real-time test execution, and even an element inspector & test recorder (just like codegen).

Github: [https://github.com/sudharsan-selvaraj/playcraft](https://github.com/sudharsan-selvaraj/playcraft)

<img width="3096" height="2100" alt="Image" src="https://github.com/user-attachments/assets/2ab90a67-bf7c-4cea-9128-3173701c7c93" />
