### ISSUE TITLE
[BUG] tracing affects screenshot

### ISSUE THREAD

**Issue by leotg130** [microsoft/playwright#14168]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux
- Node.js version: 16.13.2
- Browser: Chromium

```javascript
const config: PlaywrightTestConfig = {
  use: {
    headless: true,
    trace: 'on', // vs `off`
  },
};
```

**Describe the bug**

The visual snapshot generated by `expect(await page.screenshot({ fullPage: false })).toMatchSnapshot(`snap.png`, { threshold: 0 });` with `trace: 'on'` produces slightly different snapshot than `trace: 'off'`. Out of ~500 snapshots only one seems to have this issue, and it's only the corners of a rounded box with a single digit difference in color channels (eg. `0x3989F3` vs `0x3A8AF3`). `retain-on-failure` produces same snapshot as `on`, which would be expected, as it does the tracing.

This could also be something weird in our code, but I can't think of a reason why tracing would affect the screenshot functionality.

Below is an zoomed in example of one corner diff.
![image](https://user-images.githubusercontent.com/33344634/168456394-725d313a-bf7d-419a-8ba5-6167c11e1fdc.png)

Trying to produce a repro will take some effort, so I thought I'd ask first if there's something obvious the tracing might do that could affect the screenshots.

By the way, is there a reason `screenshot()` doesn't seem to wait until the whole document is ready? I was getting flaky results (eg. some images/icons not fully loaded), so I now use `fullPage: false` and do the resizing and waiting myself.

**Comment by rwoll** [comment]
> Out of ~500 snapshots only one seems to have this issue, and it's only the corners of a rounded box with a single digit difference in color channels (eg. 0x3989F3 vs 0x3A8AF3).

Some minor differences—especially 1 out of 500—due to how the browser renders and paints can be expected.

> By the way, is there a reason screenshot() doesn't seem to wait until the whole document is ready?

Check out the new `toHaveScreenshot` Web-First assertion which will wait for the screenshot to stabilize: https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot

**Comment by aslushnikov** [comment]
> Out of ~500 snapshots only one seems to have this issue, and it's only the corners of a rounded box with a single digit difference in color channels (eg. 0x3989F3 vs 0x3A8AF3)

@leotg130 from our experimentation, it looks like these kind of things happen due to non determinism in anti-aliasing that browsers do while rendering. While we rely on a [pixelmatch](https://github.com/mapbox/pixelmatch) library that has some smartness to cancel out anti-aliasing artifacts, some still might go through.

The way to go with this screenshot would be to bump up the [`maxDiffPixels`](https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-2) value for image comparison.

Hope this helps!

**Comment by leotg130** [comment]
@aslushnikov We have around 500 components of which we take screenshots, they all produce reliable results, it's only one component that has this issue.

Even that one component produces reliable results, I ran that one visual snapshot test hundreds of times, each time it produces the same result. It's _only_ if I change tracing `on` => `off`, or vice versa, that I get different result.

So tracing `on` produces one result, always the same result, so it's reliable. Tracing `off` produces a different result than tracing `on`, but still it's the exact same one each time.

Seems really odd that changing tracing on/off affects visuals, and only for one component, and only very little.

This is not a major issue for us, as we will be keeping the tracing setting static, but I thought I'd report it anyway, as it's pretty odd that tracing affects the results.
