### ISSUE TITLE
frame got detached[BUG]

### ISSUE THREAD

**Issue by xiaowenhuman** [microsoft/playwright#14176]
https://github.com/microsoft/playwright/discussions/14169
playwright: 1.18.0
os:mac
I have this problem with firefox.

<img width="699" alt="截屏2022-05-16 上午10 26 44" src="https://user-images.githubusercontent.com/1261933/168509777-fb61fbfa-5de2-4792-98a9-1e69c1c8dfc6.png">

**Comment by mxschmitt** [comment]
What is the problem?

**Comment by xiaowenhuman** [comment]
> 
https://github.com/microsoft/playwright/discussions/14169#discussioncomment-2764744

**Comment by mxschmitt** [comment]
Looks like a duplicate of https://github.com/microsoft/playwright/issues/9840 to me then.
