### ISSUE TITLE
[BUG] Video Recordings 

### ISSUE THREAD

**Issue by haskell-monad** [microsoft/playwright#14177]
**Context:**
- Playwright Version: v1.22
- Operating System: Mac
- Node.js version: v15.13.0
- Browser: Chromium
- Extra: no

**Code Snippet**

```javascript
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');

(async () => {
    const browser = await chromium.launch({
        headless: false,
    });
    
    const context = await browser.newContext({ 
        recordVideo: {
            dir: './videos',
            size: { 
                width: 20, 
                height: 30 
            }, 
        } 
    });
    
    
    const page = await context.newPage();
    
    await page.goto("https://baidu.com");
    
    await page.click('#su', { clickCount: 3 });

    await sleep(3000);

    await context.close();
    const video =  page.video();

    console.log(await video.path());
    
    await browser.close();
   
    await sleep(3000);

})();


function sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
}
```

I can't generate a video file in any case when I perform the test, but the name will be printed out(videos/3d4b19d69b6744c320d16920ea4b0650.webm), but there is no specific video file in the corresponding directory

**Comment by haskell-monad** [comment]
## System:
 - OS: macOS High Sierra 10.13.6
 - Memory: 2.51 GB / 16.00 GB
## Binaries:
 - Node: 15.13.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.6 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Comment by mxschmitt** [comment]
Its relative to your current working directory, works for me:

```
➜  playwright git:(main) ✗ ls -la videos/fa7999200b2dd8fc073188f19a46f493.webm 
-rw-r--r--  1 max  staff  6784 16 May 10:14 videos/fa7999200b2dd8fc073188f19a46f493.webm
```

**Comment by rwoll** [comment]
Closing as part of triage! If it's still not working, please file a new issue referencing this one!
