### ISSUE TITLE
[BUG] Selecting option in dropdown via regular click function with text - solves element as invisible and triggers test failure

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#14172]
**Context:**
- Playwright Version: 1.22
- Operating System: Windows
- Node.js Version: v16.15.0
- Browser: Chromium
- Extra: The project was installed from scratch via the **init** command.

**Code Snippet**

```javascript

//Works as well
 await page.locator('[data-test="product_sort_container"]').selectOption('lohi');

//Doesn't work
  await page.locator('[data-test="product_sort_container"]').click();
  await page.locator('option', {hasText: 'Price (low to high)'}).click();

 ======================================================

**ISSUE TEXT**
 locator.click: Target closed
    =========================== logs ===========================
    waiting for selector "option >> :scope:has-text("Price (low to high)")"
      selector resolved to hidden <option value="lohi">Price (low to high)</option>
    attempting click action
      waiting for element to be visible, enabled and stable
        element is not visible - waiting...
```

**Describe the bug**

It looks like after upgrading to the version 1.22 - it is possible to choose an option from the dropdown by selecting option by kind of manual function: 
1. Opening dropdown by click() function.
2. Clicking on an option by locator with text.

In our entire project in my company - we use custom functions of the choosing from dropdown, so after upgrade - we have more than 50% of failed tests.

Also, the issue was reproduced.

Repo with the reproduced issue:
https://github.com/AlexKomanov/playwright-version-1-22-issue

Also, see the results of the GitHub Actions tests (once used working function and once not working).

Also, see the attached video:

https://user-images.githubusercontent.com/52656401/168485009-19aa2306-9574-421d-a809-b546a855fb28.mp4

**Comment by rwoll** [comment]
> It looks like after upgrading to the version 1.22 - it is possible to choose an option from the dropdown by selecting option by kind of manual function:

Which version were you on prior to 1.22 where it was working? I can reproduce the behavior you describe on 1.22, but it has the same behavior to 1.21 from my testing.

**Comment by AlexKomanov** [comment]
Actually, I didn’t try to reproduce this specific case with the older versions. We just saw the same behavior in our entire project, and for us, just upgrade to 1.22 caused problems with dropdown handling. 
The version of 1.21.1 works as well. 
But if you can reproduce with older version - maybe we found a bigger issue that we thought?

**Comment by rwoll** [comment]
When dealing with `<select>` elements, you should use [`selectOption`](https://playwright.dev/docs/input#select-options).

The "dropdown" portion of a `select` is rendered natively by default and not part of the DOM which is what it looks like in your video as well. 

(NB: Some UI libraries will do some magic to render the dropdown as a div in a DOM, but assuming they are implemented semantically and robustly, `selectOption` should work in that case too.)

**Comment by AlexKomanov** [comment]
The drop-downs in our web application rendered as a div . I will try your suggestion. We use custom functions that click by visible text. And it stopped to work in version 1.22.

**Comment by rwoll** [comment]
> The version of 1.21.1 works as well with our project.

I found that 1.21.1 failed in the same way as 1.22 when trying your repro:

I did:

```
$ git clone git@github.com:AlexKomanov/playwright-version-1-22-issue.git repro
$ cd repro
$ npm ci
$ npx playwright install
$ npx playwright test
… error that matches your description …
$ npm i @playwright/test@1.21.1
$ npm ls @playwright/test
$ npx playwright install 
$ npx playwright test
… same error …
```

Can you try that and let me know what output you get? Regardless, as best practice, if we suggest using `selectOption` when dealing with `<select>` elements.

**Comment by AlexKomanov** [comment]
@rwoll 
I retested from my side. You're right - the behavior is the same also with version 1.21.1. 
If I try to handle the `<select>` element with a click by visible text - it fails.


> When dealing with `<select>` elements, you should use [`selectOption`](https://playwright.dev/docs/input#select-options).
> 
> The "dropdown" portion of a `select` is rendered natively by default and not part of the DOM which is what it looks like in your video as well.
> 
> (NB: Some UI libraries will do some magic to render the dropdown as a div in a DOM, but assuming they are implemented semantically and robustly, `selectOption` should work in that case too.)

According to the official documentation:
If the target element is not a <select> element, this method throws an error. 
https://playwright.dev/docs/api/class-locator#locator-select-option

Dropdown elements in our entire project are not of the `<select>` type. 
But let me check. Maybe - we've made some mistakes with our manual functions. 

BTW -  about the <select> element. The official documentation provides another case of handling elements covered by `<label>`:
However, if the element is inside the <label> element that has an associated [control](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control), the control will be used instead.

Can you give an example?

**Comment by rwoll** [comment]
> Dropdown elements in our entire project are not of the <select> type.

Folding into https://github.com/microsoft/playwright/issues/14254

**Comment by hkfsc** [comment]
Same issue in 1.23.0, Still got invisible error while trying to click it.
```html
<select>
<option value="here">Click to visible</option>
</select>
```

```
await  page.locator('select').click();
await page.locator('option').click();
```
