### ISSUE TITLE
[Question] How to use Playwright docker as a test environment without baking in the tests

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#14179]
# Table of Contents

1.  [Question) How to use Playwright docker as a test environment without baking in the tests](#orged018c3)
    1.  [Problem](#orgc803383)
    2.  [Attempted solution](#org4dd6f3f)

<a id="orged018c3"></a>

# Question) How to use Playwright docker as a test environment without baking in the tests

<a id="orgc803383"></a>

## Problem

Most uses of Playwright Docker requires an intermediate step of building a specialized image from the Docker focal image,
where the tests are copied in. Then the entire Docker machine runs the tests within itself.
See <https://medium.com/geekculture/e2e-testing-with-playwright-and-docker-91dd7eb11793> as an example.

I would like to create a Docker image that can be used as a test environment, without having to bake in the tests.
Technically, Docker supports this by using &#x2013;volume to map an arbitary test folder on the host machine into the
'test' folder inside the Docker machine. However, this results in having to install Playwright into the same 'test'
folder.

The question is whether it is possible to install Playwright globally inside the Docker machine so that only the 
test folder needs to be mapped?

<a id="org4dd6f3f"></a>

## Attempted solution

I tried the following steps but did not have much success. Hopefully someone can pin-point my mistake and help
me find a solution.

I do the following commands:

1.  On the host, invoke bash on the Playwright container

docker run &#x2013;volume <test folder on host>:/tests -it &#x2013;rm &#x2013;ipc=host mcr.microsoft.com/playwright:v1.21.0-focal   /bin/bash

1.  Below are the bash commands to setup Playwright in the container
    a) cd tests
    b) npm install -g
    c) npm install -g @playwright/test
    d) npx playwright install
2.  'npx playwright test' fails.
    Transcript:

    root@ac4939639a68:/tests# npx playwright test
    Error: Cannot find module '\@playwright/test'
    Require stack:
    - /tests/playwright.config.ts
    - /usr/lib/node_modules/@playwright/test/lib/loader.js
    - /usr/lib/node_modules/@playwright/test/lib/runner.js
    - /usr/lib/node_modules/@playwright/test/lib/cli.js
    - /usr/lib/node_modules/@playwright/test/node_modules/playwright-core/lib/cli/cli.js
    - /usr/lib/node_modules/@playwright/test/node_modules/playwright-core/cli.js
    - /usr/lib/node_modules/@playwright/test/cli.js
        at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
        at Function.resolveFilename (/usr/lib/node_modules/@playwright/test/lib/transform.js:251:36)
        at Function.Module._load (node:internal/modules/cjs/loader:778:27)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Object.<anonymous> (/tests/playwright.config.ts:2:1)
        at Module._compile (node:internal/modules/cjs/loader:1103:14)
        at Module._compile (/usr/lib/node_modules/@playwright/test/node_modules/pirates/lib/index.js:136:24)
        at Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
        at Object.newLoader (/usr/lib/node_modules/@playwright/test/node_modules/pirates/lib/index.js:141:7)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)
        at Module.require (node:internal/modules/cjs/loader:1005:19)
        at require (node:internal/modules/cjs/helpers:102:18)
        at Loader._requireOrImport (/usr/lib/node_modules/@playwright/test/lib/loader.js:255:14) {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        '/tests/playwright.config.ts',
        '/usr/lib/node_modules/@playwright/test/lib/loader.js',
        '/usr/lib/node_modules/@playwright/test/lib/runner.js',
        '/usr/lib/node_modules/@playwright/test/lib/cli.js',
        '/usr/lib/node_modules/@playwright/test/node_modules/playwright-core/lib/cli/cli.js',
        '/usr/lib/node_modules/@playwright/test/node_modules/playwright-core/cli.js',
        '/usr/lib/node_modules/@playwright/test/cli.js'
      ]

Note: As the paths indicate /usr/lib/node<sub>modules</sub>/@playwright/test does exist, but there is an error about: Cannot find module '@\playwright/test'

**Comment by yury-s** [comment]
> I would like to create a Docker image that can be used as a test environment, without having to bake in the tests. Technically, Docker supports this by using –volume to map an arbitary test folder on the host machine into the 'test' folder inside the Docker machine. However, this results in having to install Playwright into the same 'test' folder.
> 

If the tests folder on the host system already contains playwright installation you won't need to reinstall it inside docker and something like this should work:
```
docker run -it --rm --ipc=host -v $(pwd):/tests  mcr.microsoft.com/playwright:v1.22.0-focal /bin/bash
cd /tests
npm run tests
```
This is one way to run in docker without backing in the tests.

> The question is whether it is possible to install Playwright globally inside the Docker machine so that only the test folder needs to be mapped?

It is possible to the same extent as with other packages and it's discouraged by Node.js as explained in https://github.com/microsoft/playwright/issues/14181.

You don't seem to need a global installation for your use case though, you can create a derived docker image with an npm package let's say under `/root/mypackage` that contains @playwright/test as a dependency and expects tests to be under `/root/mypackage/tests`. After that you can run that new image with `-v $(pwd):/root/mypackage/tests` and run the tests via:

```
cd /root/mypackage
npm run test
```
