### ISSUE TITLE
[BUG] Screenshot of CJK languages from a Docker container is not working correctly 

### ISSUE THREAD

**Issue by niranjan-uma-shankar** [microsoft/playwright#14187]
**Context:**

Full page screenshots of CJK (Chinese, Japanese, Korean) languages are not working when the Playwright script is running in a Docker container. 

I'm testing with taking a screenshot of WordPress.com's Japanese language signup page at the location `https://wordpress.com/start/ja` with the following command:

```
await page.screenshot( {
    path: `start_ja.png`,
    fullPage: true,
    type: 'jpeg',
    quality: 20,
} );
```

This works well when I run the script on my local MacOS:
![tos_white_signup_desktop_ja](https://user-images.githubusercontent.com/1269602/168557854-900949b4-c736-4394-8079-0541f5844c02.png)

However, when the script runs from a Docker container, the screenshot looks like this:

![tos_white_signup_desktop_ja](https://user-images.githubusercontent.com/1269602/168558047-7bbc0451-9d85-4e80-8511-ce046c4d00be.png)

**Comment by rwoll** [comment]
Which Docker image are you using to run your tests in? Is it the official Playwright image (https://playwright.dev/docs/docker) or something else?

If it's the former, I suspect we be missing some fonts, but will attempt a repro once we have more info. Thanks!

**Comment by worldomonation** [comment]
> Which Docker image are you using to run your tests in? Is it the official Playwright image (https://playwright.dev/docs/docker) or something else?

We rolled our own docker image in a two-stage build: [base image](https://github.com/Automattic/wp-calypso/blob/trunk/Dockerfile.base) and the [ci-e2e](https://github.com/Automattic/wp-calypso/blob/trunk/Dockerfile) image.

Would you happen to know what might be some fonts we need to install? 
Thank you for your time! 🙇

**Comment by rwoll** [comment]
> Would you happen to know what might be some fonts we need to install?

@worldomonation I'm not sure off the top of my head! I'll leave this open for a bit to see if @aslushnikov has a hint for you, or if someone from the community has a suggestion. You can also try asking in the #general Slack channel: https://aka.ms/playwright-slack

**Comment by rwoll** [comment]
Closing as part of triage, but if you sort out which to use in your unofficial image, please comment here as it might be helpful for others in the community!

**Comment by worldomonation** [comment]
Our custom Docker image used `node:16.13.2-buster` as the base, which is in turn based on Debian. From my experiments so far, it appears that installing `fonts-noto` resolves the problem.
