### ISSUE TITLE
[Feature] The case for installing Playwright globally on a machine

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#14181]
# Table of Contents

1.  [(Feature Request) The case for installing Playwright globally on a machine](#org652b63f)
    1.  [problem statement](#org78e7e0f)
    2.  [use cases](#org7c6c4f3)
        1.  [1. Using Playwright like a standard installed application.](#orgc293c8e)
        2.  [2. Situations like classrooms and labs where a single installation of Playwright is simpler to maintain.](#org9b3fc7f)
        3.  [3. Docker images that do not bake in the tests](#org58d6ad4)
    3.  [close to technically feasible](#orgc5e47c9)

<a id="org652b63f"></a>

# (Feature Request) The case for installing Playwright globally on a machine

<a id="org78e7e0f"></a>

## problem statement

Based on my understanding, there are 3 layers to utilizing Playwright
 L1. playwright proper or what is known as @playwright/test
 L2. browser dependencies
 L3. tests

The current installation process of Playwright exposes all 3 layers because L2 is a specific step that needs
to be performed for each Playwright folder. This is ideal for developers because it allows them to deal with
problems of each layer appropriately by installing L1 and L2 in each development folder.

However, there is also a case to be made for combining L1 and L2, as a single step and presenting Playwright
as a global testing tool.

<a id="org7c6c4f3"></a>

## use cases

<a id="orgc293c8e"></a>

### 1. Using Playwright like a standard installed application.

An analogous example : we install Word and then invoke it on any file anywhere on our PC. There is no special dependencies
that the user need to do. 

The Playwright and browser support is part of one environment that the use of PATH is sufficient

This results in only one copy of Playwright and browser support layer needed instead of being duplicated in each Playwright folder.

This also allows many test sources to be run against a single Playwright install.

<a id="org9b3fc7f"></a>

### 2. Situations like classrooms and labs where a single installation of Playwright is simpler to maintain.

This is where one person/teacher deals with the install of Playwright and the browser dependencies and all users/students point
to that installation and just write tests.

<a id="org58d6ad4"></a>

### 3. Docker images that do not bake in the tests

So instead of creating custom docker images from Docker Focal, each with its own copy of tests,
the Docker image can reference arbitary test volumes and therefore only one image ( but as many containers as needed ) is needed.

The advent of WSL2 allows the running of Linux apps that interopreate with Windows in a seamless manner. Accessing Playwright via Docker is an extension of this type of seamless use.

See <https://github.com/microsoft/playwright/issues/14179>

<a id="orgc5e47c9"></a>

## close to technically feasible

There are also several technical reasons that suggests that installing Playwright globally close to being feasible.

1.  npm supports installing packages globally
    However, installing Playwright globally is not currently supported.

2.  Playwright already has functionality that seems to be allowing running tests in other directories
    that is,  &#x2013;config {dir} or testDir in configuration files
    The current problem appears to be if the {dir} is outside the Playwright folder, the tests cannot run properly.
    
    See <https://github.com/microsoft/playwright/issues/14039>

**Comment by khtan** [comment]
Although https://github.com/microsoft/playwright/issues/14039 is closed, please note that it has a zip file to reproduce the specific problem mentioned. 
This ticket is at a higher level and seeks to persuade the team to close the gap and enable Playwright to run globally.  Hence there is no repro code in this ticket.

**Comment by yury-s** [comment]
Node.js highly discourages global packages. There is nothing specific to playwright in this, you can install it globally via `npm install -g @playwright/test` but you won't be able to require its files as the global packages are not in the module search path by default. You can workaround the latter in multiple ways (see e.g. this [stackoverflow answer](https://stackoverflow.com/a/48140439/552185)), the easiest is probably to do something like this:
```bash
export NODE_PATH=$(npm root -g)
```

**Comment by Airkro** [comment]
T try to find a way to install `@playwright/test` in docker globally too, because every time I update `@playwright/test`, I have to update the docker image to make them compatible...

**Comment by Airkro** [comment]
Now I install `@playwright/test` globally, then run `npm link @playwright/test` in the project.
