### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#14184]
In the code sample here https://playwright.dev/docs/test-fixtures#creating-a-fixture for a fixture, expect is exported with **"export { expect } from '@playwright/test';"** and later on the expect from this file will be imported into the test spec file. Is this necessary to do or we can directly import expect from  **'@playwright/test'** itself in the test spec files? 

Also, is Page and other things directly imported from  **'@playwright/test'** should be accessed/imported in this manner if we have fixtures?

**Comment by mxschmitt** [comment]
For the first question, it's not necessary but easier, since in your actual tests you only need to have a single import.

Yes all the types you can import from @playwright/test, like Page etc.
