### ISSUE TITLE
[BUG] Regression: test-results folders clash in monorepos

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#14183]
Consider a monorepo where projects don't have package.json (packages/web in main repo or all the test projects in playwright-vscode). Projects now delete each-other's test-results. As a result all the playwright-vscode tests fail.

**Comment by pavelfeldman** [comment]
Looks like it broke in 1.21

**Comment by aslushnikov** [comment]
context for the previous change: https://docs.google.com/spreadsheets/d/1y_F6eNNiClyY-Eg1hFQZGH7v6-dobxyouFlgUBLNwSg/edit

**Comment by aslushnikov** [comment]
As discussed offline: this is not a regression in 1.22, the change happened in 1.21. The motivation was to have a predictable place for `test-results/` folder.

One way to fix this would be to have a `test-results/` folder next to config, instead of `package.json`

**Comment by aslushnikov** [comment]
Prior to 1.23 release, we had a discussion, and agreed that this whole setup was unfortunate.
- we don't like that we use `package.json` as an anchor point for throw-away artifacts
- we don't like that we use non-root config files

We didn't agree upon path forward though; however, we all acknowledged that the situation is unfortunate.
