### ISSUE TITLE
How to fin button with aria-checked true or not >> based on that proceed with test case 

### ISSUE THREAD

**Issue by raiajithkumarr** [microsoft/playwright#14189]
For example as shown below.
I want to find whether it is unchecked or not and based on that I want to perform test.

But here Id and Css are generating dynamically. Please suggest me how find label text is is **Off** or not if it is ON I want to OFF the button. 

div class="Toggle is-enabled root-235">
label class="Label Toggle-label label-241" for="Toggle151" id="Toggle151-label">Enable List View</label>

div class="Toggle-innerContainer container-237">
button aria-checked="false" aria-labelledby="Toggle151-label Toggle151-stateText" class="Toggle-background pill-238" data-is-focusable="true" data-ktp-target="true" id="Toggle151" role="switch" type="button">

span class="Toggle-thumb thumb-239">
</span>
</button>

label class="Label Toggle-stateText text-242" for="Toggle151" id="Toggle151-stateText">Off/label>/div>/div>

**Comment by rwoll** [comment]
Can you edit your comment above so the HTML has closing tags? I'm having trouble following the example and understanding the structure of your page to help make suggestions about the selector. Thanks!

**Comment by raiajithkumarr** [comment]
Above mentioned html elements are part of page where I want to write test case here.

But for this part Id's and css are generating dynamically unable to find text of  below label.

<label class="Label Toggle-stateText text-242" for="Toggle151" id="Toggle151-stateText">Off/label>

For example 

if Text ==ON
make Text OFF (Switch)
write test cases
Else
do nothing .

like this I want to write test cases suggest here

**Comment by raiajithkumarr** [comment]
For now I am doing like this


var switchContent=await this.page.locator(':nth-match(label,2)').textContent();
if(switchContent=="On")
{
  await this.page.click('.Toggle-background');
}

Now it is working as expected

**Comment by rwoll** [comment]
If you expect, exactly one of `<label>Off</label>` xor `<label>On</label>` you can do:

```ts
const text = await page.locator('label', { hasText: /(On|Off)/ }).innerText(); // you might need page.locator('label', { hasText: /(On|Off)/ }).nth(2).innerText() if you have multiple matches
if (text === 'On') {
…
} else {
…
}
```

This looks similar to what you have, so I will close for now. Feel free to re-open!
