### ISSUE TITLE
[Question] Is the browser supposed to reopen on every assertion?

### ISSUE THREAD

**Issue by MiguelSOliveira** [microsoft/playwright#14195]
Hello, I'm trying to investigate how playwright works and the independent context confuses me a lot.

**Say we have the following scenario:**
Given A
And B

When C

Then D
And E
And F

-----

I'm trying to translate this into playwright like so:

```js

test.describe('Given A', () => {
  let page, context
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext()
    await context.tracing.start({ screenshots: true, snapshots: true })
    page = await context.newPage()

    await page.goto('/')
    // Prepare scenario for A
  })

  test.afterAll(async () => {
    await context.tracing.stop({ path: 'trace.zip' })
    await page.close()
  })

  test.describe('And B', () => {
    test.beforeAll(async () => {
      // Prepare scenario for B
    })

    test.describe('When C', () => {
      test.beforeAll(async () => {
        // Prepare scenario for C
      })

      test('Then D', async () => {
        // Assert that D occurs
      })

      test('And E', async () => {
        // Assert that E occurs
      })

      test('And F', async () => {
        // Assert that F occurs
      })
    })
  })
})
```

But the behavior is very weird. 

- If the last test (Then F) fails, the trace file for some reason is deleted.
- If the middle test (Then E) fails, the trace file starts not from the initial state, but from the state of that specific test (I wanted the trace from the beginning to that point)
- If the first test (Then D) fails, the trace starts from the beginning like expected.
---

**Note:** the trace in the config is defined as follows:
```
    trace: {
      mode: 'retain-on-failure',
      screenshots: true,
      snapshots: true
    }
```

We like to organise our tests, so that all actions are done in "beforeAll" hooks, and then the tests are assertions only. This is so we can reuse the browser state, and not open a new window and do all the steps unnecessarily. We tested both approaches and it takes half as long to test this way.

Are we not using playwright correctly? Thank you!

**Comment by rwoll** [comment]
> Is the browser supposed to reopen on every assertion?

If assertion here means something like `expect(page.url()).toBe("foo")`, this should not trigger a re-open.

>We like to organise our tests, so that all actions are done in "beforeAll" hooks, and then the tests are assertions only. This is so we can reuse the browser state, and not open a new window and do all the steps unnecessarily.

>Are we not using playwright correctly? Thank you!

The general best-practice is to use beforeAll and other hooks for general setup, then perform your-test-specific scenerio in the test block itself alongside expect assertions. You can use `await test.step(…)` within a `test` block to logically divide distinct parts of a single test.

Here's the sample from `npm init playwright` that shows off some of these ideas:

<details>
<summary><code>example.spec.ts</code></summary>
<pre>
import { test, expect, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
});

const TODO_ITEMS = [
  'buy some cheese',
  'feed the cat',
  'book a doctors appointment'
];

test.describe('New Todo', () => {
  test('should allow me to add todo items', async ({ page }) => {
    // Create 1st todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');

    // Make sure the list only has one todo item.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0]
    ]);

    // Create 2nd todo.
    await page.locator('.new-todo').fill(TODO_ITEMS[1]);
    await page.locator('.new-todo').press('Enter');

    // Make sure the list now has two todo items.
    await expect(page.locator('.view label')).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[1]
    ]);

    await checkNumberOfTodosInLocalStorage(page, 2);
  });

  test('should clear text input field when an item is added', async ({ page }) => {
    // Create one todo item.
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');

    // Check that input is empty.
    await expect(page.locator('.new-todo')).toBeEmpty();
    await checkNumberOfTodosInLocalStorage(page, 1);
  });

  test('should append new items to the bottom of the list', async ({ page }) => {
    // Create 3 items.
    await createDefaultTodos(page);

    // Check test using different methods.
    await expect(page.locator('.todo-count')).toHaveText('3 items left');
    await expect(page.locator('.todo-count')).toContainText('3');
    await expect(page.locator('.todo-count')).toHaveText(/3/);

    // Check all items in one call.
    await expect(page.locator('.view label')).toHaveText(TODO_ITEMS);
    await checkNumberOfTodosInLocalStorage(page, 3);
  });

  test('should show #main and #footer when items added', async ({ page }) => {
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');

    await expect(page.locator('.main')).toBeVisible();
    await expect(page.locator('.footer')).toBeVisible();
    await checkNumberOfTodosInLocalStorage(page, 1);
  });
});

test.describe('Mark all as completed', () => {
  test.beforeEach(async ({ page }) => {
    await createDefaultTodos(page);
    await checkNumberOfTodosInLocalStorage(page, 3);
  });

  test.afterEach(async ({ page }) => {
    await checkNumberOfTodosInLocalStorage(page, 3);
  });

  test('should allow me to mark all items as completed', async ({ page }) => {
    // Complete all todos.
    await page.locator('.toggle-all').check();

    // Ensure all todos have 'completed' class.
    await expect(page.locator('.todo-list li')).toHaveClass(['completed', 'completed', 'completed']);
    await checkNumberOfCompletedTodosInLocalStorage(page, 3);
  });

  test('should allow me to clear the complete state of all items', async ({ page }) => {
    // Check and then immediately uncheck.
    await page.locator('.toggle-all').check();
    await page.locator('.toggle-all').uncheck();

    // Should be no completed classes.
    await expect(page.locator('.todo-list li')).toHaveClass(['', '', '']);
  });

  test('complete all checkbox should update state when items are completed / cleared', async ({ page }) => {
    const toggleAll = page.locator('.toggle-all');
    await toggleAll.check();
    await expect(toggleAll).toBeChecked();
    await checkNumberOfCompletedTodosInLocalStorage(page, 3);

    // Uncheck first todo.
    const firstTodo = page.locator('.todo-list li').nth(0);
    await firstTodo.locator('.toggle').uncheck();

    // Reuse toggleAll locator and make sure its not checked.
    await expect(toggleAll).not.toBeChecked();

    await firstTodo.locator('.toggle').check();
    await checkNumberOfCompletedTodosInLocalStorage(page, 3);

    // Assert the toggle all is checked again.
    await expect(toggleAll).toBeChecked();
  });
});

test.describe('Item', () => {

  test('should allow me to mark items as complete', async ({ page }) => {
    // Create two items.
    for (const item of TODO_ITEMS.slice(0, 2)) {
      await page.locator('.new-todo').fill(item);
      await page.locator('.new-todo').press('Enter');
    }

    // Check first item.
    const firstTodo = page.locator('.todo-list li').nth(0);
    await firstTodo.locator('.toggle').check();
    await expect(firstTodo).toHaveClass('completed');

    // Check second item.
    const secondTodo = page.locator('.todo-list li').nth(1);
    await expect(secondTodo).not.toHaveClass('completed');
    await secondTodo.locator('.toggle').check();

    // Assert completed class.
    await expect(firstTodo).toHaveClass('completed');
    await expect(secondTodo).toHaveClass('completed');
  });

  test('should allow me to un-mark items as complete', async ({ page }) => {
    // Create two items.
    for (const item of TODO_ITEMS.slice(0, 2)) {
      await page.locator('.new-todo').fill(item);
      await page.locator('.new-todo').press('Enter');
    }

    const firstTodo = page.locator('.todo-list li').nth(0);
    const secondTodo = page.locator('.todo-list li').nth(1);
    await firstTodo.locator('.toggle').check();
    await expect(firstTodo).toHaveClass('completed');
    await expect(secondTodo).not.toHaveClass('completed');
    await checkNumberOfCompletedTodosInLocalStorage(page, 1);

    await firstTodo.locator('.toggle').uncheck();
    await expect(firstTodo).not.toHaveClass('completed');
    await expect(secondTodo).not.toHaveClass('completed');
    await checkNumberOfCompletedTodosInLocalStorage(page, 0);
  });

  test('should allow me to edit an item', async ({ page }) => {
    await createDefaultTodos(page);

    const todoItems = page.locator('.todo-list li');
    const secondTodo = todoItems.nth(1);
    await secondTodo.dblclick();
    await expect(secondTodo.locator('.edit')).toHaveValue(TODO_ITEMS[1]);
    await secondTodo.locator('.edit').fill('buy some sausages');
    await secondTodo.locator('.edit').press('Enter');

    // Explicitly assert the new text value.
    await expect(todoItems).toHaveText([
      TODO_ITEMS[0],
      'buy some sausages',
      TODO_ITEMS[2]
    ]);
    await checkTodosInLocalStorage(page, 'buy some sausages');
  });
});

test.describe('Editing', () => {
  test.beforeEach(async ({ page }) => {
    await createDefaultTodos(page);
    await checkNumberOfTodosInLocalStorage(page, 3);
  });

  test('should hide other controls when editing', async ({ page }) => {
    const todoItem = page.locator('.todo-list li').nth(1);
    await todoItem.dblclick();
    await expect(todoItem.locator('.toggle')).not.toBeVisible();
    await expect(todoItem.locator('label')).not.toBeVisible();
    await checkNumberOfTodosInLocalStorage(page, 3);
  });

  test('should save edits on blur', async ({ page }) => {
    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(1).dblclick();
    await todoItems.nth(1).locator('.edit').fill('buy some sausages');
    await todoItems.nth(1).locator('.edit').dispatchEvent('blur');

    await expect(todoItems).toHaveText([
      TODO_ITEMS[0],
      'buy some sausages',
      TODO_ITEMS[2],
    ]);
    await checkTodosInLocalStorage(page, 'buy some sausages');
  });

  test('should trim entered text', async ({ page }) => {
    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(1).dblclick();
    await todoItems.nth(1).locator('.edit').fill('    buy some sausages    ');
    await todoItems.nth(1).locator('.edit').press('Enter');

    await expect(todoItems).toHaveText([
      TODO_ITEMS[0],
      'buy some sausages',
      TODO_ITEMS[2],
    ]);
    await checkTodosInLocalStorage(page, 'buy some sausages');
  });

  test('should remove the item if an empty text string was entered', async ({ page }) => {
    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(1).dblclick();
    await todoItems.nth(1).locator('.edit').fill('');
    await todoItems.nth(1).locator('.edit').press('Enter');

    await expect(todoItems).toHaveText([
      TODO_ITEMS[0],
      TODO_ITEMS[2],
    ]);
  });

  test('should cancel edits on escape', async ({ page }) => {
    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(1).dblclick();
    await todoItems.nth(1).locator('.edit').press('Escape');
    await expect(todoItems).toHaveText(TODO_ITEMS);
  });
});

test.describe('Counter', () => {
  test('should display the current number of todo items', async ({ page }) => {
    await page.locator('.new-todo').fill(TODO_ITEMS[0]);
    await page.locator('.new-todo').press('Enter');
    await expect(page.locator('.todo-count')).toContainText('1');

    await page.locator('.new-todo').fill(TODO_ITEMS[1]);
    await page.locator('.new-todo').press('Enter');
    await expect(page.locator('.todo-count')).toContainText('2');

    await checkNumberOfTodosInLocalStorage(page, 2);
  });
});

test.describe('Clear completed button', () => {
  test.beforeEach(async ({ page }) => {
    await createDefaultTodos(page);
  });

  test('should display the correct text', async ({ page }) => {
    await page.locator('.todo-list li .toggle').first().check();
    await expect(page.locator('.clear-completed')).toHaveText('Clear completed');
  });

  test('should remove completed items when clicked', async ({ page }) => {
    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(1).locator('.toggle').check();
    await page.locator('.clear-completed').click();
    await expect(todoItems).toHaveCount(2);
    await expect(todoItems).toHaveText([TODO_ITEMS[0], TODO_ITEMS[2]]);
  });

  test('should be hidden when there are no items that are completed', async ({ page }) => {
    await page.locator('.todo-list li .toggle').first().check();
    await page.locator('.clear-completed').click();
    await expect(page.locator('.clear-completed')).toBeHidden();
  });
});

test.describe('Persistence', () => {
  test('should persist its data', async ({ page }) => {
    for (const item of TODO_ITEMS.slice(0, 2)) {
      await page.locator('.new-todo').fill(item);
      await page.locator('.new-todo').press('Enter');
    }

    const todoItems = page.locator('.todo-list li');
    await todoItems.nth(0).locator('.toggle').check();
    await expect(todoItems).toHaveText([TODO_ITEMS[0], TODO_ITEMS[1]]);
    await expect(todoItems).toHaveClass(['completed', '']);

    // Ensure there is 1 completed item.
    checkNumberOfCompletedTodosInLocalStorage(page, 1);

    // Now reload.
    await page.reload();
    await expect(todoItems).toHaveText([TODO_ITEMS[0], TODO_ITEMS[1]]);
    await expect(todoItems).toHaveClass(['completed', '']);
  });
});

test.describe('Routing', () => {
  test.beforeEach(async ({ page }) => {
    await createDefaultTodos(page);
    // make sure the app had a chance to save updated todos in storage
    // before navigating to a new view, otherwise the items can get lost :(
    // in some frameworks like Durandal
    await checkTodosInLocalStorage(page, TODO_ITEMS[0]);
  });

  test('should allow me to display active items', async ({ page }) => {
    await page.locator('.todo-list li .toggle').nth(1).check();
    await checkNumberOfCompletedTodosInLocalStorage(page, 1);
    await page.locator('.filters >> text=Active').click();
    await expect(page.locator('.todo-list li')).toHaveCount(2);
    await expect(page.locator('.todo-list li')).toHaveText([TODO_ITEMS[0], TODO_ITEMS[2]]);
  });

  test('should respect the back button', async ({ page }) => {
    await page.locator('.todo-list li .toggle').nth(1).check();
    await checkNumberOfCompletedTodosInLocalStorage(page, 1);

    await test.step('Showing all items', async () => {
      await page.locator('.filters >> text=All').click();
      await expect(page.locator('.todo-list li')).toHaveCount(3);
    });

    await test.step('Showing active items', async () => {
      await page.locator('.filters >> text=Active').click();
    });

    await test.step('Showing completed items', async () => {
      await page.locator('.filters >> text=Completed').click();
    });

    await expect(page.locator('.todo-list li')).toHaveCount(1);
    await page.goBack();
    await expect(page.locator('.todo-list li')).toHaveCount(2);
    await page.goBack();
    await expect(page.locator('.todo-list li')).toHaveCount(3);
  });

  test('should allow me to display completed items', async ({ page }) => {
    await page.locator('.todo-list li .toggle').nth(1).check();
    await checkNumberOfCompletedTodosInLocalStorage(page, 1);
    await page.locator('.filters >> text=Completed').click();
    await expect(page.locator('.todo-list li')).toHaveCount(1);
  });

  test('should allow me to display all items', async ({ page }) => {
    await page.locator('.todo-list li .toggle').nth(1).check();
    await checkNumberOfCompletedTodosInLocalStorage(page, 1);
    await page.locator('.filters >> text=Active').click();
    await page.locator('.filters >> text=Completed').click();
    await page.locator('.filters >> text=All').click();
    await expect(page.locator('.todo-list li')).toHaveCount(3);
  });

  test('should highlight the currently applied filter', async ({ page }) => {
    await expect(page.locator('.filters >> text=All')).toHaveClass('selected');
    await page.locator('.filters >> text=Active').click();
    // Page change - active items.
    await expect(page.locator('.filters >> text=Active')).toHaveClass('selected');
    await page.locator('.filters >> text=Completed').click();
    // Page change - completed items.
    await expect(page.locator('.filters >> text=Completed')).toHaveClass('selected');
  });
});

async function createDefaultTodos(page: Page) {
  for (const item of TODO_ITEMS) {
    await page.locator('.new-todo').fill(item);
    await page.locator('.new-todo').press('Enter');
  }
}

async function checkNumberOfTodosInLocalStorage(page: Page, expected: number) {
  return await page.waitForFunction(e => {
    return JSON.parse(localStorage['react-todos']).length === e;
  }, expected);
}

async function checkNumberOfCompletedTodosInLocalStorage(page: Page, expected: number) {
  return await page.waitForFunction(e => {
    return JSON.parse(localStorage['react-todos']).filter((todo: any) => todo.completed).length === e;
  }, expected);
}

async function checkTodosInLocalStorage(page: Page, title: string) {
  return await page.waitForFunction(t => {
    return JSON.parse(localStorage['react-todos']).map((todo: any) => todo.title).includes(t);
  }, title);
}

</pre>
</details>

> We tested both approaches and it takes half as long to test this way.

Can you share a link to repo we can download and run that shows what you are doing and highlights the timing differences you found? I'm not following what the comments in the code sample https://github.com/microsoft/playwright/issues/14195#issue-1237324736 would be replaced with.

Thanks!

**Comment by rwoll** [comment]
In the interim, if you want to maintain the structure you originally describe (which implies inter-dependent tests):

Mark the file as serial if you can't make them independent: add `test.describe.configure({ mode: 'serial' });` to the top of the test file (https://playwright.dev/docs/test-retries#serial-mode). Without this, we assume all tests are independent (since that's best-practice), so when one fails we start the next one (running any setup hooks again in a new worker—which will result in a new browser instance). By marking your file as serial, they will always run together and in order. If one of the tests fails, all subsequent tests are skipped. All tests in the group are retried together.

**Comment by MiguelSOliveira** [comment]
hi @rwoll thank you for your answer.

hopefully this clears up what my issue is:

the following test code:
```js
const { test, expect } = require('@playwright/test')

test.describe('Given A', () => {
  let page, context
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext()
    await context.tracing.start({ screenshots: true, snapshots: true })
    page = await context.newPage()

    await page.goto('https://demo.playwright.dev/todomvc')
    // Prepare scenario for A
  })

  test.afterAll(async () => {
    await context.tracing.stop({ path: 'trace.zip' })
    await page.close()
  })

  test.describe('And B', () => {
    test.beforeAll(async () => {
      // Prepare scenario for B
    })

    test.describe('When C', () => {
      test.beforeAll(async () => {
        // Prepare scenario for C
        await page
          .locator('[placeholder="What needs to be done\\?"]')
          .fill('hello')
      })

      test('Should show the main message header', async () => {
        await expect(
          page.locator(
            'text=This is just a demo of TodoMVC for testing, not the real TodoMVC app.'
          )
        ).not.toBeVisible()
      })

      test('Should show the input box', async () => {
        await expect(
          page.locator('[placeholder="What needs to be done\\?"]')
        ).toBeVisible()
      })
    })
  })
})

```

fails on the first test. And if you open the trace file, you can see that everything looks good.

However, the following code fails on the second test.
```js
const { test, expect } = require('@playwright/test')

test.describe('Given A', () => {
  let page, context
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext()
    await context.tracing.start({ screenshots: true, snapshots: true })
    page = await context.newPage()

    await page.goto('https://demo.playwright.dev/todomvc')
    // Prepare scenario for A
  })

  test.afterAll(async () => {
    await context.tracing.stop({ path: 'trace.zip' })
    await page.close()
  })

  test.describe('And B', () => {
    test.beforeAll(async () => {
      // Prepare scenario for B
    })

    test.describe('When C', () => {
      test.beforeAll(async () => {
        // Prepare scenario for C
        await page
          .locator('[placeholder="What needs to be done\\?"]')
          .fill('hello')
      })

      test('Should show the main message header', async () => {
        await expect(
          page.locator(
            'text=This is just a demo of TodoMVC for testing, not the real TodoMVC app.'
          )
        ).toBeVisible()
      })

      test('Should show the input box', async () => {
        await expect(
          page.locator('[placeholder="What needs to be done\\?"]')
        ).not.toBeVisible()
      })
    })
  })
})

```

And the file is deleted for some reason.. I think it's related to the "method: retain-on-failure" not being picked up from the config?

Can you reproduce it on your end?

**Comment by pavelfeldman** [comment]
> We like to organise our tests, so that all actions are done in "beforeAll" hooks, and then the tests are assertions only.

Playwright assumes the tests are independent and it will record a trace per test file, as it was independent. If your tests depend on each other (and we can see that they do), you should use the 'serial' mode: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests.

This tell Playwright that it should do a best-effort at collecting the traces for inter-dependent tests.

Alternatively, instead of tests, you can split your checks into the steps.

**Comment by MiguelSOliveira** [comment]
Serial mode changes nothing, it appears.

This following code, still deletes the trace file:
```js
const { test, expect } = require('@playwright/test')

test.describe.configure({ mode: 'serial' })

test.describe('Given A', () => {
  let page, context
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext()
    await context.tracing.start({ screenshots: true, snapshots: true })
    page = await context.newPage()

    await page.goto('https://demo.playwright.dev/todomvc')
    // Prepare scenario for A
  })

  test.afterAll(async () => {
    await context.tracing.stop({ path: 'trace.zip' })
    await page.close()
  })

  test.describe('And B', () => {
    test.beforeAll(async () => {
      // Prepare scenario for B
    })

    test.describe('When C', () => {
      test.beforeAll(async () => {
        // Prepare scenario for C
        await page
          .locator('[placeholder="What needs to be done\\?"]')
          .fill('hello')
      })

      test('Should show the main message header', async () => {
        await expect(
          page.locator(
            'text=This is just a demo of TodoMVC for testing, not the real TodoMVC app.'
          )
        ).toBeVisible()
      })

      test('Should show the input box', async () => {
        await expect(
          page.locator('[placeholder="What needs to be done\\?"]')
        ).not.toBeVisible()
      })
    })
  })
})
```

Another doubt I have is why does playwright assume each test is independent? I can't see how that is efficient, could you please explain?

For the following scenario:

Given I log into facebook (with mocked feed, using network intercept)
Then I should have my username at the top of the page
And I should have the feed with the correct posts
And I should have the correct sidebar contents
And I should have the correct logged in footer
And I should have the correct logged in title bar

How would this translate into playwright? 
I only need a one time browser window, with zero refreshes. And I want to have each assertion inside a "test" method.
Can you write me a pseudocode into how this would work?

**Comment by yury-s** [comment]
> Serial mode changes nothing, it appears.
> 
> This following code, still deletes the trace file:

I can reproduce it, this is a bug. The trace file should be preserved if the test fails.


> Another doubt I have is why does playwright assume each test is independent? I can't see how that is efficient, could you please explain?
> 
See [this page](https://playwright.dev/docs/next/test-retries) for the explanation of how serial mode is different from the default.

> For the following scenario:
> 
> Given I log into facebook (with mocked feed, using network intercept) Then I should have my username at the top of the page And I should have the feed with the correct posts And I should have the correct sidebar contents And I should have the correct logged in footer And I should have the correct logged in title bar
> 
> How would this translate into playwright?

Aforementioned [serial mode](https://playwright.dev/docs/next/test-parallel#serial-mode) will allow you to reuse the page with its state between the tests.

**Comment by yury-s** [comment]
> > Serial mode changes nothing, it appears.
> > This following code, still deletes the trace file:
> 
> I can reproduce it, this is a bug. The trace file should be preserved if the test fails.

This is probably related to https://github.com/microsoft/playwright/issues/14333
