### ISSUE TITLE
[BUG] Version 1.22.0 - `Page.type` does not work anymore

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#14202]
I am not exactly sure what was changed in version `1.22.0` but `Page.type` does not work for me anymore. It used to type text and my scripts were working fine. But after upgrading to `1.22.0` it just doesn't type and move to the next step. To fix this in my script, I started using `keyboard.type` instead.

**Comment by rwoll** [comment]
Can you include a small repro? Ideally, a self-contained example that we can run locally that exhibits the issue you are seeing.

I tried:

```ts
import { test, expect } from '@playwright/test';

test('it works', async ({ page }) => {
  await page.setContent(`
    <textarea>
  `);
  await page.type('textarea', 'hello');
  const content = await page.locator('textarea').evaluate((e: HTMLTextAreaElement) => e.value);
  expect(content).toContain('hello');
});
```

and this passes across all three of the default browsers.
