### ISSUE TITLE
[Question]: How can i connect to browser running on a Moon cluster over secure websocket connection

### ISSUE THREAD

**Issue by dimsamaras** [microsoft/playwright#14204]
Your question

I am trying to connect to browser running on a [Moon ](https://aerokube.com/moon/latest/#playwright) cluster over secure websocket connection  as [documented](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect) and i am getting the following exception `"PlaywrightException: WebSocket error: unable to verify the first certificate"`
full trace: 

```
Unhandled exception. Microsoft.Playwright.PlaywrightException: WebSocket error: unable to verify the first certificate
=========================== logs ===========================
<ws connecting> wss://moon.perci.dev.local/playwright/chromium/playwright-1.22.0
<ws error> [object Object]
<ws connect error> wss://moon.perci.dev.local/playwright/chromium/playwright-1.22.0 unable to verify the first certificate
<ws disconnected> wss://moon.perci.dev.local/playwright/chromium/playwright-1.22.0 code=1006 reason=
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 164
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.ConnectAsync(String wsEndpoint, BrowserTypeConnectOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 150
   at TestMoon.TestMoon.Main() in C:\Users\69935\code\TestMoon\TestMoon\Program.cs:line 10
   at TestMoon.TestMoon.<Main>()

Process finished with exit code -532,462,766.
```

It is failing here : 
` await using var browser = await playwright.Chromium.ConnectAsync("wss://moon.test.local/playwright/chromium/playwright-1.22.0");`

The sertificates as stored in Local and User Certificate manager.

any suggestions?

**Comment by rwoll** [comment]
I will try to reproduce. If I understand correctly:

A custom cert is being used by Moon and despite adding the cert or CA to the host's cert manager, PW is not picking it up to trust it. (If this is the case, we likley need to ensure we're looking for certs in more locations.)

**Comment by dimsamaras** [comment]
You got it right!

Thank you in advance!

**Comment by rwoll** [comment]
@dimsamaras I've confirmed that connect works with wss, including custom certs. Based on the error message you are getting, it looks like Moon (or whatever is terminating SSL in front of Moon), is not configured properly (and a full cert chain is not being sent by the server). At this time, I don't believe this is an issue with PW itself.

Please reach out to Moon support channels/community to debug the SSL configuration. Feel free to reference your solution/debugging here for others to discover in the future!

Thanks!

Related:
* [`NODE_EXTRA_CA_CERTS`](https://nodejs.org/api/cli.html#node_extra_ca_certsfile)
* https://stackoverflow.com/questions/31673587/error-unable-to-verify-the-first-certificate-in-nodejs

**Comment by dimsamaras** [comment]
@rwoll Thanks a lot for getting back.
You were right that the certificates where not set properly and the intermediate cert was missing.

Once I configured it the err message changed to:

```
Unhandled exception. Microsoft.Playwright.PlaywrightException: WebSocket error: self signed certificate in certificate chain
=========================== logs ===========================
<ws connecting> wss://remote-moot-deployment.local/playwright/chromium/playwright-1.22.0
<ws error> [object Object]
<ws connect error> wss://remote-moot-deployment.local/playwright/chromium/playwright-1.22.0 self signed certificate in certificate chain
<ws disconnected> wss://remote-moot-deployment.local/playwright/chromium/playwright-1.22.0 code=1006 reason=
============================================================
   at Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync[T](String guid, String method, Object args) in /_/src/Playwright/Transport/Connection.cs:line 164
   at Microsoft.Playwright.Transport.Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
   at Microsoft.Playwright.Core.BrowserType.ConnectAsync(String wsEndpoint, BrowserTypeConnectOptions options) in /_/src/Playwright/Core/BrowserType.cs:line 150
   at TestMoon.TestMoon.Main() in C:\Users\69935\code\TestMoon\TestMoon\Program.cs:line 51
   at TestMoon.TestMoon.<Main>()

Process finished with exit code -532,462,766.
```

this is my code:

```
class TestMoon
{
    public static async Task Main()
    {
        var connection = "wss;//remote-moot-deployment.local/playwright/chromium/playwright-1.22.0"
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.ConnectAsync(connection);
        var ctx = await browser.NewContextAsync(new BrowserNewContextOptions
        {
            IgnoreHTTPSErrors = true
        });
        
        var page = await ctx.NewPageAsync();
        
        await page.GotoAsync("https://playwright.dev/dotnet/docs/screenshots#full-page-screenshots", new PageGotoOptions()
        {
            WaitUntil = WaitUntilState.NetworkIdle
        });
        await page.ScreenshotAsync(new PageScreenshotOptions()
        {
            FullPage = true,
            Path = "screenshot.png"
        });
}
}
```

this is the code that i am testing with and the connection succeeds though:

```
 using (var socket = new ClientWebSocket())
                try
                {
                    await socket.ConnectAsync(new Uri(connection), CancellationToken.None);
        
                    await Send(socket, "{dummy: payload}");
                    await Receive(socket);
        
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"ERROR - {ex.Message}");
                }

```

**Comment by rwoll** [comment]
That error should be resolved by setting [`NODE_EXTRA_CA_CERTS` ](https://nodejs.org/api/cli.html#node_extra_ca_certsfile) to point to your cert.

Let me know if that works for you. In my repro, I was hitting the same error as you above, and setting `NODE_EXTRA_CA_CERTS` to point at my `cert.pem` resolved it.

I consider this suggestion a workaround since it leaks Node.js implementation details up to .NET (and in an ideal world we'd automatically pick it up from your OSes trust store assuming it's been added).

**Comment by dimsamaras** [comment]
@rwoll Thanks again!
It works!

**Comment by mattvb91** [comment]
@SabFloki do you remember how you solved it? Im experiencing the same issue also setting the same envs but no luck
