### ISSUE TITLE
[Passing env variables in command line]

### ISSUE THREAD

**Issue by mshre001** [microsoft/playwright#14209]
Hello, I am trying to run my tests by passing the env variable in the command line. It seems to work on Mac but I get below error on a windows machine and VS code - is there a different syntax/command I should be using for Windows? I am following the instructions for passing environment variables in this site: https://playwright.dev/docs/test-parameterize#passing-environment-variables

Thanks for your help!

command I am passing: var='example variable' npx playwright test --headed

Error I get:
var=example variable : The term 'var=example variable' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of 
the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ var='example variable' npx playwright test --headed
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (var=example variable:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rwoll** [comment]
On Mac, you're likely using a bash shell, but Windows will be PowerShell under most circumstances. The syntax to use in this case is under the PowerShell tab at https://playwright.dev/docs/test-parameterize#passing-environment-variables. It looks like:

```powershell
$env:USERNAME=me
$env:PASSWORD=secret
npx playwright test
```

**Comment by rwoll** [comment]
Closing per-above! If that does not work, please re-open or file a new issue referencing this. Thanks!

**Comment by raducybersec** [comment]
In my case I successfully used  env_test=Staging npx playwright test only using git bash console on windows. It is also unclear for me why this problem occur
