### ISSUE TITLE
[BUG] Protocol error (DOM.describeNode): Cannot find context with specified id

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1421]
**Context:**
- Playwright Version: 0.11.1-next.1583909126688
- Operating System: ?
- Extra: Using [custom selector engine](https://github.com/qawolf/playwright-html-selector)

**Code Snippet**

![describebug](https://user-images.githubusercontent.com/1136652/76973709-ec5cc380-68f5-11ea-8b76-81c91b8a8547.png)

**Describe the bug**

"some times i am getting below error when ever there is radio button is involved" from @thiru2021

**Comment by jperl** [comment]
@thiru2021 If you could please provide the code that causes that so the Playwright team can reproduce the bug, it would be helpful 🙏

**Comment by thiru2021** [comment]
@jperl  - Thank you . here is the code 
Test code 
[idsqst.txt](https://github.com/microsoft/playwright/files/4349868/idsqst.txt)
Selctors code:
[idsqstSelector.txt](https://github.com/microsoft/playwright/files/4349878/idsqstSelector.txt)

**Comment by pavelfeldman** [comment]
Thank you for the repro steps. Could you please try it on the post-release version? This area has changed a lot and many bugs were fixed. I'm revisiting old bugs, but this one does not have snippet I could just run to validate, so I rely upon your help.

Please feel free to reopen (or file a new one) if the issue persists.
