### ISSUE TITLE
[BUG] 'isVisible()' return true even element not hidden

### ISSUE THREAD

**Issue by viveklandeWK** [microsoft/playwright#14214]
**Context:**
- Playwright Version:1.21.0
- Operating System:  Windows
- Node.js version: v16.15.0
- Browser:  Chromium

Issue Description: I am checking if the element is visible and Playwright returns true for the hidden element.
and  I checked element doesn't have a 'bounding box'.

**Comment by VivekLande** [comment]
Also, can you please let us know how the playwright determines the visibility of the element?

**Comment by mxschmitt** [comment]
> **Context:**
> 
> * Playwright Version:1.21.0
> * Operating System:  Windows
> * Node.js version: v16.15.0
> * Browser:  Chromium
> 
> Issue Description: I am checking if the element is visible and Playwright returns true for the hidden element. and I checked element doesn't have a 'bounding box'.

Could you provide us a code snippet or a small repro which demonstrates the issue? Maybe you missed an await, since a Promise is always truthy.

See here for our definition of stable: https://playwright.dev/docs/next/actionability#visible

**Comment by VivekLande** [comment]
Thank you!

**Comment by rwoll** [comment]
@VivekLande Can you share a small snippet of HTML+CSS that shows the issue you are seeing? You can use the below example to create/test the snippet:

```ts
import { test, expect } from '@playwright/test';

test('repro', async ({ page }) => {
    await page.setContent(`
        <style>body { background-color: red; } </style>
        <button>hello</button>
    `);
    await page.locator('text="hello"').click();
});
```

**Comment by VivekLande** [comment]
Hello @rwoll,

Please find snippet below and please let me know if I can help you with anything else>
![image](https://user-images.githubusercontent.com/16791810/169339341-1ba63f5f-4bc8-4b0f-8753-1ddf06c500b4.png)

**Comment by rwoll** [comment]
@VivekLande Thanks for the screenshot! Can you include the lines of playwright code you are running that show:

1. which element you are selecting
2. your isVisible call and whether you expect it to say true or false.

Thanks!

**Comment by VivekLande** [comment]
Hi @rwoll, 

We are setting 'PlayWright' as a driver in the 'Codeception' framework and with that, we are identifying elements and checking their visibility as below.

const element=await locate({css: "[data-e2e='cg-client-switcher-button'] [data-e2e='cg-hover-icon'] [icon-name]"});
isVisible=await element.isVisible();

**Comment by rwoll** [comment]
I'm not sure I'm following.

> const element=await locate({css: "[data-e2e='cg-client-switcher-button'] [data-e2e='cg-hover-icon'] [icon-name]"});

`locate` is not from Playwright so I'm not sure how to debug. Can you file a new issue that shares a repo we can clone and run to see the issue? Thanks!
