### ISSUE TITLE
[playwright_bug]:"aw snap" status breakpoint occurring in chrome on running playwright test

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#14216]
Context:

Playwright Version: [1.21]
Operating System: [Windows]
Node.js version: [v12.18.3]
Browser: [ Chrome v101.0.4951.67]

Describe the bug

-Actually Scenario , related with uploading of file with data >5 MB in chrome browser and then try to perform operation in browser 
 making chrome to crash with error "**Aw snap" as displayed in screenshot** and attaching the log assuming something it helps to identify
![image](https://user-images.githubusercontent.com/24275348/168794395-edadc8d5-8869-4a94-95a4-edf0119dc4c6.png)

Please let me know if any further info can be provided which help  to identify why this problem occurring and any way to fix this
[chrome_debug.log](https://github.com/microsoft/playwright/files/8707557/chrome_debug.log)

**Comment by rwoll** [comment]
I haven't had a chance to look at the debug logs; however, can you try using the latest version of Playwright 1.22.1 and let us know if you hit the same problem there. Additionally, please provide a snippet of your Playwright code that's performing the upload and crashing.

Thanks!

**Comment by saurabh4888** [comment]
Tried with latest version of playwright 1.22 still the issue exist .

So describing the scenario in details
 -Our project uses blockly GUI , for reference 
   **https://developers.google.com/blockly** 
 
Now with playwright automation we added the blockly blocks into workspace  and once it loaded into workspace ,and trying to perform context operation above issue exist  and as mentioned in chrome debug.log
"[10984:14224:0510/104339.515:VERBOSE1:script_context.cc(210)] Destroyed context for extension"

but this issue won't exist when smaller number of blockly blocks added into workspace and performing different action  .So  with increase number of blockly blocks chrome as well as chromium browser breaks with above error

Code Snippet ,using POM model and page fixture

test('saving operation with 5000 block', async ({ page }) => {

        try {

            let fileArray = await loadData(KPI._5000Block)
            await uploadFiles(fileArray, uddDirectory);

            await base.navigateToUrl();
            let test=await base.addDataToWorkspace(BlockName._5000_blocks, 400, 100);
            await test.expand();
}

and under config using this
   use: {
        browserName: "chromium",
        headless: false,
        viewport: { width: 1920, height: 1080 },
        ignoreHTTPSErrors: true,
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
        channel: "chrome",
        video: 'retain-on-failure',

    },

Could you suggest if this problem related to memory consumption w.r.t to chrome or chromium ,since tried this scenario  with firefox  works fine

**Comment by saurabh4888** [comment]
Any update on above issue

**Comment by rwoll** [comment]
Can you provide a minimal repro? Ideally, a link to a repo we can clone and run to observe the issue you are seeing since this depends on 3rd-party library. Thanks!

**Comment by rwoll** [comment]
As part of triage, I'm going to close, but please open a new issue with a link to the repo and we can go from there! Cheers! 🎉
