### ISSUE TITLE
[BUG] After upgrade to version - I'm getting the error with async functions: An async function or method in ES5/ES3 requires the 'Promise' constructor

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#14221]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: AlL
- Extra: Tested with Webstorm IDE and with VSCode

**Code Snippet**

```javascript
import test from "@playwright/test";

test.describe('Describe', async() => {

    test.beforeEach(async ({page}) => {
        await page.goto('');
    });

    test('Test', async({page}) => {
        await page.locator('').click();
    })
})
```

**Describe the bug**

The error started to appear after an upgrade to version 1.22.
It requires the 'Promise' constructor. I didn't see this error before an upgrade.

The error occurs in the VSCode:
![image](https://user-images.githubusercontent.com/52656401/168816526-d4dc2ca8-028d-4cb9-826d-c2c8b4e0a1dd.png)

And also in the Webstorm IDE:
![image](https://user-images.githubusercontent.com/52656401/168817868-ad126544-834f-4575-8952-db23de6badf6.png)

I use the Playwright with typescript - should I need to take the advice of IDEs? Or maybe is it a bug? Because as I mentioned, I didn't see these errors before an upgrade.

**Comment by AlexKomanov** [comment]
@pavelfeldman 
I have the following content in my tsconfig:
```

{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "resolveJsonModule": true,

  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by AlexKomanov** [comment]
@pavelfeldman 
Adding the lib configuration - solver the problem:

```
{
  "compilerOptions": {
    "module": "commonjs",
    "target": "es5",
    "sourceMap": true,
    "resolveJsonModule": true,
    "lib": ["ES2015", "DOM"]
  },
  "exclude": [
    "node_modules"
  ]
}
```

**Comment by AlexKomanov** [comment]
@pavelfeldman 
What are the recommended configurations of the lib in tsconfig from your side?

**Comment by rwoll** [comment]
@AlexKomanov You shouldn't need lib. On 1.22, I used your code from https://github.com/microsoft/playwright/issues/14221#issue-1238645155 and your config https://github.com/microsoft/playwright/issues/14221#issuecomment-1128960207 but deleted the `lib` section. VSCode at first complained in the same way as your screenshot when I added the tsconfig, but I closed VSCode and re-opened and it was all good again. Can you check if closing and re-opening clears the errors?

NB: Aside: if you then go and add a `process.env` call, the VSCode typing might complain, but this is related to https://github.com/microsoft/playwright/pull/14230 which will be fixed shortly in a patch release.

Please re-open if I missed something or if restarting VSCode does not resolve the issue. Thanks!

**Comment by dhiegomaga** [comment]
I'm having the same issue, `tsc: Version 4.8.4`, and `tsconfig.json`: 
```json
{
  "compilerOptions":{
    "target": "ES3"
  }
}
```
