### ISSUE TITLE
[Question]: retrieve DOM path for locator / element

### ISSUE THREAD

**Issue by LeRiton** [microsoft/playwright#14224]
### Your question

Hi,

Thanks for all the good work on Playwright ;)

I wonder if there is any way to retrieve the DOM path of a matched (through `locator`) HTML element?

Something like 
```python
foo = await page.locator("text=Sign up").click()
print(foo.dom_path()) # body > div#bar > div:nth-42 > p
```

Hope I make myself clear, thanks in advance

**Comment by LeRiton** [comment]
Is my question clear?
Should I consider that at this time this is not possible through Playwright?
Thanks

**Comment by alexferrari88** [comment]
Hi, you might find this helpful: [playwright-dompath](https://github.com/alexferrari88/playwright-DOMPath).
It does exactly what you would like to do: it can retrieve xPath and CSS selector of an element selected with Playwright. Under the hood it is using the same script that Google Chrome uses in Chrome Dev Tools. I hope it can solve your problems!

_Self-disclosure: I am the author_

**Comment by LeRiton** [comment]
Hi Alex,

Seems like a perfect match, except for one part: I work with Playwright Python. Do you know if there is a way to plug a JS plugin to my existing codebase?

**Comment by alexferrari88** [comment]
> Hi Alex,
> 
> Seems like a perfect match, except for one part: I work with Playwright Python. Do you know if there is a way to plug a JS plugin to my existing codebase?

there you go: [https://pypi.org/project/playwright-dompath/](https://pypi.org/project/playwright-dompath/)
Source at: [https://github.com/alexferrari88/playwright-dompath-py](https://github.com/alexferrari88/playwright-dompath-py)

you are welcome 😉

**Comment by LeRiton** [comment]
This is awesome and thus your are awesome!
Will have a look on this, thanks ;)

**Comment by pavelfeldman** [comment]
Closing as per above
