### ISSUE TITLE
[BUG] "expect(element).toHaveScreenshot" method doesn't auto-retry screenshot till the timeout, it fails after first try

### ISSUE THREAD

**Issue by VasylQA** [microsoft/playwright#14226]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Mac
- Node.js version: 14.4
- Browser: Chromium

Using the code from docs example which is below, expect timeout is set to 15 seconds but  in fact I see that "expect(element).toHaveScreenshot" method fails after first try of comparison, it doesn't re-try screenshot.

```javascript
const locator = page.locator('button');
await expect(locator).toHaveScreenshot();
```

**Comment by pavelfeldman** [comment]
It compares screenshots after they have been stabilized, does not wait until they match. Use toHaveText or similar to wait for the right scene before calling toHaveScreenshot. That is done for efficiency of your tests.

**Comment by VasylQA** [comment]
@pavelfeldman according to latest documentation here - https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot

**Ensures that Locator resolves to a given screenshot. This function will re-take screenshots until it matches with the saved expectation.**

**Comment by VasylQA** [comment]
In my case I'm uploading a new avatar and it takes a while to fully load the new image, and re-taking would fit in my case very well as I don't have any things to wait for

**Comment by dimkin-eu** [comment]
I have the same issue ( it was based on feelings only )
we have storybook tests, but sometimes they are failing, due to some statics were not loaded in time.
so retaking the screen, in this case, would help for sure

**Comment by dimkin-eu** [comment]
from other perspective, how to handle cases, when one needs to update screens? 
`networkidle` is deprecated, but sounds logical here :(

**Comment by aslushnikov** [comment]
Folks, the docs were wrong. The strategy described in the docs does not work in practice, since there would be no way to auto rebaseline screenshots.

The strategy that is actually used for `toHaveScreenshot` is the following:

> This function will wait until two consecutive page screenshots yield the same result, and then compare the last screenshot with the expectation. I'm fixing docs so they are actually trustworthy. 

---

Addressing some of the feedback here:

> In my case I'm uploading a new avatar and it takes a while to fully load the new image, and re-taking would fit in my case very well as I don't have any indicator things to wait for

@VasylQA the new `toHaveScreenshot` won't be of much help for you as-is. You actually need to find some signal to wait for, maybe an HTTP request for the image?

Alternatively, we can probably allow something like 

```js
await expect.poll(() => page.screenshot()).toMatchSnapshot();
```

But you won't be able to auto-rebaseline this.

> I have the same issue ( it was based on feelings only )
we have storybook tests, but sometimes they are failing, due to some statics were not loaded in time.
so retaking the screen, in this case, would help for sure

@dimkin-eu like you mentioned in a follow-up comment, it won't be possible to auto-rebaseline.

@leotg130 you filed a similar https://github.com/microsoft/playwright/issues/14272, and I'd like to bring to your attention this reply :)

**Comment by VasylQA** [comment]
Thanks for answer @aslushnikov

**Comment by leotg130** [comment]
@aslushnikov What would be the problem with changing to functionality to match docs instead? It seems to me this would be a very useful feature.

If you want a snapshot created (either there's no golden or you ran with `-u`), then you the current implementation which waits for two consecutive stable snapshots, and if not creating, but verifying against golden, then keep trying snapshots until test runs out of time.

Not sure if it's useful, but might even be nice to be able to specify how many consecutive snapshots must match when creating new snapshot, though I've not had such use yet.

**Comment by dimkin-eu** [comment]
@aslushnikov just curious, what then `{timeout}` does - fails, when 2 consecutive not happening, or happening, but didn't match or both? :)

**Comment by aslushnikov** [comment]
> What would be the problem with changing to functionality to match docs instead?

@leotg130 This would imply that the strategy for creating and matching snapshot is different, so over time, the automatic re-baseline of screenshots in bulk might not work.

> just curious, what then {timeout} does - fails, when 2 consecutive not happening, or happening, but didn't match with baseline or both? :)

@dimkin-eu it fails if we keep taking screenshots and they differ all the time. Consider a javascript animation, or a GIF 💁‍♂️

**Comment by VsKatshuma** [comment]
In our use case, we would very much like a matcher that retakes a screenshot until it matches the snapshot. I really hope that something like what @aslushnikov mentioned in https://github.com/microsoft/playwright/issues/14226#issuecomment-1131777539 is implemented in playwright. (polling a screenshot)

Would you be able to confirm if such functionality is underway, or was this just a comment with little weight behind it? If no such method will be available in the near future, we will know to explore an alternative solution.

**Comment by philib** [comment]
> In our use case, we would very much like a matcher that retakes a screenshot until it matches the snapshot. I really hope that something like what @aslushnikov mentioned in [#14226 (comment)](https://github.com/microsoft/playwright/issues/14226#issuecomment-1131777539) is implemented in playwright. (polling a screenshot)
> 
> Would you be able to confirm if such functionality is underway, or was this just a comment with little weight behind it? If no such method will be available in the near future, we will know to explore an alternative solution.

We also stumbled across this problem and expected the feature to behave like @VsKathsuma described it. Would that be a bigger change?
