### ISSUE TITLE
[BUG] Unable change snapshot naming for webkit

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#14236]
**Context:**
- Playwright Version: 1.22
- Operating System: linux 'docker'
- Node.js version: 14.6
- Browser: webkit

**Code Snippet**

```
test.describe('Landing page Test Suite', () => {

    test.beforeEach(async ({ page, landingPage },testinfo) => {
        testinfo.snapshotSuffix = ''
        await page.goto(path.en.landingPage, { waitUntil: "load", timeout: 30000 })
    });

    test('Landing page is loading properly with all exact contents in EN lang', async ({ browserName, page }) => {
        expect(await page.screenshot({ fullPage: true, timeout: 4000 })).toMatchSnapshot(`${browserName}-EN.png`,{maxDiffPixels: 30,});
    });

```

**Describe the bug**

Test is failing in beforeEach hook for webkit when using  testinfo.snapshotSuffix = ''

<img width="1042" alt="Screenshot 2022-05-17 at 23 46 48" src="https://user-images.githubusercontent.com/32042806/168915522-1bfb0033-3fc8-4684-b7bb-7c07deb21ede.png">

**Comment by rwoll** [comment]
I attempted to repro, but have been unable. The following works for me (changing the URL of the page you are visiting to https://example.com):

```
import { test, expect } from '@playwright/test';

test.describe('Landing page Test Suite', () => {
  test.beforeEach(async ({ page },testinfo) => {
      testinfo.snapshotSuffix = ''
      await page.goto('https://example.com', { waitUntil: "load", timeout: 30000 })
  });

  test('Landing page is loading properly with all exact contents in EN lang', async ({ browserName, page }) => {
      expect(await page.screenshot({ fullPage: true, timeout: 4000 })).toMatchSnapshot(`${browserName}-EN.png`,{maxDiffPixels: 30,});
  });
});
```

Can you try the following:

1. Run your snippet with the `testinfo.snapshotSuffix = ''` line removed. Does it still crash?
2. Run the snippet I included above as another test. Does it still crash? 

If (1) is yes, and (2) is no, it likely means Webkit doesn't like something about the site you are visiting. Please set `DEBUG` env var to `*` while running and repro'ing the crash to see if it shows any additional errors. If possible, can you share the URL you are testing against?

Thanks!

**Comment by amrsa1** [comment]
@rwoll 
so far it seems happening only when using testinfo.snapshotSuffix = '', also its randomly happening but generally when there are more than one test scenario with screenshot comparison

also note its happening only with webkit

**Comment by rwoll** [comment]
Thanks @amrsa1! It looks like I've found a standalone repro: https://github.com/rwoll/playwright-repro-14236

The error message is not identical, but it's also WK+Linux/Docker-only fail. (My gut says they are related.)

**Comment by amrsa1** [comment]
> Thanks @amrsa1! It looks like I've found a standalone repro: https://github.com/rwoll/playwright-repro-14236
> 
> The error message is not identical, but it's also WK+Linux/Docker-only fail. (My gut says they are related.)

Yes seems so, also extra info 
Im using macOs m1,  running test inside docker container with param platform:linux/amd64 otherwise it wont work

**Comment by rwoll** [comment]
Repro for Bisect: https://github.com/rwoll/playwright-repro-14236
Bad Commit: 41db08eca567098857d574e06691b3b43e7d6afd: feat(webkit): roll to r1631 (https://github.com/microsoft/playwright/pull/13612)
Environment: Docker container running on an M1 Mac

Since it's a WK roll, looks like we'll need to bisect WK itself. (NB: I also manually rolled ToT (432c52d31aaeeb279f4bd8b59de70a15ad1cab07) to r1647, and tested; it's still failing on that revision.)

cc: @aslushnikov @mxschmitt @yury-s

**Comment by aslushnikov** [comment]
I manage to repro - no SSL URL's can be loaded in the Ubuntu 20.04 aarch64 container.

Investigating.

**Comment by aslushnikov** [comment]
Debug build throws the following error:

```
  pw:browser [pid=778][err] Unexpected error compiling builtin: Unrecognized token 'apply' on line 179. +46ms
  pw:browser [pid=778][err] ASSERTION FAILED: error.type() == ParserError::StackOverflow +1ms
  pw:browser [pid=778][err] ../../../Source/JavaScriptCore/builtins/BuiltinExecutables.cpp(257) : static JSC::UnlinkedFunctionExecutable *JSC::Built
inExecutables::createExecutable(JSC::VM &, const JSC::SourceCode &, const JSC::Identifier &, JSC::ConstructorKind, JSC::ConstructAbility, JSC::Needs
ClassFieldInitializer, JSC::PrivateBrandRequirement) +0ms
  pw:browser [pid=778][err] 1   0xffff79e11208 WTFCrash +7ms                                                                                          pw:browser [pid=778][err] 2   0xffff767d7b78 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0xb47b78) [0xffff767d7b78] +0ms
  pw:browser [pid=778][err] 3   0xffff786069f0 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x29769f0) [0xffff786069f0] +0ms  pw:browser [pid=778][err] 4   0xffff78606f9c /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x2976f9c) [0xffff78606f9c] +0ms
  pw:browser [pid=778][err] 5   0xffff7860bfec /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x297bfec) [0xffff7860bfec] +0ms  pw:browser [pid=778][err] 6   0xffff7825fa60 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x25cfa60) [0xffff7825fa60] +0ms  pw:browser [pid=778][err] 7   0xffff797d7acc /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x3b47acc) [0xffff797d7acc] +1ms
  pw:browser [pid=778][err] 8   0xffff797d7a5c /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x3b47a5c) [0xffff797d7a5c] +0ms
  pw:browser [pid=778][err] 9   0xffff797d7954 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x3b47954) [0xffff797d7954] +1ms
  pw:browser [pid=778][err] 10  0xffff786f9ea4 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x2a69ea4) [0xffff786f9ea4] +0ms
  pw:browser [pid=778][err] 11  0xffff786e4114 /home/pwuser/webkit/WebKitBuild/WPE/Debug/lib/libWPEWebKit-1.0.so.3(+0x2a54114) [0xffff786e4114] +0ms
  pw:browser [pid=778][err] 12  0xffff791b35ec Inspector::InjectedScriptManager::createInjectedScript(JSC::JSGlobalObject*, int) +1ms
  pw:browser [pid=778][err] 13  0xffff791adc78 Inspector::InjectedScriptManager::injectedScriptFor(JSC::JSGlobalObject*) +0ms
```

Suspect: https://github.com/webkit/webkit/commit/9ab5cfe8920c
