### ISSUE TITLE
Is there a way to fill out the form with the push of a button? 

### ISSUE THREAD

**Issue by hmzprs28** [microsoft/playwright#14234]
Hi friends
i'm new in playwright
i have an ajax form in 2 part. when you fill inputs at part 1 form content change to give new parameters (without url changing). 
can i send parameters to server without fill inputs directly? the destination website written by asp.net and telerik components and i use pyhton.
Thank you in advance.

**Comment by rwoll** [comment]
You can make requests on behalf of the page via https://playwright.dev/python/docs/api/class-page#page-request (and https://playwright.dev/python/docs/api/class-page#page-request).

However, depending on how your front- and back-end work, that might not be enough to get you to part 2 of your form. Is there a reason you don't want to [fill](https://playwright.dev/python/docs/api/class-locator#locator-fill) in the form via Playwright/UI? If you can do it as a user, Playwright can do it! 😄

**Comment by rwoll** [comment]
Closing as part of triage. Feel free to file a new issue referencing this one if you need additional information!
