### ISSUE TITLE
[Feature] IntelliJ / WebStorm extension

### ISSUE THREAD

**Issue by pas2al** [microsoft/playwright#14247]
Is there a plan to provide an extension for JetBrains IDEs similar to https://playwright.dev/docs/getting-started-vscode?

**Comment by Mshumaman** [comment]
That's a great idea !
Like AlexKomanov we also use webstorm so I'm also voting for extension!

**Comment by ValorHeart** [comment]
Upvoting! I'm pretty sure there are many Jetbrains users, but it's not that easy to realize that it is required to come here in order to affect the decision to develop a playwright extension for it.

**Comment by azad-derakhshani-GS** [comment]
What exactly does the extension do? The link in the OP doesn't link to the extension anymore, the docs have changed apparently.

I'm using GoLand (uses the same engine as Webstorm) and I don't feel like anything's missing in terms of PW support, hence my question.

**Comment by pas2al** [comment]
> What exactly does the extension do? The link in the OP doesn't link to the extension anymore, the docs have changed apparently.
> 
> I'm using GoLand (uses the same engine as Webstorm) and I don't feel like anything's missing in terms of PW support, hence my question.

Thanks. I fixed the link. How are you using PW in GoLand (Run config)?

I am coming from Protractor and it has been quite convenient for years to execute and debug e2e tests directly from the IDE. The VS Code extension has a few features I would like to see (besides simple "run tests") in an official plugin for Jetbrains IDEs. Like the live debugging or execution on specific browsers.

**Comment by azad-derakhshani-GS** [comment]
> How are you using PW in GoLand (Run config)?

@pas2al What do you mean exactly? I just use it the normal way, as it's described in the PW doc.  
And you can always run tests directly from the IDE, where else would you run them from?

**Comment by ValorHeart** [comment]
@azad-derakhshani-GS , Can you run specific test method straight from the spec file using the "green" arrow button in webstorm?

**Comment by azad-derakhshani-GS** [comment]
> @azad-derakhshani-GS , Can you run specific test method straight from the spec file using the "green" arrow button in webstorm?

Dunno, but why would I need to? I've always run tests from the command line, that's so much faster and there are a lot of options (files, tags, envs etc) to specify what you want to test.
Clicking a simple button in your IDE is not capable of that.

**Comment by pas2al** [comment]
Sure, this is one way. I am using the command line myself. I think it comes down to personal preference and individual workflows. The discussion seems to go a little bit off track regarding my original request.

I think there are quite a few people who are interested in this kind of IDE integration. Otherwise, the Playwright team wouldn't have built an extension for VSCode. Now the question is: Do we get the same one for Jetbrains IDEs?

**Comment by Mitri86** [comment]
While PW team is evaluating the need for IntelliJ extension, I found an existing one: https://plugins.jetbrains.com/plugin/18100-maestro
It's more or less have the same functionality as the VSCode one, but it's paid.

**Comment by ValorHeart** [comment]
Jetbrains has added official playwright support: https://blog.jetbrains.com/qa/2023/06/playwright-support-arrives-to-jetbrains-aqua/

**Comment by pavelfeldman** [comment]
Closing as per above.
