### ISSUE TITLE
[BUG] script fails to click (python)

### ISSUE THREAD

**Issue by prashant-crewscale** [microsoft/playwright#14248]
**Context:**
- Playwright Version: [1.20.1]
- Operating System: [Github ActionsLinux]
- Browser: [Chromium]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```Python
    page.keyboard.press('Enter')
    page.fill('input[id="prefix"]', opening_details["price"])
    page.fill('xpath=//textarea[@name="remarks"]', opening_details['notes'])
    page.click('xpath=//button[contains(text(),"Save Changes")]')
    time.sleep(2)
    page.reload()
```

**Describe the bug**

I am running playwright script with pytest on github actions. Its running fine but when it turn to click on the button it is not able to click and not working. It is also not throwing any error while running it.

**Comment by rwoll** [comment]
`time.sleep` should not be used; it can interfere with how PW is implemented under the hood. PW auto-waits https://playwright.dev/python/docs/actionability, so any form of sleep should not be needed, too.

```
page.click('xpath=//button[contains(text(),"Save Changes")]')
```

With the sleep removed, can you run again with the `DEBUG` env var set to `pw:*` and include the logs? It should state what it's doing or waiting on.

**Comment by prashant-crewscale** [comment]
> try with `page.waitForTimeout(time)` before click.

It did not worked for me

**Comment by prashant-crewscale** [comment]
> `time.sleep` should not be used; it can interfere with how PW is implemented under the hood. PW auto-waits https://playwright.dev/python/docs/actionability, so any form of sleep should not be needed, too.
> 
> ```
> page.click('xpath=//button[contains(text(),"Save Changes")]')
> ```
> 
> With the sleep removed, can you run again with the `DEBUG` env var set to `pw:*` and include the logs? It should state what it's doing or waiting on.

Time Sleep in not a problem. I will post the debug logs here If I get it.

**Comment by aslushnikov** [comment]
The discusison has staled, so closing this.

Feel free to re-file if you have a good repro and good logs to show us!
