### ISSUE TITLE
[BUG] focus() function in version 1.22 closes dropdown (not of select type) instead of just focus on the option

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#14254]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Windows
- Node.js version: 16.15
- Browser: Chromium
- Extra: Works as well with version 1.21.1

**Code Snippet**

```javascript

await page.locator('locator').focus();

```

**Describe the bug**
I try to handle the dropdown (not of the `<select>` type with two playwright functions:
focus and click.

In a similar way, we handle dropdowns in our entire project.

The version of the 1.22.1 - fails due to the fact that the focus() function closes the dropdown. See the video:

https://user-images.githubusercontent.com/52656401/169029036-635a9487-b519-4517-ab64-8e2372df1e4f.mp4

You can find the branch with the reproduced test in the following link:
[branch with version 1.22.1](https://github.com/AlexKomanov/playwright-version-1-22-issue/tree/version-1.22)

The same test works as well with version 1.21.1:

https://user-images.githubusercontent.com/52656401/169026710-3466eb1e-a3c7-43b6-b616-5f35af8cab11.mp4

[master branch with version 1.21.1](https://github.com/AlexKomanov/playwright-version-1-22-issue/tree/master)

Also, you can see the same results from the GitHub Actions run results in the repo.

![image](https://user-images.githubusercontent.com/52656401/169029245-1c77befd-b3bc-4de2-bca1-b2d8fa4e9d65.png)

In my case it was reproduced in the following way:
First - run the branch with the 1.21.1 version - should work.
Second - try the branch with 1.22.1 version - should fail.

In reverse order, both of the tests will fail. 

But use the results of the workflow.

Maybe the focus function is not so necessary before click, but as you can see - something in the function behavior was changed between these two versions.

**Comment by rwoll** [comment]
Thanks for the repro. I was able to observe the change in behavior between 1.21 and 1.22. Let me take a look to see what changed.

**Comment by rwoll** [comment]
#14267 has a repro and analysis. We'll still need to land a fix, but as a workaround for now, avoid calling `.focus()` on non-focusable elements, otherwise you'll lose focus on the previously focused element (in this specific case, causing your element to hide/close).

i.e. remove https://github.com/AlexKomanov/playwright-version-1-22-issue/blob/13a2149e62d7e719e3ca57232dc4d37b842e855a/tests/semantic-ui.spec.ts#L13 and it should work.

Stay tuned for fix.
