### ISSUE TITLE
[Question] Should Playwright Test be used for Unit/Integration Tests?

### ISSUE THREAD

**Issue by pkerschbaum** [microsoft/playwright#14268]
Hello!

I wanted to ask if you envision Playwright Test to be a "generic" test runner which can also be used for unit/integration tests. As a replacement of Jest, Mocha, ...  
By unit/integration tests I mean the test cases written with Playwright Test execute the code under test **directly**. Not opening a browser to test UIs (as Playwright is probably used most of the time) or testing REST APIs (as documented here: [playwright.dev/docs/test-api-testing](https://playwright.dev/docs/test-api-testing)).

I am increasingly using it for unit/integration tests because of Playwright features I love (TS support OOTB; fixtures; ...), and I am successful doing that so far.  
But I wonder if I should stay on Jest etc. because they are _intended_ to be used for unit/integration tests.

**Comment by mxschmitt** [comment]
Yes, Playwright Test is also a very generic test-runner, we use it to test various "non end-to-end Playwright" targets with it and it works really well from our experience.

**Comment by pkerschbaum** [comment]
Ok, thank you very much for the info (I am working on a blog post why I think Playwright Test is a better option for unit/integration tests, and know I can recommend Playwright Test without doubts)

**Comment by frontsideair** [comment]
I was wondering about this as well. If I understand it correctly, if you don't use the browser fixtures, Playwright doesn't set them up so you can have fast unit tests. (API or experimental component tests don't start the browser I think.) Would you let me know when the blog post is ready?

**Comment by pkerschbaum** [comment]
@frontsideair just released the blog post here :) <https://pkerschbaum.com/blog/using-playwright-to-run-unit-tests>
