### ISSUE TITLE
[Feature] Debugging devtools panels

### ISSUE THREAD

**Issue by marvinhagemeister** [microsoft/playwright#1426]
I'm currently evaluating various ways to write end-to-end tests for [Preact-Devtools](https://github.com/preactjs/preact-devtools) which is a browser extension to debug Preact apps. It works by establishing a connection with the active tab and passing messages back and forth. Things like the component tree that was rendered by Preact and some framework specific settings, etc.

To be able to test it I'd need to find a way to get a hold of the devtools frame in the same page. I've seen some examples of opening up the extension as a separate tab, but that would mean that I'd have to jump between two tabs to test the extension. Is there a better way to do that?

Screenshot of the extension in use:

![Screenshot from 2020-03-19 08-16-13](https://user-images.githubusercontent.com/1062408/77041419-27c0c600-69ba-11ea-8d08-5d00e58bac36.png)

**Comment by pavelfeldman** [comment]
As we are prioritizing the browser-neutral approach, it is unlikely that we deliver in-depth testing support for the Chrome extensions. If there is a way to create a mock environment where your extension page would be a regular web page, that would solve it. I understand it won't cover the e2e nature of your tool test though.
