### ISSUE TITLE
[BUG] Playwright breaks JS alerts

### ISSUE THREAD

**Issue by monkekode** [microsoft/playwright#14277]
**Context:**
## System:
 - OS: macOS 12.3.1
 - Memory: 588.89 MB / 16.00 GB
## Binaries:
 - Node: 16.13.1 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.1.2 - /usr/local/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/local/bin/bash

**Code Snippet**

```javascript
import {chromium} from "playwright";
const b = await chromium.launch({
    headless: false
});

const p = await b.newPage();
await p.goto('https://monkekode.github.io/alert.html');
```

**Describe the bug**

When chromium is launched via playwright, clicking simple JS alerts stops working:

Expectation:

https://user-images.githubusercontent.com/84079248/169303132-09d0e81a-9345-4252-9726-f1d0ebb04057.mov

Reality:

https://user-images.githubusercontent.com/84079248/169303338-91917def-e88f-45e6-824d-16196c7b62a7.mov

**Comment by mxschmitt** [comment]
dialogs like alert,confirm are dismissed by default, see here: https://playwright.dev/docs/next/dialogs

You can add a custom dialog handler to prevent that or intercept them.
