### ISSUE TITLE
[Question] Is there a way to do API snapshot testing with Playwright Test and ignore certain values?

### ISSUE THREAD

**Issue by ElliottDevlinPA** [microsoft/playwright#14271]
Hi,

I'm writing some end-to-end tests using Playwright Test v1.21.1 and TypeScript. A lot of my tests will publish an item and then check the metadata in a database via an API call. There is a lot of data to check for each item, so instead of having many lines of single assertions I was hoping to do an API snapshot comparison of the returned Json instead. It is also crucial that I'm able to ignore certain values that are dynamically generated each time the test is run.

I've had a look through your documentation and found some information on visual comparisons, but it also states that 'toMatchSnapshot()' can compare text too (which i think should do the trick for me), but I can't find any way to ignore certain values in the comparison. Are you able to confirm if this is possible please? If not, do you know of any other ways I could achieve this within Playwright Test please? (I believe Jest offers this functionality but, if I understand correctly, I believe I can't use Jest and Playwright Test together?)

Many thanks,
Elliott.

**Comment by mxschmitt** [comment]
There is currently no way yet, there is toMatchSnapshot but its not made for comparing objects, but we recommend using `expect(something).toBe(somethingElse)`. You can use `expect.any()` e.g. see here: https://jestjs.io/docs/expect#expectanyconstructor to compare values you only only know the type of.

**Comment by rwoll** [comment]
Another strategy you can try depending on your use case as a workaround for now is to write a normalization function that removes/replaces the unique bits (like IDs and timestamps) before snapshotting:

```ts
expect(normalize(actualAPIResponse)).toMatchSnapshot('./api.json');
```

Your normalize function would traverse your JSON, replacing `id` key's value with `<string>`.

**Comment by ElliottDevlinPA** [comment]
Thank you both for your responses.

I will look into the normalization function idea, thanks. 

For anyone else that's facing this issue, I'm also investigating a third-party option called Approvals, which looks promising - https://github.com/approvals/Approvals.NodeJS
