### ISSUE TITLE
[BUG] toHaveScreenshot() doesn't take screenshots until they match

### ISSUE THREAD

**Issue by leotg130** [microsoft/playwright#14272]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Linux
- Browser: All

**Describe the bug**
https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot
> Ensures that [Locator](https://playwright.dev/docs/api/class-locator) resolves to a given screenshot. This function will re-take screenshots until it matches with the saved expectation.

It seems that `.toHaveScreenshot()` tests against golden snapshot once, and then starts comparing against previous snapshot (eg. testing for stability). The stability test I believe should only be used for cases where no golden snapshot exists, not for when one does.

Problem probably around here: https://github.com/microsoft/playwright/blob/729e41b3aa7aa67244c6e4eb8195a328034913d7/packages/playwright-core/src/server/page.ts#L532

Maybe of some use, call log from test report:
```
    Call log:
      - expect.toHaveScreenshot with timeout 20000ms
      -   verifying given screenshot expectation
      - waiting for selector "html"
      -   selector resolved to visible <html>…</html>
      - taking element screenshot
      -   disabled all CSS animations
      -   waiting for element to be visible and stable
      -   element is visible and stable
      - 5202 pixels (ratio 0.02 of all image pixels) are different
      - waiting 100ms before taking screenshot
      - waiting for selector "html"
      -   selector resolved to visible <html>…</html>
      - taking element screenshot
      -   disabled all CSS animations
      -   waiting for element to be visible and stable
      -   element is visible and stable
      - captured a stable screenshot
      - 5202 pixels (ratio 0.02 of all image pixels) are different
```

I believe here the first and second screenshots are identical, though they don't match the golden and the test ends up failing, even though waiting a bit more should get the golden screenshot.

**Comment by ltsuda** [comment]
same / related to https://github.com/microsoft/playwright/issues/14226

**Comment by aslushnikov** [comment]
Folding this into https://github.com/microsoft/playwright/issues/14226
