### ISSUE TITLE
[Question] Why do I keep getting a "Target closed" error when I attempt to get the text content from an element via locator.textContent()?

### ISSUE THREAD

**Issue by mathewr94** [microsoft/playwright#14284]
Hi,

Please bear in mind, I'm brand new to Playwright (and TypeScript), so this is likely a very stupid mistake on my behalf. That said, here's the offending code snippet:
`const currentDressPriceString: string = await this.page.locator(DressesPage.dressesPrices).nth(i).textContent();`

When my test gets to that line of code, it fails and gives me a "locator.textContent: Target closed" error in the console. I've Googled this extensively and it doesn't seem like many others have came across this exact thing. 

In case this helps at all, the DressesPage.dressesPrices locator I'm using is:
`static readonly dressesPrices = "div.right-block > div.content_price > span.price";`

and the webpage that I'm using it on is http://automationpractice.com/index.php?id_category=8&controller=category

Thanks,
Mathew

**Comment by gauravgandhi1315** [comment]
@mathewr94 Can you try using `[page.$eval](https://playwright.dev/docs/api/class-page#page-eval-on-selector)` to retrieve the textContent

**Comment by ltsuda** [comment]
are you using a for-loop to use `.nth(i)`?

If so, could you share a little bit more the code around this line? This error message usually occurs because of missing `await` somewhere.

**Comment by oytunerdd** [comment]
```

    test.only( 'logi1n' , async ({ page }) => {
        let dressesPrices = "div.right-block > div.content_price > span.price";
        await page.goto("http://automationpractice.com/index.php?id_category=8&controller=category");
        const currentDressPriceString: string = await page.locator(dressesPrices).nth(1).textContent();
        console.log("OUTPUT" + currentDressPriceString);
});
```

Would give you the result as $50.99, if you'd like to print them all then you should use the lines in a for loop.

**Comment by ltsuda** [comment]
I’m on my phone right now but I think the issue is the last portion of your selector.

the element has two classes `price product-price`, so `span.price` I think won’t match because it does “span with class equals to ‘price’”, not “contains”.

try `span.price.product-price` or something better.

please take a look here for more options:
https://playwright.dev/docs/selectors

**Comment by gauravgandhi1315** [comment]
@oytunerdd code looks good to me. To print all the data in the list, you can probably use:

` let selector = "div.right-block > div.content_price > span.price";
const getData = await this.page.$$eval(selector, (options) => options.map((option) => option.textContent))`

**Comment by ltsuda** [comment]
I'm sorry for my last comment, I was using a mobile browser extension that was not finding the selector. Now, I tested on my PC and the selector is correct.

As Playwright recommend the usage of Locators, here's the guide to iterate over all items:

https://playwright.dev/docs/locators#lists

**Comment by mathewr94** [comment]
> are you using a for-loop to use `.nth(i)`?
> 
> If so, could you share a little bit more the code around this line? This error message usually occurs because of missing `await` somewhere.

Yes sir. Here's the full snippet:
```
    private async getIndexOfHighestPriceDress () : Promise<number> {
        let highestPriceDressIndex: number = 0;
        let highestDressPrice: number = 0.0;
        let highestPriceDressName: string = "";
        await this.page.locator(DressesPage.dressesPrices).nth(1).waitFor();
        const numberOfDresses: number = await this.page.locator(DressesPage.dressesPrices).count();
        // Presence check validation (ensuring there are dress prices on the page at all)
        expect(numberOfDresses).toBeGreaterThan(0);
        for (let i = 1; i <= numberOfDresses; i++) {
            const currentDressPriceString: string = await this.page.locator(DressesPage.dressesPrices).nth(i).textContent();
            const currentDressPrice: number = await this.convertDressPriceStringToFloat(currentDressPriceString);
            if (currentDressPrice > highestDressPrice) {
                highestDressPrice = currentDressPrice;
                highestPriceDressIndex = i;
                highestPriceDressName = await this.page.locator(DressesPage.dressNames).nth(i).innerText();
            }
        }
        expect(highestDressPrice).toBeGreaterThan(0.0);
        return highestPriceDressIndex;
    }
```

**Comment by mathewr94** [comment]
Morning, afternoon or evening (depending on where you're from). I've figured it out and it truly was a rookie mistake... the nth() function index starting at 0, not 1. Not sure why I assumed it would be 1. Everyone feel free to boo me when you read this. Thanks anyway!

**Comment by Rusinas** [comment]
@mathewr94 booo
