### ISSUE TITLE
How do I access the value for a read-only input element which is controlled by ng-model.

### ISSUE THREAD

**Issue by ZaidMomin1** [microsoft/playwright#14281]
Hi,

I have an application, which has a read-only input element and it's value is controlled by the ng-model because of which the value is not directly accessible in the DOM. 

When I tried to use `page.locator(locator).getAttribute('value')` I get an error because the value attribute is not exposed in the DOM.

**The Element**
![image](https://user-images.githubusercontent.com/17903154/169323596-969f4f4b-7f1c-4e89-99f5-798605f0c388.png)

**The Element HTML**
![image](https://user-images.githubusercontent.com/17903154/169323722-d42648b8-7492-4d57-bf15-33f2161d1a74.png)

**The Element Properties** : I can see the value here but it's not exposed as the attribute in the DOM for this element
![image](https://user-images.githubusercontent.com/17903154/169323882-353db418-92b5-4f61-a59a-ac07d3933498.png)

I also came across similar query (but it's for Katalon) : https://forum.katalon.com/t/gettext-for-readonly-text-from-input-box/32910/2

Your help would be highly appreciated. 

Thanks,
Zaid

**Comment by gauravgandhi1315** [comment]
@ZaidMomin1 Can you try something like this:

`page.locator("ng-model*=")`

**Comment by ZaidMomin1** [comment]
> @ZaidMomin1 Can you try something like this:
> 
> `page.locator("ng-model*=")`

Hi @gauravgandhi1315 Thanks for your inputs. But I quite didn't get you (sorry about that)

Do you mean
*  `page.locator("ng-model*=").getAtttibute('value')` --> Gives an error `locator.getAttribute: Unknown engine "ng-model*" while parsing selector ng-model*=`
OR 
* `page.locator("ng-model*='Automation-First-User-Name'")`  --> Gives no error. Even if I do `page.locator("ng-model*='sssssssssssssssssssss'")` it throws no error.
OR 
Something else?

Would appreciate if you could provide more insights!

**Comment by rwoll** [comment]
@ZaidMomin1 Let's make sure the expectations from the original description are clear.

> When I tried to use `page.locator(locator).getAttribute('value')` I get an error because the value attribute is not exposed in the DOM.

What is your expectation of what that should return? i.e. what are you expecting `console.log(await page.locator(locator).getAttribute('value'))` to print?

In your screenshot of the DOM, I don't see a `value` attribute, so I expect that line to print `undefined` (unless value is clipped in the screenshot). Also, instead of writing `getAttribute('value')`, you'll generally want to use https://playwright.dev/docs/api/class-locator#locator-input-value instead since it has some conveniences around labels and controlled inputs.

Here it is working:

```ts
import { test, expect } from '@playwright/test';

test('it gets value from disabled input', async ({ page }) => {
  await page.goto('https://material.angular.io/components/input/examples#input-form');
  expect(await page.locator('label', { hasText: 'Company (disabled)'}).inputValue()).toBe('Google');
})
```

**Comment by ZaidMomin1** [comment]
Hi @rwoll 

Thank you for your valuable inputs.

Yes the value attribute is not exposed in the DOM and to get the attribute results in undefined.

All I wanted is to get the value, **Automation-User-First-Name**, from the First Name textbox

Thank you for pointing me to the correct doc, https://playwright.dev/docs/api/class-locator#locator-input-value. This helped and resolved the issue.

Appreciate your help :)

**Comment by SURESHNGP** [comment]
hi @rwoll 
  how can we assert an input value/we given as input in the particular field?

**Comment by Asrithp** [comment]
Hi,
I need to capture the text that is only in a readonly field but not present in the DOM. How can I capture this text?

I can see in Properties
<img width="589" alt="Image" src="https://github.com/user-attachments/assets/39cfd2ee-3ce2-4cc6-9eee-5a86bcf3f8de" />

but not in Dom
<img width="288" alt="Image" src="https://github.com/user-attachments/assets/6d3163e2-2b88-41cb-85b5-35f75e639321" />

<img width="853" alt="Image" src="https://github.com/user-attachments/assets/8d34c29f-5329-4233-a3bd-3c7e73b8168a" />

Thanks 
asrith
