### ISSUE TITLE
[BUG] Visual comparison screenshot size differences on mobile devices

### ISSUE THREAD

**Issue by Pinka** [microsoft/playwright#14299]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Windows
- Node.js version: 16.13.0
- Browser: Chromium

**Code Snippet**

```javascript
import { test, expect } from "@playwright/test";

test("example test", async ({ page }, testInfo) => {
  await page.goto("https://playwright.dev");

  await page.screenshot({
    fullPage: true,
    path: `${testInfo.snapshotDir}/snapshot-${testInfo.project.name.split(" ").join("-")}-${process.platform}.png`,
  });

  await expect(page).toHaveScreenshot(`snapshot.png`, {
      fullPage: true,
  });
});
```

**Describe the bug**

The screenshot width on mobile devices is not the same for the screenshots taken with `page.screenshot` and with `expect(page).toHaveScreenshot`

![image](https://user-images.githubusercontent.com/5305497/169413171-9fffda55-18fe-4d22-9f17-23f4e1bdb894.png)

With project 'Desktop Chrome' it works as expected but not with 'Mobile Chrome'.
I tried to use this to compare two different sites that should look the same on desktop and on mobile.

Used this project for mobile screenshots:
```javascript
    /* Test against mobile viewports. */
    {
      name: 'Mobile Chrome',
      use: {
        ...devices['Pixel 5'],
      },
    },
```

Is this a bug or I need to compare the screenshots differently for mobile devices?

**Comment by pavelfeldman** [comment]
> The screenshot width on mobile devices is not the same for the screenshots taken with page.screenshot and with expect(page).toHaveScreenshot

Correct, the default scale for `toHaveScreenshot` is `css`, which makes screenshots smaller and hence easier to work with. We are clarifying it in the docs.

**Comment by Pinka** [comment]
Thanks for clarification. Did not notice the default scale options are different. After adding `scale : "css"` it works as expected on mobile too.

**Comment by danielo515** [comment]
Whait, what needs to be done?
