### ISSUE TITLE
[Question] Is there a way to make browsers stay open after a test is finished?

### ISSUE THREAD

**Issue by jdem4ine** [microsoft/playwright#14293]
I have a use case where I need to spin up some browsers, navigate to a section of our site and leave them on a page until they get killed by another process. Is playwright/test able to do this, or is the browser teardown baked into the tool?

Failing that, is there a way to disable timeouts in a similar fashion to passing the PWDEBUG env var while running headlessly?

**Comment by gauravgandhi1315** [comment]
You can use [time.sleep](https://stackoverflow.com/questions/529034/python-pass-or-sleep-for-long-running-processes) in Python. [JavaScript version](https://stackoverflow.com/questions/951021/what-is-the-javascript-version-of-sleep)

**Comment by rwoll** [comment]
> I have a use case where I need to spin up some browsers, navigate to a section of our site and leave them on a page until they get killed by another process.

Based on this, it sounds like you'll want to use the library version of Playwright instead of the test runner. Are you doing any test assertions?

See https://playwright.dev/docs/library#usage for using the library (which also available in Python, .NET, etc.).

NB: In **most** cases (especially in testing contexts) we recommend never using sleeps since Playwright has [auto-waiting built-in](https://playwright.dev/docs/actionability) to the methods like click. However, for your specific use case it might be appropriate since it looks like you want to run a script and then just prevent your script from exiting.

In Node, your script might look like:

```
// run.js
// Run it via:
//     node ./run.js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://foo.example.com/');
  await page.locator('text=search').click(); // this will auto-wait for search to show up on the page and be clickable, so no need to throw in sleeps nor waitForTimeouts! 
   …
  await new Promise(() => {}); // prevents your script from exiting! 
  await browser.close();
})();
```

**Comment by jdem4ine** [comment]
@rwoll Thanks for pointing me to this, does this have support for running multiple browsers (running the same script) in parallel too? I'm used to just specifying the test.describe.configure({ mode: 'parallel' }) flag but since there's no test object here that won't work

**Comment by rwoll** [comment]
> does this have support for running multiple browsers (running the same script) in parallel too?

Yes, you could do something it like:

```js
import playwright from 'playwright';
const run = (browserType) => {
  const browser = await playwright[browserType].launch();
  const page = await browser.newPage();
  await page.goto('https://foo.example.com/');
  await page.locator('text=search').click(); // this will auto-wait for search to show up on the page and be clickable, so no need to throw in sleeps nor waitForTimeouts! 
   …
  await new Promise(() => {}); // prevents your script from exiting! 
  await browser.close();
};

// Run on all browsers at once
await Promise.all(["chromium", "webkit", "firefox"].map(browserType => run(browserType)));
```

> I'm used to just specifying the test.describe.configure({ mode: 'parallel' }) flag but since there's no test object here that won't work

👍 Gotcha—makes sense! I suggested the standalone script route, but if you wanted to do it via Playwright Test you could do:

```
test('runs until killed', async ({ page }) => {
   await page.goto(…);
   …
   await new Promise(() => {});
});
```

And then just make sure all the timeouts are really high/disabled! However, using Playwright Test for this scenario where you are killing browsers externally is curious! Can you elaborate more on your use case?

**Comment by jdem4ine** [comment]
Sure, I don't need to use playwright/test by the looks of your answers (and I'd probably be better off not doing for my use case) but essentially I need to setup a bunch of browsers with different users to sit on a web page (joining a voip call) I'm giving them custom webcam footage to simulate their presence in the call

**Comment by rwoll** [comment]
Makes sense—so some variation of the scripts should work for this. Since this is outside the testing realm, community members in the Playwright Slack may be able to provide further guidance!  https://aka.ms/playwright-slack

**Comment by rhyek** [comment]
So we can stop awaiting when the browser page is closed:
```typescript
  const browser = await playwright.chromium.launch({
    headless: false,
  });
  const context = await browser.newContext();
  const page = await context.newPage();

  // stuff

  await new Promise((resolve) => {
    page.on('close', resolve); // <-- add this
  });

  await context.close();
  await browser.close();
```

**Comment by akherlan** [comment]
```js
// ...
await new Promise(() => {});
// ...
```
How to implement this line on Python?

**Comment by pawel-krzych** [comment]
> ```js
> // ...
> await new Promise(() => {});
> // ...
> ```
> 
> How to implement this line on Python?

You may find it useful to use `page.pause()`.
