### ISSUE TITLE
Can we open a codegen chromium browser with disabled-web-security?[Question]

### ISSUE THREAD

**Issue by viveksuarez7** [microsoft/playwright#14302]

**Comment by rwoll** [comment]
No, we only support the following options today:

<detail>
<summary><code>npx playwright codegen --help</code></summary>
<pre>
Usage: npx playwright codegen [options] [url]

open page and generate code for user actions

Options:
  -o, --output <file name>     saves the generated script to a file
  --target <language>          language to generate, one of javascript, test, python, python-async, csharp (default: "test")
  -b, --browser <browserType>  browser to use, one of cr, chromium, ff, firefox, wk, webkit (default: "chromium")
  --channel <channel>          Chromium distribution channel, "chrome", "chrome-beta", "msedge-dev", etc
  --color-scheme <scheme>      emulate preferred color scheme, "light" or "dark"
  --device <deviceName>        emulate device, for example  "iPhone 11"
  --geolocation <coordinates>  specify geolocation coordinates, for example "37.819722,-122.478611"
  --ignore-https-errors        ignore https errors
  --load-storage <filename>    load context storage state from the file, previously saved with --save-storage
  --lang <language>            specify language / locale, for example "en-GB"
  --proxy-server <proxy>       specify proxy server, for example "http://myproxy:3128" or "socks5://myproxy:8080"
  --proxy-bypass <bypass>      comma-separated domains to bypass proxy, for example ".com,chromium.org,.domain.com"
  --save-storage <filename>    save context storage state at the end, for later use with --load-storage
  --save-trace <filename>      record a trace for the session and save it to a file
  --timezone <time zone>       time zone to emulate, for example "Europe/Rome"
  --timeout <timeout>          timeout for Playwright actions in milliseconds (default: "10000")
  --user-agent <ua string>     specify user agent string
  --viewport-size <size>       specify browser viewport size in pixels, for example "1280, 720"
  -h, --help                   display help for command
</pre>
</detail>

What's your use case?

**Comment by viveksuarez7** [comment]
My frontend project requires me to open my dev env inside of a local host with web security disabled. The codegen opens up the chromium browser but it doesn't open with disabled-web-security and i get an CORS issue. I am unable to recreate the sceanrios for my end to end testing due to this issue
