### ISSUE TITLE
[Question] Handle beforeunload dialog

### ISSUE THREAD

**Issue by Reddriver** [microsoft/playwright#14305]
Hi,

am trying test action triggered by leave dialog. I want to stay on page (context of the page musn't be changed) or leave page. Unfortunately this dialog is not diplayed. I tryied run playwright: 

```
test('basic test', async ({ page }) => {
  await page.goto('https://my.forms.app/form/627a0185b838185b93631641/');
  await page.locator('text=SOUNDS GOOD!').click();
  page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.dismiss();
  });  
  await page.goto('https://seznam.cz');
});
```

or 

```
test('basic test', async ({ page }) => {
  await page.goto('https://my.forms.app/form/627a0185b838185b93631641/');
  await page.locator('text=SOUNDS GOOD!').click();
  page.on('dialog', async dialog => {
    console.log(dialog.message());
    await dialog.accept();
  });  
  await page.goto('https://seznam.cz');
}); 
```
The results are not what I thought. Based on https://playwright.dev/docs/dialogs. My question is, should be dialog displayed in playwright browser (headless false)?

**Comment by pavelfeldman** [comment]
What is leave dialog? Do you mean this? https://playwright.dev/docs/dialogs#beforeunload-dialog? You can only trigger it using `page.close` with special argument.

**Comment by Reddriver** [comment]
@pavelfeldman yes, that is right dialog. 
![leave](https://user-images.githubusercontent.com/7867213/169639851-1babdd43-d1e1-4d97-8d24-d6ed0d96052b.PNG)

I tried [,]( https://playwright.dev/docs/dialogs#beforeunload-dialog?), now I am see hte dialog, but I am getting error:

![image](https://user-images.githubusercontent.com/7867213/169639960-c3a1f44f-4187-45ea-babb-0864c91cb7f9.png)

```
test('basic test', async ({ page }) => {
  page.on('dialog', async dialog => {
    assert(dialog.type() === 'beforeunload');
    await dialog.dismiss();
  });
  await page.goto('https://my.forms.app/form/627a0185b838185b93631641/');
  await page.locator('text=SOUNDS GOOD!').click();
  await page.goto('https://seznam.cz');
  await page.close({runBeforeUnload: true});
});
```

Could you help me?

**Comment by yury-s** [comment]
You need to import the module that provides the `assert` function, see https://nodejs.org/api/assert.html (if you want to use node's built-in assert). This is problem is not playwright-specific though.

Closing the issue as `dialog` does address beforeunload dialog issue.

**Comment by Reddriver** [comment]
Ok, I did comment [https://github.com/microsoft/playwright/discussions/12763](https://github.com/microsoft/playwright/discussions/12763) , I don't know how to proceed.

**Comment by phyntom** [comment]
I there a way to close the dialog when navigating to the new tab. I tried so many examples but I couldn't make it work. Any help on this
