### ISSUE TITLE
[BUG] maxDiffPixelRatio is set to be 0.04 or bigger and test is failing due to "ratio 0.02 of all image pixel are different"

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#14308]
**Context:**
- Playwright Version: 1.22.1
- Operating System: linux - docker pipeline
- Node.js version: 14.6
- Browser: chrome

**Code Snippet**

```
Error: Screenshot comparison failed:

  24426 pixels (ratio 0.02 of all image pixels) are different

Expected: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-expected.png
Received: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-actual.png
    Diff: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-diff.png

  28 |     test('Landing page is loading properly with all exact contents in DE lang', async ({ browserName, page }) => {
  29 |         await page.goto(path.de.landingPage, { waitUntil: "load" })
> 30 |         expect(await page.screenshot({ fullPage: true, timeout: 4000 })).toMatchSnapshot(`${browserName}-DE.png`, { maxDiffPixels: 30, maxDiffPixelRatio: 0.2  });
     |                                                                          ^
  31 |     });
  32 |
  33 |     test('User can search for a city using IT/DE/FR lang while selected lang is EN', async ({ page, landingPage }) => {

    at /src/specs/PublicSearch/LandingPage.test.ts:30:74
```

```
Error: Screenshot comparison failed:

  24426 pixels (ratio 0.02 of all image pixels) are different

Expected: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-expected.png
Received: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-actual.png
    Diff: /test-results/PublicSearch-LandingPage-Landing-page-Test-Sui-5c31e-ing-properly-with-all-exact-contents-in-DE-lang-Chrome-retry2/chromium-DE-diff.png

  28 |     test('Landing page is loading properly with all exact contents in DE lang', async ({ browserName, page }) => {
  29 |         await page.goto(path.de.landingPage, { waitUntil: "load" })
> 30 |         expect(await page.screenshot({ fullPage: true, timeout: 4000 })).toMatchSnapshot(`${browserName}-DE.png`, { maxDiffPixels: 30, maxDiffPixelRatio: 0.04  });
     |                                                                          ^
  31 |     });
  32 |
  33 |     test('User can search for a city using IT/DE/FR lang while selected lang is EN', async ({ page, landingPage }) => {

    at /src/specs/PublicSearch/LandingPage.test.ts:30:74
    ```

**Describe the bug**

maxDiffPixelRatio is set to be 0.2 and test is failing due to ratio 0.02 of all image pixel are different

**Comment by amrsa1** [comment]
@aslushnikov am i missing anything here ?

**Comment by yury-s** [comment]
The test is failing because of maxDiffPixels parameter not maxDiffPixelRatio. The image diff contains `24426 pixels` whereas toMatchSnapshot is configured with `maxDiffPixels: 30`, you can increase the absolute number to allow for that many pixels. Does that help?

**Comment by amrsa1** [comment]
> The test is failing because of maxDiffPixels parameter not maxDiffPixelRatio. The image diff contains `24426 pixels` whereas toMatchSnapshot is configured with `maxDiffPixels: 30`, you can increase the absolute number to allow for that many pixels. Does that help?


If its failing in maxDiffPixels why its not showing how much difference in pixels as its usually show

**Comment by yury-s** [comment]
> If its failing in maxDiffPixels why its not showing how much difference in pixels as its usually show

Do you mean you don't see those pixels on `chromium-DE-diff.png` ? If you share full repro or at least the png results we can have a look.

**Comment by amrsa1** [comment]
> > If its failing in maxDiffPixels why its not showing how much difference in pixels as its usually show
> 
> Do you mean you don't see those pixels on `chromium-DE-diff.png` ? If you share full repro or at least the png results we can have a look.

No i meant if its failing due to pixel difference should the  playwright show in the logs that there are difference in pixel

**Comment by yury-s** [comment]
> No i meant if its failing due to pixel difference should the playwright show in the logs that there are difference in pixel

This is what it does including the size of the diff:

```
Error: Screenshot comparison failed:

  24426 pixels (ratio 0.02 of all image pixels) are different
```

Do you suggest changing the message format to be more obvious or what else do you expect to see in the logs?

**Comment by amrsa1** [comment]
@yury-s  sorry for the confusion whats the difference between maxDiffPixel and maxDiffPixelRation, and what  is threshold 
and how its functioned if I added all of them as option

**Comment by yury-s** [comment]
These are two different options. They allow to relax comparison condition. In order for a check to pass it has to meet all configured conditions, so in your case:
- one condition is met, the total diff pixels ratio is 0.02 which is less then `maxDiffPixelRatio: 0.2`
- the other condition is not met though because there are 24426 different pixels between the two images which exceeds configured threshold `maxDiffPixels: 30` by 24394. This is the reason the test fails.

The feature was discussed a bit in [the release video](https://www.youtube.com/watch?v=6vV-XXKsrbA), hope that helps with understanding the intents of both options.

**Comment by valtersantosmatosmanulife** [comment]
@yury-s coming back here as I got exactly the same issue. I believe that changing the error message could make it much clear, maybe from `9106 pixels (ratio 0.01 of all image pixels) are different.` to `9106 pixels (max set to 30), ratio 0.01 (max set to 0.01) of all image pixels are different.`.

Happy to do PR if you think its ok :)
