### ISSUE TITLE
[BUG] sort out locatorassertions vs test-assertions docs

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#14301]
It looks like those are still unresolved.

**Comment by pavelfeldman** [comment]
Different ports have it differently, Node.js does not include locatorassertions, which makes it hard to reason about them

**Comment by LeviticusMB** [comment]
Not sure you're discussing this or something else? But the links in the https://playwright.dev/docs/next/test-assertions#api-reference section don't work. Also, *API/API Reference/Classes/Assertions* is the same as *Docs/Playwright Tests/Assertions* which super confusing and also breaks the *Next* & *Previous* page links at the bottom.
