### ISSUE TITLE
[Question] How can I get value for "testId" query-parametr for each test in HTML-report

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#14310]
### Problem:

We push a message into the slack that contains a link to the playwright HTML-report. My colleagues asked that this message contain a link not only to the full report, but also to each test.

Example of a link to one of the tests:
`https://test.com/index.html#?testId=ec870af7b8935a30dd92c181a150c5a3d014e16b-0671b0d0053685bb8fe9ac82667f6d117cb6faf3`

I read the documentation, and also looked at the structure of the playwright JSON-report and didn't find that testId was specified for each test in it. How can I get testId query for each test in the suite?

_____
P.S. Thank you for such a wonderful tool! <3

**Comment by pavelfeldman** [comment]
We don't expose it, but you can use the value from [here](https://github.com/microsoft/playwright/blob/634ba85c83ae19de1e1610e5b393e35eb03012e4/packages/playwright-test/src/reporters/raw.ts#L232) for now.

**Comment by pavelfeldman** [comment]
I'll leave this open for us to expose it.

**Comment by Pd51** [comment]
can we also get testId in xml report

**Comment by hoangtaiki** [comment]
@Pd51 Have you found a way to locate it in the HTML report?

**Comment by hoangtaiki** [comment]
The simplest way to retrieve the testId is by adding `['json', { outputFile: 'results.json' }]` to the `reporter` section in `playwright.config.js`. This will generate a `results.json` file where you can easily locate the testId.
