### ISSUE TITLE
[Question] How to get around incognito mode - or how to pass argument to already running test

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#14312]
For testing salesforce it would be easier to use the installed browser in normal mode `incognito = false`. This is because our salesforce is set up to require a `<one-time-verification-code>` if the user logs in without any prior logins. 

What am i asking

 - Either is there a way to use the installed edge in normal mode (`incognito=false)`?
 - Or how can cookies from a previous session be used?
 - Or how can i pass an argument `<my-code>` to an already running test?

From [Salesforce - Methods for Verifying Your Identity](https://help.salesforce.com/s/articleView?id=sf.activating_computer.htm&type=5)

> If device activation is turned on, you’re prompted for a verification method when you log in to Salesforce from a browser or application that we don’t recognize. 
> ....
>  - Email (not available for MFA)
> Salesforce sends an one-time password (OTP) in an email to the address associated with your account. The code expires after 24 hours.
>
> ...
> Salesforce doesn’t ask you to verify your identity again when you log in from the same browser or application. Exceptions are if you clear browser cookies, set your browser to delete cookies, or browse in private or incognito mode. In these cases, you’re prompted to verify your identity every time you log in to Salesforce from an IP address that’s not defined as trusted for your org.

According to our security departement whitelisting of certain IPs is no option.

I would like to have these [LaunchOptions](https://playwright.dev/docs/api/class-browsertype#browser-type-launch)

```
var myLaunchOptions = {
    executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', // use installed edge
    headless: false, 
    incognito: false, // to my understanding this is no valid option
    slowMo: 4000
}
```
The code below outlines the sequence of events

```
const playwright = require('playwright');

(async () => {
  const browser = await playwright.chromium.launch({  myLaunchOptions });  
  const page = await browser.newPage();
  await page.goto('https://ourCompany.salesforce.com/'); // login-page
  await page.locator('form input[name="_username"]').fill(USER.name);
  await page.locator('form input[name="_password"]').fill(USER.pass);
  await page.locator('form input[type="submit"]').click();
  await page.screenshot({ path: 'salesforce_msedge_001_after_login_click_.png' });

  // trouble starts at this point
  if(page.url().includes(verificationURL))
  {
      var <my-verification-code> = xxx // pass code to already running test
      await page.fill('#emc', '<my-verification-code>');  // getCodefromChangedfile();
  }
  await browser.close();
})();
```
Above we are stuck; 
  - because now the  `<verification-code>` has to be entered 
  - but at the time this test was started the code was yet unknown
  - it will only be send by e-mail briefly after login above which is to late for this test run
  -  unless there is an option to pass an argument or read from a local file to an already running test

**Comment by rwoll** [comment]
See https://playwright.dev/docs/auth#multi-factor-authentication which describes an MFA workflow using Persistent Contexts.

Alternatively, if you are using Playwright Test and want isolation between runs:

1. (Manually) Use codegen to perform your MFA and save off Browser Auth state: https://playwright.dev/docs/codegen#preserve-authenticated-state. This can be used in subsequent test runs.
2. Assuming you are using Playwright Test, use the `storageState` option in your Playwright Test config and point it at the file from (1): https://playwright.dev/docs/api/class-testoptions#test-options-storage-state

If neither of those work for you, or if you have additional questions while trying them out, please re-open the issue! Thanks!

**Comment by surfmuggle** [comment]
I can not figure out how to apply the mentioned steps


## Option 1 launchPersistentContext 

I did the follwing

1. Create two  directories `C:\dev\webtest>mkdir mfaTest1` and `C:\dev\webtest\mfaTest1>mkdir userDataContext`
2. Create a node project `C:\dev\webtest\mfaTest1>npm init --yes` and install playwright   `C:\dev\webtest\mfaTest1>npm install playwright@latest`
3. Add index.js inside `C:\dev\webtest\mfaTest1>` (see code below)
4. Running index.js `C:\dev\webtest\mfaTest1>node index.js` starts the browser
5. Manually enter Salesforce-Login-URL into browser and log in (1st step: enter user, pass and click login; 2nd step: receive code by e-mail and enter code)
6. close browser

Result
 - Expected: inside `C:\dev\webtest\mfaTest1\userDataContext>` is a file that contains some context information
 - Actual: folder is empty


The code inside index.js
```
const { chromium } = require('playwright');
(async () => {
    const userDataDir = './userDataContext';
    const context = await chromium.launchPersistentContext(userDataDir, { headless: false });
    // Execute login steps manually in the browser window
})();
```

It is unclear to me how [`testOptions.storageState`](https://playwright.dev/docs/api/class-testoptions#test-options-storage-state) has to be incorporated. 


## Option 2: npx codegen

 1. Run `C:\dev\webtest\salesforce-record>npx playwright codegen --save-storage=auth.json` 
 2. Do all the steps as written above in step 5 (log in, wait for e-mail, enter code, close browser)

Result: `auth.json` is created.

How to proceed from here? How to use the auth.json?

**Comment by rwoll** [comment]
@surfmuggle Sorry for the confusion! Our docs could use some improvement here!

I've added a full end-to-end example here: https://github.com/rwoll/playwright-reuse-auth-demo

The README in the root points you to one of two demos.

Let me know if that clarifies things!

> How to proceed from here? How to use the auth.json?

https://github.com/rwoll/playwright-reuse-auth-demo/blob/5696769af8ba17a0ed472f7706de93e61d47417a/playwright-library/index.js#L18

**Comment by surfmuggle** [comment]
Regarding the demo. Thanks a lot. It was very useful. For a novice some additional steps might be helpful. If you want you can see [this PR](https://github.com/surfmuggle/playwright-reuse-auth-demo/tree/surfmuggle-patch-1)
