### ISSUE TITLE
[BUG] WebKit crashes when retrieving a11y snapshot for [aria-modal] 

### ISSUE THREAD

**Issue by lemnis** [microsoft/playwright#14328]
**Context:**
- Playwright Version:  1.22.2
- Operating System: Linux
- Node.js version: 12.22
- Browser: Webkit

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.goto('http://www.w3c-test.org/core-aam/aria-modal_true-manual.html');
  await page.accessibility.snapshot()
})();
```

**Describe the bug**

Webkit crashes when I try to get the accessibility snapshot of a page that contains `[aria-modal]`. The error I receive is `accessibility.snapshot: Target closed `

**Comment by mxschmitt** [comment]
I was able to repro on macOS.

**Comment by yury-s** [comment]
It looks like it will be fixed with next webkit update (1652).

**Comment by yury-s** [comment]
Fixed with recent roll: https://github.com/microsoft/playwright/pull/14709
