### ISSUE TITLE
[Question] Possible to keep the window when "Resume" hits an error?

### ISSUE THREAD

**Issue by mgenware** [microsoft/playwright#14329]
![image](https://user-images.githubusercontent.com/11565096/169690500-238db977-d4da-45a7-8679-3535fc135ac8.png)

When "Step over" hits an error, the inpector window stays, I can live debug the issue.

But when "Resume" hits an error, the inpsector window simply disappers. Error and stack traces are printed in console instead. Is there a way to keep the inspector window when "Resume" hits an error? Thanks.

**Comment by yury-s** [comment]
As far as I can tell if there is an exception both step over and resume will end up with playwright closed if there is an exception in the code like this:

```
(async () => {
  const browser = await playwright.webkit.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://google.com');
  // Error is thrown at this line:
  await page.goto('http://asdasdasd/asdasd');  
  await context.close();
  await browser.close();
})();
```
Can elaborate on where you see the difference in behavior between the two or maybe share a code?

Do I understand correctly that you want the inspector to pause if there is an unhandled exception in the code?

**Comment by mgenware** [comment]
Hi @yury-s , sorry I wasn't clear enough. Say I'd like to debug a failing test, I start playwright with:

```sh
npx playwright test --debug -g "<failed test name>"
```

The inspector window appears. I can keep clicking the "Step over" button until it hits a failed assertion. Now the process hangs and I can live debug the issue like this:
![image](https://user-images.githubusercontent.com/11565096/170204966-dca02b76-f78e-471c-8fc6-460c41163e1b.png)

So I figured intead of multiple "Step over" clicks, I can use the "Resume" button, which I thought should function like a "Debug" button in Visual Studio. One click of that would lead me to the failed assertion code. But turned out it always closes the inpector window and report the error to console.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
