### ISSUE TITLE
How do I deploy trace viewer locally?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#14320]
https://github.com/microsoft/playwright-java/issues/655#issuecomment-961197336 Now the source is 404.

**Comment by mxschmitt** [comment]
There are multiple ways:

a) checkout the git repository, run npm ci and npm run build. Then the trace viewer is as of today under: `packages/playwright-core/lib/webpack/traceViewer/`
b) you can download it from NPM: `https://registry.npmjs.org/playwright-core/-/playwright-core-1.22.2.tgz`  and find it under: `http://package/lib/webpack/traceViewer/`

**Comment by yury-s** [comment]
Closing per the last comment.

**Comment by hes69** [comment]
I tried to host Trace viewer locally but it seems something is missing, I got following error
TypeError: Cannot read properties of undefined (reading 'register')
does anyone know solution?

**Comment by mxschmitt** [comment]
It needs a secure context (https://) or localhost, otherwise service workers are not available.

**Comment by hes69** [comment]
I deploy it in localhost and access it via http, and it seems sw.bundle.js is not found in this line of code
navigator.serviceWorker.register("sw.bundle.js")
Do you mean I couldn't access through http?

**Comment by yandongxu** [comment]
> I deploy it in localhost and access it via http, and it seems sw.bundle.js is not found in this line of code navigator.serviceWorker.register("sw.bundle.js") Do you mean I couldn't access through http?

Same here
