### ISSUE TITLE
[Question]: Save HAR files 

### ISSUE THREAD

**Issue by sla-te** [microsoft/playwright#14338]
### Your question

Is there a way to do that programatically?

**Comment by mxschmitt** [comment]
Recording a har file is only supported when [creating a new context](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-har) and when its closed its saved. What is your use-case for starting and stopping it on-demand?

**Comment by unlikelyzero** [comment]
@sla-te you can add it to your playwright config as follows:

      name: "local-chrome",
        use: {
            browserName: 'chromium',
            channel: 'chrome',
            baseURL: 'https://',
            contextOptions: { recordHar: { path: './har.har'}}
        },

**Comment by sla-te** [comment]
Mhh, thanks for this, sadly I use my own browser which I connect to via ```chromium.connect_over_cdp(endpoint_url=ws)```, is there a different approach via dev console to achieve it?

**Comment by yury-s** [comment]
You can create a [new context](https://playwright.dev/docs/api/class-browser#browser-new-context) in the remote browser and pass recordHar option as Max suggested above, it will work the same way as for local browser (will save the har file locally).
