### ISSUE TITLE
[BUG] Tracing does not work

### ISSUE THREAD

**Issue by NeilRiver** [microsoft/playwright#14334]
**Context:**
- Playwright Version: v1.22.0
- Python python-3.10.4-amd64
- Browser: Chromium
- OS -> Windows 11 

```
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    context = browser.new_context()

    # Start tracing before creating / navigating a page.
    context.tracing.start(screenshots=True, snapshots=True, sources=True)

    browser.new_page().goto("https://playwright.dev")

    # Stop tracing and export it into a zip archive.
    context.tracing.stop(path = "trace.zip")
```
![image](https://user-images.githubusercontent.com/41006652/169708776-7c016e5e-6625-4354-92b6-ef95a96cb145.png)

**Comment by rwoll** [comment]
Change the following line:

```
    browser.new_page().goto("https://playwright.dev")
```

to:

```
    context.new_page().goto("https://playwright.dev")
```

and it should work. Since you are enabling tracing on the `context` (via `context.tracing.start(screenshots=True, snapshots=True, sources=True)`), you'll want to create pages from there instead of directly off the `browser`.
