### ISSUE TITLE
pageshot case memory leak

### ISSUE THREAD

**Issue by roy-k** [microsoft/playwright#14336]
context: 
- playwright version: 1.19.2
- operation System: Linux
- node.js version:  14 & 16
- browser: chromium

I am using pageshot to save images, but the memory increased obvious~
when check code line by line, I find this: It seems pageshot method case a memory leak?

1. **the heap keeps even I didn't use the Buffer**
<img width="904" alt="image" src="https://user-images.githubusercontent.com/21359236/169662255-9313c956-c086-45cd-b2e1-7467c59de711.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/21359236/169662343-f44746ea-645c-4443-a455-2a1707f01a95.png">

2. **and when delete this code, the Retained Size clear**:
<img width="998" alt="image" src="https://user-images.githubusercontent.com/21359236/169662422-2a94f2fc-0380-44df-a710-716aa9a26847.png">
<img width="718" alt="image" src="https://user-images.githubusercontent.com/21359236/169662452-48a6771e-6c29-425b-9ece-92b416356f5e.png">

_Originally posted by @roy-k in https://github.com/microsoft/playwright/issues/6319#issuecomment-1133694599_

**Comment by pavelfeldman** [comment]
It looks like client-side fixture values are leaking via Fixture::usages.
