### ISSUE TITLE
[BUG] Upgrade 1.22.2, run 'Record using custom setup',  no Inspector window display

### ISSUE THREAD

**Issue by hsl727261250** [microsoft/playwright#14341]
**Context:**
- Playwright Version: 1.22.2
- Operating System: macOS 11.5.2 (20G95)
- Node.js version:  v16.14.2
- Browser: Playwright integrated Chromium
- Extra: Typescript
- Env: vscode 1.67.2 (Electron: 17.4.1 Chromium: 98.0.4758.141)

**Code Snippet**
run the code from [document](https://playwright.dev/docs/codegen#record-using-custom-setup)

```javascript
import { chromium } from 'playwright';

async function start() {
    // Make sure to run headed.
    const browser = await chromium.launch({ headless: false });

    // Setup context however you like.
    const context = await browser.newContext({ /* pass any options */ });
    await context.route('**/*', route => route.continue());

    // Pause the page, and start recording manually.
    const page = await context.newPage();
    await page.pause();
};

start();
```

**Describe the bug**
my vscode `launch.json` file:
```json
{
    "configurations": [
        {
            "command": "npm run test",
            "name": "test",
            "request": "launch",
            "type": "node-terminal"
        }
    ]
}
```
run `test` from vscode `Run and Debug`,
on Playwright 1.17.0 or 1.17.1, it will open a Chromium and a Inspector window;
upgrade to Playwright 1.19.0, no Inspector window display;
upgrade to Playwright 1.22.2, no Inspector window display.

**Comment by mxschmitt** [comment]
I was try to reproduce it but for me when running your code snippet the inspector opens. Does it maybe open and its out of viewport then? Do you see a Playwright icon the taskbar?

**Comment by hsl727261250** [comment]
only a Chromium icon, no Playwright icon. i will clean cache and integrated Chromium, and retry it.

**Comment by mxschmitt** [comment]
This is expected. When using the vscode debug terminal or using Run and Debug we expect that a JavaScript debugger is attached.

Having a JavaScript debugger attached + the Playwright Inspector turned out to be not beneficial since you have breakpoints on both sides.

**Comment by hsl727261250** [comment]
got it.
close.
