### ISSUE TITLE
[BUG] codegen doesn't work if recorded page tampers Set

### ISSUE THREAD

**Issue by mzujevova** [microsoft/playwright#14344]
**Context:**
## System:
 - OS: macOS 12.3.1
 - Memory: 74.42 MB / 16.00 GB
## Binaries:
 - Node: 18.1.0 - /usr/local/bin/node
 - npm: 8.8.0 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.21.1 => 1.21.1 

I have been exploring the possibility of using Playwright for our automated testing. However when I run Playwright in codegen mode, the page is not reacting to anything except for right clicks or button presses: e.g. if a field is selected on page load, I can type into it, but if it is not, there is no way to make it active. If I turn off Recording, page works fine again.

The console is full of these errors:
```
Uncaught TypeError: allEngineNames is not a function or its return value is not iterable
    at InjectedScript.parseSelector (<anonymous>:3791:24)
    at chooseFirstSelector (eval at extend (login:3948:39), <anonymous>:1281:43)
    at calculate (eval at extend (login:3948:39), <anonymous>:1083:18)
    at calculateCached (eval at extend (login:3948:39), <anonymous>:1118:15)
    at generateSelectorFor (eval at extend (login:3948:39), <anonymous>:1123:10)
    at generateSelector (eval at extend (login:3948:39), <anonymous>:1056:26)
    at Recorder._onFocus (eval at extend (login:3948:39), <anonymous>:1676:36)
    at HTMLDocument.eval (eval at extend (login:3948:39), <anonymous>:1538:54)
```

They are genereated basically on each event, including onMouseMove and the like, so they differ only in the ```Recorder._onFocus``` step, the rest of the callstack is the same for all of them.

Sadly, I cannot share the page I am working with here, as it is a non-disclosable company property, but I did some debugging, and here's something that may or may not be relevant. The Playwright part fails in this particular place:

```
parseSelector(selector) {
    const result = parseSelector(selector);
    for (const name of allEngineNames(result)) {
      if (!this._engines.has(name))
        throw this.createStacklessError(`Unknown engine "${name}" while parsing selector ${selector}`);
    }
    return result;
  }
```

Before getting passed into allEngineNames(), result looks as such:

```
{
    "parts": [
        {
            "name": "css",
            "body": [
                {
                    "simples": [
                        {
                            "selector": {
                                "css": "[placeholder=\"Username\"]",
                                "functions": []
                            },
                            "combinator": ""
                        }
                    ]
                }
            ],
            "source": "[placeholder=\"Username\"]"
        }
    ]
}
```

And allEngineNames(result) returns this (which is deemed non-iterable):

```
{
    "_values": [
        "css"
    ],
    "_size": 1
}
```

I am filing this as a bug, because this is a standard Playwright installation, without any specific configuration. I will gladly provide as much additional info as I can when needed.

**Comment by yury-s** [comment]
It seems that the page (or one of the libraries it depends on) modifies constructor of `Set` and the objects created via `new Set()` become non-iterable which breaks  [`allEngineNames`](https://github.com/microsoft/playwright/blob/71a55c74daf4117a1501f65242bc0d66333980e6/packages/playwright-core/src/server/isomorphic/selectorParser.ts#L125-L136). Can you check that by running `console.log(Set)` in the page where the codegen fails and post the result here?

**Comment by mzujevova** [comment]
That returns
```
ƒ (){var n=arguments[0];this._values=[];this.size=this._size=0;n&&typeof n.forEach=="function"&&n.forEach(function(n){this.add.call(this,n)},this)}
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by bobotzzz** [comment]
this issue still persists, I can reproduce it on Windchill systems, was anything done to further investigate this issue? 
<img width="1275" alt="image" src="https://github.com/user-attachments/assets/8d4b0f52-5b79-4382-86f0-6d52613bb65d">
