### ISSUE TITLE
[BUG]record video got blurred

### ISSUE THREAD

**Issue by wanghaisheng** [microsoft/playwright#14359]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Python version: [e.g. 3.7, 3.9]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally.

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    # ...
    browser.close()
```

**Describe the bug**

Add any other details about the problem here.

            context = await browser.new_context(record_video_dir=record_video_dir,
            # is_mobile=True,

            record_video_size={"width": 428, "height": 926},
            screen={"width": 428, "height": 926},
            viewport={"width": 428, "height": 926}
            )

https://www.indiehackers.com/post/how-to-come-up-with-good-business-ideas-aee2850c63

https://user-images.githubusercontent.com/2363295/169890523-d556b7af-2e01-4087-9ddf-b2a4a0643b5c.mp4

**Comment by yury-s** [comment]
Scrolling text is one of the scenarios where vp8 codec that we use for the video might struggle with the quality. We try to balance between the video file size and its quality. If you need to capture better images you can use [Tracing](https://playwright.dev/python/docs/next/api/class-tracing) which will also capture state of the dom.

Closing this bug as there are no plans on changing this behavior.
