### ISSUE TITLE
[Feature] Electron automation support on Java

### ISSUE THREAD

**Issue by MeravYa** [microsoft/playwright#14368]
Hi, is there a plan to support Electron automation on Java as well? In addition, why is Electron support defined as experimental? What are the current gaps? My team was started to think of moving our tests from Selenium to Playwright but shifting to Javascript might be painful from our automation team perspective.

Thanks

**Comment by mxschmitt** [comment]
The main reason why it is experimental is, that we might re-shape the API in the future a bit (but it should be easy to migrate!) - so feel free to jump on the train and help us to add missing methods, features or spot bugs!

For Java support, I'm folding it into https://github.com/microsoft/playwright-java/issues/830
