### ISSUE TITLE
[Question] npx playwright install necessary with docker images?

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#14366]
I'm attempting to speed up my circleci runs and am using the playwright focal images. If I don't perform a npx playwright install step, the run will fail. Here's a recent example

CircleCI Config:
https://github.com/nasa/openmct/commit/c56fe6d8f34191e7de45db75e14459344adbd5d4

The circleci config's playwright base image version matches the package.json playwright/test version of 1.21.1

### Spin Up Environment step
```
Build-agent version 1.0.124340-e0f27245 (2022-05-23T16:04:14+0000)
System information:
 Server Version: 20.10.16
 Storage Driver: overlay2
  Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.13.0-1023-aws
 Operating System: Ubuntu 20.04.4 LTS
 OSType: linux
 Architecture: x86_64

Starting container mcr.microsoft.com/playwright:v1.21.1-focal
mcr.microsoft.com/playwright:v1.21.1-focal:
  using image mcr.microsoft.com/playwright@sha256:c3c8a833254aaad31b2d336e67b0dbb9af744a12ab486e18f230033b99649c4f
  pull stats: Image was already available so the image was not pulled
  time to create container: 6ms
  image is cached as mcr.microsoft.com/playwright:v1.21.1-focal, but refreshing...
v1.21.1-focal: Pulling from playwright
Digest: sha256:c3c8a833254aaad31b2d336e67b0dbb9af744a12ab486e18f230033b99649c4f
Status: Image is up to date for mcr.microsoft.com/playwright:v1.21.1-focal
Time to upload agent and config: 339.235221ms
Time to start containers: 378.141847ms
```

### npm run test step
```
 1) [chrome] › branding.e2e.spec.js:31:5 › Branding tests › About Modal launches with basic branding properties 

    browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1000/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team     
  
```

**Comment by yury-s** [comment]
Is it some image derived from the official one? The file it is complaining about is there in the image:
```
$ docker run mcr.microsoft.com/playwright:v1.21.1-focal /bin/bash -c 'ls -lh /ms-playwright/chromium-1000/chrome-linux/chrome'
-rwxrwxrwx 1 root root 310M Apr 18 20:59 /ms-playwright/chromium-1000/chrome-linux/chrome
```
unless you deleted it somehow. Can you share the code and commands that reproduce it?

**Comment by yury-s** [comment]
Can you try adding [`PLAYWRIGHT_SKIP_BROWSER_GC=1`](https://playwright.dev/docs/next/browsers#stale-browser-removal) to those workflows and see if it helps?

**Comment by unlikelyzero** [comment]
@yury-s https://app.circleci.com/pipelines/github/nasa/openmct/10871/workflows/1b69be63-1f07-4542-82a8-66e202956275/jobs/36822/steps is the failing job in circle ci.

I'll try that playwright check now

**Comment by yury-s** [comment]
This is not specific to Circle CI but rather to the playwright dependencies in other packages that you use. @rwoll pointed out that you have @percy/playwright in your packages deps and that packages itself specifies playwright as its peer dependency which leads to this dependency structure:

```sh
$ npm ls @playwright/test playwright
openmct@2.0.4-SNAPSHOT <...>/openmct
├─┬ @percy/playwright@1.0.3
│ └── playwright@1.22.2
└── @playwright/test@1.21.1
```
Note how @percy/playwright [brings](https://github.com/percy/percy-playwright/blob/deaa3946c57d81b0282da1aaafd8330c4c21549d/package.json#L34-L36) in a newer version (1.22.2) of `playwright` and openmct depends on @playwright/test@1.21.1.

Now, if playwright@1.22.2 is installed first (which is true) it will by default cleanup browser cache with older browser versions. For now you can use `PLAYWRIGHT_SKIP_BROWSER_GC=1` and longer term right fix would be to fix @percy/playwright to change its peer dependency from `playwright` to `playwright-core`.

**Comment by yury-s** [comment]
I'm closing this bug as there is nothing else we can do on our end. I've sent a PR to the Rercy repo so they should be aware of the issue.

**Comment by unlikelyzero** [comment]
@yury-s and @rwoll thanks again for taking a look at this. I was scratching my head for a while!

**Comment by yury-s** [comment]
@unlikelyzero the [PR](https://github.com/percy/percy-playwright/pull/84) was merged, you should be able to drop `PLAYWRIGHT_SKIP_BROWSER_GC=1` from your config after updating to a revision of percey that includes the fix.

**Comment by unlikelyzero** [comment]
@yury-s I removed it and confirmed that it worked. Thank you
