### ISSUE TITLE
[Question] How to call to the parent element (in the reverse direction)

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#14374]
Hi team!

I have a case when I need to locate a selector from some child element. I have a unique element, and one of the elements of the upper has an attribute that I want to check. 

![image](https://user-images.githubusercontent.com/52656401/169990018-feabfc80-0c69-4f3e-b5ba-c505dce9e058.png)

There are a lot of options to find elements inside others - but what about a reverse direction? Do we have another option than `:above(inner > selector)`?

**Comment by yury-s** [comment]
You can use [`has`](https://playwright.dev/docs/api/class-page#page-locator-option-has) to specify condition on the contained element, something like:

```
page.locator('table', {has: page.locator('#isc_2Lo') });
```
will select the `table` element above. If you need to select the span, before the table you can e.g. select parent of the table instead and then select it's child `span`, something along these lines:

```
page.locator('div.table-container', {has: page.locator('#isc_2Lo') }).locator('span[align=left]');
```
