### ISSUE TITLE
How to pass newPage between methods?

### ISSUE THREAD

**Issue by agataDeviniti** [microsoft/playwright#14373]
I have following problem with passing newPage between methods. Let's assume, I have page1 and button on it, which allows me to open newPage (page2). After clicking this button I receive newPage(page2) and I would like to make all other methods on page2.
That is why I need 2 separate methods:
Method 1 (navigateTo.page2()) -> click button, open newPage and check if it exists
Method 2 (createIssue()) - > check URL and create issue on page2

**My test:**
```
test('How to pass newPage between methods?', async ({
    page1, page2,
}) => {
    await test.step(
        'Navigate to page2',
        async () => {
            await page1.commonActions.navigateTo.page2();
        },
    );
    await test.step(
        'Create issue on page2',
        async () => {
            await page2.commonActions.createIssue();
        },
    );
});
```

**Method1 (navigateTo.page2()):**
  ```
  navigateTo = {
        page2: async (): Promise<any> => {
            const context = this.page.context();
            const [newPage] = await Promise.all([
                context.waitForEvent('page'),
                this.page
                    .frameLocator(this.iframes.iframe1)
                    .locator(this.myPage1.button)
                    .click(),
            ]);
            await newPage.waitForLoadState('domcontentloaded');
            await newPage.bringToFront();
        await newPage.url();
```

**Method2 (print URL and createIssue)**
```
    async createIssue() {
        await this.page.url();
    }
```
What I need is to pass the received newPage from method1 to method2. Right now method2 throws URL from page1. What is important method 1 and method 2 are in separate files and sometimes I would like to use method2 on page 1. I thought .bringToFront() would help me in this case, but without succes. I have also tried to assign page = newPage, but it throws error.  Is there any possibility to access newPage in method2?

**Comment by yury-s** [comment]
If you just want to pass page2 to the second step you can store it in a local variable in the containing test:

```js

test('How to pass newPage between methods?', async ({
    page1
}) => {
    let page2;
    await test.step(
        'Navigate to page2',
        async () => {
            page2 = await page1.commonActions.navigateTo.page2();
        },
    );
    expect(page2).toBeTruethy();
    await test.step(
        'Create issue on page2',
        async () => {
            await page2.commonActions.createIssue();
        },
    );
});
```

> What I need is to pass the received newPage from method1 to method2.

You can change that method into a function that accepts page object:

```js
    async createIssue(page) {
        await page.url();
    }
```
It's not quite clear from the description what your constraints are. If you are trying to pass page2 between methods on commonActions then you can store it in a field on that object.
