### ISSUE TITLE
[Question] - Component using jsx files

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#14376]
Hello , regarding this https://github.com/microsoft/playwright/issues/14290 (Will cc @rwoll as he might have some context) - I could it make work, however, I am having an issue when using .jsx files.
All the components are .jsx , so I created a spec.jsx file and the import statements are failing.
I've tried using require() instead but it says it can't find the modules. When switching to spec.tsx and using import, it works fine, but there are some .jsx components that does not work due to how they are build I assume, it throws an error: The type {} is missing the following properties from type ....
Is there any issues using .jsx ?
Thanks!

**Comment by rwoll** [comment]
> Is there any issues using .jsx ?

Yes, but https://github.com/microsoft/playwright/pull/14326 landed a few hours ago that should fix it when we do the next release (likely a patch release in the coming days).

In the interim, you can try it out by doing `npm i @playwright/experimental-ct-react@next` in the project you have. After running that command, you should see the version of `@playwright/experimental-ct-react` change in your package.json.

**Comment by imartinflores** [comment]
Appreciate it! Will follow that one!

**Comment by imartinflores** [comment]
hey @rwoll just in case it helps, Ill provide some feedback. I've tried installing it using @next , and then updated the .tsx file to .jsx and the imports to require(). I've got 2 errors:
1: When using import
```
Error: Requiring @playwright/test second time,
First:
Error
   at ..\..\node_modules\@playwright\test\lib\index.js:69
   }
   } else {
 process['__pw_initiator__'] = new Error().stack;
                              ^
  }
```

2 - When updated to require()
```
const component = await mount(<TestComponent slides={[slides]} />)
                                  ^

SyntaxError: Unexpected token '<'


```

**Comment by rwoll** [comment]
@imartinflores What's the output of `npm ls @playwright/test @playwright/experimental-ct-react`? I suspect mismatched versions. 

> When updated to require()

What does your require statement look like? For the component tests, you should require `@playwright/experimental-ct-react` (or vue or svelte).
