### ISSUE TITLE
Where do the console.log test runner messages go when debug test from explorer in VSC?

### ISSUE THREAD

**Issue by danielvanmil** [microsoft/playwright#14372]
When I run a test from the test explorer in VSC my test runner log messages are viewed nicely in the console. When debugging a test they are not. Where do they go and how can I fix this?

**Comment by yury-s** [comment]
You can use [`context.cookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies), something like this:

```ts
test('cookies', async ({ page }) => {
  await page.goto('http://example.com');
  const cookies = await page.context().cookies();
  const cookie = cookies.find(c => c.name === 'expected_name');
  expect(cookie).toBeTruthy();
  expect(cookie.value).toBe('expected value');
});
```
