### ISSUE TITLE
[Question] locators selectors 

### ISSUE THREAD

**Issue by Nerijus123** [microsoft/playwright#14370]
Hello,
i have case where need to select row by name and click on icon near name. For e.x i try select row by text=Birute Basanaviciene and try click svg icon with attribut svg[data-icon="edit"] .  

![image](https://user-images.githubusercontent.com/29463426/169968374-43aa977a-3dd4-4d58-8788-1634d5e6cc2b.png)

Problem is they are both parents in html.

![image](https://user-images.githubusercontent.com/29463426/169969091-bf27c8d0-4ac3-4803-992c-9cb02eefa084.png)

![image](https://user-images.githubusercontent.com/29463426/169969438-0dc9ff41-3761-483a-a2cf-b3623f0c18f2.png)

I have tried several ways, but i'm not sure if i did everything right because I am newbie with playwright :) anyway thanks for help. 

![image](https://user-images.githubusercontent.com/29463426/169971879-46adcfc6-f0e1-4a46-87ab-460f5d4eb843.png)

**Comment by gauravgandhi1315** [comment]
@Nerijus123 Would you be able to share the website link? I can try on my side

**Comment by Nerijus123** [comment]
No sorry, its forbidden ip address and need account to log in. :/

**Comment by gauravgandhi1315** [comment]
OK, can you try the following and see if it works:

`[class='row align-items-center']:nth-child(4)`
`[class='col-md-2 d-none d-md-inline-block text-truncate'] [class='col-md d-none d-md-inline-block text-truncate']`

**Comment by yury-s** [comment]
Try something like this:

```js
    page.locator('div.row', {hasText: 'Birute Basanaviciene'}).first().locator('a[data-sta-id="link-screening"] > svg')
```

**Comment by Nerijus123** [comment]
This one actually works perfect, thank you very much 👍 💯

**Comment by Nerijus123** [comment]
> @Nerijus123 I thought you have to click on all the edit button starting from the first one correct? For the above solution, you have to write the separate locator for each one.

no no, i needed find a first row in the list with that name and click on edit button :)
