### ISSUE TITLE
[Question] Run one spec isolated

### ISSUE THREAD

**Issue by cunhabruno** [microsoft/playwright#14399]
Hello,

My Playwright tests have 2 projects. firefox and chrome, although, there is one spec that cannot be run at the same time in different browsers, is there a way to say to Playwright that one specific spec cannot be run in parallel in different projects?

**Comment by yury-s** [comment]
This is not currently possible but you can workaround it by doing something like this:


```js
async function testImpl(page) {
  // shared test code
}

test.describe('cr', () => {
  test.use({
    browserName: 'chromium'
  })
  test('the test', async ({ page }) => {
    testImpl(page);
  });
});

test.describe('wk', () => {
  test.use({
    browserName: 'webkit'
  })
  test('the test', async ({ page }) => {
    testImpl(page);
  });
});
```
and making sure that particular test file runs only in one project (with one of the browsers). Does it work for you?>

**Comment by yury-s** [comment]
Folding this into #14419
