### ISSUE TITLE
Getting Cookie Value using specified Cookie name?

### ISSUE THREAD

**Issue by isa3bel** [microsoft/playwright#14394]
Hello, I'm writing a test in Playwright, and I want to verify a cookie value. A user takes an action, which stores a cookie value. I want to use Playwright and TS to verify that the cookie was set properly. I want to check a specific cookie value, how can I do that using Playwright? Thanks

**Comment by yury-s** [comment]
You can use [`context.cookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies), something like this:

```ts
test('cookies', async ({ page }) => {
  await page.goto('http://example.com');
  const cookies = await page.context().cookies();
  const cookie = cookies.find(c => c.name === 'expected_name');
  expect(cookie).toBeTruthy();
  expect(cookie.value).toBe('expected value');
});
```

**Comment by isa3bel** [comment]
instead of doing page.goto and page.context() , could I do browser.newContext().cookies() instead? @yury-s

**Comment by isa3bel** [comment]
Does context.cookies() return an array? I'm getting an error that says .find isn't a function. Do I need to cast to an array first? @yury-s
