### ISSUE TITLE
[Feature] Extend expect() timeout after it started waiting

### ISSUE THREAD

**Issue by cassus** [microsoft/playwright#14408]
I'd like way to extend the [expect timeout](https://playwright.dev/docs/test-timeouts#expect-timeout) similarly to how I can extend the test timeout:
```ts
testInfo.setTimeout(testInfo.timeout + 30000)
```

#### Use case
I'm testing a rate limited backend and sometimes it gets overloaded. In that case my tests need to wait 10-20 seconds, sometimes up to 60 seconds before a backend requests can successfully be retried.
I don't want to extend all expect timeouts to 60+ seconds as that would make failure detection very slow.
But I can detect the backend rate limitation kicking in and in that case I already increase the test timeout. I'd like to do the same for the expect timeout.

#### This is the current function I use to extend the currently running test timeout
```ts
function tryToExtendPlaywrightTestTimeout(extendByMs: number) {
   test.info().setTimeout(testInfo.timeout + extendByMs)
   // would be nice to have a way to extend the timeout of the currently running expect(...) -- if one is running
}
```

**Comment by cassus** [comment]
For more context this is the router that I use to catch the rate limit, pause and retry the request and extend the test timeout

```ts
await context.route("**/graphql", async (route) => {
    const delayBetweenRetries = 2 * 1000
    const response = await pRetry(getResponse, {
      minTimeout: delayBetweenRetries,
      onFailedAttempt() {
        tryToExtendPlaywrightTestTimeout(delayBetweenRetries)
      },
    })
    assert(isDefined(response))

    route.fulfill({ response })

    async function getResponse(): Promise<APIResponse> {
      let maybeResponse
      try {
        maybeResponse = await context.request.fetch(route.request())
      } catch (e) {
        // stop retry for other than tenant-limit-exceeded errors
        if (isString(e) || isError(e)) throw new AbortError(e)
        throw new AbortError("unknown")
      }

      if (await ifLimitError(maybeResponse)) {
        console.warn("[BrowserContext] Backend limit exceeded, retrying")
        throw new Error("backend-limit-exceeded -> retry")
      }
      return maybeResponse
    }
  })
```

**Comment by yury-s** [comment]
Can you also share the code that uses `expect` triggering the route handler? Many assertions like [`toHaveURL`](https://playwright.dev/docs/next/test-assertions#page-assertions-to-have-url) already accept `timeout` option, can you simply pass a longer timeout to the specific `expect` call?

**Comment by cassus** [comment]
I use many different assertions. I could pass timeout to them individually, but I don't know in advance when will the test need an extra delay. That is only discovered in the `.route` callback when the backend returns the rate limit error. At that point the expect timeout has already started. I'd like to have a way to extend the expect timeout after it has began. This can be done with a test timeout.

One example is
```ts
test("THEN I see the test survey", async ({ page }) => {
    await expect(
      page.locator("text=[test data] Analytics fixture").first(),
    ).toBeVisible()
  })
```

**Comment by cassus** [comment]
It would work fine for success / Failure detection.
The only drawback is the lack of the the more accurate expect failure error messages. The test timeout error messages are less detailed, harder to debug.

Along these lines I think setting the expect timeout sufficiently high (30-60 seconds) will avoid most of the congestion issues and still give me a more helpful error message. Thanks for the inspiration @aslushnikov !
