### ISSUE TITLE
Error Uncaught frame.frameElement: Frame has been detached.

### ISSUE THREAD

**Issue by yatharth202030** [microsoft/playwright#14404]
Getting error with playwright as
 Uncaught frame.frameElement: Frame has been detached.
      at node_modules\codeceptjs\lib\helper\Playwright.js:2756:46

This error is occurred while trying to click an action button inside the iframe.

**Comment by yury-s** [comment]
This may happen if the page navigates and frame gets replaced while you are trying to perform the click. If the click itself triggers the navigation you may be able to workaround this by passing [noWaitAfter](https://playwright.dev/docs/next/api/class-locator#locator-click-option-no-wait-after) Please file a new issue with a reproducible example if you think there is a bug in playwright.
