### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DianeLamant** [microsoft/playwright#14400]
**Context:**
- Playwright Version: "1.22.0"
- Operating System: Pop!_OS
- Node.js version: v14.19.1
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

Hi, 

I can't run the webkit test, I had missing dependencies at first that I installed. 
![missing-dependencies](https://user-images.githubusercontent.com/49782204/170236524-cd2ddf6e-677e-4576-8523-c97f6d0ba188.png)

Now the error is with the libgtk-3.so.0: undefined symbol: atk_plug_set_child
![libgtk-3 so 0](https://user-images.githubusercontent.com/49782204/170236550-7e332ca2-00c9-4591-bc41-f4e86c5e3717.png)

I can't fix it, the solutions I found are link to snap but I'm not using it. 

Does someone know what can I do ? 

Thank you

**Comment by dimkin-eu** [comment]
there must be message, that only ubuntu is supported

**Comment by DianeLamant** [comment]
Only Ubuntu is supported for the test on webkit ?

**Comment by ltsuda** [comment]
The Playwright itself only supports Ubuntu 18.04/20.04 and 22.04 will be supported after the team finish testing.

**Comment by yury-s** [comment]
Only Ubuntu Linux distribution is [officially supported](https://playwright.dev/docs/next/library#linux) at the moment.
