### ISSUE TITLE
[Feature] Support backslash on command line for Windows

### ISSUE THREAD

**Issue by ghost** [microsoft/playwright#14402]
I would love for Playwright to support backslashes on the command line. This would make it so much easier to work with in a Microsoft Windows command prompt. For example, I have several nested folders in my playwright directory:
```
playwright\tests\group1\test1.spec.ts
playwright\tests\group2\test1.spec.ts
```
Typing on the command prompt using path completion yields something as simple as this:
```
playwright> yarn playwright test tests\group1\test1.spec.ts
```
To which playwright responds: `no tests found.` At which point I go back, switch all the backslashes to forward slashes to result in:
```
playwright> yarn playwright tests/group1/test1.spec.ts
```
And the test is found and run.

**Comment by pavelfeldman** [comment]
Or path filters are regular expressions, you would need to escape \ to become \\ for it to run.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
