### ISSUE TITLE
[Question] Need to make single test not run in parallel while running on multiple browsers

### ISSUE THREAD

**Issue by mnataraj17** [microsoft/playwright#14419]
Hi everyone, I have a test for profile data update, when I run  this test with all 3 browsers in github workflow, it’s failing because of not having expected values after the update. This is happening because, the profile data getting updated simultaneously in all 3 browsers so at the time of assertion in firefox browser, it’s getting the value updated through chromium browser test. How can I avoid this for this particular test when I am running on all 3 browsers.
Or else what’s the right way of running test on all 3 browsers in github workflow, should I add separate steps for each browser execution in github workflow?Thanks!

**Comment by yury-s** [comment]
This request is the same as https://github.com/microsoft/playwright/issues/14399, there is no ready solution at the moment.

> the profile data getting updated simultaneously in all 3 browsers so at the time of assertion in firefox browser, it’s getting the value updated through chromium browser test.

Can you isolate the profile by using different users (profiles) for each browser or it's not an option?

> Or else what’s the right way of running test on all 3 browsers in github workflow, should I add separate steps for each browser execution in github workflow?

This can be used as a workaround. An obvious downside is that you reduce parallelism of the tests in this case.

**Comment by yury-s** [comment]
Another solution would be to put the test into separate projects (one per browser) and make sure they never run in parallel

**Comment by aslushnikov** [comment]
I'll close this for now in favor of a workaround.

**Comment by richmar10** [comment]
Is there a way to combine html reports if we want to run isolated projects separately?
