### ISSUE TITLE
[Feature] mount options component testing

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#14416]
Will there be more mounting options available in the future like [vue-test-util's global options](https://test-utils.vuejs.org/api/#global)?

**Comment by pavelfeldman** [comment]
What capabilities are you interested in? Many of these are already possible suing existing APIs.

**Comment by sand4rt** [comment]
- stubs
- plugins
- provide/inject
- directives

**Comment by pavelfeldman** [comment]
These are not in the present scope of Vue, but we can consider them. Could you be more specific in how you intend to use those? I.e. what would be the use case for stubs, directives, etc?

**Comment by Onatcer** [comment]
Is there any way to use vue plugins in Component Testing with the current APIs? 

I was looking into setting up playwright with Vue 3 in a project that uses pinia (formerly vuex) and i18n which are provided to an Vue `App` instance before the component is mounted.

**Comment by sand4rt** [comment]
@pavelfeldman  I dont know how familiar you are with Vue, but Vue has a few ways to inject code into all components. This is usually done through first calling `createApp()` and then calling a function based on which type of injection you want do _(examples are [directives](https://vuejs.org/guide/reusability/custom-directives.html#custom-directives), [mixins](https://vuejs.org/api/options-composition.html#mixins), [plugins](https://vuejs.org/guide/reusability/plugins.html), [components](https://vuejs.org/api/application.html#app-component) & [provide & inject](https://vuejs.org/api/composition-api-dependency-injection.html))_. With other test libraries you can override those type of injections through the mount options on a test by test basis see docs:

- [plugins](https://test-utils.vuejs.org/api/#global-plugins)
- [provide/inject](https://test-utils.vuejs.org/guide/advanced/reusability-composition.html#provide-inject)
- [directives](https://test-utils.vuejs.org/api/#global-directives)
- [components](https://test-utils.vuejs.org/api/#global-components)
- [mixins](https://test-utils.vuejs.org/api/#global-mixins)

As of now i belive its only possible to define those injections globally trough `index.html` / `playwright/index.ts` and not on a test by test basis?

In addition, vue-test-utils provides adittional features that can also come in handy like [mocks](https://v1.test-utils.vuejs.org/api/options.html#mocks) an [stubs](https://test-utils.vuejs.org/guide/advanced/stubs-shallow-mount.html).

Not saying that you should but, if you are reusing the [MountOptions](https://test-utils.vuejs.org/api/#mount) from Vue test utils as much as possible, the migration from Vue test utils, Testing Library and Cypress to Playwright will become esier because the same interface is used.

**Comment by pavelfeldman** [comment]
> I dont know how familiar you are with Vue

Little-to-none

> With other test libraries you can override those type of injections through the mount options on a test by test basis

Passing those between the Node and the Browser contexts is going to be tricky. We can't pass live objects, only well-serializable JSON and alike.

> As of now i believe it's only possible to define those injections globally trough index.html / playwright/index.ts and not on a test by test basis?

I'm not even sure if you can configure those globally.

> In addition, vue-test-utils provides adittional features that can also come in handy like [mocks](https://v1.test-utils.vuejs.org/api/options.html#mocks) an [stubs](https://test-utils.vuejs.org/guide/advanced/stubs-shallow-mount.html).

Again, those suggest that you are running the tests in the same environment you render (Browser for Cypress and Node for JSDom). Our use case is a little different, we assume that components will run in the browser (to render) and tests will run in Node (to save files). So if you need to stub / mock, we assume you'll be creating ComponentForTest.vue that you'll be mounting in your test.

> the migration from Vue test utils, Testing Library and Cypress to Playwright and vice versa will become easier because the same interface is used

I still think there is a way to pass most of the MountOptions from your test into the mounting code in the browser, but that won't be the same MountOptions. For example, plugins would need to be picked and bundled at the test pre-process time, etc. That's why I was asking about the concrete use cases, to cover them one by one. We can aim at consistency with TL, but we are unlikely to achieve interoperability on the interface level.

**Comment by lmiller1990** [comment]
Hello, I work on the libraries in question (Test Utils, Testing Library, Cypress). Always good to see more solutions in the component testing space :100: 

I had a look at the code, Playwright does a simple mount, see here: https://github.com/microsoft/playwright/blob/214117c9c5f86daa7b24f79094b0fc33ca687023/packages/playwright-ct-vue/registerSource.mjs#L132-L137. Instead of just mounting the app, it would be possible to use the `mount` function from Vue Test Utils and the `attachTo: document.body` option to insert to component to the DOM, if Playwright wanted to get all the Test Utils API, including things like (Vue component specific) `stubs`, `plugins`, etc). 

Test Utils basically does what Playwright does here, with a bunch of extra things based on 5ish years of feature requests.

I'm not sure on the goals of Playwright w.r.t component testing, though; this kind of library specific API might not be in line with their philosophy around component testing, or the underlying model.

**Comment by pavelfeldman** [comment]
@lmiller1990 thanks for following up!

> Instead of just mounting the app, it would be possible to use the mount function from Vue Test Utils and the attachTo:

That's what I started with, and then eventually it evolved to what we are doing. Overall, using Vue Test Utils in Playwright would be great! However, as I explain above, wiring it to Playwright is not the same as wiring it to TL or Cypress. Our tests run in Node and our components run in the browser. You can't simply pass the plugins, directives, etc between the two. We could try figuring out something useful based on VTU.

> Test Utils basically does what Playwright does here, with a bunch of extra things based on 5ish years of feature requests.

It'd be awesome to reuse it and account for the 5 years of experience. So far I couldn't even make it handle component events, so I definitely need help :)

It feels like DM-ing (or even jumping on a VC) could be simpler, so if you are up for it, could you reach out to me on our [Slack](http://aka.ms/playwright-slack)? Or tell me where I can find you!

**Comment by Uninen** [comment]
I'm looking at converting Cypress component tests over to Playwright and this is basically what would be needed to use [Pinia](https://github.com/vuejs/pinia) in Vue component tests.

This is what the old mount looks like:

```js
  mount(HelloWorld, {
    propsData: {
      msg: 'Hello World',
    },
    global: {
      plugins: [
        createTestingPinia({
          createSpy: (args) => {
            console.log('spy', args)
            return () => {
              console.log('spyreturns')
            }
          },
        }),
      ],
    },
  })
```

The component mounting just fails if it uses Pinia and the test instance isn't created with `createTestingPinia`. Haven't found a workaround yet but if there is one, I'd be happy to know about it! :)

**Comment by lmiller1990** [comment]
> I'm looking at converting Cypress component tests over to Playwright and this is basically what would be needed to use [Pinia](https://github.com/vuejs/pinia) in Vue component tests.


I work on both Test Utils + Cypress - kind of curious if there's something lacking in Cypress Component Testing that made you move to Playwright, or just a personal preference?

Either way, happy to help out with either solution.

**Comment by Uninen** [comment]
Hi @lmiller1990. I've been a Cypress user for many years but I finally [gave up a few weeks ago](https://til.unessa.net/weeknotes/2022-18/) after a thousand paper cuts.

There are a handful of issues with Cypress that never have worked well for me, including multiple tab/windows support, websockets, drag & drop, and maybe most importantly flakiness in CI (both on GitHub and GitLab). Not being able to trust the CI pipelines is a big issue for me and it has  slowly gotten worse with every single release during past 18 months or so. Playwright is super stable and also much lighter and I can run the same tests with 3 different browsers in less time than one test run with Cypress. It does lack features like coverage reporting but being a stable tool far outweighs any fancy features for this kind of tool.

Lastly, Cypress 10 breaks the old json-based configuration which forces me to change the configuration in literally all the repos that we're using it in. I'm now spending 30 minutes more on each of those and configuring them to use Playwright instead.

I do hope all the best for the Cypress team, and I hope the focus gets back to the core product and important basic features so it will stay relevant and continue to give Playwright and others run for their money.

**Comment by lmiller1990** [comment]
Cool, thank for the feedback! I agree Playwright gets some things really right,  cross browser for instance (I hope Cypress can have Safari support one day... although I feel like we Safari users are a dying breed).

My personal goal is to move component testing forward, and better tools for the web in general, so I'll help where I can at the intersection of Playwright x Vue 👍 better integration between runners and frameworks benefits everyone.

**Comment by pavelfeldman** [comment]
> Otherwise i can do my best to specify some use cases?

This would be best!

**Comment by sand4rt** [comment]
Thanks for your reply! Okay, i'll create separate issues for the use cases and associate them with this issue when i find the time _(if anyone can help that would be great!)_. I believe that the plugin mount option is the one that people need the most so created a [ticket](https://github.com/microsoft/playwright/issues/15472) for that.

**Comment by sand4rt** [comment]
@pavelfeldman I closed this ticket because everything can now be done via the mount hooks.
