### ISSUE TITLE
await locator().focus() does not work without additional waitForTimeout

### ISSUE THREAD

**Issue by einarpersson** [microsoft/playwright#14422]
**Context:**
- Playwright Version: `1.22.2`
- Operating System: Ubuntu under Windows 10, WSL2
- Node.js version: 16.13.1
- Browser: Chromium
- Extra: Sveltekit 1.0.0-next.345

I have a slider in Svelte and I've written at test that verifies that I can focus it, and move it with my keyboard with expected result
![image](https://user-images.githubusercontent.com/6043691/170463317-860dfcd4-6e25-4982-aae4-df68b2790244.png)
![image](https://user-images.githubusercontent.com/6043691/170463462-61fd240d-3d14-4453-b5aa-ae43bb0d1313.png)

**Code Snippet**

```javascript
 test('should be able to move slider for Inrikes transporter', async ({ page }) => {
    await page.goto('/nyköping/scenarios')

    const sliderWrapper = page.locator('.wrapper:has-text("Inrikes transporter")')

    await sliderWrapper.locator('input').focus()
    // await page.waitForTimeout(100) // WITHOUT THIS LINE THE TEST FAILS

    await page.keyboard.press('ArrowLeft')
    await page.keyboard.press('ArrowLeft')
    await page.keyboard.press('ArrowLeft')
    await page.keyboard.press('ArrowLeft')
    await page.keyboard.press('ArrowLeft')
    await page.keyboard.press('ArrowLeft')

    expect(await sliderWrapper.textContent()).toContain('-6 %')
  })
```

**Describe the bug**
```
Expected substring: "-6 %"
Received string:    " Inrikes transporter  0 % "
```

Since I am awaiting the `locator().focus()` I thought it would be enough. But it seems to be the case, at least in this situation, that I need to manually wait for an timeout. Is this expected or something weird going on?

It works fine with the `waitForTimeout` but without it, it fails or is at least flaky.

**Comment by yury-s** [comment]
The `input` element is not ready yet to handle the keyboard events by the time playwright decides that it is [actionable](https://playwright.dev/docs/next/actionability) and focuses it. This may happen if the (js) event handlers are added after the element appears in the dom. This is an issue that would affect a human user too so should be considered a bug. Right way to fix it would be to make sure the element cannot be focused until it has all the event handlers ready.

As a workaround better than `waitForTimeout` you should be able to programmatically wait for the listeners to be ready before sending keyboard events, e.g. by evaluating some condition with [waitForFunction](https://playwright.dev/docs/next/api/class-page#page-wait-for-function). The condition would be specific to the logic of your application, there is no universal solution. Does it make sense?
