### ISSUE TITLE
[BUG] Cannot import TypeScript files from test spec written in TypeScript

### ISSUE THREAD

**Issue by ivpdev** [microsoft/playwright#14427]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac 
- Node.js version: 16.14.0
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { setupDfAccount } from './df_setup'
```

**Describe the bug**

When I'm trying to import a TypeScript file from test spec (also written in TypeScript), I'm getting an error 'Error: tests/smoke_test.spec.ts: JavaScript files must end with .mjs to use import.'

**Comment by yury-s** [comment]
Can you share the project / full repro where you see this error?

**Comment by ivpdev** [comment]
@yury-s Unfortunately I cannot share full repo, since it's a commercial product. But while I was trying to make an excerpt from the project for you, I found that one of the ts modules imported into the test includes an import of a js file.
That explains the error. 

I would still prefer being able to have js imports in ts files not only in mjs. But that's rather feature request, not a bug.

**Comment by pavelfeldman** [comment]
Importing js file just works, as long as you are not trying to import an ESM module into CJS. If you convert your package into ESM module, you'll be able to import other ESM modules.

https://www.typescriptlang.org/docs/handbook/esm-node.html
