### ISSUE TITLE
[Question] A buffer object is incorrectly serialized when passing it into the page.evaluateHandle? 

### ISSUE THREAD

**Issue by Itsamna** [microsoft/playwright#14420]
**Context:**
- Playwright Version: 1.21
- Operating System: Windows
- Node.js version: v14.18.2
- Browser: Chrome
- Typescript

I  use the following code to emulate a file dropping from the file system to a page (taken from [here](https://charliedigital.com/2021/12/20/simulate-drag-and-drop-of-files-with-playwright/)):

```javascript
let fileBuffer = await fs.readFileSync(itemFilePath)

const dataTransfer = await buildTabPage.page.evaluateHandle((fileBuffer) => {
    const dt = new DataTransfer();

    console.log(JSON.stringify(fileBuffer))

   const file = new File([fileBuffer.toString('hex')], '140185A.zip', { type: 'application/octet-stream' });
   dt.items.add(file);
   return dt ;
}, fileBuffer);

await buildTabPage.page.dispatchEvent('.file-dropzone', 'drop', { dataTransfer });
```

The code itself works: the drop event is triggered and I see the file coming to the backend.
It reads a file to a buffer, passes the buffer into the `page.evaluateHandle` function, and creates a file object there based on the buffer.

If I call the `fileBuffer.toString('hex')` on an initial buffer before passing it to the function, the output is a correct string.

But inside the `evaluateHandle` function `fileBuffer.toString('hex')` leads to the `[object Object]` output, making the file to be corrupted.

As far as I see, the buffer is serialized to some other format before being passed there: 

Before serialization (correct):
![image](https://user-images.githubusercontent.com/15904382/170449736-4009da40-66fd-4574-a901-313329a3d194.png)

After:
![image](https://user-images.githubusercontent.com/15904382/170449828-eb789a24-48c5-4df3-8a69-43298811c99a.png)

Is this really expected that each buffer chain item is converted from just being a number to the following:

```javascript
{
    k: '0', 
    v: {
        n: 80
    }
}
```

If so, could you suggest how to properly turn it back to the buffer inside the `page.evaluateHandle` context?

**Comment by yury-s** [comment]
Only [`serializable`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#description) arguments and handles are supported by playwright as described in [the docs](https://playwright.dev/docs/next/evaluating#evaluation-argument). `Buffer` is serialized as a regular object and is parsed into a regular object in the page (this is why you get `[object Object]` when calling toString on it). To pass the buffer you can serialize it to a hex string in the node:

```js
let fileBuffer = await fs.readFileSync(itemFilePath)

const dataTransfer = await buildTabPage.page.evaluateHandle((fileBuffer) => {
    const dt = new DataTransfer();

    console.log(JSON.stringify(fileBuffer))

   const file = new File([fileBuffer], '140185A.zip', { type: 'application/octet-stream' });
   dt.items.add(file);
   return dt ;
}, fileBuffer.toString('hex'));

await buildTabPage.page.dispatchEvent('.file-dropzone', 'drop', { dataTransfer });
```
