### ISSUE TITLE
If Automation Test == z_W2M == May26,2022 == Pending ==  Self-- then click on 4th row.. how can i achive that.(plz refer the attached screenshots)

### ISSUE THREAD

**Issue by biswasritu66** [microsoft/playwright#14437]
![Screenshot (312)](https://user-images.githubusercontent.com/94857457/170625952-817448c9-891a-4498-8a8c-fa483de6d0e5.png)

If 4th row(Automation Test) contains (z_W2M, May26,2022, Pending, Self)-- then click on 4th row.. how can i achive that.(plz refer the attached screenshots)

or

If Automation Test == z_W2M == May26,2022 == Pending ==  Self-- then click on 4th row.. how can i achive that.(plz refer the attached screenshots)

or

If Automation test contains "pending" text  then click on pending,

**Comment by yury-s** [comment]
You can specify [hasText](https://playwright.dev/docs/next/api/class-page#page-locator-option-has-text) option to narrow down elements by text, so something like this should work:

```js
page.locator('div.ant-card-body', {hasText: 'z_W2M'}).nth(3).locator('div', {hasText: 'PENDING'});
```

You can also use [codegen](https://playwright.dev/docs/next/codegen), it will help you pick a selector automatically.
