### ISSUE TITLE
[BUG] [Soft Assertions] Error: toBeEmpty can be only used with Locator object

### ISSUE THREAD

**Issue by fertavora** [microsoft/playwright#14439]
**Context:**
- Playwright Version: 1.22.1
- Operating System: Ubuntu 20.04 (Windows 11 WSL)
- Node.js version: 16.15.0
- Browser: Chromium
- Extra: [Soft Assertions Documentation](https://playwright.dev/docs/test-assertions#soft-assertions)

**Code Snippet**

```javascript
await expect.soft(projectPage.welcomeMessage, 'Welcome message does not match expected!').toHaveText(EXPECTED_WELCOME_MESSAGE);
await expect.soft(projectPage.buttonAgreeWelcome, 'Agree Welcome button is not enabled!').toBeEnabled();
expect(test.info().errors).toBeEmpty();
```

**Bug Description**

When implementing soft assertions, I followed the instructions in the documentation:
`expect(test.info().errors).toBeEmpty();`

But when running test, I got this error:
```
Error: toBeEmpty can be only used with Locator object

      74 |     await expect.soft(projectPage.welcomeMessage, 'Welcome message does not match expected!').toHaveText(EXPECTED_WELCOME_MESSAGE);
      75 |     await expect.soft(projectPage.buttonAgreeWelcome, 'Agree Welcome button is not enabled!').toBeEnabled();
    > 76 |     expect(test.info().errors).toBeEmpty();
         |                                ^
      77 |   });
```

**Comment by ltsuda** [comment]
Do you think `.toHaveLength(number)` from https://jestjs.io/docs/expect#tohavelengthnumber works for you?

`.toBeEmpty()` is part of the Web first assertions, so this only works for Locators. See https://playwright.dev/docs/release-notes#-web-first-assertions for more details.

**Comment by fertavora** [comment]
The thing is that the documenation suggest to use `toBeEmpty`.
If it is for locators only, documentation should be updated with a working example.

![image](https://user-images.githubusercontent.com/10965973/170692738-90031ff7-7201-41a8-967a-83c4f6c7fd71.png)

**Comment by ltsuda** [comment]
Huum. That might be a mistake, let's wait for someone from the team to confirm that.

**Comment by yury-s** [comment]
It's a typo in the docs, it should have been:
```js
expect(test.info().errors).toBeEmpty();
```
I'll update the docs.
