### ISSUE TITLE
[Question] Speed up installing browsers in GitHub Actions

### ISSUE THREAD

**Issue by axelson** [microsoft/playwright#14434]
Is it possible to speed up installation of browsers in GitHub Actions?

I just had a run where it took 40 minutes for `playwright install --with-deps` to finish on `ubuntu-latest` in a hosted GitHub Actions runner. Is there something that can be done to speed this up? Even when it's not unbearably slow it still takes about 55 seconds which is really slow.

It looks like the official GitHub Actions for Playwright are at least sometimes around 55 seconds as well:
https://github.com/microsoft/playwright/runs/6617763313?check_suite_focus=true

**Comment by pavelfeldman** [comment]
How long do your tests run? You could use channel: chrome if you are running on Chrome only, in that case you can skip browser installation.

**Comment by axelson** [comment]
The tests themselves take about 3 minutes right now. When the Playwright installation is fast the entire suite runs in about 6 minutes.

I'll look into using the stable chrome channel:
https://playwright.dev/docs/browsers#google-chrome--microsoft-edge

Although we want to test on Firefox as well so unfortunately I won't be able to rely on only that for a speedup.

**Comment by pavelfeldman** [comment]
Got it. Browser installation should be pretty fast - often it does not even make sense to cache them. GHA is supposed to pull them from Azure extremely fast. Same goes to dependencies - I'm sure there is an instant apt mirror available to them. So I wonder what's happening with the several minutes delay, probably an outage. 1 minute does not sound great, but my hesitation is that no matter what we do, installing browsers will be taking some time. Even our docker container, when used, pulling and starting it has some cost.

**Comment by peterbe** [comment]
I too suffered this. Not only did it take an age, it timed out too sometimes. Thanks for the tip about using the stable chrome channel. 
Now my GItHub Action looks like this:

```yaml
      # If you're NOT going to use `--project="Google Chrome"` when running
      # the Playwright tests, uncomment these lines. They're very slow
      # - name: Install Playwright Browsers
      #   run: pnpm dlx playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm dlx playwright test --project="Google Chrome"
```

And my `playwright.config.js` looks like this:

```js
...

  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },

    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },

    {
      name: "webkit",
      use: {
        ...devices["Desktop Safari"],
      },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    {
      name: "Mobile Safari",
      use: {
        ...devices["iPhone 12"],
      },
    },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge',
    //   },
    // },
    {
      name: "Google Chrome",
      use: {
        channel: "chrome",
      },
    },
  ],

...
```

So in GitHub Actions, I'm currently OK with it only testing with `chrome` but on my laptop, when I do `pnpm dlx playwright test` (after `pnpm dlx playwright install` once) then it tests all different browsers. 

Nota bene; this makes sense for me on a side-project but I wish still it was easier/faster to get those dependencies installed.

**Comment by karlhorky** [comment]
We have seen this commonly too, taking many minutes to install the Playwright browsers.

In our experience, we have seen this caused by the `man-db` triggers which are run and take a long time:

```bash
pnpm playwright install --with-deps chrome
  
Installing dependencies...
Switching to root user to install dependencies...
...
Processing triggers for man-db (2.12.0-4build2) ... # 💥 Hangs for a long time
```

Maybe it's a problem with running it on GitHub Actions runners:

- https://github.com/actions/runner/issues/4030

@aslushnikov considering that this is still an active issue, could you reopen the issue?

**Comment by karlhorky** [comment]
## Workaround

After a few test runs, it appears that uninstalling `man-db` helps reduce the run time of the GitHub Actions workflow:

```diff
       - name: Install Playwright browsers
         run: |
-          pnpm playwright install --with-deps chrome
+          # Avoid long delays on the "Processing triggers for man-db"
+          # step during installation
+          #
+          # ```
+          # pnpm playwright install --with-deps chrome
+          # Installing dependencies...
+          # Switching to root user to install dependencies...
+          # ...
+          # Processing triggers for man-db (2.12.0-4build2) ...
+          # ```
+          #
+          # - https://github.com/actions/runner/issues/4030
+          # - https://github.com/microsoft/playwright/issues/14434
+          sudo apt-get --yes remove --purge man-db
+
+          pnpm playwright install --with-deps chrome
```
