### ISSUE TITLE
[Question] Run tests on specific chrome version

### ISSUE THREAD

**Issue by AAAstorga** [microsoft/playwright#14435]
Hello,

We use Playwright to test against Chrome and Safari. We use the real Chrome version since we need media codec support etc. 

Is there anyway to have Playwright use a specific version of Chrome for a set of tests? Our site runs on hardware that is version locked to Chrome M85 and we want to make sure we run our tests against that version since that is a browser version required for an endpoint we ship on. 

If this is possible, how would one do this? 

We want to be able to run the tests on the latest Chrome (which we do now) but also against a specific version of Chrome. 

Thank you!

**Comment by pavelfeldman** [comment]
You can only use Chrome Stable, Beta or Chromium. Chrome M85 is 2 years old, Playwright won't run against the browser that old.

**Comment by Bessonov** [comment]
Although the information that 85 is too old is helpful (btw why?), this isn't the answer for more control of used versions. For one of the projects we have same requirement - supporting a minimal browser version.

**Comment by aslushnikov** [comment]
> Would it be possible?

Unfortunately, it wouldn't: Playwright relies heavily on exact remote debugging protocol versions, so there's no guarantee other browser versions will work with a particular Playwright version.

**Comment by terryzfeng** [comment]
Even if it's not guaranteed, specifying a custom executable path is available for the playwright library, however not playwright-test. Is it also implement this as a field for playwright-test?

https://playwright.dev/docs/api/class-browsertype#browser-type-executable-path

**Comment by udarrr** [comment]
> > Would it be possible?
> 
> Unfortunately, it wouldn't: Playwright relies heavily on exact remote debugging protocol versions, so there's no guarantee other browser versions will work with a particular Playwright version.

Is it the similar for connectOverCDP connection to debugger port? Should it be used with playwright that comply with debugging protocol versions? For example there is chrome v118 instance
