### ISSUE TITLE
[BUG] source code lines in trace viewer aren't aligned if using esm

### ISSUE THREAD

**Issue by Bessonov** [microsoft/playwright#14459]
**Context:**
- Playwright Version: 1.22.2, but tried also 1.23.0-alpha-may-28-2022
- Operating System: ubuntu 20.04
- Node.js version: v16.14.0
- Browser: chromium, but probably all browsers
- Extra: using esm

## System:
 - OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 3.11 GB / 7.66 GB
 - Container: Yes
## Binaries:
 - Node: 16.14.0 - ~/.nvm/versions/node/v16.14.0/bin/node
 - Yarn: 1.22.15 - ~/.nvm/versions/node/v16.14.0/bin/yarn
 - npm: 8.3.1 - ~/.nvm/versions/node/v16.14.0/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**
Nothing special, see https://github.com/Bessonov/playwright-14459 and the second commit with switch to esm.

**Describe the bug**

There is no relation between steps and source code:
![Screenshot from 2022-05-28 13-23-44](https://user-images.githubusercontent.com/182451/170823369-523f1bab-61c1-42c0-aa08-9a00bdca5268.png)

**Comment by yury-s** [comment]
> Nothing special, see https://github.com/Bessonov/playwright-14459 and the second commit with switch to esm.

I tried your example and got this:

```
Error: playwright.config.ts: Cannot import a typescript file from an esmodule.
================================================================================
Make sure that:
  - you are using Node.js 16+,
  - your package.json contains "type": "module",
  - you are using TypeScript for playwright.config.ts.
================================================================================

    at errorWithFile (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/util.js:217:10)
    at Loader._requireOrImport (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/loader.js:286:39)
    at Loader._requireOrImportDefaultObject (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/loader.js:308:18)
    at Loader.loadConfigFile (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/loader.js:79:20)
    at Runner.loadConfigFromResolvedFile (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/runner.js:96:12)
    at runTests (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/cli.js:153:27)
    at Ai.<anonymous> (/Users/yurys/sandbox/playwright-14459/node_modules/@playwright/test/lib/cli.js:70:7)
```

**Comment by Bessonov** [comment]
@yury-s this example was created with `npm init playwright@latest new-project` and only the second commit were made by me. I cloned it from scratch again and didn't get your error. Is there any example on how to run pw inside docker, so we ensure that you didn't ran in an environmental problem?

**Comment by Bessonov** [comment]
@yury-s I've added new commit with docker environment. Just checkout and run:
```bash
npm start
npm run trace
```

**Comment by Bessonov** [comment]
@yury-s does it work for you? It seems like lines are already incorrect in the `trace.trace` file. Is there any pointer in source where I can look at this issue? I see that [stack-trace](https://www.npmjs.com/package/stack-trace) is used. I'm not sure, but it could be related.

**Comment by Bessonov** [comment]
@pavelfeldman thank you very much for your amazing work! I was able to test it with `1.23.0-alpha-jun-20-2022` and it worked!
