### ISSUE TITLE
[Question] ScrollIntoView on a particular Locator

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#14457]
While we were testing our application, we noticed that some locators that were present in the DOM were not visible in the viewport. As a result we had to scroll to that element and execute commands appropriately. There is no direct _scrollIntoView()_ method available in playwright and we had to use a combination of evaluate + JS scrollIntoView() as a workaround. Is this advisable? is there a better way to perform this operation please?

**Comment by ltsuda** [comment]
Is this help?
https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed

**Comment by yury-s** [comment]
Please use [locator.scrollIntoViewIfNeeded](https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed), if it doesn't work for some reason (say actionability condition is not met), you can do it in js as you described by calling [locator.evaluate](https://playwright.dev/docs/api/class-locator#locator-evaluate)
