### ISSUE TITLE
[Question] How to ensure onTestEnd(test, result) completes after the very last test

### ISSUE THREAD

**Issue by kbowles393** [microsoft/playwright#14452]
Hi,

I am writing my own custom reporter (where test results are logged in a google sheet using the google sheets api) and am running into an issue where the very last test is not reported when using onTestEnd(test, result). Here is my code:

class MyReporter {
    onBegin(config, suite) {
        console.log(`Starting the run with ${suite.allTests().length} tests`);
    }

    onTestBegin(test) {
        console.log(`Starting test ${test.title}`);
    }

    async onTestEnd(test, result) {
        const auth = new google.auth.GoogleAuth({
            keyFile: "credentials.json",
            scopes: "https://www.googleapis.com/auth/spreadsheets",
        });
    
        // create client instance for auth
        const client = await auth.getClient();
    
        // create an instance of google sheets api
        const googleSheets = google.sheets({ version: "v4", auth: client });
    
        const spreadsheetId = "ID";
    
        // append the test results to the spreadsheet
        await googleSheets.spreadsheets.values.append({
            auth,
            spreadsheetId,
            range: "Sheet1!A:B",
            valueInputOption: "RAW",
            resource: {
                values: [[`${result.status}`]],
            },
        });
        
        console.log(`ending test`);
    }

    onEnd(result) {
        console.log(`Finished the run: ${result.status}`);
    }
}

In addition to the google sheet not displaying the final result, the console looks like this:
Starting the run with 5 tests
Starting test test1
Starting test test2
ending test
ending test
Starting test test3
Starting test test4
ending test
Starting test test5
ending test
Finished the run: failed
(note: two of the tests are designed to fail, so the run status of "failed" is appropriate)

I believe that when all tests end, playwright stops trying to append the final results to the spreadsheet and thus the reporter does not function properly. All other test results are added as expected. Is there a way to ensure the test runner adds all results before it closes? 
Thanks!

**Comment by pavelfeldman** [comment]
`onTestEnd` is not async, Playwright won't be waiting for it. As a workaround, you can wait in `onEnd` though, which is async. So you can create promises in onTestEnd, put them into array and await Promise.all() in onEnd.

**Comment by kbowles393** [comment]
Got it - thanks! I'm trying to implement that but running into another issue: 
class MyReporter {
    onBegin(config, suite) {
        console.log(`Starting the run with ${suite.allTests().length} tests`);
    }

    onTestBegin(test) {
        console.log(`Starting test ${test.title}`);
    }

    // initialize an array of promises that will be resolved later
    testResults = [];


    onTestEnd(test, result) {
        const myPromise = writeResults(test, result);
        testResults.push(myPromise);
    }

    onEnd(result) {
        Promise.all(testResults);
        console.log(`Finished the run: ${result.status}`);
    }
}
(note: writeResults(test, result) is a function that does the writing to the google sheets api)

when I try and run this, it tells me that testResults is not defined. To define it, I believe I would have to modify the constructor for the MyReporter class, is there a way I can do that?

Thanks again!

**Comment by viraxslot** [comment]
@pavelfeldman hi, here is a similar request from my team: https://github.com/microsoft/playwright/issues/13704
And I know that in pw telegram chat there was another request for this feature. Is there any possibility to implement it? It would be really helpful.

**Comment by aslushnikov** [comment]
@kbowles393 you just need to initialize array outside of the class:

```js
// initialize an array of promises that will be resolved later
const testResults = [];

class MyReporter {
    onBegin(config, suite) {
        console.log(`Starting the run with ${suite.allTests().length} tests`);
    }

    onTestBegin(test) {
        console.log(`Starting test ${test.title}`);
    }


    onTestEnd(test, result) {
        const myPromise = writeResults(test, result);
        testResults.push(myPromise);
    }

    onEnd(result) {
        Promise.all(testResults);
        console.log(`Finished the run: ${result.status}`);
    }
}
```

> Is there any possibility to implement it? It would be really helpful.

@viraxslot so far we guide everybody to use the workaround posted here; no plans to change this anytime soon.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by viraxslot** [comment]
@pavelfeldman well, our request was closed with the same workaround. It's a pity you don't plan to add this functionality. I just wanted to emphasize there are several requests for this feature.

**Comment by gajus** [comment]
This feels very convoluted. Can we reconsider this? @aslushnikov 

At the very least... (though not ideal) Playwright should check the result of `onTestEnd`, and if it is a Promise, then throw an error.

We were treating `onTestEnd` as if it is async-capable, and realized we were missing a ton of errors.
