### ISSUE TITLE
[BUG] webkit browser not recognized on MacOS system  Monterey with Apple M1 silicon

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#14454]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.15
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: MacOS Monterey 12.3

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {test, expect, firefox, chromium, webkit} = require('@playwright/test');

test.only('Test', async ({}) => {
    const browser = await webkit.launch();
    const context = await browser.newContext({viewport: {width: 1500, height: 900}}); // Btowser context with capabilities
    const page = await context.newPage(); // New fresh page of browser

    await page.goto('https://www.saucedemo.com/');

    await page.waitForTimeout(2000);
```

**Describe the bug**

While an attempt to run a basic test with WebKit browser I get the error:

![async-await spec js — playwright-basic-project 2022-05-28 at 12 19 12 AM](https://user-images.githubusercontent.com/52656401/170790751-8feb9897-d0f7-4748-87b4-4b4800d0a883.jpg)

The same scenario works as well with other browsers. 

My section of 'About my Mac':

![About This Mac 2022-05-28 at 12 17 22 AM](https://user-images.githubusercontent.com/52656401/170790576-380dec21-6f30-46ba-8610-23a5d13debbe.jpg)

**Comment by yury-s** [comment]
I cannot reproduce it. Can you share your project?

**Comment by AlexKomanov** [comment]
@yury-s 
I cannot too. Maybe I just forgot to save the file as well.
Thanks, I'm closing.
In case of some new issue with this one - I'll open a new bug.
