### ISSUE TITLE
[BUG] Different screenshot quality with and without plugged power source

### ISSUE THREAD

**Issue by Kreeg** [microsoft/playwright#14460]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.3.0
- Browser: Chromium
- Extra: Macbook M1 13"

**Code Snippet**

```javascript
const { chromium } = require('playwright-chromium');

(async () => {
  const context = await browser.newContext();
  page = await context.newPage();
  const width = 1280;
  const height = 1024;
  const previewImagePath = `${HTMLPath}.png`;

  await page.setViewportSize({ width, height });

  await page.goto(`file://${HTMLPath}`);
  await page.screenshot({
      omitBackground: true,
      path: previewImagePath,
      type: 'png',
      clip: { x: 0, y: 0, width, height }
  });
})();
```

I provided HTML and all the other files [here](https://drive.google.com/file/d/1UfjSYmKEhGAvVVVw4YE5GECTqta_DYvY/view?usp=sharing) 

**Describe the bug**

1. Plug the power source
2. Save screenshot
3. Unplug the power source.
4. Save screenshot
5. Consider the difference

Screenshot with the unplugged power source 
File size **24.9 KB (25507 bytes)**
![изображение](https://user-images.githubusercontent.com/1666622/170828325-565777d1-12a6-4eb3-a007-8b793c688240.png)

Screenshot with the plugged power source
File size  **24.7 KB (25340 bytes)** 
![css vertical centered html](https://user-images.githubusercontent.com/1666622/170828392-b3dbc505-b532-41d8-a2dd-66b5ca064792.png)

I faced this bug before with the `puppeteer`, you can check the opened issue [here](https://github.com/puppeteer/puppeteer/issues/8009). Then we moved from `puppeteer` to `playwright` in `svg-sprite` package for [more stable tests](https://github.com/svg-sprite/svg-sprite/pull/610). But now we're facing the same problem with the 1.22.2 version. This bug does not appear  in version 1.21.1. The code above is from the current [tests](https://github.com/svg-sprite/svg-sprite/blob/main/test/jest/setup.js#L38).

**Comment by pavelfeldman** [comment]
Could this be because when you switch to power source, a more powerful GPU is being used? That is what MacBook Pros do.

**Comment by Kreeg** [comment]
@pavelfeldman hello! Thanks for the suggestion, I'll try tonight. But if this is the case then why this changes is appeared in 1.22.0 version? There is no such behavior in version 1.21.1. And there is no any references for this in patch notes

**Comment by Kreeg** [comment]
Okay. This is the weird one. Currently I am using an external display, connected with the hub with power delivery. So when I disconnect my hub, the power source is disconnected too. So I thought that the problem is in the disconnected power source. Now I tried to disconnect only the power source from the hub, and... everything worked. Then I tried to disconnect only the external display from the hub, and the tests failed. Then I tried to connect only the power source to notebook, and again, tests failed.
So this problem exists on the same device only when I disconnect the external monitor. 

External data (this may help):
1. macOS Monterey 12.4
2. MacBook Pro (13-inch, M1, 2020)
3. 16 GB RAM
4. Display 1: Built-in Retina Display 13,3-inch (2560 × 1600)
5. Display 2: BenQ PD2700Q LCD Display 27-inch (2560 × 1440)

@pavelfeldman I've tried to launch chromium with `--disable-gpu` args. The results are the same.

**Comment by aslushnikov** [comment]
@Kreeg  Overall, we are aware that browsers / operating systems render things differently depending on the monitors attached. And unfortunately, we can't help with this: this is how things work! 

However, this is unlikely to change with the last release. Are you sure that v1.21 doesn't exhibit this behavior, while 1.22 does?

**Comment by aslushnikov** [comment]
> Can this relates to the updated version of Chromium?

Most likely this is the case. Chromium is a very lively project with lots of stuff going on.
To validate this hypothesis, you can:
- install Playwright 1.22 and Playwright 1.21 on the machine (in separate folders)
- get [`chromium.executablePath()`](https://playwright.dev/docs/api/class-browsertype#browser-type-executable-path) of the both chromiums that we ship with Playwright 1.22 and Playwright 1.21
- run Playwright 1.22 with the Chromium from Playwright 1.21, using the `executablePath` option of the [`chromium.launch()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch) option

If Playwright 1.22 with the old browser works, then this is some change that happened in Chromium. If not, then something has changed in Playwright! (and I'll be curious to see what)

**Comment by Kreeg** [comment]
@aslushnikov thank you! I'll try this within 2 weeks.

**Comment by pavelfeldman** [comment]
We keep non-actionable issues closed to maintain the repo in a healthy state. Please file a new issue and link this one once you get back to it!
