### ISSUE TITLE
[BUG] Two files run when names are similar

### ISSUE THREAD

**Issue by oytunerdd** [microsoft/playwright#14462]
**Context:**

Two spec files with similar head or the tail of the name, when the shorter one is triggered both files run and two browser open.

For example 
**Cutover_For_Exited_With_Different_Beneficiary_Reentered.spec**
**Cutover_For_Exited_With_Different_Beneficiary.spec**

Let's assume these files exist in our suite, when triggered by using the shorter named file two of the spec files get triggered, with no relation to the length of the file names;

` npx playwright test Scenario_One_Test_Case_One_Cutover_For_Exited_With_Different_Beneficiary --project=dev `

two different browsers open 

- Playwright Version: [1.21]
- Operating System: [Windows,]
- Node.js version: [16.14.0]
- Browser: [Chromium]

**Comment by pavelfeldman** [comment]
This looks right to me, what are your expectations?

**Comment by oytunerdd** [comment]
> This looks right to me, what are your expectations?

Well the first file end with Reentered so the names of the files are different. Do you really think the command should run both files ?

**Comment by Basti098765** [comment]
If you want to run just the short file you can add the .spec at the end, otherwise both files match your command.

**Comment by oytunerdd** [comment]
For example in the case where the file names are ;
Cutover_For_Exited.spec
For_Exited.spec

and the command to run is ;
npx playwright test For_Exited.spec --project=dev --headed

yet again two files get triggered.

**Comment by oytunerdd** [comment]
> @oytunerdd probably, you are interested in `-g` flag:
> 
> ```
>   -g, --grep <grep>            Only run tests matching this regular expression (default: ".*")
> ```
> 
> Something like `npx playwright test -g "^For_Exited\..*" --project=dev --headed` could work.

Neither of the -g or --grep works

**Comment by aslushnikov** [comment]
@oytunerdd the way filtering works is by checking if the filter word is contained in the file name. This is intended behavior; consider the following spec files:

```
click-header.spec.ts
click-footer.spec.ts
hover-header.spec.ts
hover-footer.spec.ts
```

with the filtering logic, you can do the following:

```bash
# run all the footer tests
$ npx playwright test footer
# run all click tests
$ npx playwright test click
```

To run a specific file only, make sure to specify the unique-enough file name:

```bash
# run only click footer tests
$ npx playwright test click-footer
```

**Comment by Bessonov** [comment]
@oytunerdd 
> Neither of the -g or --grep work

Probably, you aren't interested in a solution, if you don't even mind telling us what did you tried and what you have got.

**Comment by oytunerdd** [comment]
I actually tried and prepared a sample on my local also applied the suggested answers with them. But for using it as a filter rather than exact and unique file names rather a new feature since there is no tag for running targeted test files. (Eg. --project=smt)
As stated on previous quote, names should be in unique enough context.
And since the case closed, can be accepted. Yet in general to other programming languages it is not.

**Comment by oytunerdd** [comment]
@Bessonov  i found how to properly use this i guess it requires the file path as well /samples/my-spec.spec.ts 

and in the case where there is /samples/my-spec-2.spec.ts under the project it only works one file this way
