### ISSUE TITLE
[Question] Intellisense (auto completion) doesn't work with beforeEach when using POM

### ISSUE THREAD

**Issue by sam-022** [microsoft/playwright#14464]
I am trying to use Page Object Model with `@playwright/test` using `JavaScript` but seems like when you initialize a page in `beforeEach`, the auto-completion (intellisense) stops working.

**Example:**
```
const { test, expect } = require('@playwright/test');
const HomePage = require('../pages/home.page');

test.describe('Home', () => {
  let homePage;
  test.beforeEach(async ({ page }) => {
    homePage = new HomePage(page)
  })

  test('Load HomePage', async ({ page }) => {
   // the auto-completion doesn't work here anymore
    await homePage.navigate()
  });
});
```

**Note:** it works fine when I initialize the POM class in the test itself like this - 
```  
test('Open HomePage and verify title', async ({ page }) => {
   // this works
   let homePage = new HomePage(page)
   await homePage.navigate()
});
```

 Any suggestions on how to get this to work using `beforeEach` hook?

**Comment by mxschmitt** [comment]
There are multiple ways of fixing this:

a) you can annotate your homePage with the HomePage class via JSDoc.
```js
/** @type {HomePage} */
let homePage;
````

b) Use TypeScript, then you can do: `let homePage: HomePage;`
