### ISSUE TITLE
[Question] How to handle multiple window using framework?

### ISSUE THREAD

**Issue by ortoniKC** [microsoft/playwright#14473]
Playwright V1.22 with typescript and test runner.
Hi, I am trying to achieve a window handling concept similar to Selenium Webdriver.

here the problem is it's always referring to the initially launched page, in switchToWindow(1), I have changed the new page but still referring to the old page object.
Can you pls help?
Repo link: https://github.com/ortoniKC/playwright-typescript-framework
test.ts
```
import test from "../src/base/utils/fixtures";

test("test", async ({ page, wsPage, winPage, base }) => {
    await page.goto("https://letcode.in/windows");

// Opens a new tab
    await winPage.clickOpenHomePage();
    base.switchToWindow(1);
    console.log('After switching: ' + page.url());
// Performing click action in new tab
    await wsPage.clickEditLink();
    console.log('Expected test: ' + page.url());
})

```

Fixture.ts
```
const test = baseTest.extend<{
    wsPage: WSPage;
    winPage: WindowPage;
    base: Wrapper
}>({
    base: async ({ page }, use) => {
        await use(new Wrapper(page));
    },
    wsPage: async ({ page }, use) => {
        await use(new WSPage(page));
    },
    winPage: async ({ page }, use) => {
        await use(new WindowPage(page));
    },
})

export default test;
export const expect = test.expect;
```
Wrapper.ts
```
import { ElementHandle, Locator, Page } from "@playwright/test";
export default class Wrapper {

    constructor(protected page: Page) {
    }

    protected async findLocator(value: string, options?: {
        frame?: string | undefined;
        waitForLocator?: boolean | undefined;
        state?: "visible" | "attached";
        timeout?: number;
    }): Promise<ElementHandle<SVGElement | HTMLElement> | Locator> {
        if (options?.waitForLocator) {
            return await this.page.waitForSelector(value, {
                state: options.state,
                timeout: options.timeout
            });
        }
        if (options?.frame) {
            return this.page.frameLocator(options.frame).locator(value);
        }
        return this.page.locator(value);
    }
    public switchToWindow(tabId: number) {
        const pages = this.page.context().pages();
        console.log('No.of Windows: ' + pages.length);
        this.page = pages[tabId];
    }
     public get getUrl() {
            return this.page.url();
        }

}

```

windowPage.ts
```
import { Page } from "@playwright/test";
import Wrapper from "../base/Wrapper";

export default class WindowPage extends Wrapper {
    constructor(protected page: Page) {
        super(page);
    }

    public async clickOpenHomePage() {
        await Promise.all([
            this.page.waitForEvent("popup"),
            this.page.click("#home")
        ])
    }
}
```
WsPage.ts
```
import { Page } from "@playwright/test";
import Wrapper from "../base/Wrapper";

export default class WSPage extends Wrapper {
    constructor(protected page: Page) {
        super(page);
    }

    public async clickEditLink() {
        console.log('Got new page? ' + this.getUrl);
        await (await this.findLocator("//a[.='Edit']")).click({ timeout: 10000 });
    }
}
```

**Comment by Bessonov** [comment]
Not sure I get you. Just wild guess:
- to open a new browser look at https://playwright.dev/docs/api/class-browsercontext
- to open a new tab look at https://playwright.dev/docs/api/class-browser#browser-new-page

**Comment by ortoniKC** [comment]
> Not sure I get you. Just wild guess:
> - to open a new browser window look at https://playwright.dev/docs/api/class-browsercontext
> - to open a new tab look at https://playwright.dev/docs/api/class-browser#browser-new-page

Yeah, I'm aware of this, when i click on home page link, it will open a new tab. 
I want to switch there and perform some tasks. 

const pages = page.context().pages() will return the all the opened tab, i can use pages[1] to interact with the new opened page. 
But what I'm trying to replace the existing page obj with the new page.

**Comment by pavelfeldman** [comment]
I'm not sure what replace means in your context. You have two variables, they represent two pages, what do you mean by replace and why do you need it? What user action would this correspond to?

**Comment by ortoniKC** [comment]
await wsPage.clickEditLink(); - This function has only one action to click on element.
This page can load in the direct tab itself or it can be opened from an another page.
So I don't want to change the function rather I would like to handle it from the page obj.

**Comment by pavelfeldman** [comment]
That would not be possible. If depending on what this function do, you need to continue in this or another page, your only option is to return this page from the method and go on with whatever is returned.
