### ISSUE TITLE
[BUG] Slow tests on Webkit (> 30 seconds)

### ISSUE THREAD

**Issue by rainerhahnekamp** [microsoft/playwright#14470]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: WebKit

**Code Snippet**

```typescript
import { test, expect } from '@playwright/test';

test('should add a new customer', async ({ page }) => {
  await page.goto('https://genuine-narwhal-f0f8ad.netlify.app/');
  await page.click('data-testid=btn-customers');
  await page.click('data-testid=btn-add-customer');
  await page.fill('data-testid=inp-firstname', 'Luise');
  await page.fill('data-testid=inp-lastname', 'Dervist');
  await page.click('data-testid=inp-country'); // fails here
  await page.click('text=Greece');
  await page.fill('data-testid=inp-birthdate', '12.9.2001');
  await page.click('data-testid=btn-submit');

  await expect(
    page.locator('data-testid=row-customer', {
      hasText: 'Dervist, Luise',
    })
  ).toBeVisible();
});
```

**Describe the bug**

The test fails with a timeout error message when clicking on `data-testid=inp-country`. When I increase the timeout from 30 to 60 seconds, it works. Firefox and Chromium run around 2-3 seconds.

Would be great, if you can give me a clue what might cause that issue.

Thank you very much!

**Comment by aslushnikov** [comment]
> https://genuine-narwhal-f0f8ad.netlify.app/

@rainerhahnekamp This URL is not available; any chance you can bring it back so that we can have a look?

**Comment by rainerhahnekamp** [comment]
@aslushnikov , can you please re-check? It is available on my machine and I also ran a successful WebPageTest on it: https://www.webpagetest.org/result/220531_BiDcT4_8AZ/

**Comment by aslushnikov** [comment]
> can you please re-check? 

@rainerhahnekamp yep, works rn. I don't have a windows readily available to try your snippet, but it works instantly for me on MacOS.

Can you record a trace of the slow run? Maybe it'll shed some light.

**Comment by pavelfeldman** [comment]
Following styles make rasterization very slow w/o HW acceleration on Windows.

```css
background-blend-mode: saturation
background-size: cover;
```

The image that is being processed is https://genuine-narwhal-f0f8ad.netlify.app/assets/large-bg.jpg
800k, 2048x1536 size.

**Comment by rainerhahnekamp** [comment]
I see, thank you very much for your help. Makes totally sense.

@pavelfeldman @aslushnikov  👍
