### ISSUE TITLE
[Question] Is there any option to get an element using children or parent like functions?

### ISSUE THREAD

**Issue by gegoncalves** [microsoft/playwright#14478]
In cypress we have the option to get a children or parent using the `.children()` and `.parent()` syntaxes

- Do we have any similar option in Playwright?

https://docs.cypress.io/api/commands/children
https://docs.cypress.io/api/commands/parent

**Comment by vomc** [comment]
+1

**Comment by vomc** [comment]
Doesn't seem supported as per this: https://github.com/microsoft/playwright/issues/14374

**Comment by gegoncalves** [comment]
> Doesn't seem supported as per this: #14374

It would be nice to have that feature. Probably I am the only one that needs it 😅

**Comment by aslushnikov** [comment]
@gegoncalves The `has` option is much more powerful than both `.children` and `.parent`. Why would you need them?

**Comment by gegoncalves** [comment]
I am trying to return the amount of div inside of a another div and for any reason for the `has` it is returning only the first found div.

With `has` is possible to do find an specific ascendent or it just goes to the descendent? @aslushnikov

**Comment by aslushnikov** [comment]
> I am trying to return the amount of div inside of a another div

For this you don't even need `has`! You'll need to just select the elements. Here's an example:

```
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
const page = await browser.newPage();
// Set a dummy HTML to illustrate.
await page.setContent(`
  <section>
    <div>hello</div>
    <div>world</div>
  </section>
`);

// This is just a CSS selector with a ">" combinator, which means direct descendants. 
console.log(await page.locator('section > div').count());
await browser.close();
```

**Comment by gegoncalves** [comment]
Shoooees. I am dumb 😅 

Thanks for the help
