### ISSUE TITLE
[BUG] fullyParallel flag affects serial suites to be executed in parallel.

### ISSUE THREAD

**Issue by DOrlov77** [microsoft/playwright#14471]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 16.12.0
- Browser: Chromium, Firefox
- Extra: ---

**Code Snippet**

const config: PlaywrightTestConfig = {
    fullyParallel: true,
   ...
 }

**Describe the bug**

When this flag is set, all tests A,B and C will be executed in the dedicated worker (parallel) instead of the defined explicitly Serial mode

```
test.describe.serial("Tests to be run in Serial", () => {
    test("A", () => { ... });
    test("B", () => { ... });
    test("C", () => { ... });
});
```

**Comment by sam-022** [comment]
I am facing the same issue as well. `fullyParallel` flag is not letting the individual test file to run sequentially. Tried both ways - 

`test.describe.configure({ mode: 'serial' })`

`test.describe.serial('Tests to run in serial', () => {}`

Note: the opposite works fine. When setting the `fullyParallel` to `false`, all tests runs sequentially. And, when you set the mode to parallel for individual file, it will run that file in parallel.
