### ISSUE TITLE
[BUG] multiple tests suddenly fail "waiting for element to be stable"

### ISSUE THREAD

**Issue by benwiley4000** [microsoft/playwright#14480]
**Context:**
- Playwright Version: 1.18.1
- Operating System: Linux
- Node.js version: v14.6.1
- Browser: Chromium
- Extra: Jenkins CI environment

**Describe the bug**

Unfortunately there's not any short code snippet I can provide to reproduce this but I can describe the issue. In our CI, our suite of tests is normally green just about every time on our main branch. But this morning one of our tests runs was red, and the large majority of our tests failed. Other subsequent runs were green.

When I inspected the traces that were collected, all of the traces fail because we were waiting for an element to become stable, and our 30 second timeout ran out. The thing is, in the video of the test run, we can see that the element is visible and motionless for the duration of those 30 seconds. It's possible something happened with the render, but it seems like a strange coincidence that this happened for multiple pieces of UI in different tests at the same time.

One of our tests got stuck on a loading spinner and the spinner was motionless, so it makes me think there might have been a memory issue.

Another strange thing I noticed (this is the second time I see this, but the first time I document it) is that not every failed Playwright test had a saved trace associated. Instead we have a bunch of strange folders labeled `.playwright-artifacts-#` and they contain only webm fragments, not test traces, and everything is unlabeled. Seems to indicate that Playwright melted down at some point, but the console output seems to indicate that the main Playwright process exited normally.

![2022-05-30_09-57](https://user-images.githubusercontent.com/13558253/171010273-f2425131-42a2-49c2-8a78-4b05220bc653.png)

**Comment by aslushnikov** [comment]
> When I inspected the traces that were collected, all of the traces fail because we were waiting for an element to become stable, and our 30 second timeout ran out. The thing is, in the video of the test run, we can see that the element is visible and motionless for the duration of those 30 seconds. It's possible something happened with the render, but it seems like a strange coincidence that this happened for multiple pieces of UI in different tests at the same time.

@benwiley4000 it's hard to say what went wrong here. Did the failures happen on multiple different machines or a single one? If all the failures happened once on the single machine, it could be some machine misbehavior.

**Comment by aslushnikov** [comment]
> it seems like Playwright might be swallowing an error case silently on the Node.js level.

It could be, but it'll be hard to debug without a repro.

> What are these playwright-artifacts directories and when do they get deleted / what would cause them to stick around ?

These are created when browser is launched and removed as the browser is closed. If these persist, then something went wrong there, but just by eye-balling the code I can't say for sure.

**Comment by pavelfeldman** [comment]
I don't think we can act on this report without the reproduction. Please file a new issue and link to this one if you succeed at creating a small repro for us.

**Comment by usersina** [comment]
I also often have the same errors running as a library. It's so hard to reproduce though due to how random it seems, so I just assumed it's the nature of browsers to be clunky when ran as automation/testing tools.

I'm considering using the [Trace Viewer](https://playwright.dev/docs/trace-viewer) with some screenshots as a debug step.
