### ISSUE TITLE
[Question] Is it possible to run parallel x browser (firefox,chromium) test against moon cluster  ?

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#14484]

**Comment by aslushnikov** [comment]
I'd ask this question in the Moon support!

**Comment by amrsa1** [comment]
@aslushnikov  yes true, but i was asking more on configuration level ?

**Comment by aslushnikov** [comment]
Configuration-wise, all Playwright [parallelization strategies](https://playwright.dev/docs/test-parallel) should apply there as well!
