### ISSUE TITLE
[Feature] Add label to HTML-report from test for test filtering

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#14487]
Hi! 
Is it possible to add such beautiful labels to the HTML report directly from the test, even if it is already in the scope of the project or does not have a project at all. It is very convenient to filter the tests in the report using these tags.

Thank you for your attention!

![Screenshot 2022-05-30 at 19 34 20](https://user-images.githubusercontent.com/35337277/171033635-e29d19e8-6511-4c17-8381-67727dba29bc.png)

**Comment by alexneo2003** [comment]
@bezyakina hi
does it look like you wanted?

<img width="1074" alt="Monosnap Playwright Test Report 2023-02-23 21-19-33" src="https://user-images.githubusercontent.com/11705902/221009971-bcc772a7-7992-4c92-9abf-3a6dc9c4742f.png">
<img width="1128" alt="Monosnap Playwright Test Report 2023-02-23 21-20-51" src="https://user-images.githubusercontent.com/11705902/221009965-074a1553-ff2f-4352-9017-eae3450b00c7.png">
<img width="1141" alt="Monosnap Playwright Test Report 2023-02-23 21-21-49" src="https://user-images.githubusercontent.com/11705902/221009961-8327592f-9be1-40a0-801c-48236ac36a81.png">

@pavelfeldman if it does i can make PR
(it will only be necessary to cover it with tests :-))

**Comment by bezyakina** [comment]
> @bezyakina hi
> 
> does it look like you wanted?

@alexneo2003 hi, these tags look nice. I can add yet another custom tag from test? (maybe this feature already implemented as part of another issue)

**Comment by alexneo2003** [comment]
> @alexneo2003 hi, these tags look nice. I can add yet another custom tag from test? (maybe this feature already implemented as part of another issue)

yes, you may write tags in test name like `@smoke` `@regression `etc... and than tests will be filtered about it
now i make some feature for this filters - severals tags filter and after it i make PR

**Comment by PaulMEdwards** [comment]
First, thanks for this functionality, it's pretty good.

However, we have noticed a couple issues with the implementation in #21468... Specifically, tags in a `test.describe` wrapper of other `test`s are ignored and tags with hyphens are broken.

Attached is a screenshot showing both issues. The `test.describe('@Monitoring', ...` tag is ignored and the tag `@call-details` is incorrectly rendered as `call`.

<img width="996" alt="Screenshot 2023-05-04 at 2 06 35 PM" src="https://user-images.githubusercontent.com/153847/236291053-a077e078-1622-4e3b-94b9-39ce77e8b172.png">

**Comment by alexneo2003** [comment]
@PaulMEdwards 
Dash was fixed in #22709 and will be released soon.
Tag in describe was not planning for parsing
Maybe you will create feature issue for this?

**Comment by mxschmitt** [comment]
This looks implemented on test-level, closing for now. For further feature requests, don't hesitate to file new ones!
