### ISSUE TITLE
[BUG] Playwright component testing doesn't seem to record videos

### ISSUE THREAD

**Issue by Phonesis** [microsoft/playwright#14483]
I have the following version of playwright component testing set up: 

```  "@playwright/experimental-ct-react": "^1.22.2",```

I have this set in my playwright ct config file: 

```
  use: {
    headless: true,
    video: 'on',
    screenshot: 'on',
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100
  },
```

In the HTML report I see screenshots but no video for any tests (passed of failed). Is this a bug or expected? Would be good to get videos.

**Comment by aslushnikov** [comment]
> Is this a bug or expected?

It is expected for videos.

> Would be good to get videos.

We recommend everybody to use traces instead! It has videos and much more! Would it work for you?

**Comment by PavanMudigondaTR** [comment]
@pavelfeldman @aslushnikov I have the same feedback. I suddenly see video capture is not working. I loved this feature and its main selling point to my team. Could you please tell if you could bring this back ?

**Comment by aslushnikov** [comment]
@PavanMudigondaTR the fix has landed and will be live in 1.23!

**Comment by Phonesis** [comment]
Yeah fantastic work turning this around so quick

**Comment by PavanMudigondaTR** [comment]
> 

sorry i saw video file getting generated but white screen in 1.22 i will check when 1.23 arrives.
