### ISSUE TITLE
How is this better than Selenium or Appium ?

### ISSUE THREAD

**Issue by vikramvi** [microsoft/playwright#14490]
What's the reason, MS has created this "one" more automation tool ? When it could have contributed to 2 popular open source libraries namely Selenium and Appium ?

Why should one use this and not Selenium, Appium ( as these 2 are gold standards for Web, Mobile automation ) ?

**Comment by pavelfeldman** [comment]
Please only file issues related to the project functionality, bugs and features!

**Comment by vikramvi** [comment]
Being ex-MS employee, am curious to know philosophy behind reinventing wheel by team in MS headquarter.

Even though this is not a bug, I've asked as query; why can't responsible person can't reply in detail ?

Is there any secret for not replying or MS just don't want to support open source community ?
