### ISSUE TITLE
[BUG]: Unable to accept/dismiss leave site pop up

### ISSUE THREAD

**Issue by vivekvasu95** [microsoft/playwright#14505]
**Context:**
- Playwright Version: [1.21.0]
- Operating System: [Mac]
- Python version: [3.10]
- Browser: [Chromium]

**Code Snippet**

```python
page.once("dialog", lambda dialog: dialog.dismiss())
page.click("text=Drafts")

```
 Tried  setting the onbeforeload function as well
```python
await page.evaluate(() => {
  window.onbeforeunload = null;
});
```

**Describe the bug**

Leave site pop up is not closing. Test is working running in background without any issues, but the leave site pop up is unable to handle

![image](https://user-images.githubusercontent.com/102962308/170439841-82dc2f11-aa0b-49ba-ac9b-a19bd100f88c.png)

**Comment by aslushnikov** [comment]
@vivekvasu95 [Max's answer](https://github.com/microsoft/playwright/issues/14505#issuecomment-1142026640) should work for you 

@Warrfie you should setup an HTTP authentication: https://playwright.dev/docs/network#http-authentication

**Comment by Warrfie** [comment]
> @vivekvasu95 [Max's answer](https://github.com/microsoft/playwright/issues/14505#issuecomment-1142026640) should work for you
> 
> @Warrfie you should setup an HTTP authentication: https://playwright.dev/docs/network#http-authentication

It didn't work. Because there is more than one SSO Login Prompt on that site, I can pass only one via that method.

**Comment by siddesh-sadamastula** [comment]
@vivekvasu95 have you got any solution to close 'leave site?' warning in playwright
I am facing same issue, tried lot of thing from net but nothing works
need help!

**Comment by tinbka** [comment]
@mxschmitt It's still not working in 2024. The lambda doesn't run at all when this annoying dialog pops up.

**Comment by tinbka** [comment]
@mxschmitt it's only working against `alert`, `prompt`, `confirm` JS guys, not against "Leave site?"
@siddesh-sadamastula this helped me https://stackoverflow.com/questions/64569446/can-i-ignore-the-leave-site-dialog-when-browsing-headless-using-puppeteer

**Comment by mxschmitt** [comment]
See here how to deal with beforeunload dialogs in Playwright: https://playwright.dev/docs/dialogs#beforeunload-dialog

**Comment by tinbka** [comment]
@mxschmitt An example of a page that doesn't define window.onbeforeunload but still fires that pop up: https://partners.ridge.com/join?referral=Organic
I haven't tested the `on('dialog'...` function in Node but in Ruby it definitely doesn't listen to those pop-ups. And I actually deceived myself, in Ruby `page.on` doesn't listen to `alert` etc as well.
`page.close(runBeforeUnload: false)` also doesn't prevent this, and manually clicking Cancel in the pop-up leaves `page.close` hanged up.
I also tried a bunch of Chromium flags that GPT coined, with no success:
```
        '--disable-popup-blocking',
        '--disable-features=beforeunload',
        '--disable-infobars',
        '--no-default-browser-check',
```

**Comment by mxschmitt** [comment]
> @mxschmitt An example of a page that doesn't define window.onbeforeunload but still fires that pop up: https://partners.ridge.com/join
> 
> I haven't tested the `on('dialog'...` function in Node and Python but in Ruby it definitely doesn't listen to those pop-ups. And I actually deceived myself, in Ruby `page.on` doesn't listen to `alert` etc as well.
> 
> `page.close(runBeforeUnload: false)` also doesn't prevent this, and manually clicking Cancel in the pop-up leaves `page.close` hanged up.
> 
> I also tried a bunch of Chromium flags that GPT coined, with no success:
> 
> ```
> 
>         '--disable-popup-blocking',
> 
>         '--disable-features=beforeunload',
> 
>         '--disable-infobars',
> 
>         '--no-default-browser-check',
> 
> ```

Please file a new bug report, happy to triage from there.

**Comment by tinbka** [comment]
For Ruby guys getting here in the search of a fix, you can add this and run `page.prevent_blocking` once for every web page you want to seamlessly escape.
```ruby
class Playwright::Page
  def cdp_session
    @cdp ||= context.new_cdp_session(self)
  end

  def cdp_evaluate(js)
    cdp_session.send_message('Runtime.evaluate', params: { expression: js, includeCommandLineAPI: true, returnByValue: true })
  end
  
  def prevent_blocking
    cdp_evaluate(<<~JS)
      getEventListeners(window).beforeunload.forEach(listener => {
        window.removeEventListener('beforeunload', listener.listener, { capture: listener.useCapture })
      })
    JS
  end
```
