### ISSUE TITLE
What is the way to scroll page to the bottom? - playwright java?

### ISSUE THREAD

**Issue by shilpa32** [microsoft/playwright#14503]
I need a solution to scroll the page to the bottom in playwright java. could anyone please help me out?

**Comment by aslushnikov** [comment]
Use [`page.evaluate`](https://playwright.dev/java/docs/next/api/class-page#page-evaluate) for this:

```java
page.evaluate("document.documentElement.scrollTop = document.documentElement.offsetHeight")
```
