### ISSUE TITLE
disable Web push notifications WEBKIT

### ISSUE THREAD

**Issue by tiger360** [microsoft/playwright#14514]
Hey,
I added in args : --disable-notifications.
`browser = await webkit.launch({           
            args: ['--disable-notifications',
                   ],
            headless: false,
            slowMo: 500,
        });`
But there is still the popup. 
I am using the webkit

Thanks

**Comment by aslushnikov** [comment]
@tiger360 what OS are you running? What kind of popup do you try to disable? Can you share a screenshot / website?

**Comment by tiger360** [comment]
Hello,
It is on Ubuntu 20.04
Sorry, it was on Youtube but I could not reproduce it. 
Time to time it's appearing and because of that, the selectors are failing.
![image](https://user-images.githubusercontent.com/5794444/171405094-f6f4e847-befc-414c-a794-ffb5f5535673.png)

**Comment by tiger360** [comment]
Yeah it's just an example 😅.
The message was kinda : "Allow YouTube.com to send notifications?"
It was in the YouTube studio page when I'm connected.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
