### ISSUE TITLE
[Question] Different global setup per project

### ISSUE THREAD

**Issue by agataDeviniti** [microsoft/playwright#14513]
Hi,
I am wondering, if there is possibility I could create two different globalSetup for different projects defined in playwright.config.ts?
Right now I have 1 global setup for both of my projects, but I would like to make it separate and create 2 different globalSetup.

**Comment by aslushnikov** [comment]
We do have thoughts about this. It might be implemented as part of the https://github.com/microsoft/playwright/issues/13362, so I'll merge this into the "plugins" bug.

**Comment by mariaceo** [comment]
We're also interested in this feature, but I see that #13362 was closed. Do you have a workaround or any future plans for such functionality?

**Comment by missing1984** [comment]
+1, need different global setup logic per project. Should we reopen this?

**Comment by tomer555** [comment]
+1

**Comment by MelodicsVincent** [comment]
+1

**Comment by cmatth765** [comment]
+1

**Comment by ryaudio** [comment]
+1

**Comment by stephanebenayoun** [comment]
+1

**Comment by srieas** [comment]
+1

**Comment by abetss** [comment]
+1

**Comment by ltsuda** [comment]
it might be the ideal/expected feature but do you think this could be a workaround for now?

Using project dependency.
https://playwright.dev/docs/release-notes#new-apis-1
