### ISSUE TITLE
[BUG] toMatchSnapshot always pass with custom filepath

### ISSUE THREAD

**Issue by khtufteland** [microsoft/playwright#14527]
**Context:**
- Playwright Version: 1.22
- Operating System: Linux and Mac
- Node.js version: v14.18.1
- Browser: Firefox

**Code Snippet**

All code available in https://github.com/khtufteland/playwright-toMatchSnapshot.

**Describe the bug**

It's very possible that I'm not using the library correctly. However, I encountered this problem when I tried to manipulate the `snapshot` function together with the `toMatchSnapshot` function to control the file path of the generated snapshots to fit my needs. Basically would I like to store the snapshots in separated folders, rather than having all snapshots in one folder.

In the aforementioned repo have I created two tests, both should fail. But the one with custom path never fails.

**Comment by aslushnikov** [comment]
@khtufteland I created a PR for your repo that fixes the test: https://github.com/khtufteland/playwright-toMatchSnapshot/pull/1/files

Your test was saving screenshot as an image expectation, and then comparing against the same expectation. No wonder it always passed!

hope it helps!

P.S. you do not need to install both `@playwright/test` and `playwright` - just use `@playwright/test` in your package.json!
