### ISSUE TITLE
[BUG] firefox relaunching for 100 times doesn't work

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#14523]
See https://github.com/microsoft/playwright/runs/6674078920?check_suite_focus=true

**Comment by mxschmitt** [comment]
For example in Python: https://github.com/microsoft/playwright-python/runs/6691621380?check_suite_focus=true

**Comment by mxschmitt** [comment]
Seems like its affecting Windows as well: https://github.com/microsoft/playwright-python/runs/6700039466?check_suite_focus=true
