### ISSUE TITLE
[BUG] array setup to use in a forEach loop

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#14533]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Mac
- Node.js version: 16.14.2
- Browser: not applicable
- Extra: I use axios as the node module to make api calls as mentioned below.

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```js
// helperFunctions.ts

export function usernameGen(length) {
    let result = '';
    const characters = `'你好喂èíàóえこれúñç@들은서ระกาศถ่ายทอดสดศึกฟุตบอล비스호출에추èящий%用語ăをțどん#ね.[]{}`;
    const charactersLength = characters.length;
    for (let i = 0; i< length; i++) {
        result += characters.charAt(Math.floor(Math.random() * charactersLength))
    }

    return result;
}

export function usernameArr(arrLength, usernameLength) {
    let arr = [];
    for (let i = 0; i < arrLength; i++) {
        arr.push(usernameGen(usernameLength));
    }
    return arr;
}
```

```js
// test.spec.ts

test.describe("Custom Username Login Tests", async () => {


   let names = usernameArr(4, 18);


     names.forEach(function (username) {
        test(`save a special character username, username saved is: ${username}`, async () => {
            
            let response = await putSaveUsername(username);

            await expect(response.status).toBe(200);
            await expect(response.data.status).toBe("SUCCESS");
          
        })
    })
})
```

**Describe the bug**

Hey guys, this might just be something Playwright can't do at execution or maybe I just don't understand but wanted to see if this was a bug or if this is something not supported/won't be a feature.

I'm doing a test that's a sort of hybrid API/UI test where I randomly generate some strings and then send those strings to an API to ensure it saves correctly and then on the UI side I ensure that string that was saved can also be used to login with. If you look at the code example above, you can see the setup where within the test file I am calling the function to setup the usernames I want to save. What happens when this starts running is it just constantly runs through this function and doesn't stop so it never gets to the test execution. If I do NOT call that usernameArr function and instead pass in hardcoded strings into the array, then the test works and runs successfully. However, having the ability to have these randomly generated would be nice but I think Playwright is limiting me doing that with the way it executes. 

Let me know if I can do this another way or if this is just something Playwright may not support / won't support.

Thank you!

**Comment by kryaksy** [comment]
I think it's not a bug. It's a promise chaining issue if I understood correctly. I've tried to produce test cases dynamically in a loop but it doesn't work as expected. Instead, producing test steps in the loop works well for this case. I don't know if this is a best practice.

```javascript
// test.spec.ts
import { test, expect } from '@playwright/test';

test.describe('Custom Username Login Tests', async () => {

  let names = usernameArr(4, 18);

  test(`save special character usernames`, async () => {
    await names.reduce((acc, username) => {
      return acc.then(async () => {
        await test.step(`username saved is: ${username}`, async () => {
          let response = await putSaveUsername(username);
          expect(response.status).toBe(200);
          expect(response.data.status).toBe('SUCCESS');
        });
      });
    }, Promise.resolve());
  });

});


```

**Comment by aslushnikov** [comment]
@bshostak you should remove `async` from the `test.describe` callback function, and it should all work:

```js
// test.spec.ts

test.describe("Custom Username Login Tests", () => {


   let names = usernameArr(4, 18);

     names.forEach(function (username) {
        test(`save a special character username, username saved is: ${username}`, async () => {
            
            let response = await putSaveUsername(username);

            await expect(response.status).toBe(200);
            await expect(response.data.status).toBe("SUCCESS");
          
        })
    })
})
```

**Comment by bshostak** [comment]
@aslushnikov thank you for looking at this! I removed the async from the describe block but I am still seeing the same behavior. Basically what happens is:

1. I run npx playwright test
2. I see a log of "Running 4 tests using 1 worker" ( i have it set to use 1 worker for right now).
3. It sits at this log and never starts executing the tests. 

the odd thing is that when debugging, if I had a console.log here:
`export function usernameArr(arrLength, usernameLength) {
    let arr = [];
    for (let i = 0; i < arrLength; i++) {
        arr.push(usernameGen(usernameLength));
    }
console.log(arr);
    return arr;
}`

the cl is constantly running through this function and returning multiple arrays with the values. So it's almost like Playwright is thinking it needs to run this function over and over and over?

**Comment by aslushnikov** [comment]
@bshostak so could you please show me all your source code so that I can debug it locally?

**Comment by bshostak** [comment]
@aslushnikov Unfortunately I can't share all the source code since it's behind work stuff, but this repo I created does basically the same functionality with trying to generate an array of strings and then the test just dies as explained previously. Thanks for looking at this.

https://github.com/bshostak/playwrightdemo

**Comment by aslushnikov** [comment]
@bshostak Ah! Now I see!

The issue is that test generation has to be **deterministic**, so you cannot use `Math.random()` when generating tests.

One way to workaround this would be to use a [seeded random](https://en.wikipedia.org/wiki/Random_seed). Something like this:

```ts
const rand = mulberry32(1989);

export function usernameGen(length) {
    let result = '';
    const characters = `'你好喂èíàóえこれúñç@들은서ระกาศถ่ายทอดสดศึกฟุตบอล비스호출에추èящий%用語ăをțどん#ね.[]{}`;
    const charactersLength = characters.length;
    for (let i = 0; i< length; i++) {
        result += characters.charAt(Math.floor(rand() * charactersLength));
    }

    return result;
}

export function usernameArr(arrLength, usernameLength) {
    let arr = [];
    for (let i = 0; i < arrLength; i++) {
        arr.push(usernameGen(usernameLength));
    }
    return arr;
}

function mulberry32(a) {
  return function() {
    var t = a += 0x6D2B79F5;
    t = Math.imul(t ^ t >>> 15, t | 1);
    t ^= t + Math.imul(t ^ t >>> 7, t | 61);
    return ((t ^ t >>> 14) >>> 0) / 4294967296;
  }
}
```

**Comment by bshostak** [comment]
@aslushnikov wow, consider my brain broken looking at how that function works 😅 . Thanks so much for your help with figuring out this issue! I will go ahead and close this.
