### ISSUE TITLE
Importing private typescript modules in Playwright

### ISSUE THREAD

**Issue by dragancla** [microsoft/playwright#14547]
### Discussed in https://github.com/microsoft/playwright/discussions/14545

I'm having issues with importing custom private modules in Playwright tests. 

Test code - functionality.test.ts

```typescript 
import { FunctionalityRequest } from '@privateRepo/schemas/functionality-schema'
import { Builder } from 'builder-pattern'
import { MyLocation } from '../../../api/api-helper'
import { getAfterDaysDateUTC, nowUTC } from '../../../utils/date-utils'

test.describe('[@API] Some functionality', () => {
  test('verify functionality of main product', async ({ functionalityController }) => {
    const functionalityRequest = Builder<FunctionalityRequest>()
      .location(MyLocation.DEV)
      .functionalityStart(nowUTC)
      .functionalityEnd(getAfterDaysDateUTC(1))
      .build()

      await functionalityController.functionalityThing(functionalityRequest)
      // rest of test
  })
})
```

It always throws an error `Error: src/tests/api-tests/functionality.test.ts: JavaScript files must end with .mjs to use import.`

Test is obviously typescript. I have no javascript files in my project at all. The module I'm importing is also written in typescript. 

What works: on line 1, add the word `type` after the import, like `import type { FunctionalityRequest } from '@privateRepo/schemas/functionality-schema'`

That works for this scenario as the thing I'm importing is an interface but, if we would want to import other data, being constrained to only being able to import types would not work for us.

I've isolated the issue to https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/loader.ts (or, in my case, `project/node_modules/@playwright/test/lib/loader.js`) lines 292-295. Commenting those lines makes the tests run perfectly. 

I wonder what's this limitation about? How would I be expected to import private typescript modules in Playwright?

Package: @playwright/test@1.22.2

**Comment by aslushnikov** [comment]
> I've isolated the issue to https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/loader.ts (or, in my case, project/node_modules/@playwright/test/lib/loader.js) lines 292-295. Commenting those lines makes the tests run perfectly.

Permalink to the code: https://github.com/microsoft/playwright/blob/e69c3f12e6f07ee9e737446ba22f20cb669d7211/packages/playwright-test/src/loader.ts#L292-L295

cc'ing @pavelfeldman who might have more context

**Comment by pavelfeldman** [comment]
> What works: on line 1, add the word type after the import, like import type { FunctionalityRequest } from '@privateRepo/schemas/functionality-schema'

This is expected, with the TypeScript / ESM interoperability, you must say `import type` when you are importing types.

For non-types, you are hitting the `Cannot use import statement outside a module` error. This means that you are importing a JavaScript ESM module from a non-module (TypeScript has nothing to do with it). Only Node modules can import from other modules. Could you share which ones are `type: module` and which ones are not in your setting? Also the exact code that triggers the error and the error itself.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by pawelgur** [comment]
For anyone landing here from google: there's a wider discussion on the topic https://github.com/microsoft/playwright/issues/14303
