### ISSUE TITLE
[Feature] Mark test for auth. / manage often used states in config

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright#14552]
I would like to request a feature:

I think it would be really convenience when we could mark test authenticated or not

I know playwright config have a use {} object that we can use to authenticate all tests but what if we have tests that dont need that auth?

So some pseudo code here:

```
// get_states.ts
import { chromium } from '@playwright/test';

// variable to store the function
let guestUserState: Function;

guestUserState = async () => {
    let browser = await chromium.launch();
    let page = await browser.newPage();
    await page.goto('/login')
    await page.locator("//input[@id='username']").fill(process.env.GUEST_USERNAME)
    await page.locator("//input[@id='password']").fill(process.env.GUEST_PASSWORD)
    await page.locator("//button[@id='submitButton']").click()
    await page.context().storageState({ path: './guestState.json' })
}
// we export then all the functions stored in variables to use it in the config
export -> functions

```

```
use: {
    baseURL: "https://someUrl.com",
    locale: "en-GB",
    ignoreHTTPSErrors: false,
    launchOptions: {slowMo: 1000},
    httpCredentials: {username: process.env.SOME_USERNAME, password: process.env.SOME_PASSWORD},
    states: {
    {guestUser(could be anything just the key): "./guestState.json", guestUserState // some function that is called once per worker to get a fresh state},
    {adminUser(could be anything just the key): "./adminState.json", adminUserState // some function that is called once per worker to get a fresh state},
    {someOtherUser: "./someOtherState.json", otherUserState // some function that is called once per worker to get a fresh state},
    .... and so on
    }
  },
```

And we would use it like that:

```
test.describe("Some Epic", async () => {
  let header: Header

  test.beforeEach(async ({ page }) => {
    await page.goto("/")
  });

  test.auth("Header_loggedIn", guestUser, async ({ page }) => {
  // this test has context injected with the guestUser from the config and so on, the page itself in this test
    header = new Header(page)
    await header.gotoLoginOrProfile()
    await expect(page).toHaveURL("https://someUrl/my-profile")
  })
})
```
if we want no auth we just use:

```
test("some text", async () => {
//
})
```
if we want auth we use:

```
test.auth("some text", //key from config, async () => {
//
})
```

What do you think about that approach? Its just an idea because often tests need a specific authorization for many tests.

**Comment by aslushnikov** [comment]
@Kranael you can use [`test.use()`](https://playwright.dev/docs/api/class-test#test-use) right next to the test you want to auth. Like this:

```js
test.describe('tests with auth', () => {
  test.use({
    httpCredentials: {username: process.env.SOME_USERNAME, password: process.env.SOME_PASSWORD},
  });
  
  test('should auth', () => {
    // ...
  });
});
```

Would it work for you?

**Comment by aslushnikov** [comment]
@Kranael you can use [`test.use()`](https://playwright.dev/docs/api/class-test#test-use) right next to the test you want to auth. Like this:

```js
test.describe('tests with auth', () => {
  test.use({
    httpCredentials: {username: process.env.SOME_USERNAME, password: process.env.SOME_PASSWORD},
  });
  
  test('should auth', () => {
    // ...
  });
});
```

Would it work for you?

**Comment by Kranael** [comment]
> @Kranael you can use [`test.use()`](https://playwright.dev/docs/api/class-test#test-use) right next to the test you want to auth. Like this:
> 
> ```js
> test.describe('tests with auth', () => {
>   test.use({
>     httpCredentials: {username: process.env.SOME_USERNAME, password: process.env.SOME_PASSWORD},
>   });
>   
>   test('should auth', () => {
>     // ...
>   });
> });
> ```
> 
> Would it work for you?

It works as mentioned in my other post i really would like to have test describe just for grouping and test() for all propertys of the test itself. And if i need a global setup i would use your approach.

Maybe it could be renamed refactored to a "feature" instead of "test" and under the feature.describe() -> test.use etc.?

**Comment by aslushnikov** [comment]
> Maybe it could be renamed refactored to a "feature" instead of "test" and under the feature.describe() -> test.use etc.?

@Kranael You can do it yourself, like this:

```js
const feature = test.describe.bind(test);

feature('tests with auth', () => {
  test.use({
    httpCredentials: {username: process.env.SOME_USERNAME, password: process.env.SOME_PASSWORD},
  });
  test('should auth', () => {
    // ...
  });
});
```

> It works as mentioned in my other post i really would like to have test describe just for grouping and test() for all propertys of the test itself.

I think we're talking about https://github.com/microsoft/playwright/issues/14548. As mentioned there, you can use nested describes, so it all should just work for you!

**Comment by pavelfeldman** [comment]
> It works as mentioned in my other post i really would like to have test describe just for grouping and test() for all propertys of the test itself. And if i need a global setup i would use your approach.

Let me fold it into [14548](https://github.com/microsoft/playwright/issues/14548) then.
