### ISSUE TITLE
[BUG] Any Chrome channel crashes on macOS with no error after few seconds of launching

### ISSUE THREAD

**Issue by mike1808** [microsoft/playwright#14563]
**Context:**
- Playwright Version: `1.23.0-alpha-may-31-2022`
- Operating System: macOS 12.3.1
- Node.js version: v18.2.0
- Browser: `chrome`, `chrome-beta`, `chrome-canary`
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.3.1
 - Memory: 10.54 GB / 64.00 GB
## Binaries:
 - Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
 - Yarn: 1.22.18 - ~/.nvm/versions/node/v18.2.0/bin/yarn
 - npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/local/bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { chromium } = require("playwright");

(async () => {
    const browser = await chromium.launch({
        headless: false,
        channel: "chrome",
        devtools: true,
        logger: {
            isEnabled(name, severity) {
                return true;
            },
            log(name, severity, message, args, hints) {
                console.log(name, severity, message, args);
            },
        },
    });
    const page = await browser.newPage();
    while (true) {
        await page.goto("https://example.org");
        await wait(1000);
    }
    await browser.close();
})();

function wait(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}
```

**Describe the bug**

I'm trying to use any Chrome version instead of Chromium but it closes spontaneously with no errors. Even if you do `npx playwright open --channel chrome` it will close after few seconds.

**Comment by aslushnikov** [comment]
@mike1808 I just ran on MacOS 12, Macbook Pro M1, and it worked fine - no crashes.

It does look though that your stable chrome is corrupted. Could it be the case?

**Comment by mike1808** [comment]
@aslushnikov I don't think so. I have tried all available chrome channels and also tried re-installing. Also, this issue happened with my other teammates.

**Comment by aslushnikov** [comment]
@mike1808 I see you run the `1.23.0-alpha-may-31-2022` Playwright version. Does it repro for you with the Playwright v1.22?

**Comment by mike1808** [comment]
@aslushnikov yes, the result is the same. Are there any flags to make Chrome more verbose to get the error message from it?

**Comment by aslushnikov** [comment]
@mike1808 you can try running `DEBUG=pw:browser npx playwright test` to get logs from the browser.

Also, can you try opening your stable chrome manually? Does it open?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
