### ISSUE TITLE
[BUG] Origin request header is removed when extraHTTPHeaders are used with Chromium

### ISSUE THREAD

**Issue by mike1808** [microsoft/playwright#14566]
**Context:**
- Playwright Version: `1.23.0-alpha-may-31-2022`
- Operating System: macOS 12.3.1
- Node.js version: v18.2.0
- Browser: `chromium`
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.3.1
 - Memory: 10.54 GB / 64.00 GB
## Binaries:
 - Node: 18.2.0 - ~/.nvm/versions/node/v18.2.0/bin/node
 - Yarn: 1.22.18 - ~/.nvm/versions/node/v18.2.0/bin/yarn
 - npm: 8.9.0 - ~/.nvm/versions/node/v18.2.0/bin/npm
## Languages:
 - Bash: 5.1.8 - /usr/local/bin/bash

**Code Snippet**

Open any website, check request headers in the dev tools and see that `origin` is missing.

```javascript
const { chromium } = require("playwright");

(async () => {
    const browser = await chromium.launch({
        headless: false,
        devtools: true,
    });
    const page = await browser.newPage({ extraHTTPHeaders: { "x-my-header": "value" } });
    await page.goto("https://example.org");
    await wait(10000);
    await browser.close();
})();

function wait(ms) {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

```

**Describe the bug**

When you use `extraHTTPHeaders` with Chromium origin request header is not set.

**Comment by yury-s** [comment]
In your example the `origin` header is not expected to be sent and it would be missing without `extraHTTPHeaders`. Do you have a reproducible example where `origin` header is sent without extraHTTPHeaders but not with it?

**Comment by mike1808** [comment]
@yury-s sorry, I realized that I was using `--disable-web-security` which made the browser not to add `origin` header. I am not sure if it's intended behavior for chore or not, but it's not related to playwright.
