### ISSUE TITLE
[BUG] html reporter doesn't respect the OutputFolder, I have 2 different folders with the results split

### ISSUE THREAD

**Issue by dmallavarapu** [microsoft/playwright#14562]
**Context:**
- Playwright Version: [v1.22.0]
- Operating System: [Mac]
- Node.js version: [v16.4]
- Browser: [Chromium]

**Code Snippet**

Here is my playwright.config.ts file

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
    globalSetup: require.resolve('./lib/starter.mjs'),
    use: {
        baseURL: process.env.EX_ENVIRONMENT,
        headless: process.env.RUN_HEADLESS?.toLowerCase() === 'true',
        storageState: 'storageState.json',
        actionTimeout: 10 * 1000,
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
        video: { mode: 'retain-on-failure' },
    },
    testDir: './tests',
    timeout: 30 * 1000, 
    expect: {
        timeout: 5000,
    },
    fullyParallel: true,
    reporter: [
        **['html', { open: 'never', outputFolder: 'pw-results/html' }],**
        ['list'],
        ['allure-playwright', { outputFolder: 'allure-results' }],
        [
            'json',
            {
                outputFile: process.env.PW_RESULTS_FILENAME,
            },
        ],
    ],
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
            },
        },
    ],
};
export default config;
```

**Describe the bug**

I initially gave outputFolder as 'test-results' for html reporter, ran a few times and later decided to change it and now I want to push the html reporter results into "pw-results/html".  Updated the config file accordingly.
Now I see that there are 2 folders created 

- 'test-results' - which has the .png, trace.zip and .webm files
- 'pw-results' - which has data, trace, and index.html file

Expected:

Playwright respects the config file outputFolder for every run to push html reporter results into.

Add any other details about the problem here.
When I initially gave just "html" as outputFolder, the video and snapshots were missing.

I don't understand a consistent way of generation of html reporter results. Please help!!

**Comment by pavelfeldman** [comment]
As per your config, `pw-results/html` will contain all the resources necessary to render the report. You can disregard the intermediate assets under test-results that this report was built off.

**Comment by dmallavarapu** [comment]
Thank you for the immediate response.

For testing, I deleted `test-results` folder and the report worked fine. Thanks for clarifying that. However `test-results` is the parent folder of all our results including other run results. Is there a way we can avoid this creation of intermediate assets under `test-results `? Why is playwright remembering '`test-results`', even if for the temp assets? 

Also, two weeks back when I gave the results outputFolder as just 'html' without a parent folder, the screenshot and video didn't work, they didn't get attached to the html. Once I started providing the outputFolder as `'test-results/html'`.

**Comment by pavelfeldman** [comment]
Playwright Test will store intermediate results under `test-results`, it thinks it owns this folder. If you point html reporter to `test-results/html`, those will clash. Playwright Test thinks it owns test-results, html report thinks it owns test-results/html, but they are nested!

**Comment by pavelfeldman** [comment]
> Why is playwright remembering 'test-results', even if for the temp assets?
That's because we want to make sure you have access to all those temp assets, regardless of whether you are using reporters or not. You can delete it if you don't need it. But if we delete it on CI, it would be considered data loss, and clients might use this data to troubleshoot.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
