### ISSUE TITLE
[Question] DRY way to create fixtures

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#14570]
say I have some typescript code like this:

```ts
type testFixtures = {
	modelBroadway : BroadwayModel.default,
	modelMediaPlayer : MediaPlayerModel.default,
};
const test = base.extend<testFixtures>({
	modelBroadway : async ({ page }, use) => {
		const model = new BroadwayModel.default(page.locator("body"));
		use(model);
	},
	modelMediaPlayer : async ({ page }, use) => {
		const model = new MediaPlayerModel.default(page.locator("body"));
		use(model);
	},
});
```

how would I make it so that I can create a function to return the fixture, so I don't have to copy and paste? i.e.
```ts
function GENERATE_FIXTURE (model) : returnType {
	return async ({ page }, use) => {
		const output = new model.default(page.locator("body"));
		use(output);
	};
}
```

What's the type for the values in the fixtures?

**Comment by aslushnikov** [comment]
@A-ZC-Lau you can just omit it - it'll be inferred. 

You can also parametrize `GENERATE_FIXTURE` if you'd like to:

```ts
import { test as base } from '@playwright/test';

type testFixtures = {
  modelBroadway: number,
  modelMediaPlayer: String,
};
const test = base.extend<testFixtures>({
  modelBroadway : GENERATE_FIXTURE<number>(10),
  modelMediaPlayer : GENERATE_FIXTURE<String>('foo'),
});

function GENERATE_FIXTURE<T>(value: T) {
  return async ({ }, use) => {
    use(value);
  };
}

test('foo', async ({ modelBroadway, modelMediaPlayer }) => {
  console.log(modelBroadway);
  console.log(modelMediaPlayer);
});
```

Does it work?

**Comment by A-ZC-Lau** [comment]
@aslushnikov that could work for this example.

But what's the type that the fixture uses? Just in case I need to access `page` and other properties in the future.

**Comment by A-ZC-Lau** [comment]
@aslushnikov I can't use that method because it makes `use` have an `any` type which I want to avoid.

Also, `T` becomes unknown so will have a `Type 'unknown' has no construct signatures` error

**Comment by aslushnikov** [comment]
@A-ZC-Lau All the types work properly for me for the snippet I pasted:

<img width="767" alt="image" src="https://user-images.githubusercontent.com/746130/172131024-a15a4a51-4fa0-4f8d-bf1f-4ee7d9c1014f.png">

Make sure you have a `testFixtures` type that you use later in `extend`:

```js
type testFixtures = {
  modelBroadway: number,
  modelMediaPlayer: String,
};
const test = base.extend<testFixtures>({ 
  ...
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by pavelfeldman** [comment]
I'm still not sure what you are trying to achieve. Could you provide a complete example with fixtures and usages and explain what is expected vs what is happening.

**Comment by pavelfeldman** [comment]
At this point it looks like a TypeScript question rather than Playwright one to me, would you agree?

**Comment by raulparada** [comment]
Gonna leave here what I came up regarding what I came looking for (_the type that the fixture uses_) in case it would help someone. I just wanted a way to split my fixtures to different files, and then compose them elsewhere. My TS game is awful and this might not even be a wise idea though:

```ts
import { test, PlaywrightTestArgs, PlaywrightWorkerArgs, Fixtures } from "@playwright/test";

// Playwright doesn't seem to expose this.
type KeyValue = { [key: string]: any };
export type TestFixtureValue<T extends KeyValue, W extends KeyValue = {}> = Fixtures<
  T,
  W,
  PlaywrightTestArgs,
  PlaywrightWorkerArgs
>;

interface XrayProperties {
  key: string;
  summary: string;
  requirements: string;
  description: string;
}

export type XrayFixtures = {
  xray: (annotations: Partial<XrayProperties>) => void;
};

export const XrayFixturesValues: TestFixtureValue<XrayFixtures> = {
  xray: async ({}, use, testInfo) => {
    const callback = (annotations: Partial<XrayProperties>) => {
      const { key, summary, requirements, description } = annotations;
      key && testInfo.annotations.push({ type: "test_key", description: key });
      summary && testInfo.annotations.push({ type: "test_summary", description: summary });
      requirements && testInfo.annotations.push({ type: "requirements", description: requirements });
      description && testInfo.annotations.push({ type: "test_description", description: description });
    };
    await use(callback);
  },
};

export const extendedTest = test.extend<{ inlineFixture: string } & XrayFixtures>({
  inlineFixture: async ({}, use) => {
    await use("foo");
  },
  ...XrayFixturesValues,
});
```

**Comment by Georgegriff** [comment]
Spent a bit of time trying to figure out how to build ontop of the previous solution to allow to for dependencies across base.extends.
You can't just do `TestFixtureValue<FixtureOne & FixtureTwo>` you end up with mismatched typing issues.
Instead, you could build a custom type to do that like so:

By introducing an additional custom parameter "D" the key changed being  adding `  D extends KeyValue = {},
` and `D & PlaywrightTestArgs`.

A rarer use case but it took me long enough to figure out the fixture types, that i think its worth a share.

```ts
import {
  test,
  Fixtures,
  PlaywrightTestArgs,
  PlaywrightWorkerArgs,
} from "@playwright/test";

type TInput = { one: number };
type TInput2 = { two: 2 };

type KeyValue = { [key: string]: any };

export type TestFixtureValue<
  T extends KeyValue,
  D extends KeyValue = {},
  W extends KeyValue = {}
> = Fixtures<T, W, D & PlaywrightTestArgs, PlaywrightWorkerArgs>;

const oneFixture: TestFixtureValue<TInput> = {
  one: async ({ browser }, use) => {
    await use(1);
  },
};

const twoFixture: TestFixtureValue<TInput2, TInput> = {
  two: async ({ one }, use) => {
    console.log("one from two", one);
    await use(2);
  },
};

const baseTest = test.extend<TInput>({
  ...oneFixture,
});

const myTest = baseTest.extend<TInput2>({
  ...twoFixture,
});
```

![image](https://user-images.githubusercontent.com/9056958/229911637-f4ca8df8-7587-4558-9009-654c11b518a2.png)

**Comment by reallyely** [comment]
Thanks for this, @Georgegriff . I was very close to this solution but I like where you arrived more. For posterity, like others in this thread, I wanted to build my tests to be modular, independent and encapsulated. I'm currently straddling PoMs and a more use-case/workflow oriented method of approaching my tests while organizing them according to my domain, this format allows me to pursue that.
