### ISSUE TITLE
How can I disable the extension after launching the browser and navigating to a URL?

### ISSUE THREAD

**Issue by Mosorathia** [microsoft/playwright#14576]
// Here i am launching browser with extension and navigating to a url....  Problem is that after url is opened, I want to disable AdBlocker extension and reload the page.. what is the way to do that using playwright?

```
Playwright playwright=Playwright.create();
BrowserType chromium = playwright.chromium();

String projectPath = System.getProperty("user.dir");
List<String> ext = new ArrayList<>();
ext.add("--disable-extensions-except=" + projectPath + "\\Extensions\\cfhdojbkjhnklbpkdaibdccddilifddb\\3.14_0");
ext.add("--load-extension=" + projectPath + "\\Extensions\\cfhdojbkjhnklbpkdaibdccddilifddb\\3.14_0");

BrowserContext browserContext = chromium.launchPersistentContext(Paths.get("user dir"),new BrowserType.LaunchPersistentContextOptions().setChannel("chrome").setArgs(ext).setHeadless(false));

Page page=browserContext.newPage();
page.navigate(url);

**// Here i want to disable extension before refreshing..**

`page.refresh()`

**Comment by aslushnikov** [comment]
> Problem is that after url is opened, I want to disable AdBlocker extension and reload the page.. what is the way to do that using playwright?

@Mosorathia There's no way to do this after the browser launch. Sorry for the inconvenience! Is this a testing or scraping scenario?

**Comment by Mosorathia** [comment]
It is a testing scenario.. I have to test a URL once with adblocker and then after disabling  adblocker and refreshing the page..

**Comment by aslushnikov** [comment]
The best I can suggest is launching the browser one more time without adblocker.

**Comment by Mosorathia** [comment]
That won't work here as the log which I want to test is fired only when the page is refreshed and not on the first time load on the browser..

**Comment by aslushnikov** [comment]
@Mosorathia maybe you can hack into the adblock background page to disable it.. but I can't think of much besides this

**Comment by Mosorathia** [comment]
My whole scenario of refresh is like it first checks local storage and based on that fires a log.. Is it possible that i launch a browser with extension, hit a url and get/save local storage data.. then relaunch browser without extension and set the local storage data which I got formerly?

**Comment by aslushnikov** [comment]
>  then relaunch browser without extension and set the local storage data which I got formerly?

@Mosorathia Yep, you can do this using the [storage state API](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state)

**Comment by pavelfeldman** [comment]
This feature is not supported and there are no immediate plans to implement it. Closing.
