### ISSUE TITLE
[Question] Does locators work across frame navigations?

### ISSUE THREAD

**Issue by inancgumus** [microsoft/playwright#14574]
A frame can navigate, and only the page document will change. Will the locator continue to work even after navigation then? What about page navigations?

**Comment by aslushnikov** [comment]
> Will the locator continue to work even after navigation then? What about page navigations?

@inancgumus yes, locators will work regardless or the navigations. Note that for a locator to point to an element inside an iframe, you should use [frame locators](https://playwright.dev/docs/api/class-framelocator):

```js
const locator = page.frameLocator('#my-frame').locator('text=Submit');
await locator.click();
```

To get most from locators, make sure to use [web-first assertions](https://playwright.dev/docs/release-notes#-web-first-assertions) as well!

**Comment by inancgumus** [comment]
Thanks, @aslushnikov! I read from the documentation that a locator belongs to a single frame. So wouldn't the frame go away when its page changes?

**Comment by aslushnikov** [comment]
> I read from the documentation that a locator belongs to a single frame. So wouldn't the frame go away when its page changes?

It will!

I feel like there's some confusion though; just to re-iterate: `locator` is not an exact element on the page, but rather a "rule" to retrieve the element. So for example the following interaction:

```js
await page.locator('button').click();
```

... will re-query locator to find the button it points to. No matter if there's a navigation going on, Playwright will wait until there's the button to click it.
