### ISSUE TITLE
[BUG] expect(locator).toHaveCount() throws expression: expected string, got object

### ISSUE THREAD

**Issue by kbrueckner** [microsoft/playwright#14577]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.13.2

**Code Snippet**

I was following the documentation:

```javascript
import { expect } from '@playwright/test';

// ...

const loc = page.locator('tr');
await expect(loc).toHaveCount(1);
```

**Describe the bug**

The tests throws:
locator._expect: expression: expected string, got object

**Comment by aslushnikov** [comment]
@kbrueckner the following works just fine for me:

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('foo', async ({ page }) => {
  await page.goto('https://example.com');
  await expect(page.locator('h1')).toHaveCount(1);
});
```

Can you try running this and see if it works for you too?

**Comment by kbrueckner** [comment]
That is actually a good point. I am not having the expect statement wrapped into test from playwright/test.
My setup is still based on jest as the runner. I suppose that is not working together?

**Comment by aslushnikov** [comment]
> I suppose that is not working together?

@kbrueckner yeah, no guarantees with jest. We don't test this setup at all; all our focus is at @playwright/test. 

I'll close this then; feel free to re-file if you think we can be helpful!
