### ISSUE TITLE
[Question] Nightly (Firefox) SEC_ERROR_UNKNOWN_ISSUER

### ISSUE THREAD

**Issue by oktayozkan0** [microsoft/playwright#14571]
When im trying navigate to a website, nightly gives an error like this:

```
Someone could be trying to impersonate the site and you should not continue.
 
Websites prove their identity via certificates. Nightly does not trust www.holidaygems.co.uk because its certificate issuer is unknown, the certificate is self-signed, or the server is not sending the correct intermediate certificates.
 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```
How can i solve this issue?

**Comment by aslushnikov** [comment]
@oktayozkan0 Try using `https://playwright.dev/docs/api/class-testoptions#test-options-ignore-https-errors` option in your test

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
