### ISSUE TITLE
[Question] How can I update window obj?

### ISSUE THREAD

**Issue by ooo2003003v2** [microsoft/playwright#14575]
Hello there. 

I'm trying to update the window obj in beforeEach but I cannot find a right way to do it. I've tried page.evaluate and page.  
 page.evaluateHandle but it doesnt seem to work. Could anyone help me???

```ts
const isMock = true;

const windowHandle = await this.workspace.page.evaluateHandle(() => window);
windowHandle.__mock = isMock ;
// In browser console shows undefined

await this.workspace.page.evaluate((isMock) => window.__mock = isMock, isMock);
// In browser console shows undefined

await this.workspace.page.evaluate(`window.__mock = 'true'`)
// In browser console shows undefined
```

**Comment by aslushnikov** [comment]
@ooo2003003v2 The following works just fine for me:

```ts
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
const page = await browser.newPage();
await page.evaluate(mockValue => {
  window.__mock = mockValue;
}, 'this is my mock value');
console.log(await page.evaluate(() => window.__mock));
await browser.close();
```

To double-check with devtools, you can:
1. comment out `browser.close()`
2. change `chromium.launch()` to `chromium.launch({ headless: fase})`
3. Run script, open devtools and make sure that `window.__mock` is initialized properly

If things don't work for you, please re-file a new issue with a good repro that illustrates things that don't work for you!
