### ISSUE TITLE
[BUG] Html report does not mark report tree correctly if assertion is missing await

### ISSUE THREAD

**Issue by gegoncalves** [microsoft/playwright#14583]
**Context:**
- Playwright Version: 1.22
- Operating System: Windows
- Node.js version: v16.14.1
- Browser: All
- Extra: Using custom fixtures and POM

**Describe the bug**

1. Using `test.step()` , Html report does not mark with X failed actions that are nested. In this case is just 2 levels but with more levels all of them has a green mark, excluding the root action

<img src="https://user-images.githubusercontent.com/101710983/171648302-b28519cc-a934-4743-b5ac-d7722a77f935.png" alt="drawing" width="350"/>

2. If any steps fails after the first one succeed, the report put the step inside of the last step action which succeeded . Ex: Step one pass and step 2 fail. The report the step 2 inside of the last action of the step 1

<img src="https://user-images.githubusercontent.com/101710983/171652469-18a4ba47-bf6e-46be-9a5e-5e7f7e09b7dc.png" alt="drawing" width="350"/>

<img src="https://user-images.githubusercontent.com/101710983/171651435-7ca56480-4ad9-4ed4-abe4-fc7d2c495151.png" alt="drawing" width="350"/>

**Code Snippet**

```js
test.describe('Report check', () => {

    test("Using custom fixtures:", async ({ loginPage, carPage }) => {
        await test.step('Test Login', async () => {
            await loginPage.loginUser();
        });

        await test.step('Test 1', async () => {
            await carPage.navigateToLibrary();
            const modal = await carPage.addElement();
            expect(modal).toBeVisible();

            const active = await carPage.isProcessTabActive();
            expect(active).toHaveAttribute('class', 'active');

            const stepListSize = await carPage.getProcessInfoList();
            expect(stepListSize).not.toBe(0);
        });


        await test.step('Test 2', async () => {
            await carPage.navigateToLibrary();
            await carPage.addCar();

            const active = await carPage.isPerformanceTabActive();
            expect(active).toHaveAttribute('class', 'inactive');
        });
    })
})
```

Not using POM the html report goes ok

````ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
    await test.step('Test 1 Not fail', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('Playwright');
    });

    await test.step('Test 2 pass', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('Playwright');
    });

    await test.step('Test 3 should fail', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('blabla');
    });
});
````

**Comment by gegoncalves** [comment]
@aslushnikov  I found what is the issue after trying many different things. 
It is just because of the `await ` missing in the assertion. Anything that follows the assertion goes inside the node in the html report

Try this:
````ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
    await test.step('Test 1 Not fail', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        expect(title).toHaveText('Playwright'); //missing `await`. It is going to put the next step inside of the assertion node
    });

    await test.step('Test 2 pass', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('Playwright');
    });

    await test.step('Test 3 should fail', async () => {
        await page.goto('https://playwright.dev/');
        const title = page.locator('.navbar__inner .navbar__title');
        await expect(title).toHaveText('blabla');
    });
});
````

<img width="522" alt="image" src="https://user-images.githubusercontent.com/101710983/171889846-54cc76f2-0998-4885-8d01-d19e343f6145.png">

**Comment by aslushnikov** [comment]
> It is just because of the await missing in the assertion. Anything that follows the assertion goes inside the node in the html report.

@gegoncalves yeah, you cannot miss awaits! You should probably use something like [no-floating-promises](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md) eslint rule to guard against these in your code.

**Comment by gegoncalves** [comment]
Thank you gonna close it and sorry for the confusion
