### ISSUE TITLE
Playwright proxy IP address

### ISSUE THREAD

**Issue by IuliiaBondarieva** [microsoft/playwright#14585]
**Context:**
- Playwright Version: @playwright/test@1.22.0
- Operating System: Mac
- Node.js version: v16.13.2
- Browser: Chromium

We have a problem to access our e2e tests 'cause it seems to be not whitelisted from one of VPNs.
We are also using whitelisted VPN at work, but it still doesn't solve the problem.

If I try to run playwright locally in chrome browser it shows the same IP as my local chrome browser. But the same page I can open by local Chrome browser and can't reach by running headless chrome binary with Playwright.

After sending test requests to server we find out that there is some kind of proxy with another IP as expected in between.

```
52.114.75.216
Amsterdam, North Holland, Netherlands
Company | Microsoft Corporation

```

We need help to understand how then playwright is running and wich IP range is it using?

**Comment by aslushnikov** [comment]
@IuliiaBondarieva Playwright doesn't do anything special - it just controls a browser. However, headless browser has a different user agent, reports a different set of cookies, and so on - so servers can rely on these hints and change behavior.

First of all, I'd recommend trying to run headed version of chrome browser, and alternatively to try running [stable chrome channel](https://playwright.dev/docs/browsers).

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
