### ISSUE TITLE
[Question] I have a question about Page.

### ISSUE THREAD

**Issue by ooo2003003v2** [microsoft/playwright#14582]
Hello there. 

Currently I am using browserContext.newPage() to create a page. But I came across there's another way to create page which browser.newPage(). Could anyone tell me what's the difference between these two? Thank you.

**Comment by aslushnikov** [comment]
> Could anyone tell me what's the difference between these two?

@ooo2003003v2 the `browser.newPage()` is a shortcut for the following:

```js
const context = browser.newContext();
const page = context.newPage(;
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
