### ISSUE TITLE
[BUG] TypeError: Cannot read properties of null (reading 'status')

### ISSUE THREAD

**Issue by ritikkumarsahu** [microsoft/playwright#14580]
**Context:**
- Playwright Version: 1.21.1
- Operating System: Windows
- Node.js version: v16.13.2
- Browser: Firefox
- Extra: using proxy and incognito mode

![image](https://user-images.githubusercontent.com/50456414/171625816-a3ce3137-d924-4f61-aeff-baccd7679eb9.png)

**Code Snippet**

```javascript
async function prepareBrowser(proxies) {
    const res = await getIpDetails(proxies);
    const browser = await playwright.firefox.launch({
        headless: false, // Show the browser. 
        firefoxUserPrefs: {
            "media.peerconnection.enabled" : false
        },
        args: ['--start-maximized','--start-in-incognito']
    });
    const context = await browser.newContext({
        timezoneId: res.timezone,
        locale: 'en-'+res.country,
        proxy: {
            server: `http://${proxies.proxy_address}:${proxies.ports.http}`,
            username: proxies.username,
            password: proxies.password
        },
    });

    return context;
}
  const browser = await prepareBrowser(proxies[0]);
  let page = await browser.newPage();
  
 await page.goto('https://example.com/')
 await page.goto('https://example2.com/') // Error occurs here upon navigation
 
})();
```

**Describe the bug**

Whenever page is navigated to some other URL using page.goto(URL),  This error (see attached image)  occurs randomly, I came across this bug several times.
    const isRedirected = response.status() >= 300 && response.status() <= 399;
                                  ^
TypeError: Cannot read properties of null (reading 'status')
    at FFNetworkManager._onRequestFinished (D:\Projects\path\node_modules\playwright-core\lib\server\firefox\ffNetworkManager.js:131:35)
    at FFSession.emit (node:events:390:28)
    at D:\Projects\path\node_modules\playwright-core\lib\server\firefox\ffConnection.js:247:41

**Comment by aslushnikov** [comment]
@ritikkumarsahu does it happen for you without proxies? I tried a few snippets but i failed to repro this.

Any chance you can build a repro that I can actually run locally to debug it?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by 0x0480** [comment]
```
C:\Users\xxxxxxxxAppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffNetworkManager.js:110
    response.setTransferSize(event.transferSize);
             ^

TypeError: Cannot read properties of null (reading 'setTransferSize')
    at FFNetworkManager._onRequestFinished (C:\Users\xxxxxxxx\AppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffNetworkManager.js:110:14)
    at FFSession.emit (node:events:518:28)
    at C:\Users\xxxxxxxxAppData\Local\ms-playwright-go\1.42.1\package\lib\server\firefox\ffConnection.js:154:41

Node.js v20.11.0
```

It randomly occurred several times.
