### ISSUE TITLE
Not able to run test with npx playwright test, error First argument must use the object destructuring pattern: _a

### ISSUE THREAD

**Issue by ramnutheti** [microsoft/playwright#14590]
**Context:**
- Playwright Version: [1.22.1]
- Operating System: [e.g. Windows, Linux]
- Node.js version: [e.g. 16.4]
- Browser: [ Chromium]
- Extra: [Microsoft Visual Studio Professional 2022 (64-bit) Version 17.0.5]

System:
    OS: Windows 10 10.0.19044
    Memory: 4.33 GB / 15.73 GB
  Binaries:
    Node: 16.14.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.3.1 - C:\Program Files\nodejs\npm.CMD

```js
test.describe('Create jobs of different pipeline', () => {
    test('user should be able to create job for running Databricks notebook', async ({ page }) => {
        await page.goto('/');
        const jobsPage = new JobsPage(page);
        const homePage = new HomePage(page);
        await homePage.ClickJobsBtn();
        await jobsPage.ClickCreateJobBtn();
        const createJob = new CreateJobsPage(page);
        const testName = 'AJob' + Math.random().toString().substr(2,6);
        await createJob.CreateJobRunDatabricksNotebook(testName, testName, 'Job', '7159 - pl_job_run_databricks_notebook', 'monthly', 'test/jobpath')
        await createJob.ClickSaveBtn();
        await page.waitForSelector('id=jobSearch')
        const jobTitle = await page.innerText('[class=p-card-title]')
        await expect(jobTitle).toBe('Jobs');
    })
    });
```

When I run the above test using npx playwright test I get the below error , how ever if I run it through file name    npx playwright test CreateJobTests.spec.ts  the test works fine.

```
Error: First argument must use the object destructuring pattern: _a
  defined at Tests\CreateJobTests.spec.ts:2:5
    at errorWithLocations (C:\hpajobsysautomatedtests\hpa-jobsys-automated-tests\node_modules\@playwright\test\lib\fixtures.js:453:10)
    at innerFixtureParameterNames (C:\hpajobsysautomatedtests\hpa-jobsys-automated-tests\node_modules\@playwright\test\lib\fixtures.js:391:81)
```

Thanks,
Ram

**Comment by ramnutheti** [comment]
I have 4 test files classified based on there functionality and all of them under tests folder 

![image](https://user-images.githubusercontent.com/98409766/171871012-d7eb6f04-a581-4839-a5ab-e565b88e7d88.png)

**Comment by aslushnikov** [comment]
@ramnutheti ok, could you please create a repository with the test files that reproduces the issue so that we could debug it locally?

**Comment by ramnutheti** [comment]
@aslushnikov I figured out the issue and now my command works , I was missing testMatch:'*spec.ts' in playwright.config.ts

**Comment by ramnutheti** [comment]
Thanks a lot for the support

**Comment by navidshad** [comment]
> @aslushnikov I figured out the issue and now my command works , I was missing testMatch:'*spec.ts' in playwright.config.ts

It fixed my problem as well, but how really you find it :D? the error wasn't clear and wasn't addressed it

**Comment by ShaMan123** [comment]
> I was missing testMatch:'*spec.ts' in playwright.config.ts

still getting this, destructing the param does fix it but it is strange

**Comment by ppushpanayagam** [comment]
I had similar issue like below:

<img width="953" alt="Screenshot 2024-01-06 at 08 59 08" src="https://github.com/microsoft/playwright/assets/23029950/c97df504-7d83-468d-b628-f8629cfc7c9a">

but I was able to resolve this by enclosing **page** with **{page}** 

<img width="500" alt="Screenshot 2024-01-06 at 09 01 51" src="https://github.com/microsoft/playwright/assets/23029950/19f5736f-8a81-4320-b22e-40edd3bf387e">

**Comment by CallmeJooj** [comment]
Solved this by using empty brackets as the argument
```test("Test", async ({ }, testInfo) => { ... })```

**Comment by jonnysamps** [comment]
A requirement to use destructuring is not helpful. It prevents user from create generic fixture functions and such. This should be a linting rule not a hard requirement.

**Comment by osdiab** [comment]
@jonnysamps As a user I agree that the syntax is counterintuitive and doesn't agree with common lint rules, but [it seems that there are deeper reasons for this](https://github.com/microsoft/playwright/issues/21566#issuecomment-1464858235), and this opinion has been [voiced](https://github.com/microsoft/playwright/issues/21566#issuecomment-1464858235) [many](https://github.com/microsoft/playwright/issues/23600) [times](https://github.com/microsoft/playwright/issues/21566) [in other](https://github.com/microsoft/playwright/issues/17043) [issues](https://github.com/microsoft/playwright/issues/13784). Ultimately there's a quick and easy workaround and so practically speaking while it's a counterintuitive API choice, it does not prevent users from doing things and it doesn't appear like it could simply be a linting rule based on how Playwright works.

**Comment by jonnysamps** [comment]
@osdiab I appreciate the response. Ya, it looks like they use the function destructured args as a means of inferring required dependencies for the test/hooks. That makes me feel a bit better about it.
