### ISSUE TITLE
[BUG] Chromium removing origin header when POST for login token

### ISSUE THREAD

**Issue by almiller9** [microsoft/playwright#14597]
**Context:**
- Playwright Version: [1.22.2]
- Operating System: [ Windows]
- Node.js version: [e.g. 10.7.0]
- Browser: [Chromium]
- Extra: [Doesnt happen in Webkit or Firefox]

**Code Snippet**

```js
    const [popup] = await Promise.all([
        page.waitForEvent('popup'),
        //page.waitForNavigation({ url: 'https://login.microsoftonline.com/**' }),
        page.locator('text=GuestLogin >> button').click()
    ]);
  
    // Click text=someone@example.com
    await popup.locator('text=someone@example.com').click();
    // Fill [aria-label="someone\@example\.com"]
    await popup.locator('[aria-label="someone\\@example\\.com"]').fill('user@host.com');

      // Click text=Next
    await Promise.all([
        popup.waitForNavigation(/*{ url: 'https://login.microsoftonline.com/**' }*/),
        popup.locator('text=Next').click()
    ]);

   // Fill input[name="passwd"]
    await popup.pause();
    await popup.locator('id=i0118').click({ force: true });
    await popup.locator('id=i0118').fill('password');

    // Click text=Sign in
    await Promise.all([
      popup.waitForNavigation(/*{ url: 'https://login.microsoftonline.com/**' }*/),
      popup.locator('text=Sign in').click()
    ]);

    // Click text=Yes
    await Promise.all([
      popup.waitForNavigation(/*{ url: 'https://localhost/login' }*/),
      popup.locator('text=Yes').click()
    ]);


  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Our application uses Microsoft to create a token for sign on by calling a token endpoint 
POST https://login.microsoftonline.com/***/oauth2/v2.0/token)

In desktop version of chrome and all other Playwright browsers, below header is created. 
Origin: https://test-website.com

However it is missing in Playwright chromium when trying to run tests. This causes the token endpoint to return 400 and never log in.

**Comment by aslushnikov** [comment]
@almiller9 could you please create a small reproduction script that I can run locally to see this for myself?

Also, note that if you use `--disable-web-security` flag in Chrome, than `origin` header will not be sent.

**Comment by almiller9** [comment]
Removing --disable-web-security fixed my issue.
