### ISSUE TITLE
[BUG] Shadow DOM - DOM.scrollInToViewIfNeeded wasn't found

### ISSUE THREAD

**Issue by Georgegriff** [microsoft/playwright#1459]
**Context:**
- Playwright Version:0.11.1
- Operating System:MAC
- Extra: Targeted my chrome version 

I'm not sure if should raise this with Chrome or not, but i'm finding that if I changed my executable to the MAC OC version of Chrome, like so:
`    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' `
 and try to click an element in shadow dom i get the error in the stack trace below.

Why do i change the exe like this? To work around this annoying MAC OS warning:
![image](https://user-images.githubusercontent.com/9056958/77225798-93e22c00-6b6a-11ea-8cec-40260928ff00.png)

I get the following error:
```
e:21887) UnhandledPromiseRejectionWarning: Error: Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found

```

**Code Snippet**

This snippet runs chrome (not headlessly so we can access downloads page to demo the problem) and tries to click the search bar on chrome

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const playwright = require("playwright");

(async () => {
const browser = await playwright["chromium"].launch({
    devtools: true,
    headless: false,
    executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
    
});
const context = await browser.newContext();
const page = await context.newPage();
await page.goto("chrome://downloads");
const searchButton = await page.waitFor(()=> {
    return document.querySelector("body > downloads-manager")
    .shadowRoot.querySelector("#toolbar")
    .shadowRoot.querySelector("#toolbar")
    .shadowRoot.querySelector("#search")
}, { timeout: 3000 });
await searchButton.click();

})();
```

**Describe the bug**

Stack trace
```
e:21887) UnhandledPromiseRejectionWarning: Error: Protocol error (DOM.scrollIntoViewIfNeeded): 'DOM.scrollIntoViewIfNeeded' wasn't found
    at /Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/chromium/crConnection.js:121:63
    at new Promise (<anonymous>)
    at CRSession.send (/Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/chromium/crConnection.js:120:16)
    at CRPage.scrollRectIntoViewIfNeeded (/Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/chromium/crPage.js:413:28)
    at ElementHandle._scrollRectIntoViewIfNeeded (/Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/dom.js:148:36)
    at ElementHandle._performPointerAction (/Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/dom.js:212:20)
    at ElementHandle.click (/Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/node_modules/playwright-core/lib/dom.js:225:21)
    at /Users/george.griffithsibm.com/Code/CodeceptjsShadowDom/shadow-dom-click.js:19:10
(node:21887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by Georgegriff** [comment]
This may not be an issue with Playwright but i wanted to raise it here incase someone else knew a better place to raise it

**Comment by arjun27** [comment]
Thanks @georgegriff. Playwright depends on the bleeding edge of Chromium, and some of those dependencies are not available in Chrome stable. I would recommend Chrome Canary if you want to use Chrome instead of Chromium. A quick way to verify is to compare the version numbers by running `chrome://version` in the different browsers.

I'm curious to know more about the incoming network connections dialog box. What version of macOS are you on?

**Comment by arjun27** [comment]
Closing this as the issue reported can be fixed by using Chrome Canary. Feel free to reopen if I missed something
