### ISSUE TITLE
[Question] Can we intercept and modify API response with Playwright in .NET version

### ISSUE THREAD

**Issue by davidhprotective** [microsoft/playwright#14593]
I went through this documentation here: https://playwright.dev/dotnet/docs/network and checked the same link for the Node.js version. I noticed that "Modify responses" is missing in the .NET version. 

First, just so that I understand the feature correctly, is that what intercepting API response and modifying it with whatever we would like to display, such as mocking a server error?

Second, was that feature intentionally omitted in .NET version? Is there an alternative?

Our goal is to write tests where we modify the success response to be a 500 server error and validate on the browser that it displays "Server Error" message.

Thanks!

**Comment by mxschmitt** [comment]
In version 1.23 this feature gets released for Playwright for .NET. It should get released in 1-2 weeks.

**Comment by mxschmitt** [comment]
> First, just so that I understand the feature correctly, is that what intercepting API response and modifying it with whatever we would like to display, such as mocking a server error?

This is possible today see here: https://playwright.dev/dotnet/docs/network#handle-requests

**Comment by davidhprotective** [comment]
> 
Thanks.

Then, can you please help me understand the difference between handling requests vs mocking/modifying API responses?

Thanks.

**Comment by davidhprotective** [comment]
Ok thanks. Then I am really looking for the difference between handling requests vs modifying responses, one of which is not yet available in .NET version.
