### ISSUE TITLE
[Question] Time out on CI

### ISSUE THREAD

**Issue by rommels-pageup** [microsoft/playwright#14615]
does anyone have an experience on this kind of issue? where on my CI the playwright is timing out, as usual everything works on my local. 

note that:
npm run  is executed before the playwright test is called .

![image](https://user-images.githubusercontent.com/89371423/171795965-ba62fcae-81ea-4d18-aebc-ef775d9d29e5.png)

tia... :)

**Comment by aslushnikov** [comment]
@rommels-pageup there might be lots of different issues that manifest themselves as a timeout on CI:

- your test uses a URL that is inaccessible on CI. To debug this, use [Playwright Tracing](https://playwright.dev/docs/api/class-tracing).
- your CI hardware is over-saturated, so everything is just very slow there. Make sure not to run with too many workers

It's hard to recommend anything beyond this given how limited information is. Please re-file if you think we can be helpful!
