### ISSUE TITLE
[BUG] Playwright can not find test by name via command line (-g)

### ISSUE THREAD

**Issue by ferrykranenburgcw** [microsoft/playwright#14618]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 16
- Browser: Chrome

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
npx playwright test -g "add a todo item"
```

**Describe the bug**

It look like the `-g` command line option does not work correctly any more. It does not find tests with all the given words in it. Except it looks for tests that include one or more words.

**Comment by aslushnikov** [comment]
> It look like the -g command line option does not work correctly any more.

@ferrykranenburgcw I experimented with multiple Playwright versions (1.18, 1.20, 1.22), and no matter what I do, I always get a single test to be run.

Here's my test suite:

```ts
// a.spec.ts
import { test } from '@playwright/test';

test('foo bar', async ({}) => {});
test('for bar baz', async ({}) => {});
```

This is the command I run:

```bash
aslushnikov:~/tmp$ npx playwright test -g 'foo bar'

Running 1 test using 1 worker

  ✓  a.spec.ts:3:1 › foo bar (2ms)


  1 passed (246ms)
```

So is this a regression?

**Comment by ferrykranenburgcw** [comment]
After running `npx playwright install` it works correctly now. I don't know what happened but it works. Thanks.
