### ISSUE TITLE
Error on GH action when running playwright tests

### ISSUE THREAD

**Issue by lefado** [microsoft/playwright#14617]
I am using your package in order to run playwright tests on Github Actions. However, I am getting error
```
> bash -c '. ./load_dotenv.sh; environment=DEV npx playwright test tests/'

require(...).addListFilesCommand is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! e2e-playwright@1.0.0 e2e-dev: `bash -c '. ./load_dotenv.sh; environment=DEV npx playwright test tests/'`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the e2e-playwright@1.0.0 e2e-dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-06-03T08_46_39_9[16](https://github.com/borecz/GlobalCarsTest/runs/6722892863?check_suite_focus=true#step:5:17)Z-debug.log
Error: Process completed with exit code 1.
```

Error is not intuitive to debug, since code line causing error is not being displayed. I wonder if you have seen this issue before.

Thanks in advance

**Comment by aslushnikov** [comment]
> Error is not intuitive to debug, since code line causing error is not being displayed. I wonder if you have seen this issue before.

@lefado no, I've never seen it before. Any more details to help us debug it?

**Comment by pavelfeldman** [comment]
> require(...).addListFilesCommand is not a function

This suggests that you have conflicting versions of  `playwright` (or `playwright-core`) and `@playwright/test`. Make sure you either use one or the other and run `npm ci`.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
