### ISSUE TITLE
[BUG] Support for vite plugins and svelte preprocess

### ISSUE THREAD

**Issue by bhvngt** [microsoft/playwright#14621]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.22
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] 18.2
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment] svelte-kit, vite, unocss

## System:
 - OS: macOS 12.4
 - Memory: 623.73 MB / 32.00 GB
## Binaries:
 - Node: 18.2.0 - ~/Library/Caches/fnm_multishells/1664_1654253939618/bin/node
 - npm: 8.9.0 - ~/Library/Caches/fnm_multishells/1664_1654253939618/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 
**Code Snippet**
```
use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,

    ctViteConfig: {
      resolve: {
        alias: {
          '$lib': resolve(__dirname, './src/lib'),
        }
      },
      plugins: [
        UnoCss({ extractors: [extractorSvelte] }),
      ]
    },
```

```playwright/index.ts
// Import styles, initialize component theme here.
import "@unocss/reset/tailwind.css";
import "uno.css";
export {}
```
**Describe the bug**
I am testing playwright component testing with my `svelte-kit` setup. I also use [unocss](https://github.com/unocss/unocss) as a `css library`. To make it work with svelte, I need to add it as a vite plugin. I have added the plugin configuration to  `playwright-ct.config.ts` and have imported the library to my `playwright/index.ts`. However, after doing that I am getting following error

```
Running 1 test using 1 worker

vite v2.9.9 building for production...
✓ 3 modules transformed.
[rollup-plugin-dynamic-import-variables] Unexpected token (1:0)
file: <project-root>/apps/web/src/lib/auth/Signup.svelte:1:0

SyntaxError: Unexpected token (1:0)

    at Parser.pp$4.raise (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:19844:13)
    at Parser.pp$9.unexpected (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:17138:8)
    at Parser.pp$5.parseExprAtom (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:19219:10)
    at Parser.pp$5.parseExprSubscripts (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:19011:19)
    at Parser.pp$5.parseMaybeUnary (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:18977:17)
    at Parser.pp$5.parseExprOps (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:18904:19)
    at Parser.pp$5.parseMaybeConditional (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:18887:19)
    at Parser.pp$5.parseMaybeAssign (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:18854:19)
    at Parser.pp$5.parseExpression (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:18817:19)
    at Parser.pp$8.parseStatement (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:17328:45)
    at Parser.pp$8.parseTopLevel (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:17195:21)
    at Parser.parse (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:16967:15)
    at Function.parse (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:17017:35)
    at Graph.contextParse (<project-root>/common/temp/node_modules/.pnpm/rollup@2.75.5/node_modules/rollup/dist/shared/rollup.js:23121:38)
    at Object.transform (<project-root>/common/temp/node_modules/.pnpm/vite@2.9.9/node_modules/vite/dist/node/chunks/dep-59dc6e00.js:19826:27)

TypeError: Cannot read properties of undefined (reading 'httpServer')
```

Vite aliases works without any issue. I start getting errors only once I add vite plugins. I have also tried adding some other vite supported plugin such as [rollup-plugin-visualizer](https://github.com/btd/rollup-plugin-visualizer). However, it also faces the same error. They all work well in my current sveltekit setup. 

### Add any other details about the problem here.

Likewise, I have few configuration done using [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess). Can I configure  that in my `playwright-ct config`?

**Comment by pavelfeldman** [comment]
When you specify Vite plugins, you take over configuring plugins, all of them. It means that we won't be setting the `svelte()` plugin for you anymore. Try adding `svelte()` from `@sveltejs/vite-plugin-svelte` as the first item of the plugin list.

**Comment by pavelfeldman** [comment]
> Likewise, I have few configuration done using [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess). Can I configure that in my playwright-ct config?

I'm not familiar with it, but how do you integrate it with vite/rollup today? I would imagine that a Vite plugin could do that as well.

**Comment by bhvngt** [comment]
> When you specify Vite plugins, you take over configuring plugins, all of them. It means that we won't be setting the `svelte()` plugin for you anymore. Try adding `svelte()` from `@sveltejs/vite-plugin-svelte` as the first item of the plugin list.

This worked like a charm. 

> > Likewise, I have few configuration done using [svelte-preprocess](https://github.com/sveltejs/svelte-preprocess). Can I configure that in my playwright-ct config?
> 
> I'm not familiar with it, but how do you integrate it with vite/rollup today? I would imagine that a Vite plugin could do that as well.

You are right. Vite plugin can do this for me. Interestingly, I did not had to do anything. Apparently, picked up my `preprocess` config from `svelte.config.ts`. 

Thanks a ton @pavelfeldman.

**Comment by Uninen** [comment]
I had this same problem (`undefined (reading 'httpServer')`) but it was due using mount wrong with Vue. (The examples in the docs only show React syntax, only place where the Vue syntax is shown is [this FAQ ticket](https://github.com/microsoft/playwright/issues/14298). 

However, I also use Vite plugins and the component doesn't seem to mount at all. My setup works with a simple component but fails with an actual one that uses for example imports provided by AutoImport plugin.


Here's my config:

```
    ctViteConfig: {
      plugins: [
        vue(),
        AutoImport({
          imports: [
            'vue',
            'vue-router',
            '@vueuse/head',
            'pinia',
            {
              '@/store': ['useStore'],
            },
          ],
          dts: 'src/auto-imports.d.ts',
          eslintrc: {
            enabled: true,
          },
        }),
        Components({
          dirs: ['src/components'],
          extensions: ['vue'],
        }),
      ],
      resolve: {
        alias: {
          '@': resolve(__dirname, './src'),
        },
      },
    },
```

and component source: 

```
<template>
  <h2 class="!mt-0">{{ props.msg }}</h2>
  <button class="px-3 py-2 bg-white border border-gray-300 rounded-md shadow" @click="increment">
    count is: {{ count }}
  </button>
  <p>Edit <code>components/HelloWorld.vue</code> to test hot module replacement.</p>
</template>

<script setup lang="ts">
// useStore, and computed are automatically imported. See vite.config.ts for details.
const store = useStore()
const count = computed(() => store.count)
const props = defineProps<{
  msg: string
  optionalProp?: number
}>()

function increment() {
  store.increment()
}
</script>
```

**Comment by pavelfeldman** [comment]
@[Uninen](https://github.com/Uninen) could you file a separate ticked w/ a repro I could try? This ticket was about Svelte and is already closed. Btw, this would be a non-JSX syntax example: https://github.com/microsoft/playwright/blob/main/tests/components/ct-vue-cli/src/notation-vue.spec.ts

**Comment by Uninen** [comment]
I think I found the root issue which is that I need Vue plugins for my component to work and adding those is not currently possible with the current implementation of `mount`. Here's a related comment: https://github.com/microsoft/playwright/issues/14416#issuecomment-1146062955 and here is a PR that demonstrates the problem with a [working](https://github.com/Uninen/vite-ts-tailwind-starter/pull/218/files#diff-5d87e042c06bd4c54898d00ea245377702dbb3d663704f9cb2e740d371078871) and [non-working](https://github.com/Uninen/vite-ts-tailwind-starter/pull/218/files#diff-e17ea97189bf2c22f00b4906c6ccd156a96060cc8fdeccd3a4ee23bfa2a758ad) component: https://github.com/Uninen/vite-ts-tailwind-starter/pull/218
