### ISSUE TITLE
[Question] How to force the download of certain files? XML Files are not triggering download but opening directly on browser.

### ISSUE THREAD

**Issue by casmeiron** [microsoft/playwright#14626]
Hi guys,

I have to download several kinds of files with playwright, and all it's working as I expected but XML.
When I click on some link that's linking to a XML file, the playwright is not handling it like it handles the other types. ( I call page.waitForDownload and wait till the path is returned).

I suspect it's rendering the XML into the window instead.

Is it possible to force playwright (Chromium) to download all files, whatever it is?

**Comment by aslushnikov** [comment]
@casmeiron if you just want to download XML files, you can easily do it like this:

```js
import { chromium } from '@playwright/test';

const browser = await chromium.launch({
  channel: 'chrome',
});

const context = await browser.newContext();
const page = await context.newPage();
const response = await page.goto('https://www.w3schools.com/xml/note.xml');
console.log(await response.text());
await browser.close();
```

Alternatively, you can use [response interception](https://playwright.dev/docs/release-notes#response-interception) to inject the `content-disposition` header to the response.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
