### ISSUE TITLE
[Feature] Allow request interception chaining (was 'based on request method')

### ISSUE THREAD

**Issue by purepear** [microsoft/playwright#14625]
Currently `page.route(url, handler, options)`/`browserContext.route(url, handler, options)` intercept routes based on url alone. It would be great if we have the ability to intercept based on any request properties like `method`, `header`, etc.

## Use case
A use case would be the common REST scenario where we want to intercept both `GET /items` and `POST /items`. 

Very simplified example:
```js
test('items', async ({ page }) => {
  // Intercept GET /api/items
  await page.route('/api/items', route => route.fulfill({ body: JSON.stringify([{ id: 1, name: 'Item 1' }]) }))
  
  // Intercept POST /api/items
  await page.route('/api/items', route => route.fulfill({ body: JSON.stringify({ id: 2, name: 'Item 2' }) }))
  
  await page.goto('/items')
  //  expect "Item 1" to be in the list
  
  await page.click('role=button[name="New item"]')
  // expect "Item 2" to be created in the list
})
```

The "matcher"(`url<string|RegExp|function(URL):boolean>`) doesn't allow for any matching on the request itself - only the request url. 
The "response"(`handler<function(Route, Request)>`) doesn't allow us to "skip" to the next interceptor - as the comment says in the source code `// There is no chaining, first handler wins.`. 

## Existing workarounds

1. Add single interceptor with conditional handler:

```js
await page.route('/api/items', (route, request) => { 
  if (request.method() === 'GET') {
    return route.fulfill({ body: JSON.stringify([{ id: 1, name: 'Item 1' }]) }) 
  } 
  
  if (request.method() === 'POST') {
    return route.fulfill({ body: JSON.stringify({ id: 2, name: 'Item 2' })
  } 
  
  return route.continue()
})
```
While this is enough in some cases, it's not very atomic and reusable. My idea is to make these a bit more generic and use them in fixtures - making sure that i can easily target just the request i need. Also, the idea of having the matching logic in the handler instead of the matcher just seems wrong.

2. Use `options.times` and order the interceptors based on their runtime execution. This seems very fragile and really not ideal.

## Proposal
Even though the contribution guide says "Expose as little information as needed. When in doubt, don’t expose new information.", i feel like we should have an escape hatch in the "matcher" function. Two options:
* Non-breaking change: adding the request as a second parameter to the url function:
   `url<string|RegExp|function(URL, request):boolean>`
   Not the best API but that's the price of non-breaking i guess.
* Breaking change: replacing the URL param with the request param in the url function:
    `url<string|RegExp|function(request):boolean>`
    This seems like a very robust and flexible way of route matching but it does break BC.

It's a bit unfortunate that we can't reuse the standard glob/regex url matching when we use the function. 
This is how i imagine it could look like:

```js
await page.route(
  (url, request) => request.method() === 'GET' && minimatch('/api/items', url.toSting()), 
  route => route.fulfill({ body: JSON.stringify([{ id: 1, name: 'Item 1' }]) }) 
)

await page.route(
  (url, request) => request.method() === 'POST' && minimatch('/api/items', url.toSting()), 
  route => route.fulfill({ body: JSON.stringify({ id: 2, name: 'Item 2' })
)
```

I think that having a convenient way to match by method(in addition to url) would be helpful in a lot of situations. 
What do you guys think? Do you have other APIs in mind to achieve this or do you think the current workaround methods are good enough?

**Comment by purepear** [comment]
Another option: 
* Non-breaking change: adding `options.method`

**Comment by pavelfeldman** [comment]
I find the snippet in the proposal to be less readable than the original one - two callbacks per call are harder to work with. Options.method can be added, but I'd like to better understand the exact use cases it addresses.

**Comment by purepear** [comment]
Hi @pavelfeldman, the current use case we have is: we have a test suite that entirely mock the api. We have a thin wrapper fixture that helps us reuse endpoint mocks so we don't have to declare the paths in each file. A very simple representation:

```js
// base.js
const endpoints = { 
  getItems: {
    method: 'GET',
    path: '/api/items'
  },
  createItem: {
    method: 'POST',
    path: '/api/items'
  },
  ...
}

const test = baseTest.extend({ 
  intercept: async ({ page }, use) => {
    await use(async (endpointName, response) => {
      await page.route(endpoints[endpointName].path, (route) => route.fulfill({ 
        body: JSON.stringify(response)
      }))
    })
  }
})

// items.test.js
test('list items', async ({ page, intercept }) => {
  await intercept('getItems', [{ id: 1, name: 'Item 1' }])

  await page.goto('/items')

  await expect(page.locator('text=Item 1')).toBeVisible()
})

test('create item', async ({ page, intercept }) => {
  await intercept('getItems', [{ id: 1, name: 'Item 1' }])
  await intercept('createItem', { id: 2, name: 'Item 2' })

  await page.goto('/items')
  await page.locator('role=button[name="Create item"]').click()

  await expect(page.locator('text=Item 2')).toBeVisible()
})
```

Without a way to target routes by method, we would have to use sth like `intercept('getAndCreateItems', [response1, response2])` endpoint, which doesn't seem very atomic and couples 2 routes.

While adding an `options.method` seem like a good and simple to use solution, i still think that providing the whole `request` to the matcher function, instead of just `request.url()` is worth it in the long run. It will allow for even more specific targeting when needed (like based on headers, payload, etc.). I know this could be done in the handler but i think having it in the matcher is still worth in cases where you have predefined that you want to fallback. (and like in the use case above). But event `options.method` would be helpful to have as it's probably the most common scenario.

**Comment by pavelfeldman** [comment]
So why can't you use `endpoints[endpointName].method` in your `intercept` fixture?

**Comment by purepear** [comment]
The issue is that we can't intercept both GET and POST requests at the same time because:
* the matcher `<string|RegExp|function(URL):boolean>` provides only the `url` so we can't match by method.
* the handler `<function(Route, Request)>` can match by method but once you are in a handler, you can't "skip" it, if it's not the right method, and go to the next matcher/handler. If we intercept both `getItem` and `createItem`, we'll always hit the last registered interceptor with path `/api/items` (`createItem` in this example) and there will be no way to fall back to `getItem` because `// There is no chaining, first handler wins.`

**Comment by mrmckeb** [comment]
We've started hitting these limitations too, specifically "There is no chaining, first handler wins.".

Engineers, after using tools like Cypress, expect that if they use `route.continue()`, the request will "bubble up" to the next handler. They also expect to be able to handle POST and GET separately.

We'll add more custom tooling to our project to help mitigate the issue, but an implementation on the Playwright side would be amazing.

I quite like the interface that MSW offers (as an example): https://mswjs.io/

**Comment by mrmckeb** [comment]
Thanks @pavelfeldman, amazing work as always!

**Comment by purepear** [comment]
Thanks @pavelfeldman! 🙇
