### ISSUE TITLE
[BUG] PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD not work

### ISSUE THREAD

**Issue by scruel** [microsoft/playwright#14627]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Windows 10 21H2
- Node.js version: 16.15.1
- Browser: All

C:\Users\user>set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
C:\Users\user>playwright install
Downloading Chromium 102.0.5005.40 (playwright build v1005) - 104.1 Mb [                    ] 0% 535.2s Terminate batch job (Y/N)?

**Describe the bug**
Keep downloading browsers after set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1.

**Comment by pavelfeldman** [comment]
This flag is about automatic browser download. You are giving an explicit command to download the browsers manually, so it does not respect the flag. If you don't want the browsers to be downloaded, don't call this command.

**Comment by scruel** [comment]
[Installation](https://playwright.dev/python/docs/intro#installation)
Everyone start with this....

**Comment by pavelfeldman** [comment]
Yes, but that flag is rarely used, so it isn't mentioned in the well lit path of the tool usage.

Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by scruel** [comment]
@pavelfeldman  Flag is rarely used? What's your mean? We don't need to execute `playwright install` following the installation part of document said?

**Comment by scruel** [comment]
So how can I skip browser download? What flag? `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD`? Even if it's rarely used, I think it should be work when anyone uses it, right? But it's not? Then issue just closed?
