### ISSUE TITLE
[Question] Can we create multiple APIRequestcontext in same config file for API Testing

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#14623]
I need to write API Tests for 2 different user roles. I have 2 different user roles. One is admin and other one is guest.

I need to create 2 different APIContexts in config file so that I can call them from tests.

something like requestadmin, requestguest.

Is this feasible. Current playwright official example shows creation of one Apicontext, and then using the request in the tests

**Comment by aslushnikov** [comment]
@jithinjosejacob You can [create a fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture) for yourself that creates an [API Context](https://playwright.dev/docs/api/class-apirequest#api-request-new-context).

For example, like this:

```ts
import { test as base, request, APIRequestContext } from '@playwright/test';

const test = base.extend<{
  myRequest: APIRequestContext,
}>({
  myRequest: async ({}, use) => {
    const context = await request.newContext({});
    await use(context);
    await context.dispose();
  },
});

test('foo', async ({ myRequest}) => {
  console.log(await myRequest.get('https://example.com'));
});
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
