### ISSUE TITLE
[Question] Using Vue plugin with Vue component testing

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#14631]
Original reports: https://github.com/microsoft/playwright/issues/14416, https://github.com/microsoft/playwright/issues/14621

Original message:

I think I found the root issue which is that I need Vue plugins for my component to work and adding those is not currently possible with the current implementation of mount. Here's a related ticket and my comment: https://github.com/microsoft/playwright/issues/14416#issuecomment-1146062955 and here is a PR that demonstrates the problem with a [working](https://github.com/Uninen/vite-ts-tailwind-starter/pull/218/files#diff-5d87e042c06bd4c54898d00ea245377702dbb3d663704f9cb2e740d371078871) and [non-working](https://github.com/Uninen/vite-ts-tailwind-starter/pull/218/files#diff-e17ea97189bf2c22f00b4906c6ccd156a96060cc8fdeccd3a4ee23bfa2a758ad) component: https://github.com/Uninen/vite-ts-tailwind-starter/pull/218

**Comment by pavelfeldman** [comment]
Investigation note:

I put a breakpoint after mount and looked at the devtools console:

![step1](https://user-images.githubusercontent.com/883973/171938814-63c20ce0-beeb-4df9-9f28-5501400dacbb.png)
![step2](https://user-images.githubusercontent.com/883973/171938842-afff307c-d85f-4963-b08c-942912b3aa47.png)

Which suggests that `useStore` is being used before `activePinia` was set. I'm not familiar with Pinia, but I added following to `playwright/index.js`

```js
import { createTestingPinia } from '@pinia/testing';

createTestingPinia({
  createSpy: (args) => {
    console.log('spy', args)
    return () => {
      console.log('spyreturns')
    }
  },
});
```

and the test passed!

**Comment by pavelfeldman** [comment]
@Uninen: I sent you a pull request: https://github.com/Uninen/vite-ts-tailwind-starter/pull/219/commits/44a91ce16c12bc6270d64e12ab70c9020e0cd708

**Comment by pavelfeldman** [comment]
Added a section into https://github.com/microsoft/playwright/issues/14298

**Comment by Uninen** [comment]
Thank You for the help and the added docs for the Vue community @pavelfeldman 🙏

The Playwright team and community is amazing. Keep up the good work and kudos to the whole team for such a great product 👍

**Comment by Mone71** [comment]
Thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
