### ISSUE TITLE
[Question] Conflict with existing Jest tests and mjs modules with js extension

### ISSUE THREAD

**Issue by manuca** [microsoft/playwright#14637]
I'm adding Playwright to an existing Vue 2 project but I'm having issues when I run tests. 

There are internal Jest test files with `js` extension but in `mjs` format. Those Jest tests are in `__tests__/` directories scattered around the project. Jest picks them up just fine when it runs but I'm guessing that works due to some Babel magic (just guessing). Anyway, just pointing out that I didn't have issues with those files till now.

This is what I get:

```
% yarn playwright test
yarn run v1.22.17
$ ./node_modules/.bin/playwright test

Running 1 test using 1 worker

Error: pages/contracts/__tests__/index.test.js: JavaScript files must end with .mjs to use import.
Error: store/__tests__/getters.test.js: JavaScript files must end with .mjs to use import.
```

The error does make sense from what I researched about how Node and ES modules work but I can't understand why Playwright is recursing into those directories. I explicitly set `testDir` to a sub directory named `integration-tests`, trying to keep everything isolated from the project.

If I delete those files Playwright works fine and runs my tests in `integration-tests/`.

My `playwright.config.js` has the following:

```
module.exports = {
  use: {
    testDir: 'integration-tests/',
    testIgnore: '__tests__/**'
  }
}
```

I appreciate if you could give me suggestions on how I could get around this issue. 

(I'd also prefer not to go renaming files to `mjs` as that will make the impact of these changes much bigger and also they don't seem to fix this issue anyway. I get a different error.)

Node: v14.19.2
Playwright: v1.22.2

Thanks

**Comment by pavelfeldman** [comment]
Your testDir is misplaced, should be one level higher. Use types via TS or JSDoc as in our examples to make working with config easier!

**Comment by manuca** [comment]
Thanks @pavelfeldman that made it work!
