### ISSUE TITLE
Recommendations for installing on RedHat8 Linux

### ISSUE THREAD

**Issue by ksdaftari** [microsoft/playwright#14640]
I know officially only support installation for Ubuntu Linux, but wondering if there are recommendations/approaches for to get working on other Linux distributions like RedHat 8? Also just curious will there be possibility to support other Linux distorts in future? Also is it just that user have to have build scripts/etc themselves or is there going feature set that inherently wouldn't work on other Linux Distros like Red Hat 8?

Also don't know if relevant but I am using python playwright

**Comment by aslushnikov** [comment]
> but wondering if there are recommendations/approaches for to get working on other Linux distributions like RedHat 8?

@ksdaftari so far the best we can recommend is to use Docker container to abstract away from your host distribution. 

> Also just curious will there be possibility to support other Linux distorts in future?

More distributions **might be** supported over time, depending on the demand. 

>  Also is it just that user have to have build scripts/etc themselves or is there going feature set that inherently wouldn't work on other Linux Distros like Red Hat 8?

No idea! Sometimes things work if compiled manually, sometimes not. YMMV!

Hope I answered all the questions :) Feel free to close the issue; we'll close it in a few days if no more questions arise.

**Comment by ksdaftari** [comment]
@aslushnikov Yep that answers all my questions thanks!
