### ISSUE TITLE
屏幕分辨率设置不当，有些部分不可见

### ISSUE THREAD

**Issue by weitaifu** [microsoft/playwright#14647]
**Context:**
2022/6/4安装了playwright,录制代码时，发现它设置的**_分辨率不当_**，以致于下部有些部分看不见，因而无法操作。手动缩小到80%，可以看见这些部分。可以进行到下一步，问题依然，重新录制，不能保持修改的设置。人家都说playwright超过selenium许多。然而我立即卸载了playwright和pytest-playwright。**playwright比selenium IDE差很多。无法修改代码**，比如追加条件和循环，**参数无法更换**，playwright喜欢用文本定位（比如下拉框select),以致于代码太长。许多注释往往也是很长，往往也是参数造成的，似乎抓不住关键。似乎**无法重新执行录制的代码**。而且仅有的一次重新执行就出错。**智能等待并没有出现在代码中**，而实际上等待是执行成功的一个十分关键的因素。人家使用录制功能，主要是利用代码，而playwright不能录制等待，人家怎么学？当然，懂英语的行家还好。不懂英语，又是新手就犯难了。还有playwright居然不支持自家的（系统自带）Microsoft Edge浏览器。playwright自己安装了好几个浏览器，而实际上只会用到chromium。占用了不必要的空间，增加管理难度和代价。
- Playwright Version: [what Playwright version do you use?]1.22
- Operating System: [e.g. Windows, Linux or Mac]Windows10
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]chromium
- Extra: [any specific details about your environment]http://128.0.3.8:19001

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
Please use GitHub Issues to file bugs or feature requests!
