### ISSUE TITLE
[Question] logged in fixture / how to create a worker scoped function

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright#14643]
Hi i try to create a fixture named something like "loggedInPage":

Given your documentation: https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures

```
import { test as base } from '@playwright/test';

// I want to create a loggedInPage should this be like:
type LoggedInPage = { loggedInPage: Page }

// Note that we pass worker fixture types as a second template parameter < ?.
export const test = base.extend<{} // What is this?, { loggedInPage: Page }>({
  loggedInPage: [async ({ browser }, use, workerInfo) => {
    // Unique username.
    const username = myUsername
    const password = myPassword

    // login with this account.
    const page = await browser.newPage();
    await page.goto('/');
    await Header(page).gotoLogin()
    await page.locator('#username').fill(username);
    await page.locator('#password').fill(password);
    await page.locator('text=login').click();
    await use(page);
    // Do not forget to cleanup.
    await page.close();
  }, { scope: 'worker' }],
  },
});
//would that work?

export { expect } from '@playwright/test'; <-  Why this?
```

**Comment by aslushnikov** [comment]
> Hi i try to create a fixture named something like "loggedInPage":

@Kranael Your code snippet looks mostly legit. What doesn't work? 

Here's a working code snippet I just tried:

```ts
import { test as base, Page } from '@playwright/test';

type MyPage = { myPage: Page };

export const test = base.extend<{}, MyPage>({
  myPage: [async ({ browser }, use, workerInfo) => {
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await use(page);
    await page.close();
  }, { scope: 'worker' }],
});

test('should work', async ({ myPage }) => {
  console.log(await myPage.title());
});
```

**Comment by Kranael** [comment]
> > Hi i try to create a fixture named something like "loggedInPage":
> 
> @Kranael Your code snippet looks mostly legit. What doesn't work?
> 
> Here's a simple code snippet you can draw inspiration from:
> 
> ```ts
> import { test as base, Page } from '@playwright/test';
> 
> type MyPage = { myPage: Page };
> 
> export const test = base.extend<{}, MyPage>({
>   myPage: [async ({ browser }, use, workerInfo) => {
>     const page = await browser.newPage();
>     await page.goto('https://example.com');
>     await use(page);
>     await page.close();
>   }, { scope: 'worker' }],
> });
> 
> test('should work', async ({ myPage }) => {
>   console.log(await myPage.title());
> });
> ```

I want to understand the fixture structure more. Here your documentation is not enough i think.

For example i want to know `base.extend<{}, MyPage>` <- What is the {}? I know its a object but why do we need to pass here a empty object?

And the next question:

Not scoped fixtures are written like that:
```
import { test as base, Page } from '@playwright/test';

type MyPage = { myPage: Page };

export const test = base.extend<MyPage>({
  todoPage: async ({ page }, use) => {
    // Do something like
    const todoPage = new TodoPage(page);
    await todoPage.goto();
    await todoPage.addToDo('item1');
    await todoPage.addToDo('item2');

    // Here we use the state/code that we generate
    await use(todoPage);

    // all cleanup is after the use method right?
    await todoPage.removeAll();
   someOtherCleanUp() // for example
  },
```

If i want a scoped fixture i need a array like this?

```
type MyPage = { myPage: Page };

export const test = base.extend<{}, MyPage>({
  myPage: [async ({ browser }, use, workerInfo) => {
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await use(page);
    await page.close();
  }, { scope: 'worker' }],
});
```

and the scope is setup with a second object `{scope: '//myscope'}` correct?

**Comment by pavelfeldman** [comment]
You pretty much never want a worker-scope fixture. We use those to optimize the number of browser instances, but you should not need them. Keep it simple and follow the docs: https://playwright.dev/docs/next/test-fixtures#overriding-fixtures

If you do this, the first parameter of extend will contain types for your fixtures (MyPage in your case).

**Comment by pavelfeldman** [comment]
Or are you looking for this? https://playwright.dev/docs/next/test-auth#reuse-signed-in-state

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
