### ISSUE TITLE
[Question] Safe invisible two way communication

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#14651]
I wonder if there's an API, or a workaround, that allows a script in the page to communicate with Playwright directly, passing messages between one another through two-way channels, like [Channel Messaging API](https://developer.mozilla.org/en-US/docs/Web/API/Channel_Messaging_API).

I considered `WebSocket`, with which we can connect a Node.js server. By that the script can send messages to Playwright via the server, and the other Node.js' code can send messages back, too. Although it's invisible and safe to the other scripts in the page, we can see the connection in the Network panel DevTools, it is easily visible.

My best guess is to use window events. In Node.js side, to pass a message, we dispatch a custom event on the `window`, whose name is an unguessable string and only the target script knows and listens to the event. The body of the message can be attched to `event.detail`. But how can we receive messages from the script? We can't use `exposeFunction` and let the script call the exposed, as it adds a global function which is visible. We can use `evaluate` to wait for the page to dispatch similar events, but `evaluate` is not a listener, we need to run it again when it returns, and I doubt if there will be some uncaught messages if the messages were sent continuously and rapidly.

Do you have any suggestion or comment? Thank you!

**Comment by pavelfeldman** [comment]
Could you share why exposeFunction's visibility is a problem?

You can poll using evaluate, if you organize an event queue (array of outgoing messages) on the page side, you'll be picking all the events and you'll never miss any.

**Comment by PaperStrike** [comment]
Thank you for your suggestion! Your event queue idea is really inspiring!

exposeFunction's visibility isn't a real problem. It turns out that it's just me feeling uncomfortable for introducing any global variable / function. The complexity may make me ended up using it or webSockets, anyway.

Thanks!
