### ISSUE TITLE
Why is browser not called Close(), and the browser closes automatically. How to prevent the browser from closing automatically

### ISSUE THREAD

**Issue by fj201314** [microsoft/playwright#14658]
with sync_playwright() as playwrite:
        browser = playwrite.chromium.launch(headless=False,slow_mo=5000)
        context=browser.new_context(permissions=['clipboard-read'])
        page=context.new_page()
        page.goto(url=”“)
        time.sleep(3)

**Comment by fj201314** [comment]
Can you tell me how to modify this code so that the browser will not be closed automatically ，please。I tried, but failed


from playwright.sync_api import sync_playwright,Playwright
with sync_playwright() as playwrite:
    browser = playwrite.chromium.launch(headless=False, slow_mo=5000)
    page = browser.new_page()
    page.goto('https://www.google.com.hk/')

**Comment by pavelfeldman** [comment]
playwright = sync_playwright()
browser =...

**Comment by fj201314** [comment]
But when the waiting time is up, the browser still closes. What I want is if the user doesn't close it manually or the script doesn't call the browser Close(), the browser is still open

**Comment by fj201314** [comment]
Is there any way to implement it

**Comment by pavelfeldman** [comment]
There is way to implement it other than setting a large timeout. You have a synchronous program, it has the beginning and and end, so unless you wait_for_timeout, the sync program needs to end!
