### ISSUE TITLE
[Question] Component tests. React <= 16.13.1. Cannot find module 'react/jsx-runtime'

### ISSUE THREAD

**Issue by pashidlos** [microsoft/playwright#14662]
Assuming it was added in React 17 
https://ru.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html

Is that possible to make it work with React 16?

```
[vite:react-jsx] Could not load react/jsx-runtime (imported by src/TestComponent.tsx): Cannot find module 'react/jsx-runtime' from 'packages/ui'

Error: Could not load react/jsx-runtime (imported by src/TestComponent.tsx): Cannot find module 'react/jsx-runtime' from '/packages/ui'

    at Function.resolveSync [as sync] (/Users/pstrunkin/work/backoffice-core-client-library/node_modules/@vitejs/plugin-react/node_modules/resolve/lib/sync.js:111:15)
    at Object.load (node_modules/@vitejs/plugin-react/dist/index.js:526:52)
    at node_modules/rollup/dist/shared/rollup.js:22974:37

TypeError: Cannot read property 'httpServer' of undefined
```

**Comment by pavelfeldman** [comment]
Could you suggests the steps to reproduce this?

**Comment by pashidlos** [comment]
@pavelfeldman thanks for quick response
in did it cannot be reproduced with the latest v16 
but reproduces with the one I have in project 
check the reproduce project 
https://github.com/pashidlos/pw-component-test-example

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
