### ISSUE TITLE
Unify download path type with testInfo.attach path type

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#14667]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 14.19.2
- Browser: -

**Describe the bug**

Download path has `string | null` type while `testInfo.attach` path argument has `string | undefined` so it's not possible to pass path without getting a warning. It's minor but could it be unified?

![SCR-20220606-txc](https://user-images.githubusercontent.com/17873445/172224681-58af2be5-321a-4c97-833e-b14ebfab8fa8.png)

**Comment by pavelfeldman** [comment]
- `download.path()` returns `null` when `acceptDownloads` is set to false. So it is guaranteed to be there if you are accepting the downloads.
- And `undefined` path in attachment means that the value is optional (as opposed to nullable).

Making attachments accept nullable path sounds arbitrary, so I guess doing `path: path!` on the client side would be the least of the evils.

**Comment by MindaugasMateika** [comment]
Makes sense, thank you.
