### ISSUE TITLE
[Suggestion] consolidate dotnet java and python bindings into main repository 

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#14665]
- some of the issues reported in the other repositories are solved by fixes in the underlying nodejs server logic
- most if not all of the abstraction classes are generated by code in the main repository 
- the release versions numbers are aligned between the different languages
- the docs for the different languages are located in the main repository

**Comment by pavelfeldman** [comment]
Please limit the usage of Issues to feature requests and bug reports!
