### ISSUE TITLE
[Question] How to solve the inconsistency caused by the asynchronous rendering of the page when taking screenshots

### ISSUE THREAD

**Issue by SilenceCarrot** [microsoft/playwright#14672]
How to solve the inconsistency caused by the asynchronous rendering of the page when taking screenshots？

E.g.
After clicking the submit button, take a screenshot of the screen.
Then when taking screenshots, taking into account the influence of network and machine load, there will be some differences due to the asynchronous actions of the page when taking screenshots.
Then there may be inconsistencies between the two screenshots.

**Comment by pavelfeldman** [comment]
That's a great summary. On top of that you'll see the font discrepancies and rasterization artifacts. So you need to wait for the dom to get into the expected state, wait for images to load. `toMatchScreenshot` will make sure consecutive screenshots are the same to minimize potential rasterization effects.

**Comment by SilenceCarrot** [comment]
Thanks a lot for your answer.
But please excuse my unprofessionalism, which API provides the 'toMatchScreenshot' method? I kind of didn't find it in Playwright's API.
I hope you can give me more information, I will be very grateful to you.

**Comment by ltsuda** [comment]
I hope this helps:

API:
https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-1
https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-2

Visual comparison page:
https://playwright.dev/docs/test-snapshots

**Comment by SilenceCarrot** [comment]
Oh great, that's exactly what I was looking for.
So, the search function in the top right corner of the playwright documentation page is flawed, it doesn't help me find the keyword I'm looking for: 'toMatchSnapshot'.
![image](https://user-images.githubusercontent.com/15966265/172520949-32dd0191-bf74-489a-a2f9-596641ace7ec.png)

My problem has been solved, playwright is a great project, thank you for everything.

**Comment by SilenceCarrot** [comment]
Oh, great, that's a nice ability.
But I am currently using playwright-java, does it provide an effective method?

**Comment by pavelfeldman** [comment]
Playwright Java does not have that method yet, please stay tuned!

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by SilenceCarrot** [comment]
OK，looking forward to supporting this feature, thank you for your answer.
