### ISSUE TITLE
How to minimize a page with the repo?

### ISSUE THREAD

**Issue by zydjohnHotmail** [microsoft/playwright#14677]
### Your question

Hello:
From time to time, I need to minimize a page, but not close it.  Just minimize it, so it will stay in Windows task bar.  And later on, I can open it again, and use it to visit other pages.
I have searched around, the only examples I can find are either maximize the page, or SetViewportSizeAsync, but they are not what I need.
I need to minimize the page.
Please advise,
Thanks,

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
