### ISSUE TITLE
[BUG] Test steps spill over into after hooks and fail even though they passed

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14685]
**Context:**
- Playwright Version: 1.22
- Operating System: Manjaro Linux
- Node.js version: v16.15.0
- Browser: Chromium

Today I've repeatedly seen a test fail even though all its steps passed (and in the video I can actually see the test running fine without any problems). The fail only occurs due to a 60s timeout (see attachment).
However, what's odd is that the test actually ran for an entire 1.7m even though it is not marked as `.slow()`:

```
test('Edit Tutor Availabilities', async ({shared, webApp, webAppTutor}) => {
    await webAppTutor.goToCalendar();
    await webApp.closeCodeOfConductBannerIfNecessary(shared);
    await webAppTutor.moveCalendarByWeeks(4);
    await webAppTutor.removeAllTutorAvailabilitySlotsInCalendarIfPossible(webApp);
    await webAppTutor.addTutorAvailabilities(shared, webApp);
});
```

And just FYI the timeout in my config is set to 60s:
`timeout: 60000,`

So it seems to me there is a bug regarding PW's timeout.
The test execution should stop after 60s but it doesn't. 
But since it doesn't and the test passes, it shouldn't mark the test as failed either.

Upon a closer look, I noticed that the test step are wrongly "spillling over" into the after hooks (I haven't defined any after hooks):
![image](https://user-images.githubusercontent.com/98180468/172450069-8b17b097-9df6-43e7-a7ec-10c08e91847d.png)

And at the end of the after hooks, browserContext.close actually takes 24 seconds! How can that be?
![Screenshot_20220607_135509](https://user-images.githubusercontent.com/98180468/172450336-6ab7b994-a7b5-4b82-be79-d13355f3b995.png)

In some cases it also took -1ms:
![image](https://user-images.githubusercontent.com/98180468/172459424-b2ef7e66-b236-4876-830b-da487852ff08.png)

This issue only occurs when I run my entire test suite (23 tests, 4 skipped, 4 minutes in total, 7 spec files & workers) though. When I run those tests individually, it doesn't occur. So maybe the root cause is the same as in https://github.com/microsoft/playwright/issues/14686.

[Playwright test passed but failed with timeout.zip](https://github.com/microsoft/playwright/files/8854184/Playwright.test.passed.but.failed.with.timeout.zip)

**Comment by azad-derakhshani-GS** [comment]
Since it only happens when running the entire test suite and not individual tests, I would have to give you the entire test suite, which of course I can't, so that's why I suggested showing it in a call instead.

Which script do you mean?
The strange thing is that those steps are part of the test (the test isn't over yet), they should not spill over into the after hook, so it would seem like a PW bug to me.

**Comment by pavelfeldman** [comment]
Most likely you did not await those steps.

**Comment by azad-derakhshani-GS** [comment]
No I always use await.

**Comment by pavelfeldman** [comment]
> If you take a look at the screenshot, you see that the part where it spills over is in the middle of a for loop

I'm not sure which screenshot you are referring to. Is that in the archive? I don't have apps that would open mhtml.

> So this is definitely a Playwright bug. It should stop the test execution after 60s

We would need to see the source code or a minimal reproduction to tell what's happening.

> Marking the test as .slow() prevents this issue but that doesn't change the fact that there is a bug in PW.

This is a signal supporting my hypothesis - one of the stray async flows finishes before the test is over if you mark it as slow.

> So I would appreciate it if someone took these bugs seriously, I'm just trying to improve PW.

I'm doing my best, but there are no steps to reproduce, no scenarios, no reproduction, just a statement that "something does not work". We need more details than that!

**Comment by azad-derakhshani-GS** [comment]
> I'm not sure which screenshot you are referring to. Is that in the archive? I don't have apps that would open mhtml.
The first screenshot in the post. :) 
Here it is again: 
![image](https://user-images.githubusercontent.com/98180468/172709017-acca7934-419f-4a4c-bfa3-f5ca1187b667.png)

> We would need to see the source code or a minimal reproduction to tell what's happening.
> I'm doing my best, but there are no steps to reproduce, no scenarios, no reproduction, just a statement that "something does not work". We need more details than that!

I know, and I would love to give you more details, but that's the whole problem. The issue was only observed when running the whole test suite, so there are not really any details. Believe me, I would prefer to narrow it down and give you easy reproduction steps too!
And for the same reason, creating a minimal repro is not quite possible either, I'd basically have to give you a maximal repro (=the entire project) instead. That's why I suggested to show the code and a full testrun in a call. 

I even tried to create a minimal repro for you, but that means the behaviour is completely different. 
The test steps don't spill over into the After Hooks anymore, the only thing that can reproduced this way is issue #14686.
I'll have a call with my manager tomorrow, maybe we can create a user specifically for you and then give you a bigger code bundle privately.

> This is a signal supporting my hypothesis - one of the stray async flows finishes before the test is over if you mark it as slow.
But how can we identify which one of them goes stray? I even checked every line that is executed and there are no missing awaits, just as expected.

**Comment by pavelfeldman** [comment]
> Here it is again:

Ok, so we are seeing getAttribute in the after hooks. What this means is that after the test has finished, getAttribute was called. Can you look at its usages and figure out what is calling it after the test end? Maybe you use `page.on` somewhere?

**Comment by azad-derakhshani-GS** [comment]
> Ok, so we are seeing getAttribute in the after hooks. What this means is that after the test has finished, getAttribute was called.

Ah sorry, maybe I should've posted a bigger screenshot. `getAttribute` is called in the test, not the AfterHooks, that's what I meant by spilling over (into the AfterHooks).
Part of the test is a nested for loop that goes through a calendar cell by cell, checks an attribute and then clicks it.

![Screenshot_20220609_115538](https://user-images.githubusercontent.com/98180468/172891781-9a8dabde-0c31-4e26-b9c3-a18b5dec0f2b.png)

So what you're seeing there are lines from this function:
```
async addSlotsInCalendar(shared, desiredNumberOfSlots = 80){
        for (let i = 0; i < 7; i++){
            console.log("The desired number of slots is " + desiredNumberOfSlots);
            if (desiredNumberOfSlots == 0) {
                break;
            }
            console.log(`Trying to add slots to day ${i+1}`);
            let dayInWeek = this.calendarDaysInWeek.nth(i);
            for (let j = 16; j < 33; j++){
                let slotInDay = dayInWeek.locator("div").nth(j);
                let slotIsNotSelectable = await shared.elementAttributeContains(slotInDay,"class","not-selectable");
                if (slotIsNotSelectable == false) {
                    await slotInDay.waitFor();
                    await slotInDay.click();
                    desiredNumberOfSlots--;
                }
                if (desiredNumberOfSlots == 0) {
                    break;
                }
            }
            if (desiredNumberOfSlots == 0) {
                break;
            }
        }
    }
```

Specifically, these lines:
```
let slotIsNotSelectable = await shared.elementAttributeContains(slotInDay,"class","not-selectable");
                if (slotIsNotSelectable == false) {
                    await slotInDay.waitFor();
                    await slotInDay.click();
```

Anyway, I talked to my manager and we can send you a minimal repro privately, but as mentioned it only reproduces #14686, not #14685 (this ticket). Can you give me an email address to send it to? Or I could also send it on Slack if you prefer.

**Comment by pavelfeldman** [comment]
The code looks good, but there isn't anything I can reproduce, so I'll have to close it as non-actionable. I'm not familiar with the Spill term and it seems like you can use debugger / console.log to see what runs, when and why. Playwright test is just a program, so you should put a bunch of console.logs and you'll quickly identify the place where the problem with missing await or something similar is.

**Comment by azad-derakhshani-GS** [comment]
I meant spilling over figuratively (like a fluid spilling over), as in: the test steps are shown in the Afterhooks in the PW test report, which they shouldn't. Or to put it this way:

Expected result:
- Afterhooks only contain Afterhooks

Actual result:
- Afterhooks contain test steps

There is definitely no missing await or anything like that, and I already use tons of console.logs in my tests.
The issue is clearly a bug in PW and has nothing to do with the test, so all I was trying to do is improve the _program_ Playwright test by reporting this bug.
And I repeatedly offered to show it to you in a call, so you could see the actual bug for yourself.
But I'm getting the impression that there's no interest in fixing bugs or improving PW, which is a shame to be honest. I would do it myself if I knew how.

**Comment by pavelfeldman** [comment]
Ok, sure, let's do the call! Ping me on our Slack!

**Comment by pavelfeldman** [comment]
I'll close this bug as non-actionable because there are no steps to follow, but feel free to ping me over Slack!

**Comment by ramam-v** [comment]
@azad-derakhshani-GS were you able to address this issue on your side. I am seeing a similar issue at my end. I have react app with 84 input fields where the execution is failing due to time out or pending operations. I am also noticing that few of the step results are captured under AfterHook  step as you have experienced. I dont see any issues with the first 70 fields but the issue crops up after 70 fields. I am on playwright 1.27.1

**Comment by azad-derakhshani-GS** [comment]
@ramam-v As far as we could figure out, it was happening because the test timeout was too short, because the duration of the test timeout also has to cover the teardown.
To alleviate this, I [suggested](https://github.com/microsoft/playwright/issues/15019) moving the teardown timeout out of the test timeout. However, that approach was not approved so instead (iirc) the errror message was adjusted a bit to avoid confusion.

Another related topic is the number of workers. We used to run our tests with 8 workers, which led to a lot of test timeouts. Halving them to 4 made our tests much more stable and all but eliminated those timeouts for good. Other PW users have observed the same.
To make this more flexible, [this feature request](https://github.com/microsoft/playwright/issues/17204) was created and approved and by now, released.

So what I would suggest as first steps to tackle your issue is:
- try changing the number of workers to 50%
- if that isn't enough, increase the test timeouts for the tests that still exhibit that issue

**Comment by cyrus-afshari** [comment]
Chiming in with a "me too" comment here, how does the below make sense? Anyone able to explain why the After hooks would show as failed, with 0 failed steps? This is in the scenario where the test reached its timeout. I think the OP is truly revealing a PW bug.

![Screenshot 2024-09-24 at 10 45 08 AM](https://github.com/user-attachments/assets/a25e1245-77ef-48a9-95a1-b86304aabca0)

**Comment by andrecasal** [comment]
I constantly bump into this too.

<img width="1726" height="1047" alt="Image" src="https://github.com/user-attachments/assets/a35a302d-9e42-4e41-86cb-16fa2aa87887" />

Notice I have the first test selected. Here's the test code:
```ts
test('Users can onboard with link sent to email', async ({
	page,
	generateUserData,
}) => {
	const onboardingData = {
		...(await generateUserData()),
		password: faker.internet.password(),
	}

	await page.goto('/')
	await page.getByRole('link', { name: /log in/i }).click()
	await expect(page).toHaveURL(`/login`)
	await page
		.getByRole('link', {
			name: /create an account/i,
		})
		.click()

	await expect(page).toHaveURL(`/signup`)
	await page.getByRole('textbox', { name: /email/i }).fill(onboardingData.email)
	await page.getByRole('button', { name: /submit/i }).click()

	await expect(page).toHaveURL(/\/verify/)
	await expect(page.getByText(/check your email/i)).toBeVisible()

	// Get URL from email
	const email = await readEmail(onboardingData.email)
	invariant(email, 'Email not found')
	expect(email.to).toBe(onboardingData.email.toLowerCase())
	expect(email.from).toBe(sendingEmail)
	expect(email.subject).toMatch(/welcome/i)
	const onboardingUrl = extractUrl(email.text)
	invariant(onboardingUrl, 'Onboarding URL not found')

	// Visit onboarding URL
	await page.goto(onboardingUrl)
	await expect(page).toHaveURL(/\/verify/)
	await page.waitForLoadState('networkidle')
	await page
		.getByRole('main')
		.getByRole('button', { name: /submit/i })
		.click()

	await expect(page).toHaveURL(`/onboarding`)
	await page.getByRole('textbox', { name: /^name/i }).fill(onboardingData.name)
	await page.getByLabel(/^password/i).fill(onboardingData.password)
	await page.getByLabel(/^confirm password/i).fill(onboardingData.password)
	await page.waitForLoadState('networkidle')
	await page.getByLabel(/terms/i).check()
	await page.getByLabel(/remember me/i).click()

	await page.getByRole('button', { name: /Create an account/i }).click()

	await expect(page).toHaveURL(`/settings/profile`)
	await page.waitForLoadState('networkidle')
	await page.getByRole('button', { name: /user menu/i }).click()
	await page.getByRole('menuitem', { name: /profile/i }).click()

	await expect(page).toHaveURL(`/settings/profile`)
	await page.waitForLoadState('networkidle')
	await page.getByRole('button', { name: /user menu/i }).click()
	await page.getByRole('menuitem', { name: /logout/i }).click()
	await expect(page).toHaveURL(`/`)
})
```

Also notice the test code spills into the `After Hooks` section, which makes no sense to me.

Additionally, a lot of tests fail when I run them all in parallel, but they all pass individually.
