### ISSUE TITLE
[BUG] Back/forward cache (bfcache) global values leaking from one page to another

### ISSUE THREAD

**Issue by infonline** [microsoft/playwright#14683]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows with WSL + GitLab CI
- Node.js version: 16.5.0
- Browser: Chromium, Firefox
- Extra: [any specific details about your environment]

**Code Snippet**

E2e test:

```javascript
const browsers = [
  {
    instance: chromium,
    name: 'Chromium',
    options: {
      headless: false,
    },
  },
  {
    instance: firefox,
    name: 'Firefox',
    options: {},
  },
];

test.describe('Bfcache', async () => {
  await Promise.all(
    browsers.map(async (browser) => {
      test(`[${browser.name}] Bfcache test1`, async () => {
        const browserInstance = await browser.instance.launch(
          browser.options,
        );
        const page = await browserInstance.newPage();

        // ... intercept requests (to load bundles / return 200 / ...) ...

        // Visit first page and make sure request was sent
        const [request1] = await Promise.all([
          page.waitForRequest('**/xyz.io'),
          page.goto(`http://localhost:8080/e2e/fixtures/${lang}/bfcache/page1`),
        ]);
        checkRequest(request1, {
          site: 'site1', // set in fixture by calling JS function from loaded bundle in global namespace
        });

        // Visit second page and make sure request was sent
        const [request2] = await Promise.all([
          page.waitForRequest('**/xyz.io'),
          page.goto(`http://localhost:8080/e2e/fixtures/${lang}/bfcache/page2`),
        ]);
        checkRequest(request2, {
          site: 'site2',  // set in fixture by calling JS function from loaded bundle in global namespace
        });

        // Go back to first page with browser navigation
        const [request3] = await Promise.all([
          page.waitForRequest('**/xyz.io'),
          page.goBack({ waitUntil: 'networkidle' }),
        ]);
        checkRequest(request3, {
          site: 'site1',  // fails, because it is "site2"
        });
      });
    }),
  );
});
```

Page 1 fixture:
```html
...
<script type='text/javascript'>
  AnalyticsSolution.configure({ site: 'site1' });
</script>
```

Page 2 fixture:
```html
...
<script type='text/javascript'>
  AnalyticsSolution.configure({ site: 'site2' });
</script>
```

**Describe the bug**

We offer analytics solutions and due to the Back/forward cache (or [bfcache](https://web.dev/bfcache/)) and the way it is [handled](https://web.dev/bfcache/#how-bfcache-affects-analytics-and-performance-measurement), we need to automatically fire pageview events once a user returns to a website, which is then served from bfcache. This involves end to end testing of course.

While verifying our implemented solution with an e2e test, we noticed a bug, which probably comes from playwright and which we cannot explain properly.

This is our test setup (reflected by the code above):
- Visit the first page, where our analytics solution is loaded (.js bundle) and configured with `site: site1`, the bundle will automatically trigger a pageview event, validate the resulting request and make sure the parameter site is actually set to `site1`
- Visit the second page, where our analytics solution is loaded (.js bundle) and configured with `site: site2`, the bundle will automatically trigger a pageview event, validate the resulting request and make sure the parameter site is actually set to `site2`
- Go back to the first page with the browser navigation, now the page is loaded from bfcache (JS runtime was frozen before and is now resumed), now our solution detects the page was loaded from bfcache and triggers a pageview event, make sure the parameter site is actually set to `site1`

The last assertion _fails_, the request after returning to page 1 (served from bfcache this time) actually  has the parameter site set to `site2`, even though we are on the first page.

This shouldn't be the case, because we never configured the site parameter to have the value `site2` on the first page (it should be `site1)` and since bfcache freezes the JS environment (including the heap) and resumes it when serving the bfcache for each page. Even though the bundle used on both pages is the same and the variable name as well, the two JavaScript environments on page 1 and page 2 should be completely separated and it should not be possible for page 1 to have values from JS environment from page 2.

So we assume that there is a bug in playwright that leads to this behavior, when reproducing the setup locally and testing it manually it didn't occur.

One thing we noticed when running the e2e test with the `--debug` flag, is the following error in the console:
<img width="515" alt="image" src="https://user-images.githubusercontent.com/1984089/172385326-86c0ce15-76d5-4520-a13c-3c40394b193e.png">

Maybe this error stops the execution of JavaScript on the page and the heap (global environment) still contains values of the page before. 

Any help or suggestions are greatly appreciated!

**Comment by pavelfeldman** [comment]
Is there a chance we can get a repro for this?

**Comment by infonline** [comment]
Hi again, sorry for the late answer. The problem still exists though.

Unfortunately, we cannot provide the original repository since the code is proprietary.

Instead, we created a new repository demonstrating the bfcache problem with playwright after version `1.22.2`.

Please have a look at the following repository with the bfcache demo: [https://github.com/infonline/playwright-bfcache](https://github.com/infonline/playwright-bfcache)

We would really like to know if the mistake is on our side, or if this is a problem with playwright / newer browser versions.

Thank you!
