### ISSUE TITLE
[Question] Error due to pages being too isolated.

### ISSUE THREAD

**Issue by oscargforce** [microsoft/playwright#14681]
Hello!

I wondered if there are any "hacks" to work around the below issue.

When I try to login into an application that uses nemID === a danish bankID login service provided by Signicat, I get the following message.
![image](https://user-images.githubusercontent.com/102926658/172376158-f99c745b-3fe0-484e-b06a-edeb241e1bfe.png)

"too restrictive privacy settings or other environmental factors" === is most likely the issue since it works with selenium.
I tried giving all permission that exists in: https://playwright.dev/docs/next/api/class-browsercontext#browser-context-grant-permissions

Is there any workaround that comes to mind?

**Comment by pavelfeldman** [comment]
Could we get a repro for this problem? Can you perform the same steps manually?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
