### ISSUE TITLE
[Question]: proxy url script with WebKit

### ISSUE THREAD

**Issue by sgdowney** [microsoft/playwright#14690]
### Your question

Using C# with Playwright 1.22.
I can specify a proxy url script with launching Chromium (Chrome channel) via the Args property of the BrowserTypeLaunchOptions.  I specify the proxy url like this:
```
string [] args = { "--proxy-pac-url http://url.to.proxy/ProxyFile.pac" };
await using var browser = await Playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
      {
            Channel = "chrome",
            Headless = false,
            Args = args
       });
```
The browser is able to reach the site.
Using Webkit, I'm not able to reach the site using the code below:
```
string [] args = { "--proxy-pac-url http://url.to.proxy/ProxyFile.pac" };
await using var browser = await Playwright.Webkit.LaunchAsync(new BrowserTypeLaunchOptions
      {
            Headless = false,
            Args = args
       });
```
Can you use a proxy script with WebKit?

**Comment by pavelfeldman** [comment]
Maybe this helps: https://playwright.dev/docs/api/class-testoptions#test-options-proxy

**Comment by sgdowney** [comment]
It's not just a single proxy server.  Depending upon the destination different proxy servers have to be used so providing a single proxy server IP isn't possible.

**Comment by pavelfeldman** [comment]
Understood. No, there is no such feature for WebKit.

**Comment by Du-in-it** [comment]
will this feature be available in the future?
