### ISSUE TITLE
[Feature] Add feature to allow mocking useRouter in Next.js for component testing

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#14707]
If the component uses `useRouter()` hook, tests will fail because the hook will be null/undefined.

Jest has `jest.spyOn` to mock it (reference - https://jamespotz.github.io/blog/how-to-mock-userouter). It would be helpful to have something similar here.

**Comment by pavelfeldman** [comment]
Could you provide a complete example of what you'd like to achieve? Note that in most cases, putting all the mocking / init code into the `playwright/index.js` would be sufficient.

**Comment by pavelfeldman** [comment]
Once the patch above lands, you should be able to do the following:

```js
// index.js
import router from 'next/router';
import { beforeMount, afterMount } from '@playwright/experimental-ct-react/hooks';

beforeMount(async ({ hooksConfig }) => {
  // Before mount, redefine useRouter to return mock value from test.
  router.useRouter = () => hooksConfig.router;
});
```

```js
// test.spec.jsx
// Pass mock value from test into `beforeMount`.
await mount(<App></App>, {
  hooksConfig: {
    route: {
      query: {page: 1, per_page: 10},
      asPath: '/posts'
    }
  }
});
```

**Comment by pavelfeldman** [comment]
I'll close it, but please feel free to reopen if there are outstanding issues.

**Comment by a-vershinin** [comment]
@pavelfeldman 
Hi. Could you provide more complex example how to mock any modules in components. The example which was present before doesn't work with custom react hooks and useRouter

**Comment by jhancock532** [comment]
+1 to the above, I'd also love to see how to get component testing working with `useRouter` from Next.js

**Comment by scottbert** [comment]
IMHO mocking is essential for component tests - or we are stuck with only being to test components that render purely on props passed in - hooks are a major part of react development these days and not being able to mock a hook before tests is a big issue for us.

**Comment by harrison-carter** [comment]
> Once the patch above lands, you should be able to do the following:
> 
> ```js
> // index.js
> import router from 'next/router';
> import { beforeMount, afterMount } from '@playwright/experimental-ct-react/hooks';
> 
> beforeMount(async ({ hooksConfig }) => {
>   // Before mount, redefine useRouter to return mock value from test.
>   router.useRouter = () => hooksConfig.router;
> });
> ```
> 
>  ```js
> // test.spec.jsx
> // Pass mock value from test into `beforeMount`.
> await mount(<App></App>, {
>   hooksConfig: {
>     route: {
>       query: {page: 1, per_page: 10},
>       asPath: '/posts'
>     }
>   }
> });
> ```

How does this work when mocking named exports?
The above example covers mocking a default export of `router` but `useRouter` as a hook is not a default export.
<img width="434" alt="Screenshot 2023-01-06 at 11 40 29" src="https://user-images.githubusercontent.com/51029201/211005627-63a844b1-6dac-444a-b0d8-4f1da330a3a4.png">


With a different example of mocking `useContext` from react, how we would we overcome mocking an import and satisfying TypeScript?
<img width="557" alt="Screenshot 2023-01-06 at 11 38 08" src="https://user-images.githubusercontent.com/51029201/211005447-15515fdd-e1f3-439d-87ae-d67312b6e42b.png">

**Comment by bonchuk** [comment]
> Once the patch above lands, you should be able to do the following:
> 
> ```js
> // index.js
> import router from 'next/router';
> import { beforeMount, afterMount } from '@playwright/experimental-ct-react/hooks';
> 
> beforeMount(async ({ hooksConfig }) => {
>   // Before mount, redefine useRouter to return mock value from test.
>   router.useRouter = () => hooksConfig.router;
> });
> ```
> 
>  ```js
> // test.spec.jsx
> // Pass mock value from test into `beforeMount`.
> await mount(<App></App>, {
>   hooksConfig: {
>     route: {
>       query: {page: 1, per_page: 10},
>       asPath: '/posts'
>     }
>   }
> });
> ```

can you provide the same example but for the useParam() from the react-router-dom please?
