### ISSUE TITLE
[Question]  Can chromium.connect send traffic through proxy?

### ISSUE THREAD

**Issue by ronnymikalsen** [microsoft/playwright#14704]
I am trying to connect to LambdaTest from our CI environment that is behind a firewall. All our traffic has to go through a proxy. I can't find a way to make `chromium.connect` to connect using our proxy

```
this.browser = await chromium.connect(
      `wss://cdp.lambdatest.com/playwright?capabilities=${encodeURIComponent(
        JSON.stringify(capabilities)
      )}`
    );
```

**Comment by pavelfeldman** [comment]
There is no way to specify the proxy for the connect call. But you can point it to a different location (proxy itself).

**Comment by ronnymikalsen** [comment]
Thanks for the quick reply. I will try that
