### ISSUE TITLE
[Question] Should waitForResponse care about the order of query params?

### ISSUE THREAD

**Issue by sugendran** [microsoft/playwright#14702]
Hi, I have a question about `waitForResponse` - should it care what order the URL params are specified in? I’m changing the HTTP request client in a project, and the clients order the params differently, which causes my playwright tests to fail. 

Here's a zip with a sample test that I think should pass in both cases.
[playwright-url-param-question.zip](https://github.com/microsoft/playwright/files/8860816/playwright-url-param-question.zip)

FWIW I was expecting that playwright would use some sort of URL parser under the hood and compare the resulting objects.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
