### ISSUE TITLE
[Question]How get the drop down selected option using indexing?

### ISSUE THREAD

**Issue by isherkhan** [microsoft/playwright#14713]
Hi

I have a same selector for one or more drop down list elements I would like to read the selected option of the second instance of the drop down list.

**Comment by isherkhan** [comment]
> I'm not sure I follow, could you provide a snippet of code or a reproduction?


Hi, I am trying to get the selected option from a dropdown.(i have multiple dropdowns in the page with the same selectors)
i tried passing indexing in the page.$eval function.

Iam looking for a similar function as below for the multiple selectors

const a = await page.$$(['data-id="DDLUser"]).nth(1);

const last = await page.$eval<string, HTMLSelectElement>('[data-id="DDLUser"]).nth(1)', el => el.value);
console.log(last);

**Comment by pavelfeldman** [comment]
await page.locator('...').nth(1).inputValue()

**Comment by isherkhan** [comment]
It worked thank you

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
