### ISSUE TITLE
[BUG] should get a non-session cookie fails on Chromium ToT

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#14725]
```

> playwright-internal@1.23.0-next ctest
> playwright test --config=tests/library/playwright.config.ts --project=chromium "tests\\library\\browsercontext-cookies.spec.ts:43" "--reporter=list"

Using executable at C:\Users\maxschmitt\Downloads\Win_x64_1006179_chrome-win\chrome-win\chrome.exe

Running 1 test using 1 worker

  ✘  [chromium] › library\browsercontext-cookies.spec.ts:43:1 › should get a non-session cookie (605ms)


  1) [chromium] › library\browsercontext-cookies.spec.ts:43:1 › should get a non-session cookie ====

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "username=John Doe"
    Received: ""

      50 |     return document.cookie;
      51 |   }, date);
    > 52 |   expect(documentCookie).toBe('username=John Doe');
         |                          ^
      53 |   const cookies = await context.cookies();
      54 |   expect(cookies.length).toBe(1);
      55 |   expect(cookies[0]).toEqual({

        at C:\Users\maxschmitt\development\playwright\tests\library\browsercontext-cookies.spec.ts:52:26


  1 failed
    [chromium] › library\browsercontext-cookies.spec.ts:43:1 › should get a non-session cookie =====
PS C:\Users\maxschmitt\development\playwright>
```

**Comment by mxschmitt** [comment]
Bisect range: https://chromium.googlesource.com/chromium/src/+log/d93b1011ef82e78b408181faa309a6f7a84dc489..3c9cf06d12947f01e3495fee4f3560b9c98e2d17

Good: 1006175
Bad: 1006179

Well reproducible and confirmed.

**Comment by mxschmitt** [comment]
Disabled the tests for now, search in the code base for the issue URL when fix is rolled.

**Comment by arichiv** [comment]
Can you confirm that the version used (Win_x64_1006179_chrome-win) is the same as https://chromereleases.googleblog.com/2022/06/dev-channel-update-for-desktop_10.html (the latest dev channel release)? We had a fix go in late in the canary stage that resolved an issue observed on windows https://chromium-review.googlesource.com/c/chromium/src/+/3684429

**Comment by arichiv** [comment]
I was able to reproduce on tip-of-trunk with the same inconsistency on windows only. I'll try to come up with a fix today and should be able to merge it into dev by end of week.

**Comment by arichiv** [comment]
Thanks for surfacing this, it ended up being a simple fix but would have been a disaster if it made it past dev to beta. Credit to @sbingler for figuring it out. https://chromium-review.googlesource.com/c/chromium/src/+/3702661

It's on main now, working to merge it into the M104 release as well and hope to have it in the weekly dev build.

**Comment by mxschmitt** [comment]
@arichiv thanks for keeping us updated!

**Comment by arichiv** [comment]
It's landing now and will make the new dev release tomorrow.
