### ISSUE TITLE
[BUG] Full page screenshot only captures viewport

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#14738]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows/Linux
- Browser: Chromium

**Code Snippet**
```javascript
// Do actions here to expand some rows
// This code generates a new baseline if no image is present
await expect(page).toHaveScreenshot({fullPage: true, animations: 'disabled'});
```

**Describe the bug**
The baseline image shows the rows are expanded, but only the viewport is captured - both top and bottom are clipped. Both for Windows Chromium and the official Playwright docker.

![image](https://user-images.githubusercontent.com/18096566/172820594-0d5df39b-08cd-4bd3-8924-3a508704e2cd.png)

**Comment by pavelfeldman** [comment]
We would need a reduced test case that we could reproduce locally for this.

**Comment by Exoow** [comment]
I figured the cause: the application's scrollbar is not at the top <body> tag. I'll have to find a workaround, sorry for the confusion.
