### ISSUE TITLE
[Question] webKit dependencies available for fedora 36 ?

### ISSUE THREAD

**Issue by pbadak** [microsoft/playwright#14736]
I tried running below simple python code on webKit on OS: fedora version: 36 (latest)
```from playwright.sync_api import Playwright, sync_playwright, expect
def run(playwright: Playwright) -> None:
    browser = playwright.webkit.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.amazon.in/")
    print(page.title())
    # ---------------------
    context.close()
    browser.close()
with sync_playwright() as playwright:
    run(playwright)
```

Initially I get below error ->

```Host system is missing dependencies to run browsers. 
 Missing libraries:                                   
     libpcre.so.3                                     
     libicui18n.so.66                                
     libicuuc.so.66                                  
     libjpeg.so.8                                    
     libwebp.so.6                                    
     libffi.so.7                            
     libx264.so  
```

So I created symblinks for all above mentioned dependencies like  libpcre.so.3 -> libpcre.so file present in my system as mentioned in one of the solution.
But after that I'm getting another error ->

```/home/pbadak/PycharmProjects/pythonProject1/venv/bin/python /home/pbadak/PycharmProjects/pythonProject1/main.py
Traceback (most recent call last):
  File "/home/pbadak/PycharmProjects/pythonProject1/main.py", line 21, in <module>
    run(playwright)
  File "/home/pbadak/PycharmProjects/pythonProject1/main.py", line 5, in run
    browser = playwright.webkit.launch(headless=False)
  File "/home/pbadak/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/playwright/sync_api/_generated.py", line 11557, in launch
    firefoxUserPrefs=mapping.to_impl(firefox_user_prefs),
  File "/home/pbadak/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/playwright/_impl/_sync_base.py", line 88, in _sync
    return task.result()
  File "/home/pbadak/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/playwright/_impl/_browser_type.py", line 90, in launch
    Browser, from_channel(await self._channel.send("launch", params))
  File "/home/pbadak/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/home/pbadak/PycharmProjects/pythonProject1/venv/lib/python3.7/site-packages/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> /home/pbadak/.cache/ms-playwright/webkit-1641/pw_run.sh --inspector-pipe --no-startup-window
<launched> pid=207860
[pid=207860][err] /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/bin/MiniBrowser: /lib64/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/lib/libwebkit2gtk-4.0.so.37)
[pid=207860][err] /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/bin/MiniBrowser: /lib64/libffi.so.7: version `LIBFFI_BASE_7.0' not found (required by /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/sys/lib/libgobject-2.0.so.0)
=========================== logs ===========================
<launching> /home/pbadak/.cache/ms-playwright/webkit-1641/pw_run.sh --inspector-pipe --no-startup-window
<launched> pid=207860
[pid=207860][err] /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/bin/MiniBrowser: /lib64/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/lib/libwebkit2gtk-4.0.so.37)
[pid=207860][err] /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/bin/MiniBrowser: /lib64/libffi.so.7: version `LIBFFI_BASE_7.0' not found (required by /home/pbadak/.cache/ms-playwright/webkit-1641/minibrowser-gtk/sys/lib/libgobject-2.0.so.0)
============================================================

Process finished with exit code 1
```
Is there a workaround to use webkit with playwright on fedora OS?

**Comment by pavelfeldman** [comment]
Not at this point, but we are likely to get it to work in the future.

**Comment by pbadak** [comment]
Thanks for the update @pavelfeldman .
I'm also getting below error on firefox when tried opening our internal URLs on fsame fedora 36.
```
playwright._impl._api_types.Error: SEC_ERROR_UNKNOWN_ISSUER
```
can you assist on the same.

**Comment by rsramkis** [comment]
I'm doing separate testing for Arch Linux and I noticed the following with Webkit:

~/Development/Playwright is 📦 v1.0.0 via  v16.15.0 took 21s
❯ npx playwright test --project=webkit

Running 25 tests using 2 workers
  1) [webkit] › example.spec.js:38:3 › New Todo › should clear text input field when an item is added

    browserType.launch:
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libpcre.so.3                                     ║
    ║     libicui18n.so.66                                 ║
    ║     libicuuc.so.66                                   ║
    ║     libwebp.so.6                                     ║
    ║     libenchant.so.1                                  ║
    ╚══════════════════════════════════════════════════════╝

Thought I would let you know has playwright support continues to grow.

**Comment by nlhkabu** [comment]
Hi @pbadak I have the exact same missing libraries when trying to run webkit on fedora 35.

Did you find a solution to this?  Are there alternative packages on fedora that I can use?

Thanks

**Comment by pbadak** [comment]
[@nlhkabu](https://github.com/nlhkabu) No I did not find any alternative package for that even I'm stuck here .

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by airtonix** [comment]
lol

**Comment by PagnuM** [comment]
I'm getting the same issue on Fedora 38

Error: browserType.launch: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libpcre.so.3                                     ║
║     libffi.so.7                                      ║
╚══════════════════════════════════════════════════════╝

**Comment by intsanerarity** [comment]
can we  get an update here? seems like chromium and firefox are working but the webkit isn't?

**Comment by ayoisaiah** [comment]
Same issue on Fedora 39:

![image](https://github.com/microsoft/playwright/assets/13372163/d63729f0-2dd8-4c93-9754-c4414cc07279)

**Comment by airtonix** [comment]
i came here originally due to a golang wrapper around playwright.

after seeing this ticket i just dropped playwright on the floor. and moved to using chromedp instead. 

I dont need a particular browser to be automated. but in theory chromedp can do them all.

**Comment by mysticaltech** [comment]
Like common folks, Linus Torvalds himself uses Fedora. We need support please!

**Comment by tifandotme** [comment]
Pwease add support for Fedora

**Comment by Lupphes** [comment]
Please add support for Fedora.

**Comment by mbledkowski** [comment]
@pavelfeldman Would you be interested in merging a pull request, adding support for other distributions? I think I know how to add support for many other distros, I just need a confirmation, that this is something, you are interested in maintaining afterwards.

**Comment by ahmafi** [comment]
Should I change my OS just to run playwright?!

**Comment by chris17453** [comment]
I'd love to use playwright in fedora...

**Comment by konstantinblaesi** [comment]
I managed to run the playwright webkit browser from a ubuntu 22.04 container on fedora 40 [using distrobox](https://github.com/89luca89/distrobox)

**Comment by AurelienQA** [comment]
adding my voice to the need of fedora support

**Comment by berkayalparslan** [comment]
where can i sign the petition to add fedora support? :D

**Comment by mysticaltech** [comment]
@berkayalparslan This is it brother, but unfortunately they closed it down already ignoring our wish.

**Comment by mysticaltech** [comment]
But in all honesty, via Python pip at least, playwright seems to work for me at least. It has some sort of compatibility mode.

**Comment by chrisolsen** [comment]
No Fedora support seems like typical Microsoft style. This is why I use GNU/Linux.

**Comment by Loki-Afro** [comment]
ridiculous that there is even an issue, though ms is loving linux now

**Comment by dlabaja** [comment]
+rep

**Comment by UnDesSix** [comment]
> But in all honesty, via Python pip at least, playwright seems to work for me at least. It has some sort of compatibility mode.

For me too. I usually work on Fedora (40 currently) and I do use playwright a lot.

I do have some missing libraries, but I still can make it works, at least codegen and for testing with headless=False.

Otherwise I am using a container with Ubuntu on it.

**Comment by liel-almog** [comment]
> This comment [here](https://github.com/microsoft/playwright/issues/29559#issuecomment-2322908078) fixed it for me - pasting here for convenience. So far seems to work fine for me 🥳
> 
> ```
> sudo dnf install -y \
>     libicu \
>     libjpeg-turbo \
>     libwebp \
>     flite \
>     pcre \
>     libffi
> ```

After installing I still get this error
```bash
Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libpcre.so.3                                     ║
║     libffi.so.7           
```

**Comment by Etherdrake** [comment]
> If you use anything unsupported you are in a world of pain.

Can confirm. Eventually you will forget Playwright is not supported on your OS which will result in you likely spending hours trying to find out why a different lib is having problems with Playwright while it's the OS issue all along.

**Comment by rkrisztian** [comment]
> For the love of god, why the most popular server linux distribution (rhel/fedora etc.) is not supported?

Just to be clear, on my RHEL9, Playwright works nicely with just the `npx playwright install` command executed (so no `npx playwright install-deps`, that's skipped). Despite the warning message about certain libraries missing, the browsers run just fine. This has been the case ever since I started using Playwright (somewhere in last year).

> Working brilliantly with Distrobox which takes 10 mins to set-up anyway.

Thanks for this tip, I'm sure this is a great workaround, although I find it a bit too inconvenient to run Playwright tests this way. If there is a native way, I prefer that over containerization.

**Comment by airtonix** [comment]
just use containers... local dev tooling that you cobble together with OS specific steps is very inconsiderate of other people on your team.

**Comment by rkrisztian** [comment]
@airtonix, as I said, I don't even need to run `npx playwright install-deps` in my case (using RHEL9 natively). So, I understand your viewpoint, but while Playwright's browsers still work just fine natively in the host Linux system, I would only suggest using DistroBox once the user actually sees problems with those browser binaries.

Yes, DistroBox is easy to use, and I would recommend it over any other containerization solution over the Linux host you already use, but the full convenience is provided by not having to containerize at all.
