### ISSUE TITLE
click three times on the same page rather than waiting for the page to reload .

### ISSUE THREAD

**Issue by viveksuarez7** [microsoft/playwright#14735]
I wanted to test a flow for my end to end testing ... for my single page application , Where on the click of the save and continue button i move to the next page but the playwright test fails as the button clicks on 'Save and Continue 'thrice before it goes to the next page. Because of this the the test case fails for the next page

**Comment by viveksuarez7** [comment]
// Select BGN
  await page.frameLocator('#storybook-preview-iframe').locator('select[name="ViewAccount\\.Currency\\.CurrencyCd"]').selectOption('BGN');
  // Click text=Save and continue
  await page.frameLocator('#storybook-preview-iframe').locator('text=Save and continue').click();

  

  await page.frameLocator('#storybook-preview-iframe').locator('text=Save and continue').click();

  // Click text=Save and continue
  await page.frameLocator('#storybook-preview-iframe').locator('text=Save and continue').click();

  // Click text=Save and continue
  await page.frameLocator('#storybook-preview-iframe').locator('text=Save and continue').click();``
  
  Save and Continue continues to click three times on the same page rather than waiting for the page to reload .

**Comment by pavelfeldman** [comment]
You should put `page.waitForURL(pattern)` after each click to wait for the navigation.

**Comment by viveksuarez7** [comment]
The Navigation url reamains the same .. after every save and continue in the flow . Though the page fetches new api data and renders a new step in the flow

**Comment by pavelfeldman** [comment]
Use this pattern then:

https://playwright.dev/docs/navigations#asynchronons-navigation

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
