### ISSUE TITLE
[Question]: How do I select options  in ant design version 4?

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#14734]
### Your question

https://ant-design.gitee.io/components/select-cn/ 
![image](https://user-images.githubusercontent.com/9427959/172765145-db856936-652c-4d5b-9a72-a2151df41603.png)

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-locator#locator-select-option

**Comment by god-pane** [comment]
do this:
page = context.new_page()
page.goto('https://ant-design.gitee.io/components/select-cn/', timeout=120 * 1000)
page.select_option('.ant-select-selection-search-input >> nth=18', label='z35')

throw:
waiting for selector ".ant-select-selection-search-input >> nth=18"
  selector resolved to visible <input readonly value="" type="search" role="combobox" …/>
  selecting specified option(s)
  Element is not a <select> element

**Comment by god-pane** [comment]
@pavelfeldman

**Comment by ltsuda** [comment]
This website is using some weird/really hard framework to work with but the following code passed here.

The website is not using the HTML `select` tags, so the `select-option` would not work, I think. 

```javascript
const { test, expect } = require("@playwright/test")

test("test select", async ({ page }) => {
    await page.goto("https://ant-design.gitee.io/components/select-cn/")

    // the box containing the dropdown you want
    const containerLocator = page.locator(".code-box#components-select-demo-size")

    // click the dropdown element to open list
    const selectDropdownLocator = containerLocator.locator(".ant-select-single")
    await selectDropdownLocator.click()

    const dropdownSelector = ".ant-select-dropdown"

    // wait for dropdown list to be attached
    const dropdownLocator = page.locator(dropdownSelector)
    const dropdownListLocator = dropdownLocator.locator("[role='listbox']")
    // role=listbox is not "visible" because width/height are 0px and style is "hidden"
    // so, waiting to be attached to DOM
    await dropdownListLocator.waitFor({ state: "attached" })

    // press "ENTER" key on desired item
    const item = dropdownListLocator.locator("[aria-label='a10']")
    // or
    // const item = dropdownListLocator.locator("text='a10'") // exact match for text 'a10'
    item.press("Enter")

    // ############## FAIL ##################
    // await item.click({ force: true }) locator.click: Element is outside of the viewport
    // await item.dispatchEvent("click") doesn't close the dropdown list

    // Wait for dropdown list to close
    // element is still attached but with a new class ".ant-select-dropdown-hidden"
    const dropdownHiddenLocator = page.locator(`${dropdownSelector}.ant-select-dropdown-hidden`)
    await dropdownHiddenLocator.waitFor({ state: "attached" })

    // expect dropdown selected item to have value
    const selectedLocator = selectDropdownLocator.locator(".ant-select-selection-item")
    await expect(selectedLocator).toHaveText("a10")
})

```

**Comment by god-pane** [comment]
There is a worse case, inside the selection, when the number of options reaches a certain number, you have to use the mouse to scroll in order to display the options, what should I do?
![image](https://user-images.githubusercontent.com/9427959/173013513-3b5b6ee1-7e7f-434d-b6d5-9db54c7dca32.png)

**Comment by ltsuda** [comment]
I'm not sure how to do that and I can't try right now.

You might need to perform some kind of loop, scrolling into the last item and validating until the item you want is present to send the ENTER key.

Maybe something using `await dropdownListLocator.locator(".ant-select-item").last().scrollscrollIntoViewIfNeeded()` to scroll to the last item of the list, then validate if the item you want is present, if not, continue the loop.

**Comment by AndriiFrolov** [comment]
scrollIntoViewIfNeeded did not help me :(

Code below works for me. Not looking good, but ... works

```
async setDropdownValue(select: Locator, dropdownValueId: string, text: string): Promise<void> {
    await select.click();
    let itemToSelect = this.page.locator(`//div[@id="${dropdownValueId}"]//following-sibling::div//div[contains(@class,'ant-select-item-option') and @title='${text}']`);
    
    const maxItemsToScroll = 50;//to avoid infinite loop
    for (let i = 0; i < maxItemsToScroll; i++) {
      let isItemVisible = await itemToSelect.isVisible();
      if (isItemVisible) {
        break;
      } else {
        await this.page.keyboard.press('ArrowDown');
      }
    }
    await itemToSelect.click();
  }
```

**Comment by Gagafeee** [comment]
If someone passes here, this simple approach worked for me :
```TS
export async function selectOption(page: Page, selectInputElement: Locator, optionLabel: string) {
    //Click on the select element
    await selectInputElement.click();
    await page.waitForTimeout(1000);
    //Get generated dropdown on the page
    const selectDropdown = page.locator(".ant-select-dropdown");
    //Click on the option
    await selectDropdown.getByText(optionLabel).click();
}
```
