### ISSUE TITLE
[REGRESSION]: Documentation outdated for toHaveScreenshot (naming screenshot no longer possible)

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#14733]
**Context:**
Playwright 1.22.2
Documentation 1.22

**Code Snippet**
Trying to define screenshot name per the following documentation, but this seems not possible.
(Yes I'm using Page object in this code, but same error goes for Locator.)
![image](https://user-images.githubusercontent.com/18096566/172784903-b013e34d-bb56-4402-9520-e1bb4ce8a968.png)
![image](https://user-images.githubusercontent.com/18096566/172784809-f693de9f-1208-44e1-bd12-f480174ed883.png)

**Describe the bug**
Documentation on both of these pages is incorrect:
https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot-1
https://playwright.dev/docs/test-snapshots

**Comment by pavelfeldman** [comment]
It should be fixed in v1.22.2

**Comment by Exoow** [comment]
> It should be fixed in v1.22.2
Already using 1.22.2 - sorry, I corrected the original post.

**Comment by pavelfeldman** [comment]
> Already using 1.22.2 - sorry, I corrected the original post.

I don't think you are, erase your node_modules and package-lock to ensure update to 1.22.2.

<img width="720" alt="Screen Shot 2022-06-11 at 8 01 15 AM" src="https://user-images.githubusercontent.com/883973/173193195-bbea0d9e-e57f-40a4-bbd9-fd411a9c078f.png">

**Comment by Exoow** [comment]
You are correct, there was a discrepancy between package file and node_module files. Thanks.
