### ISSUE TITLE
[Question] page.fill vs page.type

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#1473]
I was about to file an issue for the supposed race condition for `page.type` with sscce: https://github.com/aesyondu/bug-playwright-screenshot. However, I found out in this issue: https://github.com/microsoft/playwright/issues/811 that for inputs one should use `page.fill`

Why is there a need for two separate public apis, **fill** and **type**? What if, `page.fill` is hidden behind `page.type`, where if the selector evaluates to an input, then `page.type` will delegate to `page.fill`?

**Comment by aesyondu** [comment]
Filed an issue anyway: https://github.com/microsoft/playwright/issues/1474, since I captured a race condition even for `page.fill`

**Comment by aesyondu** [comment]
I think I get it now. I do have a use case where I just need to fill out the input. But I also have a use case where typing a few characters in the input triggers DOM UI events. But for that would it be possible to just make an option: `page.type("#myselector", "blah", { fill: true })`

**Comment by pavelfeldman** [comment]
We'd like `page.fill` to be used whenever one needs to fill a form. When you need fine-grained keyboard events, you use `page.type`.
