### ISSUE TITLE
[Question] Is locator.click() always click in the center of the button?

### ISSUE THREAD

**Issue by Nhasa** [microsoft/playwright#14737]
I use playwright 1.19.2 at the moment

Is locator.click() always click in the center of the button? what if I have element overlayed element on top of the button (partially but still clickable manually). For example, chat bubble is covering a portion of the button.
![image](https://user-images.githubusercontent.com/22735419/172817819-d00aef58-6397-4bf3-9cfb-ff4631fa56c0.png)

As you can see the button is visible (and clickable manually) but playwright saying that subtree intercept pointer event (due to overlayed chat bubble)

```
 locator.click: Timeout 60000ms exceeded.
    =========================== logs ===========================
    waiting for selector "#continue-contract"
      selector resolved to visible <button type="button" ng-click="continue()" id="continue…>…</button>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      <div class="intercom-lightweight-app-launcher-icon in…>…</div> from <div class="intercom-lightweight-app">…</div> subtree intercepts pointer events
```
Btw, below is the intercom bubble as I mentioned:
```html
      <div class="intercom-lightweight-app-launcher-icon in…>…</div> from <div class="intercom-lightweight-app">…</div> subtree intercepts pointer events
```
As a note, I think we could reposition chat bubble. The problem is the actual button we want to click is having a dynamic position (but still clickable manually). So reposition chat bubble is not the preferred solution

**Comment by MindaugasMateika** [comment]
> Is locator.click() always click in the center of the button?

From my experience - yes. But you can provide coordinates in the click options, at least in JS/TS.
https://playwright.dev/docs/api/class-locator#locator-click-option-position

**Comment by ltsuda** [comment]
If you guarantee that the button is interactable, you can use the option `force` to ignore the actionability.

https://playwright.dev/docs/api/class-locator#locator-click

**Comment by Nhasa** [comment]
Thanks @ltsuda 
 > If you guarantee that the button is interactable, you can use the option `force` to ignore the actionability.
> 
> https://playwright.dev/docs/api/class-locator#locator-click

I think using force option is discouraged? Based on the playwright lint rule? 
https://github.com/playwright-community/eslint-plugin-playwright#no-force-option

**Comment by pavelfeldman** [comment]
If you force, it'll click the center and hit your overlay. Your scenario looks like an edge case that we would not want to address. you can do `await locator.dispatchEvent('click')` to just dispatch it in JS and move on.

**Comment by Nhasa** [comment]
> If you force, it'll click the center and hit your overlay. Your scenario looks like an edge case that we would not want to address. you can do `await locator.dispatchEvent('click')` to just dispatch it in JS and move on.

Thanks @pavelfeldman.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
