### ISSUE TITLE
[BUG] Component test. Cannot use component with `path` methods used - Timeout of 10000ms exceeded.

### ISSUE THREAD

**Issue by pashidlos** [microsoft/playwright#14740]
**Context:**
- Playwright Version: 1.22.2

 System:
    OS: macOS 11.6.6
    Memory: 1.79 GB / 16.00 GB
  Binaries:
    Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
  Languages:
    Bash: 3.2.57 - /bin/bash

**Code Snippet**
https://github.com/pashidlos/pw-component-test-example/tree/import-interface

works if comment lines that use `path` methods
https://github.com/pashidlos/pw-component-test-example/blob/import-interface/src/TestComponent.tsx#L12-L14

**Describe the bug**

```
arn run v1.22.17
$ playwright test -c playwright-ct.config.ts

Running 1 test using 1 worker

vite v2.9.10 building for production...
✓ 39 modules transformed.
playwright/.cache/playwright/index.html      0.32 KiB
playwright/.cache/assets/index.6c700568.js   182.72 KiB / gzip: 56.87 KiB
  1) [chromium] › src/component_tests/TestComponent.pw-spec.tsx:5:1 › should work ==================

    Timeout of 10000ms exceeded.

    undefined: Target closed

      4 |
      5 | test("should work", async ({ mount }) => {
    > 6 |   const component = await mount(<TestComponent hint="Test"/>);
        |                           ^
      7 |
      8 |   await expect(component).toContainText("Test");
      9 | });

        at /Users/work/pw-component-test-example/src/component_tests/TestComponent.pw-spec.tsx:6:27


  1 failed
    [chromium] › src/component_tests/TestComponent.pw-spec.tsx:5:1 › should work ===================
error Command failed with exit code 1.
```

**Comment by mxschmitt** [comment]
`path` is a Node.js module which is not available inside the browser thats why its not working.

**Comment by pashidlos** [comment]
@mxschmitt yeah, that make sense 
the problem is even tho methods are not executed inside browser so I don't expect them to work in component 
they are just part of the utility lib that we have 
any chance we could bypass the error during transformation?

**Comment by dgozman** [comment]
@pashidlos Unfortunately, there is no way to bypass the error during transformation right now. I'd suggest to move the code that uses Node.js-specific APIs to a separate file (e.g. `pathHelpers.ts`). This way you can even use the helpers in your component tests, because tests run in Node.js.

**Comment by dgozman** [comment]
Closing as per above.

**Comment by Glebone23** [comment]
> @pashidlos Unfortunately, there is no way to bypass the error during transformation right now. I'd suggest to move the code that uses Node.js-specific APIs to a separate file (e.g. `pathHelpers.ts`). This way you can even use the helpers in your component tests, because tests run in Node.js.

@dgozman Hey you're little bit wrong about it, such libraries like `path` can be replaced with `path-browserify` for example. This trick can be made by passing [alias](https://vitejs.dev/config/#resolve-alias) to Vite config from [Playwright config](https://github.com/microsoft/playwright/blob/59fa61aef1d17f2c7fc2065f59a4c67b358c8ff1/packages/playwright-test/src/plugins/vitePlugin.ts#L36).

But, one more thing about this situation: many React applications use `react-scripts` (it uses Webpack 4 under the hood) to build and start an application.
And Webpack 4 provides big amount of aliases for Node.js packages (polyfills) to be used in browser (including `path` package). So some of the Node.js packages can be used in browser (by providing polyfill).

So it would be nice to at least mention this case in docs and describe how to use Playwright components testing with `react-scripts` and `webpack` if some of the Node.js packages used in application.

Thanks!
