### ISSUE TITLE
[BUG] page.type and page.fill race conditions on bootstrap modal with input elements

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#1474]
**Context:**
- Playwright Version: 0.11.1-next.1584853682027
- Operating System: Mac OS X 10.14.6
- Extra: node@13.11.0, npm@6.13.7, bootstrap@3.4.1, jquery@1.12.4

**Code Snippet**

sscce:
`page.fill` - https://github.com/aesyondu/bug-playwright-screenshot/commit/36d5cf8f9145d765ea3ab94827118c99333cbec0
`page.type` - https://github.com/aesyondu/bug-playwright-screenshot/commit/1cff9070c88671d039751d2c58a6bf168d45f118

**Describe the bug**
expected:
* given `python3 -m http.server -d src/` or any other http dev server to port 8000
* given `npm test`
* when `page.type` or `page.fill` is executed in *playwright.spec.js*
* then it should fully type the given value

actual:
* *sometimes* it does not fully type the given value

P.S. Also, taking a screenshot of the modal content does not FULLY capture the whole modal (limited by viewport), see `ss/` folder and differences between chromium, firefox, and webkit.

**Comment by aesyondu** [comment]
I added a test for input elements outside the modal: https://github.com/aesyondu/bug-playwright-screenshot/commit/2de9dbf62c9ae00030019db881a2bcec290c9653

It seems that the race condition only occurs for elements inside the modal.

**Comment by aesyondu** [comment]
I experimented further and added vuetify dialog/modal. It seems that it only occurs when bootstrap modal is used: https://github.com/aesyondu/bug-playwright-screenshot/commit/15ef20e40feb7c79fcadfa95b9ed39d4088567e7

Also I discovered that adding a timeout will eliminate the race condition. 100ms still has errors but 500ms doesn't: https://github.com/aesyondu/bug-playwright-screenshot/commit/8700130042145c0072ba2997bacb3cb044d8e178

**Comment by aesyondu** [comment]
Oof, just had an epiphany, what if I target the parent of the input elements instead (waitForSelector):
https://github.com/aesyondu/bug-playwright-screenshot/commit/252a7b825d567d2ef90e83e027a43e343a646b76

Sorry this was a non-issue to begin with.

**Comment by dbousamra** [comment]
Sorry to gravedig but we are coming across this on 0.12. We are seeing this only occur in GH actions, and maybe 40% of the time.

Anyone know the status of any "race condition" with page.type?
