### ISSUE TITLE
[BUG] exposeBinding() breaks in Webkit on a certain page

### ISSUE THREAD

**Issue by muodov** [microsoft/playwright#14745]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: v17.8.0
- Browser: WebKit
- Extra: nothing special

**Code Snippet**

```typescript
import { test, expect, Page, Frame } from "@playwright/test";

test.describe('xxx', async () => {
  test(`test exposeBinding`, async ({ page }) => {
    const url = "https://www.dastelefonbuch.de/"; // fails with this url
    // const url = "https://example.com/"; // works with this url
    await page.exposeBinding("exposedFn", messageCallback);
    await page.goto(url, { waitUntil: "commit" });

    let received = null;

    async function messageCallback({ frame }: { frame: Frame }, msg: any) {
      console.log("RECEIVED MESSAGE", msg);
      received = msg;
    }

    await page.waitForTimeout(1000); // seems to be important. I suspect the page is messing up the global context upon initialization

    console.log('trying to call the exposed function...');
    await page.evaluate(
      'exposedFn({ hello: "there" })'
    ); // hangs here
    console.log('...done');

    expect(received).toEqual({ hello: "there" });
  });
});

```

**Describe the bug**

The callback exposed with `Page.exposeBinding()` stops working on a specific page: https://www.dastelefonbuch.de/. It does seem to exist in page context, but the payload is never delivered to playwright scope.
It works when I change the URL or the browser, so it's really specific to WebKit and this particular website.

I run the above code with `npx playwright test doit.spec.ts --browser webkit`, so there's no extra config.

**Comment by mxschmitt** [comment]
Internal observation: the reason for that is that the site has overridden the `console.debug` function to a noop:

<img width="989" alt="image" src="https://user-images.githubusercontent.com/17984549/172851665-bbbab5fc-ebbe-471f-a4f0-3dea86a64356.png">

**Comment by pavelfeldman** [comment]
@[muodov](https://github.com/muodov) it does, but only on webkit, we'll fix it.
