### ISSUE TITLE
[Feature] Add more entries to response.securityDetails (and HAR output)

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright#14754]
The method `response.securityDetails` returns a few details regarding the certificate, but I'd love to get a few more, especially hashes of the certificate and/or the complete certificate itself (maybe as an option?).

I want to use it in [PlaywrightCapture](https://github.com/Lookyloo/PlaywrightCapture) (via the HAR output) and ultimately in [lookyloo](https://github.com/Lookyloo/lookyloo) in order to display more information about the page we're investigating. I think having that feature available in `response.securityDetails` would be useful for many other people than me.

Down the line, I'd like to push the certificates captured on lookyloo to [CIRCL passive SSL](https://circl.lu/services/passive-ssl/) service, which will require the full certificate.

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/issues/6759

**Comment by pavelfeldman** [comment]
Could you be more specific as to what you would like to see? This largely falls outside of the Playwright scope, so unless it is needed for testing, we are likely to close it.

**Comment by Rafiot** [comment]
It definitely relates to https://github.com/microsoft/playwright/issues/6759. I'd like to be able to get the serial number and the hashes (sha1 and sha256, at least) in `response.securityDetails` (and in the HAR export). The full certificate is definitely optional (but nice to have if possible).

I'm not using Playwright for testing, but that sounds like a useful information to me?

**Comment by pavelfeldman** [comment]
Folding into #6759!
