### ISSUE TITLE
[Question] Need a complex example to test react component which requires internationalization and redux store

### ISSUE THREAD

**Issue by stevez** [microsoft/playwright#14750]
I tried to implement a component test to our existing application but unsuccessful, due to our existing component requires following 2 things:
1. react-intl IntlProvider
2. redux store

Could you provide a more complex example on how to test the react component which requires intlProvider and redux store?

**Comment by pavelfeldman** [comment]
> react-intl IntlProvider

You don't need to do anything, it just works. There is nothing specific about react-intl when it comes to component testing. Or do you have a concrete question in mind?

> redux store

Same here, you can add your init code into playwright/index.js if you need certain setup. Could you be more specific in terms of what you need?

**Comment by hippyhorse** [comment]
I had similar issues with more complex dependencies - this thread might be useful? #15325

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/15325. We are embracing wrappers for context configuration. I.e. you create a wrapper component that does

```jsx
<Provider store={store}>
  <IntlProvider locale={language()} messages={messages}>
  ...
  </IntlProvider>
</Provider>
```
