### ISSUE TITLE
[BUG] Change in storageState/use behavior in Playwright 1.21 and 1.22

### ISSUE THREAD

**Issue by dwalleck** [microsoft/playwright#14759]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 16.15.1
- Browser: All

**Code Snippet**

The full reproduction of this issue can be found in [this repo](https://github.com/dwalleck/playwright-storage-state-use-reproduction).

```javascript
const { test, expect } = require('@playwright/test');
const path = require('path')
const fs = require('fs')
const { v4 } = require('uuid')

const generateStorageStateFile = (filename) => {
  const currentPathSegments = filename.split(path.sep)
  const storageStatePath = `storage-states/state-${currentPathSegments[currentPathSegments.length - 1]
    }-${v4()}.json`
  if (fs.existsSync(storageStatePath)) {
    fs.unlinkSync(storageStatePath)
  }
  return storageStatePath
}

const deleteStorageStateFile = (filePath) => {
  if (fs.existsSync(filePath)) {
    fs.unlinkSync(filePath)
  }
}

const storageStatePath = generateStorageStateFile(__filename)

test.beforeAll(async ({ browser }) => {
  const page = await browser.newPage()
  await page.goto('https://demo.playwright.dev/todomvc');
  console.log(`Setting storage state to ${storageStatePath}`)
  await page.context().storageState({ path: storageStatePath })
  await page.close()
})

test.describe('New Todo', () => {
  console.log(`test.use called with storageState ${storageStatePath}`)
  test.use({ storageState: storageStatePath })

  test('should allow me to add todo items', async () => { console.log('In test') })
})
```

**Describe the bug**

The above scenario worked for us through Playwright 1.20.2 . When I tried to upgrade to Playwright 1.21 or 1.22, I receive an error about the state file not existing similar to this:

```
Error: ENOENT: no such file or directory, open 'C:\Users\dwall\repos\playwright-storage-state-use-reproduction\storage-states\state-repro.test.js-755875be-fbda-41d9-a2d9-9ae5edeba758.json'
```

I've waited a bit to file this issue because it's difficult to say if what we had been doing before should have been valid. Our scenario is challenging because we cannot create a state file in a global fixture. A new entity is created for each test file, which each has its own admin user. This ordering of things works in Playwright 1.20.2, but not in any newer versions. My best guess is that some validation was added when setting the storage state path, but it also seems like the order of `beforeAll` may have also changed. We're trying to come up with a workaround, but I was interested to know if this was an expected change in behavior.

**Comment by pavelfeldman** [comment]
It will probably work if you move `storageStatePath = generateStorageStateFile(__filename)` into beforeAll, but overall, it does not sound like a recommended way of the storage reuse. Did you see https://playwright.dev/docs/auth#reuse-authentication-state ?

**Comment by pavelfeldman** [comment]
> the users are created on the fly with each test.

If that is the case, why are you using beforeAll, etc? Could you share more about your scenario? I suspect that there is an overall simpler solution.

**Comment by dwalleck** [comment]
Ugh, I misspoke. I meant a new user for each test file. Our beforeAll uses a fixture that provides the necessary credentials. This is what our actual beforeAll looks like:

```
test.beforeAll(async ({ browser, org }) => {
  const page = await browser.newPage()
  const loginPage = new LoginPage(page)
  await loginPage.login(
    org.newOrgData.adminEmail,
    org.newOrgData.adminPassword
  )
  await page.context().storageState({ path: storageStatePath })
  await page.close()
})
```
We did this outside of our describe block since the expectation is that the `beforeAll` block would be executed before the `test.use` statement. That assumption was true until Playwright 1.21. I dug around in the PRs for 1.21 and noticed that the topic of several PRs was related to how beforeAll and other hooks are executed ([this](https://github.com/microsoft/playwright/commit/9cd704220cede7d5f1e0a4babf8a47194462744c) was the only PR that I remembered to bookmark).

A better way to state our issue is that it appears that the order of operations for the `beforeAll` hook and `test.use` appear to have changed starting with Playwright 1.21. We're not certain if that was intentional or a side effect of other changes.

**Comment by pavelfeldman** [comment]
While we are figuring it out, you could use following patern:

```js
import { test } from '@playwright/test';
import path from 'path';
import fs from 'fs';

test.use({
  storageState: async ({ browser }, use, testInfo) => {
    const fileName = path.join(testInfo.project.outputDir, 'storage-' + testInfo.workerIndex);
    if (!fs.existsSync(fileName)) {
      const page = await browser.newPage()
      await page.goto('https://playwright.dev');
      await page.context().storageState({ path: fileName });
      await page.close();
    }
    await use(fileName);
  }
});

test('hello', ({ page }) => {
});
```

**Comment by pavelfeldman** [comment]
... or if you prefer beforeAll:

```js
import { test } from '@playwright/test';
import path from 'path';

let storageStatePath: string;

test.beforeAll(async ({ browser }, workerInfo) => {
  const page = await browser.newPage();
  await page.goto('https://playwright.dev');
  storageStatePath = path.join(workerInfo.project.outputDir, 'storage-' + workerInfo.workerIndex);
  await page.context().storageState({ path: storageStatePath });
  await page.close();
})

test.describe('Given an some conditions', () => {
  test.use({ storageState: ({}, use) => use(storageStatePath) });

  test('hello', ({ page }) => {
  });
})
```

**Comment by pavelfeldman** [comment]
@[dwalleck](https://github.com/dwalleck) ^^

**Comment by dwalleck** [comment]
Ahh, nice! I will try these options out in the morning and let you know how they work out. Thanks for the help!

**Comment by JCMais** [comment]
I just upgraded from `v1.19` to `v1.21` and I had the same issue as @dwalleck. The first workaround proposed by @pavelfeldman did work for me.

The second one did not, the use is called before the `beforeAll` hook is called. Execution is something like this:

```
test.use call inside test.describe
test.beforeAll outside the test.describe call
test.beforeEach <-- this does not call test.use again
```

The test I had before was similar to this one:

```ts
// ... snip

const storagePath = getRandomStateStoragePath()

test.beforeAll(async ({ browser, credentials }) => {
    const page = await getNewBrowserPage(browser)

    const signupPage = new SignupPage({ page })
    await signupPage.signupAsMemberAndStoreState(credentials, storagePath)

    await page.close()
})

test.describe('something', () => {
    test.use({ storageState: storagePath })
    
    test('bla bla', async () => {})
})
```

**Comment by cma-skedulo** [comment]
another option is to override storageState when creating a new login page inside test.beforeAll:
```typescript
test.beforeAll(async ({ browser }) => {
  const context = await browser.newContext({
    storageState: undefined
  });
  const page = await context.newPage();
  /**
   * login logic here
   */
  await context.storageState({ path: STORAGESTATE });
  await context.close();
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
