### ISSUE TITLE
I want to check If DOM is loaded or not? and if not I want to wait on the page till DOM loads.   - Playwright Java

### ISSUE THREAD

**Issue by shilpa32** [microsoft/playwright#14776]
I want to check If DOM is loaded or not? and if not, I want to wait on the page till DOM loads.   -  Playwright Java

Concern: Manually when I launch the browser, Icons are loading but from automation, it's not.

I tried with waits (  page.waitForSelector(locator, new Page.WaitForSelectorOptions().setState(WaitForSelectorState.VISIBLE)); )
but didnt worked.

**Comment by pavelfeldman** [comment]
Something else is wrong with your script, you should not wait for DOM, Playwright does it for you. We would need exact steps to reproduce in order to help.
