### ISSUE TITLE
[Question] Using Multiple Browser Contexts with Playwright Test

### ISSUE THREAD

**Issue by ElliottDevlinPA** [microsoft/playwright#14783]
Hi, I'm using Playwright Test v1.21.1 on MacOS and have a question regarding using multiple browser contexts within a test.

My use case is that I need to have two users log in to the same app in separate windows, carry out their own individual actions and have them completely independent of each other, i.e. no state can be shared across the two windows. From looking at your docs, I see that creating multiple browser contexts may be the way to accomplish this? 

However, I'm having some difficulties getting it to work, especially as the docs seem to show how to use multiple contexts when using Playwright Library, but I'm not clear how to do it when using Playwright Test.

This is the code that I have (based on the Library approach), but when I run the test, nothing happens. No browsers are launched and the test gets marked as passed, despite no steps being carried out.

    ` const browser = await chromium.launch();
      const reporterContext = await browser.newContext({ ignoreHTTPSErrors: true });
      const editorContext = await browser.newContext({ ignoreHTTPSErrors: true });

      const pageOne = await reporterContext.newPage();
      const pageTwo = await editorContext.newPage(); 

      pageOne.goto('https://app-url/wp-login.php');
      pageOne.locator('#user_login').type('reporter');
      pageOne.locator('#user_pass').type('reporterPass');
      pageOne.locator('#wp-submit').click();

      pageTwo.goto('https://app-url/wp-login.php');
      pageTwo.locator('#user_login').type('editor');
      pageTwo.locator('#user_pass').type('editorPass');
      pageTwo.locator('#wp-submit').click();`

Any guidance on this and what I'm doing wrong would be appreciated please!

Many thanks,
Elliott.

**Comment by pavelfeldman** [comment]
(You are missing await on every line starting with .goto)

I'll update the docs. For now:

```js
test('two profiles', async ({ browser }) => {
  const reporterContext = await browser.newContext();
  const editorContext = await browser.newContext();
  try {
    // ...
  } finally {
    await reporterContext.close();
    await editorContext.close();
  }
});

**Comment by ElliottDevlinPA** [comment]
Hi @pavelfeldman, thank you for your response - I am now able to launch two browser instances. 

Another question please - is it possible to create two new pages with the two separate browser contexts using my existing page objects? So, rather than creating a generic page object, can I specify that they are instantiated with my page object for the Login page of my app?

**Comment by ElliottDevlinPA** [comment]
I worked out how to do it - thanks for your help.
