### ISSUE TITLE
[REGRESSION]: `toHaveCSS` does not compute styles correctly

### ISSUE THREAD

**Issue by ritz078** [microsoft/playwright#14784]
**Context:**
- GOOD Playwright Version: 1.20.2
- BAD Playwright Version: 1.22.2
- Operating System: Mac

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://f3j9jj.csb.app/');
  const h1 = page.locator('h1');

  // This works
  expect(await h1.evaluate(node => window.getComputedStyle(node).backgroundImage)).toBe('linear-gradient(rgb(245, 240, 158) 0%, rgb(250, 247, 106) 100%)')

// This does not work
  await expect(h1).toHaveCSS('backgroundImage', 'linear-gradient(rgb(245, 240, 158) 0%, rgb(250, 247, 106) 100%)');
});
```

Live Example: https://try.playwright.tech/?l=playwright-test&s=7b961yt

**Describe the bug**

`toHaveCSS` does not calculate the computed value correctly anymore.

**Comment by mxschmitt** [comment]
It was actually not working correctly before and fixed in https://github.com/microsoft/playwright/issues/12629. You need to use the CSS property name, in your case: `background-image`. Then it will work as expected.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
