### ISSUE TITLE
[Feature] Select by accessible name

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#14782]
It's possible to interact with form controls by their `<label>`, but not to select them.

Other elements can also be labelled with `aria-label`/`aria-labelledby`, such as:

```html
<h2 id="list-of-things">A list of things</h2>
<ul aria-labelledby="list-of-things">
  <li>...</li>
</ul>
```

but there isn't a way (that I'm aware of) to select an element with the label 'A list of things'. 

The selector documentation gives the example

```ts
await page.locator('[aria-label="Sign in"]').click();
```

which is enough when using `[aria-label]`.

## Suggestions

- A `label` selector that works similar to `text` (`'label=A list of things'`, `'label="A list of things"'`, `'label=/A\\s*list\\s*of\\s*things/i'`) that works on `aria-label`, `aria-labelledby` and `<label>`.
- Recognise the `aria-labelledby` attribute and fill in `aria-label` with its text content. (Don't feel great, but means not extra selector.)

**Comment by thewilkybarkid** [comment]
Thanks, @lemnis, that's really useful (and something I can use now: https://github.com/PREreview/prereview.org/commit/9c963d8d87dba490196562859b97bff004a0c10d).

Hadn't spotted that the `role` selector was added recently, but going through the docs it looks really powerful.

> What it sounds like, you want to be able to select by accessible name without needing to define a role.

Yeah, but now I'm aware I can use the `role` selector I'll use it. I do wonder if it would still be useful (e.g. to help make sure there aren't duplicate accessible names, as well as being a simpler selector), but I'm happy to close this now.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by wkeese** [comment]
FYI, the doc is now at https://playwright.dev/docs/locators.  [getByRole()](https://playwright.dev/docs/locators#locate-by-role), [getByLabel()](https://playwright.dev/docs/locators#locate-by-label), etc.
