### ISSUE TITLE
[Question] Can I set string header in the playwright?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#14795]
My application URL is not loading using playwright because one of the key string is missing in the header api request. Is there any way I can add missing string value in the header api request?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/api/class-testoptions#test-options-extra-http-headers

In config, specify
```js
use: { extraHttpHeaders: { Name: 'Value' } }
```

or if using library, use

https://playwright.dev/docs/next/api/class-browser#browser-new-context-option-extra-http-headers

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by gauravgandhi1315** [comment]
@pavelfeldman Thank you! `page.setExtraHTTPHeaders` works for me.
