### ISSUE TITLE
How do perform operation on electron app after Login on first window is successful. Is there any sample code?

### ISSUE THREAD

**Issue by githubhappyKaur** [microsoft/playwright#14796]

**Comment by githubhappyKaur** [comment]
const {test} = require('@playwright/test');
const {_electron: electron} = require('playwright-core');

test('test click', async () => {
const electronApp = await electron.launch({executablePath:"C:/Program Files/TestApp+.exe"});
const appPath = await electronApp.evaluate(async ({ app }) => {
        return app.getAppPath();
  });
  console.log(appPath+" -App path");  
 test.setTimeout(120000); 

  let window = await electronApp.firstWindow();     
  console.log(await window.title());
   
  await window.fill('input[name="userid"]', 'UID');
  await window.fill('input[name="password"]', 'pwd');
  await window.click('text=Login');
 
  console.log("Login Successful. Going to Home page");

  await window.type('input[id="Name"]', 'Happy');
  await window.fill('input[id="Age"]', '18'); 
  await window.click('text=Go');

**Comment by pavelfeldman** [comment]
In is unclear what you mean by that, but maybe you have several windows? 
```js
const windows = electronApp.windows()
```

**Comment by githubhappyKaur** [comment]
I am not able to perform operations on second page after login is done and Home page is displayed. I am using the same methods fill and click to enter data and perform click operation on objects on second screen that I used for first login screen.

If there are some additional steps that i need to perform when we move from one screen to another I am looking sample code for that.

**Comment by dgozman** [comment]
@githubhappyKaur Is there any error? What's happening on the screen? If you could provide a repro (including your test and electron app), we can definitely take a look. Otherwise, something like screen recording would at least have a chance for a guess at the issue.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
