### ISSUE TITLE
[BUG] Video recording not working as it should

### ISSUE THREAD

**Issue by divysharma007** [microsoft/playwright#14823]
**Context:**
## System:
 OS: Windows 10 10.0.19044
 Memory: 43.17 GB / 63.99 GB
## Binaries:
Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
 npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD    
## npmPackages:
 playwright: ^1.22.2 => 1.22.2 

**Code Snippet**
```js
   use: {
        headless: true,
        screenshot: 'off',
        trace: 'on',
        storageState: 'storageState.json',
        video: 'on',
    }

```

**Describe the bug**

I am using the above in the playwright config file, video recording only shows a white screen
![image](https://user-images.githubusercontent.com/70777384/173341380-8349e41d-2452-44d8-b279-41d6738162e3.png)

**Comment by dgozman** [comment]
@divysharma007 Please share a test/script that developer could run locally to reproduce the issue.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by divysharma007** [comment]
@dgozman, I searched and came to know that it is happening with others as well. The issue is still open - [link](https://github.com/microsoft/playwright/issues/12266). thanks for looking into it.
