### ISSUE TITLE
[Question] - When step failed in the beforeEach hook - test still wait until global timeout

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#14820]
@playwright/test version: 1.20.2

When step failed in the beforeEach hook - test still wait until global timeout. 

Is it should act like that?

**Comment by dgozman** [comment]
@hananmalka I am not sure I understand the question. Usually, each test should terminate after reaching the test timeout. You can read more about [timeouts here](https://playwright.dev/docs/test-timeouts).

For more detailed help, could you please share a repro script and an error you are getting? Sharing Playwright report would also be nice.

**Comment by hananmalka** [comment]
Thanks @dgozman. I'm attaching a code sample. 
I hope it would be more clear now. 

Let's say I have global timeout of 1 minute, expect timeout of 10 seconds and action timeout of 30 seconds.

In the below test I'm waiting for response in the beforeEach hook.
If the waitForResponse condition will be failed - the test still wait for the global timeout.

My expectation is that the waitForResponse timeout (Or any action in the beforeEach hook) will be aligned to the action timeout (which mean in this case 30 seconds) and not to the global timeout. 

`playwright.config.js`

```
const config = {
  timeout: 60000,
  expect: { timeout: 10000 },
  reporter: [["allure-playwright"]],
  globalSetup: "./global-setup",
  testDir: "../tests",
  workers: 2,
  use: {
    headless: true,
    browserName: "chromium",
    baseURL: "https://playwright.dev/",
    trace: "retain-on-failure",
    storageState: "automation/storageState.json",
    actionTimeout: 30000,
  }
};

module.exports = config;
```

`example.js`
```
    test.beforeEach(async ({ page }) => {
      await page.goto();
     await this.page.waitForResponse(
      (resp) =>
        resp.url().includes("/example") &&
        resp.status() === 200
    );
    });

    test("Basic test for example", async ( {page} ) => {
      await page.goto();
});
```

**Comment by dgozman** [comment]
@hananmalka I tried your example and everything works as expected. Test execution finishes after 30 seconds, with an error in `beforeEach`. Could you please double-check on your side, or provide a fully-detailed repro that exhibits the problem?

```log
  1) a.spec.ts:34:1 › Basic test for example =======================================================

    page.waitForResponse: Timeout 30000ms exceeded while waiting for event "response"

      29 | test.beforeEach(async ({ page }) => {
      30 |   await page.goto('/');
    > 31 |   await page.waitForResponse(resp => resp.url().includes("/example") && resp.status() === 200);
         |              ^
      32 | });
      33 |
      34 | test("Basic test for example", async ({ page }) => {

        at <path>/a.spec.ts:31:14

  Slow test file: a.spec.ts (32s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    a.spec.ts:34:1 › Basic test for example ========================================================
```

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
