### ISSUE TITLE
[Feature] official Docker image on Docker Hub

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#1482]
I saw somewhere the discussion that it's still an ongoing process. But I would maybe keep this issue open until it's published under the Microsoft Docker Hub account.

**Comment by mxschmitt** [comment]
@arjun27 probably also a v1 blocker?

Needs to be changed here too since its referred to that in the docs for CircleCI:

https://github.com/microsoft/playwright/blob/193582445dea4ed3b6309777bfe945a23d3e1293/.circleci/config.yml#L4-L6

**Comment by idxn** [comment]
Will the official image be released any time soon?

**Comment by sajTempler** [comment]
I suppose this one is official:
https://github.com/microsoft/playwright/tree/master/docs/docker

**Comment by mxschmitt** [comment]
> I suppose this one is official:
> https://github.com/microsoft/playwright/tree/master/docs/docker

Yes, but it's not published to the Docker Hub.

**Comment by arjun27** [comment]
The official docker image is up! Find [Playwright on the Docker Hub](https://hub.docker.com/_/microsoft-playwright?tab=description).

```
docker pull mcr.microsoft.com/playwright:bionic
```

I'll follow-up with a docs change and close this PR. Thank you for your patience, everyone :)
