### ISSUE TITLE
[BUG] The following code is working fine in headed mode but doesn't work in headless mode, in Firefox. 

### ISSUE THREAD

**Issue by divysharma007** [microsoft/playwright#14821]
**Context:**
## System:
 OS: Windows 10 10.0.19044
 Memory: 43.17 GB / 63.99 GB
## Binaries:
Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
 npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD    
## npmPackages:
 playwright: ^1.22.2 => 1.22.2 

```js
   test('using CTRL+A/CTRL+C', async ({ page }) => {
            const window = await goToComposePane(page, MODE);
            await addCard(window); // add card
            await copyCardUsingKeyBoard(window); //copy it using CTRLA/CTRLC
            await pasteCard(window); //paste it using CTRL V
            await clipboard.write(RESET_STRING); //reset clipboard after using it
            await expect(window.locator(CARD_ADDED), errors.CARD_ADDED).toBeVisible(); // card should get pasted
        });
```
I am unable to copy the stuff in headless mode (firefox)

**Comment by dgozman** [comment]
@divysharma007 Could you please share the full test, including your helpers like `goToComposePane` and similar, and also the page url? This way we would be able to reproduce the issue locally and help you.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
