### ISSUE TITLE
[Question] Can be this framework used to automate tasks?

### ISSUE THREAD

**Issue by vamseekrishna9** [microsoft/playwright#14827]
As per documentation, it seems PlayWright can be used for end to end testing of web apps.

I would like to know, if can automate tasks such as navigating to certain path in the local file system and running some commands in the terminal., etc

**Comment by dgozman** [comment]
> I would like to know, if can automate tasks such as navigating to certain path in the local file system and running some commands in the terminal., etc

This sounds like generic scripting, and Playwright is not needed for that. You can write a script with something like [Node.js](https://nodejs.org/) that does all that.
