### ISSUE TITLE
[Feature] update only failing snapshots

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#14833]
from [docs](https://playwright.dev/docs/api/class-testconfig#test-config-update-snapshots) one can update all/missing/none (huh ?) snapshots
we have ±1000 snapshots, and the entire test run takes ± 20 minutes. now, for updating even 1 screenshot one needs to regenerate all.
I think this is a bit wrong and time-consuming

another case, which doesn't work correctly - if `maxDiffPixels` is used and comparison is passing, then after regenerating `all`  images, which were passing also are regenerated ( which forces to check differences - if those are 2-3 pixels, then some external tools are used as this doesn't get to report )

there was a bit related conversation [here](https://github.com/microsoft/playwright/issues/14226), but not loaded statics is less evil and cant be handled

**Comment by dimkin-eu** [comment]
As a solution - add flag `delete_if_not_match` to `toHaveScreenshot` , then regeneration of `missing` files will do the trick

Or maybe there are other ideas

**Comment by dgozman** [comment]
@dimkin-eu Could you please explain your workflow a little better? Some questions below:
- If you'd like to update one screenshot, what command do you run?
- Do you use `-g "test name I want to update screenshots for" -u` to update screenshots for a single test?
- Why do you regenerate all images (that `maxDiffPixels` issue)? Any specific reason?
- If we introduce "update only failing", how would you use it? Command line? Config?

**Comment by dimkin-eu** [comment]
We have such scripts for storybook testing in Merge Requests ( MR )

```
        "test-storybook": "playwright test storybook/",
        "test-storybook-with-update": "playwright test --update-snapshots storybook/",
```

Flow is 
- run `test-storybook` for tests ( MR `test` stage )
- if there are updates in UI or new tests - run `test-storybook-with-update` ( MR `test update` stage )

As there are only 2 options for snapshot regeneration ( `all` or `missing` ) we regenerating all.

After regeneration in the next MR stage snapshots are pushed. if snapshots are the same  - there is an empty git diff and everything is ok. 

Fun starts, when there is a bit difference (happens) - `maxDiffPixels` is set to `64` ( and we have no issues after that ), so rendering issues are covered with that, but on the update, such snapshots also are counted as changes and pushed.

The only idea that came to my mind - add the flag `delete_if_not_match` to `toHaveScreenshot`, which deletes the `golden` file after the test, then regeneration of missing files will do the trick ( it will take into consideration `maxDiffPixels` value. So far tests are very stable and there is no flakiness.

Grepping some tests would be a problem as tests look like the next snippet and are running against 11 different "browsers"

```javascript
someStorybook.forEach((story) => {
    test(story.name, async () => {
        await page.goto(storybookLocalhost + story.url)
        await expect(page).toHaveScreenshot(`${story.name}.png`, { scale: "device", caret: "hide", animations: "allow", maxDiffPixels: 64 })
    })
})
```
some explanation about params 
- `scale: "device"` - not `css` as this brings fewer rendering changes for smaller devices ( or there will be more regenerated snapshots )
- `animations: "allow"` - we pause animations in storybook

**Comment by dgozman** [comment]
@dimkin-eu Let me summarize the problem as I understood it:
- You are only able to run all tests, not those that may possible have changed snapshots.
- Updating all snapshots does not have the performance impact because you still run all the tests.
- However, small differences when updating snapshots (under `maxDiffPixels`) bring a lot of churn and non-empty diffs that you would like to avoid.

Is that a fair assessment?

**Comment by dimkin-eu** [comment]
> You are only able to run all tests, not those that may possible have changed snapshots.

sounds like yes - mostly because of `foreach` + tests were running against many `projects`. if rerunning 1 test would be easy one, but rerunning 1 test only for FF - not sure if i've met such option

> Updating all snapshots does not have the performance impact because you still run all the tests.

still pw waits for 2 consequent snapshots while running tests, which adds some extra time

> However, small differences when updating snapshots (under maxDiffPixels) bring a lot of churn and non-empty diffs that you would like to avoid.

yes, most painful part , because this issue has been started

i feel some innuendo here - how to distinguish good `golden` from bad one ? 😄 Thats why `delete failed` came to my mind

**Comment by dimkin-eu** [comment]
> Use --project="Firefox project name". Here are [CLI docs](https://playwright.dev/docs/test-cli).

Yes, this is valid for 1 failed test using 1 project. And if need to rerun `specA on projectB` and `testC from specD on projectE` and `testF from specG on projectH` - not sure if anyone will be happy to create grep for that and this is a completely different story and might be some specifics, I'm not searching for silver bullet here :)
