### ISSUE TITLE
[BUG] Debug window displaying No Source (ESM first)

### ISSUE THREAD

**Issue by lkauned2l** [microsoft/playwright#14835]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 18.2.0
- Browser: All

**Code Snippet**

Test I am trying to run:

```javascript
import { expect, test } from '@playwright/test';

test.only('basic test', async({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  await expect(title).toHaveText('Playwright');
});
```

**Describe the bug**

My team recently switched to ESM first and as such we now need to use `import` over `require`. However, I encountered an issue when running `--debug` with a test. The windows will open but the debug window says No source available:
![image](https://user-images.githubusercontent.com/100633775/173409294-bbda3acc-e872-4289-b51c-e5bee7da5133.png)

**Comment by pavelfeldman** [comment]
Should be fixed by e912b6897d496e5dedc9ce15e2c8e89ead01298f
