### ISSUE TITLE
Browsers (firefox, webkit) for mac are not available

### ISSUE THREAD

**Issue by jokinr** [microsoft/playwright#14852]
**Context:**
- Playwright Version: 1.22 (python)
- Browser: firefox, webkit

**Describe the bug**

![image](https://user-images.githubusercontent.com/46047015/173499061-df4af465-3382-4c4e-a8ae-b2b789427e3f.png)
![image](https://user-images.githubusercontent.com/46047015/173499156-136b1b36-2b20-4c39-bec5-81640c656fc6.png)

**Comment by mxschmitt** [comment]
the builds are called different:
- webkit-mac-12.zip
- firefox-mac-11.zip

why do you download them manually?
