### ISSUE TITLE
[Question] Expect.toThrowError with own function error tells me function does not throw error

### ISSUE THREAD

**Issue by machtyn** [microsoft/playwright#14869]
I've got a function in a POM class that attempts to select a checkbox on a table row. If it can't find the row, it will throw it's own error.

essentially, I have the following:
```
async function selectEvent(options) {
   // see https://stackoverflow.com/questions/72520456/selecting-a-specific-row-from-a-table-using-two-text-criteria-playwright-js for details on this function
   const row = await getRowByValues(options); // It will return null if no row is found.

   if (row) {
      row.locator('input[type="checkbox"]).setChecked(true);
   } else {
      throw new Error("Could not find the row.");
   }
}
```

When I try to test that this method throws an error when the row is not found, 

```
await expect( async () => {
    await selectEvent(options);
}).toThrowError("Could not find the row.");
```
I get "Received function did not throw" message.

What is the correct way to expect an error that my own method throws?

**Comment by dgozman** [comment]
This is because `toThrowError` expects the function to throw synchronously. Use [`rejects.toThrowError`](https://jestjs.io/docs/expect#rejects) for async functions.

```ts
await expect(async () => {
    await selectEvent(options);
}).rejects.toThrowError("Could not find the row.");
```
