### ISSUE TITLE
[Question] Is it possible to run one test on Firefox and others on chrome?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#14877]
I have 5 test cases in 3 separate js files. I want to run one file in Firefox and others in chrome. Is it possible to do that?

**Comment by dimkin-eu** [comment]
one way is adjusting config

```javascript
        {
            name: "Desktop-Firefox",
            testIgnore: ["foo.spec.ts", "bar.spec.ts"],
            use: {
                browserName: "firefox",
                viewport: { width: 1920, height: 1080 },
            },
        },
        {
            name: "Desktop-Chromium",
            testMatch: "**/spec_folder/**",
            use: {
                browserName: "chromium",
                viewport: { width: 1920, height: 1080 },
            },
        },
```

https://playwright.dev/docs/api/class-testproject#test-project-test-ignore

https://playwright.dev/docs/api/class-testproject#test-project-test-match

**Comment by dgozman** [comment]
As @dimkin-eu says, use [`testMatch`](https://playwright.dev/docs/api/class-testproject#test-project-test-match) or [`testIgnore`](https://playwright.dev/docs/api/class-testproject#test-project-test-ignore) in the config. If you can put Firefox-specific tests in a separate directory, you can also use [`testDir`](https://playwright.dev/docs/api/class-testproject#test-project-test-dir) config option.

Alternatively, you can [skip tests based on some condition](https://playwright.dev/docs/api/class-test#test-skip-4), for example check the `browserName`:

```ts
// Skip all tests in this file when running in Firefox.
test.skip(({ browserName }) => browserName === 'firefox');

test('does not run in Firefox', async ({ page }) => {
  // ... test goes here ...
});
```

**Comment by gauravgandhi1315** [comment]
@dgozman this config works fine. But I have `global-setup` for all the scripts


```
if (process.env.RunMode == undefined || process.env.RunMode !== 'local') {
    browser = await firefox.launch({ executablePath: '/usr/bin/firefox-browser' });
  } else {
    browser = await chromium.launch();
  }
```


How do I configure this for firefox and chromium?

**Comment by dgozman** [comment]
@gauravgandhi1315 I am not sure I understand your last question. What exactly would you like to configure?

**Comment by dgozman** [comment]
@gauravgandhi1315

- I don't think that browser launched in the `globalSetup` will be used in any tests.
- Global setup runs once before all chromium and firefox tests, so there should be no question about one vs another. Depending on your needs, you might need both, I guess.
