### ISSUE TITLE
[Question] How run the codegen on Edge browser 

### ISSUE THREAD

**Issue by madhuriinakollu** [microsoft/playwright#14879]
npx playwright open --viewport-size=800,600 --color-scheme=dark --browser=chromium twitter.com 

The above command is working fine.

npx playwright open --viewport-size=800,600 --color-scheme=dark --browser=msedge twitter.com

is not working. May i know how to record the code on an edge browser?

**Comment by dgozman** [comment]
Use `--channel` option:

```bash
npx playwright open --viewport-size=800,600 --color-scheme=dark --browser=chromium --channel=msedge twitter.com

# To see all available options:
npx playwright open --help
```

**Comment by rev233** [comment]
mark

> Use `--channel` option:
> 
> ```shell
> npx playwright open --viewport-size=800,600 --color-scheme=dark --browser=chromium --channel=msedge twitter.com
> 
> # To see all available options:
> npx playwright open --help
> ```
