### ISSUE TITLE
[Question] Config doesn't accept multiple storageState files

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14872]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Manjaro Linux
- Node.js version: 16.5
- Browser: Chromium

According to https://playwright.dev/docs/test-auth#multiple-signed-in-roles, it should be possible to use multiple storageState files for different roles (need a total of 5 different roles, probably more later).
However, that doesn't seem to be the case, as `playwright.config.ts` only accepts one storageStage file argument.
It is neither possible to list multiple files, nor is it possible to have multiple storageState entries (not that I expected that to work).

![Screenshot_20220614_175145](https://user-images.githubusercontent.com/98180468/173695424-8fee5100-a1bc-4afa-882b-76c54c1d438f.png)
![Screenshot_20220614_175244](https://user-images.githubusercontent.com/98180468/173695541-289ef35d-68e9-405a-9829-3130c5a24f55.png)

```
  globalSetup: require.resolve('./globalSetup'),

  use: {
    storageState: 'AdminStorageState.json', 'userStorageState.json',
    ...
  }
```

I have also tried it with brackets but that doesn't seem to be correct either:
```
  use: {
    storageState: {'adminStorageState.json', 'userStorageState.json'},
    ...
  }
```

https://playwright.dev/docs/api/class-testoptions#test-options-storage-state also doesn't indicate a usage of multiple storageState files.

If it is indeed possible to use multiple storageState files, the doc is missing the required information on how to set them up in the config.

**Comment by dgozman** [comment]
@azad-derakhshani-GS Multiple `storageState` files would mean multiple contexts with different storages. Since Playwright Test by default gives you a single context, you cannot configure multiple storage states in the config.

Possible solutions:
- Configure `storageState` on per-test-file basis. This is useful if you have different storages for different tests.
   ```ts
    // example1.spec.ts
    import { test, expect } from '@playwright/test';

    test.use({ storageState: 'adminStorageState.json' });

    test('test with admin', async ({ page }) => {
      // ...
    });


    // example2.spec.ts
    import { test, expect } from '@playwright/test';

    test.use({ storageState: 'userStorageState.json' });

    test('test with user', async ({ page }) => {
      // ...
    });
   ```
- Create multiple contexts in a single test if you need to test the interaction between multiple roles.
   ```ts
    // example.spec.ts
    import { test, expect } from '@playwright/test';

    test('test with user', async ({ browser }) => {
      // Create two pages in isolated browser contexts.
      const adminPage = await browser.newPage({ storageState: 'adminStorageState.json' });
      const userPage = await browser.newPage({ storageState: 'userStorageState.json' });
     
      // ... perform actions with adminPage and userPage ...
    });
   ```

I will update the docs accordingly.

**Comment by azad-derakhshani-GS** [comment]
> Possible solutions:
> 
> * Configure `storageState` on per-test-file basis. This is useful if you have different storages for different tests.

Aaah so I don't need to add it in the config if I add in the test files?
I thought having it in the config is a requirement for it to be used in the test files, at least in the doc it seemed that way to me.  
Thanks for clearing that up! Also wanted to offer to update the docs once I understood it, but I see you've already started. :)
