### ISSUE TITLE
Element selection, based on multiple inner selectors (that might not be in a parent/child relation)

### ISSUE THREAD

**Issue by DiogoLopes99** [microsoft/playwright#14881]
Hi all,

I have a mat-table:
Column1 | Column2
a | 1
a | 2
b | 1
b | 2
b | 3
c | 1

If I want to check that there is a row that has a cell with value 'a', I can simply use:
await page.waitForSelector('mat-row >> mat-cell >> text="a"');
or
await page.locator(`mat-row >> mat-cell >> text="a"`).waitFor();
or
await page.locator('mat-row', { has: page.locator(`mat-cell >> text="a"`) }).waitFor();
and a few other ways.

But what if I want to check that there is a row that has a cell with value 'a' and another cell with value '1'?
I didn't find an easy solution for this.
It would be nice to be able to do something like:
await page.waitForSelector('mat-row >> (mat-cell >> text="a" && mat-cell >> text="1")');

It might be that there is already a simple way to do this, but I did not find it.

**Comment by dgozman** [comment]
Use [`locator.filter`](https://playwright.dev/docs/api/class-locator#locator-filter) to filter by multiple descendants:

```js
await page.locator('mat-row')
    .filter({ has: page.locator('mat-cell >> text="a"') })
    .filter({ has: page.locator('mat-cell >> text="1"') })
    .waitFor();
```

Let me know if this works for you.

**Comment by DiogoLopes99** [comment]
It worked perfectly!

Reading the documentation (https://playwright.dev/docs/api/class-locator#locator-filter), it wasn't obvious for me that I could use multiple filters for this purpose, so maybe it would be useful for other developers if the documentation was a bit more descriptive in that sense.

Thanks!
