### ISSUE TITLE
[Question] why am I getting different headers in playwright chrome for the the following code from the ones that I get when I remove this code?

### ISSUE THREAD

**Issue by divysharma007** [microsoft/playwright#14888]
```js
await page.route(data.ENTITLEMENTS_API, async (route) => {
 let response = await page.request.fetch(route.request());
 route.fulfill({ response });
})
```
I am getting this in playwright chrome after adding this code
![image](https://user-images.githubusercontent.com/70777384/173872916-16ff140e-2bd8-459a-9615-44fd80434500.png)

**Comment by dgozman** [comment]
@divysharma007 This is expected, because technically browser does not send the request to the network - your code `page.request.fetch()` does it instead.
