### ISSUE TITLE
[Feature] add documentation around how to capture traces during the global setup

### ISSUE THREAD

**Issue by stephenkilbourn** [microsoft/playwright#14889]
Sometimes tests fail because of an error that occurs during the global setup. There's currently no clear guidance for how to set up tracing to assist with debugging. I would like to add documentation around how to do this with a try/catch loop to ensure the trace is closed before throwing the error. If there are no concerns, then I can open a PR.

As follow-up, it does feel like this would be a useful feature to enable by a flag in the config.

**Comment by azad-derakhshani-GS** [comment]
That's a great idea with the feature flag in the config!  
But otherwise the documentation of this would also be very helpful already.

+1 on both

**Comment by dgozman** [comment]
I think we should make existing [`trace`](https://playwright.dev/docs/api/class-testoptions#test-options-trace) option in the top-level `use` block apply to `globalSetup`. We will also need a way to include this trace in the report - I'll think about that. Feel free to file a new issue, or repurpose this one for a feature request.

**Comment by azad-derakhshani-GS** [comment]
> I think we should make existing [trace](https://playwright.dev/docs/api/class-testoptions#test-options-trace) option in the top-level use block apply to globalSetup.

Yeah I agree, that would be the most straightforward option!

**Comment by stephenkilbourn** [comment]
I can open a separate issue apply to apply to `globalSetup`  I'd be happy to help contribute to that. I wanted to dig into the existing code to see how that would work, anyways.
