### ISSUE TITLE
[Question] How can I upload a video generated via Playwright in Github Actions artifacts

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#14905]
Hi, I am running a bunch of e2e tests using Playwright and was wondering how I can upload the video generated in the github artifacts. I am currently trying to upload using this snippet, but the artifacts doesn't gets uploaded - instead it says that the video folder is empty.

```- if: always()
        name: Upload the e2e test video
        uses: actions/upload-artifact@v3.0.0
        with:
           name: tests-e2e-video
           path: videos
```

I am using `video : "true"` in my `options` and recording videos using this code 

```
global.context = await global.browser.newContext({
    recordVideo: { dir: "videos/" },
  });
```
The video gets generated when I run on my local, but on the github actions runner, it says 

`No files were found with the provided path: videos. No artifacts will be uploaded.`

**Comment by dgozman** [comment]
@zac11 What test runner do you use? This seems like a question about `actions/upload-artifact@v3.0.0` - perhaps ask on their [issue tracker](https://github.com/actions/upload-artifact/issues)?

**Comment by zac11** [comment]
@dgozman since the tests being run on an internal company network, the runners are configured as per the needs of company. However, it mimics somewhat the behavior of `ubuntu-latest`, but since there are other configs so I cannot say for sure. 
Also. let me open an issue for the actions team too.

**Comment by zac11** [comment]
@dgozman However, one thing is that I am successfully able to upload the HTML run report as an artifact.

**Comment by mxschmitt** [comment]
Closing as per above.
