### ISSUE TITLE
[Question] How do I change the headless browser language in python?

### ISSUE THREAD

**Issue by mlvps** [microsoft/playwright#14908]
```
context = browser.new_context()
context({locale: "en-US"})
```

I tried this, but all I get is:
`NameError: name 'locale' is not defined`

**Comment by dgozman** [comment]
[See documentation](https://playwright.dev/python/docs/emulation#locale--timezone).

```py
context = browser.new_context(locale="en-US")
```

**Comment by AnhPC03** [comment]
@dgozman, @mlvps

> context = browser.new_context(locale="en-US")
I set as you recommended but the browser language still was set based on my ip address
