### ISSUE TITLE
[Question] My tests are failing when i do headless = true and the same tests are passing when i do headless = false. What do i need to keep in mind when creating tests for headless = false

### ISSUE THREAD

**Issue by apakhil** [microsoft/playwright#14916]

**Comment by apakhil** [comment]
The test is very simple. I am navigating to a page and asserting if an element is visible or not on the page.
await expect(page.locator(xpath of the locator)).toBeVisible({timeout: 20000});

This is the line that gives error in headless mode and passes in headless = false mode.

**Comment by dgozman** [comment]
@apakhil Most likely, your page tries to detect a headless browser and does something different in that case. You can [record a trace](https://playwright.dev/docs/trace-viewer) to see what's happening inside the headless browser.

If you believe there is a bug in Playwright, please provide a scenario that we can run locally to reproduce the issue, and we'll happily fix it!

**Comment by dgozman** [comment]
Closing, as there is no action item here.

**Comment by yairEO** [comment]
I also experience this. all headless tests used to work fine and the page I am testing is a basic React app I created running on localhost. I suspect it is a matter of playwright configuration file or some change in the test Page Object Model and it's hard to know what change caused the tests to fail only in `headless` mode.

**Comment by makbulebahar2** [comment]
I have the same issue , my Playwright .NET test project  at the first locator when its in headless = true mode , completely fine in headfull mode
