### ISSUE TITLE
[Question] Can we add screenshot as base64 in playwright report?

### ISSUE THREAD

**Issue by arpitaggarwal-oyo** [microsoft/playwright#14918]
I want to attach screenshots in base64 format in playwright HTML reports. how can I achieve this?

**Comment by dgozman** [comment]
@arpitaggarwal-oyo You can write screenshot to a file and attach it.

```js
test('my test', async ({ page }) => {
  // assuming base64 is a string with base64-encoded screenshot in png format
  const file = test.info().outputPath('screenshot.png');
  await fs.promises.writeFile(file, Buffer.from(base64, 'base64'));
  await test.info().attach('my screenshot', { path: file });
});
```

**Comment by plh97** [comment]
where does that base64 variable come from?

![image](https://github.com/user-attachments/assets/bff725df-3113-4928-ac7d-fee5c4f24b76)
