### ISSUE TITLE
[Question] userdatadir and PID

### ISSUE THREAD

**Issue by Rumatoid** [microsoft/playwright#14910]
How can I launch browser to get his PID and pass user-data-dir argument?

**Comment by dgozman** [comment]
If you'd like to pass user data dir, use [`browserType.launchPersistentContext()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context). There is currently no API to get the PID. Could you provide more details about the usecase?

**Comment by Rumatoid** [comment]
I need to remote kill browser from pm2 process and pass userDataDir to locate my profiles

**Comment by dgozman** [comment]
@Rumatoid Why don't you call `browser.close()` instead? Or terminate the parent Node.js process?
