### ISSUE TITLE
[Feature] Pass multiple paths to `PLAYWRIGHT_BROWSERS_PATH`

### ISSUE THREAD

**Issue by aszenz** [microsoft/playwright#14911]
I have chrome and firefox binaries stored in different locations due to the way nix works, I can pass the path for one of them and everything works, but i haven't found a way to pass multiple paths where playwright can look for browsers.

I tried passing it like it is done for `$PATH`:

`/nix/store/jx108qlg3s1qc83yi94y39j98k3lsrj0-firefox-playwright:/nix/store/nlw1bkm089syp9ngy00jq2s7y0fv9mdj-chromium-playwright`

So each path separated by a colon but it didn't work

**Comment by dgozman** [comment]
@aszenz This is not supported today.

**Comment by rwoll** [comment]
@aszenz I'm not a nix user, so pardon my ignorance. Does nix allow you to relocate multiple builds/artifacts under one directory? For example, you could have your FF, CR, FFMPEG, and WK nix packages, and then create another package called PW_BUNDLE that depends on the others and puts them in one directory.

`PLAYWRIGHT_BROWSERS_PATH`, despite having a similar name to the UNIX `$PATH` variable, does not implement the colon based, multiple search paths that `$PATH` supports. It's exact value should be a valid directory path itself.

**Comment by aszenz** [comment]
Good idea, yes that is certainly possible and would fit my use case well.

**Comment by rwoll** [comment]
Awesome—since this is mostly nix build system related and there is a workaround, going to close for now. 

Please file a new issue and reference this one for any follow up!
