### ISSUE TITLE
[BUG] Install fails with node 16

### ISSUE THREAD

**Issue by dhochman-kroger** [microsoft/playwright#14929]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.14.2
- Browser: none
- Extra: none

**Code Snippet**

```shell
yarn add --dev @playwright/test
...
info @ffmpeg-installer/win32-x64@4.1.0: The CPU architecture "arm64" is incompatible with this module.
error opossum@5.1.3: The engine "node" is incompatible with this module. Expected version "^15 || ^14 || ^12 || ^10". Got "16.14.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Describe the bug**

Cannot install @playwright/test using `yarn add --dev @playwright/test`.
A dependency on opossum@5.1.3 fails in our environment with node v16.14.2.

**Hint**

opossum@6.1.0 added support for "node" ^16 in the "engines" section of package.json.

**Comment by mxschmitt** [comment]
Playwright does not depend on `@ffmpeg-installer/win32-x64` nor on `opossum` so the issue needs to be in some of your other dependencies!
