### ISSUE TITLE
[BUG] Wrong suffix added to screenshot files when running in a remote browser

### ISSUE THREAD

**Issue by MarioCadenas** [microsoft/playwright#14921]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.11.1
- Browser: All
- Extra: Running playwright browsers inside docker Linux image and connecting from the host through WebSockets

**Code Snippet**

Running this from linux docker image
```javascript
const {chromium, firefox, webkit} = require('playwright');

(async () => {
    await chromium.launchServer({
        headless: true,
        channel: 'chrome',
    });
    await firefox.launchServer({
        headless: true,
    });
    await webkit.launchServer({
        headless: true,
    });
})();
```

projects property in `playwright.config.js`

```javascript
    projects: [
        {
            name: 'chromium',
            use: {
                connectOptions: {
                    wsEndpoint: 'the websocket to connect for chrome',
                },
            },
        },
        {
            name: 'firefox',
            use: {
                connectOptions: {
                    wsEndpoint: 'the websocket to connect for firefox',
                },
            },
        },
        {
            name: 'webkit',
            use: {
                connectOptions: {
                    wsEndpoint: 'the websocket to connect for webkit',
                },
            },
        },
    ],
```

**Describe the bug**
I'm running server browsers inside the docker image that is running Linux, and I can properly connect from the host and the tests run fine. The problem comes with tests that include visual comparisons. 

The names generated for the screenshots are suffixed with the host operating system (`darwin`) instead of `linux` which would be the expected behavior since the browsers I'm connecting and running are on Linux.

**Comment by aslushnikov** [comment]
With https://github.com/microsoft/playwright/issues/7792, you'll be able to specify `snapshotPathTemplate` for the remote projects so that they reuse snapshots you'd like.

So merging this into https://github.com/microsoft/playwright/issues/7792
