### ISSUE TITLE
[Question] Is there a way to use persistent context and command-line args when using Playwright test runner

### ISSUE THREAD

**Issue by fara20222** [microsoft/playwright#14924]
In our test, we need to use persistent context as below to enable the Designer features. Right now, we are using Playwright as a library and using Jest to run the test. 

------args passed below works when Playwright is used as a library
const context = await chromium.launchPersistentContext('C:\\temp-edge\\edge-dev-profile', {
            headless: false,
            channel: "msedge-canary",
            args: ['--enable-features=NetworkService,NetworkServiceInProcess,msEdgeDesignerUI,msDisableHubPopupLightDismiss',
            '--enable-logging --v=0 --vmodule=*/components/edge_designer/*=1'],
        });

We want to switch to Playwright test runner as this is what our existing tests are doing. Could you confirm that:
1) Whether Playwright supports args as below, and if so how to do it. I tried to pass it from config.ts as below, but it doesn't work.
2) Is it possible to use persistent context in playwright/test and how? I only see a reference to page "test('test', async ({ page })" and am not sure how to get a persistent context from there.

-----args passed from config.ts don't work
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    browserName: 'chromium',
    acceptDownloads: true,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    channel: 'msedge-canary',
    args: ['--enable-features=NetworkService,NetworkServiceInProcess,msEdgeDesignerUI,msDisableHubPopupLightDismiss'],
    launchOptions: {
      slowMo: 100,
    },
  },

Thank you for your help.

**Comment by dgozman** [comment]
> Whether Playwright supports args as below, and if so how to do it. I tried to pass it from config.ts as below, but it doesn't work.

You should put `args` under `launchOptions`:
```ts
const config: PlaywrightTestConfig = {
  use: {
    launchOptions: {
      args: ['--enable-features=NetworkService,NetworkServiceInProcess,msEdgeDesignerUI,msDisableHubPopupLightDismiss'],
    },
  },
};
```

> Is it possible to use persistent context in playwright/test and how? I only see a reference to page "test('test', async ({ page })" and am not sure how to get a persistent context from there.

There is no built-in support. When using persistent context, you probably want to launch the browser with your `userDataDir` once per file? If so, you need to launch in `beforeAll`, similar to the [reuse page between tests](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests) guide.

```ts
// example.spec.ts

import { test, BrowserContext, Page } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

let context: BrowserContext;
let page: Page;

test.beforeAll(async ({ browserType }) => {
  context = await browserType.launchPersistentContext('my/user/data/dir');
  page = context.pages()[0];
});

test.afterAll(async () => {
  await context.close();
});

test('runs first', async () => {
  await page.goto('https://playwright.dev/');
});

test('runs second', async () => {
  await page.click('text=Get Started');
});
```

**Comment by fara20222** [comment]
Hi, thank you for your reply. Now I can have the designer turned on when args are passed under launchOptions. Thank you for that.

However, when I try to run the following snippet, it says "Error: beforeAll hook has unknown parameter "browserType".
  beforeAll hook defined at app-ui-tests\edge\edge2.spec.ts:8:6
    at errorWithLocations (D:\OC\designer.app\.yarn\cache\@playwright-test-npm-1.22.2-fa49b9813b-55392a97d9.zip\node_modules\@playwright\test\lib\fixtures.js:460:10)
    at FixturePool.validateFunction (D:\OC\designer.app\.yarn\cache\@playwright-test-npm-1.22.2-fa49b9813b-55392a97d9.zip\node_modules\@playwright\test\lib\fixtures.js:280:32)" Any ideas why this is happening?

test.beforeAll(async ({ browserType }) => {
  context = await browserType.launchPersistentContext('my/user/data/dir');
  page = context.pages()[0];
});

**Comment by dgozman** [comment]
My bad, `browserType` is not a thing. Correct snippet:

```ts
test.beforeAll(async ({ playwright, browserName }) => {
  context = await playwright[browserName].launchPersistentContext('');
  page = context.pages()[0];
});
```

**Comment by fara20222** [comment]
That works! Thank you so much for your timely help!
