### ISSUE TITLE
[BUG] Background page doesn't handle 'request' & 'response' event  

### ISSUE THREAD

**Issue by AlterB** [microsoft/playwright#14936]
**Context:**
- Playwright Version: 1.22.0
- Operating System: Linux - Debian 9
- Python version: 3.9.6
- Browser: Chromium

**Code Snippet**

```python
import asyncio
from playwright.async_api import async_playwright



extensionPath = f"path/to/estension"
user_data_dir = f"browser-data-repr"
extensionID = f"ID"



browser_opt = [
        f"--disable-extensions-except={extensionPath}",
        f"--load-extension={extensionPath}",
        f"--no-sandbox",
        f"--disable-setuid-sandbox",
        f'--ignore-certificate-errors'
]


async def main():
    async with async_playwright() as p:
        # start Chromium with extension 
        browser = await p.chromium.launch_persistent_context(
                user_data_dir,
                headless=False,
                args=browser_opt
        )
      
        background_page = await browser.wait_for_event('backgroundpage')
        print(background_page)
        background_page.on("request", lambda request: print(">>", request.method, request.url))
        background_page.on("response", lambda response: print("<<", response.status, response.url))

        extPage = await browser.new_page()
        await extPage.goto("chrome://extensions/")
        async with extPage.expect_navigation(timeout=1200000):
            pass 

asyncio.run(main())
```

**Describe the bug**

I'm trying to retrieve the network requests/responses from an extension's background page, but the code doesn't log any activity.
It seems like the background_page object doesn't handle the events.

Does anyone have experienced this problem?

**Comment by dgozman** [comment]
@AlterB Would you mind sharing a sample extension that exhibits this problem?

**Comment by AlterB** [comment]
I just created a sample extension that fetches google.com every 5s from the background.
I also notice that sometimes it throws the following error:
`playwright._impl._api_types.TimeoutError: Timeout 30000.0ms exceeded while waiting for event "backgroundpage"`
[hello-world.zip](https://github.com/microsoft/playwright/files/8943842/hello-world.zip)

**Comment by mxschmitt** [comment]
Thanks! I was able to repro and identify the issue.
