### ISSUE TITLE
[BUG] Typo in doc

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#14930]
The newly merged documentation update in https://github.com/microsoft/playwright/pull/14891 introduced a typo, so I would like to fix it.

This part:
`and you must ensure that of your that you [stop tracing](./api/class-tracing.md#tracing-stop) if an error occurs before that error is thrown.`

should be:
`and you must ensure that you [stop tracing](./api/class-tracing.md#tracing-stop) if an error occurs before that error is thrown.`

Furthermore, there is also an error here:
`const context = await browser.newPage();`

This needs to be changed to:
`const context = await browser.newContext();`

Also there is an unnecessary exclamation mark in line 375 which was flagged by my IDE:
`await page.goto(baseURL!);`

Also the `storageState` in line 379 and 409 wasn't formatted correctly.

**Comment by Itimol82** [comment]
__
