### ISSUE TITLE
[BUG] baseURL type definition error

### ISSUE THREAD

**Issue by frederikhors** [microsoft/playwright#14945]
**Context:**
- Playwright Version: "@playwright/test": "1.22.2",
- Operating System: Windows
- Node.js version: v16.15.1

**Describe the bug**

I'm using this config:

```ts
const baseURL = "someURL";

const config: PlaywrightTestConfig = {
  // ...
  use: {
    baseURL,
    // ...
  },
  // ...
};
```

and in my tests:

```ts
test.describe.parallel("test", () => {
  test.beforeEach(async ({ page, baseURL }) => {
    await page.goto(baseURL); // typescript error, see below
	});
  // ...
})
```

but this is the Typscript error:

```
Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.ts(2345)
```

And it is understandable.

How to fix this?

**Comment by ville-nvt** [comment]
If you have baseUrl configured you can just use goto("/")

**Comment by dgozman** [comment]
As @ville-nvt suggests, you don't usually need to reference `baseURL` directly, you use relative urls instead.

```js
await page.goto('./foo/bar');
```

If you really need `baseURL`, silence TypeScript by adding an exclamation mark.

```js
await page.goto(baseURL!);
```

**Comment by dgozman** [comment]
@frederikhors The example above works for me with Playwright v1.23. Could you please share a full repro that we can run locally to debug the issue?

**Comment by KeionneDerousselle** [comment]
> 

This happens to me as well when trying to use `page.goto('/login');` in my global setup file. I think for some reason the `baseURL` is not available yet in the global setup file. Don't know if this is the best workaround, but I ended up doing this:

```ts
import { chromium, FullConfig } from '@playwright/test';
import { users, login } from './utils/auth';

async function globalSetup(_: FullConfig) {
  const baseURL = _.projects?.[0]?.use?.baseURL;
  const browser = await chromium.launch();

  for (const user of Object.values(users)) {
    const page = await browser.newPage();
    await login(page, user.auth, baseURL);
    await page.context().storageState({ path: user.contextStoragePath });
  }

  await browser.close();
}

export default globalSetup;
```
🤷🏽‍♀️

**Comment by hornta** [comment]
> @frederikhors The example above works for me with Playwright v1.23. Could you please share a full repro that we can run locally to debug the issue?

The baseUrl is not working when navigating to "/" in global setup files. It works only in the tests.

**Comment by umairnazeer** [comment]
> @ville-nvt, @dgozman this doesn't work.
> 
> If I use `await page.goto('./foo/bar')` or `await page.goto('/')` it throws with:
> 
> ```
> page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
> =========================== logs ===========================
> navigating to "/", waiting until "load"
> ============================================================
> ```
> 
> even if `baseURL === "http://localhost:3000"`.
> 
> I think we should re-open this.

I am still facing this issue

**Comment by ltsuda** [comment]
I might be wrong because I don't know TypeScript, but isn't this code wrong?

In the [documentation](https://playwright.dev/docs/test-advanced#global-setup-and-teardown), `baseURL` configuration expects a string, but in the code below, at the top we set a custom const `baseURL` and in the `use` block, isn't the `baseURL` wrong? Like, there, the `baseURL` is the configuration option that is expecting `= some variable or string` from the top constant. Or using this way will spread/destruct the top constant?

I'm sure I explained correctly my thoughts.

```javascript
const baseURL = "someURL";

const config: PlaywrightTestConfig = {
  // ...
  use: {
    baseURL,
    // ...
  },
  // ...
};
```

For me, it should be like this:

```javascript
const mybaseURL = "someURL";

const config: PlaywrightTestConfig = {
  // ...
  use: {
    baseURL = mybaseURL ,
    // ...
  },
  // ...
};
```

**Comment by umairnazeer** [comment]
I actually resolve it. I was not providing the config reference in the command when running a single file

**Comment by AndrewPahomovOtto** [comment]
baseURL really doesn't work in globalSetup. I resolvet it just import config and use `await page.goto(String(config.use?.baseURL))`

**Comment by CsillaCsipak** [comment]
If Docker runs my code, it fails at this point, what can I do? I do not want to hardcode the url everywhere, because I also have got a custom testconfig.ts with different environments: (export const testconfig = { qa: , dev:}) 

`Tests/Login.test.ts:4:5 › @Navigate to Login form an login › Open browser ─────────────────────

   Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
  =========================== logs ===========================
  navigating to "/", waiting until "load"
============================================================
      await page.goto('/');
               });`

**Comment by dsarlo-viso** [comment]
Having the same issue on the latest version. BaseUrl does nothing

**Comment by TommyGods** [comment]
Has anyone found a resolution for this issue
`page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
=========================== logs ===========================
navigating to "/", waiting until "load"
============================================================`

I have the baseURL set in playwright.config.ts

**Comment by NedxLab** [comment]
i ran into this issue when trying to use in my globalSetup and i want to put this out there for whoever needs it " 
`const browser = await chromium.launch();
 // Create a new context with the config's baseURL
    const context = await browser.newContext({
      baseURL, // Ensure the context uses the config's baseURL
    });
    const page = await context.newPage();"`

this should work

**Comment by NedxLab** [comment]
> > i ran into this issue when trying to use in my globalSetup and i want to put this out there for whoever needs it " `const browser = await chromium.launch(); // Create a new context with the config's baseURL const context = await browser.newContext({ baseURL, // Ensure the context uses the config's baseURL }); const page = await context.newPage();"`
> > this should work
> 
> Hi, I've just run into this as well.
> 
> Could you elaborate on your answer a bit more, as it's not clear. Would you be able to post your full setup file for reference sake?
> 
> I've tried using this as a reference https://playwright.dev/docs/test-global-setup-teardown#example but it doesn't work reliably, What's frustrating is it will work sometimes, then randomly stop working with the protocol error. It's really difficult to figure out why it works, then suddenly doesn't.
> 
> Surely this issue needs some resolution, if people are still experiencing it after this long?
> 
> Thanks,

sorry if i wasn't clear enough but to be sure we have the same problem, my baseUrl wasn't being picked up in the globalSetup but it is being picked up assuming i don't use the global setup.
this is the global setup function `async function globalSetup(config: FullConfig) {}`
i take the baseurl from the playwright config `const baseURL = config.projects[0].use.baseURL;
  if (!baseURL) {
    throw new Error("baseURL is not defined in Playwright config");
  }
  console.log("Using baseURL in globalSetup:", baseURL);`
depending on where your use object is, that determines the array index it'll be in. then just continue with my previous reply. remember to pass the baseURL in the command line when trying to run the npx playwright test command.

**Comment by sonicviz** [comment]
Thanks for the clarification. 

I can't figure out the trigger that makes it suddenly work, or the trigger that makes it suddenly not work. 
It's bizarre behavior.

**Comment by NedxLab** [comment]
> Thanks for the clarification.
> 
> I can't figure out the trigger that makes it suddenly work, or the trigger that makes it suddenly not work. It's bizarre behavior.

You might have to try and comment out the globalSetup from the playwright config to see if others tests pick up the base url, you might be passing it wrongly, secondly, try and console.log the base url in the globalsetup file to be it's reaching there, if it reaches there, then try adding it directly to the newContext as I already did. Might require more debugging, Goodluck, some days are like that

**Comment by sonicviz** [comment]
I've done both those already, and it is getting passed through. 
It's actually "page.goto: Protocol error (Page.navigate): Cannot navigate " https://ray.run/discord-forum/threads/60152-trouble-getting-baseurl-to-work-error-pagegoto-protocol-error-pagenavigate-cannot-navigate-t but at the moment I'm rechecking anything related to try to resolve it.
