### ISSUE TITLE
How to modify a display: style in an element

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#14956]
Hello, i was looking for a method with playwright to modify an element style, so i can change the display : inner.line to display : block

I did something like this, not working:

await page.evaluateHandle('selector', style => style.innerHTML = 'display: block');

**Comment by dgozman** [comment]
Use [`locator.evaluate`](https://playwright.dev/docs/api/class-locator#locator-evaluate) to access [`element.style`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/style):

```js
await page.locator('selector').evaluate(element => element.style.display = 'block');
```

**Comment by NicoloLattanzio** [comment]
I did this but isnt working 

await page.locator('body > div.wrapper > img').evaluate(element => element.style.display = 'block');

**Comment by dgozman** [comment]
@NicoloLattanzio Could you please provide a repro we can run locally to help you?

**Comment by Develop5** [comment]
Hello, Any news about this topic?

**Comment by ryanewtaylor** [comment]
Setting `element.style.display` did not work for me but using `element.style.setProperty` does. Here, I'm using pytest but I suspect it'll work just fine if using Node.

```python
div.evaluate("element => element.style.setProperty('display', 'block' , 'important')")
```
