### ISSUE TITLE
[Question] Can we access the current retry and Mac retries in on test end in custom reporter

### ISSUE THREAD

**Issue by jithinjosejacob** [microsoft/playwright#14950]
Can we access current retry and max retry count in custom reporter in test enc

**Comment by Nav-2d** [comment]
https://playwright.dev/docs/api/class-testcase#test-case-retries
https://playwright.dev/docs/api/class-testresult#test-result-retry

Snippet:
```
project.allTests().forEach((test) => {
        test.results.forEach((result) => {
         if (result.retry < test.retries) {
            retryCount = retryCount + 1;

```
