### ISSUE TITLE
[Feature] - Playwright needs to support electron app testing with dotnet/C#

### ISSUE THREAD

**Issue by HarikrishnanVK** [microsoft/playwright#14955]
We do have a requirement to automate electron application using dotnet framework and c# as language. 

Recently we discovered playwright provides effective support on testing electron application but only with nodeJS. 

With dotnet playwright do support chromium, firefox based web testing but not electron.

So requesting playwright team to add the electronApp package to the dotnet platform.

**Comment by Itimol82** [comment]
hi . let me know if you need any help . tnx
