### ISSUE TITLE
One test case only works when debugging. If not it fails with error :  ThreadOperations.ExecuteWithAbortSafety

### ISSUE THREAD

**Issue by mkgn** [microsoft/playwright#14965]
I am using MSTest with playwright.

The scenerio I am testing is a successful login where I give a correct user/pass and it should take the user to dashboard.

current steps are;

            await Page.GotoAsync("http://mysite.com/");
            await Page.Locator("[placeholder=\"Username\"]").FillAsync("admin");
            await Page.Locator("[placeholder=\"Password\"]").FillAsync("admin123");
            await Page.Locator("button:has-text(\"Sign In\")").ClickAsync();

   
            isLoggedIn = await Page.Locator("button:has-text(\"Sign out\")").CountAsync();
            System.Diagnostics.Debug.WriteLine(isLoggedIn);
            Assert.IsTrue(isLoggedIn == 1);

To check the successful login, I check for a button with Sign out text.

The issue is, if I run this in debug mode, it always passes. But if I just run it, it fails always (it doesn't seem to find the signout button. It doesn't take much time to login if you test it manually (~1 seconds you are logged in consistently). The result shows below.

![image](https://user-images.githubusercontent.com/8392595/174429809-3182fc6a-3cb0-4e16-a00e-9abb4f18d749.png)

It points to Assert.IsTrue(isLoggedIn == 1); line. However in debug mode it works fine.

What may be the reason? Not sure whether this is playwright or MSTest playing.

**Comment by dgozman** [comment]
@mkgn As you said, it takes ~1 second to log out. Playwright runs your test very fast, so by the time you check for the "Sign out" button, 1 second did not pass yet, and the button is not there. You should use one the [web-first assertions](https://playwright.dev/dotnet/docs/test-assertions) that takes care of the auto-waiting for you.

```csharp
var locator = Page.Locator("button:has-text(\"Sign out\")");
await Expect(locator).ToBeVisibleAsync();
```
