### ISSUE TITLE
[BUG] Some firefox console messages with workers are not getting shown

### ISSUE THREAD

**Issue by PaperStrike** [microsoft/playwright#14974]
**Context:**
- Playwright Version: 1.22.2, 1.23.0-alpha-jun-20-2022
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: All
- Extra:

**Code Snippet**

```javascript
const playwright = require('playwright');

(async () => {
  for (const browserName of ['chromium', 'firefox', 'webkit']) {
    console.log(`=== ${browserName} ===`);
    const browser = await playwright[browserName].launch();
    const page = await browser.newPage();
    page.on('console', console.log);
    await page.evaluate(async () => {
      console.log('before worker');
      const worker = new Worker(URL.createObjectURL(
        new Blob(
          ['console.log(\'inside worker\')'],
          { type: 'application/javascript' },
        ),
      ));
      console.log('after worker');
      worker.terminate();
      console.log('after terminate');
      await new Promise((resolve) => {
        setTimeout(() => {
          console.log('after 100ms');
          resolve();
        }, 100); // Lower ms might not print in firefix
      });
    });
    await browser.close();
  }
})();
```

**Describe the bug**

The code above produces:

```
=== chromium ===
before worker
after worker
after terminate
after 100ms
=== firefox ===
before worker
after 100ms
=== webkit ===
before worker
after worker
after terminate
after 100ms
```

If the worker is not being terminated immediately like the code above, the `inside worker` will be printed out in and only in Firefox. Chromium and Webkit ignore the worker messages at all times. Firefox ignores all messages when there's a worker and the worker is being terminated immediately.

I first met this on 1.23.0-alpha-jun-19-2022, then switched to 1.22.2 and 1.23.0-alpha-jun-20-2022, but got the same results.

**Comment by PaperStrike** [comment]
ah..

**Comment by mxschmitt** [comment]
The creation of the worker is not synchronous, so I modified your example to wait until the worker is ready. Then `inside worker` gets printed all the time in the browsers:

```js
const playwright = require('playwright');

(async () => {
  for (const browserName of ['chromium', 'firefox', 'webkit']) {
    console.log(`=== ${browserName} ===`);
    const browser = await playwright[browserName].launch();
    const page = await browser.newPage();
    page.on('console', console.log);
    await page.evaluate(async () => {
      console.log('before worker');
      const worker = new Worker(URL.createObjectURL(
        new Blob(
          [
            'console.log(\'inside worker\');',
            'self.postMessage(\'ready\');',
          ],
          { type: 'application/javascript' },
        ),
      ));
      // wait until worker is ready
      await new Promise(resolve => worker.addEventListener('message', resolve));
      console.log('after worker');
      worker.terminate();
      console.log('after terminate');
    });
    await browser.close();
  }
})();
```

So I see only a bug in Firefox that the `after worker` and `after terminate` does not get printed?

**Comment by PaperStrike** [comment]
@mxschmitt Thank you. I forgot about the creation is not synchronous. So it's only a bug with Firefox. Has the issue already been tracked elsewhere? This bug makes Firefox output nothing when there's a worker and I have to use headed mode to see the the console, which is a bit annoying.

**Comment by mxschmitt** [comment]
It has not, but now since the issue is clear, I'll mark it as a firefox bug.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
