### ISSUE TITLE
[BUG] Not able to set Dark mode in playwright

### ISSUE THREAD

**Issue by ajayEngProd** [microsoft/playwright#14973]
OS: windows
playwright version : 1.13.0
Dot net version : 5 and 6
Browser : chrome

I am trying to set dark mode to the browser using the following
 
var browserContextOptions = new BrowserNewContextOptions();
browserContextOptions.ColorScheme = ColorScheme.Dark;

but the browserContextOptions.ColorScheme is always null even after this is set.
requesting you to let me know if i am missing out on anything.

**Comment by pavelfeldman** [comment]
It is unclear what your code snippet does, what is happening versus what is expected.

**Comment by ajayEngProd** [comment]
code initializing browser is here

 public async Task InitializeAsync()
        {
            var browserContextOptions = new BrowserNewContextOptions();
            var mockUserAgent = this.SessionOptions.HttpOptions.UserAgent;
            var overridedUserAgent = this.SessionOptions.UserAgentOverride;
            if (mockUserAgent == null && overridedUserAgent != BrowserType.NotDefined)
            {
                mockUserAgent = overridedUserAgent.GetUserAgent(false);
            }
            Log.LogComment($"EnableHighContrast is {this.SessionOptions.EnableHighContrast}");
            if(this.SessionOptions.EnableHighContrast)
            {
                browserContextOptions.ColorScheme = ColorScheme.Dark;
            }
            **Log.LogComment($"Set ColorScheme to  {browserContextOptions.ColorScheme}");**
            var headless = this.SessionOptions.Browser.IsAnaheim() ||
                this.SessionOptions.Browser.IsFirefox() ||
                this.SessionOptions.Browser.IsSafari() ||
                ConfigManager.LaunchChromeInHeadlessMode ||
                (!string.IsNullOrWhiteSpace(mockUserAgent) && !this.SessionOptions.LaunchChromeInHeadlessModeExemption);
            var ismobile = !string.IsNullOrWhiteSpace(mockUserAgent);
            if (ismobile)
            {
                browserContextOptions.UserAgent = mockUserAgent;
                Log.LogComment($"Set Playwright Browser UserAgent to {mockUserAgent}");
            }
            else if (!(this.SessionOptions.Browser.IsAnaheim() || this.SessionOptions.Browser.IsFirefox() || this.SessionOptions.Browser.IsSafari()))
            {
                var chromeUserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Safari/537.36";
                browserContextOptions.UserAgent = chromeUserAgent;
                Log.LogComment($"Overwrite Playwright Chrome UserAgent to {chromeUserAgent}");
            }

            if (this.SessionOptions.EnableHiDpiLaptopEmulation)
            {
                browserContextOptions.DeviceScaleFactor = 2;
            }

            ITestTelemetry testTelemetry = new TestTelemetry(TestTelemetryEvent.BrowserSessionCreation);
            testTelemetry.StartTelemetry();
            var pageLoadTimeoutInMilliseconds = ConfigManager.PageLoadTimeoutInMilliseconds + ConfigManager.BufferTimeForGracefulSessionExitInMilliseconds;
            var pair = await PlaywrightBrowserFactory.GetPlaywrightAndBrowser(this.SessionOptions.AutopilotDeploymentToken, mockUserAgent, this.SessionOptions.Browser, this.SessionOptions.TestContext, headless, ConfigManager.LaunchChromeInIncognitoMode, pageLoadTimeoutInMilliseconds);
            this.Playwright = pair.Item1;
            this.PlaywrightBrowser = pair.Item2;
            this.PlaywrightBrowserContext = await this.PlaywrightBrowser.NewContextAsync(browserContextOptions);
            if (ConfigManager.ClearCookies)
            {
                await this.PlaywrightBrowserContext.ClearCookiesAsync();
                this.TestUrl += "&refresh=1";
            }
            if (this.RouteHandlerDict != null)
            {
                foreach (var item in this.RouteHandlerDict)
                {
                    var url = item.Key;
                    var routeHandler = item.Value;
                    await this.PlaywrightBrowserContext.RouteAsync(url, routeHandler);
                }
            }
            this.PlaywrightPage = await this.PlaywrightBrowserContext.NewPageAsync();
            this.PlaywrightPage.Console += PlaywrightPageConsoleLog;
            testTelemetry.EndTelemetry();

            if (this.SessionOptions.BrowserSize.HasValue)
            {
                try
                {
                    var w = this.SessionOptions.BrowserSize.Value.Width > 0
                        ? this.SessionOptions.BrowserSize.Value.Width
                        : DefaultWindowWidth;
                    var h = this.SessionOptions.BrowserSize.Value.Height > 0
                        ? this.SessionOptions.BrowserSize.Value.Height
                        : DefaultWindowHeight;
                    await this.SetBrowserWindowSizeAsync(w, h);
                }
                catch (Exception exc)
                {
                    Log.LogException(exc, "Failed to resize browser, type: {0}, msg: {1}", exc.GetType().ToString(), exc.Message);
                }
            }
            else
            {
                await this.MaximizeBrowserWindowAsync();
            }

            try
            {
                await this.NavigateToAsync(new Uri(this.TestUrl));
            }
            catch
            {
                await this.CleanupPlaywrightAsync();
                throw;
            }
        }


actual image is 
![image](https://user-images.githubusercontent.com/105768577/174534464-d98dbcce-bc3f-4afb-a928-87ea0ff361d7.png)

expected image is 
![image](https://user-images.githubusercontent.com/105768577/174534551-69f57491-ddb1-4f9b-b916-560848121dfc.png)

**Comment by mxschmitt** [comment]
Closing as per above
