### ISSUE TITLE
[Question] Playwright and PowerBI login

### ISSUE THREAD

**Issue by wbovela** [microsoft/playwright#14977]
Hi,

I have recently started out with Playwright testing PowerBI visuals. I have written some basic tests and a login script and they seemed to work fine. Until I moved my computer from my home to the office network. Now, PowerBI's login dialog is different: it asks if I want to stay logged in and offers a tickbox to prevent the question in the future. I changed my login script accordingly, but even after a successful login, when the actual Playwright test opens a report PowerBI asks for a login AGAIN. 

How am I supposed to handle all these altering and spurious login dialogs?
Is there a way to do a single signon for PowerBI?

Some details about the scripts:

This is my globalsetup.ts:

```ts
import { chromium, firefox, FullConfig } from '@playwright/test';
import login from './login';

const username = process.env.PBI_USERNAME ?? '';
const password = process.env.PBI_PASSWORD ?? '';

async function globalSetup(config: FullConfig): Promise<void> {  
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();
  await login(page, username, password);
  await page.context().storageState({
    path: 'storage-state/storageState.json',
  });
  await browser.close();
}

export default globalSetup;
```

This is login.ts. Note that it now has two login method scripts which is undesirable because I don't know how to detect one or the other login dialog.

```ts
import { Page } from '@playwright/test';

async function login(
  page: Page,
  username: string,
  password: string,
): Promise<void> {

  // LOGIN METHOD 1
  await page.goto('https://app.powerbi.com');  
  await page.locator('id=i0116').fill(username); 
  await Promise.all([
    page.waitForNavigation(),
    page.locator('text=Next').click()
  ]);  
  await page.locator('id=i0118').fill(password);
  await Promise.all([    
    page.locator('input[type=submit] >> "Sign in"').click(),
  ]);

  // LOGIN METHOD 2
  // await page.goto('https://app.powerbi.com');  
  // await page.locator('id=email').fill(username);
  // await page.locator('button[id=submitBtn] >> "Submit"').click();  
  // await page.locator('id=i0118').fill(password);
  // await Promise.all([    
  //   page.locator('input[type=submit] >> "Sign in"').click(),
  // ]);

}

export default login;
```

**Comment by mxschmitt** [comment]
> Is there a way to do a single signon for PowerBI?

Playwright has nothing specific for any of the login providers.

---

If your test does not work we recommend following the debugging section: https://playwright.dev/docs/debug

If you have concrete questions, let us know, otherwise we can't act on open ended questions.
