### ISSUE TITLE
[Feature] Consider adding console.log output to Trace Report

### ISSUE THREAD

**Issue by aytik** [microsoft/playwright#14985]
**Description**

Sometimes there is a need to see `console.log()` output when analyzing Actions in Trace Report, especially in tests with complicated conditions. 
It could help to understand after which action a particular logging message appeared instead of switching to the stdout section of the Playwright Report.

**Steps To Reproduce**

- As an example, place a logging message somewhere in the body of a test
- Enable trace in `playwright.config.ts`
- Execute the test
- Check the generated Trace report.

**Actual result**

`console.log()` output does not exist in Trace Report.

**Expected result**

`console.log()` output exist in Trace Report (proposed: in Actions section (or somewhere else)).

**Additional information**

It might be helpful when analyzing tests with complicated conditions.

**Comment by dimkin-eu** [comment]
its there ;)
![Screenshot 2022-06-20 at 17 36 29](https://user-images.githubusercontent.com/7899764/174625610-94c61e7a-334c-44f0-9ea7-7b049db7ad62.png)

**Comment by mxschmitt** [comment]
We already show it inside the trace. For each step you can see the console logs on the ride side under "Console": 

<img width="341" alt="image" src="https://user-images.githubusercontent.com/17984549/174769181-eb637c21-ea75-423a-8289-87d423376e8c.png">
