### ISSUE TITLE
Remove an image before a screenshot

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#14980]
Hello, i wanted to remove an image(or set it as not visible), before a screenshot, i did this script, but isnt working:

await page.locator('body > div.wrapper > img').evaluate(element => element.style.display = 'block;');

It doesnt give an error, it just dont do anything

**Comment by ville-nvt** [comment]
display: block, propably doesn't do what you think it does. 

_block | Displays an element as a block element (like <p>). It starts on a new line, and takes up the whole width_
https://www.w3schools.com/cssref/pr_class_display.asp

display: none would be better choice

If you are writing screenshot tests you could use mask option found in toHaveScreenshot assertion to avoid unwanted elements from affecting test results.
_mask?: <Array<Locator>> Specify locators that should be masked when the screenshot is taken. Masked elements will be overlayed with a pink box #FF00FF that completely covers its bounding box._
https://playwright.dev/docs/test-assertions#page-assertions-to-have-screenshot-1

**Comment by mxschmitt** [comment]
see the answer above and the `mask` option would be the right choice for that.

**Comment by NicoloLattanzio** [comment]
it says "tohavescreenshot" doesnt exist

**Comment by NicoloLattanzio** [comment]
Yes i'm using it, and even the mask options isnt usable

**Comment by NicoloLattanzio** [comment]
Ok, so i updated playwright, that was the problem, now i have the .tohavescreenshot, but still cant use the mask option

**Comment by NicoloLattanzio** [comment]
await expect(page).toHaveScreenshot({mask:" body > div.wrapper > img"});

Shouldnt it be something like this?

**Comment by mxschmitt** [comment]
`await expect(page).toHaveScreenshot({mask: page.locator("div.wrapper > img")});`

**Comment by mxschmitt** [comment]
I had a typo in my snippet, mask is actually an array of Locators.

Please try again, I updated the snippet, that might explain the error. If not, please share with us how you invoke toHaveScreenshot.

**Comment by NicoloLattanzio** [comment]
The only way to fix this is to update playwright, i discovered that i had the 1.19, instead it's needed the 1.22 to use toHaveScreenshot, thanks
