### ISSUE TITLE
[Question] Recently I have multiple trace files in allure report

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#14984]
`"@playwright/test": "^1.22.0"`
`"allure-playwright": "^2.0.0-beta.17"`

Recently for each test failure I'm getting 3 trace files in allure results. 
Two of them are very small size and doesn't contain anything while the third one contains the real trace date. 

Can you share what is the reason?

![Screen Shot 2022-06-20 at 11 21 39](https://user-images.githubusercontent.com/14985481/174615268-9ad6afd3-78d3-4d47-af30-b153cedb3c86.png)

Note: I'm using global-setup and custom Reporter.

**Comment by dimkin-eu** [comment]
could it be related ?
https://github.com/microsoft/playwright/issues/14532
