### ISSUE TITLE
[BUG] Combined reporters don't work (JUnit and html)

### ISSUE THREAD

**Issue by emiride** [microsoft/playwright#14999]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: v17.4.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```typescript
const config: PlaywrightTestConfig = {
reporter: [
    ['html'],
    ['junit', {outputFile: 'results.xml'}],
  ],
};
export default config;


```

Combination of these two reporters seem to not work. Am I doing something wrong, or is this really a case? Is there some other piece of configuration that could impact this?

I am not sure if it is relevant, but I am running my tests where I specifically indicate it to use this config.
```npx playwright test --config=playwright.config.ts --project=staging```

**Comment by emiride** [comment]
For anyone looking, the workaround is pretty simple. Just put ```junit``` first.

```typescript
const config: PlaywrightTestConfig = {
reporter: [
    ['junit', {outputFile: 'results.xml'}],
    ['html']
  ],
};
export default config;

**Comment by mxschmitt** [comment]
What do you mean that it does not work? Does an error get thrown or what happens?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by emiride** [comment]
I am sorry I didn't see when you answered it. I didn't check logs, but it just doesn't produce a file if you put 'junit' on second place.

**Comment by mxschmitt** [comment]
I tried to reproduce it, but it works for me. Config:

` reporter: [['html'], ['junit']],`

**Comment by emiride** [comment]
It is probably something with the rest of my configuration then. It might be that someone else encounter this issue in the future and have it reproducible for them. In the meantime I solved my issue by replacing its order. Thanks anyways for quick turnaround and attempt to reproduce.
