### ISSUE TITLE
How to input on dynamic on-screen keyboard with playwright

### ISSUE THREAD

**Issue by Smalltarget108** [microsoft/playwright#15002]
https://stackoverflow.com/questions/50618011/login-virtual-keyboard-bank

I meet almost the same problem as above,
 have tried to use "  # Click text=? page.click("text=?")", it doesn't work as expected.
Is there any solution on playwright for dynamic on-screen keyboard input.

Thank you

**Comment by mxschmitt** [comment]
Can you share with us a short piece of the DOM you wanna test / locate an element of?

It's unfortunately not very clear for us what you are trying to achieve. 

See here for our selector engines: https://playwright.dev/docs/selectors#quick-guide

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
