### ISSUE TITLE
[BUG] ReferenceError: document is not defined

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15006]
Hello, trying to use the command document.getElementById(), i get this error "ReferenceError: document is not defined", but the document.Something is still usable, dont know how to fix it

**Comment by NicoloLattanzio** [comment]
I'm trying to get a label(only read) text

**Comment by NicoloLattanzio** [comment]
new error : apiRequestContext.put: headers[1].value: expected string, got undefined

**Comment by mxschmitt** [comment]
Seems like you want this: `const key = await page.locator('#apiKey').innerText()`.

**Comment by NicoloLattanzio** [comment]
Ok i did this, const key = await page.locator('#apiKey_obscured').innerHTML();, it doesnt give any error, but still doesnt work, like he doesnt find anything or idk maybe he add some spaces when getting the element?

**Comment by mxschmitt** [comment]
Maybe the api key is not on the innerHTML / the element, could you share your DOM or a link to your site?

**Comment by NicoloLattanzio** [comment]
Fixed using the command inputValue().

**Comment by alisatas7** [comment]
Hello, I am trying to get all HTML headers from h1 to h6, but I got this `ReferenceError: document is not defined playwright typescript` error. Do you know why?

This is my code. 
```
    // eslint-disable-next-line @typescript-eslint/require-await
    await test.step('Test html header structure for catalog page', async () => {
      // Get all the heading tags (h1, h2, h3, h4, h5, h6) in the document
      const headingTags = document.querySelectorAll('h1, h2, h3, h4, h5, h6')

      // Define a function to test the hierarchy
      function testHeadingHierarchy() {
        const hierarchy = []

        headingTags.forEach(heading => {
          const tagName = heading.tagName.toLowerCase() // Get the tag name (e.g., "h1", "h2")
          const level = parseInt(tagName.charAt(1), 10) // Extract the numeric level from the tag name

          // Check if the hierarchy is valid
          if (level > hierarchy.length + 1) {
            console.error(`Invalid hierarchy: ${tagName} is not in the correct order.`)
          }

          // Update the hierarchy array with the current level
          hierarchy[level - 1] = tagName
        })

        console.log('Heading hierarchy is valid:', hierarchy.join(' > '))
      }

      // Call the function to test the hierarchy
      testHeadingHierarchy()
    })
```
