### ISSUE TITLE
[Question] Unable to do case-insensitive text matching assertions

### ISSUE THREAD

**Issue by ElliottDevlinPA** [microsoft/playwright#15009]
Hi,

I'm trying to implement some case-insensitive text matching assertions into my project, but am experiencing some issues with it.

If I'm understanding them correctly, your docs state that I can pass the ignoreCase option into the text assertion. However, when I try to do that, I get an error saying that the argument type is not assignable to the 'toContainText()' function.

This is my code:

![image](https://user-images.githubusercontent.com/38210127/174789338-d6dfad89-a80e-4ce6-bcc5-c087dc672ac9.png)

I'm using the latest version of Playwright Test. Please could you offer any advice on what I'm doing wrong here?

Many thanks,
Elliott.

**Comment by mxschmitt** [comment]
ignoreCase gets released with 1.24, its not released yet.

**Comment by ElliottDevlinPA** [comment]
@mxschmitt  - is there another way to do case-insensitive assertions until 1.24 is released?

**Comment by mxschmitt** [comment]
There is not, but you can use the dev version: `npm i @playwright/test@next`.

**Comment by ltsuda** [comment]
As `.toContainText()` accepts a RegExp, isn't possible to do something line `/pattern/i` ?
https://playwright.dev/docs/test-assertions#locator-assertions-to-contain-text

**Comment by ElliottDevlinPA** [comment]
@ltsuda apologies for the delay in responding - your suggestion does indeed solve my issue. Thank you.
