### ISSUE TITLE
[Feature] Don't use test timeout for teardown

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#15019]
After creating issue https://github.com/microsoft/playwright/issues/14686 and talking to a PW dev, it turned out that the reason was that the defined test timeout also needs to cover the time the teardown takes.  
Because of that, a passed test can still get marked as failed if there wasn't enough time left for the teardown.

However, that is not very intuitive, you would expect the timeout to only apply to the tests (even more so when the teardown happens automatically).
In fact, other PW users have run into the same issue and didn't understand the underlying reason either:

- https://playwright.slack.com/archives/C01AG7QGW2F/p1652700815678729
- https://playwright.slack.com/archives/CSUHZPVLM/p1655761928528629?thread_ts=1654612590.135749&cid=CSUHZPVLM
- https://playwright.slack.com/archives/CSUHZPVLM/p1655793597947849?thread_ts=1654612590.135749&cid=CSUHZPVLM
- https://playwright.slack.com/archives/CSUHZPVLM/p1652800328352589?thread_ts=1652788993.187159&cid=CSUHZPVLM
- https://playwright.slack.com/archives/CSUHZPVLM/p1655478473225959

### Feature request:
To make Playwright more intuitive and avoid fails of tests that actually passed, it would make a lot of sense to move the setup and teardown out of the test timeout.

If need be, setup and teardown could have their own timeout durations instead (maybe also configurable via the config?).

**Comment by RichardGuion** [comment]
I had this exact same scenario. My test actually succeeded, but it just missed the timeout threshold during the teardown. It was very confusing at first.

**Comment by azad-derakhshani-GS** [comment]
Wait, would this already solve the issue? Or is the teardown separate from the fixture timeout?
https://playwright.dev/docs/test-timeouts#fixture-timeout

Just stumbled upon that by accident.
But of course it might still make sense to have them separate by default, if you guys agree.

**Comment by dgozman** [comment]
We think that separate timeout for teardown will increate the complexity without actually solving the issue. Changing teardown timeout is equivalent to changing the test timeout, since teardown is always run immediately after the test, so they both apply one after another.

Instead, we are going to change the error message to make it easier to understand that test timed out. The solution is usually either figuring out which part of the test is waiting forever (probably flaky?), or increasing the timeout because it just needs more time.

**Comment by azad-derakhshani-GS** [comment]
Yeah I get that, and I actually agree that shortening the error message as suggested in #15117 would probably lead to less confusion.

I was thinking why not have both:
Having the teardown included in the test timeout by default.
But also having a config option where people can define a separate teardown timeout if needed.
So unless that option is set, it would still work the same way as now.
That would give people more granular control, which I'm always a fan of. :)

But otherwise your solution should work well enough too.

**Comment by dgozman** [comment]
@azad-derakhshani-GS Any new option always come with more complexity, both for the project and for the users that have to understand available options. We can leave this issue open to see whether there's enough interest in such an option.
