### ISSUE TITLE
[Question] How to suppress multiple msedge command windows when enabling logging

### ISSUE THREAD

**Issue by fara20222** [microsoft/playwright#15018]
We need to enable logging when running Playwright script as below. However multiple msedge command windows pop up when running scripts. These windows interferes with debugging, and also cause issues for screenshot testing. They don't pop up when we enable logging using selenium. Is there a way to compress these windows?

-----config to turn on logging--------

```ts
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    browserName: 'chromium',
    acceptDownloads: true,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    channel: 'msedge-canary',
    launchOptions: {
      slowMo: 100,
      args: ['--enable-features=NetworkService,NetworkServiceInProcess,msEdgeDesignerUI,msDisableHubPopupLightDismiss',
      '--enable-logging', '--v=0 --vmodule=*/components/edge_designer/*=1'],
    },
  },
};
```
---sample script-------

```
import { test, BrowserContext, Page } from '@playwright/test';

test.describe.configure({ mode: 'serial' });

let context: BrowserContext;
let page: Page;

test.beforeAll(async ({ playwright, browserName }) => {
  context = await playwright[browserName].launchPersistentContext('C:\\temp-edge\\edge-dev-profile');
  page = context.pages()[0];
  await page.pause();
});

test.afterAll(async () => {
  await context.close();
});

test('runs first', async () => {
  await page.goto('https://playwright.dev/');
});

test('runs second', async () => {
  await page.click('text=Get Started');
});
```
----------screenshot of multiple msedge command windows----------------

<img width="1583" alt="Screen Shot 2022-06-21 at 11 34 08 AM" src="https://user-images.githubusercontent.com/107517959/174874089-21b6eadc-5157-4ff7-9ff6-62eff694876d.png">

**Comment by mxschmitt** [comment]
I was able to reproduce this with pure Chromium and `--enable-logging` CLI flag is causing it. 

I recommend filing an issue on https://crbug.com, since this is not something Playwright can control. Puppeteer would encounter the same.

**Comment by fara20222** [comment]
I see. Thanks Max for investigating this issue.


Regards,
Fara


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
