### ISSUE TITLE
[Feature] Add chrome-beta to focal docker containers

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#15013]
We're looking for ways to keep in front of chrome regressions like https://github.com/microsoft/playwright/issues/14037 and would like to test `chrome-beta` as part of our larger, more comprehensive regression suite.

We could manually run `npx playwright install chrome-beta` as a part of our build step, but that would add 20-30s per run (which is run in parallel, so that would be 2 build minutes per commit). Instead, it would be great if the available browsers were automatically installed in the docker container.

**Comment by mxschmitt** [comment]
> @mxschmitt that makes sense thank you.
> 
> > Also if you use the normal chromium channel, you'll end up with with Chromium Beta channel, thats mostly the same except branded vs. chromium channel.
> 
> Are you saying that if we specify chromium, we'll implicitly use chrome-beta?

Yes, as of today it's the same underlying chromium release channel. Audio and video codecs might differ tho since it's branded vs unbranded.

**Comment by unlikelyzero** [comment]
@mxschmitt is there a list of all of the browsers that are natively installed in the docker container? I poked around a bit and couldn't find one

**Comment by mxschmitt** [comment]
Only the default browsers are installed there, chromium, firefox, webkit.
