### ISSUE TITLE
Selector not found error, if a run the test with pause and --headed it pass 

### ISSUE THREAD

**Issue by camargodan** [microsoft/playwright#15022]
Hi,  I'm running a test without --headed and a 'waiting for selector' error rise, it's like the element it's not founded, if a run the same test with the pause function (await page.pause();) and go step by step with --headed the test pass normally. my question is why is this happening? 

This is the block of test that I'm running
    await page.locator('button:has-text("add")').nth(1).click();
    await page.locator('div[role="tab"]:has-text("Claims")').press('Tab');
    await page.locator('mat-select[role="listbox"]:has-text("Process")').press('ArrowDown');
    await page.locator('[placeholder="ID"]').fill('111222333');
    await page.locator('[placeholder="ID"]').press('Tab');
    await page.waitForTimeout(1500);
    await page.locator('[aria-label="Analist"]').press('ArrowDown');
    await page.locator('[aria-label="Analist"]').press('Tab');
    await page.locator('textarea').fill('This is a test');
    await page.locator('button:has-text("Save")').click();

And this is the error

Timeout of 100000ms exceeded.
locator.press: Target closed
=========================== logs ===========================
waiting for selector "[aria-label="Analist"]"
============================================================

**Comment by mxschmitt** [comment]
I'd recommend following the debugging tools section to understand why its failing: https://playwright.dev/docs/debug

So setting the `DEBUG=pw:api` env or if this does not yield to helpful output, then record and view a trace.
