### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ksodipo** [microsoft/playwright#15020]
CONTEXT:
- Playwright Version: [1.22.0]
- Operating System: Amazon Linux 2 (aws lambda)
- Python 3.9
- Stable headless Chromium (https://github.com/adieuadieu/serverless-chrome/releases/tag/v1.0.0-57)
- Extra: This is being run in a lambda function

TRACEBACK:

`Traceback (most recent call last):
  File "/var/task/goto_website.py", line 62, in crawl
    await go_to_task 
  File "/var/task/playwright/async_api/_generated.py", line 7601, in goto
    await self._async(
  File "/var/task/playwright/_impl/_page.py", line 493, in goto
    return await self._main_frame.goto(**locals_to_params(locals()))
  File "/var/task/playwright/_impl/_frame.py", line 122, in goto
    await self._channel.send("goto", locals_to_params(locals()))
  File "/var/task/playwright/_impl/_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "/var/task/playwright/_impl/_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Navigation failed because page was closed!
=========================== logs ===========================
navigating to "https://www.youtube.com/", waiting until "load"
============================================================`

My CODE:
![image](https://user-images.githubusercontent.com/20947006/174798267-d6ecc014-0a36-447f-af5c-2b26aa9bf241.png)

ISSUE:

Error is thrown at the point when I await page.goto(url). Navigation failed because page was closed is the error.

Things attempted to no avail: using headless or not, putting a wait time before the browser definition, reopening the page, trying a few different chromium --flags, trying different urls (http/https)

SIMILAR BUGS:
https://github.com/microsoft/playwright/issues/13640 (very similar)
https://github.com/microsoft/playwright/issues/2061#issuecomment-623100345 (less similar)

**Comment by mxschmitt** [comment]
You can set the `DEBUG=pw:browser` env var, to see the browser's stdout/stderr, which might yield to more output.

Probably you'll have to disable the GPU by passing `--disable-gpu`.

Keep in mind that Amazon Linux is not supported. Only Ubuntu 18/20/22 (next release) so far., so you'll only receive limited support here.

**Comment by ksodipo** [comment]
Thanks. I set the debug flag and figured it was an issue with the Linux libraries and Chromium. Not playwright. Closing the issue
