### ISSUE TITLE
[BUG] page.SetInputFiles doesnt work

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15037]
Hello, i'm trying to put as an input an excel file, but the comand setinputfiles cant find it.

await page.locator('input[name="parts_file"]').setInputFiles('/files/import.xlsx');

This is the code, i've tried to put only the file name, or the full path.

But as i'm using a wsl, i dont know if the problem is related to it.

**Comment by mxschmitt** [comment]
`/files/import.xlsx` would try to upload it from the files root directory. I guess thats not what you want.

What you actually want is something like this I guess:

```js
const path = require('path');
await page.locator('input[name="parts_file"]').setInputFiles(path.join(__dirname, 'files', 'import.xlsx'));
```

This would be relative to your source file directory, upload a file in the files directory import.xlsx.

**Comment by NicoloLattanzio** [comment]
That still give an error, but when the test start searching for the path, it goes here(check the image)
![Immagine 2022-06-22 141912](https://user-images.githubusercontent.com/80640027/175027366-d844001a-dce8-4b7e-85dd-dd454479b1cf.png)

**Comment by NicoloLattanzio** [comment]
Maybe i have to put the file in a specific folder? So he can see it
