### ISSUE TITLE
[Feature] TypeScript stack trace via source maps?

### ISSUE THREAD

**Issue by mgenware** [microsoft/playwright#15042]
I followed [Manually compile tests with TypeScript](https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript) from official docs. Problem is, stack traces from console are pointing to artificial JS files with this approach.

Mocha supports TS stack traces via [node-source-map-support](https://github.com/evanw/node-source-map-support):

```sh
mocha --require source-map-support/register tests/
```

It would be great if playwright also supports this.

**Comment by mxschmitt** [comment]
If your source-files have source maps attached/referenced, then they should get picked up.

I was testing it and it was working fine for me:

<img width="727" alt="image" src="https://user-images.githubusercontent.com/17984549/175080816-a6832705-baab-427f-adb6-9d8b5bad2e49.png">

**Comment by mgenware** [comment]
Yes, I have `sourceMap` enabled and I can see `.js.map` files in dist folder. Not sure if it's because the `tsconfig.json` I'm using has some plugins to transform code. Let me try extracting my code into a reproducible demo on github 😄

**Comment by mxschmitt** [comment]
Please file a new issue if you still encounter issues. Closing for now.
