### ISSUE TITLE
[Feature] How can I uninstall playwright?

### ISSUE THREAD

**Issue by obtusebanana** [microsoft/playwright#15049]
I can't find uninstall script for playwright.

Does it even exist?

**Comment by mxschmitt** [comment]
The uninstallation process is based on two steps:

a) you need to uninstall Playwright the dependency, e.g. NPM/Python/Java/.NET whatever.
b) you need to remove the browsers which Playwright has downloaded. See here for the paths: https://playwright.dev/docs/ci#caching-browsers

**Comment by Gentl3man** [comment]
Like, do you even want to help us?

**Comment by slch** [comment]
c) manually find and remove any varied dependencies installed at different playwright versions via `npx playwright --install-deps`
Unless any of them are required by other apps.

**Comment by vincerubinetti** [comment]
Now you can do it with:

`npx playwright uninstall --all`

I wanted this so I could test to make sure that my project's unified install script would properly install everything Playwright needed for users who had never had it on their system before.

**Comment by LaserBread** [comment]
> Sorry, to confirm, this also removes the deps installed from `npx playwright install deps`?

It appears so.
