### ISSUE TITLE
[Feature] Optional param to "retry" page.fill

### ISSUE THREAD

**Issue by davidjonesdialexa** [microsoft/playwright#15048]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
Page.fill will occasionally fail to fill input fields. An optional param `retry` would execute .fill until the input field's.value is equal to the passed value arg

**Comment by mxschmitt** [comment]
Page.fill should not fail, could you provide an example why it fails?

**Comment by davidjonesdialexa** [comment]
I can't actually see why it fails, but there's discussion on the topic in this [slack thread](https://playwright.slack.com/archives/CSUHZPVLM/p1655985022279659)

**Comment by mxschmitt** [comment]
Most likely there is something wrong with the state handling of your website then! Without a repro we unfortunately can't act on it.

**Comment by davidjonesdialexa** [comment]
I am definitely not discounting that as a possibility 😂

**Comment by mxschmitt** [comment]
Closing by that for now since this is not a Playwright bug!
