### ISSUE TITLE
[Question] Unable to download firefox

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#15055]
Local on my mac machine, it works fine but unable to download in Jenkins(Ubuntu). Can someone please help?

```
npm ERR! code 1
17:02:42  npm ERR! path /jenkins/workspace/tomation_gg_networkGraphAndSlack/node_modules/playwright-firefox
17:02:42  npm ERR! command failed
17:02:42  npm ERR! command sh -c node install.js
17:02:42  npm ERR! BEWARE: your OS is not officially supported by Playwright; downloading Ubuntu build as a fallback.
17:02:42  npm ERR! Downloading Firefox 99.0.1 (playwright build v1323)...
17:02:42  npm ERR! /jenkins/workspace/tomation_gg_networkGraphAndSlack/node_modules/playwright-core/lib/server/registry/index.js:652
17:02:42  npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
17:02:42  npm ERR!             ^
17:02:42  npm ERR! Error: Failed to download Firefox 99.0.1 (playwright build v1323), caused by
17:02:42  npm ERR! Error: Download failed: server returned code 403.
17:02:42  npm ERR!     at fulfill.error.error 
```

**Comment by zac11** [comment]
What Ubuntu version are you on, because it explicitly mentions that your OS is not supported.

**Comment by gauravgandhi1315** [comment]
@zac11 Chrome is working fine

**Comment by mxschmitt** [comment]
Which linux distribution are you using?

You can set the `DEBUG=pw:install` env var to find out the exact download URL and try to download it manually, curious to understand why 403 gets returned.

Also are you maybe under some copr/proxy/firewall environment?

**Comment by gauravgandhi1315** [comment]
@mxschmitt Yes, we do have proxy and don't have much control over the ubuntu machine. So I was able to download firefox now(I see it in the logs) but when I tried to launch it, its not able to find the `executable path`. Is there any way I can print downloaded path?

**Comment by gauravgandhi1315** [comment]
@dgozman

**Comment by dgozman** [comment]
@gauravgandhi1315 Try launching without passing the executable path, so that Playwright picks the right path for you: `browser = await firefox.launch({})`

**Comment by dgozman** [comment]
@gauravgandhi1315 Sorry, that's the only suggestion I had. Without any repro, clear steps that you run and their output, there is nothing else I can suggest.

**Comment by mxschmitt** [comment]
To summarise:

- you can't use a normal firefox with Playwright, it needs to be the Firefox, Playwright downloads via npx playwright install
- It returns 403 http status code, so something with your proxy is wrong, you can set another proxy by setting the `HTTPS_PROXY` env var

Also which OS are you using? Since it complains with that the linux distribution is not supported.

**Comment by mxschmitt** [comment]
did you put firefox manually there now? You need to use npx playwright install, otherwise it won't work. I'd recommend if so to remove the folder again and execute the install command.

**Comment by rwoll** [comment]
Closing as part of triage, but https://github.com/microsoft/playwright/issues/13230#issuecomment-1090555843) shares an example that works with some installation of Jenkins that might be helpful. (There are also other comments in that thread that have some pointers for debugging Jenkins.)

Unfortunately, Jenkins environments can be complex and vary from deployment to deployment, so without a repro and detailed commands and output you've run, we're unable to provide more specific tips.

Thanks!
