### ISSUE TITLE
[Question] Does the nth-match selector only works on text selectors

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#15059]
Hi, 

I was going through the documentation , when I found this interesting selector provided using the `nth-match`, which is used for matching from a list of elements available.

Link -> https://playwright.dev/docs/selectors#pick-n-th-match-from-the-query-result

However, the documentation doesn't clearly specify if this would work for only text matches or can I use any `css` based selectors for doing the same. 

For e.g. - 
`await page.locator(':nth-match(:text("Buy"), 3)').click();`  // works perfectly fine

but this returns error

`await page.locator(':nth-match(:class("someclass"), 3)').click();`
or
`await page.locator(':nth-match(:class(".classname"), 3)').click();`

Since I've seen that in many react/angular based drop down or combo boxes implementations, that there will be same classes used for the entire drop down or combo box implementation and it would be great if we're able to use this to select element from a specific index.

If this works for `css` or other engine locators, then can we please explicitly mention ( and may be add examples).

**Comment by ltsuda** [comment]
Let see If I understood correctly, do you think this is the same and could work for your use case?

`await page.locator(".className").nth(3).click()`

https://playwright.dev/docs/api/class-locator#locator-nth
https://playwright.dev/docs/api/class-locator#locator-first
https://playwright.dev/docs/api/class-locator#locator-last
Released since 1.14 
https://playwright.dev/docs/release-notes#-new-nth-and-visible-selector-engines
In case of workings with a list of locators
https://playwright.dev/docs/locators#lists

**Comment by zac11** [comment]
@ltsuda This is how I am currently working with - using the `locator.nth`. However, I'm interested if the `nth-match` use case. 
That is why I have asked this as a question (not as bug or feature) to see if the `nth-match` use case can be used in this scenario.

**Comment by ville-nvt** [comment]
We have actually used :nth-match with attribute selectors. Looking through documentation I could not find any mention about :class pseudo selector. 

I would try like this:
`await page.click(':nth-match(.classname)', 3)`

**Comment by zac11** [comment]
@ville-nvt Already tried this but got an error - `invalid selector`.

**Comment by mxschmitt** [comment]
`nth-match` is a CSS pseudo class Playwright has added. If you want to combine it with other selector engines, you can use `nth=42` selector engine, see here: https://playwright.dev/docs/selectors#n-th-element-selector

Does this answer your question?

**Comment by zac11** [comment]
@mxschmitt Are you suggesting something like this -> 
`await page.locator(':nth-match(:class(".classname"),nth=3)').click()`

**Comment by mxschmitt** [comment]
`await page.locator('.classname >> nth=3').click()`

**Comment by ville-nvt** [comment]
> @ville-nvt Already tried this but got an error - `invalid selector`.

Sorry there was an error on the example.
`await page.click(':nth-match(.classname, 3)')`

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/issues/15059#issuecomment-1163989286

Please file a new issue if you still have questions.
