### ISSUE TITLE
[Feature] text selector case insensitive

### ISSUE THREAD

**Issue by jacobmesu** [microsoft/playwright#15051]
I would like to request a selector for an case insensitive match on the whole text. Partial match is not an option because of mismatches in the past (f.e. 'type' also matches 'article type' and regex is not an option because of incidental `&nbsp;` in elements text. I'd be grateful if you'd consider this. Thanks.

**Comment by mxschmitt** [comment]
With version 1.23 we'll add an `ignoreCase` option, does this fit for your needs?

See here how it will look like: https://github.com/microsoft/playwright/pull/14534/files#diff-e439b950e5f1e6dfc1f475165d8bdc324a8d86a7e288371ac1fb2b9e07e550c4

**Comment by jacobmesu** [comment]
Thanks Max for your reply. Unfortunately I think that's not a solution for my case. This is a nice solution for comparing the contents of an element after it's been selected. But I want to use it as an selector. F.e. :text-is("Home", "i"). Or any help with ignoring the nbsp is a regex selector would also be very helpful.

**Comment by jacobmesu** [comment]
Given the html
```html
<html>
  <body>
    <div>new article&nbsp;type</div>
    <div>Article&nbsp;Type</div>    
  </body>
</html>
```

given the string "article type" as parameter to my function I want to match the second div and not the first. 
```javascript
div :text-matches("${text}","i") // Can't handle nbsp; 
div :text-is("${text}") // Case sensitive
div :text=${text} // Partial matching
```

**Comment by mxschmitt** [comment]
The text selector engine has an "exact mode" which is case sensitive, see the following example:

```ts
// @ts-check
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // Create pages, interact with UI elements, assert values
  const page = await browser.newPage();
  await page.setContent(`
  <html>
    <body>
      <div>new article&nbsp;type</div>
      <div>Article&nbsp;Type</div>    
    </body>
  </html>`);
  console.log(await page.locator('div >> text="Article Type"').count())
  await browser.close();
})();
```

if you remove the quotes, then its "not exact mode" anymore and count is by that 2 instead of 1.

**Comment by jacobmesu** [comment]
Thank you for your reply. It's not exactly what I want. I want to have a text-selector for a case **in**sensitive exact match. So given the following code and a new selector the following code should result in 1 and not in 0. 

```typescript
// @ts-check
const { chromium } = require("playwright");

(async () => {
   const browser = await chromium.launch();
   // Create pages, interact with UI elements, assert values
   const page = await browser.newPage();
   await page.setContent(`
  <html>
    <body>
      <div>new article&nbsp;type</div>
      <div>Article&nbsp;Type</div>    
    </body>
  </html>`);
   console.log(await page.locator('div >> text2="article type"').count());
   await browser.close();
})();
```

**Comment by mxschmitt** [comment]
Something like this should work then for your use-case: `console.log(await page.locator('div >> text=/^article\\stype$/i').count());`

**Comment by rwoll** [comment]
Closing per-above as part of triage; please re-open if the suggested code does not work for you. Thanks!

**Comment by jacobmesu** [comment]
A bit late, but thank you @mxschmitt. You suggestion solved my problem.

**Comment by Pomax** [comment]
@mxschmitt the link in [your message](https://github.com/microsoft/playwright/issues/15051#issuecomment-1164502100) no longer exists. It would be good if that could be updated to the current documentation page, as case sensitive/insensitive matching is still a problem for users today, and they _will_ find this issue and use it as guide =)
