### ISSUE TITLE
[Feature] Components: support for Solid.js

### ISSUE THREAD

**Issue by floer32** [microsoft/playwright#15057]
Since there is support for Svelte, Vue, and React, I imagine the components feature could also support [Solid.js](https://solidjs.com/) components eventually. Solid.js projects are built with Vite.

I'll try it myself soon, but wanted to open the issue first, in case it takes me a while before getting around to it.

**Comment by mxschmitt** [comment]
Since there is a vite plugin for it, it should be doable: https://github.com/solidjs/vite-plugin-solid

Marking it as a feature request.

**Comment by bjoluc** [comment]
To anyone coming across this issue looking for SolidJS component testing support: `@playwright/experimental-ct-solid` has been deprecated again in #33523, sadly. The last published version (1.48.2) still works, but it lacks any Playwright features released after Playwright 1.48.2, unfortunately.

**Comment by sand4rt** [comment]
> To anyone coming across this issue looking for SolidJS component testing support: `@playwright/experimental-ct-solid` has been deprecated again in [#33523](https://github.com/microsoft/playwright/pull/33523), sadly. The last published version (1.48.2) still works, but it lacks any Playwright features released after Playwright 1.48.2, unfortunately.

I'm going bring the library back to life soon under my own namespace—I'll post an update here when it's done

**Comment by bjoluc** [comment]
That's wonderful news – thanks @sand4rt! I'm currently overriding my Playwright version (still works fine with Playwright 1.53.0), but that's quite scary and guaranteed to break sooner or later, so I appreciate your efforts! 🙌

**Comment by sand4rt** [comment]
@bjoluc see: https://github.com/sand4rt/playwright-ct-solid
