### ISSUE TITLE
How do I handle a jstree using .Net playwright?

### ISSUE THREAD

**Issue by techpro8791** [microsoft/playwright#15063]
![vqBD5](https://user-images.githubusercontent.com/61744255/175229708-54715227-bf86-469b-afad-b500559f10f5.png)
How do i search through the nodes (hidden prior to expansion), and perform a click on a specific node? I could do this with JavascriptExecution using selenium. I need help pls.

**Comment by mxschmitt** [comment]
If you can do this by using JavaScript evaluation, you can also do this using Playwright. `Locator.EvaluateAsync` e.g.

You can use the normal click actions in combination with the selector engines: https://playwright.dev/docs/selectors

So this means you need to click on all the nodes in the tree until the one you actually want to click on is visible.

**Comment by techpro8791** [comment]
> If you can do this by using JavaScript evaluation, you can also do this using Playwright. `Locator.EvaluateAsync` e.g.
> 
> You can use the normal click actions in combination with the selector engines: https://playwright.dev/docs/selectors
> 
> So this means you need to click on all the nodes in the tree until the one you actually want to click on is visible.

Tried it but getting an illegal return statement.

**Comment by mxschmitt** [comment]
Could you share code with us?

**Comment by techpro8791** [comment]
> Could you share code with us?

await Page.EvaluateAsync("return ('#National').jstree('open_all');");
![image](https://user-images.githubusercontent.com/61744255/175241105-64164871-4f78-4996-b6a6-b548cef8984a.png)

**Comment by mxschmitt** [comment]
`await Page.Locator("#National").EvaluateAsync("element => element.jstree('open_all')");`

something like this might work, I'm not familiar with this tree library tho.

**Comment by techpro8791** [comment]
I have tried it but was to no avail. I’m a bit stuck. Please, I need help.

**Comment by mxschmitt** [comment]
We unfortunately are not familiar with the library you are using, so we can't act on it. If you tell us about their API, then we might can give more helpful suggestions.

**Comment by techpro8791** [comment]
was able to resolve it, might not be the very best approach but through the nested loop. A bit time-wasting approach although seems to solve the problem.
