### ISSUE TITLE
playwright._impl._api_types.Error: Browser closed.

### ISSUE THREAD

**Issue by twopicc** [microsoft/playwright#15062]
Fill Out the template :)

Describe the bug
I used this code a few days ago and it worked fine, but when I used it today, I got this exception. Running this code, the browser opens a blank page and does not close it, but the code throws an exception

The buggy code
```
def bom():
USER_DATE_DIR_PATH = f"C:\Users\{getuser()}\AppData\Local\Google\Chrome\User Data"
# chrome.exe 的地址
EXECUTABLE_PATH = "C:\Program Files\Google\Chrome\Application\chrome.exe"
playwright = sync_playwright().start()
browser = playwright.chromium.launch_persistent_context(
# 指定本机用户缓存地址
user_data_dir=USER_DATE_DIR_PATH,
# 指定本机google客户端exe的路径
executable_path=EXECUTABLE_PATH,
# 要想通过这个下载文件这个必然要开 默认是False
accept_downloads=True,
# 设置不是无头模式
headless=False,
bypass_csp=True,
slow_mo=10,
# 跳过检测
args=['--disable-blink-features=AutomationControlled']
)
return browser.new_page()
```

error

File "D:\python3.9\lib\site-packages\playwright_impl_connection.py", line 63, in inner_send
result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
pid=8932
[pid=8932][out] �������е�������Ự�д򿪡�
=========================== logs ===========================
C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,Mediading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptConentUpdater --allow-pre-commit-input --disable-hang-monitoHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater -ompt-on-repost --disable-renderer-backgrounding --disable-s-allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-proenable-automation --password-store=basic --use-mock-keychaitection --disable-popup-blocking --disable-prompt-on-repost --disable-reneatures=AutomationControlled --user-data-dir=C:\Users\twopiderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-rnkecording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox
--disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
pid=8932
[pid=8932][out] �������е�������Ự�д򿪡�

**Comment by mxschmitt** [comment]
Which version of Google Chrome is that? Have you tried without a persistent profile, maybe the persistent profile is corrupted.

**Comment by twopicc** [comment]
My chrome is 102.0.5005.115. but two days ago, the persistent profile is ok.

**Comment by twopicc** [comment]
`playwright.chromium.launch_persistent_context(
        # 指定本机用户缓存地址
        user_data_dir=__USER_DATE_DIR_PATH__,
        # 指定本机google客户端exe的路径
        executable_path=__EXECUTABLE_PATH__,
        # 要想通过这个下载文件这个必然要开  默认是False
        accept_downloads=True,
        # 设置不是无头模式
        headless=False,
        bypass_csp=True,
        slow_mo=10,
        # 跳过检测
        args=['--disable-blink-features=AutomationControlled']
    )`
error 
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\python3.9\lib\site-packages\playwright\sync_api\_generated.py", line 11728, in launch_persistent_context
    self._sync(
  File "D:\python3.9\lib\site-packages\playwright\_impl\_sync_base.py", line 88, in _sync
    return task.result()
  File "D:\python3.9\lib\site-packages\playwright\_impl\_browser_type.py", line 148, in launch_persistent_context
    from_channel(await self._channel.send("launchPersistentContext", params)),
  File "D:\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 39, in send
    return await self.inner_send(method, params, False)
  File "D:\python3.9\lib\site-packages\playwright\_impl\_connection.py", line 63, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
<launched> pid=4888
[pid=4888][out] �������е�������Ự�д򿪡�
=========================== logs ===========================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\twopic\AppData\Local\Google\Chrome\User Data --remote-debugging-pipe about:blank
<launched> pid=4888
[pid=4888][out] �������е�������Ự�д򿪡�
============================================================`

**Comment by twopicc** [comment]
`browser = playwright.chromium.launch(
        # 指定本机用户缓存地址
        # user_data_dir=__USER_DATE_DIR_PATH__,
        # 指定本机google客户端exe的路径
        executable_path=__EXECUTABLE_PATH__,
        # 要想通过这个下载文件这个必然要开  默认是False
        # accept_downloads=True,
        # 设置不是无头模式
        headless=False,
        # bypass_csp=True,
        slow_mo=10,
        # 跳过检测
        args=['--disable-blink-features=AutomationControlled']
    )`
I use this can open and no error, but this browser is not my chrome in win10.

**Comment by mxschmitt** [comment]
> I used this code a few days ago and it worked fine

what did you change since then?

> I use this can open and no error, but this browser is a new chrome not my chrome in win10.

Do you mean that its a new browser profile and does not have the same bookmarks etc.?

Most likely Google Chrome auto updated and it does not like the user profile directory anymore.

**Comment by rwoll** [comment]
Closing as part of triage due to inactivity. Feel free to re-open, or file a new issue referencing this. Thanks!

**Comment by twopicc** [comment]
> > I used this code a few days ago and it worked fine
> 
> what did you change since then?
> 
> > I use this can open and no error, but this browser is a new chrome not my chrome in win10.
> 
> Do you mean that its a new browser profile and does not have the same bookmarks etc.?
> 
> Most likely Google Chrome auto updated and it does not like the user profile directory anymore.

nothing changed, but this code woked fine in another computer with lastest  Google Chrome. My computer may be bad in some place. thanks for you reply.
