### ISSUE TITLE
[Question] How to position an element between  two elements   

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#15061]

**Comment by mxschmitt** [comment]
Its not clear for us what you are trying to achieve, could you provide us more input to act on this issue?

**Comment by god-pane** [comment]
![image](https://user-images.githubusercontent.com/9427959/175229084-0447e063-9500-42fc-b8d6-1d574a7da754.png)

**Comment by god-pane** [comment]
Because the page has many of these save buttons, and some of them can also be hidden depending on the function scaling

**Comment by mxschmitt** [comment]
`await page.locator('button:below(:text("Cloud Management"))').click();`

See here: https://playwright.dev/docs/selectors#selecting-elements-based-on-layout

**Comment by god-pane** [comment]
thx
