### ISSUE TITLE
How do I record video on test failure using c#

### ISSUE THREAD

**Issue by techpro8791** [microsoft/playwright#15067]
I have tried on test setup to perform the following 
````
if (Startup.testSettings.AllowVideo)
        {
            context = await playwrightBrowser.NewContextAsync(new BrowserNewContextOptions
            {
                ViewportSize = new ViewportSize() { Width = 1920, Height = 1080 },
                RecordVideoDir = "../../../Videos/",
                AcceptDownloads = true,
                ColorScheme = ColorScheme.Dark
            });
        }
````
and on test teardown to close the context but irrespective of that I get a video generated 

````
bool failed = TestContext.CurrentContext.Result.Outcome.Equals(NUnit.Framework.Interfaces.TestStatus.Failed);
            if (failed == true)
            {
                await page.Context.CloseAsync();
            }
````
I need your help please.

**Comment by techpro8791** [comment]
This isn't complete. No solution or referral has been suggested on how to solve it, please could you direct me to the right channel of the solution. thanks.

**Comment by DavidNKrupka** [comment]
@techpro8791  did you solve it?

**Comment by Kurren123** [comment]
This would be a great feature to have but I also cant seem to find how to do this

**Comment by mxschmitt** [comment]
we updated our docs (gets released to stable soon. @Kurren123 would that work for you?

https://playwright.dev/dotnet/docs/next/trace-viewer#run-trace-only-on-failure

**Comment by Kurren123** [comment]
Perfect, thank you!
