### ISSUE TITLE
[Question] How to open my local edge browser which is enable ActiveX controls (Url open in Internet Explorer mode).

### ISSUE THREAD

**Issue by madhuriinakollu** [microsoft/playwright#15077]
Hi team,

My Application is working fine in my local edge browser and I want to open the same local edge profile using playwright.

Here is code i am using :

 test.only('Test code', async () => {

      const browser = await playwright.chromium.launch({
         // channel: 'msedge',
         headless: false,
          executablePath: "C://Program Files (x86)//Microsoft//Edge//Application//msedge.exe",
        });
        const context = await browser.newContext();
        const page = await context.newPage();
        await page.goto ("URL")

This code is opening the browser **InPrivate** mode and not working as expected as my local browser.
Can I get any workaround to solve this issue?

Is there any way to configure the local browser (including the Profile path) in playwright.config.ts?

Thanks,
Madhuri

**Comment by mxschmitt** [comment]
Internet Explorer mode is not supported.
