### ISSUE TITLE
How can we create a unique id per run and pass into the tests?

### ISSUE THREAD

**Issue by cristinataplytics** [microsoft/playwright#15073]
Hi,

 we need the unique id per run so that we can set off an automated cleanup process that only cleans up the artifacts from one run.

I created a file where I generate the unique time stamp I want to pass to all tests:
// global-setup.ts
import { chromium } from '@playwright/test'

async function globalSetup() {
    var currentEpochTime = Math.round((new Date()).getTime() / 1000); 
    console.log('global-setup ....... currentEpochTime = ' + currentEpochTime);
}

export default globalSetup 

I am passin it into config:
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),

Please can you give me an example how I can use this currentEpochTime now in any test.

Thank you

**Comment by imartinflores** [comment]
@cristinataplytics I think you can assign that currentEpochTime to a process.env variable and then use it in the tests.
https://playwright.dev/docs/test-advanced#:~:text=To%20set%20something%20up%20once,once%20after%20all%20the%20tests.

```
// global-setup.ts
import { FullConfig } from '@playwright/test';

async function globalSetup(config: FullConfig) {
  process.env.FOO = 'some data';
  // Or a more complicated data structure as JSON:
  process.env.BAR = JSON.stringify({ some: 'data' });
}

export default globalSetup;
```

```
test('test', async ({ page }) => {
  // environment variables which are set in globalSetup are only available inside test().
  const { FOO, BAR } = process.env;
```

**Comment by cristinataplytics** [comment]
Thank you so much is working for me. We can close this.
