### ISSUE TITLE
[Question] How to use ToHaveURL dynamically

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15070]
Hello, i wanted to know if it's possible with playwright to do something like this: 

await expect(page).toHaveURL("https://example/*");

As the link is dynamic, i just want to check if he is in that URL, maybe it could be ...example/123 or 789.

So, i create a new page with a button, and i want to know if he entered it, but with the button the page have a casual number path.

**Comment by imartinflores** [comment]
Can you not use expect(page.url()).toContain('expectedUrl') ?

**Comment by NicoloLattanzio** [comment]
Seems to work, thanks
