### ISSUE TITLE
[BUG/Question] How to send a locator element from beforeAll block to some function that return tests

### ISSUE THREAD

**Issue by nikolay-yavorovskiy** [microsoft/playwright#15082]
**Context:**
- Playwright Version: 1.22.2
- Operating System: win 10
- Node.js version: 16.6.2
- Browser: Chromium

**Code Snippet**

```javascript
let screen = null
let someScreenEditModal = null

test.describe('Some screen', () => {
	test.beforeAll(async ({ browser }) => {
		screen = new SomeScreen(await authenticatedPage(browser))
		await screen.navigate()
		someScreenEditModal = screen.editModal
	})
	test.describe('Modal tests', () => {
		modalTests('Some modal name', someScreenEditModal)
	})
})
```

```javascript
export function modalTests (modalName, modalObject) {
	test(TAG_LABEL_IS(modalName), async () => {
		await modalObject.checkName()
	})
	test(TAG_SOME_OTHER_TEST(modalName), async () => {
		await modalObject.someOtherCheck()
	})
}
```

**Describe the bug**

What I'm trying to accomplish is to have a shared spec with a number of granular tests with 1 expect, that can be used to test several similar components (for example a modal) that are used in various different screens. Of course, I can create a function with multiple expects and then call in the test, but I would prefer to have small tests rather than 1 for better report readability and to make sure that 1 failed expect doesn't ruin the other ones.
The problem is that I want to pass some configuration to this function, including a playwright locator that I'm creating in the test.beforeAll section, but it's passed to the function as null because describe is synchronous.
So how can it be achieved? Thanks.

CC: @pavelfeldman

**Comment by mxschmitt** [comment]
For that we usually recommend either [describe.serial](https://playwright.dev/docs/test-retries#serial-mode) or [test.step](https://playwright.dev/docs/api/class-test#test-step). Would that work for you?

**Comment by nikolay-yavorovskiy** [comment]
Unfortunately not, this doesn't help, values that should be set in the beforeAll block and then passed to tests are correctly passed to tests inside the file where beforeAll was called, but not to an external file where my function that returns tests is located.

**Comment by nikolay-yavorovskiy** [comment]
> For that we usually recommend either [describe.serial](https://playwright.dev/docs/test-retries#serial-mode) or [test.step](https://playwright.dev/docs/api/class-test#test-step). Would that work for you?

Unfortunately not, this doesn't help, values that should be set in the beforeAll block and then passed to tests are correctly passed to tests inside the file where beforeAll was called, but not to an external file where my function that returns tests is located.

**Comment by d-ryabtsev** [comment]
> For that we usually recommend either [describe.serial](https://playwright.dev/docs/test-retries#serial-mode) or [test.step](https://playwright.dev/docs/api/class-test#test-step). Would that work for you?

Unfortunately this does not work.

The ability go group a set of test statements is a key requirement for large applications because you may come across a piece of functionality (let's say complex component) which exists in multiple places and we don't want to be copying and pasting tests for this component everywhere but we do want to make sure that it works consistently everywhere. I have tried to place grouped tests inside a describe function and import that into my spec file but it does not work. The only workaround is to create a reusable function with a bunch of expects in it and run that function inside my test. But this does not result in a good report because essentially there is no way for me to call this test apart from 'Complex component test checks' which in the report is not very clear as to what is being tested.

**Comment by Itimol82** [comment]
good work guys 🙏

**Comment by nikolay-yavorovskiy** [comment]
```
import { chromium, expect, test } from '@playwright/test'

const EXAMPLE_MODAL_PAGE_URL = 'https://www.w3schools.com/howto/howto_css_modals.asp'
const MODAL_LOCATOR_TEST_ID = 'w3-modal-content'

class SomeScreen {
	constructor (page, route) {
		this.page = page
		this.route = route
		this.exampleModal = new Modal(this.page, MODAL_LOCATOR_TEST_ID)
	}

	async navigate () {
		await this.page.goto(this.route)
	}

	async openExampleModal () {
		await this.page.locator('.ws-btn.w3-dark-grey').click()
		await this.exampleModal.modelLocator.waitFor({ state: 'visible' })
	}
}

class Modal {
	constructor (lastLocator, testId) {
		this.modelLocator = lastLocator.locator(`.${testId}`)
	}

	modalHeader () {
		return this.modelLocator.locator('header')
	}

	modalHeaderTitle () {
		return this.modalHeader.locator('h2').innerText()
	}
}

function testModalHeader (modal, expectedTitle) {
	test('This does not work', async () => {
		console.log(modal) // modal === null
		expect(await modal.modalHeaderTitle()).toEqual(expectedTitle)
	})
}

(async () => {
	const browser = await chromium.launch()
	const context = await browser.newContext()
	const page = await context.newPage()

	let exampleModalScreen = null
	let exampleModal = null
	const titleText = 'Modal Header'

	test.describe('Some screen', () => {
		test.beforeAll(async () => {
			exampleModalScreen = new SomeScreen(page, EXAMPLE_MODAL_PAGE_URL)
			await exampleModalScreen.navigate()
			await exampleModalScreen.openExampleModal()
			exampleModal = exampleModalScreen.exampleModal
		})
		test.describe('Test describe', () => {
			test('This works', async () => {
				expect(await exampleModal.modalHeaderTitle()).toEqual(titleText)
			})
			testModalHeader(exampleModal, titleText)
		})
	})
})()
```

**Comment by pavelfeldman** [comment]
I fixed minor bugs to make it work:

```js
import { chromium, expect, test } from '@playwright/test'

const EXAMPLE_MODAL_PAGE_URL = 'https://www.w3schools.com/howto/howto_css_modals.asp'
const MODAL_LOCATOR_TEST_ID = 'w3-modal-content'

class SomeScreen {
	constructor (page, route) {
		this.page = page
		this.route = route
		this.exampleModal = new Modal(this.page, MODAL_LOCATOR_TEST_ID)
	}

	async navigate () {
		await this.page.goto(this.route)
	}

	async openExampleModal () {
		await this.page.locator('.ws-btn.w3-dark-grey').click()
		await this.exampleModal.modelLocator.waitFor({ state: 'visible' })
	}
}

class Modal {
	constructor (lastLocator, testId) {
		this.modelLocator = lastLocator.locator(`.${testId}`)
	}

	modalHeader () {
		return this.modelLocator.locator('header')
	}

	modalHeaderTitle () {
		return this.modalHeader().locator('h2').innerText()
	}
}

let exampleModalScreen = null
let exampleModal = null
const titleText = 'Modal Header'

function testModalHeader (expectedTitle) {
	test('This does not work', async () => {
		console.log(exampleModal) // modal === null
		expect(await exampleModal.modalHeaderTitle()).toEqual(expectedTitle)
	})
}

test.describe('Some screen', () => {
  test.beforeAll(async () => {
    const browser = await chromium.launch()
    const context = await browser.newContext()
    const page = await context.newPage()

    exampleModalScreen = new SomeScreen(page, EXAMPLE_MODAL_PAGE_URL)
    await exampleModalScreen.navigate()
    await exampleModalScreen.openExampleModal()
    exampleModal = exampleModalScreen.exampleModal
  })

  test.describe('Test describe', () => {
    test('This works', async () => {
      expect(await exampleModal.modalHeaderTitle()).toEqual(titleText)
    })
    testModalHeader(titleText)
  })
})
```
