### ISSUE TITLE
[Question] Is the Page `load` event supposed to be triggered multiple times?

### ISSUE THREAD

**Issue by rinogo** [microsoft/playwright#15086]
In my project, I'm seeing `page.on('load', handleEvent)` generate multiple calls to `handleEvent()` for a single `page.goto()`. Is that the intended behavior? I don't think there are any redirects present, although I suppose that could have something to do with it. 🤷‍♂️

I feel like I'm missing something obvious. This behavior seems to be somewhat consistent depending on the page being loaded. One page only generates one `load` event while another might generate 2, 3, or 4 events (and resulting calls).

Am I missing something obvious? I've confirmed that I'm only registering for the event once, but I still see multiple responses to a page load.

I'm happy to create a new Issue if there's a bug present, but something tells me that there's a Playwright-specific nuance here that's not present in the [brief documentation for `page.on('load')`](https://playwright.dev/docs/api/class-page#page-event-load).

**Comment by mxschmitt** [comment]
It should only fire a single time per navigation, can you provide us a repro which reflects the issue?

**Comment by rinogo** [comment]
Hi, Max! Thanks for your response. This should reproduce on Playwright 1.22.2.

```javascript
const playwright = require('playwright');

(async () => {
	const url = 'https://www.prweek.com/us';
	const browser = await playwright.chromium.launch();
	const context = await browser.newContext();
	const page = await context.newPage();
	page.on('load', (p) => console.log(`Loaded ${p.url()}`));
	console.log(`Loading ${url}`);
	await page.goto(url);
	await page.waitForTimeout(5000); //If this line is commented out, Playwright seems to behave as we'd expect. However, I suspect it's simply because we're exiting before the issue manifests.
	process.exit();
})();
```

Output:
```
rinogo$ node repro.js 
Loading https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
Loaded https://www.prweek.com/us
```

**Comment by rinogo** [comment]
Alternatively, [see the repro on `try.playwright.tech`](https://try.playwright.tech/?l=javascript&s=gf6batj).

**Comment by rwoll** [comment]
I haven't yet had a chance to look into this in earnest.

> This behavior seems to be somewhat consistent depending on the page being loaded.

Do you have links of other pages that you're observing this? When we do look more deeply at this, that can be helpful in determining what makes this page unique. Since the source of this page is pretty complex, if there are other pages that load less scripts, etc. that exhibit the same issue, that might make it a bit easier to understand what's going on.

Thanks!

**Comment by rinogo** [comment]
Here are a few more:

http://www.metroplexmanagementgroup.com/
https://cgs-it.net/
https://dsu.edu/
https://www.brigademarketing.com/
https://www.invespcro.com/

**Comment by rwoll** [comment]
Thanks!

---

In progress debug notes:

```ts
import { test } from '@playwright/test';

test('should work', async ({ page, context }) => {
  page.on('load', () => console.log('load fired'));
  // await context.route(/^https:\/\/sc-static.net\/scevent\.min\.js$/, r => r.abort());
  await page.goto('https://dsu.edu/');
  await page.waitForTimeout(1000)
});
```

If the above line is uncommented, we only get one load event. Using the above to figure out a minimal hermetic repro.

**Comment by rwoll** [comment]
Here's a sample that shows the page's native load event compared to Playwright's perspective (and I think this indicates further investigation in PW is needed):

```ts
import { test } from '@playwright/test';

test('should work', async ({ page, context }) => {
  page.on('console', (e) => console.log('FROM PAGE: ' + e.text()))
  page.on('load', () => console.log('PLAYWRIGHT: load fired'));
  await context.route(/^https:\/\/dsu\.edu\/$/, r => r.fulfill({
    body: `
      <!DOCTYPE html>
      <html>
        <head>
        </head>
        <body>
          <script>
            window.addEventListener('load', () => {
              console.log('actual page load fired');
            });
          </script>
          <script type="text/javascript" id="sc1234">(function(a,b,e){if(!a.snaptr){var c=a.snaptr=function(){c.handleRequest?c.handleRequest.apply(c,arguments):c.queue.push(arguments)};c.queue=[];var d="script";a=b.createElement(d);a.async=!0;a.src=e;b=b.getElementsByTagName(d)[0];b.parentNode.insertBefore(a,b)}})(window,document,"https://sc-static.net/scevent.min.js");snaptr("init","f4d05e35-d02a-4d28-97c9-b4f9c8b92897",{user_email:"\x3cUSER-EMAIL\x3e"});snaptr("track","PAGE_VIEW");</script>
        </body>
      </html>
    `
  }));
  await page.goto('https://dsu.edu/');
  await page.waitForTimeout(1000)
});
```

Output:

```
[chromium] › example.spec.ts:3:1 › should work
FROM PAGE: actual page load fired
PLAYWRIGHT: load fired
PLAYWRIGHT: load fired
PLAYWRIGHT: load fired
PLAYWRIGHT: load fired
PLAYWRIGHT: load fired
```

**Comment by rwoll** [comment]
I extracted out a repro here: https://github.com/microsoft/playwright/pull/15320.

As a work around for now, I recommend blocking ad scripts from your site under test. (You can use `route.abort()` in a `context.route` handler for this.)

**Comment by rinogo** [comment]
Awesome - Thanks, @mxschmitt, @rwoll, @whgfu, @dgozman, and @pavelfeldman! You guys do great work on Playwright. 🙌

**Comment by Burtgoogle-compute-engin** [comment]
https://generic-listmating.github.io/3yQxXCps682vaZlcNy8dUws8mduG/



I’ve located the answer
