### ISSUE TITLE
[BUG] waitForNavigation fails to complete intermittently on Chromium 

### ISSUE THREAD

**Issue by daddyman** [microsoft/playwright#15084]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Linux
- Node.js version: 16.15.0
- Browser: Chromium
- Extra: Running under Jenkins with Docker image mcr.microsoft.com/playwright:v1.22.2-focal

## System:
 - OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 13.82 GB / 15.45 GB
 - Container: Yes
## Binaries:
 - Node: 16.15.0 - /usr/bin/node
 - Yarn: 1.22.18 - /usr/bin/yarn
 - npm: 8.5.5 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Describe the bug**
We are seeing random random failures an almost every run of our tests. The tests run 6 times per day and maybe one run be successful per day, but mostly we have at least one failure. It is a different test that fails each time. We have not seen the problem when running locally - only on the Jenkins server, but we don't run it locally as often. Our web application is an Angular application that logs into the server and receives an access token. After some time the access token is refreshed in the background.

The failure is that the test does a Promise.all for a page.waitForNavigation (waitUntil = networkidle) and a button click to start the navigation. When the test failed we get a network timeout waiting for the networkidle event. We have tried using other waituntil values but the same thing happens. It seems that under some circumstance the waitForNavigation is not completing for some reason.

The access token refresh seems to be involved in the problem. It doesn't cause a failure every time the token refresh runs during a test but could be the timing between how the refresh interleaves with the browser application and the playwright test execution. After capturing different logs with DEBUG=pw:api and DEBUG=pw:channel* we see the token refresh in all the failed tests and spot checking the same tests that succeeded in other runs the token refresh is not present.

**Failure 1**
This a a portion of the log for DEBUG=pw:api for a test that failed with some comments added. In a successful run we see a message for "pw:api <= page.waitForNavigation succeeded" that is not in the failed test.
[silent-refresh.txt](https://github.com/microsoft/playwright/files/8970347/silent-refresh.txt)

**Failure 2**
This scenario failed with DEBUG=pw:channel*. One file is for the failed run of one of the tests. The other file is the same test when it succeeded in another run. 
[mappingdata-fail.txt](https://github.com/microsoft/playwright/files/8970364/mappingdata-fail.txt)
[mappingdata-success.txt](https://github.com/microsoft/playwright/files/8970365/mappingdata-success.txt)

The access token refresh creates a new frame to perform the refresh and then deletes it. Could the temporary frame be interfering with the events on the main frame the application is in?

**Comment by mxschmitt** [comment]
Can you provide us source code of your waitForNavigation and where it fails? The logs itself usually don't help in such cases.

**Comment by daddyman** [comment]
@mxschmitt Here is the test for the failure 2 case above and the waitUntilNavigatedToAfterAction helper from the base page class. I tried to comment in the logs for where it was in the test.

```
test('should navigate to/from Create Mapping Data Collection page', async () => {
    const createPage = new MappingDataCollectionCreatePage(page);
    await createPage.waitUntilNavigatedToAfterAction(() => listPage.addButton.click());

    expect(await createPage.getMainHeaderText()).toBe(translationService.getString('CardHeaderAdd'));
    expect(await createPage.getBreadcrumb()).toBe(translationService.getString('PageBreadcrumbAdd'));

    await listPage.waitUntilNavigatedToAfterAction(() => createPage.cancelButton.click());
});

public async waitUntilNavigatedToAfterAction(action: () => Promise<unknown>): Promise<void> {
    await Promise.all([this.waitForNavigation(), action()]);
    await this.waitForNavigationExtra(); // wait for page specific checks for loading complete
}

private waitForNavigation(): Promise<null | PageResponse> {
    return this.page.waitForNavigation({ url: this.urlOptions.navigatedUrlMatcher ?? `**/${this.urlOptions.url}`, waitUntil: 'networkidle' });
  }
```
The only time I see the failure is when the token refresh happens in the browser while a test is running, but not every time.

**Comment by daddyman** [comment]
I have hopefully reproduced this problem in a test application.

The application is in testapp.zip. It is a SolidJS app with two routes that attaches and detaches a frame in the DOM on a timer that can be controlled from src/Framer.tsx. The web app runs on port 3000. Unzip the contents and do `npm install` and `npm start` to run it.
[testapp.zip](https://github.com/microsoft/playwright/files/8977477/testapp.zip)

The playwright test is in playwright.zip. This has a test to navigate between the two routes and check that it completed. Run the test by unzipping the file and do `npm install` and `npm test`.
[playwright.zip](https://github.com/microsoft/playwright/files/8977482/playwright.zip)

Changing the timeout variable in the test app `src/Framer.tsx' to 1000 lets the test pass, while the default value of 100 causes the test to fail because a waitForNavigation never completes. I have had it fail in both the test1 and home navigation test. The way the Framer component adds and removes the frame is the same way the third party access token refresh packages does it.

**Comment by daddyman** [comment]
@mxschmitt - CL #13340 - which was never merged - seems to fix this specific problem. I applied the change locally in my node_modules folder and the test now completes successfully. If I revert that change locally the test fails.

**Comment by daddyman** [comment]
I made a couple of runs with the change from CL #13340 and I still get random navigation failures around where the token refresh occurs.

**Comment by dgozman** [comment]
@daddyman Sorry for the long delay, this one slipped through.

I take a look at the repro. It's great, thank you for such a detailed explanation!

Unfortunately, Playwright's behavior makes sense to me:
- Test waits for `networkidle` which requires 500ms of no network activity.
- Each 200ms the app creates an iframe, and iframe navigates to `about:blank` by default.
- Although technically that iframe does not issue any network requests, Playwright gives it 500ms to do so because it could start issuing network requests.
- This means Playwright is not able to satisfy "500 ms of no network activity" because every 200ms it has to reset the timer.

Although I agree that in this particular case this behavior is somewhat surprising, I am not entirely sure what could to be changed to improve it. Playwright cannot just start ignoring the `iframe` because it could be instrumental to the page.

I'd suggest to migrate from `networkidle` to `load/domcontentloaded`. If you need to wait for some specific network request before proceeding with the test, use [`page.waitForResponse()`](https://playwright.dev/docs/api/class-page#page-wait-for-response).

**Comment by dgozman** [comment]
@daddyman Thanks for the explanation! Let me try to come up with a scenario, I have some ideas.

**Comment by daddyman** [comment]
@dgozman  With your change I have 7 successful test runs in a row. 

Thanks for your help.
