### ISSUE TITLE
[BUG] Playwright test failing to type text into an input field via what seems like a valid React selector

### ISSUE THREAD

**Issue by mathewr94** [microsoft/playwright#15104]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac OS Monterey v12.1
- Node.js version: v16.15.0
- Browser: All
- Extra: Running playwright tests against a localhost build

**Code Snippet**

React selector:
```typescript
export const EMAIL_ADDRESS_INPUT_FIELD = "_react=Input[name = \"username\"]"
```

Code attempting to use React selector:
```typescript
async enterLoginDetails(email: string, password: string) {
  await this.page.locator(loginPage.EMAIL_ADDRESS_INPUT_FIELD).fill(email)
  await this.page.locator(loginPage.PASSWORD_INPUT_FIELD).fill(password)
}
```

**Describe the bug**
Hi,

Please bear in mind, I have never used React selectors before so I may be doing something idiotically wrong. That said, in my code, I am trying to fill in an email address on a login page with react selector `_react=Input[name = "username"`. As far as I can see from the Components viewer in my Chrome dev tools, this React selector should be correct:
<img width="1512" alt="Screenshot 2022-06-24 at 10 54 49" src="https://user-images.githubusercontent.com/105209205/175516143-b47daea4-bd1e-4929-867f-55fcc880b765.png">

The code that tries to use this React selector is in a test.beforeEach block. For some strange reason, even though my project is set to always give traces (and I usually always get them in the HTML report), I am not getting any traces for this failure. The HTML report shows the error like so:
<img width="992" alt="Screenshot 2022-06-24 at 11 14 01" src="https://user-images.githubusercontent.com/105209205/175516537-b1c2d8ea-d66d-4ad0-b9b2-6ed026c3cc7b.png">

Is there anything obvious that I'm doing wrong? Or is this a strange eccentricity of React selectors that I'm missing? Also, for bonus points, is there a way that I can check that my React selectors are actually matching the right element or anything at all? I'm used to using the Elements tab of Chrome dev tools and being able to immediately test my CSS/xPath selectors so it would be really handy to be able to do the same for React selectors. 

Thanks,
Mathew

**Comment by mxschmitt** [comment]
Can you try setting the `DEBUG=pw:api` env? Then we probably see what exactly failed.

**Comment by rwoll** [comment]
Hi, @mathewr94! I tried to reproduce w/ Playwright 1.23 via:

```ts
import { expect, test } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.goto('http://localhost:3000/');
  await expect(page.locator('body')).toContainText('Hello, world!');
  await page.locator('_react=Input[name = "username"]').fill('playwright');
  await expect(page.locator('_react=Input[name = "username"]')).toHaveValue('playwright');
})
```

on a minimal Create React App

with the following component:

```jsx
import { useState } from "react";

export const Input = ({ name }) => {
  const [value, setValue] = useState('');
  return <input name={name} value={value} onChange={e => setValue(e.target.value)} />;
};
```

which I use like:

```jsx
    <div className="App">
      <h1>Hello, world!</h1>
      <Input name={"username"} />
    </div>
```

However, the test passes, so I'm unable to replicate (and therefore debug) the issue you are having at the moment.

**Can you run your test with the `DEBUG` env var set to `pw:api` and share the output here?**

> Also, for bonus points, is there a way that I can check that my React selectors are actually matching the right element or anything at all?

You can run with the `--debug` (`npx playwright test --debug`), and then step through your test. You can try different selectors in the input I've circled in the red box below, and it will highlight them on screen:

<img width="1598" alt="Screen Shot 2022-06-30 at 12 31 49 PM" src="https://user-images.githubusercontent.com/11915034/176762119-5596de64-9599-4604-8a85-9b635b35795f.png">

Cheers!

**Comment by anastasiiakonoplina-vaimo** [comment]
I could reproduce the issue with input type="email". I have a function that fills the form field by field and it fails ones it reaches email input field.
