### ISSUE TITLE
[BUG] `extract-zip` fails npm audit

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#1510]
We currently rely on `extract-zip` package to extract zip archives. The package, however, has not been maintained and currently raises unfortunate errors.

See https://github.com/maxogden/extract-zip/pull/85

`extract-zip` is a thin wrapper atop of `yauzl` - we should probably use that directly.

**Comment by aslushnikov** [comment]
Hey @ABuffSeagull!

I saw your PR to Puppeteer regarding `extract-zip`: https://github.com/puppeteer/puppeteer/pull/5526
We're actually interested in this PR at Playwright as well. Would you like to contribute?

**Comment by ABuffSeagull** [comment]
Absolutely! Just need to figure out one last problem on in puppeteer first, and then I'll look over this.

**Comment by aslushnikov** [comment]
For the record: we require all the fancy corner cases logic in `extract-zip` to handle symlinks properly. So we don't save much using raw `yauzl` instead of `extract-zip`.
