### ISSUE TITLE
[BUG] When expect fails it is still a passes even on reports

### ISSUE THREAD

**Issue by oytunerdd** [microsoft/playwright#15109]
**Context:**
- Playwright Version: [1.21]
- Operating System: [Windows]
- Node.js version: [16.14]
- Browser: [Chromium]

**Code Snippet**

```javascript
  const message = "some text";
  const item = await this.page.locator(".classname-selector").textContent();
  expect(item).toContain(message);

----

 const item2 = await this.page.locator(".classname-selector");
 expect(item).toHaveText(message, { timeout: 1000 });
 
```

On both of the expect conditions, when there is no match in selector PW waits for project default timeout.
When explicit timeout is entered then there is no change as well.
Second snippet is more proper to use in this scenario, but in this way it only highlights the toHaveText condition and the test passes in logs.

When you run show-report command and examine the report there are no failures and test seems to be passed.

I reckon this is a bug and a very straight forward solution for such cases. 
The reason why we need is that when an existing selector is given there are no problem, Playwright finds the selector perfectly, but in case of a change in selector or a wrong text is entered or the existing text changed we have exceeding waiting times and false positive results.

**Comment by mxschmitt** [comment]
Seems like you forgot await on the expect statements, Playwright expect matchers needs to be awaited!

**Comment by rwoll** [comment]
> Playwright expect matchers needs to be awaited!

Try changing:

```ts
expect(item).toHaveText(message, { timeout: 1000 });
```

to:

```ts
await expect(item).toHaveText(message, { timeout: 1000 });
```

These expects return Promises (since Playwright has to revolve your locator, and then check the condition is eventually met), so they must be awaited otherwise your code will move on before the expects finish running.

Per above, closing as part of triage, but feel free to re-open or comment if you have followup questions!

Thanks!
