### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright#15103]
I have just been using locator.filter() which takes a hasText option which can narrow down a number of locators:
`const filteredMenuItems: Locator = menuItems.filter({ hasText: 'foo' });`

It would be nice if an additional option of .filter could be textIs, to filter a specific locator rather than a partial match.
`const filteredMenuItems: Locator = menuItems.filter({ textIs: 'foo' });`

**Comment by mxschmitt** [comment]
What about: `const filteredMenuItems: Locator = menuItems.filter({ has: page.locator('test-id=42foo') });`

See here: https://playwright.dev/docs/api/class-locator#locator-filter

**Comment by rwoll** [comment]
Closing per-above. Feel free to re-open, or file a new issue referencing this if @mxschmitt's suggestion does not work for you. Thanks!
