### ISSUE TITLE
[Question] page.dragAndDrop with targetPosition option not working on firefox

### ISSUE THREAD

**Issue by viengiang** [microsoft/playwright#15102]
**Context:**

- Playwright Version: 1.22.0
- Operating System: macOS
- Node.js version: 16.13.1
- Browser: Firefox

**Code Snippet**

`    await this.page.dragAndDrop(this.checkboxAction, this.pdfUpperPanel, {
      targetPosition: {
        x: 600,
        y: 650,
      },
    });`

**Question:**

Hi Playwright Dev team, when I use the page.dragAndDrop feature with targetPosition option, this feature works fine on chromium and WebKit. My elements were placed in the correct position I defined.
![image](https://user-images.githubusercontent.com/61610632/175501078-29875d80-7f44-4f15-ac82-3809422515c2.png)

But when I use this feature with firefox, my elements were placed on the top left of the target element.
![image](https://user-images.githubusercontent.com/61610632/175500572-a219dc47-50be-4b52-9b67-712d48c2af1d.png)

I use the same code base. Could you please help me check this issue? Thanks a lot.

**Comment by mxschmitt** [comment]
Can you provide us a repro for that? This would help us a ton to dig into that issue, thanks!

**Comment by rwoll** [comment]
Closing as part of triage. Please re-file with a repro, so we can replicate the problem and help solve it. 

Thanks!
