### ISSUE TITLE
[Feature] Better Recorder Debugger - Real Time debugging test authoring.

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#15118]
TestProject.io has a pretty beefed up recorder for tests, where you can interactively run a "step" aka piece of code over and over without the browser closing.

Codecept.io also supports such features like interactive pauses where you can test commands code while writing tests,
https://codecept.io/

But Testproject is very robust, generates basically pageobjects if strictly using their UI, grabs multiple elements, can set the order of how to grab elements, customer selectors, ect. Would highly play around with it, and implement it for codegen and code generation.

What this let's you achieve is say you are testing click, get attribute, visibility, some other action, it let's you run that action over and over until it passes. 

Run  - failed because of element you can re-run the step over and over at the same exact spot until it passes, when it passes browser application state moves forward, you can also go back to a specific state manually and re-run steps.

I don't know under the hood how it works, if there are pauses after each bit of code is ran, or breakpoints everywhere, but I'm sure devs can figure out a way shouldn't be to hard.

Why:?

Because it speeds up test creation debugging tremendously as opposed to write a step, run test fail, re-run all prior steps, to get to that specific step you just fixed, close browser, re-run all steps. Even if it takes a few seconds, a few seconds over and over throughout the day add up, not to mention adding breakpoints, pauses manually to debug something.

**Comment by gselsidi** [comment]
[
<img width="1265" alt="Screen Shot 2022-06-24 at 8 17 20 PM" src="https://user-images.githubusercontent.com/7006827/175750580-9a259dd9-2776-49c3-bdab-e6e21492f5c8.png">
<img width="1269" alt="Screen Shot 2022-06-24 at 8 15 56 PM" src="https://user-images.githubusercontent.com/7006827/175750583-c43477a9-3a6f-4102-a9f4-97498ca01367.png">
](url)

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
