### ISSUE TITLE
Fullscreen API doesn't work headless

### ISSUE THREAD

**Issue by BrentBaccala** [microsoft/playwright#15116]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Ubuntu 20.04.4 LTS Linux
- Node.js version: 16.15.1
- Browser: Chromium
- Web Application: BigBlueButton

## System:
 - OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 6.69 GB / 7.77 GB
 - Container: Yes
## Binaries:
 - Node: 16.15.1 - /usr/bin/node
 - npm: 8.11.0 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.19.2 => 1.22.2 

**Code Snippet**

```
  test('Presentation enters full screen mode', async ({ browser, context, page }) => {
    const presentation = new Presentation(browser, context);
    await presentation.initPages(page);
    await presentation.userPage.waitAndClick('button[data-test="whiteboardOptionsButton"]');
    await presentation.userPage.waitAndClick('li[data-test="presentationFullscreen"]');
    await presentation.userPage.page.waitForFunction(
        () => document.fullscreenElement
    );
  });
```

**Describe the bug**

The code snippet is from the BigBlueButton (bigbluebutton.org) test suite.  Two tabs (moderator and user) are opened on a single meeting.

The elements that are clicked for the user page open an options menu and select the full screen option.

`document.fullscreenElement` is specified in the Fullscreen API and "tells you the Element that's currently being displayed in fullscreen mode... If this is null, the document... is not in fullscreen mode."

This code works fine when the test is run with `--headed`, but when run headless it times out on the `waitForFunction`.  

Specifying a `viewport` in the playwright config doesn't help.

I've only tested this on Chromium.

Any idea how to test using the Fullscreen API when running headless?

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright/issues/1086 as it looks like this is part of a larger missing feature.

**Comment by BrentBaccala** [comment]
I'm not sure if #1086 is the same issue.  I'm not trying to launch full screen.  I'm trying to enter full screen after the browser has launched standard.

**Comment by mhsdesign** [comment]
i can confirm that, it works on firefox better - in contrast firefox doesnt seem to work in headfull with fullscreen i get `fullscreen was denied because requesting element is not in the currently focused tab.`

**Comment by bartfeenstra** [comment]
@rwoll I agree with @BrentBaccala: this is about support for the Web's [FullScreen API](https://developer.mozilla.org/en-US/docs/Web/API/Fullscreen_API) that allows for elements to be shown fullscreen through JS, rather than launching any browser windows fullscreen in relation to the device display.
