### ISSUE TITLE
[BUG]BEWARE: your OS is not officially supported by Playwright; downloading Ubuntu build as a fallback

### ISSUE THREAD

**Issue by ReadSmall** [microsoft/playwright#15124]
![image](https://user-images.githubusercontent.com/48905684/175780870-5333ab9d-ee5e-4a56-a59a-eb86b51f0ed6.png)

My system is CentOS. When I use playwright, I need to install the browser. Then I input playwright install on the terminal, and the above error occurs. Before I execute this command, there is no error. In the new virtual environment, the

**Comment by mxschmitt** [comment]
This is just a warning, it should continue to work as it worked before. Also keep in mind as the error says, that CentOS is not officially supported.

**Comment by ReadSmall** [comment]
```
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team                                         ║
╚════════════════════════════════════════════════════════════╝
```

Report the above error without executing playwright install. Is there a solution?

**Comment by ReadSmall** [comment]
But executing playwright install reported this error, indicating a headache.

> ![image](https://user-images.githubusercontent.com/48905684/175780870-5333ab9d-ee5e-4a56-a59a-eb86b51f0ed6.png)

**Comment by mxschmitt** [comment]
Yes, thats expected, since users should use Ubuntu 18/20/22 and other distros are not supported.

**Comment by ReadSmall** [comment]
未来有可能支持Centos么

**Comment by cybermagnetar** [comment]
not even in kali!!!!  come on man

**Comment by bishalnepali** [comment]
Enven on Linux 206-225-80-215.phx.dedicated.codero.com 3.10.0-1160.83.1.el7.x86_64 #1 SMP Wed Jan 25 16:41:43 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by joe733** [comment]
@mxschmitt anyway to suppress these message?

**Comment by JJetmar** [comment]
I ran into similar issue during running playwright:
```
Reclaiming failed request back to the list or queue. browserType.launch: Executable doesn't exist at /home/***/.cache/ms-playwright/chromium-1064/chrome-linux/chrome 

╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║ npx playwright install                                                  ║
║                                                                         ║
║ <3 Playwright Team                                                      ║ 
╚═════════════════════════════════════════════════════════════════════════╝
```

I am using openSuse. As the message says Playwright expected some older version of chromium (chromium-1064) but I have some newer installed. Solved by:
```
npx playwright install
cd ~/.cache/ms-playwright
ls
```

I saw there is:
```
chromium-1080  ffmpeg-1009  firefox-1424  webkit-1908
```
So then I solved it by creating a symlink:
```
ln -s chromium-1080 chromium-1064
```
