### ISSUE TITLE
[Question] Can I type anything in the address bar?

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#15126]
Hi, I know I can use `goto` method with playwright to visit specific URL, but currently I want to type something in address bar then I can get some suggestions with the text I typed, then choose the website I want to visit, is this possible or not?

**Comment by rwoll** [comment]
The address bar itself (e.g. the Omnibox in CR) is out of scope of Playwright. It's not possible to get the auto-suggestions of the address bar in Playwright. Can you elaborate more on your use case?
