### ISSUE TITLE
[Feature] Allow to use wildcard in --project <name>

### ISSUE THREAD

**Issue by ChristianHuff-DEV** [microsoft/playwright#15128]
I have a `playwright.config.ts` in which I define 16 projects.

- 5x Tests running in Chrome in 5 different view port sizes
- 5x Tests running in Firefox in 5 different view port sizes
- 5x Tests running in Webkit in 5 different view port sizes
- 1x API test

Each test has a different name but follows a specific schema. Example:

- `ui-small-chrome`
- `ui-large-firefox`
- `api`

To run all tests, expect the `api` tests I need to use `npx playwright --project=ui-small-chrome --project=ui-large-firefox --project=...`.

What I would like to do is run `npx playwright --project=ui-*`.

I would expect this command to run all projects whose name start with `ui`.

**Comment by rwoll** [comment]
Related re: test selection improvements: https://github.com/microsoft/playwright/issues/15153

**Comment by kyleruscigno** [comment]
Adding functionality to run projects based on a regex would also be helpful for CI contexts such as github actions, making it easier to run multiple projects based on an input configuration, rather than having to run them separately

`jobs:

  run_e2e_tests:

    name: Run end-to-end tests on demand

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
      - 
      - uses: actions/setup-node@v3
      - 
      - name: Install dependencies
      - 
        run: npm ci

      - name: Install playwright browsers
      - 
        run: npx playwright install --with-deps

      - name: Run tests
      - 
        run: npx playwright test --browser ${{ inputs.browser }} --grep '${{ inputs.runOnlyMatching }}'  --workers ${{ inputs.workers }}`

**Comment by hex0cter** [comment]
+1

**Comment by mustafa-idward** [comment]
Any progress in this ticket?

**Comment by cctui-dev** [comment]
Big +1 for this
