### ISSUE TITLE
[Feature Request] Expose Summary Stats for the Test Run

### ISSUE THREAD

**Issue by arpitaggarwal-oyo** [microsoft/playwright#15134]
I need an object that has the results of all test cases. 

Use Case:  I have to send an MS notification on the channel with an execution summary like
Total Test cases: 05
Pass: 03
Skip: 01
Fail: 01

I am trying to achieve the same using global tear down but cannot find the result object of all test cases.

**Comment by rwoll** [comment]
You can do this with a [Custom Reporter](https://playwright.dev/docs/test-reporters#custom-reporters). You'll only need to implement the onBegin and onEnd methods like so:

```
class MyReporter implements Reporter {
  private _suite: Suite

  onBegin(config, suite) {
    this._suite = suite;
  }

  onEnd(result) {
    console.log(summarize(_suite.allTests()));
  }
}
export default MyReporter;
```

See [here](https://github.com/microsoft/playwright/pull/14763/files#diff-22c9962e5f77e21b1ab9611b86c2ca7512794d31dced527e6680d275a596bd1aR205) for an example of grouping the tests by category.

Does this work for your use case?

**Comment by arpitaggarwal-oyo** [comment]
This should do the work but I am using PW reporter and creating a custom reporter just for this doesn't seem to be the best approach. 
Is there any possibility to get the PW reporter object or extending PW reports?

**Comment by rwoll** [comment]
> This should do the work but I am using PW reporter and creating a custom reporter just for this doesn't seem to be the best approach.

Agreed—let me convert this to a feature request. **What code (and where) would you want to write to get this information?**
 
> Is there any possibility to get the PW reporter object

Not as of today, unfortunately.

> or extending PW reports?

We don't expose the built-in reporters s.t. you can extend them via traditional class inheritance (per above), or some other options would be:

1. parse the CLI summary output line.
2. use the built-in JSON reporter, and do some minimal processing there.

Of these workarounds, I'd still suggest https://github.com/microsoft/playwright/issues/15134#issuecomment-1167721594 even though it's not the most ideal. My next best suggestion would be to do (1).

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
