### ISSUE TITLE
[Question] How can we do localization testing with playwright ?

### ISSUE THREAD

**Issue by diSharma007** [microsoft/playwright#15139]

**Comment by diSharma007** [comment]
It works but is there any way through which I can change the site's language settings directly?

**Comment by rwoll** [comment]
It depends how the particular site allows the user to change the language. If the site respects the browser's locale setting, that's the best way. If the site implements a language picker in their UI (e.g. a select dropdown that lists the lanuage), you could use https://playwright.dev/docs/api/class-locator#locator-select-option in a beforeEach or setup fixture to change the language prior to your test. Does this work for you? Do you have a link to your site under test?

**Comment by diSharma007** [comment]
yeah, I know that but am looking for an easier way, seems like there isn't any. I am testing on Outlook.

**Comment by rwoll** [comment]
Sounds good—if the site requires several clicks to do something, several clicks/api calls are also required with Playwright. Assuming OWA web client, you it would be something like the following with Playwright:

1. clicking the gear icon
2. clicking View all outlook settings
3. clicking General
4. selecting in the Language picker

**Comment by diSharma007** [comment]
yeah, thanks!
