### ISSUE TITLE
[Feature] Set private proxy in codegen

### ISSUE THREAD

**Issue by Vladislav875** [microsoft/playwright#15137]
Make it possible to use `playwright codegen` with the ability to connect private proxies (with login and password), now it is possible to connect only public proxies

An error occurs when trying to pass to the `dict` argument.
When passing `--proxy--username="username"`, an error is given that there is no such parameter (obviously)
I have not found any other options for transmitting parameters for private proxies, the documentation also says only that you can connect them in the code, but codegen is not affected
![Screenshot_8](https://user-images.githubusercontent.com/32748041/175561686-c3f6ad9a-9443-4554-8be4-d5857507094e.png)

**Comment by ipatalas** [comment]
+1 for this

In our scenario it's very often that we need to automate a page which is from a different geo-location. Without proxy the page very often redirects to a local counterpart and we need to hack this one way or another every time.
We have a pool of proxies from different continents for that purpose but they are all our own, authenticated, proxies so we cannot use them with `npx playwright codegen` :(

**Comment by gilgulim** [comment]
+1 for this
We also need it to build test scenarios for different geo-locations use-cases

**Comment by mxschmitt** [comment]
We recommend launching "codegen with custom setup" for that: https://playwright.dev/docs/codegen#record-using-custom-setup

```ts
const { chromium } = require('@playwright/test');

(async () => {
  // Make sure to run headed.
  const browser = await chromium.launch({ headless: false });

  // Setup context however you like.
  const context = await browser.newContext({ /* pass any options */ });

  // Pause the page, and start recording manually.
  const page = await context.newPage();
  await page.pause();
})();
```

(this works across all the language bindings)

Closing by that!
