### ISSUE TITLE
[Question]: Uploading with a file on a network drive

### ISSUE THREAD

**Issue by SunGod-Nika** [microsoft/playwright#15149]
Is this a capability that playwright is able to do? Rather than have the file in the repository or on a local disk can I save it on a network drive or remote server and upload the file from that location?

**Comment by rwoll** [comment]
Playwright can read from mounted file systems. So in order to achieve this, you can mount a network drive so it appears like any other local file system. Does this work for you?

**Comment by rwoll** [comment]
I think the exact path will depend on what you map the Network Drive to: https://support.microsoft.com/en-us/windows/map-a-network-drive-in-windows-29ce55d1-34e3-a7e2-4801-131475f9557d

Once you mount it, you should be able to see files in it via File Explorer and use the path it shows you in the Windows GUI.

I don't have a network drive to test with, atm. Let me know if it works for you.

**Comment by rwoll** [comment]
Awesome! Happy coding! 🎉
