### ISSUE TITLE
[BUG] Playwright dont find a config parameter

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15141]
Hello, i wanted to change the parameter "language" in every projects[] creating a config file, but when i launch the script it says the parameter doesnt exist
![fgd](https://user-images.githubusercontent.com/80640027/175902763-02ea0f57-1aac-4e76-b2a9-50ba47350f48.png)
![sfsf](https://user-images.githubusercontent.com/80640027/175902771-835453a8-a0f6-4c0e-94f3-9796bead7874.png)

**Comment by mxschmitt** [comment]
See here how to annotate it with types: https://playwright.dev/docs/test-parameterize#parameterized-projects

**Comment by NicoloLattanzio** [comment]
Is it possible to do the same with the fixtures?

**Comment by NicoloLattanzio** [comment]
Cause i have a test.use(viewport... etc) but it goes in contrast with the import { TestOptions } from './my-test';
