### ISSUE TITLE
[BUG] Playwright html reporter cannot be displayed in Azure Devops

### ISSUE THREAD

**Issue by MeravYa** [microsoft/playwright#15148]
While trying to publish html reporter to Azure devops, we got this error:
Parameter 'Cannot upload task attachment file, attachment file location is not specified or attachment file not exist on disk'

Is there a solution for this issue?

Thanks

**Comment by imartinflores** [comment]
By that message, I guess you are not specifying the correct file path or that file has not been generated. You might need to copy the file first with a copy task file, , then publish it with the results using the Publish Artifact Task.

**Comment by rwoll** [comment]
Can you please share a minimal Azure DevOps config that represents your setup and exhibits the problem, and I will debug off of that? Thanks!

**Comment by MeravYa** [comment]
Sure, following is the publish step in Azure DevOps:

steps:
- task: JakubRumpca.azure-pipelines-html-report.PublishHtmlReport.PublishHtmlReport@1
  displayName: 'Publish Html Report'
  inputs:
    reportDir: /TestResults/html

nothing special.. and again - I made sure that the files in the agent are present under /TestResults/html folder

Thanks

**Comment by rwoll** [comment]
Thanks for the additional info.

It looks like this your code snippet uses a third-party Azure DevOps extension (https://github.com/JakubRumpca/azure-pipeline-html-report). Since you see Playwright's report being output, this does not appear to be an issue with Playwright itself.

Please raise an issue with https://github.com/JakubRumpca/azure-pipeline-html-report to see if they can advise on debugging. Thanks!

Feel free to comment here with what you find!

**Comment by MeravYa** [comment]
Ok I will try to raise a question in their github.
Will update with my findings, thanks for you support :)

**Comment by imartinflores** [comment]
I would try it on my side but as Ross mentioned is a third party and I can't install it now. Are you sure you do not need to include the agent directory as part of that reportPath? $(build.SourcesDirectory) or use the workingDirectory? I'd give that a try.

**Comment by FrankNutreco** [comment]
Hello, I am experiencing the same problem that MeravYa is describing in her last step.
The html report is published and showing in my tab, 

![image](https://user-images.githubusercontent.com/107055245/207281726-731d9654-ad79-4c73-961c-edfac87f3ff7.png)

But when I click a test, it shows as empty.
![image](https://user-images.githubusercontent.com/107055245/207281835-1e47eb38-afb1-495d-8c50-05f6cbbfa8e6.png)

Is there any follow up on this?

**Comment by daniavander** [comment]
because it is only a static report index.html, so it can not show tests"s details
