### ISSUE TITLE
[Question] Is it possible to create steps level through the html reporter?

### ISSUE THREAD

**Issue by MeravYa** [microsoft/playwright#15147]
Hi,
Is it possible to create steps level through the built-in html reporter?

**Comment by rwoll** [comment]
This should work out of the box today:

<img width="1706" alt="Screen Shot 2022-06-27 at 10 14 36 AM" src="https://user-images.githubusercontent.com/11915034/175997950-cf3768f8-e2be-4d75-8f6f-2368a7930c63.png">

Please re-open if this does not cover your issue. Thanks!

**Comment by MeravYa** [comment]
Perfect! that's what I was looking for.
Thank you
