### ISSUE TITLE
[Question] Browser versions (which one is used)

### ISSUE THREAD

**Issue by sijakret** [microsoft/playwright#15140]
According to https://playwright.dev/docs/browsers#firefox

`Playwright's Firefox version matches the recent [Firefox Stable](https://www.mozilla.org/en-US/firefox/new/) build.`

Does this refer to the recent stable browser version at the time of the release of the respective playwright version?
Or does it mean the browser version drifts as new browsers get released?

In other words. If i use playwright 1.17.1, as new browsers get released I will keep getting the browser version that was current at the time of playwright 1.17.1.  Correct?

**Comment by rwoll** [comment]
/cc'ing @aslushnikov to help with the answer here. Thanks!

**Comment by aslushnikov** [comment]
> Does this refer to the recent stable browser version at the time of the release of the respective playwright version?

@sijakret Yes, this is precisely what it means

> In other words. If i use playwright 1.17.1, as new browsers get released I will keep getting the browser version that was current at the time of playwright 1.17.1. Correct?

That's correct!

**Comment by rwoll** [comment]
Closing per-above, but please re-open if you need additional information. Thanks @aslushnikov!
