### ISSUE TITLE
[BUG] Playwright output not showing Chinese characters

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15146]
While testing i noticed that the chinese characters arent showed in any screenshot nor when playwright it's working, what should i do?

**Comment by NicoloLattanzio** [comment]
Running it in docker, subsystem linux ubuntu, main OS Windows 11, i'm giving the script the choosen language, with an API, everything works but the chinese

**Comment by NicoloLattanzio** [comment]
I tried with the amazon.cn site, it has the same problem, but google.cn doesnt...

**Comment by rwoll** [comment]
When trying to repro, Amazon looks good, too: https://github.com/rwoll/playwright-repro-fonts-15146

See the linked repro for the exact Docker file and commands I'm using as well as example screenshots.

NB: I tested with the official Docker image. **Which Docker image are you using?** If you're not using the official image (but are still using an ubuntu-based image), you'll want to run `npx playwright install deps` in it to ensure all of Playwright's dependencies are present. (However, if it's not the official image, I might be of limited help!)

To debug further, please link to a self-contained repro like [this example](https://github.com/rwoll/playwright-repro-fonts-15146). Thanks!

**Comment by NicoloLattanzio** [comment]
Yeah it is not the official image, but still thanks for the help

**Comment by NicoloLattanzio** [comment]
The command isnt working, it says "Invalid installation targets"

**Comment by rwoll** [comment]
Oops…I typed the wrong command. Try:

```
$ npx playwright install-deps
```

**Comment by NicoloLattanzio** [comment]
How should i install the repro? In a docker

**Comment by rwoll** [comment]
The commands to clone, build the docker container, and run the container/tests in the README—should be run on your host machine. (You might have to modify on Windows.) It'll eventually run a container, but you should not run the commands in a container.
