### ISSUE TITLE
[BUG] `browser.close` doesn't close contexts properly

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#15163]
**Context:**
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 1.41 GB / 15.78 GB
## Binaries:
 - Node: 18.0.0 - C:\Program Files\nodejs\node.EXE
 - npm: 8.7.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright: ^1.23.0 => 1.23.0

**Code Snippet**

```javascript
const { chromium } = require('playwright')

;(async () => {
    const browser = await chromium.launch()
    const context = await browser.newContext({
        recordHar: { path: 'asdf.har' },
    })
    const page = await context.newPage()
    await page.goto('https://google.com/')
    await browser.close()
})()
```

**Describe the bug**

when closing the browser with `browser.close()` instead of `context.close()`, it does not close the context properly. in this case, no HAR file is created.

i would expect `browser.close()` to also call `context.close()` on all of its contexts before closing the browser

**Comment by rwoll** [comment]
Thanks for the report! This is expected behavior. You should close all contexts you create before calling `browser.close()`. Playwright doesn't want `browser.close()` to hang/not work, so it can't wait on too much and instead requires explicit `context.close()` to happen before it.

**Comment by KotlinIsland** [comment]
That's absolute insanity

**Comment by DetachHead** [comment]
@rwoll i think in that case it should at least output a warning when you call `browser.close` without closing all the contexts first

**Comment by rwoll** [comment]
I feel your pain! Is there somewhere in the docs you think seeing this information would be useful? The warning/log line is a good idea; I'll raise with the team, but there's not a precedent of outputting logs in Playwright (other than when using the DEBUG env/mode).

It is indeed slightly extra bookkeeping if you are using Playwright directly as a Library. However, we expect most users are using Playwright Test and are therefore not managing contexts directly. (The Test Runner handles their creation _and_ closing.)

**Comment by KotlinIsland** [comment]
What about users of playwright-<other language>, that has no support for playwright test at all?

**Comment by rwoll** [comment]
> It is indeed slightly extra bookkeeping if you are using Playwright directly as a Library. However, we expect most users are using Playwright Test and are therefore not managing contexts directly. (The Test Runner handles their creation and closing.)

Upon further thinking, I realize even using the `recordHar` feature as is in Playwright Test, requires a bit of manual context creation. We'll think about how to avoid that.

**Comment by rwoll** [comment]
> It is indeed slightly extra bookkeeping if you are using Playwright directly as a Library. However, we expect most users are using Playwright Test and are therefore not managing contexts directly. (The Test Runner handles their creation and closing.)

We're releasing a patch version of 1.23 that exposes an `update` option on `routeFromHar` which removes the need of manually using `recordHar` (and, by extension, manual contexts).

> What about users of playwright-<other language>, that has no support for Playwright Test at all?

They each have their respective official test plugins or recommendations that make them behave similarly to Playwright Test (i.e. providing common fixtures that auto-close and cleanup):

-  Python [pytest plugin](https://playwright.dev/python/docs/test-runners) 
- Java's [example](https://playwright.dev/java/docs/test-runners) shows an afterEach hook that similarly closes the context
- .NET there are [base classes](https://playwright.dev/dotnet/docs/test-runners#base-nunit-classes-for-playwright) for each of the test types that do similar closing

Playwright is centered around end-to-end testing, so if you're consuming Playwright as a library, it expects the integration do more explicit work (like explicitly closing a context).

`browser.close()` is like pulling the power cord on your browser or force quitting, so before you do that, you should close the `contexts`.

Is there somewhere in the docs that this information would have been helpful before you hit this issue? At this time, we can't change the behavior/relationship between browser.close and context.close, but we can document it better!

**Comment by KotlinIsland** [comment]
You could add a warning at the start of the documentation warning "Do not use!, only use if you are developing a high level testing framework"

**Comment by DetachHead** [comment]
> Is there somewhere in the docs that this information would have been helpful before you hit this issue? At this time, we can't change the behavior/relationship between browser.close and context.close, but we can document it better!

it would be useful if it was mentioned in the documentation for [`browser.close`](https://playwright.dev/docs/api/class-browser#browser-close). the current documentation seems to imply that it *does* correctly close the contexts:

> In case this browser is connected to, clears all created contexts belonging to this browser and disconnects from the browser server.

**Comment by rwoll** [comment]
Thanks @DetachHead! I've opened https://github.com/microsoft/playwright/pull/15255 with some doc changes.

**Comment by rwoll** [comment]
Landed—including updated caveat and example code. Thanks for your patience and helping us improve here!

(It'll be a bit until the docs site rolls over with the changes.)
