### ISSUE TITLE
[BUG] har file documentation link in release is broken

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#15164]
https://github.com/microsoft/playwright/releases/tag/v1.23.0

![image](https://user-images.githubusercontent.com/57028336/176069731-cee26172-0285-4e68-a800-74b41384d840.png)

https://playwright.dev/network#record-and-replay-requests

![image](https://user-images.githubusercontent.com/57028336/176069769-60a52347-e302-4246-be23-a7105924faa1.png)

**Comment by rwoll** [comment]
Oops! Thanks for bringing to our attention! Should now be fixed in the GH release notes (https://github.com/microsoft/playwright/releases/tag/v1.23.0) so it should be good now! 😄 

Thanks again!
