### ISSUE TITLE
[Question] - Component Testing with JS

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#15169]
Hey gusy, was trying component with .jsx files, when running the test, I am getting this now:
Could not resolve entry module (playwright/index.html).
[..................] \ : timing npm:load Completed in 65ms
```
Error: Could not resolve entry module (playwright/index.html).

   at node_modules\rollup\dist\shared\rollup.js:198

function error(base) {
   if (!(base instanceof Error))
       base = Object.assign(new Error(base.message), base);
                             ^
     throw base;
 }
  function augmentCodeLocation(props, pos, source, id) {
```
  
  Is there any log generated or any way to debug this to know why is it not finding that file ? I can the see the playwright/index.html as it was before in the project. I think something has changed and I am not seeing it, but would like to know how to debug it ?
@rwoll 
  Thanks!

**Comment by imartinflores** [comment]
Seems like when using a config in the package.json, --config=/qa/configs/playwright.config.js  , it looks for the playwright/index.html to be in the same folder, so I moved to /qa/configs, and it works..

**Comment by imartinflores** [comment]
Another issue I noticed is that we have a mix of old and new modules in the project as we are migrating, some of them still use:
const data = require('myFile'). When I render a component that uses require() it fails 
```
Uncaught ReferenceError: require is not defined
    at index.js:1:14
```
Is there something that can be added to fix this or should it be fixed in the project to use imports ?
Thanks!

**Comment by pavelfeldman** [comment]
> Uncaught ReferenceError: require is not defined

There is no support for `require` in ESM modules, so there aren't any Playwright settings that can fix that.

**Comment by imartinflores** [comment]
Thanks @pavelfeldman !
