### ISSUE TITLE
[Question] How to avoid mixing stdout from playwright and my own console.log

### ISSUE THREAD

**Issue by lancelodliu** [microsoft/playwright#15168]
I'm using 1.22.0 NodeJS version and is experiencing a mixture of stdout/stderr between palywright and my own console.log. You can see it in the screenshot. The red "F" and green dot are the stdout/stderr from playwright.
![image](https://user-images.githubusercontent.com/19603852/176138736-b080b689-37ab-403b-972b-8b5d1b7f85b2.png)
How can I remove this output?
Thank you.

**Comment by lancelodliu** [comment]
Thank you @rwoll . The output I found seems to be the dot reporter. Is it possible to disable it?

**Comment by rwoll** [comment]
> The output I found seems to be the dot reporter. Is it possible to disable it?

See https://playwright.dev/docs/test-reporters#using-reporters for how to select reporters either on the command line or in the config.

You'll need at least one reporter, so the custom `DevNullReporter` above can be used in place of any of the defaults.

> And why these reporters' output mixes with the console.log in my test code?

This is the default behavior. The built in reporters assume console.log is only used for debugging, so it mixes it in with their own output. 

How do you use the console.log statements? Do you need to see them real-time in the terminal, or do you just want a log per-test after the fact in a report?

**Comment by rwoll** [comment]
Here's example output:

```
$ npx playwright test --reporter=./devNullReporter.ts
foo

bar

bar

foo

foo

bar
```

**Comment by lancelodliu** [comment]
> > The output I found seems to be the dot reporter. Is it possible to disable it?
> 
> See https://playwright.dev/docs/test-reporters#using-reporters for how to select reporters either on the command line or in the config.
> 
> You'll need at least one reporter, so the custom `DevNullReporter` above can be used in place of any of the defaults.
> 
> > And why these reporters' output mixes with the console.log in my test code?
> 
> This is the default behavior. The built in reporters assume console.log is only used for debugging, so it mixes it in with their own output.
> 
> How do you use the console.log statements? Do you need to see them real-time in the terminal, or do you just want a log per-test after the fact in a report?

I use `console.log` in a customized Page fixture setup to provide detailed info about current running test. What I expect from PW is that the stdouts won't get mixed.

**Comment by rwoll** [comment]
> What I expect from PW is that the stdouts won't get mixed.

What is the ideal output in your scenario? Does DevNullReporter cover your case? It doesn't log any information about which test are running itself.

If you use the HTML Reporter, the stdout from PW is seperated per-test and does not include the test runner info. However, for the built in reporters running on the command line, the default only has stdout/stderr to communicate to the user at runtime, so it mixes its output with the anything coming out of the tests in the terminal only; while it's mixed on the CLI, if you view the HTML Report (JUnit, JSON, etc.) it's separated out per-test and not interleaved.
