### ISSUE TITLE
How to Review Test Emails for use cases such as authorization and confirmation with playwright

### ISSUE THREAD

**Issue by cristinataplytics** [microsoft/playwright#15177]
Hi,

How can we write tests in playwright as authorization and confirmation email.?

I am looking for something similar to this:
https://help.rainforestqa.com/docs/how-to-review-test-emails

**Comment by rwoll** [comment]
Does this properly summarize what you're hoping to do with Playwright? (I looked at the link, but want to make sure I understand.)

Your app sends emails (e.g. as part of the user login flow), as well as confirmations after certain actions in your Web App (e.g. a reciept after you make a purchase on the website). You'd like Playwright to receive these emails, display them, and test.

**Is this along the lines of what you're looking for?** Unfortunately, Playwright does not have such a feature out of the box. However, you could achieve this by:

1. signing up for a email address(es) with your choice of online email service
2. use it while testing your web app (many services, if you have, `foo@example.com`, allow you to send to `foo+some-random-label@example.com` and will still get to `foo@example.com`)
3. Logging into the online UI of the the email you got in (1) in Playwright like any other site under test

Would this work for you?

**Comment by weyert** [comment]
You can use https://docs.mailslurp.com/js/#quick-start for this.

**Comment by rwoll** [comment]
Closing per-above and the other suggestions in the Slack thread you started: https://playwright.slack.com/archives/CSUHZPVLM/p1656428612216749
