### ISSUE TITLE
[BUG] [playwright-test] Fixture can't be wrapped by quotes

### ISSUE THREAD

**Issue by csr632** [microsoft/playwright#15189]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Ubuntu
- Node.js version: 16.15.1
- Browser: All

**Code Snippet**
```js
const test2 = test.extend({
  "as-df": async ({}, test) => await test(123),
});
test2("should use asdf", ({ "as-df": asdf }) => {
  expect(asdf).toBe(123);
});
```

Get error: `Test has unknown parameter ""as-df""`

**Describe the bug**

Params in the test function can not be wrapped by quotes.

**Comment by rwoll** [comment]
Thanks for the report! This is working as intended. The code that "parses" fixture names is limited, so you'll need to avoid using key names that require using fixtures. I'll add a note in the docs with this information for others; sorry you found out the hard way!

Unless a full parser is brought in to do the job, the proposed change https://github.com/microsoft/playwright/pull/15201 is limited in its effectiveness. To keep things simple, Playwright Test will keep the restriction on naming conventions for fixtures.

**Comment by rwoll** [comment]
Documentation updated here: https://github.com/microsoft/playwright/pull/15203
