### ISSUE TITLE
[Feature] Add check for `stable`: `locator.waitFor({ state: 'stable' })`

### ISSUE THREAD

**Issue by pavelicii** [microsoft/playwright#15195]
Currently, with `locator.waitFor(...)`, you can only wait for 4 states:
`state?: "attached"|"detached"|"visible"|"hidden"`

It would be great to have an opportunity to also wait for [Stable](https://playwright.dev/docs/actionability#stable) state, which checks if element stopped animating.

My use case is:
I want to get `locator.boundingBox()` after its animation is finished (it has a small transition from top to bottom on appearance). Since `boundingBox` action doesn't have any [auto-waiting actionability checks](https://playwright.dev/docs/actionability), I get coordinates of the `locator` before it is in its final position on the page (which would be after its animation is finished).

As a workaround I'm using `locator.scrollIntoViewIfNeeded()`, which waits for `stable`, but I don't think it's very concise.

Is this a valid feature request, or is there a good reason it is not implemented as of now?

**Comment by ltsuda** [comment]
Although my usage was only for study purposes, I found a similar use case while test saucedemo.com. There's a side menu when logged in, the menu has an animation and testing that I can close it by clicking at the X button fails if I don't wait it to be stable.

In this case, I had to use ElementHandles so I could use `waitForElementState` (https://playwright.dev/docs/api/class-elementhandle#element-handle-wait-for-element-state).

Here's my study repo with the workaround:
https://github.com/ltsuda/playwright-study/blob/main/tests/cart.spec.js#L92

**Comment by pavelicii** [comment]
@ltsuda thank toy for another workaround. My issue with it is that there is a disclaimer in docs saying `ElementHandle` use is discouraged:
![image](https://user-images.githubusercontent.com/26544034/176405366-499465a6-6c2d-415b-9787-69b615163d10.png)

**Comment by ltsuda** [comment]
Yes, that's not the best option. Adding more examples/workaround I think could help with the feature request :)

**Comment by aslushnikov** [comment]
@pavelicii There's also a [`trial`](https://playwright.dev/docs/api/class-locator#locator-click-option-trial) option in `locator.click()` which is a decent workaround!

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by Tallyb** [comment]
Wait for locator state to be stable is extremely useful, especially when there are animation. would be great to have it on locator states.

**Comment by Limoer96** [comment]
set `force`option in `location.click()` worked for me. see https://playwright.dev/docs/actionability#forcing-actions

**Comment by Bjoren** [comment]
Wanted to add that I came here after discovering that this wasn't possible and I wish this would be opened for consideration again.

Consider, for example, that you have some animated element that can display different content depending on what the user is doing. Now, if you have a generalized function to do stuff to this element, you'd want to wait for the animation to complete before continuing with the test, or you might have failing assertions, or end up doing a lot of unnecessary state checks in the functions following it instead.

There are workarounds suggested above, true, but they're not very clean code in my opinion and leaves you scratching your head at first glance. I like to avoid that as much as possible, and I think that `.waitFor({ state: 'stable' })` would be elegant and easy to understand.

**Comment by pavelicii** [comment]
@aslushnikov @pavelfeldman I think we can see there is a lot of interest in this feature. Given it has `collecting-feedback`, what needs to be done to reopen this issue? Or are there strong reasons to not implement this?

**Comment by Sharma-IT** [comment]
Here's a solution if anyone is interested: https://github.com/Sharma-IT/playwright-stable-locator

**Comment by midnightGambler** [comment]
run up the same problem, decided to use `trial` option with `hover` method (i believe it works with other actions too)

https://playwright.dev/docs/api/class-locator#locator-hover-option-trial

`locator.hover({ trial: true })` - waits for [actionability](https://playwright.dev/docs/actionability) checks without performing the action

**Comment by caribou-code** [comment]
@pavelfeldman I'm a little confused, why did you close this ticket as completed? There are workarounds mentioned, but they're not unintuitive and/or not recommended in the docs. `waitFor` supports other possible states, so it seems sensible that it would support `stable` too.

**Comment by GeorgiyIakunenko** [comment]
Still a workaround but I found this function https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed which is based on https://playwright.dev/docs/actionability table checks only for stability.

**Comment by dword-design** [comment]
I put the `expect.toBeStable()` assertion into an npm package [playwright-expect-stable](https://www.npmjs.com/package/playwright-expect-stable) to abstract away the implementation (`locator.hover({ trial: true })`). Worked for me for a [Buefy modal](https://buefy.org/documentation/modal).

```ts
import { test } from '@playwright/test';
import { expect } from 'playwright-expect-snapshot';

test('works', ({ page }) => {
  const element = page.locator('.some-animated-element');
  expect(element).toBeStable();
});
```
