### ISSUE TITLE
[Structured steps in report based on context]

### ISSUE THREAD

**Issue by lavcraft** [microsoft/playwright#15196]
Hello. I found unusual scenario, but is very complex and can be interests for others

My scenario test:
```typescript
 //given
        async function userIndependentScenario(user: TestUser) {
            await user.toJoin(event.id);
            await user.doSth();
        }

        log('Start user scenarios independently')
        await Promise.all(users.map((user) => userIndependentScenario(user)))
```

Inside Page Object `user` i mark code with next block:
```typescript 
test.step(`${this.userName} do sth`, ...)
```

After this, i see problem in report view, because all steps expect sequential execution order. But actually (in my case) it's not

For example - init 4 users and my report contained next non human readable structure:

```
> User 0 join
  > User 1 join
    > User 2 join
      > User 3 join
        > User 0 do sth
          .....
```

Need a feature like a zone, for group async code or prefix all operations without step with specfic tag (like user name, for describe in all report operations (like `USER 0 page.goto(....)`)

**Comment by rwoll** [comment]
Thanks for the report! Agreed this is a bit confusing as presented in the report; however, unfortunately, there's no current support for concurrent steps in the reporter(s).

Here's the code that produces the final screenshot of the HTML Reporter:

```ts
import { test } from '@playwright/test';

const doAConcurrent = async (i) => {
  await test.step(`step ${i}`, async () => {
    await new Promise(r => setTimeout(r, Math.floor(Math.random() * 10)));
  })
}

test('example', async ({ page }) => {
  await Promise.all([doAConcurrent(1), doAConcurrent(2), doAConcurrent(3), doAConcurrent(4)]);
});
```

<img width="1031" alt="Screen Shot 2022-06-28 at 4 29 57 PM" src="https://user-images.githubusercontent.com/11915034/176321095-32d15e1c-1fe5-46d3-940f-4fc4978a1f23.png">

**Comment by seanlaff** [comment]
I ran into this same problem. My use-case was to record some performance timings of widgets on my page (that all load on page-load) by using async `test.step()` blocks like in the sample below. I had hoped to see each of them as their own `step` element in the json reporter output, but they are nested strange as rwoll showed. 

```ts
test("example", async ({ page }) => {
  await page.goto("/somepage");

  Promise.all([
    test.step("load widget 1", async () => {
      await expect(page.getByAltText("figure 1")).toBeVisible();
    }),
    test.step("load widget 2", async () => {
      await expect(page.getByAltText("figure 2")).toBeVisible();
    }),
    test.step("load widget 3", async () => {
      await expect(page.getByAltText("figure 3")).toBeVisible();
    }),
  ]);

  // remaining tests for the page...
});
```

As far as alternatives go- maybe custom reporters would give me more control https://playwright.dev/docs/api/class-reporter#reporter-on-step-begin I'll look into them next. Worse case I could add loggers to print perf timings.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
