### ISSUE TITLE
[Question] Can I force the HTML report to be generated first?

### ISSUE THREAD

**Issue by hughbillings** [microsoft/playwright#15215]
I have a custom reporter and using the HTML reporter for my test automation suite. Using axios to transfer data to the necessary platforms it seems as if the HTML report is generated at a point where I can't capture it asynchronously. I'm trying to push the instance.post to a test case management system and push the HTML file to Slack. But it wont capture the latest index file.

`async onEnd(result: FullResult) {
    console.log(`✅ Finished the run: ${result.status}`);
    const data = {
      projectId: ,
      testRunName: `[${
        process.env.STAGING === "1" ? "STAGING" : "PRODUCTION"
      }] `,
      description: "Triggered by test automation suite",
      includeAllCases: true,
      suites: [...new Set(results.map((result) => result?.suite_id))],
      results: results,
    };

    try {
      await instance.post("/add-automated-test-execution", data);

      // /**
      //  *  Slack Integration Start
      //  */

      const formData = new FormData();
      
     

      formData.append("file", fs.createReadStream(
'./playwright-report/index.html');
      formData.append("channels", ``);
      formData.append("title", ``);
      formData.append(
        "initial_comment",
        `
        # OF TEST CASES: ${data.results.length} \n
        PASSED 🟢: ${
          data.results.filter((item) => item.status === "passed").length
        } \n
        FAILED 🔴: ${
          data.results.filter((item) => item.status === "failed").length
        } \n
        SKIPPED 🔵: ${
          data.results.filter((item) => item.status === "skipped").length
        } \n

        `
      );

      const slack = await axios.post(
        "",
        formData,
        {
          headers: {
            "Content-Type": "multipart/form-data",
            Authorization: `Bearer ${} `,
          },
          transformRequest: (formData) => formData,
        }
      );

      console.log(slack);
    } catch (err) {
      console.log(err);
    }

    console.log("🚀 Test Results have been posted");
  }
}
`

**Comment by rwoll** [comment]
Instead of uploading the HTML Reporter's output from another Custom Reporter, please run a script _after_ the test run is fully complete and Playwright has exited. Currently, reporters interacting with other reporters is not defined behavior[^1].

Your run would look something like:

```
$ npm test
$ npm run upload-to-slack
```

(Depending on your CI system, if one is in use, you'll want to put the  `npm run upload-to-slack` command in a post-step and ensure it runs even if `npm test` exits with code of 1 as would be the case if a test failed.)

Does this work for you?

[^1]: You can try re-ordering the reporters in on the CLI/config so HTML Report is before your Custom Reporter, but if this is works, it is by coincidence.

**Comment by hughbillings** [comment]
@rwoll is it possible to get the summary data from the html reporter to be reflected in the form data code? The summary data would be the Number in the all tab, passed tab, failed, flaky and skipped? 

`# OF TEST CASES: ${data.results.length} \n
PASSED 🟢: ${
data.results.filter((item) => item.status === "passed").length
} \n
FAILED 🔴: ${
data.results.filter((item) => item.status === "failed").length
} \n
SKIPPED 🔵: ${
data.results.filter((item) => item.status === "skipped").length
} \n`

My current implementation gets the data from my Custom reporter. If there is a way, you will have saved my day!

**Comment by hughbillings** [comment]
@rwoll THE FOOTNOTE WORKED! 

> but if this is works, it is by coincidence.

A very great coincidence! Thank you. Have a good day
