### ISSUE TITLE
[BUG] Cant screenshot an element

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15214]
Hello, as u can see in the image, the first screenshot works properly, but in the others it gives this error : "
elementHandle.screenshot: Element is not attached to the DOM
    =========================== logs ===========================
      waiting for element to be visible and stable

But the element is the same, and doesnt change.

![Immagine 2022-06-29 103613](https://user-images.githubusercontent.com/80640027/176391727-c6637264-f4ab-4035-8dc1-f57c3906b7f1.png)

**Comment by rwoll** [comment]
Thanks for the report! Can you provide a URL or minimal code snippet of the page that shows the issue? Unfortunately, looking at the screenshot above, I'm unable to follow.

You can also record and upload a trace to debug: https://playwright.dev/docs/trace-viewer
