### ISSUE TITLE
[REGRESSION]: SyntaxError: Unexpected token '<' in monorepo project on 1.23.0 version

### ISSUE THREAD

**Issue by klepik1990** [microsoft/playwright#15212]
Hi guys! Can't run tests on new playwright version(1.23.0). We use monorepo project, so tests are in the same project with front-end code. It worked fine on 1.22.*
When I run my tests on the new version I get an error
<img width="1228" alt="image" src="https://user-images.githubusercontent.com/49123512/176378695-099a8655-bf4c-4256-bcd7-e34970a0d496.png">

There are not component tests and to be honest I don't use these files due testing
**Context:**
- GOOD Playwright Version: 1.22.*
- BAD Playwright Version: 1.23.0
- Operating System: Mac
- typescript: 4.1.3

Frontend devs use "react": "17.0.2",

**Code Snippet**

A piece of the frontend code with the mentioned error.
<img width="694" alt="image" src="https://user-images.githubusercontent.com/49123512/176378972-a66b8efa-8bc1-4e82-a133-272562e1eb7c.png">

**Comment by aslushnikov** [comment]
@klepik1990 Can you please show us your config? Could it be that your test pattern includes `component.tsx` as a test file?

**Comment by klepik1990** [comment]
@aslushnikov 
```
import type { PlaywrightTestConfig } from '@playwright/test';
import getUrl from './src/testData/environments';
// import { devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
    timeout: 100 * 1000,
    expect: {
        timeout: 10000,
    },
    testMatch: '**/tests/**/*.spec.ts',
    forbidOnly: Boolean(process.env.CI),
    retries: process.env.CI ? 1 : 0,
    workers: 4,
    reporter: [
        ['list'],
        ['allure-playwright', { outputFolder: 'allure-results' }],
        [
            'playwright-qase-reporter',
            {
                apiToken: '**',
                projectCode: '**',
                runComplete: true,
                basePath: 'https://api.qase.io/v1',
                logging: true,
                uploadAttachments: true,
            },
        ],
        ['html'],
    ],

    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        baseURL: getUrl(),
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
        headless: true,
        video: 'off',
        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: 0,
    },
    projects: [
        {
            name: 'chromium',
            use: {
                browserName: 'chromium',
                viewport: {
                    width: 1792,
                    height: 912,
                },
            },
        },
        {
            name: 'webkit',
            use: {
                browserName: 'webkit',
                viewport: {
                    width: 1792,
                    height: 912,
                },
            },
            retries: 1,
        },
    ],
};

export default config;
```

**Comment by klepik1990** [comment]
there are only *.ts files associated with `./src/testData/environments`

**Comment by aslushnikov** [comment]
Does this file import other files though? My hypothesis is that eventually somewhere in this chain there's a `component.tsx` import

**Comment by klepik1990** [comment]
yes, this file imports another file which imports another file, but all of them has *.ts extension

**Comment by aslushnikov** [comment]
@klepik1990 any chance you can provide with a repro that we can run locally to debug this?

**Comment by klepik1990** [comment]
@aslushnikov I'm not sure, there is a monorepo and i don't know how to cut needed pieces of the cod

**Comment by yury-s** [comment]
Closing as part of the triage process. We need a reproducible example to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by klepik1990** [comment]
@aslushnikov You were right. There was an imported method in my test from the module witch includes component.tsx, problem temprorary solved by changing import path. Thanks for your time
