### ISSUE TITLE
[Feature] Tracking element attribute changes

### ISSUE THREAD

**Issue by KonstantinTsvetkov** [microsoft/playwright#15222]
### Use case
There is a Vue2 app with Vuetify where images are being streamed to a dashboard. Images are being displayed in the same element. So, the only thing that is changing is xlink:href (image is provided as base64).
So, the element itself is not detached from DOM. The only thing that is changing is the attribute: xlink:href. UPD: And it changes randomly. There is no way of knowing what value will come next.

### Limitations
It is not possible to process this with not(contains()) as contains() fails to work with this attribute due to an error:
> contains unresolvable namespaces 

P.S. It might be improved in the future as using xlink:href is no longer recommended. But if changing the attribute is not possible, it is quite hard to deal with this.

### Workaround
It seems that it might be possible to use custom JavaScript and Mutation Observer:
https://thewebdev.info/2021/03/03/how-to-watch-for-dom-changes-with-javascript/
https://playwright.dev/python/docs/api/class-page#page-add-init-script

### Feature
It would be great to have a native Playwright API that would allow waiting for an element update (i.e. attribute change).

**Comment by rwoll** [comment]
> It would be great to have a native Playwright API that would allow waiting for an element update (i.e. attribute change).

Are you talking about Playwright as a Library, or as a Test Runner?

If the latter, it can do this via Web-First Assertions. For example, see https://playwright.dev/docs/test-assertions#locator-assertions-to-have-attribute

**Comment by KonstantinTsvetkov** [comment]
> > It would be great to have a native Playwright API that would allow waiting for an element update (i.e. attribute change).
> 
> Are you talking about Playwright as a Library, or as a Test Runner?
> 
> If the latter, it can do this via Web-First Assertions. For example, see https://playwright.dev/docs/test-assertions#locator-assertions-to-have-attribute

Hi #rwoll. I meant the latter. However, I have no way of knowing what attribute will be. Thus, I cannot use this assertion. I just need to wait until the attribute changes and then perform other actions. Consider the attribute value random.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
