### ISSUE TITLE
[Question] Page resized to 1280,720 after second GotoAsync() call against browserless.io container

### ISSUE THREAD

**Issue by MattHorrocksNetwealth** [microsoft/playwright#15223]
Hi!

I'm running this against a self hosted browserless.io container.

When I call the second `GotoAsync()` command, the page is resized to 1280,720.

If I run the same test locally, the page is not resized on the second `GotoAsync()` command.

Trace attached here [trace.zip](https://github.com/microsoft/playwright/files/9009974/trace.zip).

Browserless are aware of this, but I thought I'd ask here in case anyone has any thoughts on what might be causing it, or if you feel it might be a Playwright bug, after all.

```
class Program
{
    public static async Task Main()
    {
        var playwright = await Playwright.CreateAsync();
        var browser = await playwright.Chromium.ConnectAsync("ws://testurl:3000");
        //var browser = await playwright.Chromium.LaunchAsync();

        var context = await browser.NewContextAsync();
        await context.Tracing.StartAsync(new TracingStartOptions
        {
            Screenshots = true,
            Snapshots = true
        });

        var page = await context.NewPageAsync();
        await page.SetViewportSizeAsync(1920, 1080);
        await page.GotoAsync("https://playwright.dev/dotnet");
        await page.Locator("//a[text()='Docs']").ClickAsync();
        await page.GotoAsync("https://slack.com/intl/en-gb/");
        await context.Tracing.StopAsync(new TracingStopOptions

        {
            Path = "c:\\temp\\trace.zip"
        });

        await page.Locator("(//a[text()='Solutions'])[1]").ClickAsync();
    }
}
```

**Comment by rwoll** [comment]
Thanks for the report! Since you've tested and said it works locally, but not with Browserless and they are already investigating, let's hold off until you finish your investigation.  I'll close this for now, but if after Browserless gets back to you, feel free to re-open.

Thanks!

Perhaps related: https://github.com/microsoft/playwright/issues/15131
