### ISSUE TITLE
[Feature] Amount of  `fixme` vs `skip` in report

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#15239]
Tests marked with `.skip` and `.fixme` 
- both are skipped
- both are counted at the end as `skipped` 
- hides the number of tests to be fixed.

Having a big permutation of tests ( this mostly affects screenshot testing ) we skip a lot of them ( like some combinations don't make sense to test), but skipped tests are shown as `skipped`. 

Could be nice to not include the `.skip`-ed tests at the end, but only show tests with `.fixme` which are failing/flaky.
Showing both in separate lines also could be an option.

![Screenshot 2022-06-29 at 19 29 54](https://user-images.githubusercontent.com/7899764/176488690-9ec8364c-26f4-476f-b541-18a6f556b45e.png)

As a workaround we are doing this way, but meh
```js
    someStorybook.forEach((story) => {
        test(story.name, async ({}, testInfo) => {
            if (testInfo.project.name.startsWith("Desktop-") && story.name.endsWith("foobar Story")) {
                return
            }
            await page.goto(storybookLocalhost + story.url)
            await compareScreenshots(page, story.name)
        })
    })
```

**Comment by rwoll** [comment]
Thanks for the report! I've included a workaround below that I think gives the info you need. (We'll have to think more deeply about changing the built-in reporter as some folks may already depend on the format of it's output in, for example, CI/CD reporting. But hopefully this helps in the interim!)

**Let me know if the below unblocks you!**

With the workaround, the output looks like:

```
$ npx playwright test --reporter=line,./DetailedSkipInfoReporter.ts

Running 6 tests using 6 workers

  6 skipped

  Skipped Breakdown: 3 skipped, 3 fixme
```

To get this output (the additional line with _Skipped Breakdown_), you can do the following:

1. Save/check-in the [Custom Reporter](https://playwright.dev/docs/test-reporters#custom-reporters) I've included at the end of this comment called `DetailedSkipInfoReporter.ts`.
2. Add the custom reporter at the end of the reporters array in your playwright config (or on the command line like `npx playwright test --reporter=line,./DetailedSkipInfoReporter.ts`)

```ts
// @filename: DetailedSkipInfoReporter.ts
import type { FullConfig, FullResult, Reporter, Suite } from '@playwright/test/reporter';

class DetailedSkipInfoReporter implements Reporter {
  private _suite!: Suite;

  onBegin(config: FullConfig, suite: Suite) {
    this._suite = suite;
  }

  onEnd(result: FullResult) {
    let fixme = 0;
    let skip = 0;
    for (const test of this._suite.allTests()) {
      if (test.expectedStatus === 'skipped') {
        if (test.annotations.some(a => a.type === 'fixme')) {
          fixme++;
        } else {
          skip++;
        }
      }
    }

    console.log(`\n  Skipped Breakdown: ${skip} skipped, ${fixme} fixme`);
  }
}

export default DetailedSkipInfoReporter;
```

As an aside: test.fixme is effectively the same as test.skip, except for the annotation type. Some reporters, like the HTML Reporter, will show you the fixme vs. skip annotation(s) when you click on a test to view it.

**Comment by rwoll** [comment]
Oops! I had tried with a different style:


```ts
test('foo', () => test.skip());
test('another', () => test.fixme());
```

I'll add some tests in our repo around the annotations to see what's going on.

**Comment by rwoll** [comment]
@dimkin-eu The PR was landed. Tomorrow, give `@next` a try and the annotations should be there. See the tests in the PR for how the annotations across multiple levels are applied. Depending on where your annotations are, you may have to update the code snippet I sent along.

Thanks!

**Comment by dimkin-eu** [comment]
@rwoll, works like a charm :)
There is only 1 issue - if one `fixme`s whole spec with n tests it adds 1 to skipped, not n

**Comment by rwoll** [comment]
@dimkin-eu Can you elaborate with a code snippet? I'm not sure I follow. Depending on where the skip/fixme is used certain code is not run. Some examples in the tests of the various cases: https://github.com/microsoft/playwright/pull/15277/files
