### ISSUE TITLE
[BUG] Waiting for visible element to become visible

### ISSUE THREAD

**Issue by bradydowling** [microsoft/playwright#15236]
**Context:**
- Playwright Version: 1.21.1
- Operating System: macOS 11.6.7
- Node.js version: 16.13.2
- Browser: Chromium
- Extra:

## System:
 - OS: macOS 11.6.7
 - Memory: 520.14 MB / 16.00 GB
## Binaries:
 - Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
 - Yarn: 3.2.0 - ~/.yarn/bin/yarn
 - npm: 8.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

[Here is the trace for the failed run](https://github.com/microsoft/playwright/files/9012126/trace.zip)

**Code Snippet**

```typescript
    await page.click(
        `[role="button"]:has-text("Coaching with Random Laster")`,
    );
```

**Describe the bug**
The selector finds an element that is visible. In the PWDEBUG UI I can test this and verify it but the CLI itself fails and says the element is not visible.

**Comment by bradydowling** [comment]
This does not appear to be caused by the issue found here https://github.com/microsoft/playwright/issues/15034

**Comment by aslushnikov** [comment]
@bradydowling this does look like a bug to me. Could you please come up with a repro that we can run locally to investigate this?

**Comment by aslushnikov** [comment]
Unfortunately this is not actionable for us without a repro. Since my triaging shift is over, I'll have to close this.

However, please do not hesitate to file a new issue with a repro that we can run locally & debug!
