### ISSUE TITLE
[BUG] WebKit screenshots are 1 px off after recent roll

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#15240]
There is an upstream regression tracked in https://bugs.webkit.org/show_bug.cgi?id=242079 which was introduced by https://github.com/WebKit/WebKit/commit/e7abdadb1b69209d90e51b46caab32d4cc6bb093

**Comment by rwoll** [comment]
We re-baselined to keep rolling, but we plan to address this prior to releasing 1.24 to ensure old screenshots still work unless there is justification upstream for the off-by-a-pixel error.

**Comment by yury-s** [comment]
Fixed by https://github.com/microsoft/playwright/pull/15384
