### ISSUE TITLE
Playwright results via Playwright Reporter exported out to Microsoft Teams, or Outlook to review the smoke test results.[Feature]

### ISSUE THREAD

**Issue by AnythingButNormal** [microsoft/playwright#15258]
Let us know what functionality you'd like to see in Playwright and what your use case is:

I work for a fortune 100 company. We just implemented Playwright after having no automation framework.  Everything is awesome thus far, you all did an awesome job and my app dev team thanks you immensely.  But if you could possibly please help us (?). we are looking for a way to take the results of the nightly smoke test results from Playwright, via Playwright Reporter and we need to be able to export those results back to our Enterprise MS Outlook, or more preferably, Microsoft Teams (group message if possible) to review what passed/failed before going into the daily stand up meeting.  And since smoke tests are ubiquitous in our industry, to answer your aforementioned question, I am confident this feature would be well received amongst a plethora of testers and developers.  Before submitting this feature request, I did research thoroughly through the playwright.dev document on export types, like TestNG, Cucumber, JUnit, etc., but it would be super awesome to be able to have Playwright Reporter integration with MS Teams, Outlook, or even Power Automate Desktop? :)

I searched numerous YouTube videos, but I only saw that XRay (test management plugin tool for JIRA) works well with Playwright, which is really sweet and would love to see both companies continue to build that relationship and technology.

Do you think others might benefit from this as well?: 
Playwright gaining rapid adoption amongst QA Automation Engineers, it would be extremely helpful to expand its functionality when implementing with Microsoft Power Desktop, or any exporting results of Playwright reporter via MS Teams, or Outlook, as mentioned above.

Thank you all so much; many blessings to you all for making our lives so much easier!! <3

**Comment by rwoll** [comment]
Thanks for detailed report! Glad to hear you are enjoying your time with Playwright so far!

This is not yet a built-in feature. 😢 

As a workaround, you can run a script after your test run that sends and email or message with a report, and/or implement a [Custom Reporter](https://playwright.dev/docs/test-reporters#custom-reporters) that can format your results whichever way works for your team and send them off!

**Comment by PavanMudigondaTR** [comment]
> Let us know what functionality you'd like to see in Playwright and what your use case is:
> 
> I work for a fortune 100 company. We just implemented Playwright after having no automation framework. Everything is awesome thus far, you all did an awesome job and my app dev team thanks you immensely. But if you could possibly please help us (?). we are looking for a way to take the results of the nightly smoke test results from Playwright, via Playwright Reporter and we need to be able to export those results back to our Enterprise MS Outlook, or more preferably, Microsoft Teams (group message if possible) to review what passed/failed before going into the daily stand up meeting. And since smoke tests are ubiquitous in our industry, to answer your aforementioned question, I am confident this feature would be well received amongst a plethora of testers and developers. Before submitting this feature request, I did research thoroughly through the playwright.dev document on export types, like TestNG, Cucumber, JUnit, etc., but it would be super awesome to be able to have Playwright Reporter integration with MS Teams, Outlook, or even Power Automate Desktop? :)
> 
> I searched numerous YouTube videos, but I only saw that XRay (test management plugin tool for JIRA) works well with Playwright, which is really sweet and would love to see both companies continue to build that relationship and technology.
> 
> Do you think others might benefit from this as well?: Playwright gaining rapid adoption amongst QA Automation Engineers, it would be extremely helpful to expand its functionality when implementing with Microsoft Power Desktop, or any exporting results of Playwright reporter via MS Teams, or Outlook, as mentioned above.
> 
> Thank you all so much; many blessings to you all for making our lives so much easier!! <3

One solution could be to use Github Actions to run your nightly tests and store results in Github Pages, Azure Storage or AWS S3 and Trigger an email to your outlook or MS Teams with links to results. 

My team had same use case as you did so I wrote Github Actions for this. Just trying to help you!  If there is the better solution please let me know!

Please note Github Pages is free for public and it comes included with Github Enterprise. But AWS S3 and Azure Storage will cost you based on size. Github Pages can let you store up to 5 GB but AWS S3 and Azure Container is unlimited storage based on cost.

https://github.com/marketplace/actions/html-reporter-github-pages
https://github.com/marketplace/actions/html-reporter-azure-website
https://github.com/marketplace/actions/html-reporter-aws-s3-website

**Comment by krishnaaSundaram-QaStack-1989** [comment]
Thanks for directing me to this page .It helped me a lot in getting solutions for my automation efforts

**Comment by krishnaaSundaram-QaStack-1989** [comment]
Hi I need assistance for below
- An understanding of the workflow file "test.yml" which is present in your repo
- I have an already existing "main.yml" file which runs test and generates html report
- My question is should I run both yours and mine as a separate file as each push to git repo starts the workflow
we can have a call on this or if chat at krishnaasundaram1989@gmail.com .

**Comment by krishnaaSundaram-QaStack-1989** [comment]
Below is my repo 
https://github.com/krishnaaSundaram-QaStack-1989/playwright_baseframework

my test.yml file
name: test

on:
  workflow_dispatch:

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git Repo
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: List Files in workspace
        if: always()
        run: |
          ls -R;
      - name: Get Test Results history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Create Test Results History
        uses: krishnaaSundaram-QaStack-1989/playwright_baseframework

        with:
          test_results: automation-report
          gh_pages: gh-pages
          results_history: results-history
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: krishnaaSundaram-QaStack-1989/playwright_baseframework
        with:
          github_token: ${{ secrets.GH_PAT }} ---> Need info on this ??
          publish_branch: gh-pages
          publish_dir: results-history
          keep_files: true

**Comment by PavanMudigondaTR** [comment]
@krishnaaSundaram-QaStack-1989 i will help you. I will send you email in couple of hours.

**Comment by PavanMudigondaTR** [comment]
@krishnaaSundaram-QaStack-1989  Please see this. I have forked your repo and updated. my GitHub pages action should be last step in your GitHub action file.  https://github.com/PavanMudigonda/playwright_baseframework/actions

sorry I have written this action for only Ubuntu. so you need to change runner type to Ubuntu-latest. I will add support for windows runner in couple of days !

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
