### ISSUE TITLE
I want the browser to stay connected in the background instead of closing after running

### ISSUE THREAD

**Issue by 18cmPenis** [microsoft/playwright#15272]
我希望浏览器在后台一直保持连接状态，而不是运行完了就关闭了
browser = playwright.chromium.launch(timeout=150000, headless=False)
context = self.browser.new_context()
context.tracing.start(screenshots=True, snapshots=True)
page = self.context.new_page()

.........

# context.close()  #
# browser.close()

For example, if the above code is not added,# context.close()  # browser.close()
The program will report an error. I don't need the browser to click. What I need is a complex JS encryption result. If the result is tracked by myself, it is very complex. I can easily obtain it with the help of playwright's JS interactive function. This is a very good function. However, since I only get this result periodically, I don't need anything else, so I need the background browser to exist all the time, He can only close when I need to.

例如上面的代码，如果不添加这段代码，# context.close()  # browser.close()
程序就会报错，单我不需要浏览器点击的操作，我需要的是一段复杂的js加密的结果，这个结果由自己来追踪的话非常的复杂，单我可以借助playwright的js互动功能轻松取得，这是个非常棒的功能，但是，由于我仅仅只是周期性的来获取这个结果，其它的都不需要，所以我需要后台浏览器一直存在，在我需要关闭时他才能关闭。

**Comment by rwoll** [comment]
Playwright's mostly focused on ephemeral testing, so the behavior of the browser exiting when the script exists is intended. You can add some code to block the script from exiting, but this is outside the scope of Playwright's API.

```py
while True:
    page.wait_for_timeout(1000)
```

at the end of your script would keep it from exiting.
