### ISSUE TITLE
[BUG] LaunchOptions config has no effect after update to v1.23.0

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#15273]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: Chromium

**Describe the bug**

I have a working project with Playwright v1.22.2 where I uncomment the LaunchOptions for local runs. After updating to v1.23 I observe the following behavior:

- the launchOptions have no effect (the test runs successfully but headless)
    `launchOptions: {
      slowMo: 500,
      headless: false
    },`

- the global setup config **does** work in headed mode with this code:
    `const browser = await chromium.launch({headless: false});`
    
- after downgrading to v1.22.2 the headed mode is working again

**Workaround**
The following code still works to run in headed mode
```javascript
launchOptions: {
      ignoreDefaultArgs: ['--headless']
    },
```

**Comment by rwoll** [comment]
Thanks for the report! I can repro the change in behavior here: https://github.com/rwoll/playwright-repro-launch-options-issue-15273/blob/main/README.md

/cc @dgozman for further triaging
