### ISSUE TITLE
[BUG] Trying to pull from NPM registry with the wrong URL

### ISSUE THREAD

**Issue by rlords** [microsoft/playwright#15284]
**Context:**
## System:
 - OS: macOS 12.4
 - Memory: 218.72 MB / 32.00 GB
## Binaries:
 - Node: 17.6.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.13.2 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.23.1 => 1.23.1 

**Code Snippet**

```
npx playwright test src/tests/path/to/test
```

**Describe the bug**

When I try to run a test it responds back with this error. The URL is incorrect as playwright is spelled wrong. I have tried uninstalling and reinstalling playwright. Tried searching for that bad URL, but was only able to find it in the log files.

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/playwrignt - Not found
npm ERR! 404 
npm ERR! 404  'playwrignt@latest' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by rwoll** [comment]
Thanks for the report—although it looks like maybe something with npm is corrupt on your machine. I tried the command in your code snippet (but replaced `src/tests/path/to/test` with `--help`), and it successfully printed the help message, and did not display the error you are seeing. I don't see `playwrignt` typo anywhere in our codebase.

Try searching just for `playwrignt` in your project. Perhaps your package-lock.json or package.json is corrupt? You can also try completely removing `node_modules/` and installing again and you can also try clearing the npm cache (`npm cache clean --force`).

**Comment by rlords** [comment]
Ok thanks. Now my tests are working again. Deleted the package files and nod_modules folder, cleared my npm cache. Did a hard reset on my git repo, and reinstalled everything
