### ISSUE TITLE
[BUG] Mouse cursor movement is unpredictable

### ISSUE THREAD

**Issue by johanndev** [microsoft/playwright#15301]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Windows 11 21H2 (OS Build 22000.739)
- Node.js version: v16.15.0
- Browser: All
- Extra: -

**Code Snippet**

```typescript
import { test } from '@playwright/test';

test('simple panning test', async ({ page }) => {
    await page.goto("https://www.openstreetmap.org")
    await page.waitForLoadState("networkidle");

    const { width, height } = page.viewportSize();
    // without the next line, the panning operation will not work *at all* 
    // I guess the mouse pointer position starts at (0,0), so I reposition it in the middle of the viewport
    await page.mouse.move(width / 2, height / 2); 

    await page.mouse.down();
    // I just want to pan 100 px on the x-Axis, but the movement also occurs in the y-Axis 
    await page.mouse.move(100, 0, { steps: 5 });
    await page.mouse.up();

    await page.waitForTimeout(5000) // Wait a moment to be able to observe the new map position
});
```

[Sample on try playwright](https://try.playwright.tech/?l=playwright-test&s=nyemltb)

**Describe the bug**
I'm trying to test an application that embeds an OSM map. During my tests I want to able to pan across the map, but I always get (at least for me) unpredictable results.

As stated in the comments, I'm just trying to pan to the right (along the x-Axis) - but the map always also moves in the y-direction.

What a I'm doing wrong/where is my mental model wrong?

Thanks!

**Comment by pavelfeldman** [comment]
Those are absolute x and y as in mouse events. So you are telling it to move to y=0.
