### ISSUE TITLE
[BUG] firefox: protocol error in Page.dispatchMouseEvent

### ISSUE THREAD

**Issue by axelson** [microsoft/playwright#15317]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac
- Node.js version: 16.14.2
- Browser: Firefox Nightly
- Extra:

## System:
 - OS: macOS 12.4
 - Memory: 1.10 GB / 16.00 GB
## Binaries:
 - Node: 16.14.2 - ~/.asdf/installs/nodejs/16.14.2/bin/node
 - Yarn: 1.22.19 - ~/.asdf/installs/nodejs/16.14.2/.npm/bin/yarn
 - npm: 8.5.0 - ~/.asdf/plugins/nodejs/shims/npm

## Languages:
 - Bash: 3.2.57 - /bin/bash

**Describe the bug**
I'm getting this failure pretty often:
```
    mouse.up: Protocol error (Page.dispatchMouseEvent): error in channel "content::page": exception while running method "dispatchMouseEvent" in namespace "page": Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIDOMWindowUtils.sendMouseEvent] _dispatchMouseEvent@chrome://juggler/content/content/PageAgent.js:720:37
    _onMessage@chrome://juggler/content/SimpleChannel.js:165:37
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
     _onMessage@chrome://juggler/content/SimpleChannel.js:149:16
    receiveMessage@chrome://juggler/content/SimpleChannel.js:16:42
```

It doesn't seem like anything that I can control since it's coming so deep within playwright. I haven't been able to find anything from Googling and I haven't been able to reproduce it in a more minimal setup.

My test loads a page, clicks a couple times which sends a websocket message, when the websocket response comes back the app code sets `window.location.href` to a new value, then the test selects an element, calculates it's bbox, and runs:

```
  await page.mouse.down();
  await page.mouse.move(300, 300);
  await page.mouse.up();
```

This error happens about 50% of the time locally on the `page.mouse.up()` line (although also sometimes on other lines). It might occur because there's a race condition because I'm not sure how to properly wait for the page navigation after the mouse clicks. So my guess is that the `window.location.href` is sometimes being executed at the same time as the `page.mouse.up()`.

Edit: I have since found Playwright's method for waiting for navigation which so far works around this bug (but I'll have more confidence one there's 100+ runs without errors).

**Comment by aslushnikov** [comment]
@axelson this is definitely a Playwright bug! I'll be happy to take a look, but I'll need a repro. Any chance there's something you can share that reproduces the issue for you?

**Comment by aslushnikov** [comment]
@axelson unfortunately this is not actionable for us without a repro. I'll have to close this, but please feel free to refile if you have a repro that we can run & debug locally!

**Comment by 0x0480** [comment]
It randomly pops-up I cant repro.
But in my code flow, I have a pool of context's that constantly closes and re-opens on same browser instance.

**Comment by samuelrizzo** [comment]
Probably it's not fixed yet, but it also happens with Selenium WebDriver.

I believe neither of them can handle browser closure properly. In my situation, the solution I found was not to close the browser, but just to reload the page. I don't know if it applies to your case, @0x0480 and @axelson

Playwright reload documentation is there: https://playwright.dev/docs/api/class-page
