### ISSUE TITLE
[Feature] Add playwright query engine to https://trace.playwright.dev/

### ISSUE THREAD

**Issue by rapidroamer** [microsoft/playwright#15313]
Playwright trace is very helpful in debugging, it shows the dom snapshots as well.
But if my locator has issues, I'd like to have the capability of using query engine on the dom snapshot in https://trace.playwright.dev/ (on the same browser instance where https://trace.playwright.dev/ is running)

it will save time.

Currently I resort to Playwright Inspector / Codegen and replay my test up to that point.

**Comment by rapidroamer** [comment]
Hi @aslushnikov, Is the local trace viewer the same as https://trace.playwright.dev codebase-wise? If so, then agreed - this is a duplicate. If not, we may need to triage again.

My thought was since trace.playwright.dev is a hosted app, it might be easier to add playwright library on the server side.

Have upvoted 7853 anyways. Thanks.

**Comment by aslushnikov** [comment]
> Hi @aslushnikov, Is the local trace viewer the same as https://trace.playwright.dev/ codebase-wise? I

@rapidroamer Yes, it's the same thing!
