### ISSUE TITLE
[Question] The difference between using Promise.all with page.waitForURL and without it

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#15322]
I use playwright/test 1.23.1  
My app is an eCommerce app with the checkout flow which I am trying to automate. 
Checkout flow consists of different steps which are basically forms the user needs to fill with the data and then click the NEXT button to proceed to the next form/step in the checkout process.  
I am having difficulties clicking the NEXT button in this process meaning that sometimes it just doesn't click it and hangs there.  
For example, I have this step:   
```
await test.step('Fill out Shipping Method checkout form', async () => {
      // HACK: don't know why I need to put this here when I already have one in the method shippingMethodCheckout.clickNextButton()
      // couldn't make it to click the NEXT button otherwise
      await page.waitForURL(/.*\/delivery-method\/choose$/);
      await shippingMethodCheckout.clickNextButton();
    });
```  
And in the `shippingMethodCheckout.clickNextButton()` is this:  
```
  public async clickNextButton() {
    await Promise.all([
      this.page.waitForURL(/.*\/delivery-method\/choose$/),
      this.nextBtn.click(),
    ]);
  }
```  
I am confused about the fact that I need to do `this.page.waitForURL(/.*\/delivery-method\/choose$/),` twice.   
I would think that having it in the `shippingMethodCheckout.clickNextButton()` method in combination with `Promise.all` would be good enough.  
But it turns out that it doesn't work unless I put additional `this.page.waitForURL(/.*\/delivery-method\/choose$/),` into the step.  
Why is that so?  
What is the difference between using `Promise.all` and not using it? What should be the correct approach here?

**Comment by ltsuda** [comment]
I'm not a Javascript developer in a good level to explain the Promise.all but I think you have some issue in your code.

Looking at the documentation of [.waitForURL](https://playwright.dev/docs/api/class-page#page-wait-for-url), you need to use it after the `.click()` occurs.

Please, remove the `.waitForURL` in the test and try the code below.
```javascript
 public async clickNextButton() {
      this.nextBtn.click(),
      this.page.waitForURL(/.*\/delivery-method\/choose$/),
  }
```

Another method that could work if the code above doesn't work is [.waitForNavigation](https://playwright.dev/docs/api/class-page#page-wait-for-navigation)

```javascript
  public async clickNextButton() {
    await Promise.all([
      this.page.waitForNavigation(),
      this.nextBtn.click(),
    ]);
  }
```
I hope this helps but let's wait for someone more experienced to explain correctly.

**Comment by mareru** [comment]
@ltsuda Thanks for your reply.  
But I actually waitForURL to be done so that I can click the button. It is not like clicking this button will cause the navigation to that URL. On the contrary, I am trying to wait for the page to finish loading so I can click the button. 
  
The flow is like Shipment form with the NEXT button -> click NEXT -> page reloads (this is when the URL changes to `/.*\/delivery-method\/choose$/`) and Shipping method form is loaded with the NEXT button -> there is a dropdown with the default option chosen so I just leave it and click NEXT button (at this point the test gets stuck - doesn't click the NEXT button) ->  page reloads and Payment method form is loaded with the NEXT button, etc. 

I will try with `waitForNavigation`  

Do you have different advice based on this?

**Comment by mareru** [comment]
WaitingForNavigation did the trick and I had to reorder it a bit in the code. Thanks for help.
