### ISSUE TITLE
[Question] How to recognize if the user is not logged in?

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#15329]
I am using the Playwright Test with Typescript.
I have implemented the authentication as described in https://playwright.dev/docs/test-auth#reuse-signed-in-state
I am testing the eCommerce app.  
I have a case where I want to do the checkout as a guest user (not logged in).  
For my test I put `test.use({ storageState: { cookies: [], origins: [] } });` in the describe bock and it works like a charm.
But then, because of the POM, I would like to have separate flows based on the fact if the user is logged in or not.  
My question is: how to check that? how do I check if I am running the test with the logged-in user or guest customer?  
I have done this so far on the `cart-page.ts`:  
```javascript
public async clickCheckoutBtn(context: BrowserContext) {
    let isLoggedInUser: boolean = await Utils.isLoggedInUser(context);
    console.log('isLoggedInUser = ' + isLoggedInUser);
    if (isLoggedInUser) {
      // Necessary in order for the NEXT button on the Shipment Checkout Form to be clickable
      await Promise.all([
        this.checkoutBtn.click(),
        this.page.waitForURL(/.*\/delivery-address\/add$/),  // this is not the flow that happens with the guest customer, so I need to avoid it for the guest user
      ]);
    } else {
      this.checkoutBtn.click();
    }
  }
```  
This is how I check it for now.
```javascript
  public static async isLoggedInUser(
    context: BrowserContext
  ): Promise<boolean> {
    let storageState = await context.storageState();
    let JSESSIONID = storageState.cookies.filter(
      (item) => item.name === 'JSESSIONID'
    );
    console.log(JSESSIONID);
    if (JSESSIONID) return true;
    return false;
  }
}
```  
But it doesn't work as I would expect. JSESSIONID is still present in the browser cookies even if I am logged out.  
Is there any better mechanism in order to check this?  
I also noticed that when doing it manually in the app if I:  

1. log in -> JSESSIONID is present
2. log out -> JSESSIONID is still there (I would expect not to be anymore)

I maybe don't understand how my app works internally and need to investigate that.  But maybe there is some more standard way to check if you are logged in or not?

**Comment by rwoll** [comment]
Since you manually mark the test as a "guest" test via `test.use({ storageState: { cookies: [], origins: [] } });`, I recommend adding a parameter to your POM Constructor (`isGuest`) that you manually set to `true` wherever you are using `test.use({ storageState: { cookies: [], origins: [] } });`.

Something like the following might work nicely as well if you are doing this in _many_ places across many files:

```ts
import { authenticatedTest, guestTest } from './base';

authenticatedTest('should have credit card already saved', async ({ myPom }) => {
   await myPom.clickProfile();
   …
})

guestTest('should have a sign up for a new account', async ({ myPom }) => {…})
```

```ts
// base.ts
import { test as _test, expect, Page, BrowserContext } from '@playwright/test';

class MyPOM {
  constructor(public page: Page, public context: BrowserContext, public isGuest: boolean = false) {
    // …
  }

  // …
}

const authenticatedTest = _test.extend<{ myPom: MyPOM, isGuest: boolean }>({
  storageState: './authenticated-state.json',
  isGuest: false,
  myPom: async ({ page, context, isGuest }, use) => {
    // beforeEach
    const pom = new MyPOM(page, context, isGuest);
    await pom.setup();

    // provide the POM to the test
    await use(pom);

    // afterEach code below here
    await pom.dispose();
  },
});

const guestTest = authenticatedTest.extend<{}>({
  storageState: { cookies: [],  origins: []},
  isGuest: true,
});

export { expect, authenticatedTest, guestTest };

```

Related:
- https://playwright.dev/docs/test-auth#testing-multiple-roles-with-pom-fixtures
- https://playwright.dev/docs/test-fixtures

**Comment by mareru** [comment]
@rwoll Thanks for the reply. This works!  
One more question if I may :)   
Do you have any recommendations on how to organize the fixture files?  
For example, `authenticatedTest` is filled with all the objects needed for my checkout flow like loginCheckoutPage, categoryPage, cartPage, shipmentChekout, paymentChekout etc.  
`guestTest` also uses those with some minor differences as shown above.  
With the setup, you purposed it works for those "big" tests. I have all that saved in a `checkout-fixture.t`s file.     
But for example, when I want to test MY ACCOUNT page, I also need to be logged in but I don't need all the pages that the fixture for the `authenticatedTest` has to offer.  
So I created a separate fixture file called `my-account-fixture.ts`. But there I only have something like this:  
```
import { Header } from '../pages/components/header';
import { test as base } from '@playwright/test';

type Fixtures = {
  header: Header;
};

export const test = base.extend<Fixtures>({
  header: async ({ page }, use) => {
    const header = new Header(page);
    await use(header);
  },
});

export { expect } from '@playwright/test';
```  
And this would mean this test would use like test instead of authenticatedTest since I already have the reuse of the authentication in the `global-setup.ts` this test will be running as authenticated user already:  
```
import { test, expect } from './fixtures/my-account-fixture';
import * as urlPartData from './data/url.part.json';

test.describe('My Account page', () => {
  test('Open My Account page', async ({ page, baseURL, header }) => {
    await test.step('Navigate to My Account page', async () => {
      await page.goto('/');
      await header.clickUsernameIcon();
      await header.clickMyAccountOption();
      await expect(page).toHaveURL(baseURL + urlPartData.myAccount);
    });
  });
});
```  
This might be confusing, when to use one and when to use another.  Do you have any suggestions on how to organize this better?

**Comment by rwoll** [comment]
> but I am kinda struggling to organize my tests somehow from the beginning so I can write them in an easy manner afterwords when more of them come.

This is very natural! Keep things as simple as possible, and as you add more tests some patterns may fall out. It's a bit like general software eng: pre mature abstractions can make future code more difficult to work with, so only add them after the fact.

Without seeing your full test suite (which is outside the scope of the help I'm able to provide), it's hard to make concrete recommendations for your specific case.

Fixtures v helper functions v different base tests v beforeEach hooks etc. are all tools to experiment with and see what works best for your project. You can look through Playwrights own tests to see some patterns we use.

I know that might not be the most helpful answer, but I can't say to do it one way or the other without more context.

**Comment by mareru** [comment]
@rwoll 
Thanks for the helpful information and advice, I really appreciate it.  
Can you send me the link where I can check out the Playwrights own tests to see the patterns you use? I am not sure what you refer to by that.   
Thanks once again.
