### ISSUE TITLE
[BUG] Getting action was interrupted frequently 

### ISSUE THREAD

**Issue by divysharma007** [microsoft/playwright#15324]
## System:
 - OS: Windows 10 10.0.19044  
 - Memory: 52.51 GB / 63.95 GB
## Binaries:
 - Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: ^1.22.2 => 1.23.1
**Code Snippet**
```js
await page.goto(data.COMPOSE_URL);
await page.locator(selectors.COMPOSE_PANE_LIST_BOX).waitFor();
await page.locator(selectors.MORE_APPS).last().click();
```
**Describe the bug**
I am getting action was interrupted while clicking more apps, it times out. I am facing this in other steps also, why is it happening? I am attaching trace also. 
[f683ee78b92fb4d0b112d85659673109c5438b66.zip](https://github.com/microsoft/playwright/files/9032649/f683ee78b92fb4d0b112d85659673109c5438b66.zip)

**Comment by dgozman** [comment]
@divysharma007 Unfortunately, I am not able to figure out the issue just from the trace. It seems like the target element is there, but it was not found. Could you please share a repro that we can run locally?

**Comment by divysharma007** [comment]
@dgozman Sorry I cannot share it as I am not allowed to, is there any other way?

**Comment by dgozman** [comment]
@divysharma007 Not really. We have to reproduce locally to be able to debug it.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one with a reproducible example and link to this issue when you get back to it!
