### ISSUE TITLE
[Feature]Google Authentication

### ISSUE THREAD

**Issue by Raghu-GreatLearning** [microsoft/playwright#15328]
Looking for a way to sign in or signup to my application using google account. 
......
https://developers.google.com/identity/protocols/oauth2

**Comment by rwoll** [comment]
See https://playwright.dev/docs/test-auth and https://github.com/rwoll/playwright-reuse-auth-demo. You can automate part of it, but Google will likely serve 2FA challenges which you'll have to complete manually every few days. The links above guide you through re-using authentication state, so you login once—either in global setup or via the CLI—and then re-use this state during your tests so you are already signed in on Google's side.

**Comment by rwoll** [comment]
Closing per above and as part of weekly triage, but feel free to re-open or re-file if the guides above don't provide the information you need. Thanks!
