### ISSUE TITLE
Is there a way to use playwright python with a BDD system based on Cucumber?

### ISSUE THREAD

**Issue by keithwhitson** [microsoft/playwright#15335]

**Comment by Maciejjy** [comment]
Yes, you can use Playwright with cucumber.js. There are many guides online.
I don't reccomend it though. This is not a "standard" way of working with Playwright and you will have to custom some things and use different runner instead of @playwright/test.

**Comment by keithwhitson** [comment]
But I want to use the Python Version of Playwright and not the Typescript/Javascript version of it. I have found many ways to use it with JavaScript but I mean with Python.

**Comment by aslushnikov** [comment]
@keithwhitson there's nothing for it out-of-the-box, and I'm not well-versed in Python ecosystem to recommend anything! Consider asking on stackoverflow or on out slack channel: https://aka.ms/playwright/slack
