### ISSUE TITLE
[Feature] I would love tight integration with a cucumber based bdd

### ISSUE THREAD

**Issue by keithwhitson** [microsoft/playwright#15336]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

**Comment by aslushnikov** [comment]
Overall, this has been discussed before at https://github.com/microsoft/playwright/issues/14265

As a summary, you can use Playwright with cucumber today, e.g. read here: https://tally-b.medium.com/e2e-testing-with-cucumber-and-playwright-9584d3ef3360
