### ISSUE TITLE
[Question] How to use Playwright Test with a test project and shared project?

### ISSUE THREAD

**Issue by GP-QA** [microsoft/playwright#15349]
Hi,

We have a Playwright with Jest runner project with an Electron app. It uses routes for mocking API calls and some page objects from a shared project (which has his own package.json). We would like to switch to Playwright Test, but we are facing issues. When I use Playwright Test in both project and start a test, then I receive the following error:

Error: Requiring @playwright/test second time
...
 no tests found.

With references to test project files and shared project files.

When I use Playwright Test in the test project and Playwright in the shared project, then the mocking in the 2nd test fails. The API responses are empty. The first test is working correctly. What is the right approach for this setup?

**Comment by GP-QA** [comment]
Hi aslushnikov,

Yes this works, the error **Requiring @playwright/test second time** is gone. Thank you! I also needed to move a login script (being used by a 2nd test project) which imports chromium from the shared project to the testproject itself. Since chromium cannot be used as a type when launching it.

But when running the tests the 2nd, 4th, 6th etc. tests have again an empty API response for a mocked API call. The first, third, fifth etc. tests are working correctly, which is very strange. We didn't see any issues with Jest runner. I think this has to do with the setup order of our Electron project. Because the initialization of routes (routes = new Routes(window)) is not in place before the Electron window is created and therefore the first api call is too late mocked. 

We have an authentication window, main window and dev tools window. We first check the amount of windows via a for loop, after that we wait for 5 secs (wait for loading windows to be completed)  and then we identify the windows via the title.  And then we initialize the routes for the main window. In the app we select a home button that results in executing the API calls again. But this seems to be not working correctly with the Playwright Test runner. I don't know if I should report this as a bug or that we need to alter our setup?

Code:
```
init.ts:
export let windows: ElectronWindows;
export interface ElectronWindows {
    authenticationWindow: Page;
    mainWindow: Page;
    devToolsWindow: Page;
}

export async function initWindow(): Promise<Page> {
    const electronApp: ElectronApplication = await electron.launch({
        executablePath: setup.executablePath,
        acceptDownloads: true,
        offline: false,
        args: ['openDevTools'],
    });
    windows = await setWindows(electronApp, true); // identify Electron windows
    await windows.mainWindow.bringToFront();
    await initRoutes(windows.mainWindow as Page);

    const sessionStorageFile = fs.readFileSync('storageState.json', 'utf8');
    const sessionStorage = JSON.parse(sessionStorageFile);
    await windows.mainWindow.evaluate((json) => {
        for (const key in json) sessionStorage.setItem(key, json[key]);
    }, sessionStorage);

    await windows.mainWindow.reload();
    await windows.authenticationWindow.close();
    return windows.mainWindow as Page;
}

spec file example:
test.beforeAll(async () => {
        const window = await initWindow();
        floorplanPage = new FloorplanPage(window);
        projectsPage = new ProjectsPage(window);
        await routes.solutions.mockGetSolutionsOK(ProjectsData.artProjectsAll);
```

**Comment by aslushnikov** [comment]
@GP-QA so it looks like you're setting routes too late. So you'll need to launch your electron app, set the interception routes, and then proceed with app launching logic.

For this you'll need to have some `UNDER_TEST` environment variable that your applications sniffs and postpones its loading. When doing test, you set this env variable, open electron app, and then call special `applicationContinueLoadingForTest` method.

In pseudo-code, this would look like this:

```js
// Electron app: the very start of its lifecycle 
if (process.env.IS_UNDER_TEST) {
  // .. do nothing! Wait for test function to call the doLoadApplication()
} else {
  doLoadApplication();
}
```

**Comment by Forfold** [comment]
@aslushnikov I'm also running into this- first I had the issue of `Error: Requiring @playwright/test second time` but after making some changes and moving things into dev dependencies I'm now seeing this error:

`Argument of type 'import("/website/node_modules/playwright-core/types/types").Page' is not assignable to parameter of type 'import("/playwright-auth/node_modules/playwright-core/types/types").Page'. The types returned by 'evaluateHandle(...)' are incompatible between these types.`

I have a `playwright-auth` package I'm creating to handle some login stuff that I plan to use in multiple repos I'm working on. `playwright-auth` exports a `login()` and a `globalLogin()` function

When I try writing tests in the repo that installs `playwright-auth`, I get the above type error when I try using `page` from within a test. Both repos utilize `@playwright/test` as well for different reasons

**Comment by yury-s** [comment]
> My `playwright-auth` package.json looks like this:

@Forfold remove `"playwright": "1.23.2",` from your dependencies and peer dependencies, a module should depend on either  `@playwright/test` or `playwright` but not both. If you want `playwright-auth` to work with both types of modules as peer deps you can set peer dependencies to playwright-core:

```
  "peerDependencies": {
    "playwright-core": "1.23.2"
  },
```

**Comment by Forfold** [comment]
Thanks for the catch on removing that package @yury-s, it looks like I was only using it for a type that's also available in @playwright/test. After fixing that though I am still seeing the same error of `Error: Requiring @playwright/test second time`. I tried adding `"playwright-core": "1.23.2"` to `playwright-auth`'s peer dependencies but the error still came up

**Comment by yury-s** [comment]
@Forfold could you share a project where you see the error?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by Forfold** [comment]
For sure- I just made a repo outlining this (unfortunately where I'm seeing it is in an internal project). I'll make another issue though

https://github.com/Forfold/playwright-test
