### ISSUE TITLE
[Question] waitFor times out without even waiting 

### ISSUE THREAD

**Issue by divysharma007** [microsoft/playwright#15341]
![image](https://user-images.githubusercontent.com/70777384/177046352-2971f295-c847-4aaf-bf3f-20c7d5c6c8a7.png)
Here waitFor didn't wait and timed out, its happening frequently, why is it happening?

**Comment by aslushnikov** [comment]
> Here waitFor didn't wait and timed out

@divysharma007 It looks like it waited, but the test ran out of time. You can try [marking the test as "slow"](https://playwright.dev/docs/api/class-test#test-slow-1) to give the page more time to load, or manually adjust the test timeout.

**Comment by divysharma007** [comment]
Yeah, I think the same, thanks
