### ISSUE TITLE
How to set force-dark-mode in playwright

### ISSUE THREAD

**Issue by ajayEngProd** [microsoft/playwright#15345]
we are running some tests which requires dark mode by setting force-dark-mode as shown in the below screen shot. As this is the only way to render our webpage in dark mode.

Requesting you to pls let me know if we have a way to force-dark-mode set up in playwright.

we tried to set the dark mode using the following piece of code but the webpage is not coming up in dark mode even though dark color scheme is enabled.

      await Page.EmulateMediaAsync(new() { ColorScheme = ColorScheme.Dark });
       Assert.True(await Page.EvaluateAsync<bool>("() => matchMedia('(prefers-color-scheme: dark)').matches"));

![image](https://user-images.githubusercontent.com/105768577/177082757-2c59373c-bf85-4571-a0ef-06bfdab4309e.png)

**Comment by p01** [comment]
https://playwright.dev/docs/codegen#emulate-color-scheme-and-viewport-size ;)

**Comment by p01** [comment]
This other issue #15211 even shows how to do set color scheme and forced colors using the playwright.config.ts

**Comment by ajayEngProd** [comment]
@p01  the above issue is still open and am trying to set the force color scheme as shown in the above issue.

**Comment by ajayEngProd** [comment]
hi @aslushnikov , i am using 
OS: windows
playwright version : 1.13.0
Dot net version : 5 and 6

but it seems like forced colors is not available in this version , am i correct ? 

   
![image](https://user-images.githubusercontent.com/105768577/177465851-8dba839e-5324-493d-82d9-d58ae43f50d6.png)

**Comment by aslushnikov** [comment]
Looks like this is resolved, so closing! Please file new issues if/when things don't work for you or when you have questions!
