### ISSUE TITLE
[BUG] Trying to run Playwright script through Selenium 4 grid, but getting socket err

### ISSUE THREAD

**Issue by maranbalu** [microsoft/playwright#15346]
**Context:**
- Playwright Version: [1.23]
- Operating System: [Windows]
- Node.js version: [v16.13.2]
- Browser: [Chrome]
- Extra: [Selenium Hub in Windows and Node in Linux]

In CLI, first set the env variable as follows:
set SELENIUM_REMOTE_URL=http://localhost:4444 (This is my remote driver URL)

[ERROR] Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 6.708 s <<< FAILURE! - in TestSuite
[ERROR] setup(com.practice.SeleniumGrid4Demo.tests.TestFour)  Time elapsed: 6.595 s  <<< FAILURE!
com.microsoft.playwright.PlaywrightException:
Error {
  message='WebSocket error: connect ECONNREFUSED

**Describe the bug**
While trying to run my playwright scrip in node machine, I received the above error message. I strictly followed the instructions provided here:
[https://playwright.dev/java/docs/selenium-grid]
But still got nowhere
Add any other details about the problem here.

**Comment by aslushnikov** [comment]
(cc'ing @dgozman for an advice)

**Comment by dgozman** [comment]
@maranbalu We have updated [the docs](https://playwright.dev/java/docs/next/selenium-grid) - perhaps you could follow them to resolve your issue?

**Comment by dgozman** [comment]
Closing as per above. If the problem persists and you have a repro, please file a new issue and link to this one.
