### ISSUE TITLE
[Question] Could playwright be a good framework for automating UI tests using Visual Studio with Team foundation server (TFS) 2017?

### ISSUE THREAD

**Issue by JeromeT-B** [microsoft/playwright#15358]
Hi, I'm a beginner in IT development and my team asked me to find a framework/tool to help automate UI tests for our projects. We currently use Visual studio with Team Server Foundation 2017 (TFS\Azure) and I was wondering if playright could be a good option? Also, if anyone knows a better tool or alternative for this purpose, it would help me a lot. It doesn't need to be free either.

Programming languages:
.NET and Python

**Comment by aslushnikov** [comment]
@JeromeT-B Playwright's good for automating Web sites. Both .NET and Python are supported to author your automations.

What kind of projects do you have?

**Comment by JeromeT-B** [comment]
I'm not exacly sure but for now let's say mainly for Web development. We are also probably gonna work with multiple databases and customer data.

**Comment by aslushnikov** [comment]
> I'm not exactly sure but for now let's say mainly for Web development. We are also probably gonna work with multiple databases and customer data.

@JeromeT-B So I'd say it's hard to recommend anything given this limited information, but as long as you're testing Web, Playwright should suite you well! 

I'll close this for now; feel free to re-file if you have more questions!
