### ISSUE TITLE
[Question]: How to use HTTP Authentication with MS dynamics

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#15357]
### Your question

Hello playwright team,

hope you can help me with the following:

I am not able to login to MS dynamics application via HTTP Authentication

If I have to log in manually this is what I usually do (example with incognito session)

1. I open the URL of the application
2. I am redirected to the MS login authenticate page
![image](https://user-images.githubusercontent.com/94455079/177163828-9dd96aec-7730-413a-ae3f-0532e6e7b396.png)
3. I type my email and click on Next button
4. Then I am redirected to a new page where I need to put my username and password -> this authentication pop up is not in the DOM, so I am not able to perform UI actions on it and my idea was to try with HTTP Authentication.
![image](https://user-images.githubusercontent.com/94455079/177164410-2726b8ec-44fc-407a-b06a-9897296e6e7a.png)

Below is the code that I currently have, but unfortunately it is not signing me in. I thought that when clicking Next button it will also take the HttpCredentials values, but seems it does not.

            var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
                Headless = false,
            });

            await browser.NewContextAsync(new BrowserNewContextOptions
            {
                HttpCredentials = new() { Username = "myusername", Password = "mypassword" }
            });

            var page = await browser.NewPageAsync();
            await page.GotoAsync("https://clientname.dynamics.com/");
            await page.Locator("//input[@name='loginfmt']").FillAsync("myemail");
            await page.Locator("text=next").ClickAsync();

            await page.PauseAsync();

Could you please tell me what I am doing wrong?

**Comment by marko-simic** [comment]
You can try:
```JavaScript
await context.setHTTPCredentials({
  // @ts-ignore
  username: process.env.USERNAME,
  // @ts-ignore
  password: process.env.PASSWORD,
});
```

**Comment by aslushnikov** [comment]
@NikkTod your issue is that you set HTTP credentials on one context, while creating a page in a new one.

One way to fix it would be like this:

```csharp
        var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
        {
            Headless = false,
        });

        var context = await browser.NewContextAsync(new BrowserNewContextOptions
        {
            HttpCredentials = new() { Username = "myusername", Password = "mypassword" }
        });

        var page = await context.NewPageAsync();
        await page.GotoAsync("https://clientname.dynamics.com/");
        await page.Locator("//input[@name='loginfmt']").FillAsync("myemail");
        await page.Locator("text=next").ClickAsync();

        await page.PauseAsync();
```

**Comment by aslushnikov** [comment]
Looks like this is resolved, so closing! If things don't work for you, then please do not hesitate to re-file!

**Comment by NikkTod** [comment]
@aslushnikov It works! Very very much thank you! Keep it going, playwright is the future!
