### ISSUE TITLE
[BUG] junit_reporter: embed attachments only works for tests in project root folder

### ISSUE THREAD

**Issue by bitcoder** [microsoft/playwright#15360]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Mac
- Node.js version: v12.18.2
- Browser: All
- Extra: 

## System:
 - OS: macOS 12.4
 - Memory: 1.26 GB / 16.00 GB
## Binaries:
 - Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 8.3.0 - ~/.nvm/versions/node/v12.18.2/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

playwright.config.js
```

```

sample test:

```javascript
    test('Login with valid credentials', async({ page }, testInfo) => {
       await page.goto('https://example.com/');

        // Capture a screenshot and attach it.
        const path = testInfo.outputPath('tmp_screenshot.png');
        await page.screenshot({ path });
        testInfo.attachments.push({ name: 'screenshot.png', path, contentType: 'image/png' });
    });

```

Expected Junit XML report (after running `npx playwright test`):
```xml
<testcase name="Login validations Login with valid credentials" classname="login.spec.js:13:5 › Login validations › Login with valid credentials" time="2.226">
<properties>
<property name="testrun_evidence">
<item name="screenshot.png">
<![CDATA[iVBORw0KGgoAAAANSUhEUgAABQAAAALQCAYAAADPfd1WAAAAAXNSR0IArs4c6QAAIABJREFUeJzs3Xv81/PdP/BHB+TwdbhQDjW09FVR5ComYiGHhGrNYWziYphTOeW6nMIcZpfDLlNsl5nM2ZrFZcmQQ5pDKkSlDNloLHwlJfX7o9/3s759Pt/65rB4736/3brt83m9X+/3+/V+vz9u6/bo9Xo/G02fPn1RAAAAAIBCaryyBwAAAAAAfHkEgAAAAABQYAJAAAAAACgwASAAAAAAFJgAEAAAAAAKTAAIAAAAAAUmAAQAAACAAhMAAgAAAECBCQABAAAAoMAEgAAAAABQYAJAAAAAACgwASAAAAAAFJgAEAAAAAAKTAAIAAAAAAUm....
....
```
**Describe the bug**

The junit reporter has the possibility of embedding attachments as base64. However, the previous code checked for the existence of the attachment based on a wrong check and was not reading it also from the correct path.
The previous code worked fine, if the test was in the project's root folder. If the test was somewhere else, like in ".tests/", then it wouldn't work as expected.

**Comment by aslushnikov** [comment]
(Over to Dmitry who's overseeing JUnit reporter)
