### ISSUE TITLE
[Question] Validate date format

### ISSUE THREAD

**Issue by Aenz99** [microsoft/playwright#15365]
Hello people, I'm new to Playwright, Question: Is there any way to validate a format?
In this case it's a date. e.g:

28/06/2022 12:41:39

To be more precise, I want to validate in which place the slashes and colons are located.

I hope you can help me.
Thanks in advance.

**Comment by daddyman** [comment]
You could use expect toMatch and use a regular expression to validate any format you want.

```
const value = '28/06/2022 12:41:39';
expect(value).toMatch(/^\d\d\/\d\d\/\d\d\d\d \d\d:\d\d:\d\d$/);
```

**Comment by mxschmitt** [comment]
You can use a [web-first assertion: toHaveText](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text) with a regex, e.g. https://regex101.com to verify that.
