### ISSUE TITLE
[Question] Is navigationTimeout mentioned in playwright config is applicable for globalSetup Script  ??

### ISSUE THREAD

**Issue by shivam1490tyro** [microsoft/playwright#15368]
What we have done is write a globalsetup to re-use auth login for our website. Also we have put navigationTimeout in our playwright config as below 

```
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  use: {
    headless: true,
    storageState: './storageState.json',
    navigationTimeout: 90 * 1000,
  },
  testDir: 'web-tests',
  timeout: 90 * 1000,
  expect: {
    timeout: 15000,
  },
  globalSetup: './helpers/auth.ts',
};

export default config;
```

our globalSetupfile is not recognising it when we run in buildkite pipeline and we have to setup manually for page.goto and page.waitForLoadState as below to make it work. Why config timeouts are not working for this file ?? 

```
const auth = async ({ config: FullConfig }) => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(baseUrl, { timeout: 80000 });
  await page.locator('id=email').fill('xxxx');
  await page.locator('id=password').fill('xxxxx');
  await page.locator('text="Log in"').click();
  await page.waitForLoadState('networkidle', { timeout: 90000 });
  await page.context().storageState({ path: './storageState.json' });
  await browser.close();
};

```

Another issue is that these timeouts(navigationTimeout in config and two in globalSetup)  are not required when we are running this in local.
Its failing only when runs in pipeline which is why we have added timeouts manually in globalScript file

**Comment by mxschmitt** [comment]
The options you set inside your config do not reflect inside global setup. Since global setup runs for all the projects and not only for a single one. You need to manually set the different launch, context or other options inside global setup again.
