### ISSUE TITLE
[Question] "locator.click: Target closed" for different random selectors

### ISSUE THREAD

**Issue by gegoncalves** [microsoft/playwright#15379]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Windows and Linux
- Node.js version: v16.15.1
- Browser: All
- Extra: [any specific details about your environment]

Until 2 weeks ago my tests were working without a problem. Since Monday they are failing with the same error but for random locators. 

For example:
```log
Execution log

- waiting for selector "a[role="tab"]:has-text("addition") >> nth=1"
   - selector resolved to visible <a role="tab" href="#addition" data-toggle="tab" ari…> addition
- attempting click action
   - waiting for element to be visible, enabled and stable
```

Coincidentally the problem started happening after I updated to PW version 1.23.1. I think I was in the version 1.22

Looking to the trace it is clear that the element is there.

What can cause that problem?

**Comment by aslushnikov** [comment]
@gegoncalves can you share your trace?

**Comment by gegoncalves** [comment]
> @gegoncalves can you share your trace?

Unfortunately I cannot 😞 

But I noticed the pattern. It generally happens when it tries to interact with the notification center box or elements that are not visible. PW kinds of try to scroll or resize the viewport and returns the error

ex: I am trying to click on the Hide button for the notification. However, if the notification center is too big (but fully visible on screen) the error occurs.

```html
<notification-center style="display: inline;">
...
<div class="notification_panel_bottom"> <a class="hide-notifications"> Hide </a> <a>
shenanigans ... 
</a> </div>
</notification-center>
```

Some elements (that are out of the visible area) inside of modals sometimes are not scrolled to view and the issue happens
