### ISSUE TITLE
[Feature] Easy mode for shortcuts

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#1537]
Right now pressing shortcuts can be a bit of a pain. Pressing multiple keys requires something like
```js
await page.keyboard.down('Control');
await page.keyboard.press('a');
await page.keyboard.up('Control');
```
If you want it to perform select all, you need extra code for Mac to work:
```js
await page.keyboard.down(isMac ? 'Meta' : 'Control');
await page.keyboard.press('a');
await page.keyboard.up(isMac ? 'Meta' : 'Control');
```

It would be nice to be able to do something like
```js
await page.keyboard.press('Control+a');
```
or
```js
await page.keyboard.command('selectAll');
```
@pavelfeldman

**Comment by jperl** [comment]
Cypress has a [{sequence}](https://docs.cypress.io/api/commands/type.html#Arguments) concept which seems like a handy pattern. Ex. `{selectall}`
