### ISSUE TITLE
[BUG] Browser download randomly interrupts and gets reported as success

### ISSUE THREAD

**Issue by MarkKahn** [microsoft/playwright#15378]
**Context:**
- Playwright Version: 1.12.1
- Operating System: OSX 12.4, M1 MBP
- Node.js version: 18.4.0
- Browser: Chromium
- Extra: clean

**Code Snippet**
**Describe the bug**

```
> mkdir test
> cd test
> npm init
> npm init playwright@latest
> npx playwright install
Downloading Chromium 104.0.5112.20 (playwright build v1012) - 115.7 Mb [=================== ] 93% 26.9s npx playwright install  4.57s user 3.66s system 2% cpu 6:17.17 total
> npx playwright open
➜  npx playwright open
object.<anonymous>: Executable doesn't exist at ~/Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/Chromium
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
    at Object.<anonymous> (~/git/test/node_modules/playwright-core/cli.js:17:18) {
  name: 'Error'
```

`~/Library/Caches/ms-playwright` is empty.  During the install, `~/Library/Caches/ms-playwright/__lockfile` exists, so it doesn't appear to be a permissions issue.

**Comment by mxschmitt** [comment]
Looks like you ran into that: https://github.com/microsoft/playwright/issues/15026

could you try running "npx playwright install" again? or delete the ms-playwright folder and do it again?

**Comment by MarkKahn** [comment]
I've run `npx playwright install` about 5 or 6 times now, no luck.  Just deleted that folder in ~/Library/Caches, still no luck

**Comment by mxschmitt** [comment]
Could you do:
- `rm -rf ~/Library/Caches/ms-playwright/`
- `DEBUG=pw:install npx playwright install`

This should give us more debug output.

> Does there happen to be a manual way to do this? Just wget whatever it needs?

Unfortunately not that easy :/

**Comment by MarkKahn** [comment]
Nothing useful:

```
➜  test DEBUG=pw:install npx playwright install
  pw:install downloading Chromium 104.0.5112.20 (playwright build v1012) - attempt #1 +0ms
  pw:install running download: +1ms
  pw:install -- from url: https://playwright.azureedge.net/builds/chromium/1012/chromium-mac-arm64.zip +0ms
  pw:install -- to location: /var/folders/lc/21_b8vjx55zf6jnn2bjpp4j00000gq/T/playwright-download-chromium-mac12-arm64-1012.zip +0ms
  pw:install -- response status code: 200 +996ms
  pw:install -- total bytes: 121282821 +3ms
Downloading Chromium 104.0.5112.20 (playwright build v1012) - 115.7 Mb [====================] 99% 5.3s DEBUG=pw:install npx playwright install  4.94s user 5.32s system 1% cpu 8:53.67 total
```

The file it downloaded appears to be invalid FWIW:

```
➜  T unzip playwright-download-chromium-mac12-arm64-1012.zip
Archive:  playwright-download-chromium-mac12-arm64-1012.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of playwright-download-chromium-mac12-arm64-1012.zip or
        playwright-download-chromium-mac12-arm64-1012.zip.zip, and cannot find playwright-download-chromium-mac12-arm64-1012.zip.ZIP, period.
```

**Comment by aslushnikov** [comment]
> [edit] Kinda. It unzips, but OSX says the app isn't valid

@MarkKahn Yeah, that's because it's been download via a browser, so it's been quarantined by OSX. You can make it work [like this](https://superuser.com/questions/526920/how-to-remove-quarantine-from-file-permissions-in-os-x). 

Are you available for a quick live slack debugging session right now ?

**Comment by MarkKahn** [comment]
@aslushnikov -- cool, un-quarantining it and putting it where playwright expects it to be works.

> live slack debugging session right now ?

Not at the moment, but since this is also an issue for others happy to later today if it'd help you debug (it works for me at the moment and I have a workaround, so I'm "good")

**Comment by aslushnikov** [comment]
It'll help tremendously if this misbehavior reproduces reliably on your machine so that we can add some logging and see what's broken!

Let me know when you have time, I'll be happy to jump on a call

**Comment by aslushnikov** [comment]
>  cool, un-quarantining it and putting it where playwright expects it to be works.

@MakrKahn To make things completely legit, make sure to add an empty `INSTALLATION_COMPLETE` flag to the directory, like this:

```bash
$  touch ~/Library/Caches/ms-playwright/chromium-1012/INSTALLATION_COMPLETE
```

This way Playwright won't nuke this chromium next time you run `npx playwright install`.

**Comment by aslushnikov** [comment]
@MarkKahn I can't find you on playwright.slack.com - could you please write me a DM there? I'm @aslushnikov there

**Comment by aslushnikov** [comment]
Also, if you're on some other slack - Playwright's slack is https://aka.ms/playwright-slack

**Comment by MarkKahn** [comment]
It appears I need an invite to that

**Comment by aslushnikov** [comment]
The https://aka.ms/playwright-slack should do!

**Comment by aslushnikov** [comment]
Can you please try one more time? The invite should be good now

**Comment by mxschmitt** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
