### ISSUE TITLE
[BUG] Can't use a screenshot path created by a function

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15374]
Hello, i did a little function to build the path to the screenshot, this is the function;

```js
export async function abstractpath(language : String, pagina : String , screenshot : String){
    const today = new Date();
    const date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();
    return "Application Screenshot/" + date + "/" + language + "/" + pagina + "/" + screenshot + "_" + language + ".png";
}
```

But for some reason, when using this function, when the screenshot moment come i get this error: " Error: path: unsupported mime type "null"

**Comment by mxschmitt** [comment]
Can you log the path which you generate before passing it to the Playwright screenshot function and then you know more why the error happens!

**Comment by aslushnikov** [comment]
Good advice from @mxschmitt !
