### ISSUE TITLE
[Question] Hardware acceleration with headless mode

### ISSUE THREAD

**Issue by zawadzkilukasz** [microsoft/playwright#15373]
Hi,
I have some problems with running chromium browser in headless mode. I'm using playwright witch java.
While running without headless flag, page that I want to test works fine but when I turn on headless mode page don't load showing message that "hardware acceleration is off".
How can I turn on hardware acceleration in headless mode ?
I tried to add some additional args but without luck.

**Comment by mxschmitt** [comment]
Where do you see this message? Which website are you testing? Whats your OS/etc. can you. provide us a repro which we can run locally?

**Comment by zawadzkilukasz** [comment]
I solved my problem. 
It seems that adding flag "--use-angle=default" enabled hardware acceleration in headless mode.

```
    try (Playwright playwright = Playwright.create()) {
       Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setHeadless(true).setArgs(List.of( "--use-angle=default"))
       );
      Page page = browser.newPage();
      page.navigate("url");
    }
```
