### ISSUE TITLE
Are we able to use the expect assertions with playwright while using specflow

### ISSUE THREAD

**Issue by ayayassine** [microsoft/playwright#15375]
We are currently using .Net playwright integrated with the BDD framework using Specflow (Given,When,Then).

We have all extensions and nugets installed. However the await Expect is not being recognized. 

Are there any limitation for using the assertions library and expect method?

**Comment by mxschmitt** [comment]
We provide it as a method only in the NUnit and MSTest bindings. But you can use it manually like this:

`await Assertions.Expect(loginPage.Locator("#weather")).ToHaveTextAsync("foobar");`

Which is exported from `Microsoft.Playwright`
