### ISSUE TITLE
[Question] In CMD run test not found

### ISSUE THREAD

**Issue by zantler** [microsoft/playwright#15387]
Hi im trying ti run my test on the cmd but the terminal doenst load de config file o dont found any test.
![image](https://user-images.githubusercontent.com/89181258/177405780-d9b78abe-9a39-409d-9967-b514c736cbe1.png)
![image](https://user-images.githubusercontent.com/89181258/177405815-bbb4f48a-f598-4520-a4d2-c70989d3b81c.png)
![image](https://user-images.githubusercontent.com/89181258/177405923-3c34474f-971a-4949-a533-13eca8f8bfa1.png)

Thanks

**Comment by ltsuda** [comment]
Your `playwright.config.ts` is inside the `tests` directory and the `testDir` configuration is set to `test`. So, `test` directory doesn't exist inside the `tests` directory, that's why is not finding any test case.

Please, try moving the `playwright.config.ts` file to the root of the `automation` folder and set `testDir: "tests"` [1], or set `testDir: "."` [2].

I think playwright look up for tests cases relatively to `playwright.config.ts` file location, so you have to set `testDir` correctly.

1. Move config file to `automation` root directory
```bash
automation/
...
playwright.config.ts
tests/
|---Find hotels
|---...
```
and update `testDir`

```javascript
const config: PlaywrightTestConfig = {
  testDir: "tests",
..
}
```

2. Just update `testDir`
```javascript
const config: PlaywrightTestConfig = {
  testDir: ".",
..
}
```

**Comment by ltsuda** [comment]
I'm sorry if my last comment was too confused.

As you moved the `playwright.config.ts`, as item 1 from my last comment, to the root directory, the `testDir` should be set to `tests`.

**Comment by zantler** [comment]
> I'm sorry if my last comment was too confused.
> 
> As you moved the `playwright.config.ts`, as item 1 from my last comment, to the root directory, the `testDir` should be set to `tests`.

If i try that way, the message on the console is the same

**Comment by ltsuda** [comment]
your `testDir` is incorrect, it should be `tests` plural as this is the folder that has you test cases, not `test` singular.

**Comment by ltsuda** [comment]
your `testDir` is incorrect, it should be `tests` plural as this is the folder that has you test cases, not `test` singular.

**Comment by zantler** [comment]
> your `testDir` is incorrect, it should be `tests` plural as this is the folder that has you test cases, not `test` singular.
> 
> ![image](https://user-images.githubusercontent.com/3965277/177571781-767635c3-c5bf-4c0d-a08d-e58df798a73b.png)

sorry my bad. I fix it but is the same :/

**Comment by ltsuda** [comment]
I'm sorry to hear that :(

I'm not able to test on my Windows machine right now because I'm at work and I don't have node/playwright installed on Windows, only on Linux. I will install it after work to try it.

Let's hope someone has a better idea until then.

**Comment by zantler** [comment]
> I'm sorry to hear that :(
> 
> I'm not able to test on my Windows machine right now because I'm at work and I don't have node/playwright installed on Windows, only on Linux. I will install it after work to try it.
> 
> Let's hope someone has a better idea until then.

Thank you a lot

**Comment by ltsuda** [comment]
Just installed @playwright/test 1.23.1 on my Windows machine, it's working fine.

I created this project using the Playwright VSCode extension that setup a template project. I don't know what could be the problem on your setup.

```bash
Windows 11
npm 8.11.0
node: 16.15.1
```

![image](https://user-images.githubusercontent.com/3965277/177626470-0bca5e17-bd88-4ed7-9255-97a827b94928.png)

Maybe try to setup the template project on another folder:

https://playwright.dev/docs/intro#using-init-command

Then run `npx playwright test` on the project created.

**Comment by spnraju** [comment]
I had the same issue on `Windows 10`. Interestingly, `./tests` did not work but `../tests` did work for `testDir`. 
I tried this with `outputDir` and it works in the same way. If I have `./reports`, it creates this folder in the location of my config file.

Maybe somewhere in the code, we are setting the config file location as the project root directory?

Sample Project: https://github.com/spnraju/demo-playwright-typescript

**Comment by aslushnikov** [comment]
Thank you @ltsuda for helping out! Looks like this issue can be closed. If anything missing, feel free to re-file, or ask a question in our slack - https://aka.ms/playwright/slack
