### ISSUE TITLE
[Question] I cannot set cookies properly - my page doesn't even load

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#15392]
I am using Playwright Test 1.23.1.  
I am testing an eCommerce site. I have a scenario that loads the site for Europe or US depending on the cookies set in the browser.  
So I want to do it inside a fixture file like this:  
```javascript
// common-fixtures.ts
export const authenticatedTestEU = authenticatedTest.extend<{}>({
  storageState: './euCustomerStorageState.json',
  setCookies: async ({ browser, page, baseURL }) => {
    const browserContext = await browser.newContext();
    const cookieValues = [
      {
        name: 'myCookie',
        value: 'myValue',
        url: baseURL
      },
    ];
    await browserContext.addCookies(cookieValues);
    console.log(await browserContext.cookies());
  },
}); 
```  
`authenticatedTest` is an extension of playwright/test which contains a bunch of POMs used in the tests and the storageState for US Customer.  
Then in my test, I do the following:  
```javascript
authenticatedTestEU.beforeEach(async ({ page, homePage, setCookies }) => {
  setCookies();
  await homePage.goto();
  await homePage.acceptCookies();
});
```  
What happens is that in my console (Terminal) I can see that my cookie is added, but when I run the test it looks like this - a blank page and is stuck there:  

![image](https://user-images.githubusercontent.com/6464981/177420356-34e4249f-0b0d-490d-a43a-5f256a014be0.png)  

The strange thing to me is that when I run the authenticatedTest for the US customer, then the browser has all the cookies loaded (I can see them in the Developer tools when I run the test). But when I print in the console `browserContext.cookies()` I don't see all of my app's cookies necessary for it to run - the ones I see in the Dev Tools. I can only see that the 1 cookie which I added is there, but the rest seems like they are not present. So I am a bit confused about how this works.  

My expectation would be once I use the `euCustomerStorageState,json`, then all my cookies are loaded for the app and I just need to set the correct cookie value for the app to switch to the EU mode.

Can you please help to identify what am I doing wrong?  
Thanks!

**Comment by sumanthpfs** [comment]
I'm having a similar issue too with authentication. I reuse a login state but after a day or it doesn't set the preset value to the cookie that was described in my storageState. Probably not related but sounded a bit similar

**Comment by rwoll** [comment]
It looks like you're setting cookies on the default fixture via `storageState`, but then are creating a new context (`browser.newContext()`) instead of amending the existing `context` fixture's cookies.

Try:

```ts
  setCookies: async ({ context, page, baseURL }) => {
    await context.addCookies([...await context.cookies(), {
        name: 'myCookie',
        value: 'myValue',
        url: baseURL
      }]);
    console.log(await context.cookies());
  },
```

Aside: if you don't want to manually call `setCookies`, you can mark `setCookies` as an [auto fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures) (but wait to try that until it works without it so you debug one thing at a time).

**Comment by mareru** [comment]
@rwoll Thanks again for your superpowers. :D    
Unfortunately, it didn't help. But I managed to figure it out.  
I didn't even need to set anything up manually. I suspected that there is something wrong with my  `./euCustomerStorageState.json` file.  
So I used this command:  
`npx playwright codegen --save-storage=euCustomerStorageState.json` 
to record my login with the EU customer (where I also changed the cookie value in the browser Developer Tools).  
I deleted setCookies entirely and I just used it like this:  
```javascript
export const authenticatedTestEU = authenticatedTest.extend<{}>({
  storageState: './euCustomerStorageState.json',
});
```  
And it worked! :D I reviewed the ./euCustomerStorageState.json and it contains this time all the needed cookies for my app to function.  
What is interesting those same cookies are not present in the `usCustomerStorageState.json` but the test somehow works with it. I wonder why is that so?  
One more question, how would you update the existing cookie value and not add a new one? For example, if I already have the `myCookie` in the storageState.json file and I want to update its value and not add a new one.   
Also, are auto fixtures also lazy or are they loaded no matter if the test uses them or not?

**Comment by rwoll** [comment]
> I deleted setCookies entirely and I just used it like this:

Sounds good—simple is better, so if you don't have to change any cookies at run time and just have a few state files, that's likely easier to debug.

> One more question, how would you update the existing cookie value and not add a new one?

```ts
// before this bar was set to `initial value`.
await context.addCookies([...await context.cookies(), { name: 'bar', value: 'overriden', url: 'https://example.com' }])
```

You can do something like above. i.e. put the similar cookie at the end if the array in `addCookies` that would override the original cookie coming from `...await context.cookies()`. Alternatively, do `const updatedList = await context.cookies()` and then find/update/delete the cookie in the `updatedList` list before calling `await context.addCookies(updatedList)` to set everything to the new value.

> Also, are auto fixtures also lazy or are they loaded no matter if the test uses them or not?

Auto-fixtures are not lazy. Automatic fixtures are set up for each test/worker, even when the test does not list them directly. (https://playwright.dev/docs/test-fixtures#automatic-fixtures) The not needing to list them makes them "auto".

**Comment by mareru** [comment]
@rwoll 
I have now an issue that the cookies for my user expire and I don't want to manually generate the storageSession.json each time. 
So, I need to do it programmatically.  
This is what I have in global-setup.ts file:  
```javascript
async function globalSetup(config: FullConfig) {
  await loginUS(config);
  await loginEU(config);
}

export default globalSetup;

async function loginUS(config: FullConfig<{}, {}>) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(config.projects[0].use.baseURL + urlPartData.login);
  console.log('Contexts YYY' + browser.contexts().length); // --> this is not empty but it doesn't contain all the cookie values that I would expect
  const context = browser.contexts()[0];
  console.log(await context.cookies());
  await page.fill('input[id="j_username"]', loginData.usCustomer.username);
  await page.fill('input[id="j_password"]', loginData.usCustomer.password);
  await page.click('#loginButton');
  console.log('XXX');
  console.log(await context.cookies());
  // Save signed-in state to 'usCustomerStorageState.json'.
  await page.context().storageState({ path: 'usCustomerStorageState.json' });
  await browser.close();
}

async function loginEU(config: FullConfig<{}, {}>) {
  const browser = await chromium.launch();

  const browserContext = browser.contexts()[0];
  const page = await browser.newPage();
  await page.goto(config.projects[0].use.baseURL + urlPartData.login);
  let updatedList = await browserContext.cookies();
  console.log(await browserContext.cookies()); // --> this is [] empty for some reason

  const url = config.projects[0].use.baseURL;

  const index = updatedList.findIndex((cookie) => cookie.name === 'myCookie');
  console.log('index = ' + index); // this is -1, IT DOES NOT FIND A VALUE in the list since it is empty
  console.log('Value before XXX ' + updatedList[index].value);
  updatedList[index].value = 'myValue';

  await browserContext.addCookies(updatedList);
  console.log(await browserContext.cookies());
  await page.fill('input[id="j_username"]', loginData.euCustomer.username);
  await page.fill('input[id="j_password"]', loginData.euCustomer.password);
  await page.click('#loginButton');
  // Save signed-in state to 'usCustomerStorageState.json'.
  await page.context().storageState({ path: 'euCustomerStorageState.json' });
  await browser.close();
} 
```  
My cookies for EU are empty for some reason. And what bothers me also is that the cookie list for the US doesn't contain `myCookie` which is needed for the app and for me to change it.  
Do you have any ideas on what could it be wrong?  
Thanks.

**Comment by rwoll** [comment]
```ts
async function loginUS(config: FullConfig<{}, {}>) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(config.projects[0].use.baseURL + urlPartData.login);
  console.log('Contexts YYY' + browser.contexts().length); // --> this is not empty but it doesn't contain all the cookie values that I would expect
```

Each time you call `const browser = await chromium.launch();` you're getting a fresh browser with basically no state. It's like downloading a new copy of the browser and installing it for the first time.

So, 

```ts
  console.log('Contexts YYY' + browser.contexts().length); // --> this is not empty but it doesn't contain all the cookie values that I would expect
```

The cookies you are seeing here, are just the cookies you get when you first go to `config.projects[0].use.baseURL + urlPartData.login` in the line before. It's like opening an incognito tab, going to that URL, and inspecting the cookies.

The same applies to your second snippet, but there you are likely going to a different URL that doesn't set cookies on your first visit.

> A [BrowserContext](https://playwright.dev/docs/api/class-browsercontext) is an isolated incognito-alike session within a browser instance. Browser contexts are fast and cheap to create. We recommend running each test scenario in its own new Browser context, so that the browser state is isolated between the tests.

More info here: https://playwright.dev/docs/browser-contexts#browser-context

It's not clear to me what the expectations are for each of these methods. 

Also, this line ` const browserContext = browser.contexts()[0];` looks little odd. Either access the context via `page.context()` or explicitly create it:

```
const browser = await chromium.launch();
const context = await browser.context();
const page = await context.newPage();
console.log(await context.cookies()); // This should be empty! We're in a fresh incognito-like profile!
```

**Comment by rwoll** [comment]
I've added some additional lines/comments to the example on https://playwright.dev/docs/test-auth#reuse-signed-in-state which hopefully help illustrate what's going on independent of your specific site's implementation:

```js
// global-setup.js
const { chromium } = require('@playwright/test');

module.exports = async config => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  console.log(await page.context().cookies()); // no cookies yet
  await page.goto('https://github.com/login'); 
  console.log(await page.context().cookies()); // maybe some cookies like tracking cookies, but not authentication cookie since we haven't logged in yet
  await page.fill('input[name="login"]', 'user');
  await page.fill('input[name="password"]', 'password');
  await page.click('text=Sign in');
  // Save signed-in state to 'storageState.json'.
  console.log(await page.context().cookies()); // we should no see auth cookies
  await page.context().storageState({ path: 'storageState.json' });
  await browser.close();
};
```

**Comment by mareru** [comment]
@rwoll Thanks for reaching out.  
Those 2 methods should try to do login for US and EU stores and save the cookies in the respective storgeState.json files.  
Like it is explained in the docs https://playwright.dev/docs/test-auth#reuse-signed-in-state as you mentioned.  

I am actually visiting the same URL all the time, but as I realize now (thanks to your explanation) I don't have those cookies loaded on that login page. I have to visit the home page first. So I will try to play with that.  

I am trying to call this method `globalSetup()` to be called once before my tests run so that it always creates storageState.json file with fresh cookies. That way I don't need to manually create storageState.json files each time my authentication cookie expires. 

Can you recommend any other better way to do it?

**Comment by mareru** [comment]
@rwoll It works finally.  
Hmm, the only thing I had to change was this:  
```javascript
 // global-setup.js
const { chromium } = require('@playwright/test');

const usLogin = async () => {
const browser = await chromium.launch();
  const context = await browser.newContext(); // create FRESH context 
  const page = await context.newPage();
  await page.goto('https://us.github.com/login'); // US URL
  await page.fill('input[name="login"]', 'user');
  await page.fill('input[name="password"]', 'password');
  await page.click('text=Sign in');
  await context.storageState({ path: 'us-storageState.json' });
  await context.close();
}

const euLogin = async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext(); // create FRESH context 
  const page = await context.newPage();
  await page.goto('https://eu.github.com/login'); // EU URL
  await page.fill('input[name="login"]', 'user');
  await page.fill('input[name="password"]', 'password');
  await page.click('text=Sign in');
  await context.storageState({ path: 'eu-storageState.json' });
  await context.close();
}


module.exports = async config => {
  // const browser = await chromium.launch();
  await Promise.all([euLogin(), usLogin()]);
  // await browser.close();
};
```  
It didn't like the fact to do it with the same browser instance.  
I wonder why? hmm
