### ISSUE TITLE
[BUG] Error when locating page element through Inspector

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#15398]
**Context:**
- Playwright Version: [1.23.0]
- Operating System: [Windows 11]
- Node.js version: [16.15.1]
- Browser: [Chromium]
- Extra: [Nothing]

**Code Snippet**

Provide me email address and I will send a har file and json file

```typescript
import { chromium } from '@playwright/test';

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
    ignoreHTTPSErrors: true, viewport: null,
    storageState: 'storageState.json'
  });
  const page = await context.newPage();
  await page.routeFromHAR("github.har.zip");
  await page.goto("https://www.haigeek.com/developercenter/static/develop.html#/")
  await page.pause()
  // Click Record And Locate Elements, Check console messages
  await context.close()
})();
```

**Describe the bug**

When I locate the element through the Inspector, I find that there are a lot of error messages in the console, and it is almost impossible to locate the element itself. This situation occurs in some pages. I also encountered this error message when I used playwright(java) 1.8. I suspect that the locator engine is in conflict with the non-standard html code, because I found that this page has the phenomenon of repeated id. It's worth mentioning that when I run the code after manually positioning the page element there is no error, the error only occurs in the record and explore functions.
![image](https://user-images.githubusercontent.com/23394317/177478063-f09c6897-91c2-475d-9928-34cde274e3fc.png)

**Comment by LongLiveY96** [comment]
> @LongLiveY96 feel free to send the har & json to `anlushni@microsoft.com`

I have sent the file, If you have other needs, please contact me

**Comment by aslushnikov** [comment]
I tried and it worked for me. I was able to generate some locators:

```js
Record




Target:

JavaScript

  // Click text=xt-指定开发者
  await page.locator('text=xt-指定开发者').click();
  // Click text=创建时间： 2022-07-06 10:02:09
  await page.locator('text=创建时间： 2022-07-06 10:02:09').click();
  // Click text=201405477994151414ee4bfbcec61f000000c4c14fe41f822af0a7ab79c1b140
  await page.locator('text=201405477994151414ee4bfbcec61f000000c4c14fe41f822af0a7ab79c1b140').click();
  // Click [placeholder="请输入功能集名称或typeID"]
  await page.locator('[placeholder="请输入功能集名称或typeID"]').click();
```

and page errors were website related; nothing like that `css.tokenize` error you have on your screenshot.

I'm running on Playwright 1.23.2 though; could you please try once again with it?

**Comment by LongLiveY96** [comment]
> @LongLiveY96 Thanks, I received the files.
> 
> However, I tried and it worked for me. I was able to generate some locators:
> 
> ```js
>   // Click text=xt-指定开发者
>   await page.locator('text=xt-指定开发者').click();
>   // Click text=创建时间： 2022-07-06 10:02:09
>   await page.locator('text=创建时间： 2022-07-06 10:02:09').click();
>   // Click text=201405477994151414ee4bfbcec61f000000c4c14fe41f822af0a7ab79c1b140
>   await page.locator('text=201405477994151414ee4bfbcec61f000000c4c14fe41f822af0a7ab79c1b140').click();
>   // Click [placeholder="请输入功能集名称或typeID"]
>   await page.locator('[placeholder="请输入功能集名称或typeID"]').click();
> ```
> 
> and page errors were website related; nothing like that `css.tokenize` error you have on your screenshot.
> 
> I'm running on Playwright 1.23.2 though; could you please try once again with it?

I upgraded @playwright/test to version 1.23.2, and recorded the entire operation process, the problem still recurs, I have sent the screen recording file to your email, if you have any other needs, please contact me.

**Comment by LongLiveY96** [comment]
After upgrage to 1.28, this issue is solved.

**Comment by LongLiveY96** [comment]
After upgrage to 1.28, this issue is solved.
