### ISSUE TITLE
[Question] I'm not able to reuse my login states after a day or two. Why is that?

### ISSUE THREAD

**Issue by sumanthpfs** [microsoft/playwright#15393]
I have a json file that stores a session that looks similar to this
{
  "cookies": [
    {
      "sameSite": "Lax",
      "name": "something",
      "value": "somthing",
      "domain": "localhost",
      "path": "/",
      "expires": 1656758325.827613,
      "httpOnly": true,
      "secure": false
    }
  ],
  "origins": [
    {
      "origin": "http://localhost:8000",
      "localStorage": [
        {
          "name": "last_known_organization_code",
          "value": "something"
        }
      ]
    }
  ]
}

When I store a context after a login through page api "await page.context().storageState({path: 'something'})" I can use this stored state fine for a while but after a day or two it doesn't work any more. I had to login and save a new context to reuse the state. Is there something I'm missing how do I reuse my stored state without having to login again after a day or two?

**Comment by rwoll** [comment]
I think this is the same question from here: https://playwright.slack.com/archives/CSUHZPVLM/p1657057316356429

The backend auth session associated with the cookie likely has an expiry on the backend. It's similar to how if you log in to your app on the browser, you'll be authenticated and able to do things in your app, but then after a few days, you might be prompted to sign in again.

**Comment by sumanthpfs** [comment]
yep, thanks for the info. So to work around this issue I would re-save the auth states periodically.
