### ISSUE TITLE
[Feature] is there a plan to support tauri ?

### ISSUE THREAD

**Issue by cnryb** [microsoft/playwright#15404]
tauri is an electron like framework ？ More info here https://tauri.app/about/intro

Is there a plan to support tauri ?

**Comment by aslushnikov** [comment]
@cnryb No, there are no plans to support Tauri at the moment. But nothing is set in stone, so if there's a huge demand, we might reconsider!

**Comment by cnryb** [comment]
@aslushnikov Thanks for your reply. How to know if the demand is huge?

**Comment by AlexanderYW** [comment]
+1 for this feature

@cnryb I assume we vote for the feature here
https://github.com/microsoft/playwright/discussions/14765

Or am i wrong @aslushnikov ? :)

**Comment by MikeJerred** [comment]
+1 for this. Not sure how difficult this would be to implement?

**Comment by asankeg2000** [comment]
+1 for this feature. More and more desktop apps will use Tauri.  HOw soon can we have this? Is there a place to vote?

**Comment by shipurjan** [comment]
+1 :)

**Comment by kurdin** [comment]
+1

**Comment by rkofman** [comment]
+1 Especially since there is Electron support, it would be wonderful to have Tauri as well -- it's taking over a growing mindshare of developers who target the desktop while using web technologies.
