### ISSUE TITLE
[BUG] onblur can not be used to detect popups or similar

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#15409]
**Context:**
- Playwright Version: 1.23.0
- Operating System: all
- Node.js version: all
- Browser: all

**Code Snippet**

`test.html`: 
```html
<body>
    <script>
    window.addEventListener("blur", () => {
        console.log(`blur window`);
        alert("blur window");
    })
    let el = document.createElement("iframe");
    el.srcdoc = `
    <body>
        <script>window.open("abc")<\/script>
    </body>
    `
    document.body.appendChild(el);
    </script>
</body>
```
Run: `playwright open test.html`

**Describe the bug**

The `blur` event usually can be used to detect whether any included resource opened a popup (or a download occurred).
In Playwright, this does not work as the pages are always focused see: https://github.com/microsoft/playwright/issues/11645
Detecting popups or downloads can be achieved using Playwright functions, however normal websites do not have these capabilities.

**Comment by aslushnikov** [comment]
> onblur can not be used to detect popups or similar 

@JannisBush This is intended, and the motivation was outlined in https://github.com/microsoft/playwright/issues/11645. 

> Detecting popups or downloads can be achieved using Playwright functions, however normal websites do not have these capabilities.

Since Playwright API is sufficient, what is the usecase that requires blur?

**Comment by JannisBush** [comment]
@aslushnikov 
The usecase is studying information leaks in browsers. What information can a website infer about included resources (such as an iframe opening a popup)? Such a website does not have access to the playwright API and I use playwright to open the test website thousands of times with different included resources.

**Comment by aslushnikov** [comment]
@JannisBush I see; this is quite far from the use Web testing use case we focus on right now! 

The best I can suggest is to fork playwright and remove the call to `Emulation.setFocusEmulationEnabled` call from `crPage.ts`.

**Comment by JannisBush** [comment]
@aslushnikov I understand that it is quite far from the main use case you are focusing on right now. It would, however, be nice to have a "pure" mode in the future that is better suited for testing browsers in their default configurations as installed by users :)

**Comment by aslushnikov** [comment]
We might focus on "pure" mode eventually! But there are no plans so far.

I'll close this since there's no action item on our side, and my triaging shift is over. Thank you for filing though! And please don't hesitate to file issues if something's off and not working.
