### ISSUE TITLE
[Question] How can I use firefox stable instead of nightly?

### ISSUE THREAD

**Issue by Quietscheentchen13** [microsoft/playwright#15406]
Hi,

after installing playwright (1.23.1) via the vscode extension ("Install Playwright") and configuring a firefox project in the config, I have the problem that the browser used is Nightly 100.0.2. In the docs its written that the firefox version matches the recent firefox stable build.

Maybe there is a missunderstanding on my side, but how can I make use of the firefox stable version instead of the nightly version?

Thanks in advance for any help.

**Comment by aslushnikov** [comment]
Hi @Quietscheentchen13,

The firefox & playwright release cadence got out of sync; current Firefox stable is available on tip-of-tree that you can install via `npm i @playwright/test@next` or `npm i playwright@next`

**Comment by Quietscheentchen13** [comment]
Hi @aslushnikov,

thanks for your fast reply and the explanation.
Should I close this "Issue"?

**Comment by aslushnikov** [comment]
I'll handle this :)

**Comment by Nisthar** [comment]
> I'll handle this :)

So there's no way to make playwright work with your stable firefox browser? I tried setting executablePath to my firefox browser, but it doesn't navigate at all.
