### ISSUE TITLE
[BUG] WebKit : Unacceptable TLS certificate                                                                                       │

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#15410]
**Context:**
- Playwright Version: >1.22
- Operating System: Ubuntu 18.04
- Browser: WebKit

**Code Snippet**

Run `npx playwright open --browser webkit https://example.org`
Observe:
```
: Unacceptable TLS certificate                                                                                       │
=========================== logs ===========================                                                         │
navigating to "https://example.org/", waiting until "load"                                                           │
============================================================                                                         │
    at captureRawStack (/data/data/webkit_test/node_modules/playwright-core/lib/utils/stackTrace.js:62:17) {         │
  name: 'Error'                                                                                                      │
}
```

**Describe the bug**

Opening any https site in WebKit on Ubuntu 18.04 crashes with `Unacceptable TLS certificate` starting with Version 1.22.0. For lower versions and other browsers everything works fine.
This bug seems related: https://github.com/microsoft/playwright/issues/9466

**Comment by aslushnikov** [comment]
I can repro. cc'ing @dpino and @yury-s

**Comment by mudit94** [comment]
I am facing the similar issue with webkit browser

**Comment by michaelworm** [comment]
I am facing a similar issue with webkit browser, but in a GitLab CI environment
