### ISSUE TITLE
[BUG]: popups aren't opened in headless mode for clicks on non button elements

### ISSUE THREAD

**Issue by thdk** [microsoft/playwright#15415]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Linux (ubuntu)
- Node.js version: 14.19.1
- Browser: Chromium

**Code Snippet**
Repro repo: https://github.com/thdk/playwright-headless-popup

**Describe the bug**
I think this issue is a duplicate of closed issue #12342

The problem seems to be that popups won't open in headless mode when they are not initiated from a `button` element.

This is probably by design. So I'm mainly writing this here as documentation.

**If your popup is not opening in headless playwright tests:**
Make sure the click event is on a `button`. 

```javascript
<button onClick={() => openPopup();}>click me</button>
```
Playwright seems not to open the popup in headless mode when a `div` element is clicked.

**Comment by aslushnikov** [comment]
@thdk is this headless browser only? Also, could it be a specific behavior of a library that summons the popup?

**Comment by thdk** [comment]
Hi @aslushnikov seems you are right. Playwright does handle popups correctly even when event is fired on a `div` element.
I have updated my repo with a test without react-googe-login component. That test runs without issues.

It was only an issue in headless browser. But I don't think this issue still belongs here.

Sorry for bringing this up.
