### ISSUE TITLE
[BUG] Playwright Debugger/Inspector Pauses at Nonexistent Breakpoints

### ISSUE THREAD

**Issue by chrstophr-wltrs** [microsoft/playwright#15423]
### System:
 - OS: Windows 10 10.0.19044
 - Memory: 16.58 GB / 31.75 GB
### Binaries:
 - Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.10.0 - C:\Program Files\nodejs\npm.CMD
 - VS Code: 1.68.1
### Languages + Frameworks:
 - Typescript: 4.6.2
 - @playwright/test: 1.22.2
### Configuration
`launch.json`:
```json
{
  "configurations": [
    {
      "name": "PW",
      "request": "launch",
      "runtimeArgs": ["run-script", "e2e:debug"],
      "runtimeExecutable": "npm",
      "skipFiles": ["<node_internals>/**"],
      "type": "node"
    }
  ]
}
```

`package.json`, in the `scripts` section:
```json
"e2e": "npm run playwright test -- --config=my-app/playwright.config.ts",
"e2e:ci": "cross-env CI=true npm run e2e",
"e2e:debug": "cross-env PWDEBUG=1 npm run e2e -- --project=chromium"
```

I've had to change some of the names, since the code I'm referencing is for work, and therefore confidential, but I've only changed the names that reference the app under test.

### Code

Because the behavior has to deal with breakpoints, it's easier to post a picture of the code as viewed from my IDE, rather than pasting the contents of that code as text.

![image](https://user-images.githubusercontent.com/29496790/177633251-043dd0e7-d5fe-4efb-8360-bba0f8bfdbb7.png)

Note that there is no breakpoint set at line 8, and that there _is_ a breakpoint set at line 23.

### Expected
When I launch the Playwright test runner under the above conditions, I would expect that the test would launch a headed Chromium browser and the Playwright Inspector helper utility. The runner would then execute the tests uninterrupted until reaching lines that have been marked with breakpoints in VS Code, where it would pause. 

When the runner is paused, I would expect that I can inspect the DOM using the Playwright Inspector, and continue uninterrupted execution of the test until I encounter the next breakpoint. I'd like to be able to continue execution either from the panel in the Inspector OR in VS Code, but as long as one of them is working, that would be fine.

### Actual
Everything works as described, _except_ that test execution pauses at line 8, despite no breakpoint being set in VS Code at that line. The Playwright Inspector will highlight line 8, and I can continue execution of the test using the debugging panel in the Inspector.

![image](https://user-images.githubusercontent.com/29496790/177632231-5536c786-6ee7-4dd9-a884-c7dbf44187d3.png)

Execution **_also_** pauses at the breakpoint on line 23, as would be expected. Interestingly, line 23 is _only_ highlighted in VS Code, and I can continue execution only by using the debugger panel in VS Code. This behavior (apart from the paused execution) would seem to be the inverse compared to when the runner pauses at line 8.

## Conclusion

This is an incredibly minor defect. It's not that hard to just click 'continue' in the Inspector debug panel, and the test execution doesn't pause when I run normal execution scripts during CI, so it only effects my troubleshooting and development process in a very minor way.

It's also entirely possible that this behavior is entirely intended, and that I've just misunderstood the differences and interactions between how to control the integrated PW debugger in contrast to VS Code's debugger.

**Comment by aslushnikov** [comment]
@chrstophr-wltrs So PWDEBUG=1 mode is not actually intended to be used together with VSCode. Could you please tell us why do you use it? What are the things that you like in PWDEBUG=1 mode that you're missing in vscode experience?

**Comment by chrstophr-wltrs** [comment]
> @chrstophr-wltrs So PWDEBUG=1 mode is not actually intended to be used together with VSCode. Could you please tell us why do you use it? What are the things that you like in PWDEBUG=1 mode that you're missing in vscode experience?

Oh! I had a situation where neither the VS Code or Playwright debugger was stopping at breakpoints in my code, so I pulled out all the stops, turned on all the flags I could find, just so that I could have _something_ actually stop at the breakpoints and I could check the values of variables.

Specifically from the Playwright Inspector, I like that I can write and debug selectors for Locators during a testing session, and PW will highlight all DOM elements that would be returned by the selector I'm currently working with. It's not a make-or-break situation, I can accomplish something very similar by navigating through the test flow myself in a clean Chrome instance, and opening up the dev tools. 

In my current situation, where I want to run headed tests in a manner that can be paused, monitored, and resumed with the VS Code debugger, would it be more appropriate to use `PWDEBUG=console` instead?

**Comment by aslushnikov** [comment]
> Oh! I had a situation where neither the VS Code or Playwright debugger was stopping at breakpoints in my code, so I pulled out all the stops, turned on all the flags I could find, just so that I could have something actually stop at the breakpoints and I could check the values of variables.

@chrstophr-wltrs This does sound like a bug in VScode debugger! Please file it next time to us so that we could take a look!

> Specifically from the Playwright Inspector, I like that I can write and debug selectors for Locators during a testing session, and PW will highlight all DOM elements that would be returned by the selector I'm currently working with. 

You actually get this behavior with VSCode Playwright extension as well; just start a debugging session and move the cursor over the locator to highlight it in inside the page: https://youtu.be/z0EOFvlf14U?t=399

> In my current situation, where I want to run headed tests in a manner that can be paused, monitored, and resumed with the VS Code debugger, would it be more appropriate to use PWDEBUG=console instead?

Just using the VSCode debugger together with Playwright extension should be enough!

**Comment by aslushnikov** [comment]
My triaging shift is over, so I'll close this. Please don't hesitate to file issues if something still doesn't work for you! Also, there's a huge community at https://aka.ms/playwright/slack that's happy to respond to questions :)

**Comment by chrstophr-wltrs** [comment]
Oh, yes! Sorry I didn't get back sooner, this is all really solid information. I'll adjust my npm scripts to focus specifically on just using the VS Code debugger, and if I'm still getting weird behavior, I'll create an issue for VS Code instead. Thanks for your help! :D
