### ISSUE TITLE
[BUG]check() method in Playwright Python is not working

### ISSUE THREAD

**Issue by soumya-kar** [microsoft/playwright#15420]
**Context:**
- Playwright Version:1.23, 1.22
- Operating System: [e.g. Windows]
- Python- 3.9.6
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
import time

from playwright.sync_api import Page

def test_check_checkbox(page: Page) -> None:
    page.goto("https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407")
    time.sleep(5)
    page.locator(get_days_locator("Monday")).check()
    assert page.locator(get_days_locator("Monday")).is_checked()

def get_days_locator(day):
    return f"//label[text()='{day}']/preceding-sibling::input"

**Describe the bug**

When I run the above code with Pytest. Browser gets launched. Url is loaded. After that, it just trying to check the checkbox but unable to do it. Doing retrying multiple times
E       retrying click action, attempt #14
E         waiting 500ms
E         waiting for element to be visible, enabled and stable
E           element is not stable - waiting...
E         element is visible, enabled and stable
E         scrolling into view if needed
E         done scrolling
E         performing click action
E         <label for="RESULT_CheckBox-8_1">Monday</label> intercepts pointer events
E       retrying click action, attempt #15
E         waiting 500ms

**Comment by rwoll** [comment]
In the error message above, the line that reads:

```
<label for="RESULT_CheckBox-8_1">Monday</label> intercepts pointer events
```

indicates there is an element on top of the `input` element that is being re-targeted when you click the label. This element is getting in the way of actually clicking the `input` element.

If you inspect the DOM of the sample page where that label element is, you'll see the "checkbox" is implemented like:

1. `<input …>` element with opacity zero
2. overlayed on that is `<label>` that has `::before` content of a square which is overlayed where the `<input>` would be if it wasn't `opacity: 0`.

Simplified, it's like: https://jsfiddle.net/12pdg56z/16/ (and if you change opacity of the actual input you can see it visually https://jsfiddle.net/0uxL2fez/).

Let me review with the team what the expected behavior here should be. As a workaround, for this specific element, you can set `force=True` as an argument of check which will disable some of the internal conditions.

**Comment by rwoll** [comment]
@aslushnikov I failed to reproduce via:

```ts
it.only('should check the box behind another element when using the label', async ({ page }) => {
  await page.setContent(`
    <style>
    input {
      opacity: 0;
      position: absolute;
    }

    #checkbox-label::before {
      content: "\\2610";
      position: absolute;
      top: 0;
      left: 0;
      font-size: 25px;
      line-height: 15px;
    }

    #checkbox-label {
      position: relative;
      padding-left: 1.5em;
    }
    </style>
    <input type="checkbox" id="agree" />
    <label id="checkbox-label" class="checkbox" for="agree">Agree?</label>
  `);

  await page.locator('label').check();
});
```

The above runs cleanly, so maybe I'm a bit off.

@aslushnikov Can you review? 

(`force=True` does workaround it for https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407, however.)

**Comment by rwoll** [comment]
Your selector `//label[text()='{day}']/preceding-sibling::input` is trying to directly click the `input` element which is behind the `label`. With this site's particular implementation of the multiple choice element, you'll need to call check on an element a user can click. In this case, it's the `label` which the site manipulates to overlay on top of the actual `input`.

With this, you won't need `force`. Change:

```py
def get_days_locator(day):
    return f"//label[text()='{day}']/preceding-sibling::input"
```

to:

```py
def get_days_locator(day):
    return f"//label[text()='{day}']"
```

or more idiomatically with Playwright, just do:

```py
page.locator('label', has_text='Monday').check()
```

The following works:

```py
with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context()
    page =context.new_page()
    page.goto('https://fs2.formsite.com/meherpavan/form2/index.html?1537702596407')
    page.locator('label', has_text='Monday').check()
    assert page.locator(get_days_locator("Monday")).is_checked()
```

Let us know if this makes sense!

Aside: Playwright has [auto-waiting built-in](https://playwright.dev/docs/actionability), so you shouldn't need `time.sleep`. And if you really _must_ have a sleep, use [`page.wait_for_timeout`](https://playwright.dev/docs/api/class-page#page-wait-for-timeout) instead.

**Comment by soumya-kar** [comment]
Hello,
Thank you for the prompt response and the detailed RCA.
I tried the above work arounds which you mentioned. It is working fine with those work arounds. 
But I feel Playwright could handle that gracefully. It prints infinite logs in console if I use my old code where it is interacting with the input tag. It should throw some error and stop the execution there. 
It would be great if that can be fixed.

Thanks again.
