### ISSUE TITLE
[Question] How to mock getAccessTokenSilently() from @auth0/auth0-spa-js

### ISSUE THREAD

**Issue by rmakovyak** [microsoft/playwright#15446]
Hi!

I have a setup where my SPA is only accessible for a user that has an open session at Auth0.
Upon load, the application is performing getAccessTokenSilently() and if it fails it redirects the user to the Auth0 Login page.

I don't want to write tests for auth0 login, as it is not the scope of my application. While I can mock HTTP requests, auth0 SDK is using iframe to retrieve the session cookie from the auth0 tenant to find out if it can request a token before any requests happen.

Here is more about silent auth: https://auth0.com/docs/authenticate/login/configure-silent-authentication

I figured this should be a common scenario, maybe someone has a solution for it already?

**Comment by aslushnikov** [comment]
@rmakovyak Unfortunately, I have no experience with auth0 and know nothing about silent auth you referred to.

Maybe you can ask this kind of question on our slack @ https://aka.ms/playwright/slack and see if anybody responds?

**Comment by aslushnikov** [comment]
My triaging shift is over, so I'll close this. Please don't hesitate to re-file and/or ask on slack any questions though!
