### ISSUE TITLE
[Question] FrameLocator.locator(....).press(...) or FrameLocator.locator().type(....) not working

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#15448]
Hi, I'm having issues while trying to use type or press function to a locator (a paragraph) inside an iframe. 
I don't think it is a selector problem since I can use the FrameLocator.locator(...).fill('whatever') function (or hover on the locator and finding it)  with any problem. I want to append some text to this existing paragraph but since fill() would clear all my text I don't know what to do... 

To be clearer, by debugging it, the actions after the type/press function would continue with no problems, but the type/press function would not type/press anything.

Ps. I am awaiting those functions, of course :)

Does someone else have this problem? :(

EDIT: I am trying different kind of keys, I am having issues mainly with Digit0- Digit9, KeyA- KeyZ keys, the other ones seem to work..

EDIT 2: in order to give you an example, I'm using CKEditor 4, and using this test should be enough to explain better my problem:

```
import { expect } from '@playwright/test';
import { test } from "@playwright/test";

test.beforeEach(async ({ page }) => {

    await page.goto('https://ckeditor.com/ckeditor-4/demo/#article');


});

test('try-editor', async ({ page }) => {
    const frame_locator = page.frameLocator('.cke_wysiwyg_frame.cke_reset');
    await frame_locator.locator(':nth-match(p,1)').click({ position: { x: 0, y: 0 } });
    await frame_locator.locator(':nth-match(p,1)').press('Control+A');
    await frame_locator.locator(':nth-match(p,1)').press('Backspace');
    await frame_locator.locator(':nth-match(h2,1)').press('A');
    await expect(frame_locator.locator(':nth-match(h2,1)')).toHaveText('A');

});
```

Hoping you can reproduce this, pressing Control+A or Backspace work with no problems, the A does not work..

**Comment by DvDream** [comment]
Hi, any ideas?

**Comment by yury-s** [comment]
You send keyboard events to ':nth-match(p,1)' which  `<h2>` inside the content editor. The actual element which handles the events as far as I can tell is the body element (`'[aria-label="Editor, ckdemo"]'`) so the keyboard events end up being dispatched on a different element than they would be if the user was typing in the browser (they would go to document.activeElement which is the editor element). You can change your code the following way to first pass focus into the editor and let it adjust it accordingly and after that use [`page.keyboard`](https://playwright.dev/docs/next/api/class-page#page-keyboard) to send keyboard events to the currently focused element.

```js
  await page.goto('https://ckeditor.com/ckeditor-4/demo/#article');
  const frame_locator = page.frameLocator('.cke_wysiwyg_frame.cke_reset');
  await frame_locator.locator(':nth-match(p,1)').click({ position: { x: 0, y: 0 } });
  await page.keyboard.press('Control+A');
  await page.keyboard.press('Backspace');
  await page.keyboard.press('A');
  await expect(frame_locator.locator(':nth-match(h2,1)')).toHaveText('A');
```

**Comment by DvDream** [comment]
Thank you man, I appreciate your help and explanation!
