### ISSUE TITLE
[Question] How can i update playwright in my docker container?

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15444]
Hello, i'm trying to update playwright in my docker container, but using command like npx install playwright-1.23.0 or npm playwright --version 1.23.0 isnt working.

**Comment by NicoloLattanzio** [comment]
How should i update the version in the docker file? Like i changed it in the package.json, but then it doesnt do the make all-up, it gives an error: failed to solve: executor failed running [/bin/sh -c mkdir -p /playwright-browsers     && npx playwright install --with-deps chromium     && chown -R node:node /tester]

Like he cant install playwright anymore

**Comment by aslushnikov** [comment]
My triaging shift is over, so I'll close this. If things still don't work for you, please feel free to re-file or post your questions on our slack: https://aka.ms/playwright/slack !
