### ISSUE TITLE
[Feature] Add way to access the default context

### ISSUE THREAD

**Issue by Jamesernator** [microsoft/playwright#1544]
I would like to be able to optionally show automation that's happening with the browser, however without access to the default context this tends to look kinda messy as the default context sits in the background.

It'd be nice if we could get the default context so we can control it, e.g. `browser.defaultContext()` or by including it in `browser.contexts()`.

**Comment by dgozman** [comment]
Would [launchPersistent()](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsertypelaunchpersistentcontextuserdatadir-options) work for you?

**Comment by pavelfeldman** [comment]
>  default context sits in the background.

are you on 0.11? It does not sit there in 0.12!

**Comment by Jamesernator** [comment]
> are you on 0.11? It does not sit there in 0.12!

Yes, 0.12 solves the problem.
