### ISSUE TITLE
[BUG] Component testing vue doesn't work with only a <template> tag

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#15449]
**Context:**
- Playwright Version: "@playwright/experimental-ct-vue": "^1.23.1", & "@playwright/test": "^1.23.1",
- Operating System: All
- Node.js version: v17.3.0
- Browser: All

**Code Snippet**
Version that does not work:
https://github.com/sand4rt/playwright-component-testing-vue-issues/blob/master/src/components/ComponentWorksNot.test.ts

Version that does work: https://github.com/sand4rt/playwright-component-testing-vue-issues/blob/master/src/components/ComponentWorks.test.ts

**Describe the bug**

Component testing vue doesn't work with only a template tag

**Comment by aslushnikov** [comment]
(cc'ing @pavelfeldman)
