### ISSUE TITLE
[Feature] Hide sensible data in the html report

### ISSUE THREAD

**Issue by ugioni** [microsoft/playwright#15453]
I would like to have the possibility for some hooks (before, before all, before each) to be hide inside the html report, this is useful to guarantee security in some situations.

**Comment by p01** [comment]
What kind of sensible data do you in mind ? Anyhow, this sounds like something that must be handled by using test accounts and data to make sure that you don't run against "real" company or customer data.

**Comment by aslushnikov** [comment]
My triaging shift is over, so I'll close this. If you still have questions, please re-file or reach out on slack - https://aka.ms/playwright/slack !
