### ISSUE TITLE
[Question]Is it possible to locate the first adjacent div element in an html file based on the element of the previous div?

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#15480]
If I want to locate the <div role="listbox" id="ipsec_policy_pfs_list"> element in the screenshot to the <div class="rc-virtual-list"> below, how should I locate it?
![image](https://user-images.githubusercontent.com/9427959/177910835-1f9dfd71-c41e-4de5-a712-746d28337cda.png)

**Comment by ltsuda** [comment]
You can use the CSS adjacent combinator selector, which selects the first adjacent element after another element.

**example:**
css selector: `div + div` will find the first adjacent `div` (+ div) from the left div element.

Note that as the example selector is very broad, it would find all elements matching this combination.

To be more specific with the screenshot, something like `div#ipsec_policy_pfs_list + div.rc-virtual-list` could work. But it will find more than one element if there are more with this combination.

If you want to use XPATH selectors, you could take a look at the `following-sibling`.

`//div[@id='ipsec_policy_pfs_list']/following-sibling::div`
`//div[@id='ipsec_policy_pfs_list']/following-sibling::div[@class='rc-virtual-list']`

Resources:
- CSS
https://developer.mozilla.org/en-US/docs/Web/CSS/Adjacent_sibling_combinator
https://www.w3schools.com/cssref/sel_element_pluss.asp
- XPATH
https://www.w3schools.com/xml/xpath_axes.asp
https://devhints.io/xpath

**Comment by god-pane** [comment]
thx
