### ISSUE TITLE
[BUG] Can't use the mask function while screenshotting

### ISSUE THREAD

**Issue by NicoloLattanzio** [microsoft/playwright#15485]
Hello, i'm trying to hide an image while screenshotting a page, but the mask functions isnt working, i wrote this:

await page.screenshot({path: BuildPath("ScreenshotAPP",language,"LavagnaFornitore","lavagnaf")},{mask:"body >div.wrapper > img"});

**Comment by NicoloLattanzio** [comment]
So i should pass him an array with the string inside?

**Comment by NicoloLattanzio** [comment]
I wrote this:
await page.screenshot({path: BuildPath("ScreenshotAPP",language,"LavagnaFornitore","lavagnaf")},{mask:[page.locator("body > div.wrapper > img")]});

But isnt working

**Comment by MindaugasMateika** [comment]
are you getting an error? it's not clear what is not working
