### ISSUE TITLE
[Question] how to install playwright in Azure pipelines

### ISSUE THREAD

**Issue by doublesweet01** [microsoft/playwright#15484]
I need to run the playwright test in pipelines, but it keeps reporting an error that the npx installation failed.

I read the official website about the code for configuring playwright in pipelines, and there is a lot of code omitted in the middle, can you elaborate on how each step is implemented? Just like the GitHub Actions example.

I know the step is：
npx playwright install-deps

But I don't know how to write in pipelines

**Comment by aslushnikov** [comment]
@doublesweet01 i think this is more a "how do I use Azure Pipelines" question rather than a Playwright question. Please ask this on our slack channel instead: https://aka.ms/playwright/slack 

Folks from Playwright community are very friendly and are happy to help!
