### ISSUE TITLE
[Feature] Mismatch version error message in gitlab ci

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15483]
After updating playwright to 1.23.0 I had the following error in my CI
```
browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1012/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     npx playwright install                                              ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

and thats cool! But what could be even cooler is:

```
browserType.launch: Executable doesn't exist at /ms-playwright/chromium-1012/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just updated to 1.23.0                            ║
    ║ Please update docker image from current playwright:v1.22.0-focal
    ║ to playwright:v1.23.0-focal as well             ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

I failed to find this message in the source code, so I cannot contribute this feature.

**Comment by Diokuz** [comment]
Also, in the doc playwright docker image version is 1.23.1, but on docker hub is 1.23.0

[docker pull mcr.microsoft.com/playwright:v1.23.1-focal](https://playwright.dev/docs/docker)

[docker pull mcr.microsoft.com/playwright:v1.23.0-focal](https://hub.docker.com/_/microsoft-playwright)

**Comment by aslushnikov** [comment]
> But what could be even cooler is:

@Diokuz Fair! 

> Also, in the doc playwright docker image version is 1.23.1, but on docker hub is 1.23.0

I see all of the following on docker hub:

```
$ docker pull mcr.microsoft.com/playwright:v1.23.0-focal
$ docker pull mcr.microsoft.com/playwright:v1.23.1-focal
$ docker pull mcr.microsoft.com/playwright:v1.23.2-focal
```

**Comment by vekunz** [comment]
Can you please fix this issue? It is very annoying that we cannot update Playwright anymore.

**Comment by aslushnikov** [comment]
> Can you please fix this issue? It is very annoying that we cannot update Playwright anymore.

@vekunz This issue is purely about proper error message; if you cannot update Playwright somehow, please file a separate issue!

**Comment by vekunz** [comment]
> > Can you please fix this issue? It is very annoying that we cannot update Playwright anymore.
> 
> @vekunz This issue is purely about proper error message; if you cannot update Playwright somehow, please file a separate issue!

I thought this issue is about the problem, that the Docker images do not work anymore since version 1.23.0, because of the first error message above.
