### ISSUE TITLE
[Feature] Allow to modify the device scale factor

### ISSUE THREAD

**Issue by AmitMY** [microsoft/playwright#15494]
Relates to the closed issue, https://github.com/microsoft/playwright/issues/3828

#### Use case:
I am taking hundreds of screenshots w/ playwright. 
For performance reasons (each page takes 5 seconds to fully load, due to machine learning being performed in it), I am attempting to consolidate my screenshots, and after load, modify the `setViewportSize` to different devices sizes (`load`=10 seconds, `setViewportSize`=0 seconds)

#### Current missing support:
Unfortunately, different devices require different `deviceScaleFactor`, which is not currently modifiable on the fly. In order to emulate a different screen, I need to create a new context, and open a new page.

#### Request:
Similar to `setViewportSize`, please include a `setViewportDeviceScaleFactor` method to modify on the fly

**Comment by aslushnikov** [comment]
@AmitMY on average, creating a new context & page inside of it is very fast; the majority of time is spent navigating the page. 

Changing device scale factor on the fly is not possible: at the very least, it will require page reload, so it's unlikely to save any time.

**Comment by AmitMY** [comment]
If it is not possible without a reload, then what i want to do is not possible. unfortunately, due to machine learning and stuff, it takes 10 seconds to fully load the page i want to screenshot
