### ISSUE TITLE
[BUG] Trace flag does not apply to headless

### ISSUE THREAD

**Issue by clabough** [microsoft/playwright#15497]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Windoes
- Node.js version: 16.15.1
- Browser: All

## System:
 - OS: Windows 10 10.0.19044
 - Memory: 8.75 GB / 31.93 GB
## Binaries:
 - Node: 16.15.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.16 - C:\Windows\system32\bash.EXE

**Code Snippet**

```
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./tests/global-setup'),
  testDir: './tests',
  timeout: 120 * 1000,
  expect: {
    timeout: 5000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [ ['html', { open: 'never' }] ],
  use: {
    actionTimeout: 0,
    trace: 'on',
    storageState: 'storageState.json',
    headless: true
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],
};

export default config;

```

**Describe the bug**

When running `npx playwright test`, the trace file does not get generated, but I set `headless: false`, it does for each browser. It would be nice if this would work, but if it will not, then the documentation should be updated to note this.

**Comment by mxschmitt** [comment]
Trace files should be generated on both, headless and headed browser instances. Do you have a repro which you can share so we can dig into it more?

**Comment by yury-s** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
