### ISSUE TITLE
Browser.ConnectOverCDPAsync open a new InPrivate Window[BUG]

### ISSUE THREAD

**Issue by knowwhythat** [microsoft/playwright#15492]
**Context:**
- Playwright Version: 1.23
- Operating System: Windows
- .NET version: .NET 6
- Browser:  Chromium
- Extra: no

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```cs
using System.Threading.Tasks;
using Microsoft.Playwright;

class Program
{
    public static async Task Main()
    {
      using var playwright = await Playwright.CreateAsync();
            var browser = await playwright.Chromium.ConnectOverCDPAsync("ws://127.0.0.1:9222/devtools/browser/5ae5ad41-c3a7-4e4f-98d4-eaeab578b17a",
                new BrowserTypeConnectOverCDPOptions() { Timeout = 10000 });
            var context = await browser.NewContextAsync();
            var page = await context.NewPageAsync();
            await page.GotoAsync("https://www.bing.com");
    }
}
```

**Describe the bug**

code above open a new InPrivate Window,but i donot want the InPrivate pattern

**Comment by yury-s** [comment]
You can get access to the existing [contexts](https://playwright.dev/dotnet/docs/next/api/class-browser#browser-contexts) and create a page in one of them. If the browser was launched in the persistent mode, one of the contexts will be persistent context.

**Comment by sontiq** [comment]
> You can get access to the existing [contexts](https://playwright.dev/dotnet/docs/next/api/class-browser#browser-contexts) and create a page in one of them. If the browser was launched in the persistent mode, one of the contexts will be persistent context.

can you please show the code that  can solve the problem?
