### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by AbhijitBiradar** [microsoft/playwright#15509]
Does playwright support mobile and tablet? Can we execute script in mobile and iPad?

**Comment by Meir017** [comment]
related #15504

**Comment by AbhijitBiradar** [comment]
Thanks for your reply. Link is informative.

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/issues/15509#issuecomment-1179668457.

Thanks @Meir017
