### ISSUE TITLE
[Question] How to add new mobile devices to emulate

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#15504]
I am trying to use the mobile device emulation feature. There is a good list of devices I can emulate, but there are a few I would like to emulate that aren't in the library. Is there a way to manually add them, or can that only be done by the Playwright team?

For reference, I was wanting to emulate the top-ten best selling smartphones, but I couldn't find most of the Android ones on the list. https://appleinsider.com/articles/22/06/22/apple-sold-five-of-the-top-ten-smartphones-in-april-2022

**Comment by Meir017** [comment]
see the file https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json.

you can just create your own overrides

```json
{
    "userAgent": "Mozilla/5.0 (PlayBook; U; RIM Tablet OS 2.1.0; en-US) AppleWebKit/536.2+ (KHTML like Gecko) Version/15.4 Safari/536.2+",
    "viewport": {
      "width": 600,
      "height": 1024
    },
    "deviceScaleFactor": 1,
    "isMobile": true,
    "hasTouch": true,
    "defaultBrowserType": "webkit"
  }
```

instead of using the provided devices by playwright you can supply your own configuration for the device - https://playwright.dev/docs/next/test-configuration#emulation

**Comment by mxschmitt** [comment]
Closing as per above. A device is just a combination out of context options.

If you are interested in contributing a new device to Playwright, you can do it here: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json

**Comment by eatonjl** [comment]
Thanks for the answer! Sorry I did not respond earlier. I went out of town after posting this question. Most of what to put in for a new device seems pretty straight forward besides the userAgent. How do we know what to put for that?

**Comment by mxschmitt** [comment]
For userAgents either you have access to the specific device or you use Google aka a user agent database to find out what user agent it has.

e.g. https://developers.whatismybrowser.com/useragents/parse/294137safari-ios-ipod-webkit

**Comment by eatonjl** [comment]
@mxschmitt Thank you!
