### ISSUE TITLE
[Question] How can i hide keyboard of Android on Android tests ?

### ISSUE THREAD

**Issue by hudsonxhenrique** [microsoft/playwright#15505]
I'm doing tests in a website using an Android device using Chrome.
But i'm stuck on screen because the button what i need to click has been covered by the keyboard.

How can i hide or close the keyboard of Android ?
I was trying these codes below:

`await page.press(locator, 'Escape');`
`await page.keyboard.press('Escape');`
`await device.shell('input keyevent 111');`

But i don't have sucess with them.

Anyone have an solution for this ?

![2022-07-08 17_53_52-Window](https://user-images.githubusercontent.com/23124589/178070923-a86ea236-5584-4dfa-8300-47c817242be8.png)

**Comment by yury-s** [comment]
> But i'm stuck on screen because the button what i need to click has been covered by the keyboard.

There is no special support in playwright for that, running the adb command that you mentioned (`await device.shell('input keyevent 111');`) should in theory do the trick. With that said [`locator.click()`](https://playwright.dev/docs/next/api/class-locator#locator-click) will automatically scroll the button into view before clicking it so the soft keyboard on the screen should not prevent the click. Would that work for you or you don't want the page to be scrolled?

**Comment by hudsonxhenrique** [comment]
> > But i'm stuck on screen because the button what i need to click has been covered by the keyboard.
> 
> There is no special support in playwright for that, running the adb command that you mentioned (`await device.shell('input keyevent 111');`) should in theory do the trick. With that said [`locator.click()`](https://playwright.dev/docs/next/api/class-locator#locator-click) will automatically scroll the button into view before clicking it so the soft keyboard on the screen should not prevent the click. Would that work for you or you don't want the page to be scrolled?

The button I need to click is at the bottom of the page. Therefore, the page does not allow the implicit scroll in the "click()" method to display the button.

**Comment by yury-s** [comment]
> The button I need to click is at the bottom of the page. Therefore, the page does not allow the implicit scroll in the "click()" method to display the button.

At least in that case playwright is doing the right thing - a human user would not be able to click the button either without hiding the keyboard. This is not to say that there should not be a way to hide the keyboard.

**Comment by hudsonxhenrique** [comment]
> > The button I need to click is at the bottom of the page. Therefore, the page does not allow the implicit scroll in the "click()" method to display the button.
> 
> At least in that case playwright is doing the right thing - a human user would not be able to click the button either without hiding the keyboard. This is not to say that there should not be a way to hide the keyboard.

Ok, I get it.

**Comment by yury-s** [comment]
Closing this issue as there is no planned action on the playwright end.
