### ISSUE TITLE
Playwright test case on Azure pipeline, Locally runs without any error

### ISSUE THREAD

**Issue by muttukk** [microsoft/playwright#15502]
I am trying to write a e2e test case for an angular application using Playwright.It runs without any error in dev environment, but it fails when I run the pipeline.

Pipeline logs:
  
    page.check: Target closed
  =========================== logs ===========================
        waiting for selector "input[name="buyerRadio"]"
        ============================================================
    
      at D:\a\r1\a\e2e-playwright\e2e-playwright\src\tests\sampleTest.spec.ts:23:14[22m
      at D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\workerRunner.js:388:9[22m
      at TestInfoImpl._runFn (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\testInfo.js:166:7)[22m
      at D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\workerRunner.js:344:26[22m
      at TimeoutManager.runWithTimeout (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\timeoutManager.js:70:7)[22m
      at TestInfoImpl._runWithTimeout (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\testInfo.js:154:26)[22m
      at WorkerRunner._runTest (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\workerRunner.js:326:5)[22m
      at WorkerRunner.runTestGroup (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\workerRunner.js:195:11)[22m
      at process.<anonymous> (D:\a\r1\a\e2e-playwright\node_modules\@playwright\test\lib\worker.js:87:5)[22m 

    
   Below is Azure set up to run the Playwright
  
 Context:
    

    Playwright Version: 1.23.0
    Operating system :- Windows 2019
    Node version :- 12.16.0
    Extra: running Azure Pipeline

  Azure Pipeline: Added below Task to the azure agent.I added the YAML details of the task.
```

    steps:

      -task: NodeTool@0
      displayName: 'Use Node 12.16.0'
      inputs:
        versionSpec: 12.16.0

    steps:

    script: |
       
       call npm install
       call npm install -D @playwright/test
       call npx playwright install
       call set PLAYWRIGHT_JUNIT_OUTPUT_NAME=results.xml
       call set base_url=https://branch_url_hidden
       call npx playwright test --reporter=junit
      workingDirectory: '$(System.DefaultWorkingDirectory)/test-playwright'
      displayName: 'Run Playwright'
```

 TestCases: Below are the test cases I am trying to run:

    
   ```
 import { test, expect} from '@playwright/test';

// this test works well locally , failes in pipeline
    test("Sample test",async({page})=>{
      const id =123456;
      const baseUrl: string = process.env['base_url'] || 'https://test_env_url_hidden_security_purpose';
      const testLink :string= baseUrl + '/dashboard/Id/'+id;
      console.log(testLink); //I checked the url from pipeline, it loads without any error
      //go to test page
      await page.goto(testLink)
      await page.waitForNavigation();
      // Check text=Buyer input[name="buyerRadio"]
      await page.check('input[name="buyerRadio"]');
      // Continue button
      await page.click('button[qaid="apc-continue-button"]');
      await page.close();
    });
    
    // this test case pass in local and poipeline without any error
    test("testing addition",()=>{
    let x=2,y=2;
    let result=x+y;
    expect(result).toEqual(4);
    });
```

**Comment by mxschmitt** [comment]
We recommend following debug guide: https://playwright.dev/docs/next/debug

This means:
1. Setting `DEBUG=pw:api` env var
2. Enabling traces

Also keep in mind, that your Node.js version is not supported, we recommend 16+.

**Comment by muttukk** [comment]
Thank you @mxschmitt , yeah i updated my node version to 16 & used ignoreHTTPSErrors: true which solved my problem in azure pipeline
