### ISSUE TITLE
如何让playwright连接到已打开的浏览器

### ISSUE THREAD

**Issue by jiangyijin** [microsoft/playwright#15515]
我是这样操作的

首先在cmd中运行这个：
chrome.exe --remote-debugging-port=9222 --user-data-dir="D:\新建文件夹"

然后再使用下面的代码连接：

`from playwright.sync_api import sync_playwright

u = 'https://www.baidu.com/'
sy = sync_playwright()
qd = sy.start()
bo = qd.chromium.connect("http://localhost:9222")
pg = bo.new_page()
pg.goto(u)
bo.close()
qd.stop()
`

但是会报一个这样的错：
playwright._impl._api_types.Error: websocket.connect: http://localhost:9222 isn't a valid URI: scheme isn't ws or wss

请问这该如何去解决？

**Comment by aslushnikov** [comment]
Please re-file in english!
