### ISSUE TITLE
[Question] How to run the test suite in different  environments  like local, dev, st,int and sit environments, Also credentials differ with respect to environment.

### ISSUE THREAD

**Issue by Kapil-Anandagiri** [microsoft/playwright#15517]
Note - Need to use dotenv and crossenv , Have to set the credentials in encrypted format.

**Comment by aslushnikov** [comment]
@Kapil-Anandagiri The general advise is to expose all the sensitive information with environment variables and configure local, dev and other environments with necessary variables.

So what exactly is the question?

**Comment by Kapil-Anandagiri** [comment]
Problem statement : 
3 environments available,  against each environment and project , have to execute playwright test. My objective is to retrieve credentials and baseurl from .env file.

**Comment by aslushnikov** [comment]
> Since credentials are sensitive information have to encrypt and decrypt, so Is playwright has inbuilt functionality to encrypt ?

@Kapil-Anandagiri No, there's no built-in functionality to encrypt

> To retrieve the env variables , configured in the playwright config file and try to retrieve using global setup, but unfortunately playwright not able to sense the env variable, so please suggest a way to move further.

Please show us what you do and how it doesn't work!

> Based on projects my baseurl often has to be amended, without using test.use ,shall we able to change the baseurl ? Is there a way to group the test and for particular group will use my preferred baseurl.

You can group them via `test.describe` and use `test.use()` inside the describe to override the URL.

**Comment by ortoniKC** [comment]
> Queries
> 
> 1. Since credentials are sensitive information have to encrypt and decrypt, so Is playwright has inbuilt functionality to encrypt ?
> 2. To retrieve the env variables , configured in the playwright config file and try to retrieve using global setup, but unfortunately playwright not able to sense the env variable, so please suggest a way to move further.
> 3. Based on projects my baseurl often has to be amended, without using test.use ,shall we able to change the baseurl ? Is there a way to group the test and for particular group will use my preferred baseurl.

You can refer to this video to handle multiple env's
https://youtu.be/GQStVI5qbLI

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
