### ISSUE TITLE
[Question] How to get a reminder/alert when a new version is released

### ISSUE THREAD

**Issue by jithintill** [microsoft/playwright#15513]
Is there a reminder/alert we can get through email when a new main version is released eg: when 1.24 is released, 1.25 is released

Just to make sure that we are updating the package to get the latest browsers

**Comment by rwoll** [comment]
As of now, you can either follow the project on Twitter (https://twitter.com/playwrightweb), or you can Watch/Subscribe to the Repository on GitHub (and subscribe to just the Release notifications):

<img width="368" alt="Screen Shot 2022-07-10 at 1 11 38 PM" src="https://user-images.githubusercontent.com/11915034/178160615-29178d2b-26e1-42ed-962c-95db46294753.png">

**Comment by jithintill** [comment]
thanks
