### ISSUE TITLE
[BUG] yarn install playwright - infinite loading

### ISSUE THREAD

**Issue by Orilow** [microsoft/playwright#15523]
**Context:**
- Playwright Version: 1.19.1 in package.json
- Operating System: macOs **M1**
- Node.js version: 16.16.0
- HomeBrew version: 3.5.4
- Extra: [any specific details about your environment]

**Code Snippet**

![image](https://user-images.githubusercontent.com/32433465/178212471-ad0c6aa3-f18f-4bef-bfb6-4ab7a763ff8c.png)

**Describe the bug**

My `yarn install` is breaking after running on macOS M1 - it goes infinite load.
After research I thought it was node-gyp and tried this, as was said here (https://github.com/HashLips/hashlips_art_engine/issues/1220)
`arch -arm64 brew install pkg-config cairo pango jpeg giflib librsvg` but i doesnt help. so i dont eevent know where is the problem, because on screenshot i already use verbose.
what do you think, where i should dig?

**Comment by mxschmitt** [comment]
Playwright does not depend on node-gyp, so it has to be another dependency of your project which causes that!

I recommend digging into yarn.lock/package-lock.json to find out who depends on node-gyp.
