### ISSUE TITLE
[Question] Is it possible for page.routeFromHAR or browserContext.routeFromHAR to block specific resource types?

### ISSUE THREAD

**Issue by marcm099** [microsoft/playwright#15530]
Currently exploring the great new record har and replay har feature.
The problem I am facing is we use web sockets which always reload data from the api after the mocked out data, so i was wondering of there was a way to block certain resource types, e.g. websockets, images etc?

I have tried to  "trick" Playwright. y recording a har with only graphql responses then adding graphql and ws to the routeFromHAR call, e.g.:
 context.routeFromHAR('example-fail.har', { url: '(**/graphql**)|(ws:*)' });

example of ws url:  wss://b795de93ffc0.ws.bebbf0793f07.551762560152.example.com/

Thank you

Marc

**Comment by yury-s** [comment]
WebSocket interception is currently not supported (and har depends on the network interception feature internally). The feature is tracked in https://github.com/microsoft/playwright/issues/4488, please thumb it up to help us prioritize it.

To block certain resource requests you can use regular request interception. You can also combine it with routeFromHar, e.g.:

```js
  await context.routeFromHAR('example-fail.har', { url: '(/graphql)|(ws:*)' });
  // Abort all image requests but continue normal flow for others:
  await context.route('**/*', route => {
    if (route.request().resourceType() === 'image')
      route.abort();
    else
      route.fallback();
  });
```
