### ISSUE TITLE
[BUG] Hardware Acceleration is not being turned on for headless Chromium

### ISSUE THREAD

**Issue by nate-blum** [microsoft/playwright#15533]
**Context:**
- Playwright Version: 1.23.2
- Operating System: Ubuntu/Windows
- Node.js version: 16
- Browser: Chromium
- Extra: Running both locally on my machine and remotely from an Ubuntu Github Action, neither works

```typescript
import { chromium } from '@playwright/test';

(async () => {
        const browser = await chromium.launch({
            args: [
                '--use-gl=egl',
                '--ignore-gpu-blocklist',
                '--use-angle=angle',
            ],
        });
        const context = await browser.newContext();
        const page = await context.newPage();
        await page.goto('chrome://gpu');
        await page.pdf({
             path: 'flags.pdf',
        });
        await browser.close();
})();
```

I've tried `--use-gl=egl`, `--use-gl=desktop`, and `--use-gl=swiftshader` to no avail. Every time, the pdf shows Software only, hardware acceleration unavailable. At this point I suspect it may be some issue with my laptop's hardware but I don't know exactly how to find this out. Additionally, I believe that my issue lies somewhere with '--ignore-gpu-blocklist', since this flag is remaining disabled even when I include it, which leads me to believe that something is forcing my GPU to not provide hardware acceleration. My laptop's GPU is an Nvidia 2060 if that helps, although my code doesn't work when run remotely through a GitHub Action either.

Here's a pastebin with the results from chrome://gpu as-is: https://pastebin.com/U6m0pcjY  
Here's one with the results after adding --disable-software-rasterization: https://pastebin.com/uDfQuqQq  
Any help is greatly appreciated!

**Comment by yury-s** [comment]
The support varies depending on the hardware that you have. Also it will use hardware acceleration only when run under x11 server so I believe it won't work on GitHub Actions as they run in headless mode. To make it work, you need to pass the following flags (no use-angle):

```js
        const browser = await chromium.launch({
            args: [
                '--use-gl=egl',
                '--ignore-gpu-blocklist',
            ],
        });
```

**Comment by nate-blum** [comment]
Unfortunately, using just those flags didn't enable it either. Also, my laptop is definitely capable of hardware acceleration, since normal Google Chrome does have it enabled. It's only headless mode where it doesn't work. Let me know if any more info is required, thank you!

**Comment by yury-s** [comment]
Hw acceleration in headless is quite finicky. You can open an upstream chromium bug at https://crbug.com for your problem as this is a browser feature and we can't do much about it on the playwright end.

**Comment by yury-s** [comment]
Closing this bug as there is no action to be done in playwright.
