### ISSUE TITLE
[Question] Using global-setup for parametrization 

### ISSUE THREAD

**Issue by kbowles393** [microsoft/playwright#15539]
Hi all, 

I've been trying for a while to figure out a way to dynamically parametrize tests from user input, and I think I'm close but not quite there yet. I am currently using a global-setup file to set env variables that contain an array of test cases, and want to use that array to parametrize the tests, much like you would a CSV. I am currently not able to use a CSV to parametrize tests, and using projects does not allow tests to be dynamically generated.

The issue that I am running into is the env variables are not accessible in a test.describe() hook - as an example:
```
test.beforeEach(async ({ page }) => {
  const { INPUT } = process.env;
  processedInput = JSON.parse(String(INPUT));

  await page.goto(processedInput.url);
});

// for each test case in the processedInput.tests array, run a test
test.describe("parametrized tests", () => {
  const { INPUT } = process.env; // <-- line A
  processedInput = JSON.parse(String(INPUT));

  for (const testCase of processedInput.tests) {
    test("parametrized test name", async ({ page }) => {
      // do some tests
    });
  }
});
```

However currently playwright says there are no tests found since { INPUT } is not accessible in test.describe.

I have also tried using test.beforeAll() to define { INPUT } and assign it to a global variable, but playwright (presumably) checks the processedInput array in the for loop first, sees that it's empty, and concludes that there are no tests without running test.beforeAll(). 

At line A, I checked the output of process.env which contained typical env variables but did not contain INPUT (which I set in the globalSetup property).

Any help/advice/workarounds would be greatly appreciated!

**Comment by kbowles393** [comment]
> @Daemos87 Thank you for the example, it makes sense.
> 
> Unfortunately, this is not supported and I do not see an easy way to support it. Two available workarounds for you:
> 
> 1. Instead of using `test.describe` and multiple `test` blocks, make a single `test` that uses the fixture. You can check each element in the for loop. We are looking into adding [`test.step` API](https://github.com/microsoft/playwright/issues/7254) so that you can have multiple steps in a single test - in your case that would be one step per element.
> 2. Put your database code into [global setup file](https://playwright.dev/docs/test-advanced#global-setup-and-teardown) to execute it once. You can do whatever you want in the global setup phase. In this particular case, I'd store the data in some file or env variable, and then create multiple tests by reading from the file/env in your `describe` block.

https://github.com/microsoft/playwright/issues/7482#issuecomment-875868308

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/12857, please thumb up that issue to help us prioritize it.

For the time being I suggest you generate the tests suites before running playwright test as described in https://github.com/microsoft/playwright/issues/12857#issuecomment-1071204950
