### ISSUE TITLE
[Feature] Test suite scoped fixtures

### ISSUE THREAD

**Issue by aolanrewaju** [microsoft/playwright#15542]
We use a shared page/frame in our test suites and are trying to use fixtures to abstract some of the boilerplate code that happens in our test hooks. Using a shared frame makes this tricky.

Ideally we would want something  like this 

```
//hooks.ts
import {test as base} from "@playwright/test"

const test = base.extend<{frame:Frame}>({
    frame: [async ({ browserName }, use) => {
       await use(await createFrame(browserName)));
    }, {scope: "suite"}],
});

test.afterEach(async ({ frame }) => {
    tearDownTest(frame)
 });

test.afterAll(async ({ frame }) => {
    tearDownSuite(frame)
});
export default test
```
```
//myTest.ts
import test from "./hooks.ts"
let sharedFrame:Frame

test.describe("sample test", () => {

  test.beforeAll(async ({ frame }) => {
    //more test setup with frame
   
  });

  test("RenameTest", async ({frame}) => {
    //test using frame
  });
});
```

Where the frame fixture in the afterAll, afterEach, test, etc are the same rather than it creating a new frame every time the fixture is called. Could this be something you support?

**Comment by yury-s** [comment]
Can you tell us more [`{ scope: 'worker' }`](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) type of fixture wouldn't work in this scenario? It is created once per test worker similar to built-in browser fixture and meets all the requirements that you listed.

**Comment by aolanrewaju** [comment]
I'm not exactly sure how the workers are assigned but for it to work in this use case we would need 1 worker per test file. Is this the functionality of worker already?

**Comment by aolanrewaju** [comment]
To be clear after reading the documentation [here](https://playwright.dev/docs/test-parallel#worker-index-and-parallel-index), Each worker will/can run multiple test files but the worker should be restarted before running each new file and will be assigned a new worker index to showcase this (while the parallel index stays the same). Is it correct that a worker fixture will then be run once per parallel index and thus once per file? (assuming theres no failures)

**Comment by yury-s** [comment]
Closing the issue as there is a solution for the described problem and we don't have immediate plans to implement such scope for the fixtures. We'll keep collecting feedback on the feature and if there is enough interest we may add it in the future.
