### ISSUE TITLE
[Question] About mocking HTTP requests and the HAR file (Migration from Cypress to Playwright)

### ISSUE THREAD

**Issue by SirMishaa** [microsoft/playwright#15553]
Hello! 

First, I want to say that I love this test library, it's amazing the work behind it.

For work, I am in the process of converting some of our Cypress tests into Playwright tests, with a much more modern approach.
For context, it's just a silly Vue application, with lots of HTTP calls to API.

**The old Cypress test and mocking structure is as follows:** 

- The routes are defined in the entry point of the tests via the` cy.route` method
```ts
  cy.server()
  cy.route('POST', '/ardor/tracker', 'fx:tracker/create')
  cy.route('POST', '/ardor/gamification', 'fx:gamification/create')
  cy.route('PUT', '/ardor/wins', 'fx:wins/update').as('putWin')
  cy.route('GET', '/ardor/sw/risk_objects', 'fx:risk_objects/index').as('getRiskObjects')
  cy.route('GET', '/ardor/sw/users/search?q=*', 'fx:users/search_tiny')
  cy.route('GET', '/ardor/sw/users/search?q=*&format=standard', 'fx:users/search_standard')
  cy.route('GET', '/ardor/sw/motorbike_manufacturers', 'fx:motorbike_manufacturers/index')
  cy.route('GET', '/ardor/sw/products?locale=*', 'fx:products/show').as('getProducts')
  // ..... a lot of routes
```

In parameter order, we have method, URL like, and the fixture to be loaded.
That is, we have a fixture folder that contains folders for each URL, for example ` accident_records

This folder contains one JSON file per HTTP method that the Vue application does.
![image](https://user-images.githubusercontent.com/42717232/178401223-488f6f34-1669-4a9d-889a-b68f2b2f07ec.png)

The JSON file just contains an arbitrary valid response. 
So automatically, when one of the **defined URLs is matched during an HTTP request**, Cypress will automatically load the corresponding file that contains the answer and return this result.

**In relation to this, several questions:** 

- Is this approach appropriate for Playwright? 
- Is there a better way than doing this (while keeping the response JSON files) 

Actually, I have started a basic homepage test and I'm recording HTTP request to Har file : 
```ts
test.describe('Basic homepage test', () => {
  test('should display the homepage', async ({ browser }) => {
    const browserContext = await browser.newContext({
      recordHar: { path: path.join(process.cwd(), 'e2e/shared/homepage.har'), urlFilter: 'https://*********/**' }
    })

    const page = await browserContext.newPage()

    await page.goto('http://localhost:3000')
    const title = await page.title()
    expect(title).toBe('Ardor Test')

    // Click text=Bienvenue, Tester@seraphin
    await page.locator('text=Bienvenue, Tester').click()
    // Click h2:has-text("📊 Mon funnel de vente")
    await page.locator('h2:has-text("📊 Mon funnel de vente")').click()
    await page.pause()
    await browserContext.close()
  })
})
```

So, I have, indeed, queries that are well registered, as [said in the documentation](https://playwright.dev/docs/network#recording-har-with-a-script).

Now, I don't really understand what to do next? I don't know what approach to take

My idea was to use `page.route` from Playwright and to make a loader in the global-setup file that automatically loads all the responses in memory. Then, when the request is match, use ``fulfill`` and load the appropriate response.

But it's a bit annoying because I'll have to make my own method for that and import it into the test files (which is not really a problem) because Playwright doesn't seem to offer that.

I have thinking of something like that for the implementation : 
```ts
/***
 * Retrieve the appropriate mocked response for the given request.
 * @param {Request} request
 */
export async function loadAppropriateResponse(request: Request) {
  const httpFixtures: Record<string, any> = {}; // Imagine here a store of HTTP responses mapped like {url: {method: { ...(response) }}

  // This is just an example here, we need to do some transformation for url, not with regex
  const url = request.url().replace(/^http:\/\/localhost:3000/, '') // accident_records

  const associatedFixture = httpFixtures.url ?? {}

  const response: Record<string, any> | undefined = associatedFixture?.[request.method().toLowerCase()] // Return the first response for the method depend on the request url
  return response
}
```
Usage could be : 
```ts
await page.route('**/ardor/aircall/calls', async (route, request) => {
      await route.fulfill({
        status: 200,
        body: JSON.stringify(await loadAppropriateResponse(request))
      })
    })
```

But by doing it my way, the using of Har files become useless.
Here it is, sorry for this long message.

I hope to have some help on the suitable way to mock HTTP requests.

Thanks a lot !

**Comment by yury-s** [comment]
> Now, I don't really understand what to do next? I don't know what approach to take

In v1.23 we introduced [context.routeFromHar](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har) which is intended to be used in network replay scenarios like you described, it will automatically find the best match for a request (based on the url, method and headers) and serve it from the har file. After recording the har file you can actually make your network requests served from it like this:

```js
test.describe('Basic homepage test', () => {
  test('should display the homepage', async ({ browser }) => {
    const browserContext = await browser.newContext()
    await browserContext.routeFromHAR(path.join(process.cwd(), 'e2e/shared/homepage.har'))
   // ... same code as when you were recording the har file.
  })
})
```

By default playwright will write all network data into a single har file. If you want to keep storing data for different urls in separate files you can use multiple `routeFromHar` calls with [update](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har-option-update) option and different [url filters](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har-option-url). After running the test first time and saving the data to the files remove the `update` option and it will be replayed from the har files:

```js
  await browserContext.routeFromHAR('tracker/create.har', { url: '**/ardor/tracker', notFound: 'fallback', update: true });
  await browserContext.routeFromHAR('gamification/create.har', { url: '**/ardor/gamification', notFound: 'fallback', update: true });
  await browserContext.routeFromHAR('wins/update.har', { url: '**/ardor/wins', notFound: 'fallback', update: true });
...
```

You can also combine routeFromHAR with page.route and fulfill some of the requests manually while letting the others to be handled by routeFromHAR.

There is also a short [video](https://www.youtube.com/watch?v=NRGOV46P3kU&t=129s) giving a short overview of reouteFromHar feature which may be helpful.
