### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by DiogoLopes99** [microsoft/playwright#15558]
In my application, there is a scrollable element, which contains a list of elements that the user can click. The Trace Viewer doesn't show  which of those elements was clicked. I see the red dot that represents the click, but it isn't on top of the element that was actually clicked, because the container element wasn't scrolled to the correct position in the Trace Viewer. See the image below.
![image](https://user-images.githubusercontent.com/58359122/178457511-b2acf167-db44-40b0-bc8a-69f7fd8ae6c8.png)
![image](https://user-images.githubusercontent.com/58359122/178457629-d727b32e-bcce-41f6-8fc9-895fc97f5862.png)

I actually have to scroll it myself, looking for the correct element that was clicked. It would be helpful if the container element started in the correct scroll position, so that we are able to see which element was clicked more easily. In my case, I think this should be the default scroll position to be shown in the Trace Viewer:
![image](https://user-images.githubusercontent.com/58359122/178457919-0b0a1914-a67f-4af4-82dd-6ea317eb866f.png)

**Comment by yury-s** [comment]
Can you attach example trace or share a reproducible example where we can record it?

**Comment by DiogoLopes99** [comment]
Yeah sure, I can attach example trace. May I ask for a private email or something where I can send it to? I would prefer to not to put it here

**Comment by DiogoLopes99** [comment]
Ok, done!

**Comment by yury-s** [comment]
@DiogoLopes99 Thanks for the trace, I can see locally that the sidebar is not scrolled to the selected element. Trace recorder failed to save the scroll position to the trace file. We need access to the page where this happens to debug the recorder. Can you share a page with such sidebar?

**Comment by DiogoLopes99** [comment]
Done, sent it to you email :)

**Comment by yury-s** [comment]
Thanks for sharing! I tried recording similar [trace.zip](https://github.com/microsoft/playwright/files/9202833/trace.zip) with that page and a simple test below but the problem doesn't reproduce (everything scrolls as expected). Can you try locally finding a page where the bug could be reproduced?

 ```js
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:9080/');
  await page.locator('text=SCROLL TEST - Federation 2').click();
  await page.locator('#mat-checkbox-5798 >> text=SCROLL TEST - Federation 1').click();
});
```

**Comment by DiogoLopes99** [comment]
Thanks for your help.
I asked internally, but my PM said that for now we can't spend more time on this.
Again, thank you for your help.

**Comment by yury-s** [comment]
Thanks for taking time to send the repro! We need more information to act on this report. Please file a new one and link to this issue if you have a chance to get back to it!
