### ISSUE TITLE
[BUG] 'console' events sometimes missed on Firefox

### ISSUE THREAD

**Issue by ozyx** [microsoft/playwright#15550]
**Context:**
- Playwright Version: 1.23.2
- Operating System: Mac/Linux
- Node.js version: 16.16.0
- Browser: Firefox
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.4
 - Memory: 40.59 MB / 16.00 GB
## Binaries:
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Describe the bug**

In some situations, `page.on('console')` fails to trigger when using Firefox.

In our case, we have a custom test fixture which is listening to 'console' events and failing any tests which produce console errors:
https://github.com/nasa/openmct/blob/8e322ee0009eac600bd3f5421a7c7e0c966a8ec4/e2e/fixtures.js#L48

```js
/* ... */
    page: async ({ baseURL, page }, use) => {
        const messages = [];
        page.on('console', (msg) => messages.push(msg));
        await use(page);
        messages.forEach(
            msg => expect.soft(msg.type(), `Console error detected: ${consoleMessageToString(msg)}`).not.toEqual('error')
        );
    },
/* ... */
```

We also have framework tests which **pass** when run with Firefox:
https://github.com/nasa/openmct/blob/8e322ee0009eac600bd3f5421a7c7e0c966a8ec4/e2e/tests/framework.e2e.spec.js#L32

```js
const { test } = require('../fixtures.js');

test.describe('fixtures.js tests', () => {
    test('Verify that tests fail if console.error is thrown', async ({ page }) => {
        test.fail();
        //Go to baseURL
        await page.goto('/', { waitUntil: 'networkidle' });

        //Verify that ../fixtures.js detects console log errors
        await Promise.all([
            page.evaluate(() => console.error('This should result in a failure')),
            page.waitForEvent('console') // always wait for the event to happen while triggering it!
        ]);

    });
/* ... */
```

But in other tests that hook into 'console' events, the events are never triggered (on Firefox only). The same tests pass on chrome and chrome-beta channels.

See here for the test in question: https://github.com/nasa/openmct/blob/8e322ee0009eac600bd3f5421a7c7e0c966a8ec4/e2e/tests/plugins/plot/missingPlotObj.e2e.spec.js#L35

**Things I've tried**:
- Registering `page.on('console')` in the `beforeEach` hook
- Extending the `page` in `fixtures.js` with a list of all console messages received and then filtering within the test itself (works on chrome/chrome-beta but not Firefox)
- Registering `page.on('console')` after the `page.reload()`
- Calling `page.waitForEvent('console')`, this causes the test to time out
- Upgrading to 1.23.2

However, If I explicitly call `page.evaluate(() => console.warn('Some warning'))` within the test, the event is caught and handled properly.

Any idea on what could be happening here? I saw a couple Firefox-specific issues related to console events, but upgrading to 1.23.2 did not seem to resolve this one. Any advice you can provide is greatly appreciated.

**Comment by yury-s** [comment]
I can reproduce it with the test that you refer to. The warning message is there in the Firefox devtools console but not triggered on the playwright end (there is no `Runtime.console` in the DEBUG=pw:protocol logs).

@aslushnikov can you have a look?

**Comment by yury-s** [comment]
@ozyx can you provide a reduced test case where a console message is missing, the test in the project is quite big and would take us more time to reduce it given that we are unfamiliar with the app?

**Comment by ozyx** [comment]
@yury-s 

Yup totally understand. I'll try to put together a smaller repro example over the next week or so. It's crunch time right now so I haven't had much time to distill the issue, but I wanted to raise it now in case anybody had any insight into what could be happening here.

Thanks for the quick response!

**Comment by aslushnikov** [comment]
@ozyx first are foremost and until we have a repro: could you please also try installing tip-of-tree:

```bash
$ npm i @playwright/test@next
$ npx playwright install firefox 
```

And see if it works? If it doesn't, then also (using that same @playwright/test@next):

```bash
npx playwright install firefox-beta # should download Firefox-Beta 103
```
and then use `"firefox-beta"` as a "`channel`" argument in `firefox.launch({ channel: 'firefox-beta' })` ?

**Comment by ozyx** [comment]
@aslushnikov Thanks! I gave both of those options a try and I'm still seeing the same behavior.

**Comment by aslushnikov** [comment]
@ozyx I'll move this to the next release. Any chance you can come up with a shorter repro?

**Comment by ozyx** [comment]
@aslushnikov 

Hi Andrey. Here's a shorter repro I was able to put together: https://github.com/ozyx/playwright15550-firefox-missed-console-error

**Comment by yury-s** [comment]
> Hi Andrey. Here's a shorter repro I was able to put together: https://github.com/ozyx/playwright15550-firefox-missed-console-error

The page in that project doesn't print anything to the console. Did you mean a different page?

**Comment by ozyx** [comment]
@yury-s:

In the project I am specifically trying to capture the `console.error()` [thrown by the server itself](https://github.com/ozyx/playwright15550-firefox-missed-console-error/blob/1613038eb2ace2464e3cb74768e516495e04d15d/index.js#L11), as this is the simplest way to illustrate the issue we are having with Firefox not capturing these events when they are being thrown by our app. However, even if performed by the `page` itself within the test via `page.evaluate()`, we did notice that Firefox failed to capture this as well.

Hope that helps, please let me know if I can provide any further clarification.
