### ISSUE TITLE
[Feature] Debugability: log everything from the browser when test fails

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15567]
Some context: we have a HUGE problem with our old tests, which relies on some network access. Nowadays we have to move to the new CI infra, which have some stronger network restrictions. So, a lot of our tests in CI are failing just because load event never happen (because some requests pending forever)

```
 Timeout of 30000ms exceeded.
    page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "http://localhost:3000/iframe.html?id=dolyame-forms--primary", waiting until "load"
    ============================================================

```

but we dont see why. Screenshot and video – both are cool, but not helping in this case anyway.

It would be supercool to have everything from **DevTool Console** and everything from **DevTool Network** (maybe HAR?) for every failed test.

**Comment by Diokuz** [comment]
Now we have to run every test locally and then add some code like this: 
```
test('testname', async ({ page, storybook }) => {
  await page.route('**/no_access_domain.com/**', route => route.fulfill({
    status: 403,
  }));

  ...

```

PS: we have > 10 000 tests

**Comment by yury-s** [comment]
Did you try recording a trace as described [here](https://playwright.dev/docs/trace-viewer#recording-a-trace) ? It contains both console messages and network data among other things.

**Comment by Diokuz** [comment]
Wow! You guys awesome!

But one small problem remains: there is no pending request in the Trace viewer → Network tab. Could you please add any network activity, not just completed?
<img width="1247" alt="1" src="https://user-images.githubusercontent.com/2929442/178666967-d651781e-aed0-4c3a-8bf2-dd003827be4e.png">

**Comment by Diokuz** [comment]
One more thing: it would be cool to list **all** network activity and all browser console.logs at once, not just what happend during the current action. That is not a good practice, but sometimes we have >300 actions per test.

**Comment by anru** [comment]
Also, there is no information about network request was rerouted ( by page.route for example ) or not

**Comment by yury-s** [comment]
>  Could you please add any network activity, not just completed?

Filed https://github.com/microsoft/playwright/issues/15690 for this

> One more thing: it would be cool to list all network activity and all browser console.logs at once, not just what happend during the current action. That is not a good practice, but sometimes we have >300 actions per test.

We can add a separate view for that. Feel free to file a feature request for that.

> Also, there is no information about network request was rerouted ( by page.route for example ) or not

@anru please file a separate feature request for that.
