### ISSUE TITLE
[Question] How to pass a dynamic variable from one test case to other test cases in Suite

### ISSUE THREAD

**Issue by dushyantjoshi23** [microsoft/playwright#15569]
Need to automate a scenario where a dynamic variable need to passed from one test case to another test case. For example - OrderId need to be passed to other test cases . How can we achieve it as the values stored in local storage will be auto deleted on opening new browser window for new test case.

**Comment by yury-s** [comment]
You can run related tests in [serial mode](https://playwright.dev/docs/test-retries#serial-mode) and similar to how page is shared in [this example](https://playwright.dev/docs/test-retries#serial-mode) read some values in first test and save them in a variable on node.js side to later pass it to the page in subsequent tests:

```js
test.describe.configure({ mode: 'serial' });

let sharedVar;
test('first', async ({ page }) => { 
  sharedVar = await page.evaluate(() => readYourVariable());
  //...
});
test('second', async ({ page }) => {
  await page.evaluate(v => setYourVariable(v), sharedVar);
  //...
});
test('third', async ({ page }) => {
  await page.evaluate(v => setYourVariable(v), sharedVar);
  //...
});
```
