### ISSUE TITLE
[BUG] Webkit mouse wheel scrolling not working in headless mode

### ISSUE THREAD

**Issue by ivy-lli** [microsoft/playwright#15566]
**Context:**
- Playwright Version: 1.23
- Operating System: Linux
- Node.js version: 16.15.0
- Browser: WebKit
- Extra: headless

**Code Snippet**

I've created a small test for this:

```typescript
test('webkit scroll headless', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const getStartBtn = page.locator('.getStarted_Sjon');
    await expect(getStartBtn).toBeVisible();
    const bounds = await getStartBtn.boundingBox();
    await page.mouse.wheel(0, 100);
    const scrolledBounds = await getStartBtn.boundingBox();
    expect(bounds!.y).not.toEqual(scrolledBounds!.y);
});
```

with the config:

```typescript
let config: PlaywrightTestConfig = {
  use: {
    // headless: false,
    browserName: 'webkit'
  }
};
```

**Describe the bug**

The mouse wheel scrolling seems to be defect in the webkit headless mode. If I run the above test with chromium or firefox it works in headful and headless mode. With webkit it only works in the headful mode.

**Comment by yury-s** [comment]
The test is actually flaky, it fails every second run for me on chromium macos with the error below. Do you have a standalone example where the scroll issue can be reproduced?

```

   Expected: not 322


       8 |   await page.mouse.wheel(0, 100);
       9 |   const scrolledBounds = await getStartBtn.boundingBox();
    > 10 |   expect(bounds!.y).not.toEqual(scrolledBounds!.y);```

**Comment by aslushnikov** [comment]
Speculatively assigning to Yury so that it doesn't fall through the cracks!

**Comment by ivy-lli** [comment]
Thanks a lot for your work! Playwright is an awesome piece of software 🎉
