### ISSUE TITLE
[Question] screenshot lighthouse report fails.

### ISSUE THREAD

**Issue by janwillemwilmsen** [microsoft/playwright#15573]
Hi, 
I have a local install of Lighthouse to test urls on my machine. I used Playwright to loop through multiple urls and create screenshots of the results. For some reason the results of Lighthouse scan aren't in the screenshot, the header and footer are. When using the web.dev Lighthouse scan I also get the same result (missing report but header and footer are visible in screenshot). 
I can't figure out what is causing the screenshot to miss the report section. Is Lighthouse blocking automated screenshots? or is there something wrong with the script?

Below is my script. Added timeouts, changed screenshot filetype, added some css and added scrolling to bottom of the page thinking that might have an effect, but it didn't. Hope this question isn't against the rules or that it should be on stackoverflow. 
I am on Windows 10, have  @playwright/test 1.23.1, playwright-chromium 1.23.1, playwright-core 1.23.1 installed.

<pre>
const { url } = require('inspector');
const playwright = require('playwright-chromium');
const projectName = 'webdev'
const apiUrl = "https://web.dev/measure/?url="
const siteList = [{ "id": 1, loc: "https://www.essent.nl/klanten" }, { "id": 2, loc: "https://www.essent.nl" }, { "id": 3, loc: "https://www.essent.nl/klanten/thuisvoordeel" }];
const siteLoop = async(url) => {
    for (const browserType of[playwright.chromium]) {

        const browser = await browserType.launch({ headless: false, slowMo: 250 });
        const context = await browser.newContext({
            // viewport: { width: 1100, height: 1100 },
            setDefaultTimeout: { timeout: 500000000000 }
        });

        const page = await context.newPage({
            // viewport: { width: 1100, height: 1100 },
            setDefaultTimeout: { timeout: 500000000000 }
        });;

        for (const url of siteList) {
            resultAction = apiUrl + url.loc
            console.log('webdev?testurl:', resultAction)
            try {
                await page.goto(resultAction);
                await page.waitForTimeout(800);
                await page.click('text=Run Audit');
                await page.waitForTimeout(80);

                const orderSent = page.locator('text=Generated by Lighthouse 9.6.2', { timeout: 5000000 });
                await orderSent.waitFor();

            } catch {
                // console.log('error')   // After timeout Playwright will continue with next url.
                await page.goto('https://i.stack.imgur.com/6M513.png')
            }

            await page.evaluate(async() => {

                // add inline element 'sticker with BETA + date'
                const selector = 'body'

                var today = new Date();
                var date = today.getFullYear() + '-' + (today.getMonth() + 1) + '-' + today.getDate();

                const newDiv = document.createElement("div");
                newDiv.innerHTML = `<div style='background:red;
                                                color:white;border-radius: 100%; 
                                                padding-top:35px;  
                                                margin: auto; 
                                                text-align: center; 
                                                font-size:20px;  
                                                z-index:9999999; 
                                                position: fixed; 
                                                width:100px; 
                                                height:100px; 
                                                top:40px; 
                                                right:40px;'>
                                        BETA 
                                        <br> 
                                        <span style="font-size:10px;">${date}</span>
                                    </div>`;

                const currentDiv = document.querySelector(selector);
                currentDiv.prepend(newDiv);

                // Set z-index on resultelement on webdev + Set important. 
                const resultdiv = '.lh-report'
                const resbg = document.querySelector(resultdiv);
                resbg.style = `z-index:99999999;color:blue !important; display:block !important;`
            });

            /// wait and scroll and repeat:
            await page.waitForTimeout(80);

            await page.evaluate(async() => {
                window.scrollTo(0, document.body.scrollHeight / 10);
            })
            await page.waitForTimeout(50);

            await page.evaluate(async() => {
                window.scrollTo(0, document.body.scrollHeight / 3);
            })
            await page.waitForTimeout(50);

            await page.evaluate(async() => {
                window.scrollTo(0, document.body.scrollHeight / 2);
            })

            await page.waitForTimeout(159);

            await page.evaluate(async() => {
                window.scrollTo(0, document.body.scrollHeight * 0.8);
            })
            await page.waitForTimeout(200);

            await page.evaluate(async() => {
                window.scrollTo(0, document.body.scrollHeight);
            })

            await page.waitForTimeout(89);

            // await page.evaluate(_ => {
            //     window.scrollTo(0, 0);
            // });
            await page.waitForTimeout(169);

            // convert url to filename for screenshot:
            const fileName = url.loc.replace(/\//g, '-');
            const fileName2 = fileName.replace(/\:/g, '-');
            const fileName3 = fileName2.replace(/%20/g, '-');

            console.log(fileName3)

            // create and save screenshot in folder:
            // await page.screenshot({ path: testorproduction + `${fileName3}.jpeg`, fullPage: true, quality: 30, type: 'jpeg' });
            await page.locator('body').screenshot({
                path: `./export/${projectName}/screenshots/lighthouse/` + `${fileName3}.png`,
                fullPage: true,
                type: 'png'
            });
        }

        await browser.close();
    }
}

siteLoop(siteList)

// ();
</pre>

**Comment by yury-s** [comment]
Please file a new bug with a reduced scenario and refer to this issue, otherwise it's hard to understand what's going on and what is not working (I tried to run your code but it fails with the below exception). I see that you are taking `fullPage: true` screenshots, note that the parts outside of the visible viewport may be rendered lazily by chromium and could be blank on the screenshot in that case.

```
page.evaluate: TypeError: Cannot set properties of null (setting 'style')
    at eval (eval at evaluate (:178:30), <anonymous>:25:29)
    at UtilityScript.evaluate (<anonymous>:180:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
    at siteLoop (/Users/yurys/sandbox/pw/test.js:38:24)
```
