### ISSUE TITLE
[Question] Arguments for string script when using evaluate

### ISSUE THREAD

**Issue by Samat-Imamov** [microsoft/playwright#15579]
Hi, I have a small question. I'd like to pass a string that contains script code to page's evaluate function as well as arguments. How can I refer to those arguments inside the string script? Trying to read "arguments" doesn't work. Thanks!

**Comment by yury-s** [comment]
Can you share example of the script that you'd like to pass?

Assuming that you can change your script to a function you can do something like this:

```js
  await page.evaluate(({a, b}) => a + b, {a: 1, b: 2});
```
If you have your function defined as a string you can call with arguments in the page like this:

```js
  const script = '(a, b) => a + b';
  // Create function in the page by evaluating the script.
  const functionHandle = await page.evaluateHandle(script);
  // Call the function with two arguments.
  const result = await page.evaluate(({fn, x, y}) => fn(x, y), {fn: functionHandle, x: 1, y: 2});
```
Alternatively, you can serialize the arguments to string and wrap the script in a function call like this:

```js
  const script = '(a, b) => a + b';
  // Call the script with 2 args.
  const callWithArgs = `(${script})(1, 2)`;
  const result = await page.evaluate(callWithArgs);
  console.log(result);
```
Does it address your use case?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
