### ISSUE TITLE
[BUG] Inconsistency with recordHar/routeFromHar with 304s

### ISSUE THREAD

**Issue by muryoh** [microsoft/playwright#15571]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Linux
- Node.js version: 14.6
- Browser: Chromium

**Describe the bug**

Hi there! Thanks for the great HAR based replay feature
It's exactly what I needed in the context of a support feature in a product I'm working on, where we want to be able to capture and replay a page to reproduce and fix issues

I did notice what I believe to be a problem though - 304 are not really handled. In my case, this happens because I'm basically opening multiple tabs on different pages loading up common resources.

What I'm experiencing is the following
```
1. 1st request on bundle.js file => 200 + content + etag
2. 2nd request on bundle.js file with `if-none-match` specified to previous etag => 304
```

The problem I can see is that the 2nd request has no chance of being replayed properly with the [current logic](https://github.com/microsoft/playwright/blob/f76fb3e08a8a8ade5dcd2b434f9e563d72fd3b5d/packages/playwright-core/src/server/dispatchers/localUtilsDispatcher.ts#L206), because 304s are not followed (_another problem I'm having is that even the first request isn't replayed properly, because the [disambiguation](https://github.com/microsoft/playwright/blob/f76fb3e08a8a8ade5dcd2b434f9e563d72fd3b5d/packages/playwright-core/src/server/dispatchers/localUtilsDispatcher.ts#L227) probably doesn't work here and playwright ends up replaying the 304)_

**Workaround**

Just for reference, I'm working around this issue by overriding the `if-none-match` header in the `extraHTTPHeaders` of the browser context:
```
    extraHTTPHeaders: {
          ['if-none-match']: 'disabled',
        },
```

**Comment by yury-s** [comment]
Sounds like we can improve how 304 are handled. Can you share a reproducible example so that we can better understand your scenario?

**Comment by Tyutin** [comment]
```
context = await browser.newContext({
    ...config.browserContextOptions,
    recordHar: {...},
});
await context.route('**/*', route => {
    const headers = route.request().headers();
    delete headers['Cache-Control'];
    route.continue({headers});
});
```

worked as a temporary solution for me

**Comment by ahmed-noman** [comment]
Same is happening with the java version as well

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
