### ISSUE TITLE
How to perform operations on electron app that has multiple browsers?

### ISSUE THREAD

**Issue by githubhappyKaur** [microsoft/playwright#15576]
Login page is single browser so I am able to access it using firstwindow method after perform login operation using palywright but after login it is multi browser app and I am not able to perform any operation using playwright.

Can you provide example?

**Comment by yury-s** [comment]
You can listen to [`window`](https://playwright.dev/docs/api/class-electronapplication#electron-application-event-window) event to get notified about all new windows created by the app and inspect them via Page interface. You can also get a list of existing windows by calling [`electronApp.windows()`](https://playwright.dev/docs/api/class-electronapplication#electron-application-windows). Does it work for you?

**Comment by githubhappyKaur** [comment]
Do you have sample code that explains it.

Here is my scenario - After I login, Home page has multiple windows. 

Code I am using to get notified about  new window -
 const newWindow= await electronApp.waitForEvent('window');

I can perform operations on window number 0 using  this but how do I get to other windows that were created after login. I am only able to access one window if I use waitForEvent(Window) method. 

Also, is there any way to access window some property. currently I am using total windows open and using numeric to access each of them.

My code currently - const windows = await electronApp.windows();
 await windows[1].fill('input[id="name"]', 'Happy');

Pls share some sample code.

**Comment by yury-s** [comment]
> I can perform operations on window number 0 using this but how do I get to other windows that were created after login. I am only able to access one window if I use waitForEvent(Window) method.

If those are browser windows you will get one 'window' event for each of them when they are created. You can either do subsequent calls to waitForEvent('window') or subscribe to the `window` event and handle each new window in order:

```js
  electonApplication.on('window', page => {
    console.log('another window created');
  });
```

> Also, is there any way to access window some property. currently I am using total windows open and using numeric to access each of them.

You can look at [page.url()](https://playwright.dev/docs/api/class-page#page-url) to find the window you need in the list returned by `electronApp.windows()` or if they have same URLs call [page.evaluate()](https://playwright.dev/docs/api/class-page#page-evaluate) to evaluate some js in the context of the window and read its properties. This depends on your application.

Does that work for you?

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
