### ISSUE TITLE
[Question] Page reloading on locator.screenshot?

### ISSUE THREAD

**Issue by mattboehm** [microsoft/playwright#15589]
I am running Playwright 1.23.1 with the Chromium runner to test a react-based web application.

I've noticed that the page will frequently refresh after taking a screenshot with a line like the following (myTab.myButton is a Locator):

`await myTab.myButton.screenshot({ path: 'public/doc/sensor_add_button.png' })`

During the screenshot, the page appears to blink/resize, after which the page is reloaded and any page state is lost. It appears to happen when running in headed, headless, and debugger modes.

I've tried playing with the `animations`, `caret`, and `scale` arguments, but can't seem to prevent this from happening.

Does anyone have an idea of why these refreshes are occurring and how I might prevent them?

**Comment by mattboehm** [comment]
By the way, I'm running on a MacBook Pro. The resizing led me to believe that pixel density might be involved, but I'm not sure.

I suspect that the refreshes do not happen consistently, as sometimes when running headless, tests would pass. Other times, they would fail due to the reload losing page state halfway through a test.

**Comment by yury-s** [comment]
We used to resize the page while taking screenshots but that was fixed a few releases ago (1.20 or so). This should not happen anymore and in general taking screenshot should not be noticeable from the page's code and should not trigger any reloads.

> During the screenshot, the page appears to blink/resize,

When you run in headed mode the picture may blink if you are using emulation (different dpi e.g.) but this should be transparent for the page.

Can you share a reproducible example that we can try locally?

**Comment by mattboehm** [comment]
Thanks for your quick and thorough reply. I think I've figured out the problem: I was running the web server in a "develop mode" that reloads on file changes and it was picking up the saved screenshots as file changes and triggering the reload.

I think it makes most sense for me to fix this by moving the screenshots to an unwatched location or disabling/limiting the code reloading and will close this issue, as I can't think of a reasonable change for playwright that would help others that stumble into this issue.

**Comment by DeeHive** [comment]
Hello,

I am facing the same problem with puppeteer but I don't know how to apply your solution please? Could you help please?

**Comment by DeeHive** [comment]
> We used to resize the page while taking screenshots but that was fixed a few releases ago (1.20 or so). This should not happen anymore and in general taking screenshot should not be noticeable from the page's code and should not trigger any reloads.
> 
> > During the screenshot, the page appears to blink/resize,
> 
> When you run in headed mode the picture may blink if you are using emulation (different dpi e.g.) but this should be transparent for the page.
> 
> Can you share a reproducible example that we can try locally?

You mean on PlayWright or Puppeteer as well please?

**Comment by mattboehm** [comment]
In my case, when I took a screenshot, it was saved to the project directory. Separately, my webserver (running in development live-reload mode) was watching for file changes, noticed the new screenshot file, and triggered the page reload itself. If this is the issue you are facing, you'll want to disable the live-reloading or look into configuring it to ignore the directory where screenshots are saved.
