### ISSUE TITLE
[Question] About mocking HTTP requests causing flaky scenarios and VR test

### ISSUE THREAD

**Issue by Zifan27** [microsoft/playwright#15601]
We are trying to mock a `user-info` endpoint request

```ts
async function modifyResponse(
  response: APIResponse,
  field: string,
  modifiedValue: any
) {
  const jsonBody = await response.json();
  jsonBody[field] = modifiedValue;
  return JSON.stringify(jsonBody);
}

export default async function interceptUserInfo(
  page: Page,
  responseField: string,
  responseValue: any
) {
  await page.route("**/user-info", async (route) => {
    const response = await page.request.fetch(route.request());
    const body = await modifyResponse(response, responseField, responseValue);
    await route.fulfill({ status: 200, body });
  });
}
```

Scenarios and VR tests seem to be flaky within our CI job and locally for the `interceptUserInfo` function

All tests pass locally and in CI but with the following error in the report
![Screenshot 2022-07-13 at 08 30 50](https://user-images.githubusercontent.com/17220991/178676992-a964832c-df24-4ee8-ad26-fd68583b2569.png)

I hope to have some help or insights with this on how to resolve these flaky mock HTTP requests.

Thanks a lot!

**Comment by Meir017** [comment]
@Zifan27 can you provide a minimal project with the test that can be run? it's not clear from the description what error message you are getting

**Comment by yury-s** [comment]
From the information you provided  it seems that `...fetch(.../user-info)` fails on the CI for some reason. Look at the test trace to see what the network failure was. To help you further we need either a repro or the trace from the failing test, could you share that?

**Comment by Zifan27** [comment]
```
Error: Response has been disposed
[1158]()   at setup/browser/interceptUserInfo.ts:8
[1159]()   6 |   modifiedValue: any
[1160]()   7 | ) {
[1161]()>  8 |   const jsonBody = await response.json();
[1162]()     |                    ^
[1163]()   9 |   jsonBody[field] = modifiedValue;
[1164]()  10 |   return JSON.stringify(jsonBody);
[1165]()  11 | }
[1166]()    at modifyResponse (/buildsfrontend/tests/model-based-tests/library/setup/browser/interceptUserInfo.ts:8:20)
[1167]()    at /builds/frontend/tests/model-based-tests/library/setup/browser/interceptUserInfo.ts:20:18
[1168]()    at async Promise.all (index 1)
```
Two test cases are using this method. Do you think it could be that we are not resetting the mock? Any suggestions on how to reset it?

(The project is in private hosted GitLab, I will try to create a minimal project after some more investigation)

**Comment by yury-s** [comment]
> const jsonBody = await response.json();

This error is different from the one on your screenshot. In this case you are likely calling `response.json();` when the context where the page was created has already been closed. Can you share source of the tests that call `interceptUserInfo`? My hunch is that the context is being closed while the test is still running.

> Do you think it could be that we are not resetting the mock? Any suggestions on how to reset it?

I'm not sure which mocks you mean, can you elaborate on that?

**Comment by Zifan27** [comment]
```ts  
async function verifyTechnicalErrorPage(
  browserPage: any,
  interceptUserInfoField: string,
  interceptUserInfoValue: any,
  pageDataTestId: string
) {
  await interceptUserInfo(
    browserPage,
    interceptUserInfoField,
    interceptUserInfoValue
  );
  await browserPage.pause();
  await browserPage.goto(getServerUrl());
  await verifyTechnicalErrorsPage(pageDataTestId);
}

test.beforeAll(async ({ browser, locale, viewport }) => {
  await beforeAllTests(browser, locale, viewport);
});

test.afterAll(async () => {
  await afterAllTests();
});

test("user access-denied test", async ({ browserPage }) => {
  await verifyTechnicalErrorPage(browserPage, "authorities", [], ACCESS_DENIED);
});

test("generic technical-error page test", async ({ browserPage }) => {
  await verifyTechnicalErrorPage(
    browserPage,
    "authorities",
    "",
    TECHNICAL_ERROR_RELOAD_PAGE
  );
});
```

**Comment by yury-s** [comment]
Your tests are reusing the same page object created in `beforeAll` and seem to rely on the execution order of the tests. If that's the case you should use run them in [`serial mode`](https://playwright.dev/docs/test-retries#serial-mode) otherwise the tests may end up running on in different worker processes depending on the failures/flakes.

If switching to serial mode doesn't help, can you also share the definition of `browserPage` fixture (and its dependencies if any)?

**Comment by dgozman** [comment]
@Zifan27 It could also be the case that your test finishes successfully before `http://localhost:8098/user-info` has finished. For example, it might be that `/user-info` is not triggered immediately during `page.goto()`, but after some timeout, and your `verifyTechnicalErrorsPage` finishes before that. In such a case, you will get a route called, but won't respond to it before the test finishes and page closes. Does that make sense?

In this case, I'd suggest to wait for `user-info` explicitly, for example:

```js
  await interceptUserInfo(
    browserPage,
    interceptUserInfoField,
    interceptUserInfoValue
  );

  // Setup waitForEvent before the action. Make sure there's no await here.
  const userInfoRequested = browserPage.waitForEvent('requestfinished', request => request.url().endsWith('user-info'));
  await browserPage.goto(getServerUrl());
  // Wait for the event triggered by the goto above.
  await userInfoRequested;

  await verifyTechnicalErrorsPage(pageDataTestId);
```

**Comment by Zifan27** [comment]
Hey, I was able to fix the issue by adding 

```ts
async function verifyTechnicalErrorPage(
  browserPage: any,
  interceptUserInfoField: string,
  interceptUserInfoValue: any,
  pageDataTestId: string
) {
  await interceptUserInfo(
    browserPage,
    interceptUserInfoField,
    interceptUserInfoValue
  );
  await browserPage.goto(getServerUrl());
  await verifyTechnicalErrorsPage(pageDataTestId);
}
```
By adding `(browserPage)` to `await verifyTechnicalErrorsPage(pageDataTestId);`

```ts 
async function verifyTechnicalErrorPage(
  browserPage: any,
  interceptUserInfoField: string,
  interceptUserInfoValue: any,
  pageDataTestId: string
) {
  await interceptUserInfo(
    browserPage,
    interceptUserInfoField,
    interceptUserInfoValue
  );
  await browserPage.goto(getServerUrl());
  await verifyTechnicalErrorsPage(pageDataTestId)(browserPage);
}
```

Thanks everyone for your help!!
