### ISSUE TITLE
[Question] Is there a way to import vanilla-extract styles in a test

### ISSUE THREAD

**Issue by pweimann** [microsoft/playwright#15604]
Hi,

is there a way to import a vanilla-extract .css.ts file into a component test. I wanted to check if there is a style applied. I would appreciate any kind of advice.

Happy hacking!

**Comment by pweimann** [comment]
Hey @yury-s, I'm using vue3 and the *.css.ts files are compiled to css files at build time. Vanilla extract hashes the style/class names and so I can't check the applied class names directly. And I have no access to the vanilla extract references because playwright is running in its own environment. Is there any way to share a reference between both environments?

**Comment by yury-s** [comment]
You can use [page.evaluate](https://playwright.dev/docs/api/class-page#page-evaluate) to get the "references" in the page context if they are available to the app but my understanding that the app only includes post-processed .css files in which case there is no easy way to get them except for loading and parsing the file manually. Perhaps vanilla-extract produces some sort of source map which you can employ?

**Comment by pweimann** [comment]
To use page.evaluate works but the IDE shows some warnings and i would have to write magic strings to access the style. This approach seems to be more complicated and I think I will try to use vanilla extracts debug identifiers and check css class names for "myfile_mystyle_hash". Thank you very much for your time!
