### ISSUE TITLE
[BUG] Empty test result folders created when using toHaveScreenshot

### ISSUE THREAD

**Issue by devkat** [microsoft/playwright#15600]
**Context:**
- Playwright Version: 1.23.2
- Operating System: Linux, Mac

**Code Snippet**

```javascript
await expect(page).toHaveScreenshot(…)
```

**Describe the bug**

When using `toHaveScreenshot`, Playwright creates an empty directory for the test under `test-results`, even if the test succeeds.

The cause is probably this line:

https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/testInfo.ts#L240

```typescript
  outputPath(...pathSegments: string[]){
    fs.mkdirSync(this.outputDir, { recursive: true });
```

`SnapshotHelper.constructor` calls `outputPath`:

https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/matchers/toMatchSnapshot.ts#L129

```typescript
    const inputFile = testInfo.outputPath(...inputPathSegments);
```

See also: https://en.wikipedia.org/wiki/Command%E2%80%93query_separation

**Comment by drwpow** [comment]
I had to write a script to clean up empty folders after Playwright runs for this reason. In CI it doesn’t really matter too much, but locally it can be hard to find the snapshot diffs with all the empty folders.
