### ISSUE TITLE
[Feature] having a test suite running on 1 worker, while the rest can run on multiple workers

### ISSUE THREAD

**Issue by jeremieflrnt** [microsoft/playwright#15611]
I have multiple test suites (test.describe) that can run in parallel, and I have one test suite that need to run on a single worker.

Now, my solution is to have a npm script "parallelizable-tests" with --workers=undefined, so it can be more than 1
and I have a second npm script "serial-tests" with workers=1, so it is one test after the other
I would prefer to have just one script (and so one report, etc.).

It seems that describe.serial could do the trick, but the problem is that if one test fails, the others won't run.

Something like test.describe.serial with an option to not skip tests if one fails could be great!!

Thanks for reading!

**Comment by yury-s** [comment]
By default (unless you use [fullyParallel](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) mode) all tests in a single file will run in order and failure of one of them will not prevent others from running, see [this doc](https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file). So the behavior that you describe is the default one unless you [configure](https://playwright.dev/docs/api/class-test#test-describe-configure) the mode explicitly.

**Comment by jeremieflrnt** [comment]
I can't believed  I missed that. Thanks a lot!
I guess I thought, since I use test.describe.parallel for all my suites since now, the only other solution was test.describe.serial.
Anyway, thanks again for the fast reply, and awesome tool :)
