### ISSUE TITLE
[Question] HSTS on chromium inside docker

### ISSUE THREAD

**Issue by JanHuege** [microsoft/playwright#15613]
Hi,

we are trying to run playwright e2e-tests inside a docker-compose setup. We need to test with chrome (chromium). Running with the following config trying to navigate to our app inside a service called "app":

```
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
    use: {
        headless: true,
        viewport: { width: 1280, height: 720 },
        ignoreHTTPSErrors: true,
        video: 'on-first-retry',
        locale: 'de-DE',
    },
};
export default config;

```

`await page.goto("http://app:4000");`

We always end up with chrome internally redirecting us/elevating protocol to https without us having any HSTS/Strict-Transport-Security Headers present.

```
Response Internal Redirect {"cross-origin-resource-policy":"Cross-Origin","location":"https://app:4000/","non-authoritative-reason":"HSTS"}
```

Is there any ways to avoid this?

**Comment by yury-s** [comment]
You should look for the answer elsewhere ([this](https://stackoverflow.com/questions/34108241/non-authoritative-reason-header-field-http#:~:text=The%20Non%2DAuthoritative%2DReason%20%3A,response%20with%20this%20header%20set.) stackoverflow answer seems relevant), it has to do with your server configuration. Closing as this is not a playwright issue.
