### ISSUE TITLE
[Question] Disposing resolver which is already registered in a frame.

### ISSUE THREAD

**Issue by R-Prasi** [microsoft/playwright#15618]
I am using client API commands with expose function to resolve as below,

**_page.exposeFunction(<resolverFunc_name>, resolve)_**
https://playwright.dev/docs/api/class-page#page-expose-function

 When the function which is using this 'resolve' callback , is invoked more than once within same page/frame ,it is only working the first time , on the 2nd call getting error as
<img width="365" alt="image" src="https://user-images.githubusercontent.com/109231171/178772468-4cee6514-be36-4c92-92d0-53828271cdf1.png">

Is there any way to dispose this resolver when exiting from the function, and reinitialized the next time when function called again?

**Comment by yury-s** [comment]
There is no way to remove exposed bindings except for creating a new page/new context. You can workaround that by changing actual callback used in the test for the same bound function:

```js
  let fooBinding = x => console.log('first function called');
  await page.exposeFunction('foo', arg => fooBinding(arg));
  // ... do something
  fooBinding = x => console.log('second function called');
  // ... do something else
```
