### ISSUE TITLE
[Question] Saving Storagestate via Sign in via API request and then using inside BowserContext does not work - takes me back to login page

### ISSUE THREAD

**Issue by AshisRaj** [microsoft/playwright#15619]
I am in an urgent situation where I need to have an answer and resolution to the problem as described below.
This is in order to decide whether to go with Playwright as an E2E Automation tool or not. 

Following piece of code using backend API for sign in is working fine. But when I use the saved Storagestate file inside the BrowserContext, then it fails to sign me in, hence taking me back to the Login page.

```
    test.describe('User login', async () => {
    
        var browser: any;
      
        test.beforeEach(async () => {
            browser = await chromium.launch({
                channel: 'chrome',
                headless: false
            });
        });
    
        const requestContext = await request.newContext();
        const response = await requestContext.post(`${testConfig.envConfig.apiURL}/login/authorize`, {
            form: {
                'email': 'user.tech+admin@xxxx.com',
                'password': 'xxxxxx'
            }
        });
        const responseJson = await response.json();
        console.log(responseJson);
        expect(response.ok()).toBeTruthy();
        
        // Save signed-in state.
        await requestContext.storageState({ path: './.storagestates/adminUserStorageState.json' });
        await requestContext.dispose();
    
        // Using the Storagesate in the BrowserContext
        // page should sign in as a admin user.
            test.use({ storageState: './.storagestates/adminUserStorageState.json' });
            test('Version 1: Cookies stored via Auth. by backend API', async ({ page }) => {
                let url = `/brand/f99f06fb1f121234aaf/gallery`;
                await page.goto(url, {timeout: 60000});
            });
        
    
            test('Version 2: Cookies stored via Auth. by backend API', async () => {
                // page should sign in as a buyer user.
                const userContext = await browser.newContext({ storageState: './.storagestates/buyerUserStorageState.json' });
                const page = await userContext.newPage();
                await page.goto(`/`, {timeout: 60000});
            });
    });
```

**Comment by AshisRaj** [comment]
Thanks. I see that `await page.context().cookies();` and `await userContext.cookies();` do not return all the cookies that are written into the adminUserStorageState.json file. This is something strange. I clearly see that the most important one *csma* cookie is missing though it is there in the json file.

Rest of the info I will share once I gather those information from Application Dev team.

**Comment by yury-s** [comment]
> Thanks. I see that `await page.context().cookies();` and `await userContext.cookies();` do not return all the cookies that are written into the adminUserStorageState.json file. This is something strange. I clearly see that the most important one _csma_ cookie is missing though it is there in the json file.

Do you mind sharing the .json file and tell us which cookie is missing? You can send it to the email address in my github profile if you don't want to share it publicly.

**Comment by jobinsj27** [comment]
Hi Yury-s. I believe we've figured it out. Part of our authentication process requires that the user-agent string stay consistent with the cmsa cookie value. After statically setting the user agent string in a new browser context, then saving the storage state, we retained the cookie value. We then needed to once again re-use the same user-agent string in a new browser context where we were loading the same storage state json file and every successive call worked.

**Comment by jobinsj27** [comment]
Let me know if there's any functionality that would do that in a more streamlined way than what I performed i.e. is there a way to preserve the browser's user agent string as part of the json file? My guess from the documentation is no, but if something similar exists where I can dynamically derive and save the agent string that would be optimal.

**Comment by yury-s** [comment]
> Let me know if there's any functionality that would do that in a more streamlined way than what I performed i.e. is there a way to preserve the browser's user agent string as part of the json file? My guess from the documentation is no, but if something similar exists where I can dynamically derive and save the agent string that would be optimal.

There is no generic way to do that. As this is not something that is normally needed in a testing scenario, also there are many different way of authentication and some of them may rely on user-agent string, others could check other headers etc. Since in your case you know that the UA string has to be the same you can read that string from the browser you are going to use and set it in the API request that is used to retrive the cookies or just stick with your approach.

Closing this issue as the problem has been solved.
