### ISSUE TITLE
[BUG] addInitScript

### ISSUE THREAD

**Issue by platinumuser** [microsoft/playwright#15612]
**Context:**
- Playwright Version: 1.23.3
- Operating System: Mac
- Node.js version: 18.5.0
- Browser: WebKit

System:
OS: macOS 11.6.6
Memory: 28.09 GB / 64.00 GB
Binaries:
Node: 18.5.0 - /usr/local/bin/node
Yarn: 1.22.18 - /usr/local/bin/yarn
npm: 8.12.1 - /usr/local/bin/npm
Languages:
Bash: 3.2.57 - /bin/bash
npmPackages:
playwright: ^1.23.3 => 1.23.3 

**Code Snippet**
await page.addInitScript({ content });
OR
await page.addInitScript({ path });

Injected but not executed...
Tested in chromium everything works

**Comment by Meir017** [comment]
@platinumuser what are you running after you call `await page.addInitScript({ content / path });`? are you calling `page.goto(...)`?

**Comment by platinumuser** [comment]
> 

yes

**Comment by yury-s** [comment]
Please share full example that includes the script that you inject and the test that uses it.

**Comment by platinumuser** [comment]
> Please share full example that includes the script that you inject and the test that uses it.

await page.addInitScript('alert("test");'); not work

**Comment by yury-s** [comment]
Modal dialogs are [automatically dismissed](https://playwright.dev/docs/dialogs#alert-confirm-prompt-dialogs) by playwright unless you have an explicit event handler for `dialog` event, you can see that by running the following code:

```js
        page.on('dialog', e => {
          console.log('dialog: ' + e.type());
          e.accept();
        });
        await page.addInitScript('alert("test");');
```
