### ISSUE TITLE
[Question] How to perform action on child node button based on its siblings property? 

### ISSUE THREAD

**Issue by mystcuro** [microsoft/playwright#15625]
🙇 **I am a beginner in Playwright. Please excuse me if this is something trivial. I am stuck on this problem.**

🤖 **Expected Functionality:**
I am fetching some list. This list have child elements that indicates online status of profile, and contains follow button. I am trying to fetch list and click follow button only if user is online. 

🕸️ **Layout:**

```
    <article class="profile-list-item">
        <div class="profile-info">
            <>
                   <>
                       <>
                           <div class="online-status is-online"></div>
                       </>
                   </>
               </>
           </div>
        </div> 
        <button class="follow-button btn-simple">
        </button>
    </article>    

    <article class=profile-list-item">
    <article class=profile-list-item">
    .
    .
    .
    // More appears when scrolled 


</section>

```

📃**Workflow:** 
1. Fetching all the profile list items
2. Iterating through each item
3. checking if item contains this div => `<div class="online-status is-online"></div>`
4. Clicking on buttons if div mentioned in step 2 is present in the dom. The button is sibling of  `<div class="profile-info">`

🧑‍💻**Approach:**
 
 ```
let profile = page.locator("xpath=//article[contains(@class, 'profile-list-item')]");
let count = await profile.count();
while (i < count) {
    let item = profile.nth(i);
    await item.hover(); //without scrolling new elements wont appear in case all visible profile is offline
    if (page.locator(item, {has: page.locator("xpath=//div[contains(@class, 'online-status is-online')]")})) {
        let onlineProfileItem = page.locator(item, {has: page.locator("xpath=//div[contains(@class, 'online-status is-online')]")});
        await page.locator(page.locator("follow-button btn-simple"), {has: onlineProfileItem}).click();
        //Error while clicking 
        }
    i++;
}
 ```
 
☠️**Error:**
locator.click: Unsupported token "@follow-button" while parsing selector "Locator@follow-button btn-simple"

How can I fix this ? Or if there is any better methods available for such use case that would be really great help. Thank you for reading through 🐼

**Comment by yury-s** [comment]
You can check if there is a visible element with 'profile-list-item' class and nested '.online-status.is-online' in it and if so select the follow-button in it:

```js
  await page.setContent(`
<article class="profile-list-item">
  <div class="profile-info">
     <div>
       <div class="online-status is-online"></div>
     </div>
  </div> 
  <button class="follow-button btn-simple">
  </button>
</article>  `);

  const onlineProfile = page.locator('.profile-list-item', { has: page.locator('.online-status.is-online') });
  if (await onlineProfile.isVisible()) {
    const followButton = onlineProfile.locator('button.follow-button');
    console.log(await followButton.isVisible());
  }

```

**Comment by mystcuro** [comment]
Thank you pro! :-)
