### ISSUE TITLE
Axios don t work,how to solve?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#15623]
I want to run axios in my Login.api.ts file. But when I run the project taking below error when start debugging;

```
import * as axios from "axios";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```

When I don t use third-part import, the project run. But when I m using third-party import, it is not working and don t see axios post .I guess this is related to my tsconfig.json file. How I can configure this file properly for running axios in my project. In my Login.spec.ts url,username and password is not valid,please change this fields according to you

I create a core file and managing spec files there. 

This is my tsconfig.json;

```
{
    "compilerOptions": {
        "target": "ESNext",
        "module": "commonjs",
        "moduleResolution": "Node",
        "sourceMap": true
    }
}
```

This is my package.json;

```
{
  "name": "e2e_tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npx playwright test Login.spec.ts"
  },
  "author": "Crowdsol",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.23.1",
    "@types/jsonwebtoken": "^8.5.8",
    "axios": "^0.27.2",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "@openapitools/openapi-generator-cli": "^1.0.8-4.2.2",
    "@types/axios": "^0.14.0",
    "jsonwebtoken": "^8.5.1"
  }
}
```

this is my Login.spec.ts file;

```
import Core from "../../../core";
import { Login } from "./Login.api";

Core.create("Login", Login);
```

This is my Login.api.ts file ;

```
import * as axios from "axios";
export const Login = {
    States: {
      username: "test@domain.com",
      password: "alzm.22"
    },
    API: {
      Success: {
        run: async () => {
          let response: any = await axios.default.post("http://test", {
            username: Login.States.username,
            password: Login.States.password
          }
          );
          const body = response.data;
          console.log("body",body)
          console.log("response",response)
        },
      },
    },
  };
```

This is my core.ts file

```
import { test} from '@playwright/test';

const Core = {
    create(name: string, config: any) {
      return (() => {
        test(`${name} API Testing`,() => {
          Object.keys(config.API).map(t => {
            let test = config.API[t]
             test.run()
  
          });
        });
      })();
    },
   
  };
  
  export default Core;
```

**Comment by yury-s** [comment]
I created a [project](https://github.com/microsoft/playwright/files/9106500/proj.zip) with the files you described and everything works well (no syntax error that you mentioned), there must be something else in your configuration that causes the error. Can you share complete example where the error is observed?

**Comment by YusufOzturk-Development** [comment]
@yury-s  thanks for info. Do u see the console.log response on the terminal? 

          console.log("body",body)
          console.log("response",response)

If you are see everything is ok.If not axios not working.By the way,I m taking passed but there is no console.log

**Comment by yury-s** [comment]
> @yury-s thanks for info. Do u see the console.log response on the terminal?

No, I was only looking for the syntax error you mentioned. The console messages are not there because you are missing `await` in a couple of places, changing core.ts like this will fix it:

```ts
const Core = {
  create(name: string, config: any) {
    return (() => {
      test(`${name} API Testing`, async () => {
        await Promise.all(Object.keys(config.API).map(t => {
          let test = config.API[t]
          return test.run();
        }));
      });
    })();
  },
};

```
