### ISSUE TITLE
[Question] Improve tests performance using webkit on Ubuntu 22.04

### ISSUE THREAD

**Issue by heikergil** [microsoft/playwright#15621]
On my ubuntu machine (nuc i7 32gb) tests run fine and super fast while using Chromiun project however when I switch to Webkit (my works demands testing on webkit) the emulation is really slow to the point that tests that pass using Chromiun in 6s on Webkit takes more than 2 minutes and most of the times fails, I know this has to be OS related because running the same tests on my mac (mac mini i3 16gb) is much faster and reliable. so my question is there a way to improve performance of emulation webkit on ubuntu?

**Comment by heikergil** [comment]
> That's probably because there is not hardware acceleration support for some graphics stuff that you app depends on. Do you have any clue which part is slower? Can you share a sample test where the performance differs that much?

So I was able to reduce the difference, turns out in my config i had 
`{
name: 'Mobile Chrome',
			use: {
	...devices['iPhone 12'],
	},
 },
`
changing that to a normal Mobil Safari + iphone reduced the difference from 1 minutes to ~6s that i guess is acceptable, Thanks @yury-s

**Comment by yury-s** [comment]
Closing as the problem seem to have been resolved. Feel free to file a new issue if it doesn't work.
