### ISSUE TITLE
[Feature] Get `Page` from `sessionId` / `targetId`

### ISSUE THREAD

**Issue by szmarczak** [microsoft/playwright#15627]
Currently we can connect to remote browsers via https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp

However there's no way to get desired page instance. Assuming [a target has been created](https://chromedevtools.github.io/devtools-protocol/tot/Target/#method-createTarget) outside of Playwright, then knowing all the details - how to find it in Playwright?

Checking the URL doesn't work because there may be multiple tabs with the same URL.

**Comment by yury-s** [comment]
You can use [browser.contexts()](https://playwright.dev/docs/api/class-browser#browser-contexts) and [context.pages()](https://playwright.dev/docs/api/class-browsercontext#browser-context-pages) to iterate all pages in the browser. It's up to the test application to figure out which page it's looking for (e.g. based on url on by inspecting the page's state via page.evaluate() etc). If you need to work in terms of target ids you can use [CDPSession](https://playwright.dev/docs/api/class-cdpsession)

**Comment by szmarczak** [comment]
@yury-s Can you elaborate please? 

> based on url 

As I already mentioned:

> Checking the URL doesn't work because there may be multiple tabs with the same URL.

And per your second proposal:

> inspecting the page's state via page.evaluate()

This would require altering the window object. It's not a good idea, as there's a race condition - there may be redirects.

> If you need to work in terms of target ids you can use [CDPSession](https://playwright.dev/docs/api/class-cdpsession)

Thanks for the suggestion, however I'd like to use the high-level [`Page`](https://playwright.dev/docs/api/class-page) API in order to expose it for end users.

**Comment by szmarczak** [comment]
Ah, I just found out that `sessionId` / `targetId` differs per WS connection 🤦🏼 I'll try to find a way, but I'd really appreciate any help.

**Comment by szmarczak** [comment]
I think the possible solutions are: using `console.log` in an isolated world, checking history (the first entry might be `about:blank#someRandomIdHere`) or a binding. I'll see and will post code here.
