### ISSUE TITLE
[BUG] Can't click options even I can see them

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#15626]
**Context:**
- Playwright Version: Playwright 1.23.0
- Operating System: Windows
- Node.js version: 16.13.0
- Browser: Chromium

**Code Snippet**

```html
<select>
<option value="here">Click to visible</option>
</select>
```

```javascript
await page.locator('select').click();
await page.locator('option').click();
```

**Describe the bug**
Even I can see the options after click the select element, still got invisible errors, and `page.locator('option').is_visible()` return false as well.
Tried `selectOption` method, it works well, but I wonder why this happened? Is that possible to make options visible?

Might related to:
https://github.com/microsoft/playwright/issues/13994
https://github.com/microsoft/playwright/issues/14172

**Comment by yury-s** [comment]
The answer is the same as [this](https://github.com/microsoft/playwright/issues/14172#issuecomment-1128040079) in one of the issues that you linked: the dropdown is a native UI control which is not exposed to the web API, i.e. the page code cannot detect individual clicks on options, it will only get `input` or [`change`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) event once selected option has changed. In playwright we only support changing selected option which and not provide a way to click on individual options in the dropdown as it is non-essential for web testing scenarios.

**Comment by dmrock** [comment]
> The answer is the same as [this](https://github.com/microsoft/playwright/issues/14172#issuecomment-1128040079) in one of the issues that you linked: the dropdown is a native UI control which is not exposed to the web API, i.e. the page code cannot detect individual clicks on options, it will only get `input` or [`change`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/change_event) event once selected option has changed. In playwright we only support changing selected option which and not provide a way to click on individual options in the dropdown as it is non-essential for web testing scenarios.

Hey @yury-s 
A quick note on this issue: we have a user profile form that saves automatically when something is changed, and the `selectOption()` method doesn’t trigger this event. All other fields like `input` and `textbox` work correctly, but now we can’t test the dropdown at all.
