### ISSUE TITLE
[Feature] Add "focus" as locator engine, and add isFocus() function as well

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#15637]
This selector for example `locator('select:has-text("Feedback") >> ..')`
If I want to have a function which will help to locate the element only when its focused:
```
def locator_focus(selector: str):
  return page.locator(wrapper_selector(selector))
```
Already tried following code(as `wrapper_selector` function)
`':focus(' + selector + ')'` =>  Error: is not a valid selector.
`selector + '>> :scope:focus'` => always `True` even element is not focused.
`selector + ' >> focus=true'` => Error: Unknown engine "focus" while parsing selector
CSS selector won't enough, for simple selector, we can just use `select:focus`, but can't be used for combined complex selectors.

**Comment by yury-s** [comment]
> CSS selector won't enough, for simple selector, we can just use `select:focus`, but can't be used for combined complex selectors.

Can you explain what you are trying to achieve?

`:focus` can be combined with other selectors just like any other css selector, e.g.:

```js
page.locator('div', { has: page.locator('input:focus') })
```

**Comment by hkfsc** [comment]
> > CSS selector won't enough, for simple selector, we can just use `select:focus`, but can't be used for combined complex selectors.
> 
> Can you explain what you are trying to achieve?
> 
> `:focus` can be combined with other selectors just like any other css selector, e.g.:
> 
> ```js
> page.locator('div', { has: page.locator('input:focus') })
> ```

Already explained, can you read my question well?

**Comment by yury-s** [comment]
You can implement the function like this:

```ts
const locator_focus = (selector: string) => page.locator(selector, { has: page.locator(':focus') });
```

**Comment by hkfsc** [comment]
> You can implement the function like this:
> 
> ```ts
> const locator_focus = (selector: string) => page.locator(selector, { has: page.locator(':focus') });
> ```

Do you think it not looks awful?

**Comment by hkfsc** [comment]
And it didn't work at all....
```
page.locator('input:focus').count()
page.locator('input', has=page.locator(':focus')).count()
```

Result:
```
1
0
```

**Comment by hkfsc** [comment]
@yury-s
Your code didn't work at all....
```
page.locator('input:focus').count()
page.locator('input', { has: page.locator(':focus') }).count()
```

Result:
```
1
0
```

**Comment by hkfsc** [comment]
@yury-s If you keep not replying me, I will have to raise an new issue?
