### ISSUE TITLE
[Question] -- How can I build the playwright packages in my forked repo?

### ISSUE THREAD

**Issue by MakingStuffs** [microsoft/playwright#15641]
Hi all,

I have forked the playwright package in order to fix a bug I noticed and cannot workout how to build all packages etc. The contribution guidelines seem as though they may be a bit outdated so I thought I would ask here. 

Here is what I did:

1. Fork the repo
2. Run `npm i` 
3. Run `npm i @babel/core` as it doesn't get installed with `npm i` and causes an error
4. Made changes
5. Run `npm build`
6. Run `npm run test` -- just bails, even if I do this on a fresh fork
7. Run `npm lint`
8. Push to repo
9. Import playwright from my repo

From there it just either cannot find the overriding `playwright` module or, if I set to import from `/packages/playwright-core`, it cannot find the associated lib as they are gitignored for some reason. 

Is there something I am missing?

**Comment by mxschmitt** [comment]
Most likely you are using an outdated NPM version, thats why not all the packages were installed since we leverage NPM monorepo functionalities.

**Comment by yury-s** [comment]
Closing for now, feel free to file a new bug and reference this one if it still doesn't work for you.
