### ISSUE TITLE
[Question] How can I download and test the latest CT changes?

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#15647]
How can i download and use the latest Vue component testing changes @pavelfeldman pushed? I see there is a [new release on NPM](https://www.npmjs.com/package/@playwright/experimental-ct-vue/v/1.24.0-alpha-jul-14-2022) every day but it doesn't include [the latest changes](https://github.com/microsoft/playwright/pull/15551).

**Comment by pavelfeldman** [comment]
They are there, are you trying it like this?

https://github.com/microsoft/playwright/blob/main/tests/components/ct-vue-vite/playwright/index.js

**Comment by sand4rt** [comment]
Yes that's what I want to try. It seems to be working now. I think I installed an older version or it was a cache problem. Thanks
