### ISSUE TITLE
[BUG] Wrong webstorm types

### ISSUE THREAD

**Issue by MiguelSOliveira** [microsoft/playwright#15650]
**Context:**
- Playwright Version: `"@playwright/test": "^1.22.0"`
- Operating System: Mac
- Node.js version: v14.17.0
- Browser: WebStorm 2022.1.3

```
## System:
 - OS: macOS 12.4
 - Memory: 907.78 MB / 16.00 GB
## Binaries:
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - Yarn: 1.22.11 - ~/atlas/node_modules/.bin/yarn
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
```

**Describe the bug**

Types do not work in webstorm. They work in VSCode.

Could be related: https://github.com/microsoft/playwright/issues/2268
But I've tried the solutions proposed in that issue without success.

![image](https://user-images.githubusercontent.com/8149533/178969127-8c2ba58e-dee2-4418-8826-e90777cdfb68.png)

![image](https://user-images.githubusercontent.com/8149533/178968929-51fa526c-e4a8-4aa6-b615-33258b4013f7.png)

**Comment by yury-s** [comment]
Looks like the same problem as in https://github.com/microsoft/playwright/issues/2268 and if I understand it correctly WebStorm will not parse types from playwright-core by default since it is not a direct dependency of your project but a package that @playwright/core depends on. So un-excluding node_modules/playwright-core in WebStorm setting should help, did you try that?

**Comment by MiguelSOliveira** [comment]
hi @yury-s it does not seem to be the same. I've installed `"playwright-core": "^1.23.3"` directly, and the error still persisted.

**Comment by yury-s** [comment]
> hi @yury-s it does not seem to be the same.

"So un-excluding node_modules/playwright-core in WebStorm setting should help, did you try that?" - did you try this?

> I've installed `"playwright-core": "^1.23.3"` directly, and the error still persisted.

You should not have playwright-core in your dependencies as @playwright/test will bring it in automatically. Can you share a project where it happens?
