### ISSUE TITLE
[Feature] add `locator.waitForTransition()`

### ISSUE THREAD

**Issue by janosh** [microsoft/playwright#15660]
I'd like to test `computedStyles` and visibility _after_ some CSS transition (triggered by user input) finishes. From https://github.com/microsoft/playwright/issues/4055, it seems this is a common but unsupported use case.

```ts
const dropdown = await page.locator('.dropdown').

closeDropdown()
await dropdown.waitForTransition() // waitForElementState('stable') doesn't work if the element stays in place

expect(dropdown).toBeHidden()
```

**Comment by yury-s** [comment]
You can probably use [getAnimations](https://developer.mozilla.org/en-US/docs/Web/API/Element/getAnimations) and check if all/some of the animations have finished. Something like this:

```js
const dropdown = await page.locator('.dropdown').

closeDropdown()
await dropdown.evaluate(e => Promise.all(e.getAnimations({ subtree: true }).map(animation => animation.finished)));

expect(dropdown).toBeHidden()
```

Will that work for you?

**Comment by janosh** [comment]
Wonderful, that does exactly what I need!

I use it in several places so wrapped it in a litter helper:

```ts
import type { Page } from '@playwright/test'

function waitForAnimationEnd(page: Page, selector: string) {
  return page
    .locator(selector)
    .evaluate((element) =>
      Promise.all(
        element
          .getAnimations()
          .map((animation) => animation.finished)
      )
    )
}


test(`dropdown is hidden when reaching maxSelect items`, async ({ page }) => {
  await wait_for_animation_end(page, `div.dropdown`)

  expect(await page.locator(`div.dropdown`)).toBeHidden()
  expect(await page.getAttribute(`div.dropdown`, `class`)).toContain(`hidden`)
})
```

Would it make sense to have a `waitForAnimationEnd` `page` method in `@playwright/test`?

**Comment by yury-s** [comment]
We can add a sugar API for this if there is enough interest, leaving this request open to see if there is enough demand.

**Comment by alvipeo** [comment]
Interestingly, I tried yesterday to use the `waitForAnimationEnd()` helper and it didn't work for angular material sidenav... Either I did not really understand the case or it doesn't work in that case. I ended up with a simple 400 msec timeout (just to be sure the animation is over). And yes, this is probably the best solution in my case as I'm not testing the animation itself.

**Comment by JeremieBourque1** [comment]
I would also find this feature useful

**Comment by skysantoroa** [comment]
Does this work with elements animated with react-spring?

**Comment by niyarlatotep** [comment]
+1 to add as feature

**Comment by kawaii-flesh** [comment]
+ very useful

**Comment by bkfarnsworth** [comment]
+1, copying the helper into my code now to use in the meantime

**Comment by Piero87** [comment]
+1

**Comment by juniorerico** [comment]
+1

**Comment by MrCliff** [comment]
+1

**Comment by tomdelahaba** [comment]
+1 for this functionality, it should help us a lot avoiding evaluating timeouts / waits...

**Comment by GCyganek** [comment]
+1

**Comment by pavelfeldman** [comment]
Please +1 the issue on top, that's what is used when we are prioritizing the issues.

**Comment by denkorz** [comment]
> Wonderful, that does exactly what I need!
> 
> I use it in several places so wrapped it in a `waitForAnimationEnd` helper function:
> 
> ```ts
> import type { Page } from '@playwright/test'
> 
> function waitForAnimationEnd(page: Page, selector: string) {
>   return page
>     .locator(selector)
>     .evaluate((element) =>
>       Promise.all(
>         element
>           .getAnimations()
>           .map((animation) => animation.finished)
>       )
>     )
> }
> 
> 
> test(`dropdown is hidden when reaching maxSelect items`, async ({ page }) => {
>   await wait_for_animation_end(page, `div.dropdown`)
> 
>   expect(await page.locator(`div.dropdown`)).toBeHidden()
>   expect(await page.getAttribute(`div.dropdown`, `class`)).toContain(`hidden`)
> })
> ```
> 
> Would it make sense to have a `waitForAnimationEnd` method in `@playwright/test`?

In my case animations is empty, but if I do this: 
```
await this.page.evaluate('$.timers.length')
```
it works like that:
```
2
2
2
2
{ x: 243, y: 165, width: 349, height: 24 }
{ x: 243, y: 165, width: 349, height: 24 }
{ x: 243, y: 165, width: 349, height: 24 }
{ x: 243, y: 169, width: 349, height: 24 }
{ x: 243, y: 173, width: 349, height: 24 }
{ x: 243, y: 177, width: 349, height: 24 }
2
2
2
2
2
2
2
{ x: 243, y: 189, width: 349, height: 24 }
{ x: 243, y: 190, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
{ x: 243, y: 192, width: 349, height: 24 }
0
0
0
0
```

**Comment by janosh** [comment]
@yury-s This issue sits at 20 upvotes. Curious what the threshold for entry is?

**Comment by manojatlas** [comment]
+1 for this feature. As we face this issue frequently.

**Comment by VikramSinghMTL** [comment]
+1

**Comment by sirganya** [comment]
+1

**Comment by ValorHeart** [comment]
+1

**Comment by ch4r-ch4r** [comment]
+1

**Comment by remkoboschker** [comment]
+1

**Comment by ngocdd** [comment]
+1

**Comment by RuanAlesi** [comment]
+1

**Comment by theniceangel** [comment]
+1

**Comment by amit-ash** [comment]
+1

**Comment by sajaghori** [comment]
+1

**Comment by elimccoy** [comment]
+1

**Comment by pablopaul** [comment]
Guys please don´t comment with "+1" as your vote won´t be counted as @pavelfeldman pointed out:

<img width="935" alt="image" src="https://github.com/microsoft/playwright/assets/635526/a7c37b1f-d654-4670-b714-5981a341d4ad">

**You need to press on the 👍 emoji** of the first message in the current issue:

![image](https://github.com/microsoft/playwright/assets/635526/85227357-4f92-421d-b315-5a71a410321d)

**Comment by fildasabo** [comment]
+1

**Comment by Xtravaganz** [comment]
+1

**Comment by ellhans1** [comment]
+1, this has sent me down a bit of a rabbit hole. Much needed feature

**Comment by tiec7** [comment]
+1

**Comment by tiec7** [comment]
> Wonderful, that does exactly what I need!
> 
> I use it in several places so wrapped it in a `waitForAnimationEnd` helper function:
> 
> ```ts
> import type { Page } from '@playwright/test'
> 
> function waitForAnimationEnd(page: Page, selector: string) {
>   return page
>     .locator(selector)
>     .evaluate((element) =>
>       Promise.all(
>         element
>           .getAnimations()
>           .map((animation) => animation.finished)
>       )
>     )
> }
> 
> 
> test(`dropdown is hidden when reaching maxSelect items`, async ({ page }) => {
>   await wait_for_animation_end(page, `div.dropdown`)
> 
>   expect(await page.locator(`div.dropdown`)).toBeHidden()
>   expect(await page.getAttribute(`div.dropdown`, `class`)).toContain(`hidden`)
> })
> ```
> 
> Would it make sense to have a `waitForAnimationEnd` method in `@playwright/test`?

This function, moved in typescript, saved my job,  thanks <3

**Comment by yury-s** [comment]
> Wonderful, that does exactly what I need!
> 
> I use it in several places so wrapped it in a `waitForAnimationEnd` helper function:
> 
> ```ts
> import type { Page } from '@playwright/test'
> 
> function waitForAnimationEnd(page: Page, selector: string) {
>   return page
>     .locator(selector)
>     .evaluate((element) =>
>       Promise.all(
>         element
>           .getAnimations()
>           .map((animation) => animation.finished)
>       )
>     )
> }
> 
> 
> test(`dropdown is hidden when reaching maxSelect items`, async ({ page }) => {
>   await wait_for_animation_end(page, `div.dropdown`)
> 
>   expect(await page.locator(`div.dropdown`)).toBeHidden()
>   expect(await page.getAttribute(`div.dropdown`, `class`)).toContain(`hidden`)
> })
> ```
> 
> Would it make sense to have a `waitForAnimationEnd` method in `@playwright/test`?

In your test, you can remove the waitForAnimationEnd helper and rely on Playwright's web-assertions [auto-retry](https://playwright.dev/docs/test-assertions#auto-retrying-assertions) capabilities, note that `await` must be placed before expect:
```js
await expect(page.locator(`div.dropdown`)).toBeHidden()
await expect(page.getAttribute(`div.dropdown`, `class`)).toContain(`hidden`)
```

In the original example there is similarly missing await before the assertion call, it should have been this instead:
```js
await expect(dropdown).toBeHidden()
```


> I'd like to test `computedStyles` and visibility _after_ some CSS transition (triggered by user input) finishes. From [#4055](https://github.com/microsoft/playwright/issues/4055), it seems this is a common but unsupported use case.
> 

You don't need to manually wait for animations. Playwright's assertions and actions already handle waiting for the necessary conditions:

- **Auto-retry for assertions**: Playwright's web assertions like expect(page.locator()).toBeHidden() will automatically retry until the condition is met or the timeout is exceeded, so manually waiting for animations becomes redundant.
- **Built-in actionability checks**: Playwright's actions (e.g., clicking or typing) automatically wait for elements to become actionable, including handling animations.

I'm going to close this issue as all the uses cases mentioned so far should be covered by auto-wait functionality. If you encounter a scenario where this doesn't work, feel free to open a new issue with a specific example, and we can investigate further.

**Comment by bdcarr** [comment]
I don't have time to open a new ticket right now, but I found this because I want to automatically take a screenshot if a toast appears on the page, to make for more useful reports. The toasts slide up from the bottom of the screen while transitioning to full opacity, so I need to wait for that animation to finish in order to get a useful screenshot.

The screenshot function can fast-forward animations, but I worry that might cause issues or invalidate the test, so I just want to wait for it to finish.

I'll try the function shared above, thank you Yury and Yanosh
