### ISSUE TITLE
input[type=file] in webkit fails to display uploaded file

### ISSUE THREAD

**Issue by lemnis** [microsoft/playwright#15664]
**Context:**
## System:
 - OS: macOS 11.6.7
 - Memory: 18.27 MB / 16.00 GB
## Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - Yarn: 1.22.11 - /usr/local/bin/yarn
 - npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.23.3 => 1.23.3 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { webkit } from "playwright";
import { inspect } from 'util';

(async () => {
  const browser = await webkit.launch({
    headless: false,
  });
  const context = await browser.newContext();

  // Open new page
  const page = await context.newPage();

  // Go to http://nativeformelements.com/
  await page.setContent('<input id="test" type="file">');
  await page.locator("input").setInputFiles("data/image.svg");
  console.log(await page.locator("input").inputValue());
  console.log(
    inspect(await page.accessibility.snapshot({ root: "input", interestingOnly: false }), false, 8, true)
  );

  // ---------------------
  await context.close();
  await browser.close();
})();

```

**Describe the bug**

I expected to see:
![image](https://user-images.githubusercontent.com/3999815/179038400-ebc1959b-d9a6-4085-a6a2-7096d98508b5.png)

(with a populated `value` prop in the AX tree)

<details>
<summary>AX tree </summary>

```
{
  role: 'ScrollArea',
  name: '',
  orientation: 'horizontal',
  children: [
    {
      role: 'WebArea',
      name: '',
      children: [
        {
          role: 'Group',
          name: '',
          children: [
            {
              role: 'button',
              name: 'Choose File',
              roledescription: 'file upload button',
              value: 'image.svg',
              checked: undefined,
              pressed: undefined,
              children: undefined
            }
          ],
          value: undefined,
          checked: undefined,
          pressed: undefined
        }
      ],
      value: undefined,
      checked: undefined,
      pressed: undefined
    }
  ],
  value: undefined,
  checked: undefined,
  pressed: undefined
}
```

</details>

Instead I saw this:
![image](https://user-images.githubusercontent.com/3999815/179041620-b00636d8-ac04-4a87-b908-4b3a7a315b4d.png)

(without a populated `value` prop in the AX tree)

<details>
<summary>AX tree </summary>

```
{
  role: 'ScrollArea',
  name: '',
  orientation: 'horizontal',
  children: [
    {
      role: 'WebArea',
      name: '',
      children: [
        {
          role: 'Group',
          name: '',
          children: [
            {
              role: 'button',
              name: 'Choose File',
              roledescription: 'file upload button',
              value: undefined,
              checked: undefined,
              pressed: undefined,
              children: undefined
            }
          ],
          value: undefined,
          checked: undefined,
          pressed: undefined
        }
      ],
      value: undefined,
      checked: undefined,
      pressed: undefined
    }
  ],
  value: undefined,
  checked: undefined,
  pressed: undefined
}
```

</details>

**When using `await page.pause();` & manually uploading the file, the expected behaviour is displayed!**

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
