### ISSUE TITLE
[BUG] page.screenshot failed on Android devices (flaky screenshots)

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#15662]
**Context:**
- Playwright Version: 1.23.0 (but this behavior started a long time ago)
- Operating System:  Linux and Mac
- Node.js version: 16.15.1
- Browser: Chromium (WebView on android devices)
- Extra: Samsung Galaxy A50 (Android 11), Google Pixel 5 (Android 12)

**PW API debug log:**
```
pw:api => page.evaluate started +1ms
pw:api <= page.evaluate succeeded +146ms
pw:api => page.screenshot started +0ms
pw:api taking page screenshot +1ms
pw:api <= page.screenshot failed +5s
pw:api => page.evaluate started +3ms
pw:api <= page.evaluate succeeded +77ms
pw:api => page.screenshot started +0ms
pw:api taking page screenshot +1s
pw:api <= page.screenshot succeeded +2s
```
Full log in attachment [logs.txt](https://github.com/microsoft/playwright/files/9113661/logs.txt)

**Describe the bug**
In the test on a real device:
1. Open the webview in the application
2. Take a screenshot using `page.screenshot`

The problem is that sometimes for some reason the screenshot is not taken, after a few attempts I came up with the idea of immediately repeating the screenshot in such a situation, and it worked. But sometimes I need to repeat the screenshot call several times. Increasing the waiting time for the screenshot does not help (I tried to wait up to 5 minutes)

I understand that working with devices is an experimental feature, but maybe it is possible to add more information to the debug tool to understand what is the reason for such unstable behavior of screenshots?

Thanks for your attention:)

**Comment by bezyakina** [comment]
@yury-s I mean file is not saved. 

My code is contained in several files, here are the functions that take screenshots. I use these functions for a page obtained from a webview https://playwright.dev/docs/api/class-androidwebview#android-web-view-page. Please contact me if you need anything else, thank you

```typescript
        /**
	 * Takes and returns a screenshot of the visible area of the webview page
	 *
	 * @param screenshotPath - the path to save the screenshot
	 * @param mask - array of locator strings for masking
	 *
	 * @example
	 * ```getPageScreenshot(
	 * 'specs/search.spec.ts-snapshots', '['[class*="__version"]']'
	 * )```
	 */
	async getPageScreenshot(
		screenshotPath: string,
		mask?: string[] | undefined
	): Promise<Buffer | undefined> {
		let screenshotOptions: PageScreenshotOptions;

		if (mask !== undefined) {
			screenshotOptions = {
				path: screenshotPath,
				mask: this.getLocatorsFromStrings(mask),
				timeout: 5000,
			};
		} else {
			screenshotOptions = {
				path: screenshotPath,
				timeout: 30000,
			};
		}

		try {
			await this.waitForAllImagesLoaded();
			const pageScrenshot = await this.page.screenshot(screenshotOptions);

			return pageScrenshot;
		} catch (err) {
			console.log(
				`Get page '${screenshotOptions.path}' screenshot error`,
				err,
				'\nRetry page screenshot'
			);
			await this.getPageScreenshot(screenshotPath, mask ?? undefined);
		}
	}

	/**
	 * Takes a full-screen screenshot of the webview and returns the path to the screenshot for a given number of screens to be scrolled
	 *
	 * @param options - see interfaces/TestOptionsInterface.ts
	 * @param snapshotOutputName - the name of the file to save the final screenshot
	 * @param testInfo - see https://playwright.dev/docs/api/class-testinfo
	 *
	 * @example
	 * ```getFullPageSnapshot(TestOptions, 'search-offer-full-testing.png', '['[class*="__version"]']')```
	 */
	async getFullPageSnapshot(
		options: TestOptions,
		snapshotOutputName: string,
		testInfo: TestInfo
	): Promise<string> {
		testInfo.snapshotSuffix = '';
		testInfo.project.name = '';
		testInfo.snapshotDir = path.join(
			testInfo.project.testDir,
			'search.spec.ts-snapshots'
		);

		let currentSnapshotPath = '';
		const snapshotOutputPath = path.join(
			testInfo.snapshotDir,
			snapshotOutputName
		);

		const partOfView = 3;
		const heightOfPart = (await this.getViewPortHeight()) / partOfView;

		await this.scrollToTheTop();

		for (
			let i = 0;
			i <= options.numberOfScreens * partOfView - partOfView;
			i += 1
		) {
			currentSnapshotPath = path.join(
				testInfo.snapshotDir,
				`${options.testSlug}-${i}.png`
			);

			await this.getPageScreenshot(
				currentSnapshotPath,
				options.locatorsForMasking ?? undefined
			);
			await this.scrollPage(heightOfPart);

			if (i > 0) {
				const previousSnapshotPath = path.join(
					testInfo.snapshotDir,
					`${options.testSlug}-${i - 1}.png`
				);

				await concatOverlappingImages(
					previousSnapshotPath,
					currentSnapshotPath,
					currentSnapshotPath
				);
				fs.rmSync(previousSnapshotPath);
			}
		}

		fs.renameSync(currentSnapshotPath, snapshotOutputPath);

		return snapshotOutputPath;
	}
```

**Comment by yury-s** [comment]
> await this.page.screenshot(screenshotOptions);

Just to confirm, this line does not throw an error when the screenshot is missing?

Would you be able to provide a minimal reproducible example which we could run locally? The code you shared is legit but it depends on a lot of other stuff, which may well be unrelated but it's hard to tell.

**Comment by bezyakina** [comment]
@yury-s The minimum code with which the bug is reproduced (not stable, but reproducible, as in my product code):
1. Run test
2. Open webview in app manually on page that can be scrolled for a long time
3. Wait until one of the screenshots falls with an error

```typescript
import { AndroidDevice, test, Page } from '@playwright/test';
import { _android as android } from 'playwright';
import { config } from '../../../../../config';

{
	test.describe('', () => {
		let device: AndroidDevice;

		test('', async () => {
			test.slow();

			[device] = await android.devices();
			const webView = await device.webView({ pkg: config.appPkg });
			const page = await webView.page();

			await page.waitForLoadState('networkidle');

			for (let i = 0; i <= 100; i += 1) {
				await page.screenshot({
					path: `screenshot-${i}.png`,
					timeout: 60000,
				});
				await page.evaluate(() => {
					globalThis.window.scrollBy(0, 100);
				});
			}
		});
	});
}
```

```bash
12:18 $ DEBUG=pw:api npx playwright test screenshot.spec.ts

Running 1 test using 1 worker

  screenshot.spec.ts:9:3 ›  › 
  pw:api => android.devices started +0ms
  pw:api <= android.devices succeeded +433ms
  pw:api => androidWebView.page started +1ms
  pw:api   "commit" event fired +460ms
  pw:api   "domcontentloaded" event fired +75ms
  pw:api   "load" event fired +0ms
  pw:api   "commit" event fired +1ms
  pw:api   "domcontentloaded" event fired +153ms
  pw:api   "load" event fired +1ms
  pw:api <= androidWebView.page succeeded +6ms
  pw:api => page.waitForLoadState started +3ms
  pw:api   "networkidle" event fired +265ms
  pw:api <= page.waitForLoadState succeeded +5ms
  pw:api => page.screenshot started +0ms
  pw:api   "networkidle" event fired +1ms
  pw:api taking page screenshot +1ms
  ✘  screenshot.spec.ts:9:3 ›  ›  (1m)
  pw:api <= page.screenshot succeeded +2s
  pw:api => page.evaluate started +6ms
  pw:api <= page.evaluate succeeded +268ms
  pw:api => page.screenshot started +1ms
  pw:api taking page screenshot +1ms
  pw:api <= page.screenshot succeeded +2s
  pw:api => page.evaluate started +6ms
  pw:api <= page.evaluate succeeded +314ms
  pw:api => page.screenshot started +1ms
  pw:api taking page screenshot +2ms
  pw:api <= page.screenshot failed +1m


  1) screenshot.spec.ts:9:3 ›  ›  ===================================

    page.screenshot: Timeout 60000ms exceeded.
    =========================== logs ===========================
    taking page screenshot
    ============================================================

      17 |
      18 |                      for (let i = 0; i <= 100; i += 1) {
    > 19 |                              await page.screenshot({
         |                                         ^
      20 |                                      path: `screenshot-${i}.png`,
      21 |                                      timeout: 60000,
      22 |                              });

        at /screenshot.spec.ts:19:16

  Slow test file: screenshot.spec.ts (1m)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    screenshot.spec.ts:9:3 ›  ›  ====================================
```

**Comment by yury-s** [comment]
> 2\. Open webview in app manually on page that can be scrolled for a long time

We'd need a page where it fails too.

>  pw:api taking page screenshot +1ms
  ✘  screenshot.spec.ts:9:3 ›  ›  (1m)

Ok, page.screenshot() actually times out. Can you run it with `DEBUG=pw:protocol,pw:browser` and share the logs? Also please try running without path option in page.screenshot (to ensure there are no issues related to the file writes).

**Comment by dgozman** [comment]
@bezyakina Any change for a log with `DEBUG=pw:protocol,pw:browser`?

**Comment by bezyakina** [comment]
> Any change for a log with DEBUG=pw:protocol,pw:browser?

@yury-s @dgozman sorry for the late reply, logs in file [debug-logs.txt](https://github.com/microsoft/playwright/files/9176008/debug-logs.txt)

>We'd need a page where it fails too.

Unfortunately I cannot provide access to the debug build of our application

> Also please try running without path option in page.screenshot (to ensure there are no issues related to the file writes).

I tried, the error is still reproducible

**Comment by bezyakina** [comment]
@yury-s @dgozman I tested the code with adding a forced wait of 1000ms between scroll and screenshot, took 50 screenshots one after another, as a result, the error did not reproduce. When I remove the extra wait, the bug reproduces again. I hope this information helps you.

```javascript
import { AndroidDevice, test } from '@playwright/test';
import { _android as android } from 'playwright';
import { config } from '../../../../config';

{
	test.describe('', () => {
		let device: AndroidDevice;

		test('', async () => {
			test.slow();

			[device] = await android.devices();
			const webView = await device.webView({ pkg: config.appPkg });
			const page = await webView.page();

			await page.waitForTimeout(30000);
			await page.waitForLoadState('networkidle');

			for (let i = 0; i <= 100; i += 1) {
				await page.screenshot({
					path: `screenshot-${i}.png`,
					timeout: 10000,
				});
				await page.evaluate(() => {
					globalThis.window.scrollBy(0, 100);
				});
				// forced wait of 1000ms
				await page.waitForTimeout(1000);
			}
		});
	});
}
```

**Comment by pavelfeldman** [comment]
Let's make sure non-stalling evaluate is not stalling and allow an explicit nowait option that disables caret waiting.

**Comment by dgozman** [comment]
I looked at the logs. `Page.captureScreenshot` CDP command is taking more than 5 seconds. Maybe it is hanging, or maybe it's just slow - we don't know unfortunately.

Fixing this issue requires debugging chromium on android, with a local repro that includes this specific webview app. This is a lot of setup, so I don't think we'll be prioritizing this issue high enough in the nearest future.

For now, I'd suggest to use `waitForTimeout()` workaround if that makes things work reliably.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
