### ISSUE TITLE
[Question] Creating a custom fixture with a global scope

### ISSUE THREAD

**Issue by nate-blum** [microsoft/playwright#15672]
So in order to run my tests, I need to run some API requests to my own API before the tests. Essentially to get a configuration object that specifies which suite of tests are going to be run. Now my understanding is that the proper way to do this would be with a custom fixture, but from what I could find these fixtures are scoped only to individual workers, and since I intend to use parallelization, I don't want my program to request this configuration object for every single worker when it could just do it once globally, since all the processes need it. I've also seen the globalSetup configuration option, which would also work, but I didn't really see a way to save a custom state out of it, just the Browser's state (cookies and DOM storage). Is there any sort of option for me here that I haven't found yet? Thank you!

**Comment by yury-s** [comment]
> Essentially to get a configuration object that specifies which suite of tests are going to be run. Now my understanding is that the proper way to do this would be with a custom fixture, 

Note that the list of tests to run is compiled before running globalSetup and any test workers. So it'd be better to load list of test suits before running playwright. With that said you can still skip individual tests by calling `test.skip(condition)` from inside the tests.

> I've also seen the globalSetup configuration option, which would also work, but I didn't really see a way to save a custom state out of it, just the Browser's state (cookies and DOM storage).

You can download the configuration once in globalSetup and then save it to a file (alternatively you can pass it from globalSetup to the workers in an environment variable). The file can be read by a worked scope fixture in each worker. Will that work for you?

**Comment by nate-blum** [comment]
Saving to a file just seems like a workaround to me, would it work if I were to make my API requests in globalSetup and made closures with the results, and then put the closures into fixtures? Otherwise what would it look like if I went the environment variable way?

**Comment by yury-s** [comment]
> would it work if I were to make my API requests in globalSetup and made closures with the results, and then put the closures into fixtures?

No, globalSetup runs in the test runner process while the fixtures are executed in test worker processes so they wouldn't have access to the closures.

> Otherwise what would it look like if I went the environment variable way?

Something like the following:

```ts
// globalSetup.ts

async function globalSetup() {
  process.env.MY_VALUE = '2022';
}

export default globalSetup;

// test.spec.ts
import { test, expect } from '@playwright/test';

test('basic test', async ({ }) => {
  console.log(`process.env.MY_VALUE = ${process.env.MY_VALUE}`);
});

test('another test', async ({ }) => {
  test.skip(process.env.MY_VALUE === '2022');
});
```
