### ISSUE TITLE
[Question] a little confusing word "substring" in the document at expect(page).toHaveURL(urlOrRegExp[, options])

### ISSUE THREAD

**Issue by xbhoneybee** [microsoft/playwright#15703]
from document https://playwright.dev/docs/test-assertions#page-assertions-to-have-url
![image](https://user-images.githubusercontent.com/18543388/179170747-9ed11b3b-6d92-4582-a8db-1293f4749f1b.png)

The urlOrRegExp can be a substring of the target url if the type of argument is string. So I can use any substring in my opinion.

But actually it can only be the URL that remove the baseURL. For example:
if my expected URL is  https://playwright.dev/docs/test-assertions#page-assertions-to-have-url

I can only use `await expect(page).toHaveURL('https://playwright.dev/docs/test-assertions#page-assertions-to-have-url')`
or `await expect(page).toHaveURL( '/docs/test-assertions#page-assertions-to-have-url')`

`await expect(page).toHaveURL( 'test-assertions')` will fail, I should regex for this situation.

It will help a lot if you can change the word substring to another word, or give more detail information. 

Not sure here is the correct place to communicate about this.

Thanks in advance.

**Comment by yury-s** [comment]
There is a bug in the docs, the string parameter should be the full url or the part of the full url without base url prefix. I'll update the docs.
