### ISSUE TITLE
[Question] Is it possible to create shared state in globalSetup but ignore it for certain tests?

### ISSUE THREAD

**Issue by hoIIer** [microsoft/playwright#15705]
For example I have both authenticated and unauthenticated pages in my app that need testing.

Can I create users and authenticate in globalSetup, and use that for testing authenticated routes, while somehow ignoring that for tests that should be unauthenticated?

Separately, is it possible to import the configuration file in tests so that I can set `baseURL` once via playwright.config.js?

I'd like to do this and then just import config in tests:
```
  use: {
    baseURL: process.env.BASE_URL,
    trace: 'on-first-retry',
  },
```

**Comment by yury-s** [comment]
> Can I create users and authenticate in globalSetup, and use that for testing authenticated routes, while somehow ignoring that for tests that should be unauthenticated?

Yes, you can add the following code to the tests files that require authentication:
```js
test.use({
  storageState: './authenticated-state.json'  
})
```

> Separately, is it possible to import the configuration file in tests so that I can set baseURL once via playwright.config.js?
>
> I'd like to do this and then just import config in tests:

You can specify `use` section in your playwright.config.ts, it will be used by the tests automatically. If you want to override some values from the config you can call [`test.use`](https://playwright.dev/docs/api/class-test#test-use) inside the test file similar to the above example.

**Comment by matttrice** [comment]
for posterity:
https://playwright.dev/docs/auth#avoid-authentication-in-some-tests
