### ISSUE TITLE
Add the ability for locators to match zero elements

### ISSUE THREAD

**Issue by robertlagrant** [microsoft/playwright#15707]
Apologies if I've missed this in the docs.

I would like to test that a card is removed from the DOM when its close button is clicked. What I've tried to do is use a locator to search for any element like it, and then assert that the `count()` is 0 on that locator. However this appears to throw a timeout, as the locator is waiting for elements to exist, rather than knowing that they don't need to exist (in fact I'd rather it waited to check they don't exist, as there is a short animation before the element is removed).

Is it possible to tell a locator that it should look for something, and as soon as it finds nothing, it proceeds?

**Comment by ltsuda** [comment]
Do you think this helps?

https://playwright.dev/docs/test-assertions#locator-assertions-to-have-count

**Comment by yury-s** [comment]
Closing per the above comment.

```js
await expect(page.locator('button')).toHaveCount(0);
```

**Comment by robertlagrant** [comment]
Sorry I missed this. Thanks for the update; let me just add a final comment to see if I've understood correctly.

The issue is that when the automation clicks close, the element may still be present due to animation runs, until it eventually (from the perspective of a computer) is removed. If I expect the count to be 0, and it's still there, will the check retry until it passes?
