### ISSUE TITLE
Chromium driver gets deleted

### ISSUE THREAD

**Issue by pratikshah1001** [microsoft/playwright#15718]
**Context:**
- Playwright Version:  1.22.2",
- Operating System: Mac
- Node.js version: v17.4.0
- Browser: Chromium
- Extra: [any specific details about your environment]

**Describe the bug**

I am running a cucumber feature file using playwright and keep running onto this error 

All I have done is use npm install and it installs the latest chromium version and then it crashes and it deletes it. 

Error 

`1) Scenario: Create New Member successfully # src/features/BoostCRM/CreateNewMember.feature:8
   ✖ Before # src/support/cucumber/common-hooks.ts:7
       browserType.launch: Executable doesn't exist at /Library/Caches/ms-playwright/chromium-1012/chrome-mac/Chromium.app/Contents/MacOS/Chromium
       ╔═════════════════════════════════════════════════════════════════════════╗
       ║ Looks like Playwright Test or Playwright was just installed or updated. ║
       ║ Please run the following command to download new browsers:              ║
       ║                                                                         ║
       ║     npx playwright install                                              ║
       ║                                                                         ║
       ║ <3 Playwright Team                                                      ║
       ╚═════════════════════════════════════════════════════════════════════════╝
           at CustomWorld.newBrowser (work/repos/Playwright_Demo/cucumber-playwright/src/support/cucumber/custom-world.ts:24:42)
           at CustomWorld.init (work/repos/Playwright_Demo/cucumber-playwright/src/support/cucumber/custom-world.ts:44:36)
           at CustomWorld.<anonymous> work/repos/Playwright_Demo/cucumber-playwright/src/support/cucumber/common-hooks.ts:13:12)
   - Given I login as a "tester_usa" into "boost_crm" # src/features/common/steps/login.steps.ts:7
   - When I create a new member and fill out the required fields # src/features/BoostCRM/steps/CreateNewMember.steps.ts:11
   - Then the new member has been created # src/features/BoostCRM/steps/CreateNewMember.steps.ts:52
   ✖ After # src/support/cucumber/common-hooks.ts:18
       TypeError: Cannot read properties of undefined (reading 'page')
           at CustomWorld.<anonymous> (/work/repos/Playwright_Demo/cucumber-playwright/src/support/cucumber/common-hooks.ts:16:23)
`

**Comment by yury-s** [comment]
This looks like a cucumber issue (all the traces point to that and also playwright itself doesn't normally delete browsers), please file this issue in their repository instead.
