### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Matheus-Patrick** [microsoft/playwright#15738]
I have a code in Python using the PlayWRight library, which does the whole process right in the browser, so when I download the file, it presents something that I don't know how to solve... the result in a common browser (manual way) is a excel spreadsheet in .xls format >>> but in the code as download it brings me a file with a Windows icon with a name to see (attached image) and it doesn't save anywhere.... (remembering that the act of downloading it doesn't have a direct link, that's why I couldn't use the 'requests' library.... that's why I'm using the xpath path.... follow the code below:

```
from playwright.sync_api import sync_playwright
import time


with sync_playwright() as p:
    browser = p.firefox.launch(headless = False)
    page = browser.new_page()
    page.goto('https://solution.marketup.com/index.html#/report_sales_by_seller')
    page.fill('xpath=//*[@id="login§ds_login"]', "xxxxxxxxx@xxxxx.com")
    page.fill('xpath=//*[@id="login§ds_password"]', "xxxxxxxxx")
    page.locator('xpath=//*[@id="login§bt_login"]').click()#login
    page.fill('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[1]/div/div[1]/input', '2022-07-01')
    page.locator('xpath=/html/body/div[2]/div/ng-include[3]/div/div/button').click()#close side flap
    page.locator('xpath=//*[@id="report_search"]').click()#search date
    #page.locator('xpath=/html/body/div[2]/div/div/button').click()#close announcement
    page.locator('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[2]/div/div/button').click()#list
    page.locator('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[2]/div/div[1]/div[3]/button').click()#excel
    page.locator('xpath=/html/body/div[1]/div/div/form/div[3]/a').click()#click Download
    print("Sucesso")
    time.sleep(10)
    browser.close()
```

And then finally it ends with the download done, but nothing to do with the report I need:
![download](https://user-images.githubusercontent.com/109397311/179361678-18eb627e-cbb0-4451-bd14-3ab41fbbf397.png)

I also tried using this way:

```
with page.expect_download() as download_info:
    page.click('xpath=/html/body/div[1]/div/div/form/div[3]/a')#click Download
download = download_info.value
# wait for download to complete
path = download.path()
```

I don't know how to use the above function correctly or it doesn't work in my code, because it didn't have any success

**Comment by dgozman** [comment]
@Matheus-Patrick Your second snippet is good. You just need to save the download somwhere:

```py
with page.expect_download() as download_info:
    page.click('xpath=/html/body/div[1]/div/div/form/div[3]/a')#click Download
download = download_info.value
# wait for download to complete
path = download.save_as("/save/to/this/path.xls")
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
