### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Matheus-Patrick** [microsoft/playwright#15732]
Eu tenho um código em Python usando a biblioteca PlayWRight, que vez faz todo o processo certo no navegador, portanto na hora de baixar o arquivo, apresenta algo que não sei como resolver... o resultado em um navegador comum(forma manual) é uma planilha de excel em formato .xls   >>>  mas no código como download ele me trás um arquivo com ícone do Windows com um nome a ver (imagem anexada) e não salva em nenhum lugar.... (lembrando que o ato de download não tem link direto, por isso não consegui usar a biblioteca 'requests' .... por isso estou usando o caminho xpath.... segue o código abaixo:

```
from playwright.sync_api import sync_playwright
import time

with sync_playwright() as p:
    browser = p.firefox.launch(headless = False)
    page = browser.new_page()
    page.goto('https://solution.marketup.com/index.html#/report_sales_by_seller')
    page.fill('xpath=//*[@id="login§ds_login"]', "xxx@gmail.com")
    page.fill('xpath=//*[@id="login§ds_password"]', "xxxxx")
    page.locator('xpath=//*[@id="login§bt_login"]').click()#login
    page.fill('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[1]/div/div[1]/input', '2022-07-01')
    page.locator('xpath=/html/body/div[2]/div/ng-include[3]/div/div/button').click()#fechar aba lateral
    page.locator('xpath=//*[@id="report_search"]').click()#pesquisar data
    #page.locator('xpath=/html/body/div[2]/div/div/button').click()#fechar anuncio
    page.locator('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[2]/div/div/button').click()#lista
    page.locator('xpath=/html/body/div[2]/div/section/div/div/ng-include/div[1]/div/div[2]/div/div[2]/div/div[1]/div[3]/button').click()#excel
    page.locator('xpath=/html/body/div[1]/div/div/form/div[3]/a').click()#click do donwload
    print("Sucesso")
    time.sleep(10)
    browser.close()
```

E logo por fim ele finaliza com o download feito, porém nada a ver com o relatório que eu preciso

imagem do arquivo gerado:
![download](https://user-images.githubusercontent.com/109397311/179334316-f9be568b-9e1c-45e1-93b2-d6c814d4ea7e.png)

**Comment by yury-s** [comment]
Please file issues in English. Looks like the click results in a download which you want to handle, in that case please use `download` events as described in [this guide](https://playwright.dev/python/docs/downloads).

**Comment by Matheus-Patrick** [comment]
> Por favor, registre problemas em inglês. Parece que o clique resulta em um download que você deseja manipular. Nesse caso, use `download`eventos conforme descrito [neste guia](https://playwright.dev/python/docs/downloads) .



Mr. Yuri, I've tried using it that way, I don't know if I did it the wrong way, but I couldn't succeed....
