### ISSUE TITLE
[Question] How can I wait for one thing or the other

### ISSUE THREAD

**Issue by Tikvesa** [microsoft/playwright#15737]
I switched from selenium to playwright not that long ago and I want to ask if I can wait for one thing or the other.
For example I'm waiting for one selector but if the other selector shows up do something else.
On Selenium it works thru try and catch but when I tried it in playwright it doesn't work.
`    try{
      await page.waitForSelector(locator1)
      console.log('a')
    } catch{
      await page.waitForSelector(locator2)
      console.log('b')
    }`
    Any help?

**Comment by jfgreffier** [comment]
`locator.waitFor()` returns a Promise, so you should be able to do something similar

https://playwright.dev/docs/api/class-locator#locator-wait-for

**Comment by kremenni** [comment]
You can use locator.count() https://playwright.dev/docs/api/class-locator#locator-count to see if element exists or not (count is 0 if it doesn't exist)

**Comment by dgozman** [comment]
@Tikvesa Perhaps you can wait for a selector that matches both? Take a look at [this section](https://playwright.dev/docs/selectors#selecting-elements-matching-one-of-the-conditions).

Alternatively, try `Promise.race()`, but make sure to `catch()` both to avoid errors:

```js
await Promise.race([
  page.locator('text=First').waitFor().catch(() => {}),
  page.locator('text=Second').waitFor().catch(() => {}),
]);
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
