### ISSUE TITLE
[Question] What is difference between waitForSelector and locator?

### ISSUE THREAD

**Issue by topolanekmartin** [microsoft/playwright#15747]
Hello,

I have question which I can't find answer on. What is difference between `page.waitForSelector` and `page.locator` functions? I mean when I want use `locator` and when I want use `waitForSelector` functions?

Thanks in advance for answer.

**Comment by dgozman** [comment]
[This doc](https://playwright.dev/docs/locators) should explain it. In short, `page.locator` is almost always better. Let me know if something is still unclear, and we'll try to explain more details in the docs.
