### ISSUE TITLE
i trying to fetch the text while hovering on element. i unable to do that.

### ISSUE THREAD

**Issue by vishwajeetgodge13** [microsoft/playwright#15751]
hii, i'm working on playwrigh with js.
this is example code:

**await page.locator('([@class="highcharts-point"])[1]);**

when i mover hover over it, it shows value. what i want to fetch that hover value.
can suggest me, what should i do?

**Comment by dgozman** [comment]
@vishwajeetgodge13 Most likely, you want [HTMLElement.title](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/title).

To retrieve the title:
```js
const title = await page.locator('([@Class="highcharts-point"])[1]').getAttribute('title');
```

To assert the title:
```js
await expect(page.locator('([@Class="highcharts-point"])[1]')).toHaveAttribute('title', 'expected title value');
```

If that does not work, please share a url of the page you are working with, so we can take a look.

**Comment by vishwajeetgodge13** [comment]
@dgozman i'm trying to fetch the hover value, not a title.
when i hover over bars (graph) then shows value, i want to fetch that value to evaluate, whether showing correct value or not?

**Comment by dgozman** [comment]
@vishwajeetgodge13 In this case you probably want to hover, and then expect text. It's really hard to say without looking at your page though. Here is a snippet, replace locators with the real ones that work on your page. You can use [test generator](https://playwright.dev/docs/codegen) that will suggest the locators for you.


```js
await page.locator('text=Something to hover over').hover();
await expect(page.locator('.hover-element-that-appears')).toHaveText('Hover text that should appear');
```

**Comment by vishwajeetgodge13** [comment]
it's not working. i will share sample of code snippet

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by vishwajeetgodge13** [comment]
@dgozman hey,
I'm adding code snippet here, can help me to capture the tool tip text.
here i added one website where the when we hover over graph bars it's showing text.
that text i want to capture and validate whether is it showing correct?
same things in my application we have.

const { expect, test, page } = require ("@playwright/test");

test('Validation of tool tip text',async({ page }) =>{
    await page.goto('https://demos.telerik.com/kendo-ui/bar-charts/index');
    await page.hover('(//div[@id="chart"]//*[name()="svg"]//*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][4]/*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][1]/*[name()="path"])[1]');
    const text = await page.innerText('//div[@class="k-tooltip-content"]');
    expect(text).toBe('Total Visits: 56000');
})

**Comment by js0753** [comment]
Did you find a solution?
Not exactly a fix but I found a workaround, if you do await page.hover(".body") before any other calls to hover(), it works.

**Comment by aldoreyes** [comment]
@js0753 I freaking love you, that really works

**Comment by ewancombe** [comment]
I found this worked (in c#). Only slightly annoying thing is it looks for the text of tooltip in the entire page as it does not seem to belong to the button. This might be because of the way the System Under Test and it's controls work, could be different for other SUTs...

        //Assert the hover tooltip = "Add to watchlist".
        string hoverTooltipthatsExpected = "Add to watchlist";
        try
        {
            await page.GetByTestId("pw-OrderPage-WatchList-btn-1").First.HoverAsync();
            int found = page.GetByText(hoverTooltipthatsExpected).CountAsync().Result;
            Assert.AreEqual(found, 1);
        }
        catch (Exception ex)
        {
            Assert.Fail("In the Tech Parts page, failed to find the hover tooltip '" + hoverTooltipthatsExpected + "' Error: " + ex.Message);
        }

**Comment by Feuerhamster** [comment]
Had a similar issue and the fix from @js0753 worked! But why does it work? What was wrong?
