### ISSUE TITLE
[Question] Remaining test case shouldn't skip if one failed

### ISSUE THREAD

**Issue by santanakrishnan** [microsoft/playwright#15752]
Hi Team,

If one test case is failed, remaining all the test cases are skipped if i run in serial mode.
I want all my test to run in sequential because all my test to be run one after another but if one fails rest all the test cases are skipped. I don't want this. Can anyone tell me how to do this

**Comment by santanakrishnan** [comment]
The test is failed because of the bug in the application. It should fail only. But my remaining test should not skip

**Comment by dgozman** [comment]
@santanakrishnan Just don't mark your tests as `serial`. Tests in one file still run sequentially, so it should not matter for you. For more details, read [this guide](https://playwright.dev/docs/test-parallel), there is a nice overview at the top and detailed explanation of various modes.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
