### ISSUE TITLE
[REGRESSION]: extended expect matchers are no longer exported when using cucumber as framework

### ISSUE THREAD

**Issue by FinKingma** [microsoft/playwright#15760]
**Context:**
- GOOD Playwright Version: 1.21.1
- BAD Playwright Version: 1.22.1
- Operating System: Windows
- Extra: We use Cucumberjs as framework

**Code Snippet**
from our own project:
![image](https://user-images.githubusercontent.com/1401432/179546239-d2a8241d-6697-47ee-8529-a4fbb1528f8e.png)

reproduced using the boilerplate.
clone de boilerplate:
https://github.com/e2e-boilerplate/playwright-commonjs-cucumber-expect

add a second expect line in the test:
expect(title).toBeVisible();

**Describe the bug**
toBeVisible() is no longer exported as type if you try to use the expect from a cucumberjs context.

**More detailed information**
In version 1.21.1, the @playwright/test module exported 'testExpect.d.ts', which contained the toBeVisible() matcher. This was used when running tests from within a cucumber framework.
in version 1.22.1, the @playwright/test module exported 'expect-types.d.ts', which does not contain the toBeVisible() matcher anymore.

in version 1.22.1, the @playwright/test module also exported 'test.d.ts', which contains the toBeVisible() matcher, but this seems to only be used when running tests from the playwright test framework.

**Comment by dgozman** [comment]
@FinKingma Where can I look to see how cucumber, or this particular boilerplate, uses playwright types? We never had `testExpect.d.ts` as a requirement so we refactored our code and it disappeared 😄 We can bring it back, but need better understanding of how things work there to make a long-term support commitment.

**Comment by FinKingma** [comment]
ah I was missing the @types/expect dependency (compared our solution with https://github.com/Tallyb/cucumber-playwright). I've added it to my npm package and now it is able to find the normal test types from playwright.

**Comment by FinKingma** [comment]
besides adding types/expect, I also had to update ts-node to version 10.
