### ISSUE TITLE
[BUG] Can no longer dynamically add describe blocks like I could in 1.14.1

### ISSUE THREAD

**Issue by scottwalter-nice** [microsoft/playwright#15767]
Context:  I use to be able to dynamically add test describe blocks in 1.14.1 but it stopped working in 1.23.0 (or perhaps sooner).  As I want to run the same tests multiple times but with different background colors to test accessibility issues.

Playwright Version: 1.23.0
Operating System: MacOS
Node.js version: 16 lts
Browser: Chrome Canaru

I used to be able to do this in 1.14.1

```

addTestPerBackgoundColor(color: string) {
   test.describe('modal tests' + color, async() => {
      test('verify something', () => {
      );
   });
}
test.describe('Modal E2E Tests', async () => {
   addTestPerBackgoundColor('white');
    addTestPerBackgoundColor('black');
});
```

However, in 1.23.1 I get a "no tests found" error.

**Comment by dgozman** [comment]
@scottwalter-nice The snippet above works for me in 1.23.1. Could you please share a full repro?

That said, I think that in your real tests the problem is in the `async` describe function. `test.describe` only accepts a synchronous function, so you cannot do any `await`s inside. Let me know if this helps.

**Comment by scottwalter-nice** [comment]
@dgozman Sorry about that async in the describe that was a typo when I hand-wrote the above code.    You are right it does  work.  I was expecting globalSetup (which I set up an environment variable) to run before the Playwright builds its list of tests to run.   I have this in my global setup:

```
const globalSetup = async () => {
  process.env.backgroundColors = JSON.stringify(['#F5F8FA']);
  console.log('GLOBAL SETUP RAN', process.env.backgroundColors);

  if (!process.env.PLAYWRIGHT_BASE_URL) {
    process.env.PLAYWRIGHT_BASE_URL = 'http://localhost:6006';
  }
};

export default globalSetup;
```

Here is my test code:

```
import { test, expect } from '@playwright/test';

const runTestsPerColor = (fn: Function) => {
  console.log('runTestsPerColor', process.env.backgroundColors);

  if (!process.env.backgroundColors) {
    console.log('colors not set');
    return;

  }
  const colorsToProcess = JSON.parse(process.env.backgroundColors);

  for (const color in colorsToProcess) {
    fn(colorsToProcess[color]);
  }
};

test.describe('All Tests', () => {

  test('basic test', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const title = page.locator('.navbar__inner .navbar__title');
    await expect(title).toHaveText('Playwright');
  });

  runTestsPerColor(() => {
    test.describe('Dynamic1', () => {
      test('Test1', () => {
        console.log('Test1');
      });

      test('Test2', () => {
        console.log('Test2');
      });
    })
  });
});
```

In case you are curious here is repo to demonstrate this:   https://github.com/scottfwalter/playwright-dynamic

**Comment by dgozman** [comment]
@scottwalter-nice Thanks for the explanation. There was indeed a change in this behavior in v1.19.0 release. Take a look at [this write-up](https://github.com/microsoft/playwright/issues/12018) for the explanation and available mitigations. Let me know if that helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
