### ISSUE TITLE
[Question] How to create a new user profile in Google Chrome using Playwright

### ISSUE THREAD

**Issue by sanjoyghosh** [microsoft/playwright#15763]
Hello,

I am trying to test Autofill in Google Chrome.  This needs the Google Chrome browser have a signed in user.  The signed in user's profile will be used to populate some of the Autofill fields like Credit Card, etc.

What is the best way to do this in Playwright?

Thanks,
Sanjoy

**Comment by dgozman** [comment]
Use [`launchPersistentContext()` method](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) and pass a `userDataDir` path. If you perform actions in this browser, like signing in somewhere, and close it, user profile directory should be persisted. Let me know if this helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by ilorwork** [comment]
Maybe this will help:
[How to launch Chrome or Chromium using an existing user profile in Playwright](https://stackoverflow.com/questions/77359563/how-to-launch-chrome-or-chromium-using-an-existing-user-profile-in-playwright)
