### ISSUE TITLE
[Question - Java] Allow browser to connect on HTTP website

### ISSUE THREAD

**Issue by Sanady** [microsoft/playwright#15775]
Hello,
Currently, I am testing an application that has a sign-in form and after successful authorization, sign-in should redirect the user to a custom URL that contains a code, for now, that URL is localhost. After redirect on GUI less, I see that redirect link on chromium, and second, after redirect, I get this kind of error:
chrome-error://chromewebdata/
Basically, it says that chrome could not connect to that specific URL. is there an option to allow Playwright to connect on redirected localhost URL? Without any proxy or some kind of other things that are being used. So far I haven't found any helpful information about this topic when the user gets redirected to an HTTP page instead of HTTPS.

I hope that there is a solution for my issue,
Best regards,
Sanady

**Comment by dgozman** [comment]
@Sanady Chrome does not allow this because it is not secure. You can pass `--disable-web-security` argument, but do that on your own risk. See #15757.

**Comment by dgozman** [comment]
@Sanady Nope, this is chromium-specific. I don't think there is a similar argument for firefox/webkit.

**Comment by Sanady** [comment]
Is there any similar option for these two browsers, I mean to edit BrowserContext or something like that? Because when it comes to these two browsers all I get is the sign in page, no redirect to the HTTP website...
