### ISSUE TITLE
[Question] Overriding page fixture messes with storage state

### ISSUE THREAD

**Issue by nate-blum** [microsoft/playwright#15770]
I'm trying to override the Page fixture so that I can add network request blocking to all Pages without repeating the code. Here's what I have so far:
```typescript
export const test = base.extend<{
    page: Page;
}>({
    page: async ({ baseURL, page }, use) => {
        await page.route() //blocking requests here

        await page.goto(baseURL);
        await use(page);
    },
});
```

However, the problem is that once I do this, context storage states now seem to persist between tests, which is not ideal. I can tell because events that only happen for users who visit the sites I'm testing multiple times begin to happen to my second or third tests, when I've never seen them happen otherwise. I've tried passing brand new contexts into await use(page) that I generate in the function but it never seems to work, is there something I'm missing here?

**Comment by dgozman** [comment]
@nate-blum I think this snippet should work, and `page`s should still be isolated between tests. If you have a repro that we can run locally, we would definitely take a look.

**Comment by nate-blum** [comment]
sorry about this, it turns out the issue was completely unrelated and playwright was working as expected. my apologies
