### ISSUE TITLE
[BUG] default timeout doesn't work when inspector is open

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#15772]
re-raising #10312 as there are many scenarios where this behavior makes the inspector a huge pain to use:

- Currently there's no indication when it's failed to find an element (which I guess https://github.com/microsoft/playwright/issues/10311 could sort of address)
- when debugging tests i often go afk while they're running and when i come back to it hanging like this and an expired session on the site i'm testing i have no way to see what happened.
- if i have code that relies on a timeout error occurring, the test will hang with no way for me to continue the execution:
   ```ts
   try {
       await page.click("foo")
   } catch(e) {
       await page.click("bar") // no way to debug this code while the inspector is open
   }
   ```
- > This the intended behavior so you can see whats going on instead of closing the page.

   i understand this use case, however most of the time i can see what happened by simply viewing the trace file (along with the history of what led up to that point). but when the test hangs like this there's no way to even get the trace file, because you have to just kill the process before it gets saved

please consider *at least* an option to disable this behavior. the inspector is pretty much useless while it behaves this way.

# original issue

> **Context:**
> 
>     * Playwright Version: 1.16.1
> 
>     * Operating System: windows 10
> 
>     * Node.js version: 16.9.1
> 
>     * Browser: chromium
> 
>     * Extra: [any specific details about your environment]
> 
> 
> **Code Snippet**
> 
> Help us help you! Put down a short code snippet that illustrates your bug and that we can run and debug locally. For example:
> 
> ```js
> const {chromium, webkit, firefox} = require('playwright');
> 
> (async () => {
>   const browser = await chromium.launch();
>   const page = await browser.newPage()
>   await page.goto('https://google.com/')
>   await page.click('asdfsdfasdf')
> })();
> ```
> 
> **Describe the bug**
> 
> when the inspector is open, it just hangs forever waiting for the element instead of hitting the default timeout (which should be 30s)
> 
> however it works when you specify a custom timeout in `page.click` or `page.setDefaultTimeout`

**Comment by KotlinIsland** [comment]
```py
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    p = pw.chromium.launch().new_page()
    p.set_content("<html></html>")
```

This hangs indefinitely until I close the inspector, although, it seems like a different issue.

**Comment by pavelfeldman** [comment]
That's by design for the ease of debugging.
