### ISSUE TITLE
[Feature] `screenshot` methods can have a long delay

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#15773]
So basically I have noticed that `screenshot` functions can have a rather long delay before actually taking the screenshot.

```py
try:
    if not page.locator("#foo").is_visible():
        raise Exception("failed to find element")
except Exception:
    page.screenshot()  # the element appears before it takes the screenshot because 'screenshot' is doing something that takes a long time
    raise
```

**Comment by dgozman** [comment]
@KotlinIsland There are no stability checks when calling `page.screenshot()`. The checks are performed when calling `elementHandle.screenshot()`. Generally speaking, it seems like you have a race condition, so making screenshot faster will not help as it will still fail on slow CI machines.

If you use [`expect(locator).to_be_visible()`](https://playwright.dev/python/docs/test-assertions#locator-assertions-not-to-be-visible) and [enable tracing](https://playwright.dev/python/docs/trace-viewer), it should produce a snapshot as fast as possible - that would be your best bet to see what was happening in the page.

**Comment by rwoll** [comment]
Closed related issue in Python repo and moving the example from the user here for triaging: https://github.com/microsoft/playwright-python/issues/1420#issuecomment-1191053014

**Comment by dgozman** [comment]
@aslushnikov Could this be caret hiding that waits for some evaluate?

**Comment by dgozman** [comment]
Note that passing `caret: 'initial'` option could make screenshot a little bit faster, as a workaround. However, there are no strict guarantees about how long does a screenshot take, because browsers are very asynchronous internally.

**Comment by dgozman** [comment]
Closing per above, since there is no API changes required.

**Comment by KotlinIsland** [comment]
I've recently tested this, and even with `caret: 'initial'` I'm not seeing any change. @dgozman Do you think there could ever be any now approach that could improve the responsiveness/accuracy of screenshots?

**Comment by dgozman** [comment]
@KotlinIsland There's not much we can suggest here. Screenshots in the browser are asynchronous, complicated and time consuming, so there are no guarantees that it happens very fast, especially when your computer is under heavy load.

**Comment by DetachHead** [comment]
here's a workaround to take a screenshot with no delay:
```ts
const base64 = (await (await page.context().newCDPSession(page)).send('Page.captureScreenshot')).data
```

it would be nice if playwright's `screenshot` method had an option to behave like this

**Comment by KotlinIsland** [comment]
Wow, this is blazingly fast🔥! That's amazing 🚀.

**Comment by MKITConsulting** [comment]
@DetachHead is there a way to do this in Java as well?

**Comment by cyberw** [comment]
Great suggestion by @DetachHead . Complete code if someone else wanders here :)

```
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    cdp = context.new_cdp_session(page)
    page.goto("https://www.google.com", wait_until="commit")
    b64_str = cdp.send("Page.captureScreenshot")["data"]
    b64_bytes = b64_str.encode("ascii")
    binary = base64.decodebytes(b64_bytes)
    with open("screenshot.png", "wb") as binary_file:
        binary_file.write(binary)
```

**Comment by jeff-an** [comment]
any idea on how to replicate the playwright's scale: 'css' option with only CDP methods?
