### ISSUE TITLE
[Question] Is it possible to reliably record/replay specific requests with routeFromHAR in single endpoint APIs?

### ISSUE THREAD

**Issue by kremenni** [microsoft/playwright#15778]
I need to save and then route a specific request in an app that uses Graphql. Is it possible? Because it seems that so far the only filtering available is by url, which is always the same

**Comment by dgozman** [comment]
@kremenni `routeFromHAR` will match by the post data used by GraphQL, so it should pick the right one.

That said, if you don't want to replay other requests, you'll have to record all of them requests into the HAR, and then manually remove those you don't want to be replayed. Edit the `.har` file, it is a simple json, and you can differentiate requests by their `postData` property to find the right one. Let me know if this helps.

**Comment by kremenni** [comment]
It seems like that after manually deleting not needed graphql requests, it's also required to set `notFound: 'fallback'` in the options.

I also just found that in [documentation](https://playwright.dev/docs/network#replaying-from-har) it's said that not only urls, but POST payloads are also matched, which is exactly how `routeFromHAR` would differentiate between different graphql requests

@dgozman thank you
