### ISSUE TITLE
[Question] Firefox does not reload if goto has the same url

### ISSUE THREAD

**Issue by cupcakearmy** [microsoft/playwright#15781]
I wanted to ask if this is expected behaviour:
Firefox does not goto/reload the page if the url is the same as the current one. Safari and Chrome both reload/load the page even if the current url is the same.

```
const link = 'http://localhost/foo/bar'
await page.goto(link)
await page.goto(link) -> Firefox does not reload
```

(Browsers are all desktop on macos)

Thanks for the AMAZING project! ❤️

**Comment by dgozman** [comment]
@cupcakearmy Firefox does reload the page for me. Could you please share a full repro that we can run locally?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by penyaskito** [comment]
Sorry for commenting on a closed issue, landed here searching.
I thought I was having the same issue while testing there are no cached issues. My tests failed only on firefox.
In step by step debugger, if I Ctrl + R just before my navigation, my content doesn't change. If I Ctrl + Shift + R, it does. So might be the same you were experiencing, and it looks like it's not reloading. Still figuring out a way to hard refresh via playwright.

**Comment by penyaskito** [comment]
Ended up doing this and it worked:

```
    // Firefox does some aggressive caching, so playwright reload will load from
    // the cache instead of a hard refresh. Firefox implementation of
    // location.reload has non-standard bool argument for forcing it. That
    // argument is ignored for other browsers, so it's safe to use.
    // https://developer.mozilla.org/en-US/docs/Web/API/Location/reload
    await anonPage.evaluate(() => location.reload(true)),
```
