### ISSUE TITLE
[Feature] Opt out of parallelism for some files

### ISSUE THREAD

**Issue by WhyAsh5114** [microsoft/playwright#15788]
I love Playwright because of its parallelism, but there's an issue that makes me want to disable it. Whenever I use database interactions, sometimes there are conflicts between requests that wouldn't occur in serial mode, due to parallelization.

For example, a file could test the login and it would clear the database and create a new user, while the register file would test the register function and clear the database to create a new user. Sometimes these operations might occur in an undesirable order which causes tests to fail. So I would like to suggest adding a feature in the test config which disables parallelization for certain files (which should be run serially instead).

**Comment by dgozman** [comment]
@WhyAsh5114 Tests in a single file run in order by default. Are you using a fully parallel mode? Take a look at [this guide](https://playwright.dev/docs/test-parallel) for more options.

If you want some order across the multiple test files, I'd suggest to create multiple `project`s in the `playwright.config.ts` and use different [`testMatch` options](https://playwright.dev/docs/api/class-testproject#test-project-test-match). This way you can run first project, and then second project as two separate `npx playwright test --project=projectName` command.
