### ISSUE TITLE
[Question]Why can't I start the local Firefox browser？playwright._impl._api_types.Error: Protocol error (Browser.enable): Browser closed.

### ISSUE THREAD

**Issue by zfp19961018** [microsoft/playwright#15785]
`from playwright.sync_api import Playwright, sync_playwright, expect
def run(playwright: Playwright) -> None:
    browser = playwright.firefox.launch(executable_path="/Applications/Firefox.app/Contents/MacOS/firefox",  headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.baidu.com")
    context.close()
    browser.close()
with sync_playwright() as playwright:

    run(playwright)`

**Comment by mxschmitt** [comment]
Using the stock Firefox is not supported, only the Firefox and WebKit which comes with Playwright you can use with Playwright.

See here: https://playwright.dev/python/docs/next/browsers
