### ISSUE TITLE
[Question] Standalone globalTeardown

### ISSUE THREAD

**Issue by raje312** [microsoft/playwright#15794]
I noticed that  globalSetup  works independently where as if user world like to use  globalTeardown independently, it does not work. Is this on purpose ?  I would like to delete data created by test at the end. 

globalTeardown  works if user has below in config file:

globalSetup: './tests/globalSetup.ts',
globalTeardown: './tests/globalTeardown.ts',

globalTeardown  does not work with only globalTeardown is defined in config file: 

globalTeardown: './tests/globalTeardown.ts',

**Comment by dgozman** [comment]
This should work, but it is broken indeed.
