### ISSUE TITLE
[BUG] Not able to upgrade from playwright from 1.13.0 to 1.23.0

### ISSUE THREAD

**Issue by ajayEngProd** [microsoft/playwright#15799]
playwright version new version: 1.23.0
playwright old version: 1.13.0

OS: windows 11.
language : c# dotnet 6.

when am trying to upgrade the playwright version, am getting the below error  in some of the test executions.
any help in this regard is appreciated.

![playwrightError](https://user-images.githubusercontent.com/105768577/179896919-f894b4fd-f303-4277-b711-55bf75055053.png)

**Comment by mxschmitt** [comment]
You need to install browsers, as the exception says, see here: https://playwright.dev/dotnet/docs/browsers#installing-browsers

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
