### ISSUE TITLE
[BUG]I can't run the code which I record

### ISSUE THREAD

**Issue by wuchengzenb** [microsoft/playwright#15792]
**Context:**
- Playwright Version: 1.23
- Operating System:linux
- Browser:firefox

**Code Snippet**

from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.firefox.launch(headless=False)
    context = browser.new_context() 
    page = context.new_page()
    page.goto("http://www.baidu.com")

**Describe the bug**

File "playwright/sync_api/_context_manager.py", line 94, in start
  File "playwright/sync_api/_context_manager.py", line 89, in __enter__
AttributeError: 'PlaywrightContextManager' object has no attribute '_playwright'

**Comment by mxschmitt** [comment]
Which Python version and which linux distribution are you using?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
