### ISSUE TITLE
[Question] Advise on how to test common components in different projects

### ISSUE THREAD

**Issue by cunhabruno** [microsoft/playwright#15790]
Hello,

I have multiple projects that use some shared UI components, so the code is basically the same, but they are in different E2E test repositories, so I am getting code duplication that could be fixed if I had a library for those common components. I actually did a library, but my doubt is that the lib I created is an NPM module with playwright installed, if I want to update the PL version there might be breaking changes between the repos and the lib. Would you have any advise on how I could create playwright  libs for some shared components?

Simplifying my question:

How would you advise me to create a Page Object Model as an npm module??

**Comment by dgozman** [comment]
@cunhabruno Perhaps you could set `@playwright/test` in `peerDependencies` for your POM module `package.json`? I assume you only use types from it anyway, because POMs are actually instantiated in the real test projects. This way, it will use Playwright from the outer project that uses your POMs.

**Comment by cunhabruno** [comment]
I will try this, for the quick response!
