### ISSUE TITLE
OS platform support 

### ISSUE THREAD

**Issue by rohithbb433** [microsoft/playwright#15801]
Do we have the option to test specific OS + browser combinations ? E.g.: Chrome on MacOS vs Chrome on Windows ?

If Yes how can I configure it in Playwright.config.ts file?

**Comment by mxschmitt** [comment]
Each Playwright version is bound to a specific Chromium, WebKit and Firefox version. You can run your tests on different operation systems - by configuring it on your CI provider - to fulfil this criteria, but usually there is not much difference between Chrome on Mac and on Linux.

See here for more information: https://playwright.dev/docs/next/browsers

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by ivanli1990** [comment]
> Each Playwright version is bound to a specific Chromium, WebKit and Firefox version. You can run your tests on different operation systems - by configuring it on your CI provider - to fulfil this criteria, but usually there is not much difference between Chrome on Mac and on Linux.
> 
> See here for more information: https://playwright.dev/docs/next/browsers

But I've found that the same version of playwright and the browser it installs doesn't behave the same way on linux and macos. You can see what I posted below
https://discord.com/channels/807756831384403968/1242831341565771867/threads/1283072650016456735
