### ISSUE TITLE
Regexes in selectors (python)

### ISSUE THREAD

**Issue by nouni19** [microsoft/playwright#15803]
Hello, I want to screenshot a div if its class starts with "Comment ", so I tried this: page.locator('/.Comment \\s*/').
But it's telling me that the / was unexpected. Any other way to do it? (I'm using python)

**Comment by dgozman** [comment]
Prefix it with `text=`

```py
page.locator("text=/.Comment \s*/")
```

Read this [selectors guide](https://playwright.dev/python/docs/selectors#text-selector) for more options and examples.
