### ISSUE TITLE
Error: toMatchSnapshot() must be called during the test

### ISSUE THREAD

**Issue by karthick27august** [microsoft/playwright#15800]
I am using playwriht in cucumber framework with a javascript codebase.

Below is my code, where 1 is with the comparing the screenshot with the page and the other with the particular element.

Then('the graph should be loaded successfully in the Graph page', async() =>{
  await expect(await page.locator('[data-testid=graph-01]').screenshot()).toMatchSnapshot('graph.png');
});

Then('the graph should be loaded successfully in the Graph page', async() =>{
  await expect(page).screenshot()).toMatchSnapshot('graph-page.png');
});

On executing this test, I am getting **"Error: toMatchSnapshot() must be called during the test"**

Is there something I am missing? Is it wrong approach?

Kindly help me on this. Many thanks in advance
![error](https://user-images.githubusercontent.com/104966690/179904755-3ad8c722-397f-4cfb-8b29-1d649ef81112.PNG)

**Comment by dgozman** [comment]
@karthick27august Snapshots require tight integration with the test runner, so they are not available when not using `@playwright/test`. Since you are using the cucumber runner, you should look for a similar capability there. Let me know if you have more questions.

**Comment by zheeeng** [comment]
I also encountered this issue with vitest, is there any adjust solution?

```ts
import { afterAll, beforeAll, describe, test } from 'vitest';
import { preview } from 'vite';
import type { PreviewServer } from 'vite';
import { chromium } from 'playwright';
import type { Browser, Page } from 'playwright';
import { expect } from '@playwright/test';

describe('basic', async () => {
  let server: PreviewServer;
  let browser: Browser;
  let page: Page;

  beforeAll(async () => {
    server = await preview({ preview: { port: 3000 } });
    browser = await chromium.launch();
    page = await browser.newPage();
  });

  afterAll(async () => {
    await browser.close();
    await new Promise<void>((resolve, reject) => {
      server.httpServer.close(error => error ? reject(error) : resolve());
    });
  });

  test('should match the startup snapshot', async () => {
    await page.goto('http://www.google.com');
    await expect(page).toHaveScreenshot('goole.png');
  }, 10_000);

});
```

reported: `Error: toHaveScreenshot() must be called during the test`

**Comment by karthick27august** [comment]
@dgozman Could you please share the code for the screen comparison using cucumber runner?
