### ISSUE TITLE
[QUESTION] Prevent browser crash on failed action

### ISSUE THREAD

**Issue by Agustin-DeLuca** [microsoft/playwright#15815]
I was asked to write a test in which there is a step that might fail, so I need to retry that step without closing the current instance of the browser. I've tried using try/catch and page.on("crash") with no results.

**Comment by dgozman** [comment]
@Agustin-DeLuca Could you please provide more details? Ideally, a code snippet.

**Comment by Agustin-DeLuca** [comment]
The app that I'm testing has an element that sometimes loads correctly and sometimes doesn't. I was asked not to take the first try as an error; so I need to assert if the element was loaded or not and, if it wasn't, refresh the page to retry the failed action and continue the test. The problem is that when playwright fails to find the element, the browser is closed and I can't prevent it. I don't want to retry the whole test.

For instance, let's say that Google fails to load the search input the first time you go to the page. I need to do something like this:

````typescript
test("Test", async ({ page }) => {
	await page.goto("https://google.com");
	const searchInput = page.locator("#q");
	try{
		await searchInput.fill("something to search"); // will fail because the element didn't load
	}catch(e){
		await page.reload();
		await searchInput.fill("something to search"); // will succeed
	}

	// continue the test
});
````

**Comment by dgozman** [comment]
@Agustin-DeLuca Thank you for the detailed report!

I think that you just need to a timeout to your first `.fill()` call that may fail. Otherwise, it waits until the whole test times out, and the browser is closed because testing has finished.

```js
try {
  // Give it 5 seconds to appear.
  await searchInput.fill("something to search", { timeout: 5000 });
} catch(e) {
  // If it did not, continue with the reload.
  await page.reload();
  await searchInput.fill("something to search");
}
```

Let me know if this helps.
