### ISSUE TITLE
[BUG] window.location.href is empty when testing <a/> tag

### ISSUE THREAD

**Issue by slim-hmidi** [microsoft/playwright#15828]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: MacOs
- Node.js version: 16.14.2
- Browser: chromium
- Extra: [any specific details about your environment]

## System:
 - OS: macOS 12.4
 - Memory: 438.21 MB / 16.00 GB
## Binaries:
 - Node: 16.14.2 - /usr/local/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.13.2 - ~/Desktop/workspace/everestate-next/node_modules/.bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
    <a href={`https://www.linkedin.com/sharing/share-offsite/?url=${url}`} target=`_blank` data-testid='share-link'> Share Link </a>
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  await page.goto('/mypage')
  
    const [newPage] = await Promise.all([
        context.waitForEvent("page"),
        page.locator('[data-testid="share-link"]').click(),
      ]);
    
      expect(newPage.url()).toContain('https://www.linkedin.com/sharing/share-offsite/?url=http://app_url/mypage');
})();
```

**Describe the bug**

the test fails and I in the url of the newPage `https://www.linkedin.com/sharing/share-offsite/?url=`.

**Comment by dgozman** [comment]
You need to add `await newPage.waitForLoadState()` to wait until the new page loads. Take a look at [this guide](https://playwright.dev/docs/pages#handling-popups).
