### ISSUE TITLE
[Question] Proper QA term for "PageObject of component"?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15825]
Question about QA terms, not playwright)

We all know https://playwright.dev/docs/test-pom which is about page (PageObject = object of page). But in our case there are many "objects" relates to

1. Reusable react components (e.g. form with a lot of complex logic, or just part of that form like accordion field)
2. Reusable app modules (like authorization)
3. Reusable Client API (e.g. for mocking http requests)

In fact, we have these "objects" and we use them in our tests. But which term to use to name them?)

There are alternative term you have – fixtures. But as far as I understand it is 1) not an "object" but rather a mechanism of composing these objects 2) relates only to playwright.

Is there are common and widely accepted in QA term for something we want to call `PageObject of component, not page`? If no, could we invent it right here?)

**Comment by pavelfeldman** [comment]
We don't own the names, but I think COM (component object model) sounds great :)
