### ISSUE TITLE
[BUG] Experimental CT: Svelte named Slots 

### ISSUE THREAD

**Issue by aMediocreDad** [microsoft/playwright#15820]
**Context:**
- Playwright Version: experimental-ct-svelte": 1.23.4
- Operating System: Mac / Linux
- Node.js version: 16.14.2 / 18.5.0
- Browser: All
- Extra: *
 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Reproduction**: https://github.com/aMediocreDad/playwright-svelte-slots-repro

```js
import { test, expect } from "@playwright/experimental-ct-svelte";

import Component from "./slot-example.svelte";

test("Named Slots", async ({ mount }) => {
	const component = await mount(Component, {
		props: {
			title: "Named Slots",
		},
		// This should work
		slots: {
			text: "Hello World",
		},
	});

	const title = component.locator("h1");

	await expect(title).toHaveText("Named Slots");

	const text = component.locator("p");

	// Yet, this fails
	await expect(text).toContainText("Hello World");
});
```

**Describe the bug**

While this is *experimental* the [FAQ](https://github.com/microsoft/playwright/issues/14298) indicates that you can pass (text) to named slots when mounting the Svelte component. 

This seems to be wrong. It would, however, be a desirable feature.

**Comment by sand4rt** [comment]
related to: https://github.com/sveltejs/svelte/issues/2588

**Comment by aMediocreDad** [comment]
> related to: [sveltejs/svelte#2588](https://github.com/sveltejs/svelte/issues/2588)

I was under the impression that Playwright had some custom code that did this. Injecting slots programmatically when mounting Svelte components has never been a feature in Svelte 3. It does, however, look like it is possible when using an editor like VS Code and the Svelte LSP, this because of an internal handler for the typing of the component that unfortunately has to be exposed.

**Comment by bhvngt** [comment]
I stumble upon this while playing around with component testing for my svelte components. As @aMediocreDad said, seems like passing of slots (default or named) is not working out of the box. 

@aMediocreDad Did you manage to make it work for your use case by following sveltejs/svelte#2588. Code there does not seem to work for me.

**Comment by aMediocreDad** [comment]
> @aMediocreDad Did you manage to make it work for your use case by following sveltejs/svelte#2588. Code there does not seem to work for me. 

No, I have not tried using those solutions. We use the same solutions we do for Storybook, which is using a svelte component that wraps the one being tested populating the slot with relevant parameters exposed through props.

**Comment by bhvngt** [comment]
Thanks @sand4rt for addressing this issue. The included [test](https://github.com/sand4rt/playwright/blob/1fb7d8697eca9a61dcc1137c9decd69f8ca8b589/tests/components/ct-svelte-vite/src/components/NamedSlots.svelte) passes text content to the slot. Is it also possible to pass components to slots?

**Comment by sand4rt** [comment]
@bhvngt lets track that in: https://github.com/microsoft/playwright/issues/15900
