### ISSUE TITLE
[Feature] Modify response body of a fulfilled routes request

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#15835]
Add an option to intercept the request response and modify the body. Currently this doesn't seem to be possible, so we are working around it with `page.route` + `route.fulfil`

Example:

```js
await context.route("**/graphql/", async route => {
  const response = await context.request.fetch(route.request())
  const responseData = (await response.json()) as GraphQLResponse
  
  const data = handler(responseData.data) // modify the data with a handler here
  return route.fulfill({
    response,
    status: 200,
    contentType: "application/json",
    headers: response.headers(),
    body: JSON.stringify({
      data,
    }),
  })
}
```

This is not ideal, because requests are now made via `context.request.fetch` which is not 100% identical to the default browser request.

**Comment by dgozman** [comment]
@Meemaw Your snippet is the intended way to modify the response, see original issue #1774. Here is [the documentation](https://playwright.dev/docs/network#modify-responses).
