### ISSUE TITLE
[Question]How to verify a document opening in new tab after clicking a button

### ISSUE THREAD

**Issue by AmanDaharwal** [microsoft/playwright#15834]
In our web application, we have a button, on click opens document( pdf) in new tab. How we can verify the document is successfully opened( may be using response code) in new tab?

**Comment by dgozman** [comment]
Usually, a new tab will produce another `page` that you can check for various conditions like a url. Take a look at [this guide](https://playwright.dev/docs/pages#handling-popups).

That said, pdf documents usually end up as a download, so you might need to expect a download instead. Follow [this guide](https://playwright.dev/docs/downloads) in such a case.

Let me know if this didn't help.
