### ISSUE TITLE
[Question] Playwright test runner with different browser engine?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15846]
Is that possible to use playwright-test with different browser engine, not just playwright? Like puppeteer, webdriver or protractor?

I like fixtures and retries, but what if I want to use different engine?

**Comment by dgozman** [comment]
@Diokuz You can use `@playwright/test` as a general-purpose test runner. Just add your own fixtures, or overwrite existing ones, and use any other library you'd like. [This guide](https://playwright.dev/docs/test-fixtures) should get you started.
