### ISSUE TITLE
[Feature] Add option to compress *.har files into zip archives

### ISSUE THREAD

**Issue by joshuacc** [microsoft/playwright#15845]
My team recently hit an issue where after enabling the `recordHar` option for failures we ran out of storage space for our test runs pretty quickly. After investigating we saw that the har files were on average about 8 times larger in size than the Playwright trace files we also save.

Compressing the har files into a zip archive results in a huge improvement in storage. For example, a 40mb har file compresses to about 10mb using Windows' default zip compression settings.

It would be great if `recordHar` also supported an option to save the har into a zip archive at the time of creation. (Something like `compressToZip`?) Because Playwright already records its trace files into zip archives, I imagine that this would be a relatively simple change to the code and potentially save users a lot of storage space. :)

**Comment by dgozman** [comment]
If you pass `recordHar.path` that ends with `.zip`, har will be compressed automatically. Take a look [at the API docs](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-har) for more available options, for example `recordHar.content`. Let me know if this didn't help.

```js
await browser.newContext({ recordHar: { path: 'mypage.har.zip' } });
```

**Comment by joshuacc** [comment]
@dgozman Thanks for pointing that out!
