### ISSUE TITLE
[BUG] Chrome and Webkit always return null for postDataBuffer

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#15853]
**Context:**
- Playwright Version: 1.23.4
- Operating System: Mac
- Node.js version: 18.3.0
- Browser:  Webkit, Chromium

## System:
 - OS: macOS 12.4
 - Memory: 99.64 MB / 16.00 GB
## Binaries:
 - Node: 18.3.0 - ~/.volta/tools/image/node/18.3.0/bin/node
 - Yarn: 3.2.1 - ~/.volta/tools/image/yarn/1.22.18/bin/yarn
 - npm: 8.13.2 - ~/.volta/tools/image/npm/8.13.2/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

See repro in this repository:
https://github.com/weyert/playwright-request-data-bug

**Describe the bug**

I am trying to intercept outgoing POST network requests from a third-party analytics company only I am unable to get the raw request data because the `request.postDataBuffer`-method always returns `null` in this case

**Comment by mxschmitt** [comment]
Looks similar to https://github.com/microsoft/playwright/issues/6479.

**Comment by dgozman** [comment]
Thank you for the repro! Merging into https://github.com/microsoft/playwright/issues/6479.
