### ISSUE TITLE
how to handle captcha (v2) [Question]

### ISSUE THREAD

**Issue by matt-seedata-io** [microsoft/playwright#15850]
we have introduced captcha into our login journey and signup journey, and our previous e2e test script now (predictably) fails. How  should captcha be incorporated within a test script?

**Comment by weyert** [comment]
I think you need to disable it for your test users

**Comment by dgozman** [comment]
As @weyert suggests, you need a testing mode where captcha is disabled. Playwright is not able to solve captchas for you 😄
