### ISSUE TITLE
[Question] Chromium distribution 'msedge-canary' is not found

### ISSUE THREAD

**Issue by fara20222** [microsoft/playwright#15859]
I'm setting up a docker image to test our features in Edge Canary using Playwright. In the docker environment, Edge Canary is installed at C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Edge SxS/Application/msedge.exe. However, Playwright tries to launch Edge at a different location, as indicated in the error message below. 

I tried to specify executablePath as below to where Edge Canary is installed. However, I still get the same error message and it looks like the setting is not taking effect. I have also attached the basic structure of our test scripts as below. 

Please let me know how we can have Playwright launch Edge Canary. Thank you.

-----Error message-----
```
browserType.launchPersistentContext: Chromium distribution 'msedge-canary' is not found at C:\Users\ContainerAdministrator\AppData\Local\Microsoft\Edge SxS\Application\msedge.exe
designerapp-app-1  |
designerapp-app-1  |        9 |
designerapp-app-1  |       10 | test.beforeAll(async ({ playwright, browserName }) => {
designerapp-app-1  |     > 11 |   context = await playwright[browserName].launchPersistentContext('C:\\temp-edge\\edge-dev-profile');
designerapp-app-1  |          |             ^
designerapp-app-1  |       12 |   page = context.pages()[0];
designerapp-app-1  |       13 |   await signInToTwitter(page, playwright);
designerapp-app-1  |       14 | });
```

-----Config with executablePath----------
```
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    browserName: 'chromium',
    acceptDownloads: true,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    channel: 'msedge-canary',
    **executablePath: 'C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Edge SxS/Application/msedge.exe',**
    launchOptions: {
      args: ['--enable-features=msEdgeDesignerUI'],
    },
  },
  expect: {
    toMatchSnapshot: { threshold: 0.1 },
  },
};
```
----Basic test structure--------
```
import { expect, test, BrowserContext, Page } from '@playwright/test';

import { signInToTwitter } from '../flyout-playwright-utils';

test.describe.configure({ mode: 'serial' });

let context: BrowserContext;
let page: Page;

test.beforeAll(async ({ playwright, browserName }) => {
  context = await playwright[browserName].launchPersistentContext('C:\\temp-edge\\edge-dev-profile');
  page = context.pages()[0];
});

test.afterAll(async () => {
  await page.close();
});

test('Verify the flyout in Twitter', async () => {
});
```

**Comment by mxschmitt** [comment]
If you specify you don't need to specify a channel. Does it work if you just specify the executablePath?

**Comment by fara20222** [comment]
Hi Max, I appreciate your quick reply. If I don't specify a channel, it will pop up the following error asking me to do npx playwright install. Since I'm using Edge Canary installed myself, do I need to do px playwright install?

browserType.launchPersistentContext: Executable doesn't exist at C:\Users\ContainerAdministrator\AppData\Local\ms-playwright\chromium-1011\chrome-win\chrome.exe
designerapp-app-1  |     ╔═════════════════════════════════════════════════════════════════════════╗
designerapp-app-1  |     ║ Looks like Playwright Test or Playwright was just installed or updated. ║
designerapp-app-1  |     ║ Please run the following command to download new browsers:              ║
designerapp-app-1  |     ║                                                                         ║
designerapp-app-1  |     ║     npx playwright install                                              ║
designerapp-app-1  |     ║                                                                         ║
designerapp-app-1  |     ║ <3 Playwright Team                                                      ║
designerapp-app-1  |     ╚═════════════════════

If I do npm playwright install, it will pop up the below warning, and when running the test, it still says chrome.exe is not found.

WARNING: It looks like you are running 'npx playwright install' without first ║
║ installing your project's dependencies.                                       ║
║                                                                               ║
║ To avoid unexpected behavior, please install your dependencies first, and     ║
║ then run Playwright's install command:                                        ║
║                                                                               ║
║     npm install                                                               ║
║     npx playwright install                                                    ║
║                                                                               ║
║ If your project does not yet depend on Playwright, first install the          ║
║ applicable npm package (most commonly @playwright/test), and                  ║
║ then run Playwright's install command to download the browsers:               ║
║                                                                               ║
║     npm install @playwright/test                                              ║
║     npx playwright install

browserType.launchPersistentContext: Executable doesn't exist at C:\Users\ContainerAdministrator\AppData\Local\ms-playwright\chromium-1011\chrome-win\chrome.exe
designerapp-app-1  |     ╔═════════════════════════════════════════════════════════════════════════╗
designerapp-app-1  |     ║ Looks like Playwright Test or Playwright was just installed or updated. ║
designerapp-app-1  |     ║ Please run the following command to download new browsers:              ║
designerapp-app-1  |     ║                                                                         ║
designerapp-app-1  |     ║     npx playwright install                                              ║
designerapp-app-1  |     ║                                                                         ║
designerapp-app-1  |     ║ <3 Playwright Team

**Comment by dgozman** [comment]
@fara20222 The last error message suggests that you don't have `@playwright/test` in your dependencies. Do what it suggests:

```bash
npm install @playwright/test
```

The first error message suggests that your `executablePath` is ignored. That's because you should put into `launchOptions`:
```ts
const config: PlaywrightTestConfig = {
  use: {
    headless: false,
    browserName: 'chromium',
    acceptDownloads: true,
    viewport: { width: 1280, height: 720 },
    screenshot: 'only-on-failure',
    channel: 'msedge-canary',
    launchOptions: {
      args: ['--enable-features=msEdgeDesignerUI'],
      executablePath: 'C:/Windows/System32/config/systemprofile/AppData/Local/Microsoft/Edge SxS/Application/msedge.exe',
    },
  },
  expect: {
    toMatchSnapshot: { threshold: 0.1 },
  },
};
```

Let me know if that helps.

**Comment by fara20222** [comment]
Thank you so much, Dmitry. Moving it to launchOptions solves the problem for me.
The interesting thing was that I have both @playwright/test 1.23.4 and playwright 1.23.4 in my dependencies, and chromium-1012 on my machine, but Playwright wanted chromium-1011. Anyway, problem solved :)

**Comment by dgozman** [comment]
@fara20222 I am happy that it helped! To avoid issues in the future, you should only have `@playwright/test` in your deps, but not `playwright`.
