### ISSUE TITLE
Surface Credit Card Autofill on Google Chrome on www.amazon.com

### ISSUE THREAD

**Issue by sanjoyghosh** [microsoft/playwright#15867]
Hello,

I am trying to write a Playwright Script to surface the Credit Card Autofill on www.amazon.com when you have GPay Credit Card on file at pay.google.com.  When you try to add a Credit Card to your amazon account on Google Chrome, if you click in the "Card number" text box, it should popup all the Credit Cards registered with pay.google.com to the user profile that you are signed into Google Chrome with.  So the script is, on Google Chrome

1) Make sure your user profile is signed in with a Google Account that has a GPay account associated with it.
2) Make sure you have opted in to Sync your Google Chrome browser.
3) Log into your www.amazon.com account.
4) Try to add a Credit Card.
5) In the Add a credit or debit card iFrame, click in the Card number text box.
6) Chrome will surface all the Credit Cards on file with pay.google.com as a popup.

I am using the following script to do this.  For this script to work, make sure you are **not** logged into amazon.com at the start.

The problem is with the script the GPay Credit Cards popup doesn't pop.  When I manually click, they popup.  What am I doing wrong in the script?  I am assuming the problem is in the last line of the script.  The last click() doesn't bring up the popup.

Thanks,
Sanjoy

```
const playwright = require("playwright-core");

(async () => {
  const browser = await playwright.chromium.launchPersistentContext(
    '/Users/<user>/Library/Application Support/Google/Chrome',
    {
    headless: false,
    executablePath: '/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome',
    remoteDebuggingPort: 9222,
    ignoreDefaultArgs: ['--enable-automation'],
    args: [
      '--disable-blink-features=AutomationControlled',
    ],
  })
  const page = await browser.newPage()
  await page.goto('https://www.amazon.com/');
  await page.goto('https://www.amazon.com/cpe/yourpayments/wallet');
  await page.locator('id=ap_email').fill('<email>');
  await page.locator('.a-button-input').click();
  await page.locator('id=ap_password').fill('<password>');
  await page.locator('id=signInSubmit').click();
  await page.locator('text=Add a payment method').click();
  await page.locator('text=Add a credit or debit card').first().locator("xpath=..").first().click();
  const thisFrame = await page.frameLocator('iframe').first();
  await thisFrame.locator('[name="addCreditCardNumber"]').click();
  // await browser.close();
})()


```

**Comment by dgozman** [comment]
@sanjoyghosh That's probably because Chrome does not want to do this when controlled by automation. Try passing `ignoreDefaultArgs: true` to see whether it helps. Otherwise, not sure how we can help.

**Comment by dgozman** [comment]
Closing as per above.
