### ISSUE TITLE
[Question] Playwright + MutationObserver

### ISSUE THREAD

**Issue by chaganiu** [microsoft/playwright#15869]
I'd like to use Playwright + MutationObserver to handle a situation where my application has random loader elements show up.  A simplified use-case that i'm trying to handle is like this:

1. fill input A
2. click button B
3. **Sometimes** loader shows up, disappears, **sometimes** shows up a 2nd time, disappears.
4. fill input C
5. click button D

While the loader is present, if I fill input C, once the loader disappears, input C will be cleared out by the application.  Input C will pass actionability checks while the loader is present and so I can't just wait on it because it will always be actionable.

The above happens on various pages across our application.

I had the idea of using mutation observers to watch for the loader element, and if it shows up, wait for it to disappear.  

Could I use playwright and mutation observers together to pause execution of the script until the loader disappears?  That way no matter how many times (or when) the loader shows up my script will pause/resume automatically?

**Comment by dgozman** [comment]
@chaganiu I think you cannot solve this problem 100% reliable, because you don't know whether the loader will show up. However, you can give it some time to appear and then wait for it to disappear like this:

```js
await page.locator('.input-a').fill('value');
await page.locator('.button-b').click();

// Catch in the next line to avoid failures when the loader does not appear.
await page.locator('.loader').waitFor('visible', { timeout: 3000 }).catch(() => {});
// Make sure loader is not shown anymore or at all.
await expect(page.locator('.loader')).toBeHidden();

await page.locator('.input-c').fill('value');
await page.locator('.button-d').click();
```

Let me know if this helps.

**Comment by chaganiu** [comment]
@dgozman this is what i'm doing now but i wanted to avoid putting these types of waits all over my tests since it happens in a lot of places/pages.

That's why i thought if there was a way for the DOM to tell me when the loader shows up (via mutation observer or some other method), then i could wait until it disappears somehow?

**Comment by dgozman** [comment]
@chaganiu But even with the mutation you will still have to wait for some time to make sure the loader either did appear or it didn't. As you say, you want to "pause execution of the script until the loader disappears", but that means pausing for some time until you are certain it will not appear at all. At least, that's how I understand your problem.

**Comment by chaganiu** [comment]
I guess i was wondering if there was some way for the callback in the mutation observer to pause the playwright script.

**Comment by dgozman** [comment]
@chaganiu There's no such thing. But also it won't help, since by the time this callback would run, your script could have already executed the second `fill()`, and therefore the input would be cleared anyway.

**Comment by dgozman** [comment]
I guess I'll close this, since the question was answered.
