### ISSUE TITLE
[Question]What is the difference between waitForEvent('load') and waitForLoadState('load')?

### ISSUE THREAD

**Issue by rokumura7** [microsoft/playwright#15868]
Is there any difference between waitForEvent('load') and waitForLoadState('load') other than the return value?

**Comment by dgozman** [comment]
@rokumura7 You can call `waitForLoadState('load')` at any moment, even after `'load'` has already happened. With `waitForEvent('load')` you'll make sure there that page is not loaded right now, but will get a load event in the future.

**Comment by rokumura7** [comment]
Thank you for your answer. I will try to use it in the right place at the right time :)
