### ISSUE TITLE
[Feature] Locate element by focus 

### ISSUE THREAD

**Issue by Miciurash** [microsoft/playwright#15865]
As a developer I would like to get the element the focus is on.

We currently have `elementHandle.focus()`, `page.focus(selector[, options])` and `frame.focus(selector[, options])`.

It would be great to have a method that could **return the element on which we have the focus on**.

**Comment by Miciurash** [comment]
Good point @chaganiu! Wouldn't we expect that to be part of the Playwright framework and work for both Page and Frame ?

**Comment by dgozman** [comment]
@Miciurash What do you want to do with the focused element? Assert it? Click on it? Something else? Depending on the usecase, we might have a different API.

For now, you can get it through evaluate:
```js
const focusedElementText = await page.evalute(() => document.activeElement.textContent);
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by naemtl** [comment]
I'm having this same issue, and I'm not able to get past it with the current solution!

`const focusedElementText = await page.evalute(() => document.activeElement.textContent);`

If I try: 

```
const focusedElement = await page.evalute(() => document.activeElement);
await focusedElement.click()
```

I get: ` TypeError: focusedButton.click is not a function`

**Comment by dgozman** [comment]
@naemtl Try using [`:focus`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) CSS pseudo.

```js
await page.locator('*:focus').click();
```

**Comment by lawrencecushman** [comment]
> @naemtl Try using [`:focus`](https://developer.mozilla.org/en-US/docs/Web/CSS/:focus) CSS pseudo.
> 
> ```js
> await page.locator('*:focus').click();
> ```

Did this work for you?

**Comment by johan-gorter** [comment]
`:focus` worked really well in my case

**Comment by imdfl** [comment]
> I'm having this same issue, and I'm not able to get past it with the current solution!
> 
> `const focusedElementText = await page.evalute(() => document.activeElement.textContent);`
> 
> If I try:
> 
> ```
> const focusedElement = await page.evalute(() => document.activeElement);
> await focusedElement.click()
> ```
> 
> I get: ` TypeError: focusedButton.click is not a function`

The element returned from `evaluate` is serialized, you don't get a live object so its api is gone.
