### ISSUE TITLE
[BUG] Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory

### ISSUE THREAD

**Issue by berelton** [microsoft/playwright#15870]
Hi, getting following issue with playwright in docker with gitlab-ci:

```
  pw:browser [pid=524][err] [524:540:0722/041731.757207:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") +204ms
  pw:browser [pid=524][err] [524:540:0722/041731.757276:ERROR:bus.cc(398)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix") +1ms
  pw:browser [pid=524][err] [524:541:0722/041731.760019:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory +2
```

I created a repo with issue reproducible:
https://gitlab.com/berelton/playwright-issue

You can check the job logs:
https://gitlab.com/berelton/playwright-issue/-/jobs/2755635983

image used: `mcr.microsoft.com/playwright:v1.24.0-focal`

**Comment by dgozman** [comment]
I see the following error in the logs:

```log
  pw:browser [pid=170][err] libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null) +42ms
  pw:browser [pid=170][err] [197:197:0722/0[42](https://gitlab.com/berelton/playwright-issue/-/jobs/2755635983#L42)127.378343:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization +6ms
  pw:browser [pid=170][err] libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null) +24ms
  pw:browser [pid=170][err] [221:221:0722/042127.412392:ERROR:gpu_memory_buffer_support_x11.cc([44](https://gitlab.com/berelton/playwright-issue/-/jobs/2755635983#L44))] dri3 extension not supported.
```

Try passing `--disable-gpu` flag to see whether it helps:
```js
const config = {
  // ...
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        // Add the next line:
        launchOptions: { args: ['--disable-gpu'] },
      },
    },
  ],
};


```

**Comment by berelton** [comment]
> ```js
> launchOptions: { args: ['--disable-gpu'] },
> ```

@dgozman thanks for the reply. This did not help :(

https://gitlab.com/berelton/playwright-issue/-/jobs/2759902752

**Comment by dgozman** [comment]
@berelton Oh, it looks like you are launching the browser yourself. You should add `--disable-gpu` [here instead](https://gitlab.com/berelton/playwright-issue/-/blob/master/tests/utils/test.js#L17). Sorry, that was not clear to me the first time.

**Comment by berelton** [comment]
> @berelton Oh, it looks like you are launching the browser yourself. You should add `--disable-gpu` [here instead](https://gitlab.com/berelton/playwright-issue/-/blob/master/tests/utils/test.js#L17). Sorry, that was not clear to me the first time.

@dgozman same :(

https://gitlab.com/berelton/playwright-issue/-/jobs/2760236085

**Comment by aslushnikov** [comment]
This has something to do with your custom fixtures; running just plain Playwright works fine: https://gitlab.com/aslushnikov/playwright-issue/-/jobs/2768557930

**Comment by serembon** [comment]
@aslushnikov I have a similar problem, with one worker your example works, but if more than one then the error remains

**Comment by serembon** [comment]
Addition: when setting up with 2 or more workers, the playwright opens new pages in the first context instead of creating new contexts. This happens both in CI and when run locally.

**Comment by serembon** [comment]
I have found the problem:

If `userDataDir` provided, for instance `/tmp/user-data-dir` - error occurs; if not - tests starts correct

https://gitlab.com/serembon/playwright-issue

`npm run test`

**Comment by dgozman** [comment]
@serembon If you run with multiple workers, you should pass different `userDataDir` in each worker. It is impossible to run two browser instances pointing to the same user data dir at the same time.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
