### ISSUE TITLE
[Question] Browser versions in 1.24 release notes

### ISSUE THREAD

**Issue by mirao** [microsoft/playwright#15877]
Is it possible to add browsers used in 1.24 here: https://github.com/microsoft/playwright/releases/tag/v1.24.0 ?

I can see them in https://github.com/microsoft/playwright/releases/tag/v1.23.4 only

**Comment by aslushnikov** [comment]
Oops, fixed!


Browser Versions: 

- Chromium 104.0.5112.48
- Mozilla Firefox 102.0
- WebKit 16.0

Stable channels:

- Google Chrome 103
- Microsoft Edge 103
