### ISSUE TITLE
[Question] Is it possible to get selectors from ElementHandle

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#15875]
Hi,

Thanks for this cool project.
If I have an ElementHandle, is it possible to generate all possible selectors that would (uniquely) identify this element?

As an example use case, let's suppose I have a selector that resolves to three elements.
For these three elements I want to have alternative selectors such that in the future I can uniquely identify them and I cannot use `nth` as the order of these three elements is random.

**Comment by dgozman** [comment]
@JannisBush This is not possible today. Could you please lLet us know how you intend to use it?

Note that if you call `locator.click()` for example, and selector does not uniquely identify the element, Playwright will suggest unique selectors for all the matching elements in the error message. Does that work for you?

**Comment by JannisBush** [comment]
@dgozman The idea is that I manually find some interesting elements on some pages and want to find similar elements on other pages automatically. If I only use the manually created selectors from the beginning, I will miss many elements that do not match the selectors. Thus, I want to extend the set of selectors during the crawl by adding alternative selectors for the elements I already found in the hope that these new selectors match more elements on other pages.

Thanks for the hint about `locator.click()`. Using the exception works as long as the initial locator is not already unique.

**Comment by dgozman** [comment]
@JannisBush Thank you for the details. Since the workaround works for you, I'll close this issue.
