### ISSUE TITLE
[Feature] axe-core(web accessibility testing plugin) support for Playwright Java

### ISSUE THREAD

**Issue by KSingla15** [microsoft/playwright#15872]
I think accessibility testing is equally important to functional and visual testing for a web application.

I am currently using Playwright-Java as an automation tool for functional testing and there is no support for accessibility testing with Playwright-Java. However, there is support available for Playwright-Node.js.

Could you please consider extending accessibility testing support to Playwright Java as well?

**Comment by dgozman** [comment]
See issue #14112 for a plan.

@dbjorge Here is a request for the Java version. I remember you wanted to add it as well 😄
