### ISSUE TITLE
how to skip download web driver when i npm install?

### ISSUE THREAD

**Issue by sonacy** [microsoft/playwright#1587]
for puppeteer, it has PUPPETEER_SKIP_CHROMIUM_DOWNLOAD,  but seems playwright do not support it.  my case is i need to use it in self docker hub. but i can not skip install web driver? any solutions?

**Comment by mxschmitt** [comment]
Instead of using the `playwright` package, you can use e.g. `playwright-chromium` to only download chromium. If you want to install no browsers at all you can use `playwright-core`.

**Comment by woutervanwijk** [comment]
For people searching for a solution: use PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD
See https://playwright.dev/#path=docs%2Finstallation.md&q=skip-browser-downloads

**Comment by acro5piano** [comment]
@woutervanwijk Thank you very much!

The link moved here: https://playwright.dev/docs/browsers#skip-browser-downloads

**Comment by NedWilbur** [comment]
Documentation for this moved again: https://playwright.dev/docs/library#browser-downloads
