### ISSUE TITLE
[REGRESSION]: Error: multipleDefine and Page is not a constructor (dojo), when trace is set to on.

### ISSUE THREAD

**Issue by MichalFidor** [microsoft/playwright#15878]
**Context:**
- GOOD Playwright Version: 1.20.2
- BAD Playwright Version: 1.21.1
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const config: PlaywrightTestConfig = {
  testDir: './test',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  quiet: true,
  expect: {
    timeout: 5000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    actionTimeout: 0,
    headless: false,
    ignoreHTTPSErrors: true,
    bypassCSP: true,
    browserName: 'chromium',
    baseURL: <app-url>,
    viewport: {
      height: 900,
      width: 1400,
    },
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',
    launchOptions: {
      devtools: false,
      args: [
        '--disable-web-security',
        '--no-sandbox',
        '--disable-site-isolation-trials'
      ]
    }
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

  ],

};
```

**Describe the bug**

I’ve wanted to upgrade our `@playwright/test` runner to the newest one (1.23.4 and now 1.24) from 1.20.2. When I’ve did it, then everything was going good, until a set of test cases which are checking the authentication part between apps which we have in the flow. Those just login in one app and checks if we are logged in in the other app. Anyway, the problem is that, on one of the older application, during the test execution the browser doesn’t wan’t to load the page. In the browser console I can see the error relating to dojo

```
Error: multipleDefine
    at _f (https://<page-url>.com/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:436)
    at _fa (https://<page-url>/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:16552)
    at https:/<page-url>/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:17143
    at _9 (https://<page-url>o.com/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:328)
    at _7f (https://<page-url>.com/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:17112)
    at _f4 (https://<page-url>.com/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:15156)
    at HTMLScriptElement._10a (https://<page-url>.com/share/res/js/lib/dojo-1.10.4/dojo/dojo.js:15:18265)
```

and I thought that it was a problem with the app itself (because of the stack trace). But no. After a day of investigation I saw, that Playwright trace is the issue here. When it was recording the test execution, then this issue is appearing. When I’ve disabled trace from config, then the app is normally loading up. Once or twice, I've also have seen the other log which came from `dojo` which is `Page is not a constructor`. Why it can happening?

Unfortunately I can't provide the URLs and credentials cause it's the interior company product. If you will need it, then maybe I can find some page, where this issue is also appearing (will be hard)...

**Comment by dgozman** [comment]
@MichalFidor It could be that code that collects snapshots for the trace file has some kind of conflict with dojo. However, I am not sure what to do without a page that has this problem. If you could get this reproduced with un-minified dojo source, maybe we can make sense of the issue by reading the source around the stack trace locations, but that's a stretch.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
