### ISSUE TITLE
[BUG] codegen stalls browser for some sites, even the close button is not working anymore

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#15874]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Linux, Mac
- Browser: Chromium, (Firefox)
- Extra: codegen

**Code Snippet**
Run `playwright codegen cloudflare.com`

**Describe the bug**

Wait for the site to load, then click outside of the cookie banner.
After that you cannot click anywhere anymore, only scrolling still works. 
Even the close button of the browser is not working anymore (minimize and maximize still work).
In Firefox, the close button still works but only with a double click. 
WebKit does not seem to be affected.

This is the only site where I have seen a complete stall of the browser, however on other sites I had additional issues with codegen that some elements could not be clicked or only a double click on them worked which might be related to this bug.

**Comment by clehene** [comment]
@dgozman
Curious what caused the actual stall behavior and how to debug it. 
We're seeing this across all browser for a particular webpage (can't share) but could share some relavant details if I know how
