### ISSUE TITLE
Playwright JAVA -- Inspector[Question]

### ISSUE THREAD

**Issue by chandruswaminathan** [microsoft/playwright#15880]
Hi,

I am trying to invoke the inspector from command prompt. The web page which I use has a self signed certificate and after invoking the inspector getting error as  below. Is it possible to ignore the HTTPSError during inspector. Thanks in advance
{
  name: 'Error'
}

Regards,
Chandru

**Comment by dgozman** [comment]
Try the following command:

```bash
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="open --ignore-https-errors"
```

Get a list of all options applicable to `open` command:

```bash
mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="open --help"
```
