### ISSUE TITLE
[BUG] Trace not correctly generated when using npx playwright open --save-trace

### ISSUE THREAD

**Issue by michaelchiche** [microsoft/playwright#15883]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Linux
- Node.js version: 16.16.0
- Browser: Chrome

**Code Snippet**

```bash
# Works as expected
npx playwright codegen --save-trace trace --save-storage cookie.json --save-har har.har https://playwright.dev 

# Does not work as expected
npx playwright open --save-trace trace --save-storage cookie.json --save-har har.har https://playwright.dev 

npx playwright show-trace trace

```

When generating a trace with `npx playwright --save-trace trace open ` I dont have all the steps, nor the console & network tabs filled with data when opening the trace using `npx playwright show-trace trace`
but it does work when usig `codegen`

**Comment by dgozman** [comment]
@michaelchiche Indeed! That's because `open`, as opposite to `codegen`, does not really record any actions.

We can probably remove this flag from `open`, but you can always turn on codegen in the UI and the actions will be recorded. Does that work for you?

**Comment by michaelchiche** [comment]
Hi @dgozman . That's fine by me. But I just thought it was weird. I expected both to have the same behavior.

I guess removing the flag from `open` does the trick :)
