### ISSUE TITLE
[Feature] Component testing and page.goto

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#15889]
**Context:**
- Playwright Version: 1.24.0
- Operating System: All
- Node.js version:  v17.3.0
- Browser: Chromium
- Extra: Vue component testing

I've been playing with the Vue component testing feature and it seems like the `page.goto()` is not working properly.

For example 
[i have a failing test that should be passing](https://github.com/sand4rt/TVmaze/blob/master/src/Features/NotFound/NotFoundPage.test.ts).

It should navigate to the 404 page because i have a catch all specified [`/:pathMatch(.*)*`](https://router.vuejs.org/guide/essentials/dynamic-matching.html#catch-all-404-not-found-route) inside Vue router [see the code here](https://github.com/sand4rt/TVmaze/blob/master/src/Router/Index.ts#L52).

The Vue router plugin is registered [here](https://github.com/sand4rt/TVmaze/blob/master/playwright/index.ts).

[Here](https://github.com/sand4rt/TVmaze/blob/master/src/Features/Browse/BrowsePage.test.ts#L61) you can see another example that also uses the `page.goto` function that i can't get to work.

**Comment by sand4rt** [comment]
[Here](https://github.com/sand4rt/TVmaze/blob/master/src/Features/Browse/BrowsePage.test.ts#L61) you can see another example that also uses the `page.goto` function that i can it goes to work.

**Comment by pavelfeldman** [comment]
I believe `page.goto` works as expected here. What it does is it navigates the page to the specified URL and navigation is resetting the world along with all the JS state, as it is supposed to. No wonder none of the installed routers work. Non-anchor navigation is equivalent to going to a new URL via `about:blank`. In order to perform the navigation that router can handle, you should actually click on a router-aware link or you should know the mechanics that the framework uses to support routing. In most cases it'll be history API, so instead of `page.goto` you should do

```js
await page.evaluate(() => {
  window.history.pushState('', '', '/route-not-exsist-5b45f7cd193ecc56339c64428079706a');
});
```

It is saying "Perform SPA navigation to the new URL that history controller will handle".

**Comment by pavelfeldman** [comment]
For the second use case, it would be something like this:

```js
// Typically mount() navigates to the component registry page (playwright/index.html)
// I'm doing it manually here, but we can probably make it work automatically as the test starts. It will install the router.
await page.goto(process.env.PLAYWRIGHT_VITE_COMPONENTS_BASE_URL!);
// Make navigation that router can handle using history API, not hard page.goto:
await page.evaluate(() => {
    window.history.pushState('', '', '/search?query=DOES_NOT_EXSISTS');
  });

// Sadly, I think that another page.goto() that goes to playwright/index.html inside this mount() might reload the page and reset the state.
await mount(BrowsePage);
```

Navigating to `playwright/index.html` before `mount()` is consistent with your `unmount` request, so I think we can try making that change.

**Comment by sand4rt** [comment]
Thanks for explaining! Yes, makes sense. Yeah i believe it's either history mode or hash mode. 

The first use case/test is works!

Navigating before mount doesn't work yet. Need to debug it a little further but looks like the [navigation will be reset when mounting](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/mount.ts#L38).  

Don't you think that the API for navigating in SPA's is a bit too verbose? Also i think the `config.use.baseURL` setting is not respected when using `page.evaluate(() => window.history.....)` right?

Why not something like?:

```typescript
page.goto('/route-not-exsist', { mode: 'history' })
```

**Comment by pavelfeldman** [comment]
> Don't you think that the API for navigating in SPA's is a bit too verbose? I think the config.use.baseURL setting is not respected when using page.evaluate(() => window.history.....) as well right?

Well, the document's [baseURL](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base) will be used, which is different from our baseURL.

> Why not something like page.goto('/route-not-exsist', { mode: 'history' })?

No real reason to not add it, we can have that sugar. We can convert this issue into the request for this feature.

**Comment by sand4rt** [comment]
Unfortunately, it looked like the first test passed but it wasn't.. Did some debugging and found out that `window.history.pushState()` doesn't trigger the Vue router. So this won't work:

```typescript
await page.evaluate(() => {
  // history.state is needed because of: https://router.vuejs.org/guide/migration/#usage-of-history-state
  window.history.pushState(history.state, '', '/route-not-exsist-5b45f7cd193ecc56339c64428079706a');
});
```

Created an [example application](https://sand4rt.github.io/playwright-component-testing-vue/) to illustrate this. Code can be viewed [here](https://github.com/sand4rt/playwright-component-testing-vue/blob/page.goto/src/components/Component.vue). See also the [failing tests](https://github.com/sand4rt/playwright-component-testing-vue/blob/page.goto/src/components/Component.test.ts).

Don't know yet if other routers allow URL changes trough `window.history.pushState` and if there is a workaround for that?  Did you want to handle this in a feature request for the `page.goto('/', { mode: 'history' })` sugar?

**Comment by pavelfeldman** [comment]
I'm not surprised - the way routers work is their implementation detail. The contract is that they would give you a way to create a link and that link would work. So the test for it would suggest that you are clicking the link instead.

**Comment by sand4rt** [comment]
I don't think a link is the only contract. Users are able to type the url in the browsers address bar as wel _(aka 'page.goto')_.

IMO we should be able to mimic the user's behavior even if this reloads the JS state.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
