### ISSUE TITLE
[Question]Is there a way to do emulation using `launchPersistentContext `?

### ISSUE THREAD

**Issue by sandogeek** [microsoft/playwright#15903]
I found a way to do emulation using `launch` here https://playwright.dev/docs/emulation.
It is inconvenient since I need to login every time.
Thanks for any help.

**Comment by pavelfeldman** [comment]
I'm not sure I understand your request, if you are using persistent context, you can login once and the context will keep your logged in state.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
