### ISSUE TITLE
[Question]How to Open Brave Tor using the launch method ?

### ISSUE THREAD

**Issue by morkos11** [microsoft/playwright#15908]
i was wondering how to open Brave Tor using the launch method , i already try to set ignore_default_args to True so i can open tor but it was useless as it gives me an error , i can control brave tor only with  launch_persistent_context but browser appear as bot and i cant log to google , i can do this process with selenium but playwright is much faster, i hope anyone can help me or tell me what is the suitable args to pass so i can use brave tor

**Comment by humanfriend22** [comment]
Try passing `--incognito` as an argument. I haven't tried this myself however.

Source: https://github.com/brave/brave-browser/issues/2105#issuecomment-448337939

**Comment by morkos11** [comment]
> Try passing `--incognito` as an argument. I haven't tried this myself however.
> 
> Source: [brave/brave-browser#2105 (comment)](https://github.com/brave/brave-browser/issues/2105#issuecomment-448337939)

thnx for ur help, but unfortunately it didnt work too

**Comment by SimonGolms** [comment]
Passing `--tor` as an argument could work, see: https://github.com/brave/brave-browser/issues/2105#issuecomment-891961837

**Comment by pavelfeldman** [comment]
This would be outside of the scope for the Playwright test, but I can leave it open so that if someone has a solution they could help.

**Comment by dingyxyx** [comment]
> 这将超出 Playwright 测试的范围，但我可以将其保持打开状态，以便如果有人有解决方案，他们可以提供帮助。
Will future updates consider improving this area?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
