### ISSUE TITLE
[Question] Firefox installed along with playwright install firefox is nightly instead of stable

### ISSUE THREAD

**Issue by hazelcj** [microsoft/playwright#15902]
Hi,

I have a question regarding how to install Firefox stable with command: playwright install firefox.

My environment:
Python: 3.7
Playwright: 1.22
Firefox: Nightly 99.0.1 (64-bit)

According to https://playwright.dev/python/docs/1.22/browsers#firefox, Playwright's Firefox version should match the recent stable build. How do I install a stable version of Firefox and make it working with Playwright?

Thanks!

**Comment by aslushnikov** [comment]
This is the build of 99.0.1 version which is a stable version; Beta would have a `99.0.1b3` version, or something like this.
Don't let the "Nightly" confuse you; this is just to designate that we don't use official mozilla branding for our builds.

**Comment by hazelcj** [comment]
Hi @aslushnikov,
Appreciate your professionalism and explanation.
