### ISSUE TITLE
[Feature] component testing mount result

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#15919]
Can the `update ` and the `unmount` functions be added? This is useful for Vue, React and Svelte:

```typescript
test('update props', ({ mount }) => {
  const component = await mount(Component, {
    props: { name: 'test' }
  });
  await component.update({ props: { name: 'test2' }});
  await expect(component).toHaveText('test2');
})
```

```typescript
test('display a pending changes conformation', ({ mount }) => {
  const component = await mount(Component);
  await component.unmount();
  await expect(component.locator('#conformation-dialog')).toBeVisible();
})
```

## TODO
- [x] update Svelte
- [ ] update Solid
- [x] update React
- [x] update Vue
- [x] update Vue2
- [x] unmount Svelte
- [x] unmount Solid
- [x] unmount React
- [x] unmount Vue
- [x] unmount Vue2

**Comment by pavelfeldman** [comment]
Thanks for another useful use case. I meant to ask a while ago, would you be interested in contributing patches for the components story?

**Comment by pavelfeldman** [comment]
> I'm somewhat limited in time, but I'd love to! How would you like to proceed?

I'm adding unmount in the PR above, you can follow the pattern and implement `setProps`. I'm not sure it will work for all the frameworks, but present fixtures API allows framework-specific signatures, so I'm sure something useful can be done for each.

**Comment by sand4rt** [comment]
Awesome😄 I will have a look at ’setProps’!

Wondering why you would choose for '({ unmount }) => {}' and 'unmount(compoment)' instead of just calling 'component.unmount()'? The last option is easier to write and read right?

**Comment by pavelfeldman** [comment]
> Wondering why you would choose for ({ unmount }) => {} and unmount(compoment) instead of just calling component.unmount()? The last option is easier to write and read.

There is no `Locator.unmount`, so we would need a separate type for it. Let's see how many methods we will need and if we get a bunch, we can transition.

**Comment by sand4rt** [comment]
Have you taken into account that the `setProps` will not automatically be type safe as well if i follow the current implementation of `unmount`?

```typescript
test('work', ({ mount, setProps }) => {
  const component = mount<Props>({ 
    props: { title: 'test' }
  })
  
  setProps<Props>(component, { title: 'test' }) // Must specifically specify the type here
})
```

instead of

```typescript
test('work', ({ mount }) => {
  const component = mount<Props>({ 
    props: { title: 'test' }
  })
  
  component.setProps({ title: 'test' }) // Reuse of the same type defined in mount<Props>()
})
```

In addition, [Testing Library](https://github.com/testing-library/react-testing-library/blob/main/types/index.d.ts#L14), [Vue Test Utils](https://test-utils.vuejs.org/api/#wrapper-methods) and partially [Cypress component testing](https://github.com/cypress-io/cypress/blob/master/npm/react/src/mount.ts#L254) are using the same API. If you decide to use the same API as well, context switching and the migration to Playwright will becomes easier.

We now have feature requests for the following functions and i think a few more will follow. Then why not release a breaking change sooner rather than later?

```typescript
component.unmount()
component.setProps()
component.emitted() // if feature request gets accepted
```

Arguably, but a minor inconvenience is that you will have some line breaks if we have many function props, making the code a little bit harder to read..

```typescript
test('some test description', ({ 
  page,
  mount,
  setProps,
  unmount
}) => {
   // test implementation
} )
```

Maybe i'm nitpicking a bit, but would like to know what you think.

**Comment by pavelfeldman** [comment]
> We now have feature requests for the following functions and i think a few more will follow. Assuming it will be a breaking change, why not release it sooner rather than later?

We have until v1.25 branch point to make this decision. I agree with your points, we can put those calls on the Locator subclass. The unfortunate bit is that they might end up being different for each framework, but I guess we can live with it. Do you want to send a patch that does it?

**Comment by basickarl** [comment]
Hey guys any documentation on this? I've just been winging it until now would be nice to see some solid examples!

**Comment by sand4rt** [comment]
Hey @basickarl help is definitely appreciated :) feel free to add more topics/idea's in the ticket above
