### ISSUE TITLE
[BUG] hooksConfig is required for mount fixture

### ISSUE THREAD

**Issue by AlexanderMykulych** [microsoft/playwright#15913]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: Chromium

**Code Snippet**
I have a component test:

```ts
  const component = await mount(Feature, {
    props: {
      code: testFeatureName,
    },
  })
```

**Describe the bug**

After updating to 1.24.0 I have typecheck error that `hooksConfig` is required in the `mount` fixture. Full text:

```
Property 'hooksConfig' is missing in type '{ props: { code: "enable_test_feature"; text: string; disabledText: string; }; }' but required in type '{ props: { code: "enable_test_feature"; text: string; disabledText: string; }; slots?: { [key: string]: any; }; on?: { [key: string]: Function; }; hooksConfig: any; }'.
```

**Possible resolution**
make `hooksConfig` optional for `mount` fixture

**Comment by pavelfeldman** [comment]
Fixed and merged into 1.24 branch, will be published with 1.24.1. Thanks @sand4rt !
