### ISSUE TITLE
[BUG] text content assertion in web-components

### ISSUE THREAD

**Issue by romanzy-1612** [microsoft/playwright#15927]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Debian GNU/Linux 11 (bullseye)
- Node.js version: v16.16.0
- Browser: All

**Code Snippet**
```typescript
await page.goto('#/remote-component/manual');
// this works
expect(page.locator(`lit-router:has-text("Hello, manual")`)).resolves;
// and this is broken
await expect(page.locator(`lit-router`)).toHaveText('Hello, manual');
```

**Error output**
```
Error: expect(received).toHaveText(expected)

Expected string: "Hello, manual"
Received string: ""
Call log:
  - expect.toHaveText with timeout 5000ms
  - waiting for selector "lit-router"
  -   selector resolved to <lit-router></lit-router>
  -   unexpected value ""
  -   selector resolved to <lit-router></lit-router>
  -   unexpected value ""

  48 |   await page.goto('#/remote-component/manual');
  49 |   expect(page.locator(`lit-router:has-text("Hello, manual")`)).resolves;
> 50 |   await expect(page.locator(`lit-router`)).toHaveText('Hello, manual');
     |                                            ^
```
**Describe the bug**

While testing my web-component routing library, I have noticed an issue with methods such as `toHaveText`, `toContainText`, or any other way of asserting the text content of web-components shadow root. All of the methods return empty string. I have found the workaround with asserting that locator promise resolves, but this makes tests less readable. And there seems to be no way to enter the shadow-dom explicitly, as docs say it should be done automatically.

You can see the test and repo [here](https://github.com/romanzy-1612/lit-router/blob/master/test/main.spec.ts) on line 52.

Thank you

**Comment by pavelfeldman** [comment]
> `expect(page.locator(`lit-router:has-text("Hello, manual")`)).resolves;`

`page.locator` does not return a promise and `expect.resolves` should be followed by something. So this code does not check anything.

```js
await expect(page.locator(`lit-router`)).toHaveText('Hello, manual');
```

This does looks like the right check, but it looks like your lit-router never gets the needed text, so it times out after default 5 seconds.

**Comment by romanzy-1612** [comment]
Thank you for the reply.

Indeed `:has-text` does nothing. Still learning playwright 😁

But I do have the given text inside of the shadow dom. Here is more input on the issue:

If I wrap `Hello, manual` in the div (`<div>Hello, manual</div>`) the output is the same. Playwright says that text is "".

Now if I change my locator query to target a div inside of the webcomponent
```typescript
await expect(page.locator(`lit-router >> div`)).toHaveText('Hello, manual');
```
The test passes.

I think this is a bug

**Comment by pavelfeldman** [comment]
Could you provide the code snippet I could use to reproduce it, or at the very least a screenshot of your dom along with the expectations? Playwright's selectors pierce shadow dom seamlessly, but text is still taken from the light (usual) DOM, as opposed to the composed DOM (that browser uses to render the page after slot composition). That might explain what you are observing, but I'd like to make sure this is the case.

**Comment by romanzy-1612** [comment]
You can find repo with test results included [here](https://github.com/romanzy-1612/playwright-issue-15927)

I have done assertion on the class, so the web-component is located correctly.

Many thanks!
