### ISSUE TITLE
[Question] Is there assertion for check if is element fully visible?

### ISSUE THREAD

**Issue by topolanekmartin** [microsoft/playwright#15924]
Hello,

I've scenario where I have element overlapped with other element. Is there some assertion where I can check if element is fully visible?

![image](https://user-images.githubusercontent.com/44465269/180826849-20549154-9d4a-43ec-a3b4-9a4afa4c696f.png)

Thanks in advance.

**Comment by pavelfeldman** [comment]
No, please upvote https://github.com/microsoft/playwright/issues/8740 + describe your scenario there to make sure we cover it.
