### ISSUE TITLE
[Feature] Component testing Vue/Svelte events/emits

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#15920]
Can the event handling API be changed to that of Vue Test Utils and Testing library? Those seems more user-friendly to me than the current API.

Current API:
 
```typescript
test('event should work', async ({ mount }) => {
  const messages = []
  const component = await mount(Button, {
    props: {
      title: 'Submit'
    },
    on: {
      submit: data => messages.push(data)
    }
  })
  await component.click()
  expect(messages).toEqual(['hello'])
})
```

VTU API:

```typescript
test('event should work', async ({ mount, page }) => {
  const component = await mount(Button, {
    props: {
      title: 'Submit'
    },
  })
  await component.click()
  await expect(component.emitted('submit')).toEqual(['hello'])
})
```

related to: https://github.com/microsoft/playwright/issues/15919

**Comment by pavelfeldman** [comment]
We would still need something like the existing API so that we could handle the event being fired. How is this handled in VTU? Or do they store events in separate collections at all times and don't allow for checking the relative timing of multiple events on different targets?

**Comment by sand4rt** [comment]
Seems like they [record](https://github.com/vuejs/test-utils/blob/main/src/emit.ts#L47) and store all [events in a collection](https://github.com/vuejs/test-utils/blob/main/src/emit.ts#L8) at [any time](https://github.com/vuejs/test-utils/blob/main/src/emit.ts#L36). Not completely sure but I think VTU does not support checking for relative timing of multiple events on different targets. I don't see why you would want to check for this?

For more info see also the API [v1 docs about emitted](https://v1.test-utils.vuejs.org/api/wrapper/#emitted) and the [v2 docs about emitted](https://test-utils.vuejs.org/api/#emitted).

**Comment by pavelfeldman** [comment]
Well, they are events, so you might want to know "when" they fire, not just "that" they fire. But I can see how a collection can save time.

**Comment by sand4rt** [comment]
Maybe i misunderstood your question. You can still verify when the events are triggered because the events are stored in order/sequence. For example:

```typescript
<script>
export default {
  created() {
    this.$emit('greet', 'hello')
    this.$emit('greet', 'goodbye')
  }
}
</script>

import { mount } from '@vue/test-utils'
import Component from './Component.vue'

test('emitted', () => {
  const wrapper = mount(Component)

  // wrapper.emitted() equals to { greet: [ ['hello'], ['goodbye'] ] }

  expect(wrapper.emitted()).toHaveProperty('greet')
  expect(wrapper.emitted().greet).toHaveLength(2)
  expect(wrapper.emitted().greet[0]).toEqual(['hello'])
  expect(wrapper.emitted().greet[1]).toEqual(['goodbye'])
})
```

**Comment by sand4rt** [comment]
Another inconvenience is that you have to type the messages array in the example below otherwise type errors
s are thrown:

```typescript
test('event should work', async ({ mount }) => {
  const messages = [] // NEEDS: const messages: any[] = []
  const component = await mount(<Button title='Submit' v-on:submit={data => {
    messages.push(data) // ERROR: Argument of type 'any' is not assignable to parameter of type 'never'.
  }}></Button>)
  await component.click()
  expect(messages).toEqual(['hello'])
})
```

**Comment by segevfiner** [comment]
In general, vue test-utils has other goodies as well in it's mount command which can be useful in the context of playwright as well. Currently some of them have to be reimplemented via `beforeMount`.

**Comment by segevfiner** [comment]
P.S. Cypress supports passing event handlers as props: https://docs.cypress.io/guides/component-testing/vue/examples#Testing-Event-Handlers, this might be a feature of `@vue/test-utils`, which Playwright requires the separate `on` from as it is not based on it. Also Playwright Test doesn't have builtin spy/stubs to make such testing convenient.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
