### ISSUE TITLE
[Feature] Locate element by focus (reprise)

### ISSUE THREAD

**Issue by naemtl** [microsoft/playwright#15929]
https://github.com/microsoft/playwright/issues/15865#issue-1313964836 this issue was opened a few days ago by someone else, and I'm experiencing something quite similar. So far, I've tried a multitude of ways to try to overcome this limitation. With the solution outlined in the ticket I've linked, I've tried:

```
const focusedElement = await page.evalute(() => document.activeElement);
await focusedElement.click()
```

After running this, I get: `TypeError: focusedButton.click is not a function`

**Comment by pavelfeldman** [comment]
That's because element handles are not primitive types, try this instead:

```js
const focusedElement = await page.evaluteHandle(() => document.activeElement);
await focusedElement.click()
```

**Comment by naemtl** [comment]
Almost there! This does get the focused element signed, but I wanted to know if there was a way to compare the result of `const focusedElement = await page.evaluteHandle(() => document.activeElement);` to a locator. To be more specific, I mean something like:

const focusedElement = await page.evaluteHandle(() => document.activeElement);
if (focusedElement === this.page.locator(`[data-test-id^="InitialButton-"]`)) {
    await focusedElement.click()
}

Thanks for your help so far!

**Comment by pavelfeldman** [comment]
You can try `page.locator(':focus')` then.

**Comment by naemtl** [comment]
Gotcha. 

Forgive me if I'm missing something here. For added context, here's the entire code block I'm trying to get to work. When I try to do `focusedButton === this.fields.signatures`, the condition always returns falsy, though my intention is to be able to assert that they're equal. 

```
      const focusedButton = await this.page.locator(':focus');
      let currentSig;

      if (focusedButton === this.fields.signatures) {
        currentSig = this.fields.signatures;
      } else if (focusedButton === this.fields.captureSignatures) {
        currentSig = this.fields.captureSignatures;
      } else if (focusedButton === this.fields.initialsButton) {
        currentSig = this.fields.initialsButton;
      }

      await expect(
        currentSig,
        `${baseError} Signature was not focused by sticky navigator.`
      ).toBeFocused();

      await currentSig.click();
```

If I go about it like this though: 

```
const currentSig = await this.page.locator(':focus');
await expect(
    currentSig,
    `${baseError} Signature was not focused by sticky navigator.`
).toBeFocused();

await currentSig.click();
if (await this.capSigDialog.container.isVisible()) {
    await this.capSigDialog.drawSignature();
    await this.capSigDialog.doneBtn.click();
}
```

the test runs and passes, but I want to be able to evaluate what kind of locator matches what is focused as a result of `await this.page.locator(':focus');`

**Comment by pavelfeldman** [comment]
There are a couple of problems with your script:

```js
const focusedButton = await this.page.locator(':focus')
```

1. page.locator does not return a promise, it is a value

```js
if (focusedButton === this.fields.signatures)
```

2. This comparison is only true if `this.fields.signatures` in fact stores a pointer to the exact same `focusedButton` locator. That's how JavaScript works.

```js
await expect(
    currentSig,
    `${baseError} Signature was not focused by sticky navigator.`
).toBeFocused();
```

This check does not add value, because you just obtained a focused element, so it is focused. Typically the test would be retrieve element by text / id and would check that it is focused instead. Then you don't need to compare the objects.

**Comment by naemtl** [comment]
Thank you Pavel, you've been a great help! :)
