### ISSUE TITLE
[Handling new pages] getting Context closed error when trying to get to new tab

### ISSUE THREAD

**Issue by mshre001** [microsoft/playwright#15937]
Hello, I am using playwright Version 1.23.4  - I am trying to test a scenario where clicking a button opens a new tab, and I am trying to focus on the newly opened tab and get the title of the page. Following the instructions found at : https://playwright.dev/docs/pages. 

Below is a snippet of  my spec - 
test.describe("Test suite ", async () => {
  let page;
  let context;
  test.beforeAll(async ({ browser }) => {
    context = await browser.newContext();
    //page = await browser.newPage();
    page = await context.newPage();
    await page.goto("https://mywebsite.com");
});

  test("Test case 1", async () => {
    const [newPage] = await Promise.all([
      await context.waitForEvent("page"),  // this is where I get the context closed error
      await page.locator('#submit').click();
    ]);
    await newPage.waitForLoadState();
    await newPage.bringToFront();
    console.log(await newPage.title());
});
});

Below is the error I am getting:
    browserContext.waitForEvent: Context closed

Would you be able to suggest what I am doing wrong here? Thanks and appreciate your help!

**Comment by mshre001** [comment]
Thanks Pavel, 
yes I am running in serial mode, the beforeAll has a login step for our application, which requires otp code and wanted to avoid doing that for each test. Is that the reason for me getting this error?

**Comment by pavelfeldman** [comment]
1. I don't see where you are using the serial mode.
2. Your Promise.all usage is wrong, they have extra awaits, should be:

```js
const [newPage] = await Promise.all([
  context.waitForEvent("page"), // this is where I get the context closed error
  page.locator('#submit').click();
]);
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by mshre001** [comment]
> ```js
> const [newPage] = await Promise.all([
>   context.waitForEvent("page"),
>   page.locator('#submit').click();
> ]);
> ```

Thank you so much for your help,  this seems to have worked! I do need to get a better understanding of Promise  in pw.
