### ISSUE TITLE
[BUG] `page.locator.toContainText` returns single string in an array for nested DOM nodes

### ISSUE THREAD

**Issue by chrisboakes** [microsoft/playwright#15949]
**Context:**
- Playwright Version: [1.24.0]
- Operating System: [Mac]
- Node.js version: [16.16.0]
- Browser: [Chromium]

**Code Snippet**

```javascript
const {playwright, expect} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  await page.goto('https://cdpn.io/pen/debug/gOexNqZ?authentication_hash=RBrOJbmagbQM', { waitUntil: 'networkidle' });

  const searchList = page.locator('[data-test="items"]');

  const expectedOutput = [
    'Foo 1',
    'Bar 1',
    'Foo 2',
    'Bar 2'
  ];

  // This will fail
  // Actual output is ['Foo 1Bar 1Foo 2Bar 2']
  expect(searchList).toContainText(expectedOutput);
})();
```

**Describe the bug**

It seems that running the `toContainText` assertion on a `locator` with nested DOM nodes returns a single string in an array (instead of an array of values). E.g.

```html
<ul data-test="items">
  <li>
    <p>Foo 1</p>
    <a href="#">Bar 1</a>
  </li>
  <li>
    <p>Foo 2</p>
    <a href="#">Bar 2</a>
  </li>
</ul>
```

Returns `['Foo 1Bar 1Foo 2Bar 2']` whereas it should be `['Foo 1', 'Bar 1', 'Foo 2', 'Bar 2']`

**Comment by pavelfeldman** [comment]
toHaveText / toContainText would expect as many strings as there are elements in the `locator.count()`. In your case, this is one element, so you get one string. You can change your locator to `page.locator('[data-test="items"] > *')` if you want immediate children of your items list.

**Comment by chrisboakes** [comment]
@pavelfeldman thanks. I found to match all children everything in the example above, I needed to run `page.locator('[data-test="items"] > * > *')`. Closing now

**Comment by thebencourt** [comment]
@pavelfeldman this used to work in v1.23.4. Is it an intentional change or a regression?
