### ISSUE TITLE
[BUG]: chaining multiple API calls with stored variables and re-used are not applied to the last API calls

### ISSUE THREAD

**Issue by eutudb23** [microsoft/playwright#15946]
**Context:**
- Playwright Version: [1.23.4]
- Operating System: [Mac]
- Node.js version: [16.16.0]
- Browser: [Chromium, Firefox]
- Extra: [nothing additional]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

This is working by having a token hardcoded:
```
test('Test Post Artist', async ({ request }) => {
const idToken = "some token for the request";
        const postArtist = await request.post(`apiURL`, {
            headers: {
                Authorization: "Bearer " + idTokenStringify,
                ContentType: "application/json",
                Connection: "keep-alive"
            },
            data: {
                "md": {
                    "displayName": "querty"
                }
            }
        });
        const postArtistResponse = await postArtist.json();
        console.log("response" + postArtistResponse);
        expect(postArtist.ok()).toBeTruthy();
});
```
![image](https://user-images.githubusercontent.com/11492145/180976328-d8ef31dd-f649-4731-bd3f-316bfc6a48b7.png)

This does not work by extracting idToken from another call, store as a variable and re-use it in a next call
This is not the 1st instance/test I encountered it.
```
test('Test Post Artist', async ({ request }) => {
const creatorPayloadQuerty = { "bla bla" };
const postSignUp = await request.post(`apiURL?key=${appKey}`, {
            data: JSON.stringify(creatorPayloadQuerty)
        });
expect(postSignUp.status()).toEqual(200);
expect(getArtistNotFound.status()).toEqual(404);
        const retrieveToken = await request.post(`apiURL?key=${appKey}`, {
            data: JSON.stringify(creatorPayloadQuerty)
        });
        expect(retrieveToken.ok()).toBeTruthy()
        // we save the response json then parse and store the value and re-use
        const tokenResponse = await retrieveToken.json();
        const idTokenStringify = tokenResponse.idToken;
const postArtist = await request.post(`apiURL`, {
            headers: {
                Authorization: "Bearer " + idTokenStringify,
                ContentType: "application/json",
                Connection: "keep-alive"
            },
            data: {
                "md": {
                    "displayName": "querty"
                }
            }
        });
        const postArtistResponse = await postArtist.json();
        console.log("response" + postArtistResponse);
        expect(postArtist.ok()).toBeTruthy();
})
```
![image](https://user-images.githubusercontent.com/11492145/180976288-e0488e20-3a22-432d-abca-4e417e00e0a1.png)

**When working with sequential calls, storing responses as variables to be re-used on later API calls is not working. By having the values hardcoded seem to work just fine **

Add any other details about the problem here.

**Comment by eutudb23** [comment]
It can be closed as I found a solution by using timeout for specific/between calls as it takes more than the default allotted time.
This seems more pronounced when querying response and re-use the var on the next call, seems like it does not have enough time to parse and re-use.

**Comment by pavelfeldman** [comment]
I'll close as per above, but it sounds strange - there are no such timeouts on the client side, so it might be the server issue that takes time to propagate the credentials. In either case, if you find more issues, please feel free to open a new bug and link to this one.
