### ISSUE TITLE
[Question] How to override fixture's scope?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15948]
Hi there!

We want to override `page` fixture to run all our 1000+ tests in just one browser tab, because each navigation takes 3-5 seconds, and SPA-navigation (in the storybook) just 5 ms. Otherwise we have x20 test running time, because the average test takes just ~50ms (so, you got total test time 5ms + 50ms in one case and 3s + 50ms in another).

I tried to follow this guide https://playwright.dev/docs/test-fixtures#overriding-fixtures but got an error:

```ts
import { test as base } from '@playwright/test'
import type { Page } from '@playwright/test'

export const test = base.extend<{}, { page: Page }>({
  page: [async ({ browser }, use) => {
    const page = await browser.newPage();
    await use(page)
  }, { scope: 'worker' }], // Type 'string' is not assignable to type 'never'.
})
```

The runtime error is

```
Error: Fixture "page" has already been registered as a { scope: 'test' } fixture.
  "page" defined at ***/fixtures.ts:7:26
  "page" defined at node_modules/@playwright/test/lib/index.js:76:24
```

Is that possible to override `page` fixture and change its scope?

**Comment by pavelfeldman** [comment]
The easiest would be to use serial mode for that: https://playwright.dev/docs/next/test-retries#reuse-single-page-between-tests. Note though that since you are using the same context for multiple tests, it'll be slowly leaking. So using it for 1000 tests would be pushing it. Maybe use one per file.

**Comment by pavelfeldman** [comment]
```js
export const test = base.extend<{}, { page: Page }>({
  _sharedContext: [async ({ browser }, use) => {
    await use(await browser.newContext())
  }, { scope: 'worker' }],

  context: async ({ _sharedContext }, use) => {
    await use(_sharedContext);
  },

  page: async ({ context, baseURL }, use) => {
    let [page] = context.pages();
    if (!page) {
      page = await context.newPage();
      await page.goto(baseURL!);
    }
    await use(page);
  }
});
```

**Comment by Diokuz** [comment]
Just tweaked types a bit

```ts
base.extend<{ page: Page }, { _sharedContext: BrowserContext  }>
```

and it works!

Thanks!
