### ISSUE TITLE
[Question] Strange Action when I change the screen using Codegen

### ISSUE THREAD

**Issue by fortegaseguel** [microsoft/playwright#15942]
Hi everybody!

This is some weird question, but, when I'm using Playwright with Firefox and I try to navigate to login in a page, in the laptop screen all works fine, but if I change the action to my secondary screen, the browser send me an server's error and the process fails.

What could it be?? I'm think is something about browser fingerprint or some like this.

If you know how can I adjust it, I'm sincerelly thankful.

Best regards.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
