### ISSUE TITLE
[Question] How I can Activate/Deactivate Enhanced Tracking Protection for Firefox

### ISSUE THREAD

**Issue by fortegaseguel** [microsoft/playwright#15941]
Hi, When I use Playwright some sites block the navigation, especially in login forms.
I discovered that if I deactivate the Enhanced Tracking, when I'm using Firefox, I can access without problems, but I have to do this manually.

How can I add this feature in the context of my program to do this automatically?  I'm using python for now.

Thanks to all!!

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by aslushnikov** [comment]
There's a variety of preferences that we can try toggling, but we'd need a repro to recommend at least something!

**Comment by jake-b-story** [comment]
It sounds like there needs to be a way to launch the  Firefox browser with the setting "Enhanced Tracking Protection" in  `Preferences > Provacy & Security > Enhanced Tracking Protection` automatically set to `Custom` with all items (cookies, tracking content, cryptominers, and finderprinters) unchecked. This would disable "Enhanced Tracking Protection feature'.

I am seeking something similar where I just want to click a dialog box asking me to "Allow" or "Block"  a 3rd party to cookie access. Unfortunately,  having the `page` listen for a `dialog` event, does not automatically accept this window (see image below). 

`Code snippet attempted to auto accept dialog box`
```typescript
page.on('dialog', async dialog => {
      await dialog.accept();
    });
```
`Firefox dialog box trying to auto accept`
![Screen Shot 2022-08-15 at 8 50 10 PM](https://user-images.githubusercontent.com/100636797/184782130-7a24649c-98e4-4300-b6fe-6aca860c0d16.png)

**Comment by PacoSoftwerft** [comment]
This is similar to https://github.com/microsoft/playwright/issues/15941#issuecomment-1216056221
but even less restrictive.
Works like a charm on my project.

Good luck and if it solves your problem, please consider closing this issue.

```
    {
      name: 'firefox',
      use: {
        launchOptions: {
          firefoxUserPrefs: {
            'browser.contentblocking.category': 'custom',
            'network.cookie.cookieBehavior': 0,
          },
        },
        ...devices['Desktop Firefox'],
      },
    },
```

it is the same as the following settings in `about:preferences#privacy`

See screenshot:

![image](https://user-images.githubusercontent.com/81621559/186660277-3e3f5300-597e-4a23-b994-a1587752f896.png)

**Comment by aslushnikov** [comment]
I'll close this for now since there's been quite a few workarounds already.

Please feel free to file new issues if you think Playwright team can be helpful!
