### ISSUE TITLE
[Question] Can't download browsers

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#15957]
I am using the following for my shell script in TeamCity to run my tests:
```
npm ci
npx playwright install --with-deps
npx playwright test tests/smoketestshould --project=firefox
```

However, when I try to run them, I get the following error: Password: su: Authentication failure

I assume this is an issue with how we have the Docker container set up on the linux server, but I am not sure how to fix it. Any help would be appreciated!

**Comment by pavelfeldman** [comment]
`npx playwright install --with-deps` installs system dependencies and that certainly requires super user privileges. It looks like your Docker user does not have them. If this is your own image, you should run `npx playwright install --with-deps` when building the container rather than at runtime. That would also make it run much faster because all the dependencies will be baked into your container.

**Comment by eatonjl** [comment]
@pavelfeldman I will give that a try. Thank you! Do I need to install the dependancies if I am using the Playwright Docker image? The documentation says, "Use our Docker image in Linux agents or install your dependencies using the CLI."

**Comment by pavelfeldman** [comment]
You don't need deps if you are using the official Docker image, everything is installed!

**Comment by eatonjl** [comment]
@pavelfeldman Since I am using the Playwright Docker image, I shined my shell script to just this:
`npx playwright test tests/smoketestshould --project=firefox`
That works fine with it is "--project=webkit" or "--project=chromium". But when run with "--project=firefox" the build log says it is running 88 tests on 1 worker but then it hangs like it is in an eternal loop or something.

**Comment by pavelfeldman** [comment]
Ok, so Firefox tests hang when running in Docker? Is that v1.24?

**Comment by pavelfeldman** [comment]
Firefox tests are passing on our internal Docker dashboard, please provide an example of the test that we should try.

**Comment by eatonjl** [comment]
Yes, it hangs when running it in Playwright Docker 1.24.  I will try and get you something tomorrow.

**Comment by eatonjl** [comment]
OK, I will try to add some code here and what I am doing in TeamCity to recreate this. Let me know if you need something more or something different. The global setup and a lot of the config entries do not matter for the example test, but I am including them in here since they are in the code and global setup is being done before the example test runs. 
I have this in TeamCity and I am using the following shell script: npx playwright test tests/example --project=firefox
This is using the mcr.microsoft.com/playwright:v1.24.0-focal docker image. 
I tried running a test and stopped it 16 hours after saying "Running 88 tests using 1 worker" without any progress. 

```
// global-setup.ts
import { chromium, FullConfig } from '@playwright/test';
import { GatewayLogin } from './tests/PageObjectModels/Gateway/login-page';

async function globalSetup(config: FullConfig) {
	const { baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;
	const browser = await chromium.launch();
	const context = await browser.newContext({
		locale: 'en-us',
		ignoreHTTPSErrors,
	});
	const page = await context.newPage();
	try {
		await context.tracing.start({ screenshots: true, snapshots: true });
		const gatewayLogin = new GatewayLogin(page);
		await page.goto(baseURL!);
		await gatewayLogin.username.fill(process.env.MARTIN1_USERNAME!);
		await gatewayLogin.password.fill(process.env.MARTIN1_PASSWORD!);
		await Promise.all([
			page.waitForNavigation({url: baseURL! }),
			page.locator('text=Sign In').click(),
		]);
		// Save signed-in state to 'storageState.json'.
		await page.context().storageState({ path: storageState as string });
		await context.tracing.stop({
			path: './test-results/setup-trace.zip',
		});
		await browser.close();
	} catch (error) {
		await context.tracing.stop({
			path: './test-results/failed-setup-trace.zip',
		});
		await page.close();
		throw error;
	}
}

export default globalSetup;
```

```
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices, expect } from '@playwright/test';
import matchers from 'expect-axe-playwright';
import dotenv from 'dotenv';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
dotenv.config();

/* expect-axe-playwright settings*/
expect.extend(matchers);

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
	testDir: './tests',
	/* Maximum time one test can run for. */
	timeout: 40 * 1000,
	expect: {
		/**
		 * Maximum time expect() should wait for the condition to be met.
		 * For example in `await expect(locator).toHaveText();`
		 */
		timeout: 10000,
	},
	// Tell all tests to load signed-in state from 'storageState.json'.
	globalSetup: require.resolve('./global-setup'),
	/* Fail the build on CI if you accidentally left test.only in the source code. */
	forbidOnly: !!process.env.CI,
	/* Stop the test run after reaching this number of failed tests and skip any tests that were not executed yet. This is useful to avoid wasting resources on broken test suites. */
	maxFailures: process.env.CI ? 10 : undefined,
	/* Retry on CI only */
	retries: process.env.CI ? 2 : 0,
	/* Opt out of parallel tests on CI. */
	workers: 1,
	/* Reporter to use. See https://playwright.dev/docs/test-reporters */
	//reporter: process.env.CI ? 'dot' : 'list',
	reporter: process.env.CI
		? [
				['list'],
				[
					'playwright-teamcity-reporter',
					{ testMetadataArtifacts: 'test-results', logConfig: false },
				],
		  ]
		: 'list',
	// reporter: [
	// 	['list'],
	// 	['playwright-teamcity-reporter', { testMetadataArtifacts: 'test-results' }],
	// ],
	/* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
	use: {
		/* expect-axe-playwright settings*/
		axeOptions: {
			runOnly: {
				type: 'tag',
				values: ['wcag2a', 'wcag2aa'],
			},
		},
		ignoreHTTPSErrors: true,
		storageState: 'storageState.json',
		/* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
		actionTimeout: 0,
		/* Base URL to use in actions like `await page.goto('/')`. */
		baseURL: process.env.BASE_URL,

		/* Collect trace when retrying the failed test. See v */
		trace: 'retain-on-failure',
	},

	/* Configure projects for major browsers */
	projects: [
		{
			name: 'chromium',
			testIgnore: Array(
				/mobileviewshould.spec.ts/,
				/digitalintakeshould.spec.ts/
			),
			use: {
				...devices['Desktop Chrome'],
			},
		},

		{
			name: 'firefox',
			testIgnore: Array(
				/mobileviewshould.spec.ts/,
				/digitalintakeshould.spec.ts/
			),
			use: {
				...devices['Desktop Firefox'],
			},
		},

		{
			name: 'webkit',
			testIgnore: Array(
				/mobileviewshould.spec.ts/,
				/digitalintakeshould.spec.ts/
			),
			use: {
				...devices['Desktop Safari'],
			},
		},

		/* Test against mobile viewports. */
		{
			name: 'Mobile Chrome',
			testIgnore: Array(
				/smoketestshould.spec.ts/,
				/epimshould.spec.ts/,
				/draftandcollaborationshould.spec.ts/,
				/reviewandapprovalshould.spec.ts/
			),
			use: {
				...devices['Pixel 5'],
			},
		},
		{
			name: 'iPhone 13 Mobile Safari',
			testIgnore: Array(
				/smoketestshould.spec.ts/,
				/epimshould.spec.ts/,
				/draftandcollaborationshould.spec.ts/,
				/reviewandapprovalshould.spec.ts/
			),
			use: {
				...devices['iPhone 13'],
			},
		},
		{
			name: 'iPhone 13 Pro Max Mobile Safari',
			testIgnore: Array(
				/smoketestshould.spec.ts/,
				/epimshould.spec.ts/,
				/draftandcollaborationshould.spec.ts/,
				/reviewandapprovalshould.spec.ts/
			),
			use: {
				...devices['iPhone 13 Pro Max'],
			},
		},
		{
			name: 'iPhone 12 Mobile Safari',
			testIgnore: Array(
				/smoketestshould.spec.ts/,
				/epimshould.spec.ts/,
				/draftandcollaborationshould.spec.ts/,
				/reviewandapprovalshould.spec.ts/
			),
			use: {
				...devices['iPhone 12'],
			},
		},
		{
			name: 'Samsung Galaxy S22 Ultra 5G Mobile Safari',
			testIgnore: Array(
				/smoketestshould.spec.ts/,
				/epimshould.spec.ts/,
				/draftandcollaborationshould.spec.ts/,
				/reviewandapprovalshould.spec.ts/
			),
			use: {
				...devices['iPhone 12'],
			},
		},

		/* Test against branded browsers. */
		{
			name: 'Microsoft Edge',
			use: {
				channel: 'msedge',
			},
		},
		{
			name: 'Google Chrome',
			use: {
				channel: 'chrome',
			},
		},
	],

	/* Folder for test artifacts such as screenshots, videos, traces, etc. */
	// outputDir: 'test-results/',

	/* Run your local dev server before starting the tests */
	// webServer: {
	//   command: 'npm run start',
	//   port: 3000,
	// },
};

export default config;
```

```
//example.spec.ts
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // create a locator
  const getStarted = page.locator('text=Get Started');

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro');

  // Click the get started link.
  await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Comment by pavelfeldman** [comment]
Unfortunately, this is not something we can reproduces, it is full of code we don't have access to. Does it work when you run it locally? So is the problem localized to the Docker+Firefox? Are you running it on TeamCity? Our Docker tests run on GHA.

**Comment by eatonjl** [comment]
I can set it up so you have access to everything. The only thing I can't set up for you is TeamCity. It works locally but I am not using the Playwright Docker image when doing that. 
What do you need from me so you can investigate further? 
And have you been able to try running any test in Firefox with the mcr.microsoft.com/playwright:v1.24.0-focal docker image successfully?

**Comment by pavelfeldman** [comment]
> And have you been able to try running any test in Firefox with the mcr.microsoft.com/playwright:v1.24.0-focal docker image successfully?

Yes, we have internal bots that run all the tests on Docker, including Firefox.

> What do you need from me so you can investigate further?

Given the above, our best hope is your bisecting the problem and helping us localize the use case.

**Comment by eatonjl** [comment]
@pavelfeldman I am trying to run the tests locally using the Docker image so I can get TeamCity out of the mix and confirm whether or not it is part of the problem. But I am not sure how to get Playwright to use the Docker image instead of the locally installed browsers. How do I do that?

**Comment by eatonjl** [comment]
Also, is there a way to downgrade the Playwright version so I can see if this is unique to this build?

**Comment by pavelfeldman** [comment]
> How do I do that?

Same way you do it on TeamCity, but locally? Everything needs to be inside the docker.

**Comment by eatonjl** [comment]
Hmm, I will need to figure out how to set that up. In the meantime I am rolling back the version I had when it was working and confirm whether or not I still have the issue. I will let you know what I find.

**Comment by eatonjl** [comment]
So, I was able to get it to work by adding "chown root ." above "npx playwright test tests/smoketestshould --project=firefox" in the shell script. I am not sure why Firefox needs that while Chromium and Safari don't.

**Comment by pavelfeldman** [comment]
It might be due to how Firefox stores its files in the temporary partition, and depending on the docker setup it might work or not. I'll close this ticket since it started with unrelated issue, but please feel free to file a new one with the narrowed-down problem if you think we should act on it.

**Comment by eatonjl** [comment]
Will do. Thanks!

**Comment by sesameabowhill** [comment]
> `npx playwright install --with-deps` installs system dependencies and that certainly requires super user privileges.

May I ask what su is being used for by the installer? The user installs 3rd-party software in the context of their own permissions. If I run an installer as root, then su should be unnecessary. Is it doing this to install the browser libraries?

I'm trying to install playwright locally in /tmp in custom Debian container that runs in AWS Lambda.
The OS is completely locked-down in Lambda, and the only directory you are allowed to write-to is /tmp. I have all the browser libraries pre-loaded in the container during Docker build-time, but the su call is preventing me from seeing what's going on with the playwright installation.

Do you have any recommendations to disable this call, outside of using Microsoft's base image?

========== Stage: Execution ==========
=> TASK: RunTests
npm:
11.6.2
npx:
11.6.2
node:
v24.11.1
Password: su: Authentication failure 
Error: Command failed: npx playwright install --with-deps
at genericNodeError (node:internal/errors:985:15)
at wrappedFn (node:internal/errors:539:14)
at checkExecSyncError (node:child_process:925:11)
at execSync (node:child_process:997:15)
at executeCommands (/tmp/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:8272:39)
at Generator.run (/tmp/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:8356:5)
at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
at async _Command.<anonymous> (/tmp/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:8661:3)
at async _Command.parseAsync (/tmp/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:2148:9) {
status: 1,
signal: null,
output: [ null, null, null ],
pid: 111,
stdout: null,
stderr: null
}
npm error code 1
npm error path /tmp/qaa-analytics-cucumber-js
npm error command failed
npm error command sh -c "create-playwright" --quiet --install-deps
npm error A complete log of this run can be found in: /tmp/.npm/_logs/2025-11-13T16_18_19_166Z-debug-0.log
