### ISSUE TITLE
[BUG] No source available when running plawright in debug mode

### ISSUE THREAD

**Issue by MickeyTrausch** [microsoft/playwright#15952]
**Context:**
- Playwright Version: 1.21.0
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: All

**Describe the bug**

When launching playwright in debug mode, the playwright inspector diplay //No source available, but when clicking on step over in the chronium windows I can see each step of the test.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by MickeyTrausch** [comment]
My file sample.e2e.spec.js

import { test, expect } from '@playwright/test';
test('test', async ({ page }) => {
  // Go to https://www.wikipedia.org/
  await page.goto('https://www.wikipedia.org/');
  // Go to https://en.wikipedia.org/wiki/Elon_musk
  await page.goto('https://en.wikipedia.org/wiki/Elon_musk');
  // Go to https://en.wikipedia.org/wiki/Elon_Musk
  await page.goto('https://en.wikipedia.org/wiki/Elon_Musk');
});

When I launch npx playwright test ./sample.e2e.spec.sj it open a chronium browser and a playwright inspector windows, but in the inspector windows I see // No source available

Sorry, I don't knwo what you need more, but I cannot copy a printscreen of my problem.
I have updated my playwright version in my project to 1.24.2

**Comment by ButcherLTh** [comment]
I just ran into a similar problem. 
Did you find the solution?
