### ISSUE TITLE
[Question] Why does last test result gets printed after  afterAll()

### ISSUE THREAD

**Issue by raje312** [microsoft/playwright#15962]
I have simple test structure and noticed that all logging as part of afterAll() printed before the last test result 
import { test } from '@playwright/test';

test.describe.serial('root describe', () => {

  test.beforeAll(async () => {
    console.log('enter before all');
  });

  test.afterAll(async () => {
    console.log('enter after all');
  });

  test('test1', async () => {
    console.log('enter test1');
  });

  test('test2', async () => {
    console.log('enter test2');
  });

  test('test3', async () => {
    console.log('enter test3');
  });
});

![image](https://user-images.githubusercontent.com/108887224/181066739-adbed4c4-d002-43ac-9f4f-ff67999e7b69.png)

**Comment by dgozman** [comment]
@raje312 That's because we print the result after corresponding hooks including `afterAll` run. If that's problematic, please tell us in more details.

**Comment by raje312** [comment]
printing result of entire test is fine but in this case playwright is printing the result of test3 after afterAll() while that of test1, test2 is being printed before afterAll()

**Comment by raje312** [comment]
in our test, the result of test3 is printed after afterAll() cleanup logging and appears after test3 is run after cleanup

**Comment by dgozman** [comment]
> in our test, the result of test3 is printed after afterAll() cleanup logging and appears to user as if test3 is run after cleanup

It is not run after cleanup, it is finished after cleanup. That's to ensure that cleanup logging/errors/etc. gets to the report of some test and is not lost forever.

I hope this answers the question. Let me know if it does not.
