### ISSUE TITLE
[BUG] Page reopen workaround for WebKit locale and Chromium isMobile bugs is applied even when not needed

### ISSUE THREAD

**Issue by eranr-talon** [microsoft/playwright#15965]
**Context:**
- Playwright Version: 1.25.0
- Operating System: macOS 12.4
- Node.js version: 18.6.0
- Browser: Chromium-based browser

**Describe the bug**

The workaround to isMobile and locale that was introduced in https://github.com/microsoft/playwright/pull/2177 is applied to all instances, regardless of the browser type and options.

This uncommon behavior, re-opening the page, that is caused by the workaround, is causing some of our Chromium-based browser features to misbehave and breaks our end-to-end tests, that are based on Playwright, even though we do not fall into the criteria where the workaround should be fixed.

I uncommonly started off with a pull request (https://github.com/microsoft/playwright/pull/15904), suggesting a change that will not change the expected behavior for any Playwright user, but will fix the issue on our end. I opened this issue to continue the discussion as per @dgozman's request.

**Comment by eranr-talon** [comment]
> it seems like you are using locale emulation in chromium, because that's the only case this PR affects
@dgozman in https://github.com/microsoft/playwright/pull/15904#issuecomment-1195778965 

So I checked and we weren't setting `locale` explicitly anywhere. I figured that it must be set implicitly by Playwright somewhere and after some time of debugging I found that it is indeed [getting a default value](https://github.dev/microsoft/playwright/blob/0b72f7ec99dfd42ca91dee17d822a8d9a4ef711a/packages/playwright-test/src/index.ts#L216), and that default value [is set to `en-US`](https://github.dev/microsoft/playwright/blob/0b72f7ec99dfd42ca91dee17d822a8d9a4ef711a/packages/playwright-test/src/index.ts#L152)

**Comment by dgozman** [comment]
> So I checked and we weren't setting `locale` explicitly anywhere. I figured that it must be set implicitly by Playwright somewhere and after some time of debugging I found that it is indeed [getting a default value](https://github.com/microsoft/playwright/blob/0b72f7ec99dfd42ca91dee17d822a8d9a4ef711a/packages/playwright-test/src/index.ts#L216), and [that default value is set to `contextOptions.locale ?? 'en-US'` which resolves to `en-US`](https://github.com/microsoft/playwright/blob/0b72f7ec99dfd42ca91dee17d822a8d9a4ef711a/packages/playwright-test/src/index.ts#L152) as we weren't setting it.

You are right! This is an unfortunate situation. I think your proposed fix would be the best right now.
