### ISSUE TITLE
[Question]Test folders

### ISSUE THREAD

**Issue by Aenz99** [microsoft/playwright#15969]
Hello guys, I'm new to PW, a simple question here:
Could the tests files be in another folder rather than Playwright/tests ?

for example: Playwright/Model1/Tests

I tried that but it isn't recognizing my tests, it says 0 tests found.

Thanks in advance.

**Comment by pavelfeldman** [comment]
Sure, you can point to any folder. You probably specified 'tests' folder in your `playwright.config.ts`.

**Comment by srikanthmasanala** [comment]
Configure as below in playwright.config.ts

const config: PlaywrightTestConfig = {
  **testDir: "./Tests",**

**Comment by Aenz99** [comment]
> Configure as below in playwright.config.ts
> 
> const config: PlaywrightTestConfig = { **testDir: "./Tests",**

That means that tests will only run in "./Tests" folder?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/next/api/class-testproject#test-project-test-dir

**Comment by srikanthmasanala** [comment]
> > Configure as below in playwright.config.ts
> > const config: PlaywrightTestConfig = { **testDir: "./Tests",**
> 
> That means that tests will only run in "./Tests" folder?

Yes, all test files placed in the Tests folder will run.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
