### ISSUE TITLE
[Question] How to use the project browser in global setup

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#15971]
I am using the global setup feature in Playwright. I am going off of the [Playwright documentation](https://playwright.dev/docs/test-advanced) that has it using Chromium. I am wondering if there is a good way to make it, instead, use the browser the project is using (I.E. if I am running tests in webkit, use webkit for global setup). Here is my global setup file:
```
// global-setup.ts
import { chromium, FullConfig } from '@playwright/test';
import { GatewayLogin } from './tests/PageObjectModels/Gateway/login-page';

async function globalSetup(config: FullConfig) {
	const { baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;
	const browser = await chromium.launch();
	const context = await browser.newContext({
		locale: 'en-us',
		ignoreHTTPSErrors,
	});
	const page = await context.newPage();
	try {
		await context.tracing.start({ screenshots: true, snapshots: true });
		const gatewayLogin = new GatewayLogin(page);
		await page.goto(baseURL!);
		await gatewayLogin.username.fill(process.env.MARTIN1_USERNAME!);
		await gatewayLogin.password.fill(process.env.MARTIN1_PASSWORD!);
		await Promise.all([
			page.waitForNavigation({url: baseURL! }),
			page.locator('text=Sign In').click(),
		]);
		// Save signed-in state to 'storageState.json'.
		await page.context().storageState({ path: storageState as string });
		await context.tracing.stop({
			path: './test-results/setup-trace.zip',
		});
		await browser.close();
	} catch (error) {
		await context.tracing.stop({
			path: './test-results/failed-setup-trace.zip',
		});
		await page.close();
		throw error;
	}
}

export default globalSetup;
```

**Comment by pavelfeldman** [comment]
You can add `browserName` into the line `const { baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;` and do `await playwright[browserName].launch()`

**Comment by eatonjl** [comment]
I now have it this way: 
```
const { browserName, baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;
const browser = await playwright[browserName].launch();
```
But it is saying that it "Cannot find name 'playwright'."

**Comment by pavelfeldman** [comment]
```js
import playwright, { chromium, FullConfig } from '@playwright/test';
```

**Comment by eatonjl** [comment]
OK, it is no longer throwing the same fit but, when running it, I get an undefined error. I think it is because I do not have "browserName: 'firefox'" in my config. I am using project. Instead, I have lines like this:
```
{
	name: 'firefox',
	testIgnore: Array(
		/mobileviewshould.spec.ts/,
		/digitalintakeshould.spec.ts/
	),
	use: {
		...devices['Desktop Firefox'],
	},
},
```

**Comment by pavelfeldman** [comment]
The simplest would be to add browserName: 'firefox', etc into the use

**Comment by eatonjl** [comment]
I could do that, but wouldn’t that cause it to only use that one? If I have browserName be “Firefox” but I use the WebKit project then I once again will be using two different browsers. Maybe I am misunderstanding what you are saying.

**Comment by pavelfeldman** [comment]
I assume that you are running your tests using --project= in the command line. Then you would assign browserName in all the projects respectively and each time you run the tests proper browser is used.

**Comment by eatonjl** [comment]
I tried adding it to the project: 
```
	projects: [
		{
			name: 'chromium',
			testIgnore: Array(
				/mobileviewshould.spec.ts/,
				/digitalintakeshould.spec.ts/
			),
			use: {
        browserName: 'chromium',
				...devices['Desktop Chrome'],
			},
		},
```
But I still get an error at run stating that launch has an undefined value. At this point I would say you can close this and I will not worry about it. I was thinking there would be a lot less customizing to get the global setup to use the project browser. Thanks!

**Comment by scottfwalter** [comment]
> You can add `browserName` into the line `const { baseURL, storageState, ignoreHTTPSErrors } = config.projects[0].use;` and do `await playwright[browserName].launch()`
> 
> You probably want to close the browser on exception too...

playwright.firefox, playwright.chromium, playwright.edge doesn't seem to exist in 1.24.2 unless I am missing something.

**Comment by scottwalter-nice** [comment]
Oooh it looks like you can get access to the browsers when you import playwright from 'playwright-core' if using @playwright/test.

Is it advisable to import directly from playwright-core?
