### ISSUE TITLE
Showing sameSite error in code but it works properly

### ISSUE THREAD

**Issue by LadaVarga** [microsoft/playwright#15972]
Hello,

I have problem with setting "sameSite" attribute in cookie. It works but VScode shows error when I tried to set it up. If I use SameSite it doesn't show error but it doesn't work. Am I doing something wrong? I use chromedriver 102 and I updated Playwright to latest version.

```
export async function setCookieVals() {

  const cookies = [
    { name: "bbranch", value: "x", domain: "x", path: "/" },
    { name: "refreshCache", value: "true", domain: "x", path: "/", secure: true, httpOnly: true, sameSite: "None" }
]

  return cookies;
}
```
```
const cookieVals = await setCookieVals();
  await context.addCookies(cookieVals);
```
<img width="881" alt="2022-07-26 21_43_36-bid-board-integrated spec ts - esticom-frontend - Visual Studio Code" src="https://user-images.githubusercontent.com/22859476/181099965-ba13c594-5da3-4d27-afbb-be85736bc972.png">
<img width="688" alt="2022-07-26 21_43_09-bid-board-integrated spec ts - esticom-frontend - Visual Studio Code" src="https://user-images.githubusercontent.com/22859476/181099972-2c925f79-e935-43ce-a7bc-874c2b494a61.png">

**Comment by pavelfeldman** [comment]
It is a type checker issue, you can declare it as any to disable type checking:

```js
export function cookieVals(): any {
  return [
    { name: "bbranch", value: "x", domain: "x", path: "/" },
    { name: "refreshCache", value: "true", domain: "x", path: "/", secure: true, httpOnly: true, sameSite: "None" }
  ];
}
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
