### ISSUE TITLE
[BUG] page.request.fetch doesn't use proxy settings

### ISSUE THREAD

**Issue by monkekode** [microsoft/playwright#15985]
**Context:**
## System:
 - OS: macOS 12.4
 - Memory: 19.65 MB / 16.00 GB
## Binaries:
 - Node: 16.13.1 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.1.2 - /usr/local/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/local/bin/bash

**Code Snippet**

```javascript
import {chromium} from "playwright";

const b = await chromium.launch({
    headless: false,
    args: [
        '--proxy-server=socks5://localhost:9050'
    ]
});

const p = await b.newPage();

await p.route(/./, async (route, request) => {
    await route.continue();

    const response = await p.request.fetch('https://api.ipify.org/?format=text');
    const body = await response.body();
    console.log('IP FROM REQUEST FETCH', body.toString());
});

await p.goto('https://api.ipify.org/?format=text');
const body = await p.$('body');
const ip = await body!.textContent();
console.log(`IP FROM BROWSER ${ip}`);
```

**Describe the bug**

When you use chromium with proxy-server argument, requests made with `page.request.fetch` will NOT use the proxy. In the example above I have tor running on localhost:9050 (I use a different socks, tor is the simplest for you to reproduce), I would expect the following output:

```
IP FROM REQUEST FETCH 37.120.185.151
IP FROM BROWSER 37.120.185.151
```

Instead I get the following:

```
IP FROM REQUEST FETCH my.real.ip.here
IP FROM BROWSER 37.120.185.151
```

**Comment by mxschmitt** [comment]
When launching the browser, you can pass the proxy configuration instead by passing a CLI option. See [here](https://playwright.dev/docs/network#http-proxy).

```js
const browser = await chromium.launch({
  proxy: {
    server: 'http://myproxy.com:3128',
    username: 'usr',
    password: 'pwd'
  }
});
```

Let us know if this works for you!

**Comment by monkekode** [comment]
> Let us know if this works for you!

I'm actually connecting to a separate browser with `connectOverCDP`, so I have nowhere to put that option in. I was under the impression that the `p.request.fetch` part should use the browser instance to make the request, it seems however that it's just a convenience method for node.js to do the request without touching the actual browser?

**Comment by pavelfeldman** [comment]
Correct, the actual request is make by Node, but uses browser's cookie store.
