### ISSUE TITLE
[Question] data types in .HAR json

### ISSUE THREAD

**Issue by lic-8** [microsoft/playwright#15982]
Hello, when dealing with the json of the .HAR file, what is the data type of these two fields :

log -> entries -> cache -> beforeRequest
log -> entries -> cache -> afterRequest

Every site I try to scrap returns null. I need to know which type to assign to my Go struct.

Thanks

**Comment by mxschmitt** [comment]
We never set them, so its always `null`, see here about the expanded struct how it could look like in the future: 

https://github.com/microsoft/playwright/blob/7bd72716f960ed11b48447c22f49a3b4ee453eb5/packages/playwright-core/src/server/har/har.ts#L153-L157

**Comment by pavelfeldman** [comment]
Those are optional in HAR, so we don't populate them.
