### ISSUE TITLE
[Feature] Dont remove old local browser

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#15990]
The problem:

I have two project with playwright-test. One project just updated playwright-test to 1.24.1, and I had to run `npx playwright install`.

But when I switched to another project with playwright-test version 1.23.4, I failed to run tests there, because `npx playwright install` led to

```
npx playwright install
Removing unused browser at /Users/d.o.kuznetsov/Library/Caches/ms-playwright/chromium-1012
Removing unused browser at /Users/d.o.kuznetsov/Library/Caches/ms-playwright/firefox-1327
Removing unused browser at /Users/d.o.kuznetsov/Library/Caches/ms-playwright/webkit-1668
```

browsers were removed!

Could you please do not remove browsers, when they actually still might be used?

**Comment by pavelfeldman** [comment]
If there is another Playwright installation using those old browsers, they won't be removed. Only when you erase the old client they are collected.

**Comment by Diokuz** [comment]
Why they were removed then?) I definitely have a project with playwright-test@1.23.4, and I debugged tests there last week.

Another scenario with just one project:

1. Update @playwright-test
2. Update browsers with npx playwright install
3. Face some problems (doesnt matter which ones)
4. Roll playwright-test back to previous version
5. Now you have to run npx playwright install and wait more time

In my case I wait for browsers ~30 minutes.

**Comment by pavelfeldman** [comment]
- Why they were removed then?

I don't know maybe you deleted that project. If you can repro the problem, please send us the steps that we can follow.

- Another scenario with just one project

You can set `PLAYWRIGHT_SKIP_BROWSER_GC=1` env variable to skip the old browser deletion!

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
