### ISSUE TITLE
Getting "Failed to open browser on http://127.0.0.1:9323#?testId=b96b4b0675f4437bc9a4d10897410f898ad7a961-fc546356f638c7128f83693e85ebe46b7a875b8a" error message while running the script via github action(using docker image)

### ISSUE THREAD

**Issue by Ganeshcei** [microsoft/playwright#15995]
![image](https://user-images.githubusercontent.com/107694949/181282196-f348781e-b209-4eef-98f6-96655007c71a.png)

**Comment by Ganeshcei** [comment]
Could any one please help me on this?

**Comment by pavelfeldman** [comment]
Is this happening on CI? It looks like you configured HTML report to force-open on CI for passed tests.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
