### ISSUE TITLE
[Question] how to check if my input text match with what I input ?

### ISSUE THREAD

**Issue by KarolKCzarnecki** [microsoft/playwright#15992]
Hello,
I have a question  ( sorry english isn't my  native  language ) .  when i add text in text field input. For example text_page.locator_text.fill("texttext"). i saved this form. When I open this form text is in there in text field but i want to playwright check it . I try expectect(text_page.locator).to_contain_text("texttext"),  to_have_text  and other but nothing work. Please help me , thank you

**Comment by KarolKCzarnecki** [comment]
I am using python

**Comment by pavelfeldman** [comment]
Please provide a snippet of code that we could use to reproduce your problem.

**Comment by SirCmX** [comment]
Hey @KarolKCzarnecki , sometimes the field also has the text as a Value.
try await expect(page.locator('pseudoCode')).to_have_text("example")
or await expect(page.locator('pseudoCode')).to_have_value("example")

**Comment by KarolKCzarnecki** [comment]
> Hey @KarolKCzarnecki , sometimes the field also has the text as a Value. try await expect(page.locator('pseudoCode')).to_have_text("example") or await expect(page.locator('pseudoCode')).to_have_value("example")
> 
> * I try expectect(text_page.locator).to_contain_text("texttext") -
> 
> As far as i know, this : expectect(text_page.locator).to_contain_text("texttext") does not work. But this : expectect(text_page.locator)).to_contain_text("texttext")

hey thank you !!! I almost positive i tr it before but no matter it is work
