### ISSUE TITLE
[Feature] Different `actionTimeout` when spinner is showing

### ISSUE THREAD

**Issue by mmkal** [microsoft/playwright#16007]
It's not always possible to set a good `actionTimeout` that works everywhere, and in some cases, not even possible to set a good one for a _single_ action.

For example, let's say we have a step in our flow that sometimes takes 0.1s (say when some data is cached), sometimes takes up to 30s, and sometimes (while developing), errors out. Right now, our only choice is to set the timeout to `30_000` either globally or on that action. But because we're aiming to build a good user experience, we tell the user that it might take a while and show a loading spinner while the slow thing is happening. But every time it errors quickly (say, running regression tests on a feature branch), we have to waste 30 seconds waiting, even though a person would have said "hey that's a bug" right away. It'd be great if we could teach playwright to be smart enough to know when we're still working on it, and need a bit more time. Then playwright would be behaving more like a user - it sees a spinner, so it gets less angry about timeouts. Maybe something like this in the config:

```ts
use: {
  actionTimeout: [
    { locator: '.ourFunkyLoadingSpinner', timeout: 60_000 },
    { locator: '.someThirdPartyLoadingSpinner', timeout: 60_000 },
    1000
  ],
}
```

i.e. update the type of `actionTimeout` to be something like:

```ts
export type ActionTimeout = number | { locator: string; timeout: number } | ActionTimeout[]
```

Basically meaning, if playwright sees the CSS class `ourFunkyLoadingSpinner` or `someThirdPartyLoadingSpinner` active/visible in the dom, wait up to 60 seconds. If you don't, wait only one second. This will actively incentivise good UX, because anything that takes more than a second probably _should_ show some kind of loading UI. And, there will be both faster legitimate test failures *and* less flakes because developers no longer have to trade-off fail-fast against robustness.

For more granular control, the `ActionTimeout` type could be passed to any of the methods that accept a timeout prop too:

```ts
const spinnerTimeout: ActionTimeout =  [
    { locator: '.ourFunkyLoadingSpinner', timeout: 60_000 },
    { locator: '.someThirdPartyLoadingSpinner', timeout: 60_000 },
    5000
]

await page.locator('.foo1').click({ timeout: spinnerTimeout })
await page.locator('.foo2').click({ timeout: spinnerTimeout })
await page.locator('.bar').click()
await page.locator('.baz').click({ timeout: 1000 })
```
>Do you think others might benefit from this as well?

Yes!

I'd be willing to implement this if someone could point me in the right direction.

**Comment by pavelfeldman** [comment]
This would be tricky since it might be that spinner shows up after the action has started. As in it starts clicking `foo1` and while it is waiting for the element, spinner shows up. Now we need to re-install all the watchdogs, etc. I don't think it is technically feasible.

As I understand, the contract for your app is that within 5 seconds I either see a spinner or I see an error, so it might make sense to explicitly define it, where you expect it:

```js
async function waitForErrorOrSpinner(page) {
  await page.locator('.error, .spinner').waitFor();
  if (await page.locator('.error').isVisible())
    throw new Error('Error occurred: ', await page.locator('.error').textContent());
  await page.locator('.spinner').waitFor('hidden');
}

await page.locator('.submit').click();
await waitForErrorOrSpinner(page);
```

**Comment by mmkal** [comment]
It's more like, there are two "ok" states the app can get into: 1) success quickly (on cache it), 2) success slowly on cache miss. There are also various "not ok" states - which is why we're using playwright in the first place, the errors I'm talking about are just bugs, not expected app state (obviously we aim to catch these _before_ they get into our main branch).

But yes I think something like that `waitForErrorOrSpinner` could work. We're trying to avoid explicitly looking for a particular error - we'd like to write tests that travel the happy path and if they hit _anything_ else, they fail. So right now something like this might possible:

```ts
test('search', ({ page }) => async {
  await page.locator('.search').click()
  await retryWhileSpinning(page, () => page.locator('.searchResult').click(), {timeout: 30_000})
})

function retryWhileSpinning<T>(page: Page, action: () => Promise<T>, {timeout}: {timeout: number}) {
  const end = Date.now() + timeout
  while (Date.now() < end) {
    try {
      return await action()
    } catch (e) {
      const spinnerVisible = await page.locator('.spinner').isVisible()
      if (spinnerVisible) {
        continue
      }
      throw e
    }
  }
  throw new Error(`Action didn't succeed after more than ${timeout} ms`)
}
```

But it'd be great if `retryWhileSpinning` was internal to playwright so it'd "just" work without having to implement in userland, and could cover edge cases that I've probably missed here. Or even it could maybe be achieved without a try/catch at all (but I don't know what watchdogs are!).

**Comment by pavelfeldman** [comment]
> We're trying to avoid explicitly looking for a particular error - we'd like to write tests that travel the happy path and if they hit anything else, they fail.

That's a fine strategy. In your case, error handling is more of an optimization: you know if the error showed up, there is no point in waiting for the happy path to happen for 30 seconds, you can bail out immediately. As an option, you could do something like `page.waitFor('.error').then(() => throw new Error())`. That'll produce an unhandled exception that will stop the test. I.e. keep your happy path clean and readable + add a bunch of event handlers that make the test fail and save you time.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
