### ISSUE TITLE
[Question] How to stop page from automatically 'bringToFront()'-ing / becoming focused on open?

### ISSUE THREAD

**Issue by objones** [microsoft/playwright#16009]
I have some code, the spirit of which is to open and process a large number of links one after another, but never having more than e.g. 10 tabs open at a time, like so:

```
  tab_lock = asyncio.Semaphore(10)

  async def wrap_open(url):
      await tab_lock.acquire()
      await new_page = browser_context.new_page()
      response = await new_page.goto(url)
      await my_response_handler(response)
      tab_lock.release()

  await asyncio.gather(*[wrap_open(lnk for lnk in all_links])      
```

 Naturally, I want to just set this and forget it, and do other work while it's running, but I cannot, because every time a new page gets opened, it becomes active and focused, stealing focus away from whatever I would otherwise have been working on. If I'm in the middle of typing something, I would have to click back to what I was working on. Processing time is relatively short for each page, but the total number of pages to process is very large, meaning that focus is stolen away constantly, but the entire process takes a long time to complete. I would like to be able to use my computer while this is running in the background.

Is there a way to do something like so?
```
      await new_page = browser_context.new_page(url, becomes_focused_on_open=False)
      await new_page.goto(url, timeout=0, dont_steal_my_focus='PLEASE')
```

[The docs](https://playwright.dev/python/docs/pages#multiple-pages) seem to indicate that it would be at least possible ("Bringing the page to front is not required") but do not show how one would accomplish this task.

**Comment by pavelfeldman** [comment]
New pages will steal focus in the headed mode. It looks like you should uses headless mode instead? You are also running code on 10 pages at a time and are reusing the browser context for several navigation - it'll be flaky and leaky because context keeps navigation data for all pages. You should create a browser per parallel track, and create browser context for each page navigation.

**Comment by objones** [comment]
> New pages will steal focus in the headed mode. It looks like you should uses headless mode instead? You are also running code on 10 pages at a time and are reusing the browser context for several navigation - it'll be flaky and leaky because context keeps navigation data for all pages. You should create a browser per parallel track, and create browser context for each page navigation.

Thanks, this will suffice I suppose.

**Comment by VitoYane** [comment]
you can use `old_page.bring_to_front()` to bring the page to front

**Comment by Kosta-Github** [comment]
> New pages will steal focus in the headed mode.

Would it be possible to make this an option?

I looks like doing a `fetch()` request on that page object is also activating the page, bringing it to the front, and stealing the focus. Something like:

```
const req = await new_page.request.fetch(...);
```

will bring the `new_page` browser window to the front in `headed` mode as well.
