### ISSUE TITLE
[BUG] Not able to assert text in text field

### ISSUE THREAD

**Issue by PfrLisBerndt** [microsoft/playwright#16019]
**Context:**
- Playwright Version: 1.22.0, also tried 1.24.0
- Operating System: Windows

- Browser:  Chromium
- Extra: Using Java-API

**Code Snippet**

```java
PlaywrightAssertions.assertThat(page.locator(target)).hasText(content);
```
respectively
```java
PlaywrightAssertions.assertThat(page.locator(target)).containsText(content);
```

**Describe the bug**

Add any other details about the problem here.
![image](https://user-images.githubusercontent.com/43057926/181502999-b1f5f38f-ef9c-448e-843b-44b02d3abed2.png)

Output is:

> Assert: 'Kunde_auto_690429' on element data-test-id=resource-input-name
14:00:43-07/28/22 ["com.microsoft.playwright.impl.AssertionsBase.expectImpl(com/microsoft/playwright/impl/AssertionsBase.java:73)", "com.microsoft.playwright.impl.AssertionsBase.expectImpl(com/microsoft/playwright/impl/AssertionsBase.java:50)", "com.microsoft.playwright.impl.AssertionsBase.expectImpl(com/microsoft/playwright/impl/AssertionsBase.java:41)", "com.microsoft.playwright.impl.LocatorAssertionsImpl.hasText(com/microsoft/playwright/impl/LocatorAssertionsImpl.java:208)", "com.microsoft.playwright.assertions.LocatorAssertions.hasText(com/microsoft/playwright/assertions/LocatorAssertions.java:889)", ...
14:00:43-07/28/22 14:00:43-07/28/22 Locator expected to have text: Kunde_auto_690429
Received: 

> Call log:
> Locator.expect with timeout 5000ms
> waiting for selector "data-test-id=resource-input-name"
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""
>   selector resolved to <input type="text" id="customer_name" name="customer[na&/>
>   unexpected value ""

**Comment by dimkin-eu** [comment]
because the text in input is stored in `value` ?

**Comment by PfrLisBerndt** [comment]
> because the text in input is stored in `value` ?

May be a point. How can I reach it?
