### ISSUE TITLE
Submitting reports to Xray in globalTeardown script fails as reports are generated after teardown

### ISSUE THREAD

**Issue by lynn-fisher** [microsoft/playwright#16015]
Hi there,

I running tests in playwright and submitting junit report generated to Jira Xray in globalTeardown however the report is not being generated before globalTeardown is called which means it will error first time, as no report is available yet, but second time it will take the report generated first time round.

I am using the xray configuration in playwright conf file as stated in Playwright documentation
```
// JUnit reporter config for Xray
const xrayOptions = {
  // Whether to add <properties> with all annotations; default is false
  embedAnnotationsAsProperties: true,

  // By default, annotation is reported as <property name='' value=''>.
  // These annotations are reported as <property name=''>value</property>.
  textContentAnnotations: ['test_description'],

  // This will create a "testrun_evidence" property that contains all attachments. Each attachment is added as an inner <item> element.
  // Disables [[ATTACHMENT|path]] in the <system-out>.
  embedAttachmentsAsProperty: 'testrun_evidence',

  // Where to put the report.
  outputFile: './xray-report.xml'
};

const config = {
  reporter: [ ['junit', xrayOptions] ]
};

module.exports = config;
```

For the teardown I am just calling a function to submit results after all test run
```
module.exports = async config => {
await submitXrayResults()
}
```
I had assumed teardown would be run after any report generation but it doesn't seem to work that way. Have you any solution that will ensure the reports are generated before teardown is run?

Thanks in advance

**Comment by pavelfeldman** [comment]
Today, you would need to add an additional [reporter](https://playwright.dev/docs/next/test-reporters#third-party-reporter-showcase), that will send your reports in the `onEnd` async callback.

**Comment by lynn-fisher** [comment]
Thank you, Is there a way to use/pass the config to the customer reporter? I need to use the project channel information from the config in the submission to Xray to say if tests where run in Chrome/Edge etc. I had this working in globalTeardown but not sure how to access same information in custom reporter.

Thanks

**Comment by pavelfeldman** [comment]
Yes, there is: https://playwright.dev/docs/next/api/class-reporter#reporter-on-begin

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
