### ISSUE TITLE
I want to automate the test, where I am taking a screenshot of the tab/Window/Screen using Media recorder APIs. How can I do automate that ??

### ISSUE THREAD

**Issue by mitalahir18** [microsoft/playwright#16021]
Hello all, I am also facing a similar issue, Please help if anybody knows!!
I want to automate the test, where I am taking a screenshot of the tab/Window/Screen using Media recorder APIs.
Thanks in advance!

![image](https://user-images.githubusercontent.com/47550251/181519163-b40a8c69-9789-446b-b234-adb74ee3196b.png)

**Comment by pavelfeldman** [comment]
This dialog is not a part of the web page, it is a browser dialog for sharing screen. Playwright does not allow testing native browser parts, it only tests web pages.

**Comment by mitalahir18** [comment]
> This dialog is not a part of the web page, it is a browser dialog for sharing screen. Playwright does not allow testing native browser parts, it only tests web pages.

Thanks, @pavelfeldman for the confirmation we also have doubt about it but I just want to confirm it.
