### ISSUE TITLE
[BUG] Navigation failed because page was closed!

### ISSUE THREAD

**Issue by dstampher** [microsoft/playwright#16031]
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 5.73 GB / 15.73 GB
## Binaries:
 - Node: 18.4.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 8.12.1 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.16 - C:\Windows\system32\bash.EXE
## npmPackages:
 - playwright: ^1.24.1 => 1.24.1
 - playwright-extra: ^4.3.3 => 4.3.3

**Code Snippet**

```
import { chromium } from "playwright-extra";
import stealth from "puppeteer-extra-plugin-stealth";

export default async function createStealthBrowser(
  braveExecutablePath: string,
) {
  chromium.use(stealth());
  let browser = await chromium.launch({
    headless: false,
    executablePath: braveExecutablePath,
  });
  let page = await browser.newPage();
  await page.goto("brave://settings/");
  return browser;
}
```

Test:

```
import { test, expect } from "@playwright/test";
import createStealthBrowser from "../StealthBrowser";

test("Create a stealth browser", async () => {
  let browser = await createStealthBrowser(
    "C:/Program Files/BraveSoftware/Brave-Browser/Application/brave.exe"
  );
  await browser.close();
});

```
**Describe the bug**

The code above results in a failed test with the message "page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "brave://settings/", waiting until "load"
    ============================================================"

The page should not be closed.  If I change the uri to example.com, this error does not occur.  I need to be able to navigate to the settings URI for my browser (Chromium based).

**Comment by pavelfeldman** [comment]
You can't access internal pages with Playwright.

**Comment by dstampher** [comment]
@pavelfeldman Ah, would be great if the error message was a bit more explicit.  Currently it says basically nothing :)  Just that the page closed.  
Also, since Brave does not have launch flags for certain options that I need to set, and I cannot access internal pages with Playwright (I was able to with Puppeteer), I suppose there is no way to set the options that I need with Playwright?
