### ISSUE TITLE
[Question] CSS > position:absolute not visible

### ISSUE THREAD

**Issue by Misha31** [microsoft/playwright#16039]
Hello.

Faced the problem of finding links with absolute positioning.
Example page:

```
<style>
    #main{
        width:30%;
        height:30%;
        background:#FFA500;
    } 
    #menu{
        position:absolute;
        top:-30%;
        left:0;
    }
</style>
<div id="main">
    
</div>
<div id="menu">
    <ul>
        <li><a href="link1.html">link1</li>
        <li><a href="link2.html">link2</li>
        <li><a href="link3.html">link3</li>
    </ul>
</div>
<div>
    <ul>
        <li><a href="link4.html">link4</li>
        <li><a href="link5.html">link5</li>
        <li><a href="link6.html">link6</li>
    </ul>
</div>
```

This page looks like this - https://prnt.sc/GwnoZ5S_r7bU

My function:
```
def visible_links():
    links = page.locator('a:visible')
    for i in range(links.count()):
        if links.nth(i).is_visible() == True:
            print(f'{links.nth(i).get_attribute("href")} is visible')
        else:
            print(f'{links.nth(i).get_attribute("href")} not visible')
        try:
            expect(links.nth(i)).to_be_visible()
            print(f'{links.nth(i).get_attribute("href")} is visible')
        except AssertionError:
            print(f'{links.nth(i).get_attribute("href")} not visible')
```

The result of the function execution:
```
link1.html is visible
link1.html is visible
link2.html is visible
link2.html is visible
link3.html is visible
link3.html is visible
link4.html is visible
link4.html is visible
link5.html is visible
link5.html is visible
link6.html is visible
link6.html is visible
```

For the first three links, my script can't click.
How can you tell if a link is hidden?

**Comment by pavelfeldman** [comment]
This is consistent with our visibility definition: https://playwright.dev/docs/actionability#visible

**Comment by Misha31** [comment]
> 

Please tell me how to determine that this block of links is hidden?

**Comment by pavelfeldman** [comment]
You could check `locator.boundingBox()` manually to compare to the viewport boundaries.

**Comment by Misha31** [comment]
Thanks for your help, this method will work.

```
{'x': 40, 'y': -310.6875, 'width': 32.890625, 'height': 17}
{'x': 40, 'y': -292.6875, 'width': 32.890625, 'height': 17}
{'x': 40, 'y': -274.6875, 'width': 32.890625, 'height': 17}
{'x': 48, 'y': 345.890625, 'width': 32.890625, 'height': 17}
{'x': 48, 'y': 363.890625, 'width': 32.890625, 'height': 17}
{'x': 48, 'y': 381.890625, 'width': 32.890625, 'height': 17}
```

**Comment by Misha31** [comment]
Now I encountered the following problem, some of the links are hidden by the "opacity:0" property.
Tried via "XPath" - page.locator("//a[not(contains(@style, 'opacity:0'))]"), failed, this property has "div" block, not "a".
On other sites, it may not be a "div", so it's better not to use it.
Can you help solve the problem?

**Comment by pavelfeldman** [comment]
You seem to be using xpath against a JS property rather than an attribute. You can do something like

```js
await expect(locator).toHaveCSS('opacity', '1');
```

checking present value can be done with:

```js
const value = await locator.evaluate(el => window.getComputedStyle(el).opacity);
```

**Comment by Misha31** [comment]
Thanks for the help.
For some of the links, this solution helped - opacity = int(page.locator(f':nth-match(a[href="{href}"],1)').evaluate("el => window.getComputedStyle(el. parentElement).opacity")), the links themselves have the property opacity:1, and their parent opacity:0.
But there are also links in which the parents of the 6th nesting level have opacity:0, what to do with them?

Example:
```
<div style="opacity:0">
  <ul>
    <li>
      <ul>
        <li>
          <span>
            <a href="link.html">link.html</a>
          </span>
        </li>
      </ul>
    </li>
  </ul>
</div>
```

**Comment by Misha31** [comment]
I mean, on other sites, it might be a different level of nesting.
Really to check each block?

**Comment by mxschmitt** [comment]
Yes, closing as per above.

For further questions please file new issues.
