### ISSUE TITLE
[Question] same test file in different path , one works , the other one  running 0 test

### ISSUE THREAD

**Issue by changchichung** [microsoft/playwright#16042]
I create a test file with codegen and store it in the sub-directory of the working DIR
then run test but no tests found
```
chc@dc034:~/playwright$ npx playwright test onduty/onduty.spec.js 

Running 0 test using 0 worker


=================
 no tests found.

To open last HTML report run:

  npx playwright show-report
```
then I copy the test file into the tests sub-folder
then it works
```
chc@dc034:~/playwright$ npx playwright test tests/onduty.spec.js 

Running 3 tests using 2 workers

  3 passed (20s)

To open last HTML report run:

  npx playwright show-report

chc@dc034:~/playwright$ 
```

is that a "normal" behavior ?
should I store all ests files in tests folder ?

**Comment by Ghislain89** [comment]
I think Playwright looks for existing projects in your playwright.config.ts. Have you defined a project there?

**Comment by pavelfeldman** [comment]
Your config file `playwright.config.ts` is probably pointing at the `tests` folder.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
