### ISSUE TITLE
playwright-transform-cache causes permission issue when different users run tests

### ISSUE THREAD

**Issue by autTestUser** [microsoft/playwright#16044]
playwright-version: **1.21.1**
OS: **Linux (Ubuntu 20.04)**

If the same test case is run by different users, there is a permission issue as shown below. Whoever first runs the test would have the proper permission since the folders and files under **/tmp/playwright-transform-cache** would be created by that user. Is there a way to redirect this cache to each user's home directory instead of in the **/tmp/** directory.

**Error:**

Error: EACCES: permission denied, mkdir '/tmp/playwright-transform-cache/bc'

**Comment by autTestUser** [comment]
Any updates here? Is there any temporary solution for this?

**Comment by TravisJRyan** [comment]
I am also seeing this issue, and I believe it prevents Playwright from working in a multi-user environment.

@pavelfeldman How would we feel about some optional config TMP_DIR_PREFIX so users in such an environment can run Playwright in parallel? I see in the code there is an [environment variable](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/transform.ts) to override the tmp dir, but this isn't anywhere in the docs so I'm wary this isn't the right way for a user to resolve this as it could go away.

**Comment by pavelfeldman** [comment]
This has been fixed.
