### ISSUE TITLE
[Question] HTML Reports not displaying correctly on Jenkins

### ISSUE THREAD

**Issue by ElliottDevlinPA** [microsoft/playwright#16051]
Hi,

I'm currently having an issue with the built-in HTML Playwright reporter and Jenkins. When a run completes on Jenkins and I try to view the report I get a blank screen (see below image). I am able to download a zip of report, but ideally I'd like it to be displayed in Jenkins for quick reference. 

I have Implemented the Publish HTML plugin in my Jenkinsfile which I believe should allow the report to be displayed (see code snippet below for ref), however, I still get the blank page. 

Is this an issue you are aware of and needs raising as a bug, or are you able to advise if I'm doing something wrong / there is a way of resolving the issue? 

Many thanks,
Elliott. 

Jenkinsfile snippet...

`      post {
        always {
          publishHTML([
            allowMissing: false, 
            alwaysLinkToLastBuild: true, 
            keepAll: true, 
            reportDir: 'playwright-report', 
            reportFiles: 'index.html', 
            reportName: 'Playwright Test Report', 
            reportTitles: ''])
        }
      }`

![image](https://user-images.githubusercontent.com/38210127/181762309-891731a8-74c7-4b24-9c29-8fd3dab75de3.png)

**Comment by pavelfeldman** [comment]
If your report opens locally, but fails to open when served from Jenkins, it is most likely a deployment problem. Opening Chrome DevTools and looking at the Console is likely to give you a clue on what went wrong.

**Comment by ElliottDevlinPA** [comment]
Hi @pavelfeldman  - thank you for your response. 

This is the error I get in the console....

`Blocked script execution in 'https://jenkins.pa.media/job/Content/job/Playwright%20WordPress%20POC/job/main/250/Playwright_20Test_20Report/index.html' because the document's frame is sandboxed and the 'allow-scripts' permission is not set.`

`Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-/BmZIwo4U7tGdEu4eoGTQsTFJ6x+RjQWE2Go6kGVMEU='), or a nonce ('nonce-...') is required to enable inline execution.`

Are you aware of a solution for this please?

**Comment by Nav-2d** [comment]
Hi @ElliottDevlinPA - Here is the related issue that will help you: https://github.com/microsoft/playwright/issues/10274

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by ElliottDevlinPA** [comment]
OK, I'll take a look. Thank you, both.
