### ISSUE TITLE
[BUG] Example test works on chromium and webkit but fails on firefox

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#16057]
**Context:**
- Playwright Version: latest
- Operating System:  Mac Monterey version 12.4 (2019)
- Node.js version: 18.7
- Browser: All
- Extra: 

**Describe the bug**

Installing Playwright using npm init command and running the test as per getting started guide and test fails on Firefox on line 4 of test which is await page.goto('https://playwright.dev/')

**Error messages show:**

page.goto: SEC_ERROR_UNKNOWN_ISSUER

navigating to 'https://playwright.dev/', waiting until load

**other info**
Was running on node v14.17 and still had problems
Was also running big sur previously and problems with that version too
Updating system and node did not solve the issue

**Comment by pavelfeldman** [comment]
This suggests that your machine does not recognize the trusted certificate authorities. Did you update your machine?

**Comment by debs-obrien** [comment]
Interesting. I see another software update from Mac so will try that and get back to you.

**Comment by debs-obrien** [comment]
Updating to latest version did not fix the issue. Still get same error

**Comment by debs-obrien** [comment]
Ohh I see, running in debug mode gives me an error saying Did not connect: Potential Security Issue. Any idea how to fix that issue. So the test can run. Is it an issue with the website, my computer, browser ? Not on corporate network and not using anti-virus

**Comment by debs-obrien** [comment]
When running in debug mode and stepping through:
<img width="1648" alt="Screenshot 2022-07-29 at 20 35 25" src="https://user-images.githubusercontent.com/13063165/181823327-a127cfc6-70cb-400d-8b1c-0eaf50299220.png">

**Comment by pavelfeldman** [comment]
I searched for the error message and here is what I got: https://windowsreport.com/firefox-not-connect-potential-security-issue/

**Comment by debs-obrien** [comment]
Test now working after removing antivirus
