### ISSUE TITLE
Parrallel execution[Question]

### ISSUE THREAD

**Issue by tomern** [microsoft/playwright#1605]
Hi,
I would like to know how can you run playwright tests in parallel on same browser,
I know you can the following in order to run the same tests parallelly on different browsers.
Is there a test runner you can use in order to avoid using Promise.all method?

(async function() {
  await Promise.all([
      test(firefox),
      test(chromium)
    ]);
})();

**Comment by arjun27** [comment]
Hi @tomern, you can use BrowserContexts to create parallelized executions in the same browser. See our [core concepts](https://github.com/microsoft/playwright/tree/master/docs/examples#core-concepts) guide that attempts to explain it. Let me know if need more details

**Comment by nrayburn-tech** [comment]
Also, #1736 has an example of doing it for multiple browsers as well.

**Comment by aslushnikov** [comment]
> I would like to know how can you run playwright tests in parallel on same browser

@tomern For the original request here: we're getting ready to release our test runner (please follow https://github.com/microsoft/playwright/issues/3552) which will support parallel test running and should cover all the needs there. Please keep an eye there!

> I think it may be worth creating an example for it.

@nrayburn-tech so far it hasn't been brought many times, so I think the documentation is sufficient here.
