### ISSUE TITLE
[BUG] testConfig.use.viewport doesn't work

### ISSUE THREAD

**Issue by vladkrasn** [microsoft/playwright#16061]
**Context:**
- Playwright Version: 1.24.2
- Operating System: Windows 11
- Node.js version: 16.15.1
- Browser: All

**Code Snippet**

```javascript
const config: PlaywrightTestConfig = {
    use: {
        viewport: null,
    }
}
```
```javascript
const config: PlaywrightTestConfig = {
    use: {
        viewport: { width: 1920, height: 1080 },
    }
}
```

**Describe the bug**

Can't set viewport size in playwright.config.ts file. page.setViewportSize() works though

**Comment by pavelfeldman** [comment]
Is this your full config, or do you have something like

```js
      use: {
        ...devices['Desktop Chrome'],
      },
```
in your projects section? Noe that device includes the viewport definition, so in this case you overwrite your value with it.

**Comment by vladkrasn** [comment]
Thank you, didn't know it did that
