### ISSUE TITLE
[BUG] `response.status_text` is empty on Chromium

### ISSUE THREAD

**Issue by joe733** [microsoft/playwright#16062]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Linux
- Python version: 3.10.5
- Browser: Chromium

**Code Snippet**

```python
from playwright.sync_api import sync_playwright, Page, Browser, BrowserContext, Response


def main():
    """Main"""
    with sync_playwright() as spw:
        brw: Browser = spw.chromium.launch()
        # print('Browser was launched!')
        cxt_main: BrowserContext = brw.new_context(ignore_https_errors=True)
        # print('Context was created!')
        page: Page = cxt_main.new_page()
        # print('Opened a new page!')
        resp: Response = page.goto('https://stackoverflow.com/404')
        print(resp.status_text) # empty str
        cxt_main.close()
        # print('Context was closed!')
        brw.close()
        # print('Browser was closed!')


main()
```

**Describe the bug**

On Chromium `response.status_text` is always empty.

**Comment by rwoll** [comment]
If you go to `https://stackoverflow.com/404` in stock FF, CR, and WK, and then run: `fetch("https://stackoverflow.com/404").then(r => console.log(r.statusText))` you'll see Firefox is the only one to have `statusText` in this case (site doesn't set it explicitly), so I believe Playwright's behavior here is appropriate.

/cc @pavelfeldman

**Comment by joe733** [comment]
> you'll see Firefox is the only one to have `statusText`

Running the above command & looking at network headers in the inspect tool, I see `statusText` for both Firefox and WebKit.


Firefox `102.0 (Nightly Build) (64-bit)`:

![image](https://user-images.githubusercontent.com/38415384/181865565-096943a4-4732-491d-a67c-77ffcb1a0aac.png)

WebKit:

![image](https://user-images.githubusercontent.com/38415384/181865786-71e3e1d7-ddfd-4297-a6a2-5ea3cbf78196.png)

**Chromium** `104.0.5112.48 (Developer Build) (64-bit)`:

![image](https://user-images.githubusercontent.com/38415384/181865365-aeb40dc8-dcf9-489e-8d2c-cabfe192f1fc.png)

 Only chromium does not show. Looks like an upstream issue (Edge does not show either).

**Comment by pavelfeldman** [comment]
These tools are being friendly to you and offer default status text values for respective codes. In reality, this site does not return status text, you can use low level network tools to check it, for example, run:

```sh
curl -i https://stackoverflow.com/404
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
