### ISSUE TITLE
[BUG] page.url() - doesn't return actual url

### ISSUE THREAD

**Issue by aalcatelz** [microsoft/playwright#16072]
**Context:**
- Playwright Version: 1.24
- Operating System: Windows
- Node.js version: 16.16.0
- Browser: Chromium

**Code Snippet**
```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://playwright.dev/');
  const url1 = page.url();
  // url1 equals 'https://playwright.dev/" - that's correct behaviour
  // manually navigate to other page, e.g. "https://www.selenium.dev/"
  const url2 = page.url();
  // url2 still equals 'https://playwright.dev/", but expected "https://www.selenium.dev/" (edited) 
})();
```
page.url() - doesn't return actual url

**Comment by pavelfeldman** [comment]
This is as designed, Playwright assumes that it controls the navigation flow, so the manual navigations are not reflected in the `page.url()` value. You can use `await page.evaluate(() => window.location.href)` to obtain the current URL as a workaround for the hybrid and non-testing scenarios.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by neaumusic** [comment]
is there a way to keep it in sync and up to date? I don't think this is a great idea to assume that it controls the navigation flow, does this also apply to click / typing in the browser? is there no way to get the latest state unless you used playwright to perform an action?

**Comment by coolalexhuang** [comment]
> This is as designed, Playwright assumes that it controls the navigation flow, so the manual navigations are not reflected in the `page.url()` value. You can use `await page.evaluate(() => window.location.href)` to obtain the current URL as a workaround for the hybrid and non-testing scenarios.

Even I used page.goto(another URL), the page.url function still returns an legacy one.
code sample:
page.goto(url_a) 
print(page.url) # return url_
page.got(url_b)
print(page.url) # **expect to return url_b, but still got url_a**

**Comment by Taro9000** [comment]
i used `await page.waitForURL(regex, { timeout: 0 });`, a `while` loop and a `try` statement so that it forces playwright to update the url, if just want to update the url i think you can use `await page.waitForURL('.*')`

When the `timeout` is set to zero, it is interpreted as "no timeout"
The `.` in the regex stands for "any cahracter" and when combined with the `*` it means any character repeated any times, so it will practically match every string.
