### ISSUE TITLE
[Question] Apple M1 defaults to 1 worker per thread

### ISSUE THREAD

**Issue by TaylorMichaelHall** [microsoft/playwright#16074]
We recently updated from Playwright/test 1.19.0 to 1.24.1 and I noticed that the Playwright test runner now defaults to using 8 workers on my 8-core M1 Macs when it used to default to 4 workers on the same machines. 

I expect to get 1 worker for every 2 threads, but since M1 isn't hyperthreaded I'm now getting 1 worker for every 1 thread on this chip. I haven't found it to be unstable so far but I'm just curious if this was intentional for this architecture and what the reason was. Thank you!

**Comment by pavelfeldman** [comment]
It was intentional. Our experiments showed that M1 alloed a bit more stress than we typically put on the hyperthreaded Intel. When you are saying unstable, what exactly do you mean? Could it be that additional stress surfaced existing race conditions that were previously manifesting rarely?

**Comment by mxschmitt** [comment]
Closing as per above.
