### ISSUE TITLE
[Question] How to remove control chars in TestError.message?

### ISSUE THREAD

**Issue by lzh66** [microsoft/playwright#16084]
Hi, I got some questions here. When I implement custom reporter, I want write error message to file. But I found that there are some mistakes occur when I use result.errors[i].message, cause some control chars like:
 [31mTimeout of 60000ms exceeded.[39m
I only need message like "Timeout of 60000ms exceeded." because control chars make write file fail. In addition, there are many similar situations which control chars in TestError.message. I want to know if Playwright provide some config to output plain text in TestError.message? Or some useful solutions?
Thanks. :)

**Comment by mxschmitt** [comment]
We have a internal utility function for it, I recommend copying it and using it as well:

https://github.com/microsoft/playwright/blob/62e4e80599efc00a799a389ee4be76c74c9f172b/packages/playwright-test/src/reporters/base.ts#L433-L436
