### ISSUE TITLE
Question : Extending HTML reporter to create custom reporter

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#16089]
Is it possible to extend the currently available html reporter to create a custom reporter with some extra information added ? I would also like to access "option" fixtures present within my configuration in this reporter as well.kindly advise.

**Comment by mxschmitt** [comment]
This is not possible, but you can add custom annotations to your tests, would that work for you? https://playwright.dev/docs/test-annotations#custom-annotations

What kind of information do you want to add?

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/issues/11319
