### ISSUE TITLE
Having issues with looping through and read the dropdown values?

### ISSUE THREAD

**Issue by AbhilashAus** [microsoft/playwright#16088]
I  am using latest version playwright and  wrote few lines of code to read dropdown values available to user using a for loop. But when constant, used to find number of elements in an array, that constant is not recognized. Here is the brief explanation of my code using nodeJS;

- Opened the Webpage
- Created a constant dropdown object
- Created constant array to read elements in the dropdown
- Write to console, number of elements in array 
- Then tried to use this array

I am attaching screenshot of editor showing  code and error text  node JS displayed.  Please help me overcome this issue and read the  text values option1  and option2 from the dropdown.
![Screenshot 2022-08-01 180928](https://user-images.githubusercontent.com/110386314/182126520-5dc6200f-3e42-4121-8c15-52ab4ba3140b.png)

**Comment by mxschmitt** [comment]
We recommend to not use ElementHandles, (page.$ etc.) see here: https://playwright.dev/docs/locators#locator-vs-elementhandle

In your case, this example would probably fit very well for you: https://playwright.dev/docs/locators#lists
