### ISSUE TITLE
[BUG] Assertion not_to_contain_text only asserts that locator doesn't  contain at least *one* string of a given list

### ISSUE THREAD

**Issue by jammon** [microsoft/playwright#16083]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Mac
- Node.js version: v16.15.1
- Browser: Chromium
- Extra: Python 3.8

**Code Snippet**

```python
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.set_content(
        "<div>The quick brown fox jumps over the lazy dog.</div>"
    )
    expect(page.locator("div")).not_to_contain_text(
        ["fox", "hound"]
    )  # doesn't fail
    expect(page.locator("div")).not_to_contain_text(
        ["The", "quick", "brown", "fox", "hound"]
    )  # doesn't fail
    expect(page.locator("div")).not_to_contain_text(
        ["The", "quick", "brown", "fox"]
    )  # fails
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

The assertion `not_to_contain_text` passes if there is at least *one* string in the list which the text does not contain.
I expected that it asserts that every string in the list is not part of the locator.
Instead it asserts that there is at least *one* string in the list that is not part of the locator.

Maybe the documentation should be clarified as to which behaviour is to be expected.

**Comment by mxschmitt** [comment]
`to_contain_text` has two modes, either you specify a string, then the element is asserted or you specify a list, then it gets treated as a list of elements, which is asserts against the given list of strings. See here: https://playwright.dev/python/docs/test-assertions#locator-assertions-to-contain-text

In your case, you are having a single locator element (`div`) where you assert a list against, which is always false.

In your scenario you want to instead pass a single str instead of str[].

**Comment by jammon** [comment]
`to_contain_text` is ok, there is no problem.
It is `not_to_contain_text` where it gets dubious. Is it intended to assert that the locator does not contain **one** of the strings in the list? Or should it return true only if **all** of the strings in the list are not part of the locator.
My expectation was the former, the observed behaviour is the latter.

My current workaround is
```python
for s in list_of_strings:
    expect(locator).not_to_contain_text(s)
```

**Comment by mxschmitt** [comment]
It won't return anything, it will throw if the condition is not met. In your example it will make sure that the locator text does not contain any of the strings inside "list_of_strings".

Does this answer your question?

**Comment by jammon** [comment]
Sure, obviously you're right about return vs. throw. My fault.

Now I understood that list of strings is meant for cases where the locator catches a list of elements. But the behaviour is not very consistent or obvious:
```python
    page.set_content(
        "<div>The quick </div>"
        "<div>brown fox </div>"
        "<div>jumps over </div>"
        "<div>the lazy dog.</div>"
    )
    # one string for every element
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
            "jumps",
            "the",
        ]
    )  # ok, doesn't throw

```
What about less strings?
```python
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
        ]
    ) # seems to be ok
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "jumps",
        ]
    ) # ok as well
```
More strings?
```python
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
            "jumps",
            "the",
            "lazy",
        ]
    )  # ok
```
Does the additional string matter?
```python
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
            "jumps",
            "the",
            "foo",
        ]
    )  # throws, so obviously it does matter.
```
What about this?
```python
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
            "jumps",
            "the",
            "quick",
        ]
    )  # throws, so the order of strings seems to matter.
```
Adding a word from the last element is ok, a word from a previous one  not

How about inserting additional strings at the "right" place?
```python
    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown", "fox",
            "jumps",
            "the", "lazy",
        ]
    )  # ok.

    expect(page.locator("div")).to_contain_text(
        [
            "The",
            "brown",
            "jumps",
            "the", "lazy",
            "fox",
        ]
    )  # throws
```
Looks like the assertion works its way through the list of strings/patterns; if it isn't found in the first element the next element is used, but it won't go back.
This is not what I understood from the documentation. But is it meant to be this way?

**Comment by mxschmitt** [comment]
Good catch, we actually a few weeks ago wanted to sort that out. since toContainText means:
a) match a subset of a text
b) match a subset of elements

which is sometimes confusing.

Relates: https://github.com/microsoft/playwright/pull/15685 and https://github.com/microsoft/playwright/issues/15666

I think we can merge it into https://github.com/microsoft/playwright/pull/15685

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/pull/15685
