### ISSUE TITLE
How can I set to localstorage and get that item in Playwright?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16094]
I want to set the **Identity.States.token**  to localstorage .After that I want to get that localstorage item in different file.But localStorage.setItem('token', 'Identity.States.token') doesn 't work.Taking below error;

`localStorage is not defined `

How can I set to localstorage and get that item in Playwright? **Could you give me an example on my code**

This is my Identity.api.ts file ;

```
export const Identity = {
States:{
token:{} as any
},
API: {
Token: {
run: async () => {
data:{
userName:"yusuf",
password:"öztürk"
}
const response = await axios({
method: "POST",
url: "test",
data: data,
headers: {
"Content-Type": "multipart/form-data",
},
});
Identity.States.token = response.data.access_token;
console.log("data", Identity.States.token);
},
},
},
};
```

**Comment by mxschmitt** [comment]
You need to use page.evaluate, then it will work, see here: https://playwright.dev/docs/evaluating

Since browser JS != Node.js JS context.

In your case something like that:

```
const token = '';
await page.evaluate(token => localStorage.setItem('Identity.States.token', token), token)
```

localStorage is a key/value storage, so you need to e.g. use JSON.stringify to serialise it.

**Comment by mxschmitt** [comment]
I guess you want to set the token since you are writing end-to-end tests with Playwright? https://playwright.dev/docs/intro

Or could you describe a little bit more your scenario for what you are using Playwright?

**Comment by YusufOzturk-Development** [comment]
@mxschmitt  I will not develop end to end test on browser . I m developing API test on swagger. So I will use that token for autantication before the other requests .I want to use set and get "Identity.States.token" to localstorage and use it for autontication in different file

**Comment by mxschmitt** [comment]
Then this is not related to Playwright. Local storage tokens don't get sent over the wire when you perform http requests. You need JavaScript evaluation for that.

Closing since there is nothing actionable on our side.

**Comment by guruje01** [comment]
@mxschmitt , Hope you are doing good,

I am trying to get the item using local storge and facing **ReferenceError: localStorage is not defined** error
code:
localStorage.getItem('conversationId')
Could you please help me.

**Comment by TeaRex-coder** [comment]
@gruje01 Below is a playwright test I wrote to scrape savedBoard from nyt-connections-key in local storage and save it to the savedBoard.json file. Despite it being Python, maybe the example will help? 

```python
from playwright.sync_api import Page
import json

def test_scrapeConnections(page: Page):
    page.goto("https://www.nytimes.com/games/connections")

    # scrape savedBoard item from nyt-connections-beta key
    savedBoardJson = page.evaluate(
        """
        () => {
            const nytConnectionsBeta = localStorage.getItem('nyt-connections-beta');
            if (nytConnectionsBeta) {
                const data = JSON.parse(nytConnectionsBeta);
                return data.savedBoard;  // only scrape savedBoard
            }
            return null;  // return null if savedBoard or nyt-connections-bets key cannot be found
        }
    """
    )

    if savedBoardJson:
        # save savedBoard to json file
        with open("savedBoard.json", "w") as file:
            json.dump(savedBoardJson, file)
```
