### ISSUE TITLE
Error - page.$eval: Error: eval is disabled

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#16102]
I have this code to get the text of an element but it is failing with error `page.$eval: Error: eval is disabled` Can someone please help?

```   
 const getNumOfRows = await this.page.$eval(NewSim.NewSimPages.templateRows, (el) => el.textContent.split(':'));

**Comment by gauravgandhi1315** [comment]
My application might be disabling `eval`. Is there any other alternate to this?

**Comment by mxschmitt** [comment]
Seems like its disabled by [content security policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). You could set the `bypassCSP` when launching the context, or inside the playwright config, depending on how you consume Playwright.

**Comment by gauravgandhi1315** [comment]
@mxschmitt I tried to put `    bypassCSP: true` under `playwright.config` but didn't work. Am I doing it the right way?

**Comment by mxschmitt** [comment]
you need to put it under the `use` object: https://playwright.dev/docs/api/class-testoptions#test-options-bypass-csp

**Comment by gauravgandhi1315** [comment]
@mxschmitt thats what I need `bypassCSP: true` under the use object but it didn't work

**Comment by gauravgandhi1315** [comment]
@mxschmitt What else I can try?

**Comment by mxschmitt** [comment]
Can you share with us a repro?

**Comment by gauravgandhi1315** [comment]
@mxschmitt Sorry I won't be able to share my repo. But I do know `eval` is disabled on our pages. Is there any other alternative to eval that I can use?

**Comment by mxschmitt** [comment]
There is unfortunately not! How is eval disabled tho?
