### ISSUE TITLE
How can i test print/save in playwright?

### ISSUE THREAD

**Issue by amitNinjax2730** [microsoft/playwright#16100]
Example:-
I have a page and there is some data on it. We have a button for print and save which will call window.print().
I am using the html of page and creating the print page using window.open() and opens the about:blank and the print tab above that.

![image](https://user-images.githubusercontent.com/53232520/182176602-8345f794-305a-45ff-b7b3-8fe033a53018.png)

Issue:- 
When i am using playwright and try to click on print/save button using the (locator).click() the print page is blank without any data.

Expected:-
Need the html data to be in the print page.

**Comment by mxschmitt** [comment]
This is not yet possible, folding into https://github.com/microsoft/playwright/issues/6543.
