### ISSUE TITLE
[Question] How To Configure PLAYWRIGHT_DOWNLOAD_HOST

### ISSUE THREAD

**Issue by Zeckie** [microsoft/playwright#16128]
Our organization uses an internal artefact repository, and mirrors multiple repositories such as pypi (python packages), maven central. Each repository has a separate path (eg https://repository.ourdomain.example/pypi/ and https://repository.ourdomain.example/mavencentral/). 

https://playwright.dev/docs/browsers#download-from-artifact-repository shows an example of using the environment variable PLAYWRIGHT_DOWNLOAD_HOST (as an ip address only). Is that all it can be used for? Can it also be used specify the path (and not just the hostname) used for playwright downloads, and other parts of the URL, such as protocol and port?

**Comment by mxschmitt** [comment]
It should be also possible to have something like:

`'https://playwright.your-company.net`

or:

`'https://playwright.your-company.net/foobar/bar`

**Comment by mxschmitt** [comment]
Closing as per above.
