### ISSUE TITLE
[BUG] `validateConfig` does not catch an ESM config with wrong exports

### ISSUE THREAD

**Issue by atjn** [microsoft/playwright#16122]
**Context:**
- Playwright Version: 1.24.2
- Operating System: Linux
- Node.js version: 16.16.0
- Browser: N/A
- Extra: Using JS ESM modules with `type:module` in `package.json`

**Describe the bug**

1. Define a `playwright.config.js` file, and define the export as a named `config`:

```javascript
export const config = {
  testDir: "./tests",
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  ...
```
2. Try to run playwright with `npx playwright test`.

3. Observe that you see a weird error message that doesn't explain what you did wrong:

```
TypeError: Cannot add property forbidOnly, object is not extensible
    at Loader._processConfigObject (/home/anton/Documents/GitHub/easy-web-app-builder/node_modules/@playwright/test/lib/loader.js:94:23)
    at Loader.loadConfigFile (/home/anton/Documents/GitHub/easy-web-app-builder/node_modules/@playwright/test/lib/loader.js:81:16)
    at Runner.loadConfigFromResolvedFile (/home/anton/Documents/GitHub/easy-web-app-builder/node_modules/@playwright/test/lib/runner.js:96:12)
    at runTests (/home/anton/Documents/GitHub/easy-web-app-builder/node_modules/@playwright/test/lib/cli.js:153:27)
    at Gr.<anonymous> (/home/anton/Documents/GitHub/easy-web-app-builder/node_modules/@playwright/test/lib/cli.js:70:7)
```

**Further details**

The program cannot run because you defined a named export instead of a default export. Changing to a default export like this:
```javascript
export default {
  testDir: "./tests",
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  ...
```
..solves the problem and allows playrwight to run without errors.

My problem here is that the error message doesn't make that clear. The [`validateConfig`](https://github.com/microsoft/playwright/blob/3112edb4cae8285f2fde2652a16c141211cebf1f/packages/playwright-test/src/loader.ts#L79) function should detect that there is no default export, and should throw an error message that clearly explains to the developer that the mising default export is the problem.

I ran into this issue because playwright generated CommonJS exports even though I had everything set up as ESM modules. I manually changed the exports to ESM-style, but accidentally exported the config as named instead of default, and had a hard time figuring out what I did wrong because there was no help to find in the error message.

**Comment by mxschmitt** [comment]
We thought about it a while ago, but doing it has some caveats, so we didn't proceed. Relates to https://github.com/microsoft/playwright/pull/12461. Will mark it as p3 so we can eventually pick it up again.

**Comment by atjn** [comment]
Very cool, thanks :)

**Comment by queengooborg** [comment]
Can confirm this issue is still present, found whilst converting MDN Web Docs' engine to ESM (see https://github.com/mdn/yari/pull/7623).  The above fix helped, but the error message could have been more helpful.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
