### ISSUE TITLE
[BUG] Cannot run Playwright tests using playwright server on different minor versions

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#16129]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Mac
- Node.js version: 14.6
- Browser: All

**Describe the bug**
I am running Playwright using the Playwright server. I noticed few inconsistencies while running the tests.
The tests run as expected when the server and client version is the same. It throws error when they are different.

According to semantic versioning, the API contacts should be compatible **when using different minor versions**. If its a breaking change, you **need to update the major version**. As can be seen below, the minor versions `1.23.4` and `1.18.0` does not work with each other. Similar are the other cases.

A few cases are mentioned below:

Server version: `1.23.4`
Client version: `1.18.0`
Error:
```
Playwright: Connection dispatch error
Error: Missing type Tracing
```
<hr/>

Server version: `1.19.4`
Client version: `1.18.0`
Error:
```
Playwright: Connection dispatch error
Error: Missing type Tracing
```
<hr/>

Server version: `1.17.2`
Client version: `1.18.0`
Error:
```
Playwright: Connection dispatch error
TypeError: Cannot read property '_object' of undefined
```
<hr/>

**Comment by mxschmitt** [comment]
This is expected, there is a strong connection between the client and server version, and we recommend to also match on the patch version to guarantee compatibility. 

Playwright does not follow Semver in launchServer/connect API - I'll update the docs in that regard.

**Comment by ankur-lt** [comment]
@mxschmitt , but if the library is following semver, all the APIs in it are also bound to follow it. We cannot have a few functions to follow semver and not for others.
