### ISSUE TITLE
[BUG] Webkit - page.reload: Frame load interrupted

### ISSUE THREAD

**Issue by BartVanRaemdonck** [microsoft/playwright#16147]
**Context:**
- Playwright Version: [1.22.2]
- Operating System: [Mac]
- Node.js version: [v16.6.0]
- Browser: [WebKit]

**Code Snippet**

```javascript

       await defaultPage.goto(site);
        await defaultPage.refresh();





    async refresh(){
        console.log("page is refreshing");
       //await this.page.refresh(); 
       //await this.page.reload(); 
       //await this.page.reload().catch(e=>undefined);
       await this.page.reload();
    }

```

**Describe the bug**

On Chrome and FF this works perfectly.
On Webkit I got this error:

page.reload: Frame load interrupted
=========================== logs ===========================
waiting for navigation until "load"

**Comment by mxschmitt** [comment]
Can you share a full repro with us which we can locally?

**Comment by BartVanRaemdonck** [comment]
Here is a simple example where I can reproduce the bug:
[playwright_example.zip](https://github.com/microsoft/playwright/files/9244040/playwright_example.zip)

**Comment by mxschmitt** [comment]
Was able to repro it with:

```ts
test('repro', async ({ page }) => {
    await page.goto("https://demorgen.be/?adops=target_formats&ast_test=true", {
      waitUntil: 'networkidle'
    });
    await page.reload();
});
```

**Comment by BartVanRaemdonck** [comment]
I still have that bug without the `waitUntil:'networkidle'`

Like this:

```
test('repro', async ({ page }) => {
  await page.goto("http://demorgen.be");
  await page.reload();
});
```
