### ISSUE TITLE
[BUG] API calls in Firefox are way slower than Chromium

### ISSUE THREAD

**Issue by JDansercoer** [microsoft/playwright#16141]
**Context:**
- Playwright Version: 1.24.2
- Browser: Firefox

## System:
 - OS: Windows 10 10.0.19043
 - Memory: 4.75 GB / 15.95 GB
## Binaries:
 - Node: 16.13.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.18 - C:\Program Files\nodejs\yarn.CMD
 - npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD

**Describe the bug**

When running tests in Firefox, the API calls that set up the page are way slower during tests in Firefox than in Chromium. I'm needing to increase the `expect.timeout` to over `10000` to ensure the tests aren't flaky.
In Chromium they all pass with the default timeout.

I've tried my own browsers as well and I don't see any difference in Edge and Firefox when it comes to speed.

Any idea what may cause this?

**Comment by mxschmitt** [comment]
It's known that Firefox is slower in general, but do you have a particular example / repro / API call which is slower compared to Chromium?

Are you running headless or headed? Do you have video or tracing enabled?

**Comment by mxschmitt** [comment]
Can you share a minimal repro with us? Then we can take a look as well and hopefully fix the bug in a short period of time!

**Comment by rwoll** [comment]
Closing as part of triage. If you have a repro, please re-file and reference this issue so we can check it out. Thanks!
