### ISSUE TITLE
[BUG] "Timeout exceeded when running fixture "context" teardown" when trace is enabled

### ISSUE THREAD

**Issue by la2126** [microsoft/playwright#16143]
**Context:**
- Playwright Version: 1.23.4 (though have seen the same through multiple previous versions)
- Operating System: Local: Windows 11 Enterprise Pipeline: Ubuntu 20.04.4 LTS
- Node.js version: 16.16.0
- Browser: Chromium (have also replicated in Firefox, not tried in others)

We are seeing an issue where, more often than not, a subset of our tests will fail with the message 

"Timeout of 60000ms exceeded while running fixture "context" teardown."

We have narrowed this down to being an issue with the trace. Locally, and when running the tests in a deployment pipeline, when the trace is set to off, then none of the tests fail with this timeout message.

When I watch the tests run headfully, I can see that the test completes successfully within a few seconds, the browser then hangs and takes several times longer than the test to close down. Looking at the test reports, I can also see that all of the test steps have completed successfully, yet the test has failed with the timeout message.

When I up the timeout to 120000, then tests start to pass, but given that the tests seem to be finished less than 20 seconds and then wait maybe 45 secs - 1 min again to tear down, it's clear that something is not quite right!

While the tests fail in the pipeline, and I also have this issue running locally, other members of the team do not have this issue, even when we are on the same branch.

**Comment by mxschmitt** [comment]
Is it possible to share a repro with us? Would help a ton to dig deeper into it, thanks!

**Comment by rwoll** [comment]
Closing as part of triage. If you have a repro, please re-file and reference this issue.

Thanks!

**Comment by moshikd** [comment]
@mxschmitt @rwoll  i encountered this issue with playwright v1.27- i opened this issue (i think it is related) - 
**https://github.com/microsoft/playwright/issues/18016**
