### ISSUE TITLE
[Question] Locator.locator(string) can we somehow get another locator text or pass it as param ?

### ISSUE THREAD

**Issue by RobertMarszewskiUnum** [microsoft/playwright#16149]
Hi there ! I'm using playwright for while and for each time i want to find element within element (child of parent / grand parent) I have to pass it as string (which is painfull when used multiple times) or produce a lot of locators (that include such case).
Can we somehow get text of locator ? Let say this case:
```
let mainLocator = page.locator(".someMagicClass");
let grandChildLocator = page.locator(".someMagicGrandChildClass") ;
``` 
solution for now is like:
```
let newLocator = page.locator(".someMagicClass .someMagicGrandChildClass")
or
mainLocator.locator(".someMagicGrandChildClass");
```
but I would like to execute it like:
```
mainLocator.locator(grandChildLocator.getLocatorText()) // which results as string ".someMagicGrandChildClass"
mainLocator.locator(grandChildLocator)
``` 
?

**Comment by mxschmitt** [comment]
You can pass Locators inside the `has` option, see here: https://playwright.dev/docs/locators#filtering-locators

Something like that:

```js
let mainLocator = page.locator(".someMagicClass");
let grandChildLocator = page.locator(".someMagicGrandChildClass") ;

const somethingNewLocator = mainLocator.filter({
  has: grandChildLocator,
});
```

Would that work for you?

**Comment by RobertMarszewskiUnum** [comment]
I came up with something like:
```
  await expect(dashboardPage.grid_first_added_image.filter({ has: dashboardPage.video_image_icon })).toBeVisible();
```
not best looking but yea it is working :) 
Thanks, I'm closing ticket
