### ISSUE TITLE
[Question] WebServer skip with CLI

### ISSUE THREAD

**Issue by unickq** [microsoft/playwright#16144]
Is there a way to skip launching the webServer even if it's set in the config?

Use case - I have two projects in pw.config:
1) Localhost - FE only
2) www - the same FE, but with BE connected

I want to run the same tests for 1 and 2 - that's why I need to run WebServer for 1 and don't need to do this for 2.

**Comment by mxschmitt** [comment]
you can e.g. do the following:

`process.env.FOO ? {... } : undefined`

which will add the webServer stuff only if the process env FOO is set. And the FOO env you can e.g. set manually or via cross-env inside the package.json.

would something like that work for you?

**Comment by unickq** [comment]
Yep, it totally will. It's the same way I made it with cross-env.

Just thinking about creating a flag to achieve it without any extra envs. But if it's not needed - let's close this ticket

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/7539
