### ISSUE TITLE
[Question] Is it possible to get the test's video and screenshot in local machine while executing test on remote machine?

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#16145]
I am running test on a remote machine.

- Runner used: `@playwright/test`
- Playwright version: `1.24.0`

The config file is as given below:
```js
const config = {
  testDir: 'tests',
  outputDir: 'my-report-artefacts',
  testMatch: '**/*.spec.js',
  timeout: 60000,
  headless: false,
  workers: 10,
  use: {
    viewport: null,
    screenshots: 'on',
    video: 'on',
    trace: 'on',
  },
  reporter: [ ['html', { outputFolder: 'my-report' }] ],
  projects: [
    {
      name: 'chrome:latest:MacOS Catalina@lambdatest',
      use: {
        viewport: { width: 1920, height: 1080 }
      }
    }
  ]
}

```

While I am executing the tests in my local machine, I am able to get the video, screenshots and trace of the test.
While executing on remote machine, I am getting only trace. The video I am getting is blank.
Is there any way to get the video and the screenshots?

**Comment by mxschmitt** [comment]
How do you connect to the remote server?

Sounds like you are interested in this: https://github.com/microsoft/playwright/issues/8379

**Comment by ankur-lt** [comment]
I am connecting to the remote server of LambdaTest using the `browserType.connect` function. You can refer to the sample test script here: https://github.com/LambdaTest/playwright-sample/blob/main/playwright-test-js/lambdatest-setup.js

**Comment by ankur-lt** [comment]
Checked https://github.com/microsoft/playwright/issues/8379, yeah, that feature will make it easier for users to connect to Playwright server's WSS URL, rather than modifying the test function.

With the current Playwright library, is it possible to get the video and screenshots?
I suppose because the runner is executing locally and not connected to the remote server, hence the video is coming out as blank!

**Comment by mxschmitt** [comment]
Yes, as of today it's expected that video/screenshot/tracing won't work, we'd have to implement the issue above. Please upvote https://github.com/microsoft/playwright/issues/8379, and then it will be added!

Closing as per above.

**Comment by ankur-lt** [comment]
@mxschmitt , can you reopen this issue or https://github.com/microsoft/playwright/issues/8379, as the issue regarding getting the test's video/screenshots is not resolved?
