### ISSUE TITLE
How to add my core.ts file some characteristic like skip,only and test notes,test id ?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16150]
In my core.ts file I want to add some characteristic things. For example test notes,id etc. I created a core.ts file and managing spec files there. By the way, my code is running when I run below code in my core.ts file.But below code only works run() properties;
 
```
import { test} from '@playwright/test';

const Core = {
  create(name: string, config: any) {
    return (() => {
      test(`${name} API Testing`, async () => {
        await Promise.all(Object.keys(config.API).map(t => {
          let test = config.API[t]
          return test.run();
        }));
      });
    })();
  },
};
  
  export default Core;
```
I edit this core.ts file (You can see the final version of the core.ts file which includes characteristics at the end of the question .I edited above code for adding characteristics  )

If I want to add  some characteristic  to my core.ts file(you can see at the end of question) like skip,only and test notes,test id etc. I m taking below error;

```
   Error: It looks like you are calling test.skip() inside the test and pass a callback.
    Pass a condition instead and optional description instead:
    test('my test', async ({ page, isMobile }) => {
      test.skip(isMobile, 'This test is not applicable on mobile');
    });
```

My main problem is here;
-> I defined a test variable(testRun) and set that variable to config.API[t]
-> When I want to call the test function on the core.ts like `return (test.id || 0, test.only(testDesc, async () => {`, I get the above error 

How can add skip,only,notes,id etc. to my core.ts file? How can I edit my core.ts? Could you give me an example?**If I add skip:true parameter in my Identity.ts file that test should be skipped,if I add only:true parameter that test should only run. I want to use these characteristic** in Identity.api.ts(I added, you can see in my Identity.ts.    For example  `skip:true, notes:"test description"`) 

**I wrote all files below**
          

This is my package.json;

```
{
  "name": "e2e_tests",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "start": "npx playwright test Identity.spec.ts"
  },
  "author": "Crowdsol",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.23.1",
    "@types/jsonwebtoken": "^8.5.8",
    "axios": "^0.27.2",
    "ts-node": "^10.8.2",
    "typescript": "^4.7.4"
  },
  "dependencies": {
    "@openapitools/openapi-generator-cli": "^1.0.8-4.2.2",
    "@types/axios": "^0.14.0",
    "jsonwebtoken": "^8.5.1"
  }
}
```

this is my Identity.spec.ts file;

```
import Core from "../../../../core";
import { Identity } from "./identity.api";

Core.create("Identity", Identity);
```

This is my Identity.api.ts file ;

```import axios from "axios";

export const Identity = {
States:{
token:{} as any
},
API: {
Token: {
skip:true,
notes:"test description"
run: async () => {
data:{
userName:"yusuf",
password:"öztürk"
}
const response = await axios({
method: "POST",
url: "test",
data: data,
headers: {
"Content-Type": "multipart/form-data",
},
});
Identity.States.token = response.data.access_token;
console.log("data", Identity.States.token);
},
},
},
};
```
this my core.ts file

```
import { test} from '@playwright/test';

const Core = {
  create(name: string, config: any) {
    return (() => {
      test(`${name} API Testing`, async () => {
        await Promise.all(Object.keys(config.API).map(t => {
          let testRun = config.API[t]
          let testDesc = `${name} - ${t} - ${testRun.id} -  ${testRun.notes}`
          let skip = testRun.skip;
          let only = testRun.only;
          if (skip) {
            return (testRun.id || 0, test.skip(testDesc , async () => {
               testRun.run();
            }));
          }
          if (only) {
            return (testDesc.id || 0, test.only(testDesc, async () => {
               testRun.run();
            }));
          }
          return (testRun .id || 0, test(testDesc, async () => {
             testRun.run();
          }));
        }));
      });
    })();
  },
};
  
  export default Core;
```

**Comment by mxschmitt** [comment]
Generating tests is not supported, we have this feature request for it: https://github.com/microsoft/playwright/issues/12857

Seems like library would be a better fit for your use-case? https://playwright.dev/docs/library

Could you describe on a high-level what your goal is?
