### ISSUE TITLE
[Question] What does "Action was interrupted" mean?

### ISSUE THREAD

**Issue by wingardl** [microsoft/playwright#16156]
When calling `locator.isEnabled()` I'm getting a timeout. In the trace I see "Action was interrupted" - what does that mean? How can I tell what the action was interrupted by? 

Code sample: 
```
let editBtn = await page.locator('[data-unique-id="EditOnWeb"]');
console.log(editBtn);
let enabled = await editBtn.isEnabled(); //timeout here
```
![image](https://user-images.githubusercontent.com/44914634/182432266-2a03fc77-2bc6-4bde-8bea-c48c8830ccd5.png)

**Comment by mxschmitt** [comment]
Usually it means that the test was timing out, no after snapshot of the action was recorded and then action was interrupted was getting shown.

Do you get it all the time?

Could you share a repro with us?

**Comment by wingardl** [comment]
Yes this was happening consistently. Here's The code to repro:
```Typescript
//the config probably isn't relevant but including it just in case
  const config = {
    browserContextOptions: {
      recordHar: {
        path: "mockServerWithTestDoc.har",
      },
    },
  }
  const context = await browser.newContext(config.browserContextOptions);
  const page = await context.newPage();
  await page.goto(
    "https://1drv.ms/w/s!Ar1Yd2q8DWm3gdsINklmtNddVV3w2g?e=Ryjvue"
  );
// timeout to make sure page loads fully
  await page.waitForTimeout(1000);
  //click edit mode
  let editBtn = await page.locator('[data-unique-id="EditOnWeb"]');
  console.log(editBtn);
  let enabled = await editBtn.isEnabled(); // timeout here
  console.log("is edtibtn clickable?" + enabled); // this never prints
  await page.locator('[data-unique-id="EditOnWeb"]').click();
```

**Comment by mxschmitt** [comment]
Thanks, the reason why it was not working was since the element was inside an iframe. Something like that works:

```js
  // click edit mode
  const editBtn = page.frameLocator('#WacFrame_Word_0').locator('[data-unique-id="EditOnWeb"]');
  console.log(editBtn);
  const enabled = await editBtn.isEnabled(); // timeout here
  console.log('is edtibtn clickable?' + enabled); // this never prints
  await editBtn.click();
```

You can set the `DEBUG=pw:api` env var the next time to understand what Playwright is doing internally. See here for the debug guide: https://playwright.dev/docs/debug

See also here about frame locators: https://playwright.dev/docs/api/class-framelocator
