### ISSUE TITLE
Using selectors for multiple tables in a Word document

### ISSUE THREAD

**Issue by ontzic** [microsoft/playwright#16174]
We have been trying unsuccessfully to use locators to select and handle individual tables in a Word Online document. See in the [attached file](https://github.com/microsoft/playwright/files/9245479/2Tables.txt), the corresponding DOM elements of the 2 tables extracted from the document, that we are trying to use. 
The goal in this example would be to get the collection of 2 tables using locators and perform actions on each of them individually (select, change styles, etc.). The IDs present in the file cannot be used, as they are generated at runtime. 
 
What we have tried so far:
•	let tables = await frame.locator("table");
Returns more than 2 elements, because tables are used in various other places in the document, such as formatting the Ribbon.
 
•	tables = await frame.locator('[data-unique-id="Table"]');
Returns only one element which is the first table, but not the second table.
  
•	tables = await frame.locator('[data-tablestyle="MsoTableGrid"]');
Correctly returns 2 elements, but they are not accessible through actions such as click().
 
•	tables = await frame.locator('[class="TableContainerV2"]');
Returns zero elements.
 
•	tables = await frame.locator("table")
    .filter({has: frame.locator('[data-tablestyle="MsoTableGrid"]')});
Returns zero elements. (We tried other variations of filters on locators)
 
Can you please help us with the best practices in this case, for using locators to select each table individually? 
In our example, with what we tried, we either couldn't get the collection of tables correctly or we couldn't access the second table.
We haven’t tried yet, but we assume this is a more generic issue than just the tables, probably happening with other controls as well in a Word Web document.

Thanks!

**Comment by mxschmitt** [comment]
> Correctly returns 2 elements, but they are not accessible through actions such as click().

what do you mean with that?

Have you tried [codegen](https://playwright.dev/docs/getting-started-vscode#generating-tests-with-codegen) to find selectors?

**Comment by ontzic** [comment]
> what do you mean with that?
As example, tables.last().click() did not work, for instance.

> Have you tried [codegen](https://playwright.dev/docs/getting-started-vscode#generating-tests-with-codegen) to find selectors?
I did (didn't work). I will get back to you with the exact code and results for this case.

**Comment by mxschmitt** [comment]
> As example, tables.last().click() did not work, for instance.

what means "did not work"? Can you provide a repro for us? A 3k loc HTML is not enough.

Usually we recommend the [selectors doc](https://playwright.dev/docs/selectors) or especially the selectors [best practises section](https://playwright.dev/docs/selectors#best-practices) to get started with it.

**Comment by ontzic** [comment]
The 3k file attached only contains the definition of those tables, extracted from a significant larger word online file, for easier repro. If it helps, I could provide the original Word file.

**Comment by mxschmitt** [comment]
Having a link to that or similar file would be useful, so we understand which tables you mean etc.

**Comment by pavelfeldman** [comment]
I don't think we have a good idea on what you are trying to do. Playwright is a general purpose tool that works in terms of DOM, not Word. Locators are used to locate the dom elements and perform operations on them. Understanding what you are trying to do would help us help you.

**Comment by rwoll** [comment]
Closing as part of triage per-above. Please re-file and include a link to the site under test (or a Trace of an attempt at a test https://playwright.dev/docs/trace-viewer#recording-a-trace) and describe what you'd like to test at a high-level/description (e.g. "should be able to click the cell in the 2nd column, 4th row and change its color from green to purple").

Thanks!
