### ISSUE TITLE
[BUG] Playwright should (but doesn't) check the ID_LIKE field in /etc/os-release

### ISSUE THREAD

**Issue by rmunn** [microsoft/playwright#16186]
In [linuxUtils.ts](https://github.com/microsoft/playwright/blob/82fb68fdde9a234e4f46ca6e349a77da9c5aec0c/packages/playwright-core/src/utils/linuxUtils.ts#L55), Playwright reads the `ID=` and `VERSION_ID=` fields of `/etc/os-release`. This is then used in [hostPlatform.ts](https://github.com/microsoft/playwright/blob/82fb68fdde9a234e4f46ca6e349a77da9c5aec0c/packages/playwright-core/src/utils/hostPlatform.ts#L55) to determine whether the Linux distribution is Ubuntu, Debian, or something else.

However, the `os-release` manual lists other fields that would be useful to Playwright, such as [the `ID_LIKE` field](https://www.freedesktop.org/software/systemd/man/os-release.html#ID_LIKE=). This would help in detecting variants based on Ubuntu, such as Linux Mint, which are currently not being detected.  The manual has [the following to say](https://www.freedesktop.org/software/systemd/man/os-release.html#Notes) about detecting distributions:

> If you are using this file to determine the OS or a specific version of it, use the `ID` and `VERSION_ID` fields, possibly with `ID_LIKE` as fallback for `ID`. When looking for an OS identification string for presentation to the user use the `PRETTY_NAME` field.

Linux Mint is, for all practical purposes, Ubuntu with a different set of UI packages installed (Cinnamon or MATE as the desktop environment instead of Ubuntu's Unity, for example). Every core package in Mint should be the same as Ubuntu.

**Context:**
- Playwright Version: 1.24.2
- Operating System: Linux 5.15 Linux Mint 21 (Vanessa)
- Node.js version: 16.16.0
- Browser: All
- Extra: VirtualBox VM

**Additional information**

The `os-release` file for Linux Mint 21 looks like this:

```plaintext
NAME="Linux Mint"
VERSION="21 (Vanessa)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21"
VERSION_ID="21"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vanessa
UBUNTU_CODENAME=jammy
```

As you can see, the `VERSION_ID` found in the file is the version of Mint, not the version of Ubuntu that this Mint version was based on. The Ubuntu version can be obtained by checking the `UBUNTU_CODENAME` field, and looking up that codename in a table that will tell you that `jammy` is the codename for Ubuntu 22.04. The `UBUNTU_CODENAME` field is not one of the standard fields documented in the `os-release` manpage, so it might be absent in other distros, but it has been present in Linux Mint for years and can probably be counted on to continue to exist in the future.

https://github.com/microsoft/playwright/pull/15596#discussion_r919930023 contains a discussion of `/etc/upstream-release/lsb-release` which appears in Mint versions installed from a CD image (such as my virtual machine), but does not appear in Docker images (even the official `linuxmintd/mint21-amd64` image). So it's not possible to count on `/etc/upstream-release/lsb-release` appearing, and it's probably necessary to parse the `ID_LIKE` and `UBUNTU_CODENAME` fields of `/etc/os-release` instead.

To test that Mint can be treated as equivalent to Ubuntu 22.04, I edited the `/etc/os-release` file on my Mint virtual machine to say `ID=ubuntu` and `VERSION_ID=22.04`. I then ran `npx playwright install` and Playwright installed the Ubuntu browser builds. Chromium and Firefox ran just fine, while WebKit failed with the [same problem as on Ubuntu 22.04 mentioned in this comment](https://github.com/microsoft/playwright/issues/13738#issuecomment-1124572863), related to missing dependencies (e.g. `libicu66` while Ubuntu 22.04 includes `libicu70`; I verified that Linux Mint 21 also includes `libicu70`). So while I don't know why Playwright 1.24.2 was downloading a version of Webkit that didn't include the correct libicu version, I consider this a successful test of Mint acting the same as Ubuntu 22.04 w/r/t dependencies. 

Finally, a word on why it would be good for Playwright to correctly detect Mint and treat it as similar to Ubuntu. According to the rankings on https://distrowatch.com/ (accessed 2022-08-03), Linux Mint was in third place in popularity, behind MX Linux (Debian-based) and EndeavourOS (Arch-based). Ubuntu was in sixth place. So it's probably worth it to add some logic to `hostPlatform.ts` to properly detect Linux Mint, and treat it as an Ubuntu distro, since it's apparently *more* likely for Playwright to be running on Mint than on Ubuntu. (Except for CI platforms, where it will probably be running on an Ubuntu container image).

**Comment by mxschmitt** [comment]
Since Linux Mint is not officially supported, I'll mark it as a feature request for now. But we are happy to accept contributions!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by fauzil-azim** [comment]
I encountered a similar issue on Linux Mint Debian Edition Faye (based on Debian 12). I noticed that the original issue has already been resolved for Ubuntu-based Linux Mint in the [hostPlatform.ts](https://github.com/microsoft/playwright/blob/v1.44.1/packages/playwright-core/src/utils/hostPlatform.ts) file. However, the resolution for Debian-based Linux Mint still falls back to using Ubuntu, requiring additional libraries to make it work (which it would not be necessary if Playwright recognized that the OS is based on Debian 12.). Can you considered adding a parameter that allows overriding the hostPlatform constant during command execution? Or adding a parameter that specifies the path of the /etc/os-release file to be read from (potentially executing it using a custom /etc/os-release-deb file)?

Note: 
I don't have enough knowledge of the consequences of using a custom /etc/os-release file with different values than the original file. This is simply a curious question from my end.
