### ISSUE TITLE
[BUG] Playwright with Yarn and type: module causes ENOTDIR

### ISSUE THREAD

**Issue by DavidArchibald** [microsoft/playwright#16185]
**Context:**
- Playwright Version: Version 1.24.2
- Operating System: Linux
- Node.js version: v18.3.0
- Browser: Not Applicable (any)

**Reproduction**
Create project with:
```
yarn set version stable
yarn create playwright
```
At this point, running `yarn run playwright test` will succeed!

However, adding `"type": "module"` in the `package.json` will cause things to break with this error:
```
node:fs:1587
  handleErrorFromBinding(ctx);
  ^

Error: ENOTDIR: not a directory, stat `[path]/.yarn/cache/@playwright-test-npm-1.24.2-efa86d5947-3d24ae5957.zip/node_modules/@playwright/test/lib/experimentalLoader.js'
    at statSync (node:fs:1587:3)
    at tryStatSync (node:internal/modules/esm/resolve:165:13)
    at finalizeResolution (node:internal/modules/esm/resolve:398:17)
    at moduleResolve (node:internal/modules/esm/resolve:966:10)
    at defaultResolve (node:internal/modules/esm/resolve:1174:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:605:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:318:18)
    at ESMLoader.import (node:internal/modules/esm/loader:404:22)
    at initializeLoader (node:internal/process/esm_loader:71:49)
    at loadESM (node:internal/process/esm_loader:84:11) {
  errno: -20,
  syscall: 'stat',
  code: 'ENOTDIR',
  path: '[path]/.yarn/cache/@playwright-test-npm-1.24.2-efa86d5947-3d24ae5957.zip/node_modules/@playwright/test/lib/experimentalLoader.js'
}

Node.js v18.3.0
```

I seemingly have to add `"type": "module"` in order to run an unrelated package written using ESModules but it seems like the `experimentalLoader` is causing issues. I poked into the source to figure out what's going on and it seems to be happening in `cli.js` when `NODE_OPTIONS` is being set. I tried fixing it by setting `PW_DISABLE_TS_ESM` and `PW_TS_ESM_ON` but this simply made `.ts` files unusable as one might expect.

My guess is that the `--experimental-loader` flag doesn't play nice with the `.pnp.cjs` loader that recognizes how to deal with [Plug'n'Play](https://yarnpkg.com/features/pnp).

**Comment by jgerigmeyer** [comment]
I'm encountering this as well, using Yarn v3.2.3 and Playwright v1.26.1.

**Comment by gaoDean** [comment]
I'm also encountering this with Yarn 3.2.4 and Playwright 1.27.0

**Comment by johngeorgewright** [comment]
Problem also exists with Yarn 3.5.0 and Playright 1.31.2 on macos

**Comment by devunt** [comment]
Can be workarounded by running `yarn unplug @playwright/test`. Confirmed with Yarn 3.5.0 and Playwright 1.31.2, on macOS and github actions runner.

**Comment by GoglichidzeMike** [comment]
Still experiencing this issue.
`"@playwright/test": "^1.37.1`
`yarn v3.4.1`

**Comment by AlienLifeForm-UMA** [comment]
I am experiencing the same issue when using @playwright/experimental-ct-react with pnp and vite. 

```ENOTDIR: not a directory, stat '/home/git/pw-pnp-ts/.yarn/cache/playwright-npm-1.39.0-0e46dd748d-96d8ca5aa2.zip/node_modules/playwright/lib/transform/esmLoader.js
```
 
 The correct zip file is in the folder. Unplug did not work (and I have only installed the experimental component module), and TS displays no issues and builds the project as intended. For some reason, I have gotten the normal Playwright tests to work without issues in another projects but the component tests go nowhere.
 
 ```yarn: 3.6.4,
 @playwright/experimental-ct-react": "^1.39.0",
 "typescript": "^5.2.2",
  "vite": "^4.4.5"
  ```
  
  In another, similar project, I instead get this error when running component testing:
  
  ```
  Error: /home/git/settings-page/src/components/ActiveDirectorySettings.spec.tsx: Couldn't find a Program

   at ../.pnp.cjs:22803

  22801 |       }
  22802 |     }
> 22803 |     originalExtensionJSFunction.call(this, module, filename);
        |                                 ^
  22804 |   };
  22805 |   const originalDlopen = process.dlopen;
  22806 |   process.dlopen = function(...args) {
  ```

**Comment by mxschmitt** [comment]
This should be fixed with Node.js 18+ and Playwright 1.41+. Please re-file if you still encounter issues.

**Comment by GRA0007** [comment]
Was still having this issue, but I noticed that it was caused by having different versions of `@playwright/test` and `@playwright/experimental-ct-react` installed, once I set them both to the same version (1.43.1), everything worked.

**Comment by zeptonaut** [comment]
I'm still running into this with `@playwright/test: 1.44.0`. We don't have `@playwright/experimental-ct-react` (or other Playwright-related deps) listed in our dependencies, and a cursory read-through of yarn.lock doesn't show multiple versions of Playwright in our yarn.lock file.

We do use yarn workspaces with pnp, but only have Playwright installed in the root workspace.

**Comment by davidcalhoun** [comment]
This was fixed for me by updating from `@playwright/test` `1.44.0` to `1.45.0`

**Comment by joeczucha** [comment]
Can confirm that we're still seeing this in `1.57.0` (yarn `4.12`) and it also does it regardless of whether I have `"type": "module",` set or not.

```
 ERROR  Error: ENOTDIR: not a directory, stat '/Users/joe/Projects/playwright_test/node_modules/nuxt-og-image/dist/runtime/mock/proxy-cjs.js/index.js'                                                                                                                                                                                                      nitro 14:55:01

undefined

 ERROR  ENOTDIR: not a directory, stat '/Users/joe/Projects/playwright_test/node_modules/nuxt-og-image/dist/runtime/mock/proxy-cjs.js/index.js'                                                                                                                                                                                                                   14:55:01

 ERROR  ENOTDIR: not a directory, stat '/Users/joe/Projects/playwright_test/node_modules/nuxt-og-image/dist/runtime/mock/proxy-cjs.js/index.js'
```

Unfortunately, we can't use `unplug` as, for various reasons, our `nodeLinker` is still set to `node-modules`
