### ISSUE TITLE
[Question] Why --browser cannot be used when projects are defined?

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#16181]
Projects are a very powerful way of creating a first level division across tests.
I have 3 examples of their usage :
1) https://playwright.dev/docs/api/class-testproject divides the project via browsers.
   The 'npm init playwright' also generates a configuration via browsers.
2) https://playwright.dev/docs/test-parameterize#parameterized-projects divides the project via people.
3) I use projects to distinguish between our deployment environments - { dev, qa, stage, preview, sandbox, prod }
Only (1) actually defines browsers in the projects, while (2) and (3) do not.
So, although my configuration is (3), when I try to run "npx playwright test --browser=xxx", I get the error :
   > Error: Cannot use --browser option when configuration file defines projects. Specify browserName in the projects instead.

Is this warning overkill or is there a reason to protect me?
Alternatively, why not let the user signal to Playwright Test (say a config parameter like ProjectDefinesBrowsers = true|false) whether he/she has browsers in projects,
so that scenarios such as (2) and (3) do not need to be blocked from using --browsers.
Thanks,

**Comment by mxschmitt** [comment]
The reason why we don't provide a browser in 2) is because we focus on what parameterized projects are. `--browser` essentially creates a new project with the given browserName from the CLI, so if you have projects already specified in your config, this makes not a lot of sense.

In your scenario I'd recommend to not have for every environment a dedicated project and have a browser as a project. The environment itself you then control via environment variables. Aka. npx cross-env TEST_ENV=staging npx playwright test.

What are the values which are different per environment? baseURL, some keys etc?

**Comment by khtan** [comment]
Thanks for your info. If --browser creates a new project, I agree, it will conflict with any existing project
regardless of the how the projects are segmented - by users, by deployments or by browsers.

As for my environment, the entire company has its build and support infrastructure segmented by deployment environments.
That is why it makes sense for me to create projects = qa, stage etc. The browsers supported are more incidental,
ie all environments will support the same set of browsers.

The deployment environments differ in 
1) types of access
2) capabilities of the machines
2) variety of baseurl and service urls, not all of which are rational, ie someone implemented the odd naming url
and we're all stuck with it
3) test companies/tenants/users are database dependent on each environment.
   This is abstracted with an abstraction layer so that the tests do not need to know what env they are, just
   what capabilities the environment and users have.

Technically, the functionality of "projects" can be mimiced/handled with env variables so "project" is a good
convenience.

**Comment by mxschmitt** [comment]
Sounds like you can use then an env var to control the browser/name and then it should be good!
