### ISSUE TITLE
[Question] Strange module resolution for relative package.json import

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#16187]
Hi there!

I have a test file 

```ts
// src/blocks/mobile-product-panel/__playwright__/btn.test.ts
import packageJSON from '../package.json'

console.log('packageJSON', packageJSON.name)
```

and I have files:

// src/blocks/mobile-product-panel/package.json
```json
{
  "name": "alice"
}
```

// package.json
```json
{
  "name": "root"
}
```

## tsconfig.baseUrl === './src'

```
npx playwright test src/blocks/mobile-product-panel/__playwright__/btn.test.ts
packageJSON root

npx ts-node src/blocks/mobile-product-panel/__playwright__/btn.test.ts
packageJSON alice
```

## No tsconfig.baseUrl

```
npx playwright test src/blocks/mobile-product-panel/__playwright__/btn.test.ts
packageJSON alice

npx ts-node src/blocks/mobile-product-panel/__playwright__/btn.test.ts
packageJSON alice
```

If I remove `.json` extension from import statement I got the same result with and without tsconfig.baseUrl

```
npx playwright test src/blocks/mobile-product-panel/__playwright__/btn.test.ts
packageJSON alice



npx ts-node src/blocks/mobile-product-panel/__playwright__/btn.test.ts
/Users/d.o.kuznetsov/Projects/boxy/node_modules/ts-node/src/index.ts:859
    return new TSError(diagnosticText, diagnosticCodes, diagnostics);
           ^
TSError: ⨯ Unable to compile TypeScript:
src/blocks/mobile-product-panel/__playwright__/btn.test.ts:6:25 - error TS2307: Cannot find module '../package' or its corresponding type declarations.

6 import packageJSON from '../package'
```

Do you have any special logic around importing json files?

@playwright-test: 1.24.1
typescript: 4.72.0
ts-node: 10.9

**Comment by rwoll** [comment]
> Do you have any special logic around importing json files?

`package.json` has special meaning and we use it in a [variety of places](https://github.com/microsoft/playwright/search?q=getPackageJsonPath&type=code) to infer config and resolution. I'm not certain that's what's happening here, but it's very likely.

Can you create a minimal repro in the form of a GitHub repo we can clone and run to see the error? Thanks!

**Comment by rwoll** [comment]
Closing as part of triage per-above. Please file a new issue with the information requested above, and reference this issue.

A repro will help ensure we are actually debugging the same issue you are facing and will minimize us guessing. This is especially helpful when there are several layers/pieces involved.

Ideally the repro is a GitHub repository we can clone, download, and run to see the issue ourselves. It should include the commands to run it, too.

Thanks!
