### ISSUE TITLE
[Question] - While running any API function, the Playwright tool is throwing error as: apiRequestContext.get: certificate has expired.

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#16194]
While running any API function, the Playwright tool is throwing error as: **apiRequestContext.get: certificate has expired.**

<img width="512" alt="2022-08-03 15_16_32-API Certificate error png ‎- Photos" src="https://user-images.githubusercontent.com/103040866/182578713-0131f5fa-6c14-4ee1-9df6-714a85a6e42d.png">

Please let me know if anyone knows how to resolve this.
Thanks...

**Comment by mxschmitt** [comment]
Depends how you create / consume the apiRequestContext.

You can set `ignoreHTTPSErrors: true` under the. "use section" inside the config or add `ignoreHTTPSErrors : true`  when creating the context/api context.

**Comment by AkkyLohana90** [comment]
Hello,
I already tried this( **ignoreHTTPSErrors: true**)  inside the config. Still getting the above issue.

**Comment by mxschmitt** [comment]
Could you share your config and how you make the request?

**Comment by AkkyLohana90** [comment]
Thanks **mxschmitt**,
The second approach is working.
Closing the Que.

**Comment by Niemetz** [comment]
> Thanks **mxschmitt**, The second approach is working. Closing the Que.

Would you please lost the sample code on the "second approach"?  I'd like to see how you specify the ignoreHTTPSErrors: true as a parameter... I'm new to typescript/javascript.  Thanks

**Comment by vromants** [comment]
@Niemetz 
const requestContext = await request.newContext({ baseURL, ignoreHTTPSErrors: true });

**Comment by Niemetz** [comment]
> @Niemetz const requestContext = await request.newContext({ baseURL, ignoreHTTPSErrors: true });

Thanks a lot.  Will try.
