### ISSUE TITLE
[Question] Feature parity between supported languages?

### ISSUE THREAD

**Issue by shack05** [microsoft/playwright#16191]
Hello,

I've been reading through playwright.dev but could not find answers to the following questions. Apologies if this is not the appropriate forum.
1. Is the intention to support the same features across each supported language?
2. If not, is some sort of matrix/documentation describing current/planned support for various features between support languages?

I'd like to use playwright in a new project and keen on the visual comparison feature, but it doesn't seem to be supported in Playwright for .NET.

**Comment by mxschmitt** [comment]
> Is the intention to support the same features across each supported language?

Yes, it is. Library-wise all the language already have a parity. test-runner / integration wise we are working on it, especially on the .NET side, see here: https://github.com/microsoft/playwright-dotnet/issues?q=is%3Aissue+is%3Aopen+label%3Ainner-loop

Matrix support, if you mean like sharding, this is usually something which gets done on the test-runner level.

See also here for visual regression testing feature request: https://github.com/microsoft/playwright-dotnet/issues/1854

**Comment by shack05** [comment]
Thank you, that completely answers my question.
I'm happy for this issue to be closed.
