### ISSUE TITLE
[BUG] page.route() doesn't seem to work on Safari

### ISSUE THREAD

**Issue by Camo30** [microsoft/playwright#16190]
**Context:**
- Playwright Version: 1.24.2
- Operating System: Windows
- Node.js version: 16.15.0
- Browser: WebKit
- Extra: 

**Code Snippet**

```typescript
import { expect, test } from '@playwright/test';

test('should work', async ({ page }) => {
    page.route("https://developer.mozilla.org/api/v1/whoami", route => {
        route.fulfill({ body: JSON.stringify({ username: "Playwright", email: "test@playwright.dev" }) });
    });

    page.goto("https://developer.mozilla.org/de/docs/Web/HTML/Element/dialog");

    await expect(page.locator("h1")).toContainText("<dialog>");
});
```

**Describe the bug**

Execute the above code. As you can see below the route is not fulfilled on Safari. Chrome and Firefox works.

Chrome:
![grafik](https://user-images.githubusercontent.com/33700436/182559044-0a83f7e6-7ab5-4cf5-a2c1-26f5186ae55a.png)

Safari:
![grafik](https://user-images.githubusercontent.com/33700436/182560163-f7c1dea5-8800-47e3-837a-1ef56cc2d344.png)

**Comment by mxschmitt** [comment]
The reason is most likely, that WebKit DevTools are disconnecting the main Playwright connection, thats why the requests don't get intercepted again. If you test it without the devtools, in e.g. this way:

```js
test('should work', async ({ page }) => {
  await page.route('https://developer.mozilla.org/api/v1/whoami', route => {
    return route.fulfill({ body: JSON.stringify({ username: 'Playwright', email: 'test@playwright.dev' }) });
  });

  await page.goto('https://developer.mozilla.org/de/docs/Web/HTML/Element/dialog');
  await page.evaluate(() => {
    fetch(' https://developer.mozilla.org/api/v1/whoami').then(response => response.json()).then(data => {
      document.write(`<p>${data.username}</p>`);
    });
  });
  await page.waitForSelector('p:has-text("Playwright")');
  await page.screenshot({ path: 'foo.png' });
});
```

then it works as expected. We don't have it explained somewhere afaik, so I filed https://github.com/microsoft/playwright/issues/16192 for now.

**Comment by mxschmitt** [comment]
Dupe of https://github.com/microsoft/playwright/issues/17480
