### ISSUE TITLE
[BUG] Playwright Test and JavaScript options for codegen can be consusing

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#16201]
**Context:**
- Playwright Version: latest
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

````
npx playwright codegen
````

**Describe the bug**

Target says Playwright Test but also gives options for JavaScript. Then in docs we show codeblocks for JavaScript or Typescript or Library. This makes things confusing as should we be using JavaScript as in the code snippets from docs or Playwright Test and then when would someone use JavaScript and why is there no TypeScript.

Would be good to make this clearer.

<img width="466" alt="image" src="https://user-images.githubusercontent.com/13063165/182607823-bc76b07f-80d4-4a9d-a602-8a6132098dee.png">

**Comment by mxschmitt** [comment]
- Java
  - Library (default)
- .NET
  - MSTest 
  - NUnit (default)
  - Library
- Node.js
  - JavaScript (test-runner)
  - TypeScript (test-runner) (default)
  - Library 
- Python
  - Library (async)
  - Library (sync)
  - Pytest (default)
