### ISSUE TITLE
[BUG] Step definition cache

### ISSUE THREAD

**Issue by Krzysztof1985** [microsoft/playwright#16203]
**Context:**
- Playwright Version: ^1.18.1
- Operating System: Mac
- Node.js version: v16.13.1
- Browser: Chromium, Firefox

**Describe the bug**
Hello,

I noticed that playwright has some big big issue with step_definition cache.
I am running 1 scenario where this scenario around 3-4 hours ago was failing due to some assertion error.
The assertion is gone, code pass through but the scenario is still failing due to this assertion.

When I run exact the same step, but I enforce to stop at some point in IntelliJ entire scenario passed.
This brings me a big big unpredictability to my suite.

I am att
<img width="1787" alt="image (11)" src="https://user-images.githubusercontent.com/2550886/182614412-8f0cb528-5fba-41b7-baf6-bb2bdc8ee243.png">
aching the screenshots:
<img width="1787" alt="image (10)" src="https://user-images.githubusercontent.com/2550886/182614061-2bf6a4b5-d254-42a7-bf6d-4b2da856f37d.png">

I tried to invalidate the IDE cache, rebuild the project, deleted old libraries for playwright from macOs and download fresh ones.
Nothing helps. 

Do you have any idea how to fix this?

Regards
Krzysztof

**Comment by mxschmitt** [comment]
Playwright has no steps internally, so most likely something is fishy with your cucumber stuff.

We unfortunately can't act on that, I recommend to try to reduce the scope or migrating to our official test runner: https://playwright.dev/docs/intro
