### ISSUE TITLE
[Feature] Allow Fixtures to be used in global-setup

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#16215]
Currently, when trying to setup a `global-setup.ts`, it is not possible to use any of the Fixtures from Playwright or the custom Fixtures the user created.  
Instead, the pages and other variables have to be defined & instantiated from scratch there, which is not only redundant but also makes things more complicated.

So it would be a great improvement if the Fixtures could be utilized in `global-setup`.

**Comment by rwoll** [comment]
Folding into https://github.com/microsoft/playwright/issues/14895#issuecomment-1203272743
