### ISSUE TITLE
Browserslist Support

### ISSUE THREAD

**Issue by damvaz** [microsoft/playwright#16219]
# Support for browserlist

## Why?

Many existing projects use **browserlist** to define the browsers they support.

For example, in **package.json** , the following setting can be included:

```json
"browserslist": [
    "last 10 Chrome versions",
    "last 10 Firefox versions",
    "last 4 Edge versions",
    "last 7 Safari versions",
    "last 8 Android versions",
    "last 8 ChromeAndroid versions",
    "last 8 FirefoxAndroid versions",
    "last 10 iOS versions",
    "last 5 Opera versions"
  ]
```

In a sense, in the configuration of **playwright** those support requirements must be rewritten within the `projects` entry.

If there were support for **browserlist**, this "double" configuration would not be so necessary.

## Possible solution

Create a helper that returns the object for `projects`, based on the configuration of **browserlist**.

**Comment by mxschmitt** [comment]
Playwright's WebKit and Firefox version are strictly bound to the Playwright version. Only our Chromium browser is a bit more flexible in what version you can use, we test always on +1/-1 channel in advance.

So based on that I think it does not make sense to add such integration, or what do you think?
