### ISSUE TITLE
[internal] WebKit fails on Ubuntu 22.04 x86_64 in docker

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#16228]
Speculative commit: https://github.com/microsoft/playwright/commit/52aa869f123c8f48a3f95159e97dd741d4b1c722

But most likely the new build is just broken for webkit, so requires investigation. 

<img width="1496" alt="image" src="https://user-images.githubusercontent.com/746130/182717655-ec88412b-d886-489e-9eda-a2d12c632a40.png">

**Comment by aslushnikov** [comment]
Observation:
* WebKit **hangs** when launched inside ubuntu:22 container hosted on Ubuntu:20 machine; in this case, the container has to be launched in **privileged** mode. This works as expected though since it looks like Ubuntu:20 kernel doesn't support some fancy feature from Ubuntu:22 kernel, and this feature is used by WebKit.

**Comment by mxschmitt** [comment]
Fixed!
