### ISSUE TITLE
[Question] Why is the Playwright package missing from the Docker image

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#16222]
I am not sure what started this happening. I recently updated the version of Playwright I use but I can't say it is related. In the log files I see this warning when running my tests in the Playwright Docker image: "npm WARN exec The following package was not found and will be installed: playwright"

Any idea why it is missing now and needs installed every time?

**Comment by eatonjl** [comment]
I figured it out. Even though I am using the Playwright Docker image that has all the dependancies, I still need to include "npm ci" to install Playwright.

**Comment by RicardoRien** [comment]
@eatonjl Thanks a lot! That is the solution!
