### ISSUE TITLE
[BUG] Always timeout error from toHaveURL when its has already succeeded in Docker Playwright

### ISSUE THREAD

**Issue by pawlarius** [microsoft/playwright#16237]
**Context:**
- Playwright Version: @playwright/test ^1.23.1
- Operating System: Local is Mac, but the spec fail with Docker mcr.microsoft.com/playwright:v1.24.2-focal
- Node.js version: 16.13.1
- Browser: Chromium

**Code Snippet**

```javascript
// Calling API and redirects
await expect(page).toHaveURL(`/orders/${createOrderResponse?.order_detail?.id}?orderNature=incoming`);
```

**Describe the bug**

Spec ONLY failed when running Bitbucket Pipeline with official Playwright docker image `mcr.microsoft.com/playwright:v1.24.2-focal`. I can't repro this at local.

I tried adding debug mode and noticed the logs are both successfully navigated to the expected URL.

This is the successful logs when running from local:
```
  pw:api => expect.toHaveURL started +5ms
  pw:api expect.toHaveURL with timeout 5000ms +2ms
  pw:api waiting for selector ":root" +3ms
  pw:api   selector resolved to <html>…</html> +5ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   selector resolved to <html>…</html> +101ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   selector resolved to <html>…</html> +255ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   "networkidle" event fired +124ms
  pw:api   selector resolved to <html>…</html> +383ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +2ms
  pw:api   navigated to "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/orders/400?orderNature=incoming" +161ms
  pw:api   selector resolved to <html class=" ">…</html> +848ms
  pw:api <= expect.toHaveURL succeeded +14ms
  pw:api => browserContext.close started +8ms
  pw:api <= browserContext.close succeeded +16ms
  pw:api => browser.close started +13ms
  pw:api <= browser.close succeeded +22ms
```

This is logs from the same code but run by Bitbucket Pipeline with Playwright Docker image:
```
  pw:api => expect.toHaveURL started +4ms
  pw:api expect.toHaveURL with timeout 5000ms +1ms
  pw:api waiting for selector ":root" +1ms
  pw:api   selector resolved to <html>…</html> +8ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   selector resolved to <html>…</html> +100ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   selector resolved to <html>…</html> +250ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   "networkidle" event fired +133ms
  pw:api   selector resolved to <html>…</html> +367ms
  pw:api   unexpected value "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/" +1ms
  pw:api   navigated to "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/orders/399?orderNature=incoming" +230ms
  pw:api => browserContext.close started +301ms
  pw:api <= expect.toHaveURL succeeded +8ms
  pw:api <= browserContext.close succeeded +10ms
  pw:api => browser.close started +1ms
  pw:api <= browser.close succeeded +33ms
```
But at the end Playwright will return errors with timeout.
I have tried increasing the timeout duration but still failed.

<img width="984" alt="Screen Shot 2022-08-04 at 10 47 33" src="https://user-images.githubusercontent.com/27823957/182758921-4b6fcaf7-c891-43fb-a4d4-658dac26d101.png">

Not sure what more can I debug when the playwright API already said it succeeded but somehow still return as timeout error.
Any info/help is appreciated, thank you.

**Comment by pawlarius** [comment]
Seems like someone has reported the timeout issue only from Docker in the older version of Playwright: https://github.com/microsoft/playwright-dotnet/issues/1837

**Comment by mxschmitt** [comment]
Seems like your test timeout kicks in, which test timeout do you have configured inside your playwright.config.ts?

You can try increasing it, because toHaveURL says it has a timeout of 5s and a 10s timeout cancels the test.

See here an overview about timeouts: https://playwright.dev/docs/test-timeouts

**Comment by pawlarius** [comment]
Hi @mxschmitt I have tried increasing it manually with this script:
`
await expect(page).toHaveURL(`/orders/${createOrderResponse?.order_detail?.id}?orderNature=incoming`, { timeout: 10_000 });
`

But it still failed with timeout. I don't think this is timeout issue.
From the Playwright log it return this line before closing browser and returning timeout error:
`
  pw:api   navigated to "https://backoffice-runchise-git-fix-wbo-220-runchise-go.vercel.app/orders/399?orderNature=incoming" +230ms
`

Does this log line meant the Playwright has already succeed in navigating but somehow toHaveURL still returns error?

Btw the same script won't break in my local, this somehow only fail with Playwright docker image..

**Comment by mxschmitt** [comment]
I don’t mean the assertion timeout, I mean the test timeout. See here an overview about timeouts: https://playwright.dev/docs/test-timeouts

**Comment by pawlarius** [comment]
Hi @mxschmitt thankyou for that!
I tried increasing the test timeouts to 60 seconds and now all the test passed without any timeout error.

So I guess the issue is my local run the test faster than the bitbucket pipeline? 😅

**Comment by mxschmitt** [comment]
exactly! Happy to hear, closing by that.
