### ISSUE TITLE
Please add the .. (parent) locator to the docs

### ISSUE THREAD

**Issue by 304NotModified** [microsoft/playwright#16243]
> You know you can get to the parent by doing
> ```
> page.locator("#locator").locator("..").locator("div").nth(0)
> ```

_Originally posted by @sgreener in https://github.com/microsoft/playwright/issues/15234#issuecomment-1170212273_

**Comment by mxschmitt** [comment]
We'll continue in the PR.

**Comment by 304NotModified** [comment]
Off topic: I'm working with Github for years. And for some reason the playwright repos does use a bit strange and confusing process with handling issues. (No milestones, close issues that aren't fixed yet - and not using the auto close on merge feature, fully changing submitted issues)  I'm a bit confused!
