### ISSUE TITLE
[Feature] Increase default browser size

### ISSUE THREAD

**Issue by MattHorrocksNetwealth** [microsoft/playwright#16248]
The default size for the browser viewport to open is 1280x720.

This was last set in February 2020 (more than two years ago!) in https://github.com/microsoft/playwright/pull/1038/commits

Would there be scope to increase this to 1920x1080?

I'm happy to do a PR if there is agreement.

Based on statcounter data, 1920x1080 (top line) is the most common resolution, with 1280x720 beneath in the chart below

![image](https://user-images.githubusercontent.com/106080163/182833646-6c22f9cc-2d42-4f12-a4e2-5adf0eb88537.png)

**Comment by mxschmitt** [comment]
While this statistics is right, this would mean it's a breaking change for all of our customers.

We recommend for you to set the browser window size manually in Playwright configuration file.
