### ISSUE TITLE
[Question] Playwright auto intellisense not working in page object model. Do I need to import anything in my page class?

### ISSUE THREAD

**Issue by amit1791** [microsoft/playwright#16246]
Hi,

I was trying to implement page object model in my Playwright project (with JavaScript). So, I have created some new HomePage.js and LoginPage.js files in new page-objects folder
Below is the code for my HomePage.js
class HomePage{

    constructor(page){
        this.page = page;
        this.becomeMember  = page.locator('.gnav__subscribe');
    }
    async clickBecomeMember(){
        await this.becomeMember.waitfor();
        const text = await this.becomeMember.textContent();
        console.log(text);
        await this.becomeMember.click();
    }
}
module.exports = {HomePage};

Here I'm facing following issues.
1. When I'm pressing dot(.) after any locator. or page. then auto intellisense not working.
2. waitfor() and evaluate() methods are not working in page classes. Getting exception (this.becomeMember.waitfor is not a function)

Please let me know if I'm doing something wrong. Thank you!

**Comment by mxschmitt** [comment]
If you are using JavaScript, you need to add [JSDoc](https://jsdoc.app/) annotations to make autocompletion work. See [this](https://playwright.dev/docs/test-pom) example (the @param comment).

We usually recommend TypeScript because of that.

**Comment by amit1791** [comment]
Thanks alot. It worked for me. :)

**Comment by saiteja013526** [comment]
i have also tried the same but it is not working for me
