### ISSUE TITLE
[Question] testInfo.retry flag inside a fixture?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#16250]
Hi again)

Could we get the information about retry status inside test-scoped fixtures?

What I want to do: run all tests in just one single page (https://github.com/microsoft/playwright/issues/15948#issuecomment-1196020798). But, if test fails, I want to retry it in the new fresh browser context.

PS: We had some flaky issues with page in webkit, and test retry doesnt help, but job retry does.

**Comment by YusuffOzt** [comment]
@Diokuz how to add test.retry on your tests . I need the same thing with you. Could you show me an example?
