### ISSUE TITLE
[Feature] Support TypeScript declare fields, and/or consult tsconfig target or useDefineForClassFields

### ISSUE THREAD

**Issue by mweidner037** [microsoft/playwright#16257]
In some Playwright Test TypeScript code, I need to declare the TypeScript type of a class's field without defining the field in JS (due to [a library](https://sequelize.org/docs/v6/core-concepts/model-basics/#caveat-with-public-class-fields)). The [TypeScript docs](https://www.typescriptlang.org/docs/handbook/2/classes.html#type-only-field-declarations) describe a few ways to do this:
1. Change the tsconfig `target` to < `es2022`
2. Set the tsconfig `useDefineForClassFields` to `false`
3. Use `declare` on the class fields, e.g.,
```ts
class TestClass {
  public declare x: number;
}
```

However, I have not gotten any of these to work in Playwright Test ([MWE repo](https://github.com/mweidner037/playwright-test-mwe-declare)):
- tsconfig `target` and `useDefineForClassFields` are apparently not consulted by Playwright Test (they do work with ts-node).
- Running the code snippet above within Playwright Test fails with:
```
Error: /Users/matthew/repos/playwright-test-mwes/tests/declare_fields.test.ts: TypeScript 'declare' fields must first be transformed by @babel/plugin-transform-typescript.
If you have already enabled that plugin (or '@babel/preset-typescript'), make sure that it runs before any plugin related to additional class features:
 - @babel/plugin-proposal-class-properties
 - @babel/plugin-proposal-private-methods
 - @babel/plugin-proposal-decorators
  2 |
  3 | class TestClass {
> 4 |   public declare x: number;
    |   ^^^^^^^^^^^^^^^^^^^^^^^^^
  5 | }
  6 |
  7 | test('declare_fields', async ({ page }) => {
```
Note this is in a project with no Babel setup - it appears to reference playwright's internal Babel. Adding a `babel.config.json` with `@babel/plugin-transform-typescript` doesn't fix the error.

Playwright Test version: 1.24.2.

**Comment by mxschmitt** [comment]
Playwright does not respect the tsconfig target nor the babel config. For more advanced setups we recommend compiling the TypeScript tests manually see this guide: https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript

We can keep this feature request open, if enough customers request it, we can add it by default.

**Comment by jparr** [comment]
As another Sequelize user this would be really useful. Currently to seed the database I am shelling out to call an npm script in beforeEach which adds about 12 seconds to each test.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by grushetsky** [comment]
It would be great if the default configuration supported `declare` keyword.

It's quite a basic TypeScript feature and it doesn't seem to cost a lot of compilation time. I think it's reasonable to make it available by default. It's [turned on](https://github.com/microsoft/playwright/blob/main/babel.config.json) for Playwright's code base, by the way.

**Comment by grushetsky** [comment]
Plus, [`allowDeclareFields`](https://babeljs.io/docs/babel-preset-typescript#allowdeclarefields) will be turned on by default in Babel 8:

<img width="395" alt="Image" src="https://github.com/user-attachments/assets/bd02633f-14f4-44bf-8871-a59ee28a2f0b" />

**Comment by grushetsky** [comment]
One of concerns that we might have is the change in the behavior for transpilation of classes with uninitialized fields. These fields are kept in the transpiled code if `allowDeclareFields` option is enabled, while they are erased if the option is disabled.

It should also be noted that the behavior with `allowDeclareFields` enabled matches the ES standard ([more info](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#the-usedefineforclassfields-flag-and-the-declare-property-modifier) on the topic). And as I mentioned in the previous message this behavior is going to be the default in Babel 8.
