### ISSUE TITLE
[BUG] toBeFocused() matcher isn't piercing Shadow DOM

### ISSUE THREAD

**Issue by bellindj** [microsoft/playwright#16268]
**Context:**
- Playwright Version: [1.24.2]
- Operating System: [Mac]
- Node.js version: [16.13.2]
- Browser: [any]
- Extra: []

**Code Snippet**

Unfortunately I have a web component built with Svelte and it will be hard to include it all, but the gist is:

Web component named `<my-switch>` with a control inside of it `<input>`. The only element with focus is the `<input>` in this component, e.g:

```
<my-switch>
   shadowroot
      <input />
<my-switch>
```

```javascript
    await page.locator('my-switch  input').focus();
    await expect(page.locator('my-switch')).toBeFocused(); // passes but it isn't really focused
    await expect(page.locator('my-switch input')).toBeFocused(); // fails assertion but it is focused
```

When I run in headed mode and pause after focus() is run,
`document.activeElement` returns `my-switch` element.
`document.activeElement.shadowRoot.activeElement` returns `input` element.

This is because input is really what has focus, but the browser doesn't pierce the shadow DOM. 

**Describe the bug**

It appears Playwright is not piercing shadow DOM for this matcher and is returning the parent element within the browser's DOM that is focused. Playwright does a great job piercing shadow DOM for other functionality, I'd expect toBeFocused to also pierce shadow DOM to get the right focused element.

Call log:
```
      - expect.toBeFocused with timeout 5000ms
      - waiting for selector "input"
      -   selector resolved to <input type="checkbox" id="50260257-8885-4b84-b894-8d6b…/>
      -   unexpected value "false"
      -   selector resolved to <input type="checkbox" id="50260257-8885-4b84-b894-8d6b…/>
      -   unexpected value "false"
```

**Comment by rwoll** [comment]
Thanks for the report. I've opened a PR, but I need to review with the team to sort out expectations with the team. In some ways—depending on the perspective—I think both should report focused. However, it may be worth making the expectation explicit in our API instead of the implicit patch I made. Follow the PR for updates! Thanks!

**Comment by bellindj** [comment]
Wow thanks so much for addressing this @rwoll and for a super speedy turnaround!

**Comment by rwoll** [comment]
Glad we could help! And thank your for including your repro steps and some of your initial investigation! You almost made it too easy 😄 

The canary (installable via `npm i @playwright/test@next`) will likely [publish within the hour](https://github.com/microsoft/playwright/actions/runs/2821486462). 1.25 release is coming up too, so you'll be able to use the fix via official channels shortly!
