### ISSUE TITLE
How to run json config files from terminal

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16263]
I have two environment json file

The first one: development.json config file

```
  "env": {
    "url": "https://app-development.net"
  }
```

The second one: staging.json config file

```
  "env": {
    "url": "https://app-staging.net"
  }
```

My aim is in the project is like below;

->I want only change  url one place not in the project.So json config files is a good way for me
->I want to call json config url in the project
->The most important thing I want run on the terminal.For example; **npx playwright test identity.spec.ts --config="./staging.json"**

Is there any way for this?

**Comment by mxschmitt** [comment]
`CONFIG=staging.json npx playwright test identity.spec.ts`

You can pass it via env vars, and read it based on the env var.

`const config = require(process.env.CONFIG);`

does this work for you?

**Comment by YusufOzturk-Development** [comment]
@mxschmitt thanks for response . Good response for me . If I call the url in the config ,should I call like this?
```
const config = require(process.env.CONFIG);
let url =config.url
```

**Comment by mxschmitt** [comment]
You can sure.

**Comment by YusufOzturk-Development** [comment]
Thanks @mxschmitt
