### ISSUE TITLE
[Feature] Playwright Recorder

### ISSUE THREAD

**Issue by otisg** [microsoft/playwright#1626]
Similar to how there is a Puppeteer Recorder (https://github.com/checkly/puppeteer-recorder) it would be great if there was Playwright Recorder.  

Are there plans for building one?  This is definitely something others would benefit from, IMHO, as it makes Playwright adoption and use even easier.

**Comment by jperl** [comment]
@otisg We built one https://github.com/qawolf/qawolf. It's a node package instead of a chrome extension.

**Comment by otisg** [comment]
Awesome!  Do you, @jperl or somebody from Playwright team plan on building browser extension(s) for recording?

**Comment by jperl** [comment]
@otisg We have more power and flexibility with the node package than what can be done with a browser extension. 

You can edit a file while recording, use a repl, set up necessary dependencies with one command, set up CI with one command, and coming soon use a watch mode. I am curious as to why you prefer a browser extension?

**Comment by pavelfeldman** [comment]
@otisg we do plan to invest in Playwright authoring, but that would need to wait until the library is out and we have a test runner that fits it best. So far, we've been focusing on the library. Now that it is getting into a reasonable shape for 1.0, we started looking at the runner integration. Once both are there, we will invest into the authoring and debugging tools. Recorder is a great form of authoring, so if ecosystem does not have a great one in place by the time we have cycles, we will look into it!

Having said that, we believe in the open stack and interchangeable layers, so we welcome other parties to join us and build test runners and recorders for the world! @jperl's qawolf is a great example of this approach in action, we are happy to see it evolving and helping us shape the apis in a recorder-friendly manner.

**Comment by mikestaub** [comment]
This project is super interesting. You can record the session and 'replay' it into a debugger. https://github.com/RecordReplay/playwright-tests
