### ISSUE TITLE
Playwright Test Generator Custom HTML Attribute

### ISSUE THREAD

**Issue by maneeshjapa** [microsoft/playwright#16273]
Can playwright test generator be configured to look for specific HTML attribute as precedence and record it?

Example : If my web page has an input field with attribute myId like:  <input myId="MyProject.Data.Username" placeholder="Username"/>

Can I configure test generator to look for myId attribute and generate a step as:
await page.FillAsync("//*[@myId='MyProject.Data.Username']", "My Text");

**Comment by mxschmitt** [comment]
Sounds similar or a duplicate of https://github.com/microsoft/playwright/issues/9015.
