### ISSUE TITLE
[Question] How to avoid creating too many trace files?

### ISSUE THREAD

**Issue by AlexDaniel** [microsoft/playwright#16274]
When my test fails, I'm greeted with this wall of text:
```
    attachment #1: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace.zip

    ------------------------------------------------------------------------------------------------

    attachment #2: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-1.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-1.zip

    ------------------------------------------------------------------------------------------------

    attachment #3: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-2.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-2.zip

    ------------------------------------------------------------------------------------------------

    attachment #4: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-3.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-3.zip

    ------------------------------------------------------------------------------------------------

    attachment #5: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-4.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-4.zip

    ------------------------------------------------------------------------------------------------

    attachment #6: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-5.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-5.zip

    ------------------------------------------------------------------------------------------------

    attachment #7: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-6.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-6.zip

    ------------------------------------------------------------------------------------------------

    attachment #8: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-7.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-7.zip

    ------------------------------------------------------------------------------------------------

    attachment #9: trace (application/zip) ---------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-8.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-8.zip

    ------------------------------------------------------------------------------------------------

    attachment #10: trace (application/zip) --------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-9.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-9.zip

    ------------------------------------------------------------------------------------------------

    attachment #11: trace (application/zip) --------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-10.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-10.zip

    ------------------------------------------------------------------------------------------------

    attachment #12: trace (application/zip) --------------------------------------------------------
    test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-11.zip
    Usage:

        npx playwright show-trace test-results/backoffice-misc-Miscellaneous-Backoffice-stuff-da01b-nt-test-basics-chromium/trace-11.zip
```

The reason for that is that I need to make several API requests to prepare the data, and in some cases some additional API requests to test the results after user interaction in the browser, so I end up using `request.newContext(…)`. However, even though it is a single test, following/debugging the result becomes annoyingly hard because requests are spread over 12 trace files.

Yes, in some cases I'm using `request.newContext` unnecessarily and I can reuse an existing context, but looking at the available APIs that I use during tests, it seems that I will always have about 4 trace files (1 browser + 3 APIs).

Ideally, I just want 1 trace file for any test, with all of the requests. I was looking for a way to clone an existing `APIRequestContext` (while changing its baseURL in the clone), but I don't see any built-in way. What are my options?

**Comment by oscargforce** [comment]
Hello!
I faced the same issue with receiving
around 8-10 different trace files.

I was able to chunk it down to two only with this solution.

The first trace file will contain all the api requests that were made. The second trace file will contain the UI interaction.

As you mentioned the “request.newContext” is the issue in this case. What you need to do is to pass the same request through all of your functions. That will store all api calls in the same trace file.

This is how I did it.


Step 1. Remove all request.newContext calls in your functions.
Write directly await request.put/post..etc.
To make your IDE stop complaining, import and set the type of request according to the picture below.
![92FB11F5-EEA5-4EE8-B54B-A464D85D9095](https://user-images.githubusercontent.com/102926658/185802356-78311a13-5df4-40b1-a874-edb506450f0d.png)

Then

**Comment by AlexDaniel** [comment]
> The first trace file will contain all the api requests that were made. The second trace file will contain the UI interaction.

Yeah, I'm glad this works for you, but as I mentioned in the original post, I have multiple APIs that have different headers. Doing what you suggested will leave me with 4 trace files, at which point it doesn't really matter if it's 4 or 8, it's too many anyway.

**Comment by davidnuzik** [comment]
+1 to this. I don't need to see that I have 150 .zip files/traces in my console output. Each day when I review failures in CI I'm greeted with more than 1,000 lines of this and have to struggle to find what I'm looking for. I get that it's useful to some, perhaps even most, but it has zero value for me and my team.

I really wish we could actually just pass a flag or something to suppress such output or some other simple solution to completely remove this output. I ideally shouldn't have to re-write my code.

**Comment by ron-hiner-anttila** [comment]
@oscargforce I was having the same problem and your solution was exactly what I needed, thanks!

**Comment by wentwrong** [comment]
We ran into an issue where Playwright created an extra "trace.zip" file for each of our tests. It turned out that seemingly harmless destructuring of a `request` parameter leads to creation of a new context for which Playwright automatically captures a new trace.

For example, after execution of the following test file two traces will be created for each test (`trace.zip` and `trace-1.zip` files)
```js
// npx playwright test bug.spec.js --trace on
import { test as base, expect } from '@playwright/test';

const test = base.extend({
    showcase: async ({ request, page }, use) => {
        await use({});
    }
});

test('it has two traces', async ({ showcase }) => {
    expect(true).toEqual(false);
});

test('it has two traces too', async ({ showcase }) => {
    expect(true).toEqual(false);
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by AlexDaniel** [comment]
Uhh, this is still a problem as far as I'm concerned. Having 12 different trace files for one test is less than ideal. The workarounds are just that, workarounds, and they don't fully resolve the problem anyway.
