### ISSUE TITLE
WebKit startup hangs on v1.24.1-jammy Docker image in GitHub Actions [BUG]

### ISSUE THREAD

**Issue by jetwiwo** [microsoft/playwright#16279]
**Context:**
## System:
 - OS: Linux 5.15 Ubuntu 22.04 LTS 22.04 LTS (Jammy Jellyfish)
 - Memory: 5.85 GB / 6.78 GB
 - Container: Yes
## Binaries:
 - Node: 16.16.0 - /__t/node/16.16.0/x64/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.11.0 - /__t/node/16.16.0/x64/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
 - Extra: See https://github.com/jetwiwo/playwright-jammy-webkit-freeze/actions/runs/2800621772
 
This only seems to fail within GitHub Actions for me. If I run the same image in Docker Desktop  for Windows and execute the commands myself it works fine. Also seems to run properly in ACT `MSYS_NO_PATHCONV=1 act --env GITHUB_STEP_SUMMARY=/tmp/summary.md` on Windows.

**Code Snippet**

https://github.com/jetwiwo/playwright-jammy-webkit-freeze
```javascript
import { test } from "@playwright/test";

test.describe("This will freeze playwright in webkit", () => {
  test("Freezer", async ({ page }) => {});
});
```

**Describe the bug**

Playwright hangs when starting WebKit on Ubuntu Focal when running in the official Docker image

https://github.com/jetwiwo/playwright-jammy-webkit-freeze/actions/runs/2800621772 reproduces this issue using the official Docker image. It works fine in the focal image, but not in the jammy image.

Also note that when I reproduce this issue Playwright never times out on its own. If I did not add a timeout on the GitHub Action, it would keep running forever.

**Comment by jetwiwo** [comment]
May be related to https://github.com/microsoft/playwright/issues/15764

**Comment by mxschmitt** [comment]
Yup its related, we’ll dig into it. In the meantime if you use ubuntu 22 as a host it should work.

**Comment by mxschmitt** [comment]
Folding into it.

**Comment by jetwiwo** [comment]
https://github.com/jetwiwo/playwright-jammy-webkit-freeze/actions/runs/2801701850 confirmed that the ubuntu 22 host works fine 🍡
