### ISSUE TITLE
[BUG] Installation tests are broken

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#16281]
Must be fixed for 1.25.

**Comment by mxschmitt** [comment]
(Caused by the last NPM release)

**Comment by rwoll** [comment]
Confirmed locally test passes with older npm@8, but fails after upgrade to https://github.com/npm/cli/releases/tag/v8.16.0

**Comment by rwoll** [comment]
Upstream https://github.com/npm/cli/issues/5268

**Comment by rwoll** [comment]
> Must be fixed for 1.25.

For now, I will pin to last working version of `npm` for these tests. Running `npx playwright --help` outside of project works fine on latest version; it's only when you combine it with `npm_config_prefix` setting (which our tests do), that it seems to be broken (and I suspect most users do not have a custom config prefix.)
