### ISSUE TITLE
how to capture the bar graph tool tip text when we hover over it

### ISSUE THREAD

**Issue by vishwajeetgodge13** [microsoft/playwright#16296]
Hi,
I'm using Playwright with js
In my application, we provide the feature,  where user will get text while hover on bar graph. I want to capture the tool tip text to verify the text that showing when we hover over it.
i trying to capture but unable to do that. here i'm added code snippet of one website, so you can suggest me how i can do it & wrote small code to capture the text and verify that.. same way as l have in application

code snippet:

```js
const { expect, test, page } = require ("@playwright/test");

test('Validation of tool tip text',async({ page }) =>{
    await page.goto('https://demos.telerik.com/kendo-ui/bar-charts/index');
    await page.hover('(//div[@id="chart"]//*[name()="svg"]//*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][4]/*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][1]/*[name()="path"])[1]');
    const text = await page.innerText('//div[@class="k-tooltip-content"]');
    expect(text).toBe('Total Visits: 56000');
})
```

**Comment by mxschmitt** [comment]
You hover element does not fulfill all the actionability checks, see here: https://playwright.dev/docs/actionability

When setting `DEBUG=pw:api` or seeing the exception which gets thrown you'd see the following:

```
  pw:api retrying hover action, attempt #6 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   navigated to "about:blank" +132ms
  pw:api   waiting for element to be visible and stable +370ms
  pw:api   element is visible and stable +24ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +0ms
  pw:api   performing hover action +3ms
  pw:api   <path fill="#fff" stroke="none" fill-opacity="0" d="M3…></path> intercepts pointer events +20ms
```

To bypass the actionability checks, you can set `force: true` and then it works as expected:

```js
  await page.hover('(//div[@id="chart"]//*[name()="svg"]//*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][4]/*[name()="g"][1]/*[name()="g"][1]/*[name()="g"][1]/*[name()="path"])[1]', {
    force: true,
  });
```
