### ISSUE TITLE
[Question] How to record video in the screen's designated areas

### ISSUE THREAD

**Issue by buptzwl** [microsoft/playwright#16299]
sorry, please forgive my poor English.
```
const playwright = require('playwright');
const timer = require('timers/promises');

(async () => {
    const browser = await playwright.chromium.launch();
    const page = await browser.newPage({
        viewport: {
            width: 1920,
            height: 1080,
        },
        recordVideo: {
            dir: 'videos/',
            size: { width: 1920, height: 1080 },
        }
    });
    // backgroud transparent
    const client = await page.context().newCDPSession(page);
    await client.send('Emulation.setDefaultBackgroundColorOverride', {
        color: { r: 0, g: 0, b: 0, a: 0 }
    });
    await page.goto('http://www.baidu.com');
    await timer.setTimeout(20 * 1000)
    await browser.close();
})()

```

I just want to record the logo of  Google. as follows 
![google-logo](https://user-images.githubusercontent.com/12728397/183050962-814c30dc-b96b-48e0-93e7-51aaa29219e7.png)
I tried to set the configs such as viewport or recordVideo.size. But these are not working. The generated video is also the full screen.
![google-logo-fullscreen](https://user-images.githubusercontent.com/12728397/183052176-f812f030-d7ea-4521-8b20-d8f987b65bb2.png)
How could  I record video in the screen's designated areas?

**Comment by mxschmitt** [comment]
This is not possible as of today.

**Comment by buptzwl** [comment]
> This is not possible as of today.

thank you.
