### ISSUE TITLE
[BUG] Firefox opens up in new window ignoring the args passed

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#16306]
**Context:**
- Playwright Version: 1.24.0
- Operating System: WIndows
- Node.js version: 14.0
- Browser: Bundled Firefox
- Extra: Running with Playwright server

**Code Snippet**
Playwright server code:
```javascript
const {firefox} = require("playwright");

(async () => {
  const browserServer = await firefox.launchServer({
    args: [
      "-height=200",
      "-width=888",
    ],
    headless: false,
  });

  const wsEndpoint = browserServer.wsEndpoint();
  console.log("wsEndpoint=====>", wsEndpoint);
})();
```

Playwright client code:
```javascript
const {firefox} = require("playwright");

(async () => {
  let browser;
  browser = await firefox.connect({
    wsEndpoint: "<CDP WebSocket Path>",
  });

  const page = await browser.newPage();
  await page.goto("https://whatismyviewport.com/");
  await browser.close();
})();
```

**Describe the bug**
I am passing width and height in the server launch `args`. A browser window is launched with the specified args, but the test runs in a newer browser window. Refer the image:

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/84451419/183098789-7d06db3f-8a3f-4f5b-b867-12bf65624c44.png">

**Comment by mxschmitt** [comment]
If you specify the viewport inside 

```js
const page = await browser.newPage({
  viewport: {
    width: 1920,
    height: 1080,
  },
});
```

then it should work as expected!

**Comment by ankur-lt** [comment]
The issue is not just related to the viewport args. The same behaviour is observed if I pass any other CLI args to firefox.
Ideally, the test should run in the previous browser window launched by Playwright as seen in the image above.

**Comment by mxschmitt** [comment]
Which args do you pass?

Most likely they are not compatible with Firefox.

**Comment by ankur-lt** [comment]
As per I checked, if I pass any other CLI args, like `"-private", "-devtools"`, the test runs open in the same window. But if I pass `-width` or `-height`, I face the above mentioned issue.

**Comment by mxschmitt** [comment]
Closing since as per above, its not supported to pass width/height per args. Browsers support different args, in firefox its e.g. `  --window-size width[,height] Width and optionally height of screenshot.` instead of `-width` and `-height`.

Furthermore passing it inside `browser.newPage()` will make it all just work!
