### ISSUE TITLE
[BUG] Fatal error in launcher: failed to open executable.

### ISSUE THREAD

**Issue by abiliocaldas** [microsoft/playwright#16308]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Windows 
- Node.js version: v16.16.0
- Browser: Chromium, Firefox
- Extra: [any specific details about your environment]

**Code Snippet**

playwright Fatal error in launcher:  failed to open executable.
executed: playwright install (python)

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Do you have any error message which appears or a repro which you can share?

You can also set `DEBUG=pw:api`, or `DEBUG=pw:browser` to see more verbose output.

**Comment by rwoll** [comment]
Closing as part of triage. If you're still facing an issue, please re-file with the logs requested above as well as the code and commands you are running. This will ensure we can help in a timely manner without guessing.

Thanks!
