### ISSUE TITLE
[Feature] Exit with code 124 when global timeout is hit

### ISSUE THREAD

**Issue by Luc45** [microsoft/playwright#16309]
I would like Playwright to exit with status code 124 when the global timeout is hit. The current behavior exits with status code 1, which makes it hard for scripts to take different actions depending on whether a test errored or timed out.

**Example use-case:**

To eliminate flakiness in CI, we use the [retry](https://github.com/nick-fields/retry) action that will re-run the tests one time if it failed. I only want to retry the action if it errored, not if it timed-out, to prevent excessive CI usage time.

**Comment by mxschmitt** [comment]
Looks related to https://github.com/microsoft/playwright/issues/14109, sounds like we can merge?

**Comment by Luc45** [comment]
I would love to see this small change making its way into a release soon, but I agree that it sounds like a good candidate for merging with a more comprehensive exit statuses code solution.

**Comment by mxschmitt** [comment]
Merging for now! We usually add features based on upvotes, so if you upvote it there it increases the chance.
