### ISSUE TITLE
how to solve json config file problem?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16301]
I have a dev.json file;
```
{
    "env": {
        "url": "http://test.co"
      }
}
```

I want to use this json file as a config file.In my froject I m calling the url like below;
```
const config = require(process.env.CONFIG || '');
const { url } = { url: config.url };
```

In the package.json file,I m running below script;
`"pw:start": "npx playwright test test.spec.ts && CONFIG=dev.json npx playwright test id.spec.ts"`

On the terminal when I run `npm run pw:start`  , I m taking below error;
```
'CONFIG' is not recognized as an internal or external command,
operable program or batch file.
```
How to fix this problem?

**Comment by YusufOzturk-Development** [comment]
Hi @mxschmitt  sorry for attach. But this question is related to my previous question. I tried your comment but took abone error. I saw the previous question got closed by you so I didn t made commemt there

**Comment by mxschmitt** [comment]
This is not how setting env vars is working, you need to do it in the beginning or use cross-env:

`CONFIG=dev.json npx playwright test test.spec.ts && npx playwright test id.spec.ts`

or this which works on Windows too:

`npx cross-env CONFIG=dev.json npx playwright test test.spec.ts && npx playwright test id.spec.ts`

In theory you can also drop the npx, since its inside the package.json scripts section.

**Comment by YusufOzturk-Development** [comment]
@mxschmitt I got it thanks

**Comment by YusufOzturk-Development** [comment]
@mxschmitt  I tried today and solved CONFIG error as you said and run the below script;
`npx cross-env CONFIG=dev.json npx playwright test test.spec.ts && npx playwright test id.spec.ts;`


But got new error related to call url in the dev.json.I tried 3 different code like below; 
1. When I type the below code in the project,

      ```
    const config = require(process.env.CONFIG  ||  '');
    const { url } = { url: config.url }; 
     ```

     **Took below error in the terminal output**;
      `TypeError: The argument 'id' must be a non-empty string. Received '' `

2. When I type the below code in the project,

 ```
const config = require(`${process.env.CONFIG }`);
 const { url } = { url: config.url };
```

 **Took below error in the terminal output**
 `       Error: Cannot find module 'undefined'`

3.  When I type the below code in the project,I gives an error on the code , 

     `const config = require(process.env.CONFIG);` 

    **Error on the code is below**;
   ```
   Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
    Type 'undefined' is not assignable to type 'string'.
   ```

How to call url in the dev.json. How to fix my code on the `require(process.env.CONFIG)` side when I call the url in the dev.json?
