### ISSUE TITLE
[Question] How to know if the page loaded with errors?

### ISSUE THREAD

**Issue by hkfsc** [microsoft/playwright#16310]
Sometimes when the network is bad, the page will have "Failed to load resource" errors:
![image](https://user-images.githubusercontent.com/103763990/183121633-0c94adc3-cfef-4bba-b04e-6721ec117724.png)

And sometimes it will cause the page loaded partially so we can't act with the page, I wonder if there anything we can do to know if there is any error occurred while loading the page, so we can prevent act with it(might will get TimeoutError) and then can do refresh until loaded without errors?

**Comment by vladkrasn** [comment]
This? https://playwright.dev/docs/api/class-consolemessage
