### ISSUE TITLE
[BUG] ESM: Cannot find module '@playwright/test/types/...' or its corresponding type declarations.

### ISSUE THREAD

**Issue by jgerigmeyer** [microsoft/playwright#16316]
**Context**
- Playwright Version: @playwright/test@1.24.2
- Operating System: Mac with M1 chip
- Node.js version: v16.16.0
- Browser: n/a
- Extra: TypeScript 4.7.4 with `"type": "module"` and `"module": "NodeNext"`

System:
 - OS: macOS 12.5
 - Memory: 1.06 GB / 32.00 GB

Binaries:
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - Yarn: 1.22.19 - ~/.yarn/bin/yarn
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```ts
import { test, expect } from '@playwright/test';
```

**Describe the bug**

With `"type": "module"` and `"module": "NodeNext"` or `"module": "node16"` set, TypeScript throws two `TS2307` errors on `@playwright/test`:

```bash
➜ npm run tsc

> pw-esm-repro@0.0.0-development tsc
> tsc

node_modules/@playwright/test/types/test.d.ts:3027:34 - error TS2307: Cannot find module '@playwright/test/types/expect-types' or its corresponding type declarations.

3027 import type * as expectType from '@playwright/test/types/expect-types';
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@playwright/test/types/test.d.ts:3028:28 - error TS2307: Cannot find module '@playwright/test/types/testReporter' or its corresponding type declarations.

3028 import type { Suite } from '@playwright/test/types/testReporter';
                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: node_modules/@playwright/test/types/test.d.ts:3027
```

This seems possibly related to https://github.com/microsoft/playwright/issues/14971?

**Repro**

1. Clone https://github.com/jgerigmeyer/pw-esm-repro
2. Checkout `ts-npm` branch
3. `npm i`
4. `npm run tsc`

**Comment by chrisha22** [comment]
Hi @mxschmitt, what was the fix for this issue? Im seeing the same problem on my config file and everywhere I do import of the `@preact/playwright-ct `.

Thanks in advance for your help
