### ISSUE TITLE
[Question] webpage not loading electron

### ISSUE THREAD

**Issue by 2BC-Wasabi** [microsoft/playwright#16337]
hello there i have a project based on electron-react-boilerplate, when i try to run a simple test the webcontents doesn't load and i just have white screen.

i tried launching the main.js from release folder, from the app.asar after install.

also is there an option to launch it using the exe ? and how do i keep the window open after test is done?

**Comment by mxschmitt** [comment]
I created a PR to electron-react-boilerplate which demonstrates a basic integration, it was working for me! 

https://github.com/electron-react-boilerplate/electron-react-boilerplate/pull/3284

Let us know what you do different.

**Comment by 2BC-Wasabi** [comment]
thank you very much,
i'm my project is already in advanced stages where i use multiple windows, there are also some folders that i relay on that are not found in release/app/dist, i am wondering if it is possible to run the tests when using npm start..
for now i found a workaround and that is to just install the app and ignore the --inspect=0 flag at the start of the app

**Comment by mxschmitt** [comment]
Cool, since it's working I'm closing it for now, hopefully the upstream contribution into the boilerplate gets merged as well.

If you still encounter issues, please re-file with a repro.
