### ISSUE TITLE
[BUG] Package.json exports should include "default" fallback key

### ISSUE THREAD

**Issue by jeremy-daley-kr** [microsoft/playwright#16345]
**Context:**
- Playwright Version: 1.24.0
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: NA
- Extra: NA

**Describe the bug**

The `eslint-plugin-import` plugin uses a [`import/no-unresolved`](https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-unresolved.md) directive which fails on `@playwright/test` unless a [`default`](https://nodejs.org/api/packages.html#conditional-exports) export is defined in the `package.json` file.

Does this seem like a reasonable inclusion? I can't say if it's considered best practice to include the fallback, but it _is_ explicitly mentioned in Node's docs.

**Comment by rwoll** [comment]
Fixed by #16350 and #16360
