### ISSUE TITLE
[Question] Fail on unhandled exception?

### ISSUE THREAD

**Issue by tslocke** [microsoft/playwright#16355]
If an unhandled JS exception happens in the browser, i.e. an error that would show up in the devtools console, does that cause the current test to fail?

If not, is there a way to make that happen?

Alternatively, I have a "something went wrong" error indicator that pops up in the UI. I know how to write an assertion that says the error indicator is not present, but that only applies at a particular moment in the test script. 

Say I'm waiting for some action to complete, I also want to be watching to see if the error appears, and fail the test if it does. How can I code that? e.g. "wait for X to be visible" and simultaneously "fail if Y becomes visible"

Thanks

**Comment by tslocke** [comment]
I figured out a way to do this. Not sure if it's good practice or not:

I run this as the first line of the test. The key is to wait for the error message, but *not* with an `await`, so the script can continue.

```
page.waitForSelector('.error-message').then(() => expect('But it did').toBe('Error bar not to show up'))
```

The strings in expect/to-be were just a way to have something meaningful in the report (Expected: "Error bar not to show up" Received: "But it did"). I would rather have a more semantic way to fail the test, e.g. `assert(false, "Error message showed up")` but I couldn't find anything like that.

**Comment by tslocke** [comment]
Urgh. This only works for the failure case. If the test "passes", playwright complains that "Target closed" while still waiting for something.

**Comment by tslocke** [comment]
OK I found `page.on('pageerror', ...)`

Was nice chatting to me : )

**Comment by rwoll** [comment]
Closing per above 😄 😁

Yes, [`page.on('pageerror')`](https://playwright.dev/docs/api/class-page#page-event-page-error) is the recommended approach.

**Comment by karlhorky** [comment]
@rwoll @dgozman @mxschmitt would the Playwright team consider adding an option for this as default behavior?

```ts

```

**Comment by karlhorky** [comment]
For our applications, I've developed this `throwOnErrorsOrConsoleLogging()`, which I now documented in Playwright Tricks - it handles `console.log()`, `console.error()`, thrown errors, and HTTP 500 Internal Server Error responses:

https://github.com/karlhorky/playwright-tricks#fail-test-on-internal-server-error-thrown-errors-consolelog-consoleerror

<img width="1422" height="830" alt="Image" src="https://github.com/user-attachments/assets/009cddf7-2c5d-4744-9197-8297553f2637" />
