### ISSUE TITLE
[Question] How to set user preferences for Chrome browser

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright#16368]
Hi everyone,

So our question, How to set user preferences for Chrome browser??, we know that option available for firefox, but we need also to set and control the browser preferences on Chrome, as flags cmd, not covering everything, example : to disable or enable the auto-fill password!?.

kindly if any advice on this will be much appreciated, note that we using the Playwright .net version.

Thank you

**Comment by rwoll** [comment]
Thanks for the report. If it's not exposed as [CLI flag in Chrome](https://peter.sh/experiments/chromium-command-line-switches/) it's not possible today, aside from trying to use a persistent context.

Can you elaborate how auto-fill or other settings are impacting your testing?

**Comment by ahmwai** [comment]
Thanks for your reply,

in preference, we can have multiple things useful for any type of test, such as the Webrtc, the local storage, index db ...etc

currently, we are using LaunchPersistentContextAsync.

So if you have any advice what is the other way to user preference, like is it possible to edit the chrome profile file itself, or other way !?

Thank you

**Comment by rwoll** [comment]
Persistent context is still the best workaround for now for options that cannot be specified on CLI nor a formal Playwright API.

Closing as relates to https://github.com/microsoft/playwright/issues/13518, https://github.com/microsoft/playwright/issues/13516
