### ISSUE TITLE
[Question]: 'suggestedFilename' is not working and throwing error as: TypeError: Cannot read properties of undefined (reading 'suggestedFilename')

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#16373]
Getting the error as: **TypeError: Cannot read properties of undefined (reading 'suggestedFilename')**, 
looks like **suggestedFilename** is not working for my code(JavaScript) and also the file is getting download with alpha-numeric name. 
**Code**: 
**const fileNamePath = download.suggestedFilename() 
       await download.saveAs(fileNamePath); **
Please suggest how to resolve this.

**Comment by mxschmitt** [comment]
download in your case is undefined. Could you share a full reproducible with us?

See here for how to deal with downloads: https://playwright.dev/docs/downloads

**Comment by AkkyLohana90** [comment]
**Code**:
async downloadFile() {
         //Download File
         const [download]  = await Promise.all([
           this.page.waitForTimeout(20000),
            this.page.waitForEvent("download"),
       ])
       const fileNamePath = download.suggestedFilename() // de-structuring
       await download.saveAs(fileNamePath); 
       }

**Comment by rwoll** [comment]
It looks like there's a few errors in your snippet.

1. Order matters when unpacking arrays:
    ```ts
    const [a] = await Promise.all([Promise.resolve(1), Promise.resolve(2)]);
    ```
    `a === 1`. So in your `Promise.all` you'll want  `page.waitForEvent("download")` as the first item in your array. Your `download` variable that you are calling `suggestFilename` is not actual a download event because the order is incorrect. 

    If I wanted the second item, you can do `const [_, b] = …`

2. Event Trigger: When using `waitForEvent` you'll want to start waiting for it _before_ you take an action that will trigger the event (like a click). Also, `page.waitForTimeout(20000)` won't help here since it doesn't trigger a download event.

Here's a working example from the docs:

```ts
const [ download ] = await Promise.all([
  // Start waiting for the download
  page.waitForEvent('download'),
  // Perform the action that initiates download
  page.locator('button#delayed-download').click(),
]);
// Wait for the download process to complete
console.log(await download.path());
// Save downloaded file somewhere
await download.saveAs('/path/to/save/download/at.txt');
```

**Comment by AkkyLohana90** [comment]
Thanks rwoll,
Updated the code as per the above suggestions & it is working now.
Closing the Question.
