### ISSUE TITLE
 How to fix my code when I call the url in the json file?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16379]
I have a dev.json file;
```
{
    "env": {
        "url": "http://test.co"
      }
}
```

I want to use this json file as a config file.In my project I m calling the url like below;
```
const config = require(process.env.CONFIG || '');
const { url } = { url: config.url };
```

In the package.json file,I m running below script;
`npx cross-env CONFIG=dev.json npx playwright test test.spec.ts && npx playwright test id.spec.ts;`

But got error related to call url in the dev.json.I tried 3 different code like below; 
1. When I type the below code in the project,

      ```
    const config = require(process.env.CONFIG  ||  '');
    const { url } = { url: config.url }; 
     ```

     **Took below error in the terminal output**;
      `TypeError: The argument 'id' must be a non-empty string. Received '' `

2. When I type the below code in the project,

 ```
const config = require(`${process.env.CONFIG }`);
 const { url } = { url: config.url };
```

 **Took below error in the terminal output**
 `       Error: Cannot find module 'undefined'`

3.  When I type the below code in the project,I gives an error on the code , 

     `const config = require(process.env.CONFIG);` 

    **Error on the code is below**;
   ```
   Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
    Type 'undefined' is not assignable to type 'string'.
   ```

How to call url in the dev.json. How to fix my code on the `require(process.env.CONFIG)` side when I call the url in the dev.json?

**Comment by rwoll** [comment]
If you want to control your env variables from a file, the 3rd-party `dotenv` package. See https://playwright.dev/docs/test-parameterize#env-files

**Comment by YusufOzturk-Development** [comment]
@rwoll  I know the 3rd-part tools but I will not manage only env variables.So need to develop above code. Is there any option for this like my code?

**Comment by rwoll** [comment]
@YusufOzturk-Development The config is a node script, so it can run any code you'd like (although discouraged). If you need some info from a configurable JSON file you could do something like at the top of your `playwright.config.ts`:

```
import fs from "fs";
if (!process.env.SETTINGS_FILE)
  throw new Error('Must set SETTINGS_FILE');
const SETTINGS = JSON.parse(fs.readFileSync(process.env.SETTINGS_FILE, 'utf8'));

const config = {
    use: { baseURL: SETTINGS.basURL },
}

export default config;
```

Does that help you?

**Comment by YusufOzturk-Development** [comment]
Hi @rwoll these answer is helps me . When I run your code in the playwright.config.ts , should I run npm script like below ?
`npx cross-env SETTINGS_FILE=dev.json npx playwright test test.spec.ts && npx playwright test id.spec.ts`

**Comment by rwoll** [comment]
Yes, although if you want `SETTINGS_FILE` set for your second command (`npx playwright test id.spec.ts`) as well, add `npx cross-env SETTINGS_FILE=dev.json` before it as well.

**Comment by YusufOzturk-Development** [comment]
@rwoll I got it and try in 30 minutes

**Comment by YusufOzturk-Development** [comment]
@rwoll  worked, thanks
