### ISSUE TITLE
[Question] Re-creating touch based actions with dispatchEvent/evaluate

### ISSUE THREAD

**Issue by wahreChrist** [microsoft/playwright#16381]
**Context:**

  Playwright Version: 1.23.0
  Operating System: Ubuntu 20.04 KDE Neon
  Node.js version: 16.17.1
  Browser: Chromium 104.0.5112.20 (64-bit)

**Issue:**

I have been trying to re-create touch based actions(like swiping, pinching, etc.) for mobile sized viewports of a website with Playwright, but couldn't seem to make anything work.
I have tried a bunch of options, like:
```
await page.evaluate(() => {
  const target = document.querySelector("#abc");
  target.addEventListener('touchstart', (e) => {
	  console.log('touch start');
  });
  
  function simulateTouchEvent(element, type, touches) {
    const touchEvents = [];
  
    touches.forEach((touch) => {
      touchEvents.push(new Touch({
        clientX: touch.x,
        clientY: touch.y,
        identifier: touch.id,
        target: element,
      }));
    });
  
    element.dispatchEvent(new TouchEvent(type, {
      touches: touchEvents,
      view: window,
      cancelable: true,
      bubbles: true,
    }));
  }
  
  simulateTouchEvent(target, 'touchstart', [{
    id: "123",
    x: 10,
    y: 10,
  }]);

 simulateTouchEvent(target, 'touchend', [{
    id: "123",
    x: 10,
    y: 10,
  }]);
})
```
that I found on Stackoverflow, or #6072 solution that @ccpu provided and which I`m trying to stick to right now to make it work:
```
async function dispatchTouchEvent(
  playWright: Page,
  type: 'touchstart' | 'touchend' | 'touchcancel' | 'touchmove',
  selector: string,
  page?: Position,
  screen?: Position,
  client?: Position,
  options?: PageExtraTouchOptions,
) {
  await playWright.$eval(
    selector,
    (el, options) => {
      const rect = el.getBoundingClientRect();

      const {
        client = {},
        page = {},
        screen = {},
        type,
        options: touchOpt,
      } = options;

      const touchObj = new Touch({
        clientX: client.x,
        clientY: client.y,
        identifier: Date.now(),
        pageX:
          page.x || (client.x !== undefined ? rect.left + client.x : undefined),
        pageY:
          page.y || (client.y !== undefined ? rect.top + client.y : undefined),
        screenX: screen.x,
        screenY: screen.y,
        target: el,
      });

      const touchEvent = new TouchEvent(type, {
        bubbles: true,
        cancelable: true,
        ...touchOpt,
        changedTouches: [touchObj],
        targetTouches: [touchObj],
        touches: [touchObj],
      });
      return el.dispatchEvent(touchEvent);
    },
    { client, options, page, screen, type },
  );
}

await dispatchTouchEvent(
                page,
                "touchstart",
                ".selector"
            );
```

but still to no avail.

Tests are not failing in both cases, its just nothing happens, dispatch functions dont do anything, even a simple tap, that I have been trying to re-create.

Webkit version throws an error in the beginning of the dispatchTouchEvent function saying that playWright.$eval is Illegal construction, and if I try to change it to locator, then it complains that there are too many arguments and I should wrap it with object.

Can someone recommend me simpler alternatives or maybe know how to make these options work?

**Comment by rwoll** [comment]
Converting to feature request as PW could have much nicer APIs on this front one day. I recommend asking in [Community Slack](https://aka.ms/playwright-slack) to understand what other users are doing on this front. Feel free to comment back here with tips for others as you find out!

**Comment by wahreChrist** [comment]
Thanks, I`ll ask there.
Interestingly enough Playwright has touchscreen.tap method starting from version 1.8 and it works flawlessly, thats why I`m surprised that there are no other out-of-the-box implementations for touchscreen in order to have a full-fledged tool set for this purpose.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
