### ISSUE TITLE
How to write different scripts in package.json for dev tst and acc enviornments

### ISSUE THREAD

**Issue by viveksuarez7** [microsoft/playwright#16380]
Hi Everyone .. i want to write a particular script in my package.json that runs the test cases for test and dev enviornment. 
 currently i have configured it in `process.env.STAGING` === 'DEV' ---> `STAGING=DEV npm run test:e2e` ---> runs test for dev 
 
 Is there a way possible such that the i dont have to include 'STAGING=DEV' before my script can it included in the script

**Comment by rwoll** [comment]
There's a few options depending on what the rest of your setup looks like.

If you're already using env variables, the simplest approach is to define different scripts in your `package.json`:

```
{
   …
   "scripts": {
       "test:e2e:dev": "STAGING=DEV npx playwright test",
       "test:e2e:prod": "STAGING=prod npx playwright test"
   },
   …
}
```

and then you can run like:

```
npm run test:e2e:dev
```

Another approach is to use [projects](https://playwright.dev/docs/test-advanced#different-tests-different-configuration).

Does the first work for your use case? If not, please show the code snippet where you use/read `process.env.STAGING` so we can better understand what it controls and how it's used. Thanks!

**Comment by viveksuarez7** [comment]
Hi rwoll , below is the current implementation where i have used env variables ... i tried out the first use case you suggested but it threw an error where the error was --->'STAGING' is not recognized as an internal or external command,
operable program or batch file.

```
test('Go to account opening screen and Open a new account ', async ({ page }) => {
  test.setTimeout(120000);

  // await nagvigateToIntake('AO');

  // await nagvigateToIntake('AL');

  // await resumeCase('AO', 'caseId');


  if (process.env.STAGING === 'DEV') {
    await page.goto('some link');
    await page.goto(
      'some link'
    );

    await page.locator('text=Open new account').click();
  } else if (process.env.STAGING === 'TST') {
    // ends on dashboard
    await page.goto('some link');

    await page.locator('a:has-text("Client services")').click();

    // Click text=Request account opening
    await page.locator('text=Request account opening').click();
  }
```

**Comment by rwoll** [comment]
@viveksuarez7 Looks like I missed you're on Windows.

Add `cross-env` to your project:

```
npm i --save-dev cross-env
```

And then add cross-env in prefix in your package.json:

```
{
   …
   "scripts": {
       "test:e2e:dev": "cross-env STAGING=DEV npx playwright test",
       "test:e2e:prod": "cross-env STAGING=prod npx playwright test"
   },
   …
}
```

Then the syntax env variable setting syntax will work across platforms. FMI, see https://www.npmjs.com/package/cross-env
