### ISSUE TITLE
Accessibility Testing[Question]

### ISSUE THREAD

**Issue by tomern** [microsoft/playwright#1638]
Which libraries can you use for accessibility testing? (like axe)

**Comment by pavelfeldman** [comment]
You can use Axe, evaluate it in the context of the page and it should work!

**Comment by abhinaba-ghosh** [comment]
Hi @tomern 

You can use [axe-playwright](https://www.npmjs.com/package/axe-playwright). 

- Add the library as a dependency:

```ssh
npm I -D axe-playwright
```

- Inject axe in the context of the correct `page`

```js
beforeAll(async () => {
  browser = await chromium.launch();
  page = await browser.newPage();
  await page.goto(`http://localhost:3000/login`);
  await injectAxe(page);
});
```

- Execute custom command to scan the accessibility with Playwright

```js
it('simple accessibility run', async () => {
    await checkA11y(page);
  });
```
