### ISSUE TITLE
chrome extension is invisible,  how to make it visible on the toolbar?

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#16389]
chrome extension is invisible,  how to make it visible on the toolbar?

how can we control the extension? to make some option on it.
when i load the extension it's always hidden and invisible.

we need to control the extension to control the web page.

**Comment by rwoll** [comment]
See https://playwright.dev/docs/chrome-extensions#testing. Does this work for you?

**Comment by viponedream** [comment]
> See https://playwright.dev/docs/chrome-extensions#testing. Does this work for you?
thanks for your answer.

like this extension:   https://chrome.google.com/webstore/detail/phantom/bfnaelmomeimhlpmgjnjophhpkkoljpa




![QQ图片20220810091351](https://user-images.githubusercontent.com/16624529/183788973-ce31903b-948f-42b6-8168-aed7f833661e.png)

like this, we need to show it on the toolbar
![QQ图片20220810091419](https://user-images.githubusercontent.com/16624529/183788997-13f74a8e-7323-4dc8-9bd2-beb3a4d7c21b.png)

**Comment by rwoll** [comment]
Ah—thanks for the screenshots. Unfortunately, Playwright is unable to interact with that part of the browser today. Please upvote and/or comment on https://github.com/microsoft/playwright/issues/5593 to help us track users requesting this feature.
