### ISSUE TITLE
Jenkins Playwright HTML plugin

### ISSUE THREAD

**Issue by krishnaaSundaram-QaStack-1989** [microsoft/playwright#16397]
Do we have Jenkins Playwright plugin to generate and send HTML reports in MS teams or Outlook mail ?
Existing ones : HTML Publisher ( I am aware of this) 
I would be great to have one if we're not having it currently .

**Comment by rwoll** [comment]
Not as of today—although there may be some 3rd-party ones. Please comment and/or upvote https://github.com/microsoft/playwright/issues/15258 tracking this request.
