### ISSUE TITLE
[Question]: How to verify the name and size of the downloaded file?

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#16402]
[Question]: How to verify the name and size of the downloaded file?
I have copied the downloaded file from local to Project Structure - Download folder for further use, but now I have to verify the name & size of the downloaded file, to check if it same as expected result or not.
How we can achieve the same in Playwright using JavaScript?
Please suggest.

**Comment by rwoll** [comment]
You can call Node code from within your playwright script, so you can make use of assertions, https://playwright.dev/docs/next/api/class-download#download-suggested-filename, and Node's built-in [stat](https://nodejs.org/api/fs.html#filehandlestatoptions) call.

Something like:
 
```
import { test, expect } from '@playwright/test';
import fs from 'fs';

test('should download file', async ({ page }) => {
  // …
  const [ download ] = await Promise.all([
    // Start waiting for the download
    page.waitForEvent('download'),
    // Perform the action that initiates download
    page.locator('button#delayed-download').click(),
  ]);
  
  // assert filename
  expect(download.suggestedFilename()).toBe("my-file.data");
  // get and assert stats
  expect((await fs.promises.stat(await download.path() as string)).size).toBeGreaterThan(200);
});
```

**Comment by rwoll** [comment]
If the above doesn't work for your use case, can you elaborate more on what:

> Download folder for further use, but now I have to verify the name & size of the downloaded file, to check if it same as expected result or not.

means? i.e. Describe or include pseudo-code of exactly what you'd like to assert.

**Comment by AkkyLohana90** [comment]
Hello rwoll,

Thanks...!
// assert filename
  expect(download.suggestedFilename()).toBe("my-file.data");
**>> Is working.**

**But can we read the downloaded file in Playwright using JavaScript?**
and 
Download folder for further use, but now I have to verify the name & size of the downloaded file, to check if it same as expected result or not.
**Means: I want to verify the name of the downloaded file should be "xyz.csv" or not and also its size should be of #kb.** 
just to confirm the expected file is downloaded and not the unexpected1.

**Comment by rwoll** [comment]
> Download folder for further use, but now I have to verify the name & size of the downloaded file, to check if it same as expected result or not.

Change:

```
expect(download.suggestedFilename()).toBe("my-file.data");
```

to:

```
expect(download.suggestedFilename()).toBe("xyz.csv");
```

> also its size should be of #kb.

You can run any Node code you like—including converting it from Bytes to kb:

```
expect((await fs.promises.stat(pathToFileOnDisk)).size / BYTES_TO_KB).toBeGreaterThan(2);
```

(If my math is correct, `BYTES_TO_KB = 1000`)

You can also read the file's contents by doing:

```
const contents = await fs.promises.readFile(await download.path());
```

and running whatever code/assertions against the contents you'd like.

For more information about working with the filesystem in Node, see Node's docs: https://nodejs.org/api/fs.html#filehandlereadfileoptions

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
