### ISSUE TITLE
[Question] Why can't I register same url multiple times? (For page.route) 

### ISSUE THREAD

**Issue by SirMishaa** [microsoft/playwright#16408]
Hello ! 

I am in a case where I have to match the same route (url) but for different HTTP methods

### Context
I have a special system that allows me to automatically apply a fixture system with an enumeration.

```ts
export enum FixtureRoutes {
   /** Post request */
  ACCIDENT_RECORDS__CREATE = '**/ardor/accident-records',
  /** Put request */
  ACCIDENT_RECORDS__UPDATE = '**/ardor/accident-records',
}
```

I'm using this util method to apply my route : 
```ts
export async function applyRequestInterceptor(page: Page, routeKey: FixtureRouteKey | Array<FixtureRouteKey>, httpMethod: HttpMethod = HttpMethod.GET): Promise<void> {
  if (Array.isArray(routeKey))
    return routeKey.forEach(key => applyRequestInterceptor(page, key, httpMethod))

  return page.route(FixtureRoutes[routeKey], async (route, request) => {
      if (request.method().toUpperCase() !== httpMethod) return
      return route.fulfill({
        status: 200,
        path: generateFixturePath(routeKey),
      })
    }
  )
}
````

Then, I configure my interceptor globally like this : 
```ts
export const fixtureRoutesConfiguration: FixtureRoutesConfiguration = {
  "GAMIFICATION__CREATE": { method: HttpMethod.POST },
  "TRACKER__CREATE": { method: HttpMethod.POST },
  "ACCIDENT_RECORDS__CREATE": { method: HttpMethod.POST },
  "ACCIDENT_RECORDS__UPDATE": { method: HttpMethod.PUT },
}

export const test = baseTest.extend({
  page: async ({page}, use) => {
    await page.setViewportSize({width: 1440, height: 900})

    populateFixtureRoutesConfiguration()
    Object.entries(fixtureRoutesConfiguration).forEach(([routeKey, {method}]) =>
      applyRequestInterceptor(page, routeKey as FixtureRouteKey, method)
    )

    await use(page)
  }
})
```
This is a system that allows me to put all my routes in an enumeration, and to choose the HTTP methods to apply for them.

### Problem

If you use multiples times ``page.route`` for **same** URL, only the last given callback will be called. 
Example : 
```ts
page.route('**/test', async (route, request) => {
     console.log('Hello')
      return route.fulfill({
        status: 200,
        path: generateFixturePath(routeKey),
      })
    }
  )

page.route('**/test', async (route, request) => {
     console.log('Hello two')
      return route.fulfill({
        status: 200,
        path: generateFixturePath(routeKey),
      })
    }
  )

// http://localhost:3000/test 
// Here, only the second page.route will be called, so it will show Hello two in the console and NOT hello + hello two :(
```

Here, when the route will be matched, only the second callback will be executed (the ``Hello two``). 
It's really annoying, I'm not sure where this restriction comes from and why it exists :(
In my case, it blocks me completely to apply different callbacks for each HTTP method.

Any idea?

**Comment by rwoll** [comment]
`fulfill` is terminal and will stop the request handler chain from falling back and running the other matching handlers. In the handlers that match by url, but don't match by method (https://playwright.dev/docs/api/class-request#request-method), you'll want to call `return await route.fallback();`. See https://playwright.dev/docs/api/class-route#route-fallback for additional docs/examples.

In the body of you're handler, if you don't want it to handle a method, you can add:

```ts
if (route.request.method() === 'POST') return await rotue.fallback()
```

**Comment by rwoll** [comment]
Closing per-above but please re-open or re-file as appropriate.

**Comment by Forever17s** [comment]
> ```ts
> page.route('**/test', async (route, request) => {
>      console.log('Hello')
>       return route.fulfill({
>         status: 200,
>         path: generateFixturePath(routeKey),
>       })
>     }
>   )
> 
> page.route('**/test', async (route, request) => {
>      console.log('Hello two')
>       return route.fulfill({
>         status: 200,
>         path: generateFixturePath(routeKey),
>       })
>     }
>   )
> ```

This issue also troubles me. In my scenario, simulate the query details interface, and then modify the details name 'test1' to 'test2' to determine whether the name is' test2 '. The second query for details now always has the name 'test1'

```
page.route('**/detail', async (route, request) => {
      return route.fulfill({
        status: 200,
        data: { name: 'test1' },
      })
    }
  )

// STEP 1: modify
await page.getByRole('button', { name: 'edit' }).click();

// STEP 2: fill
await page.getByPlaceholder('test1').fill('test2');

// STEP 3: save
await page.getByText('ok').click();

// STEP 4: refetch
await page.getByRole('button', { name: 'update' }).click();

page.route('**/detail', async (route, request) => {
      return route.fulfill({
        status: 200,
        data: { name: 'test2' },
      })
    }
  )

// STEP 5: expect
await expect(page.getByTestId('name')).toHaveText('test2');
```
