### ISSUE TITLE
[Question] ESM Angular issues

### ISSUE THREAD

**Issue by i23591326** [microsoft/playwright#16417]
Hi! I have some questions:
1. Is there any way I could enable ESM build for Playwright without using "type": "module" in package.json?
2. Is there any way to preserve older code without ".ts" endings and type-only Imports?
3. [Are there are any plans about supporting Playwright test runner on top of ts-node](https://github.com/microsoft/playwright/discussions/13737) if it could help?

**Context**:
I'm using [Playwright test runner](https://playwright.dev/docs/test-runners#playwright-test) with [Angular Component Harnesses](https://material.angular.io/cdk/test-harnesses/overview) 12th version. 
I have to update Angular, however starting from version 13 [Angular no longer provide CommonJS modules (CJS), only ECMAScript (ESM) modules](https://angular.io/guide/angular-package-format), so it seems I have no options other than use [experimental TypeScript + ESM mode](https://github.com/microsoft/playwright/issues/13078#issuecomment-1082271101) if I want to stick to Playwright test runner. 
I managed to update a small part of my code by adding ".ts" endings to imports, [type-only Imports](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html) and write one small working test with "type": "module" in package.json just to check if it's possible.

However this approach has following problems:
-  "type": "module" in package.json brakes other part of the project which uses default Angular Karma setup with ns-node that resolves all the conflicts between CJS and ESM
- the amount of code that has to be rewritten is quite significant as for years we used to write a lot of harnesses and integration tests that runs on karma and ts-node, and only recently started writing e2e tests with Playwright and Babel
- [IDEA](https://www.jetbrains.com/idea/) does not support .ts endings and does not encourage type-only Imports, so the developer experience would significantly degrade

**Comment by rwoll** [comment]
> 1. Is there any way I could enable ESM build for Playwright without using "type": "module" in package.json?

Mostly no. See https://github.com/microsoft/playwright/blob/7c4099a0114db0fc43828e90d3e64d7eb59bbf7f/packages/playwright-test/src/loader.ts#L666 for the module detection logic.

> 2. Is there any way to preserve older code without ".ts" endings and type-only Imports?

Not in ESM mode. See below.

> 3. [Are there are any plans about supporting Playwright test runner on top of ts-node](https://github.com/microsoft/playwright/discussions/13737) if it could help?

See https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript. You can choose to compile your code explicitly instead of using Playwright to do it. Playwright is unlikely to directly integrate with `ts-node`, but I think `ts-node` essentially just combines the compile and run steps of your source, so you can achieve the same end result today.

Based on the original description of the issue, given the number of tools involved in your project and mixture of constraints, you may have to perform your own compilation step.

**Comment by rwoll** [comment]
Closing per above, but please re-open if you have further questions or re-file and reference this issue. If you hit errors, please include a minimal repro (i.e. a repo we can clone, download and run to observe the issue directly). However, given the number of tools involved, we may be of limited help, so reaching out to the community who might be using these tools in combination with eachother in the [Community Slack](https://aka.ms/playwright-slack)  or [Discussions](https://github.com/microsoft/playwright/discussions) maybe be a better option.

Thanks!

**Comment by i23591326** [comment]
For someone facing similar problem we managed to fix e2e in our case:
1. We used tsc to build whole project with test scenarios and all the test utilities including component harnesses.
2. We used tsc-alias and tsc-esm-fix packages to post-process that build.
3. We patched global NodeJS object in order Angular 13, 14 not to throw an error, because (I believe by the mistake) it is a part of exports of some harnesses modules, which at the moment leads to fail.

Last one worth more details as I didn't managed to google it easily:
When anything from Angular internals such as @Component decorator get into the playwright runtime in NodeJS it fails tests with error `JIT compilation failed for injectable [class PlatformLocation]` or similar depending on your Angular version. It happens for example if you import MatDialogHarness, but not if you import MatTableHarness or most of the others harnesses.
So in `playwright.config.ts` we added following lines.
```
globalThis.ng = {
  ɵcompilerFacade: {
    compileFactoryDeclaration: () => undefined,
    compileInjectableDeclaration: () => undefined,
    compileDirectiveDeclaration: () => undefined,
    compilePipeDeclaration: () => undefined,
    compileNgModuleDeclaration: () => undefined,
    compileInjectorDeclaration: () => undefined,
    compileComponentDeclaration: () => undefined,
  }
}
```
 It prevents error from happening and it doesn't brake anything as Angular runtime has no use when testing anything with Angular component harnesses

**Comment by kolianas** [comment]
Hello @i23591326, do you still use Playwright with Angular Component Harnesses? Do you use some custom library for that? Would really appreciate if you could share any feedback on this!

**Comment by i23591326** [comment]
Sorry for the late response, anyway the answer might be usefull for someone else:

We still use Playwright harnesses and we're still happy with them.

Back then, two years ago we started with https://github.com/bgotink/ngx-playwright/tree/main, then rewrote it a bit in TS, added some simplifications and some additional features for automatic wait for change detection. It seems nothing better has appeared since then, but the library seems to be active and new features seem to be added, so I would still recommend starting with it.

Can't share our implementation unfortunately, but one thing I could recommend trying is to use Locator everywhere instead of [handles](https://playwright.dev/docs/handles#element-handles) since it's recommended by Playwright and since it seems to be more predictable and performant https://github.com/bgotink/ngx-playwright/blob/a4efbbb5d7b33f5847bf64f8457bcd08894a9897/packages/test/src/harness/element.js#L224
