### ISSUE TITLE
[BUG] Component test ERR_EMPTY_RESPONSE on 2nd run

### ISSUE THREAD

**Issue by vhscom** [microsoft/playwright#16424]
**Context:**
- Playwright Version: `"playwright/experimental-ct-svelte": "^1.24.2"`
- Operating System: macOS
- Node.js version: 16.14.2
- Browser: All
- Extra: ARM chip device

**Code Snippet**

```ts
import {test, expect} from '@playwright/experimental-ct-svelte';

test('can show column', async ({mount}) => {
  const component = await mount(DataTable, {
    slots: {
      toolbar: '<div>Toolbar</div>'
    },
    props: {
      tableTitle: 'Test table',
      items: [],
      selectedOffsets: [],
      shouldShowColumn: true
    }
  });

  await expect(component).toContainText('Table column header text');
});
```

**Describe the bug**

When testing my first Svelte component, subsequent runs of the test runner result in an error message:

```
undefined: net::ERR_EMPTY_RESPONSE at http://localhost:3100/playwright/index.html
=========================== logs ===========================
navigating to "http://localhost:3100/playwright/index.html", waiting until "load"
============================================================
```

Occurs repeatedly and I cannot run tests after first test run and until the component under test has had its file date changed (via modification and saving). After that the app compiles and the test run. But not before then.

**Comment by rwoll** [comment]
I attempted to repro [here](https://github.com/rwoll/playwright-repro-svelte), but could did not observe any errors. Can you re-file with a repro attached (in the form of a GitHub repo we can clone, download, and run that produces the error)?

One thing to note: looks like you're missing `DataTable` import statment at the top of your file.

**Comment by vhscom** [comment]
@rwoll will do. I'm going to try a bulk upgrade on packages first and if that doesn't correct the problem I'll create a repo with a reduced test case for you if the issue persists.

**Comment by vhscom** [comment]
Refiled with repro in #16460
