### ISSUE TITLE
How do I run all spec files except one spec file on the second script?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#16425]
I have a 20 spec files in the project. I want to run all spec files in a script.But firstly, I must run token.spec.ts file before other spec files. My aim is that;
-> run token.spec.ts first
-> in the second npm script , all spec files should run except token.spec.ts

This is my npm script;
` "pw:staging": "npx cross-env ENV=./config/staging.json playwright test token.spec.ts && npx cross-env ENV=./config/staging.json playwright test",`

How to run my second script except token.spec.ts.Because it sould work one time before the other scripts. I want to solve this problem only npm script? Could u give me a npm script according to my aim?

**Comment by rwoll** [comment]
In your second command, add `--grep-invert token.spec.ts`.

From `npx playwright test --help`:

```
  -gv, --grep-invert <grep>    Only run tests that do not match this regular expression
```

---

[internal] almost relates to https://github.com/microsoft/playwright/issues/14895.

**Comment by YusufOzturk-Development** [comment]
@rwoll  thanks it worked
