### ISSUE TITLE
[BUG] DOM Snapshot disappears in the Trace Viewer if there is more than one trace

### ISSUE THREAD

**Issue by dimaBondarenko** [microsoft/playwright#16429]
**Context:**
- Playwright Version: 1.24.2
- Operating System: macOS Monterey 12.5 M1
- Node.js version: v16.15.0

**Code Snippet**

```typescript
import { test, expect } from "@playwright/test";

test('send request and check on UI', async({request, page}) => {
  // send a post request to the mockbin
  await request.post('http://www.mockbin.org/bin/87972e9c-b97c-4144-955f-656dd8482225', {
    data: {
      "test":"test"
    }
  })
  // go to the mockbin site and perform a failing assertion of the sent request body
  await page.goto('https://www.mockbin.org/bin/87972e9c-b97c-4144-955f-656dd8482225/log')
  await page.locator('button[data-id]').last().click()
  await expect(page.locator('tr.data div#preview').last()).not.toContainText('{"test":"test"}')
}) 
```

**Describe the bug**
I've got a test where in the beginning I send a request and then I go to the site and check the webpage contains the data from the sent request. 
When the test fails the report has two traces: one is for the context with the request fixture, and the other is for the context with the page. 
When I open a Trace Viewer for the failed test from the HTML report, it contains two traces at once, which is great, but it seems like the trace with the page snapshots doesn't work properly.

**Steps to repro**
1. Run the test snippet above with playwright `trace: 'on' | 'retain-on-failure' `(the test should fail)
2. Open HTML report
3. Open the failed test details
4. Open the Trace Viewer for the failed test
5. Click through all the actions _multiple times_
6. Check the actual DOM Snapshot is shown for the actions with the webpage
![2022-08-11_00-25-05](https://user-images.githubusercontent.com/31986966/184027898-bd22274b-4de5-40f9-b646-84fa4510b55f.png)

The test above is just a sample. In the real test I got a dozen of api requests and a few dozens of page verifications and the snapshots fail to be displayed right after the Trace Viewer is opened.

**Comment by aslushnikov** [comment]
I can repro:

```bash
$ mkdir tmp && cd tmp
$ npm init -y && npm i @playwright/test && npx playwright install --with-deps
$ cat <<EOF > a.spec.ts
import { test, expect } from '@playwright/test';

test('send request and check on UI', async({ request, page }) => {
  await page.goto('https://playwright.dev');
  await expect(page.locator('non-existing-elemnt')).toBeVisible();
});
EOF
$ npx playwright test --trace on --reporter html
```
