### ISSUE TITLE
[BUG] Azure DevOps HTML Viewer

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#16436]
Description:

Cannot open any test in html viewer in azure devops

steps to reproduce:
1. Create a pipeline
2. Add html viewer plug-ins
3. After the report generation , click on any test

expected result : Test should open like on local
Actual result: Getting blank screen 

note : I understand it has dependency on other directory though it seems a defect 
- Playwright Version: 1.24+
- Operating System: Windows
- Node.js version: 16+
- Browser: any
- Extra: Its in azure devops

**Comment by rwoll** [comment]
> Add html viewer plug-ins

What plugin does this refer to? If it's 3rd-party, we cannot be of assistance, but you can reach out to other users in the [Community Slack](https://aka.ms/playwright-slack) or GitHub Discussions.

Thanks!

**Comment by rwoll** [comment]
Relates https://github.com/microsoft/playwright/issues/10818#issuecomment-989891583.

**Comment by mechandan** [comment]
Thankyou

**Comment by rwoll** [comment]
Closing per https://github.com/microsoft/playwright/issues/16436#issuecomment-1211554906
