### ISSUE TITLE
[Feature] Load Testing

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#16435]
It would be great if we can do API load testing with playwright, can we expect ??

**Comment by rwoll** [comment]
This can be done today with `@playwright/test` in some capacity. You can launch lots of simultaneous tests/browsers, and or test an API itself without browsers via https://playwright.dev/docs/test-api-testing.

Is this what your looking for? If not, please elaborate on what you are looking to test and how you envision it being tested. Thanks!

**Comment by mechandan** [comment]
@rwoll Appreciate your quick response,

actually I was looking to  perform , Performance Testing of any API  ( Load, stress, spike n soak ) using playwright,

**Comment by rwoll** [comment]
Thanks for the clarification—I recommend asking some community users in the #performance channel of the [Community Slack](https://aka.ms/playwright-slack).

You can use Playwright to assist in performance testing, but it doesn't have any guides specifically on this topic.

**Comment by mechandan** [comment]
Thankyou 😊

**Comment by rwoll** [comment]
One day there may be a guide, but Perf testing is a large topic, so closing this issue for now.

Thanks!
