### ISSUE TITLE
[Question] Regular Expression Syntax with waitForUrl

### ISSUE THREAD

**Issue by alfflores** [microsoft/playwright#16430]
**Context:**
- Playwright Version: 1.24.2
- Operating System: 
              Edition	Windows 10 Pro
              Version	21H2
              Installed on	‎7/‎19/‎2022
              OS build	19044.1826
              Experience	Windows Feature Experience Pack 120.2212.4180.0
- Node.js version: 16.16.0
- Browser: Chromium

**Code Snippet**
$> npx playwright test

import { test, expect } from '@playwright/test';
test('waitForURL regex fail', async ({ page }) => {
  await page.goto('https://playwright.dev/docs/intro');
  await page.waitForURL('(.*)docs(.*)');
  const url = page.url();
  expect(url).toContain('playwright');
});

test('waitForURL url pass', async ({ page }) => {
  await page.goto('https://playwright.dev/docs/intro');
  await page.waitForURL('https://playwright.dev/docs/intro');
  const url = page.url();
  expect(url).toContain('playwright');
});

**Describe the bug**
page.waitForURL is not recognizing regex, only complete url string

**Comment by rwoll** [comment]
Change

```ts
await page.waitForURL('(.)docs(.)');
```

to

```ts
await page.waitForURL(/(.)docs(.)/);
```

To use RegEx as the argument, you need to use a JavaScript Regex (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions), otherwise Playwright has no way of knowing whether your code means string or RegEx.

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
