### ISSUE TITLE
[Question] how to translate webpage with playwright 

### ISSUE THREAD

**Issue by kakaok** [microsoft/playwright#16434]
I want to translate webpage with msedge，with playwright-python,but i dont know how to settings the playwright to run msedge auto translate webpage
![image](https://user-images.githubusercontent.com/10599857/184054995-52273aff-cbbd-4df2-8e3c-c1d30826079f.png)

**Comment by rwoll** [comment]
That translate menu is outside the scope of Playwright, but if the site provides its own localization, you can test it using `locale` emulation: https://playwright.dev/docs/emulation#locale--timezone

**Comment by kakaok** [comment]
execute_path = "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
    with sync_playwright() as p:
        browser = p.chromium.launch_persistent_context(
                                                    user_data_dir = r"C:\Users\Administrator\AppData\Local\Chromium\User Data",
                                                    executable_path = execute_path,
                                                    headless=False, 
                                                    args=["--start-maximized"],
                                                    viewport={'width': 1800, 'height': 1024},
                                                )
user_data_dir  is the key,first settings the msedge language and auto translate
