### ISSUE TITLE
[Question] API testing : How do we chain consecutive requests?

### ISSUE THREAD

**Issue by harir5** [microsoft/playwright#16445]
For an API test that i am writing currently, I have a case where we need to chain API calls in order to get the final response. Is it possible to chain requests using playwright?

I have Request 1 -> i get response 1. 
extract some information from response 1 and pass it in as values for fields in request 2.
get response 2 -> validate it.

is this possible ?

**Comment by rwoll** [comment]
Yes, when you make the first request, you get an [`APIResponse`](https://playwright.dev/docs/api/class-apiresponse) back, so any of the methods on there can be used to retrieve data that can then be included in your next request.

For example:

```ts

    const taskCreationResp = await request.post(`/todos`, {
      data: {
        title: 'My Task',
        body: 'Awesome task!',
      }
    });
    expect(taskCreationResp.ok()).toBeTruthy();
    const { id } = await taskCreationResp.json();
    expect(id).toMatch(/\d+/);
  
    const taskResp = await request.get(`/todos/${id}`);
    // …

```

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
