### ISSUE TITLE
[Feature] Add toMatch or toMatchText to expect library

### ISSUE THREAD

**Issue by DanielStoica85** [microsoft/playwright#16447]
Hi guys,

Any chance you can add an assertion for when you want to check that an element's text matches the expected text with regular expression?

Something like:

`await expect(someElement).toMatchText(/[S|s]uccess/);`

One use case that I can think of is for checking that a date format has been applied correctly, but I am sure there are several other use cases for this.

**Comment by rwoll** [comment]
You can do this today with https://playwright.dev/docs/test-assertions#locator-assertions-to-contain-text or https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text. See the examples for regex use, too.

Closing per-above, but if there's still an issue, please re-open!
