### ISSUE TITLE
[REGRESSION]: "Cannot read property 'pageOrError' of undefined" when trying to use Chrome

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#1644]
**Context:**
- GOOD Playwright Version: [0.11.1]
- BAD Playwright Version: [0.12.1]
- Operating System: [Mac]
- Extra: [Chrome version  80.0.3987.162]
- [getChromePath](https://github.com/hdorgeval/playwright-fluent/blob/master/src/utils/get-chrome-path/get-chrome-path.ts)

**Code Snippet**

```javascript
const browser = await chromium.launch({ headless: true, executablePath: getChromePath() });
const browserContext = await browser.newContext();
const page = await browserContext.newPage(); // => exception at CRBrowserContext.newPage (node_modules/playwright-core/lib/chromium/crBrowser.js:254:37)
```

**Describe the bug**

It was previously possible to start a chrome instance. 
In the new version, it is not possible any more.
Is this a bug, or is Chrome not usable anymore in this version?

**Comment by pavelfeldman** [comment]
Your Chrome is too old for Playwright. It is likely that this will often be the case. You can use the `PLAYWRIGHT_BROWSERS_PATH` [environment](https://github.com/microsoft/playwright/blob/v0.12.1/docs/api.md#environment-variables) variable to let Playwright know that you want to reuse a single browser installation.

**Comment by hdorgeval** [comment]
Hi @pavelfeldman , I have updated my chrome to latest version : 80.0.3987.163 (Official Build) (64-bit), but I have still the same problem :(

**Comment by arjun27** [comment]
Hey @hdorgeval, Chrome stable is not updated with the latest Chromium changes that Playwright requires. If you'd like to use Chrome (instead of Chromium), please use Chrome Canary. Thanks!

**Comment by hdorgeval** [comment]
Hi @arjun27 , Thank you very much for your kind feedback: now I do understand the differences between Chrome stable-latest-version and Chrome Canary. 

I just retested the `playwright-fluent` library with Chrome Canary and it works like a charm :). Thanks!
