### ISSUE TITLE
[Feature] Using nested locators feature

### ISSUE THREAD

**Issue by StanislavKlocko92** [microsoft/playwright#16446]
Hi folks,

I`m frequently using nested locators in my test, like "Locator.Locator(<Selector>). In some cases I don't want (or don't need) to pass <selector> value to get nested locator, I just want to use something like "Locator.AddLocator(Locator)" to get deeper. 
I was trying to implement my own extension to do this, but I didn't find how to get Locator's selector (didn't find correct property).

Can we have this feature be implemented? Or maybe you would suggest me how to get Locator's selector in C#.

**Comment by rwoll** [comment]
I'm not folllowing—can you share a snippet of pseudo code explaining what each step should return and/or do? A snippet of DOM along with the Playwright code you'd want to write will be most helpful here.

Thanks!

**Comment by rwoll** [comment]
Closing per-above as part of triage. If you're still facing an issue, please file a new issue referencing this one!

Thanks!
