### ISSUE TITLE
[Feature] Show values being compared in test.expect

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#16440]
It would be nice if the values being compared in `test.expect` could be shown, as this could help with identifying when you have made a typo, e.g.

```
const a = {
    x: 1,
    y: 2,
}
const b = {
    y: 3,
}
test.expect(a).toMatchObject(a) // second value should have been b, and thus would have failed
```

We already show `expectedText` and `expectedValue` in the tracer. It would be nice if in the steps, we could see what the value of `.expect` and `.toMatchObject` were.

**Comment by rwoll** [comment]
Thanks for the request! Can you clarify what you're seeing where, and what you expect to see? (Screenshots will be helpful here.)

When I run:

```ts
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect.soft(page.locator('.gh-count')).toHaveText("50+");
  const actual = {
    x: 1,
    y: 2,
  };
  const expected = {
    y: 3,
  };
  expect(actual).toMatchObject(expected);
});
```

I see the expected vs. actual in both  and in the HTML Report:

<img width="964" alt="Screen Shot 2022-08-11 at 12 03 56 PM" src="https://user-images.githubusercontent.com/11915034/184219226-7d5e8d9f-2a91-49e1-ba55-e7d315601306.png">

and CLI: 

<img width="838" alt="Screen Shot 2022-08-11 at 12 04 11 PM" src="https://user-images.githubusercontent.com/11915034/184219271-32b4c75a-8a86-4b5e-af77-3e482b296e59.png">

Thanks!

**Comment by A-ZC-Lau** [comment]
@rwoll It works fine when the code fails, my point was false positives can't be readily identified in a report due to a typo you made, as the report doesn't show the values being compared.

![Screen Shot 2022-08-12 at 11 56 03 am](https://user-images.githubusercontent.com/20273647/184273914-d824ead3-be5d-46a5-926a-7c27a77246fa.png)

In the trace file, we actually get the value being compared. But the trace files doesn't show any comparisons involving non-locators, i.e. just values.

![Screen Shot 2022-08-12 at 12 12 54 pm](https://user-images.githubusercontent.com/20273647/184272663-7e72b387-e15e-416c-abb9-a3304810f418.png)

The trace file is also very good at helping you identify false positives when it comes to locators, as it shows you everything it is doing, so in this case, we were meant to click on the "animals" instead of "settings". But the test still passes (false positive) as the conditions for it passing so happened to be the same as if you clicked on "animals", which we can identify by going through the trace file.

![Screen Shot 2022-08-12 at 12 26 52 pm](https://user-images.githubusercontent.com/20273647/184273808-0be8ef43-84ab-4b4b-b883-39bd427d102b.png)

I think it would be good if it showed the values being compared, maybe in the test steps, as the current formatting of the trace file probably wouldn't be good at displaying two objects. The data can be displayed just under the line of code after expanding the section.

![expect in step](https://user-images.githubusercontent.com/20273647/184274882-1b8f4fbf-abd9-4b9e-b6b4-960c6e3b2519.jpg)

```
import { test, expect, Locator } from "@playwright/test";



test("Should validate Animals sub-menu items", async ({ page }) => {
	const a = {
		x : 1,
		y : 2,
	};
	const b = {
		y : 3,
	};
	const actual = a;
	const expected = a; // mistakenly assigned "a" instead of "b"

	await page.goto("https://qaplayground.dev/apps/multi-level-dropdown/#home");
	await expect(page.locator(".navbar-nav")).toBeVisible();

	await page.locator(".icon-button").last().click();
	await page.locator("text=Settings").click(); // we can readily see that we targeted the wrong list in the trace file

	await expect(page.locator(".menu-secondary-enter-done >> .menu-item")).toHaveCount(5);

	const links = page.locator(".menu-secondary-enter-done >> a:visible");

	await expect(links).not.toHaveCount(0);

	test.expect(actual).toMatchObject(expected); // should have failed but won't due to issue above
});

```

**Comment by rwoll** [comment]
Thanks—converted to feature request

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
