### ISSUE TITLE
[Question] Component testing custom bundler

### ISSUE THREAD

**Issue by original001** [microsoft/playwright#16454]
My project use webpack and is not compatible with Vite. For example, we have commonjs. We are not planning migrate to Vite, but want to use component testing via playwright. 

Is there any plans about using project's build tools?

**Comment by rwoll** [comment]
At this time, no. However, there may be a way you can run a bundle step prior to PW running to get the best of both worlds.

@pavelfeldman do you have recommendations here?

**Comment by pavelfeldman** [comment]
Vite is not a requirement for the Playwright Component testing. We will bundle them using Vite under the hood, but the reality is that if you don't rely on webpack specifics / plugins in your components code, it should just work.

**Comment by rwoll** [comment]
Hid my original comment since @pavelfeldman's is more useful/correct :)

**Comment by original001** [comment]
I wanted to say, that my **code** is not compatible with Vite. Vite oblige to use esm, but we does not do it yet. Migrating codebase to esm only in future plans.

**Comment by aslushnikov** [comment]
> Is there any plans about using project's build tools?

@original001 answering the question, there are no plans for this so far!

Closing this now; if you think we can be helpful please do not hesitate to file a new issue / question!

**Comment by piotrpalek** [comment]
@aslushnikov just so I understand it, if we use webpack in our projects, is there any way (or any documentation you can point to) on how to integrate playwright with such project?

**Comment by pastelsky** [comment]
@aslushnikov 
Agreed that this would be desirable — especially for higher-level components that might use features like code splitting etc and bundler-specific differences aren't all that rare.

Would you be willing to accept a change that allowed us to customize the playwright's bundler?
