### ISSUE TITLE
[BUG] While running the playwright automation to ignore ssl certificate error not working.

### ISSUE THREAD

**Issue by Velmurug** [microsoft/playwright#16450]
**Context:**
- Playwright Version: 1.24
- Operating System: Windows
- Node.js version: 14.6
- Browser: Chromium

**Code Snippet**

        playwright = Playwright.create();
        if (browserName.equalsIgnoreCase("chrome") || browserName.equalsIgnoreCase("msedge")
                || browserName.equalsIgnoreCase("chromium")) {
            browserType = playwright.chromium();
        } else if (browserName.equalsIgnoreCase("webkit")) {
            browserType = playwright.webkit();
        }

       browser = browserType.launch(new BrowserType.LaunchOptions().setChannel(browserName).setHeadless(false));

       context = browser.newContext(new Browser.NewContextOptions().setViewportSize(1366, 768));
      context = browser.newContext(new NewContextOptions().setIgnoreHTTPSErrors(true));

   
        page = browser.newPage();
        page.setDefaultTimeout(50000);
    }
    
    public void launchApplication() {
        page.navigate("[https://example.com");  //example url.
        page.setDefaultTimeout(5000);
        context = browser.newContext(new NewContextOptions().setIgnoreHTTPSErrors(true));

   }

**Describe the bug**

https://stackoverflow.com/questions/67048422/ignore-ssl-errors-with-playwright-code-generation

While running using the above code should ignore the SSL certificate but it's not working, pls suggest the same.

**Comment by rwoll** [comment]
Please include your full script and mark which line is giving you the error. In the above the navigate line is the only line that looks to possibly give you the error, but I don't see a call to `launchApplication` so it's not clear what's being called when.

Thanks!

**Comment by rwoll** [comment]
Closing per-above, please file a new issue with the requested information and reference this issue. This will help ensure we're debugging the correct code.

Thanks!

**Comment by Sriram-Kumar1** [comment]
try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions()
        .setHeadless(false)
        );
    
        final Browser.NewContextOptions browserContextOptions = new Browser.NewContextOptions().setIgnoreHTTPSErrors(true);

      BrowserContext context = browser.newContext(browserContextOptions);

would work to setup to ignore https errors,

**Comment by Velmurug** [comment]
Thanks, it works.
