### ISSUE TITLE
How to remove duplicate screenshot name from report?

### ISSUE THREAD

**Issue by thedavidhoffman** [microsoft/playwright#16456]
When I add screenshots to a test, the test report displays the name twice. While, functionally, this isn't an issue, the detail oriented part of me is annoyed by this :)

```
const screenshot = await page.screenshot({ fullPage: true });
await test.info().attach(name, { body: screenshot, contentType: 'image/png' });
```

![image](https://user-images.githubusercontent.com/5252941/184136602-621e77ef-ecbd-44de-89cf-d60409e4da15.png)

I have tried specifying the path when taking a screenshot, and that does not produce the duplicate file name in the report, however, I want to use the default behavior in Playwright for taking screenshots, as it cleans up the screenshot directory every time the tests are run.

**Comment by rwoll** [comment]
Is the issue that the text is repeated (like you have in the screenshot above), or is the issue if you call attach multiple times:

```
  const screenshot = await page.screenshot({ fullPage: true });
  await test.info().attach('should be login screen', { body: screenshot, contentType: 'image/png' });
  await test.info().attach('should be login screen', { body: screenshot, contentType: 'image/png' });
```

you end up with multiple screenshots in the report? Both?

Regardless, looks like we need to clean up the repetition and/or formatting that is observed in your screenshot! Thanks for pointing it out!

**Comment by thedavidhoffman** [comment]
@rwoll 
My tests are taking multiple screenshots throughout each test, but I'm only calling screenshot/attach once for each screenshot that is being taken.

So I have this type of code repeated throughout my tests...
```
const screenshot = await page.screenshot({ fullPage: true });
await test.info().attach(name, { body: screenshot, contentType: 'image/png' });
```
But nowhere that I am making a double call to attach, as you mentioned...
```
const screenshot = await page.screenshot({ fullPage: true });
await test.info().attach(name, { body: screenshot, contentType: 'image/png' });
await test.info().attach(name, { body: screenshot, contentType: 'image/png' });
```
It is only taking one screenshot, but listing the name as a link and as a text element right after the link.

![image](https://user-images.githubusercontent.com/5252941/184235459-10ae7501-46e1-4e35-a92c-6d82b7688048.png)

Here's the markup being emitted by the report...
```
<a href="data/cb153e1d8e54b4eed0376a038565bff284c736af.png" target="_blank">should be login screen</a>
<span>should be login screen</span>
```
