### ISSUE TITLE
[BUG] Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]

### ISSUE THREAD

**Issue by tsharma-indeed** [microsoft/playwright#16469]
**Context:**
- Playwright Version: [what Playwright version do you use?]  1.22.2
- Operating System: [e.g. Windows, Linux or Mac] gitlab
- Node.js version: [e.g. 12.22, 14.6] v16.14.2
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

   page.screenshot: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]
    =========================== logs ===========================
    taking page screenshot
    ============================================================page.screenshot: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]
    =========================== logs ===========================
    taking page screenshot
    ============================================================
      76 |             await config.run({ context, page }, item);
      77 |           } catch (e) {
    > 78 |             const buffer = await page.screenshot({
         |                                       ^
      79 |               fullPage: true,
      80 |             });
      81 |             await addAttach({
      at screenshot (src/lib.ts:78:39)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.throw (../node_modules/regenerator-runtime/runtime.js:119:21)
      at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _throw (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:29:9)

Add any other details about the problem here.

**Comment by tsharma-indeed** [comment]
Using:
import type { Reporter } from 'jest-allure/dist/Reporter';

**Comment by rwoll** [comment]
Please re-file with a repro (i.e. a link to a GH repo we can clone, download, and run to observe the issue ourself). 

However, please note: it looks like you are using a third party reporter, so please try to reproduce the issue without using the third-party tool:

```
import type { Reporter } from 'jest-allure/dist/Reporter';
```
