### ISSUE TITLE
[BUG] Component test fails on 2nd run when SSL is used

### ISSUE THREAD

**Issue by vhscom** [microsoft/playwright#16460]
**Context:**
- Playwright Version: `"playwright/experimental-ct-svelte": "^1.24.2"`
- Operating System: macOS
- Node.js version: 16.14.2
- Browser: All
- Extra: ARM chip device

**Code Snippet**

Here's the reduced test case which reproduces the issue:
https://github.com/vhscom/playwright-ct-ssl-reduced-test

I've left the reduced test case configured with the Vite plugin for SSL but the issue can be reproduced without plugins specified in the Playwright component config file.

**Describe the bug**

This is an extension of https://github.com/microsoft/playwright/issues/16424. When testing a Svelte component using `@vitejs/plugin-basic-ssl` plugin test runner fails with error message when cache is present and unless the component under test has a timestamp modification (read: it was saved, even without changes):

```
undefined: net::ERR_EMPTY_RESPONSE at http://localhost:3100/playwright/index.html
=========================== logs ===========================
navigating to "http://localhost:3100/playwright/index.html", waiting until "load"
============================================================
```

I narrowed it down to a TLS/vite config/playwright lib corner case. It seems the URL under test does not work when the `@vitejs/plugin-basic-ssl` plugin is used—but only on the second run if the component under test doesn't have a timestamp modification since the last cached run.

Ideally tests will either fail wholesale if SSL is configured or there will be a way to run component tests over the `https` scheme—which would be expected when the plug-in is configured via Playwright experimental `ctViteConfig` prop. Having test runs once, fail on the second run, then work again when the cache is cleared or the component timestamp changed is unexpected behavior.

**Comment by rwoll** [comment]
Sorry you're facing this issue. I'm not sure Playwright will want to support using this plugin; we can probably improve the error messaging around this case if that's the case.

However, can you elaborate why it's helpful to test with SSL locally for the component test?

**Comment by vhscom** [comment]
Thanks for triaging, Ross. SSL may be enabled in the default Vite config as, as a result, could lead to the implementation DX described in OP. Potential usefulness of using SSL for component tests would be environment parity for those using SSL already for dev (for whatever reason). Off the cuff I suppose the best alternative is conditional logic in the primary vite config to disable SSL—which somehow gets picked up and causes this error even when `ctViteConfig` is left undefined in the new/temp config file.

**Comment by rwoll** [comment]
Thanks for the additional info. For now, will it work for you to disable vite SSL plugin while testing (or try setting https://playwright.dev/docs/api/class-testoptions#test-options-ignore-https-errors in your config)?

**Comment by vhscom** [comment]
Tried a few things in config such as `ignoreHTTPSErrors: true,` though the URL for the component testing harness seems to be sticky and the error persists. I'll start thinking about a way to branch the primary vite config after digging into the docs a little more and will need to leave a comment for that one—but worth it in my opinion as so far this new feature is looking great and I'm excited to see it bake into `@playwright/test` after it matures.

**Comment by rwoll** [comment]
>  I'll start thinking about a way to branch the primary vite config

I'm trying something out. If it works, I'll send you a diff.

**Comment by rwoll** [comment]
try the following:

```
npm i cross-env
```

and then modify:


```patch
diff --git a/package.json b/package.json
index 7919797..f38bbe6 100644
--- a/package.json
+++ b/package.json
@@ -13,7 +13,7 @@
     "format": "prettier --write --plugin-search-dir=. .",
     "prepare": "npm run smui-theme",
     "smui-theme": "smui-theme compile static/smui.css -i src/theme",
-    "test-ct": "playwright test -c playwright-ct.config.ts"
+    "test-ct": "cross-env RUNNING_UNDER_PLAYWRIGHT_TEST=1 playwright test -c playwright-ct.config.ts"
   },
   "devDependencies": {
     "@playwright/experimental-ct-svelte": "^1.25.0",
@@ -38,5 +38,8 @@
     "typescript": "^4.7.4",
     "vite": "^3.0.0"
   },
-  "type": "module"
+  "type": "module",
+  "dependencies": {
+    "cross-env": "^7.0.3"
+  }
 }
diff --git a/vite.config.js b/vite.config.js
index 6e45794..8e51833 100644
--- a/vite.config.js
+++ b/vite.config.js
@@ -1,6 +1,10 @@
 import { sveltekit } from '@sveltejs/kit/vite';
 import basicSsl from '@vitejs/plugin-basic-ssl';
 
+const plugins = [sveltekit()];
+if (!process.env.RUNNING_UNDER_PLAYWRIGHT_TEST)
+	plugins.unshift(basicSsl());
+
 /** @type {import('vite').UserConfig} */
 const config = {
 	define: {
@@ -9,7 +13,7 @@ const config = {
 	preview: {
 		https: true
 	},
-	plugins: [basicSsl(), sveltekit()]
+	plugins,
 };
 
 export default config;

```

Does that work for you as a workaround? I couldn't get your tests to actually run regardless of having the plugin or not.

**Comment by vhscom** [comment]
Works purrfectly, Ross. Thank you for the lift! https://github.com/vhscom/playwright-ct-ssl-reduced-test/commit/64a276ffc5d18959c2117ee9f4343f606354fc91. I'm all set and the config looks good.

**Comment by rwoll** [comment]
Sweet—I'm going to assign this a milestone and owner to take a more holistic look to see if there's something we can/should do differently, but at least there's a workaround for you until then! (It may be resolved as Won't Fix, but want another pair of eyes @pavelfeldman)
