### ISSUE TITLE
[doc] running in browser vs. node

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#16479]
There's often a conceptual gap here, and it's worth having a doc about to clarify the boundaries between node vs. browser.

For instance, I see lots of people get frustrated by writing what amounts to:

```ts
const a = 'foo';

await page.evaluate(() => console.log(a))

// vs.

await page.evaluate(a => console.log(a), a)
```

**Comment by mxschmitt** [comment]
Maybe enhance this? https://playwright.dev/docs/evaluating#evaluation-argument

**Comment by rwoll** [comment]
Yes—that looks like the correct place. I wonder if we could lint, too. I.e. produce lint violation if variable from outside the function gets used inside without it appear as arg? Does such a rule already exist?

**Comment by rwoll** [comment]
An image/diagram like we had for Component Tests would likley serve us well here. At the core, the concept is Playwright = Node/Driver <== de(serialization) ==> Browser

**Comment by unlikelyzero** [comment]
This is something our team has struggled with. Any documentation would be greatly appreciated
