### ISSUE TITLE
[Question] Testing "mailto:" anchor tag

### ISSUE THREAD

**Issue by ktakdev** [microsoft/playwright#16487]
I want to test clicking behavior of "mailto" anchor tag  like as follows:
```
<a id="email" href="mailto:test@example.com">Send Email</a>

const emailLink = page.locator("#email");
await emailLink.click();

// detect "mailto"
```
But I couldn't find how to detect "mailto".
Can anyone have solution?

**Comment by rwoll** [comment]
What do you mean by detect in this context?

You can do to simply assert it is there without needing to click it:

```ts
await expect(emailLink).toHaveAttribute("href", /^mailto:/)
```

checking if an external mail client is launched in response is outside the scope of PW.

**Comment by ktakdev** [comment]
I guessed there is an API in browser context to catch kind of "email" event.
If so, I'd be better to use it.
(testing actual behavior seems better than testing attribute)

But in my case, your simple style is enough, just overthought.

Thank you!
