### ISSUE TITLE
While running API script mention in below it shown some error but i have console display, How to handle this error

### ISSUE THREAD

**Issue by AuthithyaK** [microsoft/playwright#16489]
API script :

  await page.route('**/*', async (route) => {
    if ((route.request().url() === "")) {
      console.log(route.request().url());
    
      page.on('response', async (response) => {
      
        response.json().then(ress => ({
          data: ress.data,
        })
        ).then(res => {
          const UIresponseBody =(res.data)
          console.log(UIresponseBody)
          console.log("===================UI-NETWORK(XHR)=========================");
          const resUI = (UIresponseBody[""]);
          console.log(resUI[""]);
          console.log(resUI[""]);
          console.log(resUI[""];
        })
      })
    }
    return route.continue();
  })
Error Message :

response.json: Protocol error (Network.getResponseBody): No resource with given identifier found

37 | page.on('response', async (response) => {
38 |

39 | response.json().then(ress => ({
| ^
40 | data: ress.data,
41 | })
42 | ).then(res => {

**Comment by mxschmitt** [comment]
Can you provide us a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example)? - otherwise we can't act on it.

**Comment by rwoll** [comment]
Closing as part of triage per-above. Please file a new issue with the information requested above, and reference this issue.

A repro will help ensure we are actually debugging the same issue you are facing and will minimize us guessing. This is especially helpful when there are several layers/pieces involved.

Ideally the repro is a GitHub repository we can clone, download, and run to see the issue ourselves. It should include the commands to run it, too.

Thanks!
