### ISSUE TITLE
How do I print title of every suites in custom reporters

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#16498]
Team , I have multiple suites but using custom reporters I am able to print the title of the very first suite not others as i dont find any other way apart from indexing 

like suite.suites[0].suites[0] …….

I just want to print every suite title followed by the test cases inside

**Comment by rwoll** [comment]
You can either work with the flat list, or write a recursive function along the lines of the sample code below. See https://github.com/microsoft/playwright/blob/main/packages/playwright-test/types/testReporter.d.ts for the types involved that you can traverse and recurse.

```ts
import { Reporter, Suite } from '@playwright/test/reporter';

class MyReporter implements Reporter {
  onBegin(config, suite: Suite) {
    // Example 1: Flat List
    for (const test of suite.allTests())
      console.log(test.titlePath());
    
    // Example 2: Recursive Tree
    const print = (suite: Suite, indent: string = '\t') => {
      console.log(indent + suite.title);
      for (const test of suite.tests)
        console.log(indent + '- ' + test.title)
      for (const child of suite.suites)
        print(child, indent + '\t');
    }

    print(suite);
  }
}
export default MyReporter;
```

**Comment by mechandan** [comment]
Thanks for your response but my requirement is like 

suite1 title:
Test case1
Status 
……..


Suite 2 title :
Test case 1
Status……


Don’t we have anything like onSuiteBegin ??

**Comment by rwoll** [comment]
> Don’t we have anything like onSuiteBegin ??

Yes, [`onTestBegin`](https://playwright.dev/docs/api/class-reporter#reporter-on-test-begin). `Suite` beginning is implied by one of its Tests beginning. So, in `onTestBegin`, look at https://playwright.dev/docs/api/class-testcase#test-case-parent etc. to get the Suite it's a part of.

You can use https://github.com/microsoft/playwright/issues/16498#issuecomment-1213470705 to create a set of all the Suites that may be run, and then mark them as running as you see their tests pop up in `onTestBegin`, too.
