### ISSUE TITLE
[BUG] junit XML generates testcase elements with non-unique classname attribute

### ISSUE THREAD

**Issue by bitcoder** [microsoft/playwright#16492]
**Context:**
- Playwright Version: 1.26.0-next
- Operating System: Mac
- Node.js version: 12.6 .0
- Browser: All
- Extra: [any specific details about your environment]

npx: installed 1 in 1.154s

## System:
 - OS: macOS 12.5
 - Memory: 432.82 MB / 16.00 GB
## Binaries:
 - Node: 12.6.0 - ~/.nvm/versions/node/v12.6.0/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 6.14.13 - ~/.nvm/versions/node/v12.6.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 -

**Code Snippet**

sample test:

```javascript
    test('Login with valid credentials', async({ page }, testInfo) => {
       await page.goto('https://example.com/');
    });

```

Expected Junit XML report (after running `npx playwright test`):
```xml
<testcase name="Login validations Login with valid credentials" classname="login.spec.js › Login validations › Login with valid credentials" time="2.226">
...
```

Current Junit XML report (after running `npx playwright test`):
```xml
<testcase name="Login validations Login with valid credentials" classname="login.spec.js:13:5 › Login validations › Login with valid credentials" time="2.226">
...
```

**Describe the bug**

Tools that import JUnit XML, such as well-known test management tools such as Xray and TestRail among other, process the results and identify tests usually based on the `classname` and `name` attributes on the `testcase` element. The original JUnit/surefire projects generated this based on the class name and method name of the underlying test implementation. Therefore, these are assumed to be unique and non-volatile and tools take advantage of this to group the results of multiple runs, track trends, etc.

However, plawright-test generates weak identifiers for the tests stored in the JUnit XML report, that will easily break whenever source code is updated (e.g., lines added/removed).

Whenever  running the tests with playwright-test and the junit reporter, it generates `testcase` elements having non unique identifiers, namelly on the `classname` attribute where the line number and column number are added (e.g.,  ` classname="login.spec.js:13:5 › Login validations › Login with valid credentials"`)

The idea is to remove the line and column numbers (e.g. ":13:5" from  "login.spec.js:13:5 › Login validations › Login with valid credentials" ), making the testcase clearly identifiable, and not prone to change if the line/column numbers change in the source file. This way, external tools that process the Junit XML can always properly identify the same test cases.

**Comment by bitcoder** [comment]
This is implemented on the  [`formatTestTitle` function ](https://github.com/microsoft/playwright/blob/3dc1920ce83b56a408d84e2d43e07ec8976d924d/packages/playwright-test/src/reporters/base.ts#L359) that is used by the [junit reporter ](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/junit.ts#L136) and in other places.
Several options are possible:

1. change the `formatTestTitle` to remove the `:${test.location.line}:${test.location.column}` string; this will impact other places using `formatTestTitle`
2. add an option to `formatTestTitle`, so that the junit reporter can tell it to don't include the source location
3. create a new `formatTestTitle`  on the junit.ts class, tailored for its purpose (i.e., that doesn't include the source location)

Please let me know what you think, and I can quickly make a PR for it

**Comment by bitcoder** [comment]
I've submitted a preliminary PR following approach 2) mentioned above.

> 2\. add an option to `formatTestTitle`, so that the junit reporter can tell it to don't include the source location

**Comment by dgozman** [comment]
@bitcoder Thank you for the issue, I see the problem. Could you please attach a screenshot of how XRay and/or TestRail show the report produced by our junit reporter? I would like to better understand how they surface the `name` vs `classname` attributes.

We've recently introduced [`testCase.id`](https://playwright.dev/docs/api/class-testcase#test-case-id) property that is intended as a "history id", but it's not human-readable. I wonder whether we could leverage it here, because it accounts for all possible situations like `repeatEach` index, multiple projects and similar, while `formatTestTitle` does not.

**Comment by bitcoder** [comment]
Hi @dgozman , so in Xray we internally use the string "<classname>.<name>" as the unique identifier for the Test in Xray; this was based on the way JUnit was thought in java context.
TestRail follows a similar approach (we aligned with the TestRail team on this).
In Xray we have a field to store this kind of id; TestRail also follows a similar approach.
Actually, in TestRail we have a pending tutorial for Playwright because of the issue we're discussing  here :)

Whenever we upload the JUnit XML report (dump ahead), a "Test Execution" will be created.. it's like a entity that groups all the test results being imported. Then, for each `testcase` element on the JUnit XML report, a Test issue will be created, unless an existing one already exists having the same "definition" (think on it as our test id).  

This is the Test Execution containing the two test results, one per each testcase element; each one will be linked to a Test in Jira (that will be either autoprovisioned... or reused).

<img width="1015" alt="image" src="https://user-images.githubusercontent.com/553801/184500976-839ad30d-fcb3-413d-a085-d73b2bc9df45.png">

This is the details of a run for a given Test; here becomes clear that the unique identifier we use (in a field called "Definition")  has the info from the source line/column numbers.. 
<img width="1765" alt="image" src="https://user-images.githubusercontent.com/553801/184500948-a1f1befa-5b30-40af-a757-348734b311dd.png">

So, if we import the same or similar results, these will be linked to the already created Tests... if they have the same "definition"/id. Therefore, if they change in terms of source code line/col numbers..  as these are part ot the `classname`attribute, it will lead to new Tests whenever they're uploaded.

Having said that, the `testCase.id` can be perhaps a good fit.   What is the exact syntax of it? Does it include also the `test.describe(s)`, as I think it may make sense to do so as the test name may not be unique enough?

I can give it a try if you want 

=====
dump used for the screenshots above.
`xml
<testsuites id="" name="" tests="2" failures="0" skipped="0" errors="0" time="2.809">
<testsuite name="login.spec.ts" timestamp="1660404689432" hostname="" tests="2" failures="0" skipped="0" time="2.426" errors="0">
<testcase name="Login validations Login with valid credentials" classname="login.spec.ts:6:5 › Login validations › Login with valid credentials" time="1.466">
</testcase>
<testcase name="Login validations Login with invalid credentials" classname="login.spec.ts:14:5 › Login validations › Login with invalid credentials" time="0.96">
</testcase>
</testsuite>
</testsuites>
`

**Comment by bitcoder** [comment]
From what I just tested, `testCase.id` is a hash. I understand its purpose but I think that using it in this context will remove some transparency and traceability, so end users can quickly identify the code that is linked to the result they're seeing on Xrat/Jira/TestRail.


```
  1) [playwright-test] › reporter-junit.spec.ts:241:6 › should render projects =====================

    Error: expect(received).toContain(expected) // indexOf

    Expected substring: "[project1] › a.test.js › one"
    Received string:    "17c2af56efedce05daab-87f1b7dad98b54d2df7d"

      261 |   expect(xml['testsuites']['testsuite'][0]['$']['skipped']).toBe('0');
      262 |   expect(xml['testsuites']['testsuite'][0]['testcase'][0]['$']['name']).toBe('one');
    > 263 |   expect(xml['testsuites']['testsuite'][0]['testcase'][0]['$']['classname']).toContain('[project1] › a.test.js › one');
          |                                                                              ^
      264 |
      265 |   expect(xml['testsuites']['testsuite'][1]['$']['name']).toBe('a.test.js');
      266 |   expect(xml['testsuites']['testsuite'][1]['$']['tests']).toBe('1');

        at /Users/smsf/exps/playwright/tests/playwright-test/reporter-junit.spec.ts:263:78
```


My suggestion then, would be to stick perhaps with the current logic that  I've implemented on the PR. What do you think?
