### ISSUE TITLE
The batch file cannot be found - slows down execution

### ISSUE THREAD

**Issue by damyanstoychev** [microsoft/playwright#16495]
Hi,

At the company I work for we have our frontend framework automated using Selenium. We are always trying new things out, so we are thinking about switching to Playwright. I am currently testing out TestNG 7.5, Playwright 1.24.1, Java 8 (Eclipse). Everything looks good except... Something that's a big bother to us is that when a test case finishes there's a big wait, probably about a minute. Then a message in the console appears in red "The batch file cannot be found." which is definitely PW related.  Just to note we have some permission issues so we have to skip the chromium download and we use the files from our chrome browsers to run test cases.

Do you guys have any idea why are we having this huge delay in the end of each test case, I read that the message is related to files that are supposed to be deleted but missing but that's all.

Thank you,

**Comment by rwoll** [comment]
Closing as part of triage per-above. Please file a new issue with a repro, and reference this issue.

A repro will help ensure we are actually debugging the same issue you are facing and will minimize us guessing. This is especially helpful when there are several layers/pieces involved.

Ideally the repro is a GitHub repository we can clone, download, and run to see the issue ourselves. It should include the commands to run it, too.

Thanks!
