### ISSUE TITLE
[Question] Can I save the text of codegen to a file?

### ISSUE THREAD

**Issue by tachish** [microsoft/playwright#16493]
For more details:
As for the trace, I can set the option to save as a file:

```
await context.tracing.start({ screenshots: true, snapshots: true });
const page = await context.newPage();
await page.goto('https://playwright.dev');
await context.tracing.stop({ path: 'trace.zip' });
```

Is there any way for me to save the text of codegen as a file?
If not, It will be possible to use like the following in the future?
`
page.pause({ path: '' })
`

**Comment by ltsuda** [comment]
See if this helps

`npx playwright codegen www.google.com -o test.spec.js`

I didn't find any reference to this options in the docs anymore, I don't know if it got removed or it's too deep in the page.

**Comment by rwoll** [comment]
Output is still supported and documented in the CLI `--help` command:

```
$ npx playwright codegen --help
Usage: npx playwright codegen [options] [url]

open page and generate code for user actions

Options:
  -o, --output <file name>        saves the generated script to a file
```

@tachshish Does this work for you or are you approaching it from a different angle? 

Additionally, the latest version of our [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) will allow you to generate the lines directly into your VSCode editor.

**Comment by tachish** [comment]
> Thanks for reply! What I wanna implement is actually the codegen command in CLI, but I notice that codegen command use a private method `_enableRecorder` to set the output file. I'm not sure it's appropriate to use the method directly in my project~  Is there any official recommendation?

**Comment by rwoll** [comment]
You can use it at your own risk, but it's not documented as an external/public API so it could break in the future without warning. Can you elaborate more on your use case and what you are building?

**Comment by tachish** [comment]
Actually, the background is the inspector invoked by ` page.pause() ` only supports to copy the generated code. So, I'm thinking  if it's possible to save the generated code to a file. In that case, I could upload the file and build an automatic test service using the generated code.

Furthermore, I need to use script to resolve SSO(single sign on) and other tasks first. So, directly use the command like `  npx playwright codegen www.google.com -o test.spec.js ` is not appropriate I think.

**Comment by aslushnikov** [comment]
Hey @tachish, I'm triaging issues this week so taking over from Ross!

> Actually, the background is the inspector invoked by page.pause() only supports to copy the generated code. So, I'm thinking if it's possible to save the generated code to a file. In that case, I could upload the file and build an automatic test service using the generated code.

Programmatic access to generated code is not possible at the moment; let me bring this up on the team meeting to gauge interest.

**Comment by tachish** [comment]
Thanks for reply! Looking forward to the outcome of the discussion～

**Comment by aslushnikov** [comment]
@tachish We recently released a new VSCode extension that lets you start "codegenning" from wherever you are. Would it work for you? And let us know what is missing!

**Comment by tachish** [comment]
Great! I will try it recently!

**Comment by Sriram-Kumar1** [comment]
> @tachish We recently released a new VSCode extension that lets you start "codegenning" from wherever you are. Would it work for you? And let us know what is missing!

can we get the name of the plugin @aslushnukov?. i see there are a number of plugins in Vscode.

**Comment by aslushnikov** [comment]
This one: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright

**Comment by aslushnikov** [comment]
Closing as per above! Feel free to file new issues if things don't work!

**Comment by aslushnikov** [comment]
Closing as per above! Feel free to file new issues if things don't work!

**Comment by tachish** [comment]
I tried the extension! I think the extension is perfect for me~
