### ISSUE TITLE
Looks like Playwright Test or Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers:              ║ ║                                                                         ║ ║     npx playwright install                                              ║ ║                                                                         ║ ║ <3 Playwright Team   [Question]

### ISSUE THREAD

**Issue by noumanshahid12** [microsoft/playwright#16506]
How can i fix it ?

**Comment by rwoll** [comment]
Does running `npx playwright install` from the error message fix it, or do you run that and then it gives you the error the next time, too?

**Comment by noumanshahid12** [comment]
> Does running `npx playwright install` from the error message fix it, or do you run that and then it gives you the error the next time, too?

But it's not work

**Comment by rwoll** [comment]
Can you share the commands you run, which directory you run them in, and the contents of your package.json and package-lock.json?

Thanks!

**Comment by noumanshahid12** [comment]
> Can you share the commands you run, which directory you run them in, and the contents of your package.json and package-lock.json?
> 
> Thanks!

PS C:\Users\User\Errors> npx playwright test adminLogin.test.ts
Please install @playwright/test package to use Playwright Test.
PS C:\Users\User\Errors> npm install -D @playwright/test

added 3 packages, and audited 4 packages in 20s

found 0 vulnerabilities
PS C:\Users\User\Errors> npx playwright test adminLogin.test.ts

Running 0 tests using 0 workers

Error: ArrayEngagementApp\AdminLogin\adminLogin.test.ts:15:12: Playwright Test did not expect test.describe() to be called here.
Most common reasons include:
- You are calling test.describe() in a configuration file.
- You are calling test.describe() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependenices in your package.json depends on @playwright/test.

   at ArrayEngagementApp\node_modules\@playwright\test\lib\util.js:221

  219 |
  220 | function errorWithLocation(location, message) {
> 221 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  222 | }
  223 |
  224 | function expectTypes(receiver, types, matcherName) {

    at errorWithLocation (C:\Users\User\Errors\ArrayEngagementApp\node_modules\@playwright\test\lib\util.js:221:10)
    at TestTypeImpl._ensureCurrentSuite (C:\Users\User\Errors\ArrayEngagementApp\node_modules\@playwright\test\lib\testType.js:79:41)
    at TestTypeImpl._describe (C:\Users\User\Errors\ArrayEngagementApp\node_modules\@playwright\test\lib\testType.js:106:24)
    at Function.describe (C:\Users\User\Errors\ArrayEngagementApp\node_modules\@playwright\test\lib\transform.js:269:12)
    at Object.<anonymous> (C:\Users\User\Errors\ArrayEngagementApp\AdminLogin\adminLogin.test.ts:15:12)
=================
 no tests found.
=================


  1 error was not a part of any test, see above for details
PS C:\Users\User\Errors>

**Comment by rwoll** [comment]
What directory are your package.json and package-lock.json in?

**Comment by noumanshahid12** [comment]
> What directory are your package.json and package-lock.json in?

pakage.json

**Comment by aslushnikov** [comment]
@noumanshahid12 i don't think we have enough details here, and it looks like the discussion got us into a place where we can't act upon this.

Could you please re-file this bug, but this time with a small demo repository that has your code that illustrates the issue?

Thanks!

**Comment by noumanshahid12** [comment]
> @noumanshahid12 i don't think we have enough details here, and it looks like the discussion got us into a place where we can't act upon this.
> 
> Could you please re-file this bug, but this time with a small demo repository that has your code that illustrates the issue?
> 
> Thanks!

Issue Resolve Thanks
npm i -D playwright

**Comment by sharath2106** [comment]
I'm facing this issue. Has someone resolved this before? @noumanshahid12 @aslushnikov

**Comment by test20161010** [comment]
I don't have this problem on my computer.
But it does on a colleague's computer.
The cause is that the following directory does not exist
after `npm install` with package.json.

C:\Users\username\AppData\Local\ms-playwright\chromium-1064

However, when he installed it with `npm install` before,
the following directory was created
and was able to use the test at that time.

C:\Users\username\AppData\Local\ms-playwright\chromium-1028

**Comment by rob4629** [comment]
Although I'm able to resolve this using `npx install playwright`, my understanding is I shouldn't do this given the [Breaking Changes of v1.34](Looks like Playwright Test or Playwright was just installed or updated.)
> `npx playwright test` no longer works if you install both `playwright` and `@playwright/test`. There's no need to install both, since you can always import browser automation APIs from `@playwright/test` directly

**Comment by konflic** [comment]
Same here. Playwright was installed, but that message appears during the tests. Python 1.35.0 that is obviously some king of bug.

**Comment by pfftdammitchris** [comment]
The error can occur when installing with ``npx playwright install in a nested directory and then running `npx playwright install` again in the root directory (in monorepo)

**Comment by rapattonimusic** [comment]
> Although I'm able to resolve this using `npx install playwright`, my understanding is I shouldn't do this given the [Breaking Changes of v1.34](Looks like Playwright Test or Playwright was just installed or updated.)
> 
> > `npx playwright test` no longer works if you install both `playwright` and `@playwright/test`. There's no need to install both, since you can always import browser automation APIs from `@playwright/test` directly

The way I fixed this is pinning both `playwright` and `@playwright/test` to a specific version. And the trick is to omit the ^character from in front of the version. So for instance `"@playwright/test": "1.38.0"`

**Comment by thebsv** [comment]
Hello all, I fixed this by just running `sudo playwright install` ; for some reason it needed sudo privileges

**Comment by mklueh** [comment]
I was running into the same issue after I've upgraded playwright dependencies.

To make use of the CI cache, I was using

>  run: npx playwright install-deps

and it seems the dependency upgrade has invalidated those caches

need to revert back to

> run: npx playwright install

at least once, till the next upgrade or keep it that way, not using the cache at all...

**Comment by alexprudhomme** [comment]
> The error can occur when installing with `npx playwright install` in a nested directory and then running `npx playwright install` again in the root directory (in monorepo)

Thank you so much ! Need to specify the `working-directory` when installing if you have multiple projects with playwright.

**Comment by KirubaBabu** [comment]
I am installing Playwright via requirements.txt in an Azure WebApp. How can I avoid reinstalling Playwright each time by running playwright install? Alternatively, is there a way to execute this command automatically?"

**Comment by alfasin** [comment]
Why was this issue closed?
This issue keeps happening on one of my production instances!

I worked around it by putting: `yarn playwright install` on my installation script (CI/CD - runs on every deploy) but this is an ugly workaround that doesn't address the *real* problem!

**Comment by Gamewise** [comment]
Getting this issue too :(

**Comment by Tamir198** [comment]
For those who got it and cant fix it - try to remove your node modules + pnpm-lock file then re install everything. 
This is what solved the problem for me

**Comment by everysundays** [comment]
The Playwright MCP server is outdated and looking for version 1179, but the latest install downloaded version 1181. This is an issue with the MCP server itself.

**Comment by bhagwatn** [comment]
- I am getting the same error, I am using Pycharm, Python, Playwright, Robot Framework and also Browser Library of Robot Framework. 
- How do it fix this issue - please help. 
- BrowserType.launch: Executable doesn't exist at ~\PycharmProjects\RobotAug19\.venv\Lib\site-packages\playwright\driver\package\.local-browsers\chromium-1187\chrome-win\chrome.exe
- 
╔════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.       ║
║ Please run the following command to download new browsers: ║
║                                                            ║
║     playwright install                                     ║
║                                                            ║
║ <3 Playwright Team
