### ISSUE TITLE
[BUG] context.close don't work as expected in headless = false and close all opened contexts

### ISSUE THREAD

**Issue by 21febbraio** [microsoft/playwright#16500]
- Playwright Version: 1.25.0
- Operating System: windows 10
- Node.js version: v16.13.2
- Browser:  Chromium
my tests use mocha to run since when I started this project, playwright didn't had such a util

Hi playwright community, after upgrading from 1.18. to 1.25 , my tests broke when closing a context , let me explain:
If i run my tests with headless: false the instruction "await context.close()" don't close the browser page immediatly , it hangs out for some seconds , meanwhile other instructions get executed and suddenly after 2 seconds all context get closed , it happen in all of my project wich is quite big. To note that if i run my tests in headless all works fine , i tried also to get back to 1.18 but the issue doesn't solve. Any idea ?
Ive also builted a specific test to prove it:

![image](https://user-images.githubusercontent.com/51358213/184380393-930c3568-1341-48e8-91ba-fe078a4ee020.png)

**Comment by mxschmitt** [comment]
We need a [minimal reproduction ](https://stackoverflow.com/help/minimal-reproducible-example) on act on this, also we recommend our [own Test Runner](https://playwright.dev/docs/intro) instead which takes care of context creation / closing and browser re-use.

**Comment by rwoll** [comment]
Closing as part of triage per-above. Please file a new issue with the information requested above, and reference this issue.

A repro will help ensure we are actually debugging the same issue you are facing and will minimize us guessing. This is especially helpful when there are several layers/pieces involved.

Ideally the repro is a GitHub repository we can clone, download, and run to see the issue ourselves. It should include the commands to run it, too.

Thanks!
