### ISSUE TITLE
How do we add extension using launchPersistentContext in Java ?

### ISSUE THREAD

**Issue by bibinmohana** [microsoft/playwright#16501]
I  couldn't find the documentation for the same in java. I tried adding user directory path to launchPersistenTContext , but facing below issues.

BrowserContext browser=playwright.chromium().launchPersistentContext(directorypath).
When directory path is initialized as a string it is not accepting , it requires a path variable. When tried initializing as path  as shown below, its throwing an error at  c "invalid character constant" . 

Path filename='c:\\users\\directory'
Path filename='c:\users\directory'
Path filename='c://users//directory'
Path filename='c:/users/directory'

Please let me now your thought .

Thanks for the support!

**Comment by rwoll** [comment]
This looks like a Java syntax error, and not a PW error. single quotes `'` are for _character constants_, while double quotes `"` are for strings.

See samples of using Java Paths here: https://www.geeksforgeeks.org/java-nio-file-paths-class-in-java/

**Comment by bibinmohana** [comment]
Thanks for the quick response !
