### ISSUE TITLE
Extension not getting loaded with playwright Java

### ISSUE THREAD

**Issue by bibinmohana** [microsoft/playwright#16516]
Please find code I tried .

Playwright playwright= Playwight.create();
LaunchPersistentContextOptions lp= new LaunchPersistentContextOptions();
lp.setChannel("chrome")
lp.setHeadless(false)

Path path=(path)Paths.get("C:", "User Data");
BrowserContext browser=playwright.chromium.launchPresistentContext(path,lp)
Page page=browser.newPage()
page.navigate("url")
---------- 

Browser is getting launched , but extension which is there in the user data session is not getting loaded.

Any issue with the above approach ?  Please share your thoughts ..

Thanks in advance :)

**Comment by bibinmohana** [comment]
I even tried adding providing the extension  path as array list

Playwright playwright= Playwight.create();

Path extpath = Paths.get("c:\\extension")
List<String> chromeArgs = new ArrayList<>(); chromeArgs.add("--disable-background-timer-throttling"); chromeArgs.add("--disable-backgrounding-occluded-windows"); chromeArgs.add("--disable-renderer-backgrounding"); chromeArgs.add("--no-sandbox"); chromeArgs.add("--disable-setuid-sandbox"); chromeArgs.add("--disable-dev-shm-usage"); chromeArgs.add("--disable-extensions-except=" + extensionPath); chromeArgs.add("--load-extension=" +extensionPath);

LaunchPersistentContextOptions lp= new LaunchPersistentContextOptions();

lp.setChannel("chrome")
lp.setHeadless(false)
lp.args=chromeArgs

Path path=(path)Paths.get("C:", "User Data");
BrowserContext browser=playwright.chromium.launchPresistentContext(path,lp)
Page page=browser.newPage()
page.navigate("url")


But still its just launching thebbrowser with url , extensions are not getting loaded . Any idea on the same ?

**Comment by bibinmohana** [comment]
This worked fie when i added the below code.
chromeArgs.add(--disable-extensions-except="+extpath);

This can be closed !  Thanks

**Comment by ankitY1997** [comment]
hey i just wanted to know you are taking Path path=(path)Paths.get("C:", "User Data");  what is the meaning of this argument  ("C:", "User Data")  here what i have to pass ?

**Comment by coarsehorse** [comment]
> hey i just wanted to know you are taking Path path=(path)Paths.get("C:", "User Data"); what is the meaning of this argument ("C:", "User Data") here what i have to pass ?

It's just a Windows path to the user's data folder: "C:\User Data"
