### ISSUE TITLE
[Feature] Utilities/Fixtures for OIDC Authentication

### ISSUE THREAD

**Issue by chrstophr-wltrs** [microsoft/playwright#16511]
Hi! 👋 I think it would be handy if Playwright had fixtures or some other utility for true-headless OpenID Connect (OIDC) authentication. OIDC is kind of the standard for authentication of web applications, especially at the enterprise level. If you're not already familiar with OIDC, an excellent guide can be found [here](https://www.youtube.com/watch?v=t18YB3xDfXI).

I've been attempting to implement a system in my current project that can authenticate a browser context using one or more of the various OIDC authentication flows in a truly headless manner (meaning that everything is done with API calls, rather than being restricted by the rendering capabilities of the browser itself, where I need to wait for the browser to render each redirected page before proceeding), but I've found that the process is fairly tedious, where I need to make every API call using an APIRequestContext on my own, researching the correct URLs for my particular app at each stage.

This is, of course, a fairly common problem, and many people have created libraries to simplify the process of OIDC authentication. Two such libraries that come to mind are [`oidc-client-ts`](https://github.com/authts/oidc-client-ts) and [`node-openid-client`](https://github.com/panva/node-openid-client/blob/main/docs/README.md), although both of these libraries are designed to aid with the implementation of OIDC Authentication as part of an application, rather than facilitating End-to-End testing _of_ an application which uses OIDC.

If simplifying the OIDC process seems like it would be advantageous to Playwright, the source code for those libraries I mentioned above might be a good starting place to examine for inspiration. It could end up being something of an undertaking, so I totally understand if it's deemed out-of-scope for the time being.

Thanks for reading and good luck!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
