### ISSUE TITLE
[Feature] When Recording Is Set, Audio Should Be Captured

### ISSUE THREAD

**Issue by y0utubeperson1** [microsoft/playwright#16526]
Playwright allows you to record video: https://playwright.dev/docs/videos

But I wish for an option to also record the browsers audio. 

This is useful to ensure in our tests that the video players are acting correctly and the audio can be clearly heard when running its test. It would help in scenarios where Playwright is being ran in an pipeline such as GitHub Actions where we can see the end result in a Github Actions Artifact [a.k.a this: https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts ]

It should capture all audio from the browser [not PC audio]

Currently, there is no way to test this.

**Comment by aslushnikov** [comment]
@y0utubeperson1 This has been discussed before as part of the https://github.com/microsoft/playwright/issues/4870 and was considered outside of the project scope for now.

**Comment by hexabyte23** [comment]
I understand args of ffmpeg must be modified in file videoRecorder.js line 104 to properly handle audio recording

`    const args = `-loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i - -y -an -r ${fps} -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=${w}:${h}:0:0:gray,crop=${w}:${h}:0:0`.split(' ');`

**Comment by ricardowiseverge** [comment]
@hexabyte23 any insights on your research? Trying to understand how to make the same use case working

**Comment by hexabyte23** [comment]
I figure out that anybody is expected that kind of enhancement, but as Microsoft refuse too take in account, we need a ffmpeg specialist...
