### ISSUE TITLE
[BUG] Having a hash symbol in a tag breaks eval and .content()

### ISSUE THREAD

**Issue by scdev0** [microsoft/playwright#16529]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows
- Node.js version: 14.17.3
- Browser: chromium, firefox, webkit

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

const minHTML = `
<html>
    <body>
        <table>
            <tbody>
                <tr #>
                    <td>
                        Table data in first row
                    </td>
                </tr>
                <tr>
                    <td>
                        Table data in second row
                    </td>
                </tr>
            </tbody>
        </table>
    </body>
</html>`;

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(`data:text/html,${minHTML}`);

  console.log(await page.content());
})();
```

**Describe the bug**
This logs out:
```
<html><head></head><body>
    <table>
        <tbody>
            </tbody></table></body></html>
```
But if I remove the '#' in the first `tr` tag then it works as expected.
This can be reproduced by having the '#' in other tags as well. I ran into this when the html had <svg><use xlink:href="...#..."></use></svg> and narrowed it down to the hash symbol.

**Comment by scdev0** [comment]
It might be the `await page.goto(data:text/html,${minHTML});` that's the issue because if I replace it with `await page.setContent(minHTML);` then the `page.content()` outputs fine.

**Comment by aslushnikov** [comment]
> It might be the await page.goto(data:text/html,${minHTML}); that's the issue because if I replace it with await page.setContent(minHTML); then the page.content() outputs fine.

@scdev0 Yep, this is precisely the issue; `#` in URLs are treated as anchors so you'll need to escape it.

I'll close this since you have a proper fix for the issue! A rule of thumb is to avoid navigating to data URLs and use `page.setContent()` instead.

**Comment by scdev0** [comment]
How can I fix it when using `page.goto(URL)` if the URL page has `#` in its HTML? The page I goto has bunch of `<svg><use xlink:href="...#..."></use></svg>`
