### ISSUE TITLE
[BUG] Set proxy for Firefox Profile not affect

### ISSUE THREAD

**Issue by nguyenthanhtien** [microsoft/playwright#16523]
**Context:**
- Playwright Version:     "@playwright/test": "1.25.0"
- Operating System: Windows
- Node.js version:  v16.14.0
- Browser: Firefox
- Extra: [any specific details about your environment]

I want set proxy for specific user Firefox Profile, but when we using code below, it's not affect change proxy of firefox browser.
How many way can workaround. Please help give some solution?

```javascript
        const proxyServer = `http://154.32.33.55:5567`;
        const launchOptions = {
            proxy: {
                server: proxyServer,
                username: 'test',
                password: 'test',
            },
            headless: false
        };
        const browser = await firefox.launchPersistentContext(process.env.PROFILE_DIR + data[0].browserId, launchOptions);
        const page1 = await browser.newPage();
```

**Describe the bug**

**Comment by aslushnikov** [comment]
@nguyenthanhtien I was not able to repro this. I tried the following:

1. Launch docker with mitm proxy: `docker run --rm -p 8080:8080 -it mitmproxy/mitmproxy`
2. Launch the following script:

    ```js
    import { firefox } from '@playwright/test';

    const context = await firefox.launchPersistentContext('./ooo', {
      proxy: {
        server: 'http://127.0.0.1:8080',
      },
      headless: false,
    });
    const page = context.pages()[0];
    await page.goto('http://neverssl.com');
    ```
3. In an opened browser, try to navigate to any URL
4. Notice a log in the mitm terminal UI that browser actually uses the proxy to navigate.
