### ISSUE TITLE
[BUG] undefined: TypeError: Right side of assignment cannot be destructured (component with redux store)

### ISSUE THREAD

**Issue by heikergil** [microsoft/playwright#16524]
**Context:**
## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 25.56 GB / 31.07 GB
 - Container: Yes
## Binaries:
 - Node: 17.9.0 - ~/.nvm/versions/node/v17.9.0/bin/node
 - npm: 8.13.2 - ~/.nvm/versions/node/v17.9.0/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.25.0 => 1.25.0 

Cart.jsx (simplified)
```typescript  
import React from 'react';
import { useSelector } from 'react-redux';

const Cart = () => {
	const rootUrl = useSelector(state => state.shop.routes.root_url);
	const isCanada = useSelector(state => state.cart.localization.country) === 'Canada';
	const price = useSelector(state => state.cart.total_price);

	return (
		...
	);
};

export default Cart;
``` 

CartWrapper.jsx
```typescript  
import configureAppStore from '../../stores/cartStore';
import Cart from './Cart';
import { Provider } from 'react-redux';
import React from 'react'

const CartWrapper = () => {
	return (
		<Provider store={configureAppStore(window.pageContext)}>
			<Cart />
		</Provider>
	);
};

export default CartWrapper;
``` 
Cart.spec.tsx
```typescript  
import { test, expect } from '@playwright/experimental-ct-react';
import CartWrapper from './CartWrapper';
import React from 'react'


test('should render', async ({ mount }) => {
	const component = await mount(<CartWrapper></CartWrapper>);
	await expect(component).toBeVisible();
});
``` 

I'm trying to follow the instruction on [#15325](https://github.com/microsoft/playwright/issues/15325#issue-1292005300) for testing a component with a redux store, so far the example on  [#15325](https://github.com/microsoft/playwright/issues/15325#issue-1292005300) works but if I tried to implement the solution with my own component as the coded above I get this error

![Screenshot from 2022-08-13 11-43-37](https://user-images.githubusercontent.com/36630350/184503522-dd131ace-66c5-463b-99fe-021151cf127d.png)

**Comment by aslushnikov** [comment]
cc'ing @pavelfeldman

**Comment by pavelfeldman** [comment]
The problem here is that the error message is erroneously showing the stack frame that contains the test, while the error is actually on some other stack frame. You can try installing `@playwright/experimental-ct-react@next` where this problem is already fixed, or you can wrap your call to `mount` with try/catch and print the exception. It should point at the component internals where the right-side destructuring is taking place.

**Comment by heikergil** [comment]
Hi I tried what you suggested this way

```
	const mountComponent = async () => {
		try {
			const component = await mount(<CartWrapper></CartWrapper>);
			console.log(component)
			return component
		} catch (error) {
			console.log(error)
		}
	}
```
I'm getting this result, the error is pointing to the test file, what am I doing wrong?

![Screenshot from 2022-08-16 15-41-19](https://user-images.githubusercontent.com/36630350/184981572-ef48c9aa-b0ea-4101-bdcd-c51938b672d8.png)

**Comment by aslushnikov** [comment]
@heikergil a few things:

1. could you please try insatlling `@playwright/experimental-ct-react@next` and see if it fixes things?
2. if it doesn't fix, could you please do a simple demo repository that illustrates the issue? This would help us reproduce it locally and debug it

**Comment by aslushnikov** [comment]
My triaging rotation is over; please feel free to file a new issue if you think we still can be helpful!
