### ISSUE TITLE
Is it possible to load extension in firefox  playwright -  Java (getting loaded using xpi , but value of extension not reflecting)

### ISSUE THREAD

**Issue by bibinmohana** [microsoft/playwright#16544]
I have tried using xpi file as given below

Path extpath= Paths.get("xpi path");
Args.add("disable-extensions-except="+extpath)
Args.add("--load-extension="+extpath)
Path profilepath=Paths.get(profile path)
BrowserContext browser=playwright.firefox().launchPersistentContext(path,lp)
Page page= browser.pages.get(0)
page.navigate("url")

While running am getting a "popup whether to add the extension " upon clicking ok manually its getting added , but the value for the extension is not getting fetched from profile.

Is there any way to fix this issue ?

**Comment by aslushnikov** [comment]
I don't think it is possible to run an extension in Firefox rn; please upvote https://github.com/microsoft/playwright/issues/7297 to receive updates!

**Comment by bibinmohana** [comment]
> I don't think it is possible to run an extension in Firefox rn; please upvote https://github.com/microsoft/playwright/issues/7297 to receive updates!

Thanks for the update .. I tried changing the above code in such a way that , instead of pointing to xpi file i gave the extension folder path in the profile directory , and its started loading extension but its loading in Nightly not in actual forefox is that the issue ?

**Comment by kilted-andres** [comment]
hey @bibinmohana 
could you share functional your javascript or typescript code here?
