### ISSUE TITLE
[Feature] Command events/hooks

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1654]
Hi there. First of all v0.12 is looking really great. Thank you for all the work you've been doing!

The feature I'm interested in is events or hooks that indicate that a command is starting or finishing. Ideally the command name and arguments would be exposed.

My use case: I'm writing end-to-end tests, and I want to display a command log via stdout for faster debugging (ignore the `[object Object]` part).
<img width="497" alt="Screen Shot 2020-04-03 at 12 21 43 PM" src="https://user-images.githubusercontent.com/750809/78383051-c85fda00-75a5-11ea-88d9-2eb982550653.png">

I have gotten this to work by monkey-patching my `page` instance and decorating some built-in methods like this.

```js
const method = page.click;

page.click = (...args: any[]) => {
  return commandLogger.log(page, () => method.apply(page, args), 'click', args);
};
```

But it would be nice to have a cleaner way of accomplishing this. :) Let me know what you think!

**Comment by pavelfeldman** [comment]
You could try setting the `DEBUG=pw:api` environment variable for a variation of this. But I think we could also expose a hook for you to specify your own sink for these log messages.

**Comment by celeryclub** [comment]
Ah great point. I do think it would be nice to have a bit more control over what gets logged though as that's quite verbose and not all of it is useful to the average developer.

**Comment by aslushnikov** [comment]
There's now a [`Logger`](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=class-logger) that you can specify for the [browser](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-logger), [browsercontext](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsernewcontextoptions--options-logger) or [page](https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsernewpageoptions--options-logger). This is pretty low-level, but should give enough control!
