### ISSUE TITLE
[Question] Is it possible to view the location of a mouse click in the debugger / inspector?

### ISSUE THREAD

**Issue by vomc** [microsoft/playwright#16546]
I have a super rare edge case where I need to do a test on a Mapbox canvas and click on something based on location, i.e. `await page.mouse.click(215, 289)`

The problem is that I don't know the exact position of the canvas element that I need to click on, so I need a way to view where a click at say 215, 289 actually took place on the page. In cypress this is quite simple, you can trigger the `click` command just like Playwright and then the debugger will show you where that click took place by rendering a red dot at the location. This makes it quite simple to using basic trial and error ensure you are at the exact location: https://docs.cypress.io/api/commands/click

Is something like that also possible in Playwright, i.e. provide a debug view in which you can see the location of a given click?

**Comment by vomc** [comment]
Ah! nvm, I found it, so I guess if you turn on 'record' in the debugger you see what took place.

**Comment by aslushnikov** [comment]
@vomc [Trace Viewer](https://playwright.dev/docs/next/trace-viewer) shows click location - would this work for you?

**Comment by vomc** [comment]
> @vomc [Trace Viewer](https://playwright.dev/docs/next/trace-viewer) shows click location - would this work for you?

Hi @aslushnikov  - thanks for responding so quickly! Could you show me an example? For me when I look through the trace I can scrub to the timeline where the click event happened like this:
<img width="136" alt="Screen Shot 2022-08-16 at 09 17 37" src="https://user-images.githubusercontent.com/78635/184820652-4427bc81-6910-4484-a77d-b2c176289e14.png">

However in the screenshot that shows up below (not shown here for confidentiality reasons), I cannot see any mouse click or any changes. How does the click location render for you? Do you actually see a dot or something?

**Comment by aslushnikov** [comment]
@vomc you should select a click action in the [actions](https://playwright.dev/docs/next/trace-viewer#actions) panel; then it'll show a red dot in the DOM snapshot:

![image](https://user-images.githubusercontent.com/746130/184838620-6f721de9-26b4-4bab-87a2-925a09334a4e.png)

**Comment by vomc** [comment]
> @vomc you should select a click action in the [actions](https://playwright.dev/docs/next/trace-viewer#actions) panel; then it'll show a red dot in the DOM snapshot:
> 
> ![image](https://user-images.githubusercontent.com/746130/184838620-6f721de9-26b4-4bab-87a2-925a09334a4e.png)

I can confirm that this is not working for me in the version of playwright that I listed above. I have the `snapshots` and `screenshot` and `trace` all options on, yet when I view the trace in the browser, I get to the click action and see that it took place as per my screenshot, however the browser window that is shown does not show the click location.

**Comment by aslushnikov** [comment]
@vomc this looks like a bug then. Can you share your trace with me?

**Comment by vomc** [comment]
> @vomc this looks like a bug then. Can you share your trace with me?

hmmm I am not sure because this is on our internal product, so likely not but I can (when I find the time) try to reproduce it. In a nutshell the HTML canvas element in question is a MapboxGL map rendered in a react app. I would assume that if the canvas element is the problem it would be simple to write a quick mock file in which a static html page is set up that includes a mapboxGL map and a click is done at some point that is within that canvas element.

**Comment by aslushnikov** [comment]
> hmmm I am not sure because this is on our internal product, so likely not but I can (when I find the time) try to build something to reproduce it.

@vomc This would be very helpful and probably the only way we can proceed further.

Let me close this for now, please file a new issue with the repro so that we get back to it!

**Comment by rajveer28** [comment]
@vomc you can use: npx playwright codegen
it will find you location where you want to click.. this make things easier with playwright

**Comment by yjbdsky** [comment]
用page.locator("xxx").click()会显示红点，但用page.mouse.click(1010, 212)不会显示红点
