### ISSUE TITLE
[Feature] Custom methods on `Page`

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1655]
Hey team. Got a feature suggestion here. I know Playwright is a general-purpose browser automation tool and not specifically an end-to-end testing tool, but I wonder if any thought has been given to a way to add custom methods to the `Page` class. This can be very useful in providing creating methods like this one (pseudocode).

```js
async function waitForVisible(selector) {
  return this.waitForSelector(selector, { waitFor: 'visible' });
}

await page.waitForVisible('.e2e-button');
```

This can be accomplished in the current version of Playwright, but the usage isn't as seamless since you need to pass `page` as an argument, unlike with built-in methods.
```js
await waitForVisible(page, '.e2e-button');
```

Similar to https://github.com/microsoft/playwright/issues/1654, I've been able to get this to work by monkey-patching my `page` instance, but I wonder if there could be a cleaner way to do this.

Thanks for taking a look!

**Comment by pavelfeldman** [comment]
> I know Playwright is a general-purpose browser automation tool and not specifically an end-to-end testing tool

We actually focus on the end-to-end testing,  so if some of the defaults are off (such as `attached` vs `visible` here), we should fix them. Could you share more on when you need to call `waitForVisible`? Input actions should be doing most of the waiting for you, so it should not be needed that often.

**Comment by celeryclub** [comment]
Ah right. Even better. :)

Well, I see your point about `waitForVisible` maybe not being needed. Maybe that's not the best example - let me show you another method I created to monkey-patch in.

```js
getAttribute: async function(selector: string, attribute: string): Promise<string | null> {
  await this.waitForVisible(selector);
  return this.$eval(selector, (element, attribute) => element.getAttribute(attribute), attribute);
}
```

I've created several of these - they're just intended to make a slightly cleaner API in test files. A couple more examples:

```js
clickAndUploadFile: async function(this: Page, selector: string, file: string): Promise<void> {
  this.on('filechooser', async ({ element }) => {
    await element.setInputFiles(file);
  });

  await this.waitForVisible(selector);
  return this.click(selector);
}
```

```js
getTextContent: async function(this: Page, selector: string): Promise<string | null> {
  await this.waitForVisible(selector);
  return this.$eval(selector, (element) => element.textContent);
},
```

**Comment by pavelfeldman** [comment]
Got it. I hate to derail the original request of making the API extensible, but these all look super useful and generic, so I would much rather bake them into the core api 🤷‍♂. Could we repurpose this request to collect more of those? Having a larger set would give us a better idea on how to approach extensibility.

We've been thinking about the lazy selectors that would resolve upon availability so that you could basically map the entirely of the `ElementHandle` API to `Page`:
```
await page.$wait(selector).eval(e => e.textContent())
```
But for the ones you bring up above, we don't event have convenience methods on the `ElementHandle` itself. We should totally bring the `textContent`, `innerText`, `getAttribute` and maybe the smartness of the `clickAndSelectFiles` there. Then you would get

```
await page.$wait(selector).textContent();
await page.$wait(selector).getAttribute(name);
await page.$wait(selector).clickAndSelectFiles([file]);
```

**Comment by celeryclub** [comment]
No worries! I'm fine with that. I can always open another issue later if I need to. :)

I really like the idea of a method that lazily returns an `ElementHandle`. Seems very intuitive.

Here are the ones I have currently in my codebase:
`clickAndGetPopup(selector)` (uses `waitForEvent('popup')` to return new `Page` instance)
`clickAndUploadFile(selector, file)`
`getAttribute(selector, attribute)`
`getTextContent(selector)`
`waitForVisible(selector)`
`waitForHidden(selector)`
`scrollAndWaitForMoreOf(selector, scrollX, scrollY)` (used to test infinite scrolling behavior - checks that the element count increases)

I may think of more later, but that's all I've got so far.

I'd also be interested in seeing qawolf's `scroll` helper make it into core, as I've found it quite useful. It makes scrolling a lot more intuitive too since it waits for the element/page to be scrollable before continuing or failing.
https://github.com/qawolf/qawolf/blob/master/src/utils/page/scroll.ts

**Comment by zeevrosental** [comment]
@pavelfeldman

if i might add my 2 cents :-)

I think the original request is still a solid one,
For example: if I create complicated components in my react app.(special trees for example)
if I create a test suite for my react page I would like to create special function to test my own components.(to make the test code simplified)

usage example:
page.getTree(); //to return an object that represents the whole tree 
page.rightClickTreeElement(elementIdentifier); // to click on an element with specific conditions

or maybe:
page.tree.getTree()
page.tree.rightClick(elementIdentifier)

right now there is no correct way to append these functions to page.

hope this makes sense :-)

**Comment by JoelEinbinder** [comment]
Closing this request becuase we aren't planning to do anything to make `page` extensible. Any generic testing methods that you feel compelled to add to the page, please file them as feature requests. We probably want to add them for everyone!

For app specific methods, like `page.getMySpecialTree`, you are better off building a Page Object Model. Something like `new MySpecialTree(page)`. [playwright-test](https://github.com/microsoft/playwright-test) is interested in solving any ergonomic problems with creating and passing around POMs.

Feel free to continue the discussion here even though this is closed. Or file a new issue in playwright-test.
