### ISSUE TITLE
Only nightly gets opened with playwright , Is there any way to open forefox stable version in playwright. ?

### ISSUE THREAD

**Issue by bibinmohana** [microsoft/playwright#16557]
Sample Code tried

Playwright playwright = Playwright.create()
LaunchOptions lp= new LaunchOptions()
lp.setChannel("firefox")
lp.setHeadless(false)

Browser browser = playwright.firedox().launch(lp)

Page page=browser.newPage()
page.navigate(url)

**Comment by aslushnikov** [comment]
@bibinmohana The visual design is different since we intentionally compile without official branding. Is this what makes you think it's nightly?

If you go to the `About Firefox` and check out the version, you'll see `103`; nightly and beta versions are marked something like `103.0b5`.

**Comment by bibinmohana** [comment]
@aslushnikov 
Thanks for the update , even in the settings , its showing About Nightly , not About Firefox . If I click on that , I could see the blue color logo and and its written like Nighltly . Version is 102.0(64-bit). And also if i trigger for some 5 time 2 times it will open browser with out the tool bar or menu bar   but its loading the extensions well. So  am wondering where there is some issue in the approach , also saw the post  like extensions are not implemented for firefox  and its loading here. It will be really helpful if you can share your thoughts. Thanks in advance :)

**Comment by aslushnikov** [comment]
> Thanks for the update , even in the settings , its showing About Nightly , not About Firefox . If I click on that , I could see the blue color logo and and its written like Nighltly .

@bibinmohana Yeah, while all the branding is nightly'ish, it should quack & behave exactly like stable!

> And also if i trigger for some 5 time 2 times it will open browser with out the tool bar or menu bar but its loading the extensions well.

Extensions might load if you're using `firefox.launchPersistentContext` and the profile already had an extension, but we don't support installing extensions by default with `firefox.launch()` method.

**Comment by bibinmohana** [comment]
Thabks for the update !

**Comment by aslushnikov** [comment]
Closing this then! Feel free to file a new issue if you think we can help you!
