### ISSUE TITLE
It will very handy to have a function for reading Data from an excel file saving it as an array would be very handy

### ISSUE THREAD

**Issue by AbhilashAus** [microsoft/playwright#16564]
I  want to read data from an excel file where the first row is name or title of the fields and the rows after that have values for those fields. I want the count of data rows. Then use this count to loop through and enter data into the fields and perform actions in the web application.

**Comment by vsravuri** [comment]
Here is an example.

https://playwright.dev/docs/test-parameterize#create-tests-via-a-csv-file

**Comment by aslushnikov** [comment]
> I want to read data from an excel file where the first row is name or title of the fields and the rows after that have values for those fields.

@AbhilashAus you should be able to achieve this with third-party tools like https://github.com/SheetJS/sheetjs
