### ISSUE TITLE
load more extension? how please

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#16562]
how can we load more than 1 extension?
in many test, we need to load 2 or more extension. 
how to do that,  thanks

**Comment by aslushnikov** [comment]
@viponedream just pass all the extension paths comma-separated:

```js
  const browserContext = await chromium.launchPersistentContext(userDataDir,{
    headless: false,
    args: [
      `--disable-extensions-except=${pathToExtension1},${pathToExtension2}`,
      `--load-extension=${pathToExtension1},${pathToExtension2}`
    ]
  });
```

**Comment by viponedream** [comment]
thank  you

**Comment by aslushnikov** [comment]
Well, there's this documentation page: https://playwright.dev/docs/next/chrome-extensions
And also this feature request that you can follow for the updates: https://github.com/microsoft/playwright/issues/5593

Hope this helps!
