### ISSUE TITLE
Can playwright implement a similar pyautogui library? Like the locationonscreen method, it can find the screenshot of the target element through full screen and return this element.

### ISSUE THREAD

**Issue by fj201314** [microsoft/playwright#16570]
Can playwright implement a similar pyautogui library? Like the locationonscreen method, it can find the screenshot of the target element through full screen and return this element. I feel that this is an algorithm that needs image recognition. Is there any hope to support it? It seems that this can solve the expectation of positioning failure caused by Dom level changes every time in UI automation!

**Comment by aslushnikov** [comment]
>  Is there any hope to support it? 

@fj201314 No, there are no plans to do anything like this at the moment
