### ISSUE TITLE
[Question] Supporting Locator as an argument to page.locator()?

### ISSUE THREAD

**Issue by np-xavier** [microsoft/playwright#16574]
As per the docs, I keep elements on my page objects as Locators. Often times, I'll have something like

```
container = this.page.locator('.container');
container-button = this.page.locator('button');
container-title = this.page.locator('h3');
```

And it's often the case that `container-button` and `container-title` are children of `container` in the DOM.

If I have multiple `.container` elements on the page, I will want to filter one down, maybe with something like `container.filter({ hasText: 'foo123')}` that is determined solely at runtime.

Now, if I want to access any of my predefined `container-button` or `container-title` locators that are inside this runtime-decided `container`, I was hoping to just be able to do:

`container.locator(container-button)` to give me the `button` element within that arbitrary container. But, `locator()` only allows a selector string to be passed in, so my obviously option is to define both a selector string and locator in the PageObject class, e.g. `container-button-css: string` and `container-button: Locator`, then I can use something like

`container.locator(container-button-css)`

But it's inelegant because I'm maintaining two properties. Just wondering what the best approach is with something like this? It would be nice if `.locator()` supported Locators themselves, or alternatively you could extract some kind of `Locator.selectorText` property from it.

Any thoughts?

**Comment by CtrlZvi** [comment]
I believe this already exists. Take a look at the [`has` filter for locators](https://playwright.dev/docs/locators#filtering-locators).

**Comment by np-xavier** [comment]
> I believe this already exists. Take a look at the [`has` filter for locators](https://playwright.dev/docs/locators#filtering-locators).

It's slightly more subtle - that gives me the element containing the sub-element, I need the sub-element itself. It's more down to the fact I have to pass it a text selector, and I can't pass it a Locator. My PageObjects all use Locators.

**Comment by heygarrett** [comment]
I'm not sure when it was added, but this seems to exist now:

> You can also chain two locators together, for example to find a "Save" button inside a particular dialog:
> 
> ```
> const saveButton = page.getByRole('button', { name: 'Save' });
> // ...
> const dialog = page.getByTestId('settings-dialog');
> await dialog.locator(saveButton).click();
> ```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
