### ISSUE TITLE
[Question] Testing on real mobile devices in cloud

### ISSUE THREAD

**Issue by Domadin** [microsoft/playwright#16578]
Hello.
I'm curious about missing integration of Playwright with platforms like BrowserStack and LambdaTest.
Will we ever be able to launch our autotests in mobile browsers using these cloud solutions? If so, is there any estimate of when this feature will be added?

**Comment by aslushnikov** [comment]
> I'm curious about missing integration of Playwright with platforms like BrowserStack and LambdaTest.

- BrowserStack: https://www.browserstack.com/docs/automate/playwright
- LambdaTest: https://www.lambdatest.com/playwright-testing

**Comment by aslushnikov** [comment]
Closing as per above
