### ISSUE TITLE
[Feature] BrowserType.connect() Should Accept Type LaunchOptions

### ISSUE THREAD

**Issue by jake-b-story** [microsoft/playwright#16580]
## Let us know what functionality you'd like to see in Playwright and what your use case is.
I am connecting my Playwright runs to Browserstack via BrowserType.connect(). Currently the only options `connect()` accepts are of type `ConnectOptions`:
```Typescript
export interface ConnectOptions {
  headers?: { [key: string]: string; };
  logger?: Logger;
  slowMo?: number;
  timeout?: number;
}
```

This means I cannot pass in additional launch options like I can in the `playwright.config.ts` file. I have a use case where I would like to disable Enhanced Cookie Tracking  on one particular test. I can do this just fine locally using the `browser.launch()` since the `launch()` method accepts type `LaunchOptions` which include all options I have in the `playwright.config.ts` file.

Currently the only way for me to alter firefoxUserPrefs when connecting to a remote server is to set it for all firefox instances in the `playwright.config.ts`,  IE:
```Typescript
{
  name: 'firefox',
  use: {
    launchOptions: {
      firefoxUserPrefs: {'network.cookie.cookieBehavior': 4}
    }
  },
}
```

I would like to be able to set it at the initial connection time like this:
```Typescript
firefox.connect({
  wsEndpoint: "....",
  firefoxUserPrefs: {'network.cookie.cookieBehavior': 4}
})
```

I would like to see the `connect()` method include the options found in the `LaunchOptions` type so I get the same granularity on a remote server as I do locally.

## Do you think others might benefit from this as well?
I do think this would be useful to others. Expecting similar options locally and on remote servers increases compatibility and adoption, and reduces complexity.

**Comment by aslushnikov** [comment]
> This means I cannot pass in additional launch options like I can in the playwright.config.ts file.

@jake-b-story This is by design. `connect()` API only connects to the running browser; you'll need to build your own proxy that will launch browsers that could be connected to and that will accept the launch options.

**Comment by jake-b-story** [comment]
@aslushnikov, does this mean setting the launch options at the 'playwright.config.ts' level will be ignored if using the `connect()` API option without setting up your own proxy?

**Comment by aslushnikov** [comment]
> does this mean setting the launch options at the 'playwright.config.ts' level will be ignored as well if using the connect() API option without setting up your own proxy?

@jake-b-story Yes, you should file this over to browser stack so that they fix it! :) 

> If this is the case, is there anyway around the popout Firefox has relating to cookie access (https://github.com/microsoft/playwright/issues/15941#issuecomment-1216056221)?

I don't think there is, unfortunately. There's a feature request to change ff preferences on the fly - https://github.com/microsoft/playwright/issues/16449 - but it's not very popular and thus low-priority for us.

**Comment by jake-b-story** [comment]
@aslushnikov, wanted to thank you for the quick turnaround, it's really appreciated. 

I'll post the Browserstack example in case anyone is looking for something similar:
Browserstack does expose the [ability to set user preferences](https://www.browserstack.com/docs/automate/playwright/set-browser-options#set-firefox-user-preferences) in Firefox on the initial connection via `caps` (capabilities).

An example cap would look like:
```Typescript
const caps = {
    'browser': 'firefox',
    'browserstack.username': process.env.BROWSERSTACK_USERNAME
    'browserstack.accessKey': process.env.BROWSERSTACK_ACCESS_KEY
    'firefox_user_prefs': { 'network.cookie.cookieBehavior': 4 },
};
```

Which is then consumed like the following:
```Typescript
chromium.connect({
        wsEndpoint:
          `wss://cdp.browserstack.com/playwright?caps=` +
          `${encodeURIComponent(JSON.stringify(caps))}`,
      });
```
