### ISSUE TITLE
[BUG] The installation with the "Install Playwright" command using the VSCode extension triggers several errors

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#16583]
**Context:**
- Playwright Version: Try to install the latest one
- Operating System: Windows
- Node.js version: 14.18.1
- Browser: Try to install all of them.
- Extra: VSCode extension version v0.2.8

**Code Snippet**

The VSCode extension tries to run the following command:

```javascript
npm init --yes playwright@latest -- --quiet --browser=chromium --browser=firefox --browser=webkit --gha
```

**Describe the bug**

I try to install Playwright into the empty folder.

The installation via the **Install Playwright** command of the VSCode extension triggers several errors:

![image](https://user-images.githubusercontent.com/52656401/184932819-c0e18015-cfb3-423a-ab08-a924604d6098.png)

And I get only the folder with a name **playwright@latest** created in the project.

![image](https://user-images.githubusercontent.com/52656401/184934289-f20ea291-838e-4b72-a11f-ee65f2d38f34.png)

See the attached video:

https://user-images.githubusercontent.com/52656401/184933671-45496863-4204-44b7-b603-214cd2ae5caf.mp4

Also, I'm attaching the log of the failed installation:

[2022-08-16T16_38_29_692Z-debug.log](https://github.com/microsoft/playwright/files/9352857/2022-08-16T16_38_29_692Z-debug.log)

**Comment by BW-PA** [comment]
I am experiencing the exact same problem.  Same error, same version of vscode extension same empty playwright@latest folder.

**Comment by BW-PA** [comment]
Just logged the same over on the GitHub issues page for teh VsCode extension here [https://github.com/microsoft/playwright-vscode/issues/220#issue-1341120040](url)

**Comment by aslushnikov** [comment]
I can repro:

```bash
$ mkdir tmp && cd tmp
$ npm init -y
$ code .
```

and in VSCode: `Cmd-Shift-P`, `Test: Install Playwright`

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/746130/185051745-80a0caf9-726b-4eb1-8831-6462f372c82f.png">

**Comment by mxschmitt** [comment]
> I can repro:
> 
> ```shell
> $ mkdir tmp && cd tmp
> $ npm init -y
> $ code .
> ```
> 
> and in VSCode: `Cmd-Shift-P`, `Test: Install Playwright`
> 
> <img alt="image" width="1125" src="https://user-images.githubusercontent.com/746130/185051745-80a0caf9-726b-4eb1-8831-6462f372c82f.png">

I think thats different and should already be fixed!

—-

@BW-PA what npm version are you using? npm —version

**Comment by pavelfeldman** [comment]
Merging into https://github.com/microsoft/playwright-vscode/issues/220

**Comment by nrajubairaju91** [comment]
I am getting below error. could some one help me plz
npm error code E502
npm error 502 Bad Gateway - GET https://infyartifactory.ad.infosys.com/artifactory/api/npm/npm/create-playwright
npm error A complete log of this run can be found in: C:\Users\bairaju.narasaraju\AppData\Local\npm-cache\_logs\2025-05-13T05_31_06_186Z-debug-0.log
