### ISSUE TITLE
Is it possible to open up a new page styled as a popup?

### ISSUE THREAD

**Issue by mhkeller** [microsoft/playwright#16598]
Hello, I'd like to open up a new page but without any page chrome.

Similar to how you could do in JavaScript:

```js
const params = `scrollbars=no,status=no,location=no,toolbar=no,menubar=no,width=500,height=500`;

window.open('/', 'test', params);
```

[edit]

It seems that using `args: ['--app']` in the `chromium.launch` method should work but it has no effect for me.

Using `--kiosk` in puppeteer works but doesn't work in playwright...

**Comment by aslushnikov** [comment]
@mhkeller something like this works for me:

```ts
import { chromium, firefox } from '@playwright/test';

const context = await chromium.launchPersistentContext('./foo', {
  args: [
    `--app=data:text/html,`,
    '--window-size=600,600',
    '--window-position=100,10',
    '--test-type=',
  ],
  ignoreDefaultArgs: ['--enable-automation'],
  headless: false,
});
```

I'll close this, but please feel free to file a new issue if you think we can be helpful!

**Comment by mhkeller** [comment]
@aslushnikov. Thanks. That does create a window with no toolbar but when I then do `context.newPage()` it creates a regular page. I don't see a `context.setContent` or similar method. How can I add HTML and CSS to this window?

**Comment by mhkeller** [comment]
Looks like I can do:

```js
const context = await chromium.launchPersistentContext('./test/tmp/context2', opts);

const pages = await context.pages();
```

And then use `pages[0]`. 

@aslushnikov Is there any way to get this window appearance without using `launchPersistentContext`? Also, do you know if it's possible to disable chromium from launching a new window when you click the application icon in the dock during this mode? This gets me part of the way there but sacrifices some usability and also some complexity in having to manage the persistent context store.

**Comment by aslushnikov** [comment]
> Is there any way to get this window appearance without using launchPersistentContext?

@mhkeller I don't think so!

> if it's possible to disable chromium from launching a new window when you click the application icon in the dock during this mode? 

I don't think it's possible too.

**Comment by aslushnikov** [comment]
> My last question as a possible workaround: would it be possible to launch a browser environment without displaying any visual page and then execute window.open in that environment's JavaScript context to display a browser pop-up window?

Nah, unfortunately I'm not aware of any way of doing this too!

**Comment by mhkeller** [comment]
Okie doke. Thanks for your time.

**Comment by mhkeller** [comment]
For anyone coming here looking to do the same thing, I'm able to do this with command line flags directly: https://github.com/sindresorhus/open/issues/290
