### ISSUE TITLE
[Question]: Playwright with selenium grid and proxy

### ISSUE THREAD

**Issue by wodyjowski** [microsoft/playwright#16606]
Hi,
I'm currently using Selenium chromedriver + Xunit to run automated frontend tests in C#. Test runs (Xunit invocations) are managed by web application and Selenium is running on Selenium Grid 4. I wanted to try out Playwright but I've encountered two problems:

- Why `SELENIUM_REMOTE_URL` has to be provided by environment URL and it can't be injected from code? In case I want to control if the tests should be run locally/remotely I have to change environmental variable and it looks hacky.
- Is there a way to provide proxy for selenium grid other than setting `http_proxy` variable? My app runs in container and I don't want to pass the whole network traffic through proxy.

I've asked this question in main Playwright [repo](https://github.com/microsoft/playwright/discussions/16378) but I guess this is a better place.

**Comment by aslushnikov** [comment]
cc'ing @dgozman

**Comment by dgozman** [comment]
> Why SELENIUM_REMOTE_URL has to be provided by environment URL and it can't be injected from code?

We haven't arrived to an API yet. You can always use [`Environment.SetEnvironment`](https://docs.microsoft.com/en-us/dotnet/api/system.environment.setenvironmentvariable?view=net-6.0) to set env variable programmatically.

> Is there a way to provide proxy for selenium grid other than setting http_proxy variable? My app runs in container and I don't want to pass the whole network traffic through proxy.

This makes sense, but is not currently possible.

**Comment by salvadoriume** [comment]
Any ETA @dgozman ? Or is it on some roadmap? This feature is something I am also waiting for. 
Thank you very much.

**Comment by dgozman** [comment]
@salvadoriume This issue is not on the roadmap. We usually prioritize based on the popularity of the issue, and this is not popular enough yet.

**Comment by wodyjowski** [comment]
Can't you just do [this](https://github.com/microsoft/playwright-dotnet/pull/2333)?
You already pass some environment variables when creating Node.js process, how about passing more?

**Comment by wodyjowski** [comment]
@mxschmitt?

**Comment by marcinkaczor** [comment]
I'm also waiting for this feature :slightly_smiling_face:

**Comment by Qrnbth** [comment]
Some similar feature also needed in python....plus,document in python seems to be wrong with this section

**Comment by hrishi1096** [comment]
For a setup where a proxy is set up for outbound connections, playwright with nodejs not being proxy aware is quite problematic. Eagerly waiting for this feature.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
