### ISSUE TITLE
[Question] Running msedge Tests via docker Container on fedora system

### ISSUE THREAD

**Issue by Basti098765** [microsoft/playwright#16613]
I am currently trying to setup Edge to run tests on a project. For this I set up an edge project in my config:
```
{
      name: 'edge',
      use: {
        channel: 'msedge',
      },
}
```
Now when I try to launch those tests I get errors because my OS is not supported. That is why I use the docker Image to run the tests. It works fine for chrome, firefox and webkit but for edge I get an error telling me to run an install command for msedge. As far as I understand edge is not included in the [Image](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.focal) mentioned [here](https://playwright.dev/docs/docker)?
For now I worked around this Issue running my Tests like this: 
```
docker run -it --rm --ipc=host --net=host -v $(pwd):/src -w /work mcr.microsoft.com/playwright:v1.25.0 /bin/sh -c "npx playwright install msedge;cp -r /src src && cd src && npm --cache /tmp/.npm test -- --update-snapshots -g 'visual' --project=edge && chown $(id -u):$(id -g) -R snapshots/ && cp -r snapshots/ /src/"
```
This runs `npx playwright install msedge` before It starts the tests. This works for now and allows me to run the edge Tests but I am wondering if there is a way to add this to the Image or get the same result without running the install every time?

**Comment by aslushnikov** [comment]
> I am wondering if there is a way to add this to the Image or get the same result without running the install every time?

@Basti098765 MSEdge is not installed by default inside our docker image; you can build your own image based off our official one that just adds msedge.

**Comment by aslushnikov** [comment]
My triaging rotation is over, so I'll close this as per above.

Please feel free to file a new issue if you think we can be somehow helpful!
