### ISSUE TITLE
[Question] getting date and time of when a test was run into the default playwright report

### ISSUE THREAD

**Issue by goldenox777** [microsoft/playwright#16617]
Hello,

` 
reporter: [

    ['line'],

    ['allure-playwright'],

    ['json', { outputFile: 'test-results/json/results.json' }],

    ['junit', { outputFile: 'test-results/xml/results.xml' }]

  ],`

With the above in playwright.config.ts at the end of a run, playwright generates a JSON with all the results.
It does not log the timestamp when the test was actually run.

How would one get this to be shown in the report?

PS: we have found allure does it, but that leads to other problems and we need a way to do it without allure.

Any tips will be appreciated.

Thanks!

**Comment by aslushnikov** [comment]
@goldenox777 technically, the json file itself has creation attributes that you can use to get the creation timestamp. Isn't it enough?

**Comment by goldenox777** [comment]
> @goldenox777 technically, the json file itself has creation attributes that you can use to get the creation timestamp. Isn't it enough?

are you referring to reading the file info on disk?
There is only 1 file generated, and we have ~200 tests. Ideally, we would want to know when each was run.
(since we have dependencies which are out of our hands, we would like to be able to pinpoint when certain test failed, due to certain dependency)
PS: digging around, I have found console.log(testInfo["_startWallTime"]) in test.afterEach could do the job. 
Though this would mean I would have to manipulate the end report, or come up with a way of using _startWallTime in a different way. Still, specifying it in every afterEach would be cumbersome.

Thanks for your reply!
Any tips?

**Comment by goldenox777** [comment]
I have realised I will need to make my own custom reporter.
Thanks for the help!
