### ISSUE TITLE
[Question]: Triggering multiple mousebuttons simultaneously

### ISSUE THREAD

**Issue by ArjenStoop** [microsoft/playwright#16611]
### Your question

I encounter the issue that it is not possible to use more than 1 mouse button at the same time in Playwright. 

Use case: 
User presses Left-mouse-button AND another mouse button. (RMB or MMB). 
With both buttons pressed, the mouse is moved. 
This should trigger a particular behavior on our webbased application. 

So far I couldn't get it to work (the mouse.down of the second mouse button cancels the active mouse.down (or mouse.click with delay) of the first button). 

Anybody a suggestion?

**Comment by aslushnikov** [comment]
@ArjenStoop you should be able to click multiple buttons, e.g. we have the following test that makes sure that `buttons` property in event is reported properly: 

https://github.com/microsoft/playwright/blob/007e197e3dcf67cc412554b4732da4c95318a2f6/tests/page/page-mouse.spec.ts#L113-L145

**Comment by ArjenStoop** [comment]
@aslushnikov The issue is that we need both mouse buttons down at the same time (and then move the mouse). 
Both need to be in active state. 
With the example you shared, the events of the different mousebuttons are triggered indeed, but when the mouse.down of the left button is hit, the middle mouse button is not down anymore.

**Comment by aslushnikov** [comment]
@ArjenStoop I do see `buttons: 5` assertion (primary + aux buttons being down) right here: https://github.com/microsoft/playwright/blob/007e197e3dcf67cc412554b4732da4c95318a2f6/tests/page/page-mouse.spec.ts#L141

Can you build a similar minimal test case that demonstrates that something is not working in Playwright?

**Comment by aslushnikov** [comment]
Closing as per above.

Please feel free to file a new issue if you think we still can be helpful somehow!

**Comment by ashish-sparrows** [comment]
@aslushnikov 
The only difference I see is that in our code we are using HostListener and in your test window.addEventListener is used.

**Comment by ashish-sparrows** [comment]
Hi @aslushnikov, We were using playwright/test pkg version 1.17.1 
and after upgrading it to 1.20.1 it is working :)
