### ISSUE TITLE
[Feature] A way to determine whether an Electron app is executed via Playwright

### ISSUE THREAD

**Issue by c3er** [microsoft/playwright#16614]
Is there a way to determine whether an Electron application is executed via Playwright?

The use case is to regard the additional CLI arguments that are passed before the script path. Currently, the only idea I have, is to filter out the switches `--inspect` and `--remote-debugging-port` directly before passing the argument array to the application's CLI parsing. But this is not a good solution for multiple reasons.

I [made in issue in the Yargs project](https://github.com/yargs/yargs/issues/2225). AFAICT a CLI parsing library needs this requested feature to be able to properly filter the arguments.

**Comment by aslushnikov** [comment]
> Is there a way to determine whether an Electron application is executed via Playwright?

I don't think so. 

> The use case is to regard the additional CLI arguments that are passed before the script path. Currently, the only idea I have, is to filter out the switches --inspect and --remote-debugging-port directly before passing the argument array to the application's CLI parsing. But this is not a good solution for multiple reasons.

I don't think I follow this as well. It looks like there's a bug in yargs project parsing CLI arguments; how exactly can we be helpful here?

**Comment by c3er** [comment]
If I invoke an Electron application with an additional argument, e.g. a file name, how can I determine, which parameter is the actual file?

The usual trick is to filter the *first two* arguments if invoked via `npm` or *only the first* if a packed application is invoked. Electron [offers a way](https://github.com/electron/electron/blob/main/docs/api/process.md#processdefaultapp-readonly) to determine which case has to be applied.

Now, if the Electron application is invoked via Playwright, e.g. like this:

```javascript
const electronPath = require("electron")
const playwright = require("playwright")

const electron = playwright._electron

// ...

const app = await electron.launch({
    args: [
        "path/to/main.js",
        "path/to/my/file",
    ],
    executablePath: electronPath,
})
```

`process.argv` looks like this:

```javascript
[
    'path/to/Electron',
    '--inspect=0',
    '--remote-debugging-port=0',
    'path/to/main.js',
    'path/to/my/file',
]
```

It would help very much already (and make the requested feature superfluous to me), if `--inspect=0` and `--remote-debugging-port=0` would be guaranteed to be the last arguments in `process.argv` (or at least not between the paths for Electron and the main.js file).

My original idea (which I missed to communicate properly) is to have a way to find out that the application was invoked via Playwright, preferably with the additional information, which exact arguments were added by Playwright and being able to filter out these arguments before doing further processing of the command line.

Yargs is just an example, which I like to use in [my application](https://github.com/c3er/mdview). I think, this is an overall problem at CLI parsing with Electron and Playwright and if you know some library or some tricks to handle this properly, the problem would be solved for me.

I hope, this is clear enough now🙂

**Comment by c3er** [comment]
I just looked into the [source code](https://github.com/microsoft/playwright/blob/ba722a2580fd2267bddc980ade62317a51c995be/packages/playwright-core/src/server/electron/electron.ts#L128) and naively, the change itself seems quite trivial. Though, I don't see any tests for ensuring that the Electron launch options are evaluated properly -- so a test for the argument list should be added, and to do this the Electron tests should be able to look into the started Electron app somehow to check the resulting `process.argv`.

I would do the change myself and open a PR, though

1. Would this have a chance to be approved and applied?
2. I don't want to promise too much. I'd only work on this during my spare time.

Also, I had to find out, how to execute only the Electron tests. Executing all of the more than 8000 tests takes quite a while and not all tests work on my machine (some network socket problems, failed screenshot comparisons and some other minor problems).

**Comment by aslushnikov** [comment]
> I mean changing the order of the arguments, so that --inspect=0 and --remote-debugging-port=0 would be after the user provided arguments.

Sure, sgtm! Feel free to send a PR

**Comment by aslushnikov** [comment]
or let me actually send a PR myself so that I don't forget about this one

**Comment by c3er** [comment]
Thank you very much!
