### ISSUE TITLE
[BUG] Tests using Webkit have started failing on v1.25

### ISSUE THREAD

**Issue by SunilEd** [microsoft/playwright#16629]
Updated my playwright packages(nuget)  to v1.25 and updated browsers using playwright install command. Tests using webkit are failing!!. If i roll it back to version 1.24.1 all good

**Comment by mxschmitt** [comment]
Can you provide us a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) in e.g. a git repo which we can run locally to find out what the issue is?

**Comment by aslushnikov** [comment]
@SunilEd It's hard to help without much details, so please re-file with a repro and more details on what's not working!
