### ISSUE TITLE
[BUG] Invalid settings in playwright.devices

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright#16622]
**Context:**
- Playwright Version: 1.25.1
- Operating System: Linux
- Python version: 3.10
- Browser: Firefox

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    browser = p.firefox.launch()
    context = browser.new_context(**p.devices['JioPhone 2'])
```

**Describe the bug**

Raises `Error: options.isMobile is not supported in Firefox` because `'is_mobile': True` is not a valid setting for firefox: 

```
 'JioPhone 2': {'user_agent': 'Mozilla/5.0 (Mobile; LYF/F300B/LYF-F300B-001-01-15-130718-i;Android; rv:103.0) Gecko/48.0 Firefox/103.0 KAIOS/2.5', 
'viewport': {'width': 240, 'height': 320}, 'device_scale_factor': 1, 
==> 'is_mobile': True, 
'has_touch': True, 'default_browser_type': 'firefox'}
```

**Comment by rwoll** [comment]
Thanks for the report!

As a workaround, you can filter `is_mobile` (if present) property from device settings when using FF browser.

---

Even if used according to our Playwright Test docs, user would get this error based on the default browser for this device and https://github.com/microsoft/playwright/blob/94c9db299da240bcd5725f5059c34eee155707d7/packages/playwright-core/src/server/firefox/ffBrowser.ts#L83:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'Jio 2',
      use: {
        ...devices['JioPhone 2'],
      },
    },
  ]
};

export default config;

```

```
$ npx playwright test

Running 1 test using 1 worker

  ✘  1 [Jio 2] › tests/example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page (5ms)


  1) [Jio 2] › tests/example.spec.ts:3:1 › homepage has Playwright in title and get started link linking to the intro page 

    browser.newContext: options.isMobile is not supported in Firefox





  1 failed
```

**Comment by Rafiot** [comment]
Thank you for the feedback! Yep, filtering out the key is what I did on my side: 

https://github.com/Lookyloo/PlaywrightCapture/blob/34ab2c3e096fc3bc1ebef217063b78f3554d8a42/playwrightcapture/capture.py#L188
