### ISSUE TITLE
[Question] Update storageState to refresh token

### ISSUE THREAD

**Issue by jmthomas** [microsoft/playwright#16627]
I'm using Keycloak with a 30min refresh token. My test suite is longer than that and promptly at 30min it fails. I'm following the [multiple sign-in roles](https://playwright.dev/docs/test-auth#multiple-signed-in-roles) pattern to generate two json files in my [global-setup](https://github.com/OpenC3/playwright/blob/main/global-setup.ts). Once I discovered the issue I assumed I needed to simply refresh my json files. So I created a method to do that in my [utilities](https://github.com/OpenC3/playwright/blob/main/utilities.ts):

    async saveStorageState(file = 'storageState.json') {
      await this.page.context().storageState({ path: file })
    }

I called it in several of my test cases but my tests still fail at exactly 30min. Am I updating the `storageState.json` correct? Can this be updated outside of the global-setup?

**Comment by aslushnikov** [comment]
> Once I discovered the issue I assumed I needed to simply refresh my json files.

@jmthomas I guess you have to re-login in 30 minutes; just re-writing JSON files would not generate a new token.

**Comment by jmthomas** [comment]
I forgot to mention that we have a frontend background task that refreshes the tokens. Thus my local tokens should be up to date as I'm running. That's why I thought I could simply re-write them. This is all happening in a Github Action run. I'll try a local run and see if I can detect the tokens being updated.

**Comment by jmthomas** [comment]
I just wanted to confirm that _if_ my tokens were up to data, a call to `await this.page.context().storageState({ path: 'storageState.json' })` should work to update the token and the next call to run a test will use that updated token. I didn't know if perhaps there was caching or something that only looks at the storageState once. I have the following in my [playwright.config.ts](https://github.com/OpenC3/playwright/blob/main/playwright.config.ts):

    use: {
      // Tell all tests to load signed-in state from 'storageState.json'.
      storageState: 'storageState.json',
    }

**Comment by jmthomas** [comment]
I can reproduce locally and confirm the storageState.json file is getting updated. So I'm not sure why I'm still timing out after 30min.

**Comment by jmthomas** [comment]
@aslushnikov Does playwright cache or otherwise use the same storageState file given in the global-setup or does it re-read it each time it creates a new browser context?

**Comment by jmthomas** [comment]
I was unable to get the storageState thing to work so I switched to fixtures and came up with the following:

    import { test as base } from '@playwright/test'
    // Extend the page fixture to goto the OpenC3 tool and wait for potential
    // redirect to authentication login
    export const test = base.extend({
      toolPath: '/tools/cmdtlmserver',
      page: async ({ baseURL, toolPath, page }, use) => {
        page['utils'] = new Utilities(page)
        await page.goto(`${baseURL}${toolPath}`, {
          waitUntil: 'networkidle',
        })
        // Check to see if we redirect to authenticate
        if (page.url().includes('/auth/')) {
          await page.locator('input[name="username"]').fill('operator')
          await page.locator('input[name="password"]').fill('operator')
          await Promise.all([
            page.waitForNavigation(),
            page.locator('input:has-text("Sign In")').click(),
          ])
          await page.context().storageState({ path: 'storageState.json' })
        }
        await use(page)
      },
    })
    export { expect } from '@playwright/test'

**Comment by troypoulter** [comment]
Hi @jmthomas,

I'm experiencing a similar problem, and thanks for sharing your solution with the fixture.

I wanted to check if you happened to find any other way of solving this, I'm looking to solve the same challenge where we can update the `storageState` mid-test if the token refreshes and have future tests utilise it.

**Comment by madrane9** [comment]
I'm facing the same issue as you. Updating the StorageState becomes a challenge when the admin token constantly needs refreshing via Keycloak. Having to manually run the command "npx playwright codegen xx.xxx.xx --save-storage=admin.json" each time to update the StorageState is both tedious and inefficient. Moreover, this could lead to disruptions in the pipeline.

I'm also interested in finding a solution that allows updating the StorageState mid-test if the token refreshes and having future tests utilize it. As of now, I haven't found an optimal solution, but I'm actively looking for one and would appreciate any discussion on this matter. Should I find a solution, I will certainly share it. It would also be great if you could share any insights if you come across a solution.

**Comment by jmthomas** [comment]
We added codecoverage to our repo so it's a bit obfuscated but our current fixture is here: https://github.com/OpenC3/cosmos/blob/main/playwright/tests/fixture.ts
