### ISSUE TITLE
[BUG] External HTTP Requests do not fire when triggered from a custom reporter

### ISSUE THREAD

**Issue by nate-blum** [microsoft/playwright#16644]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Windows
- Node.js version: 18.5.0
- Browser: Chromium

```javascript
import {
    type FullConfig,
    type FullResult,
    type Suite,
    type TestCase,
    type TestError,
    type TestResult,
    type Reporter,
} from '@playwright/test/reporter';
import fetch from 'node-fetch';

class FTReporter implements Reporter {
    onBegin(config: FullConfig, suite: Suite) {}
    onTestBegin(test: TestCase) {}

    onTestEnd(test: TestCase, result: TestResult) {
        if (result.status != 'passed') {
            let Message = `
Finished test '${test.title}' of ${process.env.PROPS_URL.trim()} in ${result.duration}ms
Status: ${result.status}
Retries: ${result.retry}
Errors:
${result.errors.map(err => err.message).join('\n')}`;
            console.log(Message);
            fetch('https://google.com', {
                method: 'get',
            }).then(res => console.log('ok: ' + res.ok));
        }
    }

    onEnd(result: FullResult) {}
}
export default FTReporter;
```

My goal is to have my custom reporter hook into a Slack webhook so that when tests fail, it alerts the Slack channel. However, I can't seem to get HTTP requests to work from the reporter. `console.log(Message)` is working, but I never see "ok: true" in the console or anything like that. I've tried making onTestEnd asynchronous but that didn't work either. This isn't an issue with node-fetch because it works everywhere else without any issues, it's just when a request is run from the custom reporter. Please let me know what you think, thanks.

**Comment by aslushnikov** [comment]
@nate-blum it looks like test runner completes before your requests pass. You have to store all your `fetch` promises and await them in the [`onEnd`](https://playwright.dev/docs/next/api/class-reporter#reporter-on-end) reporter callback. The `onEnd` callback is the only asynchronous one, so you can wait for all the scheduled jobs to finish here.

**Comment by nate-blum** [comment]
This worked, thank you!
