### ISSUE TITLE
[Question] Inline snapshots like jest?

### ISSUE THREAD

**Issue by mmkal** [microsoft/playwright#16646]
Has `expect(...).toMatchInlineSnapshot()` been considered to include as a built-in part of playwright? i.e. something that modifies the source file it appears in, like [in jest](https://jestjs.io/docs/snapshot-testing#inline-snapshots)?

Incidentally, my team are using playwright in a multi-package repo project for browser tests, and jest in other packages. playwright seems waay nicer out of the box. It has in-built support for typescript, strongly-typed configuration, html reporting which is a *godsend* in CI, configurable retries, configurable parallelization, sensible reporters, helpful source maps, less "magic" (`import {expect, test} from '@playwright/test'` instead of magic global, for example). All of those _can_ be done in jest but the DX for playwright just seems considerably better. I think `.toMatchInlineSnapshot()` is almost the only reason I wouldn't want to start using playwright as a regular test runner (skipping browser downloading if it's not necessary).

**Comment by aslushnikov** [comment]
@mmkal inline snapshots is something we're thinking about. Please upvote #9006 to get updates!
