### ISSUE TITLE
[Question] Redirect issue in webapp

### ISSUE THREAD

**Issue by jithintill** [microsoft/playwright#16658]
i am playwright 1.25.0 

We are testing a web app across all 4 browsers

Inside the Docker container in AWS, we are getting below error

We are unable to get this while launching the app manually.

This error pops up intermittently while running tests in local

Base Image used is mcr.microsoft.com/playwright:v1.25.0-focal

 ```page.goto: Load cannot follow more than 20 redirections```

**Comment by aslushnikov** [comment]
@jithintill it looks like some network / server configuration results in more than 20 redirects while trying to load the website, and the browser just gives up following these redirects to avoid infinite looping.

Users are likely to suffer from the same issue, so this looks like a website bug to me.

**Comment by jithintill** [comment]
we had a look into the issue again and found that cookies in the storage has expired/invalidated after logout due to new auth implementation . This result in loading invalid cookies to the browser for any tests after logout and then navigating to site with that invalid storage state resulted in redirect loops.
