### ISSUE TITLE
[Question] 2FA (Factor Authentication) while authenticating in local environment

### ISSUE THREAD

**Issue by AnveshKolluri** [microsoft/playwright#16651]
I understand and have tried automating [using the docs](https://playwright.dev/docs/auth#automate-logging-in) but, I am running into 2FA step where I am having to choose between smart card or microsoft authenticator app. 

How do I silently fetch the token (without 2FA for testing) and also this is going to be a problem running in CI/CD pipeline. I didn't come across a question/sample in the docs or here on github for similar use cases. Any suggestions on handling this? Thanks!

**Comment by qtpsudhakar** [comment]
Use totp generator package for getting token on fly and use it in your test.
https://www.npmjs.com/package/totp-generator

**Comment by aslushnikov** [comment]
Integrating with 2FA is so far outside of our scope, so I'll have to close this for now since we can't be helpful here.
