### ISSUE TITLE
[Question] Parameters for Playwright Docker Image in Jenkins

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#16664]
Hi 

I am trying to use Playwright image in Jenkins. In [your example](https://playwright.dev/docs/ci#jenkins), you show the usage of it using the docker plugin. However, it is a no go for me and I would like to use pod templates instead.

![image](https://user-images.githubusercontent.com/6009200/185565087-4a2842c7-409a-468b-b7b1-c67fe0fa91d8.png)
With above configurations, the pod starts, and from terminal I can see that it is running. However, Jenkins is not able to connect and it eventually times out.

Appreciate your help if you could have a look at the parameters and let me know what should I change.

**Comment by aslushnikov** [comment]
@irharrier2 unfortunately we don't have much experience with Jenkins here; from quick googling, it looks like you at least have to launch `sshd` inside container: https://devopscube.com/docker-containers-as-build-slaves-jenkins/

All in all, feel free to ask this kind of questions on https://aka.ms/playwright/slack or on StackOverflow! If you still think we (playwright team) can be somehow helpful to you, please do not hesitate to re-file.
