### ISSUE TITLE
[BUG] custom selector engines don't work when running in debug mode

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#16665]
**Context:**
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 3.03 GB / 15.92 GB
## Binaries:
 - Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright: ^1.25.0 => 1.25.0

**Code Snippet**
```ts
import { test} from "@playwright/test";
import { selectors } from "playwright";

const createTagNameEngine = () => ({
  query(root, selector) {
    return root.querySelector(selector);
  },

  queryAll(root, selector) {
    return Array.from(root.querySelectorAll(selector));
  },
});

test("selector engine test", async ({ page }) => {
  await page.setContent(`<div><button>Click me</button></div>`);
  await selectors.register("tag", createTagNameEngine);
  await page.locator("tag=button").click();
});
```

**Describe the bug**
when running the test normally (like so), it passes.
![image](https://user-images.githubusercontent.com/57028336/185569022-ad1f941e-6bbb-4163-b152-6084d630a310.png)

however when running it in debug mode:
![image](https://user-images.githubusercontent.com/57028336/185569106-a0530cdc-48f4-423d-ba08-0892181d1371.png)

the following error occurs:
> Unknown engine "tag" while parsing selector tag=button

![image](https://user-images.githubusercontent.com/57028336/185569428-894f1ad2-dedb-4b7e-8624-48ddb84529dc.png)

sorry i don't know how to make it print the full stack trace. when running `playwright test` in either a normal terminal or a debug terminal, it passes. so it may be an issue with whatever arguments the playwright extension is passing when clicking "Debug Test"

**Comment by aslushnikov** [comment]
@DetachHead I can repro; with the latest version of extension:

1. Create a new folder and initialize test
```bash
mkdir repro && cd repro && npm init -y && npm i @playwright/test
npx playwright install --with-deps chromium # to save some time
cat <<'EOF' > a.spec.ts
import { test, selectors } from "@playwright/test";

const createTagNameEngine = () => ({
  query(root, selector) {
    return root.querySelector(selector);
  },

  queryAll(root, selector) {
    return Array.from(root.querySelectorAll(selector));
  },
});

test("selector engine test", async ({ page }) => {
  await page.setContent(`<div><button>Click me</button></div>`);
  await selectors.register("tag", createTagNameEngine);
  await page.locator("tag=button").click();
});
EOF
cat <<EOF > playwright.config.ts
export default {}
EOF
```
2. Running `npx playwright test` works
3. **HOWEVER**, launching the same test in VSCode complains about selector engine.

**Comment by DetachHead** [comment]
this issue doesn't seem to be fixed in 1.25.1. can this please be re-opened @aslushnikov @pavelfeldman 

let me know if you need any more info to reproduce

**Comment by pavelfeldman** [comment]
Let's see if this fixes it

**Comment by DetachHead** [comment]
that worked, thanks!
