### ISSUE TITLE
[BUG] Cannot close browser after user closes page

### ISSUE THREAD

**Issue by PlaywrightTester** [microsoft/playwright#16679]
**Context:**
- Playwright Version: ^1.22.2 && ^1.25.0
- Operating System: Windows 10
- Node.js version: v16.14.0
- Browser: Chromium

```javascript
import playwright from 'playwright';


async function main() {

	const browser = await playwright.chromium.launch({
		headless: false
	});

	const page = await browser.newPage();


	page.on('close', async function() {
		console.log("Page close");
		await browser.close();
		console.log("Browser close");
		process.exit(1);
	});

	await page.waitForSelector('"text"', {timeout: 0});
}

main();
```

When I close the page, I get "Page close" in the console but nothing else. The browser does not close.
If I close it in task manager, I got this error :

```
page.waitForSelector: Target closed
=========================== logs ===========================
waiting for selector ""text"" to be visible
============================================================
    at main (file:///D:/index.js:20:7) {
  name: 'Error'
}
```

However, if I replace `await page.waitForSelector('"text"', {timeout: 0});` by `await page.waitForTimeout(100000000);` the browser closes fine, and the program stops.

**Comment by aslushnikov** [comment]
@PlaywrightTester this doesn't repro for me on MacOS 12.5 and Playwright 1.25. @mxschmitt is kind to try to repro on Windows, let's see what he says!

**Comment by aslushnikov** [comment]
> When I close the page, I get "Page close" in the console but nothing else. The browser does not close.

@PlaywrightTester It didn't reproduce for Max as well; the browser closes just fine when we hit "X" on the page. Could you please try running with the latest Playwright 1.25?

**Comment by PlaywrightTester** [comment]
Same problem with Playwright 1.25.

https://user-images.githubusercontent.com/111575222/185671253-6c2d84f6-dff4-47e3-91b5-cbed3aa7d509.mp4

**Comment by aslushnikov** [comment]
@PlaywrightTester hmm it does look like a bug to me, but I don't think it's actionable unless we can repro this :( Let me ask @yury-s as well how has a windows machine.

**Comment by yury-s** [comment]
I tried with playwright 1.25.0, it closes just fine.

**Comment by aslushnikov** [comment]
@PlaywrightTester Unfortunately, we had no luck reproducing this on a variety of machines we have in our possession. And unfortunately, this is not actionable without a repro.

If you can repro this on your friend's windows machine, for example, then maybe you'll be able to come up with a better repro steps for us. In this case, please feel free to file this issue one more time! I'll close this for now.
