### ISSUE TITLE
Add Dark Mode To Playwright Inspector

### ISSUE THREAD

**Issue by PeterHevesi** [microsoft/playwright#16670]
Would you please consider adding dark mode to Playwright Inspector?
All my Windows are dark, so this Playwright Inspector white window disturbs me
I know this feature has probably the lowest possible priority for you, but still anyway, I would like it :D 
So maybe sometimes in the future, when you consider improving Playwright Inspector with some other more important feature requests for it, then you could maybe add even this one :D
Thanks so much :)

**Comment by PeterHevesi** [comment]
Thanks so much for adding it there :)

**Comment by makiwata** [comment]
Hi can you help me please how to turn this on? I find no option for this :-(
