### ISSUE TITLE
Console error is not shown when locator is not correct , instead waiting indefinitely! Playwright - Java

### ISSUE THREAD

**Issue by bibinmohana** [microsoft/playwright#16671]
Whenever its not able to identify the locator , its not throwing any error , instead it is waiting indefinetly , then have to stop the run from the eclispe.

Sample Code

```java
Path extn1path=Path.get("")
Path ext2path=Path.get("")

List<String> chromeArgs= new ArrayList<>()
chromeArgs.add("--disable-extensions-except="+extn1path+","+extn2path);
chromeArgs.add("--load-extension="+extn1path+","+extn2path)

BrowserType.LaunchPersistentContextOptions lp=new BrowserType.LaunchPersistentContextOptions();
lp.setChannel("chrome")
lp.setHeadless(false)
lp.args=chromeArgs
lp.setDevtools(false)

Path userdirpath=Paths.get("path")

BrowserContext brwsr= playwright.chromium().launchPersistentContext(userdirpath,lp)
Page page = browser.pages().get(0)
page.navigate("url")
page.locator("id=xxx").fill("val")
```

-------------

Above code will work fine when the locator is corrct , if the locator is not correct , its not throwing any error ,its just waiting . Kindly share your thoughts 

Thanks in Advance

**Comment by aslushnikov** [comment]
@bibinmohana The [`locator.fill()`](https://playwright.dev/java/docs/next/api/class-locator#locator-fill) method will wait for 30 seconds for the element to resolve. You can configure this timeout though - please check out our documentation!

**Comment by bibinmohana** [comment]
@aslushnikov  Thanks for the update , I have actually refedeed the document . In my case even if I wait for 10 mins also its not throwing any error,It will pause execution  at the line where the locator has issue. I have to stop or else will get stuck after sometime.

**Comment by aslushnikov** [comment]
@bibinmohana do you get the same behavior if you launch just a simple chrome without any extension? E.g.

```java
Path extn1path=Path.get("")
Path ext2path=Path.get("")

List<String> chromeArgs= new ArrayList<>()

BrowserType.LaunchPersistentContextOptions lp=new BrowserType.LaunchPersistentContextOptions();
lp.setChannel("chrome")
lp.setHeadless(false)
lp.args=chromeArgs
lp.setDevtools(false)

Path userdirpath=Paths.get("path")

BrowserContext brwsr= playwright.chromium().launchPersistentContext(userdirpath,lp)
Page page = browser.pages().get(0)
page.navigate("url")
page.locator("id=xxx").fill("val")
```

**Comment by bibinmohana** [comment]
@aslushnikov 
Thanks for the response !I tried the below simple code , even am facing the same issue there .

Playwright playwright = Playwright.create()
LaunchOptions lp= new LaunchOptions()
lp.setChannel("chrome")
lp.setHeadless(false)
Browser browser = playwrightt.chromium.launch(lp)
Page page= browser.newPage()
page.navigate(url)
page.locator("wrong locator").fill(value)
browser.close()
playwight.close()

**Comment by bibinmohana** [comment]
@aslushnikov 
That was a miss from myend ! Its working fine now !
