### ISSUE TITLE
I am trying to split my long end to end test 

### ISSUE THREAD

**Issue by srikanthathikari** [microsoft/playwright#16684]
I am trying to split my long end-to-end test into multiple smaller files but that should run as a single test when I run the npm test command. What it means is the flow that I am currently working on is a long test scenario from login to checkout. In this case, I want the tests to be split into multiple specs and run them all together either by doing an import and adding the imported function into the test or test. describe. Is there a way I could do that? One idea that I am trying to implement is using  web pack, which is not successful so far. 

https://github.com/srikanthathikari/Playwright/tree/feat-webpack

Please find the git repo attached.

**Comment by aslushnikov** [comment]
@srikanthathikari you should split your test into multiple and use [serial mode](https://playwright.dev/docs/next/test-retries#serial-mode) to run them in sequence.

**Comment by srikanthathikari** [comment]
@aslushnikov I did use serial at the beginning of the tests. However, I want to have 1 test in one spec file and the other one in another spec file but run them as a single test.

![image](https://user-images.githubusercontent.com/25626394/185650706-9e6b9a7b-34d6-4ae3-9b48-5bca3c73ac20.png)

**Comment by aslushnikov** [comment]
@srikanthathikari ah, i see. Then you can use a [test list pattern](https://playwright.dev/docs/next/test-parallel#use-a-test-list-file)

**Comment by srikanthathikari** [comment]
@aslushnikov,  Thank you.   I used the test list pattern as well, however, the test list pattern did not help me continue the test where the previous spec file was ended, Instead, it opens a new browser window where it considers the new spec file as a new test all together.

**Comment by aslushnikov** [comment]
> Thank you. I used the test list pattern as well, however, the test list pattern did not help me continue the test where the previous spec file was ended, Instead, it opens a new browser window where it considers the new spec file as a new test all together.

@srikanthathikari I'm not sure I follow what you see and what you expect. For example, here's what I tried:

```ts
// foo.ts
import { test, expect } from '@playwright/test';

export function addTests() {
  test('foo test - 1', () => {
    expect(1).toBe(1);
  });

  test('foo test - 2', () => {
    expect(1).toBe(2);
  });
}
```

```ts
// bar.ts
import { test, expect } from '@playwright/test';

export function addTests() {
  test('bar test - 1', () => {
    expect(1).toBe(1);
  });

  test('bar test - 2', () => {
    expect(2).toBe(2);
  });
}
```

and finally the spec file:

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';
import * as foo from './foo';
import * as bar from './bar';

test.describe.serial('all tests', () => {
  foo.addTests();
  bar.addTests();
});
```

When I run `npx playwright test`, I get the following output, and it seems to be working properly for me:

```
aslushnikov:~/tmp$ npx playwright test

Running 4 tests using 1 worker

  ✓  1 foo.ts:4:3 › all tests › foo test - 1 (5ms)
  ✘  2 foo.ts:8:3 › all tests › foo test - 2 (1ms)
  -  3 bar.ts:4:3 › all tests › bar test - 1
  -  4 bar.ts:8:3 › all tests › bar test - 2


  1) foo.ts:8:3 › all tests › foo test - 2 =========================================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

       7 |
       8 |   test('foo test - 2', () => {
    >  9 |     expect(1).toBe(2);
         |               ^
      10 |   });
      11 | }
      12 |

        at /Users/andreylushnikov/tmp/foo.ts:9:15


  1 failed
    foo.ts:8:3 › all tests › foo test - 2 ==========================================================
  2 skipped
  1 passed (263ms)
aslushnikov:~/tmp$
```

So could you please file a new issue that demonstrates the behavior that you don't like, in the way I did here above?

I'll close this one since it's unclear what's going on here and my triaging rotation is over.
