### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by temidayorb** [microsoft/playwright#16683]
Hello! I am testing a workflow and 2 of the steps in this workflow require that I click on next button. Mind you, clicking on the next button the first time loads a new page (iframe) but next button not in the iframe and the URL stays the same. On the second attempt on trying to click on "next" , playwright always goes back to the previous page to find and click "next". It is company code and I am not able to share code or screenshots. 

Anyone has any idea of the problem could be?

**Comment by aslushnikov** [comment]
> On the second attempt on trying to click on "next" , playwright always goes back to the previous page to find and click "next".

@temidayorb Are you using [locators](https://playwright.dev/docs/next/locators) to click elemenst?

**Comment by temidayorb** [comment]
Yes I used locators

**Comment by temidayorb** [comment]
Will also like to add that the next button has similar attributes, so I am guessing Playwright defaults to the one from previous page.

**Comment by KaushikTest** [comment]
@temidayorb , as you mentioned its an iframe, may I know if you are switching to iframe and trying to find the locator?

**Comment by aslushnikov** [comment]
(Closing this since we contacted privately)
