### ISSUE TITLE
[BUG] WebKit - net::ERR_CONTENT_DECODING_FAILED not throwing on Linux

### ISSUE THREAD

**Issue by codykaup** [microsoft/playwright#16682]
**Context:**
- Playwright Version: 1.22.2
- Operating System: Mac/Linux
- Node.js version: 14.17.3
- Browser: WebKit

## System:
 - OS: Linux 5.13 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 91.09 MB / 967.93 MB
 - Container: Yes
## Binaries:
 - Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v14.17.3/bin/yarn
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

```json
{
  "name": "playwright-test",
  "version": "1.0.0",
  "main": "index.js",
  "dependencies": {
    "@hapi/hapi": "20.2.2",
    "@hapi/inert": "7.0.0",
    "playwright": "1.22.2"
  }
}
```

```javascript
const { webkit } = require('playwright');
const Hapi = require('@hapi/hapi');
const Inert = require('@hapi/inert');

const init = async () => {
  const server = Hapi.server({
    port: 3000,
    host: 'localhost',
  });

  await server.register(Inert);

  server.route({
    method: 'GET',
    path: '/',
    handler: {
      file: 'test.html',
    },
  });

  server.route({
    method: 'GET',
    path: '/net_err.jpg',
    handler: (request, h) => {
      return h
        .response('not gzipped')
        .type('image/jpeg')
        .header('content-encoding', 'gzip');
    },
  });

  await server.start();
  console.log('Server running on %s', server.info.uri);
};

init();
(async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();

  page.on('pageerror', (exception) => {
    console.log(`Uncaught exception: "${exception}"`);
  });

  page.on('console', async (msg) => {
    const values = [];
    for (const arg of msg.args()) values.push(await arg.jsonValue());
    console.log(...values);
  });

  page.on('requestfailed', (request) => {
    console.log(request.url() + ' ' + request.failure().errorText);
  });

  page.on('response', async (response) => {
    console.log(`${response.url()}: ${response.status()}`);
  });
  await page.goto('http://localhost:3000/');
  await browser.close();
  console.log('done!');
})();
```

```html
<!-- Filename: test.html -->

<!DOCTYPE html>
<html>
  <body>
    <img src="http://localhost:3000/net_err.jpg" alt="A Bad Image" />
  </body>
</html>
```

**Describe the bug**

I'm seeing some odd behavior with `net::ERR_CONTENT_DECODING_FAILED` not throwing on Linux but is throwing on MacOS. In the example above, I'm trying to force that error but I get two different responses depending on the OS I'm using:

**MacOS**

```
Server running on http://localhost:3000
http://localhost:3000/: 200
http://localhost:3000/net_err.jpg cannot decode raw data

done!
```

**Linux/Playwright Docker Container**

```
Server running on http://localhost:3000
http://localhost:3000/: 200
http://localhost:3000/net_err.jpg: 200

done!
```

I tried adding event listeners to catch any console output (included in the example above) to see if the error was logging but I don't get anything there either. Is there a way to catch these errors and throw them like MacOS?

**Comment by aslushnikov** [comment]
>  Is there a way to catch these errors and throw them like MacOS?

@codykaup so it looks like WebKit @ macOS and WebKit @ Linux use different network stacks, thus the gzip decoding fails. There's no way for us to port macOS network stack to Linux!

I wonder what's your usecase?

**Comment by codykaup** [comment]
That's what I figured, thanks!

We've been using Chrome/Firefox for quite a while so all our tests are written around catching these errors to stop capturing a series of requests if these `net::ERR_*` errors pop up. Simply adding WebKit worked fine on our Mac laptops but our CI pipeline breaks down since it's all Docker-based (same with production).

Do these errors simply disappear somewhere in the network stack so Playwright doesn't get any indication of the failure?

**Comment by aslushnikov** [comment]
> We've been using Chrome/Firefox for quite a while so all our tests are written around catching these errors to stop capturing a series of requests if these net::ERR_* errors pop up. Simply adding WebKit worked fine on our Mac laptops but our CI pipeline breaks down since it's all Docker-based (same with production).

@codykaup Got it. Yeah, unfortunately there are some low-level differences between different platforms. 

> Do these errors simply disappear somewhere in the network stack so Playwright doesn't get any indication of the failure?

 It looks so! It's unlikely we'll be able to be helpful here.  I'll close this since there's not much we can do :(
