### ISSUE TITLE
How to start codegen from any line of a code?

### ISSUE THREAD

**Issue by MsLolita** [microsoft/playwright#16685]
hello, how to start codegen from any point in the script, for example, write page.codegen()

**Comment by aslushnikov** [comment]
@MsLolita try using the new VSCode extension for this!

**Comment by MsLolita** [comment]
> @MsLolita try using the new VSCode extension for this!

and what is the name of the app

**Comment by aslushnikov** [comment]
Here! https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright#:~:text=The%20extension%20automatically%20detects%20if,in%20multiple%20or%20different%20browsers.

**Comment by MsLolita** [comment]
> Here! https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright#:~:text=The%20extension%20automatically%20detects%20if,in%20multiple%20or%20different%20browsers.

But it is only js and ts I suppose, how to use it with python

**Comment by aslushnikov** [comment]
> But it is only js and ts I suppose, how to use it with python

@MsLolita Ah sorry, I didn't get you need python! Could you please file a separate issue for this?
