### ISSUE TITLE
[BUG] Firefox not clicking in hidden element but chrome and webkit it works

### ISSUE THREAD

**Issue by cunhabruno** [microsoft/playwright#16688]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Mac / Linux
- Node.js version: 14
- Browser: Firefox

I am trying to interact with a textarea element using Firefox, but it shows the below error, but it works fine on Chrome and Webkit tough.

> page.click: Target closed
=========================== logs ===========================
waiting for selector ".inputarea"
  selector resolved to hidden <textarea wrap="off" tabindex="0" data-mprt="6" role="text…></textarea>
attempting click action
  waiting for element to be visible, enabled and stable
    element is not visible - waiting...
============================================================

Application under test: https://microsoft.github.io/monaco-editor/playground.html
Follow a repository with the issue being reproduced:
https://github.com/cunhabruno/monaco-playwright-ff-bug
Github actions running in chome: https://github.com/cunhabruno/monaco-playwright-ff-bug/actions/runs/2890931585
Githyb actions running in Firefox: https://github.com/cunhabruno/monaco-playwright-ff-bug/actions/runs/2890945144

**Comment by aslushnikov** [comment]
I see Firefox exits with the following error:

> Running Nightly as root in a regular user's session is not supported.  ($HOME is /github/home which is owned by uid 1001.)

So you should configure your container to use `pwuser` to run tests:

https://stackoverflow.com/a/58956931/314883

Hope this helps!
I'll close this for now, but feel free to file another one if there are more questions.

**Comment by cunhabruno** [comment]
Sorry @aslushnikov that was the wrong error, nor this one have the correct error I wanted to show you:
https://github.com/cunhabruno/monaco-playwright-ff-bug/runs/7999930305?check_suite_focus=true#step:6:29
