### ISSUE TITLE
[internal] TypeScript installation test checks broken

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#16695]
```
Error: node_modules/@types/node/globals.d.ts(8,5): error TS2717: Subsequent property declarations must have the same type.  Property 'cause' must be of type 'Error', but here has type 'unknown'.
```

https://github.com/microsoft/playwright/runs/7925781055?check_suite_focus=true#step:9:24

**Comment by rwoll** [comment]
Looks like it's a newly added test: https://github.com/microsoft/playwright/commit/e725b5f8a9787107c04609f4dd0ccca6a998d3c9#diff-7c3926caae437612b5f1d6acb1c2d034eb931d077f6c077b18f8b6dfee0efaad

@mxschmitt from the error, I can't tell if this is an issue with Playwright or upstream with the combo of typescript version + NodeNext + @types/node.

**Comment by mxschmitt** [comment]
Looks like https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61790 gets reverted, should be fixed soon.

**Comment by rwoll** [comment]
Upstream https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61790, will be reverted
