### ISSUE TITLE
[BUG] Page.click doesn't work inside of fixed & hidden containers

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1669]
**Context:**
- Playwright Version: 0.12.1
- Operating System: macOS

**Code Snippet**
```javascript
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://cdpn.io/celeryclub/debug/zYGVYJj/yoAZEOvKpZDr', { waitUntil: 'networkidle0' });
  await page.waitFor(1000);

  await page.click('.btn-continue');

  await browser.close();
})();
```

**Describe the bug**
Hi team. I think I've found an issue with `Page.click`, or perhaps with the the actionability checks in general. In certain conditions, the actionability checks won't time out after 30s. They'll just hang forever. Here's how I've been able to reproduce it:

```
Container with `position: fixed`
  Container with `visibility: hidden`
    The element I'm trying to click
```

The strange thing is that if I pass a timeout to `.click` (`await page.click('.btn-continue', { timeout: 5000 });`), it *does* give me the error message I'd expect after 5s (`TimeoutError: waiting for element to receive mouse events failed: timeout 5000ms exceeded`).

Here's the codepen link in case the debug URL above expires.
https://codepen.io/celeryclub/pen/zYGVYJj

**Comment by pavelfeldman** [comment]
I'll take a look at the timeout.

The bug title suggests that the behaviour is not expected as well, should I be looking there as well or is it about timeout only?

**Comment by celeryclub** [comment]
Yes - sorry if my wording was unclear. I do believe this is a bug. Sometimes the actionability checks hang without timing out, which is unexpected - they should time out after 30s.

The only reason I mentioned passing a shorter timeout is to possibly provide a clue that may help in getting to the bottom of the issue. Thank you for digging into it!

**Comment by pavelfeldman** [comment]
So... closing this since I fixed the timeout. Please reopen if there is more to fix!

**Comment by celeryclub** [comment]
Thanks so much @pavelfeldman! That fixes my issue. I have a question for you about this commit though. Is there a specific reason the timeout value was removed from the logging? I found it helpful in debugging. https://github.com/microsoft/playwright/commit/c6f580faf8078ebed1e3b0d0ffc5cf394c13bcc1#diff-4ed3b5cf36b0791325d60bc5b73064d4L848
