### ISSUE TITLE
[Feature] WebRTC Emulation Support for Playwright

### ISSUE THREAD

**Issue by nirazv** [microsoft/playwright#16692]
I am using Playwright for testing multi-account browsing therefore leveraging proxy and emulating geolocations, time-zone is useful. but some website eg: [https://browserleaks.com/ip](https://browserleaks.com/ip) are still able to detect my public ip which is leads to DNS leak problem. Is there any way to emulate WebRTC public IP using Playwright? 

I have found a [github feature request post](https://github.com/microsoft/playwright/issues/2973) but no progress is made on behalf.

**Comment by aslushnikov** [comment]
@nirazv I don't think there's a way currently; the #2973 is not very popular so not highly prioritized.

Merging this in #2973!

**Comment by nirazv** [comment]
Using Playwright with Proxy Automation is useless without WebRTC Emulation. Its not ye popular but will be highly demanded in future.

**Comment by dilutedev** [comment]
From the future here :) totally agree!

> Using Playwright with Proxy Automation is useless without WebRTC Emulation. Its not ye popular but will be highly demanded in future.
