### ISSUE TITLE
[Feature] Add new CLI param (--params) 

### ISSUE THREAD

**Issue by Sam-Eldin** [microsoft/playwright#16708]
Let us know what functionality you'd like to see in Playwright and what your use case is. add an option to send options as Json Object/ Json file, this way we'll params.something, like running mode, having an automate test runner that triggers playwright with a json object as params to use inside the test.
Do you think others might benefit from this as well? yes, absolutely.

**Comment by mxschmitt** [comment]
Relates to https://github.com/microsoft/playwright/issues/7539

**Comment by aslushnikov** [comment]
Merging to https://github.com/microsoft/playwright/issues/7539!
