### ISSUE TITLE
[BUG] - Playwright browser leaks IP while using a proxy

### ISSUE THREAD

**Issue by nirazv** [microsoft/playwright#16702]
How to prevent or emulate DNS ip? I was using proxy for emulating different geo locations browsing but in this test url [https://browserleaks.com/ip](https://browserleaks.com/ip) i can see my Public IP is leaking maybe caused by WebRTC protocol. 

How to emulate or set custom private or public ip or modify WebRTC parameter?
Here are the code of playwright I am using in Java

```
public class PlayWrightKit {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(false));
            BrowserContext brcx = browser.newContext(
                    new Browser.NewContextOptions()
                            .setTimezoneId("EET")
                            .setGeolocation(58.595402,25.052695)
                            .setProxy(new Proxy("my-proxy-address")
                                    .setUsername("my-proxy-username")
                                    .setPassword("****"))

            );
            Page page = brcx.newPage();
            page.navigate("https://whoer.net/");
            TimeUnit.MINUTES.sleep(2);
//            browser.close();
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
}
```

**Comment by nirazv** [comment]
[BUG] - Playwright browser leaks IP while using a proxy

Playwright Chromium, Firefox browser leaks IP while using a proxy. It makes proxies useless because Google can detect your public IP address via WebRTC and for this reason Google shows captcha even with a new proxy and a different verify fp.

How to reproduce:
Open webkit browser and go to: https://browserleaks.com/webrtc

**Comment by aslushnikov** [comment]
I believe this is similar to https://github.com/microsoft/playwright/issues/16692 and should be merged to https://github.com/microsoft/playwright/issues/2973 as well!
