### ISSUE TITLE
[Question] Extend Page with method / function

### ISSUE THREAD

**Issue by jmthomas** [microsoft/playwright#16709]
This probably isn't specific to playwright but my Typescript-fu isn't awesome enough to figure out a generic solution. I'd like to extend the Page class with my own utilities. I did this in my fixure where I'm already extending the page like so:

    import { test as base } from '@playwright/test'
    import { Utilities } from '../utilities'
    export const test = base.extend({
      page: async ({ baseURL, toolPath, page }, use) => {
        // Add the Utilities to the page
        page['utils'] = new Utilities(page)
        await use(page)
      },
    })
    export { expect } from '@playwright/test'

This allows me to use it in a test:

    test('test something', async ({ page }) => {
      await page.utils.myFunction()
    })

This works but I'm not sure if that's the best solution. I'm also getting a ton of `Property 'utils' does not exist on type 'Page'.ts` in Visual Studio Code because of course it doesn't know what I'm doing. I had also considered doing

    Object.getPrototypeOf(page).utils = new Utilities(page)

and while that also works it doesn't get me closer in VS Code and I'm not sure if it has any benefits.

Is there a recommended way to add custom functions to the framework so they're available in any of the tests via the page object?

**Comment by mxschmitt** [comment]
We don't support extending the Page type, but you can create a helper fixture, which is very similar, and you are already almost there!

```ts
import { test as base } from '@playwright/test'
import { Utilities } from '../utilities'
export const test = base.extend<{
  utils: Utilities,
}>({
  utils: async ({ page }, use) => {
    await use(new Utilities(page))
  },
})
export { expect } from '@playwright/test'
```

```ts
test('test something', async ({ utils }) => {
  await utils.myFunction()
})
```

See here: https://playwright.dev/docs/test-fixtures#creating-a-fixture

**Comment by jmthomas** [comment]
Thanks for responding @mxschmitt. I tried that but if I pass `new Utilitiles(page)` to the `await use` I'm unable to also pass the `page` object. It seems `use` only accepts 1 parameter: `Expected 1 arguments, but got 2.`. I don't really want to change the original signature of all my tests `test('does stuff', async ({ page }) => {` because I'm directly using the page object throughout with `page.locator`, etc. That's why I was looking to add my utilities directly to the page object so they could be accessible throughout without any code changes. 

What I'm doing now with `page['utils'] = new Utilities(page)` actually works so this isn't critical but it's annoying to see all the red underlines in VS Code since it can't figure out the typing.

**Comment by yury-s** [comment]
You can extend default fixture type like this: 

```ts
import { Page, test as base } from '@playwright/test'
import { Utilities } from '../utilities'

export type ExtendedPage = Page & {
    utils: Utilities;
};

export const test = base.extend<{
    page: ExtendedPage
}>({
  page: async ({ page }, use) => {
    page.utils = new Utilities(page)
    await use(page)
  },
})
export { expect } from '@playwright/test'
```

but I'd recommend you do like Max suggested and pass utils separately to keep playwright types separate from yours:
```js
test('does stuff', async ({ page, utils }) => {
```

**Comment by jmthomas** [comment]
Thanks @yury-s! I didn't realize I could call `await use(new Utilities(page))` and then still call
    
    test('does stuff', async ({ page, utils }) => {

and use the page object. I like your original solution. For anyone who is a little slow on Typescript (like me!) I added an additional 2 parameters and this is my solution (fixture.ts):
 
    import { expect, test as base } from '@playwright/test'
    import { Utilities } from '../utilities'
    
    export const test = base.extend<{
      utils: Utilities
      toolPath: string
      toolName: string
    }>({
      toolPath: '/tools/cmdtlmserver',
      toolName: 'CmdTlmServer',
      utils: async ({ baseURL, toolPath, toolName, page }, use) => {
        await page.goto(`${baseURL}${toolPath}`, {
          waitUntil: 'networkidle',
        })
        await expect(page.locator('.v-app-bar')).toContainText(toolName, {
          timeout: 20000,
        })
        await use(new Utilities(page))
      },
    })
    export { expect } from '@playwright/test'

I then use it in my tests like so:
    
    import { test, expect } from './fixture'    
    test.use({
      toolPath: '/tools/cmdsender',
      toolName: 'Command Sender',
    })
    
    test('do stuff', async ({ page, utils }) => {
      await utils.do_stuff()
      await page.locator('main')
    })
