### ISSUE TITLE
can not access element in the nested frames

### ISSUE THREAD

**Issue by RNONGFU001** [microsoft/playwright#16701]
### Your question

I experienced a problem when I do some web automation on a legacy aspnet site. (a private deploy site)

the page has total 4 frames, top, body, footer and one child frame in body frame.

I want to access an input in the child frame using below code

```csharp
await page.FrameLocator("iframe[name=\"__Content\"]").FrameLocator("iframe[name=\"iframe-exe_iframe_RET501_Main\"]").Locator("#IMCondition_SubmitDate_range_begin").FillAsync($"{datafile.DateFrom:yyyy/MM/dd}");
```
like above said, the body frame's  name is __content, but the wired thing is that I got below timeout error message

```
Timeout 30000ms exceeded.
=========================== logs ===========================
  waiting for frame "iframe[name="__Content"]"
  selector resolved to visible <iframe border="0" noresize="" id="__Content" scrolling=…></iframe>
  waiting for frame "iframe[name="iframe-exe_iframe_RET501_Main"]"
  selector resolved to visible <iframe screenw="986" screenh="470" scrolling="no" frame…></iframe>
waiting for selector "iframe[name="__Content"] >> control=enter-frame >> iframe[name="iframe-exe_iframe_RET501_Main"] >> control=enter-frame >> #IMCondition_SubmitDate_range_begin"
============================================================
```
seems the engine could not locate the final input. I did a lot of research, but failed to get a solution, and did not know why...

I do not know what is wrong with above code, which is actually generated by recorder, and or is there anything I missed.

thanks for your help!

**Comment by aslushnikov** [comment]
@RNONGFU001 this might be a bug, but in order for us to fix it, we'll need a way to run a repro locally to debug it.

Could you please build a simple sample page that illustrates this iframe structure and exhibits the bug? Once you have it, please re-file!
