### ISSUE TITLE
[Question] How to ignore running files in a dir

### ISSUE THREAD

**Issue by shinokada** [microsoft/playwright#16710]
I have a dir which is not in the `.gitignore`.

When I revert the commit and test, I get an error.

I know `testProject.testIgnore` but this is for test files.

Is there any way to ignore a directory or files when I run `playwright test`?

Something like this:

```
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
	fullyParallel: true,
	ignoreDirwhilerun: '**/typechecktests/**',
	webServer: {
		command: 'npm run build && npm run preview',
		port: 4173
	}
};

export default config;
```

**Comment by mxschmitt** [comment]
`testIgnore` which is the opposite of `testMatch`: https://playwright.dev/docs/api/class-testconfig#test-config-test-ignore

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
