### ISSUE TITLE
[BUG] Spurious Success of Click

### ISSUE THREAD

**Issue by JoeyRxy** [microsoft/playwright#16712]
**Context:**
- Playwright Version: [1.25.0]
- Operating System: [Windows]
- Node.js version: [v14.19.3]
- Browser: [Firefox]

**Description**

There are a series of bugs, and I find I can't fix the final bug by retry, so I report these bugs.

The bug at the beginning is a spurious success of clicking a dropdown: After clicking the dropdown and Playwright reports click done, it turns out the dropdown actually hasn't been clicked. 

This is a weird bug but I use retry strategy to fix it: I will repeat clicking dropdown until dropdown list is open.

```ts
while (true) {
    try {
        await <locator of dropdown list>.waitFor({timeout: TIMEOUT});
        break;
    } catch (e) {
        <trigger>.click();
    }
}
```

But I find out sometimes the `waitFor` will emit a spurious success which claims the element has been found but actually hasn't.

So I think this may be some bugs of `waitFor`, then I use `<locator>,count()` method to detect whether the element shows. 

```ts
while (retry >= 0) {
    if (await locator.count() > 0) break;
    await Helper.sleep(1000);
    --retry;
}
```
But still, I find out sometimes `locator.count()` > 0 but the element doesn't appear.

These bugs don't occur every time.

**Comment by aslushnikov** [comment]
@JoeyRxy This does look like a bug, but it's impossible to act upon without something we can run locally and debug. Any chance you can provide a page or something that is minimalistic yet reproduces this behavior?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
