### ISSUE TITLE
[REGRESSION]: route.fulfill returns a null response when the request is done with fetch

### ISSUE THREAD

**Issue by hdorgeval** [microsoft/playwright#1671]
**Context:**
- GOOD Playwright Version: [0.11.1]
- BAD Playwright Version: [0.12.1]
- Operating System: [Mac]
- Extra: []

**Code Snippet**

I have published a repo that demonstrates the problem: https://github.com/hdorgeval/playwright-bug-report

[test file](https://github.com/hdorgeval/playwright-bug-report/blob/master/src/on-request-to-respond-with.chromium.test.ts) 

**Describe the bug**

The test is using fetch to simulate a call to a remote rest api. The call to the rest api is intercepted and the json response should be mocked, but instead of the expected mocked response, a null response is received together with an error on the request: `_failureText:"net::ERR_FAILED`.

If, in the package.json file, you downgrade Playwright to v0.11.1, the tests is ok.

Thank you for your help.

**Comment by pavelfeldman** [comment]
You are making a `fetch` from a page loaded using the `file:` protocol. Browser can't do that, you should load your page off the same `localhost:1234` origin to be able to fetch. Following snipeed makes it work:

```js
    await page.goto(`http://localhost:1234`);
    const html = await util.promisify(fs.readFile)(path.join(__dirname, 'on-request-to-respond-with.test.html'));
    await page.setContent(html.toString());
```

**Comment by hdorgeval** [comment]
Hi @pavelfeldman , thank you very much for your time and your great support 👍 . 

I completely miss the not-the-same-origin mistake on my side :(
Your suggested snippet works perfectly :)
Thanks!
