### ISSUE TITLE
[BUG] Unable to capture a snapshot of the full page with webkit (on some websites)

### ISSUE THREAD

**Issue by Rafiot** [microsoft/playwright#16727]
**Context:**
- Playwright Version: 1.25.1 (python, but I don't think it is limited to python)
- Operating System: Linux
- Node.js version: N/A (python 3.10)
- Browser: webkit

**Code Snippet**

Code used for the snapshot: https://github.com/Lookyloo/PlaywrightCapture/blob/main/playwrightcapture/capture.py#L374

Probably important: I pass `full_page=True` to the screenshot and the pages failing are pretty big. I tried to increase the timeout and it has no impact (which is in line with the exception).

**Describe the bug**

The following exception is raised when I trigger a snapshot of the full page with webkit: 

```
playwright._impl._api_types.Error: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]
```

It happens on some websites (salon.com, wort.lu, ...), and only when the browser is webkit.

**Comment by yury-s** [comment]
You are probably hitting some limits. We need a repro to act on this, please attach a small test preferably with a page that doesn't change over time (salon.com does) which we can run locally. The following simple test worked just fine:

```js
test('screensot', async({ page }) => {
	await page.goto('https://www.salon.com/');
	await page.screenshot({path: '/tmp/page.png', fullPage: true});
});
```

**Comment by Rafiot** [comment]
I can reproduce it consistently with this code (sorry, it's in python):

```python
#!/usr/bin/env python3

import asyncio
from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as playwright:
        browser_name = playwright.devices['BlackBerry Z30']['default_browser_type']
        browser = await playwright[browser_name].launch()
        context = await browser.new_context(**playwright.devices['BlackBerry Z30'])
        page = await context.new_page()
        await page.goto('http://wort.lu', wait_until='load')
        await page.screenshot(full_page=True)


asyncio.run(main())
```

**Comment by yury-s** [comment]
Still not reproducible on my machine. Try running with `DEBUG=pw:browser` and see if there are any errors printed to the terminal?

**Comment by Rafiot** [comment]
This is the output I'm getting:

```
$ (git::main) DEBUG=pw:browser python test_snap_fail.py 
  pw:browser <launching> /home/raphael/.cache/ms-playwright/webkit-1699/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=269283 +6ms
  pw:browser [pid=269283] <gracefully close start> +5s
  pw:browser [pid=269283] <process did exit: exitCode=0, signal=null> +6ms
  pw:browser [pid=269283] starting temporary directories cleanup +0ms
  pw:browser [pid=269283] finished temporary directories cleanup +3ms
  pw:browser [pid=269283] <gracefully close end> +0ms
Traceback (most recent call last):
  File "/home/raphael/gits/PlaywrightCapture/tests/test_snap_fail.py", line 27, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/raphael/gits/PlaywrightCapture/tests/test_snap_fail.py", line 24, in main
    await page.screenshot(full_page=True)
  File "/home/raphael/.cache/pypoetry/virtualenvs/playwrightcapture-ONX8HyGK-py3.10/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 8015, in screenshot
    await self._impl_obj.screenshot(
  File "/home/raphael/.cache/pypoetry/virtualenvs/playwrightcapture-ONX8HyGK-py3.10/lib/python3.10/site-packages/playwright/_impl/_page.py", line 655, in screenshot
    encoded_binary = await self._channel.send("screenshot", params)
  File "/home/raphael/.cache/pypoetry/virtualenvs/playwrightcapture-ONX8HyGK-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 43, in send
    return await self._connection.wrap_api_call(
  File "/home/raphael/.cache/pypoetry/virtualenvs/playwrightcapture-ONX8HyGK-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 387, in wrap_api_call
    return await cb()
  File "/home/raphael/.cache/pypoetry/virtualenvs/playwrightcapture-ONX8HyGK-py3.10/lib/python3.10/site-packages/playwright/_impl/_connection.py", line 78, in inner_send
    result = next(iter(done)).result()
playwright._impl._api_types.Error: Protocol error (Page.snapshotRect): Could not capture snapshot [{"code":-32000,"message":"Could not capture snapshot"}]
=========================== logs ===========================
taking page screenshot
============================================================

```

**Comment by pavelfeldman** [comment]
I can reproduce with:

```js
test.describe(() => {
  test.use({ deviceScaleFactor: 2 });
  test('repro', async ({ page }) => {
    await page.goto('http://wort.lu', { waitUntil: 'networkidle' });
    await page.screenshot({ fullPage: true });
  });
});
```

We are trying to capture a screenshot of size `{ width: 1289, height: 23332 }`

**Comment by yury-s** [comment]
Turns out this is a limitation that stems from cairo library on linux(see https://bugs.webkit.org/show_bug.cgi?id=168964). WebKit linux will not allocate image with any dimension greater than 32768 (see [this constant](https://github.com/WebKit/WebKit/blob/527e978d67e3d07aec9aa46e52664884df44d348/Source/WebCore/platform/graphics/ImageBackingStore.h#L39)).

**Comment by yury-s** [comment]
Yeah, this is the hard limit in the cairo lib at the moment: https://github.com/freedesktop/cairo/blob/c188715bbebe4d8ed756e503e1da0bb96b3ec69d/src/cairo-image-surface.c#L59-L90 It could be mitigated by titling the screenshot image in WebKit as described in the linked bug, but this would be quite a big effort. For now we can improve the error message that playwright returns.

**Comment by yury-s** [comment]
@Rafiot as a workaround you can take the screenshots with [`scale: 'css'`](https://playwright.dev/docs/api/class-page#page-screenshot-option-scale) which will only require image 1289 x 23492 and will pass:

```js
  await page.screenshot({ path: '/tmp/page.png', fullPage: true, scale: 'css' });
```

**Comment by Rafiot** [comment]
Neat! Thank you for the follow up, I'll do that.
