### ISSUE TITLE
[BUG] RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2876747111) is greater than 2 GB

### ISSUE THREAD

**Issue by araghuvarun** [microsoft/playwright#16725]
Hi,

Am trying to upload a file of more than 2GB in size and getting the below error : 

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2876747111) is greater than 2 GB
           at readFileHandle (internal/fs/promises.js:273:11)

**Context:**
- Playwright Version: 1.24.2
- Operating System: MAC
- Node.js version: v14.15.4
- Browser: Chromium
- Language : Typescript
- FileSize that am uploading : 2.8 GB

```typescript
await this.page.locator("div input[name='file’]").setInputFiles(filePath);
```

Please let me know how to resolve this issue.

**Comment by yury-s** [comment]
Can you share stack trace and complete reproducible example where it fails? I tried it locally but it works just fine with a 3GB file.

**Comment by araghuvarun** [comment]
Please find the below details:

Method am using : 
await this.page.locator("div input[name='file’]").setInputFiles(filePath);

It's working fine upto 85 MB. Failing if the file size is more than that.

RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2876747111) is greater than 2 GB
           at readFileHandle (internal/fs/promises.js:273:11)
           at async /node_modules/playwright-core/lib/client/elementHandle.js:308:18
           at async Promise.all (index 0)
           at async convertInputFiles (/node_modules/playwright-core/lib/client/elementHandle.js:304:24)
           at async Frame.setInputFiles (/node_modules/playwright-core/lib/client/frame.js:492:14)

Can you please provide the below details that is working for you with 3GB file :

Playwright Version: 
Operating System:
Node.js version: 
Browser:
Language :
Method used to upload :

**Comment by yury-s** [comment]
> Can you please provide the below details that is working for you with 3GB file :

See [this test](https://github.com/microsoft/playwright/blob/e4be1266a92932be32e538bcbb2683dceb4ba9ab/tests/page/page-set-input-files.spec.ts#L40-L86), you can increase file size to 3GB, I ran it on macOS 12.5.1 with same setup is yours but Playwright 1.25.1

**Comment by araghuvarun** [comment]
I have upgraded my macOS version to 12.5.1 and also Playwright to 1.25.1. Still facing the issue :

FeautreFile step:
When user uploads video file to Videos folder

StepDefinition:
When('When user uploads video file to Videos folder',{ timeout: 9000000 }, async function(){
  await testPage.uploadFile(file,folder);
});
 
TestPage.ts :        
public async uploadFile(): Promise<void> {
        let filePath = "./files/largeFile.m4v";
        await page.locator("div input[name='file']"").setInputFiles(filePath);
        await page.click("//*[text()='Upload']); //upload button in the application
    }
    
Present Error :
frame.setInputFiles: Target closed

Previous Error :
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2876747111) is greater than 2 GB
           at readFileHandle (internal/fs/promises.js:273:11)
           at async /node_modules/playwright-core/lib/client/elementHandle.js:308:18
           at async Promise.all (index 0)
           at async convertInputFiles (/node_modules/playwright-core/lib/client/elementHandle.js:304:24)
           at async Frame.setInputFiles (/node_modules/playwright-core/lib/client/frame.js:492:14)
           
As mentioned earlier, it is absolutely working fine upto 60-75MB. Failing if the size is more than that.
Please let me know if any modifications required in my code.

**Comment by araghuvarun** [comment]
Can anyone please update on this

**Comment by araghuvarun** [comment]
Yes. I see it is pointing to 1.20.1 version. Though I have 1.25.1 version in my local package.json, it's taking from our project common repository and showing 1.20.1. After properly updating, it is working fine. :)
Able to upload more than 2.5GB file as per our requirement.

npm ls playwright to check the playwright versions? - This helped. thanks !
