### ISSUE TITLE
[BUG] browser.newContext({ locale: 'de-DE', timezoneId: 'Europe/Berlin' }); not affecting new Date format

### ISSUE THREAD

**Issue by wopperer** [microsoft/playwright#16728]
**Context:**
- Playwright Version: 35a9daa4255f2ba556d4d7af6243cc84d1ac4f2a
- Operating System: Mac
- Node.js version: v16.15.1
- Browser: ff1345 installed in .local-browsers 

```
Running 2775 tests using 10 workers
  1) [firefox] › library/browsercontext-locale.spec.ts:55:1 › should format date ===================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "Sat Nov 19 2016 19:12:34 GMT+0100 (Mitteleuropäische Normalzeit)"
    Received: "Sat Nov 19 2016 19:12:34 GMT+0100 (Central European Standard Time)"

      67 |     await page.goto(server.EMPTY_PAGE);
      68 |     const formatted = 'Sat Nov 19 2016 19:12:34 GMT+0100 (Mitteleuropäische Normalzeit)';
    > 69 |     expect(await page.evaluate(() => new Date(1479579154987).toString())).toBe(formatted);
         |                                                                           ^
      70 |     await context.close();
      71 |   }
      72 | });
```

run `npm run ftest` to reproduce the issue

**Comment by yury-s** [comment]
What is `Browser: ff1345 `, is it some custom build? The test passes with bundled firefox.

**Comment by wopperer** [comment]
I [installed it locally](https://playwright.dev/docs/browsers) with `PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install` which places firefox binary 1345 into node_modules/playwright-core/.local-browsers.

**Comment by yury-s** [comment]
`PLAYWRIGHT_BROWSERS_PATH=0` should not matter, does it fail without the env variable?

I cannot reproduce it with the same setup. What is your macOS version and system language setting maybe that matters?

**Comment by aslushnikov** [comment]
@wopperer the test works for me as well and passes on a variety of our test bots. We'll need way more details to be able to reproduce this!

**Comment by wopperer** [comment]
It fails with and without the env variable set. My system language is German and Mac OS is 12.4 on M1.
Actually there are more than one test failing with my setup. 
When I run `npm run test` I get these errs:

[Playwright Test Report.pdf](https://github.com/microsoft/playwright/files/9399984/Playwright.Test.Report.pdf)

**Comment by pavelfeldman** [comment]
> My system language is German

This is something we didn't try.

> When I run npm run test I get these errs

Not sure what's happening here - I only have 2 failures in screenshots (we keep pixel expectations for Intel upstream, so this is expected).

**Comment by rdelcampog** [comment]
@pavelfeldman can you please let us know if you need some extra tests to prioritize this? The `timezoneId` set in the browser context is not working on Firefox. Thank you!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
