### ISSUE TITLE
[BUG] devices has incorrect type

### ISSUE THREAD

**Issue by bgotink** [microsoft/playwright#16723]
**Context:**
- Playwright Version: any version released in the last 2 years, perhaps longer
- Operating System: n/a
- Node.js version: n/a
- Browser: n/a
- Extra: n/a

**Describe the bug**

I'm trying to extend the devices to add extra properties, but the type of `devices` is currently invalid. The value of `devices` is an object, but it's listed as array with extra properties.

https://github.com/microsoft/playwright/blob/16ab54db441e268abbfdf49dc05ec44271706cad/packages/playwright-core/types/types.d.ts#L11185

This is incorrect, e.g.

```js
> require('@playwright/test').devices[0]
undefined
> require('@playwright/test').devices.length
undefined
> require('@playwright/test').devices.at
undefined
```

and it results in funky types when extending the devices, because all array methods get added to `typeof devices`

```ts
// Would be great if DeviceDescriptor (and perhaps even Devices?) were exported somewhere
type ExtendedDevice = (typeof devices)[string] & {
  myFixture: true,
};

const extendedDevices: {[K in keyof typeof devices]: ExtendedDevice} = {} as any;
```

![image](https://user-images.githubusercontent.com/821510/185922172-44114be8-1496-4dc6-a7a9-305a3ccfb162.png)

**Comment by yury-s** [comment]
There is a bug in the type definition, it's a map but not an array (should be `export const devices: Devices;`), I'm fixing that. To get the value types (DeviceDescriptor) you can use `type DeviceDescruptorType = typeof devices[string];`
