### ISSUE TITLE
[Question] Should screenshot option to hide caret work with Custom Elements (Shadow DOM)?

### ISSUE THREAD

**Issue by bellindj** [microsoft/playwright#16732]
I love the fairly new options for the screenshotter to fast forward animations and hide carets. Implementing these will remove manual workarounds we had to implement for our tests.

I'm not sure if this is a bug or intentional, but screenshot.caret's implementation (caret: "hide") does not work with Shadow DOM for custom elements. Conversely, disabling animations does work with Shadow DOM (animations: "disabled").

You can see in the source code these are next to each other, disableAnimations clearly traverses the DOM tree but hideCaret just applies a style at the document.

disableAnimations
https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/screenshotter.ts#L162

hideCaret
https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/screenshotter.ts#L151

Before filing a bug I wanted to check whether this was intentional. It seems like they should both work with custom elements for consistency.

**Comment by yury-s** [comment]
This seems to be a bug, can you share a page where it reproduces?

**Comment by danbellinski-8451** [comment]
@yury-s - thanks for your prompt reply. You're right that it does seem to work fine with normal web components. Took me a bit of debugging to reproduce. It looks like it takes a pretty specific combination of setup - a web component needs to slot an input into another web component that has a slot and the "all: initial" CSS property set.

This test below will produce a snapshot with a cursor in it. I used 1100ms timeout just to time it right for the cursor to be blinking on.

```
import { test, expect } from '@playwright/test';

test.describe.parallel(`renders`, () => {
  test('test caret focus', async ({ page }) => {
    await page.addScriptTag({
      content: `
      class CustomElementContainer extends HTMLElement {
        #shadowRoot;
        constructor() {
          super();
          this.#shadowRoot = this.attachShadow({ mode: 'open' });
          this.#shadowRoot.innerHTML = '<custom-element-input-wrapper><input type="text"/></custom-element-input-wrapper>';
        }
      }
      class CustomElementInputWrapper extends HTMLElement {
        #shadowRoot;
        constructor() {
          super();
          this.#shadowRoot = this.attachShadow({ mode: 'open' });
          this.#shadowRoot.innerHTML = '<style>:host { all: initial; }</style><slot/>';
        }
      }
      customElements.define('custom-element-input-wrapper', CustomElementInputWrapper);
      customElements.define('custom-element-container', CustomElementContainer);

      const container = document.createElement('custom-element-container');
      document.body.appendChild(container);`,
    });

    const element = await page.locator('input');
    await element.press('a');
    await page.waitForTimeout(1100);
    const image = await element.screenshot({
      animations: 'disabled',
      caret: 'hide',
    });
    expect(image).toMatchSnapshot('snap');
  });
});
```

**Comment by yury-s** [comment]
@danbellinski-8451 thanks for the test! I can reproduce the failure locally.

**Comment by aslushnikov** [comment]
I further reduced this to the following:

```js
document.body.innerHTML = `
  <style>
    *:not(#playwright-aaaaaaaaaa.playwright-bbbbbbbbbbb.playwright-cccccccccc.playwright-dddddddddd.playwright-eeeeeeeee) {
      caret-color: red; 
    }
  </style>
`;

document.body.attachShadow({ mode: 'open' }).innerHTML = `
  <input value="first shadow root">
  <section>
`;

const section = document.body.shadowRoot.querySelector('section');
section.attachShadow({ mode: 'open' }).innerHTML = `
  <style>:host { all: initial; }</style>
  <input value="second shadow root"/>
`;
```

**Comment by danbellinski-8451** [comment]
Thanks for the great support guys!
