### ISSUE TITLE
[BUG] CSS are not loaded using Playwright/Webkit in some cases

### ISSUE THREAD

**Issue by mbouchotsuricate** [microsoft/playwright#16745]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Linux (Lubuntu 18.04 on VirtuaBox VM)
- Node.js version: 16.17.0
- Browser: Webkit
- Extra: NA

**Issued Code Snippet**

```javascript
const { webkit, devices } = require('playwright');

(async () => {
    const options = {
        devtools: false,
        headless: false,
        dumpio: true,
        ignoreHTTPSErrors: true,
        args: []
    };
    const browser = await webkit.launch(options);
    const context = await browser.newContext({
        ...devices['iPhone 11'],
        ignoreHTTPSErrors: true,
        serviceWorkers: 'block'
    });

    const page = await context.newPage();

    await context.route('**', route => {
        route.continue();
    });

    await page.goto('https://www.picard.fr/');
    await page.locator('#onetrust-accept-btn-handler').tap();

    await page.locator('[href="https://www.picard.fr/on/demandware.store/Sites-picard-Site/fr_FR/Account-Show"]').tap();
    //await browser.close();
})();
```
**Working Code Snippet**

```javascript
const { webkit, devices } = require('playwright');

(async () => {
    const options = {
        devtools: false,
        headless: false,
        dumpio: true,
        ignoreHTTPSErrors: true,
        args: []
    };
    const browser = await webkit.launch(options);
    const context = await browser.newContext({
        ...devices['iPhone 11'],
        ignoreHTTPSErrors: true,
        serviceWorkers: 'block'
    });

    const page = await context.newPage();

    /*await context.route('**', route => {
        route.continue();
    });*/

    await page.goto('https://www.picard.fr/');
    await page.locator('#onetrust-accept-btn-handler').tap();

    await page.locator('[href="https://www.picard.fr/on/demandware.store/Sites-picard-Site/fr_FR/Account-Show"]').tap();
    //await browser.close();
})();
```

**Describe the bug**

The bug is that when we declare instruction "context.route" or "page.route" on our playwright scripts, on Webkit, all css declared with <link rel="preload"... are not loaded on the page but css declared with <link rel="stylesheet"... are properly loaded (as expected). if we remove the instruction context.route (as written on the working snippet), all css are properly loaded.
NB : You will see the obvious difference of style between the working and issued snippets.

**Comment by yury-s** [comment]
I don't have credentials to open the page (getting 401). Is there a test account we could use to see the bug or maybe you can share relevant files so that we could serve them locally?

**Comment by mbouchotsuricate** [comment]
I've just sent you an email with an updated version of the script containing proxy settings.

**Comment by yury-s** [comment]
Thanks for sharing the repro, I can confirm that with `route` only `commonHP-critical.css` is loaded but without request interception I also see `commonHP.css`. Works fine in Chromium.
