### ISSUE TITLE
[BUG] waitForResponse timeout while response is correctly received

### ISSUE THREAD

**Issue by skysantoroa** [microsoft/playwright#16746]
**Context:**
- Playwright Version: 1.25
- Operating System: Ubuntu 22
- Node.js version: 16
- Browser: Chromium, Webkit

**Code Snippet**

The following code should wait for a response received from polling my backend.

```typescript
const results = await Promise.all([
    page.waitForResponse(
      async (res) => await isTransactionError(baseURL!, res),
    ),
    page.locator('input[type="file"]').setInputFiles(promoFilePath),
  ])
```

```typescript
export const isTransactionError = async (
  baseUrl: string,
  response: Response,
) => {
  if (response.url() === `${baseUrl}graphql`) {
    const { 'content-length': contentLength, 'content-type': contentType } =
      await response.allHeaders()
    if (+contentLength > 0 && contentType === 'application/json') {
      const json = await response.json()
      const lastStage = json?.data?.node?.stages?.at(-1)
      const res =
        response.status() === 200 &&
        lastStage?.__typename === 'ValidationStage' &&
        lastStage?.state === 'ERROR' &&
        lastStage?.errors?.length > 1
      if (res) {
        console.log(`transaction id ${json?.data?.node?.id}`)
      }
      return res
    }
  }

  return false
}
```

**Describe the bug**

The expected response is received and correctly handled by my client but the `waitForResponse` method timeouts. With the first retry the test passes.

The failed test trace reports no Network information for the latest response.json and that the timeout comes from the line `const json = await response.json()`.

![image](https://user-images.githubusercontent.com/101178279/186101902-e5e65522-ffe2-4a33-ac9f-2c22cb955f2f.png)

Another detail I should mention is that whenever the polling starts, thus the wait for the response, the URL changes.

Here is the test output run from docker
```
playwright     |     Test timeout of 120000ms exceeded.
playwright     | 
playwright     |     page.waitForResponse: Page closed
playwright     | 
playwright     |       75 |
playwright     |       76 |   const results = await Promise.all([
playwright     |     > 77 |     page.waitForResponse(
playwright     |          |          ^
playwright     |       78 |       async (res) => await isTransactionError(baseURL!, res),
playwright     |       79 |     ),
playwright     |       80 |     page.locator('input[type="file"]').setInputFiles(promoFilePath),

```

**Comment by yury-s** [comment]
> The expected response is received and correctly handled by my client

Can you elaborate on how you check that the response is actually received?

> but the waitForResponse method timeouts. 

The server doesn't complete the response and `response.json()` keeps hanging waiting for the last byte of the response which leads to timeout. In such case the trace will not contain the network request and partial response which we should fix.

Can you share a reproducible example which we could run locally?

**Comment by skysantoroa** [comment]
> Can you elaborate on how you check that the response is actually received?

The response is handled by polling using Apollo Client and consumed from an `useEffect` by a React client.

The following is the `response.allHeaders` captured from the `isTransactionError` method (that should be related to the latest `response.json` I guess?):

```
headers: [{"name":"Date","value":"Mon"},{"name":"Date","value":"22 Aug 2022 09:40:34 GMT"},{"name":"Content-Type","value":"application/json"},{"name":"Content-Length","value":"1101"},{"name":"Connection","value":"keep-alive"},{"name":"Content-Security-Policy","value":"default-src 'self' cdn.jsdelivr.net/npm/graphql-playground-react/build/; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net/npm/graphql-playground-react/build/static/css/; font-src https://static.skyassets.com data:; frame-ancestors 'none'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net/npm/graphql-playground-react/build/static/js/"},{"name":"X-Frame-Options","value":"DENY"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"Referrer-Policy","value":"no-referrer"},{"name":"Server","value":"nginx/1.23.1"},{"name":"Strict-Transport-Security","value":"max-age=31536000; includeSubDomains"}]
```

> response which leads to timeout

Why is it timing out? The response received before the last one should correctly resolve the `waitForResponse`.

> Can you share a reproducible example which we could run locally?

I'm not able to, I'm sorry. If the `trace.zip` file doesn't leak the source code of my client I can provide it

**Comment by skysantoroa** [comment]
Could it be that when the `waitForResponse` is invoked the `page` is changing url after setting the input file? Right after the selection is done, the client starts polling, when the upload is complete the url will change.
By looking at the `waitForResponse` that is timing out you can see the url change

Before
`/upload-file`
After
`/upload-file/79898cd1-7428-409b-bb19-ca140b06b564`.


Firefox instead is printing the following error when the last `response.json` is empty (not Network info)

`[JavaScript Error: "Content Security Policy: The page’s settings blocked the loading of a resource at data:image/svg+xml,<svg xmlns='http://ww… (“default-src”)."]
`

Whereas in the `allHeaders` entry there is this message in the Console tab

`[JavaScript Warning: "Strict-Transport-Security: The connection to the site is untrustworthy, so the specified header was ignored." {file: "URL/graphql" line: 0}]
`

**Comment by skysantoroa** [comment]
Another update: I managed to look at the complete Network information from the dev tools when debugging the issue and all the responses are ok so far yet the `waitForResponse` remains stuck.
However I'm getting this warning in the console

```
Source map error: Error: NetworkError when attempting to fetch resource.
Resource URL: .../static/js/main.004dfb2e.js
Source Map URL: main.004dfb2e.js.map
```
