### ISSUE TITLE
[Feature] Accessibility.snapshot should not ignore iframe content

### ISSUE THREAD

**Issue by AutoSponge** [microsoft/playwright#1675]
**Context:**
- Playwright Version: 0.12.1
- Operating System: Mac
- Extra: n/a

**Code Snippet**

```javascript
await page.goto('https://bold-vaulted-faucet.glitch.me/')
await page.accessibility.snapshot()
// notice nothing is returned after the `role: 'iFrame'` object
```

**Describe the bug**

This may only be in Chrome...

The CDP command `Accessibility.getFullAXTree` also does not walk iframes. However, as this lib is a convenience wrapper, I'm hoping you'll accept this feature request. I've been able to build a "full" axTree from scratch by using `getPartialAXTree` on the `#document` found in `DOM.getDocument`. Sadly, `getPartialAXTree` only returns a few nodes and this must be called repeatedly until all nodes have exposed their children.

This works, however, it means I have to use hacks to create `elementHandle` in page context for using methods like `elementHandle.screenshot`. It would be better if snapshot returned a full tree.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
