### ISSUE TITLE
Cannot locate element marked with _ngcontent

### ISSUE THREAD

**Issue by thedavidhoffman** [microsoft/playwright#16754]
I'm using Angular, and no matter what I do, if I have a DOM element marked with _ngcontent I cannot access it using Playwright. I've tried all manner of locators/selectors, by id, by text, by class, and none of them work. If I go to the console in a browser, I am able to locate the element using a jQuery selector. I've also tried adding setTimeout with 10 seconds before attempting to locate the element. I am also polyfilling waitForAngular per the Playwright documentation (https://playwright.dev/docs/protractor#polyfilling-waitforangular)

The only thing I've found on the web that seems to be related is this post explaining the same issue, but with Protractor...
https://groups.google.com/g/angular/c/X7ddgWNn7f8

Here's the important part of that related Google groups post...

![image](https://user-images.githubusercontent.com/5252941/186174901-67717652-70e2-482b-b640-fabdf9cd6c94.png)

I have about 170 Playwright tests I've written against my Angular app, but this is the first time I'm having to interact with DOM elements marked with _ngcontent. I thought I was going crazy because any other time I use the Locator I can target anything in the DOM I need to. But I am absolutely stuck trying to get past this.

Please tell me I'm doing something stupid that has a simple solution :)

**Comment by thedavidhoffman** [comment]
Stupid user error.

**Comment by spaniardmaximus** [comment]
I'm here now, I don't suppose that you can tell me how did you fix it? :)
