### ISSUE TITLE
[BUG] html report duration is different than the actual duration

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#16750]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Mac
- Node.js version: 18.3.1
- Browser: Chromium
- Extra: npx playwright test demo-todo-app.spec.js --project=chromium --trace on --config=e2e/playwright.config.js

 
https://user-images.githubusercontent.com/61405630/186151623-cc2da069-0e75-44c0-8420-b28d037d518b.mov

**Describe the bug**
6 seconds actual duration presented as 37 seconds duration in the HTML report
default playwright init config with the default todo example test

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/11334, please upvote that issue instead.
