### ISSUE TITLE
start Electron react boiler plate using npm start and testing playwright  and CI

### ISSUE THREAD

**Issue by 2BC-Wasabi** [microsoft/playwright#16752]
hi everyone,

I want to setup CI, when i do the tests locally i have to build and install the application, i haven't found a way to test while using the npm install.
i'm new to CI and i still need to learn alot i guess, i was wondering if anyone knows: 
1. how to run tests in the development environment (using npm start)?
2. how to run CI with electron on bitbucket?

**Comment by yury-s** [comment]
> I want to setup CI, when i do the tests locally i have to build and install the application, i haven't found a way to test while using the npm install.

This is rather generic question and you should start with the documentation of the CI that you are going to use. We can provide help if something related to playwright does not work but writing a comprehensive guide on how to setup CI is out of this project's scope.

> * how to run tests in the development environment (using npm start)?

You can define you playwright config and add corresponding commands to package.json similar to [this](https://github.com/microsoft/playwright/blob/6ebd3ea61f9cb5dbc8b13e75ab394ac6e392f4f7/package.json#L20)

> * how to run CI with electron on bitbucket?

StackOverflow or our slack channel would be better places for such questions.

**Comment by 2BC-Wasabi** [comment]
i think i wasn't very clear about using npm start, 
i did define a command called e2e, 
when i start the electron app i use the following predefined commands 
`
  "start": "ts-node ./.erb/scripts/check-port-in-use.js && npm run start:renderer",
`

`
  "start:main": "cross-env NODE_ENV=development electronmon --trace-warnings -r  ts-node/register/transpile-only .",
`

`
  "start:preload": "cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack --config ./.erb/configs/webpack.config.preload.dev.ts",
`

`
"start:renderer": "cross-env NODE_ENV=development TS_NODE_TRANSPILE_ONLY=true webpack serve --config ./.erb/configs/webpack.config.renderer.dev.ts",
`

i was wondering if it's possible to attach playwright to it, since it's easier to test rather than building and installing the app.
