### ISSUE TITLE
[BUG] test-results folder is not deleted upon tests start

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#16751]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Mac & Docker in CI
- Node.js version: 14.19.2
- Browser: All

**Describe the bug**

It seems that the `./test-results` folder is not fully cleaned/deleted up anymore. I write a custom txt file in that directory (to keep all test run related files in one place) and now information is just appended to that file. Previously (checked 1.23 version) the folder was fully deleted upon tests start.

**Comment by yury-s** [comment]
Cannot reproduce it on my mac:

```ts
import { test } from '@playwright/test';
import fs from 'fs';

test('append to file', async({ page }) => {
    const file = test.info().outputPath('out.txt');
    const d = Date.now().toString();
    fs.appendFileSync(file, `${d}\n`);
});
```

Can you share your code?

**Comment by MindaugasMateika** [comment]
Hmm, can't repro in a new project. I'll dig and reopen if needed.
Thank you for your time
