### ISSUE TITLE
[BUG] The batch file cannot be found.

### ISSUE THREAD

**Issue by jschlade** [microsoft/playwright#16759]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by yury-s** [comment]
It's unclear from the description what you are trying to do and what is not working. I guess the problem is with launching Playwright? Please file a new one with more details and link to this issue when you get back to it!

**Comment by jschlade** [comment]
Hi,

First of all. I would like to thank you for developing this API. It's incredibly useful.
Seeing a few bugs related to exiting a java application.

1) Is I get this "The batch file cannot be found." error. See BatchMessageError1 class.

C:\Users\jdoe>C:\Work\Java\jdk1.8.0_321\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022\lib\idea_rt.jar=61127:C:\Program Files\JetBrains\IntelliJ IDEA 2022\bin" -Dfile.encoding=UTF-8 -classpath "C:\Work\Java\jdk1.8.0_321\jre\lib\charsets.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\deploy.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\access-bridge-64.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\cldrdata.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\dnsns.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\jaccess.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\jfxrt.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\localedata.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\nashorn.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunec.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunjce_provider.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunmscapi.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunpkcs11.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\zipfs.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\javaws.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jce.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jfr.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jfxswt.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jsse.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\management-agent.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\plugin.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\resources.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\rt.jar;C:\Work\Projects\Java\Playwright\target\classes;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\playwright\1.25.0\playwright-1.25.0.jar;C:\Users\jdoe\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\jdoe\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\driver\1.25.0\driver-1.25.0.jar;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\driver-bundle\1.25.0\driver-bundle-1.25.0.jar" org.example.BatchMessageError1
Fast and reliable end-to-end testing for modern web apps | Playwright

C:\Users\jdoe>The batch file cannot be found

2) I see the application hangs on exit with BatchMessageError2 class.

C:\Users\jdoe>C:\Work\Java\jdk1.8.0_321\bin\java.exe "-javaagent:C:\Program Files\JetBrains\IntelliJ IDEA 2022\lib\idea_rt.jar=61127:C:\Program Files\JetBrains\IntelliJ IDEA 2022\bin" -Dfile.encoding=UTF-8 -classpath "C:\Work\Java\jdk1.8.0_321\jre\lib\charsets.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\deploy.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\access-bridge-64.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\cldrdata.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\dnsns.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\jaccess.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\jfxrt.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\localedata.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\nashorn.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunec.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunjce_provider.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunmscapi.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\sunpkcs11.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\ext\zipfs.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\javaws.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jce.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jfr.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jfxswt.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\jsse.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\management-agent.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\plugin.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\resources.jar;C:\Work\Java\jdk1.8.0_321\jre\lib\rt.jar;C:\Work\Projects\Java\Playwright\target\classes;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\playwright\1.25.0\playwright-1.25.0.jar;C:\Users\jdoe\.m2\repository\com\google\code\gson\gson\2.8.9\gson-2.8.9.jar;C:\Users\jdoe\.m2\repository\org\opentest4j\opentest4j\1.2.0\opentest4j-1.2.0.jar;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\driver\1.25.0\driver-1.25.0.jar;C:\Users\jdoe\.m2\repository\com\microsoft\playwright\driver-bundle\1.25.0\driver-bundle-1.25.0.jar" org.example.BatchMessageError2
Fast and reliable end-to-end testing for modern web apps | Playwright
[examples.zip](https://github.com/microsoft/playwright/files/9404199/examples.zip)

The process tried to write to a nonexistent pipe.
The system cannot find the path specified

Running on Windows 10, Java 8, with browsers that come with 1.25

**Comment by jschlade** [comment]
**yury-s** Please re-open this issue. Thanks
