### ISSUE TITLE
[Question] Fixture, how can I send the page instance for multiple pages.

### ISSUE THREAD

**Issue by oscargforce** [microsoft/playwright#16768]
Hello!

See the attached picture for my code. 
I need to automate chat functionality between two browsers.

patientAppPages is one page object for the patient chat.
clinicPages is another page object from the practitioner PoV.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/102926658/186219209-5301c4c4-a2e0-4f73-bd21-c4bc02176119.png">

PatientAppPages can be controlled by adding "page"  fixture in my test like this: 
`it("should work ", async ({page, clinicPages, patientAppPages }) => {
    await page.goto("https://patientApp.com") 
})`

But there is no way for me to navigate to the clinicPages url or to control that instance of the page.
It simply creates a blank page.

I do not want to navigate to the url in the fixture. I need the page instance for clinicPages for my other functions.

Is this possible?

**Comment by yury-s** [comment]
You can store the page in the wrapper classes and then expose it to the tests:

```ts
// Assuming one of the POM classes defined like this:
class ClinicPages {
    page: Page;
    constructor(page: Page) {
        this.page = page;
    }
    async gotoLandingPage() {
        await this.page.goto('https://clilic-url');
    }
};

// In the test you can do something like this:
it("should work ", async ({clinicPages, patientAppPages }) => {
    await patientAppPages.page.goto("https://patientApp.com");
    await clinicPages.page.goto('https://clilic-url');
    // or alternatively using POM method:
    await clinicPages.gotoLandingPage();
})
```
Will that work for you?

**Comment by oscargforce** [comment]
Yes thank you 🙏

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
