### ISSUE TITLE
[Question] How to use multiple server option in Playwright config?

### ISSUE THREAD

**Issue by canopy-js-user** [microsoft/playwright#16778]
Playwright recently added support for launching multiple test servers: https://github.com/microsoft/playwright/pull/15388/files

I'm not understanding this from the documentation:

> The `port` (but not the `url`) gets passed over to Playwright as a [`property: TestOptions.baseURL`]. For example port `8080` produces `baseURL` equal `http://localhost:8080`. If `webServer` is specified as an array, you must explicitly configure the `baseURL` (even if it only has one entry).

My config looks like:

```
  webServer: [
    {
      command: 'serve -p 3000',
      port: 3000
    },
    {
      command: 'serve -p 3001',
      port: 3001
    },
    {
      command: 'serve -p 3002',
      port: 3002
    },
    {
      command: 'serve -p 3003',
      port: 3003
    }
  ]
  use: {
    actionTimeout: 0,
    baseURL: 'http://localhost/',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
  },
};
```

So I do have a base URL, and I'm specifying ports, but when I run `npx playwright test` I'm getting an error:

```
TypeError [ERR_INVALID_URL]: Invalid URL: http://localhost:undefined
    at onParseError (internal/url.js:279:9)
    at new URL (internal/url.js:355:5)
    at getIsAvailableFunction (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/plugins/webServerPlugin.js:208:21)
    at new WebServerPlugin (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/plugins/webServerPlugin.js:58:25)
    at webServerPluginForConfig (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/plugins/webServerPlugin.js:232:10)
    at Runner._performGlobalSetup (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/runner.js:489:92)
    at Runner._runFiles (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/runner.js:427:39)
    at Runner._run (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/runner.js:224:12)
    at TimeoutRunner.run (/Users/azriel/canopy-js/node_modules/playwright-core/lib/utils/timeoutRunner.js:53:14)
    at raceAgainstTimeout (/Users/azriel/canopy-js/node_modules/playwright-core/lib/utils/timeoutRunner.js:113:15)
    at Runner.runAllTests (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/runner.js:182:20)
    at runTests (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/cli.js:162:18)
    at Ai.<anonymous> (/Users/azriel/canopy-js/node_modules/@playwright/test/lib/cli.js:70:7) {
  input: 'http://localhost:undefined',
  code: 'ERR_INVALID_URL'
}
```

and when I log the options that are getting passed to `webServerPlugin.js`, I get the following:

```
{
  '0': {
    command: 'serve -p 3000',
    port: 3000
  },
  '1': {
    command: 'canopy serve -p 3001',
    port: 3001
  },
  '2': {
    command: 'serve -p 3002',
    port: 3002
  },
  '3': {
    command: 'canopy serve -p 3003',
    port: 3003
  },
  url: 'http://localhost:undefined'
}
```

I think I'm just making a mistake in my config, but I'm not sure what.

Thanks!

**Comment by yury-s** [comment]
I was not able to reproduce the failure with the config you quoted, I only managed to trigger the error in a config containing `    {      command: 'npx serve -p 3003',    } `. Can you share the project where it happens? 


> I'm not understanding this from the documentation:
> 
> > The `port` (but not the `url`) gets passed over to Playwright as a [`property: TestOptions.baseURL`]. For example port `8080` produces `baseURL` equal `http://localhost:8080`. If `webServer` is specified as an array, you must explicitly configure the `baseURL` (even if it only has one entry).

The documentation can definitely be improved, assigning to Ross.

**Comment by canopy-js-user** [comment]
Hi there @yuri-s 

Here is the project / commit: https://github.com/canopy-js/canopy-js/commit/4870e57f3ded669fedb4f804868cbdd44a187f16

I removed some information to hide some project-specific complexity but maybe that context is necessary to get to the bottom of this.

Basically, I have a CLI that creates a build and then runs a server from it, and there are a few build options I am trying to test, so I thought I would copy the given directory and build it a different way each time in order to run tests against a build with those options:

```
  webServer: [
    {
      command: 'cd playwright/test_project && canopy build && canopy serve -p 3000',
      port: 3000
    },
    {
      command: 'cp -R playwright/test_project ./prefix_test && cd prefix_test && canopy build --project-path-prefix test && canopy serve -p 3001',
      port: 3001
    },
    {
      command: 'cp -R playwright/test_project ./prefix_test && cd prefix_test && canopy build --hash-urls && canopy serve -p 3002',
      port: 3002
    },
    {
      command: 'cp -R playwright/test_project ./prefix_test && cd prefix_test && canopy build --hash-urls --project-path-prefix test && canopy serve -p 3003',
      port: 3003
    }
  ],
```

However, I don't think the complexity of my use case is causing the problem, as this approach worked when there was only a single server.

You mentioned you were able to reproduce a similar error?

**Comment by canopy-js-user** [comment]
The problem seems to be this code:
`@playwright/test/lib/plugins/webServerPlugin.js`
```
const webServerPluginForConfig = (config, reporter) => {
  const webServer = config.webServer;
  if (webServer.port !== undefined && webServer.url !== undefined) throw new Error(`Exactly one of 'port' or 'url' is required in config.webServer.`);
  const url = webServer.url || `http://localhost:${webServer.port}`; // We only set base url when only the port is given. That's a legacy mode we have regrets about.

  if (!webServer.url) process.env.PLAYWRIGHT_TEST_BASE_URL = url; // TODO: replace with reporter once plugins are removed.
  // eslint-disable-next-line no-console

  return new WebServerPlugin({ ...webServer,
    url
  }, webServer.port !== undefined, reporter);
};
```

When there are multiple webservers specified, webServer is an array, and so `webServer.url` and `webServer.port` are both undefined, because it is the array items that have port properties, and so `http://localhost:${webServer.port}` is interpolating undefined.

Does this work for other people using multiple servers?

**Comment by canopy-js-user** [comment]
Woops, I was using a version of playwright locally before this feature had been added. Sorry for the trouble!
