### ISSUE TITLE
Is there any work around for running WebKit(playwright) on AWS EC2 Instance? [Question]

### ISSUE THREAD

**Issue by Gitadventure321** [microsoft/playwright#16771]
Below is the message I get while trying to test with webkit-playwright on my EC2 instance, chromium and firefox are fine:

║ Host system is missing dependencies to run browsers. 
║ Missing libraries:                                   
║     libpcre.so.3                                     
║     libicui18n.so.66                                 
║     libicuuc.so.66                                   
║     libwoff2dec.so.1.0.2                             
║     libgcrypt.so.20                                  
║     libjpeg.so.8                                     
║     libpng16.so.16                                   
║     libwebpdemux.so.2                                
║     libwebp.so.6                                     
║     libffi.so.7                                     
║     libx264.so         

 
node version: v17.3.0
playwright version: 1.25.0
os: NAME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2

Command used to install playwright: npm init playwright@latest
I was not allowed to choose to install dependencies at the time of installation. 

Used this command to install dependencies but doesn't work: npx playwright install-deps

**Comment by yury-s** [comment]
We provide official support only for Ubuntu linux, see [this page](https://playwright.dev/docs/troubleshooting#linux) and this issue https://github.com/microsoft/playwright/issues/9199. Automatic dependency installation will not work there as it is a different distribution, you may be able to install them manually though.

**Comment by Gitadventure321** [comment]
I tried the manual installation as posted in the question above, it doesn't work either, do you suggest any other way to install/command?

Used this command to install dependencies but doesn't work: npx playwright install-deps

**Comment by azarudeena** [comment]
@Gitadventure321  You have to use Ubuntu as OS instead of Amazon Linux. that's supported version for playwright. Please check link shared by @yury-s 

https://playwright.dev/docs/release-notes#-debian-11-bullseye-support
