### ISSUE TITLE
[Question] How can I repeat a request?

### ISSUE THREAD

**Issue by MsLolita** [microsoft/playwright#16776]
What are the ways to repeat the request? 
Example:
1. I go to the page and sniff the request via route() - that is, I get cookies and headers and then make a request with them.
2. I go to the page and then use APIRequestContext with parametres what I want.
These two methods that I guessed about are purely crutches for my question - they don't work because I don't know exactly but need js rendering. Is it possible in the request handler to write, for example: **route.repeat().**

**Comment by yury-s** [comment]
> These two methods that I guessed about are purely crutches for my question - they don't work because I don't know exactly but need js rendering. 

Can you elaborate on what exactly didn't work? Seeing you code snippet may help us better understand the problem.

> Is it possible in the request handler to write, for example: route.repeat().

No.

What you described sounds like a right approach, you cannot force the page send another request but you can send one via APIRequestContext or by evaluating `fetch()` in the page.

Check out our [Replay from HAR](https://playwright.dev/docs/network#record-and-replay-requests) guide, it may work for your use case if you want to mock some requests.

**Comment by MsLolita** [comment]
Minimum code snippet:
`from playwright.sync_api import sync_playwright
import httpx

def handle_route(route):
    res = httpx.get(url, headers=route.request.headers)
    print(res.text)
    route.continue_()

def run(playwright):
    chromium = playwright.firefox
    browser = chromium.launch()
    context = browser.new_context()
    page = context.new_page()
    page.route(url, handle_route)
    page.goto(url)
    browser.close()

if __name__ == "__main__":
    url = "https://tickets.fcbayern.com/internetverkaufzweitmarkt/SelectTicketMarketTickets.aspx"
    with sync_playwright() as playwright:
        run(playwright)`

response from this request: 
`  <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Challenge Validation</title>
        <link rel="stylesheet" type="text/css" href="/_sec/cp_challenge/sec-3-8.css">
        <script type="text/javascript">function cp_clge_done(){location.reload(true);}</script>
        <script src="/_sec/cp_challenge/sec-cpt-int-3-8.js" async defer></script>
        <script type="text/javascript">sessionStorage.setItem('data-duration', 5);</script>
      </head>
      <body>
        <div class="sec-container">
          <div id="sec-text-container"><iframe id="sec-text-if" class="custmsg" src="/_sec/cp_challenge/crypto_message-3-8.htm"></iframe></div>
          <div id="sec-if-container">
            <iframe id="sec-cpt-if" class="crypto" data-key="" data-duration=5 src="/_sec/cp_challenge/ak-challenge-3-8.htm"></iframe>
          </div>
        </div>
      </body>
    </html>
`
But in browser this response is not 50 lines but 1000 line of code. And how I can repeat it?

**Comment by yury-s** [comment]
The response I'm getting locally is different from above. Most likely a bot detection kicks in on the server end because the request differs from what the browser sends, the intercepted request might lack some of the low-level network headers (e.g. sec-ch-* etc.). Circumventing bot detection is not a goal for playwright. You can sniff the request on the server end, compare it with the intercepted request and pass missing headers to page.request.get() manually. If you figure out what makes the server return different response or provide a reliable repro that we could run locally we can help further.

**Comment by MsLolita** [comment]
> The response I'm getting locally is different from above. Most likely a bot detection kicks in on the server end because the request differs from what the browser sends, the intercepted request might lack some of the low-level network headers (e.g. sec-ch-* etc.). Circumventing bot detection is not a goal for playwright. You can sniff the request on the server end, compare it with the intercepted request and pass missing headers to page.request.get() manually. If you figure out what makes the server return different response or provide a reliable repro that we could run locally we can help further.

I substituted headers and cookies from Playwright in the request, but I received a part of the code that was not loaded. As I understand it, I need to use js rendering to pass the bot anti-detection, that is, browsers do this and execute javascript code on the page and let me in. But I would like to do it via a server request.

**Comment by pavelfeldman** [comment]
Closing as per above. If you don't want to perform the request outside the browser, you can always try fetching from within the page using `page.evaluate`. In either case this falls outside of the Playwright scope for automation and testing, hence closing.
