### ISSUE TITLE
[Feature] Browser event "context"

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1678]
Feature Request:

A browser event: 'context' emitted when a new context is created.

```
browser.on("context", (context) => context.addInitScript(...));
```

Our Use Case:

We use the browser context to capture logs and video artifacts.

Since there is no API to listen for new contexts, we require users to call `qawolf.register(context)` in their test code when they create a new context.

If we could listen for a `context` event we can manage this registration logic internally in our `launch` helper.

Other Use Cases:

This would be valuable to set up global init scripts and new page listeners.

**Comment by pavelfeldman** [comment]
Node events are synchronous, so the suggested syntax implies a race between the qawolf set up and context usage. I actually like the `qawolf.register` option - it is explicit and can be awaited.

**Comment by jperl** [comment]
The setup in `qawolf.register` really happens on the "page" event. And `qawolf.register` does not need to be awaited, except for the html selector registration which we will probably move to `launch`.

**Comment by pavelfeldman** [comment]
Marking it as out of scope for Playwright driver, you should use CDP for this.
