### ISSUE TITLE
[Feature] Support for mouse contextmenu event

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#16792]
I have a website where when the user right-clicks on an image I want to prevent the user from opening the context menu.

this would require being able to dispatch an event for contextmenu and being able to detect if the context menu is displayed

this could look something like this:
```ts
it('should display contextmenu popup', async ({ page }) => {
  const [contextmenu] = await Promise.all([
    page.waitForEvent('contextmenu'), // does not exist yet
    page.locator('#img').click({ button: 'right' })
  ]);
  await contextmenu.select('Open image in new tab');  // does not exist yet
})
```

dispatching the contextmenu event is already supported, I was not able to find information about the native context menu itself

![image](https://user-images.githubusercontent.com/9786571/186340295-babe5202-3d5f-486e-ad09-6ff9b79a615d.png)

**Comment by yury-s** [comment]
> I have a website where when the user right-clicks on an image I want to prevent the user from opening the context menu.

You should be able to detect that by checking if the default action has been prevented. Would that work?

```js
it('should not display contextmenu popup', async ({ page }) => {
  const [preventeDefault] = await Promise.all([
    page.evaluate(() => new Promise(fulfill => {
      document.body.addEventListener('contextmenu', e => fulfill(e.defaultPrevented));
    })),
    page.locator('#img').click({ button: 'right' })
  ]);
  expect(preventeDefault).toBeTruthy();
})
```

> dispatching the contextmenu event is already supported, I was not able to find information about the native context menu itself

Playwright doesn't provide any API to access the native context menu items.

**Comment by Meir017** [comment]
@yury-s this is definitely enough for now. should this stay open for future tracking of this if and when accessing the context-menu options will be possible?

**Comment by yury-s** [comment]
We don't have any plans to support native context menues automation but let's keep it open to see if it gets enough upvotes to prioritize it higher.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
