### ISSUE TITLE
[Question] - Why my tests fails when I used CodeceptJS (helper Playwright) with Bitbucket and Reportportal.

### ISSUE THREAD

**Issue by Miriambnzdn** [microsoft/playwright#16797]
Hello,
I've been using CodeceptJS with Bitbucket and ReportPortal for months and I'm having a problem that I don't understand.
Sometimes I can't click on my application "Logon" button, all the attempts fail even if the button is present, stable and clickable. I get no other error message or screen shots. All my other tests fail, including some tests where I have to log in again.

Did someone meet this issue before ?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one with an example which we can reproduce locally and link to this issue when you get back to it!
