### ISSUE TITLE
[Question] Is it possible to share the browser between `globalSetup` and `globalTeardown`?

### ISSUE THREAD

**Issue by liamdocherty10** [microsoft/playwright#16800]
We are currently using `globalSetup` in order to log in as admin user and setup data, then `globalTeardown` to delete the data at the end.

At the moment, both global functions are launching a browser and logging in as the admin user.

This works, but is there a way to share the same browser/ browser context instance between setup and teardown?

This would improve our efficiency since there is nothing in our tests that invalidates the session still active in the setup browser.

E.g.

- Config file
```ts
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve("./tests/global-setup"),
  globalTeardown: require.resolve("./tests/global-teardown"),
  // Remaining config
}
```

- Global Setup
```ts
async function globalSetup(): Promise<void> {
  const browser: Browser = await chromium.launch();
  const context: BrowserContext = await browser.newContext();
  const page: Page = await context.newPage();
  // Log in
  // Create data
}
```

- Global Teardown
```ts
async function globalTeardown(): Promise<void> {
  const browser: Browser = await chromium.launch();
  const context: BrowserContext = await browser.newContext();
  const page: Page = await context.newPage();
  // Log in
  // Delete data
}
```

**Comment by yury-s** [comment]
globalSetup and globalTeardown both run in the same process, so you can store the browser in a shared variable during setup and read it in global teardown:

```ts
// globalSetup.ts
import { chromium, FullConfig } from '@playwright/test';
import { globalState } from './shared';

async function globalSetup(config: FullConfig) {
  globalState.browser = await chromium.launch();
  await globalState.browser.newPage();
}

export default globalSetup;


// globalTeardown.ts
import { globalState } from './shared';

async function globalTeardown() {
  await globalState.browser?.close();
}

export default globalTeardown;


// shared.ts
import { type Browser } from '@playwright/test';

export const globalState: ({browser: Browser | undefined}) = {
  browser: undefined
};
```

https://github.com/microsoft/playwright/issues/14895 tracks ongoing improvements in global setup/teardown.

**Comment by liamdocherty10** [comment]
This has worked for us, thank you @yury-s
