### ISSUE TITLE
[REGRESSION]: No longer able to open traceviewer using playwright showtrace

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright#16804]
**Context:**
- GOOD Playwright Version: 1.23.0
- BAD Playwright Version: 1.25.1
- Operating System: Windows
- Extra: Python - although I don't think this matters in this case

When using command "playwright show-trace"

I get this error:

node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:9322
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9322
}

**Comment by gauravgandhi1315** [comment]
@jfp1992 It is working fine for me

**Comment by yury-s** [comment]
As the error message suggests something else is already running on 127.0.0.1:9322 on your machine(it may well be another instance of trace viewer), make sure that the port is free by closing the app that is using it.
