### ISSUE TITLE
Why is requestContext not working with new FormData POST?

### ISSUE THREAD

**Issue by lynn-fisher** [microsoft/playwright#16806]
I am using requestContext to submit JUnit report to Jira Xray in Playwright custom reporter but I am continually getting an error.

The code I am using works if I use Axios but not if I use Playwright request. I have tried variations on the code below with 
ContentType: 'multipart/form-data' and without but always get error

```
const bodyFormData = new FormData()

bodyFormData.append(File, JunitReportContent, filename)

const requestContext = await request.newContext({
ignoreHTTPSErrors: true,
extraHTTPHeaders:{
Authorization: Basic $${credentialsBase64}
})

const response = await requestContext.post(url, bodyFormData)
```

The error reads
```the request does not contain a multipart/form-data or multipart/mixed stream, content type header is application/octet-stream'```

Do you have any suggestions on how to submit Junit report to rest endpoint using requestContext?

**Comment by yury-s** [comment]
You need to pass the form data as [multipart](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post-option-multipart) option, something like this:

```js
  await requestContext.post(url, {
    multipart: {
      fileFieldName: {
        name: filename,
        mimeType: 'text/plain',
        buffer: Buffer.from(JunitReportContent)
      }
    }
  });

  // Or if you read it from filepath:
  await requestContext.post(url, {
    multipart: {
      fileFieldName: fs.createReadStream(filepath)
    }
  });
```

`FormData` is not supported as input type and is considered just as an object, this is why content-type is set to application/octet-stream.

**Comment by yury-s** [comment]
@lynn-fisher does the solution above work for you?

**Comment by chaitraAshu** [comment]
@yury-s  
Please give a solution for the below query.
Posting a request.  [see the attachment.
![image](https://user-images.githubusercontent.com/99385012/186834146-b5f00139-b118-4968-ae51-82406cdc07ab.png)

i will have to send a file, filename, data within the body.  this is how I'm trying to pass. but getting the error as 
apiRequestContext.post: Only one of 'data', 'form' or 'multipart' can be specified.
![image](https://user-images.githubusercontent.com/99385012/186834323-424fd5c6-7d1c-4e07-b899-3b8710f68498.png)

**Comment by lynnafisher** [comment]
Hi Yuri,

I will give it a go today and let you know how I get on. Apologies, didnt get a chance to look at it yesterday.

Many Thanks

Lynn

**Comment by yury-s** [comment]
> i will have to send a file, filename, data within the body. this is how I'm trying to pass. but getting the error as
> apiRequestContext.post: Only one of 'data', 'form' or 'multipart' can be specified.

You should put all the payload fields into multipart, they will be passed to the server as the form's key/value fields:

```js
multipart: {
  // assuming that payload is a map
  ...payload,
  // or in a separate field
  payloadFieldName: JSON.stringify(payload),
  File: {
    name: form,
    mimeType: 'application/zip',
    buffer: image,
  }
}
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
