### ISSUE TITLE
[BUG] routeFromHar with `update:true` doesn't respect advanced routing order

### ISSUE THREAD

**Issue by shashwatjolly** [microsoft/playwright#16815]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows
- Node.js version: 12.18.3
- Browser: Microsoft Edge

**Code Snippet**
```javascript
await context.routeFromHAR('./path-to-har-file.har', {update: true});
await context.route('**', async (route, request) => {
    const headers = {
        ...request.headers(),
        'Custom-Header': 'test-value'
    };
    route.fallback({headers});
});
```

**Describe the bug**
In the code above, the HAR file saved does not have the extra header added in the route handler.
The [release notes for v1.23.0](https://github.com/microsoft/playwright/releases/tag/v1.23.0) mention that the `routeFromHar` option "also participates in routing and could be deferred to." However, in the above case, the HAR file does not respect the route handler registration ordering and saves the original request instead of the modified request (with the additional header).

**Additional context: ** I have a website that hits an endpoint multiple times and may get different responses every time. I was trying to leverage the HAR recording and playback feature to exactly mimic API playback. Since the requests are identical, Playwright uses the first matching entry in the HAR file to fulfill the request, which doesn't satisfy my use case. As a workaround, I decided to add a custom header with increasing values to my requests using Playwright route handler. If these headers were written to the HAR file, Playwright would match different requests with the appropriate entries, leading to accurate playback.

**Comment by yury-s** [comment]
We record har request before applying route overrides, it should be fixed.
