### ISSUE TITLE
[Question] Is the use of parameters supported for locators inside of POM?

### ISSUE THREAD

**Issue by DanielStoica85** [microsoft/playwright#16824]
A very simple example would be having two or more options inside of a `select` element. Let's say they also share the same `className`. The only thing that differs about them is the text. 

So I would have to do something like:
```
constructor(page) {
    this.page = page;
    this.optionOne = page.locator('option[text=Option One']);
    this.optionTwo = page.locator('option[text=Option Two']);
}
```

And then I would click on them with `await this.optionOne.click()` for the first one and `await this.optionTwo.click()` for the second one.

Can I have one single function to click on the desired `option` based on its text, which is given as a parameter? Something like:

```
async clickOption(text) {
    await page.locator(`option[text=${text}]`).click();
}
```

P.S. The question applies for any other element, not just for `option` with text, of course.

**Comment by yury-s** [comment]
Once Locator is constructed it's selector cannot be changed, so you cannot pass a parameter to the locator which is already constructed. What you describe with clickOption seems like the best approach, what are the problems with it?
