### ISSUE TITLE
[Question] How to inspect spawned test worker

### ISSUE THREAD

**Issue by kriku** [microsoft/playwright#16829]
So recently I've tried to attach to debug port

```
node --inspect-brk ./node_modules/.bin/playwright test --debug ./test.spec.ts
```

Its open debugger on default port (9229)

But test runner spawns other process, which doesn't wait for inspector.

Could you explain, please, how I can provide inspect flag for spawned test process?

**Comment by yury-s** [comment]
If you goal is to debug a test you can try our [VSCode extension](https://playwright.dev/docs/getting-started-vscode#run-in-debug-mode) instead, would that work for you?

**Comment by kriku** [comment]
Actually I was looking for possibility to debug internals of test runner, context, fixtures and overall runtime of test suite.

For example with chrome devtools, convenient node process debugger...
<img width="1614" alt="Screenshot 2022-08-25 at 20 36 40" src="https://user-images.githubusercontent.com/6429161/186732326-efa2254a-dfa9-40c0-a601-8efc5893c390.png">

I can debug playwright cli, but not the test runner itself. I tried run with one worker, but still, it spawns other process without `--inspect` flag.

I looking how I can pass args for test workers.

**Comment by kriku** [comment]
Found this fork:
https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/dispatcher.ts#L512

Are there legal ways to add inspect flag?
```
      execArgv: ['--inspect-brk=9222'],
```

I already test it locally - it works, but looks hacky, make changes to node_modules

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
