### ISSUE TITLE
[Feature] Toggle check for frame receives events

### ISSUE THREAD

**Issue by htsvetkov** [microsoft/playwright#16828]
Hello,
with recent bump of playwright from 1.22 to 1.24 / 1.25, it was noticed and new bug-fix/feature for validation of click over frames.

This change was introduced with this two commits:
```
[BUG] Misclick when some element overlays the target's iframe
https://github.com/microsoft/playwright/issues/14752
```
```
Playwright missclicks on iframe instead on actual element
https://github.com/microsoft/playwright/issues/13762
```

More/less this is an test design/implementation issue, but also normally nobody wants to click outside the main port/frame.

With the quoted fixes above, this is a breaking change for existing tests, running on a website that have some different implementation, from the normal behavior or other element intercepts the frame actions.

Sometimes the tester is out of control, how the website is designed/implemented, and/or cannot "fix" the website due 3rd party implementation/integration/other reason.

So my point is this has to be under control with feature flag.

There is a similar topics already created as a "bug", where the "solution" is to use "force" flag for operations as click.
But the "force" disables all other auto-waiting actionability checks.

Proposing a feature flag to be introduced only for the check whether element is outside the main-frame, or other element receive events in iframe.

Code ref: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/dom.ts#L439

Thanks!

**Comment by dgozman** [comment]
@htsvetkov Do you mind sharing the repro that exhibits the issue? So far I understood that something regressed (in your tests?), but I don't understand what specifically is broken.

**Comment by htsvetkov** [comment]
Hello @dgozman,
thanks for the replay!

I cant provide an real environment for test, but will do my best to explain the case.

For example we are having website:

```
<html>
<body>
    <div id="container">
        <div id="iframecontainer">
            <div id="iframe">
                <div id="iframewrapper">
                    <!-- here we have #shadow-root (closed) -->
                    <iframe id="iframeResult" name="iframeResult">
                        <html>
                            <head></head>
                            <body>
                                <div>
                                    <button id="something"></button>
                                </div>
                            </body>
                        </html>
                    </iframe>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
```

The _iframe_ is wrapped in several _divs_.
When switching the context to work with frames in playwright.

```
// Finding frame by URL. or id
const frameObj = page.frame('#iframeResult');

// trying to click the button inside the frame.
await frameObj.click('#something');
```

with the following example the wrapper of _iframe_ is with **_shadow-root (closed)_** playwright detects that the wrapper intercepts the event of click, not the _iframe_ button.

Test error:
```
_retrying click action, attempt #1
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div id="iframewrapper"></div> intercepts pointer events_
```


I am not sure why actually with **_shadow-root ( closed )_** the wrapper intercepts the events when playwright trying to click.
With **_shadow-root (open)_** - the click is being executed **successfully**.

Not sure if this is intended as final goal for the two fixes that was implemented in playwright, to track the main-frame/port - who and how intercepts the events.

As my initial request, depending on the implementation of the site - not everyone can do shadow-root / DOM manipulations to enable/disable such features or go in technical-dept how it should work.
But with the fixes done in playwright to detect such behavior of - how and where should click and who must intercepts the events, leads to failing tests.

This is the case i was trying to identify past weeks - doing a bump from **1.22** to **1.24, 1.25.**


To reduce the tech-dept or future issues here in the repo or give the ability for anyone facing similar issue, with testing their website, i would suggest the check for hit-target and intercept events - probably using shadow-root / iframe or something not very common, to be behind a feature toggle - enable/disable such validation.

I managed to identify the code changes in introducing this "issue" in:
[BUG] Misclick when some element overlays the target's iframe
https://github.com/microsoft/playwright/issues/14752
Playwright missclicks on iframe instead on actual element
https://github.com/microsoft/playwright/issues/13762

and probably the toggle should be placed somewhere here: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/dom.ts#L439

The "workaround" option "force" on click - is not relevant because it disables all validations and it will make tester life even harder.

Please let me know if something is not clear or you need more details.

Thanks!

**Comment by dgozman** [comment]
@htsvetkov Thank you for the explanation. This is most likely related to the closed-mode shadow root. I'll try to reproduce and see what we can do. Thanks for suggestions!
