### ISSUE TITLE
[BUG] Config 'video' property set to 'off' does not prevent recording

### ISSUE THREAD

**Issue by zbranzov** [microsoft/playwright#16831]
**Context:**
- Playwright Version: "name": "@playwright/test",
  "version": "1.25.1"
- Operating System: Mac
- Node.js version: lts 16
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const defaultConfig: PlaywrightTestConfig = {
  timeout: 60_000,
  expect: {
    timeout: 60_000
  },
  forbidOnly: false,
  retries: 2,
  workers: 2,
  reportSlowTests: null,
  maxFailures: 4,
  reporter: [['list'], ['html', { open: 'never' }], ['junit', { outputFile: 'junit-results/junit.xml' }]],
  globalSetup: './globalSetup.ts',
  testDir: './tests',
  use: {
    baseURL: BASE_URL,
    headless: true,
    video: 'off',
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
    contextOptions: {
      baseURL: BASE_URL,
      recordVideo: {
        dir: 'videos',
        size: { 
          width: 1280,
          height: 720
        }
      }
    }
  },
  projects: [
    {
      name: 'Chromium',
      use: {
        channel: 'chromium',
        viewport: {
          width: 1920,
          height: 1080
        }
      }
    }
  ]
};
```

**Describe the bug**

Having **video**: 'off' in the config does not prevent recording when we have specified `recordVideo: {
        dir: 'videos',
        size: { 
          width: 1280,
          height: 720
        }
      }`
In order to stop video recording we have to comment the **recordVideo** property

**Comment by yury-s** [comment]
Yes, this is working as intended. `video` is the test runner option and it's eventually translated into `recordVideo` context option. If you explicitly specify `recordVideo` option it overrides the test runner settings. If you want video not to be recorded you should turn it off both places.

**Comment by zbranzov** [comment]
@yury-s I'm sorry for bothering you, but if I have
```
use: {
    baseURL: BASE_URL,
    headless: true,
    video: 'on-first-retry',
    screenshot: 'only-on-failure',
    trace: 'on-first-retry',
    contextOptions: {
      baseURL: BASE_URL,
      // recordVideo: {
      //   dir: 'videos',
      //   size: { 
      //     width: 1280,
      //     height: 720
      //   }
      // }
    }
  }
```

no video is recorded on retry, but I have trace recorded. I don't get it how should I configure it so it takes videos on retry only.
Thank you

**Comment by mxschmitt** [comment]
Could you show us how your tests look like? Just to verify that you don't create browsers, or contexts yourself. If you do, this might impact this feature.

**Comment by zbranzov** [comment]
Hi @mxschmitt ,
I'm sorry if my question seems stupid, but I'm new to PW. 
``` 
test.describe.only('Suite', () => {
  let page: Page;
  let calendarPage: CalendarPage;
  let organizationsService: OrganizationsService;
  let storageStatesService: StorageStatesService;

  test.beforeAll(async ({ browser }) => {
    const httpContext = await request.newContext({ baseURL: process.env.URL });
    organizationsService = new OrganizationsService(httpContext);
    storageStatesService = new StorageStatesService(httpContext);
    process.env.RND_SLUG = await organizationsService.cloneOrganization(CALENDAR_CLONED_ORG, EMPTY_SOURCE_ORG);
    const storageStateFile = await storageStatesService.savePortalStorageState(
      process.env.RND_SLUG,
      OWNER_CALENDAR_EMAIL,
      DEFAULT_PASSWORD
    );
    page = await browser.newPage({ storageState: storageStateFile });
    calendarPage = new CalendarPage(page);
  });

  test.afterAll(async () => {
    await organizationsService.deleteOrganization(process.env.RND_SLUG);
    await page.close();
  });

  test.only('should fail', async () => {
    await calendarPage.goto();
    await calendarPage.clickWeekViewAndWait();
    expect(true).toBe(false);
   
  });
});
```
I do create a new context, but to split the api services' cookies  from the browser.

> If you want API requests to not interfere with the browser cookies you should create a new [APIRequestContext] by calling [apiRequest.newContext([options])](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html). Such APIRequestContext object will have its own isolated cookie storage.
