### ISSUE TITLE
[Question] How to make "toBeHidden" work

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#16833]
I am trying to assert that there is an element on a page but is hidden. If I use "toBeHidden" It will trigger as "true" as the page is loading, since the element is still coming into existence. I can even put some non-existent element in the code and it will pass because the element doesn't exist, ergo it is hidden. Is there a way to assert that an element exists and is hidden (meaning the assert will only pass if both are true)?

**Comment by sgreener** [comment]
cant you use [locator.isHidden()](https://playwright.dev/docs/api/class-locator#locator-is-hidden)?

**Comment by eatonjl** [comment]
Thanks for the suggestion! I believe that acts the same. I tried it out by using `await expect(page.locator("id=bob").isHidden).toBeTruthy();` (bob being a bogus ID) and it passes, considering it hidden. The outcome I am looking for would be for it to fail because it does not exist, fail because it exists and is visible, or pass because it exists AND is hidden.

**Comment by idmadj** [comment]
If an element doesn't exist, `locator.isHidden()` will return true, and `expect(locator).toBeHidden()` will pass.

You need to check for the existence of the element separately using something like `expect(locator).not.toHaveCount(0)` or `if (page.$$(selector)) {...}`.

If that's something you need to assert often, it might be useful to extend expect: https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend

**Comment by eatonjl** [comment]
Thanks! Those are some good suggestions. I will go ahead and close this as answered. Thank you!
