### ISSUE TITLE
[Question] Stdout object for playwright-allure (JS)

### ISSUE THREAD

**Issue by IhorTiurdo** [microsoft/playwright#16840]
Hi guys! Where exactly I can see the stdout output during test execution? I tried find it in process.stdout but unsuccessfully. For example: I want to reduce the count of stdout lines in allure reporter to one line:
![Screenshot 2022-08-25 at 19 31 45](https://user-images.githubusercontent.com/79837050/186721002-c30d94bf-d891-47be-99fe-76a1e402c640.png)
How I can do it?

**Comment by yury-s** [comment]
> Where exactly I can see the stdout output during test execution? 

It's printed out to the terminal where the test runner starts. It is also passed to each reporter's [onStdOut](https://playwright.dev/docs/api/class-reporter#reporter-on-std-out) and as the final [TestResult](https://playwright.dev/docs/api/class-testresult#test-result-stdout) object.

> I want to reduce the count of stdout lines in allure reporter to one line:

This is implemented in the allure reporter, see [this code](https://github.com/allure-framework/allure-js/blob/40400005bb1f331c39c6896ea08f6d5bf6e780f6/packages/allure-playwright/src/index.ts#L191-L197) If you want to merge those lines together you should change that implementation.
