### ISSUE TITLE
attemping to create a zip w/playwright:v1.25.0-focal

### ISSUE THREAD

**Issue by ceckles** [microsoft/playwright#16848]
first off I am fairly new to all this so bare with me, I'm using a Jenkins file with then mcr.microsoft.com/playwright:v1.25.0-focal the test all run no issues; the problem I'm having is once the test are done. I would like to zip up the screenshot folder and add them to the Jenkins Build Artifacts however when when I try and add sh 'zip -r screenshots.zip test/screenshot' zip command not found when I attempt to install zip it fail. anyone have a solution to this or better way ?

```
pipeline {
  agent {
    docker {
      image 'mcr.microsoft.com/playwright:v1.25.0-focal'
    }
  }
    stage('Run Playwright Tests') {
      steps {
        // Run Test
        sh 'npm run playwright'
        // Zip folder for archive artifacts
        //sh 'zip -r screenshots.zip e2e/screenshot'
      }
      post {
        always {
          // archiveArtifacts artifacts: 'screenshots.zip', fingerprint: true
          archiveArtifacts artifacts: 'playwright-report/index.html', fingerprint: true
        }
      }
    }
  }
}
```

**Comment by yury-s** [comment]
Our docker container doesn't preinstall `zip`, you can either install it manually by running `apt update && apt install zip` or create `.tar.gz` archive instead:
```sh
tar -czvf screenshots.tar.gz e2e/screenshot
```
