### ISSUE TITLE
[BUG] Text selector is failing at capturing a string with special characters

### ISSUE THREAD

**Issue by skysantoroa** [microsoft/playwright#16858]
**Context:**
- Playwright Version: 1.25
- Operating System: Linux
- Node.js version: 16
- Browser: All
- Extra: none

**Code Snippet**

Locator:

```typescript
await expect(
          page.locator(
            // eslint-disable-next-line no-useless-escape
            `div.field-error >> text='should match pattern "\\\\^-\\\\?\\\\\\d\\\\+\\\\$"'`,
          ),
        ).toBeVisible()
```

DOM subtree:

```html
<div class="form-group field field-string field-error has-error has-danger"><label for="root_COD" class="control-label">COD*</label><div class="text-input css-u40vo9"><input class="-error css-ye17rv" type="string" value="asdasd" style="width: calc(100% - 37px);"><span class="css-uj5gfg"></span><div class="css-6o2q91"><button type="button" tabindex="-1" class="css-m259gr"><svg aria-hidden="true" role="img" class="octicon octicon-x" viewBox="0 0 16 16" width="16" height="16" fill="currentColor" style="display: inline-block; user-select: none; vertical-align: text-bottom; overflow: visible;"><path fill-rule="evenodd" d="M3.72 3.72a.75.75 0 011.06 0L8 6.94l3.22-3.22a.75.75 0 111.06 1.06L9.06 8l3.22 3.22a.75.75 0 11-1.06 1.06L8 9.06l-3.22 3.22a.75.75 0 01-1.06-1.06L6.94 8 3.72 4.78a.75.75 0 010-1.06z"></path></svg></button></div></div><div><ul class="error-detail bs-callout bs-callout-info"><li class="text-danger">should match pattern "^-?\d+$"</li></ul></div></div>
```

**Describe the bug**

The above assertion should not fail as the selector correctly matches the element in the subtree but the test will fail with error. Also notice the amount of backslash.

```
Error: expect(received).toBeVisible()
Call log:
  - expect.toBeVisible with timeout 30000ms
  - waiting for selector "div.field-error >> text='should match pattern "\^-\?\\d\+\$"'"
```

![image](https://user-images.githubusercontent.com/101178279/186926969-03154f74-3e9f-4dec-b38a-1cf6d3af55cb.png)

**Comment by yury-s** [comment]
Looks like our selector parser is confused by the pair of " " inside the text. We should fix that. The following works (without last quote)

```js
await expect(page.locator(`div.field-error >> text=should match pattern "^-?\\d+$`)).toBeVisible();
```

You can also specify a regex as a workaround.

**Comment by yury-s** [comment]
It turns out that different escaping actually works:

```js
  await expect(page.locator(`div.field-error >> text='should match pattern "^-?\\\\d+$"''`)).toBeVisible();
```
you basically need to `\` escape the `\` which becomes `\\\\` when combined with js source code escaping and it is different from non-exact match where this escaping is not handled.

**Comment by yury-s** [comment]
> ![image](https://user-images.githubusercontent.com/101178279/186926969-03154f74-3e9f-4dec-b38a-1cf6d3af55cb.png)

The tooltip contains correctly escaped string, how did you end up with `\\\\\\d` ?
