### ISSUE TITLE
Playwright context is taking more than 2 minutes to close with video resolution 2920X1080 resolution

### ISSUE THREAD

**Issue by sswapnika** [microsoft/playwright#16856]
Hi Team,

I am using video recording resolution as width: 2920,height: 1080. with this resolution, context close is taking more than two minutes which is increasing my test execution time. with lesser resolution like 800X800, the video is not clear when we add it in pipeline jobs. Do we have a solution for this?

**Comment by yury-s** [comment]
Can you provide more details about your environment, what playwright version is this, which browser, which OS? Also how long does the test run without video or maybe you can share the code? Since the video dimensions are large it may take longer to encode.

**Comment by pavelfeldman** [comment]
This is expected, full hd video is going to be expensive to create. You should use 800x800 at most for testing, and preferably switch from video to traces for post-mortem. They are fast and crisp.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
