### ISSUE TITLE
[Question]How to run electron on CI github actions in headed mode

### ISSUE THREAD

**Issue by ptc-aramachandra** [microsoft/playwright#16851]
Github runner is a windows machine and is running as a service. When we run electron application tests on this machine, we dont see a UI opening at all and hence cannot know what is happening with the electron UI elements. Is there a way we can debug electron applications on CI ?

**Comment by yury-s** [comment]
Did you try [tracing](https://playwright.dev/docs/trace-viewer-intro)  and/or [video](https://playwright.dev/docs/test-configuration#record-video) recording?

**Comment by ptc-aramachandra** [comment]
Yes I did record a video. It is supposed to click a button and I'm also using a expect to wait for the button to appear and then click it. Code is able to see the UI element and hit that button and continue but on the UI it doesn't seem to be doing that button click and hence the code fails at the next step waiting for some other UI element to appear.
Why is this mismatch happening ?

Electron is running headless on a windows service invoked by github actions. Is it something to do with the screen size if its running headless ?

**Comment by pavelfeldman** [comment]
I'm not sure why you can't see it in the UI. Electron in fact does not have a headless mode of operation, it should be always visible. So I'd go back to the original request and figure out why you are not observing the UI at the first place.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
