### ISSUE TITLE
How to find locators and test dynamic columns for ag grid

### ISSUE THREAD

**Issue by Narayan3682** [microsoft/playwright#16855]
We have a AG-grid in which I need to validate columns and filters but, most of the columns and rows are dynamically loaded into DOM. Indefinite scroll is needed to load in UI which is not a efficient solution for automation. Is there any way I can validate this or load columns through script?

**Comment by yury-s** [comment]
You can always scroll the grid until it reaches the end / desired state by evaluating [window.scrollBy](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollBy) in the page, this is the closest to what a human would do. There might be a js method in AG-grid that allows jumping to a particular line, you should look for the information/ask experts at their forums.

Disabling the DOM virtualization for row and column https://www.ag-grid.com/angular-data-grid/dom-virtualisation/ is another option. This will disable lazy loading but will affect the app performance.

This was [discussed](https://playwright.slack.com/archives/CSUHZPVLM/p1647004745222649) some time ago on our slack channel.
