### ISSUE TITLE
How to put implicit wait in post operation 

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#16867]
Hi Team,

is there any way to put implicit wait ??

note :- Its during API testing ….

Iam doing post operation but I want it to be done after every 2 sec , as in test env we dnt have much server so on more load its giving ‘too many request in single time frame ‘ 

i tried to find but seems all waits are on page only

**Comment by pavelfeldman** [comment]
`await new Promise(f => setTimeout(f, 2000));`

**Comment by mechandan** [comment]
Thankyou, i was thinking there wud be some inbuild method, anyways thanks 😊
