### ISSUE TITLE
[Feature] request.postData to return json string instead of urlsearchparams

### ISSUE THREAD

**Issue by aesyondu** [microsoft/playwright#1686]
I noticed that when using route to assert postData:
```javascript
page.route("some-route", (route, request) => {
  expect(request.postData()).toMatchObject({ foo: "bar" })
})
```
that it returns a string of search params `foo=bar&baz=bum`.

Does it make sense to make it return a json string instead?

Reference commit: https://github.com/aesyondu/playwright/commit/1b3929dd2b2c1684b38a34448a70fb1d77e8b119, with test case and sample naive implementation

Given:
A form with input type text, input type number, and input type submit
```javascript
await page.setContent(`<form method='POST' action='/post'><input type='text' name='foo' value='bar'><input type='number' name='baz' value='123'><input type='submit'></form>`);
await page.click('input[type=submit]');
expect(request).toBeTruthy();
expect(request.postData()).toBe('{"foo":"bar","baz":"123"}');
```

When:
Form data is submitted via POST method.

Then:
`request.postData()` should return a json string: `{"foo":"bar","baz":"3"}`

**Comment by pavelfeldman** [comment]
According to the spec:

*As part of a POST request, an arbitrary amount of data of any type can be sent to the server in the body of the request message. A header field in the POST request usually indicates the message body's Internet media type.*

We could add `postDataJSON` though.

**Comment by mxschmitt** [comment]
@pavelfeldman can be closed, since already implemented.
