### ISSUE TITLE
[Question] How to return error from launchServer?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#16877]
Suppose I start server using `launchServer` and I intercept the web socket connection. How would I send a human readable error message to Playwright?, i.e. something that would break Playwright in a way that surfaces the error that was sent.

**Comment by pavelfeldman** [comment]
I don't think this is currently possible.

**Comment by pavelfeldman** [comment]
Happy you found the workaround. Your original requests seems to be outside of the scope for Playwright, so I'll close it.
