### ISSUE TITLE
[BUG] Unexpected browser.close() behaviour when connecting to a remote server

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#16884]
**Context:**
- Playwright Version: 1.25.1
- Operating System: Mac
- Node.js version: 18.7
- Browser: Chromium
- Extra: -

I would expect these two snippet to produce comparable events:

```ts
const clientWebSocket = new WebSocket('ws://127.0.0.1');

clientWebSocket.on('open', () => {
  clientWebSocket.close();
});
```

```ts
const browser = await chromium.connect('ws://127.0.0.1');

await browser.close();
```

However, looking at the events on the receiving end, Playwright version does not issue `close` event.

**Comment by pavelfeldman** [comment]
> Playwright version does not issue close event.

On which object?

**Comment by punkpeye** [comment]
v1.25.1

**Comment by punkpeye** [comment]
> On which object?

Misread what you asked – what do you mean on which object?

WebSocket server here is just an instance of https://www.npmjs.com/package/ws

I would expect `await browser.close()` to send a close event, it does not.

**Comment by pavelfeldman** [comment]
There is no `close` event in Playwright. And `browser.close()` does not close the browser if it was obtained from the server, it disconnects from it. It dispatches https://playwright.dev/docs/api/class-browser#browser-event-disconnected.

**Comment by punkpeye** [comment]
What is the actual WebSocket event? because as far as I can tell, the server just stays hanging without being aware that client disconnected.

**Comment by punkpeye** [comment]
Unless I am looking at the wrong part of the code, this part is never invoked, and I would expect it to be invoked in this scenario.

https://github.com/microsoft/playwright/blob/11dfd31dd9c44ebe888e0929a1800c70507b227b/packages/playwright-core/src/remote/playwrightConnection.ts#L199-L207

**Comment by pavelfeldman** [comment]
I'm not sure what scenario you are exploring, could you suggest the steps to reproduce the problem? It might well be you are looking at the wrong place of code altogether...

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
