### ISSUE TITLE
[Question] Evaluate: Attach File to FormData

### ISSUE THREAD

**Issue by lefado** [microsoft/playwright#16881]
I am trying to call a Javascript function from Playwright. This function basically send a API request to the Backend. 

Function code in the front end is:
```
const formData = new FormData();
formData.append('document_type', DOCUMENT_TYPE[DOCUMENT_TYPE_ID.REFUND_DOCUMENT]);
this.filesToUpload.forEach((fileToUpload) => {
  formData.append('files', fileToUpload);
});
await this.$uploadDocuments(this.caseData.id, formData);
```

Then, I am trying to replicate same logic on Playwright by doing:
```
  let buffer = fs.readFileSync("src/fixtures/test_pdf.pdf");
  let blob = new Blob([buffer]);

  await this.page.evaluate(
    ([caseId, file]) => {
      const form = new FormData();
      form.append('document_type', 'type_1');
      form.append('files', file);
      // @ts-ignore
      window.$nuxt.$uploadDocuments(caseId, form);
    },
    [caseId, blob]
  )
```

Frontend function is being called successfully from Playwright. However, triggered request is coming back with an error 

```
{
    "message": {
        "files": "Missing required parameter in an uploaded file"
    }
}
```

When Form Data is created from Front end by `formData.append('files', fileToUpload);`, the variable `fileToUpload` is  a `File()` object. 
However, I  have not been able to create a `File()` object from Playwirght/NodeJs. I believe problem is coming from there

**Comment by pavelfeldman** [comment]
> let blob = new Blob([buffer]);

What is `Blob` here, there is no such type in Node.js?

I don't think we support passing the blobs in evaluate. You should serialize your Buffer as a `base64`, pass it and parse it back in your evaluate body when constructing the File.

**Comment by gauravgandhi1315** [comment]
@lefado To attach file in playwright, I am using this:

```
//attach files(browse)
await page.setInputFiles(locator, fileName);
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
