### ISSUE TITLE
[BUG] toHaveURL and toHaveTitle sometimes timeout when the page has a URL and title

### ISSUE THREAD

**Issue by CtrlZvi** [microsoft/playwright#16883]
**Context:**
- Playwright Version: 1.25.1 (
- Operating System: Linux
- Node.js version: 18.8
- Browser: Firefox
- Extra: Also mcr.microsoft.com/playwright:v1.25.1

## System:
 - OS: macOS 12.5.1
 - Memory: 743.46 MB / 64.00 GB
## Binaries:
 - Node: 18.8.0 - /usr/local/bin/node
 - npm: 8.18.0 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

## System:
 - OS: Linux 5.10 Ubuntu 20.04.4 LTS (Focal Fossa)
 - Memory: 3.16 GB / 5.65 GB
 - Container: Yes
## Binaries:
 - Node: 16.17.0 - /usr/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.15.0 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash

**Code Snippet**

I unfortunately don't have a reproducing code snippet.

**Describe the bug**

Sometimes, and not all the rarely, [`expect(page).toHaveTitle(titleOrRegExp[, options])`](https://playwright.dev/docs/test-assertions#page-assertions-to-have-title) and/or [`expect(page).toHaveURL(urlOrRegExp[, options])`](https://playwright.dev/docs/test-assertions#page-assertions-to-have-url) will timeout despite the page being fully loaded, having a title, and having a URL.

I have not been able to determine any sort of cause in order to create a reliable repro case, but I did manage to capture a HAR and trace. If I'm reading the trace correctly, it timed out on `expect(page).toHaveURL(urlOrRegExp[, options])` while waiting for the root node of the DOM. While this is frequently what occurs, sometimes the root node is found, and the timeout is waiting for something else.

In the [trace](https://github.com/microsoft/playwright/files/9440143/trace.zip), the snapshot shows that the page has loaded far enough to render and displays a URL for the page. The [HAR](https://github.com/microsoft/playwright/files/9440140/har.zip) shows that the page was download in about 1s after being queued, and about 2s after the last page load had completed. Far less than the 10s timeout.

**Comment by CtrlZvi** [comment]
Additional [HAR](https://github.com/microsoft/playwright/files/9440157/har.1.zip) and [trace](https://github.com/microsoft/playwright/files/9440156/trace.1.zip) showing the same issue for toHaveTitle.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by CtrlZvi** [comment]
I have been trying for weeks to find an exact repro case and I have not been able to find a consistent reproduction case. The best I've come up with is slower servers seem to exacerbate it, but I've also seen it with fast servers.

**Comment by pavelfeldman** [comment]
We probably need to surface more in the trace in order to identify the issue. For some reason, we can't query the document successfully. I don't think providing additional information w/o the repro steps will help.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, we are unlikely to make progress on it. Allow me to close it, but please file a new one and link to this issue if you manage to reproduce with something you can share.
