### ISSUE TITLE
[Question] Is Playwright server somehow aware of test outcomes?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#16880]
I am trying to figure out how do I record a test outcome in Playwright server.

There appears to be nothing in the websocket stream that would signal when expectations fail.

**Comment by pavelfeldman** [comment]
No, those are implemented in different layers.

**Comment by punkpeye** [comment]
I guess my point is that it should be.

If you look at how these are implemented by companies that host Playwright test runners, they rely on hacks at the moment to capture the outcomes, e.g. https://www.browserstack.com/docs/automate/playwright/run-tests-in-parallel

```ts
try {
    expect(title).to.equal("BrowserStack - Google Search", 'Expected page title is incorrect!');
    // following line of code is responsible for marking the status of the test on BrowserStack as 'passed'. You can use this code in your after hook after each test
    await page.evaluate(_ => {}, `browserstack_executor: ${JSON.stringify({action: 'setSessionStatus',arguments: {status: 'passed',reason: 'Title matched'}})}`);
  } catch {
    await page.evaluate(_ => {}, `browserstack_executor: ${JSON.stringify({action: 'setSessionStatus',arguments: {status: 'failed',reason: 'Title did not match'}})}`);
  }
```

It would be ideal if Playwright sent a message to the server with equivalent information.
