### ISSUE TITLE
browsers are not getting installed in jenkins - working fine earlier - (Failed to install browsers)

### ISSUE THREAD

**Issue by gunabca** [microsoft/playwright#16893]
While trying to execute the pipeline, i am getting the below error 
```

Downloading Chromium 105.0.5195.19 (playwright build v1019)...
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
Downloading Chromium 105.0.5195.19 (playwright build v1019)...
Failed to install browsers
Error: Failed to download Chromium 105.0.5195.19 (playwright build v1019), caused by
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by gunabca** [comment]
Our CI is broken as a Result of this

**Comment by pavelfeldman** [comment]
It looks like your host system on Jenkins does not trust Azure CDN's TLS certificate.

**Comment by gauravgandhi1315** [comment]
@gunabca I had the same issue and ended up using docker image to fix this issue.

**Comment by gunabca** [comment]
> @gunabca I had the same issue and ended up using docker image to fix this issue.

Thanks for the Idea, I will try it.

**Comment by gunabca** [comment]
> It looks like your host system on Jenkins does not trust Azure CDN's TLS certificate.

I will check with my team here , thanks for the quick update

**Comment by pavelfeldman** [comment]
Let me fold it into https://github.com/microsoft/playwright/issues/16926
