### ISSUE TITLE
[Question] how to run same test on multiple browser one after another

### ISSUE THREAD

**Issue by vishwajeetgodge13** [microsoft/playwright#16890]
hi team,
I'm using playwright with js. and i want to run same test on multiple browser. how can i do it?
ex.
   once it successfully run on chrome then it should run on firefox..webkit..edge like this way

**Comment by vishwajeetgodge13** [comment]
Now it running on all browser at same time that i don't want. when it successfully run then, same test run on another browser

**Comment by pavelfeldman** [comment]
You can either pass `--workers=1` to make all tests run serially or you can pass `--project=chromium` to run them for specific browser.

**Comment by vishwajeetgodge13** [comment]
Hi @pavelfeldman 
i already did this changes as you said, but as per the  requirements. i wanted to run all tests on all browser. i mean to say, once all tests successfully ran on chromium. then it should start executing on second browser(firefox) then third browser (webkit) like this way & I don't want to execute all tests at the same time on all browser. In one go,  No need to change --project=chromium once it executed then --project=firefox  so on so forth
