### ISSUE TITLE
[Feature] allow exposeBinding to pass locators

### ISSUE THREAD

**Issue by damianr13** [microsoft/playwright#16895]
A previous PR introduces the ability to retrieve an `ElementHandle` from an exposed binding: https://github.com/microsoft/playwright/pull/4030

Since then the `ElementHandle` API has been discouraged and replaced by the more recent `Locator` objects. 

I would like to have another option for the `exposeBinding` method that would allow me to specify that I prefer getting a `Locator` inside the callback instead of an `ElementHandle`.

**Comment by pavelfeldman** [comment]
Locator and ElementHandle are conceptually different. First is a 'way of locating element', second is 'exact dom node handle'. Migrating from ElementHandle to Locator does not provide and of the Locator benefits, so it does not seem necessary. ElementHandlers make sense when you are evaluating and exposing bindings, they are discouraged for primary automation operations, but they exist for the corner cases like yours.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
