### ISSUE TITLE
undefined: Error: Global config has not been defined yet - Playwright component test

### ISSUE THREAD

**Issue by DH250439** [microsoft/playwright#16903]
I'm attempting to implement Playwrights component test on a grid. Here's the component test:

import { test, expect } from "@playwright/experimental-ct-react";

```
test.describe("Invoice Table Renders Component Tests: ", () => {

    test("component renders", async ({ mount }) => {
        const component = await mount(
        <InvoicesTable invoices={ mockComponentInvoices }/>);

        await expect(component).toContainText('email');
    });
});
```

Here's the error:

undefined: Error: Global config has not been defined yet. at GlobalConfig.get (http://localhost:3100/assets/index.b07305db.js:105442:13)

This is a React app.

I have one Component test running, but the new one I created is displaying that error message on execution.

Any help would be appreciated.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by DH250439** [comment]
What additional info can I provide?

I'm attempting to test a component that takes an array as a prop.  That's the only difference between this element and the others that are working.

**Comment by pavelfeldman** [comment]
We pretty much need a repo we can clone to reproduce.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
