### ISSUE TITLE
[Feature] Allow customizing the html reporter annotations

### ISSUE THREAD

**Issue by Meir017** [microsoft/playwright#16901]
When rending blocks of text into the annotations of the test they are rendered without the new lines.

Example from - https://github.com/Meir017/test262-web-runner
![image](https://user-images.githubusercontent.com/9786571/187287871-c3486807-7ea2-417b-8ce3-43aa6ed75853.png)

adding `white-space: pre-wrap;` to the css rule `.test-case-annotation` solves this.

![image](https://user-images.githubusercontent.com/9786571/187288034-d023cb75-2342-45fc-97a9-010de78ae8fb.png)

**Comment by pavelfeldman** [comment]
I don't think we expect rich format in those annotations, they don't even have a mime type.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
