### ISSUE TITLE
[BUG] ENOENT error for timed out tests with page and request when tracing on failure in Firefox with the html reporter

### ISSUE THREAD

**Issue by CtrlZvi** [microsoft/playwright#16910]
**Context:**
- Playwright Version: 1.25.1
- Operating System: Mac
- Node.js version: 18.8
- Browser: Firefox

**System:**
 - OS: macOS 12.5.1
 - Memory: 1.79 GB / 64.00 GB

**Binaries:**
 - Node: 18.8.0 - /usr/local/bin/node
 - npm: 8.18.0 - /usr/local/bin/npm

**Languages:**
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```typescript
import { test, expect } from '@playwright/test';

test.describe("reproduces the ENOENT error", async () => {
    test("poll API requests until they time out", async ({ page, request }, testInfo) => {
        await page.goto("https://github.com/microsoft/playwright");
        await expect.poll(
            async () => {
                const searchResults = await request.get(
                    'https://api.github.com/repos/microsoft/playwright/issues',
                );
                return ((await searchResults.json()).length);
            },
            {
                intervals: [1000],
                timeout: testInfo.timeout,
            }
        ).toEqual(0);
    })

})
```

**Describe the bug**

The reporter outputs an ENOENT error to the terminal that looks like `Error: ENOENT: no such file or directory, open '/var/folders/h0/j6c1j6ms36n8g62fsvpt5djm0000gn/T/playwright-tracing-zoHPvZ/f1002bb38a0e7417e5eeb8d6e0c78da5.network'`. It's unclear if there's any impact to the actual HTML report or if the error is spurious.

The provided snippet can be saved to a file and run with `npx playwright test --trace retain-on-failure --browser firefox --reporter html` to reproduce. Repro case may not be 100%, but is fairly high. On my system I have about an 80% reproduction rate. `--timeout` can be used to make the iteration time faster. I've successfully gone as low as a 5 second timeout while keeping a decently high reproduction rate.

**Comment by yury-s** [comment]
What command gives you this error? Can you also shared your config, I ran the following and was not able to reproduce it:
```sh
 npm init playwright foo
 cd foo/
 # edit playwright.config.ts to remove all projects
 cat > tests/example.spec.ts # pasted the code snippet you had
 px playwright test --trace on--browser firefox --reporter html --timeout=5000
```

**Comment by zeffron** [comment]
No config. `npx playwright test --trace retain-on-failure --browser firefox --reporter html`.

**Comment by CtrlZvi** [comment]
No config. `npx playwright test --trace retain-on-failure --browser firefox --reporter html`.

**Comment by CtrlZvi** [comment]
Following your steps except for substituting your playwright test line with mine from [my previous comment](https://github.com/microsoft/playwright/issues/16910#issuecomment-1232429077), it took me 3 tries to reproduce the issue. That was using the default 30 second test timeout, though, instead of trying to shorten it.

**Comment by CtrlZvi** [comment]
Super impressed by the turnaround time on fixing this! Thank you!
