### ISSUE TITLE
[BUG] Playwright expect timeout doesn’t work properly if you define a timeout on the playwright configuration file

### ISSUE THREAD

**Issue by alontrabolski** [microsoft/playwright#16919]
**Context:**
- Playwright Version: 1.24.1
- Operating System: MAC
- Node.js version: 14.20.0
- Browser: Chromium

Seems that Playwright expect timeout doesn’t work properly if you define a timeout on the playwright configuration file.
I defined timeout 30 * 1000 for expect in playwright.config.ts file:

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  testDir: './tests',
  timeout: 30 * 1000,
  expect: {
    timeout: 30 * 1000,
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? [['dot'], ['html', { open: 'never' }]] : 'list',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    baseURL: process.env.BASEURL,
    storageState: `${os.tmpdir()}/auth.json`,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1920, height: 1080 },
      },
    },
  ],
};

export default config;

On my test I run this code and it's failed:
await expect(this.page.locator('data-test-id=side-bar')).toBeVisible();

Getting this error:
Error: expect(received).toBeVisible() Call log:
expect.toBeVisible with timeout 5000ms
waiting for selector "data-test-id=side-bar"

But when running this code it works and the test passed:
 await expect(this.page.locator('data-test-id=side-bar')).toBeVisible({
      timeout: 30000,
    });

**Comment by pavelfeldman** [comment]
You have a race condition it seems, you can't have expect timeout and test timeout to be both 30 seconds. You can either make expect timeout 0 (no timeout) or make it smaller than the test timeout.

**Comment by alontrabolski** [comment]
Thanks. I tried what you said but it still don't works.
In playwright.config.ts file I changed the test timeout to be: 300*1000 and kept the value of expect timeout as is (30 * 1000).

Same results as before:

Test failed when running this:
await expect(this.page.locator('data-test-id=side-bar')).toBeVisible();
Getting this error:
Error: expect(received).toBeVisible() Call log:
expect.toBeVisible with timeout 5000ms
waiting for selector "data-test-id=side-bar"

Test passed when running this:
await expect(this.page.locator('data-test-id=side-bar')).toBeVisible({
timeout: 30000,
});

**Comment by pavelfeldman** [comment]
This strongly suggests that your config is not used when you are running playwright. Where is your config located and how do you run tests?

**Comment by alontrabolski** [comment]
I checked and config is used when running the tests.
I changed the viewport to be:  viewport: { width: 50, height: 50 } and when running the test the window opened accordingly.
I also changed the baseURL in the config and the browser opened with the new url.

We are working with Monorepo and playwright.config.ts file located in folder called e2e and the tests files located in folder called tests (which also located under e2e) 
We defined testDir: './tests' in the config as you can see in the bug description.

**Comment by pavelfeldman** [comment]
How do you specify the path to your config file when you run playwright?

**Comment by alontrabolski** [comment]
I think that I figured out what happens here.
The expect timeout that I defined in the config is works when I run expect from my tests files.
The code snippet that I attached to the bug description is triggered from the global setup function.

It's fine for me now.
Thanks a lot Pavel, your questions leaded me to the solution.
