### ISSUE TITLE
[Feature] Installation on ChromeOS

### ISSUE THREAD

**Issue by vogler** [microsoft/playwright#16911]
I tried to setup and run Playwright (1.20.1) on my Chromebook, but the process was a bit bumpy:

```bash
$ npx playwright install chromium
$ node epic.js
║ Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-deps
$ sudo npx playwright install-deps
Installing Ubuntu dependencies...
Switching to root user to install dependencies..
...
Note, selecting 'libfontconfig1' instead of 'libfontconfig'
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libjpeg-turbo8 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-ubuntu-font-family' has no installation candidate
E: Unable to locate package libenchant1c2a
E: Unable to locate package libicu66
E: Package 'libjpeg-turbo8' has no installation candidate
Failed to install browser dependencies
Error: Installation process exited with code: 100
$ sudo npx playwright install-deps chromium --dry-run
sudo -- sh -c "apt-get update&& apt-get install -y --no-install-recommends fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libdbus-1-3 libdrm2 libegl1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxshmfence1 xvfb fonts-noto-color-emoji ttf-unifont libfontconfig libfreetype6 xfonts-cyrillic xfonts-scalable fonts-ipafont-gothic fonts-wqy-zenhei fonts-tlwg-loma-otf ttf-ubuntu-font-family"
```
I then manually installed all those packages except `ttf-ubuntu-font-family` and everything works now.
I don't know why it detected the OS as Ubuntu. Here it also lists dependencies for `debian11`: https://github.com/microsoft/playwright/blob/35bcecc5c3bcfc0dba12273d365122c0845b5c99/packages/playwright-core/src/server/registry/nativeDeps.ts#L653

Linux container in ChromeOS:
```bash
$ lsb_release -a
...
Description:    Debian GNU/Linux 11 (bullseye)
$ uname -a                                     
Linux penguin 5.10.120-16471-g167ad2e5dcba #1 SMP PREEMPT Sun Aug 14 18:22:09 PDT 2022 x86_64 GNU/Linux
$ uname -m                                                                                           
x86_64
```

**Comment by pavelfeldman** [comment]
Playwright is not supported on ChromeOS. If you think there are others that can benefit from running Playwright on ChromeIOS, please feel free to contribute a docs section that would help them follow your steps and get it working!

**Comment by vogler** [comment]
It's not really ChromeOS but a Debian container. Here's some background: https://chromeos.dev/en/linux
I assume if the OS was correctly identified as `debian11` instead of Ubuntu, there wouldn't be any issues with installing the dependencies.

**Comment by vogler** [comment]
https://github.com/microsoft/playwright/blob/35bcecc5c3bcfc0dba12273d365122c0845b5c99/packages/playwright-core/src/utils/linuxUtils.ts#L46

correctly returns `{ id: 'debian', version: '11' }` and

https://github.com/microsoft/playwright/blob/35bcecc5c3bcfc0dba12273d365122c0845b5c99/packages/playwright-core/src/utils/hostPlatform.ts#L32

correctly evaluates to `debian11` which is used here:

https://github.com/microsoft/playwright/blob/1cedd805ed08600e87bf8a1a37f8d11ac38c9630/packages/playwright-core/src/server/registry/dependencies.ts#L86-L92

I did not find where the output `Installing Ubuntu dependencies` comes from.

**Comment by vogler** [comment]
Apparently this has been fixed in some recent version (https://github.com/microsoft/playwright/pull/14010?). 👍 

```console
$ ncu -u
 playwright                      ^1.20.1  →  ^1.25.1
```
