### ISSUE TITLE
[Question] "@import" in CSS for loading external fonts causes VRT flakiness, why?

### ISSUE THREAD

**Issue by fredboyle** [microsoft/playwright#16927]
We have an "@import" statement in our CSS to load some fonts from Google's font CDN (see example below). Unfortunately this appears to be causing some flaky tests in our visual regression testing(VRT).

We've found that adding a `await page.waitForTimeout(500);` after the page load prevents the tests from being flaky but it's not ideal as there isn't a way to universally add this delay so it must be manually added to every test.

Is there a better way to prevent flaky tests from fonts not loading fast enough in any environment?

```css
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,500;0,700;1,400;1,700&family=Poppins:wght@600;700&display=swap');
```

**Comment by pavelfeldman** [comment]
You can wait for fonts to load:

```js
await page.evaluate(() => document.fonts.ready);
```

**Comment by fredboyle** [comment]
@pavelfeldman Is there a way to apply this universally to all tests or must it be added to each individual test?

**Comment by pavelfeldman** [comment]
you can always do `test.beforeEach` or introduce a method `mygoto(page, url)` that would perform the goto and await the fonts.
