### ISSUE TITLE
PlayWright Failed to install browsers (Unable to get local issuer certificate)

### ISSUE THREAD

**Issue by aswatsankar** [microsoft/playwright#16923]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows
- Browser: All
- Extra: Java Version Installed - 16.0.2 Apache Maven Version installed - 3.8.1 
Verified with my organisation that the firewall zscaler is not blocking the network and it looks more like a certificate issue. 

**Code Snippet**
package example;
import com.microsoft.playwright.*;
public class Example {
    public static void main(String[] args) {
        try (Playwright playwright = Playwright.create()) {
            Browser browser = playwright.chromium().launch();
            Page page = browser.newPage();
            page.navigate("http://playwright.dev");
            System.out.println(page.title());
        }
    }
}

**Describe the bug**
Unable to get local issuer certificate 
![image](https://user-images.githubusercontent.com/24888082/187446682-9384970e-52c5-4a24-878d-7071e05a159d.png)

**Comment by pavelfeldman** [comment]
> Verified with my organisation that the firewall zscaler is not blocking the network and it looks more like a certificate issue.

It looks like while the address is not blocked, your host system does not trust Azure CDN TLS certificate.

**Comment by pavelfeldman** [comment]
Let me fold it into https://github.com/microsoft/playwright/issues/16926
