### ISSUE TITLE
[Question] What the best way to check that the page (and sub-apicalls) was loaded successful?

### ISSUE THREAD

**Issue by AlexBones1** [microsoft/playwright#16920]
As AQA I want to make regression tests for the list of pages
What the best way/recipes to implement this?
I tryied to use parametrization (in speudocode), but it passed for some pages where api-calls have 500th errors.
```
for (const path of paths) { test(`Smoke test for current path: ${path}`), async ({ request, page }) => {
    const auth = new Auth(request);
    const bpage = new BasePage(page);
    await page.setExtraHTTPHeaders({'authorization': `${await auth.getToken()}`});
    await bpage.navigateTo(path);
});
}
```

**Comment by pavelfeldman** [comment]
You can check the return value of page.goto(). It returns response object that has a status, you can compare it to 500.

**Comment by pavelfeldman** [comment]
Or are you talking about api calls within the page? In that case you can page.on('response') and collect all the responses while navigating. You will then check their statuses.

**Comment by AlexBones1** [comment]
> 

Yes, about the api calls within the page. Thanks, Pavel

**Comment by pavelfeldman** [comment]
Something like this then:

```js
const requests = [];
// start collecting requests
page.on('request', r => requests.push(r));
// load the page
await page.goto(...);
// wait for all responses to arrive
const responses = await Promise.all(requests.map(r => r.response()));
// expect no response has a bad status.
expect(responses.find(r => r.status() > 400)).toBeFalsy();
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
