### ISSUE TITLE
[Question] Best way to screenshot while mouse down?

### ISSUE THREAD

**Issue by fredboyle** [microsoft/playwright#16932]
What is the best way to take a screenshot during a mousedown event?

We'd like to locate an element, mouse to it similar to hover, then mousedown on the element, and while the mouse button is down take a screenshot.

This is specifically to perform a visual regression test on the CSS `:active` state of elements such as buttons.

Thanks for any and all help and guidance.

**Comment by pavelfeldman** [comment]
Did you try issuing `page.mouse.down()` and taking the screenshot?

**Comment by fredboyle** [comment]
@pavelfeldman I have not. I'll give it a try. Thanks.

Would doing a `locator.hover()` then a `page.mouse.down()` perform a mouse down in the center of the located element or would I need to do a `page.mouse.move()` before the `page.mouse.down()`?

**Comment by fredboyle** [comment]
Update, gave the `locator.hover()` then a `page.mouse.down()` and it did do the trick. Hopefully that's "official" and not a happy happenstance.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
