### ISSUE TITLE
[Question] Is it possible to test using a device just in one suite, using @playwright/test?

### ISSUE THREAD

**Issue by mcntsh** [microsoft/playwright#16931]
I know that you can define devices to test with [via the configuration](https://playwright.dev/docs/test-configuration), but don't want to test using multiple devices all the time, just in one single test. Is this possible?

**Comment by pavelfeldman** [comment]
Are you asking about [this](https://playwright.dev/docs/test-configuration#local-configuration)?

**Comment by mcntsh** [comment]
If I try that I get the following error:

```
Error: Cannot use({ browserName }) in a describe group, because it forces a new worker.
Make it top-level in the test file or put in the configuration file.
```

**Comment by mcntsh** [comment]
I guess this just means I have to create new test files for testing different devices. That's fine! If I put it at the top level it works.
