### ISSUE TITLE
[Missing functionality] no option to send GET request with Body

### ISSUE THREAD

**Issue by moshikd** [microsoft/playwright#16930]
I'm trying to send a get request with a body using playwright.
 I did not find any resource / way how to do it.
 I would like to query the elasticsearch using get request with payload. example:

```
test("Get simki", async ({request})=> {
    const response = await request.get('http://test.test.be/es/ad_matrix_agg_*/_search', {
        headers:{
            'Authorization': 'Basic token',
            'Content-Type': 'application/json'
        },
      data:{
}
    }); 
    console.log(await response.json());
    expect(response.status()).toBe(200);
})
```

issue:
There is no option to add data in get request like in post request.

trying to use data in get request did not work and got this:

![get request issue](https://user-images.githubusercontent.com/76883800/187528605-3a2ca174-f9c3-48b4-a1f2-1cdc3e97d5df.png)

![data error](https://user-images.githubusercontent.com/76883800/187529715-43572859-5607-424a-8264-1c8a78de4418.png)

it seems that there is a missing functionality ( that IMO is basic in order to query ElasticSearch for instance) 
can it be resolved and be added soon?

**Comment by pavelfeldman** [comment]
Would `request.fetch('...', { method: 'GET', data: })` work for you?

**Comment by moshikd** [comment]
I tried to use it and still it does not work. this is the code:
`import { test, expect } from '@playwright/test';
test("Get simki info", async ({request})=> {
    const response = await request.fetch('http://vcs7pelb.geoedge.be/es/ad_matrix_agg_*/_search', {
        method: "GET", 
        headers:{
            'Authorization': 'Basic ZWxhc3RpYzppQ2lxaFZhQ0p5JjlLMiNp',
            'Content-Type': 'application/json',
            'Accept': '*/*',
        },
        data: {
            key1: 'value1',
            key2: 'value2',
            key3: 'value3',
            key4: 'value4',
          }     
    })
    console.log(await response.json());
    expect(response.status()).toBe(200);
})
`

![monosnap 31 08 22](https://user-images.githubusercontent.com/76883800/187610892-8c69b0a2-0595-4b55-86e8-20346b544276.png)

Am i missing something?



![monosnap 31 08 22](https://user-images.githubusercontent.com/76883800/187610166-7eb2733a-e155-4dfd-8367-a62c7f0b47cf.png)

**Comment by pavelfeldman** [comment]
Ouch, we are indeed not accepting raw body into any of the fetch requests.

**Comment by moshikd** [comment]
will this functionality be added soon? we will appreciate it if this could be delivered so we could add it to our testing cycle that involved many Get requests with Payload/ body?
any timeline for this? 
Thanks again

**Comment by moshikd** [comment]
@yury-s @pavelfeldman 
i have tested it with latest version playwright 1.26.
It seems to work with fetch with GET method: fetch('http://test.test.com', { method: 'GET'....  ( which is great) BUT it does not work with request.get ( as it mentioned in my first comment) . 
should it work also with request.get ??
thanks in advance

**Comment by YusukeIwaki** [comment]
@yury-s @pavelfeldman I found that the context.request.get API definition doesn't have `data` param, and I fixed the issue.
Could you review it? Thank you in advance.

**Comment by moshikd** [comment]
@YusukeIwaki @yury-s was it fixed and deployed? if not when it be available?

**Comment by YusukeIwaki** [comment]
@moshikd It seems Playwright 1.27 includes the fix.
