### ISSUE TITLE
[Question]use codegen with extraHTTPHeaders

### ISSUE THREAD

**Issue by yile222** [microsoft/playwright#16944]
Hello, I just started using playwright in my project,in the playwright.config.ts, extraHTTPHeaders doesn't take effect when I use the codegen command,I can't find the property in the request anymore

**Comment by pavelfeldman** [comment]
codegen does not respect your test config, it is a separate utility. You can use the [VSCode extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) to run a test with 'Show browser' mode on and then use 'Record from here'.

**Comment by pavelfeldman** [comment]
https://www.youtube.com/watch?v=NFLHA57a-so - watch this for more details.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
