### ISSUE TITLE
Not using channel on config file when Show and Reuse browser is checked

### ISSUE THREAD

**Issue by wmira** [microsoft/playwright#16955]
How can I have the extension use the config file for the browser to use? If  I run: npx playwright test from the command line, tests executed fine. If I run test from the VSCode Extension with "Show & Reuse browser" unchecked, it executes tests fine as well.

Problem is if I have "Show and reuse browser" checked it always insist on launching chromium (which I dont have) even though on the playwright config I have use { channel: 'chrome' } only -- which is use when launching from command line.

Is there a way to have the Extension to use installed browser?

**Comment by dgozman** [comment]
This was indeed fixed by #16898.
