### ISSUE TITLE
[BUG] Chrome -  Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright#16951]
**Context:**
- Playwright Version:1.25
- Operating System: Windows
- .NET version: .NET 6
- Browser: Chromium - chrome channel
- ProductVersion  105.0.5195.54 
 - FileVersion    105.0.5195.54                                                                                                                                                

**Describe the bug**

Running my Tests in chrome channel is seems after a couple of tests playwright is throwing an error.
i create a new context for each test but i am seeing after a few tests, not always the same test in same order

==================== Browser output: ====================
<launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\VSSADM~1\AppData\Local\Temp\playwright_chromiumdev_profile-ew4AQv --remote-debugging-pipe --no-startup-window
<launched> pid=4152
[pid=4152][err] [4152:4436:0831/100839.566:ERROR:device_event_log_impl.cc(214)] [10:08:39.566] Bluetooth: bluetooth_adapter_winrt.cc:1074 Getting Default Adapter failed.

**Comment by pavelfeldman** [comment]
What is the script that you are running and what is the error thrown? This bluetooth error does not look critical.

**Comment by infinitejest69** [comment]
its a different script that fails each time. running on an Azure pipeline windows agent. i switched to headless and that seems to have solved the issues for now. also Chrome was fine on version 104.0.5112.102 which was being deployed yesterday and had no issues. the only thing that changed in my scripts in the playwright command to downloads chrome downloaded a newer version.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
