### ISSUE TITLE
Can we please add pause functionality while recording tests in playwright-vscode plugin

### ISSUE THREAD

**Issue by AmareshFnu** [microsoft/playwright#16966]
My application requires OTP authentication, Basically whenever i open recording option,I have to repeat login functionality, however in CLI, we do use the storageState, that bypasses authentications. similar that can we implement reuse authentication option in VS extension plugin as well. And also please provide Pause options while recording the sessions, That would help skip recording the scripts for unwanted steps. We can directly resume recording options wherever we would like to capture the steps. Please consider this option Thank you ,
Amaresh

**Comment by pavelfeldman** [comment]
Implemented in vscode extension, will ship along with v1.28.
