### ISSUE TITLE
Tests fail to run when multiple configs are present

### ISSUE THREAD

**Issue by mozeryansky** [microsoft/playwright#16978]
I have an examples folder within my main app containing various sample projects, one was a playwright example with a config. In my main app I had my own config. VSCode would not run any test when pressing the run button and there was no indication of a failure. Running from the command line worked fine.

I figure it out that the default profile being selected was from the config file in my examples folder and not the top level config file. Deleting that file fixed the issue.

Shouldn't this extension only use the top most config?

**Comment by pavelfeldman** [comment]
VS Code extension is generic and requires some getting used to. You can select default profiles (configs and projects) that will run when pressing the global Run button.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/16982
