### ISSUE TITLE
No debug reason for failure

### ISSUE THREAD

**Issue by mozeryansky** [microsoft/playwright#16977]
I was having an issue where pressing run did nothing. I can run the tests fine from the command line, but the vscode extension wouldn't work. I don't see any error messages prompted or in console. I discovered the issue (https://github.com/microsoft/playwright-vscode/issues/152) was another playwright.config.ts file was in an examples folder and the extension was picking up.

Where could I have found this error printed in a console log? If not, can it be made available?

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/16978
