### ISSUE TITLE
Playwright Inspector Does Not Open In 1.25.0

### ISSUE THREAD

**Issue by richmar10** [microsoft/playwright#16989]
After upgrading @playwright/test to 1.25.0  the playwright inspector no longer opens by calling `await page.pause()`.   Downgrading to 1.24.2 resolves this issue temporarily.

Once the page.pause() is hit, the test just pauses and will not continue.

**Comment by pavelfeldman** [comment]
Could you share more about why you are using the inspector? Our assumption is that VS Code extension how offers all the features inspector provides.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/16994

**Comment by richmar10** [comment]
I used the playwright inspector to pause at a specific line, and start recording new clicks so that I can improve existing tests.  Is this possible with the vscode extension and I'm not just using it correctly?

**Comment by julian-hoch** [comment]
> Could you share more about why you are using the inspector? Our assumption is that VS Code extension how offers all the features inspector provides.

How would you test your locators with just VSCode? With the inspector you can write and validate locator expressions and directly see the result in the browser, or vice versa select elements in the browser and see a proposed locator expression.
