### ISSUE TITLE
Test grouping (test.describe) does not apply to the name of the test

### ISSUE THREAD

**Issue by ScubaDaniel** [microsoft/playwright#16986]
We're using `test.describe` to provide a top-level label on parameterized tests, per this documentation: https://playwright.dev/docs/test-annotations#group-tests

The text in the `test.describe` is not added to the test name, which makes it impossible to know which test we're running/debugging:
![image](https://user-images.githubusercontent.com/66570270/177811216-be22ab19-f7cb-4cc2-9da4-52579f6bee62.png)

The same problem applies when you're on the Testing tab and try to view in a list view:
![image](https://user-images.githubusercontent.com/66570270/177811973-73ddfb09-e1d6-45a5-8578-433b4829af4a.png)

If we add the parameter in the `test` call itself, it gets added to the name:
![image](https://user-images.githubusercontent.com/66570270/177812377-bcec99e1-1901-438a-8a9f-15e7467620e3.png)

This seems like a bug, as the Playwright output lists them just fine.

**Comment by pavelfeldman** [comment]
I'm seeing the full title, including the describes. What VSCode version are you using?

<img width="393" alt="Screen Shot 2022-08-31 at 12 47 03 PM" src="https://user-images.githubusercontent.com/883973/187768883-ca868caa-5293-414f-b8d2-2c409ea15cea.png">

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
