### ISSUE TITLE
No Test Found 

### ISSUE THREAD

**Issue by gtodd876** [microsoft/playwright#16982]
* Using Windows 10 & VS Code v1.64.2 (user setup)
* Install Microsoft's official Playwright extension v0.2.1
* Add Playwright to project with `Ctrl-Shift-P` and typing `install playwright`
* Click on the `Testing` Icon on the Activity bar to open Playwright extension pane
* No tests are found
* No green play buttons to run isolated tests in the test file 
![image](https://user-images.githubusercontent.com/28220658/155334438-5ac567fb-35bf-4b04-8244-cd7b7ab3d4f2.png)

**Comment by pavelfeldman** [comment]
New VSCode introduced a smartness that runs the project selected file belongs to even if this project is not selected to be a part of the active configuration in the Run/Debug dropdown. Let me close this issue, but please open a new one if there are outstanding action items on our side.

**Comment by lrstanley** [comment]
> New VSCode introduced a smartness that runs the project selected file belongs to even if this project is not selected to be a part of the active configuration in the Run/Debug dropdown. Let me close this issue, but please open a new one if there are outstanding action items on our side.

Can you clarify exactly what this means? Seems rather unclear to me.

**Comment by mxschmitt** [comment]
@lrstanley we don't monitor closed issues, please file a separate issue with a repro repo and we are happy to take a look!
