### ISSUE TITLE
Faulty installation script and inadequate documentation regarding installation

### ISSUE THREAD

**Issue by talkingtoaj** [microsoft/playwright#16983]
I've had my developer friend tell me that the vscode playwright extension doesn't work. I figured if Microsoft supports it, it must. So I dug into the issue myself. I believe the problem is a slightly faulty installation script and inadequate documentation. See below for my journey and fix.

# Personal Specs
* Running on windows 11, WSL2 shell
* I already have playwright and Chromium installed and successfully running tests outside of the VSCode extension. 

# Steps I took
After I install the extension, it successfully finds my tests and populates the left sidebar.
If I run tests, they fail immediately with no description as to why
The extension help page seems to suggest using VSCode's command ">Install playwright" is not necessary if you already have playwright installed (I installed it with yarn). Since it isn't working, I use the VSCode command and attempt to install playwright, chromium browser support and dependencies. 

Most seems to install correctly, until this point:
```
Err:7 https://dl.yarnpkg.com/debian stable InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
Reading package lists... Done
W: GPG error: https://dl.yarnpkg.com/debian stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 23E7166788B63E1E
E: The repository 'https://dl.yarnpkg.com/debian stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
Failed to install browsers
Error: Installation process exited with code: 100
Error: Command failed: npx playwright install --with-deps chromium
    at checkExecSyncError (node:child_process:828:11)
    at execSync (node:child_process:899:15)
    at executeCommands (/home/talkingtoaj/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/home/talkingtoaj/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4592:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /home/talkingtoaj/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4844:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 6509,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /home/talkingtoaj/GFGD_frontend
npm ERR! command failed
npm ERR! command sh -c create-playwright "--quiet" "--browser=chromium" "--install-deps"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/talkingtoaj/.npm/_logs/2022-06-17T13_31_37_183Z-debug-0.log
```
It appears that there is a problem with unsigned debian package which prevents chromium from being installed?

If I try playwright extension again, still fails each test immediately. If I run in debug mode and have the test file open in the main window, I receive more info:
```
browserType.launch: Executable doesn't exist at /home/talkingtoaj/.cache/ms-playwright/chromium-1005/chrome-linux/chrome
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers: ║
║ ║
║ npx playwright install ║
║ ║
║ <3 Playwright Team ║
╚═══════════
```

So I try `npx playwright install` and it installs browsers chromium, firefox, webkit.

All works now!

# Requested action
Better documentation:

1. Select to install playwright from Vscode command bar, even if you have previously installed playwright and browsers
2. If install process fails to install browser support, run `npx playwright install` from terminal to complete installation
3. Make it clear that you must have the playwright test file open in the main window in order to have the debug terminal open up and see debug output

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
