### ISSUE TITLE
Adding a nonstandard reporter in Playwright configuration causes tests to no longer be found.

### ISSUE THREAD

**Issue by dougrday** [microsoft/playwright#16987]
When configuring Playwright, if I add a non-standard reporter to the configuration, the extension can no longer find my tests.

## Works
```
reporter: [["list"]],
```

## Works
```
reporter: [["list"], ["html"]],
```
![image](https://user-images.githubusercontent.com/923398/179255993-3c3fb12f-f8ff-4c68-909b-f35f45536ad4.png)

## Fails
```
reporter: [["list"], ["@bgotink/playwright-coverage", {...}]],
```
or
```
reporter: [["list"], ["other-nonstandard-reporter"]],
```

![image](https://user-images.githubusercontent.com/923398/179255580-adf6e31d-764d-4b23-9927-44f1957536a2.png)

This is forcing me to use multiple configuration files in my project - one simple one to ensure the VSCode extension works, and another for more in-depth testing needs.

**Comment by pavelfeldman** [comment]
Things work for me on  the example project w/ `reporter: [['html'], ['@bgotink/playwright-coverage']],`. Could you publish a small repo I could clone to reproduce?

**Comment by dougrday** [comment]
I've tried to reproduce with a simple repo, and cannot reproduce this anymore. This leads me to conclusion that it was likely an issue with the specific 3rd-party reporter `@bgotink/playwright-coverage`, which has been resolved in the latest version.

Closing - thanks for the support.
