### ISSUE TITLE
Debug test does not work

### ISSUE THREAD

**Issue by Camo30** [microsoft/playwright#16985]
Hey guys,

When I click on 'Debug Test' (on the left) the following appears:

![grafik](https://user-images.githubusercontent.com/33700436/177759159-a8f0284d-2071-4791-a9a3-643f17329b73.png)

Any ideas? Tried to reproduce the issue in a new workspace without any success.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
