### ISSUE TITLE
[Bug]  browser._newContextForReuse: Target closed

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#16990]
Hi,guys, I am sufferring such errors when debugging some test right after other tests finished with the `show & reuse browser` option checked:
```ts
 browser._newContextForReuse: Target closed
 =========================== logs ===========================
  navigating to "about:blank", waiting until "load"
  ============================================================
        at Object.context [as fn] (E:\<path>\node_modules\.pnpm\@playwright+test@1.25.0\node_modules\@playwright\test\lib\index.js:767:21)
```

As the option mean, The browse will be reused and the page opened by the previous test is also kept
However, once I started another debugging through the playwright vscode extension, the previous opened page will navigate to "about:blank" and  test suddenly failed with such error

## System:
 - OS: Windows 10 10.0.22000
 - Memory: 19.76 GB / 31.73 GB
## Binaries:
 - Node: 16.13.0 - ~\AppData\Local\fnm_multishells\9580_1660468529134\node.EXE
 - Yarn: 1.22.19 - ~\scoop\apps\yarn\current\bin\yarn.CMD
 - npm: 8.1.0 - ~\AppData\Local\fnm_multishells\9580_1660468529134\npm.CMD
## npmPackages:
 - playwright: 1.25.0 => 1.25.0

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by syed-sapaad** [comment]
browser._newContextForReuse: Target closed

Execution log

navigating to "about:blank", waiting until "load"
