### ISSUE TITLE
[Question] Browser Pool

### ISSUE THREAD

**Issue by RichiCoder1** [microsoft/playwright#1699]
Howdy! Just had a question about the remote browser support. It looks like with [`launchServer`](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsertypelaunchserveroptions) it should be trivial to create single remote server that can be used test against. I wanted to ask if the was any potential issues scaling that up such that I could, say, have x Pods (possibly dynamically scaled) running Playwright servers to enable parallel testing? Could I just spin up a number of containers w/ Playwright and LB between them without issues?

**Comment by aslushnikov** [comment]
> Could I just spin up a number of containers w/ Playwright and LB between them without issues?

@RichiCoder1 yes, you can! This is a primary use case for `launchServer` API.

Let us know how it goes :)

**Comment by RichiCoder1** [comment]
Will do!

**Comment by bekraupov** [comment]
Did you have any issues with sticky sessions or websocket connection stayed connected to one of the pods at all times?   (example use case where you have 3 pods and trying to run 3 tests against them).
