### ISSUE TITLE
`page.pause()` does not work when debugging tests via VS Code

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#16994]
Steps to reproduce

1. Create a Playwright project (Test: Install Playwright)
2. Add `await page.pause()` to `tests/example.spec.ts`

   <img width="568" alt="image" src="https://user-images.githubusercontent.com/193136/181919058-31ae532e-2f33-485e-b0b0-c41b9524000e.png">

3. Right click and **Debug Test**

    <img width="324" alt="image" src="https://user-images.githubusercontent.com/193136/181919113-509a0bfe-c1c1-42b4-af6a-161370306f89.png">

Expected:

- Test should pause on `page.pause()`

Actual:

- Test runs right past `page.pause()`

**Comment by pavelfeldman** [comment]
Could you share more about why you are using the inspector? Our assumption is that VS Code extension how offers all the features inspector provides.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
