### ISSUE TITLE
Breakpoints in VS Code shift up several lines when debugging starts

### ISSUE THREAD

**Issue by stuartbrussell-intuit** [microsoft/playwright#16993]
When debugging a test, a breakpoint set in the code will visibly shift up several lines as soon as debugging starts. The code then breaks on the (incorrect) location as if I had set the breakpoint there on purpose. Then when the test stops, the breakpoint visibly moves back to the original line.

```
const { test } = require('@playwright/test');
test.describe('Debug breakpoints', async () => {
  test('test breakpoints', async ({ page }) => {
    await page.goto('https://accounts.intuit.com/terms-of-service')
    await page.locator('text=INTUIT WEBSITE TERMS OF SERVICE').waitFor();
  });
});
```

1. Set a breakpoint on the last line of code "await page.locator...". 
2. Right click the green triangle to the left of either "test('describe'..." or "test('test breakpoints'...", and choose Debug Test.
3. Or, you can click Debug Test in the VSCode Testing tab.

Expected: script breaks on "await page.locator..."
Actual: 
1. red dot breakpoint indicator disappears from where it was set, and the indicator now appears several lines up, e.g. at "const { test }..." or "test.describe(...". 
2. The script breaks at the line with the indicator.
5. Continue at the breakpoint, and the test does not break at the intended line, but finishes normally.
6. The breakpoint indicator now moves back to the correct line.

Playwright Test for VSCode 0.2.10 (first noticed it in 0.2.6, the first version I installed).

VSCode Version: 1.70.2
Commit: e4503b30fc78200f846c62cf8091b76ff5547662
Date: 2022-08-16T05:36:37.829Z (1 wk ago)
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Darwin x64 21.5.0

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
