### ISSUE TITLE
[Question]Playwright and selenium grid integration

### ISSUE THREAD

**Issue by apurva3107** [microsoft/playwright#17019]
For playwright and selenium grid integration, how to pass the hub url in the playwright browser launch setup below?
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      Page page = browser.newPage();
      page.navigate("http://playwright.dev");
      System.out.println(page.title());

Thanks,
Apurva

**Comment by dgozman** [comment]
@apurva3107  Take a look at the [documentation](https://playwright.dev/java/docs/selenium-grid).

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
