### ISSUE TITLE
[BUG] got error when assign Locator as function param on playwright v1.25.1

### ISSUE THREAD

**Issue by rio-ap** [microsoft/playwright#17018]
**Context:**
- Playwright Version:1.25.1
- Operating System: Mac
- Node.js version: 16.16.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: got error in latest playwright (1.25.2) when set Locator as function param. this didnt happen in version (1.24.2)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```Typescript 
hotelDetailPage.ts
import { expect, Page } from '@playwright/test';
import { Locator } from 'playwright';
import { mockingClass } from '../../../shared/network/mocking';
import { HotelNewSearchFormPage } from './hotelNewSearchFormPage';

const classConstant = {
    btBookRoomNow : "xpath=//*[text()=\"Book Now!\"]/parent::*[@role='button']",
    iconPAHXPathFromRoomBt : "xpath=./../..//*[text()='Pay upon Check-in']",
    btBookNowEle:(textLang:string) => `xpath=//*[@id=\"room-search-bar\"]/../../following-sibling::*//*[text()=\"${textLang}"]/parent::*[@role='button']`
}

export class HotelDetailPage{
    readonly page: Page;
    mock: mockingClass;

    hotelCountry:string = '';
    requiredBookingData:Array<string> = new Array<string>;

    constructor(page: Page) {
        this.page = page;
        this.mock = new mockingClass(this.page);
    }
. //some logic
. //some logic
. //some logic
     async getAllRequiredData(i:number, btBook:Locator){
        await this.setAllRequiredData(i, btBook);
        await this.page.waitForTimeout(500);
        return this.requiredBookingData;
    }
    async selectCheapestPayNowRoomWithSetData(useMock:boolean, language?:string){
    let lang = ""
    if(language!=undefined){
       lang = language;
    }
    let btBookRoomEle = (await this.btBookNowEleBuilder(lang))[0];
    //some logic
       if(!(await (this.page.locator(btBookRoomEle).nth(i)).locator(classConstant.iconPAHXPathFromRoomBt).count() > 0)){
           console.log("pay now1, loop: "+i);
           await this.getAllRequiredData(i, await this.page.locator(btBookRoomEle).nth(i)); <= //error in this line code
           await this.page.waitForTimeout(500);
           console.log(await(await this.page.locator(btBookRoomEle).nth(i)).textContent());
           await(await this.page.locator(btBookRoomEle).nth(i)).click();
           break;
       }
    }

}
```
**the error**
`Argument of type 'import("/Users/user/Documents/Project/projectname/node_modules/playwright-core/types/types").Locator' is not assignable to parameter of type 'import("/Users/user/node_modules/playwright-core/types/types").Locator'.ts(2345)
`

**Describe the bug**

the bug is happen after upgrading to playwright version 1.25.1. it return error when function have locator as Parameter. this didnt happen on previous version (1.24.2). because of this we downgrade the playwright version in our project

**Comment by pavelfeldman** [comment]
You have two conflicting installations of @playwright/test:

in /Users/user/Documents/Project/projectname/node_modules
and
in Users/user/node_modules

**Comment by pavelfeldman** [comment]
You can't mix playwright and @playwright/test, you should only use @playwright/test.
