### ISSUE TITLE
[Question] Hi, is there any method to make html report created before global teardown execution?

### ISSUE THREAD

**Issue by rio-ap** [microsoft/playwright#17015]
as the title said, i was wondering if there any method to make built-in html reporter created before global teardown?

i have need to send .zip/ file report after all the test completed. all the test function is done via before all - after all. global teardown is used for reporting. but for some reason, i found the report (default folder under "./playwright-report) is created after the global teardown finish.

is there something wrong in my config? or there any function to do that?

pw version : 1.25.1
OS : mac os

**Comment by rio-ap** [comment]
here the log what i get 
`Global Setup
before all
before all
before all
before all
before each
test 4
after each
after all
before each
test 2
after each
after all
before each
test 3
after each
after all
before each
test 1
after each
after all
····Global Teardown

Error: File not found: report`

it give error file not found because the report folder is not found

**Comment by dgozman** [comment]
@rio-ap Global teardown runs before reporters finish, this is by design. I'd recommend a separate step in your CI configuration that uploads the report. Take a look [here for an example](https://github.com/microsoft/playwright/blob/main/.github/workflows/tests_primary.yml#L184-L186). Let me know if this helps.

**Comment by rio-ap** [comment]
Hi, already found solution for this, i created custom reporter that contain only onEnd function to zip built in report result and sent to the zip file to slack message. But will check the example if this solution is flaky, for now my solution already fit my need

**Comment by dgozman** [comment]
@rio-ap Reporters' `onEnd()` are called in the order of definition in the config file, so your solution is great.

**Comment by anbhattacharjee** [comment]
@rio-ap - could you please share the code as i am also facing the same issue ?
