### ISSUE TITLE
[Question] By default, test files are run in parallel ? Even when num(workers) < num(files) ?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#17013]
Hi there!

You wrote in the docs:

> By default, test files are run in parallel

https://playwright.dev/docs/test-parallel#worker-processes

Also you wrote:

> You can disable any parallelism by allowing just a single worker at any time. Either set workers: 1 option in the configuration file or pass --workers=1 to the command line.

https://playwright.dev/docs/test-parallel#disable-parallelism

I have multiple workers, not one. And Im a bit confused. What about the case, when I have 5 files and 3 workers? All 5 files run parallel?

Is it guaranteed that test files inside one worker runs serial by default (even if total number of workers > 1)?

**Comment by Diokuz** [comment]
Is it guaranteed that test files inside one worker runs serial by default (even if total number of workers > 1)?

**Comment by pavelfeldman** [comment]
Files run in parallel, the number of parallel tracks is defined by the number of workers.

> I have multiple workers, not one. And Im a bit confused. What about the case, when I have 5 files and 3 workers? All 5 files run parallel?

No, you can't run 5 parallel with only 3 workers

> Is it guaranteed that test files inside one worker runs serial by default (even if total number of workers > 1)?

There is no such thing as 'test files inside one worker'. But we do say in that doc "Tests in a single file are run in order, in the same worker process."

**Comment by Diokuz** [comment]
Thanks! Thats important, because in fact test files (in each worker) runs not in parallel, but in order. I would suggest to change this statement then:

> By default, test files are run in parallel
