### ISSUE TITLE
[BUG] Component testing error with vue

### ISSUE THREAD

**Issue by hangboss1761** [microsoft/playwright#17017]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- @playwright/test:1.23.1、@playwright/experimental-ct-vue：1.23.1
- Operating System: [e.g. Windows, Linux or Mac]
- mac
- Node.js version: [e.g. 12.22, 14.6]
- v16.0.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
all
- Extra: [any specific details about your environment]
## System:
 - OS: macOS 11.5.1
 - Memory: 1018.00 MB / 16.00 GB
## Binaries:
 - Node: 16.0.0 - ~/.nvm/versions/node/v16.0.0/bin/node
 - Yarn: 1.22.5 - ~/.yarn/bin/yarn
 - npm: 7.10.0 - ~/.nvm/versions/node/v16.0.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

see this repo:
https://github.com/sand4rt/playwright-component-testing-vue

**Describe the bug**

Add any other details about the problem here.

```
undefined: net::ERR_EMPTY_RESPONSE at http://localhost:3100/playwright/index.html
=========================== logs ===========================
navigating to "http://localhost:3100/playwright/index.html", waiting until "load"
============================================================
```

![image](https://user-images.githubusercontent.com/30379896/187932288-785657c1-5737-424b-ad15-45d2cc88ae5a.png)

**Comment by pavelfeldman** [comment]
It works for me, also you might want to file an issue against that repo instead.
