### ISSUE TITLE
page.evaluate: TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by zw-slime** [microsoft/playwright#17029]
``` javascript
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({ devtools: true });
    const page = await browser.newPage();


    await page.goto('https://www.zzfx.net.cn/policy/com_reporterandroid_weatherprojects/privacy.html', { waitUntil: 'domcontentloaded' });

    await page.evaluate('1 + 2')

})();
```
playwright version: 1.23.4

Run it , then report error: UnhandledPromiseRejectionWarning: page.evaluate: TypeError: Cannot convert undefined or null to object
<img width="1428" alt="企业微信截图_d3089641-c625-4fcc-8178-5313a6ed0670" src="https://user-images.githubusercontent.com/18528957/188050139-65ac0921-d37d-4869-8688-fbb15af6e88f.png">

**Comment by mxschmitt** [comment]
The issue with their site is that they do the following in their `<head />`:

```javascript
var defineProperty = Object.defineProperty;
Object.defineProperty = function (exports, name) {
  if (name === '__esModule') {
    exports[name] = true;
    return;
  }
  return defineProperty.apply(this, arguments);
};
```

**Comment by zw-slime** [comment]
I see the issue is closed. so 1.26 How long will it take to release？

**Comment by mxschmitt** [comment]
We can't provide an eta on releases but you can use the canary releases to get the latest features: https://playwright.dev/docs/canary-releases
