### ISSUE TITLE
[BUG] test.fail() is ignored when awaiting a promise that times out

### ISSUE THREAD

**Issue by cpolera** [microsoft/playwright#17026]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Mac, Linux 
- Node.js version: 16.15.0
- Browser: Chromium

```javascript
import { test, expect, request, Page } from '@playwright/test';

test.beforeEach(async({page}) =>{
  await fakeRoute(page);
})

test('homepage has Playwright in title and get started link linking to the intro page @smoke', async ({
  page
}) => {
  test.fail();
  test.setTimeout(5000);
  // Subscribe to 'request' and 'response' events.
  page.on('request', request =>
      console.log('>>', request.method(), request.url()));
  page.on('response', response =>
      console.log('<<', response.status(), response.url()));

  const [response] = await Promise.all([
    page.waitForResponse('**/img/logos/**.jpg'),
    page.goto('https://playwright.dev/')
  ]);

  await expect(response.ok()).toBeTruthy();

});

//delay response long enough to imitate not getting the image
export const fakeRoute = (page : Page) => page.route('**/img/logos/**.jpg', route => {
  void (async () => {
    await delay(5000);
    await route.fulfill({
      status: 404,
    });
  })();
});

export const delay = async (ms) => {
  const waiter = new Promise(resolve => {
    setTimeout(function() {
      resolve("true");
    }, ms);
  });
  await waiter;
}

```

**Describe the bug**

If the test above times out on the waitForResponse, then the test status will show as failed. It ignores the test.fail() incorrectly.
You can change the test around to fail on any kind of timeout, but ultimately it will still show as failed instead of passed. 

According to the documentation, test.fail() is unconditional. I'd expect this to not show as a failure.
https://playwright.dev/docs/api/class-test#test-fail-1

**Comment by pavelfeldman** [comment]
`test.fail` is intended to be used as a negative test. I.e. it should successfully assert the wrong behavior. Test that times out is a broken test rather than a negative test.

**Comment by cpolera** [comment]
That seems contrary to the documentation
"This is useful for documentation purposes to acknowledge that some functionality is broken until it is fixed"

`import { test, expect } from '@playwright/test';

test('not yet ready', async ({ page }) => {
  test.fail();
  // ...
});`

Based on this and the fact it says unconditionally, it seems like this really should work. I think something like waitForResponse failing because the response never comes is also a valid failure. I think its jumping through hoops to make sure that you fail on an assert for a response that never comes.
