### ISSUE TITLE
[Question] Why ScrollIntoViewIfNeededAsync() is not working with virtual scroll?

### ISSUE THREAD

**Issue by MilanMax** [microsoft/playwright#17034]
Locator.ScrollIntoViewIfNeededAsync() is not working because of virtual scroll. I need to use Page.Mouse.WheelAsync() to do the scroll and click on certain node.

Is there maybe some other suggestions how to do this?

**Comment by pavelfeldman** [comment]
The nature of the virtual scroll is that it handles the wheel / scroll events to build content on the fly. So you need to initiate those wheel/scroll events for it to do so. So you are doing the right thing.
