### ISSUE TITLE
[BUG] waitForResponse won't throw when the request is aborted

### ISSUE THREAD

**Issue by skysantoroa** [microsoft/playwright#17035]
**Context:**
- Playwright Version: 1.25
- Operating System: Ubuntu 22
- Node.js version: 16
- Browser: Firefox, Chromium, Webkit

**Code Snippet**

The following code should wait for a response received from polling my backend.

```typescript
const results = await Promise.all([
    page.waitForResponse(
      async (res) => await isTransactionError(baseURL!, res),
    ),
    page.locator('input[type="file"]').setInputFiles(promoFilePath),
  ])
```

```typescript
export const isTransactionError = async (
  baseUrl: string,
  response: Response,
) => {
  if (response.url() === `${baseUrl}graphql`) {
    const { 'content-length': contentLength, 'content-type': contentType } =
      await response.allHeaders()
    if (+contentLength > 0 && contentType === 'application/json') {
      const json = await response.json()
      const lastStage = json?.data?.node?.stages?.at(-1)
      const res =
        response.status() === 200 &&
        lastStage?.__typename === 'ValidationStage' &&
        lastStage?.state === 'ERROR' &&
        lastStage?.errors?.length > 1
      if (res) {
        console.log(`transaction id ${json?.data?.node?.id}`)
      }
      return res
    }
  }

  return false
}
```

**Describe the bug**

My client will abort the request when right before the polling is stopped but Playwright is unable to parse the response of the aborted request thus timing out at the line `await response.json()`.

The last `response.json` of my stack trace looks like

![image](https://user-images.githubusercontent.com/101178279/188116027-339f981e-fef6-47d3-aa4f-142096963f34.png)
![image](https://user-images.githubusercontent.com/101178279/188116074-99e15db7-cf1b-44d3-84d4-f8a7b9f879cb.png)

Here is the test output run from docker
```
playwright     |     Test timeout of 120000ms exceeded.
playwright     | 
playwright     |     page.waitForResponse: Page closed
playwright     | 
playwright     |       75 |
playwright     |       76 |   const results = await Promise.all([
playwright     |     > 77 |     page.waitForResponse(
playwright     |          |          ^
playwright     |       78 |       async (res) => await isTransactionError(baseURL!, res),
playwright     |       79 |     ),
playwright     |       80 |     page.locator('input[type="file"]').setInputFiles(promoFilePath),

```

**Comment by pavelfeldman** [comment]
Your snippet looks wrong - the callback in `waitForResponse` should be sync. Your test always returns truthy value (`Promise`), so it accepts all the responses. And nothing waits for `isTransactionError`, so the tests finishes and page is closed before it ends. If you have async operations that need checking, you should collect all the 'request' events that are issued while you re setting the input files. Then you should iterate them and check their responses:

```js
const requests = [];
page.on(request => requests.push(request));
await page.locator('input[type="file"]').setInputFiles(promoFilePath);
const responses = await Promise.all(requests.map(r => r.response()));
for (const response of responses) {
  const json = await response.json();
  ...
}

**Comment by skysantoroa** [comment]
> Your snippet looks wrong - the callback in `waitForResponse` should be sync. Your test always returns truthy value (`Promise`), so it accepts all the responses. And nothing waits for `isTransactionError`, so the tests finishes and page is closed before it ends. If you have async operations that need checking, you should collect all the 'request' events that are issued while you re setting the input files. Then you should iterate them and check their responses:
> 
> ```js
> const requests = [];
> page.on(request => requests.push(request));
> await page.locator('input[type="file"]').setInputFiles(promoFilePath);
> const responses = await Promise.all(requests.map(r => r.response()));
> for (const response of responses) {
>   const json = await response.json();
>   ...
> }
> ```

You're right, I posted the wrong snippet, this is the one I've used for my test suite

```
const [uploadResult] = await Promise.all([
    waitForTransactionError(page, baseURL!),
    selectFileBtn.setInputFiles(promoFilePath),
  ])
```
```

export const waitForTransactionError = (page: Page, baseURL: string) => {
  return page.waitForResponse(
    async (res) =>
      await (async () => {
        if (res.url() === `${baseURL}graphql`) {
          const {
            'content-length': contentLength,
            'content-type': contentType,
          } = await res.allHeaders()
          if (+contentLength > 0 && contentType === 'application/json') {
            const json = await res.json()
            const lastStage = json?.data?.node?.stages?.at(-1)
            const { state, errors, __typename } = lastStage || {}
            return (
              res.status() === 200 &&
              __typename === 'ValidationStage' &&
              state === 'ERROR' &&
              errors.length > 1
            )
          }
        }
        return false
      })(),
  )
}
```

**Comment by pavelfeldman** [comment]
It suffers from exactly the same problem, please refer to my previous response.

**Comment by skysantoroa** [comment]
> And nothing waits for isTransactionError

Not true, the test is stuck in the `isTransactionError` until the response that was looking for is received. After setting the input file I should wait a specific response as the client starts polling. The issue arises when a new response is received before the polling is stopped, because another response is received but the body can't be parsed

**Comment by skysantoroa** [comment]
I'm not getting why you are saying that the methods above are wrong. The `waitForResponse` type signature is

```typescript
Page.waitForResponse(urlOrPredicate: string | RegExp | ((response: Response) => boolean | Promise<boolean>)
```

My innermost function respect the same type

```typescript
  const p = async (res: Response) =>
    await (async () => {
      if (res.url() === `${baseURL}graphql`) {
        const { 'content-length': contentLength, 'content-type': contentType } =
          await res.allHeaders()
        if (+contentLength > 0 && contentType === 'application/json') {
          const json = await res.json()
          const lastStage = json?.data?.node?.stages?.at(-1)
          const { state, errors, __typename } = lastStage || {}
          return (
            res.status() === 200 &&
            __typename === 'ValidationStage' &&
            state === 'SUCCESS' &&
            errors.length === 0
          )
        }
      }
      return false
    })()
```

How the `Response` returned by `waitForResponse` differs when `false` is returned? In my test more checks are implemented to see if the response got from the `waitForTransactionError` is the one expected, the problem here is not that the page closes before the test ends

**Comment by skysantoroa** [comment]
Implementing the `waitForResponse` method like this

```typescript
export const waitForTransactionError = async (page: Page, baseURL: string) => {
  const requests: Request[] = []
  page.on('request', (request) => requests.push(request))

  await page.waitForSelector(
    'text="Something went wrong while validating the file."',
  )

  const responses = await Promise.all(requests.map((r) => r.response()))

  for (const response of responses) {
    if (response && response.url() === `${baseURL}graphql`) {
      const { 'content-length': contentLength, 'content-type': contentType } =
        await response.allHeaders()
      if (+contentLength > 0 && contentType === 'application/json') {
        const json = await response.json()
        const lastStage = json?.data?.node?.stages?.at(-1)
        const { state, errors, __typename } = lastStage || {}
        if (
          response.status() === 200 &&
          __typename === 'ValidationStage' &&
          state === 'ERROR' &&
          errors.length > 1
        ) {
          return response
        }
      }
    }
  }
}
```

all the `response.json` are missing the Network data in the trace file

**Comment by dgozman** [comment]
@skysantoroa It seems like your backend aborts the request before sending the response. Therefore, there is no `response` object at all and `waitForResponse()` hangs waiting for a response. If you use `waitForRequest()`, you will get the request and `null` response for it:

```js
const request = await page.waitForRequest(async request => {
  const response = await request.response();
  if (!response)
    return false;  // Aborted request will not have a response.
  const json = await response.json();
  // .....
});
const response = await request.response();  // Get the response if needed.
```

**Comment by skysantoroa** [comment]
> @skysantoroa It seems like your backend aborts the request before sending the response. Therefore, there is no `response` object at all and `waitForResponse()` hangs waiting for a response. If you use `waitForRequest()`, you will get the request and `null` response for it:
> 
> ```js
> const request = await page.waitForRequest(async request => {
>   const response = await request.response();
>   if (!response)
>     return false;  // Aborted request will not have a response.
>   const json = await response.json();
>   // .....
> });
> const response = await request.response();  // Get the response if needed.
> ```

Is the response got from `waitForResponse` be null if the backend is returning no response?

**Comment by skysantoroa** [comment]
> @skysantoroa It seems like your backend aborts the request before sending the response. Therefore, there is no `response` object at all and `waitForResponse()` hangs waiting for a response. If you use `waitForRequest()`, you will get the request and `null` response for it:
> 
> ```js
> const request = await page.waitForRequest(async request => {
>   const response = await request.response();
>   if (!response)
>     return false;  // Aborted request will not have a response.
>   const json = await response.json();
>   // .....
> });
> const response = await request.response();  // Get the response if needed.
> ```

Is there any way to detect the aborted response in the `waitForResponse`?

**Comment by dgozman** [comment]
@skysantoroa When backend aborts the request before sending a response, there will be no response, and no "aborted response". Does that make sense?

**Comment by skysantoroa** [comment]
Yes, but the aborted signal comes from the client in my case via `AbortController`

**Comment by dgozman** [comment]
> Yes, but the aborted signal comes from the client in my case via `AbortController`

That should not matter, as long as the request is aborted before the response. I'd suggest to use `waitForRequest()` and capture anything you'd like as suggested above.

**Comment by skysantoroa** [comment]
So if a request is aborted by the client one cannot detect that using `waitForResponse`, do you confirm?

**Comment by dgozman** [comment]
> So if a request is aborted by the client one cannot detect that using `waitForResponse`, do you confirm?

As long as request was aborted before response was received from the server, yes.

**Comment by dgozman** [comment]
Closing as per above. If you still have issues, please file a new bug and link to this one.
