### ISSUE TITLE
[Feature] Grouping soft assertions to expect them to fail

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#17030]
Sometimes, there are a group of assertions that you want to do the inverse of (e.g. adding or removing `.not`) depending on the scenario.

Take for example, there are a bunch of `input` that you want to check that are `disabled` in one situation, and not disabled in another. At the moment, soft assertions will fail a test if any of the assertions fail, but in my scenario, I'd actually like the test to fail if any of them pass!

For example:
```
async function CHECK () {
	await test.expect.soft(page.locator("a")).toBeDisabled();
	await test.expect.soft(page.locator("b")).toBeDisabled();
	await test.expect.soft(page.locator("c")).toBeDisabled();
}
if (!beDisabled) {
	test.expect.inverse(CHECK);
}
else {
	CHECK();
}
```

is better than the current way

```
const targets = [
	"a",
	"b",
	"c",
];
for (const target of targets) {
	let exec = test.expect.soft(page.locator(target));
	if (!beDisabled) {
		exec = exec.not;
	}
	await exec.toBeDisabled();
}
```

**Comment by pavelfeldman** [comment]
This would be an extremely unusual pattern. You can always try/catch or .catch your assertions and achieve the desired behavior manually.

**Comment by A-ZC-Lau** [comment]
@pavelfeldman isn't it more unusual to correct behavior in a try/catch and continue on with the test?

How would a try/catch work in this case?

**Comment by pavelfeldman** [comment]
Well, `soft` can be implemented in userland using try/catch. Btw, for your use case, it sounds like you are looking for `toBeEnabled({ enabled })`. Let us do that for you instead.

**Comment by A-ZC-Lau** [comment]
@pavelfeldman but this would also extend to something like `toBeVisible()` and any other similar assertions that generally use a `not`
