### ISSUE TITLE
[Question] How to obtain the underlying WebSocket from chromium.connect()?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#17049]
I wish, for debugging purposes, to inspect the WebSocket object that is created by `chromium.connect`.

I cannot figure out looking at the source code how to obtain this object.

**Comment by pavelfeldman** [comment]
There is no way to obtain it, using proxy would be easier to sniff the traffic.

**Comment by pavelfeldman** [comment]
(note that this protocol can and will change w/o notice, it might become binary at any moment)

**Comment by punkpeye** [comment]
> it might become binary at any moment

Is this on a roadmap so I could track it?

The system that I am designing does rely on intercepting and manipulating this traffic.

Closing as the original question has been answered.
