### ISSUE TITLE
Multiple code examples violate typescript:S3799 rule

### ISSUE THREAD

**Issue by twalshOG** [microsoft/playwright#17043]
Multiple code example violate the "Destructuring patterns should not be empty"
https://rules.sonarsource.com/typescript/RSPEC-3799

Example from 
https://playwright.dev/docs/test-fixtures#overriding-fixtures
```typescript
import { test as base } from '@playwright/test';

export const test = base.extend({
  storageState: async ({}, use) => {
    const cookie = await getAuthCookie();
    await use({ cookies: [cookie] });
  },
});
```

**Comment by pavelfeldman** [comment]
Is this rule enabled by default anywhere? If not, I'd recommend disabling it.

**Comment by twalshOG** [comment]
This rule is enabled by default in SonarQube and SonarCloud.
Are you saying this rule is invalid or are you saying this is just how Playwright works so the rule must be violated in this case?

**Comment by pavelfeldman** [comment]
It is a lint rule, not a compilation error, so it is a matter of a personal preference. It does not make sense to me and Playwright uses this pattern, so you should disable it for the folder that has Playwright tests.
