### ISSUE TITLE
[BUG] `page.pause` doesn't work when running from the vscode extension

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#17059]
**Context:**
- Playwright Version: 1.25.1
- Operating System: windows 10
- Node.js version: 16.11.1
- Visual Studio Code version: 1.70.1
- Playwright for VSCode extension version: 0.2.10
- Browser: all

**Code Snippet**
```ts
test('asdf', async ({ page }) => {
    await page.goto('https://google.com')
    await page.pause()
})
```

**Describe the bug**

`page.pause` does not open the inspector when running tests with the vscode extension.

when clicking "Debug Test", it doesn't pause at all

when clicking "Run Test". it pauses on `page.pause`, but since there's no inspector there's no way to resume:

![image](https://user-images.githubusercontent.com/57028336/188255327-abd7a299-660e-4108-b5ac-3da0faa945e5.png)

**Comment by pavelfeldman** [comment]
We allow one debugger at a time, when using VS Code, you should use regular JS debugger w/ debugger; statement and breakpoints instead!
