### ISSUE TITLE
[Question]is it possible to watch when a element with selector is showing?

### ISSUE THREAD

**Issue by coader** [microsoft/playwright#17068]
just like:
page.on('show', 'selector',()=>{
})

otherwise, I have to detect it again and again, it's unacceptable.

**Comment by coader** [comment]
or always detect it in another thread? and how to do this?

**Comment by dgozman** [comment]
@coader Could you please explain what are you trying to achieve? There might be a solution for you already.

**Comment by coader** [comment]
for example, sometimes, page will show element likes "are u accept cookie", and it's not browser dialog by alert/confirm, it's appears random, so we need some function to auto click it.

**Comment by dgozman** [comment]
@coader There is no solution if your page is deterministic. However, the following snippet might work most of the time:

```js
test('my test', async ({ page }) => {
  // Set up a click on "Accept all cookies" when it appears.
  // Note no await and a catch, for the case it does not appear.
  page.locator('text=Accept all cookies').click().catch(() => {});

  // Proceed with the test.
  await page.locator('text=Click me').click();
  // ....
});
```
