### ISSUE TITLE
[BUG] "Pick selector", "Record" buttons don't work in debug mode when "Show browser" is off

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#17060]
**Context:**
- Playwright Version: 1.25.1
- Operating System: windows 10
- Node.js version: 16.11.1
- Visual Studio Code version: 1.70.1
- Playwright for VSCode extension version: 0.2.10
- Browser: all

**Code Snippet**

```ts
test('asdf', async ({ page }) => {
    await page.goto('https://google.com')
    await page.pause() // breakpoint here because of https://github.com/microsoft/playwright/issues/17059
})
```

**Describe the bug**

when the "Show browser" option is off and running in debug mode (which shows the browser regardless), the "Pick selector" and Record buttons don't do anything

if these buttons aren't supposed to work when "Show browser" is off, they should be hidden or disabled when it's off

**Comment by pavelfeldman** [comment]
Fixes

**Comment by DetachHead** [comment]
@pavelfeldman the "Pick locator" button is still enabled when "Show browser" is disabled even though it doesn't work

![image](https://user-images.githubusercontent.com/57028336/206942307-62f65eb3-417f-4adc-ab31-6dff7c3c6389.png)

playwright v1.28.1, extension v1.0.1
