### ISSUE TITLE
[Feature] DOM snapshot & comparison

### ISSUE THREAD

**Issue by Sheraff** [microsoft/playwright#17063]
An old classic of automated testing is comparing a piece of the DOM. One could argue that it's now deprecated in favor of visual comparisons by screenshots, or "interaction testing" where we simulate some actions and check the resulting state. But there seems to still be cases where neither is appropriate.

## Example use case
- Say we have a page where we need to make sure the `<meta>` tags remain correct after each build.
- The dev team doesn't really understand or care about these `<meta>` tags, but the SEO team analyzed a build and approved them.
- => from this point on, all we need to test, is that these tags don't change from one build to the next unless the change was intentional.

As far as I can tell, Playwright doesn't provide any tool for validating this, **unless each `<meta>` tag is individually selected by its own locator, and each attribute is tested `.toBe` a known value.**

## A simple *user-land* solution
A naive solution to this problem would be to simply stringify the DOM that is known to be correct and then test for any changes to the resulting string. This comes with a few issues:
- If the stringified DOM is generated manually, the expected values become hardcoded and changing the string will require strict process so that it's always generated the same way the "locator stringifier" function does it (line returns, escapes, spaces...).
- If the stringified DOM is generated automatically, the code needed to generate a "snapshot" quickly becomes very much an exercise in *replicating playwright internals* (combining `testInfo` pieces to generate a file name, different execution path based on the value of `updateSnapshots`, throwing a relevant "fail" message when necessary)

In addition to that, it can fail in cases that should pass. For example, as far as the browsers are concerned, `<meta name="foo" content="bar">` is equivalent to `<meta content="bar" name="foo">`. But when comparing strings, this will fail.

## A complex *user-land* solution
Because of this need, and because the native `isEqualNode` function was exactly made for DOM node comparisons, I had to write a pretty complex piece of code, that is still probably full of holes and not very performant:

- first, it needs a bit more arguments than most "playwright native" test functions
```ts
async function matchDOMSnapshot(
  page: Page,
  uid: string, // any string that will identify one specific test to avoid collisions
  tags: Locator,
  testInfo: TestInfo,
) {
```
- then it tries to replicate playwright's logic for "where to store a snapshot"
```ts
  const [, ...testLocation] = testInfo.titlePath
  const testLocationString = testLocation.map(id => id.replace(/[\/\s]/g, '-')).join('-')
  const browser = testInfo.project.name
  const environment = testInfo.snapshotSuffix
  const fileName = `${testLocationString}-${uid}-${browser}-${environment}.txt`
  const snapshotFileName = join(testInfo.snapshotDir, fileName)
```
- after that it needs to do some trivial nodejs stuff that is also probably already implemented in playwright in a more robust way
```ts
  try {
    await access(dirname(snapshotFileName), constants.F_OK)
  } catch (error) {
    if (error && error.code === 'ENOENT') {
      // known error, just create the directory
      await mkdir(dirname(snapshotFileName), { recursive: true })
    } else {
      // unknown error
      throw error
    }
  }

  let storedDomStrings: string[] | null = null
  try {
    const data = await readFile(snapshotFileName, { encoding: 'utf-8' })
    storedDomStrings = JSON.parse(data)
  } catch {} // swallow errors, this just means the file doesn't exist, this is the first snapshot
```
- then stringifies the locator, which is the first bit of code that doesn't seem to be just boilerplate
```ts
  const locatorAsString = (
    await tags.evaluateAll(tags => {
      return tags.map(tag => tag.outerHTML)
    })
  ).map(cleanupURLFromString) // this is custom to my project, but a general solution might be possible with info from playwright.config, or even just a `sanitize(s: string) => string` callback as an argument for the test
```
- then has to determine which "execution path" to take (take a snapshot or compare with existing one), which is again trying to replicate "internal playwright behavior"
```ts
  const shouldMatchExisting =
    storedDomStrings !== null
    && testInfo.config.updateSnapshots !== 'all'
  const shouldWriteComputed =
    testInfo.config.updateSnapshots === 'all' ||
    (storedDomStrings === null && testInfo.config.updateSnapshots === 'missing')
```
- then it goes a bit "hacky" by taking advantage of the browsers playwright provides to call `isEqualNode`. In this case, it will *pass* even if the nodes in the locator are in an order different from the "stored nodes" from a previous snapshot (i.e. `<a/><b/>` will match `<b/><a/>`) but that could just be a parameter of the test function (`{order: 'strict' | 'any'}`).
```ts
  if (shouldMatchExisting) {
    for (const itemString of locatorAsString) {
      const foundIndex = await page.evaluate<number>(`
		  const locatorTemplate = document.createElement('template');
		  locatorTemplate.innerHTML = \`${itemString}\`;
  
		  const storedStrings = [\`${storedDomStrings.join('`,`')}\`]
		  storedStrings.findIndex(string => {
			const template = document.createElement('template');
			template.innerHTML = string;
			return template.content.isEqualNode(locatorTemplate.content)
		  })
		`)
      if (foundIndex !== -1) continue

      expect(storedDomStrings).toContain(itemString) // This is not a very good fail message
    }
  }
```
- and finally, it writes the snapshot for next time. Which is trivial, but still something playwright has already implemented.
```ts
  if (shouldWriteComputed) {
    await writeFile(snapshotFileName, JSON.stringify(locatorAsString), { flag: 'w' })
  }
}
```

> WARNING to anyone taking this as an example, this specific "solution" has a few known issues:
> - if the stringified DOM contains a backtick `` ` ``, it will fail
> - the order of elements within the locator is not taken into account, `<a/><b/>` will match `<b/><a/>`
> - it is not very performant as it's re-parsing the stored snapshot for every locator when it could use a JSHandle instead
> - there is a slight chance it could interfere with / be disturbed by the page's actual code
> - it does not print an easy to understand fail message
> - it does not notify in console when "writing the actual" snapshot
> - it uses `outerHTML` to stringify, `innerHTML` to turn back into a node, and `isEqualNode` to compare nodes so if any of these has peculiarities, they will be present here too

## A *pure-playwright* solution
If this functionality were to be provided by playwright, we could imagine a much simpler DX that could look something like this:
```ts
expect(locator).toHaveDOMSnapshot({
  // whether `<a/><b/>` should match `<b/><a/>`
  order?: 'strict' | 'any',
  // allow user to strip parts of the string susceptible to change (base URL in absolute paths, random hashes in classnames or filenames, ...)
  sanitize?: (html: string) => string,
  // whether `<parent><child/></parent>` should match `<parent/>`
  shallow?: boolean
})
```

## A *partial* playwright solution (give access to internal functions)
If the use-case presented above seems too specific and/or the playwright team would prefer to discourage DOM snapshots, another way to make playwright more useful would be to expose some of the internal functions. In this specific case, exposing an agnostic `.toMatchArbitrarySnapshot()` could handle the following:
- picking an appropriate file name
- storing / retrieving the file content
- picking whether to write a new snapshot or compare to an existing one
- displaying a good fail message

Which would take this entire example down to a few lines of code. We might imagine the DX to be something like
```ts
expect(Locator | Page).toMatchArbitrarySnapshot<T extends Locator | Page, U extends string | Buffer>({
  capture: (input: T) => U | Promise<U>,
  compare?: (stored: U, current: U) => boolean | Promise<boolean>,
})
```

**Comment by Sheraff** [comment]
Related issue: https://github.com/microsoft/playwright/issues/8113

**Comment by dgozman** [comment]
@Sheraff Thank you for the great issue! I will leave it open for prioritization as a feature request.

If you are fine to forgive the attributes order issue, "a simple user-land solution" could be pretty small:

```js
// Make sure that page has already loaded. That's usually not an issue for the meta tags.
// Alternatively, wrap everything with expect.poll if things are dynamic.

const locator = page.locator('meta');
const snapshot = await locator.evaluateAll(elements => {
  return elements.map(e => e.outerHTML).sort();
});
expect(snapshot).toMatchSnapshot('meta-tags.html');
```

**Comment by eric-burel** [comment]
@dgozman Is it expected to work already? In which case it could be just a documentation issue, as the docs show only the .png use case.
I don't necessarily expect HTML snapshotting to be a built-in feature, but being able to customize the snapshot logic to whatever we feel relevant seems very useful

**Comment by dgozman** [comment]
> I currently hit: TypeError: The "buf2" argument must be an instance of Buffer or Uint8Array. Received an instance of Array

You are right, passing an array is not supported, see feature request in #13545. For this example to work properly, we'll need `JSON.stringify(array)` or something like that, because `toMatchSnapshot()` supports strings and buffers.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
