### ISSUE TITLE
[BUG]No Test Found

### ISSUE THREAD

**Issue by w5pand** [microsoft/playwright#17067]
**Context:**
- Playwright Version: [v1.25.1]
- Operating System: [windows10 ]
- Node.js version: [v16.17.0]
- Npm version:[v8.15.0]
- Visual Studio Code version: [v1.71.0 (user setup)]
- Playwright for VSCode extension version: [v0.2.10]
- Browser: [chrome 104.0.5112.102]
- Extra: [ I use fnm to manage node. (fnm v1.31.1)]

**Code Snippet**

![1662259435045](https://user-images.githubusercontent.com/1818498/188294803-abc717e2-925b-4bdf-8b33-a5e128f0b23b.png)

**Describe the bug**

No tests are found.

**Comment by dgozman** [comment]
@w5pand Could you please provide a repro that we can try locally? Otherwise it is impossible to help you.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by natsuki-engr** [comment]
in my case, same problem is resolved by writing
```
fnm env --use-on-cd --shell fish | source
```
in `~/.config/fish/config.fish` instead of `~/.config/fish/conf.d/fnm.fish`
