### ISSUE TITLE
[Question] SSO in playwright 

### ISSUE THREAD

**Issue by jacobmesu** [microsoft/playwright#1707]
I'm looking at playwright to replace puppeteer. We use puppeteer at this moment to run our functional tests. In puppeteer I use the following arguments when starting chromium. 
         '--auth-negotiate-delegate-whitelist=\*.afasgroep.nl',
         '--auth-server-whitelist=\*.afasgroep.nl',
With these arguments I can automatically login with SSO. I use the same arguments in Playwright, but it's not working. 
I'm working on a Mac and I'm certain there is a kerberos ticket. Does playwright handle the runtime args different from puppeteer? Any idea how I can fix this?

**Comment by pavelfeldman** [comment]
It should behave the same way parameter-wise. I don't see the `--auth-negotiate-delegate-whitelist` flag in Chromium, but `--auth-server-whitelist` is there. If you run your app as

```
DEBUG=*browser* node app.js
```

it'll print the command line that it uses to start Chromium. You can experiment with it locally and see what's going on. Another potential reason is that we are using newer Chromium in Playwright and something changed in the browser. All in all, if you share more about your setup we could help!

**Comment by jacobmesu** [comment]
@pavelfeldman thanks for your reply. Appreciate it! Some additional info:

1. The parameters are passed on to Chromium. 
2. The single sign on is working when I use the method launchPersistentContext.
3. The only noticable difference between the commandlines is the user-data-dir parameter when launching without a persistent context.
4. It's probably related to the way contexts are handled? Could be related to #852? 

Let's say I continue running with the persistent context, is it safe to run multiple instances so I can test in parallel?

With a persistent context
```
  pw:browser:proc:[1] <launching> /Users/jms/Projects/Test/development/runner/node_modules/playwright/.local-browsers/chromium/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=./tmp/test-user-data-dir --remote-debugging-pipe --auth-negotiate-delegate-whitelist=*.afasgroep.nl --auth-server-whitelist=*.afasgroep.nl about:blank +0ms
```

Without

```
  pw:browser:proc:[1] <launching> /Users/jms/Projects/Test/development/runner/node_modules/playwright/.local-browsers/chromium/chrome-mac/Chromium.app/Contents/MacOS/Chromium --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/var/folders/hq/nfxht5bn1_x__2mpgs__1g6h2ynvp3/T/playwright_dev_profile-pPZ4Q6 --remote-debugging-pipe --auth-negotiate-delegate-whitelist=*.afasgroep.nl --auth-server-whitelist=*.afasgroep.nl --no-startup-window +0ms
```

**Comment by jacobmesu** [comment]
I decided to change my approach and push an enterprisepolicy via the managed preferences of chromium. The settings are now visible in the chrome://policy page, but they don't seem to have effect while browsing in incognito in Chromium. They do however work in Chrome in incognito mode or in Puppeteer in incognito context.

**Comment by jacobmesu** [comment]
This is by design (https://bugs.chromium.org/p/chromium/issues/detail?id=458369). NTLM is by default disabled in newer version of Chromium in incognito mode. You need to set the policy ​Ambient​Authentication​In​Private​Modes​Enabled to 1 or higher. (https://cloud.google.com/docs/chrome-enterprise/policies/?policy=AmbientAuthenticationInPrivateModesEnabled).
