### ISSUE TITLE
Timeout in the secondwindow although I can see the Window is open for an Electron Application[BUG]

### ISSUE THREAD

**Issue by shastrisubramaniam** [microsoft/playwright#17077]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [Mac]
- Node.js version: [16.17
- Browser: [Chromium]
- Extra: [any specific details about your environment]

Hi,

I am using Playwright to automate an Electron Application. So I was able to go to the second window, but it times out and the test never passes.

See below 👍 

 electronApplication.waitForEvent: Timeout 30000ms exceeded while waiting for event "window"

      18 |     expect(buttontext).toBeVisible;
      19 |     const[secondwindow] = await Promise.all([
    > 20 |       electronApp.waitForEvent('window'),
         |                   ^
      21 |       mainPage.click('[aria-labelledby="_ojcustomelem7|text"]'),
      22 |     ]);
      23 |     console.debug((await secondwindow.title()).toString);

**Comment by dgozman** [comment]
@shastrisubramaniam Could you please provide a repro that we can run locally? Otherwise it is impossible to help you.

**Comment by shastrisubramaniam** [comment]
So it appears that the application actually does not use multiple windows,
but uses IPCRenderer to publish content on the fly. So, I need to figure
out a way to wait for rendering to have completed.

If you have any suggestions around that, it would help. If not, I will try
and figure it out and you can close this issue out.

Thanks !

**Comment by dgozman** [comment]
@shastrisubramaniam We usually suggest to wait for something particular on the page. For example, `await expect(page.locator('text=Shows last')).toBeVisible()`.
