### ISSUE TITLE
[BUG] page.route in debug mode makes my app not interactable.

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#17078]
**Describe the bug**

I'm following up on this issue: https://github.com/microsoft/playwright/issues/16992

While it **does** explain to me why it happens, it doesn't provide a solution or a workaround? Running the test on debug mode directly with the CLI is working just fine. Can I do anything in order to make it work with the extension execution?

**Comment by dgozman** [comment]
@baptisteArno This is a nature of a single-threaded JavaScript, you cannot work around that. If you want your `route` code to run, your test must not be paused on a breakpoint. I'd suggest to use other debugging tools that don't actually pause the script like `page.pause()` or `--debug`. Sorry for the inconvenience!
