### ISSUE TITLE
Handle Window popup with in Popup java

### ISSUE THREAD

**Issue by predil** [microsoft/playwright#17083]
I have a requirement that my main page has link and after a click on that link popup new window, and in that window has link and when I click on that link will pop up another new window. and need to enter value there. How to handle this in playwright.
I tried the below code and it didn't work.
`Page ePagePopup= BaseTest.page.waitForPopup(() -> {
				adapterRouteDetailPage.editRuleBtnClick();
			});

ePagePopup.waitForLoadState();
				Page tPagePopup= BaseTest.page.waitForPopup(() -> {
				ePagePopup.translationLink.click();// new window getting open
			});	
			//not comes to here.
tPagePopup.waitForLoadState()`

**Comment by mxschmitt** [comment]
Just to confirm, do you mean with popup a target=_blank window which gets opened? Then your solution would be correct, see [here](https://playwright.dev/java/docs/pages#handling-popups).

**Comment by predil** [comment]
> Just to confirm, do you mean with popup a target=_blank window which gets opened? Then your solution would be correct, see [here](https://playwright.dev/java/docs/pages#handling-popups).
Hi mxschmitt,
No it's not target="_blank" link. it's a new popup window(Lookup) .First popup window is handling successfully. 2nd window is opening with above code but after that throwing 
com.microsoft.playwright.TimeoutError: Timeout 40000ms exceeded.

Main page  click link1-> opens new popup window(not new tab)  click on link2 -> opens new popup window (not new tab)

**Comment by yury-s** [comment]
You need to listen for the popup event in the page which opens it (i.e. the page where you click second time). I believe this should work:

```java
Page tPagePopup= ePagePopup.waitForPopup(() -> {
    ePagePopup.translationLink.click();// new window getting open
});
```

**Comment by dgozman** [comment]
Closing per above. Please open a new issue and link to this one if the solution above does not work.
