### ISSUE TITLE
[Question] Return only the text after span

### ISSUE THREAD

**Issue by gegoncalves** [microsoft/playwright#17087]
I am struggling with the following problem:

I want to save the **_Company administrator_** text in a variable to compare later. However, it is out of the span and I am trying to take only this part

````html
<li><span class="pillow__label">Permission</span>
    Company administrator
</li>
````

I tried:
```javascript
const permission = await page.locator('li', { hasText: 'Permission'}).textContent()
// Tried also using this but also returns everything:
const permission = await page.locator('//li[5]//span[contains(@class,“pillow__label”)]').textContent()
````
but it always return the "Permission Company administrator"

I know that I can use `.replace()`, `.slice()` `.toContain()`and others to deal with it but I dont want to have it hardcoded.
Is there any better way that I am missing?

**Comment by ltsuda** [comment]
Did you try `.innerText()` function? Maybe with the first code with the `hasText` you posted?
https://playwright.dev/docs/api/class-locator#locator-inner-text

**Comment by gegoncalves** [comment]
Hi @ltsuda > It also returns the full text inside of the it. :(

**Comment by dgozman** [comment]
@gegoncalves Unfortunately, there is no API for this. You should either change the page to wrap this text in a span, or get `textContent()` from both `li` and `span. pillow__label ` and subtract one from the other.
