### ISSUE TITLE
[REGRESSION]: Can't mock CORS request since 1.17.0

### ISSUE THREAD

**Issue by ElVisPL** [microsoft/playwright#17081]
**Context:**
- GOOD Playwright Version: 1.16.3
- BAD Playwright Version: 1.17.0
- Operating System: Ubuntu 20.04

**Describe the bug**
When I mock CORS request (by setting headers when using `route.fulfill` function) on playwright 1.16.3, we have as expected OPTIONS request first and then PUT request:
![2022-09-05_08-06](https://user-images.githubusercontent.com/3405010/188379453-484777cc-98f5-4d07-828f-37fc6f93bd4d.png)

But on playwright 1.17.0:
![2022-09-05_08-10](https://user-images.githubusercontent.com/3405010/188379857-77fe3c5e-6130-43ca-b311-90f67c47d633.png)
As you can see for some reason PUT request is fired before OPTIONS and it's pending (waiting for OPTIONS request that should start before?)

After 2 minutes PUT request is cancelled (so the mock fails)
![2022-09-05_08-13](https://user-images.githubusercontent.com/3405010/188380341-72ce2c0d-5575-4911-898f-f51a5edd9a76.png)

Not sure it is Playwright problem or Chromium, but the only thing I'm changing here is the playwright version

**Comment by dgozman** [comment]
@ElVisPL Could you please provide a repro that we can run locally?

**Comment by ElVisPL** [comment]
@dgozman Unfortunately I couldn't reproduce on some basic example. 

Maybe that's not actually playwright issue... Weird thing is that it happens only for playwright >= 1.17.
I will try to investigate this further, no idea why it happens.

**Comment by mxschmitt** [comment]
Any updates? Otherwise we'd have to close it unfortunately, but you can re-file one if you have a repro.

**Comment by ElVisPL** [comment]
I think it can be closed. I'll get back when I'm able to create a repro.
