### ISSUE TITLE
[Feature] Allow reconnecting to page in a separate processes

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#1709]
Use Case: I need to connect to an existing page created in another process to create an end-to-end test.

The way I do this right now is by using `launchServer` in the first process and sending the `wsEndpoint` and `page._delegate._targetId` to the second process. Then I create a `WebSocket` manually in the second process that uses `Target.attachToTarget` to connect to the page.

Feature Request:

1. Expose page.targetId()
2. Allow passing targetId to browser.newBrowserCDPSession(targetId?: string);

Proposed Usage:

Process A.
```
const server = await playwright.chromium.launchServer();

const browser = await playwright.chromium.connect({
  wsEndpoint: server.wsEndpoint(),
});

const context = await browser.newContext();
const page = await context.newPage();

sendToProcessB({ 
  targetId: page.targetId(),
  wsEndpoint,
})
```

Process B.

```
const { targetId, wsEndpoint } = receiveFromProcessA();

const browser = await playwright.chromium.connect({ wsEndpoint });

const session = await browser.newBrowserCDPSession(targetId);
```

**Comment by jperl** [comment]
Alternative approach:

It would be great if browsers connected to the same server wsEndpoint were aware of the same contexts and pages.

```
const server = await playwright.chromium.launchServer();

const browser = await playwright.chromium.connect({
  wsEndpoint: server.wsEndpoint(),
});
await browser.newContext();

const browserTwo = await playwright.chromium.connect({
  wsEndpoint: server.wsEndpoint(),
});

expect(browserTwo.contexts().length).toEqual(1);
```

**Comment by pavelfeldman** [comment]
Hm! We were explicitly isolating the context, but I don't think we were thinking about your use case. Could you share why you need to reuse context from multiple places in your end2end test?

**Comment by jperl** [comment]
This is definitely an edge-case, but it is an end-to-end test for `npx qawolf create`. 

So I need to [simulate browser actions](https://github.com/qawolf/qawolf/blob/85dea765f8c31abe2250fe80c751b77945049892/test/cli/create.e2e.test.ts#L56-L70 in a spawned child process and check it generates code.

**Comment by kababoom** [comment]
New to playwright, thank you for your time and effort creating this......

I'm also looking for a way to reconnect to a previously created session to cover my end-to-end testcases.

- StartServer.js
- Openpage.js   page.goto-> evaluate element -> fill username/password -> take screenshot
- Login.js click button -> check for element -> take screenshot.js
etc...

So Login.js should continue with previously created Openpage.js session.

This would be the only way to integrate playwrite inside our existing framework and I'm not able to get this to work (yet).

**Comment by pavelfeldman** [comment]
@kababoom I think you are talking about https://github.com/microsoft/playwright/issues/1745. I'm closing the session reconnect aspect for now.
