### ISSUE TITLE
[Question] Using Playwright on Android

### ISSUE THREAD

**Issue by DTrombett** [microsoft/playwright#17116]
I'm interested in using Playwright directly on Android using the terminal emulator Termux. I've seen in another issue that is possible to do this when connected via adb but I'm looking for a way to use it **without** a PC. I tried and successfully installed but I receive the "unsupported platform" error when running any script.
So my question is: is it possible to run playwright on Android without using a PC? If so, how? And, if not, is this planned or we should just use it through adb?

**Comment by dgozman** [comment]
@DTrombett This scenario is not supported currently, and I am not sure it will ever be supported. Could you please explain the reason for such a usecase?

**Comment by DTrombett** [comment]
Well, any use case actually. For example, running tests or scripts on a mobile device without needing a PC.
I know it isn't something straightforward to implement, I was just surprised it is supported through adb but not natively.
However, if it isn't something planned or that Playwright probably won't support at all, not such a big problem 😅

**Comment by dgozman** [comment]
@DTrombett Thank you for more information. I don't think we'll be prioritizing this usecase, so I'll close the issue. Sorry for the inconvenience.

**Comment by Jobians** [comment]
It 100% possible with some patch

**Comment by Jobians** [comment]
Solution 

https://github.com/Jobians/playwright-termux
