### ISSUE TITLE
[Feature] Access DOM elements in infinite scrolling Page

### ISSUE THREAD

**Issue by naveensabares92** [microsoft/playwright#17121]
So, our app pages have been performance tweaked  & infinite scrolling has been implemented in the FE. 
PW is able to locate the element only when it’s active in the DOM, which means I have to scroll a bit so that it can load.
`locator.scrollIntoViewIfNeeded()` did not work for this. So, I have written something custom to scroll and verify if the element is available!

And If we need to use `page.mouse.wheel` to scroll, it requires the coordinates of the desired element!

Custom Code- 
```
async scrollUntilElementIsVisible(page, selector) {
        while (!(await selector.isVisible())) {
            await page.mouse.wheel(0, 600);
        }
    }
```

It would be great if we can have a native function that can handle elements in such pages! Something that other tools do not support.

[Slack Discussion](https://playwright.slack.com/archives/CSUHZPVLM/p1662386776427269)

**Comment by dgozman** [comment]
@naveensabares92 Your snippet looks great! I am not sure we'll come with an API that is more convenient than your snippet. Do you have a particular API proposal in mind?

**Comment by dgozman** [comment]
Closing per above. If you have any good ideas for the API, please file a new issue and link to this one.

**Comment by naveensabares92** [comment]
@dgozman  - Apologies for the delay. Honestly, I do not have an idea on top of my mind. If you can come up with something that can be handled by the playwright in a native manner, It would be great.
