### ISSUE TITLE
[Question] Problem with sending multi-part request

### ISSUE THREAD

**Issue by lukcaster** [microsoft/playwright#17126]
Hello,

Sorry for opening new thread, i have tried to resolve my problem using comments in issue `16806` but to no avail.

I am trying to send a form-data request with 2 separate files as per attached screenshot 
![obraz](https://user-images.githubusercontent.com/56275839/188651490-0e08044e-5cb8-4c6c-a497-530f15b6de2f.png)

I have added both files into the same folder as the test
![obraz](https://user-images.githubusercontent.com/56275839/188651932-3452b5c7-1f67-43b8-9c46-7e2d312b2fde.png)

I have tried several different routes to solve the problem, this is my latest try 
```
 var request = await request.post(url, {
      headers: {
        "Authorization": "Bearer " + machineToken.token,
        "Content-Type": "multipart/form-data"
      },
      multipart: {
        "file": {
          name: "photo",
          mimeType: "image/jpg",
          buffer: image
        },
        "metadata": {
          name: "fail",
          mimeType: "application/json",
          buffer: text
        }
      }
    })
```
I am getting this error 

```
ReferenceError: image is not defined

      155 |           name: "photo",
      156 |           mimeType: "image/jpg",
    > 157 |           buffer: image
          |                   ^
```

Could you please advise?

**Comment by dgozman** [comment]
Let me know whether the following works for you.

```js
import fs from 'fs';
import path from 'path';

test('my test', async ({ request }) => {

    await request.post(url, {
      headers: {
        "Authorization": "Bearer " + machineToken.token,
        "Content-Type": "multipart/form-data"
      },
      multipart: {
        "file": fs.createReadStream(path.join(__dirname, 'photo.jpg')),
        "metadata": fs.createReadStream(path.join(__dirname, 'fail.json')),
      }
    })

});
```

**Comment by lukcaster** [comment]
It now shows a different error, that the file is not present in the request 

```
 "type" : "https://www.jhipster.tech/problem/problem-with-message",
  "title" : "Bad Request",
  "status" : 400,
  "detail" : "Required request part 'file' is not present",
```

**Comment by lukcaster** [comment]
Not really sure if i can share that easily as the project is not fully published and would be hard to connect to. 
I am not on my working pc right now, could you advise how would form data request look like?

**Comment by dgozman** [comment]
@lukcaster I looked at this once again, and most likely need the multipart. Sorry for the confusion. I am not sure how to help better without a repro.

**Comment by lukcaster** [comment]
@dgozman thank you for trying. Could I please ask one more thing? In playwright documentanion there is also another way of adding files, similair to the one i have tried to use in the first post. Was this done correctly?

**Comment by dgozman** [comment]
> @dgozman thank you for trying. Could I please ask one more thing? In playwright documentanion there is also another way of adding files, similair to the one i have tried to use in the first post. Was this done correctly?

Could you share a link to that documentation please?

**Comment by lukcaster** [comment]
https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post-option-multipart

**Comment by dgozman** [comment]
@lukcaster Yes, that is also a right way. You just have to actually pass the content.
```js
buffer: image
```
Replace the above with:
```js
buffer: fs.readFileSync(path.join(__dirname, 'photo.jpg'))
```

**Comment by lukcaster** [comment]
Well it still does not work I am afraid, I have copied Request Headers from Postman console, not sure this can help

```
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiI5ODY2NDg3IiwiYXV0aCI6IlJPTEVfTUFDSElORSIsImF1ZCI6Ik1BQ0hJTkUiLCJpYXQiOjE2NTIwODI0NzN9.HzgyaMoUx7PeibmMCqEh6cnHbY-6oR6bqxK7guFE0R7a-UNZrLtHC-1sCAeokNY5MAc3QrbKi6dn7OP2P9iuOw
User-Agent: PostmanRuntime/7.29.2
Accept: */*
Postman-Token: 4ec9f356-0faf-4def-9108-0329addcb490
Host: localhost:8080
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Type: multipart/form-data; boundary=--------------------------424048325158766317230827
Content-Length: 2016955
```
It shows that this is multipart/form-data?
Not sure if you have any more ideas, thank you for trying anyway.

**Comment by dgozman** [comment]
@lukcaster Sorry, no other ideas. If you could share a repro, we'll be able to take a look/debug.

**Comment by dgozman** [comment]
Closing as per above. If you come up with a repro we can run locally, please open a new issue and link to this one.

**Comment by lukcaster** [comment]
@dgozman hello, just wanted to updated this thread cause the request actually works right now, the funny part is that i have just removed quotes from the field names... 

```
multipart: {
         file: {
          name: "photo",
          mimeType: "image/jpg",
          buffer: fs.readFileSync(pathTest.join(__dirname, 'photo.jpg'))
        },
        metadata: fs.createReadStream(pathTest.join(__dirname, 'fail.json')),        
      }
```

Sorry if this opens the thread again, maybe this will be helpfull to someone struggling with sending multipart post requests. Thanks again for the provided support.
