### ISSUE TITLE
[BUG] - extension not enabling, blank screen visible

### ISSUE THREAD

**Issue by ChaosEngine** [microsoft/playwright#17135]
**Context:**
- Playwright Version: 1.25.1
- Operating System: Windows10
- Node.js version: v16.15.1
- Visual Studio Code version: 1.71.0
- Playwright for VSCode extension version: v0.2.10
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**
start VSCode, wait 5-10 sec. Playwright extension is not enabling, seeing blank screen

![image](https://user-images.githubusercontent.com/1271428/188697158-29bec6b1-4dc6-42f1-98a4-8863ba1593a3.png)

**Comment by dgozman** [comment]
@ChaosEngine Could you please share a repro that we can take a look at? Otherwise it is impossible to help you.

**Comment by ChaosEngine** [comment]
Yup, not much in dev tools. Not really having an achor here :-)
https://user-images.githubusercontent.com/1271428/188943298-b10306b5-597a-4279-972e-0916906ec02c.mp4

**Comment by dgozman** [comment]
@ChaosEngine Thank you for the repro! Everything works as expected for me. Did you run `npm install`? Here is what I did and it gives me `InkBall.spec.js` in the test explorer.

```bash
git clone https://github.com/ChaosEngine/Dotnet-Playground.git
cd Dotnet-Playground/
git checkout playwright
cd DotnetPlayground.Web/
npm install
cd ..
code .
```

**Comment by ChaosEngine** [comment]
> @ChaosEngine Thank you for the repro! Everything works as expected for me. Did you run `npm install`? Here is what I did and it gives me `InkBall.spec.js` in the test explorer.
> 
> ```shell
> git clone https://github.com/ChaosEngine/Dotnet-Playground.git
> cd Dotnet-Playground/
> git checkout playwright
> cd DotnetPlayground.Web/
> npm install
> cd ..
> code .
> ```

Achhaa!!!!
I did that but on `playwright` branch. But earlier I switched to `dev` branch where there is **no** `playwright.config.js` or **no entry** in package.json for playwright.

So is it mandatory to have run `npm install` for extension to work? Is it specified  anywhere in docs or extension welcome screen? Coz without it I was mislead that something is broken. I get it one could not work without other but still.
I think this issuer can be closed after that.

**Comment by dgozman** [comment]
> So is it mandatory to have run `npm install`

Yes, it is required. We'll see about adding that to the docs somewhere.
