### ISSUE TITLE
[Question] - Is there any way to simulate api 500 error?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#17141]
I have a scenario whenever api response is 500, display some error message to the user. Is there any way to simulate this scenario using playwright?

**Comment by dgozman** [comment]
Take a look at [this doc](https://playwright.dev/docs/network#handle-requests). You would need to pass `status: 500`.

**Comment by gauravgandhi1315** [comment]
@dgozman thank you! I will try this.

**Comment by gauravgandhi1315** [comment]
@dgozman It works for me. Thanks for your help!
