### ISSUE TITLE
[Question] Do multiple BrowserContexts have isolated SharedWorkers in playwright/test?

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#17146]
We have some [sharedworker](https://developer.mozilla.org/en-US/docs/Web/API/SharedWorker) functionality which we're trying to test with playwright. We specifically need to have two totally separate sharedworkers making updates to our application as if they were separate browser installs.

When BrowserContexts are created with context.newPage() do they get their own shared worker?
Is there a way to create a totally separate browser instance with `playwright/test`?

Here is the code snippet with `context.newPage()`
```js
test.describe('Shared Worker Update Test', () => {
    test('A fresh notebook entry entered by UserA will appear for UserB within 60 seconds', async ({ context, page }) => {

        await page.goto('./', { waitUntil: 'networkidle' });
        
        // Create Notebook
        const notebookObject = await createDomainObjectWithDefaults(page, {
            type: 'Notebook',
            name: "Test Notebook"
        });

        const page2 = await context.newPage();

        await page2.goto(notebookObject.url, {waitUntil: 'networkidle'});

        await expect(page.locator('text=AAA')).not.toBeVisible();
        //Enter AAA into notebook entry
        await enterTextEntry(page);
        await expect(page.locator('text=AAA')).toBeVisible();
        await expect(page2.locator('text=AAA')).toBeVisible();
    });
});
```

**Comment by dgozman** [comment]
@unlikelyzero In your snippet, you create two pages in the same context, so they are not isolated. Instead, you need two separate contexts:

```js
test.describe('Shared Worker Update Test', () => {
    test('A fresh notebook entry entered by UserA will appear for UserB within 60 seconds', async ({ browser, page }) => {
       const context2 = await browser.newContext();
       const page2 = await context2.newPage();

       // Use page and page2
    });
});
```

**Comment by unlikelyzero** [comment]
For those of you who find this issue in the future:

Browser.newContext() will create a separate shared worker.
context.newPage() will share the sharedworker.

I'm filing an RFE to add first class support
