### ISSUE TITLE
[BUG] Documentation bug: Parametrize tests

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#17143]
It looks like on the https://playwright.dev/docs/test-parameterize first code snippet should be put after the words `The first project runs with the value Alice and the second with the value Bob.` and other code snippets till `We can also use the option in a fixture` should be shifted accordingly.

**Comment by dgozman** [comment]
@e-oz Thank you for the issue! The doc looks correct to me - first the description, then the code block to illustrate it.

**Comment by e-oz** [comment]
Well... okay :)
![2702E19F-32B9-41EE-AA7E-79F70E431E09](https://user-images.githubusercontent.com/526352/188949887-461c3034-1a43-42aa-b1c7-6e875c95e19b.jpeg)
