### ISSUE TITLE
[Question] Use the global variable in the globalSetup function already

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#17144]
I have a question related to the running Playwright Test on the different environments. 
I did the following:
```Typescript
async function globalSetup(config: FullConfig) {
  if (process.env.testEnvironment) {
    dotenv.config({
      path: `.env.${process.env.testEnvironment}`,
      override: true,
    });
  }
  const baseURL = ENV.BASE_URL;
  await Promise.all([loginEU(baseURL), loginUS(baseURL)]);
}
```
ENV is a class containing the constants like process.env.BASE_URL
But my baseURL const var is not defined. How can I do it here? I need to call these login functions for both shops EU and US and they need the baseURL defined depending on the environment.
Everywhere else where I use the ENV.BASE_URL the variable is defined, except in this place ...
Can you please advise on how to approach this case?

**Comment by dgozman** [comment]
@mareru Unfortunately, I don't exactly understand the issue. Could you please share more code, for example for your `ENV`?

**Comment by mareru** [comment]
```
export default class ENV {
  public static BASE_URL = process.env.BASE_URL;
}
```
located in tests\utils\env.ts
The code from the previous comment is in ./gloabl-setup.ts file

**Comment by dgozman** [comment]
@mareru Thanks! The problem here is that you read `process.env.BASE_URL` in `ENV` before setting it up with `dotenv`, probably when you `require` your `ENV`. You should restructure the code so that `ENV` definition happens **after** your call `dotenv.config()`, or make `ENV` a function or something like that. Does that make sense?

Here is an example of making it a function:

```ts
export default class ENV {
  public static BASE_URL() { return process.env.BASE_URL; }
}
```

**Comment by mareru** [comment]
I solved it by using the `process.env.BASE_URL` directly in the global-setup.ts.  
I don't like it I cannot use my ENV class. I don't like to make it a function as well. Is there any other way to load that class after `deotenv.config()`

**Comment by dgozman** [comment]
@mareru No more suggestions, sorry!
