### ISSUE TITLE
[Question] Is there a global timeout for assertions?

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [microsoft/playwright#17154]
Currently assertions in PW timeout at 5000 milliseconds. This number is adjustable per assertion, but is there a way to set a global default timeout for assertions?

**Comment by ltsuda** [comment]
See if this helps

https://playwright.dev/docs/test-timeouts#set-expect-timeout-in-the-config

**Comment by halexiev-hedgeserv** [comment]
@ltsuda Thanks, that seems to be possible in typescript. I did not specify, but we are using Java and I could not find same config there...

**Comment by ltsuda** [comment]
I'm sorry, then :/

The only thing for Java I found is https://playwright.dev/java/docs/test-assertions#playwright-assertions-set-default-assertion-timeout

But as I don't know about Java or Playwright on Java, I don't know if this is only per file or where to put it.

**Comment by halexiev-hedgeserv** [comment]
@ltsuda Thank you, that seems to be exactly what I needed! Interestingly enough the method is present only in the docs, not in the actual class, but I'll open a bug for that :)

**Comment by ltsuda** [comment]
I'm glad that helps 👍
