### ISSUE TITLE
Handle Window popup(not a tab) with in Popup java 

### ISSUE THREAD

**Issue by predil** [microsoft/playwright#17150]
# https://github.com/microsoft/playwright/issues/17083

I have a requirement that my main page has link and after a click on that link popup new window, and in that window has link and when I click on that link will pop up another new window. and need to enter value there. How to handle this in playwright.
I tried the below code and it didn't work.
`Page ePagePopup= BaseTest.page.waitForPopup(() -> {
adapterRouteDetailPage.editRuleBtnClick();
});

ePagePopup.waitForLoadState();
Page tPagePopup= ePagePopup.waitForPopup(() -> {
ePagePopup.translationLink.click();// new window getting open
});
//not comes to here.
tPagePopup.waitForLoadState()`

**Comment by dgozman** [comment]
@predil When you say "popup (not a tab)" - what do you mean? Could you please share a repro, a screenshot, or something? Otherwise it is impossible to help you.

**Comment by dgozman** [comment]
@predil I think [this comment](https://github.com/microsoft/playwright/issues/17083#issuecomment-1238486301) answers your question. Could you please try that?

**Comment by predil** [comment]
> @predil I think [this comment](https://github.com/microsoft/playwright/issues/17083#issuecomment-1238486301) answers your question. Could you please try that?

Hi dgozman
Yeah I have tried it also as below code.
No success yet.
```
Page ePagePopup= BaseTest.page.waitForPopup(() -> {
adapterRouteDetailPage.editRuleBtnClick();
});

ePagePopup.waitForLoadState();
Page tPagePopup= ePagePopup.waitForPopup(() -> {
ePagePopup.translationLink.click();// new window getting open
});
//not comes to here.
tPagePopup.waitForLoadState()
```

**Comment by predil** [comment]
It's Worked.
Issue resolved.
