### ISSUE TITLE
[Question] What is the right Maven repo for the java version of Playwright?

### ISSUE THREAD

**Issue by halexiev-hedgeserv** [microsoft/playwright#17157]
Current version of Playwright as of this writing is 1.25.2. Yet latest version of Playwright in Maven central repo is 1.25.0 (https://mvnrepository.com/artifact/com.microsoft.playwright/playwright).

Is there an official repo to use or we just need to wait till the latest version appears in Maven central?

**Comment by dgozman** [comment]
@halexiev-hedgeserv Patch versions are different between Playwright languages. Playwright JavaScript is currently at 1.25.2, while Playwright Java is at 1.25.0. Your Maven central link is the right one.
