### ISSUE TITLE
[Question] How to keep the browser open in case of a failed assertion?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#17151]
When using `--debug`, I would expect that if an assertion fails, the browser stays open so I could inspect what went wrong.

Currently, @playwright/test closes the browser window immediately if there is an error and prints out a log int he terminal.

The latter is useful, but typically still requires to restart the entire test and put a `page.pause()` just before the failing test assertion.

**Comment by dgozman** [comment]
Merging into #10478.
