### ISSUE TITLE
[Question] Is it possible to take a screenshot at page.goto?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#17167]
My tests are failing in Jenkins at `page.goto()` Is it possible to take a screenshot at this line?

`await page.goto(baseURL)`

**Comment by dgozman** [comment]
@gauravgandhi1315 Take a look at [this doc](https://playwright.dev/docs/test-configuration#automatic-screenshots). Would that work for you?

**Comment by gauravgandhi1315** [comment]
@dgozman My `page.goto` is in `global-setup`. I think the link above will work only for `@test`

**Comment by dgozman** [comment]
@gauravgandhi1315 I see. The following snippet should work then:

```js
try {
  await page.goto(baseURL);
} catch (e) {
  await page.screenshot({ path: 'failed-global-setup.png' });
}
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
