### ISSUE TITLE
[Question] Does a route sniff redirects requests on page?

### ISSUE THREAD

**Issue by MsLolita** [microsoft/playwright#17161]
![image](https://user-images.githubusercontent.com/58307006/188912226-3ed1e046-05d5-4890-9547-8ac1be1033e1.png)
Second line in console should be with url https://oneboxtm.queue-it.net/?c=oneboxtm...

```
import os
from playwright.sync_api import sync_playwright

def handler(route):
    print(route.request.url)
    route.continue_()

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.route("**/*", handler)
    page.wait_for_timeout(5000)
    page.goto("https://proticketing.com/realmadrid_champions/en_US/entradas/evento/26218/session/1494284/select?viewCode=V_EstadioSantiagoBernabu")
    page.wait_for_timeout(20000000)
```

**Comment by dgozman** [comment]
@MsLolita `page.route()` does not intercept redirects, as [stated in the docs](https://playwright.dev/docs/api/class-page#page-route).

**Comment by MsLolita** [comment]
> 

And how I can do it?

**Comment by standbyoneself** [comment]
I also need to catch OIDC-provider redirect and fulfill it with response from request made with SSL certificate. Any workarounds?
