### ISSUE TITLE
[Question] Is it possible to have Browser UI and API tests in the same project?

### ISSUE THREAD

**Issue by joaodias14** [microsoft/playwright#17162]
Currently, we have a project setup with only Browser UI tests. They span 4 different browsers and complete the test for each. This is working without any issues. However, now we want to do some API testing as well using the same project, but we didn't find any way to override the global configuration that includes the 4 browsers and thus each API test is being performed 4 times, which is not what we want as 1 is enough. Is there any way of achieving this? Thanks!

**Comment by dgozman** [comment]
@joaodias14 This should be possible by defining multiple projects. If you could shared the config file, we might be able to help you.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by joaodias14** [comment]
Hi @dgozman, can you provide an example of how to define multiple projects? Thanks!

**Comment by mxschmitt** [comment]
See here: @joaodias14 https://playwright.dev/docs/test-advanced#projects

**Comment by joaodias14** [comment]
Thanks for the link, but my understanding about the `projects` config is that this is a global configuration that is applied to all tests. And that is exactly the problem we are facing because we have tests that we want to run in all these different browsers, but we also have others that are simply API tests and thus do not need a browser at all. Below you can find our config:
```
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  retries: 3,
  workers: 4,
  testDir: 'src/tests',
  timeout: 60000,
  reporter: [['list'], ['junit', { outputFile: 'results.xml' }]],
  use: {
    headless: true,
    trace: 'retain-on-failure',
    navigationTimeout: 120000,
  },
  projects: [
    {
      name: 'Firefox',
      use: { browserName: 'firefox' },
    },
    {
      name: 'Chromium',
      use: { browserName: 'chromium' },
    },
    {
      name: 'Android',
      use: {
        browserName: 'chromium',
        ...devices['Pixel 5'],
      },
    },
    {
      name: 'IOS',
      use: {
        browserName: 'webkit',
        ...devices['iPhone 13'],
      },
    },
  ],
};

export default config;
```

**Comment by mxschmitt** [comment]
You can pass [testMatch](https://playwright.dev/docs/api/class-testconfig#test-config-test-match) to a project to include some files into a project. So you target e.g. only the tests/api directory for the api tests and put your e2e tests into tests/e2e folder.

**Comment by joaodias14** [comment]
Do you mean having something like the following?
```
import { PlaywrightTestConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  retries: 3,
  workers: 4,
  testDir: 'src/tests',
  timeout: 60000,
  reporter: [['list'], ['junit', { outputFile: 'results.xml' }]],
  use: {
    headless: true,
    trace: 'retain-on-failure',
    navigationTimeout: 120000,
  },
  projects: [
    {
      name: 'Firefox',
      testMatch: 'src/tests/e2e',
      use: { browserName: 'firefox' },
    },
    {
      name: 'Chromium',
      testMatch: 'src/tests/e2e',
      use: { browserName: 'chromium' },
    },
    {
      name: 'Android',
      testMatch: 'src/tests/e2e',
      use: {
        browserName: 'chromium',
        ...devices['Pixel 5'],
      },
    },
    {
      name: 'IOS',
      testMatch: 'src/tests/e2e',
      use: {
        browserName: 'webkit',
        ...devices['iPhone 13'],
      },
    },
  ],
};

export default config;
```
