### ISSUE TITLE
How to use playwright codegen without codegen creating automatically generated assertions to have URL "await expect(page).toHaveURL('')"

### ISSUE THREAD

**Issue by Wilhop** [microsoft/playwright#17179]
### Discussed in https://github.com/microsoft/playwright/discussions/16914

<div type='discussions-op-text'>

<sup>Originally posted by **Wilhop** August 30, 2022</sup>

I'm using playwright codegen to generate the frame for a new test:
`npx playwright codegen https://cloudapp.azure.com`

The problem is that codegen generates quite many expects that the URL is a certain URL where the app has navigated to.

But the URL in most cases has dynamic routes, for example a new ID or number. In the example below, we record the creation of a new salesorder. Playwright codegen has generated an auto-assert that the url should have /salesorder/103. I have to delete this line, because I cannot be sure of the ID in parallel runs with multiple browsers. It is not relevant to test anyhow.
```
 // Click div[role="button"]:has-text("Create")
  await page.locator('div[role="button"]:has-text("Create")').click();
  await expect(page).toHaveURL('https://cloudapp.azure.com/salesorder/103'); // Don't want this autogenerated line, it will only cause instability
```

**Any ideas on how to not have those auto-assert URL lines?** it seems silly to having to always delete those lines, when pretty much all others lines are based on recorded actions.</div>

**Comment by dgozman** [comment]
@Wilhop This is not currently possible, but sounds like a nice feature request.

**Comment by Wilhop** [comment]
After using codegen a lot, from the perspective of our application the auto-generated expect(page).toHaveURL(..) could be categorized more as a "bug" or to be more precise: doesn't work as expected based on requirements: _"Playwright will generate the code for the user interactions."_ https://playwright.dev/docs/codegen

- If I don't click a button, input text or move my mouse, it won't be generated. User has control, works as expected.
- **I have no control over those auto-expects, it is not a user interaction.**

These cause lots of bugs in test code when someone forgets to clean them. I hope this use case is useful in the future! :)

**Comment by Wilhop** [comment]
I must add some additional data on this: 13.10.2022 Microsoft presented Playwright in Microsoft Ignite Playwright https://ignite.microsoft.com/en-US/sessions/ea19c293-7d8a-4218-8203-5af9528a091b?source=sessions

The presenters recorded tests. After recording, they instructed that one should refactor and remove all hardcoded URL's, which were expects toHaveURLs that were generated automatically. So basically this exact issue. And I saw some of the comments wondering: "why generate something you have to delete anyway?"
