### ISSUE TITLE
[REGRESSION]: 1.25.2 Install error

### ISSUE THREAD

**Issue by trevorbye** [microsoft/playwright#17171]
**Context:**
- GOOD Playwright Version: [1.25.1]
- BAD Playwright Version: [1.25.2]
- Operating System: [Linux]
- Extra: [Node.js: 16.17.0, npm: 8.15.0]

**1,25,2 Install error**

Install for new version 1.25.2 is failing on Linux docker image; seems to be something Chromium-related. Issue is fixed by pinning to version 1.25.1. here is the relevant stack trace:

```
 Installing node modules
 npm ERR! code 1
 npm ERR! path /tmp/build_069b47bb/node_modules/playwright
 npm ERR! command failed
 npm ERR! command sh /tmp/install-5cf7febd.sh
 npm ERR! Downloading Chromium 102.0.5005.40 (playwright build v1005)...
 npm ERR! Downloading Chromium 102.0.5005.40 (playwright build v1005)...
 npm ERR! Downloading Chromium 102.0.5005.40 (playwright build v1005)...
 npm ERR! /tmp/build_069b47bb/node_modules/playwright-core/lib/server/registry/index.js:652
 npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
 npm ERR!             ^
 npm ERR! 
 npm ERR! Error: Failed to download Chromium 102.0.5005.40 (playwright build v1005), caused by
 npm ERR! Error: read ECONNRESET
 npm ERR!     at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
 npm ERR!     at /tmp/build_069b47bb/node_modules/playwright-core/lib/server/registry/index.js:652:13
 npm ERR!     at async Registry._downloadExecutable (/tmp/build_069b47bb/node_modules/playwright-core/lib/server/registry/index.js:651:5)
 npm ERR!     at async Registry.install (/tmp/build_069b47bb/node_modules/playwright-core/lib/server/registry/index.js:626:9)
 npm ERR!     at async installBrowsersForNpmInstall (/tmp/build_069b47bb/node_modules/playwright-core/lib/server/registry/index.js:819:3)
```

**Comment by zardoy** [comment]
As I understand it is not a regression, I tried different versions. Now install at any version fails.

**Comment by jimmytimmons** [comment]
Seeing the below on playwright 1.22.1

```Downloading Firefox 99.0.1 (playwright build v1323)...
Failed to install browsers
Error: Failed to download Firefox 99.0.1 (playwright build v1323), caused by
Error: getaddrinfo EAI_AGAIN playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26)

**Comment by dgozman** [comment]
@jimmytimmons Could you please try downloading the following urls and see whether any of them works?
```
https://playwright.azureedge.net/builds/firefox/1323/firefox-ubuntu-20.04.zip
https://playwright-akamai.azureedge.net/builds/firefox/1323/firefox-ubuntu-20.04.zip
https://playwright-verizon.azureedge.net/builds/firefox/1323/firefox-ubuntu-20.04.zip
```

I assume you are on ubuntu-20.04. If not, please share your OS version.

**Comment by dgozman** [comment]
@trevorbye It seems like something strange is happening in your setup. Playwright v1.25.1 and v1.25.2 come with `Chromium 105.0.5195.19`, while your log says `Downloading Chromium 102.0.5005.40 (playwright build v1005)...`.  Could you please double check the versions you are using? If you could share a repro, that would be great!

**Comment by trevorbye** [comment]
> @trevorbye It seems like something strange is happening in your setup. Playwright v1.25.1 and v1.25.2 come with `Chromium 105.0.5195.19`, while your log says `Downloading Chromium 102.0.5005.40 (playwright build v1005)...`. Could you please double check the versions you are using? If you could share a repro, that would be great!

just double checked, original version tag we were using was `^1.16.3` which I just installed locally to check, and it is indeed resolving to 1.25.2 (this installs fine locally btw). This is on Heroku using buildpacks (which I think are just some abstracted docker images), and it's using the buildpacks `heroku/nodejs` and `https://buildpack-registry.s3.amazonaws.com/buildpacks/jontewks/puppeteer.tgz` so you may be able to repro by creating a node application, and trying to compile it with those two buildpacks on heroku. 

I'm not sure about the Chromium versions, maybe  `^1.16.3` is not resolving to the same version on this image as it is when installing locally? but I think it probably should be.. default build logs don't show which version it is actually trying to install either so I'll see if there is a way to change logging level.

**Comment by eddiemonge** [comment]
```
node_modules/playwright-core/lib/utils/registry.js:574
npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
npm ERR!             ^
npm ERR! 
npm ERR! Error: Failed to download chromium v939194, caused by
npm ERR! Error: connect ETIMEDOUT 13.107.213.40:443
```

```
    "playwright": "^1.15",
    "playwright-cli": "^0.180.0",
```

Happening on Github actions as well

**Comment by orestis** [comment]
I have the same issue with GitHub actions too.
