### ISSUE TITLE
[BUG] test.fail() weird behavior with soft assertions

### ISSUE THREAD

**Issue by klepik1990** [microsoft/playwright#17195]
**Describe the bug**

Hello guys! I came across strange behavior related to test.fail() method. The problem is in the following:
If one of the steps marked as test.fail() with a condition does not pass for this reason, then it does not matter for what reason the subsequent steps will fail - the test will still be green. I'm not sure if it's bug or not.
P.S. I use soft assertions.

**Context:**
- Playwright Version: 1.25.2
- Operating System: macOs Monterey 12.5.1
- Node.js version: 14.16.0

**Code Snippet**
Here is fake test, but main idea is the same.

```javascript
import { expect, test } from '@playwright/test';

test('Demo', async () => {
    await test.step('Should mark as passed', async () => {
        test.fail(2 === 2, 'always green');
        await expect.soft(2).toEqual(1);
    });

    await test.step('Should failed always', async () => {
        await expect.soft(2).toEqual(1);
    });
});
```

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/49123512/189142019-99ad0e8b-7832-43bb-ba88-c3f88edb2935.png">

**Comment by dgozman** [comment]
@klepik1990 This seems to work as expected:
- `test.fail()` marks the whole test as "expected to fail", not a particular step. Therefore, if any assertion in the test fails, in any of the steps, the test turns green.
- Meanwhile, there were two assertions that failed, so both of them are shown in the report.

Does that make sense? Did you expect something else?

**Comment by klepik1990** [comment]
Maybe there is a way to mark just a step as failed?

**Comment by dgozman** [comment]
Closing as per above. If you still have issues, please file a new bug and link to this one.
