### ISSUE TITLE
[Question]  When does test.fail(condition[,description]) echo the description?

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#17205]
In https://playwright.dev/docs/api/class-test#test-fail-1, when test.fail() is called with the optional description,
when does that description gets displayed? The documentation says "Optional description that will be reflected in a test report".

I have tried running a test.fail(true, "This fails bec XXX") with dot, line and list reporters and none of them displays this description string in the console output. Is the console output different from a test report?

In my scenario, a testcase writer can use test.fail to pass a testcase that is expected to fail. When the CiCd runs,
another engineer ( not necessarily the one who added the test.fail ) might look at the test output and it would be nice if he/she 
sees that test.fail description string.

**Comment by dgozman** [comment]
@khtan Terminal reporters do not show annotations due to limited space, but html report includes them. I'll leave this issue as a feature request. See also #8852 for a similar one.

**Comment by khtan** [comment]
OK, thanks for the explanation.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
