### ISSUE TITLE
[BUG] Can't use navigator for paste from 'copy to clipboard' button

### ISSUE THREAD

**Issue by chalvjulian** [microsoft/playwright#17212]
Hii all, please help me for my problem

I got error message
![image](https://user-images.githubusercontent.com/53189284/189287337-0a8a06d7-8179-4925-911f-d501f3ac5743.png)

This is my code:
![image](https://user-images.githubusercontent.com/53189284/189287459-2d128185-2b10-4f65-ab4e-b30cbbd8c3fd.png)

This is my config:
![image](https://user-images.githubusercontent.com/53189284/189287535-6e26f684-7d89-40ee-aba7-39f4e1a13867.png)

**Comment by dgozman** [comment]
@chalvjulian It looks like you are trying to call `navigator.clipboard.readText()` in your test in the Node.js environment. You should instead call this in the page environment using one of the `evaluate` methods. [Learn more about evaluating in the docs](https://playwright.dev/docs/evaluating).

```js
await this.imgCopy.click()
let text = await page.evaluate(() => navigator.clipboard.readText());
console.log(text);
```

**Comment by dgozman** [comment]
Closing per above. If you still have issues, please file a new bug and link to this one.
