### ISSUE TITLE
[Question] Using filtering and chainging on locators together

### ISSUE THREAD

**Issue by AbdealiJK** [microsoft/playwright#17213]
Hi, I have a usecase where I am trying to find a section based on `has_text` and then finding children elements within that.
(I use the python client with the sync api)

So, If I have a DOM structure like:
```html
<div class="address">
  <p>
    <label>Line 1</label>
    <input type="text" />
  </p>
  <p>
    <label>Line 2</label>
    <input type="text" />
  </p>
</div>
```

When I am trying to fill these values - I am doing:
```py
card = page.locator('.address p', has=page.locator('text="Line 1"'))
card.locator('input').fill('text to type')
```

But this is failing with the error showing something like this:
```
Waiting for selector ".address p >> has="text=\"Line 1\"" >> input"
```
And fails

It looks like this is actually looking for `input` within my `label`
But I was expecting playwright would find the `input` within my `p` (which contains "Line 1")

It looks like instead onf doing a filter and then a chain it is doing 2 chains.
What would be the right way to write the locator for my case ?

**Comment by dgozman** [comment]
@AbdealiJK This works for me with playwright v1.25.2:

```py
import re
from playwright.sync_api import Page, expect


def test_mytest(page: Page):
    page.set_content("""
      <div class="address">
        <p>
          <label>Line 1</label>
          <input type="text" id=target />
        </p>
        <p>
          <label>Line 2</label>
          <input type="text" />
        </p>
      </div>""")
    card = page.locator('.address p', has=page.locator('text="Line 1"'))
    card.locator('input').fill('text to type')
    print(card.locator('input'))
    expect(page.locator('#target')).to_have_value('text to type')
```

Running with `pytest -s`:
```
test_mytest.py <Locator frame=<Frame name= url='about:blank'> selector='.address p >> has="text=\\"Line 1\\"" >> input'>

==== 1 passed in 0.82s ====
```

Could you please share a repro?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by AbdealiJK** [comment]
Really weird - in my actual application this is throwing an error.
But in the example application you shared - it is working fine.

Looks like I was mistaken. Will double check the selectors and so on and get back

Thanks for the reproducible example ! Wasnt aware that `set_content` can be used here - that's pretty nice
