### ISSUE TITLE
[Question] I cannot make eslint playwright plugin to work

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#17225]
I am trying to use [eslint-plugin-playwright](https://www.npmjs.com/package/eslint-plugin-playwright) but I can't make it work properly.

This is my eslintrc.json file:  
```
{
  "parser": "@typescript-eslint/parser",
  "parserOptions": {
    "ecmaVersion": "6",
    "sourceType": "module"
  },
  "plugins": ["@typescript-eslint"],
  "extends": [
    "eslint:recommended",
    "plugin:playwright/playwright-test",
    "plugin:@typescript-eslint/recommended"
  ]
}
```
This is my package.json file  
```
  "devDependencies": {
    "@playwright/test": "^1.25.1",
    "@typescript-eslint/parser": "^5.36.2",
    "allure-commandline": "^2.17.2",
    "allure-playwright": "^2.0.0-beta.15",
    "cross-env": "^7.0.3",
    "eslint": "^8.23.0",
    "eslint-plugin-playwright": "^0.11.1",
    "husky": "^7.0.0",
    "playwright": "^1.22.2",
    "prettier": "2.5.1",
    "pretty-quick": "^3.1.3"
  },
  "dependencies": {
    "dotenv": "^16.0.2"
  }
``` 
When I run the following command: `eslint "**/*.ts" --ignore-pattern node_modules/`  
I get the following errors:  
```
Parsing error: The keyword 'import' is reserved
Parsing error: The keyword 'export' is reserved
```  
Also when I have for example: `await page.waitForTimeout(3000);` in my code, it doesn't show me any errors.   
Can you please help?

**Comment by mareru** [comment]
Sorry guys, I had named the configuration file without the dot at the beginning - so it was eslintrc.json instead of .eslintrc.json.  
Now it works when I run it via command `eslint "**/*.ts" --ignore-pattern node_modules/` 
But it doesn't show errors in the code while typing it. What do I need to do in order to achieve this?

**Comment by jfgreffier** [comment]
If you are using VS Code, you'll need this extension https://marketplace.visualstudio.com/items?itemName=dbaeumer.vscode-eslint

Can you close your issue as it is sloved ?

If you have more questions, please consider joining Playwright's slack https://aka.ms/playwright-slack

**Comment by dgozman** [comment]
Closing as per above.
