### ISSUE TITLE
[BUG] HTML and tracefiles are missing page.percySnapshot() Actions/Steps

### ISSUE THREAD

**Issue by unlikelyzero** [microsoft/playwright#17226]
**Context:**
- Playwright Version: mcr.microsoft.com/playwright:v1.23.0-focal
- Browser: chromium

**Describe the bug**
Filed here https://github.com/percy/percy-playwright/discussions/130

We are actively triaging a percy bug and as a part of that debugging process, we noticed that the page.percySnapshot() commands/actions/steps are described as `page.evaluate— ../../../node_modules/@percy/playwright/index.js:18`. 

How are commands "registered" with the HTML and tracefile reports as they would be interpreted in the IDE?

**Debug logs**

https://circleci.com/api/v1.1/project/github/nasa/openmct/49758/output/106/0?file=true&allocation-id=631b813cddd6ab006df32154-0-build%2F3ADEF78B

**Code to reproduce issue

https://app.circleci.com/pipelines/github/nasa/openmct/13274/workflows/44cd228c-30b6-4fc2-b237-40e08c290419/jobs/49758/steps

HTML Report
https://output.circle-artifacts.com/output/job/fe2433fc-3e3b-4702-8dce-d0f52b39d6f2/artifacts/0/html-test-results/index.html

Tracefile
https://output.circle-artifacts.com/output/job/fe2433fc-3e3b-4702-8dce-d0f52b39d6f2/artifacts/0/html-test-results/data/99a21c6592bc4170505b7f7d6766d65fed3cbe9c.zip

**Comment by dgozman** [comment]
I read this as a feature request to somehow change `page.evaluate()` in the html/trace to a custom title, am I right?

As a workaround, wrap percy snapshot with a `test.step()` that will be shown with a custom title:

```js
page.percySnapshot = async (...args) => {
  await test.step('percy snapshot', () => actualPercySnapshot(page, ...args));
};
```

Let me know if this helps.

**Comment by unlikelyzero** [comment]
@dgozman what would that look like if the step failed?

**Comment by dgozman** [comment]
@unlikelyzero Red, as any other failed step 😄

**Comment by mxschmitt** [comment]
@unlikelyzero does it work for you? If not, I'd keep it open as a feature request.

**Comment by unlikelyzero** [comment]
@mxshmitt it doesn't address the root of the issue. We've actually noticed several issues with the reporter's api that i think i'll file together as soon as i'm freed up at work

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
