### ISSUE TITLE
[BUG] MountResult functions hang indefinitely when called on an empty React.Fragment, but not an empty div

### ISSUE THREAD

**Issue by f-o-w-l** [microsoft/playwright#17231]
**Context:**
- Playwright Version: 1.25.1
- Operating System: Linux 5.17 Pop!_OS 20.04 LTS
- Node.js version: v16.14.2 LTS
- Browser: All
- Extra: N/A

**Code Snippet**

When testing a list component in a test using the `mount` function from the `@playwright/experimental-ct-react` `test` function, I ran into this problem.

I have not yet stubbed the `listElements` variable in my test, so the `MyListContainer` component renders an empty JSX Fragment. 

This code can be tested successfully:

```javascript
const MyListContainer = () => {
  return (
    <div>
      {listElements.map(() => <SomeListElement />)}
    </div>
  )
}
```

But with this code:

```javascript
const MyListContainer= () => {
  return (
    <>
      {listElements.map(() => <SomeListElement />)}
    </>
  )
}
```

The `textContent`, `innerText`, and `innerHTML` functions will hang a test indefinitely after called on the mounted component. The `allInnerTexts` and `allTextContents` functions understand the JSX and correctly return an empty array.

Test code:

```javascript
import React from 'react'
import { test, expect } from '@playwright/experimental-ct-react'

import MyListContainer from '.'

test('component mounts', async ({ mount }) => {
  const component = await mount(<MyListContainer />)

  console.log('allInnerTexts():', await component.allInnerTexts()) // Correctly prints: allInnerTexts(): []
  console.log('allTextContents():', await component.allTextContents()) // Correctly prints: allTextContents(): []
  console.log('textContent():', await component.textContent()) // Will hang the test indefinitely, nothing is logged
  console.log('innerText():', await component.innerText()) // Will hang the test indefinitely if called first
  console.log('innerHTML():', await component.innerHTML()) // Will hang the test indefinitely if called first

  await expect(component).toBeTruthy()
})

```

**Describe the bug**

Described above.

**Comment by mxschmitt** [comment]
The reason for this behaviour is that Playwright Locator methods are essentially performing [auto waiting](https://playwright.dev/docs/actionability) until an element appears on the DOM, is visible, etc. see [here](https://playwright.dev/docs/actionability). It tries to auto wait for the element which got rendered.

In your case, the DOM looks like this: `<div id="root"></div>` - so there is nothing rendered, Playwright will wait for the element to appear, but it never appears.

If you want to ensure, nothing is there, then we'd recommend: `await expect(component).toBeHidden()`.

Alternatively a bit more hacky you can do the following which would work: `await page.locator('#root').innerText()`

**Comment by f-o-w-l** [comment]
Thanks for your reply! Alright, that makes sense to me that auto-waiting behavior should be consistent and always require the root component element to be Attached. Seems like good design to me!

My question now would be why `allInnerTexts` and `allTextContents` aren't listed as actions in the table, when they seem to be actions available on any Locator. Seems like that would be helpful, even if its value in the Attached column of the table would be "-" to indicate being attached isn't required.

**Comment by mxschmitt** [comment]
All Locator functions are based on [strict mode](https://playwright.dev/docs/locators#strictness), so they will throw if the Locator will match multiple DOM elements. Only `allInnerTexts` and `allTextContents` are an exception there. They will be executed on all the matching DOM elements. Since they don't know for how many elements they should wait, they don't wait.
