### ISSUE TITLE
[Question] Error: Cannot find module 'playwright' when trying to import electron from playwright

### ISSUE THREAD

**Issue by ManikandanMani** [microsoft/playwright#17234]
Hi, I am trying to launch windows teams desktop client through using playwright electron namespace, but couldn't able to import it from the namespace provided in the docs-https://playwright.dev/docs/api/class-electron `const { _electron } = require('playwright');` . Can anyone cite me on how to import electron functions from the namespace without any errors and lauch the electron app locally on windows machine

**Comment by mxschmitt** [comment]
If you get `Cannot find module 'playwright'` this means that the module is not installed. You can install NPM libraries with e.g. `npm install -D playwright-core`

Playwright exposes `_electron` on all the packages, so you can choose between `@playwright/test`, `playwright-core` and `playwright`.

Note that the latter will download all the three browsers automatically, so if you are not using them, we'd recommend the first or second. If you are not using `@playwright/test` then `playwright-core` is most likely the best fit!

**Comment by ManikandanMani** [comment]
Hi @mxschmitt , Thanks for reaching out, you were right I didn't install  the playwright-core npm package, after installing this package I didn't get any import errors and I could able to access _electron.
