### ISSUE TITLE
[getting page.$eval: Execution context was destroyed, most likely because of a navigation]

### ISSUE THREAD

**Issue by Avi-1996** [microsoft/playwright#17233]
I am just using got function but it gives me the error.

   const context = await chromium.launch("./state.json", { headless: false });
    await page.goto("https://www.google.com");

**Comment by mxschmitt** [comment]
Can you share a full repro with us? It's throwing at `page.$eval` but we see no `page.$eval` in your code snippet!

**Comment by mxschmitt** [comment]
Closing for now, please re-file with a clear repro.
