### ISSUE TITLE
How can I maximize the browser window when I use browser context in C#

### ISSUE THREAD

**Issue by dbhimar** [microsoft/playwright#17246]
How can I maximize the browser window when I use browser context in C#(Nunit)

I tried with following code, but still browser is not maximized.

 public async Task Setup()
        {
            _playwright = await Playwright.CreateAsync();

            _browser = await _playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
            {
              //  Headless = true,
                Channel = "msedge",
                Args = new[]
                    {
                        "--start-maximized"
                    }
            });
            _browserContext = await _browser.NewContextAsync();
            await _browserContext.Tracing.StartAsync(new()
            {
                Screenshots = true,
                Snapshots = true,
                Sources = true
            });
             _page = await _browserContext.NewPageAsync();
            await _browser.NewContextAsync(new BrowserNewContextOptions()
            {
                RecordVideoDir = "videos/",
                ViewportSize =ViewportSize.NoViewport,

            });
                  }

**Comment by vjvibhanshu** [comment]
I am also looking for something like this
it's not language related I think it is more toward feature-related.
Playwright has an option for `view-port` but not for the full screen like selenium.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/4046 since we have a feature request for it already. There is a workaround available for Chromium, but not for Firefox and WebKit.
