### ISSUE TITLE
[Question] what the use case Interrupted status. i cant find in official document

### ISSUE THREAD

**Issue by rio-ap** [microsoft/playwright#17253]
as the title said, what trigger test mark as interrupted (in Testinfo.status) other than stopping test in prematurely. is this achievable or what? when browsing in github issue, the only explanation i found is interrupted is skipping status when max failure (retry) achieved. care to elaborate more?

**Comment by mxschmitt** [comment]
When the user does CTRL + C (sigint) the current test ends up being in interrupted state. The tests after it are marked then as skipped. Does this answer your question?

**Comment by rio-ap** [comment]
So the interrupted status only achievable by this action? Or we have another use case (more natural case) to get that? I mean by default, only ctrl + c will get you interrupted status in Playwright?

**Comment by mxschmitt** [comment]
So it can be for the following reasons:

- uncaughtException
- unhandledRejection
- sigint (CTRL + C)
- maxFailures limit reached, the rest of the tests get stats interrupted

**Comment by rio-ap** [comment]
i see, thank you for the information @mxschmitt . it will be better if this information is stated in the official document

([here](https://playwright.dev/docs/api/class-testcase#test-case-expected-status) or [here](https://playwright.dev/docs/api/class-testresult#test-result-status))

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
