### ISSUE TITLE
[BUG] No run icons after spec file rename

### ISSUE THREAD

**Issue by Mitri86** [microsoft/playwright#17251]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Windows
- Node.js version: 16.13.2
- Visual Studio Code version: 1.71.0
- Playwright for VSCode extension version: 0.2.10
- Browser: All
- Extra: none

**Code Snippet**

https://github.com/Mitri86/playwright-browserstack

**Describe the bug**
Steps to reproduce:
1. Open the https://github.com/Mitri86/playwright-browserstack/playwright-test folder in VSCode
2. Rename a spec file.

As soon as I rename a spec file, the extension stops showing run icons in the editor. 
Icons come back after VSCode restart.
`npx playwright test` works good from the command line as well.

Seems the issue happens only if the playwright config does not define the `testDir` option.

**Comment by mxschmitt** [comment]
The repository does not contain a Playwright confile file, without that the extension does not work!

**Comment by Mitri86** [comment]
yep, that was my bad. 
I've added  https://github.com/Mitri86/playwright-browserstack/blob/main/playwright-test/playwright.config.ts

**Comment by Mitri86** [comment]
I usually try `test_1.spec.js` to `test_2.spec.js`
![image](https://user-images.githubusercontent.com/113098014/189940480-359caf1d-d236-4f31-8505-7491c1532f82.png)

**Comment by mxschmitt** [comment]
I can repro, the test tree does not update if you rename test_1 into test_2 on Windows. On macOS it works as expected. After reloading inside the test explorer it gets detected correctly.

**Comment by mxschmitt** [comment]
@Mitri86 unfortunately you deleted your reproduction, would it be possible to upload it again so Pavel can take a look?

**Comment by Mitri86** [comment]
@mxschmitt @pavelfeldman 
I've uploaded the repo again

**Comment by pavelfeldman** [comment]
There is a lot happening in your custom fixtures, is there a simpler repro we could use?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
