### ISSUE TITLE
[Bug] Chromium proxy config throws on Windows

### ISSUE THREAD

**Issue by 22mSqRi** [microsoft/playwright#17252]
I need test on authentication proxy, so I wrote proxy setting in `playwright.config.ts` .
Proxy setting is successed on firefox, but chronium still have proxy error.
What should I to do?

playwright version: 1.25.1

playwright.config.ts
```
const config : PlaywrightTestConfig = {
...
use:{
   proxy: {
      server: 'xxxxx',
      username: 'xxxxx',
      password: 'xxxxx',
   },
  },
}
```

chronium error message
```
browser.newContext: Browser needs to be launched with the global proxy, If all contexts override the proxy, global proxy will be never used and can be any string, for example "launch({ proxy: {server:'http://per-context'}})"
```

**Comment by mxschmitt** [comment]
I can repro, and its caused by the following upstream Chromium bug: https://crbug.com/1310057

Would be amazing if you could star ⭐  it on their side, then it's getting prioritized higher!

As a workaround, you can do the following: 

```ts
const config: PlaywrightTestConfig = {
  use: {
    proxy: {
      server: 'xxxxx',
      username: 'xxxxx',
      password: 'xxxxx',
    },
    // workaround for: https://crbug.com/1310057
    launchOptions: {
      proxy: {
        server: 'per-context',
      },
    },
  },
}

```

**Comment by helloworldcyj** [comment]
playwright version: 1.39.0

I solved the error using the following configuration:

`launchOptions: { args: ['--proxy-server=xxxxx'] }`

**Comment by mxschmitt** [comment]
Note: Created a fix for it upstream https://chromium-review.googlesource.com/c/chromium/src/+/5688851 - keeping this issue open until we remove our `per-context` downstream hacks.
