### ISSUE TITLE
[Question] CLI Aliases confusing

### ISSUE THREAD

**Issue by vitalics** [microsoft/playwright#17257]
Hi PW team. I got a question after reviewing [PR](https://github.com/microsoft/playwright/pull/17229/files). As for me: `--workers` and `-j` aliases are confusing for me. Maybe it possible to fix it to `--jobs` (in case of mismatch long abbreviation), or it should be like `-w` (in case of mismatch short abbrev.)?

**Comment by mxschmitt** [comment]
We had it for historical reasons. Removing it would mean a breaking change, so we keep it for now.

**Comment by vitalics** [comment]
@mxschmitt does you have any plans for renaming this flags? Or maybe better to add all variations, like '--jobs' and 'workers' and mark unused/confused as deprecated

**Comment by mxschmitt** [comment]
> @mxschmitt does you have any plans for renaming this flags? Or maybe better to add all variations, like '--jobs' and 'workers' and mark unused/confused as deprecated 

No plans as of of today but we'll add it to the list of what to change in v2.
