### ISSUE TITLE
[Question]: Recursive function and wait statement are not working in "for" loop in Playwright

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#17259]
[Question]: **Recursive function** and **wait statement** are **not working** in **for** loop in Playwright.
Is anyone have any idea how to make it work? 
I need to call API function to grab the status of the tasks. There are 3 tasks for which I want the statuses.

**Comment by mxschmitt** [comment]
Can you share code with us? Otherwise we can't act on it.

**Comment by AkkyLohana90** [comment]
Hello Max Schmitt,

PFB code:
async getStatus(token, taskid, reponame, dataId, dataName) {
        for (let loopCount = 0; loopCount < 3; loopCount++) {
            this.verifyDSLoaded(token, taskid, reponame, dataId, dataName);
            taskId += 1;
        }
    }
I want to iterate this loop 3 times as I have 3 tasks for which I am looking for Status.

**Comment by mxschmitt** [comment]
I don't see any Playwright related code inside this? Playwright runs in Node.js so we recommend creating a small script e.g. test.js first to verify if things work as expected.

**Comment by AkkyLohana90** [comment]
ok, will check that. 
Closing it...
