### ISSUE TITLE
[BUG]-Visual Comparison - incorrect image is being compared when providing an image name in toHaveScreenshot function

### ISSUE THREAD

**Issue by oleksiykyrylenko** [microsoft/playwright#17261]
I am doing a data driven test. I have multiple screenshots with naming that follows this structure - user-sees-x-apples-when-y-apples. All works fine except of the case where I need to compare a current page with user-sees-1-apples-when-1-apples. Instead of grabbing this image, playwright grabs user-sees-0-apples-when-0-apples image. That causing the screenshot comparison to fail 

**Context:**
- Playwright Version: [what Playwright version do you use?] - 1.25.0
- Operating System: [e.g. Windows, Linux or Mac] - Windows
- Node.js version: [e.g. 12.22, 14.6] - 16.6.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] - All
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await expect.soft(page).toHaveScreenshot(`${configs.title}.png`);
```

**Describe the bug**

Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Does the same happen when you are not using soft assertions?

Can you provide a small repro/file which demonstrates the problem?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
