### ISSUE TITLE
[Question] Binary download URL

### ISSUE THREAD

**Issue by madmadson** [microsoft/playwright#17260]
``
npm init playwright@latest`
``
install binaries to local folder.. Sound legit. 

I have to know the URL from where the binaries are. For whitelabeling in  aproxy  environment.
IP or Domain.
A small log entry would be very helpfull...

**Comment by ltsuda** [comment]
See if this helps, I'm not 100% though

https://github.com/microsoft/playwright/pull/17158

**Comment by mxschmitt** [comment]
In the next version we're releasing `npx playwright install --dry-run` see https://github.com/microsoft/playwright/pull/17158. Would that work for you?
