### ISSUE TITLE
Can we link automation script with test plan in azure

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#17264]
Team , I have question regarding test cases in azure linking with playwright automation scripts written with javascript/ typescript ?
Can we link do that? If so how??

**Comment by mxschmitt** [comment]
Sounds like https://github.com/microsoft/playwright/pull/15736 would work for you and we can merge it into https://github.com/microsoft/playwright/issues/11143.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11143.
