### ISSUE TITLE
[BUG] locator.click: Timeout 30000ms exceeded. 

### ISSUE THREAD

**Issue by k4mmm** [microsoft/playwright#17275]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: v14.17.3
- Browser: Chrome

```
TimeoutError: locator.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".free >> nth=5"
    ============================================================locator.click: Timeout 30000ms exceeded.
    =========================== logs ===========================
    waiting for selector ".free >> nth=5"
    ============================================================
      48 | 		await page.waitForTimeout(10000);
      49 |
    > 50 | 		await page.locator('.free').nth(5).click({ force: true });
         | 		                                                                 ^
      51 |
      52 | 		await page.type('//*[@data-e2e="info.address.text"]/div/input', 'TestAdress' + randomNumber, { delay: 100 });
      53 | 		await page.fill('//*[@data-e2e="comment"]/div/textarea[1]', reason);
```

Hi
I have a problem with a button click, I get an error when I run the test. Locally everything works correctly.
i tried to add waitForSelector with timeout=150000 - does not work.
when the test is run locally - everything ends successfully.

**Comment by mxschmitt** [comment]
I'd recommend following out [debugging](https://playwright.dev/docs/debug) [guides](https://playwright.dev/docs/debug-selectors) and/or enabling [Traces](https://playwright.dev/docs/trace-viewer-intro) to understand how the DOM looks like on your remote environment! Enabling traces should give you an instant hint on what's going wrong.

Closing since we can't act on that issue.

**Comment by k4mmm** [comment]
@mxschmitt but when I start the test locally - the test works both on the localhost and on the site that is already on the hosting. 
but when I upload the changes to the hosting - at the end the same test fails. Therefore, I can not track with the help of these tools. Or is there such a possibility?

**Comment by mxschmitt** [comment]
Tracing allows you to record the DOM of your page, it will output a zip which you can open locally.

**Comment by k4mmm** [comment]
ohh... thank U. I misunderstood. it's great!!
