### ISSUE TITLE
[Feature] Show image diff when image width/height are different

### ISSUE THREAD

**Issue by brandonfillpot** [microsoft/playwright#17274]
**Context:**
- Playwright Version: v1.25.0
- Operating System: Mac (docker instance for ci which uses linux)
- Node.js version: v18.3.0
- Browser: Chromium, Safari
- Extra: [any specific details about your environment]

**Code Snippet**

```ts
import { test, expect } from "@playwright/test";
import { hideElements, hideOneTrust, timeout } from "../../../../../helpers.js";
test.describe.configure({ mode: "parallel" });

let env = process.env.ENV_VAR;

test.beforeEach(async ({ page }) => {
  const visibility = await page.locator("#onetrust-consent-sdk").isVisible();
  if (!process.env.EXCLUDE_COOKIE_TEST) {
    if (visibility) {
      await page.locator("#onetrust-accept-btn-handler").click();
    }
  }
});

test(`${env}/contact/`, async ({ page }) => {
  await page.goto(process.env.TEST_TARGET + "/en-ca/contact/");
  await page.waitForLoadState("networkidle");
  await hideOneTrust(page);
  await expect(page).toHaveScreenshot({
    fullPage: true,
    maxDiffPixelRatio: 0.02,
  });
});

```

**Describe the bug**

When changes to a page affect the length of the page, the pixelmatch will automatically fail the test without showing the diffs. I know that jest-image-snapshot has an option called allowSizeMismatch that fixes this, but i havent found any solution in the playwright docs for this issue, and its quite a sever one as it renders most visual regression testing useless, allowing too much room for human error when checking the artifacts

what we get when the page size is different below:

<img width="640" alt="Screen Shot 2022-09-08 at 10 57 21 AM" src="https://user-images.githubusercontent.com/84605170/189740195-8bfa35e2-85d0-46dc-bb6b-b73745a806d6.png">
<img width="426" alt="Screen Shot 2022-09-08 at 10 57 43 AM" src="https://user-images.githubusercontent.com/84605170/189740207-e1d0d535-8e04-4eaf-883a-de8bdc9aaf58.png">

what we need to see even if page size is different: 

<img width="944" alt="Screen Shot 2022-09-08 at 10 58 22 AM" src="https://user-images.githubusercontent.com/84605170/189740401-2e5d394b-9891-4a5f-8390-02cef1686447.png">

**Comment by pavelfeldman** [comment]
This should be fixed.
