### ISSUE TITLE
[BUG] Not able to click on security popup (for 3rd party cookie access) on Safari

### ISSUE THREAD

**Issue by zluo-owo** [microsoft/playwright#17285]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: v14.20.0
- Browser: WebKit
- Extra: need to install `python3` for serving a local web used for testing the issue. Or you can just open it using file path (need to change the url in the test spec.).

**Code Snippet**
Repo for the test:
https://github.com/zluo-owo/test-iframe/tree/master

**Describe the bug**
Not able to click on the buttons from security popup (for 3rd party cookie access) on Safari.
(This pop up is triggered by the [requestStorageAccess api](https://developer.mozilla.org/en-US/docs/Web/API/Document/requestStorageAccess))

<img width="800" alt="Screenshot 2022-09-13 at 5 22 50 PM" src="https://user-images.githubusercontent.com/113414388/189864404-1bab47ce-1dd7-433e-9ee1-6cb07e524e6d.png">

**Expected**
There should be a way to click on the `Allow` button of the popup.
Or maybe a workaround to handle the popup will also be really helpful.

Thanks in advance.

**Comment by zluo-owo** [comment]
Just to add-on: for some e2e cases, we actually want to verify how the page reacts to different user choices (`Allow` or `Dont't Allow`). So it would be really great if there is a way to click/resolve the dialog based on the given choice. 
Cheers!

**Comment by dgozman** [comment]
Proposed solution: make this dialog auto-allow, or make a permission for it.
