### ISSUE TITLE
[BUG] Allow downloads not working with default context when connectOverCDP is used in headless mode

### ISSUE THREAD

**Issue by douglasrpe** [microsoft/playwright#17281]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: -
- Browser: Chrome
- Extra: -

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```python
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from playwright.sync_api import sync_playwright

def enable_download(driver):
    driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')
    params = {'cmd':'Page.setDownloadBehavior', 'params': {'behavior': 'allow', 'downloadPath': '/Users/douglas.pereira/Downloads'}}
    driver.execute("send_command", params)

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--remote-debugging-port=46666")
driver = webdriver.Chrome(options=chrome_options)
enable_download(driver)
driver.get("https://www.python.org/downloads/release/python-3107/")

with sync_playwright() as p:
    result = requests.get('http://localhost:46666/json/version').json()
    wsEndpoint = result['webSocketDebuggerUrl']
    browser = p.chromium.connect_over_cdp(wsEndpoint)

# if you comment the with block above, the download will work. 
driver.find_element(By.XPATH, '//a[text()="Windows installer (64-bit)"]').click()
```

**Describe the bug**

Similar issue to https://github.com/microsoft/playwright/issues/12543 .
After connecting over cdp, download stops working. If the connect over cdp is removed, download feature works fine. The reason why the download feature is used by selenium and not playwright is that there are over ˜500 test cases in the private repo already written with selenium. Looking for the best approach to introduce playwright API without disturbing the existing functional test cases running everyday in the pipeline. Therefore, this is the reason that I need to download it using selenium still.

**Comment by mxschmitt** [comment]
You mean that your custom "enable_download" logic does not work anymore right?

Playwright also [sets](https://github.com/microsoft/playwright/blob/7e2aec7454f596af452b51a2866e86370291ac8b/packages/playwright-core/src/server/chromium/crBrowser.ts#L326) the download behavior, so it overrides your custom configured one. This is probably just the tip of the iceberg when running Selenium and Playwright together. I recommend to have them running independent from each other and use their own browsers, then such stuff does not occur.

aka. you have your existing selenium tests, and then you create a new project for playwright. New tests get written in Playwright and old tests either stay in selenium or you rewrite them to Playwright over time.

**Comment by douglasrpe** [comment]
Hi... Thanks in advance for your prompt reply.

Yes. However, if this code is run without the headless argument in the chrome options, everything works fine (even after the playwright's connect to CDP method). I mean this code below works fine (100% fine):
```python
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from playwright.sync_api import sync_playwright

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--disable-extensions")
#chrome_options.add_argument("--headless")
chrome_options.add_argument("--remote-debugging-port=46666")
driver = webdriver.Chrome(options=chrome_options)
driver.get("https://www.python.org/downloads/release/python-3107/")

with sync_playwright() as p:
    result = requests.get('http://localhost:46666/json/version').json()
    wsEndpoint = result['webSocketDebuggerUrl']
    browser = p.chromium.connect_over_cdp(wsEndpoint)

driver.find_element(By.XPATH, '//a[text()="Windows installer (64-bit)"]').click()
```

My custom "enable_download" logic was needed to make sure I can download the file in headless mode without playwright's connect to CDP method. I mean this code below works fine (100% fine):
```python
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from playwright.sync_api import sync_playwright

def enable_download(driver):
    driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')
    params = {'cmd':'Page.setDownloadBehavior', 'params': {'behavior': 'allow', 'downloadPath': '/Users/douglas.pereira/Downloads'}}
    driver.execute("send_command", params)

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--remote-debugging-port=46666")
driver = webdriver.Chrome(options=chrome_options)
enable_download(driver)
driver.get("https://www.python.org/downloads/release/python-3107/")

driver.find_element(By.XPATH, '//a[text()="Windows installer (64-bit)"]').click()
```

The bug is introduced after executing the playwright connect to CDP in headless mode. Then, the selenium's download stopps working. We have been running playwright and selenium for sometime now (2 months maybe), everything works fine but the download. 

 > I recommend to have them running independent from each other and use their own browsers, then such stuff does not occur.
> aka. you have your existing selenium tests, and then you create a new project for playwright. New tests get written in Playwright and old tests either stay in selenium or you rewrite them to Playwright over time.

Sure. That was my initial intention, but I have no "authority" to do that yet :( . That's why I am using the connectOverCDP method.

**Comment by mxschmitt** [comment]
I unfortunately need to close this, since there is nothing we can do from our side, I'm not familiar with Selenium nor we can spend time on digging into reasons why they infer with each other.

If you find a solution to your issue, feel free to comment it here, so others won't encounter it.

**Comment by douglasrpe** [comment]
Hi,
I got my head a refresh and I found how to solve this. We can just re-enable the download configuration again after playwright's connect to CDP. 

Thanks anyway for the prompty reply.

Here is the code.
```python
import requests
from selenium import webdriver
from selenium.webdriver.common.by import By
from playwright.sync_api import sync_playwright

def enable_download(driver):
    driver.command_executor._commands["send_command"] = ("POST", '/session/$sessionId/chromium/send_command')
    params = {'cmd':'Page.setDownloadBehavior', 'params': {'behavior': 'allow', 'downloadPath': '/Users/douglas.pereira/Downloads'}}
    driver.execute("send_command", params)

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--disable-extensions")
chrome_options.add_argument("--headless")
chrome_options.add_argument("--remote-debugging-port=46666")
driver = webdriver.Chrome(options=chrome_options)
enable_download(driver)
driver.get("https://www.python.org/downloads/release/python-3107/")

with sync_playwright() as p:
    result = requests.get('http://localhost:46666/json/version').json()
    wsEndpoint = result['webSocketDebuggerUrl']
    browser = p.chromium.connect_over_cdp(wsEndpoint)

enable_download(driver)
driver.find_element(By.XPATH, '//a[text()="Windows installer (64-bit)"]').click()
```
