### ISSUE TITLE
[BUG] Chrome Policy ExtensionInstallForcelist prevents Browser from closing

### ISSUE THREAD

**Issue by gemiusz** [microsoft/playwright#17299]
**Context:**
- Playwright Version: 1.22 (JAVA)
- Operating System: Windows 10 Pro
- Browser: Chrome (103.0.5060.53)
- Extra: Browser managed by the organization.

**Code Snippet**

```java
import com.microsoft.playwright.*;
import org.testng.annotations.Test;

public class PlayWrightTestNGExample {

    @Test
    public void testName() {
        Playwright playwright = Playwright.create();
        Browser browser;
        BrowserContext context;
        Page page;
        browser = playwright.chromium().launch(new BrowserType.LaunchOptions().setHeadless(false).setChannel("chrome"));
        context = browser.newContext();
        page = context.newPage();

        page.navigate("chrome://chrome-urls/");

        page.close();
        context.close();
        browser.close();
    }
}

```

**Describe the bug**

It took me a week of looking how to reproduce Bug mentioned and closed here [https://github.com/microsoft/playwright-java/issues/347](https://github.com/microsoft/playwright-java/issues/347)

I announce that: **I have reproduced it xD**

Below long story short:
I asked about this issue on Polish Facebook Playright group and one person have the same issue but in Playwright JS version. 
In my work environment Chrome is managed by organisation and have appiled some polices - the same have person from microsoft/playwright-java#347 and facebook group so this was place to search.
After some analyses and tirals with Workplace Team who managed polices we found that Extensions making problem - when all disabled everything working fine.
Today I added Chrome polices to my private laptop and found that when Policy [ExtensionInstallForcelist](https://chromeenterprise.google/policies/?policy=ExtensionInstallForcelist) is enabled and added for example [Webex Extension](https://chrome.google.com/webstore/detail/cisco-webex-extension/jlhmfgmfgeifomenelglieieghnjghma) Playwright driver have mentioned above problems with "Gracefully Close".

Logs when Policy is enabled:
![image](https://user-images.githubusercontent.com/30750006/176017274-43f731fd-de54-4d50-808e-ad9a5ae69134.png)

Policy settings:
![image](https://user-images.githubusercontent.com/30750006/176017425-e6b0c37c-971f-4826-9483-6efb3f9470d0.png)

I think the find above should help in preparing the fix.

**Comment by dgozman** [comment]
Closing this one, because Playwright does not work with any Chrome Policies.

**Comment by gemiusz** [comment]
From 13.09.2023 issue is under investigation by Chromium team.
Keep fingers crossed :)
