### ISSUE TITLE
[Question] - How do I append text into a Input Field ?

### ISSUE THREAD

**Issue by GunjanSheth** [microsoft/playwright#17295]
There is an input field on my page.
The input field is such that if I click on New -> there will be a default value in the input field (say "`letter-13092022-1`").

now i want to append "`-automation`", so that the input field looks like "`letter-13092022-1-automation`".

Can someone please help me how to do that ?

Obviously I can do the following.
```
previous_text = page.locator('locator of input field').input_value()
new_text = previous_text + '-automation'
page.locator('locator of input field').fill(new_text)
```

but that does not replicate the exact scenario i perform manually.

**Comment by mxschmitt** [comment]
The exact replicate would be the following:

```python
const my_element = page.locator("input")
await my_element.focus()
# Set the cursor to the end.
await my_element.evaluate("e => e.setSelectionRange(-1, -1)")
await my_element.type("kektus")
```

**Comment by GunjanSheth** [comment]
thanks a lot @mxschmitt. That worked
Closing the question here
