### ISSUE TITLE
Unable to install the playwright tool in the jenkins server - running in GCP - Long pending issue

### ISSUE THREAD

**Issue by gunabca** [microsoft/playwright#17322]
npm ERR! code 1
npm ERR! path /var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright
npm ERR! command failed
npm ERR! command sh -c node install.js
npm ERR! Downloading Chromium 105.0.5195.19 (playwright build v1019)...
npm ERR! Downloading Chromium 105.0.5195.19 (playwright build v1019)...
npm ERR! Downloading Chromium 105.0.5195.19 (playwright build v1019)...
npm ERR! /var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright-core/lib/server/registry/index.js:683
npm ERR!       throw new Error(`Failed to download ${title}, caused by\n${e.stack}`);
npm ERR!             ^
npm ERR! 
npm ERR! Error: Failed to download Chromium 105.0.5195.19 (playwright build v1019), caused by
npm ERR! Error: Client network socket disconnected before secure TLS connection was established
npm ERR!     at connResetException (node:internal/errors:691:14)
npm ERR!     at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
npm ERR!     at TLSSocket.emit (node:events:402:35)
npm ERR!     at endReadableNT (node:internal/streams/readable:1343:12)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm ERR!     at /var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright-core/lib/server/registry/index.js:683:13
npm ERR!     at async Registry._downloadExecutable (/var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright-core/lib/server/registry/index.js:682:5)
npm ERR!     at async Registry.install (/var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright-core/lib/server/registry/index.js:656:9)
npm ERR!     at async installBrowsersForNpmInstall (/var/workload/workspace/QET-PipeLine-Jobs/Playwright/Playwright_Jenkins_PipelineScript/node_modules/playwright-core/lib/server/registry/index.js:850:3)

**Comment by mxschmitt** [comment]
Looks like you are on a corporate environment which requires setting a proxy, do you have one configured? 

See here: https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy

**Comment by gunabca** [comment]
proxy is setup in the jenkins global configurations by default. However, I will check the link

**Comment by mxschmitt** [comment]
You are using the `playwright` module which will install the browsers by default. So it does exactly the same what `npx playwright install` is doing.

You could try logging the environment variables to make sure that `HTTPS_PROXY` is set?

**Comment by gunabca** [comment]
Yes, it was working fine with npm ci - installing the browsers by itself without npx playwright install command. however it stopped working 3 weeks back. The Https proxies are set at global level and other lines are working fine.

**Comment by mxschmitt** [comment]
What did you change 3 weeks ago? Did you change some settings on the Jenkins server, did you upgrade Playwright, did you change something on the network? There needs to be a reason, we at Playwright didn't change anything in that regard the past few releases. We unfortunately don't know anything about your network, so hard to debug that from our end!

**Comment by gunabca** [comment]
There is a high probability for it,  let me check with the team.

**Comment by mxschmitt** [comment]
Closing as per above in the meantime, since this is not a Playwright issue. Something has changed on your IT side, so nothing to act on our side.
