### ISSUE TITLE
[BUG] Browser works in headless mode for debug mode if fixtures are created inside step

### ISSUE THREAD

**Issue by balukov** [microsoft/playwright#17325]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Node.js version: 16.13.0
- Visual Studio Code version: 1.71.1
- Playwright for VSCode extension version: 0.2.10
- Browser: Chromium

**Code Snippet**

```js
import { test, chromium, expect } from '@playwright/test';

test.describe('Browser, where are u?', () => {
  test.beforeAll(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto('https://microsoft.com/');
    await page.waitForTimeout(10000);
  });

  test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    const getStarted = page.locator('text=Get Started');
    await expect(getStarted).toHaveAttribute('href', '/docs/intro');
  });
});

```

**Describe the bug**

Debug test from example (right click green triangle near the test > Debug test )  => Browser with Microsoft site doesn't exist

If just run the test (left click green triangle near the test) => Browser with Microsoft site exists 10 seconds

I need the unexpected beforeAll because I have a lot of preparations on different pages before tests.

**Comment by mxschmitt** [comment]
So the reason for that is that you create your whole browser, including context and page yourself which is strongly discouraged and leads to this misbehavior. The newly created browser does not know about the browser inside your test and the extension does not work with that. The recommended approach is to do this instead (move it to beforeEach):

```js
  test.beforeEach(async ({ page }) => {
    await page.goto('https://microsoft.com/');
    await page.waitForTimeout(10000);
  });
```

Alternatively you can do this: https://playwright.dev/docs/test-retries#reuse-single-page-between-tests but you suffer there from limited parallelism.

**Comment by mxschmitt** [comment]
Closing as per above.
