### ISSUE TITLE
[BUG] E2E test is failing as it's closing all the instances when test closes the current forked browser instance

### ISSUE THREAD

**Issue by shahabkhan12342** [microsoft/playwright#17323]
**Context:**
- Playwright Version: [1.25]
- Operating System: [Windows]
- Node.js version: [14.17.3]
- Browser: [Chrome]
- Chrome Version: [105]

**Code Snippet**
```
     public static async quitNewBrowserInstance() : Promise<void> {  
          await this.browser.contexts().pop().close();
          this.currentContextIndex = this.browser.contexts().length - 1;          
           this.currentPageIndex = 0;      
    }
```

**Describe the bug**

I am facing an issue since my Chrome is upgraded from version 101 to 105, When ever I fork a browser instance to perform any task in my test and then close that instance, instead of closing that respective instance it closes all the Brower instances and my E2E test fails. I have tested this on Firefox and also by downgrading the chrome to 101 version so it's working fine on Firefox and old version of chrome. I am only facing this issue on the latest version of Chrome i.e version 105.

**Error in the terminal**
![ss](https://user-images.githubusercontent.com/46971803/190090270-b5140da4-98b5-4fd7-b89c-c1637cde53f2.png)

**Comment by mxschmitt** [comment]
Can you provide a repro for us so we can try it out locally? Otherwise we can't act on it.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
