### ISSUE TITLE
[BUG] Playwright Test, TypeScript: Not accepting browser permissions in Chrome when headless (unless debug mode)

### ISSUE THREAD

**Issue by Phsyrik** [microsoft/playwright#17320]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Windows
- Node.js version: 18.7.17
- Browser: Chromium]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://app.teamflowhq.com/{roomcode}');

  // Click [data-testid="guest-submit"]
  await page.locator('[data-testid="guest-submit"]').click(); //ERROR, element doesnt exist because the page doesnt accept the camera and mic permissions.
});
```

When I run the test in headful, or debugger the test runs fine, but when I run normally headless, it fails. I used screenshot and trace to figure out it was redirecting to another page due to the permissions for the browser not being accepted. I assume since it works debug and headful that it is supposed to also work headless, which is why I marked it as a bug. 

I tried messing around with the browserContext permissions but that didnt seem to solve my problem.

**Comment by mxschmitt** [comment]
inside your playwright config for the chromium project, you can put the following:

```js
use: {
  launchOptions: {
    args: ['--use-fake-ui-for-media-stream'],
  },
},
```

then fake streams should be used for Google Chrome, would that work for you? since on CI environments you most likely don't have a camera attached, fake microphone/camera might be a better option compared to a real camera/microphone setup.
