### ISSUE TITLE
[Feature] Allow playwright to access pages in hub or extension popup

### ISSUE THREAD

**Issue by KagamiChan** [microsoft/playwright#17321]
Hi Playwright team,

Our team is working on a hub page and want to use Playwright to do the automation testing, but this is currently not possible while Selenium does provide a way.

## background
Let me first explain what the hub framework/page means: it's a special webUI embedded inside a drawer panel of the browser, we can find it in both Edge and Chrome
<img width="326" alt="image" src="https://user-images.githubusercontent.com/3816900/190053868-14657b8d-ccf5-4a3a-a7ce-88d35c3653eb.png">

<img width="264" alt="image" src="https://user-images.githubusercontent.com/3816900/190054011-4e391402-4a8f-4f78-9d97-a67ee18760be.png">

Similarly, for browser extensions, the popup window also contains a web page:
<img width="195" alt="image" src="https://user-images.githubusercontent.com/3816900/190055633-e8c6c00e-0843-4bd4-ae68-c6a7233116d6.png">

These embedded pages are often using `edge://` or `chrome://` protocol, and in Playwright there's no way to switch to the page inside the hub, it would not appear in the result of `BrowserContext.pages()`.

Although we may open them in a new tab with the URL, these pages are usually **contextual** for current active browser tab, opening them in the new tab will completely loses the context.

## how Selenium is handling these types of pages
Selenium provides a (relatively) low level page handle API so that we can find the page interating over the handles with `getAllWindowHandles`, example code:
```ts
import { WebDriver } from 'selenium-webdriver';

export const switchToWindowByUrl = async (driver: WebDriver, url: string) => {
  const handles = await driver.getAllWindowHandles();
  var currentHandle = '';
  if (handles.length > 1) {currentHandle = await driver.getWindowHandle();}

  for (const handle of handles) {
    try {
      await driver.switchTo().window(handle);
      const currentUrl: string = await driver.getCurrentUrl();
      if (currentUrl.startsWith(url)) {
        return true;
      }
    } catch {
    }
  }
  return false;
};
```

## Who will benefit from this feature
- browser functionality developers
- extension developers

**Comment by mxschmitt** [comment]
This looks similar to that: https://github.com/microsoft/playwright/issues/14876

Could you try if https://github.com/microsoft/playwright/issues/14876#issuecomment-1156687861 works for your use-case before we triage this further?

**Comment by KagamiChan** [comment]
@mxschmitt Thanks for the info, this looks working, I'm closing the issue for now
