### ISSUE TITLE
[Question]: How can we wait for API function Response in Playwright using JavaScript

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#17327]
[Question]: How can we wait for API function Response in Playwright using JavaScript, as wanted to wait till the API Response status is Completed for the task for which I am looking for.
**API Function**:
 async getTaskStatus(token, reponame, taskid) { 
          const getStatusResponse = await this.apiContext.get(config.baseapiurl + taskid,
         {
             headers: {
                 'Authorization':  'Bearer ' +token, 
                 'Content-Type': 'application/json'             
             },            
         })             
         const getStatusResponseJson = await getStatusResponse.json();
         return getStatusResponseJson.data;
     }

**Comment by AkkyLohana90** [comment]
Hello Team,

Any update on this?

**Comment by mxschmitt** [comment]
do you mean that you need to call your API multiple times and want to wait until the status is 200?

I don't follow the question, would be good if you could elaborate a bit more what you are trying to do.

**Comment by AkkyLohana90** [comment]
Yes, I need to call your above API function multiple times and want to wait until the jobStatus is **Completed**.
For that I am calling the API function in other function(**verifyDSLoaded**) multiple times.

async getStatus(token, taskid, reponame, dataId, dataName) {
for (let loopCount = 0; loopCount < 3; loopCount++) {
**this.verifyDSLoaded(token, taskid, reponame, dataId, dataName);**   // In this function I am calling API function
taskId += 1;
}
}

**Comment by mxschmitt** [comment]
You can either use a manual loop like you do or use polling, see here: https://playwright.dev/docs/test-assertions#polling

**Comment by AkkyLohana90** [comment]
Sure, will try the same.

**Comment by mxschmitt** [comment]
Closing as per above, should work. If not, please re-file and we'll take a look in the new issue.
