### ISSUE TITLE
[Question] How to change the browser language?

### ISSUE THREAD

**Issue by Quietscheentchen13** [microsoft/playwright#17326]
Hi all,

I have created a brand new project via the vs code extension. 
When I start example.spec.ts, keep the browser open and check the browser language, I get the following results:
chromium: browser language german
firefox/webkit: browser language english

My system language is german.

Changing ```locale:``` in the config file does not affect the results.

Is it possible to change the browser language? If yes, how?

**Comment by GunjanSheth** [comment]
it seems you are using JavaScript which i am not much familiar with, but i once tried the locale on python using the following.

`
with sync_playwright() as playwright:
    run(playwright)
    browser = playwright.chromium.launch(headless=False, channel='msedge')
    context = browser.new_context(locale="de-DE")
    page = context.new_page()
    page.goto("https://www.google.com")
    time.sleep(10)
`

I checked launching Google home page, it does open in German Language.
I'm sure you would find relevant code in node.js

![image](https://user-images.githubusercontent.com/110458975/190172829-922b5625-7c9b-4408-9c2b-559aa7dddd7e.png)

**Comment by Quietscheentchen13** [comment]
@GunjanSheth / @mxschmitt 
Thanks for your help, but it seems I was not clear enough, sorry. The question is not about the language of the site, it's just about the browser language. When I look at the the request and response headers, locale works fine (#17181), but is not affecting the browser language.

I tried, but were not able to change the browser language in code. I can change it in the settings, when the browser is open, but when I restart the test, it's back to default. It seems I am missing something or it's just not possible.
So it's really only about the question if it's possible to define the browser language somewhere in my code and if yes, how?

chromium (german):
![Screenshot](https://user-images.githubusercontent.com/108295847/190322435-0c1c2d74-d349-4b79-ad50-a359952a3f43.JPG)

firefox (english):
![ScreenshotFF](https://user-images.githubusercontent.com/108295847/190322880-0c5f9c1b-3da1-482e-86e6-6436f9dec300.JPG)

webkit (english):
![ScreenshotWK](https://user-images.githubusercontent.com/108295847/190322907-31e5f343-34d2-4bf8-a5c7-3691652ac703.JPG)

**Comment by mxschmitt** [comment]
Why do you care about the browser language? It does not affect the page web apis, and the one which are affected are adjusted by the locale emulation.

**Comment by Quietscheentchen13** [comment]
Hi @mxschmitt,
like I mentioned in #17181 we have the weird behavior that on our projects site, the browser language affects expected date/time formats in input fields and locale has no effect on these inputs. As I'm unable to share any code and locale is correct when looking at the network, changing the browser language would have been a workaround for now.

**Comment by mxschmitt** [comment]
> Hi @mxschmitt,
> like I mentioned in #17181 we have the weird behavior that on our projects site, the browser language affects expected date/time formats in input fields and locale has no effect on these inputs. As I'm unable to share any code and locale is correct when looking at the network, changing the browser language would have been a workaround for now.

This is not how the web works, your date control has to use some web apis, some Javascript apis etc. Unless we know which ones, we can't act on it. Changing the browser language is the wrong approach there. 

I recommend contacting a dev on your side to debug that further.

**Comment by Quietscheentchen13** [comment]
> This is not how the web works, your date control has to use some web apis, some Javascript apis etc. Unless we know which ones, we can't act on it. Changing the browser language is the wrong approach there.
> 
> I recommend contacting a dev on your side to debug that further.

Ok, thanks again for your time and help. I will close this issue.

**Comment by zomars** [comment]
BTW. Browser language DOES affect html form validation messages. Which may break some test across machines.

**Comment by davidenke** [comment]
> BTW. Browser language DOES affect html form validation messages. Which may break some test across machines.

It affects the chrome://settings and chrome://extension page locale as well.
Since the issuer stated that this works for webkit and firefox, I'd ask for reopening this issue.

In my case, I'm testing a browser extension and for that, using the extensions settings page is necessary.
