### ISSUE TITLE
[Feature] Update Dockerfile to have more flexible 'npx playwright install' command with options

### ISSUE THREAD

**Issue by demchuknick6** [microsoft/playwright#17333]
In my Dockerfile, I use a statement `FROM mcr.microsoft.com/playwright:v1.25.2-focal` which under the hood calls `npx playwright install --with-deps`, code here - https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.focal#L41.
This installs all available browsers to PLAYWRIGHT_BROWSERS_PATH directory, but I only want Chromium to be installed and have a smaller size of the image.

Is it possible to update the base image and use an argument or env variable so that I can set in my Dockerfile smth like this:
`ARG PLAYWRIGHT_INSTALL_OPTION=chromium`
`FROM mcr.microsoft.com/playwright:v1.25.2`

**Comment by mxschmitt** [comment]
This is not how Docker works, when you specify a Docker image via `FROM` it will pull the already built image, so the browser downloads and installation of dependencies has already happened. It happens on our side when we push it to the Microsoft Container Registry.

If you want a Docker image with only Chromium, we recommend building your own or starting from Ubuntu and doing `npx playwright install chromium --with-deps` inside which is for most use-cases enough and gives you a much smaller image.

**Comment by demchuknick6** [comment]
thank you for your suggestions
