### ISSUE TITLE
[Question] Do CSS combinators really pierce shadow DOMs?

### ISSUE THREAD

**Issue by jrpool** [microsoft/playwright#17338]
https://playwright.dev/docs/selectors#selecting-elements-in-shadow-dom says yes, but I am finding no.

A `body form` selector should find the `form` element in https://www.cvs.com/retail-easy-account/create-account?page=/account/signup.jsp&icid=cvsheader:createaccount&screenname=/, but it does not.

**Comment by mxschmitt** [comment]
For me it does: 

<img width="945" alt="image" src="https://user-images.githubusercontent.com/17984549/190371501-7acb4195-5258-4a9d-b545-5e8872178d44.png">

also via the inspector:

<img width="755" alt="image" src="https://user-images.githubusercontent.com/17984549/190371735-88bb0407-de85-4393-9c30-0c97425997f7.png">


could you provide us more code related input or a small script?

**Comment by jrpool** [comment]
Thank you, @mxschmitt. I have tested again, and this time, surprisingly, a locator returned by `page.locator('body form')` finds the `form` element inside the shadow root. I have no idea why the result differs from before. Sorry for the distraction!
