### ISSUE TITLE
[Question] - Use reporters with Jest + Playwright

### ISSUE THREAD

**Issue by kolodny** [microsoft/playwright#17342]
My use case is that I need to use Playwright in library mode (not `@playwright/test`) but I would like to be able to leverage the Playwright test reporters. Is there any way to hook those together? For example my test looks like this

```ts
// using `describe` and `it` from jest
describe('a test', () => {
  it('works', async () => {
    const page = await utils.getPage();
    await page.goto('...');
    await page.click('...');
    await page.waitForNavigation();
    expect(page.url()).toContain('/some-other-page');
  });
});
```

I understand if I need to call some additional code before or after each test block if necessary .

**Comment by mxschmitt** [comment]
This is not possible, we recommend migrating to Playwright Test instead, since it provides much more features like html report, retries, web-first assertions, visual studio code extension etc. You are missing out on developer experience!
