### ISSUE TITLE
[Question] alternative to test.afterAll that is guaranteed to execute only once after test suite

### ISSUE THREAD

**Issue by marinamelin** [microsoft/playwright#17340]
Hello playwright team!

We are migrating from jest test runner to playwright test runner. There was some custom functionality in all of our test suites that was sitting inside an afterAll block in each test suite.

We've noticed that in case if some of the tests failed in a test suite, test.afterAll will be executed multiple times (presumably after each failure). [This documentation](https://playwright.dev/docs/test-advanced#workerinfo-object) states: `For example, Playwright Test will always start a new worker process after a failing test.`

Due to the nature of the custom functionality, we need to have some mechanism to execute this code only once, and it must happen after all the tests in the test suite were executed regardless of their pass/fail status.

Could you please point what should be used in this scenario?

Alternatively, is there a configurable way to disable starting a new worker process after a failing test?

Thanks!

**Comment by rio-ap** [comment]
trying to help here

just use global teardown [official doc](https://playwright.dev/docs/test-advanced#global-setup-and-teardown) this function will only run 1 time. 

if you need something like reporting file from built-in reporter, create custom reporter contain only onEnd() function, and call it on the last order in config file [like this, note the log from my comment, global teardown only called once](https://github.com/microsoft/playwright/issues/17015#issuecomment-1238666661)

**Comment by mxschmitt** [comment]
As mentioned above, we recommend [globalSetup](https://playwright.dev/docs/test-advanced#global-setup-and-teardown) for that.

**Comment by marinamelin** [comment]
Global teardown appears to be called after all tests in all test suites are executed. Our old use case was to run the custom logic after all tests in each individual test suite were executed.

I think as part of the test runner migration this custom logic would have to be refactored to either run after each test or as part of the global teardown.
