### ISSUE TITLE
[Question] Pausing / stopping gifs for toHaveScreenshot

### ISSUE THREAD

**Issue by atlowl** [microsoft/playwright#17348]
Is there a way to pause or stop a gif in one state with playwright

The pages that i'm testing have some animated gifs on them that then fail periodically as it doesn't quite get the right state of the image.

Cheers

**Comment by GunjanSheth** [comment]
from the documentation it does seem you can pause / stop in a specific state.
but it can either be initial state or the last state

Below is the exact text
```
animations? <"disabled"|"allow"> When set to "disabled", stops CSS animations, CSS transitions and Web Animations. Animations get different treatment depending on their duration:[#](https://playwright.dev/docs/api/class-page#page-screenshot-option-animations)

finite animations are fast-forwarded to completion, so they'll fire transitionend event.
infinite animations are canceled to initial state, and then played over after the screenshot.
Defaults to "allow" that leaves animations untouched.
```

https://playwright.dev/docs/api/class-page#page-screenshot

does that help ?

**Comment by mxschmitt** [comment]
Stopping GIFs is not supported, afaik there is no Web API which is capable of doing that.

But what you can do is to mask out (hide the gif during the screenshot) the gif, toHaveScreenshot and the normal screenshot methods support all this option:

```
await expect(page).toHaveScreenshot({
  mask: [page.locator('your-gif-locator'],
});
// or
await page.screenshot({
  mask: [page.locator('your-gif-locator'],
})
```

See here: https://playwright.dev/docs/api/class-page#page-screenshot

**Comment by atlowl** [comment]
Ok - i see thats an issue bought up with webkit (from years ago) to have the ability to stop gifs playing. 
So because i've got text on top of the gif, i couldn't just mask it, as then i wouldn't see the text. 
Instead, i've deleted the gif before i take a screen shot.  Will leave it here for someone else who wants to make it more efficient.
```      
     let allGifs = await page.$$('img[src$=".gif"]');
      if (allGifs.length > 0) {
        /* Goodby-ski nasty moving gifs */
        await page.evaluate(() => {
          /* poof! */
          document.querySelectorAll('img[src$=\".gif\"]').forEach((gif)=>{gif.remove()});
        });
      }
```
