### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by sh977218** [microsoft/playwright#17359]
**Context:**
- Playwright Version: [^1.25.2]
- Operating System: [Mac]
- Node.js version: [v14.20.0]
- Visual Studio Code version: [1.71.1 ]
- Playwright for VSCode extension version: [v0.2.10]
- Browser: [Chromium]
- Extra: [N/A]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**
Hi, is there anyway I can start `Record from here` to open browser with some args, like `--disable-web-security`
Add any other details about the problem here.

**Comment by mxschmitt** [comment]
This is currently not possible, https://github.com/microsoft/playwright/issues/17330 is a very similar request, so I'll fold it into that. I described a workaround there, to first run a test, with the Show Browser option, and then record from there, which has the right browser, and context options opened. All taken from the playwright.config.ts

Folding into https://github.com/microsoft/playwright/issues/17330
