### ISSUE TITLE
[BUG] component testing in VS Code only shows last edited test

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#17358]
**Context:**
- Playwright Version: latest
- Operating System: Mac M1
- Node.js version: 16.6
- Browser: all
- Extra: VS Code extension

https://user-images.githubusercontent.com/13063165/190413590-3985e0d8-2bb1-43d4-89e8-37e175084f14.mov

Download repo and use VS Code extension to run component tests:
https://github.com/debs-obrien/component-testing-vue

**Describe the bug**

With show browser clicked run a test, browser will open, run another test, browser will probably show the test, go back to first test and browser will not the test you are now running but will remain on the last test edited. edit the test and run and it will show. 

Expected bahaviour is to to pick up the test that is being run and show that one rather than the last edited one.

Close all browsers and running a component test will not open a browser unless you actually run the test that was last edited. Then browser will open and show that test. If I close browsers and run another test it should open the browser for that test.

**Comment by debs-obrien** [comment]
Seems removing the cache folder has fixed this issue

**Comment by mxschmitt** [comment]
Should be fixed in 1.27 or @next once its released. Please re-open if not with repro steps.
