### ISSUE TITLE
[Feature] CLI command to get total number of tests cases

### ISSUE THREAD

**Issue by thekp** [microsoft/playwright#17365]
**Feature suggestion**

- Run `npx playwright <define directory || use current directory || test file path> --total-tests`
- The above command will then return the total number of tests cases 

**Example of what I mean by test case:**

```
  test("main navigation", async ({ page }) => {
    // Assertions use the expect API.
    await expect(page).toHaveURL("https://playwright.dev/");
  });
```

**My use-case:**

I am on planning on rapidly adding new tests to multiple test projects using Playwright, and I want to dynamically scale my run script in my CI pipeline. If I have the total test cases, then I can define that I only want 50 tests per shard and then do some "quick maths" like: `Maths(total_tests/50)` to get the max total shards I need for my CI at that given time.

**Alternative feature suggestion for my use-case**

Maybe you could enhance the `shard` flag to accept the max number of test cases a user wants in a shard and then it can dynamically generate the total shards required.

Thank you in advance for any response 🙏

**Comment by mxschmitt** [comment]
You can do `npx playwright test --list | wc -l` and strip some lines of, which are before and after, would that work as a workaround?

**Comment by thekp** [comment]
@mxschmitt I tried this command in my project, and it responded with the wrong number, it outputted `13` but I expected `6`
![image](https://user-images.githubusercontent.com/30599794/190575849-886b5197-0020-487a-a8f9-c79ba68f3ba2.png)

**Comment by mxschmitt** [comment]
Yeah that's what I mean with subtracting the header / footer lines. But actually it prints the right amount, so you can do it with grep: 

```
amount_of_tests=$(npx playwright test --list | grep -oh "Total: [0-9]* tests" | grep -o "[0-9]*")
echo $amount_of_tests
```

**Comment by thekp** [comment]
@mxschmitt Thank that has worked for me 💯
