### ISSUE TITLE
[BUG] Playwright fills out a test value into the wrong form field while testing a form submission

### ISSUE THREAD

**Issue by boldchains** [microsoft/playwright#17378]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.25.2
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] v16.16.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
test("admin can create/delete a user", async ({ page }) => {
    const firstName = faker.name.firstName();
    const lastName = faker.name.lastName();
    const userEmail = faker.internet.email(firstName, lastName);
    const password = "P@ssw0rd";

    // Admin user can create a user
    await page.locator("id=create-user-email").fill(userEmail);
    await page.locator("id=create-user-firstname").fill(firstName);
    await page.locator("id=create-user-lastname").fill(lastName);
    await page.locator("id=create-user-password").fill(password);
    await page.locator("id=create-user-password-confirm").fill(password);

    await page.waitForSelector("id=create-user-role");
    await page.locator("id=create-user-role").click();
    await page.locator(`li[role="option"]:has-text("User")`).click();
    await page.locator("id=create-user-button").click();
    await page.waitForURL(`/users`);

    // should have one row within the users list
    const rowSelector = `div[role="row"]:has-text("${userEmail}")`;
    await page.waitForSelector(rowSelector);
    await expect(await page.$$(rowSelector)).toHaveLength(1);
    const row = await page.locator(rowSelector);
    await expect(row).toContainText(userEmail.toLowerCase());
    await expect(row).toContainText(firstName);
    await expect(row).toContainText(lastName);
    await expect(row).toContainText("User");

    // delete user
    await page
      .locator(`div[role="row"]:has-text("${userEmail}") >> button`)
      .nth(1)
      .click();
    await page.locator("text=Confirm").click();
    await expect(await page.locator(rowSelector).count()).toEqual(0);
  });
});
```

**Describe the bug**

I detected some strange behaviour while filling out the multiple fields, it's not happening every time, but it does happened sometimes. Instead of filling out the password into confirm password field, it was filling out into user email field. What would make this happen?

**Comment by mxschmitt** [comment]
Does it happen with every browser? Can you provide us a repro which we can run locally? Your code looks good so far.

**Comment by boldchains** [comment]
It happens for only Chromium browser. Unfortunately, I am not able to share the repo with you

**Comment by mxschmitt** [comment]
Then we unfortunately have to assume that it's an issue within your application, if you are able to share a repro in the future, then feel free to file a new issue with it. closing for now since we can't act on it.

**Comment by Krisell** [comment]
Just wanted to add here that we were experiencing the same thing in a project and the reason was a delayed explicit autofocus (`document.getElementById('some-id').focus()` in a `timeout`). We solved that for now by skipping that when Playwright runs (and we know it's of course not ideal to make testing-specific changes to the app).

**Comment by guido-visser** [comment]
Our application does the same thing when a form appears, it gives focus to the first input field it finds (`element.focus()`). In most cases Playwright is later than the `focus()` event, in which case it works fine. However, sometimes Playwright is quicker causing a fill in an unwanted place.

Could there be some sort of implementation (or an event listener for the `focus` event) to wait until that first field is in focus (it's a generic field in my case, which makes it a bit more complex)?

@Krisell Could you share how you let the application know it was Playwright running? I've tested some with environment variables, but that doesn't seem to work. Much appreciated!

**Comment by Krisell** [comment]
> @Krisell Could you share how you let the application know it was Playwright running? I've tested some with environment variables, but that doesn't seem to work. Much appreciated!

Here's how we do that: https://github.com/microsoft/playwright/issues/9468#issuecomment-1403214587

**Comment by olavholten** [comment]
I have a similar problem when filling out a field and then using tab to trigger a server call. Sometimes, not always, the next field gets the value filled in even though we check that the value actually is there (getInputValue). The fill action seems to be running in a different thread, not caring about which field was in focus when the fill method was called.
