### ISSUE TITLE
[BUG] Cookies set via fetch are set with SameSite=Lax even if SameSite=None is set

### ISSUE THREAD

**Issue by Druckles** [microsoft/playwright#17398]
### Context

- Playwright Version: 1.25.0
- Operating System: Windows 10 10.0.19043
- Node.js version: 16.16.0
- npm: 6.14.5
- Browser: Chromium

### Describe the problem

I have a running server that sets a cookie, e.g.

```
JSESSIONID=1C51D7C238A1EE427CC92259C7A9D1F1; Path=/; Secure; HttpOnly; SameSite=None
```

Then I do a `fetch` against it, e.g. with:

```typescript
const response = await page.request.fetch('https://localhost:7443/');
```

The cookie should have `SameSite=None`, but `SameSite=Lax` is set instead. This causes problems if then using the cookies in a third-party context.

### Code snippet

The following test fails and it should pass:

```typescript
import {test, expect} from '@playwright/test';

test.only('A SameSite=None cookie is set to Lax', async ({page}) => {
    await expect(page.context().cookies()).resolves.toStrictEqual([]);
    const response = await page.request.fetch('https://localhost:7443/', {
        method: 'get',
        ignoreHTTPSErrors: true
    });
    const setCookieHeader = response.headersArray()
        .filter(({name}) => name.toUpperCase() === 'Set-Cookie'.toUpperCase())
        .map(({value}) => value);
    expect(setCookieHeader[0]).toContain('SameSite=None');
    const [cookie] = await page.context().cookies();
    expect(cookie.sameSite).toBe('None');
});
```

### Minimal reproducible example

I've created a repository here to help reproduce the problem: https://github.com/Druckles/playwright-samesite-none. It does the above but also includes an nginx server to simulate the `Set-Cookie` header.

### Other things I've tried

This may have something to do with other CORS headers or the domain used, but I have tried the following and none changed the outcome:

* Non-localhost domain, i.e. adding `www.example.com 127.0.0.1` to the `/etc/hosts` file.
* No port, i.e. running on the default port of 443.
* The following headers:
  * Access-Control-Allow-Credentials true;
  * Access-Control-Allow-Origin "localhost";
  * Access-Control-Allow-Headers "localhost";
* The above headers but with an IP address.
* Adding `credentials: "include"` to the `fetch` options.

What leads me to believe that this is a Playwright issue is that the cookie is actually set and Chrome throws an error and does not set the cookie at all if there are problems with the configuration.

Performing a fetch directly in Chrome (not in incognito mode and the above headers set properly) sets SameSite to None as you'd expect:

```javascript
fetch('https://localhost:7443', {credentials: 'include'})
```

**Comment by mxschmitt** [comment]
Thanks for your repro! An internal test would look like:

```ts
it('A SameSite=None cookie is set to Lax', async ({ page, server }) => {
  server.setRoute('/empty.html', (req, res) => {
    res.setHeader('Set-Cookie', 'JSESSIONID=1C51D7C238A1EE427CC92259C7A9D1F1; Path=/; Secure; HttpOnly; SameSite=None');
    res.end();
  });
  const response = await page.request.get(server.EMPTY_PAGE);
  const setCookieHeader = response.headersArray().filter(({ name }) => name.toLowerCase() === 'set-cookie').map(({ value }) => value);
  expect(setCookieHeader[0]).toContain('SameSite=None');
  const [cookie] = await page.context().cookies();
  expect(cookie.sameSite).toBe('None');
});

```
