### ISSUE TITLE
[Question] Public roadmap?

### ISSUE THREAD

**Issue by vitalics** [microsoft/playwright#17409]
Hi PW team. I see that some of the features are rejected by "out of scope for now" and I wonder about public roadmap for everyone, like in Typescript pinned issue about future versions. I think it will helps community to understand which features are coming to the next release.

**Comment by mxschmitt** [comment]
There is no public roadmap, we usually plan very short ahead, so the best is to monitor the issues for the next release which are marked with e.g. the `v1.27` label.

If you have feature ideas, we recommend filing them and once they have enough upvotes, we start working on them.
