### ISSUE TITLE
[Question]: How to reduce the docker image size?

### ISSUE THREAD

**Issue by cfancc** [microsoft/playwright#17408]
### Your question

I'm using mcr.microsoft.com/playwright/python:v1.20.1-focal-amd64 image, but after docker pull, I found it's size too large(1.8GB).Is there any way to reduce the size, actually I only use firefox driver inside.

![image](https://user-images.githubusercontent.com/7942955/190540982-26973f2c-e3d9-4c9e-90c8-6219d0951d81.png)

**Comment by mxschmitt** [comment]
Closing as per above! This works in all the language ports and is available in all the language port repositories.

**Comment by jw-star** [comment]
@cfancc @rwoll  hello, have you built it, because the build is not just a dockerfile, I don't know how to build it
