### ISSUE TITLE
[BUG] Occasional crash in Docker

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1741]
**Context:**
- Playwright Version: 0.13.0
- Operating System: Linux
- Extra: Docker on Jenkins - using `aslushnikov/playwright:bionic`

**Describe the bug**

Hey team. I'm seeing an occasional crash on Docker running on a Jenkins host. This only happens about 2% of the time, so I don't know how to create a consistently failing code snippet. I can share the logs with you though, and I'm using `{ dumpio: true }`.

```sh
Protocol error (Target.setAutoAttach): Target closed.

  at node_modules/playwright-core/lib/chromium/crConnection.js:123:63
  at CRSession.send (node_modules/playwright-core/lib/chromium/crConnection.js:122:16)
  at CRSession.<anonymous> (node_modules/playwright-core/lib/helper.js:87:31)
  at Function.connect (node_modules/playwright-core/lib/chromium/crBrowser.js:59:27)
  at Chromium.launch (node_modules/playwright-core/lib/server/chromium.js:44:53)
  at getBrowserPerProcess (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:58:33) # This is the call to launch()
  at CustomEnvironment.setup (node_modules/jest-playwright-preset/lib/PlaywrightEnvironment.js:107:31)

[err] Inconsistency detected by ld.so: ../elf/dl-tls.c: 481: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!
``` 

That last line in particular looks interesting. Any clue about what might be causing this or how I could create a repro case for this issue?

Thanks very much!

**Comment by celeryclub** [comment]
I guess it could be caused by this glibc bug, but I'm not sure if there's a recommended mitigation strategy. https://sourceware.org/bugzilla/show_bug.cgi?id=19329

**Comment by pavelfeldman** [comment]
@aslushnikov do we run our tests on aslushnikov/playwright:bionic ? We should see 2% on our tests.

**Comment by aslushnikov** [comment]
> do we run our tests on aslushnikov/playwright:bionic ? We should see 2% on our tests.

@pavelfeldman we run our tests in Docker on Circle CI. The crash though usually relates to some lack of resources, oftentimes memory shortage on the system. So I'd say it's very much host-dependent. 

> [err] Inconsistency detected by ld.so

@celeryclub I've never seen this error though - but it's unlikely it's on our end. Your bug reference looks relevant.

However, one it comes to page crashes in docker, some folks reported that running docker with extra shm size `--shm-size=` might make things better.

**Comment by aslushnikov** [comment]
We enabled Circle CI testing for all our PRs - so if there are crashes, we'll get to see soon'ish. For now, I don't think there's anything else we can do here.

If by any chance you find a good repro for this, please let us know - we'd be happy to look into it.

**Comment by celeryclub** [comment]
Thanks @aslushnikov. I added `--disable-dev-shm-usage` to my args. We'll see if that improves things.

**Comment by celeryclub** [comment]
@aslushnikov I'm still seeing the error occasionally even after adding the flag. Would it make sense to keep this issue open till we can get to the bottom it?

**Comment by celeryclub** [comment]
@aslushnikov Would you be able to share the source code for `aslushnikov/playwright:bionic`? I've switched to a different docker image and I'm seeing far fewer crashes (though still a few) and I'm curious to compare the two images.
