### ISSUE TITLE
[Question] How to get all tests that will be run?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#17428]
I am building a test runner and one of the requirements is that I need to know all tests that will be run.

I am not able to get individual test description when they start from `testInfo`, but is there a built-in way to get information about all tests that the runner is going to run?

**Comment by mxschmitt** [comment]
Why are you building a test-runner, Playwright is and has already a test-runner called Playwright Test!

**Comment by punkpeye** [comment]
> Why are you building a test-runner, Playwright is and has already a test-runner called Playwright Test!

Like a cloud test runner for Playwright Test.

**Comment by pavelfeldman** [comment]
This looks outside of the scope for Playwright Test, so you are on your own with this one!
