### ISSUE TITLE
Why does await chromium.launch work and chromium.launchPersistentContext fail?

### ISSUE THREAD

**Issue by pbains1** [microsoft/playwright#17420]
Why does this work?

    const browser = await chromium.launch({ headless: false });
    const browser = await chromium.launchPersistentContext('', { headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();

and this doesnt?
    const browser = await chromium.launchPersistentContext('', { headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();

In both cases the browser opens but when using chromium.launchPersistentContext the subsequent steps fail
I get the following errror:
TypeError: browser.newContext is not a function

   9 |     //const browser = await chromium.launchPersistentContext("", { headless: false });
  10 |     const browser = await chromium.launchPersistentContext('C:\Users\PB85371\AppData\Local\Chromium\User Data', { headless: false });
> 11 |     const context = await browser.newContext();
     |                                   ^
  12 |     const page = await context.newPage();
  13 |   
  14 |     //await page.goto('https://cdpn.io/celeryclub/debug/RwPogLo/GnAnbOZXLOnA');

**Comment by mxschmitt** [comment]
`launchPersistentContext` returns a [`BrowserContext` ](https://playwright.dev/docs/api/class-browsercontext)instance and not a [`Browser`](https://playwright.dev/docs/api/class-browser) instance see [here](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context).

So you can do:

```ts
const context = await chromium.launchPersistentContext('', { headless: false });
const page = await context.newPage();
// there is also a page by default created which you can use:
const page = await context.pages()[0];
```

We recommend to use TypeScript or use [`// @ts-check` ](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html)to spot the errors before you execute it.

**Comment by pbains1** [comment]
Hi Max,

That seems to work. Thanks.
