### ISSUE TITLE
[Question] How to use "firefoxUserPrefs" when working with "launchPersistentContext"

### ISSUE THREAD

**Issue by tapinomics** [microsoft/playwright#17442]
I am googling and experimenting for hours and I still cant find a working method to change Firefox config when working with persistent context.
For example every time I start the script and new (or old) persistent context is loaded I want to have 'browser.toolbars.bookmarks.visibility' set to 'always' and 'media.navigator.enabled' set to 'false'

Did anyone manage to do this? firefoxUserPrefs works well with browserType.launch([options]) but there is no working method when using browserType.launchPersistentContext(userDataDir[, options])

Thanks a lot in forward!

**Comment by aslushnikov** [comment]
@tapinomics  You should put `user.js` file in your `userDataDir` folder: http://udn.realityripple.com/docs/Mozilla/Preferences/A_brief_guide_to_Mozilla_preferences

**Comment by tapinomics** [comment]
> 

Thanks a lot for a quick reply! That did the trick!

**Comment by Mokto** [comment]
Is it still working for you?
Using python playwright latest version (1.28.0) and the user.js file is always overriden when using `user_data_dir`.

**Comment by Mokto** [comment]
Ok! 

I went through each past Playwright version and 1.28.0 is the only one where the file is overridden! 

1.27.1 works fine.

I think we should maybe reopen this issue?

**Comment by aslushnikov** [comment]
> I went through each past Playwright version and 1.28.0 is the only one where the file is overridden!

@Mokto Sorry, it'll be fixed in 1.29!

**Comment by Mokto** [comment]
Thanks a lot 👍
