### ISSUE TITLE
[Question] Sharing context between specs: good or bad?

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1745]
I chatted with @dgozman about this a bit here. https://github.com/playwright-community/jest-playwright/pull/96#issuecomment-608587152

I understand that in theory it makes sense to *not* share context, but the end result I'm seeing doesn't seem ideal.

When I share context:
```js
describe('editor/page', () => {
  it('can log in and create a site', async () => {});

  it('can create a page and add content', async () => {});

  it('can publish the site', async () => {});

  it('can delete the page', async () => {});
});
```

When I don't share context:
```js
describe('editor/page', () => {
  it('can create a site, add a page, add content, publish, and delete the page', async () => {
    // Create a site
    [some code here]

    // Create a page
    [some code here]

    // Add content
    [some code here]

    // Publish
    [some code here]

    // Delete the page
    [some code here]
  });
});
```

I find the code a bit easier to read in the first example, and the output in Jest looks a bit nicer too. Do you have any thoughts about how to achieve clearer code and output without sharing context?

Thanks!

**Comment by pavelfeldman** [comment]
This opens a set of interesting questions and challenges, so thank you for bringing it up. It is clear how the first snippet reads better, but it also is clear how it is not great formally - when the first test fails, there is no point in running the subsequent ones.

I bet that's not the only `describe` where you log in and you can't inherit state in the subsequent test, so you inevitably come up with the page object model for your site that can log in, create pages and publish them. You will be testing deleting this page before editing, after editing, while editing in the separate tests. So in order to reuse all that code, I'm convinced that you would have these helper methods. Do you think this is a fair assessment?

If that is the case, here is the way it would look:

```
describe('editor/page', () => {
  it('can log in and create a site', async () => {
    expect(await pom.login()).toBeTruthy();
  });

  it('can create a page and add content', async () => {
    expect(await pom.createPageAndContent()).toBeTruthy();
  });

  it('can publish the site', async () => {
    expect(await pom.createPageAndContent()).toBeTruthy();
    // publish the site code that is unique to the test
  });
  ...
});
```

Which brings a question if we can speed it up, along the lines you were discussing with @dgozman. But let's not go there for now and validate this initial assessment that you will end up having the page object model.

**Comment by celeryclub** [comment]
Yes I think it's a fair assessment that I'd need some kind of helper methods. But I'm not sure my code would look like the example code you posted above.

What if test 3 depends on the state from test 2, and test 2 depends on the state from test 1 (as it appears to)? In that case, what's the point of running all three instead of just the last one? It seems like you're just testing partial behavior in the first two, and the full behavior in the last one.

**Comment by aslushnikov** [comment]
What is the status of this discussion? Is this still relevant?

**Comment by celeryclub** [comment]
I still haven't come up with a great answer for this. For now what I'm doing is this:

1. Grouping all tests that depend on one another into one very large test with a long name
2. Logging individual actions so that developers can see the current status of the run and quickly identify problems

I don't love this because I end up with very long test names in order to include everything that's happening in the test, and the test output doesn't contain any grouping of related actions. That being said though, I don't have a better idea for how to fix this at the moment. I think some type of test group support would be great for this, but that's a lot of work and I'm not sure this is an area of focus for you.

Up to you whether you'd like to keep this open based on if this is an area of interest to the team. Thanks for checking in!

**Comment by aslushnikov** [comment]
@celeryclub I see! This is more about test running rather then browser automation, so probably falls outside of the scope of this project.

But! We're looking into different test runners as well, so thank you for the input! I'll close this right now, but we might get back to you eventually if we get more questions.

**Comment by dgozman** [comment]
> 1. Grouping all tests that depend on one another into one very large test with a long name

Why do you need a longer name? I think it should be the same to the "suite name", assuming the opposite way of running multiple tests sharing a single context in a single suite.

> 2. Logging individual actions so that developers can see the current status of the run and quickly identify problems

Yeah, something like `step('sign in')` seems to be useful in this scenario, ideally with some support from test runner.

```js
test('todos screen', async () => {
  step('sign in');
  ...
  step('add todo');
  ...
  step('mark todo as checked');
  ...
  step('remove todo');
  ...
});
```

**Comment by celeryclub** [comment]
Fair point @dgozman. I think the name isn't a huge issue. But some kind of step delineator would be really nice.
