### ISSUE TITLE
[BUG] tsconfig-loader tries to load non-existing tsconfig causing the correct config not to be used

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/playwright#17469]
**Context:**
- Playwright Version: 1.23.1
- Operating System: Windows 10 x64
- Node.js version: 16.17.0
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

```typescript
import { Environment } from '@oas/internal-lib-e2e';
```

**Describe the bug**

I'm unable to import my monorepo package using TypeScript paths in the runner's child process (it works in the main process).
![image](https://user-images.githubusercontent.com/5993909/191313053-a7078b25-c9ba-4581-955e-31ccc61f2a28.png)

After a debugging session with myself here: https://github.com/microsoft/playwright/discussions/17466, i have come to the conclusion that the tsconfig-loader (https://github.com/microsoft/playwright/blob/29ff00ead2e79ea9b5374513f98801745e93b80c/packages/playwright-test/src/third_party/tsconfig-loader.ts#L60) is trying to resolve a `tsconfig` that doesn't exists and then try to use that instead of the correct one in the package root (process.cwd() in the main process).

So here it is resolving a non-existent tsconfig file:
![image](https://user-images.githubusercontent.com/5993909/191314190-4eee2139-f632-45a9-8515-9a283c6b5089.png)

And then it's using that in the child process instead of the correct one with the paths:
![image](https://user-images.githubusercontent.com/5993909/191314277-6f007f52-f009-41c8-8387-c09ceea8e9a0.png)

Since the `cwd` for the `child process` is the `testDir` from the config file, and not the `package root`, no matter what I do, I will have to wrong path since I use `./tsconfig.json` as `TS_NODE_PROJECT`.  It will always be resolved to the wrong path.
My guess is that you do not want to return a non-existent `tsconfig.json` or return it but then don't cache it in `loadAndValidateTsconfigForFile` here: https://github.com/microsoft/playwright/blob/42491ecc0867129b97fa2fbd4fe9c58ff0d3feff/packages/playwright-test/src/transform.ts#L79

**Comment by JonWallsten** [comment]
Hmm, creating a repro would take a lot of time since we have a pretty complex setup involving a monorepo and multiple packages. 
I can try to create a PR instead with a solution to the problem.

**Comment by JonWallsten** [comment]
So I have a repro here:
https://playwright-repro-tsconfig.stackblitz.io

Instructions:
1. Download source from Stackblitz
2. Run `npm i` in the root.
3. Go to `packages/app`
4. Run `npm run playwright:debug`
5. Open DevTools for Node
6. Set breakpoint in `test.spec.ts` on line 2.
7. Step into these functions: 
![image](https://user-images.githubusercontent.com/5993909/191430038-a35291f1-475d-47c2-9626-f00eedd794fc.png)
8. Profit!

I would say the main issue here is that it's using `cwd` instead of `process.cwd()` when trying to resolve the `tsconfig.json`, unless you guys are deliberately looking for `tsconfig.json` files in the test suite?

![image](https://user-images.githubusercontent.com/5993909/191431316-ddb624d2-3023-4d65-95d3-6fb6c54bb01d.png)


I mean, I specify the `TS_NODE_PROJECT` relative to the `process.cwd()` in my `package.json`, so I don't see a point looking relative to the `testDir`? BUT, if you guys really want to look for a `tsconfig.json` in the `testDir` (from Playwright config) you should at least not stop if it doesn't exists. Then you should move up the tree stopping when you find one. 
I don't think it's a bad idea caching the result here:

![image](https://user-images.githubusercontent.com/5993909/191432182-ea989f66-e46d-48c2-a748-fc73519f2510.png)

But you should not cache `undefined` for a path just because the `tsconfig.json` does not exist in that exact folder.
![image](https://user-images.githubusercontent.com/5993909/191433538-199546bc-65a2-4581-9c93-b44c24284789.png)

So I guess one of these two solutions should be implemented:
The static way: Either always use `process.cwd()` when you use `TS_NODE_PROJECT` to to resolve the `tsconfig.json` so I have control of it.
The dynamic way: Try resolving `tsconfig.json` with `cwd` first, if it does not exists, either move up the file tree until one is found,  or fallback to `process.cwd()` depending on how dynamic you want to be.

The current solution of only using a `tsconfig.json` if it exists in the `testDir` is probably not a good solution.

**Comment by pavelfeldman** [comment]
When resolving config for the TypeScript file, resolution is based on the filesystem nesting, so I'm not sure why cwd is used. We are inheriting this logic from tsloader, so we should have probably cleaned it up further.

**Comment by dgozman** [comment]
@JonWallsten Thank you for the PR! Before we proceed, I'd like to clarify a few things:

1. Looking at the repro, it seems like you are running playwright with `ts-node`:
```
cross-env TS_NODE_PROJECT=./tsconfig.json node -r ts-node/register -r tsconfig-paths/register --inspect-brk ../../node_modules/@playwright/test/cli test
```
I don't think this is supported. Playwright supports TypeScript out of the box, and so does its own processing. If you use `ts-node`, there are no guarantees anything would work.

Could you please try without `ts-node`, with built-in TypeScript support? If that somehow does not work for you, we recommend [compiling manually as a last resort](https://playwright.dev/docs/test-typescript#manually-compile-tests-with-typescript).

2. Do you use `TS_NODE_PROJECT` just to configure `ts-node`? I think it's a mistake this variable is respected by 
Playwright, and we should drop that.

Let me know what you think.

**Comment by JonWallsten** [comment]
@dgozman: Oh, I did not know that. I just assumed TS-node was needed. My bad! I'll try the same thing without it. 
I can tell though, that besides failing reading `tsconfig.json` causing `paths` not to work, everything works fine. But if you support TypeScript there's really no point in running ts-node, just adds another layer of complexity. 

I use `TS_NODE_PROJECT` to point to a specific tsconfig (`tsconfig.e2e.json`) instead of the default one.

I'll try without ts-node and check if I get a different result.

**Comment by JonWallsten** [comment]
@dgozman: I have removed the ts-node part, but it didn't change the outcome. It still uses the wrong directory to resolve  `tsconfig.json`. And the fix I did still solves it. The good thing is that since it didn't change the outcome I really don't need ts-node for this. Thanks for that!

![image](https://user-images.githubusercontent.com/5993909/192455203-13bee9b4-b13f-4b81-af32-b612183a65de.png)

**Comment by JonWallsten** [comment]
Related issue: https://github.com/microsoft/playwright/issues/12829

**Comment by dgozman** [comment]
@JonWallsten You should stop passing `TS_NODE_PROJECT` environment variable. As I said, it unfortunately confuses our tsconfig loader, and we'll remove it from future releases. If you do that, tsconfig should be resolved to the closest config next to the source/test file. Let me know if that works for you.

**Comment by JonWallsten** [comment]
@dgozman But then it won't find my `tsconfig.e2e.json` since it will only look for `tsconfig.json`. I have a feeling you guys really don't want to support this, but I don't understand why? It's supported in the rest of the tools we use and it was supported in protractor, which we are replacing.

**Comment by dgozman** [comment]
@JonWallsten We would like to understand the scenario to make an informed decision. If you have a usecase that does not work, we would be happy to help you!

In the stackblitz repo above, I don't see the `tsconfig.e2e.json` file, so I am lost. Could you please explain what are you trying to achieve, what files do you have, what configs, and which config should apply?

For the reference, we usually have a root `tsconfig.json` that configures the source, and also put a separate `tests/tsconfig.json` file that has some test-specific options. This setup just works for us. That said, if this does not work for you, we would love to know why.

**Comment by JonWallsten** [comment]
@dgozman: I did some tests, and there seems to be an issue that you guys don't adress that TS-node does, that causes our tests to fail. It's related to, but not directly caused by this issue (I think you can stately remove the ts-node related stuff).

The issue is in: https://github.com/microsoft/playwright/blob/9f17ee68719c75abbe3fdfce2ffecf8d032d47a3/packages/playwright-test/src/transform.ts#L96:

When using a monorepo, we uses paths to point to the different packages. But we're pointing to the dist folders. And the dist folders contains the compiled and bundled code in js-format. 
And since you guys are only loading the `tsconfig` file for `TypeScript` files it can't resolve our packages if they are linked in another package.

As you can see in the image below, it processes `internal-lib-e2e` and that in turn uses our `web-lib-core`. 
But it can't resolve `web-lib-core` since our `paths` are missing because it doesn't read the `tsconfig` since it's not a TypeScript file.
![image](https://user-images.githubusercontent.com/5993909/192975590-7f758a65-c2f9-4920-b4ae-1c264532355f.png)

So is there any other way of providing these paths?

**Comment by dgozman** [comment]
@JonWallsten If I understood you correctly, you want paths from `tsconfig.json` to apply when `require`'ing from a compiled `.js` file? This is not something Playwright supports, because it assumes that compiled code is ready to run "as is".  I see that `ts-node` transforms javascript files when `allowJs` is set in the config, but I am not sure we should go this way. Perhaps you could point your paths to the source directory instead of the dist directory?

**Comment by JonWallsten** [comment]
@dgozman: Yeah, exactly. I point my `paths` to the dist-folder in each package so it mimics the behavior of being a regular installed dependency. But since they are not located in `node_modules` they can't be resolved without `paths`.
This works great for one level of imports. TS-file requiring bundle in JS from one of my packages.
But when a TS-file is requiring one of my bundles, and that bundle is requiring another bundle, it fails, since you guys don't apply that `paths` unless the file requiring is a TypeScript files.
This is really just a monorepo-issue, albeit still an issue.

I can definitely try to point to the source. But that might not work in our CI-environment. 
And since you guys are removing support for `TS_NODE_PROJECT` I can't use different `tsconfig.json` for different environments.

Hopefully we can use [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) for this though. I think the idea is to always have the paths available in the process.

**Comment by tytusplanck-8451** [comment]
> @dgozman: Yeah, exactly. I point my `paths` to the dist-folder in each package so it mimics the behavior of being a regular installed dependency. But since they are not located in `node_modules` they can't be resolved without `paths`. This works great for one level of imports. TS-file requiring bundle in JS from one of my packages. But when a TS-file is requiring one of my bundles, and that bundle is requiring another bundle, it fails, since you guys don't apply that `paths` unless the file requiring is a TypeScript files. This is really just a monorepo-issue, albeit still an issue.
> 
> I can definitely try to point to the source. But that might not work in our CI-environment. And since you guys are removing support for `TS_NODE_PROJECT` I can't use different `tsconfig.json` for different environments.
> 
> Hopefully we can use [tsconfig-paths](https://www.npmjs.com/package/tsconfig-paths) for this though. I think the idea is to always have the paths available in the process.

I'm also in a monorepo environment where some `tsconfig.json` point to the dist vs. the actual source for testing/usage as a consumer or ourselves. Ideally, it would be awesome if we could pass `tsconfigPath` to the `PlaywrightTestConfig` option rather than assuming the path automatically.

**Comment by dgozman** [comment]
I discussed this issue with the team and we arrived to the following:

- Removing TS_NODE_XXX env variables support, because we are not following `ts-node` semantics.
- Do not respect tsconfig for javascript files as we do today.
- Recommend a separate `tsconfig.json` in the `tests` directory for any test-specific path mappings.

Overall, Playwright assumes that each file is either:
- A typescript source. In this case Playwright transforms it and respects tsconfig.
- A javascript file. In this case Playwright assumes it's ready to load as is.

If you have a question or need help with your setup, please share your repro and we'll try to help as we can.
If you believe there is still a problem, please file a new issue with a repro and link to this one.
