### ISSUE TITLE
[BUG] Test no longer behaves as expected after inspecting on webkit

### ISSUE THREAD

**Issue by mjhenkes** [microsoft/playwright#17480]
**Context:**
- Playwright Version: 1.26.0
- Operating System: Mac
- Node.js version: 16.14.2
- Browser: Webkit
- Extra: [any specific details about your environment]

**Code Snippet**

This is a modified version of the example test provided by the playwright starter project.

```javascript
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // After inspecting routes are no longer captured
  page.context().route('**', (route, request) => {
    console.log('route', route)
    console.log('request', request)
  })

  await page.waitForTimeout(10000)

  // Open inspector in webkit browser (i tried opening it in the test with the keyboard command of 'Meta+Alt+I', but no luck. I wonder if the browser is prevented from doing that.)

  // create a locator, the locater is created but the href attribute will be blank when checked.
  const getStarted = page.locator('text=Get Started');

  // While clicking is successful, the expected url is actually a blank string.
  page.click('text=Get Started')

  // Expect an attribute "to be strictly equal" to the value.
  // await expect(getStarted).toHaveAttribute('href', '/docs/intro');

  // Click the get started link.
  // await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Describe the bug**

When running tests in webkit, after launching the inspector in the webkit browser, the test no longer functions as expected.

routes are no longer captured, locators have blank href values and behave strangely when clicked.

It seems like something happens to the context when the inspector is launched.

This is the command I used to recreate: 
`npx playwright test --headed --project=webkit`

after launching the test, i would right click and inspect the dom during the 10 second wait.

**Comment by mjhenkes** [comment]
@rwoll, thanks for looking into this. As far as I this has never worked for me, which matches up with what you've discovered.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
