### ISSUE TITLE
[Question] Capture "retina" quality screenshot

### ISSUE THREAD

**Issue by bytasv** [microsoft/playwright#17501]
Hello,

I'm trying to use playwright to capture screenshots of my application, I got it working, however the quality of the screenshot is lower than on my laptop (MBP). I'm wondering if there is a way to instruct library to use a different `devicePixelRatio` so that the screenshots would be "crispier"?

I went through GH issues, searched documentation, looked for answers on SO but couldn't find anything to sort this out.

Is this even possible? If yes, how could I do it?

Thank you

**Comment by bytasv** [comment]
Oh right, I should have mentioned what I've already tried - I did add this option to the global `playwright.config`:
```
const config: PlaywrightTestConfig = {
  ...
  use: {
    ...
    deviceScaleFactor: 2
  },
  ...
};
```
But that didn't seem to have any effect either I was missing something to get it working

**Comment by bytasv** [comment]
I'm using following:

```
  await page.screenshot({
    path: 'playwright-screenshots/app.png',
    fullPage: true,
    scale: 'device',
  });
```

Here is the actual code https://github.com/mui/mui-toolpad/pull/1045/files#diff-28cdd2e975ead9fbc15c1a1bb12a6912bbad188e786ed0b4f83c331836a1c096R16

And I also set `deviceScaleFactor: 2` in the main config https://github.com/mui/mui-toolpad/pull/1045/files#diff-59e49ab960c74ab53a6d4ce13cb625ff7bf038521bcd34a3a278252f5dc145aeR10

**Comment by bytasv** [comment]
@aslushnikov thanks a lot! that did help 👍

I'm just wondering then - whether the docs need to be clarified, implementation fixed or I simply misunderstood the documentation: https://playwright.dev/docs/api/class-testoptions#test-options-device-scale-factor 🤔 

I was under the impression that setting this option in the main config file would make it use option for all tests by default

**Comment by aslushnikov** [comment]
@bytasv well, the following works for me as well:

```ts
// playwright.config.ts
const config = {
  use: {
    deviceScaleFactor: 2,
  },
};

export default config;
```

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('desktop dimensions', async ({ page }) => {
  await page.goto('https://example.com');
  await page.screenshot({
    path: 'img.png',
  });
});
```

So I'm curious what exactly went wrong in your code and wether it's a Playwright bug or some coding issue on your side.

**Comment by aslushnikov** [comment]
It looks like there's no action item here from the team, so I'll close this.

Please do not hesitate to file new issues if something doesn't work or you have questions!

**Comment by bytasv** [comment]
@aslushnikov thanks a lot for help, I will check and figure out what's wrong with the setup on my end. For now it's more than enough that specifying that per test works 👌
