### ISSUE TITLE
Module not found with component testing

### ISSUE THREAD

**Issue by olivier65** [microsoft/playwright#17503]
Playwright Version: 1.26.0

I have this project structure:
```
project_root
  node_modules
  src
    layouts
      Header.tsx
  playwright-ct-test
    layouts
      Header.test.tsx
```

In `playwright-ct.config.ts` `testDir` is set to `./playwright-ct-test`. When I run `npx run test-ct` I get 
```
Error: Cannot find module 'geojson'
Require stack:
- <project_root>\src\measurement\types.ts
- <project_root>\src\user\types.ts
- <project_root>\src\user\userReducer.ts
- <project_root>\src\rootReducers.ts
- <project_root>\src\configureStore.ts
- <project_root>\playwright-ct-test\layouts\Header.spec.tsx
- <project_root>\node_modules\@playwright\test\lib\loader.js
- <project_root>\node_modules\@playwright\test\lib\runner.js
- <project_root>\node_modules\@playwright\test\lib\cli.js
- <project_root>\node_modules\playwright-core\lib\cli\cli.js
- <project_root>\node_modules\playwright-core\cli.js
- <project_root>\node_modules\@playwright\test\cli.js

   at ..\src\measurement\types.ts:1

> 1 | import { Feature, Point } from 'geojson'
    | ^
```

Now of course `@types/geojson` is installed (the application works fine). Why cannot Playwright or Vite resolve this module?

**Comment by pavelfeldman** [comment]
The fact that your application works suggests that it was available to your bundler. It is not available to Node though, so it would be interesting to get a minimal repro for that.

**Comment by aslushnikov** [comment]
> What could I do to debug it locally?

@olivier65 I'd recommend slowly removing code from the complicated app until the problem stops reproducing to pin-point to the code segment that is at fault!

I'll close this for now. Please do not hesitate to open a new issue if you think we still can be helpful to you!
