### ISSUE TITLE
How to use Axios inside page.evaluate - Error: Evaluation failed: ReferenceError: Axios is not defined

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#1751]
Hi Team, 

I am trying to downalod file behind Site Logins with Axios, does not work. I am getting Error: Evaluation failed: ReferenceError: Axios is not defined.

```
const { chromium} = require("playwright");
const fs = require("fs");
const Axios = require("axios");
....
....
....
for (let val of listings) {
    const downloadUrl = val.URL;
    const name = val.Filename;


    const downloadedContent = await page.evaluate(async (downloadUrl) => {
      const response = await Axios({
        url: downloadUrl,
        method: "GET",
        headers: {
          "Upgrade-Insecure-Requests": "1",
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
      Chrome/80.0.3987.163 Safari/537.36",
          "Sec-Fetch-Dest": "document",
          Accept:
            "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
        },
        withCredentials: true,
      });


      return response.data;

    }, downloadUrl);

    fs.writeFile(`./${name}`, downloadedContent, () =>
      console.log("Wrote file")
    );
```
I have another function - fetch . This function works inside page.evaluate, can download and save file (also behind Site Logins because of { credentials: "include" } ) -> Problem is files are corrupt. I do not why. I am not able to open file. For CSV it works.

```
const { chromium} = require("playwright");
const fs = require("fs");
.....
.....
const downloadedContent = await page.evaluate(async (downloadUrl) => {
    const fetchResp = await fetch(downloadUrl, { credentials: "include" });
    return await fetchResp.text();
  }, downloadUrl);

  fs.writeFile(`./${name}`, downloadedContent, () =>
  console.log("Wrote file")
```

I tryed also to call external function :

```
const { chromium, webkit } = require("playwright");
const fs = require("fs");
const Axios = require("axios");
const download_function = require("./download_function");
 ....
....
 ....
for (let val of listings) {
     const downloadUrl = val.URL;
    const name = val.Filename;
 
 const downloadedContent = await page.evaluate(
       async (Filename, downloadUrl) => {
         const downloadfile = await download_function.downloadFileAxios(
           name,
           downloadUrl
         );
       },
       name,
       downloadUrl
     );
```

and in external function i have:

```
const fs = require("fs");
const Path = require("path");
const Axios = require("axios");

async function downloadFileAxios(Filename, URL) {
  const url = `${URL}`;
  const path = Path.resolve(__dirname, "images", `${Filename}`);
  const writer = fs.createWriteStream(path);

  const response = await Axios({
    url,
    method: "GET",
    headers: {
      "Upgrade-Insecure-Requests": "1",
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
      "Sec-Fetch-Dest": "document",
      Accept:
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    },
    responseType: "stream",
    withCredentials: true,
  });

  response.data.pipe(writer);

  return new Promise((resolve, reject) => {
    writer.on("finish", resolve);
    writer.on("error", reject);
  });
}
exports.downloadFileAxios = downloadFileAxios;
```

how can i call axios inside page.evaluate with param: withCredentials: true and download files behind login page?

Thanks in advance for your help.

**Comment by mxschmitt** [comment]
Hey,
basically the evaluation functions work only with JavaScript which is directly inside of the passed function. (Under the hood it basically uses toString()).

So if you try to call external functions, imports/require statements, it does not work.

Regarding your axios question, here is some example maybe it helps: https://try.playwright.tech/?s=gvdfa

**Comment by osmenia** [comment]
Hi mxschmitt,
thanks a lot for your reply
https://try.playwright.tech/ looks very nice. 

it means i am not unable to start function in the browser. 
But why does fetch function work? because it is part of the browser function or? fetch function can only download text. 
I tryed `return await fetchResp.ArrayBuffer() and return await fetchResp.blob() `
i couldn't download the excel file

https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch

then what options do i have to download the file?

I was also thinking about to get the cookies from the browsercontext and then put them in axios request. Unfortunately I don't know how to put cookies into axios request.
something like this (see code below)-> I tried, does not work. 

```
const { chromium} = require("playwright");
const fs = require("fs");
const Axios = require("axios");
const download_function = require("./download_function");
....
....
const cookies = await crContext.cookies();
  console.log(cookies);

 for (let val of listings) {
    const downloadUrl = val.URL;
    const Filename = val.Filename;
    console.log(val);

        const downloadfile = await download_function.downloadFileAxios(
          Filename,
          downloadUrl, cookies 
        );
```

and in the external function:

```
async function downloadFileAxios(Filename, URL, cookies) {
  const url = `${URL}`;
  const path = Path.resolve(__dirname, "images", `${Filename}`);
  const writer = fs.createWriteStream(path);

  const response = await Axios({
    url,
    method: "GET",
    headers: {
      "Upgrade-Insecure-Requests": "1",
      "User-Agent":
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36",
      "Sec-Fetch-Dest": "document",
      Accept:
        "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
Cookie: `${cookies}`
    },
    responseType: "stream",
    withCredentials: true,
  });

  response.data.pipe(writer);

  return new Promise((resolve, reject) => {
    writer.on("finish", resolve);
    writer.on("error", reject);
  });
}
exports.downloadFileAxios = downloadFileAxios;
```

**Comment by arjun27** [comment]
Hi @osmenia, I'm curious to know if you were able to use the `download` event in Playwright ([docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-download)). This would look like

1. navigate the page to the right place
2. click an element (or some other action on the UI) to trigger the download
3. use the `page.on('download')` event to use the downloaded file

Would something like this work for your use-case? Curious to know if there are benefits to using `fetch` instead of this.

**Comment by osmenia** [comment]
> Hi @osmenia, I'm curious to know if you were able to use the `download` event in Playwright ([docs](https://github.com/microsoft/playwright/blob/master/docs/api.md#event-download)). This would look like
> 
> 1. navigate the page to the right place
> 2. click an element (or some other action on the UI) to trigger the download
> 3. use the `page.on('download')` event to use the downloaded file
> 
> Would something like this work for your use-case? Curious to know if there are benefits to using `fetch` instead of this.

download event is very good and useful. Specialy for download without link. Does the download event only download file if a click is made? 

Problem: I have about 220 documents on one page that I would like to download automatically. Each document has a version Name and a minimum of 4 languages (as drop down). I have to select language and download dociument for this language.

Only one File (language) is visible while the others are hidden. I looked at the html structure, there is already a link (href) for each file. So it would be much easier to download the files via request. 
If i use download event then i would have to choose the language first then click download file. If i have 220 File with 4 Languages = 880 clicks to select a language. it is not necessery

Does the download event support the download file via the link. And how to create custom file name in download event?

my idea is to use axio to download the file if there is a file link on the web page. It works very well for public pages. 
The problem is, I have to log in with playwright first and then get cookies from page and pass cookies to axios. Handing cookies to axio is not easy. The Fetch function is much easier to run within page.evaluate and cookies are immediately accepted. But with fetch i can only download text file. Not excel pdf

**Comment by pavelfeldman** [comment]
@osmenia : that depends on what you are testing or automating. If you simply need to fetch all these files from the server for some kind of an automation scenario, you can use Playwright to scrape the hrefs from these links using the single `const links = await page.$$eval(...)` call. At this point, you don't need the browser, you can simply download those from Node using `axio` or other `fetch` implementation. If you need cookies for that, `await browserContext.cookies()` is there for your.

If you are testing the page and want to make sure the user gets files downloaded, you should click them. You don't need to select the options, you can `await page.click(selector)` or you can `await page.evaluate()` to get yourself a bunch of the element handles. Then you `await handle.click()` them all in a loop and each of those will kick the download started.

**Comment by osmenia** [comment]
hi Team, 

tnx a lot!
