### ISSUE TITLE
[Feature] Allow test.step() to receive "failed" status to display step as failed inside of report.

### ISSUE THREAD

**Issue by 7artur7** [microsoft/playwright#17534]
Currently if `soft assertion` fails inside of `test.step()` test step remains with passed checkmark icon near of it.

It would be helpful if user could mark `test.step()` as failed programmatically, so it would be more clear in report that assertions inside of the step are failed. 

![2022-09-22_16-10](https://user-images.githubusercontent.com/22345107/191755993-21f73050-ae0b-45f0-b3b8-4659572e51d1.png)

**Comment by klhex** [comment]
Is this a duplicate to https://github.com/microsoft/playwright/issues/16904?

**Comment by 7artur7** [comment]
@klhex very similar. In #16904 it is proposed to mark such step automatically. In current ticket - I propose to do it programmatically, when user can select whether he wants to mark this step as failed or remain it as passed, this adds more flexibility. But the solution from #16904 should work as well.

**Comment by dgozman** [comment]
Now that #16904 is completed, I will close this issue as well. You can always fail the step programmatically with a fake expect:

```js
await test.step('step', async () => {
  // ...
  expect.soft('mark this step as failed').toBe('');
});
```
