### ISSUE TITLE
Why I am unable to use any fixture in side global Setup.ts

### ISSUE THREAD

**Issue by madhuRath** [microsoft/playwright#17550]
After using any fitures (page/ browser) i am getting  page.goTo() is not a function
Please find my code snippet below:
async function globalSetup(page: Page) {
  
    await page.goto('Some URL')
    await page.close()
}

By using browser fixture, i am getting the same type of issue.

**Comment by madhuRath** [comment]
Thank you for the quick update.

**Comment by pavelfeldman** [comment]
Starting with v1.31 you'll be able to shape your global setup as a Playwright project: https://playwright.dev/docs/next/api/class-testproject#test-project-dependencies. You can use the fixtures there.

**Comment by dgozman** [comment]
Closing per above.
