### ISSUE TITLE
[Feature] Add waitFor in ElementHandle

### ISSUE THREAD

**Issue by flintliu** [microsoft/playwright#1755]
When we move to Vue.js or React, I found the page object is not good enough because of the large number of reusable components. So I added the component layer on the top page object to reduce the work of creating a new test. Because of that, to have a waitFor function in ElementHandle will be super useful.

**Comment by pavelfeldman** [comment]
Could you share a bit more about your component layer and expectations regarding the `handle.waitFor`, which even would you like it to wait for?
