### ISSUE TITLE
[Feature] Allow async reporter

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#17569]
`onBegin`, `onTestBegin`, `onTestEnd` and `onEnd` should allow returning promises.

This is needed when the intent is to submit results to an external service.

This process typically involves:

* authenticate with the remote service (`onBegin`)
* record start of test (`onTestBegin`)
* record test result (`onTestEnd`)

All above steps require making HTTP request and waiting for a response to ensure everything is working as expected.

At the moment, the options are:

* Have a dangling promise that might fail during test execution
* Use hacky solutions that block the event cycle until, e.g. [deasync](https://www.npmjs.com/package/deasync)

Neither is ideal.

If reporter methods allowed to return promises (and waited for them) this would be clean and straightforward.

For the record, I've considered implementing the above logic using fixtures. However, I quickly realized that there are [scenarios](https://github.com/microsoft/playwright/issues/17565) in which fixtures are not even invoked, providing incomplete picture of test execution.

**Comment by aslushnikov** [comment]
@punkpeye Philosophically, test execution cannot be paused by reporters sending information to some third-party services. So the solution in https://github.com/microsoft/playwright/issues/17569#issuecomment-1258562068 (thanks @rwoll!) is the one we recommend using.

**Comment by pavelfeldman** [comment]
There is a simpler solution than the above, which would be await all the pending jobs in onEnd.
