### ISSUE TITLE
[Question] How to detect skipped test?

### ISSUE THREAD

**Issue by punkpeye** [microsoft/playwright#17565]
If I am extending base, like...

```ts
export const test = base.extend({
  /* How to detect test being skipped? */
});

test.skip('test', () => {});
```

How do I detect that a test was skipped?

I have tried `test.beforeEach` and `browser` fixtures, but it does not seem like any of them are being called.

**Comment by punkpeye** [comment]
Related to https://github.com/microsoft/playwright/issues/17569

**Comment by aslushnikov** [comment]
You can use [`testInfo.expectedStatus`](https://playwright.dev/docs/next/api/class-testinfo#test-info-expected-status) in `afterEach` hook to detect test status.

**Comment by aslushnikov** [comment]
closing as per above. Please do not hesitate to file more issues if you have more questions!
