### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by ldy12347** [microsoft/playwright#17578]
When running on Linux, screenshots and recordings do not display text
![截图](https://user-images.githubusercontent.com/32159351/192224056-09fbce68-44b9-4107-9ea3-34b49a6072ff.png)

**Comment by aslushnikov** [comment]
@ldy12347 it looks like your linux setup doesn't have fonts installed. Please try using our docker container - `mcr.microsoft.com/playwright` that has all the fonts!

If things still don't work, please re-file one more time, this time explaining in details what you do and what doesn't work.
