### ISSUE TITLE
[Question] would like to access the variable from global-setup ts file to global-teardown file.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#17575]
1. i would like to access the variable and the request payload from global-setup ts file to global-teardown file-ts, is there a way to access the variable between these files or how to access the variable in global teardown file when the values are assigned in global-setup ts file? Can you please clarify?

my URL, and request payload are captured in global ts file, i want to reuse the URL and the payload from global-setup ts file to global teardown file and make API calls to update the values in the database. Please advise how to use the values from global ts file to global teardown file. 

2. tried the above scenario beforeAll and afterAll , however beforeAll() hook gets executed before each test , I want to run it only once before all tests, any reason why it is running before each test? i am using "@playwright/test": "^1.22.1", (edited) 
I wanted to run certain lines of code only once before all tests, but  beforeAll() gets executed again if there is a test failure.
Is there anything similar to beforeAll that can be used inside the test file but wont run again if there is a test failure?

**Comment by Exoow** [comment]
Not sure if a class with a static field might work; otherwise go old school and write/read a text file.

**Comment by aslushnikov** [comment]
@InduKrish your globalsetup can return a function that does global teardown. This way you can re-use all the same data captured by global setup in your global teardown! See [our docs](https://playwright.dev/docs/next/test-advanced#global-setup-and-teardown).

Would it help?

**Comment by aslushnikov** [comment]
Closing as per above. Please do not hesitate to file new issues if you have other questions!
