### ISSUE TITLE
[Feature] Add new state for page.waitForLoadState function based on time to interactive

### ISSUE THREAD

**Issue by bezyakina** [microsoft/playwright#17583]
I would like to offer a function that will check the completion of the last long task on page and followed by 5 or N seconds of inactivity of the network and the main thread ([time to interactive](https://developer.mozilla.org/en-US/docs/Glossary/Time_to_interactive)).

For example:
```js
// with the ability to change the inactivity time value
await page.waitForLoadState('tti', {inactivity: 5000});
```
This way we can wait for the page to become smooth and pleasant if it has lots of scripts to execute at the beginning.

**Comment by aslushnikov** [comment]
@bezyakina Our ideology is to perform actions on the page whenever the action are available. TTI should not matter. 

Playwright is like a very fast user; it sees the button it clicks the button! Nothing can stop it.

So what exactly do you want to achieve?

**Comment by bezyakina** [comment]
@aslushnikov If we are talking about screenshot testing, waiting for TTI can be important and that's why: when each test is run in a new browser context, a lot of scripts are loaded each time during initialization. We need to wait until the page becomes stable to take a screenshot of the entire page (reference or test). None of the current options of the waitForLoadState function is suitable in this case because it does not give us the opportunity to wait until most of the scripts are executed, most of the page elements are rendered and stabilized.

Because of this, we get falling tests even on the same build due to the fact that some elements do not have time to stabilize. Maybe there are some other ways of smart waiting besides waiting for long timeouts?

The test is executed in headless mode. Simplified test logic:
```js
// navigation
await page.goto(url, { waitUntil: 'domcontentloaded' });

// waiting for stabilization of one of the locators
const _locator = page.locator(locator).first()
await _locator.waitFor({ state: 'visible'});

// taking a screenshot and comparing it
const actualSnapshot = await this.screenshot('actual.png');
expect.soft(actualSnapshot).toMatchSnapshot('expected.png');
```

Results:
<img width="214" alt="actual" src="https://user-images.githubusercontent.com/35337277/193016440-3995f666-2c38-4314-a107-fd4119622f0b.png"> <img width="214" alt="diff" src="https://user-images.githubusercontent.com/35337277/193016442-05785839-8c9b-4f7a-a334-02abb51d6b25.png"> <img width="214" alt="expected" src="https://user-images.githubusercontent.com/35337277/193016444-e6f5c38e-e135-416e-8642-df9c9a3f7e3f.png">

 <img width="214" alt="actual" src="https://user-images.githubusercontent.com/35337277/193016661-c6c2db5a-53bc-4628-bfd1-75a309e233b9.png"> <img width="214" alt="diff" src="https://user-images.githubusercontent.com/35337277/193016666-c0678822-d59b-4a52-95bc-12514daa59af.png"> <img width="214" alt="expected" src="https://user-images.githubusercontent.com/35337277/193016670-7c8b2774-b827-4a56-a8ed-d74aa2fed505.png">
