### ISSUE TITLE
[Question] Difference between > and >>

### ISSUE THREAD

**Issue by SirCmX** [microsoft/playwright#17580]
Given:

A table with only one record. The record table >> tbody >> tr have another table inside.

After filtering i try the assertion : 
await expect(page.locator('tbody[id*="' + tableID + '"] **>>** tr >> visible=true')).toHaveCount(1) = does not work, because also the table within the tr was found.

await expect(page.locator('tbody[id*="' + tableID + '"] **>** tr >> visible=true')).toHaveCount(1) =  does work, only 1.

I searched for the difference in the documentation, but I didnt found one.

Can someone please explain the diffence, or does it already exist somewhere in the documentation?

Thanks in advance!

**Comment by daddyman** [comment]
The single greater than is the [CSS child combinator ](https://developer.mozilla.org/en-US/docs/Web/CSS/Child_combinator).

The double greater than is for combining different Playwright selector types such as a CSS and text selector in the same string. This is shown on the [selector page](https://playwright.dev/docs/selectors) in the docs but doesn't any extra explanation of why the double greater than is present.

`await page.locator('#nav-bar >> text=Contact Us').click();`
