### ISSUE TITLE
Upgrading from playwright 1.24.0 to 1.26.0 changes text check on //head/title

### ISSUE THREAD

**Issue by emakaay** [microsoft/playwright#17588]
**Context:**

We were using playwright 1.24.0 without problems.
The following assertion was used: 
assertThat(homePage.titleLocator()).hasText("appName")

were homePage.titleLocator was: page.locator("//head/title")

When upgrading to 1.26.0 the assertion broke

LOG:
Waiting for selector  "//head/title"
  selector resolved to <title>appName</title>
  unexpected value ""

**Code Snippet**
can't share

**Describe the bug**
Would expect the assertion still works. Perhaps piercing the shadow root for ("expect(locator)toHavetext()" is the reason ?
We have many hasText assertions, but only the //head/title fails

**Comment by aslushnikov** [comment]
@emakaay this is a bug fix! Title is not a node visible to the user. To assert a title, use:

```java
assertThat(homePage).hasTitle("appName")
```

**Comment by emakaay** [comment]
Thanks for the bug fix and explanation
