### ISSUE TITLE
[BUG] `viewport` `contextOptions` not overriding

### ISSUE THREAD

**Issue by chrisboakes** [microsoft/playwright#17586]
**Context:**
- Playwright Version: `1.26.0`
- Operating System: Mac
- Node.js version: `v16.16.0`
- Browser: Chromium
- Extra:

**Code Snippet**

Repro repo: https://github.com/chrisboakes/playwright-viewport-bug

**Describe the bug**

I'm trying to override the default `viewport` browserContext options in `playwright.config.js`:

```js
const config = {
    ...
    use: {
        browserName: "chromium",
        viewport: {
            width: 1000,
            height: 600
        }
    },
};

export const testMobile = base.extend({
	contextOptions: {
		viewport: {
			width: 100,
			height: 50,
		},
	},
});

export default config;
```

When I write a regular test like so:

```js
test('should be default viewport', async ({ page }) => {
    await page.screenshot({
        animations: 'disabled',
        path: 'screenshots/desktop.png',
        fullPage: true,
    });
});
```

I see the default viewport size. When I import and call `testMobile`, I expect to see the viewport overriden:

```js
testMobile('should be mobile viewport', async ({ page }) => {
    // I expect to see the viewport as 100 x 50 here
    await page.screenshot({
        animations: 'disabled',
        path: 'screenshots/mobile.png',
        fullPage: true,
    });
});
```

However the viewport is the same default size. If I pass other params e.g. `offline: true` to the `contextOptions` they seem to work fine. It's just the viewport I'm struggling with.

**Comment by aslushnikov** [comment]
@chrisboakes you should use `test.use` instead of the custom fixture here. The following worked for me:

```ts
// playwright.config.ts
const config = {
  use: {
    browserName: "chromium",
    viewport: {
      width: 1000,
      height: 600
    }
  },
};
export default config;
```

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test.describe('mobile', () => {
  test.use({
    viewport: {
      width: 100,
      height: 50,
    },
  });

  test('mobile dimensions', async ({ page }) => {
    expect(await page.evaluate(() => window.innerWidth)).toBe(100);
  });
});

test('desktop dimensions', async ({ page }) => {
  expect(await page.evaluate(() => window.innerWidth)).toBe(1000);
});
```

**Comment by chrisboakes** [comment]
Thanks @aslushnikov. I was actually able to get my above fixture example working by simply not passing it to `contextOptions` and directly to the base extend like so:

```js
// playwright.config.ts
export const testMobile = base.extend({ 
    viewport: { width: 400, height: 400 }
});
```

I can then use it like so:

```js
testMobile('should be mobile viewport', async ({ page }) => {
    // This test will run as viewport as 400 x 400 here
    await page.screenshot({
        animations: 'disabled',
        path: 'screenshots/mobile.png',
        fullPage: true,
    });
});
```

I updated my sample repo with a working example: https://github.com/chrisboakes/playwright-viewport-bug
