### ISSUE TITLE
[BUG] Can't run browser session copied from another PC

### ISSUE THREAD

**Issue by dxpnkil** [microsoft/playwright#17585]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Windows
- Browser: Chromium

**Describe the bug**

I copied user data from another computer's browser. But when I run user data on my browser, it doesn't get the browser session.

```python
from multiprocessing import process
import os
from playwright.sync_api import sync_playwright
with sync_playwright() as p:
    context =p.chromium.launch_persistent_context(user_data_dir ='D:\\TestProfile',
                   headless=False,channel='chrome',service_workers='block').new_page()
    input("Press Enter to continue...")
    context.close()
```
Thank you for all your help!

**Comment by aslushnikov** [comment]
@dxpnkil hard to say! It might be that chromium encoded something in the profile directory using other machine's information, so this user profile is not available here.

All in all, it looks like this is how Chrome works and has nothing to do with Playwright; feel free to file this to https://crbug.com/new or ask on some chromium google-group!
