### ISSUE TITLE
How do I stop headed mode when running tests in VS Code. 

### ISSUE THREAD

**Issue by ErroneousBee** [microsoft/playwright#17589]
Ive just upgraded to playwright 1.25 from 1.23, and when I run tests using the VS Code plugin, it now run in headed mode. I only want headed mode when debugging ( as in the previous behaviour), how do I achieve that?

**Comment by aslushnikov** [comment]
You should uncheck the "show browser" checkbox in the bottom-left corner! 

<img width="1013" alt="Screen Shot 2022-09-27 at 1 17 24 AM" src="https://user-images.githubusercontent.com/746130/192447889-4989d76f-890e-4763-943c-fec8688cdf43.png">
