### ISSUE TITLE
[Feature] Global setting for delay after each `page.press`

### ISSUE THREAD

**Issue by fredboyle** [microsoft/playwright#17594]
During the development of our design system toolkit we found that when testing for keyboard workflows that repeated `page.press` could cause flaky tests, particularly in Chromium.

Add a `page.waitForTimeout(100)` between each key press helped to resolve this flaky behavior. This unfortunately means we need to remember to do this when writing new tests. It would be nice to have a global setting such as `pagePressAfterPause` where we could set a value (in milliseconds) for how long to pause after a `page.press`.

Usecase in particular is a custom select field with a scrolling listbox. When testing keyboard interactions of navigating to the element, pressing 'Enter' to open the listbox, then repeatedly pressing 'ArrowDown' to reach an option past the scrolling window.

Hope this helps. Thanks.

**Comment by aslushnikov** [comment]
> Add a page.waitForTimeout(100) between each key press helped to resolve this flaky behavior.

While this might help on some setups, it might still be flaky on CI where the concept of time is severely skewed: highly-saturated CI machines might take a long time before yielding to your workload, so assuming the 100ms would be enough for browser to process something is risky. We even have a saying: "There's no time on CI".

A proper workaround would be to wait for the proper condition that you need. It looks like you have some custom lists with scrolling, so in this case you'd need for the proper list element to appear in the view.

Given all of this, we'd rather not add anything timeout-based to our API to avoid confusing our users!
