### ISSUE TITLE
[Question] The problem with storageState injection values【test.use 】

### ISSUE THREAD

**Issue by levidcd** [microsoft/playwright#17603]
![image](https://user-images.githubusercontent.com/10431861/192418279-46d5c879-999c-4967-8096-b13a7013e44e.png)
![image](https://user-images.githubusercontent.com/10431861/192418320-2b70b54e-b851-4ec7-85e3-73206a2861d5.png)
![image](https://user-images.githubusercontent.com/10431861/192418928-deb49c20-0fd4-4c7b-90fb-b8d46edc2ceb.png)

I saved `auth.json` with `--save-storage`, I used `--load-storage=auth.json` to log in normally, but I couldn't log in when I used `test.use`, and cookies didn't exist `access_token`. When I modify the value `access_token` in `auth.json` to a normal string, it can be added to the `access_token`, and `access_token` value now is `2|1:0|10:1664243392|12:access_token|48:YWRlNzJiZjItM2UwNi0xMWVkLTgyNDAtZWU0M2M2YTQ3ZDVj|c9acc64d160ccf2e3fca98f905783a3d959398fd884e48b0a3cd53095bee8702`

**Comment by levidcd** [comment]
It seems to be related to `:`

**Comment by aslushnikov** [comment]
I tried this locally and was not able to reproduce: https://github.com/aslushnikov/playwright/commit/9b252f7f4f18a75aa3a4fac8bcdc79e6ee4a2503

Any chance you can build a small script that reproduces this issue in isolation and share it with us?

**Comment by levidcd** [comment]
I feel sorry that it was my problem. I checked the backend program and revalidated the issue using a blank page, and playwright worked fine.
![image](https://user-images.githubusercontent.com/10431861/192493276-f00f3cb3-e030-4bc2-a6d7-81e2596ab522.png)
