### ISSUE TITLE
[BUG] The memory occupied by chrome is not completely released after the page is closed

### ISSUE THREAD

**Issue by yangJiang-create** [microsoft/playwright#17602]
**Context:**
Playwright Version: 1.26.0
Operating System: windows
Node.js version: v16.16.0
Browser: Chromium
Extra:

**Code Snippet**

```python
import asyncio
from playwright.async_api import async_playwright
import time
async def get_refer():
    async with async_playwright() as p:

        browser =await p.chromium.launch(headless=True, args=[
                "--no-zygote",
                "--no-sandbox", 
                "--allow-running-insecure-content",
                "--disable-gpu", 
                "--disable-web-security",
                "--disable-xss-auditor",
                "--disable-setuid-sandbox",
                "--disable-webgl",
                "--disable-popup-blocking",
                "--disable-dev-shm-usage", 
                "--disable-accelerated-2d-canvas", 
                "--disable-mipmap-generation", 
                "--disable-partial-raster", 
                "--no-first-run", 
            ]) 
        context = await browser.new_context(ignore_https_errors = True)
        page = await context.new_page() 
        url ="https://playwright.dev/python/docs/intro"
        await page.goto(url)
        print(url)
        time.sleep(15) # one page used 30MB memory
        
        page_list = []
        url_list = ['https://yandex.com/','https://pixabay.com','https://www.tusij.com','https://modao.cc/feature/prototype/']
        for u in url_list:
            page = await context.new_page()
            page_list.append(page) 
            await page.goto(u)
            print(u)
        time.sleep(15) # five page used more memory , that is ok

        for pages in page_list:
            await pages.close()# when i close other page ,only reserve the first page .
        print(0)
        time.sleep(15)  # used 60MBmemory
        await browser.close() 

asyncio.run(get_refer())
```

**Describe the bug**

thanks for palywright group . I'm not sure if this is a playwright problem or a chrome problem .

The code I provided is a simple fragment: the complete program is to open all subdomains under our domain name . 

The flow of the program is open 4url at a time, then record the information, then close, then open 4 URLs, and then close, and so on. About 800-1000 pages or so. 

but the program always take up a very large amount of memory, causing it to get stuck .  i used some args  but it is useless . i don‘t konw why i use browser Incognito mode to open the page  and close the page , the  memory still grows as more pages are opened .
I have saved the data in the database, is there any way to reduce the memory of the browser?

**Comment by aslushnikov** [comment]
This is a dupe of https://github.com/microsoft/playwright/issues/6319

Long story short: `context` stores a bunch of helpful debugging information, so please close browser context and open a new one for a long-running jobs that navigate lots of urls.

Thanks!
