### ISSUE TITLE
[Question] how to persist data between tests if one fails

### ISSUE THREAD

**Issue by A-ZC-Lau** [microsoft/playwright#17609]
For the example code below (assume that the functions are actually in other files)

```
import { test } from "@playwright/test";

class Data {
	name = "example";
}

function FIRST (d : Data) {
	return async function () {
		console.log(d.name);
		d.name = "first";
	};
}
function SECOND (d : Data) {
	return async function () {
		console.log(d.name);
		test.expect(2).toBe(1); // expect it to fail
		d.name = "second";
	};
}
function THIRD (d : Data) {
	return async function () {
		console.log(d.name);
		d.name = "third";
	};
}

const d = new Data();

test("first", FIRST(d));
test("second", SECOND(d));
test("third", THIRD(d));
```

When the test is run, the output is:
```
example
first
example
```

whereas I was expecting
```
example
first
first
```

is this expected behavior? How do I retain the existing/current data in the event that any one test fails?

**Comment by mxschmitt** [comment]
> Workers are always shutdown after a [test failure](https://playwright.dev/docs/test-retries#failures) to guarantee pristine environment for following tests.

See here: https://playwright.dev/docs/test-parallel

What kind of data you want to persist? Depending on the use-case we can suggest a solution for it.

**Comment by aslushnikov** [comment]
> is this expected behavior?

@A-ZC-Lau Yes, it is. It looks like you're running with a single worker, and this worker:
- launches a process
- executes the first test (prints "example")
- executes the second test (prints "first")
- test fails, so the worker **is being re-created with a new process**. This re-creates a new data instance.
- the worker then runs the third test (prints "example")

> How do I retain the existing/current data in the event that any one test fails?

It looks like your tests are dependent. First of all, dependent tests are discouraged! Try to make them independent / merge in a single test instead.

Alternatively, you can use serial mode: https://playwright.dev/docs/test-retries#serial-mode

**Comment by A-ZC-Lau** [comment]
@aslushnikov i put them as dependent tests, as there's no `test.step.skip` or `test.step.only`.

Here's a summary of what I'm currently doing.

```
test("create")
test("update")
test("check")
```

the "create" test basically sets up for "update", which then sets up for "check".

Since my "create" test is passing, but "update" and hence "check" isn't, I simply use `test.skip("create")` so I can check the other two.

But I guess I could settle for just commenting out code that needs to be skipped
