### ISSUE TITLE
[Question] Is there a plan to add next.js support for component testing?

### ISSUE THREAD

**Issue by artyompvl** [microsoft/playwright#17605]
I was going through playwright documentation and was amused by amount of features you guys have. Especially component testing. Do you have any plans to add next.js support?

**Comment by aslushnikov** [comment]
@artyompvl The `ct-react` should just work for you! What's missing?

**Comment by artyompvl** [comment]
Nice! I'm just doing some research for my projects and haven't sent too much time on it. I tried to add `ct-react` as is to my next.js project and got some compilation errors from vite:
```
[vite:esbuild] Transform failed with 5 errors:
ERROR: Transforming const to the configured target environment ("es5") is not supported yet
...
```
Probably will need to hook up babel somehow

**Comment by aslushnikov** [comment]
@artyompvl feel free to file new issues if things don't work for you!
