### ISSUE TITLE
[BUG] VSCode “Show Browser” (reusedBrowser) does not respect "playwright.env" (settingsEnv)

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#17616]
**Context:**
- Playwright Version: 1.26.0
- Operating System: Linux
- Node.js version: v14.19.1
- Visual Studio Code version: 1.72.0-insider (Universal)
- Playwright for VSCode extension version: v0.2.10
- Browser: Chromium
- Extra: Codespaces

**Code Snippet**

```ts
import { test } from '@playwright/test';
test('repro', async ({ page }) => {
  await page.goto('https://playwright.dev/');
});
```

**Describe the bug**

I am using a remote XServer on my dev machine. I want to pass the environment variable `DISPLAY=127.0.0.1:0` to the Chromium browser.

Usually, I do this from `settings.json`:

```js
	"playwright.env": {
		"DISPLAY": "127.0.0.1:0"
	}
```

This works fine when debugging the tests.

However, when I check the "Show Browser" checkbox, the browser fails to start with this message:

```
browserType.launch: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝
```

I have checked the extension code. It turns out that in `reusedBrowser`, the settings defined at `playwright.env` in `settings.json` is not used at all.

https://github.dev/microsoft/playwright-vscode/blob/0ab88da48baffa6a5fde3dc5d9a1066697c90f7d/src/reusedBrowser.ts#L72

**Current workaround**

To workaround this issue temporarily, I add this line to `node_modules/playwright-core/lib/cli/cli.js`:

```ts
process.env.DISPLAY = '127.0.0.1:0'
```

**Comment by mxschmitt** [comment]
I can repro, the code pointer to the missing passed env is here: https://github.com/microsoft/playwright-vscode/blob/5476e6f5ded849b9488175c03918e92cee67b95d/src/reusedBrowser.ts#L85
