### ISSUE TITLE
[Question] Is it possible to generate the custom routes using the data in the `trace.zip`?

### ISSUE THREAD

**Issue by tachish** [microsoft/playwright#17619]
Background:
In some cases, I don't want to really request the back-end. For example, there will be many requests while refactoring the project.  
It's maybe better to use the data I traced before, instead of writing to the DB.

However, if using `network mock`, I have to spend a lot of time to write the custom routes. Is it possible to generate the custom routes using the data in the `trace.zip`?

**Comment by aslushnikov** [comment]
>  I have to spend a lot of time to write the custom routes.

@tachish If I understand correctly, this is something that Network Replay can help with: https://playwright.dev/docs/network#record-and-replay-requests

Video explanation: https://www.youtube.com/watch?v=NRGOV46P3kU&feature=youtu.be

>  Is it possible to generate the custom routes using the data in the trace.zip?

No, that's not possible. I'll close the bug now, but please don't hesitate to file a new one if you think we still can be helpful!
