### ISSUE TITLE
[BUG] localhost domain incorrectly prefixed with dot when exporting to storageState

### ISSUE THREAD

**Issue by overbalance** [microsoft/playwright#17615]
**Context:**
- Playwright Version: 1.26.0
- Operating System: Mac
- Node.js version: 18.9.1
- Browser: Chromium
- Extra: simple Java API server

**Code Snippet**

```javascript
const requestContext = await request.newContext();
const response = await requestContext.post(`${API_URL}/login`, {
  form: {
    email: env.PLAYWRIGHT_EMAIL,
    password: env.PLAYWRIGHT_PASSWORD,
  },
});

console.log(await response.headers()); // domain: localhost

await requestContext.storageState({ path: "adminStorageState.json" }); // domain: .localhost
```

**Console Output**
```js
{
  'access-control-allow-credentials': 'true',
  'access-control-expose-headers': 'Content-Disposition',
  'x-frame-options': 'SAMEORIGIN',
  'content-encoding': 'gzip',
  'content-type': 'application/json',
  connection: 'close',
  'set-cookie': 'localhost.token=pnbEIxP_AohlFt5xbaxCM4yZ0I8; version=1; path=/; domain=localhost; expires=Thu, 27-Oct-2022 08:04:49 GMT; max-age=2592000\n' +
    'localhost.redirect=null; version=1; path=/; expires=Tue, 27-Sep-2022 08:04:49 GMT; max-age=0'
}
```

**Contents of adminStorageState.json**
```json
{
  "cookies": [
    {
      "name": "localhost.token",
      "value": "pnbEIxP_AohlFt5xbaxCM4yZ0I8",
      "domain": ".localhost",
      "path": "/",
      "expires": 1666857889.581,
      "httpOnly": false,
      "secure": false,
      "sameSite": "Lax"
    }
  ],
  "origins": []
}
```

**Describe the bug**

I expect the cookie domain to be unchanged upon storing in a state file. The localhost domain is being prefixed with a period instead.

**Comment by mxschmitt** [comment]
The leading dot means that the cookie is valid for subdomains as well, see [here](https://stackoverflow.com/a/20884869/6512681).

Storage state is an implementation detail, does it yield to issues if you restore it, does the cookie not applied correctly then? What if you restore it (passing it to newContext({storageState}) or via the playwright config if you are using playwright test) and call [`context.cookies()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-cookies)?

**Comment by aslushnikov** [comment]
@overbalance There's not much we can do unless we can see & debug the issue ourselves. Can you build a small repro that we can run locally to debug this? 

I'll close this for now, but please file a new issue with a repro so that we start over looking into this!
