### ISSUE TITLE
[Question] Chromium only - "Verify it's you" when using google auth

### ISSUE THREAD

**Issue by yanivefraim** [microsoft/playwright#17622]
Hi,
While I know that this is not Playwright's falt, I'm struggling with an issue and I couldn't find a solution online for it.
My app is using google Auth0 to for authentication. I'm writing a test which starts with the Google login part.
In Firefox/Webkit the test is green, while in Chromium I'm getting the "Verify it's you" message (My test user does not have 2FA).
Locally, after opening with `headless:false`, and clicking the browser, the problem stopped. But, I keep getting it on CI.

Possible solutions that I thought about (didn't really work for me):
- Somehow disable this feature for chromium (I have no idea how)
- Using global-setup to get the auth cookie, using FF browser. Save the cookie to a file, and use this cookie for Chromium, later on. This didn't work for me (I tried something like that: 
global-setup:
```
// Login process... 

// Then:

const cookies = await page.context().cookies()
  
const cookieJson = JSON.stringify(cookies)

fs.writeFileSync('cookies.json', cookieJson)
```

On the test side:
```
  const cookies = fs.readFileSync('cookies.json', 'utf8')
  const browser = await chromium.launch()
  const context = await browser.newContext()
  const deserializedCookies = JSON.parse(cookies)
  await context.addCookies(deserializedCookies)
  const page = await context.newPage()
  console.log(cookieJson)
  await page.goto(`${TESTS_SERVER_URL}/login`)
```

Again, not a Playwright issue, but any help will be highly appriciated!!! 
Thanks!

**Comment by aslushnikov** [comment]
@yanivefraim I assume you run headed on the CI? if not, then please try running headed!

Other then that I can't help much. I'd suggest asking on our slack channel https://aka.ms/playwright/slack, maybe someone has encountered this already!
