### ISSUE TITLE
[BUG] When clicking on a link navigating away from the website, playwright throws a removeFrameSession failure

### ISSUE THREAD

**Issue by cnishina** [microsoft/playwright#1762]
**Context:**
- Playwright Version: 0.13.0
- Operating System: Mac

**Code Snippet**

```javascript
it('should work', async () => {
  console.log('goto');
  await page.goto(
    'https://journal.cnishina.dev/2020/04/create-mp4-from-screencast.html');
  await new Promise((resolve) => {
    setTimeout(resolve, 500);
  });
  console.log('click journal');
  await page.click('a[href="https://journal.cnishina.dev/"]');
  console.log('youtube');
  await page.click('a[href="https://youtu.be/dQw4w9WgXcQ"]');
});
```

**Describe the bug**

As a person writing a test, if I click on a link that navigates me away from the page, then it should not throw an error.  I noticed this when I was clicking the `a[href="https://youtu.be/dQw4w9WgXcQ"]`. Clicking on this throws an error. I am either looking for documentation explaining targetId and sessionId and why this does not work when this happens (what the workflow should be if we decide to click on a link navigating us away from the main page) or to fix it with:

```
removeFrameSession(targetId) {
    const frameSession = this._sessions.get(targetId);
    if (!frameSession)
        return;
    // Frame id equals target id.
    const frame = this._page._frameManager.frame(targetId);
    if (frame) {
        this._page._frameManager.removeChildFramesRecursively(frame);
        frameSession.dispose();
        this._sessions.delete(targetId);
    }
}
```
This just changes the `assert(frame);` and puts it into a conditional. I've tried out this change and it appears to work but might not be the right fix. Let me know and I can put in a PR this week. Thanks!

**Comment by cnishina** [comment]
I have more info here: https://journal.cnishina.dev/2020/04/playwright-removeframesession.html on what I've tried, etc.

**Comment by arjun27** [comment]
Thanks for reporting this @cnishina. Can you share some more context on how you were setting up the `browser` and `page`? Were you using jest-playwright, or something similar? I tried doing this on plain Playwright in Node (v13.12 – code snippet below), and did not run into any errors. Trying to find out what I'm missing.
<details>
<summary>Code snippet</summary>

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();

  await page.goto(
    'https://journal.cnishina.dev/2020/04/create-mp4-from-screencast.html');
  await new Promise((resolve) => {
    setTimeout(resolve, 500);
  });
  console.log('click journal');
  await page.click('a[href="https://journal.cnishina.dev/"]');
  console.log('youtube');
  await page.click('a[href="https://youtu.be/dQw4w9WgXcQ"]');

  await browser.close();
})();
```
</details>

**Comment by pavelfeldman** [comment]
Looks like a OOPIF error, @dgozman, PTAL!

**Comment by cnishina** [comment]
Here's my sample code. This runs with `npm test`.

https://github.com/cnishina/protractor-experiments/tree/master/playwright-issue-1762

**Comment by cnishina** [comment]
I have the following: https://github.com/cnishina/playwright/commit/778f4ba8c02f9e428a15bfa78f9ccc0fc4af1862

Let me know if this is a reasonable PR or if there's something else going on.

**Comment by dgozman** [comment]
I can reproduce this locally, but cannot write a test that reproduces this issue in our environment. Most likely, there is a race between renderer-issued frameDetached and browser-issued detatchFromTarget.

@cnishina Your commit is indeed a good solution. The only problem is that the following lines should be executed even when `frame` is undefined:

```ts
frameSession.dispose();
this._sessions.delete(targetId);
```

If you could update your change and send a PR - that would be wonderful!

**Comment by cnishina** [comment]
Sounds good. I'll have something in by the end of the day...
