### ISSUE TITLE
> > > @alexneo2003 i have used your reporter earlier and it worked well. I faced one limitation. All test cases need to be present under one suiteID. Actually we keep test cases in different suites for each Feature.

### ISSUE THREAD

**Issue by mechandan** [microsoft/playwright#17623]
> > > @alexneo2003 i have used your reporter earlier and it worked well. I faced one limitation. All test cases need to be present under one suiteID. Actually we keep test cases in different suites for each Feature.
> > 
> > 
> > Maybe you mean planId? As i seen planId is highest level at test cases what includes test suites.
> 
> Azure DevOps instance could have multiple projects. One one particular project there could be multiple Test Plans (test plan IDs). If you take one Test Plan it can have multiple test suites. If you would provide option to specify testPlanID, suiteID and testCaseID for each test case that would be awesome. Rest of variables such as PAT token, project id, ADO Org URL can be common.

To add to my above feedback, for those people who are storing all test cases in single Test Plan and single Test Suite,  you can continue your current capability as well. So if the testPlanID, TestSuiteID are not found at test case level then it will search and use the same from playwright.config.ts

@alexneo2003
There could be multiple planId inside a project , is it not possible to allow this field to take multiple planid or can take testcaseid directly from the test case irrespective of the planId passed or not in the conf file …

**Comment by mechandan** [comment]
> 

@alexneo2003 is it possible to pass plan id from the test case itself and set it here ?? 

I feel these are immutable properties though asking for any possibilities ,,,

**Comment by alexneo2003** [comment]
> > 
> 
> @alexneo2003 is it possible to pass plan id from the test case itself and set it here ?? 
> 
> I feel these are immutable properties though asking for any possibilities ,,,

this will not make sense because the project must have one test plan if you want to get one test run result.  
data from different test plans should be published to different test results.  
try to manually create a test run based on the plan and try to add results from another test plan to it, if it works out - tell me.
