### ISSUE TITLE
Connect to Azure key vault from playwright .net

### ISSUE THREAD

**Issue by lvendramini** [microsoft/playwright#17624]
I am trying to login as different AD users in my playwright tests to test permissions.  I am able to login fine with hardcoding the username and password.  I want to be able to use the username and passwords saved in Azure keyvault so they are secure.  Is this possible?  I do not have a programs.cs or startup.cs.

**Comment by mxschmitt** [comment]
Playwright is like a normal program, so you can use normal of receiving secrets like you'd do without Playwright. Depending on where you run your application, different options may apply. Where do you run your program, locally, in CI (GitHub Actions, Azure Pipelines), some different Azure service?

**Comment by mxschmitt** [comment]
Closing since its not Playwright specific, usually your CI injects them or you can use any .NET library to get them.

**Comment by bheemreddy181** [comment]
Can we store token in StorageState like cypress https://medium.com/version-1/using-cypress-to-test-azure-active-directory-protected-spas-47d04f5add9 ?
