### ISSUE TITLE
[BUG] Can't seem to get playwright to listen to my aliases?

### ISSUE THREAD

**Issue by Morklympious** [microsoft/playwright#17638]
**Context:**
- Playwright Version: `^1.22.2`
- Operating System: Windows
- Node.js version: 16.16.0
- Browser: N/A
- Extra: Running a Sveltekit project which generates a build folder and relies on a `jsconfig.json` that extends a generated `tsconfig.json`

**Describe the bug**
Hello! I've been vigorously google searching for a solution to this but I don't know that there is one yet? I have a Sveltekit project that makes use of Playwright as a test system and it's been great so far! One issue, however, is that I can't seem to get playwright test files to respect my alias imports.

I have a file that maps to aliases, e.g.:

```js 
const aliases = {
    shared     : path.resolve("./src/shared/"),
    components : path.resolve("./src/components/"),
    mocks      : path.resolve("./src/mocks"),
    test       : path.resolve("./test"),
};
```
And in the root of my project, I have a jsconfig.json that (mostly) maps onto these aliases:

```json
{
	"compilerOptions": {
		"baseUrl": ".",
		"paths": {
			"components/*" : ["src/components/*"],
			"mocks/*" : ["src/mocks/*"],
			"test/*" : ["src/test/*"]
		},
		"allowJs": true,
		"checkJs": true,
		"forceConsistentCasingInFileNames": true,
		"resolveJsonModule": true,
		"skipLibCheck": true,
		"moduleResolution": "NodeNext"
	},
	"include" : ["src/**/*.d.ts", "src/**/*.js", "src/**/*.svelte"],
	"extends" : "./.svelte-kit/tsconfig.json",
}
```

And my playwright config looks like this:
```js
import path from "path";

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
	webServer : {
		command : "npm run build && npm run preview",
		port    : 4173,
	},

	testDir : path.resolve("./"),
};

export default config;
```

Now whenever I try to run my test command (`"playwright test -c ./config/playwright.config.js"`), it looks for files with test in the name by default. in an example, this test passes perfectly:

```js
import { expect, test } from "@playwright/test";

test("index page has a body", async ({ page }) => {
	await page.goto("/");
	expect(await page.isVisible("body")).toBeTruthy();
});
```

HOWEVER, the second I try to introduce an alias path into the test, lets say I want to bring in a testing utility or an Enum from a component, the test horks

```js
import { expect, test } from "@playwright/test";
import { IconNames } from "components/icon/icon-names.js";

test("index page has a body", async ({ page }) => {
	await page.goto("/");
	expect(await page.isVisible("body")).toBeTruthy();
});
```

This will fail with an error message of 

```
> project@0.0.1 test
> playwright test -c ./config/playwright.config.js


Running 0 tests using 0 workers

Error: Cannot find package 'components' imported from ...
```
Now I've been looking to see if there are problems here and it looks like `tsconfig`, or in my case, `jsconfig` isn't being respected with paths for aliases? I'm just curious if anyone has seen this problem or has found a good solution for it. 

Again, I know I'm running a sveltekit project and that is outside the scope of Playwright itself, but is there a reason that playwright isn't wanting to resolve my modules? **For what it's worth, if I use a fully relative path, it works**, but I'd really rather not do that if I can help it. Vite respects my aliases, intellisense also respects my aliases, every alias inside my component code is also respected. Does playwright expose any alias option?

Any ideas would be mighty helpful! thanks!

**Comment by Morklympious** [comment]
Sure thing! I'll see if I can't get something setup!

**Comment by aslushnikov** [comment]
@Morklympious I'll close this for now, but please do not hesitate to re-file once a repro is ready! Thanks!
