### ISSUE TITLE
[Question] How to take a screenshot for a page with alert box

### ISSUE THREAD

**Issue by changhuixu** [microsoft/playwright#17639]
`await Page.ScreenshotAsync(new()
{
    Path = "screenshot.png",
    FullPage = true,
});`

This method only take screenshots with the HTML elements, not the Alert box from the browser.
Is there a way to take screenshots including the alert box?

Thank you

**Comment by mxschmitt** [comment]
This is not possible, an alert box, aka. [window.alert](https://developer.mozilla.org/en-US/docs/Web/API/Window/alert) is not part of the DOM so its not actually rendered.
