### ISSUE TITLE
[BUG] Unable to run newly created tests

### ISSUE THREAD

**Issue by LoreCrux** [microsoft/playwright#17635]
**Context:**
- Playwright Version: v1.26.1
- Operating System: Windows
- Node.js version: v16.14.2
- Browser: Chrome

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 11.95 GB / 31.71 GB
## Binaries:
 - Node: 18.9.1 
 - Yarn: 1.22.19 
 - npm: 8.19.2 
## npmPackages:
 - playwright: ^1.26.1 => 1.26.1
 - playwright-core: ^1.26.1 => 1.26.1

**Code Snippet**

```typescript
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // create a locator
  const getStarted = page.locator('text=Get Started');

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro');

  // Click the get started link.
  await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Describe the bug**

When I try to run any newly created test(s) after upgrading to v1.26.0, the terminal throws an error: **Running 0 tests using 0 workers**.  I also tried it with the "example.spec.ts" that is included when installing Playwright and it gets the same error.  My pre-existing tests ran before updating and still are able to run.  I put the example test in the same folder where my other tests are located, just to eliminate that being the issue.

I recently updated to v1.26.1 to see if that fixed the issue, but it did not.

![Screenshot 2022-09-27 120920](https://user-images.githubusercontent.com/40617919/192604655-bf9bc4f2-948f-4fb9-9571-732f5785f3dc.jpg)

**Comment by mxschmitt** [comment]
What is your path for the example.spec.ts? 

So you confirm that this also happens when you try to run the default project created via [`npm init playwright`](https://playwright.dev/docs/intro)?

Is it only not working if you pass a filename, or does `npx playwright test` without passing an argument also not work?

Usually this happens if your test you are trying to run is not inside the [testDir](https://playwright.dev/docs/api/class-testproject#test-project-test-dir) which is configured in the playwright config.

**Comment by LoreCrux** [comment]
> What is your path for the example.spec.ts?
> 

Here is what my folder structure looks like:

![Screenshot 2022-09-28 074258](https://user-images.githubusercontent.com/40617919/192795252-6b00644d-c132-4d07-b62f-35b4a424af49.jpg)

> So you confirm that this also happens when you try to run the default project created via [`npm init playwright`](https://playwright.dev/docs/intro)?
> 
I did install playwright into a different folder separate from my current framework and the example.spec.ts DID work.  Which leaves me to believe it's something wrong with my config or something along those lines.

> Is it only not working if you pass a filename, or does `npx playwright test` without passing an argument also not work?
> 
Both.  It sees the pre-existing tests, but not the example test with `npx playwright test`

> Usually this happens if your test you are trying to run is not inside the [testDir](https://playwright.dev/docs/api/class-testproject#test-project-test-dir) which is configured in the playwright config.

I checked that when I first experienced the issue.  The example test is in the same folder as my other tests that are able to run,

**Comment by LoreCrux** [comment]
Ok I figured out the issue.  In my playwright.config.ts, I had the following line for tagging in the `const config: PlaywrightTestConfig`:

`grep: [new RegExp("@smoke")],`

3 of my tests have `@smoke` in the test title while the other 2 (including the example test) did not have that tag.  Thus, the Test Explorer did not see the tests w/o the `@smoke` tag or running `npx playwright test`.
