### ISSUE TITLE
[Question]: How to resolve CORS when page.evaluate method executes Javascript

### ISSUE THREAD

**Issue by HangJau** [microsoft/playwright#17631]
### Your question

Hello developers! I'm having a CORS issue that I've reported when executing a JavaScript script via the page.evaluate method. How to deal with CORS issues in playwrights. Getting JavaScript to work? I have manually turned on chromium-1015 and configured Block insecure private network requests to Disabled

Error message:
XMLHttpRequest accessing "http://127.0.0.1:12345/getrsp" from origin "http://xxxx.com" has been blocked by CORS policy: The requesting client is not a security context, the resource is located in the more-private address space `local `. Failed to load resource: net::ERR_FAILED

**Comment by mxschmitt** [comment]
Depending on your use-case there are multiple ways to workaround it. 

We'd recommend to your Playwright's [API testing client](https://playwright.dev/docs/next/api/class-apirequestcontext) to make your http request, this one is not affected by cors.

If you need to make the request inside the browser, you can pass `'--disable-web-security'` as an arg to the browser and set bypassCSP to true. Something like that should work for Chromium:

```
  use: {
    bypassCSP: true,
    launchOptions: {
      args: ['--disable-web-security']
    }
  },
```

**Comment by HangJau** [comment]
Problem solved, thanks a lot🌹

**Comment by adudew852** [comment]
> bypassCSP

Hi there - I tried to do the same thing for webkit but it doesn't seem to work.  Can you provide more details?  Many thanks in advance!

`async def main():
    async with async_playwright() as p:
        browser = await p.webkit.launch(
            headless=False,
            slow_mo=50,
            args=[
                '--disable-web-security'
            ],
            ignore_default_args=[
                '--disable-extensions',
                '--disable-default-apps',
                '--disable-component-extensions-with-background-pages',
            ]
        )
        context = await browser.new_context(
            bypass_csp=True,
            java_script_enabled=True,
            user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/105.0.5195.100 Mobile/15E148 Safari/604.1"
        )`

**Comment by archaabajpai** [comment]
> > bypassCSP
> 
> Hi there - I tried to do the same thing for webkit but it doesn't seem to work. Can you provide more details? Many thanks in advance!
> 
> async def main(): async with async_playwright() as p: browser = await p.webkit.launch( headless=False, slow_mo=50, args=[ '--disable-web-security' ], ignore_default_args=[ '--disable-extensions', '--disable-default-apps', '--disable-component-extensions-with-background-pages', ] ) context = await browser.new_context( bypass_csp=True, java_script_enabled=True, user_agent="Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) CriOS/105.0.5195.100 Mobile/15E148 Safari/604.1" )

Hi, did it solve your issue? The --disable-web-security fails for webkit, how to resolve this?
