### ISSUE TITLE
[BUG] Playwright extension for VSCode stopped working

### ISSUE THREAD

**Issue by charlyautomatiza** [microsoft/playwright#17633]
**Context:**
- Playwright Version: 1.25.0
- Operating System: Windows 10
- Node.js version: v16.14.0
- Visual Studio Code version: 1.71.2
- Playwright for VSCode extension version: 0.2.10
- Browser: All

**Code Snippet**

[starter-playwright](https://github.com/charlyautomatiza/starter-playwright)

**Describe the bug**

Some people who use windows are having problems with the use of the extension, in my case the play button does not appear, to other people when pressing the play button a spinner appears but no test is executed.

![2022-09-27_13h18_27](https://user-images.githubusercontent.com/89928062/192582984-f3c2b8b8-ce46-44a1-bd6e-7f4c7b514b43.png)
![2022-09-27_13h23_32](https://user-images.githubusercontent.com/89928062/192582997-b0be6acb-7bef-4559-a288-ec8ec3d4b006.png)
![2022-09-27_13h24_06](https://user-images.githubusercontent.com/89928062/192583015-2ed609d7-0947-42ba-a04a-2dc037092b0a.png)

**Comment by aslushnikov** [comment]
This might be related to https://github.com/microsoft/playwright/issues/17500

Are you sure you have playwright 1.25 and not 1.26? Can you try updating to Playwright 1.26.1 and check if it fixes things?
