### ISSUE TITLE
[Question] Using Request as part of the cleanup step for a fixture

### ISSUE THREAD

**Issue by Addison-Dalton** [microsoft/playwright#17642]
I've created a custom fixture that makes a call to my API to create an object to test against. As part of the clean-up step, I have it make a call to delete the created object. This is, however, returning the following error: `apiRequestContext.delete: Request context disposed.` when making the delete call.

Here's how I've setup the fixture that extends from base:
```typescript
// fixture used to extend functionality on playwright's base "test"
export const test = base.extend<CustomFixtures, { registerSelectors: void }>({
  // playwright testing library
  ...testingLibrary,
  // custom fixtures
  mockObject: async ({ request }, use) => {
    const object = new PlaywrightObject(request);

    await use(object);

    // cleanup
    await object.delete();
  },
  // other custom fixtures
  ...
});
```

_Bonus questions if I may_: Does the cleanup step for a fixture run if a test fails?

Thank you!

**Comment by aslushnikov** [comment]
> Does the cleanup step for a fixture run if a test fails?

@Addison-Dalton yes it does!

> This is, however, returning the following error: apiRequestContext.delete: Request context disposed. when making the delete call.

I tried reproducing this with the following but with no luck:

```ts
// a.spec.ts
import { test } from '@playwright/test';

const fooTest = test.extend<{ superbFixture: boolean }, {}>({
  superbFixture: async ({ request }, use) => {
    console.log((await request.get('https://aslushnikov.com')).status());

    await use(true);

    console.log((await request.delete('https://aslushnikov.com')).status());
  },
});

fooTest('should work', async ({ superbFixture }) => {
  console.log('done');
});
```

Running this with `npx playwright test` was successful to me. Could you please build a similar repro that illustrates the issue and file a new one?

**Comment by Addison-Dalton** [comment]
@aslushnikov Thank you for responding, and the info provided! I'll see if I can't get a more detailed repro. In the meantime, may I ask what would typically cause `apiRequestContext.delete: Request context disposed` to be thrown?

**Comment by Addison-Dalton** [comment]
Following up on this. The issue was inside the `delete` method. I was not using `await` with the `request.delete`. Thanks again!
