### ISSUE TITLE
[Question] I would like to ask if there is an appropriate playwright reporter

### ISSUE THREAD

**Issue by CHHome** [microsoft/playwright#17647]
I use **playwright** for secondary development，But I haven't found the right reporter。**playwright test** has the right report。But I didn't find a reporter for **playwright**。I would like to ask if there is an appropriate **playwright** reporter。

**Comment by aslushnikov** [comment]
Reporters are a part of Playwright Test package; Playwright doesn't have reporters since it doesn't have a notion of a "test", "test suite" and so on.

So please use Playwright Test instead!
