### ISSUE TITLE
[Feature] Allow opening trace via Trace Viewer for WSL 2 (Tracing "[...] must be loaded over the http:// or https:// protocols.")

### ISSUE THREAD

**Issue by bennettdams** [microsoft/playwright#17658]
Right now, it is not "easy" use the trace viewer when running Playwright via WSL 2.

I would like to open a trace file via the built-in HTML report, clicking on the preview image here:

![image](https://user-images.githubusercontent.com/29319414/192776090-845b94b2-9498-4ddb-a438-bc75f4238248.png)

But this opens an error message instead:

"_The Playwright Trace Viewer must be loaded over the http:// or https:// protocols._"

![image](https://user-images.githubusercontent.com/29319414/192776045-4c966a1b-e7c6-4a7c-9f47-5a610e900a3a.png)

I understand why this error is there, as the URL when clicking looks like this (native WSL file path):

`file://wsl%24/Ubuntu-20.04/home/bennett/code/.../reports/summary/trace/index.html?trace=file://wsl%24/Ubuntu-20.04/home/bennett/code/.../reports/summary/data/c80a98de4270c7e134819f1c713cfc798d36bb6c.zip`

I think you can't even open the trace viewer via the CLI (`npx playwright show-trace trace.zip`), as the source files are also located in WSL.
In my case even that wouldn't work, because the trace files have no specific name, but rather an auto-generated one, as I use the `trace` option in my `playwright.config.ts`, which makes it hard to use.

My workaround right now is to download the ZIP via the HTML report (one click) and upload it to `https://trace.playwright.dev/` (Thanks for the site, btw!) - but as you can imagine, clicking the preview image in the HTML report to open the trace would be way more comfortable.

**Comment by mxschmitt** [comment]
How do you open the HTML report?

It should open automatically and served correctly, alternatively you can use `npx playwright show-report`. Does shown issue about opening trace viewer when clicking on it appear that way?

Or do you open the HTML files of HTML report manually?

**Comment by bennettdams** [comment]
> How do you open the HTML report?

Right now I have to open the HTML report via the File Explorer. So I go to 

`\\wsl$\Ubuntu-20.04\home\bennett\code\...\reports\summary`

and open the `index.html` there.


> alternatively you can use npx playwright show-report

Oh wow, I was not aware of that! Opening the report via `show-report` also makes the trace viewer work!

Thanks a lot 🥳
