### ISSUE TITLE
[BUG] Internal server error when pulling image

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#17654]
We are pulling the docker image in our CI for Playwright tests.
After a few months, we now got this for the first time:

```
Pulling image: [mcr.microsoft.com/playwright:v1.26.0-focal](http://mcr.microsoft.com/playwright:v1.26.0-focal)
Error response from daemon: received unexpected HTTP status: 500 Internal Server Error
Error response from daemon: toomanyrequests: Too many requests. Please visit https://aka.ms/acr/skus#sku-feature-matrix to view limits of all service tiers.
```

**Comment by aslushnikov** [comment]
(Note to self: added this to the tomorrow's team discussion agenda)

**Comment by aslushnikov** [comment]
@Exoow does it still fail for you btw? It might've flaked as we hit some quotas, but the `docker pull` reliably works for me now.

**Comment by Exoow** [comment]
@aslushnikov No, it was only during a brief period for me (and others, as discussed on Slack).
But @mxschmitt suggested to log the issue here.

**Comment by aslushnikov** [comment]
We bumped the quotas, so this shouldn't happen much anymore.
