### ISSUE TITLE
[Question]How do i run codegen on edge browser?

### ISSUE THREAD

**Issue by vrait** [microsoft/playwright#17661]
I am unable to run codegen on edge browser with below command

npx playwright codegen --channel=msedge

**Comment by mxschmitt** [comment]
Works for me! What error do you get? What happens when you execute the command?

**Comment by vrait** [comment]
Hi, Thanks for your response. I am getting below error 
![image](https://user-images.githubusercontent.com/70270827/192927461-cf5418fc-35f5-46af-bfb3-befee4237295.png)

**Comment by vrait** [comment]
Also i am using Windows Server 2012

**Comment by mxschmitt** [comment]
Try to install msedge? `npx playwright install msedge` maybe it's installed to a different location! Where is the .exe located?

**Comment by aslushnikov** [comment]
Closing as per above! Make sure to install msedge before using it for codegen.
