### ISSUE TITLE
[BUG] Use of storageState doesn't work on retry for tests that execute logout in some step

### ISSUE THREAD

**Issue by mariaceo** [microsoft/playwright#17660]
**Context:**
- Playwright Version: v1.22
- Operating System: Linux (for the CI) and  Mac
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Chromium

**Describe the bug**

In our test suite we store the storageState during the global setup and reuse it to avoid login.
However, we have a test where we logout at some point and login with another user.
If the test fails, then the retry will open a new browser that doesn't have the authenticated state and it requires to login again, a step that we don't have at the beginning of our test anymore since we reuse the storageState. So the test fails even before starting.

Shouldn't the retry start with an authenticated state, as the first run of the test?

This does not happen for tests that don't logout during some steps. Those work just fine with retry.

**Comment by mariaceo** [comment]
Sorry, I thought the description would be self explanatory. Here is how we use it:
```
// global-setup.ts
import { chromium, FullConfig } from '@playwright/test'

async function globalSetup(config: FullConfig) {
  const { baseURL } = config.projects[0].use

  const browser = await chromium.launch()
  const user1Page = await browser.newPage()
  await user1Page.goto(baseURL)
  await user1Page.locator('input[name="username"]').fill(user1username)
  await user1Page.locator('[placeholder="Password"]').fill(user1password)
  await user1Page.locator('#kc-login').click()

  await user1Page.context().storageState({ path: 'user1StorageState.json' })
  await user1Page.close()

  const user2Page = await browser.newPage()
  await user2Page.goto(baseURL)
  await user2Page.locator('input[name="username"]').fill(user2username)
  await user2Page.locator('[placeholder="Password"]').fill(user2password)
  await user2Page.locator('#kc-login').click()

  await user2Page.context().storageState({ path: 'user2StorageState.json' })

  await browser.close()
}

export default globalSetup
```
```
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  use: {
    storageState: 'user1StorageState.json'
  }
};
export default config;
```
```
//test.ts

test.beforeEach(async ({ page }) => {
  await page.goto('/')
})

test.use({ storageState: 'user2StorageState.json' })
test('portals', async ({
  applicationsPage,
  publishApplicationPage,
  mainHeaderPage,
  loginPage,
  page
}) => {
  await test.step('get first application id', async () => {
    await applicationsPage.openApplication('applicationName1')
    await applicationsPage.navigateToPublishApplicationPage()
    publishedApplicationId1 = publishApplicationPage.getApplicationId()
  })

   // some other steps on the app
   //...

    await test.step('logout', async () => {
      await mainHeaderPage.clickUserMenuItem(userMenu.Logout)
    })

    await test.step('login as admin', async () => {
      await loginPage.login(getCredentialsForUser('anotherUserWIthNoStoredState'))
    })

    await test.step('create first application', async () => {
      await applicationsPage.createNewApplication(applicationName1)
    })
   
   //continue until test fails
})
```

In this setup, when the test fails the retry starts without being logged in.
And if the user 'anotherUserWIthNoStoredState' is created during the test, then I cannot use this https://playwright.dev/docs/auth#testing-multiple-roles-together

**Comment by yury-s** [comment]
> In this setup, when the test fails the retry starts without being logged in.

When you logout does the server invalidate the session cookies? This would make state written to `user2StorageState.json` invalid and next time even if you start with the same storage state on retry the user won't be logged in.

The storage state is loaded from the file on every retry. You can check that by inspecting output of `await context.storageState()` in the beginning of the test. My hunch is that you have to login again after logging out as the server side state changes.

**Comment by pavelfeldman** [comment]
> In our test suite we store the storageState during the global setup and reuse it to avoid login.
> However, we have a test where we logout at some point and login with another user.

Playwright does not support this use case, you can only reuse valid logged-in state throughout the entire run.
