### ISSUE TITLE
[Question] How to get text of selected dropdown text 

### ISSUE THREAD

**Issue by yeassine** [microsoft/playwright#17663]
i Have following code:
_page.frameLocator("#iframeContainer").locator("//label[@class='db-select__label']/select").selectOption(index);_

after selecting the dropdown i will get the content (Text) of selected option. 
I tried lot of things but it doesn't work.
thank you for your help

**Comment by mxschmitt** [comment]
This will work:

`page.frameLocator("#iframeContainer").locator("//label[@Class='db-select__label']/select").inputValue();`

See here: https://playwright.dev/docs/api/class-locator#locator-input-value

**Comment by mxschmitt** [comment]
then you can do the following:

```js
console.log(await page.frameLocator("#iframeContainer").locator("//label[@Class='db-select__label']/select").evaluate(e => e.options[e.selectedIndex].innerText)
```

**Comment by yeassine** [comment]
thanks a lot, it works mxschmitt :), with Java is the expression like this:
String selectedtext=page.frameLocator("#iframeContainer").locator("//label[@Class='db-select__label']/select").evaluate("e => e.options[e.selectedIndex].innerText").toString();

**Comment by JeroenHeemskerk** [comment]
I have a simular problem, and the solution works, but it is not a nice sokution with the evaluate etc. 
I would like to do something like 
`page.frameLocator("#iframeContainer").locator("//label[@Class='db-select__label']/select").inputText();` 

mayby an addition to the Locator class?
