### ISSUE TITLE
[Question] Failed soft assertions are retriggering beforeAll hook within test.describe group

### ISSUE THREAD

**Issue by szuszik** [microsoft/playwright#17662]
Hello, I've got a question regarding soft assertions and their impact on restarting tests - currently, I'm running several tests in one context and whenever soft assertion fails in the middle of test, worker is scrapping browser process to relaunch it with fresh context. My question is, is there a way to prevent it from happening and allow the test group to finish executing to avoid prelonging the duration of tests, then to throw the results?

The example of my code can be found below:

```typescript
import { test, Page, expect } from '@playwright/test';

import { styleCriteria } from './data/cssCriteria';
import { LoginPage } from './models/LoginPage';

const { colours, sizes } = styleCriteria;

let page: Page, loginPage: LoginPage, employeeListPage: EmployeeListPage;

test.describe('UI Tests - Items', () => {
  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage({
      ignoreHTTPSErrors: true,
      httpCredentials: loginData.httpCredentials,
    });

    loginPage = new LoginPage(page);
    employeeListPage = new EmployeeListPage(page);

    await page.goto('https://localhost:3000/');
    await loginPage.loginFirstStep(loginData.login, loginData.password);
    await loginPage.loginSecondStep(loginData.pin);
  });

  test.afterAll(async () => {
    await page.close();
  });

  test('Item number one is visible ', async () => {
    await expect.soft(item).toBeVisible();
  });

  test('Items are visible', async () => {

    await expect.soft(item2).toBeVisible();
    await expect.soft(item3).toBeVisible();
    await expect.soft(item4).toBeVisible();
    await expect.soft(item5).toBeVisible();
    await expect.soft(item6).toBeVisible();
    await expect.soft(item7).toBeVisible();
  });

  test('Item 8 is styled properly', async () => {
    //Check for color
    await expect
      .soft(item8, `Color should be #${colours.greyDarkest}`)
      .toHaveCSS('color', hexToRgb(colours.greyDarkest));
    //Check for size
    await expect
      .soft(item8, `Font size should be ${sizes.headingRegular}`)
      .toHaveCSS('font-size', sizes.headingRegular);
  });

  test('Item 9 is styled properly', async () => {
    //Check for color
    await expect
      .soft(item9, `Color should be #${colours.greyDarkest}`)
      .toHaveCSS('color', hexToRgb(colours.greyDarkest));
    //Check for size
    await expect
      .soft(item9, `Font size should be ${sizes.subtitleSmall}`)
      .toHaveCSS('font-size', sizes.subtitleSmall);
  });

  test('Item value is visible', async () => {
    await expect.soft(item10.nth(0)).toBeVisible();
  });
});
```

As previously mentioned, if any of those assertions fail, the beforeAll hook is retriggered. Is there any way to avoid it and wait for the tests to execute until the end?

Thank you for your answers!

**Comment by aslushnikov** [comment]
> My question is, is there a way to prevent it from happening and allow the test group to finish executing to avoid prelonging the duration of tests, then to throw the results?

@szuszik no, there's no way. Failing tests might corrupt global state in an unpredictable manner, so we have to re-create worker & run the `beforeAll` hook.

Depending on your logging in state, you might benefit from the [reusing authentication state](https://playwright.dev/docs/next/test-api-testing#reusing-authentication-state) approach.

Hope this helps!

**Comment by szuszik** [comment]
@aslushnikov thank you for your answer! I will try to work around it with the auth state reuse as you suggested and tweak the structure of tests, then.

Have a great day!
