### ISSUE TITLE
[Question] How to unsubscribe from page's event listners

### ISSUE THREAD

**Issue by changhuixu** [microsoft/playwright#17679]
For example, after
```csharp
 page.Dialog += (_, dialog) =>
            {
                // deal with (dialog.Message);
                dialog.AcceptAsync();
            };
```

How can I remove this event listener?  Thank you.

**Comment by aslushnikov** [comment]
Looks like you should store the lambda function in a variable and unsubscribe it later: https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/events/how-to-subscribe-to-and-unsubscribe-from-events#unsubscribing

**Comment by changhuixu** [comment]
@aslushnikov Thank you. Will the `page` automatically unsubscribe it?
`page` is initialized by ` var page = await browser.NewPageAsync();`

**Comment by aslushnikov** [comment]
> Will the page automatically unsubscribe it?

No, you'll need to unsubscribe explicitly

**Comment by changhuixu** [comment]
Good to know. Thank you very much.
