### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by sam-ashford** [microsoft/playwright#17678]
I need playwright to open multiple tabs in one browser all using different proxies. Depending on which line you comment out, I can either open multiple tabs in one browser (and proxies don't work). Or open multiple browsers where proxies do work. It appears to be either or. I need multiple tabs in one window with different proxies for each tab. Any ideas? Been at this weeks now.

`
const playwright = require('playwright');

(async () => {

    const browser = await playwright.chromium.launch({ headless: false, proxy: { server: 'per-context' } });
    const context = await browser.newContext({ headless: false, proxy: { server: 'per-context' } });

    const page = [];

    for (let i = 0; i < 2; i++) {

        //page[i] = await browser.newPage( //Proxy works but opens in different browsers
        //page[i] = await context.newPage( //Opens tabs in same browser but proxies don't work
        { proxy: { server: 'http://193.8.138.56:4075', username: 'bhxjan', password: 'v4swu77kv' } }
        );
        page[i].goto('https://www.whatismyip.com');

    }

})();
`

**Comment by aslushnikov** [comment]
>  I need multiple tabs in one window with different proxies for each tab. A

@sam-ashford This is not possible; we set up proxies per browsing contexts.
