### ISSUE TITLE
Playwright component error: Cannot find module 'vite/package.json'

### ISSUE THREAD

**Issue by westwai** [microsoft/playwright#17672]
I'm receiving the following error when trying to run playwright component tests in github CI. Running it locally it works fine. Would greatly appreciate the help

Error: Cannot find module 'vite/package.json' Require stack:

/home/runner/work/project/project/node_modules/@playwright/test/lib/plugins/vitePlugin.js
/home/runner/work/project/project/node_modules/@playwright/experimental-ct-react/index.js
/home/runner/work/project/project/playwright-ct.config.ts
/home/runner/work/project/project/node_modules/@playwright/test/lib/loader.js
/home/runner/work/project/project/node_modules/@playwright/test/lib/runner.js
/home/runner/work/project/project/node_modules/@playwright/test/lib/cli.js
/home/runner/work/project/project/node_modules/playwright-core/lib/cli/cli.js
/home/runner/work/project/project/node_modules/playwright-core/cli.js
/home/runner/work/project/project/node_modules/@playwright/test/cli.js

**Comment by aslushnikov** [comment]
@westwai Nothing from the top of my head to help here – not enough information. We'd need a repro that we can run & debug. Please re-file with such a repro!
