### ISSUE TITLE
[Question] - Hooks and teardown

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#17670]
Hi guys, quick question, is it always recommended to use test.afterAll or afterEach when using the page fixtures in a spec file ?
I have a couple of specs and noticed some issues when running them on azure with the error:

"Test timeout of 30000ms exceeded while tearing down "context"."

It is intermittent , but seems to have stopped when adding page.close() in the afterEach hook. However, I could see there is no afterEach hook in the example class created automatically when installing playwright (So I was not sure if it is 100% needed or not)

I have one spec with different test cases using the page fixture and another one that loops through a list of values to execute the tests, and it happened in both of them. I.e:

Example1:

```
text.describe({
   test('test1' , async ({page})=> {
      //do something
   })
   
   test('test2' , async ({page})=> {
      //do something else
   })
})
```

Example2:

```
test.describe({
        for(const value of values){
          test(`test ${value}`, async ({ page }) => {
          await page.goto(`/value`);
        });
    }
})
```

**Comment by aslushnikov** [comment]
> Hi guys, quick question, is it always recommended to use test.afterAll or afterEach when using the page fixtures in a spec file ?

@imartinflores No, this should not be needed. I'm surprised it did help you though – what browser do you use that exhibits this error?

**Comment by lianapache** [comment]
@aslushnikov I started seeing the same  "Test timeout of 30000ms exceeded while tearing down "context" error after upgrading @playwright/test from `1.25.2` to `1.26.1`. The error occurs in all browsers we use - webkit, chromium, and firefox.

**Comment by imartinflores** [comment]
@aslushnikov thanks, I am using Chromium. Tbh, that was my assumption, as I ran it a few times using the hooks and it didnt fail, but it was also intermittent..  But Now that @lianapache mentioned that, I am also on PW 1.26 .. could be a problem on this version?

**Comment by aslushnikov** [comment]
@lianapache @imartinflores Any chance you can supply us with a repro?

**Comment by imartinflores** [comment]
@aslushnikov I can try creating my own repo (with the same kind of tests) and see if I can reproduce it somehow. I can't share the one I am working with as it is a private working repo unfortunately..

**Comment by aslushnikov** [comment]
That would be awesome. We didn't find anything that might affect this kind of behavior change from 1.25 to 1.26, so a repro would drastically help us debug this issue. 

Let me close this for now, but please file another issue as you have a repro. (this way we won't accidentally forget about it).

Thanks!

**Comment by imartinflores** [comment]
Thanks a lot for looking into @aslushnikov ! I will give that a try and if I can find how to reproduce it, will create a new one. Thanks again!

**Comment by imartinflores** [comment]
Hi @aslushnikov , not sure if this can be of some help. I have tried reproducing the issue with a fresh playwright project and I couldn't tbh, so I assume it could be something to do with the app under test. I've turned on traces and videos and I could see this:

The actions seems ok:
![image](https://user-images.githubusercontent.com/17011557/193235652-c214d4a1-4a03-4b7e-a391-875e8a499336.png)

The trace indicates a timeout:
![image](https://user-images.githubusercontent.com/17011557/193235744-f846d047-f8ad-40d8-8533-922fa27d40cc.png)

But on the video, I can see the error message being displayed after clicking the "Validate" button that was supposed to "Time Out" in the Trace:
![image](https://user-images.githubusercontent.com/17011557/193235872-fd61493b-1d17-45bd-9382-b23ed82777ce.png)

The test is quite simple, looping through a json file to get some values from there, and in total 5 tests are running in 5 workers:

```
test.describe("My Tests", ()=>{
 for(const val of values){
   test(`Display error message ${val.name}`, ({page})=> {
     await page.goto()
     await page.locator("#textbox").fill("")
     await page.locator("#Validate").click()
     await expect(page.locator("error message")).toContainText("ErrorMessage")
   })
   }
})
```

Any suggestions of where to look at or get more logs about it ?
Thanks!

**Comment by imartinflores** [comment]
And in top of that, I've downgraded pw to 1.25 and ran the same tests on ci with both versions. I could see the issue once with 1.26 but never on 1.25

**Comment by imartinflores** [comment]
Seeing the issue on 1.25 intermittently as well, so I definitely assume it has something to do with the app itself. However the Traces and what can be seen on the video confused me a little bit. In the last Trace I got, I can see a page.close() timing out

**Comment by TomasHubelbauer** [comment]
See #17869 - this same error message also happens when you forget an `await` when calling a Playwright API. Very unintuitive so I hope this comment helps future Google travelers.

**Comment by Varun-L** [comment]
> See #17869 - this same error message also happens when you forget an `await` when calling a Playwright API. Very unintuitive so I hope this comment helps future Google travelers.

Thank You so much !!!! This was the issue all along!!!
