### ISSUE TITLE
Playwright scripts are not running on the firefox{Error: browserContext.newPage: Page closed}[BUG]

### ISSUE THREAD

**Issue by anjireddy5817** [microsoft/playwright#17688]
Whenever I started running scripts on the firefox browser getting below error:(Playwright version: 1.25.2)
browserContext.newPage: Page closed

config file:

projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },

**Comment by aslushnikov** [comment]
@anjireddy5817  please re-file following issue template and with a proper repro. Otherwise we won't be able to help!
