### ISSUE TITLE
[Feature] Add test timings in terminal to html reporter

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#17683]
Currently, the `list` reporter shows test timings in the terminal output, but the `html` reporter doesn't.
Seeing the test timings immediately is really useful for tweaking tests. 
But switching from the `html` to the `list` reporter just for that is not a viable option since that would mean losing viewable test results. There's also no obvious reason to withhold the timings feature from the `html` reporter.

So I would like to suggest that the test timings in the terminal ouput be added to the `html` reporter as well.

---

<details>
  <summary>Original post</summary>
  
When a Playwright test case passes, the terminal output displays its duration:
![Screenshot_20220928_202859](https://user-images.githubusercontent.com/98180468/192912126-3e15c4a2-e443-4c81-a013-bd4988d9bcf0.png)

But when that test case fails, the duration is not displayed:
![Screenshot_20220928_202923](https://user-images.githubusercontent.com/98180468/192912138-269d1c8b-7c41-48af-85a6-480bd25b9ac7.png)

It would be really useful to have it output there as well in order to finetune the test timeouts (since those have to be orientated around the usual fail duration). Without that, it's always guesswork and trial & error until you've found the right test timeout for your test case.

So I would like to suggest adding the test case duration for fails in the terminal.

---
And while we're at it, I've also noticed that the duration shown in the terminal rounds up to full minutes:
![Screenshot_20220928_205706](https://user-images.githubusercontent.com/98180468/192914635-b63a2877-01da-496a-9945-b08c715cfaf3.png)
It would be great if it could show the same value as in the test report:
![Screenshot_20220928_205807](https://user-images.githubusercontent.com/98180468/192914677-0797a953-3999-406c-a5b6-981fbaf30b86.png)
(these two screenshots are from one test run)

</details>

**Comment by aslushnikov** [comment]
The duration next to `1 passed` is not the test duration - it's a whole Playwright Test run duration. 

> It would be really useful to have it output there as well in order to finetune the test timeouts (since those have to be orientated around the usual fail duration).

You can use list reporter to show test timings:

```bash
npx playwright test --reporter list
```

Yields the following result with failed test timing:
<img width="1024" alt="Screen Shot 2022-09-30 at 3 34 12 AM" src="https://user-images.githubusercontent.com/746130/193228594-7280cba2-fc33-450f-bf3c-546b7b6afb21.png">

**Comment by azad-derakhshani-GS** [comment]
Ah ok, thanks for letting me know! I wasn't aware of that.
Then I'm wondering - a bit off an off-topic question -  why is the total duration higher than the test case duration when I run only one test case (see the example in my OP, 1.6m vs 2m)?

Anyway, in that case, I would like to change the feature request and instead suggest that the test timings also be displayed in the terminal when selecting the `html` reporter option.

Switching to the `list` reporter is not really an option since we would lose the viewable test report.  
And unless I'm missing something, it makes no sense to withhold the timings in the terminal output from the html reporter option.

**Comment by yury-s** [comment]
> Then I'm wondering - a bit off an off-topic question - why is the total duration higher than the test case duration when I run only one test case (see the example in my collapsed OP, 1.6m vs 2m)?
> 

Some time is spent on fixtures setup, framework startup etc. See also https://github.com/microsoft/playwright/issues/11334

> Anyway, in that case, I would like to change the feature request and instead suggest that the test timings also be displayed in the terminal when selecting the `html` reporter option.
> 
> Switching to the `list` reporter is not really an option since we would lose the viewable test report. And unless I'm missing something, it makes no sense to withhold the timings in the terminal output from the `html` reporter option.

You can run the tests with multiple reporters, so if you want to see the timings in the terminal as well as get html report you can use the following command:

```sh
npx playwright test --reporter=list,html
```

**Comment by azad-derakhshani-GS** [comment]
Oh I didn't know that! Thank you, that helps too. :)

Do we have that documented somewhere? I couldn't find anything, always thought you can only use one reporter at a time.
