### ISSUE TITLE
[Question] How does the nth-match pseudo class work

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#17689]
Apologies in advance if this has been asked already.

Playwright has this nifty little feature, when we can use the `nth-match` pseudo class to locate elements - an example being given in the documentation [here](https://playwright.dev/docs/selectors#pick-n-th-match-from-the-query-result) .

This is different from the `nth-child` concept as is mentioned on the documentation itself. I wanted to know how does the `nth-match` selection works internally? Does it uses the CSS 4 `nth-match` concept?  How does `nth-match` is different from the `nth` index selection? 

As per [this](https://drafts.csswg.org/selectors-4/#the-nth-match-pseudo), CSS4 has removed `nth-match` for `nth-child`, does it have any bearings on this working?

**Comment by aslushnikov** [comment]
> This is different from the nth-child concept as is mentioned on the documentation itself. I wanted to know how does the nth-match selection works internally? Does it uses the CSS 4 nth-match concept? 

@zac11 playwright implements a bunch of features atop of browser CSS. The `nth-match` is one of this enhancements.

> How does nth-match is different from the nth index selection?

I guess by the `nth-index` you mean `nth-child`? In this case, `nth-match` selects the **match** by index, whereas the `nth-child` selects the **child** by index.

> As per [this](https://drafts.csswg.org/selectors-4/#the-nth-match-pseudo), CSS4 has removed nth-match for nth-child, does it have any bearings on this working?

Nope, we have our own implementation. If you're curious:

https://github.com/microsoft/playwright/blob/33bbb15e30f0deaf65f7581b94330932bd79530a/packages/playwright-core/src/server/injected/selectorEvaluator.ts#L485-L496

Hope this helps!
