### ISSUE TITLE
[BUG] page.on('pageerror') not always catch exceptions on WebKit

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#17696]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Mac
- Node.js version: 18.3.0
- Browser: WebKit
- Extra: 

playwright test e2e/tests --project=Webkit --config=e2e/mainConfig.ts

**Code Snippet**
```
test("Console collection", async ({page}) => {
  const msgarr = [];
  const errarr = [];
  page.on('pageerror', (exception) => {
    console.log(`Uncaught exception: "${exception}"`);
    errarr.push(exception);
  });
  page.on('console', (msg) => {
    console.log(`Error text: "${msg.text()}"`);
    msgarr.push(msg);
  });
  await page.goto("http://localhost:3020")
  const appShell = await new AppShell(page);
  const atoPage = await appShell.clickAtoButton();
  console.log(msgarr, errarr)
})
```
**Config**
```
  webServer: {
    command: 'npm run start',
    port: 3020,
    reuseExistingServer: !process.env.CI,
  },
```

**Describe the bug**
My localhost web server has a page with unhandled exceptions and I would like to check in the test that this particular exception happens.
on Chromium, it works without any issue every time.
on Webkit the `page.on('pageerror')` doesn't always catch the exception.
when I'm in debug mode with developer tools open I see in the console the exception, but it doesn't register in the event listener.

I've also run on 'repeat' of 100 times and chromium always passes while on Firefox and Webkit it always has few fails.

Unfortunately, I can't upload my local host, I've tried to find a similar website with an unhandled error but wasn't able to find one.
it's simple single-page loading with exception

**Comment by aslushnikov** [comment]
@ValorHeart  We have quite a bunch of tests that validate this behavior across all our browsers: https://github.com/microsoft/playwright/blob/main/tests/page/page-event-pageerror.spec.ts

And yet there's some behavior that we don't cover. It's not actionable without us reproducing & running locally, so I'd appreciate if you can build a small reproduction snippet that demonstrates the issue!

I'll close this for now, but please do not hesitate to re-file once you have a repro!
