### ISSUE TITLE
Reporters are a part of Playwright Test package; Playwright doesn't have reporters since it doesn't have a notion of a "test", "test suite" and so on.

### ISSUE THREAD

**Issue by CHHome** [microsoft/playwright#17692]
Reporters are a part of Playwright Test package; Playwright doesn't have reporters since it doesn't have a notion of a "test", "test suite" and so on.

So please use Playwright Test instead!

_Originally posted by @aslushnikov in https://github.com/microsoft/playwright/issues/17647#issuecomment-1260554052_
      
thank you
I know what you said.
actually，I use playwright for secondary development，Just like yours playwright test.
The difference is that our philosophy is no code（Generate code by recording）
Maybe I need to write my own reporter

**Comment by CHHome** [comment]
thank you
I know what you said.
actually，I use playwright for secondary development，Just like yours playwright test.
The difference is that our philosophy is no code（Generate code by recording）
Maybe I need to write my own report

**Comment by aslushnikov** [comment]
> Maybe I need to write my own reporter

Sounds reasonable to me!
