### ISSUE TITLE
[BUG] Safari tests fail due to "browserContext.newPage: Protocol error"

### ISSUE THREAD

**Issue by MarcoSpoerl** [microsoft/playwright#17699]
**Context:**
- Playwright Version: 1.26.1
- Operating System: macOS 10.15.7
- Node.js version: 16.17.1
- Browser: WebKit
- Extra: n/a

**Code Snippet**

This is one test of many showing the same error.

```javascript
test.describe("sign-in", () => {
  test.beforeEach(async ({ page }) => {
    await page.goto("/");
  });

  test.afterEach(async ({ page }) => {
    await expect(page).toHaveURL(
      /^https:\/\/api\.twitter\.com\/oauth\/authenticate/
    );
    await page
      .locator('[id="username_or_email"]')
      .fill(process.env.TWITTER_TEST_USERNAME || "");
    await page
      .locator('[id="password"]')
      .fill(process.env.TWITTER_TEST_PASSWORD || "");
    await page.locator('[id="allow"]').click();
    await expect(page).toHaveURL("/searches");
  });

  test("main sign-in is working", async ({ page }) => {
    await page.locator('button:has-text("Sign in with Twitter")').click();
  });
});
```

**Describe the bug**

I haven't touched the test specs or the config. Yet all Safari-based tests (both mobile and desktop) stopped working. Chrome and Firefox still work fine.

I upgraded Playwright from 1.25.1 to 1.26.1, before this error showed up.

The only hint I have is this error:

browserContext.newPage: Protocol error (Page.setForcedColors): 'Page.setForcedColors' was not found [{"code":-32601,"message":"'Page.setForcedColors' was not found"}]

**Comment by aslushnikov** [comment]
@MarcoSpoerl yes, Playwright 1.25 was the last Playwright to support WebKit @ MacOS 10.15

Please either update MacOS to 11+ or keep Playwright version 1.25!
