### ISSUE TITLE
[Question] Check of visibility of error toast message or Error in the logs

### ISSUE THREAD

**Issue by LadaVarga** [microsoft/playwright#17700]
It is somehow possible to check if after every action (page....) there is no new ERROR toast message/console error (with filter)? 
Sometimes it throws when we click on some button or on some page. Sometimes the ERROR toast didn't break the flow of the test, but I would like to catch these too.

**Example:**
1. Click on the button.
2. Check the result.
3. Result is ok.

Actual: Test passed as the result is ok.
Expected: I would like to break test when ERROR toast appeared or selected error in console appeard.
![2022-09-29 16_34_55-Details](https://user-images.githubusercontent.com/22859476/193061000-13c3a5b1-2a33-494d-b828-35002aaf757a.png)

**Comment by aslushnikov** [comment]
> Expected: I would like to break test when ERROR toast appeared or selected error in console appeard.

@LadaVarga you can setup a trigger in the beginning of the test like this:

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  // Setup a trigger to fail the test once the toast appears.
  // NOTE: no await here!
  page.locator('text=Status code')
      .waitFor()
      .catch(() => {})
      .then(() => { throw new Error('toast appeared - test failed!!'); });

  // Do your test automation
  await page.goto('https://example.com');
  await page.evaluate(() => {
    document.body.textContent = 'Status code';
  });
  // ... simulate long-running test automation ...
  await new Promise(x => setTimeout(x, 1000));
});
```

Hope this helps! Please do not hesitate to file more questions - we'll be happy to answer!
