### ISSUE TITLE
[Feature] Support to locate the select_option by text.

### ISSUE THREAD

**Issue by yandong01** [microsoft/playwright#17725]
`<select>`
 ` <option value="red">apple</option>`
`</select>`

Currently, playwright supports to locate by value: **element.select_option(value="red")**

Can we support to locate by the inside text: **element.select_option(text="apple")**?

**Comment by aslushnikov** [comment]
@yandong01 you can match by `label`: options without labels get the text content as a label. Would it work?

**Comment by yandong01** [comment]
> @yandong01 you can match by `label`: options without labels get the text content as a label. Would it work?

Thanks aslushnikov, it works!
