### ISSUE TITLE
Hi all , I am currently facing a very strange situation wherein my test cases are running differently on local terminal and on the ci/cd pipeline in azure . The test pass on the terminal on my local but it is always falling in the pipeline (Im running both tests in the headless mode). Can anyone guide me how to debug my failed tests on the pipeline level ? Can we setup Playwright Trace in the pipeline ? If yes then Please guide me how .[Question]

### ISSUE THREAD

**Issue by viveksuarez7** [microsoft/playwright#17729]

**Comment by aslushnikov** [comment]
To record a trace, please follow our docs: https://playwright.dev/docs/next/trace-viewer-intro#recording-a-trace

Once trace is recorded, you'll need to [upload trace from azure pipeline](https://learn.microsoft.com/en-us/azure/devops/pipelines/artifacts/pipeline-artifacts?view=azure-devops&tabs=yaml).

Hope this helps!

**Comment by viveksuarez7** [comment]
Hi Aslushnikov , Im not a ci/cd expert , so a stupid question would be , how can we view this trace file once its uploaded , currently on the local we can see that the pipeline open it via npx playwright show-trace    .. how will we able to see the trace file and debug it on the ci/cd pipeline ?

**Comment by aslushnikov** [comment]
@viveksuarez7 you should download it from the CI/CD server and then use https://trace.playwright.dev

**Comment by Blue101black** [comment]
@viveksuarez7 did you ever figure out why your tests worked locally but on azure pipeline? I am having same issue where it seems to not be able to load the local dev that I configure in playwright.config.ts
