### ISSUE TITLE
[Question]: Is there a way to export the result of codegen before transforming the result into sometype of code

### ISSUE THREAD

**Issue by lzt007** [microsoft/playwright#17735]
### Your question

Playwright-codegen works amzing in recording web operations. But I can‘t find a way to export the recorded operations as some kind of data. All the options means to export the operations as a kind of code.
I'm trying to make a gui-transformer by pyqt which can analyse and transform operations recorded by any type of recorders.So that I want to find a way to export web operations as data instead of code.
Of course it's possible to analysis operations by reading the code file as a type of text,but I'm sure it's not a good idea.

I have tried to use --save-trace , but I can't find the "frame_locator" operations in the .trace file.Though the click in frame was recorded as "frame.click" with a frameid="frame@xxxxxxx" in it.But I can't find the meaning of this frame id and can't find a frame to select by it.The "frame_locator" operation can't be found in show-trace window either,so I guess the .trace file may not record such infos.

So is there a way to export the result of codegen before transforming the result into sometype of code?

**Comment by yury-s** [comment]
There is no intermediate representation that could be exported from the codegen in a structured / language-agnostic way. So parsing the resulting source file or trace is probably your best bet.

> I have tried to use --save-trace , but I can't find the "frame_locator" operations in the .trace file.

Trace file contains only information that is displayed in the trace viewer, e.g. information on manually performed mouse actions, keyboard actions may be missing there. frame_locator is the concept of the playwright public API whereas trace file uses internal format. You can reverse engineer and use it as you like but bear in mind that it's not standard and may change in the future.

> So is there a way to export the result of codegen before transforming the result into sometype of code?

There is no ready solution but the code is all open source and you are free to change it to your liking and produce output in the format that meets your requirements. I'm going to close the bug as we are not planning any work in that direction.

**Comment by lzt007** [comment]
Thanks， i got that
