### ISSUE TITLE
[BUG]Playwright Inspector cannot be opened

### ISSUE THREAD

**Issue by developer-wlj** [microsoft/playwright#17730]
**Context:**
- Playwright Version: v1.26.1
- Operating System: Windows Server 2019 Datacenter (build 17763)
- python version: python3.9.12
- Browser: Chrome
- Extra: Playwright Inspector

**Code Snippet**

```javascript
python -m playwright codegen
```

**Describe the bug**

Playwright Inspector cannot be opened. The window is blank

https://user-images.githubusercontent.com/55836679/193203811-80fd7e60-b910-4814-8e32-af1dc0c66aac.mp4

**Comment by aslushnikov** [comment]
@developer-wlj do other versions work? Does this machine has any corp policies (you can find these navigating to chrome://policy/)

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
