### ISSUE TITLE
[BUG] Memory increases when a page is visited and does not get cleared

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright#17736]
**Context:**
- Playwright Version: 1.26
- Operating System: Windows / Linux (occurs on both)
- Node.js version: ?
- Browser: All

```
import time

from playwright.sync_api import Playwright, sync_playwright


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()

    # Open new page
    page = context.new_page()

    for _ in range(1000):
        # Go to https://www.amazon.com/
        page.goto("https://www.amazon.com/")
        time.sleep(0.05)
    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
```

For about:blank, the loop is:
```
for _ in range(100000):
        # Go to about:blank
        page.goto("about:blank")
```

**Describe the bug**
Memory usage will increase every time a page is loaded, this scales with page size,

For example, 
Visiting about:blank will increase the memory usage of node only and very slowly leaks, you can see the memory go up, get purged, continue to go up

Example memory usage over time(MB):
30 | 60 | 50 | 80 | 110 | 100

Video attached for about_blank page load spam, no delay for 2 minutes

https://user-images.githubusercontent.com/20302512/193237944-15049d15-576a-4de3-bb01-4088a5ec9327.mp4

Next video is amazon.com page load, 50ms delay between requests for 1 minute, memory usage for node + python is around 1GB from ~38MB at the start

https://user-images.githubusercontent.com/20302512/193238864-fab7cd38-fba9-458d-b3f0-9c783ca0e9bd.mp4

I know there is already a memory leak thread, but I think people are over complicating it, so wanted to produce something much simpler with clear examples.

**Comment by jfp1992** [comment]
To also add, 

about:blank loading only appears to affect the node process
When there is content, it affects python and the node process

**Comment by mxschmitt** [comment]
This is expected, memory gets only flushed when you close the context. In end-to-end testing scenarios its recommended to create a context per test to have a fresh clean isolated in-memory browser profile.

Closing by that as a won't fix.

**Comment by jfp1992** [comment]
> This is expected, memory gets only flushed when you close the context. In end-to-end testing scenarios its recommended to create a context per test to have a fresh clean isolated in-memory browser profile.
> 
> Closing by that as a won't fix.

We have long tests and the test environment doesn't have much memory and this issue is causing problems during testing.

**Comment by maximveksler** [comment]
> This is expected, memory gets only flushed when you close the context. In end-to-end testing scenarios its recommended to create a context per test to have a fresh clean isolated in-memory browser profile.
> 
> Closing by that as a won't fix.

This is truly problematic on across usecase and utilities of the tool. Can we discuss options and implications for changing the decision for "wont fix" ?
