### ISSUE TITLE
[Question] Is it possible to know if it's the last scenario in aftereach?

### ISSUE THREAD

**Issue by ooo2003003v2** [microsoft/playwright#17734]
Hello there. 
I have a probelm for getting the scenario index to check if it's the last one in aftereach. 
Is it possible to know if it's the last scenario in aftereach or get the total count of scenarios in beforeAll?
Thank you.

**Comment by yury-s** [comment]
There is no API for that , what are you trying to achieve? Maybe [reporter](https://playwright.dev/docs/api/class-reporter) API will work for you.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
