### ISSUE TITLE
[Feature] Add InputLabelAsync to Locator to get the selected label of an <select>, simular to the InputValueAsync

### ISSUE THREAD

**Issue by JeroenHeemskerk** [microsoft/playwright#17742]
When you want to get the selected value of a `<select>` you can use the function ILocator.InputValueAsync(options), but when you want de labeltext of the selected value you have to add an evaluate (`evaluate(e => e.options[e.selectedIndex].innerText)`) after it (see [Question] #17663)
This is not a nice solution, It would be better to have a function like inputLabelAsync that returns the text of the selected option.

## Locator.InputLabeAsync(options)
* options <LocatorInputTextOptions?>
  Timeout <[double](https://docs.microsoft.com/en-us/dotnet/api/system.double)?> Maximum time in milliseconds, defaults to 30 seconds, pass 0 to disable timeout. The default value can be changed by using the [BrowserContext.SetDefaultTimeout(timeout)](https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-set-default-timeout) or [Page.SetDefaultTimeout(timeout)](https://playwright.dev/dotnet/docs/api/class-page#page-set-default-timeout) methods.
* returns: <[string](https://docs.microsoft.com/en-us/dotnet/api/system.string)>

Returns input option text for the selected `<select>` element.

Throws for non-input elements. However, if the element is inside the `<label>` element that has an associated [control](https://developer.mozilla.org/en-US/docs/Web/API/HTMLLabelElement/control), returns the text of the control.

## Do you think others might benefit from this as well? 
Yes, when searching for how to get the text of a dropdown i found several people that have the same question.
* [searchresult one](https://stackoverflow.com/questions/66155711/how-can-you-get-the-selected-option-of-a-dropdown-with-playwright)
* [searchresult two](https://github.com/microsoft/playwright/issues/17663)

Also add a function to Expected.ToHaveLabel simular to Expected.ToHaveValue

**Comment by JeroenHeemskerk** [comment]
Sidenote: Also think about what to do with `<select>` with multiple selections

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by Drewtopia** [comment]
It would be good to have something like this!
