### ISSUE TITLE
[Question] How to fix load extension error

### ISSUE THREAD

**Issue by refcpu** [microsoft/playwright#17746]
I tried to load the extension using the following methods:
```
await chromium.launchPersistentContext(userDataDir, {
    channel: 'msedge',
    headless: false,
    viewport: null,
    args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`
    ],
    ignoreDefaultArgs: ['--enable-automation']
});
```

but, occurred this error:
![UnpackedExtensionsError](https://user-images.githubusercontent.com/27007235/193331506-136ce1ed-3596-4567-9fde-bbf2fc4dbe09.png)

How can solve this problem?
Some search results show that Selenium solves the problem by the following methods:
`options.setExperimentalOption("useAutomationExtension", false);`

but, Playwright doesn't know how to apply it.
Please teach me.

**Comment by yury-s** [comment]
Does it work if you remove

```js
 ignoreDefaultArgs: ['--enable-automation']
```
?

What edge version is this? Is it reproducible with Chromium?

**Comment by yury-s** [comment]
Does it reproduce without playwright, i.e. if you start the browser from the command line with the same options? Try something like this:

<path to edge exe>  --disable-extensions-except=<pathToExtension> --load-extension=<pathToExtension> --user-data-dir=<an empty dir>

We need to be able to reproduce it locally to help you.

**Comment by refcpu** [comment]
@yury-s
`--disable-extensions-except= --load-extension= --user-data-dir=`
I tried it, but the result was the same.

Probably because the browser is managed by the local group policy of WindowsOS
![Organization_Error_Message](https://user-images.githubusercontent.com/27007235/193961878-b61f0d32-a6f8-4dd0-b199-470552fee356.jpg)
```
Microsoft Edge is managed by your organization
If you use Microsoft Edge at school or work, it might be managed, or set up and maintained, by your organization. Your organization can set up or restrict certain features, install and block extensions, monitor activity, and control how you use it.

If Microsoft Edge is managed, you can view the policies that are set by your organization on the edge://policy page.
```
ImportExtension flag was false in **edge://policy**

Is it difficult to load extensions using Playwright in this environment?

**Comment by yury-s** [comment]
> Is it difficult to load extensions using Playwright in this environment?

Unfortunately yes, playwright doesn't override the policies, this is similar to the issues described in [this doc](https://playwright.dev/docs/next/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings).

Closing the issue as there is not much we can do on our end.
