### ISSUE TITLE
[Question] Modify Headers to Response

### ISSUE THREAD

**Issue by AutoSponge** [microsoft/playwright#1775]
I'm looking for a way to ADD (or modify) a CSP. For instance, I want to disable all CSS on the page. ByPassCSP relies on a low-level call to the CDP. Network/Fetch seems like the right place, but I'm unsure if the CDP will allow this.

Currently, `route.fulfill` is what I'd want but I really need something like a `tap` on the response, not a full replacement, since I only want to modify the headers before they're sent to the browser.

Is this possible?

**Comment by pavelfeldman** [comment]
There is no response interception available yet, but I wonder if you could `route.abort` all the requests with the `request.resourceType() === "Stylesheet"`. Browsers should tolerate failed CSS requests just fine.

**Comment by AutoSponge** [comment]
@pavelfeldman sadly, that won't help with inline styles.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1774
