### ISSUE TITLE
[Question] how to have globalsetup can return a function that does global teardown. ?

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#17751]
Related to Issue #17575)

@InduKrish your globalsetup can return a function that does global teardown. This way you can re-use all the same data captured by global setup in your global teardown! See [our docs](https://playwright.dev/docs/next/test-advanced#global-setup-and-teardown).

Would it help?

I have gone thru the documentation, did not find examples, can you please provide examples?

**Comment by yury-s** [comment]
```ts
// setup.ts
async function globalSetup() {
  const startTime = Date.now();
  console.log(`START\n`);
  return () => {
    console.log(`Performing tear down after ${Date.now() - startTime} ms\n`);
  }
}

export default globalSetup;
```

In your playwright.config.ts:

```ts
const config: PlaywrightTestConfig = {
  globalSetup: 'setup.ts',
}
```
