### ISSUE TITLE
[BUG] consistent crash after upgrading playwright to 1.26.1

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [microsoft/playwright#17755]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- 1.23.4 works fine, 1.24.0 seems to be the point where it starts failing
- Operating System: [e.g. Windows, Linux or Mac]
- Windows 10
- Node.js version: [e.g. 12.22, 14.6]
- v16.14.2
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Chrome
- Extra: [any specific details about your environment]

## System:
 - OS: Windows 10 10.0.19044
 - Memory: 30.69 GB / 63.95 GB
## Binaries:
 - Node: 16.14.2 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 8.6.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - playwright: 1.23.4 => 1.26.1

**Code Snippet**

Nothing special about the code, just a waitForSelector.
loom video of the crash:
https://www.loom.com/share/20ad4745a9884bff8a2320e106f81122

**Comment by yury-s** [comment]
From the video it looks like a browser bug or the page is running out of memory. We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
