### ISSUE TITLE
Does playwright has self-healing and if yes, do you have reference to example

### ISSUE THREAD

**Issue by miriamluskind** [microsoft/playwright#17756]
Does playwright has self-healing and if yes, do you have reference to example.

Thanks,
Miriam

**Comment by yury-s** [comment]
We have web [assertions](https://playwright.dev/docs/test-assertions), [toHaveScreenshot](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot-1) that auto waits for the image to stabilize etc, but there is no built-in self-healing functionality.
