### ISSUE TITLE
[Feature] Option to start firefox in fullscreen mode

### ISSUE THREAD

**Issue by LuckyMika** [microsoft/playwright#17758]
Title. 
It works for chromium using the flags but firefox doesn't have the command line flags so it would be nice to have this.

**Comment by yury-s** [comment]
The following code will launch it in full screen mode:
```js
    const browser = await firefox.launch({args: ['--kiosk'], headless: false});
```

See also https://github.com/microsoft/playwright/issues/4046

**Comment by Kal-Aster** [comment]
This is actually not a window fullscreen but a fullscreen of the webpage... not the same thing unfortunately
