### ISSUE TITLE
[Feature] Allow to set mime type in set `setInputFiles` for file paths

### ISSUE THREAD

**Issue by grigory-bogush** [microsoft/playwright#17763]
I was trying to upload a file in a test with `.psz` extension. Playwright was setting `application/octet-stream` mime type, but when trying to upload a file through the browser manually (chrome and firefox), for whatever reason the mime type field is empty.

I could not use buffer for a workaround as it has a hard limit of `50mb` which is not enough for my use case.

It might a bit of an edge case, but it would be helpful to get the extra control.

**Comment by yury-s** [comment]
> for whatever reason the mime type field is empty.

Looks like the browsers do not recognize the file extension. Can you pick one of the file extensions that are understood by the browsers? That would automatically work with setInputFiles in Playwright.

We should also support uploading buffers larger than 50Mb but there is no ETA for that as it's a low priority for at the moment.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
