### ISSUE TITLE
[Question] Multiple downloads from one click

### ISSUE THREAD

**Issue by oakstreetrec** [microsoft/playwright#17777]
Hi,

I can't find any examples of how to deal with multiple download events from one click. The canonical example below only returns the first file download that triggers the event. Can you please let me know how this could be modified to catch multiple events (in my case 2).

```
const [download] = await Promise.all([
  // Start waiting for the download
  page.waitForEvent("download"),
  // Perform the action that initiates download
  page.locator(".download-button").click(),
]);
```

**Comment by yury-s** [comment]
You can handle multiple downloads by adding a listener for [`download`](https://playwright.dev/docs/api/class-page#page-event-download) event:

```
page.on('download', download => download.path().then(console.log));
```

**Comment by oakstreetrec** [comment]
Thanks for helping! Is this what you had in mind?

'''
(async () => {
  for (const browserType of [playwright.chromium]) {
    const browser = await browserType.launch();
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto("https://www.chathamfinancial.com/technology/us-market-rates");

    page.on("download", (download) => download.path().then(console.log));
    await page.locator(".download-button").click();

    await browser.close();
  }
})();
'''

This doesn't work for me - I think it's because nothing makes the code wait for the download events. It awaits the click and then just proceeds to the next section of code, in this case simply closing the browser, before any download events have a chance to happen.
