### ISSUE TITLE
[Question] Devtools extension testing

### ISSUE THREAD

**Issue by ferllings** [microsoft/playwright#17773]
Hello team,

Is it possible to test a devtools extension panel?
I suppose it is about to find the right url, but I don't know how.

Thanks for your help.

**Comment by yury-s** [comment]
The easiest way to test such an extension would be to enable [remote debugging](https://blog.chromium.org/2011/05/remote-debugging-with-chrome-developer.html) in the browser with an extension and then navigate to the URL under Playwright. After that you should be able to perform all the actions as with a regular web page.

**Comment by ferllings** [comment]
Thanks for the answer, but I'm not sure to understand your suggestion:
Once I launched my Chrome using remote debugging,
* how do I connect PlayWright with this chrome instance?
* how can I tell PlayWrite to navigate the devtools and find my extension panel?

**Comment by yury-s** [comment]
> * how do I connect PlayWright with this chrome instance?

You run playwright and navigate it to the remote front-end URL the same way you'd do in a browser.

> * how can I tell PlayWrite to navigate the devtools and find my extension panel?

The DevTools remote front-end is a regular web page so you can interact with it using regular playwright APIs.
