### ISSUE TITLE
[Feature] More granular trace configuration

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#17772]
I'm looking for a way to lower trace file size. Currently, with 180 tests suite and considerable amount of failures the report can consume up to 4GB space in my case.

I would be interested in options like:
`snapshot-on-failure-action-only` to keep snapshot on failure action instead of every action in the trace
`on-first-retry-and-failure` currently if retried test passes it will still save trace with `on-first-retry` option, I would like to save it only if retry also fails.

**Comment by yury-s** [comment]
> I would like to save it only if retry also fails.

Why does 'retain-on-failure' not work for you use case?

**Comment by MindaugasMateika** [comment]
`retain-on-failure` will save things on both original run and retry, if I'm not mistaken. I'd love to save it only on retry if it failed.
