### ISSUE TITLE
[BUG] Import Aliases not respected (re-file)

### ISSUE THREAD

**Issue by Morklympious** [microsoft/playwright#17785]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Windows
- Node.js version: 18.6.0 (had this problem on 16.x as well)
- Browser: N/A

Hello! I recently filed #17638 as I was having trouble getting aliasing to work for tests. in some cases, e.g. one where I'm testing the existence of, let's say, a button and I have 5 known button types, I like to reach into the enumeration where those types are declared (usually deep in my component code) and use part of the enum to check for an existing data attribute via `page.locator`

My issue is simply in being able to import these things. 

I've given an small reproduction with a readme here:
https://github.com/Morklympious/playwright-alias-case

- Clone the repository
- `npm install`
- `npm run test`

**Describe the bug**

It seems as though every time I try to import with an alias declared either with my build system (vite) or with `jsconfig.json` and it's `path` options (yes, I do have `baseURL` declared) OR BOTH the config and my build system, I can't seem to import from an alias, as I get this error:

```bash
> playwright test

(node:25664) ExperimentalWarning: Custom ESM Loaders is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

Running 0 tests using 0 workers

Error: Cannot find package 'test' imported from C:\Users\Morklympious\Desktop\test\nested\test\sample.test.js

 no tests found.
=================
```

I've been looking for a clear cut solution but it seems like everyones solution is just hacky at best. Is there any support for this? it seems like playwright is trying to resolve something before it... knows everything? Thanks!

**Comment by yury-s** [comment]
We don't support jsconfig.json, we assume that .js files are ready to execute and don't require preprocessing. The compilation is only performed for .ts files, you can change your code to use typescript and tsconfig.json, it should work. You can call `git apply` on this patch for example:

```
diff --git a/src/test/data.js b/src/test/data.ts
similarity index 100%
rename from src/test/data.js
rename to src/test/data.ts
diff --git a/test/sample.test.js b/test/sample.test.ts
similarity index 88%
rename from test/sample.test.js
rename to test/sample.test.ts
index 97ad4b8..8227174 100644
--- a/test/sample.test.js
+++ b/test/sample.test.ts
@@ -1,5 +1,5 @@
 import { test, expect } from "@playwright/test";
-import message from "test/data.js";
+import message from 'test/data';
 
 test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
     await page.goto('http://localhost:4173');
diff --git a/jsconfig.json b/tsconfig.json
similarity index 85%
rename from jsconfig.json
rename to tsconfig.json
index cae304e..816505e 100644
--- a/jsconfig.json
+++ b/tsconfig.json
@@ -8,5 +8,5 @@
         "test/*" : ["src/test/*"]
       }
     },
-    "include": ["src/**/*"]
+    "include": ["**/*"]
 }
\ No newline at end of file
```

**Comment by Morklympious** [comment]
This is really unfortunate, as my `jsconfig.json` actually extends a `tsconfig.json` by way of `extends`. 

Is there any way to opt in to parsing the `jsconfig` if it extends a typescript config? Is this a feature that might be a welcome change by way of PR?

The reason I ask is because I'm using sveltekit, which generates a `tsconfig` in a build folder that I can extend from a local `jsconfig.json`

**Comment by tivac** [comment]
I'd also like to see an answer here, I don't use `TS` and have a `jsconfig.json`, but that locking me out of being able to use path aliases seems really unfortunate.

**Comment by Bonjour123** [comment]
Any update or workaround ?
