### ISSUE TITLE
[Question] How do I set the number of workers on the per-test basis?

### ISSUE THREAD

**Issue by esokol-d2l** [microsoft/playwright#17788]
Hello,

Thanks for your work on Playwright! It's a totally fantastic product!

Currently, my tests run via GHA workflow using the 3 key supported browsers - chromium, firefox and webkit. My playwright.config file has the recommended setup for the number of workers:

`workers: process.env.CI ? 1 : undefined,`

But due to the nature of one test (updating of the shared app settings), I need to run it sequentially under the 3 browsers, i.e. I effectively need to disable parallelism for one test only.

Based on what I've looked up so far, this config exists globally via the config file or the command line only. Is it possible to set it on the code level for the given test or test suite? Something like test.use...

Thanks for your responses!

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/14084 Please upvote that issue instead.
