### ISSUE TITLE
Is Playwright API implementation the same for Java and JS/TS?

### ISSUE THREAD

**Issue by andresdfsl** [microsoft/playwright#17782]
Hello there,  I'm trying to determine what language to use to write the playwright automation for our teams.   First of all, I wanted to thank the developers for coming up with a better solution than Selenium and Cypress.  I much rather implement Playwright using Java as we want to use JUnit 5 as our test driver since it's integration with TestRail is much smoother, also since we want to use Rest Assured for our API tests and that works much better in Java too.   

My question is the one mentioned in the title:  **is Playwright API implementation the same for any language (when it comes to the low-level browser hooks?)**  I'm almost sure it's the same (why should it differ) but just wanted to be sure.

Thanks!

**Comment by yury-s** [comment]
The Java (as well as Python and .Net) APIs mostly match those of Node.js version. There are some slight differences when it comes to browser specific APIs, e.g. Chromium extension debugging or CDP session are not available in Java at the moment but the core API is available in all languages. One big difference is that Playwright for Node.js comes with it's own test runner that provides great parallelization mechanism, screenshot assertions, html reporter, automatic tracing etc. If you are cool with JUnit and existing integrations in your Java project then Playwright for Java should have all the same APIs as one would find in Node.js
