### ISSUE TITLE
[Question] Cannot find "only changed" option

### ISSUE THREAD

**Issue by y-nk** [microsoft/playwright#17799]
I'm looking to integrate Playwright into CI, and was wondering if it was a known use-case and how to solve it within Playwright. I've seen some issues relying on chokidar, but would you recommend this?

**Comment by yury-s** [comment]
There is a feature request for watch mode https://github.com/microsoft/playwright/issues/7035

Can you clarify how such option would apply to CI? Normally we assume that CI runs the entire test suite.

**Comment by y-nk** [comment]
For CI, the scenario would be jest's equivalent of `onlyChanged` rather than a watch mode. the goal is to reduce the duration of our playwright suite CI job which curreny takes 25mn at the moment.

`onlyChanged` works by listing the files which have changed since a given time, and execute only those tests

**Comment by jfgreffier** [comment]
Isn't it a duplicate of https://github.com/microsoft/playwright/issues/15075 ?

**Comment by y-nk** [comment]
@jfgreffier yes most likely. although #15075 seems stalled?

--

closing since duplicate, thanks for noticing 🙏

**Comment by jfgreffier** [comment]
Hey @y-nk I'm working on #15075

**Comment by y-nk** [comment]
thanks for the notice @jfgreffier well appreciated 🙏 if you need some help/support/feedback let me know.
