### ISSUE TITLE
[BUG] consistent crash after upgrading playwright to 1.26.1 

### ISSUE THREAD

**Issue by LanderBeeuwsaert** [microsoft/playwright#17808]
Hi @yury-s ,
I've been able to pinpoint where the crash as displayed in 
https://github.com/microsoft/playwright/issues/17755#issuecomment-1266044848
happens.

During our tests, we have a listener on the console log of the browser, so we can output that to text files and in the CI pipeline run
![image](https://user-images.githubusercontent.com/1098243/193828989-e4f13bb9-247c-46a2-a433-aa3c1dff52d1.png)
Somewhere in our code we have a console.log that logs out a crazy big object (it's a row node of the ag-grid library):
![image](https://user-images.githubusercontent.com/1098243/193829134-b5bb81cd-e0dd-43fb-b711-79f699fca92c.png)
(If I would open this up further it has thousands of nodes & subobjects, recursive ones as well)

When this line is logged out in the web application, it goes in the console listener function, and the messageLineHandle.jsonValue()
makes the browser crash.

So the crash doesn't happen until playwright 1.23.4, but from 1.24.0 it does.

**Comment by yury-s** [comment]
Can you create a minimum example where it happens, so that we can reproduce it? If that is just a large object that cannot be serialized, it should be easy create one without ag-grid.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
