### ISSUE TITLE
[BUG] The right caret character used to construct a full test title is unable to be rendered

### ISSUE THREAD

**Issue by jwells967** [microsoft/playwright#17806]
The formatTestTitle function is using the  ›  character rather than the standard keyboard character of  >  to split up the parts of the line 

 In our CI/CD test runner, this is rendered as â€º

![image](https://user-images.githubusercontent.com/55147745/193825787-21bacfa2-3213-4281-b956-09aa59e84104.png)

location of character:
https://github.com/microsoft/playwright/blob/e2b5fc4f88ca7a1ad6db91d2d658ee687cc658f0/packages/playwright-test/src/reporters/base.ts#L369

**Comment by yury-s** [comment]
Make sure the terminal on CI supports unicode symbols (the one that we use as the delimiter is https://www.compart.com/en/unicode/U+203A).

**Comment by jwells967** [comment]
this is occurring in Atlassian Bamboo on a windows build server

**Comment by yury-s** [comment]
Please make sure the terminal is properly configured to display unicode (maybe its font lacks  a glyph for › ). This is how it looks on one of the windows 11 machines with the stock cmd.exe:

![image](https://user-images.githubusercontent.com/9798949/194672496-8cb34170-66a7-46dc-8a39-efac41a28e5e.png)
