### ISSUE TITLE
[Feature] Stress testing framework with playwright scripts

### ISSUE THREAD

**Issue by pratik-fluxon** [microsoft/playwright#17803]
Providing a framework by which user can load test their end to end application would be a good use case for playwright. There are many tools for load testing some of the prominent one are Jmeter and K6. But for very exhaustive and lengthy flow, it becomes difficult to maintain their scripts so if there is a feature with playwright providing the functionality of stress testing and then distributed testing as an extension would be of great use.

**Comment by yury-s** [comment]
Do you have an idea of what APIs Playwright currently lacks that would be necessary for the stress testing?

**Comment by jfp1992** [comment]
Probably won't work with playwright as the memory usage climbs while the context is open. Every page navigated to adds to memory for the python and node processes.

The memory issue es apparently expected behaviour
https://github.com/microsoft/playwright/issues/17736

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
