### ISSUE TITLE
[Feature] approve Screenshot button for playwright test report

### ISSUE THREAD

**Issue by frank-swp** [microsoft/playwright#17801]
Is it possible to integrate an `approve Screenshot` button into the Playwright Test Report?
Clicking this button would copy the actual screenshot to the location of the expected (the same as `npx playwright test -u` does, but for a single screenshot).

This would allow to approve screenshot by screenshot, which is useful when there are a lot of changes because of an update of the dependencies. Remaining changes which are caused by bugs can be fixed later.

Using `npx playwright test -u` has problems, because you can not be sure that the new generated screenshots have no flaky effects.

**Comment by frank-swp** [comment]
I found some similar issues:
https://github.com/microsoft/playwright/issues/14883
https://github.com/microsoft/playwright/issues/16970

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/14883, please upvote that issue instead.

**Comment by mscottford** [comment]
While working on a project that has a lot of screenshot tests, I was getting rather frustrated with having to "approve" small differences. So I created a [Tampermonkey script](https://gist.github.com/mscottford/86dcda220a61c1107da128ba0824f61a) to help. It adds a button that can be clicked on to copy a `mv` command to the clipboard. Then you just paste that in the terminal and run it to approve the file.
