### ISSUE TITLE
[Feature] Add option to BrowserContext.storageState() for storing Session Storage

### ISSUE THREAD

**Issue by svdHero** [microsoft/playwright#17812]
The [Playwright documentation](https://playwright.dev/docs/auth#session-storage) states
> Rarely, [session storage](https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage) is used for storing information associated with the logged-in state. Session storage is specific to a particular domain and is not persisted across page loads.

However, [MSAL](https://github.com/AzureAD/microsoft-authentication-library-for-js) uses session storage for storing login information. That means that for any front-end SPA that authenticates against Azure AD or Azure B2C, login state cannot be reused as described [here](https://playwright.dev/docs/test-auth#multiple-signed-in-roles). It gets especially messy when trying to test multiple signed-in roles. For more details compare #17328 and https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/5221.

This is a major draw-back when using Playwright for testing web applications in the Microsoft Azure ecosystem.

It would make life so much easier, if there was an easy way to save the session storage. I propose to add a boolean option `includeSessionStorage` to the method [BrowserContext.storageState()](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state). When said option is set to `true`, the session storage would be saved alongside the local storage in the JSON file's `origins` array.

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/8874 Please upvote that issue to help us prioritize.
