### ISSUE TITLE
[REGRESSION]:  Webkit reports duplicate resource timings entries

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#17811]
**Context:**
- GOOD Playwright Version: 1.25
- BAD Playwright Version: 1.26
- Operating System: Windows, Linux
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
test.only("provides correct resource timings", async ({ page }) => {
        const html = `
            <!DOCTYPE html>
            <html>
                <head>
                    <title>Test page</title>
                    <script src="/script.js"></script>
                </head>
                <body>
                    <img src="/img/image.jpg" alt="text">
                </body>
            </html>
        `;

        await page.route(/something.php/, function (route) {
            return route.fulfill({
                headers: {},
                body: html,
                contentType: "text/html"
            });
        });
        await page.goto("https://something.php");
        await page.pause();
        const resTimings = await page.evaluate(() => performance.getEntries());
        const images = resTimings.filter(res => res.name.includes("image.jpg"));
        expect(images.length).toBe(1);
    });
```

**Describe the bug**

After update to 1.26 from 1.25 webkit started reporting duplicate resource timings.
It happens if script is requested in the head, along with images in the body. 
I haven't tried other scenarios.
Might be an upstream webkit bug.
I have provided a simple test case.
Chrome and firefox pass this test, and webkit passed it on playwright version < 1.26.

This is how entries look on webkit with playwright 1.26.1
```typescript
 [{"connectEnd": 43, "connectStart": 43, "domainLookupEnd": 43, "domainLookupStart": 43, "duration": 16.000000000000007, "entryType": "resource", "fetchStart": 43, "initiatorType": "img", "name": "https://test.local/img/image.jpg", "nextHopProtoco
l": "", "redirectEnd": 0, "redirectStart": 0, "requestStart": 43, "responseEnd": 59.00000000000001, "responseStart": 43, "secureConnectionStart": 0, "serverTiming": [], "startTime": 43, "workerStart": 0}, {"connectEnd": 93, "connectStart": 93, "domainLookupEnd
": 93, "domainLookupStart": 93, "duration": 25.000000000000014, "entryType": "resource", "fetchStart": 93, "initiatorType": "img", "name": "https://test.local/img/image.jpg", "nextHopProtocol": "", "redirectEnd": 0, "redirectStart": 0, "requestStart": 93, "responseEnd": 118.00000000000001, "responseStart": 93, "secureConnectionStart": 0, "serverTiming": [], "startTime": 93, "workerStart": 0}]
```
Entries with playwright 1.25.1
```typescript
[{"connectEnd": 36.00000000000001, "connectStart": 36.00000000000001, "domainLookupEnd": 36.00000000000001, "domainLookupStart": 36.00000000000001, "duration": 11.999999999999993, "entryType": "resource", "fetchStart": 36.00000000000001, "initiat
orType": "img", "name": "https://something.php/img/image.jpg", "nextHopProtocol": "", "redirectEnd": 0, "redirectStart": 0, "requestStart": 36.00000000000001, "responseEnd": 48, "responseStart": 36.00000000000001, "secureConnectionStart": 0, "serverTiming": [], "startTime": 36.00000000000001, "workerStart": 0}]
```

**Comment by yury-s** [comment]
Is it reproducible without network interception?

**Comment by yury-s** [comment]
Ok, the underlying problem is that the request is intercepted second time after it was fulfilled. I can confirm that it didn't happen in 1.25 and happens with the newer webkit from 1.26

**Comment by yury-s** [comment]
This is a regression introduced by https://github.com/microsoft/playwright-browsers/pull/12

**Comment by yury-s** [comment]
Well, the new behavior is actually correct. The browser sends two requests for the image - one `preload` and the other is normal load request. Playwright intercepts both and the timing information is also available for both requests/

**Comment by Smrtnyk** [comment]
When intercepting preload request, is it possible to know that  it is a preload?
just so we can let these through then

**Comment by Smrtnyk** [comment]
this still doesn't make sense to me
I have created this simple html page
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="/main.js" ></script>
</head>
<body>
    <img src="https://via.placeholder.com/150" alt="" />
</body>
</html>
```

and I created an empty script.js

if I visit this page using webkit ( and I am using @playwright/test package btw) I get duplicate image entry in resource timings, but if I remove the script from html, then I get only 1 image entry in resource timings.
Why would script.js have any influence on image showing twice in resource timings?

**Comment by Smrtnyk** [comment]
actually even if we would know that it is a preload request it wouldn't help us.
But this still doesn't make sense to me.
I have created this page.

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="/main.js" ></script>
</head>
<body>
    <img src="https://via.placeholder.com/150" alt="" />
</body>
</html>
```

I served it using vscode live server

and I have this test
```typescript
 test.only("google", async ({ page }) => {
        await page.route(/google/, () => {
            throw new Error("should never come here!");
        });
        await page.goto("http://127.0.0.1:5500/index.html");
        console.log(await page.evaluate(() => {
            return performance.getEntriesByType("resource");
        }));
    });
```
which I run using @playwiright/test package.
Basically what happens that it yields duplicate entries for image in performance.getEntries().

case 1: no route handler for /google/ and main.js on page -> no duplicate entries in resource timings for image
case 2: route handler for /google/ registered, no main.js in html -> no duplicate entries in resource timings
case 2: no route handler for /google/ registered, no main.js in html -> no duplicate entries in resource timings
case 3: route handler for /google./ registered, main.js in html -> duplicate entries in resource timings for image

there is not a single resource on the page that loads something from google, and main.js is completely empty so there is nothing that would trigger duplicate load.
From the test case above there is not even anything intercepted, because only route handler registered throws an error so it never comes to that line at all.

I have tests where I need to have the route handlers, and I have scripts on the page, I can't change that, and those work well on firefox and chrome and worked well on previous webkit versions.

You said it is a preload request, I tried adding preload="none" to image tags and it still doesn't help.
I am just trying to understand how to fix this, because it is breaking lots of our tests now.

**Comment by Smrtnyk** [comment]
@pavelfeldman sorry for the ping, but, do you have some thoughts about this? 
In my last comment I have provided a minimal repro.
This is blocking us to update playwright as it breaks many tests on webkit (chrome and ff work properly).
It's just that we don't know why this inconsistency in behavior for webkit.
