### ISSUE TITLE
[Question] Why page.goto(url) fails to load the page completely to move to next statement, hence fails the TCs with timeout?

### ISSUE THREAD

**Issue by AshisRaj** [microsoft/playwright#17815]
Hi, we have been seeing such navigation timeout issue with page.goto('url') calls randomly with random TCs. We have 205 UI TCs currently running in one go against a CD environment. 

We need to know if there is anything we can do to fix this random failures apart from increasing the navigationTimeout?

Please note we are running the tests from our local laptop. It is just that the application is deployed on the CD environment.
Below the details.

**Command we use to run tests**
_________________________________
npx cross-env ENV=stg02  playwright test ./tests/functional/core --workers=10

**Local Laptop configs**
_________________________________
RAM - 32 GB
CPU Core - 4
Logical Processes - 8

**Playwright version - 1.25.0**
_________________________________

**Playwright.config.ts**
_________________________________
fullyParallel: false,
retries: process.env.CI ? 2 : 1,
workers: process.env.CI ? 1 : undefined,
navigationTimeout: 60 *1000,
headless: true,
viewport: { width: 1280, height: 720 },

Thanks,,
Ashis Raj

**Comment by imartinflores** [comment]
@AshisRaj is it something to do with this error ? Im having a timeout issue as well and not sure why is it
[https://github.com/microsoft/playwright/issues/17670](https://github.com/microsoft/playwright/issues/17670)

**Comment by yury-s** [comment]
Probably there is a race condition in your tests or they somehow interfere with each otehr or the response from the server sometimes takes longer. The configuration looks ok for that hardware, you can also let playwright pick number of workers automatically. To make this report actionable on our end we need a reproducible example. Please file a new issue with a repro and link to this one.
