### ISSUE TITLE
[Question] How can I use my custom build chromium to run it with playwright

### ISSUE THREAD

**Issue by bobHealy** [microsoft/playwright#17819]
I want to run my own custom build chromium with playwright. To make this work I have the following questions:

1. Where can I see the tweaks i need to do to make chromium work with playwright? (gitdiff etc.?)
2. In the docs there is something written about browser channels. Would I use this to use my custom build chromium?
3. Is there a known How-To Custom Chromium Build with playwright? (maybe I was just a bad googler)

**Comment by yury-s** [comment]
> I want to run my own custom build chromium with playwright. To make this work I have the following questions:
> 
> 1. Where can I see the tweaks i need to do to make chromium work with playwright? (gitdiff etc.?)

There is no diff, Playwright works with the stock Chromium build (and Chromium based browsers too).

> 2. In the docs there is something written about browser channels. Would I use this to use my custom build chromium?

No, you don't need that, it's only for the vendor builds (Google Chrome, MS Edge etc). You can point Playwright to your custom build by adding [`executablePath`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-executable-path) option.

> 3. Is there a known How-To Custom Chromium Build with playwright? (maybe I was just a bad googler)

There is no how-to, just adding `executablePath` option should work.
