### ISSUE TITLE
[Question] Multiple Elements For A Single Selector

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#17810]
Is there a way to have a selector use two separate elements? Here is an example:

A site has a button that shows up in two areas. In the first it is in an iframe, in the second it isn't. Let's say the ID for this button is button_1 and the iframe ID is iframe_1.

Instead of having:
```
readonly button: Locator;
readonly buttonInIframe: Locator;

button = page.locator('id=button_1);
buttonInIframe = page.frameLocator('iframe_1').locator('id=button_1);

async clickButton() {
    await this.button.click();
  }

async clickButtonInIframe() {
    await this.buttonInIframe.click();
  }
```

Is there a way to do something like this?:
```
readonly button: Locator;

button = page.locator('id=button_1) or page.frameLocator('iframe_1').locator('id=button_1);

async clickButton() {
    await this.button.click();
  }
```

**Comment by yury-s** [comment]
If the elements are inside the same iframe and only one is visible at any time you can use [selector list](https://playwright.dev/docs/selectors#css-selector-list) to pick the one. But if they are in different iframe you'll have to manually check the condition and pick one of the two, there is not builtin support for that.
