### ISSUE TITLE
[BUG] Specific site does not load on Webkit (headless) in docker container

### ISSUE THREAD

**Issue by ps-jalvarado** [microsoft/playwright#17822]
**Context:**
- Playwright Version: 1.26.1
- Operating System: Mac OS (M1)
- Node.js version: 16.17.1
- Browser: Webkit (Headless)
- Extra: Using Docker Container

**Code Snippet**

* Here is my repo that can reproduce the issue I am having. Extra info can be found in there
* https://github.com/ps-jalvarado/Playwright-Testing

**Describe the bug**

I would want to run webkit headless and go to a home depot product. However, when running playwright in a docker container it can never comeplete the `page.goto` step. On the other hand, when using it locally non-containerized it works without any issues. When using the container I can get messages involving `"Target Closed"` or `"Timout because 120000ms has exceeded"`

**Comment by yury-s** [comment]
Apparently some bot detection kicks-in on the homedepot side and makes the goto request hang if it has suspicious user agent. The test passed for me once on linux and all subsequent attempts time out if custom user agent is used. Playwright does not support stealth mode out of the box. So this is working as intended.
