### ISSUE TITLE
[Question] When you start Electron, you get an error that the version of Node.js is not supported

### ISSUE THREAD

**Issue by kurohoan** [microsoft/playwright#17828]
When you start Electron, you get an error that the version of Node.js is not supported.

The operating system is Windows. When I update Node.js and do node -v, it shows v16.17.1. When I start it with npm run electron:serve, the following error appears again. What could be the cause? The following modules are used to start Electron. "vue-cli-plugin-electron-builder".

`
You are running Node.js 12.14.1.
Playwright requires Node.js 14 or higher.
Please update your version of Node.js.
`

This question has also been posted on stackoverflow.

https://stackoverflow.com/questions/73944223/when-you-start-electron-you-get-an-error-that-the-version-of-node-js-is-not-sup

**Comment by yury-s** [comment]
What electron version are you using? Can you share the project where the error occurs?

**Comment by kurohoan** [comment]
Electron
"version": "9.4.4",


The project is not immediately available for sharing due to the huge private repository.
The project consists of Vue2 in vue-cli-plugin-electron-builder, what might be the connection?

**Comment by yury-s** [comment]
> Electron
> "version": "9.4.4",

We don't support such old version anymore, from https://playwright.dev/docs/api/class-electron :

<img width="277" alt="image" src="https://user-images.githubusercontent.com/9798949/194135152-30dd35c0-aca8-4674-ab7f-17484486e62a.png">

**Comment by kurohoan** [comment]
thank you.
