### ISSUE TITLE
[Question]How to apply timeouts for global setup file for resuable signed in state

### ISSUE THREAD

**Issue by alapanme** [microsoft/playwright#17823]
So I am automating a scenario where I am using the session storage across multiple tests and for that, I have written a simple script like this. This is copied from the playwright docs, but the script is of similar nature.

```
// global-setup.ts
import { chromium, FullConfig } from '@playwright/test';

async function globalSetup(config: FullConfig) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto('https://github.com/login');
  await page.locator('input[name="login"]').fill('user');
  await page.locator('input[name="password"]').fill('password');
  await page.locator('text=Sign in').click();
  // Save signed-in state to 'storageState.json'.
  await page.context().storageState({ path: 'storageState.json' });
  await browser.close();
}

export default globalSetup;
```
The problem here is that the webpage elements of the login page are being loaded very slowly and the commands are unfortunately not following the timeouts defined in the playwright config file. Any suggestions on what can I do so that the elements follow the timeouts from the playwright config file? It is working as expected when I am using the `Page.waitForTimeout()` method.

**Comment by yury-s** [comment]
Currently timeout settings from the config do not apply to global setup/teardown. This should be address by 
 as part of https://github.com/microsoft/playwright/issues/17550, so I'm going to fold this issue into that. For the time being you can manually change default timeouts in the global setup via [setDefaultTimeout](https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-timeout), [setDefaultNavigationTimeout](https://playwright.dev/docs/api/class-browsercontext#browser-context-set-default-navigation-timeout) or passing custom timeout as [option](https://playwright.dev/docs/api/class-locator#locator-fill-option-timeout) to individual commands.

**Comment by alapanme** [comment]
Unfortunately none of the timeouts are working. When the element is not found it just skips and an invalid session storage is saved.

**Comment by yury-s** [comment]
> Unfortunately none of the timeouts are working.

What do you mean by that? Do the click()/fill() actions not throw on timeout?

**Comment by alapanme** [comment]
I tried using both time outs alternatively as well as together:
```
const browser = await chromium.launch()
const context = await browser.newContext()
const page = await context.newPage()
page.setDefaultNavigationTimeout(30000)
page.setDefaultTimeout(30000)
```

The test basically skips while running `await page.goto(config.projects[0].use.baseURL)` and an invalid session storage is added.

**Comment by yury-s** [comment]
> But the same scenario works when I do:

This means that the session storage is populated asynchronously after navigation completes, you can read more about different navigation stages [here](https://playwright.dev/docs/navigations#navigation-lifecycle). In your case page keeps  doing some work asynchronously after 'load' event has fired and the session storage is also populated after the 'load' event. You need to find a signal in the login page that would indicate that the session storage is already populated, the most naive approach could be via [expect.poll](https://playwright.dev/docs/test-assertions#polling):

```js
  await expect.poll(() => {
    return page.evaluate(() => window.sessionStorage.getItem('expectedKeyName'));
  }).toBeTruthy();
```

or just wait until the storage is not empty:
```js
  await expect.poll(() => {
    return page.evaluate(() => window.sessionStorage.length);
  }).toBeTruthy();

```
