### ISSUE TITLE
[Question] how to remove exposed functions?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#17836]
Is it possible to undo the result of [page.exposeFunction](https://playwright.dev/docs/api/class-page#page-expose-function)? I tried this:

```js
const x = await this.page.evaluate(() => {
  delete window.foobar
  return typeof window.foobar
}) // 'undefined'
```

but still have an error when call page.exposeFunction second time:

```
page.exposeFunction: Function "foobar" has been already registered
```

context: we want to run multiple tests in just one browser page, and we want to clear as much as possible after every test.

**Comment by Diokuz** [comment]
I found this method https://github.com/microsoft/playwright/blob/df143031e7eac11460bcd658dc3bb5a8951ccd64/packages/playwright-core/src/server/browserContext.ts#L188 but it does not exist on browser.newContext() and probably private.

**Comment by yury-s** [comment]
There is no API for removing exposed bindings/functions (the function you refer to does only part of the job), we recommend creating a new context for each test which will start with a clean environment.
