### ISSUE TITLE
[Question]Why is there a long gap in front of my recorded video?

### ISSUE THREAD

**Issue by oushiki1219** [microsoft/playwright#17834]
![image](https://user-images.githubusercontent.com/115062756/193991769-1416f3ad-89d1-4cdc-bc6c-04ec62156a11.png)
A total of eight seconds of video in the first seven seconds are blank, please ask why?

**Comment by oushiki1219** [comment]
I think I have found the cause, sorry, please close this issue

**Comment by HeDo88TH** [comment]
> I think I have found the cause, sorry, please close this issue

What was the cause?

**Comment by codingedgar** [comment]
> I think I have found the cause, sorry, please close this issue

what was the issue? I also have that dead time.
