### ISSUE TITLE
[Question] Angular: Wait for component event

### ISSUE THREAD

**Issue by GregBe** [microsoft/playwright#17835]
Hey, 

currently I'm testing playwright in Angular with a third-party viewer component. Since it is not a component I wrote, O don't care if all the UI is properly build, but what I do care about is that the viewer will show the document. So I'm doing a screeshot test. The first screenshot shows the loaded document how it should be, all fine so far. But every follow up screenshot doesn't show the document loaded correctly, so the testcase will fail.

Is there a way to wait for an event emitted by the component, or by my wrapping component ( like viewerLoaded-Event). Since it isn't a dom/window event i couldnt find a way to wait for such an event.

My current testcase looks like this:

```
test('Load document into viewer', async ({ page }) => {
  // waits for inital component loading and loads file into viewer
  const [fileChooser] = await Promise.all([
    page.waitForEvent('filechooser'),
    page.locator('label:has-text("Select file")').click(),
  ]);
  await fileChooser.setFiles('tests/test.pdf');

  //should wait till file is loaded into viewer
  const selector = 'app-root';
  await page.waitForFunction(async selector => {
    const app = (document.querySelector(selector) as unknown as any)
    return await app.viewerLoaded;
  }, selector)
 
 // after file is loaded take a screenshot
 await expect(page).toHaveScreenshot('loadeddocViewer.png');
});
```

**Comment by yury-s** [comment]
There is no generic mechanism for that, [waitForFunction](https://playwright.dev/docs/api/class-page#page-wait-for-function) seems to work well for you. Another option would be [expect.poll](https://playwright.dev/docs/test-assertions#polling).
