### ISSUE TITLE
[BUG] (📚) Strict text selector trims, this should be documented

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#17831]
**Context:**
- Playwright Version: [what Playwright version do you use?]  Playwright-python 1.25.2
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Node.js version: [e.g. 12.22, 14.6] Python 1.10.7
- Browser: [e.g. All, Chromium, Firefox, WebKit] All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as pw:
    page = pw.chromium.launch().new_page()
    page.set_content("<div>a </div>")
    print(page.query_selector("text='a'"))  # JSHandle@node
```

**Describe the bug**

Docs be like:
> default matching is case-insensitive and searches for a substring.

> text body can be escaped with single or double quotes to search for a text node with exact content.

Yet in practice playwright is still trimming the text. I'm not disagreeing with this behavior, but it definitely should be mentioned in the docs.

> NOTE
Matching always normalizes whitespace. For example, it turns multiple spaces into one, turns line breaks into spaces and ignores leading and trailing whitespace.

The docs do actually mention this later on, but I think it would be valuable to reiterate it in the strict match section.

**Comment by debs-obrien** [comment]
should be added to revised selectors doc which is work in progress by @dgozman
