### ISSUE TITLE
[Feature] Record WebSocket frames in HAR

### ISSUE THREAD

**Issue by baltiyskiy** [microsoft/playwright#17838]
As suggested in https://github.com/microsoft/playwright/issues/6254, creating an issue to support recording sent and received WebSocket frames in the HAR.

**Comment by mxschmitt** [comment]
Sounds like a duplicate of https://github.com/microsoft/playwright/issues/17848.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/17848, please upvote that issue instead.
