### ISSUE TITLE
[Question] Is it possible to remove header on browser request after adding custom header with extraHTTPHeaders?

### ISSUE THREAD

**Issue by 4nif** [microsoft/playwright#17830]
Is it possible to remove header on browser request after adding custom header with extraHTTPHeaders?

**illustration**
homepage (open with additional headers) --> click registration button --> open registration button without additional header (remove custom header) --> continue with all step without additional headers

**Comment by yury-s** [comment]
You can add [`page.route`](https://playwright.dev/docs/api/class-page#page-route) handler and use [`route.continue`](https://playwright.dev/docs/api/class-route#route-continue) for fine grained control over which headers are sent to the server with which request. You can remove the extra headers like this:

```js
  const context = await browser.newContext({extraHTTPHeaders: {
    'foo': 'bar'
  }})
  const page = await context.newPage();
  await page.route('**/*', (route, request) => {
    // Override headers
    const headers = {
      ...request.headers(),
      foo: undefined, // remove "bar" header
    };
    route.continue({headers});
  });
```
