### ISSUE TITLE
[BUG] launchOptions.args and vieport:null have no effect

### ISSUE THREAD

**Issue by shwarcu** [microsoft/playwright#17837]
**Context:**
- Playwright Version: 1.26.1
- Browser:  Chromium, Firefox
## System:
 - OS: macOS 12.6
 - Memory: 9.70 GB / 32.00 GB
## Binaries:
 - Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
 - Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.0/bin/yarn
 - npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 - TypeScript 4.8.4

**Code Snippet**

Part of the config I am working with

```typescript
const config: PlaywrightTestConfig = {
// not related config here
  use: {
    viewport: null,
    launchOptions: {
      args: ['--start-maximized'],
    },
    headless: !!process.env.CI,
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
// not related config here
};

export default config;

```

Repository with reproduction is here https://github.com/shwarcu/playwright-reportportal-example

**Describe the bug**

As far as I remember, previously, setting `viewport: null` in config made browser window to always maximise when launched.
This is not working anymore.
In addition to that, I was trying to use browser args but it seems that this configuration option is also not working. I tried `--start-maximized` and `--start-fullscreen` and it has no effect too. So it looks like passing args to browser is not working.

https://user-images.githubusercontent.com/58426925/194022335-87a4768f-65f9-450f-be24-1e19fcb52a21.mov

Repro steps:
1. Comment out `viewport` or `launchOptions`
2. Run example test

**Comment by yury-s** [comment]
The option only works if you launch playwright manually and it only applies to the default page created by the browser. 
```js
    const browser = await chromium.launch({
      args: ['--start-fullscreen'], // on mac or args: ['--start-maximized'] on other platforms
      ignoreDefaultArgs: ['--no-startup-window'],
      headless: false});
    const context = await browser.newContext({
        viewport: null
    });
    const page = await context.newPage();
```
Playwright test starts the browser without the default page (--no-startup-window). Configuring `viewport: null` lets the browser decide which window size to use, but since '--start-maximized' applies only to the default window it will not affect subsequent pages created by playwright. 

Folding this issue into https://github.com/microsoft/playwright/issues/4046
