### ISSUE TITLE
[BUG] browserContext.clearCookies() doesnot clear microsoft access tokens

### ISSUE THREAD

**Issue by akshat55narang** [microsoft/playwright#17843]
**Context:**
- Playwright Version: v1.26.0
- Operating System: Windows
- Node.js version: v14.17.0
- Browser: Chromium

**Describe the bug**
Application Overview
We have an Single Page App that uses Microsoft Auth code flow https://learn.microsoft.com/en-us/azure/active-directory/develop/v2-app-types#single-page-apps-javascript. So, when I open the application http://localhost:8080/ , I am redirected to https://login.microsoftonline.com/{tenant-id}/oauth2/v2.0/authorize where I need to fill the credentials. After filling the credentials I am redirected to the app http://localhost:8080/. 
When I reopen the browser the token is preserved in browser and I don't need to enter credentials again. Only if I open the app in Incognito mode, I am required to fill in the credentials again.

When I run the test via playwright in Chromium , the app (http://localhost:8080) redirects to https://login.microsoftonline.com and instead of prompting for credentials , it just picks up the existing session. 

**Code Snippet**
I am new to playwright and I tried the below approaches to clearCookies.

```javascript
test('test1', async ({ page }) => {
    await page.context().clearCookies();
    await page.goto('http://localhost:8080');

    await page.waitForNavigation({
            timeout: 5,
            url: 'https://login.microsoftonline.com/',
            waitUntil: 'domcontentloaded'
        });
   await expect(page.url()).toContain('https://login.microsoftonline.com/');
   await page.locator('input[type="email").fill('test.user@test.com');   // Fails as user is already signed in
});

test('test 2', async ({ browser }) => {
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://localhost:8080');
});
```

**Comment by yury-s** [comment]
> When I run the test via playwright in Chromium , the app (http://localhost:8080) redirects to https://login.microsoftonline.com and instead of prompting for credentials , it just picks up the existing session.

Each tests starts with a new incognito context which has no data. Unless you have some setup in beforeAll or something there should be no cookies in the context, you can check that by printing result of (`await page.context().cookies()`). Does your project saves storage state in a global setup as described [here](https://playwright.dev/docs/test-auth#reuse-signed-in-state) ? Can you share playwright.config.ts that is used and the test file where it fails?

**Comment by akshat55narang** [comment]
I ran `await page.context().cookies()` and it returned no cookies. In the browser Application tab, I looked at the Local Storage ( which was empty ). However, the Session Storage contained all the cookies. It is quite weird, If I open the chrome on my laptop in Incognito mode, all the cookies / Session Storage is empty and I am prompted to enter the credentials.  Only when the browser is instantiated via Playwright ( In Incognito Mode ) , the cookies are somehow being already picked up.

[playwright.config.txt](https://github.com/microsoft/playwright/files/9725651/playwright.config.txt)
[BasePage.txt](https://github.com/microsoft/playwright/files/9725706/BasePage.txt) - Failure on this step as it is waiting for login screen from https://login.microsoft.com, but since the credentials are already present in Session Storage, user is already signed in. 
[test.spec.txt](https://github.com/microsoft/playwright/files/9725709/test.spec.txt) // Contains the test which fails

**Comment by yury-s** [comment]
> Only when the browser is instantiated via Playwright ( In Incognito Mode ) , the cookies are somehow being already picked up.

This is odd, there is no place where it could pick up the session storage as it is destroyed after browser exits. We need a full reproducible example (with project and the test file) that we can run locally to act on this. Can you share one?

**Comment by akshat55narang** [comment]
Hi Yury, 
Unfortunately, we cannot share the project as it is not allowed. When I ran the tests inside a docker container, this issue does not occur.  I am using this as a work around. Perhaps its just something within my laptop. 

Thanks again!

**Comment by udaypatel1** [comment]
Had the same issue, seems to work on our CI build container but not locally as it's not prompting our `Accept All Cookies` modal which is causing an error when trying to click past it in our codebase logic, assuming it should be there.

However, it was working locally when I ran the tests using `Playwright Version: 1.28.1` and broke when I upgraded to `Playwright Version: 1.45.2`

Just something to note @yury-s 

I also am not able to share the codebase but am able to give other details if necessary.

Thanks!

**Comment by gladykov** [comment]
For a moment I also thought `clearCookies` does not always clear cookies, but then I got it:

1. Once page is loaded, in the background there are still API requests / JS is executed .
2. If we call `clearCookies()`, and during / after this operation one of API requests / JS functions will finish, it will set the cookie again. 

And this is now we still have cookie after clearing cookies.

Our workaround: load page -> sleep(5) -> `clearCookies`
