### ISSUE TITLE
[Question] Component Tests perform a different bundling? Failed to resolve asset import

### ISSUE THREAD

**Issue by Nithos** [microsoft/playwright#17846]
I have a simple component for a header which just includes a logo and button.
But running the component test fails as the vite bundler gets invoked and complains due to the reference to the image.
Does it not resolve aliases properly?
When using a relative path it works.

Fails
`

	<nav>
		<img src="@assets/images/logo.png" height="32" width="128" alt="logo" />
		{{ auth.name }}
		<Button v-if="isAuthenticated" @click="logout">Logout <Logout /></Button>
		<Button v-else @click="login">Login <Login /></Button>
	</nav>
`
ERROR:
[vite]: Rollup failed to resolve import "@assets/images/logo.png" from "src/components/Header.vue?vue&type=script&setup=true&lang.ts".

Works with a relative path
`

	<nav>
		<img src="../assets/images/logo.png" height="32" width="128" alt="logo" />
		{{ auth.name }}
		<Button v-if="isAuthenticated" @click="logout">Logout <Logout /></Button>
		<Button v-else @click="login">Login <Login /></Button>
	</nav>
`

**Comment by sand4rt** [comment]
Hi @Nithos, you have to specify your import alias in `playwright-ct-config.ts` as well:

```typescript
import { resolve } from 'path';
const config: PlaywrightTestConfig = {
  use: {
    trace: 'on-first-retry',
    ctPort: 3100,
    ctViteConfig: {
      resolve: {
        alias: {
          '@': resolve(__dirname, './src'),
        },
      },
    },
  },
};
```

Playwright doesn't reuse the Vite config yet: https://github.com/microsoft/playwright/issues/14749.

**Comment by Nithos** [comment]
Thank you @sand4rt that was an omission on my part. When I first configured it I added our main alias but forgot about the additional ones :(. That solves my issue.
