### ISSUE TITLE
[Question] Is it possible to simulate a mouse-right click?

### ISSUE THREAD

**Issue by dandara-navarro** [microsoft/playwright#17851]
Hi, I'd like to know if I can simulate a mouse right-click on Playwright. My application is a React app and I have a DIV with the event `onContextMenu` and I'd like to make sure this is working. Thank you in advance.

**Comment by Andyspickle** [comment]
I believe there is information here. https://playwright.dev/docs/api/class-locator#locator-click
`page.locator("(div locator)").click({button: "right"})`

**Comment by yury-s** [comment]
Closing per above comment.
