### ISSUE TITLE
[Question] How to compile/transform files with custom file extensions

### ISSUE THREAD

**Issue by dvargas92495** [microsoft/playwright#17852]
I am using playwright to test a [Nearley](https://nearley.js.org) grammar. These grammars are specified as `.ne` files. My current setup involves compiling that file (during global test setup) and then importing it as a typescript file.

This works, however I was wondering if there was a way to define custom transforms or esbuild plugins so that it would be handled by playwright's transformation and no files would be generated on my file system. This would allow me to simply do:

```typescript
import grammar from "path/to/grammar.ne";

// test the grammar
```

I know `jest` had a notion of transforms based on a regex in its config. From what I could tell, playwright is using some combination of esbuild or vite under the hood, I would love to be able to pass that underlying compiler a plugin so that I could transform this custom file extension seamlessly.

**Comment by yury-s** [comment]
Playwright does not support pluggable transformations. Closing this issue as have no plans on adding such extension mechanism  and there is a workaround for the described problem.

**Comment by dvargas92495** [comment]
would the team be open to me proposing a PR for adding this mechanism?
