### ISSUE TITLE
Integration with Cucumber

### ISSUE THREAD

**Issue by pbarros5** [microsoft/playwright#17873]
Integration with Cucumber is very important for us in Agile and using BDD.

**Comment by jfgreffier** [comment]
Depending on the language you use and the test runner, you'll have different options.

For JavaScript/Typescript, you have cucumber-playwright.  
https://medium.com/@manabie/how-to-use-playwright-in-cucumberjs-f8ee5b89bccc  
https://github.com/Tallyb/cucumber-playwright  

Also, you can seek help on Slack https://aka.ms/playwright-slack

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/11975
