### ISSUE TITLE
[BUG] page.screenshot fails: "ReferenceError: __name is not defined"

### ISSUE THREAD

**Issue by Uninen** [microsoft/playwright#17872]
**Context:**
- Playwright Version: 1.26.1
- Operating System: macOS 12.6
- Node.js version: 16.15.1
- Browser: Chromium
- Extra: 

```
"@playwright/test": "1.26.1",
"playwright-chromium": "1.26.1",
"tsx": "3.9.0",
"typescript": "4.8.4",
```

```
## System:
 - OS: macOS 12.6
 - Memory: 96.53 MB / 16.00 GB
## Binaries:
 - Node: 16.15.1 - ~/.nvm/versions/node/v16.15.1/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.15.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright-chromium: 1.26.1 => 1.26.1 
```

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
// test.ts
import { chromium } from 'playwright-chromium'
;(async () => {
  const url = 'https://www.unessa.net'

  const browser = await chromium.launch({
    headless: true,
  })
  const context = await browser.newContext()
  const page = await context.newPage()

  await page.goto(url)
  await page.screenshot({
    path: 'test-screenshot.png',
    fullPage: true,
  })
})()

```

**Describe the bug**

If I run `pnpm tsx test.ts` I get the following error:

```
page.screenshot: ReferenceError: __name is not defined
    at eval (eval at evaluate (:190:30), <anonymous>:1:102)
    at UtilityScript.evaluate (<anonymous>:192:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
=========================== logs ===========================
taking page screenshot
============================================================
    at null.<anonymous> (/Users/uninen/Code/Libraries/garminconnect/src/testfn.ts:12:14)
```

This has been working fine previously, at least w/ Playwright 1.22.2 (live here: https://github.com/Uninen/garmin-connect-to-json/blob/main/src/functions.ts)

**Comment by Uninen** [comment]
Sorry for the noise, this has nothing to do with Playwright, it's a tsx/ts/node issue. (After some tweaking got it working w/ ts-node but the tsx still doesn't work.)

**Comment by arpadgabor** [comment]
Hi @Uninen , I'm facing the same issue, how did you setup ts-node for it to work properly?

**Comment by 445817848** [comment]
> 

This is tsx bug, you need to compile ts with tsc then run the .js
