### ISSUE TITLE
[BUG] Firefox newPage crashes in Docker when it is setting seccomp+tsync

### ISSUE THREAD

**Issue by wxiaoguang** [microsoft/playwright#17876]
**Context:**
- Playwright Version: 1.24.x-1.26.1
- Operating System: Linux Docker
- Node.js version: N/A
- Browser: Firefox
- Extra: Docker

**Code Snippet**

The simplest test:

```
test('Load Homepage', async ({page}) => {
  const response = await page.goto('/user/login');
  await expect(response?.status()).toBe(200);
});

```

**Describe the bug**

playwright shows that:

```
  pw:protocol SEND ► {"id":12,"method":"Browser.newPage","params":{"browserContextId":"8f9c770c-ec69-43aa-b305-3d2b0a0a3901"}} +6ms
  pw:channel:response { id: 3 } +4ms
  pw:channel:response { id: 4 } +0ms

==== HERE ====
  pw:browser [pid=25206][err] Sandbox: thread-synchronized seccomp failed: Unknown error 524 +168ms
  pw:browser [pid=25206][err] Sandbox: thread-synchronized seccomp failed: Unknown error 524 +177ms

  pw:protocol ◀ RECV {"method":"Browser.attachedToTarget","params":{"sessionId":"5bcd8d9c-7dce-4c3b-adf9-8e6fbd0fdc7e","targetInfo":{"targetId":"7aa58230-cee8-4208-abc1-e6b083c1c347","type":"page","browserContextId":"8f9c770c-ec69-43aa-b305-3d2b0a0a3901"}}} +278ms
  pw:protocol SEND ► {"method":"Page.setInitScripts","params":{"scripts":[{"script":"","worldName":"__playwright_utility_world__"}]},"id":13,"sessionId":"5bcd8d9c-7dce-4c3b-adf9-8e6fbd0fdc7e"} +1ms
  pw:protocol ◀ RECV {"id":12,"result":{"targetId":"7aa58230-cee8-4208-abc1-e6b083c1c347"}} +91ms
  pw:browser [pid=25206][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /tmp/playwright_firefoxdev_profile-racKao/search.json.mozlz4", (void 0))) +110ms

==== HERE ====
  pw:protocol ◀ RECV {"method":"Page.crashed","params":{},"sessionId":"5bcd8d9c-7dce-4c3b-adf9-8e6fbd0fdc7e"} +34ms
  pw:protocol ◀ RECV {"method":"Browser.detachedFromTarget","params":{"sessionId":"5bcd8d9c-7dce-4c3b-adf9-8e6fbd0fdc7e","targetId":"7aa58230-cee8-4208-abc1-e6b083c1c347"}} +1ms
```

According to Firefox's code: https://hg.mozilla.org/mozilla-central/file/tip/security/sandbox/linux/Sandbox.cpp#l229 , it crashes if it can not set seccomp+tsync

**Comment by aslushnikov** [comment]
@wxiaoguang so how do I repro this? Any simple test or snippet that I can run locally in default docker container that will illustrate the issue?

**Comment by wxiaoguang** [comment]
Reference: https://github.com/go-gitea/gitea/pull/20744 , the logs are collected from its failure logs. I can add you as editor for the repo and you can push to retry

I think it should be stable to reproduce (sorry that I am out and haven't prepared the environment on my carried computer)

**Comment by wxiaoguang** [comment]
Related  files:

https://github.com/wxiaoguang/gitea/blob/f08d8b836d5e7e791722e50f52edc92d4662c8fa/tests/e2e/example.test.e2e.js

It's started by  `npx playwright test`, pretty simple.

**Comment by aslushnikov** [comment]
@wxiaoguang i tried a few times to repro / figure out what to do, but it was very time consuming. A simpler repro is desperately needed! ideally, a simple github repo with a trivial playwright script and docker commands to run that demonstrate that things crash.

**Comment by wxiaoguang** [comment]
Sorry, I can not reproduce it on my side at the moment either. Maybe it could be related the Docker version or other environment configs for that CI servers (which I do not have privileges to access).

I think it's time to close this issue. Thank you very much!

**Comment by wxiaoguang** [comment]
And according to 
* https://github.com/deephaven/web-client-ui/issues/960#issuecomment-1416309049

Maybe it have been fixed somehow? 😂
