### ISSUE TITLE
Soft Assertions is not working in Test.Describe (Multiple Tests)

### ISSUE THREAD

**Issue by RaviThippana** [microsoft/playwright#17878]
Referring to the Title, I need to map my  each test case in to each test ( because in reports we need information how many test cases have passed and failed or skipped)
Currently Soft assertions can be applied to single test only. Where as if we apply to multiple tests under describe, any assertions error occurs all the remaining tests are skipped.
Overall, my main objective is to convert/Map Test cases to Test so that reports will show detailed information about ran tests cases.

I am using Playwright Version: 1.25.2
allure-playwright: 2.0.0-beta.19.

Please let me know how to deal with. Or workaround to show the details ( test case wise) in my allure report or HTML default reporter.

Thanks in advance.
![TestA](https://user-images.githubusercontent.com/113978282/194352209-c652da3d-1f2a-494c-97d3-43ada5fe38ae.png)
![TestB](https://user-images.githubusercontent.com/113978282/194352234-21d52f7a-c3f2-483d-af41-30df55b067b2.png)

**Comment by yury-s** [comment]
> Referring to the Title, I need to map my each test case in to each test ( because in reports we need information how many test cases have passed and failed or skipped)

Can you attach an example test.spec.ts file with the tests etc so that we can understand how you write it in playwright?

> Currently Soft assertions can be applied to single test only. Where as if we apply to multiple tests under describe, any assertions error occurs all the remaining tests are skipped.

All assertions work within a single test, this is by design. Can you explain what you mean by " if we apply to multiple tests under describe"?

Note that if a single test inside describe fails the remaining tests will still run (unless you explicitly configure 'serial' mode), so I this is the only limitation it should work already.

> Overall, my main objective is to convert/Map Test cases to Test so that reports will show detailed information about ran tests cases.

You can probably use [test.step](https://playwright.dev/docs/api/class-test#test-step) for a more fine grained information about individual step. Can you map Test Case to test.step:


```js
test('Test Suite', async () => {
  test('Test', async () => {
    await test.step('Test Case1', () => { ... });
    await test.step('Test Case2', () => { ... });
    await test.step('Test Case3', () => { ... });
  });
});
```
In the code above soft assertions will be checked once for all steps inside 'Test' at the end of the test. Would that work?

**Comment by RaviThippana** [comment]
My code looks like below
test.describe.serial("Test Suite", async()=>{
 test.beforeAll(async ({ browser }) => {
    const context = await browser.newContext();
    page = await context.newPage();
  });
  test("First Test Case", async () => {
            .........
});
  test("Second Test Case", async () => {
           await expect.soft(Expected).toHaveText(Actual);
});
  test("Third Test Case", async () => {
           await expect.soft(Expected).toHaveText(Actual);
});
});

In the above code, for example, if assertion fails in second test case, by default Third Test Case is skipped.
In Report:
by implementing above, my report will look like..
First Test Case - Passed
Second Test Case Failed
Third Case Skipped...

But, even though second one fails, it needs to run the third also right. Currently it's not working in that way. 

Why I am doing like this because, I need to show the report in Test Case wise. Hope you understood.


test('Test Suite', async () => {
  test('Test', async () => {
    await test.step('Test Case1', () => { ... });
    await test.step('Test Case2', () => { ... });
    await test.step('Test Case3', () => { ... });
  });
});


The above snipped what you have shared, will it work in serial mode..?

Thanks for your quick reply.

Thanks in advance

**Comment by yury-s** [comment]
> The above snipped what you have shared, will it work in serial mode..?

The steps inside test are not affected by cross test concurrency mode, so the answer is yes, they will work if the test is configured to run as part of a serial suite.

**Comment by JasKirk70** [comment]
I have seen the same problem when I run the tests in serial mode, even after using soft assertion if one test fails , the remaining tests are skipped.

**Comment by JasKirk70** [comment]
this bug raised https://github.com/microsoft/playwright/issues/16119 seems to be related

**Comment by RaviThippana** [comment]
> > The above snipped what you have shared, will it work in serial mode..?
> 
> The steps inside test are not affected by cross test concurrency mode, so the answer is yes, they will work if the test is configured to run as part of a serial suite. Would it solve your problem?

Will Implement and let you know.
Thanks

**Comment by RaviThippana** [comment]
> this bug raised #16119 seems to be related

Yes I know already, even I commented in that request, no one replied. that's why created new issue

**Comment by RaviThippana** [comment]
> > The above snipped what you have shared, will it work in serial mode..?
> 
> The steps inside test are not affected by cross test concurrency mode, so the answer is yes, they will work if the test is configured to run as part of a serial suite. Would it solve your problem?

No its not working, Test.step are not treating as a new Test. And in Report it's showing as Only one Test Case have ran.


test.describe('Test Suite', async () => {
  test('Test', async () => {
    await test.step('Test Case1',async () => { 
await expect.soft(Expected).toHaveText(Actual);
});
    await test.step('Test Case2', async() => { 
await expect.soft(Expected).toHaveText(Actual);
 });
    await test.step('Test Case3'async, () => { 
await expect.soft(Expected).toHaveText(Actual); 
});
  });
});

I implemented the above code what you have suggested, the script continues even though any assertion failure in the middle, but test.step is not treating as separate test(test case). Even one fails its shows all the steps/Test Case have failed.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/16119, please upvote that issue instead.
