### ISSUE TITLE
[BUG]not able to generate json report as well as html report stopped attaching video, snapshots and trace after implementing custom report

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#17892]
**Context:**
- Playwright Version: "@playwright/test": "^1.25.2",
- Operating System: Mac
- Node.js version: v16.17.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]

I was initially only using html reporter and I could see the video, snapshot and trace file attached in the index.html report. But I also wanted a custom reporter. But after I included the custom reporter I stopped seeing the video, snapshot and trace file attached in the index.html report. I am also not able to generate the json report

**Code Snippet**

```
reporter: [['html'],
            ["json", { outputFile: "Users/jkirk/Documents/Workspaces/qa-playwright-tests/src/utils/test-result.json" }], 
              ['/Users/jkirk/Documents/Workspaces/qa-playwright-tests/src/utils/customreport/CustomReporter.ts'] 
            ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    headless: false,
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    trace: 'retain-on-failure',
```

**Comment by yury-s** [comment]
Can you attach a minimal example with the custom reporter so that we could reproduce the problem locally?
