### ISSUE TITLE
[Question] Is it possible to enable the 'Record and Replay' feature as a global setting?

### ISSUE THREAD

**Issue by leggomuhgreggo** [microsoft/playwright#17899]
## Overview

**Use Case:** In order to reduce the time it takes to merge changes, I would like to run all my E2E tests w/ replay mode in Pull Request CI workflows -- and then run them live in the trunk branch CI.

All of the [docs](https://playwright.dev/docs/network#replaying-from-har) seem to be geared towards individual tests and I'm wondering what the best solution is to toggle this feature globally

## Possible Approaches

At first, I thought there would be a way to define this in `playwright.config.js` but I wasn't able to find anything.

Next, I looked at `globalSetup`, but didn't figure it'd be possible to apply a har setup to iterate for each test.

My current thinking is that I will need to write a utility based on `page.routeFromHAR`, using `testInfo.title` for the path -- and then call it from every test. But I am hoping to avoid this if possible.

The only other alternative that seemed potentially viable is a [fixture override](https://playwright.dev/docs/test-fixtures#overriding-fixtures). But I felt like that was going to possibly invite other complications. 

## Questions

- Is there a recommended way to configure record/replay globally? 
- Is there a way to toggle the replay mode when running tests from the command line? Should I just figure on an environment variable? 
- Since I'm trying to individuate the HAR recordings for each test, would it make sense to save as `zip`

----

Thanks for the cool feature and all the work y'all put into this library!

**Comment by yury-s** [comment]
> Is there a recommended way to configure record/replay globally?

Any of the two approaches (with shared util or a fixture) sounds fine as long as it solves the problem.

> Is there a way to toggle the replay mode when running tests from the command line? Should I just figure on an environment variable?

There is no dedicated option for that, environment variable is your best bet. See also this feature request https://github.com/microsoft/playwright/issues/10337

> Since I'm trying to individuate the HAR recordings for each test, would it make sense to save as zip

This is up to you, if you pick a file name with .zip playwright will automatically compress the har in a zip.

I'll keep this request open for now to collect more feedback.

**Comment by leggomuhgreggo** [comment]
## Update

Still finalizing my implementation, but I wanted to give an update.

Mainly it's been working great!

Here's the fixture override file I've ended up with.

<details>
  <summary>Show Code</summary>

```tsx
import { test as base, Page, TestInfo } from '@playwright/test';
import path from 'path';

const DEFAULT_OPTIONS: TestOptions['customHarParams'] = {
  enabled: rebool(process.env.ENABLE_RECORD_REPLAY),
  compress: rebool(process.env.SAVE_HAR_AS_ZIP),
  options: {
    update: rebool(process.env.UPDATE_RECORDINGS),
    notFound: 'fallback',
    url: rebool(process.env.ONLY_RECORD_GRAPHQL_CALLS) ? '**/graphql' : '**/*', 
  },
};

export type TestOptions = {
  readonly customHarParams: {
    readonly enabled: boolean;
    readonly compress: boolean;
    readonly options: Parameters<Page['routeFromHAR']>[1];
  };
};

export const test = base.extend<TestOptions>({
  customHarParams: [DEFAULT_OPTIONS, { option: true }],

  async page({ page, customHarParams }, use, testInfo) {
    if (customHarParams.enabled) {
      const outputPath = getOutputPath(testInfo, customHarParams.compress);
      await page.routeFromHAR(outputPath, customHarParams.options);
    }

    await use(page); // base functionality
  },
});


function getOutputPath(testInfo: TestInfo, shouldCompress: boolean) {
  const slug = testInfo.outputDir.split('/').slice(-1)[0]
  const fileSegment = shouldCompress ? `${slug}.zip` : `${slug}/main.har`; 

  return path.join(process.cwd(), `har/${fileSegment}`);
}
```
</details>


## Notes

### Idempotency

The main difficulty I ran into was around "idempotency" issues. 

#### Setup

Part of this was trivial -- just test setup + reused [storageState](https://playwright.dev/docs/test-auth#reuse-signed-in-state) need to be in sync with the recordings -- and also conditioned setup commands not to generate state when in replay mode.

#### GraphQL Limitation 
The more challenging piece had to do with non-idempotent GraphQL mutations, for example this test:
```
test('cannot duplicate home address', async (..) => {...})
```
It starts by sending the `addAddress(homeInput)` mutation, which resolved successfully. Then it tried to send a second `addAddress(homeInput)` and asserts that an error notification has appeared.

This works as expected when recording, but when replaying, it's not able to distinguish between the first and second request. 

##### Question
I'm actually not sure what the best approach to solving this is. 
- I think the most "robust" solution would be to use a nonce in the mutation input
- after the first mutation, I could try adding a second routeFromHar, configured to save the second mutation to a different file
- I could make a small change the payload of the second mutation -- enough to distinguish for playwright -- but not enough to nullify the test. 

**Aside:** this has prompted to me to improve our GraphQL Schema's type specificity and encourage individualization of Operation names. So that's a nice thing. 

### Global Controls + Test-Level Controls

When I first realized that not every test would work in replay mode, I was not sure how I was going to proceed with the global configuration option -- I really didn't want to have to shotgun record/replay changes across all my tests. 

But this library is magnificent. And I was able to use custom [parameters](https://playwright.dev/docs/next/test-parameterize#parameterized-projects) to add test-level controls -- so for that address test with the idempotency quirk, I changed it like this:

```
test('cannot duplicate home address', async ({ page, customHarParams }) => {
  test.skip(customHarParams.enabled, 'Still working on it');
  ...
})
```

This enables me to skip it only in when record replay is enabled -- and let it run normally when Im running the tests live. 

### Feature Visibility

I ended up adding some logging to help keep me on track when I was iterating back and forth a lot.

```tsx
  if (isRecordReplayEnabled) {
    console.log('====================================');
    console.log(`Running in ${isReplayMode ? 'REPLAY' : 'RECORD'} mode`);
    console.log('====================================');
  }
```
### Additional Usage Considerations

- One feature that I found myself wishing existed was "only save if successful". It was sometimes a chore to find which recordings corresponded to failed tests. And it'd be nice to be able to only have "passed" test recordings. 
- I think it'd be cool to have a default/standard recording path -- although it's easy enough to configure
- It was a little difficult to adapt my intuitive mental model to the "update" API. Initially I added an environment variable for both `ENABLE_RECORD` and `ENABLE_REPLAY` but realized that I was looking at impossible state. I think at some point I might play around with an enum eg  `REPLAY_MODE: RECORD | REPLAY | OFF` I think this is approximately what [PollyJS does](https://netflix.github.io/pollyjs/#/examples?id=typescript-jest-node-fetch).

Anyway I hope that's useful. 

Thanks!

**Comment by kimloco** [comment]
@leggomuhgreggo Thanks for the great fixture extension code. One questions I have - I can see from the code that an option can be used to enable or disable replay from HAR, but I don't see any code that actually records the HAR in the first place. Do you create a separate browser context with record HAR option enabled in your tests?

Thanks!

**Comment by leggomuhgreggo** [comment]
Hey @kimloco, glad you found it useful.

Right now it's controlled through environment variables. 
```ts
const DEFAULT_OPTIONS: TestOptions['customHarParams'] = {
  enabled: rebool(process.env.ENABLE_RECORD_REPLAY),
  compress: rebool(process.env.SAVE_HAR_AS_ZIP),
  options: {
    update: rebool(process.env.UPDATE_RECORDINGS),
    notFound: 'fallback',
    url: rebool(process.env.ONLY_RECORD_GRAPHQL_CALLS) ? '**/graphql' : '**/*', 
  },
};
```

But I think since it's using [fixture options](https://playwright.dev/docs/test-fixtures#fixtures-options) that could (probably should) be ported over to the main PW config file.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
