### ISSUE TITLE
[Question]How can I get value of input field

### ISSUE THREAD

**Issue by thuanvoparsley** [microsoft/playwright#17909]
Hi everyone,

 when I try to get the value of the input field, the empty value always displays. I also used some way as below but it didn't work
- const result = element.getAttribute('value');
- await page.$eval('locator', element => element.nodeValue))
- const result = page.inputValue('locator');
Could you please let me know if you have any solution?

Thanks
<img width="693" alt="Screen Shot 2022-10-07 at 22 51 48" src="https://user-images.githubusercontent.com/110482224/194596036-7124dcca-d2b8-4e36-ad55-bac5452b59f6.png">

**Comment by Nav-2d** [comment]
`inputValue` works for me.

```
await page.goto(
    "https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_value"
);
const frame = await page
    .frameLocator(`#iframeResult`)
    .locator('input#fname');
console.log(await frame.inputValue())
```

**Comment by yury-s** [comment]
Closing per the comment above. Free free to file a new bug with a repro if you still experience the issue.
