### ISSUE TITLE
[BUG] appIcon.png is loaded as a module

### ISSUE THREAD

**Issue by hamzaydia** [microsoft/playwright#17911]
I tried to build an executable of playwright using pkg

I got this bug:
[https://github.com/vercel/pkg/issues/1776](https://github.com/vercel/pkg/issues/1776)

which I found later that it's a playwright bug not pkg

**Comment by yury-s** [comment]
It's unclear from the description what you are trying to do what playwright bug is about. Can you attach a minimal example that demonstrates the problem?

**Comment by hamzaydia** [comment]
steps to reproduce:

package.json
```
{
  "name": "bug",
  "version": "1.0.0",
  "description": "bug",
  "main": "index.js",
  "scripts": {
    "dev": "node index.js"
  },
  "author": "",
  "license": "ISC",
  "type": "module",
  "dependencies": {
    "playwright": "^1.26.1"
  }
}
```

index.js
```
import { chromium } from 'playwright';
```

then:
```
npm install
```

then:
```
pkg index.js
```
Output:
```
> Warning Babel parse has failed: Unexpected character '�'. (1:0)
> Warning Failed to make bytecode node18-x64 for file /snapshot/pwbug/index.js
> Warning Failed to make bytecode node18-x64 for file /snapshot/pwbug/node_modules/playwright-core/lib/server/chromium/appIcon.png
> Warning Failed to make bytecode node18-x64 for file /snapshot/pwbug/index.js
> Warning Failed to make bytecode node18-x64 for file /snapshot/pwbug/node_modules/playwright-core/lib/server/chromium/appIcon.png
> Warning Failed to make bytecode node18-x64 for file C:\snapshot\pwbug\index.js
> Warning Failed to make bytecode node18-x64 for file C:\snapshot\pwbug\node_modules\playwright-core\lib\server\chromium\appIcon.png
```

and you can run it with --debug for verbose details.

**Comment by yury-s** [comment]
`pkg` is not a part of playwright, please continue with the bug in their repository. Support for pkg is not a goal for playwright. With that said, if there is a concrete change that needs to be made to the playwright code we can discuss that.

**Comment by hamzaydia** [comment]
That's not just with `pkg` even with `esbuild` which means clearly it's a playwright bug:

```
npx esbuild index.js  --bundle --outfile=build.cjs \
--format=cjs --platform=node
```

Output:
```
▲ [WARNING] "./appIcon.png" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/playwright-core/lib/server/chromium/crApp.js:28:67:
      28 │ ...t _fs.default.promises.readFile(require.resolve('./appIcon.png'));
         ╵
```

What I want to achieve is to build .exe from a playwright node.js app

**Comment by DemonMartin** [comment]
Encountering same issue. Anyone has found a fix for that?

**Comment by elyran** [comment]
Solution for esbuild:
Add `--external:<resolved-module>` to the command line.

For example, for the error:
```
▲ [WARNING] "./loader" should be marked as external for use with "require.resolve" [require-resolve-not-external]

    node_modules/playwright-core/lib/server/electron/electron.js:183:56:
      183 │         electronArguments.unshift('-r', require.resolve('./loader'));
```

You write this:
`esbuild --external:./loader ...`

Add each warned module as needed.
