### ISSUE TITLE
[BUG] Error: spawn EPERM Failed to launch browser. (firefox 1319)

### ISSUE THREAD

**Issue by tgrstamp** [microsoft/playwright#17913]
I'm getting this when using jest on windows

Error: spawn EPERM Failed to launch browser.
==================== Browser output: ====================
<launching>

or when trying to launch manually from the firefox directory I'm getting a pop-up saying file contains a virus or potentially unwanted software

Issue just started happen in the last day and doesn't happen with the chrome or webkit in ms-playwright directory

**Comment by yury-s** [comment]
Looks like your antivirus software kicks in and doesn't like firefox for some reason. Try changing your antivirus settings. Closing this issue as it is not actionable on our end.
