### ISSUE TITLE
[BUG] User-provided NODE_OPTIONS are overridden when debugging tests

### ISSUE THREAD

**Issue by badeball** [microsoft/playwright#17925]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Arch Linux
- Node.js version: 18.9.0
- Visual Studio Code version: 1.71.1
- Playwright for VSCode extension version: 0.2.10

**Code Snippet**

I'd like to specify `NODE_OPTIONS` to all child processes when running tests from VSCode. I do this by specifying `playwright.env` like so:

```json
{
    "playwright.env": {
        "NODE_OPTIONS": "...",
    }
}
```

**Describe the bug**

However, when debugging a test, `NODE_OPTIONS` gets overridden and wiped, ref. https://github.com/microsoft/playwright-vscode/blob/v0.2.10/src/playwrightTest.ts#L173. It works when I run a test "normally".

Can the extension play nice and augment user-provided NODE_OPTIONS when provided, similar to what happens in https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/cli.ts?

**Comment by pavelfeldman** [comment]
> Can the extension play nice and augment user-provided NODE_OPTIONS when provided

We need to clear the NODE_OPTIONS that VSCode itself is setting to enable process-tree debugging. We can hard-code those, but they are a subject to change, so it makes this task problematic.

**Comment by pavelfeldman** [comment]
> It's not how I would do it ideally, I think NODE_OPTIONS should be taken into account from all possible sources and in that particular case one source omitted.

Exactly. I'm Ok with merging your change that moves the settingsEnv below though, so please feel free to send a PR!
