### ISSUE TITLE
[Feature] support winappdriver

### ISSUE THREAD

**Issue by fenchu** [microsoft/playwright#1792]
Could you please talk to the nice people over at https://github.com/microsoft/WinAppDriver
it supports the selenium xml protocol via appium, should be easy to add this to playwright.

**Comment by arjun27** [comment]
Thanks for writing in @fenchu. Playwright has a very different approach and architecture from Selenium (happy to share more details), and we are focused on web apps only for now.

Having said that, I'm curious to know why you would want WinAppDriver support. Is there a way Playwright could add value to WinAppDriver and testing Windows apps?

**Comment by arjun27** [comment]
Closing this as out of scope for now.

**Comment by vandervillain** [comment]
We stumbled upon this and I thought I'd illustrate an example of how it would help us: 
We have an electron app with custom c++ node addons. The UI is used for authentication and workflow management, and the c++ is used to capture file/folder operations, tell our electron app, which hits some APIs. It would be nice to have playwright controlling the test process, authenticate through electron (OIDC worfklow) test the UI, and then use WinAppDriver to simulate file/folder operations.

**Comment by fenchu** [comment]
I use winappdriver to automate windows desktop via appium selenium api. But we are making a electron based webauthen yubikey app that requires me to run a command outside of the browser to mock it for testing. I can do this in winappdriver, but not in pupeteer with the chrome devtools protocol. Mainly because the chrome browser is not allowed to go outside of the browsers scope. Chrome devtools also offer way better control than selenium. This may be the winappdriver folks error because many object do not show up there.
