### ISSUE TITLE
[Question] modify the default timeout

### ISSUE THREAD

**Issue by curry-cb** [microsoft/playwright#17924]
the default 30s timeout is modified to 60s, why not in effect

![企业微信截图_16652268246000](https://user-images.githubusercontent.com/75304638/194704235-064df3c7-9ba2-4c00-aa74-6cb617c53a40.png)

**Comment by klhex** [comment]
I'd say you have not set up your Playwright Test Config correctly. See here for an example: https://playwright.dev/docs/api/class-testconfig#test-config-timeout

**Comment by curry-cb** [comment]
Is it right here?
![企业微信截图_16652861023611](https://user-images.githubusercontent.com/75304638/194736456-50378815-6e18-4fb8-a1d0-a1325307ea3d.png)

**Comment by curry-cb** [comment]
But I only introduced playwright module no config file, how should set the timeout of playwright in gauge?
![企业微信截图_16653005725912](https://user-images.githubusercontent.com/75304638/194743773-b526dc18-570c-4585-b783-91ebd339f7f0.png)

**Comment by klhex** [comment]
Oh, I see. You are not (yet ;) using Playwright Test as test runner. In that case, regarding the Playwright API, you should have a look at https://playwright.dev/docs/api/class-page#page-set-default-timeout and https://playwright.dev/docs/api/class-page#page-set-default-navigation-timeout.

**Comment by curry-cb** [comment]
OK,thank you~
