### ISSUE TITLE
[BUG] VSCode can't resolve node API if Playwright project exists in subdirectory

### ISSUE THREAD

**Issue by Torsteinws** [microsoft/playwright#17932]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Windows 11
- Node.js version: 18.7
- Browser: All

**Code Snippet**

```bash
# Init new Playwright project in a subdirectory of the repo
mkdir my-tests
cd my-tests
npm init playwright@latest

# This VSCode instance works fine
code .

# This VSCode instance can't resolve node API
cd ..
code . --new-window
```

**Describe the bug**

VSCode can't resolve node API if the Playwright project is created in a sub directory. 
However, everything seems to work fine when running the project, so only DX is affected.

**Solution to bug**

Adding an empty tsconfig.ts to the Playwright project.

**Comment by Torsteinws** [comment]
Sorry if this is the wrong place to post this bug. I just started tinkering with Playwright, and this caused quite a bit of friction for me when getting started.

**Comment by pavelfeldman** [comment]
> VSCode can't resolve node API if the Playwright project is created in a sub directory.

Could you elaborate? A screenshot would be great!

**Comment by Torsteinws** [comment]
Sure thing!

Here is a new playwright project, opened in two different instances of VSCode. The only difference between the two is which directory VSCode is using as root.  
![playwright-vscode-bug](https://user-images.githubusercontent.com/47348352/194920141-31774f36-bdd5-42cb-bc7d-6215157d6b67.png)


And here is the solution to the problem:
![bug-solutionpng](https://user-images.githubusercontent.com/47348352/194920213-2f292321-8dc4-47b5-ad41-fc2ac5cf4268.png)

**Comment by Torsteinws** [comment]
The same error occurs also when writing tests:

![image](https://user-images.githubusercontent.com/47348352/194958724-b35bf5f6-67b0-4414-88c7-b9d51b9541dd.png)

**Comment by pavelfeldman** [comment]
Yup, I can repro, opening VS Code in the outer folder does not resolve Node types. Interestingly, VS Code is smart enough to suggest that I install @types/node. Which I can clearly see installed under the node_modules, which is in the folder containing my config. I.e. it should resolve this dependency when it starts resolving from playwright.config.ts per Node rules. Looks like something VS Code team could look at!

**Comment by pavelfeldman** [comment]
Would you be interested in filing it there? I'm hesitant filing it because it feels too small of a deal given how unusual scenario is and how straightforward the workaround is.

**Comment by yury-s** [comment]
Closing per the response above, there is no further action planned on playwright end. @Torsteinws please file a bug with VS Code to have them fix it.
