### ISSUE TITLE
Opening Multiple URL's in a loop

### ISSUE THREAD

**Issue by nagendrakumar02** [microsoft/playwright#17939]
I am using NodeJS to scrape a website. The URL is different as I am passing an Id to the url. 

 results.forEach(async result => {
      let URL ="www.example.com?id=" + result.id;   /*some url  that keeps changing based on the id*/
      const browser =  await playwright.launchChromium({headless:true});  
      const context =  await browser.newContext();
      const page = await context.newPage();
      await page.goto(URL);  
....
Evaluate some results

     await page.close();
     await browser.close();
    
  }); 

This gives memory leak error. I also tried creating the browser outside of the for look to no avail. I also tried to setTimeout after the evaluate  Does anybody have a suggestion on how to accomplish this?

(node:47667) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 101 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit

**Comment by pavelfeldman** [comment]
You need to close context after each navigation in your look and create a new one.
