### ISSUE TITLE
[Feature] test.todo or test.manual

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#17945]
_testcase_ – a set of actions to perform to verify some functionality
_test_ – automated testcase

In our delivery process **all** our testcases are stored as a code:

`test` – automated testcase
`test.skip` – broken/outdated testcase (not test!) which must not be checked anyway
`test.todo` – testcase, which is valid and must be checked until release, but not implemented as autotest yet.

Let say we have two testcases:

```ts
test('testcase one')

test.todo('testcase two')
```

the second one will be uploaded to Allure EE as _inprogress_ testcase, which must be checked. QA guy could mark it as _Passed_ or _Failed_ manually:

<img width="534" alt="Screenshot 2022-10-10 at 08 35 09" src="https://user-images.githubusercontent.com/2929442/194804158-80dd7c73-fa65-41e9-95d3-2e83b0d60e20.png">

So, our QA do this:

1. Run all tests (this is done automatically by pull request CI) → generate report → upload report to Allure as a _test launch_
2. Inspect the _test launch_ – and here we come 1) some testcases passed 2) some testcases failed 3) some testcases are not implemented
3. Run manually all failed and not implemented testcases (within the same test launch!)
4. Close test launch
5. Merge pull request if launch is successful → run CD and make a release

What do you think about the idea of using autotests as a source of truth for all testcases? Including these which could not be automated (e.g. hover state or some rare browser).

What do you think about `test.todo` or `test.manual` annotation for such a case?

[Jest](https://jestjs.io/docs/api#testtodoname) and [CodeceptJS](https://codecept.io/basics/#todo-test) already have this. But Jest does not allow to pass callback, which is not good, because we cannot set allure.description anywhere but in callback. allure.description is important for QA guy, because it contains a body of a testcase (a human readable set of actions to perform).

**Comment by vitalics** [comment]
Agreed with you. I put references to relevant issue/discussion to keep in track
https://github.com/microsoft/playwright/issues/10918 
https://github.com/microsoft/playwright/discussions/10914

**Comment by pavelfeldman** [comment]
`test.todo` is called `test.fixme` in Playwright test and there is no notion of the manual test, because Playwright is automated test runner!

**Comment by Diokuz** [comment]
> Playwright is automated test runner!

The best one!

We are just seeking for better QA architecture, which includes explicit _testcase → autotest_ stage)

**Comment by pavelfeldman** [comment]
I would suggest introducing a convention for annotating those using fixme. Something like a tag, annotation or attachment:

```js
test.fixme('add to cart @manual', async ({ page }) => {
  test.info().annotations.push({ type: 'manual' });
  test.info().annotations.push({ type: 'spec', description: `
    1. Log in
    2. Pick product
    3. Add to cart
  ` });
  test.info().attach('spec', {
    body: `
      1. Log in
      1. Pick product
      1. Add to cart
    `,
    contentType: 'text/markdown'
  });
});
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by markalanevans** [comment]
@pavelfeldman  in your example:

```
test.fixme('add to cart @manual', async ({ page }) => {
  test.info().annotations.push({ type: 'manual' });
  test.info().annotations.push({ type: 'spec', description: `
    1. Log in
    2. Pick product
    3. Add to cart
  ` });
  test.info().attach('spec', {
    body: `
      1. Log in
      1. Pick product
      1. Add to cart
    `,
    contentType: 'text/markdown'
  });
});
```

 how does get visualized?  Is there some way to visualize that at a higher level all pretty?
 
 
![CleanShot 2024-06-13 at 18 07 36@2x](https://github.com/microsoft/playwright/assets/129052/3627fe16-4334-4f89-80bd-8a000021ec42)

**Comment by TomasHubelbauer** [comment]
It would be really cool to add an alias for `test.fixme` called `test.todo`. To me, semantically, the two names aren't equal (one is for tests that are broken, the other is for tests that are work in progress or fully empty). @pavelfeldman it would seems that you see things differently considering your comment here:

> `test.todo` is called `test.fixme` in Playwright

As such, would you be open to introducing an alias? Seeing as other test frameworks like Jest have `test.todo` and it is already muscle memory for many developers, doing so would be a nice pit-of-success type improvement, IMO.
