### ISSUE TITLE
[Question] Is there a way to merge test reports?

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#17944]
I have a scenario: hundreds of test scripts are distributed to different execution machines to run, and the html reports generated after running are in different places. How to merge these html reports together so that users can view them conveniently? After all, users do not need to be aware of the execution logic of scripts

**Comment by Nav-2d** [comment]
Related https://github.com/microsoft/playwright/issues/10437

**Comment by pavelfeldman** [comment]
Folding into #10437
