### ISSUE TITLE
[BUG]: scripts are not running on firefox browser if video is on config file in playwright

### ISSUE THREAD

**Issue by anjireddy5817** [microsoft/playwright#17950]
use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
  //   baseURL: "https://ecommerce-playground.lambdatest.io/index.php?",

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    headless: false,
    trace: "retain-on-failure",
    screenshot: "on",
    **video: "on",**
    launchOptions:{
      slowMo: 1000,
    }

After opening firefox instance getting below statement on console and closed immediately:
browserContext.newPage: Page closed.

Could you please resolve ASAP.

**Comment by pavelfeldman** [comment]
Could you share a scenario we could reproduce? Preferably in a form of a github repo.

**Comment by anjireddy5817** [comment]
Scripts are not running if you configure "video: on" on the playwright.config file

**Comment by pavelfeldman** [comment]
Which scripts, test scripts or page scripts? We would need exact steps to follow in order to address this!

**Comment by pavelfeldman** [comment]
Could it be that you set `video: undefined`?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
