### ISSUE TITLE
[Question] Can the new locators strategy be used within a Shadow DOM

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#17954]
Thanks for the latest version 1.27 and the changes regarding locators. 

I wanted to know if the new methods are able to pierce shadow DOM or not as I am getting failures when trying to access elements inside a shadow DOM.

Test URL ->  [Link](https://selectorshub.com/xpath-practice-page/)
Test Element -> Input with the placeholder text `Do you love tea`

Using a CSS selector works absolutely fine - so this works

`await page.frameLocator("#pact").locator("input[placeholder='Do you love tea']").fill("Kancha China");`

but this

`await page.frameLocator("#pact").locator("input").getByPlaceholder("Do you love tea").fill("Kancha China");`

fails after waiting for the timeout period of 30 seconds.

**Comment by pavelfeldman** [comment]
```js
await page.frameLocator("#pact").locator("input").getByPlaceholder("Do you love tea").fill("Kancha China");
```

In here, you are saying "within input find by placeholder". Should be

```js
await page.frameLocator("#pact").getByPlaceholder("Do you love tea").fill("Kancha China");
```

**Comment by JarodChen** [comment]
I met same issue, my case also can not visit the content that in the shadow dom  like
<div>
     #shadow-root (user agent)
        <div>the content i want to get</div>
</div>

do we have any workround?  my app is write by angularjs, almost inputs value are in shadow root

**Comment by zac11** [comment]
@JarodChen Are you using an xpath locator? Xpaths do not pierce shadow dom by default, where as css locators and text locators do. I applied the solution given by Pavel and my code works without any doubt.

**Comment by zac11** [comment]
> ```js
> await page.frameLocator("#pact").locator("input").getByPlaceholder("Do you love tea").fill("Kancha China");
> ```
> 
> In here, you are saying "within input find by placeholder". Should be
> 
> ```js
> await page.frameLocator("#pact").getByPlaceholder("Do you love tea").fill("Kancha China");
> ```

Works perfectly.

**Comment by JarodChen** [comment]
> @JarodChen Are you using an xpath locator? Xpaths do not pierce shadow dom by default, where as css locators and text locators do. I applied the solution given by Pavel and my code works without any doubt.

appreciate your reply!
