### ISSUE TITLE
[BUG] DOM is not loaded properly in the trace

### ISSUE THREAD

**Issue by Karlo5o** [microsoft/playwright#17968]
Hello guys,

when I want to look at the snapshot in my Playwright test trace I see **broken page in the snapshot**:
![image](https://user-images.githubusercontent.com/36458173/194493498-1d3037b0-4ea9-402c-809e-cf9594cd7628.png)
Even though the screenshot from the top navigation looks normal:
![image](https://user-images.githubusercontent.com/36458173/194487065-15160dfd-9085-4b50-824b-ebdaf96c141c.png)

Of course the **web page is working** and **tests are passing**, but this kind of evidence (trace) is not working for me. These tests are used for internal web application, could the slow page loading speed cause these problems? Because tracing works just fine with classic pages e.g. google.com. And if so, is there a way how to make snapshots wait after the page is loaded properly?

Using:
Python 3.10.4, **Playwright 1.26.1**, python-playwright 0.3.0, pytest 7.1.3.
OS: Windows 10
Browser: Chromium-1024

Thanks for your help :)

**Comment by yury-s** [comment]
@Karlo5o Can you share an example of the page where it happens so that we can reproduce it locally and see where it breaks? Without that we can't tell where it breaks.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

**Comment by Karlo5o** [comment]
Sorry for late response. I have been experiencing this problem for few weeks, but suddenly it works just fine. Application wasn't change neither the version of Playwright, I guess it could have been some issue with deploy server. But thanks for response :)
