### ISSUE TITLE
[Question] Typescript Monorepo Tsx Issue

### ISSUE THREAD

**Issue by rubber-duck-software** [microsoft/playwright#17964]
I am getting the following error: 
```
SyntaxError: Unexpected token '<'
```
Because, deep in my test's dependency tree, I import a tsx file. Any workaround for this would be awesome, because this error is currently blocking adoption. 

More details on my project setup below: 

We are looking to adopt playwright for e2e testing one of our sites. The site is located in a typescript monorepo. Some packages in the typescript monorepo are only used internally, and so are not compiled. One of these packages is our "core" package in which we locate all of our core business logic. This package handles database interactions, sending email, accepting payments, etc. All use case logic is in the "core" package. Our strategy for authoring html emails is to use react, giving us reusable components for all our emails. So, deep in the "core" package, we import jsx/tsx files. 

Since the core package also handles database interactions, it exposes a set of functions used to seed data, like `SeedFoo`, and `SeedBar`. These seed functions are called before some end to end tests to provide the appropriate data state for the site. 

So, our tests import `core` and `core` contains tsx files, causing the error above.

Is there any workaround to allow playwright tests to import tsx files (even indirectly)? In not, is this on the roadmap at some point?

Note: We are not using component testing at this time. We are not trying to import these components in the context of component testing. And we cannot have these email related react components subject to same limitations as component testing (ie no react fragments). 

Any help people can offer would be greatly appreciated.

Thank you! :)

**Comment by pavelfeldman** [comment]
There are workarounds for this other than extracting the code that you intend to reuse into isomorphic TS utility files. We can't and don't want to import TSX files in our e2e story because you can accidentally feed Playwright with the code that intends to run in the browser, while your Playwright tests run in Node.js for more powers and parallelization.

**Comment by rubber-duck-software** [comment]
Thank you for the quick response! :)

For my use case, we really do have tsx files which are imported in Node.js packages. Awesome that playwright protects its users from misunderstanding the model and trying to use client only code in their tests. I think that is a great safety feature. 

Is there a way for me to disable this safety feature? What kind of workarounds do you recommend (aside from changing our project structure altogether)? 

Thanks again for you attention!

**Comment by pavelfeldman** [comment]
I had a typo in my original reply. So the workaround would be to extract no-component code into the files with .ts extension that can be used from the tests.

**Comment by rubber-duck-software** [comment]
Tsx files are allowed in typescript Node.js projects (with jsx: 'react' tsconfig). To be clear, there are no plans to support this typescript compiler flag in playwright?

**Comment by pavelfeldman** [comment]
> Tsx files are allowed in typescript Node.js projects (with jsx: 'react' tsconfig).

Tsx files are allowed by tsc as far as the type checking is concerned. This config option is saying "don't yell at tsx in my source code, type check it". Typescript is not the one that is transpiling your code, webpack / babel, rollup / esbuild, etc would be doing that and they will be targeting the browser environment (or Jest's emulation of that environment). So you can't run that code in a general-purpose Node, it is not a browser. No other tool supports it and we won't be either.

**Comment by rubber-duck-software** [comment]
I think we have a different understanding of the typescript compiler and its role in the larger ecosystem. 

From the typescript docs [here](https://www.typescriptlang.org/docs/handbook/jsx.html)
> TypeScript supports embedding, type checking, and compiling JSX directly to JavaScript.

I believe the JSX transform is a special case in the JS transpilation ecosystem since typescript supports it natively (without webpack / babel, rollup / esbuild, etc). Further, since JSX is just transformed into Javascript, it can execute correctly in Node.js, not just in the browser.

As for other tools which support Node.js TSX, this isn't something that I think of tools explicitly supporting. This is done simply with a typescript compilation. On our backend, we use tsx files in Node.js, run with ts-node using swc as our compiler. Currently, we have use cypress for e2e testing and these tsx files are imported into [cypress tasks](https://docs.cypress.io/api/commands/task) (run Node.js in cypress). 

My interpretation of this is that playwright's support for typescript is incomplete since typescript will transform JSX but playwright cannot. I have very little experience with playwright and certainly don't understand how it works internally. Any help you could provide (or any correction you can offer) would be welcome. 

Thank you!

**Comment by pavelfeldman** [comment]
> I think we have a different understanding of the typescript compiler and its role in the larger ecosystem.

Let's try to get to the bottom of this!

> I believe the JSX transform is a special case in the JS transpilation ecosystem since typescript supports it natively (without webpack / babel, rollup / esbuild, etc). Further, since JSX is just transformed into Javascript, it can execute correctly in Node.js, not just in the browser.

I agree I should not have emphasized it or used it as an argument. Yes, TSC has a transpilation option, so you can refer to it as to a transpiler. I'm used to clearly separating the type checking where TSC is the only solution + a non-TSC production bundler.

> Further, since JSX is just transformed into Javascript, it can execute correctly in Node.js, not just in the browser.

The link you provide above lists all the JSX transpilation options. I assume you are using `react` mode that emits `React.createElement("div")` in your setup. This code won't run in Node though - it needs the react jsdom shims to function inside Node. That's what I meant when I said that it is intended to run in the browser. Now imagine we supported that in Playwright. It would mean that:
1) Our target platform would be Node + JSDom instead of pure Node, which is problematic due to us stating that you must run tests in the browser, not simulate them in Node. But more importantly
2) We would see parts of JSDom trees flying around in the test code, completely detached from what is happening in the browser.

If running both page and the test runner in the same runtime is important to you, you can use either Jest (simulating browser in Node) or Cypress (executing test runner inside page). Playwright clearly separates the two, your page lives in the browser, your test code lives in Node. See https://playwright.dev/docs/next/evaluating for more details.

**Comment by rubber-duck-software** [comment]
I think we mostly agree, but there is a technical question which I think we might differ on and, for me, is at the heart of the issue. Namely, 

**Can JSX be used in vanilla typescript Node.js?**

I think the answer to this is yes, because I believe that is what my project is doing. We have a large Node.js backend which performs a variety of functions, including sending HTML emails. Since these are just another kind of visual for our users, we decided to use React (since our team already had expertise). Therefore, we author our email content in JSX, and then call `renderToString` from `react-dom/server`. This gives us the HTML content for our emails. All of this works (I believe) without JSDom and I believe we can still count our backend as a vanilla typescript node project. 

If I am right in thinking that JSX can be used in vanilla typescript Node.js, then my question is, _how do I prevent the syntax error in playwright?_ I don't want my page to render in Node.js, nor do I want playwright to execute in browser. I really love playwright's model. To be clear, my JSX in Node.js has nothing to do with the page I am trying to test. It just so happens that JSX is in the dependency tree for my playwright tests. Since this is allowable in typescript Node.js, I wish I could work around the syntax error in playwright. 

I realize this limitation likely doesn't effect many users, thanks for spending your time figuring it out with me :)

**Comment by pavelfeldman** [comment]
> All of this works (I believe) without JSDom and I believe we can still count our backend as a vanilla typescript node project.

Yup, it looks like `react-dom` has enough smarts to spit out the HTML markup w/o JSDom. So in my message above, we should replace `Node+JSDom` with `Node+React`.

Supporting JSX in our setup is a technicality, nothing prevents us from enabling it. We both seem to appreciate the separation ("To be clear, my JSX in Node.js has nothing to do with the page I am trying to test"), but supporting your use case is a change that goes against that separation even though in a non-explicit manner. Having said that, we can try doing that and not tell anyone that we supported it. Let me schedule it for 1.28.

**Comment by rubber-duck-software** [comment]
Wow! Thanks much for looking at this, that's really great! I'm super excited to get to use playwright on this project going forward. 

Thanks for your attention on this issue. Looking forward to 1.28!
