### ISSUE TITLE
[Feature] Support NodeList and Node[] as return from Page.evaluateHandle(pageFunction[, arg])?

### ISSUE THREAD

**Issue by ducktype** [microsoft/playwright#1797]
As documentation states we should return a single DOM Node or Serializable value from pageFunction.
What i'm interested in is to support also a NodeList from the page like the one returned by document.querySelectorAll and for convenience also a JS Array of Node/Elements like [document.querySelector('a'),document.querySelector('p')] and probably also the type returned by document.evaluate('.//a',document).

In my speculation the parallel is between Page.$$('xpath=') and Page.$$('css=') and Page.evaluateHandle(), which should be able to support the same return data types.

This will allow a scenario like this:

```
var arrh = await page.evaluateHandle(()=>document.querySelectorAll('a'))
var arrh = await page.evaluateHandle(()=>[document.querySelector('a'),document.querySelector('p')])
var arrh = await page.evaluateHandle(()=>Sizzle('a'))
var arrh = await page.evaluateHandle(()=>document.evaluate('.//a',document))
```

To my understanding this should be possible and in some way supported by the underlying Chrome DevTools Protocol, but i'm unable to see the exact point where it happens in the code,
i see Page.$$() able to return a list of ElementHandle which uses"Selectors._queryArray()" and "Selectors._queryAll()" calling "const arrayHandle = await context.evaluateHandleInternal(...)" but i'm not able to find the exact point where the marshalling happens to compare this to the Page.evaluateHandle() implementation.

**Comment by pavelfeldman** [comment]
The way it would be solved is via introducing a new ArrayHandle beside JSHandle and ElementHandle. I'm supportive to this overall.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.

**Comment by trixn86** [comment]
I'm also very interested in this.

I have a page with a "load more" button which loads data from an API and adds child nodes to a DOM node. I want to be able to observe this node using a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) and return it's nodes which where added. Something like this:

``` javascript
await page.evaluate(listElem => {
        window.observeListPromise = new Promise(resolve => {
            new MutationObserver((mutationList, observer) => {
                mutationList.forEach(mutation => {
                    resolve(Array.from(mutation.addedNodes));
                    observer.disconnect();
                });
            }).observe(listElem, {childList: true});
        });
    }
)

await button.click()

const nodes = await page.evaluate_handle(
    async () => {
        nodes = await window.observeListPromise;
        return nodes;
    }
)
```

**Comment by rinogo** [comment]
Just tossing out another +1 for this feature - 

I've worked around this issue by exposing a `getElement(i)` function in the page context that I can call iteratively instead of a single `getElements()` function.

The latter would obviously be much better for many reasons, but this hacky approach works for now.

Thanks for all of the work you do on Playwright! It's awesome.
