### ISSUE TITLE
[Question] Webkit WebCrypto Pop Up

### ISSUE THREAD

**Issue by ps-jalvarado** [microsoft/playwright#17976]
I am using playwright in order to automate adding an item to the shopping cart. This only works on webkit but I have noticed that once it reaches the cart drawer it will create a pop up shown below that happens every single time once the cart drawer loads. Is this normal behavior and if so is there a way to bypass or prevent it? I am running my application in a container so it is failing because of this I assume. But for testing I am running locally headed. Thank you.

- Playwright Version: 1.26.1
- Operating System: Mac OS (M1)
- Node.js version: 16.17.1
- Browser: Webkit (Headless)
- Extra: Using Docker Container

```javascript
const { firefox, webkit } = require('playwright');  // Or 'chromium' or 'webkit'.

(async () => {
  const browser = await webkit.launch({
    headless: false
  });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.homedepot.com/p/Simpson-Strong-Tie-9-x-1-1-2-in-1-4-Hex-Drive-Strong-Drive-SD-Connector-Screw-100-Pack-SD9112R100/202071152',{
    waitUntil: 'load',
    timeout: 120000
  });
  await page.waitForTimeout(5000)
  await page.click("div.u__center div.fulfillment__head div.delivery-true")
  await page.waitForTimeout(5000)
  await page.click("div.buybox__atc div button span.bttn__content")
  await page.waitForTimeout(5000)
  //await browser.close();
})();
```
![Screen Shot 2022-10-10 at 2 11 02 PM](https://user-images.githubusercontent.com/105526118/194975679-3a9d971f-ff97-48b4-8a1f-ec505158ed2d.png)

**Comment by yury-s** [comment]
@ps-jalvarado what linux image do you run in the container?

**Comment by ps-jalvarado** [comment]
Using `ubuntu:22.04` for the linux image

**Comment by yury-s** [comment]
The popup looks like macOS native window while you mentioned that you run the test in the docker container if I understood correctly. If playwright runs inside the container it should no be able to trigger such dialog in the host OS, can you tell us more about how you run the test and how the docker container is involved into the process?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
