### ISSUE TITLE
[BUG]Junit Report xml not getting generated with Playwright version 1.27

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#17978]
**Context:**
- Playwright Version: [1.27]
- Operating System: [Windows, Linux]
- Node.js version: [14.6]
- Browser: [ Chrome]

  In playwright conf file
    **reporter: [
        ['junit', { outputFile: `./testResults/report.xml` }],
]**
     
**Describe the bug**

With latest version of playwright(1.27) noticed that report.xml not getting generated  while this works fine till previous version i.e 1.26.1

So this is desired changes or bug introduced.?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
