### ISSUE TITLE
[BUG] toContainEqual, objectContaining

### ISSUE THREAD

**Issue by benjaminviaud** [microsoft/playwright#17970]
**Context:**
- Playwright Version: 1.27
- Operating System: Mac osX
- Node.js version: 16.17.1
- API

**Code Snippet**

```javascript
import { expect, test } from '@playwright/test';

test('Login erreur identifiants incorrects', async ({ request }) => {
	const response = await request.post(`/api/v1/users/login`, {
	  data: {
		email: 'unknow@user.com',
		password: 'test',
	  }
	});
	expect(response.ok()).toBeFalsy();
	expect(await response.json()).toContainEqual(expect.objectContaining({
		"message":"Identifiants de connexion invalides"
	}));
	expect(response.status()).toBe(400);
});
```
**Test**
![Capture d’écran 2022-10-10 à 22 11 29](https://user-images.githubusercontent.com/25077689/194944760-0efccda2-2c06-4005-bc85-99b03aaefada.png)

**Describe the bug**

I follow the Docs API testing : https://playwright.dev/docs/test-api-testing#writing-tests
I don't understand why i have an error

Thanks for your help

**Comment by pavelfeldman** [comment]
Did you mean following instead?

```js
expect(await response.json()).toEqual(expect.objectContaining({
		"message":"Identifiants de connexion invalides"
	}));
```

**Comment by pavelfeldman** [comment]
Oh, I can see you took it from our docs, let us fix them.

**Comment by pavelfeldman** [comment]
My colleague is telling me that the example was with a list of issues, so the docs seem to be correct.
