### ISSUE TITLE
[Question] workers on selenium grid

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#17984]
Hi guys, quick question, if I set my workers like this:

workers: process.env.CI ? undefined 

When I run the tests against a Selenium Grid, it always sets only 1 worker. Should I specify the workers or based on what Playwright picks them?

Thanks!

**Comment by pavelfeldman** [comment]
I'm not sure I follow the question, workers will be what you set it to be, would be 1 if you set 1.

**Comment by pavelfeldman** [comment]
I can't explain it, undefined should be picking the default value in all cases, it has nothing to do with Selenium grid. Having a repro would help getting to the bottom of this. A minimal repro in a form of the github repo would be ideal.

**Comment by imartinflores** [comment]
Thank you! No worries, I'll see if I can create something and will link it in a new issue, I'll close this one , wanted to clarify that behaviour. Thank you very much!
