### ISSUE TITLE
[BUG] Unable to upload any extension in the codegen browser instance

### ISSUE THREAD

**Issue by Santhosh-kumar21** [microsoft/playwright#17983]
**Context:**
- Playwright Version: 1.23.0
- Operating System: Mac
- Language: Java
- Browser: Chromium

I'm not able to add extension from local to the chromium instance which is launched through the below command
 mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="codegen playwright.dev".
Also when i tried to add any extension from chrome web store, the browser getting closed with the below error

/private/var/folders/vj/c0qbx9md2yg6ns_m0nd4qgh40000gq/T/playwright-java-3529224288155066191/package/lib/utils/index.js:100
  if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Download started in unknown page: {"frameId":"C94348C442ADF1587B602E73C8418180","guid":"753f2359-6c13-437f-a6bf-25122242cb40","url":"file:///Users/santhoshkumarg/Downloads/chrome%20(31).zip","suggestedFilename":"chrome (31).zip"}
    at assert (/private/var/folders/vj/c0qbx9md2yg6ns_m0nd4qgh40000gq/T/playwright-java-3529224288155066191/package/lib/utils/index.js:100:21)
    at CRBrowser._onDownloadWillBegin (/private/var/folders/vj/c0qbx9md2yg6ns_m0nd4qgh40000gq/T/playwright-java-3529224288155066191/package/lib/server/chromium/crBrowser.js:286:23)
    at CRSession.emit (node:events:390:28)
    at /private/var/folders/vj/c0qbx9md2yg6ns_m0nd4qgh40000gq/T/playwright-java-3529224288155066191/package/lib/server/chromium/crConnection.js:228:14

**Comment by pavelfeldman** [comment]
> I'm not able to add extension from local to the chromium instance which is launched through the below command

Could you elaborate on what this means 'to add extension from local to the chromium instance' ?

**Comment by santhoshmechatron** [comment]
Hi Pavel,
Good Morning. 
What i meant was, uploading the extension which got saved in local machine to the browser instance .

**Comment by pavelfeldman** [comment]
Hm, we don't support uploading the extensions to the browser instance. Are you trying to automate some chrome:// pages that upload local extension? This would be outside of scope for Playwright because chrome:// pages are not actually web, they are browser internals.
