### ISSUE TITLE
Missing comments from code generated by codegen

### ISSUE THREAD

**Issue by acampa** [microsoft/playwright#18006]
**Context:**
- Playwright Version: 1.27
- Operating System: Windows
- Node.js version: 16.17.1
- Browser: All

npx playwright codegen

**Describe the bug**
When recording a test using codegen the code comments no longer appear as I perform the test. The only other thing that change was that I updated powershell from 5.0 to 7.2.6. I also tried reinstalling playwright but no luck. Does no matter what binding I pick

![image](https://user-images.githubusercontent.com/30902321/195197283-ac401ebb-9e19-4dd6-9c70-caa54d04a439.png)

**Comment by Nav-2d** [comment]
I believe it is an expected change. Since the actions are self-explanatory, the comments were removed. Ref: https://github.com/microsoft/playwright/pull/17747

**Comment by pavelfeldman** [comment]
Playwright 1.27 removed the comments, we assume those calls are now self-documenting.
