### ISSUE TITLE
[BUG] process.send() not working in playwright

### ISSUE THREAD

**Issue by sjainr** [microsoft/playwright#18014]
[**Context:**]
- Playwright Version: [1.25.2]
- Operating System: [1.25.2]
- Node.js version: [14.17.5]
- Browser: [Chromium]

I am trying to run playwright test by spawning a child process using child_process library

**Code Snippet**
```javascript

//parent.js
const { spawn } = require("child_process");

var proc = spawn("npx", ["playwright","test","tests/example.spec.js"], {
    shell: true,
    stdio: ['ipc']
  });
  proc.stdout.on("data", (data) => {
    console.log("stdout: " + data); //this works
  });
  proc.on('message', function (message) {
    console.log(message) // this doesn't work
  })

//inside example.spec.js(playwright test file)
process.send("Hello from child") // doesn't work

```

**Describe the bug**

At times, I get an error saying that process.send is not a function.
![image](https://user-images.githubusercontent.com/109061130/195277545-de8f17d7-dd7c-4cc5-9d67-7f2ce20902bf.png)

**Comment by pavelfeldman** [comment]
We control the worker process of Playwright Test, so you can't send messages to its parent.

**Comment by sjainr** [comment]
Thanks for the update @pavelfeldman 😄. Can you suggest any way/workaround to send message from playwright test(running inside a child process) to its parent process?

**Comment by yury-s** [comment]
@sjainr you can create another IPC connection using [node API](https://nodejs.org/api/net.html#ipc-support). Can you tell us more about what you are trying to achieve, maybe there is another API in Playwright that you can use?

**Comment by sjainr** [comment]
Thanks for writing @yury-s. 

- My idea is actually to trigger playwright tests via an API call.

- I am spawning a child process and running playwright tests inside it. 

- And while doing so, I want the send some messages like data from the UI, etc.. from my playwright child process to my parent process i.e. my API so that I can send those messages in my API response which will be used by other services.

So, for example - 
```javascript
//my-server
app.get("/runPlaywrightTests", async function (req, res) {
  var proc = spawn("npx", ["playwright","test","tests/example.spec.js"], {
    shell: true,
    stdio: ['ipc']
  });

let messages = [];
  proc.on('message', async function (message) { // this doesn't work
    console.log(message) // this doesn't work
    messages.push(message) // this doesn't work
  })

  proc.on("exit", async function (code, signal) {
    if(code==0)
      res.json({ testStatus: "success", response: messages});
    else
      res.json({ testStatus: "failure", response: messages});
  });
})

**Comment by yury-s** [comment]
The code above tries to open IPC channel between  `my-server` and playwright test runner process, each test runs in a worker process spawned by the test runner process. So even if you open an IPC channel to the test runner you'll still have to route the messages to workers. To avoid all of that it'd be easier to establish a connection (IPC or even http?) between the tests and `my-server` directly. If you only need to send messages from the tests to `my-server` you can probably get away with writing to stdout/stderr in the tests (with some unique prefix) and then reading that stream in `my-server`.

I'm going to close this bug as we are not planning to change current IPC mechanism used by the test runner.

**Comment by alexkuc** [comment]
This is the workaround I have used to display stdout/stderr from inside `.test()`. Using asynchronous commands like `spawn` or `exec` will _not_ work. Like initial comment on this issue have said, nothing will be shown. Instead, use synchronous commands like `spawnSync` and `execSync`. Keep in mind that buffers won't be flushed until command finishes so you won't see output in real-time. Also, in some cases, your app might appear to "hang" because it is waiting for input but since buffers won't be flushed until after the command finishes, it causes command to indefinitely wait. A bit gotcha for headless systems like CI! If you want to separate stdout and stderr, you can use something like this:

```typescript
const cmd = 'bin';
const args = [];
const buffers = spawnSync(cmd, args, { stdio: ['inherit', 'pipe', 'pipe'] });
if (buffers.stdout.length > 0) {
  // do something with stdout...
}
if (buffers.stderr.length > 0) {
  // do something with stderr...
}

```
