### ISSUE TITLE
[BUG] Explorer doesn't show getByRole

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#18018]
**Context:**
- Playwright Version:1.27.1
- Operating System: Mac
- Node.js version: 16.6
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

```js
npx playwright test --debug
```

**Describe the bug**

should show getByRole in explorer

<img width="712" alt="Screenshot 2022-10-12 at 10 41 33" src="https://user-images.githubusercontent.com/13063165/195295908-c3ee8cb1-3acc-4fe0-8550-96706af852c7.png">

**Comment by Nav-2d** [comment]
Hi, I am facing a similar issue with `getByPlaceholder` and `getByTestId`. Adding it here for reference:

![image](https://user-images.githubusercontent.com/22205721/195412473-4826c350-02ca-4e6d-93d7-392d6bc7df1f.png)

**Comment by mxschmitt** [comment]
The same happens for the trace viewer in the actions tab.
