### ISSUE TITLE
[Question] How do I use if-statements to filter if elements exist or not?

### ISSUE THREAD

**Issue by lmathuse** [microsoft/playwright#18020]
I tried using `if(await page.locator('.some-class').count() > 0){ // DO SOMETHING }` but it always goes straight down to the else branch. Am I forgetting something? Afaik count returns a number and if its bigger than 0 then it should do something.
Is there a special function for this in Playwright that I just haven't seen?

**Comment by pavelfeldman** [comment]
When you are asking for the count, the element is not there yet, so you get into else. Wait for some other element that you know should be on the screen when conditional .some-class should be checked.

**Comment by jameskip** [comment]
Would `isVisible()` be better for this?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
