### ISSUE TITLE
[BUG] Unable to upload images as Playwright returns "selector resolved to hidden <input type="file" id="license" " even when the selector is not hidden

### ISSUE THREAD

**Issue by saransh88** [microsoft/playwright#18026]
**Context:**
- Playwright Version: Version 1.26.1
- Operating System: Mac (Monterey)
- Node.js version: 16.16
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

I have tried all the approaches mentioned [here](https://playwright.dev/docs/input#upload-files) but none see to work 

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
      await this.page.locator('div[class*="SingleFileSelector"] input').nth(1)
     .setInputFiles(imageLocation);
       
 
```
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.

We have a component called `CompanyLinks` that has file uploads, `CompanyLinks` has a `SingleAttachmentUploader` component which contains `SingleFileSelector` which is used to upload files. 

The code snippet for the same 

  ```<div className={styles.singleFileSelector}>
      {tooltipComponent
        ? React.cloneElement(
          tooltipComponent,
          { ...tooltipComponent.props },
          uploadButtonComponent,
        )
        : uploadButtonComponent}
      <input
        type="file"
        ref={fileInput}
        accept={accept}
        onChange={e => {
          onFilesSelect(e.target.files);
          fileInput.current.value = '';
        }}
        className={styles.fileInput}
      />
    </div>
```

**Describe the bug**

Add any other details about the problem here.

I receive selector `resolved to hidden <input type="file" id="license" class="SingleFileSelect…/> even when the selector/component does not have any hidden property`

**details about the components**

We have a component called `CompanyLinks` that has file uploads, `CompanyLinks` has a `SingleAttachmentUploader` component which contains `SingleFileSelector` which is used to upload files.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
