### ISSUE TITLE
[Question] Where is the playwright executable inside the docker image?

### ISSUE THREAD

**Issue by ppshobi** [microsoft/playwright#18025]
I am using [this](https://playwright.dev/docs/docker) link to setup a playwright docker instance. I get logged into the container with this command  
`docker run --rm -it  mcr.microsoft.com/playwright:v1.24.0-focal /bin/bash`
and I can see the `ms-playwright` directory and browsers. but where is the playwright executable?

when I try to run playwright using `npx` the following message comes

```
root@ea0956d273c2:/sbin# npx playwright test
Need to install the following packages:
  playwright
Ok to proceed? (y)
```

isn't it the point that a playwright docker image contains a playwright executable?

**Comment by pavelfeldman** [comment]
Only browsers and their dependencies are pre-installed. We assume you have a package depends on playwright, so you get it installed by the npm means.

**Comment by ppshobi** [comment]
https://playwright.dev/docs/docker
> It is recommended to always pin your Docker image to a specific version if possible. If the Playwright version in your Docker image does not match the version in your project/tests, Playwright will be unable to locate browser executables.

so it means that somehow a docker image is pinned with a playwright version. So I don't know if its ideal to expect the user to install things separately

**Comment by yury-s** [comment]
> so it means that somehow a docker image is pinned with a playwright version.

Yes, docker image comes with preinstalled browsers for a particular playwright version. If the version doesn't match playwright can still download them, it is just less efficient.

> So I don't know if its ideal to expect the user to install things separately

We don't bake playwright executable itself into the image as it's tiny compared to the browser binaries and your project would normally pull it anyway. With that said, if you need playwright to be preinstalled globally you can always build a derived image.

**Comment by MaximeBernard** [comment]
Thank you for the clarification. I have to admit this is counter-intuitive and you may want to add a comment about it in the documentation ([above `npm ci` for example](https://playwright.dev/docs/ci#github-actions-via-containers)).

To have some insight into our use case:
- we're using a monorepo (npm workspaces)
- our `npm ci` takes quite some time (1min30)
- we don't have a specific CI job to run E2E 

So we were trying a different approach.
