### ISSUE TITLE
[Question]puppeter has target,but playwright does not

### ISSUE THREAD

**Issue by FishBlanche** [microsoft/playwright#18021]
puppeter's browser has target and targets,but why playwright does not have?
export interface Browser extends EventEmitter, TargetAwaiter {
    
    /** A target associated with the browser. */
    target(): Target;

    /** Promise which resolves to an array of all active targets. */
    targets(): Promise<Target[]>;
}

**Comment by pavelfeldman** [comment]
Because we don't see the need for them, are you looking for a specific feature?

**Comment by FishBlanche** [comment]
> 

We have a function(based on puppeteer) in which try to find a page  in target whose type is webview.
Part of the function is as following:

 const targets = await this.browserDriver.browser.targets();
      const target = targets.find((t) => {
        if (<any>t.type() === 'webview' && t.url().indexOf(url) > -1) {
          return t;
        }
      });
      if (target) {
        page = await target.page();
      }

**Comment by yury-s** [comment]
Can tell us what you are trying to automate in terms of what kind of app is that and how it uses webviews? Playwright has means for automating [android web view](https://playwright.dev/docs/api/class-androidwebview), [Electron](https://playwright.dev/docs/api/class-electronapplication), [WebView2](https://playwright.dev/docs/webview2) etc. Without knowing more about what you are trying to achieve it's hard to tell whether one of those will work for you.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
