### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ahmwai** [microsoft/playwright#18030]
**Context:**
- Playwright Version: [1.25.0]
- Operating System: [Windows]
- .NET version: [e.g. .NET 6]
- Browser: [Chromium]

Hello team,

We have an issue, when we are using,  await browser.AddInitScriptAsync( "js_code"), to inject some JS code before document creation.

So if we run Chromium, and use the debugger to debug the web URL, the debugger shows our AddInitScriptAsync inject code under debugger:///VM, any idea how we can stop the debugger from debugging the inject js code?

Also even if the browser through some errors or warnings its showing in the console with the debugger:///VM, link which will show the injected code in the debugger window tool.

Kindly advise about the same.

Thank you

**Comment by pavelfeldman** [comment]
Chrome will debug any JavaScript code that is running within the VM. debugger:// url only means that there is no friendly source file name for that script. You can't tell debugger to not debug JS code in Chrome!
