### ISSUE TITLE
Vendor support

### ISSUE THREAD

**Issue by vanajasukumar** [microsoft/playwright#18031]
Hi Team, 
In my current company we are trying to migrate from protractor to playwright.  I am checking to see if we can get any vendor support on Playright. 

Looking forward for your reply.

Regards
Vanaja

**Comment by pavelfeldman** [comment]
What do you mean by 'vendor support'?

**Comment by pavelfeldman** [comment]
No, we don't provide corporate support at this time. Playwright lives by the open source rules, you can file bugs and feature requests and we'll be prioritizing them.
