### ISSUE TITLE
[Question] How to show name and metadata in HTML report

### ISSUE THREAD

**Issue by dskochubey** [microsoft/playwright#18038]
There are two options in configuration file:

- metadata - Metadata that will be put directly to the test report serialized as JSON.
- name - Config name is visible in the report and during test execution, unless overridden by testProject.name

I set values to those fields, but they are not shown during execution and in the HTML report. 

How can I see those values during execution and in the HTML report?

**Comment by yury-s** [comment]
These fields are not currently rendered anywhere. There was some work on displaying metadata in html report but we decided not to proceed with that for now. It will be added to the docs and announced if we decide to surface it in the html report.

`PlaywrightTestConfig.name` is not actually used anywhere and it's just a side effect of PlaywrightTestConfig extending TestConfig type.

**Comment by sKopheK** [comment]
can you update documentation then please?

"Metadata contains key-value pairs to be included in the report. For example, **HTML report will display it as key-value pairs**, and JSON report will include metadata serialized as json."
