### ISSUE TITLE
[BUG] browserType.connect(): Playwright version 1.27.0 not supported

### ISSUE THREAD

**Issue by dskochubey** [microsoft/playwright#18034]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Mac
- Node.js version: 16.6
- Browser: remote browser with LambdaTest
- Extra: n/a

**Code Snippet**

```javascript
const { chromium } = require('playwright');
const { expect } = require('@playwright/test');

(async () => {
  const capabilities = {
    'browserName': 'Chrome', // Browsers allowed: `Chrome`, `MicrosoftEdge`, `pw-chromium`, `pw-firefox` and `pw-webkit`
    'browserVersion': 'latest',
    'LT:Options': {
      'platform': 'Windows 10',
      'build': 'Playwright Sample Build',
      'name': 'Playwright Sample Test',
      'user': process.env.LT_USERNAME,
      'accessKey': process.env.LT_ACCESS_KEY,
      'network': true,
      'video': true,
      'console': true,
      'tunnel': false, // Add tunnel configuration if testing locally hosted webpage
      'tunnelName': '', // Optional
      'geoLocation': '', // country code can be fetched from https://www.lambdatest.com/capabilities-generator/
    }
  }

  const browser = await chromium.connect(`wss://cdp.lambdatest.com/playwright?capabilities=${encodeURIComponent(JSON.stringify(capabilities))}`);

  const page = await browser.newPage();

  await page.goto('https://www.bing.com');

  const element = await page.$('[aria-label="Enter your search term"]');
  await element.click();
  await element.type('LambdaTest');
  await element.press('Enter');
  const title = await page.title();

  try {
    expect(title).toEqual('LambdaTest - Search');
    // Mark the test as completed or failed
    await page.evaluate(_ => {}, `lambdatest_action: ${JSON.stringify({ action: 'setTestStatus', arguments: { status: 'passed', remark: 'Title matched' } })}`);
  } catch {
    await page.evaluate(_ => {}, `lambdatest_action: ${JSON.stringify({ action: 'setTestStatus', arguments: { status: 'failed', remark: 'Title not matched' } })}`);
  }
  await browser.close();
})()
```

**Describe the bug**

I use the Playwright method [browserType.connect(wsEndpoint[, options])](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) with wsEndpoing provided by LambdaTest. When running a test, Playwright throws the error: `browserType.connect: Playwright version 1.27.0 not supported. Supported versions are 1.19.0 to 1.24.2.`
Official documentation and VS Code extension don't say anything that that function doesn't support or what is the new method to connect to a remote browser

**Comment by mxschmitt** [comment]
LambdaTest is not affiliated with Playwright, I recommend reaching out to their support instead!

**Comment by dskochubey** [comment]
@mxschmitt I don't think the issue I reported. The issue with Playwirght [browserType.connect(wsEndpoint[, options])](https://playwright.dev/docs/api/class-browsertype#browser-type-connect). The Playwirght throws the error: `browserType.connect: Playwright version 1.27.0 not supported. Supported versions are 1.19.0 to 1.24.2.`. This is not related to the LambtaTest.

**Comment by dskochubey** [comment]
Here screenshot of the error
<img width="984" alt="image" src="https://user-images.githubusercontent.com/37943734/195468081-4f740455-1e29-4a92-be93-e7046fae3226.png">

**Comment by dskochubey** [comment]
Or you are saying that that error message throws LambaTest and Playwright just shows it?

**Comment by zac11** [comment]
This seems like an error from LambdaTest
