### ISSUE TITLE
[BUG] Exception when using `LaunchPersistentContextAsync`

### ISSUE THREAD

**Issue by dracan** [microsoft/playwright#18046]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Windows
- Node.js version: n/a (using .NET)
- Browser: Chromium
- Extra: [any specific details about your environment]

I've created a simple repro case here:
https://github.com/dracan/PlaywrightBugRepro

I'm trying to use Playwright against my main Chrome profile/browser with the `LaunchPersistentContextAsync` method, but it just throws an exception...

![image](https://user-images.githubusercontent.com/567988/195525971-1ffb11bd-45fd-4a6d-8c78-3ceadb61617e.png)

The exception on that screenshot is thrown on line 2. Ignore that it's using LINQPad there - the same happens in a normal dotnet console app (see repro-case above).

Instructions followed from the docs [here](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-launch-persistent-context] to get that path.

**Comment by dracan** [comment]
I've just realised that this doesn't happen if I don't have my browser window already open. However, it's trashed my Chrome profile! I had to re-sync to get all my extensions back, and relogin to everything 🙁

**Comment by yury-s** [comment]
You cannot reuse same profile directory between two browser instances, Chrome will enforce use of the already running instance. Playwright cannot connect to already running browser like that, the is why you get an error. You should either first close all browsers before running playwright with that user-data-dir or use a separate profile directory. If you want to connect to existing browser you can try starting it with remote debugging enabled and then use [ConnectOverCDPAsync](https://playwright.dev/dotnet/docs/api/class-browsertype#browser-type-connect-over-cdp).

**Comment by dracan** [comment]
Thanks, that's useful to know about that Connect method.

Is it worth improving the exception message to be a bit more meaningful? And perhaps the documentation too. I can't be the only one to hit this, and currently, googling for and finding this GitHub issue is the only way of knowing the reason.
