### ISSUE TITLE
[Question] Detect if playwright reused an existing server.

### ISSUE THREAD

**Issue by ambiguous48** [microsoft/playwright#18041]
I'm looking for a way to detect if playwright used an existing server or if it started it's own.

For reasons that I've yet to discover, playwright does not properly kill all servers after all tests are done. For context, playwright is running in a monorepo with `pnpm` & `turborepo`. I've found that using `tree-kill` during `global teardown` does kill every server successfully. However, I want this to happen only when the servers were started by playwright and never else.

Example:

```mermaid
graph TD
    D[Global Teardown] --> A
    A[Check if playwright reused existing server - *How to do this?*] -->|server was started by playwright| B(Use tree-kill to clean up)
    A -->|playwright reused an existing server| C(don't do anything)
```

Is there a way to do this, whether with playwright or a normal bash shell on linux? Tried going through `ps`/`pstree`, but I can't seem to find a way to reliably check if a given `pid` was started by `playwright` or not.

**Comment by yury-s** [comment]
> I've found that using `tree-kill` during `global teardown` does kill every server successfully. However, I want this to happen only when the servers were started by playwright and never else.

Can you follow the process tree of the playwright process and kill only those server processes whose parent is playwright? From what I understand currently you call `tree-kill` on the root process of each of the running servers, is that the case?

**Comment by ambiguous48** [comment]
> follow the process tree of the playwright process and kill only those server processes whose parent is playwright

I'm not really sure how to do that. Here is an example to further illustrate the scenario:

Playwright started the servers successfully, completed the test, and exited. However, it failed to kill the servers it started on ports 3000 & 3002. Ideally, playwright should kill those process after the tests are done. I think this is bug.

Meanwhile though, I wouldn't mind writing the logic to kill those servers manually using `tree-kill` in `global-teardown`. The bit I'm having trouble with is: What is a reliable way to tell if those processes were started by playwright? This is important because for situations where I am writing tests and playwright is re-using the dev server, I don't want the `tree-kill` logic in global-teardown to run.

```ts
// global-teardown.ts

import type { FullConfig } from '@playwright/test';
import kill from 'tree-kill';

export default function globalTeardown(config: FullConfig) {
  const PORTS = config._webServers.map((ws) => ws.port);

  const pids = getProcessIds(PORTS);
  
  for (const pid of pids) {
    const wasStartedByPlaywright = /* What sort of logic could this be? */

    if (wasStartedByPlaywright) {
      kill(pid);
    } else {
      console.log(`Not killing process ${pid} because it was not started by Playwright. `);
    }
  }
}
```

Anyways here's a full example of a test run:

### Monorepo structure

3 packages, a website, a server, and a seperate package for e2e testing.

```
my-monorepo/
├─ packages/
│  ├─ site/
│  ├─ backend/
│  ├─ test/
│  │  ├─ playwright.config.ts
```

### Config

```ts
// playwright.config.ts
  webServer: [
    {
      cwd: '../../',
      command: 'pnpm turbo run preview --filter=@self/backend',
      port: 3002,
      reuseExistingServer: false,
      ignoreHTTPSErrors: true,
    },
    {
      cwd: '../../',
      command: 'pnpm turbo run preview --filter=@self/site',
      port: 3000,
      reuseExistingServer: false,
      ignoreHTTPSErrors: true,
    },
  ]
```

### Running the tests

```
▶ cd ~/my-monorepo/packages/test
▶ pnpm playwright test ./forms/combobox.spec.ts

Running 1 test using 1 worker

[Global Setup] Skipping login and using existing cookies
  ✓  1 [chromium] › forms/combobox.spec.ts:5:1 › can be searched (657ms)
globalTeardown


  1 passed (5s)

▶ 
```


### After tests are done

After tests are done, process still running and ports occupied.

```
▶ lsof -i :3002; lsof -i :3000
COMMAND     PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    1009415 myusername   22u  IPv6 5351407      0t0  TCP *:3002 (LISTEN)
COMMAND     PID  USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
node    1009560 myusername   19u  IPv6 5354859      0t0  TCP localhost:3000 (LISTEN)
```

```
▶ pstree -s -h -p -t -G -c -a --long 1009415
systemd,1 splash
  └─systemd,4336 --user
      └─pnpm,1009395 /home/myusername/.local/share/pnpm/pnpm run preview
          └─pnpm,1009401 run preview
              └─node,1009415 dist/src/main.js
                  ├─{futures-timer},1009480
                  ├─{node},1009416
                  ├─{node},1009417
                  ├─{node},1009418
                  ├─{node},1009419
                  ├─{node},1009420
                  ├─{node},1009421
                  ├─{node},1009437
                  ├─{node},1009438
                  ├─{node},1009439
                  ├─{node},1009440
                  ├─{opentelemetry-e},1009479
                  ├─{tokio-runtime-w},1009455
                  ├─{tokio-runtime-w},1009456
                  ├─{tokio-runtime-w},1009457
                  ├─{tokio-runtime-w},1009458
                  ├─{tokio-runtime-w},1009459
                  ├─{tokio-runtime-w},1009460
                  ├─{tokio-runtime-w},1009461
                  ├─{tokio-runtime-w},1009462
                  ├─{tokio-runtime-w},1009463
                  ├─{tokio-runtime-w},1009464
                  ├─{tokio-runtime-w},1009465
                  ├─{tokio-runtime-w},1009466
                  ├─{tokio-runtime-w},1009467
                  ├─{tokio-runtime-w},1009468
                  ├─{tokio-runtime-w},1009469
                  ├─{tokio-runtime-w},1009470
                  ├─{tokio-runtime-w},1009471
                  ├─{tokio-runtime-w},1009472
                  ├─{tokio-runtime-w},1009473
                  ├─{tokio-runtime-w},1009474
                  ├─{tokio-runtime-w},1009475
                  ├─{tokio-runtime-w},1009476
                  ├─{tokio-runtime-w},1009477
                  └─{tokio-runtime-w},1009478
```

```
▶ pstree -s -h -p -t -G -c -a --long 1009560
systemd,1 splash
  └─systemd,4336 --user
      └─pnpm,1009544 /home/myusername/.local/share/pnpm/pnpm run preview
          └─pnpm,1009550 run preview
              └─node,1009560 /home/myusername/projects/my-monorepo/packages/site/node_modules/.bin/../../../../node_modules/.pnpm/vite@3.1.7/node_modules/vite/bin/vite.js preview --port 3000
                  ├─esbuild,1009576 --service=0.15.10 --ping
                  │   ├─{esbuild},1009577
                  │   ├─{esbuild},1009578
                  │   ├─{esbuild},1009579
                  │   ├─{esbuild},1009580
                  │   ├─{esbuild},1009581
                  │   ├─{esbuild},1009582
                  │   └─{esbuild},1009583
                  ├─{node},1009566
                  ├─{node},1009567
                  ├─{node},1009568
                  ├─{node},1009569
                  ├─{node},1009570
                  ├─{node},1009571
                  ├─{node},1009572
                  ├─{node},1009573
                  ├─{node},1009574
                  └─{node},1009575
```

**Comment by yury-s** [comment]
> Playwright started the servers successfully, completed the test, and exited. However, it failed to kill the servers it started on ports 3000 & 3002. Ideally, playwright should kill those process after the tests are done. I think this is bug.

Playwright sends -SIGKILL signal to the web server process. It should be sufficient to terminate the entire process subtree. Normally this signal cannot be caught or ignored but your web server manages to survive it and keeps running after the playwright exited. You should check what happens with SIGKILL sent to your server process.

> What is a reliable way to tell if those processes were started by playwright? 

Before playwright exits you should be able to reach playwright process from the web server process by traversing its parent pid chain ( you can get parent pid of a process by executing `ps -o ppid -p <pid>` or use a node library to do that). Note that after playwright exits the webserver is automatically reparented to systemd (which is what you see in the output of `pstree`)

**Comment by ambiguous48** [comment]
> Note that after playwright exits the webserver is automatically reparented to systemd (which is what you see in the output of pstree)

I wasn't aware of that. Things make much more sense now. Thank you.

Fwiw, this seems to do the trick.

```ts
import { execSync } from 'node:child_process';

/**
 * Returns true if the process was started by playwright.
 */
export const wasProcessStartedByPlaywright = (pid: number): boolean => {
  // get parent tree
  const tree = execSync(`pstree -s -h -p -t -G -c -a --long ${pid}`)
    .toString()
    .trim();

  // check if any of the parents has a command that contains the string "playwright"
  const hasPlaywright = tree.includes('playwright');

  console.log(`Process ${pid} was started by Playwright: ${hasPlaywright}`);

  return hasPlaywright;
};
```

As for why the processes are not responding to the original SIGKILL, it _could_ be related to this `pnpm` issue but I'm not really sure. https://github.com/pnpm/pnpm/issues/2653
