### ISSUE TITLE
No video is added to report on page shared with multiple tests

### ISSUE THREAD

**Issue by Shanmuktej** [microsoft/playwright#18047]
When a page is shared to multiple tests as described in the below snippet, the video is not being added to the report.

```js
test.describe("Demo", async () => {

    let page: Page;
    test.beforeAll(async ({ browser }) => {
        page = await browser.newPage()
    })
    test("google", async () => {
        await page.goto("www.google.com")
    })
    test("bing", async () => {
        await page.goto("www.bing.com")
    })

})
```

![image](https://user-images.githubusercontent.com/62170837/195526862-da4320b0-4068-474b-b1ad-5e1db0a47422.png)

**Comment by yury-s** [comment]
This is currently not supported. As a workaround, you can manually record it and attach to the report like this:

```js
test.describe("Demo", async () => {
  let page: Page;
  test.beforeAll(async ({ browser }, testInfo) => {
      page = await browser.newPage({
        recordVideo: {
          dir: testInfo.outputPath('video.webm')
        }
      })
  })
  test.afterAll(async ({}, testInfo) => {
    const savedPath = testInfo.outputPath(`video.webm`);
    await page.close();
    const path = await page.video()!.path();    
    testInfo.attachments.push({ name: 'video', path, contentType: 'video/webm' });
  })
  test("google", async () => {
      await page.goto("https://www.google.com")
  })
  test("bing", async () => {
      await page.goto("https://www.bing.com")
  })

})
```

**Comment by Shanmuktej** [comment]
Thanks @yury-s for the workaround, but in this approach the video will be attached to the failed test only.
If the tests - Google & Bing & Yahoo are run, the video of combined feature will be added to the Bing Test if it failed.
![image](https://user-images.githubusercontent.com/62170837/196191567-dcbddc36-855f-4d1c-b326-10a8afa62219.png)
But the traces and screenshots are working as expected by attaching to the tests where they're recorded only.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by ranjit-1905** [comment]
const path = await page.video()!.path();   
Error: Path is not available when connecting remotely. Use saveAs() to save a local copy.

**Comment by ranjit-1905** [comment]
Thanks Code ,When are get error on Path() .Use this code...
test.afterAll(async ({},testInfo) => {
    const savedPath = testInfo.outputPath(`video.webm`);
    await page.close();
    const path = await page.video().saveAs(testInfo.outputPath('video.webm')); 
    testInfo.attachments.push({ name: 'video', path: savedPath, contentType: 'video/webm' });      
    
});

Get on Path() error. Use this code...
