### ISSUE TITLE
[Question] Handling new tabs with Page object model 

### ISSUE THREAD

**Issue by sh0tal** [microsoft/playwright#18056]
Hello guys, 

I want to know how  to handle a tab or multiple tabs when using Page object model.

My test runs successfully if i don't use the page object model function to run it.
Basically when i click and navigate to the new tab i am using this on the normal test without the POM:

const [newPage] = await  Promise.all([
page.waitForEvent('popup'),
page.locator(button...).click();
]);

and then using the newPage as my new tab and it's working.

await newPage.locator(field).fill(testing);
...SNIP..

When using the POM I cant do that and I am not able to continue with the rest of the test, it doesnt recognise the new tab as i cant declare the new page in the POM. 

Can someone point me in the right direction ? 

How can i implement the same logic using the POM ?
Thanks

**Comment by oscargforce** [comment]
You have the create a new instance of
the page object.

for example:
const homePage = new HomePage(newPage)

You are have to pass in the newPage as an argument to the constructor of the class.

const [newPage] = await Promise.all([
page.waitForEvent('popup'),
page.locator(button...).click();
]);

**Comment by sh0tal** [comment]
Hello, 
can you please explain more?
 since I didn't quite understand your solution since  adding an argument to the constructor it results to error, newpage is not a constructor.

**Comment by yury-s** [comment]
@sh0tal you need to find a way to create a new POM with newPage (`const homePage = new HomePage(newPage)` above). How do you create first instance of the POM page? Please share your code so that we can help you.

**Comment by sh0tal** [comment]
@yury-s let me share my code then.

One note here is that i managed to find a workaround by not declaring the locators in the constructor, i just declared the new page inside the function and continue with the newPage instead of page from there.  But i would like to see how i can implement it using the locators in the constructor.

Initial page object model: (its a snip code), the problem is on the paywallTopUpCC function where upon clicking on the button it redirects to a different page to add your payment details.

```
exports.general = class general {

    constructor(page) {
        this.page = page;
        this.registerButtonHomePage = page.locator('header button:has-text("Register")');
        this.username = page.locator('[placeholder="Username"]');
        this.password = page.locator('[placeholder="Password"]');
        this.email = page.locator('[placeholder="Email"]');
        this.registerButtonModal = page.locator('div[role="dialog"] button:has-text("REGISTER")');
        this.creditCardButtonPaywall = page.locator('button:has-text("Creditcard")');
        this.secondChoiceTopUp = page.locator('button:has-text("click here")');
        this.getCreditsButton= page.locator('button:has-text("test")');
        this.creditCardNumber = page.locator('input[name="cc_num"]');
        this.creditCardDate =page.locator('input[name="cc_exp"]'); 

SNIP....
 }

 async baseUrl(){

        await this.page.goto('https://example.com')


      }
 async registration(){
        ...SNIP...
          this.registerButtonModal.click() //click register button
        ]);

      }

  async paywallTopUpCC(){
        await this.creditCardButtonPaywall.nth(1).click();
        await this.secondChoiceTopUp.click();
      const [newPage] = await Promise.all([
         this.page.waitForEvent('popup'),
       this.getCreditsButton.click()
         ]);
//FROM HERE -> A second tab is opening upon clicking on the getCreditsButton, the rest of the steps are not getting processed since its a new tab

        await this.creditCardNumber.fill('xxxx');
        await this.creditCardDate.fill('02/55');
        await this.creditCardCvv.fill('256');
       ....SNIP....
```

If I change the paywallTopUpCC function to not use the locators declared in the constructor it works:


```
 async paywallTopUpCC(){
        await this.creditCardButtonPaywall.nth(1).click();
        await this.secondChoiceTopUp.click();
        const [newPage] = await Promise.all([
          this.page.waitForEvent('popup'),
          this.getCreditsButton.click()     
           ]);
      
      await newPage.locator('input[name="cc_num"]').fill('xxxx'); 
      await newPage.locator('input[name="cc_exp"]').fill('02/55'); 
      await newPage.locator('input[name="cc_cvv"]').fill('256'); 
 ...SNIP...     
     }
}
```
test.spec.js 

```
test.only('new login test', async ({page}) => {  
   
    const pageObject = new general(page)
    await pageObject.baseUrl();
    ...SNIP...
    await pageObject.paywallTopUpCC();
  })

```

**Comment by yury-s** [comment]
Changing the code like this should also work (this is roughly what I meant by creating POM for the new page):

Split paywallTopUpCC into two parts and make it return POM for the popup page:
```ts
exports.general = class general {

    constructor(page) {
        this.page = page;
        this.registerButtonHomePage = page.locator('header button:has-text("Register")');
        this.username = page.locator('[placeholder="Username"]');
        this.password = page.locator('[placeholder="Password"]');
        this.email = page.locator('[placeholder="Email"]');
        this.registerButtonModal = page.locator('div[role="dialog"] button:has-text("REGISTER")');
        this.creditCardButtonPaywall = page.locator('button:has-text("Creditcard")');
        this.secondChoiceTopUp = page.locator('button:has-text("click here")');
        this.getCreditsButton= page.locator('button:has-text("test")');
        this.creditCardNumber = page.locator('input[name="cc_num"]');
        this.creditCardDate =page.locator('input[name="cc_exp"]'); 

SNIP....
 }

  async paywallTopUpCC(){
        await this.creditCardButtonPaywall.nth(1).click();
        await this.secondChoiceTopUp.click();
      const [newPage] = await Promise.all([
         this.page.waitForEvent('popup'),
       this.getCreditsButton.click()
         ]);
       // Return POM for the new tab
       return new general(newPage);
   }

   async fillOutCreditCardData() {
        await this.creditCardNumber.fill('xxxx');
        await this.creditCardDate.fill('02/55');
        await this.creditCardCvv.fill('256');
       ....SNIP....
   }
```

Then in the test call fillOutCreditCardData on the popup's POM:
```ts
test.only('new login test', async ({page}) => {  
   
    const pageObject = new general(page)
    await pageObject.baseUrl();
    ...SNIP...
    const popupObject = await pageObject.paywallTopUpCC();
    awai popupObject.fillOutCreditCardData();
  })
}
```

**Comment by mike2339** [comment]
Can you tell more info about this popupobjectfillcreditcarddata

**Comment by sh0tal** [comment]
@mike2339 
I described it in more detail above.

**Comment by sh0tal** [comment]
@yury-s @mike2339 
Now It seems to be working like a charm, maybe I did a mistake implementing it. Nonetheless thank you for the help :)

**Comment by hassanht** [comment]
Hi, i am facing the same issue i have a test class which is totally doing nothing other than calling functions from page class.For creating page object i am using playwright advance fixture and than call that page object in my test function. Can you suggest me how to handle second tab in this case

**Comment by ldelregueromartinez** [comment]
hi!
How could you solve it? I'm starting Playwright and I'm having the same problem.

Use POM, Fixture and test

thank you!
