### ISSUE TITLE
[BUG] Mocking does not work when run in headless mode

### ISSUE THREAD

**Issue by dolkons** [microsoft/playwright#18054]
**Context:**
- Playwright Version: 1.25.1
- Operating System: MacOS Monterey 12.6
- Node.js version: v18.7.0
- Browser: Chromium

**Code Snippet**

```javascript
await page.clickOnCopyIdButton();
await expect(page.snackbar).toHaveText(`ID скопирован`);
```

**Describe the bug**
Hi Everyone! I have a simple test that opens a page, click on "copy" button that copies an ID to the clipboard and validates the snackbar message.
To open the page I mock the response and work with the fake page.

The problem is: If I run a test in **headed** mode everything works fine: fake page is opened, test click on a button and then validates the snackbar text. But if I run the same test in the **headLESS** mode it fails to check the **expect()** condition.
I tried to run the test with the **trace on** option and noticed quite strange behaviour. Here is the example of test execution in **headed mode** (when everything works fine):
<img width="326" alt="image" src="https://user-images.githubusercontent.com/22120969/195566288-cb1a0bba-9d7d-4a75-bd21-49f8486a7b51.png">

**Q1:** The first thing I don't understand, why is there a **route.fulfill** call between the click and expect actions while in my code I setup the route.fulfill before running the test? 

Okay, now this is the trace for the test execution in **headLESS** mode (in this case browser is not opened and I don't see what is going on in the real-time):

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/22120969/195566940-9c0e03e2-34c0-4ba3-a1fc-efb7504b675f.png">

**Q2:** as you can see from the screenshot above, the **route.fulfill** call fails for me with some strange error in the console:
> Write permission denied.

What does it mean? Why that happens?

**Comment by yury-s** [comment]
Please share the code that is failing so that we can help you.

> Q1: The first thing I don't understand, why is there a route.fulfill call between the click and expect actions while in my code I setup the route.fulfill before running the test?

I guess you by setup you mean `page.route`, it's callback is executed asynchronously when a request is intercepted it may well happen later between click and expect.

> Q2: as you can see from the screenshot above, the route.fulfill call fails for me with some strange error in the console:

It's hard to tell what the error is about without seeing the code.

**Comment by dolkons** [comment]
Sure, I'll try to get a full code example and will get back to you

**Comment by dgozman** [comment]
@dolkons Any chance for a repro?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
