### ISSUE TITLE
[Question] Store JSON report as an gitlab artifact

### ISSUE THREAD

**Issue by oscargforce** [microsoft/playwright#18065]
Hello!

First, I have to say that I love playwright, amazing work guys, it is being used to automate some of Swedens digital healthcare 💪 

Secondly, I need some help on how to store the JSON reporter as an artefact in Gitlab CI. Does anyone have any ideas? I tried adding variables, like the HTML report in the picture below.

` reporter: [['json', { outputFile: './json_reporter/test-results.json' }], ['html']],`
![image](https://user-images.githubusercontent.com/102926658/195640801-6abe79bf-e9e7-4934-8ce6-dee4232b19e2.png)

**Comment by yury-s** [comment]
Please refer to Gitlab documentation and examples. The report is just an json file so regular artifact upload mechanisms should work. We have [an example](https://playwright.dev/docs/ci#github-actions) for html report upload to GitHub Actions. You config looks fine, perhaps just the path is wrong, make sure that the report you want to upload is actually written to `visual-tests-report` dir. You can specify the output folder in the [reporter config](https://playwright.dev/docs/test-reporters#html-reporter).
