### ISSUE TITLE
[Question] Is There a way to inject or modify cookies and header on page (without initiating browserContext in test level)

### ISSUE THREAD

**Issue by rio-ap** [microsoft/playwright#18068]
Hi as question above, 

first question : is there a way to inject cookies / modify the cookies with test page without creating new context?

```
test('inject_cookies', async ({ page }) => {
//test code
})
```

also is there an easy ways to modify existing cookies with new value without clear all the cookies and adding again using browserContext?

our usage is to inject cookies already login cookies into test, so there is no login every time the test happen. using storage state also is not usable in our case, as our test cases/suite have different use case (have login as precondition, and not login in some of the test) as in my understanding saving storageState.json in config will override the login state for all test in the repo.

or to be more precise can we add new capabilites to use test.use(storage state) in test level (not testsuite level/test.describe)

second question : related to header (page.setExtraHTTPHeaders). is there a ways to remove this header after we set in in first request

```
test('inject_cookies', async ({ page }) => {
  const appURL = "https://google.com"
  await page.setExtraHTTPHeaders({"testing" : "testing 1"})
  await page.goto(appURL);
  
  //remove testing header?
})
```

**Comment by yury-s** [comment]
> first question : is there a way to inject cookies / modify the cookies with test page without creating new context?

You can call [context.addCookies](https://playwright.dev/docs/api/class-browsercontext#browser-context-add-cookies) to add new cookies:
```js
test('inject_cookies', async ({ page, context }) => {
  await context.addCookies([...]);
  //test code
})
```
To remove cookies you can do something like this:
```js
test("remove cookie", async ({page, context}) => {
  const cookies = await context.cookies();
  await context.clearCookies();
  await context.addCookies(cookies.filter(c => c.name !== 'foo'));
  // test code
});
```

> also is there an easy ways to modify existing cookies with new value without clear all the cookies and adding again using browserContext?

No. Is there a reason why clearing and setting them back doesn't work for you?

You can also modify individual request headers using [route.continue](https://playwright.dev/docs/api/class-route#route-continue). But if you only care about cookies then changing them on the context may be easier.

> our usage is to inject cookies already login cookies into test, so there is no login every time the test happen. using storage state also is not usable in our case, as our test cases/suite have different use case (have login as precondition, and not login in some of the test) as in my understanding saving storageState.json in config will override the login state for all test in the repo.

You can use separate storageState.json per test file:

```js
// user.spec.ts
import { test, expect } from '@playwright/test';

test.use({
  storageState: 'signedInUser.json'
});

test('test 1', async({ page }) => {
});

// admin.spec.ts
import { test, expect } from '@playwright/test';

test.use({
  storageState: 'signedInAdmin.json'
});

test('test 1', async({ page }) => {
});
```
Would this work for you?

> second question : related to header (page.setExtraHTTPHeaders). is there a ways to remove this header after we set in in first request

There is no way to remove such headers from the page but you can intercept requests and modify its headers using [route.continue](https://playwright.dev/docs/api/class-route#route-continue).

**Comment by rio-ap** [comment]
hi @yury-s thank you for clarifying context.addcookie it seem i missed that when skimming the doc. the inject cookies problem already solve with that.

now for change specific cookies, because we want to add several cookies (with custom key and custom value) as flag to route our connection (and get data from our mock server). with your implementation it work for one custom key cookies. but if we have several cookies, we need to save initial cookies without custom one, then re add one by one manually with new value (just discover the cookies.filter function from your answer). 

for storage state, is there any plan to enabled it in test case level instead of test suite collection (test file)/ testsuite (test.describe) level? just asking as for now our test framework designed to have only 1 test file per product/service. if there is no plan testsuite level actually fine by us. it just nice to have for to be enabled in test level

i see, so there is no function to remove that extrahttpheader we set. i think it will be better if there also function like removeExtraHttpHeader

**Comment by yury-s** [comment]
> for storage state, is there any plan to enabled it in test case level instead of test suite collection (test file)/ testsuite (test.describe) level? just asking as for now our test framework designed to have only 1 test file per product/service. if there is no plan, testsuite level actually fine by us. it just nice to have for to be enabled in test level

There are not plans for that.

> for header question, so there is no function to remove that extrahttpheader we set. i think it will be better if there also function like removeExtraHttpHeader. 

To cleanup extra headers we recommend creating a new page instead. For more fine grained control we recommend request interception with route.

> as route continue cant be used in my case (i already try create custom function for this)

Use `delete` to avoid the error:
```js
async removeCustomHeader(headerKey:string){
      await this.page.route('**/*', (route, request) => {
        // Override headers
        const headers = { ...request.headers() };
        delete headers[headerKey];
        route.continue({headers});
      });
    }
```
