### ISSUE TITLE
[BUG] - Error: page.exposeFunction: Target closed

### ISSUE THREAD

**Issue by gonzaloavilasalgueiro** [microsoft/playwright#18067]
**Context**
- Playwright Version: 1.27
- Operating System: MAC
- Node.js version: 16.13
- Browser: Chrome 105.0.5195.125

**Description**

When trying to expose functions using:

```javascript
await page.exposeFunction(functionName, callback);
```

It works most of the time, but for some pages I get the following error: 

`Error: page.exposeFunction: Target closed`

While debugging I found out that the error is thrown at `playwright-core/src/server/chromium/crPage.ts`, in method `_forAllFrameSessions` of the `CRPage` class, while trying to call `_initBinding` on non-main frames:  

```javascript
async _forAllFrameSessions(cb) {
    const frameSessions = Array.from(this._sessions.values());
    await Promise.all(frameSessions.map(frameSession => {
      if (frameSession._isMainFrame()) return cb(frameSession);
      return cb(frameSession).catch(e => {
        // Broadcasting a message to the closed iframe shoule be a noop.
        if (e.message && (e.message.includes('Target closed.') || e.message.includes('Session closed.'))) return;
        throw e;
      });
    }));
  }
```
If I understand correctly there's an intention to ignore these errors since they might be expected, but it skips the conditional due to an extra dot causing the error string to not match. 

![image](https://user-images.githubusercontent.com/91805634/195660106-283bbfd1-1075-4d30-aa61-566c73ff5e2d.png)
 
```
error.message -> "Target closed" 
condition -> "Target closed."
```

It seems removing the dot works but maybe I am missing something.

Thanks in advance!

**Comment by yury-s** [comment]
Can you share an example where the error happens?

**Comment by gonzaloavilasalgueiro** [comment]
It depends on the page's behavior so it can't be reproduced on every website or execution, but this would be the use case.  

```javascript
const {chromium} = require("playwright");

async function test(){
    const browserContext = await chromium.launchPersistentContext("browser-data", {
        headless: false,
    });

    const page = browserContext.pages()[0];

    const onLoad = (page) => {
        page.exposeFunction("dummyFunction", () => {
            console.log("Dummy function called")
        })
    };

    page.on("load", onLoad);
    page.goto(<page_url>);
}

test()
```
