### ISSUE TITLE
[BUG] npx playwright test doesn't like backward slash \ in test file path

### ISSUE THREAD

**Issue by toannguyen83** [microsoft/playwright#18072]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Node.js version:v16.18.0
- Browser:  Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
```
npx playwright test nested-folder\test-file.spec.ts
```

**Describe the bug**
In the past I'm able to perform npx playwright test and able to use the backslash \ as a path separator and it's able to find and run the test. As of recent version it's no longer working.

The workaround now is to use the forward slash / instead. 

My use case is if i need to run specific test file, in vscode (windows), i right click on the file and select "Copy Relative Path" and paste it into CLI and able to run the test. 

Example code
[playwright-issue-relative-path.zip](https://github.com/microsoft/playwright/files/9780059/playwright-issue-relative-path.zip)

**Comment by yury-s** [comment]
There was a [fix](https://github.com/microsoft/playwright/pull/11763/files) for this which was reverted in [this PR](https://github.com/microsoft/playwright/pull/12004). @pavelfeldman do you remember the deails?

**Comment by yury-s** [comment]
This might have worked without escaping a while ago (a year or so) but that was a just a side effect of another bug. You currently have to escape the backslash `\\` to make it work on win. Closing this issue as there are no plans on changing this.

**Comment by toannguyen83** [comment]
I see thanks @yury-s  @pavelfeldman . The problem is the workaround to add escape backslash won't work with my current workflow since in VS Code, when right click on a file and select "Copy Path" or "Copy Relative Path", it will not include the escape backlash. It will be a chore to correct all the backlash with the escape character. Here's my reason for running test this particular way:
- guarantee to run set of test(s) in this specific file
- provide by just file name only can have collisions and run other tests having similar file names

To me it's clearly an inconsistent issue for Windows user since I can perform the exact same workflow on a Mac and will not have the problem, since Mac is using forward slash when Copy Relative Path in VS Code. I hope this issue can be re-considered to be looked at in the future. 

I suppose the workaround I can find is from this PR https://github.com/microsoft/vscode/issues/56279  that in VS Code, I might be able to use the setting `explorer.copyRelativePathSeparator` and specify a specific separator when copy relative path or using an extension, in this case I'm pretty much just fighting against the system and use forward slash on Windows. At least I can leave this workaround here for others to see since this issue not likely to be looked at.

**Comment by JontyMC** [comment]
Please reopen this, been looking at this issue for a while. In our team, using ${relativeFile} in launch.json for vscode works for me but no-one else, not sure why this is. Our launch.json looks like this:

```json
{
  "name": "This test",
  "request": "launch",
  "runtimeArgs": ["playwright", "test", "${relativeFile}"],
  "runtimeExecutable": "npx",
  "skipFiles": ["<node_internals>/**"],
  "type": "node",
  "outputCapture": "std"
}
```

Which runs the command:

`C:\Program Files\nodejs\npx.cmd playwright test path\to\test`

This works on my machine, but not others.

**Comment by JontyMC** [comment]
I found out why it was working on my machine. I had node 16.14.0 installed. When I updated to 16.18 I got `no tests found` as others were seeing on the team.

**Comment by JontyMC** [comment]
Workaround, use [Command Variable](https://marketplace.visualstudio.com/items?itemName=rioj7.command-variable) vscode extension and use `"${command:extension.commandvariable.file.relativeFilePosix}"`

**Comment by unickq** [comment]
for me workaround on win was vscode option
`Explorer: Copy Relative Path Separator` 

![image](https://user-images.githubusercontent.com/6696821/207349579-c8e3cc1a-244b-4e74-9ddd-c03d778df5b2.png)

**Comment by bingtimren** [comment]
My workaround, if not using any extension, is to create a javascript launcher.

```
const exec = require('child_process').exec;
const path = process.argv[2].replace(/\\/g, '/');
const cli = `npx playwright test --headed ${path}`;
console.log("Running: ", cli);
exec(cli, 
    (error, stdout, stderr)=>{ 
        if (stdout) console.log(stdout);
        if (stderr) console.error(stderr);
        if (error)
        console.log('Execution finished with error')
    })
```
Put it somewhere, e.g. "framework/launcher.js", then this is my launch.json

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "<FILE>",
      "skipFiles": ["<node_internals>/**"],
      "program": "${relativeFile}",
      "runtimeExecutable": "node",
      "runtimeArgs": ["framework/launcher.js"]
    },
    {
      "type": "node",
      "request": "launch",
      "name": "<LINE>",
      "skipFiles": ["<node_internals>/**"],
      "program": "${relativeFile}:${lineNumber}",
      "runtimeExecutable": "node",
      "runtimeArgs": ["framework/launcher.js"]
    }
  ]
}

```

See screenshot below. The launch just replaces backslash with forward slash

![image](https://github.com/microsoft/playwright/assets/2824513/033eb8f6-d29b-475a-8aa2-8e719d7f5253)
![image](https://github.com/microsoft/playwright/assets/2824513/5b394b0e-2932-4cec-a00b-8c8e1b846d81)
