### ISSUE TITLE
[Feature] Show JSON intuitively in trace-viewer and make easily copyable/expandable

### ISSUE THREAD

**Issue by ryaudio** [microsoft/playwright#18075]
Playwright 1.25.2
Node v12.18.2

The trace-viewer does not show JSON responses, which makes it difficult to debug what went wrong during API testing.  

Please let me know if I am missing something or there is a way to trace JSON responses.

## List of requests:

Make JSON-like bodies are expandable/copyable, i.e. #9372

### Under `apiRequestContext.get`, tab "Call":

1. Make PARAMETERS > `params` expandable/copyable, and maybe as a simple JSON rather than the "name", "value" keys.

What it is now:

<img width="659" alt="Screen Shot 2022-10-13 at 2 57 48 PM" src="https://user-images.githubusercontent.com/60672162/195709108-819c40a9-b870-4873-8c5b-bd2322b5fd86.png">

Desired:
(expandable/copyable)
```
params: { "token": "7446-5d67etcetcetc", "s": "the value for s"}
```

2. Make RETURN VALUE > response expandable/copyable, and include the actual response body rather than just the headers/basic info

What it is now:

<img width="660" alt="Screen Shot 2022-10-13 at 2 49 07 PM" src="https://user-images.githubusercontent.com/60672162/195709444-a4beb946-0d47-4204-ba7e-d36cb43f0f5d.png">

Had to copy this out of the HTML:

```json
{"fetchUid":"267e94db9e1945a745c36f849e51e07a","url":"https://myjsonurl.com/json","status":200,"statusText":"OK","headers":[{"name":"Date","value":"Thu, 13 Oct 2022 20:23:51 GMT"},{"name":"Server","value":"Apache"},{"name":"Vary","value":"Cookie"},{"name":"access-control-allow-origin","value":"*"},{"name":"X-Frame-Options","value":"DENY"},{"name":"Content-Security-Policy","value":"frame-ancestors 'none'"},{"name":"Set-Cookie","value":"PHPSESSID=toc9ncvjb2uq0fi4aphq78fuls; path=/; secure; HttpOnly"},{"name":"Expires","value":"Thu, 19 Nov 1981 08:52:00 GMT"},{"name":"Cache-Control","value":"no-store, no-cache, must-revalidate"},{"name":"Pragma","value":"no-cache"},{"name":"Accept-Ranges","value":"none"},{"name":"Content-Length","value":"190"},{"name":"Connection","value":"close"},{"name":"Content-Type","value":"application/json; charset=UTF-8"}]}
```

#### Desired:

Add JSON response body, make expandable and copyable

### Under `apiRequestContext.get`, tab "Network":

1. Show response body under Response Body.  There is nothing there.

![Screen Shot 2022-10-13 at 2 31 48 PM](https://user-images.githubusercontent.com/60672162/195710400-d5491d61-aced-42d9-8a57-afd0586c8b79.png)

### Under `apiResponse.json`, tab "Call":

1. Show expandable/copyable JSON under RETURN VALUE.  Right now it is showing a "binary" key.

![Screen Shot 2022-10-13 at 2 32 20 PM](https://user-images.githubusercontent.com/60672162/195710671-2804393a-b829-44ff-8009-fafa48a66457.png)

**Comment by ryaudio** [comment]
I should note that this is when you view a trace in a browser from the HTML report via `show-report`

Things are a bit better when you `show-trace` directly, since you can see the Response Body under `apiRequestContext.get`, tab Network.

![image](https://user-images.githubusercontent.com/60672162/195721314-ee905ad3-20b3-440d-a6db-dc792ee82057.png)

**Comment by JonahKK** [comment]
I’d love to have better way to get data from trace, instead of using dev tools 👍🏻

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
