### ISSUE TITLE
[Question] How to set SessionStorage for all tests

### ISSUE THREAD

**Issue by dskochubey** [microsoft/playwright#18079]
I'm trying to figure out how to add SessionStorage for all tests in my framework. I need to add something like this:
` "sessionStorage": [
      {
        "name" : "Automation",
        "value": "1"
      }]`
In documentation I found only this article https://playwright.dev/docs/auth#session-storage. 

How can I implement that each hook and test has the SessionStorage set?

I'm running tests with different browsers and configurations specified as projects.

**Comment by yury-s** [comment]
You can initialize session storage in [beforeEach](https://playwright.dev/docs/api/class-test#test-before-each) hook. You can pick which state to use based on the browserName:

```js
test.beforeEach(async ({context, browserName}) => {
  const file = `sessionState-${browserName}.json`;
  const sessionStorage = (await fs.promises.readFile(file)).toString();
  await context.addInitScript(storage => {
    if (window.location.hostname === 'example.com') {
      const entries = JSON.parse(storage);
      for (const [key, value] of Object.entries(entries)) {
        window.sessionStorage.setItem(key, value);
      }
    }
  }, sessionStorage);
});

```
Would that work for you?

**Comment by dskochubey** [comment]
This works, but I need to use beforeEach in each spec file. Is there a way to use global-setup of something else on global level?

**Comment by dskochubey** [comment]
I found solution using [fixtures](https://playwright.dev/docs/test-fixtures#creating-a-fixture)
```
export default base.test.extend({
    page: async ({ page }, use) => {
        const file = `sessionState-${browserName}.json`;
        const sessionStorage = (await fs.promises.readFile(file)).toString();
        await page.context().addInitScript((storage) => {
            if (window.location.hostname === 'example.com') {
                const entries = JSON.parse(storage);
                for (const [key, value] of Object.entries(entries)) {
                    window.sessionStorage.setItem(key, value);
                }
            }
        }, sessionStorage);
        await use(page);
    },
});
```
Thank you @yury-s for the idea
