### ISSUE TITLE
[ct]: sometimes SvelteComponent.$on() is not in sync 

### ISSUE THREAD

**Issue by caenguidanos** [microsoft/playwright#18073]
In a regular scenario it seems that custom event is not dispatched in sync with the test execution and after searching in Playwright repo and Svelte repo, i don't know how to understand this.

https://github.com/microsoft/playwright/blob/693ed9b19e03f7d29ef188e8b71d6f9485093c8b/packages/playwright-ct-svelte/registerSource.mjs#L104

The value of `result` in the test sometimes is **null**:

![evidence-1](https://raw.githubusercontent.com/caenguidanos/evidences/main/Captura%20de%20Pantalla%202022-10-13%20a%20las%2021.23.26.png)

I need to do a trick and "await" for the result binding a global var inside the component:

![evidence-2](https://raw.githubusercontent.com/caenguidanos/evidences/main/Captura%20de%20Pantalla%202022-10-13%20a%20las%2021.31.54.png)

¿`await locator("...").click()` is not really waiting to the callback finnish when is a well declared `Promise`? Here is the trick with global var. Previously, there is a `dispatcher('end', result)`.

![evidence-3](https://raw.githubusercontent.com/caenguidanos/evidences/main/Captura%20de%20Pantalla%202022-10-13%20a%20las%2021.38.34.png)

**Comment by yury-s** [comment]
> ¿await locator("...").click() is not really waiting to the callback finnish when is a well declared Promise? Here is the trick with global var. Previously, there is a dispatcher('end', result).

Correct, `locator.click()` doesn't know anything about async behavior of the onclick handler, it will only auto-wait for navigations that may be triggered by the click action. In your case `waitForFunction` is the right choice. Does it not wait in some cases or what is the issue with it?

**Comment by caenguidanos** [comment]
Now that the behavior of `locator.click()` is clear, I have no more questions to answer.

But could there be an opportunity to create a helper inside the `MountResult` instance that waits for a specific component event?

```ts
let result: null | number = null;

let component = await mount(SuperSvelteComp, {
  on: {
    end: (payload) => {
      result = payload;
    }
  }
});

await Promise.all([
  // component.waitForOutput("end"),
  component.waitForEvent("end"),
  component.locator("button").click()
]);

expect(result).toBe(200);
```

What do you think?

**Comment by sand4rt** [comment]
Not sure if possible but it would be great if we don't have to think about awaiting at all. Maybe with a retry mechanism?
Made a simpler version of the problem:

```typescript
// Button.svelte
<script lang="ts">
  import { createEventDispatcher } from "svelte";
  const dispatch = createEventDispatcher();

  async function handleClick() {
    await new Promise(r => setTimeout(r, 5000)); // sleep 5 seconds
    dispatch("click", 'hello');
  }
</script>
 
<button on:click={handleClick}>Submit</button>
```

```typescript
// tests.spec.ts
test('emit an async event when the button is clicked', async ({ mount }) => {
  const messages: string[] = []
  const component = await mount(Button, {
    on: {
      click: () => {
        messages.push('clicked')
      }
    }
  })
  await component.click();
  expect(messages).toEqual(['clicked']) // fails because we need to await handleClick
})
```

**Comment by caenguidanos** [comment]
Exactly, but I wouldn't know how to do it looking at the complexity of the playwright-test source code.

The simplest solution I can think of is:

```ts
import { EventEmitter } from 'node:events';
import { test } from '@playwright/experimental-ct-svelte';

import Button from './Button.svelte';

test.only('emit an async event when the button is clicked', async ({ mount }) => {
    let emitter = new EventEmitter();

    const component = await mount(Button, {
        on: {
            click: () => emitter.emit('click')
        }
    });

    await component.click();

    await new Promise((res) => emitter.once('click', res));
});
```

And add a payload to the event if you need it.

**Comment by yury-s** [comment]
> Not sure if possible but it would be great if we don't have to think about awaiting at all. Maybe with a retry mechanism?

You can already achieve that with [poll](https://playwright.dev/docs/test-assertions#polling):

```js
await expect.poll(() =>messages).toEqual(['clicked']);
```

Unfortunately there is no generic mechanism that would automatically wait for the desired effects of a user action. Closing this issue as there are several solutions for the problem.
