### ISSUE TITLE
[BUG] Page.click() sometimes doesn't work

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1808]
**Context:**
- Playwright Version: 0.13.0
- Operating System: macOS

**Describe the bug**

Hi team. I'm having an issue with `page.click()` failing. This is happening in the context of React and Vue apps. I haven't been able to create a reliable reproduction, but I have a couple of clues.

1. In cases where the click fails, the visual state of the element changes and it appears to be in a hover state
2. If I use `page.$eval(selector, (element) => element.click())` in these cases, the click *does* work

Could you shed some light on what the differences are between `page.click(selector)` and `page.$eval(selector, (element) => element.click())`? This may help me create a reproduction case for this issue.

**Comment by dgozman** [comment]
Most likely, React updates the DOM and shuffles around DOM nodes (without changing the visual appearance), so that we start clicking on top of one node and finish on top of the other, at the same coordinates. In this case there are two possible outcomes:
- We click at the wrong place because the node have moved before we calculated click coordinates. This would be a race between Playwright click implementation and dom reshuffling. I don't think the hover effect will be visible in this case.
- We click at the right place and click handlers do not catch it correctly. This would be a bug in the page, because the same could happen to the user clicking during reshuffling.

Of course, this might be something totally different.

**Comment by pavelfeldman** [comment]
@celeryclub thanks for the report!

> Could you shed some light on what the differences are between page.click(selector) and page.$eval(selector, (element) => element.click())? This may help me create a reproduction case for this issue.

`page.$eval(selector, (element) => element.click())` performs a *soft* programmatic click on the element that corresponds to the selector.
- Programmatic click will happen even if the element is invisible, has zero size, is behind another element or is otherwise not interactable.
- Programmatic click is not trusted, see [event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted), it'll be false, the page would know it was injected.

`page.click(selector)` is a real click for testing. It'll locate the element, wait for it to become visible, wait for it to receive input events when clicked in the center of its box, wait for it to stop moving. It'll then perform mouse operations as if the user was clicking the mouse or tapping a phone screen. Browser would think those are real events, they also will be trusted.

Run your app with `DEBUG=pw:input` to see where it stalls. It is likely that the last line of the log will be `waiting for element to receive pointer events at (x, y)`.

**Comment by celeryclub** [comment]
Thanks both of you for the insight. I'm going to see if I can get a repro working.

I realized when re-reading my original message that I may not have been as clear as I could be. When I say the click "fails," what I mean is that according to Playwright it succeeded (no error message related to click), but I can see in my app that it didn't actually click the element, and the next step of my test will fail because the page is in the wrong state.

**Comment by richardwillars** [comment]
I've managed to replicate this consistently. Feel free to use the site for testing this bug. It's built using React and Next.JS.

```
  await page.goto("https://www.waggel.co.uk");
  await page.click("a.login", {
     timeout: 5000,
  });
```

The log says:
```
2020-04-17T13:16:06.496Z pw:input waiting for element to be displayed and not moving...
2020-04-17T13:16:06.514Z pw:input ...done
2020-04-17T13:16:06.515Z pw:input scrolling into veiw if needed...
2020-04-17T13:16:06.516Z pw:input ...done
2020-04-17T13:16:06.519Z pw:input waiting for element to receive pointer events at (12.36,1) 
```

..and then it gets stuck.

Interestingly it also doesn't find the selector if I use `page.click('text="Login"')`

**Comment by celeryclub** [comment]
@richardwillars I don't believe this is the same issue. The first instance of `a.login` on your page is inside of your mobile nav, which has `visibility: hidden` at desktop size. I think that's why playwright can't click your link.

**Comment by osmenia** [comment]
> @celeryclub thanks for the report!
> 
> > Could you shed some light on what the differences are between page.click(selector) and page.$eval(selector, (element) => element.click())? This may help me create a reproduction case for this issue.
> 
> `page.$eval(selector, (element) => element.click())` performs a _soft_ programmatic click on the element that corresponds to the selector.
> 
> * Programmatic click will happen even if the element is invisible, has zero size, is behind another element or is otherwise not interactable.
> * Programmatic click is not trusted, see [event.isTrusted](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted), it'll be false, the page would know it was injected.
> 
> `page.click(selector)` is a real click for testing. It'll locate the element, wait for it to become visible, wait for it to receive input events when clicked in the center of its box, wait for it to stop moving. It'll then perform mouse operations as if the user was clicking the mouse or tapping a phone screen. Browser would think those are real events, they also will be trusted.
> 
> Run your app with `DEBUG=pw:input` to see where it stalls. It is likely that the last line of the log will be `waiting for element to receive pointer events at (x, y)`.

Can you pls give me example how to use DEBUG=pw:input? 
tnx a lot.

**Comment by celeryclub** [comment]
@osmenia It's just an environment variable, so you put it before your command.

```js
DEBUG=pw:input npm run jest (or whatever command you use to run your Playwright script)
```

**Comment by osmenia** [comment]
> @osmenia It's just an environment variable, so you put it before your command.
> 
> ```js
> DEBUG=pw:input npm run jest (or whatever command you use to run your Playwright script)
> ```

sorry i don't understand

I am using windows 10 -> VS Code Terminal
i use command:  node '.\Demo Download_plw.js'

how can i run Demo Download_plw.js with DEBUG=pw:input

What is DEBUG=pw:input? generate log?

thanks a lot

**Comment by celeryclub** [comment]
@osmenia This is a bit off-topic for this thread. StackOverflow has some good resources for learning how to use environment variables on the command line. [Here's one I found](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt). If you have more questions about general command line usage, please ask them there.

**Comment by osmenia** [comment]
> @osmenia This is a bit off-topic for this thread. StackOverflow has some good resources for learning how to use environment variables on the command line. [Here's one I found](https://superuser.com/questions/79612/setting-and-getting-windows-environment-variables-from-the-command-prompt). If you have more questions about general command line usage, please ask them there.

ok sorry for my topic off

i will check it, thanks a lot

**Comment by celeryclub** [comment]
@dgozman @pavelfeldman I was able to create a repro for one of my cases! It turns out that the element I was trying to click was covered by an invisible element. That element begins to animate out of the way upon hover, but at the time of the click it's still covering the center of the button I want to click.

So IMO the bug is that Playwright should tell me that this element isn't interactable, but instead it tells me it successfully clicked the button.

```javascript
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({
    headless: false,
    args: ['--window-size=1280,720'],
  });
  const page = await browser.newPage();

  await page.goto('https://cdpn.io/celeryclub/debug/yLYJLXM/WPMLYZQWGdPr', { waitUntil: 'networkidle0' });
  await page.click('.button');
  await page.waitFor(1000);
  // We should be on bing.com right now but we're still on the original page because the click didn't work

  await browser.close();
})();
```

Here's the codepen link in case the debug URL expires. https://codepen.io/celeryclub/pen/yLYJLXM?editors=0110

**Comment by zeevrosental** [comment]
> Most likely, React updates the DOM and shuffles around DOM nodes (without changing the visual appearance), so that we start clicking on top of one node and finish on top of the other, at the same coordinates. In this case there are two possible outcomes:
> 
> * We click at the wrong place because the node have moved before we calculated click coordinates. This would be a race between Playwright click implementation and dom reshuffling. I don't think the hover effect will be visible in this case.
> * We click at the right place and click handlers do not catch it correctly. This would be a bug in the page, because the same could happen to the user clicking during reshuffling.
> 
> Of course, this might be something totally different.
@dgozman
if the case is dom reshuffling while we do the click.. what can we do to make it more consistent?
I have a case where the ScrolIIntoView(that is inside the click function) reshuffles the dom and then the click fails due to that reshuffling.

**Comment by dgozman** [comment]
@zeevrosental Could you please share more details? What is happening inside ScrollIntoView? How does that trigger reshuffling? If the target element moves, is user supposed to click it after the move?

**Comment by celeryclub** [comment]
@dgozman I can confirm that https://github.com/microsoft/playwright/pull/1869 fixes the issue for me. Thanks! I'm fine with closing this unless you'd like to keep it open.

**Comment by dgozman** [comment]
@celeryclub Wonderful!
