### ISSUE TITLE
File upload API call using Playwright Javascript with Multipart/formdata

### ISSUE THREAD

**Issue by moumita30** [microsoft/playwright#18082]
Testing the upload of a file (image) via API using Playwright with Javascript , My code is given below :

First Way 

```js
test("POST: Upload a file", async ({ request, baseURL }) => {
  const fileName = path.resolve("lib/", "invoice.jpg");
 // const imageData = fs.readFileSync(fileName);
  
  const response = await request.post('capturedoc', {
    headers: {
      Accept: "*/*",
      ContentType: "multipart/form-data",
    },
   
    multipart: {
      "payload": fs.createReadStream(fileName),
      "formdata": {
        "kwdEmployeeName":"Logan McNeil",
        "kwdDocumentName":"Pay Slip",
          "kwdMiscellenous":"Recommendation",
          "documentTypeId":"118",
      },
    },
  })
  expect(response.status()).toBe(201);
  const respbody = await response.text();
  const parsedResp = JSON.parse(respbody)
  console.log(parsedResp);
})
```

2nd way 
```js
test("POST: Upload a file1", async ({ request, baseURL }) => {
  const file = path.resolve("lib/", "invoice.jpg");
  const image = fs.readFileSync(file);
  
  const response = await request.post('capturedoc', {
    headers: {
      Accept: "*/*",
      ContentType: "multipart/form-data",
    },
   
    multipart: {
      payload: {
        name: file,
        mimeType: "image/jpg",
        buffer: image,
      },
      formdata: {
      documentTypeId: "118",
      kwdEmployeeName: "Logan Mcneil",
      kwdDocumentName:"Pay Slip",
      kwdMiscellenous : "Recommendation",
    }
    },
  });
  expect(response.status()).toBe(201);
  const respbody = JSON.parse(await response.text());
  console.log(respbody);
})
```
I was actually trying to recreate a POSTMAN call which is running successfully. But some how through playwright javascript I am facing 500 server error. Any help is appreciable.

**Comment by yury-s** [comment]
Shouldn't all the fields inside `formdata` be just top level fields on `multipart`?

> But some how through playwright javascript I am facing 500 server error. Any help is appreciable.

What is the text of the error message?

Try recording a [trace](https://playwright.dev/docs/trace-viewer-intro) to see what headers / data playwright sends and compare that to what postman sends. Perhaps they send an extra header or the body is formatted differently. We need to know what the difference between the messages is to help you.

**Comment by moumita30** [comment]
![Captureuploadfile](https://user-images.githubusercontent.com/57482730/196105933-2f8ac696-fb5f-4145-b378-3cdec844157e.PNG)

**Comment by moumita30** [comment]
This is the postman request with the code in NodeJs-request mode given beside. The error message is a 500 Server error in debug mode from Vs Code. But when I am running the code from terminal , it is giving no such file or directory. Unfortunately unable to capture trace even if Trace is on in the config file and also running the test file with --trace on. I think, what you said is correct , may be in the The multipart/form data part I am writing something wrong..any thoughts on this..

**Comment by yury-s** [comment]
I think you need to change the parameters as follows to match postman structure:

```js
  const response = await request.post('capturedoc', {
    multipart: {
      payload1: file,
      formdata: {
        documentTypeId: "118",
        kwdEmployeeName: "Logan Mcneil",
        kwdDocumentName:"Pay Slip",
        kwdMiscellenous : "Recommendation",
      }
    },
  });
```
If it doesn't work, can you capture the request on the server side to see what it actually gets in case of postman?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
