### ISSUE TITLE
[Question] why does the app refresh when clicking an element? 

### ISSUE THREAD

**Issue by IdreesSamadi** [microsoft/playwright#18089]
It seems like whenever we click an element on a page it refreshes the app. The reason we don't want the app to refresh is that it resets the app state which we don't want to happen. 

**Context:**
-  nuxt(`2.15.7`)
- single-page application
- playwright (`1.25.1`)
- Operating System: [Windows, Mac]
- Browser: [Chromium, Firefox]

We tried two different ways of clicking an element, both seem to have the same behavior.

- The first way, we just used the `click` function on `page.locator`

 ```javascript
await this.page.goto(`${this.baseURL}`);
await page.waitForSelector('<selector>');
await page.locator('<selector>').first().click();
await page.waitForNavigation();
```

- The second way, we tried to use `page.mouse.click()`

```javascript
await this.page.goto(`${this.baseURL}`);
await page.waitForSelector('<selector>');
const element = await page.locator('<selector>').first();
const box = await element .boundingBox();
await page.mouse.click(box!.x + box!.width / 2, box!.y + box!.height / 2);
```

The element we are clicking looks like this on the browser: 
```
<article class="selector">
     <a href="/random/url" class="">
           <div></div>
     </a>
</article>
```
The `a` tag is rendered by the Nuxt but on our source code we have `NuxtLink` 

```
<article class="selector">
     <nuxt-link :to="/random/url" @click.native="doSomething">
           <div></div>
     </nuxt-link>
</article>
```

**Comment by yury-s** [comment]
You click on a link an the page navigates to the link, the same would happen if a human clicked on the same element, wouldn't it?

**Comment by IdreesSamadi** [comment]
whenever I click on that element, the page doesn't refresh which is the expected behavior. when clicking, Nuxtjs/Vue just replaces the page content with the new content without refreshing the application. however, when I run the code snippet I mentioned above the application seems to refresh when navigating.
 
I'm expecting a similar behavior from Playwright, i.e no refresh when navigating. 

when Playwright clicks on the mentioned element, I see the loading indicator on the browser tab which indicates the application is refreshed, something that should not happen after the initial load of the application, because those navigation are handled by Nuxtjs.

**Comment by dgozman** [comment]
Closing as per above.
