### ISSUE TITLE
[BUG] Query params separated by & are not loaded when using codegen

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#18080]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 14.6
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

`npx playwright codegen https://www.playwright.dev?test=debug&test1=debug1`

**Describe the bug**
When I use codegen to load an url with two query params separated by `&`, it doesn't load the second one. So, in the above example it loads the browser with `https://www.playwright.dev?test=debug`

Could be an expected behavior but wanted to run it through here once.

**Comment by mxschmitt** [comment]
You either need to escape it with backslash or you need to put it between quotes. 

e.g.

`npx playwright codegen "https://www.playwright.dev?test=debug&test1=debug1"`

and

`npx playwright codegen https://www.playwright.dev\?test\=debug\&test1\=debug1`

This is how Bash handels CLI arguments.

Let us know if it works for you!
