### ISSUE TITLE
Set config file in Visual Code Extension 

### ISSUE THREAD

**Issue by janostgren** [microsoft/playwright#18097]
I want to be able to set configuration file.
It will make possible to work with several configuration inside A VS Code project

**Comment by pavelfeldman** [comment]
This just needs a doc - you can already specify the config in the 'Run' and 'Debug' drop downs in Testing sidebar.

**Comment by janostgren** [comment]
Hi
Can not find this in my UI.
Which version has this feature?.

mån 17 okt. 2022 kl. 16:55 skrev Pavel Feldman ***@***.***>:

**Comment by wandyezj** [comment]
I'm loving Playwright and the extension so far!

I have a similar issue.

I would like the `playwright.config.ts` to be named `playwright.ts` in a config folder.

Ideally this should be settable from the `settings.json` file.

The search for the playwright config is currently hard coded in the extension to find all configs named `playwright.config.ts` in any folder.

I'm happy to make this change to add this setting if it seems reasonable.
