### ISSUE TITLE
Why does the firefox application.ini says CodeName=Nightly?

### ISSUE THREAD

**Issue by francopcwolfram** [microsoft/playwright#18094]
I knew that back in the earlier versions of playwright, you were using the nightly version instead of the stable version. Now I see that you started using the Firefox stable version (https://playwright.dev/docs/browsers#firefox). However when I navigate to my browsers installation folder I found this in the firefox application.ini:

```
; This file is not used. If you modify it and want the application to use
; your modifications, move it under the browser/ subdirectory and start with
; the "-app /path/to/browser/application.ini" argument.
[App]
Vendor=Mozilla
Name=Firefox
RemotingName=firefox-default
CodeName=Nightly
Version=105.0.1
BuildID=20221003092848
ID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}

[Gecko]
MinVersion=105.0.1
MaxVersion=105.0.1

[XRE]
EnableProfileMigrator=1


[AppUpdate]
URL=https://aus5.mozilla.org/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml
```

I am a bit confused whether you are using the nightly version but say that it is the stable version or if this file is actually outdated and is being overwritten by the playwright installer (I am using the playwright CLI to update browsers `npx playwright install`).

These are the versions of playwright I have installed:

```
"@playwright/test": "^1.27.1",
"playwright": "^1.27.1",
"playwright-core": "^1.27.1",
```

And the firefox folder I am in is: `firefox-1357`

**Comment by yury-s** [comment]
We do build firefox based on sources of the stable version. The executable that we ship is what build ourselves in our build farm though, we use roughly the same configuration for the builds based on the beta sources of firefox which is likely why you see `CodeName=Nightly` in the .ini file. What actually matters is the version in that file.

Does such CodeName cause any trouble?

**Comment by yury-s** [comment]
We should change that to something that contains 'Playwright' in it to make it clear that this is a custom build.

**Comment by francopcwolfram** [comment]
See this is the default `application.ini` that you get when you download firefox for linux from their site:

```
; This file is not used. If you modify it and want the application to use
; your modifications, move it under the browser/ subdirectory and start with
; the "-app /path/to/browser/application.ini" argument.
[App]
Vendor=Mozilla
Name=Firefox
RemotingName=firefox
Version=105.0.3
BuildID=20221007134813
SourceRepository=https://hg.mozilla.org/releases/mozilla-release
SourceStamp=5a2af3ed86a64618b34bde6f427f2132b13f6bed
ID={ec8030f7-c20a-464f-9b0e-13a3a9e97384}

[Gecko]
MinVersion=105.0.3
MaxVersion=105.0.3

[XRE]
EnableProfileMigrator=1

[Crash Reporter]
Enabled=1
ServerURL=https://crash-reports.mozilla.com/submit?id={ec8030f7-c20a-464f-9b0e-13a3a9e97384}&version=105.0.3&buildid=20221007134813

[AppUpdate]
URL=https://aus5.mozilla.org/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml
```

**Comment by aslushnikov** [comment]
@francopcwolfram we build firefox with "unofficial" branding. This is the default branding for un-official builds.

> Also I would like to know the version/flavour you are using as base.

You can navigate to `about:buildconfig` in Firefox - it gives all the build configuration.

Hope it helps!
