### ISSUE TITLE
[Question] Restrict tests to run only specific envs like dev and qa env, but not in prod

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#18099]
Hi All, is there a way to restrict tests to run only specific envs like dev and qa env, but not in prod?
i run all my tests in docker and pass URL like this.

I have few tests that i want to run only when i pass dev/ qa urls, but when i pass prod url. Can you please advise how to achieve this behavior?

To Run tests in dev:
docker run -e PLAYWRIGHT_BASE_URL="http://ssss.dev.com/" -e RUNMODE="playwright" aug26_401

To Run tests in qa:
docker run -e PLAYWRIGHT_BASE_URL="http://ssss.qa.com/" -e RUNMODE="playwright" aug26_401 

To Run tests in prod:
docker run -e PLAYWRIGHT_BASE_URL="http://ssss.prod.com/" -e RUNMODE="playwright" aug26_401

**Comment by yury-s** [comment]
There are several ways you can achieve that, you can pick one depending on your preferences and constraints, e.g.

1. One way to achieve that would be to have separate [projects](https://playwright.dev/docs/api/class-testproject) for the tests that should run in dev/qa env and in the prod. Then you can pass the names of the projects that you want to execute as command line argument:

```sh
npx playwright test --project=chromium-dev,webkit-dev,qa
```

2. You can [tag](https://playwright.dev/docs/test-annotations#tag-tests) tests that should run in production with e.g. `@prod` and then pass a filter to run only those tests in produnction environment:

```sh
npx playwright test --grep @prod
```

3. You can make your config depend on `PLAYWRIGHT_BASE_URL` environment variable and filter out the tests that should run in that environment:

```ts
const testFilter = ['tests/common/**/*.spec.ts'];
if (process.env.PLAYWRIGHT_BASE_URL?.includes('.prod.com'))
  testFilter.push('tests/prod/**/*.spec.ts');
if (process.env.PLAYWRIGHT_BASE_URL?.includes('.qa.com'))
  testFilter.push('tests/qa/**/*.spec.ts');
if (process.env.PLAYWRIGHT_BASE_URL?.includes('.dev.com'))
  testFilter.push('tests/dev/**/*.spec.ts');

export const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'webkit',
      testMatch: testFilter,
      use: {
        browserName: 'webkit'
      }
    },
  ],
}
```
would that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
