### ISSUE TITLE
[Question] How to have contents of `outputDir` and JSON report (`outputFile`) in the same folder?

### ISSUE THREAD

**Issue by mmdfaisal1** [microsoft/playwright#18092]
I have a question about `playwright.config`, specifically related to `outputDir` and the `outputFile` property of the json report.

```
const currentDateTime = new Date()
  .toISOString()
  .replace(/[:.]/g, "_") //Dot does not need to be escaped inside character class []
  .slice(0, -1);
const resultsOutputPath = `./results/results-${currentDateTime}`;
```
I then use `resultsOutPutPath` in the following two places:

```
const config: PlaywrightTestConfig = {
  testDir: `./tests`,
  outputDir: `${resultsOutputPath}/traces`,
  timeout: 90000,
  expect: {
    timeout: 15000,
  },
  reporter: [
    ["list"],
    [
      "html",
      {
        open: "on-failure",
        outputFolder: `./results/playwright-report`,
      },
    ],
    [
      "json",
      {
        outputFile: `${resultsOutputPath}/test-results.json`,
      },
    ],
  ]
}
```

But when the test executes, it ends up creating two directories under `./results` Please see screenshot.

How can I have just one directory with the JSON report and the contents of the `outputDir`? Thank yuou
<img width="826" alt="image (2)" src="https://user-images.githubusercontent.com/83415767/195865219-c47c36b9-8086-462b-9808-27233854a5be.png">

**Comment by yury-s** [comment]
Today the config file is loaded multiple times - once in the test runner and then in each of the worker processes running the tests. So each of them will have a different timestamp. The json report is written from runner process whereas trace files are written from the workers, so you'll have separate directory for each of the workers. To use the same dir in each test run you can save the timestamp to an environment variable and then read it in the workers:

```js
if (!process.env.CURRENT_DATE_TIME) {
  const currentDateTime = new Date()
    .toISOString()
    .replace(/[:.]/g, "_") //Dot does not need to be escaped inside character class []
    .slice(0, -1);
  process.env.CURRENT_DATE_TIME=currentDateTime;
}
const resultsOutputPath = `./results/results-${process.env.CURRENT_DATE_TIME}`;
```
Will this work for you?

**Comment by mmdfaisal1** [comment]
Thank you, the above is working. I am even more glad to have gotten a better understanding of how the config file works
