### ISSUE TITLE
Improved docs

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#1810]
### Documentation

- [x] `1. Introduction.md`
- [x] `2. Core concepts.md`
  - [x] Contexts, pages and frames
  - [x] Evaluation
    - [x] Node vs Page execution context
    - [x] Object & element handles
  - [x] Selectors
  - [x] Auto-waiting
- [x] `3. Input.md`
  - [x] Forms
  - [x] Text
  - [x] Checkboxes
  - [x] Selects
  - [x] Clicks
  - [x] Files
  - [x] Keys & Shortcuts
- [x] `4. Emulation.md`
  - [x] User agent
  - [x] Viewport, color scheme
  - [x] Devices
  - [x] Locale & Timezone
  - [x] Geolocation
  - [x] Permissions
- [x] `5. Network.md`
  - [x] Navigation & load
  - [x] Waiting for navigation
  - [x] Handling downloads
  - [x] Network events
  - [x] Mocking network
  - [x] Aborting requests
- [x] `6. Scraping and verification.md`
  - [x] Evaluating JavaScript
  - [x] Capturing screenshot
  - [x] Page events
  - [x] Handling exceptions
- [x] `7. Selector engines.md`
  - [x] Built-in engines
  - [x] Custom engines
- [x] `8. Test runners.md`
  - [x] Jest
  - [x] Mocha
  - [x] Karma
  - [x] Jasmine
  - [x] Jasmine
  - [ ] Storybooks
- [x] `9. Continuous integration.md`
  - [x] Docker
  - [x] Git Hub
  - [x] Azure Pipelines
  - [x] Travis CI
  - [x] CircleCI
  - [x] AppVeyor
  - [x] Troubleshooting

-------------------------

Since Playwright was open sourced, we've received incredible feedback from the community and that has had a huge influence on the API design. To make this API more accessible to a larger audience, we plan to invest in better documentation along with the v1 release. This will be a continuous effort, and this issue is a means to put a stake in the ground.

### Content
Structured as navigation sidebar of the upcoming documentation website. Feel free to suggest edits/improvements - this is an evolving list.

* Introduction
  * [ ] Getting started [includes local, GH Action, basic examples that are broadly applicable: goto/navigate -> click -> evaluate]
  * [ ] FAQs
  * [ ] Community showcase
* Guides [with inline code for explanations, and larger snippets with `<details>`]
  * [ ] [Working with elements](https://github.com/microsoft/playwright/blob/master/docs/elements.md) - @arjun27, @dgozman [including resolution of ElementHandle - describe what we have]
  * [x] [Page navigation and loading](https://github.com/microsoft/playwright/blob/master/docs/loading.md) - @dgozman 
  * [ ] Waiting for events/signals [to be linked from `pw:hints` callout for `waitFor`] - @arjun27
  * [ ] Verifying execution: with screenshots, console logs, `pageerror` - @yury-s
* API reference
  * [ ] Release notes / Changelog
  * [ ] { ...List of classes }

### Infra 
- [ ] Docs website @aslushnikov

**Comment by mxschmitt** [comment]
The supported operating systems would be quite helpful. So which minimum version of Windows, MacOS etc. is required and why we don't support every MacOS version.
Ref: #1901 #1535

**Comment by arjun27** [comment]
Closing this for now - we have the first set of docs out. We can take up specific improvements in subsequent issues.
