### ISSUE TITLE
[Question] How to record video on Mac system

### ISSUE THREAD

**Issue by CodingProgrammer** [microsoft/playwright#18102]
Mac : Apple M1 Pro 
version: 12.6 

I created a context with dir, but it did not work and there is no dir named "videos" created and there are no video recordings.

```
const context = await browser.newContext({
    recordVideo: {
        dir: "../videos",
    },
});
```

**Comment by CodingProgrammer** [comment]
@dgozman The picture one is the repo. I true the video on(picture two) and configured the dir as the 'files/' under the root. But there is no video recording generated.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/22937096/197095023-f8d879ae-304a-4082-83cf-181058148373.png">
<img width="898" alt="image" src="https://user-images.githubusercontent.com/22937096/197095109-714ee547-759a-47d1-8d00-ccbacb0882e1.png">

**Comment by dgozman** [comment]
@@CodingProgrammer You should do either `video: 'on'` or use `newContext({ recordVideo })`, but not both at the same time. I'd suggest to use configuration file, and `{ page }` argument for the test function to not create browser/context/page yourself. This way you get everything Playwright has to offer. Take a look at [our docs](https://playwright.dev/docs/writing-tests) as well.

**Comment by CodingProgrammer** [comment]
> @@CodingProgrammer You should do either `video: 'on'` or use `newContext({ recordVideo })`, but not both at the same time. I'd suggest to use configuration file, and `{ page }` argument for the test function to not create browser/context/page yourself. This way you get everything Playwright has to offer. Take a look at [our docs](https://playwright.dev/docs/writing-tests) as well.

@dgozman  OK, thank you
