### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ramam-v** [microsoft/playwright#18101]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows 10
- Node.js version: 16.16.0
- Browser: Edge

## System:
 - OS: Windows 10 10.0.19042
 - Memory: 4.46 GB / 15.78 GB
## Binaries:
 - Node: 16.16.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD  
 - npm: 8.18.0 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

```typescript
```config

import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';


const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 90 * 1000,
  globalTimeout: 900000,
  expect: {

    timeout: 5000
  },

  fullyParallel: true,

  forbidOnly: !!process.env.CI,

  retries: process.env.CI ? 2 : 0,

  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',

  use: {

    actionTimeout: 0,
    video: 'on',
    trace: 'retain-on-failure',
  },

  /* Configure projects for major browsers */
  projects: [

    {
      name: 'Microsoft Edge',
      use: {
        channel: 'msedge',
      },
    },

  ],


};

export default config;

```config
```test
import { test, expect, TestInfo } from '@playwright/test';

test.describe('@TimeOutError', () => {

  test(`@Error`, async ({ page }, testInfo: TestInfo) => {

    await test.step(`Navigate to google.com `, async () => {
      await page.goto("https://www.google.com/");
    });

    for (let i = 1; i < 85; i++) {
      let data = 'Search' + i

      let edit = await page.locator('input[name="q"]');

      await test.step(`Updated search field attemtp ${i}`, async () => {
        await edit.fill("");
        await edit.type(data);

      })

      await test.step(`And presses TAB/ENTER on <DIN> field ${i}`, async () => {
        await edit.press('Tab', { delay: 100 });

      })



      await test.step(`Verify the value was entered in <DIN> field ${i} `, async () => {
        let val = await edit.inputValue();
        expect.soft(val).toBe(data);

      })





    }




  });

});


```test

```

**I have a react app with 84 fields which I have to fill as a part of my script. When I execute my test in regular mode I am seeing Test timeout error after entering the value for fields 70 and above.   When I  run the  test  in slow mode   Test.Slow() it runs most of the time. I have tried adding waits  using WaitFor/waitForElementState method at page and locator  levels but that did not help. 
I was able to replicate the issue using google.com and provided the code sample for you to test. Please let me know if you need any further information here?  **

<img width="802" alt="image" src="https://user-images.githubusercontent.com/68227660/195956216-550a07b3-f6eb-4300-80e4-376a7ee20977.png">

**Comment by yury-s** [comment]
The test you attached passes just fine for me in 15s. It may take much longer on a less powerful machine.

> I have a react app with 84 fields which I have to fill as a part of my script. When I execute my test in regular mode I am seeing Test timeout error after entering the value for fields 70 and above. When I run the test in slow mode Test.Slow() it runs most of the time. I have tried adding waits using WaitFor/waitForElementState method at page and locator levels but that did not help.

You need to increase timeout even further to let the test enough time to pass. The performance may very between different machines so you'd normally want to add extra time to the test average duration. You can either increase the global per test timeout in the config or if it's just one long test like this you can do it inside that test along via [test.setTimeout](https://playwright.dev/docs/api/class-test#test-set-timeout).
