### ISSUE TITLE
[BUG] Playwright run in docker aws lambda break lambda with cryptic error 254

### ISSUE THREAD

**Issue by lughino** [microsoft/playwright#18110]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux ubuntu 20.4
- Node.js version: 16.17.1
- Browser: Chromium
- Extra: Run in docker using the suggested image `mcr.microsoft.com/playwright:v1.27.1-focal`

I'm trying here as you folks may have more clue than me if this is a Playwright specific or not.
I built a docker image using the suggested base image `mcr.microsoft.com/playwright:v1.27.1-focal` to run in a lambda container.
In local (macos) works flawlessly, but once I deploy it, the lambda breaks with a cryptic Error 254.
Sadly, aws seems to not help with debugging as it only prints the error: `Error: Runtime exited with error: exit status 254`

I tried every single combination of changes, even using other docker base images, but resulting in the same issue.
I then downgraded the Playwright version one by one until I found the first latest version `1.22.2` (with `mcr.microsoft.com/playwright:v1.22.2-focal`) which works perfectly.
I'm not sure what changed since that version.
Any ideas?

**Comment by enrialonso** [comment]
Some time ago I built this you can look and try to test if work for you

[https://github.com/enrialonso/aws-lambda-playwright-python](https://github.com/enrialonso/aws-lambda-playwright-python)

**Comment by dgozman** [comment]
@lughino Not really sure how we can help here. The error message does not ring the bell unfortunately.

**Comment by dgozman** [comment]
Closing as per above.
