### ISSUE TITLE
[BUG] Test execution in Webkit is very slow

### ISSUE THREAD

**Issue by sterschl** [microsoft/playwright#18119]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows 10 or Linux
- Node.js version: 16.14.0
- Browser: WebKit

**Describe the bug**

Generally in all tests, it can be observed that the execution in the webkit browser is significantly slower than in chromium, for example.

Running 20 tests in our application takes 3 minutes in chromium. The same tests take 11 minutes to run in webkit.

In this test example, there are regular timeouts because execution in Webkit takes about 40 seconds longer:

> Running 3 tests using 1 worker
> 
>  ok 1 [chromium] › example.spec.ts:36:1 › should test (20s)
>  ok 2 [firefox] › example.spec.ts:36:1 › should test (30s)
>  ok 3 [webkit] › example.spec.ts:36:1 › should test (1m)

The videos show the execution of the sample test. In the example, several folders are created via menu items in the interface and deleted again at the end. It generally seems to take much longer in webkit to capture HTML elements via the locator:

[example-test-webkit.webm](https://user-images.githubusercontent.com/47656372/196150375-b7386846-6358-4ce3-ad3e-b5ace19f2fd3.webm)
[example-test-chromium.webm](https://user-images.githubusercontent.com/47656372/196150387-ad09e320-a789-45d1-9599-b692ad4a380c.webm)

Are there any optimization approaches to this problem?

**Comment by dgozman** [comment]
@sterschl Maybe your app is just slower in Safari? Could you please share a repro with us? Also, I see `Operating System: Windows 10 or Linux` - is it slow on both platforms or just one?

In general, try [recording a trace](https://playwright.dev/docs/trace-viewer-intro#recording-a-trace) and see which operations are slow. Unfortunately, we do not provide any performance recordings inside the page itself.

**Comment by Christian-E** [comment]
I am a colleague of @sterschl and want to provide some further information. The operation system we use is Windows 10 on our development machines and Linux in CI - but that doesn't change anything for us concerning this issue.
What we observe is that basically no matter what we do, it takes much longer in webkit then it takes in chromium.

What we would like to know is, if that is to a certain degree an "expected" or normal behaviour in playwright or if we can do something on our side to improve that.

I can also reproduce this using the `demo-todo-app.spec.ts` tests that come bundled with playwright.
I simply ran `npm init playwright@latest` and changed the `testDir` inside `playwright.config.ts` to `'./tests-examples'`. This gives me the attached report ([playwright-report.zip](https://github.com/microsoft/playwright/files/9811463/playwright-report.zip)). Basically no matter what test you look at - webkit always takes much longer then chromium. And inside the tests every action takes longer. So there is nothing I can narrow it down to.
Thank you already for investigating!

**Comment by yury-s** [comment]
I can't reproduce it on linux (Ubutnu 22.04), here is the report I've got [report.zip](https://github.com/microsoft/playwright/files/9813310/report.zip) Chromium and WebKit are comparable, Firefox is a little slower. What's the linux configuration you ran it on?

**Comment by yury-s** [comment]
Can't reproduce it on the same machine under Windows, here is the report: 
[report-win.zip](https://github.com/microsoft/playwright/files/9813771/report-win.zip)

**Comment by Christian-E** [comment]
In our CI environment (it's GitLab, but I don't think that matters) we run our playwright tests using a docker image that is heavily based on the official playwright docker image (`mcr.microsoft.com/playwright:v1.27.1-focal`). Today I did some further investigations to narrow our problems down.
In the end I removed all of our customisations and ran the mentioned tests using just the plain official docker image on our CI server. This gives me this report: [playwright-report-ci.zip](https://github.com/microsoft/playwright/files/9820991/playwright-report-ci.zip). The webkit tests still take about 1.5 to 2 times longer than the chromium tests. That is not as drastically anymore then it was in my previous report from my local machine, but still much worse than in the reports you provided. Can you try reproducing it using the `mcr.microsoft.com/playwright:v1.27.1-focal` docker image? Thanks again!

**Comment by kasperkowalik** [comment]
I've got the same problem. I run tests in Ci with playwrights docker image (mcr.microsoft.com/playwright:v1.27.0-focal) and every test is 2x-4x times slower than chrome/firefox. When I run tests locally (v1.27), there are no differences between browsers.

**Comment by mxschmitt** [comment]
@Christian-E what is your host OS on the GitLab server? Like the OS where Docker is running on.

Currently it's hard for us to act on it, since we can't repro it.

**Comment by kasperkowalik** [comment]
In my case, we’re running a test in docker in docker service. Looking at trace, it's a problem with locating elements. I have a full loaded page with a form and action page.locator().fill() takes 3.2s in webkit vs 375ms in chromium. In webkit after 3 seconds, input becomes active and it’s filled. It happens in every simple action based on locators like page.locator().hover() 

Same test in WebKit (left) and Chromium (right)
<img width="612" alt="image" src="https://user-images.githubusercontent.com/50206142/198533712-71788388-2e51-4d05-89b7-897531891133.png">

**Comment by Christian-E** [comment]
Hey @mxschmitt ,
I was sure that would be easily reproducible using the docker image, so I didn't already provide more information the last time. Sorry!
Our GitLab runner runs on a `Debian 11 bullseye` host that is virtualized using VMware vSphere. It uses `Docker version 20.10.18, build b40c2f6`.
To make sure that we are not missing something easy, I also pushed the repo I use for generating the reports: https://github.com/Christian-E/playwright-performance-demo
That also includes the `.gitlab-ci.yml`, but there is nothing fancy in it.

In addition I can also reproduce roughly the same performance difference when running the docker image on my local machine in interactive mode. My local machine runs Windows 10 and Docker 20.10.11. In the provided repo's folder i simply do (in powershell): `docker run -it --rm --ipc=host -v ${PWD}:/tests mcr.microsoft.com/playwright:v1.27.1-focal /bin/bash` and then inside the containers interactive bash:

- `cd tests`
- `npm install`
- `npx playwright install`
- `npm run test`

**Comment by yury-s** [comment]
@Christian-E I followed these steps and ran it also under docker on macos host machine. Here is the report: 
[report-mac-docker.zip](https://github.com/microsoft/playwright/files/9976488/report-mac-docker.zip) As you can see there is nothing that stands out in the run time between the browsers. Have you tried running the same suite on another machine to see if the time distribution is the same? At this point I've tried it on 3 different host OSs and was not able to reproduce that on any of them neither were my colleagues. We cannot act on this if we cannot reproduce the problem, so I'm going to close this issue. Feel free to file a new one and link to this if you have more details that could help understand what is the environment in which we could reproducible the problem.

**Comment by Christian-E** [comment]
@yury-s I can accept, that this issue was closed. But I am not so happy with the reasoning behind it. I checked the report you provided and it basically shows exactly what my last report also showed. Summing up the chromium vs. webkit durations in your report leads to a 1.7 times slower webkit performance.
You say that "nothing stands out in the runtime between the browsers" when seeing these numbers. Does this imply, that a 1.7 times (or "almost doubled") runtime in webkit compared to chromium is normal and expected in your experience? That would be totally fine for us. We just want to be sure about that. In that case we would simply increase our timeouts when running in webkit.
Thanks again for investigating! Appreciate it a lot.

**Comment by kasperkow** [comment]
@Christian-E I found a source of the problem in my case. Maybe it's also yours ;) Video and trace recording slowed down webkit performance. In playwright.config.ts I have had
`video: 'retain-on-failure',
  trace: 'retain-on-failure',`
Change to "on-first-retry" speeded up the test 3x.

**Comment by Christian-E** [comment]
Hey @kasperkow. Thank you so much! Sometimes the solution can be so easy. That worked for us as well. It also increased firefox performance significantly.

**Comment by cioroiuradu** [comment]
Had similar situation where running 7 tests on chromium took roughly 5 minutes but on webkit almost 17 minutes.
After changing the config to retain video only on first retry the run time dropped to 8 minutes. I'll say, optimised pretty good.

**Comment by currybob** [comment]
I had a similar issue and after switching from retain-on-failure to on-first-retry, I saw a performance improvement of about 50%. Here are my profiling results

using docker image with playwright version 1.39 (webkit version 17.4)
2core, 4gb memory, 1 test case repeated 10 times

*chromium*
- retain-on-failure / took 3.9m
- on-first-retry / took 2.3m

*webkit*
- retain-on-failure / 7.5m time. 1 flaky
- on-first-retry / 4.3m duration

As you can see, there is a performance improvement by applying the on-first-retry option, but it doesn't make up for the overall performance difference between chromium and webkit.

Overall, I agree with the direction of this issue.
Is the playwright team aware of this and do they have any solutions?

**Comment by penyaskito** [comment]
I use `trace: on-first-retry` and this is still a concerning issue, creating lots of flaky tests because of timeouts.

I ended up adding
```  test.slow(browserName == 'webkit', 'This test is slow on safari');``` on most of my tests to double the timeouts for those, and even if less frequent, it's still an issue.

I usually run my tests on Debian via WSL2, but have GH based CI with docker containers, and some colleagues run them directly on Mac and still noticeable.

Don't think this is something that can be fixed on playwright itself, but just giving another testimony.

**Comment by duartmig** [comment]
Another testimony:
I also use  trace: on-first-retry and my webkit tests normally take 3 or 4x times more than chrome. Since page load, UI interactions, etc all operations take more time than on chromium.
In the report I can see that, in before each hook, only browserType.launch takes 1.7 seconds on webkit while on chromium the whole before each hook takes 61 ms
I also use  screenshot: 'on' to save a screenshot after each test run and same thing observed: on chromium 100ms while on safari 2.2 seconds

**Comment by gvillo** [comment]
For the records, I found a workaround with the release of [v1.52.0](https://github.com/microsoft/playwright/releases/tag/v1.52.0) that introduces [testProject/workers](https://playwright.dev/docs/api/class-testproject#test-project-workers)

The idea is to set 1 worker for every webkit project and I found the sweet spot for now.

Example:
```typescript
{
	name: 'iPhone 15 Safari Guest Flow',
	dependencies: ['setup'],
	grep: [/@guest/],
	use: {
		...devices['iPhone 15'],
	},
	workers: process.env.CI ? 1 : undefined,
}

**Comment by fs-dfernandez** [comment]
Hi everyone I just did something extra that might help I discover that  when using webkit it automatically sets `deviceScaleFactor: 2 `to represents the retina display, making it also very heavy, I just configured it to:
````
 name: "webkit",
      use: { ...devices["Desktop Safari"],
        deviceScaleFactor: 1,
        launchOptions: {
          ignoreDefaultArgs: ["--hide-scrollbars"],
          args: []
        },
        viewport: viewport,
      }
````
using a `deviceScaleFactor: 1` speeded the process a lot.
hope it helps

**Comment by RolandsKundzins** [comment]
Thank you @fs-dfernandez. Setting deviceScaleFactor: 1, cut down on Webkit test times by about 1.8x in my case.
