### ISSUE TITLE
[Feature] - Polling for Python

### ISSUE THREAD

**Issue by athaissen** [microsoft/playwright#18125]
I will need to do something like this :

```py
def check_deploy():
    order_sent = page.locator("text=Deployment successful")

    try:
        order_sent.wait_for(timeout=1000)
        return True
    except:
        return False

while check_deploy() == False:
    page.reload()
```

Refresh a page repeatedly until expecting a particular element.

I did not find in the doc how to do it except like this

Thanks 🙏

**Comment by dgozman** [comment]
@athaissen This seems like a perfectly valid solution. Is there a problem with it? Do you have a better alternative in mind?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
