### ISSUE TITLE
[BUG] input text field goes empty after filling in firefox

### ISSUE THREAD

**Issue by ppshobi** [microsoft/playwright#18121]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux/Mac
- Node.js version: 18
- Browser: [Firefox]
- 

## System:
 - OS: macOS 12.2.1
 - Memory: 87.73 MB / 16.00 GB
## Binaries:
 - Node: 18.6.0 - /opt/homebrew/bin/node
 - npm: 8.13.2 - /opt/homebrew/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**
```javascript
    await page.getByRole('button', { name: 'Create New Campaign' }).click();
    await expect(page).toHaveURL(`/${DCMN_ORG_ID}/campaign/create`);

    await page.locator('#campaign_name').click();
    await page.locator('#campaign_name').fill(campaignName);
    expect(await page.locator('#campaign_name').inputValue()).not.toBe("");

    await page.locator('input[name="campaign\\[localDateRange\\]\\[start\\]"]').click();
    await page.getByRole('spinbutton', { name: 'Year' }).click();
    await page.getByRole('spinbutton', { name: 'Year' }).fill('2021');
    await page.getByRole('spinbutton', { name: 'Year' }).press('Enter');
    await page.getByRole('combobox', { name: 'Month' }).click();
    await page.getByRole('combobox', { name: 'Month' }).selectOption('0');
    await page.locator('.flatpickr-calendar.open').locator('[aria-label="January 1, 2021"]').first().click();
```

## The bug

![ezgif-5-a95a79f173](https://user-images.githubusercontent.com/8536607/196172729-c662f5bb-dd6e-427d-aece-5999197f8750.gif)

This is just a small example I have, but facing issues in other forms too,  

as you can see in the video/code snippet, I am filling in the text field first and then selecting the dates, but in firefox this produces a flaky test because the input field gets emptied as soon as the focus goes away. 

what can I look into to figure out whats going on, I looked at the traces already but did not give any indication other than the test was timed out. also very sure no network calls or javascript acts on this field.

**Comment by dgozman** [comment]
@ppshobi If there is no javascript here at all, this could be Playwright or Firefox bug. Unfortunately, without a repro that we can run locally, it's almost impossible to help you.

That said, this usually indicates a problem with the page itself. Playwright is very fast, and so it exposes possible timing issues. For example, if you open your site while emulating 3G network in Developer Tools, and type the value pretty fast, you might see the same effect because the page does something after you type the value.

**Comment by ppshobi** [comment]
Thanks for the reply. I can try to put up a repo with this problem. The thing is that this problem only appears in firefox. I had around 40 test runs in our Jenkins pipeline and only firefox had this issue of flakiness

**Comment by kemsky** [comment]
This bug definitely exists, input is cleared right after focus moves away. Not present in slowmo.

**Comment by KatrukDmitriy** [comment]
I also faced with this bug. My framework created in java 11. In the version '1.30.0' and browser chrome, for me text dissapired after methods fill() and type(). Similar problem apears for adding file to upload. 

I've found workaround, it's using 'waitForTimeout()'  after type() method.

**Comment by baumar** [comment]
you saved my day Dmitiry by mentioning type()!!! In my case I could fill the field with fill() but when test addressed the next item on the page the content - that was visible in the input field! - disappeared. So clearly when going on from the input field to another page element this action made the input disappear. I tried the click method on the  input field and other actions but that did not work. 
So I thought maybe there is a difference between fill and try that I ignored and filled the field with (deprecated!) fill - and it worked, that is the text remained after program 'jumped' to other fields.

**Comment by KatrukDmitriy** [comment]
> you saved my day Dmitiry by mentioning type()!!! In my case I could fill the field with fill() but when test addressed the next item on the page the content - that was visible in the input field! - disappeared. So clearly when going on from the input field to another page element this action made the input disappear. I tried the click method on the input field and other actions but that did not work. So I thought maybe there is a difference between fill and try that I ignored and filled the field with (deprecated!) fill - and it worked, that is the text remained after program 'jumped' to other fields. And it happened on Chrome, so it does not seem to be firefox specific.


you can try these methods:

   public void type(String inputLocator, String text) {
        Awaitility.await().ignoreExceptions().atMost(1, TimeUnit.MINUTES)
                .pollInterval(5, TimeUnit.SECONDS)
                .until(() -> tryToType(inputLocator, text));
    }

    private boolean tryToType(String inputLocator, String text) {
        page.locator(inputLocator).clear();
        page.type(inputLocator, text);
        return text.equals(page.locator(inputLocator).inputValue());
    }

**Comment by baumar** [comment]
Thank you Dmitriy for that input! Just one small question: I saw the method type is deprecated in Playwright, so maybe this workaround is not durable. Was there no (successful) way to use the recommended function fill?
