### ISSUE TITLE
[Question] How to properly intercept a POST request's response?

### ISSUE THREAD

**Issue by Addison-Dalton** [microsoft/playwright#18133]
Hello!

I'm trying to setup a fixture that will automatically listen for POST requests, record the `id` of the created item, and then delete that item as part of the fixtures clean-up phase.

What I'm running into it is it appears the code I have is inadvertently causing a second item to be created.

Here's the code, it's inside a fairly basic `base.extend...` fixture setup.
```javascript
 cleanupItems: [
    async ({ page }, use) => {
      const itemIds = [];
      await page.route(
        'url/goes/here',
        async (route) => {
          if (route.request().method() === 'POST') {
            const response = await page.request.fetch(route.request());
            const itemId = (await response.json()).id;
            itemIds.push(itemId);
          }

          route.continue();
        }
      );

      await use();

      console.log('cleans ids', itemIds);
    },
    { auto: true },
  ],
```
To be clear, I know it's the fixture above causing the second item. If I remove it, a second item is not created.
Thank you!

**Comment by dgozman** [comment]
@Addison-Dalton Do not continue the route if you have already fetched it and call `route.fulfill()` instead.

```ts
async (route) => {
  if (route.request().method() === 'POST') {
    const response = await page.request.fetch(route.request());
    const itemId = (await response.json()).id;
    itemIds.push(itemId);

    // Add these two lines:
    route.fulfill(response);
    return;
  }

  route.continue();
}
```

Let me know if this helps.

**Comment by Addison-Dalton** [comment]
@dgozman Hey, thanks for the suggestion. I gave this a try, but this is the error I got:

```javascript
route.fulfill: status: expected a number, got a function
```

**Comment by Addison-Dalton** [comment]
@dgozman Ah! I tried this instead, and that seems to be working for now.

```javascript
route.fulfill({ ...response });
```
