### ISSUE TITLE
[BUG] File downloading in some random format not in specified format like pdf/csv 

### ISSUE THREAD

**Issue by GunasriRangu** [microsoft/playwright#18139]
**Context:**

Playwright Version: 1.22.2
Operating System: Mac
Node version: v16.17.1
Browser: Chromium

**Code Snippet**

test.only('Download Script', async ({ browser }) => {
  const context = await `browser.newContext({ acceptDownloads: true });
const page = await context.newPage();
await page.goto('url');
await page.locator("text= Submit ").click();
const [download] = await Promise.all([
  page.waitForEvent('download'),
  page.locator('text=Download Excel').click()
]);
});

**Describe the bug**

After running the script, The file was downloading in some random format and random name and unable to open that file and that file is not available in downloads folder. I would expect it should download in .csv format.

I am not sure why i am unable to attach the images/screenshots . but the same issue is already addressed in https://github.com/microsoft/playwright/issues/2993

suggestedFilename() gives the original name to the file . but we are working on a scenario where we can read the file and see the information in the file.

**Comment by dgozman** [comment]
You have to save the download to where you'd like. Take a look at the [downloads guide](https://playwright.dev/docs/downloads). Let me know if you have more questions.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
