### ISSUE TITLE
[Question] proxy.reload: net::ERR_ABORTED

### ISSUE THREAD

**Issue by gajus** [microsoft/playwright#18137]
I am seeing this happening in our tests:

```ts
proxy.reload: net::ERR_ABORTED; maybe frame was detached?
=========================== logs ===========================
waiting for navigation until "networkidle"
============================================================
```

My theory is that the app is using `window.location` to change the location, which is somehow causing reload to fail.

The code that's failing is simply:

```ts
await page.reload({
  waitUntil: 'networkidle',
});
```

**Comment by dgozman** [comment]
@gajus Your theory seems legit. I'd recommend [recording a trace](https://playwright.dev/docs/trace-viewer-intro#recording-a-trace) and looking for "navigated to <url>" in the logs around `page.reload()` to see what's going on.

**Comment by gajus** [comment]
That appears to be indeed the case. What's the correct way to handle this?

Do I `try..catch` reload and retry or is there a better way?

**Comment by dgozman** [comment]
> Do I `try..catch` reload and retry or is there a better way?

Depends on what your are trying to achieve. If the page navigates itself, perhaps you could just `await page.waitForURL()` and let it navigate to the final url? Try/catch and retry is also a fine solution.

**Comment by gajus** [comment]
> > Do I `try..catch` reload and retry or is there a better way?
> 
> Depends on what your are trying to achieve. If the page navigates itself, perhaps you could just `await page.waitForURL()` and let it navigate to the final url? Try/catch and retry is also a fine solution.

In this case, the intent is to ignore what web app is attempting to do, and take user to a new page.

Prior to adding `page.reload()`, we had a race condition problem. To illustrate it:

```ts
// This methods calls a GraphQL query using `page.evaluate()`
await authenticate(page);

await page.goto('/bar');

await baz();
```

The intent was to authenticate user and redirect to them to `/bar`.

However, what happens in practice, the polling mechanism of the app detects that the user was authenticated, and attempts to redirect them to post-login page.

The end result was that sometimes when `baz()` executes we would be on `/home` and sometimes on `/baz`.

The reason for adding `page.reload()` after `authenticate()` is to ensure that before we are calling `goto` there are no more outstanding redirects.

**Comment by dgozman** [comment]
I think the easiest would be to let the page redirect to `/home`, and then navigate to `/bar`. Something like this:

```js
await authenticate(page);
await page.waitForURL('/home');
await page.goto('/bar');
await baz();
```

**Comment by gajus** [comment]
Where is the facepalm emoji when I need it.

Of course that makes the most sense.

Thanks.
