### ISSUE TITLE
When my test run I want my chrome browser to open a zoom value of 80% automatically, currently it opens 50% by default. How can I setup this in playwright?

### ISSUE THREAD

**Issue by MesfinMT** [microsoft/playwright#18151]

**Comment by MesfinMT** [comment]
package org.example;

import com.microsoft.playwright.*;

public class Example {
  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      Page page = browser.newPage();
      page.navigate("http://playwright.dev");
      System.out.println(page.title());
    }
  }
}

**Comment by dgozman** [comment]
@MesfinMT Could you share a screenshot please? I am unable to reproduce zooming, so more details are needed.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.

**Comment by ray440** [comment]
It's possible that the zoom level was manually set (e.g. an accidental ctrl+mouse-drag).  Chrome remembers the zoom level and whenever you open that page, it "defaults" to that zoom. Bringing up playwright and resetting the zoom (ctrl+0) might fix the issue.
