### ISSUE TITLE
[Question] How to debug tests in VS Code (without Playwright Test extension)?

### ISSUE THREAD

**Issue by mmdfaisal1** [microsoft/playwright#18164]
I’d like to debug Playwright tests in VS Code (without using [Playwright Test for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) the extension). I have the following `launch.json`

```
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Debug Playwright Tests",
      "skipFiles": ["<node_internals>/**"]
    }
  ]
}
```

This works fine if I use the JavaScript Debug Terminal and command `npx playwright test testfile.ts`. But not able to debug from within VS Code itself (Run -> Start Debugging / F5 or the Run and Debug section and choosing the above configuration). I think I would need the right values for the `program` and `args` property in the above launch config.

<img width="1613" alt="image (3)" src="https://user-images.githubusercontent.com/83415767/196554806-215e2a86-ffad-479b-b3ad-c9ffb3ca46d9.png">

**Comment by dgozman** [comment]
@mmdfaisal1 I think you'll need something like this:
```json
{
  "program": "node",
  "args": ["node_modules/playwright-core/cli.js", "test", "testfile.ts"]
}
```
Let me know whether this helps.

That said, we highly recommend the extension, because it will make your life much easier.

**Comment by mmdfaisal1** [comment]
Thank you @dgozman. The following worked

```
"program": "${workspaceFolder}/node_modules/playwright-core/cli.js",
 "args": ["test", "${file}"]
 ```
 
We could not get the Playwright extension to work in the past where Playwright was a Node project inside another Node project/repo. I will try again - both in that scenario and in the stand alone Playwright project (where I am sure it will work just fine)
