### ISSUE TITLE
[BUG] Not able to run Playwright test on firefox node on selenium grid

### ISSUE THREAD

**Issue by Nagam-Naidu** [microsoft/playwright#18174]
**Context:**

**Summary:** [BUG] Not able to run Playwright test on firefox node on selenium grid

We have selenium grid with firefox node, when trying to run playwright test using pabot command it is failing with below 
error.

**Error:**
`details = “Error: browserType.launch: Connecting to SELENIUM_REMOTE_URL is only supported by Chromium”`

**Command to run test:**
`pabot --processes 5 --testlevelsplit --outputdir=./output --exclude exclude --include Playwright .`

For redirecting browser to selenium grid we are have exported below command.

`export SELENIUM_REMOTE_URL=http://localhost.com:4444/wd/hub`

After looking in the code it seems like we don't have support for Firefox. Let us know how can this be resolved or do we have any workaround solution around it.

`  const __testHookSeleniumRemoteURL = `http://127.0.0.1:4444/wd/hub`;
  const error = await browserType.launch({ __testHookSeleniumRemoteURL } as any).catch(e => e);
  expect(error.message).toContain('Connecting to SELENIUM_REMOTE_URL is only supported by Chromium');
});`

https://github.com/microsoft/playwright/blob/c7212e6d56c05cf0618794e878b4d11987c70c36/tests/library/browsertype-launch-selenium.spec.ts#L173

- Playwright Version: Version 1.23.0
- Operating System: 
- Node.js version: v12.18.3
- Browser:"browserName":"firefox","browserVersion":"105.0","platformName":"LINUX","se:noVncPort":7900,"se:vncEnabled":true}
- Extra:
Below are Grid details 
- Node Id: 15e762cf-7493-4ccd-a786-f16048c371ea
OS Arch: amd64
OS Name: Linux
OS Version: 5.10.135-122.509.amzn2.x86_64
Total slots: 1
Grid version: 4.5.0 (revision fe167b119a)

**Comment by dgozman** [comment]
@Nagam-Naidu As the error message says, connecting to SELENIUM_REMOTE_URL is only supported by Chromium. [Documentation](https://playwright.dev/docs/selenium-grid) says the same. There are no plans to make this work with Firefox, sorry.

**Comment by Nagam-Naidu** [comment]
@dgozman, Do we have any plan for the same in future?

**Comment by dgozman** [comment]
There are no plans to make this work with Firefox, sorry.
