### ISSUE TITLE
[BUG] Locator option hasText actually fails on browserstack on click() method

### ISSUE THREAD

**Issue by Iv3x** [microsoft/playwright#18176]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Mac]
- Node.js version: [14.6]
- Browser: [Chromium]
- Extra: [local and browserstack]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
this.Locator = this.page.locator('//*[@data-test-id="list-item"]', { hasText: 'foo' })}

this.Locator.click();
```

**Describe the bug**

This Locator actually works locally on my machine but throws an error on BrowserStack:
locator.click: Unknown engine "internal:has" while parsing selector xpath=//*[@data-test-id="list-item"] >> internal:has="text=foo"

Is this intended to fail like this ? 
I am actually a bit confused since it works locally on my machine

**Comment by dgozman** [comment]
@Iv3x Most likely, you have different versions of Playwright locally and on the Browserstack server. I'd suggest to check with them. Let me know if we can help with anything else.

**Comment by dgozman** [comment]
Closing as per above.
