### ISSUE TITLE
Can i customize the code gen ? Like while recording can i download the code to the local folder ?

### ISSUE THREAD

**Issue by VasanthEzhilkumar** [microsoft/playwright#18181]

**Comment by dgozman** [comment]
@VasanthEzhilkumar Could you be more specific about what kind of customization you are interested in?

> can i download the code to the local folder?

You can always copy-paste the code into any file you'd like, there is a button for copying the source. You can also use `--output` command line flag that will save the code at the end.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
