### ISSUE TITLE
[BUG] Clicking on a hidden element shouldn't crash the browser

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#18183]
**Context:**
- Playwright Version: 1.27
- Operating System: Mac
- Node.js version: [e.g. 12.22, 14.6]
- Browser: Chromium

**Code Snippet**

```javascript
import { test } from '@playwright/test';

test('will not crash the browser', async ({ context, page }) => {
  await page.goto("https://yari-demos.prod.mdn.mozit.cloud/es/docs/Web/HTML/Element/input/hidden/_sample_.basic_example.html");
  await page.locator('#prodId').click({timeout:0, force: true});
});
```

**Describe the bug**

Although clicking on a hidden element is not a valid action, The target shouldn't crash (see screenshot) if I try to do that.

![image](https://user-images.githubusercontent.com/2198466/196722469-6410e344-f933-4b5c-b475-4cf03172e732.png)

Hint. It seems that the `DOM.scrollIntoViewIfNeeded` CDP call is crashing the target.

**Comment by dgozman** [comment]
Filed upstream: https://bugs.chromium.org/p/chromium/issues/detail?id=1379391

**Comment by dgozman** [comment]
Fixed upstream, should be good after next roll.

**Comment by kblok** [comment]
Thank you so much @dgozman!
