### ISSUE TITLE
Importing into test file causes Playwright to evaluate all js/ts in external module

### ISSUE THREAD

**Issue by harry-gocity** [microsoft/playwright#18184]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Mac
- Node.js version: 16 LTS
- Browser: All

**Code Snippet**

I couldn't get it working in CodeSandbox but please see the reproduction [here](https://github.com/harry-gocity/playwright-import) (or try a [sandbox](https://codesandbox.io/s/github/harry-gocity/playwright-import)) 

1) run `npx playwright test`- the test should pass
2) uncomment `import {testData} from '../mockData'` in the `repro.test.ts` file
3) run the test again

**Describe the bug**

The test will fail on the second run with an error, event though the import that is causing the error in `mockData.ts` is not used by the playwright test itself. This also appears when our `mockData.ts` file imports types from other files, and in going to those files playwright evaluates module level js that would not normally be run (e.g. outside of NextJs runtime). We don't see this behaviour with jest when running unit tests.

We have a general mock data file that is used across our unit/integration/e2e tests, which contains info such as dummy card details, mock redux state, pretend user details etc. Importing anything from this file in our playwright tests seems to result in playwright evaluating every single import in that file rather than just using what it needs. 

There is a similar issue here (https://github.com/microsoft/playwright/issues/18150) which relates to using experimental components and not being able to import anything other than components. We aren't using component testing, and either way I would consider the `mockData` file to essentially be our helper in that scenario.

**Comment by dgozman** [comment]
@harry-gocity You are not supposed to import front-end stuff from your tests, except for components. Take a look [at the docs](https://playwright.dev/docs/test-components#under-the-hood), especially [this section](https://playwright.dev/docs/test-components#q-i-cant-import-anything-other-than-the-components-from-tsxjsxcomponent-files).

That said, this could be fixed by #18157 if your redux imports are actually unused in the `mockData.ts` file. However, if those are used, Playwright will have to load the whole file and will fail because redux does not run in the Node.js environment.

**Comment by harry-gocity** [comment]
Thanks @dgozman - I saw both of those previous links in the similar issue but they apply specifically to using the web components experimental features (or at least that's what the docs imply). If this is the case for using playwright to run tests in browser then these known issues should be bumped much much higher up the docs IMO.

The redux (and other) imports are used in the `mockData` file (just not in the repro) but the const declarations they are used in are not imported by playwright tests. So I'm not sure https://github.com/microsoft/playwright/pull/18157 would resolve our issues, and it seems to apply to component tests anyway. Is there a preview I can try that has that fix included?

**Comment by dgozman** [comment]
@harry-gocity I didn't realize this is about e2e and not component tests, my bad! So, in e2e tests you should not import any front-end code at all. Everything is executed in Node.js, which means no redux imports.

I'd recommend to split `mockData` into two files: data that you need for e2e tests and everything else. This way you should be able to import e2e specific data without any problems. Let me know if that helps.

**Comment by harry-gocity** [comment]
@dgozman No problem - that's the workaround we've taken in the meantime and it's working fine, albeit we have some duplicated mock data. Is this in the docs and I've just missed it completely? 

Thanks otherwise - if this is expected behaviour then you can close this issue. Although, It would be a nice to not have to worry about this at all - we're not really importing these Redux types into our tests anyway, they're just in the general import scope that playwright is working through.
