### ISSUE TITLE
[BUG] Playwright bundle browsers does not have/install Chrome and Edge browsers

### ISSUE THREAD

**Issue by siricinschigrenke** [microsoft/playwright#18196]
Playwright should support out of the box Chrome and Edge browsers.
That means when you use ./playwright install it should install supported versions of Chrome and Edge browsers in this location %USERPROFILE%\AppData\Local\ms-playwright on Windows
~/Library/Caches/ms-playwright on MacOS
~/.cache/ms-playwright on Linux
Now it install only Chromium and is not the desired behavior because there is no way to control what version of Chrome and Edge browser are installed and supported by version of playwright.
Expected behavior : With ./playwright install command playwright should also download the supported Chrome and Edge browsers

**Comment by dgozman** [comment]
@siricinschigrenke Playwright works with Chrome and Edge that are already installed on the machine. [See docs](https://playwright.dev/dotnet/docs/browsers#google-chrome--microsoft-edge)
