### ISSUE TITLE
[BUG]page.request.get() hangs with the timeout parameter

### ISSUE THREAD

**Issue by shuguang101** [microsoft/playwright#18190]
**Context:**
- Playwright Version: [playwright==1.25.2]
- Operating System: [Mac]
- Python version: [python3.8.13]
- Browser: [Chromium]

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

def run(playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch(headless=False, channel="chrome")
    page = browser.new_page()
    page.set_default_timeout(10000)
    page.set_default_navigation_timeout(10000)

    page.goto("https://juejin.cn/post/6844903846766968845")
    page.wait_for_load_state(state="networkidle", timeout=10000)
    # the page.request.get() will hang, but it should timeout
    page.request.get("https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/site.webmanifest", timeout=5000, headers={
        "Accept": "*/*",
        "Pragma": "no-cache",
        "Cache-Control": "no-cache",
        "Range": "bytes=0-1"
    })
    
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```

**Describe the bug**

This url "https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/site.webmanifest" does not support range headers, so a request with the "Range: bytes=0-1" header will caused http request hang. Because I set the timeout parameter(timeout=5000), so page.request.get() should timeout after 5s. But in fact, page.request.get() will hang.

**Comment by mxschmitt** [comment]
Looks like response does only emit `close` but not `end` when its a partial response.

cp: https://github.com/microsoft/playwright/blob/9b35a8071f2afbd6fb123bf418b8c734f8daa2e8/packages/playwright-core/src/server/fetch.ts#L368

**Comment by mxschmitt** [comment]
Looks like the server doesn't properly encode range response with Brotli - apparently it cuts selected range from already encoded body whereas it should first cut out the specified range and then encode it. You can see that the response received with curl is also corrupted: `curl -O -v -X GET -H "range: bytes=0-1" -H "Accept-Encoding: br" https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/site.webmanifest`
If you don't care about the response encoding you can pass headers:
```
{
    'Accept-Encoding': '',
    'Range': 'bytes=0-1',
}
```
as a workaround. Would that work for you?

**Comment by shuguang101** [comment]
`{
    'Accept-Encoding': '',
    'Range': 'bytes=0-1',
}`
This is worked for "https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/site.webmanifest". But other urls may also encounter this problem. Is it possible to fix this problem(return an error or trigger timeout). The decompress() is called in fetch.ts, if decompress failed an error should be returned, BrotliDecompress a corrupted data should not caused page.request.get() hang.
https://github.com/microsoft/playwright/blob/9b35a8071f2afbd6fb123bf418b8c734f8daa2e8/packages/playwright-core/src/server/fetch.ts#L352
https://github.com/microsoft/playwright/blob/9b35a8071f2afbd6fb123bf418b8c734f8daa2e8/packages/playwright-core/src/server/fetch.ts#L359

**Comment by yury-s** [comment]
Looks like it only hangs in node 16 and passes in node 18, I tried this test:

```js
test('should not hang on a brotli encoded Range request', async ({ context }) => {
  await context.request.get('https://lf3-cdn-tos.bytescm.com/obj/static/xitu_juejin_web//static/favicons/site.webmanifest', {
    headers: {
      range: 'bytes=0-2',
    },
  });
});
```

In node 18 it throws 
```
Error: unexpected end of file

    at BrotliDecoder.zlibOnError [as onerror] (node:zlib:189:17)
```
So it should be fixed in the next release once we switch to node 18.

**Comment by shuguang101** [comment]
fixed in Node.js 18
