### ISSUE TITLE
[waitForTimeout] Slower than actual 

### ISSUE THREAD

**Issue by RSS1102** [microsoft/playwright#18198]
```ts
test("rotatestart", async ({ page }) => {
  await page.goto("http://localhost:5173/#/rotatestart");
  await page.waitForTimeout(5000);
});

```
I visited a `<canvas ></canvas >`page and asked him to wait for 5000ms to generate a video. The action of the video **is slower than that on the actual web** (twice slower)

**Comment by dgozman** [comment]
@RSS1102 Could you please share a repro that we can run locally? Attaching a video would also be helpful. I'd suggest to [record a trace](https://playwright.dev/docs/trace-viewer-intro) and investigate what's going on.

**Comment by RSS1102** [comment]
> @RSS1102 Could you please share a repro that we can run locally? Attaching a video would also be helpful. I'd suggest to [record a trace](https://playwright.dev/docs/trace-viewer-intro) and investigate what's going on.

https://github.com/RSS1102/canvas
This is my project (including the generated video)。
```
npm install 
npm run dev
npm run test
```

and you will see the produced video. When you visit the video, you will find that the image in the video runs very slowly(Not the speed on the web).
You can first visit the video I have generated before, and then you can generate the video yourself again to see the difference.

---
_by the way,In fact, I want to generate video through playwright, and then transfer it to gif for display, but I haven't found a good method of ** video=>gif**._

**Comment by Jasonlhy** [comment]
I also encountered this issue in my project ... but I pull the playwright source code today and run playwright-test, it fixed my problem.
