### ISSUE TITLE
[BUG] Firefox Web Audio API is not working properly in docker image since v1.24.0-focal

### ISSUE THREAD

**Issue by skyuplam** [microsoft/playwright#18206]
**Context:**
- Playwright Version: from v1.24.0 to v1.27.1
- Operating System: Linux
- Node.js version: v16.16.0 - v16.17.1
- Browser: Firefox
- Extra: The bug only occurs i in the official docker images from `mcr.microsoft.com/playwright:v1.24.0-focal` to `mcr.microsoft.com/playwright:v1.27.1-focal`

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { test, expect } from '@playwright/test';

test('web audio', async ({ page }) => {
  const detected = await page.evaluate(async () => {
    const context = new AudioContext();
    const oscillator = new OscillatorNode(context, {type: 'square', frequency: 1000});
    const analyser = new AnalyserNode(context);
    oscillator.connect(analyser);
    oscillator.start();

    const buffer = new  Float32Array(analyser.fftSize);

    const THRESHOLD = 1 / 32767;
    const verifySamples = () => {
      const first = buffer[0] ?? 0;
      const last = buffer[buffer.length - 1] ?? 0;
      return ((Math.abs(first) > THRESHOLD) && Math.abs(last) > THRESHOLD);
    };

    const result = await new Promise<boolean>(resolve => {
      const intervalId = setInterval(() => {
        analyser.getFloatTimeDomainData(buffer);
        if (verifySamples()) {
          clearInterval(intervalId);
          clearTimeout(timeoutId);
          resolve(true);
        }
      }, 50);
      const timeoutId = setTimeout(() => {
        clearInterval(intervalId);
        analyser.getFloatTimeDomainData(buffer);
        resolve(verifySamples());
      }, 5000);
    });

    await context.close();

    return result;
  });

  expect(detected).toBeTruthy();
});

```

**Describe the bug**
Since the docker image upgrade from v1.24.0, Firefox fails to get audio data with web audio API inside the container as shown above. It works as expected in `mcr.microsoft.com/playwright:v1.23.4-focal`, and it works properly when not using the docker image.

**Comment by aslushnikov** [comment]
@skyuplam it looks like Firefox now requires Pulse audio service working for the web audio api to work. By default, docker container doesn't have `pulseaudio` installed & running.

You can fix it like this:

```bash
$ apt-get update && apt-get install -y pulseaudio
$ pulseaudio --start # start pulseaudio in background
```

Once PulseAudio is started, the test passes for me.

**Comment by skyuplam** [comment]
@aslushnikov Oh, thanks for your quick response and I have just tried it and it works when I installed the pulseaudio and started it.

**Comment by aslushnikov** [comment]
It's not something we can put to our docker image though: docker container doesn't launch any services by default. So I'll close this for now given this workaround.

**Comment by skyuplam** [comment]
Hi @aslushnikov , I am wondering why it worked in the image of v1.23 and now we have to use this workaround to make it work again? As you said that 

> docker container doesn't launch any services by default

How could it work in v1.23 and before without launching any service?

**Comment by aslushnikov** [comment]
@skyuplam this seems to be a firefox upstream change that now requires pulse audio service.

**Comment by skyuplam** [comment]
hmm... I can only find that Firefox starts to require PulseAudio since version 52.0 https://www.mozilla.org/en-US/firefox/52.0/system-requirements/

**Comment by aslushnikov** [comment]
@skyuplam i think they extended their reliance on PulseAudio for other WebApi's, not sure if intentionally or not. I'd ask mozilla folks on their bug tracker or in their matrix channel.

**Comment by skyuplam** [comment]
@aslushnikov really appreciated for your reply. We use Web Audio APIs a lot test test audio related parts of our app, and would like to avoid the complications of setting up PulseAudio for testing the app with Firefox. I would really appreciate if you can post some updates (if any) of your findings from the mozilla folks. 🙇🏻‍♂️
