### ISSUE TITLE
[BUG]baseURL : No expected splicing baseURL

### ISSUE THREAD

**Issue by RSS1102** [microsoft/playwright#18202]
**Context:**
- Playwright Version:  "@playwright/test": "^1.27.1",
- Operating System: Windows
- Node.js version:18.0.6
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
1. The route I expect to access is:`http://localhost:5173/#/rotatestart`
     infact:`http://localhost:5173/rotatestart`
```ts
baseURL: "http://localhost:5173/#/"
```
```ts
test("risingstars", async ({ page }) => {
  await page.goto("/risingstars");
  await expect(page).toHaveURL("http://localhost:5173/#/risingstars");
  await page.waitForTimeout(5000);
});
```
---
When I do this is the correct access:
```ts
baseURL: "http://localhost:5173/"
```
```ts
  await page.goto("/#/risingstars");
  ```

**Comment by dgozman** [comment]
@RSS1102 This is how `baseURL` completion works. See [this comment](https://github.com/microsoft/playwright/issues/8933#issuecomment-920270705) or [docs](https://playwright.dev/docs/api/class-testoptions#test-options-base-url) for examples. Your last example is perfect.

Let me know if you have any questions.

**Comment by RSS1102** [comment]
> @RSS1102这就是`baseURL`完成的工作方式。有关示例，请参阅[此评论](https://github.com/microsoft/playwright/issues/8933#issuecomment-920270705)或[文档](https://playwright.dev/docs/api/class-testoptions#test-options-base-url)。你的最后一个例子是完美的。
> 
> 如果您有任何问题，请告诉我。

ok ，i get it.thanks.
