### ISSUE TITLE
[Question]What is the best way to introduce wait time if UI automation has to wait for some back end apis to run to proceed further

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#18216]
So I have a scenario where playwright automation runs to perform some actions in the UI and then has to wait for few seconds for some apis to trigger and create some data. this data will be used by the UI automation to perform further actions on the web.What is the best way to introduce wait here. for now I am using page.waitForTimeout(). Just wanted to check if there is a better way than introducing static wait.

**Comment by dgozman** [comment]
@JasKirk70 Are there any changes on the page after backend is done with creating the data? If so, you can do something like this:

```js
await expect(page.getByText('Done creating data')).toBeVisible();
```

Basically, how would the user know that they can proceed? You should mimic that in the test.

**Comment by JasKirk70** [comment]
got it sounds good..thanks for the reply
