### ISSUE TITLE
[BUG] connect ETIMEDOUT { myIP } on windows10 env

### ISSUE THREAD

**Issue by inqom-circle** [microsoft/playwright#18211]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Windows 10]
- Node.js version: [16.18]
- Browser: [All]

Recently I got many connect ETIMEDOUT { myIP } error.
I use a windows10 computer.
There is no specific things that trigger this error, art least I can't notice it, I just do basic stuff with request calls and front interaction.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
