### ISSUE TITLE
[Question] If Promise.all runs all promises at the same time (concurrently), why does the order then still matter?

### ISSUE THREAD

**Issue by larsqa** [microsoft/playwright#18213]
Looking at `waitForEvent` (https://playwright.dev/docs/api/class-page#page-wait-for-event), the code example mentions

> // It is important to call waitForEvent before click to set up waiting.

I thought using `Promise.all` solved the issue all-together?

**Comment by dgozman** [comment]
@larsqa In general, async methods that return a Promise have a synchronous part (before the first `await` inside), and the order of two synchronous parts matter. In the particular case of `waitForEvent()` vs `click()` there is no difference, because synchronous parts are not doing much, but in general you should use caution. Does this make sense?

**Comment by larsqa** [comment]
@dogzman I tried to read your explanation several times but didn't really get what you mean?

**Comment by yury-s** [comment]
@larsqa Imagine that all methods that you call in Promise.all return their results synchronously. In that case wrapping them in `await Promise.all` is essentially a no-op and the order of calls obviously matters. Playwright API methods marked as async have some parts which run synchronously (and some methods may even complete synchronously) so the order of their invocation matters for the same reason as in the sync example.

**Comment by larsqa** [comment]
I'm having a tough time understanding your (probable) good explanations, but would love to understand the reason!

My understanding of Promise.all is that it executes its promises all at the same time. Even with some promises, that have synchronous parts inside, how does the order matter if PromiseA or PromiseB end up beeing executed at the same time?

**Comment by dgozman** [comment]
@larsqa I'd suggest to read about JavaScript single threaded environment and async model. Here is an [example article](https://dev.to/lydiahallie/javascript-visualized-event-loop-3dif) that explains it.
