### ISSUE TITLE
[Question] Navigating between Angular routes

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/playwright#18236]
We're currently migrating protractor tests to playwright, and one thing that doesn't work, and I can't find away around it looking through the documentation, is navigating to other routes or navigating to the same route without the current query params.
Example:
`await this.page.goto('http://localhost/#/my-app');`
We then do some stuff in the test and the URL i updated to:
`await this.page.goto('http://localhost/#/my-app?state=mystate');`
For the next test we need to remove the state, so we do:
`await this.page.goto('http://localhost/#/my-app');`
The URL is not updated with the `state=mystate` removed like it behaved in Protractor.

Also, this doesn't work either:
`await this.page.goto('http://localhost/#/my-app');`
`await this.page.goto('http://localhost/#/my-other-app');`

It doesn't update the URL with the other route.
The current solution of the the devs did was:
``` 
await this.page.reload();
await this.page.goto('http://localhost/#/my-app');
```
But that increases the test times with 100% since it's two navigations instead of one.

What is the correct way of doing this?

**Comment by dgozman** [comment]
@JonWallsten Your `page.goto()` calls look correct. Could you please share a repro that we can run locally? Otherwise, I can just advise to use the [debugging tools](https://playwright.dev/docs/running-tests#debugging-tests) and see what's going on.

**Comment by mxschmitt** [comment]
Since it does not look like an issue with Playwright, I'm closing it for now.

If you have a repro in the future, (preferred without any frameworks like Angular) then feel free to re-file! Thanks.
