### ISSUE TITLE
[BUG] Browser fixture can't be overriden

### ISSUE THREAD

**Issue by dh0d** [microsoft/playwright#18238]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Linux
- Node.js version: 16.17.1
- Browser: [e.g. All, Chromium, Firefox, WebKit]

**Code Snippet**
```javascript
export const test = base.extend({
	browser: async ({ browser }, use) => {
		browser = await chromium.launch({
			ignoreDefaultArgs: ['--no-startup-window'],
			executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,
		});
		await use(browser);
		await browser.close();
	},
});
```

**Describe the bug**
The idea - if PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD is set in env we need to use installed cromium for test, otherwise use browsers from playwright.

I've tried to do this via fixtures, but with code above browser from playwright is still used.

But if to change code to (remove browser on entry):
```javascript
export const test = base.extend({
	browser: async ({ }, use) => {
		const browser = await chromium.launch({
			ignoreDefaultArgs: ['--no-startup-window'],
			executablePath: process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH,
		});
		await use(browser);
		await browser.close();
	},
});
```
installed browser is used.

**Comment by dgozman** [comment]
@dh0d I think both versions should work. The first version will also launch the default playwright browser, because you wanted to use it by specifying the `browser` argument.

That said, it's much easier to change things in the config:
```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    launchOptions: {
      // Use a custom path, or undefined for default path.
      executablePath: process.env. PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH || undefined,
    },
  },
};
export default config;
```

**Comment by dh0d** [comment]
@dgozman seems it is what exactly I need)) thank you.  I will close the issue then.
