### ISSUE TITLE
How to set ffmpeg to system

### ISSUE THREAD

**Issue by jw-star** [microsoft/playwright#18233]
### Your question

this is dockerfile,I want to set up alis, but when I run the container, it doesn't take effect

```
RUN pip --no-cache-dir  install --user -r /app/requirements.txt  \
    && python3.10 -m playwright install chromium --with-deps
RUN  echo alias ffmpeg='~/.cache/ms-playwright/ffmpeg-1007/ffmpeg-linux' >>/etc/profile
```
There is also a relationship between the path of ffmpeg and the version number, it is best to fix the path

**Comment by dgozman** [comment]
@jw-star Could you tell us more about your workflow? Note that Playwright's [official docker images](https://playwright.dev/docs/docker) already has ffmpeg and all browsers pre-installed.

**Comment by jw-star** [comment]
@dgozman I built it myself, no other browser needed

**Comment by jw-star** [comment]
```
FROM ubuntu:jammy
MAINTAINER jwstar
ENV DEBIAN_FRONTEND=noninteractive
RUN mkdir /config  \
    && mkdir /app && apt-get -y update  \
    && apt-get install -y wget python3.10 python3-pip python3.10-dev 
RUN pip --no-cache-dir  install --user -r /app/requirements.txt  \
    && python3.10 -m playwright install chromium --with-deps

```

**Comment by dgozman** [comment]
@jw-star I am sorry, but I still don't understand what are you trying to achieve. Playwright installs browser and ffmpeg for itself, it does not use any ffmpeg that's available on the system. How should we help you?

**Comment by jw-star** [comment]
@dgozman I want to use Playwright's ffmpeg, put it in environment variables

**Comment by jw-star** [comment]
> > Playwright chrome正式安装后，ffmpeg的路径可能会根据版本不同，ffmpeg-1007/ffmpeg-linux
> 
> 没错，偶尔 Playwright 会附带一个新的 ffmpeg 版本。到目前为止，已经 1007 年了。
Therefore, it may need to be changed according to the 1007 path if referenced by other programs

**Comment by jw-star** [comment]
If you can fix the directory to remain unchanged, it will be much more convenient

**Comment by dgozman** [comment]
> If you can fix the directory to remain unchanged, it will be much more convenient

I don't think we'll do that, because the cons outweigh the pros.
