### ISSUE TITLE
[Feature] [playwright-vscode] Respect custom testIdAttribute in codegen

### ISSUE THREAD

**Issue by xianshenglu** [microsoft/playwright#18237]
Normally, the generated code can not be used directly. One reason is that the generated selector is not what we want.

Since we have already supported `getByTestId` and `testIdAttribute`, so why not use them in the record and pick selector function if the `testIdAttribute` is set?

**Comment by dgozman** [comment]
@xianshenglu I think codegen should already generate `getByTestId()` calls for you. Could you share a page where this does not happen? Also, what's your playwright version?

**Comment by xianshenglu** [comment]
> @xianshenglu I think codegen should already generate `getByTestId()` calls for you. Could you share a page where this does not happen? Also, what's your playwright version?

playwright@1.27.0
@playwright/test@1.27.0

I have created a repo https://github.com/xianshenglu/playwright-codegen-test-id-issue.  I tested with https://playwright.dev with `testIdAttribute: 'class'`

**Comment by xianshenglu** [comment]
Or you can use `data-ph-id` with https://jobs.microfocus.com/global/en/

**Comment by dgozman** [comment]
@xianshenglu Where do you set `testIdAttribute`? In your config? I think codegen does not respect that.

**Comment by xianshenglu** [comment]
> @xianshenglu Where do you set `testIdAttribute`? In your config? I think codegen does not respect that.

Yes. Any other place I can set `testIdAttribute` to let codegen respect it?

**Comment by aslushnikov** [comment]
This will be fixed in 1.28
