### ISSUE TITLE
[Question] How can I strip project name from snapshot filename creation?

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#18234]
This is as far as I've gotten but TestInfo.file gives the absolute path, how can i just grab fileName of the current test? Or an easier way to strip the project name? I've already removed the suffix platform stuff.

Reason i want this is to use the screenshots for different desktop browsers, I noticed chrome and firefox both pass image comparison even baseline images created on chrome. 

should probably modify the screenshot methods to override typical naming convention:

```export const screenshotPath = testPages.extend<{ _autoSnapshotSuffix: void }>({
  _autoSnapshotSuffix: [
    async ({}, use, testInfo) => {
      testInfo.snapshotDir = `./screenshots/visual/`;
      testInfo.snapshotSuffix = "";
      testInfo.snapshotPath = (name: string) =>
        `${testInfo.snapshotDir}${testInfo.file}-snapshots/${name}`;
      await use();
    },
    { auto: true },
  ],
});```

**Comment by aslushnikov** [comment]
I'll merge this into https://github.com/microsoft/playwright/issues/7792
