### ISSUE TITLE
[BUG] Allowing geolocation permissions does not work in Chromium

### ISSUE THREAD

**Issue by orlyk** [microsoft/playwright#18242]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.15.0
- Browser: Chromium
- Extra: Chromium version 107.0.5304.18 (Developer Build) (x86_64)

**Code Snippet**
```javascript
import { chromium } from '@playwright/test';

async function globalSetup() {
  const baseUrl = 'https://my-location.org/';
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  await context.grantPermissions(['geolocation'], { origin: baseUrl });
  const page = await browser.newPage();
  await page.goto(baseUrl)
  await browser.close();
}
```

**playwright.config.ts**
```javascript
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
```

**Describe the bug**
There is no `Know your location` pop-up in Chromium, but location is disabled for specific site. Works on Desktop Chrome version: 
```javascript
  projects: [
    {
      name: 'chrome',
      use: {
        channel: 'chrome'
      },
    },
  ],
```
<img width="1244" alt="Screenshot 2022-10-21 at 12 00 54" src="https://user-images.githubusercontent.com/5757189/197170216-4c6af0fc-ec18-4b96-898a-d9aa52b48c5b.png">
<img width="1280" alt="Screenshot 2022-10-21 at 12 01 21" src="https://user-images.githubusercontent.com/5757189/197170223-e64c3210-2505-4c3a-9b06-5a27db011edd.png">

**Comment by HoodyStiliyan** [comment]
I can confirm, in fact, this seems to be happening in all browsers and all the latest channels.

**Comment by eriandev** [comment]
I too am trying to enable geolocation as part of a test flow.
```js
import { test, expect } from '@playwright/test'

test.describe('Main flow', async () => {
  test('should allow geolocation', async ({ page, context }) => {
    await page.goto('/')

    const button = page.locator('button').first()
    expect(await button.textContent()).toEqual('I\'m here 🗺️')

    await button.click()
    await context.grantPermissions(['geolocation'], { origin: 'http://127.0.0.1:4173' })
  })
})
```

**Comment by HoodyStiliyan** [comment]
Hello, for me, the solution was to host it on https instead of http. The mdn docs cleary state geo location permision is only accessible inside secure contexts. I guess we overlooked that part :)

**Comment by Prateekdewalya** [comment]
Hi All,

I am also facing this issue with all browsers. Also i used HTTPS but still having same issue.

**Comment by pyprasad** [comment]
Hello All, 

I have the same problem, is there any progress on this issue by any chance ?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by pratiksyngenta** [comment]
Spent almost a day by adding

```
permissions: ['geolocation'],
```
but it was not working as expected 

I tried adding additional line next to it i.e
```
geolocation: { latitude: xx.xx , longitude: xx.xx },
```

and it worked .. 

in playwright.config.js, it looks like 

```
use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    permissions: ['geolocation'],
    geolocation: { latitude: 50.8551729, longitude: 4.340312 },
    ignoreHTTPSErrors: true,
    video: 'retain-on-failure',
    headless: true,
  }
```
