### ISSUE TITLE
[Question] Screenshot difference between mac and ubuntu 

### ISSUE THREAD

**Issue by mokone91** [microsoft/playwright#18240]
Hi! 
I going to setup screenshot testing using @storybook/test-runner + jest-image-snapshot
@storybook/test-runner uses  jest-playwright under the hood, and issue is - screenshots different in various OS.

I understand that this is a normal behavior, different OS renders things differently...
But is its possible to do something to minimize this difference, so i can use some threshold as now its not possible, as it depends on to many factiors?
Seems in my case - difference in fonts and box shadows..

![components-forms-input-test--default-diff](https://user-images.githubusercontent.com/2384641/197167129-3846f2bd-56db-4f76-a961-e27107c0d416.png)

**Comment by mokone91** [comment]
Have to try different cromium flags - but no luck
```
testEnvironmentOptions: {
    'jest-playwright': {
      ...originalConfig.testEnvironmentOptions['jest-playwright'],
      launchOptions: {
        args: [
          '--no-sandbox',
          '--headless',
          '--enable-logging',
          '--hide-scrollbars',
          '--disable-lcd-text',
          '--printBackground=true',
          '--disable-dev-shm-usage',
          '--disable-gpu',
          '--font-render-hinting=none',
          '--disable-accelerated-2d-canvas',
          '--disable-font-subpixel-positioning',
          '--disable-canvas-aa',
          '--disable-composited-antialiasing',
        ],
      },
    },
```

**Comment by dgozman** [comment]
@mokone91 There's not much you can do to get the same screenshots between OSes. You use a container to run your visual tests - this way you'll have a reproducible environment.
