### ISSUE TITLE
[Question] Does getByRole work like locator in vscode?

### ISSUE THREAD

**Issue by yugawara** [microsoft/playwright#18246]
In https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright

See Debug step-by-step, explore selectors

As in the document above, the page.locator.... expression works well with vscode.

However, if I click on getByRole in VSCode, nothing is highlighted.    Is there anything I can  do about this?

**Comment by dgozman** [comment]
@yugawara This works for me with the extension `v0.2.13`. Could you please share a repro we can run locally?

**Comment by yugawara** [comment]
https://github.com/yugawara/workers-cafe/blob/main/workers-memo/playwright/tests/example.spec.ts#L9

While in debug mode, clicking on line 12 and line 13 will highlight the sections.
The same is not true for lines 10 and 11.

(However, line 16 and 17 do work - so once assigned to variables they work??)

**Comment by dgozman** [comment]
@yugawara Hmm... this works for me. Do you click at `getByText()`, or somewhere else in the line 10? Note that you should click somewhere inside the locator expression for it to be highlighted. Perhaps that could be the issue?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
