### ISSUE TITLE
[BUG] debug mode breaks visual regression (event showing mouse icon event on screenshot)

### ISSUE THREAD

**Issue by theillo** [microsoft/playwright#18244]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Windows
- Node.js version: v16.13.2
- Browser: [e.g. All, Chromium, Firefox, WebKit]

**Code Snippet**

test("Smart Frame 1 testing", async ({ page }) => {
  await page.goto("https://smartitnow.blogspot.com/p/e.html");
  await page.mouse.move(700, 400);
  await page.waitForTimeout(4000);
  expect(await page.screenshot()).toMatchSnapshot("scrennshot1.png", {
    maxDiffPixels: 84, // allow no more than 84 different pixels.
  });
  expect(
    await page
      .frameLocator("iframe")
      .getByText(
        "An image (from Latin: imago) is an artifact that depicts visual perception, such"
      )
      .click()
  );
});

**playwright.config.js**
use: {
    browserName: "chromium",
    headless: false,
  },

**Describe the bug**
Generally, the problem is with debugging visual regression. When a mouse event (page.mouse.move (700, 400)) is used in headed mode, seems to be creating a screenshot based on what is visible on the displayed screen including the cursor icon () which causes the build to fail. In the case of the headless mode test, the test runs without complications because it does not detect a mouse event (icons).

An example of such an error while debugging:
![scrennshot1-diff](https://user-images.githubusercontent.com/44233908/197185042-687ac2c8-0855-4cfa-99e1-6bd3b850ccb0.png)

**Comment by dgozman** [comment]
@theillo This is not a mouse cursor, but just some html element being rendered under the mouse by the site. You can try it yourself. I think there might be a race condition, where just running the test happens fast, and site does not render this "cursor", but when you are debugging and moving the mouse around and do it slowly, it does render the "cursor". I don't think we can help in this case.

**Comment by theillo** [comment]
Hmm, I understand, I'll check it again. Sorry for the problem and thank you for your time @dgozman
