### ISSUE TITLE
[BUG] addStyleTag gets unresponsive with polyfilled setImmediate and high parallelity  

### ISSUE THREAD

**Issue by Xiphe** [microsoft/playwright#18243]
### Context:
- Playwright Version: 1.27.1
- Operating System: OSX 12.6 (M1 Max)
- Node.js version: 16.15.1
- Browser: Chromium

### Code Snippet

```js
const playwright = require('playwright');

/* Polyfill 1: This causes instability */
global.setImmediate = (cb) => cb();

/* Polyfill 2: This is also unstable even though it's an elaborate polyfill */
// global.setImmediate = null;
// require('setimmediate');

/* Buildin: This sometimes causes closing of firefox to timeout 🤷 */
// global.setImmediate = setImmediate;

/* Polyfill 3: This works best */
// global.setImmediate = setTimeout;

/* the amount of parallel executions, more means higher chance of failure */
const parallel = 30;

console.log(`Launching ${parallel} parallel contexts`);
console.log(
  Array.from({ length: parallel })
    .map(() => '_')
    .join(''),
);

const cache = {};
async function run(i) {
  const browsername = ['chromium', 'firefox', 'webkit'][i % 3];
  if (!cache[browsername]) {
    cache[browsername] = playwright[browsername].launch();
  }

  const browser = await cache[browsername];
  const context = await browser.newContext();
  const page = await context.newPage();

  await withTimeout(
    page.setContent('<button>Hello World</button>'),
    `Failed to set content in ${browsername} (${i})`,
    5_000,
  );
  await withTimeout(
    /* This causes the timeout */
    page.addStyleTag({ content: 'button { background-color: fuchsia; }' }),
    `failed to add style tag in ${browsername} (${i})`,
    5_000,
  );
  process.stdout.write('.');
}

Promise.all(Array.from({ length: parallel }).map((_, i) => run(i)))
  .then(async () => {
    console.log('\nclosing browsers');
    for (const browsername in cache) {
      const browser = await cache[browsername];
      const contexts = await withTimeout(
        browser.contexts(),
        `Failed to get contexts of ${browsername}`,
      );
      for (const context of contexts) {
        await withTimeout(
          context.close(),
          `Failed to close a context of ${browsername}`,
        );
      }
      await withTimeout(browser.close(), `Failed to close ${browsername}`);
    }
    console.log('Done');
  })
  .catch((err) => {
    console.error('\nERROR:', err);
    process.exit(1);
  });

function withTimeout(promisedValue, message, timeout = 15_000) {
  return Promise.race([
    promisedValue,
    new Promise((_, rej) => setTimeout(() => rej(new Error(message)), timeout)),
  ]);
}
```

### Describe the bug

Seems as if there is a race condition causing unresponsiveness when setImmediate invokes the passed callback too fast.
On my machine the issue can be reproduced quite reliably with the above snippet and `parallel = 30`.

I've also added some variants of setImmediate polyfills that cause the following behaviour on my machine

- Polyfill 1: Most extreme and most unreliable
- Polyfill 2: using the widely used [`setImmediate` npm package](https://github.com/yuzujs/setImmediate) - works better, still unreliable
- Buildin: Works good enough with addStyleTag, sometimes causes firefox to not get closed within 15s on my machine 🤷
- Polyfill 3: Works reliably

### Why is this relevant

My assertion is that this is an edge case not many people will encounter but I've ran into it when [debugging timeouts in jest tests using playwright](https://github.com/microsoft/playwright/issues/18207).

The underlaying issue is that [since jest@27 the jsdom environment comes without setImmediate](https://github.com/facebook/jest/issues/11204), requiring a polyfill. 

If there's nothing you can do about this, I'm 100% fine with polyfilling with `setTimeout` in my tests. But I still wanted to make you aware that there might be a race condition.

**Comment by dgozman** [comment]
@Xiphe I don't think that Playwright is ready for all kinds of `setImmediate` polyfills in the wild. We have [some interesting logic](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/utils/index.ts#L28-L65) around `setImmediate` use.

Playwright should all work with built-in `setImmediate`, and if it does not that's an issue. I think that "firefox no closing within 15s" is unrelated, it just happened at the time you tried this particular `setImmediate`. If you have a consistent repro, we would love to take a look.

**Comment by Xiphe** [comment]
Thanks for the feedback! Absolutely fine with this. I just wanted to share my findings in case someone else might run into this.

**Comment by Xiphe** [comment]
I'll keep an eye on the firefox not closing issue. But currently I cant reproduce that one either.

**Comment by dgozman** [comment]
@Xiphe Thank you! I will close this issue for now. If you'll be able to reproduce the Firefox issue, please file a new bug.
