### ISSUE TITLE
[Question] I can't get tracing to work in the global setup

### ISSUE THREAD

**Issue by moefinley** [microsoft/playwright#18253]
I followed the instructions [here](https://playwright.dev/docs/next/test-advanced#capturing-trace-of-failures-during-global-setup) but my trace file contains no actions.

I've recreated it in a [simple example](https://github.com/moefinley/playwight-does-not-trace-in-global-setup).

In my simple example my global setup creates a locator and performs and action on it. My understanding is both of those count as an "action".

```Typescript
import {chromium, FullConfig, Page} from '@playwright/test';

async function defaultSetup(config: FullConfig) {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await browser.newPage();
    const baseURL = 'https://demo.playwright.dev/todomvc/';

    await context.tracing.start({ screenshots: true, snapshots: true });
    await page.goto(baseURL);
    let input = page.locator('input');
    await input.fill('testing');
    await context.tracing.stop({path: __dirname + '/trace-global.zip'});
}

export default defaultSetup;
```

In the application I'm trying to debug the global setup contains the whole login journey. It runs in a docker container in CI so having the tracing would be a great way to debug it.

Am I doing something wrong or is this a bug?

**Comment by dgozman** [comment]
You should replace
```ts
const page = await browser.newPage();
```
with
```ts
const page = await context.newPage();
```

This will make sure that page is created in the `context` that records the trace later on. Let me know if that helps.

You can also follow #14895 that will make it all automatic for you.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by moefinley** [comment]
Thanks @dgozman that was the solution. Thanks!
