### ISSUE TITLE
[Feature] Create bindings for Rust

### ISSUE THREAD

**Issue by hamza1311** [microsoft/playwright#18266]
## Description

Create Playwright bindings for Rust. There are many web frameworks that enable developers to write entire web applications in Rust, such as [Yew](https://yew.rs/), [Dioxus](https://dioxuslabs.com/), [Sycamore](https://github.com/sycamore-rs/sycamore) and others. It would be beneficial to write tests for these applications in Rust as well.

## Prior work

In no particular order:
- initially suggested in https://github.com/microsoft/playwright/discussions/15050 but no feature request was created.
- testing of Yew components was brought up in https://github.com/microsoft/playwright/issues/17221
- 3rd party bindings were created in [`playwright-rust`](https://github.com/octaltree/playwright-rust) by @octaltree. That, and other efforts have fallen victim to https://github.com/microsoft/playwright/issues/9673

## Current state of testing in Rust

Right now, the way to write end-to-end tests is by using a crate like [thirtyfour](https://crates.io/crates/thirtyfour), which provides access to using the WebDriver APIs directly. This is not optimal for testing as it lacks the testing-specific features that playwright offers, on top of ability to interact with a web driver. Practically, it is equivalent of using Selenium for testing.

Tests are usually written using [wasm-bindgen-test](https://rustwasm.github.io/wasm-bindgen/wasm-bindgen-test/), which provides a low-level API, compared to playwright. It can get the job done for testing small components in isolation and unit testing, however falls apart when end-to-end testing or complex component (integration) testing is needed.

Having access to Playwright would improve the situation drastically.

**Comment by mxschmitt** [comment]
This is unfortunately out of scope for Playwright, so having Playwright for Rust would be more a community driven project, either ran by a person or ran by e.g. https://github.com/playwright-community/

**Comment by darioalessandro** [comment]
Hey @mxschmitt , initially you told @Mbensler that playrwright would handle this as a feature request, are you still open to that? 

<img width="1840" alt="Screen Shot 2022-10-26 at 12 20 23 AM" src="https://user-images.githubusercontent.com/1176339/197941384-c156d46f-f309-41c7-9737-620dcda18bb7.png">

**Comment by padamson** [comment]
See https://github.com/padamson/playwright-rust and https://crates.io/crates/playwright-rs. Would love to get feedback from the community.
