### ISSUE TITLE
[Question] CSS from styled-components is missing (component testing)

### ISSUE THREAD

**Issue by olivier65** [microsoft/playwright#18277]
**Playwright:**
1.27.1

**System**:
    OS: Windows 10 10.0.19044
    Memory: 16.57 GB / 31.67 GB

**Binaries**:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD

Playwright CT mostly works for me except that CSS styles defined using styled-components are not loaded. I know this is more of a Vite issue but googling was not much help and the [Tooling](https://styled-components.com/docs/tooling) page of the styled-components docs has nothing to say about Vite. you happen to know what the problem is?

**Comment by sand4rt** [comment]
Hi @olivier65 could you provide a code example that doesn't work?

**Comment by mxschmitt** [comment]
Closing since there is no repro, please re-file with a small repro otherwise we can't act on it. Thanks!
