### ISSUE TITLE
[Feature] HAR Converter

### ISSUE THREAD

**Issue by kazimir-malevich** [microsoft/playwright#18275]
We have uses who give us HAR files so we can discern the major user flows. 

It'd be nice to have a HAR converter so we can these user flows in Playwright.

The load test tools k6 and Gatling both have HAR converters.

**Comment by mxschmitt** [comment]
Playwright since v1.23 has "context.routeFromHAR", see [here](https://playwright.dev/docs/release-notes#network-replay). Is that what you are looking for?

What do you mean with user flows?

Do you want to use Playwright for load testing?

Please be more specific, what you are trying to accomplish.

**Comment by kazimir-malevich** [comment]
Many apologies and if I could clarify. I would like a utility to convert HAR file requests into actual Playwight scripts which I could then run. But then I am thinking HAR is a network utility and it''s going to be difficult with heavy JavaScript front ends. But it least we could convert the basic requests. Or maybe it is just best sticking to HTTP protocol tools like Gatling or k6 for this kind of thing?

**Comment by mxschmitt** [comment]
HAR is a network file format, it knows nothing about clicks, fills etc.

Maybe codegen works for you? https://playwright.dev/docs/codegen-intro#running-codegen

Closing since HAR -> Playwright scripts is not doable as per above.

**Comment by kazimir-malevich** [comment]
I don't think you're right @mxschmitt. I think it can be done. At the very least we'd need to pre-scan the A-U-T. I'll create a feature branch and submit an MVP.
