### ISSUE TITLE
[Question] How i should intercept request and modify response?

### ISSUE THREAD

**Issue by SRVFLLN** [microsoft/playwright#18276]
Hi! I trying to get a better understanding of how i can use playwright, so i want to figure out how should i intercept request/response and modify it. Before writing this on playwright, i created some tests using cypress:
![image](https://user-images.githubusercontent.com/93190152/197404673-b0b97c08-49e1-4668-bc9d-f3837392a87c.png)
and it's work exatly how i expected. But now i want to create the same tests but on playwright, so after reading the documentation i realized that i should use page.route for interception, so i wrote this code:
![image](https://user-images.githubusercontent.com/93190152/197405489-c4676498-3e3e-4b92-a69f-5a5cefd3de55.png)
If i understand documentation correctly, this code should be able to modify the response, and after which the page should display the message i put in the body of the response. Unfortunatly, after running the test, page which should displayed request results, nothing is displayed, and i can't understand why.
![image](https://user-images.githubusercontent.com/93190152/197405352-0e8f5851-7d86-496a-bc1d-6182af149300.png)

All tests are created for this website: 
https://testpages.herokuapp.com/styled/sync/xhttp-messages.html

**Comment by mxschmitt** [comment]
The following works for me:

```ts
  await page.route('**/*messageset03.json', async route => {
    const response = await page.request.fetch(route.request());
    await route.fulfill({
      response,
      body: JSON.stringify([
        { 'message': 'Playwright!' },
        { 'message': 'Playwright!' },
        { 'message': 'Playwright!' }
      ])
    });
  });
  await page.goto('https://testpages.herokuapp.com/styled/sync/xhttp-messages.html');
  await page.waitForTimeout(50_000);
```

keep in mind that Playwright uses Glob to match request URLs, you can also pass a regular expression instead.

**Comment by mxschmitt** [comment]
Closing as per above, xhr requests are coming asynchronously, so it either waitForTimeout or a playwright assertion (which waits) or page.locator(...).click() (which waits) is required.

**Comment by SRVFLLN** [comment]
Thank you so much, your answer helped me a lot!
