### ISSUE TITLE
[BUG] Unknown file extension ".ts" on fresh init when adding `"type": "module"`

### ISSUE THREAD

**Issue by pleek91** [microsoft/playwright#18282]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.5.0
- Browser: N/A
- Extra: N/A

## System:
 - OS: macOS 12.6
 - Memory: 89.59 MB / 16.00 GB
## Binaries:
 - Node: 16.5.0 - ~/.nvm/versions/node/v16.5.0/bin/node
 - npm: 8.3.0 - ~/.nvm/versions/node/v16.5.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

N/A

**Describe the bug**

In a completely empty directory I ran `npm init playwright@latest`, and chose

```
✔ Do you want to use TypeScript or JavaScript? · TypeScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · false
```
Then I ran `npx playwright test` and everything ran correctly. 
Then I added `"type": "module"` to my package.json and ran `npx playwright test` again. 

Received this error
```
TypeError: Unknown file extension ".ts" for /Users/my-name/Development/playwright-ts-bug/playwright.config.ts
```

**Comment by mxschmitt** [comment]
Works for me - I can't repro! Can you make sure that you use Node.js 16+? I saw you wrote that you are using a recent one, but type: module support is only supported in Playwright in 16+.

**Comment by pleek91** [comment]
My node version is 16.5.0 so that should be fine right?

**Comment by mxschmitt** [comment]
It actually needs to be a more recent one, like v16.18.0.

**Comment by pleek91** [comment]
Okay, I'll update node and try that again when I have a chance. Thank you! I'll close this issue.

**Comment by acdcjunior** [comment]
I got this error in a monorepo where the package with TS tests had `"type": "module",` and playwright was installed in the root.

Setting `"type": "module",` in the root as well fixed the problem.

I don't have non  `"type": "module",`  packages, so take it with a grain of salt.

**Comment by diegohaz** [comment]
I'm also seeing this error on a monorepo project. The packages with the test files are marked with `"type": "module"`. But, unfortunately, I can't set `"type": "module"` to the root package, where the `playwright.config.ts` file is.

It would be nice if Playwright implemented a flag or something to force it to run as ESM even without `"type": "module"` or maybe detect it automatically by reading a `playwright.config.mts` file (notice the `.mts` extension).

The workaround I found was running playwright with an ESM loader (make sure to install `esm-loader-typescript`):
```sh
NODE_OPTIONS=--loader=esm-loader-typescript playwright test
```

**Comment by Simonwep** [comment]
Any update on this one? This is still an issue... and I'm not sure what is the recommended workaround for that.

**Comment by M-51** [comment]
If you still have this problem, try to add `playwright.config.ts` file (even empty!) to directory where `package.json` of your project is.
I have no idea why it works this way.

I had simple project, I didn't need complex configuration, so I skipped config file (as far as I know it is not required), but was getting `TypeError: Unknown file extension ".ts"` error.

Then added empty `playwright.config.ts` - and it works...

If you have monorepo, every project needs to have own config file.
One `playwright.config.ts` in root of monorepo is not enough.

**Comment by morganney** [comment]
Why is this closed?
