### ISSUE TITLE
[BUG] CT Svelte: functions as props do not return correctly (duplicate)

### ISSUE THREAD

**Issue by pooledge** [microsoft/playwright#18281]
**Context:**
- Playwright CT Version: [1.26.1]
- Operating System: [e.g. Mac]
- Node.js version: [e.g. 16.15.0]
- Browser: [tested in FF]

```typescript
const component = await mount(CustomSelect, {
	props: {
		prepare: (option) => option.label
	}
});
```

**Describe the bug**

This issue has been discussed [here](https://github.com/microsoft/playwright/issues/17254), but it's quite blocking since the function output is crucial for the component itself.

For `option` being `{id: 1, label: 'Foo'}` does not return `Foo`, is logged as `(...args) => { window['__ct_dispatch'](ordinal, args); }`, however returns `undefined` instead of an empty string in the above issue.

If a viable workaround exists, it'd be great if someone could provide a minimum example, thank you.

**Comment by mxschmitt** [comment]
The best workaround is to use a wrapper component and rely either data from there or from beforeMount: https://playwright.dev/docs/next/test-components#hooks

Since Browser communication is asynchronous, this is not working as of today.

**Comment by mxschmitt** [comment]
Closing since this is a known limitation of Playwright component testing as of toda see https://github.com/microsoft/playwright/issues/17254#issuecomment-1245063476y, we are working on making this better understandable or working around it.
