### ISSUE TITLE
Record video retain-on-failure with launchPersistentContext

### ISSUE THREAD

**Issue by aronzvi** [microsoft/playwright#18289]
Hey guys,

I'm testing a chrome extension using a test fixture to set the context as specified at [https://playwright.dev/docs/next/chrome-extensions#testing](https://playwright.dev/docs/next/chrome-extensions#testing)

I'd like to record and retain video on failure and I set the video mode to 'retain-on-failure' in my PlaywrightTestConfig as specified at [https://playwright.dev/docs/next/videos#record-video](https://playwright.dev/docs/next/videos#record-video) and this appears to not work for me. Furthermore, it seems that other video modes in PlaywrightTestConfig are ignored as well.

How can I use launchPersistentContext and record video on failure?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11833
