### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RJJ95** [microsoft/playwright#18299]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux
- Node.js version: 16
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
import { AzureFunction, Context, HttpRequest } from "@azure/functions";
const { chromium } = require("playwright-chromium");

const httpTrigger: AzureFunction = async function (
  context: Context,
  req: HttpRequest
): Promise<void> {
  try {
    const browser = await chromium.launch();
    await browser.close();

    context.bindings.res = {
      status: 200,
      body: {
        message: "success",
      },
      headers: { "Content-Type": "application/json" },
    };
  } catch (error) {
    context.bindings.res = {
      status: 500,
      body: {
        error: error,
      },
      headers: { "Content-Type": "application/json" },
    };
  }
};

export default httpTrigger;

```

**Describe the bug**

Add any other details about the problem here.

I'm trying to run Playwright from an Azure function using Node 16 and Typescript. I have an HTTP trigger which seems to be working fine. I can call it, but I'm getting back a 500 message. I see the following error in the logs:

Result: Failure Exception: browserType.launch: Executable doesn't exist at /home/site/wwwroot/node_modules/playwright-core/.local-browsers/chromium-1028/chrome-linux/chrome ╔═════════════════════════════════════════════════════════════════════════╗ ║ Looks like Playwright Test or Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers: ║ ║ ║ ║ npx playwright install ║ ║ ║ ║ <3 Playwright Team ║ ╚═════════════════════════════════════════════════════════════════════════╝ Stack: browserType.launch: Executable doesn't exist at /home/site/wwwroot/node_modules/playwright-core/.local-browsers/chromium-1028/chrome-linux/chrome ╔═════════════════════════════════════════════════════════════════════════╗ ║ Looks like Playwright Test or Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers: ║ ║ ║ ║ npx playwright install ║ ║ ║ ║ <3 Playwright Team ║ ╚═════════════════════════════════════════════════════════════════════════╝ at Object.<anonymous> (/home/site/wwwroot/dist/test/index.js:15:40) at /home/site/wwwroot/dist/test/index.js:8:71 at __awaiter (/home/site/wwwroot/dist/test/index.js:4:12) at Object.httpTrigger [as default] (/home/site/wwwroot/dist/test/index.js:14:12) at p.<anonymous> (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:29095) at o (/azure-functions-host/workers/node/dist/src/worker-bundle.js:2:26973)

Now I checked the interwebs, and I already switched from Windows to Linux, and from Node version 14 -> 16. I'm getting the same error again and again. I followed this guide: https://dotnetthoughts.net/running-playwright-on-azure-functions/, where the author is using Node 12, but I'm not allowed to anymore by Azure.

I also set up the env variable PLAYWRIGHT_BROWSERS_PATH to 0, but that also doesn't work. How should I proceed here?

**Comment by mxschmitt** [comment]
How did you set the `PLAYWRIGHT_BROWSERS_PATH`?

Did you create an app setting?

**Comment by mxschmitt** [comment]
Looks like you have set the environment variable correctly, otherwise it would not look for browsers inside your node_modules directory.

My guess is that your host OS where you deploy it is different to the OS where your Azure Function is running, so it adds the Chromium browser for macOS into your `node_modules` folder but you are using Linux inside the Azure functions.

Due the dependency constraints and challenges with making the browser available inside the Azure Function (since they get installed inside ~/.cache usually either with a postinstall script or via `npx playwright install`), we recommend using the Docker image instead: https://playwright.dev/docs/docker

**Comment by RJJ95** [comment]
Thanks for your reply! I've been able to fix this by setting an Azure Function env variable. It works now. Thanks for your help!

**Comment by jaskomesanovic** [comment]
@RJJ95  can you please share which Azure Function env variable did you set. I am having the same problem. Thanks in advance.

**Comment by saurabhabh** [comment]
@RJJ95  Can you please share the change you did ? I am facing the same issue. @jaskomesanovic were you able to fix the issue ?

**Comment by cjgaspari** [comment]
> Thanks for your reply! I've been able to fix this by setting an Azure Function env variable. It works now. Thanks for your help!

which env variable did you change in Azure functions that allowed you to get this to work? I'm having the same issue. 

@jaskomesanovic @saurabhabh were you able to figure it out?

**Comment by saurabhabh** [comment]
Hi @cjgaspari What I did to make it work was that I created a docker image, added the chrome-linux folder to the docker image, you can download the chrome-linux executable from the below link  -
https://download-chromium.appspot.com/?platform=Linux_x64&type=snapshots

Changed the puppeteer launch command to 
 await puppeteer.launch({headless: true, executablePath: "./chrome-linux/chrome", args: ['--no-sandbox']});

and published this docker image to the Azure functions. This way there is no need to make use  of the instance installed in cache.

**Comment by cjgaspari** [comment]
@saurabhabh thank you, I just might have to try that approach!
