### ISSUE TITLE
[BUG] Codegen should generate getByLabel when <label> with for is used

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#18297]
This
<img width="871" alt="image" src="https://user-images.githubusercontent.com/17984549/197603469-085519a4-e4aa-4944-8c44-d4da6a03a954.png">

generates getByText instead of getByLabel when clicking on the checkbox

URL: https://demo.playwright.dev/todomvc/#/

**Comment by dgozman** [comment]
In this example, the target element is `<label>`, so `getByLabel()` is not going to work because it targets the associated control instead.

Overall, we already generate `getByLabel()` and prioritize it over `getByText()`.
