### ISSUE TITLE
[BUG]. Playwright 1.27.1 npx playwright install fails with unable to get certificate

### ISSUE THREAD

**Issue by stixaw** [microsoft/playwright#18293]
**Context:**
- Playwright Version: 1.27.1
- Operating System: [MAC M1 with 12.6]
- Node.js version: [14.20.1]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [New Mac M1]

## System:
 - OS: macOS 12.6
 - Memory: 2.71 GB / 32.00 GB
## Binaries:
 - Node: 14.20.1 - ~/.nvm/versions/node/v14.20.1/bin/node
 - npm: 6.14.17 - ~/.nvm/versions/node/v14.20.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
**Code Snippet**
``` bash
npx playwright install Fails to install any of the browsers
```

**Describe the bug**
Error: unable to get local issuer certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket._finishInit (_tls_wrap.js:937:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12) {
  code: 'UNABLE_TO_GET_ISSUER_CERT_LOCALLY'
}
Failed to install browsers
Error: Failed to download Chromium 107.0.5304.18 (playwright build v1028), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (/Users/anwillia/dev/pde-ui/node_modules/@playwright/test/node_modules/playwright-core/lib/server/registry/download.js:51:16)
    at ChildProcess.emit (events.js:400:28)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:285:12)
    
    Add any other details about the problem here.

**Comment by mxschmitt** [comment]
Looks like your system and by that Node.js, does not trust the Azure CDN certificate. You can get the download URL by setting the `DEBUG=pw:install` to debug it further.

Are you behind a corporate environment?

Useful might be https://github.com/microsoft/playwright/issues/5636#issuecomment-920558210 or our guide for using Playwright behind a Firewall: https://playwright.dev/docs/browsers#install-behind-a-firewall-or-a-proxy where you have to set your custom certificate certificate storage.

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues!
