### ISSUE TITLE
[Question] Problems on firing get request followed by put request

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#18315]
Hi, hope you can help me.

I'm trying to fire two request, one get request whose part of the0 result is used as a param for a put request. I'm using right now the APIRequestContext in this way: 

```ts
    let apiContext: APIRequestContext;
    let token = auth['access_token'];
        apiContext = await request.newContext({
            baseURL: signinUrl,
            extraHTTPHeaders: {
                'Authorization': "Bearer " + token
            }
        });

        const load_settings = async(apiContext: APIRequestContext) => apiContext.get(`*endpoint*`, {
            failOnStatusCode: true,
            params: {
                "usr": `${username}`
            }
        }).then(r => r.json())
            .then(async (r) => {
                const key = r[0]?._key;
                if (!key)
                    throw new Error("Invalid key");
                return await apiContext.put(`*endpoint*/${key}`, {
                    headers: {
                        "Content-Type": "application/json"
                    },
                    failOnStatusCode: true,
                    data: {
                        *some data*
                    }
                })
                .then(r => r.json())
                .then(r => console.log(`${username} User settings successfully loaded!`))
                .catch(e => console.log('Put error', e));
    
            }).catch((e) => {
                console.log('Get error', e);
            });


    await page.goto(signinUrl + '/home');
    await load_settings (apiContext);
```

These are requests that should be fired everytime I launch my automated tests, and those requests can success if my user has already   authenticated. Said that I've already checked that I am already authenticated by the time I call this function, I'm encountering some problems when I launch multiple tests one after another:

1) I cannot see my requests in the Network Tab when the script fires them, so I can't be sure if my service Worker is intercepting them;
2) After the first test, I encounter this error: 

`apiRequestContext.get: 503 Service Unavailable
=========================== logs ===========================
→ GET *url_path_with_endpoint*
  user-agent: Playwright/1.26.1 (x64; windows 10.0) node/16.16
  accept: */*
  accept-encoding: gzip,deflate,br
  authorization: Bearer *token*
← 503 Service Unavailable
  cache-control: no-cache, no-store, max-age=0, must-revalidate
  content-length: 172
  content-type: application/json
  expires: 0
  pragma: no-cache
  referrer-policy: no-referrer
  vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
  x-content-type-options: nosniff
  x-frame-options: DENY
  x-xss-protection: 1 ; mode=block
  date: Tue, 25 Oct 2022 14:17:04 GMT
  connection: close`

and this is something that never happened to me..can someone help me? Am I badly writing these requests? For me is really a problem because in this way I cannot run my entire tests list. Thank you!!

**Comment by mxschmitt** [comment]
> I cannot see my requests in the Network Tab when the script fires them, so I can't be sure if my service Worker is intercepting them;

These requests are mode on the Node.js side, that's why you don't see them in the devtools of the browsers.

If you use page.request or context.request then the cookies get automatically added to the browsercontext/page. Thats what Playwrights request api makes special.

> After the first test, I encounter this error:

This means that the server you are making a request to responds with a 503 response which means that its not available, thats not an issue on Playwright side, often just an outage.

**Comment by DvDream** [comment]
> > I cannot see my requests in the Network Tab when the script fires them, so I can't be sure if my service Worker is intercepting them;
> 
> These requests are mode on the Node.js side, that's why you don't see them in the devtools of the browsers.
> 
> If you use page.request or context.request then the cookies get automatically added to the browsercontext/page. Thats what Playwrights request api makes special.
> 
> > After the first test, I encounter this error:
> 
> This means that the server you are making a request to responds with a 503 response which means that its not available, thats not an issue on Playwright side, often just an outage.

Just to be more specific, we use a Service worker to inject jwt token in order to authenticate our requests.. instead, in that way I suppose that my requesta are not passing through the service Worker, so how can this problem be overcome?

**Comment by mxschmitt** [comment]
Can you give more context what you are trying to achieve? [APIRequestContext](https://playwright.dev/docs/api/class-apirequestcontext) does requests on Node.js side, it knows nothing about ServiceWorkers etc.

Unrelated to that, I recommend to read into [async/await vs. .then/catch](https://dev.to/masteringjs/using-then-vs-async-await-in-javascript-2pma.).

**Comment by DvDream** [comment]
> Can you give more context what you are trying to achieve? [APIRequestContext](https://playwright.dev/docs/api/class-apirequestcontext) does requests on Node.js side, it knows nothing about ServiceWorkers etc.
> 
> Unrelated to that, I recommend to read into [async/await vs. .then/catch](https://dev.to/masteringjs/using-then-vs-async-await-in-javascript-2pma.).

Hi, What I'm trying to do is to send authenticated request to get and put data. These request are performed upon being logged in. Since I don't wanna perform the login operation everytime I run my test scripts, firs I inject a jwt Token into my IndexedDB so that I am already authenticated when I navigate in the home page of the web application (and this is work fine as expected). Every request here is intercepted by our service worker that authenticate the requests. It seems that with APIRequestContext the request that I fire are not intercepted by it  as you said, so everytime I try to do that, now I receive 401 as error. Is it a bit more clear now? :)

**Comment by mxschmitt** [comment]
Unfortunately it's not clearer! What does exactly not work and is there a chance for a repro? Otherwise we can't act on it.

API testing, aka. page.request has nothing to do with Service Workers, since the requests happen on the Node.js side.

**Comment by aslushnikov** [comment]
@DvDream this thread has quite some discussion! Could you please re-file with a repro that we can run locally and see what exactly not working?

Thanks!
