### ISSUE TITLE
[BUG] Redirecting in an intercepted response does not work on Webkit

### ISSUE THREAD

**Issue by janhesters** [microsoft/playwright#18318]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: v16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
- Browser: Webkit
 - OS: macOS 12.5.1
 - Memory: 66.27 MB / 32.00 GB
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
       <form method="post" route="/some-route">
         <button type="submit">Force redirect</button>
       </form>
    </div>
  `);

   await page.route('/some-route', route => {
     return route.fulfill({
       headers: { ...route.request().headers(), Location: '/' },
       status: 302,
     });
   });

   await page.getByRole('button', { name: /force redirect/i }).click();
})();
```

**Describe the bug**

The error that Webkit throws is:

```
route.fulfill: Cannot fulfill with redirect status: 302
```

Is there a different way to redirect in an intercepted `page.route` with Playwright, so it works on Webkit?

**PS:**

[It looks like](https://github.com/microsoft/playwright/blob/f91e41ef400c09fe9a0b86872a87415f652993a8/tests/page/page-route.spec.ts#L531), currently this behavior is intended 😕

**Comment by mxschmitt** [comment]
Can you use instead of the redirect response directly use the final response? Would that work for you?

**Comment by mxschmitt** [comment]
Closing as per above since supporting redirected responses is not planned as of today. We recommend working it around by directly returning the actual response.

**Comment by mauriceackel** [comment]
@mxschmitt Can you elaborate why this is not planned to be supported? My test setup requires to mock a redirect in order for the client to navigate to another page (i.e. oauth flow). To test the whole auth flow, I need to redirect back to my page after I "opened the auth page".

Is there any workaround?

**Comment by schinckel** [comment]
I agree. This flow (required by OAuth flows) works in Playwright in other browsers, but not WebKit.

I'm using Playwright, in conjunction with python-level request mocking, to prove that an OAuth flow matches the specification (ie, that the redirects happen as defined). 

There is a workaround, where you can fulfill with a different status code, but then have the test case manually redirect, but this required a bunch of custom handling and then lots of comments...

**Comment by iulspop** [comment]
Same, mocking oauth flow to test login page. Why would this not work only on WebKit?

**Comment by mxschmitt** [comment]
@iulspop please file a separate issue with your use-case, thanks!
