### ISSUE TITLE
[BUG] Error messaging in VS Code extension for getByRole

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#18313]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Change example test to have a role of button instead of link and run test using vs code extension.

```js
await page. getByRole ("button", { name: "Get Started" }) .click() ;
```

<img width="1235" alt="Screenshot 2022-10-25 at 15 32 25" src="https://user-images.githubusercontent.com/13063165/197788225-b8d6c726-5029-4211-be6f-ed400bafc3e7.png">

**Describe the bug**

debugging error messaging in VS Code not clear - pending operations where as running in terminal the log shows better error message or at least points in the right direction.

<img width="1235" alt="Screenshot 2022-10-25 at 15 34 07" src="https://user-images.githubusercontent.com/13063165/197788454-d4db7c1a-d07d-4170-84a9-30cddba9259b.png">

**Comment by mxschmitt** [comment]
I can't repro, could you provide me the full test file?

<img width="932" alt="image" src="https://user-images.githubusercontent.com/17984549/197844060-b3123cb4-0838-4b4b-ad48-4150e031f413.png">

**Comment by debs-obrien** [comment]
I can't reproduce anymore either. now constantly getting browser has been closed. Am trying to show that we have good error messages in vs code like before but not finding a good example to show case this. If someone choses the wrong locator or someone in code changes the button to a link or vice versa the test should pick up that no such locator exists rather than the browser has been closed.

In terminal it logs this message quite well so I guess on CI it would be easily seen but when developing with vscode the error message isn't the same as that of terminal and isnt very helpful so how can we improve this.

**Comment by weyert** [comment]
Yes, I am see the same issue when trying to use `getByRole` within the Code extension. Same code works fine when running from the command-line

**Comment by aslushnikov** [comment]
@weyert this one seems to be stale since we can't repro any more. Let me close this one.

Could you please file a new issue with a repro?
