### ISSUE TITLE
[Feature] Support Debian 11 arm

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#18319]
Debian amd is supported, but not arm.

Depends on https://github.com/microsoft/playwright/issues/19987.

**Comment by vskatusa** [comment]
Please support Debian 11 arm64

**Comment by ltsuda** [comment]
> Please support Debian 11 arm64

Please, upvote the first comment in this issue.

**Comment by nhooyr** [comment]
Yea looks like it's going to be in 1.31 instead.
