### ISSUE TITLE
[BUG] Microsoft.Playwright.PlaywrightException: Element is outside of the viewport

### ISSUE THREAD

**Issue by fikaa14** [microsoft/playwright#18312]
I have a disabled button that contains a span element inside of it with a little icon, I'm trying to test click on that span element, like this
![2022-10-25_09h57_45](https://user-images.githubusercontent.com/95932487/197716789-a61aaedb-3f82-4f26-b6f5-1985d8abffbb.png)
but I get this error Microsoft.Playwright.PlaywrightException: Element is outside of the viewport, when it's clearly not outside because I can see it, that little arrow pointing down is an element I should click
![2022-10-25_09h54_05](https://user-images.githubusercontent.com/95932487/197716975-1b638096-534e-44c0-894b-daa8a0249215.png)
The problem is I can not put some id to that element because it is auto-generated by angular, and here is how the html looks like
![2022-10-25_10h01_50](https://user-images.githubusercontent.com/95932487/197717673-ace9adb5-fc50-47fb-9bea-fa51215a0169.png)

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

Maybe you have the wrong element selected - and the one which is selected is outside of the viewport? I'd recommend to use `Page.PauseAsync()` then the Playwright Inspector will come up and you can inspect your selectors.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
