### ISSUE TITLE
[BUG] Unexplained Target Closed when running page.waitForSelector

### ISSUE THREAD

**Issue by JonWallsten** [microsoft/playwright#18320]
**Context:**
- Playwright Version: 1.26.0
- Browser:  Chromium

**System:**
 - OS: Windows 10 10.0.19044
 - Memory: 14.18 GB / 31.85 GB
 
**Binaries:**
 - Node: 16.17.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD  
 - npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD

** Config: **
```
import { PlaywrightTestConfig } from '@playwright/test';
import * as puppeteer from 'puppeteer';

const whiteListDomains = '*****';
const chromiumFlags = [
    '--auth-negotiate-delegate-whitelist='+whiteListDomains,
    '--auth-schemes="basic,ntlm,negotiate"',
    '--auth-server-allowlist='+whiteListDomains,
    '--auth-server-whitelist='+whiteListDomains,
    '--disable-dev-shm-usage',
    '--disable-extensions',
    '--disable-setuid-sandbox',
    '--no-sandbox',
    '--window-size=1920,1200'
];


const config: PlaywrightTestConfig = {
    testDir: './src',
    testMatch: /.*(e2e-spec)\.(js|ts|mjs)/,
    timeout: 50 * 1000,
    expect: {
        timeout: 30 * 1000
    },
    fullyParallel: false,
    forbidOnly: !!process.env.CI,
    retries: 0,
    workers: process.env.CI ? 3 : undefined,
    reporter: [['html', { outputFolder: '.test_results/test_report' }]],
    use: {
        actionTimeout: 0,
        trace: process.env.CI ? 'retain-on-failure' : 'on',
        screenshot: process.env.CI ? 'only-on-failure' : 'on',
        video: process.env.CI ? 'retain-on-failure' : 'on'
    },
    projects: [
        {
            name: 'chromium',
            use: {
                browserName: 'chromium',
                launchOptions: {
                    args: chromiumFlags,
                    executablePath: process.env.CI ? puppeteer.executablePath() : undefined
                }
            }
        }
    ],
    outputDir: '.test_results/output'
};

export default config;
``` 
**Code Snippet**

```typescript
// This is a simplification of the code since we use a service to call these. But as you can see in the tracer screenshot, these are the only three only three lines that has something to do with Playwright.
test.beforeAll(async ({ browser }) => {
    const page = await browser.newPage();
    await page.goto('https://ourdomain.com/#/search-objects', { timeout: 60000 });
    await page.waitForSelector('.app-title');
});
```

**Describe the bug**

We have an issue where a simple beforeAll hook where we setup at page fails.
It works when I run the tests locally, it works when I only run these tests, but as soon as I run them at the same time as our other application's E2E tests they fail. And how they fail makes no sense what so ever.
We have 5 test files running in parallel, and they all fail at the same line with the same error.
Here's a screenshot from the tracer:
![image](https://user-images.githubusercontent.com/5993909/197833196-6f476a8d-662c-4865-a6e6-5de89c7dfc42.png)

And here's one from the report:
![image](https://user-images.githubusercontent.com/5993909/197834035-84469bbd-b351-4829-a690-c25339bfcfbb.png)

From this we can deduct a few things:
The page seems to be working. 
The selector I'm looking for is clearly there if you look in the code.
It always fail taking a screenshot, so I can't really say for sure the page is really loaded, but since the tracer shows the code it should be loaded.
It says `Target closed` which according to the source code can one of many different issues.

I don't even now how to begin debugging this since it's such a simple code/test and it fails so consistently when I'm running it together with our other tests and works so consistently when running it locally and without other test running this. Is the page somehow crashing? Is there a proxy issue? Please point me in the right direction here.

**Comment by mxschmitt** [comment]
I see that you are using Puppeteer and Playwright together and passing a lot of custom arguments, we unfortunately can't act on it, we need a full repro which we can run locally.

**Comment by JonWallsten** [comment]
@dgozman : Do mind taking a quick look at this? I really need some pointer as to why the browser just gives up. It would be good to find out if it crashes or just closing.
Here's the log:
```
09:03:14    pw:api => browserType.launch started +0ms
09:03:14    pw:api <= browserType.launch succeeded +81ms
09:03:14    pw:api => browser.newPage started +3ms
09:03:14    pw:api <= browser.newPage succeeded +8ms
09:03:14    pw:api => tracing.start started +6ms
09:03:14    pw:api <= tracing.start succeeded +4ms
09:03:14    pw:api => browser.newPage started +1ms
09:03:14    pw:api <= browser.newPage succeeded +41ms
09:03:14    pw:api => page.goto started +3ms
09:03:14    pw:api navigating to "https://*****.com/oas/analyses/#/search-objects?uiEnvId=10&uiEnv=test", waiting until "load" +7ms
09:03:14    pw:api   "commit" event fired +260ms
09:03:14    pw:api   navigated to "https://*****.com/oas/analyses/#/search-objects?uiEnvId=10&uiEnv=test" +1ms
09:03:15    pw:api   "networkidle" event fired +878ms
09:03:15    pw:api   navigated to "https://*****.com/oas/analyses/#/search-objects?uiEnvId=10&uiEnv=test" +217ms
09:03:15    pw:api   "domcontentloaded" event fired +0ms
09:03:15    pw:api   "load" event fired +94ms
09:03:15    pw:api <= page.goto succeeded +9ms
09:03:15    pw:api => page.waitForSelector started +1ms
09:03:15    pw:api waiting for selector ".app-title" to be visible +2ms
09:04:12    pw:api => page.screenshot started +48s
09:04:12    pw:api taking page screenshot +16ms
09:04:12    pw:api <= page.screenshot failed +5s
09:04:12    pw:api => tracing.stopChunk started +2ms
09:04:12    pw:api <= tracing.stopChunk succeeded +66ms
09:04:12    pw:api => tracing.stopChunk started +1ms
09:04:12    pw:api <= tracing.stopChunk succeeded +1ms
09:04:12    pw:api => tracing.stopChunk started +2ms
09:04:12    pw:api <= tracing.stopChunk succeeded +1ms
09:04:12    pw:api => browser.close started +3ms
09:04:12    pw:api <= page.waitForSelector failed +9ms
09:04:12    pw:api <= browser.close succeeded +23ms
```
Here's the trace I put in `_onClosed` in `playwright-core\src\server\chromium\crConnection.ts` 
```
Trace: Browser disconnected
09:04:12      at CRSession._onClosed (/opt/oas/jenkins/slave/workspace/_Components_OAS_oas-web_debug-pw/node_modules/playwright-core/lib/server/chromium/crConnection.js:249:66)
09:04:12      at CRConnection._onMessage (/opt/oas/jenkins/slave/workspace/_Components_OAS_oas-web_debug-pw/node_modules/playwright-core/lib/server/chromium/crConnection.js:107:17)
09:04:12      at Immediate._onImmediate (/opt/oas/jenkins/slave/workspace/_Components_OAS_oas-web_debug-pw/node_modules/playwright-core/lib/server/pipeTransport.js:84:42)
09:04:12      at processImmediate (node:internal/timers:466:21)
```

**Comment by JonWallsten** [comment]
Turn out Chrome was crashing. Some missing sub dependencies on our build server.

**Comment by JonWallsten** [comment]
Maybe some message about the Browser closing unexpectedly would be nice so it's easier to understand what's going on. 
Should at least be in the debug output.

**Comment by dgozman** [comment]
@JonWallsten Perhaps if you run with `DEBUG=pw:browser`, it will have more information. I am sorry that's not at all obvious, we'll try to improve the situation.

**Comment by JonWallsten** [comment]
@dgozman Cool! I will try that and crash the browser deliberately so see what we can get, in case it happens again in the future. Thanks!
