### ISSUE TITLE
[Question]electron.launch: The "file" argument must be of type string. Received an instance of Object

### ISSUE THREAD

**Issue by LuHugo** [microsoft/playwright#18336]
### main.js
```javascript
const { BrowserWindow, app,ipcMain } = require("electron");
const path = require('path');
const playwright = require('playwright');


const createWindow = async () => {
    const win = new BrowserWindow({
        width: 800,
        height: 600,

        webPreferences: {
            preload: path.join(__dirname, 'preload.js'),
        }
    });
    
    // ipcMain
    ipcMain.handle('run', async () => {
        try {
            console.info('starting');

            const electronApp = await playwright._electron.launch({ args: ['demo.js'] });
            const window = await electronApp.firstWindow();
            await window.screenshot({ path: 'google.png' });

            await electronApp.close();
        } catch (error) {
            console.log(error.message)
        }
    });
    
    win.webContents.openDevTools();
    win.loadFile('index.html');
};
```

### preload.js
``` javascript
const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('versions', {
  node: () => process.versions.node,
  chrome: () => process.versions.chrome,
  electron: () => process.versions.electron,
  //invoke
  start: () => ipcRenderer.invoke('run')
})

```
### renderer.js
```javascript
    document.querySelector('button').addEventListener('click',async (el)=>{
        el.target.innerHTML = 'Starting'
        const response = await window.versions.start()||'error';
        el.target.innerHTML = response
    })

```

There is a button in the page of the electron application, when I click the button in the page, it triggers the handle in ipcMain to use playwright._electron.launch to start electron, but I get the following error message. This code is not testing the electron application itself.

The documents I found are all examples of testing the electron application itself, is playwright in electron can only test the electron application itself and not as a launcher

```bash
electron.launch: The "file" argument must be of type string. Received an instance of Object
```

**Comment by mxschmitt** [comment]
Can you share a full repro in form of a git repository? Since the code above is not runnable.

**Comment by LuHugo** [comment]
> Can you share a full repro in form of a git repository? Since the code above is not runnable.

[https://github.com/LuHugo/playwright-electron-demo](https://github.com/LuHugo/playwright-electron-demo)

Run the project and click the `Automate` button in the application

**Comment by mxschmitt** [comment]
Since you run inside Electron, you need to specify `executablePath` inside your `electron.launch({ executablePath: require('electron').app.getPath('exe') })` then it's working for me.

**Comment by LuHugo** [comment]
@mxschmitt Thanks, it works after adding this property.
