### ISSUE TITLE
[BUG] Cannot set proxy to playwright running on electron.

### ISSUE THREAD

**Issue by kurohoan** [microsoft/playwright#18337]
https://playwright.dev/docs/network#http-proxy
I have set up a proxy as described above, but an error message "page cannot be displayed" appears on the chrome screen.
This is exactly the same error I get when I am not connected to the internet.

There must be nothing wrong with the settings, but is there any way to find out the cause of the error?
The proxy itself is working fast on another tool.

I have installed electron from the vue cli as follows, and the version of electron is "13.6.9".

https://nklayman.github.io/vue-cli-plugin-electron-builder/

**Comment by mxschmitt** [comment]
It's not possible to set a http proxy with Electron as of today as you can see [here](https://playwright.dev/docs/api/class-electron#electron-launch). How did you do it since you wrote about that you configured it?

Can you maybe share a bit of code for it?

**Comment by kurohoan** [comment]
The situation of starting up CHROMIUM from ELECTRON.

The process of obtaining the use_proxy object in the code below was omitted, but the contents were stored without any problems.
Is the proxy set up in the correct way?

`
const { chromium } = require('playwright-extra')

const browser_option = {
  headless: false,
  ignoreHTTPSErrors: true,
  executablePath: chrome_path,
  slowMo: 20,
  args: [
    '--no-sandbox',
    '--disable-web-security',
    '--disable-features=IsolateOrigins,site-per-process',
    '--flag-switches-begin --disable-site-isolation-trials --flag-switches-end',
    '--disable-features=AudioServiceOutOfProcess',
  ]
};

browser_option.proxy = {
  server: use_proxy.host + ':' + use_proxy.port,
  user: use_proxy.user,
  password: use_proxy.pass,
};

const page_option = {
  bypassCSP: true,
  userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36',
  extraHTTPHeaders: {
    'Accept-Language': 'ja'
  }
};

browser = await chromium.launch(browser_option)
page = await browser.newPage(page_option);
`

**Comment by mxschmitt** [comment]
Yes looks good, you can specify proxy on the launch and context level. Does it work for you?

See here: https://playwright.dev/docs/network#http-proxy

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues / have questions.
