### ISSUE TITLE
[Feature]: Show my own code in the codeframe

### ISSUE THREAD

**Issue by kentcdodds** [microsoft/playwright#18330]
Could this codeframe ignore node_modules and show my own code in the codeframe? 

I'm fine with it showing where the error was actually created, but I'd like the codeframe to be my own code.

![unknown](https://user-images.githubusercontent.com/1500684/197889171-8c36ddd3-643c-4203-8517-00fc3912b232.png)

Jest does it this way. I even wrote about how I fix my own errors to put the code frame where I want it: https://kentcdodds.com/blog/improve-test-error-messages-of-your-abstractions

Thanks!

**Comment by mxschmitt** [comment]
I can repro:

```js
// node_modules/foo/index.js
module.exports = {
  foo: () => {
    throw new Error('foo!');
  },
}
```

and put this inside the test:

```ts
const foo = require('foo')
foo.foo();
```

**Comment by kentcdodds** [comment]
Sweet! Thanks 👏👏
