### ISSUE TITLE
[BUG] Incorrect TS->JS transform for classes

### ISSUE THREAD

**Issue by Ilrilan** [microsoft/playwright#18340]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Windows]
- Node.js version: [16.16.0]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [Typescript version ]

**Code Snippet**

Hello. I want to create fixtures with expression like this:

```typescript
import { test as base } from '@playwright/test'

abstract class MyAbstractFixtureClass {
  constructor() {
    this.innerInitialize()
  }
  protected abstract innerInitialize(): void
}

class MyFixtureClass extends MyAbstractFixtureClass {
  private myInnerField: string
  public getInfo(): string {
    return this.myInnerField
  }
  protected innerInitialize() {
    this.myInnerField = '123'
  }
}

console.log(MyFixtureClass.toString())

export const test = base.extend<{
  my: InstanceType<typeof MyFixtureClass>
}>({
  my: async ({}, use) => {
    const myFixtureInstance = new MyFixtureClass()

    await use(myFixtureInstance)
  },
})

```

This is correct TypeScript, for example if i'll try to insert this code in Typescript sandbox - we receive this JS:

```
"use strict";
class MyAbstractFixtureClass {
    constructor() {
        this.innerInitialize();
    }
}
class MyFixtureClass extends MyAbstractFixtureClass {
    getInfo() {
        return this.myInnerField;
    }
    innerInitialize() {
        this.myInnerField = '123';
    }
}
```

https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgsgTwILmjggDEBLADwgFcoBTAYVXQQG8AoBJAewDtIoq8LlAAUASlYdOCCAAtSYAHSkePWlACSPUhFLBkpAF61xUgL5SADlC4Ra8WgBMEofkQQq1m7bv1GTYgBcCABuXKSObBZsKGgYOGSUNAxMGLSUtDyO8XgEMPCJ1HSMcZKc1qQhwHYIALbYWl5ktMiOwfwqAOZWVCAGsAidtBBaAGZc4u3QXWXSdEU8MvJK9Y3qza3mVjZ2Ds6e6lo6egbG4rOccgqKq6rrpC3OALwIAOQAjABMAMyvW2ZAA

But if i try to run this code from playwright test - i receive another JS code, because of inner call babelTransform hook (node_modules/@playwright/test/lib/transform.js):

```
class MyFixtureClass extends MyAbstractFixtureClass {
  constructor(...args) {
    super(...args);
    this.myInnerField = void 0;
  }
  getInfo() {
    return this.myInnerField;
  }
  innerInitialize() {
    this.myInnerField = '123';
  }
}
```

<img width="950" alt="2022-10-26-15-29-31-8aZ8z" src="https://user-images.githubusercontent.com/37865011/198003763-97adb364-d314-40d5-87cb-86082619c1fb.png">

The problem is in inserting `this.myInnerField = void 0;` to the MyFixtureClass constructor function after `super` call - this string rewrite correct value, setted in the `innerInitialize`

It can be simple reproduced in console.

**Comment by mxschmitt** [comment]
Simpler repro: 

```ts
abstract class MyAbstractFixtureClass {
  constructor() {
    this.innerInitialize();
  }
  protected abstract innerInitialize(): void;
}

class MyFixtureClass extends MyAbstractFixtureClass {
  private myInnerField: string;
  public getInfo(): string {
    return this.myInnerField;
  }
  protected innerInitialize() {
    this.myInnerField = '123s';
  }
}

const myInstance = new MyFixtureClass();
console.log(myInstance.getInfo());
```

and [here](https://babeljs.io/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&corejs=3.21&spec=false&loose=false&code_lz=FAQwRgzgLgTiDGUAE8A2IISQWQJ4EFJYEoAxASwA8oBXGAUwGF1MkBvYJFAewDtoYNRNxgAKAJTtOXJFAAW5CADpyvXvRgBJXuSjkQqcgC96EgNzSAvtIAOMblHqJ6AEyTgBJJKvVadeg2NTcQAuJAA3bnIXC2tgNAwsPApqOiYWLHpqel4XJIIiOEQU2gZmRKkuO3JwkEckAFtcbV8KelQXMIFVAHMLKpowQ3gkHvoobQAzbgku2F7KmQZS3lkFZSaWjTaO_qRrKvtHZzcfDW1dfUMTCUWueUUlTbVt8na3AF4kAHIARgAmADMEG-e2scXgfGgjWa_CgIF48HoSC-6gA7jhcCU0uVMOZ4lDuKh6EpUNweqJntAEUilGMJrxphJxGYgA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Ctypescript&prettier=false&targets=&version=7.19.6&externalPlugins=%40babel%2Fplugin-proposal-class-properties%407.18.6&assumptions=%7B%22setPublicClassFields%22%3Atrue%7D) on the Babel Playground.

Seems like its a JS limitation, that super() needs to be the first call. [`@babel/plugin-proposal-class-properties`](https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) is causing this behaviour.

**Comment by mxschmitt** [comment]
Looks like its following the spec as per https://github.com/babel/babel/issues/8280#issuecomment-403019035. Closing thereby.
