### ISSUE TITLE
[Question] Proxy For Webkit

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#18359]
Hi guys, just related to this one [https://github.com/microsoft/playwright/issues/810](https://github.com/microsoft/playwright/issues/810 ) , should it work when setting the proxy within the project in the .config file ? I can see it works for chromium, but when I try to run webkit on mac os 12 platform, I am still seeing the HTTP Proxy modal popping up.

This is what I have in the config file:

```
name: 'ios',
      use: {
        headless: false,
        ...devices['iPhone 12'],
        launchOptions:{
          proxy: {
            server: `myProxy`,
            username: 'myuser',
            password: 'mypassword'
          },
        },
```

Thanks!

**Comment by mxschmitt** [comment]
Try doing it like:

```
name: 'ios',
      use: {
        headless: false,
        ...devices['iPhone 12'],
        proxy: {
          server: `myProxy`,
          username: 'myuser',
          password: 'mypassword'
        },
```

which should work!

Which popup do you mean? Having a screenshot for it would be helpful!

**Comment by imartinflores** [comment]
Thanks @mxschmitt , I will try it like that, I thought I needed the launchOptions within the project config. I will upload a pic sure, there is a popup saying I need to set user and password for the proxy.. Just when using webkit on Mac OS, Chromium on Windows 10 or 11 is working fine. Let me try this and will post the pic!
Thanks again!

**Comment by mxschmitt** [comment]
Closing as part of the triaging process, please re-file if you still encounter issues / have questions.

**Comment by rapattonimusic** [comment]
Hey @imartinflores I'm having the exact same issue as you. Did you ever get it resolved?
