### ISSUE TITLE
[Question] Why don't we the options interfaces ?

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#18351]
I'll take the `page.click(selector[, options])` method.

If you look at the signature, the `options` interface is not exposed to users.

This could be helpful in abstractions that developers want to use, without having to copy paste source code, and having to make sure it hasn't changed in releases without knowing.

So I thougt: Why don't we unify them under an interface & expose them ?

**Comment by mxschmitt** [comment]
You can do `type PageClickOptions = Parameters<Page['click']>[1];` would that work for you?

Most customers don't need the interfaces, so having the `Parameters` workaround is usually fine for the folks who need it.

**Comment by shtlrs** [comment]
Alright, that does it indeed for me.

Thanks @mxschmitt !
