### ISSUE TITLE
[Question] page.GetByRole throwing errors .net

### ISSUE THREAD

**Issue by fomnus** [microsoft/playwright#18366]
await Page.GetByRole("link", new() { Name = "Sign in." }).ClickAsync();
await Page.GetByRole("button", new() { Name = "Continue" }).ClickAsync();

In visual studio this is being thrown as an error? I just used the test generator to generate the syntax

Error	CS1503	Argument 1: cannot convert from 'string' to 'Microsoft.Playwright.AriaRole'

**Comment by mxschmitt** [comment]
await Page.GetByRole(AriaRole.Link, new() { NameString = "Sign in." }).ClickAsync();

this should work. I'll release an update soon.

**Comment by mxschmitt** [comment]
1.27.2 is currently being published, should be fixed in that version.
