### ISSUE TITLE
[Feature] Allow reading .only in annotations

### ISSUE THREAD

**Issue by tanishqkancharla** [microsoft/playwright#18363]
Hello, it seems .only doesn't get processed into test annotations: https://playwright.dev/docs/test-annotations

Is it possible to add this to the annotation list so fixtures can conditionally perform some action based on if a test runs as .only or not?

(and is there a workaround for now?)

**Comment by mxschmitt** [comment]
What is your use-case for it?

If you annotate it with .only all the other tests are filtered out, so only the test will run. As of today there is no way of detecting it. But you can assume that if .only is used, all tests that run are basically marked as .only.

**Comment by tanishqkancharla** [comment]
Normally my tests run headless, but if .only is used, I'd like to run the test in "head-full" mode so the author can debug the test. 

Maybe I should just instead use a headless annotation on every headless test? Or explicitly annotate the "head-full" test. But these seem like less than ideal solutions, since the test author now has to know how to explicitly use that annotation...

**Comment by mxschmitt** [comment]
What about using the VSCode extension for debugging? This is our recommended solution for a good developer and debugging experience: https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright

Alternatively you can focus a manual test via: `npx playwright test --debug foo.spec.ts:42` 42 is in this case the line number of the test.

**Comment by tanishqkancharla** [comment]
Sorry I think I conflated the meaning of headless. Playwright has its own concept of headless tests that run in the browser. We are using playwright to test an electron app, which we can run headlessly (which is different; playwright headless doesn't mean anything here). Is there anyway to learn if a test is being run in debug mode programmatically? Didn't see it on the docs.

**Comment by mxschmitt** [comment]
As per above, this is not possible, you can introduce an environment variable which you set while debugging, that should work!

**Comment by tanishqkancharla** [comment]
Seems like I can read the `PWDEBUG` env vriable, even if invoked through `npx playwright test --debug`. Works for me as a workaround. Docs can be updated to reflect that + the `TestInfo` object passed could have a `debug` flag.

**Comment by mxschmitt** [comment]
Yes --debug will set the PWDEBUG env var, but this is more an internal implementation detail, so this might change in the future.

Since the original issue is answered and this workaround works for you, I'm closing it for now.
