### ISSUE TITLE
[Question]  debug `no tests found`

### ISSUE THREAD

**Issue by jonny64** [microsoft/playwright#18369]
@Mallikarjunkrs how do I debug `no tests found`?

I want to match `slices/**/tests/**/*.js` for slices/${folder}/tests/${all subfolders}, there about 10 submodules

* `ls slices/**/tests/*.js` prints just first level, but match occurs
* Tried to inspect pw /tests/ and found no test about glob pattern
* `DEBUG=* npx playwright test` prints NO info about matched files

If no debugging is possible, could you please point out where the hell in pw source code match occurs? I want to debug my case

Impact: integrating pw into my enviroment blocked

**Comment by mxschmitt** [comment]
Where do you put the glob pattern, do you pass it as CLI options or do you put it into [testMatch](https://playwright.dev/docs/api/class-testconfig#test-config-test-match)?

usually make sure that testDir, testMatch, CLI test-filter all are ok.

Can you share your Playwright config with us and how you invoke Playwright Test?

You can do `npx playwright test --list` to list the matched tests.

**Comment by mxschmitt** [comment]
Closing as per above.
