### ISSUE TITLE
[Question] Loading older browsers to run tests 

### ISSUE THREAD

**Issue by Ghosty669** [microsoft/playwright#18375]
Hi there,
 We've got a scenario where we'd like to run our tests against an old version of Edge (version 18) so was wondering if there was a way to load in this as part of our CI and run our tests on it?
Thanks
 John

**Comment by mxschmitt** [comment]
The old Edge is not supported, only the new Chromium based Edge is supported.

Each Playwright version is tightly coupled to a version of Firefox, WebKit and Chromium to guarantee that everything works as expected.

You can tho set a custom `executablePath` in the `launchOptions` to a different Chromium based browser or use channels.

See https://playwright.dev/docs/browsers for more information.
