### ISSUE TITLE
[Question] Add annotations to skipped tests

### ISSUE THREAD

**Issue by raulparada** [microsoft/playwright#18372]
A bit of background on https://github.com/microsoft/playwright/issues/9348#issuecomment-1293387867

tldr: I'd need to add annotations to skipped/fixme tests (`test.skip(...)` / `test.fixme(...)`) but cannot figure out how. I'm using a fixture that basically (automatically) adds:
```ts
...
test.info().annotations.push({ type: "key", description: key });
...
```

...but fixtures are not run for skipped tests? (right?). How would I go about this? at what point of the test lifecycle could I inject this info so that it is available to a downstream reporter?

**Why do I need this?** because otherwise I lack this key annotation when importing results into a (popular) test management framework, producing either errors or suboptimal reporting.

**Comment by bitcoder** [comment]
If I understood correctly, you want to have visbility of the skipped tests on the TM tool (i.e., Xray in this case), is that it?
And the current problem is that the annotations are added within the test code block, right?

**Comment by raulparada** [comment]
Hi @bitcoder 👋 

Yes that's it; I want to 'report' on skipped tests, but the only way to add the linking metadata (i.e. `test_key` property) is as an annotation, yet I cannot figure out how to add this for skipped tests, as these don't run any `beforeEach` or fixture code. Maybe I'm missing something? this affects the import of results into the TM tool as it (I think) attempts to create new issues for these tests without `test_key`.

**Comment by bitcoder** [comment]
So, in this case I've added a similar problem. I wasn't able to figure out a solution for it as the annotation code is implemented within the test code... so the test reporter never sees it.
It's true that in that case,  and since you're enforcing results to be mapped to existing Test issue, new tests will be provisioned. If you didn't have the test_key annotation, then tests would be automatically provisioned on Xray side.. and then if you decided to skip them, Xray would find the same tests and simply report agains them.
In your case, you have some Tests ... that you're reporting results against using the annotation. And then whenever tests are skipped, Xray will see results and will try to find related tests by using a specific algorithm based on the test name.. if it doesn't find them, it will autoprovision them.
I don't know how to overcome this honestly. If PW had like tags/labels, then eventually the test reporter could know them, but in this case we don't have them, so..

**Comment by bitcoder** [comment]
Somehow related, some time ago I've made this [junit-processor](https://www.npmjs.com/package/junit-processor) that can be useful for some situations (e.g.,  removing tests marked as skipped for example); it's a post-processing utility.

**Comment by raulparada** [comment]
Thank you 🥇@bitcoder! that tool really does it as workaround for my issue for the time being; importing is smooth now 😌 

For Playwright team, **question / feature request still stands**; I think my naive expectation as user here would be to have another parameter for fixtures (similar to `auto` or `scope`) that makes them run unconditionally to whether the test is run or not (e.g. skipped). That could surely cover this and a few other use cases. Thank you

**Comment by mxschmitt** [comment]
How do you do your annotation and fixme/skip? Could you provide us a repro?

If your annotations gets added before the test gets skipped, then they should be added to the report.

I tested if annotations get added when fixme is used, and it looks good to me, so having expect/actual would be very helpful!

**Comment by aslushnikov** [comment]
Looks like there's a good discussion and no action point for the playwright team; closing! 

Please feel free to re-file if you think we still can be helpful!

**Comment by ArCiGo** [comment]
Hi, I'm facing the same issue. I have some tests that are skipped (for many reasons). I added the `test.fixme()` in my `beforeEach()` hook, and `test.info().annotations.push({})` annotation in the test that's skipped, with a message about why it was skipped, but the reporters I have doesn't show in the reports the descriptions.

Sample 1.-

```typescript
test.beforeEach(async ({ page }) => {
    test.fixme();

    // rest of the code
});

test.describe('My amazing suite, () => {
    test('My amazing test to fix', async ({ page }) => {
        test.info().annotations.push({
            type: 'My amazing issue',
            description: 'My amazing description'
        });

        // rest of my test
    });

    // other tests
});
```

Then I moved the `test.fixme()` to the skipped test, before the `test.info().annotations.push({})` annotation, and it continued with no showing in the reports the description of why the test was skipped.

Sample 2.-

```typescript
test.beforeEach(async ({ page }) => {
    // rest of the code
});

test.describe('My amazing suite, () => {
    test('My amazing test to fix', async ({ page }) => {
        test.fixme();
        test.info().annotations.push({
            type: 'My amazing issue',
            description: 'My amazing description'
        });

        // rest of my test
    });

    // other tests
});
```

Finally I put the `fixme()` annotation as a flag in my test (like this `test.fixme('My test, async ({ page }) => { // body of my test });` and it happened the same behaviour I mentioned.

Sample 3.-

```typescript
test.beforeEach(async ({ page }) => {
    // rest of the code
});

test.describe('My amazing suite, () => {
    test.fixme('My amazing test to fix', async ({ page }) => {
        test.info().annotations.push({
            type: 'My amazing issue',
            description: 'My amazing description'
        });

        // rest of my test
    });

    // other tests
});
```

Is there another way to show the description of why the test was skipped or set with the annotation `fixme()`? The only things that I see in my reports are the words **fixme** and **skip**.
