### ISSUE TITLE
[Feature] Navigate back to `.spec` file from single test in HTML report

### ISSUE THREAD

**Issue by pas2al** [microsoft/playwright#18378]
After clicking on a single test within a `.spec` file I cannot go back. It would be nice to have more straightforward navigation.

![Screenshot 2022-10-27 at 17 27 53](https://user-images.githubusercontent.com/14128066/198333743-8519f18c-b62c-433c-a8e9-16f3db0fab1a.png)

![Screenshot 2022-10-27 at 17 28 14](https://user-images.githubusercontent.com/14128066/198333731-cd9dedb6-c157-458c-9fc1-cfd2ef8dda87.png)

**Comment by mxschmitt** [comment]
You can click on "All" 
<img width="111" alt="image" src="https://user-images.githubusercontent.com/17984549/198359872-0d26192d-872e-4e8c-8c1d-22115ae44f76.png">
 at the top, would that work for you? A Playwright report can contain multiple test results from different spec files, so making it go back when you click on the spec file name would be missleading.

**Comment by pas2al** [comment]
Hmm, that would bring me back to the overview of all tests. Listing a block for each spec file and it's containing tests. That might be a pretty long list. I would like to navigate between the failing tests in one suite (spec file).

What do you mean by?
> can contain multiple test results from different spec files

Isn't the top-level element always the spec file? For example:

- `.spec`
  - test.describe1
    - testA
    - testB
      - test.describeNestedIn1
        - testC
        - testD
  - test.describe2
    - testE
    - testF

**Comment by mxschmitt** [comment]
Look at this html report e.g. which is the entry point to the html report. There is no "per file" view available yet.

![localhost_9223_](https://user-images.githubusercontent.com/17984549/198676696-fd090c93-0e73-4ee0-902d-2cbe9d51c2ad.png)

We could make it possible to filter for a spec file, and then when you click on the spec file name it will use this query to filter by file. That would probably help you already a lot if I understand you correctly.

**Comment by pas2al** [comment]
> We could make it possible to filter for a spec file, and then when you click on the spec file name it will use this query to filter by file. 

Yep, that sounds good! Or we create an anchor for the `.spec` file and use it to jump to the corresponding section in the "All" view. Single tests have a `testId` like `playwright-report/index.html#?testId=90352081d4846ce67435-a72830451154c5654e96`. Something similar for the files?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
