### ISSUE TITLE
Locating span elements by text content

### ISSUE THREAD

**Issue by MiriamAlter** [microsoft/playwright#18385]
I've come across an issue with a `:has-text()` selector and I'd like to know the best way to fix it.

Right now, I have two elements that I'm testing with:
`<div class="name"><span>Example 1</span></div>`
`<div><span class="name">Example 2</span></div>`

This is the locator I've written, and it works with example 1:
`locator('.name:has-text("Example 1")')`

However, the same locator format _doesn't_ work with example 2. My assumption is that I'm trying to locate the span element directly, rather than a child element inside it. Is there a similar selector that I can use to get the span element in example 2 - preferably one that will work with both examples? If not, what would be the cleanest way to get the parent div from example 2 so I can use the `:has-text()` selector without issue?

(Unfortunately, I can't alter the HTML, so adding or moving classes/IDs is not an option.)

**Comment by mxschmitt** [comment]
Does `page.locator('.name', { hasText: 'Example 1' })` work for you?

You can also use `page.locator('.name').getByText('Example 1')` which should work or `page.locator('.name >> text="Example 1")`

**Comment by MiriamAlter** [comment]
Thanks for the feedback! I tried your first solution and it worked perfectly to solve the problem. But in doing so, it caused another problem. I have an if/else condition that looks for the selector with an `isVisible()` function before performing any actions on it. The condition looks like this:
`if(await this.page.isVisible(".name", { hasText: "Example 1" })) {
     //actions
}`
It's returning true for all "name" class elements regardless of text content, so any code inside would be evaluated even if the only element on the page is example 2. Does `isVisible()` not recognize that syntax the way `.locator()` does? What do you suggest as an alternative?

**Comment by mxschmitt** [comment]
> Does isVisible() not recognize that syntax the way .locator() does?

Exactly, don't use `page.isVisible()`, use:

`if(await this.page.locator(".name", { hasText: "Example 1" }).isVisible()) { //actions }`

instead. We recommend using TypeScript or using JavaScript with `// @ts-check` to make sure only supported parameters get passed over to Playwright functions.

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you have any further questions.

**Comment by MiriamAlter** [comment]
This worked. Thank you!

**Comment by gokulpoojary17** [comment]
TypeError: Cannot read properties of undefined (reading 'goto')

   at ..\Member\BankDetails.js:14

  12 |
  13 |     async gotobankpage(){
> 14 |         await this.page.goto('https://dev-team2.starmfv2.remiges.tech/en-US/#/member/add/bank-details?id=10438&status=DRAFT')
     |                         ^
  15 |
  16 |
  17 |     }
    at Bankpage.gotobankpage (C:\UCC_Playwright\Member\BankDetails.js:14:25)
    at C:\UCC_Playwright\tests\Member-details.spec.js:19:16

getting this error when calling the page using goto locator

**Comment by HashanPerera** [comment]
> TypeError: Cannot read properties of undefined (reading 'goto')
> 
> at ..\Member\BankDetails.js:14
> 
> 12 | 13 | async gotobankpage(){
> 
> > 14 |         await this.page.goto('https://dev-team2.starmfv2.remiges.tech/en-US/#/member/add/bank-details?id=10438&status=DRAFT')
> > |                         ^
> > 15 |
> > 16 |
> > 17 |     }
> > at Bankpage.gotobankpage (C:\UCC_Playwright\Member\BankDetails.js:14:25)
> > at C:\UCC_Playwright\tests\Member-details.spec.js:19:16
> 
> getting this error when calling the page using goto locator

remove 'this' and try.
