### ISSUE TITLE
[BUG] Can't drop element onto element outside the viewport

### ISSUE THREAD

**Issue by PinkChampagne17** [microsoft/playwright#18395]
**Context:**
- Playwright Version: 1.25.2
- Operating System: Mac
- Browser: Chromium

**Describe the bug**
In [previous issue](https://github.com/microsoft/playwright/issues/17621), I report that Playwright will always be waiting and do nothing if I drag an element to drop onto an element outside the viewport. 
The reply is that's expected because users can't drop elements outside of viewport too.

However, I still believe that this is a bug because actually users can let the target element into the viewport during dragging in somehow. 
For example, while dragging, scroll the mouse wheel or drag the element to the edge of the browser window to start scrolling to let the target element into the viewport.
The scenarios above are very common in the draggable long lists, can we simulate such behavior?

**Comment by mxschmitt** [comment]
You can do the following which works in chromium, does it work for you?

```ts
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });
  const context = await browser.newContext({
    viewport: {
      width: 1920,
      height: 1080,
    }
  });
  const page = await context.newPage();
  await page.goto('https://playwright.dev/docs/api/class-page');
  await page.mouse.move(20, 20);
  await page.mouse.down();
  await page.mouse.move(1920 - 5, 1080 - 5);
  await page.waitForTimeout(1000);
  console.log('done');
  await page.waitForTimeout(50_000);

  // Teardown
  await context.close();
  await browser.close();
})();
```

**Comment by aslushnikov** [comment]
Closing as per above
