### ISSUE TITLE
[Question] What is the difference between to put an await before expect and put await inside expect ?

### ISSUE THREAD

**Issue by loxinchi** [microsoft/playwright#18393]
Hi, What is the difference between to put an `await` before `expect` and put `await` inside `expect` ? and why?

`expect(screenshot).toMatchSnapshot(name[, options]) ` [doc](https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-1)
```javascript
expect(await page.screenshot()).toMatchSnapshot('landing-page.png');
```
`expect(success).toBeTruthy()`[doc](https://playwright.dev/docs/test-assertions)
```javascript
await expect(locator).toBeEditable();
```

**Comment by MindaugasMateika** [comment]
`toMatchSnapshot` is not async assertion and returns void so you don't need to an await while `page.screenshot()` returns Promise<Buffer> so you need to await it.

await expect(locator).toBeEditable() this is also async, as per documentation, so you need to await.

**Comment by mxschmitt** [comment]
As per above, `toMatchSnapshot ` does not retry rather than `toHaveScreenshot` which does retry until the expectation is met or the timeout is reached.

[`toHaveScreenshot`](https://playwright.dev/docs/test-assertions#locator-assertions-to-have-screenshot-1) is the recommended one.
