### ISSUE TITLE
[Feature] Allow wildcard proxy bypass

### ISSUE THREAD

**Issue by test20161010** [microsoft/playwright#18391]
Proxy Bypass does not work properly with following code.

```
const launchOptions: LaunchOptions = {
    proxy: {
        server: '202.222.222.222:8080',
        bypass: '10.*,192.*.0.*,192.*.2.*,172.20.*,172.17.*',
    }
};
await firefox.launch(launchOptions);
```

I cannot see the page with a private IP address like below.
http://10.10.110.180:1080/

If I remove the proxy options, I can see sites on private IP addresses, but then I cannot see external pages.

The same issue is happening with WebKit, but not with Chromium, Chrome or Edge. The version I used is below.

Playwright: 1.27.1
Chromium: 107.0.5304.18
Chrome: 107.0.5304.63
Edge: 106.0.1370.52
Firefox: Nightly 105.0.1
Webkit: 16.0
NodeJS: 16.13.0 LTS
OS: Windows 10 (21H2 / Build 19044.2006)

I have confirmed that the same problem does not occur in my environment when using Firefox 102.4.0.esr with Selenium Webdriver 4.5.0.

Thank you for your reading.

**Comment by mxschmitt** [comment]
How do you specify them in Webdriver?

As per documentation it seems like wildcards/glob patterns are not supported.

**Comment by test20161010** [comment]
WebDriver works with this code.
`const options: string[] = [];
options.push(`--proxy-server=http://202.222.222.222:8080`);
options.push(`--proxy-bypass-list=10.*;192.*.0.*;192.*.2.*;172.20.*;172.17.*`);
const option = new chrome.Options().addArguments(...options);
cont driver = new Builder()
    .forBrowser('chrome')
    .setChromeOptions(option)
    .build();`
However, currently I use only "10.*".
The other values ​​are prepared because they are likely to be needed in the future.
I've never had this problem with WebDriver.

I saw a code in Playwright that puts an asterisk if it starts with a dot,
so I thought it was supported.
`if (proxy.bypass)
        proxyBypassRules.push(...proxy.bypass.split(',').map(t => t.trim()).map(t => t.startsWith('.') ? '*' + t : t));`

**Comment by mxschmitt** [comment]
It's not supported yet, Chromium works, since they have it implemented already, but for Firefox and WebKit this is not the case. I'll mark it as a feature request.

**Comment by test20161010** [comment]
I understand. 
Thank you for your explanation.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
