### ISSUE TITLE
[Question] VSCode extension install via yarn

### ISSUE THREAD

**Issue by JonrGull** [microsoft/playwright#18396]
Would it be possible to add a setting to install Playwright via yarn using extension and command pallete?

I typically like to use `yarn` over `npm`. When I use the VSCode extension to install Playwright, it makes a `package-lock.json` file. 

Is it okay to just delete `package-lock.json` and continue using yarn?

Thank you.

**Comment by mxschmitt** [comment]
> Is it okay to just delete package-lock.json and continue using yarn?

Yes, absolutely.

Since the majority of the users are using NPM, we think that's the way to go. If you want to use Yarn instead, you can setup the project via the command line, then it will choose Yarn instead: `yarn create playwright`
