### ISSUE TITLE
[BUG] Full Page Screenshot does not work when height is set to: 100%

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#18406]
I've ran into this issue in the past too with different frameworks, that take full page screenshots, and do some sort of resizing scrolling before taking the screenshot. 

If you have specific styling set for height width that aren't auto, it usually messes up and breaks. 

We have styling set to 100% for height on the body as to get a footer behaving correctly across different screen sizes, this proceeds to break window.scrollTo which I'm assuming fullPage uses.

**Comment by mxschmitt** [comment]
Can you share a repro with us?

**Comment by gselsidi** [comment]
basically add a height style to any site at 100%. But go here ufeelgreat.com and take a snapshot, you'll see the page is long and has a bunch of assets, but it only captures the first part. If you disable the height style it captures it fine. 

we're redesigning the page and the style now as a work around, but there should be a better way to handle this from playwrights side.

**Comment by aslushnikov** [comment]
@gselsidi could you please re-file with a code snippet we can easily copy-and-paste-and-debug? This would save a ton of time for the team. 

Thank you!

**Comment by gselsidi** [comment]
1. Go to ufeelgreat.com page.goto
2. Take a full page screenshot tomatchscreenshot(fullpage: true)

You need a code snippet for this? It’s 2 lines of code….

Full page screenshot fails because the website has style height: 100% on the body
