### ISSUE TITLE
[Feature] Is there any way to Duplicate Browser Tabs (Chrome and Edge)

### ISSUE THREAD

**Issue by cx4** [microsoft/playwright#18409]
I tried using "keyboard.press(control+shift+k)" in the msedge browser to Duplicate Browser Tabs in the same state, but it gave an error. 

so  Is there any way to Duplicate Browser Tabs. thanks.

**Comment by cx4** [comment]
There are several elements on a page that I need to click on to go to the next step, but clicking only supports opening in the current page. If I use the same url to open, the page will load an initial page, and I need to do multiple operations on this page to reach the interface with multiple elements.

**Comment by cx4** [comment]
> This is not possible, we recommend to just create a new page and doing page.goto(oldPage.url()).
> 
> What is your end-to-end specific use-case of it?

There are several elements on a page that I need to click on to go to the next step, but clicking only supports opening in the current page. If I use the same url to open, the page will load an initial page, and I need to do multiple operations on this page to reach the interface with multiple elements.

**Comment by aslushnikov** [comment]
> so Is there any way to Duplicate Browser Tabs. thanks.

There's no way to do this.

**Comment by maint14** [comment]
Too sad thing
