### ISSUE TITLE
[How to Click on  button part of form tag]

### ISSUE THREAD

**Issue by AbhinavDubey22** [microsoft/playwright#18414]
Hi,
I am trying to automation one of healthcare application. Here we need to click on  link which is part of a form. But  not able to get success on it. Even via recording also, that step is not recording. Kindly help. If I will not get success on it, I will not able to continue my automation.  PFB Details:

**<form role="form" method="POST" action="modelSwitchBranch.php" id="chBranch" xpath="1"><div class="branchCard flex flexAlignItemsCenter flexJustifyBetween mb20">
				                <div class="flex flexAlignItemsStart flexDirectionCol">
				                     <h4 class="mb4">Dr. Nikam Heart</h4>
				                     <span>domlur</span>
				                </div>
		                  	<div class="form-group">
								    	<input type="hidden" name="branch-id" value="6034">
                              <input type="hidden" name="return_url" value="/md/viewRemoteAppointments.php">
									</div>
		                 	 	<div>
                              <input type="image" src="resources/images/arrowRightIcon.svg" alt="Submit" id="btn_submit">
                           </div>
		               		</div></form>**

Tried all possible  Way:
 **public static void click(Page page, String locator){
        System.out.println("User is supposed to click on  => "+page.locator(locator).innerText());
        page.locator(locator).click();

        System.out.println("User clicked on expected field!!!");
    }
    public static void single_click_by_force(Page page,String locator) {
        page.locator(locator).click(new Locator.ClickOptions().setForce(true));
    }
    // Double click
    public static void double_click(Page page,String locator){
        assertThat(page.locator(locator)).isEnabled();
        page.locator(locator).dblclick();
    }
 public static void click_by_action(Page page,String locator) {

        page.locator(locator).press("Enter");
    }**

Please  Check recording screenshot. That line got skipped. 
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/116916651/198720112-c8a02a71-4715-471f-8712-9c5a990d771d.png">

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/116916651/198720294-d48f0ee2-d921-4cf0-a922-2c94d266f4c7.png">

**Comment by AbhinavDubey22** [comment]
Even not clicked [Login Button] too which is also a form. 
**<form role="form" method="POST" action="modelLoginCheck.php" xpath="1">
                        <div class="form-group">
                           <div class="textLeft">Email</div>
                           <input type="text" class="frmField" id="email" name="email" placeholder="Enter your email">
                        </div>
                        <div class="form-group">
                           <div class="textLeft">Password</div>
                           <input type="password" class="frmField" id="password" name="password" placeholder="Password">
                        </div>
                        <div class="flexDirectionRow flex">
                           <div class="form-group textLeft">
                              <label class="formCheckbox">Remember Me
                              <input type="checkbox" name="autologin" id="autologin" value="1">
                              <span class="checkmark"></span>
                              </label>        
                           </div>
                           <div class="form-group textRight password">
                              <span><a href="forgotPassword.php" class="linkBlue password">Forgot Password</a></span>
                              <a style="display: none;" id="extensionKey" href="offline/extensionKey.php"><small>Enter Extension Key</small></a>
                           </div>
                        </div>  
                        <div class="textRight mb32">
                        <div class="form-group textLeft red">
                           <div id="login-error"></div>
                        </div>
                        <div class="form-group">
                           <button type="button" data-style="zoom-in" class="btnBlue btnL" id="loginButton" onclick="submitLoginForm();">
                           Sign in
                           </button>
                        </div>
                        
                           
                           
                     
                  </div></form>**
<img width="1312" alt="image" src="https://user-images.githubusercontent.com/116916651/198720469-8f162cf3-5d56-4b6d-93ad-e069c301e344.png">

**Comment by aslushnikov** [comment]
Hey @AbhinavDubey22,

I can't help much here. I'd need to have a repro that I can run locally and that will demonstrate how things don't work. Please, re-file once you have this repro!
