### ISSUE TITLE
[Feature] Enable All Cookies or launch chrome in non-incognito mode

### ISSUE THREAD

**Issue by easyrepro** [microsoft/playwright#18411]
Some websites are not working properly in Chromium Incognito mode if "Block third-party cookies in Incognito" is enabled while launching browser.

Please provide a way to launch chrome with 'Allow all cookies' enabled or launch browser in non-incognito mode as a workaround for this specific issue

P.S.: launchPersistentContext is not an option for our use case, so can not save 'Allow all cookies' in user-data-dir.

**Comment by easyrepro** [comment]
> Why is this a no-option? This is the suggested solution to run non-incognito context.

While running in CI/CD pipeline, we can not store and use same user-data-dir directory (tests may run on different environments, large size of user-data-dir folder to store and retrieve while starting test cases)

**Comment by aslushnikov** [comment]
@easyrepro I'm not sure I follow: why would you need to store the `user-data-dir` directory? Why can't you just use the method instead of the regular `browserType.launch()`? 

```js
// before
const browser = await browserType.launch();
const context = await browser.newContext();
// after
const context = await browserType.launchPersistentContext('/tmp/foo');
```

**Comment by easyrepro** [comment]
I was confused with Selenium stuff.

> `const context = await browserType.launchPersistentContext('/tmp/foo');`

This returns context object with browser object set to null. (Verified in playwright-java). Our scenario needs browser object also so to launch new contexts. 

For this scenario using launchPersistentContext is a work around to overcome third-party cookies issue but, having a way to pass chrome preference makes it easier to pass other chrome preferences (as using Selenium ChromeOptions)
