### ISSUE TITLE
[BUG] Concatenating xpath locator that starts with an axes fails

### ISSUE THREAD

**Issue by dadamsGS** [microsoft/playwright#18417]
**Context:**
- Playwright Version: 1.27.2
- Operating System: Linux
- Node.js version: 16
- Browser: Chromium

**Describe the bug**
Concatenating an xpath locator that starts with an axes `/` does not get recognized as a good locator. When using the following locator approach
```javascript
this.ticketTopNav.locator(`//button[@id='composition-button']`).locator(`/following-sibling::div//ul[@id='composition-menu']//li[@role='menuitem']`).click()
```
my test will fail with the error message 

```javascript
locator.click: Unsupported token "@id" while parsing selector "/following-sibling::div//ul[@id='composition-menu']//li[@role='menuitem']"
```

However, the following locator will work:
```javascript
this.ticketTopNav.locator(`//button[@id='composition-button']/following-sibling::div//ul[@id='composition-menu']//li[@role='menuitem']`).click()
```

Not sure if I am missing something with xpath locators.

**Comment by aslushnikov** [comment]
@dadamsGS `locator.locator()` methods are locating in the subtree. It does not concatenate your selectors. You can always concatenate selectors just like this:

```js
const selectorA = `//button[@id='composition-button']`;
const selectorB = `/following-sibling::div//ul[@id='composition-menu']//li[@role='menuitem']`;
await page.locator(selectorA + selectorB).click();
```

Read more about subtree selection: https://playwright.dev/docs/next/locators#locate-in-a-subtree
