### ISSUE TITLE
[BUG] WebKit doesn't play webm files on MacOS

### ISSUE THREAD

**Issue by warrenseine** [microsoft/playwright#18423]
---

Triaging summary from @aslushnikov: WebKit doesn't play webm files on MacOS.

---

**Context:**
- Playwright Version: 1.27.1
- Operating System: macOS 12.6 on M1
- Node.js version: 16.17
- Browser: WebKit

```
## System:
 - OS: macOS 12.6
 - Memory: 214.27 MB / 32.00 GB
## Binaries:
 - Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
 - Yarn: 1.22.19 - ~/.yarn/bin/yarn
 - npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
``` 

**Describe the bug**

The WebKit version fetched by Playwright has an unexpected user agent (reported with `navigator.userAgent`):
> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.4 Safari/605.1.15

In particular, I would expect `Version/16.0`, which I correctly get with my default Safari. With a manually installed Safari Technology Preview, I get `Version/16.4`.

I've tried cleaning caches and fetching it again:
```
$ rm -rf ~/Library/Caches/ms-playwright/webkit-*
$ npx playwright install webkit
Downloading Webkit 16.0 (playwright build v1724) - 53.9 Mb [====================] 100% 0.0s
Webkit 16.0 (playwright build v1724) downloaded to ~/Library/Caches/ms-playwright/webkit-1724
```

I suspect that the [current build](https://playwright.azureedge.net/builds/webkit/1724/webkit-mac-12-arm64.zip) is not actually WebKit 16, but WebKit 13. I cannot be sure although WebM video playback support (don't play in this build, plays in official Safari and STP) seems to confirm it.

I've also tried forcing build 1728 (latest unreleased) to no avail.

**Comment by warrenseine** [comment]
Plus, if I refer to [this comment](https://github.com/microsoft/playwright/issues/5795#issuecomment-796914803), the version used to be higher (14, at the time), so something must be wrong with the current build.

**Comment by warrenseine** [comment]
Relatedly, WebKit on Linux is reporting version 16. It does plays WebM. On the other hand, it doesn't have `MediaRecorder`, but that's another story 🤔

To sum up, taking the latest builds on each platform:

|                                                                                   | User agent        | WebM playback | MediaRecorder |
| ---                                                                             | --------------- | ---------------- | --------------- |
| Official Safari (macOS 12.6 arm64)                       | Version/16.0     | ✅                         | ✅                       |
| Safari Technology Preview (macOS 12.6 arm64) | Version/16.4     | ✅                         | ✅                       |
| Playwright WebKit v1724 (macOS 12 arm64)       | Version/13.0.4  | ❌                         | ✅                       |
| Playwright WebKit v1724 (Docker v1.27.1-focal)  | Version/16.0     | ✅                         | ❌                       |

I don't know how Playwright WebKit was built. I'll have a look at the [browser_patches](https://github.com/microsoft/playwright/tree/main/browser_patches/webkit) directory, but any help would be welcome.

**Comment by aslushnikov** [comment]
@warrenseine how do you check the user agent?

For example, the following yields a proper user agent for me.
```js
// a.mjs
import { webkit } from '@playwright/test';

const browser = await webkit.launch();
const page = await browser.newPage();
console.log(await page.evaluate(() => navigator.userAgent));
// Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
await browser.close();
```

If you use the WebKit Web Inspector, then user agent will reset to some old value. Unfortunately, this is a known issue.

**Comment by warrenseine** [comment]
Yes, I used the Web Inspector.

If it is indeed version 16, can you confirm that WebM is not supported? Any reason why we see these differences in feature support?

**Comment by aslushnikov** [comment]
@warrenseine the WebM should be supported on MacOS; we'll take a look.

**Comment by warrenseine** [comment]
Cool, thanks! I'll try a nightly soon.

**Comment by warrenseine** [comment]
I can confirm that playback works now, thanks! Unfortunately, I've discovered another WebM-specific issue (#20489). Please have a look!
