### ISSUE TITLE
[BUG] Playwright server does not launch with webkit's executablePath

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#18439]
**Context:**
- Playwright Version: all versions
- Operating System: Mac
- Node.js version: v16
- Browser: Webkit

**Code Snippet**

```javascript
const {webkit} = require("playwright");

(async () => {
  try {
    const browserServer = await webkit.launchServer({
      headless: false,
      executablePath: '/Users/ankur/Library/Caches/ms-playwright/webkit-1724/Playwright.app/Contents/MacOS/Playwright'
    });

    const wsEndpoint = browserServer.wsEndpoint();

    console.log("wsEndpoint:: ", wsEndpoint);
  } catch (e) {
    console.error("Error:: ", e)
  }
})();

```

**Output**
```
Error::  ProtocolError: Browser closed.
==================== Browser output: ====================
<launching> /Users/ankur/Library/Caches/ms-playwright/webkit-1724/Playwright.app/Contents/MacOS/Playwright --inspector-pipe --no-startup-window
<launched> pid=72924
[pid=72924][err] dyld[72924]: Symbol not found: (_OBJC_CLASS_$__WKBrowserContext)
[pid=72924][err]   Referenced from: '/Users/ankur/Library/Caches/ms-playwright/webkit-1724/Playwright.app/Contents/MacOS/Playwright'
[pid=72924][err]   Expected in: '/System/Library/Frameworks/WebKit.framework/Versions/A/WebKit'
[pid=72924] <process did exit: exitCode=null, signal=SIGABRT>
[pid=72924] starting temporary directories cleanup Failed to launch browser.

```

**Describe the bug**
I want to launch Playwright server with custom executable path. The builds of Chromium and Firefox work when the executablePath is provided. However, with WebKit, the server does not launch even when the executablePath of the bundled WebKit is provided. Is there anything missing in the script?
We are working on providing remote test execution for Playwright, and debugging which WebKit versions are compatible with the respective playwright versions.

@mxschmitt

**Comment by ankur-lt** [comment]
Here, https://github.com/microsoft/playwright/issues/17691#issuecomment-1262130886, @mxschmitt mentioned that only Playwright's bundled browsers are supported, not the custom ones.

**Comment by ankur-lt** [comment]
But this ideally shouldn't affect if executing the script with the same browser in the `executablePath`.

**Comment by aslushnikov** [comment]
@ankur-lt  well, the following works just fine for me on MacOS:

```js
// a.mjs
import { webkit } from '@playwright/test';

const browserServer = await webkit.launchServer({
  headless: false,
  executablePath: webkit.executablePath(),
});

const wsEndpoint = browserServer.wsEndpoint();

console.log("wsEndpoint:: ", wsEndpoint);
```

**Comment by aslushnikov** [comment]
@@ankur-lt oh yeah, you're using wrong path there. Check the one from `webkit.executablePath()`!

**Comment by ankur-lt** [comment]
Thanks @aslushnikov !
