### ISSUE TITLE
[Feature] Ability to Set Default Typing Delay

### ISSUE THREAD

**Issue by rmorshea** [microsoft/playwright#18436]
In my particular application I have a websocket that sends over `onchange` events from `<input/>` elements. In order to get consistent results when running in CI, I often find that I need to set a delay on all calls to `my_input.type()`. It would be great if there were a way to set a default delay for this purpose.

It doesn't seem like a default delay for `type()` ought to apply to the delay for click/press related actions so, if the addition of this feature makes sense, it also seems reasonable to have a way to set a default delay for those actions as well. Thus, the following methods could probably be added to the browser and page contexts:

- `set_default_type_delay`
- `set_default_click_delay` - this could probably apply to both click and press actions
- `set_default_dblclick_delay`

**Comment by aslushnikov** [comment]
@rmorshea I'd recommend to create a sugar method for yourself or a single set of reusable options that you will share between `page.type` calls.

As per the feature request, we are unlikely to ever implement this since it is niche, so I'll close this right away.
