### ISSUE TITLE
[Question] What is the role of the command npx playwright install?

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#18446]
Hi there!

I would like to understand something that confuses me.

I perform the tests on the GitLab runner.

We use runners with installed Windows OS (due to our app's specifications that require installing MSIs).

When I perform the command `npx playwright install` - it looks like all necessary is installed:

```Downloading Chromium 107.0.5304.18 (playwright build v1028)...
Chromium 107.0.5304.18 (playwright build v1028) downloaded to C:\Users\ContainerAdministrator\AppData\Local\ms-playwright\chromium-1028

[36mcore-ui-playwright-server_1  |[0m   Downloading FFMPEG playwright build v1007...

And OTHERS....
```

Then, I try to run the tests with the Chrome browser and get the following error:

```
[36mcore-ui-playwright-server_1  |[0m       browserType.launch: Chromium distribution 'chrome' is not found at C:\Users\ContainerAdministrator\AppData\Local\Google\Chrome\Application\chrome.exe

[36mcore-ui-playwright-server_1  |[0m       Run "npx playwright install chrome"
```

But when I run with the mentioned command:
`npx playwright install chrome`

I don't get any errors.

If so - what is the role of the command `npx playwright install`?

**Comment by aslushnikov** [comment]
The `npx playwright install` installs only the "bundled browsers": Chromium, Firefox and WebKit of specific versions.

The command `npx playwright install chrome` installs Google Chrome, latest version of the official Google Chrome build. This is not versioned and is installed in the common location.
