### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ivanokunkov** [microsoft/playwright#18447]
**Context:**
- Playwright Version: 1.28.0-alpha-oct-25-2022
- Operating System: MacOS Monterey 12.5.1 
- Node.js version: [e.g. 12.22, 14.6]
- Browser: All
- Extra: Test for 60+ geolocations through proxy array

I run the test on 60+ locations, through personal paid proxies. Each test is run and accesses the array for access to the proxy. A small part of the tests is performed from the first run. Most of it is from 2-3 runs, a small part remains not passed.

```import { test } from '@playwright/test';

const geolocations = [
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 1', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 2', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 3', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 4', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 5', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    {server: '195.208.55.99:57459', username: 'uAzpXtHs1', password: 'HRVZ8FTPh', localebrowser: 'hi_IN', localetranslate: 'hi', localeenglish: 'en', name: 'India 6', codephone: '91', countre: 'India', currency: 'INR (Indian rupee)' },
    ];

geolocations.forEach(g=>

test(`${g.name} - Checking the opening of the site loading Web, taking into account the array of geolocations`, async ({ browser, browserName, isMobile  }) => {

//Settings the test
    const context = await browser.newContext({
      
      permissions: ['geolocation'],
      ignoreHTTPSErrors: true,
      proxy: {
        server: g.server,
        username: g.username,
        password: g.password
        },
    })
    
const page = await context.newPage();
    await page.setViewportSize({ width: 1440, height: 900 });
    await page.goto('https://playwright.dev/');
    await page.waitForSelector('.logosList_zAAF');
    await context.close();
    await browser.close();
    })
)
```

**Here are the errors I get in the html report:

1. page.goto: Navigation failed because page was closed!
2. browser.newContext: Target page, context or browser has been closed (If you add real 20 proxies with different geo)
3. page.goto: net::ERR_ABORTED; maybe frame was detached? (If you add real 20 proxies with different geo)

Help me figure out the problems, what's the matter - do I have bad proxies or problems with the code?**

**Comment by aslushnikov** [comment]
@ivanokunkov We see no issues with folks running tests with proxies and geolocation overrides. The errors you mention here are pretty generic and usually happen as the browsers run out-of-memory; it looks like you saturate the machine you run tests on.

I'd suggest running them in serial or getting a beefier machine to run them. There's not much I can tell with this much information; so I'll close this for now. If you have a repro that we can run locally and experience the failures, please re-submit!

**Comment by ivanqa2022** [comment]
> 

Thanks for the answer. I correctly understood that you need to reduce the number of workers (--workers 1)?
