### ISSUE TITLE
[BUG] Rollup failed to resolve import "$env/static/public" 

### ISSUE THREAD

**Issue by vhscom** [microsoft/playwright#18465]
**Context:**
- Playwright Version: `"@playwright/experimental-ct-svelte": "^1.27.1"`
- Operating System: macOS
- Node.js version: 18.6.0
- Browser: Chromium
- Extra:

```
## System:
 - OS: macOS 12.6
 - Memory: 81.05 MB / 16.00 GB
## Binaries:
 - Node: 18.6.0 - ~/Library/Caches/fnm_multishells/77742_1666972699539/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.13.2 - ~/Library/Caches/fnm_multishells/77742_1666972699539/bin/npm
## Languages:
 - Bash: 5.1.16 - /opt/homebrew/bin/bash
```

**Reduced Test Case**
https://github.com/vhscom/playwright-ct-env-reduced-test

**Important bits from reduced test case called out below:**

_tests/component/test.ts_

```ts
import { test, expect } from '@playwright/experimental-ct-svelte';
import Foo from '$lib/Foo.svelte';

test('should work', async ({ mount }) => {
  const component = await mount(Foo);
  await expect(component).toContainText('Vite + Svelte');
});
```

_src/variable.ts_

```ts
import { VITE_APP_NAME } from '$env/static/public';

// the old way still works
// const variables = {
//   appName: import.meta.env.VITE_APP_NAME
// };

// the new way does not work
const variables = {
  appName: VITE_APP_NAME
};

export default variables;
```

**Describe the bug**

Above fails in supplied reduced test case, which is the Svelte boilerplate generated today with a single Environment variable added by following SvelteKit. Open `src/variable.ts` to the difference in the failing scenario and a working scenario. Use of  functionality is security-related in SvelteKit and, as such, should enjoy first-class support in Playwright.

**More background**

This is likely related to https://github.com/sveltejs/kit/issues/1485

**Comment by aslushnikov** [comment]
@vhscom we're happy to look at it when SveteKit stabilizes! So far it has been changing under our feet with every update.

Let me close this for now; feel free to re-file once SvelteKit is stable!

**Comment by vhscom** [comment]
I'm not sure I understand the logic behind closing this. I believe the purpose of Playwright experimental component testing was to enable component testing for major platforms. Is support for current versions SvelteKit now being deprecated?

**Comment by vhscom** [comment]
There's a workaround for this problem and that's to add a `.env.production` (used during build time) and drop in some empty env variables. This prevents playwright ct from failing to build using the new `$env` module in SK. More info in Kit docs here: https://kit.svelte.dev/docs/modules#$env-static-public

**Comment by vhscom** [comment]
> Let me close this for now; feel free to re-file once SvelteKit is stable!

SvelteKit is in RC phase currently and per their doc [should be considered stable](Let me close this for now; feel free to re-file once SvelteKit is stable!).

@aslushnikov Please consider reopening this to find a way to provide a better OOB experience.
