### ISSUE TITLE
[BUG] Waiting for `testConfig.webServer` with `url` timesout

### ISSUE THREAD

**Issue by Xenfo** [microsoft/playwright#18467]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.27.1
- Operating System: [e.g. Windows, Linux or Mac] WSL Ubuntu 22.04
- Node.js version: [e.g. 12.22, 14.6] 19.0.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment]

## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 9.44 GB / 15.55 GB
 - Container: Yes
## Binaries:
 - Node: 19.0.0 - ~/.asdf/installs/nodejs/19.0.0/bin/node
 - Yarn: 1.22.19 - ~/.asdf/installs/nodejs/19.0.0/bin/yarn
 - npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Code Snippet**

`npm run dev` would run a Vite dev server for React.

```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from "@playwright/test";
import { devices } from "@playwright/test";
import dotenv from "dotenv";
import path from "path";

dotenv.config({ path: path.resolve(__dirname, "test.env") });

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
  testDir: "./e2e",
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000,
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: Boolean(process.env.CI),
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: "html",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
    },

    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },

    {
      name: "webkit",
      use: {
        ...devices["Desktop Safari"],
      },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 12'],
    //   },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge',
    //   },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: {
    //     channel: 'chrome',
    //   },
    // },
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  webServer: [
    {
      cwd: "client",
      command: "npm run dev",
      url: "https://localhost:3000/", // TLS is setup for this example
    },
  ],
};

export default config;
```

**Describe the bug**

Using a `url` instead of `port` will cause Playwright to always timeout. Once switching to just `port: 3000,` instead, everything works instantly.

**Comment by dgozman** [comment]
@Xenfo Perhaps your server does not respond on that url? If you could share a repro that we can run locally, we might be able to take a look.

**Comment by Xenfo** [comment]
I unfortunately can't share a repro with my specific code but when I open the link in my browser after running the command that Playwright should run, everything responds properly. I'll look into making a custom repro for you. I'll also check that Playwright is also running the command by checking the URL manually.

**Comment by Xenfo** [comment]
Found the issue. When a port is provided, it always works and when a non `https` URL is provided it always works. When an `https` URL is provided, it runs the command provided for the webserver and then hangs. So the webserver is created but Playwright was unable to check if it is running and hanged instead. Certs were generated with [`mkcert`](https://github.com/FiloSottile/mkcert).

Repro: https://github.com/Xenfo/playwright-demo (you need to add certs)

**Comment by aslushnikov** [comment]
>  (you need to add certs)

@Xenfo How do I do this? Can you provide steps?

**Comment by Xenfo** [comment]
@aslushnikov using `mkcert` which I linked above, run the commands in the root of the reproduction repository.

```sh
mkcert -install
mkcert localhost
mkdir certs
mv localhost.pem certs/cert.pem
mv localhost-key.pem certs/key.pem
```

**Comment by aslushnikov** [comment]
@Xenfo thank you! Turns out you need to configure node.js to use the custom root CA: https://github.com/FiloSottile/mkcert#using-the-root-with-nodejs

The following worked for me:
```sh
export NODE_EXTRA_CA_CERTS="$(mkcert -CAROOT)/rootCA.pem"
npx playwright test
```

**Comment by aslushnikov** [comment]
Looks like there's nothing else to be done on our side here; closing!

**Comment by lukaselmer** [comment]
@aslushnikov Shouldn't `ignoreHTTPSErrors: true` ignore the https errors if the certs are wrong? I think that's still a bug? 🤔
