### ISSUE TITLE
[BUG] Firefox browserContext.pages method returns empty array after newContext call.

### ISSUE THREAD

**Issue by jasonandmonte** [microsoft/playwright#1847]
**Context:**
- Playwright Version: 0.13.0
- Operating System: Windows

**Code Snippet**

```javascript
const { firefox } = require('playwright');

(async () => {
  const browser = await firefox.launch({ headless: false });
  const context = await browser.newContext();
  const pages = context.pages();
  console.log(pages); // []
})();
```

**Describe the bug**
Expected access to the first tab created through the `browserContext.pages` method. However when `pages` is called it returns an empty array.

Current workaround is using `browserContext.newPage();`.
```javascript
  const context = await browser.newContext();
  const page = await context.newPage();
```
 However this creates two tabs in the browser window with the initial tab still inaccessible through the `pages` method.

**Comment by yury-s** [comment]
The page you see doesn't belong to the context you created. It's an artifact that we cannot get rid of in headful Firefox at the moment (basically there should be at least one tab) but it's not created in headless mode. You can only get a grip on that page in [persistent context](https://playwright.dev/#version=v0.13.0&section=api&q=browsertypelaunchpersistentcontextuserdatadir-options):

```js
const { firefox } = require('playwright');

(async () => {
  const context = await firefox.launchPersistentContext('/tmp/testprofile', { 
    headless: false
  });
  const pages = context.pages();
  console.log(pages.length);
  await context.close();
})()

```
