### ISSUE TITLE
Can elements in iframe and page be handled in same .ts file

### ISSUE THREAD

**Issue by sswapnika** [microsoft/playwright#18471]
My application have two different environments. In one of the environment, elements are available in iframe whereas in other environment, they are present in page. I don't want to duplicate my code. Is there a way that I can handle both frame and page elements in the same ts file?

**Comment by dgozman** [comment]
@sswapnika You can do something like that:

```ts
test('my test', async ({ page }) => {
  // Choose a base, either page or iframe.
  const pageOrFrame = process.env.INSIDE_IFRAME ? page.frameLocator('iframe.my-frame') : page;
  
  // Now start your operations from this base.
  await pageOrFrame.getByText('Submit').click();
});
```

Let me know if this helps.

**Comment by aslushnikov** [comment]
Closing as per above.
