### ISSUE TITLE
[Question] .eml file extension

### ISSUE THREAD

**Issue by fomnus** [microsoft/playwright#18474]
I am trying to test if a .eml file is downloaded in the browser, however whenever I download a .eml file it downloads incorrectly?

![image](https://user-images.githubusercontent.com/116797592/199276850-4c5b4863-ed2b-4228-8701-07c114d433b7.png)

this is how it downloads in chrome
![image](https://user-images.githubusercontent.com/116797592/199276964-b1897d58-0693-4c31-a4c2-c75250d78cb1.png)

**Comment by dgozman** [comment]
@fomnus You need to call `download.suggestedFileName()` to get the name. See [this guide](https://playwright.dev/docs/downloads) for more details about downloads.

**Comment by fomnus** [comment]
`var download2 = await Page.RunAndWaitForDownloadAsync(async () =>
        {
            await Page.GetByRole(AriaRole.Link, new() { NameString = "Download mail" }).ClickAsync();
        });`
adding
var fileName = download2.suggestedFileName() gives me the error
