### ISSUE TITLE
[REGRESSION]: Test Flakiness regression (10-15%) since playwright upgrade from v1.13 to v1.23

### ISSUE THREAD

**Issue by harmansinghchawla** [microsoft/playwright#18488]
**Context:**
- GOOD Playwright Version: [1.13]
- BAD Playwright Version: [1.23]
- Browsers: [Chrome, firefox, edge....]

**Regression**
Hey folks, we recently upgraded from Playwright v1.13 to v1.23, and have since seen a severe uptick in flakiness ~10-15% (overall), especially w.r.t. firefox (~10%), our assumption was that this upgrade would actually reduce flakiness, but the outcome has been quite the opposite. 
We don't want to rollback our system, since offering Dark-mode and High Contrast test support is critical for our product. Any thoughts to what can we do mitigate this?

**Comment by aslushnikov** [comment]
I don't think we have enough information to act upon it, so I'll close this for now. Please feel free to re-file if you think we can be helpful!
