### ISSUE TITLE
Playwright works locally but fails on CI

### ISSUE THREAD

**Issue by Gbahdeyboh** [microsoft/playwright#1848]
**Context:**
- Playwright Version: 0.13.0
- Operating System: Linux

**Describe the bug**

Playwright works normally locally, but when on the CI. The browser fails to Open. I get the error 
` TypeError: Cannot read property 'newContext' of undefined`

The full log can be found [here](https://integration.wikimedia.org/ci/job/wmf-quibble-selenium-php72-docker/32730/console).

And I'm not exactly sure why this works locally and not on CI.

**Comment by aslushnikov** [comment]
Hey @Gbahdeyboh,

I see there's the following line in the log:

```js
browser = await Browser.startBrowser( 'chromium' );
```

which doesn't look like Playwright. Do you wrap it into something? Where can I get to look at the code?

**Comment by Gbahdeyboh** [comment]
Yes, I created a separate route to start the browser.

You can check the `Browser` class code [here](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/589591/-1..2/tests/playwright/playwrightMediawiki/Browser.js).

The whole code is [here](https://gerrit.wikimedia.org/r/#/c/mediawiki/core/+/589591/-1..2) In case you need and other info from the code.

**Comment by Gbahdeyboh** [comment]
I stopped the use of the `Browser` class I wrapped around playwright to see if I was doing something wrong and I get a new kind of error here
```
(node:2725) ExperimentalWarning: The fs.promises API is experimental
```

Full error [here](https://integration.wikimedia.org/ci/job/wmf-quibble-selenium-php72-docker/32942/console)

**Comment by mxschmitt** [comment]
I think the reason could be either an outdated Node.js version, it needs `10.15.0` or greater or that you not have all the required dependencies installed:  https://github.com/microsoft/playwright/blob/master/docs/troubleshooting.md#chrome-headless-doesnt-launch-on-linuxwsl

**Comment by aslushnikov** [comment]
@Gbahdeyboh I'm sorry I didn't follow up on this. Is this still relevant?

**Comment by Gbahdeyboh** [comment]
No, not at all.
Just in case anyone else experiences the same issue, fs.promises(which playwright uses) is only stable in Node erbium(v12) upwards. I was also missing some Docker CI config, see [here](https://github.com/microsoft/playwright/blob/master/docs/ci.md#travis-ci) for correct configurations for your CI
