### ISSUE TITLE
npx playwright install chrome command fails in windows 11

### ISSUE THREAD

**Issue by SUNITHA-H-N** [microsoft/playwright#18497]
**Context:**
- Playwright Version: ^1.27.1
- Operating System: Windows 11
- Node.js version: v16.16.0
- Browser: Chrome 

Used Commands 
Tried using below commands
** npx playwright install --force chrome**
** npx playwright install chrome**

Got Below Error 

**Downloading Google Chrome
Installing Google Chrome
ERROR: failed to install Google Chrome
Failed to install browsers
Error: Failed to install chrome**

It is blocking our automation Can anyone please help.

Thanks & Regards
Sunitha
![Screenshot 2022-11-02 090621](https://user-images.githubusercontent.com/109061820/199389559-43b077a1-4938-4793-b59d-fdca7fce877e.png)

**Comment by aslushnikov** [comment]
@SUNITHA-H-N it looks like the Google Chrome installer cannot run on the windows machine. Do you run as an administrator?

**Comment by SUNITHA-H-N** [comment]
> @SUNITHA-H-N it looks like the Google Chrome installer cannot run on the windows machine. Do you run as an administrator?

Yes I tried running as administrator

**Comment by aslushnikov** [comment]
@SUNITHA-H-N can you try running chrome installer manually? Does it work?

**Comment by SUNITHA-H-N** [comment]
> @SUNITHA-H-N can you try running chrome installer manually? Does it work?

Not working

**Comment by aslushnikov** [comment]
@SUNITHA-H-N Well, if you can't install chrome on the machine, then this is the answer! I guess this has something to do with the permissions.

I'll close this then since this becomes a general question of "how to install chrome with my specific setup" that is better asked elsewhere.
