### ISSUE TITLE
[Question] any roadmap for when component testing is no longer considered experimental ?

### ISSUE THREAD

**Issue by robskaar** [microsoft/playwright#18498]
I'm researching new frameworks our company should pick up, and with playwright having E2E, and now also CT and the way it's so easy writting tests, it just seems like a really nice framework to pick up, however, the experimental state scares us off a bit for now to commit ourselves completely to it, so i wonder if there's any "high level" roadmap for when CT is expected to  no longer be experimental, e.g. Q3 2023 or something like that?

**Comment by aslushnikov** [comment]
@robskaar Our main focus was and is e2e and it is safe to commit to Playwright for those. There is no deadline for CT to be promoted into the stable as of this moment, but we would be interested in learning how it works for you. The more positive signals we collect, the sooner we'll drop the experimental badge!
