### ISSUE TITLE
[Question]: how can we get the page title?

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#18490]
### Your question

print (page.title())

it return ""
but it's about:blank
how can we get the page title?

_default_title = "Keplr"
if p.to_have_title(re.compile(rf".*{_default_title}")):
it say page doesnt  to_have_title method.

how can we get the page title?

**Comment by aslushnikov** [comment]
@viponedream the `about:blank` is a URL, not a title. You can get it with [`page.url()`](https://playwright.dev/python/docs/next/api/class-page#page-url)
