### ISSUE TITLE
[Feature] Add conditional test.describe.skip()

### ISSUE THREAD

**Issue by azad-derakhshani-GS** [microsoft/playwright#18493]
We have an [unconditional test.describe.skip()](https://playwright.dev/docs/api/class-test#test-describe-skip) but not a conditional one like we have for [test.skip()](https://playwright.dev/docs/api/class-test#test-skip-3).

But it would be really useful to be able to conditionally skip an entire describe block, instead of having to add the conditional skip to every single test inside the describe block.

**Comment by aslushnikov** [comment]
>  instead of having to add the conditional skip to every single test inside the describe block.

@azad-derakhshani-GS you can actually add the condition in the `test.beforeEach()` inside describe:

```js
import { test } from '@playwright/test';

test.describe(() => {
  test.beforeEach(() => {
    test.skip();
  });
  test('shoudl work-1', async ({ page }) => {
    console.log('works-1');
  });
  test('shoudl work-2', async ({ page }) => {
    console.log('works-2');
  });
});
```

Could you please share your use case? What is the condition you use to skip tests?

**Comment by azad-derakhshani-GS** [comment]
> @azad-derakhshani-GS you can actually add the condition in the `test.beforeEach()` inside describe:
That's actually what I first tried, however that doesn't work because I can only get the condition status at the end of the `beforeEach()` hook.

To get the condition (basically feature flag status), I first have to
- log in to the webapp with a user (which already involves instantiating several page objects)
- handle a bunch of banners/popups
- check the href attribute of a link to then set the condition to true or false
- then depending on the condition, execute either the first describe block with 5 tests in it, or the second describe block with 5 different tests.

But since the boolean variable starts as `false` and is only (potentially) changed to `true` at the end of the beforeEach() hook, each test case will still be run based on the `false` condition.

I ended up just adding a test that checks the href and sets the condition value.
Then I have two describe blocks with 5 test casess each, and for each of those 10 test cases I have to add `test.skip(condition)`.

I also tried `beforeAll()` instead of adding a test case, which kinda works, but `beforeAll`'s lack of feature support (no fixtures, no console output, no test report) and bugs (its traces appear as a second trace in the first test of the file) makes it generally unfavourable.

**Comment by aslushnikov** [comment]
> The problem is that beforeEach() is already too late.

@azad-derakhshani-GS  Sure, how about this?

```js
test.describe(() => {
  test.skip(1 == 1);
  test('should work-1', async ({ page }) => {
    console.log('works-1');
  });
  test('should work-2', async ({ page }) => {
    console.log('works-2');
  });
});
```

**Comment by azad-derakhshani-GS** [comment]
@alushnikov That was the very first thing I tried of course, long before filing this feature request, alas it doesn't work, the tests in the describe block are not being skipped despite the skip condition being true.

Here's the first describe block in my file with your suggestion:

```
import { test } from '../Fixtures';

let isNewProfileAppFlagOn = false;

test.beforeEach(async ({ some fixtures }) => {
  //some login steps
  isNewProfileAppFlagOn = await pageObject.element.isVisible({timeout:5000});
  console.log(`The status of the feature flag is ${isNewProfileAppFlagOn}`);
});

test.describe('Check Old Profile ', () => {
  test.skip(isNewProfileAppFlagOn === true);
  test.beforeEach(async ({ some fixtures }) => {
    //some login steps
  });

  test('Edit Profile Form', async ({ tutorProfilePage }) => {
    //some stuff
  });

  test('Edit Profile Contact Form', async ({ some fixtures }, testInfo) => {
    profileContactPage.testCaseTitle = testInfo.title;
    //some stuff
  });

  test('Check That Achievement Elements Are Displayed', async ({ some fixtures}) => {
    //some stuff
  });

  test('Check Pause Button', async ({ some fixtures}) => {
    //some stuff
  });

  test('Check Payment Form Validation', async ({ some fixtures}) => {
    //some stuff
  });
});
```

As you can see here, the console log of the beforeEachshows that the condition is `true`, yet the tests in that describe block are still being run (and fail).
![Screenshot_20221107_165023](https://user-images.githubusercontent.com/98180468/200422915-45f2f6f4-a29f-40c2-9cbc-99dcea8fa525.png)

That's why I had to slap a `test.skip(isNewProfileAppFlagOn === true);` into each test case inside the describe block, otherwise they don't get skipped.

But don't you agree that `test.describe()` should have the same features as `test()`?
This feature request is not just about what I'm currently working on but more in general.

**Comment by aslushnikov** [comment]
@azad-derakhshani-GS there are two stages: test declaration and test execution.

1. If you want to skip tests during test declaration, you should use `test.skip()` inside the `test.describe()` callback.
2. If you want to skip tests during test execution, you should use `test.skip()` inside the `beforeEach()` hook

If you have a weird mixture - like, some tests should be skipped, and this is only known during the `beforeEach` step, then
you should split your tests into groups, and use `test.skip` inside the `beforeEach` callback to skip all tests in the group.

> But independently of that, don't you agree that test.describe() should have the same features as test()? Since it's basically the same feature, just one level higher.

This is skipping tests during **test declaration** and functionally the same as using `test.skip()` inside the `test.describe()` callback.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by mmtr0g** [comment]
@azad-derakhshani-GS is dead right here, if describe has a .skip() method it should allow for conditional execution in a similar manner. Users will expect this. Also IMO, doing it in a beforeEach function is fugly.
