### ISSUE TITLE
[Question] NameString regex

### ISSUE THREAD

**Issue by fomnus** [microsoft/playwright#18509]
Is there a way to inject regex in the following, I am looking for a specific button however the button has a small image inside and I need to just look for specific text, the codegen outputs the following

`await Page.GetByRole(AriaRole.Link, new() { NameString = " Download mail" }).ClickAsync();`

**Comment by aslushnikov** [comment]
@fomnus According for the [`page.GetByRole()`](https://playwright.dev/dotnet/docs/next/api/class-page#page-get-by-role-option-name) documentation, you can pass regex as a name!

Feel free to file another issue if you think we can be helpful.
