### ISSUE TITLE
[Feature] Ability to Add Multiple TestId Attributes for use with getByTestId()

### ISSUE THREAD

**Issue by angelo-loria** [microsoft/playwright#18508]
The new getByTestId() and setTestIdAttribute() functions are great. I think it would be helpful to be able to set more than one TestId attribute, so that getByTestId() works with both `data-testid` and `id`, for example. We're using Playwright across a few projects, some projects using `data-testid`, some `id`, and some using both, unfortunately. Eventually I'll work on getting our code moved over entirely to `data-testid` but in the meantime it'd be super helpful to set more than one attribute for getByTestId().

**Comment by aslushnikov** [comment]
>  I think it would be helpful to be able to set more than one TestId attribute, so that getByTestId() works with both data-testid and id, for example.

@angelo-loria This would be unfortunate logic; the `data-testid=foo` and `id=foo` might point to different elements, and then the `page.getByTestId('foo')` might result in something unpredictable.

In case you're migrating from `id` to `data-testid`, I'd recommend to use `page.getByTestId('foo')` for all new tests and `data-testid` elements, and use `page.locator('id=foo')` for the legacy system.

Hope this helps!

**Comment by angelikabucko** [comment]
Hi @aslushnikov ! Is there any way for that feature to be reconsidered? I have similar issue in my company, we use `data-cy` for certain pages and `data-testid` for others. The company aquired several different products and implemented them in our platform, unfortunately we don't have a unified strategy which ids we want to use yet. At the moment I need to choose between which test-id attribute I want to use and change the other one to `locator()`. I wish I could add both 🤞
