### ISSUE TITLE
[Feature] Add option sort or any order to method toHaveText 

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#18503]
use case
I have list of elements with text contents and want to check that list of elements contents equal to expected list ['b', 'a', 'c' ] but I don't care about ordering. For example I don't have sorting on the page and elements can come in different order so if I use toHaveText it expects I know order of getting elements texts.

**Comment by niyarlatotep** [comment]
Another approach to have an "hook" function to modify result from page on getting before expect. So we could be able modify result for example filter array, or sort, or string to uppercase etc ... 

something like:
expect(locator, {hook: (array)=>array.sort()}).toHaveText(["a", "b" , "c"])

**Comment by dgozman** [comment]
@niyarlatotep Do you mind sharing a specific example where you'd like to use this feature? This will helps us getting the API just right.

Btw, meanwhile you can workaround with something like:
```js
await expect.poll(async () => {
  const texts = await locator.allTextContents();
  return texts.sort();
}).toEqual(['a', 'b', 'c']);
```

**Comment by niyarlatotep** [comment]
@dgozman Hello! I've already made the helper before opening issue, it looks like:

```
const expectLocator = (locator: Locator, messageOrOptions?: MessageOrOptions) => ({
    toHaveTextAnyOrder: (expected: Array<string>) => expect
        .poll( async () => (await locator.allTextContents()).sort().map(el => el.trim()), messageOrOptions)
        .toEqual(expected.sort())    
})
```
So I use it like (example near to production):
```
const user1 = userPage.createUser('user1')
const user2 = userPage.createUser('user2')
expectLocator(userPage.usersList.name).toHaveTextAnyOrder([user1.name, user2.name])
```
So I've already solve my problem somehow, but it would be nice to have it built in (not sure if it really needed), now I have to import my helper explicitely. I'm not sure may be there's a way to extend native playwright expect I tried a bit but had no success so desided to use this simple way.

**Comment by dgozman** [comment]
@niyarlatotep Thank you for the explanation. I'll leave this issue open for prioritization for now.
