### ISSUE TITLE
[Question] How to prevent specific locator interaction logging or gather to sub-logging area?

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#18502]
Hello, I have AgGrid table helper class that scans all the table rows and returns to the page object as an interactable table object.
My problem is that when the helper class is scanning all the elements of the table, the test log is spammed with hundreds of logs about all of the table columns, rows, and cells.
I was wondering if one of the two options is possible:

1. Prevent logging for those specific locators
2. Create a sub-logging area in the HTML document like "test.step" does and put there all the logs for the table scanning

Thanks, Adi

it looks like that:
![2022-11-02_11-13-14](https://user-images.githubusercontent.com/61405630/199451828-8fd5105c-9632-4988-a8a4-39114a1ced8e.png)

**Comment by ValorHeart** [comment]
@aslushnikov Thanks for the reply!; my Challege is that the initialization method of the helper is being called from the page object itself and not straight from the test, so I can't wrap it in test.step at the POM class

**Comment by aslushnikov** [comment]
>my Challege is that the initialization method of the helper is being called from the page object itself and not straight from the test, so I can't wrap it in test.step at the POM class

@ValorHeart I don't follow - can you elaborate? Why cannot you wrap the call with the `test.step()`?

**Comment by ValorHeart** [comment]
@aslushnikov, given the following pseudo code, the test interacts with the page that interacts with the table scan helper, usually I don't control the tests and the pages as-well as other developers are writing the tests, and I write the helpers, as well as the table scanning part is not a test step by its own, but is a part of small flows
**test:**
const tablePage = new tablePAge(page)
tablePage.clickOnTableRow("row22");

**page:**
import AgGrid from "./helpers"
clickOnTableRow(row) {
const agGrid = new AgGrid(); <------------ Scan of table happens here and all the logs spamming
const rows = agGrid.getRows();
rows.foreach((row) => ...row.click); <------ This click operation i want to log
}

**Comment by yury-s** [comment]
@ValorHeart in that case you can either wrap the calls in the test into steps:

```js
const tablePage = await test.step('create tablePAge', () => new tablePAge(page));
await test.step('click on row22', () => tablePage.clickOnTableRow("row22"));
```
or call test.step from the helpers:
```ts
import { test, expect } from '@playwright/test';
import AgGrid from "./helpers"

clickOnTableRow(row) {
  await test.step('clickOnTableRow', () => {
    const agGrid = new AgGrid(); <------------ Scan of table happens here and all the logs spamming
    const rows = agGrid.getRows();
    rows.foreach((row) => ...row.click); <------ This click operation i want to log
  });
}
```
 would that work?

**Comment by yury-s** [comment]
Yes, it's a global instance so you should be able to import it in multiple files. You could also pass it explicitly via as a constructor argument from the tests.

Closing the issue as proposed solution seems to work. Feel free to open a new request and link to this issue if you need further help.
