### ISSUE TITLE
[Question] CountAsync and Strictness

### ISSUE THREAD

**Issue by reavdhoef** [microsoft/playwright#18507]
Hi all,

I tried using Locator.CountAsync from Playwrightfor  .NET, but it throws an error. The code and error are as follows:

`var n = await Page.Locator("tbody > tr").CountAsync();`

`Microsoft.Playwright.PlaywrightException : Error: strict mode violation: "tbody > tr" resolved to 4 elements`.

The [documentation ](https://playwright.dev/dotnet/docs/locators) seems to suggest this should work since CountAsync should know how to deal with multiple elements. Am I missing some option/configuration?

Cheers,
Rick

**Comment by aslushnikov** [comment]
@reavdhoef which Playwright version is this? I cannot reproduce on 1.27.1

**Comment by reavdhoef** [comment]
As I was checking the version numbers and I found that I used the exact same Locator elsewhere in the code on which I called ToContainTextAsync.
Removing this line fixed the problem.

Sorry for the false alarm and thanks for the response!
