### ISSUE TITLE
[Question]How to wait till an embedded pdf is loaded

### ISSUE THREAD

**Issue by arifshaon** [microsoft/playwright#18510]
Hello everyone,

I have the following the HTML page from which loads an embedded PDF:

<!DOCTYPE html><html><head></head><body style="height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);"><embed name="ACA90C252440377ED478E6306E0F4201" style="position:absolute; left: 0; top: 0;" width="100%" height="100%" src="about:blank" type="application/pdf" internalid="ACA90C252440377ED478E6306E0F4201"></body></html>

How do I get playwright to wait till the pdf is loaded and then navigate within the frame?

Any help would be greatly appreciated.

Best
Arif

**Comment by aslushnikov** [comment]
> How do I get playwright to wait till the pdf is loaded and then navigate within the frame?

@arifshaon Playwright does not load to PDFs - instead, we download them since PDF viewers are not part of the web platform. So in general you'll need to await for the download to conclude; see https://playwright.dev/docs/next/downloads for more info!

**Comment by arifshaon** [comment]
Hi, @aslushnikov,

Thanks for the quick reply.  I am not actually trying to download the pdf but access the frame within which the pdf is loaded.  The code snipped it as follows:
`<!DOCTYPE html><html><head></head><body style="height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);"><embed name="31A58BA265F9023E5A4E99B0919CC62C" style="position:absolute; left: 0; top: 0;" width="100%" height="100%" src="about:blank" type="application/pdf" internalid="31A58BA265F9023E5A4E99B0919CC62C"></body></html>
`

**Comment by alvaromartmart** [comment]
@aslushnikov can you clarify please? Is it not possible to check if a pdf has been loaded to an iframe then?
I was trying to do something like this in my project:
```ts
await expect(this.page.frameLocator('iframe').locator('embed[type="application/pdf"]')).toBeVisible();
```
Interestingly, it works if I run the test in headed mode, but not in headless mode. Does this have anything to do with [this warning in the docs](https://playwright.dev/docs/api/class-frame) (screenshot below) and [related chromium issue](https://bugs.chromium.org/p/chromium/issues/detail?id=761295), or is it something else?
<img width="827" alt="Screenshot 2023-12-07 at 09 43 30" src="https://github.com/microsoft/playwright/assets/18287793/d680583f-eac8-4923-aa22-881558e741f9">

**Comment by carlosmmelo** [comment]
This is an interesting question since I dont want to download the pdf, just check if it is present as `application/pdf` loaded in the iframe
