### ISSUE TITLE
[Question] Viewing PDF file without downloading it

### ISSUE THREAD

**Issue by wygun** [microsoft/playwright#18512]
Context:

    Playwright Version: 1.20
    Operating System: Windows 10 x64
    Browser: Chromium and Firefox

Issue Description:
I want to view PDF file without downloading it with any of the browser in playwright. 

Steps: 
When I click on PDF file with below selector, I can see there is a successful POST method on network but can not open PDF file. When I try to open same PDF file without playwright automation I mean manually; I can open it.
`page.querySelector("//div[2]//a[1]//img[1]").evaluate("el => el.parentElement.querySelector(\"img\").click()");`

**Comment by aslushnikov** [comment]
> I want to view PDF file without downloading it with any of the browser in playwright.

@wygun this is not a supported use case for Playwright; PDF viewers are not the part of Web Platform so we don't automate them.

The best suggestion would be to download PDF and then use something like pdf.js to load the file. Hope this helps!
