### ISSUE TITLE
if waitForNavigation failed，timeout end it,how to get response of waitForNavigation  

### ISSUE THREAD

**Issue by wyying** [microsoft/playwright#18527]
I want get response of login,but if login success,that reload,I can not get response,that I think the waitForNavigation ,but if waitForNavigation  faild, I cant't get response of waitForNavigation ;
```
 Response response = page.waitForNavigation(()->{
            page.click("#login[ng-click=\"doLogin(loginCredential)\"]");

        });
```
![image](https://user-images.githubusercontent.com/15809193/199645359-ebdefab7-15fb-4647-9f3d-da2fb70f1681.png)

**Comment by aslushnikov** [comment]
@wyying I'm not sure I follow. Could you please re-file following the template? Ideally, with a full but small snippet in your language that I can run locally to see the issue?

Thanks!
