### ISSUE TITLE
[Question] Serial + Parallel on the same file

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#18520]
Hi there, is it possible to use "Serial" and "Parallel" on the same .spec file?
So, all tests in the file run in Serial mode, but the ones grouped on the same describe run in Parallel ? or is it better to split them on different files ? I think it's been raised or asked before, but could not find it. Thank you!

So in this Example , test1 should run first and then test2 and test3 will run in parallel once 1 has finished:

```
test.describe.configure({ mode: 'serial' });
  test.describe(() => {
    test('@test fail 1', ({}, testInfo) => {
    expect(1).toBe(2);
  });
})

test.describe.parallel(() => {
  test.describe(() => {
      test('@test should fail2', ({}, testInfo) => {
          expect(1).toBe(2);
      });

      test('@test should fail3', ({}, testInfo) => {
          expect(1).toBe(2);
    });
  })
})
```

**Comment by aslushnikov** [comment]
> So in this Example , test1 should run first and then test2 and test3 will run in parallel once 1 has finished:

Hey @imartinflores, this kind of orchestration is not yet possible!

**Comment by imartinflores** [comment]
Cool, thanks for clarification @aslushnikov !!
