### ISSUE TITLE
[BUG] ENOENT: no such file or directory, when attempting to upload a file with playwright

### ISSUE THREAD

**Issue by andrzey** [microsoft/playwright#18534]
**Context:**
- Playwright Version: 1.27.1
- Operating System: macOS Monterey
- Node.js version: Node 16.14.2
- Browser: Chrome 107.0.5304.87

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from '@playwright/test';

test('Upload XML', async ({ page }) => {
  await page.goto('/');

  await page.getByRole('button', { name: 'Choose file' }).click();
  await page.getByLabel('Choose file').setInputFiles('e2e/files/office.xml');

  await expect(page.getByText('office.xml')).toBeVisible();
});
```

**Describe the bug**

I try to upload a file in my test, but is constantly hit with the `ENOENT: no such file or directory` error. My folder structure is the following:
```
e2e
- tests
-- upload-xml.spec.ts
- files
-- office.xml
- node_modules
- playwright.config.ts
```

I have tried all possible paths, but somehow not one of them is correct. I run my tests with `npx playwright test tests/upload-sxml.spec.ts` from the root of the `e2e` folder. Can anyone see what I possible can be doing wrong?

**Comment by aslushnikov** [comment]
@andrzey You should either pass absolute paths or paths relative to the `process.cwd`. Try passing absolute paths.

Also check out how we do it in our tests for the method:

https://github.com/microsoft/playwright/blob/245260b3656c71274aab80f5f5544ea9e5a74404/tests/page/page-set-input-files.spec.ts#L138-L151

Hope this helps!

**Comment by Fish3913** [comment]
in your path instead of single slash use double slash like this, await page.getByLabel('Choose file').setInputFiles('e2e//files//office.xml');
