### ISSUE TITLE
[Question] toHaveText assertion not matching substring?

### ISSUE THREAD

**Issue by sagrawal-code** [microsoft/playwright#18539]
Why does the following test fail though the substring is present in the locator text (the output is listed below along with the case which passes)?

```ts
await expect(newPage.getByTestId('plan-end-date')).toHaveText(
    '13 Nov 2022'
)
```
Failure output:
```
Error: expect(received).toHaveText(expected)


- Expected string  - 1
+ Received string  + 3

- 13 Nov 2022
+
+                                         (Valid till 13 Nov 2022)
+                                     
```

Following test passes:

```ts
await expect(newPage.getByTestId('plan-end-date')).toHaveText(
    '(Valid till 13 Nov 2022)'
)
```

**Comment by Nav-2d** [comment]
You can do this:

`await expect(newPage.getByTestId('plan-end-date')).toHaveText(/13 Nov 2022/)`

or

`await expect(newPage.getByTestId('plan-end-date')).toContainText('13 Nov 2022')`

**Comment by sagrawal-code** [comment]
Thanks. Though the documentation says "Expected substring" for `toHaveText` assertion: https://playwright.dev/docs/test-assertions#locator-assertions-to-have-text

`toContainText` description says the same: https://playwright.dev/docs/test-assertions#locator-assertions-to-contain-text

Maybe some clarification is needed there?
