### ISSUE TITLE
Is there a way to set `expect.toMatchSnapshot()` options globally?

### ISSUE THREAD

**Issue by udidol** [microsoft/playwright#18537]
The `expect().toMatchSnapshot()` assertion method accepts an options object with settings like `maxDiffPixels`.
Is there a way to set these options globally in one place, like the Playwright config file?

**Comment by aslushnikov** [comment]
@udidol yep, you can either use [`testConfig.expect`](https://playwright.dev/docs/next/api/class-testconfig#test-config-expect) or [`testProject.expect`](https://playwright.dev/docs/next/api/class-testproject#test-project-expect) to configure these:

```ts
// playwright.config.ts
export default {
  expect: {
    toMatchSnapshot: {
      maxDiffPixels: 100, 
    }
  },
};
