### ISSUE TITLE
[Question] How to mock Chromium's Embedded Search API on Edge?

### ISSUE THREAD

**Issue by marinamelin** [microsoft/playwright#18546]
- Playwright Version: 1.24.2
- Operating System: Windows
- Node.js version: 16.14.0
- Browser: Edge

Hello Playwright team,

We are migrating from jest test runner to playwright test runner. We have a few existing tests that used to mock properties of `window.chrome.embeddedSearch.newTabPage` ([API reference](https://www.chromium.org/embeddedsearch/)). Mocking worked when we were performing it in `browserContext.addInitScript` using jest test runner. And it stopped working when the same script is being passed to `browserContext.addInitScript` using playwright test runner.

Simplified test code that reproduces the issue:

```
// @ts-check
const playwrightTest = require("@playwright/test");

playwrightTest.test('It can set mock for ntp', async ({ page }) => {
    await page.addInitScript(() => {
        window.chrome.embeddedSearch = {
            newTabPage: {
                mostVisitedAvailable: true
            }
        };
    });

    await page.goto("https://ntp.msn.com/edge/ntp");
    await playwrightTest.expect(await page.evaluate("window.chrome.embeddedSearch.newTabPage.mostVisitedAvailable")).toEqual(true);
});

```
Test execution result:
![image](https://user-images.githubusercontent.com/107934934/199758888-ac9675ed-7050-46ce-a16a-8701e8ba4c62.png)

Related settings in the playwright.config.ts are:
```
use: {
    headless: false
},
projects: [
    {
        name: "Microsoft Edge",
        use: {
            channel: "msedge"
        }
    }
]
```

Could you please advise why this mock stopped working after switching the test runner, and how to make it work?

Thank you!

**Comment by aslushnikov** [comment]
@marinamelin could you try mocking on the context level instead of on the page level?

```js
    await page.context().addInitScript(() => {
        window.chrome.embeddedSearch = {
            newTabPage: {
                mostVisitedAvailable: true
            }
        };
    });
```

**Comment by marinamelin** [comment]
@aslushnikov , tried to mock on the context level, it didn't make a difference. Test is still failing on the same assertion as before.

**Comment by aslushnikov** [comment]
@marinamelin how do I try it? The `https://ntp.msn.com/edge/ntp` is not available for me. Is there any open website that has this API enabled so that I can try this?

**Comment by marinamelin** [comment]
@aslushnikov the `https://ntp.msn.com/edge/ntp` is available on edge browser only (not chromium). We are trying to test a starting page of the edge browser. Related settings in the playwright.config.ts are:
```
use: {
    headless: false
},
projects: [
    {
        name: "Microsoft Edge",
        use: {
            channel: "msedge"
        }
    }
]
```

I tried searching this repository for anything potentially related to the problem, and found what appears to be a [disablement of new tab page on firefox](https://github.com/microsoft/playwright/blob/05b623e6b05e81b64a30ad3fbf1f9e21d762ae9d/browser_patches/firefox/preferences/playwright.cfg#L83). Could anything like that be interfering with ntp mocks on edge?

**Comment by marinamelin** [comment]
Thank you for the suggestion! Moved this mock in `page.evaluate()` and it is now working as intended. Will close this question.

With jest we were mocking it in `browserContext.addInitScript`.
