### ISSUE TITLE
How i can pass Graphql request using playwrite ?

### ISSUE THREAD

**Issue by vinayanth** [microsoft/playwright#18545]
Hi Team ,

i am using playwright for both web and API testing and its working fine but now i am trying to automate Graphql and since its post request i don't know how to tackle the issue?
for example if this is my Graphql how to pass the post request using playwright
{
  DemoCards(
    filter: {
      language: ENGLISH,
      name: [
        {
        terms: "Lion",
        operator: AND
        }
      ],
       setAbbreviation: [
        {
        terms: "LBK",
        operator: AND
        }
      ]
    },
    sort: {
      SortBy: NAME
      Order: ASC
    },
    offset: 0,
    limit: 10
) {
    DemoCards{
      name
      printings{
        name
        set{
          name
          abbreviation
        }
      }
      printing{
        name
      }
    }
    currentPage
    totalPages
    hasPreviousPage
    hasNextPage
    totalResults
  }
}

**Comment by Nav-2d** [comment]
I haven't tried it but here is what I think should work:

```
test('graphql api post', async ({ request }) => {
    const response = await request.post('/', {
        data: {
            query: YOUR_QUERY
        }
    })
    const jsonResponse = await response.json();

    expect(response.ok()).toBeTruthy()
    expect(response.status()).toBe(200)
})
```

**Comment by klepik1990** [comment]
Can you share the error you are getting?
Did you try to send your query as string using JSON.stringify?

**Comment by aslushnikov** [comment]
Looks like a general programming question with a good reply already; closing since there's no action needed from the Playwright team.

**Comment by vinayanth** [comment]
Thanks all for your response, will try today and get back to you folks.

Regards

**Comment by vinayanth** [comment]
Hi Team,

i tried using first option as mentioned below

const {test, expect, request} = ***@***.***/test');

const { ExecutableItemWrapper } = require('allure-js-commons');



test('graphql api post', async ({ request }) => {

    const response = await request.post(“——URL________”, {

            data: {

                query: {

                    DemoCards(

                      filter: {

                        language: ENGLISH,

                        name: [

                          {

                          terms: "crust”,

                          operator: AND

                          }

                        ],

                         setAbbreviation: [

                          {

                          terms: "JHT”,

                          operator: AND

                          }

                        ]

                      },

                      sort: {

                        SortBy: NAME

                        Order: ASC

                      },

                      offset: 0,

                      limit: 10

                  ) {

                      DemoCards{

                        name

                        printings{

                          name

                          set{

                            name

                            abbreviation

                          }

                        }

                        printing{

                          name

                        }

                      }

                      currentPage

                      totalPages

                      hasPreviousPage

                      hasNextPage

                      totalResults

                    }

                  }

        }

    })

        const jsonResponse = await response.json();

        expect(response.ok()).toBeTruthy()

        expect(response.status()).toBe(200)

})


but i am getting error msgs as mentioned in the attachment can u please
help me how to insert the Graphql request


Regards

vinayanth.k

**Comment by vinayanth** [comment]
Hi team,

this wat i tried



const {test, expect, request} = ***@***.***/test');

const { ExecutableItemWrapper } = require('allure-js-commons');

let query;


test('graphql api post', async ({ request }) => {

    const response = await request.post("__________URL________________", {



        data: {



                query: "{ DEMOCards( filter: { language: ENGLISH, name: [ {
terms: Angel, operator: AND } ], setAbbreviation: [ { terms: JHT, operator:
AND } ] }, sort: { SortBy: NAME Order: ASC }, offset: 0, limit: 10) {
DEMOCards{ name printings{ name set{ name abbreviation } } printing{ name }
} currentPage totalPages hasPreviousPage hasNextPage totalResults }}",


                body: JSON.stringify({query



                  })

          }


    })



        console.log(response)

        const jsonResponse = await response.json();

        expect(response.ok()).toBeTruthy()

        expect(response.status()).toBe(200)

})


NOTE-

BUT GETTING OUT PUT AS BELOW

 Error: expect(received).toBeTruthy()

    Received: false

      18 |         console.log(response)
      19 |         const jsonResponse = await response.json();
    > 20 |         expect(response.ok()).toBeTruthy()
         |                               ^
      21 |         expect(response.status()).toBe(200)

REGARDS

**Comment by DanteUkraine** [comment]
Just use normal integration. 
https://www.npmjs.com/package/playwright-graphql?activeTab=readme
