### ISSUE TITLE
[BUG] AxeBuilder is not a constructor

### ISSUE THREAD

**Issue by LedaThemis** [microsoft/playwright#18562]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux 5.13 Ubuntu 20.04.4 LTS
- Node.js version: 16.14.0
- Browser: All
- Extra: Using `@axe-core/playwright`

**Code Snippet**
```ts
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright'; // 1

test.describe('homepage', () => { // 2
  test('should not have any automatically detectable accessibility issues', async ({ page }) => {
    await page.goto('https://your-site.com/'); // 3

    const accessibilityScanResults = await new AxeBuilder({ page }).analyze(); // 4

    expect(accessibilityScanResults.violations).toEqual([]); // 5
  });
});
```
This is the exact code used in the [docs](https://playwright.dev/docs/accessibility-testing#scanning-an-entire-page)

**Describe the bug**

Running the tests outputs the following:

```
TypeError: AxeBuilder is not a constructor

   6 |     await page.goto('/'); // 3
   7 |
>  8 |     const accessibilityScanResults = await new AxeBuilder({ page }).analyze(); // 4
     |                                            ^
   9 |
  10 |     expect(accessibilityScanResults.violations).toEqual([]); // 5
  11 |   });
```

**Comment by aslushnikov** [comment]
the proper way in typescript would be:

```ts
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright'; // 1

test.describe('homepage', () => { // 2
  test('should not have any automatically detectable accessibility issues', async ({ page }) => {
    await page.goto('https://your-site.com/'); // 3

    const accessibilityScanResults = await new AxeBuilder.default({ page }).analyze(); // 4

    expect(accessibilityScanResults.violations).toEqual([]); // 5
  });
});
```

Let me fix the docs

**Comment by LedaThemis** [comment]
@aslushnikov Thanks! it does work, but it loses all type safety. Any idea as to why that is happening?

https://github.com/dequelabs/axe-core-npm/blob/9557d9256bcb1415364a74dc23db2b5dabdf143b/packages/playwright/src/index.ts#L20
The package does export the `AxeBuilder` class

but the transpiled code is this
```js
// index.js
exports.default = AxeBuilder;
```

**Comment by mxschmitt** [comment]
Since this looks more like an issue how @axe-core/playwright publishes their MJS version of their package, I'm closing it for now since we can't act on it.
