### ISSUE TITLE
[Question] How do i wait before the browser close due to any error

### ISSUE THREAD

**Issue by harshith-rm** [microsoft/playwright#18567]
Hi,

I want to wait before the browser closes on encountering any error - Might be like unable to click the element, element not found or if expect fails.

**Comment by aslushnikov** [comment]
> I want to wait before the browser closes on encountering any error

@harshith-rm I'm not sure I follow; could you please re-file the issue with a code snippet, and language, and more elaborate explonation of what you want to do?
