### ISSUE TITLE
[BUG] firefox locator.waitFor: Protocol error (Page.describeNode)

### ISSUE THREAD

**Issue by ibrayevabay** [microsoft/playwright#18563]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.18.0
- Browser: Firefox
- Extra: after switching pages in context

**Describe the bug**

Only on firefox: After switching pages in context **locator.waitFor** with error below
error log
```
locator.waitFor: Protocol error (Page.describeNode): error in channel "content::12/14/3": exception while running method "describeNode" in namespace "page": Component returned failure code: 0x80040111 (NS_ERROR_NOT_AVAILABLE) [nsIDocShell.domWindow] domWindow@chrome://juggler/content/content/FrameTree.js:573:5
_describeNode@chrome://juggler/content/content/PageAgent.js:442:30
_onMessage@chrome://juggler/content/SimpleChannel.js:194:37
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:53:44
 _onMessage@chrome://juggler/content/SimpleChannel.js:178:24
bindToActor/actor.receiveMessage@chrome://juggler/content/SimpleChannel.js:53:44
```

**Comment by aslushnikov** [comment]
@ibrayevabay This looks like a bug! Any chance you can provide us with a snippet that we can run locally to reproduce & debug this?

**Comment by ibrayevabay** [comment]
@aslushnikov 
I cannot provide code snippet but can only retell Detailed steps to reproduce: 
1. Create browser context 
2. create new page
3. click element that opens a new Tab
4. switch context to new page 
we are using something like this:
```
    const pages = page.context().pages();
    page = pages[1];
```
5. try to Interact with elements (in our case` page.locator(LOCATOR).waitFor({ state: 'visible' });`)

**Comment by aslushnikov** [comment]
@ibrayevabay these steps unfortunately didn't reproduce this for me. I tried the following and it worked:

```js
// a.mjs
import { firefox } from '@playwright/test';

const browser = await firefox.launch();
const page = await browser.newPage();
await page.setContent(`
  <button>clickme</button>
`);
await page.evaluate(() => {
  document.querySelector('button').addEventListener('click', () => {
    window.open('https://playwright.dev', '_blank');
  }, false);
});
const [popup] = await Promise.all([
  page.waitForEvent('popup'),
  page.getByText('clickme').click(),
]);
await popup.getByRole('link', { name: 'Docs' }).click();

await browser.close();
```

Without repro, this is not actionable! Please re-file the issue with a repro similar to the one I did above that reproduces the behavior for you. This way we'll have something to look at.
