### ISSUE TITLE
Does Playwright support windows based applications?

### ISSUE THREAD

**Issue by isherkhan** [microsoft/playwright#18575]
HI

I am trying do record some of the mouse Events on the windows based application that in turn launches the web browser.

does playwright support capturing the windows events?(i Know it is a web based tool wanted to make sure if there is away to do it)

**Comment by yury-s** [comment]
Playwright does not support windows applications, but if the app uses WebView2 you should be able to debug it following [this document](https://playwright.dev/docs/webview2) or if it launches a new standalone Chromium-based browser you may be able to connect to it via [connectOverCDP](https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp), you'll have to make sure the browser is launched with --remote-debugging-port=... option.

**Comment by kmturley** [comment]
Someone appears to have tried it here:
https://ttcglobal.com/what-we-think/blog/playwright-selenium-desktop-application-automation-testing
