### ISSUE TITLE
[Question] await use()

### ISSUE THREAD

**Issue by HanLiu1976** [microsoft/playwright#18572]
Hi Experts. This is the sample code coming from plawright.dev. my question is : the "use" for what? preserved key words ? and what's doing ? actually I can change the "use" to whatever name I want. This confused me the function really action is .

```ts
import { test as base } from '@playwright/test';
import { TodoPage } from './todo-page';

// Extend basic test by providing a "todoPage" fixture.
const test = base.extend<{ todoPage: TodoPage }>({
  todoPage: async ({ page }, **use**) => {
    const todoPage = new TodoPage(page);
    await todoPage.goto();
    await todoPage.addToDo('item1');
    await todoPage.addToDo('item2');
    await **use**(todoPage);
    await todoPage.removeAll();
  },
});

test('should add an item', async ({ todoPage }) => {
  await todoPage.addToDo('my item');
  // ...
});

test('should remove an item', async ({ todoPage }) => {
  await todoPage.remove('item1');
  // ...
});
```

**Comment by weyert** [comment]
`use` for using the `todoPage` in your `test()`-function below, above it is for setting up the value `todoPage` in this `test`-function after the promise resolves, typically after the `test`-function completes it will call the rest, e.g. for cleaning up stuff

**Comment by HanLiu1976** [comment]
> `use` for using the `todoPage` in your `test()`-function below, above it is for setting up the value `todoPage` in this `test`-function after the promise resolves, typically after the `test`-function completes it will call the rest, e.g. for cleaning up stuff

Thank you weyert, I am wondering this "use" function must be used in the async second parameter or not? and any backend operations that  the "use" done ? now I can't find any operations definition in the "use" function. so this puzzled me what this function really did.

**Comment by yury-s** [comment]
Without calling `use` you would get todoPage=undefined in

```js
test('should add an item', async ({ todoPage }) => {
...
});
```
As mentioned in the above answer this is the way fixture value is passed to the tests.
