### ISSUE TITLE
Playwright tests/behaves differently when running in parallel [BUG]

### ISSUE THREAD

**Issue by ThibaultJanBeyer** [microsoft/playwright#18578]
## Describe the bug
- Running my tests using multiple workers, they pass
- Running tests on GitHub actions using a single worker, they fail

## example
I narrowed down the problem, it has to do with async and/or computational heavy actions that get triggered by a mouse interaction. Basically:
- listens to the mouse events
- do something intensive or async
- go a few hoops back and store the event value
- from the test grab the stored value in the assertion

This will pass (most of the time, not always) on your machine if you have a good one but fail (most of the time) on the remote test

- [See example repo: https://github.com/ThibaultJanBeyer/playwright-race-condition](https://github.com/ThibaultJanBeyer/playwright-race-condition)

## ideas
- There could be an option that one mouse interaction to another mouse interaction only happens when the event loop is clear
  - ~~I believe this is done with the`requestIdleCallback`, which unfortunately is [not (yet) supported by safari](https://caniuse.com/requestidlecallback)~~ while this would work with sync computation, unfortunately this will not wait for timeouts
  - await page.waitForTimeout would help to overcome the timeouts but does not help overcoming other async actions

I’ll try out the idea listed above, but if you have any other ideas, happy to hear them!

## Context:
- Playwright Version: 1.27.1
- Operating System: MacOs 13.0 (22A380)
- Node.js version: 14.18.2
- Browser: All

**Moar Context**
Hello 👋 , I am working on a library called ([dragselect](https://github.com/ThibaultJanBeyer/DragSelect/) (if you are interested, you can compare the puppeteer setup from the playwright by checking out the tests/playwright branch)) that does listen for mouse interaction, calculates mouse positions and elements in between, and a lot more to provide a selection and drag and drop functionality. I have no issues testing it with Puppeteer, today, however, I wanted to switch to playwright because it is faster, supposedly non-flaky, and I thought would integrate better with GitHub-actions (puppeteer is extremely slow on them) and VSCode. So I tried it out but seems like it is flakier than puppeteer for my use case.

**Comment by yury-s** [comment]
Your test is inherently flaky as mouse events are dispatched asynchronously (all the calls to PS.publish). If it passes for you locally you are just lucky, try increasing the timeouts to 1000 and the test will be always failing. The reason for that is that `page.mouse.down()` and other mouse actions wait only while corresponding DOM event is dispatched but not for any async handlers such event could trigger. If you know that such async handlers should be triggered and want to check that you can use `expect.poll`:

```js
await expect.poll(() => page.evaluate(() => window.up)).toBe(2);
```
