### ISSUE TITLE
[Question] Reload the page until element contains text

### ISSUE THREAD

**Issue by pgarbocz89** [microsoft/playwright#18574]
I'm running tests right after application deployment. Sometimes the application is not ready to use yet and has to be reloaded.

I'd like to check in a loop if a specific element contains a text (which means that the app is ready). If not, then reload page and check again.

I tried several options, but none of it worked, so I wonder if there's some known solution for cases like that.

**Comment by jfgreffier** [comment]
Doesn't sound like a good idea.

Maybe deploy your app and have a healthcheck in the CI before launching the tests ? It's probably easy if you're using Docker or K8S

You can have Playwright Test wait for the server to be up and running.  
https://playwright.dev/docs/test-advanced#launching-a-development-web-server-during-the-tests

`page.goto()` options can probably help  
https://playwright.dev/docs/api/class-page#page-goto

In a last resort, you can adjust timeouts if needed  
https://playwright.dev/docs/test-timeouts

**Comment by pgarbocz89** [comment]
I haven't thought about the healthcheck, that's a good idea. Will do it that way then, thanks!
