### ISSUE TITLE
Why my playwright tests are running locally but not found on azure pipeline?

### ISSUE THREAD

**Issue by sonitandon** [microsoft/playwright#18588]
Getting this exception :
Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

**Comment by yury-s** [comment]
Can you share code of the project that works for you locally but not on azure pipeline? Without that it's hard to tell more than what you already see in the list of possible reasons.

**Comment by sonitandon** [comment]
This was the yml : 
steps:
  # install node
  - template: steps/node-installer.yml@templates
    parameters:
      useSpecificNodeVersion: true
      nodeVersion: '16.x'
    
  # NPM install
  - script: npm ci
    displayName: 'NPM Install'
    workingDirectory: 'RecordingUI'

   # Install Playwright browsers and dependencies
  - script: 'npm install @playwright/test'
  - script: ' npx playwright install --with-deps'
    displayName: 'Install Playwright'
     
  # Run Playwright tests   
  - script: 'npx playwright test'
    displayName: 'Run playwright Tests'
   
   # Publish test results
  - task: PublishTestResults@2
    displayName: 'Publish test results'
    inputs:
      testResultsFiles: '**/junit-result-*.xml'
      mergeTestResults: true
    condition: succeededOrFailed()
    continueOnError: true

**Comment by klepik1990** [comment]
what's an error you get?

**Comment by sonitandon** [comment]
Do you think I am using two scripts to install playwright is causing the issue?

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
