### ISSUE TITLE
[BUG] test.step returning undefined

### ISSUE THREAD

**Issue by mmkal** [microsoft/playwright#18585]
<details>
<summary>**Context:**</summary>

## System:
 - OS: macOS 11.4
 - Memory: 1.28 GB / 64.00 GB
## Binaries:
 - Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
 - Yarn: 1.22.18 - /usr/local/bin/yarn
 - npm: 8.6.0 - ~/.nvm/versions/node/v14.17.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - @playwright/test: 1.24.0
</details>

**Code Snippet**

The snippet directly from the [`test.step` docs](https://playwright.dev/docs/api/class-test#test-step), unmodified, doesn't work:

```javascript
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  const user = await test.step('Log in', async () => {
    // ...
    return 'john';
  });
  expect(user).toBe('john');
});
```

**Describe the bug**

The types work but it fails with:

```
yarn run v1.22.18
$ playwright test test-svc --debug -u

Running 1 test using 1 worker
  1) [chromium] › test-svc.spec.ts:72:1 › test =====================================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "john"
    Received: undefined

      75 |     return 'john'
      76 |   })
    > 77 |   expect(user).toBe('john')
         |                ^
      78 | })
      79 |
```

**Comment by yury-s** [comment]
Which playwright version is this?

**Comment by mmkal** [comment]
Sorry, seems the npx envinfo cmd found the wrong package. It's 1.24.0, I've updated the PR body.

**Comment by yury-s** [comment]
test.step supports return value starting from [v1.25.0](https://github.com/microsoft/playwright/releases/tag/v1.25.0), you need to update playwright to at least that version.

**Comment by mmkal** [comment]
Aah. Was confusing because the types implied that the return value would be used, so didn't occur to me an update was needed.
