### ISSUE TITLE
[Feature] sync API

### ISSUE THREAD

**Issue by bootstraponline** [microsoft/playwright#1858]
>Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?

In this [web automation framework evaluation](https://github.com/software-platform/web_test_infra#frameworks), playwright and other frameworks were compared.

[webdriverio's](https://github.com/webdriverio/webdriverio) API had the best developer experience  because they're using [node fibers](https://github.com/laverdet/node-fibers) in [wdio-sync](
https://github.com/webdriverio/webdriverio/tree/master/packages/wdio-sync) to provide a synchronous API. Synchronous APIs are easier to use for both developers and QA teams.

What do you think about adding sync API support to playwright?

**Comment by bootstraponline** [comment]
> NOTE OF OBSOLESCENCE -- The author of this project recommends you avoid its use if possible. The original version of this module targeted nodejs v0.1.x in early 2011 when JavaScript on the server looked a lot different. Since then async/await, Promises, and Generators were standardized and the ecosystem as a whole has moved in that direction.
>
> https://github.com/laverdet/node-fibers

It looks like there's no supported way to provide a synchronous API for automation. If anyone figures out how to do this, let me know. I'm closing the feature request.

**Comment by daguar** [comment]
Since this issue is currently the top Google result for "playwright synchronous" I wanted to drop a link reference for Playwright for Python, which supports a synchronous API for Playwright now! https://playwright.dev/python/docs/intro/#usage 

Hope the breadcrumps help someone!
