### ISSUE TITLE
[BUG] Start debug from particular line in playwright

### ISSUE THREAD

**Issue by harshith-aimyth** [microsoft/playwright#18593]
There is no way to start the debug from particular line in playwright unlike other editors like eclipse/IntelliJ

Consider i have 50 line of code, if i want to debug the script from line 29. Playwright doesn't support this

**Comment by jfgreffier** [comment]
You have several ways to do that.

Breakpoint with the VSCode extension
https://playwright.dev/docs/getting-started-vscode#run-in-debug-mode

With Playwright Inspector in command-line
```
npx playwright test example.spec.ts:42 --debug
```
https://playwright.dev/docs/running-tests#debugging-tests

Thru `page.pause()` with Playwright Inspector
https://playwright.dev/docs/running-tests#debugging-tests

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
