### ISSUE TITLE
[BUG] when given a blank value string, toHaveAttribute always fails with "serializes to the same string"

### ISSUE THREAD

**Issue by jmuheim** [microsoft/playwright#18592]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac 12.5
- Node.js version: v16.14.2
- Browser: Only tested on Chromium
- Extra: I just updated from Playwright 1.21 (everything worked there)

I just updated playwright from 1.21 to 1.27, and since then all of the following assertions seem to fail:

```javascript
expect(element).toHaveAttribute('required', '') // Check that an attribute simply exists **without** a value, e.g. <input type="text" required>
```

The error message always is:

```
Expected string: ""
Received string: serializes to the same string
```

Any help is highly appreciated. :pray:

This seem to be related: https://github.com/microsoft/playwright/issues/16517. I have already tried some work arounds, but nothing seems to work reliably.

This sometimes works:

    expect(await element.getAttribute("attr")).toBeNull();

But then again, it fails, complaining the the received result was `""`. But when changing it to:

    expect(await element.getAttribute("attr")).toBe("");

...it again complains that the received result was `null`. I'm not 100% sure whether there's a pattern behind that which I don't see. But anyway, the original `toHaveAttribute('required', '')` should work in any case, shouldn't it?!

**Comment by jmuheim** [comment]
For the records: in v1.21, the following workaround does what I need:
```javascript
await expect(element).toHaveAttribute('required', ''); // Check that an attribute simply exists **without** a value, e.g. <input type="text" required>
expect(await filterInput.getAttribute('aria-invalid')).toBeNull(); // Makes sure that the attribute **does not** exist at all
```

**Comment by luckyluck** [comment]
I faced the same issue. I do not understand why, but we have been using [v1.27.0]([v1.27.0](https://github.com/microsoft/playwright/releases/tag/v1.27.0)), which worked three days ago.

Currently, this line is failing:
`await expect(page.locator(gameModeSwitch)).toHaveAttribute('checked', '');`

I was able to fix it this way:
`expect(
      await page.locator(gameModeSwitch).getAttribute('checked')
    ).toBeFalsy();`

Any ideas on why this is happening?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by amarose** [comment]
I think i just faced exact same problem and i figured how to 'solve' it.

First approach you should try is to swap .toHaveAttribute method with strict equalision, for example:
```
    const resultAttr = await yourSelector.getAttribute("checked", {timeout: 1000});
    expect(resultAttr).toStrictEqual("");
```
and it should work.

If still you are getting the same error there is a high probability that you are trying to get that attribute before the UI actually changes element and its properties (which was my case). 
Solution for that was to wait for element to be editable.
So adding **await yourSelector.isEditable()** before scrapping attribute from it might work for you.
Note that .isVisible() wont do the job as element probably will be displayed in DOM before it is interactable in browser
