### ISSUE TITLE
[Question]: How to click this checkbox?

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#18590]
### Your question

When i  click a button , it appears this.  how to select and click?
![QQ图片20221105183101](https://user-images.githubusercontent.com/16624529/200116332-ffb450b6-8a81-42a4-8a5f-49c3bd80c34b.png)

**Comment by yury-s** [comment]
See [this guide](https://playwright.dev/python/docs/input#mouse-click) for introduction on working with actions. The following javascript snippet does it for Google demo page, but note that real captcha pages may detect if browser is controlled by an automation tool. Overcoming that is not a priority for playwright as our main goal is test automation.

```js
import { test, expect, TestInfo } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/recaptcha/api2/demo');
  await page.frameLocator('[title="reCAPTCHA"]').getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.getByRole('button', { name: 'Submit' }).click();
  await expect(page).toHaveURL('https://www.google.com/recaptcha/api2/demo');
});
```
