### ISSUE TITLE
[Question]How to bind extraHTTPHeaders to the specified URL

### ISSUE THREAD

**Issue by ldy12347** [microsoft/playwright#18605]

**Comment by yury-s** [comment]
[extraHTTPHeaders](https://playwright.dev/docs/api/class-testoptions#test-options-extra-http-headers) specified in the config apply to all requests from all pages created by playwright fixtures. If you want to apply them only to particular URL you can add the headers to selected request via [request interception](https://playwright.dev/docs/network#modify-requests).
