### ISSUE TITLE
[Question] Run on synology, shared libraries is missing

### ISSUE THREAD

**Issue by ordimans** [microsoft/playwright#18604]
Hello

I am trying to run a node app with playwright code. 
It run smoothly until yesterday (my /dev/md0 was full)
And now i cannot running.

I installed browser in the app folder.

So i have this :

`drwxr-xr-x+ 1 xxx users   3914 Nov  6 00:26 node_modules
drwxr-xr-x+ 1 xxx users     66 Nov  6 01:13 chromium-1028
drwxr-xr-x+ 1 xxx users     98 Nov  6 01:13 ffmpeg-1007
drwxr-xr-x+ 1 xxx users     56 Nov  6 01:14 firefox-1357
drwxr-xr-x+ 1 xxx users    146 Nov  6 01:14 webkit-1724
-rwxrwxrwx  1 xxx users 135871 Nov  6 21:57 package-lock.json
-rwxr-xr-x  1 xxx users  33191 Nov  6 23:35 app.js`

When i run , have this : 

` P[18543] - browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /volume1/docker/IVT_Bot/chromium-1028/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-6Od1CG --remote-debugging-pipe --no-startup-window
<launched> pid=18587
[pid=18587][err] /volume1/docker/IVT_Bot/chromium-1028/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory`

error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

I don't know how can i installed on Synology directly, without apt-get.
And don't know how i am running until yesterday.

Result of commands : 

root@SynoAJT:/volume1/docker/IVT_Bot# npx playwright --version
Version 1.27.1
root@SynoAJT:/volume1/docker/IVT_Bot# npm ls @playwright/test
IVT_Bot@1.0.0 /volume1/docker/IVT_Bot
└── (empty)

root@SynoAJT:/volume1/docker/IVT_Bot# npm ls playwright
IVT_Bot@1.0.0 /volume1/docker/IVT_Bot
└── playwright@1.27.1

**Comment by yury-s** [comment]
Since the disk was full the installation failed and some of the files have not been installed. To fix that delete playwright, delete installed browsers (see [this doc](https://playwright.dev/docs/browsers#installing-browsers) for default locations if deleting the app folder doesn't help), make sure there is enough free space on disk and install playwright and browsers again.

**Comment by ordimans** [comment]
> Since the disk was full the installation failed and some of the files have not been installed. To fix that delete playwright, delete installed browsers (see [this doc](https://playwright.dev/docs/browsers#installing-browsers) for default locations if deleting the app folder doesn't help), make sure there is enough free space on disk and install playwright and browsers again.

I tried, to remove old install, and reinstall in node module.
But i did this :
Something i am wrong ??

```
sudo npm remove playwright

removed 2 packages, and audited 183 packages in 1s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

Nothing in 
```
 cd /root/.cache/ms-playwright/
-ash: cd: /root/.cache/ms-playwright/: No such file or directory

root@SynoAJT:/volume1/docker/IVT_Bot# PLAYWRIGHT_BROWSERS_PATH=0 npx playwright install
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.

```
Next : 
```
 PLAYWRIGHT_BROWSERS_PATH=0 npm instal playwright

up to date, audited 185 packages in 3s

46 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
OK 👍 


And next : 

```
[pid=29196][err] /volume1/docker/IVT_Bot/node_modules/playwright-core/.local-browsers/chromium-1028/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory
[pid=29196] <process did exit: exitCode=127, signal=null>
[pid=29196] starting temporary directories cleanup
```

**Comment by ordimans** [comment]
apt-get is not available on synology, so cannot install dependencies.
I am running by docker now. Seems to be good, with this option
PLAYWRIGHT_BROWSERS_PATH=0
