### ISSUE TITLE
[BUG] waitForSelector with visibility: 'visible' causes timeout

### ISSUE THREAD

**Issue by azazrehman** [microsoft/playwright#1860]
**Context:**
- Playwright Version: 0.13.0
- Operating System: Windows 10 Pro

**Code Snippet**

Here is my code which i use for waiting the element after that i have to click
**Puppeteer**  :heavy_check_mark:
```javascript
   await page.waitForSelector(selector, { visible: true, timeout: 30000}) 
```
**Playwright** :x:
```javascript
    await page.waitForSelector(selector, { visibility: 'visible', timeout: 30000}) 
```
          
        

**Describe the bug**
Exception through after the timeout end:

> _TimeoutError: waiting for element to be displayed and  not moving failed: timeout exceeded_

if i remove the visibility option it work smmothly, and also some time it works but still wait.

Related issue in puppeteer
[https://github.com/puppeteer/puppeteer/issues/4356](https://github.com/puppeteer/puppeteer/issues/4356)

#https://github.com/puppeteer/puppeteer/pull/4373

This is my first issue on Github so sorry in advance if there's any mistake.:slightly_smiling_face:

**Comment by mxschmitt** [comment]
In Playwright, its done via the `waitFor` property. Reference: https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectorselector-options

Example:
```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.webkit.launch();
  const page = await browser.newPage();
  await page.evaluate(() => document.write(`
    <div id="foo">bar</div>
  `))
  await page.waitForSelector("#foo", {
    waitFor: "visible",
  })
  console.log("done")
  await browser.close()
})();
```

Or interactive: https://try.playwright.tech/?s=z6ciw

**Comment by azazrehman** [comment]
Thank you so much @mxschmitt its working.

**Comment by raphaellueckl** [comment]
Up to date example:

```
const playwright = require("playwright");

(async () => {
  const browser = await playwright.webkit.launch();
  const page = await browser.newPage();
  await page.evaluate(() => document.write(`
    <div id="foo">bar</div>
  `))
  await page.waitForSelector("#foo", {
    state: "visible", // 'hidden', ...
  })
  console.log("done")
  await browser.close()
})();
```
