### ISSUE TITLE
[Question] [Codegen] DPR in codegen?

### ISSUE THREAD

**Issue by joshmar** [microsoft/playwright#18610]
Heey Playwrighters!

I was wondering if it is possible to specify the DPR (Device Pixel Ratio) for the code generator. I know its possible for the [test variant itself](https://github.com/microsoft/playwright/issues/2113) but as far as I've been able to find not for the [code generator](https://github.com/microsoft/playwright/blob/main/docs/src/codegen.md)?

Could someone shed some more light on this?

**Comment by yury-s** [comment]
There is no separate option for DPR but you can pass --device option that would be use to emulate the device with particular DPR (and other options):

```sh
 npx playwright codegen --device "iPhone 11" wikipedia.org
```
Would that work for you?

**Comment by joshmar** [comment]
That honestly would work for now. 

Its a bit harder to see the settings and know what you're dealing with but it could work, would be nice to maybe see it added in the future though.

**Comment by yury-s** [comment]
Will keep an eye on the requests for this and may add a dedicated option in the future. Closing the issue for now as part of triaging process since there is an immediate workaround.
