### ISSUE TITLE
Click is not working, to read the api response. causing  error page.waitForResponse: Page closed

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#18614]
Hi, the last line that is supposed to click the button, is not executing.
```javascript
const [auctionResponse] = await Promise.all([
    page.waitForResponse(res =>
        res.status() == 200
        &&
        res.url() == "https://golden/vacation/auctions"
    ),

    page.locator('text=Create a New Auction').click(),
    page.locator('text=Select Option').click(),
    page.locator('text=2027').click(),
    page.locator('[data-testid="wizard-next-button--cbna-wizard"]').click(),  -----> for some reason this button(last line) is not clicked by the playwright , Can you please advise? 
]) 
```
I want to capture the api response after the click (button --> wizard-next-button--cbna-wizard).

if i execute just these 4 lines ,they work fine , but not inside the above block, is there any reason ? Please advise.
```javascript
 await page.locator('text=Create a New Auction').click();
 await page.locator('text=Select Option').click();
 await page.locator('text=2027').click();
await page.locator('[data-testid="wizard-next-button--cbna-wizard"]').click();
```

Seeing the following error:
 Test timeout of 30000ms exceeded.

    page.waitForResponse: Page closed

      35 |
      36 |         const [auctionResponse] = await Promise.all([
    > 37 |             page.waitForResponse(res =>
         |                  ^
      38 |                 res.status() == 200
      39 |                 &&
      40 |                 res.url() == "https://golden/vacation/auctions"

**Comment by InduKrish** [comment]
```javascript
 await page.locator('text=Create a New Auction').click(),
  await  page.locator('text=Select Option').click(),
   await page.locator('text=2027').click(),

const [auctionResponse] = await Promise.all([
    page.waitForResponse(res =>
        res.status() == 200
        &&
        res.url() == "https://golden/vacation/auctions"
    ),

  page.locator('[data-testid="wizard-next-button--cbna-wizard"]').click()
]) 
```
after i moved three lines outside ,it worked. is there any reason why it doesnt work when all 4 lines are inside promise?

**Comment by yury-s** [comment]
> after i moved three lines outside ,it worked. is there any reason why it doesnt work when all 4 lines are inside promise?

When you run all actions inside `Promise.all` all of them start running at the same time. It looks like some of them depend on the result of the previous ones in which case you should do separate `await` per action.

If you know for sure that request to `https://golden/vacation/auctions` is triggered by the latest click you should only include that one into Promise.all and run previous actions in order waiting for them to complete.
