### ISSUE TITLE
[BUG] Selector generator generates invalid utf8 selectors for icons

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#18626]
1. Open Codegen
2. Goto: https://fontawesome.com/icons/magnifying-glass?s=solid&f=classic or [here](https://dotnetpodcasts.azurewebsites.net/show/c0e35c5d-bdd5-4e5c-6903-08d9b42c62b0) (Subscribe button)
3. hover over the icons.

Expected: no broken utf8 char
Actual: broken utf8 char

<img width="440" alt="image" src="https://user-images.githubusercontent.com/17984549/200434446-77f44551-2c06-417d-8d0a-cfb0fbd018b1.png">

**Comment by mxschmitt** [comment]
It tries to get the content from the icon:

<img width="637" alt="image" src="https://user-images.githubusercontent.com/17984549/200435030-3f87095f-c3ec-47cf-9fc7-b170e062455f.png">

here:

https://github.com/microsoft/playwright/blob/1cee65722bc45ace5edfc0843654a2ba9ef35608/packages/playwright-core/src/server/injected/roleUtils.ts#L598

**Comment by dgozman** [comment]
@mxschmitt I looked at the both sites, and they have `"\uE901"` and `"\uF002"` characters respectively. These are both valid characters from the [Private Use Area](https://www.unicode.org/faq/private_use.html), so we might as well use them. Are there any issues that you've encountered?

**Comment by MitchKuijpers** [comment]
Hi, I am having troubles with this same issue, using fontawesome inside a button. Since the button name is the content and not the actual button name. How can I edit the recording so that it will be able to click on it?

I tried someting like this but that also doesn't work.
    await Page.Locator("#IdOfParent").GetByRole(AriaRole.Button, new() { Name = "\\f077" }).ClickAsync();
