### ISSUE TITLE
Post api response not returned 

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#18620]
```javascript
 const [auctionResponse] = await Promise.all([
            page.waitForResponse(res =>
                res.status() == 200
                &&
                // res.url() == "https://service.aws.spa.com/golden/vacation/auctions" ---> not working, error below.
              //  res.url().includes('/vacation/auctions')  --> this one return the response of the second api ,where as i wanted the response from the first api call.
                res.url().endsWith('/vacation/auctions'). --> not working, error is listed below.
            ),

            actor.attemptsTo(Click.on('Id', 'wizard-next-button--cbna-wizard'))
        ]);
       const auctionResult = JSON.stringify(await auctionResponse.json())
        console.log(" result " + auctionResult)
        const accrualUrl = JSON.parse(auctionResult)._links.self.href;
        console.log( "url" + accrualUrl )
```

after clicking wizard-next-button--cbna-wizard button, 
This URL loads first --> 1. https://service.aws.spa.com/golden/vacation/auctions (POST call)
2.and then the second url --> https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters (GET Call)

when i run  res.url().includes('/vacation/auctions')  , it returns the response from the second call which is https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters (GET Call)
But i expected to read the response from the POST call , the first url --> https://service.aws.spa.com/golden/vacation/auctions (POST call)

hence i tried with  res.url().endsWith('/vacation/auctions'), but when i use endsWith, i see the error and it doesnt return the api response.
  Test timeout of 30000ms exceeded.

    page.waitForResponse: Page closed

      56 |
      57 |         const [auctionResponse] = await Promise.all([
    > 58 |             page.waitForResponse(res =>
         |                  ^
      59 |                 res.status() == 200
      60 |                 &&
      61 |                 // res.url() == "https://service.aws.spa.com/golden/vacation/auctions"

first api call:
Request URL: https://service.aws.spa.com/golden/vacation/auctions
second api call:
Request URL: https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/18614

**Comment by InduKrish** [comment]
Can you please advise what changed i have to make on the above snippet to get this working?
