### ISSUE TITLE
[BUG] The test gets stuck on the page.pause()  with appeared playwright debugger while running by vscode extension

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#18637]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Node.js version: 16
- Browser: Chrome and MSEdge
- VSCode extension version: 0.2.13

**Code Snippet**

```javascript

test('homepage has Playwright in title and get started link linking to the intro page @testing', async ({ page }) => {
  allure.epic('Testing Module');

  await page.goto('https://playwright.dev/');

   // Pause test here - please un-comment this
  // await page.pause();

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
```

**Describe the bug**

While running the test via VSCode extension - the test gets stuck in case we have the `page.pause()` function. 
In this case, the test stops without presenting the Playwright debugger and without any option to continue with the test running. 

But if the same scenario will be executed by CLI command `npx playwright test --headed` - the test will stop and the Playwright debugger will be presented. 

See the repo with my code (it has 2 branches with msedge and chrome browsers):
[Repo](https://github.com/AlexKomanov/playwright-pause-issue)

The pausing command is under comment.

See the video of the issue:

https://user-images.githubusercontent.com/52656401/200535034-f254e1dc-8e8e-4528-b01c-f0c569f423e3.mp4

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/17059 with the same answer:

> We allow one debugger at a time, when using VS Code, you should use regular JS debugger w/ debugger; statement and breakpoints instead!
