### ISSUE TITLE
[BUG] ScreenDiff plugin doesn't work in allure report for failed VisualComparison tests

### ISSUE THREAD

**Issue by ivan-krupskyi** [microsoft/playwright#18638]
**Context:**
- Playwright Version: 
- "@playwright/test": "^1.27.1",
    "allure-commandline": "^2.18.1",
    "allure-playwright": "^2.0.0-beta.19",

- Operating System: Mac
- Node.js version: 16.15.1
- Browser: N/A
- Extra: [any specific details about your environment]

ScreenDiff plugin doesn't work for failed VisualComparison tests. There is no "diff" and "overlay" options in the report. Only expected and actual and diff screenshots are attached:

<img width="722" alt="Screen Shot 2022-11-08 at 10 16 55" src="https://user-images.githubusercontent.com/102296081/200538644-4137aad8-de80-48c9-ae7c-42f48954c5ae.png">

**Comment by yury-s** [comment]
Please file this issue in the [allure repo](https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md) instead.
