### ISSUE TITLE
[Question] Is there anyway that open chromium browser minimized?

### ISSUE THREAD

**Issue by lubiksss** [microsoft/playwright#18633]
I want to open the browser minimized
because it is very annoying to steal the focus of the computer when the browser window is open.
Is there anyway that open chromium browser minimized?
** In my case, I can't run playwright in headless mode, and I don't want to

**Comment by yury-s** [comment]
We recommend using headless for running the tests, among other things it automatically avoids all the issues with the stolen focus. There is no builtin api to open chromium minimized, you can try passing custom --window-size= and --window-size= [launch options](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options) to the browser.
