### ISSUE TITLE
Not able to click on a datapoint for <path> element

### ISSUE THREAD

**Issue by shirshGit** [microsoft/playwright#18643]
### Discussed in https://github.com/microsoft/playwright/discussions/18642

<div type='discussions-op-text'>

<sup>Originally posted by **shirshGit** November  8, 2022</sup>
I Have a graph which is as below:

*<g class="Chart_line_4eOS7" transform="translate(0 0)" data-testid="g-root-container"><path class="Chart_path_2fyhd " d="M1.5691326041666667,161.9520386991758L12.423299270833333,96.05517154418422L23.2774659375,231.52452514414756L34.13163260416666,186.68804521017458L44.98579927083334,178.8416612217293L55.8399659375,156.30191317904098L66.69413260416667,194.00586906931693L77.54829927083333,147.972534589681L88.4024659375,135.46327819617824L99.25663260416667,146.9609798594633L110.11079927083333,198.3224434586242L120.9649659375,58.69751366965852L131.81913260416667,185.02642227495215L142.67329927083335,55.009743572108164L153.5274659375,107.44047823744512L164.38163260416667,103.57044602634204L175.23579927083335,145.68514506459417L186.0899659375,217.1501197886218L196.94413260416667,141.73309490239234L207.79829927083335,65.6842280225134L218.6524659375,103.42767403739236L229.50663260416667,218.98489173171936L240.36079927083335,159.88336371035228L251.2149659375,201.62138771392873L262.06913260416667,183.57136306842278L272.9232992708333,74.92795488152964L283.7774659375,184.2700345037083L294.63163260416667,226.49409081009205L305.4857992708333,104.533397526279L316.3399659375,211.32988296250443L327.19413260416667,156.0953494503479L338.0482992708333,204.55277004023523L348.9024659375,80.58719350734208L359.75663260416667,212.7606405538934L370.6107992708333,137.4468975320105L381.4649659375,86.20694200855144L392.31913260416667,154.35170856402672L403.1732992708333,15.537845180370738L414.0274659375,112.16410468035352L424.88163260416667,91.05815193094674L435.7357992708333,128.09685110675517L446.5899659375,0L457.44413260416667,121.13443836904065L468.2982992708333,118.23647076355215L479.1524659375,157.65065281933124L490.00663260416667,41.73498630168393L500.8607992708333,138.7713355571604L511.7149659375,98.84074417964857" style="stroke: rgb(93, 158, 212);"></path></g>*

Now when I mouse hover on any data point defined in path <circle> tags get added dynamically. 
<img width="775" alt="image" src="https://user-images.githubusercontent.com/13121844/200569561-18f1467d-c43e-41ae-9468-7502d0545f50.png">

My question is how can I click or mousehover on any data point defined in path. 

Is there any way I can do this by using Javascript, then I can use that inside page.eval().</div>

**Comment by shirshGit** [comment]
Element looks like below:

<g class="Chart_line_4eOS7" transform="translate(0 0)" data-testid="g-root-container"><path class="Chart_path_2fyhd " d="M1.5691326041666667,161.9520386991758L12.423299270833333,96.05517154418422L23.2774659375,231.52452514414756L34.13163260416666,186.68804521017458L44.98579927083334,178.8416612217293L55.8399659375,156.30191317904098L66.69413260416667,194.00586906931693L77.54829927083333,147.972534589681L88.4024659375,135.46327819617824L99.25663260416667,146.9609798594633L110.11079927083333,198.3224434586242L120.9649659375,58.69751366965852L131.81913260416667,185.02642227495215L142.67329927083335,55.009743572108164L153.5274659375,107.44047823744512L164.38163260416667,103.57044602634204L175.23579927083335,145.68514506459417L186.0899659375,217.1501197886218L196.94413260416667,141.73309490239234L207.79829927083335,65.6842280225134L218.6524659375,103.42767403739236L229.50663260416667,218.98489173171936L240.36079927083335,159.88336371035228L251.2149659375,201.62138771392873L262.06913260416667,183.57136306842278L272.9232992708333,74.92795488152964L283.7774659375,184.2700345037083L294.63163260416667,226.49409081009205L305.4857992708333,104.533397526279L316.3399659375,211.32988296250443L327.19413260416667,156.0953494503479L338.0482992708333,204.55277004023523L348.9024659375,80.58719350734208L359.75663260416667,212.7606405538934L370.6107992708333,137.4468975320105L381.4649659375,86.20694200855144L392.31913260416667,154.35170856402672L403.1732992708333,15.537845180370738L414.0274659375,112.16410468035352L424.88163260416667,91.05815193094674L435.7357992708333,128.09685110675517L446.5899659375,0L457.44413260416667,121.13443836904065L468.2982992708333,118.23647076355215L479.1524659375,157.65065281933124L490.00663260416667,41.73498630168393L500.8607992708333,138.7713355571604L511.7149659375,98.84074417964857" style="stroke: rgb(93, 158, 212);"></path></g>

**Comment by shirshGit** [comment]
[element.txt](https://github.com/microsoft/playwright/files/9961311/element.txt)


Element is as above

**Comment by yury-s** [comment]
You can use raw [mouse API](https://playwright.dev/docs/api/class-mouse) to generate mouse events or pass [custom x, y](https://playwright.dev/docs/api/class-locator#locator-click-option-position) position within the element to click on. Would that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
