### ISSUE TITLE
[BUG] Webkit browsers not authenticating using storage state session information and OAuth2

### ISSUE THREAD

**Issue by jhilber** [microsoft/playwright#18647]
- Playwright Version: 1.27 (current)
- Operating System: Windows
- Node.js version: 16.15
- Browser: Webkit
- OAuth2 provider: Microsoft

Issue:
Unable to go to a url using a Webkit browser and the web application uses OAuth2 authorization using storage state session information.  Page attempts to go to the url, but then never authenticates and loops until timeout.  Unable to trap the error in console because the loop refreshes the browser.

This was working with version 1.22 of Playwright.  I determined that it started failing in version 1.23 with Webkit 15.4 (v1668).  This is not an issue with Chromium or Firefox browsers.

**Comment by yury-s** [comment]
Please share an example code that triggers the error we cannot help without seeing your code and what is not working there. It may well be that the web site doesn't like the new user agent or something like that, hard to tell without the code.

**Comment by jhilber** [comment]
I was able to create a small test using example code that connects to MS Outlook web client that uses storage state session information and Microsoft's OAuth.  Ran the test using webkit and it is working.  There must be something on our end within our application redirect that causing the issue.  My apologies for taking up your time.
