### ISSUE TITLE
[Question] When rendering component test, how to wait for external stylesheet + fonts to be loaded?

### ISSUE THREAD

**Issue by Hives** [microsoft/playwright#18640]
I'm trying to make a visual regression snapshot test for a component. I need to load an external stylesheet, including some `@font-face` definitions which reference external fonts, which I want to be applied to the component I'm rendering.

I've tried added a link to the stylesheet to my `index.html` file, like this:

```
<html lang="en">
  <head>
    <link rel="stylesheet" href="https://www.example.com/static/my-styles.css" />
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/playwright/index.js"></script>
  </body>
</html>
```

but this is too slow - the fonts don't load by the time the snapshot is taken.

Is there a way I can load the external css, including the external font, before the snapshot gets taken?

**Comment by Hives** [comment]
thanks, but that didn't work for me.

i've worked out that the problem is only happening with headless chromium - if i use headless webkit the fonts render correctly, even without waiting for `document.fonts.ready`, which is good enough for my use case

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by nasir-aviva** [comment]
I'm having the same problem as Hives @yury-s only happening with headless chromium 

```  
await component.evaluate(() => document.fonts.ready);
```

isn't changing anything. I do have a fallback to system fonts. 

```
body, html, input, select {
    font-family: source-sans-pro-vf,fallback-system-fonts,sans-serif;
}
```

I tried this manually in chrome. Loaded my page, disabling cache and forcing 3g speed and my fonts didn't load in chrome. The fallback did. Guessing the same is happening in playwright? It doesn't always happen leading to flakiness

**Comment by vkoves** [comment]
I ran into this too, and I think using `documents.font.check` might help, so you can assert that a given font is loaded. You could then retry until it is. See [docs](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/check), and e.g. in my case, with Roboto:

```ts
/**
 * Wait for fonts to be loaded, specifically Roboto
 */
async function waitForFontsLoaded(page: Page) {
  // Wait for fonts to be done loading
  await page.waitForFunction(() => document.fonts.ready);

  // Log the current status of Roboto font check
  const robotoLoaded = await page.evaluate(() => document.fonts.check('1em Roboto'));
  console.log(`Roboto font check result: ${robotoLoaded}`);

  // Wait specifically for Roboto font to load (up to 2 seconds)
  await page.waitForFunction(
    () => document.fonts.check('1em Roboto'),
    { timeout: 2000 }
  );
}
```

I'm still testing this to see if this is working exactly right
