### ISSUE TITLE
[Feature] Ability use "save Page as" to download a web page with its resources

### ISSUE THREAD

**Issue by dev590t** [microsoft/playwright#18645]
I want to be able to edit a portion of text of a web page and render that with its images.

For instance:
download a web page with its images,use pandoc to convert the html file to latex, edit the latex file, export the latex file to slide format, use the slide in a conference.

This feature could be interest for anybody who like edit a web page and render that with its images.

**Comment by yury-s** [comment]
Playwright already allows to [save](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har-option-update) page traffic to a HAR file and [replay](https://playwright.dev/docs/network#replaying-from-har) from it. You can open that file, edit to your liking and then serve from the har file edited source. You can also listen for [network events](https://playwright.dev/docs/network#network-events) to feed loaded resources to the converter and get the output in the desired format. Would any of those work for you?

**Comment by yury-s** [comment]
Another more straightforward option would be to send [Page.captureSnapshot](https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureSnapshot) command using a custom [CDP session](https://playwright.dev/docs/api/class-cdpsession) and saving the result to file.

**Comment by dev590t** [comment]
the HAR file solution is very technical. 

The Page.captureSnapshot solution is great. I need just download the MHTML file, then extract to html.

Thank you.

**Comment by lzy37ld** [comment]
@dev590t But extracting the mhtml to html will lose other resources? Like Image and css etc.  how to you perfectly restore the original online web?

**Comment by dev590t** [comment]
> @dev590t But extracting the mhtml to html will lose other resources? Like Image and css etc. how to you perfectly restore the original online web?

I have tried to search a library to do this job, but I've not time to test these lib. 

Maybe you could open a new feature request issue, if any open source library solve this problem.

**Comment by gildas-lormeau** [comment]
This might interest you: https://github.com/gildas-lormeau/mhtml-to-html
