### ISSUE TITLE
Setting storageState in the global-setup doesn't work

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#18657]
`global-setup` works as expected. When test open up the URL, it goes back to the login page. I am not sure what I am doing wrong in my code. Can someone please help.

Playwright config file:

```
  globalSetup: require.resolve('./config/global-setup'),
  use: {
    storageState: 'storageState.json'
}
```

global setup:

```
 const page = await browser.newPage();
  console.log('global setup test');
  await page.goto("URL", { waitForSelector: '#okta-signin-username' });
  await page.fill('#okta-signin-username', 'test');
  await page.click('#okta-signin-submit');
  await page.fill('#input', 'Password');
  await page.click('[value=Verify]');
  await page.context().storageState({ path: storageState });
  await browser.close();
```

test file:

```
    await page.goto("URL");
await verifyActions.verifyElementEnabled('#page-header');
```

**Comment by yury-s** [comment]
Standard fixtures currently don't work in global setup scripts hence the configuration options are not applied there. Folding this into https://github.com/microsoft/playwright/issues/17550

**Comment by gauravgandhi1315** [comment]
@yury-s I didn’t get it. Then how does this storageState works? I thought this is how it works

**Comment by gauravgandhi1315** [comment]
@yury-s Can you please help me understand what is wrong with my code? I was following the documentation. If you can send me an example, I can follow that approach as well
