### ISSUE TITLE
[BUG] Blinking browser at page load (Mobile, WebKit, Docker)

### ISSUE THREAD

**Issue by mspina-cit** [microsoft/playwright#18650]
**Context:**
- Playwright Version: 1.27.1 (but it was occurring since 1.19 as I could remember)
- Operating System: MacOS 11.7
- Node.js version: 16.17.1 / npm 8
- Browser: WebKit simulating any iPhone
- Issue happens on Docker only (locally is running fine). Image used: mcr.microsoft.com/playwright:v1.27.1-focal

**Code Snippet**

```javascript
import { test, devices } from '@playwright/test';

test.use({ ...devices['iPhone 11'] })

test('Load DKO homepage', async ({ page }) => {
  await page.goto('https://www.dietcoke.com/', { waitUntil: 'networkidle' });

  await page.locator('img.nav__logo-img').click();
});
```

**Describe the bug**

When running locally it works fine, but on docker, at page load, the page starts blinking and does not load until the end.
It happens on specific sites/pages only. I was not able to identify the cause.
It is the same issue as seen at https://github.com/microsoft/playwright/issues/12153

Evidence:
[dko-load-bug.webm](https://user-images.githubusercontent.com/17860600/200622718-79919ea6-e708-444d-aafb-4c08c7a29244.webm)

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/17152
