### ISSUE TITLE
[Question] PLAYWRIGHT PYTHON POST REQUEST

### ISSUE THREAD

**Issue by LucasLau00** [microsoft/playwright#18665]
r = requests.post('https://httpbin.org/ / post', data ={'key':'value'})

Searching the docs, I cant seem to find any guidance on how I would make a POST request with DATA posted and HEADERS along with it. Is it possible for someone to show me an example on how it could be done?

**Comment by yury-s** [comment]
Please have a look at the parameters in [the doc](https://playwright.dev/python/docs/api/class-apirequestcontext#api-request-context-post). You can pass data and headers like this:

```py
data = {
    "title": "Book Title",
    "body": "John Doe",
}
request.get('https://httpbin.org/post', headers={"Cookie": "foo=bar"}, data=data)

```
