### ISSUE TITLE
[Question] New Selectors

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#18660]
Hey there! Hope you are doing well. Just wondering With the introduction of the new selectors (getByRole, getByLabel, etc) , if you still need to select an element by its class, will page.locator() still exist ? or is there any plan to add something like getByClass or getByCssSelector?

Thank you!

**Comment by yury-s** [comment]
We discussed that but there are no plans for adding getByClass or getByCssSelector as of today. Keep using `page.locator` for the CSS selectors.
