### ISSUE TITLE
[Feature] Faster turnaround with  npx playwright test --debug

### ISSUE THREAD

**Issue by JanSchankin** [microsoft/playwright#18666]
Hi!

When working with ` npx playwright test --debug` to create a new test, I work in a cycle like this:

1. run ` npx playwright test --debug`
2. step to a particular line in the playwright inspector
3. find a new Selector
4. change the selector, or something else in the spec using the IDE
5. press ctrl-c (multiple times, because the terminal is asking me if I wanted to cancel the process)
6. goto 1) 

This is tedious, since I have to do this quite often during  the daily work. 
Is it possible to add an auto reload, that restarts the current test if the spec-file has been changed? A restart-button in the inspector would also be a possibility.

Some background: This might be easier if we use the vscode extension. But we are planning a project that will have a lifetime of decades and we don't want to have a strong dependency to a particular IDE (even though we like vscode), since nobody knows if we will be able to use this particular IDE during the whole lifetime of that project.

Greetings

**Comment by yury-s** [comment]
The new record from here feature (see https://github.com/microsoft/playwright/issues/17771) should address this scenario, folding this request into that issue.

**Comment by JanSchankin** [comment]
Could you elaborate how #17771 solves this issue? If I understand it correctly, then #17771 is solved in vscode by  microsoft/playwright-vscode#266 . I'm looking for a solution _without_ vscode. Something that can be used in conjunction with the command line `npx playwright test --debug`
