### ISSUE TITLE
[BUG] Mocking API endpoint via handling network request throws 401

### ISSUE THREAD

**Issue by stoyanK7** [microsoft/playwright#18667]
**Context:**
- Playwright Version:  "@playwright/test": "^1.27.1",
- NextJS Version: 12.2.5
- Operating System: Ubuntu 22.04
- Node.js version: v18.8.0
- Browser: Chromium Version 105.0.5195.19 (Developer Build) (64-bit)
- Extra: no extra details

`npx envinfo --preset playwright --markdown`
```
## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 1.30 GB / 7.57 GB
 - Container: Yes
## Binaries:
 - Node: 18.8.0 - ~/.nvm/versions/node/v18.8.0/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.18.0 - ~/.nvm/versions/node/v18.8.0/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

```

**Code Snippet**

```typescript
test('Subscription details visible', async ({ page }) => {
  const subscription = {
    id: 'Ao7TAgkxtHk47SL8',
    ...
  };
  await page.route(
    `http://localhost:8081/internal_api/v2/subscriptions/${subscription.id}`,
    (route) => {
      route.fulfill({
        status: 200,
        body: JSON.stringify({
          subscriptions: [subscription],
        }),
      });
    },
  );

  await page.goto(`/cmsnew/subscription-details/${subscription.id}`);
});
```

**Describe the bug**
![Screenshot from 2022-11-09 11-41-30](https://user-images.githubusercontent.com/23459549/200809569-e964d5bd-8439-47f5-920b-b8c26387eb20.png)
![Screenshot from 2022-11-09 11-42-32](https://user-images.githubusercontent.com/23459549/200809400-6077ee73-0d26-43ee-8216-3136596329a8.png)

I have a Flask API running locally on `localhost:8081` that accepts this request. I assume the purpose of this mocking is to skip the call to the API completely and just return the subscriptions, however I am getting 401 Unauthorized. I am looking at the [Handle request examples](https://playwright.dev/docs/network#handle-requests).

The error comes from `authorizedFetcher.ts` which looks like this:
```typescript
const authorizedFetcher = (url: string) =>
  fetch(url, { credentials: 'include' }).then((r) => r.json());

export default authorizedFetcher;
```
We include credentials since we use HTTP cookies. I already tried adding some cookies [like in this Stackoverflow answer](https://stackoverflow.com/a/72263938/9553927) but it did not make a difference. I want to use mocking so I can skip all this authorization.

and `authorizedFetcher` is used like this to make the request via `useSWR`:
```typescript
  const { data: response } = useSWR(
    `http://localhost:8081/internal_api/v2/subscriptions/${id}`,
    authorizedFetcher,
  );
```

**Comment by yury-s** [comment]
Can you add some logging to see if the page.route callback is actually invoked?

> and authorizedFetcher is used like this to make the request via useSWR:

From the method name it looks like the request might be sent from a service worker (and might not be actually intercepted by page.route as it is written). If that's the case you should follow [this guide](https://playwright.dev/docs/service-workers-experimental#how-to-enable) to try the experimental service worker interception support.

**Comment by stoyanK7** [comment]
Added some `console.log()`s and indeed `page.route` is not called
```typescript
  console.log("Before route")
  await page.route(
    `http://localhost:8081/internal_api/v2/subscriptions/${subscription.id}`,
    (route) => {
      console.log("Inside route")
      route.fulfill({
        status: 200,
        body: JSON.stringify({
          subscriptions: [subscription],
        }),
      });
    },
  );
  console.log("After route")
```
```
23:08 $ npx playwright test subscription-details.spec.ts 

Running 2 tests using 2 workers

  ✓  1 [firefox] › e2e/subscription-details.spec.ts:3:1 › Subscription details visible (2s)
  ✓  2 [chromium] › e2e/subscription-details.spec.ts:3:1 › Subscription details visible (629ms)
Before route
After route
Before route
After route

```

**Comment by yury-s** [comment]
Note that `await page.route(` only adds an intercepting callback but does NOT wait for it to be invoked. It will be called later whenever matching request is issues but if you don't see `console.log("Inside route")` until the end of your test it means there haven't been any matching requests by the time the test finished so the problem is likely that the url filter is wrong or you need to explicitly wait until the request is sent and make sure the test keeps running until then.

You can check if it's the former by relaxing the filter condition to: `await page.route('http://localhost:8081/**',` and block the test execution until the request is fulfilled in the end of your test with
```js
await page.waitForResponse(`http://localhost:8081/internal_api/v2/subscriptions/${subscription.id}`);
```

**Comment by stoyanK7** [comment]
`waitForResponse` did the trick. Thanks for the help!
