### ISSUE TITLE
[BUG] When ever i am telling plawrite to open a new browser and create context etc. It is taking a lot of time

### ISSUE THREAD

**Issue by Srinivasan-Akash** [microsoft/playwright#18672]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by yury-s** [comment]
It has something to do with your environment, please make check that antivirus software doesn't interfere with playwright/browsers and your machine has enough free resources. There is not much we can do on our end.

**Comment by Srinivasan-Akash** [comment]
Nope, we can just abort or reject the font family CDN and analytics to make it faster by
        await page.route(/(analytics|fonts)/, (route) => route.abort())
