### ISSUE TITLE
[Feature] add option which allows to store reference screenshots next to test file

### ISSUE THREAD

**Issue by tom2drum** [microsoft/playwright#18670]
Currently, when doing visual comparison of a component with `.toHaveScreenshot()` assertion, the reference screenshot will be placed in common folder which you specified in config. But storing the test file and its screenshots separately could lead to cluttering screenshots directory during refactoring (e.g like file renaming or moving it around), because old screenshot files will not be deleted but new ones will be created. 

So, I think that it could be a good idea to place all reference screenshots for test file next to it and have the folder structure like this:
```
components/
  ExampleComponent/
    ExampleComponent.tsx
    ExampleComponent.spec.tsx
    __screenshots__
      screenshot-1.png
      screenshot-2.png
```

As a benefit we could have a more clear file structure for our projects where we keep all related files in one place and not spreading them across different folders (more like module-based architectural approach).

What do you think? Could we have such kind of option in config?

**Comment by aslushnikov** [comment]
I'll merge this into https://github.com/microsoft/playwright/issues/7792
