### ISSUE TITLE
How to close the browser in case of an error (click element not found.)

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#1867]
Hi Team, 

If an error occurs, click element is not found, the nodejs throws an error, but the browser is not closed and does not release the memory. I can see that in the task manager.
 
In case of an error, how to set the browser to close, or to kill process

thanks a lot

**Comment by mxschmitt** [comment]
Since these are Promise reject exceptions, you can use a [try catch block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) to handle this case. Example here:

```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.webkit.launch();
  const page = await browser.newPage();
  try {
    await page.waitForSelector("#foooo", {
      timeout: 1000
    })
  } catch (err) {
    console.log("Closed the browser")
    await browser.close();
  }
})();
```

Or interactive: https://try.playwright.tech/?s=hxtxm

**Comment by osmenia** [comment]
Hi Max,
 
tnx you for your answer. 

```
const browser = await playwright.webkit.launch();
const page = await browser.newPage();

```
are outside of try und catch in main(). Is there any way to catch  error for playwright.webkit.launch();

**Comment by osmenia** [comment]
> Since these are Promise reject exceptions, you can use a [try catch block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) to handle this case. Example here:
> 
> ```js
> const playwright = require("playwright");
> 
> (async () => {
>   const browser = await playwright.webkit.launch();
>   const page = await browser.newPage();
>   try {
>     await page.waitForSelector("#foooo", {
>       timeout: 1000
>     })
>   } catch (err) {
>     console.log("Closed the browser")
>     await browser.close();
>   }
> })();
> ```
> 
> Or interactive: https://try.playwright.tech/?s=hxtxm

Hi Max,

tnx you for your answer.

```
const browser = await playwright.webkit.launch();
const page = await browser.newPage();
```

are outside of try und catch in main(). Is there any way to catch error for playwright.webkit.launch();

**Comment by mxschmitt** [comment]
> > Since these are Promise reject exceptions, you can use a [try catch block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) to handle this case. Example here:
> > ```js
> > const playwright = require("playwright");
> > 
> > (async () => {
> >   const browser = await playwright.webkit.launch();
> >   const page = await browser.newPage();
> >   try {
> >     await page.waitForSelector("#foooo", {
> >       timeout: 1000
> >     })
> >   } catch (err) {
> >     console.log("Closed the browser")
> >     await browser.close();
> >   }
> > })();
> > ```
> > 
> > 
> > Or interactive: [try.playwright.tech/?s=hxtxm](https://try.playwright.tech/?s=hxtxm)
> 
> Hi Max,
> 
> tnx you for your answer.
> 
> ```
> const browser = await playwright.webkit.launch();
> const page = await browser.newPage();
> ```
> 
> are outside of try und catch in main(). Is there any way to catch error for playwright.webkit.launch();

You somewhere have to have a try catch block around your callee of your waitForSelector call. Due the fact, that I don't know your codebase, thats the most generic answer.

**Comment by osmenia** [comment]
Hi Ma

> > > Since these are Promise reject exceptions, you can use a [try catch block](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch) to handle this case. Example here:
> > > ```js
> > > const playwright = require("playwright");
> > > 
> > > (async () => {
> > >   const browser = await playwright.webkit.launch();
> > >   const page = await browser.newPage();
> > >   try {
> > >     await page.waitForSelector("#foooo", {
> > >       timeout: 1000
> > >     })
> > >   } catch (err) {
> > >     console.log("Closed the browser")
> > >     await browser.close();
> > >   }
> > > })();
> > > ```
> > > 
> > > 
> > > Or interactive: [try.playwright.tech/?s=hxtxm](https://try.playwright.tech/?s=hxtxm)
> > 
> > 
> > Hi Max,
> > tnx you for your answer.
> > ```
> > const browser = await playwright.webkit.launch();
> > const page = await browser.newPage();
> > ```
> > 
> > 
> > are outside of try und catch in main(). Is there any way to catch error for playwright.webkit.launch();
> 
> You somewhere have to have a try catch block around your callee of your waitForSelector call. Due the fact, that I don't know your codebase, thats the most generic answer.

HI Max 

This is my code:
```
function customError(result, screenshot_error) {
.....
}

(async () => {
  // Launch a headless browser instance of chromium, webkit or firefox
  const browser = await chromium.launch({ headless: false, slowMo: 50 });

  // Use the default browser context to create a new tab and navigate to URL
  const page = await browser.newPage();
  try {
    await page.goto("https://cgi-lib.berkeley.edu/ex/fup.html");

    // Get an element handle to the file upload input
    const handle = await page.$('input[type="file"]');

    await handle.setInputFiles("upload.js");

    // Click on the form submit element
    await page
      .click('input[type="submi"]')
      .catch(
        customError(
          "Failed to click, Page did not load completely or the selector for input has changed.",
          await page.screenshot({ encoding: "base64" })
        )
      );

    await page.close();
    await browser.close();
  } catch (customError) {
    console.error("An error occured.");
    console.error(customError);
    await page.close();
    await browser.close();
  }
})();
```

**Comment by nrayburn-tech** [comment]
@osmenia, here is a short example on how to handle a try/catch.

You need to define the customError function inside of the scope of the page, or pass the page as a parameter.  This is how scope works in JavaScript, if you want more information you would be best off asking a question on StackOverflow (or finding one that already exists.).


Here, the catch block handles 'TypeErrors' differently than all other errors.  After the error is handled, it closes the browser.
```
import playwright from 'playwright';
(async () => {
  const browser = await playwright.chromium.launch({ headless: false });
  const page = await browser.newPage();
  try {
    await page.goto('https://wetransfer.com');
    page.setInputFiles('input[type="file"]', 'test.js');
    await page.click('.transfer__footer > button');
  } catch (error) {
    if (error.name === 'TypeError') {
      console.log('TypeError because page.setInputFiles is not a function');
    } else {
      await customError(error);
    }
    browser.close();
  }

  async function customError(error) {
    console.log('Error in test => ', error);
    await page.screenshot({ path: 'error.png' });
  }
})();

```
