### ISSUE TITLE
[BUG] Error on importing types from playwright for module project type

### ISSUE THREAD

**Issue by niyarlatotep** [microsoft/playwright#18671]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Node.js version: 18.9.0
- Browser: All
- Extra: "type": "module"

**Steps**

1.  `npm init playwright@latest` using TypeScript as language 
2. Add to package.json `"type": "module"`
3. Add to example.spec.ts ```import { test, Page } from '@playwright/test';```
4. run `npx playwright test`

**Result**

> import { test, Page } from '@playwright/test';
               ^^^^
SyntaxError: The requested module '@playwright/test' does not provide an export named 'Page'

**Comment by yury-s** [comment]
You have to import types using `import type` rather than `import` in modules, otherwise `import { Page } from '@playwright/test';` will compile as is in .mjs file and will end up trying to import a javascript entity which doesn't exist in .mjs files after compiling `export interface Page {`.

```ts
import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';
```

**Comment by niyarlatotep** [comment]
@yury-s thantk you for the explanation but tsc compiles it without errors and it works fine after compilation, maybe I should  somehow provide settings for playwright tsc compiler?

**Comment by niyarlatotep** [comment]
The problem is that I have a lot of types import in my internal test code (page objects, helpers etc) and it requers a lot of work to rewrite it to importing types. And as I said before it's not a problem when i'm using native tsc.

**Comment by niyarlatotep** [comment]
But I'd prefer it to compile on the fly.
