### ISSUE TITLE
[Question]How can I use "--first-run" with launch_persistent_context()

### ISSUE THREAD

**Issue by liyingjie12345** [microsoft/playwright#18678]
I want to create a new user profile in chrome, how can I do it. I can create new profile when I use "--first-run" + "--user-data-dir", but how can I do it with playwright?

**Comment by yury-s** [comment]
You already described the solution, you can pass a new directory as [userDataDir](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context-option-user-data-dir) option to launchPersistentContext. It will essentially create a new profile. Note though that Playwright recommends using ephemeral contexts for writing tests as doesn't persist state between runs and guarantees that you start with fresh environment every time.

Can you tell us more about your use case and why you need a new profile?

**Comment by liyingjie12345** [comment]
I have many google account with bookmark, now I want to merge all the bookmark. All the bookmark were saved on many google account.

**Comment by yury-s** [comment]
You can only launch browser with one user data dir at a time, this is a Chromium limitation. You can try launching the browser with each of the profiles and export its bookmarks by navigating to chrome://bookmarks and using Playwright to save it e.g. to a file, then use playwright to load the bookmarks and add them to the profile that you want using the same chrome://bookmarks page.
