### ISSUE TITLE
[BUG]: Empty trace preview and timeline

### ISSUE THREAD

**Issue by coryhouse** [microsoft/playwright#18677]
**Context:**
- Playwright Version: 
- Operating System: Mac
- Node.js version: 16.13.1
- Browser: Chromium, but likely all
- Extra: [any specific details about your environment]

**Code Snippet**

[This repo shows trace not working.](https://github.com/coryhouse/playwright-demo).

Run these commands after starting the app: 
```
npx playwright test --trace on
npx playwright show-report
```

Note that the trace window in the middle and the timeline are empty:

<img width="1496" alt="Screenshot 2022-11-09 at 10 20 14 AM" src="https://user-images.githubusercontent.com/1688997/200869431-194a04ae-0d91-4cc9-bc14-5fe23a5848eb.png">

**Describe the bug**

The trace window is empty. It doesn't show the app's content.

**Comment by yury-s** [comment]
Clicking on page.goto reveals this for me:

<img width="813" alt="image" src="https://user-images.githubusercontent.com/9798949/200915837-5b104b35-75a9-464e-9244-a68ffbdf0975.png">

**Comment by coryhouse** [comment]
Ah, you're right. Thanks for clarifying that I needed to click on a specific step. Closing. Thanks!
