### ISSUE TITLE
[Question] How to have playwright wait till an embedded his loaded

### ISSUE THREAD

**Issue by arifshaon** [microsoft/playwright#18679]
Hello everyone,

I have the following the HTML page which loads an embedded object:

`<!DOCTYPE html><html><head></head><body style="height: 100%; width: 100%; overflow: hidden; margin:0px; background-color: rgb(38, 38, 38);"> <embed name="31A58BA265F9023E5A4E99B0919CC62C" style="position:absolute; left: 0; top: 0;" width="100%" height="100%" src="about:blank" type="application/pdf" internalid="31A58BA265F9023E5A4E99B0919CC62C"></body></html>`

How do I get playwright to wait till the object is loaded and then navigate within the frame?

Any help would be greatly appreciated.

Best
Arif

**Comment by yury-s** [comment]
There is no special support for `embed` element in playwright, your best bet is using [its web API](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/embed) to check when it's loaded.
