### ISSUE TITLE
[Question]  Search/query element by id with the Partial name 

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#18682]
we use getByTestId to query like below:

```javascript
return await page.getByTestId('td-CrewMemberVacationAccruals-adjustmentComment-0').click(); 
```
the question is, Instead of querying by the complete name of the id, is there a way to query the element with the partial name of the id?

something like below: like containing partial text
```javascript
return await page.queryByTestId('*adjustmentComment*').click(); 
```

I would like to query just by the name adjustmentComment . Can you please advise how to achieve it?

**Comment by yury-s** [comment]
Currently only exact string is accepted. You can use CSS selector as a workaround:

```js
await page.locator('[data-testid*="adjustmentComment"]').click();
```

I'll leave this issue open to see if there is enough upvotes to justify support of regex parameter.

**Comment by joeflan** [comment]
> I'll leave this issue open to see if there is enough upvotes to justify support of regex parameter.

I'm confused though. In the docs it says the testId argument supports regular expressions

https://playwright.dev/docs/api/class-page#page-get-by-test-id

**Comment by guido-visser** [comment]
Definitely interested :)

**Comment by eatonjl** [comment]
I am interested!

**Comment by ltsuda** [comment]
doesn't `.getBy<something>()` accepts `RegExp`?

https://playwright.dev/docs/api/class-page#page-get-by-test-id

```javascript
await page.getByTestId(new RegExp('.*adjustmentComment.*')).click();

await page.getByTestId(/.*adjustmentComment.*/).click();
```

**Comment by mxschmitt** [comment]
Closing as per https://github.com/microsoft/playwright/issues/18682#issuecomment-1565064181. It supports RegExp since v1.29: https://github.com/microsoft/playwright/pull/19419.
