### ISSUE TITLE
[Feature] Co-locate snapshots for component testing near the test file / component being tested

### ISSUE THREAD

**Issue by pastelsky** [microsoft/playwright#18694]
Currently, the playwright stores all of the component screenshots at the top level in a single folder. For large repositories with hundreds of tests, it ends up becoming a bit of a dumping ground for images.

One of the core tenants of [Component Driven Development](https://www.componentdriven.org/) is co-location of tests, stories and other artifacts with the component (rather on the route or project level). It would be much more idiomatic to store snapshots of components along with the components themselves (or at-least in the same package as the component being tested instead of monorepo root).

Would you consider accepting a config option that will allow snapshots are stored in (say) a `__snapshots__` folder or similar at the component / package level? Perhaps using the re-using the same logic that jest uses for its snapshot tests.

This will make snapshots easy to find and coverage for VR tests easier to define.

**Comment by yury-s** [comment]
We are planning to introduce snapshotPathTemplate in 1.28 release, stay tuned. Merging this issue into https://github.com/microsoft/playwright/issues/7792
