### ISSUE TITLE
[BUG] Application Page is not getting loading , Playwright is blocking page element to load

### ISSUE THREAD

**Issue by aviraljain23** [microsoft/playwright#18693]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Window
- Node.js version: v16.16.0
- Browser: [Chromium,Firefox]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

In  Application, Report Page  is not loading after performing click action for fetching report with playwright .
With Playwright page loading is  getting blocked  and report is not loaded. Looks like Playwright is blocking something.
When tried Manually using local browser report is fetched correctly.

![console report fetch](https://user-images.githubusercontent.com/67741315/201062996-1d07f7eb-5dc7-4554-867d-9d25ac85369f.png)

[27c2ffdc5a06c618d920ee2d0de1f93d11c1798a (1).zip](https://github.com/microsoft/playwright/files/9979672/27c2ffdc5a06c618d920ee2d0de1f93d11c1798a.1.zip)

Attaching Full Trace Report for debugging the issue.
I tried in chromium/firefox/edge locally with both normal and incognito mode, works fine. 
Also tried with  timeout upto  9 * 100000  in playwright , getting same loading issue, and in case of Manual report fetch, report is getting loaded in 2-3 sec.
I think Playwright is blocking something fore sure. let me know if any other details are required! thanks in advance

**Comment by yury-s** [comment]
Can you share a minimal reproducible example which we could run locally to see what's going on? Judging by the number of waitForTimeout in the code of test I'd expect a lot of racy behavior in that test but we cannot tell much without being able to reproduce it. Another thing is you pass 500ms delay to click in `await this.saveAndRun_button.click({delay : 500});` which also hints at some race condition in the app.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by DeeHive** [comment]
for example I am struggling to load this simple website:  'https://www.carrefour.com/en/finance/carrefour-share'

    const { chromium } = require('playwright')


    const browser = await chromium.launch()
    const page = await browser.newPage()
    await page.goto('https://www.carrefour.com/en/finance/carrefour-share', { waitUntil: 'networkidle' })


    const dimensions = await page.evaluate(() => {

        body = document.body,
            html = document.documentElement;
        return {
            height: Math.max(body.scrollHeight, body.offsetHeight,
                html.clientHeight, html.scrollHeight, html.offsetHeight)
        };
    });

    await page.setViewportSize({ width: 1280,height:dimensions.height })

    console.log("dim",dimensions)

    await page.screenshot({ path: '/Users/deehive/Desktop/screenshot/sscreen8.png' })
    await browser.close()
