### ISSUE TITLE
[BUG]queryByText(id).click() is not working in iphone while its working fine in chromium

### ISSUE THREAD

**Issue by msabya** [microsoft/playwright#18706]
**Context:**
- Playwright Version: FROM mcr.microsoft.com/playwright:latest
- Operating System: Mac
- Node.js version: v16.15.1
- Browser: [e.g. All, Chromium, iphone/webkit
- Extra: [any specific details about your environment]

await this.screen.queryByText(id).click();

When run locally this is working fine when i ran locally both in Chromium and webkit.
but failing  for iphone12/webkit  when its ran inside docker container. Below is a snapshhot of the error.
I have an attachment zip file with recording and screenshot. 

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:
await this.screen.queryByText(id).click();

**Describe the bug**

I am working on a reactJs UI where in a drop down has a selection - and click on it by text. which is working fine in chromium
but failing in iPhone/Webkit.
Below is a snippet of the error. Its able to identify the year 2027 but failing to click on it.

error scenario here
proxy.click: Target closed
=========================== logs ===========================
waiting for selector "query-by-text=["2027"]"
  selector resolved to visible <div tabindex="-1" aria-disabled="false" id="react-se…>2027</div>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="react-select__menu-list css-1f41iti">…</div> intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="react-select__menu-list css-1f41iti">…</div> intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="react-select__menu-list css-1f41iti">…</div> intercepts pointer events

**Comment by msabya** [comment]
nov10.zip

**Comment by msabya** [comment]
<img width="1694" alt="image" src="https://user-images.githubusercontent.com/28334629/201193294-99bf3e05-a1b7-4c2d-9d6c-4cb42a33793a.png">

**Comment by yury-s** [comment]
> intercepts pointer events retrying click action, attempt https://github.com/microsoft/playwright/pull/1 waiting for element to be visible, enabled and stable element is visible, enabled and stable scrolling into view if needed done scrolling

There is another element at the position where you try to click which intercepts the click events. Look at the DOM tree of the page which run in the browser with iphone emulation it should be clear which element is that.

In the log from the screenshot the element you try to click was detached from the DOM so it's not [actionable](https://playwright.dev/docs/actionability). The error message is pretty clear about it.

If you think there is a bug in playwright we need a minimal reproducible example which we could run locally. Can you share one?

**Comment by msabya** [comment]
Is there any way we can chat or communicate live?

**Comment by msabya** [comment]
Dont think its appropriate to say that way....
In the attached screen shot above ..its clearly selecting the text that means 2027 is selected. The same code is passed in the chrome browser and even in iphone/webkit in the local. But when i ran the same code inside a docker container its failing.

**Comment by msabya** [comment]
> Dont think its appropriate to say that way.... In the attached screen shot above ..its clearly selecting the text that means 2027 is selected. The same code is passed in the chrome browser and even in iphone/webkit in the local. But when i ran the same code inside a docker container its failing.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro when you have one and link it to this one.
