### ISSUE TITLE
[Question] What's the testMatch priority?

### ISSUE THREAD

**Issue by alexplischke** [microsoft/playwright#18717]
Let's say I have a folder structure like this:
```
/tests
-- /foo.spec.js
-- /bar.spec.js
```

### CLI Argument Only

Now let's apply a filter via the CLI args:
```
❯ npx playwright test foo.spec.js --list
Listing tests:
  foo.spec.js:4:1 › foo
Total: 1 test in 1 file
```

Works as expected 👍 

### Config File Only

This time I'll set a default `testMatch: 'foo.spec.js'` in my `playwright.config.ts`:

```
❯ npx playwright test --list
Listing tests:
  foo.spec.js:4:1 › foo
Total: 1 test in 1 file
```

Works as expected 👍 

### CLI Arg and Config

For the final round, I'll leave the default of `testMatch: 'foo.spec.js'` in my `playwright.config.ts` but also specify a different filter via the CLI:

```
❯ npx playwright test bar.spec.js --list
Listing tests:
Total: 0 tests in 0 files

=================
 no tests found.
=================
```

_My expectation_ would have been that of the CLI arg taking precedence over the defaults in the configuration (cli args/flags > project settings > global settings). However, it seems that if both are specified, nothing works?

The same is true for CLI Arg vs. Project level testMatch.

Bug? Or am I doing something wrong here?

Playwright Version: 1.27.1

**Comment by yury-s** [comment]
`testMatch` from the config applies first and then CLI filter applies to its result. E.g if in the config you have
`testMatch: /(a|b).spec.js/` and in command line pass `(b|c).spec.ts` then only `b.spec.ts` will run.
