### ISSUE TITLE
[Question]: Playwright add <html>.. tags around returned page

### ISSUE THREAD

**Issue by gurmitteotia** [microsoft/playwright#18710]
### Your question

I'm requesting a URL using playwright which returns partial html response something like below

```

<div>
<p>hello</p>
</div>
```
However when I access the response using page.content() I get following response

```
<html><head></head><body>
<div>
<p>hello</p>
</div>
</body></html>
```

I'm using sample code from playwright documentation-
```
def run(playwright):
    chromium = playwright.chromium # or "firefox" or "webkit".
    browser = chromium.launch(headless=True)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://site.com/ajaxcall/partial.html")
    page.evaluate('window.scrollTo(0, document.body.scrollHeight)')
    page.wait_for_load_state("networkidle")
    with open("output.html", "w") as f:
        f.write(page.content())
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)
```
I get similar behaviour with both chromium and Firefox. Not sure which component- playwright or browser is adding these additional  html tags. Any idea on how can I instruct the playwright to not enclose the returned response inside `<html><body> `tags?

**Comment by yury-s** [comment]
Browser automatically completes the html to an html document, playwright has nothing to do with that. You can get original content by looking at the navigation response:

```py
response = page.goto('https://google.com')
print(response.text())

```
