### ISSUE TITLE
Display report in SonarQube

### ISSUE THREAD

**Issue by nestle1936** [microsoft/playwright#18721]
I would like to display my playwright test in SonarQube. It is possible? if Yes How can we do it?
I will appreciate your support. Any Comment ?

**Comment by yury-s** [comment]
Playwright exposes [Reporter API](https://playwright.dev/docs/test-reporters#custom-reporters) which can be used to export test results data to other tools. All builtin reporters use it, there is also a few [third-party examples](https://playwright.dev/docs/test-reporters#third-party-reporter-showcase) that use it and may be worth looking at for inspiration.
