### ISSUE TITLE
[Question] Does page.setDefaultTimeout() set a consolidated timeout for all function utilising it?

### ISSUE THREAD

**Issue by TSViv13** [microsoft/playwright#18724]
Suppose if i set the page's default timeout at 60seconds
eg.
page.setDefaultTimeout(60 * 1000)

if i use any methods that accept timeout options without explicitly mentioning the timeout,
eg.
page.click('locator 1')
page.click('locator 2')
page.click('locator 3')

will the test only wait for a total of 60 seconds for the above 3 click actions OR will it give each click action a timeout of 60 seconds?
ie.
page.click('locator 1') -> took 30 seconds to load
page.click('locator 2') -> took next 30 seconds to load

if page.click('locator 3') takes 10 seconds to load, will the test fail since by the time execution has reached this step as the prior 2 steps itself took 60seconds?

This setting will change the default maximum time for all the methods accepting timeout option.
This is what the documentation states and i was a bit confused at this

**Comment by yury-s** [comment]
You can see a list of all kinds of timeouts that are configurable in Playwright Test on [this page](https://playwright.dev/docs/test-timeouts). If you use Playwright Test runner you shouldn't normally need to call page.setDefaultTimeout directly and can specify it in the config instead.

> Suppose if i set the page's default timeout at 60seconds eg. page.setDefaultTimeout(60 * 1000)
> 
> if i use any methods that accept timeout options without explicitly mentioning the timeout, eg. page.click('locator 1') page.click('locator 2') page.click('locator 3')
> 
> will the test only wait for a total of 60 seconds for the above 3 click actions OR will it give each click action a timeout of 60 seconds?

As the description for [page.setDefaultTimeout](https://playwright.dev/docs/api/class-page#page-set-default-timeout) says it would be equivalent to passing timeout: 60_000 to each of the click calls:
```js
page.click('locator 1', {timeout: 60_000})
page.click('locator 2', {timeout: 60_000})
page.click('locator 3', {timeout: 60_000})
```
so each action will be allowed to hang for 60s. The total test time is controlled independently and can be less than that. E.g. if the [test timeout](https://playwright.dev/docs/api/class-testconfig#test-config-timeout) is set to 30_000 then it will be interrupted after 30s no matter what timeout currently running action has.
