### ISSUE TITLE
[Question] How do i extend the built-in helper keyword?

### ISSUE THREAD

**Issue by xyngfei** [microsoft/playwright#18727]
How do I extend the existing built-in keyword, for example, 
await page.**< my diy keyword >** 
await page.locator("xxx").**< selectRandom(xxx)> **

Take an example from codeceptjs, I can easily extend the built-in helper keyword. 

https://codecept.io/helpers/#development

**Comment by yury-s** [comment]
Playwright doesn't allow extending built-in APIs. You can wrap standard Page/Locator into a [custom POM](https://playwright.dev/docs/test-pom) class and implement your methods there. See also related issue Related issue https://github.com/microsoft/playwright/issues/16785.

Closing this request as we have no plans making Page/Locator APIs extensible.

**Comment by xyngfei** [comment]
@y-f-123, ok. In this case, I will focus on implementing with custom POM method.
