### ISSUE TITLE
[BUG] "Record at cursor" is doing "Record new test"

### ISSUE THREAD

**Issue by arnaudambro** [microsoft/playwright#18737]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 16.15
- Browser: All

##### System:
 - OS: macOS 12.6
 - Memory: 21.66 MB / 16.00 GB
##### Binaries:
 - Node: 16.15.0 - /usr/local/bin/node
 - Yarn: 1.22.18 - ~/.yarn/bin/yarn
 - npm: 7.6.3 - /usr/local/bin/npm
##### Languages:
 - Bash: 3.2.57 - /bin/bash

**Describe the bug**

Form within an existing test, when I do `Command+Shift+P` then click on `Record at cursor`, well it doesn't record at cursor, it just creates a new test like `Record a new test`.

There use to be a command `Record from here` working good, but now we're lacking of something similar.

**Comment by pavelfeldman** [comment]
This feature requires upcoming Playwright v1.28 and is hence hidden from the UI for lower Playwright versions. We still have it in the command palette since we can't make it conditional to the target Playwright version.

**Comment by pavelfeldman** [comment]
Closing as per above, I restored Record a new test in the sidebar for now.
