### ISSUE TITLE
[BUG] Incorrect example in the official documentation

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#18735]
The[ first example test case](https://playwright.dev/docs/writing-tests#the-example-test) in the documentation breaks one of the fundamental principles of test case design where tests should be atomic and have a single responsibility. The test case verifies the title of page, validates an URL path via locators and then navigates to the page to verify its URL. This should be divided into two or three test cases.

In addition there are inconsistencies in the comments.

```
import { test, expect } from '@playwright/test';

test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // create a locator
  const getStarted = page.getByRole('link', { name: 'Get started' });

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro');

  // Click the get started link.
  await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

Suggested example:
```
import { test, expect } from '@playwright/test';

test('User can navigate from Homepage to Intro page using the Get started link', async ({ page }) => {
  // Navigate to homepage
  await page.goto('https://playwright.dev/');

  // Click the "Get started" link
  await page.getByRole('link', { name: 'Get started' }).click()

  // Verify we are on the correct page
  await expect(page).toHaveURL(/.*intro/);
});
```

This example better divides the given-when-then principle and follows good practices of test case design.

**Comment by pavelfeldman** [comment]
It is an example, we choose this style show more capabilities with less boilerplate.

**Comment by irharrier2** [comment]
@pavelfeldman sorry, I didn’t fully understand the reason. Is it my example that has boilerplate or yours?

because creating a locator in a page is the very definition of boilerplate plate. 

Also see:
https://docs.cypress.io/guides/end-to-end-testing/writing-your-first-end-to-end-test

**Comment by pavelfeldman** [comment]
The purpose of this first test is not to introduce users into the best practices or writing tests, but to highlight the main capabilities they'll be using while writing their tests.

**Comment by irharrier2** [comment]
@pavelfeldman introducing highlights of the main capabilities shouldn’t break the basics of test case design. 

Even as someone who is invested in Playwright since the beginning, this worries me if the Playwright team have a clear idea about testing or are hardcore developers and we are going to end up with a mess like Selenium. 

To go further, the test doesn’t highlight anything unique or important to Playwright.
