### ISSUE TITLE
[Feature] Request to add Javascript stack trace addition to the snapshots, Calls, Console and Network 

### ISSUE THREAD

**Issue by raju-a** [microsoft/playwright#18739]
Is it possible to have JS call stack in trace, if we have it will be great for us to understand which one takes long time, Which still in queue.
I'm working on a Web Components based application, Where we are owning one component,
In our End-to-End test case, we clicked on the element but it took couple of seconds to respond(Widget should open) in UI, which is not the expected behaviour,
When we debugged our playwright trace, automation code and application code,
On that particular moment, In our application code, On click we are making an async call which didn't complete, neither it didn't throw any errors(we are catching and printing stack trace).
What we are suspecting is our async call got stuck in call stack queue, In this case if we have Javascript stack trace, We will understand which is blocking our call.

**Comment by yury-s** [comment]
When playwright clicks on an element it may trigger multiple listeners in the page, each of them in turn may schedule its own async operation, so it'd be impossible/impractical to show all of them. Can you elaborate on what stack trace do you want to see in the trace viewer? We currently record and show in the trace the call stack that lead to the action in the test on the Node.js end but AFAIU you're talking about in page javascript code.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
