### ISSUE TITLE
[BUG] HTML Report index.html is created as read-only and can't have playwrightReportBase64 written

### ISSUE THREAD

**Issue by madjam002** [microsoft/playwright#18747]
**Context:**
- Playwright Version: Version 1.25.0
- Operating System: macOS
- Node.js version: 16.18.1
- Browser: N/A
- Extra: Using Nix Package manager

**Describe the bug**

If the Playwright node module is installed into a read-only location, the HTML reporter creates an index.html file that is read-only and then subsequently fails with the error:

```
Error in reporter Error: EACCES: permission denied, open '<redacted>/playwright-report/index.html'
    at Object.openSync (node:fs:590:3)
```

...when trying to append the report base64 data.

I think this is probably down to the file simply being copied here https://github.com/microsoft/playwright/blob/765ac5f0a7a0949ebc48abd5cbde294ea7c93f63/packages/html-reporter/bundle.js#L48 perhaps the file should have the write permission bit explicitly set.

**Comment by pavelfeldman** [comment]
Ah, I did not see your PR! I guess we should do that to all copied files as in mine, but your OR for the bits makes sense! Make sure you update the group bit as well though. Happy to close my PR if you follow up on yours to address the comments.

**Comment by madjam002** [comment]
> Ah, I did not see your PR! I guess we should do that to all copied files as in mine, but your OR for the bits makes sense! Make sure you update the group bit as well though. Happy to close my PR if you follow up on yours to address the comments.

Ah I wasn't sure whether to set the group bit, I thought it would be best to just inherit the existing permissions and make it owner writable as that's enough to amend the report. Is there a reason why the group bit should be set as well?
