### ISSUE TITLE
[Question] How to use serial mode but run all tests

### ISSUE THREAD

**Issue by khtan** [microsoft/playwright#18752]
In the documentation for serial mode, https://playwright.dev/docs/test-retries#serial-mode, it says that if one
of the tests fails, all subsequent tests are skipped.

I have a situation where I have a number of tests that I wish to run serially and I want them all to run, ie not
stop on first failure. In this sense, the dependency is not due to functional dependency but policy dependency.

Another way to view this issue generically is that there are 2 ways to react to failure - StopOnFirstFailure or 
ContinueAfterFailure. There are scenarios that would be ideal for each of these two settings.

Is there a way to override this default behavior?

Thanks,

**Comment by yury-s** [comment]
There is such option today. Note though, that in [default mode](https://playwright.dev/docs/test-parallel) all tests from the same file will run sequentially on a single worker and will continue running even if some of them fail.

There is an open request for more sophisticated policy where at most one test of a set should run at any given moment https://github.com/microsoft/playwright/issues/17495. Merging this one into it.
