### ISSUE TITLE
[BUG] Meta+X not working on macOS for Chromium

### ISSUE THREAD

**Issue by luin** [microsoft/playwright#18755]
Meta+X doesn't work whereas Meta+C/Meta+A work as expected. Not sure whether it's due to https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/macEditingCommands.ts doesn't include cut.

**Context:**
Playwright Version: 1.27.1
Operating System: Mac
Node.js version: 16
Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });
  const context = await browser.newContext();
  await context.grantPermissions(['clipboard-read']);
  const page = await context.newPage();
  await page.goto('https://output.jsbin.com/zifated');
  await page.locator('input').click();
  await page.keyboard.type(String(Date.now()));
  await page.keyboard.press('Meta+KeyA');
  await page.keyboard.press(`Meta+KeyX`); // works if changing KeyX to KeyC.

  console.log(
    await page.evaluate(async () => {
      return (await (await navigator.clipboard.read())[0].getType('text/plain')).text();
    }),
  );

  await browser.close();
})();
```

**Describe the bug**

With `Meta+KeyX`, the Hello*** text is not written into the clipboard, whereas `Meta+KeyC` works. Make sure to clear your clipboard before running the test.

**Comment by LiutskoOlga** [comment]
Hello,
I have a problem with next shortcut that added on our site -> 
'Control+Z'/'Meta+Z' - for undo and 'Control+Y'/'Control+Shift+Z' for redo.
It is working in debug mode, but it is not working on headless mode
Thank you for helping to resolve

**Comment by luin** [comment]
The original Meta+X issue was fixed with https://github.com/microsoft/playwright/pull/18756 so I'm okay to close it. Not sure we need to keep this open for tracking the issue mentioned by @LiutskoOlga?

**Comment by skogsmaskin** [comment]
I want to mention that `Meta+KeyV` has also stopped working when triggering pasting into a contentEditable div on MacOS in Chromium. Works fine on Linux, and used to work on MacOS (I think before v. `chromium-1055`).

**Comment by StanislavIvanovQA** [comment]
I have the following function:
`export const pasteFromClipboard = async (page: Page) => {
  await test.step('Pasting value from clipboard', async () => {
    await page.keyboard.press(`${process.env.CI ? 'Control' : 'Meta'}+V`);
  });
};`
and it's working in headless only in localhost, but not working for custom domain. in headed mode - it's ok.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
