### ISSUE TITLE
[BUG] headless false rendering blank page

### ISSUE THREAD

**Issue by sylhero** [microsoft/playwright#18757]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [MAC M1]
- Node.js version: [v16.16.0]
- Jest version: [28.1.3]
- Browser: [All]
- Extra: [NO]

**Code Snippet**
jest.e2e.config.js
```javascript
module.exports = {
    preset: "jest-playwright-preset"
}
```
playwright.config.js
```javascript
module.exports = {
    launchOptions: {
      headless: false
    },
    contextOptions: {
      ignoreHTTPSErrors: true,
      viewport: {
        width: 1920,
        height: 1080
      }
    },
    browsers: ["firefox"],
    devices: []
  }
```
Test case

```javascript
const { firefox } = require('playwright');
let browser;
let page;
beforeAll(async () => {
  browser = await firefox.launch();
});
afterAll(async () => {
  await browser.close();
});
beforeEach(async () => {
  page = await browser.newPage();
});
afterEach(async () => {
  await page.close();
});
it('should work', async () => {
  await page.goto('https://www.google.com');
  const title = await page.title();
  console.log(title);
  expect(title).toBe('Google');
  await page.getByRole('combobox').fill('Peter');
  await page.screenshot({ path: 'screenshot.png' });
  await page.keyboard.press('Enter');
  await page.screenshot({ path: 'screenshot2.png' });
});
```

**Describe the bug**
when the test opens the browser I can take screenshots with actual page content but the browser itself doesn't render anything. This happens to all browsers 
<img width="1235" alt="Screenshot 2022-11-12 at 10 38 04 AM" src="https://user-images.githubusercontent.com/4540917/201482139-337103e2-2e3a-4b10-99c1-5017590ac16e.png">

Add any other details about the problem here.
Test case itself is validating the right content but nothing is actually rendering when headless is false

**Comment by pavelfeldman** [comment]
You are probably misusing the jest-playwright-preset. We recommend using @playwright/test to stay on the well-lit path and not miss on the test runner features.

**Comment by selvakumarram** [comment]
I don't see a solution given for this issue. can someone share the solution for this issue?
