### ISSUE TITLE
I'm wanting to click on more than one element at the same time, I have to open all the answers or the comments

### ISSUE THREAD

**Issue by joaomorais07** [microsoft/playwright#18767]
```
try:
        pagina.locator("text=ver respostas").dispatch_event('click', timeout=5000)
except:
        pass
```

this returns me the following error:

playwright._impl._api_types.Error: Error: strict mode violation: "text=ver respostas" resolved to 3 elements:
    1) <span class="_a9yi">Ver respostas (1)</span> aka playwright.$("button:has-text("Ver respostas (1)") >> nth=0")
    2) <span class="_a9yi">Ver respostas (2)</span> aka playwright.$("button:has-text("Ver respostas (2)")")
    3) <span class="_a9yi">Ver respostas (1)</span> aka playwright.$("button:has-text("Ver respostas (1)") >> nth=1")

**Comment by pavelfeldman** [comment]
Playwright can only click one button at a time, and it does not know which one to click - three buttons match the provided selector. See https://playwright.dev/python/docs/next/locators#get-by-nth-item.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
