### ISSUE TITLE
[Question] Why is my Playwright codegen's Target is not have 'Playwright test or Typescript option in the combo field?

### ISSUE THREAD

**Issue by CKPallavi** [microsoft/playwright#18763]

**Comment by pavelfeldman** [comment]
What does it have? Could you share a screenshot?

**Comment by CKPallavi** [comment]
My playwright vesrion is v1.27.1.
![image](https://user-images.githubusercontent.com/118112890/201591282-63e83aeb-06f6-4928-ab54-f659108ffe87.png)

**Comment by pavelfeldman** [comment]
Test runner is the Playwright Test.

**Comment by Archie-f** [comment]
My playwright version is 1.30.0. Is it normal not to have the steps as Commented out?
The version in the video I watch is recorded like:
<img width="393" alt="image" src="https://user-images.githubusercontent.com/90334115/215345442-35c89a88-0a29-4b11-97b6-05b6dc3252b1.png">
My test is recorded like:
<img width="415" alt="image" src="https://user-images.githubusercontent.com/90334115/215345474-fd411a1a-8ef5-4fd4-9b5a-7f5347aa9835.png">
