### ISSUE TITLE
[BUG] channel msedge with headed mode slow teardown

### ISSUE THREAD

**Issue by vethman** [microsoft/playwright#18766]
When I use msedge browser with channel=msedge in headed mode (headless=false), then a failing test has a long shutdown (30sec) after a failure. WaitForCompletion(int timeout) has a timeout value of -1. When I do not use the channel (Default Chrome) or do headless with edge, then there is no problem.

In my demo github repo you can find the stacktrace.

- Playwright Version: Microsoft.Playwright.NUnit" Version="1.27.2"
- Operating System: Windows 11
- Browser: Edge

Here to link to my little demo project to show the problem:
https://github.com/vethman/Playwright.Vethman

**Comment by pavelfeldman** [comment]
Most likely, your Edge browser is picking up the Edge enterprise policy enforced in your organization. This enterprise policy is affecting the browser behavior in many ways, including tampering with the browser exit routine. Headless mode does not respect the enterprise policy, hence is immune to its side-effects. You should not test against the browsers w/ enterprise policies anyways, so it might be best to run your tests using headless mode only.

**Comment by vethman** [comment]
Many thanks for the explanation. Will continue using the chrome browser.
