### ISSUE TITLE
[Question] Playwright hook / callback / try-catch to handle the overall test timeout

### ISSUE THREAD

**Issue by sanjoyghosh** [microsoft/playwright#18769]
When the timeout specified as below in playwright.config.ts expires, Playwright simply blows away the browser. How can I catch this timeout expiry in my Playwright test script, and handle it gracefully? I would like to log the timeout and exit the test gracefully.
```
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  timeout: 60000, // Timeout is shared between all tests.
```
I would like a hook / callback that can log the timeout and close the browser gracefully.

Thanks, 
Sanjoy

**Comment by pavelfeldman** [comment]
You can always try to race the test internals with your own timeout and perform graceful actions. But you can't close the browser - subsequent tests will fail and you can't keep using it - timeout of the operation is unrecoverable operation. Not sure what you mean by 'log the timeout' - you might find better luck with the use of a custom reporter that logs the timeout.

**Comment by sanjoyghosh** [comment]
Thanks a lot Pavel.  When the overall test times out will the `Reporter.onEnd(result)` function be called?  That is exactly what I need.

```
  onEnd(result) {
    console.log(`Finished the run: ${result.status}`);
  }
```

**Comment by pavelfeldman** [comment]
Don you mean overall test run? Or a single test? In either case, check this out: https://playwright.dev/docs/api/class-reporter.

**Comment by sanjoyghosh** [comment]
Thanks a ton Pavel.  That works perfectly.
