### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by srisha2953** [microsoft/playwright#18774]
I am getting this error while installing playwright in Ubuntu 22 

-----------------------------------------------------------------------------------
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
✔ Do you want to use TypeScript or JavaScript? · JavaScript
✔ Where to put your end-to-end tests? · tests
✔ Add a GitHub Actions workflow? (y/N) · false
✔ Install Playwright browsers (can be done manually via 'npx playwright install')? (Y/n) · true
✔ Install Playwright operating system dependencies (requires sudo / root - can be done manually via 'sudo npx playwright install-deps')? (y/N) · false
Initializing NPM project (npm init -y)…
Wrote to /home/srisha/Repos/playwright_Automation/package.json:

{
  "name": "playwright_automation",
  "version": "1.0.0",
  "description": "# Introduction",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/srisha2953/playwright_Automation.git"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/srisha2953/playwright_Automation/issues"
  },
  "homepage": "https://github.com/srisha2953/playwright_Automation#readme"
}

Installing Playwright Test (npm install --save-dev @playwright/test)…
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@playwright/test@1.27.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'playwright-core@1.27.1',
npm WARN EBADENGINE   required: { node: '>=14' },
npm WARN EBADENGINE   current: { node: 'v12.22.9', npm: '8.5.1' }
npm WARN EBADENGINE }

added 3 packages, and audited 4 packages in 4s

found 0 vulnerabilities
Downloading browsers (npx playwright install)…
You are running Node.js 12.22.9.
Playwright requires Node.js 14 or higher. 
Please update your version of Node.js.
Error: Command failed: npx playwright install
    at checkExecSyncError (child_process.js:635:11)
    at execSync (child_process.js:671:15)
    at executeCommands (/home/srisha/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/home/srisha/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4660:5)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/srisha/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4926:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 11563,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /home/srisha/Repos/playwright_Automation
npm ERR! command failed
npm ERR! command sh -c create-playwright

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/srisha/.npm/_logs/2022-11-14T06_27_14_499Z-debug-0.log

**Comment by pavelfeldman** [comment]
If you read those error messages, you'll see

> Playwright requires Node.js 14 or higher.
> Please update your version of Node.js.

**Comment by srisha2953** [comment]
I am using node 18

**Comment by srisha2953** [comment]
![image](https://user-images.githubusercontent.com/62602829/201607237-963af98e-7e37-4feb-8410-03ec05317536.png)

**Comment by srisha2953** [comment]
![image](https://user-images.githubusercontent.com/62602829/201607515-dd82ddb6-5aea-46ec-afeb-75a085d015e8.png)

**Comment by srisha2953** [comment]
![image](https://user-images.githubusercontent.com/62602829/201607607-5cbc52d7-a59c-42eb-84ce-02864b202224.png)

**Comment by srisha2953** [comment]
Found the issue, and solve it thanks for the Help
