### ISSUE TITLE
page.query_selector_all("#author-text > span")

### ISSUE THREAD

**Issue by leungfukwong** [microsoft/playwright#18778]
I have tried different ways of web scraping youtube comments. I am quite sure that the selector used is correct as attached verified.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/39502448/201657905-10b39654-b55d-4482-b671-a2c8d4e66a63.png">
The statement  -- page.query_selector_all("#author-text > span") -- was used but could not get any result.
Would appreciate if someone can help!
Thanks a million

**Comment by h4nz4** [comment]
use page.locator("#author-text > span")

Why are you using it for scraping? Are you writing a test or?

**Comment by h4nz4** [comment]
use `page.locator("#author-text > span").first()` to get the element. then you can do for example:
 ```ts
  let spanElement = page.locator("#author-text > span").first();
  let elementContent = await spanElement.innerHTML();
  await expect(elementContent).toBe("<p>Hello</p>");
```
