### ISSUE TITLE
[BUG] Inconsistent behavior running headed mode in Docker image when running on local machine vs. Gitlab-CI pipelines - one works, other doesn't

### ISSUE THREAD

**Issue by h4nz4** [microsoft/playwright#18777]
Greetings!

We are working on using Playwright with Cucumber. In the BeforeAll hook we are starting browsers in headed mode. In the CI pipelines on GitLab, the command we use is `xvfb-run npm run test`, which works fine in headed mode. Running that locally on a Docker container, we found that it crashed with the following error: 

![image](https://user-images.githubusercontent.com/18464660/201654741-354a536e-fcf5-4229-8588-e1898218a86f.png)

The reason why we run it in headed mode is to ensure consistency of running e2e tests both locally and in the CI pipelines. We want to test it locally on a Docker environment to ensure 100% consistency between the tests running locally and in the CI pipelines, additionally to benefit from containerized local environment. 

The exact command we tested locally (Windows machine with Docker running on WSL2 and Linux machine with native Docker):

`docker run --rm -ti --shm-size=1G --ipc=host -v $(pwd -P):/cucumber mcr.microsoft.com/playwright:v1.27.1-focal /bin/bash`

**What we cannot do, and ask for you for help, is explain how on the Earth can it work on the same Docker image v1.27.1 on the pipelines, but not on local machines? This is worrysome because it implies inconsistencies of the behavior in running in different environments.**

Here's a screenshot from GitLab pipeline job, where running xvfb-run with Playwright works fine:

![image](https://user-images.githubusercontent.com/18464660/201653721-c1a8e3c2-75b7-4dc6-aa70-981eec7b89bb.png)

## What is even more mindboggling, is that in the local Docker, installing npm version 9.1.1 fixes the problem.... this is almost certainly a bug in Playwright implementation... 

![image](https://user-images.githubusercontent.com/18464660/201655231-4d419f6e-13cd-4ba2-b788-1a4a7bd433ee.png)

We have tried troubleshooting this issue on our end, checked thoroughly for things that we might have done wrong, with no hope for a solution. On this basis, we decided to open this Issue to involve the Playwright community and help prevent the same types of issue for other people.

**Comment by h4nz4** [comment]
> You should always run headless, on both, unless you are using headed browsers features not available in the headless mode.

Thank you for your reply. Regarding what we should do or shouldn't do, I have to respectfully disagree with your suggestion. We are running in headed mode for a reason. It works in the CI with no problem. On local Docker execution it behaves like seen above. Please don't focus on our reasons,  the reasons are based on good e2e testing principles - having a controlled testing environment, which the Docker image should provide. 

> This is a great question, but I don't think this is a question to the Playwright team - it docker that guarantees consistent environments, not Playwright. So I would compare all the docker params and look into why environments can differ on the docker side.

Actually, we believe this is indeed a relevant question for Playwright's development community. Let me elaborate: there are no Docker params used here. We checked the environments thoroughly, two different people on two different machines. Here are the details:

Exact environment (Gitlab CI, shared runner) - keep in mind, on the CI it works fine!

```yaml
test.dev.e2e:
  stage: test.dev
  needs: 
    - job: deploy.dev 
      optional: true
    
  image: mcr.microsoft.com/playwright:v1.27.1-focal
  cache:
    paths:
      - e2e-tests/node_modules/
  artifacts:
    when: always
    paths:
      - e2e-tests/reports/report.html
      - e2e-tests/screenshots/*
      - e2e-tests/traces/*
      - e2e-tests/package-lock.json
    # reports:
    #   junit: e2e-tests/report/junit/report.xml  
  script:
    - xvfb-run npm test
  before_script:
    - npm i   
```

Running the tests locally, in the Docker environment, spinning up the Docker image with this command:

`docker run --rm -ti --shm-size=1G --ipc=host -v $(pwd -P):/cucumber mcr.microsoft.com/playwright:v1.27.1-focal /bin/bash`

And running `npm i` and then `xvfb-run npm test` (exactly the same way as in the CI pipeline), we get the error shown above in the OP. 

We are spinning up the browser instance like this in the implementation:

```ts
let browserOptions = {
      slowMo: 0,
      headless: false,
      args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'],
      firefoxUserPrefs: {
        'media.navigator.streams.fake': true,
        'media.navigator.permission.disabled': true,
      },
    };
let browser = await chromium.launch(browserOptions);
```
Everything works fine locally without Docker, but with Docker it errors, but not on the CI environment. This is especially alarming. 

We troubleshooted the environment thoroughly and did an analysis of the situation. The reason why we believe this is a Playwright issue and not a Docker issue:

1. If you carefully read the OP, you see that updating npm to 9.1.1. inside the local Docker container fixes the problem in the Docker container. This is almost certainly a Node.js related issue, not a Docker issue. Especially since we reproduced this issue on two different machines with different OS, with different (up to date) Docker versions.

2. Since we see there is a lot of Docker logic in the implementation ([e.g. here](https://github.com/microsoft/playwright/tree/8538f61a72a53c672231cbddc3cbdd3ab248535a/packages/playwright-core/src/containers )), it certainly points general suspicion that this indeed is a technical issue with Playwright. 

We really like the library, all the work done with it, and would really appreciate if you could at least please investigate this topic, if not opt for a solution. I am sure somebody might stumble upon the same problem eventually.

**Comment by pavelfeldman** [comment]
We'll get to the bottom of this, but could you help me reducing the number of moving parts here? If you could share a container spec that runs in one runtime and does not run in another runtime, it would be a good start. Your GitHub CI is not a raw container, so we seem to be comparing apples to oranges here. Let's try to reduce the scope to the same container, but two exact runtimes.

> If you carefully read the OP, you see that updating npm to 9.1.1. inside the local Docker container fixes the problem in the Docker container. This is almost certainly a Node.js related issue, not a Docker issue. Especially since we reproduced this issue on two different machines with different OS, with different (up to date) Docker versions.

I don't see Playwright in this picture, which is suspicious
 
> Since we see there is a lot of Docker logic in the implementation ([e.g. here](https://github.com/microsoft/playwright/tree/8538f61a72a53c672231cbddc3cbdd3ab248535a/packages/playwright-core/src/containers)), it certainly points general suspicion that this indeed is a technical issue with Playwright.

This code is used in a new feature that has not even been released, so you should not point the general suspicious at it. The way Playwright interoperates with containers is that you just run it in those containers, there is no communication with the runtime or anything, Playwright simply runs inside a container as it would run inside any other Linux system.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
