### ISSUE TITLE
errno: -4047, [BUG] ?

### ISSUE THREAD

**Issue by mkdobtc** [microsoft/playwright#18787]
### Olá como vão espero que bem, desde já gostaria de agradecer a equipe da `Playwright Nota 10 !`
Ainda estou engatinhando na programação se alguma coisa não condisser como deveria ser mil perdões

**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows 10 Pro | 22H2
- Python version: 3.10.5
- Browser: Firefox
- Extra:
- Virtualenv
  Python:         3.10.5
  Implementation: CPython
  Path:           C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-GavygvRQ-py3.10
  Executable:     C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-GavygvRQ-py3.10\Scripts\python.exe
  Valid:          True
  
  System
  Platform:   win32
  OS:         nt
  Python:     3.10.5
  Path:       C:\Users\mkdob\.pyenv\pyenv-win\versions\3.10.5
  Executable: C:\Users\mkdob\.pyenv\pyenv-win\versions\3.10.5\python.exe

### setup.py
```
#!/usr/bin/python
import asyncio
import gc
from playwright.async_api import async_playwright
from app.src.addmefast import AddMeFasT, azul, vermelho
'''
async def main() -> None:
    bot = AddMeFasT()
    while True:
        try:
            async with async_playwright() as playwright:
                await bot.open_browser(
                    browser_name='firefox', playwright=playwright, headless=False
                )
                await bot.newpage()
                await bot.backgroudclose()
                await bot.loginpinterest()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.logindiscord()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.logintwitter()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.logininsta()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.loginreddit()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.logingoogle()

                await bot.newpage()
                await bot.backgroudclose()
                await bot.site(url=r'https://addmefast.com/welcome')
                await bot.check_all_title()
        except Exception as err:
            azul(f'Exception: {err}')
        finally:
            gc.collect()
            await asyncio.sleep(5)
            await main()


if __name__ == '__main__':
    asyncio.run(main())

```

**Describe the bug**
Add any other details about the problem here.
### o evento abaixo parece acontecer de maneira aleatoria e imparcial sobre o programa que normalmente flui bem passa por todas as funções e classes de maneira que se repete por varias horas.
Não tenho ideia do que possar ser não sei quase nada de java **como disse la em cima estou começando**

(app-py3.10) PS C:\Users\mkdob\Desktop\Programas em execução\BoT> node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: EPIPE: broken pipe, write
    at Socket._write (node:internal/net:55:25)
    at writeOrBuffer (node:internal/streams/writable:391:12)
    at _write (node:internal/streams/writable:332:10)
    at Socket.Writable.write (node:internal/streams/writable:336:10)
    at PipeTransport.send (C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-GavygvRQ-py3.
10\Lib\site-packages\playwright\driver\package\lib\protocol\transport.js:54:21)
    at DispatcherConnection.dispatcherConnection.onmessage (C:\Users\mkdob\AppData\Local\pypoetry\Ca
che\virtualenvs\app-GavygvRQ-py3.10\Lib\site-packages\playwright\driver\package\lib\cli\driver.js:65
:57)
    at DispatcherConnection._sendMessageToClient (C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtua
lenvs\app-GavygvRQ-py3.10\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatc
her.js:252:10)
    at DispatcherConnection.sendCreate (C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-
GavygvRQ-py3.10\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:214
:10)
    at new Dispatcher (C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-GavygvRQ-py3.10\L
ib\site-packages\playwright\driver\package\lib\server\dispatchers\dispatcher.js:90:40)
    at new ConsoleMessageDispatcher (C:\Users\mkdob\AppData\Local\pypoetry\Cache\virtualenvs\app-Gav
ygvRQ-py3.10\Lib\site-packages\playwright\driver\package\lib\server\dispatchers\consoleMessageDispat
cher.js:29:5)
Emitted 'error' event on Socket instance at:
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4047,
  syscall: 'write',
  code: 'EPIPE'
}

**Comment by pavelfeldman** [comment]
Please file a bug that we can reproduce, it should contain the exact steps we should perform, your expectations and the actual behavior! I'll close this one to clear the history, please file a new one! It should also have title, not "?"!

**Comment by mkdobtc** [comment]
acho que você é cego o título se encontra aqui `errno: -4047, [BUG]?`, não acha? se não é do seu agrado ai o problema não é meu não ?

**Comment by mkdobtc** [comment]
> Por favor, registre um bug que possamos reproduzir, ele deve conter as etapas exatas que devemos executar, suas expectativas e o comportamento real! Vou fechar este para limpar o histórico, por favor, arquive um novo! Também deveria ter título, não "?"!

acho que você é cego o título se encontra aqui , não acha? se não é do seu agrado ai o problema não é meu não ?errno: -4047, [BUG]?
