### ISSUE TITLE
[BUG] soft assertion terminates test

### ISSUE THREAD

**Issue by mk654321** [microsoft/playwright#18793]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Linux
- Node.js version: v14.17.0
- Browser: Chromium, Firefox

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// @ts-check
const { test, expect } = require('@playwright/test');


test.describe.configure({ mode: 'serial' });


/** @type {import('@playwright/test').Page} */
let page; 



function randomUrl() {
  const urls = ['https://www.bing.com/images','https://www.bing.com','https://www.bing.com/maps','https://www.bing.com/videos','https://www.bing.com/news','https://www.bing.com/shop','https://www.bing.com/travel'];
  return urls[Math.floor(Math.random() * urls.length )];
  }

test.beforeAll(async ({ browser }) => {
  
  
  page = await browser.newPage();
  await page.goto(randomUrl());

});

test.afterAll(async () => {
  await page.close();
});

test('001 Screenshot', async () => {
  await page.goto(randomUrl());
  await expect.soft(page).toHaveScreenshot();

});

test('002 Screenshot', async () => {
  await page.goto(randomUrl());
  await expect.soft(page).toHaveScreenshot();
});

test('003 Screenshot', async () => {
  await page.goto(randomUrl());
  await expect.soft(page).toHaveScreenshot();
});

```

**Describe the bug**

[According to documentation on Soft Assertions](https://playwright.dev/docs/test-assertions#soft-assertions) "failed soft assertions do not terminate test execution, but mark the test as failed."

However when trying to run above script, only the first test is not terminated, test 2 and test 3 are not executed, the test run is terminated.

** to reproduce ** 
1. Save above code snippet in ```tests``` folder as ```example_screenshot_softAssertion.spec.js```
2. Execute test: ```npx playwright test tests/example_screenshot_softAssertion.spec.js```

**Comment by pavelfeldman** [comment]
That's as expected, `expect.soft` allows the test ('001 Screnshot' in your case) to run to the end and then it fails it. Since you are running in the serial mode, no subsequent tests are running and retry sequence starts. I don't think expect.soft makes much sense in the scope of the serial tests, you would need to `expect(page).toHaveScreenshot().catch(e => errors.push(e))` to handle this pattern.

**Comment by mk654321** [comment]
Thanks for explanations.
What I wanted to do is run 3 serial tests, where each test takes an action and screenshot. I wanted to use hard assertions on actions and soft assertions  on screenshots, so even if screenshots do not match I could still carry on. Your suggestion gives me what I need, I can populate ```errors``` and then fail the test in ```afterAll``` or since it's serial anyway, add a last test that would pass/fail based on ```errors```.
Thank you @pavelfeldman for pointing me the right direction. I much appreciate your extra effort :clap:

**Comment by pavelfeldman** [comment]
Just out of curiosity, did you consider merging it into a single test and using test.step for stages?

**Comment by mk654321** [comment]
Thank you for you hint, yes this works better using `test.step`.
