### ISSUE TITLE
[Question] Not able to capture the post response

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#18797]
Related to 18620 , Please advise what changes i should make on the snippet below to get the response of the first URI?

``` javascript
const [auctionResponse] = await Promise.all([
            page.waitForResponse(res =>
                res.status() == 200
                &&
                res.url() == "https://service.aws.spa.com/golden/vacation/auctions" ---> not working, seeing timeout error although the URI was loaded. not storing the response.
               res.url().includes('/vacation/auctions')  --> this one return the response of the second api ,where as i wanted the response from the first api call.
                res.url().endsWith('/vacation/auctions'). --> not working, seeing timeout error although the URI was loaded not storing the response.
            ),

            actor.attemptsTo(Click.on('Id', 'wizard-next-button--cbna-wizard'))
        ]);
       const auctionResult = JSON.stringify(await auctionResponse.json())
        console.log(" result " + auctionResult)
        const accrualUrl = JSON.parse(auctionResult)._links.self.href;
        console.log( "url" + accrualUrl )
```

after clicking wizard-next-button--cbna-wizard button,
This URL both the urls ,first url--> 1. https://service.aws.spa.com/golden/vacation/auctions (POST call)
2 second url --> https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters (GET Call)

when i run res.url().includes('/vacation/auctions') , it returns the response from the second call which is https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters (GET Call)
But i expected to read the response from the POST call , the first url --> https://service.aws.spa.com/golden/vacation/auctions (POST call)

hence i tried with res.url().endsWith('/vacation/auctions'), but when i use endsWith, i see the error and it doesnt return the api response.
Test timeout of 30000ms exceeded.

page.waitForResponse: Page closed

  56 |
  57 |         const [auctionResponse] = await Promise.all([
> 58 |             page.waitForResponse(res =>
     |                  ^
  59 |                 res.status() == 200
  60 |                 &&
  61 |                 // res.url() == "https://service.aws.spa.com/golden/vacation/auctions"

first api call:
Request URL: https://service.aws.spa.com/golden/vacation/auctions
second api call:
Request URL: https://service.aws.spa.com/golden/vacation/auctions/8e908cdc-5288-467b-a10e-94275b316645/parameters

**Comment by pavelfeldman** [comment]
If I had to guess, I would think that your url actuall ends with '/', that's why your endsWith does not work. But why guessing if you can just console.log that URL and put down the right predicate.

**Comment by InduKrish** [comment]
the URL doesnt have '/' at the end,  this is how it looks- https://service.aws.spa.com/golden/vacation/auctions

all these three ways didnt work, including endsWith. Can you please advise?

```javascript
 res.url() == "https://service.aws.spa.com/golden/vacation/auctions" ---> not working, seeing timeout error although the URI was loaded. not storing the response.
               res.url().includes('/vacation/auctions')  --> this one return the response of the second api ,where as i wanted the response from the first api call.
                res.url().endsWith('/vacation/auctions'). --> not working, seeing timeout error although the URI was loaded not storing the response.
```

**Comment by pavelfeldman** [comment]
Could you console.log these urls from the route handler and share the exact output?

**Comment by InduKrish** [comment]
<img width="1766" alt="Screen Shot 2022-11-18 at 11 46 23 AM" src="https://user-images.githubusercontent.com/113629123/202769107-b8589bc0-ecec-41d2-9a80-29a1bde6f9c7.png">

here is the screenshot when i try - res.url().includes('/vacation/auctions')

**Comment by pavelfeldman** [comment]
Could you console.log request url in the waitForResponse and share the exact output?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
