### ISSUE TITLE
Playwright with JAVA under VPN

### ISSUE THREAD

**Issue by ronibary** [microsoft/playwright#18795]
### Your question

Hi All,

I'm working under VPN connection and when I try simple page navigation to site that is under VPN connection from playwright JAVA code I geting timeout and the page is not opening the site .

If I do it manually on the Chrome browser when the VPN connection active the site is opening. all is good

I wonder if the reason is that PW is launches the brwser in Incognito mode , but I also tried to use non Incognito mode
but still under VPN the site is not open or navigate  ? strange
do you have any idea how to solve this?

see this is my simple code that is running under VPN

            Playwright playwright = Playwright.create();
 
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            int width = (int)screenSize.getWidth();
            int height = (int)screenSize.getHeight();

            Path userDataDir = Paths.get(System.getenv("LOCALAPPDATA"),"\\Google\\Chrome\\User Data", "");

            BrowserType.LaunchPersistentContextOptions browserOptions = new BrowserType.LaunchPersistentContextOptions();
            browserOptions.setHeadless(false);
            browserOptions.setChannel("chrome");
            browserOptions.setTimeout(120000);
            browserOptions.setViewportSize(width,height);

            BrowserContext browserContext = playwright.chromium().
                    launchPersistentContext(userDataDir,browserOptions);

            Page page = browserContext.newPage();
            page.setDefaultTimeout(120000);
            page.setDefaultNavigationTimeout(120000);

            page.navigate(url);   // in this line the browser is stuck and wait and wait ...  

			
            page.locator("input#username").fill(username);
            page.locator("input#password").fill(password);
            page.locator("button[type='submit']").click();

**Comment by yury-s** [comment]
You can open devtools and inspect the network activity of the page. Perhaps it will shed some light on what's going on. You can also run with `DEBUG=pw:install` to see if playwright fails to load browsers (see [this page](https://playwright.dev/java/docs/browsers) for more information on where they are dowloaded and how to skip it).

**Comment by ronibary** [comment]
thanks will check it

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
