### ISSUE TITLE
[BUG] .not.toBeVisible with short timeouts (or no timeouts) is broken

### ISSUE THREAD

**Issue by AlexDaniel** [microsoft/playwright#18815]
**Context:**
- Playwright Version: Version 1.25.0
- Operating System: Linux
- Node.js version: v18.10.0
- Browser: Chromium, but probably all

I want to write a test to ensure no error message has popped up on the screen. Yes, I understand that negative tests can be flaky, so I am taking extra precautions. Anyway, a basic test can look like this:

```js
await expect(page.locator('text=Blah blah error that clearly does not exist on the page')).not.toBeVisible()
```
However, because toBeVisible has retries, if the error does show up (we're writing a test that makes sure that it doesn't show up), then the retry logic will keep retrying until the timeout. In the project I'm working on, the errors disappear after a little while (after a few seconds), so the retry logic can actually result in the test passing even though the error popped up! **So we need a way to test without waiting for too long (either with no retries at all or with a very small timeout).**

# ①
First I tried reducing the timeout:
```js
await expect(page.locator('text=Blah blah error that clearly does not exist on the page')).not.toBeVisible({ timeout: 10 })
```
But got this failure:
```js
    Error: expect(received).not.toBeVisible()
    Call log:
      - expect.toBeVisible with timeout 10ms
      - waiting for selector "text=Blah blah error that clearly does not exist on the page"
```
Except that it doesn't make sense, it's a false negative. The text is not on the page, and we're testing with `.not`. The fact that I specified the timeout makes the test fail 🤔 

Also, changing the timeout to 100ms makes the test pass.

# ②
So I thought, OK, something is wrong with small timeouts, and I should probably use 0 instead, so I did this:
```js
await expect(page.locator('text=THIS TEXT EXISTS')).not.toBeVisible({ timeout: 0 })
```
But this test passes even if the text is present on the page, even though we are testing with `.not`, it is a false positive!

**Comment by pavelfeldman** [comment]
Are you trying to ensure that something is not visible w/o retries and auto-wait? That would be

```js
expect(await page.locator('text=Blah blah error that clearly does not exist on the page').isVisible()).toBeFalsy();
```

**Comment by AlexDaniel** [comment]
@pavelfeldman doesn't matter. `.not.toBeVisible({ timeout: 10 })` always fails and `.not.toBeVisible({ timeout: 0 })` always succeeds. Obviously, a test should test something instead of just failing/succeeding at all times.

As for what to use, I find `timeout: 0` to be more readable than what you proposed. Testing for something being visible/not visible shouldn't suddenly be written completely differently just because we don't want retries – similar things should look similar. But, at the same time, I guess you're right.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
