### ISSUE TITLE
[Question] Using the beforeMount in js instead of ts

### ISSUE THREAD

**Issue by oliver-freudrich-packwise** [microsoft/playwright#18812]
Hey there, I've tried to use your `beforeMount` function as mentioned in [this ticket](https://github.com/microsoft/playwright/issues/17704) to register global plugins for vue 2, but I am trying to use it an js instead of ts.

index.js
```javascript
import { beforeMount } from '@playwright/experimental-ct-vue2/hooks'; // <= "Resolve error: Cannot find module './node_modules/@playwright/experimental-ct-vue2/hooks.mjs'"
import { registerPlugins } from '@/register';

beforeMount(({ app }) => {
  registerPlugins(app);
});
```

Is that not possible yet or do I have to use it in another way?

**Comment by pavelfeldman** [comment]
The fix will be live in 1.28 in a day or two.
