### ISSUE TITLE
[Question] - (Locust.io) - can i open more than an instance of playwright simultaneally?

### ISSUE THREAD

**Issue by andreabisello** [microsoft/playwright#18821]
i use Locust.io for generating load tests.
Due to the architecture of the website under test, I cannot make api calls and have to act with the browser.
Locust.io is a Python load testing tool that can create "instances" of emulated users that act as instances of a class: each has its own life. I've used locust.io in several cases and also playwright in other cases, but never together.
when locust.io creates a user, it performs the task defined in @task functions.
for this reason i can't use the asynchronous playwright api, only the synchronous one.
when I spawn 2 parallel users, I see that the tasks are executed sequentially: The second user doesn't open the browser until the first one finishes the task. i also tried to set playright as instance variables and not class variables, but the problem there is not related with this. Can anyone suggest me the way to use playwright as a no blocking resources in locust?

![image](https://user-images.githubusercontent.com/2149815/201996387-526c91f9-2e01-4180-a76c-6faa67f881b0.png)

thanks

**Comment by pavelfeldman** [comment]
You can only use one sync instance of Playwright on one thread because it is blocking (sync) by definition.

**Comment by andreabisello** [comment]
@pavelfeldman thanks.
reading from [documentation ](https://docs.locust.io/en/stable/writing-a-locustfile.html#tasks):

```
For every running user, Locust creates a greenlet (micro-thread), that will call those methods.
```
so every running user  should has it own thread,
but i don't know what a "greenlet" technically is.

**Comment by pavelfeldman** [comment]
You can't run one cooperatively concurrent application within the other. Playwright sync will block the thread for the time of its execution. It also uses greenlets to achieve it. To solve this fundamental program, all the modern async frameworks provide an async/await API variations. Playwright has this version of the API, but it looks like you are missing it in the enclosing system.

**Comment by andreabisello** [comment]
@pavelfeldman thanks. so using async variation of the playwright api i can virtually open how much playwright instances i want at the same moment?

**Comment by pavelfeldman** [comment]
Yes, you can, although you should not need to, you can have as many browsers in one Playwright as you like.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by andreabisello** [comment]
@pavelfeldman thanks.
we moved away from locust for this topic, usint pytest xdist to parallelize playwright on different threads.
