### ISSUE TITLE
[Question] swith to iFrame and then leave the iframe

### ISSUE THREAD

**Issue by strusbergAlex** [microsoft/playwright#18828]
Hi,
It appears that i have an issue with clicking on elements on the main page after clicking an element inside an iframe.
The scenario is 
1. set tet in text box - works
2. click on a button - works
3. switch to an internal iframe and click a checkbox - works
4. click on a button outide the iframe - doens't work.
After I do:  await page.frameLocator(`${mainScreen.parentSelector} [title="myframe"]`).locator('myCheckBox').click();
Do I need to do somehting to exit the iframe and switch back to the main page ?
Thanks

**Comment by pavelfeldman** [comment]
Nope, nothing like that is needed. Try running your test step by step using VS Code extension or in --debug mode.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
