### ISSUE TITLE
[Feature] Support single quotes in text selector engine

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#1882]
To improve the developer experience I think, that it would help to also allow single quotes in the text selector engine due the fact that not all code bases use nowadays only single quotes as a standard.

If the code base uses double quotes, the user either has to escape them like that:

```js
await page.waitForSelector("text=\"fooobar\"")
```

or be inconsistent in this code base with quotes and the corresponding coding standard.

(if you agree with that, I'm open to submit a PR for this enhancement.

**Comment by dgozman** [comment]
Makes sense, I'd love to approve the PR 👍
