### ISSUE TITLE
[BUG]:Uploading file using "setInputFiles" or "fileChooser" method not allowing to click submit button on upload dialog menu

### ISSUE THREAD

**Issue by saurabh4888** [microsoft/playwright#18820]
**Context:**
- Playwright Version:1.27.1
- Operating System: Windows
- Node.js version: 14.6
- Browser: Chromium
- Extra: 

Mentioning Code snippet stepwise 
**Code Snippet**

  1.  **await app.navigateTo("http://localhost:4201/");**  _//Navigating to url_

  2. const configFilter = app.ViewOffline.toolbar.configurationFilters; 

  3.  **await configFilter.getFilterConfigurationToggle().click()**;  _//Open main Filter upload menu_
  4.   **await configFilter.upload.getChooseFilterElement().waitFor({ state: "attached", timeout: 1000 })**  __//Checking Sub Uploader menu visibility_

   5. **await configFilter.upload.getChooseFilterElement().setInputFiles(path.resolve('../../../TestData/e2e/StoryTests/445868'))**; _//Send the uploading file destination to sub uploader menu i.e getChooseFilterElement()_
    
    **6.await configFilter.upload.getFilterUploaderTextbox().fill("New Name");** _//Giving new name to uploaded file in uploader dialog box_
    **7.await configFilter.upload.getUploadButton().click();** _//Click finally on uploader dialog box submit button__

**Describe the bug**
  On launching URL ,on **Step 1** ,need to click on uploader dialog menu, once uploader dialog menu opens ,then there again one 
  sub uploader button  in uploader dialog box, so sending the file path s mentioned in **Step 5**, but issue on sending file path ,it closing 
  main uploader dialog box immediately ,so **Step:6 and Step:7** are never getting performed in primary Uploader dialog box.

**Comment by pavelfeldman** [comment]
Playwright only does what you told it to do, it seems like the page closes the dialog itself when input file is selected. If you think this is not the case, please provide a reduced test case that we can reproduce and fix.

As a workaround, you can try using the second snippet from https://playwright.dev/docs/next/input#upload-files.

btw, you probably don't need `await configFilter.upload.getChooseFilterElement().waitFor`

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
