### ISSUE TITLE
[BUG] Passing storage state file/object to BrowserContext is not working

### ISSUE THREAD

**Issue by Kremliovskyi** [microsoft/playwright#18846]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Node.js version: 16.17.0
- Browser: Chromium

**Code Snippet**

```javascript
test.beforeAll(async ({ browser }) => {
  const context = await browser.newContext()
  const loginPage = new LoginPage(await context.newPage())

  await loginPage.open()
  const opportunitiesPage = await loginPage.loginWithMicrosoft(individualUser)

  await context.storageState({ path: 'state.json' })
  await opportunitiesPage.close()
})

test.only('Verify Clients page elements', async ({ browser }) => {
  const context = await browser.newContext({ storageState: 'state.json' })

  const page = await context.newPage()

  const clientsPage = new ClientsPage(page)

  await clientsPage.open()
})

// open is just 
 await this.page.goto(this.url)
```

**Describe the bug**

Local storage is empty and it only works with test.use(), but I can not use test.use() inside the test and I can not prepare the state json file in before all. I also tried passing the object that ` await context.storageState({ path: 'state.json' })` returns and still the same. Also I tried only test part while state.json was already created from previous run and the same. It looks like the pattern `const context = await browser.newContext({ storageState: 'state.json' })` is not working (both with file and object arguments).

The idea is I want to authenticate once per spec file in before all and reuse the state in all the tests inside the spec file, token lifetime is short, I can not prepare state json in global setup once, I need it more often like in beforeAll of each spec.

**Comment by Kremliovskyi** [comment]
I see that it is even not working with test.use(), I bet I saw it working. Here is state.json (github does not support attaching json files for some reason)
{
  "cookies": [
    {
      "name": "x-ms-gateway-slice",
      "value": "estsfd",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "stsservicecookie",
      "value": "estsfd",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "AADSSO",
      "value": "NA|NoExtension",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "SSOCOOKIEPULLED",
      "value": "1",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": 1668607020,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "esctx",
      "value": "AQABAAAAAAD--DLA3VO7QrddgJg7WevrLZSUqiCR-yTShq68tRDqGOaaILiIPwORmH0Hol4UkG31xPxdcmm_MvahWz3FtB96_-shEdGNpZ2dcvGePw4hq5ex4GKOEavtzqDLhIYR_1pjmM-S0DNVhXFHr8AbYmlnhO3-HJUno-K1XHVRkaw_P-gkGENyaS1S_ppESE_hGHox0I1PCiX52uKNBIKFggvym1_lL89O-Bdcv1fZuPEzxrfusL9C8ho6CDERGVaD72EgAA",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "brcap",
      "value": "0",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": 1702302961,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "wlidperf",
      "value": "FR=L&ST=1668606962352",
      "domain": ".microsoftonline.com",
      "path": "/",
      "expires": 1702302962,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "ESTSAUTHLIGHT",
      "value": "+c207414e-d19a-4605-9867-973bc4a05ce9",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "ESTSSC",
      "value": "00",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "uaid",
      "value": "83ed3103b1e047cebb4cfcea759ecb4e",
      "domain": ".login.live.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "MSPRequ",
      "value": "id=N&lt=1668606962&co=2",
      "domain": ".login.live.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "ESTSAUTHPERSISTENT",
      "value": "0.AYEAG-L-8zVrDEWF9LL0zqj2C_-Y5_-KwcpGufaGb7lpOAeBAAA.AgABAAQAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P_BjRp5TeZArvQXJeEQ-QU3hrQraNTIv0czqp6cYc_c4oZRqvrf1u-byDhjCM5GUWB6qpDfGkWM8c7JdOX4jYRUxe6r62O0GHNg0E6BlByddvXiMnRhjwKlmTlE3nPWzpXJr7Le4P_MpxWhRdzIs35u8s84u_NwotmADEQoFdauTpVZ_FqmIcX1xkb5eF0tRgUwx3YEw-MAVlwaXItuKfAuBUyEvs8IFGaMzEWNfEv8c26ww1um9_l0juuk2KImVkRiOgWXJ1zgExOPr47VA80yNlSIa_3q9mkM8kh-9jh7K42GcsBOrwjud_ID417vxFK45YPsX65CvXXiTTrv5-4-KIvwfTjeQSK9uKLxJUJ6wphRzb-j8WbSddmgCF4zpwhohiTCubeUBtnVnBPOHRHsFC1R7TS_Jh1ImWyzuNbHrPVSBYCEc8DWybGunNwjClQhxuGtsDvUzF4VZmP4CLXXN2qYfLWZLD7xeyR74dEAgI9wFCLs83M2mzI2qdPJd9-_DQtqVDkW246zupFPD5OdYL5vnRBoNKJ54c02nEA",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": 1676382963.040215,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "ESTSAUTH",
      "value": "0.AYEAG-L-8zVrDEWF9LL0zqj2C_-Y5_-KwcpGufaGb7lpOAeBAAA.AgABAAQAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P_pfnC9VCevFWS7nbyhoMZ-IIw_DoinyfBf1Ttpwqj9052exKhge4WBcGV6HyKkf8B-pONgYDsFUg",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "ch",
      "value": "sw38lqmK5oZcisVOrBZ9RCPOwzYI6EhMRzpuOerPr2k",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": 1676382963.040296,
      "httpOnly": false,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "buid",
      "value": "0.AYEAG-L-8zVrDEWF9LL0zqj2C_-Y5_-KwcpGufaGb7lpOAeBAAA.AQABAAEAAAD--DLA3VO7QrddgJg7Wevr1x21YExYK3G9_xv37vmBUebZRH2Tg1MBQuPvfDad7D0k8PaC3m26-fS18PdkmAZQ69pHkHxciSN6_PxZFhtftWlbNRQ4AAhupmmcbhk7e5uhHTXyf1XvH4d-TYLH1aMRp3C-7zi-KMZ6xShNyedRXfDg5FHEDEvyCy4Kk_ILizIgAA",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": 1671198963.040322,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "CCState",
      "value": "RWhJS0VNZXQyTkZ4V0Y5RnNUV25Ba1UzMjRFPQ==",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": 1669470963.040337,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "SignInStateCookie",
      "value": "CAgABAAIAAAD--DLA3VO7QrddgJg7WevrAgDs_wQA9P-niIwqRrpS1tn51xpmqC9W-GQeGRtjm6LRZ01T2PX-j8J44bT8UYTgHl1Qg7JzpBqdXd1bcFdvfTpd-T3z1703WVpd-Y_nL3Z-L6HXPsHYmBiTwSziFpTw43i-CMLtOPIPW5tm_yw5xnqtD5-qMJh7rwdaGoVYJc5OcwdkJb2BwP392ejABDr9eNsUwklKDVhwuz3Nvm2lC2eiF0UI1Zmp3G9g3yu5nRXdKwbOIXVuTUdieM0JHX13UsFvRTkZTb3QNw",
      "domain": ".login.microsoftonline.com",
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": "fpc",
      "value": "Ao-rC3MmOl1Hq9uKs94jywiqZ4_-AQAAAPDiBtsOAAAAs4hdnAEAAADx4gbbDgAAAHSHrUkBAAAA8uIG2w4AAAA",
      "domain": "login.microsoftonline.com",
      "path": "/",
      "expires": 1671198963.040366,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    }
  ],
  "origins": [
    {
      "origin": "http://localhost:8080",
      "localStorage": [
        {
          "name": "oauth:provider:credential",
          "value": "{\"idToken\":\"eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiJmZmU3OThmZi1jMThhLTQ2Y2EtYjlmNi04NjZmYjk2OTM4MDciLCJpc3MiOiJodHRwczovL2xvZ2luLm1pY3Jvc29mdG9ubGluZS5jb20vZjNmZWUyMWItNmIzNS00NTBjLTg1ZjQtYjJmNGNlYThmNjBiL3YyLjAiLCJpYXQiOjE2Njg2MDY2NjMsIm5iZiI6MTY2ODYwNjY2MywiZXhwIjoxNjY4NjEwNTYzLCJhaW8iOiJBVFFBeS84VEFBQUFqSzZJR3BLY2wzcURKY0NLaGpZZVFIa0pKa0RUWExwQ1ZrK0dCbnN5VjdpaXNnN2s3UVJFdzhqbURTYXEzZUduIiwibmFtZSI6IkFuZHJpaSBLcmVtbG92c2t5aSIsIm9pZCI6ImYxYWE4Y2YzLTY5ZmEtNDhhMC05MGE0LTlkN2FlYmY2OWQ1OCIsInByZWZlcnJlZF91c2VybmFtZSI6ImFuZHJpaS5rcmVtbG92c2t5aUB0aXRhbmJheS5jb20iLCJyaCI6IjAuQVlFQUctTC04elZyREVXRjlMTDB6cWoyQ18tWTVfLUt3Y3BHdWZhR2I3bHBPQWVCQUtnLiIsInN1YiI6IlhjTHYzYklNTXZicE5CclRoc3BTb3dCLWZ3djJxbDFyNGJlR0VMUGxyS28iLCJ0aWQiOiJmM2ZlZTIxYi02YjM1LTQ1MGMtODVmNC1iMmY0Y2VhOGY2MGIiLCJ1dGkiOiJMWU5rOTB4Q1pVYTlzWGp2aXlvdkFBIiwidmVyIjoiMi4wIn0.kUSrXNML2t_oe96hfh2aaimcZiCXzYTGD3ZMYPNdfNg6N-5twpcPjFSNSNKtqNzZ2igz4ySpl6LqiVuqA7plR1IJV_oXJPn4Cld4DwS6Eg9WfWHhMdJJKjlTph99HoOXeTBWTZusJkVo42gEU98Yd2o0ns-_QFcbp_JfYkgVb-h1JGzrSFbPNnBRwDrIzWUJia-AUaZIQUuoLxswlQ1IYBDbaCNqzgzoAMW9CBX7XFHec-LqgGEhkhWlCLwj2ZXMiI_DFvlZR8KtcEGUCUV7mCh6PNBadaVY--MduFjyt0Khqj9_RLaiPXXKBp9fTgPz4Z-tYdHXOeBrZVuz-usKzA\",\"accessToken\":\"eyJ0eXAiOiJKV1QiLCJub25jZSI6ImFMTnRWUTJJRGc0Qk5BVUhwMTBOY0I5T3l3UWNBOXNPOHR5WjN4U2p0Vk0iLCJhbGciOiJSUzI1NiIsIng1dCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSIsImtpZCI6IjJaUXBKM1VwYmpBWVhZR2FYRUpsOGxWMFRPSSJ9.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTAwMDAtYzAwMC0wMDAwMDAwMDAwMDAiLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mM2ZlZTIxYi02YjM1LTQ1MGMtODVmNC1iMmY0Y2VhOGY2MGIvIiwiaWF0IjoxNjY4NjA2NjYzLCJuYmYiOjE2Njg2MDY2NjMsImV4cCI6MTY2ODYxMTk4OCwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkFUUUF5LzhUQUFBQXNRcExFcC9DWTlxQzRHd0pacVlBTTg0NjZ2anp2WEJTVnhEOWFIejNJVjNWYUlpUWp4UFF3c2RsYjA3ZHZnTFUiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6IlRCLURFVjEtQXBwUmVnaXN0cmF0aW9uIiwiYXBwaWQiOiJmZmU3OThmZi1jMThhLTQ2Y2EtYjlmNi04NjZmYjk2OTM4MDciLCJhcHBpZGFjciI6IjEiLCJmYW1pbHlfbmFtZSI6IktyZW1sb3Zza3lpIiwiZ2l2ZW5fbmFtZSI6IkFuZHJpaSIsImlkdHlwIjoidXNlciIsImlwYWRkciI6IjkxLjIxOC4xMDYuOTciLCJuYW1lIjoiQW5kcmlpIEtyZW1sb3Zza3lpIiwib2lkIjoiZjFhYThjZjMtNjlmYS00OGEwLTkwYTQtOWQ3YWViZjY5ZDU4IiwicGxhdGYiOiIzIiwicHVpZCI6IjEwMDMyMDAyM0NGOUZBMTYiLCJyaCI6IjAuQVlFQUctTC04elZyREVXRjlMTDB6cWoyQ3dNQUFBQUFBQUFBd0FBQUFBQUFBQUNCQUtnLiIsInNjcCI6IlVzZXIuUmVhZCBwcm9maWxlIG9wZW5pZCBlbWFpbCIsInN1YiI6Im1PN2FlNFJKM2dhRDlkRTVEdFo0b2JSLW5aT2g5SUZqbG5tMklMVlJIQkUiLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiRVUiLCJ0aWQiOiJmM2ZlZTIxYi02YjM1LTQ1MGMtODVmNC1iMmY0Y2VhOGY2MGIiLCJ1bmlxdWVfbmFtZSI6ImFuZHJpaS5rcmVtbG92c2t5aUB0aXRhbmJheS5jb20iLCJ1cG4iOiJhbmRyaWkua3JlbWxvdnNreWlAdGl0YW5iYXkuY29tIiwidXRpIjoiTFlOazkweENaVWE5c1hqdml5b3ZBQSIsInZlciI6IjEuMCIsIndpZHMiOlsiYjc5ZmJmNGQtM2VmOS00Njg5LTgxNDMtNzZiMTk0ZTg1NTA5Il0sInhtc19zdCI6eyJzdWIiOiJYY0x2M2JJTU12YnBOQnJUaHNwU293Qi1md3YycWwxcjRiZUdFTFBscktvIn0sInhtc190Y2R0IjoxNjE3ODk3NjUwfQ.gWrCEi-XXaJHZLATtmUJz0aDzzcbrPXWJjIdlPbSzkPV3ucFuqcctBQVlm9U8Vf_A2-udoBmFF3ZcCO1OJNsGvDcrajjDkp2vRssJjMKa7rHZikrAeyFec1tOifj0T28WYRO4Zj-mXi1auImR1QhYJCdhdBPHIMg9YyMVaTE2g9WYQiZmXl7pQeZP_tXuv9wP7EXrbI_VzP_HOUqkLNrR8C45d_dfMQIdnJdMVw_56VYH1EIVCuC2TdF8gIvaXKw3CMu6pA_05o86TEMEZGk4g1AVlFK1DrcsruWHEUvmb8csOOZnuXmoU7wLPxnaqYoq8byWR3_UxSi77UoCN4UVQ\",\"pendingToken\":\"AMzJoSnkb4wpMdQgmdVqeLw9pVWHNNadl-Tv4VnPDIrOtVFn11xBZFLWBWA2mbuiwtsM78L8IZlyT_iZXPh4VcIb5rkDD93toIhp-Hkay_N1RjAxt7hiuQmg_66mEVnu5P-pExKlak9uT0iyxnc_werpjeSD82shtnFHDLp-6K53H3BVMbdHP9yzj0D6i6QCnNvOjxTrlyER5BV5_D4JPcPxb-0zMI_NehqoOGzWYUdYgE5dTpYvuXLNypFvMMyRDejBA6cDfiyAp9gCA4NfyDDPt0kz8HQZVbHEpXjrSUZaHuFvrgJH9rgabcMBrAX14vXHcsVvCuW5mwq4_oDBe9L-EblmzZQ4ldexoK-WjeFc-XzwX8N9YcK2DhWfoFS8SmzTrCbIclMW21hWE1IYSbSK3srNDmySUGy5bi4nBK8KvEsMMk1-vnYfQXGrgIm8-7bg4Vx020E4bmGz1D9i1oc9GeKB6zihJJn7V057JvBlnut9_sFD22262L-kPLiJtsL3KUDf2LLX_zVT5dptsargREhUlE46aG6wNNwXpyLRsvG43raEkHJ4OxON-UdAVkz4liqLJ33dVtf8xZcnBPmYirgelyHDxjJGDXi-1w3xd-oIsNtwlPp2AmyE56ue2n0mkmBwC4_nzU5t0nZcHoJBcg-hEbOEyHrGdFXJIipqHWokgqNOW28KYYrgutVCfFR_RLqapi7pIwVOY9JcTFoLX2VkCjzc1srnE_eemVtcADJcFoLlRwFdzFaNoMV9npySYCgmHzn0mX6kaEim-Ixx8rH78Of_3gnH0UVQrka576iNISiPo3Pt-I2Gd_CBpZC784PmBzfJmiU0zypmldwamO7v-y_xJJSzx7DsMDH332sQmBVtk-xprXXHWc2G521gXQcucZ_wIepu6gZy0qGyFfqT5-DJRztIVmSsZTBCCEdRKhUumN9tQBfFBtk3WUIlLpc-HUAN5_qczjHYEpl15_e7IfmGPrdMeBJ-xyJTNICvBajzPKQ0WgBhik-rfOW76cLiEOZb8xQVJeAX0dIwdW1LZejwvF-uu3zR3eWbFiHRw9N-nUQfUeP85N1echyS0YgBWwISHyV3cq1BdALF9sOfMk6Tzdfs77e85tqzHbLpqworGAue3kp5NAmzicI5fpDNj-GdByLfcuyMz-mxfx90GwQhWQk3F_N4KoVlswOxNAXaSVRy6NPF830ot-tcaz2skN-8IIW_pUoL55ee5rk5vslAO0HwTZ0zftZ7wlt36sUEAFtAXABk1Bm-yAkUtW4mWQj0PHW9T_Xa7gkSTHajvKNVB_A_87fmlZLEFhIqWJAK8YLynmADCknncjgJ8HCJ4FuPLIFmfjvivYXAuj9LNt9JyjK3uW1DZOis-AOU_zKima5MyI8bLeciGp-GDZL-Hxd4tJlGe6ooJecr0Yzbhihq-iNHG8hp1tvlt7PMHrLteqPoVeT59cdxIF5GPjEkDb64RdOo86xgdruUw-lkNDIq1ZDF2llTGxB8Pu_18kFx7lRBsWFaVYCc9KmdGlhU-bgppvzhd1WkOUlWh2saZ0mio85lk77ZhzKlQtY8U7-TR0LCkRf16i_atisCICYK9n4aPFaC8YY-SmJm5LUAl9nHTVPeR_L60f09_kP7IuAZiovAegRDgcRzh9ZQaBnL-Tou2e9ZGducmPwvYQr5nalrB-dk6RcF779raVgwzevFU-KeycwrjRrV-YVqPCZW7fP4wniyef9QO6SyM1vxFere34s0aeRXpevhif-1TxAPS16kKWXt12EO9d4vLGm5hikhoDpQt46fBwLx3UBhYuOPWyTOyjBTyrLAnMmBSVv148pt8rfEj7ioJi4x1y_d43ONn9AvR0DU1WRQe9Q4pACTXwb6L8LP5ecsMxL3SXkuY7qRx23kNborMLx0B64LvAA4AC5vUbdAUALhnJhiCSC_Z4jkC2Z0jolCOh0ANM6oDeg660mflYWnu0AwuplVih8XPkHnzfPtGsXbygARc9ToJ0r2U_YW0opmGDhnGw7HFcahhYNY4M1qjewmpQOTfgMX_50RpT8azpPLE5junAzgESYmu5f4tXf4ffK_GbcPlYQOVVCOiq0ettGQBVN6Ba3OTOsdZhSJRX6fQYRGpyUJ5W3NsZEwsAkWR60im9dpLDwOeDBHppyeWxIFbefpLk-lPbkGTgkEM7Oe6EwXmHFOpc3xjJNEmb4quVJXsRAzHP9MmaFlUY9lTtVtqeImXZSyhEtkPidbyY96YkmxxhyhI0bxGW4BF9dWLWpmz12HD20xQ9LQ6Qw1A6D7CkhmyZNc6TLbD23tFiiIPIe7Vz7CVIx4UFmhhOABGNPA3z7xQ8PNyQptRjhrndRVRQ1dkkyaoJtmGejY-BQuRRRaSc4oxf4VUYbJ28jtUz1aJgC_HSaPoSXaukjfXaOvYr6BFYIHi7qaECqGwEeIZZ6ju7wqM410khvOUFDeODckOw8qdlA-UaLCNf4_TzRhm_CCrq4xMENUNsaQ14rgq-JrQMXhU-qQkFqgWJjaScfHdPsL6bpBUU3YBs20NQBmkpwsCpyzMDuFWhdGv5iY1_0LgFQ1qw70aPxX6dw1Bkcxs82xEmEgO-mts2jloWAxV8_70dSY9TA5WVClcyXLGrBhivgHCi1niz-V_68fzRujlzot65vsfZN8tL0wu5OZHPAmwW8LdmDC_KnZ7JdV6SqF56VqapGwNbr5zzRiSUDExSSEl3xVnkGuO579A-HduGJf_VHcwsFfpPpfo3ifJkj8u_e4yIliFf7HvzTlOF8sZFen3k484UeuIv1m2eM5T9EDX_qUK1LMHcnZJkSI1h8clin5-_fCVudiR0nxtCJsCCUCcuNgBQrogQNUiaetAQyetAN6X8R_1LmDnZBUiOGSG1sL7tL4VDUNJqd5TOqdrdCNoNIs2otsLsf3JNMkgG85hvWnaWgDpvNBlMV8EKUPPGd8yDZwKxqydCi344q2tf4w-wtKDSBK4eAq1D0tSIQ60Lo79cwUVF9KgouRXjr-g3szCID2TduIRUq_kSqfk7x4xSvIx-vhOdDRfQNCNB6WmTzJA7pb2gO3bfZ2gY_e6SmvAmy7yoNVwl1cM45Gyo458Ghbl_-Pj7SVGCIeKB1qeUPdY8FBi6bq0sXS6ZV-MWshh3BWnsg9pjR1uBkLj5nm0sn_F1KZxkLe4J80y3AzHV3-oNQdSMxSAPGIzPgZt7SzBH-Ei-Xm3JmGVLOaPOwTSkLS831Pacb-vhK9D4TUoMu6xomGUEm6vaftQmRsPuO-JxhamOcFi_Aiz5ZPOOKP9c5rad5-_F9tDzJW1LLN99-u20QWxoNBl95AKGAiZh0Zkr0em0RBQfDmQoAuusDZKL-HaZzRH_kuWeEW5nHCUEaJTilDujlYh1PTK4GD-Vt_RC1S18SmdoiMH8kYYPzba6YpJLx61hwNPK_WHSU-qSPqVznwNKhBAV-mcFzdjbF4nw9JtRe74nbY4E6ghwDVeC7RK7BdOSvOa33Ev5fqmhy7D7TIby3kw3LMKXGesmbhaQr9r_cdFduIteESr7BoGXL-_9pX5s_GxjCOI39HHHEpwxoUdLjtpUEiuONiZDtD-SXibX_GzrJXcdASGQV44FWYPKUer1XsYyPvIUS7Vomwp7HN8HrrKBb7CEYf2SAxCCqWX8pTukZo0TAutuEJ5AG3qHrO1uDl6gAXQupBrPl_I8qSRSVwz9EtxvPiW-UtJQiDvBvzKRWGDQimbyNVKGTwn4wm_UVl1HTUzAexVI7Qk0GBOESghdiZgXVli-OfAIyb0YZk0zBU72Dt2NpVYG7A2UHzZKnoRK8qPNm_xiubo9Ia2w9Lyf1r1OoG9C7S7cn-5hSMdL0ycc4KM_VGwonTQjexfK1BR7K64mpeJ2iulv6MsJo67AbuS93tXHXV14uo82kJlM47aqczjdNsUyHvz5Xm_Pxeaxo6KAtw6ngHIgRInGCeqvVug7NJZ9yJZDJnRUzUVSlLmzwhTU1m2jSIjKuYPnQp1Qu1V4dDr5TixiUTDwrITCbiBMSYu6kHw-q5n3aD8-sbav0C2ZhzGtnIWSij5Ler67LQq4h6icAQ2VZgoLA_MNaU5um3Hl1TZKfsnbVB2aOiVUgbSfyFTQCROCZohu1DUXbyvdhLLvtHMUgvX2p6W0ITxf5ssZhTcS99NcJ1FhT4sxKGw8SqsmeknhkpuwMzQyEc2EMHjEHWnoNCTbna9GnzjW59oyC3nKQ6lTRAKz78_Er3Lvodo6exKXXJgjnSm0x32HXmNAphfQkAf28VwyqdOvROosoLSTBoTIRTLmnJFN9gVdQmn2UjCvhhHNqVrHrTamPTHZrkjwiBjzwx-PJY3ZrsyANm1FvKF3eSihtK23lAEQKiPolC4urm0wglPJEG4WF3TUIH9ajyJwL4VH84YkOz-II3h6nhwYkocLmivlsHuZ1QufIcyvF7aM0OF90oMTmXCK6Gg8deRGKk43_y8-sgm0g1SIlYdLyuuHG7mBcr3FbE_KBRWqxl0jh2pU_Ny6MkQ8GPPvGAz6qihY0NoQl3NDd1HrAY-1QoXnrwyRNoHWvW8P7he7UXzVmEJtPMg3XV8vE64thTzb8u5g9p_MPVpBJRE7IPI1rxcF1a3-bSXcEO1tb-IbxipoUExdB1czYNyGtE5OCs1bKMKgIsCMcH7pC0aYeBEKCJnk0aRJ8uXkOFFZBwqS82Nk44ZXQldgmJ_QiZ_fJ3CWHFWh4IJ7hXv0Y4GQMVnvjjhyuGJ5YKCe-b1a7C4Hsa_8lxlce6sAt3YXFMVIA2B7gwg-AwxqqZ8Mf6zNYscIXLVu_Nv0Rbx2FOTnUMdx6Rh6HFQAqrdUVM5eVT4JK8MKxMySO-gG4FJzSCZvma9SzBHw1GGFaUXG8ivpzmlcUkKBs16fOjkYKnGeiriC7phXsiJRwEYw9M2o8zCOMKAkt-RP00o3ivzEjqPWZkhAtIyW7AxNrm-IxLR3TUOZwGx6iJnsrpY9VQO6U06dSyfpt5ecIcFnRh-FQEQwvLqahAXiSQdPL-_dhWAmCipslNTverascI87CWu0ZMHjAv7iwWD8jXGiBO4pTJv8gS3ROcjnWlWXlFqXb4Nfn4OCWe2wz_g-YJ1yueTGIZAkkiOOIZrHe5EK4Z5sOuz6DeLZzwnbCsihjp5mGVvluZ2-arlRDtd6CkQWwpZHOMS_RRtW-CRtYKPRLO0g-gJIF3Fj21CzQlvqYwSNVPa8uG\",\"providerId\":\"microsoft.com\",\"signInMethod\":\"microsoft.com\"}"
        }
      ]
    }
  ]
}

**Comment by Kremliovskyi** [comment]
Ok I found the problem though it states 
```
"origins": [
    {
      "origin": "http://localhost:8080",
```
it is storing it not for localhost but for `"domain": "login.microsoftonline.com",` which is microsoft popup. This domain is set for cookies in state.json file and is applied only to popup. Whenever I open this popup it does not ask me for username and password and just proceeds. I managed to see Local storage of the popup while it is processing and the state is there. Is it microsoft specific stuff? Why is it applied to login.microsoftonline.com  and not localhost ?

**Comment by pavelfeldman** [comment]
We can only help if this is something we can reproduce  locally. My guess would be that you save storage state before authentication happened and the page code had a chance to save corresponding localStorage values - you never wait for it to happen.

**Comment by Kremliovskyi** [comment]
@pavelfeldman I tried `await page.evaluate(value => window.localStorage.setItem('oauth:provider:credential', value), localStorageValue` it has set the localstorage I have previously taken. Whenever I tried to navigate to any page login page refreshed and local storage is erased. So I guess microsoft doesw not allow to reuse auth state. Sorry for bothering, closing ticket.
