### ISSUE TITLE
[Question] offline install playwright browser but failed to read message pipe closed

### ISSUE THREAD

**Issue by 1355692540** [microsoft/playwright#18841]
1:  l copy the java maven playwright jar and chronium(from another pc which surely can use playwright correctly ,the path is 
xxx/local/ms-palwrght/*  ,ffmpeg-1007 and chronium-1012) to my pc,  
then use code to set playwright_skip_browser=1 and  set playwright_browser_path= xxx/local/ms-palwrght. but exception 
failed to read message pipe closed.

**Comment by pavelfeldman** [comment]
Nothing we can do here due to no steps, no exception details and the manual Playwright installation that is not per the official instructions.
