### ISSUE TITLE
[BUG] nested locator cannot then be used in has options

### ISSUE THREAD

**Issue by amado-saladino** [microsoft/playwright#18856]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Linux]
- Node.js version: [v16.18.1]
- Browser: [Chromium]

**Code Snippet**

```javascript

 activate = async (tab: Locator) => {
  const span = tab.locator('span:has-text("some label")')     // returns  "app-tablist >> span[class*=history]" but expected to get only the span
  await tab.locator('a', {has: span}).click()   // should get me the link that encloses span element
}
  
```

**Describe the bug**

I tried to locate an element regarding to an outer element ---> let's say *a span*
then I need to get the enclosing _anchor_ element that contains that *span*

I got this error:
Timeout locator.click: Timeout 40000ms exceeded

a >> internal:has="app-tablist >> span[class*=history]"

where `app-tablist` is the selector of the element locator passed in as a parameter to the given method
This element `app-tablist` is a container for all tabs.

**Comment by pavelfeldman** [comment]
Your first locator is likely to resolve to something outside your anchor, because you say "has-text" and enclosing elements also have that text. What you could do is:

```js
await tab.locator('a', {hasText: 'some label'}).click()
```

or

```js
await tab.locator('a', {has: tab.getByText('some label')}).click()
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by amado-saladino** [comment]
> Your first locator is likely to resolve to something outside your anchor, because you say "has-text" and enclosing elements also have that text. What you could do is:
> 
> ```js
> await tab.locator('a', {hasText: 'some label'}).click()
> ```
> 
> or
> 
> ```js
> await tab.locator('a', {has: tab.getByText('some label')}).click()
> ```

the first locator resolves to `a span`  inside an anchor element.
This line of code got me what I need:

```
await tab.locator('a', {hasText: 'some label'}).click()
```

The second one will do the same thing I wanted to do before, it will try to resolve to an element that does not exist
