### ISSUE TITLE
[BUG] Not waiting for network events

### ISSUE THREAD

**Issue by martinowren** [microsoft/playwright#18852]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Mac
- Browser: All
 - Node: 16.17.1 - ~/.nvm/versions/node/v16.17.1/bin/node
 - Yarn: 1.22.19 - ~/Documents/personal/headless-rm/node_modules/.bin/yarn
 - npm: 8.15.0 - ~/.nvm/versions/node/v16.17.1/bin/npm

```javascript
test('Edit cart item', async ({ page }) => {
	await page.setViewportSize({ width: 1280, height: 720 });
	await page.goto('/design-selv/');

	await page.setInputFiles(
		'[data-cy="design-selv_uploadfile"]',
		'tests/files/logo-1.png'
	);

	await page.locator('[data-cy="design-selv_type_standard"]').click();
	await page.locator('[data-cy="design-selv_antall"]').fill('1000');

	await page.locator('[data-cy="design-selv_addtocart"]').click(),
	await expect(page).toHaveURL(/handlekurv/);
});
```
On the last click() it does not seem to finish the complete onClick handler. It does the first of 3 API calls, then stops. At that point playwright times out.

**Comment by martinowren** [comment]
[trace.zip](https://github.com/microsoft/playwright/files/10023940/trace.zip)
Trace^

**Comment by martinowren** [comment]
I have tried to wait for networkIdle, wait manually, use different selectors, different locators

**Comment by pavelfeldman** [comment]
Thanks for sharing the trace. When I open the 'After' snapshot in the last click action, I can see the following image:

![trace_after](https://user-images.githubusercontent.com/883973/202287314-9b81def3-43dd-4c5d-8641-a35e6d8f68ac.png)

This makes me think that Playwright has done it's job clicking. You seem to be stuck on the last await expect(page).toHaveURL(/handlekurv/). You can try running you script with --debug to see whether navigation actually commits.

**Comment by martinowren** [comment]
The last click() has a long onClick handler. Is there a way that I can give a sign to playwright that it is still doing its thing? 
For example using aria-busy etcetc?

**Comment by pavelfeldman** [comment]
You can add { timeout: 15000 } to the subsequent toHaveURL call to let Playwright know that it'll be waiting for it to happen for a long time.

**Comment by martinowren** [comment]
For me, it feels like playwright blocks the onClick handler after the first request (of 3).  The actual call should only take up to 5 seconds, but playwright will time out at 30 seconds, because it will never finish the onClick

**Comment by martinowren** [comment]
Here is the onClick handler when done locally in a normal browser: 
![image](https://user-images.githubusercontent.com/22822433/202505511-d7ef38d3-7e52-4bad-bc5c-970b7c558108.png)

Here is it in playwright: 
<img width="223" alt="image" src="https://user-images.githubusercontent.com/22822433/202505569-5dfbebb5-ee84-4e89-a99b-a5c656bd4bd4.png">


Exact same steps taken

**Comment by martinowren** [comment]
Narrowed it down further. This is where playwright fails. :

`thumbnail = dataURL` never happens 

```javascript
			const svg = drawingElement;
			const boundingBox = svg.getBBox();
			const img = new Image();

			// Export SVG to xml.
			var xml = new XMLSerializer().serializeToString(svg);

			// Base64 encode xml.
			var svg64 = btoa(xml);
			var b64Start = 'data:image/svg+xml;base64,';

			// Create base64 encoded image.
			const image64 = b64Start + svg64;

			// Set image src to base64 encoded image.
			img.onload = () => {
				const canvas = document.createElement('canvas');
				canvas.width = boundingBox.width;
				canvas.height = boundingBox.height;

				// draw the image to the canvas
				canvas
					.getContext('2d', { willReadFrequently: true })
					?.drawImage(img, 0, 0);
				const dataURL = canvas.toDataURL('image/jpg');
				thumbnail = dataURL;
			};
			img.src = image64;
```
