### ISSUE TITLE
[Question] How to cancel the dialog listener with python

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#18868]
In our test scenario, we need to listen to the dialog once before doing a certain operation, and if it appears, then accept it, or there may not be a dialog, and when the operation is completed, if the dialog is still listening, it needs to be canceled to avoid the impact on the later dialog.

**Comment by god-pane** [comment]
page.once("dialog", lambda dialog: dialog.accept())   this listener

**Comment by pavelfeldman** [comment]
if you don't have dialog listeners at all, the dialogs are going to be accepted. So don't install your listener to just accept the dialog. You can also use page.off to remove listeners

**Comment by god-pane** [comment]
There is no page.off method in the python language
