### ISSUE TITLE
[Question] disabled Chrome is being controlled by automated test software

### ISSUE THREAD

**Issue by cosoc** [microsoft/playwright#18872]
![image](https://user-images.githubusercontent.com/19447682/202375999-4b1848c7-efdd-414a-a24d-4af10a7b275b.png)

how to ban this message

![image](https://user-images.githubusercontent.com/19447682/202375344-49b9012c-2b19-4e83-8195-05c090e06ef3.png)

but have

![image](https://user-images.githubusercontent.com/19447682/202375473-e28c9e3d-56c7-4abf-9509-c5b6abd71faf.png)

**Comment by pavelfeldman** [comment]
This is out of scope for Playwright.
