### ISSUE TITLE
[BUG] "Pick locator" disabled when running my test

### ISSUE THREAD

**Issue by baptisteArno** [microsoft/playwright#18874]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: 18
- Visual Studio Code version: 1.73.1
- Playwright for VSCode extension version: 0.2.16

For some reason, the "Pick locator" button is greyed out when running my test:

https://user-images.githubusercontent.com/16015833/202400889-8fdb0144-7a23-493d-b731-00d1022a863e.mp4

**Comment by pavelfeldman** [comment]
That's as designed, you can use it when the test finishes, otherwise picking locator interferes with the running script.

**Comment by baptisteArno** [comment]
Oh, but that would be super useful if the test is stuck, and you want to pick a particular element selector. Any chance we can enable it when running in debug mode at least?

**Comment by pavelfeldman** [comment]
> Oh, but that would be super useful if the test is stuck

The risk here is that as you interact with the page, the test can get unstuck.

> Any chance we can enable it when running in debug mode at least?

Makes sense, scheduling it for the next milestone!

Btw, with the latest version of Playwright and the latest version of the VS Code extension, you should be able to do the following: comment out everything after the test, run it, it'll stay on the last state. Then you can pick selector. But I'm sure you've figured it out and want something better. Understandable.
