### ISSUE TITLE
[Question] Is there a way to access playwright version information in code?

### ISSUE THREAD

**Issue by Songyu-Wang** [microsoft/playwright#18886]
I would like to have a framework validation test that basically do this:
```
pass the test iff the playwright version === "a hardcoded number"
```
Unfortunately, I cannot find code allow me to do that. Is this a functionality supported? Or do I need to jump out to run a bash script and jump back in?

**Comment by pavelfeldman** [comment]
You can use `const version = require('@playwright/test/package.json').version` as a workaround.

**Comment by Songyu-Wang** [comment]
Ah yea, I guess that works. Thanks. And im not sure if I should close this issue since you added an assignee. Let me know. Thanks again
