### ISSUE TITLE
[Question]How can I wait for selector and don't break out when it can't find a element?

### ISSUE THREAD

**Issue by Three-Colors** [microsoft/playwright#18880]
In my case, one element may have two selectors. I want to `await page locator('the first selector')`, if the first selector can't get a **stable** Element. I will try the second selector. So, I don't want to break out when I use `await page locator('the first selector').waitFor()` or `await page.waitForSelector('the first selector')`, how can I achieve the following code logic:

> const xpathElement = page.locator(xpath)
const selectorElement = page.locator(selector)
if(xpathElement) {
   await xpathElement.click()
} else if(selectorElement && selectorElement.lenght === 1) {
  await selectorElement.click()
} else {
  console.error('can not find element')
}

**Comment by pavelfeldman** [comment]
`const found = await page locator('the first selector').waitFor({ timeout: 3000 }).then(() => true).catch(() => false);`
