### ISSUE TITLE
[BUG] Codegen doesn't use testIdAttribute from config file

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#18888]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Mac
- Node.js version: 14
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
use: {
  testIdAttribute: 'data-test-id',
}
```

**Describe the bug**
While recording a test using codegen, if we use custom data test id like `data-test-id` instead of `data-testid`, the codegen locator explorer doesn't pick it up from the playwright config. It will try to use `.locator` instead of `.getByTestId`.

**Comment by netcompany-sadiksahin** [comment]
I am experiencing the same issue. Would appreciate this being configurable :)

**Comment by aslushnikov** [comment]
This is fixed for VSCode extension.

**Comment by BohdanZinkevych** [comment]
just use **npx playwright codegen --test-id-attribute=data-stable-name**
