### ISSUE TITLE
[Feature] Make Run Tests and Debug Tests default profile in sync

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#18885]
Minor request - Currently, in vscode extension when changing default profile under Run Tests button, it doesn't automatically change it under Debug Tests button. Need to change it again in debug tests.

Does it make sense to make them in sync instead of doing it twice?
<img width="245" alt="Screen Shot 2022-11-17 at 9 41 00 AM" src="https://user-images.githubusercontent.com/22205721/202519167-0eb259f5-6ff2-4bbe-a56e-650e5fc8f05f.png">

**Comment by pavelfeldman** [comment]
Would you mind filing it against vscode and linking this issue to it?

**Comment by pavelfeldman** [comment]
Folding into the VSCode issue.
