### ISSUE TITLE
Playwright Debugger Uncaught TypeError: elementText(...).full.trim(...).replace is not a function

### ISSUE THREAD

**Issue by asgharkrk** [microsoft/playwright#18896]
Hi,
I am using playwright with javascript to develop a framework, But every time I try to use codeGen tool or debugger from playwright I get this error and the page stops responding "Uncaught TypeError: elementText(...).full.trim(...).replace is not a function" Please help me fix this issue. Thank you.
OS:WIndows 11
Playwright version: 1.27.1
Language binding:Javascript

**Comment by dgozman** [comment]
@asgharkrk Do you mind sharing the page url? I suspect that it overwrite `String.prototype.replace` function, but I am not 100% sure.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
