### ISSUE TITLE
[BUG] frame.inner_text('body') is returning <script> content as well

### ISSUE THREAD

**Issue by sohaib17** [microsoft/playwright#18894]
**Context:**
- Playwright Version: playwright==1.27.1
- Operating System: Ubuntu 20.04
- Python Version: 3.8
- Browser: Chromium 105.0.5195.19

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and that we can run and debug locally.

```import os
import asyncio
from playwright.async_api import async_playwright, Error


async def request(request):
    pass


async def coroutine():
    async with async_playwright() as playwright:
        # Launch browser
        binary = playwright.chromium
        browser = await binary.launch(headless=True)
        page = await browser.new_page()
        page.on('request', request)
        await page.goto("https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_areamap2")
        for frame in page.frames:
            try:
                txt = await frame.inner_text('body', timeout=3000)
            except Error:
                txt = ''
            print('*****' + frame.name)
            print('*****' + frame.url)
            print(txt)
            print('\n\n\n')
        await browser.close()


asyncio.run(coroutine())
```

**Describe the bug**

I am trying to extract inner frame text using the code above. Instead of printing only the body text part, it is printing <script> tag as well. However when I open the URL and access the frame in my browser, it returns the text correctly e.g. the following works fine:
```
document.getElementById('adg-0-sync').innerText
```

**Comment by sohaib17** [comment]
@dgozman are your steps same as the one mentioned in OP? I reran the test case with latest build (PyPW 1.28 and Chromium v108) and can still see the script tags being returned.

Please see attached screenshots against an ad iframe from this URL.

**- This is the text I got by running the test case:**
![test-output](https://user-images.githubusercontent.com/16270214/203311351-0c52ad3f-971a-4fe2-a6b6-033aca2285ac.png)

**- Whereas Browser console returns empty innerText against this iframe:**
![console-output](https://user-images.githubusercontent.com/16270214/203311486-1403c009-fa6f-4640-9785-a3064cc936d8.png)

**Comment by dgozman** [comment]
@sohaib17 Oh, here you are calling `innerText` not on the `body` element, but on the outer `iframe` element instead. I'd suggest to select the `<body>` in the elements panel, and then try `$0.innerText` in the console. Let me know how that goes.

**Comment by sohaib17** [comment]
@dgozman selecting the `<body>` tag and trying `$0.innerText` made the output similar to test script.

I am trying to extract `iframe` text just like we can extract a `page` text in pw. In case of page, I can do `page.inner_text('body')` to extract text version of a page (ignoring script tags). Is there anything similar for iframes in playwright (get plain text content of an iframe)?

I tried to do `frame.inner_text('body')` but result includes script tags too instead of just text version of `iframe`.

**Comment by dgozman** [comment]
> I tried to do `frame.inner_text('body')` but result includes script tags too instead of just text version of `iframe`.

This should work exactly the same as `page.inner_text()`. I think for this particular `iframe`, inner text just includes the `<script>` tag, but usually that's not the case. Perhaps that's a browser bug, or some edge case behavior in web spec? Unfortunately, there is no easy solution for this. Playwright just calls `element.innerText` and if browser decides to include the script contents, you'll get the script contents.

If all you need is to just get some text, try removing all script elements before taking the text:
```py
await frame.locator("script").evaluate_all("scripts => scripts.forEach(script => script.remove())")
text = await frame.locator("body").inner_text()
```

**Comment by sohaib17** [comment]
@dgozman thanks. I will give this snippet a try.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
