### ISSUE TITLE
[Question] Request interception not working sometimes

### ISSUE THREAD

**Issue by morfies** [microsoft/playwright#18904]
Here is my demo code in a fixture:

```ts
let browserCtx = await browser.newContext({
  serviceWorkers: 'block',
});

const entry = {url: '/api1', data: {some: 'mock data'}}

await browserCtx.route(entry.url, (route) => {
  route.fulfill({
    body:
      typeof entry.data === 'string'
        ? entry.data
        : JSON.stringify(entry.data),
  });
});


await use(page);

await page.close()
```

The `/api1` mocking not always working, it will fail sometimes.

Not sure if I am using the right way, should I wait for some event before running the test cases?

Thanks

**Comment by JonahKK** [comment]
How was the `page` created?
It seems that you've created new context, yet you pass in `use` the `page`, which is created in different context. That is why the registered route does not work.

**Comment by morfies** [comment]
Yes, that makes sense.  Thank you very much for the explanation sir.
