### ISSUE TITLE
[BUG] The same tests runs twice through jenkins pipeline script even after specifying the worker to 1

### ISSUE THREAD

**Issue by harshith-rm** [microsoft/playwright#18906]
Hi,

I am integrating the abc.spec.js file to run in jenkins pipeline script. The issue is, first it runs the script correctly and again it starts the script from first line of abc.spec.js which means it runs the same script twice. And after the execution it print the letter 'F', not sure what does this mean.

**Pipeline Command**

cd ./record-and-play
npx playwright test --list
npx playwright test sales-order-return.spec.js --project=chromium --workers=1

**Jenkins Console Logs**

+ npx playwright test sales-order-return.spec.js --project=chromium --workers=1
Running 1 test using 1 worker
'sales-order-return' : Entered Phone Number
'sales-order-return' : Clicked on Generate OTP
'sales-order-return' : Entered OTP
'sales-order-return' : Clicked on Login Button
'sales-order-return' : User logged in successfully
'sales-order-return' : Navigated to Sales Order page
'sales-order-return' : Clicked on Search in Sales Order page
'sales-order-return' : Clicked on Search button Sales Order page
'sales-order-return' : Clicked on Return in Sales Order page
×'sales-order-return' : Entered Phone Number
'sales-order-return' : Clicked on Generate OTP
'sales-order-return' : Entered OTP
'sales-order-return' : Clicked on Login Button
'sales-order-return' : User logged in successfully
'sales-order-return' : Navigated to Sales Order page
'sales-order-return' : Clicked on Search in Sales Order page
'sales-order-return' : Clicked on Search button Sales Order page
'sales-order-return' : Clicked on Return in Sales Order page
F

**playwright.config.js file**

//Run tests in files in parallel
fullyParallel: false,
//Fail the build on CI if you accidentally left test.only in the source code.
forbidOnly: !!process.env.CI,
//Retry on CI only
retries: process.env.CI ? 1 : 0,
//Opt out of parallel tests on CI.
workers: process.env.CI ? 1 : undefined,

**Comment by MindaugasMateika** [comment]
F means failure and your config is set to retry tests once so it runs it again.
