### ISSUE TITLE
[Feature] Front-end performance testing

### ISSUE THREAD

**Issue by nadvolod** [microsoft/playwright#18912]
It would be great if Playwright could do front-end performance testing using something like Google Lighthouse. For example, Cypress has `cypress-audit`. Something similar where we can run a test and assert the metrics would be great to do with Playwright.

**Comment by pavelfeldman** [comment]
Could you narrow down your request? We need to know the exact use case and the exact perf data you are after. I.e. what exactly you'd like to collect and how exactly you intend to use it.

**Comment by imartinflores** [comment]
@nadvolod there used to be a package https://www.npmjs.com/package/playwright-lighthouse - I have never used it and not sure if it still being updated, but I think is similar to cypress-audit

**Comment by nadvolod** [comment]
@pavelfeldman as a software engineer I would like to be able to run automated front-end performance tests using Google Lighthouse metrics.

- Create an automated test that allows me to open a URL and test for certain Lighthouse metrics. Below is an example from cypress-lighthouse. I imagine something similar from Playwright

```js
    it('has maintained lighthouse metrics', () => {
        cy.visit('/')
        cy.lighthouse({
            accessibility: 77,
            'best-practices': 87,
            seo: 75,
            pwa: 20,
            performance: 30,
        })
    })
```
- The test should fail and report on the metrics that did not meet our acceptance criteria
- Initially, this would be great at least for desktop browsers. A future iteration could include mobile emulation as well
- Being able to configure CPU throttling and internet speeds

Let me know if you need more clarification.

**Comment by nadvolod** [comment]
> https://www.npmjs.com/package/playwright-lighthouse

@imartinflores  Looks interesting but hasn't had any commits since April 2022 🤔

**Comment by pavelfeldman** [comment]
@nadvolod there isn't much from Cypress in this snippet above, you only use it to navigate the page and then to run Lighthouse. Ironically, lighthouse would always need to re-navigate to the page (multiple times) while it is performing its analysis, so this initial Cypress navigation is a pure overhead.

So this looks like a test runner + Lighthouse integration request. https://github.com/GoogleChrome/lighthouse/blob/main/docs/readme.md#using-programmatically has four lines that you can run in your test to get what you need, you could extract them into a function and get the desired result, wdyt?

**Comment by nadvolod** [comment]
@pavelfeldman good to know about the initial Cypress navigation, thanks for pointing that out 👍 

Yes, a test runner + Lighthouse integration. The issue for me with direct Lighthouse integration is that it's not automated. Looks like I could manually construct my assertions on the result of the `await lighthouse('https://example.com', options);` . However, seems more difficult than just calling a function with some pre-configured behavior. I can build that function myself or Playwright can build it into its capabilities and have that as a feature to benefit the entire community. Wdyt?

**Comment by dgozman** [comment]
@nadvolod It would be awesome if you would like to build a convenient integration! If you could publish it to share with anyone else that needs it, that would be even better 😄 

It is not a top priority for Playwright to include such a feature right now, but I'll leave this feature request open for future prioritization.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
