### ISSUE TITLE
[Question] Migration from Protractor to Playwright for larger spec files

### ISSUE THREAD

**Issue by kedarsprabhu** [microsoft/playwright#18916]
Our team was just getting started with migration from Protractor to Playwright. We have huge Protractor spec files with lots of PO's, reusable methods and dependencies from other private artefacts. Please suggest how to go about on migration. Have already gone through Protractor to PW migration Doc on the website but it seems to be fine for smaller scripts.

**Comment by pavelfeldman** [comment]
You can port your POs, reusable methods, etc. from Protractor to Playwright on a 1:1 basis. There isn't much we can say outside of that doc.

**Comment by kedarsprabhu** [comment]
Oh! We used a migration tool which wasn't much effective on longer specs. Need to figure out if anything else can be done

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
