### ISSUE TITLE
[Question] How to validate text in a disabled field

### ISSUE THREAD

**Issue by WallaceAnalista** [microsoft/playwright#18918]
I have a specific field, which has a value shown. I need to validate the text, but the field is disabledand it is not allowed to enable this field. I'm using JavaScript.

Please, could anyone help me how do I validate the text of this field?

**Comment by Nav-2d** [comment]
You can do something like this:
```
await expect(page.locator('[name="disabled"]')).toHaveText('YOUR_VALUE')
```

**Comment by WallaceAnalista** [comment]
Hello Nav,

Thanks for the information.

I did it that way but it didn't work.

await expect(page.locator('[totalAtendimentoAbertoLabel="disabled"]')).toHaveText('16.515,27')

This is the field information:

<input type="text" disabled="disabled" value="16.515,27" id="totalAtendimentoAbertoLabel" style="width: 100px;text-align: right;height: 28px;" autocomplete="off">

Regards,

**Comment by WallaceAnalista** [comment]
<input type="text" disabled="disabled" value="16.515,27" id="totalAtendimentoAbertoLabel" style="width: 100px;text-align: right;height: 28px;" autocomplete="off">

**Comment by WallaceAnalista** [comment]
input type="text" 
disabled="disabled" 
value="16.515,27"
id="totalAtendimentoAbertoLabel" 
style="width: 100px;text-align: right;height: 28px;" autocomplete="off"

**Comment by WallaceAnalista** [comment]
Hello Nav,

Thanks for the information.

I did it that way but it didn't work.

await expect(page.locator('[totalAtendimentoAbertoLabel="disabled"]')).toHaveText('16.515,27')

This is the field information:

input type="text"
disabled="disabled"
value="16.515,27"
id="totalAtendimentoAbertoLabel"
style="width: 100px;text-align: right;height: 28px;" autocomplete="off"



Regards,

**Comment by WallaceAnalista** [comment]
`input type="text"disabled="disabled"value="16.515,27"id="totalAtendimentoAbertoLabel"style="width: 100px;text-align: right;height: 28px;" preenchimento automático="desligado"`

**Comment by WallaceAnalista** [comment]
Hello Nav,

Thanks for the information.

I did it that way but it didn't work.

`await expect(page.locator('[totalAtendimentoAbertoLabel="disabled"]')).toHaveText('16.515,27')`

This is the field information:

`input type="text"disabled="disabled"value="16.515,27"id="totalAtendimentoAbertoLabel"style="width: 100px;text-align: right;height: 28px;" autocomplete="off"`

Regards,

**Comment by pavelfeldman** [comment]
You want `toHaveValue`

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
