### ISSUE TITLE
[BUG] Electron firstWindow times out after upgrading to 1.28.0

### ISSUE THREAD

**Issue by tnorling** [microsoft/playwright#18928]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Tested on Windows and Mac
- Node.js version: 16
- Browser: Electron
- Extra: Wasn't a problem in 1.27.1 or below. Repros 100% of the time after upgrading.

**Code Snippet**

```javascript
import { ElectronApplication, Page, _electron as electron } from "playwright";

(async () => {
  const electronApp = await electron.launch({
            args: [path.join(__dirname, "../dist/App.js"),
            '--enable-logging',
            '--skip-welcome',
            '--disable-telemetry',
            '--no-cached-data',
            ],
            env: {
                automation: "1",
                authConfig: JSON.stringify(config),
            }
        });
  const page = await electronApp.firstWindow(); // times out after 30 seconds
})();
```

**Describe the bug**

After upgrading to 1.28.0 Electron tests are all timing out. Downgrading to 1.27.1 resolves the issue. Example test to assist in repro can be found [here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/samples/msal-node-samples/ElectronTestApp/test/electron-code-aad.spec.ts)

**Comment by pavelfeldman** [comment]
Which Electron version is that?

**Comment by sanperrier** [comment]
electron@14 same

**Comment by tnorling** [comment]
We're using 18

**Comment by pavelfeldman** [comment]
@tnorling I tried following the steps in repo you linked, but they seem to be out of date. I tried to do what makes sense to bring it up (including commenting out puppeteer usage), but still no luck. It is missing mode modules, etc. Can someone share a smaller repro for the problem?

**Comment by tnorling** [comment]
@pavelfeldman Sorry about that, I stripped out all the unnecessary stuff in [this branch](https://github.com/AzureAD/microsoft-authentication-library-for-js/tree/repro-playwright-issue/samples/msal-node-samples/ElectronTestApp). The most minimal repro is literally the code shared in the original issue. Try to launch an electron app then await `firstWindow`

**Comment by pavelfeldman** [comment]
Sounds good, I can repro, we will try to fix it as a part of 1.28.1.

**Comment by pavelfeldman** [comment]
The fix should be live now.

**Comment by cawa-93** [comment]
Still have this issue with 1.28.1

**Comment by mxschmitt** [comment]
> Still have this issue with 1.28.1

Can you file a different issue with a repro? Thanks

**Comment by andirsun** [comment]
Still happening on 1.28.1

**Comment by mxschmitt** [comment]
@andirsun can you provide us a repro and file a new issue with it?

**Comment by andirsun** [comment]
@mxschmitt let me work on that.

**Comment by andirsun** [comment]
@mxschmitt Here is the repo https://github.com/andirsun/electron-test run ```npm run test``` must works normally, then upgrade to playwright 1.28.1 and try to run again ```npm run test``` will fail.
