### ISSUE TITLE
[Question] How to fail the current test execution if pre hook has a failure 

### ISSUE THREAD

**Issue by fasatrix** [microsoft/playwright#18921]
Hi
Is there a way to fail/retry the current test execution if something goes wrong in any of the PreHooks?
I see we have a `test.fail()` annotation but does that work in the before hook?
Our use case: we have some complex setup as a pre condition to tests (creating users, setting up data into a database etc) and a number of things can go wrong from time to time and I am trying to find a rubust way to skip/fail the test if anything goes wrong as no point of executing tests if we know already they are going to fail.

Thanks for the answer

**Comment by pavelfeldman** [comment]
How do you run your complex setup? If it is a part of the global setup, then failing the global setup blocks the test run. If that failure is in beforeAll/beforeEach, dependent tests are not executed. What PreHooks are you referring to?

**Comment by fasatrix** [comment]
> How do you run your complex setup? If it is a part of the global setup, then failing the global setup blocks the test run. If that failure is in beforeAll/beforeEach, dependent tests are not executed. What PreHooks are you referring to?

@pavelfeldman thanks for the quick answer. I am mainly after the before all/beforeEach

**Comment by pavelfeldman** [comment]
`test.fail()` is not what you think it is - it marks test as failing. What you want is to throw an exception there `throw new Error('Could not set up data');
