### ISSUE TITLE
[Feature]  Soft assertions in playwright java , so that all steps will run after that i can check which steps got failed

### ISSUE THREAD

**Issue by TannuBansal56** [microsoft/playwright#18930]
I have a scenario where we have multiple scenarios to assert. I want to finish off all assertions irrespective of their status and need to see what all assertions got passed or failed once all validations steps were done.
Is there any way to do this in Playwright in java

**Comment by dartyuhov** [comment]
You can use 3rd party tools like [assertJ](https://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/SoftAssertions.html) or built-in assertions based on test-runner that you're using [Junit5 (assertAll)](https://junit.org/junit5/docs/current/user-guide/#writing-tests-assertions) or [TestNG SoftAssert](https://www.javadoc.io/doc/org.testng/testng/6.8.8/org/testng/asserts/SoftAssert.html)

**Comment by dgozman** [comment]
As @dartyuhov says, this heavily depends on your test runner. You can already use soft assertions available in your framework, but most likely they will not work with [Playwright's own assertions](https://playwright.dev/java/docs/test-assertions).

I'll close this issue in favor of https://github.com/microsoft/playwright-java/issues/819.
