### ISSUE TITLE
[BUG] Arabic characters are broken in snapshots in Playwright versions above 1.24

### ISSUE THREAD

**Issue by obulat** [microsoft/playwright#18948]
**Context:**
- Playwright Version: [what Playwright version do you use?] Any version above 1.24.0
- Operating System: [e.g. Windows, Linux or Mac] Linux (inside Docker)
- Node.js version: [e.g. 12.22, 14.6] 16.15.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chrome

**Describe the bug**

Arabic characters in the snapshots are broken in Playwright version above 1.24.

At [Openverse](https://wordpress.org/openverse), we use Playwright for end-to-end and visual regression testing. To make sure that RTL layouts work, we auto-generated some Arabic text for tests. These tests work well until Playwright version 1.24, but in later versions, the rendering of Arabic text is broken: the letters are displayed differently, and there are some broken characters. Here, the broken version is on the left, and the expected snapshot is on the right:
<img width="573" alt="Screenshot 2022-11-21 at 7 25 51 AM" src="https://user-images.githubusercontent.com/15233243/202965614-fd8217ac-15b7-4b55-882e-7fe3fc7a0a07.png">

Interestingly, when you open the `trace` archive, all characters are displayed correctly. 

[trace.zip](https://github.com/microsoft/playwright/files/10053311/trace.zip)

For context, this is the PR where we tried to update Playwright to higher versions but had to pin it to 1.24: https://github.com/WordPress/openverse-frontend/pull/1646

**Comment by dgozman** [comment]
@obulat What docker image do you use? I expect this to be a fonts issue. The fact that rendering trace snapshots locally works as expected also hints at the environment being the culprit.

**Comment by obulat** [comment]
Using the `jammy` image instead of `focal` seems to have fixed this issue. The font rendering inside the Docker container still looks worse than on a Linux desktop machine, even for English texts.

**Comment by aslushnikov** [comment]
Let me keep this open to investigate what's happening.
