### ISSUE TITLE
[BUG] "npx playwrite test" get 404 error

### ISSUE THREAD

**Issue by avizilbershtein** [microsoft/playwright#18941]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Windows 10 x64
- Node.js version: 18.12.1 NPM: 9.1.2
- Browser: Chromium
- Extra: 

**Code Snippet**

I run "npx playwrite test" but get error

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/playwrite - Not found
npm ERR! 404
npm ERR! 404  'playwrite@*' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\azilbers\AppData\Local\npm-cache\_logs\2022-11-20T16_03_57_436Z-debug-0.log

[2022-11-20T16_03_57_436Z-debug-0.log](https://github.com/microsoft/playwright/files/10050136/2022-11-20T16_03_57_436Z-debug-0.log)

**Comment by Nav-2d** [comment]
You need `npx playwright test`

**Comment by mstepin-edt** [comment]
Looks like a typo there. You have `playwrite` but I think it should be `playwright`....

**Comment by avizilbershtein** [comment]
Yes sorry my mistake it works fine. 
To install it i did copy paste from website and it was installed successfully. But to run it i typed manually.
I tried few hours to find a solution to the error i saw and didn't thought for a second i have typo.

Thanks all

**Comment by mozeryansky** [comment]
> Looks like a typo there. You have `playwrite` but I think it should be `playwright`....

Just want to say I also experienced this bug 😉
