### ISSUE TITLE
[Question] global-setup not storing the correct info

### ISSUE THREAD

**Issue by stevenlumina** [microsoft/playwright#18956]
I am trying to reuse a [sign in using this guide](https://playwright.dev/docs/auth#reuse-signed-in-state).  While it does sign in it isn't saving the information into the correct URL.
For context the steps are:

1. Go to app url which redirects to the SSO
2. log into the SSO saves some into to local storage
3. Go back to the app URL and it saves the same into to local storage but under the app URL

The part I am having an issue with is step 3.  I set up ```global-setup-ts``` to go back to the app url but it does not record the local storage details, but it does for the SSO page.

I can run ```npx playwright codegen --save-storage=auth.json``` and go through the exact same steps but this time it does record the local storage under the app URL.  For now while I experiment with playwright I can get away with this I want to fully automate it into my CI/CD pipeline.  

My ```global-setup.ts``` file looks like this:
```javascript
async function globalSetup(config: FullConfig) {
    const browser = await chromium.launch();
    const page = await browser.newPage();

    await page.goto('http://localhost:5000/');
    await page.getByPlaceholder('Username or Email Address').click();
    await page
        .getByPlaceholder('Username or Email Address')
        .fill('my username');
    await page.getByRole('button', { name: 'Next' }).click();
    await page.getByPlaceholder('Password').click();
    await page.getByPlaceholder('Password').fill('somepassword);
    await page.getByRole('button', { name: 'Sign In' }).click();
    await page.goto('http://localhost:5000');
    await page.waitForLoadState('networkidle');
    await page.context().storageState({ path: 'storageState.json' });
    await browser.close();
}

export default globalSetup;
```

**Comment by dgozman** [comment]
@stevenlumina On the first glance, you are doing everything right, and it should work. Could you share a repro, or at least a page url, so that we can debug locally?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
