### ISSUE TITLE
[Question] Workers config option for a project

### ISSUE THREAD

**Issue by suneetfcc** [microsoft/playwright#18950]
My playwright config looks like 
```javascript
const config = {
projects: [
        {
            name: 'Project1,
            testMatch: '**/project1/**',
            workers: 1
        },
        {
            name: 'Project2',
            testMatch: '**/project2/**'
        }
    ]
}
```

when i run  `npx playwright  test --project=Project1  `
`Running 18 tests using 3 workers`
the project is parallelised with 3 workers and my worker config is not honoured. 

Basically i am trying to disable parallelization for one project

**Comment by viraxslot** [comment]
Hi @suneetfcc As far as I know there is no such option like `workers` for a project. Please see here: https://playwright.dev/docs/api/class-testproject

I think a workaround could be:
```
const config = {
  workers: process.env.ONE_WORKER ? 1 : 3,
  projects: [
          {
              name: 'Project1,
              testMatch: '**/project1/**',
              workers: 1
          },
          {
              name: 'Project2',
              testMatch: '**/project2/**'
          }
      ]
  }
```

It's like [in this code snippet](https://playwright.dev/docs/test-configuration#testing-options) (please see to the very bottom of the page), but with the different environment variable.

So you can run your tests like
`ONE_WORKER=1 npx playwright test --project=Project1` (will work for macOS for sure)

And with no such environment variable for other projects.
Of course environment variable can have an another name.

For Windows you need to set environment variable like `set ONE_WORKER=1` before the run.
Hope it will help.

**Comment by dgozman** [comment]
@suneetfcc There is no such feature as of today - you can only specify `workers` for the whole config. Let's consider this issue a feature request.

**Comment by suneetfcc** [comment]
> @suneetfcc There is no such feature as of today - you can only specify `workers` for the whole config. Let's consider this issue a feature request.

thank you so much i think this is a pretty desirable feature.

**Comment by nulladdict** [comment]
I would also love to see this feature. Here's some context for my use case.
Most of my tests can be run fully parallel, but there's a number of test suites that puts load on a shared resource.

Currently we have all this tests in a single file, effectively disabling concurrency.
Ideally, we would put them in a separate project and run those projects sequentially to mitigate side-effects on other tests.

We can also just run tests twice, but then handling results and artifacts is a bit tricky.

**Comment by HendrikJan** [comment]
I would actually like such a feature per spec-file:
```javascript
test.describe.configure({ workers: 1 });
```

**Comment by marcusNumminen** [comment]
I would also like to have this. In my case I work in a project were we do both api and UI tests. I have divided up this into two projects, one api-test and one ui-test project. Since I don't use the browser at all in the api-test project I can run that project with a larger amount of workers than the UI tests.

**Comment by xiaojieyang** [comment]
I would like to have this feature as well, under big project this can be quite useful.

**Comment by denkorz** [comment]
This feature looks really useful, it would really help for flexible management of test runs. Looking forward for new version with this feature implemented!

**Comment by inriverisac** [comment]
Looks like a great feature. I would also like this implemented!

**Comment by marcusNumminen** [comment]
@dgozman and @aslushnikov is there any plans for adding workers option to the projects? This would have been a very nice option.

**Comment by GlacialBoy** [comment]
We'd like also to have this feature implemented so we can tune the parallization grade on different projects. Great job with Playwright!

**Comment by alexisadorn** [comment]
This would be a helpful feature for us as well, especially if it could be determined at the spec file level

**Comment by AndiBMGitHub** [comment]
Would be great to have this implemented!

**Comment by giorgoslytos** [comment]
This is a feature that would benefit us a lot!
Especially this one
`test.describe.configure({ workers: 1 })`

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/21970
