### ISSUE TITLE
[FEATURE REQUEST] Allow setting up env variables inside VSCode extensions

### ISSUE THREAD

**Issue by tymfear** [microsoft/playwright#18957]
Our setup is done in a way that we need to pass env vars to run against different environments.
Currently I haven't found any clues on how to do that.
But anyway, even if there is a hack to work around it, imo, it would be much user-friendlier to allow setting it up in extension.

**Comment by mxschmitt** [comment]
You can already do this as of today by setting the `playwright.env` setting inside the VSCode settings.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
