### ISSUE TITLE
[BUG] Test timeout exceeded while setting up "page". webkit

### ISSUE THREAD

**Issue by Nilamber01** [microsoft/playwright#18953]
**Context:**
- Playwright Version: 1.28
- Operating System: Mac OS X 10_15_7
- Node.js version: 18.10.0
- Browser: WebKit
- Extra: Works fine locally, but doesn't work on CI env (mac agent with above config). Chromium and firefox runs fine though.

**Code Snippet**

```javascript
test('netverify client upload test', async ({page})=>
{
    await page.goto(endpoint);
    await page.waitForLoadState();
    const startVerification = new NetverifyStartVerification(page);
    await startVerification.clickStartVerification();
    await startVerification.selectCountry("USA");
    await startVerification.selectPassport();
});
```

**Describe the bug**

browserContext.newPage: Browser closed.
14:28:06      ==================== Browser output: ====================
14:28:06      <launching> /Users/ec2-user/Library/Caches/ms-playwright/webkit-1735/pw_run.sh --inspector-pipe --headless --no-startup-window
14:28:06      <launched> pid=75496
14:28:06      [pid=75496][err] 2022-11-21 08:56:37.047 Playwright[75501:18087878] +[NSXPCSharedListener endpointForReply:withListenerName:]: an error occurred while attempting to obtain endpoint for listener 'ClientCallsAuxiliary': Connection interrupted

**Comment by dgozman** [comment]
@Nilamber01 Playwright does not support macOS 10.15 since version v1.26. See [release notes](https://github.com/microsoft/playwright/releases/tag/v1.25.0).

I wonder how did you end up with `webkit-1735`. Did you do anything specific to download it? Did you run `npx playwright install`? If so, could you please run `DEBUG=pw:install npx playwright install` and post logs here?

**Comment by Nilamber01** [comment]
Thanks for pointing. I took some hint from your comment and updated the mac agent on AWS with latest version
Playwright Version: 1.28.0
Operating System: Mac OS X 13
Node.js version: v18.12.1
Browser: WebKit

Here is the debug log. I have a similar error but atleast NSXPCSharedListener error is gone.

pw:channel:response {
  pw:channel:response   id: 9,
  pw:channel:response   error: {
  pw:channel:response     error: {
  pw:channel:response       message: 'Browser closed.\n' +
  pw:channel:response         '==================== Browser output: ====================\n' +
  pw:channel:response         '<launching> /Users/ec2-user/pw-browsers/webkit-1735/pw_run.sh --inspector-pipe --headless --no-startup-window\n' +
  pw:channel:response         '<launched> pid=37486\n' +
  pw:channel:response         '[pid=37486] <gracefully close start>',
  pw:channel:response       stack: 'Error: Browser closed.\n' +
  pw:channel:response         '==================== Browser output: ====================\n' +
  pw:channel:response         '<launching> /Users/ec2-user/pw-browsers/webkit-1735/pw_run.sh --inspector-pipe --headless --no-startup-window\n' +
  pw:channel:response         '<launched> pid=37486\n' +
  pw:channel:response         '[pid=37486] <gracefully close start>\n' +
  pw:channel:response         '    at /Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/webkit/wkConnection.js:140:16\n' +
  pw:channel:response         '    at new Promise (<anonymous>)\n' +
  pw:channel:response         '    at WKSession.send (/Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/webkit/wkConnection.js:136:12)\n' +
  pw:channel:response         '    at WKBrowserContext.newPageDelegate (/Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/webkit/wkBrowser.js:207:45)\n' +
  pw:channel:response         '    at WKBrowserContext.newPage (/Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/browserContext.js:345:37)\n' +
  pw:channel:response         '    at BrowserContextDispatcher.newPage (/Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/dispatchers/browserContextDispatcher.js:182:75)\n' +
  pw:channel:response         '    at DispatcherConnection.dispatch (/Users/ec2-user/web-test-playground/node_modules/playwright-core/lib/server/dispatchers/dispatcher.js:317:46)',
  pw:channel:response       name: 'Error'
  pw:channel:response     }
  pw:channel:response   }
  pw:channel:response } +11ms

**Comment by dgozman** [comment]
@Nilamber01 There's probably an issue with your environment/setup, but these logs are not enough. Try running with `DEBUG=pw:browser` to see whether browser complains about anything. If not, I am not really sure how to help.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
