### ISSUE TITLE
[Question] How can I set a value to a password input inside a closed shadow root.

### ISSUE THREAD

**Issue by zac11** [microsoft/playwright#18952]
So from [this](https://playwright.dev/docs/selectors#selecting-elements-in-shadow-dom) documentation , it is clear to me that Playwright cannot natively access elements inside closed shadow root. However I'm just trying to see if I can get a workaround. 

[This](https://selectorshub.com/xpath-practice-page/) is the application under test - an I'm trying to access the `Password` field inside the closed shadow root. I am successfully able to get to the element using this
```
await page.locator('div#userPass').click();
await page.keyboard.press('Tab'); 
```
Also, I'm able to set the value for the password field attribute using 

` await page.evaluate(() => document.activeElement.setAttribute('value','Top Gun Maverick'));`

However, the value doesn't show on the UI and the input field remains blank. I checked and the value attribute is getting correctly set

```
let textcontent = await page.evaluate(()=> document.activeElement.getAttribute('value'));
 await console.log(`The value set is ${textcontent}`);
```

returns ` The value set is Top Gun Maverick`. However the UI remains same...nothing appears.  This also appears to another element which is inside another closed shadow root - value gets set but never appears on UI - and that input is not of password type. 

Can someone let me know if this is possible or not? It's not a deal breaker, just trying to play around with Playwright's capabilities

**Comment by dgozman** [comment]
@zac11 I can see two possible solutions:

1. Type on the keyboard after you've focused the input.
```ts
await page.locator('div#userPass').click();
await page.keyboard.press('Tab'); 
await page.keyboard.type('the secret password'); 
```

2. Instead of setting an attribute, assign to the `value` property:
```ts
await page.locator('div#userPass').click();
await page.keyboard.press('Tab'); 
await page.evaluate(() => document.activeElement.value = 'Top Gun Maverick');
```

Let me know if this helps.

**Comment by zac11** [comment]
Thanks @dgozman . The first one works and does the job. Not sure why I didn't use this method tbh. The second doesn't and has the same impact as the one's I've tried.

**Comment by zac11** [comment]
Also tried 
`await page.evaluate(() => document.activeElement.nodeValue = 'Top Gun Maverick');` but has the same effect. Nevertheless you can mark this as closed.
