### ISSUE TITLE
[BUG] Debug mode doesn't highlight elements on the page

### ISSUE THREAD

**Issue by viraxslot** [microsoft/playwright#18959]
**Context:**
- Playwright Version: 1.28.0
- Operating System: macOS 12.3
- Node.js version: 16.15.1
- Browser: Chromium

**Code Snippet**
Any code, related to UI automation.

**Describe the bug**
1. Run test case in debug mode `PWDEBUG=1 yarn pw:run --project=chromium`
2. Step over to the step that operates with UI element
3. Check the element is highlighted on the page.

In playwright 1.27.1: we can see the exact element that used in the test step:
![image](https://user-images.githubusercontent.com/20737672/203068033-c5491d8c-4279-486a-9cc4-51dcdab410d2.png)

In playwright 1.28.0: no highlighting on the same test step.

Why this behavior is expected: it's a good way to verify that selector was chosen correctly.

**Workaround**: I can click "explore", but clicking it on each test step is a bit annoying.

**Comment by dgozman** [comment]
@viraxslot I am running our example test (see below) with `PWDEBUG=1 npx playwright test --project=chromium`, and pausing at `await getStarted.click()` highlights the element.

<img width="408" alt="Screen Shot 2022-11-21 at 4 06 08 PM" src="https://user-images.githubusercontent.com/9881434/203182801-fe7e3ff1-8385-46cc-94ca-265d5c9f0d24.png">


```ts
test('homepage has Playwright in title and get started link linking to the intro page', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);

  // create a locator
  const getStarted = page.getByRole('link', { name: 'Get started' });

  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro');

  // Click the get started link.
  await getStarted.click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

Could you please share a repro that we can run locally?

**Comment by dgozman** [comment]
@viraxslot Thank you, I can reproduce.
