### ISSUE TITLE
[Feature]ability to select an option value by title

### ISSUE THREAD

**Issue by macroking** [microsoft/playwright#18958]
`locator.selectOption` supports label, value, and index. I think those who are using Playwright to automate Oracle Cloud application will be benefited if we support selecting an option by `title` also.

```html
<select>
<option value="0" title="USD - US Dollar">USD - US Dollar</option>
</select>
```

**Comment by dgozman** [comment]
@macroking In this example, does selecting by `label` work? It is the same as title here.

**Comment by macroking** [comment]
@dgozman No, it is not working. The way I have it automated is using elementhandle.

**Comment by dgozman** [comment]
@macroking The following snippet works for me. If you run it in headed mode, you'll see how "Other" is selected by default, but then it switched to "USD - US Dollar". No need to use element handles.

```ts
await page.setContent(`
  <select>
    <option value="0" title="USD - US Dollar">USD - US Dollar</option>
    <option value="1" title="Something else" selected>Other</option>
  </select>
`);
await page.waitForTimeout(3000);
await page.locator('select').selectOption({ label: 'USD - US Dollar' });
```

**Comment by macroking** [comment]
@dgozman Thanks this is working as expected.
