### ISSUE TITLE
[BUG] Reports generating playwright screenshot is outside the Vitest testing context

### ISSUE THREAD

**Issue by zheeeng** [microsoft/playwright#18963]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: v16.18.1
- Browser: All
- Extra: Vitest runtime

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```ts
import { afterAll, beforeAll, describe, test } from 'vitest';
import { preview } from 'vite';
import type { PreviewServer } from 'vite';
import { chromium } from 'playwright';
import type { Browser, Page } from 'playwright';
import { expect } from '@playwright/test';

describe('basic', async () => {
  let server: PreviewServer;
  let browser: Browser;
  let page: Page;

  beforeAll(async () => {
    server = await preview({ preview: { port: 3000 } });
    browser = await chromium.launch();
    page = await browser.newPage();
  });

  afterAll(async () => {
    await browser.close();
    await new Promise<void>((resolve, reject) => {
      server.httpServer.close(error => error ? reject(error) : resolve());
    });
  });

  test('should match the startup snapshot', async () => {
    await page.goto('https://vitest.dev/');
    await expect(page).toHaveScreenshot('vitest.png');
  }, 10_000);
});
```

**Describe the bug**

Console reports Error: toHaveScreenshot() must be called during the test.

See more details [here](https://github.com/vitest-dev/vitest/discussions/2340)

**Comment by dgozman** [comment]
@zheeeng  Snapshots require tight integration with the test runner, so they are not available when not using @playwright/test. Since you are using `vitest`, you should look for a similar capability there. Let me know if you have more questions.

See also #15800.

**Comment by zheeeng** [comment]
Is there any guide for looking for the capability?

**Comment by jfgreffier** [comment]
Is there any other assertions that require Playwright Test ? It's probably better to list it as a limitation of these methods in the documentation.

**Comment by dgozman** [comment]
> Is there any guide for looking for the capability?

You better ask this question on `vitest` forum.

> Is there any other assertions that require Playwright Test ? It's probably better to list it as a limitation of these methods in the documentation.

I think `toMatchSnapshot()`, `toHaveScreenshot()` and `expect.soft` are the only ones today.
