### ISSUE TITLE
[Question] page.setExtraHTTPHeaders also affect 'request' ?

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#18962]
Hello, I have two questions:
1. What is the difference between page.setExtraHTTPHeaders and testOptions.extraHTTPHeaders?
2. Does page.setExtraHTTPHeaders also affect the 'request' API ?
Thanks!

**Comment by dgozman** [comment]
@ValorHeart 

> What is the difference between page.setExtraHTTPHeaders and testOptions.extraHTTPHeaders?

`TestOptions.extraHTTPHeaders` is just an easy way to set headers in the config. Under the hood it sets `extraHTTPHeaders` option for the [`browser.newContext()`](https://playwright.dev/docs/api/class-browser#browser-new-context) call and affects all pages created in this context.

`page.setExtraHTTPHeaders()` only affects a single page.

> Does page.setExtraHTTPHeaders also affect the 'request' API ?

I assume you are talking about `page.request.get()` and friends. If so, `page.setExtraHTTPHeaders()` does not affect it, but `context.setExtraHTTPHeaders()` and `TestOptions.extraHTTPHeaders` do.

**Comment by ValorHeart** [comment]
Thanks a lot @dgozman
