### ISSUE TITLE
[Question] Codegen related queries

### ISSUE THREAD

**Issue by kedarsprabhu** [microsoft/playwright#18977]
Things not captured in Codegen recording:: =============================== 
1.>Waiting time or sleep loading time is not captured
 2.>Switch between windows tab is not captured in the code (in multiple windows) 
3.>It is not using locators, instead it is using the url links for navigations most of the time. 
 4.>If we are to assert any text, then we will have to add it manually isn't it? 
5.>Can we have multiple test blocks inside a single describe block? 
6.> Frame to frame switch and popup to popup is not captured.

**Comment by dgozman** [comment]
@kedarsprabhu Could you please explain in more details what are you talking about? I understand some of items, but not all.

> Waiting time or sleep loading time is not captured

What is this "waiting time" or "sleep loading time"?

> Switch between windows tab is not captured in the code (in multiple windows)

Playwright does not need to "switch" between tabs, it just works with multiple tabs right away.

> It is not using locators, instead it is using the url links for navigations most of the time.

Could you be more detailed here please? Codegen definitely generates locators for input actions, so perhaps you are talking about something else?

> If we are to assert any text, then we will have to add it manually isn't it?

This is correct. See #14913.

> Can we have multiple test blocks inside a single describe block?

So far, codegen only generates a single test. You are free to format/split it into multiple tests/describes as you see fit.

> Frame to frame switch and popup to popup is not captured.

Again, Playwright does not have a concept of "frame switch". Could you be more detailed please?

**Comment by kedarsprabhu** [comment]
1. In waiting time, await page.waitForTimeout(); is it captured?
2. Just it was generating URL along with locators but I suppose since the functionality is met that shouldn't be an issue.
3.If I were to click on a "open in a new window" in a frame and it opens in another window, and I've to go back to mainframe, will codegen do it?

**Comment by dgozman** [comment]
> 1. In waiting time, await page.waitForTimeout(); is it captured?

You mean if you waited between performing actions? This does not produce `waitForTimeout()`. Overall, Playwrights works without `waitForTimeout()` in almost all cases due to built-in auto-waiting, and we recommend other explicit waits like `waitForResponse()` if you really need them.

>    3.If I were to click on a "open in a new window" in a frame and it opens in another window, and I've to go back to mainframe, will codegen do it?

Codegen does not "go back to it", but it will generate correct code that operates on the window you are interacting with.

**Comment by kedarsprabhu** [comment]
Thanks for the responses! With few manual manipulations Codegen would work fine.
