### ISSUE TITLE
pass a proxy to page.evaluate()

### ISSUE THREAD

**Issue by FishBlanche** [microsoft/playwright#18985]
i am trying to pass a proxy to page.evaluate like following:
const newFun = new Proxy(func,{
  apply: function(target, thisArg, argumentsList) {
    console.log('called: ' + argumentsList);
// to do something
    return target(argumentsList);
  }
});
   const   result = await this.page.evaluate(newFun,args);

But got the error:  page.evaluate: Passed function is not well-serializable!page.evaluate: Passed function is not well-serializable!

**Comment by dgozman** [comment]
@FishBlanche This is not supported. I'd suggest to create a proxy inside your evaluate:

```js
const result = await this.page.evaluate(args => {

const newFun = new Proxy(func, {
    apply: function(target, thisArg, argumentsList) {
      console.log('called: ' + argumentsList);
      // to do something
      return target(argumentsList);
    }
  });
  return func(args);
}, args);
```

I'd recommend reading [this guide](https://playwright.dev/docs/evaluating) that explains how node.js environment and page environment are different. Let me know if that helps.

**Comment by FishBlanche** [comment]
> 
 public async evaluate(consoleApi: types.EvaluateFn,...args: any) {
      const result = await this.page.evaluate(args1 => {
         const newFun = new Proxy(consoleApi, {
            apply: function(target, thisArg, argumentsList) {
              console.log('called: ' + argumentsList);
              // to do something
              return target(argumentsList);
            }
          });
          return newFun(args1);
        }, args);
      console.log('evaluate val..',result);
      return result;
    }

when i try to invoke this function:    
evaluate(async (e,attr) => await e.getAttribute(attr),  e,"title");
,got the following errors:
![error](https://user-images.githubusercontent.com/19261291/203492731-2e5f431d-f797-4b94-a234-6b0046b82b30.png)

the reason i want to use proxy is that we use puppeteer before,but  in playwright
should change to this :  evaluate(async ([e,attr]) => await e.getAttribute(attr),  e,"title"); //users miss [ ] in their code
we don't want the users to change their code,so try to use proxy to achieve that.

**Comment by dgozman** [comment]
Here is a rough sketch, try adapting it to your usecase.

```ts
public async evaluate(consoleApi: types.EvaluateFn,...args: any) {
  // Pass function's string representation along with arguments and
  // reconstruct it in the page.
  return await page.evaluate(([fnString, args]) => {
     const fn = new Function(fnString);
     new Proxy(fn, { ... });
  }, [String(consoleApi), args]);
```

**Comment by FishBlanche** [comment]
> Here is a rough sketch, try adapting it to your usecase.
> 
> ```ts
> public async evaluate(consoleApi: types.EvaluateFn,...args: any) {
>   // Pass function's string representation along with arguments and
>   // reconstruct it in the page.
>   return await page.evaluate(([fnString, args]) => {
>      const fn = new Function(fnString);
>      new Proxy(fn, { ... });
>   }, [String(consoleApi), args]);
> ```
 This 'const fn = new Function(fnString);'  does not work.
I made a test as following:
 let tmp1 = await testtest(async (a,b) => {return a+b;},   1,2);

async function testtest(func,...args){
    const a = await func(...args);
    console.log('a...',a);
    const fnString = String(func);
    const fn1 = new Function(fnString);
    const b = fn1(...args);
    console.log('b...',b);
    return a;
}
b is undefined..

**Comment by dgozman** [comment]
This depends on your usecase, I cannot provide fully-working source for you. Here is a [code pointer](https://github.com/microsoft/playwright/blob/2887a2a883292415fab403b4ea9b6b075c121ca5/packages/playwright-core/src/server/javascript.ts#L290) for function normalization, if that helps you.

The following example works for me in Node:

```ts
const fn = async (a,b) => {return a+b;};
const fnString = String(fn);
// ...
const newFn = new Function('return ' + fnString)();
console.log(await newFn(5, 2));  // 7
```

**Comment by dgozman** [comment]
Closing as per above.
