### ISSUE TITLE
[BUG] record at cursor when in record new

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#18987]
**Context:**
- Playwright Version: 1.28
- Operating System: mac
- Node.js version: [e.g. 12.22, 14.6]
- Visual Studio Code version: [e.g. 1.65]
- Playwright for VSCode extension version: latest
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

Click record new
- record a few things
- delete something
- click record at cursor

**Describe the bug**

as the button record at cursor is activated I click it cause that is what I want to do but actually it doesn't work like that. I have to stop the recording for the record at cursor button to work upon clicking it. 

Of course it does record at cursor when just moving the cursor and continuing recording so problem only arrises when you actually click the record from cursor button while in record new mode.

**Comment by pavelfeldman** [comment]
Could you link the steps I should perform along with your expectations and the actual result?

**Comment by pavelfeldman** [comment]
Got it, I fixed clicking record from here while already recording.
