### ISSUE TITLE
[Question] How to chain GetByRole to return table cells in row groups / AriaRole.Row & AriaRole.Cell usage

### ISSUE THREAD

**Issue by gotmike** [microsoft/playwright#18991]
i'm trying to get a list of rows and then iterate through that list to get the cells in each row of a table...

the `.GetByRole` locator appears to work for `.AriaRole.Row`, but when i try using `.AriaRole.Cell` i don't get any results...

```
var htmlRow = htmlTableLocator.GetByRole(AriaRole.Row);
var htmlRowCount = await htmlRow.CountAsync(); // returns 264 rows (correctly)

var htmlRowCells = htmlRow.Nth(i + 1).GetByRole(AriaRole.Cell);
var htmlCellCount = await htmlRowCells.CountAsync(); // returns 0 cells (expect 17 cells)

var htmlRowCellsText = await htmlRow.Nth(i + 1).AllInnerTextsAsync();
var htmlRowCellsTextList = htmlRowCellsText.FirstOrDefault().Split("\t"); // returns 17 cells

var htmlAllCells = htmlTableLocator.GetByRole(AriaRole.Cell);
var htmlAllCellsCount = await htmlAllCells.CountAsync(); // returns 0 cells (expect 264 x 17 = 4,488 cells)

var pageAllCells = page.GetByRole(AriaRole.Cell);
var pageAllCellsCount = await pageAllCells.CountAsync(); // returns 0 cells (expect 264 x 17 = 4,488 cells)
```

is this the wrong way to use `.AriaRole.Cell`?

**Comment by gotmike** [comment]
based on this page...
https://www.w3.org/TR/wai-aria-1.2/#cell

seems like cell is intended to indicate `<td>`

**Comment by gotmike** [comment]
is there something about angular pages that would block this sort of locator?

i seem to be able to select based of `.Locator("tblAdSchedule")` but can't get like `.GetByRole(AriaRole.Table)`

**Comment by gotmike** [comment]
another example...

this does NOT work...
`var table = page.GetByRole(AriaRole.Table);`

this DOES work...
`var table = page.Locator("#top > div.panel-body > div.table-responsive > table");`

table tag looks like this...

**Comment by gotmike** [comment]
also, strangely...

this does NOT work...
`var cells = table.GetByRole(AriaRole.Cell);`

but this DOES work...
`var cells = table.Locator("td");`

shouldn't these produce the same result?

**Comment by dgozman** [comment]
@gotmike I think there might be an explicit `role` attribute that overrides the default one. For example, notice the `role="grid"` in your snippet - `AriaRole.Grid` should work in this case:

```html
<table navigatable="tblAdSchedule" role="grid" class="tblAdSchedule table table-bordered ng-scope" aria-labelledby="tblAdSchedule" ng-if="allAdPublishingCtrl.AdList">
```

However, I recommend using [CodeGen](https://playwright.dev/dotnet/docs/codegen-intro) to generate locators and then tweak them if you'd like. Let me know if that helps.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
