### ISSUE TITLE
[Question] Locator seems to hang when selector doesn't exist, is this by design?

### ISSUE THREAD

**Issue by gotmike** [microsoft/playwright#18994]
i'm using `Page.Locator("#elementId")` and i find if no element exists with `#elementId` then i get timeout errors.

is this by design? is there some way to test for existence first? maybe a best practice here?

i suppose i could grab the entire page content and look for it just with full-text searching but seems more reasonable it would simply return a `null` value if not found.

**Comment by dgozman** [comment]
@gotmike `Locator` by itself does not hang, but an action performed on this locator might hang. For example, if you click a locator, it [will auto-wait](https://playwright.dev/dotnet/docs/locators) for the element to appear.

If you want to check whether something is visible on the page at a particular moment, you can use:
- [`Expect(locator).ToBeVisibleAsync()`](https://playwright.dev/dotnet/docs/test-assertions#locator-assertions-to-be-visible)
- [`Locator.IsVisibleAsync()`](https://playwright.dev/dotnet/docs/api/class-locator#locator-is-visible)

Let me know if this helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by gotmike** [comment]
yessir, that does work. the documentation is not clear about using in this way or stating to check first with `.IsVisibleAsync()`

is documentation on github to propose edits?
