### ISSUE TITLE
[BUG] Weird Chromium headless issues.....

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19000]
1. Can't click on a specific button Works on Firefox Headless

On Chromium headless the app throws "Write permission denied"
I tried changing the user-agent, still fails. It only fails for this specific element only.... it's not passing in headless in the UA....
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

2. Grabbing a screenshot element again only a specific element, always shows 2 pixel difference same exact docker env.. image..

99% of the tests pass it's just these weird 1 off issues....

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
