### ISSUE TITLE
"expected string, got undefined" error while passing Key from a text file stored in framework.

### ISSUE THREAD

**Issue by biswasritu6** [microsoft/playwright#19009]
#@ I have a text file stored in my framework. eg:Companyname .(as u can see in screenshot 1.)
1. I wanted to pass the value Companyname( the dream company) from that text file into my test script line no 109(as u can see in screenshot 2.). but I am getting the expected string, got undefined" error.
2. in line no 2 I am declaring the text file location and storing it in a variable i.e CompanyDetails, and in line no 109 I am passing the key( Companyname).
attaching the screenshot of my code and text file.

![Screenshot1 (1)](https://user-images.githubusercontent.com/86822634/203484592-0bc6636f-94d6-4325-8aa0-d0adc2c7db25.png)

![Screenshot2 (2)](https://user-images.githubusercontent.com/86822634/203486007-d0199a0b-0db5-4a48-a651-8b9643292082.png)

Error-------
![Screenshot3 (3)](https://user-images.githubusercontent.com/86822634/203486044-635083f6-d543-43e8-8315-3566aa226695.png)

RawCode---------------
const { expect } = require('../playwright.config');
const CompanyDetails = ((require("../utils/Companyname.txt")));
  async addnewSupplier_Activities() {

        await this.addnew_supplier.click();
        await this.direct_supplier.click();
        await this.Activity_service.click();
        await this.type_city_name.fill('New delhi');
        await this.select_NewDelhi.click();
        await this.suppliername_search_bar.click();
        await this.company_name.type(CompanyDetails.Companyname);
        await this.create_new_supplier.click();
        await this.save_continue.click();

**Comment by biswasritu6** [comment]
here is my code 

const { test, expect } = require('@playwright/test');
const { POManager } = require('../pageobjects/POManager');
const { timeout } = require('../playwright.config');
const supplierDataset3 = ((require("../utils/SupplierloginTestData3.txt")));
//const supplierDataset = JSON.parse(JSON.stringify(require("../utils/SupplierloginTestData.json")));
const { loggers } = require('winston');
const winston = require('winston');
const logger = winston.createLogger();


test.describe('Activities supplier module', () => {

test('Create Activities supplier', async ({ page }) => {

    const poManager = new POManager(page);
    const loginPage = poManager.getLoginPage();
    const supplier_create_Activities = poManager.getsupplier_create_Activities();
    await loginPage.costingUrl();
    await loginPage.validLogin(supplierDataset3.costingusername, supplierDataset3.costingpassword);

**Comment by biswasritu6** [comment]
const { expect } = require('../playwright.config');
const CompanyDetails = ((require("../utils/Companyname.txt")));
//const CompanyDetails2 = JSON.parse(JSON.stringify(require("../utils/Companyname.txt")));

Line 3 also not working.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by tiyiselani** [comment]
I have the same issue too tried with the Json aboce nothing worked
