### ISSUE TITLE
[Question] How to limit the number of running tests running at the same time?

### ISSUE THREAD

**Issue by Mathiaszero** [microsoft/playwright#19008]
I plan to do load testing on my server, but don't know how to limit the number of headless browsers run at a time.  Anyone to guide me in the right direction would be appreciated.  I looked at process ID but can't seem to see those in the process monitor on Linux, as I was planning to detect if the names on the process list and take a head count every second.  I am thinking about maxing out to 5 concurrent tests.

**Comment by dgozman** [comment]
@Mathiaszero Take a look at the [parallelization guide](https://playwright.dev/docs/test-parallel#limit-workers). Let me know if this helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
