### ISSUE TITLE
[Question] How to use expect.poll if the locator is not yet visible on the page?

### ISSUE THREAD

**Issue by gineanne** [microsoft/playwright#19007]
I can't figure out how to poll when there is an error encountered inside the expect.poll. My goal is to wait for the locator to be displayed in the page. I need to reload the page to display the new record. I'm creating a record via api  but the problem is I need to wait for a couple of seconds to display the new record in the page. 

![image](https://user-images.githubusercontent.com/21330975/203467979-83e200ad-3ba3-41eb-84b5-af0adaf2e532.png)

**Comment by gineanne** [comment]
Update: I managed to make it work. I put a try catch then return the actual value for comparison. 

![image](https://user-images.githubusercontent.com/21330975/203488006-1ac3c0d3-b530-4c4a-b9ab-cace7f5ec148.png)

Is this the right way or do you have any suggestions?

**Comment by dgozman** [comment]
@gineanne Your snippet looks good. Since, I assume, you have to call `page.reload()` to get it visible, something like this is the easiest solution.
