### ISSUE TITLE
[Feature] Code-coverage between functions and test cases

### ISSUE THREAD

**Issue by necdetterkes** [microsoft/playwright#19015]
We are creating some functions. For example I created this function to make api call. 

`async getRequests (): Promise<any> {
    try {
      const _response = await this.request.get(
          `${apiUrl}`,
          {
            headers: {
              Accept: 'application/json',
              Authorization: userApiKey
            }
          }
      )
      // Assertions
      expect(_response.status()).toBe(200)
      expect(_response.ok()).toBeTruthy()
      // Check response parameters
      const res = await _response.json()
      expect(res).toHaveProperty('data')
      console.log('Requests fetched successfully')
    } catch (error) {
      console.log(error)
      throw new Error(error)
    }
  }`
  
  
  And after that I'm using this function as a test step.
  
  But I want to calculate code coverage for these functions. I want to know which test functions are used during the tests.

**Comment by dgozman** [comment]
Merging into #9208.
