### ISSUE TITLE
[Question] Checking window's attributes

### ISSUE THREAD

**Issue by ISilviu** [microsoft/playwright#19011]
Hi, is there any way one could check any attribute of the window object?
For example, I'd like to create a test where I'd check the window's `scrollY` attribute.

Thank you!

**Comment by dgozman** [comment]
@ISilviu Take a look at the [evaluation guide](https://playwright.dev/docs/evaluating). Here is an example:

```ts
test('my test', async ({ page }) => {
  // ...
  const scrollY = await page.evaluate(() => window.scrollY);
  // ...
});
```

Let me know if this helps.

**Comment by ISilviu** [comment]
@dgozman thank you kindly. 
Yes, it does exactly what I needed.

Fun fact, I was having the same concept in mind, except that I was implementing it in a "React" manner :laughing: :

```js
let scrollY = 0;

await page.evaluate(() => {
    scrollY = window.scrollY;
});

expect(scrollY).toBe(0);
```
