### ISSUE TITLE
[BUG] Document needs to be modified regarding locator.fill Maximum timeout 30 seconds will be overridden by actionTimeout of 0.

### ISSUE THREAD

**Issue by loxinchi** [microsoft/playwright#19018]
**Describe the bug**

Per the document [locator.fill(value[, options])](https://playwright.dev/docs/api/class-locator#locator-fill)
`Maximum time in milliseconds defaults to 30 seconds`
But if I don’t set action timeout such as `config = { use: { actionTimeout: 10000 } }` or `locator.fill({ timeout: 10000 }))`,
This default timeout `30 seconds` doesn’t seem to be applied.
The error throws until the configured **Test timeout** instead of `30 seconds`.

Thanks to @mxschmitt for clarification: 
`Playwright Test has an actionTimeout of 0, which reflects in the Playwright API to setDefaultTimeout(0) which overrides the default timeouts. I agree that this is confusing, feel free to file an issue then we adjust the docs accordingly.`

Therefore, create this issue for requesting the documentation modification to avoid confusion.

**Comment by aslushnikov** [comment]
For the record: we tried using inline templates in our documentation to enhance documentation. See https://github.com/aslushnikov/playwright/commit/d125e8b9d2e17481b59775b569422be234da7399

However, we do not support per-language inline templates as of today, so this is postponed for now. @dgozman has a refactoring in mind that should allow per-language inline templates are reality; so we postpone this for a while.
