### ISSUE TITLE
[Question] How to keep the test result history with the HTML reporter

### ISSUE THREAD

**Issue by daganilsen** [microsoft/playwright#19010]
Hi. I am new to Playwright and it is absolute amazing to work with.
My question is about the HTML reporter (or any of the reporters). It is working fine but it overwrites the results for each test run. Is it possible to add something in the config file so that the test result history is preserved?
It would be nice to see a sub folder within the test-results for each test run.

I hope that this is possible.

Regards,
Dag

**Comment by dgozman** [comment]
@daganilsen This is not supported out of the box. However, you can work around it by providing custom `outputFolder`:

```ts
// playwright.config.ts

// Generate unique output folder.
const currentDateTime = new Date().toISOString().replace(/[:.]/g, "_").slice(0, -1);
const outputFolder = `./results/results-${currentDateTime}`;

export default {
  // Change your "reporter" line in the config like this:
  reporter: [["html", { outputFolder } ]],
};
```

Let me know if this helps.

**Comment by daganilsen** [comment]
Hi Dmitry. Thanks for your answer.
I have actually found a similar solution. Inside the config I have added

`const config: PlaywrightTestConfig = {
....
globalTeardown: './src/copyResults.ts',
`

I have my copy code inside copyResults.ts. So when the testing session is done it will copy the results
Thanks!

**Comment by ortoniKC** [comment]
You can try Ortoni Report, it stores the test history. 
https://www.npmjs.com/package/ortoni-report
