### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by mecies** [microsoft/playwright#19023]
Hey, I am migrating tests from Cypress to Playwright and we had a couple of tests that were testing some elements on the SSR. Is it possible to achieve an equivalent behavior to the Cypress one from [this article](https://glebbahmutov.com/blog/ssr-e2e/#ssr-application)?

With Cypress, we were able to use selectors on the `$html` from the response, I'm not sure if that's doable with Playwright.
I tried both:
- `const response = await page.goto()` / ` const response = await request.get()`

Then to apply the `response.text()` I can see the server-side HTML as a string but I cannot use any selectors on it.
I would appreciate any advice on how to test SSR HTML, thank you.

**Comment by ambiguous48** [comment]
You can [turn off](https://playwright.dev/docs/emulation#javascript-enabled) javascript. This way, the page won't hydrate and you can test the server-rendered version of the page.

**Comment by dgozman** [comment]
@ambiguous48 Nice idea!

**Comment by mecies** [comment]
Thank you very much guys, I'll try that and let you know, in the meantime I also tried to parse the response from string to HTML Element with `node-html-parser` like so:
```javascript
 const response = await request.get(...);
 const htmlAsString = await response.text();
 const html = parse(htmlAsString);
 const [nav] = html.getElementsByTagName("nav");
 expect(nav.toString()).toContain("something")
```
Would consider that an anty pattern?

**Comment by mecies** [comment]
I tried it out with the `javascriptEnabled` flag and it's great, thank you. Feel free to close the issue, I'm not closing in case you would be so kind to reply to the previous question. 🙏

**Comment by ambiguous48** [comment]
I guess that would depend what are you testing for. If your aim is to test the _user experience_ on different browsers/devices/screen sizes/etc, then you're better off using the [various](https://playwright.dev/docs/next/release-notes#locators) [web](https://playwright.dev/docs/next/release-notes#new-apis-7) [api's](https://youtu.be/b84eqab3kwc?t=56) exposed by playwright.

Based on the simple example you've given, if you change the html tag from `nav` to `header` (or `div` to `span`, etc) for whatever reason, your test will fail even though nothing would change from the end user's perspective. If you use playwright's locators however, your tests will continue to pass regardless of the implementation details.

**Comment by dgozman** [comment]
Closing as per above. Thanks @ambiguous48 for the great explanation!
