### ISSUE TITLE
[BUG] Black video capture when running playwright on jenkins worker

### ISSUE THREAD

**Issue by napsta32** [microsoft/playwright#19022]
**Context:**
- Playwright Version: 1.23.2
- Operating System: Ubuntu, macOS
- Node.js version: 16.17
- Browser: Webkit (macOS), Firefox (Ubuntu)
- Extra: Run on Jenkins job

## System:
 - OS: macOS 12.6
 - Memory: 255.82 MB / 16.00 GB
## Binaries:
 - Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.23.2 => 1.25.1 
 - playwright-core: ^1.23.2 => 1.25.1

**Code Snippet**

```ts
const config: PlaywrightTestConfig = {
    // ...
    use: {
        // ...
        /** Record videos for all tests in this configuration */
        video: 'on',
    }
};
export default config;
```

**Describe the bug**

When I run my tests locally I don't have any issues. I get videos for each test.
However when I run the same tests on a Jenkins worker, I get black videos instead.
Also the trace reports don't show any screenshot of any sort.

See this video as an example:
[2d222f178b34de517f24af827102bfc43982985a.webm](https://user-images.githubusercontent.com/26403251/203579163-0837a745-b371-4e0e-b1d9-b517c497ab93.webm)

I am not sure if there are special permissions needed to record videos. My guess is that this should be reproducible by running playwright on a daemon service.

**Comment by dgozman** [comment]
@napsta32 Could you share a link to the Jenkins job? It's unlikely we'll be able to help without a repro scenario. If you have a Jenkins worker on your own hardware, it is probably environment- or configuration-related.

**Comment by mxschmitt** [comment]
Closing since it seems stale, please re-file if you have a repro.

**Comment by AkshayAutomationQA** [comment]
I am facing an issue with video recordings during Jenkins runs, even though the same repository works perfectly and records videos correctly on GitHub Actions.
