### ISSUE TITLE
[Question]: I want to delete some entities after every test case, how can I do that? & Exception Handling?

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#19020]
1. I want to delete some entities after every test case, how can I do that?
I have written the delete code to delete the respective entities at the end of each test cases **but if any test case gets fails in between, so it is not executing the delete entity code which is written at last of the test case and that entities are impacting the next test cases**.
Can you please suggest me how to do that?
Also, to delete the respective test cases entities some info is required which is specific to each test case (like entity Ids) and also some info which is common at describe/suite level (like package name).

2. Also, how we can prevent our test case to get fail because of some unexpected popup. Where can we write some code for error / exception handling? 

3. Can we use try - catch mechanism?

**Comment by dgozman** [comment]
> 1. I want to delete some entities after every test case, how can I do that?

Usually, you would put deletion code inside [`test.afterEach()`](https://playwright.dev/docs/api/class-test#test-after-each) hook.

>    Also, to delete the respective test cases entities some info is required which is specific to each test case (like entity Ids) and also some info which is common at describe/suite level (like package name).

If you share an example, I might be able to suggest a particular solution.

> 2. Also, how we can prevent our test case to get fail because of some unexpected popup. Where can we write some code for error / exception handling?

This very much depends on your usecase. Decide what you'd like to do with the popup: close it, retry the test, something else? You can use `try/catch` if you have an action that might fail, and handle the error appropriately.

> 3. Can we use try - catch mechanism?

Yes.

**Comment by AkkyLohana90** [comment]
Thanks for the above reply...
1. If you share an example, I might be able to suggest a particular solution.
>> **Sample Code:**
**async deletePackage(apiToken, packageName, packageId) {
        const deletePackageResponse = await this.apiContext.post(config.baseapiurl + 'url',
            {
                data: {
                    "command": "delete",
                    "data": {
                        "packageId": packageId
                    }
                },
                headers: {
                    'Authorization': 'Bearer ' + apiToken,
                    'Content-Type': 'application/json'
                },
            })
        expect(await deletePackageResponse .ok()).toBeTruthy();
        console.log("Package: " + packageId + " is deleted successfully")
    }**
**NOTE**: Here, **packageId** is TC specific & **packageName** is describe / suite level specific.

2. This very much depends on your usecase. Decide what you'd like to do with the popup: close it, retry the test, something else? You can use try/catch if you have an action that might fail, and handle the error appropriately.
>> **I want to close the popup wherever (on any step) it appears.**  so that I can execute next steps of the TC.

**Comment by AkkyLohana90** [comment]
Hello All,
GM...

**Comment by dgozman** [comment]
@AkkyLohana90 I would do something like this:

```ts
let packageName = 'package name';
let packageId;

test.afterEach(async () => {
  await deletePackage(packageName, packageId);
});

test('test 1', async () => {
  packageId = 'test 1 package id';
  // ... test goes here ...
});

test('test 2', async () => {
  packageId = 'test 2 package id';
  // ... test goes here ...
});
```


> I want to close the popup wherever (on any step) it appears. so that I can execute next steps of the TC

Unfortunately, there is no non-racy solution to this problem. If popup could appear during any action, like while user is clicking some button, and mess up the click, the test could also fail. However, you can hope that's a rear occasion and rely on retries, and then you can just schedule a "click the close button" action. Note no `await`.

```ts
test('example', async ({ page }) => {
  // Click whenever it appears, make sure to not await and catch.
  page.getByRole('dialog').getByRole('button', { name: 'Close the dialog' }).click().catch(() => {});

  // test goes here:
  await page.goto(...);
  await page.getByText('click me').click();
  // ...
});
```

Let me know if this helps.

**Comment by AkkyLohana90** [comment]
**Thanks, dgozman...**
Will try the above suggestions tomorrow (on Monday) and let you know.

**Comment by AkkyLohana90** [comment]
**Thanks, dgozman...**
The above sugested **afterEach** to delete packageName & packageIds is working.
Closing the ticket.
For Exception handling will check the above suggestion.
