### ISSUE TITLE
[Feature] codegen should generate getByTitle locator for title=<...>

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#19032]

**Comment by pavelfeldman** [comment]
There is no such think `aria-title`.

**Comment by yury-s** [comment]
s/aria-title/title/

**Comment by yury-s** [comment]
For this part of the DOM in outlook send UI
<img width="769" alt="image" src="https://user-images.githubusercontent.com/9798949/203664608-c007d995-6182-4d50-8220-1d1fd18da803.png">

we currently generate 
```js
    await page.getByTestId('ComposeSendButton').locator('div').getByRole('button', { name: 'Send' }).filter({ hasText: '' }).click();
```
whereas it could be

```js
    await page.getByTestId('ComposeSendButton').getByTitle('Send (Ctrl+Enter)').click();
```

**Comment by aslushnikov** [comment]
This seems to be fixed!
