### ISSUE TITLE
[Question] I have a issue with create script to authentication login. I have try to use HTTP Authentication and HTTP Proxy option available in documentation under network. But still browser not load with provided username and password. Is there any way to create driver (or browser profile) with already login for given username and password.

### ISSUE THREAD

**Issue by amilup** [microsoft/playwright#19036]
I have try to use HTTP Authentication and HTTP Proxy option available in documentation under network. But still browser not load with provided username and password. Is there any way to create driver (or browser profile) with already login for given username and password.

**Comment by dgozman** [comment]
@amilup Take a look at [`launchPersistentContext()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) - it allows you to launch the browser with pre-populated profile. Let me know if that helps.

**Comment by amilup** [comment]
This is the current code I have try 
`private async Task<IPage> InitializePlaywriteWithAuth()
		{
			var playwright = await Playwright.CreateAsync();
			_browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
			{
				Channel = "chrome",
				Headless = false,
			});

			var context = await _browser.NewContextAsync(new BrowserNewContextOptions
			{
				HttpCredentials = new HttpCredentials
				{
					Username = "Username",
					Password = "Password"
				}
			});
			return await context.NewPageAsync();
		}`

but still its not load with given details. Still browser load with using my current windows login details.

**Comment by dgozman** [comment]
@amilup Your snippet looks good, it should make basic http auth work. Unfortunately, without seeing the whole test (and the page url), I cannot help in a more meaningful way. If you could share a repro, we might be able to help you.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
