### ISSUE TITLE
[BUG] Chrome Headless Clipboard issue

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19038]
We have this function, which is a tooltip, which copies text clipboard, this fails on headless chrome but works on headed.
Works on firefox headless and headed.
Error on headless is: write permission denied

Saw this was supposed to be resolved in 1.24 or never applied to scenario when copy is being initiated from the browser.

```import { useState } from "react";
import { Tooltip } from "@mui/material";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";

const CopyToClipboard = ({ stringToCopy, iconId }) => {
  //Tooltip displayed when copying string to clipboard
  const [toolTipIsOpen, setToolTipIsOpen] = useState(false);

  //Copy the given value to the clipboard and display a success tooltip
  const copyToClipboard = async (value) => {
    await navigator.clipboard.writeText(value);
    setToolTipIsOpen(true);
    setTimeout(() => setToolTipIsOpen(false), 2000);
  };

  return (
    <Tooltip
      PopperProps={{
        disablePortal: true,
      }}
      open={toolTipIsOpen}
      disableFocusListener
      disableHoverListener
      disableTouchListener
      title={`Copied "${stringToCopy}" to clipboard`}
      placement="right"
      arrow
    >
      <ContentCopyIcon
        fontSize="8px"
        id={iconId}
        sx={{
          verticalAlign: "middle",
          marginLeft: "5px",
          cursor: "pointer",
        }}
        onClick={() => copyToClipboard(stringToCopy)}
      />
    </Tooltip>
  );
};

export { CopyToClipboard };
```

**Comment by dgozman** [comment]
@gselsidi you probably need to set `clipboard-write` permission in your config for Chromium. Take a look [at this option](https://playwright.dev/docs/api/class-testoptions#test-options-permissions). 

For comprehensive clipboard coverage, there is an open issue #15860, so merging into it.

**Comment by gselsidi** [comment]
it works in headed, does headed automatically set clipboard?

**Comment by dgozman** [comment]
> it works in headed, does headed automatically set clipboard?

Headed and headless have somewhat different permission systems, so it might be the case.

**Comment by gselsidi** [comment]
working thanks
