### ISSUE TITLE
[Question] - Routing

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#19048]
Hi!

I have a question about page.route() ,  I am not sure if I am using it properly.

I have the following code in a fixture:

```
await page.route('**/*', route => {
    if (route.request().url().includes('blocker') || route.request().url().includes('testing')) {
        route.abort()
    }
    else {
        route.continue();
    }
})
await page.goto(url)
```
Then on my test:

```
//Some stuff
await page.waitForUrl("something")
```

If I am not wrong, I have noticed that "routing" gets executed again when page.waitForUrl() is called, could it be the case?. Is this a correct usage ? I only want to block some request on the initial navigation (page.goto()), should I use "unroute()" after that to prevent this ?

Thanks a lot!

**Comment by dgozman** [comment]
@imartinflores Once setup, route affects all requests matching the pattern, so it is usually called multiple times. Unrouting is a good solution here. You can also narrow down the pattern to only route some requests, not all of them.

```ts
const abortPattern = /blocker|testing/;
await page.route(abortPattern, route => route.abort());
await page.goto(url);
await page.unroute(abortPattern);
```

**Comment by imartinflores** [comment]
Got it! Thanks @dgozman , I finally used unroute() and worked perfectly . Is the route.continue() necessary in my case ? I think when I only used the abort()  (like in your example), the code hang..

**Comment by dgozman** [comment]
@imartinflores `route.continue()` is necessary if your route pattern matches more than you'd like. So, in your example, you abort only some requests, and the rest you must continue as you do.

**Comment by imartinflores** [comment]
Perfect, thanks for the clarification @dgozman !

**Comment by dgozman** [comment]
Closing as per above.
