### ISSUE TITLE
[QUESTION] Call close() on BrowserContext closes chromium when used with --single-process option

### ISSUE THREAD

**Issue by SeekDaSky** [microsoft/playwright#1904]
**Context:**
- Playwright Version:0.13.0
- Operating System: Linux
- Extra: Code built with Typescript

**Code Snippet**

```typescript
import { chromium } from 'playwright'

(async () => {
   const c = await chromium.launch({
        args: [
            '--single-process'
          ]
    })
    let ctx = await c.newContext()
    let p = await ctx.newPage()
    await ctx.close()
   //fails
    ctx = await c.newContext()
})();
```

**Describe the bug**

I tried to use chromium in single-process mode to try to make it more lightweight, but by doing so closing a `BrowserContext` also closes the browser, this might be a normal behavior, but if so it should be documented

**Comment by pavelfeldman** [comment]
`--single-process` is among the flags that are there for internal Chromium needs, they don't warrant normal browser operation and can be gone at any moment. There have been times browser did not even start in a single process mode.

We assume user takes full responsibility over the runtime should they pass any command line flags into Chromium. I thought it goes without saying, but it does not hurt adding it into the docs!
