### ISSUE TITLE
[Feature] Align getByRole behavior with testing librrary

### ISSUE THREAD

**Issue by Fox32** [microsoft/playwright#19046]
I really like the approach of `getByRole` and similar selectors in testing library and therefore I'm happy to use the in playwright too!

There is one difference that makes problems for me.
Having a page like:

```tsx
<button>Add</button>
<button>Add post</button>
```

Using the `getByRole` selector in testing library would match a single result:

```tsx
screen.getByRole('button', {name: 'Add'}) // Returns only the first button
```

While the same selector in playwright matches both and therefore fail:

```tsx
page.getByRole('button', {name: 'Add'}) // Fails because it matches both buttons.
```

The difference between Playwright and testing library is, that Playwright uses a contains query if a string is passed as the name, while testing library is using an exact match. In testing library there is an `exact` option to toggle this behavior, which defaults to `true`. In both libraries you can use RegEx to perform contains or other matches.

There is currently a workaround that I'm using for an exact match:

```tsx
page.getByRole('button', { name: /^Add$/ })
```

Even though it is a behavior change, I would vote for aligning the behavior of the selectors, especially as they claim to be like testing library. That makes it a lot easier for devs to switch from one library to another.

**Comment by debs-obrien** [comment]
Hi @Fox32 can you try adding exact true as the default for exact is in fact false

```js
await page.getByRole('button', { name: 'Add', exact: true }).click();
```

See the [API docs ](https://playwright.dev/docs/next/api/class-locator#locator-get-by-role-option-exact) for more details

**Comment by Fox32** [comment]
Ah, I'm still on 1.27, but yeah that is the behavior I mean. The problem is that the default for exact is different between testing library and playwright.

**Comment by debs-obrien** [comment]
Yes it is different. I will let @dgozman give a better explanation to why we chose the exact default to be false

**Comment by dgozman** [comment]
We made `exact: false` the default to align with all other locators. Overall, it is usually more convenient to write lax locators, especially when you do that manually.

**Comment by Fox32** [comment]
Ok, that's a good reasoning. Selectors like `text=` are also contains queries by default.

I'm fine with keeping it, now I know that `exact` was introduced recently.

**Comment by ZooDoo4U** [comment]
Would assert if, or as Playwright is a test library, being exact is more important and should be the default behavior.  Or better? Provide both by doing:

page.getByRole('button', {name: 'Add'})
page.getByRole('button', {nameLax: 'Add'})
or even be 100% explicit, only have: 
page.getByRole('button', {nameExact: 'Add'})
page.getByRole('button', {nameLax: 'Add'})

Remove 'name' and only have the fully qualified propertyNames...?

Also would assert "name == name",  and "name != name*".  Or again why is it most every library out there have Equals and/or Contains/ContainsInsensitive...  Seems strange lax would be the default and add confusion...   If one wants a lax match, easy enough to be explicit with a properly clear request, if nameLax is provided or nameContains, nameContainsInsensitve...

Also locators are strict by default.   Just saying the precedence in the library is more of a strict nature.  Not a bad thing, if users know they must be exact, would argue that increases the quality of the testing?
