### ISSUE TITLE
[BUG] waitForEvent filechooser timeout 

### ISSUE THREAD

**Issue by InfectedG** [microsoft/playwright#19051]
- Playwright Version: 1.28.1 / 1.27.1 
- Operating System: Windows 10
- Node.js version: 18.12.1 / 7.13.0
- Browser: All expect Firefox, no one in 1.27.1/7.13.0
**this is 2 different setups**

**Code Snippet**

```javascript
import { test, expect } from "@playwright/test";
import dotenv from "dotenv";
dotenv.config();
// ENV
let LoginNew = process.env.LOGIN_NEW || "";
let PwdNew = process.env.PASS_NEW || "";
// ENV
test("censored", async ({ page }) => {
  await page.goto(`${URL}login`);
  await page
    .locator(
      '//*[@id="censored"]/div/div/div/div/div/div/form/div[3]/div[2]/div/div'
    )
    .click();
  await page.getByText("Français").nth(1).click();
  await page.locator('input[name="email"]').type(LoginNew);
  await page.locator('input[name="password"]').type(PwdNew);
  await page.getByRole("button", { name: "censored" }).click();
  await expect(page).toHaveURL(`${URL}`);
  await page.locator(".SkipTutorial").click();
  await page.getByTestId("MenuIcon").click();
  await page.getByRole("link", { name: "censored" }).click();
  await page.locator(".leftContent").click();
  await expect(page).toHaveURL(`${URL}`);
  await page.getByRole("link", { name: "censored" }).click();
  await expect(page).toHaveURL(`${URL}censored`);
  await page.getByRole("button", { name: "censored" }).click();
  await page.waitForTimeout(1000);
  await page.mouse.move(500, 150);
  await page.mouse.down();
  await page.mouse.move(300, 150);
  await page.waitForTimeout(500);
  await page.mouse.move(0, 150);
  await page.mouse.up();
  await page.locator(".startBtn").click();
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    await page.getByRole("button", { name: "censored" }).click(),
  ]);

  if (await page.locator("//div[@role='dialog']").isVisible()) {
    page.click("(//button[@type='button'])[2]");
  }
  const filesUp = [
    "./divers/censored.png",
    "./divers/censored2.jpg",
    "./divers/censored3.jpg",
  ];
  let rdmfilesUp = filesUp[Math.floor(Math.random() * filesUp.length)];
  await fileChooser.setFiles(rdmfilesUp);

  await page.getByRole("button", { name: "censored" }).click();
  await page.getByRole("button", { name: "censored" }).click();
});
```

This test is working fine with debug mode, but when I run this in headless, it keep crashing except on Firefox (I guess its due to the fact that I put `permissions.default.microphone: 1` & `permissions.default.camera: 1` in playwright.config.ts) (I have `permissions: ["camera","microphone"]` on Chrome too), here is the CLI logs:
![image](https://user-images.githubusercontent.com/12138607/203775990-6f8d8da4-3533-4aa0-97a9-c2f5c66150e5.png)

! This test is for a React Native app !

Here is the trace: 
![image](https://user-images.githubusercontent.com/12138607/203778147-1b8d6740-37d0-458d-ad31-58be50205576.png)

![image](https://user-images.githubusercontent.com/12138607/203790189-081a4951-ac19-4950-8a0e-8cec1fcf62cc.png)
I have the feeling that it is because of this modal that it timeout/crashes, this modal appears because there are no permissions on the camera

**Comment by mxschmitt** [comment]
```
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    await page.getByRole("button", { name: "censored" }).click(),
  ]);
```
this should be the following
```
  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    page.getByRole("button", { name: "censored" }).click(),
  ]);
```

otherwise the async flow is not guaranteed. You want to have first let the filechooser listener attach and then click, when having an await there, it first does the click and race then most likely.

```
if (await page.locator("//div[@role='dialog']").isVisible()) {
    page.click("(//button[@type='button'])[2]");
  }
```

this should also be

```
if (await page.locator("//div[@role='dialog']").isVisible()) {
    await page.click("(//button[@type='button'])[2]");
  }
```

(missing await)

Most likely this already makes your script work when you apply these two suggestions. this is unrelated to the permission issue tho.

Let us know if this helps!

**Comment by InfectedG** [comment]
Hi! Thanks for the reply and for the fixes, but this is not working actually, I still have the same modal thing for the camera because all of theses browsers except Firefox don't have the perms

**Comment by InfectedG** [comment]
> Hi! Thanks for the reply and for the fixes, but this is not working actually, I still have the same modal thing for the camera because all of theses browsers except Firefox don't have the perms (still working in debug/headed mode)

Any news? I can't launch tests in headless, this is very annoying because I can't test in CI/CD..

**Comment by dgozman** [comment]
@InfectedG Could you share your config please? I see you are setting up permissions there, and since it looks like a permission issue in Firefox, that would make debugging easier.

**Comment by InfectedG** [comment]
> @InfectedG Could you share your config please? I see you are setting up permissions there, and since it looks like a permission issue in Firefox, that would make debugging easier.

Sure: https://pastebin.com/raw/7uSCv3ib

**Comment by mxschmitt** [comment]
We need unfortunately a repro to act on this, otherwise we can't help much.

**Comment by InfectedG** [comment]
> We need unfortunately a repro to act on this, otherwise we can't help much.

It won't be possible, it's financial stuff, but you can use the browser with canvas/pure HTML ; as simple as that: https://davidwalsh.name/demo/camera.php

**Comment by mxschmitt** [comment]
You can do this for Chromium based browsers to emulate a media device inside your playwright config under the "use section":

```
        permissions: ['camera', 'microphone'],
        launchOptions: {
          args: ['--use-fake-device-for-media-stream'],
        }
```

Since the thread has now quite an amount of context, could we summarise whats the exact issue is and what works / does not work?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by InfectedG** [comment]
> 
Well, since I've written this several times, the browsers timeout all on the same line **(EXCEPT FIREFOX)** : 'filechooser', the technology used is native as simple as that, here it is : https://developer.mozilla.org/fr/docs/Web/API/MediaDevices/getUserMedia

`  const [fileChooser] = await Promise.all([
    page.waitForEvent("filechooser"),
    page.getByRole("button", { name: "J'ai compris" }).click(),
  ]);
  if (await page.locator("//div[@role='dialog']").isVisible()) {
    await page.click("(//button[@type='button'])[2]");
  }
  const filesUp = [
    "./divers/test.png",
    "./divers/test2.jpg",
    "./divers/test3.jpg",
  ];
  let rdmfilesUp = filesUp[Math.floor(Math.random() * filesUp.length)];
  await fileChooser.setFiles(rdmfilesUp);`

I'll write a summary for all of you
**BROWSERS :** 

Firefox: ✅ **working**
Chromium : ❗ **NOT WORKING**
Google Chrome : ❗ **NOT WORKING**
MS Edge : ❗ **NOT WORKING**
Webkit : ❗ **NOT WORKING**
![image](https://user-images.githubusercontent.com/12138607/206466375-ee59efe2-f31c-4700-a10a-4ff24ca85db0.png)
Guys it doesn't seem very complicated to understand
