### ISSUE TITLE
[Feature] Page has locator function

### ISSUE THREAD

**Issue by domme1908** [microsoft/playwright#19050]
It would be great to have something like page.hasLocator(XY, {timeout:1000}), that essentially does the same thing as page.waitForLocator() but without throwing anything in case the locator was not found and instead returning a boolean. Working with expect(page.locator).toBeSOMETHING requires the DOM-Element the locator is referring to to be existing. But if the element doesn't even exist the auto-wait would wait for the locator until the timeout expires.

Thanks!

**Comment by mxschmitt** [comment]
there is no page.waitForLocator(). There is [locator.isVisible()](https://playwright.dev/docs/api/class-locator#locator-is-visible) what people usually use. But it does not retry, so for assertions we recommend [expect(locator).toBeVisible()](https://playwright.dev/docs/test-assertions#locator-assertions-to-be-visible) which retries until the condition is met or the timeout is reached.

If you want to combine it with a timeout, you can use [locator.waitFor({ state: 'visible' })](https://playwright.dev/docs/api/class-locator#locator-wait-for) where you can pass if you want to wait until its attached, detached or visible.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
