### ISSUE TITLE
[Question] Interact with extension under devtools panel

### ISSUE THREAD

**Issue by vinodreddy-bs** [microsoft/playwright#19053]
I need to write e2e tests for an accessibility extension. Our extension is loaded in the devtools panel and I would like to interact with it via UI.

Have a library [puppeteer-devtools](https://github.com/dequelabs/puppeteer-devtools) which will provide us the extension panel as a frame and can interact with it (puppeteer version used in this library is depecated). However, this is not supported with latest puppeteer version and I cannot go with this.

Is there a way I can do this via playwright? I am not looking for loading the extension in a separate page (this will not work for my extension as it should be loaded under active page/tab). Our extension manifest is v3

**Comment by mxschmitt** [comment]
I created a demo for you, let us know if it works for you! Requires definitely some tweaks, and the demo is with a manifest v2 extension, but in general it should work with v3 as well: https://gist.github.com/mxschmitt/f891a2f8fb37ce01ed026627f75d7ce6

**Comment by vinodreddy-bs** [comment]
@mxschmitt Thanks it worked. Only thing I wanted to do is to set the size of devtools panel. When I am trying with userDataDir, it is creating additional records and overrriding Preferences file.

**Comment by mxschmitt** [comment]
What about 

```
  await devtools.setViewportSize({ width: 1920, height: 1080 });
```

we don't support maximising as of today.

**Comment by vinodreddy-bs** [comment]
@mxschmitt It is partially worked. It sets the devtools size but leaving the bottom space whitish. 
```js
global.browser = await chromium.launchPersistentContext("", {
    headless: false,
    executablePath: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    args: [`--disable-extensions-except=${extensionPath}`, `--load-extension=${extensionPath}`, "--window-size=1920,1040"],
    devtools: true,
    viewport: null,
  });
global.devtools = browser.pages().find((page) => page.url().includes("devtools://devtools/bundled/devtools_app.html"));
assert(devtools);
await devtools.setViewportSize({ width: 1920, height: 500 });
```

**Comment by mxschmitt** [comment]
sounds then like its solved and not a Playwright issue now, more a devtools issue. Closing by that.
