### ISSUE TITLE
[BUG] Mocked requests not being intercepted

### ISSUE THREAD

**Issue by neil-lancaster** [microsoft/playwright#19054]
**Context:**
- Playwright Version: 1.27.1
- Operating System: macOS 12.6.1
- Node.js version: 18.11
- Browser: Firefox, WebKit

**Code Snippet**

```javascript
import { expect, test as base } from "@playwright/test";

const test = base.extend({
  page: async ({ page }, use) => {
    await page.route("**/account/forgot_password", (route) => {
      route.fulfill();
    });
    await use(page);
  },
});

export { expect, test };
```
```javascript
test("navigates to reset password view when user submits an email", async ({
  page,
}) => {
  const forgotPasswordPage = new ForgotPasswordPage(page);
  await forgotPasswordPage.start();
  await forgotPasswordPage.populateEmail("name@email.com");
  await forgotPasswordPage.confirmEmail();
  await expect(forgotPasswordPage.resetPasswordButton).toBeVisible();
});
```
```javascript
export class ForgotPasswordPage {
  readonly page: Page;
  readonly emailInput: Locator;
  readonly confirmEmailButton: Locator;
  readonly resetPasswordButton: Locator;

  constructor(page: Page) {
    this.page = page;
    this.emailInput = page.getByRole("textbox", { name: "Email" });
    this.confirmEmailButton = page.getByRole("button", {
      name: "Confirm email",
    });
    this.resetPasswordButton = page.getByRole("button", {
      name: "Reset password",
    });
  }

  async start() {
    await this.page.goto("http://localhost:3000/forgot-password");
  }

  async populateEmail(value: string) {
    await this.emailInput.fill(value);
  }

  async confirmEmail() {
    await this.confirmEmailButton.click();
  }
}
```

**Describe the bug**

I'm having an issue with Firefox and WebKit where requests are not being intercepted and therefore tests are failing. I don't have any issues on Chromium (or Edge for that matter) but when I run the tests in debug mode on Firefox, I can see they are showing as blocked in the Network tab. I'm struggling to see why there would be any difference between them.

I've included one of the simpler tests that is failing. All it does is populate an input and click a submit button which sends a request to `/account/forgot_password` which is mocked in my custom text fixture above. I've tried adding a generic route handler and putting logging in there and I only see the document, image, and CSS requests get logged but not the one to my REST API. Again, this does work fine on Chromium which is why I'm a bit lost for ideas.

**Comment by dgozman** [comment]
@neil-lancaster Your code looks good, and symptoms sound like a bug. We would be happy to debug, if you could provide a repro including the page. Most likely this is related to a specific request your page is sending, so it's hard to figure out what's going on without trying to debug it locally.

**Comment by neil-lancaster** [comment]
I have some new information for this one. I setup a new app with Create React App and created a basic form to replicate the test above which all worked fine. I then went back to the app that is having issues and ran the entire test suite on all 4 browsers. Strangely the tests for the "Forgot Password" page now work but one of my other test files is now completely failing across all 4 browsers with the same issue where one request just doesn't get intercepted.

**Comment by neil-lancaster** [comment]
Seems to all be working now 🎉 One test on Safari is failing locally but for different reasons. For anyone who comes across this, I think my main issue was trying to use a disallowed port in my test environment file which Safari (and maybe Firefox) block. Once I changed that, requests were being intercepted again.

**Comment by dgozman** [comment]
@neil-lancaster It's great that you have figured it out! If you have any other questions/problems, don't hesitate to open a new issue.
