### ISSUE TITLE
[Question] While running a test with VSCode, browser closes when test is finished even though "Show browser" option is enabled

### ISSUE THREAD

**Issue by BekaOkromchedlidze** [microsoft/playwright#19059]
I would like to utilise the new record at cursor feature but the browsers automatically close once the test has finished. Can anyone tell me is there a preference I have to change in order to keep the browser open?

Thanks

**Comment by mxschmitt** [comment]
Can you show us how your test looks like? Do you launch your browser or context manually?

If you use the [page fixture](https://playwright.dev/docs/writing-tests#test-isolation) which Playwright provides to you, the browser should stay open all the time.

**Comment by BekaOkromchedlidze** [comment]
@mxschmitt I use the page fixture. Please take a look at an example below. I'm wondering if it is because I use global setup to save a logged in storage state. So, at setup I log in, save the state, browser closes and another browser opens once the test begins.
![image](https://user-images.githubusercontent.com/45874523/203955095-d9224c20-16c8-4fb4-83e8-a3f3092210c7.png)

**Comment by BekaOkromchedlidze** [comment]
@mxschmitt I use the page fixture. Please take a look at an example below. I'm wondering if it is because I use global setup to save a logged in storage state. So, at setup 
![image](https://user-images.githubusercontent.com/45874523/203955095-d9224c20-16c8-4fb4-83e8-a3f3092210c7.png)

**Comment by pavelfeldman** [comment]
I can see you are overriding the fixtures in ../../../../fixtures/fixtures. You are probably overriding the page / context fixtures and close the page / context.

**Comment by BekaOkromchedlidze** [comment]
Hi @pavelfeldman , I have created a custom fixture which extend playwright test object but I don't think I am overriding the page fixture. Could you please take a look below. Do you know what I could change to not override the page fixture?
![image](https://user-images.githubusercontent.com/45874523/204269969-d6c7c767-7ca6-4d19-98a7-fb22fb97e57b.png)

**Comment by BekaOkromchedlidze** [comment]
I don't think the custom fixture is the problem. I have swapped to use the default playwright test instead and the issue is still happening. 
![image](https://user-images.githubusercontent.com/45874523/204282223-58843d03-dacf-451d-9854-3b0e0682a1c8.png)

I have also removed the global setup login + save logged in state flow and this had no effect either. 
![image](https://user-images.githubusercontent.com/45874523/204282470-669f18f0-8136-420e-8f5d-9460fc194ca0.png)

**Comment by BekaOkromchedlidze** [comment]
@mxschmitt @pavelfeldman I've found the issue. The browser closes when trace collect option is set to 'on'. Can this be considered a bug? I would expect the trace save could be initiated once the user manually closes the browser?
![image](https://user-images.githubusercontent.com/45874523/204287471-405dbb45-3a9e-4974-8a65-4e615773f9bc.png)

**Comment by pavelfeldman** [comment]
I wonder if we should do the opposite instead: while in the 'Show browser' mode, we could disable tracing. Would that work for you? Or do you use traces in your dev workflow?

**Comment by BekaOkromchedlidze** [comment]
@pavelfeldman I do use traces quite a lot during development, because it is such a great tool for having a good overview of what is exactly going on during the test in-case something isn't going quite as expected. However, your suggestion would also work. I would just toggle the Show Browser option off if I need to save and view the traces.

**Comment by markbrockhoff** [comment]
I'm experiencing the exact same issue. The difference is that I set trace to 'retain-on-failure' in my playwright config. It would be really great if this could be fixed as it's very confusing that tracing being enabled is causing the browser to close after the test.

**Comment by ValentinH** [comment]
I faced the same issue and it was due to using the `video` option:
```ts
  use: {
    video: {
      mode: 'retain-on-failure',
      size: { width: 640, height: 480 },
    },
}
```

I find this a bit misleading, would it be possible to automatically disable the video if the test in run with "Show browser"?
