### ISSUE TITLE
[Question] How to connect Playwright with AWS secret manager?

### ISSUE THREAD

**Issue by Safbanu13** [microsoft/playwright#19052]
What would be the best way to manage passwords and secrets in Playwright. We are contemplating using AWS Secret manager for the same. Can someone help me with the implementation code for the same.

**Comment by mxschmitt** [comment]
Closing as per above. Also its pretty common to inject secrets via environment variables into your testing infrastructure. Depending on your setup e.g. GitHub Action secrets etc.
