### ISSUE TITLE
[Question] Security scan with playwright

### ISSUE THREAD

**Issue by kedarsprabhu** [microsoft/playwright#19061]
Can security scan be performed using Playwright automation scripts integrating with ZAP (Zed attack proxy) security scan tool as we used to do in Selenium?

**Comment by mxschmitt** [comment]
Yes, you can set a proxy, see here: https://playwright.dev/docs/network#http-proxy

You can also do this inside your playwright.config.ts

**Comment by kedarsprabhu** [comment]
Thanks for the inputs!
