### ISSUE TITLE
[Question] Roadmap for future features port to all available languages

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#19062]
Hello Playwright team,

I was wondering if you could create a roadmap for future features that possible would be included in future releases (the ones that affect all programming languages).

Every release I am seeing some great improvements, many of them only for JS/TS, but there are also a lot of tickets marked as "P3-collecting- feedback" that are staying for long time waiting on queue.  

Visual comparisons, soft assertions, expect.pool and many others are really great features to be ported also to other languages, but will we see them sometime in the future? 

Those important features most probably will make a difference to a lot of people to switch to Playwright.

That is why something like a roadmap for me would be very beneficial to make the picture more clear with the test tools selection. 

For reference below screenshot:

![image](https://user-images.githubusercontent.com/94455079/203848496-52b7d132-e29b-4672-b0a3-ac3e9cb1d1f8.png)

**Comment by pavelfeldman** [comment]
The features you list are Playwright Test Runner features, not Playwright Library features: visual comparisons, soft assertions, expect.poll. While we offer feature parity for Playwright Library in the language ports, we only offer test runner for Node, suggesting that other platforms should utilize prominent test runners from the respective ecosystems: Pytest, JUnit, NUnit, MSTest, etc.

If there is something we can do from our side, we would need to prioritize it, i.e. figure out what's missing in what language port, which test runner is being used, collect upvotes and proceed to the implementation.

**Comment by mxschmitt** [comment]
Closing as per above.
