### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by arsoni20** [microsoft/playwright#19064]
**Context:**
- Playwright Version: 1.28
- Operating System: Linux
- Node.js version: 14.0
- Browser: [WebKit]
- Extra: I am trying to build automated tests which use headful browser to take screenshots and scroll the page, headless browser doesnt work in my case. 

**Code Snippet**

```javascript
const { webkit } = require('playwright');  // Or 'chromium' or 'firefox'.

(async () => {
  const browser = await webkit.launch({headless:false});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://example.com');
  const title = await page.title(); // ({path: 'screenshot.png'});
  console.log(title);
  await browser.close();
})();
```

**Describe the bug**

I am not able to get the response when I add the config - headless:false. 

When I add the command in my Dockerfile 
``` CMD ["xvfb-run","node", "index.js"] ```

it just goes into hung state.

If I just pass ``` CMD ["node", "index.js"] ```

browserType.launch: 
╔════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team                                                                             ║
╚════════════════════════════════════════════════════════════════════════════════════════════════╝                          

Dockerfile-
```
FROM node:14
FROM mcr.microsoft.com/playwright:focal

# Create app directory
WORKDIR /usr/src/app

# install all required libraries
#RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev libsoup2.4-dev chromium

# RUN apt-get update && apt-get -y install chromium-browser

RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev fluxbox xinit xterm xvfb x11-apps x11-xkb-utils libx11-6 libx11-xcb1


# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install


# Bundle app source
COPY . .

EXPOSE 8080

CMD ["xvfb-run","node", "index.js"]

```

**Comment by mxschmitt** [comment]
How do you start the container? to make xvfb work, you need to pass `--init` when starting the container.
