### ISSUE TITLE
[Question] FingerPrint Emulator

### ISSUE THREAD

**Issue by sansepion** [microsoft/playwright#19071]
Hello.

I have a problem using Playwright with Stealth.

I'm trying to automate messages to my customers, but WhatsApp is detecting the automation and quickly banning me.

When I try to use Playwright's Stealth, the site simply won't open.

But the subject is... How do I emulate a FingerPrint in PlayWright and prevent sites from being detected?

**Comment by dgozman** [comment]
@sansepion Playwright is a testing solution. If a page actively does not want to be tested/automated, Playwright is not going to try to work around that. We do not provide any "Stealth" package/mode that tries to be undetectable, so this is out of scope for the Playwright project.
