### ISSUE TITLE
[Question] Playwright configuration file path options?

### ISSUE THREAD

**Issue by PriyankaSoni1210** [microsoft/playwright#19076]
Can the playwright config file be specified in any other locations other than the root or 'tests' directory. For me, any other path except the project root/tests directory, throws the error -
---------------------------------------------------
Running 0 tests using 0 workers

=================
 no tests found.
----------------------------------------------------

**Comment by dgozman** [comment]
@PriyankaSoni1210 Run with `--config` option. Overall, running with `--help` will show some more interesting options 😄 

```sh
npx playwright test --config ./path/to/playwright.config.ts

npx playwright test --help
```
