### ISSUE TITLE
[Question] Is there a way for a test to get the value of a variable that was set during the execution of a previous test?

### ISSUE THREAD

**Issue by agusjacob** [microsoft/playwright#19075]
We've had some flaky tests related to the IMAP API for reading emails. Many times, the emails have already been received but the API needs extra time to be able to get to them. We have several tests, in different modules/suites that depend on this functionality, and we also don't want to introduce any flakyness to test results.

Therefore, we've come to the conclusion that the best approach would be to have some variable in a module that is set to true if the email API is not working as intended, and skipping tests that require email validation. The code is something like this:
```

import setEmailFlagValue from 'helpers/runConfig'
test.describe('Payments', async (page) => {
    test('Send Receipts to user', async (page) => {
        let error = this.someLogicThatReturnsEmailAPIError();
        // Below line populates a JS Object to true
        setEmailFlagValue(error);
    })
})

// ON ANOTHER MODULE/FILE:
import getEmailFlagValue from 'helpers/runConfig'
test.describe('Payments', async (page) => {
    test('Send Greetings to user', async (page) => {
        test.skip(getEmailFlagValue(), 'Email API not working!');
    })
})
```
The value stored through the setEmailFlagValue() method is not getting passed to the execution of the other tests,  therefore when the getEmailFlagValue() method is executed, it's not skipping the test. Even when they are in the same module, that run in the same worker, just different tests.

Thanks!

**Comment by dgozman** [comment]
@agusjacob Note that any such approach only works if you are not running tests in parallel. Otherwise, you might running the test "supposed to be skipped" even before you determine whether it should be skipped or not.

So, if you are not running tests in parallel, I'd recommend creating a file meaning "skip email tests". Rough sketch:

```ts
import fs from 'fs';
import path from 'path';

test('determines the flag', async () => {

  // ...
  if (shouldBeSkipped)
    fs.writeFileSync(path.join(test.info().project.outputDir, 'skip.flag'), '1');
});
```

```ts
import fs from 'fs';
import path from 'path';

test('determines the flag', async () => {
  test.skip(fs.existsSync(path.join(test.info().project.outputDir, 'skip.flag')));
  // ... test goes here
});
```

Let me know if that helps.

**Comment by reutenkoivan** [comment]
For this case, probably, be better to create a file names convention in your project and calculate the glob pattern in the playwright config before every tests execution.

**Comment by agusjacob** [comment]
Hey everyone, I actually ended up implementing a file system solution like you mentioned. Are there any plans in the future to implement any functionality that might replace this?

**Comment by dgozman** [comment]
We recommend to use [`serial` mode](https://playwright.dev/docs/test-retries#serial-mode) for any inter-dependent tests.
