### ISSUE TITLE
[BUG] Webkit browser is cut off at the top

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#19084]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Mac
- Node.js version: 14.6
- Browser: Webkit
- Device: Macbook Pro 14" M1 2021

**Describe the bug**
Launch any test and observe the Webkit browser that is launched. The browser is bit cutoff at the top

<img width="1297" alt="Screen Shot 2022-11-25 at 4 17 57 PM" src="https://user-images.githubusercontent.com/22205721/204065264-d13a21b1-7e34-4789-b24b-f8d0cdb8ff17.png">

**Comment by aslushnikov** [comment]
this is fixed with the latest roll.
