### ISSUE TITLE
[BUG] .not assertion is not rendered correctly in Inspector

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#19083]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Mac
- Node.js version: 14.6
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test("sample test", async ({
  page,
}) => {
  await page.goto("https://playwright.dev/");
  await page.getByRole("link", { name: "Get started" }).click();
  await page.getByRole("link", { name: "Community" }).click();
  await expect(
    page.getByRole("link", { name: "Star microsoft/playwright on GitHub" })
  ).not.toBeVisible();
});
```

**Describe the bug**
For the above tests, when I do last assertion i.e `not.toBeVisible()`, it doesn't correctly `.not.` in codegen. It shows as `expect(..).toBeVisible()`. Please see the attached screenshot.

Also, when I am on any assertion, it takes me to `captureStackTrace()`. I would prefer if it showed the execution line in my source/test file.

<img width="595" alt="Screen Shot 2022-11-25 at 4 13 42 PM" src="https://user-images.githubusercontent.com/22205721/204065090-eaa0fa2a-5ef7-4059-b15c-15c5954d91d5.png">

**Comment by dgozman** [comment]
@Nav-2d I can repro the incorrect naming, but not the `captureStackTrace` problem. Do you have multiple files in the "Target" dropdown at the top-right of Inspector window?

**Comment by Nav-2d** [comment]
@dgozman - I see three files. `test.spec.ts` is my test file but it automatically takes me to the `util.js` when I am on assertion step

**Comment by dgozman** [comment]
@Nav-2d Thank you. The root cause is probably the same as in #19087, so let's track it separately there.

**Comment by Nav-2d** [comment]
Thanks @dgozman. Looks like you fixed the `.not` render issue. Please feel free to close it
