### ISSUE TITLE
[BUG] If test title is wrapped to next line, then the "Play" button does not start the test

### ISSUE THREAD

**Issue by JonahKK** [microsoft/playwright#19088]
**Context:**
- Playwright Version: 1.27.1, extension 1.0.0
- Operating System: Mac
- Node.js version: 16.14.0

**Describe the bug**

![Image 26-11-2022 at 15 34](https://user-images.githubusercontent.com/23238398/204094248-4e66c0ac-81aa-4edc-a5d0-67035eaee1c2.jpg)
Clicking the second button for running the test does not work. Only the first button does something.

**Comment by ambiguous48** [comment]
Is there any output when you click the `show output` button?

https://user-images.githubusercontent.com/17984549/131338744-2bf71d20-79b4-48f2-94dd-9c945c34fae1.png

This can happen when 2 tests have the exact same title. You can also try running it through the terminal with `npx playwright test ./myfile.spec.ts` to check the output.

**Comment by pavelfeldman** [comment]
Folding into the upstream issue.
