### ISSUE TITLE
[Question] Chrome extension with github action.

### ISSUE THREAD

**Issue by sleaper** [microsoft/playwright#19090]
Hi guys,
I have a question. When I am testing my chrome extension locally everything is ok and works perfectly well. But when I run a test inside GitHub action I get this error: `Test timeout of 30000ms exceeded while setting up "context".` Is it even possible to test chrome extension inside with Github actions?
My version of playwright: 1.28.1

Here is my test:
![image](https://user-images.githubusercontent.com/19505081/204102836-89c89f65-5bd8-4469-94b3-2e81e9ff179b.png)

Here is my GitHub action:
![image](https://user-images.githubusercontent.com/19505081/204102883-2edc280c-6e06-446b-b6ac-4a74598c561c.png)

if you have any questions, feel free to ask!

**Comment by pavelfeldman** [comment]
You seem to be running Chromium in headless mode, which does not have extensions support.

**Comment by bd-dm** [comment]
@sleaper I had the same issue and for me it was missing dist folder - I forgot to add build step before test step, check it out

**Comment by mxschmitt** [comment]
You can set the `DEBUG=pw:api,pw:browser` env var to see what it actually happening including logs. That might give us a hint whats going on.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by sleaper** [comment]
> @sleaper I had the same issue and for me it was missing dist folder - I forgot to add build step before test step, check it out

That was it! Thank you
