### ISSUE TITLE
Can't seem to get test to run in GitHub Actions

### ISSUE THREAD

**Issue by omar-ameen1** [microsoft/playwright#19098]
Hello! I'm brand new to PlayWright and was hoping I could get some guidance with this issue.

I've written a fairly simple and straightforward test for my electron application, and it works beautifully locally. Unfortunately, it times out on github actions and fails. I'm not quite sure why. 

<img width="802" alt="Screen Shot 2022-11-27 at 3 05 43 PM" src="https://user-images.githubusercontent.com/99096427/204157161-8194a14e-b22e-46bd-b8e9-bef00c8cc92f.png">

here's the test^

and here's the github actions .yml file:
<img width="500" alt="Screen Shot 2022-11-27 at 3 06 22 PM" src="https://user-images.githubusercontent.com/99096427/204157187-b9a31ed1-902f-42dc-ad8e-eb56193ee2ca.png">

finally, here's the error log:
<img width="972" alt="Screen Shot 2022-11-27 at 3 06 46 PM" src="https://user-images.githubusercontent.com/99096427/204157205-6e0def7c-2f2a-4a71-aa57-962336a3d6fb.png">

Any guidance would be greatly appreciated. Thanks so much!

**Comment by pavelfeldman** [comment]
So the same clean install works locally, but on on GH Actions w/ macos? This would be very strange, could you confirm clean checkout works?

**Comment by mxschmitt** [comment]
Which Playwright version are you using? Make sure to use 1.28.1 which is the latest which includes an electron fix.

Also you can set the `DEBUG=pw:api` env var to see what is exactly hanging.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
