### ISSUE TITLE
[Feature] Record Youtube videos with resolution at least of 1080p

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#19094]
I'm a big fan of your videos. I think it is one of the things that makes the project unique. Gathering information directly from the major developers - is one of the most excellent parts. 

But I have a little complaint :) 
Your videos are recorded with a resolution of 720p - please record them in at least a resolution of 1080p.

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/52656401/204133258-cbfea2cb-b6e6-4d9d-9532-e25654149fec.png">

**Comment by aslushnikov** [comment]
@AlexKomanov we recorded 1.29 video in 1080p, hopefully it'll be more pleasing to the eyes!
