### ISSUE TITLE
[BUG] can't run custom describe block from vscode

### ISSUE THREAD

**Issue by goldylucks** [microsoft/playwright#19092]
**Context:**
- Playwright Version: `"@playwright/test": "^1.28.1"`
- Operating System: Mac
- Node.js version: `v16.18.0`
- Visual Studio Code version: `1.73.1`
- Playwright for VSCode extension version: `v1.0.1`
- Browser: all

**Code Snippet**

```js
import { test } from "@playwright/test"

export const describeGuest = describeGuestFn as unknown as typeof test.describe

function describeGuestFn(testSuffix: string, describeFn: IDescribeFn) {
  // eslint-disable-next-line jest/valid-title
  test.describe(...makeDescribeGuestArgs(testSuffix, describeFn))
}
```

PS. The bug template is missing the example:

> Help us help you! Put down a short code snippet that illustrates your bug and
> that we can run and debug locally. For example:

(I assume the example should be here? 🤔)

**Describe the bug**

New user here, migrated from `cypress`, in which I had custom `describe` commands. For example, I `describeUser` is used like so:

```
describeUser("Home page" , function() {
  test("does xyz", ...testImplementationHere)
})
```

Behind the scenes, the `describeUser` has `before` and `after` logic (setup, teardown, etc), as well as prefixing the test name so "Home page" becomes "User - Home page".

This works as expected in Playwright, but in vscode I can't run the entire block, see in the screenshot there's no ▶️ button.

I assume the extension doesn't rely on TS types but rather locates by exact string match?

Maybe there's a more `playwright` way to achieve what I'm doing here?

when I do `npx playwright test` it works as expected (which makes sense, it's just JS at the end of the day), so looks like the problem is specific to VScode?

Thanks for the great project btw! I'm now migrating all my tests over to you guys 💪

**Comment by dgozman** [comment]
@goldylucks Could you please share the full repro? I tried with the following, and things work for me:

```ts
// helper.ts

import { test } from "@playwright/test"

export const describeUser = describeGuestFn as unknown as typeof test.describe

function describeGuestFn(testSuffix: string, describeFn: any) {
  // eslint-disable-next-line jest/valid-title
  test.describe(describeFn);
}
```

```ts
// example.spec.ts

import { test, expect } from '@playwright/test';
import { describeUser } from './helper';

describeUser("Home page" , function() {
  test(`test`, async ({ page }) => {
    await page.goto("https://playwright.dev/");
    await page.getByRole("link", { name: "Get started" }).click();
    await page.getByRole("link", { name: "Community" }).click();
    await expect(
      page.getByRole("link", { name: "Star microsoft/playwright on GitHub" })
    ).not.toBeVisible();
  });
});
```

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
