### ISSUE TITLE
[Question] Stubbing same route with different requests

### ISSUE THREAD

**Issue by yjing001** [microsoft/playwright#19106]
I have a page that makes multiple GraphQL requests. Those requests have the same route `**/graphql` but different request body. So for a given test, a generalised function `stubResponse` is called multiple times at the beginning to set up stubs, e.g., 
```
await stubResponse(page, expectedRequestBody1, responseBody1);
await stubResponse(page, expectedRequestBody2, responseBody2);
``` 
but it seems that only the last `stubResponse()` will take effect when the page is loading. Is it supposed that the last one overrides the previous ones for the same route?

The following is the code snippet and basically it will fulfil the request when the incoming request body equals the expected request body. 
```
const stubResponse = async (page, expectedRequestBody, responseBody) => {
  await page.route('**/graphql', async (route, request) => {
    if (request.postDataJSON() _equals_ expectedRequestBody) {
      await route.fulfill(...responseBody...);
    }
  });
}
```

I'm wondering if it's possible to make all `stubResponse`s work for a given test? Thank you very much.

**Comment by pavelfeldman** [comment]
You would need to finish it with [route.fallback()](https://playwright.dev/docs/next/api/class-route#route-fallback) to chain all the matching routes.
