### ISSUE TITLE
[Question] Switch between multiple configuration files

### ISSUE THREAD

**Issue by buraksimsekgit** [microsoft/playwright#19101]
Hello everyone,

My question is; sometimes Test Data depends from the environment to the environment. Is that possible for the test class to fetch Test Data dynamically depending on the environment? Let's say we have " qa.json, stage.json, or prod.json " files to store our Test Data. Can fetch these Test Data dynamically on the Test class depending on which environment are we running our tests?

I have seen this on Cypress documentation that it reads JSON files like a .env file and dynamically reads Test Data from there with the help of the " fs-extra " npm package. (Added example below)
https://docs.cypress.io/api/plugins/configuration-api#Switch-between-multiple-configuration-files

Is that possible to do the same thing with Playwright? Thank you very much!

**Comment by pavelfeldman** [comment]
Playwright tests are Node.JS programs, so you can fetch anything you want in the global setup and then use it in the tests. You don't need any extra packages for it.
