### ISSUE TITLE
Where and how to deploy my python script using Playwright ?[Question]

### ISSUE THREAD

**Issue by OmarSaidIbrahim** [microsoft/playwright#19105]
Hi all, I am trying to deploy my code somewhere like Heroku or my personal RaspberryPi, but I know none of them support Playwright. My code should run 24/7, every 5 minutes so I will need somewhere to host it and run it. Does anyone have some kind of solution?

The buildpack for Heroku does not support stack 22. 

My RaspberryPi is an ARM71 which is not supported.

**Comment by pavelfeldman** [comment]
This is outside of the scope for the Playwright project - we can't act on it, so I'll close it.
