### ISSUE TITLE
[BUG] Unknow engine for page.getByRole after upgrade to 1.28.1

### ISSUE THREAD

**Issue by lucasbit** [microsoft/playwright#19110]
**Context:**
- Playwright Version: 1.28.1 bug does not show in 1.27.1
- Operating System: Windows
- Node.js version: v18.12.1
- Browser: Chromium
- Extra: Not really- it is fresh project has only 3 tests in it, I have removed node modules, and rerun npm i

![image](https://user-images.githubusercontent.com/29520131/204283974-0e22add7-bf69-4e28-ae0c-d08e1d6ed650.png)

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

![image](https://user-images.githubusercontent.com/29520131/204283503-25b846b5-e821-4cca-becf-fe41a8127446.png)

![image](https://user-images.githubusercontent.com/29520131/204281628-a1574f51-8a25-4a2d-9e12-13e5271843e0.png)
const headerNew = page.getByRole('button', { name: 'New' })
  await headerNew.click()
```

**Describe the bug**
It was working fine on older Playwright version (1.27.1) it broke right after upgrade to 1.28.1. I have removed pack.lock.json and node-modules, rerun npm i. Bug still present
Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
Are you running tests locally or are you using launchServer/connect variation of servicified Playwright?

**Comment by lucasbit** [comment]
I was running tests locally using Playwright VSC extension. However, I have restated PC after night and cannot reproduce issue anymore. It seems that PC restart solved issue. I will close issue.
