### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Durukpandit** [microsoft/playwright#19117]
I'm trying to automate the download of a PDF file using Playwright, if I click on the link then a new tab opens as a pdf viewer, I am trying to download the pdf by clicking over the link. Just like the selenium plugin works,I have the solution of this using js but i want solution using python.
Please somebody help me.

**Comment by pavelfeldman** [comment]
You can read this for PDF scraping: https://github.com/microsoft/playwright/issues/6342#issuecomment-929112605
