### ISSUE TITLE
[Question] print console.log  on terminal when running test from vscode extension

### ISSUE THREAD

**Issue by inqom-circle** [microsoft/playwright#19111]
Hello,
Is there a way to print the console.log on the terminal when I'm running my test from the playwright vscode extension.
Best.

**Comment by ambiguous48** [comment]
Do your logs not show when you click the `show output` button?

https://user-images.githubusercontent.com/17984549/131338744-2bf71d20-79b4-48f2-94dd-9c945c34fae1.png

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
