### ISSUE TITLE
[BUG] Playwright Test for VSCode: No tests have been found in this workspace yet

### ISSUE THREAD

**Issue by jimpriest** [microsoft/playwright#19123]
**Context:**

## System:
 - OS: Linux 6.0 Pop!_OS 22.04 LTS
 - Memory: 12.11 GB / 31.08 GB
 - Container: Yes
## Binaries:
 - Node: 16.13.2 - ~/.nvm/versions/node/v16.13.2/bin/node
 - npm: 9.1.2 - ~/.nvm/versions/node/v16.13.2/bin/npm
## Languages:
 - Bash: 5.1.16 - /usr/bin/bash
## npmPackages:
 - playwright: ^1.24.1 => 1.28.1 
## VSCode
 - Version: 1.73.1

Installed the latest Playwright Test for VSCode v1.0.1 from extensions.

Click on Test icon I get "No tests have been found in this workspace yet"

There was a previous ticket open for this which has been closed but with no obvious solutions to fixing this issue:  https://github.com/microsoft/playwright/issues/16982

I've tried everything in that issue with no success :(

**Comment by pavelfeldman** [comment]
Does "Developer: Reload Window" action fix the problem? Could you specify other extensions installed on your system?

**Comment by jimpriest** [comment]
Disabled all my extensions except for the Playwright one and ran Reload Window - didn't change anything.  I will try setting up the sample tests in a different directory to see if that works.  Then maybe I can diff the config files maybe and figure out what is breaking things.

**Comment by keshavjha06** [comment]
@pavelfeldman I'm facing the same issue in playwright => 1.28.1.Reload window is also not working.

**Comment by pavelfeldman** [comment]
I've tested all kinds of scenarios and they all work for me. Could you tell me more about the location of your tests?

**Comment by jimpriest** [comment]
Weird.  In both scenarios - my tests, and the Playwright example tests I use the same testDir path.  Could it be because I'm on Linux? 

```
testDir: './tests' 
```

**Comment by pavelfeldman** [comment]
Yeah, I'm also using Ubuntu workstation. There are people reporting it on macOS, but I tested there and it works fine.

I was wondering if the absolute path was including node_modules or something like that that was falling into the default filters. ./tests does not help me much.

**Comment by pavelfeldman** [comment]
If there is someone on the US time who is experiencing the issue and ready to do a screencast with me, please let me know!

**Comment by jimpriest** [comment]
I can't do it today but could do something tomorrow around this time if that works?

**Comment by jimpriest** [comment]
I should have some availability today after 4:30pm EST.  What's the best way to connect?

**Comment by pavelfeldman** [comment]
If you could ping me on our Slack I can try catching you online!

**Comment by pavelfeldman** [comment]
Folding it into https://github.com/microsoft/playwright/issues/18954

**Comment by qwertie** [comment]
I have the same problem, except Playwright Test for VSCode 1.0.9 used to work and then simply stopped working one day (right after installing some Python-related extensions; disabling them didn't help). VS Code info:

~~~
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z (2 wks ago)
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
~~~

**Comment by mxschmitt** [comment]
Make sure to use up2date Playwright inside your package.json and re-run npm install.

**Comment by adityasuman100** [comment]
```json
  "description": "",
  "main": "index.js",
  "type": "module",
```

removing this `"type": "module",` from my `package.json` file worked for me
