### ISSUE TITLE
[Question] How to close an instance and open a new one without stopping the for? Firefox Open 2 tabs

### ISSUE THREAD

**Issue by sansepion** [microsoft/playwright#19128]
I have 10 different profiles in the temp folder. I would like that every 5 searches it would close the current browser, change the instance variable and open a different instance without breaking the for of the list of products.

Another error I'm having is that it's opening two Firefox tabs.

```
import time
from playwright.sync_api import sync_playwright
import os

instance = '01'
user_dir = f'/tmp/playwright{instance}'
count = 0

amazonsearch = '#twotabsearchtextbox'
firts = '#search > div.s-desktop-width-max.s-desktop-content.s-opposite-dir.s-wide-grid-style.sg-row > div.sg-col-20-of-24.s-matching-dir.sg-col-16-of-20.sg-col.sg-col-8-of-12.sg-col-12-of-16 > div > span.rush-component.s-latency-cf-section > div.s-main-slot.s-result-list.s-search-results.sg-row > div:nth-child(2) > div > div'
price = '#renewedBuyBoxPrice'

if not os.path.exists(user_dir):
    os.makedirs(user_dir)

def navegadorAuth():
    global page, browser

    browser = sync_playwright().start().firefox.launch_persistent_context(
        user_dir, 
        headless=False)
    page = browser.new_page()
    page.goto('https://www.amazon.com/')
    page.locator(amazonsearch).fill(products)

list = open(f"products.txt", "r").readlines()

navegadorAuth()

for products in list:
    count += 1
    try:
        page.keyboard.press("Enter")
        time.sleep(10)
        page.locator(f'text={products}').click
        page.locator(price).inner_html
        url = page.frame.url
        print(price, url)


        if count == 5:
            instance += 1
            browser.close()
            navegadorAuth()
            count = 0
            if instance == 10:
                break
            else:
                continue

    except:
        print('Erro search')
        break
```

**Comment by dgozman** [comment]
@sansepion Unfortunately, I don't really understand what you are asking for.

> I have 10 different profiles in the temp folder. I would like that every 5 searches it would close the current browser, change the instance variable and open a different instance without breaking the for of the list of products.

It looks like your snippet does exactly that? Could you be more specific in what's going wrong?

**Comment by sansepion** [comment]
```
Traceback (most recent call last):
  File "PycharmProjects\pythonProject4\venv\py.py", line 36, in <module>
    navegadorAuth()
  File "pythonProject4\venv\py.py", line 23, in navegadorAuth
    browser = sync_playwright().start().firefox.launch_persistent_context(
  File "site-packages\playwright\sync_api\_context_manager.py", line 95, in start
    return self.__enter__()
  File "pythonProject4\venv\lib\site-packages\playwright\sync_api\_context_manager.py", line 44, in __enter__
    raise Error(
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by sansepion** [comment]
> @sansepion Unfortunately, I don't really understand what you are asking for.
> 
> > I have 10 different profiles in the temp folder. I would like that every 5 searches it would close the current browser, change the instance variable and open a different instance without breaking the for of the list of products.
> 
> It looks like your snippet does exactly that? Could you be more specific in what's going wrong?



> @sansepion Unfortunately, I don't really understand what you are asking for.
> 
> > I have 10 different profiles in the temp folder. I would like that every 5 searches it would close the current browser, change the instance variable and open a different instance without breaking the for of the list of products.
> 
> It looks like your snippet does exactly that? Could you be more specific in what's going wrong?

```
Traceback (most recent call last):
  File "PycharmProjects\pythonProject4\venv\py.py", line 36, in <module>
    navegadorAuth()
  File "pythonProject4\venv\py.py", line 23, in navegadorAuth
    browser = sync_playwright().start().firefox.launch_persistent_context(
  File "site-packages\playwright\sync_api\_context_manager.py", line 95, in start
    return self.__enter__()
  File "pythonProject4\venv\lib\site-packages\playwright\sync_api\_context_manager.py", line 44, in __enter__
    raise Error(
playwright._impl._api_types.Error: It looks like you are using Playwright Sync API inside the asyncio loop.
Please use the Async API instead.
```

**Comment by dgozman** [comment]
I think I now understand the issue. Don't call `sync_playwright().start()` every time. Instead, use the `with` block:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    # all your script goes here, including "def navegadorAuth():" and everything else

    # when you need to launch firefox
    browser = p.firefox.launch_persistent_context(user_dir, headless=False)
```

**Comment by sansepion** [comment]
It still shows an error, the solution you presented closes the browser every FOR, I need it to remain open, and when I tell it to close, it will close and open the other instance.

`sys:1: RuntimeWarning: coroutine 'BrowserContext.new_page' was never awaited
`

> I think I now understand the issue. Don't call `sync_playwright().start()` every time. Instead, use the `with` block:
> 
> ```python
> from playwright.sync_api import sync_playwright
> 
> with sync_playwright() as p:
>     # all your script goes here, including "def navegadorAuth():" and everything else
> 
>     # when you need to launch firefox
>     browser = p.firefox.launch_persistent_context(user_dir, headless=False)
> ```

It still shows an error, the solution you presented closes the browser every FOR, I need it to remain open, and when I tell it to close, it will close and open the other instance.

`sys:1: RuntimeWarning: coroutine 'BrowserContext.new_page' was never awaited
`

**Comment by mxschmitt** [comment]
Some hints to make it work like:

1. never use `list` as a variable name, `list` is a built-in function in python
2. start playwright only a single time, not for every test
3. never use time.sleep always page.wait_for_timeout
4. launch_persistent_context gives you a context not a browser
5. you did not click the product text, method calls need "()" at the end
6. you did for products in products but it should be for product in products

after applying it looks like this:

```python
from playwright.sync_api import sync_playwright
import os

instance = '01'
user_dir = f'/tmp/playwright{instance}'
count = 0

playwright = sync_playwright().start()

amazonsearch = '#twotabsearchtextbox'
firts = '#search > div.s-desktop-width-max.s-desktop-content.s-opposite-dir.s-wide-grid-style.sg-row > div.sg-col-20-of-24.s-matching-dir.sg-col-16-of-20.sg-col.sg-col-8-of-12.sg-col-12-of-16 > div > span.rush-component.s-latency-cf-section > div.s-main-slot.s-result-list.s-search-results.sg-row > div:nth-child(2) > div > div'
price = '#renewedBuyBoxPrice'

if not os.path.exists(user_dir):
    os.makedirs(user_dir)

def navegadorAuth():
    global page, context

    context = playwright.firefox.launch_persistent_context(
        user_dir, 
        headless=False)
    page = context.new_page()
    page.goto('https://www.amazon.com/')

products = open(f"products.txt", "r").readlines()

navegadorAuth()

for product in products:
    count += 1
    try:
        page.locator(amazonsearch).fill(product)
        page.keyboard.press("Enter")
        page.wait_for_timeout(10_000)
        page.get_by_text(product).first.click()
        print(page.locator(price).inner_text(), page.frame.url)


        if count == 5:
            instance += 1
            context.close()
            navegadorAuth()
            count = 0
            if instance == 10:
                break
            else:
                continue

    except Exception as e:
        print('Erro search')
        break
```

We unfortunately can't spend more time on it, since this is not end-to-end testing related I'm closing it for now.
