### ISSUE TITLE
[BUG] deviceScaleFactor not setting devicePixelRation properly

### ISSUE THREAD

**Issue by joshmar** [microsoft/playwright#19122]
**Context:**
- Playwright Version: 1.28.0 (latest)
- Operating System: Windows 11
- .NET version: .NET 7
- Browser: All

**Code Snippet**
[Devices](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json)
(I'm not sure if the same file is used in the playwright-dotnet repo, so I'm just assuming here)

```json
{ 
  "Galaxy S9+": {      
    "userAgent": "Mozilla/5.0 (Linux; Android 8.0.0; SM-G965U Build/R16NW) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.5359.48 Mobile Safari/537.36",
    "viewport": {
      "width": 320,
      "height": 658
    },
    "deviceScaleFactor": 4.5,
    "isMobile": true,
    "hasTouch": true,
    "defaultBrowserType": "chromium"
  }
}

```

```js

window.devicePixelRatio
// in console the output = 1 

```

```pwsh

pwsh playwright.ps1 codegen --browser "chromium" --target "csharp-nunit" --device "Galaxy S9+" playwright.dev

```

**Describe the bug**

I found that no matter which device I pick - even though the devices JSON states `"deviceScaleFactor": 4.5` - the DPR stays 1 exactly.

**Comment by dgozman** [comment]
@joshmar This is codegen-specific trade-off, where we set `deviceScaleFactor` to 1 or 2, assuming high-dpi on macOS, for things to look nice and sharp. When specifying `Galaxy S9+` in the test, I get `window.devicePixelRatio === 4.5`.

Let me know if this helps.
