### ISSUE TITLE
[Question] Is it possible to get the intrinsic value of an image?

### ISSUE THREAD

**Issue by agustinmme** [microsoft/playwright#19124]
Hello,

I am wondering if it is possible to get the intrinsic value of an image.

I'm trying to evaluate if the values being downloaded are the same as being rendered. To do this I compare the width with
  "natural width".

The width can be easily obtained with offsetWidth, getBoundingClientRect or boundingbox.

But the problem is with the intrinsic value, the only way I found is using "naturalWidth" but
they usually give the value of the viewport.

For example:
 
![image](https://user-images.githubusercontent.com/76716674/204372353-8fffc2bd-4e27-48f2-8158-caadcad2f07b.png)

![image](https://user-images.githubusercontent.com/76716674/204372927-49818ce6-b674-4be9-97fa-afcf36111014.png)

There's another way?

Thank you

**Comment by pavelfeldman** [comment]
> But the problem is with the intrinsic value, the only way I found is using "naturalWidth" but
they usually give the value of the viewport.

Could you elaborate on this? It sounds like naturalWidth is exactly what you need, what do you mean by "they usually give the value of the viewport"?

**Comment by agustinmme** [comment]
It works if you navigate to the Resizer url, but if you are on the page it doesn't work.

I give you an example so you can see

https://www.lanacion.com.ar/politica/el-juez-martin-cormick-anulo-la-designacion-de-la-radical-roxana-reyes-en-el-consejo-de-la-nid28112022/

https://www.lanacion.com.ar/resizer/uMlfIEtNpwcJuQG7njW3aq4L-Gs=/1200x800/smart/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar /CW3LNO5HIRHZFHHUTIN4HAPCQM.JPG

**Comment by agustinmme** [comment]
This is another example where it just prints the device viewport values

![image](https://user-images.githubusercontent.com/76716674/204384084-bfa97bf7-3f23-4e85-a56f-b5ee4b64ed18.png)

```
const images = await page.$$('img.com-image');
  for (const image of images) {
    const width = await image.getProperty('offsetWidth');
    const naturalWidth = await image.getProperty('naturalWidth');
    console.log(naturalWidth+' naturalwidth')
    
    const srcCurrent = (await image.getProperty('currentSrc'))['_preview']
      .match(/\/[0-9]{1,4}x[0-9]{1,4}\//g)[0]
      .split('x')[0]
      .slice(1);
      console.log(srcCurrent+' srcCurrent')
    }
```



It works but for this case but I am dependent on the url of resizer.

**Comment by pavelfeldman** [comment]
I see what you are saying, an example would be here:
```
data:text/html,<img src="https://www.lanacion.com.ar/resizer/Tplj6_zsZ58C62VJeJs3tk88PaU=/309x206/smart/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/CW3LNO5HIRHZFHHUTIN4HAPCQM.JPG" srcset="https://www.lanacion.com.ar/resizer/uMlfIEtNpwcJuQG7njW3aq4L-Gs=/1200x800/smart/filters:format(webp):quality(80)/cloudfront-us-east-1.images.arcpublishing.com/lanacionar/CW3LNO5HIRHZFHHUTIN4HAPCQM.JPG 1200w">
```

We only expose browser capabilities here, so there is nothing extra that Playwrght can do. Note that browsers don't have consistent behavior here as well (Safari does not return the viewport size, only Chrome and Firefox do).

**Comment by agustinmme** [comment]
Ok thanks for the info, I'll go the only way.
