### ISSUE TITLE
[BUG] Unselectable "input" element

### ISSUE THREAD

**Issue by quidnu** [microsoft/playwright#19121]
**Context:**
- Playwright Version: 1.28
- Operating System: Ubuntu 22.10
- Python version: 3.9
- Browser: Chromium

**Describe the bug**

I have a dynamically loaded "<input type='tel'>" input field that I cannot seem to select (hangs on "waiting for locator"). When I put a page.pause() before the locator command and inspector launches it highlights the field with the locator expression. Timing doesn't seem to be the problem: I've put in waits for dom, timeout, networkidle and have just waited in the inspector. I've also put a breakpoint in python and tried selecting using query_selector which doesn't return anything.

Are there some elements which are not selectable (but would still be highlighted in the inspector)?

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
