### ISSUE TITLE
[Question]: witch xpath version playwright supports?

### ISSUE THREAD

**Issue by brzssh** [microsoft/playwright#19120]
### Your question

im trying to use xpath 2.0 features such lower-case and matches
but getting invalid xpath error 
```
waiting for selector "//*[lower-case(@data-table-column-id)='specInfo.fileName']"
  Failed to execute 'evaluate' on 'Document': The string './/*[lower-case(@data-table-column-id)='specInfo.fileName']' is not a valid XPath expression.
```

```
waiting for selector "//*[matches(@data-table-column-id,'specInfo.fileName','i')]"
  Failed to execute 'evaluate' on 'Document': The string './/*[matches(@data-table-column-id,'specInfo.fileName','i')]' is not a valid XPath expression.
```

**Comment by angelo-loria** [comment]
I believe this is a browser issue unrelated to Playwright. Most (all?) modern browsers do not support xpath 2.0- https://stackoverflow.com/questions/65271107/why-modern-browser-engines-do-not-support-xpath-2-0

You're better off using a [different Locator](https://playwright.dev/docs/locators) over xpath with Playwright

**Comment by pavelfeldman** [comment]
As per above, we use Browser's xpath engine for xpath selectors, but you should use high level locators instead.

**Comment by DetachHead** [comment]
you can use my [`playwright-xpath`](https://www.npmjs.com/package/playwright-xpath) selector engine which supports up to xpath 3.1
