### ISSUE TITLE
[Question] using regex with toHaveAttribute

### ISSUE THREAD

**Issue by michelle-choi1** [microsoft/playwright#19135]
Hi, I have a test here where I'm trying to use regex to verify that there is any kind of url starting with `https://` in the `src` attribute. For some reason, the regex I have here - verified through https://regexr.com/ - doesn't work even though I've used regex here and there in other tests. Is this possibly an issue with `toHaveAttribute`?

```js
test.beforeEach(async ({ page }) => {
    await page.goto('/');
});

test.only('Splash appears', async ({ page }) => {
    await page.waitForSelector('.hero img');
    await expect(page.locator('.hero img')).toBeVisible();
    await expect(page.locator('.hero img')).toHaveAttribute('src', /(https://).*/);
});
```

When I run this, the error message I get is:
```
Error: .../playwright-tests/live-tests/splash.spec.js: Unexpected token (12:77)

  10 |     await page.waitForSelector('.hero img');
  11 |     await expect(page.locator('.hero img')).toBeVisible();
> 12 |     await expect(page.locator('.hero img')).toHaveAttribute('src', /(https://).*/);
     |                                                                              ^
  13 | });
  14 |
```

I've also tried putting quotes around it, escaping any of the slashes, and various things because I'm not all that familiar with regex, but none of them seem to work.

Thanks for your time!!

**Comment by angelo-loria** [comment]
try escaping the forward slashes after the colon

`/(https:\/\/).*/`

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by michelle-choi1** [comment]
oops, thanks @angelo-loria that was it!! thanks @pavelfeldman!
