### ISSUE TITLE
[BUG] Tests fail when testing a vue.js front-end while a node.js back-end is inside a docker container.

### ISSUE THREAD

**Issue by cardinal-II** [microsoft/playwright#19136]
**Context:**
- Playwright Version: 1.28.1
- Testing with Mocha/Chai
- Operating System: Kubuntu 20.04/64-bit
- Node.js version: 16.18.1
- Browser: Chromium
- Docker: 4.14.1
- Image for testing: mcr.microsoft.com/playwright:latest
- Image for Node.js: node:16

**Describe the bug**

The app consists of three layer: 
- Vue.js for front-end, 
- Node.js for back-end (API), 
- Postgresql for db. 

Each of the layers sits in its own docker container on my laptop. Everything works when I manually test, but automated tests with Playwright fail. When I take the back-end out of its container and run it locally (while the other two layers run in containers), the automated tests pass.

Some test cases pass, some don't. Tests that are longer than 6 sec, fail. Sometimes Playwright can't find a locator, sometimes it finds the locator but with empty innerText instead of with some text.

```
page.innerText: Timeout 15000ms exceeded.

=========================== logs ===========================

waiting for locator('data-test-id=tournament_id')
```

Did anyone face this? How to overcome it?

**Comment by pavelfeldman** [comment]
As long as things run successfully when ran locally, you should be looking into the container-related issues. If things don't work locally, please provide a repro script we could run to look into your problem.

**Comment by mxschmitt** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
