### ISSUE TITLE
[BUG] incorrect data returned by page.frames().size

### ISSUE THREAD

**Issue by vladibelsublightapi** [microsoft/playwright#19137]
**Context:**
- Playwright Version:1.23.0
- Operating System: Windows
- Browser: All
- Language: Kotlin (playwright Java)

Hey,
Recently I noticed that some actions like `page.frames().size` result in a value that is not the actual value as expected.

only when I perform some "fake" actions like key-press, the actual value of `page.frames().size` return with the real number.

**Failure Test ❌**
```kotlin
    @Test
    fun `playwright bug`() {
        runBlocking {
            page.navigate(server.EMPTY_PAGE)
            val frame = addNewFrame()
            assertEquals(2,page.frames().size)
            page.evaluate("() => setTimeout(() => document.querySelector('#frame1').remove(), 2000)")
            delay(3000)
            assertEquals(1,page.frames().size)
        }
    }
```
*result*
```java
org.opentest4j.AssertionFailedError: 
Expected :1
Actual   :2
```
**Success Test ✔️**
```kotlin
    @Test
    fun `playwright bug`() {
        runBlocking {
            page.navigate(server.EMPTY_PAGE)
            val frame = addNewFrame()
            assertEquals(2,page.frames().size)
            page.evaluate("() => setTimeout(() => document.querySelector('#frame1').remove(), 2000)")
            delay(3000)
            page.keyboard().press("Tab")
            assertEquals(1,page.frames().size)
        }
    }
```
*result*
```java
Tests passed: 1
```

Is it related to the fact that some methods don't "read" the actual state of the DOM, but uses some sort of cached information?
Is there a more elegant way to "refresh" the state rather than performing fake actions like key press?

I would appreciate your help, thanks 🙏

**Comment by pavelfeldman** [comment]
Java is a blocking API, when you block the thread with delay, nothing happens. You should replace it with `page.waitForTimeout(3000)`

**Comment by vladibelsublightapi** [comment]
Thanks, Pavel!

**Comment by mxschmitt** [comment]
Looks like its answered, closing for now.
