### ISSUE TITLE
[BUG] Playwright test runner always show test result pass when working with websocket (ws or sockiet io client)

### ISSUE THREAD

**Issue by cuongld2** [microsoft/playwright#19131]
**Context:**
- Playwright Version:"^1.27.1"
- Operating System: Linux (Ubuntu 22.04)
- Node.js version: v18.2.1
- Browser: request (API testing)
- Extra: "socket.io": "^4.5.4","socket.io-client": "^4.5.4", "ws": "^8.11.0"

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
test(`check websocket available`, async({}) => {

    const ws = new WebSocket(`${endpoint.WEBSOCKET_HOST}/notification/inapp/register`,{
        headers: {
          Cookie: `token=1${accessToken}`
        }
    });
    ws.on('open', function (){
        ws.send("say Donnnnnnnnnnn") 
    });

})
```

**Describe the bug**

When running the test, even inputting an invalid value into the cookie field, Playwright still shows the test result as pass.
I checked with socket io client also, but still the result is pass.
I guess there's something wrong with Playwright test runner when working with WebSocket client.

![image](https://user-images.githubusercontent.com/42601985/204533275-e9246e86-dd6d-4ed5-b0a1-c2cc79a64397.png)

**Comment by dgozman** [comment]
@cuongld2 I think this test just finishes too fast, before the websocket has a chance to connect. Note that `ws.on('open', ...)` does not actually wait for the websocket to open. You have to `await` something to make the test function actually wait.

**Comment by cuongld2** [comment]
Oh, I tried with jest test runner with the same code, jest is able to spot the exception.

![image](https://user-images.githubusercontent.com/42601985/204700158-ecf66fde-c989-4359-99a0-cd62455d89ba.png)

```typescript
describe('test websocket', () => {
  test('websocket connection', async () => {
    const ws = new WebSocket('wss://dev.vinlab.io/notification/inapp/register',{
        headers: {
          Cookie: 'token=11eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2UVI5d0loWGFmSFJTbklRaFFRRjIwRDFyUE5CQndXdE5kOE5vaHdmVFlVIn0.eyJleHAiOjE2Njk4MTMyMTUsImlhdCI6MTY2OTc3NzIxNSwianRpIjoiNWI1NTQ5NDQtYTQ3Mi00YzY2LTk1MWEtZTBhOTFiMzZmODZjIiwiaXNzIjoiaHR0cHM6Ly9kZXYudmlubGFiLmlvL2F1dGgvcmVhbG1zL3ZpbmxhYiIsImF1ZCI6WyJ2aW5sYWIiLCJ2aW5sYWItYmFja2VuZCIsImFjY291bnQiXSwic3ViIjoiM2FiYmFkMDItYjljOC00ODUwLTkzZmUtOGFlMGJiNjgyZWUyIiwidHlwIjoiQmVhcmVyIiwiYXpwIjoidmlubGFiLWZyb250ZW5kIiwic2Vzc2lvbl9zdGF0ZSI6IjViY2RlMDlhLWE1YTgtNDhiNi04NGYxLTFlMTEzMDg3YTZmOCIsImFjciI6IjEiLCJyZWFsbV9hY2Nlc3MiOnsicm9sZXMiOlsiVEVBTV9BRE1JTiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoidmlubGFiIHByb2ZpbGUgZW1haWwiLCJyZWFsbV9yb2xlcyI6WyJURUFNX0FETUlOIl0sImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwibmFtZSI6IkxlIERpbmggIEN1b25nIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidi5jdW9uZ2xkOSIsImdpdmVuX25hbWUiOiJMZSBEaW5oICIsImZhbWlseV9uYW1lIjoiQ3VvbmcifQ.aOCIYNkASnUQrr2Jj2XYtE8oTCHc4sDHcUEVR33SxXlJ1bNG1bfOpy3b9AHPoDOrT8DEPMb0he3UEHrvFs6teRb9vPB880zZJBvJwvZV2pBfghSKccQ7E07o6vZRuW7V0_FQTmXbdI3FW41xL3LYRGQTCZpixiD1fMnpiufUta0WBT8yKqlj-1tjxMJkl30o_-IpizWM6MVLrIhTg0iAXi3ZnvS5GZscvqSB7FgDNvLcMmesuWKu4PFqfFFDIWCkHHUAfVxYw2Lr71g9jFVQvD-HxMdoz08imHrDzWVFO0UiP9VwYmsDvRzJRDMkwkQgWWS_UTjKLhGElWKP2psStA'
        }
    });
    
    ws.on('open', function open() {
        ws.send("say something")
        ws.terminate()
    });

// create instance of WebSocket connection
// const wsp = new WebSocketAsPromised('wss://dev.vinlab.io/notification/inapp/register');

// // wait for WebSocket connection to open
// await wsp.open();

// // send some data
// wsp.send('data');

// // wait for connection to close
// await wsp.close();

  });
});
```

**Comment by dgozman** [comment]
@cuongld2 That's probably because Jest does not exit fast enough for the websocket error to be thrown. Most likely Jest will wait for the open socket connection to close before exiting, but Playwright won't do that. I'd recommend to await things, for example:

```ts
  test('websocket connection', async () => {
    await new Promise(done => {
      const ws = new WebSocket('wss://domain/inapp/register', {
        headers: {
          Cookie: 'token=11',
        }
      });

      ws.on('open', function open() {
          ws.send("say something")
          ws.terminate()
          done()
      });
    });
  });

```

**Comment by mxschmitt** [comment]
Closing as per above, since this is not a Playwright issue, you need to await for the WS to connect.

**Comment by cuongld2** [comment]
Thank you guys,
Works like a charm.
