### ISSUE TITLE
Playwright Typescript Monorepo JSX issue

### ISSUE THREAD

**Issue by rubber-duck-software** [microsoft/playwright#19142]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac
- Node.js version: v16.16.0
- Browser: All
- Extra: Typescript Monorepo

**Code Snippet**

Here is an example repo which demonstrates the issue 
https://github.com/rubber-duck-software/playwright-typescript-monorepo-tsx

**Describe the bug**

This is a followup to #17964. Playwright can now do the jsx transform in general, but it cannot handle jsx fragments. As far as I can tell `babel-plugin-syntax-jsx` does support fragments, so I am not sure about the underlying cause of this issue.

**Comment by pavelfeldman** [comment]
Could you provide steps to initialize your repo? (I don't use pnpm). I can't see where you are specifying base/paths for common in any of the tsconfigs.

**Comment by rubber-duck-software** [comment]
Hi @pavelfeldman ! Thanks for getting back to me so quickly.

I have adapted the example repository to use `npm` instead of `pnpm`. 

As for the tsconfigs, the tsconfig inside of `common` is written by me, but the tsconfig inside of `site` is the default tsconfig generated by `pnpm create vite`. However, it is unnecessary to provide the base/paths for common inside of the tsconfig for site. common is treated like any other package and so its type definitions are found by tsc.

**Comment by mxschmitt** [comment]
Looks like we would have to add https://babeljs.io/docs/en/babel-plugin-transform-react-jsx to support fragments in JSX and TSX. As of today they both error out.
