### ISSUE TITLE
[Question] Does test.skip() cancel retries?

### ISSUE THREAD

**Issue by agusjacob** [microsoft/playwright#19140]
Hi everyone!
I have a scenario in which if a condition is met, I skip the test using 
`test.skip(condition, 'description')`

Does this behavior skip future retries? Because when my test runs in the pipeline, I'm noticing it is running more than once even though it's skipped. 

Thanks!

**Comment by dgozman** [comment]
@agusjacob `test.skip()` does skip the retries. Although, if your condition is `false` for the first time and `true` for the second time, the original run will not be skipped and may fail causing a retry. Does that make sense?

**Comment by agusjacob** [comment]
I'm going to try to get evidence from the issue I'm having then, and will come back soon. Thanks!
