### ISSUE TITLE
Playwright: Roadmap

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#1914]
**Focus**

- **screencast**: Screen video recording is crucial when it comes to debugging CI failures :fire:
- **performance**: there are multiple requests from developers that want to test performance of automation scenarios across browsers :fire:
- **persistence**: persist browser context state :fire:
- **upstream**: (ongoing) upstream local changes to WebKit :construction_worker:
- **upstream**: (ongoing) upstream local changes to Firefox :construction_worker:

----

**Collect feedback**

- **serviceworkers**: Support for service worker testing
- **touch**: touch event support
- **drag**: Drag'n'drop support
- **httpproxy**: First-class citizen support for http proxy
- **cert**: Support for client certificate
- **electron**: Support for electron

**Comment by roughsoft** [comment]
No.1 and No.4

**Comment by roughsoft** [comment]
7.Playwright Grid for the test excution,the same as .....

**Comment by osmenia** [comment]
> 7.Playwright Grid for the test excution,the same as .....

+1

**Comment by shirshak55** [comment]
how httpproxy is going to be implemented? Will browser be patched to support it or it will be done from node side?

**Comment by k15a** [comment]
> screencast: Screen video recording is crucial when it comes to debugging CI failures 🔥

It would be great to add Playwright API calls as captions to the video, so it's easier to figure out what interaction did break a test.

For example:
```js
const browser = await chromium.launch()
const page = await browser.newPage()
await page.startRecording()
await page.goto("https://google.com")
await page.waitForTimeout(1000)
await page.type("Hello world")
await page.waitForTimeout(1000)
await page.stopRecording()
await page.close()
```

It would be super nice to have the following caption in the video:
```
~0s: await page.goto("https://google.com")
~1s: await page.type("Hello world")
```

**Comment by ticxx** [comment]
I would love to see support for client certificates!

**Comment by gkushang** [comment]
👍   for the `drag n drop` & `performance` support

**Comment by ClestonRM** [comment]
Client Certificate would be great!

**Comment by bheemreddy181-zz** [comment]
Pact integration would be great https://github.com/microsoft/playwright/discussions/11168
