### ISSUE TITLE
[Documentation] There is a typo in the official documentation example.

### ISSUE THREAD

**Issue by blankoon** [microsoft/playwright#19159]
Hello!

I'm having fun using playwright these days.
Thanks for developing such a great tool!

I was currently looking for an official document to see if I could get an accurate report from CI/CD.
In the meantime, there is a typo in the example code, so I'm reporting it. 

You can check it out at the link below.

- AS-IS
```
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [['list', { printSteps: true }], // here!
};
export default config;
```
- TO-BE
```
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  reporter: [['list', { printSteps: true }]], // add `]` at the end
};
export default config;
```

**Comment by mxschmitt** [comment]
Thanks!

**Comment by Anatol-1990** [comment]
Hello, in my project printSteps: true doesn't seem to work. Could you please tell me, what I might be doing wrong? It acts the same as just ['list']

**Comment by blankoon** [comment]
> Hello, in my project `[ 'list', { printSteps: true }]` doesn't seem to work. Could you please tell me, what I might be doing wrong? It acts the same as just `['list']`

Can you try with `[[ 'list', { printSteps: true }]]`? not `[ 'list', { printSteps: true }]`

**Comment by Anatol-1990** [comment]
Hi, thanks. It didn't work out for me. Will try to open another issue
