### ISSUE TITLE
playwright: How to get Authorization: Bearer token and pass to request? 

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#1915]
Hi Team, 

I'm logged in to the web page, navigate to the destination web page and want to download a csv file with request.
The request headers include Authorization: "Bearer eyJ0eXAiOiJKV......"

is it possible to take Authorization: "Bearer Token" from playwright and submit it to request (eg axios).

Thnx a lot

**Comment by mxschmitt** [comment]
That does fully depend on how your application is structured. If the token is stored in the local storage or cookies, which is usually the case then you can simply grab it and make the the request with it either from the Node.js thread or from your browsers environment by using `page.evaluate`.

**Comment by osmenia** [comment]
> That does fully depend on how your application is structured. If the token is stored in the local storage or cookies, which is usually the case then you can simply grab it and make the the request with it either from the Node.js thread or from your browsers environment by using `page.evaluate`.

I tryed with 
 ```
 const cookies = await crContext.cookies();
  console.log(cookies);

```
Token is not stored in cookies. 

Then i tryed 

```
var accessTokenObj = await crPage.evaluate(() => {
      return localStorage;
    });
    console.log(accessTokenObj);
```

I want to see what is inside localStorage, output ist null 
(I am runing Playwriht incognito mode) 

do you have code example how to get token?

Thanks a lot for your help

**Comment by mxschmitt** [comment]
Is the application which you try to use public available? Otherwise its kinda hard for me to give you more input.

**Comment by osmenia** [comment]
> Is the application which you try to use public available? Otherwise its kinda hard for me to give you more input.

I sent you Email.

**Comment by osmenia** [comment]
> > Is the application which you try to use public available? Otherwise its kinda hard for me to give you more input.
> 
Thanks you very much for your help. 
I found token in Chrome LocalStorage (tnx for input)

i got token with function:

```
var accessTokenObj = await crPage.evaluate(() => {
      return localStorage.getItem("TokenName");
    });
    console.log(accessTokenObj);
```
I highly appreciate your help. 
Thank you very much Max!
