### ISSUE TITLE
[REGRESSION]: "Webpacking" Playwright no longer works in 1.28

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#19155]
**Context:**
- GOOD Playwright Version: 1.28.0-beta-1668203080000
- BAD Playwright Version: 1.28.0-beta-1668558158000
- Operating System: Windows
- Extra: Webpack5

**Code Snippet**

The following require statement in Playwright is confusing Webpack : 

`packages\playwright-core\src\server\electron\loader.ts`

```ts
const { app } = require('electron');
```

```
ERROR in ./node_modules/playwright-core/lib/server/electron/loader.js 21:4-23
Module not found: Error: Can't resolve 'electron' in '/__w/1/s/node_modules/playwright-core/lib/server/electron'
Did you mean './electron'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.
resolve 'electron' in '/__w/1/s/node_modules/playwright-core/lib/server/electron'
  Parsed request is a module
  using description file: /__w/1/s/node_modules/playwright-core/package.json (relative path: ./lib/server/electron)
    resolve as module
      /__w/1/s/node_modules/playwright-core/lib/server/electron/node_modules doesn't exist or is not a directory
...
```

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ... 
})();
```

**Describe the bug**

We are leveraging "Webpack" to make our tests portable in our CI/CD to eliminate the need for running dependency installation on our machines, with the latest version we see Webpack having problems finding "electorn" from Playwright as it is a devDepency. Currently we are trying to create a hack in webpack to make that dependency blank but would like to know if there is a bug in Playwright for this?

**Comment by mastrzyz** [comment]
We are using the Jest framework with Playwright so we just have each of our test file be an entrypoint : 

```js
  entry: {
    ...glob
      .sync(PROJECT_ROOT("/**/tests/**/*.ui.test.ts"))
      .reduce((acc, path) => {
        const baseDirPath = relative(PROJECT_ROOT(), dirname(path));
        let basePathName = basename(path);
        // Remove test file paths
        basePathName = basePathName.replace(/\.ui\.test\.ts/, ".ui.test");
        acc[`${baseDirPath}/${basePathName}`] = path;
        return acc;
      }, {}),
  },
```
This creates portable test files that we can just give to Jest directly.

Here is a snippet of our entire webpack configuration if that helps.

```js
module.exports = {
  stats: { warnings: false },
  entry: {
    ...glob
      .sync(PROJECT_ROOT("packages/experiences/**/tests/**/*.ui.test.ts"))
      .reduce((acc, path) => {
        const baseDirPath = relative(PROJECT_ROOT(), dirname(path));
        let basePathName = basename(path);
        // Remove test file paths
        basePathName = basePathName.replace(/\.ui\.test\.ts/, ".ui.test");
        acc[`${baseDirPath}/${basePathName}`] = path;
        return acc;
      }, {}),
  },
  resolve: {
    mainFields: ["main", "module"],
    extensions: [".js", ".ts"],
    modules: ["node_modules"],
  },

  module: {
    rules: [
      {
        test: /\.ts$/,
        use: [
          {
            loader: webpackHelper.findLoader("ts-loader"),
            options: {
              transpileOnly: true,
              allowTsInNodeModules: true,
              configFile: PROJECT_ROOT("tsconfig.webpack.json"),
            },
          },
        ],
        exclude: /node_modules/,
      },
      // No way to 'webpackify' this into a portable format
      // These are `post install` scripts and whatnot
      {
        test: /(LICENSE|\.d.ts|\.md|\.apk|\.png|\.sh|\.ps1|\.dmg|\.css|\.html|\.exe|\.ttf)$/,
        use: ["null-loader"],
      },
    ],
  },
  mode: "development",
  devtool: "source-map",
  node: {
    __dirname: false,
  },
  target: "node",
  output: {
    filename: "[name].ts",
    libraryTarget: "commonjs2",
    path: PROJECT_ROOT("test-portable"),
  },
  optimization: {
    minimizer: [
      new TerserWebpackPlugin({
        extractComments: false,
        parallel: true,
        terserOptions: {
          keep_classnames: true,
          keep_fnames: true,
          output: {
            comments: false,
          },
        },
        test: /\.m?(?:ts|js)(\?.*)?$/i,
        exclude: /\.d\.ts?$/i,
      }),
    ],
    splitChunks: {
      chunks: "all",
    },
  },
};
```

I am able to reproduce this locally if this helps.

**Comment by mastrzyz** [comment]
If I add a "blank" shim for electron, webpack is able to compile again.

```js
    alias: {
      electron: PROJECT_ROOT(
        "packages/utilities/shims/blankDependency.js"
      ),
    },
  },
```

**Comment by mxschmitt** [comment]
Playwright does not support being bundled with Webpack, randomly nulling out requires/imports is not an approach we recommend nor support. Playwright is dependency-free, so installation of it takes usually less than 5 seconds.

Thereby I'm closing it. Regarding the bisect range, thats the diff https://github.com/microsoft/playwright/compare/a7b2b04588390988df4ea18d5755dad84b02465b...b40d0d2d83b62dd0e71490510d84389ae5f6aa9a and its mostly _caused_ by dbf3fc50896494d13153e45d08b75deae43afd7c.

**Comment by mastrzyz** [comment]
@mxschmitt  Please re-consider.

We have machines running hundreds of shards and adding `git and `yarn` on them we found is very flaky. 

With webpack we have one dependency free `.js` file we can plug directly into `node`. This is a major blocker for us currently.

**Comment by PSoltes** [comment]
Just adding a note that might help someone. When using `serverless-bundle` with playwright, adding it as [external](https://www.npmjs.com/package/serverless-bundle) in its config works

**Comment by mxschmitt** [comment]
Marking it as external was also the trick which did it for mastrzyz, had a follow-up session with him, forgot to post an update here.
