### ISSUE TITLE
[Question]Can control playwright in electron?

### ISSUE THREAD

**Issue by keyiis** [microsoft/playwright#19157]
I want use playwright in electron app, my electron app has two windows, The A is main window, The B is controled by A window, Now I used playwright to control B window in main process, The code is as follows:
**Electron main process index.js**
```
import {ElectronApplication, Page, _electron} from 'playwright-core';
const electronApp:ElectronApplication,B_window:Page;
function openB(){
    electronApp = await _electron.launch({ args: ['./B_Win.js'] });
    B_window  = await electronApp.firstWindow();
}
```
**B_Win.js**
```
import * as path from "path";
import { BrowserWindow } from "electron";
(async () => {
    let win = new BrowserWindow({
        webPreferences: {
            preload: path.join(__dirname, '../preload/b.js')
        }
    });
    await win.loadURL("https://www.zhipin.com");
})();
```
Then the main window can be opened normally, but error occurred when execute `openB()` to open the b window in main process.
```
 [Error: Cannot find module './loader'
Require stack:
- D:\project\boss\electron\out\main\index.js
- D:\project\boss\electron\node_modules\electron\dist\resources\default_app.asar\main.js
- ]
```

**Comment by dgozman** [comment]
@keyiis You are not supposed to use playwright from inside electron. I'd recommend a separate script/test that will control both A and B, like in [this example](https://playwright.dev/docs/api/class-electron).

**Comment by keyiis** [comment]
@dgozman Thanks for your reply! If change the way, how can i control B window in main process, such as "click button" or "scroll page"?

**Comment by dgozman** [comment]
@keyiis You wouldn't be able to control window B from the main process. Playwright only provides a solution for testing from outside of the Electron application itself, not from inside of it.
