### ISSUE TITLE
[Feature] Expose outputDir in TestResult or TestCase so reporters can use it

### ISSUE THREAD

**Issue by berstend** [microsoft/playwright#19165]
Hey there, 

I have a use case where I want my custom test reporter to work with output files from the tests.

It is possible to use `testInfo.outputDir` in tests but it doesn't look like there's currently a way to access this test specific directory in a test reporter using either `TestResult` or `TestCase`. :-)

I'm currently about to vendor in the outputDir logic in my own code but that's not optimal:
https://github.com/microsoft/playwright/blob/307a0b6ea7508306dd99c5819c47a23081760531/packages/playwright-test/src/testInfo.ts#L113-L127

Thanks for all the great work!

**Comment by berstend** [comment]
In case anyone else has a need to access the outputDir of a test in a reporter, here's a quick/hackish way to "reverse" the path:

```ts

**Comment by berstend** [comment]
Ah, just stumbled on this (attaching test metadata through a test fixture) which is a much better interim fix:
https://github.com/microsoft/playwright/issues/12396#issuecomment-1090600247

**Comment by mxschmitt** [comment]
Looks like the issue is answered? The recommended approach is [TestInfo.attach()](https://playwright.dev/docs/api/class-testinfo#test-info-attach) to write and [TestResult.attachments](https://playwright.dev/docs/api/class-testresult#test-result-attachments) to read inside the reporter.

**Comment by berstend** [comment]
I noticed another hackfix I'll be using for now instead of `testInfo.outputDir`:

The unique test id (which is readily available in reporters) can be surfaced in fixtures:
```ts
((testInfo as any)._test as TestCase).id
```
With a shared test id available in tests + reporter I'm able to direct & reconcile log file output as well. :)

**Comment by aslushnikov** [comment]
> edit, the reason of wanting to pipe the stdio as it comes in:
I noticed occasional issues where result.stdout/result.stderr of tests would be empty in onEnd, typically when timeouts occurred. :)

@berstend This looks like something we can fix! Could you please file a separate bug report for us with a repro steps? Other than that, I believe this issue was addressed. Please don't hesitate to file new issues if you still think we can help somehow.
