### ISSUE TITLE
[BUG]Browser is picking window OS (AAD) login profile instead of Browser login or any specific user profile

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#19163]
**Context:**
- Playwright Version: [1.28.0]
- Operating System: [Mac]
- Maven project with JAVA
- Browser: [Chrome]
- Extra:
Describe the bug

We need to automate the testing of Internal Website which is SSO enabled. We see that PW starts the browser in incognito (which is our req. aswell) but the page loads using the current SSO user cred thus skipping the Login screen. 

 Not sure if the PW opened incognito is any difference in preference.

Please try this scenario in any of your MSFT internal app which will open Login screen when accessed through Incognito.

We are evaluating PW for our automation purpose and this is a blocker to get started as we have test users with different access roles which cannot be tested if we don't get the SSO Login screen. Happy to help you with any specific logs incase needed. Looking forward.

**Code Snippet**

  
  // Please include a snippet of HTML that shows an example of the content
  public static void main(String[] args) {
            try (Playwright playwright = Playwright.create()) {
                BrowserType chromium = playwright.chromium();
                BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
                launchOptions.setHeadless(false);
                Browser browser= chromium.launch(launchOptions.setChannel("chrome").setSlowMo(500));
                
                launchOptions.setArgs(Collections.singletonList("--auth-server-whitelist='_'"));

                BrowserContext browserContext=browser.newContext();
                Page page = browserContext.newPage();
                page.navigate(applicationurl);
                page.getByText("Sign in").click();

**Comment by mxschmitt** [comment]
This is most likely because you pick Google Chrome which is a branded browser where enterprise policies are applied (Microsoft Edge as well). What happens if you choose normal Chromium, without specifying a channel?

**Comment by mridiniveni** [comment]
Yes with Chromium  its working fine thanks for the response

**Comment by aslushnikov** [comment]
@mridiniveni  I'd recommend using Chromium to avoid enterprise policies affect testing.
