### ISSUE TITLE
[BUG][VSCode] Quitting chromium when paused crashes Playwright

### ISSUE THREAD

**Issue by cosmith** [microsoft/playwright#19168]
**Context:**
Playwright Version: 1.28.1
Operating System: Mac
Node.js version: 18.10
Visual Studio Code version: 1.73.1
Playwright for VSCode extension version: 1.0.1
Browser: Chromium

**Code Snippet**

```typescript
import {test} from "@playwright/test";

test("crash", async ({
    page,
}) => {
    await page.goto("https://www.google.com/");
    await page.pause();
});
```

**Describe the bug**

Reproduction steps:
- launch the test above in VSCode
- quit chromium
- you're now stuck: can't resume, can't stop the tests, can't launch new tests
- restarting VSCode is the only solution I found

**Comment by mxschmitt** [comment]
I can repro, thanks for the great bug report!

**Comment by pavelfeldman** [comment]
You can stop the test via pressing the "Stop" button labeled "Cancel test run" in the test explorer. You can use shortcut Cmd+; Cmd+X.
