### ISSUE TITLE
[BUG][VSCode] Page stuck on `about:blank` when recording at cursor

### ISSUE THREAD

**Issue by cosmith** [microsoft/playwright#19167]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac
- Node.js version: 18.10
- Visual Studio Code version: 1.73.1
- Playwright for VSCode extension version: 1.0.1
- Browser: Chromium

**Describe the bug**

When I click on "record at cursor" in one of my tests, the browser is opened but the page never loads. I'm stuck on `about:blank`.

https://user-images.githubusercontent.com/1194749/204802738-9e01e524-7776-4cc7-be3d-a5686c7a0618.mov

**Comment by dgozman** [comment]
@cosmith "Record at cursor" continues recording from the current state of the page. I'd recommend you to first run the test, so that page ends up in a state corresponding to the last line of the test, and only then use "record at cursor". Does that make sense?

**Comment by cosmith** [comment]
Hi, how is that supposed to work since the browser is closed at the end of the test? Should I use `await page.pause()`?

**Comment by cosmith** [comment]
Also the button "record at cursor" is grayed out while the test is running. There must be something I'm missing!

**Comment by Nav-2d** [comment]
In the video, I can see that you ran multiple-domain.spec.ts file. Can you show how the code looks like for that file?

It shouldn't close the browser unless you do something like context.close(); or etc.

**Comment by cosmith** [comment]
Here's the code for the test:

```typescript
import {test, expect, Page} from "@playwright/test";

import {createCarrier, login} from "../../lib/setup";

const replaceDate = async (page: Page, testId: string, date: string) => {
    await page.getByTestId(testId).click();
    await page.getByTestId(testId).fill(date);
    await page.keyboard.press("Enter");
};

test("multiple duplication modal", async ({page}) => {
    const credentials = await createCarrier();
    await login(page, credentials);
    await page.goto("/app/");
    await page.getByTestId("transport-row").first().click();
    await page.locator("h3", {hasText: "Transport n"});

    await page.getByTestId("transport-detail-duplicate").click();
    await page.getByTestId("multiple-duplication-button").click();

    await replaceDate(page, "begin-date-picker", "09/11/2022");
    await replaceDate(page, "end-date-picker", "11/11/2022");
    // when I set a begin date that's after the end date
    await replaceDate(page, "begin-date-picker", "15/11/2022");
    // then the end date is changed to the begin date
    await expect(page.getByTestId("end-date-picker")).toHaveValue("15/11/2022");

    // and when I set an end date that's before the begin date
    await replaceDate(page, "end-date-picker", "12/11/2022");
    // then the begin date is changed to the end date
    await expect(page.getByTestId("end-date-picker")).toHaveValue("12/11/2022");
});
```

I'm not sure it's linked to this specific test though. Here's a recording with a simple test:

```typescript
import {test, expect} from "@playwright/test";

test("test", async ({page}) => {
    await page.goto("https://playwright.dev/");
    await page.getByRole("link", {name: "Get started"}).click();
});
```

https://user-images.githubusercontent.com/1194749/205004047-f5b4551e-b65e-4386-97a4-962115918032.mov

**Comment by cosmith** [comment]
I setup a new project and indeed the browser stays open... Investigating

**Comment by dgozman** [comment]
@cosmith Great investigation! There is indeed a trace + show browser interoperability nuance, #19059 is already tracking that, so I'll close this issue. Thanks again for getting to the bottom of it.
