### ISSUE TITLE
[Question] Network throttling with Firefox and Webkit

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#19173]
Hi all,

I'm trying to simulate network speed in my tests for chromium, firefox and webkit. I saw in this issue https://github.com/microsoft/playwright/issues/15364 a way to do it with chromium based browser but what about Firefox and Webkit ?

Thank you !

**Comment by mxschmitt** [comment]
For Firefox and WebKit there are no ways to do it out of the box. What you can do instead as a workaround is to delay every http request coming from the page, it would look like this:

```js
await context.route('**/*', route => {
  await new Promise(resolve => setTimeout(resolve, 500));
  await route.continue();
});
```
