### ISSUE TITLE
In a table, if i do the horizontal scroll then only i can able identify the element hidden columns 

### ISSUE THREAD

**Issue by mvendhanbig** [microsoft/playwright#19174]
in our case, we have a table with 7column. if the website is launched we can able to see the 5cloumn. If I want to see the other 2cloumn I have to scroll down using a vertical scroll ball after that only we can able to see the horizontal scroll bar. Then we have to scroll right. we can able to see the other 2cloumns..

Do we have any method for this?
 i have used below code:
`const box = await scroll.boundingBox();`
    if (box) {
      const y = box.y;
      await page.mouse.wheel(0, y);
      await page.waitForTimeout(2000);
      await page.mouse.wheel(y, 0);
      await page.waitForTimeout(2000);
    }
this code is working but, do we have any other method to achieve above mention scenario

**Comment by ltsuda** [comment]
Just an idea here, if you have the correct selector for the Table or any row, maybe pressing the right arrow to scroll horizontally works.
Adding an await to the hidden columns to be visible in a loop with the right arrow press.

https://playwright.dev/docs/api/class-keyboard#keyboard-press

**Comment by mxschmitt** [comment]
Yes mouse wheel is recommended there but waitForTimeout is discouraged. We recommend `await yourLocator.waitFor()` instead which is more reliable.

**Comment by mvendhanbig** [comment]
can i use the above code

**Comment by mxschmitt** [comment]
Sure if it does work, its fine!

I'd recommend a small delay inside your while true loop tho.
