### ISSUE TITLE
[Question] Getting Syntax error while uploading .jpg file from work directory.

### ISSUE THREAD

**Issue by biswasritu6** [microsoft/playwright#19172]
Getting "SyntaxError: Invalid or unexpected token" while uploading a .jpg file from the working directory.
1. declared file path at the top. and passing the same file path inside setFiles . and its locating the file as well. but while running getting error.

 screenshot attached below of my code and error.
![Screenshot (929)](https://user-images.githubusercontent.com/86822634/204833711-155cbfc8-e90f-4e86-9568-af9f80c09a60.png)
![Screenshot (930)](https://user-images.githubusercontent.com/86822634/204833721-5facb8e2-4383-429c-ac1f-6d57ed3c45f8.png)

**Comment by mxschmitt** [comment]
This is not how it works, you don't require files, because Node.js can't handle them. You need to resolve file names to get file paths instead and pass them to the setFiles function. You can do this e.g. with

```js
import path from 'path';
const yourFileToUpload = path.join(__dirname, '../fileupload1/file1.jpg')
``` 

which makes it relative to the current file path.

**Comment by biswasritu6** [comment]
![Screenshot (931)](https://user-images.githubusercontent.com/86822634/204975608-1daa6f50-f29a-49b0-916d-cb064439a72a.png)
is it like this? 10th and 11th line

**Comment by mxschmitt** [comment]
Is there an error appearing? What does it mean that its not locating the file?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
