### ISSUE TITLE
[BUG] dragTo does not move item to target location

### ISSUE THREAD

**Issue by paweldeviniti** [microsoft/playwright#19171]
**Context:**
- Playwright Version: 1.24.2
- Operating System: Windows 11
- Node.js version: 16.16.0
- Browser: Chromium

**Describe the bug**

Method locator.dragTo does not work in our application. It catches the dragable object but it is not moved to target.

To reproduce please install [Dynamic Forms Cloud](https://marketplace.atlassian.com/apps/1210820/dynamic-forms-for-jira?tab=overview&hosting=cloud) on Jira cloud. App is free. 

1. When app is installed please click on get started 
![image](https://user-images.githubusercontent.com/119504955/204806232-a0904be9-348d-4596-a302-014c4cb67124.png)
2. On next page you will see dragable elements 
![image](https://user-images.githubusercontent.com/119504955/204812905-8b93a673-b091-472a-9fa4-ce07873f5d5d.png)
3. Try to use page.framelocator('[data-testid="hosted-resources-iframe"]').locator('[data-testid="issue-type-item"]', {hasText: 'Epic'}).dragoTo('[data-rbd-droppable-id="disabledIssueTypes"]')

Observed result: 
Element is yanked but it does not reach target destination.

**Comment by mxschmitt** [comment]
We unfortunately need a standalone repro for it, since we have no access to Jira. Otherwise we can't act on it.

Are you able to create a minimal repro out of it?

**Comment by paweldeviniti** [comment]
I have to check if we have any avalilable open environment for investigation. I'll inform you.
