### ISSUE TITLE
[Feature] Warn about getting close to timeouts + increase timeouts on retry

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#19196]
We have thousands of tests. Some of them takes more time than other ← thats also depends on 1) browser engine (webkit is the slowest) 2) available cpu on runner, which depends on the time of the day and many other stuff.

The problem: developer do some dev stuff, creates merge request, and get failed tests (say 100 tests). No way further to prod, you must fix failed test. Great solution here is _retries feature_, which allows you to get warns about flaky tests before too late. But not in the case of timeouts. If you run your CI in a bad day time, you have no chances to get green pipeline: each retry will fail because of timeouts.

What do you think about:

1. Allowing to configuring timeouts per browser? Looks like custom `project.use.timeout = ` does not work right now.
2. Allowing to increase timeouts, say +20%, for each retry? E.g. 30sec then 36sec then 43.2sec...
3. Generate median and average test time, and warn if it exceed some user defined value? I want to monitor the trend here.
4. Warn (in the report) about all stuff (navigations, expects, tests...) which exceed any timeout multiplied 0.8? So we can find problems before it hurts dev processes.

```
Warning! Some tests exceeds 80% of the timeout limit:
test1 in file ... 28 sec
test3 in file ... 27 sec

some navigations exceeds 80% of the navigationTimeout
line 2 in test4 in file ... 26 sec

etc
```

The main point of this issue is to split _developing process_ and _fixing-flaky-tests process_.

**Comment by Diokuz** [comment]
Actually, it could be done with fixtures on our side if you do this https://github.com/microsoft/playwright/issues/16250

**Comment by aslushnikov** [comment]
> 1. Allowing to configuring timeouts per browser? Looks like custom project.use.timeout = does not work right now.
> 2. Allowing to increase timeouts, say +20%, for each retry? E.g. 30sec then 36sec then 43.2sec...

@Diokuz you can implement these strategies yourself using the `test.setTimeout()` call. Many of these strategies are explained here: https://playwright.dev/docs/test-timeouts

```ts
const { test, expect } = require('@playwright/test');

test("test", async () => {
  test.setTimeout(100);
  /* ... */
});
```

> 3. Generate median and average test time, and warn if it exceed some user defined value? I want to monitor the trend here.

This should be easy with a simple custom test reporter. 

> 4. Warn (in the report) about all stuff (navigations, expects, tests...) which exceed any timeout multiplied 0.8? So we can find problems before it hurts dev processes.

This is there to some extend, in a form of a "slow tests" that are printed after test run.

**Comment by Diokuz** [comment]
> you can implement these strategies yourself using the test.setTimeout() call

@aslushnikov that is cool idea for "per browser" part of my issue, thank you!

But it wont work for "+20%, for each retry" (which is the primary problem for us) because we dont have an information wether a test running the first time, or as a retry. See https://github.com/microsoft/playwright/issues/16250 for more information.

> This is there to some extend, in a form of a "slow tests" that are printed after test run.

Not exactly. There are only slow test-files, not tests. That helps us to find test files with too many tests inside, but not really helps us to find too slow tests.
___

Probably this issue now boils down to two things:

1. What do you think about implementing https://github.com/microsoft/playwright/issues/16250 ?
2. Do you think a flaky tests problem could be a part of Playwright fundamentals? Or it is too high-level and too specific problem which should be solved on top of Playwright API by separate tools?

**Comment by Diokuz** [comment]
@aslushnikov  Wow, big thanks! Awesome!

https://playwright.dev/docs/api/class-testinfo#test-info-retry
