### ISSUE TITLE
[BUG] Call log can be verbose and contain redundant information for a simple component tests

### ISSUE THREAD

**Issue by pastelsky** [microsoft/playwright#19204]
**Context:**
- Playwright Version: 1.28
- Operating System:Mac
- Node.js version: 14.6
- Browser: All

**Describe the bug**
In a simple component test —
```ts
test(`foo`, async ({ mount, page }) => {
    const component = await mount(<Box />);
    await expect(component).toHaveScreenshot()  
})
```

If say, a failure occurs, the call logs get printed to the console are quite verbose — 

```
 Call log:
      - expect.toHaveScreenshot with timeout 5000ms
      -   verifying given screenshot expectation
      - waiting for locator('#root').locator('internal:control=component')
      -   locator resolved to visible <div id="root">…</div>
      - taking element screenshot
      -   disabled all CSS animations
      -   waiting for element to be visible and stable
      -   element is visible and stable
      - Expected an image 1280px by 771px, received 1280px by 776px. 
      - waiting 100ms before taking screenshot
      - waiting for locator('#root').locator('internal:control=component')
      -   locator resolved to visible <div id="root">…</div>
      - taking element screenshot
      -   disabled all CSS animations
      -   waiting for the element to be visible and stable
      -   element is visible and stable
      - captured a stable screenshot
      - Expected an image 1280px by 771px, received 1280px by 776px. 
```
There is a lot of redundant information here — and everything seems to appear twice for some reason.

#### Expectation
Call logs are succinct.

**Comment by mxschmitt** [comment]
I can repro:

1. Create a new CT project
2. Run good test
3. Run failing test

Expected: no duplicate call logs
Actual: duplicate call logs

**Comment by dgozman** [comment]
This is working as expected. The screenshot was taken twice, because it did not match for the first time and Playwright captured one more screenshot to make sure it is a stable one. All the information is here for a reason 😄  How would you like the logs to look like?

**Comment by pastelsky** [comment]
> The screenshot was taken twice, because it did not match for the first time and Playwright captured one more screenshot to make sure it is a stable one.

I've retries set to `0` — does it do it twice regardless? If so, it seems like an internal implementation detail of the framework.

It would be good if there was some control over verbosity so I can skip through certain log items. Or if the call logs were grouped.

**Comment by dgozman** [comment]
> It would be good if there was some control over verbosity so I can skip through certain log items. Or if the call logs were grouped.

If possible, could you be more specific? Which log items would you like to skip through? What do you mean by "grouped" in the error message string? We are open to ideas, and any specific examples would help.

**Comment by pastelsky** [comment]
For a start, perhaps collapse the logs so that the stable screenshot part isn't printed completely —
Also, increasing indentation / color coding (white / gray) might help.  

```
 Call log:
      - expect.toHaveScreenshot with timeout 5000ms
      -     verifying given screenshot expectation
      - waiting for locator('#root').locator('internal:control=component')
      -     locator resolved to visible <div id="root">…</div>
      - taking element screenshot
      -     disabled all CSS animations
      -     waiting for element to be visible and stable
      -     element is visible and stable
      - captured a stable screenshot
      - Expected an image 1280px by 771px, received 1280px by 776px. 
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
