### ISSUE TITLE
[Feature] Python support for the vscode extension

### ISSUE THREAD

**Issue by symc-alexander-harris** [microsoft/playwright#19207]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Mac
- Node.js version: n/a
- Visual Studio Code version: 1.73.0
- Playwright for VSCode extension version: 1.0.1
- Browser: All

Hi - question about VSCode extension support for python (or other languages). I am commenting here since the Q&A section for the extension marketplace links here. 

Is it possible to run python tests and explore locators, etc, in the middle of debug for python too? All the documentations and examples are in javascript (understandable).

I have installed the extension and it appears in the "testing" tab. But when I run my (pytest) tests, the "show browser" opens a different browser and not related to the current test.  If I try `pw.extension.command.inspect` from command pallette similarly, a new chromium opens up (not the one in my test). I have to open a separate codegen window and follow along to explore locators, which is inconvenient. 

I hope I am wrong and have missed some configuration steps. If not currently supported, is there a workaround? Or plan to support?

```
def test_goto_google(page):
    page.goto("https://google.com")
```
^^^ I can debug my test here and with it stopped, I am trying to "inspect".

**Comment by symc-alexander-harris** [comment]
Thank you both for the clarification.

**Comment by mxschmitt** [comment]
Thanks, folding into https://github.com/microsoft/playwright/issues/16971.
