### ISSUE TITLE
[Question] How do you move the cursor outside of viewport for Playwright, when it's not supported by default

### ISSUE THREAD

**Issue by rejectozaur** [microsoft/playwright#19203]
**Use case:**
There are some apps, especially e-commercial ones, that show a "please leave your contact credentials / sign up" modal when user moves the cursor outside of the viewport pane. I've conducted some research and could not find any solution to that for playwright. 

1. https://playwright.dev/docs/api/class-mouse acknowledged by reading documentation and own testing that it works inside a viewport
2. https://playwright.dev/docs/api/class-page#page-hover same

How would you tackle it? Is that a candidate for a new feature, though if it was, I supposed it would had been already implemented for mouse related methods.

Sample app for trying out such case https://the-internet.herokuapp.com/exit_intent

**Comment by mxschmitt** [comment]
You can do the following:

```ts
await page.locator('html').dispatchEvent('mouseleave');
```

**Comment by rejectozaur** [comment]
It indeed does. Thanks a ton!
