### ISSUE TITLE
[BUG] Could not use Socks 5 on Nightly 106

### ISSUE THREAD

**Issue by funnydevdotvn** [microsoft/playwright#19215]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows 10 x64 Pro v16.17.1
- Node.js version: 16.17.1
- Browser: Firefox
- Extra: Nothing
![317365312_827084385401075_2454500147895805247_n](https://user-images.githubusercontent.com/83385604/205126701-9cc20ca6-7b56-440d-95b4-b16500afe53c.png)

**Code Snippet**

```javascript
const playwright = require('playwright');

(async () => {
  const options = {
   proxy: {
     server: 'socks5://sock_ip:socks_port',
     username: '',
     password: ''
   }
  }
  const browser_context = await playwright.firefox.launchPersistentContext(path_to_profile... , options);
  const page = browser_context.pages()[0];
  await page.goto('https://domain.com...').then(...);
})();
```

**Describe the bug**

- Playwright does not support socks5 with user & password, but in my case there is no auth here.
- HTTP proxy seems like okay, but socks5 is treat as unable to connect with Nightly (tested with NodeJs failed but now success in Python).
- The Socks5 I used was tested on many kind of other platform like Pup, Selenium, Simple Requests... and of course it works.
- The older version does not meet this case.
- I also hope Playwright will have officially support for Socks5 with user & password.

**Comment by mxschmitt** [comment]
Do you think its a regression, was it working at any point with a different Playwright version?

Our socks5 tests are passing, so I'm curious whats different to your socks5 server. Is it open source?

**Comment by funnydevdotvn** [comment]
> Do you think its a regression, was it working at any point with a different Playwright version?
> 
> Our socks5 tests are passing, so I'm curious whats different to your socks5 server. Is it open source?

No it is not an open source, it is from some online services like Mountproxies or any private online Proxy/Socks5. In my case it was Vietnam's Socks5 service. I think there is no different between it and other services in USA or the others. And the version 1.25 still good at this.

**Comment by mxschmitt** [comment]
Can you manually go over the Playwright versions to see which one was a good and which one a bad one was?

Since we have no repro, its hard to assist and our tests are passing!

I'd then try to go over the change log and might spot something proxy related.

**Comment by funnydevdotvn** [comment]
> Can you manually go over the Playwright versions to see which one was a good and which one a bad one was?
> 
> Since we have no repro, its hard to assist and our tests are passing!
> 
> I'd then try to go over the change log and might spot something proxy related.

Hi, I've found this bug related to using Playwright in NodeJs, combined with Electron to run asynchronously will get socks5 connection error in Firefox as "NS_ERROR_UNKNOWN_PROXY_HOST". I used another temporary method to fix it and now solved my problem. But I think you should research more about this.
