### ISSUE TITLE
[BUG] .route() causes browser issues and fails test in vscode but ok on CI

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#19216]
**Context:**
- Playwright Version: 1.28
- Operating System: Mac
- Node.js version: 16
- Browser: Chromium
- Extra: [any specific details about your environment]

When running tests with `.route()` through the vs code extension with show browser open the main window keeps a loading spinner going and basically crashes meaning you need to manually close the browser in order to continue running tests. 

Running all tests locally will fail due to having multiple tests with `.route()`. You have to manually close the browser and run tests one by one  manually closing browser after each test. All tests will pass on CI.

```js
test('microsoft mvp link in home page works', async ({ page }) => {
  await page.context().route('https://mvp.microsoft.com/**', route => route.fulfill({
    body: '<html><body><h1>Microsoft MVP</h1></body></html>'
  }));

  const [page1] = await Promise.all([
    page.waitForEvent('popup'),
    await page.getByRole('link', { name: 'Former Microsoft MVP' }).click()
  ]);
  await expect(page1).toHaveURL('https://mvp.microsoft.com/en-us');
});
```

<img width="374" alt="Screenshot 2022-12-01 at 20 13 27" src="https://user-images.githubusercontent.com/13063165/205140670-0ca6ee2e-c4a8-40e6-b48a-b278a1e694bf.png">
<img width="620" alt="Screenshot 2022-12-01 at 20 18 46" src="https://user-images.githubusercontent.com/13063165/205140689-e34e5d8c-ec8d-47ab-9abe-4ed54ec55041.png">

For full repo: https://github.com/debs-obrien/debbie.codes/blob/master/tests/award-links.spec.ts

**Comment by dgozman** [comment]
I tried the following:

```sh
git clone https://github.com/debs-obrien/debbie.codes.git
cd debbie.codes
npm i
npx playwright install
npx playwright test --project=chromium --grep="microsoft mvp link in home page works"
```

Somehow it works for me:
```sh
Running 1 test using 1 worker

  1 passed (2s)

To open last HTML report run:

  npx playwright show-report
```
