### ISSUE TITLE
[Question] Unable to click a list item containing no text

### ISSUE THREAD

**Issue by skysantoroa** [microsoft/playwright#19214]
Hello, I'm trying to click the empty entry inside my `ul` element

![image](https://user-images.githubusercontent.com/101178279/205117336-4d29b5e6-c4c0-4475-aa1c-70f5c26775f0.png)

However the selector won't resolve to the entry and it's unable to click it. Same happens when `text=" "`.

Do you have any suggestion?

**Comment by mxschmitt** [comment]
Can you share a repro with us? How does the user know where to click? Can you share the exception with us what happens when you click with the selector? (this should give us hints why its failing, maybe it clicks on a 0px x 0px element.

**Comment by skysantoroa** [comment]
> Can you share a repro with us? How does the user know where to click? Can you share the exception with us what happens when you click with the selector? (this should give us hints why its failing, maybe it clicks on a 0px x 0px element.

No exception is thrown, the page will be closed. The element that should be selected is something like

`<ul>...<li>...<span></span></li></ul>`

**Comment by mxschmitt** [comment]
Are you using the Playwright test-runner and the vscode extension? There must be a nice exception thrown when using the Playwright Test Runner.

**Comment by mxschmitt** [comment]
We need a clear repro to act on it, either a small script/test which we can locally or more verbose logs. You can also set the `DEBUG=pw:api` env var to see more logs.

**Comment by aslushnikov** [comment]
@skysantoroa the checkbox without text cannot be located with a `text` engine; you'd be better off using the [`locator.nth()`](https://playwright.dev/python/docs/next/api/class-locator#locator-nth) or even [`locator.last()`](https://playwright.dev/python/docs/next/api/class-locator#locator-last) methods to pick the "last" checkbox and making sure it has no text.

**Comment by skysantoroa** [comment]
> @skysantoroa the checkbox without text cannot be located with a `text` engine; you'd be better off using the [`locator.nth()`](https://playwright.dev/python/docs/next/api/class-locator#locator-nth) or even [`locator.last()`](https://playwright.dev/python/docs/next/api/class-locator#locator-last) methods to pick the "last" checkbox and making sure it has no text.
> 
> Hope this helps!

The position of the empy string element is not deterministic, how to handle that?

**Comment by skysantoroa** [comment]
> @skysantoroa the checkbox without text cannot be located with a `text` engine; you'd be better off using the [`locator.nth()`](https://playwright.dev/python/docs/next/api/class-locator#locator-nth) or even [`locator.last()`](https://playwright.dev/python/docs/next/api/class-locator#locator-last) methods to pick the "last" checkbox and making sure it has no text.
> 
> Hope this helps!

Following your suggestion

```
const idx = (await page.locator('ul >> li >> span').allTextContents()).indexOf(val)
assert(idx !== -1)
await page.locator('ul >> li >> input').nth(idx).click()
```

The element is correctly located (`idx` is correct) however it keeps trying to retry the click action

```
  pw:api retrying click action, attempt #51 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +37ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +9ms
  pw:api retrying click action, attempt #52 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +39ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +11ms
  pw:api retrying click action, attempt #53 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +504ms
  pw:api   element is visible, enabled and stable +35ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +2ms
  pw:api   <div class="css-tc4hya">…</div> intercepts pointer events +8ms
  pw:api retrying click action, attempt #54 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +502ms
  pw:api   element is visible, enabled and stable +36ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +6ms
  pw:api retrying click action, attempt #55 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +44ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +2ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +13ms
  pw:api retrying click action, attempt #56 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +29ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +8ms
  pw:api retrying click action, attempt #57 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +41ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +2ms
  pw:api   <div class="css-tc4hya">…</div> intercepts pointer events +15ms
  pw:api retrying click action, attempt #58 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +503ms
  pw:api   element is visible, enabled and stable +26ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +1ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +7ms
  pw:api retrying click action, attempt #59 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +502ms
  pw:api   element is visible, enabled and stable +28ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +2ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +6ms
  pw:api retrying click action, attempt #60 +1ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +502ms
  pw:api   element is visible, enabled and stable +36ms
  pw:api   scrolling into view if needed +0ms
  pw:api   done scrolling +0ms
  pw:api   <div class="css-o5qx0d">…</div> intercepts pointer events +8ms
  pw:api retrying click action, attempt #61 +0ms
  pw:api   waiting 500ms +0ms
  pw:api   waiting for element to be visible, enabled and stable +502ms

```

**Comment by aslushnikov** [comment]
@skysantoroa logs complain there's some `<div>` that intercepts pointer events. Could it be the case?

Any way, if you can re-file with a reproduction steps so that we can look at it locally, it'll be very helpful.

**Comment by skysantoroa** [comment]
> @skysantoroa logs complain there's some `<div>` that intercepts pointer events. Could it be the case?
> 
> Any way, if you can re-file with a reproduction steps so that we can look at it locally, it'll be very helpful.

I solved by selecting the `li` elements however even though there's a `div` intercepting the click event should be handled correctly
