### ISSUE TITLE
[Feature] Add a way to add user browser args while launching browser in android

### ISSUE THREAD

**Issue by pranavj1001** [microsoft/playwright#19211]
Currently, there's no way to add user browser args for launching the chrome browser in android ([link](https://github.com/microsoft/playwright/blob/dbf3fc50896494d13153e45d08b75deae43afd7c/packages/playwright-core/src/server/android/android.ts#L267-L272)). We would like a way to add additional browser args.

We have developed a [PR](https://github.com/microsoft/playwright/pull/19212) for the same where we have added a new param (`browserArgs: string[]`) in BrowserNewContextParams. Before launching the browser, the code goes through the new param and adds it to the existing list.

**Comment by mxschmitt** [comment]
In what kind of browser args are you interested in? What is the use-case? This would help us to prioritise this feature request.

**Comment by pranavj1001** [comment]
Hey @mxschmitt, thanks for the reply. Currently, we're interested in flags like `--proxy-server` and `--proxy-bypass-list`. But in the future, we might be interested in other args as well.

**Comment by mxschmitt** [comment]
Then the better way would be to allow supporting passing proxy when performing Android.launchBrowser. See [this](https://github.com/microsoft/playwright/blob/dbf3fc50896494d13153e45d08b75deae43afd7c/packages/playwright-core/src/server/chromium/chromium.ts#L304-L323) logic which we can re-use for it.

Allowing passing args is generally speaking fine, but in the linked PR it was made in the wrong location. I commented there.

**Comment by pranavj1001** [comment]
Ack, thanks. Have done some changes in the [PR](https://github.com/microsoft/playwright/pull/19212).
