### ISSUE TITLE
[BUG] page.waitForNavigation not working

### ISSUE THREAD

**Issue by 3wweiweiwu** [microsoft/playwright#19224]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.28.1
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Node.js version: [e.g. 12.22, 14.6] V16.13
- Browser: [e.g. All, Chromium, Firefox, WebKit] 
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
        let browser = await chromium.launch({ headless: true })
        let page = await browser.newPage()
        await page.goto('https://todomvc.com/examples/vue/')
        await page.locator('//*[.="Evan You"]').click()
        await page.waitForNavigation({ timeout: 5000 })
})();
```

**Describe the bug**

playwright is unable to wait for navigation. as we switch from one page to the other.

error inforamtion: page.waitForNavigation: Timeout 5000ms exceeded. The target page is a static page.

**Comment by mxschmitt** [comment]
`waitForNavigation` needs to get called before you actually click, this then looks like the following:

```js
// @ts-check
const playwright = require('playwright');

(async () => {
  // Try to add 'playwright.firefox' to the list ↓
  const browser = await playwright.chromium.launch();
        let page = await browser.newPage()
    await page.goto('https://todomvc.com/examples/vue/')
    await Promise.all([
       page.waitForNavigation({ timeout: 5000 }),
       page.locator('//*[.="Evan You"]').click(),
    ])
  await browser.close();
})();
```

Usually you never need to call waitForNavigation, Playwright waits for it internally and handles it.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
