### ISSUE TITLE
[Question] Hybrid WebView-based apps support

### ISSUE THREAD

**Issue by AndreyZarembo** [microsoft/playwright#19227]
My team works on hybrid app based on Web view. Our Web-base front makes most of the business logic, and we've created JS-Native bindings to give access to camera, contacts, biometry and so on. We'd like to run some End2End tests to make sure everything works as expected in full setup. It's important to run tests on simulators and on real devices.
We'd like to add hybrid apps support to Playwright, something like plugins. 

It should works something like this: 
- In Playwright configuration we add custom browser with its own name, url to connect via sockets to hybrid app, some configuration JSON. 
- Modify app to receive connections via sockets and respond to Browser events from test. And communicate with internal browser and web-page.
- ...
- Profit

What's the best way to start digging into it?

**Comment by mxschmitt** [comment]
We don't know anything about your app, so its hard to give advice!

Most likely connect to your Webview if its CDP based via CDP and figure out from there whats working and whats not working?

**Comment by mxschmitt** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by stachu99** [comment]
Hi. I think @AndreyZarembo has written about BlazorWebView control but Webview2 control.
BlazorWebView is Blazor hybrid control  https://learn.microsoft.com/en-us/aspnet/core/blazor/hybrid/?view=aspnetcore-7.0.
The content of the BlazorWebView control can be inspected and debugged in Ms Edge DevTools.
I'm digging for a solution to use Chrome DevTools Protocol (CDP) for connecting to the BlazorWebView control.
I know how to configure Playwright. I don't know is possible to set remote debugging port in the BlazorWebControl.

**Comment by AndreyZarembo** [comment]
I'll give more details next week in new ticket.

**Comment by AndreyZarembo** [comment]
Reposted with details as #20316
