### ISSUE TITLE
[BUG] <canvas> elements don't show up in screenshots

### ISSUE THREAD

**Issue by ffxsam** [microsoft/playwright#19225]
**Context:**
- Playwright Version: 1.28.1
- Operating System: macOS
- Node.js version: 18.12.1
- Browser: All

**Code Snippet**
```js
import { chromium, devices } from "playwright";

(async function () {
  const browser = await chromium.launch();
  const context = await browser.newContext(devices["Desktop Chrome"]);
  const page = await context.newPage();

  await page.goto("https://waveform.prototyping.bbc.co.uk/");
  await page.screenshot({ path: "wow.png", fullPage: true });

  await context.close();
  await browser.close();
})();
```

**Describe the bug**

The full page is captured, except for the `<canvas>` elements.

**Comment by mxschmitt** [comment]
In your case you take the screenshot too early. You can e.g. wait for a specific timeout via `  await page.waitForTimeout(1000)` or figure out the reason why the site takes a specific time to draw on the canvas.

**Comment by ffxsam** [comment]
@mxschmitt Thanks, waiting did the trick! Not really sure why there's a delay, other than the fact that it's using axios to fetch binary data to draw the waveform.

The only other issue I have now (with a different URL than the one above) is that the images aren't showing up because they're lazy-loaded and only appear once the page is scrolled. Is there some mechanism within Playwright I can use to force the images to show up?

**Comment by ffxsam** [comment]
Coded a possible solution for the lazy loading. #19277
