### ISSUE TITLE
[Feature] Shorten trace viewer URL / Trace files in location hash

### ISSUE THREAD

**Issue by max-te** [microsoft/playwright#19228]
We currently have some tests using `expect.poll` which time out after a long time. This leads to a large number of generated trace files for a single test. The links to the trace viewer for these tests are thus very long, exceeding the maximum url length for our instance of Gitlab. It looks something like this:
```
https://group.pages.gitlab.example.com/-/group/projectname/-/jobs/12345678/artifacts/playwright-report/trace/index.html?trace=https://group.pages.gitlab.example.com/-/group/projectname/-/jobs/12345678/artifacts/playwright-report/data/8eb66c1238d4657ce6cb9e5213b44a7b18ef2fbf.zip&trace=https://group.pages.gitlab.example.com/-/group/projectname/-/jobs/12345678/artifacts/playwright-report/data/f519bb8d34c23784b7858e5a2d50c743ba5360d5.zip&trace=https://group.pages.gitlab.example.com/-/group/projectname/-/jobs/12345678/artifacts/playwright-report/data/6ca987a3b58f9ac60f43f25e190e8c8a4b6b243a.zip (and so on...)
```
This quickly leads to very long urls, an example we have with 13 traces has 2397 characters.

Our request is to move the `?trace=....` parameters into the location hash, so that they aren't sent to the server, similarly to how the `#?testid=....` is [implemented](https://github.com/microsoft/playwright/blob/df143031e7eac11460bcd658dc3bb5a8951ccd64/packages/html-reporter/src/reportView.tsx#L45) for the report view.

**Comment by mxschmitt** [comment]
Where do you get the long URL with the 13 trace files from? You can try passing a relative URL which should work.

**Comment by max-te** [comment]
The URL comes from the trace viewer thumbnail in the Playwright report
![Screenshot_20221206_080513](https://user-images.githubusercontent.com/870074/205844036-a27e7699-3388-4073-8046-d314fa08b83d.png)

Using relative URLs doesn't work:
![image](https://user-images.githubusercontent.com/870074/205844631-06b965df-a00f-46f7-89e0-2459313378af.png)

**Comment by aslushnikov** [comment]
@max-te do I understand correctly that you use API testing inside the `expect.poll` predicate and thus you're getting all these traces?

**Comment by max-te** [comment]
Yes, that is correct. The poll is making requests to an api waitng for a background process to complete.

Now that I say that, I realise we are creating a new RequestContext inside the poll, maybe that does cause creating the new traces? In this case I could work around the issue by reusing the context.

**Comment by aslushnikov** [comment]
> In this case I could work around the issue by reusing the context.

@max-te Yes, re-using the context should result in a single trace for the context.

**Comment by aslushnikov** [comment]
@max-te could you please verify that re-using API context worked for you?

**Comment by max-te** [comment]
Moving the context definition out of the poll, and overall decreasing the creation of new APIRequestContexts, did work for me to shorten the urls to a usable length, yes.
