### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Armen-Khachatryan** [microsoft/playwright#19230]
Hello. Running `npx playwright install --with-deps` fails with `playwright: not found` error using node 16 in github actions workflow. With node 14 there are no errors. I tried to use `yarn create playwright` command instead, but it's waiting for some input in the workflow file

![image](https://user-images.githubusercontent.com/32818855/205278115-9c574b55-8905-4789-9e72-65da43dba4ac.png)

Any idea what should we do?

**Comment by mxschmitt** [comment]
`yarn create playwright` is a CLI tool which helps you to scaffold a new Playwright project, it should not be used on CI.

If you are using Yarn, you should not use `npx playwright install --with-deps` and you should use `yarn playwright install --with-deps` instead. Can you try that?
