### ISSUE TITLE
[Feature] Support new headless mode in chromium

### ISSUE THREAD

**Issue by BorisOsipov** [microsoft/playwright#19233]
## Background
There is an new headless mode in chromium. See [Issue 1237546: Implement native headless mode option](https://bugs.chromium.org/p/chromium/issues/detail?id=1237546)

## Describe the improvement
I'd like to use the new headless mode. Main advantage for playwright users seems to be the capability to run chrome extension tests in headless mode.

## Demo
I've created [simple repo ](https://github.com/BorisOsipov/playwright-headless-extension) via project generator and add a test with extension and new headless mode. It works like a charm in github action.

**Comment by mxschmitt** [comment]
Since it already works, you can use it as of today via specifying `--headless=chrome` via the `args` - what does this issue request in particular?

**Comment by aslushnikov** [comment]
> I'd like to use the new headless mode. Main advantage for playwright users seems to be the capability to run chrome extension tests in headless mode.

@BorisOsipov Using the new headless mode via the cli arg is the suggested approach; we'll see how it goes over time!

Closing this since there's no action regarding this in the foreseeable future. Thanks for filing though!

**Comment by BorisOsipov** [comment]
>we'll see how it goes over time!

Agree.

@aslushnikov  
Do you consider add such workaround to official docs https://playwright.dev/docs/chrome-extensions#testing ? I've seen a lot of questions over the time "how to test extenstions with headless chrome?". Seems new headless is good candidate for this.

**Comment by aslushnikov** [comment]
> Do you consider add such workaround to official docs https://playwright.dev/docs/chrome-extensions#testing ? I've seen a lot of questions over the time "how to test extenstions with headless chrome?". Seems new headless is good candidate for this.

Good point! Would you like to send a PR for this?
