### ISSUE TITLE
Sorting a table

### ISSUE THREAD

**Issue by mvendhanbig** [microsoft/playwright#19249]
In our scenario, We have to sort the table, by clicking the header column name. do we have any inbuilt method for sorting in playwright or else could you please suggest the solution for our scenario?

below is the code I have written it is working if we have limited data in the table

 await userManagementPage.headerByName("Admin User ID").click();
    await userManagementPage.columnByName("Admin User ID").nth(1).waitFor({ state: "visible" });
    const descending = await userManagementPage.columnByName("Admin User ID").allTextContents();
    await userManagementPage.headerByName("Admin User ID").click();
    await userManagementPage.columnByName("Admin User ID").nth(1).waitFor({ state: "visible" });
    const ascending = await userManagementPage.columnByName("Admin User ID").allTextContents();
    await expect(descending).toEqual(ascending.reverse());

for example:
If we have 100 records, in a table. per page, we make it 10 records. So, that time if we sort the table by clicking the column header in ascending order it will show the 10 records. If again click the column header it will sort in descending order the last record will be displayed.. if use the above code for this scenario it will fail... why? means list of records will different in sorting as ascending and descending order

**Comment by pastelsky** [comment]
@mvendhanbig This seems related to your application rather than anything to do with playwright.

**Comment by aslushnikov** [comment]
@mvendhanbig This doesn't seem to be related to Playwright misbehaving - rather a weird website behavior. I'd recommend asking these questions on forums like StackOverflow!
