### ISSUE TITLE
[Question] Can playwright support component slots rendered through render function? Not a slot for component template

### ISSUE THREAD

**Issue by huiyimeijiaodian** [microsoft/playwright#19247]
I have a component rendered through render function.
eg: 
![image](https://user-images.githubusercontent.com/11565772/205422127-26c21a7f-bdc8-4488-b5b1-dcba39b5cc36.png)

my playwright test demo code:

![image](https://user-images.githubusercontent.com/11565772/205422263-f3df85b0-fb0b-4774-a902-93d7dc0f0663.png)

when test this demo, that can not render slot content???

**Comment by hangboss1761** [comment]
`@playwright-ct-vue2` convert
```ts
await mount(Component, { slots: { header: 'Header' } })
```
to just like
```ts
new Vue({
    render: h => h(Component, { scopeSlots: { header: () => h('span', 'Header') } })
})
```

It's not playwright's problem. You kan see [this demo](https://codesandbox.io/s/fragrant-wood-49mref?file=/src/main.js).

You can solve the problem in two ways：
- import your component in TestWrapper.vue and test it.
or
- change `this.$slots.header` to `this.$scopedSlots.header()` in your code

**Comment by aslushnikov** [comment]
Closing as per @hangboss1761 response.
