### ISSUE TITLE
[Question]Is it possible to run tests in sequence from multiple test files?

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#19243]
Is there a way to run the test cases in multiple test files in sequence. From what I have noticed all the tests in a single file run in sequence if we add test.describe.configure({ mode: 'serial' });

What if I want to run tests from multiple files in a sequence and not in parallel. Is there a way to achieve this?

**Comment by mxschmitt** [comment]
You can use a list file for that: https://playwright.dev/docs/test-parallel#use-a-test-list-file

Let us know if it helps!

**Comment by aslushnikov** [comment]
Closing as per Max's response!
