### ISSUE TITLE
[BUG] : weird screenshot with c# api

### ISSUE THREAD

**Issue by ray440** [microsoft/playwright#19250]
**Context:**
- Playwright Version: 1.27.2 dll
- Operating System: Windows
- Browser: Chromium
- Extras: using c# api

Using the c# api to capture a form I get weird results.
Note how the top border of some text boxes are missing/overwritten.

![form_filled](https://user-images.githubusercontent.com/10067289/205459889-4dea77f2-25b9-4acb-9ab3-f871bda38d14.png)

**Comment by ray440** [comment]
The issue may have something to do with the monitor scale.  On one monitor I have the scale set to 125%.  When I set it to 100%, the problem seems to go away.

**Comment by aslushnikov** [comment]
> On one monitor I have the scale set to 125%.

@ray440 this is the root cause. And this is not something that we can fix on our end: monitor scaling affects browser rendering in an intricate way that we can't override. Sorry about this!

**Comment by ray440** [comment]
> @ray440 this is the root cause. And this is not something that we can fix on our end

I get it.
This happens with chrome but not the firefox driver.  Should I pass this on to the chrome devs?

**Comment by aslushnikov** [comment]
> Should I pass this on to the chrome devs?

@ray440 yeah, you can file this on https://crbug.com/new

**Comment by ray440** [comment]
> > Should I pass this on to the chrome devs?
> 
> @ray440 yeah, you can file this on https://crbug.com/new

Done. For reference: https://bugs.chromium.org/p/chromium/issues/detail?id=1396401

**Comment by ray440** [comment]
FYI: somewhat related.  I got this exception while trying to take a snapshot in chrome (ctrl-i, ctrl-p "screen capture node")

```
\bin\Debug\net7.0-windows\.playwright\package\lib\utils\index.js:90
	if (!value) throw new Error(message || 'Assertion error');
				    ^
				
Error: Download started in unknown page: {"frameId":"1E8B2793B308B932CCB00525EBF19173","guid":"92761600-4edf-4daa-8b2b-d50f99c43cb8","url":"blob:devtools://devtools/ebd50e30-46ce-4e72-b9e7-b6ef76477d55","suggestedFilename":"localhost_5205_MyTests_AllTests_filter=$RawHtmlTests.png"}
	at assert (…\bin\Debug\net7.0-windows\.playwright\package\lib\utils\index.js:90:21)
	at CRBrowser._onDownloadWillBegin (…\bin\Debug\net7.0-windows\.playwright\package\lib\server\chromium\crBrowser.js:222:23)
	at CRSession.emit (node:events:513:28)
	at …\bin\Debug\net7.0-windows\.playwright\package\lib\server\chromium\crConnection.js:190:14


```
