### ISSUE TITLE
[Feature] playwright show-report without automatically opening the browser

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#19257]
I am running playwright on CI (webapp.io), in particular, webapp.io allows you to expose a port if you have a command that hosts a server, which theoretically show allow me to have a really nice setup where I don't have to download the report and open up the playwright viewer locally, and can instead click open the one hosted on the ci server.

However, I'm running into an issue where `npx playwright show-report` tries to open a browser, which it won't be able to do on the CI server. Is it possible to host the playwright server without it trying to open the browser?

**Comment by LongLiveY96** [comment]
In my opinion, you can deploy the report directory on the server and can access the report content directly through index.html. All you may need to do is to customize the report directory name to prevent the report from being overwritten.

**Comment by WesleyYue** [comment]
That works for part of the report, but won't work if you try to open the trace viewer b/c the server isn't running.

**Comment by LongLiveY96** [comment]
> That works for part of the report, but won't work if you try to open the trace viewer b/c the server isn't running.

I did this and it works, as long as you deploy content that includes the trace service, accessing index.html and viewing the trace online is fully available.
![image](https://user-images.githubusercontent.com/23394317/205566969-0a91e51f-60a8-4d63-a44a-ddbcca46a5c5.png)

**Comment by LongLiveY96** [comment]
> You're not in the trace viewer, that's the report viewer.
> 
> https://playwright.dev/docs/trace-viewer

I just found out too that if I go to trace viewer, the page does not load. 😔
![image](https://user-images.githubusercontent.com/23394317/205617812-b9fe3f4c-ba12-4154-b2d3-8b5f4c8d936b.png)

**Comment by aslushnikov** [comment]
> However, I'm running into an issue where npx playwright show-report tries to open a browser, which it won't be able to do on the CI server.

@WesleyYue It should print unhappy message to the terminal, but will still serve the HTML report for you. Did you try it on your CI?

**Comment by aslushnikov** [comment]
Closing this since this seems to be stale. Feel free to re-file if this doesn't actually work!
