### ISSUE TITLE
How can I build a remote browser myself?[Question]

### ISSUE THREAD

**Issue by bbhxwl** [microsoft/playwright#19267]
How can I build a remote browser myself?

**Comment by aslushnikov** [comment]
@bbhxwl What's a "remote browser"?

**Comment by bbhxwl** [comment]
> @bbhxwl What's a "remote browser"?

It is similar to the ws protocol to connect to the browser.

**Comment by bbhxwl** [comment]
> @bbhxwl What's a "remote browser"?

ws://server:9222   
How do I create this browser?

**Comment by aslushnikov** [comment]
Ah, try this: https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-server

**Comment by bbhxwl** [comment]
> Ah, try this: https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch-server

This only says how to connect, not how to build

**Comment by aslushnikov** [comment]
@bbhxwl you create it with the `launchServer` command and then you can connect to it remotely.

The snippet demonstrates the whole workflow:

```ts
const { chromium } = require('playwright');  // Or 'webkit' or 'firefox'.

(async () => {
  // create server
  const browserServer = await chromium.launchServer();
  const wsEndpoint = browserServer.wsEndpoint();
  // Use web socket endpoint later to establish a connection.
  const browser = await chromium.connect(wsEndpoint);
  // Close browser instance.
  await browserServer.close();
})();
```

**Comment by bbhxwl** [comment]
> ```ts
> launchServer
> ```

Apart from nodejs, does C # not have a launchServer?

**Comment by aslushnikov** [comment]
@bbhxwl only Node.js has the "launchServer" method, but you can connect to it from other languages.

**Comment by aslushnikov** [comment]
This seems to be resolved; closing!

**Comment by bbhxwl** [comment]
> 

Why do I have to quote @playwright/test

Can you let the program wait?
Can this be accessed remotely by default?



const { chromium } = require('@playwright/test');  // Or 'webkit' or 'firefox'.
