### ISSUE TITLE
[Question] Disable screenshot resolution check?

### ISSUE THREAD

**Issue by Psixodelik** [microsoft/playwright#19266]
Hi, is it possible to turn off the screenshot resolution check? I want to get diff even if both screenshots have different resolutions.

Before Playwright, I used jest-image-snapshot, where there was an allowSizeMismatch setting. When it was turned on, an empty space was added to the screenshot and they were compared.

This is convenient, because it is strange to fail tests due to a difference of 1 pixel in height

**Comment by aslushnikov** [comment]
Folding this in https://github.com/microsoft/playwright/issues/18827

**Comment by Psixodelik** [comment]
No, I don't think it's a bug. I deliberately want to turn off the permission check so as not to fail the tests due to minor differences.

**Comment by jhned** [comment]
Hey I've been working on this as well, here's a way I found around it. The tricky part is that you have to find the size of the expected image before you go and get the actual, so that you can clip actual to expected: 

``` js
// External dependency to get the image dimensions
import sizeOf from 'image-size';

... test setup...

// "label" is equal to the test name
const snapshotName = `${label}.png`;
const snapshotPath = await testInfo.snapshotPath(snapshotName);
const expected = await sizeOf(snapshotPath);
if (expected) {
    const width = Number.isInteger(expected.width) ? expected.width : 0;
    const height = Number.isInteger(expected.height) ? expected.height : 0;
    await expect(page).toHaveScreenshot(snapshotName, { clip: {x: 0, y: 0, width, height}, fullPage: true, maxDiffPixelRatio: .4 });
} else {
    await expect(page).toHaveScreenshot(snapshotName, { fullPage: true, maxDiffPixelRatio: .4 });
}
```
