### ISSUE TITLE
[Question] Get the locator string generated by codegen

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#19268]
I have a requirement to get the locator string from script, for example
`await page.locator('.el-select-dropdown__list:visible li').first().click();`
Get the locator part of it: `locator('.el-select-dropdown__list:visible li').first()`
`await page.locator('label').filter({ hasText: 'xxxxxx' }).locator('span').nth(1).click();`
Get the locator part of it: `locator('label').filter({ hasText: 'xxxxxx' }).locator('span').nth(1)`
`await page1.getByRole('listitem').filter({ hasText: 'netword' }).click();`
Get the locator part of it: `getByRole('listitem').filter({ hasText: 'netword' })`
Is there a regular expression for the locator in the code generated by codegen for reference ?

**Comment by aslushnikov** [comment]
> Is there a regular expression for the locator in the code generated by codegen for reference ?

@LongLiveY96  There's no regex. But it looks like you can just split by `'.'` (dot) and drop the first token.
