### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by AntunesLaurindo** [microsoft/playwright#19269]
Hello everyone, everything good? I'm building an automation and I have a question. How do I loop repeat in Playwright? Do I use "For" and "While" or is there some other command?

**Comment by gauravgandhi1315** [comment]
Depending upon on your use case, you can use either for or while loop. Playwright doesn't change the scope of for and while loop.

```
for(let i=x; i<=y; i++){
   // your code
    }
```
