### ISSUE TITLE
[Question] Extract DOM snapshots from the trace file

### ISSUE THREAD

**Issue by xiang-deng** [microsoft/playwright#19265]
Hello guys,

I am using playwright for web automation. I see that the trace viewer captures & displays the dom snapshots. Is there a way to extract the dom snapshots associated with each action as individual txt files? Or some pointers to how the trace viewer constructs the snapshots, and maybe I can write some code to parse the recorded trace file. Thanks!

**Comment by aslushnikov** [comment]
>  Is there a way to extract the dom snapshots associated with each action as individual txt files? 

@xiang-deng We don't provide any API for this

> Or some pointers to how the trace viewer constructs the snapshots, and maybe I can write some code to parse the recorded trace file.

You should probably start reading somewhere around [`snapshotter.ts`](./packages/playwright-core/src/server/trace/recorder/snapshotter.ts).

Hope this helps!
