### ISSUE TITLE
[BUG] Documentation: need specify baseURL in fixture

### ISSUE THREAD

**Issue by robertu7** [microsoft/playwright#19264]
**Context:**
- Playwright Version: v1.28.1
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: All

**Code Snippet**
Code from [Avoiding multiple sessions per account at a time](https://playwright.dev/docs/auth#avoiding-multiple-sessions-per-account-at-a-time):
```ts
export const test = baseTest.extend({
  storageState: async ({ browser }, use, testInfo) => {
    // Override storage state, use worker index to look up logged-in info and generate it lazily.
    const fileName = path.join(testInfo.project.outputDir, 'storage-' + testInfo.workerIndex);
    if (!fs.existsSync(fileName)) {
      // Make sure we are not using any other storage state.
      const page = await browser.newPage({ storageState: undefined });
      await page.goto('https://github.com/login');
      // Create a unique username for each worker.
      await page.getByLabel('User Name').fill(users[testInfo.workerIndex].username);
      await page.getByLabel('Password').fill(users[testInfo.workerIndex].password);
      await page.getByText('Sign in').click();
      await page.context().storageState({ path: fileName });
      await page.close();
    }
    await use(fileName);
  },
});
```

**Describe the bug**

In this code sample of documentation, the `baseURL` seems doesn't work and we have to pass it into the context like so:

```ts
...
  storageState: async ({ browser, baseURL }, use, testInfo) => {
...
      const page = await browser.newPage({ storageState: undefined, baseURL })
...
```

**Comment by robertu7** [comment]
Closed since we may shouldn't use `baseURL` in `storageState`

**Comment by aslushnikov** [comment]
@robertu7 what do you mean that `baseURL` doesn't work? Why do you want to use `baseURL` if you always navigate to `https://github.com/login`?

**Comment by robertu7** [comment]
@aslushnikov Sorry, I made some changes to the sample code, the URL should be relative:

```diff
export const test = baseTest.extend({
  storageState: async ({ browser }, use, testInfo) => {
    // Override storage state, use worker index to look up logged-in info and generate it lazily.
    const fileName = path.join(testInfo.project.outputDir, 'storage-' + testInfo.workerIndex);
    if (!fs.existsSync(fileName)) {
      // Make sure we are not using any other storage state.
      const page = await browser.newPage({ storageState: undefined });
-      await page.goto('https://github.com/login');
+      await page.goto('/login');
      // Create a unique username for each worker.
      await page.getByLabel('User Name').fill(users[testInfo.workerIndex].username);
      await page.getByLabel('Password').fill(users[testInfo.workerIndex].password);
      await page.getByText('Sign in').click();
      await page.context().storageState({ path: fileName });
      await page.close();
    }
    await use(fileName);
  },
});
```

**Comment by aslushnikov** [comment]
@robertu7 ah now i follow! So since you create a page yourself, you'll have to specify the baseURL for it yourself as well. 

The approach you suggested - explicitly passing `baseURL` to the `browser.newPage()` call - is the proper way to do this.

**Comment by robertu7** [comment]
@aslushnikov I see, so the `page` fixture works with normal cases (import `test` from `@playwright/test`) because it's already passed by `baseURL`?

**Comment by aslushnikov** [comment]
Yep, [exactly](https://github.com/microsoft/playwright/blob/3c1b26b9f1632e2782046bc87069fc97bb206d48/packages/playwright-test/src/index.ts#L240).

**Comment by robertu7** [comment]
@aslushnikov Got it, thanks!  Though it would be a bit confusing, lol.
