### ISSUE TITLE
[Question] Better way to force loading of lazy load images?

### ISSUE THREAD

**Issue by ffxsam** [microsoft/playwright#19277]
I wrote the following code, which works, but I'm wondering if there's a better way to force lazy images to load?

```js
  const sizes = await page.evaluate(() => {
    const browserHeight = window.innerHeight;
    const pageHeight = document.body.scrollHeight;

    return { browserHeight, pageHeight };
  });

  for (let i = 0; i < sizes.pageHeight; i += sizes.browserHeight) {
    await page.mouse.wheel(0, i);
    console.log("scrolled to", i);
    await page.waitForTimeout(1000);
  }
```

**Comment by aslushnikov** [comment]
@ffxsam you can also try to remove the `loading="lazy"` attribute from all the images if the lazy loading is implemented via browser means.

But in general, the scrolling solution is more bullet-proof since it'll take work for a javascript-powered lazy loading as well.

Hope this helps!

**Comment by ffxsam** [comment]
@aslushnikov Thanks! Mostly I was hoping there would be a way to not do `page.waitForTimeout(1000)`, but I couldn't find any reliable way to wait for the image to load. Waiting for network state of "idle" didn't work.
