### ISSUE TITLE
[BUG] - Cannot call npx playwright in the predeveloped Docker image

### ISSUE THREAD

**Issue by akosbalasko** [microsoft/playwright#19275]
**Context:**
- Playwright Version: [1.28.0]
- Operating System: [Docker]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [All]
- Extra: [any specific details about your environment]

**Describe the bug**

Hi there! 
It looks like that the pre-developed Docker image does not work very well, or I missed something in the docs. 
I simply start the image according to the description:
```
docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.28.0-focal /bin/bash

```
which in the given bash I try to execute the following:
```
npx playwright test
```
It returns this 
```
Need to install the following packages:
  playwright@1.28.1
Ok to proceed? (y) 
```
Then if I type y, it installs the package and returns the following:
```
Please install @playwright/test package to use Playwright Test.
  npm install -D @playwright/test 
```
  What am I missing?

**Comment by Nav-2d** [comment]
you need `npm install` before `npx playwright test`

**Comment by akosbalasko** [comment]
@Nav-2d , thanks for your response! but this means that i have to copy my package.json into the docker image (or mount a volume which contains it)  so i cannot use the image as it is, right?

**Comment by aslushnikov** [comment]
Closing as per @Nav-2d response

**Comment by PumpkinSeed** [comment]
I don't really get the purpose of the docker image. If I need to do an `npm install`, just before I want to test I can use a node image as well. Can you guys detail how we should use the docker image as a one-liner? Since most of these images are created for that purpose.
