### ISSUE TITLE
[Question] how to clear credentials?

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#19286]
context = browser.new_context(
    http_credentials={"username": "bill", "password": "pa55w0rd"}
)
page = context.new_page()

After I set the http_credentials parameter to log in to the device, I need to test the function of logging out, but after clicking the logout button, I automatically logged in again. 
What do I need to do to log out?

**Comment by aslushnikov** [comment]
@god-pane there's no way to "log out" out of a basic HTTP auth. What does the button do?

**Comment by god-pane** [comment]
thx,   there is no point in quitting in this scenario either.
