### ISSUE TITLE
Add support for React Testing Library `getByLabelText`

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#19284]
### Discussed in https://github.com/microsoft/playwright/discussions/19261

<div type='discussions-op-text'>

<sup>Originally posted by **mrwwalmsley** December  4, 2022</sup>
Given that all our unit tests use React Testing Library, I was excited to migrate our e2e tests to use these new methods that mostly mirror those in Testing Library.

The main difference is currently missing full support for `getByLabelText`.
Playwrights `getByLabel` only partially supports the functionality of `getByLabelText`.
i.e. no support for `aria-label` or  `aria-labelledby`.

It seems a shame to me that the API's have this difference.  Is there a strong rationale for not supporting `getByLabelText` ?</div>

**Comment by mxschmitt** [comment]
Good spotting @mrwwalmsley I filed an issue for it.

**Comment by mrwwalmsley** [comment]
If I understood the PR, it added support for `aria-labelledby` but did not add support for  `aria-label`.  Is that going to be added in a separate PR?
