### ISSUE TITLE
[BUG] When adding any code in the playwright.config.* the extension is not working

### ISSUE THREAD

**Issue by muhammmedkhattab** [microsoft/playwright#19292]
**Context:**
- Playwright Version: [1.28]
- Operating System: [Mac]
- Node.js version: [16.14.2]
- Visual Studio Code version: [Version: 1.73.1 (Universal)]
- Playwright for VSCode extension version: [v1.0.1 @latest]
- Browser: [All]

**Code Snippet*
![Screenshot 2022-12-06 at 10 03 44](https://user-images.githubusercontent.com/36113228/205867626-172db1fc-42ab-4469-8e45-c99c9468f39a.png)

![Screenshot 2022-12-06 at 10 04 10](https://user-images.githubusercontent.com/36113228/205867659-f5533583-4d02-4580-90cb-e57d22c238e6.png)

**Describe the bug**

saw if you added any code for my example I added a condition to give me console log if I didn't choose a env. the whole extension doesn't work and can't run any test locally once I remove it or commented it out all work

**Comment by aslushnikov** [comment]
@muhammmedkhattab Playwright reads and evaluates your config to get the list of tests. While doing so, it doesn't set the env variable that you'd like to have in there, so it naturally fails.

There's no way to workaround this; I'd try running VSCode with this env variable pre-set. Hope this helps!
