### ISSUE TITLE
[BUG] Unable to generate allure report

### ISSUE THREAD

**Issue by keshavjha06** [microsoft/playwright#19303]
- Playwright Version: [1.28.1]
- Operating System: [Mac]
- Node.js version: [19.2.0]
- Browser: [Chromium, Firefox, WebKit]
-  "allure-playwright": "^2.0.0-beta.20"

I have installed allure and also ran the test cases with npx playwright test --grep @web --reporter=line,allure-playwright

allure-results folder got generated

But unable to generate the report using the below command

allure generate ./allure-results --clean

getting the error - zsh: command not found: allure

**Comment by gauravgandhi1315** [comment]
how did you install allure? It looks like the issue with the allure installation to me

**Comment by keshavjha06** [comment]
I have installed using the command npm i -D @playwright/test allure-playwright

**Comment by aslushnikov** [comment]
> I have installed using the command npm i -D @playwright/test allure-playwright

This doesn't install allure itself. Please check out https://docs.qameta.io/allure/ for the installation instructions; right now
it says to do something like the following to install on Mac:

```bash
brew install allure
```

Closing this since this is a not a playwright issue.
