### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by k87perera** [microsoft/playwright#19319]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: v16.17.1
- Browser: [e.g. All, Chromium, Firefox, WebKit]

Java Script 
```js
const { test, expect } = require('@playwright/test');

test.only('testing edit',async ({ page }) => {

   await page.locator("[alt ='logo']").nth(1).click();
   await page.waitForLoadState('networkidle');
   await page.locator ("button[class='btn_btn-danger']").click();
   await  page.locator("[name='link']").click(); // **Issue is starting from here**
//    await  page.locator("[name ='appName']").click(); // can not locate edit page crashing
//    await page.locator("[name ='appName']").fill(' ');// can not locate edit page crashing

});
```

**Describe the bug**
Normal chrome browser without any issue or crashing transaction can continue manually ;
but we script runs (Playwright chrome browser ) element eg: buttons and fields are not displaying page also crashing. 

error -

```
 locator.click: Target closed
=========================== logs ===========================
waiting for locator('button[class=\'btn btn\']')
============================================================

```

**Comment by aslushnikov** [comment]
@k87perera  The best I can say is that if the page closes unexpectedly, it very much might mean a missing `await` statement somewhere in your code. 

However, there's not much else I can help with. I'd assume there's some error in your code so I'd recommend debug it thoroughly. If you do think this is Playwright's issue, please re-file with a reduced reproduction case that we can run & debug locally.

Thank you!
