### ISSUE TITLE
Why examples for JavaScript contains 'require' instead of 'import'? [Question]

### ISSUE THREAD

**Issue by woytekn** [microsoft/playwright#19321]
Hello,
I wonder if there is any specific reason, why 'require' is being used over 'import' in the official documentation/examples for Javascript? I know that both work almost the same, but since ES6 modules are part of the standard, shouldn't 'import' be used?

**Comment by aslushnikov** [comment]
@woytekn we are considering to update all snippets to use `import`. But yes, both `require` and `import` are functionally the same.

**Comment by aslushnikov** [comment]
We'll eventually update snippets that only run in a test runner as we have some more cycles towards documentation.
