### ISSUE TITLE
I keep getting `locator.click: Target closed` on GitHub CI while everything passes on my local environment

### ISSUE THREAD

**Issue by Onokaev** [microsoft/playwright#19322]
<img width="500" alt="image" src="https://user-images.githubusercontent.com/45680252/206128070-998de327-fb9d-44ed-bae2-3ee98ba38e14.png">
Here is a snippet of where we are experiencing the problem

**Comment by aslushnikov** [comment]
@Onokaev usually that is how a missing `await` somewhere in your test manifests itself. Please make sure that e.g. all calls to the function are awaited.

It's harder to say anything more than this without the actual repro that we can look at & debug. Feel free to re-file with a proper repro so that we can be more helpful!

**Comment by pavelfeldman** [comment]
Your report does not give us much to work with. We can't run it (we can't even copy code from an image). And you did not provide us with an actual error message - which click did not work? I can see at least 3 clicks in the snippet, you know which one failed, we don't.

When something like this happens, you should use debugging tools to locate the problem. Did you look at the trace? It would probably point you to the problem immediately. If not, could you attach it? Note that it might have sensitive information, so if that is the case you need to pass it to us via non-GitHub public channels.

---

I don't think you are missing any awaits, in fact you have more than needed:

This does not need an await:
```js
await expect(popup).toBeDefined()
```

This does not need an await, the next check is a noop, `locator` always returns something.
```js
const finalStep = await page.locator('...')
```

**Comment by Onokaev** [comment]
I have re-created the part that's causing the problem here: https://codesandbox.io/s/unruffled-lehmann-i8bb1t?file=/src/tests/sample_spec.js

My test is failing on the final click on line 52
![image](https://user-images.githubusercontent.com/45680252/207803885-b0b59925-bcb4-4a64-a0f9-3826ce2576a7.png)

**Comment by pavelfeldman** [comment]
I ran your script and it passed for me. It does not seem to follow the best practices for the authentication, but it worked. You should also remove all the toBeDefined and waitForTimeout calls, they only make the test go slower.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
