### ISSUE TITLE
[BUG] Can't run tests with playwright vscode extension on macOS

### ISSUE THREAD

**Issue by michaelgack** [microsoft/playwright#19328]
**Context:**
- Playwright Version: Playwright Test for VSCode v1.0.1 (npm v1.28.1)
- Operating System: Mac macOS Ventura
- Node.js version: 18.12.1
- Visual Studio Code version: 1.73.1
- Playwright for VSCode extension version: 1.0.1
- Browser: -
- Extra: MacBook Pro M1 Max stock

**Code Snippet**

_all stock from the examples and documentation_
![Bildschirm­foto 2022-12-07 um 11 12 01](https://user-images.githubusercontent.com/61299212/206151910-5c36498b-f087-4eab-bd80-2b3295b342f0.png)

**Describe the bug**

I closely followed the Docs on https://playwright.dev/docs/getting-started-vscode

To make it short, I can't run tests from the code-file (play button missing), can't run tests from the test menu (tests not showing up there), can run test from terminal (e.g. npm init @playwright/test, npx playwright test).

**Comment by aslushnikov** [comment]
@michaelgack do you have a playwright config file?

**Comment by michaelgack** [comment]
@aslushnikov Like i stated in my report, i followed the docs "[Getting started - VS Code](https://playwright.dev/docs/getting-started-vscode)" closely, so after the step "Test: Install Playwright" all the "playwright.config.ts", the /tests and /tests-examples were created in the project folder.

**Comment by arpan-patelia** [comment]
This one looks like same as #18954 

@michaelgack How did you install npm?

**Comment by michaelgack** [comment]
I installed node(18.12.1) from nodejs.org systemwide, but i'm also using nvm on project basis in conjunction with my pure work related projects in an IDE. I have read the #18954 issue, could be the same problem, but I need to verify first. I'll get back to you when I tested the behavior with a clean state on a fresh test project.

**Comment by aslushnikov** [comment]
This does look indeed like https://github.com/microsoft/playwright/issues/18954; I'll speculatively fold this into that issue. Please come back to us if you think this is separate.
