### ISSUE TITLE
[Question] VSCode IntelliSense - Playwright Import not working automatically

### ISSUE THREAD

**Issue by RThuys** [microsoft/playwright#19329]
I'm not sure if it's a Playwright issue or a VSCode issue, but I've noticed a quite annoying issue while working with a shared project.
The question is: "**What is the correct way to implement the following?**" Because I found a work around, but it's... ugly... and the magic goes byebye 
 
### The structure
I've the following structure:

Project1 - Shared base project (lets call it baseProject)
> This project has Playwright installed and has no issues at all

Project2, Project3, ProjectX, ... (lets call them a pain in the ass)
> These projects have the baseProject as a package and have Playwright in their node_modules

### The issue

When creating a spec file, I use IntelliSense to auto import test / expect /... from the Playwright module.
In the baseProject, it works as expected. 
In the other projects it doesn't. The IntelliSense doesn't pick up the Playwright module out of the box

The other projects: 
Here we see the auto import does not work
![image](https://user-images.githubusercontent.com/20083678/206145147-9e957fe2-19de-48cb-9e0b-9ba736735539.png)

When I manually type the import everything works as it should, see the play button showing 
![image](https://user-images.githubusercontent.com/20083678/206146233-3bd053a9-e6dd-4973-b48f-0e081a0cea4b.png)

My solution: Ok, I'll export Playwright from the baseProject and import it into the otherProjects: 
![image](https://user-images.githubusercontent.com/20083678/206147286-a5202732-a42c-4ac2-a37d-db8da2cb0063.png)

This looks promising! We see that it knows its from Playwright, IntelliSense is working, so it's fixed right? Well no... Now my Playwright Test for VSCode is not detecting any tests...  (don't mind the structure, its a PlayFull environment) 
![image](https://user-images.githubusercontent.com/20083678/206147883-e600feac-d816-4134-b8b1-3d37e2f41db5.png)
I do noticed that, once I imported the Playwright library manually, with for example expect, the IntelliSense starts working automatically
![image](https://user-images.githubusercontent.com/20083678/206149160-cb4022d0-ac6c-4f64-b6ab-925b24d16adf.png)

So Ok, let's try something else... Lets create a 'service' that imports Playwright for me in the other projects
![image](https://user-images.githubusercontent.com/20083678/206150296-b7e5e351-c67d-436d-ad14-1779ff043d1d.png)
Ok this seems to work? Yes, this does work... But this ain't a good solution in my eyes. I kinda loose the power of the baseProject because I have to create that service in all my other projects. 

### Moral of the story

There is a way around my issues, that's why it is not a bug and I'm not sure if its Playwright or VSCode causing the issue. But if I'm doing something wrong, how can I fix this? What approach should I take on this matter?

**Comment by RThuys** [comment]
Found the solution

**Comment by YusufOzturk-Development** [comment]
@RThuys  I have the same problem ,how do u fixed?

**Comment by RThuys** [comment]
@YusufOzturk-Development I simply forgot to build my package while exporting it in my index.ts. So the export wasn't captured in my index.js

**Comment by YusufOzturk-Development** [comment]
@RThuys thanks for response
