### ISSUE TITLE
[Question] How to enable bfcache for chromium

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#19323]
Playwright version: 1.25.
I am using `@playwright/test` to run tests.

I am writing a test for web vitals like lcp, cls, fcp etc...
I want to observe how it behaves when bfcache is active.
On firefox it seems that bfcache works properly, but for chromium it seems like it is disabled by default.
I have opened the test page in headed mode and went to `Application->Cache->Back/Forward cache` and ran the test.
It complains that bf cache cannot be used because of reasons:
```text
Back/forward cache is disabled by flags. Visit chrome://flags/#back-forward-cache to enable it locally on this device.
BackForwardCacheDisabled

1 frame
https://test.local/some-test-file.html
Back/forward cache is disabled by the command line.
BackForwardCacheDisabledByCommandLine

1 frame
https://test.local/some-test-file.html
```

For test repro, it should be sufficient to just navigate in any page in chromium in headed mode, make `page.pause()` and run the test manually in devtools.
Page should be empty so that way it is eligible for bfcache.

How can we pass the flags to the chromium browser to enable bf cache?

**Comment by aslushnikov** [comment]
> How can we pass the flags to the chromium browser to enable bf cache?

@Smrtnyk You should filter out the flag from the switches that are passed by default by playwright:

```ts
const browser = await chromium.launch({
  ignoreDefaultArgs: ['--disable-back-forward-cache'],
});
```

Hope this helps!

**Comment by aslushnikov** [comment]
@Smrtnyk ah, sure!

```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  use: {
    launchOptions: {
      ignoreDefaultArgs: ['--disable-back-forward-cache'],
    },
  },
};
export default config;
```

**Comment by Smrtnyk** [comment]
Thank you
I have enabled the flag, but seems like bf cache only works in headed mode
and there is an exception coming from playwright on the page
```typescript
Error: Invalid arguments: should be exactly one string.
    at Recorder._pollRecorderMode (eval at extend (:4529:39), <anonymous>:3080:36)
    at Recorder.globalThis.__pw_refreshOverlay (eval at extend (:4529:39), <anonymous>:3044:12)
    at new Recorder (eval at extend (:4529:39), <anonymous>:3046:16)
    at InjectedScript.extend (<anonymous>:4535:12)
    at eval (eval at evaluate (:191:30), <anonymous>:5:29)
    at UtilityScript.evaluate (<anonymous>:193:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```
it doesn't happen without the bf cache triggered

**Comment by Smrtnyk** [comment]
is this maybe known @aslushnikov ?

**Comment by aslushnikov** [comment]
@Smrtnyk ah yes, actually, I don't think that CDP properly supports back-forward cache at this moment: https://bugs.chromium.org/p/chromium/issues/detail?id=1317959

So there's no way to properly automate chromium with this option turned "on".

**Comment by Smrtnyk** [comment]
oh, ok, that explains it then, thank you
I will try to see if I can have some tests with bf cache on webkit and ff at least

**Comment by rviscomi** [comment]
The linked [Chromium issue](https://issues.chromium.org/issues/40222714) seems to have been marked fixed in the recent weeks. Does that unblock progress on this issue?

**Comment by aabccd021** [comment]
> It actually works now for me when using headless=new

Would you mind sharing your working configuration (+playwright version) ? 

I've been trying to  enable bfcache in headless mode with `channel: "chromium` and `ignoreDefaultArgs: ['--disable-back-forward-cache']`
 but no luck so far.
