### ISSUE TITLE
[Question] Support JSX

### ISSUE THREAD

**Issue by testerez** [microsoft/playwright#19333]
Hello, I'd like to import some JSX files in my test files. My use case is to import test helpers from my main codebase. Those include JSX code.

Right now, when I import those files, I get this kind of errors:
```
SyntaxError: Unexpected token '<'
```

Is there a simple way to add JSX support to `playwright test`?

**Comment by aslushnikov** [comment]
> Is there a simple way to add JSX support to playwright test?

@testerez The simplest would probably be splitting helpers into those with jsx and those without it. Would this work?

**Comment by testerez** [comment]
It's certainly possible but not super easy considering my codebase. If I could just enable JSX support in playwright build, that would make my life easier for sure.

**Comment by aslushnikov** [comment]
@testerez so it looks like we do have some transpilation in place. Any chance you can come up with a small repo that illustrates your issue?

**Comment by testerez** [comment]
Right, I realize it does support JSX. The error I get is on a JSX fragment. Looks like it does not support it.
Example JSX:

```jsx
const test = <><div/><div/><>
```

**Comment by luke-john-atlassian** [comment]
FYI -- this looks like a duplicate of https://github.com/microsoft/playwright/issues/19142

**Comment by aslushnikov** [comment]
Ah indeed, thank you! Folding into https://github.com/microsoft/playwright/issues/19142 then.
