### ISSUE TITLE
[Feature] skip test.step

### ISSUE THREAD

**Issue by SirCmX** [microsoft/playwright#19332]
I would like to ask for a feature to skip test.steps like you can use test.skip()

I have a scenario, where I would like to skip a condition like change a state of an object.
After that, check the history to see if the change has been documented.

For example : 

Boolean : object_state_already_changed = true;
await test.step(`Change state of Object`, async () => {
        test.step.skip(object_state_already_changed);
        await page.locator()
}
await test.step(`Check history`, async () => {
  await expect()
}

**Comment by aslushnikov** [comment]
Folding this into https://github.com/microsoft/playwright/issues/10033
