### ISSUE TITLE
[BUG] timezoneId not being applied to new tabs

### ISSUE THREAD

**Issue by Tyron199** [microsoft/playwright#19334]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: 16.13.1
- Browser: Chromium

```javascript
const {chromium} = require('playwright');

(async () => {
 
  const browser = await chromium.launchPersistentContext("test", {
        headless: false,
        timezoneId: "America/Los_Angeles",
    });

})();
```

Just running this basic script, you will see that if you open 2 additional tabs, the 3rd tab will not have timezoneId applied.
If you first navigate a tab, the next tab will work properly but for some reason if you create 2 new tabs, the last one wont work.

![chrome_QyJLKvo2Ei](https://user-images.githubusercontent.com/6433549/206195266-995dfa71-a650-45ef-8e18-cea8e586e638.gif)

**Comment by aslushnikov** [comment]
@Tyron199 this is indeed a bug in CDP. Filed upstream: https://crbug.com/1399917

**Comment by aslushnikov** [comment]
This is fixed upstream now. We missed the Chromium M110 branch by one day, so it won't make it in Chrome 110 and Playwright 1.30. Expect this to work in Chromium M111 and Playwright 1.31 then!
