### ISSUE TITLE
[BUG] Page resizes on load, disregarding command line arguments

### ISSUE THREAD

**Issue by mhkeller** [microsoft/playwright#19342]
**Context:**
## System:
 - OS: macOS 12.6.1
 - Memory: 98.27 MB / 32.00 GB
## Binaries:
 - Node: 16.16.0 - /usr/local/bin/node
 - npm: 8.11.0 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.28.1 => 1.28.1 
 
**Code Snippet**

```javascript
import { chromium } from 'playwright';

const context = await chromium.launchPersistentContext('./foo', {
  args: [
    `--app=data:text/html,`,
    '--window-size=200,600',
    '--window-position=100,10',
    '--test-type=',
  ],
  ignoreDefaultArgs: ['--enable-automation'],
  headless: false,
});
```

**Describe the bug**

The page opens up initially at the correct size of 200 by 600 but then resizes to much larger. I am using @aslushnikov's code from [here](https://github.com/microsoft/playwright/issues/16598#issuecomment-1218088727). The expected behavior is for the window to stay the correct size. 

Here is a video of the bug:

https://user-images.githubusercontent.com/498744/206302090-b0f28892-5753-42b7-b9c9-6191885548fc.mov

**Comment by aslushnikov** [comment]
@mhkeller just add the `viewport: null` to the arguments:

```ts
import { chromium } from 'playwright';

const context = await chromium.launchPersistentContext('./foo', {
  args: [
    `--app=data:text/html,`,
    '--window-size=200,600',
    '--window-position=100,10',
    '--test-type=',
  ],
  viewport: null,
  ignoreDefaultArgs: ['--enable-automation'],
  headless: false,
});
```

**Comment by mhkeller** [comment]
Thanks! That works great!
