### ISSUE TITLE
[BUG]: Seeing some unexpected character in json file generated through reporter.

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#19348]
Playwright Version: "@playwright/test": "^1.26.1"
Operating System:Mac
Node.js version: v16.17.0
Browser:WebKit

I am using the json option to get the report in json format in playwright.config.ts as mentioned above  
reporter: [['html'],
            ["json", { outputFile: "./src/test-results/test-result.json" }], 

But in the json report generated getting some random characters as mentioned below **( \u001b[2m-)**

 "error": {
                        "message": "Error:  Link not visible**\n\nCall log:\n  \u001b[2m-** expect.toBeEnabled with timeout 50000ms\u001b[22m\n\u001b[2m  -   waiting for frame \"xpath=//iframe[contains(@name,'MainPortal')]\"\u001b[22m\n\u001b[2m  -   selector resolved to visible <iframe tabindex=\"0\" width=\"100%\" height=\"100%\" framebor…></iframe>\u001b[22m\n\u001b[2m  - waiting for selector \"//iframe[contains(@name,'MainPortal')] >> control=enter-frame >> text='Look ABCD'\"\u001b[22m\n",
                        "stack": "Error: Link not visible\n\nCall log:\n  \u001b[2m- expect.toBeEnabled with timeout 50000ms\u001b[22m\n\u001b[2m  -   waiting for frame \"xpath=//iframe[contains(@name,'MainPortal')]\"\u001b[22m\n\u001b[2m  -   selector resolved to visible <iframe tabindex=\"0\" width=\"100%\" height=\"100%\" framebor…></iframe>\u001b[22m\n\u001b[2m  - waiting for selector \"//iframe[contains(@name,'MainPortal')] >> control=enter-frame >> text='Look ABCD'\"\u001b[22m\n\n    at Page.funcname(/Users/xxxxx/Documents/xxxx/src/pages/xxxxx/xxxx.ts:159:88)\n    at /Users/xxxxx/Documents/xxxxxxtests/xxxxxx/xxxx.test.ts:79:9"
                      },

**Comment by aslushnikov** [comment]
These are jest's errors and they are highlighted for terminal using the ANSI codes. 

Please check out the discussion here: https://github.com/microsoft/playwright/issues/13522
