### ISSUE TITLE
[Question] Playwright error "apiRequestContext.post: unable to get local issuer certificate"

### ISSUE THREAD

**Issue by subhabratapal** [microsoft/playwright#19351]
While trying to hit POST API call, getting an error: "**apiRequestContext.post: unable to get local issuer certificate**"

```ts
//playwright.config.js
use: {
      // Configure browser and context here
      baseURL: "https://xxxxxxx/hhhhh/api/mail/validate",
      extraHTTPHeaders :{
         "Content-Type": "application/json; charset=UTF-8",
         "ignoreHTTPSErrors": "true",
        "Authorization" : "Bearer bdbdgtrgfhksns1827hdhdV1QiLCn"
      }
    },

// api.spec.js

test('test', async ({request, baseURL }) => {
      const response = await request.post(baseURL, {
      data:{
        "subject": "Testing mail api",
        "body": "mail body",
        "isHighImportance": false,
        "from": "abcd@sdef.com",
        "to": "mnop@sdef.com",
        "cc": null,
        "bcc": null,
        "replyTo": null
      }        
      });

});
```
This is a SSL error - but how to resolve it? is there any tag within header that needs to be added?

**Comment by aslushnikov** [comment]
@subhabratapal it looks like you're using self-signed certificates. In this case, you might need to use something like 
 [`NODE_TLS_REJECT_UNAUTHORIZED=0`](https://nodejs.org/api/cli.html#node_tls_reject_unauthorizedvalue) env variable.

You might also need to set the `NODE_EXTRA_CA_CERTS` env variable. Check out the discussion in https://github.com/microsoft/playwright/issues/18467

This is as much as I can tell without being able to repro this. Closing this. If it still doesn't work for you, feel free to re-file the issue with a repro steps that we can run locally to debug the issue!

**Comment by subhabratapal** [comment]
@aslushnikov 
Thanks you :)
"NODE_EXTRA_CA_CERTS" worked by setting it as Env Variable

**Comment by mbaggu** [comment]
> @aslushnikov Thanks you :) "NODE_EXTRA_CA_CERTS" worked by setting it as Env Variable

Hi can u pls explain how did u set the env variable. I have gone thru the link but it's quite confusing... 

First thing I am not able to generate rootCA.pem at all.. pls explain

**Comment by subhabratapal** [comment]
Hi,

U need to set "NODE_EXTRA_CA_CERTS" as Env Variable and point the "PEM"
file location.
Now, rootCA.pem file needs to be generated based on ur Org. i.e., for me I
raised a request in our Org security team. Pls check with them.

**Comment by mbaggu** [comment]
Environment variables means system environment variables? 

I will try to get rootCA.pem file from IT team...
