### ISSUE TITLE
[Question] Global setup API request context can use the browser.cotext.setHTTPHeaders?

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#19355]
Hello!
So I'm enriching browser HTTP headers using fixture override like so:
```
context: async ({ context }, use) => {
      await context.setExtraHTTPHeaders(headers);
    await use(context);
},
```
This also creates a new APIRequestContext for use with the page.request  API,
but it doesn't affect the global { request } imported from @playwright/test which I'm not sure where it initializes from, right?

I want to create a Global Setup to store storageState.json and share it between my isolated tests.

Following this guide: https://playwright.dev/docs/auth#sign-in-via-api-request
importing `{ request } imported from @playwright/test` won't use my HTTP headers enrichment of the browser.context previously made, right?

I'll be glad to have assistance regarding if is it possible to use the same extraHttpHeaders with the global setup file that i've used during the fixture override.

**More information about how i receive my headers:**
the fixture override get it's headers from custom option defintion that extends at the playwright.config.ts.
, like so:
fixture.ts:
`headersForMyCase: [{ use: false, headers: {} }, { option: true }],`
playwright.config.ts:
```
const globalConfig: PlaywrightTestConfig<CustomOptions> = {
use {
headersForMyCase = {
        use: true,
        headers: {
          'x-riskified-dynamicenv': process.env.DYNAMIC_ENV_HEADER,
        },
      };
}
```

**Comment by yury-s** [comment]
> This also creates a new APIRequestContext for use with the page.request API, but it doesn't affect the global { request } imported from @playwright/test which I'm not sure where it initializes from, right?

Global request is an APIRequest which can be used to create APIRequestContext manually. It will get all the options that you pass manually.

It looks like what you are asking about is [request fixture](https://playwright.dev/docs/api/class-fixtures#fixtures-request) which initializes APIRequestContext with corresponding context parameters. You can override it similar to the context fixture if you want. But by default it will inherit all the context extra headers automatically, you just need to use it as a fixture instead of global import:

```ts
import { test, expect } from '@playwright/test';

test.use({
  extraHTTPHeaders: {
    'foo': 'bar';
  }
})

test('test', async ({ request }) => {
  await request.get('...');
});
```

Will that work for you?

**Comment by ValorHeart** [comment]
Hi @yury-s Thanks for the reply,
I wanted to ask is if i can have one source of truth for using extraHttpHeaders for both the tests (Like you examined in the comment) and Global setup file, which runs before the tests and doesn't automatically receives the tests fixtures

Thanks, Adi

**Comment by yury-s** [comment]
Global setup function is called with a [config object](https://playwright.dev/docs/test-advanced#global-setup-and-teardown), you can read the option from it, something like this:

```ts
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

type CustomOptions = {
  headersForMyCase: { [key: string]: string; };
}

export type MyConfig = PlaywrightTestConfig<CustomOptions>;

const config: MyConfig = {
  use: {
    headersForMyCase: {
        'foo': 'bar',
    }
  },
  testDir: './tests',
  globalSetup: 'tests/global-setup.ts',
}

// tests/global-setup.ts
import { MyConfig } from '../playwright.config';

async function globalSetup(config: MyConfig) {
    const headers = config.projects?.[0].use?.headersForMyCase;
    console.log(headers);
    console.log('\n');
}
export default globalSetup;
```

Does this answer your question?

**Comment by aslushnikov** [comment]
Closing as per above. Feel free to file another issue if you think we can help you!
