### ISSUE TITLE
[Question]: wait_for_url does not work with redirects

### ISSUE THREAD

**Issue by JorisBoelen-TomTom** [microsoft/playwright#19352]
### Your question

We have an application to login to an AWS account using AzureAD as SAML provider. Basically we launch a browser, let the user authenticate, extract the SAML response and close the browser. 

Below is a simplified version:
```
from playwright.sync_api import sync_playwright
from urllib.parse import parse_qs

SIGNIN_URL = 'https://account.activedirectory.windowsazure.com/applications/signin/****?tenantId=****'
SAML_URL = 'https://signin.aws.amazon.com/saml'


def parse_request(request):
    if request.url == SAML_URL:
        saml = parse_qs(request.post_data)['SAMLResponse'][0]
        print(saml)


def main():
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=False)
        context = browser.new_context()
        page = context.new_page()
        page.goto(SIGNIN_URL)
        page.on("request", parse_request)
        page.wait_for_url(SAML_URL)
        browser.close()


if __name__ == "__main__":
    main()
```

If a user is eligible to assume multiple roles in AWS, the SAML_URL (https://signin.aws.amazon.com/saml) will return a HTTP-200 and the `page.wait_for_url(SAML_URL)` works. 

However, when a user is eligible to assume a single role, the SAML_URL (https://signin.aws.amazon.com/saml) will return a HTTP-302 and gets redirect to a different page. In that case the `page.wait_for_url(SAML_URL)` doesn't do anything, it gets ignored.

Is this expected behaviour? If so, what would be a better approach to wait for this URL to be hit? (even if the result is a redirect?). The application SAML2AWS does something similar in Go: https://github.com/Versent/saml2aws/blob/49701e7d9563da09ad93f13db0cb5bd90a57bbc4/pkg/provider/browser/browser.go#L55 using `waitForRequest`, but that doesn't seem to be available in Python: https://github.com/microsoft/playwright-python/issues/1665

**Comment by aslushnikov** [comment]
@JorisBoelen-TomTom the page itself doesn't transition throgh the URL with 302 HTTP code. Instead, the main document request gets redirected. For example, you will never see a redirect URL in the browser URL bar. The `page.waitForURL()` assumes exactly this: browser URL bar.

Does this explanation make sense?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
