### ISSUE TITLE
[BUG] Only on firefox I get "Test timeout of  xxxms exceeded while tearing down "context"."

### ISSUE THREAD

**Issue by ImanDPG** [microsoft/playwright#19354]
**Context:**
- Playwright Version: same issue on 1.27, 1.28 and latest version "^1.29.0-alpha-dec-8-2022"
- Operating System: MacOS Venstura
- Node.js version: v18.11.0
- Browser: Firefox and Chrome 
- Extra: Chrome has no problem with the same test, the issue is only with Firefox 

**Code Snippet**

```
test(`Click on a random subsection then validate the navigation to the correct subsection ${brand.name}`, async ({
                page,
            }) => {
                await applyCookies(brand, page);

                const homeFeedPage = new HomeFeedPage(page);
                await homeFeedPage.gotoHomePage(brand);

                homeFeedPage.generateRandomNumber(0, 25).then(async (randomNumber) => {
                    const subSectionLocator = page.locator(`div.section__header>div>a>span>>nth=${randomNumber}`);

                    const randomSubSectionName = await subSectionLocator.innerText();
                    expect(subSectionLocator.isVisible());
                    subSectionLocator.click();
                    let randomSubSectionNameWithNoSpaces = randomSubSectionName?.trim().toUpperCase();
                    const subSectionHeaderLocator = page.locator(`div.page-element-title-overview>div>div>h1`);
                    expect.soft(subSectionHeaderLocator.isVisible());
                    const subSectionHeaderName = await subSectionHeaderLocator.textContent();
                    let subSectionHeaderNameWithNoSpaces = subSectionHeaderName?.trim().toUpperCase();
                    await expect(randomSubSectionNameWithNoSpaces).toContain(`${subSectionHeaderNameWithNoSpaces}`);
```

```

**Describe the bug**

I try to run the above test, I always get the below error with firefox, while it's working fine on chrome, I also noticed that firefox browser close right away when I run headful, tried using debug mode and I also tried to enlarge the test timeout till 1200000ms but still not working, and I receive the below error, please note that it sometimes work but very rare and for no specific reason which makes me feel that its not really reliable
```
locator.textContent: Target closed
=========================== logs ===========================
waiting for locator('div.page-element-title-overview>div>div>h1')
============================================================

  25 |                     const subSectionHeaderLocator = page.locator(`div.page-element-title-overview>div>div>h1`);
  26 |                     expect.soft(subSectionHeaderLocator.isVisible());
> 27 |                     const subSectionHeaderName = await subSectionHeaderLocator.textContent();
     |                                                                                ^
  28 |                     let subSectionHeaderNameWithNoSpaces = subSectionHeaderName?.trim().toUpperCase();
  29 |                     await expect(randomSubSectionNameWithNoSpaces).toContain(`${subSectionHeaderNameWithNoSpaces}`);
  30 |                 });

Test timeout of 1200000ms exceeded while tearing down "context".
```

**Comment by aslushnikov** [comment]
@ImanDPG can you come up with a repro that we can run locally to debug this?

**Comment by ImanDPG** [comment]
@aslushnikov I created this repo with a sample test where the firefox is only giving an error so that you can debug it locally 
https://github.com/ImanDPG/troubleshoot
Please update me

**Comment by yury-s** [comment]
@ImanDPG you forgot to `await` in [this line](https://github.com/ImanDPG/troubleshoot/blob/f27d17fe47f3cd378c856465455ec5b1c28a564e/tests/feature/desktop/ui/allBrands/subSectionNavigation.test.ts#L17), changing it to the following makes the test pass:

```js
await homeFeedPage.generateRandomNumber(0, 25).then(async (randomNumber) => {
```
Without await everything inside `(async (randomNumber) => {` may continue running after the test has finished and the browser/page has been closed.

Note that there is another missing await before subSectionLocator.click(); too.
