### ISSUE TITLE
[Question] Conditional environment variables

### ISSUE THREAD

**Issue by michelle-choi1** [microsoft/playwright#19366]
Hi! Is there a way to assign environment variables conditionally aside from using the command line?
What I am guessing may be possible pathways:

- if condition in `global-setup.js`, and then export the variable?
```js
import { chromium, FullConfig } from '@playwright/test';

let testEnv = process.env.project;

if (testEnv === "staging") {
  process.env.API_URL = 'https://api.sitedev.com/v1'
} else if (testEnv === "qa1") {
  process.env.API_URL = 'https://qa1.api.sitedev.com/v1'
} else if (testEnv === "qa2") {
  process.env.API_URL = 'https://qa2.api.sitedev.com/v1'
} else if (testEnv === "production") {
  process.env.API_URL = 'https://api.site.com/v1'
}

module.exports = async config => {
  process.env.API_URL;
};
```

- in `playwright.config.js`, is it possible to set an environment variable there under project configs? I think this would be cleanest!
```js
projects: [
    {
      name: 'Staging',
      // retries: 3,
      use: {
        baseURL: `https://store${process.env.STOREID}.sitedev.com/`,
        process.env.API_URL: 'https://api.sitedev.com/v1'
      }
    },
    // ... (and so on with other env's)
]
```

- setting the env variable in command line - this is the option I'm currently using, but it would be nice to parameterize the `API_URL` field so I can just quickly invoke it when I switch the environment! Any tips on using variable in the `API_URL` spot in the call?
```
STOREID=... API_AUTH='...' API_URL='...' npx playwright test ./live-tests/stream-b/reviews.spec.js --config=playwright.config.js --project=staging
```

Btw, thank you so much playwright team/community for the prompt responses to all my questions/issues so far. Your help has been really invaluable to me!

**Comment by aslushnikov** [comment]
@michelle-choi1 you can assign `process.env` as part of your config and `global-setup` files! Your first snippet is perfectly fine with this regard.

Hope this helps!

**Comment by michelle-choi1** [comment]
thank you @aslushnikov! for `let testEnv = process.env.project`, I was trying to use the flag `--project=...` that `playwright.config.js` uses as part of the projects config. it turns out that `testEnv` is undefined though, so I'm concluding that the flag `--project=...` is not something I can use. is that the right conclusion?

**Comment by aslushnikov** [comment]
@michelle-choi1 ah, you wanted to have it based on the project! Now I see.

yeah, this is not somethings that's possible when it comes to env variables: these only support the simplest configuration.

If you want to customize some variables as part of the test execution, e.g. have an `API_URL` different based on the project, i'd recommend using fixture options: https://playwright.dev/docs/next/test-fixtures#fixtures-options

**Comment by michelle-choi1** [comment]
@aslushnikov oh, that sounds great! yeah, will look into how to use fixture options. Thank you!!
