### ISSUE TITLE
File Upload with page.setInputFiles(locator,filepath) throws net::ERR_ABORTED error

### ISSUE THREAD

**Issue by msabya** [microsoft/playwright#19362]
I have an input type=file element is defined as follows
<input type="file" name="file" data-testid="file-input-undefined" id="file-input-select-undefined" multiple="" accept=".pdf">

I am initiating FileUpload functionality  by locating the above element. The code snippet for the same is as below. locator isn the xpath value of the above element
 await page.setInputFiles('(//*[@id="file-input-select-undefined"])[3]',file_path);

The setInputFiles method is throwing me the below error and uploading is not happening. While playwright passes this step but actual upload is not achieved.

![image](https://user-images.githubusercontent.com/28334629/206500853-9d84e5a4-0e21-420b-bf92-63f7c89ad6ea.png)

**Comment by msabya** [comment]
Hi Any update ... can some one be assigned to help out on this issue...
Let me know if any further updates are required ...

**Comment by aslushnikov** [comment]
@msabya it looks like the server aborts the upload. Is there a repro we can try running locally? This way we'd be able to debug stuff and see.

**Comment by msabya** [comment]
I have pinged you in the slack channel ... let me know your availability and we can run this locally to trace it out

**Comment by aslushnikov** [comment]
(responded in slack)

**Comment by aslushnikov** [comment]
> I have pinged you in the slack channel ... let me know your availability and we can run this locally to trace it out

@msabya I'm afraid the one-on-one debugging sessions do not scale. 

Could you please re-file this issue with a repro? Once we have a repro, someone from the team or community might be able to tackle this independently as they have time.
