### ISSUE TITLE
[Question] What makes Playwright faster than Selenium, Cypress and other browser testing frameworks?

### ISSUE THREAD

**Issue by thekp** [microsoft/playwright#19376]
Hi,

I understand Playwright communicates with the browser engine with a web-socket connection, as opposed to the other frameworks and Playwright also has auto-awaiting.

Can anyone help me get a deep understanding of the technicalities that make Playwright so much faster than other frameworks?

P.s I am asking about the runtime speed of a test

**Comment by aslushnikov** [comment]
We don't have a white paper explaining Playwright architecture. You're very welcome to poke at the code - Playwright is 100% open-source!
