### ISSUE TITLE
[Question] How do I view the metrics of the page?

### ISSUE THREAD

**Issue by Fhui** [microsoft/playwright#19373]
I'm now ready to replace the puppeteer with playwright, but I found that there is no API to view the page metrics.

like [puppeteer metrics](https://zhaoqize.github.io/puppeteer-api-zh_CN/#?product=Puppeteer&version=puppeteer-v19.4.0&show=api-pagemetrics)

**Comment by aslushnikov** [comment]
Folding this into https://github.com/microsoft/playwright/issues/18071
