### ISSUE TITLE
[BUG] Problem in Focus on chromium

### ISSUE THREAD

**Issue by joannajerz** [microsoft/playwright#19383]
**Context:**
- Playwright Version: 1.27.1
- Operating System: Windows
- Node.js version: 18.12.1
- Browser: Chromium
- Extra: Works on Firefox

Hi, i have problem with focus(). This code works on firefox, on chromium unfortunately no.
Do you have some idea:
```
await product.focus()
await page.waitForTimeout(3000)
await expect(productsSimilar.productsSimilarContainer).toBeVisible()
```

**Comment by aslushnikov** [comment]
@joannajerz focusing elements doesn't make them visible. It's hard to say for sure why things work in firefox for you and don't work in chromium with this much information.

Without actual code in hands that we can run locally & debug, there's not much we can do. Could you please re-file this issue with a repro that we can run locally to take a look?

**Comment by joannajerz** [comment]
Unfortunetly i don't have this problem in public repo but the steps look like that:
1. I click in anchor. Anchor open new page in new tab. I also trigger onClick with focus inside.
` const onClick = useCallback(async(id: number, index:number, event) => {
     onfocus = async() => {
         setIsVisibleSimilarProduct(true);
                }
            };
 }, [isVisibleSimilarProduct]);`

3. I close new tab and go back to my page (and get focus to setVisible container)
4. I trigger focus in my onclick function. But this code below doesn't work:

` const data = await response.json()

        if(data.length > 3) {

            await product.click()

            const [newPage] = await Promise.all([

                context.waitForEvent('page')

            ])

            await newPage.close()

            await page.bringToFront()

            await product.scrollIntoViewIfNeeded()

            await product.focus()`
