### ISSUE TITLE
Does artillery integration with playwright support UI Load Testing with Multi Concurrent users for Dynamics 365

### ISSUE THREAD

**Issue by ksatishcrm** [microsoft/playwright#19386]
Can you let us know if Artillery integration with playwright support UI Load Testing with Multi Concurrent users for Dynamics 365?
Any idea if Artillery integration with playwright only supports UI load testing or only API testing? 
In the earlier post https://github.com/microsoft/playwright/issues/18487 as mentioned we wanted to run load test with 500 concurrent users.

Link for Artillery integration with playwright: https://github.com/artilleryio/artillery/tree/main/examples/browser-load-testing-playwright

**Comment by aslushnikov** [comment]
@ksatishcrm We don't know much about the integration; I'd recommend asking this question at artillery repository.
