### ISSUE TITLE
[Feature] add `toHaveCountGreaterThan` and `toHaveCountLessThan` locator assertions

### ISSUE THREAD

**Issue by alvaromartmart** [microsoft/playwright#19381]
Playwright currently offers the `LocatorAssertions.toHaveCount` function, that allows to expect -with wait- for a locator to have an exact count.
```ts
await expect(someLocator).toHaveCount(1);
```
However, it doesn't provide an out of the box way for asserting on non-exact counts.

The proposal here is to add the following additional functions:
```ts
await expect(todoLocator).toHaveCountGreaterThan(2);
await expect(recentTodoLocator).toHaveCountLessThan(4);
```

See related: https://github.com/microsoft/playwright/issues/14278#issuecomment-1343970254

**Comment by mxschmitt** [comment]
Workaround for now

```ts
  await expect.poll(async () => page.locator('div').count()).toBeGreaterThan(5);
```

**Comment by aslushnikov** [comment]
A new alternative workaround with 1.29 release is the `expect().toPass()` matcher:

```ts
await expect(async () => {
  const count = await page.locator('div').count();
  expect(count).toBeGreaterThan(5);
).toPass();
```

We think `expect.poll` and `expect().toPass()` approaches are good-enough; otherwise, we'll end up duplicating all expect matchers as the web-first assertions which will add churn to the API.
