### ISSUE TITLE
[Question] Why does .isVisible() return immediately?

### ISSUE THREAD

**Issue by Eloy2** [microsoft/playwright#19396]
I work as a QA engineer and I use playwright every day. I was wondering why .isVisible() returns immediately. It would be useful for me and a lot other QA engineers I work with if .isVisible() would wait up to the default 30 seconds. 🙏 

I think it's useful to have it wait up to 30 seconds because then I can use it in an if statement. Like this:

```js
if ( await page.isVisible(`selector`) ) {

 // do something

} else {

 // do something else

}
```

Currently I have to do something like this:

```js
try {
 await expect(locator).toBeVisible();

// do something

} catch {

// do something else

}
```

It seems like that was the case before but then it was deprecated. Is there a benefit to it returning immediately?

**Comment by gauravgandhi1315** [comment]
what is your use case? You can add `wait` command for 30 seconds

**Comment by yury-s** [comment]
> Is there a benefit to it returning immediately?

All Playwright actions automatically wait for the element to become visible so one shouldn't need to call this method before any actions to wait for actionability. You can still call isVisible to check if an element is visible (e.g. after previous actions) and will not wait. If you know that an element must become visible within a certain timeout you should use [expect(locator).toBeVisible](https://playwright.dev/docs/test-assertions#locator-assertions-to-be-visible) instead.

The better approach would be to determine which branch to proceed using a condition that doesn't involve a 30 seconds timeout - maybe some flag in the page's code that would tell you if the element is going to show up at all.

**Comment by 8LO8** [comment]
@yury-s Then what is a proper way to do:
await expect.soft(page.getByRole('cell', { name: projectName, exact: true })).toBeVisible();
if(await page.getByRole('cell', { name: projectName, exact: true }).isHidden()){
logger.info(`Project is not visible: ${projectName}`);
}
await page.getByRole('cell', { name: projectName, exact: true }).click();
logger.info(`Project is selected for testing: ${projectName}`);

**Comment by 8LO8** [comment]
> > Is there a benefit to it returning immediately?
> 
> All Playwright actions automatically wait for the element to become visible so one shouldn't need to call this method before any actions to wait for actionability. You can still call isVisible to check if an element is visible (e.g. after previous actions) and will not wait. If you know that an element must become visible within a certain timeout you should use [expect(locator).toBeVisible](https://playwright.dev/docs/test-assertions#locator-assertions-to-be-visible) instead.
> 
> The better approach would be to determine which branch to proceed using a condition that doesn't involve a 30 seconds timeout - maybe some flag in the page's code that would tell you if the element is going to show up at all.

Then how to write the following correctly?

```
await expect.soft(page.getByRole('cell', { name: projectName, exact: true })).toBeVisible();
if(await page.getByRole('cell', { name: projectName, exact: true }).isHidden()){
logger.info(`Project is not visible: ${projectName}`);
}
await page.getByRole('cell', { name: projectName, exact: true }).click();
logger.info(`Project is selected for testing: ${projectName}`);
```
