### ISSUE TITLE
Issue #19367 not resolved :I tried using an external variable and I dont think that will resolve the issue. My main question was what should be the exit criteria in the toBe ?

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#19393]
why are we closing requests without ensuring whether the solution provided works? Here in this case I can use an external variable. But my main question was what should be the exit criteria in the toBe ?

As the condition toBE depends on the returning object which is data in this case(long response body from the api), what condition can I put in the toBe block?

_Originally posted by @JasKirk70 in https://github.com/microsoft/playwright/issues/19367#issuecomment-1344894502_

**Comment by aslushnikov** [comment]
(replied in the original issue!)
