### ISSUE TITLE
[Question] Get test timeout value

### ISSUE THREAD

**Issue by anastasiyamazheika** [microsoft/playwright#19407]
Dear Playwright team,
Is it possible somehow to get a test timeout value? In some cases, I override the default timeout with a custom one and I need to get this value through the code to modify the wait time in some locators.

Thanks!

**Comment by yury-s** [comment]
You can read and set the timeout value using [testInfo.timeout](https://playwright.dev/docs/api/class-testinfo#test-info-timeout):

```js
test('test', async ({ page }) => {
    const timeout = test.info().timeout;
    console.log('timeout = ' + timeout);
});
```
