### ISSUE TITLE
[Feature] Add video type 'application/vnd.apple.mpegurl' to Chromium

### ISSUE THREAD

**Issue by dmontes7** [microsoft/playwright#19404]
Hey team, 

In order to test some video types on Playwright, we are having issues with Chromium trying to load 'application/vnd.apple.mpegurl' videos. It would be nice if you can support this video type.

Thanks, best regards.

**Comment by yury-s** [comment]
Please file this in Chromium repository (https://crbug.com/) as support for such videos is a Chromium feature.
