### ISSUE TITLE
[BUG] `playwright test` does not type check `.ts` files

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#19402]
**Context:**
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 4.50 GB / 15.92 GB
## Binaries:
 - Node: 16.11.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.1.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 5.0.17 - C:\WINDOWS\system32\bash.EXE
## npmPackages:
 - playwright: ^1.28.1 => 1.28.1

**Code Snippet**

```ts
import { test } from '@playwright/test'

const foo: number = '' // no error

test('foo', () => {})
```

**Describe the bug**
when running `playwright test`, it doesn't type check `.ts` files

**Comment by aslushnikov** [comment]
This works as intended: `playwright test` is not a type checker, it uses babel to transpile code. There's `tsc` for type checking. You'll also see a red squiggly line in VSCode.

**Comment by DetachHead** [comment]
@aslushnikov other test runners like [ts-jest](https://www.npmjs.com/package/ts-jest) type check the tests before running them, and i can't imagine why you wouldn't want your `.ts` files type checked before they're run, so imo it makes sense for the test runner to handle the type checking.
