### ISSUE TITLE
get Response object in custom reporter [Question]

### ISSUE THREAD

**Issue by shobu13** [microsoft/playwright#19403]
Hello, is it possible to get response (#5632) object form a custom reporter in PW typescript ?
I need to fetch resources and transferred size in a custom reporter but this informations seems not to be present in the base hooks of the API.

**Comment by yury-s** [comment]
You can store arbitrary data including information about the responses as an attachment via [testInfor.attach](https://playwright.dev/docs/api/class-testinfo#test-info-attach) call in the test and then read it in the reporter from [testResult.attachments](https://playwright.dev/docs/api/class-testresult#test-result-attachments). Will that work for you?

**Comment by shobu13** [comment]
Yeah i've seen that solution but that implying calling the function after each test request, it do the job but i search for an automated solution than can be used without involving adding too much code to the tests.

**Comment by yury-s** [comment]
You can leverage fixtures or even [automatic fixtures](https://playwright.dev/docs/test-fixtures#automatic-fixtures)  to automatically add the network listeners that would collect response data and save it as attachments. This way you wouldn't have to touch every test manually to record the responses.

Closing the issue as there is a solution for the problem and there are no plans to extend existing API to address this scenario in a different way.
