### ISSUE TITLE
[REGRESSION]: Can't find selector using regex

### ISSUE THREAD

**Issue by mpaczula** [microsoft/playwright#19405]
**Context:**
- GOOD Playwright Version: 1.27.1
- BAD Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: 19.0.0
- Browser: Chromium

**Code Snippet**

```
const item = this.listItems
      .filter({ hasText: itemName })
      .filter({ hasText: new RegExp(`^${getUiWeekdays(itemWeekdays)}$`) });
```

selector in Playwright 1.27.1:
list >> .list-item >> internal:has="text=z-20221212-bsqg" >> internal:has="text=/^Mon$/"

selector in Playwright 1.28.1:
list >> .list-item >> internal:has-text="z-20221212-bsqg"i >> internal:has-text=/^Mon$/

full X-Path:
/html/body/app-root/div/app-view/app-side-menu-layout/dx-drawer/div/div[2]/div[2]/app-item-creation-view/div[2]/div/div[1]/dx-scroll-view/div[1]/div/div[1]/div[2]/div/app-item-list/div[92]/div[2]/div[1]/p[1]

**Describe the bug**

Selector was properly located using regex for v1.27.1, after updating to v1.28.1 it cannot be found (there is an i added after first text but not after the second one)

**Comment by yury-s** [comment]
Please attach the page where it fails with a complete test code which we could run to reproduce this locally.

**Comment by yury-s** [comment]
This is good enough, thank you!

**Comment by mpaczula** [comment]
@dgozman it does, thanks for the info
