### ISSUE TITLE
[Question] Config 'storageState' relative path to playwright folder?

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#19400]
Hello, so my global config saves the storageState.json file in rootDir like so:
```
import { type FullConfig, request } from '@playwright/test';

const globalSetup = async function (testConfig: FullConfig<CustomOptions>) {

   ............

    // Save state to 'storageState.json'.
    await requestContext.storageState({
      path: `${testConfig.rootDir}/storageState.json`,
    });

};

export default globalSetup;
```

the variable testConfig.rootDir returns the playwright folder.

My issue, is that i want to use the same folder when loading the storageState.json at the playwright.config.ts option:
use: {
storageState: 'storageState.json'
}

But I don't have the 'testConfig.rootDir' at the config file.

How i can dynamically find what is the playwright folder in the config?
or is there any other way to load the storageState?

Thanks, Adi

**Comment by yury-s** [comment]
Relative storage state path is resolved relative to the current working directory (same way as fs.readFile() would do). If you want the path to be predictable, you can resolve it relative to __dirname in the config:

```js
use: {
  storageState: path.join(__dirname, 'e2e/storageState.json'),
}
```
