### ISSUE TITLE
[Question] - `Page.url` does not show the current page URL

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#19415]
I have a scenario when I go the page and click on a link on that page, it takes me to the URL that opens up in a new tab. But `page.url` prints the url for the original page and not the url of the link that opens up in the new tab. Can someone please help?

```
  async validatePageUrl(locator, locator1) {
    //click on the element
    await this.verify.clickOnElement(locator);
    //wait for page to load
    await this.page.expectElementVisible(locator1)
    const url = this.page.url();
    console.log("Print url : " + url);
  }
```

**Comment by Eloy2** [comment]
I could be wrong but it seems like you need to capture the new page in a variable. [Docs](https://playwright.dev/docs/pages#handling-new-pages)

```
// Get page after a specific action (e.g. clicking a link)
const [newPage] = await Promise.all([
  context.waitForEvent('page'),
  page.locator('a[target="_blank"]').click() // Opens a new tab
])
await newPage.waitForLoadState();
console.log( newPage.url() );
```

**Comment by yury-s** [comment]
> I have a scenario when I go the page and click on a link on that page, it takes me to the URL that opens up in a new tab. But page.url prints the url for the original page and not the url of the link that opens up in the new tab. 

As noted above there are two pages now and you need to check the url of the popup rather than the old page:

```js
  async validatePageUrl(locator, locator1) {
    // Start waiting for popup before clicking. Note no await.
    const popupPromise = page.waitForEvent('popup');
    //click on the element
    await this.verify.clickOnElement(locator);
    const popup = await popupPromise;
    //wait for page to load
    await popup.expectElementVisible(locator1)
    const url = popup.url();
    console.log("Print url : " + url);
  }

```

**Comment by gauravgandhi1315** [comment]
@yury-s Thanks for your response. It is not a popup, its just a link on a page and it opens up in a new tab when you click on it.

**Comment by gauravgandhi1315** [comment]
@yury-s It works as per your suggestion. Thank you so much for your help!
