### ISSUE TITLE
[BUG] Node script isn't killable if importing chromium

### ISSUE THREAD

**Issue by mhkeller** [microsoft/playwright#19418]
**Context:**
## System:
 - OS: macOS 12.6.1
 - Memory: 250.61 MB / 32.00 GB
## Binaries:
 - Node: 16.16.0 - /usr/local/bin/node
 - npm: 8.11.0 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.28.1 => 1.28.1

**Code Snippet**

Reproduction repo: https://github.com/mhkeller/playwright-process-bug

**Describe the bug**

If you `import { chromium } from 'playwright'`, the parent node process can no longer be exited with control-c.
Steps to reproduce

1. Clone the test repo
2. Run `node index.js`
3. Try to kill the process in the terminal with control-c. It will not work

To fix it, comment out the chromium import line in `my-module.js`.

https://user-images.githubusercontent.com/498744/207184711-d8e9a9db-93b0-47b3-872a-9b33a88267d1.mov

**Comment by yury-s** [comment]
It doesn't seem to be playwright specific, the following code also fails to exit on Ctrl+C:

```js
process.on('SIGINT', () =>  {
	process.exit(2);
})

for (let i = 0; i < 1_000_000; i += 1) {
	console.log(i);
}
```

**Comment by mhkeller** [comment]
Testing both of these on node v18.12.1 and control-c does properly exit the script – although in the rest repo (the scenario using playwright) it takes about 7-9 seconds to exit. In your version with the `process.on` listener, it exits in about 1-3 seconds.

It would be interesting to see what about playwright is causing that to happen – especially since there is no code being executed – just the import.

**Comment by yury-s** [comment]
> It would be interesting to see what about playwright is causing that to happen – especially since there is no code being executed – just the import.

Yeah, I am not aware of any sigint handlers that playwright would add during its initialization (we use some but all of them are related to child process launches), so my hunch is that a third-party dependency might be adding such a listener.

**Comment by yury-s** [comment]
Ok, the culprit is `signal-exit` package which we indirectly import via the following dependency chain:

```
utils-bundle@0.0.1 /home/user/playwright/packages/playwright-core/bundles/utils
└─┬ proper-lockfile@4.1.2
  └── signal-exit@3.0.7
```

that module unconditionally installs signal handlers during [its initialization ](https://github.com/tapjs/signal-exit/blob/d4adbebea89cee95da197e9e94f32b3d685b4c80/index.js#L110-L111). This is a very interesting design choice but given that it only causes a problem when you have a toplevel tight loop fixing it will probably be a lower priority for us and I don't see an easy work around at this point. Let me bring this is up in the team meeting tomorrow.

**Comment by mhkeller** [comment]
Thanks for the quick and thorough investigation! That's interesting and I see that repo has some issues about this, too. My use case is that I use playwright in [this package](github.com/mhkeller/plot) where the workflow is:

1. Read in a csv
2. Loop through the rows to do some cleaning
3. Render a chart with playwright

So hence why I'm using a toplevel loop. Thanks again for looking into it!

**Comment by yury-s** [comment]
We've decided in the team meeting that it would make sense for playwright to fix the lock file support and make it not depend on signal-exit code.

**Comment by mhkeller** [comment]
Very exciting – thanks for your time in working on it.

**Comment by mhkeller** [comment]
Thanks for your work on this @aslushnikov @yury-s @dgozman ! I'm looking forward to using it in the next release
