### ISSUE TITLE
Difference between Locator.ScreenShotAsync() and Page.ScreenShotAsync()

### ISSUE THREAD

**Issue by jpEngProd** [microsoft/playwright#19432]
If I want to capture screenshot of an element within the page using Xpath as selector.
Then which is the best option among these two?
1. `Locator.ScreenShotAsync("xpath={element_xpath}")` https://playwright.dev/dotnet/docs/api/class-locator#locator-screenshot
2. `Page.ScreenShotAsync("xpath={element_xpath}")` https://playwright.dev/dotnet/docs/api/class-page#page-screenshot

Is any of them more recommended or both will provide same consistency in result?

**Comment by yury-s** [comment]
There is no such thing as `Page.ScreenShotAsync("xpath={element_xpath}")` - the `Page.ScreenShotAsync` method does not accept any selector and instead always captures the entire page. If you need to capture a particular element you should call something like `Page.Locator("xpath={element_xpath}").ScreenshotAsync()`. We also recommend using built[-in locators](https://playwright.dev/dotnet/docs/locators) over xpath. Hope this helps.

**Comment by jpEngProd** [comment]
Let me re-phrase the question a bit.
I was asking about this-

```
//Using page.ScreenShotAsync()
var rect = await Locator("xpath={element_xpath}").BoundingBoxAsync();
var clip =  new Clip { X = rect.X, Y = rect.Y, Width = rect.Width, Height = rect.Height };
var options = new PageScreenshotOptions
{
FullPage = false,
Clip = clip
};
await Page.ScreenshotAsync(options)
```

Or 
//Using Locator.ScreenShotAsync()
await Locator("xpath={element_xpath}").ScreenShotAsync()

Which of them is more recommended in terms of consistent results[considering the page is getting rendered via a request]?
