### ISSUE TITLE
[BUG] Unable to resolve TsConfig Aliases in Playwright Component Testing for React

### ISSUE THREAD

**Issue by bdlb77** [microsoft/playwright#19437]
Currently we are unable to resolve our `tsconfig.json` Alias paths that we set. 

The error we receive is:

<img width="1218" alt="Screenshot 2022-12-13 at 2 57 54 PM" src="https://user-images.githubusercontent.com/32174912/207463125-0e4bd1ed-86fe-49b9-95f5-2565614e22ab.png">

**Context:**
- Playwright Version: v.1.28.1
- Operating System: Mac Ventura 13.0.1
- Node.js version: 16.17.1
- Browser: All

**Extra**

We are using both e2e Playwright tests, and component Testing. Here are the playwright packages being used:

```json
    "@playwright/experimental-ct-react": "^1.28.1",
    "@playwright/test": "^1.28.1",
    "playwright": "^1.28.1",
```

**Code Snippet**
Component to be tested (it's a basic sample one)

```tsx
// src/renderer/components/sample.tsx
import React from "react";

const MyComponent: React.FC = () => {
    return <h1>Hello World</h1>;
};

export default MyComponent;
```
This works:

```tsx
import MyComponent from "../../../src/renderer/components/sample";
test("should work", async ({ mount }) => {
    const component = await mount(<MyComponent />);
    await expect(component).toContainText("Greetings");
});
```

This Does Not work:

```tsx
import MyComponent from "~Components/sample";

test("should work", async ({ mount }) => {
    const component = await mount(<MyComponent />);
    await expect(component).toContainText("Greetings");
});
```
Here is the `tsconfig.json` paths definition

```json
    "paths": {                                    
      "~Components/*": ["src/renderer/components/*"],
    },
```
**Describe the bug**

As Stated above, it seems to be an issue with resolving `tsconfig.json` specifically in the Experimental Testing Components library. 
Our aliases are resolving fine in our `e2e` testing suite using playwright. 

We have 2 playwright configs:
-  1 for `e2e`
- 1 for **react component testing**. The generated one through `yarn create playwright --ct` is what we use, besides changes to the `testDir`

```ts
const config: PlaywrightTestConfig = {
    testDir: "./__tests__/renderer",
   // ...
}

**Comment by sand4rt** [comment]
It seems you forgot to tell vite that you are using import aliases:

```
// playwright-ct.config.ts
import { type PlaywrightTestConfig, devices } from '@playwright/experimental-ct-react'

import { resolve } from 'path'

const config: PlaywrightTestConfig = {
  use: {
    ctViteConfig: {
       resolve: {
        alias: {
          "~Components/*": resolve('./src/renderer/components'),
        },
      },
    },
  },
};
```

**Comment by bdlb77** [comment]
> ```ts
>   ctViteConfig: {
>        resolve: {
>         alias: {
>           "~Components/*": resolve('./src/renderer/components'),
>         },
>       },
>     },
> ```

thank you for the quick reply! 

Out of curiousity, what is the reason that aliases are resolved for `@playwright/test` vs not for `@playwright/experimental-ct-react`? My guess is since for `e2e` we do an `electron-forge make` which would compile our TS to JS then and do the path and alias resolutions (This is an Electron-Forge  / React app)

**Comment by dgozman** [comment]
@bdlb77 This is because component testing involves actually building components for the web page, which is done by Vite. Thus, you have to separately configure how your web page is built, including aliases. For the tests themselves, which run in Node.js, Playwright follows `tsconfig.json` path mapping for this. You can read more about [component testing internals here](https://playwright.dev/docs/test-components#under-the-hood).

**Comment by sand4rt** [comment]
Related to https://github.com/microsoft/playwright/issues/14749

**Comment by bdlb77** [comment]
> It seems like you forgot to tell Vite that import aliases are used:
> 
> ```ts
> // playwright-ct.config.ts
> import { type PlaywrightTestConfig, devices } from '@playwright/experimental-ct-react'
> 
> import { resolve } from 'path'
> 
> const config: PlaywrightTestConfig = {
>   use: {
>     ctViteConfig: {
>        resolve: {
>         alias: {
>           "~Components/*": resolve('./src/renderer/components'),
>         },
>       },
>     },
>   },
> };
> ```

unfortunately this has hasn't resolve the issue.

I'm still seeing this error: 
<img width="1202" alt="Screenshot 2022-12-14 at 9 39 45 AM" src="https://user-images.githubusercontent.com/32174912/207667780-7046e713-0d16-4709-9b68-b478de544f51.png">


Here's my updated vite config 

```ts
import type { PlaywrightTestConfig } from "@playwright/experimental-ct-react";
import { devices } from "@playwright/experimental-ct-react";
import { resolve } from "path";

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
    testDir: "./__tests__/renderer",
    globalSetup: "./__tests__/playwrightGlobalSetup",

    /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
    snapshotDir: "./__snapshots__",
    /* Maximum time one test can run for. */
    timeout: 10 * 1000,
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!process.env.CI,
    /* Retry on CI only */
    retries: process.env.CI ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 1 : undefined,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: "html",
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: "on-first-retry",

        /* Port to use for Playwright component endpoint. */
        ctPort: 3100,
        ctViteConfig: {
            resolve: {
                alias: {
                    "~Components/*": resolve("./src/renderer/components"),
                },
            },
        },
    },
  //...
};

export default config;
```

**Comment by bdlb77** [comment]
> Related to #14749

We are using `webpack` as our bundler for electron forge

**Comment by bdlb77** [comment]
^^ Resolved : I've been hasty :) 

@sand4rt  Thank you for your assistance! your response here was exactly what I needed: https://github.com/microsoft/playwright/issues/17846#issuecomment-1269618105
``` ts


const config: PlaywrightTestConfig = {
  use: {
    ctViteConfig: {
       resolve: {
        alias: {
          "~Components": resolve(__dirname, './src/renderer/components'),
        },
      },
    },
  },
};
```
