### ISSUE TITLE
how to use extent report with playwright typescript cucumber framework

### ISSUE THREAD

**Issue by PallaviYadav-2022** [microsoft/playwright#19430]
how to use extent report with playwright typescript cucumber framework

**Comment by yury-s** [comment]
Playwright doesn't have out of the box integration with "Extent Reports", but it exposes a reach [reporter API](https://playwright.dev/docs/test-reporters#custom-reporters) that can be used for implementing  such a reporter (perhaps one already exists). There is some information on the internet on the topic including a video (don't know anything about its quality though) and we also have [some examples](https://playwright.dev/docs/test-reporters#third-party-reporter-showcase) of third-party reporters which can be used as examples.
