### ISSUE TITLE
[Question] Does playwright have an on-error hook / error formatting?

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#19449]
We are migrating our tests to Playwright from Cypress.

In our `beforeAll`hooks, we often have operations that interact with MongoDB:

```
test.beforeAll(async () => {

   await updateDocInMongodb();
})

```

If the operation fails, playwright reports an error in the console. However in the case of MongoDB, the error.message property being printed is not very helpful, as it just says "document failed validation". We would like to `JSON.stringify` the error. Something like this:

```
onError(error => {
  console.log(error?.message, JSON.stringify(error, null, 2));
}); 
```

Is something like the above possible in  Playwright - maybe using a fixture or something?

If not I will just have to wrap our before functions in try/catch 🤔

**Comment by yury-s** [comment]
Playwright does not have such a hook, so wrapping the call in a try/catch and formatting the error yourself is the right way to print more detailed information.

> Is something like the above possible in Playwright - maybe using a fixture or something?

You could change the setup code into a fixture but you would still have to wrap it with try/catch to print a more detailed message.
