### ISSUE TITLE
[Question] Are events (such as clicks and keystrokes) performed by Playwright "Synthetic" or "Native" events?

### ISSUE THREAD

**Issue by atgehrhardt-stripe** [microsoft/playwright#19445]
Does playwright use synthetic events or is it using native events?

I am attempting to build some tools that allow testing against a production site, however, the site will lock accounts for anything flagged as "botting/non-human". We generally flag systems using synthetic events, as we can simply monitor these and stop them when necessary, but any attempts to obscure the nature of a script (ie pretend to be human) can, and will cause issues.

To expand a bit, Selenium for example (to my knowledge) uses its WebDriver to send an http request to Chrome via DevTools containing the appropriate JavaScript to perform the action, thus all clicks and keystrokes are synthetic and not attempting to hide the fact it is simply executing JS on the page.

I want to ensure that using this testing suite will send synthetic events such as clicks and keystrokes and does not attempt to use native events to 'seem human'.

Any insight here would be greatly appreciated.

Thank you for the help!

**Comment by yury-s** [comment]
Playwright will trigger 'native' input events from the page's point of view, similar to how it would happen if a real mouse click was performed. With that said, stealth mode is not a goal for playwright and there are still many ways for a page to detect that it is running under automation tool. Does it answer your question?

**Comment by yury-s** [comment]
There is no documentation describing this but Playwright is all open source so you can have a look at our code.
