### ISSUE TITLE
Playwright returns the same thing every time a site is loaded

### ISSUE THREAD

**Issue by Kaid3n22** [microsoft/playwright#19446]
Not sure the reason, but when loading a Spotify authorize URL (to get an authorization token), even though you are supposed to get a new one each time you log in, it continues giving out the same code. I tried it with headless off, but it only loaded the page once, and the other time, it didn't open the browser at all and just gave the code.

**Comment by Kaid3n22** [comment]
Here's the code I'm using (You'll need to create a Spotify application to repro):
`
import {PlaywrightCrawler, sleep} from 'crawlee'
var requestdata = {}
var responsedata = {}

const webcrawler = new PlaywrightCrawler({
    // Use the requestHandler to process each of the crawled pages.
    async requestHandler({page, parseWithCheerio, request}) {
        if(request.url.substring(0, spotauthurl.length) === spotauthurl) {
            await page.reload({
                waitUntil: "domcontentloaded"
            })
            await page.waitForSelector("#login-username")
            await page.waitForSelector("#login-password")
            await page.waitForSelector("#login-button")
            await page.type("#login-username", requestdata[request.url].username)
            await page.type("#login-password", requestdata[request.url].password)
            await page.click("#login-button")
            await page.waitForSelector("[data-testid=auth-accept]")
            await page.click("[data-testid=auth-accept]").catch(err => console.log(err))
            await page.waitForNavigation({
                timeout: 30000,
                waitUntil: "domcontentloaded",
            })

            var code = page.url().split(spotredircall+"?code=")[1]
            responsedata[request.url] = code

            await sleep(2000)
        }
    },
    // Uncomment this option to see the browser window.
    // headless: false
})

var clientId = ""
var redirectUri = ""
var scopes = ""
var username = ""
var password = ""

var url = spotauthurl + "?client_id="+clientId+"&response_type=code"
url += "&redirect_uri="+encodeURI(redirectUri)
url += "&show_dialog=true&scope="+scopes
    
requestdata[url] = {
    username: username,
    password: password
}
      
await webcrawler.run([url])
.catch(() => {})
        
delete requestdata[url]
var code = responsedata[url]
console.log("The new code is "+code)
    
requestdata[url] = {
    username: username,
    password: password
}
      
await webcrawler.run([url])
.catch(() => {})
        
delete requestdata[url]
var code = responsedata[url]
console.log("The new code is "+code)
`
Also, I have my code type set to module, you can change the first line to
`
const {PlaywrightCrawler, sleep} = require('crawlee')
`
for it to work not as a module

**Comment by yury-s** [comment]
It's unclear what PlaywrightCrawler does and I suspect it just uses cached results from the first login. Can you share a minimal repro (ideally just a playwright test) which we could run locally to reproduce the problem?

**Comment by Kaid3n22** [comment]
Here's the code (You'll only need to enter your spotify password and username)
```
import {PlaywrightCrawler, sleep} from 'crawlee'

var spotredircall = "https://multiple-discord-bots.glitch.me/spotifycallback"
var spotauthurl = "https://accounts.spotify.com/authorize"
var requestdata = {}
var responsedata = {}

const webcrawler = new PlaywrightCrawler({
    // Use the requestHandler to process each of the crawled pages.
    async requestHandler({page, parseWithCheerio, request}) {
        if(request.url.substring(0, spotauthurl.length) === spotauthurl) {
            await page.reload({
                waitUntil: "domcontentloaded"
            })
            await page.waitForSelector("#login-username")
            await page.waitForSelector("#login-password")
            await page.waitForSelector("#login-button")
            await page.type("#login-username", requestdata[request.url].username)
            await page.type("#login-password", requestdata[request.url].password)
            await page.click("#login-button")
            await page.waitForSelector("[data-testid=auth-accept]")
            await page.click("[data-testid=auth-accept]").catch(err => console.log(err))
            await page.waitForNavigation({
                timeout: 30000,
                waitUntil: "domcontentloaded",
            })

            var code = page.url().split(spotredircall+"?code=")[1]
            responsedata[request.url] = code

            await sleep(2000)
        }
    },
    // Uncomment this option to see the browser window.
    // headless: false
})

var clientId = "7113e3c8f91b49eab07741d0537a3560"
var redirectUri = "https://multiple-discord-bots.glitch.me/spotifycallback"
var scopes = "" //this one can be left alone
var username = ""
var password = ""

var url = spotauthurl + "?client_id="+clientId+"&response_type=code"
url += "&redirect_uri="+encodeURI(redirectUri)
url += "&show_dialog=true&scope="+scopes
    
requestdata[url] = {
    username: username,
    password: password
}
      
await webcrawler.run([url])
.catch(() => {})
        
delete requestdata[url]
var code = responsedata[url]
console.log("The new code is "+code)
    
requestdata[url] = {
    username: username,
    password: password
}
      
await webcrawler.run([url])
.catch(() => {})
        
delete requestdata[url]
var code = responsedata[url]
console.log("The new code is "+code)
```
I'll edit out the redirecturi after since I don't want people using it
