### ISSUE TITLE
[Question] How do I keep my in-memory server alive while Playwright is still running?

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#19450]
Thanks to awesome help from the community, I now have a powerful worker fixture that spins up an in-memory MongoDB server, perfect for testing! But, when a test fails I would like to inspect the test. Currently, this is not possible. Can you please advice how I could do this differently?

**worker-fixture**
```typescript
export const test = base.extend<{}, { server: string }>({
    server: [
        async ({}, use, workerInfo) => {
            const { MongoMemoryReplSet } = await import('mongodb-memory-server');
            const mongoServer = await MongoMemoryReplSet.create({
                replSet: { storageEngine: 'wiredTiger' },
            });
            const uri = mongoServer.getUri();
            process.env['MONGO_CONNECTION_STRING'] = URI;
     
            // Here I start my Sveltekit application, but left out for brevity
            await use(serverUri);
            console.log('cleanup running'); 
        },
        { scope: 'worker', auto: true},
    ],
});
```

The problem with this is that when I have a test failing, and see this screen:

<img width="1513" alt="Screenshot 2022-12-14 at 11 30 51" src="https://user-images.githubusercontent.com/9967422/207571599-87ffe495-f6a0-470a-baef-6a1448c572e4.png">

(coming after running `playwright test`), the in-memory server no longer exists!

This is not very good, because I would like to inspect the database. Thanks 🙏

**Comment by yury-s** [comment]
Did you try to follow our [debugging guide](https://playwright.dev/docs/debug) ? You can e.g. run the failing test under VS code debugger to get more insight into what's going on, would that work for you?

**Comment by alexbjorlig** [comment]
No this is not about the debugging guide. 

I'm starting an in-memory database, in the worker fixture.

It works really nice, but when the tests errors out the database is closed (because the worker fixture process is killed). 

And I would like the database to still be running, so I could debug the database state

**Comment by yury-s** [comment]
As described [here](https://playwright.dev/docs/test-parallel#worker-processes) worker processes are always shut down if there is a test failure. This is done for better state isolation between tests and there is no way to disable that. You can use debugger to pause in `afterEach` hook and inspect the database state after test failure, you can set a conditional breakpoint / error log based on whether there are any errors in [TestInfo.errors](https://playwright.dev/docs/api/class-testinfo#test-info-errors). If you absolutely need the db process to keep running after playwright finishes you'll have to move the db into a separate process (not sure how feasible it is in your case).

**Comment by alexbjorlig** [comment]
Thanks for the quick answer.

I moved the db into a separate process with nodejs childprocess running in `"detached: true"`.

Works like a charm - thanks for helping out 🙏
