### ISSUE TITLE
[Question] Is Fedora OS supported?

### ISSUE THREAD

**Issue by vaibhav0710-hub** [microsoft/playwright#19458]
Hi,

I am trying to use Playwright on Fedora OS and getting some issues like the below and wondering if Fedora is supported yet or not.
Are there any known issues and workarounds?

It seems one can't use 'apt' to install packages on Fedora, so do we have rpm and dnf packages for Playwright?
--

$ sudo npx playwright install-deps
[sudo] password for xxxxxx: 
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
sh: line 1: apt-get: command not found
Failed to install browser dependencies
Error: Installation process exited with code: 127

**Comment by yury-s** [comment]
Only Ubuntu and Debian 11 are officially supported, see [this page](https://playwright.dev/docs/troubleshooting#linux).

Folding this issue into https://github.com/microsoft/playwright/issues/14736

**Comment by nafg** [comment]
https://playwright.dev/docs/troubleshooting#linux link is broken

**Comment by jcubic** [comment]
Fedora is supported by Docker container described here:
 
* https://github.com/microsoft/playwright/issues/26482

Note: that I didn't test it myself.
