### ISSUE TITLE
[Question] Test reusability / organizing tests

### ISSUE THREAD

**Issue by Attic0n** [microsoft/playwright#19452]
I'm a mainly manual tester with a non-technical background and am currently rebuilding an old Selenium IDE test suite in Playwright with VS Code. I'm loving it so far, a whole world of versatility opening up for me, but I have some issues I can't seem to find an answer to. Might be self-evident perhaps, but please bear with me.

The application under test is a long and complex process of creating a file with many different options and parameters, then moving that file though multiple statuses until it reaches the status "closed". Depending on some options and parameters of the file, there might be additional statuses and steps (and sometimes in different orders or repeated) required to go from A to Z. 
The way the old Selenium IDE suites were set up was to have a different suite for each A to Z flow, and reuse the same test scenarios between the suites so we wouldn't need to reuse the same tests' code a dozen times.

How do I achieve the same with Playwright? What I have so far is a single spec with a test for every test scenario. Is there a way to call the tests from this spec in another spec, in a different order/leaving some out/adding others? 

I also realize Playwright is built with test isolation in mind, but it makes it difficult to figure out how to tackle an app like this one where by the very nature of it the majority of operations are dependent on a prior operation from the very start onward, that being the creation of a file.

**Comment by yury-s** [comment]
> How do I achieve the same with Playwright? 

Based on what you described I'd recommend you put the common functionality into a function and call it from the tests that need to perform corresponding steps, e.g.:

```ts
// common.ts
import { expect, Page } from '@playwright/test';

export async function modifyTheFile(page: Page) {
    await page.locator('...').click();
    await expect(page.locator('file-status')).toHaveText('modified');
    // ...    
}

// first-file-test.spec.ts
import { test } from '@playwright/test';
import { modifyTheFile } from './common';

test('test A', async ({ page }) => {
  await page.goto('https://your site');
  // ...
  await modifyTheFile(page);
});

test('test B', async ({ page }) => {
  await page.goto('https://your site');
  // ...
  await modifyTheFile(page);
});
```

> What I have so far is a single spec with a test for every test scenario. Is there a way to call the tests from this spec in another spec, in a different order/leaving some out/adding others?

You cannot reuse tests directly from different files but you can extract shared functionality into functions and call it like I described above, let us know if you have more questions about it.

> I also realize Playwright is built with test isolation in mind, but it makes it difficult to figure out how to tackle an app like this one where by the very nature of it the majority of operations are dependent on a prior operation from the very start onward, that being the creation of a file.

For the tests that depend on one another you should use [serial mode](https://playwright.dev/docs/test-retries#serial-mode). That documentation page contains detailed information including an example of reusing a page instance between several consequent tests. Hope that helps.

**Comment by Attic0n** [comment]
Thank you, the explanation and example of functions was very helpful!
That, and serial mode as well as the beforeEach I put together should solve my issues!

**Comment by brgermano** [comment]
Thank you @yury-s
