### ISSUE TITLE
I need to send a POST API request body from json file and validate the response . How can i do that

### ISSUE THREAD

**Issue by Asanka-R** [microsoft/playwright#19453]

**Comment by yury-s** [comment]
Playwright provides [APIRequestContext.post](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-post) method for that, did you try it?

**Comment by Asanka-R** [comment]
Worked. Thank you @yury-s 
Able to do that from the below code

//Read the request body from json file and save to object
			
			Object obj = new JSONParser().parse(new FileReader("request.json"));
			JSONObject jo = (JSONObject) obj;
			
			//Post the request 
			
			APIResponse response=apirequestContext.post("/useraccounts", RequestOptions.create().
					setData(jo));

**Comment by daniavander** [comment]
how we post data from a seperated file:
data:{  //path to the file   }
