### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Asanka-R** [microsoft/playwright#19451]
Anybody knows about the below import 
What maven dependency should i add in pom.xml to import this

import io.playwright.client.Playwright;

**Comment by yury-s** [comment]
That package is not a part of Playwright. To add playwright to your maven project you only [need this](https://playwright.dev/java/docs/intro#usage):

```xml
    <dependency>
      <groupId>com.microsoft.playwright</groupId>
      <artifactId>playwright</artifactId>
      <version>1.28.0</version>
    </dependency>
```
