### ISSUE TITLE
 Showing "Test Timeout Exceeded Error" while executing 5/6 tests together 

### ISSUE THREAD

**Issue by TAJWAR99** [microsoft/playwright#19457]
When I am executing one test at a time, everything is working perfectly. But when  5 or 6 similar types of tests are executed at a time, after successfully executing 3/4 tests, it is showing a Timeout error for the rest of the tests. I am seeking help to find out a solution to resolve the timeout error.

```
import { test, expect, Locator } from '@playwright/test';
let businessSidebar: Locator;
let search: Locator;

test.beforeEach(async({ page }) => {
    await page.goto('/');
    //login to dashboard
    await page.locator("input[name='email']").fill('demo@gmail.com');
    await page.locator("input[name='password']").fill('password');
    await page.locator("button:text('Login')").click();

    businessSidebar = page.locator('text=Business Profile');
    await businessSidebar.click(); 
})
test('Verify user can search with Name', async({ page }) => {
    search = await page.locator("input[name='search']");
    const searchByName = 'Name';
    await search.fill(searchByName);
    await page.keyboard.press("Enter");
    const result = (await page.locator("(//td[@class='rc-table-cell business_name'])[1]").innerText()).valueOf();
    expect(result).toMatch(searchByName);
})
test('Verify user can search with TIN', async({ page }) => {
    search = await page.locator("input[name='search']");
    const searchByTIN = '123456789';
    await search.fill(searchByTIN);
    await page.keyboard.press("Enter");
    const result = (await page.locator("(//td[@class='rc-table-cell business_tin'])[1]").innerText()).valueOf();
    expect(result).toMatch(searchByTIN);
})
//similar type 3/4 tests are added
```

My timeout config is given below:
`timeout: 40 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },`

**Comment by yury-s** [comment]
This is probably a resource issue (either on the client side or on the server which may not be keeping up with concurrent connections). Can you tell us more about how you run your tests (how many parallel workers) and what is the hardware configuration (how many CPU cores it has) where you experience timeout? Does it reproduce it you run the tests with `npx playwright test --workers=1`?

**Comment by TAJWAR99** [comment]
Hey @yury-s I am using Apple M1 chip with 8‑core CPU, 7‑core GPU, and 16‑core Neural Engine. I usually run by `npx playwright test file_name.spec.ts` command. I also tried `npx playwright test --workers=1` command but the timeout error still persists. Please have a look at my error.
![image](https://user-images.githubusercontent.com/63014244/208188548-6b93bb07-01f2-4d4c-855d-a1d61e0c03d4.png)

**Comment by yury-s** [comment]
According to the log playwright cannot find "text=Business Profile" element (or it is not [actionable](https://playwright.dev/docs/actionability)) and times out. Try recording [a trace](https://playwright.dev/docs/trace-viewer-intro) to get more details on what's going on and why the element is not there.

If you think there is a playwright bug, please file a new issue (and link to this one) with a reproducible example that we could run locally.
