### ISSUE TITLE
[REGRESSION]: Lots of Navigation timeout errors in 0.14.0

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#1946]
**Context:**
- GOOD Playwright Version: 0.13.0-next.1587452068410
- BAD Playwright Version: 0.14.0
- Operating System: macOS

**Describe the bug**

I'm seeing a *lot* of `Navigation timeout` errors on 0.14.0 that don't seem valid. I haven't found a way to reliably repro yet, but I did find one clue. A lot of the time, my error message gets duplicated in this weird way.

```ssh
TimeoutError: Navigation timeout exceeded while navigating to https://portfolio.adobe.com/ while navigating to https://portfolio.adobe.com/
```

I'm going to keep trying to repro, but I figured it was worth posting now anyway in case the double error message was enough. This was also happening to me sometimes in 0.13.0-*, but not nearly as often.

**Comment by pavelfeldman** [comment]
Is that Chromium?

**Comment by celeryclub** [comment]
Yes.

**Comment by celeryclub** [comment]
@pavelfeldman I ran my job overnight using `0.13.0-next.1587452068410` and didn't see these errors. Maybe that will help narrow down the range a bit.

**Comment by celeryclub** [comment]
Ok well I can't repro this anymore. Might be something on my end. I'll close this and possibly reopen later if I can repro again. Thanks!
