### ISSUE TITLE
[Question] Login fails while running on AWS

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#19475]
**Scenario:**
User sends the Booking request to Supplier for their respective email ids. So Supplier will open the email and click on Booking link to view the bookings

**Problem:**
I have written automation test for gmail and it runs fine on local machine, but when i run the scripts on AWS the scripts fails due to gmail terms & security issues which i am totally agreed upon.
But could someone help me out how i can test and run the emails via playright JS without using gmail? If there is any tool for that, please let me know.

**Comment by yury-s** [comment]
You can use an email service that provides a rest API for manipulating the emails or you can use a different web email client which fits your requirements. Stealth mode (where the browser tries to hide that it is controlled by an automation tool) is not a goal for Playwright. The question of finding appropriate email implementation is outside of Playwright's scope, so I'm closing this request, you can look for an answer on appropriate forums.
