### ISSUE TITLE
[Feature] Ability to upload multiple files at once through REST API using APIRequestContext

### ISSUE THREAD

**Issue by amulalic** [microsoft/playwright#19471]
Hi,

I am trying to test my API endpoint for uploading files. I have made one test using REST API client (such as Postman and Insomnia) for uploading multiple files at once (see the Insomnia screenshot below).

![image](https://user-images.githubusercontent.com/32891915/207842390-62b99069-a300-4f34-a45c-5e133e8ab348.png)

I am trying to replicate the same test using Playwright's APIRequestContext but it seems I cannot upload multiple files at once. See the code below and let me know if I am doing something wrong.

```javascript
// @ts-check
import { test, expect } from "@playwright/test";
const path = require("path");
const fs = require("fs");

test(`Uplaod two files at once`, async ({ request, baseURL }) => {
  let files = [
    {
      filePath: "files/json/",
      fileName: "example_json.json",
    },
    {
      filePath: "files/yml/",
      fileName: "example_yaml.yml",
    }
  ];
  let file1 = path.resolve(files[0].filePath, files[0].fileName);
  let buf1 = fs.readFileSync(file1);
  let file2 = path.resolve(files[1].filePath, files[1].fileName);
  let buf2 = fs.readFileSync(file2);
  let response = await request.post(baseURL + "/api/file/upload", {
    headers: {
      Accept: "*/*",
      ContentType: "multipart/form-data",
    },
    multipart: {
      file: {
        name: file1,
        mimeType: "application/json",
        buffer: buf1,
      },
      file: {
        name: file2,
        mimeType: "application/json",
        buffer: buf2,
      }
    }
  });
  expect(response.ok()).toBeTruthy();
  expect(response.status()).toBe(201);
});
```

**Comment by yury-s** [comment]
Remove `content-type` header, playwright will generate a correct one for your multiplart requeest ( it has to be in a form 'multipart/form-data; boundary=...' which includes separator of the field data). This should be sufficient:

```ts
  let response = await request.post(baseURL + "/api/file/upload", {
    multipart: {
      file: {
        name: file1,
        mimeType: "application/json",
        buffer: buf1,
      },
      file: {
        name: file2,
        mimeType: "application/json",
        buffer: buf2,
      }
    }
  });
  expect(response.ok()).toBeTruthy();
  expect(response.status()).toBe(201);
});
```
Does it work for you?

**Comment by amulalic** [comment]
I removed the "ContentType" but for some reason it only uploads the second file (file2). It looks like it skips over the first one.

**Comment by amulalic** [comment]
In other words it doesn't work. :)

**Comment by yury-s** [comment]
>  I removed the "ContentType" but for some reason it only uploads the second file (file2). It looks like it skips over the first one.


Well, that's because you have a js object with two fields called `file` and the last one overrides the previous value:

```
multipart: {
      file: { ... },
      file: { ... }
    }
```
Make sure to use unique names for the fields.

**Comment by amulalic** [comment]
Thanks a lot @yury-s. That fixed it.
