### ISSUE TITLE
[Question] How to add environment variables to node server

### ISSUE THREAD

**Issue by supermacro** [microsoft/playwright#19480]
The following is my `webServer` configuration inside of `playwright.config.ts`:

```
  webServer: [
    {
      command: 'node ./backends/api-server/build/index.js',
      port: 8081,
      env: {
        NODE_ENV: 'production',
        END_TO_END: 'true',
        NODE_PATH: './backends/api-server/build',
      },
    },
    {
     ...some other server config
    }
  ],
```

However, when the server starts up, none of the envs I have set are available in `process.env`. e.g. `NODE_ENV`, `END_TO_END` and `NODE_PATH` are all undefined.

Is there something I am doing wrong?

**Comment by yury-s** [comment]
You code is correct, it should work. Can you share full reproducible example which we could run locally?

**Comment by EgonBolton** [comment]
I have a similar problem with my Nextjs project.
I understand that config.webServer.env defaults to process.env, so it's unnecessary to put it, right?

This is my config.webServer:
```
webServer: process.env.CI
     ? {
         command: "npm runstart",
         port: 3000,
         reuseExistingServer: true,
       }
     :undefined,

```

And this is what I receive in the github action that comes by default:
```
[WebServer] ❌ Invalid environment variables:
// my env vars
```

**Comment by yury-s** [comment]
> I understand that config.webServer.env defaults to process.env, so it's unnecessary to put it, right?

Yes, by default the server process will inherit env from its parent (i.e. playwright test runner). If it doesn't work please file an issue with full repro.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

**Comment by jamalsoueidan** [comment]
This is still an issue! 

console.log('test', process.env.SESSION_SECRET);

inside playwright.config.ts

it prints out ***

  webServer: [
    {
      command: `npm run dev`,
      url: 'http://localhost:3000',
      timeout: 120 * 1000,
      reuseExistingServer: !process.env.CI,
    },
    {
      command: 'npm run tunnel',
      url: 'https://' + process.env.NGROK_URL,
      timeout: 120 * 1000,
      reuseExistingServer: !process.env.CI,
    },

but npm run dev can't find the env
