### ISSUE TITLE
[Question]How to upload csv file ? 

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#19486]
->fixtures(folder)
         -share.csv(file)
->playwrgiht(folder)
        -test(folder)
              --channels.config.ts(file)
              --login.config.ts(file)

You can see my folder structure above. I have a share.csv file in fixtures folder and  want to upload share.csv file in my channels.config.ts (By clicking Upload file button). You can see the web directory of the Upload File button below

`<button type="button" class="ant-btn secondary-btn  width-full text-left"><span class="fa fa-upload"></span><span>Upload File</span></button>`
     

In my channels.config.ts I tried below code but got error.
`    await page.getByText('Upload File').setInputFiles('../../fixtures/share.csv');`        

Also tried using xpath instead of using getByText text but took same error again. You can see error below;

`Error: ENOENT: no such file or directory, stat '../../fixtures/share.csv'`

How can upload share.csv file according to above DOM structure and my folder structere? Tried many different codes but got error again. What is my fault?

**Comment by yury-s** [comment]
The file name is resolved relative to the current working directory (where you start `npx playwright test`), so if you run the script in the parent directory of fixtures and playwright then this should work:
```js
await page.getByText('Upload File').setInputFiles('fixtures/share.csv');
```
but a more reliable way which doesn't depend on current directory would be:
```js
await page.getByText('Upload File').setInputFiles(path.join(__dirname, '../../fixtures/share.csv');
```
