### ISSUE TITLE
[Question] How to login to the application only once during all tests?

### ISSUE THREAD

**Issue by YusufOzturk-Development** [microsoft/playwright#19488]
**First question**; How can I use process.env in global-setup.ts? You can check below code;
`    await page.locator(LoginPageRepository.emailTextField).type(process.env.NAME)`

when try above code in global-setup.ts,giving below warning(tried this method in different file it worked , did not give any warning,but in global-setup.ts I took below warning);
`Argument of type 'string | undefined' is not assignable to parameter of type 'string'`

**Second question**; I want to login to the application only once during all tests. When I try below code, browser opens but there is no action, don't navigate the url. Are there any configuration error in my code?

**my npm script**

`"pw:staging": "NAME=test@domain.com PASS=test npx playwright test "`

**this is my global-setup.ts** 

```
import { chromium, FullConfig } from '@playwright/test';
import LoginPageRepository from "./playwright/pages/login"

const fs = require("fs");
const environment = JSON.parse(fs.readFileSync(process.env.ENV, "utf8"));
const { baseURL } = { baseURL: environment.env.baseURL }

async function globalSetup(config: FullConfig) {
    const browser = await chromium.launch();
    const page = await browser.newPage();
    await page.goto('https://test/login')
    await page.locator(LoginPageRepository.emailTextField).type("test@domain.com")
    await page.locator(LoginPageRepository.passwordTextField).type("test")
    await page.locator(LoginPageRepository.loginButton).click()
    await page.context().storageState({ path: 'storageState.json' });
    await browser.close();
}

export default globalSetup;
```

**this is my playwright.config.ts**
```

import { type PlaywrightTestConfig, devices } from "@playwright/test";
const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  reporter: [ ['html', { outputFolder: 'report' }] ],
  use: {
    headless: false,
    storageState: 'storageState.json'
  },
  projects: [
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: ["--disable-web-security"],
        },
      },
    }
  ],
};
export default config;
```

**Comment by yury-s** [comment]
> Argument of type 'string | undefined' is not assignable to parameter of type 'string'

If you are confident that the variable is not undefined at that context you can suppress the warning by adding exclamation mark after the property name:
```js
await page.locator(LoginPageRepository.emailTextField).type(process.env.NAME!);
```

> Second question; I want to login to the application only once during all tests. When I try below code, browser opens but there is no action, don't navigate the url. Are there any configuration error in my code?

The code looks correct, do you pass baseURL explicitly to `page.goto` or what does it have to do with the navigation in global setup?

**Comment by YusufOzturk-Development** [comment]
@yury-s  process.env.NAME! worked.Also today tried different method for other question and it worked,too. But I have question again , I m closing this issue and open new question
