### ISSUE TITLE
[BUG] Session timeout occurring unexpectedly

### ISSUE THREAD

**Issue by kacy-weakley** [microsoft/playwright#19482]
**Context:**
- Playwright Version: @playwright/test 1.28.1
- Operating System: Mac
- Node.js version: v14.17.2
- Browser: Chromium
- Extra: trace and screenshots turned on; timeout set to 60 seconds

**Code Snippet**

I'm unable to provide credentials here, but you can create a free account yourself at https://login.mailchimp.com/signup/.  We have internal tools to bypass login verification, but I have provided an additional snippet for you to plug in answers to security questions if you want to avoid extra steps during login.

```javascript
const { test } = require('@playwright/test');

const securityQuestions = {
  'What was your first car?': 'replace with your answer',
  'In what city did your parents meet?': 'replace with your answer',
  'Name of your first employer?': 'replace with your answer',
};

test('Session timeout while on page with fallback iframe and Ada chat iframe', async ({ context, page }) => {
  await context.addCookies([
    {
      name: 'OptanonAlertBoxClosed',
      value: new Date().toISOString(),
      domain: '.mailchimp.com',
      path: '/',
    },
  ]);
  await page.goto('https://us21.admin.mailchimp.com');
  await page.locator('#username').type('replace with your username');
  await page.locator('#password').type('replace with your password');
  await page.locator('button[value="log in"]').click();
  await page.locator('.recover-question div').click();
  const securityQuestion = await page.locator('.question-input').innerText();
  await page
    .locator('[name="question_answer"]')
    .type(securityQuestions[securityQuestion]);
  await page.locator('button:has-text("Submit Verification")').click();
  await page.locator('li a[href="#/create-campaign"]').click();
  await page
    .locator("div[role = 'listitem']", {
      hasText: 'Email',
    })
    .click();
  await page.locator('a span', { hasText: 'regular' }).click();
  await page.fill("input[name='textValue']", 'Playwright Test Campaign');
  await page.locator('button', { hasText: 'Begin' }).click();
  await page.locator('[class*=container] [class*=closeButton]').click();
  await page
    .frameLocator("#fallback:not([title *='Loading'])")
    .locator('button', {
      hasText: 'Add Subject',
    })
    .click();
  await page
    .frameLocator("#fallback:not([title *='Loading'])")
    .locator("div[data-dojo-attach-point='fauxInput']")
    .first()
    .type('Important session timeout');
  await page
    .frameLocator("#fallback:not([title *='Loading'])")
    .locator("div[data-dojo-attach-point='fauxInput']")
    .nth(1)
    .type('Important preview text');
  await page.waitForTimeout(5000);
  await page
    .frameLocator("#fallback:not([title *='Loading'])")
    .locator("button[data-dojo-id='itemSubmitButton']")
    .click();
  await page.pause();
});

```

**Describe the bug**
While on some pages with an iframe as the context (in this particular case, the iframe with id `fallback`), when an additional iframe is loaded into the page, the test intermittently results in a session timeout. When this occurs, the trace shows there are also 403 errors for some XHR requests. 

For a bit of additional context, on this and other pages where this occurs, the Ada chat bot iframe loads into the document and is displayed after 5 seconds interacting within certain parts of the page. It is at that point that the test seems to result in the session timeout most often and is the reason I've added the 5 second hard wait in the above code snippet.

When testing these impacted flows using other tools (i.e. Selenium and TestCafe), this session timeout issue doesn't occur and interaction can continue in the iframe and onto the next page in the flow as expected. It seems there may be something going on with Playwright's session cookies (perhaps the login cookie in this case) or even with the viewport when another iframe is added to the document and displayed. I seem unable to prevent the session timeout from occurring.

_Result when session timeout occurs:_
![Screen Shot 2022-12-15 at 9 45 07 AM](https://user-images.githubusercontent.com/42981008/207890315-dc2f3305-f544-44b5-85fc-3077692efb04.png)

**Comment by yury-s** [comment]
Per response above we need a minimal reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

**Comment by kacy-weakley** [comment]
The scenario is only complex because I can't give you a Mailchimp account. I used the hard 5 second `waitForTimeout` to ensure that you could see the session timeout error as it typically occurs intermittently, which I explained in my description.  We have created this same test with other automation libraries (namely selenium and testcafe) without experiencing this session timeout.

**Comment by kacy-weakley** [comment]
Circling back to share more info, in case it ends up being helpful to others in the future...

The issue for us ended up being our use of the `Desktop Chrome` device descriptor in our config file, specifically the `screen` options specified: https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json#L1334. 

It appears that whenever our support chat iframe loads into view, Playwright is updating the screen/viewport sizes.
Our app is configured to invalidate the login cookie whenever users manually change device size (e.g. changing emulated device size). The result is the displayed “Your Mailchimp Session Expired” page.

By not using the `Desktop Chrome` device descriptor, or another that sets the `screen` option, we're able to prevent the viewport from changing mid-test, thereby preventing the session timeout in our app.
