### ISSUE TITLE
[Question] Is theres a way to randomly sort spec files into the various shards

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#19496]
**_Playwright:_** 1.27.1

The issue we are facing relates to all of our slow tests running on the same shard because their spec file names are similar.

For example, we split our execution across multiple BuildKite jobs like so 

(a) `npx playwright test --workers=4 --config ./playwright.ci.config.ts --shard=1/4`
(b) `npx playwright test --workers=4 --config ./playwright.ci.config.ts --shard=2/4`
(c) `npx playwright test --workers=4 --config ./playwright.ci.config.ts --shard=3/4`
(d) `npx playwright test --workers=4 --config ./playwright.ci.config.ts --shard=4/4`

What we are seeing:
(a) will run in 5 minutes
(b) will run in 7 minutes
**(c) will run in 20 minutes**
(d) will run in 3 minutes

**Job (c)** becomes the bottleneck since all of the slow tests happen to be grouped on this shard.

**Comment by yury-s** [comment]
The files are sorted alphabetically before playwright splits them and their tests into shards. You can add a prefix to the file names to change the order in which they appear in the sequence which is broken down into shards. Would that work for you?

There is no other way currently to control which tests would go to which shard.

**Comment by ryanrosello-og** [comment]
Thanks, yeah prefer not to mess with the spec file names. It would be nice if this was an optional extra command line argument `--shard-short=random` or something

**Comment by ryanrosello-og** [comment]
And just to doubly confirm, is it sorting by the specfile name not the directory subfolder names?

**Comment by ryanrosello-og** [comment]
> And just to doubly confirm, is it sorting by the specfile name not the directory subfolder names?

Yes, its sorted by specfile names but if your specs are grouped into subfolders it wont help you much.

![2022-12-20_15-47-51f](https://user-images.githubusercontent.com/50574915/208780304-abef03ff-d51c-462c-9be4-31255c78bfbe.jpg)

**Comment by ryanrosello-og** [comment]
for those who happen to stumble across this, here's a snippet that may (or may not) help you.

```javascript
import path from 'path';
import glob from 'glob';
import fs from 'fs';

export default class FileNameRandomizer {
  private allSpecFiles: string[] = [];
  constructor(private baseFolder: string, private fileExtension: string = '.spec.ts') {
    this.allSpecFiles = glob.sync(`${this.baseFolder}/**/*${this.fileExtension}`);
  }

  randomizeSpecfiles() {
    this.allSpecFiles.forEach((filename) => {
      this.renameFile(filename);
    });
  }

  getAllSpecFiles(): string[] {
    return this.allSpecFiles;
  }

  renameFile(oldFilename: string) {
    const newFilename = this.prependRandomTextToFilename(oldFilename);
    fs.renameSync(oldFilename, newFilename);
    console.log(`\r\n${oldFilename} \r\n => ${newFilename}\r\n`);
  }

  prependRandomTextToFilename(filename: string): string {
    const randomText = this.getRandomText();
    const dirname = path.dirname(filename);
    const basename = path.basename(filename);
    return `${dirname}/${randomText}${basename}`;
  }

  getRandomText(): string {
    const crypto = require('crypto');
    return `__${crypto.randomBytes(4).toString('hex')}__`;
  }
}
```
*Usage*
```javascript
import {join} from 'path';
import FileNameRandomizer from './src/FileNameRandomizer';

try {
  const rootDir = join(__dirname, '../../tests/');
  const fileNameRando = new FileNameRandomizer(rootDir);
  fileNameRando.randomizeSpecfiles();
  console.log('🥳 Spec files randomized');
} catch (error) {
  console.log(`File name randomization failed: \r\n ${JSON.stringify(error, null, 2)}`);
}
```

**Comment by pavelfeldman** [comment]
There is no feature to randomly sort spec files and it is unlikely to be added, so I'm closing this issue.
