### ISSUE TITLE
[Question] How to start codegen from terminal with the already available browser in the machine

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#19495]
Hi all,

does someone knows how I can start the recording tool from the VSCode terminal on an already installed browser?

I am working on a company that has strict policy and I am not able to intall the browsers that come with installing playwright, so I want to record and explore elements within an already installed chrome browser.

**Comment by yury-s** [comment]
You can pass [browser channel](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-channel) as a command line option:
```sh
npx playwright codegen --channel=msedge https://playwright.dev
```
Would that work for you?

**Comment by NikkTod** [comment]
@yury-s worked perfectlly, you saved me, thanks for the help!

Maybe it could be added as info within the codegen page.

**Comment by yury-s** [comment]
It's in the output of `npx playwright codegen --help`, will add it to the docs if there are more requests.

**Comment by MikeDabrowski** [comment]
Thanks! Helped me as well. I wish it was in the docs
