### ISSUE TITLE
[BUG] Logger sink with name `browser` skips `browser:err`

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#1950]
**Context:**
- Playwright Version: 0.14.0
- Operating System: Ubuntu 20.04

**Code Snippet**

I was expecting to see errors in launching the browser with this logger sink. However, this does not show logs in the `browser:err` namespace.

```javascript
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch({ logger: {
        isEnabled: (name, severity) => name === 'browser',
        log: (name, severity, message, args) => console.log(`${name} ${message}`)
    }});
    await browser.close();
})();
```

Using this with `DEBUG=*` shows the errors.
![Screen Shot 2020-04-23 at 2 00 05 PM](https://user-images.githubusercontent.com/284612/80148999-bd77e400-856a-11ea-89dc-837751e21474.png)

**Comment by pavelfeldman** [comment]
That's kind of intended. Does name startsWith("browser") work for you?

**Comment by arjun27** [comment]
`startsWith` works for me. I thought the `err` was for severity and not the name, hence the confusion.

**Comment by pavelfeldman** [comment]
Browser's `stderr` can be noisy, so we actually dispatch it as a warning severity :-)
