### ISSUE TITLE
[BUG] screenshot of embed element with pdf

### ISSUE THREAD

**Issue by romulanul** [microsoft/playwright#19516]
**Context:**
- Playwright Version: any version >= 1.26.0 (works ok on versions < 1.26.0, for example 1.25.0)
- Operating System: Windows (11)
- Node.js version: N\A
- Browser: Chromium, Chrome 108.0.5359.125 (Official Build) (64-bit)
- Extra: N\A

**Code Snippet**

```python
from playwright.sync_api import sync_playwright
import time
import random

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    page = browser.new_page()

   # public url, should be accessible
    page.goto("https://www.w3docs.com/tools/code-editor/1085")

    # just wait here to make sure page is loaded, 
    # manually agree on any consent if displayed, for the sake of simplicity here only
    time.sleep(10)

    # take a screenshot and have a look at it
    # better to add a breakpoint on the next line, and see live on the page what happens
    page.screenshot(path=f".\\screenshot_{random.randint(100,999)}.png", type='png')    
    browser.close()
```

**Describe the bug**
*Having* a page with a pdf viewer (default pdf viewer from Chrome) embedded (see url in the code sample)
*When* trying to take a screenshot using the above code (version >= 1.26.0)
*Then* the actual page view is modified while the screenshot is taken (see attachments). This does not happen on previous versions (for example 1.25.0).

- taking screenshots on version >= 1.26.0, one will not get in the screenshots what one sees on the page, page view is altered while taking the screenshot.
- to better understand the issue, add a breakpoint as suggested in the comments. 
- for the sake of simplicity, please manually agree on any consents on the page if displayed, I apologize for the trouble here

![browser_view](https://user-images.githubusercontent.com/36658502/208117356-f9ccfd48-7e3c-4e78-a238-549f97843377.png)
![screenshots_differences](https://user-images.githubusercontent.com/36658502/208117363-820750fa-5ffc-4087-a37c-438f82f38ea1.png)

**Comment by yury-s** [comment]
This is a playwright bug, it has to do with support of `embed` elements in general. I'll keep the bug open but embed elements has been a low priority for us.

Having said that, if all you need is to render a pdf you can use [pdf.js](https://mozilla.github.io/pdf.js/).

**Comment by romulanul** [comment]
Thank you for fast feedback and for acknowledging the issue! I will try as suggested.
Best regards.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
