### ISSUE TITLE
[BUG] In reference to #17335 issue with Playwright download 

### ISSUE THREAD

**Issue by LavK17** [microsoft/playwright#19515]
All the details are identical to that provided in bug #17335. This is now a organization wide blocker to adapt playwright. As mentioned by my teammate in the issue, due to security policies  the requested logs cannot be externally shared for further investigation.
Instead we can setup a virtual connect over teams to troubleshoot. Hope to hear back at the earliest.

**Comment by yury-s** [comment]
If you can't share the code, can you at least record [a trace](https://playwright.dev/docs/trace-viewer-intro) and share it with us? If you don't want to share it publicly feel free to send it to the email address in my profile.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
