### ISSUE TITLE
[Question] is workerIndex consistent during tests?

### ISSUE THREAD

**Issue by vovsemenv** [microsoft/playwright#19519]
Hello, at allure-report we have timeline view with all the used threads and timings. and this timeline uses workerIndex to determine which thread was used.

<img width="1728" alt="image" src="https://user-images.githubusercontent.com/20096510/208134386-347cb79f-4f28-495e-865a-b787f2a42bf5.png">

I found that workerIndex is not always consistent during tests. It can be reproduced when we have a lot of tests of when we repeat each multiple times.

**So is it bug that workers have index more than total amount of workers??**

reproduction

``` bash
❯ npm run test -- --repeat-each 5                                             

> pw-primer@1.0.0 test
> playwright test --repeat-each 5

Total workers: 2
tesworker index: 0; testName: should allow me to mark all items as completed
tesworker index: 1; testName: should allow me to clear the complete state of all items
tesworker index: 1; testName: should allow me to add todo items
tesworker index: 0; testName: complete all checkbox should update state when items are completed / cleared
tesworker index: 1; testName: should clear text input field when an item is added
tesworker index: 0; testName: should append new items to the bottom of the list
tesworker index: 2; testName: should allow me to mark all items as completed
tesworker index: 3; testName: should allow me to clear the complete state of all items
tesworker index: 2; testName: complete all checkbox should update state when items are completed / cleared
tesworker index: 3; testName: should allow me to add todo items
tesworker index: 2; testName: should clear text input field when an item is added
tesworker index: 3; testName: should append new items to the bottom of the list
tesworker index: 4; testName: should allow me to mark all items as completed
tesworker index: 5; testName: should allow me to clear the complete state of all items
tesworker index: 4; testName: complete all checkbox should update state when items are completed / cleared
```

**Comment by yury-s** [comment]
Worker index used for a test is not guaranteed to be the same across test runs, it depends on multiple factors. See [this page](https://playwright.dev/docs/api/class-workerinfo#worker-info-worker-index), worker index will increase when a new worker process is used (e.g. after previous test failures). There is also [parallelIndex](https://playwright.dev/docs/api/class-workerinfo#worker-info-parallel-index) which may be a better fit for your use. Note that worker index assignment is an implementation detail and it may change in the future depending on the algorithm we use for parallelizing the tests.
