### ISSUE TITLE
[Question] Is there a way switching off Codegen highlight?

### ISSUE THREAD

**Issue by yagitk** [microsoft/playwright#19511]
In a end-to-end test for a website, we are evaluating the usage of codegen.
When using codegen, each object highlights red when mouse pointing.

On the other hand, we have requests to take screenshots of the webpage while using codegen.
Taking screenshots will be done manually, because of manually testing first time at this point 
and codegen coding might not be complete, we want to take a screenshot.
When taking screenshots the highlighting will been taken into the screenshot.

Question is there a way to switch off the highlighting while codegen? 
Ex. the codegen parameters.

Or is there no way switching off the red highlighting when using the codegen.

One way is to stop recording, take a screenshot and start recording again,
but it is bothering stopping each time before pressing print screen.

**Comment by yury-s** [comment]
> On the other hand, we have requests to take screenshots of the webpage while using codegen.
> Taking screenshots will be done manually, because of manually testing first time at this point
and codegen coding might not be complete, we want to take a screenshot.
> When taking screenshots the highlighting will been taken into the screenshot.

There is no way to disable the highlight in the codegen. The users are expected to use it for authoring tests and once the test is ready you can add logic of taking [screenshots automatically](https://playwright.dev/docs/screenshots) or even [record traces](https://playwright.dev/docs/trace-viewer-intro) that would among other things automatically include page screenshots before and after each action.

> One way is to stop recording, take a screenshot and start recording again,
but it is bothering stopping each time before pressing print screen.

This is the way to go if you absolutely need to take the screenshots while generating code.

Closing the request as there is a workaround and we are not planning to change the behavior.

**Comment by yagitk** [comment]
Thank you for your reply.
We understand the main way of codegen usage, and just questioned if there was an option function.
