### ISSUE TITLE
[BUG] Run icon not showing for paramaterized tests

### ISSUE THREAD

**Issue by paustint** [microsoft/playwright#19526]
**Context:**
- Playwright Version: `"@playwright/test": "^1.28.1",`
- Operating System: Mac
- Node.js version: 16
- Visual Studio Code version: Version: 1.74.1
- Playwright for VSCode extension version: v1.0.1
- Browser: N/A
- Extra: N/A

**Code Snippet**

```typescript
function getTestData() {
  return [1, 2];
}

// THIS IS THE ONLY ONE PROPERLY DETECTED BY TEST RUNNER AS A TEST THAT CAN BE EXECUTED
test.describe('Quote - Existing Account - Test Quote Prices', () => {
  const testCases = [1, 2];
  for (const x of testCases) {
    test('my test', async () => {
      // fake
    });
  }
});

const testCases = [1, 2];

test.describe('Quote - Existing Account - Test Quote Prices', () => {
  for (const x of quoteTestCases) {
    test('my test', async () => {
      // fake
    });
  }
});

test.describe('Quote - Existing Account - Test Quote Prices', () => {
  for (const x of testCases) {
    test('my test', async () => {
      // fake
    });
  }
});

test.describe('Quote - Existing Account - Test Quote Prices', () => {
  for (const x of [1, 2]) {
    test('my test', async () => {
      // fake
    });
  }
});
```

**Describe the bug**

If test case data for parameterized tests are obtained from any variable declared outside the scope of the current scope or are declared inline in the for loop, the tests do not provide the option to be run.

![image](https://user-images.githubusercontent.com/5461649/208159644-52d6eee1-f73e-4bd4-814e-675f9ebb1568.png)

**Comment by yury-s** [comment]
You have tests with duplicate titles. If you run `npx playwright test` you will get a message like this:
```
Running 9 tests using 1 worker
========================================
 duplicate test titles are not allowed.
 - title: Quote - Existing Account - Test Quote Prices › my test
```

Once you make the test names unique you should see the run button next to each of them:

```js
import { test, expect } from '@playwright/test';

function getTestData() {
  return [1, 2];
}

// THIS IS THE ONLY ONE PROPERLY DETECTED BY TEST RUNNER AS A TEST THAT CAN BE EXECUTED
test.describe('Quote - Existing Account - Test Quote Prices', () => {
  const testCases = [1, 2];
  for (const x of testCases) {
    test(`my test ${x}`, async () => {
      // fake
    });
  }
});

const testCases = [1, 2];

test.describe('Quote - Existing Account - Test Quote Prices 1', () => {
  for (const x of getTestData()) {
    test(`my test ${x}`, async () => {
      // fake
    });
  }
});

test.describe('Quote - Existing Account - Test Quote Prices 2', () => {
  for (const x of testCases) {
    test(`my test ${x}`, async () => {
      // fake
    });
  }
});

test.describe('Quote - Existing Account - Test Quote Prices 3', () => {
  for (const x of [1, 2]) {
    test(`my test ${x}`, async () => {
      // fake
    });
  }
});
```

**Comment by yury-s** [comment]
The extension could do a better job explaining why there is no triangle in the gutter, e.g. add wiggly lines to the tests with duplicate names and show an error when mouse hover them.

**Comment by paustint** [comment]
@yury-s 

I still think there is a bug here. I have a fairly complex return type for my test-cases that is an array. Even when I have a unique name foe the test case, the VSCode plugin is unable to detect it.

My types are imported from from within the test area but also imported using VSCode paths and come from the application (outside the test folder area) - could this have something to do with it?

I don't see that the VSCode plugin has any output logs like most other extensions, so I am unable to see if there was an error reported. Is it possible that there is some issue parsing the types which breaks detection for the play icon?

Even when I create a stand-alone variable with hard-coded indexes for the test cases (final screenshot), nothing shows up to run the test.

The only way I have gotten it to work is to embed the for loop inside the `test()`, but then it takes a long time to run and risks a timeout on CI.

```typescript
import {
  IAccountRespSchema,
  IContactRespSchema,
  IProductResSchema,
} from '~app/types';
import {
  createAccountsAndContacts,
  createProductCatalog,
} from './api-data-utils';

type QuoteTestCaseReturnType = {
  testCaseIdx: number;
  account: IAccountRespSchema;
  contact: IContactRespSchema;
  products: IProductResSchema[];
} & ReturnType<typeof generateTestCasesForSubscription>;
```

![image](https://user-images.githubusercontent.com/5461649/211052528-da2f5cab-bfbf-4540-a6eb-50e2fc10cadc.png)

![image](https://user-images.githubusercontent.com/5461649/211054320-a1f600df-0cbd-4c7c-9ac0-6fb52e0a3a97.png)

**Comment by paustint** [comment]
Here is another simplified example that shows that something is wrong and it is not related to duplicate names

![image](https://user-images.githubusercontent.com/5461649/211056370-9d3f044f-b8fe-4725-a26f-4549470b4883.png)


![image](https://user-images.githubusercontent.com/5461649/211056272-597773ad-7b70-4fc8-9711-3a2ffe7589b7.png)

**Comment by pavelfeldman** [comment]
Can I ask you to share a reduced case as a github repo? Trying to re-create the use-case based on the images is hard, especially given that there are some utilities that I don't have source code for...

**Comment by paustint** [comment]
@pavelfeldman - I have created a repo and was able to reproduce the issue. I am not sure about what the exact issue here is, but it is somehow related complex types.

https://github.com/paustint/playwright-issue-19526

* `test.describe("Run Test Cases1", async () => {`
  * This one does not have any green arrows
*  test.describe("Run Test Cases2", async () => {
  * this one works as expected with two green arrows (suite and test)
*  test.describe("Run Test Cases3", async () => {
  * This one is missing the green arrow on the suite, but has one on the test

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/5461649/211450593-0f5e4607-8a40-4faf-ba76-6a61461abfd4.png">

**Comment by pavelfeldman** [comment]
Playwright does not support async describes, all the tests need to be generated synchronously.

**Comment by paustint** [comment]
Ah, I guess that makes sense why I was having issues, I didn't realize that was the case. I ended up using fixtures to generate the test-cases and that seems to working.

Thanks for helping out!

**Comment by THLJamie** [comment]
Hi Paustint, Can you explain how you fix it by using fixtures? was the issue related with the imported types? I have similar issue even for a single test case, I have tried Google everywhere, haven't found out why. Thank you

**Comment by paustint** [comment]
@THLJamie - 
1. async test cases are not supported, if you have the `async` keyword in your test function, then it will not work (e.x. `test.describe('my test', async () => {})` is not allowed
2. your test-case names must be 100% unique

Aside from that, you would need to share an example to get specific information.

**Comment by priyankaencora** [comment]
I have just installed the playwright and unable to find the green triangular icon to execute and found that async is written in the code , so what is the replacement of this, how to execute the code.
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});

**Comment by nichita-pasecinic** [comment]
![image](https://github.com/microsoft/playwright/assets/98735377/cb058327-140e-42ed-b601-8b1d64187bb5)
mine are messed up - not aligned correctly with the test itself
