### ISSUE TITLE
[BUG] Playwright does not close port correctly

### ISSUE THREAD

**Issue by paymog** [microsoft/playwright#19520]
**Context:**
## System:
 - OS: macOS 12.6
 - Memory: 229.03 MB / 32.00 GB
## Binaries:
 - Node: 17.9.1 - ~/.nvm/versions/node/v17.9.1/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v17.9.1/bin/yarn
 - npm: 8.18.0 - ~/.nvm/versions/node/v17.9.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

This is more of a runtime problem with playwright

**Describe the bug**

I often find that playwright does not close it's port properly. Here's a workflow that often fails for me:

1. make a change to one of my tests
2. run the tests with `npx playwright test`
3. playwright runs the tests and opens the summary in the browser
4. some tests failed
5. I make changes to my test suit
6. go back to my terminal and hit `ctrl-c` to kill playwright
7. run tests again
8. see that port 9233 is still in use
9. use lsof to kill the node process using the port
10. run playwright again
11. port is *still* in use
12. kill the process again
13. run tests again, this time they succeed and open the browser tab

Here's a sample of the error that's output:

```
  1 failed
    [chromium] › project.spec.ts:104:5 › Project › delete › cannot delete self from project ========
  9 passed (2s)
node:events:505
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:9323
    at Server.setupListenHandle [as _listen2] (node:net:1380:16)
    at listenInCluster (node:net:1428:12)
    at doListen (node:net:1567:7)
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1407:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 9323
}
```

**Comment by yury-s** [comment]
Can you share project where it happens so that we could try it locally?

**Comment by paymog** [comment]
Unfortunately this happens in a private project which I can't share

**Comment by yury-s** [comment]
Unfortunately there is not much we can do without a repro because the same ctrl+c scenario works fine on simple tests, we also use it on a daily basis when running playwright test suite. There is likely something specific to your project / env, feel free to file a new bug if you have more details to share.
