### ISSUE TITLE
[Question] Same test with multiple data and parallel worker execution

### ISSUE THREAD

**Issue by Colas-RIPOLL** [microsoft/playwright#19539]
Hi,

I have a smoke test with multiple data.
When I use a single worker => all tests are passed
When I use more than 1 worker in playwright.config.ts 
```
	fullyParallel: true,
	workers: 5,
```
=> first started tests are always failed (here 5 tests because 5 workers) then the others are mostly (80%) passed.

For all failed tests, the trace is a goto in timeout => no network, no screenshot 
![image](https://user-images.githubusercontent.com/118912332/208245670-aa03b05d-6b90-4fed-bd43-fd4b0f631a06.png)

My code 

```
test.describe("Verification of : @smoke", () => {
	const listOfPage = [
		{
			name: "Test Class1",
			pageObject: MainPage,
		},
		{
			name: "Test Class2",
			pageObject: OtherPage,
		},
        ... // a lot of object page (about 30)
	];
	listOfPage.forEach((data) => {
		givenPersonaAdmin();
		test(`${data.name}`, async ({ page }) => {
			const currentPageObject = new data.pageObject(page);
			await test.step("WHEN Open page", async () => {
				await Promise.all([currentPageObject.navigateTo(), currentPageObject.detectAndCloseUserFlow()]);
			});
			expect(page.url(), "THEN Landing url is not redirect and functionality is correctly opened").toBe(
				currentPageObject.currentUrl,
			);
		});
	});
});
```

Any idea ? 

Playwright version : 1.28.0
Windows and wsl
Chronium

**Comment by pavelfeldman** [comment]
Could it be that you are using the same user when you log into your page concurrently?

**Comment by Colas-RIPOLL** [comment]
Yes ! 
As describe in documentation, I use a storage state before all these tests through global-setup.ts
So no real re-log.

**Comment by pavelfeldman** [comment]
You can refer to this: https://playwright.dev/docs/next/auth#avoiding-multiple-sessions-per-account-at-a-time

Note that this doc is slightly out of date, it should use `testInfo.parallelIndex` instead of `testInfo.workerIndex`.

**Comment by Colas-RIPOLL** [comment]
If I understand correctly, each worker needs to have its own copy of storage if we want to be able to have tests that connect with the same user in parallel ?

So, givenPersonaAdmin(); must know which worker it is on
The problem is that the worker is only known in the test function ( test("Verification of ...", async ({ page }) => {}) , not before but the test.use must be declared before the test function ...

Shouldn't this be native to playwright?
I'll try your link but I don't think it will meet my needs :-( namely:
- fully use the parallelism with the workers 
- be able to use the storage with its workers even if it is the same user to use

**Comment by pavelfeldman** [comment]
> If I understand correctly, each worker needs to have its own copy of storage if we want to be able to have tests that connect with the same user in parallel ?

I thought the whole point is that you can't have the same user connected in parallel, so you want to isolate the users. It means that you have as many admins and users as parallel tracks, so that the tests were independent.

> Shouldn't this be native to playwright?
> fully use the parallelism with the workers

That's what the solution under link does, it allows parallel execution of independent tracks

> be able to use the storage with its workers even if it is the same user to use

I'm not sure I follow this requirement. What do you mean "use storage with workers"?

**Comment by Colas-RIPOLL** [comment]
If I understand correctly, 
the "Reuse signed in state" in documentation allow to have 
- 1 worker 
- x test which use test.use(adminStorage.json) or test.use(standardUserStorage.json) or other pre-logged users of our choice just before 
	test("Verification of ... ", async ({ page }) => {}


The "Avoiding multiple sessions per account at a time" in documentation allow to have 
- x workers 
- all test which use only 1 type of users imported thanks to import { test, expect } from './fixtures';

My goal is to have/use both :)
- x workers
- x test before which I can choose the one prelogged user I want

I just saw this documentation : "Testing multiple roles with POM fixtures" and I'm going to try a merge with "Avoiding multiple sessions per account at a time"

**Comment by pavelfeldman** [comment]
Looks like you know what you are doing, closing!
