### ISSUE TITLE
[BUG] `page` events don't get emitted while running on `WebView2`

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#19530]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: v16.13.0
- Browser: WebView2

We are seeing a strange bug where the `pages` array of the current context not being updated when new pages materialize in our Product.

Workflow:

1. WebView2 App is launched with a debugging port on `9222`
2. We connect to WebView2 app via `connectOverCDP`
3. WebView2 App initially has just one page and Playwright is only able to see that one page.
4. After a period of time ~2s the WebView2 App spawns another page.
5. Playwright is not able to see the new page.

We have example code like this:

```ts
        this.browser = await chromium.connectOverCDP(CDPurl);

        // We always have just one context
        const currentContexts = this.browser.contexts();
        const contextInstance = currentContexts[0];
 
        const currentPages = contextInstance.pages();
```

`currentPages` will randomly have 1 or 2 pages forever depending on how fast our app starts and renders the second page.

If we put the connectOverCDP and methods for getting the contexts/pages in a loop, we do get a deterministic way to get the 2 pages.

```ts

       let currentPages = 0;

       while(currentPages !== 2){

        this.browser = await chromium.connectOverCDP(CDPurl);

        // We always have just one context
        const currentContexts = this.browser.contexts();
        const contextInstance = currentContexts[0];
 
        currentPages = contextInstance.pages();

      }
```

This leads me to possibly believe the event emitter in : `packages\playwright-core\src\client\browserContext.ts`

Does not emit while automating a WebView2 application?

```ts
    this._channel.on('page', ({ page }) => this._onPage(Page.from(page)));

  private _onPage(page: Page): void {
    this._pages.add(page);
    this.emit(Events.BrowserContext.Page, page);
    if (page._opener && !page._opener.isClosed())
      page._opener.emit(Events.Page.Popup, page);
  }


````

**Comment by mastrzyz** [comment]
This also is reproing if the test tries to open a new Window, we do not see the page in the `pages` function.

**Comment by mxschmitt** [comment]
Can you share a minimal reproduction with us? The best would be if you can use [this small demo](https://github.com/microsoft/playwright/tree/main/tests/webview2/webview2-app) and extend it with your "specific use-case". That would help a ton, thanks!

**Comment by mastrzyz** [comment]
@mxschmitt tried to augment the WebView2 sample app to open a new window but didn't reproduce the problem unfortunately.

Our App is a bit heavy with its implementation and not able to share but I did some more searching : 

Looks like the page first shows up as `other` and then after a delay turns into a `page` .
```
{                                                                                                                                                                                                                                   
  targetId: '7467F3C8603D79A3E5FC24AD249B9DAB',                                                                                                                                                                                     
  type: 'other',
  title: '',
  url: '',
  attached: true,
  openerId: '26F2F6CD85BABFD76DB501967238D75F',
  canAccessOpener: true,
  openerFrameId: '26F2F6CD85BABFD76DB501967238D75F',
  browserContextId: '5C623885469017F8602727BF85C58526'
}
```


If I add 
`    process.env.PW_CHROMIUM_ATTACH_TO_OTHER = "true";`

to our test file this race condition doesn't occur anymore, but I don't know if this is a `hack`

**Comment by mxschmitt** [comment]
I think this is currently the recommended approach as of today which we implemented for the Edge team back in the days.

Reference: https://github.com/microsoft/playwright/issues/14876

**Comment by mastrzyz** [comment]
Thank you for the clarification! appreciate the fast response, hopefully we can have this somewhat documented for WebView2 from Edge Team as I'm not 100% confident in why WebView2 behaves like this.
