### ISSUE TITLE
How to retry a failed test case in Playwright using C# and Visual Studio?

### ISSUE THREAD

**Issue by navreen1999** [microsoft/playwright#19544]
Hi All,
I'm searching for an option to retry failed test cases in Playwright using C# and Visual Studio

**Comment by pavelfeldman** [comment]
Retry is a feature of the test runner and not the Playwright Library. You should direct your question to your test runner vendor (NUnit/MSTest).

**Comment by DavinderZilo** [comment]
this option is available on node. but not dotNet. When will this be available
