### ISSUE TITLE
[Feature] Chaining function and methods

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#19545]
Hi there PW team!

I would like to suggest adding an option to chain the functions/methods like in the Syntax of the TestCafe framework (see examples below). And it is instead of starting every operation and line with the `await` keyword. 

We've used the TestCafe for some period and sometimes it feels more convenient and readable when you can chain the async functions (in the case of TestCafe it is possible with the object that provides APIs).

See the examples below.

Chained Syntax
![image](https://user-images.githubusercontent.com/52656401/208295342-a465bd47-6e54-4081-9c90-a286c4f96025.png)

![image](https://user-images.githubusercontent.com/52656401/208295401-8db21c8e-cec8-48cd-a2a6-b18e1e53ff71.png)

Thanks a lot for your time!

**Comment by pavelfeldman** [comment]
In each of the platforms we support, we pick the idiomatic way native to the platform. For Node.js and JavaScript in general, the idiomatic way is async/await.
