### ISSUE TITLE
[Feature] Make `parallelIndex` available in public API for reporters

### ISSUE THREAD

**Issue by vovsemenv** [microsoft/playwright#19541]
Sadly https://playwright.dev/docs/api/class-workerinfo#worker-info-parallel-index is not available in `TestResult` object for 
reporters. Let's make it visible.

Successor of https://github.com/microsoft/playwright/issues/19519

**Comment by vovsemenv** [comment]
@yury-s i can PR for this myself if it's fine

**Comment by vovsemenv** [comment]
👀

**Comment by pavelfeldman** [comment]
> @yury-s i can make PR for this myself if it's fine

Sure, go ahead!
