### ISSUE TITLE
[BUG] Error running with systemctl

### ISSUE THREAD

**Issue by farrokh** [microsoft/playwright#19549]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Linux
- Node.js version: v18.12.1.
- Browser: NA

**Code Snippet**
```python
from playwright.sync_api import sync_playwright, Playwright
def entry():
    Logger("1").log()
    try:
        with sync_playwright() as playwright:
            Logger("2").log()
            return run(playwright)
    except Exception as e:
        Logger(f"Error: {e}").error()
        return None
```

everything works fine when I run the code above inside my virtual env (source bin/activate) but I can't make this code run using systemctl and wsgi. I get the following error:
<img width="1136" alt="image" src="https://user-images.githubusercontent.com/392570/208335425-4f872dc4-4b1f-4abb-b291-85bb00dc7010.png">

my systemctl config:
```service
[Unit]
Description=uWSGI instance to serve foo
After=network.target

[Service]
User=boo
Group=www-data
WorkingDirectory=/home/boo/foo
Environment="PATH=/home/boo/foo/bin"
ExecStart=/home/boo/foo/bin/uwsgi --ini app.ini

[Install]
WantedBy=multi-user.target
```

and I didn't edit any of the .sh file:

```bash
#!/bin/sh
SCRIPT_PATH="$(cd "$(dirname "$0")" ; pwd -P)"
echo SCRIPT_PATH

if [ -z "$PLAYWRIGHT_NODEJS_PATH" ]; then
  PLAYWRIGHT_NODEJS_PATH="$SCRIPT_PATH/node"
fi
"$PLAYWRIGHT_NODEJS_PATH" "$SCRIPT_PATH/package/lib/cli/cli.js" "$@"
```

**Describe the bug**

FYI other routes of my API work fine just ones with Playwright don't.

**Comment by mxschmitt** [comment]
Instead of extending the `PATH` you are overriding it, that might explain the behavior since `dirname` is an executable located in `/usr/bin`.

**Comment by pavelfeldman** [comment]
This would be outside of the scope for Playwright. I'll close it to make it clear that core team is not looking at it, but others should feel free to comment on it with their suggestions.

**Comment by farrokh** [comment]
> Instead of extending the `PATH` you are overriding it, that might explain the behavior since `dirname` is an executable located in `/usr/bin` which Playwright needs when starting.

Thank you for your help. I fixed the path and I don't get that error anymore. 
`Environment="PATH=/home/boo/foo/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"`
however, for some reason it still doesn't react to my code:
```python
    try:
        from playwright.sync_api import sync_playwright
        import sys
        print('\n'.join(sys.path))

        with sync_playwright() as p:
            url = "https://www.wikipedia.org/"
            browser = p.chromium.launch(headless=True)
            Logger(f"opening {url} ...").info()
            context = browser.new_context()

            # Open new page
            page = context.new_page()
            page.goto(url)
            Logger(page.title(), 'is the title').log()

    except BaseException as error:
        print('An exception occurred: {}'.format(error))
```
<img width="537" alt="image" src="https://user-images.githubusercontent.com/392570/208506415-e3948891-3ad8-481d-9556-488af344d3de.png">

is it still outside the playwright's scope?

**Comment by mxschmitt** [comment]
Yes, don't override PATH, extend it instead. We are not familiar with systemctl so we can't provide any support on that. Make also sure you are using compatible operating systems. (debian 11 or ubuntu 20/22)
