### ISSUE TITLE
[REGRESSION]: Ubuntu 18 LTS not supported anymore

### ISSUE THREAD

**Issue by gunters63** [microsoft/playwright#19548]
Playwright 1.29.0 removed support for Ubuntu 18 LTS.
This breaks our CI builds on private Gitlab build agents which are running on Ubuntu 18 LTS.

What was the reason for removing the support now? Ubuntu 18 LTS has not reached its end-of-life yet (April 2023 with ESM until 2028). 

This forces us to update our internal servers ahead of the planned schedule if we want to stay up-to-date with Playwright.

**Comment by pavelfeldman** [comment]
Let me keep it open to collect reports.

**Comment by pavelfeldman** [comment]
Another workaround for you would be `channel: 'chrome'` in your config to use the branded Google Chrome that works on Ubuntu 18.

**Comment by fuongduyuid** [comment]
> 

Hi Pavel,

Could you please suggest a snippet of how to achieve this?
Is it a flag or something in `browser options`?

**Comment by gunters63** [comment]
But on the other hand, I just read the Github Ubuntu deprecation schedule about longer queues and temporarily failing jobs so I understand you decision. I guess we will have to update our servers sooner than planned.

**Comment by aslushnikov** [comment]
A best-effort support has landed on tip-of-tree and will be released in 1.29.1 as well.
