### ISSUE TITLE
[BUG] Cannot match direct HTML element of React components

### ISSUE THREAD

**Issue by hanayashiki** [microsoft/playwright#19550]
**Context:**
- Playwright Version: 1.29.0
- Operating System: MacOS
- Node.js version: 18.9
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

If my understanding for [React locators](https://playwright.dev/docs/other-locators#react-locator) is correct, then for the following component:

```jsx
import "./App.css";

function App() {

  return (
    <div className="App">
      App
    </div>
  );
}

export default App;

```

the `div` under it should be matched by `_react=App >> div`.

However, when I write a test for it, the `waitFor` just times out:

```js
// @ts-check
const { test } = require("@playwright/test");

test("cannot match direct html component under react component", async ({
  page,
}) => {
  await page.goto("http://localhost:5174/");

  await page.locator("_react=App >> div").waitFor({ state: "attached" });
});

```

**Describe the bug**

I think the locator should be able to match the `div` element.

However, if I add a `button` under `div`,

```js
function App() {

  return (
    <div className="App">
      App
      <button>button</button>
    </div>
  );
}
```

And `_react=App >> button` seems running ok.

I have a little fixture for the case above, and I hope that can be helpful:

https://github.com/hanayashiki/playwright-react-selector-fixture

**Comment by pavelfeldman** [comment]
Why do you need the `>> div` suffix and can't use `_react=App`? Alternatively, you can try using `_react=App >> div:scope`

**Comment by hanayashiki** [comment]
> Why do you need the `>> div` suffix and can't use `_react=App`? Alternatively, you can try using `_react=App >> div:scope`

because in my real application, there are two cases where the App could render different dom elements, and I want to match the exact type of element

**Comment by hanayashiki** [comment]
> Why do you need the `>> div` suffix and can't use `_react=App`? Alternatively, you can try using `_react=App >> div:scope`

Do you mean that `>> div` does not match `_react=App` itself at all? Then I think this is just my misunderstanding of `>>`.

Thank you!

**Comment by pavelfeldman** [comment]
`>>` means descendant, but you can use `:scope` modifier to make it apply to the root of the query.
