### ISSUE TITLE
Is there a way to start/run the docker in the detach mode

### ISSUE THREAD

**Issue by manoraj** [microsoft/playwright#19554]
Right now there are three steps to run the tests in the repository
1.`playwright docker build`
2.`playwright docker start` 
3. `yarn test`

I want to provide single command where it does all the three steps mentioned above. The problem with `playwright docker start` is that it doesn't start the docker in the detached mode which blocks executing the further steps.

Is there a way to run this docker in a detached mode for `playwright docker start` ??

**Comment by manoraj** [comment]
It looks like we have to write our own utilities which is the reason we used the `playwright docker` in the first place. I will wait for the outcome of the triage. Thanks!

**Comment by pavelfeldman** [comment]
That basically was the triage, you are referring to an undocumented option which is not necessary to run Playwright in docker. Refer to the https://playwright.dev/docs/next/docker docs for how to do that.
