### ISSUE TITLE
[Feature] Component Testing - support vite 4

### ISSUE THREAD

**Issue by SimonGolms** [microsoft/playwright#19552]
Vite has released their new version [4.x](https://github.com/vitejs/vite/blob/v4.0.0/packages/vite/CHANGELOG.md#400-beta0-2022-12-05) last week. In addition new major versions of [@vitejs/plugin-vue@4.0.0](https://github.com/vitejs/vite-plugin-vue/blob/plugin-vue@4.0.0/packages/plugin-vue/CHANGELOG.md#400-2022-12-09) and [@vitejs/plugin-react@3.0.0](https://github.com/vitejs/vite-plugin-react/blob/plugin-react@3.0.0/packages/plugin-react/CHANGELOG.md#300-2022-12-09) were released.

In my react project repo I have updated/migrated all related packages to the latest versions. The app can be started and built without problems. Unfortunately now the components tests fail with.

```sh
 $ npm run test

Running 1 test using 1 worker

vite v4.0.2 building for production...
✓ 517 modules transformed.
playwright/.cache/playwright/index.html                 0.39 kB
playwright/.cache/assets/index-7dbc7e2e.css            41.90 kB │ gzip:     7.76 kB
playwright/.cache/assets/status-tap-d1eefeb7.js         1.29 kB │ gzip:     0.62 kB │ map:     2.41 kB
playwright/.cache/assets/swipe-back-72cb9a37.js         2.08 kB │ gzip:     0.84 kB │ map:     4.44 kB
playwright/.cache/assets/web-b00e8e40.js                2.27 kB │ gzip:     0.74 kB │ map:     5.35 kB
playwright/.cache/assets/index10-238e3cb7.js            5.42 kB │ gzip:     1.75 kB │ map:    11.38 kB
playwright/.cache/assets/shadow-css-14acc35f.js        15.72 kB │ gzip:     4.19 kB │ map:    31.28 kB
playwright/.cache/assets/input-shims-64f83c07.js       16.18 kB │ gzip:     4.92 kB │ map:    30.54 kB
playwright/.cache/assets/swiper.bundle-0a6c0fd4.js    204.38 kB │ gzip:    39.96 kB │ map:   457.11 kB
playwright/.cache/assets/index-bf8add6e.js          5,402.51 kB │ gzip: 1,119.99 kB │ map: 8,820.85 kB
  ✘  1 [Desktop Chromium] › App.test.tsx:6:3 › App › renders (20s)


  1) [Desktop Chromium] › App.test.tsx:6:3 › App › renders =========================================

    Test timeout of 20000ms exceeded.

    Target closed

       5 | test.describe("App", () => {
       6 |   test("renders", async ({ mount }) => {
    >  7 |     const component = await mount(
         |                             ^
       8 |       <AppProviders>
       9 |         <App />
      10 |       </AppProviders>

        at /home/.../src/App.test.tsx:7:29


  1 failed
    [Desktop Chromium] › App.test.tsx:6:3 › App › renders ==========================================
```

I am not sure, but could it be that it now fails in combination with the usage of the incompatible `@vitejs/plugin-react@2.x`?

https://github.com/microsoft/playwright/blob/b5f908d31f821a7462cf6caa92a2a85e9602a25b/packages/playwright-ct-react/package.json#L28-L32

I would appreciate it very much if these dependencies are also updated in a timely manner so that the latest version of `vite@4.x` is also supported. In the meantime my only current known solution is to continue using `vite@3.x` in my react project.

**Comment by pavelfeldman** [comment]
We are using vite as our implementation detail, you should be able to use any vite version, while Playwright will be using 3.2.1 internally. Theoretically, we should be able to switch to some other bundler to build components for test without breaking our users. Is there anything you did to your components while converting to vite v4 that made them stop working with other versions of the bundler / with other bundlers?

**Comment by pavelfeldman** [comment]
Your issue has a good title, so users that experience the problem will be able to find it and look at your investigation note. Upvoting your comment and closing.
