### ISSUE TITLE
[REGRESSION]: waitUntil: 'domcontentloaded' in page.goto()

### ISSUE THREAD

**Issue by MattEarth** [microsoft/playwright#19553]
**Context:**
- GOOD Playwright Version: 1.28.1
- BAD Playwright Version: 1.29
- Operating System: ubuntu 20.04 LTS
- Extra: -

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

    await page.goto(pageUrl, { timeout: timeouts.TIMEOUT_60S, waitUntil: 'domcontentloaded' });

**Describe the bug**

waitUntil 'domcontentloaded' failed in syntax as in code above.

**Comment by MattEarth** [comment]
Just try to use the following syntax in your code:
`await page.goto('https://playwright.dev/', { timeout: 60000, waitUntil: 'domcontentloaded' })`
it ends with an error in the latest version (1.29), whereas works as expected in version 1.28. Or maybe I missed something in change log?

**Comment by pavelfeldman** [comment]
Could you print / screenshot the error? What do you mean by syntax error?

I see no TSC errors:

![error1](https://user-images.githubusercontent.com/883973/208529057-daabedac-d79a-433e-aa2c-3dbca56fa81c.png)

And no test errors:

![error2](https://user-images.githubusercontent.com/883973/208529264-e8540cc5-c3e7-47aa-a86c-91b295fe5811.png)

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
