### ISSUE TITLE
[Question] How to use headed/debug mode for browser in global setup?

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#19566]
Similar to the questions at the end of this thread [here](https://github.com/microsoft/playwright/issues/12588), if I manually launch a browser in global setup, how can I see that in headed or debug mode?

**Comment by pavelfeldman** [comment]
There is no built-in support for that atm. You can launch your browser with headed: process.env.HEADED and hence control the mode your browser comes up in via the environment variable HEADED.

**Comment by pavelfeldman** [comment]
Starting with v1.31 you'll be able to shape your global setup as a set of tests: https://playwright.dev/docs/next/api/class-testproject#test-project-dependencies. You can configure headless/headed for that setup project. You can give it a try with `npm i @playwright/test@next`.

**Comment by WesleyYue** [comment]
awesome api! it makes a lot of sense since most people are essentially testing login at setup
