### ISSUE TITLE
[Question] After the search operation, how can I wait for the searched row in the table to come and verify searched name is correct?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19569]
I have search text field in my web page. When I type a name into Search field, only the row of that name is displayed instead of the all rows in the table. But when I type a name into search field, I just have to wait. I don t use hard wait.

**I search and verify using below code. But this code sometimes works good, sometimes giving error.** 
         
     ```
           await page.getByPlaceholder("Search...").fill("Yusuf")
                await page.getByPlaceholder("Search...").press('Enter');
                await page.locator("//tbody/tr/td[2]", { hasText: "Yusuf"}).waitFor()
                await expect(page.locator("//tbody/tr/td[2]")).toHaveText("Yusuf")

**This is the table html structure after search,I try to reach second td.**
```
        <tbody class="ant-table-tbody">
        <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">1</td>
        <td class="">"Yusuf"</td>
```


**This is the table html structure before search**

```
<tbody class="ant-table-tbody">
     <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">1</td>
        <td class="">"Yusuf"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">2</td>
        <td class="">"Geo"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">3</td>
        <td class="">"Hrl"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">4</td>
        <td class="">"Abl"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">5</td>
        <td class="">"GB"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">6</td>
        <td class="">"GH"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">7</td>
        <td class="">"HY"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">8</td>
        <td class="">"REO"</td>
<tr class="ant-table-row ant-table-row-level-0" >
        <td class="">9</td>
        <td class="">"NEO"</td>
<tr class="ant-table-row ant-table-row-level-0" >
        <td class="">10</td>
        <td class="">"FRG"</td>
```

The error I get some times is as follows;

```
expect.toHaveText: Error: strict mode violation: locator('xpath=//tbody/tr/td[2]') resolved to 10 elements:
    1) <td class="">Yusuf</td> aka getByRole('cell', { name: 'Yusuf' })
    2) <td class="">Geo</td> aka getByRole('cell', { name: 'Geo' })
    3) <td class="">Hrl</td> aka getByRole('cell', { name: 'Hrl' })
    4) <td class="">Abl</td> aka getByRole('cell', { name: 'Abl' })
    5) <td class="">GB</td> aka getByRole('cell', { name: 'GB' })
    6) <td class="">GH</td> aka getByRole('cell', { name: 'GH' })
    7) <td class="">HY</td> aka getByRole('cell', { name: 'HY' })
    8) <td class="">REO</td> aka getByRole('cell', { name: 'REO' })
    9) <td class="">NEO</td> aka getByRole('cell', { name: 'NEO' })
    10) <td class="">FRG</td> aka getByRole('cell', { name: 'FRG' })
```


I m taking above error  because the search process is not complete and it pulls all the rows. If the search is done fully, a single row will come and I will have verified it.After the search operation, how can I wait for the searched row in the table to come and verify searched name is correct? I don't want using any hard delete or delay because time can be changeable when search is done

**Comment by pavelfeldman** [comment]
> await page.locator("//tbody/tr/td[2]", { hasText: "Yusuf"}).waitFor()

This check is Ok, you are waiting for the row

> await expect(page.locator("//tbody/tr/td[2]")).toHaveText("Yusuf")

This check is wrong - you expect `"//tbody/tr/td[2]"` to have certain text, but there are more than one. You actually don't need this check, you already ensured that this row exists in the check above.
