### ISSUE TITLE
Hyphens in html attributes not supported? 

### ISSUE THREAD

**Issue by pradeipp** [microsoft/playwright#19561]
I was trying to get an element with test id that contained a hyphen: 

e.g.
```HTML
<button id='submit-login'>
``` 
Playwright: 
```JS
 await page.locator('#submit-login').click();
```
OR
```JS
 await page.locator('#submit\\-login').click();
```

None of the above two ways seem to be able to find the button. Are attributes with special characters like hyphens not supported in playwright?

**Comment by mxschmitt** [comment]
The first should work, do you maybe get an error that e.g. the button is disabled?

```js
  await page.setContent(`<button id="my-button">Click me</button>`);
  await page.locator('#my-button').click();
```

**Comment by pradeipp** [comment]
Hi @mxschmitt sorry for  false alarm, it was apparently because some test IDs I added werent showing up. The hypens can be escaped in both attribute values and attributes names itself and playwright handles both situations gracefully. Thank you :)
