### ISSUE TITLE
[BUG] Playwright does not support chromium on ubuntu18.04

### ISSUE THREAD

**Issue by fuongduyuid** [microsoft/playwright#19575]
**Context:**
- Playwright Version: playwright-chromium ^1.23.0
- Operating System: Ubuntu 18.04
- Node.js version: v16.14.2
- Browser: Chromium

**Describe the bug**
I'm having a project using playwright-chromium. Everything runs okay until this morning when I go to the server, ran test scripts and playwright announced that `Playwright does not support chromium on ubuntu18.04`
I tried re-install but does not help

Anyone can help me on this?

Thank you

**Comment by ltsuda** [comment]
same as https://github.com/microsoft/playwright/issues/19548
Please, see if is the same issue.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/19548, please upvote that issue.
