### ISSUE TITLE
[Feature] `globalSetup` should [optionally] be able to wait for `config.webserver` to be active before running

### ISSUE THREAD

**Issue by wibjorn** [microsoft/playwright#19571]
The Playwright documentation about various automated [authentication methods](https://playwright.dev/docs/auth) is excellent and will indeed allow for developers who log in _through a remote context__ to be able to save their storage state. 

However, there may be various workflows in which we want to start our web server, visit a local page, log in _locally or even via a local proxy_, and save our state that way. This is a problem on larger code bases that might take some time to start up a webserver 🥹😿.

This is because the following global setup code will run even before (or perhaps during) the webserver's set up. It's possible (consistent in my case at least) that global set up runs before the webserver is available.

```ts
export default async function globalSetup(config: FullConfig) {
	const browser = await chromium.launchPersistentContext('', {
		channel: 'msedge',
		ignoreHTTPSErrors: true
	});
	const page = await browser.newPage();

	await page.goto('https://localhost:1111', {
		timeout: 240 * 1000, // 💀 ineffectual if the server hasn't had time to start yet, and page.goto throws due to ERR_CONNECTION_REFUSED 
		waitUntil: 'networkidle'
	});

	const username= 'xxxxxxx@test.com';
	const password = 'xxxxxxx';

	const testUsers = [{ username, password}];

	for (const { username, password } of testUsers) {
		await signinAndSaveState(page, username, password);
	}

	await browser.close();
}
```

And we'll get an error something on the order of this:

```txt
page.goto: net::ERR_CONNECTION_REFUSED at https://localhost:1111/
=========================== logs ===========================
navigating to "https://localhost:1111", waiting until "networkidle"
============================================================

   at ..\lib\sign-in.ts:10

   8 |  const page = await browser.newPage();
   9 |
> 10 |  await page.goto('https://localhost:1111/', {
     |             ^
  11 |          timeout: 240 * 1000,
  12 |          waitUntil: 'networkidle'
  13 |  });

    at globalSetup (pathto\integration\lib\sign-in.ts:10:13)

  8 skipped
  1 error was not a part of any test, see above for details
```

What I would like to suggest is that we expose some functionality to allow global setup to await the web server if its required. Just a few quick ideas below for interfaces, take them with a grain of salt; it's the main idea that is important here.

1. `available` property on config.webServer.

    ```ts
    export default async function globalSetup(config: FullConfig) {
	    await config.webServer.available;
	    // etc
    }
    ```

2. `globalSetup` auto awaits `webserver` if `webserver` is specified in config
3. FullConfig gets a `globalSetupAwaitsWebserver` boolean property
4. New union type for `globalSetup` to allow for `awaitWebserver` boolean.
    ```ts
    // test.d.ts
    globalSetup?: string | {
	    path: string,
	    awaitWebserver: boolean
    };
    ```

Thanks for listening!

**Comment by pavelfeldman** [comment]
Our code suggests that global setup only runs after the web server has been set up and the endpoint became available [source code](https://github.com/microsoft/playwright/blob/53ef0d060c6ee04cc537502ea74959b02c4299cb/packages/playwright-test/src/runner.ts#L612). Could you share an example that we could reproduce?

**Comment by wibjorn** [comment]
Closing this one, you are correct that it does wait @pavelfeldman. Problem was in fact with my code 💀. Thanks for the quick response!
