### ISSUE TITLE
[BUG] userAgent in config doesn't work

### ISSUE THREAD

**Issue by goldylucks** [microsoft/playwright#19585]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac
- Node.js version: 16.18.0
- Browser: chrome

```
## System:
 - OS: macOS 13.0.1
 - Memory: 1.29 GB / 32.00 GB
## Binaries:
 - Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
 - Yarn: 1.22.18 - ~/.yarn/bin/yarn
 - npm: 8.19.2 - ~/.nvm/versions/node/v16.18.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
```

**Code Snippet**
```
// playwright.config.ts
config.use.userAgent = "foo"

// backend ctrl
console.log(req.headers["user-agent"]) // no "foo" in there
```
**Describe the bug**

"foo" should appear in the user agent

**Comment by pavelfeldman** [comment]
> config.use.userAgent = "foo"

Each of your projects defines userAgent using `...devices[...]`, they are project specific, so they take precedence over the global value.

```js
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'], // Desktop Chrome has `userAgent` property that matches Chrome's UA.
      },
    },
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
