### ISSUE TITLE
[Feature] Tell the browser playwright is running it

### ISSUE THREAD

**Issue by goldylucks** [microsoft/playwright#19584]
I want my app to know it's running under playwright, one use case is running tests on production environment, and telling the html to NOT load google analytics and other trackers.

How can I go about it?

**Comment by vovsemenv** [comment]
pw have bunch of globally injected variables like `__pw_recorderState`. see (more)[https://github.com/microsoft/playwright/blob/3565d97a36a13c690aeb9730bd38e1aa222c1be7/packages/playwright-core/src/server/injected/recorder.ts#L25]

you can use it 🙌🏽

**Comment by pavelfeldman** [comment]
The answer above is not correct, recorder is not there when codegen is not recording. You can do something like this:

```js
test.beforeEach(({ context }) => {
  await context.addInitScript(() => window.isUnderTest = true);
});
```

then in your page, you can do

```js
if (window.isUnderTest) ...
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by tsvetkovv** [comment]
For everyone else who come to solve the same issue, use [navigate.webdriver](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/webdriver) property. You don't need to set anything from playwright
