### ISSUE TITLE
[Question] Is there a way to detect and delete obsolete snapshots using playwright 

### ISSUE THREAD

**Issue by Jamesj001** [microsoft/playwright#19597]
- Is there any flag/api provided currently we can use to detect and delete obsolete snapshots present ?

**Comment by pavelfeldman** [comment]
There is no such feature, but if you delete all the snapshots and run Playwright with update snapshot flag, it'll generate only the ones that are used.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by stuymedova** [comment]
@pavelfeldman It'd be nice to have this as a feature. Otherwise screenshots directories can get polluted so we have to monitor this on code review when clearly this can (and should) be automated
