### ISSUE TITLE
[BUG] dumpio no longer seems to be an option when launching

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#1959]
**Context:**
- Playwright Version: 0.15.0
- Operating System: macOS

**Code Snippet**

```javascript
const browser = await playwright[browserType].launch({ headless: false, dumpio: true });
```

**Describe the bug**

This was not a compile error before (0.12.1), but seems now.

**Comment by mxschmitt** [comment]
Hey,

`dumpio` was removed (#1861) in 0.14 and replaced by the logger sink API. Unfortunately not mentioned in the docs directly with the dumpio keyword.

Example Usage: https://playwright.dev/#version=v0.15.0&path=docs%2Fapi.md&q=class-logger

**Comment by bpasero** [comment]
@mxschmitt thanks, what would be an example for getting the `dumpio: true` behaviour?

**Comment by mxschmitt** [comment]
> @mxschmitt thanks, what would be an example for getting the `dumpio: true` behaviour?

Probably something like that: https://try.playwright.tech/?s=71xa6

That will lead to that all messages will be logged to the console.

Via the `isEnabled` callback, you can filter if you only want to get browser or protocol logs.

**Comment by bpasero** [comment]
Thanks, I will give that a try.

**Comment by pavelfeldman** [comment]
Debug logging is now configured via the environment:

```js
DEBUG=pw:browser* node test.js
```

And for more complex scenarios you can use the `logger` sink in the api.
