### ISSUE TITLE
[BUG] Playwright is using intel Chrome instead of arm64 on Mac with M1 chip.

### ISSUE THREAD

**Issue by mrwwalmsley** [microsoft/playwright#19602]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Mac
- Node.js version: 18.12.1
- Browser: Google Chrome
- Extra: Mac Studio with M1 max

**Code Snippet**

Terminal command: `npx playwright test --headed`

Playwright config:

```
projects: [
    {
      name: 'Google Chrome',
      use: {
        channel: 'chrome',
      },
    },
  ],
```

**Describe the bug**

I recently "upgraded" from a intel i5 2018 Mac Mini to a new Mac Studio with M1 max chip.

Suddenly my Playwright e2e tests started running so slowly that half of them fail with a 30 second timeout.

When I run in headed mode with "Google Chrome" as the browser, the browser opens and has a white screen for 10-15 seconds before my page loads in the browser. On my old intel Mac Mini the page loads in a 1-2 seconds.  This 10 second+ delay is enough for many of my tests to fail.

When I installed Chrome, I installed the universal version.

I can see that in headed mode Playwright is launching the Intel version of Chrome.
When I run Chrome from the "Applications" folder, the OS launches the arm64 (Apple Silicon) version.

Is there anyway to force Playwright to use the arm64 version? I suspect this is the cause of the tests loading slowly, since that seems to be the only difference between my Mac Mini and Mac Studio setup.

When I switch to using Chromium, the tests complete as quickly as expected.

**Comment by pavelfeldman** [comment]
When you use `channel: 'chrome'`, Playwright is going to run Google Chrome installed on your system. If you installed universal binary, it'll be using universal binary. It basically runs `/Applications/Google Chrome.app/Contents/MacOS/Google Chrome`.

**Comment by mrwwalmsley** [comment]
I discovered the problem.

When I setup my MacStudio it copied across the Intel version of NodeJS and NPM.
Running Playwright in Intel NodeJS was launching the Intel version from universal Chrome.

Running Chromium from Playwright with Intel NodeJS installed and ran arm64 Chromium.

I installed arm64  NVM/NodeJS/NPM and then reinstalled Playwright and now it is opening the arm64 version of Chrome.  This eliminated the 10-15 second loading cost on each test.

My Jest unit tests are also running twice as fast now.

I'm guessing there is nothing you can do on your end about this!

**Comment by bdav** [comment]
> Running Playwright in Intel NodeJS was launching the Intel version from universal Chrome.

@mrwwalmsley how do you tell which version of Chrome nodejs is launching?
