### ISSUE TITLE
[BUG] Playwright in Storybook

### ISSUE THREAD

**Issue by hlawuleka** [microsoft/playwright#1960]
**Context:**
- Playwright Version:   "0.15.0",
- Operating System: Mac Catalina 10.15.3 
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ... 
})();
```

**Describe the bug**

`ERROR in ./node_modules/playwright-core/node_modules/extract-zip/index.js Module not found: Error: Can't resolve 'fs' in '<path/to/node_modules/playwright-core/node_modules/extract-zip>'`

`ERROR in ./node_modules/playwright-core/node_modules/fd-slicer/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/.../project-folder/node_modules/playwright-core/node_modules/fd-slicer'`

**Comment by pavelfeldman** [comment]
Could you share more about how you installed playwright and your Node version? It can't find the standard node module `fs`, which suggests an installation error...

**Comment by hlawuleka** [comment]
`yarn add playwright` or `npm i playwright`
Nove v14, I was on version 12 and upgraded but still had the same issue.

**Comment by mxschmitt** [comment]
How do you run your tests? Directly via the `node` executable or via e.g. webpack in a SPA like React?

**Comment by hlawuleka** [comment]
The latter, thanks @mxschmitt 

if this helps, this is part of the many errors that are spit on the console:

```
ERROR in ./node_modules/playwright-core/node_modules/extract-zip/index.js
Module not found: Error: Can't resolve 'fs' in '/Users/.../playwright-core/node_modules/extract-zip'
 @ ./node_modules/playwright-core/node_modules/extract-zip/index.js 3:44-57
 @ ./node_modules/playwright-core/lib/server/browserFetcher.js
 @ ./node_modules/playwright-core/download-browser.js
 @ ./node_modules/playwright/index.js
 @ ./file-importing-playwright.js
 @ ./src/packages/3-docblocks-example.stories.mdx
 @ ./src/packages sync ^\.\/(?:(?:|\/|(?:(?:(?!(?:|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.(js|ts|tsx|mdx))$
 @ ./.storybook/generated-entry.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./node_modules/@storybook/addon-docs/dist/frameworks/common/config.js ./node_modules/@storybook/addon-docs/dist/frameworks/react/config.js ./.storybook/preview.js ./node_modules/@storybook/addon-knobs/dist/preset/addDecorator.js ./.storybook/generated-entry.js (webpack)-hot-middleware/client.js?reload=true&quiet=true```

**Comment by hlawuleka** [comment]
> How do you run your tests? Directly via the `node` executable or via e.g. webpack in a SPA like React?

The command I run in my React app is: `yarn test:unit`

**Comment by mxschmitt** [comment]
And whats behind `test:unit` in your package.json scripts section?
My guess is that you try to run it in a webpack environment.

**Comment by hlawuleka** [comment]
Correct, you guessed accurately.

**Comment by hlawuleka** [comment]
Wait!!!! This actually happens before I even begin testing, this happens as I try to boot up my app with `yarn storybook`....

**Comment by hlawuleka** [comment]
Which then output a set of these before the errors above:

```
(node:5294) Warning: Accessing non-existent property 'cat' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5294) Warning: Accessing non-existent property 'cd' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'chmod' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'cp' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'dirs' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'pushd' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'popd' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'echo' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'tempdir' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'pwd' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'exec' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'ls' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'find' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'grep' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'head' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'ln' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'mkdir' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'rm' of module exports inside circular dependency
(node:5294) Warning: Accessing non-existent property 'mv' of module exports inside circular dependency```

**Comment by mxschmitt** [comment]
At least in that configuration, webpack then tries to bundle Playwright for the web, so storybook can consume it. Thats not possible. If you want to use Playwright, then you have to run them on your hosts machine directly.

**Comment by hlawuleka** [comment]
Is this to say I cannot do `import { firefox, chromium } from 'playwright'` and follow the example that's given above - please see the first post?

**Comment by mxschmitt** [comment]
If this is in a webpack consumed / storybook environment, then not. It needs to run on the backend in the end.

Alternative is to run it directly via the `node` executable. What are you trying to archive?

**Comment by hlawuleka** [comment]
I think I have a better understanding now, wow - thanks for patiently assisting me to this point. I actually just createx a server-side and run one of the examples in node and everything worked.

But to answer your question, I have test cases/files (`.tsx`) that reside inside my storybook project alongside the component (s) code, so my `yarn test` runs through all `.test.tsx` files and then execute the test suites in those files. I was and am still able to do and achieve this with Puppeteer, hence i thought I could easily do the same with Playwright.
