### ISSUE TITLE
[BUG] page.route() preventing page redirect with login button

### ISSUE THREAD

**Issue by BenzTivianne** [microsoft/playwright#19607]
**Context:**
- Playwright Version: Latest (1.28.0)
- Operating System: Mac M.1
- Node.js version: N/A (Don't have or cannot find) 
- Browser: All
- Extra: Using VSCode. Headful playwright. 

**Code Snippet**

```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context()
    page =  context.new_page()

    page.route("**/*.{png,jpg,jpeg}", lambda route: route.abort()) # Redirect works works when this line is commented out

    page.goto('https://www.test-website.com/sign-in-page')

    page.type(selector="//input[@id='email']", text='fake_email@email.com')
    page.type(selector="//input[@id='password']", text='password123')
    page.click(selector="//*[@id='login-button']/button") # Redirects to main page as well as log in 
    
    print('Test Complete') # Code is able to get here but does not load main page when page.route() is uncommented out
```

**Bub Description**

I am not sure if this is a bug or if I am missing a piece of code to help me but I attempting to log into a webpage, enter my username/password, then click a button that logs me in. The button that logs me in also redirects me to the main webpage when clicked: https://www.test-website.com/main-page (different than the login webpage). It seems that the page.route() function prevents the new page from loading since if I comment that line out, the page no longer hangs and is able to redirect me. Do I need to add something else to let my program know I want the redirect or will I need to remove the page.route entirely? 

Potential similar issue I found: https://github.com/microsoft/playwright/issues/19158 

Thank you for any insight into this!

-Benz

**Comment by pavelfeldman** [comment]
It is hard to tell without being able to reproduce locally. Could it be that your main page requires some assets that are matching the route pattern to load?

**Comment by BenzTivianne** [comment]
Hi pavelfeldman. Thank you for your response. There is not but I have an idea of how to reproduce the same issue. I tested it and it has the same outcome: 

```Python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context()
    page =  context.new_page()

    page.route("**/*.{png,jpg,jpeg}", lambda route: route.abort()) # remove this line to no longer have an infinite load state

    page.goto('https://www.wikipedia.org/')

    print('Test Complete') # Add break point here

```

When adding a break point to the final print statement, let the page to wikipedia load. Then select any of the links on the page. It will be stuck in an infinite load state. This happens no matter what the page.route() option is. And when the page.route() option is removed, all links are able to load and redirect the user to the webpage. 

I believe this has the same concept as when the user logs into a website and is redirected to a different webpage upon hitting the login button. Are you also able to replicate this? 

-Benz

**Comment by pavelfeldman** [comment]
This second one is working as intended: you are using sync API and you block the thread on your breakpoint. Now that you are on the breakpoint, no code can run. But when you navigate the page in the browser, it wants to route the requests, to check their url pattern, etc. But they can't because you blocked the execution with your breakpoint.

**Comment by BenzTivianne** [comment]
Thank you for your explanation. Does that mean that async should allow the web browser to redirect to a different webpage if there is a page.route()? 

I am trying to figure out what is the best way to have a page.route() in my code to block certain traffic (ie images) but also allow web url redirects when a button is clicked. It seems that it does not matter if I use async vs sync, if there is a page.route() in the code, redirects from button clicks or manual clicks will be blocked. Is that correct?

**Comment by pavelfeldman** [comment]
> Thank you for your explanation. Does that mean that async should allow the web browser to redirect to a different webpage if there is a page.route()?

It is not about async, both will work, sync and async. It does not work because you set a breakpoint there. Replace it with print() and it'll work. Your code snippet seems correct, that's why we need a reproducible scenario to investigate further.

**Comment by BenzTivianne** [comment]
I understand now, thank you for the explanation. Also, after many testing attempts, I found that the issue lies with chromium and it not able to 'click' < button > tags as the following code works with firefox and webkit: 

```Python
from playwright.sync_api import sync_playwright
import time
with sync_playwright() as p:
    browser = p.firefox.launch(headless=False) # change this to chromium and the click() hangs 
    context = browser.new_context()
    page =  context.new_page()

    page.route("**/*.{png,jpg,jpeg}", lambda route: route.abort())

    page.goto('https://login.g2a.com/welcome/?redirect_uri=https://www.g2a.com/')

    page.type(selector='//*[@id="6c71f04f-8525-4312-a48e-d22676b232b4"]/div[2]/div/form/div[1]/label/div/input', text='youremail@email.com', delay=50)
    page.locator('//*[@id="6c71f04f-8525-4312-a48e-d22676b232b4"]/div[2]/div/form/button').click()
    page.wait_for_url('https://login.g2a.com/login-page')

    print('Test Complete')
```

The page.route was what I expected was the issue for the reasons you stated above, but it was the fact that no matter what, chromium cannot click the button. It looks like the button gets clicked, then the 'page_wait_for_url' is called and a timeout exception is thrown after 30000 ms. 

With firefox and webkit, the next login page (with email and password entries) loads properly with the button click

**Comment by dgozman** [comment]
The action item here would be to serialize the route pattern and send it to the server side, so that unrelated network requests do not wait for the client paused on a breakpoint.
