### ISSUE TITLE
[BUG] docs showing same titles for methods

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#19603]
API class docs showing multiple of same heading in side bar.

All overloads should have single entry

https://playwright.dev/docs/api/class-test#test-skip-1

<img width="994" alt="Screenshot 2022-12-20 at 19 30 38" src="https://user-images.githubusercontent.com/13063165/208740070-3d1156fb-4170-4955-9891-304d9dfe45d6.png">

**Comment by pavelfeldman** [comment]
Fixed.
