### ISSUE TITLE
[Question] - Test Name at Run Time

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#19604]
Hi guys!

I am experimenting something and need a suggestion / guidance / advice :) .

I 've created helper class that reads information from a json file. The files I am reading, are part of the Web Dev Project, so I just need to get some configuration from there basically ..
Then, I am looping through some of the values and generating my tests inside the loop, adding the value to the test name, so it'd be something like:

```
let myValues  = helper.ReadValues()

for (const myValue of myValues) {
  test.describe("Describe",() =>{
    test(`My test name is ${myValue}`, async ({ page }) => {
      //TODO
    });
  })
}
```

But I noticed, as it is reading the values at runtime, I can't execute the tests from the Playwright test executor, as it does not recognize them, however, I can run them within the terminal. Any suggestion on what's the best way to handle something like this ? or is there something I could be missing and this is not the expected behaviour ?
Thanks a lot!

**Comment by pavelfeldman** [comment]
>I can't execute the tests from the Playwright test executor, as it does not recognize them, however, I can run them within the terminal.

Do you mean you can't run it from VS Code sidebar by name? Sidebar should have all the generated test names right and you should be able to run them. If this does not work, can you extract a reduced reproducible case for us to fix?

**Comment by imartinflores** [comment]
Hi @pavelfeldman ! Yes, it does not recognize the tests on the sidebar or even on the same spec file (Left hand side, play arrows are not there) - If instead of reading the names from the config file at runtime, I create an array of strings in the file itself, it picks them up and recognize the tests. Let me see if I can get an example for you (I will try to create a similar local repo, also to double check there is nothing else messing it up).

**Comment by imartinflores** [comment]
@pavelfeldman That was a good exercise, I think I've found the problem, sorry, it was my mistake. I did not spot it before, but when reading the files, the path contains an environment variable. I hardcoded that value and it worked. Should a null or empty check help with that? i.e:

```
actual:
let path = `root/project/${process.env.FILENAME}`

refactored:
let path = ! ! process.env.FILENAME ?  `root/project/${process.env.FILENAME}`  ?  `root/project/myfile`  (Just as example)
```

**Comment by imartinflores** [comment]
I think we can close it :). I've added some checks for the env variables and seems to be working. Will dig a little bit more and open a new question if needed. Thanks as always!
