### ISSUE TITLE
[Question] How to test that a tab opened even without internet?

### ISSUE THREAD

**Issue by canopy-js-user** [microsoft/playwright#19612]
Hi there, I want to test that a certain interaction in my app opens a new tab to www.google.com. So I have this code: 

```
    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.locator('body').press('Enter')
    ]);
    await newPage.waitForLoadState();

    await expect(newPage).toHaveURL(/google\.com/);

```

It works when my test suite runs with an internet connection, but when it doesn't have internet, the URL of the new tab is eg `chrome-error://chromewebdata/`, and so this test fails, even though I want it to pass because from my perspective the URL is google.com eg:

<img width="582" alt="image" src="https://user-images.githubusercontent.com/47240210/208797314-05b172ac-0ff0-431d-ab51-72e68a48c5de.png">

Is there any way to assert even in the event of an error page that the page that the browser had been requesting was google.com?

Thanks

**Comment by Eugene-grb** [comment]
Get text from some element, for example from a button on the main page

**Comment by canopy-js-user** [comment]
@eugene-grb Sorry, could you elaborate just a bit? You mean rather than asserting on the opened tab, asserting on the original page?

**Comment by pavelfeldman** [comment]
chrome-error://chromewebdata/ is an error interstitial, the page actually thinks it is on that url, while the browser shows a dummy google.com entry to the user. I don't think there is a way to check that location value with Playwright.

To test transitions to the third party sites without navigating to them, it is best to use

```js
  await page.context().route(
      'https://*google.com/**',
      route => route.fulfill({ body: 'I am on www.google.com' })
  )
```

The entire google page will be replaced with this mock and you can test it via

```js
  await expect(page.locator('body')).toHaveText('I am on www.google.com');
```

**Comment by imartinflores** [comment]
@canopy-js-user if it is a new tab, have you tried context.pages() ? that should give you the list of opened pages within that context.

**Comment by canopy-js-user** [comment]
@imartinflores I think the problem is that when chrome eg gets a network error, the page objects don't retain any reference to what page was requested that generated the error

**Comment by canopy-js-user** [comment]
@pavelfeldman It doesn't look like the code you wrote is mocking anything for me. I suspect that is because in my case, I want to mock a new tab that doesn't exist yet? I just tried this but it didn't work because the new tab is opened before the mock takes effect:
```
    await page.goto('United_States/New_York/Style_examples#URLs');
    await expect(page.locator('.canopy-selected-link')).toHaveText('URLs');

    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.locator('a:has-text("http://google.com")').click()
    ]);

    await newPage.route(
      'https://*google.com/**',
      route => route.fulfill({ body: 'I am on www.google.com' })
    )

    await newPage.waitForLoadState();
```

Is there any way to mock all tabs, even ones that have not been opened yet? Thanks

**Comment by pavelfeldman** [comment]
Your snippet does not work because it is different from my snippet:
- you need to route context, not page
- you need to do that before you do anything else, first thing in your test.

**Comment by canopy-js-user** [comment]
@pavelfeldman Hi, sorry for being unclear, I did try your snippet first, and it also didn't work. Ie:
```
    await page.context().route(
      'https://*google.com/**',
      route => route.fulfill({ body: 'I am on www.google.com' })
    )

    await page.goto('United_States/New_York/Style_examples#URLs');
    await expect(page.locator('.canopy-selected-link')).toHaveText('URLs');


    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.locator('a:has-text("http://google.com")').click()
    ]);

    await newPage.waitForLoadState();

    await expect(newPage).toHaveURL(/google\.com/);
```

This doesn't seem to mock anything, and the test fails when there is no internet.

Thanks

**Comment by canopy-js-user** [comment]
@pavelfeldman And it also fails when I assert on the body text like in your example:
```
    await page.context().route(
      'https://*google.com/**',
      route => route.fulfill({ body: 'I am on www.google.com' })
    )

    await page.goto('United_States/New_York/Style_examples#URLs');
    await expect(page.locator('.canopy-selected-link')).toHaveText('URLs');


    const [newPage] = await Promise.all([
      context.waitForEvent('page'),
      page.locator('a:has-text("http://google.com")').click()
    ]);

    await newPage.waitForLoadState();

    await expect(newPage.locator('body')).toHaveText('I am on www.google.com');
```

**Comment by pavelfeldman** [comment]
Your script works fine for me locally. If you can share a self-contained example with your exact page and scenario, that would help.

**Comment by canopy-js-user** [comment]
@pavelfeldman looks like my code was navigating to http://google.com, not https://google.com, so changing that fixed the problem. Thanks so much for your help!
