### ISSUE TITLE
[BUG] iFrame bug

### ISSUE THREAD

**Issue by whitedemon133** [microsoft/playwright#19613]
**Context:**
- Playwright Version: 1.74.2
- Operating System: Windows 11
- Node.js version: None
- Browser: Chromium

**Code Snippet**

```typescript
import { test, expect } from '@playwright/test';

test('weebly-teacher-forgot-password', async ({ page, context }) => {
  
  const delay = ms => new Promise(resolve => setTimeout(resolve, ms));

  // Go to https://www.getclasshive.com/signin.html
  await page.goto('https://www.getclasshive.com/signin.html');

  await page.frameLocator('[id="\\32 15177238592853876"] iframe').locator('#classhiveBody > app-root > div > div.content > app-login > div > div > div > div > form > div.row > div.six.columns.u-align-right > a').click();
  
  await delay(15000);

});
```

**Describe the bug**

Whenever I use script test or codegen it won't click anything and the content of the iframe moves up and down, and also the codegen doesn't create codes whenever I click.

here's the video:

https://user-images.githubusercontent.com/85241077/208821341-c2dbaffe-87d3-4f5f-8c1d-05809ed705f4.mp4

**Comment by pavelfeldman** [comment]
I can repro with `npx playwright codegen https://www.getclasshive.com/signin.html`

**Comment by dgozman** [comment]
I can repro with Playwright v1.26-v1.29, did not try earlier versions. Most likely, the issue is related to `padding-top: 50px` on the `iframe` element, which mistakenly leads to Playwright performing hit test at the wrong location and complaining about "password input intercepts pointer events for the email input".
