### ISSUE TITLE
[Question] Is there a optimal way to click or tap on element depends on hasTouch attribute?

### ISSUE THREAD

**Issue by yurii-sav** [microsoft/playwright#19624]
Hi. I am writing project with next requirements
- one test should be run on any viewport type. (both desktop and mobile devices) 
- test should behave as much as possible closer to real user behavior

This means, that on some project configuration where it's supposed to be a desktop, I need to `click()`  and on some (there `hasTouch` is enabled) I need to interact by `tap()` on the same element.

It forces me to write something like code below
```
// in base.pageObject.ts class
async clickOrTap(locator: Locator): Promise<void> {
    if (this.projectConfig.isMobile) {
      await locator.tap()
    } else {
      await locator.click()
    }
  }
```
and in the method where I actually click or tap on the same element
```
// in homepage.pageObject.ts
 public async clickLoginIcon(): Promise<void> {
    await this.clickOrTap(this.getLoginButton)
 }
```

In my opition there should be some feature from Playwright, for example method `interact()` where depends on the config Playwright clicks or tap on the element, but not sure that there is a big demand in it and possibility to implement. Maybe I am wrong and this behavior can be applied in some other way, by overriding Playwright methods or... please suggest your option. Thanks in advance for any suggestions.

**Comment by pavelfeldman** [comment]
You should use page.click() unconditionally.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by cp-michael-schoormann** [comment]
> You should use page.click() unconditionally.

Hello @pavelfeldman ,

can you explain why i should use .click() unconditionally on mobile devices? and not .tap()?

I also have existing desktop tests, which now should run on mobile and i was thinking that i have to build a check to run tap or click.
