### ISSUE TITLE
[BUG] Mobile Devices don't behave properly

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19637]
I don't know if it's specific scale settings on some of the devices haven't had time to debug, but it breaks reactive sites at least ours. 

When I used devices like Galaxy Note 2, iPhones there is a lot of visual issues, if i set viewport manually and not use a device everything behaves correctly. 

When using the emulators inside chrome dev tools everything behaves correctly also. 

Maybe someone wants to take a look at the devices and their settings, or deprecate them.  

I am available to screen share if someone needs to repro, but seems like they have a various issues.

**Comment by pavelfeldman** [comment]
We need exact steps to reproduce the issue along with your expectations and ith the description of the actual behavior. Should include version of the project, OS, code to run.

**Comment by gselsidi** [comment]
i think it's better we just stick to our routine of closing and ignoring bugs
