### ISSUE TITLE
[Question] I am not able to install @playwright/jest-screenshot package from npm as I wanted to extend toHaveScreenshot matcher so needed to import it first

### ISSUE THREAD

**Issue by Jamesj001** [microsoft/playwright#19635]
I want to import "toHaveScreenshot" matcher from @playwright/jest-screenshot as I wanted to extend it but not able to do so
Does the name of playwright/jest-screenshot package has been changed ?

**Comment by pavelfeldman** [comment]
You don't need extra packages to use that function.

**Comment by Jamesj001** [comment]
but I am not able to extend that matcher

**Comment by pavelfeldman** [comment]
There already is toHaveScreenshot in Playwright, so you can't do that.

**Comment by Jamesj001** [comment]
So how may I achieve this : 
_Basically I want to perform some task every time this toHaveScreenshot is being triggered from any test I want to console the snapshot name being referenced_

**Comment by pavelfeldman** [comment]
There is no way to achieve it other than wrapping toHaveScreenshot into your own function that would be printing the name. Basically what you want is 'I want Node.js to console.log the file name every time I call fs.writeFileSync'.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
