### ISSUE TITLE
[Question] Why playwright not stable when using multi workers

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright#19647]
playwright version: 1.27.0
environment: windows

Hi, we are trying to use playwright instead of selenium in our team, but currently, we found something that needs your help.
The playwright's tips are much more stable when using single workers or multi-workers in our local machine, but when applying to pipelines
eg: Running 15 tests using 3 workers
Slow test file: [Google Chrome] › Daily\MobileQuestionSequence.spec.ts (5m)
  Slow test file: [Google Chrome] › Daily\MobileQuestion.spec.ts (4m)
  Slow test file: [Google Chrome] › Daily\Quiz.spec.ts (2m)
  Slow test file: [Google Chrome] › Daily\QuestionNeo.spec.ts (1m)
  Slow test file: [Google Chrome] › Daily\SharingNeo.spec.ts (46s)
  Consider splitting slow test files to speed up parallel execution

  1 failed
    [Google Chrome] › Daily\Quiz.spec.ts:11:5 › question › mobilequizzes ===========================
  1 flaky
    [Google Chrome] › Daily\Intelligence.spec.ts:14:5 › Intelligence › ThemeSuggestionNeoTest ======
  13 passed (6m)

The failed and flaky cases are very stable in local machine, I am wondering why the cases especially with more than 1 worker are not stable, Could you please give some advise ? Thanks

**Comment by pavelfeldman** [comment]
Stability is not a function of parallelization, unless you stress the system to the extent of everything timing out. 3 workers is not much, assuming your machine has 6 logical cores or more. I'm running my tests on 28 workers (my machine has 56 cores w/ hyperthreading).

Running tests in parallel surfaces existing flakiness in the tests. You can try running the tests that fail with --repeat-each=100 command line flag to see why they fail. Once you fix them, they'll be running like clockwork.

**Comment by lxy2222** [comment]
Thanks @pavelfeldman, actually we tried using 10 workers, but the test failed easily, so I reduced the workers count to 3
My concern is that 
We have working on fixing the test for quite a long time. the weird thing is that we fix it and run in locally / run with 1 worker, it was perfect, but while we want running parallelly, it failed in different place, that's my point is there any clue for the failure ?

**Comment by JonahKK** [comment]
If your tests only fail when there are multiple workers then they are probably not isolated enough. One test affects the state of another.

**Comment by pavelfeldman** [comment]
I don't think this is anything we can act upon. I would collect the traces for failures and would look at the race conditions or shared data usage that caused them.
