### ISSUE TITLE
[Feature] .locator should also take in Locator type

### ISSUE THREAD

**Issue by gselsidi** [microsoft/playwright#19642]
so chaining elements such as .byRole, .filter, .locator 
.locator should take in an actual Locator as to work better with page object model as opposed to just string

it comes in handy when chaining to find elements in a table, or in dropdown that might have icons next to each name, and that icon you've set as an Locator in your POM file.

`await dashboardPage.columnHeaders
    .filter({ hasText: "Name/UID" })
    .locator(dashboardPage.downArrowTableSortIcon);`

**Comment by dgozman** [comment]
Chaining locators is now possible with `Locator.locator()` method. Check out [this guide](https://playwright.dev/docs/locators#chaining-locators).

**Comment by gselsidi** [comment]
@dgozman thanks for this! I looked at the guide didn’t see any examples or is it not updated yet?

If so can you provide an example.

**Comment by dgozman** [comment]
The second snippet in the guide has an example of locator chaining:

```js
const saveButton = page.getByRole('button', { name: 'Save' });
// ...
const dialog = page.getByTestId('settings-dialog');
await dialog.locator(saveButton).click();
```
