### ISSUE TITLE
[BUG] Found wrong documentation 

### ISSUE THREAD

**Issue by 6unpk** [microsoft/playwright#19651]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Describe the bug**

Hello. I found a duplicate code for `WaitForResponse`. It explains about `WaitForRequest` not `WaitForReseponse`. 
<img width="1009" alt="스크린샷 2022-12-22 오후 4 23 06" src="https://user-images.githubusercontent.com/26023297/209079790-fc6bafba-14d7-4208-a507-8250780e6f88.png">
https://playwright.dev/docs/api/class-page#page-wait-for-response

**Comment by dgozman** [comment]
Fixed by #19701.

**Comment by FlandreDaisuki** [comment]
The API description is wrong in https://playwright.dev/docs/api/class-page#page-wait-for-response now.

When can we get the correct information from https://playwright.dev ?
