### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by HuckleberryCarignan** [microsoft/playwright#19656]
**Context:**
- Playwright Version: @playwrite/test 1.27.1
- Operating System: Mac
- Node.js version: v16.17.0
- Browser:  Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
test code:
.
.
.
```
await page.frameLocator('internal:attr=[title="LMAuthoritiesButtonOppty"i]').getByRole('combobox', { name: 'NavigationDD' }).selectOption('Saved Project');
await page.frameLocator('internal:attr=[title="LMAuthoritiesButtonOppty"i]').locator('internal:attr=[name="j_id0:formId:NavigationGo"]').click()
```

playwright.config.ts
```
// playwright.config.ts
import { chromium, PlaywrightTestConfig } from '@playwright/test';
const config: PlaywrightTestConfig = {
  timeout: 6000000, // Timeout is shared between all tests.
  retries: 3,
  //workers: 3,
  reporter: 'line',
  use: {
    browserName: `chromium`,
    headless: false,
    viewport: { width: 1920, height: 1200 },
    actionTimeout: 600000,
    ignoreHTTPSErrors: true,
    video: `off`,
    screenshot: `off`,
    launchOptions: {
      ignoreDefaultArgs: ['--disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies,LazyFrameLoading']
    }
  },
  projects: [
    {
      name: 'Smoke',
      testMatch: /.*smoke.spec.ts/,
      retries: 0,
    },
    {
      name: 'Default',
      testIgnore: /.*smoke.spec.ts/,
      retries: 0,
    },
  ],
};
export default config
```;

The click

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
  await page.setContent(`
    <div>
      …
    </div>
  `);
  // Alternatively, if you are testing a public application, include the URL:
  // await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**
When run manually, the end user is selecting a redirect link in Salesforce and being redirected to a different app in the same tab, so the so the original URL had "salesforce.com" in it and the new one does not.  When run in headed mode, and when playwright select the redirect link, a new tab is opened and the new tab does not conned to anything (I'm assuming due to permissions).

Is there a setting that stops redirect from opening up a new tab?

**Comment by Huckleberry-Carignan** [comment]
I'm trying to edit the above and I can't, so I hope to redirect your eyeballs here.  After investigating, I need to change the issue.   It has to do with re-direct, but not anything to do with Salesforce or the new tab.   After discussing with the developers, the new tab is supposed to occur and the redirect fails in this new tab with another action.

So, the app I'm testing with playwright has a new tab with a redirect.   Manually & Locally, this works fine.  When running Locally with Playwright, there is a complaint to change the Safari settings (even though I'm on Chrome) for the redirect.   Is there some Playwright setting that controls redirect?

So I see two issues here:
(1) The minor is that the complaint is mentioned for Safari when I'm running Chrome
(2) The major is the redirect is being allowed, even though when done manually it works
It should be noted, I even tried to start running on the Playwright, then interact with the Playwright controlled browser with manual mouse clicks (i.e. playwright paused and I continued the test case with my touchpad) and it still had the same issue.

**Comment by pavelfeldman** [comment]
- Can you show us the complaint from Safari (screenshot?)
- We need to be able to reproduce the issue in order to address it, is there anything public we can access?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
