### ISSUE TITLE
[BUG] Firefox ignore self-signed ssl and fails to run tests

### ISSUE THREAD

**Issue by AurelienKun** [microsoft/playwright#19653]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Windows
- Node.js version: v16.13.0
- Browser: Firefox
- Extra: Organization using self-signed ssl on their devices

**Describe the bug**
After a fresh install of Playwright I wanted to run the default generated test with `npx playwright test`. The test passes for Chromium and Webkit but went wrong with Firefox. It fails immediately on the instruction `await page.goto('https://playwright.dev/');`. I looked around and found a similar issue on this page : 
https://stackoverflow.com/questions/73039101/unable-to-navigate-to-any-website-in-firefox-using-playwright
So I tried to ignore ssl-issue by adding the following to the test example:
```
test.use({
  ignoreHTTPSErrors: true
});
```
With this piece of code, everything works on Firefox !

Also I checked if my npm was properly configured with the following command `npm config get ca` and I get the path to the pem certificate of my enterprise. Since Chrome and Webkit does not have the ssl problem, it might be an issue on Firefox integration with Playwright.

**Comment by pavelfeldman** [comment]
It looks like Firefox does not trust playwright.dev certificate when running on your host system. Please let us know if you can successfully open this page on regular Firefox installation.

**Comment by AurelienKun** [comment]
Yes I can see the page on my installed version of Firefox.
I'm gonna be in vacationI'll be back after the 3rd of January

**Comment by pavelfeldman** [comment]
When you are back, could you file a new issue, link this one and provide us with the exact script and error message? I need to keep all the non-actionable issues closed...

**Comment by AurelienKun** [comment]
@pavelfeldman  I don't understand why you close this issue asking me to create a clone of what I already wrote. 

There is no code to provide since it is the sample code included in the project that fails and I did explain the extra code I added to the sample code to make it work. 

The test fails and there is no special message displayed, just a red cross on the summary for the test run on firefox...

**Comment by pavelfeldman** [comment]
- Why I closed: we get 10-20 bugs a day and when reporters say "we need to step away for a week" during triaging, our process falls apart, we need them active while triaging.

- There always is an error message, if there is no error message - there is no error.
