### ISSUE TITLE
[BUG] More tests are reported than were actually run.

### ISSUE THREAD

**Issue by qakos** [microsoft/playwright#19666]
**Context:**
- Playwright Version: 1.29.0, 1.29.1
- Operating System: Windows, Linux, Mac
- Node.js version: 18.12.1
- Browser: Chromium, Firefox, WebKit
- Extra: Allure

**Describe the bug**

More tests are reported than were actually run. For example, 36 tests were run, of which 35 were successful, and only 1
  after restarting. The Allure report included 37 tests, of which 36 were successful and 1 failed. Before the update, in the same situation, the report showed 36 successfully passed tests.
![22-12-22_01](https://user-images.githubusercontent.com/93794669/209222886-2b1904b5-dbd3-4edd-97a9-14933c5eaddb.jpg)
![22-12-22_02](https://user-images.githubusercontent.com/93794669/209222892-168afa59-5ff4-4952-8f83-e47d4db2e4ce.jpg)

**Comment by pavelfeldman** [comment]
Please file this against the allure repository!
