### ISSUE TITLE
[Question] Is there a way to mark some specific tests as conflicted (not to run them in parallel)?

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#19669]
Example: There are tests for working with _business objects_(**BO**) and there are tests for the '_recently updated_ **BO**' panel. They are placed in different test files, but when they run at the same time, tests for working with some **BO** can break the test for checking the '_recently updated_ **BO**' panel (**BO** from a different test might be present there instead of expected).

I would not put them in the same test file as they require different prerequisites, but I would mark the 'recently updated **BO**' test not to be in parallel with other tests for the **BO**, which can appear in this panel.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/14084
