### ISSUE TITLE
[BUG] Route active while changing page causes some requests to hang

### ISSUE THREAD

**Issue by domrin123** [microsoft/playwright#19678]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Windows
- Node.js version: 16.16
- Browser: Chrome

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.route(
    "https://playwright.dev/whatever",
    async (route) => {
      const json = {
        test: true
      };
      await route.fulfill({ json });
    }
  );

  await page.goto('https://www.bbc.co.uk/');
  await page.getByTestId('header-content').getByRole('link', { name: 'News' }).click();
});
```

**Description**

When running the above test, going to "https://www.bbc.co.uk/", but  when the "News" button is clicked and we are taken to "https://www.bbc.co.uk/news", the page is only partially loaded, with multiple requests timing out. This does not happen when the route is not registered or if it is unregistered on page load. 

Is this expected behaviour? I would expect the route to be happily registered and causing no effect on the test in this case. 

Thanks

**Comment by pavelfeldman** [comment]
I modified the test (`header-content` test id is not a thing on the version of the site i get served). The test above passed as expected for me. Note that after your click is done, you don't do anything, so the test is finished. Router is disengaged and network events can be aborted.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
