### ISSUE TITLE
[BUG] [Ubuntu] [WebKit - Safari - Headless] Click misses target due to continuous unnecessary scrolling events.

### ISSUE THREAD

**Issue by loxinchi** [microsoft/playwright#19682]
**Context:**
- Playwright Version: `1.28.1`
- Operating System: 

```javascript
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

- Node.js version: `v14.18.3 `, `npm v8.1.4`
- Browser: `WebKit - Safari - headless`
- Extra:  This issue can be reproduced in normal ubuntu docker and also playwright ubuntu docker `playwright:v1.29.1-focal `

**Test Repository**
[Link](https://github.com/loxinchi/Safari-issue-playwright)

**Describe the bug**
Click misses target due to continuous unnecessary scrolling events.

**Comment by pavelfeldman** [comment]
Your link points to 404 for me. Private repo?

**Comment by loxinchi** [comment]
> Your link points to 404 for me. Private repo?

@pavelfeldman Changed to public now. Sorry about that, please help to check, thanks.

**Comment by aslushnikov** [comment]
@loxinchi I actually just tried on tip-of-tree playwright and it works for me. Could you please try running with `playwright@test@next` ?

**Comment by loxinchi** [comment]
@aslushnikov Verified with `"@playwright/test": "^1.31.0-alpha-feb-6-2023"` in the same `Ubuntu 20.04.5 LTS`, it worked well. Thank you.
