### ISSUE TITLE
[BUG]Fails when to run all tests as a whole

### ISSUE THREAD

**Issue by srisposi** [microsoft/playwright#19688]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Linux
- Node.js version: 16.17.0
- Browser: All
- Extra: work with typescript

**Code Snippet**

In the example I upload one of the tests of all. as you can see, they are simple, the other tests have a flow similar to the one shown

```
test("test flow Pillars", async ({ page }) => {
  await page.video();
  await page.goto(process.env.LOCALURL, {
    waitUntil: "networkidle",
  });

  await page.getByRole("button", { name: "Podcasts" }).click();
  await expect(page).toHaveURL(/podcasts/);

  const Pillar = page.getByTestId("idTestPillar3");

  await Pillar.click();

  const nameEpisode = page.getByRole("link", {
    name: "Name Podcasts",
  });

  await nameEpisode.click();

  await page.getByTestId("idPlayEpisodeDetail").locator("audio");
  await page.waitForTimeout(3000);
  await page.getByTestId("idPlayEpisodeDetail").locator("audio");
}); 
```

**Describe the bug**

Hello, I want to report the following inconvenience. I have a playright project to perform end-to-end testing of my application. When I run the tests individually, I have no problems, but when I try to run the folder with all the tests, most of them fail. Does anyone have any idea what could be going on? Maybe this has something to do with problem 14686? Thanks so much!

**Comment by pavelfeldman** [comment]
Following are red flags that prevent tests from running reliably. You should work on the quality of your tests!

- remove page.video call
- remove page.waitForTimeout
- never use networkidle
- last two calls that await locator are no-op, they do nothing.
