### ISSUE TITLE
[Question] Should I close context fixture if I use a custom one?

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#19680]
1. Should I close context fixture if I use a custom one?
   1.1 And are there pros and cons of closing context?
2. The same question is about the tests where browser fixture is used and context is created manually.
   2.1 Should this context be closed?

Maybe there is an article about browser, context, page lifecycle, and their reuse between tests?

```
export const test = base.extend<{user1Context: BrowserContext
}>({
  user1Context: async ({ browser }, use) => {
    const user1Context = await browser.newContext({ storageState: 'states/user1Logged.json' });
    await use(user1Context);
    // ??? await user1Context.close();
  },
});
```
_Tags:
context.close()
page.close()_

**Comment by pavelfeldman** [comment]
In this case yes, you want to discard it after your test is finished. I assume you are doing a multi-user test, otherwise

```js
test.use({ storageState: 'states/user1Logged.json' })
```

would do a better job.

**Comment by denkorz** [comment]
Not really multi user test. This should be default user for a lot of tests. For not to write `{ storageState: 'states/user1Logged.json' }` in each test file, it might be a good idea to create a modified context fixture. 

This one in a separate file.
```
export const test = base.extend<{user1Context: BrowserContext
}>({
  user1Context: async ({ browser }, use) => {
    const user1Context = await browser.newContext({ storageState: 'states/user1Logged.json' });
    await use(user1Context);
    // ??? await user1Context.close();
  },
});
```

And each test file just uses this context
```
test('Descriptive and perfect test name', async ({ user1Context }) => {
  const page = await user1Context.newPage();
  const somePage = new SomePage(page);
  const someApiHelper = new SomeApiHelper(user1Context);
  await somePage.PerformSomeAction();
  expect(await someApiHelper.getActionResult(), 'That is bad').toBe('Correct result');
});
```

**Comment by pavelfeldman** [comment]
If this is not a multi-user test, you should keep it simple and override storageState, not context:

```js
export const user1Test = base.extend({
  storageState: ({}, use) => use(require.resolve('../states/user1Logged.json')),
});
```
