### ISSUE TITLE
[BUG] Unable to use any get_by locator for an input element

### ISSUE THREAD

**Issue by soumya-kar** [microsoft/playwright#19689]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.28
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Python
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chrome
- Extra: [any specific details about your environment]
Hi,

I am trying to automate one website (https://the-internet.herokuapp.com/login) using Playwright and Python
I was trying to use a get_by locator for username and password field. 
![Capture](https://user-images.githubusercontent.com/57455260/209434283-de24808d-224a-420d-baf1-fc45384a7795.PNG)

I need to get a locator for input field. For that I was trying to use like this
page.get_by_role("input", name="username")
But the the above one is not working. 
When I tried with codegen, it gave me page.get_by_label("Username") for username field.
I need locator for username input field, but it is giving locator for the label which is not correct.
Although above code works, but it is not what I want.

I feel like playwright needs to work on it and provide correct get_by locator for input field

**Comment by pavelfeldman** [comment]
`page.get_by_label("Username")` is the best locatir for that input, it gets input by label.
