### ISSUE TITLE
[Feature] Add dedicated clipboard API

### ISSUE THREAD

**Issue by telmondyoel** [microsoft/playwright#19683]
After scouring the documentation there doesn't seem to be a convenient way to access the clipboard in Playwright .NET.

### Would it be possible to add a dedicated clipboard API?
The current solution is to use `EvaluateAsync()` but it's simply not convenient in any way, shape or form.

### An example of how the APIs could look like:
`string clipboardContent = await Page.Clipboard.ReadAsync()` -> would possibly return either a nullable string or an empty string if clilpboard not yet used
`await Page.Clipboard.WriteAsync("I am copied text!")` -> possibly with overloads for byte arrays, spans, etc...

I'll leave the other implementations to you folks...
Thanks in advance!

**Comment by ShaharM7** [comment]
I would be happy, our team also lacks the above feature :)
