### ISSUE TITLE
[Question]: Unable to load more than one extension

### ISSUE THREAD

**Issue by superalix** [microsoft/playwright#19684]
### Your question

Nothing happened when try to load 2 extensions (ver. 1.29.0):

USER_DIR = "D:/User Data/1"
EXT_1 = "D:/python/User Data/extensions/1"
EXT_2 = "D:/python/User Data/extensions/2"
ARGS = [
    **"--disable-extensions-except={}".format(EXT_2,EXT_1),
    "--load-extension={}".format(EXT_2,EXT_1),**
]

playwright = sync_playwright().start()
**context = playwright.chromium.launch_persistent_context(USER_DIR, headless=False, args=ARGS, devtools=False, channel='chrome', locale=locale, timezone_id=timezone)**
page = context.wait_for_event("page")

**Comment by pavelfeldman** [comment]
You can enable logging via setting environment variable `DEBUG=pw:browser*` to see why your command like is malformed.

**Comment by superalix** [comment]
ARGS = [
    f"--disable-extensions-except={EXT_1_DIR},{EXT_2_DIR}",
    f"--load-extension={EXT_1_DIR},{EXT_2_DIR}",
]

**Comment by superalix** [comment]
Solved

**Comment by superalix** [comment]
Solved
ARGS = [
    **f"--disable-extensions-except={EXT_1_DIR},{EXT_2_DIR}",
    f"--load-extension={EXT_1_DIR},{EXT_2_DIR}",**
]

**Comment by superalix** [comment]
Solved
ARGS = [
**f"--disable-extensions-except={EXT_1_DIR},{EXT_2_DIR}",
f"--load-extension={EXT_1_DIR},{EXT_2_DIR}",**
]
