### ISSUE TITLE
[Feature] defineConfig helper for playwright config file

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#19694]
Can we have a `defineConfig` helper? A lot of libraries _[(like vite)](https://vitejs.dev/config/#config-intellisense)_ have this and seems to be the standard. It's a little cleaner and provides intellisense without the need for jsdoc annotations when js is used:

```ts
type PlaywrightTestConfigProps = {
    mode: 'CI';
}

function defineConfig(config: PlaywrightTestConfig): PlaywrightTestConfig;
function defineConfig((props: PlaywrightTestConfigProps) => PlaywrightTestConfig): PlaywrightTestConfig;
```

```typescript
// playwright.config.ts
import { devices, defineConfig } from '@playwright/experimental-ct-solid';

export default defineConfig({
  retries: process.env.CI ? 2 : 0,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

Conditional Config:

```typescript
// playwright.config.ts
import { devices, defineConfig } from '@playwright/experimental-ct-solid';

export default defineConfig(({ mode }) => ({
  retries: mode === 'CI' ? 2 : 0,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
}));
```

Old way can still exist, but will be good to modify the playwright-create project if this gets accepted:

```typescript
// playwright.config.ts
import { type PlaywrightTestConfig, devices } from '@playwright/experimental-ct-solid';

const config: PlaywrightTestConfig = {
  retries: process.env.CI ? 2 : 0,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
};

export default config;
```

**Comment by dgozman** [comment]
@sand4rt How is the conditional config going to be used? Do you have an example in mind? Who is passing the arguments to the function? What could be there?

Apart from conditionals, this seems to only save a single line with the type declaration, in the config file that is already generated by `create-playwright`, so doesn't look worthwhile.

**Comment by sand4rt** [comment]
Feature request was mainly about the first `defineConfig`, but it could retrieve the flag if it's running in CI or not _(aka `process.env.CI`)_. Any config option can be injected into it in the future if needed. 

```ts
// Simple usage
export default defineConfig(({ mode }) => ({
  retries: mode === 'CI' ? 2 : 0,
}));

// Advanced usage
export default defineConfig(({ mode }) => {
  // Specify all your config for CI mode
  if (mode === 'CI') {
      return { retries: 2 }
  }
  // Specify all your config for headed mode
  return  { retries: 2 }
});
```

The `defineConfig` does nothing special would be a really small effort to add it:

```ts
// first defineConfig
export function defineConfig(options: PlaywrightTestConfig): PlaywrightTestConfig {
  return options;
}

// conditional config
export function defineConfig(callback: (options: PlaywrightTestConfigProps) => PlaywrightTestConfig): PlaywrightTestConfig {
  return callback({ mode: process.env.CI ? 'CI' : 'HEADED', /** can inject any config option here */ });
}
```


Maybe I'm nitpicking here, but have you considered these arguments?: 
1.  Bunch of other tools have this like: Vitest, Cypress, Vite, Rolup, Vue CLI, tsup and Nuxt 3. Hopefully more coming which keeps things consistent.
2. Having a more consistent way of defining configuration in `ts` and `js`
3. `defineConfig` is more expressive (i think especially for younger devs) than just exporting an object
4. Not exposing new technology _(JSDOC)_ to define types
5. Less code. Especially the `js` version:

```js
// @ts-check

/**
 * @type{import('@playwright/test').PlaywrightTestConfig}
 */
const config = {
  process.env.CI ? 2 : 0
};

module.exports = config;
```

vs

```js
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  process.env.CI ? 2 : 0
});
```

**Comment by dgozman** [comment]
@sand4rt Thank you for the input, we'll consider this.

**Comment by sand4rt** [comment]
Thanks. May i ask if this being discussed internally or are we collecting votes? BTW. i'm willing to make a PR for it if accepted.

**Comment by pavelfeldman** [comment]
> BTW. i'm willing to make a PR for it if accepted.

I wish I saw this before making the PR!
