### ISSUE TITLE
How to allow downloading files from the browser?

### ISSUE THREAD

**Issue by sspermer** [microsoft/playwright#19698]
Hello brothers!
I have a question, I use playwright as an anti-detect browser, but I can't download any file, can you please tell me how can I allow files to be downloaded from the browser created with playwright?

My code:
const { chromium } = require('playwright-extra')
const stealth = require('puppeteer-extra-plugin-stealth')()

chromium.use(stealth)
const userDataDir = "E:/playwright/"

chromium.launchPersistentContext(userDataDir, { acceptDownloads: true, downloadsPath: "E:/playwright/", headless: false, args: [ 
"--allow-profiles-outside-user-dir",
"--disable-features=UserAgentClientHint", 
"--enable-aggressive-domstorage-flushing", 
"--profiling-flush= 10", 
"--restore-last-session", 
"--disable-popup-blocking",
"--disable-webgl",
"--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
],
userAgent: "user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36",
proxy: {
server: "********************",
username: "************",
password: "************"}
}).then(async browser => {
  const page = await browser.newPage({acceptDownloads: true})
  console.log('Testing the stealth plugin..')
  await page.goto('https://pixelscan.net/')
 
  
})

**Comment by pavelfeldman** [comment]
This question falls outside of the scope for Playwright.

**Comment by sspermer** [comment]
> This question falls outside of the scope for Playwright.

that is, in the playwright it is impossible to allow downloading files in manual mode?
