### ISSUE TITLE
[Question] performance issue, high cpu utilization

### ISSUE THREAD

**Issue by yusong0926** [microsoft/playwright#19696]
I am trying to run each playwright test in a docker container. But it seems each playwright test is taking too much resource. 
For a 4core8G machine, the cpu utilization is  around 90% out of 100 for 4 concurrent playwright test within 4 containers.
I am just wondering if this high resource utilization make sense or not? 
is there any way I can lower the resource utilization to achieve higher concurrency?

base script as below:

const { test, expect } = require('@playwright/test');
const { chromium, webkit, firefox } = require('playwright');
test("test", async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext({
     recordHar: { path: 'tests/example.har'}
  });
  const page = await context.newPage(); 
  await page.goto('https://www.google.com');
  await page.close();
  await context.close();
  await browser.close();
});

**Comment by pavelfeldman** [comment]
You seem to be pushing it too hard, also unclear why you are using separate containers and browsers while you could have used 4 browser contexts on one browser in one container.

**Comment by yusong0926** [comment]
> You seem to be pushing it too hard, also unclear why you are using separate containers and browsers while you could have used 4 browser contexts on one browser in one container.

because my application is written in Golang, so I guess the only way to initiate the test is to use container to wrap it.
I also tested the performance without container by "npx playwright test" with 4 workers running 4 test each time. I got similar result.

**Comment by maxrexfax** [comment]
![ksnip_20231226-171413](https://github.com/microsoft/playwright/assets/27776358/c7c7aa16-8853-4e5f-b366-7de8c07ecd4c)
![ksnip_20231226-171353](https://github.com/microsoft/playwright/assets/27776358/97c73446-649e-4d63-95c8-fa46a00d5469)
Every start of playwright tests causes 100% CPU load. Is it fault of some media on target site or something else?

**Comment by erhathaway** [comment]
@yusong0926 @maxrexfax Did either of you ever figure out how to decrease CPU usage? I'm seeing something similar across different versions of playwright and reusing the same browser.

**Comment by akshayfluxon** [comment]
I am also experiencing the same. The tests works 1/5 time on repeated retries and CPU spikes upto 99% during the execution.

**Comment by boylec** [comment]
same...
macos intel
chromium

**Comment by fiftin** [comment]
Macbook M1, same. Crazy CPU usage.

**Comment by fiftin** [comment]
@pavelfeldman what reason to close the issue? Was it solved?

It is not possible to test app on the same machine, because Playwright uses 100% CPU.

**Comment by fiftin** [comment]
I found the reason: `video: 'retain-on-failure'`
