### ISSUE TITLE
[BUG] Stripe checkout page submission is not working

### ISSUE THREAD

**Issue by krasdav** [microsoft/playwright#19709]
**Context:**
- Playwright Version: Version 1.23.4
- Operating System: Windows/Linux]
- Node.js version: v19.1.0
- Browser:  Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
    await page.locator('[placeholder="\\31 234 1234 1234 1234"]').click();
    await page.locator('[placeholder="\\31 234 1234 1234 1234"]').fill('4242 4242 4242 42422');

    await page.locator('[placeholder="MM \\/ YY"]').click();
    await page.locator('[placeholder="MM \\/ YY"]').fill('10 / 26');

    await page.locator('[placeholder="CVC"]').click();
    await page.locator('[placeholder="CVC"]').fill('123');

    await page.locator('input[name="billingName"]').click();
[log-local.txt](https://github.com/microsoft/playwright/files/10303766/log-local.txt)

    await page.locator('input[name="billingName"]').fill('123');

    await page.locator('[data-testid="hosted-payment-submit-button"
[log-github.txt](https://github.com/microsoft/playwright/files/10303765/log-github.txt)
]').click();

    await page.waitForURL(/calendar/)
    await expect(page).toHaveURL(/calendar/)
```

**Describe the bug**

I am working on E2E tests using playwright with typescript. Part of the test is going to Stripe checkout page, filling the details and when the button is pressed, this should redirect to another page.

Everything works locally, no issues.

The problem is when i try to run it in Github Actions. Test never get passed the last "hosted-payment-submit-button".

Tried to debug but dont know why is it happening, attaching the logs from local and also from github.

Thank you for any leads, been struggling with it for a long time already.

**Comment by krasdav** [comment]
[log-local.txt](https://github.com/microsoft/playwright/files/10303770/log-local.txt)
[log-github.txt](https://github.com/microsoft/playwright/files/10303771/log-github.txt)

**Comment by dgozman** [comment]
@krasdav I'd recommend to [record a trace](https://playwright.dev/docs/trace-viewer-intro) on Github Actions and see what's going on. Let me know if that helps.

**Comment by krasdav** [comment]
@dgozman Yea it did help, nothing really complicated, just acted different in the github env. Thank you

**Comment by dev-xo** [comment]
Hello @krasdav ! I'm on a similar issue with Github Actions and Stripe Checkout page.

Test passes locally, but not on CI. And not sure why.
In my case the test should redirect to Stripe Checkout forms, not complete them yet.

I have no clue why test passes locally, but not on CI, and as you said seems to be something about Github envs?
Thanks!

**Comment by krasdav** [comment]
Hi, i checked your issue and it doesnt seem to be the same as mine. My issue was contected to the timezone, different timezone in my local browser vs on github, so was missing a check box ticked for that specific timezone. Anyway... the only way how i was able to figure it out, was trace and saving the artifact on github.

**Comment by dev-xo** [comment]
All right @krasdav. Thanks for the answer!

**Comment by Mati365** [comment]
In my case clicking directly into `hosted-payment-submit-button` was not working but clicking in any random div inside that button so.

**Comment by natterstefan** [comment]
Hi everybody,

I've been able to open the Stripe checkout page and hit the "Pay" button. Still, the Checkout page opens a new browser outside of Playwright instead of redirecting/opening the page I expect (similar to the original post above mentioning `await page.waitForURL(/calendar/)`).

I get the following error:

```
page.waitForURL: net::ERR_ABORTED; maybe frame was detached?
=========================== logs ===========================
waiting for navigation to "/checkout-in-progress" until "load"
============================================================
```

I also do not see a screen after the "Pay" button on the Stripe Checkout page went green in the Playwright UI (trace etc.).

As you all seem to have solved this or handled this flow, this could be the right place to ask for help. :)

Thanks - and sorry for using a closed issue for this.

**Comment by vineethpeddi-sureify** [comment]
Hii natterstefan,
Even I am facing the same issue. If you know how to resolve could you please share it here?
