### ISSUE TITLE
[BUG]'page.goto: SSL_ERROR_UNKNOWN' error from global-setup.ts file for all URLs in globalSetup.ts.

### ISSUE THREAD

**Issue by khanjunaid53** [microsoft/playwright#19704]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Mac
- Node.js version: v16.14.2
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript

Code snippet:
import { chromium, FullConfig,Page,BrowserContext,firefox } from '@playwright/test';
`
async function globalSetup(config: FullConfig) {
    const browser = await firefox.launch({
        headless:false
      });
      const context = await browser.newContext({
        ignoreHTTPSErrors:true     
      });
      const page = await context.newPage();

    try {
        await context.tracing.start({ screenshots: true, snapshots: true });
        await page.goto('https://google.com');
        await context.close()
        await browser.close()
        console.log('SFDC Login Completed.')
        await context.tracing.stop({
            path: './test-results/setup-trace.zip',
        })
    } catch (error) {
        await context.tracing.stop({
            path: './test-results/failed-setup-trace.zip',
        });
        await page.close();
        throw error;
    }
  }

 export default globalSetup;
`
```

**'page.goto: SSL_ERROR_UNKNOWN' error from global-setup.ts file for all URLs even on navigating to 'https://google.com'**

The problem seems to be present only with global-setup.ts file. Navigating to test file working as expected from test files.

**Comment by khanjunaid53** [comment]
More logs:
  
pw:api => browserType.launch started +0ms
  pw:browser <launching> /Users/XXXX/Library/Caches/ms-playwright/firefox-1369/firefox/Nightly.app/Contents/MacOS/firefox -no-remote -wait-for-browser -foreground -profile /var/folders/_m/crdg3x2d0457ss8jt49pc2nc0000gn/T/playwright_firefoxdev_profile-n4Zoji -juggler-pipe -silent +0ms
  pw:browser <launched> pid=1385 +3ms
  pw:browser [pid=1385][out]  +337ms
  pw:browser [pid=1385][out] Juggler listening to the pipe +0ms
  pw:api <= browserType.launch succeeded +381ms
  pw:api => browser.newContext started +1ms
  pw:api <= browser.newContext succeeded +24ms
  pw:api => browserContext.newPage started +1ms
  pw:browser [pid=1385][err] UNSUPPORTED (log once): POSSIBLE ISSUE: unit 1 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable +410ms
  pw:browser [pid=1385][out] console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at /var/folders/_m/crdg3x2d0457ss8jt49pc2nc0000gn/T/playwright_firefoxdev_profile-n4Zoji/search.json.mozlz4", (void 0))) +62ms
  pw:api   navigated to "about:blank" +424ms
  pw:api   navigated to "about:blank" +0ms
  pw:api <= browserContext.newPage succeeded +2ms
  pw:api => tracing.start started +0ms
  pw:api <= tracing.start succeeded +26ms
  pw:api => page.goto started +1ms
  pw:api navigating to "https://google.com/", waiting until "load" +6ms
  pw:browser [pid=1385][err] JavaScript error: resource://gre/modules/URIFixup.sys.mjs, line 304: NS_ERROR_FAILURE: Should pass a non-null uri +111ms
  pw:api <= page.goto failed +178ms
  pw:api => tracing.stop started +1ms
  pw:api <= tracing.stop succeeded +14ms
  pw:api => page.close started +1ms
  pw:api <= page.close succeeded +50ms
page.goto: SSL_ERROR_UNKNOWN
=========================== logs ===========================
navigating to "https://google.com/", waiting until "load"

**Comment by dgozman** [comment]
@khanjunaid53 I cannot reproduce the issue with your snippet. Perhaps something's wrong with your network setup? I see you are passing `ignoreHTTPSErrors: true` while navigating to `google.com` - is that just for example purposes? I don't think that `google.com` has any SSL errors. If you could share a full repro with us, we might be able to take a look.

**Comment by aslushnikov** [comment]
@@khanjunaid53 Could you please try the same advice as was mentioned here: https://github.com/microsoft/playwright/issues/19773#issuecomment-1367754730?

**Comment by khanjunaid53** [comment]
Hi Andrey / Dmitry,

Sorry for the late response and thank you for checking the same. On
retesting have confirmed that the above snippet works when proxy configs
are commented out which is not expected as they work perfectly fine when
outside of the 'glbal-setup.ts' file.  In addition the code snipped works
when the proxy part is commented out. Shall be working on providing repo
shortly after removing sensitive information.

const context = await browser.newContext({
ignoreHTTPSErrors:true,
proxy: {
server: 'https://xyz.example.com:3128'
}
});

Error screenshot:
[image: image.png]

Thanks again for your precious time and efforts.

Regards,
Junaid Khan

**Comment by khanjunaid53** [comment]
Hi Max, after further debugging from my end this seems to be an issue with the proxy setup my organisation is using and not playwright. Was able to reproduce the ERROR with a proxy from https://spys.one/en/free-proxy-list/ which too gave SSL error for google.com.

Also had ' ignoreHTTPSErrors:true,' added in **playwright.config.ts** file which explains the difference in behaviour described in earlier comment. 

Issue can be closed if it's working fine with a proper proxy. Thanks again for your time.

Sharing code below incase somebody needs to reproduce the same.

`import { chromium, FullConfig,Page,BrowserContext,firefox } from '@playwright/test';
import {LoginPage} from "../pages/LoginPage"

async function globalSetup(config: FullConfig) {
    console.log('Inside Global setup. Env='+process.env.CENV)
    const browser = await firefox.launch({
        headless:false
      });
      const context = await browser.newContext({
       // ignoreHTTPSErrors:true,
        proxy: {
            server: 'https://210.209.83.22:3128'
          }
      });
      const page = await context.newPage();

    try {
        await context.tracing.start({ screenshots: true, snapshots: true });
        await page.goto('https://google.com');
        let loginPage = new LoginPage(page)
        await loginPage.login(process.env.USERNAME);
        await loginPage.assertSFDCHomeIsOpen();
        await loginPage.saveStorageStateExternal(process.env.USERNAME);
        console.log('SFDC Login Completed.')
        await context.tracing.stop({
            path: './test-results/setup-trace.zip',
        })
        } catch (error) {
            await context.tracing.stop({
                path: './test-results/failed-setup-trace.zip',
            });

        throw error;
        }
        await page.close();
        await context.close()
        await browser.close()
  }
  
  export default globalSetup;
`

<img width="666" alt="image" src="https://user-images.githubusercontent.com/121419016/210617645-c002ba6b-e0a0-4dcf-a79b-00ae28b80162.png">

**Comment by mxschmitt** [comment]
👍
