### ISSUE TITLE
[Question] how to share browser instance with multiple test

### ISSUE THREAD

**Issue by yusong0926** [microsoft/playwright#19706]
trying to run multiple test in parallel. but I want to share the same browser instance with opening multiple browserContext
is there any example for this?

const { test, expect } = require('@playwright/test');
test("test1", async ({browser}) => {
  const context = await browser.newContext({});
  const page = await context.newPage(); 
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
  await browser.close();
});

test("test2", async ({browser}) => {
  const context = await browser.newContext({});
  const page = await context.newPage(); 
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
  await browser.close();
});

**Comment by klepik1990** [comment]
I think you should use test.describe.parallel and then use test.beforeEach inside this test suite

**Comment by pavelfeldman** [comment]
It is best to rely on the built-in parallelism that runs browsers in parallel, it gives the best performance characteristics while keeping things reliable and isolated.

**Comment by yusong0926** [comment]
> It is best to rely on the built-in parallelism that runs browsers in parallel, it gives the best performance characteristics while keeping things reliable and isolated.

Is there any performance test result regarding to cpu and memory utilization? I have tried to run multiple test with the built-in parallelism ("npx playwright test testfolder --workers 4, running tests in a folder with multiple workers configuration)

**Comment by yusong0926** [comment]
the cpu utilization is 90% out of 100 for a 4 core 4g a cloud instance. I am trying to test the concurrency so I can decide how many test I can assign to one machine. but it seems the result is not good.

**Comment by dgozman** [comment]
@yusong0926 Performance measurements heavily depend on your environment, so any measurements taken on my computer will not apply to your cloud instances. I'd recommend to measure things yourself.

That said, Playwright does not run two tests in the same worker process simultaneously to avoid flakiness, and so two tests do not share the browser by default. We have not seen performance issues because of that. If you really want to share the browser, look into [`launchServer()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server) and [`connect()`](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) combo.

**Comment by yusong0926** [comment]
I actually tried sharing browser instance with multiple test. It doesn't make any difference in terms of cpu utilization. It seems each test will take over 1 core anyways.

onst { test } = require('@playwright/test');
const { chromium, webkit, firefox } = require('playwright');
test.describe.configure({ mode: 'parallel' });
let browser;
test.beforeAll(async () => {
  browser = await chromium.launch();
});
test.afterAll(async () => {
  await browser.close();
});
test('runs first', async () => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
});

test('runs second', async () => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
});

test('runs third', async () => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
});

test('runs fourth', async () => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.taobao.com');
  await page.close();
  await context.close();
});

**Comment by aslushnikov** [comment]
So to re-iterate, if you want to share browser instance between workers, you'll have to follow [this advice](https://github.com/microsoft/playwright/issues/19706#issuecomment-1366202883)

Other than that, there's no way to share browser between test workers.

**Comment by TanvirHossain-eco** [comment]
I know that I'm responding to this closed issue, but it will be helpful for others. The final solution is something like this. Try it you will see the results. 
The Code. 
const { test, expect } = require('@playwright/test');
test.describe.configure({ mode: 'serial' });

let browser;
let page;

test.beforeAll(async () => {
  browser = await require('playwright').chromium.launch();
  const context = await browser.newContext();
  page = await context.newPage();
  await page.goto('https://www.saucedemo.com/');
});

test.afterAll(async () => {
  await browser.close();
});

test('Test Case 1: Login', async () => {
  await page.goto('https://www.saucedemo.com/');
  await page.waitForTimeout(3000);
  await page.fill('#user-name', 'standard_user');
  await page.fill('#password', 'secret_sauce');
  await page.click('#login-button');
  await page.waitForTimeout(3000);
  // Verify login success...
});

test('Test Case 2: Filter and Add to Cart', async () => {
  await page.selectOption('.product_sort_container', 'za');
  await page.waitForTimeout(3000);
  await page.click('button[name="add-to-cart-sauce-labs-backpack"]');
  await page.waitForTimeout(3000);
  // Continue with the rest of the steps...
});

From the Terminal run the code: npx playwright test ./tests/my_first_test.spec.js --project=chromium --headed
It will run the multiple tests by sharing the same browser instance
