### ISSUE TITLE
[BUG] - Can't import TS File - Cannot find module X imported from Y

### ISSUE THREAD

**Issue by jdgamble555** [microsoft/playwright#19710]
**Context:**
- SvelteKit 1.0
- Windows 11
- Playwright 1.28.1 (comes with SvelteKit 1.0)

# Code Snippet

**tests/tests.ts**
```javascript
import { expect, test } from '@playwright/test';
import { my_module } from './utils';

test('index page has expected h1', async ({ page }) => {
	console.log(my_module);
	await page.goto('/');
	expect(await page.textContent('h1')).toBe('Welcome to SvelteKit');
});
```

**tests/utils.ts**
```js
export const my_module = 'testing buddy!';
```

**Describe the bug**

I run `npm run test` and I get this error:

```
Error: Cannot find module 'C:\web projects\testing-import\tests\utils' 
imported from C:\web projects\testing-import\tests\test.ts
```

This is a brand new SvelteKit project with Playwright. All I did was add those two files. I created a repo regardless:

https://github.com/jdgamble555/testing-import

Playwright is supposed to support Typescript [out-of-the-box](https://playwright.dev/docs/test-typescript).

How can I get a basic TS import working?

J

___

I also am not using any fancy TS Module alias etc... just basic importing.

**Comment by dgozman** [comment]
@jdgamble555 This is because your project has `type: "module"` in the `package.json`. When importing TypeScript files from modules, you have to specify the extension. You can read about this [in the documentation](https://playwright.dev/docs/test-typescript#typescript-with-esm). Let me know if that helps.

**Comment by jdgamble555** [comment]
I can't take off `type: module` without having unknown problems with SvelteKit.

Why then can I import `TS` files without the file extension outside of testing? 

J

**Comment by dgozman** [comment]
> Why then can I import TS files without the file extension when I am not testing fine?

I guess this depends on your bundler and/or build system. Playwright follows [official TypeScript + modules guidelines](https://www.typescriptlang.org/docs/handbook/esm-node.html).

**Comment by aslushnikov** [comment]
Closing since there's no immediate action required from Playwright team.

**Comment by danieldiekmeier** [comment]
In TypeScript 5.0, there (probably) will be a new module resolution option: `--moduleResolution bundler`: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler

I installed the TypeScript 5.0 Beta because I also want to use imports without extensions in Playwright. Sadly, it still does not seem to work. Are there plans to update Playwright to also support `--moduleResolution bundler`?

**Comment by kristojorg** [comment]
This is still the case with TS 5 having been released. I still have to use file extensions when importing into playwright tests.

**Comment by dgozman** [comment]
@danieldiekmeier, @kristojorg I filed #22169 for this feature.

**Comment by ASaiAnudeep** [comment]
I am able to make it work by updating the file extension to `.mts` and importing the file using `.mjs`.

### tests/tests.ts

```ts
import { expect, test } from '@playwright/test';
import { my_module } from './utils.mjs';

test('index page has expected h1', async ({ page }) => {
	console.log(my_module);
	await page.goto('/');
	expect(await page.textContent('h1')).toBe('Welcome to SvelteKit');
});
```

### tests/utils.mts

```ts
export const my_module = 'testing buddy!';
```

**Comment by JobaDiniz** [comment]
I'm using `type: commonjs` and still cannot import typescript modules:

```
ReferenceError: fetch is not defined

       at ..\worker\repository.ts:21

      19 |             return this.cache;
      20 |
    > 21 |         const response = await fetch(this.filePath);
         |                          ^
      22 |         if (response.status !== 200)
```

**Comment by theskillwithin** [comment]
I have the same problem just it requires .js extension

```
Error: Cannot find module '/node_modules/lodash/groupBy' imported from /app/utils/question.ts
Did you mean to import "lodash/groupBy.js"?
```

**Comment by xkomiks** [comment]
@theskillwithin did you solve this issue?

**Comment by theskillwithin** [comment]
no
