### ISSUE TITLE
[BUG] Can's capture right element snapshot

### ISSUE THREAD

**Issue by FrankWang117** [microsoft/playwright#19714]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac 12.4
- Node.js version: 16.15.0
- Browser: Chromium

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
  public async getCompareBuffer(templateIndex: number) {
        const path = `./newest-snapshot-for-e2e/template-${templateIndex}.png`;
        return this.page
            .locator('.flow-template-detail .thy-layout--has-sidebar .flow-chart-editor')
            .first()
            .screenshot({ path });
    }
  
  // Please include a snippet of HTML that shows an example of the content
  // you are testing.
 <flow-template-detail class="flow-template-detail"> 
  <div class="thy-layout--has-sidebar">
    <flow-chart-editor class="flow-chart-editor"></flow-chart-editor>
  </div>
</flow-template-detail>
```

**Describe the bug**

I want to capture element snapshot like this:
![image](https://user-images.githubusercontent.com/21688648/209597555-8d5e003d-84f0-426f-8560-66b1d76a7c06.png)
And I pretty sure my code is correct.
But I got this:
![image](https://user-images.githubusercontent.com/21688648/209597586-90b63f8e-ae48-4f78-b1f0-ba955d21f4b9.png)

I don't know why, can anybody help me?

**Comment by dgozman** [comment]
@FrankWang117 Your code looks correct indeed. Could you please provide repro that we can run locally? Otherwise I am not really sure how to help.

**Comment by aslushnikov** [comment]
@FrankWang117 this is not actionable without a repro. I'll have to close this for now, but please do not hesitate to re-file once you have a repro that we can run & debug locally!

Thanks,
Andrey
