### ISSUE TITLE
[Question] Args playwright test

### ISSUE THREAD

**Issue by Lineaire** [microsoft/playwright#19711]
Does a solution exist today to scour the data for example: 2 with process.args?

playwright test myfile 2

**Comment by dgozman** [comment]
@Lineaire Could you please be more specific? I am not sure I understand the question.

**Comment by Lineaire** [comment]
@dgozman thank you for your quick reply.

I'll explain my project to you, I use dramaturge to automate the posting of an object on 3 different sites in one go, my script retrieves the identifier of an object in the database and starts the posting of the ad .

I run the command: playwright test myfile.ts 2

2 represents the id of an object, I need to pass it to my script for it to perform the automation. It retrieves from the database.

My problem is therefore to transmit information in the command and to retrieve it in the code

**Comment by dgozman** [comment]
@Lineaire Take a look [at this guide](https://playwright.dev/docs/test-parameterize#passing-environment-variables) and let me know whether that helps.

**Comment by Lineaire** [comment]
@dgozman Thank you for your answer, the problem is indeed solved:

Works by writing this:
ID=2 playwright test file.test.ts

is by adding this in the file.test.ts file
console.log(process.env.ID)

Can we use playwright without necessarily doing tests?

**Comment by dgozman** [comment]
> Can we use playwright without necessarily doing tests like Puppeeter ?

Take a look at [this guide](https://playwright.dev/docs/library) then 😄

**Comment by Lineaire** [comment]
Thank you @dgozman
