### ISSUE TITLE
[BUG] Component Tests doesn't work with Zustand: "Target closed"

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#19717]
**Context:**
- Playwright Version: 1.29.1
- Operating System: mac
- Node.js version: 16
- Browser: all

**Code Snippet**

```typescript
import create from "zustand";

const useStore = create((set) => ({
  count: 1,
  inc: () => set((state) => ({ count: state.count + 1 })),
}));

function Controls() {
  const inc = useStore((state) => state.inc);
  return <button onClick={inc}>one up</button>;
}

function Counter() {
  const count = useStore((state) => state.count);
  return <h1>{count}</h1>;
}

function App() {
  return (
    // Workaround for React.Fragment not being supported
    <div>
      <Controls />
      <Counter />
    </div>
  );
}

test("zustand", async ({ mount, context }) => {
  const component = await mount(<App />);

  await component.click("button");
  await expect(component).toContainText("2");
});

```

**Describe the bug**

Playwright gets stuck on mounting/serializing the component (which means component tests cannot be used with any components that use zustand). The actual error message is "Target closed", but I assume that just means there was some issue serializing the component and the test timed out while trying to do it.

**Comment by sand4rt** [comment]
Tried to reproduce the issue but it seems to work as expected. I did noticed that the button click selector needs to be: 
`await component.getByRole("button").click();` instead of `await component.click('button');`

Are the components separated in multiple files or are they all defined in the test file? If so, you may run into this issue https://playwright.dev/docs/test-components#q-why-cant-i-pass-a-variable-to-mount 

Reproduction that works:

```typescript
// store.ts
import create from "zustand";

export const useStore = create((set) => ({
  count: 1,
  inc: () => set((state) => ({ count: state.count + 1 })),
}));
```

```typescript
// Controls.tsx
import { useStore } from './store';

export function Controls() {
  const inc = useStore((state) => state.inc);
  return <button onClick={inc}>one up</button>;
}
```

```typescript
// Counter.tsx
import { useStore } from './store';

export default function Counter() {
  const count = useStore((state) => state.count);
  return <h1>{count}</h1>;
}
```

```typescript
// App.tsx
import Controls from './Controls';
import Counter from './Counter';

export function App() {
  return (
    // Workaround for React.Fragment not being supported
    <div>
      <Controls />
      <Counter />
    </div>
  );
}
```

```typescript
// App.test.tsx
import { test, expect } from '@playwright/experimental-ct-react';
import App from './App';

test("zustand", async ({ mount, context }) => {
  const component = await mount(<App />);

  await component.getByRole("button").click();
  await expect(component).toContainText("2");
});
```

**Comment by WesleyYue** [comment]
Thanks for verifying that this is supposed to work. That's actually super helpful. I double checked and it turned out I had three issues:

1. In my actual application, my store was within the same file of one of the components. Extracting the store out to it's own file fixed the problem.
2. In the toy example, while I did read the Known Issues in the docs, I did not realize declaring the components would also be part of the same bug, since that FAQ technically only talks about using variables, which I didn't think I was doing.
3. I had to clear my cache (`rm -rf playwright/.cache`) and rebuild. Once I got the error the first time, I have to clear the cache or it will continue to get stuck even if everything is fixed.

**Comment by WesleyYue** [comment]
@sand4rt if I get Target Closed (because presumably, there's some non-component code being run in a .tsx/jsx), is there a way to get a more meaningful message and see where in the component tree is causing the mount to hang? This is the biggest barrier to adoption for us in our real application right now. We've isolated out all the Zustand stores to separate .ts files, but something else is stuck and since we didn't write our initial codebase with Playwright component test in mind, we would have to go through every file manually to verify which makes it a blocker from us adopting Playwright component tests.

**Comment by sand4rt** [comment]
Yes, i agree that better error messages would be really helpful. Maybe you can create a separate ticket to bring this to light again?
