### ISSUE TITLE
[Question] Playwright Electron - does it launch the app using the current user?

### ISSUE THREAD

**Issue by JessnarStretchSense** [microsoft/playwright#19718]
I am currently getting confused whether Playwright is launching my app as the current user that I am logged in my machine. When I run my app manually using my admin account, it is working properly but when I start running it via Playwright, it doesn't seem to use my admin account as it starts erroring out where it shouldn't.

**Comment by dgozman** [comment]
@JessnarStretchSense Yes, Playwright starts the app as a current user.
