### ISSUE TITLE
[Feature] Render props pattern for Component Tests

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#19716]
Trying to use Playwright Component Tests with Formik and I have the following feature requests:

# Playwright can't serialize render props pattern
It looks like Playwright's .mount() is unable to work with the [render props pattern that Formik uses](https://formik.org/docs/api/formik), where the [children prop is a function that returns a component](https://github.com/jaredpalmer/formik/blob/e677bea8181f40e6762fc7e7fb009122384500c6/packages/formik/src/types.tsx#L187), rather than a component directly.

I'm not entirely familiar with how Playwright does the serialization (would be awesome if there can be more documentation on this, as I think the browser/node boundary was the hardest concept to understand. What code is running in browser? What code is running in node?), but is there a technical limitation that makes this impossible? Or is this something we can put on the roadmap?

# Better error messages when serialization breaks
When I tried to build the Playwright Component Test, I got the following stack trace for the above issue:
```
    component.type is undefined
    render@http://localhost:3100/assets/index.c905fa6c.js:58431:11
    render/<@http://localhost:3100/assets/index.c905fa6c.js:58449:12
    render@http://localhost:3100/assets/index.c905fa6c.js:58446:92
    render/<@http://localhost:3100/assets/index.c905fa6c.js:58449:12
    render@http://localhost:3100/assets/index.c905fa6c.js:58446:92
    render/<@http://localhost:3100/assets/index.c905fa6c.js:58449:12
    render@http://localhost:3100/assets/index.c905fa6c.js:58446:92
    render/<@http://localhost:3100/assets/index.c905fa6c.js:58449:12
    render@http://localhost:3100/assets/index.c905fa6c.js:58446:92
    window.playwrightMount@http://localhost:3100/assets/index.c905fa6c.js:58461:19
    @debugger eval code line 197 > eval:24:18
    evaluate@debugger eval code:199:17
    @debugger eval code:1:44
```
This was super hard to understand and debug, and I had to eliminate things in the component tree one by one to figure out what was causing this error. It would be great if this stack trace can be more helpful in explaining what is breaking the serialization.

**Comment by sand4rt** [comment]
About the Formik issue: There is no support for "scoped slots" or "function as children" atm see: https://github.com/microsoft/playwright/issues/18758

**Comment by dgozman** [comment]
Closing in favor #18758.
