### ISSUE TITLE
[Question] How can I run Playwright’s test inside a preact project? 

### ISSUE THREAD

**Issue by chrisha22** [microsoft/playwright#19728]
Does Playwright supports preact?

I found this plugin https://www.npmjs.com/package/@preact/playwright-ct?activeTab=readme, but there is not enough documentation to test it, and when I try to run `yarn run test-ct`, the below error shows up.

any help is appreciated.

```
[vite]: Rollup failed to resolve import "react" from "playwright/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
Error: [vite]: Rollup failed to resolve import "react" from "playwright/index.ts".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

**Comment by sand4rt** [comment]
Would be nice, but unfortunately there is no support for Preact at the moment. Don't know how much priority it has for Playwright but i could take a look at the issue if you can share a GitHub repo?

**Comment by pavelfeldman** [comment]
Are you interested in component or e2e testing?

**Comment by chrisha22** [comment]
@sand4rt Thank you so much for the update.
Unfortunately I cannot share a repo right now, but thanks anyway.

@pavelfeldman It is for test automation, It is more related to e2e.

**Comment by sand4rt** [comment]
@chrisha22 i was talking about component testing support for Preact: https://playwright.dev/docs/test-components. E2E testing should work

**Comment by pavelfeldman** [comment]
@chrisha22 Preact and all the other web frameworks are supported out of the box in Playwright, no plugins necessary.
