### ISSUE TITLE
[BUG] toHaveJSProperty matcher doesn't work with regex

### ISSUE THREAD

**Issue by 4ekki** [microsoft/playwright#19722]
**Context:**
- Playwright Version: Version 1.25.1
- Operating System: macOS 13.0.1
- Node.js version: v18.12.1
- Browser: Chromium

**Bug description**
Matcher `toHaveJSProperty` is unable to work with regexes in the same way, as `toHaveText` one.
F.e., I want to check `outerText` property of some element on http://example.com. 
![image](https://user-images.githubusercontent.com/38757986/209690360-ff1fae41-49ff-427c-8997-0a8a9cd9e7c1.png)
I expect, that `expect(page.locator("body > div > h1")).toHaveJSProperty("outerText", /Domain/);` will pass. However, it fails. 

**Code Snippet**
```typescript
import {expect, test} from "@playwright/test";

test.describe("toHaveJSProperty", () => {
  test("plain value works", async ({page}) => {
    await page.goto("http://example.com");
    expect(page.locator("body > div > h1")).toHaveJSProperty("outerText", "Example Domain");
  });

  test("regex value doesn't work", async ({page}) => {
    await page.goto("http://example.com");
    expect(page.locator("body > div > h1")).toHaveJSProperty("outerText", /Domain/);
  });
});

test.describe("toHaveText", () => {
  test("plain value works", async ({page}) => {
    await page.goto("http://example.com");
    expect(page.locator("body > div > h1")).toHaveText("Example Domain");
  });

  test("regex value doesn't work", async ({page}) => {
    await page.goto("http://example.com");
    expect(page.locator("body > div > h1")).toHaveText(/Domain/);
  });
});
```

**Console Output**
```bash
$ playwright test bugDemo

Running 4 tests using 1 worker
  1) [chromium] › bugDemo.test.ts:9:3 › toHaveJSProperty › regex value doesn't work ================

    Error: expect(received).toHaveJSProperty(expected) // deep equality

    Expected: /Domain/
    Received: "Example Domain"
    Call log:
      - expect.toHaveJSProperty with timeout 5000ms
      - waiting for selector "body > div > h1"
      -   selector resolved to <h1>Example Domain</h1>
      -   unexpected value "Example Domain"


       9 |   test("regex value doesn't work", async ({page}) => {
      10 |     await page.goto("http://example.com");
    > 11 |     expect(page.locator("body > div > h1")).toHaveJSProperty("outerText", /Domain/);
         |                                             ^
      12 |   });
      13 | });
      14 |

        at /.../tests/bugDemo.test.ts:11:45

    attachment #1: trace (application/zip) ---------------------------------------------------------
    report/html/bugDemo-toHaveJSProperty-regex-value-doesn-t-work-chromium/trace.zip
    Usage:

        npx playwright show-trace report/html/bugDemo-toHaveJSProperty-regex-value-doesn-t-work-chromium/trace.zip

    ------------------------------------------------------------------------------------------------


  1 failed
    [chromium] › bugDemo.test.ts:9:3 › toHaveJSProperty › regex value doesn't work =================
  3 passed (5s)

```

**Comment by dgozman** [comment]
@4ekki `toHaveJSProperty()` compares the property value with the value you passed. Since `outerText` is a string, and you pass a `RegExp` instance, they are not equal. `toHaveText()` is very different, it matches text against regular expression or a substring.

So, if you would like to match text, use `toHaveText()`. If you need to compare JS properties, use `toHaveJSProperty`. Let me know if that helps.

**Comment by 4ekki** [comment]
@dgozman, unfortunately, I'm not able to use `toHaveText()`, cause my element doesn't have any text in HTML. I used `outerText` only as an example on common website, for submitting this issue. What I'm actually trying to check, is `value` string property of Angular webapp and it seems that only `toHaveJSProperty()` is able to check such things. 
Other possible option is to extract that value into a variable and assert it separately, but in this case Playwright won't `await` till this assertion is fulfilled.

**Comment by dgozman** [comment]
> Other possible option is to extract that value into a variable and assert it separately, but in this case Playwright won't await till this assertion is fulfilled.

Yes, if you need a custom-type assertion for the value, this is the easiest way. Luckily, Playwright has a solution for awaiting until the assertion is fulfilled with [`expect().toPass()`](https://playwright.dev/docs/test-assertions#retrying). Let me know if that helps.

**Comment by 4ekki** [comment]
@dgozman, thank you, retrying should help with this.
