### ISSUE TITLE
[Question] Is there any possibility to do Database testing using Playwright JS?

### ISSUE THREAD

**Issue by yash-lohakare** [microsoft/playwright#19738]
Is it possible to verify and test the data directly from DB using Playwright js?

**Comment by dgozman** [comment]
@yash-lohakare It is possible. You'll need some Node.js package to connect to the database, like [this one](https://www.npmjs.com/package/pg) for Postgres, and then make any database calls you'd like.

**Comment by ShaharM7** [comment]
The functionality that you want is not the mission of the playwright.
 If you want to connect to third parties like databases, and message queues (kafka, rabbitmq and so on) you have to use the SDK client library. 
 For example what @dgozman said to you :)
