### ISSUE TITLE
[Question] Test passes locally but fails on Github CI at expecting external URL domain.

### ISSUE THREAD

**Issue by dev-xo** [microsoft/playwright#19731]
Hello guys. 
This probably is a simple one, but I'm not able to solve it by myself.

On local dev, I'm able to get the test pass, by awaiting a redirect from my site, to an external domain url.
Sadly this does not succeed on Github CI Actions.

**Any idea about what could be going on?
Does Playwright allow to await for an external url redirect when running on CI?**

Here is the test code:
```
test('Should redirect to Stripe checkout on submit paid-plan form.', async ({
    page,
}) => {
    const user = await createFakeUser({})
    await setUserContextCookies({ page, user })
    
    await page.goto('/register/plans')
    await page
    .getByTestId(`${STRIPE_KEYS.PREMIUM_PLAN}-plan`.toLowerCase())
    .click()
    
    await expect(page).toHaveURL(STRIPE_KEYS.CHECKOUT_REDIRECT_URL)
})
```

And here is the logs from Github Actions:
![Screen Shot 2022-12-28 at 00 01 41](https://user-images.githubusercontent.com/82425492/209734848-e950abf2-724d-4f91-8969-21e238e8eeaa.png)

I've checked the Trace, and as I said, on local dev everything works as expected.
I'm not mockign anything, and keeping things as simple as possible.

Thank you!

**Comment by dgozman** [comment]
@dev-xo Playwright works exactly the same locally and on CI. However, stripe page may behave differently. There was a similar issue #19709 recently, where @krasdav figured out the issue. Perhaps you are facing the same problem?

**Comment by dev-xo** [comment]
Thanks @dgozman . Posted a message on that Issue.

Him says the Issue was fixed from Github Actions and his envs, or something like that. 
So gonna take an eye on it.

Gonna update here my workaround about this in the next few hours / days.
Thank you!

**Comment by dev-xo** [comment]
Solved here. 
Had issues with .env variables and my environment.

Closing this. Thank you @dgozman for the replies.

**Comment by teddy-beau** [comment]
Thanks, I had the same issue and it was indeed related to a missing .env variable in our Playwright dedicated .env, and more specifically the one used to build the URL of the external page.
