### ISSUE TITLE
[Question] How correctly use persistent context in parallel tests which require authorization?

### ISSUE THREAD

**Issue by AndrewEgorov** [microsoft/playwright#19742]
I have following situation:
* I have extension which works on some sites
* I have a sites to which I need login
* Currently I do the following and it works:
  * I use test fixture to setup context using launchPersistentContext in a worker scope (this gives me isolated context for every worker). In this context I specify different user dirs (using worker index e.g.)
  * In same fixture I return page (test scope), and some other wrappers (also test scope)
   * Tests run in parallel by spec files. Every spec file has: beforeAll - in which I login to site/extension and tests. 

I tried to use `launchPersistentContext` with `storageState` to avoid logging in every time and wanted just login once, save to storage.json and reuse it in every new context - but seems it's not supported and doesn't work.

Currently I experiment with following scenario:
* global setup - create persistent context in **USER_DIR**, login to every site
* run tests in parallel (even inside spec) - create persistent context in **USER_DIR** for every test (and some other things), do test etc...

Questions:
* Is it possible to re-use **USER_DIR** in parallel and create many persistent context targeting same dir? If yes how correctly to do that
* Is there any chance that launchPersistentContext will work with storageState?
* If the way I want to achieve my aim above incorrect: can you please point me to the correct one? 

Thanks.

Sample code (doesn't work):

```
import {
  test as base,
  BrowserContext,
  chromium,
  Page,
} from "@playwright/test";
import path from "path";

type ExtensionTestFixtures = {
  launchPersistent: () => Promise<{ page: Page }>;
  page: Page;
};

export const test = base.extend<ExtensionTestFixtures>({
  launchPersistent: async ({}, run) => {
    let persistentContext: BrowserContext | undefined;
    await run(async () => {
      if (persistentContext)
        throw new Error("can only launch one persistent context");
      var extensionPath = __dirname + "/../chrome-extension/";

      const userDataDir = path.join(
        __dirname,
        `/../tmp/user_dir_${process.env.ENV}`
      );

      persistentContext = await chromium.launchPersistentContext(userDataDir, {
        headless: false,
        devtools: false,
        ignoreDefaultArgs: ["--enable-automation"],
        args: [
          `--disable-extensions-except=${extensionPath}`,
          `--load-extension=${extensionPath}`,
        ],
      });
      const page = persistentContext.pages()[0];
      return { page };
    });
    if (persistentContext) await persistentContext.close();
  },
  page: async ({ launchPersistent }, run) => {
    const { page } = await launchPersistent();
    //btw for some sites it fails immediately without this wait :/ 
    await page.waitForTimeout(2000);
    await run(page);
  },
});

test.describe.configure({ mode: "parallel" });

test.describe("Extension Test #1", async () => {
  test("1.1", async ({ page }) => {
    await page.goto("https://www.google.com");
    await page.waitForTimeout(2000);
  });

  test("2.1", async ({ page }) => {
    await page.goto("https://www.google.com");
    await page.waitForTimeout(2000);
  });
});

test.describe("Extension Test #2", async () => {
  test("1.2", async ({ page }) => {
    await page.goto("https://www.google.com");
    await page.waitForTimeout(2000);
  });

  test("2.2", async ({ page }) => {
    await page.goto("https://www.google.com");
    await page.waitForTimeout(2000);
  });
});

```

**Comment by dgozman** [comment]
> Is it possible to re-use USER_DIR in parallel and create many persistent context targeting same dir? If yes how correctly to do that

No, browsers do not allow that.

> Is there any chance that launchPersistentContext will work with storageState?

Since persistent context already comes with storage state from previous usage, such an API would be hard to define/use. However, we can still look into that.

> If the way I want to achieve my aim above incorrect: can you please point me to the correct one?

So far you are doing the right thing, given the limitations. Take a look at [this guide](https://playwright.dev/docs/auth#avoiding-multiple-sessions-per-account-at-a-time) that allows you to login once per worker, instead of once per test file - this technique could improve the performance.

It could be that running in `fullyParallel` mode and logging in for each test will end up faster just because of the parallelism, but you'll need to measure it.

**Comment by AndrewEgorov** [comment]
Thanks @dgozman.

> So far you are doing the right thing, given the limitations. Take a look at [this guide](https://playwright.dev/docs/auth#avoiding-multiple-sessions-per-account-at-a-time) that allows you to login once per worker, instead of once per test file - this technique could improve the performance.

Yeah, I already use almost same approach create storage fixture in scope of worker. I just was experimenting thing to understand more about persistent context and how it works.

> Since persistent context already comes with storage state from previous usage, such an API would be hard to define/use. However, we can still look into that.

Would be really good if you can take a look at it, as it may definitely improve speed of some tests. Currently I can do that by setting cookies, which works but require some work :/ 

> No, browsers do not allow that.

But can you say why? What is the idea of 'persistent context', is it the same as current user dir on my PC? If yes, I can override browser's user dir and target it to same (even from different user accounts).

Also e.g. I have few sites which require MFA to login (I can' bypass it as it's not our app), the idea previously was: I login to all sites, even those which require MFA in global setup and then re-use this state targeting same dir in multiple persistent contexts.   [This guide] (https://playwright.dev/docs/auth#multi-factor-authentication) describe how to use MFA with persistent context so seems it can only be done only once for each user dir. Will it work if I will create copy of this dir on creating new persistent context? :D (need to try)

And going back to the code above (one more question). If I remove 'parallel' from code above, remove wait before return page from text fixture and change navigation url to not `www.google.com` the code will fail. Can you help me understand why?

* If you specify navigation url as google.com code below will work
* If navigation url not google but some other site it fails without wait in `page` fixture. Tried to catch error using goto(url).catch(e) but it return same informative error and I can't understand why it doesn't work

![image](https://user-images.githubusercontent.com/7087798/209895492-5839f13b-619c-4063-9464-483ce833a540.png)


```
import {
  test as base,
  BrowserContext,
  chromium,
  Page,
} from "@playwright/test";
import path from "path";

type ExtensionTestFixtures = {
  launchPersistent: () => Promise<{ page: Page }>;
  page: Page;
};

export const test = base.extend<ExtensionTestFixtures>({
  launchPersistent: async ({}, run) => {
    let persistentContext: BrowserContext | undefined;
    await run(async () => {
      if (persistentContext)
        throw new Error("can only launch one persistent context");
      var extensionPath = __dirname + "/../chrome-extension/";

      const userDataDir = path.join(
        __dirname,
        `/../tmp/user_dir_${process.env.ENV}`
      );

      persistentContext = await chromium.launchPersistentContext(userDataDir, {
        headless: false,
        devtools: false,
        ignoreDefaultArgs: ["--enable-automation"],
        args: [
          `--disable-extensions-except=${extensionPath}`,
          `--load-extension=${extensionPath}`,
        ],
      });
      const page = persistentContext.pages()[0];
      return { page };
    });
    if (persistentContext) await persistentContext.close();
  },
  page: async ({ launchPersistent }, run) => {
    const { page } = await launchPersistent();
    //btw for some sites it fails immediately without this wait :/ 
    //if you uncomment this wait with targeting not google.com it will work, otherwise fails
    // await page.waitForTimeout(2000);
    await run(page);
  },
});

const navigationUrl = "https://www.outreach.io/";
// const navigationUrl = "https://www.google.com/";

test.describe("Extension Test #1", async () => {
  test("1.1", async ({ page }) => {
      await page.goto(navigationUrl);
      await page.waitForTimeout(2000);
  });

  test("2.1", async ({ page }) => {
    await page.goto(navigationUrl);
    await page.waitForTimeout(2000);
  });
});

test.describe("Extension Test #2", async () => {
  test("1.2", async ({ page }) => {
    await page.goto(navigationUrl);
    await page.waitForTimeout(2000);
  });

  test("2.2", async ({ page }) => {
    await page.goto(navigationUrl);
    await page.waitForTimeout(2000);
  });
});

```

**Comment by dgozman** [comment]
> > No, browsers do not allow that.

> But can you say why? What is the idea of 'persistent context', is it the same as current user dir on my PC? If yes, I can override browser's user dir and target it to same (even from different user accounts).

Each browser assumes the ownership of the user data dir. For example, if you launch Chromium twice pointing to the same dir, the second instance will focus the first one and exit. This is by design.

> Will it work if I will create copy of this dir on creating new persistent context?

Probably, unless there are some absolute paths written inside the user data dir. Give it a try!

> If navigation url not google but some other site it fails 

Looking at the `net::ERR_ABORTED`, something interrupts the navigation. Perhaps the extension? Unfortunately, I cannot really help there without a repro.

**Comment by AndrewEgorov** [comment]
Ok. Thanks for your help @dgozman. Really appreciate it. Will open separate ticker for the bug if issue not in extension. Thanks
