### ISSUE TITLE
[BUG] - aftereAll is not executed if there is a last test with a skip

### ISSUE THREAD

**Issue by IgorKoryapin** [microsoft/playwright#19745]
**Context:**
- Playwright Version: [1.23.3]
- Operating System: [Linux]
- Node.js version: [18.12.1]
- Browser: [All]
- Extra: [-]

**Code Snippet**

```
test.describe.....
  test.beforeAll ....1....
  test.afterAll .......1......

  test.describe.....
     test.beforeAll ....2....
     test.afterAll .......2......

     test.describe.....
         test.beforeAll ....3....
         test.afterAll .......3......
         test.....1.....
         test....2...
         test.skip....3.....
```

**Describe the bug**
With this design, when the last test is skipped, it will not be executed "test.afterAll .......3......"
If you make a skip, for example, pre-midday, then "test.afterAll .......3......" will be performed

Add any other details about the problem here.
-

**Comment by dgozman** [comment]
@IgorKoryapin I cannot reproduce this issue on the latest Playwright. Perhaps the issue was fixed, and you should upgrade? 

---

Here is what I run with Playwright v1.29.1:

```ts
// example.spec.ts

import { test } from '@playwright/test';

test.describe('outer', () => {
  test.beforeAll(() => { console.log('beforeAll1'); });
  test.afterAll(() => { console.log('afterAll1' ); });

  test.describe('middle', () => {
    test.beforeAll(() => { console.log('beforeAll2'); });
    test.afterAll(() => { console.log('afterAll2'); });

    test.describe('inner', () => {
      test.beforeAll(() => { console.log('beforeAll3'); });
      test.afterAll(() => { console.log('afterAll3'); });

      test('test1', () => { console.log('test1'); });
      test('test2', () => { console.log('test2'); });
      test.skip('test3', () => { console.log('test3'); });
    });
  });
});
```

```sh
% npx playwright test example.spec.ts --reporter=line

Running 3 tests using 1 worker
example.spec.ts:15:11 › outer › middle › inner › test1
beforeAll1
beforeAll2
beforeAll3
test1
example.spec.ts:16:11 › outer › middle › inner › test2
test2
example.spec.ts:17:12 › outer › middle › inner › test3
afterAll3
afterAll2
afterAll1

  1 skipped
  2 passed (295ms)
```

**Comment by IgorKoryapin** [comment]
Hello.
I changed your code a bit to:

`import { test } from '@playwright/test' ;



test.describe ( 'outer' , ( ) => {

  test.beforeAll ( ( ) => { console.log ( 'beforeAll1' ) ; } ) ;

  test.afterAll ( ( ) => { console.log ( 'afterAll1' ) ; } ) ;



  test.describe.serial ( 'middle' , ( ) => {

    test.beforeAll ( ( ) => { console.log ( 'beforeAll2' ) ; } ) ;

    test.afterAll ( ( ) => { console.log ( 'afterAll2' ) ; } ) ;



    test.describe.serial ( 'inner' , ( ) => {

      test.beforeAll ( ( ) => { console.log ( 'beforeAll3' ) ; } ) ;

      test.afterAll ( ( ) => { console.log ( 'afterAll3' ) ; } ) ;

      
      test.describe.serial ( 'inner2' , ( ) => {

        test.beforeAll ( ( ) => { console.log ( 'beforeAll4' ) ; } ) ;
  
        test.afterAll ( ( ) => { console.log ( 'afterAll4' ) ; } ) ;
  
  
  
        test ( 'test1' , ( ) => { console.log ( 'test1' ) ; } ) ;
  
        test ( 'test2' , ( ) => { console.log ( 'test2' ) ; } ) ;
  
        test.skip ( 'test3' , ( ) => { console.log ( 'test3' ) ; } ) ;
  
      } ) ;

      test.describe.serial ( 'inner3' , ( ) => {

        test.beforeAll ( ( ) => { console.log ( 'beforeAll5' ) ; } ) ;
  
        test.afterAll ( ( ) => { console.log ( 'afterAll5' ) ; } ) ;
  
  
  
        test ( 'test4' , ( ) => { console.log ( 'test4' ) ; } ) ;
  
        test ( 'test5' , ( ) => { console.log ( 'test5' ) ; } ) ;
  
        test.skip ( 'test6' , ( ) => { console.log ( 'test6' ) ; } ) ;
  
      } ) ;

    } ) ;

  } ) ;

} ) ; `

`Running 6 tests using 1 worker

  ✓  1 [chromium] › tests/example.spec.ts:36:9 › outer › middle › inner › inner2 › test1 (20ms)
beforeAll1
beforeAll2
beforeAll3
beforeAll4
test1
  ✓  2 [chromium] › tests/example.spec.ts:38:9 › outer › middle › inner › inner2 › test2 (11ms)
test2
  -  3 [chromium] › tests/example.spec.ts:40:14 › outer › middle › inner › inner2 › test3
  ✓  4 [chromium] › tests/example.spec.ts:52:9 › outer › middle › inner › inner3 › test4 (6ms)
beforeAll5
test4
  ✓  5 [chromium] › tests/example.spec.ts:54:9 › outer › middle › inner › inner3 › test5 (10ms)
test5
  -  6 [chromium] › tests/example.spec.ts:56:14 › outer › middle › inner › inner3 › test6
afterAll5
afterAll3
afterAll2
afterAll1


  2 skipped
  4 passed (22s)`
  
  as you can see after **test2** there is no **beforeAll4**
