### ISSUE TITLE
[Question] If my XPATH has an invalid token, how can I overpass it?

### ISSUE THREAD

**Issue by doviec** [microsoft/playwright#19748]
- Playwright Version: 1.28.0
- Operating System: Windows
- Browser: Chromium
- sync_playwright

I have the following XPATH:  //span[contains(text(),'Tom & Jerry')]
and when trying to generate a Locator from this xpath, I get this error:
**Unexpected token _"&"_ while parsing selector**
Is there a workaround on this? is this a bug? 

Please note, that I get the xpath from a different source so I can't change the xpath.

Thanks for any answer.

**Comment by dgozman** [comment]
@doviec This particular xpath selector `//span[contains(text(),'Tom & Jerry')]` works for me both in Chrome and through Playwright. Perhaps there is another one that does not work? That said, if your selector is not a valid xpath, it is not going to work. Note that Playwright [does not recommend](https://playwright.dev/docs/locators) to use xpath, you'll be better off with other locators.

**Comment by doviec** [comment]
Thanks @dgozman for your quick reply.
Indeed the XPATH is working. 
Due to the fact that Playwright **doesn't have a method to get a web element by ID** such as: //div[@id='Tom & Jerry'] 
I tried to convert the Selenium locator by ID to a valid Xpath which was written incorrectly.
Unfortunately, shifting from Selenium to Playwright while having 1,000+ locators based on Xpath, id etc, is the reason of using these Xpathes and not the recommended methods.

**Comment by LongLiveY96** [comment]
id contains spaces in itself is not standardized, playwright itself is to support css selector, in addition id is usually globally unique, you do not need to add the div filter conditions, if id specification premise you want to do so, then you can write so:div#id.
