### ISSUE TITLE
[BUG] Actionability checks in Locator.BoundingBoxAsync() and ElementHandle.BoundingBoxAsync()

### ISSUE THREAD

**Issue by jpEngProd** [microsoft/playwright#19749]
**Context**
We are replacing ElementHandler by Locator for performing interactions on elements. This is about one of such replacement `BoundingBoxAsync()` and it's usage in Locator vs ElementHandler

- Playwright Version: [1.23.0]
- Operating System: [Windows]
- Dot Net Version: .net 7.0.101
- Browser: [Chromium]

**Code Snippet**

```//Dotnet
using var playwright = await Playwright.CreateAsync();
var chromium = playwright.Chromium;
var browser = await chromium.LaunchAsync(new BrowserTypeLaunchOptions { Headless = false });
var page = await browser.NewPageAsync();
var url="{Localhost_url}";
await page.GotoAsync(url);
var xpath = "{}";
var elementHandle = await page.QuerySelectorAsync(xpath );
var elementLocator = page.Locator(xpath );
var rect = await elementHandle.BoundingBoxAsync(); //This executes successfully
var rect1 = await elementLocator.BoundingBoxAsync(); //This part throws exception  
 ```

**Exception Details**
```
Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "{xpath}" to be visible
  selector resolved to hidden <div>..</div>
============================================================

   at Microsoft.Playwright.Transport.Connection.<InnerSendMessageToServerAsync>d__38`1.MoveNext()
   at Microsoft.Playwright.Transport.Connection.<WrapApiCallAsync>d__50`1.MoveNext()
   at Microsoft.Playwright.Core.Frame.<WaitForSelectorAsync>d__81.MoveNext()
   at Microsoft.Playwright.Core.Locator.<ElementHandleAsync>d__20.MoveNext()
   at Microsoft.Playwright.Core.Locator.<WithElementAsync>d__64`2.MoveNext()
```

**Describe the bug**
I have a DOM element in UI where visibility of DOM element is set to hidden, but the element is present on the page. In this case if I use elementHandle.BoundingBoxAsync() then it return the box variables(x, y, width, height) but If I use Locator.BoundingBoxAsync() then it throws an error stating that waiting for element to be visible, element is resolved to hidden.
1. Here I believe that elementHandle.BoundingBoxAsync() does not perform actionability checks but Locator does.
2. If yes then Is there any way to set `Force=true` in order to not perform actionability checks over Locator as well?

**Comment by dgozman** [comment]
@jpEngProd I think this was fixed in https://github.com/microsoft/playwright-dotnet/pull/2304, so try updating your Playwright to a newer version and let me know whether it helps.

**Comment by aslushnikov** [comment]
Closing this for now since it seems to be fixed.

@jpEngProd please do not hesitate to re-file if things are still broken for you!
