### ISSUE TITLE
[BUG] VSCode extension does not update testInfo object

### ISSUE THREAD

**Issue by lucasbit** [microsoft/playwright#19746]
**Context:**
- Playwright Version: 1.28.1
- Operating System: [e.g. Windows 11
- Node.js version: 18.12.1
- Visual Studio Code version: 1.74.2
- Playwright for VSCode extension version: 1.0.3
- Browser: Chromium
- Extra: 

**Code Snippet**
![image](https://user-images.githubusercontent.com/29520131/209802785-d39392d3-f406-4afd-a6a1-b2cf7280acfe.png)
![image](https://user-images.githubusercontent.com/29520131/209803191-c48ba0d9-3828-4bdc-981c-ca77eb971333.png)
![image](https://user-images.githubusercontent.com/29520131/209803607-4284743b-87b2-42cb-a543-a5f9caa851a4.png)

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**
I'm trying to implement visual comparison, but I have a lot of differences between headfull and headless testing with Chromium ( 12912 pixels (ratio 0.04 of all image pixels) are different) or perhaps that is not a lot off difference? 
![image](https://user-images.githubusercontent.com/29520131/209804283-3a1a237c-4847-4d8e-8f3a-e72a6b79cb5b.png)

It works fine when testing only in headless mode. So my idea is that, I can read value of testInfo object and run visual checks only when browser is headless. But that solution does not work when running tests from the VSCode extension. And that a big issue as then I can't use your amazing locator selector and other cool features from VSCode extension. 

Or perhaps there is another value in testInfo object I can check out if test run is triggered from terminal vs VSCode extension? 

Add any other details about the problem here.

**Comment by dgozman** [comment]
@lucasbit Instead of looking into `testInfo.project.use.headless` that reflects your config file and not the final value, examine the `headless` fixture:

```ts
test('my test', async ({ page, headless }) => {
  console.log(headless);
});
```

Let me know if that helps.

**Comment by lucasbit** [comment]
@dgozman, thanks for quick replay, sadly your suggestion didn't work. I will paste my code snippet in case I'm doing something wrong(doubt it):
![image](https://user-images.githubusercontent.com/29520131/209966235-8f0631aa-f676-4231-a0ff-3058f440a945.png)
![image](https://user-images.githubusercontent.com/29520131/209966356-9da7b9d7-622a-4887-b235-86a0395af4b0.png)

**Comment by dgozman** [comment]
I can repro this.

Investigation notes: "reuse browser mode" in `PlaywrightConnection` forces headed browser, and this is not aligned with what the client requests, thus the discrepancy.

Proposed solution: pass `--headed` from the extension when running tests and make the client control whether the browser is headless. This will make "Show browser" checkbox not work for test files that explicitly call `test.use({ headless: true })`.
