### ISSUE TITLE
[BUG] page.goto: Timeout 80000ms exceeded. navigating to "my-site", waiting until "load"

### ISSUE THREAD

**Issue by k4mmm** [microsoft/playwright#19750]
- Playwright Version: [1.29.1]
- Operating System: [Mac]
- Node.js version: [v14.17.3]
- Browser: [Chromium]

```
page.goto: Timeout 80000ms exceeded.
    =========================== logs ===========================
    navigating to "my-site", waiting until "load"
    ============================================================
       at helperTest.js:16
      14 |
      15 | const login = async (page, userName) => {
    > 16 | 	await page.goto(baseUrl, { timeout: 80000 });
         | 	           ^
      17 | 	await page.getByRole('button', { name: 'Sign in' }).click();
      18 | 	await page.getByLabel('username or email').click();
      19 | 	await page.getByLabel('username or email').fill(us
```

      
      
Hello.
When running the test locally, everything is fine. When I run it on gitlab, I get an error. However, sometimes the test passes. After the trace - I see what he is trying to do goto, but stops on a white screen and does not go any further

<img width="1639" alt="Знімок екрана 2022-12-28 о 16 02 17" src="https://user-images.githubusercontent.com/76705143/209824015-edd55624-ca11-4a56-8c57-33655869430b.png">

Thank you

**Comment by dgozman** [comment]
@k4mmm I'd recommend to look at the "Network" tab in the trace: there are 11 network requests, perhaps some of them fail?

**Comment by k4mmm** [comment]
@dgozman i checked it. Here are the queries when not working properly:
![Знімок екрана 2022-12-29 о 08 20 12](https://user-images.githubusercontent.com/76705143/209912544-488d86cb-fff7-45ba-93d0-90f0af8d5a5c.png)

and when everything is right:
![Знімок екрана 2022-12-29 о 08 26 09](https://user-images.githubusercontent.com/76705143/209912591-cef65d4b-5bb0-4227-a334-de9ea24bb08e.png)

**Comment by dgozman** [comment]
@k4mmm There is indeed a difference. Unfortunately, I cannot debug this issue for you by looking at these screenshots. I'd recommend poking around, perhaps there are some console errors, or one of the network requests has a different content? You definitely know better what could go wrong in your web app.

**Comment by k4mmm** [comment]
@dgozman I already checked it. I didn’t find anything ((. As if some requests just don’t start. The console has no errors. When starting the test locally, everything is in order. When starting on gitlab, the test fails.

**Comment by mxschmitt** [comment]
I tried to write a test which does just `page.goto("https://mrecords.me")` an it was working for me. You can try setting `DEBUG=pw:api,pw:protocol` env var during test execution to find out more about what is actually happening. Feel free to attach the logs to the issue then we can take a look. Most likely it has something to do with the network connection to the site, or they are blocking you maybe as well.

**Comment by mxschmitt** [comment]
Closing as per above since we were not able to repro and this is a network issue.
