### ISSUE TITLE
[Question]: Where we can find the total execution time taken to execute the TCs in the default report?

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#19769]
[Question]: Where we can find the total execution time taken to execute the TCs in the default report?
Means, suppose I have 10 spec files (test folder file which contains the describe block) and each spec file contains some N number to TCs, currently Playwright is displaying the Total Time Taken by each spec file to execute the respective N number of TCs. **But how we can find the total time taken by Playwright to execute all 10spec files?**

**NOTE:** Currently I am using the default report which Playwright generates by-default.

**Comment by aslushnikov** [comment]
@AkkyLohana90 do I read it correctly that you're missing total execution time in the HTML report?

**Comment by AkkyLohana90** [comment]
Hi aslushnikov,

Yes, I am looking for total execution time in the HTML report.
And, ok will wait for next version.
Thanks!
