### ISSUE TITLE
Reuse authentication with storageState.json file

### ISSUE THREAD

**Issue by EdmaMahesh** [microsoft/playwright#19767]
Hi Team,
I automated the reuse authentication with globalSetup.
However, while launching the page.goto('/') with the storageState.json file it might not picking the localStorage and hence it is not logging till the localStorage.

**Scenario of authentication**
Our application first navigate to Auth0 login and after entering the login details it redirect back to application and lands on selecting centre and workarea.  After selecting those and click on continue. Then it lands on our actual application functionality.

**Comment by aslushnikov** [comment]
> However, while launching the page.goto('/') with the storageState.json file it might not picking the localStorage and hence it is not logging till the localStorage.

@EdmaMahesh local storage is stored in the `storageState.json` file, so it should work. Could you please re-file with a reproduction steps so that we can try it and reproduce locally?

**Comment by saewitz** [comment]
Potentially related to #2795
