### ISSUE TITLE
[Question] Special Browser dialog is not found to work (Attached inline image for reference)

### ISSUE THREAD

**Issue by ajinkya201991** [microsoft/playwright#19777]
http://autopract.com/selenium/alert5/
In above url, there are 3 types of dialog boxes supported by playwright : 
Alert, Confirmation and Prompt

Attached image (browser_special_dialog_handling.png) is closest to confirmation type dialog box, but not able to be working with playwright api.

Please find below code used for dialog handling : 

page.on('dialog', dialog => {
    console.log("*****Dialog type:", dialog.type())
    dialog.accept()
});
await ElementHandle.click();

![browser_special_dialog_handling](https://user-images.githubusercontent.com/89912651/209941875-86f98278-015e-4cb8-b164-3a4d07a8b3b3.png)

Can you please provide any support or guidance over this.
We need to handle windows dialog further after selecting the option (Open *** .exe ) over that dialog

**Comment by aslushnikov** [comment]
@ajinkya201991 these dialogs are not part of web platform and are not supported by playwright; this on screenshot looks like an "external protocol handler".

Could you please share further your scenario? What do you test? What makes this dialog appear?

**Comment by ajinkya201991** [comment]
As you mentioned its a external handler, we just confirmed it for our workflow ( attached image : external_handler.png). If not playwright, can you please suggest any other npm or web package to handle this ?

Workflow : 
<img width="661" alt="external_handler" src="https://user-images.githubusercontent.com/89912651/210205688-a6b8f9dd-9de8-4e73-a690-97f5d57e99d0.png">

Please find below details as mentioned : 

1. Click on graphical canvas triggers an extenal protocol handler
2. This would launch a windows exeuctable : abc.exe
3. Further to it, a windows based username and password prompt appears to further launch a executable for desktop application : product.exe

What do you test? 
Clicking on graphical canvas with image thumbnail, making changes through windows based application launched by external handler and to further validate the image thumbnail again.


What makes this dialog appear?
Click on graphical canvas or button controls

**Comment by mxschmitt** [comment]
Will fold the feature request into https://github.com/microsoft/playwright/issues/11014.

In it is a workaround for Chrome.
