### ISSUE TITLE
[BUG]context tracing start and stop not working when we use it with in for loop

### ISSUE THREAD

**Issue by EdmaMahesh** [microsoft/playwright#19772]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: v16.16.0
- Browser: Chromium
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { chromium, FullConfig } from '@playwright/test';
async function globalSetup(config: FullConfig) {
    console.log('------STARTED EXECUTING GLOBALSETUP-------');
    const userNames: string[] = ['xxxx', 'xxxx', 'xxxx', 'xxxx'];
    const { baseURL } = config.projects[0].use;

    for (const username of userNames) {
        const browser = await chromium.launch();
        const context = await browser.newContext();
        const page = await browser.newPage();
        try {
            await context.tracing.start({ screenshots: true, snapshots: true });
            await page.goto(baseURL!, { waitUntil: 'networkidle' });
            await page.getByPlaceholder('Username / Email').fill(username);
            await page.getByPlaceholder('Password').fill('password');
            await page.getByText('Log In', { exact: true }).click();
            await page.waitForURL(baseURL! + '#/');
            await page.context().storageState({ path: username + 'storageState.json' });
            await context.tracing.stop({
                path: './tests/global-setup/'+username+'globalsetup-trace.zip',
            })
            await page.close();
        } catch (error) {
            await context.tracing.stop({
                path: './tests/global-setup/'+username+'globalsetup-trace.zip',
            });
            await page.close();
            throw error;
        }
    }
    console.log('------ENDED EXECUTING GLOBALSETUP-------');
}
export default globalSetup;
```

**Describe the bug**
After executing this global setup, I can see the individual zip files and also the individual storageState json files. I am not facing an issue to login with storageState json file. However, when I drag and drop trace zip files in https://trace.playwright.dev/ I am seeing a blank screen. No tracing logs. 
![image](https://user-images.githubusercontent.com/121600171/209933093-788d8289-a936-4628-8a16-2bb803351223.png)
![image](https://user-images.githubusercontent.com/121600171/209934830-22002a6a-eb69-43d0-93d7-3e99418d619c.png)

Without for loop, for single user it is working fine and able to see the tracing logs.

**Comment by aslushnikov** [comment]
@EdmaMahesh you create a page using the `browser.newPage()` api. This creates a **new** underlying context for page; instead, you should use `context.newPage()` api instead:

```ts
        const browser = await chromium.launch();
        const context = await browser.newContext();
        const page = await context.newPage(); // <<< notice this line!
        try {
          // ...
```

hope this helps!

**Comment by EdmaMahesh** [comment]
Thank you @aslushnikov . I should create new page with context instead of browser.
