### ISSUE TITLE
[Question] Did this bad URL Error occur properly ?

### ISSUE THREAD

**Issue by wlx200510** [microsoft/playwright#19775]
I use playwright to auto test my page locally，but when I use page.goto() it shows error as below:
    page.goto: bad URL
    =========================== logs ===========================
    navigating to "https://local.example.cc:3000/oversea-cashier.html", waiting until "networkidle"
    ============================================================
    
as I mention above, the 'local.example.cc' is a fake host that map in my local computer,  just as   local.example.cc  127.0.0.1
and I can open the page if replace host with localhost (https://localhost:3000/oversea-casher.html).
And the page(https://local.example.cc:3000/oversea-cashier.html) can be open via my local chrome browser.
(I need use local.example.cc to take cookie interaction with backend )

**Comment by wlx200510** [comment]
I resolved: replace local with dev or other string, it will be OK 
likes a bug

**Comment by aslushnikov** [comment]
(closing since this seems to be resolved)
