### ISSUE TITLE
[BUG] - fulfill({headers}) - The headers object is not passed to the response

### ISSUE THREAD

**Issue by luanvpereira** [microsoft/playwright#19788]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Ubuntu 22.04.1 LTS
- Node.js version: 16.15.1
- Browser: Chromium (it also happens in firefox)

**Code snippet**

```
  await context.route('**/auth/login', async (route) => {
    route.fulfill({
      status: 200,
      body: JSON.stringify(user),
      headers: {
        'x-auth-token': 'test token',
      },
    })
  })
```

**Bug:**
The network tab shows the correct header I put in the test, but in the response not.

**network tab:**
![Screenshot from 2022-12-29 15-24-50](https://user-images.githubusercontent.com/5252552/209993962-affc3c09-a8e5-487c-8a29-76f7fee8e7e1.png)

**log:**
![Screenshot from 2022-12-29 15-11-36](https://user-images.githubusercontent.com/5252552/209992584-cf8d22a5-f591-46e1-b1d3-b57d3bed28de.png)

**Comment by aslushnikov** [comment]
> The network tab shows the correct header I put in the test, but in the response not.

@luanvpereira what response are we talking about? For example, the following snippet correctly showed response headers for me:

```ts
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
const context = await browser.newContext();
await context.route('**/*', route => {
  route.fulfill({
    status: 200,
    body: '',
    headers: {
      'x-auth-token': 'test token',
    },
  });
});
const page = await context.newPage();
page.on('response', response => console.log(response.headers()));
await page.goto('https://example.com');
await browser.close();
```

**Comment by luanvpereira** [comment]
@aslushnikov The log in the terminal here is ok too... the problem is inside the browser, in the axios response, that returns only `{content-length: '2192'}`. The response **status** and **body** are returning correctly in the browser, but when the app code runs, it can't get the 
**x-auth-token** header for some reason.

**Comment by luanvpereira** [comment]
https://user-images.githubusercontent.com/5252552/210121416-8df687ac-5ae7-49fd-b0a1-9c484209ad5f.mp4

**Comment by aslushnikov** [comment]
> The response status and body are returning correctly in the browser, but when the app code runs, it can't get the
x-auth-token header for some reason.

@luanvpereira I'm afraid something's wrong with the application code. I'll have to close this since Playwright works perfectly, and thus there's no action required from the Playwright team!

**Comment by luanvpereira** [comment]
Did you see the video?!

**Comment by macrouch** [comment]
I'm seeing the same problem trying to set headers in route.fulfill. The headers I am setting in my test code are definitely not making it into the the response the browser gets, so it is not making it into my application code.

**Comment by YohanSciubukgian** [comment]
@aslushnikov We faced the same issue while testing with a browser bundled with Playwright.
We found a workaround by making it works using a browser pre-installed locally using the [browserType.executablePath();](https://playwright.dev/docs/api/class-browsertype#browser-type-executable-path) feature. 
Could it be fixed for browsers bundled in Playwright?

**Comment by Silverium** [comment]
YAY! I found out what is wrong with our approach. We are not exposing the headers!!!

While headers are visible within Playwright tests (because they are on the same server), once we want to see the headers in our app in the browser, we are actually in a `CORS` situation, in which we will only be able to see the exposed headers  from the Playwright server (the mock acts like an external server)

So, given I want to implement a mock route returning a status 429 with a `retry-after` header, this is how the mock request should look:
```js
        await page.route(
          worksSearchFirstExpression,
          route => {
            route.fulfill({
              status: 429,
              headers: {
                'access-control-expose-headers': 'retry-after',
                'retry-after': '1',
              },
            });
          },
          { times: 3 },
        );
```

Then, in the client side, I will be able to see the exposed header `retry-after`.
🥳 🎉

**Comment by Coupa-Nathan** [comment]
> YAY! I found out what is wrong with our approach. We are not exposing the headers!!!
> 
> While headers are visible within Playwright tests (because they are on the same server), once we want to see the headers in our app in the browser, we are actually in a `CORS` situation, in which we will only be able to see the exposed headers from the Playwright server (the mock acts like an external server)
> 
> So, given I want to implement a mock route returning a status 429 with a `retry-after` header, this is how the mock request should look:
> 
> ```js
>         await page.route(
>           worksSearchFirstExpression,
>           route => {
>             route.fulfill({
>               status: 429,
>               headers: {
>                 'access-control-expose-headers': 'retry-after',
>                 'retry-after': '1',
>               },
>             });
>           },
>           { times: 3 },
>         );
> ```
> 
> Then, in the client side, I will be able to see the exposed header `retry-after`. 🥳 🎉

Thank you!! This was the magic we needed. You probably just saved us days of debugging.
