### ISSUE TITLE
[BUG] JSON Reporter - Reporter will not create a new reporting file on Windows

### ISSUE THREAD

**Issue by boutchersj** [microsoft/playwright#19782]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Windows
- Node.js version: 16.15.1
- Browser: Electron app
- Extra: This bug doesn't occur on Mac. I'm developing the same project on both Mac & PC.

**Code Snippet**

```typescript
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: 'tests',
  testIgnore: 'german',
  snapshotPathTemplate: '{testDir}/__screenshots__/{testFilePath}/{arg}{ext}',
  use: {
    screenshot: {
      mode: 'on',
      fullPage: true
    }
  },
  timeout: 50000,
  projects: [
    {
      name: 'Smoke',
      testDir: 'tests/smoke',
      retries: 0
    },
    {
      name: 'Errors',
      testDir: 'tests/error_states',
      retries: 0
    }
  ],
  retries: 0,
  workers: 1,
  reporter: [
    ['list'],
    ['json', { outputFile: `test-results/test-results-${new Date().toISOString()}.json` }]
  ]
};
export default config;
```

**Describe the bug**

When the test ends on Mac, if the output directory or output file doesn't exist yet, it is created, and the report file is placed within it. On Windows, if the directory or file doesn't exist yet, the reporter will error out with:

```
Error in reporter Error: ENOENT: no such file or directory, open 'C:\Users\sboutcher\Desktop\TSM-Playwright\test-results-2022-12-29T15:47:06.051Z.json'
    at Object.openSync (node:fs:600:3)
    at Object.writeFileSync (node:fs:2221:35)
    at outputReport (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\reporters\json.js:213:17)
    at JSONReporter.onEnd (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\reporters\json.js:53:5)
    at C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\reporters\multiplexer.js:64:115
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Multiplexer.onEnd (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\reporters\multiplexer.js:62:45)
    at Runner.runAllTests (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\runner.js:149:5)
    at runTests (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\cli.js:165:18)
    at Gi.<anonymous> (C:\Users\sboutcher\Desktop\TSM-Playwright\node_modules\@playwright\test\lib\cli.js:71:7) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:\\Users\\sboutcher\\Desktop\\TSM-Playwright\\test-results-2022-12-29T15:47:06.051Z.json'
}
```

**Suggested Fix**

Mimic the behavior on Mac. Check if the directory exists, and if not, create it. Check if a file with the same name exists, and if not, create it. Write to the newly created report file or write to the existing file that has the desired file name.

**Comment by pavelfeldman** [comment]
You are putting your report into test-results, which matches the default folder for the output artifacts that Playwright test controls (erases and creates). So your settings for json and for output artifacts clash. Move the output into a separate folder.

**Comment by boutchersj** [comment]
> 

Thanks, @pavelfeldman! I'll give this a try today and let you know the result.

**Comment by boutchersj** [comment]
> h

Alrighty, @pavelfeldman, I think I've found the issue. I can get the results to print to a JSON file in a folder with any name. The true difference between my Mac and Windows machines seems to be how file & directory names are handled when they include a Date string.

On Mac, I seem to be able to create a new file using "test-results/test-results-**${new Date().toISOString()}**.json` }".
On Windows, the error suggests the file with this date string name is not created in time for it to be written to. It is possible, however, to create & write to a file with a name like "results.json".

**Comment by mxschmitt** [comment]
`toISOString` will return the date with colons `:` which is not not allowed to be put in a file name on Windows (limitation by the operating system). You can e.g. do:

`new Date().toISOString().replaceAll(":", "-")}`

which would work.

The error above is thrown by Node.js, so if you think the error should be more clear, I would reach out to them.

Closing by that.

**Comment by boutchersj** [comment]
> 

Woah, I had no idea lol Thanks for teaching me something new today, @mxschmitt!

**Comment by boutchersj** [comment]
Specifically, this is what I ended up going with:

```new Date().toISOString().replace(/:/g, '_')```

I couldn't get my TS compiler to agree with "replaceAll" since it requires es2021. But I'll probably switch it later when I finish migrating the project to TypeScript.
