### ISSUE TITLE
[Feature] page.pause() to return generated code instead of void

### ISSUE THREAD

**Issue by ovidubya** [microsoft/playwright#19793]
Is it possible for `page.pause()` to return the recorded actions that the user takes? right now according to the documentation it returns `Promise<void>`.

## Primary use case:
We want to speed up the test creation so that developers can run a single a script to login to our application and write automated tests. 

Here is how it can be used:
```js

const testFilePath = '/test/zelle/sendTransaction/sendTransaction';

async function main() {
    const browser = await chromium.launch({headless: false});
    const context = await browser.newContext();
    const page = await context.newPage();

    await loginWithMFA(page, testUser, testPassword);
    
    const autoGeneratedTest = await page.pause();
    
    writeFileSync(testFilePath, autoGeneratedTest, 'utf-8');
}
main()
```

**Comment by aslushnikov** [comment]
> We want to speed up the test creation so that developers can run a single a script to login to our application and write automated tests.

@ovidubya we recently released a new "record at cursor" functionality in our VSCode extension. 

Here's a video demo: https://www.youtube.com/watch?v=tVSq-0n-TY4&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=2&t=33s

It is supposed to help with this particular usecase; could you please give it a try and see if it works for you?

**Comment by mxschmitt** [comment]
Looks stale and answered, please re-file if you have more questions.
