### ISSUE TITLE
[Feature] Create script file to downlaod browser on Linux/Ios machine

### ISSUE THREAD

**Issue by ShaharM7** [microsoft/playwright#19809]
This is like creating playwright.ps1 just for Linux/Ios machine
I feel that using playwright.ps1 is not a best practice when using, for example, the GitHub actions ci process and I used their ubuntu machine with the latest version.
Or maybe something like gradlew or mavenw with configuration and so one.

**Comment by pavelfeldman** [comment]
Please explain what you are trying to do, steps that you perform, your expectations and the outcome.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
