### ISSUE TITLE
[asserting on inner text with &nbsp (non breaking spaces character)]

### ISSUE THREAD

**Issue by dhwani07** [microsoft/playwright#19800]
I am trying to assert on inner text with some &nbsp characters however unable to use either expect (toBe) or toContain and get the below error. How do I resolve this?

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/56876259/210077339-f0ec15b5-b900-4f0e-8390-c1879c700543.png">

This is how the structure looks like
<img width="867" alt="image" src="https://user-images.githubusercontent.com/56876259/210077429-7e9e80f5-6317-4c13-895c-d8060b3f9f22.png">

My test:
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/56876259/210077505-1a9c92c0-c2ba-4580-8605-d23da017f822.png">

**Comment by ltsuda** [comment]
Please, for now, see if something like this would work for you.

https://github.com/microsoft/playwright/issues/17625#issuecomment-1266242203

**Comment by dhwani07** [comment]
Thank you it does work :)

**Comment by aslushnikov** [comment]
Closing as per https://github.com/microsoft/playwright/issues/19800#issuecomment-1367946721 !
