### ISSUE TITLE
[Question] Is it possible to Install Playwright for vscode without using the extensions tab or the marketplace ?

### ISSUE THREAD

**Issue by ambujsahu81** [microsoft/playwright#19802]
Issue : - The Visual Studio Marketplace is not available from the vscode open source builds. 
Reference : -  [Extension need to be installed using **Install from VSIX** ](https://github.com/microsoft/vscode/wiki/How-to-Contribute#extensions)

Are there any docs or helpful resource on how to clone and build the playwright extension locally ?

**Comment by ltsuda** [comment]
I'm not sure about the correct steps but


The official Playwright for VSCode repo is https://github.com/microsoft/playwright-vscode

And I think to generate the VSIX to manually install later could be this step:
https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce

**Comment by ambujsahu81** [comment]
> I'm not sure about the correct steps but
> 
> The official Playwright for VSCode repo is https://github.com/microsoft/playwright-vscode
> 
> And I think to generate the VSIX to manually install later could be this step: https://code.visualstudio.com/api/working-with-extensions/publishing-extension#vsce

Thanks for the input 🙂.

**Comment by ambujsahu81** [comment]
I was able to download vsix from [Playwright Test for VSCode](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) and it worked with vscode open source builds. . May be it will good if this method of installing extension is also added to official docs.
