### ISSUE TITLE
[Feature] select `diff` by default when it's available

### ISSUE THREAD

**Issue by chenxsan** [microsoft/playwright#19803]
When using html-reporter for visual testing, I would love to check `diff` view first when it's available,

<img width="655" alt="" src="https://user-images.githubusercontent.com/1091472/210092734-031faa69-4cd2-42c2-93df-1e0593d6b509.png">

Which means I can tell the difference between Actual and Expected at the first sight. Selecting Actual in the beginning isn't helpful IMO.

Let me know if you would accept a pull request for it.

**Comment by aslushnikov** [comment]
This looks reasonable to me. Feel free to submit a PR!
