### ISSUE TITLE
[Question]  Auto-wait for element didn't work stable after my search issue?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19805]
My **searchOfValue** method(base.ts) writes the letters of a word one by one to the search field. The reason I do this is because the search query goes for each letter on the backend and the item in the list is listed according to the query. But when using this method, it writes the first letter then deletes the first letter instead of typing the second letter. The letters should write one by one and wait network request for each typed letter.My problem is related to waiting.Read document, tried lots of thing but taking same error again.How can I solve this? By the way I don't want to use below logic.Because there was a static delay.
`this.searchTxt.type(c,{delay:50})`

My code is below;

**this is seach field selector;**
`//span[contains(@class,'search-input')]/input`

**my base.ts**

```
import { Locator, Page } from "@playwright/test";

export class BasePage {
  page: Page;
  searchTxt: Locator;

  constructor(page: Page) {
    this.page = page;
    this.searchTxt = page.locator("//span[contains(@class,'search-input')]/input");

  }

  async searchOfValue(value:string) {
   await this.page.waitForSelector("//span[contains(@class,'search-input')]/input", {state:'attached' })
    for (let i = 0; i < value.length; i++) {
      let c = value.charAt(i);
      await Promise.all([
         this.searchTxt.type(c),
         this.page.waitForLoadState('load')
      ])
    }
  }

  } 
```

**my test.ts file**
```
import { test, expect } = require('@playwright/test');
import { faker } from '@faker-js/faker';
test.beforeEach(async({page}) => {
  basePage = new BasePage(page)
})

test('test1', async ({ page }) => {
                let fakeName = `${faker.name.firstName()}${faker.datatype.number()}${faker.lorem.word()}`
                await flowPage.addBtnOnChannel.click()
                await basePage.searchOfValue(fakeName)
                await expect(flowPage.flowCard).toHaveCount(1);
});
```

**This is the table html structure before search**

```
<tbody class="ant-table-tbody">
     <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">1</td>
        <td class="">"Yusuf"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">2</td>
        <td class="">"Geo"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">3</td>
        <td class="">"Hrl"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">4</td>
        <td class="">"Abl"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">5</td>
        <td class="">"GB"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">6</td>
        <td class="">"GH"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">7</td>
        <td class="">"HY"</td>
   <tr class="ant-table-row ant-table-row-level-0" >
        <td class="">8</td>
        <td class="">"REO"</td>
<tr class="ant-table-row ant-table-row-level-0" >
        <td class="">9</td>
        <td class="">"NEO"</td>
<tr class="ant-table-row ant-table-row-level-0" >
        <td class="">10</td>
        <td class="">"FRG"</td>
```

The error I get some times is as follows;

```
 Error: expect(received).toHaveCount(expected) // deep equality

    Expected: 1
    Received: 10
    Call log:
      - expect.toHaveCount with timeout 30000ms
      - waiting for locator('.flow-card:not(.empty)')
      -   locator resolved to 10 elements
      -   unexpected value "10"
      - waiting for locator('.flow-card:not(.empty)')
      -   locator resolved to 10 elements
      -   unexpected value "10"
      -   locator resolved to 10 elements
      -   unexpected value "10"
      -   locator resolved to 10 elements
      -   unexpected value "10"
      -   locator resolved to 10 elements
      -   unexpected value "10"
      -   locator resolved to 0 elements


       at playwright/tests/test.ts:77


      76 |                 await basePage.searchOfValue(fakeName)
    > 77 |                 await expect(flowPage.flowCard).toHaveCount(1)
         |                                                 ^
   

```

If the search is done fully, a single row will come and I will have verified it. I asked stackoverflow but didn't get response,searched and tried lots of thing. **This question may be a general one, but I have no choice to ask you.**

**Comment by aslushnikov** [comment]
> My problem is related to waiting.Read document, tried lots of thing but taking same error again.How can I solve this?

@YusufOzt answering particular question - you should use the [`page.waitForRequest()`](https://playwright.dev/docs/next/api/class-page#page-wait-for-request) method to wait for the request to be sent to the backend after you typed each letter. Note though that you'll need to figure out which request is sent to the server as the typing happens.

On a more general note, I'm not sure why would you want to type things letter-by-letter and wait for the request? Looking at the test, it looks like it validates that there's a proper suggest box after the whole value is typed, so waiting for intermediate suggestions should not be needed.
