### ISSUE TITLE
[Question] Infinite loop when encountering bot/ddos protection (like cloudflare) in headful chromium mode?

### ISSUE THREAD

**Issue by puyebu** [microsoft/playwright#19804]
I am trying to figure out why I cannot pass the protection in headful mode, after completing the captcha (if it shows) it seemingly tries to redirect me to the target page but instead it loops back to the protection page. If it doesn't show captcha, it just loops.
Such issue is only encountered on Chromium, other available browsers do not encounter the issue.
I couldn't find any mention of such issue anywhere.
Is it something Chromium specific or some setting or argument needs to be modified?

The code I used:
```
using var playwright = await Playwright.CreateAsync();
BrowserTypeLaunchOptions launchOptions = new();
launchOptions.Headless = false;
await using var browser = await playwright.Chromium.LaunchAsync(launchOptions);
var page = await browser.NewPageAsync();
await page.GotoAsync("https://www.fanfiction.net/"); //or any other protected website
await page.WaitForTimeoutAsync(60000);
return await page.ScreenshotAsync(new()
{
    Path = "screenshot.png",
    FullPage = true
});
```

**Comment by aslushnikov** [comment]
> I am trying to figure out why I cannot pass the protection in headful mode, after completing the captcha (if it shows) it seemingly tries to redirect me to the target page but instead it loops back to the protection page.

The bot evasion techniques are falling outside of the scope of the project, so I'll have to close this.
