### ISSUE TITLE
[BUG] setting a cookie in playwright but unable to retrieve it in application

### ISSUE THREAD

**Issue by alilland** [microsoft/playwright#19810]
**Context:**
- Playwright Version: 1.29.1
- Operating System: 16-inch, 2019 Macbook Pro - 2.4 GHz 8-Core Intel Core i9
- Node.js version: v16.15.0
- Browser: 
  - Mobile Safari - iPad (gen 7) landscape 
  - Microsoft Edge
  - Google Chrome

in my playwright test im setting a cookie in the browser context like this:

```javascript
test.beforeEach(async ({ page, browser }) => {
  const context = await browser.newContext()
  await context.addCookies([
    {
      name: AUTHTKN,
      value: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1NDUyMzh9.AN93Ms3qkL_mkY2_bF_-mI3MvhXVKbrsV4BRPLLF5hs',
      domain: 'localhost',
      path: '/',
      expires: 90 * 86400 // 90 days as seconds
    }
  ])

  const cookies = await context.cookies()
  console.log(JSON.stringify(cookies, null, 2))

  await page.goto('/')
})
```

using console.log i can see the output

I suspect this is an issue caused by playwright which seems to automatically inject `sameSite`, but not sure since this is a representation of the cookie and I have no ability (that i know of) how I could view it in browser to be sure
```javascript
[
  {
    "name": "AUTHTKN",
    "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1NDUyMzh9.AN93Ms3qkL_mkY2_bF_-mI3MvhXVKbrsV4BRPLLF5hs",
    "domain": "localhost",
    "path": "/",
    "expires": 7776000,
    "httpOnly": false,
    "secure": false,
    "sameSite": "Lax"
  }
]
```

in my application code, it fails to find the cookie, I load cookies from memory like this
```javascript
const getAll = () => {
  const pairs = document.cookie.split(';')
  const cookies = {}
  for (let i = 0; i < pairs.length; i++) {
    var pair = pairs[i].split('=')
    cookies[(pair[0] + '').trim()] = unescape(pair.slice(1).join('='))
  }
  return cookies
}

getAll()['AUTHTKN']
// => undefined
```

within my app in real scenarios, i can set the cookie in my application goes like this, and when done this way my app can find the cookie, but mocking it within playwright is whats not seeming to work
```javascript
const set = (key, value, seconds, domain) => {
  // ...
  let string = `${key}=${value}`
  if (seconds) string += `; max-age=${seconds}`
  if (domain) string += `; domain=${domain}`
  string += `; path=/`
  document.cookie = string
}
const NINETYDAYSASSECONDS = 90 * 86400
cont token = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1NDUyMzh9.AN93Ms3qkL_mkY2_bF_-mI3MvhXVKbrsV4BRPLLF5hs'
set('AUTHTKN', token, NINETYDAYSASSECONDS, null)
getAll()['AUTHTKN']
// => 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI1NDUyMzh9.AN93Ms3qkL_mkY2_bF_-mI3MvhXVKbrsV4BRPLLF5hs'
```

I believe it has something to do with the domain as the issue or sameSite, but cant be sure

**Comment by pavelfeldman** [comment]
The cookie is not being set in the correct context: In your test code, you are setting the cookie in a new context using browser.newContext(). However, when you try to access the cookie in your application code, you are doing so from the test-specific context. Replace your before hook with:

```js
test.beforeEach(async ({ context, browser }) {
    await context.addCookies([...]);
}
```

**Comment by alilland** [comment]
doesnt seem to be working out, that opens up a new problem

```javascript
test.beforeEach(async ({ page, context }) => {
  await context.addCookies([
    {
      name: 'AUTHTkN',
      value: '...',
      domain: 'localhost',
      path: '/',
      expires: 90 * 86400
    }
  ])
 const cookies = await context.cookies()
 console.log(JSON.stringify(cookies, null, 2))
 // => []
})
```

**Comment by pavelfeldman** [comment]
- Each test has isolated context instance and you are getting it in the before each hook. beforeEach is 'before each test', so it gets all the test fixtures.
- Your `expires` is Thu, 01 Jan 1970 02:09:36 GMT, it is in the past.

**Comment by alilland** [comment]
I gave it a second try with a unix timestamp and moved everything into the `test`

this gave me a different result, but still nothing in my application code:

```javascript
test.describe('On page load', () => {
  test('let the user through', async ({ page, context }) => {
    await support.login(page, context) // my own custom function 

    const cookies = await context.cookies()
    console.log(JSON.stringify(cookies, null, 2))

    // => [
    //   {
    //     "name": "AUTHTKN",
    //     "value": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI2MjE2NTV9.qDenNcub4WTC2l9YajR8Pq1wYAZSpEo6uAVtHXcFICA",
    //     "domain": "localhost",
    //     "path": "/",
    //     "expires": 1680307655,
    //     "httpOnly": false,
    //     "secure": false,
    //     "sameSite": "Lax"
    //   }
    // ]

    await page.goto('/')

    await page.screenshot(support.screenshot(__dirname, __filename))
  })
})
```

```javascript
async function login (page, context) {
  console.time('login')
  page.on('console', msg => console.log(msg.text()))

  const mockExp = moment().add(24, 'hours')
  const mockTokenParams = {
    exp: mockExp.unix()
  }

  const mockToken = jwt(mockTokenParams, '1234567890')

  // Add cookies to the browserContext
  await context.addCookies([
    {
      name: 'AUTHTKN',
      value: mockToken,
      domain: 'localhost',
      path: '/',
      expires: moment().add(90, 'days').unix()
      // sameSite: 'None'
    }
  ])
  console.timeEnd('login')
}

module.exports = login
```

**Comment by pavelfeldman** [comment]
Works for me!

```js
test('cookie', async ({ context, page }) => {
  // Set cookies
  await context.addCookies([
    {
      name: 'AUTHTkN',
      value: 'value',
      domain: 'localhost',
      path: '/',
      expires: Date.now()  / 1000 + 100000,
    }
  ]);
  // I simulate empty response from server.
  await page.route('http://localhost:8080/*', route => {
    route.fulfill({ body: '<html></html>' }).catch(() => {});
  });

  // Navigate
  await page.goto('http://localhost:8080');
  const cookie = await page.evaluate(() => {
    return document.cookie;
  })
  console.log(cookie);
});
```

**Comment by alilland** [comment]
I promise im not lying, your test runs successfully - but its not working with my React v16 app
<img width="1792" alt="Screenshot 2022-12-31 at 10 32 33 PM" src="https://user-images.githubusercontent.com/14061357/210162875-c8a1cc04-10a2-428f-8c46-5918be75ff2e.png">

**Comment by alilland** [comment]
been doing more research with other UI frameworks on my dev environment

cookies seem to work with React v18
works with VueJS v2.6.10
as well as another old app, AngularJS v1.7.9

so whatever the issue, this is a bug within React v16

**Comment by luanvpereira** [comment]
I'm having the same problem and I'm using react v18 :/ 

It seems that playwright is unable to write cookies in the context of the browser.

**Comment by alilland** [comment]
@luanvpereira  have you checked that there are no functions in your codebase deleting cookies when the app loads?

**Comment by mxschmitt** [comment]
I tried to reproduce as well, but unfortunately for me it was working as expected.

Can someone create a minimal repro in form of a GitHub repository which we can clone / npm ci and run the tests? Happy to dig into it then!

**Comment by alilland** [comment]
@mxschmitt identified the issue, not PW related, a hidden function clearing browser cookies from legacy code that got exposed by PW, PW testing doing its job 👍

**Comment by AyoubXwire** [comment]
If anyone is struggling with this problem, my case could be helpful, took me a whole night to figure out:

I was navigating to my website using `127.0.0.1:3000` but I was setting the cookie domain to `localhost:3000 `which was causing a problem.

The solution was to set baseURL in my playwright config file to `http://localhost:3000`

Make sure that you are using the same domain in your cookie as the domain you are using to access your website.

**Comment by neobats** [comment]
Replying here after a year to say @AyoubXwire, your suggestion was spot on, thank you for noticing that! I spent hours troubleshooting everything else, and didn't think that 127.0.0.1 vs localhost would make a difference on whether the cookie was being sent on subsequent requests to the server, but it did. Changing (what I believe is the default ) baseURL from `127.0.0.1` to `localhost` worked for me, since that's what was referenced in my api where the cookie was being set.
