### ISSUE TITLE
[BUG]Reuse authentication with storageState.json file

### ISSUE THREAD

**Issue by EdmaMahesh** [microsoft/playwright#19822]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Windows
- Node.js version: v16.16.0
- Browser:  Chromium
- Extra: 

**Code Snippet**

```import { chromium, FullConfig } from '@playwright/test';
async function globalSetup(config: FullConfig) {
  console.log('------STARTED EXECUTING GLOBALSETUP-------');
  const userNames: string[] = ['xxx', 'xxx', 'xxx'];
  const { baseURL } = config.projects[0].use;

  for (const username of userNames) {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    try {
      await context.tracing.start({ screenshots: true, snapshots: true });
      await page.goto(baseURL!, { waitUntil: 'networkidle' });
      await page.getByPlaceholder('Username / Email').fill(username);
      await page.getByPlaceholder('Password').fill('password');
      await page.getByText('Log In', { exact: true }).click();
      await page.waitForURL(baseURL! + '#/');
      await page.waitForSelector('#btnContinue', { timeout: 40000 });
      await page.locator('#btnContinue').click();
      await page.waitForSelector('#userPanelName', { timeout: 40000 });
      await page.context().storageState({ path: './playwright-e2e/global-setup/storageState/' + username + 'storageState.json' });
      await context.tracing.stop({
        path: './playwright-e2e/global-setup/storageTrace/' + username + 'storageTrace.zip',
      })
      await page.close();
    } catch (error) {
      await context.tracing.stop({
        path: './playwright-e2e/global-setup/storageTrace/' + username + 'storageTrace.zip',
      });
      await page.close();
      throw error;
    }
  }
  console.log('------ENDED EXECUTING GLOBALSETUP-------');
}
export default globalSetup;
```

**Describe the bug**

Firstly when we launch the application it asks for username and password
![image](https://user-images.githubusercontent.com/121600171/210224416-2f6a266b-3d69-4257-8800-5a44e80c8b66.png)
Once, we enter username and password and click on Log In button then it navigates to select centre and work area
![image](https://user-images.githubusercontent.com/121600171/210224693-536c6136-f688-4259-995f-85f6490bdc3a.png)
By default there is a Centre and work area selected. We just click on Continue button.

All these steps we are doing in globalSetup file and then storing it in storageState.json file.
In json file we can see the localStorage which as below
![image](https://user-images.githubusercontent.com/121600171/210224979-845db501-cd71-42e8-b442-28176a01a4a4.png)

We using this storageState.json file in test.
![image](https://user-images.githubusercontent.com/121600171/210225585-57340478-e0a4-4e02-bded-512e51a7740b.png)

However, we are not able to launch the application after the continue button clicked. It is again asking for us to select the centre and work area and click on continue button.
Actually, we did this step in global setup. We are expecting to launch the application after the continue button

**Comment by mxschmitt** [comment]
We unfortunately can't predict how your application behaves or what it requires to have a working logic. This means its hard to judge if there is a bug in our or your code. I recommend the following to debug it further:

- compare the localStorage inside your own browser (DevTools) with the generated storageState's localStorage, maybe you directly see that another token is missing
- maybe you need to wait for an element after you logged in, but it seems like you are doing that already

Some general feedback:

- no need to start multiple browsers per each user, you can re-use them and just create a new context instead, will be way faster as well.
- Your current implementation leaks browsers, you want to close the browser and context so it does not stay open via context.close() and browser.close()

**Comment by EdmaMahesh** [comment]
Hi @mxschmitt ,
Thank you for looking into this issue. It will be really great if you further look into my below comments.

**_Regarding - compare the localStorage inside your own browser (DevTools) with the generated storageState's localStorage_**
I have compared the localStorage inside own browser with the generated storageState's localStorage. I can see the same name and values. I have observed that there are few other name and values in broswer but not in file of storageState's localStorage
![image](https://user-images.githubusercontent.com/121600171/210696511-f4fa9065-42b3-46b5-94b4-88839ba80014.png)
![image](https://user-images.githubusercontent.com/121600171/210696296-1558405b-ea68-4f22-b629-ec533d7f1e01.png)
![image](https://user-images.githubusercontent.com/121600171/210696372-85a87dba-1acf-450e-a14b-d97160efb7b1.png)

**_Regarding general feedback_**

I have re-written my code as below. Is this the one you were suggesting.? However, I can't see closing of browser and context in the playwright documentation - https://playwright.dev/docs/next/test-advanced#global-setup-and-teardown
![image](https://user-images.githubusercontent.com/121600171/210697178-9ed909de-deda-4a30-aea6-8a3c06cd5ada.png)
![image](https://user-images.githubusercontent.com/121600171/210697591-6af13305-43a6-4a8c-998d-70bec1fa19fb.png)

**Comment by mxschmitt** [comment]
I'd love to help, but its hard without having an actual repro or access to the application. If you want you can send me more information over Discord (aka.ms/playwright-discord) or mail (`max.schmitt    @` `microsoft`   .   `com`) (I made it look ugly so the spambots don't find it) if this would work for you, then we can take a look.

**Comment by EdmaMahesh** [comment]
Hi @mxschmitt ,
Thank you. Unfortunately at the moment we can't give an access to application. sorry for that.
One thing I have noticed is like - 

- First when we launch URL in browser it re-directs to Auth0 and there we enter username and password and click on login button
- It validates the username and password and re-directs to our URL and lands on selection of Centre and Workare and then click on Continue button.
- Here we have the actual our application functionalities after clicking on continue button
- This is the repeated steps till selection of Centre and Workarea and click on continue button.
- Hence, I have used a globalSetup till the continue button click

I have noticed like - When we reload manually the URL it again asking for selection of Centre and Workarea. Also, when we open 2nd new tab(after login in first tab till continue button clicked) with our application URL it is landing on the selection of Centre and Workarea.

I think this might be an issue with our application behavior instead of playwright issue. 
Is there anyway with playwright to handle this scenarios.?

However, we started developing framework for our application with playwright typescript. It will be really great if you could suggest any safety steps to be considered and also any reference of framework. Thank you.

**Comment by aslushnikov** [comment]
>Also, when we open 2nd new tab(after login in first tab till continue button clicked) with our application URL it is landing on the selection of Centre and Workarea. I think this might be an issue with our application behavior instead of playwright issue.
Is there anyway with playwright to handle this scenarios.?

@EdmaMahesh Again, we can only guess since we don't know exactly what's going on, but in general, Playwright has no problem working with multiple pages: https://playwright.dev/docs/pages#multiple-pages

I'll have to close this since there's not much we can recommend and suggest without understanding what's going on. Feel free to file a new issue if you think we still can be helpful somehow!
