### ISSUE TITLE
[Question] Does Playwright support dependency injection in Typescript?

### ISSUE THREAD

**Issue by dfl2022** [microsoft/playwright#19828]
I want to have the Page Object Model classes being injected in the tests without having to create them explicitly with the new keyword.
If it does not support it natively, can you suggest a compatible DI framework.
Thanks!

**Comment by mxschmitt** [comment]
You an create your POM instance as a fixture, that should work for your use-case: https://playwright.dev/docs/test-fixtures#creating-a-fixture

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale and answered. Please create a new issue with a detailed reproducible or feature request if you still face issues.
