### ISSUE TITLE
HTML Report open option is ignored when running tests from VS Code extension

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#19826]
Hello team,

I'm following-up issue  : https://github.com/microsoft/playwright-vscode/issues/167.

With the same configuration, the html page along with the report is still not being launched automatically though it is well created : 

import { test, expect, PlaywrightTestConfig } from '@playwright/test';

//Activate reporting
const config: PlaywrightTestConfig = {
reporter: [['html',  { open:'always' }]]
};
//export default config

test('homepage has title and links to intro page', async ({ page }) => {
  // GIVEN the Playwright home page is displayed
  await page.goto('https://playwright.dev/');
  // Expect the title to be "Playwright".
  await expect(page).toHaveTitle(/Playwright/);

  // WHEN we click on the the "Get Started button"
  //create a locator
  const getStarted = page.getByRole('link', { name: 'Get started' });
  // Expect an attribute "to be strictly equal" to the value.
  await expect(getStarted).toHaveAttribute('href', '/docs/intro');
  // Click the get started link.
  await getStarted.click();

  // THEN the outcome URL should contain intro.
  await expect(page).toHaveURL(/.*intro/);
});

Same in the config file : 

reporter: [['html',  { open:'always' }]], 

Is there anything else to do or a known loggued defect on your side ?

Thank you very much in advance,

Regards,

Johan

**Comment by mxschmitt** [comment]
This is expected as of today. When using the Visual Studio Code extension, the results of the tests gets surfaced inside the test explorer sidebar in the editor. Other assets like traces, video, screenshot do not get generated. See https://github.com/microsoft/playwright/issues/16958 for the feature requests about integrating it.

What information do you miss or would you like to get shown?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale and answered. Please create a new issue with a detailed reproducible or feature request if you still face issues.
