### ISSUE TITLE
[BUG] Documentation in regards to text selector engine and single and double quotes

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1982]
**Context:**
- Playwright Version: 0.15.0

**Describe the bug**
https://github.com/microsoft/playwright/pull/1952 introduced the concept that both single and double quotes to indicate a text selector. There are a few documentation errors now due to this:

1. https://github.com/microsoft/playwright/blob/master/docs/api.md#working-with-selectors still only mentions double quotes `"`
2. https://github.com/microsoft/playwright/blob/master/docs/selectors.md says:
> Selector surrounded with quotes (either `"` or `'`) is assumed to be `text=selector`. Example: `page.click('"foo"')` is converted to `page.click('text="foo"')`.

This is not correct because of the word `surrounded`. The actual `"` and `'` is part of the selector. aslushnikov explained this here https://github.com/microsoft/playwright/issues/1239#issuecomment-598625270:
> > Your change says:
> > > Selector starting with " is assumed to be text=selector.
> 
> @thernstig I see what you mean and how it might be confusing. The definition is technically correct - double-quotes are a **part of selector**. Let me break down the example that we have in the docs:
> 
> 1. consider `page.click('"foo"')` (notice how there are single-quotes that wrap double-quotes)
> 2. in this case, selector is `"foo"`.
> 3. selector starts with `"`, so it is transformed into the form of `text=selector`
> 4. substituting selector with its value, getting `text="foo"`
> 5. which gets us to `page.click('text="foo"')`
> 
> Does the explanation make things any better?

There are one of two possible ways to fix 2) above.

a) Either to update the docs.
b) Or as can be seen in that same thread, I suggest that `'` and `"` is not included in the conversion. Reason I recommend the latter is due to that https://github.com/microsoft/playwright/issues/1341 made the default for `text=some text` to match case-insensitive, substring matching. Essentially this is what I recommend makes more sense. Example: `page.click('"foo"')` and `page.click("'foo'")` is converted to `page.click('text=foo')`. This will then default to the best default for text selectors.

**Comment by dgozman** [comment]
I am still hesitant to introduce the change proposed in (b). This would make `text` behave differently from `css` and `xpath`, and also break the mental model "quotes mean strict match".

Let me update the docs.
