### ISSUE TITLE
Is there a way to trigger the `onPointerDown` event of an element using Playwright?

### ISSUE THREAD

**Issue by RajaTheKing826** [microsoft/playwright#19823]
Hi @pavelfeldman @aslushnikov 

Is there a way to trigger the `onPointerDown` event of an element using Playwright?

**Comment by mxschmitt** [comment]
You can do it like that:

```js
  await page.goto(`data:text/html,<input type="text" onpointerdown="console.log('pointerdown')">`);
  const locator = page.locator('input');
  const [message] = await Promise.all([
    page.waitForEvent('console'),
    locator.dispatchEvent('pointerdown')
  ]);
  console.log(message.text());
```

Only the [locator.dispatchEvent()](https://playwright.dev/docs/api/class-locator#locator-dispatch-event) is the important piece here, the rest is just setting up a page with an `input` element and waiting for the console message to appear.

**Comment by pavelfeldman** [comment]
Playwright performs real clicks. pointer events are a part of the standard event sequence, so all you need is `page.click()`

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale and answered. Please create a new issue with a detailed reproducible or feature request if you still face issues.
