### ISSUE TITLE
[Feature] Add 'attribute' selector to the list of id, data-testid, ...

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1983]
Currently the attribute selector https://github.com/microsoft/playwright/blob/master/docs/selectors.md#id-data-testid-data-test-id-data-test-and-their-light-counterparts searches for `id, data-testid, data-test-id, data-test and their :light counterparts`.

Would it not make more sense to rename all these to just `attribute`, or at least add `attribute` to the list? API's that are almost self-explanatory by naming conventions are great APIs.

**Comment by pavelfeldman** [comment]
Could you elaborate on how this attribute selector would work and disambiguate with the `css=hello` constructs?

**Comment by thernstig** [comment]
I must have read the docs too quickly. I misunderstood thinking that `id=foo` would translate to `css=[foo]`.
