### ISSUE TITLE
[BUG] Can't run tests on Azure agent "Executable doesn't exist "

### ISSUE THREAD

**Issue by lucasbit** [microsoft/playwright#19837]
**Context:**
- Playwright Version: 1.28.1
- Operating System: Azure self-hosted agent (Windows)
- Node.js version:18.12.1
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
![image](https://user-images.githubusercontent.com/29520131/210366373-44fe1181-d5bd-48bb-b8e5-f1a5f0cf99da.png)
![image](https://user-images.githubusercontent.com/29520131/210365354-2e82c7e9-6755-4c0d-a610-49906300fc5a.png)
![image](https://user-images.githubusercontent.com/29520131/210366657-6c20bf97-2d4a-4369-8e2e-df1056fdb409.png)
![image](https://user-images.githubusercontent.com/29520131/210367865-d7fc6c9a-3bb7-437f-ab7b-51d1e9613e8e.png)
![image](https://user-images.githubusercontent.com/29520131/210368256-62035221-32f6-4cd1-bc48-25f9ed972ef9.png)

**Describe the bug**
Tests are running fine locally, but I pushed repo to Azure DevOps Repos and tried to run them in Azure DevOps Pipelines.
Run fails with info that:

browserType.launch: Executable doesn't exist at C:\Users\tfsbuild\AppData\Local\ms-playwright\chromium-1033\chrome-win\chrome.exe

and:
![image](https://user-images.githubusercontent.com/29520131/210368837-c3fa393f-e88f-46f8-9887-9acf7b443a8b.png)

I'm doing those 3 things:

1. Instaling dependencies by: npm install
2. As advised: running npx playwright install 
3. running tests by: npx playwright test 

But it still complains about Chromium, any tips on how to solve that? 

 
Add any other details about the problem here.

**Comment by mxschmitt** [comment]
You need to run the `npx playwright install` in the same working directory as you have your Playwright project. Currently its skipping installing the browsers, when having the working directory configured it will install the browsers.

**Comment by lucasbit** [comment]
Thank you @mxschmitt, silly mistake on my part. Solve that with:
![image](https://user-images.githubusercontent.com/29520131/210787944-13979f30-3d21-46fb-97de-5dba43ea09a3.png)
