### ISSUE TITLE
[Feature] Add path params to request options

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#19839]
**Desired behavior**
Playwright to support both query and path parameters:

```javascript
const capitalResponse = await request.get('https://restcountries.com/v3.1/name/{name}', {
        pathParams: {
            'name': 'denmark'
        },
        queryParams: {
            'fields': 'capital,languages',
        }
    });
```

Formed url:
```
https://restcountries.com/v3.1/name/denmark?fields=capital,languages
```
This feature will make it easier to move all the test data logic inside the call method itself, rather than forming the url with parameters in a previous step.

**Current behavior:** 
params in the request options are query parameter 
```javascript
const capitalResponse = await request.get('https://restcountries.com/v3.1/name/denmark', {
        params: {
            "fields": 'capital,languages',
        }
    });
```

Formed url:
```
https://restcountries.com/v3.1/name/denmark?fields=capital,languages
```

**Comment by mxschmitt** [comment]
This `https://restcountries.com/v3.1/name/{name}` is not something which is standardized inside the HTTP specification, so we are hesitant adding something opinionated to our http client.

I recommend something like this instead:

```js
const name = 'denmark';
const capitalResponse = await request.get('https://restcountries.com/v3.1/name/${name}', {
        params: {
            "fields": 'capital,languages',
        }
    });
```

**Comment by irharrier2** [comment]
Hi @mxschmitt 

Thank you for taking the time to answer. Please consider these two points:

1. [Path parameters also known as Template parameters](https://www.programsbuzz.com/article/rest-api-parameters-types#:~:text=3.%20Path/Template%20parameters) are commonly used in applications and is standard practice for API. It is not something specific to the public example that I provided.

Other testing tools, for example RESTAssured, supports this out of the box:
```Java
given().
 pathParam("name", "Denmark").
 queryParam("fields", "capital,languages").
when().
 get(RestCountriesEndpoints.COUNTRY_BY_NAME).
then().
 body("[0]", hasKey("capital"));
```

2. Regarding the solution that you provided. It is common in testing that endpoints are read from constants instead of hardcoded strings. 
This means that interpolation, as you suggested is not possible.
Example:
```Javascript
const capitalResponse = await request.get(RestCountriesEndpoints.COUNTRY_BY_NAME, {
        params: {
            "fields": 'capital,languages',
        }
    });
```

This deters me from recommending Playwright as a API testing tool if API testing principles are not possible.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
