### ISSUE TITLE
[BUG] Infinite waiting for resolving waitForLoadState('networkidle')

### ISSUE THREAD

**Issue by gamesterr** [microsoft/playwright#19835]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac
- Node.js version: 16.13.0
- Browser: Chromium

With `waitForLoadState('networkidle')` inside the `Promise.all`, playwright is waiting until timeout even though no request is sent. Noticed it in my app, but I was able to reproduce it with the example page I passed in the code.

**Code Snippet**

```javascript
test('test', async ({ page }) => {
  await page.goto('https://practice.automationtesting.in/');
  await Promise.all([page.waitForLoadState('networkidle')]);
  await page.waitForTimeout(5000);
});
```

**Comment by lyatziv** [comment]
This may just be an implementation issue, consider the following change to the code.

```
test('test', async ({ page }) => {
  await Promise.all([
    page.waitForLoadState('networkidle'),
    page.goto('https://practice.automationtesting.in/')
  ]);
  await page.waitForTimeout(5000);
});
```

**Comment by mxschmitt** [comment]
I tried to run your code and for me it works as expected.

**Comment by mxschmitt** [comment]
Closing since it seems stale and we were not able to reproduce. Please re-file with more information aka. logs which you can set when setting the `DEBUG=pw:api,pw:protocol` env var.

**Comment by peterholcomb** [comment]
FWIW, we are also seeing this in 1.29.2 but were not seeing it in 1.27.1.  In some tests, the `waitLoadState('networkidle')` seems to never return

**Comment by tonai** [comment]
Also ran into issues with `waitLoadState('networkidle')` not being fired (using 1.30.0).
But When I run chromium not in headless mode, open the devtools, check the network, then in that case `waitLoadState('networkidle')` is fired as expected.

**Comment by mxschmitt** [comment]
Feel free to file a bug report with a repro, happy to take a look then.

**Comment by rihaskh** [comment]
Still the issue with page.waitForLoadState('networkidle')

**Comment by rihaskh** [comment]
and related this my code , 

await Promise.all([
    this.page.waitForLoadState('domcontentloaded'),
     this.page.waitForLoadState(),
    this.page.waitForResponse(response => response.url().includes('/currentstatuses'), { timeout: 95000 }),
    this.page.locator("//button[.='Update']").click(),
    
  ]); works well in debugging but when i ran whole script it throws error and close the browser

**Comment by kwiniarski97** [comment]
Is there any solution for it? 
I tried to migrate `page.waitForLoadState('networkidle')` with other ways to tell if a given page, or action has ended, but there are simply some things that must use it.

**Comment by creichlin** [comment]
in my case
page.waitForLoadState('networkidle')
hangs forever, but only if my api endpoints set the header
Cache-control=no-store
I have not found out yet why this happens, might be custom to my setup.

**Comment by taschik** [comment]
@creichlin have you ever found out the reason and a potential fix for your problem?

**Comment by tgrisley** [comment]
Also seem to be getting this on some pages on playwright version `1.40.1`

Page seems to load successfully but networkidle never resolves and ends up timing out.

<img width="422" alt="Screenshot 2024-01-12 at 11 27 52" src="https://github.com/microsoft/playwright/assets/126177701/ffd64ce6-7f81-40c4-b1f2-a110aac10590">

<img width="642" alt="Screenshot 2024-01-12 at 11 28 40" src="https://github.com/microsoft/playwright/assets/126177701/b5a23bf3-c3f8-4086-9230-6eaf9a134d7f">

Will see if i can put together a simple repro


Will see if i can put together a repro

**Comment by brutaldev** [comment]
A scenario that led me here was using the `SlowMo` launch option which makes it hang on waiting for network idle state 100% of the time.

**Comment by daniel442li** [comment]
getting this error too

**Comment by glebcha** [comment]
For now and always I have to add timeout of 500ms, but it seems to be hacky and fragile.

Example with customized monaco-editor test (ctarl+enter calls api request):

```javascript
   const editor = page.locator('.monaco-editor .view-lines');

    await page.goto(baseUrl);

    await editor.click();
    await editor.focus();
    await page.keyboard.type(setSplitsSessionParameter);
    await page.keyboard.press('Enter');
    await page.keyboard.type(setColocatedSessionParameter);
    await page.keyboard.press('ArrowUp');
    await page.keyboard.press('Control+Enter');

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(500);

    await page.keyboard.press('ArrowDown');
    await page.keyboard.press('Control+Enter');

    await page.waitForLoadState('networkidle');
    await page.waitForTimeout(500);
```

**Comment by Radivarig** [comment]
It either works or more often doesn't, even though all network requests are done, tested from code and from UI network tab.
Removing `no-store` header did nothing, maybe there's another header blocking but I need this to not depend on headers.

Using this as a replacement:
```ts
import {waitForNetworkIdle} from './waitForNetworkIdle'

test('page loads with fetched title', async ({page}) => {
  await page.goto('...')
  await waitForNetworkIdle(page) // <-
  const title = await page.title()
  expect(title).toBe('some title')
})
````

```ts
import {Page, Request} from '@playwright/test'

export const waitForNetworkIdle = async (
  page: Page,
  idleTime = 500,
  timeout = 10000,
): Promise<void> => {
  const pending = new Set<Request>()
  let lastActivity = Date.now()

  const onRequest = (req: any) => {
    pending.add(req)
    lastActivity = Date.now()
  }

  const onDone = (req: any) => {
    pending.delete(req)
    lastActivity = Date.now()
  }

  page.on('request', onRequest)
  page.on('requestfinished', onDone)
  page.on('requestfailed', onDone)

  return new Promise((resolve, reject) => {
    const start = Date.now()

    const check = () => {
      const now = Date.now()
      const timeSinceLastActivity = now - lastActivity

      if (pending.size === 0 && timeSinceLastActivity >= idleTime) {
        cleanup()
        resolve()
      }
      else if (now - start > timeout) {
        cleanup()
        reject(new Error(`waitForNetworkIdle timed out after ${timeout}ms`))
      }
    }

    const interval = setInterval(check, 100)

    const cleanup = () => {
      clearInterval(interval)
      page.off('request', onRequest)
      page.off('requestfinished', onDone)
      page.off('requestfailed', onDone)
    }
  })
}

```
