### ISSUE TITLE
[BUG] Docs give misleading information about CircleCI that breaks components tests

### ISSUE THREAD

**Issue by oriSomething** [microsoft/playwright#19838]
**Context:**
- Playwright Version: next (both in latest)
- Operating System: Circle CI - mcr.microsoft.com/playwright:v1.29.0-focal
- Node.js version: What's in mcr.microsoft.com/playwright:v1.29.0-focal
- Browser: All
- Extra: CI

**Code Snippet**

[This line in the docs](https://github.com/microsoft/playwright/blob/0be1fc85590f3b7e9923dd3bcf8b4620c45814d1/docs/src/ci.md?plain=1#L374) that suggest the `NODE_ENV=development` is needed in CI is misleading:
1. It works without it
2. It's actually fails react component build with **vite 4**

**Describe the bug**

`NODE_ENV=development` causes tests with `@playwright/experimental-ct-react` to timeout due to wrong complication. Because docs suggest to do that in CI, it causes error that hard to link to wrong docs config

**Comment by oriSomething** [comment]
The project contains only `devDependencies`. It works fine even with `NODE_ENV=production` which is what we are using. But I must say we use **yarn 3**.

`NODE_ENV`:
- **works:** nothing, `production`
- **doesn't work:** `development`

**Comment by mxschmitt** [comment]
Looks then like something specific to Yarn 3?

**Comment by mxschmitt** [comment]
I think we are fine with removing the two lines. From my understanding it makes no difference to npm ci/install.

I tried to trace it back where it comes from (git blame) and its very old: https://github.com/microsoft/playwright/pull/605.

Feel free to raise a PR with removing the two lines.

Its definitely wrong to recommend setting this env var for the whole pipeline.

**Comment by oriSomething** [comment]
I've made a PR https://github.com/microsoft/playwright/pull/19887
I know you have very little time to deal with every issue 🙏

**Comment by mxschmitt** [comment]
Thanks!
