### ISSUE TITLE
[Question] Why don't read extented pages in my test?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19831]
Core.ts -> managing playwright test issues here and calling in channels.spec.ts
channels.spec.ts-> this is my spec file and run this file into npm. `npx playwright test channels.spec.ts`
channels.e2e.ts-> my tests are here
channels.ts->using channels.e2e.ts file's page object model
all-pages.ts-> all pages extend here - called here in my core.ts file because I m using playwright test there

By the way, I m asking this question thinking that this might be a problem with page fixtures. If it comes to you as a custom question, I am very, very sorry. I'm afraid to ask a custom question because,I don't want to complicate your job.

My question is when I call channelsPage(all-pages.ts) into channels.e2e.ts getting below error.Why am I taking this error?
`TypeError: Cannot read properties of undefined (reading 'channelsNav')`

**core.ts**
```
import {test} from "../playwright/pages/all-pages".     //called all-pages.ts here

const Core = {
  create(name: string, config: any) {
    return (() => {
      if (config.E2E) {
        test.describe(`${name}`, async () => {
          config.beforeAll && test.beforeAll(config.beforeAll);
          config.afterAll && test.afterAll(config.afterAll);
          config.beforeEach && test.beforeEach(config.beforeEach);
          config.afterEach && test.afterEach(config.afterEach);
          await Promise.all(
            Object.keys(config.E2E).map((c) => {
              let testContent = config.E2E[c];
              let desc = `E2E- ${c} - ${testContent.notes} - ${testContent.tag}`;
              let skip = testContent.skip || config.E2E.skip;
              let only = testContent.only;
              if (skip) {
                test.skip(desc, async ({page}) => {
                  return testContent.run({page});
                });
              }
              if (only) {
                test.only(desc, async ({page}) => {
                  return testContent.run({page});
                });
              }
              if (!skip && !only) {
                test(desc, async ({page}) => {
                  return testContent.run({page});
                });
              }
            })
          );
        });
      }
    })();
  },
};

export default Core;
```

**channels.ts(using channels.e2e.ts file's page object model)**
```
import { Locator, Page } from "@playwright/test";

export class ChannelPage {
  page: Page;
  channelsNav: Locator;
 
  constructor(page: Page) {
    this.channelsNav = page.locator("#nav-channels");
  }

}
```
**all-pages.ts(all pages extend here-called here in my core.ts file because I m using playwrgiht test there)**

```
import { test as base } from '@playwright/test';
import { ChannelPage } from 'playwright/pages/channels';

type AllPages={
  channelsPage: ChannelPage;
}
export const test = base.extend<AllPages>({
  channelsPage: async ({ page }, use) => {
    await use(new ChannelPage(page));
  }
});
```
**channels.spec.ts**

```
import Core from "core";
import { ChannelsWeb } from "./channels.e2e";

Core.create("Channels", ChannelsWeb)
```

**channels.e2e.ts**
```
import { expect } from "@playwright/test"

export const ChannelsWeb = {
    E2E: {
        NavigateChannelsPage: {
            notes: "Verify that navigate to Channels page",
            tag: "",
            run: async ({channelsPage,page}) => {
                await page.goto("")
                await expect(page).toHaveURL(/\/feedback/);
                await channelsPage.channelsNav.click()
                await expect(page).toHaveURL(/\/channels/);

            }
        },
    }
}

```

**Comment by mxschmitt** [comment]
You don't pass `channelsPage` to your `run()` function. That's the reason why its undefined and Node can't read properties of undefined.

I recommend to not invent custom logic like this one and stick with the Playwright defaults, they are much simpler to understand. (define tests inline and don't wrap them inside a custom class).

Closing as per above.

**Comment by YusufOzt** [comment]
@mxschmitt  thanks for response. How can I pass channelsPage to my run() function? Could show me a little example or is it impossible to pass?

**Comment by mxschmitt** [comment]
testContent.run({page}); -> testContent.run({page, channelsPage});

**Comment by YusufOzt** [comment]
@mxschmitt  oh got it,tkanks again
