### ISSUE TITLE
[BUG] Breaking 302 redirects in Webkit

### ISSUE THREAD

**Issue by admmasters** [microsoft/playwright#19846]
Is there any plan to fix this?

https://github.com/microsoft/playwright/blob/f91e41ef400c09fe9a0b86872a87415f652993a8/tests/page/page-route.spec.ts#L531

**Comment by mxschmitt** [comment]
Why do you want to fulfill with a redirect? Can you instead directly fulfill with the final request?

**Comment by mxschmitt** [comment]
Closing as per above, since there are no plans to support it in the near future.
