### ISSUE TITLE
[BUG] RouteHandlerCallback type incompatible with async route.* methods

### ISSUE THREAD

**Issue by carmanchris31** [microsoft/playwright#19855]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac
- Node.js version: 14.21
- Browser: Chromium

**Code Snippet**

Consider the example from https://playwright.dev/docs/network#handle-requests
```ts
    await page.route('**/api/fetch_data', route => route.fulfill({
      status: 200,
      body: testData,
    }));
```

**Describe the bug**

`RouteHandlerCallback` expects that the callback only returns `void`:
https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L425

However, most of the `route` apis are async and thus return `Promise<void>`:
`route.abort`: https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L310
`route.continue`: https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L394
`route.fallback`: https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L304
`route.fetch`: https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L322
`route.fulfill`: https://github.com/microsoft/playwright/blob/3f333a8/packages/playwright-core/src/client/network.ts#L329

`Promise<void>` is not assignable to `<void>` and raises a flag with [@typescript-eslint/no-misused-promises](https://typescript-eslint.io/rules/no-misused-promises/)
![Screen Shot 2023-01-03 at 6 15 57 PM](https://user-images.githubusercontent.com/9935648/210472749-0d4b5f85-d603-42cd-bac3-6b0f886719bf.png)

To address this should be as simple as amending the return type of `RouteHandlerCallback` to include `Promise<void>` (see https://github.com/microsoft/playwright/pull/19856)

**Comment by mxschmitt** [comment]
For further reference, this would make it work with the [`@typescript-eslint/no-misused-promises`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.md) ESLint rule.

**Comment by mxschmitt** [comment]
Sounds reasonable, will assign it to the next release so we don't forget about it, but already see that you are working on it.
