### ISSUE TITLE
[Feature] [VSCode] POM improvements

### ISSUE THREAD

**Issue by paustint** [microsoft/playwright#19852]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I have followed the [PageObjectModel pattern as recommended by the documentation](https://playwright.dev/docs/pom) combined with fixtures and the VScode extension has a few areas that could be improved when this pattern is being used.

* When a browser window is open, the locators selected in the editor are not highlighted in the browser
  * The issue is the the locators are formatted as `this.page.getByRole('button')` instead of `page.getByRole('button')`. I can temporarily remove the `this.` to see the browser highlight as a workaround.
* The line decoration that shows which line of code is running does not appear to work when using the POM  pattern.

**Comment by vincchan** [comment]
If I may add to this... (also I can also open a new ticket for this)

Would be also nice to have a generator for a POM, currently it's taking a lot of time to write a POM and find possible buttons, features and locators in general. 

I was thinking about being able to have a "Capture POM"-Mode in the codegen to just be able to click on different features/buttons on a page and it would just generate a POM including the Locators without actually changing to a different page.

**Comment by lmlikota** [comment]
> If I may add to this... (also I can also open a new ticket for this)
> 
> Would be also nice to have a generator for a POM, currently it's taking a lot of time to write a POM and find possible buttons, features and locators in general.
> 
> I was thinking about being able to have a "Capture POM"-Mode in the codegen to just be able to click on different features/buttons on a page and it would just generate a POM including the Locators without actually changing to a different page.

Since lately `codegen` is recording `data-testid`, `role` I have started to use it to record our `data-testid` and then create POM class and methods from it. It speeds up process a bit.

**Comment by rahulbansal16** [comment]
@lmlikota how are you thinking to make it POM? I am experimenting with generating POM from the code directly.

**Comment by Kranael** [comment]
Maybe it would be possible to have a button "create POM" in the VS Code Extension?

After that click on the elements and it generates a pom and also convert it in a fixture so we can use it.

**Comment by mxschmitt** [comment]
> The issue is the the locators are formatted as this.page.getByRole('button') instead of page.getByRole('button'). I can temporarily remove the this. to see the browser highlight as a workaround.

This should be addressed with the latest version of the extension.

Regarding the second feature request, this is unfortunately not possible, since we cannot know how much a function of your POM takes, only the Playwright API call execution duration is what we know. This then looks like this:

<img width="1576" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/1806a916-9eab-4a4a-92eb-a51ddb8f457e">

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further feature requests.
