### ISSUE TITLE
[Question] How to access a locator which includes a state ?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#19857]
In my **test.spec.ts** ,have a fake state ( InboxState.createdFeedbackTitle). In **inbox.ts(page object file)** I want to access that state in the locater but taking below error;

`   - waiting for locator('xpath=//span[contains(text(),\'[object Object]\')]//parent::div//div[@class=\'tag\']')`

I guess this problem is related to constructer in **inbox.ts** file.When I want to access a locator which includes state  in inbox.ts, I can not call that locater properly in my test file. Is there any solution for this related to calling a state in locater or it not impossible? I had to define that state outside so I didn t define inside inbox.ts

**inbox.ts(page object file)**

```
import { Locator, Page } from "@playwright/test";
import { InboxState } from "playwright/tests/inbox/inbox.state";

export class InboxPage {
  page: Page;
  tagValueOnFeedbackFooter: Locator;

  constructor(page: Page) {   

this.tagValueOnFeedbackFooter=page.locator(`//span[contains(text(),'${InboxState.createdFeedbackTitle}')]//parent::div//div[@class='tag']`)

  }
}

```
**test.spec.ts**

```
import { expect} from "@playwright/test"
import { InboxPage } from "playwright/pages/inbox";
import { faker } from '@faker-js/faker';

let inboxPage:InboxPage
test.beforeEach(async ({ page}) => {
 inboxPage =new InboxPage(page)

  await page.goto('http://test1');
});
test('inbox', async ({ page }) => {
               InboxState.createdFeedbackTitle = faker.lorem.sentence(5)
                await expect(inboxPage.tagValueOnFeedbackFooter).toHaveText("Has Internal Note")
});
```

**Comment by mxschmitt** [comment]
Yes you need to define it in the outside scope so InboxPage has access or make tagValueOnFeedbackFooter a function.

**Comment by YusufOzturk-Development** [comment]
@mxschmitt thanks. Could you show me a little example how can define pace.locator() outside scope?

**Comment by YusufOzt** [comment]
@mxschmitt  thanks. Could you show me a little example how can define pace.locator() outside scope?
