### ISSUE TITLE
[Question] How do I listen for a custom event, when doing page.goto?

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#19858]
My objective is to create a helper function, that navigates to a page and waits for the page hydration event. My initial code looks like this:

```typescript
await page.goto(url);
await page.evaulate( ... window.addEventListener('sveltekit:start )
```

Works great, but there is a bug. Sometimes the `sveltekit:start` event is emitted before the event listener is added.

How can I add the eventListener before calling `page.goto`?

If I move the listener to before `page.goto` I get this error : `Execution context was destroyed, most likely because of a navigation`

**Comment by mxschmitt** [comment]
You can do the following, would that work for your use-case?

```js
  await page.addInitScript(() => {
    let resolveSvelteKitStart = () => {};
    window.svelteKitStart = new Promise(resolve => resolveSvelteKitStart = resolve);
    window.addEventListener('sveltekit:start', () => resolveSvelteKitStart());
  });
  await page.goto("...")
  await page.waitForFunction(() => window.svelteKitStart);
```

**Comment by alexbjorlig** [comment]
> ```js
> await page.waitForFunction(() => window.svelteKitStart);
> ```

Will this `await` also work on another `page.goto` - or only the first time?

**Comment by mxschmitt** [comment]
It will work for another page.goto's.

**Comment by mxschmitt** [comment]
closing since it seems answered, please re-file if you have more questions.

**Comment by ambiguous48** [comment]
@alexbjorlig You can also use the strategy implemented in the sveltekit repo itself. Tldr; you wrap(override?) the `goto` function.

- https://github.com/sveltejs/kit/blob/272e6c87385833e9add656070ddc87d3f46b0d2e/packages/kit/test/setup.js#L24

- https://github.com/sveltejs/kit/blob/272e6c87385833e9add656070ddc87d3f46b0d2e/packages/kit/test/utils.js#L94
- https://github.com/sveltejs/kit/commit/70bc0015f4cfa3e2acc6a9f0b85297713c764e9c

**Comment by alexbjorlig** [comment]
> @alexbjorlig You can also use the strategy implemented in the sveltekit repo itself. Tldr; you wrap(override?) the `goto` function.
> 
> * https://github.com/sveltejs/kit/blob/272e6c87385833e9add656070ddc87d3f46b0d2e/packages/kit/test/setup.js#L24
> * https://github.com/sveltejs/kit/blob/272e6c87385833e9add656070ddc87d3f46b0d2e/packages/kit/test/utils.js#L94
> * [sveltejs/kit@70bc001](https://github.com/sveltejs/kit/commit/70bc0015f4cfa3e2acc6a9f0b85297713c764e9c)

This looks amazing!

Does this also work/support client-side navigation?

**Comment by ambiguous48** [comment]
Sure. You can override the default page fixture and use it in all your tests. Client side navigations should breeze through since the `started` class is available instantly. And durring ssr, the tests should wait for that `onMount` to happen, signalling that hydration is complete.

```ts
// +layout.svelte

onMount(() => {
  // communicate that the app is ready - used for testing
  document.body.classList.add('started');
});
```

```ts
// my-fixture.ts

export const test = base.extend({
  page: async ({
    context,
  }, use) => {
    const goto = page.goto;

    page.goto = async function(url, opts) {
      const res = await goto.call(page, url, opts);

      // https://github.com/sveltejs/kit/pull/6484
      await page.waitForSelector('body.started', {
        timeout: 5000
      });

      return res;
    };

    await use(page);
  },
});
```

**Comment by phil-w** [comment]
It may be me being thick, but without this little hack, my Playwright Sveltekit tests were completely and horribly unreliable in ways I've not come across since the early days of test tools. This is a life safer... I guess I think maybe it needs a bit more publicity. Thanks anyway.

**Comment by jgchk** [comment]
> It may be me being thick, but without this little hack, my Playwright Sveltekit tests were completely and horribly unreliable in ways I've not come across since the early days of test tools. This is a life safer... I guess I think maybe it needs a bit more publicity. Thanks anyway.

Agreed, this feels like something that should be included in the default SvelteKit scaffolding when users opt to include Playwright, or at the very least featured in documentation somewhere.
