### ISSUE TITLE
[ Question ] Do you have any example suite with CucumberJS?

### ISSUE THREAD

**Issue by rakeshnambiar** [microsoft/playwright#19866]
Do you have any example suite with CucumberJS? Same as https://github.com/badeball/cypress-cucumber-preprocessor

**Comment by mxschmitt** [comment]
Playwright's test-runner does not yet support cucumber out of the box, see [this](https://github.com/microsoft/playwright/issues/11975) feature request.

There is tho a community project available to use Cucumber with Playwright, see here: https://github.com/Tallyb/cucumber-playwright
