### ISSUE TITLE
[BUG] Ubuntu 22.10 WEBKIT missing libraries (libicui18n.so.70, libicuuc.so.70)

### ISSUE THREAD

**Issue by momcilo-dimitrijevic** [microsoft/playwright#19862]
**Context:**
- Playwright Version: 1.28.0
- Operating System: Ubuntu 22.10
- .NET 6
- Browser: WebKit

Running tests with Chromium and Firefox is working fine, but I get the following error when running tests on WebKit:

![image](https://user-images.githubusercontent.com/47745280/210524507-be5b07b7-ea39-4c9d-9781-f71d0e16c480.png)

I have reinstalled all dependencies by running playwright.ps1 Powershell script but it didn't solve the problem.
Seems like this WebKit version requires ICU v70.0, while my lib version got updated to v71.1 after upgrading to Ubuntu 22.10.

![image](https://user-images.githubusercontent.com/47745280/210524904-79ff9823-97be-424c-9e55-b25f3161ccc0.png)

Any hopes that this gets fixed so I can run tests on WebKit on Ubuntu 22.10?

**Comment by momdim** [comment]
> Playwright only [supports](https://playwright.dev/docs/troubleshooting#linux) Ubuntu LTS versions, 18.04/20.04/22.04, will mark it as a feature request to best effort support 22.04 as well.

I think you meant 22.10 :)

**Comment by mxschmitt** [comment]
We talked in our meeting about it and supporting 20.10/22.10 releases of Ubuntu is out of scope for Playwright, since it would mean we need to introduce more browser builds for these operating systems versions.

Closing by that.

**Comment by jonmartinsolaas** [comment]
I found the libicu 70 libs in the Darktable snap on ubuntu 23.10, so i just symlinked the relevant files to /usr/lib and then the playwright example app (the one downloading some pngs) worked just fine for me.
