### ISSUE TITLE
How many number of worker processes are supported for playwright in build pipeline? Also how many test files (spec files) can be made to run on build pipeline with 2 workers?

### ISSUE THREAD

**Issue by vaishnavibammigatti** [microsoft/playwright#19865]

**Comment by vaishnavibammigatti** [comment]
Hello @mxschmitt ,
Thanks for your reply.

Could you please let me know if number of workers to be selected is one, then can we not have parallel execution of test files on build pipeline?

Actually if we set number of workers as two and run only few test files then we are able to execute those few test files parallelly on build pipeline.
But if there are more test files with more test cases, then build pipeline is running until it gets timedout.
Can you please help us here if more test cases as many as 1000+ can be made to run on build pipeline with 1 worker at least? If it is possible to run with more than one worker also, please help us with the changes to be done in build pipeline or in code to achieve the same.

**Comment by mxschmitt** [comment]
Which continuous integration system are you using? Did you read over our CI guide? https://playwright.dev/docs/ci

Then I might be able to send you some examples / references to their docs.

**Comment by mxschmitt** [comment]
Closing for now as per above, please re-file with more information.
