### ISSUE TITLE
[BUG]: Playwright VS Code extension - No tests have been found in Test Explorer

### ISSUE THREAD

**Issue by Shylpx** [microsoft/playwright#19863]
**Context:**
- Playwright Version: 8.11.0
- Operating System: Linux - Ubuntu 20.04.5 LTS
- Node.js version: v16.16.0 (over `nvm`), with `npm` 8.11.0 and `yarn` 1.22.5
- Browser: All
- Extra:
  - VSCode: 1.74.2 (installed with `snap`, but I also removed it and installed it with `apt-get`, but same result)
  - Playwright Test for VSCode extension: v1.0.3
  - I have no other extensions installed

**Describe the bug**

I've followed the steps in https://playwright.dev/docs/getting-started-vscode to install the VS Code Extension, but it doesn't matter how many times I refresh the tests, **I always get the `No tests have been found in this workspace yet`** message, and **no green arrows to run isolated tests**:

![Screenshot from 2023-01-04 10-17-29](https://user-images.githubusercontent.com/6042873/210537256-7d13a16d-6feb-464d-9caa-334568fd3a4a.png)

**Things that are working**

Everything else seems to be working properly:

- Installing playwright with the command:
![Screenshot from 2023-01-04 10-13-11](https://user-images.githubusercontent.com/6042873/210537446-05fff581-735d-4b02-83f6-e634040ad083.png)
![Screenshot from 2023-01-04 10-14-08](https://user-images.githubusercontent.com/6042873/210537455-456eccc5-7ff9-40e7-aaf1-c978f90891bb.png)
- `tests` and `tests-examples` were automatically created, together with the config file (`playwright.config.ts`):
![Screenshot from 2023-01-04 10-15-12](https://user-images.githubusercontent.com/6042873/210537631-c0ebb540-ed76-475a-b03c-904822ae991f.png)
- I can execute tests from the command line: `npx playwright test example`
![Screenshot from 2023-01-04 10-15-45](https://user-images.githubusercontent.com/6042873/210537760-17d05626-cd13-4c23-8717-8d2551164326.png)
- The Playwright section appears in the `Testing` tab, and I can even record a new test:
![Screenshot from 2023-01-04 10-41-40](https://user-images.githubusercontent.com/6042873/210537833-93bdf4fd-9d47-41d5-a9bf-13b876d75e02.png)
![Screenshot from 2023-01-04 10-42-55](https://user-images.githubusercontent.com/6042873/210538162-f49415c2-be55-4638-b212-2f98ae23e793.png)
- Test explorer gets the environments, from the config file:
![Screenshot from 2023-01-04 10-18-00](https://user-images.githubusercontent.com/6042873/210538782-10b80d9e-4347-41eb-8d35-c778efa29869.png)

**Comment by arpan-patelia** [comment]
I had the same issue. Installing system-wide `npm`,  instead of using npm from nvm fixed it for me. A possible fix will be available in v1.30.

https://github.com/microsoft/playwright/issues/18954

**Comment by pavelfeldman** [comment]
Fixed in the next version.

**Comment by Shylpx** [comment]
Hi! I've updated the package to the version `v1.30` released yesterday, but still getting the same result.

I've also updated:
- VSCode: `1.74.2` -> `1.74.3`
- Playwright Test for VSCode extension: `v1.0.3` -> `v1.0.6`

**Comment by alex-vukov** [comment]
@pavelfeldman updating to v1.30 temporary fixed the issue but after a restart of VSCode I have it again. Same as @Shylpx

**Comment by redbugz** [comment]
I have the same issue, node installed via nvm, no system installation, @playwright/test 1.31.0, vscode extension 1.0.7 on a Mac. 

I have other extensions installed as well that use Node (eslint, jest), they seem to find node/npm correctly somehow

**Comment by chastabor** [comment]
I currently have this same issue. I'm able to get the Test Explorer to show tests when I use nvm to install node, but when I use a snap node version the Test Explorer does not show any tests and displays a message asking me to install Playwright. Through strace I believe that the snap version is getting an error when a child node process is attempting to write to the standard out:
```
837817 ioctl(1, TCGETS, 0x7ffc12e386f0) = -1 ENOTTY (Inappropriate ioctl for device)
837817 fstat(1, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x1, 0x3), ...}) = 0
837817 ioctl(2, TCGETS, 0x7ffc12e38530) = -1 ENOTTY (Inappropriate ioctl for device)
837817 fstat(2, {st_mode=S_IFCHR|0666, st_rdev=makedev(0x1, 0x3), ...}) = 0
837817 write(1, "{\"pwtIndex\":\"/home/<<...removed...part...of...path...>>/playwright/node_modules/@playwright/test/index.js\",\"version\":\"1.40.0\"}\n", 120) = -1 EACCES (Permission denied)
```
I think this is an issue where the child node process is prohibited from inheriting file descriptors from its parent, and thus doesn't have access to the parent nodejs' standard io.

What I see in VSCode is the following:
```
SyntaxError: Unexpected end of JSON input
  at JSON.parse (<anonymous>)
  at Oe.getPlaywrightInfo (/home/<<removed>>/.vscode/extensions/ms-playwright.playwright-1.0.17/out/extension.js:14:4228)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
  at async Ve._rebuildModel (/home/<<removed>>/.vscode/extensions/ms-playwright.playwright-1.0.17/out/extension.js:91:5603)
  at async Ve.activate (/home/<<removed>>/.vscode/extensions/ms-playwright.playwright-1.0.17/out/extension.js:91:4812)
w @ console.ts:137
```

And when I run the offending code in the VSCode console it will still work in the snap version:
```
node "-e" 'try { const pwtIndex = require.resolve("@playwright/test"); const version = require("@playwright/test/package.json").version; console.log(JSON.stringify({ pwtIndex, version})); } catch { console.log("undefined"); }'
{"pwtIndex":"/home/<<removed>>/playwright/node_modules/@playwright/test/index.js","version":"1.40.0"}
```

Currently my workaround is to use nvm to install nodejs for me, however, I wanted to post what I ran into on this thread in case someone else is running into a similar issue.
