### ISSUE TITLE
[Question] Alpine Linux Support

### ISSUE THREAD

**Issue by burritoIand** [microsoft/playwright#1986]
Do you guys have any plans to add an official docker image for Alpine Linux users?

**Comment by aslushnikov** [comment]
It's not hi in our priorities, but we might have it some time in future. For now, we'd be happy to refer to a third-party image, if there's one!

**Comment by Niek** [comment]
This would require a special build for musl libc. It would be great to have though.

**Comment by damianobarbati** [comment]
@niek is it possible to have an official ms / playwright Docker image based on alpine?

**Comment by Niek** [comment]
> @Niek is it possible to have an official ms / playwright Docker image based on alpine?

Possible? Yes. Will it ever happen? No idea, you should ask MS / the Playwright team like @aslushnikov 😄

**Comment by damianobarbati** [comment]
@aslushnikov is this something your team considered? 🥲

**Comment by aslushnikov** [comment]
There are no plans for Alpine support so far as of Dec 2022!

**Comment by TroyKomodo** [comment]
wild
