### ISSUE TITLE
Electron app is loading as blank

### ISSUE THREAD

**Issue by sanbhav1986** [microsoft/playwright#19875]
Electron application is loading as blank after successful log in and script is getting timed out.
 
However, the application is loading properly when launching .exe manually.

I am unable proceed further due to this.kindly help

![IMG_20230105_000748](https://user-images.githubusercontent.com/98820927/210637061-f4e8e233-ae16-4744-b239-45b4e65dca88.jpg)

**Comment by sanbhav1986** [comment]
I am facing another challenge. Application is loading as blank and getting timed out. However,  the application is loading properly when launching manually.

Any hint please?

**Comment by mxschmitt** [comment]
Can you provide a repro which we can run locally? Also could you try running it on our canary releases? There we fixes something electron related: https://playwright.dev/docs/canary-releases

**Comment by sanbhav1986** [comment]
Thanks @mxschmitt.

Facing the same issue when tried with Selenium as well when launching .exe with script. I am assuming some issue with the application setup.

Is there a way to connect with existing electron application window using playwright?

**Comment by mxschmitt** [comment]
You cannot attach to existing Electron Windows.

Could you ensure that `nodeCliInspect` ([FuseV1Options.EnableNodeCliInspectArguments](https://www.electronjs.org/docs/latest/tutorial/fuses#nodecliinspect)) fuse is **not** set to `false`?

**Comment by sanbhav1986** [comment]
Sorry, I am not aware how and where to check nodeCliInspect fuse is set to false.
Could you please guide me? Thanks!

**Comment by aslushnikov** [comment]
(I'll have to close this since this is now a discussion on programming electron application rather than a Playwright-specific issue).

**Comment by SabFloki** [comment]
> Sorry, I am not aware how and where to check nodeCliInspect fuse is set to false. Could you please guide me? Thanks!

have you set this? if aware, please share here.

**Comment by jevasco** [comment]
> > Sorry, I am not aware how and where to check nodeCliInspect fuse is set to false. Could you please guide me? Thanks!
> 
> have you set this? if aware, please share here.

Not 💯 sure but it could be in your build make-package file, try to look for `FuseV1Options.EnableNodeCliInspectArguments`

**Comment by jevasco** [comment]
> You cannot attach to existing Electron Windows.
> 
> Could you ensure that `nodeCliInspect` ([FuseV1Options.EnableNodeCliInspectArguments](https://www.electronjs.org/docs/latest/tutorial/fuses#nodecliinspect)) fuse is **not** set to `false`?

Hey @mxschmitt , per this [doc](https://playwright.dev/docs/api/class-electron) it is a known issue. Do you know where is this getting tracked for resolution?
