### ISSUE TITLE
[Question] Discover page with JavaScript errors

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#19877]
Does Playwright recognise that a page has JavaScript error and if so how can I obtain this information?

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/docs/api/class-page#page-event-page-error

**Comment by doberkofler** [comment]
When exactly would this event be fired:
- Uncaught exceptions?
- Failed load requests?
- console.error?
Thank you.

**Comment by mxschmitt** [comment]
Only for uncaught exception.

**Comment by doberkofler** [comment]
Thank you
