### ISSUE TITLE
Is it possible to start chromium with network throttling slow mode - Playwright Java

### ISSUE THREAD

**Issue by shilpa32** [microsoft/playwright#19883]
I want to check some use case for higher speed(4G) and slower speed (2G and 3G)
How to change the network throttling value -  using Playwright Java

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/8622 which contains a workaround which should also work in Java.

You can manually delay network requests for a few seconds but you cannot emulate network conditions as of today.
