### ISSUE TITLE
[BUG] Browsers not installing on Node 14

### ISSUE THREAD

**Issue by corbinu** [microsoft/playwright#1988]
**Context:**
- Playwright Version: 0.15.0
- Operating System: Windows

**Describe the bug**

I just upgraded to the new Node 14 and with both npm and yarn the .local-browsers folder ends up empty on install. I was on Node 13 before and was fine. I just switched back to Node 12 and it works fine again.

**Comment by rwoll** [comment]
This looks like it is likely related to https://github.com/maxogden/extract-zip/issues/94. [extract-zip](https://www.npmjs.com/package/extract-zip) is a dependency of the browser fetcher script: https://github.com/microsoft/playwright/blob/f386fa9415be8f8a1bdda294c0b545530245fa48/src/server/browserFetcher.ts#L19

---

Homebrew upgraded my environment to Node 14.0.0 surfacing this issue. As a temporary work around, I've `brew install node@12`.

**Comment by aslushnikov** [comment]
Looks like this will be fixed with Node.js 14.1.0

**Comment by corbinu** [comment]
@rwoll Confirmed it is now installing correctly on my Mac, Windows and Ubuntu machines! Thanks!
