### ISSUE TITLE
[Question] Playwright config file: Running the same test with two different urls

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#19880]
Hi Team

```
{
  name: 'chromium',
  testDir: "tests/crewtests",
  use: {
    baseURL: process.env.PLAYWRIGHT_BASE_URL,
    contextOptions : {ignoreHTTPSErrors: true},
    browserName: 'chromium',
    headless : false,
    screenshot : 'on',
    trace : 'on',//off,on
    video: 'on',
    ...devices['Desktop Chrome'],
  },
},
```
we do have a test that should use two URLs, that we pass as a run time variables like this
TEST_ENV=dev PLAYWRIGHT_BASE_URL="https://url1.com/" PLAYWRIGHT_CREWMEMBER_BASE_URL="https://url2.com/" npx playwright test ,
in the single test
Login.toApp(process.env.PLAYWRIGHT_BASE_URL)
//do something
Login.toApp(process.env.PLAYWRIGHT_CREWMEMBER_BASE_URL)
//do something
and the test should go the first url, execute something and then test should launch the second url and execute tests on the second URL, can you please advise how to build a config file to support reading both the URLs in the test?

**Comment by gauravgandhi1315** [comment]
@InduKrish You can open url to your application at test level. 

```
// Go to the application url
    await verifyActions.openURL(urlPath);
```

```
 async openURL(path) {
    await this.page.goto(path);
  }
```

Either use `openURL` 2 times with different URLs in your test or you can add in `beforeEach` with a condition to run tests with first url and then second one.

**Comment by InduKrish** [comment]
Hi, We are already using the exact same way recommended above and face the issue that the second uri is appended to the first uri, instead of launching just the second URI alone. 

here is what we already have,
// Go to the application url
    await Login.toApp(urlPath);

 async goto(url) {
        return this.page.goto(url);
    }

and it appends the first uri to the second uri, as baseURL is configured in the config file, should baeURL be removed from the config file or how to make playwright launch the two URIs one after the other?

{
name: 'chromium',
testDir: "tests/crewtests",
use: {
baseURL: process.env.PLAYWRIGHT_BASE_URL,
contextOptions : {ignoreHTTPSErrors: true},
browserName: 'chromium',
headless : false,
screenshot : 'on',
trace : 'on',//off,on
video: 'on',
...devices['Desktop Chrome'],
},
},

**Comment by mxschmitt** [comment]
From reading above, I think this issue is about that the baseURL gets not generated as expected, see here an overview about how to append things and how its working: https://playwright.dev/docs/api/class-testoptions#test-options-base-url

If you have a concrete question, let us know - hard to help with open ended questions.
