### ISSUE TITLE
Configuration  to debug the PlayWright

### ISSUE THREAD

**Issue by jdang67** [microsoft/playwright#19906]
Hi Everyone,

Can someone share the configuration for `launch.json` to debug the PlayWright tests?

Thanks,

John Dang

**Comment by mxschmitt** [comment]
We recommend the VSCode extension to debug tests, it will give you a ton of additional features and goodies. See here: https://playwright.dev/docs/getting-started-vscode

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues.
