### ISSUE TITLE
[Question] Wait for new data saved then continue to next step?

### ISSUE THREAD

**Issue by hoangngocanhskedulo** [microsoft/playwright#19914]
Hi,

I am using Playwright for my web app and I am having an issue like this: playwright executes next steps too fast before new data could be saved in the previous step.

I want new data finished saving before next steps are executed.

Is there any solution to this?

Thanks,

**Comment by mxschmitt** [comment]
Sounds like a bug in your application! imagine there is a fast user he would also encounter this issue.

What does "data finished saving" mean? is it saving it to the backend via a network request? Then you can use waitForRequest: https://playwright.dev/docs/api/class-page#page-wait-for-request

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues.
