### ISSUE TITLE
[Question] Custom commands (allowing parametrizing) for repetative operations as in cypress

### ISSUE THREAD

**Issue by tomdelahaba** [microsoft/playwright#19919]
I would like to ask if there is anything in Playwright that can be used as custom commands in cypress: https://docs.cypress.io/api/cypress-api/custom-commands

Let's say, I have a multiple tests where many of them requires the same actions / assertions, unfortunately these actions or assertions can't be involved in beforeEach. Another reason is, let's say I would like to use this "repetitive commands" in multiple different test files. 

**So, for example**:
At some point (it does not need to be at the beginning of the test, so beforeEach can't be used) I would like to login user with email & password, after successfully logging in, which I am logging into console something like "hello johndoe@foo.com" (so I am listening to console logs) select his / her avatar from their device (they select some file from the device). In few of the tests, before all this I would like to do different actions, for example go to home page, on other I would like to buy some product, etc. etc. But at some point, I know I have to go through these actions. After logging in and selecting the avatar, I would like to do various different actions like taking a snapshot, etc.

I know I would like to have some command like "loginUser" where I would like to expect that user to be successfully logged in. In each of the test / logging in I would like to login different user and select different avatar so these has to be parametrized.

I have been reading about the custom fixtures, but it does not seem to me like something I should use (but maybe I am missing something or misunderstanding fixtures): https://playwright.dev/docs/test-fixtures

Is there anything like cypress custom commands? I have been using them before migrating to playwright, so in each of the test I just called `cy.login('johndoe@foo.com', 'bar', 'picture.png')`. Unfortunately that toDoPage custom fixture example is not very helpful to me as it is very generally described so I have no clue if this is what I am looking for or not.

**Comment by mxschmitt** [comment]
You can create JavaScript functions or classes and import them in the files you need.


```ts
export function login(page: Page, username: string, password: string) {
  ...
}
```

```ts
import { login } from './login';

...

login(...)
```

**Comment by tomdelahaba** [comment]
@mxschmitt Thanks Max, but these functions, they do not have an access to assertions, right? Or do they? I need expect multiple assertions as well, because I have to make sure the logging was successful (I have to expect that particular console log), I have to expect that some kind of spinner disappeared, I have to make sure that the avatar is really attached, etc.

From what I am looking into the test-fixtures in the doc, the account part (except the signup) looks like something what should be useful for me, but unfortunately I have no idea how to call that overriden fixture... I really miss in the docs some examples with "how to use this one". The doc is (imo) showing only particular part of the definition, but not using it...

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues.
