### ISSUE TITLE
[Feature] Little improve trace analize on trace.playwright.dev

### ISSUE THREAD

**Issue by Aroot42** [microsoft/playwright#19916]
Hi.
I want to propose to little improve trace analize on trace.playwright.dev

1. When I hover mouse on action in timeline I want to see action time
![image](https://user-images.githubusercontent.com/100360547/210969337-484b1ef8-fd51-45ce-9666-aabf80d10610.png)

2. When I click on action in timeline, I want to scroll left tree and focus on action which was clicked

**Comment by mxschmitt** [comment]
Both are reasonable, 1 could be implemented as a title, so when you hover over it you'll see the duration.
