### ISSUE TITLE
[Feature] There will be a event listener for the Screen Capture API ?

### ISSUE THREAD

**Issue by zibiaowu** [microsoft/playwright#19918]
We use the [Screen Capture API](https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture) in our website, and we don't know how to test this.

When the code is like the following, there will be a browser prompt, how can we listen this just like the `page.on('dialog')`?

```js
await navigator.mediaDevices.getDisplayMedia();
```

![image](https://user-images.githubusercontent.com/18088464/211002983-b182f64f-acf1-477f-8b84-1ad5ef182911.png)

**Comment by mxschmitt** [comment]
Closing as per above, please re-file if you still encounter issues.
