### ISSUE TITLE
[Feature] Keep my application's breakpoints between test runs

### ISSUE THREAD

**Issue by DamienCassou** [microsoft/playwright#19915]
Sometimes, understanding why my application isn't working as expected requires adding a few breakpoints to the application's code. Unfortunately, each time Playwright starts the browser for a given test, a new browser profile is created and my precious breakpoints are not in the new browser profile.

Is there a way to save/restore (part of) a browser profile between test runs?

**Comment by mxschmitt** [comment]
--debug is no longer the recommended way of debugging tests, we recommend the vscode extension where you can set breakpoints and it keeps the browser open: https://playwright.dev/docs/getting-started-vscode#debugging-tests at the end of the test even if its failing.

**Comment by DamienCassou** [comment]
@mxschmitt are you referring to nodejs breakpoints or browser breakpoints? I'm interested in adding breakpoints in my application code and keeping them when launching the test again.

**Comment by mxschmitt** [comment]
I'm referring to Node.js breakpoints. Having breakpoints in the browser should also work with the VSCode extension.

**Comment by mxschmitt** [comment]
Ah you mean debug the browser using VSCode, thats not possible as of today. But you can use Chrome DevTools for it.

I can make a feature request out of it in the meantime.

**Comment by DamienCassou** [comment]
> But you can use Chrome DevTools for it.

Indeed but then you loose your breakpoints each time Playwright restarts the test.

**Comment by BenjaminVanRyseghem** [comment]
@mxschmitt what if I don't use VS Code?

**Comment by mxschmitt** [comment]
If you enable "Show Browser" then the browser gets re-used and the DevTools breakpoints in the browser stay in place. I just tried it out and it was working for me.

![image](https://user-images.githubusercontent.com/17984549/211062817-d928b70e-c745-4bc3-aacc-cabfc688c199.png)

> @mxschmitt what if I don't use VS Code?

We don't provide extensions for other IDEs/editors as of today.

**Comment by DamienCassou** [comment]
> We don't provide extensions for other IDEs/editors as of today.

I understand this. But it feels weird that this feature only exists for VSCode users. What about the Playwright command line tool?

For anyone interested, the "Show browser" toggle seems to set the variable `_shouldReuseBrowserForTests` which is then [used like this](https://github.com/microsoft/playwright-vscode/blob/4db484092bc44ed0ae366593b62ce8dab714ac66/src/reusedBrowser.ts#L256):

```js
  browserServerEnv(debug: boolean): NodeJS.ProcessEnv | undefined {
    return (debug || this._shouldReuseBrowserForTests) && this._browserServerWS ? {
      PW_TEST_REUSE_CONTEXT: this._shouldReuseBrowserForTests ? '1' : undefined,
      PW_TEST_CONNECT_WS_ENDPOINT: this._browserServerWS,
    } : undefined;
  }
```

So it seems like Playwright reads these 2 undocumented environment variables:
`PW_TEST_REUSE_CONTEXT` and `PW_TEST_CONNECT_WS_ENDPOINT`.

**Comment by mxschmitt** [comment]
> What about the Playwright command line tool?

Good feature request, we recommend users to use the VSCode extension for now, since it provides a significant better user experience for our customers compare to typing commands into the terminal. (shorter feedback loop). That's why we went into this direction for now.

If you are interested in having this feature in the CLI, please file a new issue, then I can mark it as a feature request.

Since the original issue is answered, I'm closing it for now.

**Comment by jacksonv1lle** [comment]
@DamienCassou I was able to get the breakpoints to persist by starting a new browser session before closing the previous session. Once the new browser is open it will have the same breakpoints already in place, the old one can then be closed. I am running tests through VSCode so I am not sure if the same would apply from CLI.
