### ISSUE TITLE
[BUG] Firefox cannot click on input elements with type=color in headless tests on Ubuntu 

### ISSUE THREAD

**Issue by ahmed-at-mabl** [microsoft/playwright#19929]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Ubuntu
- Node.js version: 14
- Browser: Firefox
- Extra: Was able to reproduce with Ubuntu 20 and 22

**Code Snippet**

[This repository](https://github.com/ahmed-at-mabl/playwright-firefox-color-input) based off the Playwright sample install reproduces the issue, and the test failure is visible in the github action. 

The following is the text of the test that fails

``` typescript
test('enter text into a color picker element', async ({ page }) => {
  await page.goto(
    'https://storage.googleapis.com/public-dev-test-lab/input/inputtypes.html'
  );
  const inputColorElement = await page.$('#input-color');
  await inputColorElement?.click();
});
```

It fails on the line `await inputColorElement?.click();`.

**Describe the bug**

When a Playwright script attempts to click on an [input element of type color](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color), this script will fail if run headlessly on Firefox in Ubuntu, with the error 

```elementHandle.click: Target closed
    =========================== logs ===========================
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
    ============================================================
```

which suggests the browser crashes. The test passes fine when run on Firefox headlessly on my MacOS machine, and passes when run in Chrome regardless of browser and headfulness. I also found that this error does not occur if the test is run headfully on Ubuntu, so it seems to be only an issue for headless runs.

**Comment by mxschmitt** [comment]
FTR it opens this dialog: 
![image](https://user-images.githubusercontent.com/17984549/211899684-6474ff54-155c-4d50-b735-c48c4b82700d.png)

which is `widget/windows/nsColorPicker.cpp`.

**Comment by aslushnikov** [comment]
This turns out to be an upstream issue in firefox; filed as https://bugzilla.mozilla.org/show_bug.cgi?id=1821754
