### ISSUE TITLE
[Question] Keep browser open for all tests in a test suite

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#19921]
The typical structure of my tests is as follows:

```typescript
import {test} from '@playwright/test';

test.describe('suite', () => {
   test('test1', async ({page}) => {
      await page.goto('test1');
   }); 
   test('test2', async ({page}) => {
      await page.goto('test2');
   }); 
}); 
```

This works perfectly but I noticed that Playwright opens and closes the browser window for each test and was wondering, why the browser window cannot stay open for all tests and if this could/should be optimised?

**Comment by mxschmitt** [comment]
If you use the VSCode extension, the browser stays open: https://playwright.dev/docs/getting-started-vscode

**Comment by doberkofler** [comment]
Interesting, but would it not be more useful when running thousands of tests in the CI pipeline?

**Comment by mxschmitt** [comment]
You want to ensure full test isolation on your CI, what Playwright does it guarantees that so no test will infer with each other. (less reasons to flake)

**Comment by doberkofler** [comment]
Valid point. Thank you!
