### ISSUE TITLE
[Question] How to wait for multiple locators to be visible

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#19920]
When waiting for a single `Locator` to be visible this can be with a simple `expect().toBeVisible()` but how would I wait for multiple and independent locators to be visible at the same time?
In the following example el1 might be initially visible but while waiting for el2 to be visible el2 might no longer be and I would like to ensure that both elements are visible at the same time.

```typescript
test('visible', async ({page}) => {
   const el1 = page.locator('.el1');
   const el2 = page.locator('.el2');

   await expect(el1).toBeVisible();
   await expect(el2).toBeVisible();
});
```

**Comment by mxschmitt** [comment]
Usually you can do the following:

```ts
await Promise.all([
   expect(el1).toBeVisible(),
   expect(el2).toBeVisible(),
])
```

could you give us some examples or a repro how this would fail and for what exact scenario it would be important?

**Comment by doberkofler** [comment]
I'm currently evaluating Playwright as a possible alternative to my huge selenium based test suite and am quite impressed.
The best use case for this question is a form with dependencies between the individual input elements:
```html
<form>
   <input name="n1" />
   <input name="n2" />
   <input name="n3" />
</form>
```
The business logic might now re-render the input elements based on its  content.
Changing the value of "n1" might for example hide "n3" but the value of "n2" might show "n3" again and when all updates are done, all 3 elements would be visible and we can start testing what the contents are.

In selenium I would have created a "condition" that is only fulfilled when all 3 elements are visible at the same time and I was wondering if and how this might be needed or implemented in Playwright?

**Comment by aslushnikov** [comment]
@doberkofler thank you for the usecase! In Playwright, you would usually fill in input fields, and then validate their state one-by-one. You could either use the `Promise.all` pattern that Max recommended, or just check them individually: 

```ts
test('all should be visible', async ({ page }) => {
  await page.setContent(`
    <form>
     <input name="n1" />
     <input name="n2" />
     <input name="n3" />
    </form>
  `);
  const n1 = page.locator('input[name="n1"]');
  const n2 = page.locator('input[name="n2"]');
  const n3 = page.locator('input[name="n3"]');
  await n1.fill("foo");
  await n2.fill("bar");
  await n3.fill("baz");
  await expect(n1).toBeVisible();
  await expect(n2).toBeVisible();
  await expect(n3).toBeVisible();
});
```

Hope this helps! Please do not hesitate to file new issues if you think we still can be helpful to you.

**Comment by doberkofler** [comment]
@aslushnikov 

Thank you for your feedback. My use case would more look like this and in my selenium tests, I used a custom condition that checks for all elements to be visible at the same time:

```typescript
import {test, expect} from '@playwright/test';

const content = `
<form>
	<input id="n1" value="v1" />
	<input id="n2" value="v2" style="display: none;" />
</form>
<script>
   setTimeout(() => document.getElementById('n1').style.display = 'none', 1000);
   setTimeout(() => document.getElementById('n2').style.display = 'inline', 2000);
</script>
`;

test('all should be visible', async ({page}) => {
	await page.setContent(content);

	const n1 = page.locator('#n1');
	const n2 = page.locator('#n2');

	// all inputs seem to be visible
	await expect(n1).toBeVisible();
	await expect(n2).toBeVisible();

	// but now the same check fails
	await expect(n1).toBeVisible();
	await expect(n2).toBeVisible();
});
```

and would fail here:

```bash
       21 |      await expect(n2).toBeVisible();
       22 |
    > 23 |      await expect(n1).toBeVisible();
         |                       ^
       24 |      await expect(n2).toBeVisible();
       25 | });
       26 |
```

**Comment by aslushnikov** [comment]
@doberkofler ah, that's right. This kind of states are really hard to work with. Playwright is good at validating the "settled" state of the page; if you know what the settled state looks like, then you can assert it with a set of web-first assertions. Transient states (ones that will change shortly) are hard to catch and hard to automate since these are inherently racy. We'd recommend to design tests such that they never rely on "transient states".

**Comment by TomasHubelbauer** [comment]
This GitHub issue comes up for the Google search for "playwright wait for one of two selectors" and I believe as of Playwright 1.33 the best practice for that is this:

```
await expect(locatorA.or(locatorB)).toBeVisible();
if (await locatorA.isVisible()) {
  // Take path
}
else {
  // Take alternative path
}
```

This is useful for stuff like using existing test item (like profile creation, file upload etc.) if prior test ones have created one or creating one if not. This can sometimes be useful when the page being tested lives in an environment where data persistence is enabled and allowed for read-only tests (such that they don't muddy the environment's state). It is a form of a cache.

Source: https://stackoverflow.com/a/77288539/2715716
