### ISSUE TITLE
[Question] Why is waitForEvent('download') not working on webkit

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#19939]
I'm using the canonical example on how to to test file downloads and it works exactly as expected for `chromium` and `firefox` but fails with a timeout on `webkit`. Is this a known restriction on `webkit` or are there any workarounds to get this to work also on on `webkit`?

```typescript
// Start waiting for download before clicking. Note no await.
const downloadPromise = page.waitForEvent('download');
await page.getByText('Download file').click();
const download = await downloadPromise;
// Wait for the download process to complete
console.log(await download.path());
// Save downloaded file somewhere
await download.saveAs('/path/to/save/download/at.txt');
```

**Comment by aslushnikov** [comment]
> I'm using the canonical example on how to to test file downloads and it works exactly as expected for chromium and firefox but fails with a timeout on webkit.

@doberkofler Where does it fail with a timeout? Could you share us with an example that would illustrate what exactly you're doing? Also, what version of Playwright and operating system do you run?

P.S. We will appreciate if you follow issue template next time so that we have more information to look at!

**Comment by doberkofler** [comment]
I'm new to Playwright (from selenium) and was not sure if this is a problem, so I "just" created a question ;-)

**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 18.12.1
- Browser: WebKit
- Extra: 



## System:
 - OS: macOS 13.1
 - Memory: 1.50 GB / 16.00 GB
## Binaries:
 - Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
 - npm: 9.2.0 - ~/.nvm/versions/node/v18.12.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import {test, expect, type Page} from '@playwright/test';

const moduleConfig = {
	pageUrl: 'test.page', // internal test page
	pageTitle: 'Test Page'
};

// this is a mockup of the real login function that basically just expands the pageUrl to a full url
const login = async (page: Page, options: typeof moduleConfig) => {
	await page.goto(options.pageUrl);
	await expect(page).toHaveTitle(options.pageTitle);
};

test(moduleConfig.pageTitle, async ({page}) => {
	await login(page, moduleConfig);

	const [download] = await Promise.all([
		page.waitForEvent('download'),
		page.locator('xpath=//button[contains(@class, "excel-export")]').click()
	]);
	expect(download.suggestedFilename()).toMatch(/^TimeReport-.*\.xlsx$/);
});
```

**Describe the bug**

The error is reported in the `page.waitForEvent('download')` line:
```bash
Test timeout of 30000ms exceeded.
    page.waitForEvent: Page closed
    =========================== logs ===========================
    waiting for event "download"
    ============================================================
```

When using the `--debug` option and it seems as if the webkit browser would not automatically start the download but rather ask for a security confirmation and this blocks the test.
The same test works as  expected in chromium and firefox.

**Comment by aslushnikov** [comment]
@doberkofler cool, thanks a lot for the extra info! Any chance you can share a website that you try to test? This way we'll be able to run your snippet locally and debug what's going on.

**Comment by doberkofler** [comment]
In the process of trying to setup a test case including the server, I seem to have understood what causes the problem.

1) The server that provides the download link use the following http headers:
```
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
Content-Disposition: filename="TimeReport-.xlsx"
```
Please note that the `Content-Disposition` does not specify `inline` or `attachment`.
This does work as expected in the chromium and  firefox tests but fails in the webkit test where the browser seems to display the content of the file in binary on the screen instead of starting a download.
Strangely this only happens in the Playwright tests but not when actually using the regular Safari browser.

2) Changing the `Content-Disposition` to `Content-Disposition: attachment; filename="TimeReport-.xlsx"` does resolve the problem in Playwright. The MDN documentation does explicitly explain what happens if `attachment` is missing.

3) This resolves my specific problem with the test under webkit but does not fully explain why the bundled webkit browser would react differently from the chromium and firefox browsers and especially why the official Safari browser would also not have a problem.

**Comment by aslushnikov** [comment]
Awesome, I filed this separately so that a fellow team member will not need to read all our discussion here. Merging this into https://github.com/microsoft/playwright/issues/20089!

**Comment by doberkofler** [comment]
Thank you

**Comment by Bohdan-Hevlich** [comment]
@aslushnikov Hi, I have same issue reproducible on CICD in webkit browser, while localy it works. I am using buildkite CICD + docker#v5.8.0: image: mcr.microsoft.com/playwright:v1.38.1-focal. The error I get is : page.waitForEvent: Timeout 10000ms exceeded while waiting for event "download". The element I click while trying to download is :  <a data-remote="false" href="https://example/link/download" class="dropdown-item  " target="_blank"> </a>. While trying to download manualy I see that safari opens new window with notification about Do you want to allow downloads on
"example.link"?. Should I open new issue or we can discuss it here?
