### ISSUE TITLE
[BUG] page.locator stalls indefinitely, but inspector correctly highlights the element in the application

### ISSUE THREAD

**Issue by Slapbox** [microsoft/playwright#19936]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Linux (Ubuntu 22.04)
- Node.js version: 16.17.0
- Browser: Electron 
- Extra: Disabled all Electron fuses to ensure no interference

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { _electron as electron, } from 'playwright';

(async () => {
  const electronApp = await electron.launch(...)
  page = await electronApp.firstWindow();
  await page.getByPlaceholder("some text").fill('Hello world'); // or  await page.locator('#textbox').fill('Hello world'); -- both fail to proceed
})();
```

**Describe the bug**

The execution halts, but Playwright Inspector's pause/play buttons are grayed out and it shows `waiting for getByPlaceholder('some text')`

The inspector is able to correctly locate the element though, as shown by the highlighting/label

![image](https://user-images.githubusercontent.com/6835891/211177761-3fb8a6c6-8bee-4c2e-ae81-e0ec8fd57516.png)

**Comment by Slapbox** [comment]
I also just tried the latest nightly and it's the same. We use a preload script, but I tested against `secure-electron-template` and it works properly with their setup which also includes a preload script.

**Comment by aslushnikov** [comment]
@Slapbox I'm afraid there's not much we can say without a repro. Any chance you can share a repro with?

**Comment by Slapbox** [comment]
@aslushnikov thanks for your reply; I understand. I can't share a repro, so I continued to investigate on my own and I found that the issue only occurs when the inspector is invoked.

Upon pressing play, it runs through the code but doesn't affect the page if we run `cross-env PWDEBUG=1 playwright test --debug` - but if we just run `playwright test` then the test code is executed _AND_ affects the page (as expected.)

The problem occurs whether we set `PWDEBUG=1` or use the `--debug` flag, or use both together. 

Currently it's stuck waiting for the locator when we hit the issue, rather than executing without affecting the page as previously - maybe because we upgraded to `1.29.2`.

Does that indicate anything or provide any leads for further investigation?

**Comment by aslushnikov** [comment]
> Does that indicate anything or provide any leads for further investigation?

@Slapbox I'm still out of clues, unfortunately. Maybe you can come up with a new tiny electron application that reproduces the issue?

**Comment by Slapbox** [comment]
> Maybe you can come up with a new tiny electron application that reproduces the issue?

After a while trying; unfortunately I cannot reproduce it outside of our project so far :(

I'll update if I find anything new or manage to create a repro.

**Comment by Slapbox** [comment]
Apparently `electronApp.firstWindow()` was not returning our expected first window - but another window instead.

Interestingly. the blue highlight from `locator` seemed to be displayed on a page different from what `electronApp.firstWindow()` was returning. Even more interestingly, after rebuilding our app with identical input code, I can no longer reproduce this.
