### ISSUE TITLE
[BUG] failed to resolve aliased module in config.use.ctViteConfig

### ISSUE THREAD

**Issue by sskyy** [microsoft/playwright#19934]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 18.8.0
- Browser: Chromium

**Code Snippet**

`use` field in my `playwright-ct.config.ts` file

```javascript
use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
    ctViteConfig: {
      resolve: {
        alias : {
          'reactivity': resolve(__dirname, './test.ts'),
        }
      }
    }
  },
```

my test file `/test/App.spec.ts`
```javascript
import { test, expect } from '@playwright/experimental-ct-react';
import App from '../src/App';

import {autorun} from 'reactivity' //<-- here

test.describe('should work', () => {
    test('aa', async ({ mount }) => {
        autorun(() => {})
        const component = await mount(<App />);
        await expect(component).toContainText('Learn React');
    })
});

```

**Describe the bug**

console output:
```
Error: Cannot find module 'reactivity'
Require stack:
- /Users/camus.hou/Work/plwt/test/App.spec.tsx
- /Users/camus.hou/Work/plwt/node_modules/@playwright/test/lib/loader.js
- /Users/camus.hou/Work/plwt/node_modules/@playwright/test/lib/runner.js
- /Users/camus.hou/Work/plwt/node_modules/@playwright/test/lib/cli.js
- /Users/camus.hou/Work/plwt/node_modules/playwright-core/lib/cli/cli.js
- /Users/camus.hou/Work/plwt/node_modules/playwright-core/cli.js
- /Users/camus.hou/Work/plwt/node_modules/@playwright/test/cli.js
```

files in my package root dir:

```
node_modules
package-lock.json
package.json
playwright
playwright-ct.config.ts 
playwright-report
pnpm-lock.yaml
src
test.ts
```

I followed step by step in [https://playwright.dev/docs/test-components](https://playwright.dev/docs/test-components) several times, tried cleaning up my node_modules and other attempts, still got the same error message.

**Comment by aslushnikov** [comment]
@sskyy you try to import a browser-world package "reactivity" in node.js - this won't work. You can only import this package inside the browser.

Check out the [under the hood](https://playwright.dev/docs/test-components#under-the-hood) section in our documentation.

**Comment by aslushnikov** [comment]
I'll close this as per the comment above; please feel free to submit new issue if you think we can be helpful to you.
