### ISSUE TITLE
How to locate element using multiple attribute values?

### ISSUE THREAD

**Issue by caynebrister1** [microsoft/playwright#19940]
I was able to narrow the search for the element using 
```
pw.selectors.set_test_id_attribute("data-submit")
page.get_by_test_id('"1"')
```
But the problem is that there are 2 elements with the value "1" for the 'data-submit' attribute. The only other difference that is consistent between the two elements is the 'data-series' attribute. So, naturally I thought I'd chain the locators and change the test id attribute in-between the locators, but that didn't work. I think the reason this doesn't work is because it just uses the most recently set id attribute for both locators. Here is an example of that:
```
pw.selectors.set_test_id_attribute("data-submit")
reward_btn = page.get_by_test_id('"1"')
pw.selectors.set_test_id_attribute("data-series")
reward_btn.get_by_test_id("player").click()
```
Does anyone have some suggestions to locate a element using two attributes and the corresponding values?

**Comment by aslushnikov** [comment]
@caynebrister1 can you just use CSS to search by both attribute values?

```py
page.locator("[data-submit='1'][data-series='player']").click()
```

**Comment by aslushnikov** [comment]
My triage shift is nearing its end, so I'll close this as per above. Please feel free to file another issue if you think we still can be helpful!

**Comment by caynebrister1** [comment]
> My triage shift is nearing its end, so I'll close this as per above. Please feel free to file another issue if you think we still can be helpful!

Hello, I am so sorry I just noticed this response. I tried your suggestion, but had trouble getting it to work. I was able to locate the desired element using:
```
button = page.get_by_role("cell", name="Available").get_by_role("button").first
button.click()
```
When doing this i can see in the inspector that it finds the desired element (as seen [here](https://cdn.discordapp.com/attachments/1065668047853064212/1065668048633212991/image.png)). But for some reason I still get the following error:
```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("cell", name="Available").get_by_role("button").first
============================================================
```

**Comment by caynebrister1** [comment]
I believe the reason it times out is because it is an animated button. So i tried setting 'force' to True, but no luck:
`page.get_by_role("cell", name="Available").get_by_role("button").first.click(force=True)`
I still seem to get a timeout error because it is waiting for the button to become stable. But the button stays animated constantly, is there a way to bypass this check? I thought setting 'force' to true would bypass this but for some reason it doesn't work. Does anyone know why it doesn't work?
