### ISSUE TITLE
[Question] How do I locate a upper level element?

### ISSUE THREAD

**Issue by ooo2003003v2** [microsoft/playwright#19949]
Hello there,
In this situation, how do I select the 'modal-content' from 'close-btn-container'? 
What should I fill in the somthing in the following code? 
Thank you.

page.locator('.close-btn-container something somthing .modal-content')

```
<div class="modal-content">
   <div>
      <div>
         <div>
            <div class="close-btn-container"> <- start here
               ...
            </div>
         </div>
      </div>
   </div>
</div>
```

**Comment by ltsuda** [comment]
Can you try the following?

`const modal = page.locator(".modal-content").filter({ has: page.locator(".close-btn-container") })`
or
`const modal = page.locator(".modal-content", { has: page.locator(".close-btn-container") })`

I'm not sure about the second one, I remember that was a valid syntax before the `.getBy` methods was introduced.

https://playwright.dev/docs/locators#filtering-locators

**Comment by aslushnikov** [comment]
Closing as [this comment](https://github.com/microsoft/playwright/issues/19949#issuecomment-1375508160) is giving a great recommendation!
