### ISSUE TITLE
[BUG] RouteFromHAR response to multiple graphql requests with the same result.

### ISSUE THREAD

**Issue by macceth** [microsoft/playwright#19948]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Windows
- Node.js version: 16.14.0
- Browser: Chromium
- playwright Node.js version

Hello team. I'm trying to use playwright to test UI from HAR file recorded. The problem is my website call `graphql` multiple times in a page. But in HAR file recorded by `routeFromHAR` didn't have `postData` in it. So the responses serve from the first match all the time regardless of the body context of the request. I see that some of the requests that isn't graphql have postData in HAR. Below is the code I used and the recorded request in the HAR file.

```javascript
await page.routeFromHAR('sample.har', { update: true });
```

````
      {
        "startedDateTime": "2023-01-05T07:39:17.503Z",
        "time": -1,
        "request": {
          "method": "POST",
          "url": "https://testsite.test/api/activities/graphql",
          "httpVersion": "HTTP/1.1",
          "cookies": [],
          "headers": [],
          "queryString": [],
          "headersSize": -1,
          "bodySize": -1
        },
        "response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "cookies": [],
          "headers": [...],
          "content": {
            "size": -1,
            "mimeType": "application/json",
            "_file": "90735c4ac89f95d355c8ffdf53e4f376fdeaffd0.json"
          },
          "headersSize": -1,
          "bodySize": -1,
          "redirectURL": ""
        },
        "cache": {},
        "timings": { "send": -1, "wait": -1, "receive": -1 }
      },
````

Thank you for your good work. Please let me know if any further information needed.

**Comment by aslushnikov** [comment]
@macceth do you upload files by any chance? In this case, we don't embed `postData` to the HAR.

Also, a repro that we can run & debug locally would help us a lot!

**Comment by aslushnikov** [comment]
Unfortunately we won't be able to act upon this without a repro. Feel free to file another issue with a repro if this still bothers you.

Thanks!
