### ISSUE TITLE
foreach in playwright(typescript)

### ISSUE THREAD

**Issue by ranjCS** [microsoft/playwright#19943]
I have this question regarding using foreach in the the test. This is the test structure:

import { chromium , test } from "@playwright/test"
	test (`myTest`, async ({page}) => {
	const browser = await chromium.launch()
	const context = await browser.newContext()
	await page.goto("https://www.mypage.com")
	await page.locator('button').click()
	await page.fill("input[name='login']", "myname")
	await page.fill("input[name='password']", "maypass")

	// her starter datadriven test
	const mylist = [{number:"1234567"},{number:"1122331"}]
	mylist.foreach ( async data  => {
			await page.fill("//*[@id='sanNumberSelected']", data.nummer )
		})
	})

The problem is that data.nummer takes both numbers "1234567" and "1122331" at the same time, and this is not what is expected from foreach in this case. I have expected that the foreach loop will take one number at a time. Any idea what to do?

**Comment by mxschmitt** [comment]
You want this instead, since forEach() does not await the async operations:

```ts
for (const data of mylist) {
    await page.fill("//*[@id='sanNumberSelected']", data.nummer )
}
```

**Comment by ranjCS** [comment]
Thanks a lot Max
