### ISSUE TITLE
[BUG] "context.on('serviceworker'" times out in EC2

### ISSUE THREAD

**Issue by rony-arnac** [microsoft/playwright#19942]
**Context:**
- Playwright Version:  1.29.1
- Operating System: EC2 ubuntu-focal-20.04-amd64-server
- Node.js version: v18.9.0
- Browser: Chromium

```
## System:
 - OS: Linux 5.15 Ubuntu 20.04.3 LTS (Focal Fossa)
 - Memory: 14.28 GB / 15.44 GB
 - Container: Yes
## Binaries:
 - Node: 18.9.0 - /nix/store/0pyqsg3d1d3w04i0hrixkf253caafn8n-nodejs-18.9.0/bin/node
 - Yarn: 1.22.19 - /nix/store/qc25fpy2ivk178j400x0x4319z1c49zw-yarn-1.22.19/bin/yarn
 - npm: 8.19.1 - /nix/store/0pyqsg3d1d3w04i0hrixkf253caafn8n-nodejs-18.9.0/bin/npm
## Languages:
 - Bash: 5.1.12 - /nix/store/3pa0xk3mgmx7hqskg63gxviyw7f217i6-bash-interactive-5.1-p12/bin/bash
```

**Code Snippet**

I extend `test` by adding 

```
serviceWorker: async ({ context }, use) => {
    const worker = await new Promise<Worker>(resolve => {
      console.debug('Waiting for service worker...');
      context.on('serviceworker', currWorker => {
        console.debug('Got service worker');
        resolve(currWorker);
      });
    });

    await use(worker!);
  }
```

tests are run with the following command:

`xvfb-run --auto-servernum -s "-screen 0 1920x1080x24" -- npm run e2e`

**Describe the bug**

Locally, everything passes and works fine.
In EC2, it doesn't reach `console.debug('Got service worker');`

Output is:

```
Waiting for service worker...

  1) [chromium] › xxxx.e2e.ts:7:3 › xxx

    Test timeout of 15000ms exceeded while setting up "serviceWorker".
```

When I remove the `context.on` line, it doesn't timeout anymore..

**Comment by aslushnikov** [comment]
@rony-arnac the fixtures are initialized before the test is started. Why would a service worker appear before the page is navigated anywhere?

**Comment by rony-arnac** [comment]
@aslushnikov I forgot to mention I'm testing a chrome extension, so it should have a service worker from t=0

**Comment by aslushnikov** [comment]
@rony-arnac ah, sure! Seems to be related to EC2 somehow. My best bet would be that the server detects that you're coming from amazon cloud and serves a different version of a website. 

I'd recommend recording a trace and checking what's going on. Overall, however, this is something that falls outside of the Playwright project, so I'll close this.

**Comment by rony-arnac** [comment]
@aslushnikov it fails even before any trace is made. since it's an extension, it is loaded from a build folder by playwright and hence not affected by it being run from amazon.
which logs can help understand this issue?

**Comment by aslushnikov** [comment]
@rony-arnac you can try getting browser logs via the `DEBUG` env variable:

```sh
DEBUG=*browser* npx playwright test
```

**Comment by rony-arnac** [comment]
worked when I initialized the service worker when I needed it and not in the test expansion.. probably some latency issue in ec2 that reaches this state while locally it's much faster and doesn't happen

**Comment by rony-arnac** [comment]
@aslushnikov sorry I was wrong. It still got stuck. issue still persists :(

**Comment by rony-arnac** [comment]
OK OK I FIXED IT YAY!!

Two things I had to change:

1. stop using `PW_EXPERIMENTAL_SERVICE_WORKER_NETWORK_EVENTS=1` with version `1.29.1`.
2. `context.on('serviceworker', currWorker => {` was stuck while `context.serviceWorkers()` returned 1.. so I stoped using the listener and just got it from the other function
