### ISSUE TITLE
[Question] Is it possible to launch playwright chromium from another browser?

### ISSUE THREAD

**Issue by kaidoatgit** [microsoft/playwright#19947]
Hello,

Is it possible to have a button on web application that by clicking it, it launches a new browser that playwright will automate and do tests?

Thanks

**Comment by aslushnikov** [comment]
@kaidoatgit if the question is "is there a simple way to have a button on a website, that launches some browser on my computer?", then the answer is "no". Web as a platform is a pretty secure sandbox and doesn't allow launching binaries on your host machine. 

If you're interested in launching browser remotely, then this can be done - please google launching remote browsers! But this is not easy as well.
