### ISSUE TITLE
[BUG] Playwright inspector highlights the wrong line of code (with cucumber.js)

### ISSUE THREAD

**Issue by lsdebianchi** [microsoft/playwright#19944]
**Context:**
- Playwright Version: 1.23.2
- Operating System: Mac (OS 12.6, M1 Chip]
- Node.js version: v16.16.0
- Browser: Chromium
- Extra: PWDEBUG=1

**What happens**

I have done an integration of **cucumber.js** and **playwright** and mostly all is working well!
Cucumber is the main test runner and playwright is used inside the cucumber's steps (Given, Then) to control the browser.

I noticed that in debug mode the inspector is highlighting the wrong lines in the code: 

![2023-01-08_15-36](https://user-images.githubusercontent.com/28006430/211202615-bd59f965-e843-4d02-81ef-f4080ed0a839.jpg)

As you can see it's highlighting `await this.page.locator('input[name="identifier"]'...` But it hasn't executed `await this.page.goto("/")` yet!

So it's off by 1 line. But as I continue, whenever the inspector arrives to a new cucumber Given/Then function it drifts further more of +1 line.  So it quickly becomes unusable.

I think this could be caused by the fact that I am using playwright inside the cucumber functions, so the inspector has an hard time targeting the correct point in the code.

Someone knows what could be the cause and a possible hot-fix to alleviate this issue?

**Comment by aslushnikov** [comment]
@lsdebianchi any chance you can provide us with a small repro that we can run & debug locally? 

Also assigning Max since he was curious to look into this!

**Comment by lsdebianchi** [comment]
I think I can do that. It will surely give us more hints if on the true source of the issue.
In the following days I should be able to try and get some code for you.

**Comment by aslushnikov** [comment]
> In the following days I should be able to try and get some code for you.

Thank you. Instead of commenting here, I'd appreciate if you can file a new issue with a repro. This will give a fresh start for the discussion and for the next team member responsible for the issue triage.

**Comment by gnuechtel** [comment]
I cannot provide a repro repo yet, but I can confirm this bug from own experience with cucumber.js.

I tested various playwright versions and I think this bug was introduced with playwright 1.22.0.
With Playwright 1.21.1 and below line numbers just work fine with cucumber.js.

**Comment by gnuechtel** [comment]
Please reopen

**Comment by gnuechtel** [comment]
So here is the repro:

- fork [cucumber-playwright](https://github.com/Tallyb/cucumber-playwright) from @Tallyb -> I did it here: https://github.com/gnuechtel/cucumber-playwright
- add `page.pause()` to `playwright.steps` -> I did it in [my fork](https://github.com/gnuechtel/cucumber-playwright/tree/wrong-line-number)
- and voila the line number is wrong, when we execute `npm run debug`:

![image](https://github.com/microsoft/playwright/assets/3738251/804a6cf7-565a-41fd-be89-00d6d67da24d)

Now when we change the playwright version in `package.json` to `1.21.1` everything works as expected:

![image](https://github.com/microsoft/playwright/assets/3738251/8de571f4-abed-408b-9bde-bf545815c9a9)
