### ISSUE TITLE
[Question] Can cucumber be used with Playwright?

### ISSUE THREAD

**Issue by faizerestek** [microsoft/playwright#19959]
Since Playwright has its own runner, I want to understand whether Cucumber is something that can be integrated with the latest Playwright. If yes, then is there a documentation pertaining to it?

**Comment by ltsuda** [comment]
There's the following framework for cucumber, see the section `Can we use XXX from playwright in the playwright-cucumber project?` for more details.

https://github.com/Tallyb/cucumber-playwright
https://github.com/Tallyb/cucumber-playwright#can-we-use-xxx-from-playwright-in-the-playwright-cucumber-project

**Comment by aslushnikov** [comment]
Closing this as per [this comment](https://github.com/microsoft/playwright/issues/19959#issuecomment-1375697258)!
