### ISSUE TITLE
[Question] How can I use a single page for running all the test files. 

### ISSUE THREAD

**Issue by shilvigupta** [microsoft/playwright#19957]
We use webpack for running and building application. So my application just have one URL. How can I use playwright ? I tried using test-list but it is opening different pages for different spec files. I want to be on the same page and perform testing in a specific order. Also I want to use page object model.

**Comment by gauravgandhi1315** [comment]
@shilvigupta You can configure `baseURL` in playwright config file and then use `goto("/")` in your tests

https://playwright.dev/docs/test-configuration
baseURL - Base URL used for all pages in the context allows you navigating by using just the path
`page.goto('/settings')`

**Comment by shilvigupta** [comment]
@gauravgandhi1315 you got me wrong. I am asking how can I use page.goto() just once for all the test files.

**Comment by gauravgandhi1315** [comment]
@shilvigupta have you tried using `beforeAll` it works at global level and not at script level.

**Comment by shilvigupta** [comment]
@gauravgandhi1315 yes but then I will have to use a single test file I guess.

**Comment by aslushnikov** [comment]
@shilvigupta if you want to run all tests in a single worker and with a single page, then you can use a single test file, but import all the tests in it manually:

```ts
// a.spec.ts
import {} from './tests-1.ts';
import {} from './tests-2.ts';
```

However, I'm curious about this usecase; why would you want to limit yourself to a single worker?

**Comment by shilvigupta** [comment]
> 
// a.spec.ts
import {} from './tests-1.ts';
import {} from './tests-2.ts';

Here, How will I use a single page between different test files. And just importing test files wont work. Can you please elaborate.

**Comment by shilvigupta** [comment]
Hi @aslushnikov How can I write testcases for video/audio element? Like checking if it is playing, paused or ended. Once the video/audio is ended, a next button will be enable and clicked.

**Comment by aslushnikov** [comment]
> Hi @aslushnikov How can I write testcases for video/audio element? Like checking if it is playing, paused or ended.

> Since video is of 60 sec and timeout happens at 30 sec because of configuration.

@shilvigupta These are more of "how do I test things" question rather than an issue with Playwright; I'd recommend asking these questions on https://aka.ms/playwright/discord, or maybe on StackOverflow.

> Also I want to execute test cases in a specific order. 

Please see here: https://playwright.dev/docs/next/test-parallel#control-test-order
