### ISSUE TITLE
[Question] TypeError: cannot read properties of undefined (reading 'setAutoClose')

### ISSUE THREAD

**Issue by hoangngocanhskedulo** [microsoft/playwright#19952]
Hi,

Has anyone met this issue? 

I just go to Testing tab in VS Code, click Run test button in one of my test files and this issue happen. I have no idea what it is and how to fix. 

<img width="439" alt="image" src="https://user-images.githubusercontent.com/110459758/211258645-9de5bf4c-3508-427c-8961-063b6b52975b.png">

Playwright version 1.29
OS: Mac
Browser: Chromium

**Comment by gauravgandhi1315** [comment]
I have seen this issue before and updating the VS Code fixed the issue for me.

**Comment by hoangngocanhskedulo** [comment]
I restart VS Code and the issue is no longer there.
