### ISSUE TITLE
[Question] Does launchPersistentContext cause memory leaks if not closing browContext and just close page? 

### ISSUE THREAD

**Issue by icesmartjuan** [microsoft/playwright#19953]
**Context:**

- Playwright Version: 1.24.0
- Operating System: Linux
- Node.js version: 16.16.0
- Browser: Chromium/firefox/chrome (path set via `executablePath`)

Hi team, 

It seems `launchPersistentContext` keeps memory increasing if  `browContext` is not closed but just close its newly page, the `node-worker ` process keeps increasing. is there any insight on reusing browContext? thank you.

the usage flow is as below: 
```
browContext = await pw.launchPersistentContext('', {
                                        headless: false,
                                        executablePath: isUseBrowserPath ? browserPath : undefined, 
                                        javaScriptEnabled: jsEnabled,
                                        ignoreHTTPSErrors: true,
                                        userAgent: userAgent
                                    });
...
page = await browserContext.newPage();
...
await page.close()
```

**Comment by aslushnikov** [comment]
This is a known limitation; browser contexts behave as a unit of test isolation, so in order to cleanup all the page-related memory, context should be closed and re-created. 

See https://github.com/microsoft/playwright/issues/6319 for details!

**Comment by icesmartjuan** [comment]
Thank you @aslushnikov so much for your information, do you have any suggestion if we want to use the browserContext as long as possible?

**Comment by icesmartjuan** [comment]
btw, I saw comment that `page.close()` and `newPage ` each time seems work fine, which is what I do, but memory still increases in my app..
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/37887450/211503041-d830676c-f5db-4a23-95f4-e48b890f79ac.png">

**Comment by aslushnikov** [comment]
> btw, I saw comment that page.close() and newPage  each time seems work fine, which is what I do, but memory still increases in my app..

It doesn't; we store some debugging information at the browser context level. So browser context has to be closed and re-created in order to clean up the memory.
