### ISSUE TITLE
[Feature] Record video of tests with custom file name or retry functionality with video for failed tests

### ISSUE THREAD

**Issue by rajeevdixit05** [microsoft/playwright#19963]
**My requirement is-**
1. Record video of test with testMethod name
2. Only keep video of the failed tests with custom name or testMethod name
3. Retry with video for the failed tests in Playwright java sdk

**Comment by aslushnikov** [comment]
@rajeevdixit05 these all fully depend on the test runner you use in the Java world and don't have much to do with Playwright. The only thing is the "record a video" bit that Playwright supports out-of-the-box; please check out our [record videos](https://playwright.dev/java/docs/videos#record-video) documentation.
