### ISSUE TITLE
[Feature] Better output from failure with headless=false

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#1997]
Let's say you ssh to a remote host and run Playwright there. Then if you run with `headless=false` you get this error:

```sh
    Protocol error (Target.setAutoAttach): Target closed.
```

It would be nice if it gives an error message that is understandable in this scenario.

**Comment by burritoIand** [comment]
just ran into this when doing `await chromium.launch({ headless: false })` inside a docker container (goal being to be able to debug from host browser when needed e.g. docker run -p 9229:9229 <playwright> )

**Comment by pavelfeldman** [comment]
Ok, I think we are doing a much better job now explaining the exact errors that occurred during the launch. Please give it a try!
