### ISSUE TITLE
[Question] How do we migrate to 1.29.2 ?

### ISSUE THREAD

**Issue by ericpromislow** [microsoft/playwright#19971]
Our tests are now filled with errors like

```
TS2339: Property 'toHaveCount' does not exist on type 'MakeMatchers<void, Locator>'.
```

for code like the final line in this snippet:
```
const navPage = new NavPage(page);
const wslPage = await navPage.navigateTo('WSLIntegrations');
await expect(wslPage.integrations).toHaveCount(1, { timeout: 10_000 });
```

I understand the locator API changed in v 1.29, but haven't found out why are locator-based assertions break on the 1.29.2 bump (looks like there was no bump in our dependency checker for 1.29.1). https://playwright.dev/docs/writing-tests suggests that this code should continue to work.

Is this link pointing to obsolete docs? Is there another link I can use? Do I need to create explicit locators now?

**Comment by mxschmitt** [comment]
Breaking changes are not expected, I replied in your PR with my assumption why its ending up in weird errors.

**Comment by aslushnikov** [comment]
@ericpromislow I don't see any changes in the [1.29.1..1.29.2](https://github.com/microsoft/playwright/compare/v1.29.1...v1.29.2) range that would've cause this behavior.

Max's comment might be a reason indeed; you should drop `playwright` dependency and import everything from `@playwright/test`. So this line for example:

https://github.com/rancher-sandbox/rancher-desktop/blob/984ac6d1c892407f5ce9e17aed0f0878a71ab4e4/e2e/wsl-integrations.e2e.spec.ts#L10

will become:

```ts
import { ElectronApplication, BrowserContext, _electron, Page } from '@playwright/test';
```

**Comment by ericpromislow** [comment]
Thanks for the reply. I was logged in on another account yesterday and missed the prompt response.

Indeed dropping the `playwright` import fixed the code problem.

Sometimes the first electron test suite segfaults with a strange error message

(
```
Crashed Thread:        11

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000110
Exception Codes:       0x0000000000000001, 0x0000000000000110
Exception Note:        EXC_CORPSE_NOTIFY
...
Thread 11 Crashed:
0   Electron Framework            	       0x118545ad7 node::SetTracingController(v8::TracingController*) + 101991
1   Electron Framework            	       0x1185477e4 node::SetTracingController(v8::TracingController*) + 109428
2   Electron Framework            	       0x118546174 node::SetTracingController(v8::TracingController*) + 103684
3   Electron Framework            	       0x11853e25a node::SetTracingController(v8::TracingController*) + 71146
4   Electron Framework            	       0x111ceeaff uv_async_send + 847
5   Electron Framework            	       0x111d00f6c uv_free_interface_addresses + 2476
6   Electron Framework            	       0x111ceef10 uv_run + 320
7   Electron Framework            	       0x11853d95d node::SetTracingController(v8::TracingController*) + 68845
8   libsystem_pthread.dylib       	    0x7ff803aca4e1 _pthread_start + 125
9   libsystem_pthread.dylib       	    0x7ff803ac5f6b thread_start + 15
``` 
if you were interested), but this most likely has nothing to do with playwright/test.
Except that if I run the failing test specifically (`npm run test:e2e -- e2e/backend.e2e.spec.ts`)
it passes, but if I run the whole test suite (`npm run test:e2e`) I get this seg fault on the first test
only, which happens to be `backend.e2e.spec.ts`.

We have another blocker migrating to the recent version of electron.

**Comment by mxschmitt** [comment]
That's an Electron crash, I recommend reaching out to them, they know the best how to obtain crash logs etc. https://github.com/electron/electron

Maybe wait until you have updated to their latest version, since it might be fixed already.

**Comment by aslushnikov** [comment]
Closing this since the original issue is resolved!
