### ISSUE TITLE
[Question] How can I configure typescript when using Svelte component testing? 

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#19970]
I'm trying out component testing with Svelte, and have this component: 

**simple.svelte**
```typescript
import { test, expect } from '@playwright/experimental-ct-svelte';
import App from './simple.svelte';

test.use({ viewport: { width: 500, height: 500 } });

test('should work', async ({ mount, page }) => {
    const component = await mount(App);
    await page.pause();
    expect(component).toBeTruthy();
    // await expect(component).toContainText('Vite + Svelte');
});
```

but if my `simple.svelte` component includes types, like this
```svelte
<script lang="ts">

    const foo: string = 'bar';
</script>

<h1>Hello there</h1>
```

running component tests fails with: 

```
 1 |  <script lang="ts">
 2 |  
 3 |      const foo: string = 'bar';
                   ^
 4 |  </script>
ParseError: Unexpected token
```

How do I fix this error?

I created a repo to reproduce [here](https://github.com/alexbjorlig/svelte-playwright-cmpt-testing), just clone npm install and run tests.

**Comment by ambiguous48** [comment]
Using `vitePreprocess` seems to work.

1. `npm i -D @sveltejs/vite-plugin-svelte`

2. Create a `svelte.config.js` file
```js
import { vitePreprocess } from "@sveltejs/vite-plugin-svelte";

export default {
  preprocess: vitePreprocess(),
};
```

3. Add `type: module` to package.json

[PR](https://github.com/alexbjorlig/svelte-playwright-cmpt-testing/pull/1/files)

**Comment by alexbjorlig** [comment]
> 

It works - great 🙏 Thank you!
