### ISSUE TITLE
[Question] Regex in css selector ?

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#19974]
Hi all,

I have the following locator returning an array of string:
```js
await step.page.locator('.v2-annotation-element-distance-value').allTextContents();
```
Is that possible to do something like that:
```js
await step.page.locator('.v2-annotation-element-*-value').allTextContents();
```

I can have multiple element with only one difference, **distance** can be replaced by another thing.

Thank you.

**Comment by aslushnikov** [comment]
@kamelbou you can use something like [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors), it'd look like this:

```ts
await step.page.locator('[class*=v2-annotation-element-]').allTextContents();
```

Would it help?

**Comment by kamelbou** [comment]
> 

It helps thanks. I will try this approach (I don't know yet if it will work):

```js
step.page.locator('[class*=v2-annotation-element-]', {has: step.page.locator('[class$="value"]')});
```

Because if I look only `[class*=v2-annotation-element-]`I will have elements I don't want.
