### ISSUE TITLE
[BUG] afterAll\afterEach hook runs for skipped test

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#19984]
**Context:**
- Playwright Version: 1.29.1
- Browser: Chromium
## System:
 - OS: Windows 10 10.0.19044
 - Memory: 16.72 GB / 31.75 GB
## Binaries:
 - Node: 19.0.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

My test depends on the environment and some users have to be added manually or we should test them only when they are available. So I added this skip call according to how it's described in the documentation: https://playwright.dev/docs/api/class-test#test-describe-skip
```typescript
test.beforeAll(async ({ browser }) => {
   userModel = await usersApiClient.getUserByName(userName);
  test.skip(userModel === null, `User for this test (${userName}) is not available`);
}
```
If I use this approach:
- next steps of beforeAll hook are skipped - good.
- test is skipped - good
- afterAll\afterEach hook is running and fails because `userModel` is null and it tries to clean up the user.
So even if test is skipped from beforeAll hook, I have also to add condition to afterAll hook

**Comment by aslushnikov** [comment]
@denkorz  So the `test.skip()` only skips the scheduled **test**, not the hooks around it. So as of today, this is an expected behavior.

For your usecase, I'd recommend to shape `userModel` as a fixture. This way you can easily manage it's initialization and cleanup. See https://playwright.dev/docs/next/test-fixtures#without-fixtures for details!

**Comment by aslushnikov** [comment]
I'll close this as my triaging shift is nearing its end and the response above seems to address the question.

Feel free to file new issues if you think Playwright team can be helpful!
