### ISSUE TITLE
[Feature] Better locator generation capabilities

### ISSUE THREAD

**Issue by LongLiveY96** [microsoft/playwright#19981]
Sometimes the element locator recorded by codegen is too bloated, it could have been stable, reliable and short.
As an example, as shown in the figure, the recorded generated locator for an item in the dropdown list that I want to locate looks like this, but even though the name attribute is not specified, it is still locatable and unique.
***
![image](https://user-images.githubusercontent.com/23394317/211474966-cc11337b-396c-419b-aa61-aa6a93f844a4.png)
![image](https://user-images.githubusercontent.com/23394317/211475035-ab62633f-375a-4e48-8615-f318c9b52a56.png)

Recording generated by : `getByRole('menuitem', { name: '智能物联  XTXT  1级 UI自动化测试  XT  数据智能  AI技术  智慧多屏  智能运营  智能应用拉通一级分类22 ' }).getByText('智能物联')`
After optimization: `getByRole('menuitem').getByText('智能物联')`
***
I would like to know if playwright has a rule when generating locator that elements located by getByRole must contain the filter condition of name, if so, can this generation logic be optimized, for many beginners, locator is always a headache, it would be a great feat if the automatic locator feature could be further optimized.

**Comment by aslushnikov** [comment]
@LongLiveY96 This should be fixed on tip-of-tree already! could you please try to reproduce this with `@next`?

**Comment by LongLiveY96** [comment]
> @LongLiveY96 This should be fixed on tip-of-tree already! could you please try to reproduce this with `@next`?

I updated the version to 1.30.0 and now the locator generated for the above scenario is working properly, thanks.
