### ISSUE TITLE
[BUG] Navigation not working properly when click on element if headers & args --disable-web-security is added in playwright.config.ts

### ISSUE THREAD

**Issue by Faizan-Mamji** [microsoft/playwright#19988]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 18.11.0
- Browser: Chromium

**Code Snippet**

```ts
 test('Scenario-1: Navigate to laptop & select brands', async ({ page }) => {
        console.log('Scenario-1 executes!')
        categorySelection = new CategorySelection(page);
        await commonMethods.navigation_Page(businessHelper.ConfigData().laptopsCategory)
        await categorySelection.click_Category_Icon()
        await categorySelection.select_Category()
        await categorySelection.click_Category_Icon()
        getUrl = page.url()
        console.log("Scenerio-1 url is "+page.url())
        if (getUrl.includes('dell')) {
            console.log("Assert Successfull!")
        }
        await categorySelection.header_Text_Verify(businessHelper.ConfigData().headerText)
    })
```

playwright.config.ts

```ts
use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    ignoreHTTPSErrors: true,
    actionTimeout: 0,
    viewport: null,
    browserName: "chromium",

    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'abc.com',

    extraHTTPHeaders: {
      'Content-Type': 'application/json',
    },

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    launchOptions: {
      args: ["--disable-web-security",
      ],
    },
  },
```
When i passing args & header the  Issue what i am facing is its clicked but instead of navigate to dell page it navigates to home page.
And if i am not using these header & args so its working fine.
Can you please look into this issue?

<img width="507" alt="Screenshot 2023-01-10 at 4 15 21 PM" src="https://user-images.githubusercontent.com/39759529/211537786-82d2540b-61f7-4074-a0b2-c3cfb9244c47.png">

**Comment by Faizan-Mamji** [comment]
<img width="507" alt="Screenshot 2023-01-10 at 4 15 21 PM" src="https://user-images.githubusercontent.com/39759529/211538022-19acfd7e-81a4-40ab-9011-c0b578041803.png">

Screenshot added

**Comment by Faizan-Mamji** [comment]
Issue what i am facing is its clicked but instead of navigate to dell page it navigates to home page. Its working fine if i am not using headers & args

**Comment by Faizan-Mamji** [comment]
@mtodd can you please help me to resolve this?

**Comment by Faizan-Mamji** [comment]
@aslushnikov Can you please help me to resolve this issue?

**Comment by aslushnikov** [comment]
> Issue what i am facing is its clicked but instead of navigate to dell page it navigates to home page. Its working fine if i am not using headers & args

@Faizan-Mamji the `extraHTTPHeaders` config option doesn't make sense to me. Why would you add it?

**Comment by Faizan-Mamji** [comment]
> > Issue what i am facing is its clicked but instead of navigate to dell page it navigates to home page. Its working fine if i am not using headers & args
> 
> @Faizan-Mamji the `extraHTTPHeaders` config option doesn't make sense to me. Why would you add it?

I am executing api as well as UI cases in a same project thats why i need to add these.

**Comment by aslushnikov** [comment]
> I am executing api cases as well as UI cases in a same project thats why i need to add these.

@Faizan-Mamji  I'd recommend to split these into two, or at least separate API tests into a separate spec file and use a top-level `test.use()` to configure any extra HTTP headers there.

**Comment by Faizan-Mamji** [comment]
> > I am executing api cases as well as UI cases in a same project thats why i need to add these.
> 
> @Faizan-Mamji I'd recommend to split these into two, or at least separate API tests into a separate spec file and use a top-level `test.use()` to configure any extra HTTP headers there.

I have created 2 spec files 1 for ui & 1 for api. You mean i can use test.use() in api spec file?

**Comment by aslushnikov** [comment]
> I have created 2 spec files 1 for ui & 1 for api. You mean i can use test.use() in api spec file?

Precisely!

**Comment by Faizan-Mamji** [comment]
Ok let me try & will update you here if any help needed.
Thanks :)

**Comment by aslushnikov** [comment]
@Faizan-Mamji let's do vice versa: I'll close this issue for now. If you think we'll be able to help you further, please feel free to file a new question!
