### ISSUE TITLE
[Question] Execute a separate file in whole suite

### ISSUE THREAD

**Issue by hoangngocanhskedulo** [microsoft/playwright#19996]
Hi,

I have a test suite containing 16 test files. The 16th one has some special configurations that would make tests conflict with each other if whole suite is executed at the same time. Is there a possible way that I can execute whole suite at once excluding the 16th one, after other 15 files are done then 16th one is executed last?

Thanks,

**Comment by gauravgandhi1315** [comment]
@hoangngocanhskedulo You can put 16th tests into `global-teardown` file which would basically run after all your 15 scripts.

https://playwright.dev/docs/test-advanced

**Comment by hoangngocanhskedulo** [comment]
Thanks @gauravgandhi1315 

I'll try it out.
