### ISSUE TITLE
Browser not showed when execution come from global-setup

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#19998]
Hello team,

When launching a script with "Show browser" option activated in Playwright plugin in VSCode , I can see the browser launched from my script, but not the one that gets launched from my global-setup file (the login step).

Is it normal ?

Thank you,

Regards,

Johan

**Comment by aslushnikov** [comment]
@MehseinJohan in global setup, the browser is created manually by your code, so VSCode cannot affect the way it is launched. You should launch it with `headless: false` if you want to see it!

**Comment by MehseinJohan** [comment]
Hello,

But in my script, it's also the same : I'm using a browser created manually. I'm not doing any recording, I'm executing a script as follows : 

import { test, expect, PlaywrightTestConfig } from '@playwright/test';

//Reload main page prior to any test and check presence of bulk item
test.beforeEach(async ({page }) => {
  await page.goto('/');
});

test('test_test', async ({ page }) => {
  await expect(page).toHaveTitle(******);
  await page.close();
});

I can not set property such as headless in the global-setup.ts, can I ?

Regards,

Johan

**Comment by aslushnikov** [comment]
@MehseinJohan could you please paste here your `globalSetup` script?

**Comment by MehseinJohan** [comment]
Hello,

For sure :

_// global-setup.ts
import {expect, chromium, FullConfig} from '@playwright/test';

import  * as login from './common/data/users.json'
import { SignInPage } from "./common/pages/LssLogin";
let signInPage: SignInPage;
/*
* This is not a configuration file. Global setup indicates setup that needs to be done for all the tests before
* running the tests. It is a one time setup.
*/

//Sign in and save connected state
async function globalSetup(config: FullConfig) {
      console.log('111')
      await signInPage.loginToApplication();
      process.env.g_lss_sign = login.ADMIN_USER["username"];
      process.env.g_lss_office = login.ADMIN_USER["office"];
      process.env.g_lss_password = login.ADMIN_USER["password"];
      const browser = await chromium.launch();
      const context = await browser.newContext()
      const page = await context.newPage();
      try {
        console.log(config.projects[0].use.baseURL)
        await page.goto(String(config.projects[0].use.baseURL))
        await page.locator('#userAliasInput').fill(process.env.g_lss_sign);
        await page.locator('#officeIdInput').fill(process.env.g_lss_office);
        await page.getByRole('button', { name: 'Next' }).click();
        await page.locator('#passwordInput').fill(process.env.g_lss_password);
        await page.getByRole('button', { name: 'Next' }).click();
        // Save signed-in state to 'storageState.json'.
        await page.context().storageState({ path: 'storageState.json' });
        await page.close();
      } catch (error) {
        await page.close();
        throw error;

    }

}
  export default globalSetup;_

Thanks !

**Comment by aslushnikov** [comment]
@MehseinJohan so right here in global setup when you create a browser ,you can set `headless: false`:

```ts
const browser = await chromium.launch({ headless: false });
```

Hope it helps! Feel free to file new issues if you think we can be helpful.

**Comment by MehseinJohan** [comment]
Many thanks !
