### ISSUE TITLE
[Question] Are some languages better supported in regards to Codegen and Trace Viewer?

### ISSUE THREAD

**Issue by ufst-ask** [microsoft/playwright#19990]
From https://playwright.dev/docs/languages I understand that all supported languages are equally well supported, correct?

However, Codegen is more difficult to setup with Java than with Node.js. And I recently ran into the following issue with Java which I don't think was a problem with Node.js:
https://github.com/microsoft/playwright/issues/17960 

So when it comes to Codegen and Trace Viewer, does that work better with one language than others? Which one and by how much?

**Comment by aslushnikov** [comment]
@ufst-ask all languages are equal when it comes to CodeGen and TraceViewer.

However, majority of our users use Node.js, so they file more bugs, and thus more things are getting fixed there.
If you don't care which language to use, we'd recommend using Node.js.

**Comment by ufst-ask** [comment]
Thank you @aslushnikov 
I will take that with me in my recommendations to the stakeholders.
My understanding is that Java would be much easier for us, I hope that we can avoid the worst setbacks by being late to the party and delay our updates to the latests versions.
