### ISSUE TITLE
[BUG] Playwright opens two tabs on browser when running in Non Incognito mode

### ISSUE THREAD

**Issue by soumya-kar** [microsoft/playwright#20007]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac] Windows
 - Python 1.28
- Browser: [e.g. All, Chromium, Firefox, WebKit] NA
- Extra: [any specific details about your environment]

When running on Non incognito mode Playwright opens two tabs on Browser.
Here is the code which I am executing:
```py
import os
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    app_data_path = os.getenv("LOCALAPPDATA")
    user_data_path = os.path.join(app_data_path, 'Chromium\\User Data\\Default')
    context = playwright.chromium.launch_persistent_context(user_data_path, channel='chrome', headless=False, args=['--start-maximized'], no_viewport=True)
    page = context.new_page()
    page.goto("https://www.google.com/")
    page.wait_for_timeout(5000)

with sync_playwright() as playwright:
    run(playwright)
```

It seems like a bug to me. Please have a look.

**Comment by aslushnikov** [comment]
@soumya-kar non-incognito context cannot exist without a page, so it has one by default. You can use it for your needs if you'd like, like this:

```py
    context = playwright.chromium.launch_persistent_context(user_data_path, channel='chrome', headless=False, args=['--start-maximized'], no_viewport=True)
    page = context.pages[0]
    page.goto("https://www.google.com/")
```

Hope this helps!
