### ISSUE TITLE
.ts extension not recognized by VS Code 

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20002]
Hello,

I have an issue using the Playwright plug-in for VS Code. According to the convention, .spec.ts extension would rather fit unit tests, and .ts other kind of tests. As E2E tester, I would like to rename my files from .spec.ts to .ts but when I do so, file is not recognized anymore as a test by VSCode (hence I can't launch them). 

Is there something particular to configure ?

Thank you in advance,

Regards,

Johan

**Comment by gauravgandhi1315** [comment]
I had this issue at one time and reinstalling fixed the issue for me.

**Comment by MehseinJohan** [comment]
I have already but it's not the case unfortunately.

**Comment by aslushnikov** [comment]
@MehseinJohan you should set [`testMatch`](https://playwright.dev/docs/next/api/class-testproject#test-project-test-match) option in your `playwright.config.ts` to match typescript files.

The following simple config worked for me:

```ts
// playwright.config.ts
export default {
  testMatch: '*.ts',
};
```

Hope this helps! Feel free to file another issue if you think we can be helpful.

**Comment by MehseinJohan** [comment]
Hello,

It worked, thank you !

Johan
