### ISSUE TITLE
[BUG] Page.click leads to 'Element has moved during the action'

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2000]
**Context:**
- Playwright Version: 0.15+
- Operating System: Docker / recommended image

**Code Snippet**

Still working on a small reproducible, but seems to be a bigger more rare edge case.

```js
await page.click('.ant-picker-today-btn')
```

**Describe the bug**

In Playwright <= 0.14 the used snipped for clicking on an element has worked. In 0.15+ it leads to `Element has moved during the action` in around 80%+ of the cases.

Related PR: #1942
cc @dgozman

**Comment by jperl** [comment]
If the element moved to a place that is now clickable, is the click retried?

**Comment by jperl** [comment]
Is this error thrown only if the element moved to a place that is no longer clickable?

Hopefully the the click can be auto-retried by playwright, if the element moved somewhere that it is clickable.

**Comment by mxschmitt** [comment]
Issue could be fixed by adding a `await page.waitForTimeout(100)` before the actual click action. But that seems just like a workaround for me instead of fixing the actual issue.

**Comment by hlawuleka** [comment]
But why do we have to add a timeout? I mean is 100 the base number? What happens if you put 1? and why?. I ask because we might be hacking a bigger problem, which if not addressed may bite back.

**Comment by codejamninja** [comment]
I am having this same issue. I am able to locate it just fine, but get the following error when clicking.

```
Element has moved during the action
```

**Comment by AutoSponge** [comment]
Sounds like you're racing the JS animation and rendering on the "today button" modal overlay container. The element gets rendered, waitFor resolves, animation moves and gradually makes visible the element/container, click attempts to engage.

**Comment by codejamninja** [comment]
@AutoSponge so how would I get the button to click? I do not have the ability to change the behavior of the button.

**Comment by AutoSponge** [comment]
@codejamninja The modal appears by animating opacity after placing the elements. You should wait for the modal to be visible.

**Comment by codejamninja** [comment]
Ok, thanks

**Comment by aslushnikov** [comment]
> Still working on a small reproducible, but seems to be a bigger more rare edge case.

@mxschmitt so is this still relevant?

**Comment by mxschmitt** [comment]
Workaround was previously to use the text selector for that. But now its fixed, no clue which PR but its fixed now, yey.
