### ISSUE TITLE
[Question] Mouse position after .hover on an element

### ISSUE THREAD

**Issue by jerryking58** [microsoft/playwright#20019]
I have a tooltip which is shown when the mouse is hovered on an element. The tooltip will be dismissed if the mouse moves out of the element. 

I was wondering if the mouse will keep on the element after a .hover call on the element. Or will the mouse's position be reset after the hover call ends?

Use this method to trigger the hover event. https://playwright.dev/docs/api/class-locator#locator-hover

Thanks.

**Comment by aslushnikov** [comment]
> I was wondering if the mouse will keep on the element after a .hover call on the element. 

@jerryking58 Yes, the mouse will stay over the element.
