### ISSUE TITLE
[Feature] Ability to match a selected area of the screen and then click on it

### ISSUE THREAD

**Issue by MikeGalyen** [microsoft/playwright#20017]
Hi there! 

I'd like to suggest adding the functionality to compare a selected area of the screen instead of only full screenshots and then be able to click that area if it exists on the screen. This would be similar to the way Sikuli allows users to capture just a selection of the screen and later use that image in automation to check if it exists and to click on it.

This would be useful for my QA department to test and automate parts of our application GUI that don't allow for the usual methods of location and selection like an area of the page that isn't always the same image but needs to be clicked.

Thanks so much for considering new features!!!

**Comment by aslushnikov** [comment]
> I'd like to suggest adding the functionality to compare a selected area of the screen instead of only full screenshots and then be able to click that area if it exists on the screen. This would be similar to the way Sikuli allows users to capture just a selection of the screen and later use that image in automation to check if it exists and to click on it.

@MikeGalyen I'm not sure I follow. Would you mind sharing a short video explaining & showing how it's done in Sikuli?

**Comment by MikeGalyen** [comment]
@aslushnikov here's an example of automating a website front end this way in sikuli. I know there are other ways to do this on a website like this but in other cases we aren't able to locate things the same ways so our only option is to locate things visually on the screen. The main ask is to be able to match specific part of GUI rather than the whole thing like matching with just what's in the red square in the image and then being able to perform an action like clicking on that area.

Screen Shot 2023-01-12 at 10.11.56 AM

https://user-images.githubusercontent.com/36580986/212103755-0ecb401c-222a-445b-a74f-8d9eff01a740.mov

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
