### ISSUE TITLE
pip3 install pytest-playwright fails

### ISSUE THREAD

**Issue by vskatusa** [microsoft/playwright#20014]
Hi, I tried to install using

> pip3 install pytest-playwright

But fails 

ERROR: Cannot install pytest-playwright==0.0.10, pytest-playwright==0.0.11, pytest-playwright==0.0.12, pytest-playwright==0.0.2, pytest-playwright==0.0.3, pytest-playwright==0.0.4, pytest-playwright==0.0.4.1, pytest-playwright==0.0.5, pytest-playwright==0.0.6, pytest-playwright==0.0.7, pytest-playwright==0.0.8, pytest-playwright==0.0.9, pytest-playwright==0.1.0, pytest-playwright==0.1.1, pytest-playwright==0.1.2, pytest-playwright==0.2.0, pytest-playwright==0.2.1, pytest-playwright==0.2.2, pytest-playwright==0.2.3 and pytest-playwright==0.3.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    pytest-playwright 0.3.0 depends on playwright>=1.18
    pytest-playwright 0.2.3 depends on playwright>=1.13
    pytest-playwright 0.2.2 depends on playwright>=1.13
    pytest-playwright 0.2.1 depends on playwright>=1.13
    pytest-playwright 0.2.0 depends on playwright>=1.13
    pytest-playwright 0.1.2 depends on playwright>=1.10.0
    pytest-playwright 0.1.1 depends on playwright>=1.10.0
    pytest-playwright 0.1.0 depends on playwright>=1.10.0
    pytest-playwright 0.0.12 depends on playwright>=1.9.0
    pytest-playwright 0.0.11 depends on playwright==1.8.0a1
    pytest-playwright 0.0.10 depends on playwright>=0.170.0
    pytest-playwright 0.0.9 depends on playwright>=0.0.4
    pytest-playwright 0.0.8 depends on playwright>=0.0.4
    pytest-playwright 0.0.7 depends on playwright>=0.0.4
    pytest-playwright 0.0.6 depends on playwright>=0.0.4
    pytest-playwright 0.0.5 depends on playwright>=0.0.4
    pytest-playwright 0.0.4.1 depends on playwright==0.0.4
    pytest-playwright 0.0.4 depends on playwright
    pytest-playwright 0.0.3 depends on playwright
    pytest-playwright 0.0.2 depends on playwright

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by ltsuda** [comment]
Please, can you provide more information about your system? Like what OS, what python version, etc.

**Comment by vskatusa** [comment]
Sure here is the screen shot

Linux raspberrypi 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Jan 11 00:23:56 2023 from 192.168.0.78

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

pi@raspberrypi:~ $ python --version
**Python 3.9.2**
pi@raspberrypi:~ $

**Comment by ltsuda** [comment]
Huum, although your raspberry OS is Debian 11 (bullseye), the official support is for AMD architecture, not `arm`

see the following issue:
https://github.com/microsoft/playwright/issues/18319

**Comment by aslushnikov** [comment]
Please upvote https://github.com/microsoft/playwright/issues/18319 to prioritize it accordingly!

**Comment by Liftu** [comment]
Any news on that? I still have the error on 1.32.1

**Comment by Liftu** [comment]
What I understand is that playwright isn't available for arm32 ? will it ever be ?

**Comment by jrosa-digiwest** [comment]
Are there any plans to support armv7l machines?
