### ISSUE TITLE
[BUG] electronApp.close() assumes that closing windows exits app - but it should invoke app.quit() instead

### ISSUE THREAD

**Issue by Slapbox** [microsoft/playwright#20016]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Linux
- Node.js version: 16.18.0
- Browser: Electron
- Extra: In an app that closes to system tray

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// ...
await electronApp.close(); // Never resolves because our app does not allow the primary window to be closed
```

**Describe the bug**

`electronApp.close()` should exit the app via `app.quit()`, and probably be renamed accordingly in Playwright to `electronApp.quit()`

Relevant Electron docs for understanding the issue:

- https://www.electronjs.org/docs/latest/api/app#appquit
- https://www.electronjs.org/docs/latest/api/app#event-window-all-closed

**Comment by aslushnikov** [comment]
@Slapbox Playwright calls `app.quit()` and waits for the browser context to be gone, but the underlying browser does not quit. Due to this, we did not resolve the promise.

Do you ever call quit manually? Does it quit for you? What happens?

**Comment by Slapbox** [comment]
> Do you ever call quit manually?

No we don't. I'm not sure how one would do that. I know I saw some guide for `evaluate` to do something like this, but from [the page in the docs](https://playwright.dev/docs/api/class-electronapplication#electron-application-evaluate) I don't see any example and I can't find it again. Can you advise how we would run this?

**Comment by aslushnikov** [comment]
@Slapbox I mean - how does application user quit the application?

**Comment by Slapbox** [comment]
Oh I see. They quit via right-clicking the icon in the system tray and selecting "Quit." I've tried to achieve this using Electron Playwright Helpers but due to [this issue](https://github.com/spaceagetv/electron-playwright-helpers/issues/16) I'm not able to quit that way either.

Is there any way built into Playwright to achieve this? I don't think so from my perusing the docs.

Thanks again @aslushnikov!

**Comment by aslushnikov** [comment]
@Slapbox you have access to the underlying Electron process: [`electronApp.process()`](https://playwright.dev/docs/api/class-electronapplication#electron-application-process).

You can try killing the process using Node.js API's - e.g. [`child_process.kill()`](https://nodejs.org/api/child_process.html#subprocesskillsignal). 

This is probably the best we can suggest!  Would it work?

**Comment by Slapbox** [comment]
@aslushnikov that will at least kill the app, but not very gracefully.

I think what we really need is for the Electron Playwright Helpers library to handle accessing the application tray menu as I guess that's outside of the scope of Playwright.

Related issue: https://github.com/spaceagetv/electron-playwright-helpers/issues/16

**Comment by aslushnikov** [comment]
sounds good. I'll close this in favor of https://github.com/spaceagetv/electron-playwright-helpers/issues/16 then!
