### ISSUE TITLE
[BUG] one pixel difference caused visual test fail 

### ISSUE THREAD

**Issue by chloechao** [microsoft/playwright#20015]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Linux
- Node.js version: 14
- Browser: Chromium, WebKit
- Extra: 

**Describe the bug**
Same test failed in different test run due to 1 pixel difference in the screenshot with the error message:
```
Screenshot comparison failed:

  Expected an image 393px by 420px, received 393px by 421px. 
```

Expected image:
![image](https://user-images.githubusercontent.com/12148061/211697737-9a10d0b8-6c25-408d-8e76-45ff1de62252.png)
Actual image:
![image](https://user-images.githubusercontent.com/12148061/211697781-ea1e3514-3507-490f-bfdb-6869e5827bf3.png)
This failure happened randomly and cannot be reproducible all the time. I noticed that [the similar issue has been reported before](https://github.com/microsoft/playwright/issues/18827) and the error message is from [this line in the source code](https://github.com/microsoft/playwright/blob/8167f8bf548308ad8c6f1188508aadee84f26023/packages/playwright-core/src/utils/comparators.ts#L56), code snippet:
```
  if (expected.width !== actual.width || expected.height !== actual.height) {
    return {
      errorMessage: `Expected an image ${expected.width}px by ${expected.height}px, received ${actual.width}px by ${actual.height}px. `
    };
  }
```

Can we have a setting to configure the allowed pixel difference instead of having a hard image size check before comparing the images?

Thanks in advance for any suggestions and help.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/20015.

**Comment by yury-s** [comment]
@chloechao are you taking screenshot of entire page or a particular element? Can you share the code that takes the screenshot?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by bbthorntz** [comment]
For anyone reading this, we solved this issue by changing the code from:

```tsx
await expect(locator).toHaveScreenshot('path/to/screenshot.png');
```

To:

```tsx
const box = await locator.boundingBox();
await expect(page).toHaveScreenshot('path/to/screenshot.png', { clip: box });
```

**Comment by jackmatt2** [comment]
> For anyone reading this, we solved this issue by changing from locator-based screenshots to page-based screenshots in-conjunction with the `clip` parameter. For example:
> 
> ```tsx
> await expect(locator).toHaveScreenshot('path/to/screenshot.png');
> ```
> 
> Is changed to:
> 
> ```tsx
> const box = await locator.boundingBox();
> await expect(page).toHaveScreenshot('path/to/screenshot.png', { clip: box });
> ```

@bbthorntz life saver.  Randomly since last Friday our "fullPage" screenshots have started failing.  It appears the viewport part of the screenshots showed no errors but the offscreen section showed diffs that were not visible to the human eye.  I'm not sure if this is a bug with "fullPage" or not but your solution has fixed it.

```
    const root = await page.locator('#root') // React root DOM node
    const box = await root.boundingBox()
    if (box != null) {
      await expect(page).toHaveScreenshot({
        fullPage: true,
        timeout: 6_000,
        animations: 'disabled',
        clip: box,
      })
    }
```

**Comment by wellss12** [comment]
@bbthorntz 
Thank you so much！

**Comment by MikulasMascautanu** [comment]
I'm still experiencing this issue when using locator-based screen comparison. The above workaround works for me only for a few cases. For the rest I cannot use visual comparison.

**Comment by 0000day** [comment]
I kinda solved this after a long headache-session. Maybe someone finds it useful:
https://github.com/microsoft/playwright/issues/35014#issuecomment-4671604199
