### ISSUE TITLE
[Question]How many test cases can we run using two workers on Azure pipeline?

### ISSUE THREAD

**Issue by yash-lohakare** [microsoft/playwright#20018]

**Comment by mxschmitt** [comment]
The answer of this question depends fully on how long you want to wait for your test execution to finish. If 1 hour is fine for you, then you can run A LOT of tests.

But generally speaking we recommend sharding to reduce the execution time of larger test suites see [here](https://playwright.dev/docs/test-parallel) with [a matrix](https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/jobs-job-strategy?view=azure-pipelines).
