### ISSUE TITLE
[BUG] playwright component testing does not work alongside an existing playwright install

### ISSUE THREAD

**Issue by davidAtInleague** [microsoft/playwright#20011]
**Context:**
- Playwright Version: `npx playwright --version` --> `1.25.0`
- Operating System: ubuntu 20.04
- Node.js version: 16.19
- Browser: chromium

**Code Snippet**

```javascript
import { test } from '@playwright/experimental-ct-vue';
test('should work', async ({ mount }) => {});
```

**Describe the bug**

`yarn run test-ct` yields
```
Running 0 tests using 0 workers
Error: pwct/xlel.spec.ts:5:29: Playwright Test did not expect test() to be called here.
Most common reasons include:
- You are calling test() in a configuration file.
- You are calling test() in a file that is imported by the configuration file.
- You have two different versions of @playwright/test. This usually happens
  when one of the dependencies in your package.json depends on @playwright/test.

   at ../node_modules/@playwright/experimental-ct-vue/node_modules/@playwright/test/lib/util.js:183

  181 | }
  182 | function errorWithLocation(location, message) {
> 183 |   return new Error(`${formatLocation(location)}: ${message}`);
      |          ^
  184 | }
  185 | function expectTypes(receiver, types, matcherName) {
  186 |   if (typeof receiver !== 'object' || !types.includes(receiver.constructor.name)) {
```
I stopped it in a debugger and found that it is indeed calling into the wrong version of "@playwright/test" as described in the error block above; I have both

a) `node_modules/@playwright/test/lib/globals.js`

b) `node_modules/@playwright/experimental-ct-vue/node_modules/@playwright/test/lib/globals.js`

So globals set in (a) don't make it over to (b). Is this a configuration problem on my end, or is it not possible to use component testing in a project that already has an existing `@playwright/test` install?

**Comment by aslushnikov** [comment]
> Is this a configuration problem on my end, or is it not possible to use component testing in a project that already has an existing @playwright/test install?

@davidAtInleague You should make sure that `@playwright/test` and `@playwright/experimental-ct-vue` are the same version in your `package.json`!

**Comment by davidAtInleague** [comment]
Oh that did it! Now I have other problems but this issue is resolved, thanks.
