### ISSUE TITLE
[Feature] Adding a dashboard-like integration with Azure DevOps to view test results

### ISSUE THREAD

**Issue by shtlrs** [microsoft/playwright#20028]
I haven't been able to find a similar issue/feature request so I thought I'd go ahead and make one.

Do you think of adding an integration with Azure DevOps where we can view tests results ?

Currently, there's a built-in integration for tests written in .NET to view their results, but also the run history and success/failure ratios. Here's an example:
![image](https://user-images.githubusercontent.com/48383734/211785724-8d4d4bc3-6656-4192-9ba8-8832e18c8700.png)

Currently, the only way to achieve this is by downloading artifacts, but it's becoming very tedious to do so with a huge test suite, and cases where a lot of tests are failing since the size of the artifacts grows along with the number of tests + test traces retention strategy.

It would be really beneficial to be able to directly see that in the same fashion, and to show the run history of such tests.

**Comment by aslushnikov** [comment]
This looks like a better Azure DevOps integration; I'll fold this into https://github.com/microsoft/playwright/issues/14839
