### ISSUE TITLE
How to create a custom function which runs before every spec file ?[Question]

### ISSUE THREAD

**Issue by Ashasian** [microsoft/playwright#20029]
I have a function that should be called before every spec file and i want this function to be reusable by all spec files without adding it  in the beforeAll of each file. With this , the test should check the tag and skip the tests
```
function manageCountryTags(tag) {
 
			if (tag.includes('#NA#')) return false;
			//Check available in country env
}
```

the below code is what i currently use for checking the tag
```

const { test, expect } = require("../fixtures/basePage");
 
const tag = process.env.SERVER !== 'pre' ? '#NA#' : '#DE#';  

 
let page = {};
 
test.describe.serial(`${tag} - Check the login functionality works for a user with a customer role and correct password`, function () {
  test.skip(tag == '#NA#');

  test.beforeAll(async ({ browser, dataEnv }) => {
    
    page = await browser.newPage(); //Create a new Page instance
   
  });
```
Here , the user gets the tag from the 'tag' variable and checks from the manageCountryTags function and skips the tests if it is #NA#. 
I want the  test.skip(tag == '#NA#') not be added in all the files explicitly and just call the function **manageCountryTagsbefore** every test runs. Is this possible?

**Comment by aslushnikov** [comment]
@Ashasian so far there's no way to do so; you'll have to manually import that `test.beforeEach()` function in each test file.

**Comment by jim-sears-thrivent** [comment]
@Ashasian - would grep work for you, to execute only the tests you want? 
npx playwright test --grep "smoke"
The grep is reqular expression so it supports "not" and all the usual variants. 
[https://timdeschryver.dev/blog/create-and-run-playwright-test-sets-using-tags-and-grep](https://timdeschryver.dev/blog/create-and-run-playwright-test-sets-using-tags-and-grep)
