### ISSUE TITLE
Playwright Java -nodejsx was unexpected at this time ?

### ISSUE THREAD

**Issue by mEklavya** [microsoft/playwright#20021]
**Context:**
- Playwright Version: 1.26.0 and 1.28.0
- Operating System: Windows
- Node.js version: 16.15.1
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: Playwright java and utilizing system node js path, refer env properties

**Code Snippet**
public static void main(String[] args) {
		try (Playwright playwright = Playwright.create()) {
			Browser browser = playwright.chromium()
					.launch(new BrowserType.LaunchOptions().setHeadless(false).setSlowMo(50));
			Page page1 = browser.newPage();
			page1.setDefaultTimeout(90000);
			page1.navigate("http://playwright.dev");
			System.out.println(page1.title());

		}
	}

While utilizing the system nodeJS path, not able to proceed and getting below error
Files\nodejsx was unexpected at this time.
Exception in thread "main" com.microsoft.playwright.PlaywrightException: Failed to read message from driver, pipe closed.

Add any other details about the problem here.

Error Screenshot
![image](https://user-images.githubusercontent.com/42370888/211755222-2b546b26-a703-4adc-b7fb-275a44c194a0.png)

Env properties
![image](https://user-images.githubusercontent.com/42370888/211755079-ef697d17-c00d-4051-91de-bd065adccd9f.png)

**Comment by mxschmitt** [comment]
This should be fixed by https://github.com/microsoft/playwright/pull/19801.

So waiting for a new Playwright for Java version, aka. 1.30 should fix that.

**Comment by aslushnikov** [comment]
Marking as fixed then!
