### ISSUE TITLE
Issue to call external function in globalsetup

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20026]
Hello,

In my globalsetup file I'm trying to run a function that is defined in another page (within a class), as such : 

```ts
_import { SignInPage } from "./common/pages/LssLogin";
let signInPage: SignInPage;

async function globalSetup(config: FullConfig) {
      await signInPage.loginToApplication();
}
  export default globalSetup;_

The function is defined as such in the LssLogin page : 

_export class SignInPage {
  readonly page: Page;

  constructor(page: WebActions) {
      webActions = page
      //commonFunctionsPage = new CommonFunctionsPage(page)

  }

  async loginToApplication(): Promise<void> {
    console.log('test login function')
  }_
```

However, whenever I'm running a test, nothing happens. When I say nothing, I mean that the test is not even launched, so I guess something is wrong in my calls. Could you please help

Many thanks,

Regards,

Johan

**Comment by aslushnikov** [comment]
Hey @MehseinJohan, this question is more of a general programming question rather than a Playwright question. I'd recommend asking this on Stackoverflow, or maybe even https://aka.ms/playwright/discord
