### ISSUE TITLE
[BUG] Tests are failing when running Playwright with Show browser

### ISSUE THREAD

**Issue by JoyJanssen** [microsoft/playwright#20023]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac & Windows
- Node.js version: 18.12.1
- Visual Studio Code version: 1.74.3
- Playwright for VSCode extension version: 1.0.3
- Browser: All
- Extra: 
     - [x] Show browser

**Describe the bug**

When running the tests using the Playwright extension with 'Show browser' selected some tests are failing. There is no pattern in the fail behavior. The error that occurs is the following:

```
browserContext.newPage: Error: Object with guid page@6cdc0d672d8709ce6e4ce1fc43a2d8cd was not bound in the connection
```

This error does not occur when the 'Show browser' checkbox is unchecked. 
The error also does not occur when a new page is created inside the test (even when the 'Show browser' checkbox is checked).

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue with it, and link to this one.
