### ISSUE TITLE
[BUG]Browser is picking window OS (AAD) login profile instead of Browser login  with chromium its working on MAC but not on Windows machine

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#20036]
Playwright Version: [1.28.1]
Operating System:  Windows
Maven project with JAVA
Browser: [chromium]
Extra:
Describe the bug
We need to automate the testing of Internal Website which is SSO enabled. We see that PW starts the browser in incognito (which is our req. aswell) but the page loads using the current SSO user cred thus skipping the Login screen. 

Please try this scenario in any of your MSFT internal app which will open Login screen when accessed through Incognito.

We are evaluating PW for our automation purpose and this is a blocker to get started as we have test users with different access roles which cannot be tested if we don't get the SSO Login screen. Happy to help you with any specific logs incase needed. Looking forward.

Note: Below Code is perfectly working on **MAC** but not on **windows** amchine

Code Snippet

// Please include a snippet of HTML that shows an example of the content

```java
public static void main(String[] args) {
  try (Playwright playwright = Playwright.create()) {
                BrowserType chromium = playwright.chromium();
                BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
                launchOptions.setHeadless(false);
                Browser browser= chromium.launch(launchOptions);
                launchOptions.setArgs(Collections.singletonList("--auth-server-whitelist='_'"));
     
                BrowserContext browserContext=browser.newContext(new Browser.NewContextOptions().setHttpCredentials(userName,password));

            page.navigate(applicationurl);
            page.getByText("Sign in").click();
```

**Comment by yury-s** [comment]
> We need to automate the testing of Internal Website which is SSO enabled. We see that PW starts the browser in incognito (which is our req. aswell) but the page loads using the current SSO user cred thus skipping the Login screen.

If it starts with a new incognito context, where does it get current `SSO user cred` or do you mean it skips the sign in dialog because it uses http authentication there? Can you check if the browser is running some extensions [forced by chrome](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings) policy?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
