### ISSUE TITLE
[BUG] UserAgent is not passed in mobile viewPort

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#20035]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac
- Node.js version: 16.15.1
- Browser: All
- Extra: Mobile Viewport

**Code Snippet**

```
   use: {
        trace: 'retain-on-failure',
        headless: false,
        navigationTimeout: configList.navigationTimeOut,
        actionTimeout: configList.actionTimeout,
        contextOptions: {
            userAgent: 'test,
        },
    },
projects: [
 {
                    name: 'Safari', use: {
                        browserName: 'webkit',
                        viewport: { width: 1366, height: 768 }
                    }, grep: [/^((?!Mobile).)*$/]
                },
    {
                    name: 'Safari - Iphone', use: {
                        ...devices['iPhone 12 Pro'],
                    }, grep: /Mobile/,
                }
]
```

**Describe the bug**
UserAgent is not set in the browser Context when trying to run my test in mobile viewPort, while its working fine when using regular desktop browser viewport 

userAgent should prevent recaptcha 

Desktop test
<img width="295" alt="Screenshot 2023-01-11 at 14 51 44" src="https://user-images.githubusercontent.com/32042806/211827030-73bd1174-31cf-4d18-b808-e1683d7b6064.png">

Mobile Test
<img width="794" alt="Screenshot 2023-01-11 at 14 52 06" src="https://user-images.githubusercontent.com/32042806/211827085-dd721d47-09e1-49bb-84ed-43428e1a701e.png">

**Comment by amrsa1** [comment]
Update sorry seems, not a bug

![Screenshot 2023-01-11 at 15 16 40](https://user-images.githubusercontent.com/32042806/211828823-628728a8-3b12-47f8-93eb-eca313d02a18.png)

its not a property of contextOptions as far as i understood 

```
   {
                    name: 'Safari - Iphone', use: {
                        ...devices['iPhone 12 Pro'],
                        userAgent: 'test,
                    }, grep: /Mobile/,
                },
```

**Comment by amrsa1** [comment]
it wourld r

**Comment by aslushnikov** [comment]
@amrsa1 so user agent emulation from device descriptor simply overrode the user agent from context options. While it is slightly surprising at a first glance, this is expected if you consider that `deviceDescriptor` is just a bunch of settings typical for a given device.

All in all, I don't think we can change this behavior now since it'd be a breaking change.
