### ISSUE TITLE
[BUG] Cannot import TSX components with ESM

### ISSUE THREAD

**Issue by drewloomer** [microsoft/playwright#20039]
**Context:**
- Playwright Version: 1.29
- Operating System: Mac
- Node.js version: 18.12.1, 16.8.1
- Browser: N/A

**Code Snippet**

Trying to call `import { TestComponent } from "./Component.js";` in a Playwright test blows up with a `Cannot find module` error.

**Describe the bug**

It seems that [tsxTransform](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/tsxTransform.ts#L46) has a different codepath when it detects JSX, so the ESM resolution doesn't work.

I _think_ the problem is that [gathering the component info](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/tsxTransform.ts#L176) uses `require.resolve` but the `.js` file doesn't exist (yet?). 

[Here is an example repo showing the problem](https://github.com/drewloomer/playwright-import-repro).

**Comment by pavelfeldman** [comment]
@drewloomer Thanks for the report, fix is on the way. Watch out those non-async mounts, should be await mount!

**Comment by drewloomer** [comment]
Thanks for the speedy fix, @pavelfeldman! Great call on the `mount`s too 😄 .
