### ISSUE TITLE
[Question] How can we use slider in Playwright JS

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#20032]
I have scenario where user can give the score by sliding on the bar. So could anyone help me out with the logic here as shown in snapshot below

![image](https://user-images.githubusercontent.com/77335200/211820465-eb633695-2631-424c-89a3-6b735df65081.png)

**Comment by MarkRedeman** [comment]
I recently used the following code to change a slider value:
```typescript
async function changeSlider(page: Page, thumb: Locator, slider: Locator, targetPercentage: number) {
    const thumbBoundingBox = await thumb.boundingBox();
    const sliderBoundingBox = await slider.boundingBox();

    if (thumbBoundingBox === null || sliderBoundingBox === null) {
        return; // NOTE it's probably better to throw an error here
    }

    // Start from the middle of the slider's thumb
    const startPoint = {
        x: thumbBoundingBox.x + thumbBoundingBox.width / 2,
        y: thumbBoundingBox.y + thumbBoundingBox.height / 2,
    };

    // Slide it to some endpoint determined by the target percentage
    const endPoint = {
        x: sliderBoundingBox.x + sliderBoundingBox.width * targetPercentage,
        y: thumbBoundingBox.y + thumbBoundingBox.height / 2,
    };

    await page.mouse.move(startPoint.x, startPoint.y);
    await page.mouse.down();
    await page.mouse.move(endPoint.x, endPoint.y);
    await page.mouse.up();
}
```

**Comment by ltsuda** [comment]
It might no be a good approach but it could work using the `.evaluate` in the slider element and changing the value itself.

**Comment by aslushnikov** [comment]
Thank you folks for your answers. Closing as per suggestions above!

**Comment by mandeepmm1** [comment]
@MarkRedeman What is the locator of thumb in your script?

**Comment by MarkRedeman** [comment]
I'm suing,
```typescript
        const sliderThumb = screen.getByRole('slider', { name: 'Videoframe' });
        const slider = screen.getByRole('group', { name: 'Videoframe' });
```

where screen comes from the [playwright-testing-library](https://github.com/testing-library/playwright-testing-library) plugin and the silder and group aria roles are specific to UI library we use ([React Spectrum](https://react-spectrum.adobe.com/react-spectrum/Slider.html)'s slider component in this case).

I think any locator should work so long as the `sliderThumb` selects the "thumb" (the thing you move around) and the `slider` selects the bounding box of the slider itself.

**Comment by mandeepmm1** [comment]
![image](https://user-images.githubusercontent.com/77335200/213148420-be7b17c2-2fc6-4d7c-a8a7-38f7ee7777fc.png)

Could you please define a script in this case as it is getting bit complicated @MarkRedeman

**Comment by rakeshnambiar** [comment]
@MarkRedeman thanks for sharing the sample code. I tried it for the element shown below and it didn't work. It is a sliding component. Any thoughts?

![Screenshot 2023-10-23 at 14 26 37](https://github.com/microsoft/playwright/assets/20258636/f3559c2d-fdfa-4080-8506-10893a6ce020)
