### ISSUE TITLE
[Question] How to wait until all elements are hidden

### ISSUE THREAD

**Issue by w-sr** [microsoft/playwright#20049]
I am trying to wait until all elements with specific identifier are hidden.
For example, when I go to a page, that page has several api calls and I implemented skeleton until full data is fetched.

In playwright, I am gonna wait until all skeletons are hidden.

I wrote some code for it like this:

```
await page.goto('./page', { waitUntil: 'load' })
await page.waitForSelector('.MuiSkeleton-root', { state: 'hidden' })
```

But **_waitForSelector_** only waits until the first skeleton is disappearing.
Any thoughts on this?

**Comment by aslushnikov** [comment]
@w-sr I'd use web-first assertions for this:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  // Set a dummy HTML to illustrate.
  await page.setContent(`
    <div id=foo>hello</div>
    <div id=bar>world</div>
    <div id=baz>!!!</div>
  `);
  // Slowly hide divs one by one
  await page.evaluate(() => {
    setTimeout(() => {
      document.querySelector('#foo').style.setProperty('display', 'none');
      console.log('hiding #foo');
    }, 1000);
    setTimeout(() => {
      document.querySelector('#bar').style.setProperty('display', 'none');
      console.log('hiding #bar');
    }, 3000);
    setTimeout(() => {
      document.querySelector('#baz').style.setProperty('display', 'none');
      console.log('hiding #baz');
    }, 2000);
  });
  page.on('console', console.log);

  // Get all locators that we expect to be hidden
  const locators = await page.locator('div').all();
  // use web-first assertions to wait for all locators to hide.
  await Promise.all(locators.map(locator => expect(locator).toBeHidden()));
});
```

**Comment by w-sr** [comment]
@aslushnikov Thanks

**Comment by 1j01** [comment]
This is how I'm doing it:
```js
await expect(page.locator('.something:visible')).toHaveCount(0);
```
It's concise and aligns well with what the user cares about, e.g. from the user's perspective, "there are no popups on the screen".
This will pass if `.something` does not exist OR if `.something` exists but is hidden. I think is the same behavior as @aslushnikov's snippet.

Of course, you have to be careful of typos, since an incorrect selector can make your test pass for the wrong reasons.
Negative assertions like this are prone to false positives.
