### ISSUE TITLE
[Question] Run Global Setup Parallel?

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#20054]
Is there a way to run the Global-Setup file 'parallel' if I need to authenticate with multiple users? Say I have 10 users I use throughout my tests and I need to get a storage state for each one of them. Global Setup currently goes one by one to get the storageState. I think this could run much faster if it could be ran parallel (or all at once) but I don't think there is a way to kick it off like that, is there? Thank you in advance.

``` 
async function globalSetup(config: FullConfig) {
    async function pageSetup() {
         let browser = await chromium.launch();
         let page = await browser.newPage();
         
         return [page, browser];
    }
    
    //Setup auth 1
    [page, browser] = await pageSetup();
    page.login(user1)
    page.context().storageState({path: 'state1.json'})
    browser.close()
    
    //Setup auth 2
    [page, browser] = await pageSetup();
    page.login(user2)
    page.context().storageState({path: 'state2.json'})
    browser.close()
    
    // Then so on and so forth.

}
```

**Comment by aslushnikov** [comment]
@bshostak you can just `Promise.all` authentications for multiple users. This might look like this:

```ts
async function loginForUser(user: string, stateFile: string) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  // ... do staff with page to login ...
  await page.context().storageState({ path: stateFile });
  await browser.close();
}

async function globalSetup(config: FullConfig) {
  await Promise.all({
    loginForUser('user1', 'state1.json'),
    loginForUser('user2', 'state1.json'),
  });    
}
```

Hope this helps! Feel free to file new issues if you think we can be helpful.

**Comment by bshostak** [comment]
@aslushnikov You are awesome, thank you!

**Comment by AkhilRawat** [comment]
@aslushnikov this works locally but somehow is failing when run using github action. I have 12 logins that i want to run in parallel. It runs up to 5 logins without breaking but if i add 6th one in the same promise, it fails and the failure is "element not found" i.e. it is not able to find the sign in button. Same works fine locally.
