### ISSUE TITLE
[Question] Way to select child div without that child's inner divs

### ISSUE THREAD

**Issue by RevTyler** [microsoft/playwright#20057]
Sorry title is terrible.

Assuming a setup like:
```ts
const browser = await chromium.launch();
const page = await browser.newPage();
// Set a dummy HTML to illustrate.
await page.setContent('
  <div role="list">
    <div>
        <div>inner1 content</div>
        <div>inner1 content</div>
    </div>
    <div>
        <div>inner2 content</div>
        <div>inner2 content</div>
    </div>
  </div>
');
```

I know I can grab the div's in the list with:
`page.getByRole('list').locator('div').nth(x)`
But this will cycle through the inner content divs as well. I'd just like the top list items (assuming my real world scenario has a much more complicated structure and I'd like to not count the divs to capture the right nths for each list item parent).

EDIT:
I found a way that works. Technically my structure is more like:
```
<div role="list">
    <div>
        <header><div>inner1 content</div></header>
        <div>inner1 content</div>
    </div>
    <div>
        <header><div>inner2 content</div></header>
        <div>inner2 content</div>
    </div>
  </div>
```

So I just used:
`page.getByRole('list').locator('div:has(header)').nth(x)`

This works, but I'm still interested if there's a way to do it if there was a scenario where I didn't have the headers to differentiate the main list items.

**Comment by aslushnikov** [comment]
@RevTyler i'm glad you figured it out! An alternative would be to use the `:scope` selector:

```ts
import { chromium } from '@playwright/test';

const browser = await chromium.launch();
const page = await browser.newPage();
// Set a dummy HTML to illustrate.
await page.setContent(`
  <div role="list">
    <div>
        <div>inner1 content</div>
        <div>inner1 content</div>
    </div>
    <div>
        <div>inner2 content</div>
        <div>inner2 content</div>
    </div>
  </div>
`);

console.log(await page.getByRole('list').locator(':scope > div').count()); // prints 2
await browser.close();
```
