### ISSUE TITLE
[Feature] Add group on the traces actions

### ISSUE THREAD

**Issue by macabeus** [microsoft/playwright#20056]
## Context

The trace viewer is one of the most helpful Playwright features when debugging a test case.

But it can be hard to read the steps when a test is complex. It becomes even harder if we have helper functions to make the test more declarative.
For example, let's say that we have:
```js
test('Change user name', () => {
  // arrange
  createUser();
  login();
  goToSettings();

  // act
  changeUsername('new name')

  // assert
  expect(user.name).toBe('new name')
});
```

Although we have three clearly separated `arrange` steps on the code, on Playwright's trace, everything will be at the same scope, without a clear separation on the timeline nor at the Actions list.

## Suggestion

We can add native support for `console.group`. When creating a group, it adds a mark on the trace timeline and an indention at the Actions list.
For example:
```js
console.group('foo')
something()
console.groupEnd()

console.group('bar')
something()
console.groupEnd()
```

we would have something like:

![image](https://user-images.githubusercontent.com/9501115/211933174-39c20a54-a623-49eb-8515-d965d37ba92b.png)

## Related issue

- https://github.com/microsoft/playwright/issues/15196: This suggestion asks for something similar but on the report. On the other hand, my suggestion is about the trace viewer.

**Comment by aslushnikov** [comment]
I'll merge this to https://github.com/microsoft/playwright/issues/8682 and re-open it. Please upvote to bump issue priority!
