### ISSUE TITLE
[BUG] Calendar date is not working in PW js

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#20064]
**Context:**
Description: Date is not getting clicked even after adding correct xpath. I have implemented same function in same application for other places as well and over there its working. Only for this particular field calendar date is not working.

- Playwright Version: [1.28.1]
- Operating System: [e.g. Windows 10]
- Node.js version: [v16.15.0]
- Browser: [Chromium]

**Code Snippet**

constructor(page){
this.page=page;
this.signingDate = page.locator("input[name='signingDate']");
this.date = page.locator("(//div[@class='ant-picker-cell-inner'][normalize-space()='10'])[1]");
}

async activities(){
await this.signingDate.click();
await this.date.click({ force: true });
}

![image](https://user-images.githubusercontent.com/77335200/212009917-82e813e7-783a-46b9-804d-a92fe2ab7cb8.png)

![image](https://user-images.githubusercontent.com/77335200/212010059-02bf9f50-daca-45b6-804c-51e40521cd48.png)

**Comment by aslushnikov** [comment]
@mandeepmm1 I don't think we can help much unless we can reproduce this locally; any chance you can share a repro with us?

**Comment by mandeepmm1** [comment]
@aslushnikov Unable to share the repo link due to company restrictions. Could you please share me your gmail id, so that i can upload in drive and give you the access

**Comment by aslushnikov** [comment]
@mandeepmm1 sure, it's aslushnikov [at] gmail [dot] com

**Comment by mandeepmm1** [comment]
@aslushnikov I have given access to the folder. Please check it and let me know the issue. thanks!!!

**Comment by aslushnikov** [comment]
@mandeepmm1 I got the file, but how do I run this? Any chance you can reduce this to something that I can static-serve locally and then run a single playwright script that would demonstrate the issue?

**Comment by mandeepmm1** [comment]
@aslushnikov on test.list.js you can comment all the test case except "test.describe(require('./product_create_Activities.spec'));" which will run only the specific test case for you to debug

**Comment by aslushnikov** [comment]
@mandeepmm1 the test times out for me on line 81 of `product_create_Activities.js`

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
