### ISSUE TITLE
[Question] What is fixture?

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#20073]
Hey, guys! We have a terminology question. Say we have this code:

```ts
class Foo { ... }

const foo = new Foo()

const bar = async ({}, use) => {
  await use(foo)
}

const baz = {
  bar,
}

const test = base.extend(baz)
```

What do you mean by `fixture` term here https://playwright.dev/docs/test-fixtures ?

1. Class Foo?
2. Instance foo?
3. Function bar?
4. Object baz?
5. Maybe playwright mechanism which injecting `foo` to test?

**Comment by Diokuz** [comment]
The problem: we have a lot of misunderstanding in our team, when one meaning function `bar`, and other meaning instance `foo`. We want to setup clear and simple thesarius.

**Comment by aslushnikov** [comment]
@Diokuz in our slang, "fixture" is the thing you use in test.

To annotate your snippet:
```ts
class Foo { ... } // this is just a class

const foo = new Foo() // this is just a class instance

const bar = async ({}, use) => { // this we call "fixture implementation"
  await use(foo)
}

const baz = { // this object doesn't have a name, so we usually inline it in the `extend` call.
  bar,
}

const test = base.extend(baz)

test('should work', ({ baz }) => { // << "baz" is a "fixture"
});
```

Hope this helps!

**Comment by Diokuz** [comment]
Cool, thanks!

Btw, we call Foo – component object, and baz – fixture object / object of fixtures, not sure how to translate.
