### ISSUE TITLE
[Question] How do I turn on service worker?

### ISSUE THREAD

**Issue by Dopuu** [microsoft/playwright#20071]
I'm playing with telegram and playwright, and most of the time I'm getting a pop up that says that service worker is disabled. I have no idea how to turn it on. This is how I launch the browser:
```python
browser = await playwright.chromium.launch(headless=False)
context = await browser.new_context(storage_state='state.json')
page = await context.new_page()
await page.goto(chat_url1)```

**Comment by aslushnikov** [comment]
@Dopuu it might be that service worker got installed but is not active yet, so you'll need to reload the page after installation.

However, this is more like a "how do I automate telegram" question that falls outside of the scope of the project, so I'd recommend asking somewhere else. Good places to ask would be StackOverflow, and maybe even our discord: https://aka.ms/playwright/discord

Hope this helps! Please do not hesitate to file more issues if you still think we can be helful.
