### ISSUE TITLE
[Question]Why this site is not loading?

### ISSUE THREAD

**Issue by DeeHive** [microsoft/playwright#20070]
const { chromium } = require('playwright')

    const browser = await chromium.launch()
    const page = await browser.newPage()
    await page.goto('https://www.carrefour.com/en/finance/carrefour-share', { waitUntil: 'networkidle' })

    const dimensions = await page.evaluate(() => {

        body = document.body,
            html = document.documentElement;
        return {
            height: Math.max(body.scrollHeight, body.offsetHeight,
                html.clientHeight, html.scrollHeight, html.offsetHeight)
        };
    });

    await page.setViewportSize({ width: 1280,height:dimensions.height })

    console.log("dim",dimensions)

    await page.screenshot({ path: '/Users/deehive/Desktop/screenshot/sscreen8.png' })
    await browser.close()

**Comment by aslushnikov** [comment]
@DeeHive most likely it uses some anti-scraping / anti-automation techniques that block automated access. Evading these falls outside of the scope of the project, so I'll have to close this issue.

**Comment by DeeHive** [comment]
Puppeteer handles this website properly so a bit surprised

**Comment by monikandy** [comment]
> Puppeteer handles this website properly so a bit surprised

When I try to go to that page in a browser this is what appears: 
![image](https://user-images.githubusercontent.com/25268051/212296180-d5169133-47c9-450f-bd90-486988ea945b.png)
