### ISSUE TITLE
[BUG] Chromium options `--disable-web-security` and `bypassCSP` are not working

### ISSUE THREAD

**Issue by Llois41** [microsoft/playwright#20078]
**Context:**
- Playwright Version: 1.27.1
- Operating System: MacOS Ventura 13.1 (M1 Pro), also tested on Windows 10
- Node.js version: 16.18.0
- Browser: Chromium

**Code Snippet**

```typescript
import { chromium, firefox } from 'playwright';

void (async () => {

  const browserContext = await chromium.launchPersistentContext('', {
    devtools: true,
    args: ['--disable-web-security'],
    bypassCSP: true,
  });
  const page = await browserContext.newPage();

  await page.goto('http://localhost:8123');
})();
```

**Describe the bug**

I want to test locally against an environment with strict CSP and CORS settings. That's why I want to start a playwright chromium browser which disables those settings. I crafted this code snippet using the official docs but navigating to my app on localhost still gives me CSP and CORS errors. Am I missing some obvious stuff to configure?

**Comment by aslushnikov** [comment]
@Llois41 I cannot reproduce this. I tried the following snippet, and `fetch` successfully ignores any server headers:

```ts
import { chromium } from '@playwright/test';

const browserContext = await chromium.launchPersistentContext('./foo', {
  devtools: true,
  args: ['--disable-web-security'],
  bypassCSP: true,
});
const page = await browserContext.newPage();
await page.goto('https://aslushnikov.com');
page.on('console', console.log);
console.log(await page.evaluate(() => fetch('https://bing.com').then(r => r.status)));
await browserContext.close();
```

can you help me with a repro?

**Comment by Llois41** [comment]
@aslushnikov I tried your example and it works for me too. The error messages I get are

1) `Refused to frame 'https://some-service.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.foo.com https://*.bar.com".
`

2) `Unhandled error SecurityError: Blocked a frame with origin "http://localhost:8123" from accessing a cross-origin frame.`

Does this config not work for iFrames?

**Comment by aslushnikov** [comment]
@Llois41 Again, repro would help a lot to avoid guessing. But without a repro and based just by the text you entered:

> Unhandled error SecurityError: Blocked a frame with origin "http://localhost:8123" from accessing a cross-origin frame.

Try also adding `--disable-site-isolation-trials` flag

> Refused to frame 'https://some-service.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.foo.com https://*.bar.com". 

This, unfortunately, didn't google well enough.

So unless there's a repro, I'm afraid I won't be of much help! Any chance you can build a minimal script like I did to demonstrate the issue?

**Comment by Llois41** [comment]
@aslushnikov got one:

```typescript
import { chromium } from 'playwright';

void (async () => {
  const browserContext = await chromium.launchPersistentContext('', {
    devtools: true,
    args: ['--disable-web-security', '--disable-site-isolation-trials'],
    bypassCSP: true,
  });

  const page = await browserContext.newPage();

  await page.goto('https://google.com');

  await page.evaluate(() => {
    const iframe = document.createElement('iframe');
    iframe.src = 'https://www.otto.de/';
    document.body.appendChild(iframe);
  });
})();
```
this gives me `Refused to frame 'https://www.otto.de/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'self' https://*.otto.de https://*.ottogroup.com https://og2gether.sharepoint.com".`

**Comment by aslushnikov** [comment]
@Llois41 ah yes, you can't workaround the `x-frame-options` header response from server with these options.

What you can do, though, is to use response interception to remove all the `content-security-policy` and `x-frame-options` headers from any response. See https://playwright.dev/docs/next/api/class-route#route-fetch for details.

Hope this helps!

**Comment by Llois41** [comment]
@aslushnikov yes, did this already. But I'm still confused about the `--disable-web-security` flag not working properly. A colleague started his normal chrome installation with this flag and got around the those error messages. Why does the playwright chromium browser behave different?

**Comment by aslushnikov** [comment]
> A colleague started his normal chrome installation with this flag and got around the those error messages. 

@Llois41 I just tried with my stable chrome, and the behavior is the same - iframe does not load. Try it yourself:
1. Launch with the flags:

    ```
    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --user-data-dir=./bar --disable-web-security --disable-site-isolation-trials
    ```
2. Open devtools and evaluate the in console:
    ```ts
    const iframe = document.createElement('iframe');
    iframe.src = 'https://www.otto.de/';
    document.body.appendChild(iframe);
    ```
