### ISSUE TITLE
[Question] Does Playwright expose transferSize metrics?

### ISSUE THREAD

**Issue by joychester** [microsoft/playwright#20084]
Hi, There, 
I checked out the source, seems we support the **transferSize** , but by using request.sizes() method, it does not expose such metric, anyone knows why? Thanks! 

```
 async sizes(): Promise<ResourceSizes> {
    ....

    let transferSize = await this._transferSizePromise;
    if (transferSize === null) {
      // Fallback to calculating it manually.
      transferSize = responseHeadersSize + encodedBodySize;
    }

    return {
      requestBodySize: this._request.bodySize(),
      requestHeadersSize,
      responseBodySize: encodedBodySize,
      responseHeadersSize,
      transferSize,
    };
  }```

**Comment by aslushnikov** [comment]
@joychester Transfer size is just a body size + headers size:

```ts
const sizes = await request.sizes();
const transferSize = sizes.responseBodySize + sizes.responseHeadersSize;
```

Hope it helps :) Feel free to file more issues if you think we still can be helpful!

**Comment by joychester** [comment]
Thank you @aslushnikov for the reply, I understand what the transferSize means, but i am just too lazy to write 2 statements and curious why we do not expose it directly behind the scenes :)

**Comment by aslushnikov** [comment]
@joychester ah :) exposing API's has associated costs, like managing & maintaining documentation, types, porting API across language ports, etc etc. So the general rule of thumb is to **not** expose API unless it's really pressing.
