### ISSUE TITLE
[Feature] [component tests] Support for changing component state in node environment

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#20081]
Currently, there's no ergonomic way for the node environment to affect the state of mounted components (browser environment) except via UI actions. So if I need to do something like the following:

1. Mount component
2. Call a browser side typescript function
3. Run a Playwright assertion

I end up doing something like putting the browser side function in a placeholder button onClick, which is not relevant to my test except to trigger this function. I then call the function by using Playwright to click on the button (from the node environment). 

So my mount looks something like this:
```
// wrapper.tsx
function Wrapper() {
const reactHook = useSomeReactHook();

return (<>
    <ComponentIWantToTest />
    <button onClick={reactHook}>
</>)
}
```

The best thing would be if I didn't need the wrapper at all (not sure that's technologically possible if I want to use a react hook), but the second best thing would be at least to remove the need for the placeholder button. Maybe something can be implemented in Playwright that can enable something like this:

```
// wrapper.tsx
function Wrapper({stateControlledByNodeEnvironment}) {
const reactHook = useSomeReactHook();

useEffect(() => {
  reactHook();
}, [stateControoledByNodeEnvironment])

return (<>
    <ComponentIWantToTest />
    <button onClick={reactHook}>
</>)
}
```

```
// component.spec.tsx

test("", async ({mount}) => {
  const [state, setState] = usePlaywrightState(false);  // Not a react hook, but some magic that edits the variable in the browser environment

  await mount(<Wrapper stateControlledByNodeEnvironment={state}/>)

  setState(true);
}
```

Exact API details can be hashed out, but something to enable a workflow like this would be helpful. I know the opposite (writing node environment variable by browser component) is [already possible](https://playwright.dev/docs/test-components#example).

**Comment by sand4rt** [comment]
Is the `component.update()` what you are looking for?:
https://github.com/microsoft/playwright/blob/main/tests/components/ct-react/src/tests.spec.tsx#L26

**Comment by WesleyYue** [comment]
Ah yep, I think that will work. Thanks.
