### ISSUE TITLE
[BUG] Page does not load no matter how much timeout is increased ! There is no problem accessing the page on the server.

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#20087]
- **Page does not load no matter how much timeout is increased.It opens when we try with another url.Docker is installed on the server where jenkis is located. Browser works and can go to another url. There is no problem accessing the page on the server. **

- Playwright Version: Version 1.29.1
- Operating System: Linux
- Node.js version: v18.12.1
- Browser: Chromium

Global setup

<img width="374" alt="GlobalSetup" src="https://user-images.githubusercontent.com/75999746/212199882-c3fca52f-de2c-497c-beda-2bb507d66bb4.PNG">

Pipeline

<img width="470" alt="pipeline" src="https://user-images.githubusercontent.com/75999746/212199888-b57519dc-4dba-45a4-8cc2-5b5b70c00b20.PNG">

**Comment by aslushnikov** [comment]
> It opens when we try with another url.

@MuharremBicici this makes me think that web server is doing some evasion techniques to avoid bot access. Could it be the case?

**Comment by MuharremBicici** [comment]
> > It opens when we try with another url.
> 
> @MuharremBicici this makes me think that web server is doing some evasion techniques to avoid bot access. Could it be the case?

Yes you are right. We checked and fixed it. Thank you for your interests. Solved

**Comment by MuharremBicici** [comment]
Solved.
