### ISSUE TITLE
[Question] How to conditionally retry a test?

### ISSUE THREAD

**Issue by gajus** [microsoft/playwright#20086]
We have certain categories of failures that are outside of our control, e.g. external service rate limiting our integration.

We don't want tests to be re-retry able by default, however, I am exploring if there is a way to handle test failure and determine if it needs to be retried programmatically.

**Comment by aslushnikov** [comment]
> I am exploring if there is a way to handle test failure and determine if it needs to be retried programmatically.

@gajus there's no built-in API to dynamically re-try tests. However, one way to organize this might be the following:
- use JSON reporter to store test run results
- write a separate program that would analyze JSON report, figure out which tests should be re-runned, and use the `npx playwright test` api with a list of tests to run.

Hope this gives some ideas!

**Comment by gajus** [comment]
It feels like Playwright could provide API for this. A simple event handler that catches the error and allows to retry would be extremely handy for these use cases.
