### ISSUE TITLE
[Question] Send multiple files in a request body

### ISSUE THREAD

**Issue by ecdr404** [microsoft/playwright#20085]
Hi,
I reviewed the documentation on how to send a file using _multipart/form-data_ encoding, however, it is not clear for me how to send several files

```
const stream = fs.createReadStream('team.csv');
await request.post('https://example.com/api/uploadTeamList', {
  multipart: {
    fileField: stream
  }
});
```

I have a stream for each file, so, any on how to send them as part of the attachment property?

**Comment by aslushnikov** [comment]
@ecdr404 you'll need to use something like https://github.com/form-data/form-data to encode multiple files. Check out examples on their github repo.

**Comment by ecdr404** [comment]
Thanks @aslushnikov, the problem is I'm integrating playwright with mailgun so I need to send multiple files in an array, take a look at the code below

`await mailgun.messages().send({
  from: `test@${domain}`,
  to: 'your email here',
  subject: 'Hello from Mailgun',
  html,
  text: 'Hello, World',
  // Multiple attachments
  attachment: ['./moby-dick.epub', './mastering-mongoose.pdf']
});`

Playwright multipart only accepts a string | number | boolean | stream and when I try to send a formData type I got this error
`Type 'FormData' is not assignable to type '{ [key: string]: string | number | boolean; }'.`
