### ISSUE TITLE
[BUG]  Button click with window close not working for Firefox

### ISSUE THREAD

**Issue by Rom4ig** [microsoft/playwright#20093]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Windows/docker(linux)
- Node.js version: 18.13.0
- Browser: Firefox

**Code Snippet**

```typescript
  await page.getByRole('button', { name: 'Выбрать' }).click()
```
**Console output**
![image](https://user-images.githubusercontent.com/43033763/212257593-73d31bc6-c57c-4623-a2b6-4f99f5842510.png)

After this click, the window closes.
This click works for **Chrome** but doesn't work for **Firefox**.
I also tried this with **delay** and **force** options.

**Comment by mxschmitt** [comment]
Could you provide us a repro for this? Or try to set the `DEBUG=pw:browser` environment variable, since this looks like a browser crash.

**Comment by aslushnikov** [comment]
@Rom4ig thank you for the report! I can repro this:

```ts
// a.spec.ts
import { test } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.setContent('<button>clickme</button>');
  await page.$eval('button', button => button.addEventListener('click', () => {
    window.open('');
  }, false));
  const [popup] = await Promise.all([
    page.waitForEvent('popup'),
    page.locator('button').click(),
  ]);
  await popup.setContent(`<button>clickme</button>`);
  await popup.$eval('button', body => body.addEventListener('click', () => {
    window.close();
  }));
  await Promise.all([
    popup.locator('button').click(), // throws in Firefox, but not in Chromium or WebKit
    popup.waitForEvent('close'),
  ]);
});
```

**Comment by Rom4ig** [comment]
Why if you change to `window.open(document.URL, '_blank', 'location=yes');` then it will work?

**Comment by aslushnikov** [comment]
@Rom4ig heads-up: it turns out this is how Firefox actually works. My "fix" for this particular bug was just masking the problem. 

So this might throw in Firefox in future as well, similarly to https://github.com/microsoft/playwright/issues/21225
