### ISSUE TITLE
[Question]How can I get access to properties exposed in Window object so I can test them and verify its values?

### ISSUE THREAD

**Issue by chrisha22** [microsoft/playwright#20109]
If I try to run something like this

`expect(Object.values(window).length).toBeGreaterThan(1)`

This error shows up:

```
 ReferenceError: window is not defined
       27 |
    > 28 |     expect(Object.values(window).length).toBeGreaterThan(1)
                                                        ^
```

**Comment by ltsuda** [comment]
Please, see this page if it helps you:

https://playwright.dev/docs/evaluating

**Comment by aslushnikov** [comment]
Closed as per https://github.com/microsoft/playwright/issues/20109#issuecomment-1382421060. Please do not hesitate to file more issues if you think we can helpful, or maybe ask on our discord: https://aka.ms/playwright/discord
