### ISSUE TITLE
console.log does not print to the terminal/console

### ISSUE THREAD

**Issue by ranjCS** [microsoft/playwright#20104]
Any idea why console.log ('any text') does not print to the terminal/console? Is this a config related issue?

**Comment by dlpigpen** [comment]
I found a help link: https://playwright.dev/docs/debug It might you a little bit.

**Comment by aslushnikov** [comment]
@ranjCS depending on the context in which you execute the `console.log()` call, it'll be printed in different places:
- if you have `console.log()` inside the `page.evaluate()` call, then it'll be printed to the browser's console
- if you have `console.log()` in node.js, then it'll be printed in your terminal

It also might be that something's weird is going on in your setup, but there's no way we could know this unless you shared a full repro that we can run locally & investigate. I'd recommend asking this kind of questions on our lovely discord: https://aka.ms/playwright/discord

I'll close this given the lack of information; if you think we still can be helpful, please re-file with more information, filling in the issue template. A repro that we can run locally would go a long way!

**Comment by jamesmortensen** [comment]
In case anyone comes across this issue, I discovered that allure-playwright@2.1.0 was causing this issue.  console.log and other loggers would not work inside test cases.  After upgrading to the latest, 2.8.1 at the time of this writing, the problem with console.logs not appearing went away.

Note this is not console.log captures from the browser, this is console.log for the use of tracing execution of a test case for debugging purposes.

Hope this helps!

**Comment by bmaciass** [comment]
Not sure if this is the right way to do it but replacing `console.log` with `process.stdout.write` solves the issue in my case. Hope this helps.
