### ISSUE TITLE
[Question] Generate one report per browser

### ISSUE THREAD

**Issue by kamelbou** [microsoft/playwright#20105]
Hi All,

Is there a way to generate one report per browser instead of merging all in one ?

Thank you

**Comment by aslushnikov** [comment]
@kamelbou there's one report generated per one test run, not per browser. So for example, if you have the following `playwright.config.ts`:

```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

Then the following will run all projects and generate a single HTML report:

```
npx playwright test --reporter html
```

Hope this helps! Please do not hesitate to file more issues if you think we still can be helpful.
