### ISSUE TITLE
[Question] How to maintain a reference from a get_by_text Locator if the text changes?

### ISSUE THREAD

**Issue by blksith0** [microsoft/playwright#20102]
```
thing = page.get_by_text('before')
print(thing.inner_text())
button.click() # changes the above thing's text
print(thing.inner_text()) # error
```

I want to search by text, at least initially, but still maintain a reference to that element after the text changes upon clicking the button.
What's the recommended way to do that?

**Comment by aslushnikov** [comment]
@blksith0 If you absolutely need to have a reference, then you'll have to come from locator to element handle: 

```py
thing = page.get_by_text('before').evaluate_handle(e => e)
print(thing.inner_text())
button.click() # changes the above thing's text
print(thing.inner_text()) # error
```

Do note though that holding a reference onto a DOM element has all kinds of associated issues:
- the element might get detached
- the element might get re-used by web framework to render completely different part of the page
- there's no built-in [auto-waiting logic](https://playwright.dev/python/docs/next/actionability) like with locators that makes tests reliable

So in general, the rule of thumb is to avoid element handles and to try to find a good locator for the updated element.

Hope this helps!
