### ISSUE TITLE
[BUG]: Copy To Clipboard

### ISSUE THREAD

**Issue by hlawuleka** [microsoft/playwright#2011]
**Context:**
- Playwright Version: 1.0.0-next.1587832636942
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```
const context = await browser.newContext();
context.grantPermissions(['clipboard-read']);
```

**Describe the bug**

The above snippet produces the following error:

`Unknown permission: clipboard-read`

this occurs when I run `yarn test`

**Comment by pavelfeldman** [comment]
What browser are you using? (Safari does not have it and Firefox has it behind a flag)

**Comment by hlawuleka** [comment]
I am using Firefox..."Firefox has it behind a flag" - what does this mean?

**Comment by pavelfeldman** [comment]
I was referring to [readText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText). Or what do you use this permission for? What is the scenario that works for you in Firefox that you'd like to automate?

**Comment by hlawuleka** [comment]
Yes, I want to use the permissions to do this: `await navigator.clipboard.readText();`

But the problem is the error as highlighted in my description of the issue is that this `context.grantPermissions(['clipboard-read']);` throws the error...

**Comment by dgozman** [comment]
From [readText](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText) MDN article:

> Firefox only supports reading the clipboard in browser extensions, using the "clipboardRead" extension permission.

That means `await navigator.clipboard.readText()` will not work in Firefox, so testing it and granting the permission is pointless.

**Comment by aslushnikov** [comment]
Looks like things work as expected.

**Comment by mirao** [comment]
Reading from clipboard works with FF 99, but you have to set the Firefox option `"dom.events.testing.asyncClipboard": true`, put it into [firefoxUserPrefs](https://playwright.dev/docs/api/class-browsertype#browser-type-launch).
