### ISSUE TITLE
Context.new_page

### ISSUE THREAD

**Issue by PauloCMota** [microsoft/playwright#20119]
Good afternoon, I can't find the library that contains the context.new_page() method, I don't know what I'm doing wrong
![playwright_issue](https://user-images.githubusercontent.com/91172159/212491048-cf7f4f56-0679-4843-98d2-a6e42d27c1b3.png)

**Comment by ltsuda** [comment]
`context` is part of the `Browser` API, see here
https://playwright.dev/python/docs/api/class-browsercontext
