### ISSUE TITLE
[BUG] Fail to load properly after submitting the form in some websites

### ISSUE THREAD

**Issue by xiang-deng** [microsoft/playwright#20112]
**Context:**
- Playwright Version: 1.29.0
- Operating System: Linux
- Browser: Chrome

**Code Snippet**

```python
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("https://www.delta.com/")
    page.get_by_role("link", name="From Departure Airport or City Your Origin").click()
    page.get_by_role("textbox", name="Origin City or Airport").type("new york")
    page.get_by_role("link", name="NYC New York City Area Airports, NY").click()
    page.get_by_role(
        "link", name="To Destination Airport or City Your Destination"
    ).click()
    page.get_by_role("textbox", name="Destination City or Airport").type("chicago")
    page.get_by_role("link", name="CHI Chicago Area Airports, IL").click()
    page.get_by_role(
        "combobox", name="Trip Type:, changes will reload the page"
    ).locator("span").first.click()
    page.get_by_role("option", name="One Way").click()
    page.get_by_role(
        "button",
        name=" Depart and Return Calendar Use enter to open, escape to close the calendar, page down for next month and page up for previous month, Depart date not selected",
    ).click()
    page.get_by_role("link", name="30 January 2023, Monday").click()
    page.get_by_role("button", name="done").click()
    page.pause()
    page.get_by_role("button", name=" Submit").click()
```

**Describe the bug**

On some booking websites, after filling in the information and click `submit`. The result page is not loading properly. On www.delta.com it appears as the submission fails and directs to a default page. On www.aa.com, the search result page loads, but there is a long loading time. Launch with persistent context has the same behavior, but things work fine directly using the browser (same chrome binary), and use the built-in recorder in chrome to record&replay would also work.

**Comment by aslushnikov** [comment]
@xiang-deng it looks like these websites don't want to be automated and thus process requests in a strange manner to evade automation.

Bot automation falls outside the scope of this project so I'll have to close this issue!
