### ISSUE TITLE
Playwright Cannot Go to Page

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#20114]
Hi. I try to go my url but gettin error _page.goto: Timeout 60000ms exceeded. navigating to "Url", waiting until "load"_ 
My url works normally but in test i could not understand why i cant load my page on playwright. I shared my global setup,config file and error message  with u. Thank you all for your help..

Playwright Version: Version 1.29.1

Operating System: Windows and Mac

Node.js version: v18.12.1

Browser: Chromium

Error

<img width="693" alt="error" src="https://user-images.githubusercontent.com/75999746/212442989-26d1f268-a4bf-4a89-b96c-0c49afae7b69.PNG">

Global Setup

<img width="374" alt="212199882-c3fca52f-de2c-497c-beda-2bb507d66bb4" src="https://user-images.githubusercontent.com/75999746/212442452-e0aa0fad-3043-4184-bc52-a1624a9e2c20.png">

Config

<img width="470" alt="Capture" src="https://user-images.githubusercontent.com/75999746/212442488-c5c6a51c-342a-4250-9998-345709f93a6c.PNG">

**Comment by aslushnikov** [comment]
@MuharremBicici can you navigate to this URL in your regular browser? Is this a server that you control? Could it be that the server is using bot-evasion techniques to avoid automation?

**Comment by MuharremBicici** [comment]
yes i can navigate this url in my browser normally but cant go with playwright.. I dont control the server.. I will try to learn that server is using this techniques

**Comment by aslushnikov** [comment]
> do u think that there is a problem with my config or global setup?

I don't think so. Most likely it's the website that doesn't like to be automated. 

I'll close this for now since it doesn't look like there's an immediate action from a Playwright team here.
