### ISSUE TITLE
[BUG] reports the wrong devicePixelRatio

### ISSUE THREAD

**Issue by greggman** [microsoft/playwright#20111]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.17.0
- Browser: Chrome
- Extra: Make sure you're on DPR > 1 device  This is true for most Macs but might not be if you're using an external monitor

**Code Snippet**

follow the docs for a setup with `npm init playwright@latest`

in `playwright.config.js` add `use: { headless: true, ...`

replace `example.spec.js` with

```
// @ts-check
const { test, expect } = require('@playwright/test');

test('test dpr', async ({ page }) => {
  await page.goto('data:text/html,<div id="d" style="display: inline-block;">foo</div>');
  await page.waitForLoadState('networkidle');

  const info = await page.evaluate(() => {
    let resolve;
    const promise = new Promise(_resolve => resolve = _resolve);
    const observer = new ResizeObserver((entries) => {
      resolve({
        devicePixelWidth: entries[0].devicePixelContentBoxSize[0].inlineSize,
        clientWidth: entries[0].target.clientWidth,
        devicePixelRatio: devicePixelRatio,
      });
    })
    const elem = document.querySelector('#d');
    if (elem) {
      observer.observe(elem);
    } else {
      throw new Error('no #d elem');
    }
    return promise;
  });

  console.log(JSON.stringify(info));
  const computedDeviceWidth = info.clientWidth * info.devicePixelRatio;
  const diff = Math.abs(computedDeviceWidth - info.devicePixelWidth);

  console.log('diff:', diff);
  expect(diff).toBeLessThanOrEqual(1);
});
```

Run with `npx playwright test`

**Describe the bug**

The code above creates a page with a div. It asks for the `clientWidth` (which is in CSS pixels). It then asks for the `devicePixelContentBoxSize` via `ResizeObserver`. Finally it reports those 2 values plus the `devicePixelRatio`

The reported `devicePixelContentBoxSize` should be close to `clientWidth * devicePixelRatio` (note: they are not guaranteed to be the same but they should be close)

Notice the `console.log` statements. On my M1 Macbook Pro I see this

```
{"devicePixelWidth":43,"clientWidth":21,"devicePixelRatio":1}
diff: 22
```

Which makes it very clear `devicePixelRatio` is wrong. If `1` was correct then the sizes should match. Looking at what's actually rendered it's clear the `devicePixelRatio` should be reported as `2`

**Comment by aslushnikov** [comment]
@greggman Indeed I can repro. And it works as expected in Firefox.

Moreover, seems to be a Chromium emulation bug: if you try emulating DPR in Chrome DevTools and run your ResizeObserver code in the console, then the results would be the same:

<img width="1482" alt="image" src="https://user-images.githubusercontent.com/746130/212456655-94c2e5d6-83c4-474a-9eeb-7f20be4b1632.png">

Could you please file this upstream to Chromium? (I've just stumbled upon some of the bugs you filed to Chromium, so I assume you're familiar with the process :))

**Comment by greggman** [comment]
So I reported the bug upstream but playwright could work around it until that fix. Here's the workaround I used


```
async function getDevicePixelRatio(browser: Browser): Promise<number> {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('data:text/html,<html></html>');
  await page.waitForLoadState('networkidle');
  const devicePixelRatio = await page.evaluate(() => {
    let resolve: (v: number) => void;
    const promise = new Promise(_resolve => (resolve = _resolve));
    const observer = new ResizeObserver(entries => {
      const devicePixelWidth = entries[0].devicePixelContentBoxSize[0].inlineSize;
      const clientWidth = entries[0].target.clientWidth;
      const devicePixelRatio = devicePixelWidth / clientWidth;
      resolve(devicePixelRatio);
    });
    observer.observe(document.documentElement);
    return promise;
  });
  await page.close();
  await context.close();
  return devicePixelRatio as number;
}

...

  const browser = await getBrowserInterface(executablePath);
  const devicePixelRatio = await getDevicePixelRatio(browser);
  const context = await browser.newContext({
    deviceScaleFactor: devicePixelRatio,
  });
```

**Comment by aslushnikov** [comment]
@greggman could you please share a link to the upstream bug?

**Comment by greggman** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1407546

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
