### ISSUE TITLE
[Question]: how to resolve cors issues on webkit browser?

### ISSUE THREAD

**Issue by adudew852** [microsoft/playwright#20124]
### Your question

Hi there, I encountered cors issues when using webkit browser.  I tried --disable-web-security and bypass_csp=true and a few other ways I found online but none of them work.  Below is my code.  Many thanks in advance!

`
async def main():
    async with async_playwright() as p:
        browser = await p.webkit.launch(
            headless=False,
            slow_mo=50,
            args=[
                '--disable-web-security',
                '--disable-features=IsolateOrigins',
                '--disable-site-isolation-trials',
                '--no-sandbox',
                '--disable-setuid-sandbox',
                '--disable-features=BlockInsecurePrivateNetworkRequests',
            ]
        )
        context = await browser.new_context(
            bypass_csp=True,
            java_script_enabled=True,
            user_agent=webkit_useragent,
        )
        page = await context.new_page()
        await page.goto(url, timeout=60 * 1000)
        await page.screenshot(path="demo.png")
        await asyncio.sleep(500)
        await browser.close()

asyncio.run(main())
`

**Comment by mxschmitt** [comment]
`--disable-web-security` is a Chromium only CLI flag, similar to the other ones which you provided they are not supported in WebKit.

What are you trying to accomplish? Why do you want to disable CORS? If you face CORS issues, these are most likely then also affecting real customers.

**Comment by adudew852** [comment]
Thanks for the reply.

My company is helping our client to conduct a number of tests on their production e-shop (yes, production environment and I am not sure who made that call).  As they don't want these test orders to mix with real orders, they have given us a testing user account.  The problem comes because their login process requires to obtain an authorization token from a different domain (e.g. www.shopping.com and auth.token.shopping).  As playwright treats them as different domain, i get CORS errors when I tried to login.   Real chrome, firefox and Safari does not have the same issue.  Hope this explains.  Many thanks for the help!

**Comment by yury-s** [comment]
> The problem comes because their login process requires to obtain an authorization token from a different domain (e.g. [www.shopping.com](http://www.shopping.com/) and auth.token.shopping). As playwright treats them as different domain, i get CORS errors when I tried to login.

Can you share more details on how you do the login and how it differs from the regular workflow in the real browsers? If you can share the code that'd be helpful too.

Also since you pass chromium flags to webkit I wonder if running in webkit is a requirement for you?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
