### ISSUE TITLE
[Question]how to pass extra parameters to callback function in page.on?

### ISSUE THREAD

**Issue by sailor0913** [microsoft/playwright#20128]
I want pass extra parameters to function on_response. 

what can I do? Thanks!

```
def on_response(res):
  if res.status === 200:
    ...
        
page.on("response", on_response)
```

**Comment by mxschmitt** [comment]
What kind of value do you want to pass around? You can create a wrapper function aka. `create_response_handler` which would look like that:

```
def create_response_handler(my_value):
  def on_response(res):
    if res.status === 200:
      print(my_value)
 return on_response
        
page.on("response", create_response_handler("foobar"))
```

But it all depends how your application or script is structured.

**Comment by sailor0913** [comment]
yeah！it's solve my problem! Thanks!
