### ISSUE TITLE
Is it possible to run on Google Cloud Run?[Question]

### ISSUE THREAD

**Issue by LuSrodri** [microsoft/playwright#20129]
I tried to set the scripts.start of package.json with "npm install & npx playwright install --with-deps & node app.js" but occured a follow error in the moment to deploy on Cloud Run:
```
Installing dependencies...
Switching to root user to install dependencies...
su: must be run from a terminal
Failed to install browsers
Error: Installation process exited with code: 1
```
Is there a correct way to run in the Cloud Run?

**Comment by yury-s** [comment]
"Switching to root user to install dependencies...
su: must be run from a terminal"

Playwright doesn't switch users using `su`, looks like there is an error in your script. Where do these errors come from?

You should probably refer to the google cloud run documentation. You can also have a look at our docker image [source](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy) to see how we install the deps in it or just use one of our prebuilt [docker images](https://playwright.dev/docs/docker).

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by anoblet** [comment]
I am having this issue as well.

**Comment by crazould** [comment]
I am having this issue as well.

**Comment by anoblet** [comment]
We ended up using Cloud Functions and using `spawnSync` to run our tests.

```
import functions from "@google-cloud/functions-framework";
import { spawnSync} from "child_process";

// Entry point
export const index = async (req, res) => {
  try {
    // Install browsers
    spawnSync("npx", ["playwright", "install"], {
      shell: true,
      stdio: [process.stdin, process.stdout, process.stderr],
    });

    if (!req.query.update) {
      // Run snapshot
      spawnSync("npx", ["playwright", "test"], {
        shell: true,
        stdio: [process.stdin, process.stdout, process.stderr],
      });
    } else {
      spawnSync("npx", ["playwright", "test", "--update-snapshots"], {
        shell: true,
        stdio: [process.stdin, process.stdout, process.stderr],
      });
    }

    res.status(200);
  } catch (error) {
    console.log(JSON.stringify({ message: error.stack, severity: "ERROR" }));

    res.status(500);
  }

  res.end();
};

functions.http("index", index);
```

**Comment by crazould** [comment]
I fixed the issue with this thread https://github.com/microsoft/playwright/issues/5767
