### ISSUE TITLE
[Feature] page.$ and page.$$ should pierce shadow DOM

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2012]
It seems like `page.$` and `page.$$` and their eval counterparts do not pierce the shadow DOM?

Should they maybe? It would not be equal to `document.querySelector` (or `document.querySelectorAll`) anymore then, but I'd say it is worth it?

E.g. when using `page.$$` which is the only option when e.g. getting multiple <tr> elements in a table, to loop and do something on them, it would be nice it pierced the shadow DOM.

We also have another case in tests where we in an `afterEach()` try to close any open dialogs, just to make sure we have independence between test cases if one fails in the middle of an open dialog. In this case, in the `afterEach()` we do:

```javascript
  // a-cool-button is in an open shadow DOM
  const dialog = await page.$('a-cool-dialog[show]');
  if (dialog) {
    await page.click(
      'a-cool-dialog[show] a-cool-button'
    );
  }
```

We would rather do:

```javascript
  // a-cool-button is in an open shadow DOM
  const cancelButton= await page.$('a-cool-dialog[show] a-cool-button');
  if (cancelButton) {
    await cancelButton.click();
  }
```

**Comment by pavelfeldman** [comment]
It actually should pierce shadow as any other Playwright selector. Are you seeing it not being the case?

**Comment by thernstig** [comment]
Nevermind, it does pierece the shadow DOM. (I'll be honest here... it was second hand info that it did not work, I should have tested this myself, apologies).

However, the actual description for all these is not correct anymore. https://github.com/microsoft/playwright/blob/master/docs/api.md#pageselector etc. says:

>The method runs document.querySelector within the page.

That cannot be true anymore since the functions pierce the shadow DOM, so it is not a direct mapping to that function which follows the CSS spec.

I assume then that the only difference between e.g. `page.waitForSelector()` and `page.$()` is that the latter do not have any wait at all? Is `page.$` even needed anymore?

(personally I feel all the `.$` functions are ambiguous due to no naming and should be deprecated in favor of better named functions where applicable).

**Comment by dgozman** [comment]
Great find, thank you! I have updated the docs.

**Comment by dman777** [comment]
Using the Polymer 3 shop app, I am trying to grab the [first tab](https://github.com/Polymer/shop/blob/master/src/shop-app.js#L265) and hit click(). 

![image](https://user-images.githubusercontent.com/887815/82720018-576ba300-9c75-11ea-938c-36a343d93cab.png)


```
describe('TO DO APP TESTS - PLAYWRIGHT', () => {

    beforeEach(async () => {
        browser = await playwright['chromium'].launch({ headless: false })
        context = await browser.newContext();
        page = await context.newPage();
        await page.goto(BASE_URL)
    })

    it.skip('this works', async() => {
        const sel = 'shop-tab'
        page.click('a[href="/list/mens_outerwear"]')
    })

    it('this does not work', async() => {
        const sel = 'shop-tab'
        const btns = await page.$$(sel)
        btns[0].click()
    })
})
``` 
I can grab the href and click it...is this because it is in the normal/light dom? 

I can not grab the first `shop-tab` and click it. Shouldn't I be able to since playwright selectors will walk the dom and pierce shadow dom?

**Comment by dgozman** [comment]
Hmm... Works for me with playwright v1.0.1:

```js
const { chromium } = require('playwright');
(async () => {
  const browser = await chromium.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://shop.polymer-project.org/');
  const sel = 'shop-tab';
  const btns = await page.$$(sel);
  await Promise.all([
    btns[0].click(),
    page.waitForNavigation(),
  ]);
  console.log(page.url());  // Prints https://shop.polymer-project.org/list/mens_outerwear
  await browser.close();
})();
```

What am I missing? Did you forget to await? Maybe the site is different?
