### ISSUE TITLE
[Question] Previously when i click on trace screenshot from the html report, it automatically used to open the trace viewer. Now i am getting a page saying "The Playwright Trace Viewer must be loaded over the http:// or https:// protocols. For more information, please see the docs". Why it is behaving different from before?

### ISSUE THREAD

**Issue by s-sivasubramaniam** [microsoft/playwright#20136]

**Comment by mxschmitt** [comment]
How do you open the HTML report? Do you do it via `npx playwright show-report`? Or do you just double click on the index.html?

Trace Viewer requires a web-serve to be served from, otherwise it won't work.

**Comment by s-sivasubramaniam** [comment]
> How do you open the HTML report? Do you do it via `npx playwright show-report`? Or do you just double click on the index.html?
@mxschmitt first i open the index.html under playwright-report folder by double click and once the report opens in the browser i scroll to the traces section and click on the trace screenshot- this used to open the trace viewer for me but not anymore.

> Trace Viewer requires a web-serve to be served from, otherwise it won't work. - Could you please let me know how do i do this?

**Comment by mxschmitt** [comment]
See here: https://playwright.dev/docs/ci-intro#viewing-the-html-report

**Comment by s-sivasubramaniam** [comment]
@mxschmitt - i checked the suggested link. But still i am not able to figure why it wont launch the trace viewer when i click on highlighted icons in below screenshot
![trace viewer1](https://user-images.githubusercontent.com/122524371/212713122-6212f363-5609-4617-80c9-5193b2a12a76.jpg)
![trace viewer2](https://user-images.githubusercontent.com/122524371/212713145-d9b96645-25e7-4759-a8b9-59f7e23fab2d.jpg)

**Comment by mxschmitt** [comment]
You need to open the report with `npx playwright show-report name-of-my-extracted-playwright-report` and not by opening the HTML file manually.

**Comment by s-sivasubramaniam** [comment]
> You need to open the report with `npx playwright show-report name-of-my-extracted-playwright-report` and not by opening the HTML file manually.

Thanks @mxschmitt this worked for me. By opening the report through npx playwright show-report i was able to navigate to the trace viewer by clicking on the icons.
