### ISSUE TITLE
[Feature] Improve confusing assertions result when running toBeVisible on element that doesn't exist

### ISSUE THREAD

**Issue by shwarcu** [microsoft/playwright#20134]
## Context

I was writing a test that checks if a message from user is displayed in the chat messages list.
My DOM looks like this 
<img width="673" alt="Screenshot 2023-01-16 at 10 22 27" src="https://user-images.githubusercontent.com/58426925/212644936-b7817e59-c1d7-48fe-bc9f-de410655ed42.png">

I have made a very silly mistake by writing following query

```ts
/**
* incorrect locator, element has data-test attribute, not data-testid
*/
const messagesList = page.getByTestId('messages-list');
await expect(messagesList.getByText(message)).toBeVisible();
```
Messages list won't be found because I'm searching by `data-testid` attribute value and element has `data-test`

The test kept failling with following messages
<img width="782" alt="Screenshot 2023-01-16 at 10 30 04" src="https://user-images.githubusercontent.com/58426925/212645630-222c9957-3dc7-4647-86d3-c2bd83accec3.png">

I do not have a lot of experience in Playwright yet and I intuitively understood the message that the problem is that element is found but it's not recognised as visible. Therefore I have spend time tinkering and trying to figure out why Playwright doesn't 'see' an element that is clearly visible.

### Improvement suggestion
It would be great if in similar cases, we would receive a message that element was not found in the DOM, instead of having a message that `.toBeVisible` assertion has failed. It doesn't make much sense to me, to even attempt running `.toBeVisible` assertion on a non-existing element because element that doesn't exist can't be neither hidden nor visible. So I would expect from a testing framework to fail very early and inform me about problem with the locator, not the visibility. 

I am open to contribute to the project and open PR, but I would need a little bit of guidance and hints where to start when it comes to error messages.

**Comment by dgozman** [comment]
@shwarcu I'd recommend to use [Playwright debug tools](https://playwright.dev/docs/running-tests#debugging-tests). These will show elements as Playwright finds them, and you can see whether something is visible. It should be much easier to troubleshoot wrong locators there.

I am not sure there is an action item worth pursuing here.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
