### ISSUE TITLE
[Question] Can we perform assertions in PageObject class?

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#20145]
Scenario: Since we working on website, there is lot of assertions to be handled so i want to perform assertion in page object rather on test file. Can we go with this approach, if yes could you please guide me on this as below code getting error?

```
const { expect } = require('../playwright.config');
class LoginPage{
constructor(page)
{
  this.page=page;
  this.timeoutError = page.locator("//div[@class='ant-alert-content']//div[1]");
}

async login(){
       const error = await this.timeoutError.textContent();
       await expect(error).toContainText('PreTokenGeneration');
}
}
```

![image](https://user-images.githubusercontent.com/77335200/212738164-52f60ded-5f65-4069-90ae-c22f485469b4.png)

**Comment by YusufOzt** [comment]
@mandeepmm1  I m not a microsoft developer but I want to help them when I saw this question. I edit your code.You can try this.

```
import { Locator, Page, expect } from "@playwright/test";

export class LoginPage {
  page: Page;
  timeoutError: Locator

  constructor(page: Page) {
    this.page = page;
    this.timeoutError = page.locator("//div[@class='ant-alert-content']//div[1]");
  }

  async login() {
    expect(await this.timeoutError.textContent()).toContain('PreTokenGeneration')
  }
}
```

You are taking type error, I guess this is related to `const { expect } = require('../playwright.config');` try import { expect } from "@playwright/test".

 If you are using a custom fixture you can add this code into your custom fixture file `export { expect } from '@playwright/test';`

**Comment by YusufOzturk-Development** [comment]
@mandeepmm1  I m not a microsoft developer but I want to help them when I saw this question. I edit your code.You can try this.

```
import { Locator, Page, expect } from "@playwright/test";

export class LoginPage {
  page: Page;
  timeoutError: Locator

  constructor(page: Page) {
    this.page = page;
    this.timeoutError = page.locator("//div[@class='ant-alert-content']//div[1]");
  }

  async login() {
    expect(await this.timeoutError.textContent()).toContain('PreTokenGeneration')
  }
}
```

You are taking type error, I guess this is related to `const { expect } = require('../playwright.config');` try import { expect } from "@playwright/test".

 If you are using a custom fixture you can add this code into your custom fixture file `export { expect } from '@playwright/test';`

**Comment by mandeepmm1** [comment]
> @mandeepmm1 I m not a microsoft developer but I want to help them when I saw this question. I edit your code.You can try this.
> 
> ```
> import { Locator, Page, expect } from "@playwright/test";
> 
> export class LoginPage {
>   page: Page;
>   timeoutError: Locator
> 
>   constructor(page: Page) {
>     this.page = page;
>     this.timeoutError = page.locator("//div[@class='ant-alert-content']//div[1]");
>   }
> 
>   async login() {
>     expect(await this.timeoutError.textContent()).toContain('PreTokenGeneration')
>   }
> }
> ```
> 
> You are taking type error, I guess this is related to `const { expect } = require('../playwright.config');` try import { expect } from "@playwright/test".
> 
> If you are using a custom fixture you can add this code into your custom fixture file `export { expect } from '@playwright/test';`

**Comment by mandeepmm1** [comment]
Thanks @YusufOzturk-Development. It worked for me after changing from `const { expect } = require('../playwright.config');` to `import { expect } from "@playwright/test".`

**Comment by mandeepmm1** [comment]
Thanks @YusufOzturk-Development. It worked for me after changing from `const { expect } = require('../playwright.config');` to `import { expect } from "@playwright/test".`
