### ISSUE TITLE
[Feature] Add page.waitForSuccessfulRequest method

### ISSUE THREAD

**Issue by 4en1x** [microsoft/playwright#20151]
Currently, Playwright has the [waitForRequest](https://playwright.dev/docs/api/class-page#page-wait-for-response) method, which waits for requests without paying attention to the status code.
If you want to wait for a successful request, it is suggested to write
`page.waitForRequest(response => response.url() === 'https://example.com' && response.status() === 200);`

Waiting for successful requests is quite a common way to test API requests, so I would like you to consider including something like `waitForSuccessfulRequest` as an official method.

**Comment by yury-s** [comment]
Can you tell us more about the scenario where you'd need this?

Usually, if you know the response URL you also expect certain status code and you don't need to filter multiple responses. So you can rewrite your code like this to assert the status:

```js
const response = page.waitForResponse(response => response.url() === 'https://example.com');
expect(response.status()).toBe(200);
```

**Comment by yury-s** [comment]
Closing per the response above, please open a new issue if it doesn't work.
