### ISSUE TITLE
[Question] Uploading large files reduces test inspection performance

### ISSUE THREAD

**Issue by sgielen** [microsoft/playwright#20157]
I am developing an application where large medical images must be uploaded for display. This works, but the uploaded data is included in the Playwright traces (perhaps even multiple times), making them very large and difficult to use because of browser performance degradation. At least for me, it is not necessary to include these files in the traces, so I am wondering if there is a way to prevent this.

I started out writing a test with two Mammography cases; these consist of four 2D images, 16 MB each. Because I upload three of them multiple times for unhappy path scenarios, in total I upload 11 images, ~176 MB in total. The Playwright individual trace .zip files are up to 135 MB in size - they contain the original images in `resources`, and since the `trace.trace` file is itself 367 MB I suspect it may also contain another copy. When I load a Playwright trace and (accidentally or not) click the `page.evaluateHandle` action, the browser tab freezes.

This is the code I use to upload the images:

```
export async function dropFileIntoGridImage(page: Page, canvas: Locator, opts: { filename: string, allowFailure?: boolean }): Promise<void> {
  const buffer = await readFile(opts.filename);
  const dataTransfer = await page.evaluateHandle((data) => {
    const bytes = new Uint8Array(data.length / 2);
    for (let i = 0; i < bytes.length; ++i) {
      bytes[i] = parseInt(data[i * 2] + data[i * 2 + 1], 16);
    }
    const dt = new DataTransfer();
    const file = new File([bytes], 'file.dcm', { type: 'application/dicom' });
    dt.items.add(file);
    return dt;
  }, buffer.toString("hex"));
  await canvas.locator('.gi-canvas').dispatchEvent('drop', { dataTransfer });

  // ... check if the upload succeeded ...
}
```

(As a side note: I have tried different methods to get the file buffer into `evaluateHandle` - most of them failed silently, while some of them worked but were much, much slower than this method. Even this one takes >2 seconds for a 16 MB file on my CI, which is definitely acceptable but still somewhat surprising to me for an inter-process transfer. But I digress.)

Would it be possible to exclude from the Playwright trace the data passed into, or out of, `evaluateHandle`? Or do you have some other ideas how to improve this?

If some development is necessary for this, I am willing to contribute if you could give me some thoughts and pointers.

Soon, I would like to start testing with CT scans also, which are ~180 MB per scan and I similarly need to upload multiple scans. However, currently this is impractical as the Playwright trace would likely become multiple gigabytes in size. So it is quite important for me to be able to resolve this. Thank you!

**Comment by yury-s** [comment]
You can start tracing manually and configure the [options](https://playwright.dev/docs/api/class-tracing#tracing-start) to not record the screenshots / snapshots at all. But as far as I understand you want to keep the trace just drop all the large images from it. You can probably postprocess the trace file: unzip it into a directory, delete all images under `resources/` directory larger than X Mb, zip it again. The snapshot will miss deleted resources but should work otherwise, will that work for you?

**Comment by sgielen** [comment]
Indeed, I think the traces are very useful, I would just like to drop the large files from them. (Just to make sure we are on the same page - when I said images in my original post, they are medical input images in DICOM format - from the point of view of Playwright they are simply data files, not screenshots/snapshots.)

The suggestion to remove large files from the `resources` directory makes sense! However, it looks like the information from the files is also in the `trace.trace` file, where line 343 refers to the execution of the code included in my original issue - the line is 34086001 bytes long and there are 11 such lines in the file:

```
{"type":"action","metadata":{"id":"call@32","stack":[{"file":"/home/runner/work/frontend/tests/util/case.ts","line":37,"column":35,"function":"dropFileIntoGridImage"},{"file":"/home/runner/work/frontend/tests/01-mammography-flow.spec.ts","line":34,"column":3}],"apiName":"page.evaluateHandle","internal":false,"objectId":"frame@5fd9f66a9f513bd4d9d7871d8378e7d6","pageId":"page@e7662ba7b754a45b3e2fdc42ce1abde9","frameId":"frame@5fd9f66a9f513bd4d9d7871d8378e7d6","wallTime":1673975146890,"startTime":1306974.416,"endTime":1310206.79,"type":"Frame","method":"evaluateExpressionHandle","params":{"expression":"data => {\n    const bytes = new Uint8Array(data.length / 2);\n    for (let i = 0; i < bytes.length; ++i) {\n      bytes[i] = parseInt(data[i * 2] + data[i * 2 + 1], 16);\n    }\n    const dt = new DataTransfer();\n    const file = new File([bytes], 'file.dcm', {\n      type: 'application/dicom'\n    });\n    dt.items.add(file);\n    return dt;\n  }","isFunction":true,"arg":{"value":{"s":"00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000004449434d02000000554c0400cc000000020001004f4200000200000000010200020055491c00312e322e3834302e31303030382e352e312e342e312e312e312e32000200030055493600312e322e3237362e302e373233303031302e332e312e342e3731363531333439342e333736302e313236393334313831342e33312e310200100055491200312e322e3834302e31303030382e312e320002001
[.....]
000000000000000000000000000000"},"handles":[]}},"log":[],"snapshots":[{"title":"before","snapshotName":"before@call@32"},{"title":"after","snapshotName":"after@call@32"}],"afterSnapshot":"after@call@32","result":{"handle":{"guid":"handle@2c8d10964c041ff6cb8b3a21b9dec4ae"}}}}
```

So to do proper cleanup of the .zip file, I would also have to go through each line of the `trace.trace`, and do something like "if the method is `evaluateExpressionHandle` and the arg.value.s is very large, shorten it". That's possible, of course, but starts to feel like a layer violation. Arguably, it would be better to pass a parameter to `evaluateHandle` to not store the value (in the trace or in the resources) at all, if something like that would be possible. What do you think about that?

**Comment by sgielen** [comment]
I found this relevant issue - https://github.com/microsoft/playwright/pull/18132/files - it already removes Buffers from the trace if I understand it correctly, but since I use a string instead of a Buffer, it does not help me directly. I did try to use Buffers with evaluateHandle but they always failed silently.

**Comment by yury-s** [comment]
Yeah, we can add a tracing option to not store resources larger than X.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
