### ISSUE TITLE
[Question] How do I increase timeout assertion (expect) from global-setup.js?

### ISSUE THREAD

**Issue by xyngfei** [microsoft/playwright#20154]
Although there is some update from [this](https://github.com/microsoft/playwright/issues/9361), due to the current POM design, I have a lot of assertions to ensure the stability of each of the tests. 
However, I noticed that the current expect timeout playwright config does not take the configuration into global-setup.js.

Is there a better way to increase the expect timeout in global-setup.js easily?

**Comment by mxschmitt** [comment]
There is no way of increasing it globally, but for each expect call, you can pass it manually as `{ timeout: 20_000 }`.

Usually you have assertions inside your tests rather than having them inside the global setup.

**Comment by xyngfei** [comment]
How can I refer to the expect timeout from playwright.config.ts setting since I need to pass it manually?

**Comment by yury-s** [comment]
You can import your config and read the value directly:

```ts
import config from './playwright.config';

async function globalSetup() {
    console.log(config.expect?.timeout);
}

export default globalSetup;
```

or in javascript:

```js
const { config } = require('playwright.config');

module.exports = async config => {
    console.log(config.expect?.timeout);
};
```

There is no better way right now but it will become better once https://github.com/microsoft/playwright/issues/17550 is resolved.

**Comment by xyngfei** [comment]
@yury-s 
No idea why I can't import the config properly
<img width="779" alt="image" src="https://user-images.githubusercontent.com/17619539/214754196-9099ccf1-907c-4e3d-887b-ef36e3be0c10.png">

If I m using the expect timeout in a different class, but I cant fetch the value properly, need your further advice. 

```
import { type PlaywrightTestConfig } from "@playwright/test";

class homePageAssertions {
  constructor(readonly formPage: HomePage) {}

  async enterHomePageState(): Promise<void> {
    console.log("expect timeout: " + this.formPage.config.expect?.timeout);
  }
}
```
