### ISSUE TITLE
[BUG] When runing on CI tests not using storageState

### ISSUE THREAD

**Issue by coachQa** [microsoft/playwright#20163]
### Discussed in https://github.com/microsoft/playwright/discussions/19935

<div type='discussions-op-text'>

<sup>Originally posted by **hmajid2301** January  7, 2023</sup>
I'm trying to follow the tutorial here: https://playwright.dev/docs/next/auth#reuse-signed-in-state

To use state so we can start signed in already in our tests. I get as far as creating the `storageState.json` file. But my tests don't seem to use this and load in the correct cookies.

Here is my `playwright.config.ts` file:

```ts
import type { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
	globalSetup: "./global-setup",
	webServer: {
		command:
			"NODE_ENV=test DEBUG=pw:webserver npm run build && NODE_ENV=test npm run preview > svelte_playwright.log",
		port: 4173,
		timeout: 240000,
		reuseExistingServer: !process.env.CI
	},
	use: {
		trace: "retain-on-failure",
		video: "retain-on-failure",
		storageState: "storageState.json"
		// headless: !process.env.CI,
		// browserName: "firefox",
	},
	testDir: "./tests"
};

export default config;
```

My `global-setup.ts` looks like:

```ts
import { chromium, type FullConfig } from "@playwright/test";

async function globalSetup(config: FullConfig) {
	console.log("start global setup!");
	const browser = await chromium.launch({ headless: false });
	const page = await browser.newPage();

	const baseURL = `http://localhost:${config.webServer?.port}`;
	const loginURL = `${baseURL}/login`;
	await page.goto(loginURL);

	const email = "test@bookmarkey.app";
	await page.locator('[name="email"]').type(email);
	const password = "password@11";
	await page.locator('[name="password"]').type(password);
	await page.locator('button[type="submit"]').click();

	await page.context().storageState({ path: "storageState.json" });
	await browser.close();
	console.log("end global setup!");
}

export default globalSetup;
```

My test look like:

```ts
import { expect, Page, test } from "@playwright/test";
import pocketbase from "pocketbase";

test.describe(() => {
	const email = "test+update_password@bookmarkey.app";
	const newPassword = "mY$$ecureP@ssword@112";
	const password = "password@11";
	const nickname = "haseeb";

	test.use({ storageState: "storageState.json" });

	test("Successfully update password in app", async ({ page }) => {
		// await login(page, baseURL || "");
		await page.goto("/my/settings");

		await page.locator('[name="currentPassword"]').type(password);

		const newPassword = "mY$$ecureP@ssword@112";
		await page.locator('[name="password"]').type(newPassword);
		await page.locator('button[type="submit"]').last().click();

		const toastMessage = await page.locator(".message").innerText();
		expect(toastMessage).toBe("Updated password");
	});

	async function login(page: Page, baseURL: string) {
		await page.goto("/login");
		await page.locator('[name="email"]').type(email);
		await page.locator('[name="password"]').type(password);
		await page.locator('button[type="submit"]').click();
		await page.waitForURL(`${baseURL}/my/dashboard`);
	}
});
```

``Link to Repo: https://gitlab.com/bookmarkey/gui/-/merge_requests/59

Am I doing something wrong ? Any idea why this doesn't work ? Thanks</div>

**Comment by yury-s** [comment]
The code looks okay.  Can you elaborate on how you check that the tests are not using saved state?

Try logging  cookies in the global setup and in the test to ensure that everything is loaded as expected:

```js
    await page.context().storageState({ path: 'storageState.json' });
    console.log(await page.context().cookies());
```

Note that some systems rely on [session storage](https://playwright.dev/docs/next/auth#session-storage) for authentication which might be your case.

**Comment by coachQa** [comment]
> The code looks okay. Can you elaborate on how you check that the tests are not using saved state?
> 
> Try logging cookies in the global setup and in the test to ensure that everything is loaded as expected:
> 
> ```js
>     await page.context().storageState({ path: 'storageState.json' });
>     console.log(await page.context().cookies());
> ```
> 
> Note that some systems rely on [session storage](https://playwright.dev/docs/next/auth#session-storage) for authentication which might be your case.

Hey, I create Issue from this topic https://github.com/microsoft/playwright/discussions/19935, but I have same issue. 

Everything works fine localy, but when I run tests on CI (bamboo) it doesnt use storageState. 


Here are example of my code 
// fixture file

```
export const test = base.extend<MyFixtures>({
  page: async ({ page,  userToLogin }, use) => {
    //#region STARTUP PROCESS
    const loginPage = new LoginPage(page);

    await page.setViewportSize({ width: 1920, height: 1080 });

    if (!userToLogin) {
      await loginPage.navigateToLoginPage();
    }

    await use(page);
    //#endregion

    //#region CLEANUP PROCESS
    await loginPage.cleanExit();

    //#endregion
  },

  userToLogin: undefined,

  storageState: async ({ browser, userToLogin }, use) => {
    if (userToLogin) {
      const fileName = path.resolve(
        `storagestates/${userToLogin}.json`
      ) as string;

      if (!fs.existsSync(fileName)) {
        const page = await browser.newPage({ storageState: undefined });

        await page.goto(process.env.BASEURL as string);
        await page.getByPlaceholder('Username').fill(userToLogin as string);
        await page
          .getByPlaceholder('Password')
          .fill(process.env.PASSWORD as string);
        await page.locator('#SignInDetails_SubmitButton').click();
        await page.context().storageState({
          path: fileName,
        });

        await page.close();
      }

      await use(fileName);
    } else {
      await use(undefined);
    }
  },
});

export { expect } from '@playwright/test';
```

Test example


```
test.describe('[ClickTestSuite] Test suite for Asset pages', () => {
  const initPages = (page: Page) => {
    const assetsPage = new AssetsPage(page);
    const assetsDetailsPage = new AssetDetailsPage(page);

    return { assetsPage, loginPage, assetsDetailsPage };
  };

  test.use({
  userToLogin: 'ADMINISTRATOR',
});

  test('[SmokeTest] C89600 - Search: Navigate to Asset details page', async ({
    page,
  }) => {
    const pages = initPages(page);

    const directory = './storagestates';

    console.log(`----------------`);

    fs.readdir(directory, (err, files) => {  // it checks if file with storageState created on CI 
      console.log(files);
    });
    console.log(`----------------`);

    await pages.assetsPage.navigateToAssetsPage();
    await pages.assetsPage.searchAndOpenAssetThumbnailWithText('Oatmeal');
    await pages.assetsDetailsPage.verifyItIsAssetDetailsPage('Oatmeal');
  });
});

```

It works locally, but when I run it on Bamboo test just stuck on login page without using storage state. 

Playwright version: "@playwright/test": "^1.29.2",
Docker image:  mcr.microsoft.com/playwright:v1.29.2-focal

**Comment by coachQa** [comment]
regarding cookies 

I think I found an issue, that`s cookie when we use storageState locally, 
```
{
  "cookies": [
    {
      "name": "__xRequestedBy",
      "value": "",  -- deleted by me
      "domain": "",  -- deleted by me
      "path": "/",
      "expires": -1,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    },
    {
      "name": ".AspNetCore.Identity.Application",
      "value": "",  -- deleted by me
      "domain": "",  -- deleted by me
      "path": "/",
      "expires": 1674465718.541701,
      "httpOnly": true,
      "secure": true,
      "sameSite": "None"
    }
  ],
  "origins": []
}
```
And that`s how coookies looks on CI 

```
[1A[2K[
	  {
	    name: [32m'__xRequestedBy'[39m,
	    value: ,  -- deleted by me
	    domain: , -- deleted by me
	    path: [32m'/'[39m,
	    expires: [33m-1[39m,
	    httpOnly: [33mtrue[39m,
	    secure: [33mtrue[39m,
	    sameSite: [32m'None'[39m
	  }
	]
```
this part is missing  "name": ".AspNetCore.Identity.Application",

Why it could happens?

**Comment by yury-s** [comment]
Looks like the server doesn't return the cookie when you run it in the CI environment or you export the storateState before the page receives response with the cookie (CI machines are usually slower). To fix the latter you may need to wait for a particular response that contains `.AspNetCore.Identity.Application` cookie before exporting storageState. Try looking at the trace to see which response sets the cookie or add  [page.on('response')](https://playwright.dev/docs/api/class-page#page-event-response) listener to dump response cookies. You can also compare it locally and on CI.

**Comment by coachQa** [comment]
> Looks like the server doesn't return the cookie when you run it in the CI environment or you export the storateState before the page receives response with the cookie (CI machines are usually slower). To fix the latter you may need to wait for a particular response that contains `.AspNetCore.Identity.Application` cookie before exporting storageState. Try looking at the trace to see which response sets the cookie or add [page.on('response')](https://playwright.dev/docs/api/class-page#page-event-response) listener to dump response cookies. You can also compare it locally and on CI.

Thank you :) 

Your advise helps me!!  Have a good day :) 

I put waitForResponse with  promise  and it starts working :)  

```
   await Promise.all([
          page.waitForResponse(
            response =>
              response.url().includes('') &&
              response.status() === ''
          ),
          page.locator('#login').click(),
        ]);
```
