### ISSUE TITLE
[Feature] Click and hold on an element

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#20172]
Hi Team,

In the docs, I have been trying to find out the functionality for performing `clickAndHold` operation on an element. But couldn't find any related docs.

Would it be possible to provide the `clickAndHold` API if it's not available there already?

**Use Case:**
We have a scenario, where we can open multiple pages (First page -> Second Page from first page -> Third page from second page > ....) and then there is a button available. If we click & hold on that button, then it will navigate back to first page.

**Comment by yury-s** [comment]
You can use raw [mouse api](https://playwright.dev/docs/api/class-mouse) to and call [mouse.down()](https://playwright.dev/docs/api/class-mouse#mouse-down) and not call mouse.up:

```js
    const box = await page.locator('foo').boundingBox();
    await page.mouse.move(box?.x! + box?.width! / 2, box?.y! + box?.height! / 2);
    await page.mouse.down();

```

 Will that work for you?

**Comment by ukdas** [comment]
Hi @yury-s ,

Thank you so much for quick response and providing the details. Yes, It's working fine with this `mouse` api. :)

Wouldn't it be good to have a single API in future to perform this only with `await page.locator('foo').clickAndHold()` instead of performing these 3 operations every time?

Please feel free to close this issue, if there is no plan for creating a single API for this.

**Comment by yury-s** [comment]
There are no plans to add such API due to low demand and because there is a workaround using raw mouse api.
