### ISSUE TITLE
[Feature] Please add a feature where you can control the mouse speed for individual movements

### ISSUE THREAD

**Issue by triott** [microsoft/playwright#20170]
I'm writing a function to generate real user mouse movements, which would include eliminating straight lines and single-speed mouse movements. I managed to find ways to overcome the former, but with playwright python, there seems to be only one speed throughout a single mouse movement to point A to point B. The only option to change speed for mouse movements in a single page seems to be the slow_mo argument in launch(), but even with that it only so far provides one speed for all actions on page. Please add a feature for page.mouse where you can adjust the speed individually for every single point A to point B movement.

Many thanks
Andrea

**Comment by yury-s** [comment]
You can split a single call to [mouse.move](https://playwright.dev/python/docs/api/class-mouse#mouse-move) into a series of moves and insert arbitrary delays between them, something like this:

```js
await mouse.move(10, 10);
await page.waitForTimeout(100);
await mouse.move(20, 20);
await page.waitForTimeout(100);
await mouse.move(30, 30);
```
would that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
