### ISSUE TITLE
[BUG]How to use grep invert for skipping tests with multiple tags

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#20179]
How to use grep invert for skipping tests with multiple tags like abc, xyz and so on

I tried below commands. Both dont seem to work
cross-env test_env=staging npx playwright test --grep-invert "@abc | @xyz" --workers=5  --project=webkit

cross-env test_env= staging npx playwright test --grep-invert @abc --grep-invert @xyz --workers=5  --project=webkit

In both the cases only the tests with tags @xyz are being ignored.

**Comment by yury-s** [comment]
Remove whitespaces from the first expression as they are counted as part of the tags otherwise (`@abc ` or ` @xyz`):

```sh
npx playwright test --grep-invert "@abc|@xyz"
```

--grep-invert doesn't support multiple values so the second version won't work.
