### ISSUE TITLE
Getting reference error when I try to use element.evaluate

### ISSUE THREAD

**Issue by alaamhmd** [microsoft/playwright#20188]
### Discussed in https://github.com/microsoft/playwright/discussions/19665

<div type='discussions-op-text'>

<sup>Originally posted by **alaamhmd** December 22, 2022</sup>
Hello,

I'm trying get one of the element CSS values using evaluate but I keep getting this error `locator.evaluate: ReferenceError: style is not defined` if i try to parametrize the method which get the CSS value.
### **Here's a snipped code from what I use:**

**reuseMehods.class**
```

async getElementStyle(locator, style): Promise<any> {

    const x = await this.page.locator(locator)
    const v = await x.evaluate((ele) => {

     return window.getComputedStyle(ele,null).getPropertyValue(style);

    });

    return v;
```
**Test suite where I use the method**

```
  test('test name', async ({ reuseMehods }) => {
    
   let s = await  reuseMehods.getElementStyle(elementLocator, "font-style")
    console.log(s); 
```

Can someone guide me here what I'm exactly doing wrong?
Or how else i can get any element css styles?</div>

**Comment by ltsuda** [comment]
I think is because you are evaluating the Locator, not the Page.

See documentation examples, they only uses `.evaluate()` on `.page`

https://playwright.dev/docs/evaluating

**Comment by yury-s** [comment]
This code is evaluated in the page context and doesn't have access to the style variable (which exists in the node contexts only):

```js
(ele) => {
     return window.getComputedStyle(ele,null).getPropertyValue(style);
    }
```

You have to pass it manually from node the to the page as the function's [argument](https://playwright.dev/docs/evaluating#evaluation-argument):

```js
async getElementStyle(locator, styleValue): Promise<any> {
    const x = await this.page.locator(locator)
    const v = await x.evaluate((ele, style) => {
       return window.getComputedStyle(ele,null).getPropertyValue(style);
    }, styleValue);
    return v;
}
```
I renamed style to styleValue to make it more apparent, this is not strictly necessary.
