### ISSUE TITLE
[Feature] Reusable functions in Codegen

### ISSUE THREAD

**Issue by nicogtm** [microsoft/playwright#20189]
Often a certain set of test steps is part of many tests. Fundamental parts of your software's workflow - e.g. open a product page; add an item to the shopping cart; go through checkout - that are often repeated to test other functionality.

It is desirable to have a way to reuse these workflows. When writing tests manually, you can export test steps as functions and reuse those functions. Codegen however will just generate the same set of steps over and over. Which is a problem when that workflow changes, in which case a great number of tests have to be adjusted, instead of a single function - unless you manually go over your generated tests looking for common steps.

Codegen could recognize generating a set of steps that is exactly the same as one of the defined functions - and replace them. Maybe by defining a specific folder to search for matching function exports.

That would help with writing easily maintainable tests while also keeping the lengthy, errorprone manual effort of test creation small.

**Comment by yury-s** [comment]
You can manually extract common functionality into a function and then update it when needed using [Record at cursor](https://playwright.dev/docs/getting-started-vscode#record-at-cursor), this way it will update it for all affected tests. 

Closing this request as we don't have any plans to support this functionality. There are other tools that could aid with finding repeated code blocks and refactoring them.
