### ISSUE TITLE
[Question] where can i find the error enum throws from page.goto

### ISSUE THREAD

**Issue by yusong0926** [microsoft/playwright#20183]
when I request some urls, sometimes it will throw some errors, for example:
page.goto: net::ERR_NAME_NOT_RESOLVED at https://w.unkownwebsite/

does anyone know the error enum "net::ERR_NAME_NOT_RESOLVED" comes from?
where can I find the reference of those error enum so I can classify different type of errors.

**Comment by mxschmitt** [comment]
There is no enum for that, each browser throws individual errors with different error messages. All errors are from type Error.

**Comment by yury-s** [comment]
> does anyone know the error enum "net::ERR_NAME_NOT_RESOLVED" comes from?
> where can I find the reference of those error enum so I can classify different type of errors.

As Max said these errors are browser (and sometimes platform) specific. They come from the network stack. The one you are asking about is defined [here](https://source.chromium.org/chromium/chromium/src/+/main:net/base/net_error_list.h;l=147;drc=00e7ff081d84b492e90a6557eef862ade4a49bdc), you can look at the other values in the same file to get an idea.
