### ISSUE TITLE
[Question] call api with the result

### ISSUE THREAD

**Issue by FranGomezVenegas** [microsoft/playwright#20187]
Hi,

I want to notify the run and the summary for the testing and this is done by one api endpoint, then my thought is on having one method to perform this and then be invoked/called from the tests at the very end of .....each? is there anything like 'atTheEndOfAll' to allow me run this method with the summary for all tests run (to not bombing the api with dozens in seconds/minutes)....

Any experience doing things like that?

Regards,

**Comment by yury-s** [comment]
You can implement a custom [reporter](https://playwright.dev/docs/api/class-reporter) and place this logic inside [onEnd](https://playwright.dev/docs/api/class-reporter#reporter-on-end) which is called only once. You can save root test suite in [onBegin](https://playwright.dev/docs/api/class-reporter#reporter-on-begin) method and then iterate over all test cases in the suite to get their results in onEnd.

**Comment by FranGomezVenegas** [comment]
Nice, Thanks @yury-s
