### ISSUE TITLE
[Question]: How to get a sibling element using the child element of the other sibling

### ISSUE THREAD

**Issue by ct-melodye** [microsoft/playwright#20184]
I would like to click the red highlighted element using the yellow highlighted element as locator (refer to image below). 
 
![image](https://user-images.githubusercontent.com/64621631/213135683-225a52bc-8fcb-425d-a94f-9bfc42cd8612.png)

**Comment by yury-s** [comment]
Did you try using [codegen](https://playwright.dev/docs/codegen-intro#running-codegen) to pick a selector? It's not quite clear from your screenshot how you would identify the <a> tag, how unique its containing element is etc. There are many ways to select what you want and I suggest you start with codegen's recommendation. You can looks at https://playwright.dev/docs/other-locators to see if one of the esoteric locators would work better for you. We need to better understand you constraints to help.

**Comment by ct-melodye** [comment]
Yes, I've been using codegen for picking most of my selectors but for this instance, the page is dynamic and the element that I should be getting might change location so I have to use a particular name that is a sibling of the link that I'm trying to get. 

For the meantime, I managed to do it by some workaround as follows:
` let tasks = this.page.locator('section > .item-list > li > .list-div > .details-div > a');`
`        const tasksCount = await tasks.count();`
`        let finalCount = 0;`
`        for(let i=0; i<tasksCount;i++){`
`            let try1 = await tasks.nth(i).textContent();`
`            if(try1?.includes('6x4 Edgewrap Signboard')==true){`
`                 finalCount = i+1;`
`                 break;`
 `           }`
`        }        `
`        console.log(finalCount);`
`        await this.page.locator('section > .item-list > li:nth-child('+finalCount+') > .list-div > .list-btn > a > .cs-1fr-auto-grid > button').click();`

**Comment by ct-melodye** [comment]
> ```js
> page.locator('.list-div', {
>     has: page.locator('.details-div', { hasText: 'Product' })
> }).locator('.list-btn', { hasText: 'Add' });
> ```

This works too! I just added nth(x) to get the first matching result. Thank you!
