### ISSUE TITLE
[Question] Use of different config parameters per folder in same framework

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20199]
Hello team, 

I would like to know if it is possible to set different parameters according to the folder.

Specifically, I would like to use different baseURL according to the folders I will have. My tree structure is as such : 
tests 
|
- folder 1
- folder 2
- 
I would like to use one baseURL for folder 1, and another one for folder 2.

I'm not sure usingprojects" feature in the config.ts would suit me because I'm using VS Code so I won't launch my tests with commandline.

Many thanks in advance,

Regards,

Johan

**Comment by yury-s** [comment]
You can override the baseUrl in each test file:
```js
test.use({
  baseURL: 'foo'
});
```
or you can provide your own [fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture) for baseURL that would return different result depending on current test.

```js
  import { test as base } from '@playwright/test';

  export const test = base.extend({
    baseURL: async ({ }, use, testInfo) => {      
      await use('http://mydomain/' + path.dirname(testInfo.titlePath[0]));
    },
  });

```


> I'm not sure usingprojects" feature in the config.ts would suit me because I'm using VS Code so I won't launch my tests with commandline.

You can switch between tests [projects in VSCode](https://playwright.dev/docs/getting-started-vscode#run-tests-on-specific-browsers).

**Comment by MehseinJohan** [comment]
Hello Yuri,

Many thanks, exactly what I needed. As I am also using the global-setup file, how could I use this feature as well in the global-setup or the playwright config file ? Thank you in advance.

Johan
