### ISSUE TITLE
[BUG] When I try to run against Mobile Safari I got an error that (locator.textContent: Target crashed)

### ISSUE THREAD

**Issue by magdyheiba** [microsoft/playwright#20195]
**Context:**
- Playwright Version: [1.29.2]
- Operating System: [Mac OS ventura V13.1]
- Node.js version: [v18.12.1]
- Browser: [Mobile Safari]

**Code Snippet**
<img width="519" alt="Screenshot 2023-01-18 at 6 01 40 PM" src="https://user-images.githubusercontent.com/38945724/213225471-647e3b7d-e8f4-4d25-9900-541e7aab675c.png">

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
 this.paymentValue_text = page.locator('//h5[contains(.,"Payment: ")]/span');

 this.checkoutPrice = await this.paymentValue_text.textContent();
```

**Describe the bug**

All the test are working on all browsers/Projects but on Safari I got the attached error

**Comment by mxschmitt** [comment]
Can you provide a repro for us so we can run and reproduce it locally? This would help us a ton!

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one when you get back to it.
