### ISSUE TITLE
Customizing screenshot file path

### ISSUE THREAD

**Issue by sarweshkumar2018** [microsoft/playwright#20194]
How does Playwright creates test-results folder along with test case sub-folder to save the screenshot and traces zip.
Is there any way to insert the test folder name dynamically to the path.
page.screenshot({path: 'test-results/${testFolderName}/confirmation.png'})

**Comment by yury-s** [comment]
You can use [`snapshotPathTemplate `](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template) to configure custom snapshot path that will be used for all [toHaveScreenshot()](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1) calls.

You can also get access to the files inside [outputDir](https://playwright.dev/docs/api/class-testproject#test-project-output-dir) via [testProject.outputDir](https://playwright.dev/docs/api/class-testproject#test-project-output-dir) and [testInfo.outputPath()](https://playwright.dev/docs/api/class-testinfo#test-info-output-path):

```ts
test( 'my test description @tag', async ({ page, baseURL }) => {
  const p = test.info().outputPath('my-file');
  await fs.promises.writeFile(p, "test");
});

```
