### ISSUE TITLE
[BUG] I am not getting the current page url using page.url() method

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#20196]
**Context:**
- Playwright Version: [1.28.1]
- Operating System: [ Mac]
- Java
- Browser: [Chromium]
- Extra: Actually we would like to login our application with different users , would like to bypass the url with username and password after fetching the current url some how i always get below error code while fetching the url.
- **chrome-error://chromewebdata/**

**Code Snippet**

 clickSignin();
        page.waitForTimeout(5000);
        System.out.println("#######" +page.url());
        StringBuilder builder = new StringBuilder(page.url());
        builder.insert(8,"userName" + ":" + "password" + "@" );
page.navigate(builder.toString());

**Describe the bug**

Actually we would like to login our application with different users , would like to bypass the url with username and password after fetching the current url some how i always get below error code while fetching the url.
- **chrome-error://chromewebdata/**
-   Could you help me how can we work with different users  for MFA application i used setHTTPcredentials in browserContext but its in hooks file it is triggering before the feature step and i need to run same scenario with different users how can we acheive this?

**Comment by yury-s** [comment]
To login to your application with different users, you can follow [this doc](https://playwright.dev/docs/auth#multiple-signed-in-roles). It's not quite clear from the description why the navigation fails (chrome-error://... is an built in page which is shown in case of network errors). It may be that you are sending request to a non-existing url or something else, cannot tell based on the snippet and the information you provided.

setHTTPcredentials  will only help with basic [http authentication](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication) while modern apps use more sophisticated logic.

Try following [this guide](https://playwright.dev/docs/auth#automate-logging-in) and if you think there is playwright bug, open another issue with a reproducible example that we can run locally and reference to this issue.
