### ISSUE TITLE
Font kerning in WebKit

### ISSUE THREAD

**Issue by codykaup** [microsoft/playwright#20203]
It appears others are experiencing this issue as well so I reopened it as a bug rather than a question!

---

Hey there! 👋  I didn't think this was officially a bug but more of a question. We're still working on a reproducible example but it's proving to be rather difficult. Anyway... here we go!

We're working on switching our tests to Playwright but can't figure out some behavior in WebKit and was hoping for some guidance. We're seeing some inconsistencies in font rendering but only on Safari (see below).

![safari_kerning](https://user-images.githubusercontent.com/35509748/213271985-e82635d6-3214-46b0-9936-d0809514e442.gif)

No matter what we do, WebKit appears to shift text ever so slightly around the page and causing our tests to fail. This shift doesn't happen every time but enough to make it annoying. We don't see any errors when rendering and the fonts pull from the CDN just fine. It's almost like WebKit has a non-deterministic way of laying out text? 🤔 

Environment:
- Playwright Docker container: `v1.25.1-focal`
- Host OS: `Ubuntu 20.04`

Things we tried:
- Multiple Ubuntu versions
- Global CSS property to remove kerning: `font-kerning: none;`
- Flipped between GTK and WPE
- Looked into using the SSIM version of the diff but that still picked up the shift
- Tried different Safari versions (including the latest version of Playwright)

Has anybody else seen this happen? Any suggestions on what could be causing this?

**Comment by yury-s** [comment]
Can be a webkit bug. Does it reproduce on mac? Having a repro would be very helpful.

**Comment by codykaup** [comment]
> Can be a webkit bug. Does it reproduce on mac? Having a repro would be very helpful.

I haven't been able to reproduce it on my M1. It appears to only happen on Linux at the moment.

I'm trying to narrow it down but it seems like a combination of things or loading a page over a certain size. Still working on it!

**Comment by yury-s** [comment]
@codykaup any luck with getting a repro?

**Comment by codykaup** [comment]
Sorry @yury-s we've been trying the past few days without any luck. We've tried a few different things but we can only _sometimes_ trigger the issue with a large amount of traffic. Unfortunately, that makes the feedback loop longer than we'd like. 

One interesting thing though is it's less consistent than we thought. WebKit appears to change kerning on a word like "to" by a single pixel on one instance on the page but not another (during the same page load). The issue itself appears in the same handful of spots every time but what's causing them to trigger is still unknown.

**Comment by codykaup** [comment]
We managed to figure this one out but the stars had to align just right. To trigger this issue, we had to run the Focal Playwright container inside an Amazon Linux 2 instance, run a series of screenshots in a row, and stress the CPU all at the same time. Once we did that, we were able to trigger this issue more often to diagnose what was going on.

Inside our workflow, we checked for fonts loading but not again after a bunch of potential async calls on the page. Running a second check after those calls fixed this issue even when the CPU was stressed!

```js
await page.evaluate(() => document.fonts.ready);
```

**Comment by dsmmcken** [comment]
![kerning_360](https://github.com/microsoft/playwright/assets/1576283/e0658b8c-cb18-4b86-839c-b2281725159e)

I don't have a good reproducer, but seeing the same issue. Webkit, on ubuntu 20.04 w/ docker container. Only happens in github CI, screenshots generated with the same docker container locally against ubuntu are consistent. Adding a `document.fonts.ready` did not help at all.

I gave up and change the text for the test.

**Comment by zouxuoz** [comment]
Hey, we had same issue. In our case it related to to dynamically calculated `letter-spacing`.

So it looks like this:
![Screen Recording 2024-03-17 at 11 48 29](https://github.com/microsoft/playwright/assets/9217163/43d585dc-30df-4cf1-a83a-5386b8420a8d)

We have CSS variable like this: `--rui-letter-spacing-h6: calc(-0.1em / 14)`, it can have different behaviour for the development and production builds, because for the production build it transformed to `--rui-letter-spacing-h6:-0.00714em`.

| Development build      | Production build |
| ----------- | ----------- |
| <img width="420" alt="image" src="https://github.com/microsoft/playwright/assets/9217163/64269918-31e7-40b8-bef3-9ac64860b80e">      | <img width="420" alt="image" src="https://github.com/microsoft/playwright/assets/9217163/6b1cadf0-b494-4fbd-831a-711b934928d0">       |

Reproduced for the Linux only. On MacOS both builds produce same screenshots.

I checked it only for the `letter-spacing`, but maybe others CSS properties (which affect to the font rendering) can produce same issues for the Linux.

**Comment by siarheiyelin** [comment]
Hello everyone! 👋
I would like to share my observations:
- Exactly the same issue is reproduced on version "1.43.1" as well
- It is only reproduced in "webkit" engine
- In our case it is reproduced only for one specific place (word) on a page, even though same word is repeated more than once. 
![image](https://github.com/microsoft/playwright/assets/1902079/eb38c9ac-44b4-4c45-bc18-433aa6ddcc3d)
- The text is located inside an element with next styles (not sure though whether it matters or not)
```
    position: fixed;
    inset: 0px auto auto 0px;
    z-index: 2000;
    transform: translate(29px, 70px);
```
- Sometimes it passes from the second retry and sometimes not
- It is reproduced in GitHub actions (ubuntu-latest) and (less often) via Docker container (based on playwright:v1.43.1-jammy) on windows host.

**Comment by dsmmcken** [comment]
Some other things I've tried but didn't work:

- I've changed our tests that generate the snapshots and CI to both run inside the playwright docker container to have a consistent environment.
- I tried setting css for playwright tests to disable kerning, ligatures and text rendering for webkit. My theory being if kerning is somehow non-deterministic, maybe turning it off entirely would help?

```css
* {
  -webkit-font-smoothing: none !important;
  font-variant-ligatures: none !important;
  font-feature-settings: 'liga' 0 !important;
  font-kerning: none !important;
  text-rendering: optimizespeed !important;
}
  ```
Result still are sometimes inconsistent and fail 😢 

I feel like webkit is somehow at fault, given that sometimes it succeeds and sometimes it fails.

**Comment by cooper667** [comment]
> Some other things I've tried but didn't work:
> 
> * I've changed our tests that generate the snapshots and CI to both run inside the playwright docker container to have a consistent environment.
> * I tried setting css for playwright tests to disable kerning, ligatures and text rendering for webkit. My theory being if kerning is somehow non-deterministic, maybe turning it off entirely would help?
> 
> ```css
> * {
>   -webkit-font-smoothing: none !important;
>   font-variant-ligatures: none !important;
>   font-feature-settings: 'liga' 0 !important;
>   font-kerning: none !important;
>   text-rendering: optimizespeed !important;
> }
> ```
> 
> Result still are sometimes inconsistent and fail 😢
> 
> I feel like webkit is somehow at fault, given that sometimes it succeeds and sometimes it fails.

We spent so long on this, trying lots of things and the only thing that has worked is we now don't run it in docker...we run webkit on Mac locally and Mac in CI. 

Obviously not ideal, but it has worked well so far, with no webkit text issues over 1000s of runs

**Comment by AlekseyManetov** [comment]
Hi @codykaup,

It seems that this issue is still occurring. Probably you can reopen it and convert it into an issue, since it's looks not like a question?

**Comment by mxschmitt** [comment]
We need a reproduction. Since this issue seems very old / involved, please re-file with something we can run locally.

**Comment by morawski-v** [comment]
Hey, to people who might still struggle with this issue. In my case, adding this flag to Chromium fixed it.

https://peter.sh/experiments/chromium-command-line-switches/#disable-font-subpixel-positioning

**Comment by mbrodala** [comment]
The particular test config for everyone who doesn't want to dig through the docs first:

```js
export default defineConfig({
  // ...
  use: {
    ...devices['Desktop Chrome'],
    launchOptions: {
      args: [
        '--disable-font-subpixel-positioning',
      ],
    },
  },
});
```

See [launchOptions](https://playwright.dev/docs/api/class-testoptions#test-options-launch-options)
