### ISSUE TITLE
First TAG is ignored when using selector('#id')

### ISSUE THREAD

**Issue by M4Al** [microsoft/playwright#20202]
I'm trying out the new Component testing feature. Not sure if it's related to that. 

So I'm writing a few basic tests for a component and want to try to check if a gven element with a known id is present.

My shortened testing code
```
const component = await mount(
        <Component />
    );

    var a = component.locator("div#some").elementHandles() 
    var b = component.locator("div#plop").elementHandles() 
    var c = (await a).length; // Yield 0
    var d = (await b).length; // Yields 1
```

The resulting HTML code in the brower looks like this
```
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Testing Page</title>
    <script type="module" crossorigin="" src="/assets/index.27d3dd85.js"></script>
  <style data-emotion="css" data-s=""></style></head>
  <body>
    <div id="root">
		<div id="some">
			<div id="plop">
		</div></div></div>    
  </body><x-pw-glass style="position: fixed; inset: 0px; z-index: 2147483647; pointer-events: none; display: flex;"></x-pw-glass></html>
```

I've tested quite a few permutations of this and it seems like the top element of the component can never be found with the locator.

**Comment by yury-s** [comment]
Note that mount returns locator of the component element and all subsequent `component.locator()` will search within it. You can find the element by `div#some` in the page but not within itself:

```js
test('test', async ({ mount, page }) => {
    const component = await mount(
        <Component />
    );
   expect (await page.locator("div#some").count()).toBe(1);
});

```

**Comment by M4Al** [comment]
I still think this is quite inconsistent. I was trying to check if the component was rendered (as in some situation is should not rendered at all).
I expected the div#root to be the starting point of the locator.

What would then be the suggested way of checking this? (I added the second div#some specifically for testing purposes now.

Thanks
