### ISSUE TITLE
[Feature] Set maxRedirects on page.goto

### ISSUE THREAD

**Issue by rightaway** [microsoft/playwright#20213]
maxRedirects in https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get would be useful in page.goto method so we can set a limit on how many redirects are allowed when requesting a page.

**Comment by Kovah** [comment]
I just stumbled on this issue and I guess I figured it out, but had to tweak the response a bit. It seems that the `route.fulfill()` function interprets any `Location` header in the response and follows that redirect.

That's the final code and it seems to work:
```javascript
await page.route('**', async route => {
    const response = await route.fetch({maxRedirects: 0});
    let headers = response.headers();
    delete headers['location'];
    delete headers['Location'];
    return route.fulfill({
        response: response,
        headers: headers,
    })
});
response = await page.goto(req.query.url, {
    timeout: timeout,
    waitUntil: 'domcontentloaded'
});
```
