### ISSUE TITLE
[BUG] Incorrect test execution time logged in HTML Report when tests are executed in Parallel.

### ISSUE THREAD

**Issue by khanjunaid53** [microsoft/playwright#20215]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node.js version: [e.g. 12.22, 14.6]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**
 The below code snippet runs 5 tests in parallel using 3 workers. Ideally the test execution is ideally completed in around 60 seconds owing to parallelisation but the HTML report shows the time taken for execution to be around 167 seconds / 2.8 mins which does not seems to be the case.

```javascript
import { test, expect, Page } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
});

test.beforeAll(async ({ }) => {
  await console.log('Parallel Index: '+process.env.TEST_PARALLEL_INDEX+ '# Execution Start time: '+ getTimeStamp())
});

test.afterAll(async ({  }) => {
  await console.log('Parallel Index: '+process.env.TEST_PARALLEL_INDEX+ '# Execution Finish time: '+ getTimeStamp())
});

test.describe.parallel('Test execution time', () => {
  test('Test 1', async ({ page }) => {
    await page.waitForTimeout(30000);  });

  test('Test 2', async ({ page }) => {
    await page.waitForTimeout(30000);
  });

  test('Test 3', async ({ page }) => {
    await page.waitForTimeout(30000);  });

  test('Test 4', async ({ page }) => {
    await page.waitForTimeout(30000);
  });

  test('Test 5', async ({ page }) => {
    await page.waitForTimeout(30000);  });

});


function getTimeStamp(){
    var m = new Date();
    var dateString =
        m.getUTCFullYear() + "/" +
        ("0" + (m.getUTCMonth()+1)).slice(-2) + "/" +
        ("0" + m.getUTCDate()).slice(-2) + " " +
        ("0" + m.getUTCHours()).slice(-2) + ":" +
        ("0" + m.getUTCMinutes()).slice(-2) + ":" +
        ("0" + m.getUTCSeconds()).slice(-2)+ "";

    return 'UTC '+dateString;
}


```

**Describe the bug**
Report:
![image](https://user-images.githubusercontent.com/121419016/213401098-16e9e0fd-fc65-4d95-934c-a5715f0a20c0.png)
Console Logs:
![image](https://user-images.githubusercontent.com/121419016/213401202-313089a9-0dc1-4f53-8e32-70aaae452b45.png)

The following issues may be considered:

1. No different in test execution time is reported when TCs are run in Serial / Parallel mode.
2. The difference is very significant when the number of TCs are fairly large.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/11334, please upvote that report instead.
