### ISSUE TITLE
[Question] How to use beforeEach when there are more than 1 test case?

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#20217]
Using POM framework, I have scenario where i want to run a set of code on before every test case. I have used beforeEach() in the below code as shown in snapshot. But facing issue, so someone help me how to create beforeEach() in the below snippet

![image](https://user-images.githubusercontent.com/77335200/213441108-870618b2-881e-4e20-906b-79080097ef75.png)

Also attaching the error below; 
![image](https://user-images.githubusercontent.com/77335200/213441292-3844a4cd-5ace-433e-b03b-76481d365930.png)

**Comment by ltsuda** [comment]
You probably need to create that `consts` outside of the `.beforeEach()` as `let`, then assign the values in the `.beforeEach()`, so you can use them in the test cases. So, you won't need the `page` fixture in the test hooks.

Something like:

```javascript
test.describe("Test Suite", () => {
    let myPage

    test.beforeEach(async ({ page }) => {
        myPage = myPOM(page)
    })

    test("test name", async ({ }) => {
        myPage.doSomething()
    })

```

**Comment by mandeepmm1** [comment]
thanks @ltsuda It worked. Closing this ticket
