### ISSUE TITLE
Test timeout of 30000ms exceeded error

### ISSUE THREAD

**Issue by ferozali690** [microsoft/playwright#20212]
I have a playwright test case where I want to get a web vital score called **cumulative layout shift**  from [Layout Instability API](https://developer.mozilla.org/en-US/docs/Web/API/Layout_Instability_API) but when I run the test case I am getting error of timeout exceeded as I tried to increase the time of the test case in the config file as well but the result is same error.
<img width="992" alt="Screenshot 2023-01-19 at 1 15 05 PM" src="https://user-images.githubusercontent.com/26819886/213384029-24cf176b-3aae-4e08-a64c-73c262de7634.png">

```
export const CumulativeLayoutShift = async (page: Page) => {
  const cummulativeLayoutShift: any = await page.evaluate(() => {
    return new Promise((resolve) => {
      const observer = new PerformanceObserver((list: any) => {
        const result = list.getEntries();
        resolve(result[0]);
      });

      observer.observe({ type: 'layout-shift', buffered: true });
    });
  });
  console.log(`SHIFT - ${cummulativeLayoutShift}`);
  return cummulativeLayoutShift;
};
```
```
test('network throttling fast 3g', async ({ page }) => {
  await page.goto(HOME_PAGE_URL, { timeout: 50000 });

  const client = await page.context().newCDPSession(page);
  await client.send('Network.enable');
  await client.send('Network.emulateNetworkConditions', FAST_3G_CONFIG);
  expect(await CumulativeLayoutShift(page)).toBeLessThan(CUMULATIVE_LAYOUT_SHIFT_TIME_THRESHOLD);
});
```

**Comment by yury-s** [comment]
The test case is timing out while waiting for PerformanceObserver's callback to be invoked.

There are a few things you can try to fix this issue:

* Disable network throttling to see if the issue persists.

* Try increasing the timeout value of your test case even more. I only see that you increase navigation timeout to 50s but the total test timeout is set to 30s. You can read more about different timeouts in playwright [here](https://playwright.dev/docs/test-timeouts).

* Try to see if you are able to get the layout shift score in the browser dev tools by running the same code in the browser console before running the test cases.

**Comment by ferozali690** [comment]
- I tried increasing the timeout in the playwright config file as well and disabled network throttling and ran the test the issue remains the same
- and coming to the layout shift score I am getting the score in by running the code in the browser console.
<img width="888" alt="Screenshot 2023-01-20 at 12 23 12 PM" src="https://user-images.githubusercontent.com/26819886/213635637-c4c8b2f8-3084-408f-898f-8883ccea21a7.png">

- but when tried removing the console log and try running the loop to get the value property in the browser console it returns undefined
<img width="464" alt="Screenshot 2023-01-20 at 12 29 14 PM" src="https://user-images.githubusercontent.com/26819886/213636453-815570d6-732b-431c-95f2-0a6341c07fb9.png">
