### ISSUE TITLE
[Question] Why do shared variables get unset after first failure even in non serial mode?

### ISSUE THREAD

**Issue by OShalaby** [microsoft/playwright#20225]
Not Sure if this is a bug or not but here we go.

```
import { test, expect } from '@playwright/test';

let userToken;
test("Login", async ({ request, baseURL }) => {
    const data = require('../testData.js').login_details;
    const response = await request.post(`${baseURL}authenticate`, {
        data: data
    });
    const respBody = await response.json()
    
    console.log(respBody);
    expect(response.status()).toBe(200);

    userToken = respBody.data.token
});

let profileId;
test("create a new profile", async ({ request, baseURL }) => {
    const response = await request.post(`${baseURL}profiles`, {
        data: require('../testData.js').new_profile,
        headers: {
            authorization: `Bearer ${userToken}`
        }
    })
    const respBody = await response.json()

    console.log(respBody);
    expect(response.status()).toBe(201);
    profileId = respBody.data.id
});

test("create a post", async ({ request, baseURL }) => {
    const response = await request.post(`${baseURL}posts/create`, {
        data: {
          text: 'foo bar'
        },
        headers: {
            authorization: `Bearer ${userToken}`
        }
    })
    expect(response.status()).toBe(201);
});

test("delete a profile", async ({ request, baseURL }) => {
    const response = await request.delete(`${baseURL}profiles/${profileId}`, {
        headers: {
            authorization: `Bearer ${userToken}`
        }
    })
    expect(response.status()).toBe(204);
});
```
I am trying to run cases in order but not in serial mode because I need the order to carry on with the execution of the tests regardless of failures, whilst passing a variable between tests.
So if creating a post fails, I still need the profile to be deleted.

The happy scenario is when a test case passes it continues the execution objectively, the bad/bug scenario is:

If the 3rd case fails (create a post) then the following cases fail naturally (in this case the delete profile test).
When failure happens in the create post test, with a breakpoint  in the delete profile test I check for `userToken` and `profileId`, they are both undefined at that point.

why do variables get unset with first failure and how do I avoid this? 

Thank you

**Comment by yury-s** [comment]
Another alternative is to place "create a new profile" and "Login" into test.beforeAll. This way it will always run once in test worker even after test failures.
