### ISSUE TITLE
[BUG] Trace viewer does not work when visiting non-localhost address

### ISSUE THREAD

**Issue by davidhao3300** [microsoft/playwright#20231]
**Context:**
- Playwright Version: 1.29.2
- Operating System: MacOS, but also happens on Linux
- Node.js version: 14.20.0
- Browser: Any browser when viewing HTML report

**Describe the bug**

Run any playwright test that generates a trace file.
Run `npx playwright show-report --host 0.0.0.0`. Visiting localhost:9323 and viewing the trace works, but visiting 0.0.0.0:9323 and viewing trace does not load anything.

**Comment by yury-s** [comment]
0.0.0.0 tells a server to listen on any available IP address (127.0.0.1, 192.168.0.1 etc), it's a non-routable meta-address. When opening a page in the browser you need to specify actual destination and 0.0.0.0 cannot be routed. See also [this answer](https://stackoverflow.com/a/20778887/552185).

**Comment by davidhao3300** [comment]
I'm not very satisfied with this answer - When I visit 0.0.0.0:9323, I see the rest of the HTML report fine. Why is trace viewer specifically broken?

**Comment by davidhao3300** [comment]
Example URLs that works:
- http://localhost:9323 (viewing the report homepage)
- http://0.0.0.0:9323 (viewing the report homepage)
- `http://localhost:9323/trace/index.html?trace=http://localhost:9323/data/5fd0cd3b6b911fa0c3f11bdd01e7028533986511.zip`

These do not work:
- `http://0.0.0.0:9323/trace/index.html?trace=http://localhost:9323/data/5fd0cd3b6b911fa0c3f11bdd01e7028533986511.zip` (Blank screen)
- `http://0.0.0.0:9323/trace/index.html?trace=http://0.0.0.0:9323/data/5fd0cd3b6b911fa0c3f11bdd01e7028533986511.zip` (Blank screen)
- `http://localhost:9323/trace/index.html?trace=http://0.0.0.0:9323/data/5fd0cd3b6b911fa0c3f11bdd01e7028533986511.zip` (Error with "Could not load trace from http://0.0.0.0:9323/data/5fd0cd3b6b911fa0c3f11bdd01e7028533986511.zip. Make sure a valid Playwright Trace is accessible over this url.`

If this were a pure routing issue, why does the first dysfunctional URL not work?

Also, when running `npx playwright test` with HTML reporter enabled, the reporter is launched automatically with host=0.0.0.0, so this feels like it should be supported
