### ISSUE TITLE
[BUG] Expecting a false boolean is evaluated has true. 

### ISSUE THREAD

**Issue by mathieu-fournier** [microsoft/playwright#20230]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows
- Node.js version: 18.11.18
- Browser: Chromium

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript

export class ExampleCheckValidator{
	page: Page;

	constructor(page: Page) {
		this.page = page;
	}	

	 validateCheck = async (value: boolean) => {
		const elem = await this.page.${id);
		const isChecked = await elem.isChecked(); 
		
		console.log(`typeof ischecked === typeof value : ${typeof isChecked} ${isChecked} === ${typeof value} ${value} : ${isChecked === value}`);
		expect(isChecked).toBe(value); // <-- this one fails
	};
}
```

**Describe the bug**
I expect that two false boolean variable equals to true with the "toBe" method.
The error log tells me that "expect" received true, which is wrong. 

See image : 
The console log log tells us that we have two false boolean. 
The error tells us that expect received true, how ?
![image](https://user-images.githubusercontent.com/82905333/213532603-9051b2e7-0af2-4447-9612-cc232c4b5694.png)

Thanks

**Comment by yury-s** [comment]
You have a typo in this line `const elem = await this.page.${id);`, so maybe your code didn't recompile? Try building your project from clean state to see if there are any errors. expect(false).toBe(false); should pass.

If the issue still persists please share a repro that we can run locally.

**Comment by mathieu-fournier** [comment]
It`s an issue with async code.
Expect works normally.
Sorry for the false alarm.
