### ISSUE TITLE
[BUG] WebKit crashes on await page.goto for certain urls

### ISSUE THREAD

**Issue by marinamelin** [microsoft/playwright#20237]
**Context:**
- Playwright Version: migrating from 1.24 to 1.28. Problem was not present in 1.24 and started to be present in 1.28.
- Operating System: Windows
- Node.js version: 16.14.0
- Browser: WebKit
- Extra: Issue is reproducible in local Windows environment and in Windows Docker container 

**Bug description:**
Webkit tests stopped working after playwright version update. The error message is:

```
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://superapp.msn.com/homepagefeed", waiting until "networkidle"
============================================================
page.goto: Navigation failed because page crashed!
=========================== logs ===========================
navigating to "https://superapp.msn.com/homepagefeed", waiting until "networkidle"
============================================================
```

Public urls that we want to test and that consistently cause webkit to crash:

- https://www.msn.com
- https://superapp.msn.com/homepagefeed

**Minimal reproducible test with the problem:**

```
// @ts-check
const playwrightTest = require("@playwright/test");

playwrightTest.test('It can navigate to https://www.msn.com', async ({ page }) => {
    // await page.goto("https://www.msn.com", { waitUntil: "networkidle", timeout: 60000 });
    await page.goto("https://superapp.msn.com/homepagefeed", { waitUntil: "networkidle", timeout: 60000 });
});
```

**Additional observations:**
Changing the call to just `await page.goto("https://www.msn.com")` decreases the frequency of the crash from 'always crashes' to 'crashes in 1/3 of the test runs'

**Comment by mxschmitt** [comment]
I can repro on Windows.

**Comment by mxschmitt** [comment]
This looks like its gonna be fixed with the next Playwright release. Could you try our [canary release](https://playwright.dev/docs/canary-releases) to confirm?

**Comment by marinamelin** [comment]
Tested with canary release version "@playwright/test": "^1.31.0-alpha-jan-24-2023"
Safari tests are consistently able to run. Checked both urls with `--repeat-each=10` parameter.
Thank you!

**Comment by mxschmitt** [comment]
Closing then! Feel free to refile if it happens again.
