### ISSUE TITLE
[Feature] Nicer API to wait for multiple elements

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2023]
When I want to get some content in a span in a `<td>` element, I have to do the below. I was just wondering if there is a nicer API for this, or if not, there should be?

It is quite common to want to get multiple elements like this, but only after the selector is visible (or even better possibly using the [Auto-waiting functionality](https://github.com/microsoft/playwright/blob/master/docs/core-concepts.md#auto-waiting).

```javascript
await page.waitForSelector('#users-table tr td span');
const text = await page.$$eval('#users-table tr td span', (spans) =>
  spans.map((span) => span.textContent)
);
```

**Comment by dgozman** [comment]
Note that `waitForSelector` for multiple elements is not defined. Are we considered done waiting, when there is one element matching the selector, or three, or a hundred?

Are you after a one-liner that combines `waitForSelector` and `$$eval`, or do you have something else in mind?

**Comment by thernstig** [comment]
My reasoning is that the only way to get multiple elements is with `page.$$` as of now. Now all the `$` functions has no wait functionality, they just execute immediately. This means I anyway have to have a `waitForSelector` in this cases to wait for some kind of element to exist in the DOM (or to be visible).

I believe I was after a one-liner that combines them. But you are much more adapt at all things DOM. So maybe there is a better idea? Or it is possible the current way of doing this (like in my original post) is the best way and should not change?

I've just felt it looks a bit "ugly" and it could be nicer, but I am also not entirely sure. I am reasoning that the above must be common enough to do in tables, lists etc. of sorts.

Note that lately I've been doing this instead:

```javascript
await page.waitForSelector('#users-table tr td span');
const spans = await page.$$eval('#users-table tr td span');
const text = spans.map((span) => span.textContent());
```

**Comment by dgozman** [comment]
When you do `waitForSelector('tr td span')`, you made a decision that once a single element matching the selector appears, all of them appear at the same time. As a library, we cannot make this assumption about the page, therefore we lack the signal about "all elements matching the selector are already in the page".

Given the above, I don't see a nice API that is convenient and also intuitive. Let's think more 😄

**Comment by thernstig** [comment]
I agree, it's not easy. Maybe the decision "once this element appeared, all of them exist" is what the selector would do and then get those elements. Something like `waitForElementThenGrabTheseElements('selectorMainElement', 'subelements');`. Yeah it's ugly 😏 

I am perfectly fine in closing this if you feel there is no nice API for this, but brainstorming is always good.

**Comment by thernstig** [comment]
Or, how about something like `waitForSelector` that just has one selector, but also the amount of selector matches (elements) one wants to wait for? This should be a common scenario in e2e tests.

You have some component that can add/remove things from a list (todos, users, profiles, food items, whatever). What you then do is call the new function like `waitForElements('table tbody tr`, 5)` and it will return all elements in an array once it found all of them, or time out like normal.

This could be used e.g. if you add things to the list (possibly batch-add) or remove multiple elements.

Obviously all this could be achieved with other means, but it'd be much more verbose.

**Comment by hdorgeval** [comment]
Hi @thernstig, I am current developing a [fluent api around playwright](https://github.com/hdorgeval/playwright-fluent).  Maybe the Selector API provided by this API may help solve your case.

**Comment by thernstig** [comment]
Hi @hdorgeval - looks like a nice package! It does not suit me and I personally prefer using Playwright directly for my testing needs.

**Comment by aslushnikov** [comment]
> I was just wondering if there is a nicer API for this, or if not, there should be?

hey @thernstig! Some time have passed and we still didn't come up with a nice API to cover this, so let's stick with the snippet you use to handle this usecase for now.

**Comment by thernstig** [comment]
@aslushnikov It makes me a tiny bit sad, as I believe this is actually a very common scenario that would be nice to solve in a better way. We find this used in about 30% of our test cases where we look for lists of things (tables, grids/flexbox items etc.).

**Comment by aslushnikov** [comment]
> We find this used in about 30% of our test cases where we look for lists of things (tables, grids/flexbox items etc.).

@thernstig Let's live for some more time and see. Hopefully more use-cases will emerge, and we might be able to come up with a good API!

**Comment by amalitsky** [comment]
Want to stop by and confirm that I also have to use the same or similar solution:
```ts
 // enforcing the wait
await $host.waitForSelector(selector);

// actually fetching the list
await $host.$$(selector);
```

Mb adding `options` object as a second argument for `$$` would do? I can think of two properties as the moment:
- `timeout` (I assume by default this is zero, regardless of `defaultTimeout` value set)
- `waitForTheFirstElement`, which would be zero by default. Alternatively could call this _eager_ or _lazy_ lookup policy.

Introducing new `waitForSelectors` method rather than messing with existing `$$` seems like a viable option to me.

**Comment by khowling** [comment]
I beleive this is a similar issue. I was getting unpredictable `rows.count()` from a react app rendering a table, so added the first 2 lines to waitFor 1st row, before getting full table.   Would like a nicer way to waitFor whole table

```
 // WORKAROUND - need this otherwise rows.count is not constant, due to table loading/rendering
  const fst_rows = await page.locator('table tbody tr >> nth=0');
  await fst_rows.waitFor();

  const rows = await page.locator('table tbody tr');
  const count = await rows.count()
```
