### ISSUE TITLE
[Question] How to show import resolution stack?

### ISSUE THREAD

**Issue by davidAtInleague** [microsoft/playwright#20239]
I have made some changes to a project which causes playwright to be unable to run tests, due to importing a dependency that can not be run in node.

I run playwright with `npx playwright test someFolder/`, the error is: 
```
ReferenceError: document is not defined

   at ../src/modules/izitoast.ts:2

  1 | import { boot } from 'quasar/wrappers'
> 2 | import iziToast from 'izitoast'
    | ^
  3 | import 'izitoast/dist/css/iziToast.min.css'
  4 | import {IziToastPosition} from 'izitoast/types/index'
  5 |

    at /home/david/dev-environment/quasar/node_modules/izitoast/dist/js/iziToast.js:23:10
    at /home/david/dev-environment/quasar/node_modules/izitoast/dist/js/iziToast.js:10:20
    at Object.<anonymous> (/home/david/dev-environment/quasar/node_modules/izitoast/dist/js/iziToast.js:14:3)
    at Object.<anonymous> (/home/david/dev-environment/quasar/src/modules/izitoast.ts:2:1)

```

This error is almost helpful, but it doesn't seem to go "all the way", to telling me why the `izitoast` module was imported. Is there a way to convince playwright to output the full chain of files that led to this undesired import?

**Comment by yury-s** [comment]
This looks like a bug if the stack trace is trimmed. Can you share the project where it happens?

**Comment by yury-s** [comment]
Also there was a relevant [fix](https://github.com/microsoft/playwright/issues/18330) a few revisions ago, it might be that it helps with this issue, so make sure you are on the latest playwright version.

**Comment by davidAtInleague** [comment]
Hm, still seems like a thing on 1.29.2. I was able to get a tiny repro at [playwright-20239-repro](https://github.com/davidAtInleague/playwright-20239-repro)

**Comment by yury-s** [comment]
Thank you very much for the repro, it's really helpful! We'll have a look at it.
