### ISSUE TITLE
Playwright extension not "seeing" my playwright tests in my project

### ISSUE THREAD

**Issue by alilland** [microsoft/playwright#20234]
any tips for debugging why the extension may not be able to see my playwright tests?
i suspect its because i'm not using a conventional playwright config file name due to me wanting a seperate config file for dev and prod

example folder structure:

```
/<project root>
    /applications
      /<second app>
          / ...
      /<main app>
        /playwright.common.js
        /playwright.dev.js
        /playwright.prod.js
        / ...
        /src
        /tests
            /playwright
                // <playwright tests>
```

typically I run playwright with `NODE_ENV=development npx playwright test --trace on --config=playwright.dev.js`

**Comment by mxschmitt** [comment]
We only filter for [`'**/*playwright*.config.{ts,js,mjs}'`](https://github.com/microsoft/playwright-vscode/blob/03373fa6152dab7535b6c62d105d73b3ecaf1713/src/extension.ts#L221) in our VSCode extension, so renaming your config files to e.g. `common.playwright.js` should make it work.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by alilland** [comment]
so i went ahead and changed the dev config that loads from "common" to `playwright.dev.config.js` and now it seems to be found by the beaker glass portion of the plugin. but the green play button next to tests does not work
