### ISSUE TITLE
[Question] Pause all workers to do single-threaded work and then resume?

### ISSUE THREAD

**Issue by davidAtInleague** [microsoft/playwright#20240]
I'm using playwright to integration test an existing app, and currently the way we go about "testing the untestable" is to absolutely pollute the backend database and caches. This works quite well until the backend becomes bloated and slow and things start timing out. I have wondered if there is a way to insert "join points" (??), where all workers come to rest, and once settled, some synchronous single threaded work can be done (in particular reset db/caches), and then carry on with the remaining tests?

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/14084
