### ISSUE TITLE
[Question] Issue with selecting text on the DOM

### ISSUE THREAD

**Issue by leovarmak** [microsoft/playwright#2024]
As you can see in the below snippet, I am trying to find the text `Success.` in the DOM, but asserting it always returns me an error.

```
let assert = require("assert");
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({ headless: false });
  const browserContext = await browser.newContext();
  const browserPage = await browserContext.newPage();

  await createAccount(browserPage);
})();

const createAccount = async (page) => {
  await page.goto("https://coindcx.com/signup");
  await page.fill('input[name="firstName"]', "Test");
  await page.fill('input[name="lastName"]', "test");
  await page.fill('input[name="email"]', "test@test.com");
  await page.fill('input[name="password"]', "Qwerty@123");
  await page.fill('input[placeholder="Select Country"]', "India");
  await page.click('span[class="country__name -o-6"]');
  await page.fill(
    'input[name="phone"]',
    Math.floor(1000000000 + Math.random() * 900000).toString()
  );
  await page.click('button[type="submit"]');
  assert(await page.$(`text="Success"`));
};
```

Any tips would be really helpful

**Comment by thernstig** [comment]
@leovarmak If you use `text="Success"` it needs to be an exact match (no white space before/after, case insensitive etc.), please check https://github.com/microsoft/playwright/blob/master/docs/selectors.md

Are you sure the word Success is an exact match? Can you try like this instead: `text=Success`?

I also don't think `page.$` actually waits for the element to be visible. So if you change `page.$()` to `page.waitForSelector()` does it work?
