### ISSUE TITLE
[Question]chromium doesn't show up?

### ISSUE THREAD

**Issue by arthurchan1906** [microsoft/playwright#20242]
If I run the code directly, the chromium window shows up.
Then I want to run a scheduled task, I place the cmd in the .bat file like 
```
@python a.py
@pause
```
everything runs ok. And then I create a windows service with ```nssm```.
Actually the playwright browser runs planned and everything goes fine except the window doesn't show up.
But I need to see the window.

**Comment by yury-s** [comment]
I assume you run in headed mode in both cases and don't change command line arguments passed to playwright. When you run a script as a windows service using nssm, the script runs in the background without a user interface. This is probably why the chromium window is not showing up. You need to research if it's possible to configure the service to run in foreground with user UI.  Why don't you run it in headless mode if it's a service?

**Comment by arthurchan1906** [comment]
i wanna do some website crawling with playwright. for some pages, sometimes, the browser need to wait for some elements to load. If the code run directly, no errors and no missing pages. If run with windows service, some pages will be missing because these pages didn't load properly

**Comment by yury-s** [comment]
This doesn't sound like a playwright bug more like a configuration issue related to the service environment. I'm going to close this report as there is no bug in playwright we can take an action on. If deem it's a playwright issue please file a new bug with a reproducible example that we can run locally.

**Comment by arthurchan1906** [comment]
ok, thanks
