### ISSUE TITLE
[Question] How to send this POST multipart/form-data request involving an example file and dto?

### ISSUE THREAD

**Issue by iamlevik** [microsoft/playwright#20249]
Recently moved our entire Automation suite from Selenium/Java to Playwright/Typescript. It was our best decision yet, which I wholeheartedly recommend to anyone to try. 

This change though, came with new language barriers(java->ts)  for which we might have an issue in understanding. 

here's an example dto.
`{
  "file": "string",
  "dto": {
    "lat": 0,
    "lng": 0,
    }
}`

This request in Postman looks the following, which works here.
![image](https://user-images.githubusercontent.com/48520797/213666470-44e620d1-116d-47be-a314-3f46a1edad02.png)

This is my current "implementation" 

```
const fs = require('fs');
 const stream = fs.createReadStream('utils/signature.jpeg');
   
   const skipCheckin =  await request.patch(`${ENV.API_DAI_BASE_URL}/api/delivery/orders/DRCLLVUWNGG0NO/status`,{
        headers:{
            'accept': '*/*',
            'content-type': 'multipart/form-data',
            'x-api-key': apikey,
            'authorization': 'Bearer example'
        },
        multipart:{
            File: stream
            dto:{
                lat: 0,
                lng: 0,
            }
             
        },

       
    })

    console.log(skipCheckin)
    expect(skipCheckin.status()).toBe(200)
```

It does not like the code above, what am I doing wrong in structuring this? 
Can anyone help me formatting it in order to understand it? 

Thanks in advance.

**Comment by iamlevik** [comment]
ENV it's a class where I store everything.
```
export default class ENV{
    public static API_DAI_BASE_URL = process.env.API_DAI_BASE_URL
}
```

 That's not the issue here, as I have 20 other endpoints running correctly.

**Comment by iamlevik** [comment]
@yury-s Could you give a look at my question whenever you have time? Thanks in advance.

**Comment by yury-s** [comment]
> It does not like the code above, what am I doing wrong in structuring this?

Can you elaborate on what "It does not like the code" means?

There are two problems in the code that I see:

1) The multipart parameter is missing ',' which will fail to parse in runtime:

<img width="502" alt="image" src="https://user-images.githubusercontent.com/9798949/213806041-3125d276-18fc-4268-b336-6160922c06ac.png">

2) Type of the multipart field value cannot be a random object, so if you want to pass a json object you have to manually serialize it to string:

```ts
        multipart:{
            File: stream,
            dto: JSON.stringify({
                lat: 0,
                lng: 0,
            })
        },
```

VS Code type checker / typescript compiler should catch both of these problems.

**Comment by iamlevik** [comment]
Thanks @yury-s for the quick reply. I've tried the code above
   ```
 const fs = require('fs');
    const stream = fs.createReadStream('utils/signature.jpeg');
    const skipCheckin =  await request.patch(`${ENV.API_DAI_BASE_URL}/api/delivery/orders/DRCRRFM6ZP205R/status`,{
        headers:{
            'accept': '*/*',
            'content-type': 'multipart/form-data;',
            'x-api-key': apikey,
            'authorization': 'Bearer '+ courierToken
        },
        multipart:{
            File: stream,
            dto: JSON.stringify({
                lat: 0,
                lng: 0,
            })
             
        },

       
    })
```

If I run this we get this error in our logs `Failed to parse multipart servlet request; nested exception is java.io.IOException: org.apache.tomcat.util.http.fileupload.FileUploadException: the request was rejected because no multipart boundary was found] with root cause`

What else I've noticed that in our successful Postman request in the header I have this
![image](https://user-images.githubusercontent.com/48520797/213861251-1e8fe39c-8fad-47f3-a549-5a20377b6caa.png)

Is `multipart/form-data; boundary=<calculated when request is sent>` boundary something that needs to be sent as well?

**Comment by iamlevik** [comment]
Ok so I've managed to get it working. Firstly the 
> Is `multipart/form-data; boundary=<calculated when request is sent>` boundary something that needs to be sent as well?

As long as no content-type is mentioned, I've seen that the boundary is sent automatically.

The fix for our code was the following:
```
let signature = fs.createReadStream('utils/example.png');
    let coordinates = {lat: 46.2342, lng: 23.4324}
    
    const skipCheckin =  await request.patch(`${ENV.API_DAI_BASE_URL}/api/delivery/orders/`+deliveryAWB+`/status`,{
        headers:{
            'accept': '*/*',
            'x-api-key': apikey,
            'authorization': 'Bearer ' + courierToken
        },
        multipart: {
            file: signature,
            dto: {
                name: "blob",
                mimeType: "application/json",
                buffer: Buffer.from(JSON.stringify(coordinates))
            }
    }})

    console.log(skipCheckin)
    expect(skipCheckin.status()).toBe(200)
```
Thank you @yury-s for the support!

**Comment by deepak-80** [comment]
I'm new to playwright, I was trying to attach two image files and one json file, this approach its not working. Can you please provide solution

multipart: {            
                        inputReceiptFiles:  fs.createReadStream(Imagefilepath1),
			inputReceiptFiles:  fs.createReadStream(Imagefilepath2),
			uploadDocumentInput: {
                        name: "Jsonfile",
                        mimeType: "application/json",
                        buffer: Buffer.from(JSON.stringify(fsPromise.readFile(jsonFilepath, "utf8")))
            }           
        }

**Comment by maximkoev** [comment]
Hello @iamlevik, I have the issue.
I have payload {file: "src/some.txt", path: "upload"}
Server returned issue that parameter path is missing for case
multipart: {
buffer: fileBuffer
mimeType: 'plain/text'
name: fileName
}

here is my solution

npm intall form-data

import FormData from 'form-data'



 const file = path.resolve(filePath);
 const fileBuffer = fs.readFileSync(file);

    const formData = new FormData();
    formData.append('path', path);
    formData.append('file', fileBuffer, file);
const headers = {
      ...formData.getHeaders(),
      accept: 'application/json',
      Authorization: token,
    };


await this.context.fetch(uri, {
      method: 'POST',
      data: formData.getBuffer(),
      headers: headers,
    });


While investigation I figured out that follow if statement is always false


if (globalThis.FormData && options.multipart instanceof FormData) {
          const form = options.multipart;
          for (const [name, value] of form.entries()) {
            if ((0, _utils.isString)(value)) {
              multipartData.push({
                name,
                value
              });
            } else {
              const file = {
                name: value.name,
                mimeType: value.type,
                buffer: Buffer.from(await value.arrayBuffer())
              };
              multipartData.push({
                name,
                file
              });
            }
          }
        }
