### ISSUE TITLE
[Question] How to take heap snapshot

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#20246]
I am trying to do some memory profiling using playwright and chromium CDP.
The issue I am facing is that the profile is always returning an empty object.
This is what I tried
```typescript
test.only("heap snapshot", async ({ page }) => {
        const client = await page.context().newCDPSession(page);
        await page.goto("https://www.dynatrace.com/");
        await client.send("HeapProfiler.enable");
        await page.waitForTimeout(1000);
        const profile = await client.send("HeapProfiler.takeHeapSnapshot");
        console.log(profile);
    });
```
Am I maybe missing some steps?

**Comment by yury-s** [comment]
The snapshot is sent as a series of [`HeapProfiler.addHeapSnapshotChunk`](https://vanilla.aslushnikov.com/?HeapProfiler.addHeapSnapshotChunk) events between 'HeapProfiler.takeHeapSnapshot' message and its response:
```
  client.addListener('HeapProfiler.addHeapSnapshotChunk', payload => {
    console.log('chunk');
  })
  const profile = await client.send("HeapProfiler.takeHeapSnapshot");
```
