### ISSUE TITLE
[Question]does playwright provide any api I can use to show whether each expression succeeds

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#20243]
I am using cucumber js with playwright  like https://github.com/Tallyb/cucumber-playwright

I use cucumber js test runner and cucumber report
![cucumberreport](https://user-images.githubusercontent.com/20555274/213622337-6d147617-aba3-4717-9407-f84019fefa26.JPG)

in the picture ,cucumber report does not show whether each expression (such as page.goto, locator.click expression) in test run succeeds like playwright report

does playwright have any api that I can use to make cucumber report show whether each expression in test run is executed successfully or not

**Comment by yury-s** [comment]
You can implement your own report using Playwright [reporter API](https://playwright.dev/docs/test-reporters#custom-reporters) and listen for all the test results. Since this is cucumber specific, please file this issue in  https://github.com/Tallyb/cucumber-playwright.

**Comment by bodycombathuang** [comment]
hi,@yury-s , but you ever said playwright reporter cannot be used outside playwright test runner.
