### ISSUE TITLE
[BUG] dragTo / mouse actions not working in our application

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#20254]
**Context:**
- Playwright Version: 1.29
- Operating System: Windows
- Browser: Chromium (only tested on this)

**Manual demonstration of how it works**
[https://giphy.com/gifs/pgmGBZ8hRXWcGoTU5t](https://giphy.com/gifs/pgmGBZ8hRXWcGoTU5t)

**Using the dragTo method on a locator**
You can see the release click on the target element, but the element isn't dragged.
Note the API call is done after the mouse up, so that is registered properly.
(see debug clicks: [https://giphy.com/gifs/gW0jZv50Z3wuUJLEjA](https://giphy.com/gifs/gW0jZv50Z3wuUJLEjA))

```javascript
const [request] = await Promise.all([
    this.page.waitForRequest(r => r.method() === 'PUT'), 
    originElement.dragTo(targetElement, {force: true})
]);
```
**Using manual mouse actions**
You can see the source/release click on the elements, but the element isn't dragged.
Note the API call is done after the mouse up, so that is registered properly.
(see debug clicks: [https://giphy.com/gifs/EDAadRKyCQ5UgiE8Ot](https://giphy.com/gifs/EDAadRKyCQ5UgiE8Ot))

```javascript
    await originElement.hover();
    await this.page.mouse.down();
    await targetElement.hover(); // mouse.move acts weird, not usable at all
    const [request] = await Promise.all([this.page.waitForRequest(r => r.method() === 'PUT'), this.page.mouse.up()]);
```

**Comment by yury-s** [comment]
Why do you have to pass `force: true` into dragTo? Can you also describe what exactly is not working when you perform the action with playwright vs manually? Please share a repro which we can run locally, without seeing the code we cannot tell whether it's a problem in your code, racy behavior of the application or a bug in playwright.

**Comment by Exoow** [comment]
- `force: true` doesn't matter, it was just another attempt 
- what is not working you can see in the GIF files: the item never actually moves when Playwright drags... consequence: the API request on mouse release sends the original hours because the drag did not happen (instead of the new hours the item is dragged to, which works perfecty if done by hand).
- sharing code is unfortunately not possible, but the entire visualisation is drawn with `svg`.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue if you can reduce the test case to a reproducible example that you can share and link it to this one.

**Comment by Exoow** [comment]
Fun fact: I got it working with explicit mouse actions, using `mouse.move` **and** by adding `{steps: 5}` as parameter.
Without the steps it's not working. Could we have this option in the `dragTo ` method as well?

**Comment by tommymcphillips** [comment]
> Fun fact: I got it working with explicit mouse actions, using `mouse.move` **and** by adding `{steps: 5}` as parameter. Without the steps it's not working. Could we have this option in the `dragTo ` method as well?

thanks you @Exoow

**Comment by ianNoahs** [comment]
Hey @Exoow

I am facing the same issue not able to drag and drop . can you please elaborate little bit more what you have done here to solve this issue.

**Comment by Exoow** [comment]
Sure, this is how I did it for our application (simplified method by removing irrelevant statements)

```
public async drag(
    vpItem: VisualPlanningItem,
    targetItem: VisualPlanningItem,
  ) {
    const originElement = this.svgPlanningItems.filter({hasText: vpItem.displayName});
    const targetElement = this.svgPlanningItems.filter({hasText: targetItem.displayName});

    const box = (await targetElement.boundingBox())!;
    await originElement.hover();

    await this.page.waitForTimeout(100);
    await this.page.mouse.down();
    await this.page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, {steps: 5});
    await this.page.waitForTimeout(100);
    await this.page.mouse.up();
  }
```

**Comment by nicholascm** [comment]
One thing I noticed with the above solution - if you have a drag/drop item extending below the viewport, scrolling down to the bottom first was necessary to get the appropriate coordinates.

**Comment by Nadunilam123** [comment]
Hi All,
What if the target locater is hidden by defualt . it only gets visible at mouse hover event.. this makes some drag and drops missed .. Please advice 
thank you

**Comment by kancalvin** [comment]
> We also have issues with `dragTo` not working in our app. The above solution works for us though. One thing I noticed with the above solution - if you have a drag/drop item extending below the viewport, scrolling down to the bottom first was necessary to get the appropriate coordinates.
> 
> This utility working as a replacement. for `dragTo` for now:
> 
> ```ts
> const drag = async (page: Page, draggable: Locator, droppable: Locator) => {
>   const box = (await droppable.boundingBox())!;
>   await draggable.hover();
> 
>   await page.mouse.down();
>   await page.mouse.move(box.x + box.width / 2, box.y + box.height / 2, {
>     steps: 5,
>   });
>   await page.mouse.up();
> };
> ```

this works like a charm, thanks.

**Comment by bohoril** [comment]
Why this issue is closed and I assume it is not supposed to be fixed in the Playwright? Seems to be a very common issue.

**Comment by nicholascm** [comment]
> Why this issue is closed and I assume it is not supposed to be fixed in the Playwright? Seems to be a very common issue.

Looks like they closed it because none of us provided a reproducible test case.
