### ISSUE TITLE
Test case to select an option from kendo-dropdownlist

### ISSUE THREAD

**Issue by shalini-raghu** [microsoft/playwright#20256]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows
- Node.js version: v16.14.0
- Browser: All
- Extra: using Kendo-dropdown-list for dropdown

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { test, expect } from '@playwright/test';
 await page.click("//kendo-card-header/div/button[1]");
 await page.fill("//input[@formControlname='tagSourceName']","test tag 1");
 await page.locator("//kendo-dropdownlist[@formControlname='tagSourceType']").selectOption('1');
```

**Describe the bug**
When i run this test case I'm getting following error.

```
 locator.selectOption: Error: Element is not a <select> element
    =========================== logs ===========================
    waiting for locator('xpath=//kendo-dropdownlist[@formControlname=\'tagSourceType\']')
      locator resolved to visible <kendo-dropdownlist dir="ltr" required="" tabindex="0" role="listbox…>…</kendo-dropdownlist>
      selecting specified option(s)
      Element is not a <select> element
    ============================================================
```

Please help me out to resolve this issue.

Thanks,

**Comment by yury-s** [comment]
This error message is indicating that the element located by the xpath "//kendo-dropdownlist[@formControlname='tagSourceType']" is not a `<select>` element. The selectOption method is designed to work with `<select>` elements, and is therefore not able to interact with this element (it's likely a div). Try using codegen to pick a better selector and interact with the dropdown. You will likely need to do 2 clicks: one to expand the drop down and the second one to click an option.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
