### ISSUE TITLE
globalSetup is not working in CI/CD Azure pipeline.

### ISSUE THREAD

**Issue by nudratuppal** [microsoft/playwright#20252]
Hi, I am completely new to playwright and Azure pipeline combination.

I am using globalsetup to store logged-in states. It works perfectly fine locally but when I try to run same code in Azure pipeline it is skipping the globalsetup execution and jumps directly to fixture and test execution. But I need those state JSON files to create browser contexts in my fixtures. I tried adding console logs to see if there is something wrong while accessing the web page in browser. but it didn't print anything either.  
```
async function globalSetup() {
    const usersRolesInfo = {
        "requester" : "Smith, B (Bob)",
        "admin": "Smith, A (Alex)"
    };
    for (const [role, user] of Object.entries(usersRolesInfo)) {
        console.log("Going to save context for: "+role);
        const browser = await chromium.launch({ "headless": false });
        const context = await browser.newContext({ ignoreHTTPSErrors: true });
        const state_file_path = "storage-states/"+role+"-user-state.json";
        await saveStorage(context, user, state_file_path);
        await browser.close();
    }
}
export default globalSetup;
```
Playwright config file looks something like this 
```
const config: PlaywrightTestConfig = {
  globalSetup: './global-setup',
  testDir: './tests/',

  
```
I don't understand if I am missing something here.

**Comment by yury-s** [comment]
> I tried adding console logs to see if there is something wrong while accessing the web page in browser. but it didn't print anything either.

If `console.log` from `globalSetup` doesn't appear in the test output it means that globalSetup is not executed at all. My hunch is that you are running with a different config on Azire pipeline, most likely with a default config which doesn't have global setup configured. Can you shared your azure pipeline configuration along with the project files (config and global setup) structure?

**Comment by nudratuppal** [comment]
Thanks for your help. Your hunch was correct. `playwright.config.ts` was getting overwritten with new playwright installation. I pushed the config file with some other name and used the `--config` parameter in command line. `npx playwright test --config=./playwright_vr.config.ts`. And now its executing globalsetup function.
