### ISSUE TITLE
[Question] Allure report error - npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#20257]
I am trying to generate `allure-report` locally using ` npx allure generate ./allure-results --clean` but seeing this error `npm ERR! could not determine executable to run`

Has anyone seen this error before?

**Comment by ltsuda** [comment]
This is related to https://github.com/allure-framework/allure-js/blob/master/packages/allure-playwright/README.md, not Playwright itself, I think.

The allure-report is just an "extension" to report playwright test results, you need to install the Allure CLI to be able to run `npx allure generate ./allure-results --clean`

**Comment by gauravgandhi1315** [comment]
@ltsuda I did but still seeing the same issue

**Comment by ltsuda** [comment]
I'm sorry, I copy/pasted you command.

The correct command is from the allure CLI, not npm.

`allure generate ./allure-results --clean`

https://github.com/allure-framework/allure-js/pull/297/files#diff-e0bdf09adaa5da6c630463aa229cfa670a5d39acbb57c07e63c35e1a5931fd02R21

**Comment by gauravgandhi1315** [comment]
fixed the issue. closing this
