### ISSUE TITLE
[BUG] Trace viewer TypeError on Firefox

### ISSUE THREAD

**Issue by davidnuzik** [microsoft/playwright#20259]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac (M1)
- Node.js version: v19.4.0
- Browser: Firefox (latest as of issue created date, v109.0)
- Extra: Possibly related: https://github.com/microsoft/playwright/issues/2451

**envinfo output**

> ## System:
>  - OS: macOS 13.1
>  - Memory: 29.52 MB / 16.00 GB
> ## Binaries:
>  - Node: 19.4.0 - /opt/homebrew/bin/node
>  - npm: 9.2.0 - /opt/homebrew/bin/npm
> ## Languages:
>  - Bash: 3.2.57 - /bin/bash

**Code Snippet**
(Not applicable)

**Describe the bug**
I noticed recently after upgrading to 1.29.2 that when I attempt to view traces in Firefox on Mac there is an error in the browser dev console like as follows. If I use Chrome, then the trace viewer renders without any issues. Please forgive me, I do not recall the version I was updating from but it wasn't that old. Probably 1.28.x

![image](https://user-images.githubusercontent.com/45179589/213764841-6dd6f156-ef50-4554-97ba-47e5c2cf4249.png)

And here is text of the above message:
```
Uncaught (in promise) TypeError: navigator.serviceWorker is undefined
    <anonymous> http://localhost:9323/trace/index.74859fca.js:66
    <anonymous> http://localhost:9323/trace/index.74859fca.js:66
index.74859fca.js:66:58445
```

Thank you for your time and consideration of this issue.

**Comment by mxschmitt** [comment]
I can't repro with Firefox 109 on Windows.

Do you open the Trace with `npx playwright show-report` and then you click on a test's trace file?

**Comment by davidnuzik** [comment]
Yes, I ran `npx playwright show-report` and then clicked on a test's trace file. Upon doing this the viewer for traces runs into this error and won't render the page as expected.

Interesting that you cannot reproduce on Windows; not impossible that the issue is environmental on my end. I unfortunately do not have another box to test with.

**Comment by mxschmitt** [comment]
Is your machine managed with some enterprise policies or intune'd?

**Comment by davidnuzik** [comment]
Yes, it is (with Rippling).
You are thinking it's plausible it could be the cause? If so I can reach out and see what they think. They probably have logs for anything that could be blocked, etc. I think it unlikely but not impossible.

**Comment by dgozman** [comment]
I can repro with `npx playwright show-trace --browser=firefox trace.zip`.

**Comment by aslushnikov** [comment]
@dgozman I failed to repro on either Playwright 1.29.2, 1.30.0 or canary. How do you repro this?

**Comment by m-aouainia** [comment]
For me is reproducible with playwight version 9.3.1 node v18.14.0

**Comment by mpspahr** [comment]
I'm able to produce this error when defining a host other than 127.0.0.1/localhost to serve the report.

`npx playwright show-report --host=<IP/Hostname>`

Replace `<IP/Hostname>` with your alternative host.

I see the problem in Chrome, Firefox, and Safari back to v1.27 when the `host` and `port` options were first added to the html reporter.
