### ISSUE TITLE
[Feature] Support mediaSession

### ISSUE THREAD

**Issue by Visual-Dawg** [microsoft/playwright#20263]
I want to test [mediaSession](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession) handlers and the displayed metadata.

Currently I cannot find anything about it in the docs. 

This would be a really nice feature for sites which play back media.

**Comment by yury-s** [comment]
We usually don't expose specific playwright APIs for non user-visible features. You can use things like [`page.evaluate`](https://playwright.dev/docs/api/class-page#page-evaluate) and [`page.exposeBinding`](https://playwright.dev/docs/api/class-browsercontext#browser-context-expose-binding) to interact with the media session in the page via javascript calls. See also [our doc](https://playwright.dev/docs/mock-browser-apis) about mocking browser APIs.

Closing this request is there are no plans to add such specific API to Playwright.

**Comment by Visual-Dawg** [comment]
Mocking the handlers doesn't work as they cannot get triggered.
I created another issue #20277  for that.
