### ISSUE TITLE
[Question] Can I launch browser with remote-debugging-port?

### ISSUE THREAD

**Issue by kot-shrodingera** [microsoft/playwright#20261]
By default `playwright` launches chrome with `--remote-debugging-pipe`. Can I change it so that it is launched with `--remote-debugging-port` option instead? I use `chromium.launchPersistentContext()`

**Comment by yury-s** [comment]
You can pass `--remote-debugging-pipe` as option to the launch:

```js
  const browserServer = await browserType.launch({
    args: ['--remote-debugging-port=' + port]
  });
```
this will open the port on the browser, but playwright will keep using pipe to control the browser.

You can also consider using [launchServer](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-server).

**Comment by kot-shrodingera** [comment]
But what if I whant disable pipe? And with `launchServer()` I can't to use persistent context
