### ISSUE TITLE
[BUG] page.waitForSelector() and waitFor: 'attached' not working properly

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2026]
**Context:**
- Playwright Version: 0.15.0
- Operating System: Ubuntu 18.04.4
- Node version: v12.15.0
- Browser: Chromium

**Code Snippet**

```javascript
// always works
await page.waitForSelector('lib-table-widget v0-icon', {
  waitFor: 'visible',
});
```

```javascript
// never works
await page.waitForSelector('lib-table-widget v0-icon');
```

Here is the JSPath to the selector:
```javascript
document.querySelector("body > container").shadowRoot.querySelector("#container > container-layout-holder").shadowRoot.querySelector("#LayoutHolder-app-content > app-content").shadowRoot.querySelector("#AppContent-inner > alarm-viewer").shadowRoot.querySelector("div > lib-dashboard").shadowRoot.querySelector("div > lib-tablwidget > div:nth-child(2) > lib-table").shadowRoot.querySelector("div:nth-child(3) > internal-extended-table").shadowRoot.querySelector("div > table > tbody > tr > td:nth-child(2) > span > span > v0-icon")
```

**Describe the bug**

I have no idea, but lately I've been noticing a lot of flakiness with `waitForSelector()` with its default for `waitFor`. As in the above case, as the default is `waitFor: 'attached'`, attached surely needs to happen for `visible` to occur. Still the default does not work. It times out waiting for the element.

**Comment by dgozman** [comment]
Looking at the code, there is a difference: `attached` defaults to "poll on mutations", while `visible` defaults to "poll on rafs". I'll look into fixing this.
