### ISSUE TITLE
[BUG] Execution time reported in extension not correct when tests run in parallel

### ISSUE THREAD

**Issue by miguelvalmeida** [microsoft/playwright#20276]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.13.2
- Visual Studio Code version: 1.74.3
- Playwright for VSCode extension version: 1.0.3
- Browser: Chromium

**Describe the bug**

The test execution time reported in the playwright extension in vscode does not seem to take into account when tests run in parallel which can be a bit misleading. Right now it seems to be the sum of the time of all individual test files. Is this expected?

Screenshot below shows that it took 56.7 seconds but it actually took ~20 seconds.

<img width="351" alt="Screenshot 2023-01-21 at 16 05 09" src="https://user-images.githubusercontent.com/24569372/213876132-e3d9e87d-d6ff-4358-b97a-a180defabfc6.png">

**Comment by pavelfeldman** [comment]
Merging into https://github.com/microsoft/vscode/issues/172008
