### ISSUE TITLE
[Feature] Distribute html-reporter's ReportView React component on NPM

### ISSUE THREAD

**Issue by samhuk** [microsoft/playwright#20274]
### The Issue
The html-reporter is currently designed to support only one use case: opening up a browser page that shows your Playwright test results. This means that it is (almost) impossible for a user to display Playwright test results in a browser any other way, for example in a different app, without using iframes etc.

html-reporter's package.json tells us that it is definitely not meant to be distributed:

![image](https://user-images.githubusercontent.com/10605534/213868645-f0487551-6aa8-4ec7-955e-510004ad3461.png)

### Background Information
For a good amount of background information about how the html-reporter works and what is missing, I reverse-engineered the whole thing for showing Playwright test results in [Exhibitor](https://github.com/samhuk/exhibitor), and talk about it [here](https://twitter.com/thesamhuk/status/1616772742577102848). Roughly how that looks:

![image](https://user-images.githubusercontent.com/10605534/213868658-2312a918-7100-4ff8-9ed0-677250731f24.png)

### Solution
html-reporter should do two things:
1. Through config, allow the user to access the zip-compressed base64-encoded html report string (types for that defined [here](https://github.com/microsoft/playwright/blob/main/packages/html-reporter/src/types.ts#L35) and where it's embedded in the monolithic index.html file as a global variable [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/reporters/html.ts#L111)).
2. Publish it's `ReportView` React component to NPM for reuse.

This would allow anyone to serve the zip-compressed base64-encoded html report string to any client and use the supposed `ReportView` NPM package to display it. I would suggest something like `@playwright/html-reporter-view`, or something similar?

### Potential Roadblocks
* `ReportView` does some global things such as setting `<html>` and `<body>` styles, but nothing too major. This would have to be turn-off-able.
* Licensing?

#### Fork whole repo

One workaround I could do *now* is forking this whole repository and making the necessary changes, publishing `ReportView` to NPM with some non-playwright-related name whilst retaining license and copyright info, however I'm just not knowledgeable enough about the law to properly do that lawfully. It's too risky. There's concerns about fragmentation too. So this workaround is a no-go.

#### Local copy of `ReportView` React component, search through report html file.

Another workaround (that I have successfully done and explained [here](https://twitter.com/thesamhuk/status/1616772742577102848)) is searching through the produced monolithic report html file, extracting the report data, sending to an arbitrary client, and using local copy of the `ReportView` code to render it. This has lots of problems, at the least the inevitability of it becoming incompatible when changes to how the html report data is created causes it to be incompatible with said local copy of the `ReportView` code.

**Comment by pavelfeldman** [comment]
Could you explain what your use case is? It seems like you are building your own app and are embedding the HTML report. This use case falls outside of the scope of the Playwright project.

**Comment by samhuk** [comment]
@pavelfeldman Sure. FYI I have updated the issue text (at the top) to include the use case. Essentially, the use case is to display Playwright test results in third-party apps without dodgy workarounds.

> It seems like you are building your own app and are embedding the HTML report.

Indeed.

> This use case falls outside of the scope of the Playwright project.

Could you explain why displaying Playwright test results in third-party apps is out of scope? Respectfully, that seems a bit strange.

**Comment by pavelfeldman** [comment]
We prioritize features that help Playwright Test customers that use it as a testing framework. Publishing html reporter as a standalone component adds maintenance burden and does not make a significant percentage of our customers happy, hence the out of scope disposition. You can always copy the code into an external repository and maintain a standalone mirror, hence taking up on this maintenance burden.

**Comment by samhuk** [comment]
> Publishing html reporter as a standalone component adds maintenance burden

I appreciate where you are coming, however I'm not too sure what the maintenance overhead of distributing `ReportView` on NPM would be (I'm not suggesting there is or is not, genuinely curious). I can think of the additional code for bundling and package.json changes, etc., but what else? After all, it's a relatively self-contained React component with a few code quality issues (i.e. styling etc.) which are relatively easy to address, as I found out when integrating it into my app.

Regardless, at the minimum, do you think that there should be an option (env var + config?) to spit out the report data to a separate file. It would be ~10 LoC at `html.ts:300`, a tiny mention in docs and ~0 maintenance burden.

> You can always copy the code into an external repository and maintain a standalone mirror

Couple thoughts:
* The Apache v2 license would make that territory a bit unfamiliar to me. I'm not sure to what extent I would have to maintain Microsoft's licensing notices, what notices I need to add, etc.
* In my view, copy-pasting a React component from a repository to dist it on NPM because original repository won't is not the right solution here. It's just creating a gradually fragmenting, frustating, and wasteful situation where there is two `ReportView`s

Lastly, I would be willing to take it up myself to do it *right* - get `ReportView` into a better state code quality-wide and better prepare it for being a reusable, consumable component. Thoughts?

**Comment by pavelfeldman** [comment]
I can only repeat myself here: it seems like you are building your own app that is embedding the HTML report. This use case falls outside of the scope of the Playwright project.

**Comment by samhuk** [comment]
Understood. Thanks for taking the time to consider the change. Have a good day 👍

**Comment by samhuk** [comment]
FYI for any who are coming to this issue looking to access the HTML Reporter's data, I have created an NPM package to make that data accessible [here](https://www.npmjs.com/package/playwright-html-data-reporter).

I may work on making an open version of HTML Reporter's React component used to render that data in the future, if time permits.
