### ISSUE TITLE
[Feature] Usage of envinfo to supply information in bug reports

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2027]
Currently the bug report template requires these fields:

```sh
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: [e.g. Windows, Linux or Mac]
- Node version: [e.g. 10.12, 10.14]
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]
```

If you start using https://github.com/tabrindle/envinfo you can get more detailed information, especially if you push a preset to the to the repo to this file https://github.com/tabrindle/envinfo/blob/master/src/presets.js. It can then be executed like:

```sh
npx envinfo --preset playwright
```

And you can just ask users to execute that in their environment and copy&paste the results. It would also make Playwright more official being seen as a preset there 😃 Just an idea - perfectly fine to close if you do not want this.

**Comment by mxschmitt** [comment]
What would be useful in your mind?

A output like would result:

```txt
 System:
    OS: macOS Mojave 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 2.97 GB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
    Yarn: 1.15.2 - ~/.yarn/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v8.16.0/bin/npm
  Languages:
    Bash: 4.4.23 - /usr/local/bin/bash
  npmPackages:
    playwright-core: ^0.16.0 => 0.16.0
    jest: ^22.2.1 => 22.2.1
```

If we use this configuration.

```js
{
    System: ['OS', 'CPU', 'Memory', 'Container', 'Shell'],
    Binaries: ['Node', 'Yarn', 'npm'],
    Languages: [
      'Bash',
    ],
    npmPackages: ['playwirght-core'],
  }
```

Some questions:
- Is Bash version useful? Since we use it to start webkit
- Should additional NPM global packages be provided?
- Is `playwright-core` correct or should I also add cr/wk/ff there?

**Comment by mxschmitt** [comment]
cc @pavelfeldman

**Comment by yury-s** [comment]
I'd start with bare minimum of what we are currently asking (so bash is probably excessive, same about other global packages). It'd be useful to collect info about browser-specific playwright packages too.

**Comment by aslushnikov** [comment]
Thanks @mxschmitt for handling this!
