### ISSUE TITLE
[Question] params in callback of beforeMount hook in js (not ts) undefined

### ISSUE THREAD

**Issue by oliver-freudrich-packwise** [microsoft/playwright#20289]
Hey,
I am not quite sure if it is a bug but maybe I am just using it wrong.

I am using the beforeMount hook after this bugfix https://github.com/microsoft/playwright/issues/18812 in this way:

```javascript
import { beforeMount } from '@playwright/experimental-ct-vue2/hooks';

beforeMount(data => {
  console.log(data);
});
```

but data only contains a hooksConfig which is undefined. The console.log in the playwright report says `{hooksConfig: undefined}`. I wanted to add things like `app.use` or `app.config` but the app is not existing nor the instance.
Version of playwright and the experimental-ct-vue2 is 1.29.2 so it should be the latest.

Is this a bug or am I using it wrong?

**Comment by pavelfeldman** [comment]
//cc @sand4rt

**Comment by sand4rt** [comment]
Hey @oliver-freudrich-packwise, this problem was resolved in: https://github.com/microsoft/playwright/pull/18596 but it hasn't been released yet. Perhaps @pavelfeldman can tell you when this will be available.

**Comment by sand4rt** [comment]
By the way, this will be the syntax for Vue2:

```
import Router from 'vue-router';
import { router } from '../src/router';

beforeMount(async ({ Vue, hooksConfig }) => {
   Vue.use(Router);
   return { router }
 });
```
