### ISSUE TITLE
BUG : Element is outside of the Viewport !

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#20284]
**Context:**
- Playwright Version: 1.29.2
- Operating System: github action linux latest
- Browser: Chromium,

<img width="444" alt="BUG" src="https://user-images.githubusercontent.com/75999746/213930570-68ff7410-d441-45d0-8c92-fed4986a687b.PNG">

**Element is outside of the Viewport bug**

I don't get any error locally. I'm only getting an error on github actions. I use viewport:null actually but i don't know why i am getting this error in github action.I saw similar errors in one, I tried the solutions opened for the 1.17 version and it didn't work. Can u help me to fix this error. Thanks for your help..

**Comment by pavelfeldman** [comment]
When you say `viewport: null`, you are saying "my viewport size is of my window size". It is likely that with the window size that is used on GHA your element can't be brought to the screen.

**Comment by MuharremBicici** [comment]
@pavelfeldman Doesn't GHA act on my config ts data? The window size used in gha should be the same as the window size used in my local because gha uses my config ts file. And config ts is the same in local and gha. What is problem? Thanks a lot for your support.

**Comment by MuharremBicici** [comment]
@pavelfeldman The reason why I set the viewport to null, I was waiting to open browser maximazed.
I was waiting for the maximized opening for gha

**Comment by MuharremBicici** [comment]
---First of all, I want you to know that I am using a mac operating system.
---I removed the viewport and added start maximized. But the browser still opened small.
--- I value the viewport(1280:609), but the browser still opens small.

<img width="635" alt="image" src="https://user-images.githubusercontent.com/75999746/214411769-c332996c-c6f7-4023-bb4b-72e8fa19e4f3.png">

**Comment by pavelfeldman** [comment]
You can't use viewport in combination with the start maximized. I'm thinking about it this way: GHA has a virtual monitor of 1x1 pixels in size. Those are not factual values, but as an example for demonstration purposes. You start maximized, so the viewport becomes 1x1. Then we try clicking, but no matter what we do we can't reveal the element in the viewport.

The only solution is to remove the --start-maximized and use a reasonable (default) value for your viewport size.

**Comment by MuharremBicici** [comment]
Ok. We removed the StartMaximized parameter. When we entered a specific viewport value, the windows opened a larger browser, but the mac opened a smaller browser again. We added a new window position parameter for mac and now a larger browser opens. Does the parameter we add have any harm? ? Do you mind if we use it? Thanks for your help @pavelfeldman 

<img width="598" alt="image" src="https://user-images.githubusercontent.com/75999746/214638955-8b98f790-02eb-4fdd-af9d-d92552ae5d2f.png">

**Comment by pavelfeldman** [comment]
When you use default settings (not enforcing viewport: null), the window size does not affect the viewport size. You can try resizing it and you'll see that the web page under test does not react to that. You can have a tiny window, but inside, Chrome will be still thinking that it is of a viewport size. The window position command line parameter will not affect the test execution.
