### ISSUE TITLE
[Question]: Equating two elements

### ISSUE THREAD

**Issue by RenderMichael** [microsoft/playwright#20290]
### Your question

I have requirements to write a function for whether two elements are actually the same. I wrote the following function:

``` csharp
static async Task<bool> AreSame(ILocator element1, ILocator element2)
{
    return await element1.EvaluateAsync<bool>("(e1, e2) => e1 == e2", await element2.ElementHandleAsync());
}
```

This seems to miraculously return the correct response.

Since `e1 == e2` doesn't work in vanilla javascript (always returns false) I am puzzled how this works. So my question is:

Can I rely on this? Or is this an implementation detail, some kind of interning or caching which the API contract doesn't guarantee?

edit: there is a prior guarantee both locators point to exactly 0 or 1 elements, my code does not need to account for multiple matches

**Comment by pavelfeldman** [comment]
Your code is correct, if both locators resolve to the same DOM element, e == e will return true.

> Since e1 == e2 doesn't work in vanilla javascript (always returns false) I am puzzled how this works.

What do you mean by that?

**Comment by RenderMichael** [comment]
Maybe this is a JavaScript quirk based on the querying mechanism, but the code
``` javascript
$x("(//*)[1]") == $x("(//*)[1]")
```
returns false for me when running it in the DevTools console

**Comment by RenderMichael** [comment]
Turns out `$x("(//*)[1]")` returns a one-element array, which of course does not have value equality. using `document.querySelector()` returns true for the same elements: the issue is resolved. Thanks for your time
