### ISSUE TITLE
[Question] Using Playwright Generator with Dynamics 365

### ISSUE THREAD

**Issue by ljrain** [microsoft/playwright#20294]
Hello, I am building a demo using Playwright, I used the generator to open a Dynamics 365 Accounts view and then to Click New and create a new Account in Dynamics 365.

I am getting a time out when trying to click the New button and haven't found a way to get past it, does anyone have any notes or tips for using Playwright with Dynamics 365?

Thanks

**Comment by pavelfeldman** [comment]
Since this does not look like a question to the team, I'd recommend you asking it on our Discord: https://discord.com/invite/QVvRJGE8Sa
