### ISSUE TITLE
[BUG] Playwright codegen is not working on mobile view

### ISSUE THREAD

**Issue by amrsa1** [microsoft/playwright#20293]
**Context:**
- Playwright Version: 1.29.2
- Operating System: macOS
- Node.js version: 18
- Browser: All

**Code Snippet**

`playwright codegen --color-scheme=dark
`

**Describe the bug**

Codgen  is not working when user switch desktop view to mobile view, elements are not extracted and listed in the codgen window

**Comment by pavelfeldman** [comment]
> Codgen is not working when user switch desktop view to mobile view

What do you mean switches to mobile view, do you use devtools? If yes, that is expected, you should run codegen with --device instead, otherwise Playwright and DevTools are fighting for the emulation.
