### ISSUE TITLE
How can i accept this pop up?

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [microsoft/playwright#2029]
![image](https://user-images.githubusercontent.com/26269665/80617504-d0555180-8a5f-11ea-82a0-d563a15fa733.png)
I tried 

```
 page.on('popup', async dialog => {
        console.log(dialog.message());
        await dialog.dismiss();
        await browser.close();
    });
```

and also

 ```
page.on('dialog', async dialog => {
        console.log(dialog.message());
        await dialog.dismiss();
        await browser.close();
    });
```
But both did not help me

**Comment by nrayburn-tech** [comment]
The second code bock is what should be working.
Are you adding your page bindings prior the the dialog being triggered?


Here is an example I tried that works as expected.
```
import playwright from 'playwright';

(async () => {
  const browser = await playwright.chromium.launch({
    headless: false,
    slowMo: 500
  });
  const context1 = await browser.newContext();
  const page1 = await context1.newPage();
  await page1.goto('https://google.com');
  page1.on('dialog', async (dialog) => {
    console.log(dialog.message());
    await dialog.accept();
  });
  await page1.evaluate(() => {
    confirm('are you sure');
  });
  await context1.close();
  browser.close();
})();
```

**Comment by Bharath-Kumar-S** [comment]
Thanks @nrayburn-tech.

**Comment by leochung042** [comment]
Hi
Thank you for providing useful information.
I have another question which I facing it now.
How do you handle dialog box popup when landing on the page without any click event.
Also the dialog needs to be enter username and password.

Thank you,
Leo

**Comment by nicoandmee** [comment]
@leochung042 Just register the dialog handler prior to visiting the page or performing whatever action precedes it. Assuming there is a `prompt()` for username&password, just `dialog.accept([username])` and do the same for password.

**Comment by BasavalingaS** [comment]
@nicoandmee can you please explain with example which you mentioned registering the dialog handle prior to visiting the page before i'm also facing same issue which @leochung042 is facing. As soon as i visit the page dialog popup appears and ask for username and password.
Thanks

**Comment by ggorlen** [comment]
Here's an example of handling a user/pass dialog that pops up immediately on page load:

```js
const playwright = require("playwright"); // ^1.30.0

const html = `<!DOCTYPE html>
<body>
<div id="username"></div>
<div id="password"></div>
<script>
document.querySelector("#username").textContent = prompt("please enter your username");
document.querySelector("#password").textContent = prompt("please enter your password");
</script>
</body>
`;

let browser;
(async () => {
  browser = await playwright.chromium.launch();
  const page = await browser.newPage();
  const dialogP = new Promise((resolve, reject) => {
    page.once("dialog", async dialog => {
      page.once("dialog", async dialog => {
        await dialog.accept("some pass");
        resolve();
      });
      await dialog.accept("some user");
    });
  });
  await page.setContent(html); // replace with goto on an actual site
  await dialogP;
  console.log(await page.textContent("#username")); // => some user
  console.log(await page.textContent("#password")); // => some pass
})()
  .catch(err => console.error(err))
  .finally(() => browser?.close());
```
