### ISSUE TITLE
Can I find (and break) playwright TCP sessions for a specific page?

### ISSUE THREAD

**Issue by BrentBaccala** [microsoft/playwright#20295]
I want to test the behavior of my application on connection failure.

I can break all of Playwright's TCP sessions using something like `sudo ss -K dst HOST`.  Not perfect, but it works.

Now I want to have two pages open (two users in a video conferencing system) and only break the TCP sessions on one of them.  Is there a way to do this?

**Comment by pavelfeldman** [comment]
Playwright does not have and TCP-level capabilities. Your best bet is initiating the connection error from the server side based on some testing service api call.

**Comment by BrentBaccala** [comment]
OK, fair enough.  Adding a testing service API call is pretty involved, though.

What I've done instead is to use `pstree` and `ss` to list all TCP sessions coming from a subprocess of playwright (which includes the test browser).  Open one page, list all the TCP sessions, open the second page, list all the TCP sessions again, and compare the two.  The new sessions are the ones corresponding to the second page, and they get killed.
