### ISSUE TITLE
[Question] How to resolve TypeError: Cannot read properties of undefined (reading 'post')?

### ISSUE THREAD

**Issue by eip2** [microsoft/playwright#20307]
Hi,

I'm trying to write a simple function with a POST request using playwright's "request" fixture(Not Axios), but i'm getting this error "TypeError: Cannot read properties of undefined (reading 'post')". I'm using @playwright/test": "^1.29.2". Does anybody know what the issue is? Thanks!

<img width="643" alt="Screenshot 2023-01-23 at 5 14 30 PM" src="https://user-images.githubusercontent.com/123429239/214193000-9e08bb10-90a5-446d-a791-185381bf4dd3.png">

Here is the test which calls the function:

<img width="919" alt="Screenshot 2023-01-23 at 5 16 42 PM" src="https://user-images.githubusercontent.com/123429239/214193233-c02f3703-ec1a-4a38-9179-5f3be519a2aa.png">

**Comment by pavelfeldman** [comment]
Your signIn method accepts single parameter `({ user, request, browser })`, but you call it with 3 parameters `(account, request, browser)`.
