### ISSUE TITLE
[Question] Is it possible to get the code coverage with Playwright for E2E tests?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#20300]

**Comment by pavelfeldman** [comment]
Playwright exposes raw JS and CSS coverage reports, but you would need to use third party tools to analyze them. See https://playwright.dev/docs/next/api/class-coverage#coverage-start-js-coverage

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
