### ISSUE TITLE
[BUG] Authentication persistence using storage state doesn't work with webkit browser

### ISSUE THREAD

**Issue by nvsd** [microsoft/playwright#20301]
**Context:**
- Playwright Version: [1.29.2
- Operating System: [Apple M1 Pro (Ventura 13.1 (22C65))]
- Node.js version: [16.19]
- Browser: [WebKit]
- Extra: N/A

```
## System:
 - OS: macOS 13.1
 - Memory: 2.09 GB / 16.00 GB
## Binaries:
 - Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
 - Yarn: 3.2.1 - ~/.nvm/versions/node/v16.19.0/bin/yarn
 - npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 ```

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { expect, chromium } from '@playwright/test'

async function globalSetup() {
  const browser = await chromium.launch()
  const page = await browser.newPage()

  await page.goto(process.env.URL!)
  await page.getByPlaceholder('yours@example.com').fill(process.env.USERNAME!)
  await page.getByPlaceholder('yours@example.com').press('Tab')
  await page.getByPlaceholder('your password').fill(process.env.PASSWORD!)
  await page.getByRole('button', { name: 'Log In' }).click()
  await expect(page.getByRole('heading', { name: 'Company' })).toBeVisible({ timeout: 25000 })
  await page.context().storageState({ path: 'storageState.json' })
  await browser.close()
}

export default globalSetup
```

**Describe the bug**

When using the above globalSetup, Firefox and Chromium are working fine, but WebKit doesn't seem to work.

We're using auth0 fo authentication which may be part of the reason but it doesn't explain the other browsers working.
Something that may or may not be related is when debugging I tried to use the same globalSetup but swapping out Chromium for WebKit and all browsers stopped working with the error below.

```
browser.newContext: Protocol error (Browser.setCookies): Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsICookieManager.add] setCookies@chrome://juggler/content/TargetRegistry.js:958:24
    Browser.setCookies@chrome://juggler/content/protocol/BrowserHandler.js:249:64
    dispatch@chrome://juggler/content/protocol/Dispatcher.js:129:39
    _dispatch@chrome://juggler/content/protocol/Dispatcher.js:69:36
    receiveMessage@chrome://juggler/content/components/Juggler.js:116:20
```

**Comment by pavelfeldman** [comment]
It looks like you are authenticating in Chromium and are expecting the same storage state to work for other browsers. I'm not sure this is guaranteed to work, auth0 can use browser-specific auth routine, so you might want to auth 3 times into 3 storageStates and then use those states for respective projects.

**Comment by nvsd** [comment]
This makes sense, but if I use WebKit to authenticate, WebKit browsers still fail. I'm trying to figure out the best way to debug/make a repro, but since it involves authentication, I'm not sure what the best method would be to do that. Do you have any ideas?

**Comment by pavelfeldman** [comment]
> This makes sense, but if I use WebKit to authenticate and test with WebKit browsers in isolation, those tests will fail to start in an authenticated state.

I'm not sure I follow this one, could you elaborate? Why should not WebKit work?

**Comment by nvsd** [comment]
I'm not sure I follow your question. 

> It looks like you are authenticating in Chromium and are expecting the same storage state to work for other browsers. 

So if I use WebKit to authenticate and then use WebKit to run the test, WebKit doesn't open in an authenticated state.

If I use Chromium to authenticate and then chromium to test, that does work as expected.

**Comment by pavelfeldman** [comment]
Ok, so the problem is with the WebKit browser and you can't use it with auth0. is there a snippet we could run to give it a try? It is hard to fix it without being able to reproduce.

**Comment by adam-blevins-cko** [comment]
Are you running your browser tests locally against localhost (and thus on HTTP rather than HTTPS)? 

I was having the same symptoms as you, and I found that while `chromium` and `firefox` browsers were respecting sending "Secure" cookies on localhost requests, the `webkit` browser was not.

**Comment by mosh-hamedani** [comment]
I can confirm the presence of this issue. I'm using Playwright 1.40.1. Running tests in WebKit fails to reload the authentication state. If we comment out the WebKit project in playwright.config, all tests pass in FireFox or Chromium (whether testing together or in isolation). In other words, running tests in WebKit, whether with or without other browsers always fails to reload the auth state.

**Comment by nvsd** [comment]
>...I'm trying to figure out the best way to debug/make a repro, but since it involves authentication, I'm not sure what the best method would be to do that. Do you have any ideas?`


>We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it.

@pavelfeldman So to be clear you have taken the original `globalSetup` code snippet and run it in WebKit and it reloads fully authenticated? 

All I can do is ask you to provide me with some direction on what'd you'd like to see again because at the moment all I have is a globalSetup file that I originally posted and I'm running that against WebKit. That's it.
