### ISSUE TITLE
[BUG] `getByRole('tab')` doesn't find any tabs, but `[aria-role=tab]` finds them

### ISSUE THREAD

**Issue by ozyx** [microsoft/playwright#20303]
**Context:**
## Binaries:
 - Node: 18.9.1 - ~/.nvm/versions/node/v18.9.1/bin/node
 - npm: 8.19.1 - ~/.nvm/versions/node/v18.9.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright-core: 1.29.0 => 1.29.0 

**Code Snippet**

```js
    test('GetByRole test', async ({ page }) => {
        await page.setContent(`
        <div aria-role="tablist" class="c-inspector__tabs c-tabs">
            <div aria-role="tab" title="Properties" class="c-inspector__tab c-tab is-current">
                <span class="c-inspector__tab-name c-tab__name">Properties</span>
            </div>
            <div aria-role="tab" title="Annotations" class="c-inspector__tab c-tab">
                <span class="c-inspector__tab-name c-tab__name">Annotations</span>
            </div>
        </div>
        `);
        const getByRoleTabs = page.getByRole('tab');
        const cssSelectorTabs = page.locator('[aria-role="tab"]');
        const getByRoleTabCount = await getByRoleTabs.count();
        const cssTabCount = await cssSelectorTabs.count();
        expect(cssTabCount).toBeGreaterThan(0); // This will pass
        expect(getByRoleTabCount).toBeGreaterThan(0); // This will fail
    });
```

A more full reproduction repo can be found [here](https://github.com/ozyx/playwright-20303-getByRole-tab-tabpanel-tablist-failure).

**Describe the bug**

`page.getByRole('tab')`, `page.getByRole('tabpanel')`, and `page.getByRole('tablist')` fail to find any elements on the page even though they are present in the html. However, using regular CSS selectors (`[aria-role=tab]`, `[aria-role=tablist]`, `[aria-role=tabpanel]`) work just fine.

**Comment by pavelfeldman** [comment]
Reproducing the screenshots is always hard, could you paste a single test that would demonstrate the issue? You can use `await page.setContent` to put some demo markup into it that demonstrates issue the best way!

**Comment by ozyx** [comment]
> Reproducing the screenshots is always hard, having the textual code is always better. Could you paste a single test that would demonstrate the issue? You can use `await page.setContent` to put some demo markup into it that demonstrates issue the best way!

Sure thing, let me give that a shot.

**Comment by ozyx** [comment]
```js
    test('GetByRole test', async ({ page }) => {
        await page.setContent(`
        <div aria-role="tablist" class="c-inspector__tabs c-tabs">
            <div aria-role="tab" title="Properties" class="c-inspector__tab c-tab is-current">
                <span class="c-inspector__tab-name c-tab__name">Properties</span>
            </div>
            <div aria-role="tab" title="Annotations" class="c-inspector__tab c-tab">
                <span class="c-inspector__tab-name c-tab__name">Annotations</span>
            </div>
        </div>
        `);
        const getByRoleTabs = page.getByRole('tab');
        const cssSelectorTabs = page.locator('[aria-role="tab"]');
        const getByRoleTabCount = await getByRoleTabs.count();
        const cssTabCount = await cssSelectorTabs.count();
        expect(cssTabCount).toBeGreaterThan(0);
        expect(getByRoleTabCount).toBeGreaterThan(0);
    });
```

@pavelfeldman OK, this successfully reproduces the issue on my end. Let me know if you need any other information, will be happy to provide it.

**Comment by ozyx** [comment]
Updated the issue with the code to reproduce, and I've also provided a more complete reproduction repo that covers `getByRole('tab')`, `getByRole('tablist')`, and `getByRole('tabpanel')`.

**Comment by pavelfeldman** [comment]
It is saying that the role is "generic":

<img width="376" alt="Screenshot 2023-01-23 at 10 26 34 PM" src="https://user-images.githubusercontent.com/883973/214225783-2ee419d9-3aac-414f-9c2b-664320c8a9b8.png">

Should be `role=`, not `aria-role=`, see https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/tab_role

**Comment by ozyx** [comment]
Hah! Nice catch! Thank you so much.
