### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Anharuz** [microsoft/playwright#20310]
I am learning Playwright and while learning I was trying to print an error message, I tried different solution for fixing my issue but didnt work. below is my code and result what I am getting after test run.

  public async Task GetMessage(string locator)
        {
                       
           using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions());
            var page = await browser.NewPageAsync();

            var alertMessage= new TaskCompletionSource<string>();
            page.Dialog += (_, dialog) =>
            {
                dialog.AcceptAsync();
                alertMessage.TrySetResult(dialog.Message);
            };
             page.Locator(locator);
            Console.WriteLine(alertMessage);
           
       
           /* page.Dialog += (_, dialog) =>
            {
                message = dialog.Message; // 
               Console.WriteLine(message);
          */   
        }
**Output I am getting is:**  Standard Output: 
System.Threading.Tasks.TaskCompletionSource`1[System.String]

**Comment by pavelfeldman** [comment]
This looks more like a C# question than a Playwright question. You can remove all the lines that refer to Playwright and figure out how to print!

**Comment by Anharuz** [comment]
thanks for the solution!
