### ISSUE TITLE
[Question] Hybrid WebView-based apps support

### ISSUE THREAD

**Issue by AndreyZarembo** [microsoft/playwright#20316]
Previous Question #19227 

My team works on hybrid app based on Web view. Our Web-base front makes most of the business logic, and we've created JS-Native bindings to give access to camera, contacts, biometry and so on. We'd like to run some End2End tests to make sure everything works as expected in full setup. It's important to run tests on simulators and on real devices. 

We need any way to run tests on **WKWebView** and **WebView** inside our iOS and Android apps. 

As we discussed in issue #19227 here's more details about our setup.

We have two apps, iOS and Android:

### iOS

- iOS App uses hybrid webview is build as subclass of **WKWebView**
- URLs opens with **load** method by URL
- Page load event is tracked via **WKNavigationDelegate**
- App apps custom JS script handlind via **add** method of **WKUserContentController**
- JS can call this object to run some native functions(see below)
- App calls JS via **evaluateJavaScript** method of **WKWebView**

### Android

- Android hybrid webview wraps WebView instance as composition
- URLs opens with **loadUrl** method by URL
- Page load events is tracked via **WebViewClient.onPageFinished**
- App apps custom JS script handlind via **WebViewClient.onPageCommitVisible.  window.native_bridge -> @JavascriptInterface**
- JS can call this object to run some native functions(see below). 
- App calls JS via **WebView.evaluateJavascript**.

### JavaScript on Web-page

- JavaScript  on loaded page can call code like
```
window.native.takePhoto({
    "title": "Take photo of your ID to verify personality", 
    "target": "user_id_photo", 
    "form_id": "abcde12345"
}).then(function(response) => {
    // Some real logic to process data from response JSON
    console.log(response);
}).catch(function(response) => {
    // Some real logic to handle error from response JSON
    console.error(response);
});
```
- On both iOS and Android this triggers native method with called interface name **takePhoto** and JSON as parameter
- Opens Native camera controller and takes photo

### Expected result

We'd like to have ability to choose the way to run test. Either via browsers, or run test on apps. 
- Best solution will be to start application with necessary parameters on simulator or real device, do some work and then terminate it from Playwright.
- Good solution will be to use any external tool e.g. Appium to run application and somehow connect Playwright to Webview instance

**Comment by pavelfeldman** [comment]
You can use our experimental Android support to test the Android story: https://playwright.dev/docs/next/api/class-android. I think it covers your requirements. There is nothing planned for the iOS though atm, we are focusing on the Desktop and Mobile Web instead.

**Comment by AndreyZarembo** [comment]
Ok, looks nice for Android, we'll give it a try, thanks! 

According to iOS, I think we'll try make it by ourselves, something similar to Android story. Is there any starting points or advices, which can help us? Or may be some important architectural constraints, we should know to contribute our solution?

**Comment by pavelfeldman** [comment]
Supporting even a subset of the APIs against stock WKWebView is a sizable effort. It would probably take us, WebKit and Chromium engineers months, so I don't think this is something you want to sign up for.

Do you have experience running tests on simulators and/or real devices that would last for more than a year and would prove itself maintainable and commercially viable? One of the reasons this feature is not high in our priority list is that we have not seen this model succeed long term, so we are eager to learn from those who achieved it.

**Comment by AndreyZarembo** [comment]
Ok, I don't understand the boundaries of this task for now. We need to try some proof on concept for iOS to guess if it's acceptable tradeoff. Our first step is just to run any test on app.

Is it realistic to run CDP client endpoint in our iOS apps and re-use Android story? 
Also may be this stuff https://github.com/google/ios-webkit-debug-proxy can help us to cut some corners?

**Comment by pavelfeldman** [comment]
https://github.com/google/ios-webkit-debug-proxy - yes you will need this, but there is no CDP in WebKit and WRP is insufficient to implement any meaningful part of Playwright. You are on your own from here :)

I'll close the issue since we've covered the topic and are starting to get out of the scope. Good luck!
