### ISSUE TITLE
inside a docker container (linux) getting error : unable to get local issuer certificate

### ISSUE THREAD

**Issue by subhabratapal** [microsoft/playwright#20314]
I am trying to run playwright API test inside a docker container.
This API test runs ok in my local system.

I have created the docker container using following docker commands:
================XXX=============
FROM XXXX.artifactory.nnnnnnn.net/playwright:v1.28.1-focal
RUN apt-get update

ENV NODE_EXTRA_CA_CERTS=/usr/local/share/ca-certificates/danskecerts.crt

COPY . /app
WORKDIR /app

RUN useradd subp -g 0
RUN chown subp /app

RUN chown -R subp:root /app
RUN chmod 777 /app

COPY ../certificate/abcdefgh.crt /usr/local/share/ca-certificates/
RUN echo $NODE_EXTRA_CA_CERTS
===============XXXX=======

Now with the above image, I have created a container.

but on running I am getting following error :  apiRequestContext.get: unable to get local issuer certificate
I have even tried with update-ca-certificates - but not luck.

Note: If I change the "ENV" to ENV NODE_TLS_REJECT_UNAUTHORIZED=0   - then all is working fine.

Question is how to make it run with Certificate

**Comment by pavelfeldman** [comment]
This looks like a Docker / Node question to me - Node on docker does not seem to trust your certificate. Make sure NODE_EXTRA_CA_CERTS points to the existing file, otherwise I have no ideas, you should seek for the solution on the Docker / Node forums.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
