### ISSUE TITLE
[Question] Test if proper CSS variable was used.

### ISSUE THREAD

**Issue by tpondo** [microsoft/playwright#20321]
Hello,

Is there any chance to verify if proper CSS variable was used ?
Lets say I have button which can have 2 different states and for each different background color is being set:
- state 1 -> background-color: var(--first-color)
- state 2 -> background-color: var(--second-color)
Both variables are stored in global css file, background color is being set depends on the current state.

I was trying to use snippet which many people mentioned already :
```typescript
getComputedStyle(document.documentElement).getPropertyValue(cssVariable);
```
Main problem:
Button is in state 1, when I pass first variable value like this getPropertyValue("--first-color") it will return me RGBA value which is quite ok for me at this point, now I expect that if I do same step one more time but instead of first css variable value I pass second (button is still in state 1) then method will return null or empty string but actually it will pick up value from global CSS file and it will also return RGBA value.
Because of that I can not verify  that for state 1 first variable was used not second because in both cases it will return RGBA value.

What I want to achieve:
I just need to verify that when button is in state 1 then --first-color variable was used for background-color.

**Comment by pavelfeldman** [comment]
You can't check which variable is used, but you can check the resulting color value like this:

```js
const locator = page.getByRole('button');
await expect(locator).toHaveCSS('color', 'rgb(100, 100, 100)');
```

**Comment by tpondo** [comment]
Hello Pavel,

First of all thank you for sharing your thoughts, currently I am working in a design system project and idea is to deliver library of components, then every single component can be customised by for example UX designer according to his/her needs and can be used somewhere in the future. Designer can change value of variable but name of variable should stay untouched, if my test could verify only if css variable was used then in both cases test would pass as in this situation I do not care about color value but if proper css variable was used. 
If I can test only resulting color value then in case which I described test will fail unfortunately...
I am just looking for a good way to deal with that case :(

**Comment by pavelfeldman** [comment]
Sadly, no good tool for you. This variable can be used in the style attribute, in the regular or in the composed stylesheets, inherited from somewhere, etc.

**Comment by tpondo** [comment]
Ok so Pavel one more question let say this is my variable used for button: 
--button-background: rgba(212, 236, 247, 1);

I have tried to test it with your snippet of code:
await expect(locator).toHaveCSS('background-color',  'rgba(212, 236, 247, 1)');

Unfortunately test fails, seems like Playwright while checking background color of my button calculated it from RGBA to RGB:
  Error: expect(received).toHaveCSS(expected)

    Expected string: "rgba(212, 236, 247, 1)"
    Received string: "rgb(212, 236, 247)"

Is this a proper behaviour of Playwright ? If yes then to perform this test I need to write method which will calculate RGB from RGBA value before I put it into assertion?

**Comment by pavelfeldman** [comment]
Browser does it, not Playwright. You can use [window.getComputed](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) to verify. This is a different issue though, so closing the original issue as per above!

**Comment by TomasHubelbauer** [comment]
Note that `toHaveCSS` also works with CSS variable names, for anyone who needs this:

```typescript
await expect(locator).toHaveCSS('--shift', 'center');
```

This way it is possible to not only verify the effects of CSS variables being used for actual CSS attributes via `calc` but also their values themselves.
