### ISSUE TITLE
Configuring Playwright with multiple start up projects 

### ISSUE THREAD

**Issue by shakyabipin** [microsoft/playwright#20327]
Hi,

I have three projects as a start up:
1) Blazor Client Application
2) Blazor Server Application
3) MVC Admin Application (Identity Server)

I have install Playwright and able to run it with 

.\playwright.ps1 codegen <url>

But when I try to run a test method which test the steps to cover it, I am getting page not found 404 error in the trace file generate by the playwright.

Please refer to the attached zip for more details.

[playwright.zip](https://github.com/microsoft/playwright/files/10490782/playwright.zip)

Kind Regards
Bipin

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. They should include source code we can run, expected outcome and the description of the actual result.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
