### ISSUE TITLE
[Question] get ids from a specific locator type

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20326]
Hello team,

I would like to create an array with all checkboxes of the page and their id, in order to be able to check only a subset of them randomly for specific test purposes. IDs are "dih-rules-checkbox" with a number as a suffix.
Example : "dih-rules-checkbox-556464"

I've tried the following code : 
for (const li of await this.page.getByRole('checkbox').all()) {
      console.log(li);
    }

It finds all the checkboxes but I can't get their IDs :
 "Locator@internal:role=checkbox >> nth=0".
Locator@internal:role=checkbox >> nth=0
Locator@internal:role=checkbox >> nth=1
Locator@internal:role=checkbox >> nth=2
Locator@internal:role=checkbox >> nth=3
Locator@internal:role=checkbox >> nth=4
Locator@internal:role=checkbox >> nth=5
Locator@internal:role=checkbox >> nth=6
Locator@internal:role=checkbox >> nth=7
Locator@internal:role=checkbox >> nth=8
Locator@internal:role=checkbox >> nth=9
Locator@internal:role=checkbox >> nth=10

I've tried then to find them by ID, thanks to regular expressions, but it does not return anything :

const regex = new RegExp(`\\d+`);
for (const li of await this.page.locator(`id=dih-rules-checkboxes-"/${regex}/`).elementHandles()) {
  console.log(li);
}

Could you please help me ?

Thank you very much,

Regards,

Johan

**Comment by pavelfeldman** [comment]
Try this:

```js
for (const li of await this.page.getByRole('checkbox').all()) {
  console.log(await li.getAttribute('id'));
}
```

**Comment by MehseinJohan** [comment]
Hello Pavel,

Thank you very much, works for me.
However, two things :

- I'd like to create an array and take some of them randomly (4 out of 10 for instance). How could I do it ?
- Could you also help me on the regular expression because I think it would be very helpful to me in the future ?

Thank you very much !

Regards,

Johan

**Comment by pavelfeldman** [comment]
These would be outside of the scope of Playwright, you should refer to the generic JS/TS resources for that!
