### ISSUE TITLE
[BUG] Wrong expiry date of a cookie is returned 

### ISSUE THREAD

**Issue by iamlevik** [microsoft/playwright#20334]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows 11
- Node.js version: 18.12.0
- Browser: [e.g. All, Chromium, Firefox, WebKit]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
 const cookies = await context.cookies();
    const example_cookie = cookies.find(c => c.name === 'token');
    remember = example_cookie?.expires
    console.log(remember)

    const rememberMeExpiration = new Date(remember).toISOString()
    console.log(rememberMeExpiration)
```

**Describe the bug**

I'm looking to compare the difference between the local date and the expiry date set on a cookie.

Running the above code will return the following console logs 
```
2023-01-24T16:37:39.046Z
1690130260
1970-01-20T13:28:50.260Z
```

But the issue is, that running the test in headed mode where I've added a sleep of 20 seconds just so it gives me enough time to check the cookies manually in the browsers console, the expiry is correct, is as of 2023.

Why does it return 1970 instead of what is actually in the browser context?

Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
As per https://playwright.dev/docs/next/api/class-browsercontext#browser-context-cookies-return,

`cookie.expires` is Unix time in seconds, there are no milliseconds information for cookies in the web.

`new Date` wants milliseconds, so you can do `new Date(remember * 1000).toISOString()`

**Comment by iamlevik** [comment]
Wow, it worked, fastest response I've got. Thank you! Now I understand it!
