### ISSUE TITLE
[BUG] FreeBSD support

### ISSUE THREAD

**Issue by Ae-Mc** [microsoft/playwright#20330]
**Context:**
- Playwright Version: 1.25, 1.29 (Latest)
- Operating System: FreeBSD
- Python version: 3.10
- Browser: All
- Extra: `uname -a`: `FreeBSD RandomName 13.1-RELEASE-p3 FreeBSD 13.1-RELEASE-p3 GENERIC amd64`

**Code Snippet**

```shell
pip install playwright
```

**Describe the bug**

Can't install playwright on FreeBSD system

**Comment by mxschmitt** [comment]
FreeBSD is not supported, only Debian and Ubuntu are supported Linux distributions.

**Comment by Ae-Mc** [comment]
Will it be supported sometime?

**Comment by pavelfeldman** [comment]
There are no plans to support FreeBSD!

**Comment by infostud** [comment]
FreeBSD is BSD not UNIX-like.

**Comment by alvar-freude** [comment]
> FreeBSD is BSD not UNIX-like.

That's wrong. BSD is more Unix-like than Linux.

**Comment by infostud** [comment]
> > FreeBSD is BSD not UNIX-like.
> 
> That's wrong. BSD is more Unix-like than Linux.

I'm sorry I should have been clearer. FreeBSD is derived from the Berkeley Standard Distribution (BSD) of UNIX (trademark of The Open Group) not a Unix-like or Unix-compatible operating system like Linux. The TCP/IP protocol suite was first developed on BSD UNIX. If it doesn't run on BSD it doesn't run on servers supplying about 40% of internet streaming traffic.

**Comment by adamretter** [comment]
It's now possible to use FreeBSD from GitHub Actions if that is helpful - https://github.com/vmactions/freebsd-vm

**Comment by alvar-freude** [comment]
> FreeBSD is not supported, only Debian and Ubuntu are supported Linux distributions.

Just for the record: I use Playwright since five years without any issues in a FreeBSD jail with Chromium.

Since last year there is also a Port/pkg for Python: https://www.freshports.org/www/py-playwright. (I haven't tested it.)
