### ISSUE TITLE
Is there a place to store "global" state other than `process.env`?

### ISSUE THREAD

**Issue by toddobryan** [microsoft/playwright#20338]
I've just started using Playwright and have hit a bit of a wall.

We can't store our test users in code--we have to hit a secure endpoint to get the users, passwords, etc. That's fine. But now where do I put all of that information that I only want to fetch once during `globalSetup`?

I could store the test user credentials in `process.env.USER_CREDS`, but `process.env` only supports `string`s and we get back a `UserCred[]` that I don't want to keep `Json.parse()`-ing every time I need to use it.

So, where's the right place to store stuff (specifically non-string stuff) you look up in `globalSetup` and want to have access to in the rest of the test structures?

(Note: I asked this at https://stackoverflow.com/questions/75207923 before I realized Playwright welcomed question issues.)

**Comment by pavelfeldman** [comment]
You can always write and read files!

**Comment by toddobryan** [comment]
Is that the preferred solution? And will that work on CI? And that still involves `JSON.parse()`-ing when you read from the file, right, which in my case would be in the `beforeAll` of every test.

I guess I'm looking for a place to store typed data. I mean, if `process.env` exists, why couldn't there be a `playwright.cache` whose interface could be specified in the config file, so when I grab a value, I'm guaranteed of a type.

I take it that the answer is, there is no such place. But I want one. In addition to having to fetch the user creds, there are lots of "global"-ish values that depend on environment variables. For things like BASE_URL that are strings, `process.env` is fine. But for objects or arrays or anything more complicated than a simple string, I feel like it makes sense to be able to save something in memory once and not have to keep stringifying and parsing it every time I want to get access to it.

I guess I could just declare a global object in `playwright.config.ts` or somewhere with an interface for the property types and populate that in `globalSetup`. Does that seem reasonable, or am I about to implement some sort of anti-pattern?

**Comment by pavelfeldman** [comment]
> I guess I'm looking for a place to store typed data. I mean, if process.env exists, why couldn't there be a playwright.cache whose interface could be specified in the config file, so when I grab a value, I'm guaranteed of a type.

We are working on a cross-process store that would be very close to what you describe, but there is nothing available in the release versions of Playwright. When answering questions we always assume that you need it right here and right now, my suggestion to use files stands. Yes, you will be parsing JSON, but typing is orthogonal to that, so you'll need to declare your types regardless. Node's FS + JSON apis are quite simple, it'll be 2 lines of code helper function on your end.

**Comment by toddobryan** [comment]
Cool. If the cross-process store is in development, I'll just abuse `process.env` until it gets here.

Would using a global var -- _as long as it's immutable after `globalSetup` is finished_ -- cause any problems?

And thanks for the quick response!

**Comment by pavelfeldman** [comment]
Global var won't work because globalSetup and your tests run in different processes (and different Node instances). We have one main process that does global setup and a bunch of worker processes that run actual tests.

**Comment by toddobryan** [comment]
Ok. Files it is, I guess.
