### ISSUE TITLE
[BUG] VS Code extension not showing proper error when node cannot be found

### ISSUE THREAD

**Issue by KrysKruk** [microsoft/playwright#20332]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 14.6
- Visual Studio Code version: 1.74.3
- Playwright for VSCode extension version: 1.0.6
- Browser: -
- Extra: -

**Describe the bug**

VS Code extension shows warning `Please install Playwright Test via running npm i --save-dev @playwright/test` but when I go to "Output" -> "Window" I see an error:
```
[error] [Extension Host] Error: not found: node
	at ci (/Users/.../.vscode/extensions/ms-playwright.playwright-1.0.6/out/extension.js
```

I was struggling to run Playwright VS Code extension in my monorepo project. After installing `node` with `homebrew` it started working, so the error I posted was crucial here. It couldn't find `node` because I'm using `nvm` configured with `fish` so I guess it couldn't find an executable, but IMHO the most important thing here is to show users a proper error message.

**Comment by pavelfeldman** [comment]
Merging into https://github.com/microsoft/playwright/issues/18954, you don't need to have a global node installation, it is a VS Code bug where it does not mirror the environment in time into the extension host.
