### ISSUE TITLE
Github stars needs to be updated

### ISSUE THREAD

**Issue by ItsRoy69** [microsoft/playwright#20344]
In the site we can see that the number of stars present in the banner is 46k
![image](https://user-images.githubusercontent.com/78967360/214413147-c4dfe00b-1283-4ad3-912d-35d000a22335.png)
But when we visit the repo we see it  is 7.9k. Thus needs to be updated

@maintainers I am willing to contribute here so it will be great if someone assigns me

**Comment by yury-s** [comment]
Seems accurate:
<img width="174" alt="image" src="https://user-images.githubusercontent.com/9798949/214430814-d4d30747-8d73-408a-9324-1d30e8c841de.png">

**Comment by pavelfeldman** [comment]
Looks correct to me, you are looking at some other repo I guess.
