### ISSUE TITLE
[Question] HTML reporter test result order

### ISSUE THREAD

**Issue by DMazona** [microsoft/playwright#20351]
I am using playwright primarily for API testing, and am running a group of tests in a describe block serially. I have noticed that when all tests pass, the results in the html report are in order of execution, but when one test fails, it puts the failed result at a the top of the section of that report. **Is there a way to change this, so it will maintain the same order as execution?** The JSON output appears to do this correctly.

**Comment by pavelfeldman** [comment]
There are no settings for that at this moment.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
