### ISSUE TITLE
Turn off log 'To open last HTML report run npx playwright show-report'

### ISSUE THREAD

**Issue by Ahmad-billz** [microsoft/playwright#20369]
When the execution of a test file is completed. The last logs we get(automatically) are

To open last HTML report run 
              npx playwright show-report
              
 Is there a way to turn this log off. I do not want it to be printed at the end at all.

**Comment by pavelfeldman** [comment]
There is no way to turn it off.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by zach-betz-hln** [comment]
First, thanks for this awesome project.

For what it's worth, I'm interested in this issue as well. We're using yarn 3.x for package manager, so we have a custom script to open the report, vs our developers copy/pasting the `npx playwright show-report` command.

**Comment by neurotic** [comment]
+1 

We are using playwright inside docker, and the command we need it's not npx playwright show-report, and we prefer to hide it.

**Comment by BrandonDR** [comment]
+1 mono repo means our command differs as playwright is in a subdirectory

**Comment by diegoblattner** [comment]
+1 the mono repo command differs as playwright is in a /e2e subdirectory

**Comment by mastersign** [comment]
+1 For my usecase the message is disruptive clutter as well.

**Comment by 4ekki** [comment]
@pavelfeldman, could you please explain the reasoning why it cannot be turned off? I'd like to disable it for my CI runs as well.
