### ISSUE TITLE
Captcha blocks me, how can i solve ?

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#20360]
I need to bypass the captcha block to log into one of my test environments. I tried to read the captcha with the Tesseract library, but I couldn't because of the noise. I added the captcha's photo. How can I remove the lines and noise from this photo?

<img width="99" alt="captcha" src="https://user-images.githubusercontent.com/75999746/214518201-7001623c-6fc2-4a66-8896-e5d2cf377c80.PNG">

**Comment by pavelfeldman** [comment]
This is outside of the scope for Playwright.
