### ISSUE TITLE
[Question] Could we allow to skip throwing error when performing validation with expect's poll or retrying feature

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#20372]
First of all, thank you so much for implementing the **expect's poll or retrying** feature. 

We were using our own custom defined function for these features before. As we are upgrading the playwright version. We are replacing the existing custom defined function with these new **expect's poll or retrying** features.

- I have a scenario, where I need to perform multiple async operations and then validating the multiple expected behaviors. We are using expect's retrying feature and it works perfectly as expected.

- There is another scenario, where we are performing multiple async operations in retry block with certain wait time. And if we are not getting expected behavior after the retry block execution, then we don't want to fail it or throw error instead we want to proceed for next steps and perform next operation based on the above results.

Would it be possible in any way to achieve the second scenario where we can use retrying or polling feature? Or could we have any flag in **expect's poll or retrying**, where we can mention not to throw error when it doesn't meet the expected value and we don't want to throw error.

**Comment by pavelfeldman** [comment]
Do you think adding .catch(e) would do what you want?

```js
await expect.poll(...).toBe().catch(e => {})
```

btw, for the general purpose retry you can use https://playwright.dev/docs/test-assertions#retrying. Same deal there, just add catch to the end.

**Comment by ukdas** [comment]
Hi @pavelfeldman ,

Thank you for looking into this quickly.

I tried with below scenario and it's worked perfectly.

```
import { expect, test } from "@playwright/test";

test("Navigate to playwright home page", async ({ page }) => {
    // Navigate to the playwright home page.
    await page.goto("https://playwright.dev/");

    // Wait to load the page.
    await page.locator("[id='__docusaurus']").waitFor();

    // Validate Get Started button is not visible. -  Failing this intensionally to validate the expect's poll / retry behavior.
    await expect
        .poll(
            async () => {
                const getStarted = page.locator(
                    "[id='docusaurus_skipToContent_fallback'] [href='/docs/intro']"
                );
                const isVisible = await getStarted.isVisible();
                return isVisible;
            },
            { message: "Get Started button is visble", timeout: 10000 }
        )
        .toBe(false)
        .catch(async () => {
            // Navigate to the playwright intro page.
            await page.goto("https://playwright.dev/docs/intro");
        });
});
```

But **it's not worked if we don't provide any parameter in the catch block**. Is it expected?
![image](https://user-images.githubusercontent.com/64302433/214622523-96cad31e-f414-4c5e-9140-beaa216feef7.png)

Also, as per our repo's ESLint rule, they are suggesting **not to use `try`/ `catch` / `finally` block**. So, it will be big problem in that case to use `catch` block. If are having this scenario in multiple places across multiple files, then disabling the next ESLint line rule needs to be copied everywhere as we won't be able to disable that rule in the file level or project level.

Would you like to have any suggestion for this? I would like to prefer having another flag like `message` & `timeout` flags are there.

![image](https://user-images.githubusercontent.com/64302433/214614501-2bb963d3-48a0-425f-a757-87d0d3e1a6d4.png)

Also, could we please update the doc to handle this kind of scenario once the solution will be finalized? I believe, it will help others also.

**Comment by pavelfeldman** [comment]
There is nothing Playwright-specific in the solution I suggested - that's how JavaScript works. I don't think we should be documenting the JavaScript lang in the Playwright docs. try/catch is too big of a feature to ban on the repo-level, maybe you can negotiate disabling it for your tests folder. We should not be working around the bans for JS features via new Playwright features.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by ukdas** [comment]
Thank you for the detailed info.
