### ISSUE TITLE
[BUG]: secure cookies don't get included for wss:// WebSockets

### ISSUE THREAD

**Issue by RuanAlesi** [microsoft/playwright#20370]
**Context:**
- GOOD Playwright Version: 1.27 (Webkit 1630)
- BAD Playwright Version: 1.27 and 1.28 (Webkit 1699 and 1751)
- Operating System: Windows

**Code Snippet**

- none

**Describe the bug**

It's a logging in scenario, after sending the credentials the portal doesn't work properly, it should be logged in but interacting on the page sends me back to the login page (same as clearing cookies).
It works perfectly on Chromium, Firefox and even a manual test on Safari and also previous versions of Webkit.
The only clue that I've found is regarding one of the requests to Blazor, when it works I see the header 'connection=keep-alive', but such header is missing on the current Webkit version (I have no idea if it makes difference though).

Add any other details about the problem here.
- One of the requests send cookies explicitly in the headers, but not on that version (but Safari as well and it works)

**Comment by pavelfeldman** [comment]
Can we get a script we can run locally to reproduce?

**Comment by RuanAlesi** [comment]
Hey @pavelfeldman,
First of all, thanks for the quick reply.
Well, actually it's not a code matter, but how Playwright Webkit manages cookies when accessing a Blazor application:
- I see this on the build [1751](https://playwright.azureedge.net/builds/webkit/1751/webkit-win64.zip)
![image](https://user-images.githubusercontent.com/64651136/214801124-87c80278-5cfa-4f48-818f-f80aa68e537e.png)
- **So the authenticating on the application fails likely because the cookies are not there.**

- And I see this on the build [1630](https://playwright.azureedge.net/builds/webkit/1630/webkit-win64.zip) - which works percfectely:
![image](https://user-images.githubusercontent.com/64651136/214803516-f73626f2-4e99-4cf3-b38d-76c5f50fe56e.png)

PS:
1. As we are talking about logging in scenario, it means sensitive information so I cannot share everything. Even though, if you think it's crucial for your investigation I can create a tester user for you on our testing environment. So let me know.
2. One of our developer had the kindness to build a small Hello World Blazor app in order to expose the issue. So this is what happens:
- Chromium Playwright build 1045 and Firefox Playwright build 1372: the cookie is added on the main page:
![image](https://user-images.githubusercontent.com/64651136/214811096-c1ee5cf6-08bf-4489-94f1-5da02aa8e1e4.png)
- Webkit: I see the cookie just flashing when I access/reload the page, but then it's gone:
![image](https://user-images.githubusercontent.com/64651136/214811773-0c5bd9db-a042-4ce0-b5de-1a264661c7a7.png)

FYI:
- A (maybe) not related bug on the latest Webkit build 1767: it crashes when I access the local application (it should ask for confirmation regarding untrusted certificate). These are the details on the .dmp log file
![image](https://user-images.githubusercontent.com/64651136/214807147-f8312257-8448-467d-b9d7-e816505146e6.png)

- This is the message that I have on the previous version:
![image](https://user-images.githubusercontent.com/64651136/214818164-0d1156c0-3be6-4b81-a255-1aaf8b2c3b36.png)

**Comment by RuanAlesi** [comment]
UPDATE: enabling IgnoreHTTPSErrors prevent the certificate checking, and (somehow) fixes the cookie value in the Hello World app. Even though our application is still failing only on Webkit and the only difference that I see so far it's regarding the SameSite attribute, one specific cookie is set as Strict on Firefox, Safari and Chromium but as None on Webkit.

**Comment by yury-s** [comment]
> * One of the requests send cookies explicitly in the headers, but not on that version (but Safari as well and it works)

Can you share full response that sets the cookie? 

> * As we are talking about logging in scenario, it means sensitive information so I cannot share everything. Even though, if you think it's crucial for your investigation I can create a tester user for you on our testing environment. So let me know.

That + playwright script that exposes the problem would be very helpful. You can share it privately via email in my profile.

> * One of our developer had the kindness to build a small Hello World Blazor app in order to expose the issue. So this is what happens:

Can you share that app or at least a reduced playwright test that reproduces the problem. We need a repro to act on this.

**Comment by RuanAlesi** [comment]
I've just sent to you. I couldn't attach .zip files so I shared the files on OneDrive. The links are in the email.

**Comment by yury-s** [comment]
Thanks! I tried to reproduce it with the website you mentioned but the test case you shared is passing for me, I did the following:

```ts
test("test", async ({ page }) => {
	await page.goto("https://<...>/");
	await page.locator("[id='btn-local']").click();
	await page.locator("[id='email-address']").type("<...>");
	await page.locator("[id='password']").type("<...>");
	await page.locator("[id='login-submit']").click();
	await page.waitForSelector("a[href='/Account']");
	var expectedComponent = page.locator("a[href='/Account']");
	expect(await expectedComponent.isVisible());
});
```
What check is expected to fail?

 Do you have "Hello World Blazor app" running somewhere so that we can test with a reduced example which clearly exposes the issue (sorry, I don't have C# on my machine)? It looks like there may be a bug in Playwright but we need a clear repro demonstrating the problem. If you think a cookie is missing after the login steps you provided please add a check that has to pass, something like:

```js
	const cookies = await page.context().cookies();
	expect(cookies.find(c => c.name === 'foo')).toBeTruthy();
```
We don't have resources to investigate what is going on a large app we are not familiar with.

**Comment by RuanAlesi** [comment]
Really? This is strange...
I don't see which browser you are using. Is Webkit, right? The latest version. That assertion should failed due to the failed login.
Yes, I will try to investigate the cookies.

**Comment by yury-s** [comment]
> I don't see which browser you are using. Is Webkit, right? The latest version. That assertion should failed due to the failed login.

I'm testing with  `@playwright/test@1.30.0`. Yes, this is webkit browser. I'm testing on mac though! It may well be a WIndows specific issue as webkit uses different network stack there, let me ask my colleague to try it on win.

**Comment by yury-s** [comment]
> Yes, I will try to investigate the cookies.

Thanks, knowing which cookie is missing would be very helpful.

**Comment by RuanAlesi** [comment]
> 

COOKIES FROM WEBKIT
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".databridge.galactica1.com"										string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		"ARRAffinitySameSite"												string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"c0e387a9d75451638362e4ef14c9be275e10819d07aa85f1e7acbce9f4886bd9"	string
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		"databridge.galactica1.com"											string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		".AspNetCore.Antiforgery.q08xqAsmzsI"								string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"CfDJ8HIBakkTFdhJk34vOSSFFLmm_RfiH5KkNz84TkpZWuTS0wr21qVlYaNjdcAmKRER3qm6kiTToDfznjIEGs7y_K3cSfi-e87X_nZ2H42oiyLP1RltbzY9EOcb_CQyRO8mDFglRsfHms4XlmSLmZCATxM"	string
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".galactica1.com"													string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		".DataBridge.SharedCookie"											string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value	"CfDJ8HIBakkTFdhJk34vOSSFFLngflLEjJtMOqR2DptRN6YrvNXQcQh15-nMhrkUKKo1fKfoNNg8XT9_pHxAN8pk2EJMIIbut_6Tdu_i-ymdkNDB5KkfEvYMlGuaN2ClAikuvXViK8tYMNREQs_rI9dR4gtVuAl4UWg06x2ztgKqeJXWnryiyxSP1GPd7xz7jOTti9tmBLJs8bCmU9m1x7SI8ho_B-YpdTAPA-WU2tUmQWNj5OkKosTLxnWKoP4fEoNFLF_UfX_2ZSAXXy-_O6vK1dNEztjjYEmXrP97YnHeKSmeBrvfTiyAyilNdbAKqUjktPXukxrVWosLWzooxHJe-ekNySheJWeUR3Udp9Z0_hbB8KbhuZSuT-sBZtRMU2St_Mw26xSGFCPvzvAyoPgEmJmlyRNZTQZue47RJYEHYDO21qij8IBJmK9tVKeASVUc9LyQ1CkUWyyYSRV0qUnERDR3GWSJ8RkZFWyZkt7UXHcN580dNjCuZTJlcvnMwPo1s41K-Fv7RjlxwAlfN1vCk6MYgYP4GQG6cApDJF3dd78_fXMd7db5FR3Cvx-bBOkoJxTSXqjvPCcDFD_022CdyW-SCRUClVBFHGCmY0ee3fv7wV-G8h6w28i0cCqgMy1f83j6V4zFrM1qoWp1Ss0j0AvClrxm7gSvrRa7etwTcsYuGe9vuH7AwGjjdB_c-HKCUtGL6j-VA8L9Wm6x-7Wn_nTlWY-q4TEm3b4cdDv8HzhDJx4cxNojDANjTPJVHG3tsWsocidjUluXJR6IA7nodhtnSKZ0gk83xXWZRiKQSt3Zgwz0UsVOquZXc-BS-Luq23Wq8_T12VMsoLufnsQw80M__OmKo07p75xvUsdFW-e_vwI3ZxtKhP2iqDBx4bUMubrUKqyr3XnAxD576icJXcTvWOJpUJLIfw55Oj7rq9HBuuqNxwvNXT6P_EkBe78E6maerb4jLL5m7e_ryF_WEEJucoTlmw4rqRPsyBstPKzAMJeGhwzsq_FV2ChP5LARiOMuyQ87KKplEdBFqTnahsOtlSvkcqXhMFE8-IkglpYqagsT0JwM57hG3eoMLvu47F1vqtjVabN4WRgg0OiBL-ULvGqifDJZVu3i1i81IcBBaqXjA4Z9Xmo_ONn3t0idpWl3bLhdok6S7iPO6llr_CmqMDNU0sAHQVhGZw0vTbFNEhPHu4--dlagIzS-fZVlUSS8Elq0u0OC-bq1iyqbKCSJKacko00So-xeLLM5p_gGBdpY7F_E_7XFYXWsqGbsVYc_RGLbGVhGjnueVjowWZJvBpnKpToGU8QfplKtByIRufA--ZjSNQPwSwvh2xzjCtrUzuYOPTtXvLOJThST-bja-sFk7rT8SI4zNUZpvg6waLU6U_KjQDoezLFf77mjNpNOw4SadRDxUmyhIKUY2VwhAzp2kZoXOrJEwDZS22krkLJjgmMTUUAORodsgQoKVFocXgIFPdaZJHgfXtjPHVT3WmZ1mzxF60yHMOhGuIVTFFHQ4DTNKQyI8aUhYvm_ZYoE8Lqusq9AhByB4TTT5Xegiztqm8EnZJcjME3DlUVs1fBsZxHl7So6AU0Efq_9Joc8dIrOcMs-aHi9i_B93McGeNbSt971mSKg4Zi3htsjARiIypyt3kfUTIg1j_72aiAHL8u_XzG-K45L3-hKVTR1pkM5WM08Kkk5ox_BInxkdTF-8uCO1wDd6JFXg13ZS7qHIuqHkrA61EBdxeaSu8Sn_3A5eOFuEB2RXWULkg-kiC7ooGHstrIqGLmmPj-294B03VEwEIn2dvN5hnF-Q6COehtStdoNrAbSdzH1FdNnAjyCRjt71wz74UjMM7FtNsIYsyROk8QkQMH0RIU8ifeXRQJii-K-9oB_-TOb1yBqO7Gw-9GqMmpv8RL9cmAwfw"	string
`- {Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".databridge.galactica1.com"										string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		"ARRAffinity"														string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"c0e387a9d75451638362e4ef14c9be275e10819d07aa85f1e7acbce9f4886bd9"	string

**Comment by RuanAlesi** [comment]
> > Yes, I will try to investigate the cookies.
> 
> Thanks, knowing which cookie is missing would be very helpful.

COOKIES FROM CHROMIUM
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".databridge.galactica1.com"										string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		"ARRAffinitySameSite"												string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"c0e387a9d75451638362e4ef14c9be275e10819d07aa85f1e7acbce9f4886bd9"	string
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		"databridge.galactica1.com"											string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		".AspNetCore.Antiforgery.q08xqAsmzsI"								string
		Path		"/"																	string
		SameSite	Strict																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"CfDJ8HIBakkTFdhJk34vOSSFFLmiX_Pq0Nrba1zXFsW8SVmV4er9y983g3MB1t5TRrT-IEXAGrf9-htYM5Rq9DSeXklHZoXHaGdBatCodFx5W1PjSWSu4d2TJpXKeNHLXQ9pIxbtr6cl78gaIqcqkt1sn40"	string
-{Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".galactica1.com"													string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		".DataBridge.SharedCookie"											string
		Path		"/"																	string
		SameSite	None																Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value	"CfDJ8HIBakkTFdhJk34vOSSFFLnPNX_EA7jMKdL_AIaVbJRRUCrx_gzxzDf0Cu6WwNsRzNo2neW3xisM1PU6OHiB3UHipJVRSaBOCK14XFbPoiEik0qPyNnpZkzBfRW15t-r-wKsDu7KTnJ9l8Gpji_08r5Ibyuf3UklqOoQ1u67DZvS6hcarYLgCaUmuCEEGgi_Uf4yL8pDWLdkZDK5XuO3YPqRrD-Q_2bZTBOCYWZp1hvPT0u-NtPSZdzTAvdLvfl6EHCkEHvphP7euKcARrgNRRy0w0CpDM0xaduaVvQTc4e55wVDmJRL-mq4jcJeHOtZ2A-au-Kzv4YEg_hYhXtT9ifzcHDXw--ditDnoyG58z-ZrVOSJxoOe5fyt1UJnE-tplVb74_aaMbnQri9THiuzHSOiyVEWUzmTMvudvGwVAxFxWGdDgdcqOTn1DZcHNmIlvCItflUOpxZUrwmfEdo_-DbL--5VBIf7qufIpIaBcnr8TzJ6BZfpgFZTMyeirLT6aZRyoxQ58q7Rtzp2CLJZgFmAEHgCxeYMpUhrz7y7xGebk1TQ4JW7DjWAOvNRe0zeAdfe62d1kTmL8lts6Y878H7DxiAH036x842d-BtLLXAOA4o7cllcKtdejt2Prgk1xqOIZV1d5ed23D79cGTEF-7pSVzc6YeILhiRUJhdUo6vxHCtcJi01yjkQOsb27Cr0wCOMV3Ulb1djl7fZ2pKoRkw56yvEej3Q1kPr2_lVTFtCdUyncCtm0LMUnpZVTQiu4kBD1kVNj8UlTC7nYFgBImyIT4t3y3Q8fSCOJeqCKPNDnGRW0Fmwu8m7jKX9B4MwnJelWW3ww85YDN_9U1EIoo_sz8AvOEqiJWuubc5bcS9L8CzZnlf7402_401rx8KZjKKzz-U_yxxnrbs5wi4cju88fhlhZnLHvryjzLIlqm6C8YAnvP8zUphxlXyDHO9hUkSmgG85kunma7TN1EUBxIC4boAR4m-lIe4f7e6ENg_CtylLmSs030Zc6rLQT_lOxwrarguanpNPIlLm3fU8lING8cZofNu9_2QXqBuaPYA46z6-ixHoPlF1rB_A-qe3TuZgB4yZGFlKssnUkJveluFP0jNUeZ61W7tXyqS8Azmy2DhxiRXCEuKSJAoRUQr5DngomaUUohhGCBE1IVZQsd9eNxtRAc-_nOotg892ewsTaqn8CbkYXFJikx3cjkURS_xHMk7v0CryyErYUyUAe8LA7qxYpyLptZ_23RfmC_wA0osU5i0q-oIBjYLpEe3jvtccfuCsdLc3h-x5g_G4w95CQsYev-4PX8u4ovo5aJXsgOoOOWipfpcdjkb5rzXY13LJ1MphC98mO-BBKG4Idc0usqS2XhqgvdmFqBpX5L5qJEEeZ20I_u9GUbJzH-JDaBlM2xEA4Ly-EL2dAYfJr3VXz7_-i2i-b-P_QjcngYagQoTuceZACWGYFdIWFbFDVLFew01bCqQcZ09jAN-iwKENanAfOFODvo_ePVsQCGf5qxlSqvvAAP0ZP7YJX9UjQGgTR69gjhaJZXunO7v-xJ8emEtl46kMripDye8G5H6aSzF5QCOzYLhMA9n2km1okTMhQFFFn--MvLqUNds41XqS___Jv3cTsf2QV9Q9RvbmGAgatRqrB6_lLXKeNz1dmovNHbAxOeDOPfFz0Bm9eO49M_zAEPv32JsaK1aNIk5AOWbUwjwfqoCGwVLIotmGwq1pKpGYmatNS49uqeuFSh0ZWiXUYrzKGpQV-FDHGaycQdAAtp1B3D11-wBfgbaQP9Lph7_hJwr8pXddbomBklLiqAz2tFgrxghgwdA-AB8zgxivCo9FFLRpJYZto4034NijplduqUMBEEbfXafpJos3kgwfYh2cwh-wmFEl7Nk-mn-Pu5J4Wxk1C897xgAA"	string
- {Microsoft.Playwright.BrowserContextCookiesResult}	Microsoft.Playwright.BrowserContextCookiesResult
		Domain		".databridge.galactica1.com"										string
		Expires		-1																	float
		HttpOnly	true																bool
		Name		"ARRAffinity"														string
		Path		"/"																	string
		SameSite	Lax																	Microsoft.Playwright.SameSiteAttribute
		Secure		true																bool
		Value		"c0e387a9d75451638362e4ef14c9be275e10819d07aa85f1e7acbce9f4886bd9"	string

**Comment by RuanAlesi** [comment]
If you see this button on the page, means the logging has failed 
![image](https://user-images.githubusercontent.com/64651136/215742754-bfe7e34d-77ba-40df-bbfe-305858c5b840.png)

**Comment by RuanAlesi** [comment]
A small experiment:
- After the logging has succeeded, I extracted the state from Chromium context (via `await page.Context.StorageStateAsync();` and create new contexts inputting that state (BrowserNewContextOptions.StorageState):
- Using Firefox to access the portal, the user is already logged in;
- Using Webkit I have the same anomaly

**Comment by yury-s** [comment]
I don't what the expectations of the backend are regarding the cookies and wether it supports reusing the cookies between browsers but in general I'd not rely on that. I can dump the cookies as well, but we don't know what the logic of your application is, and as far as I can tell all 4 cookies are present in the cookie jar in webkit, I don't think it is a cookie problem per se but rather has something to do with the logic of your app. Maybe there is a race condition, maybe it's an actual problem in the webkit stack  based on the information it is hard to tell. We need a minimal repro which reveals the problem, otherwise we can't act on this.


Running the following test I suspect the problem has something to do with handling of `.DataBridge.SharedCookie` but the cookie itself is there as far as I can tell.

```js
// import { test, expect, request } from '@playwright/test';
import { expect, request, test, ConsoleMessage } from '@playwright/test';


test("testing", async ({ page }) => {
	page.on('response', async r => {
		const headers = await r.allHeaders();
		if (headers['set-cookie'])
		  console.log('\n' + r.status() + ' ' + r.url() + '  => ' +  headers['set-cookie'])
	});
	await page.goto("https://databridge.galactica1.com/");
	await page.locator("[id='btn-local']").click();
	await page.locator("[id='email-address']").type("first.accesses.2@gmail.com");
	await page.locator("[id='password']").type("@Test123");
  // {
	// 	const cookies = await page.context().cookies();
	//   console.log(cookies.map(c => c.name + '  sameSite: ' + c.sameSite));
  // }	
	await page.locator("[id='login-submit']").click();
	await page.waitForSelector("a[href='/Account']");
	// await page.context().storageState({path: 'state.json'});
	var expectedComponent = page.locator("a[href='/Account']");
	expect(await expectedComponent.isVisible());
  // {
	// 	const cookies = await page.context().cookies();
	//   console.log(cookies.map(c => c.name + '  sameSite: ' + c.sameSite));
  // }	
  // const cookies = await page.context().cookies();
	// console.log(cookies);
});

```

> If you see this button on the page, means the logging has failed

Like I said we don't know the logic of your app behind this button. We'll need a minimal repro that we can run locally to act on this.

**Comment by RuanAlesi** [comment]
> maybe it's an actual problem in the webkit stack based on the information it is hard to tell. We need a minimal repro which reveals the problem, otherwise we can't act on this.

Well, the thing is it was working on the previous Webkit build 1630

> but the cookie itself is there as far as I can tell

Not exactly, the websocket request _blazor doesn't bear the cookies (which it's a different behaviour from the mentioned previous build):
![image](https://user-images.githubusercontent.com/64651136/215994398-c56dd8ef-e793-4ec2-92cb-5ad4d461be7d.png)

> Like I said we don't know the logic of your app behind this button

The button is not important, it's just an visual evidence that the user isn't logged in

**Comment by yury-s** [comment]
> Not exactly, the websocket request _blazor doesn't bear the cookies (which it's a different behaviour from the mentioned previous build):

Ok, it's websocket-speicific issue on windows. @mxschmitt has a test that fails on webkit win because a cookie is not sent along with a websocket request.

**Comment by mxschmitt** [comment]
Internal investigation note:

The bug is here: https://github.com/WebKit/WebKit/blob/1e74777056c56506dc7ac1ff1015959b98295301/Source/WebCore/platform/network/curl/NetworkStorageSessionCurl.cpp#L61

There is also an upstream TODO comment: https://github.com/WebKit/WebKit/blob/main/Source/WebCore/platform/network/curl/NetworkStorageSessionCurl.cpp#L140

Making this change makes your test above pass and your website work.
