### ISSUE TITLE
[BUG] toBeVisible() is timing out and not working as expected

### ISSUE THREAD

**Issue by pamelaabreu** [microsoft/playwright#20377]
**Context:**
- Playwright Version: "@playwright/test": "^1.25.1"
- Operating System: Mac
- Node.js version: v14.17.
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**
```javascript
// This doesn't work
test("Test 2: Verify headline is visible", async () => {
    const pageTitle = await page.getByTestId('headline');
    await expect(pageTitle).toBeVisible();
});

// This works
test("Test 1: Verify headline is visible", async () => {
    const pageTitle = await page.getByTestId('headline').innerText();
    await expect(pageTitle).toContain('Hello World!');
});
```

**Describe the bug**
Test 2 is failing due to timing out waiting for the element to be visible `toBeVisible`

Error output:
```
Error: Timed out 5000ms waiting for expect(received).toBeVisible()
Call log:
  - expect.toBeVisible with timeout 5000ms
  - waiting for getByTestId('headline')

```

At the moment, I can't upgrade to the latest version of playwright, so what can I do make the failing test pass? Side note: sometimes the Test 2 passes if I run it in headed mode using vscode extension, but it always fails in headless mode. Any help would be much appreciated!

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. Source code, target page, expected and actual results.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.
