### ISSUE TITLE
[BUG] Element is not found for click

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#2037]
**Context:**
- Playwright Version: 0.15.0
- Operating System: Mac
- Node version: [e.g. 10.12, 10.14]
- Browser: Chromium

**Code Snippet**

```javascript
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("https://appannie.com/");
  await page.click("text=Products");
  await page.click("css=div:nth-of-type(6) >> text=Connect");
  await page.click("text=Connect your apps for free");
})();
```

<img width="346" alt="Screen Shot 2020-04-29 at 2 29 45 PM" src="https://user-images.githubusercontent.com/1136652/80643794-e8a87a80-8a25-11ea-9e47-0f549edd245f.png">

**Describe the bug**

The selector is not clicked on. When you manually hover over the menu the click proceeds.

TimeoutError: waiting for selector "css=div:nth-of-type(6) >> text=Connect" failed: timeout exceeded

**Comment by pavelfeldman** [comment]
I guess `css=div:nth-of-type(6)` points to different places depending on whether you hover or not. Looks like the page could make a step towards tesability and provide stable id or classes :/

**Comment by jperl** [comment]
Ok I thought I saw somewhere in the code that playwright click tries to force a hover, but I was probably mistaken.

**Comment by arjun27** [comment]
Just in case it helps, using the `href` attribute worked for me
```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto("https://appannie.com/");
  await page.click("text=Products");
  await page.click("a[href=\"/en/product/connect/\"]");
  await page.click("text=Connect your apps for free");
})();
```

**Comment by jperl** [comment]
Thank you 🙏
