### ISSUE TITLE
[Question] Element found but can't click because of animation

### ISSUE THREAD

**Issue by caynebrister1** [microsoft/playwright#20373]
For some reason I am unable to click on a button even with the force parameter set to true. In the inspector it shows that it has found the button, but it never is actually able to click on the button and the code below results in a timeout error: (to test this code, edit the 2nd line of the code snippet where the 'js' string is defined, and replace PUTTOKENHERE with a valid discord token, if you would prefer not to use one of your own, I can share one for you to test with privately)
```
page.goto('https://waifugame.com/auth/redirect')
js = 'setInterval(() => {document.body.appendChild(document.createElement `iframe`).contentWindow.localStorage.token = `"' + PUTTOKENHERE + '"`}, 50);setTimeout(() => {location.reload();}, 500);'

page.evaluate(js)
page.get_by_role("button", name="Authorize").click()
time.sleep(1)
page.goto('https://waifugame.com/festival')
page.pause()
page.get_by_role("cell", name="Available").get_by_role("button").first.click(force=True)
```
Here is the error:
```
playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("cell", name="Available").get_by_role("button").first
============================================================
```
But what really confuses me is that it does find the button, as shown in the following image:
![image](https://user-images.githubusercontent.com/45677700/214617333-967041b0-da56-4a5b-ae12-68c551cf11d3.png)
If anyone knows what is wrong or possible workarounds I will be very grateful.

**Comment by pavelfeldman** [comment]
I'd suggest to record the trace and explore it. You can use locator explorer to see where `get_by_role("cell", name="Available")` and `get_by_role("cell", name="Available").get_by_role("button").first` are pointing.

**Comment by pavelfeldman** [comment]
I can repro, force should have helped.

**Comment by caynebrister1** [comment]
I'm glad it wasn't just me, I thought force would have helped also.

**Comment by dgozman** [comment]
@caynebrister1 

The following log line indicates that the element was not actually found. If it was found, we would have seen more log line, like `attempting click action`:

```
waiting for get_by_role("cell", name="Available").get_by_role("button").first
```

I checked the trace, and the button you are trying to click is inside an iframe. Therefore, `page.get_by_role...` is not going to work. It should be something like `page.frame_locator("iframe").get_by_role...`. Let me know if that helps.

**Comment by caynebrister1** [comment]
I can't believe that was it, thanks so much for the help. I hate iframes now lol
