### ISSUE TITLE
[Question] saving har file to each run output dir

### ISSUE THREAD

**Issue by kchen-sf** [microsoft/playwright#20382]
Currently when using playwright/test to write tests, browser context only takes a path for recordHar. When you run multiple iterations with repeatEach, the har files get overridden, is it possible to specify a dir instead or set the browser context that already gets generated from the test fixture to save it in a particular folder? I'm currently not creating contexts manually in hopes to leverage the test fixture

**Comment by pavelfeldman** [comment]
You should use https://playwright.dev/docs/next/api/class-testinfo#test-info-output-path to build your har path. That way it is stored in a test-specific folder and does not clash.

**Comment by kchen-sf** [comment]
My issue is that i want to use the global config to specify the output dir like this for example
```javascript
const { defineConfig } = require('@playwright/test');

module.exports = defineConfig({
  repeatEach: 2,
  outputDir: 'results',
  use: {
    headless: false,
    trace: 'on',
    contextOptions: {
      recordHar: {
        path: 'results/{test output dir}/example.har',
      }
    }
  }
});
```
so that ideally it saves under these two folders for 2 runs
results/test-run
results/test-run-repeat1

but since test output dir can't be created in the global config file, if i just set the path to be something like `results/example.har` i'll only get 1 har instead of 2 for 2 runs (or more if you increase repeatEach).

if i don't use the config i can get away with a fixture like this
```javascript
auto: [async ({ page, browser, context }, use, testInfo) => {
    // update har ouput path to be the testinfo output to protect from files being overwritten
    const harOpts = {
      path: testInfo.outputPath('har.har'),
      content: undefined,
      urlGlob: undefined,
      urlRegexSource: undefined,
      urlRegexFlags: undefined,
      mode: undefined
    }
    context._options.recordHar = harOpts;
    context._harRecorders.set('', harOpts)
    await use();
  }, { auto: true }],
```
but it seems cleaner to be able to specify everything in the config rather than half in a config and half in a fixture

**Comment by pavelfeldman** [comment]
> so that ideally it saves under these two folders for 2 runs
results/test-run
results/test-run-repeat1

That is what it does if you use the recommended method above.

**Comment by kchen-sf** [comment]
right, but the current way i'm doing it is with the two code snippets i've pasted because i'm using the global config and having the test fixture create the browser context for me, and as a result i have to manually set the recordHar and harRecorders, this doesn't seem ideal.

i guess my other question would be is there a different way to record the har? i've only seen examples with creating a new browser context like this
```javascript
const context = await browser.newContext({
  recordHar: { path: 'example.har', urlFilter: '**/api/**' }
});
```
but i'm not looking to create a new context since i'm relying on using `@playwright/test`

**Comment by pavelfeldman** [comment]
I think I got it, thank you for your patience! I'm not sure we have a solution for you, but let me think.

**Comment by pavelfeldman** [comment]
The workaround for you would be:

```js
// fixtures.ts
import { test as base } from '@playwright/test';
const test = base.extend({
  contextOptions: async ({ contextOptions }, use, testInfo) => {
    const path = testInfo.outputPath('out.har');
    await use({ ...contextOptions, recordHar: { path } });
  },
});

export { test };
```

**Comment by kchen-sf** [comment]
this works! thanks for your help
