### ISSUE TITLE
[Question] toBeVisible fails on horizontal line

### ISSUE THREAD

**Issue by darabos** [microsoft/playwright#20389]
I'm making some assertions about a dynamically generated SVG. It has some lines. When a line is horizontal, `toBeVisible` fails. I suspect the bounding box has basically zero area in this case. It's probably the same for vertical lines, but I don't have any.

This is such a corner case. I don't think it deserves a technical solution in Playwright. But maybe you can recommend a workaround? Thanks for any tips!

**Comment by pavelfeldman** [comment]
Nothing on top of my head, you can check for the element to be attached if you are certain it is visible (enclosing div is visible). See https://playwright.dev/docs/next/api/class-locator#locator-wait-for.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
