### ISSUE TITLE
[Question] How to run all spec files in all browsers except one, which should only be run Chrome?

### ISSUE THREAD

**Issue by gineanne** [microsoft/playwright#20385]
Here is my playwright config.
`
import { devices, PlaywrightTestConfig } from '@playwright/test';

const playwright: PlaywrightTestConfig = {
    testDir: '../../tests',
    workers: 1,
    retries: 0,
    timeout: 120000,
    maxFailures: 20,
    globalSetup: require.resolve('../setup/global-setup'),
    use: {
        trace: 'retain-on-failure',
        screenshot: 'only-on-failure',
        video: 'on'
    },
    reporter: [['list'], ['html', { open: 'always' }]],
    projects: [
        {
            name: 'ExtraLargeDesktop_Firefox',
            use: {
                ...devices['Desktop Firefox'],
                browserName: 'firefox'
            },
        },
        
        {
            name: 'ExtraLargeDesktop_Safari',
            use: {
                ...devices['Desktop Safari'],
                browserName: 'webkit'
            },
        },

        {
            name: 'ExtraLargeDesktop_Chrome',
            use: {
                ...devices['Desktop Chrome'],
                browserName: 'chromium'
            },
        },

        {
            name: 'ExtraLargeDesktop_Edge',
            use: {
                ...devices['Desktop Edge'],
                browserName: 'chromium'
            },
        },

        {
            name: 'LargeDesktopMobile',
            use: {
                ...devices['Galaxy Tab S4 landscape'],
                browserName: 'chromium'
            },

        },

        {
            name: 'MediumDesktopMobile',
            use: {
                ...devices['iPad Mini'],
                browserName: 'webkit'
            },
        },

        {
            name: 'SmallMobile_Galaxy',
            use: {
                ...devices['Galaxy Tab S4'],
                browserName: 'chromium'
            },
        },

        //mobile
        {
            name: 'ExtraSmallMobile_Galaxy',
            use: {
                ...devices['Galaxy S9+'], //320
                browserName: 'chromium'
            },
        },

        {
            name: 'ExtraSmallMobile_iPhone',
            use: {
                ...devices['iPhone X'], //375
                browserName: 'webkit'
            },
        },
    ]
};

export default playwright;`

**Comment by pavelfeldman** [comment]
Do you mean once or do you want to permanently exclude this test for that browser?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by massimopalmieri** [comment]
@gineanne did you find a solution to this? I'm also trying to do the same thing. 
@pavelfeldman I believe the question is about permanently running a test only on a specific browser

**Comment by gineanne** [comment]
@massimopalmieri I put a condition in the test to skip to that specific browser.
![image](https://user-images.githubusercontent.com/21330975/225264818-9afce35b-8b4c-4f70-948c-5ca99e594b74.png)
