### ISSUE TITLE
[BUG] Test execution gets stuck when running through Playwright extension in Vscode

### ISSUE THREAD

**Issue by denys-vowel** [microsoft/playwright#20399]
**Context:**
- Playwright Version: 1.30.0
- Playwright Test for VSCode 1.0.6
- Operating System: Mac
- Node.js version: v16.15.0
- Browser: Chromium

**Code Snippet**

Test:

```javascript
import { test, chromium } from '@playwright/test';
import path from 'path';

test('Reproduce defect', async function ({ page }) {
  await page.goto('https://google.com');

  const browser = await chromium.launch({
    headless: false,
    args: [
      '--use-fake-device-for-media-stream',
      '--use-fake-ui-for-media-stream'
    ],
  });
  const context = await browser.newContext();
  const pageNewContext = await context.newPage();

  await pageNewContext.goto('https://www.microsoft.com');
});
```

Playwright config:
```javascript
import { type PlaywrightTestConfig } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

const config: PlaywrightTestConfig = {
  name: 'tests',
  use: {
    ignoreHTTPSErrors: true,
    acceptDownloads: true,
    headless: true,
    viewport: { width: 1280, height: 720 },
  },
  testDir: 'test/tests/',
  reporter: [['list'], ['html']],
  reportSlowTests: null,
  timeout: 200_000,
};

export default config;

```

**Describe the bug**

When I run this test through Playwright extension in Vscode test execution gets stuck on await chromium.launch(). 
<img width="1246" alt="Screenshot 2023-01-26 at 17 28 18" src="https://user-images.githubusercontent.com/109543305/214876915-5b738f8b-beb3-4a5b-9b70-60f1e907497d.png">

But when I run it through: **_playwright test --grep 'Reproduce defect'_** the test works as expected and opens new chromium inside the test

**Comment by pavelfeldman** [comment]
You seem to be creating a brand new browser when you already have a browser with an opened page created for you by the test harness. You might want to specify the launch arguments in the playwright config and just use the provided page.

**Comment by denys-vowel** [comment]
> You seem to be creating a brand new browser when you already have a browser with an opened page created for you by the test harness. You might want to specify the launch arguments in the playwright config and just use the provided page.

I test webrtc application. In my scenarios I need to have one browser with default args (defined in playwright.config) and one more with another args to define another audio/media streams etc. 
So to run new context with args I can only use await chromium.launch() according to documentation and it doesn't work with Playwright extension.

**Comment by pavelfeldman** [comment]
Do you have a `Show browser` setting checked in the Testing panel?

**Comment by denys-vowel** [comment]
Yes.
But it gets stuck in all combinations: when "Show browser" is checked/unchecked and when I pass "headless: false/true" in chromium.launch().

**Comment by raulparada** [comment]
For whoever has the same issue and doesn't mind the downgrade, version `0.2.10` handles this correctly. Looking forward to the fix though :) thank you!

**Comment by pavelfeldman** [comment]
Ok, trying to reproduce this, but things work for me. Created a new project with these files and things work. Note though that your config is broken - it has malformed ternary operator as a reporter value.

**Comment by denys-vowel** [comment]
Yes, there was a mistake in config. I fixed it.
I also tried to reproduce in new project and looks like the issue is not reproducible with unchecked "Show browser" checkbox. But it was reproducible with checked "Show browser".
You can try to run with checked/unchecked "Show browser". I am pretty sure that it should be reproduced
