### ISSUE TITLE
[Question] Runner class instance for controlled test flow

### ISSUE THREAD

**Issue by NachSM** [microsoft/playwright#20395]
Hello everyone,

I have a question regarding the Playwright Test Runner, due to a migration from Jasmine Runner to Playwright Runner.

The entry point of our projects is a "project.runner.ts" file that controls the test flow by instantiating the Jasmine runner class. We first importing the jasmine module ("const Jasmine = require('jasmine');" and then we create an instance "const jasmine = new Jasmine();" which we can use to configure and run the tests with specific jasmine functions like "jasmine.loadConfig(jasmineDefaultConfig);" or  "jasmine.execute();"

Is there any way to run the tests through a Playwright Runner class that offers this kind of functionality? As far as I can see in the documentation, the way to run the tests is simply by running the command "npx playwright test".

We would need this primarily because we have our own reporter that gathers the tests information through this Jasmine Runner instance.

If I can bring any more information on the subject please let me know.

Thanks in advance.

**Comment by pavelfeldman** [comment]
No such feature, but you can define your own reporter in the playwright config.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/7275.
