### ISSUE TITLE
[Question] Retrieve text in specific td from table

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20394]
Hello team,

I would like to retrieve all the texts of a table specific column and add them in an array.

HTML code is the following :

``<div _ngcontent-itg-c113="" id="dih-rules-table" class="dih-rules-table">& ``
 ``    <table _ngcontent-itg-c113="" class="table table-hover">& ``
 ``        <tbody _ngcontent-itg-c113="" id="dih-rules-table-123456789" class="ng-star-inserted">& ``
  ``           <tr _ngcontent-itg-c113="" data-cy="rules-rule-row">& ``
  ``                   <td _ngcontent-itg-c113="" class="df-font-weight-semi-bold" title="6X STAR CPR">6X STAR CPR</td>& ``
  ``                   <td _ngcontent-itg-c113="" title="Trigger rule when the the xxx is created and there is at least one FF linked to ``  ``the segment that is actively synchronised.">Trigger rule when the the xxx is created and there is at least one FF linked to the ``  ``segment that is actively synchronised.</td>& ``
 ``                    <td _ngcontent-itg-c113="" data-cy="lastActivity" title="Created by xxxx on Jan 25, 2023, 5:10 PM, Last change ``  ``by xxxx on Jan 25, 2023, 5:10 PM">25JAN23</td>& ``
 ``                </tr><!----><!---->& ``
  ``       </tbody>&``

What I would like to retrieve is the text "6X STAR CPR" for each of the body items (I've shown only here but there are several of them).
I've tried this code to at least try on the first item but it does not return anything :

  const row = this.page.locator('table.table table-hover tbody[id="dih-rules-table-123456789"]')
    const rowTexts = await row.locator(':scope').allInnerTexts()
    await rowTexts.forEach((text) => {
      console.log(text)
    })

This as well is not working : console.log (row.nth(1).allInnerTexts)

I guess I'm not pointing to the good selector.

Could you please help ?

Thank you in advance, 

Regards,

Johan

**Comment by pavelfeldman** [comment]
Please refer to our locators documentation at https://playwright.dev/docs/next/locators, and you can also use codegen to generate selectors, see https://playwright.dev/docs/next/codegen-intro.

**Comment by MehseinJohan** [comment]
Hello Pavel, I'm afraid use of selectors won't help me for this one. I just wanted to see where my code fails, as I need to parse the HTML code...
