### ISSUE TITLE
[BUG] electron in Jest: failed to launch

### ISSUE THREAD

**Issue by MatthijsBurgh** [microsoft/playwright#20407]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Ubuntu 22.04
- Node.js version: 16.18.1
- Browser: Electron
- Extra: Jest

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
app = await _electron.launch({args: ["mainFile"], executablePath: "EXEC_PATH"})
```

**Describe the bug**
When running this in plain node, I don't have any issue. When running this inside a `jest` test environment I get:
`electron.launch: Process failed to launch!`. I do not get any additional logs for now.

**Comment by pavelfeldman** [comment]
If it works outside of Jest, I'd be looking in the Jest direction, I don't think we can help here. Looks like we can't locate and/or run the main executable.

**Comment by MatthijsBurgh** [comment]
I provide the full paths, so the issue isn't in any path resolving.

**Comment by MatthijsBurgh** [comment]
I will try to get some more logging.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it. If we can repro it locally, we will be able to fix!
