### ISSUE TITLE
[BUG] "page.goto: Target page has been closed" when re-using browser in VSCode

### ISSUE THREAD

**Issue by jonas-jonas** [microsoft/playwright#20409]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.30.0
- Operating System: [e.g. Windows, Linux or Mac] MacOS
- Node.js version: [e.g. 12.22, 14.6] 16.18.1
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment] VS Code v1.74.3 and PW for VS Code v1.0.6

Set `"playwright.reuseBrowser": true` in your VS Code config.

Start the test from VS Code.

**Code Snippet**

```ts
import { Page, test as base } from "@playwright/test";

const test = base.extend<{ loggedInPage: Page }>({
  loggedInPage: async ({ browser }, use) => {
    const page = await browser.newPage();
    // Login logic on the page object

    await use(page);

    await page.close();
  },
});

test("fails", async ({ loggedInPage, page }) => {
  await page.goto("https://playwright.dev/");
  // this fails with "page.goto: Target page, context or browser has been closed"
  await loggedInPage.goto("https://playwright.dev/");
});

// Note the reversed order of the fixtures
test("passes", async ({ page, loggedInPage }) => {
  await page.goto("https://playwright.dev/");
  await loggedInPage.goto("https://playwright.dev/");
});

```

**Describe the bug**

When using the `re-use browser` config option in VS Code, and using both the built-in `page` or  `context` fixtures and a custom defined `Page` fixture (via `browser.newPage()`) in a test case, the custom page is closed before the test case starts executing. 

This is probably due to https://github.com/microsoft/playwright/commit/412c11db208da0543137ac781e775578a72eaece as all browser contexts are closed, before the new one is created.

**Comment by pavelfeldman** [comment]
We should fix it. As a workaround, can you try swapping the order of declarations to be `{ page, loggedInPage }`? Also, you are using browser.newPage, while you probably want context.newPage for them to be in the same context.

This custom login page will anyways be closed and reopened because the dev mode is optimized for SPAs.

**Comment by jonas-jonas** [comment]
>can you try swapping the order of declarations to be { page, loggedInPage }?

Yes, that passes. I have turned off `re-use browser` for now (see the second test case from above), which is fine for me.

> Also, you are using browser.newPage, while you probably want context.newPage for them to be in the same context.

We need to have separate browser contexts, because we don't want to share the storage state (cookies). AFAICT, `context.newPage` would still share the cookies, right? I might be wrong on that.

**Comment by pavelfeldman** [comment]
> We need to have separate browser contexts, because we don't want to share the storage state (cookies). AFAICT, context.newPage would still share the cookies, right? I might be wrong on that.

Yes, you are good then.

**Comment by jonas-jonas** [comment]
>Yes, you are good then.

Thanks for the confirmation :)

I'd be happy to try my hand on a fix/PR, if no one has started work on this yet. Let me know if there is anything I'd need to take into account here.
