### ISSUE TITLE
[BUG] Iframe freezes Playwright execution.

### ISSUE THREAD

**Issue by BCGST** [microsoft/playwright#20408]
**Context:**
- Playwright Version: v1.30.0
- Operating System: Windows
- Node.js version: Reproduced in "Try Playwright"
- Browser: Firefox and Chrome
- Extra: Originally found running Browser Library RF tool but reproducible in "Try Playwright"

**Code Snippet**

https://try.playwright.tech/?l=javascript&s=j7pry4z

```javascript
// @ts-check
const playwright = require('playwright');

(async () => {
  // Try to add 'playwright.firefox' to the list ↓
  for (const browserType of [playwright.chromium, playwright.webkit]) {
    const browser = await browserType.launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('https://demos.telerik.com/aspnet-ajax/editor/examples/overview/defaultcs.aspx');
    await page.screenshot({ path: `example-${browserType.name()}.png` });
    console.log(await page.frameLocator('id=ctl00_ContentPlaceholder1_RadEditor1_contentIframe').locator('h1').innerText())

    await browser.close();
  }
})();
```

**Describe the bug**

This is a rich text editor that is implemented in a project I test. Interacting with the iframe causes most Playwright actions performed on it to freezeup. The iframe appears in the HTML as follows:
`<iframe frameborder="0" src="javascript:'<html></html>';" id="ctl00_ContentPlaceholder1_RadEditor1_contentIframe" title="Rich text editor with ID ctl00_ContentPlaceholder1_RadEditor1" style="width: 100%; height: 100%; margin: 0px; padding: 0px;">Your browser does not support inline frames or is currently configured not to display inline frames.</iframe>`
And people I have discussed this bug with indicate that this portion `src="javascript:'<html></html>';"` might be causing some of the problem though I am not particularly well versed in javascript myself.

**Comment by pavelfeldman** [comment]
I can repro, it might be due to the `src="javascript:'<html></html>';"  construct on the iframe that might be confusing the frame lifetime events. The main / utility contexts are not created/reported for the frame.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/8943
