### ISSUE TITLE
How to turn off ansi/console text color in v1.30.0?

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#20400]
Playwright version (nodejs): 1.30.0
I have the following code to turn off ansi color based on conversation from [here](https://github.com/microsoft/playwright/issues/13522#issuecomment-1098377505):
```
process.env.FORCE_COLOR = 'false';

class CustomReporter implements Reporter {
//...
```

But I'm still seeing ansi color in the output. Eg:
```
Expected substring: [32m"hello"[39m
Received string:    [31m"bye"[39m
    at ...
```

This used to work in v1.29.1. Is there a new way in v1.30 to turn this off?

**Comment by pavelfeldman** [comment]
```js
const ansiRegex = new RegExp('[\\u001B\\u009B][[\\]()#;?]*(?:(?:(?:[a-zA-Z\\d]*(?:;[-a-zA-Z\\d\\/#&.:=?%@~_]*)*)?\\u0007)|(?:(?:\\d{1,4}(?:;\\d{0,4})*)?[\\dA-PR-TZcf-ntqry=><~]))', 'g');
export function stripAnsi(str: string): string {
  return str.replace(ansiRegex, '');
}
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
