### ISSUE TITLE
[BUG]: Mismatched versions due to `playwright install` in workflow file

### ISSUE THREAD

**Issue by NashJames** [microsoft/playwright#20415]
**Context:**
- Playwright Version: 1.29.2
- Operating System: WSL
- Node.js version: 16
- Browser: All

**Describe the bug**

```
╔════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test integrity check failed:                                                                ║
║ You have @playwright/test version '1.29.2' and 'playwright' version '1.30.0' installed!                ║
║ You probably added 'playwright' into your package.json by accident, remove it and re-run 'npm install' ║
╚════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

I setup Playwright a short while ago, but I'm just beginning to write the initial tests for a project, so the workflow has been failing for some time. I just noticed the above error, you should be able to see it [here](https://github.com/NashJames/Holocron.io/actions/runs/4018214633/jobs/6903553551).

My [pnpm-lock.yaml](https://github.com/NashJames/Holocron.io/blob/main/pnpm-lock.yaml) doesn't contain any mention of playwright. The `1.30.0` is coming from the `pnpm dlx playwright install --with-deps chromium firefox webkit chrome msedge` command in the [workflow file](https://github.com/NashJames/Holocron.io/blob/main/.github/workflows/playwright.yml).

Obviously I can define the `@playwright/test` package as `"latest"` in my package.json or define a specific version to install in the workflow, but both can lead to issues in the future. I don't assume this is an intended interaction?

**Comment by pavelfeldman** [comment]
`pnpm dlx` does not respect the package version you use, `pnpm exec` would do the right thing.
