### ISSUE TITLE
The code from original docs is not working as expected.

### ISSUE THREAD

**Issue by devhiko** [microsoft/playwright#20416]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows
- Node.js version: 18.12.1
- Browser: Not Related

**Code Snippet**

```javascript
import { expect, test } from "@playwright/test";

const { describe, beforeEach, fixme } = test;

describe("navigation", () => {
  beforeEach(async ({ page, isMobile }) => {
    // This example is not working.
    fixme(isMobile, "Settings page does not work in mobile yet"); // <--- Type Signature of fixme is: (title, testFunction): void
    await page.goto("https://playwright.dev/");
  });

  test("main navigation", async ({ page }) => {
    await expect(page).toHaveURL("https://playwright.dev/");
  });
});
```
**Describe the bug**

The code at docs not working as expected. 
[link](https://playwright.dev/docs/test-annotations#use-fixme-in-beforeeach-hook)

```javascript
// example.spec.ts

test.beforeEach(async ({ page, isMobile }) => {
  test.fixme(isMobile, 'Settings page does not work in mobile yet'); // <---- HERE

  await page.goto('http://localhost:3000/settings');
});

test('user profile', async ({ page }) => {
  await page.getByText('My Profile').click();
  // ...
});
```

**Comment by pavelfeldman** [comment]
There are 4 fixme overloads and one of them is of the type (condition: boolean, message: string).

**Comment by devhiko** [comment]
Yes, says “No overload matches this call.Overload 1 of 4, '(title: string, testFunction: (args: PlaywrightTestArgs & PlaywrightTestOptions & PlaywrightWorkerArgs & PlaywrightWorkerOptions, testInfo: TestInfo) => void | Promise<...>): void', gave the following error.Argument of type 'boolean | undefined' is not assignable to parameter of type 'string'.Type 'undefined' is not assignable to type 'string'.Overload 2 of 4, '(condition: boolean, description?: string | undefined): void', gave the following error.Argument of type 'boolean | undefined' is not assignable to parameter of type 'boolean'.Type 'undefined' is not assignable to type 'boolean'.Overload 3 of 4, '(callback: (args: PlaywrightTestArgs & PlaywrightTestOptions & PlaywrightWorkerArgs & PlaywrightWorkerOptions) => boolean, description?: string | undefined): void', gave the following error.Argument of type 'boolean | undefined' is not assignable to parameter of type '(args: PlaywrightTestArgs & PlaywrightTestOptions & PlaywrightWorkerArgs & PlaywrightWorkerOptions) => boolean'.Type 'undefined' is not assignable to type '(args: PlaywrightTestArgs & PlaywrightTestOptions & PlaywrightWorkerArgs & PlaywrightWorkerOptions) => boolean'.ts(2769)” Windows için Posta ile gönderildi Kimden: Pavel FeldmanGönderilme: 26 Ocak 2023 Perşembe 23:10Kime: microsoft/playwrightBilgi: Hikmet; AuthorKonu: Re: [microsoft/playwright] The code from original docs is not working as expected. (Issue #20416) There are 4 fixme overloads and one of them is of the type (condition: boolean, message: string).—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
