### ISSUE TITLE
[QUESTION] - Workers

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#20417]
Hi there. I am running my tests on Azure DevOps  using ubuntu 20.04 as a vmImage pool.

The tests are executed in the Playwright Docker Image and workers are set as "undefined" in the global config when running on CI.

I've seen it always run only 1 worker, is there any recommendation for the numbers of workers when using playwright focal docker image ?
I know I can increase the number of workers from the project, but thought Playwright will pick the correct amount when set as undefined. Is 1 the best option when running on Playwright Docker Image ?

Thank you!

**Comment by pavelfeldman** [comment]
We recommend 50% as a sensible default value: https://playwright.dev/docs/next/api/class-testconfig#test-config-workers. So if you have a 4 core machine, you can set it to 2 (or keep defaults).

**Comment by imartinflores** [comment]
Thanks @pavelfeldman ! Will give it a try Tomorrow!
