### ISSUE TITLE
[BUG] Cookies are randomly not applied

### ISSUE THREAD

**Issue by mtt87** [microsoft/playwright#20419]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux 
- Node.js version: [e.g. 12.22, 14.6] not sure, the one bundled with the latest 1.30 Playwright docker image
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: it's a CI environment so I don't have a lot of info

**Code Snippet**

```javascript
// utils.ts
export async function getBrowserContextWithAuth(browser: Browser) {
  const cookies = [
    {
      name: 'auth_cookie'
      value: authCookieValue,
      path: '/',
      domain: '.example.com',
      secure: true,
      httpOnly: true
    }
  ];
  const browserContext = await browser.newContext();
  await browserContext.addCookies(cookies);

  return browserContext;
}

// Test.spec.ts
test('Should work', async ({ browser }) => {
    const browserContext = await getBrowserContextWithAuth(browser);
    const page = await browserContext.newPage();
    await page.goto('/something')
})
```

**Describe the bug**

I would say it happens ~5-10% of the times that cookies are not applied at all.
I download the `playwright-report` folder and look at the stack traces and I can see that the cookie header is completely missing from the request.
It's quite random that in a test suite of 10 tests only 1 would fail. The code is the same for all of them, I reuse this function to generate a browser context that has the authenticated cookie.

**Comment by pavelfeldman** [comment]
We would need a snippet we can use to reproduce locally. Note that you are leaking the contexts and pages, it is better to do:

```js
test('Should work', async ({ context, page }) => {
    await addAuthCookies(context);
    await page.goto('/something')
})
```

**Comment by mtt87** [comment]
Thank you! Since it's so random I will actually follow your better approach and if the problem persist I will re-open the issue.

**Comment by rostislav-simonik-plc** [comment]
@pavelfeldman could you elaborate little bit the leakage, we are doing the same. Do i understand correctly that we need to close context and page explicitly if it's created that way ?
