### ISSUE TITLE
can not check url of new tab in headless mode - chromium

### ISSUE THREAD

**Issue by joelneubert** [microsoft/playwright#20427]
## System:
 - OS: macOS 12.2.1
## Binaries:
 - Node: 18.12.1 - ~/.nvm/versions/node/v18.12.1/bin/node
 - npm: 8.19.3 - ~/.nvm/versions/node/v18.12.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: - 1.29.2
## browser: 
- chromium
-

**Code Snippet**

```
import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://cpw.state.co.us/thingstodo/Pages/BigGame.aspx');
  const [ newPage ] = await Promise.all([
    page.waitForEvent('popup'),
    await page.getByRole('link', {name: 'Big Game Hunting Planner cover'}).click()
  ])
  
  console.log(newPage.url())
  await newPage.waitForURL('**/*.pdf', { timeout: 5000 } )
  await newPage.close()
});
```

**Describe the bug**

When I run the above code it fails only on chromium. I have a similar use case in the application I'm testing, but it can be publicly recreated.

**Comment by pavelfeldman** [comment]
Headed and headless Chromium handle PDFs differently: one downloads them and another opens the pdf viewer. See https://github.com/microsoft/playwright/issues/6342 for a snippet you can use to handle it.

**Comment by joelneubert** [comment]
@pavelfeldman I don't believe that's accurate as in my use case it's always opened in a new tab. I can see this in the

**Comment by joelneubert** [comment]
With a default config you can see the different behavior with the code I attached running `npx playwright test --headed` vs `npx playwright test`, with the standard generated config.

**Comment by pavelfeldman** [comment]
I stand by my assessment: in headless mode, the file is downloaded, no tabs are opened, hence your code hangs. In headed mode, the new tab is opened with the pdf viewer, which is not a web page, it is a native control, so it is naturally missing the URL. The [comment](https://github.com/microsoft/playwright/issues/6342#issuecomment-929112605) in the issue I linked suggests how those should be handled.

**Comment by joelneubert** [comment]
I can investigate that as an option, but the later [comment](https://github.com/microsoft/playwright/issues/6342#issuecomment-929183546) seems to have a more dismal outlook on this particular use case. Where we'd want to check a url path in particular scenarios. Sounds like that's impossible in chromium headless.
