### ISSUE TITLE
[BUG] Locator can't find element although it's present in the "after" of the previous step

### ISSUE THREAD

**Issue by mtt87** [microsoft/playwright#20426]
**Context:**
- Playwright Version: 1.30
- Operating System: Linux (CI container)
- Node.js version: [e.g. 12.22, 14.6] the one bundled with docker playwright official image 1.30-focal
- Browser: [e.g. All, Chromium, Firefox, WebKit] Only on Safari
- Extra: [any specific details about your environment] as mentioned it's a CI container

The problem only happens with Safari, Chrome seems to be unaffected.
This is the part of the code involved, unfortunately it's quite hard to extract a sample as it's an app not available for the public.

```javascript
const searchContainerSpinner = page.getByTestId('search-container-spinner');
// it should show the loading spinner again
await searchContainerSpinner.waitFor({
  state: 'attached'
});
```

**Describe the bug**

I have a situation where the user clicks the [Search] button and I immediately show a spinner until data is received from the server.
As you can see in this first screenshot, the `AFTER` of the clicking action, shows that there is a spinner element, and it has the `search-container-spinner` test id.
<img width="1728" alt="Screenshot 2023-01-27 at 00 03 39" src="https://user-images.githubusercontent.com/2150927/214978478-49f6c116-1ff6-4f56-b0c7-e577e27bca96.png">

In this second screenshot you can see that the `BEFORE` of the following step doesn't contain the spinner anymore so the test is timing out but the spinner was there for a fraction of a second as you can see in the `AFTER` of the previous step.
<img width="1727" alt="Screenshot 2023-01-27 at 00 03 56" src="https://user-images.githubusercontent.com/2150927/214978640-18af17c9-5c48-4130-b499-2d532f55e29f.png">

This is the error in the console
```
Test timeout of 40000ms exceeded.
locator.waitFor: Target closed
=========================== logs ===========================
waiting for getByTestId('search-container-spinner')
============================================================
  56 |     await searchFormSubmitButton.click();
  57 |     // it should show the loading spinner again
> 58 |     await searchContainerSpinner.waitFor({
     |                                  ^
  59 |       state: 'attached'
  60 |     });
```

**Comment by pavelfeldman** [comment]
```js
await searchContainerSpinner.waitFor({
  state: 'attached'
});
```

If the spinner appears and disappears immediately, Playwright can miss it - we are polling the dom state on rAF, timers, etc, depending on the use case, but none of them would be able to detect such a change.

**Comment by pavelfeldman** [comment]
Playwright does not provide wants to deterministically handle these. If spinner appears for say just one frame at 60Hz, it'll be hard to catch it. You can try injecting mutation observer into the page and registering that that exact div was visible at some time. Since this is not something user would be able to see / register, Playwright considers it out of scope as a part of the e2e testing.

**Comment by tomdelahaba** [comment]
I am facing exactly the same issue. After user performs some action (upload file, change view), I am showing a spinner for a very short time period (definitely not 1 frame at 60hz), I am literally talking about few hundred milliseconds, 200, 300 maybe 500. At some point even more (up to few seconds, mostly 2 from my attempts). Playwright is not able to catch the changes...

1 - perform action
2 - wait for spinner to appear
3 - wait for spinner to disappear
4 - continue

Application simply continues in its own flow, playwright is stuck on 2nd, waiting for the spinner to appear...

This is definitely a part of e2e testing, just imagine having an application, where you are adding a credit card. In the meantime of creating the card and sending the data to server, you want to notify the user something is going on. It does not even need too be connected to server at that point. You simply create the card in SPA app, but after proceeding from the card view (that can be a part of the main app), you change some view and in the meantime you want to notify the user "something is going on"...

**Comment by Israfel21** [comment]
I'm facing a worse situation: the item is sitting perfectly visible all the time but still Playwright can't find it. 
To make things more frustrating I try the locator thrown in the exception in the Browser and it can find the element just fine.
