### ISSUE TITLE
[BUG] "Accept" header not replacing default in SetExtraHTTPHeadersAsync

### ISSUE THREAD

**Issue by heron1** [microsoft/playwright#20439]
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Node.js version: Using .Net C# environment
- Browser: Chromium

**Code:**
```C#
Dictionary<string, string> headers = new();
headers["Accept"] = "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.8";

await using var browser = await Playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
{
	Headless = false,
});

var context = await browser.NewContextAsync();
await context.SetExtraHTTPHeadersAsync(headers);

var page = await context.NewPageAsync();

string url = "https://localhost:8000/echo";
await page.GotoAsync(url);
```

**Describe the bug**

The above test is being executed via "dotnet test" and goes to a local server I'm running that will echo back all the received headers to the client. Different header values are being successfully set (eg: User-Agent, sec-ch-ua, purpose, etc), however for some reason "Accept" is always overridden with the default chromium Accept header of: "Accept=text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7" and not the one I'm specifying in the test. It's the only header that seems to have this behaviour that I've observed.

I'm not sure if this is a bug or something I'm doing wrong, as I've only started using this framework today.

**Comment by pavelfeldman** [comment]
If your goal is to modify the existing headers rather than adding extra http headers, use request interception: https://playwright.dev/dotnet/docs/next/network#modify-requests

**Comment by heron1** [comment]
Yes that allows me to modify the Accept header, thanks

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
