### ISSUE TITLE
[Question] "TypeError: this.customTesters is not iterable for custom matcher" after update to 1.30

### ISSUE THREAD

**Issue by wbartus** [microsoft/playwright#20432]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version:18.13
- Browser: doe not apply
- Extra: this is part of test code which includes only api request, without using 'browser' object

**Code Snippet**
// playwright.config.js
import playwrightApiMatchers from "odottaa";
expect.extend(playwrightApiMatchers);
```javascript
test.only("xxxxx", async ({ request }) => {
    const response = await getUser(request);
    await expect(response).toHaveStatusCode(200);
    await expect(response).toMatchJSON({
        elementsTotal: expect.any(Number),
    });
  });
  

**Describe the bug**

This is the portion of test environment where only api requests are being sent, so no browser involved. 
1. I'm using custom matchers from "odotta" package
2. Up to this point i had  "@playwright/test": "^1.29.2"
3. After update to 1.30, I am getting i.e.
TypeError: this.customTesters is not iterable
at Object.toEqual (.../node_modules/expect/build/matchers.js:752:15)
 at Object.toHaveJSON (.../node_modules/odottaa/lib/src/index.js:48:99)
4. When I switched back to 1.29.2 it was working again, but now when I went back and forth trying to investigate, it's the same for 1.29.2

Any ideas what went wrong? I wonder why it started to act like this also with 1.29.2 when it worked with it previously. Looks like something with my environment. Any suggestions highly appreciated.

**Comment by wbartus** [comment]
I've rechecked with fresh environment. As soon as I update to1.30.0, I'm getting "TypeError: this.customTesters is not iterable for custom matcher" in i.e. at Object.toEqual (.../node_modules/expect/build/matchers.js:752:15)
Do you think it's an playwright issue or more of a package "odottaa" which introduces it's own matchers, but it's not updated to changes in playwright ?

**Comment by pavelfeldman** [comment]
Playwright does not depend on the `expect` module, it uses its own version of expect, located under node_modules/@playwright/test/lib/expectBundleImpl.js. Your error points at the module `expect` module that some other package installed and uses (odotta?).

**Comment by pavelfeldman** [comment]
The action item here would be to document `expect` and its extensibility methods and mention that `expect` module should not be used for that.
