### ISSUE TITLE
[BUG]: global-setup not working with `getByTestId` with custom value set in playwright.config

### ISSUE THREAD

**Issue by borecz** [microsoft/playwright#20444]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16
- Browser: All

I had to use other selectors to make the script within global-setup working (e.g. UI login)

Was trying to replicate this: https://playwright.dev/docs/auth#automate-logging-in

playwright.config.ts
```
globalSetup: require.resolve('./global-setup'),
...
  use: {
    ...
    testIdAttribute: 'data-mgmtautomationid',
  },
  ```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/14895.

**Comment by yairEO** [comment]
I would like to note that the official Playwright page linked in the OP's description currently does not mention `getByTestId` anywhere, which I believe to be too superficial to rely on labels and not on fixed test ids `testIdAttribute`. 

This issue still happens to me now, where `getByTestId` doesn't seem to work **only** within my global setup file:

`global-setup.ts`
```ts
import { chromium, type FullConfig } from "@playwright/test";

async function globalSetup(config: FullConfig) {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  const { baseURL, storageState } = config.projects[0].use;

  await page.goto(baseURL!);
  await page.getByTestId("username").fill("user");
  await page.getByTestId("password").fill("pass");
  await page.getByTestId("login-btn").click();

  await page.context().storageState({ path: storageState as string });
  await browser.close();

  // process.env.TOKEN = body.data.accessToken;
}

export default globalSetup;
```

`playwright.config.ts`

```ts
```
import { defineConfig, devices } from "@playwright/test";
import "dotenv/config";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  globalSetup: require.resolve("./tests/global-setup"),

  testDir: "./tests",

  /* Maximum time one test can run for. */
  timeout: 30 * 1000,

  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000,

    // toHaveScreenshot: {
    //   // An acceptable amount of pixels that could be different, unset by default.
    //   maxDiffPixels: 10,
    // },

    // toMatchSnapshot: {
    //   // An acceptable ratio of pixels that are different to the
    //   // total amount of pixels, between 0 and 1.
    //   maxDiffPixelRatio: 0.1,
    // },
  },

  /* Run tests in files in parallel */
  fullyParallel: true,

  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,

  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,

  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,

  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  // reporter: 'html',
  reporter: [
    ["dot"],
    ["line"],
    ["html", { open: "never" }],
    ["allure-playwright", { outputFolder: "./frontend/allure-results" }],
    ["junit", { outputFile: "./junit-results/results.xml" }],
  ],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    screenshot: "only-on-failure",
    // video: "on",

    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,

    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: "http://localhost:3000",

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",

    browserName: "chromium",
    headless: true,

    // the `viewport` option has a value of `null` in order to configure the `launchOptions` to have "--start-maximized"
    viewport: null,

    launchOptions: {
      // slowMo: process.env.TESTS_SLOMO ? 1_000 : 0, // slows down the tests
      args: ["--start-maximized"],
    },

    testIdAttribute: "data-test-id",

    storageState: "frontend/tests/state.json",
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: {
        // ...devices["Desktop Chrome"],
      },
    },

    {
      name: "firefox",
      use: { ...devices["Desktop Firefox"] },
    },

    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },

  ]
});

---

"@playwright/test": "^1.44.1"
