### ISSUE TITLE
[Question] Azure pipeline task exits after tests execute - failing the task if any tests fail

### ISSUE THREAD

**Issue by matthewgorman** [microsoft/playwright#20447]
After the tests execute on my azure pipeline the command line exits (see image below) and the task fails if any tests fail. Is there a way to prevent the task from failing if tests fail?

Command line script is as follows:

`npm i && npx playwright install && npx playwright test targetfolder1 && npx playwright test targetfolder2`

There is 1 test failing in `targetfolder1` so the subsequent command targetting `targetfolder2` never executes.

![image](https://user-images.githubusercontent.com/66619449/215108578-ff39f681-893c-4906-93e9-940c90c6c0fd.png)

**Comment by pavelfeldman** [comment]
Your command is saying `npx playwright test targetfolder1 && npx playwright test targetfolder2`, which means only run targetfolder2 if targetfolder1 passes. Learn more about the shell to run them independently.
