### ISSUE TITLE
Chrome not opening in incognito due to organization's security

### ISSUE THREAD

**Issue by aradhna14** [microsoft/playwright#20442]
My chrome does not open in incognito by default using playwright as it fetches Authorization details (my email and phone number) automatically on trying to login into application(Microsoft oauth2). I want to run my scenario with a test email and not my user.
I have tried to open chrome using launchPerspectiveContext which successfully opens it in incognito but playwright does not interact further with chrome.
Can someone suggest a workaround for this?

![config file](https://user-images.githubusercontent.com/123738056/215083494-c0eb8e84-49de-40f7-b3dd-73cf679bb0e4.png)
</div>

**Comment by pavelfeldman** [comment]
It is unclear what you are trying to do, could you share a script we could run to reproduce this locally?

**Comment by aradhna14** [comment]
[test script.txt](https://github.com/microsoft/playwright/files/10532373/test.script.txt)
This might not work for you due to permission issues. My company uses Zscaler for security.

**Comment by pavelfeldman** [comment]
This would fall out of scope for Playwright, we assume that the browsers run in a clean environment w/o enforcing enterprise policies.

**Comment by samjmohd123** [comment]
Hi, 
I'm using playwright version 1.48.2, node version v22.10.0, npm version 10.9.0 and I'm using my personal laptop to open chrome browser in incognito mode using the code that is available in playwright documents
import { test, expect, Browser, BrowserContext, chromium } from '@playwright/test';

test('has title', async () => {
  const browser =await  chromium.launch({ channel: 'chrome'});
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('http://www.google.com');

  // Expect a title "to contain" a substring.
  //await expect(page).toHaveTitle(/Playwright/);
  await page.pause();

    // Gracefully close up everything
    await context.close();
    await browser.close();

I'm expecting to see a chrome browser opened in incognito mode 
![Image](https://github.com/user-attachments/assets/d13b65b0-e0b0-4927-b5d6-f1f158a7c78b)
but I'm not seeing incognito on the browser and looks like it opened in normal mode
![Image](https://github.com/user-attachments/assets/1cf1ee22-1ec5-49a4-8f05-a8265fc90049)

looks very simple task that i'm doing but I have no clue on why the browser is not opening in incognito mode. Please let me know what I have to do to see a chrome browser in incognito mode? 

Thanks for your help on this greatly appreciated.
