### ISSUE TITLE
[BUG] - Unable to proceed past Chrome Security Certificate dialog as page evaluates as not loading

### ISSUE THREAD

**Issue by simon-gilmurray** [microsoft/playwright#20452]
I'm trying to create a script that can run a few actions on a web portal, that can then be easily run and distributed to multiple team members.

The main issue I've run in to is that a Chrome security certificate prompt pops up that needs selecting before opening the website. It's for this reason that I can't run in headless, which is fine, but I can't seem to interact at all with the OK button as the `page.goto` command seems to never finish as it can't get past the prompt:

```
 page.goto: Navigation failed because page was closed!
    =========================== logs ===========================
    navigating to "https://<website>.com/", waiting until "load"
    ============================================================
```

I've seen there have been issues with security certificates in the past, I feel like my scenario is easily bypassed by a simple Enter press if the test gets to the point (`page.keyboard.press('Enter')`)

How can I handle this?

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/1799, there are some hints that might work for you.

**Comment by simon-gilmurray** [comment]
That's a very long thread, without any real answers...one suggests spinning up a Docker container which is not feasible...another suggests using deprecated code?
