### ISSUE TITLE
[QUESTION] How can we use Istanbul code coverage in Playwright?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#20459]
I was using `Istanbul` with WebdriverIO to generate the automation tests code coverage, check below. How can we implement same in playwright? I am not if we can declare `global` in playwright. 

```
  global: (afterEachReportAutomation = async browser => {
    const coverage = await browser.execute(() => {
      if (typeof window.__coverage__ === undefined) {
        console.log("instrumentation not done...");
        window.__coverage__ = {};
      } else {
        return window.__coverage__;
      }
    });
    coverageObjects.push(coverage);
  }),

  //Combines coverage information and merge all the information from the coverageObjects and instruct istanbul to generate readable html reports.
  after: () => {
    coverageObjects.forEach(coverage => {
      coverageMap.merge(coverage);
    });

    const context = libReport.createContext({
      dir: "report",
      defaultSummarizer: "nested",
      coverageMap
    });
    const tree = libReport.summarizers.pkg(coverageMap);
    tree.visit(reports.create("html"), context);
  },

  afterHook: function() {
    global.afterEachReportAutomation(browser);
  }
```

**Comment by pavelfeldman** [comment]
- If you need something before the page (and each iframe) loads, you can use https://playwright.dev/docs/next/api/class-page#page-add-init-script
- to collect results after the fact, you can use https://playwright.dev/docs/next/api/class-worker#worker-evaluate

**Comment by gauravgandhi1315** [comment]
@pavelfeldman Can I use `global-setup and teardown`?

**Comment by pavelfeldman** [comment]
You can definitely use global-setup and teardown, but I am not sure how this is related to the code coverage.

**Comment by pavelfeldman** [comment]
Let me fold this into https://github.com/microsoft/playwright/issues/20459
