### ISSUE TITLE
[BUG] Failing to intercept API requests

### ISSUE THREAD

**Issue by eveltman-twinfield** [microsoft/playwright#20469]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Windows
- Node.js version: v17.0.1
- Browser: Chromium

## System:
 - OS: Windows 10 10.0.19044
 - Memory: 16.19 GB / 31.85 GB
## Binaries:
 - Node: 17.0.1 - C:\Program Files\nodejs\node.EXE
 - npm: 8.5.0 - C:\Program Files\nodejs\npm.CMD   
## Languages:
 - Bash: 5.0.16 - C:\WINDOWS\system32\bash.EXE (but really Powershell Core)

**Code Snippet**

```javascript
const { chromium } = require('@playwright/test');
const readline = require('node:readline/promises');
const { stdin : input, stdout : output } = require('node:process');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({ serviceWorkers: 'block' });
  const page = await context.newPage();

   await context.route(url => true, (route, request) => {
     console.log(`Logging handler for ${request.method()} ${request.url()}`);
     route.continue();
   });

  // context.on('request', request => { console.log(`${request.method()} ${request.url()}`) });

    await page.goto('https://login.master.dev.twinfield.com/'); // Sorry, it's not openly accessible.
  
  const rl = readline.createInterface({ input, output });
  await rl.question('Please press ENTER to close Playwright browser ...');
  rl.close();

  console.log('Closing browser ...');

  await context.close();
  await browser.close();
})()
```

**Describe the bug**

Hi, I'm trying to mock all API responses to see if we can use it to do (pure) frontend testing.
First attempts with routeFromHAR I ran into some trouble handling API requests (didn't seem to get handled).

So to troubleshoot, I created a logging route handler, which only logs to the console.
Strangely, all requests, except the API requests are logged.
Also API requests in the frontend don't receive a proper response.
After logging in, the OPTIONS request on /api/ returns a 204 No content instead of a 200 with Hypermedia links to all other accessible APIs.

I thought it might have to do with service workers, so I blocked them, but it makes no difference.

If I disable the context.route block and enable the context.on('request', ...) it does log everything and API responses from the server are received properly by the frontend.

Any idea what could be the cause? Did I make a mistake in my code? Could there be something in the frontend application interfering with API request interception from Playwright?
If access to the application is needed, I might be able to arrange it (access to a public demo environment) next week.

**Comment by refactoreric** [comment]
I'm thinking maybe it has something to do with a mixed domain scenario? The login takes place on another domain than where the rest of the application lives (and of which I want to log API calls and later mock the responses).

**Comment by dgozman** [comment]
> After logging in, the OPTIONS request on /api/ returns a 204 No content instead of a 200 with Hypermedia links to all other accessible APIs.

I think this is the most probable culprit. However, we'd really need more information to be able to help. Ideally, a publicly accessible page that has this issue. Or at least [a trace file](https://playwright.dev/docs/trace-viewer-intro).

**Comment by eveltman-twinfield** [comment]
Hmm interesting. It indeed seems to have nothing to do with a cross-domain scenario. Even if I use two separate browser contexts (one for logging in and saving storage state, and the other for restoring storage state and using the application/frontend on the other domain, with request interception), the problem still persists.

Apparently the server doesn't trust the API requests as soon as they're intercepted by Playwright? 

I will try your advice and come back to you. Might take a while though, I'm doing this as a pet project.

**Comment by dgozman** [comment]
@eveltman-twinfield Intercepting OPTIONS preflight requests is full of intricate details. I assume Playwright doesn't do quite the same as your server. That's why I'm interested in a repro - perhaps we would be able to figure out something specific in your setup that Playwright misses.

**Comment by eveltman-twinfield** [comment]
Hi, @dgozman, I just sent to an e-mail (on the e-mail address you use for GitHub commits) with details to access the application. If you don't receive it, let me know. I hope this will enable you to reproduce the issue.

**Comment by dgozman** [comment]
I managed to reproduce. It seems like we are intercepting non-preflight OPTIONS and supply an empty body, which breaks this particular page.
