### ISSUE TITLE
[Question] How to test the StorageEvent of localStorage?

### ISSUE THREAD

**Issue by KID-joker** [microsoft/playwright#20477]
I created a [repository](https://github.com/KID-joker/proxy-web-storage) about web storage, which involves the StorageEvent of localStorage.
I want to do e2e testing on it, but I don't know how to handle the StorageEvent.
Can you give me some suggestions?

**Comment by dgozman** [comment]
@KID-joker I guess you should use [`page.evaluate()`](https://playwright.dev/docs/api/class-page#page-evaluate) and do things in the page? I don't think we'll be able to help without more information.

**Comment by KID-joker** [comment]
@dgozman Yes, I tried it with the code below.
```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();

  const page1 = await browser.newPage();
  await page1.goto('https://playwright.dev/');

  const page2 = await browser.newPage();
  await page2.goto('https://playwright.dev/');

  page2.on('console', msg => console.log('console ==> ', msg.text()));
  await page2.evaluate(() => {
    window.addEventListener('storage', (ev) => {
      console.log(ev);
    })
  });

  const localStorage = await page1.evaluate(() => {
    window.localStorage.setItem('test', 'hello world!');
    return JSON.stringify(window.localStorage);
  });
  console.log('localStorage ==> ', localStorage);

  await browser.close();
})();
```
But it didn't work.

**Comment by dgozman** [comment]
@KID-joker Perhaps you meant `page1` and `page2` to share local storage? If so, you need to create them in the same context:

```js
const context = await browser.newContext();
const page1 = await context.newPage();
const page2 = await context.newPage();
```

**Comment by KID-joker** [comment]
Yes, it works. Thanks for your answer.
