### ISSUE TITLE
[Question] how we do mouse scroll delay in playwright[python] 

### ISSUE THREAD

**Issue by aman-agrawal07** [microsoft/playwright#20478]
i am using page.mouse.wheel(0,5000) some vertical scroll and i want it will scroll slowly like a human not instantly because my page images not loads correctly . pls help

**Comment by dgozman** [comment]
@aman-agrawal07 Do a few scrolls in a loop:

```py
for _ in xrange(0, 10):
  page.mouse.wheel(0, 500)
```
