### ISSUE TITLE
[BUG] Reused browser (of VS code extension) doesn't work when chrome extensions are used

### ISSUE THREAD

**Issue by lukaskl** [microsoft/playwright#20470]
### Context:
- Playwright Version: `1.30.0`
- Operating System: `Mac`
- Node.js version: `v18.12.1`
- Visual Studio Code version: Version: `1.74.3` (Universal), Commit: `97dec172d3256f8ca4bfb2143f3f76b503ca0534`
- Playwright for VSCode extension version: `1.0.6`
- Browser: `Chromium`

### Code Snippet

I have created a repository where this issue is reproducible: https://github.com/lukaskl/playwright-report

But in short, when using [chrome-extensions as suggested here](https://playwright.dev/docs/chrome-extensions#testing) Reused Browser (`Show browser` checkbox) stops to work.

### Describe the bug 

**Expected**

After executing the test browser should stay open and other features such as `Pick locator` should still be working:

https://user-images.githubusercontent.com/4083977/215271441-2769026b-c1bd-4aac-a142-55e838b1d431.mp4

**Actual**

Browser immediately closes once test finishes: 
 
https://user-images.githubusercontent.com/4083977/215271522-29d52c9e-5f37-49a2-9536-d59350cf3c0e.mp4

### Notes

I'm really not sure whether the `chrome extensions` is to blame here but I've put that into the title as this was my use case.
It might be just the `const context = await chromium.launchPersistentContext("", { ... })` or something else. 

It also might be that it is necessary to update the code on my side, but in this case what changes should be made? And also maybe it would be healthy to update the documentation?

**Comment by dgozman** [comment]
@lukaskl This is because you manually launch the browser with `chromium.launchPersistentContext()` and then manually close it with `context.close()`.

Reuse browser mode in VSCode extension only works with regular contexts that are provided by the test runner out of the box, i.e. with built-in `page` and `context`. I don't think it will work for your scenario in the near future, sorry.
