### ISSUE TITLE
[Feature] Improve error messages for bad configurations

### ISSUE THREAD

**Issue by benlesh** [microsoft/playwright#20476]
I just spend WAY too much of my personal time fiddling with getting playwright set up to run a local process because of a vague error message.

The issue was that I had configured things as follows:

(What you see below is ALL that I altered about the `npx init playwright` installed config)

**playwright.config.ts**

```ts
const config: PlaywrightTestConfig = {
  /** .... SNIP default init setup stuff in here ... **/
  baseURL: 'http://localhost:3000',
  
  webServer: {
    command: 'npx start-storybook -p 6006',
    // @ts-expect-error <-- this is a WHOLE other problem! lol
    waitFor: () => { /* doesn't matter for this issue */ }
  }
```

### My issues:

1. It turns out I didn't have a `url` provided for the `webServer`, and it had NOTHING to do with the `baseURL` above. (which was a valid URL, so I was very confused.
2. `waitFor` doesn't exist in your TypeScript typings.

### Suggestions:

1. Add `waitFor` to `interface TestConfigWebServer`.
2. In your TypeScript types for `TestConfigWebServer`, make `url` a required property  so users get a TypeScript error in their IDE if they mess it up.
3. If the CLI (or whatever is running this) gets an invalid URL from the config. Have an explicit error message that describes _what_ was invalid so the developer can fix it quickly.

In fact, it's probably worth doing a pass on all of your config settings that could be invalid and ensuring a good user experience there.

**Comment by mxschmitt** [comment]
1. `waitFor` does not exist because its not a valid property and we don't use it. Where did you see any reference to it?
2. We can't make `url` required, because the user can either specify `url` or `port`. We can massage typings properly to make this work and error out.
3. This is a bug, we should [fix it](https://github.com/microsoft/playwright/blob/f72d4009529e79953dd12e02c5dd715ad9d96ffd/packages/playwright-test/src/plugins/webServerPlugin.ts#L214) and throw a good error message.

**Comment by benlesh** [comment]
> We can't make url required, because the user can either specify url or port. We can massage typings properly to make this work and error out.

@mxschmitt - you _can_ make it required though. :) 

You may not like the cleanliness on your side, but this is about ergonomics for your users rather than ergonomics for you. :) Tradeoffs. 

```ts
interface TestConfigWebServerBase {
  /**
   * Shell command to start. For example `npm run start`..
   */
  command: string;

  /**
   * Whether to ignore HTTPS errors when fetching the `url`. Defaults to `false`.
   */
  ignoreHTTPSErrors?: boolean;

  /**
   * How long to wait for the process to start up and be available in milliseconds. Defaults to 60000.
   */
  timeout?: number;

  /**
   * If true, it will re-use an existing server on the `port` or `url` when available. If no server is running on that
   * `port` or `url`, it will run the command to start a new server. If `false`, it will throw if an existing process is
   * listening on the `port` or `url`. This should be commonly set to `!process.env.CI` to allow the local dev server
   * when running tests locally.
   */
  reuseExistingServer?: boolean;

  /**
   * Current working directory of the spawned process, defaults to the directory of the configuration file.
   */
  cwd?: string;

  /**
   * Environment variables to set for the command, `process.env` by default.
   */
  env?: { [key: string]: string; };
}

interface TestConfigWebServerWithURL extends TestConfigWebServerBase {
  /**
   * The url on your http server that is expected to return a 2xx, 3xx, 400, 401, 402, or 403 status code when the
   * server is ready to accept connections. Exactly one of `port` or `url` is required.
   */
  url: string;
}

interface TestConfigWebServerWithPort extends TestConfigWebServerBase {
  /**
   * The port that your http server is expected to appear on. It does wait until it accepts connections. Exactly one of
   * `port` or `url` is required.
   */
  port: number;
}

export type TestConfigWebServer = TestConfigWebServerWithURL | TestConfigWebServerWithPort
```
