### ISSUE TITLE
[QUESTION] Using `baseFixture` to generate the istanbul code coverage report but report is empty

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#20479]
I am using `baseFixture.js` file and also added it in my tests `const { test } = require('./baseFixtures.spec');`. When I run my tests, it does generate `.nyc_output` folder with json files and I generate html report by using `npx nyc report --reporter html --reporter text -t .nyc_output --report-dir coverage/summary`.  My report has been empty<img width="656" alt="Screen Shot 2023-01-29 at 1 07 44 PM" src="https://user-images.githubusercontent.com/66381899/215347353-66793329-e587-4aed-a5de-c020cd230314.png">. Can someone please help what I am doing wrong on my side? I do see `__coverage__` object in my application console.

```
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { test: baseTest } = require('@playwright/test');
const istanbulCLIOutput = path.join(process.cwd(), '.nyc_output');
function generateUUID() {
    return crypto.randomBytes(16).toString('hex');
}
const test = baseTest.extend({
    context: async function ({ context }, use) {
        await context.addInitScript(() =>
            window.addEventListener('beforeunload', () =>
                (window).collectIstanbulCoverage(JSON.stringify((window).__coverage__))
            ),
        );
        await fs.promises.mkdir(istanbulCLIOutput, { recursive: true });
        await context.exposeFunction('collectIstanbulCoverage', function (coverageJSON) {
            if (coverageJSON)
                fs.writeFileSync(path.join(istanbulCLIOutput, `playwright_coverage_${generateUUID()}.json`), coverageJSON);
        });
        await use(context);
        for (const page of context.pages()) {
            await page.evaluate(() => (window).collectIstanbulCoverage(JSON.stringify((window).__coverage__)))
        }
    }
});
const expect = test.expect;
module.exports = { test, expect };
```

Package.json
```
I added 2 dependancies
"babel-plugin-istanbul": "^6.1.1",
"nyc": "^15.1.0" 
```

**Comment by gauravgandhi1315** [comment]
@mxschmitt Would you be able to help here?

**Comment by mxschmitt** [comment]
There are most likely two reasons why its not working:

a) the application you are testing has no __coverage data, but you confirmed, that it has
b) you create your context manually, could you show us how your tests look like? Are you using the page or context fixture?

**Comment by gauravgandhi1315** [comment]
@mxschmitt This is my test

```
const { test } = require('./baseFixtures.spec');
const TestData = require('../testData/allPages');
const { VerifyActions } = require('../../utils/verifyActions');

test.describe('Results Scripts', () => {
  let verification, verifyActions;
  test.beforeEach(async ({ page }) => {
    verification = new LandingPageNav(page);
    verifyActions = new VerifyActions(page);
    // Go to the application url
    await verifyActions.openURL(TestData.urlPath);
    await verifyActions.refreshPage();
  });

  test.only('Results - Verify Simulation Page Text Strings', async () => {
    await verification.simulationResultsRowsColumnsValidation(
      TestData.simResultsColumnNames,
      TestData.simResultsItemsPerPage
    );
  });

```

Do you think there is an issue with `collectIstanbulCoverage`, it says never used. I converted your `baseFixture.ts` to `js`

**Comment by gauravgandhi1315** [comment]
@mxschmitt can you please check above?

**Comment by mxschmitt** [comment]
This `Results - Verify Simulation Page Text Strings` test looks suspicious, since it does not use any page. It's fine that collectIstanbulCoverage does not get called, since it gets called when the `context` fixture does dispose.

**Comment by gauravgandhi1315** [comment]
@mxschmitt What would be your suggestion here? I am calling TestData functions in my tests.

**Comment by gauravgandhi1315** [comment]
`page` is being called in functions and then calling function in my tests.

**Comment by mxschmitt** [comment]
So you create the page instance yourself? This is expected that it doesn't work with the code coverage base fixtures, you'd have to implement it in your own implementation. The fixtures above only work when you use a `page` and `context` instance via the Playwright fixtures, like its shown in the official examples: https://playwright.dev/docs/writing-tests

**Comment by gauravgandhi1315** [comment]
@mxschmitt I added `page` in my test just for testing to see the report. But it is still coming up empty

```
  test.only('Simulation Results - Verify Simulation Page Text Strings', async ({page}) => {
    // await verification.simulationResultsRowsColumnsValidation(
    //   TestData.simResultsColumnNames,
    //   TestData.simResultsItemsPerPage
    // );
    await page.click(LandingPage.LandingPageNav.landingPageNav(2));

  });
  ```

**Comment by gauravgandhi1315** [comment]
@mxschmitt This works for me

`npx nyc report --report-dir ./coverage --temp-dir .nyc_output --reporter=text --exclude-after-remap false`
