### ISSUE TITLE
[BUG] drawImage doesn't work with WebM files

### ISSUE THREAD

**Issue by warrenseine** [microsoft/playwright#20489]
**Context:**
- Playwright Version: 1.31.0-alpha-jan-29-2023
- Operating System: macOS 13.2
- Node.js version: 16.17
- Browser: WebKit 1783

**Code Snippet**

See repo: https://github.com/warrenseine/playwright-webm-test

**Describe the bug**

Following the resolution of #18423, I wanted to test my use case of copying WebM frames to a canvas, using `Canvas.drawImage()`. Unfortunately, it won't work with WebM video under the most recent Playwright WebKit version. It works fine with Safari, Playwright Chromium, Playwright Firefox.

Here is a demo of the bug that you can reproduce in WebKit: https://warrenseine.github.io/playwright-webm-test/

While playback now works fine with WebKit, you can see that drawing frames to a canvas from an MP4 video works, but it doesn't with WebM.

**Comment by dgozman** [comment]
It seems that `onloadedmetadata` event does not fire for some reason.

**Comment by yury-s** [comment]
As far as I can see onloadedmetadata is dispatched. The problem is that the video frame is not properly copied to the canvas.

**Comment by mxschmitt** [comment]
When I was compiling WebKit on macOS 13.2.1 with XCode 14.2 it was working fine for me.

**Comment by amw** [comment]
I am still experiencing issues with `webm` on Playwright 1.47.2. It does not trigger callbacks for `video.requestVideoFrameCallback` and trying to use canvas `ctx.drawImage(webmVideo)` results in empty image.

@warrenseine did it ever start working for you?

**Comment by warrenseine** [comment]
To be fair, I have moved on. I'm not exactly sure if the problem was solved in the end. The test I had written is probably still disabled somewhere deep in the code base.
