### ISSUE TITLE
[Question] How to disable browser cache when using network proxy?

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright#20485]
**Context:**
- Playwright Version: 1.27.0
- Operating System: Windows
- Node.js version: 16
- Browser: Chromium

I am using the http proxy to test local build javascript files, we did find the local files with network proxy, however, we found some js files should be cached by chromium, how can I disable the browser cache ?

**Comment by dgozman** [comment]
@lxy2222 You can try running with `--disk-cache-size=1` argument. But ideally, your proxy/server should set `cache-control` and/or `max-age` headers to prevent these files from being cached. Let me know if that helps.

**Comment by lxy2222** [comment]
thanks! let me try!

**Comment by lxy2222** [comment]
thanks @dgozman, we figure out the issue was caused by our own code, but for the arguments `--disk-cache-size=1` seems not used for playwright command, this looks like used for launching chromium
