### ISSUE TITLE
[Question]Test failed in Firefox due to closed page.

### ISSUE THREAD

**Issue by fishzilla7** [microsoft/playwright#20498]
I have wrote something like:
```javascript
let page; // reuse single page between test

test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();

    await page.goto(URL_TO_LOGIN_PAGE);

    // omit steps of login
    
    await page.waitForURL(URL_TO_HOME_PAGE)
});

test.afterAll(async () => {
    await page.close();
});

test('some elements is visible in the page', async () => {
    // await page.waitForTimeout(2 * 1000);

    // in case that current page is not home page
    await page.goto(URL_TO_HOME_PAGE);

    // do some tests in home page
})
```

The test has passed in chrome and webkit but failed in firefox with the following error:

```
page.goto: Navigation failed because page was closed!
======================== logs =========================
navigating to "URL_TO_HOME_PAGE", waiting until "load"

  |
 >|  await page.goto(URL_TO_HOME_PAGE);
  |             ^

```

It kept failing until the code `await page.waitForTimeout(2 * 1000)` was added like the commented one above.

I try to use `page.screenshot()`, `page.content()` and `page.frames()` to see the differences before and after the two seconds among different browsers:

- There is no difference before and after the two seconds in chrome and webkit.
- In firefox the screenshot shows there are some elements not visible before the two seconds. In the content, a bunch of html (maybe insert by js) and an `iframe` tag is missing comparing to the after one. There is only one frame before but three after.

May I ask what lead the differences between the firefox and other browsers? Is there any way to fix it?

By the way the develop environment is wsl ubuntu 22.04 installed from microsoft store. It's a new project create using `npm init playwright@latest` last week.

some other context info:
- playwright 1.30.0
- Node.js 18.13.0  
- npm 8.19.3
- Mozilla Firefox 108.0.2

**Comment by dgozman** [comment]
@fishzilla7 Unfortunately we cannot help your here without a repro that we can run locally. Could you please share your full test/script?

**Comment by fishzilla7** [comment]
@dgozman Thanks for reply. I cannot share the original test script for some reason. I'll try to write a simple demo to reproduce the issue. It may take a while, or I'll close the issue if I cannot reproduce it.

**Comment by fishzilla7** [comment]
Close this issue for that cannot reproduce it.
