### ISSUE TITLE
[BUG] Cannot open chrome://system in headless mode

### ISSUE THREAD

**Issue by miktuy** [microsoft/playwright#20493]
**Context:**
- Playwright Version: 1.29, 1.30
- Operating System: Linux, Mac
- Node.js version: 16.15.0
- Browser: Chromium

**Code Snippet**

```
import { test } from '@playwright/test';

test.describe('Open chrome://system', () => {

  test('I can goto chrome://system',
    async ({ page }) => {
      await page.goto('chrome://system')
    });
});
```

**Describe the bug**

In headless mode test can not open the `chrome://system`. Error is 
```
page.goto: net::ERR_INVALID_URL at chrome://system
=========================== logs ===========================
navigating to "chrome://system", waiting until "load"
============================================================

   6 |   test('I can goto chrome://system',
   7 |     async ({ page }) => {
>  8 |       await page.goto('chrome://system')
     |                  ^
   9 |     });
  10 | });
```

In not headless mode is everything ok. It has started since update to version 1.29 and repeated in 1.30

Before update `page.goto` reached `chrome://system` without any problems

**Comment by dgozman** [comment]
@miktuy I think this has always been the case. I can repro going back at least to v1.25. Headless and headed Chromium have a few differences, and this is one of them. I don't think this will be changed in Chromium, sorry.
