### ISSUE TITLE
[BUG] Impossible to use same variable in different test steps

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20502]
**Context:**
- Playwright Version: 6.14.15
- Operating System: Windows
- Node.js version: 6.14.15
- Browser: Chromium

**Describe the bug**
Hello, I found out that it's not possible to define a variable in a specific test step and use it in another one. Everytime I do so, the variable is set as "undefined".
I've tough tried to use the return function in the test step where I defined it.
I've also tried "let variable" at the beginning of the test step where I call it but unsucessfully.

Is it a limitation ?

Thank you in advance,

Regards,

Johan

**Comment by ltsuda** [comment]
Please, see how to return in  here:

https://playwright.dev/docs/api/class-test#test-step

**Comment by MehseinJohan** [comment]
Hello,

Thanks for your answer. 
Still I have tried but unsuccessfully, let me show you my code : 

`test('bulk_item_presence',` async ({ dihWelcomePage, page, webActions, baseURL }) => {
`  await test.step("Getting rules ID along with their text", async () =>{
`  const checkboxesNumber = await page.getByRole('checkbox').count()
`  return checkboxesNumber ;
`  }

`  await test.step("Select 3 random rules", async () =>{
`    console.log(checkboxesNumber)
`     }
`   })

My variable checkboxesNumber can not be called in VSCode, it is considered as unknown.

Thank you,

Johan

**Comment by dgozman** [comment]
@MehseinJohan  Declare your variable outside of the step.

```
test('bulk_item_presence', async ({ dihWelcomePage, page, webActions, baseURL }) => {
  let checkboxesNumber;
  await test.step("Getting rules ID along with their text", async () =>{ 
    checkboxesNumber  = await page.getByRole('checkbox').count() 
  }

  await test.step("Select 3 random rules", async () =>{
    console.log(checkboxesNumber)
  }
})
```

**Comment by MehseinJohan** [comment]
Hello,

This syntax is still not working. When doing a console.log in the other test step, I have "undefined".

Could you please help ?

Regards,

Johan
