### ISSUE TITLE
[BUG] WebKit does not identify object based on the device used

### ISSUE THREAD

**Issue by mayurbojappa** [microsoft/playwright#20508]
**Context:**
- Playwright Version: [1.3.0]
- Operating System: [Windows 10]
- Node.js version: [14.6.1]
- Browser: [WebKit]

**Code Snippet**

Automated Microsoft Authenticator Login
    const userNameField = page.getByPlaceholder('Email, phone, or Skype');
    await userNameField.fill(userName);
    
**Describe the bug**

I am trying to automate and emulate Sonim device. For this, if I use the browserName as 'webkit' with a viewport of '480x800', it is not able to identify the basic username field based on placeholder in the Microsoft Authenticator Login page.

As a workaround, I tested it using 'iPhone 11' device with a viewport of '480x800' and it worked. But when I change the device to 'BlackBerry Z30' with the same viewport, it does not identify the username field.

What are the differences in the devices 'iPhone 11' and 'BlackBerry Z30'? What default values does the test use when you give browserName as 'webkit' instead of the device 'iPhone 11'?

**Comment by dgozman** [comment]
@mayurbojappa You can see the difference between devices [in the source](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/deviceDescriptorsSource.json). Not sure how else to help you without a repro that we can run locally.

**Comment by mayurbojappa** [comment]
Thanks for your response. 

I see that as the only difference in both 'BlackBerry Z30' and 'iPhone 11' is the userAgent. Is it possible to add Sonim devices as a part of the list of available devices?

Also, to reproduce the issue, logging into any Microsoft Authenticator login page should work. 

To give you more detail on how playwright is recognizing the field:
In chromium, the codegen identifies it with placeholder
![image](https://user-images.githubusercontent.com/112905662/215591971-44bf327d-ce9b-4a47-b4d2-a1d1f8992807.png)

But in webkit, the same page it identifies with text instead. 
![image](https://user-images.githubusercontent.com/112905662/215592195-eac71c1b-b71a-462b-a464-8c79fda48d7b.png)

And as I had written the tests using placeholder for chromium, when I test it with webkit, it fails.

**Comment by dgozman** [comment]
> Is it possible to add Sonim devices as a part of the list of available devices?

Sure, send us a PR!

> But in webkit, the same page it identifies with text instead.

I guess, there is no placeholder in the page when it is rendered by WebKit? You can check that manually by opening Web Inspector.

IIUC, Sonim is an android-based device? Are you sure it has a WebKit-based browser? I'd assume a Chromium-based one.

**Comment by mayurbojappa** [comment]
From what information I could get, it has Sonim OS based on Android OS. And as far as the userAgent for Sonim devices, I could get this out of chatGPT 
"Mozilla/5.0 (Linux; Android 8.1.0; XP7 Build/OPM1.171019.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.96 Mobile Safari/537.36"

I am not really sure if this is correct as this was the only place I could get the information of userAgent from. So since its android based, I guess chromium should be good to use.

Thanks for the help. 

For the PR, I would want to be sure that the userAgent and other parameters I use are correct. So if you can confirm that the above userAgent detail is correct, then I could create a PR!

**Comment by dgozman** [comment]
> So since its android based, I guess chromium should be good to use.

I guess we can close this issue then?

> So if you can confirm that the above userAgent detail is correct, then I could create a PR!

I never heard about Sonim devices before reading this issue today, so I am in no way an authority about their userAgent value 😄  Sorry!

**Comment by mayurbojappa** [comment]
> > So since its android based, I guess chromium should be good to use.
> 
> I guess we can close this issue then?
Yes.
> 
> > So if you can confirm that the above userAgent detail is correct, then I could create a PR!
> 
> I never heard about Sonim devices before reading this issue today, so I am in no way an authority about their userAgent value 😄 Sorry!

No problem. Thanks for your response.
