### ISSUE TITLE
[Feature] Add full list of bug fixes in release notes (e.g. 1.30.0 release)

### ISSUE THREAD

**Issue by mahtabnejad90** [microsoft/playwright#20506]
I'de like to see consistency in release notes in every release. Since there's a lot of merges going in, would be good to include a list of PRs or commits getting merged in.... 

This wasn't included in the recent release: https://github.com/microsoft/playwright/releases/tag/v1.30.0

**Comment by Smrtnyk** [comment]
I agree
there is a lot of fixes and merging going on, but release notes show nothing

**Comment by dgozman** [comment]
GitHub can show the list of commits between two branches. Here is an example with changes between v1.29 and v1.30: https://github.com/microsoft/playwright/compare/release-1.29...release-1.30.

**Comment by ltsuda** [comment]
Just asking about the 1.30.0 release, there were more bugfixes, is that right? That why there are no Highlights section in the Release page.

**Comment by dgozman** [comment]
> Just asking about the 1.30.0 release, there were more bugfixes, is that right?

We didn't count, but every release includes a large number of bugfixes. These are not usually mentioned in the release notes.

**Comment by ltsuda** [comment]
No problem, I realised that I wasn’t clear in my message :)

I meant that this release was more about bug fixes and not new/improvement feature, that’s why there wasn’t a Highlights information.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
