### ISSUE TITLE
[REGRESSION]: Test status can't be set via testInfo if test actually fails

### ISSUE THREAD

**Issue by oleksii-ti** [microsoft/playwright#20505]
**Context:**
- GOOD Playwright Version: 1.24.2
- BAD Playwright Version: 1.25.0
- Operating System: macOS 13.2, ubuntu:focal 

**Code Snippet**
```javascript
const {test, expect} = require('@playwright/test')

test.describe('Skip status test', () => {
  test(`should navigate from `, async ({ page }, testInfo) => {
    page.on('response', (response) => {
      if (response.url().includes('playwright')) {
        testInfo.status = 'skipped'
      }
    })

    await page.goto('https://playwright.dev/')
    await expect(page).toHaveTitle(/Puppeteer/)
  })
})
```

**Describe the bug**
Starting from v25.0 test from the code above will have failed status.  Test above should fail, and you can't set status to 'skipped'  via testInfo. However, status can be set to 'skipped' if your test should pass.
Before v.25.0 you could set your own test status via testInfo regardless if test fails or passes in the end.

**Comment by dgozman** [comment]
@oleksii-ti If you want to skip a test, call `test.skip()` instead of setting the status. Let me know if that helps.

**Comment by oleksii-ti** [comment]
if I use test.skip() inside of .on handler i receive error  `Error: Test is skipped: `
Using test.skip() inside of tests looks wrong in my case as I need to skip hundreds of tests basing on the same rules.

**Comment by dgozman** [comment]
@oleksii-ti If you want to skip a test from the event handler, this is not something we support out of the box. I'd recommend to restructure your test somehow and  call `test.skip()` from the main code block. This way, Playwright will recognize the skip and everything should work.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
