### ISSUE TITLE
[BUG] GitHub Actions job doesn't fail when tests fail in Playwright

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#20511]
**Context:**
- Playwright Version: v1.30
- Operating System: Happens on GitHub Actions Mac and Windows runners
- Node.js version: 16
- Browser: Chromium (didn't test on others as the app is Chrome only for now)
- Extra: [any specific details about your environment]

**Describe the bug**

Not sure if this is a Playwright issue or an actions issue. In one repo, that has the default basic PW framework with sample tests, if the tests fail, the actions job fails.

However in the other, where the pw config has been modified a little, whenthe tests fail, I can see the failure in the downloaded report but the actions job doesn't fail.

Also how do I debug this further to get more information?

**Comment by dgozman** [comment]
> Also how do I debug this further to get more information?

I am not sure. If you provide more information like a link to the failed CI run, we might be able to help, but that's also unlikely. If there is a bug in Playwright, a repro that we can run locally would be ideal. However, most likely the issue is in the CI environment.

**Comment by siddharth2023** [comment]
Thanks. I understand. I will see if I can gather more information and get back soon.

**Comment by siddharth2023** [comment]
I see that there is no

```Error: Process completed with exit code 1.```

This is why I step isn't failing and so the job isn't.

**Comment by nicolae536** [comment]
Hmm I get the same thing. I use the default github actions config provided by the docs. But if a test times out sometimes I get pipeline failed error sometimes not. Can this be because I have set 
`retries: isCi ? 2 : 0,`

Here is my playwright config
```javascript
const isCi = Boolean(process.env.CI);

const config: PlaywrightTestConfig = {
    testDir: './src',
    /* Maximum time one test can run for. */
    timeout: isCi ? 300_000 : 120_000, // 5 Minutes
    expect: {
        /**
         * Maximum time expect() should wait for the condition to be met.
         * For example in `await expect(locator).toHaveText();`
         */
        timeout: isCi ? 60_000 : 10_000,
    },
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: isCi,
    /* Retry on CI only */
    retries: isCi ? 2 : 0,
    /* Opt out of parallel tests on CI. */
    workers: isCi ? 5 : ENV_VARS.debuggingEnabled ? 1 : 10,
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: 'html',
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        headless: Boolean(process.env.CI),
        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: isCi ? 60_000 : 10_000,
        navigationTimeout: isCi ? 60_000 : 10_000,
        /* Base URL to use in actions like `await page.goto('/')`. */
        baseURL: ENV_VARS.application.frontendUrl,
        video: 'retain-on-failure',
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
        screenshot: 'only-on-failure',
        testIdAttribute: ENV_VARS.automationIdAttributeName,
        launchOptions: {
            // Reduce the speed of running the tests
            slowMo: ENV_VARS.debuggingEnabled ? 1000 : 0,
        },
    },

    /* Configure projects for major browsers */
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
            },
        },

        {
            name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
            },
        },

        {
            name: 'webkit',
            use: {
                ...devices['Desktop Safari'],
            },
        },

        /* Test against mobile viewports. */
        {
            name: 'Mobile Chrome',
            use: {
                ...devices['Pixel 5'],
            },
        },
        {
            name: 'Mobile Safari',
            use: {
                ...devices['iPhone 12'],
            },
        },

        /* Test against branded browsers. */
        // {
        //   name: 'Microsoft Edge',
        //   use: {
        //     channel: 'msedge',
        //   },
        // },
        // {
        //   name: 'Google Chrome',
        //   use: {
        //     channel: 'chrome',
        //   },
        // },
    ],

    /* Folder for test artifacts such as screenshots, videos, traces, etc. */
    // outputDir: 'test-results/',

    /* Run your local dev server before starting the tests */
    // webServer: {
    //   command: 'npm run start',
    //   port: 3000,
    // },
};

export default config;
```

**Comment by siddharth2023** [comment]
> Hmm I get the same thing. I use the default github actions config provided by the docs. But if a test times out sometimes I get pipeline failed error sometimes not. Can this be because I have set `retries: isCi ? 2 : 0,` ? Basically I want if a test times out then the action pipeline should be mark as failed.
> 
> Here is my playwright config
> 
> ```js
> const isCi = Boolean(process.env.CI);
> 
> const config: PlaywrightTestConfig = {
>     testDir: './src',
>     /* Maximum time one test can run for. */
>     timeout: isCi ? 300_000 : 120_000, // 5 Minutes
>     expect: {
>         /**
>          * Maximum time expect() should wait for the condition to be met.
>          * For example in `await expect(locator).toHaveText();`
>          */
>         timeout: isCi ? 60_000 : 10_000,
>     },
>     /* Run tests in files in parallel */
>     fullyParallel: true,
>     /* Fail the build on CI if you accidentally left test.only in the source code. */
>     forbidOnly: isCi,
>     /* Retry on CI only */
>     retries: isCi ? 2 : 0,
>     /* Opt out of parallel tests on CI. */
>     workers: isCi ? 5 : ENV_VARS.debuggingEnabled ? 1 : 10,
>     /* Reporter to use. See https://playwright.dev/docs/test-reporters */
>     reporter: 'html',
>     /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
>     use: {
>         headless: Boolean(process.env.CI),
>         /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
>         actionTimeout: isCi ? 60_000 : 10_000,
>         navigationTimeout: isCi ? 60_000 : 10_000,
>         /* Base URL to use in actions like `await page.goto('/')`. */
>         baseURL: ENV_VARS.application.frontendUrl,
>         video: 'retain-on-failure',
>         /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
>         trace: 'on-first-retry',
>         screenshot: 'only-on-failure',
>         testIdAttribute: ENV_VARS.automationIdAttributeName,
>         launchOptions: {
>             // Reduce the speed of running the tests
>             slowMo: ENV_VARS.debuggingEnabled ? 1000 : 0,
>         },
>     },
> 
>     /* Configure projects for major browsers */
>     projects: [
>         {
>             name: 'chromium',
>             use: {
>                 ...devices['Desktop Chrome'],
>             },
>         },
> 
>         {
>             name: 'firefox',
>             use: {
>                 ...devices['Desktop Firefox'],
>             },
>         },
> 
>         {
>             name: 'webkit',
>             use: {
>                 ...devices['Desktop Safari'],
>             },
>         },
> 
>         /* Test against mobile viewports. */
>         {
>             name: 'Mobile Chrome',
>             use: {
>                 ...devices['Pixel 5'],
>             },
>         },
>         {
>             name: 'Mobile Safari',
>             use: {
>                 ...devices['iPhone 12'],
>             },
>         },
> 
>         /* Test against branded browsers. */
>         // {
>         //   name: 'Microsoft Edge',
>         //   use: {
>         //     channel: 'msedge',
>         //   },
>         // },
>         // {
>         //   name: 'Google Chrome',
>         //   use: {
>         //     channel: 'chrome',
>         //   },
>         // },
>     ],
> 
>     /* Folder for test artifacts such as screenshots, videos, traces, etc. */
>     // outputDir: 'test-results/',
> 
>     /* Run your local dev server before starting the tests */
>     // webServer: {
>     //   command: 'npm run start',
>     //   port: 3000,
>     // },
> };
> 
> export default config;
> ```
> 
> For example this pipeline should have failed:
> 
> ![Screenshot 2023-02-03 at 10 02 17](https://user-images.githubusercontent.com/9453094/216545010-635c9943-a5b3-40c7-8c2e-72f3ed498826.png) ![Screenshot 2023-02-03 at 10 02 29](https://user-images.githubusercontent.com/9453094/216545020-f5569520-e34d-4409-b6b1-162bd723e78e.png)
> 
> Maybe it doesn't fail because `upload-artefacts` step has `if: always()`. If you can point me in the right direction would be nice.

My issue exactly.

**Comment by siddharth2023** [comment]
⬆️ My issue exactly. Thanks.

**Comment by dgozman** [comment]
This sounds very similar to #18248. Most likely, Playwright does not exit with exit code 1. Still no reliable repro, so the best idea I've got is to add more logging. Let me close in favor of #18248.

**Comment by nicolae536** [comment]
Ok I understood the problem 😶‍🌫️ It seems my "Failed" Tests were not failed were actually `Flaky` and I have retry attempts set to 2 and it succeeds on retry. and then the pipeline naturally succeds.

**Comment by luixo** [comment]
I got the same problem at the moment and luckily the repository I work on is public, one can check the [CI run](https://github.com/near/near-explorer/actions/runs/4855139968/jobs/8653423415?pr=1195), the [job code](https://github.com/near/near-explorer/blob/9d91548744006af1659178a4ea8ba543bbea68f2/.github/workflows/continuous-integration-workflow.yml#L112-L139) as well as [playwright config](https://github.com/near/near-explorer/blob/9d91548744006af1659178a4ea8ba543bbea68f2/frontend/playwright.config.ts) (if needed).

This might be npm issue or Github Action issue, but google got me into this issue.

**Comment by marinamarin91** [comment]
Hello, I have managed to fail the workflow using a bash script to run my tests. In that script I am using a function to run my tests and save the exit code from the run. Then I return exit from the script with the saved exit code: 
![image](https://github.com/microsoft/playwright/assets/97027602/0b66ccdf-4ee9-42b2-9e77-527e8e49d30a)
where System, Type and target are params received from the workflow run. 

Hope this helps.

**Comment by jeremy-daley-kr** [comment]
> This sounds very similar to #18248. Most likely, Playwright does not exit with exit code 1. Still no reliable repro, so the best idea I've got is to add more logging. Let me close in favor of #18248.

@dgozman I don't think the 2 things are related issues. The one you linked to is in regards to timeouts, however this one is a failure to exit 1 when `retries` are defined. I'm seeing this in my own private project as well, but it's not as nicolae discovered where the tests are considered flaky.

Here I `echo $?` immediately following the Playwright test execution:

<img src="https://github.com/user-attachments/assets/07ec8b27-fdb4-46ab-a3b2-5d7af8265732" width="480"/>

Still digging to try and find out more, but it's a really strange issue.

**Comment by rombat** [comment]
@dgozman I have the same issue, and i'm in a similar situation as @jeremy-daley-kr . 
It seems that the exit code is wrong whenever there are some flaky tests. Even if the step should fail since not all tests have been run successfully at least once (the following ones are skipped).

**Comment by rombat** [comment]
![Image](https://github.com/user-attachments/assets/65741f49-dfbf-41f0-bf19-c2ceda7d065b)
here
