### ISSUE TITLE
How to click Radio button within a span class?

### ISSUE THREAD

**Issue by aboopesh1** [microsoft/playwright#20519]
<img width="341" alt="Capture" src="https://user-images.githubusercontent.com/122396974/215666534-163316af-ce6c-4898-baf6-ec5325efe88d.PNG">

**Comment by dgozman** [comment]
This does not look like a bug report or a feature request for Playwright. If you have encountered a bug, please file a new issue using the "Bug Report" template. For feature requests, use the "Feature request" template.
