### ISSUE TITLE
[BUG] Cannot login via API with Playwright - failing at setting the cookie as it vanishes on reload

### ISSUE THREAD

**Issue by borecz** [microsoft/playwright#20524]
**Context:**
- Playwright Version: 1.30
- Operating System: Mac
- Node.js version: v16.19.0
- Browser: Chromium

I am unable to make a simple API login that works perfectly using Cypress instead. Let me share the 2 code snippets for comparison:

Simple test case:

1.  API request to the login end-point - Auth token is retrieved
2.  set the auth token as a cookie
3.  navigate to a page that is accessible only if authenticated

**Code Snippet**
Cypress (working fine)
```typescript
const body = {
  username: 'username...',
  password: 'password',
  rememberMe: true,
};

describe('Login via API to management console', () => {
  it('Login via API to management console', () => {
    cy.request({
      method: 'POST',
      url: loginEndPoint,
      headers: {
        'Content-Type': 'application/json',
      },
      body,
    }).then((response) => {
      cy.setCookie('Authorization', `Token ${response.body.data.token}`);
    });

    cy.visit(`/management`);
  });
});
```

Playwright (not working)
```typescript
test('Login via API translating from Cypress', async ({ page, context, request }) => {
  const loginResponse = await request.post(`https://${process.env.MANAGEMENT_URL}/web/api/v2.1/users/login`, {
    data: {
      username: process.env.MANAGEMENT_USER,
      password: process.env.MANAGEMENT_PASSWORD,
      rememberMe: true,
    },
  });

  const {
    data: { token },
  } = await loginResponse.body().then((b) => {

    return JSON.parse(b.toString());
  });

  expect(token).toMatch(/^[a-z0-9]{80}$/);

  await context.addCookies([
    { name: 'Authorization', value: `"Token ${token}"`, path: '/', domain: process.env.MANAGEMENT_URL },
  ]);

  await page.goto(`https://${process.env.MANAGEMENT_URL}/`);

  await expect(page).toHaveURL(/dashboard/);

  await context.close();
});
```

**Describe the bug**
Both scripts are successful at retrieving the authentication token but somehow either I'm doing something wrong with setting the cookie in Playwright or there is an issue. I'd assume the 2 scripts should be comparable.
Furthermore: I've tried to execute login via UI using global-setup, saving the storage-state, loading it before running the test and it fails also in this case... so there is something that is not setting properly the state in this case or the cookie in the previous one.

StackOverflow reference [here](https://stackoverflow.com/questions/75295612/playwright-unable-to-login-via-api-setting-cookie-able-to-do-it-with-cypress)

**Comment by borecz** [comment]
Update: the Playwright test fails on `Webkit` and `Chrome` (at different stages) and passes on `Firefox`

**Comment by dgozman** [comment]
@borecz Your code looks good. Perhaps there is an issue in Playwright, but I am not sure how to tell that. Could you please provide a repro that we can run locally?

**Comment by borecz** [comment]
Hi @dgozman thanks for quick reply. Unfortunately due to company policy I'm not authorized to share a testing environment outside of the company. 

If I can provide additional info It seems that the bug happens on Chromium but not on Firefox where I'm able to run the script I shared above and log in successfully.

**Comment by dgozman** [comment]
Without a repro, I can only recommend using [Playwright Debugging Tools](https://playwright.dev/docs/running-tests#debugging-tests) to figure out the problem yourself. Sorry.

**Comment by mxschmitt** [comment]
Closing as part of the triaging process, if you still encounter issues, feel free to file an issue with a clear repro, thanks.

**Comment by dz1dz1on** [comment]
Just wanted to mention I am struggling to add cookies. They can only be added to browser when I provide an URL property but when I've added domain + path they are not visible in browser. I've tried to debug the problem but every time playwright mark it as a correct action. 
Funny fact when I  console.log(await page.context().cookies()) they are visible in log but still not added to the browser.
