### ISSUE TITLE
How to handle SSO authentication [office 365] in Azure DevOps Pipeline.

### ISSUE THREAD

**Issue by deepchourasiya** [microsoft/playwright#20521]
I'm creating a playwright test automation tool to automate PowerBI visual application. But just got stuck while trying to create a CI pipeline using Azure DevOps Pipeline. whenever we start our test it is getting failed on the login scenario as it is an SSO-based login.

  **2 failed
    [Microsoft Edge] › test-2.spec.ts:3:1 › test ===================================================
    [Google Chrome] › test-2.spec.ts:3:1 › test ====================================================
##[error]Cmd.exe exited with code '1'.**

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by deepchourasiya** [comment]
Hey, @dgozman thanks for your response I'm not allowed to share the repo., but I can explain more about the scenario.

We have started using the playwright framework to automate the testing for our PowerBI app, and PowerBI is linked with our org. office 365 account with SSO login. So when we run the playwright test app in our local system, it takes the user as it is in our windows login. But when we try to run it using the CI pipeline using Azure DevOps pipeline it fails on the login step and the resulting test gets failed with error code '1'.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
