### ISSUE TITLE
[Question] JS doesn't execute when I call page.goto()

### ISSUE THREAD

**Issue by yolochka** [microsoft/playwright#20528]
Hi!
I have a problem. When I go to page, JS doesn't execute (`javaScriptEnabled: true` in playwright.config)
It looks like main script doesn't download (this script is needed to display content) or doesn't execute. Why ? Can Playwright block it ? Main script downloads other script from Google Tag Manager. May be, blocking could be at this stage ? 
Also, there is an error in the console: `Uncaught SyntaxError: Invalid or unexpected token`. But this error doesn't apply to the product project, this error is about metrics. Can Playwright block the execution of the main script due to an error in the console? 

How Can I solve the problem ? Maybe, should I use special flags ?
It's actual for all browsers
(I use TS + Playwright)

**Comment by dgozman** [comment]
Browser should download and run the main script like it would usually do - Playwright does not affect that. We recommend using [Playwright Debugging Tools](https://playwright.dev/docs/running-tests#debugging-tests) to figure out the problem.

**Comment by yolochka** [comment]
@dgozman I have a trace.zip with a problem
[b282cd2875830923.ZIP](https://github.com/microsoft/playwright/files/10555142/b282cd2875830923.ZIP)

````typescript
import test, { expect } from '@playwright/test';

test.only('Open SC', async ({ page }) => {
	await page.goto('https://seller.ozon.ru/', { waitUntil: 'commit' });
	await page.waitForTimeout(3000);
	await page.click('.header__button--login');
	await page.waitForTimeout(5000);
	await expect(page).toHaveURL(`https://seller.ozon.ru/app/registration/signin`);
});
````
The problem is actual when test run in CI

**Comment by dgozman** [comment]
@yolochka I looked at the trace. There are javascript files being downloaded (you can see them in the Network tab), so I assume JavaScript is running. Since there are not console messages at all, perhaps everything works as expected? One possibility is that `seller.ozon.ru` detects browser automation and does something different. I'd recommend checking with the app developers.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
