### ISSUE TITLE
[Feature]Can playwright add proxy for specific domain?

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright#20520]
Hi, we are using playwright in our pipeline. In our daily development,  we need to test and deploy the code in different environments with different ip addresses.  I have read the documents about proxy, seems once we use the proxy option to launch chromium, all the requests will go through the proxy. Can playwright add a feature that 
eg, if we want to proxy a domain A through IP x.x.x.x,  we can only add the proxy for the domain A, others will be bypassed ?

**Comment by dgozman** [comment]
@lxy2222 You can set [`proxy.bypass`](https://playwright.dev/docs/api/class-testoptions#test-options-proxy) to exclude some domains from being proxied, but there is no feature to make an explicit include-list instead.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
