### ISSUE TITLE
[Feature] Show test steps `test.step` in the `list` report (and on assertion fails)

### ISSUE THREAD

**Issue by odinho** [microsoft/playwright#20532]
Given the following test file:

```javascript
import { expect, test } from '@playwright/test';

test('My tests A', async ({ page }) => {
  await test.step('Step 1', async () => {
    expect(true).toBe(true);
  });
});

test('My tests B', async ({ page }) => {
  await test.step('Step 1', async () => {
    expect(true).toBe(true);
  });

  await test.step('Step 2', async () => {
    // several lines
    // of code here
    expect(true).toBe(false);
  });
});

```

The output of the failed assertion does not mention 'Step 2' in any place:

```
Running 2 tests using 2 workers

  ✓  1 [chromium] › web/test.spec.ts:3:1 › My tests A (39ms)
  ✘  2 [chromium] › web/test.spec.ts:9:1 › My tests B (42ms)


  1) [chromium] › web/test.spec.ts:9:1 › My tests B ================================================

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: false
    Received: true

      15 |     // several lines
      16 |     // of code here
    > 17 |     expect(true).toBe(false);
         |                  ^
      18 |   });
      19 | });
      20 |

        at step (file:///home/odin/Work/2022-tana/prototype/e2e/web/test.spec.ts:17:18)
        at file:///home/odin/Work/2022-tana/prototype/e2e/web/test.spec.ts:14:14


  1 failed
    [chromium] › web/test.spec.ts:9:1 › My tests B =================================================
  1 passed (474ms)

```
![image](https://user-images.githubusercontent.com/1451865/215783255-349b509e-a3b4-4274-9f0e-b6f8bebaffd1.png)

I am expecting it to say something like (Notice the new "Step 2" at the end):

```
  1) [chromium] › web/test.spec.ts:9:1 › My tests B › Step 2 =======================================
```

Instead, to show me the step where it failed. It could also be helpful to show that info in the summary. Especially if using soft assertions and several steps failed in one test. Like:

```
  ✓  1 [chromium] › web/test.spec.ts:3:1 › My tests A (39ms)
  ✘  2 [chromium] › web/test.spec.ts:9:1 › My tests B (42ms)
       ✘ Step 2
       ✘ Step 3
```

**Comment by jjeff** [comment]
Agreed. I'm not quite sure the purpose of `test.step()` if we don't get a report of what step was being tested when a test fails. Especially for something like this:

```JS
test(`Try doing something 20 times`, async () = {
  for (i = 0; i < 20; i++) {
    await test.step(`try #${i + 1}`, async () => {
      // test something
    })
  }
})
```

It would be really nice to know if the test failed on the first step or some subsequent step.

**Comment by amauch-adobe** [comment]
Agreed.  I would like to see this as well for reporting in general as well.

**Comment by joegoldbeck** [comment]
Similarly, we're using the Github reporter, and this just came up as a feature request on our team in order to more quickly isolate failures.

Of course we can always download and opening the html report, but that's slower when potentially diagnosing an incident :D

**Comment by scottwalter-nice** [comment]
I don't see the step listed in the error output:

![CleanShot 2024-03-08 at 11 34 40@2x](https://github.com/microsoft/playwright/assets/59891581/0e718ffc-1f17-4396-af22-d92351b7c2a8)
