### ISSUE TITLE
[Feature] Playwright close browser after generating the html reports

### ISSUE THREAD

**Issue by muhammadshoaib0k0** [microsoft/playwright#20537]
Hi, is there a way we can close the browser on which the reports show after they are generated for custom path.
it would be extremely helpful if we can close the browser after generating the report.

My current scenario, generating custom report 

PLAYWRIGHT_HTML_REPORT=path/to/project/public/system/playwright  npx playwright test --reporter=html

browser keep running . need to be able to close it with a flag

**Comment by dgozman** [comment]
@muhammadshoaib0k0 Playwright opens a tab in the default browser on your computer. You can close that tab and/or browser at any moment you'd like. I'm not really sure what exactly would you like to happen, could you please be more specific?

**Comment by muhammadshoaib0k0** [comment]
> @muhammadshoaib0k0 Playwright opens a tab in the default browser on your computer. You can close that tab and/or browser at any moment you'd like. I'm not really sure what exactly would you like to happen, could you please be more specific?

i am running the bash to pull the latest data and generate the reports, i want to close the  running server on the bash because once the reports are generated on the custom path the assets do not load properly so, have to close the server with ctrl + c to close and load the generated assets with html reporter properly, is there a way we can close the running server for html reports

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by exhannibal** [comment]
There's not comment mentioning an resolution, more like @muhammadshoaib0k0 gave up. 

I understand this.  Let's say I want an HTML report saved to file, but don't need to see it right away now ( in fact it's automated so nobody's looking anyway) .

Currently running from the command line: 

npx playwright test  --reporter=html 

starts a server serving that html output and waits fro user input to "CTRL-C" to stop the server.

If I'm executing this from bash script then the script just hangs at that point.  We don't need a server to see the HTML file, you can just open the file in a browser, the script would continue without need for input.

**Comment by muhammadshoaib0k0** [comment]
> There's not comment mentioning an resolution, more like @muhammadshoaib0k0 gave up.
> 
> I understand this. Let's say I want an HTML report saved to file, but don't need to see it right away now ( in fact it's automated so nobody's looking anyway) .
> 
> Currently running from the command line:
> 
> npx playwright test --reporter=html
> 
> starts a server serving that html output and waits fro user input to "CTRL-C" to stop the server.
> 
> If I'm executing this from bash script then the script just hangs at that point. We don't need a server to see the HTML file, you can just open the file in a browser, the script would continue without need for input.

Actually this issue has been resolved. Thanks for your cooperation.
