### ISSUE TITLE
[BUG] Failing to validate time combo box field value

### ISSUE THREAD

**Issue by ukdas** [microsoft/playwright#20536]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 18.12.1
- Browser: Chromium

**Code Snippet**
```
const time = "10:00 AM";
const timeComboBoxField = page.locator("<Selector of time combo box field">); // Field is a input type field with role combo box.
await timeComboBoxField.fill(time);
await timeComboBoxField.press("Tab");
const retrievedFieldValue = await timeComboBoxField.getAttribute("value");
const compareValue = time === retrievedFieldValue;
expect(compareValue).toBe(true);
```

**Describe the bug**

Failing to validate time combo box field value. Sorry, I am not able to provide the whole code snippet along with all required details as I can't share the information here. 

I know, the above code snippet will not work to reproduce the issue. It's provided to just show the validation part.

When validating, the `getAttribute()` value is returning like below (Second line) and that's causing issue to fail the scenario.
![Error](https://user-images.githubusercontent.com/64302433/215823532-2ce3ab5b-7f41-4906-970e-b1e42071acc7.png)

Please note, the issue is occurring with latest `1.30.0` version only. It's working fine with `1.29.0` version as expected.

Could you please take a look into this issue, if the issue is from playwright side?

**Comment by RAFraz** [comment]
I'm experiencing the same issue.  This char https://www.compart.com/en/unicode/U+202F seems to be injected between the seconds and period (AM/PM) but only when running in Playwight.  The char also causes a slight shift in the AM/PM of the image as seen here.
![diff-step2](https://user-images.githubusercontent.com/7307873/215849381-430c31e9-da2f-4a0b-b842-795773ed6e3f.png)

**Comment by dgozman** [comment]
@ukdas I guess the rendering of the site changed between 1.29 and 1.30? Note that each Playwright version includes new browser versions, so maybe that's how Chromium renders it. I am not 100% sure since there is no repro.

@RAFraz If you have a repro that shows how things render differently when running with Playwright, please file a new issue and we'll happily take a look!

**Comment by RAFraz** [comment]
So I checked the version of Chrome that Playwright 1.30.0 installs and found that is it 110.0.5481.38 (Developer Build).  That version of Chrome has this new character between our seconds and AM/PM period.  The official build that i have on my machine 109.0.5414.120 (Official Build) does not have the weird char.  Checking out Chrome Canary (112.0.5571.0 (Official Build) canary)  I also see the same odd char so the change is due solely to a change in Chrome itself.  I'm not sure why Playwright would install a developer build of Chrome with a version beyond the current official build but maybe there are reasons not to use the official build.

**Comment by RAFraz** [comment]
This explains the Chrome version --> https://playwright.dev/docs/browsers#chromium 
Got to read the manual i suppose :)

**Comment by dgozman** [comment]
I am glad that you figured it out! Playwright is designed to catch regressions early, before the next Chrome version reaches everyone, so you would have a chance to fix your page.
