### ISSUE TITLE
[Feature] page.waitForActionable()

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2054]
Would a `page.waitForActionable()` make sense to implement? I've been needing to use a `waitForSelector` when it comes to a table where I want to pick out all <tr> with `page.$$()`. But the table is somewhat animated and it can mess up things.

What I mean by `waitForActionable()` in regards to `waitForSelector()` is that it would behave like the Auto-waiting functionality works like actions, see https://github.com/microsoft/playwright/blob/master/docs/core-concepts.md#auto-waiting. There is a difference between these two in that `waitForSelector` does not wait e.g. for transitions to finish. And the other things specified in that list.

I am not sure this is a great idea altogether, but wanted to bring it up and at least we can close the issue with an explanation as to why it might be bad.

Reference where this discussions started: https://github.com/microsoft/playwright/issues/1981

**Comment by aesyondu** [comment]
I've been looking for something similar. My firefox tests especially are flaky because of the animation of modals. Even if I `waitForSelector` the modal, `page.fill` just fail sometimes.

**Comment by thernstig** [comment]
It's possible there should instead be an option to `waitForSelector` that defauls to the "Auto-waiting" logic, but has an option to only work like it does today (not caring about e.g. animations).

**Comment by dgozman** [comment]
With #3501, version 1.4 will provide the following api:

```js
// Stable, similar to click actionability check.
await handle.waitForElementState('stable');
// Visible.
await handle.waitForElementState('visible');
// Enabled, similar to fill actionability check.
await handle.waitForElementState('enabled');
```

So far, this seems like covering this case. Please comment if that does not work.
