### ISSUE TITLE
[Question]what's difference between page.locator("xx",has=Locator) and page.locator("xx").filter(has=Locator)

### ISSUE THREAD

**Issue by winka2020** [microsoft/playwright#20543]
html like:
```
<ul>
  <li>
    <h3>Product 1</h3>
    <button class="button">Add to cart</button>
  </li>
  <li>
    <h3>Product 2</h3>
    <button class="button">Add to cart</button>
  </li>
</ul>
```
when i wanna locating the first `<li>`, i can write like:
the first solution:
`page.locator("li",has=page.get_by_text("Product 1"))`

the second solution:
`page.locator("li").filter(has=page.get_by_text("Product 1"))
`
what's any detailed difference between these two solutions?

**Comment by dgozman** [comment]
@winka2020 There is no difference at all. Use whatever feels better 😄

**Comment by winka2020** [comment]
Get it
