### ISSUE TITLE
[BUG] Navigation timeout is overwritten by action timeout

### ISSUE THREAD

**Issue by ArturDuziak** [microsoft/playwright#20549]
**Code Snippet**

Here is a part of the Playwright config: 

```javascript
use: {
    navigationTimeout: 0,
    actionTimeout: 5000,
    trace: 'retain-on-failure',
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    headless: true,
    baseURL: `http://localhost:3000/`,
  },
```

**Describe the bug**

I am not sure if this counts as a bug, but yesterday I ran into a weird behavior that I wasn’t fully expecting, what I did was set Action timeout in my config to 5 seconds (`actionTimeout: 5000`) to speed up the failure of the tests (as I do not want to wait 30 seconds for the test to fail on the action). But one unexpected side effect that occurred was that my `page.goto('…')` started failing and throwing timeout errors (because the app sometimes takes longer to load) - it had a timeout of 5 seconds, the same as an action one - even though it wasn’t set in the config, in this situation, I would expect the default value of 0 (no timeout) to be used. I tried to set the navigation timeout in the config back to 0, but it still gets overwritten by action timeout. It only works when the navigation timeout is set to a higher number than 0.

I started digging into the source code and noticed that in the [packages/playwright-test/src/index.ts](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/index.ts#L295) the navigation timeout takes the value of action timeout if it is defined (or if navigation timeout is set to 0) - is this intentional? If there is a reason for it, then I won't argue, but the timeout [documentation doesn’t clearly explain it anywhere](https://playwright.dev/docs/test-timeouts), when I read it, I thought that `actionTimeout` is solely connected to [actions](https://playwright.dev/docs/input) (so click, fill, select, type, etc.) and doesn’t affect navigation (or other any timeout) because navigation has its own timeout with `page.goto` function in the example. I will be happy to help and commit changes to the documentation if needed, but I do not know the whole reasoning behind this.

**Comment by dgozman** [comment]
@ArturDuziak You are absolutely right, this is a bug. Great investigation!

**Comment by ArturDuziak** [comment]
Awesome, thanks for the lightning-fast actions 👍
