### ISSUE TITLE
[Muted Test] Is there any in-built solution to Muted Failed tests as skipped in JUnit Test Report?

### ISSUE THREAD

**Issue by kp-abhishek-agrawal** [microsoft/playwright#20548]
Hi,

In order to improve our build pipeline stability, We want to modify the JUnit test report to mark muted Failure test as 'Skipped'.

Let's say We have a given list of muted Testcase names in a file fetched from server, Is there a way to mark those test as skipped in JUnit Test Report XML file if they are failed? Do we have any built -in solution to modify JUnit result XML file?

**Comment by dgozman** [comment]
@kp-abhishek-agrawal There is no functionality in Playwright to modify JUnit XML files, but you can probably find some npm package that helps with modifying xml files.

That said, look into [`test.skip()`](https://playwright.dev/docs/api/class-test#test-skip-4). If you mark tests as skipped in advance, not only they will be "skipped" in the report, but also they would not run and waste resources. Let me know if that helps.

**Comment by kp-abhishek-agrawal** [comment]
Thanks for the response. We want to still run muted Tests because we would like to generate a stability report for them in future to keep track. 

Hence, to achieve, we tried using a Custom Report function to update the result status for each muted test.

**Comment by dgozman** [comment]
> Hence, to achieve this, we tried using a Custom Report class to update the result status for each muted test. & seems this solution works.

Sounds great!
