### ISSUE TITLE
[Feature] Removal of .$ functions

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2055]
I've always found the `page.$`, `page.$$` (and their eval and frame etc. counterparts) weird as function names. Mainly for the fact that `$` really is no English word giving any information as to what they do. I _believe_ this might come from jQuery, but I have no idea why Playwright would need to follow that style.

Now that e.g. `page.waitForSelector()` exists, is there e.g. any need at all for `page.$`? I realize there is no equivalent for `page.$$` (and maybe the evals, although `element.innerHtml()` etc. now exists that can be done outside of an eval.)

**Comment by pavelfeldman** [comment]
Your suggestion makes total sense, but it is too late for us to back from the beloved $. It does not wait for selector by the way, so if you know element it there, that's the fastest way of getting a hold of a handle...

**Comment by thernstig** [comment]
My reasoning was that since you are in beta, there wasn't any "too lates" yet 😄

Would adding documentation to the `.$` and `.$$` at least be good to mention they do not wait for selectors? Since most users will end up using the direct action commands and `waitForSelector()` (guessing here) - I'd say some users who never used Playwright (nor Puppeteer) would know the difference between e.g. `page.$()` and `page.waitForSelector()` by just reading the docs (if they are lucky they can guess).
