### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rupertting88** [microsoft/playwright#20553]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Linux
- Node.js version: 16.19.0
- Browser: Chromium
- Extra: CI build in GitHub Actions

**Describe the bug**
`beforeAll` and `afterAll` hooks runs more than once. Runs once as expected, then a second time after tests are completed.

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by mxschmitt** [comment]
Its expected that beforeAll can run multiple times, since you will get a new worker on test-failure, see here: https://playwright.dev/docs/test-parallel
