### ISSUE TITLE
[BUG] Firefox problems when running v1.30.0 inside Webstorm snap terminal

### ISSUE THREAD

**Issue by jpveooys** [microsoft/playwright#20555]
**Context:**

## System:
 - OS: Linux 5.15 Ubuntu 22.04.1 LTS 22.04.1 LTS (Jammy Jellyfish)
 - Memory: 11.14 GB / 27.24 GB
 - Container: Yes (reported by `npx envinfo`, even outside of snap)

## Binaries:
 - Node: 18.13.0 - /usr/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.19.3 - /usr/bin/npm

## Languages:
 - Bash: 5.1.16 - /usr/bin/bash

**Describe the bug**

Slightly odd problem here (and it may be out of Playwright's control). 

When I run Playwright v1.30.0 inside the terminal in the snap version of WebStorm (e.g. version 2022.3.2), it is unable to launch Firefox with varying symptoms (depending on headless vs headed).

### When running headless

Playwright hangs indefinitely. After pressing Ctrl-C, it prints:

```
    Test was interrupted.

    Fixture "browser" timeout of 0ms exceeded.
```

### When running headed

There are a few errors. First, this:

![image](https://user-images.githubusercontent.com/66470099/216064760-3e304f8e-dd01-4bee-ab01-709e075b2e54.png)

Followed by:

```
[WebServer] (node:342129) [DEP0066] DeprecationWarning: OutgoingMessage.prototype._headers is deprecated
(Use `node --trace-deprecation ...` to show where the warning was created)
  1) [firefox] › example.spec.ts:4:7 › @setA › test a ==============================================

    browserContext.newPage: Protocol error (Browser.newPage): Unexpected number of tabs in the new window: 2 newPage@chrome://juggler/content/TargetRegistry.js:317:13
```

The extra tab is a Firefox privacy notice (https://www.mozilla.org/en-US/privacy/firefox/). The browser looks like this:

![image](https://user-images.githubusercontent.com/66470099/216066702-7390b9e4-fefc-43cc-8801-215d01dcfb63.png)

It says it is using the profile `/tmp/playwright_firefoxdev_profile-pkwZ9l` (which is presumably correct).

I see various differences in the Firefox configuration that is used in this scenario. For example, with v1.30.0 inside snap:

```
  "processes": {
    "remoteTypes": {
      "extension": 1,
      "web": 1,
      "webIsolated": 1,
      "privilegedabout": 1,
      "prealloc": 3,
      "socket": 1
    },
    "maxWebContentProcesses": 8
  },
```

v1.29.2 inside snap:

```
  "processes": {
    "remoteTypes": {
      "extension": 1,
      "web": 1,
      "socket": 1
    },
    "maxWebContentProcesses": 60000
  },
```

### When there is no problem

There is no problem with Playwright v1.29.2 inside WebStorm snap. There is also no problem when running Playwright v1.30.0 outside of WebStorm snap. And there is also no problem if I run Playwright inside the official container image inside WebStorm.

### Repro

The specific project doesn't seem to matter, but I pushed a simple example here: https://github.com/jpveooys/playwright-repro/tree/firefox-1-30-0 (where `playwright test --project firefox` can be run).

**Comment by dgozman** [comment]
It looks like Firefox reads some preferences in this setup and overwrites Playwright's own preferences. I recognize "60000" value that we set, and it is reverted to "8".

Perhaps that comes from snap policies? [This discussion](https://forum.snapcraft.io/t/firefox-snap-no-longer-reads-usr-lib-firefox-for-customization/29713/28), [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1786742) and [this issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1785278) look relevant. The latter one is fixed in 108, which is exactly the version we use in v1.30. Not sure how to follow up though - any ideas?

**Comment by jpveooys** [comment]
Those links are interesting. The ironic thing is that I don't use the snap version Firefox, I use a deb version! I'll try and investigate a bit more later and see if I can find anything else out.

**Comment by jpveooys** [comment]
I was able to confirm that copying `playwright.cfg` from `~/.cache/ms-playwright/firefox-1372/firefox` to `/etc/firefox` resolves the problem.

Unsetting all SNAP environment variables (`unset ${!SNAP*}`) also resolves it.

**Comment by aslushnikov** [comment]
@jpveooys any chance you can give me a dump of SNAP variables that you have there?

**Comment by jpveooys** [comment]
This is enough to break things:

```
SNAP_NAME=webstorm SNAP_INSTANCE_NAME=webstorm npx playwright test --project firefox
```

(The Firefox source code helped determine that: https://github.com/mozilla/gecko-dev/blob/4f7f6c04558f9f9844b1c3076ea75589b12f87ff/widget/gtk/WidgetUtilsGtk.cpp#L130-L158)

**Comment by aslushnikov** [comment]
Nice, thank you! Let me try to bake a fix for this.

**Comment by aslushnikov** [comment]
@aslushnikov the fix has landed on tip-of-tree and will be live in our tomorrow's canary. Could you please try installing `npm i @playwright/test@1.31.0-alpha-feb-8-2023` tomorrow and see if it fixes things for you?

**Comment by jpveooys** [comment]
Hi @aslushnikov

Can confirm `@playwright/test@1.31.0-alpha-feb-8-2023` is working fine. Thanks for the fix!

**Comment by aslushnikov** [comment]
Awesomeness! Thank you for taking time to file & verify!
