### ISSUE TITLE
[BUG] Camera and Microphone permissions are not being granted in Firefox and Safari

### ISSUE THREAD

**Issue by mycroft-cesar** [microsoft/playwright#20563]
**Context:**
- Playwright Version: 1.30.0
- Operating System: MacOS Ventura 13.0
- Node.js version: 16.15.0
- Browser: Firefox, WebKit

**Code Snippet**

```javascript
import { Page } from '@playwright/test';

abstract class Whatever {
public readonly page: Page;

constructor(page: Page, url?: string) {
    this.page = page;
    if (url) {
      this.url = url;
    }
  }

 public async grantPermissions(permissions: BrowserPermission[]): Promise<void> {
    await this.page.context().grantPermissions(permissions); // permissions: ['camera', 'microphone']
  }
}
```

**Describe the bug**

I have some tests to enter in the conference room but for that I need to grant permissions to use the Camera and the Microphone and for some reason the test passes for Chrome but it doesn't for Firefox and Safari. The error I see is basically:

```
browserContext.grantPermissions: Unknown permission: camera
```

Whatever comes first in the permissions Array will appear as unknown permission. 
I already have tried some workaround suggested in other threads, such as setup the permissions for each browser in the playwright config file but it didn't work either.

**Comment by dgozman** [comment]
See also #7635 and #11714.

**Comment by mycroft-cesar** [comment]
@dgozman is there a way of mocking the devices? (camera, microphone and speakers). I didn't find anything about it

**Comment by dgozman** [comment]
@mycroft-cesar There is no support for faking/mocking the devices in Playwright today.

**Comment by TDL-EdgarsEglitis** [comment]
In Firefox you can grant these permissions by changing the user preferences. I've confirmed this works in playwright-python, so it should probably work in JS as well. Try something like this:

```javascript
const browser = await firefox.launch({
  firefoxUserPrefs: {
    'permissions.default.microphone': 1,
    'permissions.default.camera': 1
  }
});
```
Note that this change applies on the browser level, not context level.

**Comment by tanxeel** [comment]
Temporary solution
```
await page.evaluate(() => {
      navigator.mediaDevices.getUserMedia({ audio: true, video: true });
});
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by eatsjobs** [comment]
This could be useful if you need to mock the camera stream programmatically https://github.com/eatsjobs/media-mock (spoiler: I'm the author)
