### ISSUE TITLE
[QUESTION] multipart/form-data request missing content-type header

### ISSUE THREAD

**Issue by UserProgrammer** [microsoft/playwright#20566]
Making the following multipart/form-data request to my backend:
```
    let options = {
      baseURL: BASE_URL,
      extraHTTPHeaders: {
        'Authorization': BASIC_AUTH
      },
      multipart: {
        file: {
          name: filepath,
          mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
          buffer: spreadsheetBuffer
        }
      }
    }

    let requestContext = await request.newContext(options);

    let response = await requestContext.post('endpoint/path')
```

The backend errors with:
```
... Content type '' not supported
```

I previously set `Content-Type: multipart/form-data` explicitly, but I was getting another error regarding a missing multipart boundary. I came across this issue (https://github.com/microsoft/playwright/issues/20249), which was resolved by removing the `Content-Type` header from the request options. Unfortunately, that didn't resolve my issue

**Comment by dgozman** [comment]
@UserProgrammer You should pass your `multipart` when calling `requestContext.post()` instead of `request.newContext()`. Take a look at [these examples](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch). Let me know if this helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
