### ISSUE TITLE
[Question] Mocking network response sequence

### ISSUE THREAD

**Issue by blordpluto** [microsoft/playwright#20562]
Hi, first: thanks for an incredible tool.

I have a situation where I want to test some user actions that trigger some out-of-order network responses. In other words, `req1`, `req2`, `req3` fire in order based on some user events, but might return in the reverse order: `resp3`, `resp2`, `resp1`. I've already got a mocking system in place, with network requests all being supplied by local mock files, and everything works so far. 🤞 

I see how I could maybe do this with `page.route` using hardcoded timeout values in the second argument. But I'm a bit allergic to the hardcoded waits. Is there perhaps a missing `delay` argument in the `page.route` API or am I missing something fundamental? What's the idiomatic way to handle this sort of thing? Any help greatly appreciated.

**Comment by dgozman** [comment]
> But I'm a bit allergic to the hardcoded waits. Is there perhaps a missing delay argument in the page.route API

If we were to add `delay` argument, it would be just a `waitForTimeout` inside anyway 😄  So I'd recommend calling `page.waitForTimeout()` from inside the route handler. Would that work for you?

**Comment by blordpluto** [comment]
Well, the documentation on `page.waitForTimeout()` warns the reader with the note that:

> Note that page.waitForTimeout() should only be used for debugging. Tests using the timer in production are going to be flaky.

I am not debugging. I want to run production tests in which the network responses happen in the reverse order of the network requests (based on a specified sequence of user events). What's the most idiomatic way to do this?

Some simplified code for illustrative purposes:

```typescript
// this will be requested first, but should respond third
await page.route('https://service.com/endpoint1/*', async (route) => {
  route.fulfill({
    status: 200,
    body: JSON.stringify(responseMock1),
  });
});

// this will be requested second, and should respond second
await page.route('https://service.com/endpoint2/*', async (route) => {
  route.fulfill({
    status: 200,
    body: JSON.stringify(responseMock2),
  });
});

// this will be requested third, and should respond first
await page.route('https://service.com/endpoint3/*', async (route) => {
  route.fulfill({
    status: 200,
    body: JSON.stringify(responseMock3),
  });
});
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
