### ISSUE TITLE
[REGRESSION]: Large pages cut off the bottom when converted to PDF

### ISSUE THREAD

**Issue by nmccalme** [microsoft/playwright#20565]
**Context:**
- GOOD Playwright Version: 1.27.0
- BAD Playwright Version: 1.28.0
- Operating System: Windows and Linux both tested
- Extra: Using the Chromium browser

```csharp
        var playwright = await Playwright.CreateAsync();
        var browser = await playwright.Chromium.LaunchAsync();
        await using IBrowserContext context = await browser.NewContextAsync();
        var webPage = await context.NewPageAsync();
        var response = 
                await webPage.GotoAsync(
                        model.Url!,
                        new PageGotoOptions()
                        {
                            Timeout = model.PageLoadTimeout,
                            WaitUntil = WaitUntilState.Load
                        });
        // Wait for a custom selector to ensure rendering is finished, if provided
        await webPage.WaitForSelectorAsync(
            model.WaitFor,
            new PageWaitForSelectorOptions()
            {
                State = WaitForSelectorState.Attached
            });

        return await webPage.PdfAsync(
            new PagePdfOptions()
            {
                DisplayHeaderFooter = model.Pdf?.DisplayHeaderFooter,
                Format = model.Pdf?.Format,
                Height = model.Pdf?.Height,
                Landscape = model.Pdf?.Landscape,
                PageRanges = model.Pdf?.PageRanges,
                PreferCSSPageSize = model.Pdf?.PreferCssPageSize,
                PrintBackground = model.Pdf?.PrintBackground,
                Margin = GetMargin(model.Pdf?.Margin),
                Scale = model.Pdf?.Scale,
                Width = model.Pdf?.Width
            });
```

**Describe the bug**

We are using Playwright to generate PDFs of internal web pages.  When we upgraded to 1.28.0, we discovered that pages that rendered into PDFs with multiple pages (tough to determine an exact breaking point, but certainly at 3 PDF pages) started cutting off at the bottom.

**Comment by dgozman** [comment]
@nmccalme Did you try printing your page to pdf in Google Chrome browser, without Playwright? I think this could be a Chromium change, a new printing feature `LayoutNGPrinting` was enabled recently.

If things work in Google Chrome, but not with Playwright, could you please provide a publicly accessible page that is printed incorrectly?

**Comment by nmccalme** [comment]
@dgozman I'm going to close this as a duplicate of #9228.  Looks like our symptoms are a little bit different, but incorporating the workaround mentioned there (disable LayoutNGPrinting) did work.  So we just need to wait for the upstream bugfix to make it in.

**Comment by pdsuwwz** [comment]
I have just migrated from `puppeteer` to `playwright@1.37.1`, reproduced the same problem

**Comment by last-Programmer** [comment]
I am having this issue too wiht latest version of playwright and chroimun version 128.
