### ISSUE TITLE
[Feature] Ability to override font-display behavior

### ISSUE THREAD

**Issue by ericmatthys** [microsoft/playwright#20570]
When using Playwright to take screenshots for visual regression tests, it's important that page loads are consistent. While `font-display: optional` might be preferred in production, it can vary what you see depending on the timing of the font load `font-display: block` ensures that the custom font will always load for the screenshot. It can be tricky to vary this style when building an app to run for Playwright tests, as it's part of the `@font-face`. I've used https://github.com/vanilla-extract-css/vanilla-extract to do so based on an environment variable in the past, but that is a big change for a relatively small concern if a project is not already using it. Other suggestions for how to do this without a Playwright option are welcome. 😄

**Comment by dgozman** [comment]
@ericmatthys Perhaps you can iterate over `document.fonts`, set [`display`](https://developer.mozilla.org/en-US/docs/Web/API/FontFace/display) value on them, and await [`fonts.ready`](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/ready)? Do all of that in `page.evaluate()` call. Let me know if that works.

If you are asking for some explicit support in Playwright, I can leave this feature open, but it is very unlikely we will prioritize it.

**Comment by ericmatthys** [comment]
Thanks, I'll give it a try!

**Comment by mxschmitt** [comment]
Looks like its answered, please re-file if you still encounter issues with Playwrght.

**Comment by ericmatthys** [comment]
I can't get the approach mentioned by @dgozman to work reliably. I think setting `display = 'block'` after the font exists in `document.fonts` does not reliably influence how the browser handles the font. I've even tried something like this to set it as early as possible:

```tsx
  public async goto(url) {
    const responsePromise = page.goto(url);

    await page.waitForFunction(
      () => {
        if (!document.fonts.size) {
          return false;
        }

        document.fonts.forEach((font) => {
          font.display = 'block';
        });

        return true;
      },
      null,
      { polling: 5 }
    );

    await page.evaluate(() => document.fonts.ready);

    return responsePromise;
  }
```

But this is not consistently using the custom font still.
