### ISSUE TITLE
[Feature] Add parameter 'link' to Annotations

### ISSUE THREAD

**Issue by michael-yelnikov** [microsoft/playwright#20584]
In most cases in my practice annotations using for linking bugs for Jira (as an example).
But now we have only `type` and `description`. 

```
    test('Test is red, bug in product!', async () => {
        test.info().annotations.push({ type: 'Bug is created', description: 'https://jira.com/BUG-123' });
        // ...
    });
```

![image](https://user-images.githubusercontent.com/16642847/216286383-d4823cf6-6405-40f4-a0ce-9d4708900c07.png)

The suggestion is: to add one new parameter `link`
And show it to the reporter as a clickable link. Link should be opened in new tab (target: _blank): 

![image](https://user-images.githubusercontent.com/16642847/216288165-b5f8cbe2-d041-4739-ad3a-ba914834e0a2.png)

**Comment by dgozman** [comment]
@michael-yelnikov We ourselves do the same, but use `type: 'issue'` instead 😄  Making links clickable in the html report definitely makes sense.
