### ISSUE TITLE
I am trying to navigation a home pages but it shows access denied or blocking. 

### ISSUE THREAD

**Issue by ramprakashyadav** [microsoft/playwright#20580]
I'm using playwright for web scraping when I'm working on a few sites for configurations but all of them
have a common issue of Access Denied/Forbidden response on the homepage
itself. We found them providing good response on Indian IP's but not on
several US/UK/FR IPs as well as luminati-dc/ipdealer service IP's. can anyone guide me for this.

**Comment by ramprakashyadav** [comment]
Here is the function which i use for to navigation

    def fetch_with_object_return(
            self, playwright, url, method="get", post_data=None, retry_count=0, headers=None, wait_for_selector=None, capture_screenshot=False, screenshot_filename='screenshot.png', timeout=120000,
            extensions=None):
        """Open a browser and fetch the given page.

        If extensions are passed the browser object will be none, the browser will not be in incognito
        mode, and it will be a headful browser. Currently available extensions are 'anticaptcha'
        to work with https://anti-captcha.com, and 'textmode', which will prevent images from being downloaded.

        Args:
            playwright: playwright object
            url (str): The url to load
            method (str): get, post, del, put
            post_data (dict) data to post if method is "post"
            retry_count (int): the number of attempts at fetching the current content
            extensions (array): List of browser extension names that should be loaded from browser_extensions.json.
        Returns:
            page and browser objects
        """
        self._history.elements['network-fetches'] += 1
        browser = None

        try:
            if retry_count >= RETRY_LIMIT:
                logger.error("ERROR: Maximum retry limit reached while fetching " + url)
                # make sure that we have a proxy
            else:

                self._load_proxy()

                # get the html of the url using a proxy
                log_msg = "Fetching URL " + url
                if post_data:
                    log_msg += " with POST data: " + str(post_data)
                logger.notice(log_msg)

                if self._proxy is not None:
                    self._history.store_domain(url, self._proxy.urls()['http'])

                self._history.elements['requests-succeeded'] += 1

                html = None
                browser = None
                context = None
                plugin = False
                captcha_vendor = 'anti-captcha'

                if extensions is not None:
                    plugin = True
                logger.notice(f"Printing plugin status:{plugin}")

                if extensions is not None:
                    # launch normal, headful browser with extension
                    context = self.browser_context_with_extensions(sync_process=playwright, timeout=timeout, extensions=extensions)
                else:
                    # launch browser in incognito mode
                    browser = self.browser(sync_process=playwright)
                    context = browser.new_context(ignore_https_errors=True,
                                                  java_script_enabled=True,
                                                  no_viewport=True
                                                  )

                page = context.new_page()
                if plugin:
                    page.on("console", lambda console_message: self._log_console(console_message.text, url=url, plugin=plugin, captcha_vendor=captcha_vendor))

                page.on("request", lambda request: self._log_ajax(request))
                page.goto(url, timeout=timeout)

                if wait_for_selector is not None:
                    page.wait_for_selector(wait_for_selector)

                if capture_screenshot:
                    self.save_screenshot(page=page, file_name=screenshot_filename)

                return (page, browser, context)
                # return html
        except Exception as e:
            if e is not None:
                self._history.elements['requests-failed'] += 1
                logger.error(f"Exception occurred fetching {url}: " + str(e))

                if browser is not None:
                    browser.close()

                self.cleanup()
                return self.fetch_with_object_return(playwright, url, method=method, post_data=post_data, retry_count=retry_count + 1, headers=headers, wait_for_selector=wait_for_selector, capture_screenshot=capture_screenshot, screenshot_filename=screenshot_filename, timeout=timeout,
                                                     extensions=extensions)

**Comment by ramprakashyadav** [comment]
Can Anyone can do change in this will be very helpfull.

**Comment by dgozman** [comment]
@ramprakashyadav When web server blocks based on IP, there is nothing Playwright can do to help. Sorry!
