### ISSUE TITLE
[Feature] Allow Downloads to use "natural" browser filename

### ISSUE THREAD

**Issue by rwoll** [microsoft/playwright#2058]
When end-to-end testing sites, it's helpful to assert that the filename of a download on disk (as determined by the browser) aligns with an expectation.

For instance, if I have the following code:

```
<a href="/my/download" download="product.zip">…</a>
```

I want to write an assertion that the downloaded file is `product.zip` (or some mild variant). Browsers have all sorts of different logic to determine what to name a downloaded file, so it would be good to get it from the browser itself.

As of `playwright@v0.15.0`, the download path ends up being a GUID (assuming you've set `acceptDownloads` to `true`) since the `downloadBehavior` is hard-coded to be `allowAndName`. It would be helpful allow the user to set the `downloadBehavior` to allow for natural filenames (i.e. `allow`), and have someway to deterministically tie the download GUID (contained in the download events) with a filename.

The extended `download` API might look like:

```js
const dl = await page.waitForEvent('download');
console.log(dl.filename());
```

---

I've submitted the following MR in the Chromium repo to expose the filename in the `Page.downloadProgress` event: https://chromium-review.googlesource.com/c/chromium/src/+/2174778/.

Once that or some variant lands, I'd be more than happy to help make the changes in Playwright (assuming someone else can volunteer to patch the CDP events for Firefox and WebKit).

**Comment by pavelfeldman** [comment]
Your plan looks good. We already have suggestedFile in Juggler (Firefox). I can add it in RDP (WebKit).

**Comment by aslushnikov** [comment]
Looks like this is fixed now across the board with [`download.suggestedFilename()`](https://github.com/microsoft/playwright/blob/master/docs/api.md#downloadsuggestedfilename)
