### ISSUE TITLE
[BUG] Test specs are failed with "beforeAll hook timeout exceeded" error in parallel run

### ISSUE THREAD

**Issue by mdemenko** [microsoft/playwright#20598]
Context:

Playwright Version: [1.29.2]
Operating System: [Windows 10]
Node.js version: [18.12.1]
Browser: [Chromium]

Description:
Test specs start to failing with  "beforeAll hook timeout exceeded" error after upgrading PW to 29.2. Hooks just failed on new browser page creation. It's also reproducible for some afterAll hooks (but not for all specs). I have paralel run with 8 workers. 

![Playwright Test Report](https://user-images.githubusercontent.com/8157779/216429861-50dd9f82-baf0-4f3c-a872-50a33fb857e5.png)

Note: I've downgrade to 1.28 and issue isn't reproducible.

**Comment by mdemenko** [comment]
Seems it was similar issue for Jest https://github.com/facebook/jest/issues/11607

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by mdemenko** [comment]
I'm managed to reproduce on my laptop https://github.com/mdemenko/reproduce.git (need to run tests several times) 
![Playwright Test Report](https://user-images.githubusercontent.com/8157779/216671982-29a4845d-1abf-493a-8ded-4657946ad8d5.png)

**Comment by mxschmitt** [comment]
This is mostly caused because your machine is overbooked - so to reduce the flakiness simply reduce the workers - we also strongly discourage from launching a browser manually inside beforeAll and using the existing browser instance, this would look this that: 

![image](https://user-images.githubusercontent.com/17984549/217219627-97cbabb2-dee4-463f-9c7c-b90d58397bde.png)

**Comment by mdemenko** [comment]
@mxschmitt Thanks for advice. My main concern was that with current implementation tests were passed without any errors on 1.28 version. And this error starts to appear on 1.29.2. So I'm assumed that it's due to update.
I'll update hooks accordingly and check.

**Comment by mxschmitt** [comment]
Then closing this issue for now, please re-file then if you still encounter issues.

**Comment by mdemenko** [comment]
@mxschmitt Facing next issue on PW 1.32.2:

- for paralel run some tests spec are failing due to Error: browser.newPage: Browser closed.
- issue is intermittent (each time for different spec)
- issue doesn't depend on workers amount (I've tried with 8,6,4 workers)
![Before All hook](https://user-images.githubusercontent.com/8157779/230617919-db029d81-1ba1-4d4b-86ed-0056a2623833.png)

<launching> C:\Users\test\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\test\AppData\Local\Temp\playwright_chromiumdev_profile-kAgOwg --remote-debugging-pipe --no-startup-window
<launched> pid=63540
[pid=63540][err] [63540:59736:0407/135115.472:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[pid=63540] <gracefully close start>
