### ISSUE TITLE
[BUG] Using locator twice will make Playwright return empty string

### ISSUE THREAD

**Issue by pawlarius** [microsoft/playwright#20592]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac M1
- Node.js version: 16.13.1
- Browser: Chromium

**Code Snippet**

We have a code that will locate element inside td.
The weird thing is if we called the same code twice, the second line will fail and playwright somehow can't resolve the text content.

In the screenshot, line 27 & 28 have the exact same line.
In line 27 it works fine by expecting "Mayonaise" inside the locator.
But somehow line 28, Playwright said it expect empty string instead of "Mayonaise".

<img width="836" alt="Screen Shot 2023-02-02 at 21 51 24" src="https://user-images.githubusercontent.com/27823957/216357531-8ecce2c2-4e82-44c5-9f70-31991a0a73da.png">

```javascript
await expect(orderLineRow.locator(`td >> nth=${0}`)).toHaveText(orderLine.productName); // -> OK
await expect(orderLineRow.locator(`td >> nth=${0}`)).toHaveText(orderLine.productName); // -> Somehow this FAIL
```

I have tried other variation too, such as:

```javascript
const myElement = orderLineRow.locator(`td >> nth=${0}`)
await expect(myElement).toHaveText(orderLine.productName); // -> OK
await expect(myElement).toHaveText(orderLine.productName); // -> Somehow this FAIL
```

and I have even tried select another nth index and it return the same error.

```javascript
await expect(orderLineRow.locator(`td >> nth=${0}`)).toHaveText(orderLine.productName); // -> OK
await expect(orderLineRow.locator(`td >> nth=${1}`)).toHaveText(orderLine.productName); // -> Somehow this FAIL
```

**Describe the bug**

Playwright seems to have a bug when we call the same code twice, or call the locator twice, playwright will failed to resolve the text content inside that locator.

Is this something that Playwright can't support or I'm missing something?

**Comment by dgozman** [comment]
@pawlarius This should work, and your code looks good. Could you please provide a repro that we can run locally? We'll happily take a look.

**Comment by pawlarius** [comment]
Hi @dgozman thanks for getting back to me.
So I extract the logic to this public repo: https://github.com/pawlarius/debug-app

I tested it and it also return the same error, but the trigger somehow changed from using locator twice become locator thrice.

I'm not sure why on this new isolated folder that I made the error will only be triggered on the third try..
<img width="944" alt="Screen Shot 2023-02-03 at 01 46 37" src="https://user-images.githubusercontent.com/27823957/216420903-0a0256e3-b96a-4bb0-b63a-32615d4db4dd.png">

**Comment by dgozman** [comment]
@pawlarius Thank you for the repro! I was able to reproduce the issue. Turns out, there is a missing `await` at [this line](https://github.com/pawlarius/debug-app/blob/main/playwright-demo/scenarios/demo/expectOrderDetail.ts#L59). When you add this `await`, the test starts working.

That said, the "Timed out waiting for ..." error is misleading. I will look into that.

**Comment by pawlarius** [comment]
I felt silly now, thank you for taking the time to debug this.
Do you mind share how do you find it? I actually tried using PWDEBUG=1, and I see the code is pointing to the right element and the browser will close because Playwright resolves it to empty string.

**Comment by dgozman** [comment]
@pawlarius I thought there is a bug in Playwright, and so I debugged Playwright sources. I don't think you should ever do the same 😄  We should improve the error reporting so that the problem is more obvious, we'll work on that.

**Comment by pawlarius** [comment]
I see, thankyou then for your help 🙏
