### ISSUE TITLE
[QUESTION]Is there a way to make is_visable() detect a region that i set instead of the whole page

### ISSUE THREAD

**Issue by Edmounds** [microsoft/playwright#20605]
In the page,there are many parts,and every part has an element which has the same class(other args are complicated.Meanwhile,i need to use 
```
bounding = await locate.bounding_box() 
x = bounding['x'] 
y = bounding['y'] 
await page.evaluate(f'window.scrollBy({x}, {y})')
```
to locate the elements one by one and wait.becaunse the element is invisible at the beginning.At the first time,i use `time.sleep()`.However, this method is not flexible, because the waiting time is fixed, but fluctuations in Internet speed in actual use will have a great impact and this method will not meet expectations.

The question came`is_visable()` in the doc,I have used this method but it doesn't work as expected.From the perspective of the entire page, this method detects elements of the entire page,so it doesn't wait the rest elements.

Is there a way to make` is_visble()` detect a region that i set instead of the whole page.
I would appreciate it if you could provide a workaround

**Comment by dgozman** [comment]
@Edmounds  I am not sure I fully understood the issue. Are you looking for something like #8740?

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
