### ISSUE TITLE
[Feature] allow passing evaluate timeout in evaluate function

### ISSUE THREAD

**Issue by oceanwap** [microsoft/playwright#20608]
I am using jest with playwright and although there is a plugin jest-playwright, which runs browser instance even for unit tests in jest, Hence I am not using it.

Evaluate function throws timeout when there is some stress test running in browser instance, In my opinion we should make it an argument of evaluate function, which can be passed in individual test cases.

**Comment by dgozman** [comment]
@oceanwap From what I know, `page.evaluate()` never throws a timeout error. Perhaps I misunderstood the issue? Could you please provide a repro that demonstrates the problem, so that we can run it locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
