### ISSUE TITLE
[BUG] Fixture times out underlying worker

### ISSUE THREAD

**Issue by jabins3** [microsoft/playwright#20604]
**Context:**
- Playwright Version: [1.29.2]
- Operating System: [Windows]
- Node.js version: [16.19.0]
- Browser: [Chromium]
- Extra: [Test run with multiple workers]

**Describe the bug**
We have a test fixture that does a couple of things before each test in a suite is run and sometimes the fixture times out due to external factors. We also have test retries enabled so that we take care of such transient issues.

In some scenarios, we see that when the fixture times out the underlying worker errors out. This in turn fails the whole test run even though the failed test was retried successfully. Ideally, if there are no test errors then the run should be successful. The run errors out with the message `1 error was not a part of any test, see above for details`.

Add any other details about the problem here.
![image](https://user-images.githubusercontent.com/124320224/216483812-77caa308-a479-4fa3-9faa-addde8a18a0b.png)
![image](https://user-images.githubusercontent.com/124320224/216483941-0ccbb532-1300-41f3-8c31-d4f8f508d65f.png)

**Comment by dgozman** [comment]
@jabins3 Sounds like an issue indeed. If you could share a repro, or at least the problematic fixture, that would be great!

**Comment by mxschmitt** [comment]
Closing as part of the triage process, if you still encounter issues, feel free to file a new issue, thanks!
