### ISSUE TITLE
[BUG] Content inside <details> is not hidden

### ISSUE THREAD

**Issue by lasseklovstad** [microsoft/playwright#20610]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 18.21.1
- Browser: Chromium

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  
await page.setContent(`
  <div>
    <label>
      Name
      <input/>
    </label>
    
    <details>
      <summary>Open form</summary>
      <label>
         Name
         <input  />
      </label>
    </details>
    
  </div>
  `);

  await page.getByRole("textbox", { name: "Name" }).fill("Test");
})();
```

**Describe the bug**
I would excpect the input field inside the details tag would be hidden. 

**I get this error:**
waiting for getByRole('textbox', { name: 'Name' })
Error: strict mode violation: getByRole('textbox', { name: 'Name' }) resolved to 2 elements:
    1) <input/> aka getByLabel('Name').first()
    2) <input/> aka getByRole('group').getByLabel('Name')
    
One thing to notice is that this doesn't fail:
await expect(page.getByRole("textbox", { name: "Name" }).nth(1)).toBehidden();

**Comment by dgozman** [comment]
@lasseklovstad Well, the error message tells you that there are two textboxes on the page, so you must pick one. When to do `nth(1)`, you narrow down to the second `<input>`, and it is hidden indeed. Therefore, it seems to work as expected.

Let me know if that helped.

**Comment by lasseklovstad** [comment]
@dgozman I thought that getByRole only match non-hidden elements as described here: https://playwright.dev/docs/api/class-page#page-get-by-role-option-include-hidden ?

**Comment by dgozman** [comment]
@lasseklovstad Good point! Perhaps `<details>` content is not considered hidden in ARIA spec? I'll double check, thanks for spotting.

**Comment by lasseklovstad** [comment]
I have a hard time understanding aria spec 😅 But using the chrome Accessibility Tree view the content is hidden.
