### ISSUE TITLE
[BUG] Selectors not working when i use browserless

### ISSUE THREAD

**Issue by taral14** [microsoft/playwright#20613]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: v16.13.0
- Browser: Chromium
- Extra: -
- 

**Code Snippet**

```javascript
const pw = require('@playwright/test');

(async () => {
  const browser = await pw.chromium.connect(
    'wss://chrome.browserless.io/playwright?token={MY-TOKEN}'
  );
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.example.com/');
  await pw.expect(page.locator('h1').getByText('Example Domain')).toBeVisible();

  await browser.close();
})();
```

**Describe the bug**

I'm trying to run tests on browserless. And selectors getByTestId, getByText etc not working. I get an error

```bash
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

expect.toBeVisible: Unknown engine "internal:text" while parsing selector h1 >> internal:text="Example Domain"i
=========================== logs ===========================
expect.toBeVisible with timeout 5000ms
============================================================
    at /Users/user/PhpstormProjects/finsight/e2e-test/index.ts:11:67 {
  name: 'Error'
}
```

**Comment by ltsuda** [comment]
As documented here, browserless uses Playwright Library, not Playwright Test.
https://www.browserless.io/docs/playwright

You are using the Playwrigh Test and using Web First Assertions which are not available in Browserless because they use the Library.

https://playwright.dev/docs/library#key-differences

**Comment by dgozman** [comment]
@taral14 I think the problem is version mismatch. Make sure your Playwright version matches from both sides. Let me know if that helped.

**Comment by taral14** [comment]
Thank you all. solved the problem. selectors work if connected via connectOverCDP
