### ISSUE TITLE
[BUG] custom headers injection is ignored for FireFox & latest playwright Version (1.30)

### ISSUE THREAD

**Issue by shalikaSpringerNature** [microsoft/playwright#20614]
**Context:**
- Playwright Version: [1.27.1 & 1.30.0 ]
- Operating System: [e.g. Mac]
- Node.js version:  [14.20.1]
- Browser: [e.g. All, Chromium, Firefox, Edge]

**Code Snippet**

    page.route('**/*', (route, request) => {

        const headers = {
            ...request.headers(),
            'X-Forwarded-For': '1.1.1.1' ( i.e any particular ip which is required as per use case )
        };
        route.continue({headers});
    });

**Describe the bug**

**1) Issue with Firefox custom headers  injection** 

Currently I am using  Playwright Version: [1.27.1] 
and it's able to inject custom headers (modify headers) using above Code Snippet into  browser chrome & safari 
but it did not work with browser firefox somehow 

Tried using below options also 
i)  **--disable-web-security** 
{
      use: {
        ...devices['Desktop Firefox'],
        launchOptions: {
          args: ['--disable-web-security'],
        }
      },
    }
ii)   page.setExtraHTTPHeaders({ "X-Forwarded-For": "3.3.3.3" }); [("3.3.3.3" is just an example  i.e any particular ip which is required as per use case )]

But nothing worked out 

**2) Issue with latest playwright Version 1.29.1 , 1.30.0**

When I used latest playwright Version , I was not able to inject custom headers ( modify/add headers) in my page request at all for any browser using above Code Snippet

Reason being that with  latest playwright Version , playwright seems to install latest chrome /firefox  browser version and in which custom header injection is not working, Though it worked with old playwright Version as mentioned in #1 for chrome/safari browser.

So for example here with playwright Version =1.30.0 , it tries to install Chromium 110.0.5481.38  , in which header injection fails 

Downloading Chromium 110.0.5481.38 (playwright build v1045) from https://playwright.azureedge.net/builds/chromium/1045/chromium-mac-arm64.zip
123.8 Mb [====================] 100% 0.0s
Chromium 110.0.5481.38 (playwright build v1045) downloaded to /Users/<username>/Library/Caches/ms-playwright/chromium-1045

**while when we use old playwright Version = 1.27.1 it use old Chromium version 107.0.5304.18 , in which header injection with above code snippet works** 

I have tried everything including clearing cache ,  re-installing browser  on Mac location - ~/Library/Caches/ms-playwright/
 also but nothing seems to work . 

Can someone please look into it ?

**Comment by dgozman** [comment]
@shalikaSpringerNature Could you please provide a repro that we can run locally? How do you check that custom headers are not injected? Our tests indicate that this functionality works, so more we need more information from your side.

**Comment by shalikaSpringerNature** [comment]
@dgozman Unfortunately I can't provide repro at this time since it's associated to my organisation.
Here are the detailed steps .may be this will help 

Question - How do you check that custom headers are not injected?

Answer - 
Because as mentioned in above steps with Playwright Version: [1.27.1] 
We check particular assertion in our code which work when request comes from specific ip address ,which works with below code ,Playwright Version: [1.27.1]  for chrome and safari but fail to work for firefox 

page.route('**/*', (route, request) => {

    const headers = {
        ...request.headers(),
        'X-Forwarded-For': '1.1.1.1' ( i.e any particular ip which is required as per use case )
    };
    route.continue({headers});
});

So if same piece of code is working for chrome and safari, why will it not work for browser firefox ? 
Also as mentioned in #2 above , same piece of code does not work with any-browser for playwright version - 1.29.1 , 1.30.0

Let me know if you need further information ?

**Comment by mxschmitt** [comment]
I tried the following which works on the main branch:

```ts
it('should work @smoke', async ({ page, server }) => {
  await page.setExtraHTTPHeaders({
    'X-Forwarded-For': '1.1.1.1',
  });
  const [request] = await Promise.all([
    server.waitForRequest('/empty.html'),
    page.goto(server.EMPTY_PAGE),
  ]);
  expect(request.headers['x-forwarded-for']).toBe('1.1.1.1');
});
```

and via route.continue:

```ts
it('should work', async ({ page, server }) => {
  await page.route('**/*', route => route.continue({ headers: { ...route.request().headers(), 'X-Forwarded-For': '1.1.1.1' } }));
  const [request] = await Promise.all([
    server.waitForRequest('/empty.html'),
    page.goto(server.EMPTY_PAGE),
  ]);
  expect(request.headers['x-forwarded-for']).toBe('1.1.1.1');
});
```

could you provide us a clear repro which was working and is not working anymore?

**Comment by aslushnikov** [comment]
Looks like the discussion has stalled here; closing this!

If you still think we can be helpful, please do not hesitate to **file a new issue**. Thanks!
