### ISSUE TITLE
Default profile setting is missing

### ISSUE THREAD

**Issue by gyurik** [microsoft/playwright#20619]
There is  no way to use a pre-arranged profile for the browser. There a cases where a continues logon takes an manual intervention where an automation doesn't make sense.

For the Selenium there is a way for using a pre set profile.. Until this won't be available for Playwright I cannot use it.

I'm using PW with Robot Framework. So the solution needed for the Browser extension for RF...

**Comment by dgozman** [comment]
@gyurik Take a look at [`launchPersistentContext()`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context). Let me know if that helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
