### ISSUE TITLE
[BUG] Firefox doesnt open 

### ISSUE THREAD

**Issue by SentoxAIO** [microsoft/playwright#2061]
**Context:**
- Playwright Version: ^0.15.0
- Operating System: Windows
- Node version: v12.16.1.
- Browser: Firefox

```
const playwright = require("playwright");
async function main() {
    const browser = await playwright.firefox.launch({headless:false});
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto("https://www.google.com");
}
main()
```

Using firefox doesnt work for me, it always opens a blank page and throws that error: 
UnhandledPromiseRejectionWarning: Error: NS_BINDING_ABORTED while navigating to https://www.google.com

When I try it with Chromium it works perfectly

**Comment by pavelfeldman** [comment]
Could you `set DEBUG=pw:browser*` and paste errors it reports?

**Comment by SentoxAIO** [comment]
How can I add that to my debugging configs? In launch.json?

**Comment by pavelfeldman** [comment]
Yes, that would be

`"env": {"DEBUG":"pw:browser*"},`

**Comment by SentoxAIO** [comment]
[https://ibb.co/Px67x7k](url)

Thats the error I get

**Comment by pavelfeldman** [comment]
It claims it can't read the profile directory that was created for it... Could you check that you can create folders under `AppData\Local\Temp`? (basically the `-profile` option that it passes)

**Comment by SentoxAIO** [comment]
I can create folders under `AppData\Local\Temp`.

**Comment by SentoxAIO** [comment]
![image](https://user-images.githubusercontent.com/57367608/80829473-7aabb100-8be7-11ea-9d8a-a7a02309c582.png)

As you can see, it creates a folder in the Temp folder.

**Comment by SentoxAIO** [comment]
As I said it just opens a blank page but I found out that when I open a new tab manually it works.

**Comment by SentoxAIO** [comment]
**If someone else gets the error,  set a Timeout before getting the page and it will work**

**Comment by SentoxAIO** [comment]
But since this isnt a very reliable fix, the bug is still existing

**Comment by aesyondu** [comment]
Have you tried deleting and re-downloading the firefox browser? I'm thinking it could be a corrupt browser download.

Also does the bug exist in other versions, 0.16, 0.17 perhaps?

**Comment by SentoxAIO** [comment]
I reinstalled it multiple times and it also happes in older versions.

**Comment by dominuslabs** [comment]
+ 1 ^ I experienced the bug as well. While the timeout fixed the issue, it isn't ideal.

**Comment by pavelfeldman** [comment]
@SentoxAIO: Which timeout fixes it? After launch before creating the context?

**Comment by SentoxAIO** [comment]
I worked for me with a delay of 300-400ms

**Comment by SentoxAIO** [comment]
Seems like its fixed. Thanks for your work!

**Comment by thenengah** [comment]
```node.js
  await page.waitForTimeout(500);
  await page.goto("https://example.com/")
```
^ The timeout approach also worked for me. I only found this in Firefox but could be in other browsers. 

I think what's happening is that `page.goto` doesn't care about the current state, but something in the current state like a pending req is aborted when goto is triggered.

**Comment by vogler** [comment]
Had the same problem with `goBack`, solved it with `waitForLoadState` instead of `waitForTimeout`:

```js
// ...
await page.waitForLoadState(); // needed
await page.goBack(); // without the wait above got Error: NS_BINDING_ABORTED; same for goto()
```
