### ISSUE TITLE
[Bug] page.reload() hangs when dialog.dismiss() beforeunload is called

### ISSUE THREAD

**Issue by Sunilcharlesedward** [microsoft/playwright#20624]
**Context:**
- Playwright Version: [1.29]
- Operating System: [e.g. Windows]
- Browser: [Chromium]
- Extra: [Visual Studio 2022, C# dotnet]

In my testCase i have to refresh a page and verify unsaved changes, both ways. i.e await dialog.AcceptAsync() ( this reloads the page and i can verify that changes are lost). However,  when i use 'await dialog.DismissAsync();' it dismisses the unsaved changes dialog but comes up with this error 

waiting for navigation until "load"
============================================================
  Stack Trace: 
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary2 dictionary) line 165
Connection.WrapApiCallAsync[T](Func1 action, Boolean isInternal)
Page.ReloadAsync(PageReloadOptions options) line 684

**Code Snippet**

public async Task BrowserRefresh()
        {
           HandlePageDialog();            
           await _page.ReloadAsync();        
        }

        public void HandlePageDialog()
        {
            _page.Dialog += async (_, dialog) =>
            {
                Assert.AreEqual("beforeunload", dialog.Type);
                **await dialog.DismissAsync();**
                //await dialog.AcceptAsync();                            
            **};**
        }
![image](https://user-images.githubusercontent.com/48145837/216708244-201d015d-1f41-480b-9219-52b3ebf4fda3.png)

**Comment by dgozman** [comment]
@Sunilcharlesedward Try calling `page.CloseAsync(new () { RunBeforeUnload = true })` instead of reload. This method will trigger the before unload dialog, and only close the page if you accept the dialog. Let me know if that helps.

**Comment by Sunilcharlesedward** [comment]
> @Sunilcharlesedward Try calling [`page.CloseAsync(new () { RunBeforeUnload = true })`](https://playwright.dev/dotnet/docs/api/class-page#page-close-option-run-before-unload) instead of reload. This method will trigger the before unload dialog, and only close the page if you accept the dialog. Let me know if that helps.

#dgozman I have tired this and that too results in exctly the same error with same stacktrace. Moreover, my framework has Page.CloseAsync() as part of the [Teardown] i.e after every test, close the page. And in my testCase i am trying to verify whether  refreshing the browser and chk unsaved functionality. Also, i have tried Control+R and F5 keys to refresh, but still no go, it even didint refresh the page i.e no dialog pops out so it wont even enter the handler.

**Comment by mxschmitt** [comment]
We have tests in place related to that, e.g. [this](https://github.com/microsoft/playwright-dotnet/blob/f4be7830828257670f28d1ce1fd4e646db41320a/src/Playwright.Tests/BeforeUnloadTests.cs#L41-L56) one. Could you help us creating a minimal reproducible so we run into your exception?

**Comment by Sunilcharlesedward** [comment]
Yes, here are the steps to reproduce:

1. NavigateTo this URL ("https://codepen.io/chriscoyier/pen/GRRJobP")
2. Put a debug point, so that we can edit some stuff in one of the boxes.
3. Enter some stuff e.g 
![image](https://user-images.githubusercontent.com/48145837/218609831-cf5c0260-0825-40f7-ae40-2c15d747e7d5.png)
 4. do a page. reload using the functions below. 
 
 public async Task BrowserReload()
        {
            HandlePageDialog();
            await _page.ReloadAsync();
        }
public void HandlePageDialog()
        {
            _page.Dialog += async (_, dialog) =>
            {
                alertMessage.Add(dialog.Type);
                Assert.AreEqual("beforeunload", dialog.Type);
                await dialog.DismissAsync();
                //await dialog.AcceptAsync();
            };
        }

**Comment by mxschmitt** [comment]
Can we have a reproducible which does not involve Visual Studio? It looks expected that if ReloadAsync has started and then you have a breakpoint, that it will throw a timeout error if you break more than 30 seconds.

**Comment by Sunilcharlesedward** [comment]
I use visual studio only. However, will try to reproduce in vs code . 
I have to put breakpoint immediately after i have navigated to url so as to type in something hence i have unsaved changes. Then after that i call page.reload. so breakpoint is after that

**Comment by mxschmitt** [comment]
What about using Page.PauseAsync() instead? This is the recommended way of setting a breakpoint, halting the whole program is not the best, since then no Playwright communication can happen.

**Comment by Sunilcharlesedward** [comment]
Potentially, we can try using Page.PauseAsync().However, whatever we use
Pause or a breakpoint it's only a mechanism to edit some stuff resulting in
unsaved changes alert.
I don't understand how it is going to resolve the issue.

**Comment by mxschmitt** [comment]
I tried the following and it was working for me, could you help me creating a repro which ends up in your error?

```csharp
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
var page = await browser.NewPageAsync();
await page.GotoAsync("https://codepen.io/chriscoyier/pen/GRRJobP");
Console.Write("Hello ");
// set breakpoint here.
Console.Write("World!\n");
await page.ReloadAsync();
await page.ScreenshotAsync(new()
{
    Path = "screenshot.png"
});
```

**Comment by Sunilcharlesedward** [comment]
Try these steps: 

           using Microsoft.Playwright;
            using var playwright = await Playwright.CreateAsync();
            await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
            var page = await browser.NewPageAsync();
            await page.GotoAsync("https://codepen.io/chriscoyier/pen/GRRJobP");
            
            page.Dialog += async (_, dialog) =>
            {
               // alertMessage.Add(dialog.Type);
                Assert.AreEqual("beforeunload", dialog.Type);
                await dialog.DismissAsync();
                //await dialog.AcceptAsync();
            };
            // set breakpoint here @page.ReloadAsync() step and type the word Hello as shown in screenshot            
            await page.ReloadAsync();`

![image](https://user-images.githubusercontent.com/48145837/223365075-66cb9375-bfa0-4078-8042-49d5d84368e2.png)

**Comment by mxschmitt** [comment]
I was able to create a minimal reproducible out of it:

```csharp
using Microsoft.Playwright;
using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync(new() { Headless = false });
var page = await browser.NewPageAsync();
await page.GotoAsync("https://example.com");

// set the page content with a beforeunload dialog
await page.EvaluateAsync(@"
    window.addEventListener('beforeunload', (e) => {
        e.returnValue = 'Are you sure you want to leave?';
    });
");

page.Dialog += async (_, dialog) =>
{
    Console.WriteLine(dialog.Type);
    await dialog.DismissAsync();
    Console.WriteLine("Dialog dismissed");
};
Console.WriteLine("Reloading page");
await page.ReloadAsync();

```

**Comment by Sunilcharlesedward** [comment]
But the TestScenario here is to categorically validate that unsaved changes are not lost on page after successfully calling dialog.dismiss. Hence, its is blocked.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by samdenty** [comment]
@pavelfeldman is there a reason why this was closed? https://github.com/microsoft/playwright/issues/20624#issuecomment-1458143769 is a totally valid reproduction of the bug
