### ISSUE TITLE
[Feature] More granular support of what Playwright trace file can gather

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#20626]
Currently seeing a problem with gathering a Playwright trace file for our tests.

We start our Playwright tracer with :
```
    await this.playwrightWindow?.tracing.start({
      screenshots: true,
      snapshots: true,
      sources: false,
    });
````
and then ~4 minutes ( on average ) later we stop it 
```
            await tracingContext.stop({
              path: traceDirectory,
            }),
````

We are seeing that a lot of our tests are timing out from this, so we had to add a top level 45s timeout.

```
2023-02-01T19:19:34.1641975Z      🛑 Stopping Playwright UI Driver
2023-02-01T19:20:19.0624297Z      📩❌ Timed out trying to stop Playwright trace. (took longer than 45000ms)
2023-02-01T19:20:19.2285355Z      🛑 Stopped Playwright UI Driver
```

From my investigation, it looks like our product is VERY verbose in its console messages.

![image](https://user-images.githubusercontent.com/37447884/216734044-c4adce85-2d48-4c5c-b304-abb7e26028e7.png)

Anyway we can batch these? or report only the important console message events like Error?

It also looks like "JSHandle" is extremely verbose here : 

![image](https://user-images.githubusercontent.com/37447884/216734166-7c813dda-62a2-485e-83fe-7ecbaab79b7d.png)

**Comment by dgozman** [comment]
@mastrzyz Are you using `JSHandle`s? We [recommend locators](https://playwright.dev/dotnet/docs/handles#locator-vs-elementhandle) instead.

Anyway, this is a valid feature request, leaving it for prioritization.

**Comment by mastrzyz** [comment]
@dgozman we very sparingly use JSHandles, that I know of.

the JSHandle looks to be from a console message? it looks like, 
![image](https://user-images.githubusercontent.com/37447884/216735425-1d3bec1d-823d-4c44-913b-52a9018cd083.png)

**Comment by mastrzyz** [comment]
![image](https://user-images.githubusercontent.com/37447884/216735938-4e8c7822-8bfe-4223-9924-5ce16a2e352f.png)

**Comment by dgozman** [comment]
@mastrzyz Could you share the trace file with us?

**Comment by dgozman** [comment]
Investigation notes: out of 16000 trace events, there are: 5000 `Page.console` events, 5000 `ConsoleMessage.__create__` events and 5000 `JSHandle.__create__` events, because each console message had a handle in it.

**Comment by dgozman** [comment]
Ideally, we would compress the trace format and make it save faster, probably by batching events.

**Comment by mastrzyz** [comment]
@dgozman Will this be funded work? ~50% of our tests are timing out from spending more than 60s on Playwright trace stopping.

Is there a workaround I can use?

**Comment by mastrzyz** [comment]
The current problem we have is that stopping the playwright trace takes longer than 1 minute for some tests, I've seen it go upwards to 10 minutes.


We put a timeout on the stopTrace() method but doing that leads to unexpected results in the test ->


```
Error: ENOENT: no such file or directory, open 'D:\a\_work\1\a\test-results\.playwright-artifacts-0\traces\0f2e7512f19fc3d533830f0bceeaea45.trace'

Failed worker ran 10 tests:

```

**Comment by mastrzyz** [comment]
Any idea how we can mitigate this?
