### ISSUE TITLE
[BUG] Playwright v1.30.0 doesn't provide keyboard focus to modal/video embeds in webkit

### ISSUE THREAD

**Issue by amauch-adobe** [microsoft/playwright#20629]
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [M1 MacOS Ventura 13.2 ]
- Node.js version: [18.11.0]
- Browser: [WebKit]

Executed this command: PWDEBUG=console npx playwright test -g @modal --project=webkit

"@modal" is our test tag annotation

```javascript
      await page.goto('https://business.adobe.com/customer-success-stories/coca-cola-case-study');
      const marqueeBtn = page.locator('//*[contains(@class, "marquee")]//a[contains(@href, "#")]');
      const closeBtn = page.locator('.dialog-close');

      // Closing by pressing the Esc key
      await selectModalBtn(marqueeBtn, page);

      await page.waitForSelector('.dialog-modal');
      await page.keyboard.press('Escape');
      let count = 0;
      while (page.url().includes('#') && count < 10) {
        // eslint-disable-next-line no-await-in-loop
        await page.keyboard.press('Tab');
        // eslint-disable-next-line no-await-in-loop
        await page.keyboard.press('Escape');
        count += 1;
      }

      await checkModalClosed(page);
```

Bug Description:

We were originally on v1.29.1, updated to 1.30.0 this week and now our test that validates closing a modal video using keyboard strokes (TAB, ESC) no longer works for WebKit.  The same test cases work just fine for Chromium and Firefox.  The test iterates tabbing and the pressing escape on the keyboard until the modal closes since the embedded video in the modal has other items focused on first before the close button.  In WebKit the modal window remains open and never closes.  If I manually test this concept against my own Mac's Safari Browser (updated to the latest for Ventura Version 16.3 (18614.4.6.1.5)) it closes just fine.

**Comment by mxschmitt** [comment]
I tried to reproduce it, but for me when running it locally it seems like Akamai, the CDN your site is using is blocking some all the future resources which breaks the site.

<img width="661" alt="image" src="https://user-images.githubusercontent.com/17984549/217099959-06ccea62-83e9-4c3f-9f28-1abc3095af22.png">

Did you also experience this?

**Comment by amauch-adobe** [comment]
@mxschmitt, I don't receive that issue.  It is odd that you are being pushed out by our Akamai CDN since it is a public-facing production URL.  We might have some rules in place that are blocking certain things.  That being the case were you able to navigate to this URL?  https://business.adobe.com/customer-success-stories/coca-cola-case-study 

The lana.js is just a script for logging into our logging service.  Are you looking at the lana.js file because there was a console error with it?  The test issues with the modal, as far as I can tell don't have any connection to the lana.js file.  

Oddly enough when I run this same test using GitHub Actions free tier VMs there isn't the failure I'm seeing when I run it locally from my IDE or command line.  I'm going to see if there is a race condition of something loading that is causing the test to fail when running locally vs. within our CI/CD pipeline.

**Comment by mxschmitt** [comment]
Yes I'm able to navigate to the URL by definition, but after loading half of the resources it Akamai blocks me. I tried with `npx playwright cr` which will open Chromium, but the same ends up happening with WebKit.

Pretty sure its not related to lana.js, this is just an example after which the blockage starts happening.

I can try using a VPN to be in a different location if its location based geoblocking but this requires some more time for me to setup - so if you want to create a minimal reproducible out of your testing site, we'd appreciate it!

**Comment by amauch-adobe** [comment]
@mxschmitt I'm going to close this bug as I'm going to dig further into the issue since it works in our CI.  There might be something set up on my end that is causing the issue.
