### ISSUE TITLE
Is there an option to open pdf externally in playwright?

### ISSUE THREAD

**Issue by HK834** [microsoft/playwright#20633]
Playwright version: 1.30.0
Visual Studio 2019, C# dotnet
Browser: [Chromium]
Operating System: Windows

Hi, we want to download a PDF file. We don't have a click option to download. So in selenium, we used to set the chrome options to "plugins.always_open_pdf_externally". Similarly, can we have some options for the playwright as well?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/7822. If you run it headless it should already result in a download event.
