### ISSUE TITLE
[BUG] The installation documentation is confusing regarding the actual output

### ISSUE THREAD

**Issue by mlaopane** [microsoft/playwright#20631]
**Context:**
- Playwright Version: **1.30.0**
- Operating System: **MacOS Ventura 13.2**
- Node.js version: **18.12.1**
- Browser: **N/A**
- Extra: **N/A**

**Code Snippet**

```sh
pnpm dlx create-playwright my-project
```

**Describe the bug**

When running the command above and entering `tests-e2e` as the tests directory when prompted, here is directories/files output

```md
|-- tests-e2e
    |-- node_modules
    |-- tests-examples
        |-- demo-todo-app.spec.ts
    |-- .gitignore
    |-- example.spec.ts
    |-- package.json
    |-- playwright.config.ts
    |-- pnpm-lock.yaml
|-- my-project
```

Also the prompts says

```sh
Initializing project in 'my-project'
```

Which is not the case since this directory created but left empty.

Also I expected `tests-e2e` to be the directory for all my tests files instead of being the project itself.

**Expected behavior**

Do not use the extra command parameter.  
Or use it to install everything in this directory and update the [installation documentation](https://playwright.dev/docs/intro#installing-playwright)

The CLI should not ask :  

> Where to put your end-to-end tests?

But maybe something like :  

> Where to put your playwright project?

PS : I hope it was clear enough, don't hesitate to comment if this is not the case

**Comment by mxschmitt** [comment]
For me it was working as expected when running your command above: `pnpm dlx create-playwright my-project`

```
└───my-project
    │   .gitignore
    │   package.json
    │   playwright.config.ts
    │   pnpm-lock.yaml
    │
    ├───tests
    │       example.spec.ts
    │
    └───tests-examples
            demo-todo-app.spec.ts
```

I tried it with keeping all the defaults and one time entering `tests-e2e` like you did with `Where to put your end-to-end tests?`. But in both cases it generated it correctly. Did I miss something?

**Comment by mxschmitt** [comment]
Closing as per above, if you still experience issues with Playwright, feel free to file another issue, thanks!
