### ISSUE TITLE
[BUG] sessionStorage returns empty object all the time

### ISSUE THREAD

**Issue by lbevo** [microsoft/playwright#20632]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Node.js version: 16.15.1
- Browser: Chromium
- Extra: [Official documentation](https://playwright.dev/docs/auth#session-storage)

**Code Snippet**

The application that I will to test uses session storage to store the auth token and cookies to store the refresh token. For now I am fighting with playwright to get the value of the session storage to set it back on every other tests. I can easily have it in the browser console by entering `window.sessionStorage`

![image](https://user-images.githubusercontent.com/104770958/216776816-f3e307a7-ab31-4462-8048-6505b62a1f28.png)

What I try to do for now is to somehow use what is written [HERE](https://playwright.dev/docs/auth#session-storage)

but
```javascript
const sessionStorage = await page.evaluate(() => JSON.stringify(sessionStorage));
```
is always an empty object

What I did
```javascript
    const browser = await chromium.launch();
    const page = await browser.newPage();
    const loginPage = new LoginPage(page);
    await loginPage.goto();
    await loginPage.fillLoginForm(user);
    await loginPage.sendLogin();
    await loginPage.saveSession();
    await browser.close();
```
and the LoginPageObject
```javascript
export abstract class CommonPage {
  protected page: Page;
  private url: string = 'http://localhost:4040/#/';

  protected constructor(page: Page) {
    this.page = page;
  }

  protected async goto(url: string): Promise<void> {
    await this.page.goto(`${this.url}${url}`);
  }

  protected dt(dataTestName: string): () => Locator {
    return () => this.page.locator(`data-test=${dataTestName}`);
  }
}

export class LoginPage extends CommonPage {

  constructor(page: Page) {
    super(page);
  }

  async goto(): Promise<void> {
    await super.goto('');
  }

  private usernameInput = this.dt('username');
  private passwordInput = this.dt('password');
  private loginButton = this.dt('login');

  fillLoginForm = async (info: ILogin): Promise<void> => {
    await this.usernameInput().fill(info.login);
    await this.passwordInput().fill(info.password);
  };

  sendLogin = async (): Promise<void> => {
    await this.loginButton().click();
  };

  saveSession = async (): Promise<void> => {
    const sessionStorage = await this.page.evaluate(() => JSON.stringify(sessionStorage));
    process.env.SESSION_STORAGE = sessionStorage;
  };
}
```

**Describe the bug**

As I read in the doc I should be able to get the sessionStorage object from the current context but it's not working

**Comment by lbevo** [comment]
Fixed it using a **deprecated** function: `waitForNavigation`

sendLogin Function updated:
```
sendLogin = async (): Promise<void> => {
  await this.loginButton().click();
  await this.page.waitForNavigation();
};
```

**Comment by mxschmitt** [comment]
timing can be different based on when and where the test gets executed. if you look for an alternative to waitForNavigation, you can use waitForURL.

Looks like this issue is solved?

**Comment by lbevo** [comment]
Yes. It is. I will try with `waitForURL`. Thanks for the tip

**Comment by mxschmitt** [comment]
Closing then as per above, please re-file if you still have issues with Playwright, thanks.
