### ISSUE TITLE
evaluate javascript function

### ISSUE THREAD

**Issue by gpsdev** [microsoft/playwright#20640]
im trying to use EvaluateAsync to run the following (which works in the chrome / msedge browser console)

`document.documentElement.requestFullscreen()`

i started with the example code, which works in my very basic project

`var href = await page.EvaluateAsync<string>("document.location.href");`
`Console.WriteLine(href);
`
i cannot get the following to work, i have tried many variations 

`await page.EvaluateAsync("document.documentElement.requestFullscreen()");`

any tips? i am aware of https://github.com/microsoft/playwright/issues/1086 feature request to launch browser in fullscreen i was just curious if there could be a workaround like this

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/19720.
