### ISSUE TITLE
[BUG] Page.setForcedColors was not found error when running webkit test on MacOS Catalina

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#20649]
**Context:**
- Playwright Version: >= 1.25.0
- Operating System: MacOS Catalina
- Node.js version: v16.14.2
- Browser: Webkit

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://example.com/')
  
  await page.locator(…);
})();
```

**Describe the bug**

Running a test on MacOS Catalina with Webkit browser gives the error:
```
browser.newPage: Protocol error (Page.setForcedColors): 'Page.setForcedColors' was not found [{"code":-32601,"message":"'Page.setForcedColors' was not found"}]
```
This error occurs for Playwright version >= 1.25.0.

For version 1.30.0, getting the error:
```
browser.newPage: Protocol error (Page.overrideUserPreference): 'Page.overrideUserPreference' was not found [{"code":-32601,"message":"'Page.overrideUserPreference' was not found"}]
```

**Comment by mxschmitt** [comment]
This is expected, since Playwright requires macOS 11+ see here: https://playwright.dev/docs/troubleshooting#system-requirements it was working before because we had a best-effort implemented.
