### ISSUE TITLE
Download.delete() not deleting the file saved into specific path using download.saveAs()

### ISSUE THREAD

**Issue by vnellutla2276** [microsoft/playwright#20650]
Hi,

I have saved the downloaded file into a specific file path using download.saveAs(path).
Later when I'm done with validation of downloaded file and trying to use download.delete() to delete the above downloaded file, its not actually deleting the file downloaded above.
Is it because I used saveAs method or should I handle it differently?

Please find the below code Snippet I used : 

![image](https://user-images.githubusercontent.com/52231060/216907444-2ab4861d-7753-4f63-b3fe-3fd1f471fb0f.png)

**Comment by mxschmitt** [comment]
When you use saveAs, it will does not take download.delete() into consideration which is expected. download.delete() will delete the actual file where it was originally stored at (which you can get via download.path()).

So in your case I'd just do download.path() to validate your file and then it should be automatically get deleted on test end.

**Comment by mxschmitt** [comment]
Closing as per above, since its answered.

**Comment by kaku0225** [comment]
I referred to the following URL https://playwright.dev/docs/api/class-download and implemented the following code. 

```
  const downloadPromise = page.waitForEvent('download');
  await page.getByText('test_file').click();
  const download = await downloadPromise;

  await download.saveAs('src/static/' + download.suggestedFilename());

  expect(await download.path('src/static/test_file_folder.zip')).toBeTruthy();
```

Although it mentions `All the downloaded files belonging to the browser context are deleted when the browser context is closed.` 

When I run npx playwright test, the images are still present locally and are not automatically deleted. Additionally, using download.delete() does not work. Could you please tell me what might be wrong with the code?

**Comment by lijachandran** [comment]
> When you use saveAs, it will does not take download.delete() into consideration which is expected. download.delete() will delete the actual file where it was originally stored at (which you can get via download.path()).
> 
> So in your case I'd just do download.path() to validate your file and then it should be automatically get deleted on test end.

The downloaded file using download.saveAs is NOT getting deleted automatically when the test execution ends.
Is there a way to delete the file?
