### ISSUE TITLE
[Feature] Publish Debian 11 Docker image

### ISSUE THREAD

**Issue by cclauss** [microsoft/playwright#20657]
We are trying to figure out which image tag we should be using for Playwright on Debian bullseye on CircleCI.

We were excited to see the Debian 11 support announcement but it is a bit light on details.
* https://playwright.dev/docs/release-notes#-debian-11-bullseye-support
* https://playwright.dev/docs/docker#image-tags only talks about Ubuntu and Alpine images, but not Debian.
* https://mcr.microsoft.com/en-us/product/playwright/tags searches for Debian and bullseye return no hits.

As discussed at https://github.com/microsoft/playwright/discussions/12913#discussioncomment-4880747 there is currently support for Debian but there is no published Docker image.  [Numerous issues have been opened about Debian](https://github.com/microsoft/playwright/issues?q=is%3Aissue+Debian) so an official image would be broadly useful.

___Please 👍 if you agree.___

**Comment by mxschmitt** [comment]
As of today we recommend using the official Node.js Docker image and installing the browsers using `npx playwright install --with-deps` after you installed your regular NPM dependencies.

**Comment by th0th** [comment]
It is not working for me with the official Node.js Docker image.

This is my Dockerfile:
```Dockerfile
FROM node:19.6

WORKDIR /poeticmetric

# copy only package definition files
COPY package.json .
COPY package-lock.json .

# install dependencies
RUN npm install

RUN npm exec -- playwright install --with-deps

# ...rest of the dockerfile
```

And this is the log for the failed build:
```
[+] Building 6.4s (10/30)
 => [internal] load build definition from development.Dockerfile                                                                                                                                                                                0.1s
 => => transferring dockerfile: 865B                                                                                                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                               0.1s
 => => transferring context: 2B                                                                                                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:19.6                                                                                                                                                                                    2.2s
 => [ 1/26] FROM docker.io/library/node:19.6@sha256:f62cd4433edc4b397218d9bc005a2f2865d7827753fd480a166e247127384900                                                                                                                            0.0s
 => => resolve docker.io/library/node:19.6@sha256:f62cd4433edc4b397218d9bc005a2f2865d7827753fd480a166e247127384900                                                                                                                              0.0s
 => [internal] load build context                                                                                                                                                                                                               0.0s
 => => transferring context: 46.06kB                                                                                                                                                                                                            0.0s
 => CACHED [ 2/26] WORKDIR /poeticmetric                                                                                                                                                                                                        0.0s
 => CACHED [ 3/26] COPY package.json .                                                                                                                                                                                                          0.0s
 => CACHED [ 4/26] COPY package-lock.json .                                                                                                                                                                                                     0.0s
 => CACHED [ 5/26] RUN npm install                                                                                                                                                                                                              0.0s
 => ERROR [ 6/26] RUN npm exec -- playwright install --with-deps                                                                                                                                                                                4.0s
------
 > [ 6/26] RUN npm exec -- playwright install --with-deps:
#0 0.628 BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
#0 0.628 Installing dependencies...
#0 0.891 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
#0 1.038 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#0 1.105 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#0 1.169 Get:4 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
#0 2.570 Get:5 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [218 kB]
#0 2.609 Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#0 3.224 Fetched 8510 kB in 3s (3312 kB/s)
#0 3.224 Reading package lists...
#0 3.540 Reading package lists...
#0 3.806 Building dependency tree...
#0 3.887 Reading state information...
#0 3.901 Package ttf-ubuntu-font-family is not available, but is referred to by another package.
#0 3.901 This may mean that the package is missing, has been obsoleted, or
#0 3.901 is only available from another source
#0 3.901
#0 3.901 Package libjpeg-turbo8 is not available, but is referred to by another package.
#0 3.901 This may mean that the package is missing, has been obsoleted, or
#0 3.901 is only available from another source
#0 3.901
#0 3.946 E: Package 'ttf-ubuntu-font-family' has no installation candidate
#0 3.946 E: Unable to locate package libenchant1c2a
#0 3.946 E: Unable to locate package libicu66
#0 3.946 E: Package 'libjpeg-turbo8' has no installation candidate
#0 3.947 Failed to install browsers
#0 3.947 Error: Installation process exited with code: 100
------
failed to solve: process "/bin/sh -c npm exec -- playwright install --with-deps" did not complete successfully: exit code: 1
```

**Comment by mxschmitt** [comment]
> It is not working for me with the official Node.js Docker image.
> 
> 
> 
> This is my Dockerfile:
> 
> ```Dockerfile
> 
> FROM node:19.6
> 
> 
> 
> WORKDIR /poeticmetric
> 
> 
> 
> # copy only package definition files
> 
> COPY package.json .
> 
> COPY package-lock.json .
> 
> 
> 
> # install dependencies
> 
> RUN npm install
> 
> 
> 
> RUN npm exec -- playwright install --with-deps
> 
> 
> 
> # ...rest of the dockerfile
> 
> ```
> 
> 
> 
> And this is the log for the failed build:
> 
> ```
> 
> [+] Building 6.4s (10/30)
> 
>  => [internal] load build definition from development.Dockerfile                                                                                                                                                                                0.1s
> 
>  => => transferring dockerfile: 865B                                                                                                                                                                                                            0.0s
> 
>  => [internal] load .dockerignore                                                                                                                                                                                                               0.1s
> 
>  => => transferring context: 2B                                                                                                                                                                                                                 0.0s
> 
>  => [internal] load metadata for docker.io/library/node:19.6                                                                                                                                                                                    2.2s
> 
>  => [ 1/26] FROM docker.io/library/node:19.6@sha256:f62cd4433edc4b397218d9bc005a2f2865d7827753fd480a166e247127384900                                                                                                                            0.0s
> 
>  => => resolve docker.io/library/node:19.6@sha256:f62cd4433edc4b397218d9bc005a2f2865d7827753fd480a166e247127384900                                                                                                                              0.0s
> 
>  => [internal] load build context                                                                                                                                                                                                               0.0s
> 
>  => => transferring context: 46.06kB                                                                                                                                                                                                            0.0s
> 
>  => CACHED [ 2/26] WORKDIR /poeticmetric                                                                                                                                                                                                        0.0s
> 
>  => CACHED [ 3/26] COPY package.json .                                                                                                                                                                                                          0.0s
> 
>  => CACHED [ 4/26] COPY package-lock.json .                                                                                                                                                                                                     0.0s
> 
>  => CACHED [ 5/26] RUN npm install                                                                                                                                                                                                              0.0s
> 
>  => ERROR [ 6/26] RUN npm exec -- playwright install --with-deps                                                                                                                                                                                4.0s
> 
> ------
> 
>  > [ 6/26] RUN npm exec -- playwright install --with-deps:
> 
> #0 0.628 BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
> 
> #0 0.628 Installing dependencies...
> 
> #0 0.891 Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
> 
> #0 1.038 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
> 
> #0 1.105 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
> 
> #0 1.169 Get:4 http://deb.debian.org/debian bullseye/main arm64 Packages [8072 kB]
> 
> #0 2.570 Get:5 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [218 kB]
> 
> #0 2.609 Get:6 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
> 
> #0 3.224 Fetched 8510 kB in 3s (3312 kB/s)
> 
> #0 3.224 Reading package lists...
> 
> #0 3.540 Reading package lists...
> 
> #0 3.806 Building dependency tree...
> 
> #0 3.887 Reading state information...
> 
> #0 3.901 Package ttf-ubuntu-font-family is not available, but is referred to by another package.
> 
> #0 3.901 This may mean that the package is missing, has been obsoleted, or
> 
> #0 3.901 is only available from another source
> 
> #0 3.901
> 
> #0 3.901 Package libjpeg-turbo8 is not available, but is referred to by another package.
> 
> #0 3.901 This may mean that the package is missing, has been obsoleted, or
> 
> #0 3.901 is only available from another source
> 
> #0 3.901
> 
> #0 3.946 E: Package 'ttf-ubuntu-font-family' has no installation candidate
> 
> #0 3.946 E: Unable to locate package libenchant1c2a
> 
> #0 3.946 E: Unable to locate package libicu66
> 
> #0 3.946 E: Package 'libjpeg-turbo8' has no installation candidate
> 
> #0 3.947 Failed to install browsers
> 
> #0 3.947 Error: Installation process exited with code: 100
> 
> ------
> 
> failed to solve: process "/bin/sh -c npm exec -- playwright install --with-deps" did not complete successfully: exit code: 1
> 
> ```

Looks like you are using an outdated Playwright version. Which one are you using?

**Comment by mxschmitt** [comment]
Actually it's fixed by https://github.com/microsoft/playwright/issues/18319 which gets released in 1.31

**Comment by mxschmitt** [comment]
Yes, see here: https://playwright.dev/docs/canary-releases

**Comment by th0th** [comment]
Thanks 💐

**Comment by mxschmitt** [comment]
Sounds like then we can close this issue if you can do it yourself and even decide which Node.js version you want to use?

**Comment by Gbillington1** [comment]
> As of today we recommend using the official Node.js Docker image and installing the browsers using `npx playwright install --with-deps` after you installed your regular NPM dependencies.

What if we need a python environment? I'm using playwright in a python3.10-bookworm based container, which is debian 12, but playwright says the OS is not supported and downloads dependencies for ubuntu.

**Comment by mxschmitt** [comment]
@Gbillington1 should work as well! It should be supported, are you using latest Playwright? I recommend filing a new separate issue, since we usually don't monitor closed issues, thanks!
