### ISSUE TITLE
[BUG] VS Code - Recording a test issues

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#20661]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 16.18.1
- Browser: N/A
- Extra: N/A

**## System:
 - OS: macOS 12.6.2
 - Memory: 157.03 MB / 32.00 GB
## Binaries:
 - Node: 16.18.1 - ~/.nvm/versions/node/v16.18.1/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.18.1/bin/yarn
 - npm: 8.19.2 - ~/.nvm/versions/node/v16.18.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://integrations-test.dev.cp.collibra.dev/signin');
  await page.getByTestId('username').click();
  await page.getByTestId('username').fill('A');await page.getByTestId('username').fill('Ad');await page.getByTestId('username').fill('Adm');await page.getByTestId('username').fill('Admi');await page.getByTestId('username').fill('Admin');
  await page.getByTestId('username').press('Tab');
  await page.getByTestId('password').fill('a');await page.getByTestId('password').fill('ad');await page.getByTestId('password').fill('adm');await page.getByTestId('password').fill('admi');await page.getByTestId('password').fill('admin');
  await page.getByTestId('sign-in').click();await page.getByTestId('sign-in').click();
  await page.getByTestId('PersonalMenu|Trigger').click();
  await page.getByRole('link', { name: 'Profile: Admin Istrator' }).click();
});
```

**Describe the bug**

When recording a test using VS Code it is not handling filling in fields correctly as you can see in the generated code above.
Is this a known issue?
Thanks

**Comment by mxschmitt** [comment]
I tried to reproduce with normal CLI as well as via VSCode, could you provide exact steps which buttons you click? I might miss something.

**Comment by costa-collibra** [comment]
https://user-images.githubusercontent.com/118260471/217102480-4433e6a4-8619-4032-973c-f91e2648c05e.mov

Hi

Here is a screen recording of the exact steps

**Comment by mxschmitt** [comment]
I can reproduce! thanks.

**Comment by costa-collibra** [comment]
Brilliant, hope you find a solution :)
