### ISSUE TITLE
[Feature] Record real asset size data in HAR files

### ISSUE THREAD

**Issue by jhancock532** [microsoft/playwright#20666]
I'd like to see real performance values instead of placeholders in the HAR file generated by Playwright. This would be used for basic performance monitoring of site web pages, with a warning raised in CI if total JS assets / total page weight exceeds a certain threshold.

### Ideal behaviour

After opening a site with 

`npx playwright open --save-har=example.har https://example.com/`

and closing the browser window when the site has loaded, the following values are no longer `-1`.

- `log.entries[n].request.headersSize`
- `log.entries[n].request.bodySize`
- `log.entries[n].response.headersSize`
- `log.entries[n].response.bodySize`

### Rational 

I would like both headersSize and bodySize as these are summed by Google Chrome to create `_transferSize`, which is what you'd typically see as the transferred amount of data to load any given asset in DevTools.

I would like both request and response as this can be used for sustainability testing, which isn't just gauged on the data downloaded, but the total data sent over the network.

### Further discussion

Chrome DevTools HAR export provides `log.entries[n].response.content.compression` to give an indication of how much data has been saved by the browser compressing the data before transfer. If this information is trivial to access while adding the other values, it would be somewhat useful to know how much impact using GZIP has.

I haven't considered expanding the scope to include request timing information, as I don't think there is as great a user need for this. This could be added in a seperate issue.

**Do you think others might benefit from this as well?**

Yes, this is created off the back of an existing issue: https://github.com/microsoft/playwright/issues/6254

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
