### ISSUE TITLE
[Question]: Is there a way to set multiple files for a POST request?

### ISSUE THREAD

**Issue by jvstatinydev** [microsoft/playwright#20674]
### Your question

Hello. 

I am trying to archive sending multiple files with a same key value on post request.

It can be done with python-requests like this.
https://stackoverflow.com/a/20769921/10651708
`
files = [('file', open('report.xls', 'rb')), ('file', open('report2.xls', 'rb'))]
requests.post('http://httpbin.org/post', files=files)
 `
 In the code. the files argument takes a list of tuple so it can send files with a same key.

I am looking at [#api-request-context-post-option-multipart](https://playwright.dev/python/docs/api/class-apirequestcontext#api-request-context-post-option-multipart).
and it seems multipart argument takes only dict type.

Is there an equal way to do this?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/18247.
