### ISSUE TITLE
[BUG]Visual comparisons > toHaveScreenshot() > Failing on element height v width

### ISSUE THREAD

**Issue by NikolaTestAutomation** [microsoft/playwright#20677]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: v16.14.2
- Browser: All
- Extra: NA

I tried using toHaveScreenshot() on multiple elements. But keep getting error Expected an image 190px by 240px, received 187px by 237px. Of course different px values for different elements. 

Await seems to be ignored here. I am getting failed test immediately regardless what timeout I put. Also maxDiffPixels and maxDiffPixelRatio does not help here either.

Playwright here is correct for failing the test. Actual and expected image are different. But I have no idea what to put as wait before toHaveScreenshot() step in order for actual and expected to be captured at the same image size.

Test case:

```
test.describe('@Smoke-suite > Inventory', () => {
  test.describe('Verify product data', () => {
    test('for backpack', async ({ page, context }) => {
      //await context.tracing.start({ screenshots: true, snapshots: true });
      await page.goto('/inventory.html');
      //wanted to grab entire investory tile and not be restricted by products order
      const elementParent = page.locator(`${'#add-to-cart-sauce-labs-backpack'} >> xpath=..`)
      const parent = elementParent.locator('xpath=..');
      //now i can run validations by searching elements under defined parent
      await expect.soft(parent.locator('.inventory_item_name'), 'Backback product title is not correct').toHaveText('Sauce Labs Backpack');
      await expect.soft(parent.locator('.inventory_item_desc')).toHaveText('carry.allTheThings() with the sleek, streamlined Sly Pack that melds uncompromising style with unequaled laptop and tablet protection.');
      await expect.soft(parent.locator('.inventory_item_price')).toHaveText('$29.99');
      await expect.soft(parent.locator('.inventory_item_price')).not.toContainText("text");
      await expect(page.locator('[alt="Sauce Labs Backpack"]')).toBeVisible();
      await expect(page.locator('[alt="Sauce Labs Backpack"]')).toHaveScreenshot('inventoryBackpack.png');
      //await context.tracing.stop({ path: 'trace.zip' });
    })
```

HTML report:

```
Error: Screenshot comparison failed:

  Expected an image 190px by 240px, received 187px by 237px. 

Call log:
  - expect.toHaveScreenshot with timeout 5000ms
  -   verifying given screenshot expectation
  - waiting for locator('[alt="Sauce Labs Backpack"]')
  -   locator resolved to <img alt="Sauce Labs Backpack" class="inventory_item_…/>
  - taking element screenshot
  -   disabled all CSS animations
  -   waiting for element to be visible and stable
  -   element is visible and stable
  - Expected an image 190px by 240px, received 187px by 237px. 
  - waiting 100ms before taking screenshot
  - waiting for locator('[alt="Sauce Labs Backpack"]')
  -   locator resolved to <img alt="Sauce Labs Backpack" class="inventory_item_…/>
  - taking element screenshot
  -   disabled all CSS animations
  -   waiting for element to be visible and stable
  -   element is visible and stable
  - captured a stable screenshot
  - Expected an image 190px by 240px, received 187px by 237px. 

Expected: C:\Users\.....\Documents\play\test-results\inventory-example--Smoke-suite-Inventory-Verify-product-data-for-backpack-chromium\inventoryBackpack-expected.png
Received: C:\Users\.....c\Documents\play\test-results\inventory-example--Smoke-suite-Inventory-Verify-product-data-for-backpack-chromium\inventoryBackpack-actual.png

  16 |       await expect.soft(parent.locator('.inventory_item_price')).not.toContainText("text");
  17 |       await expect(page.locator('[alt="Sauce Labs Backpack"]')).toBeVisible();
> 18 |       await expect(page.locator('[alt="Sauce Labs Backpack"]')).toHaveScreenshot('inventoryBackpack.png');
     |                                                                 ^
  19 |       //await context.tracing.stop({ path: 'trace.zip' });
  20 |     })
  21 |

```

**Comment by mxschmitt** [comment]
We also don't know either what is different between these images, toHaveScreenshot itself waits and re-tries between the screenshots, maybe you just need to increase the waiting time, aka. the timeout.

Can you maybe attach the images? then it might show something obvious whats different.

**Comment by NikolaTestAutomation** [comment]
Hi, thanks for quick reply!

Let me copy info from bug description regarding timeout - "Await seems to be ignored here. I am getting failed test immediately regardless what timeout I put. Also maxDiffPixels and maxDiffPixelRatio does not help here either.". You can also see that by error trace that I left in the ticket. At beggining of the trace, it is stated that timeout is 5seconds (I tried 60sec as well). However later in the trace you will see that it took a screenshot after 100ms and failed the test.

Playwright here is correct for failing the test. Actual and expected image are different. But I have no idea what to put as wait before toHaveScreenshot() step in order for actual and expected to be captured at the same image size. I have attached both actual and expected images.

![actual](https://user-images.githubusercontent.com/124170171/217241459-e6df61eb-8d8c-4068-88a3-903fd9ca40b2.png)
![expected](https://user-images.githubusercontent.com/124170171/217241468-1b76f234-ef5d-42a4-a9f2-d7f188e18021.png)

**Comment by mxschmitt** [comment]
So you have tried this?

```ts
 await expect(page.locator('[alt="Sauce Labs Backpack"]')).toHaveScreenshot('inventoryBackpack.png', { timeout: 10_000 });
```

Maybe the site you are testing uses a different aspect-ration sometimes that's why its failing, having a repro would be important for us, otherwise we cannot act on it.

**Comment by NikolaTestAutomation** [comment]
I am no longer getting this issue even without timeout. It was probably something related to website under test.
Thanks for sending how using local timeout would look like. I will note it for future use.

Setting this one to closed.

**Comment by NikolaTestAutomation** [comment]
Setting this one to closed.
