### ISSUE TITLE
[BUG]: isVisible() is not working to check if the locator is present on the page or not

### ISSUE THREAD

**Issue by devmasonn** [microsoft/playwright#20685]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: v17.0.1
- Browser: WebKit
- Extra: NA

**Code Snippet**

```Typescript
async testPresentLocator(){
        const isVisible = await this.page.getByText(‘User name’).isVisible();
        console.log(“isVisible value= ", await isVisible);

        if(await isVisible){
            logger.info("Inside if check= ",await isVisible);
            await expect(this.page.getByText(‘User Name’)).toBeVisible();
        } else {
            logger.info("Inside else check= ",await isVisible);
            await expect(this.billingPageIframe.getByText(‘New User Name’)).toBeVisible();
        }
    }
```
**Bug Desciption**

I tried using isVisible() to check if the locator is present on the page or not and based on the present locator check I am verifying locator with expect statement. However, isVisible() check is coming false always and so it is always going into the else block. Please suggest a way to check if the element is present on the page or not.

**Comment by mxschmitt** [comment]
We recommend following the debugging guide to find out why its false: https://playwright.dev/docs/getting-started-vscode

[Playwright Inspector](https://playwright.dev/docs/debug) e.g. will also tell you what steps isVisible() has performed, alternatively you can use a [Playwright Trace](https://playwright.dev/docs/trace-viewer-intro).

Keep in mind, that isVisible() does not wait at all, it immediately checks if an element with the locator is on the page or not and returns it results. If you want to assert, (which will retry over and over again if the condition is not met) you need to use expect() like you are doing.

**Comment by devmasonn** [comment]
Thank you for your guidance, @mxschmitt ! Your highlighted thing "**it immediately checks**" helped me to fix this issue. I tried increasing wait time and  "const isVisible = await this.page.getByText(‘User name’).isVisible(); " worked for me. I really appreciate your quick response and help !
