### ISSUE TITLE
[BUG] Page Object Model cause taht test runner don't find any tests

### ISSUE THREAD

**Issue by bartoszluczak** [microsoft/playwright#20686]
## System:
 - OS: macOS 13.1
 - Memory: 42.20 MB / 16.00 GB
## Binaries:
 - Node: 18.12.1 - /usr/local/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.19.2 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**
Exemple of Page Object Models from https://playwright.dev/docs/pom

**Describe the bug**
Running any code with the Page Object Model causes an error shown below, the test runner indicates that there is no test. 
![Monosnap todo-list-vite-svelte – example spec ts 2023-02-06 21-03-05](https://user-images.githubusercontent.com/67592317/217078556-a7ac2c35-eda5-4b38-bf5a-d253e52f844a.png)

**Comment by mxschmitt** [comment]
How does your test file look like? Can you share a repro repository? This would help us to narrow down the cause of this error.

**Comment by mxschmitt** [comment]
Are you using component testing? Might be related to https://github.com/microsoft/playwright/issues/20639.

**Comment by aslushnikov** [comment]
Looks like the discussion has stalled, so there's no action item for Playwright team here.

If you think this is still a bug in Playwright, and you have a good repro, please do not hesitate to file a new issue!
