### ISSUE TITLE
[BUG] Injected Highlight elements cause hydration error

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#20689]
**Context:**
- Playwright Version: 1.31.0-alpha-feb-4-2023
- Operating System: Mac
- Node.js version: 16.17.1
- Browser: All

**Describe the bug**

I have a Remix app which uses SSR with React's hydrate feature. When I try to use Playwright debug mode (ie. headed), I get the following error:

`Did not expect server HTML to contain a <x-pw-glass> in <html>`

After some investigation, I'm assuming this is because Playwright injects the x-pw-glass element before the page loads, which leads to React thinking this is the server rendered html.

Is there a workaround for this?

**Comment by WesleyYue** [comment]
I guess this is actually a [react issue](https://github.com/facebook/react/issues/24430#issuecomment-1399979452)

**Comment by mxschmitt** [comment]
I read a bit through the linked upstream React but, seems like we cannot do anything there and it not only affects Playwight, it also affects a bunch of Chrome extensions, e.g. Grammaly, Lastpass etc.

**Comment by WesleyYue** [comment]
Yeah, I think that's mostly right. For future readers using remix, you can potentially do this: https://github.com/remix-run/remix/discussions/5244#discussioncomment-4832036
