### ISSUE TITLE
[Feature] status of CDP + Firefox?

### ISSUE THREAD

**Issue by Mattwmaster58** [microsoft/playwright#20699]
Currently, trying to instantiate a CDP session raising the following exception: "CDP session is only available in Chromium"

I'm aware that [firefox has not always supported CDP well](https://github.com/microsoft/playwright/issues/1765#issuecomment-613178363), but 3 years later, I was wondering if the situation has changed any?

**Comment by pavelfeldman** [comment]
CDP stands for "Chrome DevTools Protocol", so I don't think we should be expecting it implemented in "Firefox", ever.

**Comment by bmikaili** [comment]
Is that really true though? If you see [here](https://firefox-source-docs.mozilla.org/remote/cdp/), firefox does seem to implement a subset of CDP. 

We're using CDP to test Webauthn logins, and would love to be able to test that on Firefox and Webkit too. But it seems like it's more of a limitation of Firefox and Webkit than of playwright.

**Comment by mirao** [comment]
I hit this issue in CodeceptJS when I wanted to read WS messages using https://github.com/codeceptjs/CodeceptJS/blob/1420a65f26e7bd4c528f3d6b51402e299a6b8220/lib/helper/Playwright.js#L3304-L3324.
In that case an alternative solution working in all browsers exists, using https://playwright.dev/docs/network#websockets. Only drawback is that the solution allows reading only from a new WebSocket connection whereas the solution with CDP session allows reading even from an existing WebSocket connection. Or maybe there is more clever way, but I didn't find it.
