### ISSUE TITLE
page.evaluate: ReferenceError: _reportWebVitals is not defined 

### ISSUE THREAD

**Issue by ferozali690** [microsoft/playwright#20697]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Mac]
- Node.js version: [18.12.0]

**Code Snippet**

I want to get web-vitals metrics result from the 'reportWebVitals' function but am unable to achieve the result using playwright.

```javascript
import type { ReportHandler } from 'web-vitals';

const reportWebVitals = (onPerfEntry?: ReportHandler) => {
  if (onPerfEntry && onPerfEntry instanceof Function) {
    import('web-vitals').then(({ getCLS, getFID, getFCP, getLCP, getTTFB }) => {
      getCLS(onPerfEntry);
      getFID(onPerfEntry);
      getFCP(onPerfEntry);
      getLCP(onPerfEntry);
      getTTFB(onPerfEntry);
    });
  }
};

export default reportWebVitals;

import reportWebVitals from '../src/reportWebVitals';

test.only('Performance Checks using web-vitals library', async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(HOME_PAGE_URL, { waitUntil: 'networkidle' });
  const getVitals = (args) => {
    console.log('args', args);
    
  };
  await page.evaluate(async () => {
    reportWebVitals(getVitals);
  });
});
```

**Describe the bug**

Add any other details about the problem here.

**Comment by Smrtnyk** [comment]
Not sure you can use `page.evaluate` like that
https://playwright.dev/docs/api/class-page#page-evaluate

**Comment by ferozali690** [comment]
then how can page.evaluate be used ? if I want to pass non-serializable values, inside the page.evaluate I want to call ' reportWebVitals(getVitals)' function.

**Comment by mxschmitt** [comment]
That's not a Playwright issue, I recommend reaching out to web-vitals on how to integrate it with Playwright, see e.g. https://github.com/GoogleChrome/web-vitals/issues/180 or checkout Playwright's Discord community. See also here about [evaluate fundamentals](https://playwright.dev/docs/evaluating).
