### ISSUE TITLE
[BUG]: Not able to handle new popUp window as a new Page

### ISSUE THREAD

**Issue by devmasonn** [microsoft/playwright#20698]
**Context:**
Playwright Version: 1.29.2
Operating System: Mac
Node.js version: v17.0.1
Browser: WebKit
Extra: NA

**Code Snippet**
```Typescript
**SignIn.test.ts:**

test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();        
        const context = await browser.newContext();

        // Create a new context for the pop-up
        const popUpContext = await browser.newContext();
        popUpPage = await popUpContext.newPage();
    
        await page.goto(“https://example.com/”);

        signInPage = new SignInPage(page,popUpPage);
    })


**SignInPage.ts:**

export default class SignInPage {
    
    readonly page: Page;
    readonly newPage: Page;
    readonly frame: FrameLocator;
    readonly signInBtn: Locator;
    readonly textBox: Locator;

constructor(page: Page, popUpPage: Page) {
        this.page = page;
        this.newPage = popUpPage;
        this.frame = page.frameLocator("//iframe[contains(@name,’login’)]”);
        this.signInBtn = this.page.getByRole('button', { name: 'Sign In' });
        this.textBox = this.newPage.getByLabel('Sign In with your ID');
}

async signIn() {
        await expect(this.signInBtn,'Sign In button is not there.').toBeEnabled();
        await this.signInBtn.click();

await expect( this.textBox,’Textbox is not there.').toBeEnabled();
        await  this.textBox.click();

  }
}
```

**Describe the bug**

I am trying to handle new popUp window which is coming as a new page window. I have tried with creating new context and page to handle a new popup window but it is not working with the above code. Need a help to fix this issue.

**Comment by mxschmitt** [comment]
You are creating two browser contexts. Since both of them are fully isolated with each-other, a login in one has no effect on the other. I think what you want instead is to just create two pages of a single context.

Also for me its not fully clear what you mean with _popup window which is coming as a new window_. If its actually created by the page, then you don't need to create the page and just listen for a new popup, see here: https://playwright.dev/docs/pages#handling-popups

**Comment by devmasonn** [comment]
> You are creating two browser contexts. Since both of them are fully isolated with each-other, a login in one has no effect on the other. I think what you want instead is to just create two pages of a single context.
> 
> Also for me its not fully clear what you mean with _popup window which is coming as a new window_. If its actually created by the page, then you don't need to create the page and just listen for a new popup, see here: https://playwright.dev/docs/pages#handling-popups

While trying this piece of the code : 
      const popupPromise = page.waitForEvent('popup');
      await page.getByText('open the popup').click();
      const popup = await popupPromise;
      // Wait for the popup to load.
      await popup.waitForLoadState();
      console.log(await popup.title());

Still facing the same issue, not able to interact with the locator that are coming on a new popup window page. And also, could you please clarify what would be in the place of this line "await page.getByText('open the popup').click();" ?

**Comment by mxschmitt** [comment]
Usually a browser window aka. a popup opens after a click. That's why there is this text which should be replaced with the actual Locator.

**Comment by devmasonn** [comment]
I tried this way to handle new page : 

        const pagePromise = this.context.waitForEvent('page');
        await this.aidPageIframe.getByRole('button', { name: 'Continue' }).click();
        const newPage = await pagePromise;
        await newPage.waitForLoadState();
        console.log(await newPage.title());

And, also I have tried to handle popup:

        const popupPromise = this.page.waitForEvent('popup');
        await this.page.getByRole('button', { name: 'Continue' }).click();
               or await this.frame.getByRole('button', { name: 'Continue' }).click();
        const popup = await popupPromise;
        await popup.waitForLoadState();
        console.log(await popup.title());

Still not able to interact with a new popup(page) window.

**Comment by devmasonn** [comment]
Thank you, @Max Schmitt for following up on this issue. Finally, I am able to fix this issue with the help of **Playwright Inspector**. There was a little correction for a new page in this code, a new popup window locators should be called with a new page created from "this.page.waitForEvent('popup')" not the one which I was creating explicitly within the BrowserContext. Creating a new page and locators in the function itself was a game changer for me. And since, a new window opens up after the "Continue" button for me, I am calling after "this.page.waitForEvent('popup')" helped me. Below is the correct code which is working for me:

**SignIn.test.ts:**

         test.beforeAll(async ({ browser }) => {
                 page = await browser.newPage();        
                 await page.goto(“https://example.com/”);

                 signInPage = new SignInPage(page);
         })

**SignInPage.ts:**

        export default class SignInPage {
    
              readonly page: Page;
              readonly frame: FrameLocator;
              readonly signInBtn: Locator;
              readonly textBox: Locator;

          constructor(page: Page) {
                  this.page = page;
                  this.frame = page.frameLocator("//iframe[contains(@name,’login’)]”);
                  this.signInBtn = this.page.getByRole('button', { name: 'Sign In' });
          }

          async signIn() {
                  await expect(this.signInBtn,'Sign In button is not there.').toBeEnabled();
                  await this.signInBtn.click();
          
                   const popupPromise = this.page.waitForEvent('popup');
                   await this.frame.getByRole('button', { name: 'Continue' }).click();
                   const popupPage = await popupPromise;
                   await popupPage.waitForLoadState();
          
                  const textBox = popupPage.newPage.getByLabel('Sign In with your ID');
                  await expect(textBox, ’Textbox is not there.').toBeEnabled();
                  await textBox.click();
          
            }
            }

**Comment by mxschmitt** [comment]
Cool, happy to hear that its working now!
