### ISSUE TITLE
[Feature] "Step to line" in Playwright Inspector/Debugger

### ISSUE THREAD

**Issue by WesleyYue** [microsoft/playwright#20690]
I usually have a route handler that intercepts every network request and prints it, like this:
```
await page.route("**/*", logHttpErrors)
```

```
import type { APIResponse, Route } from "@playwright/test";

async function logHttpErrors(route: Route): Promise<void> {
  let response: APIResponse;
  try {
    response = await route.fetch();
  } catch (e) {
    // Will catch network errors and 500s.
    console.error("Error fetching route: ", route.request().url());
    // expect(e).toBeUndefined();
    return;
  }
  const status = response.status();

  if (status >= 400 && status < 500) {
    console.warn(`Response ${status} – ${route.request().url()}`);
  }

  await route.fulfill({ response });
}

export { logHttpErrors };
```

When trying to use the debugger/inspector to step line by line with this enabled, network requests are constantly being fired and so if my test execution is paused, it's impossible to click Resume or Step Over, since the inspector ui constantly is executing the callback. So technically, it is executing, it's just executing in the callback code (logHttpErrors) instead of my main test.

**Comment by mxschmitt** [comment]
Since you are only sniffing, you can also do the following (listen to response events) which might give you better results: https://playwright.dev/docs/network#network-events

**Comment by WesleyYue** [comment]
Will try that, thanks!

**Comment by WesleyYue** [comment]
@mxschmitt Would you consider a feature along the lines of `pauseDebugger()`? This wouldn't require any UI changes on the stepper, and the framework just needs to detect if it's running in debug mode, and if so, pause running at that point.

**Comment by mxschmitt** [comment]
Why does [`page.pause()`](https://playwright.dev/docs/api/class-page#page-pause) not work for that?
