### ISSUE TITLE
[Feature] Can we run playwright in ubuntu 16.04 docker image?

### ISSUE THREAD

**Issue by xie258** [microsoft/playwright#20702]
Before running playwright, we install dependency with commands:

 `npx playwright  install chrome `
![image](https://user-images.githubusercontent.com/33753628/217170109-d1a6edf2-bb9f-44a8-871c-e5e468d6cfee.png)

`npx playwright  install-deps`
![image](https://user-images.githubusercontent.com/33753628/217170430-5319b0cd-8329-441c-b916-f67542d81793.png)

But failed to install, does playwright support running on ubuntu 16.04 ?

**Comment by mxschmitt** [comment]
Playwright only supports Ubuntu 20+ see here: https://playwright.dev/docs/troubleshooting#system-requirements
