### ISSUE TITLE
[BUG] Codegen doesn't follow "timeout" argument

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#20710]
**Context:**
## System:
 - OS: macOS 13.2
 - Memory: 11.82 GB / 32.00 GB
## Binaries:
 - Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 9.2.0 - ~/.nvm/versions/node/v19.4.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```
npx playwright codegen --timeout=30000 http://localhost:4200
```

**Describe the bug**

Codegen exits instantly, without waiting:
`[Error: net::ERR_CONNECTION_REFUSED at http://localhost:4200/`

**Comment by mxschmitt** [comment]
This is expected, as per `npx playwright codegen --help` it says `timeout for Playwright actions in milliseconds, no timeout by default` so it only affects e.g. page.click, page.fill etc.
