### ISSUE TITLE
[BUG][extension] "Show Output" show log only first time. Test error hidden after file was changed.

### ISSUE THREAD

**Issue by alexneo2003** [microsoft/playwright#20719]
**Context:**
## System:
 - OS: macOS 12.6
 - Memory: 112.50 MB / 16.00 GB
## Binaries:
 - Node: 18.10.0 - /usr/local/bin/node
 - Yarn: 1.22.17 - /usr/local/bin/yarn
 - npm: 9.4.0 - /usr/local/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
 
- Playwright Version: 1.30.0
- VSCode version: 1.75.0
- Playwright for VSCode extension version: 1.0.6

**Code Snippet**

simple PW project what installed from extension

**Describe the bug**

1. "Show Output" show log only first time, each other times run tests output does not showing
<img width="1084" alt="Monosnap example spec ts — pw-example 2023-02-07 17-38-34" src="https://user-images.githubusercontent.com/11705902/217291119-4cc5378e-040f-451b-af4c-1f48996b38a8.png">

https://user-images.githubusercontent.com/11705902/217293641-623d829b-725f-49a6-83e2-e2240272efef.mp4

2. After test failing extension showing error at test code. When i'm change file - error was hidden

https://user-images.githubusercontent.com/11705902/217292746-8a641760-1517-4ff9-b247-d467067c1095.mp4

**Comment by dgozman** [comment]
Fixed in VSCode 1.75.1.
