### ISSUE TITLE
[Feature] Timeout for host on Codegen launch

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#20716]
Please consider adding an argument, similar to "timeout", that would instruct PW Codegen to wait for host's readiness to accept requests.
It would let me create a single command, that runs the local server and launches PW Codegen in parallel.
Right now I have to explain in docs, that user should launch server first, then launch PW Codegen in a new terminal tab.

**Comment by mxschmitt** [comment]
This is outside of the scope for codegen, since you can easily do it in the user-land.

e.g. using [wait-on](https://www.npmjs.com/package/wait-on): `npx wait-on http://localhost:300 && npx playwright codegen http://localhost:3000`;

**Comment by e-oz** [comment]
Well, with this logic testing can be done with different tools also.
