### ISSUE TITLE
[Question] Chromium always launching in Incognito mode

### ISSUE THREAD

**Issue by MaxTester1** [microsoft/playwright#2071]
Hi 

Chromium always launching in Incognito mode **which causing my app authentication fail**, how do i change this behavior to launch chrome in normal mode

Below sample script

```js
const playwright = require('playwright');

(async () => {
  for (const browserType of ['Chromium']) {
    const browser = await playwright[browserType].launch({headless: false});
    // const context = await browser.newContext();
    const page = await browser.newPage();
    await page.goto('http://www.google.com'); -**-I get error for my application**
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();
```

Error:
```
**Error Code: 500
Http failure response for https://xxx-oauth-qas.xxx.com/as/tokenKerb: 500 ERROR**
```

**same application works fine with puppeteer as it launches in normal mode**

**Comment by arjun27** [comment]
Thanks, @maxtester1. Can you elaborate more on what exactly is breaking with incognito mode? Could this be related to #2072?

**Comment by pavelfeldman** [comment]
The script you provide uses `webkit` and does not quote example. I fixed it and ran it against Chromium and WebKit and it worked.

Did you expect that you will be logged into your Google account? If you are not doing testing, you can use `browserType.launchPersistent` and point to your user profile directory.

**Comment by MaxTester1** [comment]
> Thanks, @MaxTester1. Can you elaborate more on what exactly is breaking with incognito mode? Could this be related to #2072?

Hi @arjun27 , i tried #2072 but dint help. i have updated details in original post, please check

**Comment by MaxTester1** [comment]
> The script you provide uses `webkit` and does not quote example. I fixed it and ran it against Chromium and WebKit and it worked.
> 
> Did you expect that you will be logged into your Google account? If you are not doing testing, you can use `browserType.launchPersistent` and point to your user profile directory.

Hi @pavelfeldman Thanks fro response, i tried  const browser = await playwright[browserType].launchPersistentContext(userDataDir,{headless:false}) and it worked. Browser launched in normal mode.

**Comment by aslushnikov** [comment]
> Is there any way like puppeteer launch chromium normal mode without persistent context?

@MaxTester1 Playwright's persistent context is equal to Puppeteer's chromium launch. This is not the default mode in Playwright though since Playwright focuses on better automation isolation and browser instance re-use (thus the whole concept of contexts).

**Comment by MaxTester1** [comment]
> > Is there any way like puppeteer launch chromium normal mode without persistent context?
> 
> @MaxTester1 Playwright's persistent context is equal to Puppeteer's chromium launch. This is not the default mode in Playwright though since Playwright focuses on better automation isolation and browser instance re-use (thus the whole concept of contexts).

Thank you @aslushnikov for the update.

**Comment by OlgaKuksa** [comment]
> > Is there any way like puppeteer launch chromium normal mode without persistent context?
> 
> @MaxTester1 Playwright's persistent context is equal to Puppeteer's chromium launch. This is not the default mode in Playwright though since Playwright focuses on better automation isolation and browser instance re-use (thus the whole concept of contexts).

Agreed with isolation etc. But it's a bit inconvenient if one needs to take screenshots for screenshot testing. AFAIU incognito doesn't allow screenshots. Or is there a way to do it with Playwright-Chromium incognito I don't know about?

**Comment by sublimator** [comment]
When testing extensions incognito mode can get in the way also

**Comment by muhqu** [comment]
This is also an issue when testing sites that make use of Origin-Trial features which are not available in incognito mode… There should be an option in `LaunchOptions` that allows to easily switch to normal mode.

**Comment by sublimator** [comment]
> There should be an option in LaunchOptions that allows to easily switch to normal mode.
Would be good right 

The team have made some pretty opinionated choices and dropped support for extensions. It's a bit disappointing.

**Comment by smartahsan** [comment]
> > There should be an option in LaunchOptions that allows to easily switch to normal mode.
> 
> Would be good right
> 
> The team have made some pretty opinionated choices and dropped support for extensions. It's a bit disappointing.

It really is surprising I thought there would be a way to launch in a normal browser.

**Comment by valentijnpeters** [comment]
The below sample script is a .js file

**Comment by ssasane-tibco** [comment]
Any simplest way to launch it in non-incognito mode? by just making some changes in the config file or test runner file?
