### ISSUE TITLE
[BUG] viewport is not chaging as window resizes 

### ISSUE THREAD

**Issue by fluxx030** [microsoft/playwright#20721]
**Context:**
- Playwright Version: 1.29.2 
- Operating System: ubuntu
- Node.js version:16
- Browser: firefox

**Code Snippet**

this just default test code , this is also not working ,
view port is not changing as a resize window, it dosent matter if i set viwport value to null or 0 its same .

```javascript
const { chromium, firefox, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });  // Or 'firefox' or 'webkit'.
  const page = await browser.newPage();
  await page.goto('http://xyz.com');
  // other actions...

})();
```

![Screenshot from 2023-02-07 23-23-59](https://user-images.githubusercontent.com/112842171/217328552-232effee-80ec-49d9-a414-cc02f78b6fa2.png)

**Comment by mxschmitt** [comment]
This is expected, Playwright runs with its own viewport, when you disable it with browser.newPage({viewport: null}) it will use the window viewport. Did you try it?

**Comment by fluxx030** [comment]
thanks it solved my issue !

**Comment by jpgklassen** [comment]
Another option is to set `viewport` to `null` for the entire Browser Context:
```node
const browser = await chromium.launchPersistentContext('auth', { viewport: null })
```
