### ISSUE TITLE
[REGRESSION]: 

### ISSUE THREAD

**Issue by brittnicole207** [microsoft/playwright#20739]
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?]
- BAD Playwright Version: [what Playwright version doesn't work any more?]
- Operating System: [e.g. Windows, Linux or Mac]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  // ... 
})();
```

**Describe the bug**

glitch.dec.2021.feb.2022<

**Comment by brittnicole207** [comment]
glitch.dec.2022.feb.2023<

**Comment by mxschmitt** [comment]
Can you give us more information what the regression is? Otherwise have to close the issue.
