### ISSUE TITLE
[Feature] Add steps option to mouse.dblclick

### ISSUE THREAD

**Issue by zedd3v** [microsoft/playwright#2074]
Hello
Would it be possible to add a steps option to mouse.dblclick like there is one on mouse.move

https://github.com/microsoft/playwright/blob/v0.16.0/docs/api.md#mousedblclickx-y-options
https://github.com/microsoft/playwright/blob/v0.16.0/docs/api.md#mousemovex-y-options

**Comment by pavelfeldman** [comment]
You can always mouse move w/ steps and then dblclick or what are you after?

**Comment by aslushnikov** [comment]
Pavel's answer works great!
