### ISSUE TITLE
[BUG] How to set font and language for browser ?

### ISSUE THREAD

**Issue by fluxx030** [microsoft/playwright#20742]
i am using playwright in Linux desktop and when i launch creep js shows me i am emulating windows but my fonts are not matching , so i want to change my fonts to windows for particular playwright  instance or browser session , is there any way to do it ?

also i want to change language setting to right now i can do it manually but i am wondering is there any smarter way ?

**Comment by mxschmitt** [comment]
what is creep js? There is no way to way to change fonts, you need to load them inside of your page and set them CSS wise.

You can change the locale inside the config in the use section or inside the test: https://playwright.dev/docs/emulation#locale--timezone

**Comment by fluxx030** [comment]
creep js is basically bot detector here is link .
[](https://abrahamjuliot.github.io/creepjs/)https://abrahamjuliot.github.io/creepjs/

by using `local`  i am able to change content language but its not changing browser language , for example if i open settings then its still in English.

also can you share example code how can i load and change fonts using css .

**Comment by mxschmitt** [comment]
This is expected, that does not reflect it on anything inside the page. If you have a specific API which does not get mocked correctly, please let me know, happy to fix then.

**Comment by aslushnikov** [comment]
Looks like the discussion has stalled and there's no action item for the Playwright team here. 

If you still think there's a bug in Playwright and you have a good repro, please do not hesitate to file a new issue!

**Comment by fluxx030** [comment]
i  had to download Firefox japnese version for  language and that solved my issue
