### ISSUE TITLE
[BUG] Global-setup and global-teardown running for each shard

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#20747]
1. As below code I m using sharding

    
  ```
  "pw:stage": " npx playwright test --project=chrome  --shard=1/3",
    "pw:stage1": "npx playwright test --project=chrome --shard=2/3",
    "pw:stage2": " npx playwright test --project=chrome --shard=3/3",
    "all": "npm-run-all --parallel pw:stage pw:stage1 pw:stage2"
```

running `npm run all `command on terminal. In my global setup , I m using authantication and in the global teardown, using clear data commands.

Global-setup and global-teardown not working one time for each shard, working for each shard so giving error.Is there any way grep invert for global-teardown or something else?

2. When I run all shards in my local, report overwritten. How to merge them?,There is no different reports,only one overritten report.

**Comment by mxschmitt** [comment]
If you want to run a single global setup for your different test-runs, then you need to put it inside a small node script, and call it via e.g. `node setup.js`

For sharding and combining it with the html report, we have it filed here: https://github.com/microsoft/playwright/issues/10437

**Comment by YusufOzt** [comment]
@mxschmitt thanks for response
