### ISSUE TITLE
[Feature] Replace deprecated `set-output` command with environment file

### ISSUE THREAD

**Issue by jongwooo** [microsoft/playwright#20751]
## Description

In workflow, `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information, see: [https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/)

See also [microsoft/vscode#172689](https://github.com/microsoft/vscode/issues/172689)

**Comment by mxschmitt** [comment]
Where do we use it? Are you using GitHub reporter? Can you share your workflow or a link to your GitHub Actions run?

**Comment by jongwooo** [comment]
@mxschmitt I found the workflow files that use `set-output` command through the following command:

```bash
$ find .github/workflows -name '*.yml' -o -name '*.yaml' | xargs egrep '\bset-output\b'
```

Result:
```shell
./.github/workflows/roll_driver_nodejs.yml:          echo "::set-output name=HAS_CHANGES::1"
./.github/workflows/roll_driver_nodejs.yml:          echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
./.github/workflows/roll_browser_into_playwright.yml:        echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
./.github/workflows/cherry_pick_into_release_branch.yml:        echo "::set-output name=PR_TITLE::$LAST_COMMIT_MESSAGE"
./.github/workflows/cherry_pick_into_release_branch.yml:        echo "::set-output name=BRANCH_NAME::$BRANCH_NAME"
```

**Comment by jongwooo** [comment]
If you don't mind, can I create a pull request?
