### ISSUE TITLE
[BUG] Expect assertion fails but logs and html-report show that the test passed

### ISSUE THREAD

**Issue by xGenTJ** [microsoft/playwright#20753]
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Node.js version: 19.6.0
- Browser: Chromium

Code Snippet:

    test.only('Termination', async ({ page, browser, context }) => {

        const expected = ["A", "B", "C"];
        try{
            const result = await viewIdentityPage.getAllApplicationAccounts();
            await expect(result).toEqual(expected);
        }
        catch (err){}

    }

I have seen this bug in other tickets, and the answer was to put an await before the expect. However, this bug still occurs after I've added the await

**Comment by mxschmitt** [comment]
This is expected, since the assertions are implemented in a way, that they will throw if they don't pass. Instead of you need to either re-throw inside your catch or don't have a try/catch.

**Comment by xGenTJ** [comment]
I see. It really confused me since in my mind, an error is still thrown, and the reporter even knows it, but decides to show the test passed anyways.
