### ISSUE TITLE
[BUG] - support custom AsymmetricMatchers

### ISSUE THREAD

**Issue by johndetlefs** [microsoft/playwright#20761]
**Context:**
- Playwright Version: 1.30
- Operating System: Mac
- Node.js version: [16.14.2]
- Browser: All
- Extra: [any specific details about your environment]

**Code Snippet**

`global.d.ts`

```javascript
export { };
import { AsymmetricMatcher } from './node_modules/@playwright/test/types/test';
declare global {
    type CustomAsymmetricMatchers = {
        toBeStringOrNull(): AsymmetricMatcher;
    }
    namespace PlaywrightTest {
        interface Matchers<R> {
            toBeStringOrNull(): R;
        }
    }
}
```

I've also added the `CustomAsymmetricMatchers` type to `Expect` in `test.d.ts`

```javascript
...

export type AsymmetricMatcher = Record<string, any>; // exported the type AsymmetricMatcher

...

} & BaseExpect &
  AsymmetricMatchers &
  CustomAsymmetricMatchers &
  Inverse<Omit<AsymmetricMatchers, 'any' | 'anything'>>; 
```

`api.test.ts`

```javascript
import { test, expect } from "@playwright/test";
import { ApiRoutes, baseURL } from "../../constants/api.const";

test.use({
  baseURL: baseURL
});

test.describe("manufacturers", () => {
  test("gets manufacturers", async ({ request }) => {
    const response = await request.get(ApiRoutes.Manufacturers);
    expect(response.status()).toBe(200);
    const data = await response.json().then((data) => data[0]);
    expect(data).toEqual({
      id: expect.any(String),
      name: expect.any(String),
      imageName: expect.toBeTypeOrNull(String), // without the extra code this isn't recognised by intellisense
      websiteUrl: expect.stringMatching(/https?:\/\/.+/),
      websiteWarrantyUrl: expect.stringMatching(/https?:\/\/.+/),
      productCategories: expect.toBeTypeOrNull(Array)
    });
  });
```

**Describe the bug**

When creating a custom matcher in TS the `global.d.ts` template given [in the documentation](https://playwright.dev/docs/test-advanced#add-custom-matchers-using-expectextend) only seems to allow intellisense to work for `Matchers`, but they aren't working with `AsymmetricMatchers`. I've manually updated the `@playwright/test/types/test.d.ts` file using the above code to make it work.

I'm relatively new to TS so there may be a better way of doing this, or I may have missed something, if so, apologies!

**Comment by mxschmitt** [comment]
I tried the following and it worked for me, what do I do different?

```ts
// global.d.ts
export {};

declare global {
 namespace PlaywrightTest {
    interface Matchers<R, T> {
      toBeWithinRange(a: number, b: number): Promise<R>;
    }
  }
}
```


```ts
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await expect(page).toBeWithinRange(1, 2);
})
```

**Comment by johndetlefs** [comment]
I've updated my original comment with the testing code. 👍

**Comment by mxschmitt** [comment]
Could we first start with what you are trying to do? You should never edit files in the node_modules folder by had.

**Comment by johndetlefs** [comment]
It's less than ideal I agree, but has certainly allowed me to get on with my work. :)

In terms of what I'm after, I would expect (pardon the pun) my custom `expect` matcher to be available both as a Type `Matcher` and as an `AsymmetricMatcher` - and this is how the code compiles, tests run great in both scenarios, so all good there.

Where things are breaking is in the typings, and VSCode is giving a `your custom matcher is not in type Expect` which, after checking the code in `@playwright/test/types/test` appears to be true, and I've temporarily fixed that (possibly not the best solution but has gotten me back to work) using the above code.

**Comment by mxschmitt** [comment]
Looks like Jest has support for it extending it type wise but we don’t.

Action item on our side is to make it work like it’s working upstream.

**Comment by asos-jonathanholford** [comment]
Hi, I note that a PR for this was closed without merging.

Is there some further discussion on this somewhere? It would be very useful to have this typing available to us.

**Comment by mxschmitt** [comment]
We decided to not add it for now to not increase our API scope for this feature. Once we have enough interest for this feature we'll reconsider.

**Comment by t3hk0d3** [comment]
@mxschmitt
This is one of core features for many testing frameworks, especially considering how poor choice of matchers in current implementation.

Maybe you should consider removing asymmetric matchers altogether? It will further reduce API scope, so less work for you guys.

**Comment by pavelfeldman** [comment]
Closing as per above.

**Comment by poponuts** [comment]
How will this gain interest again if closed?

**Comment by 4ekki** [comment]
I'm interested in this.

**Comment by andriy-genndy** [comment]
+1 for reopening this. IDK how it can be acceptable for a serious testing framework to not support extending its assertions with custom (asymmetric) matchers.

**Comment by t3hk0d3** [comment]
> +1 for reopening this. IDK how it can be acceptable for a serious testing framework to not support extending its assertions with custom (asymmetric) matchers.

Relax, thats Microsoft (tm)


Developers Developers Developers....
