### ISSUE TITLE
Unable to configure @alex_neo/playwright-azure-reporter

### ISSUE THREAD

**Issue by rovmak** [microsoft/playwright#20769]
This is the error that i get and i cannot figure it out.

Failed to create test run. Reporting is disabled.
undefined:1
Cannot read properties of null (reading 'value')
^

SyntaxError: Unexpected token 'C', "Cannot rea"... is not valid JSON
    at JSON.parse (<anonymous>)
    at AzureDevOpsReporter.onBegin

**Comment by mxschmitt** [comment]
Since this project is not affiliated with us, I recommend filing an issue in their repository: https://github.com/alexneo2003/playwright-azure-reporter
