### ISSUE TITLE
[BUG]Memory not freed after page close if page.on/route/content API is called

### ISSUE THREAD

**Issue by wispxjtu** [microsoft/playwright#20765]
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [Mac]
- Node.js version: [v16.16.0, v18.13.0]
- Browser: [ All, Chromium, Firefox]
- Extra: []

node --max-old-space-size=50 --expose-gc main.js

## System:
 - OS: macOS 12.6
 - Memory: 401.52 MB / 64.00 GB
## Binaries:
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.30.0 => 1.30.0

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const { chromium, firefox } = require('playwright');

(async function main() {
    console.log('start')
    const browser = await chromium.launch();
    const bc = await browser.newContext();

    for (let i = 0; i < 10000; i++) {
        console.log(`Open page ${i}`);
        const page = await bc.newPage();

        // Enable any line of below code will cause memory keep increasing significantly
        // page.on('request', () => {});
        // page.on('requestfinished', ((request) => {}));
        // page.on('requestfailed', () => {});
        // await page.route('**/*', (route, request) => {route.continue();});

        // You can use other page to reproduce this issue too
        await page.goto('http://localhost:3000/size_1m.html');

        // This API will cause memory issue too
        // Multiple call will cost more memory
        await page.content();
        await page.close();

        try {
            if (global.gc) {global.gc();}
        } catch (e) {
            console.log("`node --expose-gc index.js`");
            process.exit();
        }
        const {heapUsed, heapTotal}  = process.memoryUsage();
        console.log(`Used: ${Math.round( heapUsed / 1024 / 1024 * 100) / 100} MB`);
        console.log(`Total: ${Math.round( heapTotal / 1024 / 1024 * 100) / 100} MB`);
    }
})();
```

**Describe the bug**
```
node --max-old-space-size=50 --expose-gc main.js
```
This process will OOM after open about 15 pages if your html size is 1MB
Enable page.on/route API or call page.content() more than one time will cause OOM issue been reproduced more quicker.

The memory cannot be freed after page close. 
Close BrowserContext can free these memory but it's not our expected behavior.

I found another issue related https://github.com/microsoft/playwright/issues/11037 , but not sure if they're the same.

**Comment by wispxjtu** [comment]
register download event or use once() API do not have this issue
```
page.on('download', () => {});
page.once('request', () => {});
```

**Comment by mxschmitt** [comment]
Yes its the same, folding into https://github.com/microsoft/playwright/issues/11037.
