### ISSUE TITLE
page.route is not able to capture POST traffic in Python

### ISSUE THREAD

**Issue by agrawalsmart7** [microsoft/playwright#20776]
This is my test code

```
from playwright.sync_api import sync_playwright
import json

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False, slow_mo=10000)
    page = browser.new_page()

    # Define a route to intercept a POST request
    def modify_response(route):
        # Check if the request method is POST
        try:
            print("Not even printing this")
            if route.request.method == "POST":
                # Fetch the original response
                response = route.continue_()

                # Modify the response text
                original_text = response.body().decode("utf-8")
                modified_text = original_text.replace("error", "success")
                response.body = modified_text.encode('utf8')

                return response
                
        except AttributeError as e:
            print (e)
            return False
        
    # Add the route to the page
    page.route("/auth.php", modify_response)

    # Navigate to a page and submit a POST request
    print("akjbkhjbkbj")
    data = {"username":"admin","password":"admin"}
    response = page.request.post(
        "http://localhost:8091/auth.php",
        headers={
            "Content-Type": "application/json"
        },
        data=json.dumps(data).encode()
    )
    
    print(response.status)
    print(response.body())

    browser.close()
    
```
  
  I am trying to intercept the POST request but not able to do that, not even the function modify_response gets called why is that? I checked I successfully sending the POST request but this is not working. Please help if anyone can do.

**Comment by agrawalsmart7** [comment]
After playing here and here, it was observed that route only intercepts the request made through goto function. Now can anyone suggest me what can I change in mky code ? Because I can't send POST via goto.

**Comment by mxschmitt** [comment]
Glob accepts a full URL match, a glob which matches the full URL or a callback. In your case you need to have `**/auth.php` instead, then it should work and the page.route should trigger. Have you tried that? See here: https://playwright.dev/docs/api/class-page#page-route

**Comment by agrawalsmart7** [comment]
> Glob accepts a full URL match, a glob which matches the full URL or a callback. In your case you need to have `**/auth.php` instead, then it should work and the page.route should trigger. Have you tried that? See here: https://playwright.dev/docs/api/class-page#page-route

No still same, check my code and output

`from playwright.sync_api import sync_playwright
import json

def handle_route(route):
# Check if the request method is POST
    print("Not even printing this")
    try:
        if route.request.method == "POST":
            # Fetch the original response
            response = route.fetch()

            # Modify the response text
            original_text = response.body().decode("utf-8")
            modified_text = original_text.replace("error", "success")
            response.body = modified_text.encode('utf8')

            return response
    except AttributeError as e:
        print (e)
        return False
    
    
with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False, slow_mo=10000)
    page = browser.new_page()

    # Define a route to intercept a POST request
   

    # Add the route to the page without the scheme
    print("Is this working)")
    page.route("**/auth.php", handle_route)
    print("Yes it is")

    # Navigate to a page and submit a POST request with the scheme
    print("akjbkhjbkbj")
    data = {"username":"admin","password":"admin"}
    response = page.request.post(
        "http://localhost:8091/auth.php",
        headers={
            "Content-Type": "application/json"
        },
        data=json.dumps(data).encode()
    )
    
    print(response.status)
    print(response.body())

    browser.close()
`

Results

`Is this working)
Yes it is
akjbkhjbkbj
200
b'{"status":"error","message":"Invalid credentials"}'`

**Comment by agrawalsmart7** [comment]
My Working environment is Windows with Python

**Comment by mxschmitt** [comment]
Try ` page.route("**/*/auth.php", handle_route)`

**Comment by agrawalsmart7** [comment]
@mxschmitt Problem is, page.route don't capture api requests, it only captures the request went through goto function. I guess this should be at the code end. Let me know if I give you the correct lead.

**Comment by agrawalsmart7** [comment]
Look at this code - 

```

with sync_playwright() as playwright:
    browser = playwright.chromium.launch(headless=False, slow_mo=10000)
    page = browser.new_page()

    # Define a route to intercept a POST request
   

    # Add the route to the page without the scheme
    print("Is this working)")
    print("Yes it is")
    page.route("**/*", handle_route)
    # Navigate to a page and submit a POST request with the scheme
    data = {"username":"admin","password":"admin"}
    page.goto("http://localhost:8090/login.php")
    
    page.locator('input[name="usr_email"]').fill('test@test.com')
    page.locator('input[name="usr_password"]').fill('Test12!@')
    page.locator('input[type="submit"]').click()
    browser.close()
    # print(response.status)
    # print(response.body())

    browser.close()
    
```

It was successfully proxy the login request went on auth.php when submitting the login form.

**Comment by mxschmitt** [comment]
Ah this is expected, that `page.request.post` won't end up in `page.route` since it would just roundtrip it anyways, like a noop.

**Comment by aslushnikov** [comment]
This seems to be working as expected, so I'll close this for now. Please, do not hesitate to file a new issue if you think we still can be helpful to you somehow!
