### ISSUE TITLE
[QUESTION] page.waitForSelector times out but locator resolved to visible

### ISSUE THREAD

**Issue by mkusy-ig** [microsoft/playwright#20772]
**Context**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 16.*
- Browser: Chromium
- Extra: -

**Code snippet**:
```javascript
await page.waitForSelector(`[data-element-id="element_1"]:text-matches("${regexPattern}", "i")`, { timeout: 3000 });
```
**Describe the bug**:
```
page.waitForSelector: Timeout 3000ms exceeded.
=========================== logs ===========================
waiting for locator('[data-element-id="element_1"]:text-matches("^(?!0.00).*$", "i")') to be visible
  locator resolved to visible <div class="some classes" data-elem…>some value</div>
```
What does the above error message indicate? I'm trying to wait until an element's value becomes different than a given value and so am using page.waitForSelector. The method times out however the console message indicates that the locator was resolved to a visible element. Worth to mention this seems to happen randomly, for about 10% of cases.

**Comment by mxschmitt** [comment]
If you want to assert that an element is on the page, we recommend toBeVisible, see [here](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible): 

```ts
const locator = page.locator('[data-element-id="element_1"]', { hasText: regexPattern });
await expect(locator).toBeVisible();
```

let us know if that works for you!

**Comment by mkusy-ig** [comment]
Thanks for the guidance Max! In the end it seems to have been a performance issue where it took a longer time than 3000ms  for the element to get the desired value but I will keep in mind the alternative approach. Cheers

**Comment by codynguyen** [comment]
I'm doing a scraper and ran into the same problem. Playwright throws a TimeoutError even though it says the locator's been resolved to visible.

The code I used:

```
await page.locator('td.text:has-text("is temporarily unavailable"), #server-side-error, h3.ecaap-header-title:has-text("Extra security step required"), #nb-utilityMenu-a-profile-and-settings').waitFor()
```

Here's the log:

```
waiting for locator('td.text:has-text("is temporarily unavailable"), #server-side-error, h3.ecaap-header-title:has-text("Extra security step required"), #nb-utilityMenu-a-profile-and-settings') to be visible
locator resolved to visible <a id="nb-utilityMenu-a-profile-and-settings" class…>…</a>
```

Question is why? It is resolved to visible so it should return the result and not throw the error no?

**Comment by himat** [comment]
Any update on this as to why this happens?
