### ISSUE TITLE
[BUG] `TestConfigWebServer` type is not exported

### ISSUE THREAD

**Issue by SebastianSedzik** [microsoft/playwright#20777]
**Context:**
- Playwright Version: `1.30.0`
- Operating System: `Mac`
- Node.js version: `16.17.0`
- Browser: -
- Extra:
  - bundler: [vite@4.1.1](https://www.npmjs.com/package/vite)
  - plugin for generating dts files: [vite-plugin-dts@1.7.2](https://www.npmjs.com/package/vite-plugin-dts) 

**Code Snippet**
```ts
import { PlaywrightTestConfig } from "@playwright/test/types/test";

export const defineConfig: (config: Partial<PlaywrightTestConfig>) => {...}
```

**Describe the bug**
Cannot generate TS typings when using `PlaywrightTestConfig` type.

I'm creating library that accepts config: `PlaywrightTestConfig`. When trying to generate TS typings I receive an error:
```
Exported variable 'defineConfig' has or is using name 'TestConfigWebServer' from external module "/Users/x/@playwright/test/types/test" but cannot be named.
```

It looks like that [TestConfigWebServer](https://github.com/microsoft/playwright/blob/main/packages/playwright-test/types/test.d.ts#L5902) type is not exported.

FYI: I can create PR with fix, but I don't have access to create PR

**Comment by mxschmitt** [comment]
Why do you want to generate a dts file from your tests? I guess you need to exclude the Playwright tests from your Vite config, then its all gonna work.

**Comment by SebastianSedzik** [comment]
I don't want to generate typings from tests. I have a library that exposes a method that takes playwright configuration.

## my library
```ts
export const withConfig: (config: Partial<PlaywrightTestConfig>) => {...}
```

## consumer
```ts
import { withConfig } from '@my-lib`;

withConfig({...})
```

**Comment by mxschmitt** [comment]
but this does not use the TestConfigWebServer, so its all good no?

If you really need this type, then you can also just get it via:

```ts
type TestConfigWebServer = PlaywrightTestConfig['webServer']
```

**Comment by SebastianSedzik** [comment]
It looks like it was a problem with [vite-plugin-dts](https://github.com/qmhc/vite-plugin-dts) itself. After switching to [dts-bundle-generator](https://www.npmjs.com/package/dts-bundle-generator) it works without any errors, so feel free to close the issue ;)
Thanks for your help & time here.
