### ISSUE TITLE
[Playwright Integration with Openfin]

### ISSUE THREAD

**Issue by SabFloki** [microsoft/playwright#20780]
Any source to see how to launch openfin .exe file with Playwright which then takes to chromium shell upon tapping any links on exe file launched.

**Comment by mxschmitt** [comment]
There are no plans to have a dedicated Openfin integration, but it looks like some users already have it working: https://github.com/microsoft/playwright/issues/6936

**Comment by janagar-john** [comment]
Hi @hptabster can you please share the test file js.

**Comment by hptabster** [comment]
> Hi @hptabster can you please share the test file js. It will be great help

See [this code sample](https://github.com/microsoft/playwright/issues/6936#issuecomment-880090664) \

**Comment by janagar-john** [comment]
@hptabster thanks! 
what is LOGIN SELECTOR USER SELECTOR &  and how could i find it ?

**Comment by hptabster** [comment]
The function shown below is a sample how you could implement. Basically launch OpenFin and then connect to the CDP (Chrome Developer Port). Once connected it operates like interactions with Chrome as your now have browser, context, page objects.

Here is the setup used:
```
const IS_WINDOWS = process.platform === "win32";
const IS_OSX = process.platform === "darwin";

const OPENFIN = process.env.TEST_OPENFIN === "true" && IS_WINDOWS;
const OPENFIN_CONFIG_URL =
  process.env.TEST_OPENFIN_CONFIG_URL;
const REMOTE_DEBUGGING_PORT = 12565;
const OPENFIN_DIR = path.join(process.env.LOCALAPPDATA || "", "OpenFin");
const OPENFIN_EXE = path.join(OPENFIN_DIR, "OpenFinRVM.exe");
let OPENFIN_PROC;
```

```
async function launchOpenFin() {
  const openFinArgs = `--config=${OPENFIN_CONFIG_URL} --runtime-arguments="--remote-debugging-port=${REMOTE_DEBUGGING_PORT}"`;
  utils.debug(`launchOpenFin: ${OPENFIN_EXE} ${openFinArgs}`);
  exec(`${OPENFIN_EXE} ${openFinArgs}`, { cwd: OPENFIN_DIR });
  const startTime = Date.now();
  let browser;
  while (Date.now() - startTime < 5000) {
    try {
      browser = await chromium.connectOverCDP({
        endpointURL: `http://localhost:${REMOTE_DEBUGGING_PORT}`,
      });
      break;
    } catch (err) {
      continue;
    }
  }
  utils.debug(
    `launchOpenFin: contexts=${JSON.stringify(await browser.contexts())}`
  );
  const context = await browser.contexts()[0];
  await context.grantPermissions(["clipboard-read"]);
  utils.debug(`launchOpenFin: pages=${JSON.stringify(await context.pages())}`);
  const page = await context.pages()[0];
  return [browser, context, page];
}

```

**Comment by janagar-john** [comment]
Thanks @hptabster

**Comment by IsuruV** [comment]
Hi @hptabster , thank you for posting your workaround for getting Playwright running with OpenFin. Following your code example, I was able to get it up and running in my work repo. While it works fine on a local machine, I'm encountering issues when trying to run the code in CI/CD pipelines—specifically one set up for GitLab where I'm using a Windows runner to execute these Playwright test cases. It seems the pipeline is not able to properly launch the OpenFin instances, which is crucial for the connection over the CDP API that Playwright offers. Have you by any chance been successful in getting it to run in any CI/CD pipeline setup?

**Comment by hptabster** [comment]
@IsuruV I did not launch OpenFin in a Windows virtual host configured for a CI/CD, but it should be no different than any other virtual host. In other words, this is not a Playwright issue, but a configuration of your virtual host to support OpenFin.

**Comment by IsuruV** [comment]
> @IsuruV I did not launch OpenFin in a Windows virtual host configured for a CI/CD, but it should be no different than any other virtual host. In other words, this is not a Playwright issue, but a configuration of your virtual host to support OpenFin.

Yea, it turned out I just needed proper user permissioning set for the gitlab runner.. 
follow up question, have you gotten openfin+playwright to run in headless mode successfully?

**Comment by hptabster** [comment]
I never tried the headless scenario since OpenFin is launched as a separate process and would need to investigate what option supports headless (if any).

**Comment by janagar-john** [comment]
Hi @hptabster how to switch new window using openfin playwright?

**Comment by janagar-john** [comment]
> The function shown below is a sample how you could implement. Basically launch OpenFin and then connect to the CDP (Chrome Developer Port). Once connected it operates like interactions with Chrome as your now have browser, context, page objects.
> 
> Here is the setup used:
> 
> ```
> const IS_WINDOWS = process.platform === "win32";
> const IS_OSX = process.platform === "darwin";
> 
> const OPENFIN = process.env.TEST_OPENFIN === "true" && IS_WINDOWS;
> const OPENFIN_CONFIG_URL =
>   process.env.TEST_OPENFIN_CONFIG_URL;
> const REMOTE_DEBUGGING_PORT = 12565;
> const OPENFIN_DIR = path.join(process.env.LOCALAPPDATA || "", "OpenFin");
> const OPENFIN_EXE = path.join(OPENFIN_DIR, "OpenFinRVM.exe");
> let OPENFIN_PROC;
> ```
> 
> ```
> async function launchOpenFin() {
>   const openFinArgs = `--config=${OPENFIN_CONFIG_URL} --runtime-arguments="--remote-debugging-port=${REMOTE_DEBUGGING_PORT}"`;
>   utils.debug(`launchOpenFin: ${OPENFIN_EXE} ${openFinArgs}`);
>   exec(`${OPENFIN_EXE} ${openFinArgs}`, { cwd: OPENFIN_DIR });
>   const startTime = Date.now();
>   let browser;
>   while (Date.now() - startTime < 5000) {
>     try {
>       browser = await chromium.connectOverCDP({
>         endpointURL: `http://localhost:${REMOTE_DEBUGGING_PORT}`,
>       });
>       break;
>     } catch (err) {
>       continue;
>     }
>   }
>   utils.debug(
>     `launchOpenFin: contexts=${JSON.stringify(await browser.contexts())}`
>   );
>   const context = await browser.contexts()[0];
>   await context.grantPermissions(["clipboard-read"]);
>   utils.debug(`launchOpenFin: pages=${JSON.stringify(await context.pages())}`);
>   const page = await context.pages()[0];
>   return [browser, context, page];
> }
> ```

It's hard to create files/functions can u please send or full code with file names, it will be helpful. thanks
