### ISSUE TITLE
Is there a way to set slowMo flag without having to update playwright config file?

### ISSUE THREAD

**Issue by el-davo** [microsoft/playwright#20786]
Hi, we recently moved to playwright from cypress and this is a great plugin.

My question is around slowing down the tests to see what is happening in the browser. From looking at playwright docs it looks like there is a way to set a slowMo flag, however this needs to be set manually in the config file.

I was wondering is there a way to slow down the tests using this plugin? or perhaps this could be a future feature for this plugin. something like in the image below
![image](https://user-images.githubusercontent.com/11195158/217879933-3fdbf7c7-9122-4a9a-9537-a6c9eb0a7f02.png)
 

Would be interested in getting your thoughts on this.

**Comment by mxschmitt** [comment]
Whats the reason you want to increase the test execution duration by hand?

**Comment by el-davo** [comment]
Its explained quite well on this issue https://github.com/microsoft/playwright/issues/5900. I guess for us, we want to make it slower so we can debug tests, at the moment they are lightning fast and its hard to see what is happening, a slowmo option might help with this.

**Comment by mxschmitt** [comment]
We can re-formulate it to a feature request if you want, but as of today there are no ways to make it how you want to have it.

**Comment by aslushnikov** [comment]
I'll merge this to #5900 then.
