### ISSUE TITLE
[BUG] page.goto initial request does not seem to set referer header (nextjs, msw)

### ISSUE THREAD

**Issue by DarthHater** [microsoft/playwright#20798]
**Context:**
- Playwright Version: 1.30
- Operating System: OS X
- Node.js version: 14.19.1
- Browser: Chromium
- Extra: NextJS in combination with msw

```
npx envinfo --preset playwright --markdown                         Thu Feb  9 22:00:03 2023
npx: installed 1 in 1.713s

## System:
 - OS: macOS 13.1
 - Memory: 16.62 GB / 64.00 GB
## Binaries:
 - Node: 14.19.1 - ~/.nvm/versions/node/v14.19.1/bin/node
 - Yarn: 1.22.18 - ~/.nvm/versions/node/v14.19.1/bin/yarn
 - npm: 6.14.16 - ~/.nvm/versions/node/v14.19.1/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## npmPackages:
 - playwright: ^1.30.0 => 1.30.0 
```

**Code Snippet**

```typescript
import { test, expect } from '../next-referer-test-fixture';

test.describe('index page', () => {
  test('modal appears if referrer is search.maven.org', async ({
    browser,
    port,
  }) => {
    const context = await browser.newContext({
      extraHTTPHeaders: { referer: 'https://search.maven.org' },
    });
    const page = await context.newPage();

    page.setExtraHTTPHeaders({ referer: 'https://search.maven.org' });

    await page.goto(new URL('/', `http://localhost:${port}`).href);

    await expect(page.locator('data-test=modal')).toBeVisible();

    await context.close();
    await browser.close();
  });
});
```

**Describe the bug**

When I attempt to debug this test, I see the following, and I'm liberally sharing screenshots because this is a straight up mystery to me:

Running the test individually with the inspector: `yarn run playwright test e2e/specs/referer.spec.ts --debug`

<img width="1461" alt="Screenshot 2023-02-09 at 1 05 40 PM" src="https://user-images.githubusercontent.com/5544326/217949912-834dcd07-6b9d-47cf-89d4-358e2fda9ef4.png">

The initial request no matter what I do, does not have the referer header set. I've tried every which way to set it, and even used a few goofy things above as you can see, and for the life of me I cannot figure out what's going on here.

Every request after that first request, no big deal, referer is set correctly. However, this is not what I need, in order to properly test a function handling a referer header, I need to have it set on the original request that nextjs handles server side.

I can likely share more detail if needed. This is straight up making my head go 🤯 .

We really dig Playwright, so thanks for it! Bug requests are always negative, may as well add some positivity for whoever is reading this.

**Comment by mxschmitt** [comment]
I see that you are not awaiting setExtraHTTPHeaders, could you try awaiting it? In general this should work, but not awaiting it sounds already pretty suspicious.

**Comment by DarthHater** [comment]
@mxschmitt, gave that a shot, same result. No header set on the initial request, just on the ones past it.

**Comment by DarthHater** [comment]
What is blowing my mind is I set it on the context, etc..., and I've tried setting it using on `goto`, with no luck there either.

**Comment by aslushnikov** [comment]
@DarthHater so the following works for me just fine:

```ts
// a.spec.ts
import { test, expect } from '@playwright/test';

test('should apply referrer', async ({ page }) => {
  await page.goto('https://example.com', { referer: 'https://google.com' });
});
```

running this test with `--debug`:

```
npx playwright test --debug
```

Opening DevTools, and stepping over the "page.goto" command:

<img width="1394" alt="image" src="https://user-images.githubusercontent.com/746130/219062502-053fcff0-b74e-4ce6-8359-2f65317aa469.png">

Try running this snippet locally. Does it work for you?

**Comment by aslushnikov** [comment]
@DarthHater all in all, neither me nor Max managed to repro this. With this, I'll have to close the issue.

But if you have a better repro, or if you think we still can be somehow useful to you, then please do not hesitate to file another one!
