### ISSUE TITLE
[REGRESSION]: Performance issues on WebKit 16.4

### ISSUE THREAD

**Issue by sizmos** [microsoft/playwright#20808]
Context:

- GOOD Playwright Version: v1.27.1
- BAD Playwright Version: v1.28+
- Operating System: Linux
- Extra: WebKit only

Opening a new issue related to: https://github.com/microsoft/playwright/issues/19108

I have managed to partially recreate my test case removing and sensitive data, note the test is roughly half the length of the full test previously run:
1.27.1:
- chrome: 18s
- iphone: 33s

1.30.0
- chrome: 17.1s
- iphone: 43s

https://github.com/sizmos/playwright-test/pull/1

**Comment by aslushnikov** [comment]
@sizmos this is quite a long repro. Any chance you can slim it down further?

**Comment by sizmos** [comment]
In what way? I kept the test to run for a certain length to be able to gauge if there were improvements in speed to any potential fixes. If I cut it down to 10 seconds, the delta may only be 1-2 seconds which would be difficult to determine a fix.

**Comment by aslushnikov** [comment]
I cloned your repro twice and installed Playwright 1.27 in one of the folders and Playwright 1.30 in the other one.

However, I didn't notice any difference running them:

<img width="961" alt="image" src="https://user-images.githubusercontent.com/746130/219270392-b3ca20a1-d18e-494f-bc30-36fd409e6016.png">

In subsequent runs, Playwright 1.27 occasionally executed the test in 26 seconds, so I assume the repro heavily depends on the network I/O. If there's a regression, then it's masked by the network.

Any chance you can repro this with a locally-hosted HTML?

**Comment by sizmos** [comment]
Sorry I should have included my comments from the previous bug, this is when running using the public docker images (focal)

**Comment by aslushnikov** [comment]
Hmm, I still can't repro this reliably. I had 1.30 timeout once for me while trying to click some button, but that's about it. It reliably runs same time as 1.27:

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/746130/219278291-0dac00c3-3312-4453-a81c-615cca492e17.png">


Meanwhile, can you please try the `@playwright/test@beta`? 

```
npm i @playwright/test@beta
```

Also, do you run x86_64 docker or aarch64?

**Comment by sizmos** [comment]
I can try the beta.
x86_64

**Comment by aslushnikov** [comment]
I ran [these](https://github.com/microsoft/playwright/issues/20808#issuecomment-1432553657) on x86_64 as well. 

> I can try the beta.

Thanks. Please let me know how it went.

If beta doesn't work for you as well, maybe you'll be able to narrow-down the regression to a specific Playwright API call that became slow? Maybe this way you'll be able to craft a different repro that I'll be able to reproduce locally.

**Comment by aslushnikov** [comment]
@sizmos any updates on this?

**Comment by sizmos** [comment]
Just tested with `1.31.0-beta-1676685153000` running the whole test rather than the subset in the above repo.

Seems to be an improvement even over 1.27.1!
- 1.27.1: 1 min 30 sec
- 1.30.0: 2 min 12 sec
- 1.31.0-beta: 1min 18 sec

What is the rough release date for 1.31.1?

**Comment by aslushnikov** [comment]
Great, closing this then! Should be today/tomorrow.
