### ISSUE TITLE
[Question] page.screenshot: Error: eval is disabled

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#20807]
My code to match screenshot used to work for me but I am seeing this error now `page.screenshot: Error: eval is disabled`

```
    expect(await page.screenshot({ fullPage: true })).toMatchSnapshot(screenshotName, { threshold: 0.2 });
```

Can someone please help?

**Comment by gauravgandhi1315** [comment]
eval was always disabled in my application, but it used to work for me. Is screenshot using `eval` under the hood?

**Comment by mxschmitt** [comment]
We recently fixed an issue related to that. Could you try our beta release? https://playwright.dev/docs/canary-releases

**Comment by gauravgandhi1315** [comment]
@mxschmitt It works fine with `npm install -D @playwright/test@next`. Looks like the issue with the latest version. When do you think new version is coming out?

**Comment by mxschmitt** [comment]
in around 1-2 weeks. Closing then, thanks!
