### ISSUE TITLE
[BUG] Intercepting response body from oopif throws error 

### ISSUE THREAD

**Issue by viperlucror** [microsoft/playwright#20809]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Node.js version: 18.4.0
- Browser: Chromium
- Extra: n/a

**Code Snippet**
```javascript
import { test } from '@playwright/test';

test('route can access response body of oopif requests', async ({ page }) => {
  await page.on('response', async response => console.log(await response.body()));
  await page.goto(server.PREFIX + '/dynamic-oopif.html');
});
```
In this case dynamic-oopif.html is the standard playwright test file. This also reproduces for a simple static page with an oopif like:
`<html><body><iframe src="https://example.com/" width="400" height="400"></body></html>`

**Describe the bug**

Intercepting the response body of the out-of-process iframe results in this error:
`response.body: Protocol error (Network.getResponseBody): No resource with given identifier found`

For some reason this seems to work in _headless_, but running this test headed throws.

I've seen a few similar issues that mention there's sometimes a race condition where the Network stack will dispose of response body on a redirect, but there is no redirect here. Am I missing something obvious?

Thanks!

**Comment by mxschmitt** [comment]
I can reproduce it with the following test:

```ts
// tests/library/chromium/oopif.spec.ts
it('route can access response body of oopif requests', async ({ page, server }) => {
  page.on('response', async response => console.log(await response.text()));
  await page.goto(server.PREFIX + '/dynamic-oopif.html');
});
```
