### ISSUE TITLE
[Question] Large nesting of locators

### ISSUE THREAD

**Issue by BogachevaN** [microsoft/playwright#20814]
Hi! I need to get value from drop down list. I have an accurate locator:
![image](https://user-images.githubusercontent.com/22913482/218076620-99096694-3785-4c70-bd98-bfbedda9fb42.png)
But the playwright does not find him:
`let elementWithText = this.page.locator('div[data-testid="form-ticketCreateForm_field-inboxId"]>label>div>div:nth-child(1)>div:nth-child(1)>div>div')`
Finds only part of:
`let elementWithText = this.page.locator('div[data-testid="form-ticketCreateForm_field-inboxId"]>label>div>div:nth-child(1)')`
But it is impossible to get text from such an element.

Is this a limitation or a bug?

I have also tried using this:
`this.inboxList =  page.getByTestId('form-ticketCreateForm_field-inboxId')`
and
`let elementWithText = this.inboxList.locator('label>div>div:nth-child(1)>div:nth-child(1)>div>div')`
It isn't work too.

**Comment by mxschmitt** [comment]
Can you provide a repro for us? then we can run it locally and see what happens and what is expected, otherwise we cannot act on it, thanks!

**Comment by aslushnikov** [comment]
The discussion has stalled here - so closing this. If you do think we can be helpful, please do not hesitate to file a new issue (but please, make sure to follow issue template and provide us with a repro!)
