### ISSUE TITLE
Test cases are failing when I run in headless mode

### ISSUE THREAD

**Issue by shalini-raghu** [microsoft/playwright#20817]
Hi,

When I run testcases in debug mode, all testcases are passing. But if I run the same testcases in regular mode or headless mode testcases are failing. and also each time getting error in different lines of the testcases.

**Comment by mxschmitt** [comment]
This sounds like the tests you created are flaky. Without seeing the tests its hard to tell whats going wrong or if you followed the [best-practises](https://playwright.dev/docs/best-practices). Could you share a test with us and the error you get?

**Comment by shalini-raghu** [comment]
Hi,

The example test case is:

import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await page.goto('https://3dtrasarcip-dev.ecolab.com/en-US/');
  await page.getByPlaceholder('Please enter your email address.').fill('fnb123456789@outlook.com');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByPlaceholder('Password').fill('3col@bRocks!');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.getByRole('button', { name: 'Yes' }).click();
  await page.hover("//i[@class='ci-icon_Ecolab3D_Settings']");
  await page.getByRole('link', { name: 'CIP System' }).click();
  await page.getByRole('link', { name: 'Materials' }).click();
});

test('Add "Water" material', async({ page }) =>{
  await page.click("//kendo-grid-toolbar/button");
  await page.getByRole('button', { name: 'Select' }).first().click();
  await page.getByRole('option', { name: 'Water' }).click();
  await page.getByRole('button', { name: 'Select' }).nth(1).click();
  await page.getByRole('option', { name: 'COW Water' }).click();
  const matreialName = createGuid();
  await page.getByRole('textbox').first().fill(matreialName);
  await page.locator('//tr[1]/td[7]/kendo-numerictextbox/input').fill('5');
  await page.locator("//tr[1]/td[8]/button[3]").click();
  await page.locator('app-configuration-mode-selector i').nth(1).click();
  await page.click("//kendo-listview/div/div[2]");
  await page.getByRole('button', { name: 'OK' }).click();
  await expect(page.getByRole('gridcell', {name: matreialName})).toContainText(matreialName)
})

function createGuid() {
    return (''+[1e7]+-1e3+-4e3+-8e3+-1e11).replace(/[018]/g, function(c) {
        const r = Math.random() * 16 | 0, v = c === 'x' ? r : ( r & 0x3 | 0x8 );
        return v.toString(16);
});
}

**Comment by aslushnikov** [comment]
The discussion has stalled here - so closing this. If you do think we can be helpful, please do not hesitate to file a new issue (but please, make sure to follow issue template and provide us with a repro!)
