### ISSUE TITLE
[BUG] route.fetch() produces different headers than standard navigation

### ISSUE THREAD

**Issue by viperlucror** [microsoft/playwright#20810]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Linux
- Node.js version: 18.4.0
- Browser: Chromium
- Extra: n/a

**Code Snippet**
```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();

  const page1 = await context.newPage();
  // Intercept all requests and pass them along without modifying
  await page1.route('**/*', async route => route.fulfill({ response: await route.fetch() }));
  await page1.goto('https://httpbin.org/headers');
  const page1headers = await page1.locator('body').innerText();
  console.log(page1headers);

  const page2 = await context.newPage();
  // Intercept all requests but let them fall back to normal handling
  await page2.route('**/*', async route => route.continue());
  await page2.goto('https://httpbin.org/headers');
  const page2headers = await page2.locator('body').innerText();
  console.log(page2headers);
})();
```

**Describe the bug**
The two versions above produce different sets of headers, which was unexpected.

I'd interpreted the doc on [modifying responses](https://playwright.dev/docs/network#modify-responses) as implying that route.fetch() will get the get the original response via the normal browser stack, but it looks like a fairly different set of headers and such under the hood. While most use-cases aren't picky about what headers are included, it wasn't clear to me if this was expected behavior and/or if there were other important nuances/differences about route.fetch() behavior.

Thanks!

**Comment by mxschmitt** [comment]
Thats a diff for further reference:

<img width="605" alt="image" src="https://user-images.githubusercontent.com/17984549/218090153-fae0b5ef-1dce-40de-88db-d4a382764535.png">

**Comment by eliassorensen** [comment]
I have had this one open in Chromium for over a year. Could it be related to this bug?

[https://bugs.chromium.org/p/chromium/issues/detail?id=1292450](https://bugs.chromium.org/p/chromium/issues/detail?id=1292450)

**Comment by anderslangballe** [comment]
Is there a workaround to this bug? Does not seem to affect WebKit.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by FlareZ123** [comment]
this is still an issue and will affect caching, all the info is still there for a minimal reprod and this should be fixed
