### ISSUE TITLE
Choosing option from a dropdown with dynamic values 

### ISSUE THREAD

**Issue by shalini-raghu** [microsoft/playwright#20819]
Hi,

We are using kendo-dropdown-list in our website for dropdown and it contains dynamic value in it. As suggested in previous issue I'm using codegen to choose option from kendo-dropdown-list, the code to choose option in codegen is:

    await page.getByRole('combobox', { name: 'Severity' }).getByRole('button', { name: 'Select' }).click();
    await page.getByRole('option', { name: 'Warning' }).click();

Please suggest me how to make name value as dynamic value or suggest other way to choose option from dropdown.

Regards,
Shalini

**Comment by aslushnikov** [comment]
The discussion has stalled here - so closing this. If you do think we can be helpful, please do not hesitate to file a new issue (but please, make sure to follow issue template and provide us with a repro!)
