### ISSUE TITLE
[BUG] waitForSelector and 'waitFor' property incorrect typescript matching

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2081]
**Context:**
- Playwright Version: 0.16.0

**Code Snippet**

```javascript
await page.waitForSelector('text="some text"', {
  waitFor: 'attached',
});
```

**Describe the bug**

The above only gives code completion for `attached` and `visible` (using VS Code). Going to the types.d.ts file it matches `waitForSelector(selector: string, options?: WaitForSelectorOptionsNotHidden): Promise<HTMLOrSVGElementHandle>;` where `WaitForSelectorOptionsNotHidden` looks like this:

```typescript

type WaitForSelectorOptionsNotHidden = PageWaitForSelectorOptions & {
  waitFor: 'visible'|'attached';
}
```

It should have matched `waitForSelector(selector: string, options: PageWaitForSelectorOptions): Promise<null|HTMLOrSVGElementHandle>;` to get the proper options from `PageWaitForSelectorOptions`.

**Comment by thernstig** [comment]
To note now is that `waitFor` has been renamed to `state` on master.

**Comment by JoelEinbinder** [comment]
So this is not actually a bug with our types, but a quirk of the vscode autocomplete. There are multiple signatures, which you can toggle between with the small up/down arrows in the suggest box. However vscode doesn't merge options together when giving autocomplete. I filed a bug in typescript against it

https://github.com/microsoft/TypeScript/issues/38569
