### ISSUE TITLE
[Question]why not eat dog food?

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2082]
playwright's vision is empowering the e2e and unit test communication .
why not eat dog food?
refactor the test infrastructure into basing jest-playwright!

**Comment by pavelfeldman** [comment]
`jest-playwright` is one of the ways Playwright can be used, proposed by the third party. See the [test runners](https://github.com/microsoft/playwright/blob/master/docs/test-runners.md) doc for more details and options.
