### ISSUE TITLE
[BUG] For some reason when trying to load certain pages, it will load for eternity. 

### ISSUE THREAD

**Issue by gutenacht0221** [microsoft/playwright#20835]
**Context:**
- Playwright Version: Version 1.30.0
- Operating System: Windows
- Node.js version: v16.17.1
- Browser: All

```javascript
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: true });
  const context = await browser.newContext();
  const page = await context.newPage();

  await page.goto('https://www.microsoft.com/account/');
  console.log(`Page title: ${await page.title()}`);

  await browser.close();
})();
```

**Describe the bug**

it just never loads and i'm wondering if there is a fix or if this is intended or something

**Comment by aslushnikov** [comment]
@gutenacht0221 it looks like the website has a bot evasion technology that shields it from automation. This falls outside of the scope of the project.
