### ISSUE TITLE
[BUG] Playwright install incorrectly reports kde neon (based on 22.04.1) as unsupported OS

### ISSUE THREAD

**Issue by sdwvit** [microsoft/playwright#20838]
**Context:**
- Playwright Version: latest as of today
- Operating System: Linux; 22.04.1 ubuntu lts based KDE neon 5.26 x86_64 | Kernel: 6.0.0
- Node.js version: 16.14.2
- Browser: all
- Extra: had to do https://github.com/microsoft/playwright/issues/11122#issuecomment-1426622416 to install playwright, but this issue arises earlier

**Code Snippet**

```bash
npm init playwright@latest
```

**Describe the bug**

The command above reports 22.04.1 as unsupported OS, however playwright docs say [LTS 22.04 is supported](https://playwright.dev/docs/troubleshooting#linux)

![Screenshot_20230211_001214](https://user-images.githubusercontent.com/8777372/218242680-28e251f6-1d1b-474f-9599-d1f38e7e16de.png)

**Comment by aslushnikov** [comment]
@sdwvit I just tried installing on Ubuntu 22.04.1 with no problem:

```
$ docker run --rm -it ubuntu:22.04 /bin/bash
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
$ apt-get install -y curl
$ curl -sL https://deb.nodesource.com/setup_16.x | bash
$ apt-get install nodejs
$ cd && npm init playwright@latest
```

what distro exactly are you running? Can you can your `/etc/os-release`?

**Comment by sdwvit** [comment]
```
sdwvit@Victors-PC:~$ cat /etc/os-release
PRETTY_NAME="KDE neon 5.26"
NAME="KDE neon"
VERSION_ID="22.04"
VERSION="5.26"
VERSION_CODENAME=jammy
ID=neon
ID_LIKE="ubuntu debian"
HOME_URL="https://neon.kde.org/"
SUPPORT_URL="https://neon.kde.org/"
BUG_REPORT_URL="https://bugs.kde.org/"
PRIVACY_POLICY_URL="https://kde.org/privacypolicy/"
UBUNTU_CODENAME=jammy
```

**Comment by sdwvit** [comment]
Thanks @aslushnikov !
