### ISSUE TITLE
[BUG] Full Page Screenshots flaky, content cut off or shifted

### ISSUE THREAD

**Issue by thraizz** [microsoft/playwright#20859]
**Context:**
- Playwright Version: [what Playwright version do you use?]
- Operating System: Linux, official playwright docker image `mcr.microsoft.com/playwright:v1.30.0-focal`
- Node.js version: v16.19.0
- Browser: Chromium
- Extra: Runs in our CI environment

**Code Snippet**

I tried to recreate this the best I could by porting an example to codesandbox.io and test it with this:
```javascript
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  // Go to sandbox of page
  await page.goto("https://125nzp.csb.app/");
  // Scroll to top to counter element focus scrolling
  await page.evaluate(() => window.scrollTo(0, 0));

  await page.screenshot({
    path: "number-porting.png",
    fullPage: true,
    config: { animations: "disabled" },
  });

  await browser.close();
})();
```

**Describe the bug**

The `fullPage` screenshots of our application differ from time to time, seemingly randomly.

An example is this:
Actual:
![f84e78fec3e194e63271b065cc8e66485f1bb42f](https://user-images.githubusercontent.com/30572790/218450870-4f9cafe6-2061-43a0-879d-1bed601c142b.png)
Expected:
![277c34a06dd5fe4191e87df499b3b11a59217a06](https://user-images.githubusercontent.com/30572790/218450884-9fe7f204-6a43-4200-bdbf-40793c77f8f7.png)

Sometimes something is cut off, other times the content is shifted. We mitigated a lot of the content shift differences when having fixed positioning and dynamic content by scrolling to top before every screenshot, but this seems to cause the cut-offs. We restart the pipeline then, and the screenshots match again. But this is not the way e2e testing/visual comparison was intended, I hope 😸

**Comment by thraizz** [comment]
Yes, this is how we compare the screenshots in our tests, i just had to write it this way for the minified version to allow triaging :)

**Comment by thraizz** [comment]
This is how it looks in the reports inside our pipeline:
![image](https://user-images.githubusercontent.com/30572790/219342835-f06cc8ad-aff1-4c7a-b52e-45248756f84c.png)

Could it be that it related to the test being shutdown mid-screenshot? If we add up previous assertions of this test, we can see that the time when the partial screenshot appears is dangerously close to our 30s timeout for a single test:
![image](https://user-images.githubusercontent.com/30572790/219343821-75ee6512-2c15-4317-af97-dd4de8551f00.png)

**Comment by aslushnikov** [comment]
>  If we add up previous assertions of this test, we can see that the time when the partial screenshot appears is dangerously close to our 30s timeout for a single test:

@thraizz can you try setting larger timeout and see if it helps?

**Comment by aslushnikov** [comment]
@thraizz Overall, this looks more like a Chromium bug: it's rendering pipeline is pretty complicated, and full-page screenshots exercise rare code paths. If you have a good repro, it might be worth it filing upstream to Chromium maintainers at https://crbug.com/new

As a workaround, the best thing we can recommend here is to set `retries: 2` for these tests that bother you. 

Sorry we can't be more helpful!

**Comment by codykaup** [comment]
Hey @thraizz did you end up writing up a Chromium bug report for this? We ran into this issue but it was mostly surrounding fonts. During the full page screenshot, it appeared Chromium was reloading the page _and_ all the network assets. Unfortunately, there was no guarantee the screenshot would be taken after all of that so our results would flip back and forth randomly.

@aslushnikov Is there a way to add a delay between the viewport resize and the screenshot? I want to say Playwright leans on Chromium to do all that so perhaps there's not. I figured it's worth asking!

**Comment by pkra** [comment]
@codykaup there used to be https://bugs.chromium.org/p/chromium/issues/detail?id=760596 which was closed as wontFix/cannotReproduce. But I still run into the problem with very large screenshots; it seems to vary from machine to machine, so I'm guessing a race condition somewhere.

**Comment by yugawara** [comment]
Is Firefox better for screenshot testing?

**Comment by TopCoder02** [comment]
@thraizz I had a similar issue, and it was because long content product a vertical scroll bar, so I added "overflow:hidden" to the body tag of the page I was going to screenshot and the issue went away.
