### ISSUE TITLE
[Question] How to access/catch/intercept and fulfill requests which my extension send

### ISSUE THREAD

**Issue by AndrewEgorov** [microsoft/playwright#20858]
Hello,

I have an extension which is built on manifest v3. how to access to all network requests which it sends. It has no background page, available only service worker, so I can access to it using following code:

```
let [background] = globalContext.serviceWorkers();
if (!background)
  background = await globalContext.waitForEvent("serviceworker");
```
But how to access network requests from here?

Scenario:
* My extension sent some requests and according to responses specify some changes in UI of the page. I want to mock these requests/responses and coordinate what I want to see .

Thanks.

**Comment by aslushnikov** [comment]
@AndrewEgorov have you had a chance to read about experimental service worker network events? These might be what you're interested in: https://playwright.dev/docs/service-workers-experimental

**Comment by AndrewEgorov** [comment]
Thanks @aslushnikov for your help. Yes, this works for me. Hope this feature become not experimental very soon.

Following code works for me after enabling it:

`await globalContext.route("**/some/apicall", (route) => {
        if (route.request().serviceWorker()){
            route.fulfill({
                body: JSON.stringify(response)
            })
        }
    })`

Using it I was able to mock some requests which my extension sent.
