### ISSUE TITLE
.waitForNavigation() deprecation

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#20853]
Hello,

does `.waitForNavigation()` deprecation means that at some point in the future this method will be deleted?

I was planning replacing this method with `.waitForURL()` but  it doesn't work if navigation happens to the same url. For example:
- Open foo.url/
- Do something that triggers a long navigation to the same url
- `page.waitForURL(/\/$/)`
- Navigation wait does not happen

![SCR-20230213-ekk](https://user-images.githubusercontent.com/17873445/218408279-ad4d0361-f34e-496f-9ca8-efe0b5852306.png)

**Comment by aslushnikov** [comment]
> does .waitForNavigation() deprecation means that at some point in the future this method will be deleted?

@MindaugasMateika It will never be removed. Its use is discouraged, because it's hard to make it work reliably. It only works if and only if you know for sure what the page is doing. 

Hope it makes it clearer!

**Comment by jorisre** [comment]
> I was planning replacing this method with .waitForURL() but it doesn't work if navigation happens to the same url

@aslushnikov What's about ⬆️ ? Thank you :)

**Comment by AndyGleed** [comment]
I am still concerned about this.  @aslushnikov said above that it will never be removed, but on the [discord server](https://discord.com/channels/807756831384403968/1070990886986584124/1075904356517421167), @mxschmitt said it maybe could be removed in pw v2.

So which is it please?  Thanks.

**Comment by mxschmitt** [comment]
Playwright version 2 is not gonna happen soon, thats why Andrey wrote, its never getting removed. If we remove it, we'll add either another method where you can migrate to or you don't need it anymore.

We'll **definitely not** remove something which is essential when covering this specific e2e testing use-case.

**Comment by AndyGleed** [comment]
@mxschmitt Good news, thank you for the reply :)

**Comment by regseb** [comment]
To replace the deprecated [`Page.waitForNavigation()`](https://playwright.dev/docs/api/class-page#page-wait-for-navigation) method, you can add the `waitNavigation` option to the `Locator.click()` method (and all methods that have the [`noWaitAfter`](https://playwright.dev/search?q=noWaitAfter) option):

- `waitNavigation` [boolean](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) (optional)

  Forces wait for the main frame navigation.
Actions that initiate navigations are waiting for these navigations to happen and for pages to start loading. You can opt out of waiting via setting this flag. You would only need this option in the exceptional cases such as navigating to inaccessible pages. Defaults to false.
Waits for the main frame navigation and returns the main resource response. In case of multiple redirects, the navigation will resolve with the response of the last redirect. In case of navigation to a different anchor or navigation due to History API usage, the navigation will resolve with null.

**Comment by nekolab** [comment]
@regseb

>To replace the deprecated [Page.waitForNavigation()](https://playwright.dev/docs/api/class-page#page-wait-for-navigation) method, you can add the waitNavigation option to the Locator.click() method (and all methods that have the [noWaitAfter](https://playwright.dev/search?q=noWaitAfter) option):

Any reference? I cannot find any related change neither in recent commits, nor the type definition for the `click` API

https://github.com/microsoft/playwright/blob/f15ea35bfb100fb05a58c50b188e0a841adf0274/packages/protocol/src/channels.ts#L3154-L3164

**Comment by regseb** [comment]
@nekolab 

I misspoke. I meant to say: the Playwright team could develop a new `waitNavigation` option.

**Comment by brillout** [comment]
>  Its use is discouraged, because it's hard to make it work reliably. It only works if and only if you know for sure what the page is doing.

Can you elaborate? Our `page.waitForNavigation()` promises sometime timeout, even though we do follow the practice of calling `page.waitForNavigation()` before the action:

```js
const navPromise = page.waitForNavigation()
await someActionTriggeringPageReload()
await navPromise // Sometimes never resolves and timeouts instead
```

**Comment by Mike-Ro** [comment]
I need to click and wait for the page to load.

Earlier, I used the wait waitForNavigation, but the IDE reports that this method has been deprecated:
```js
await page.click('button');
await page.waitForNavigation({waitUntil: 'networkidle'});
```
I found a solution that works for me, but the question is - is this the correct solution within Playwright?
```js
await Promise.all([
  page.click('button'),
  page.waitForLoadState('networkidle')
]);
```

**Comment by brillout** [comment]
Workaround:

```typescript
/** Wait for a full page navigation/reload (i.e. complete DOM de-/reconstruction)
 *
 * Reliable alternative to Playwright's:
 *  - page.waitForURL() which doesn't work for page reloads (https://github.com/microsoft/playwright/issues/20853)
 *  - page.waitForNavigation() which is unreliable (https://github.com/microsoft/playwright/issues/20853#issuecomment-1698770812)
 */
async function waitForNavigation(): Promise<() => Promise<void>> {
  // We need to await page.evaluate() before the page navigation is triggered, otherwise Playwright throws:
  // ```bash
  // proxy.evaluate: Execution context was destroyed, most likely because of a navigation
  // ```
  await page.evaluate(() => (window._stamp = true))
  return async () => {
    await page.waitForFunction(() => window._stamp === undefined)
  }
}
declare global {
  var _stamp: undefined | true
}
```

Usage:

```ts
const navPromise = await waitForNavigation()
// Trigger page navigation
await navPromise()
// Page navigation is done
```

**Comment by AndyGleed** [comment]
@brillout I just tried your workaround but couldn't get it to work.  Maybe I am implementing it incorrectly...

I added a new .ts file to my project and modified the function to pass in the page:
`
import { Page } from '@playwright/test';

export async function waitForNavigation(page: Page): Promise<() => Promise<void>> {
    await page.evaluate(() => (window._stamp = true));
    return async () => {
        await page.waitForFunction(() => window._stamp === undefined);
    };
}

declare global {
    var _stamp: undefined | true;
}
`

Then in a page object class where I click a button which causes the navigatin/reload:
`
const nav = await waitForNavigation(this.page);
await this.locators.bar.getByRole('link', { name: 'Add Document' }).click();
await nav();
`

When I run the test, it fails with a timeout error on the following line:
`
await page.waitForFunction(() => window._stamp === undefined);
`
Any thoughts very much appreciated.

**Comment by nightpool** [comment]
I agree, if the method doesn't have a clear replacement yet and there's no plan to remove it then it shouldn't be marked as deprecated.

**Comment by longfellowone** [comment]
Also using the function, looking for an alternative in Go
