### ISSUE TITLE
[BUG] how to bypass cloudflare recaptcha using playwright ?

### ISSUE THREAD

**Issue by saikrishnaoggu** [microsoft/playwright#20852]

**Comment by aslushnikov** [comment]
bot evasion techniques fall outside of the scope of the project.

**Comment by saikrishnaoggu** [comment]
Hi @aslushnikov 

In our application there is cloudfare recaptcha for login. So I am unable to login to application in order to execute the tests, it is a blocker for me. Could you please provide steps to solve this issue?
