### ISSUE TITLE
[Question] Value of a specific table cell

### ISSUE THREAD

**Issue by mindeeg** [microsoft/playwright#20869]
I have a table with several rows and 4 columns. I need the value of last td in a row. The value will change, so I need to create a variable for the value. I get as far as locating the row, but getting the value of the last cell is proving to be difficult.

**Comment by aslushnikov** [comment]
@mindeeg it depends on your table structure. Have you tried using codegen to pick a good selector?

We demo'ed it a few times in our release videos:
- https://www.youtube.com/watch?v=tVSq-0n-TY4&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=3&t=287s
- https://www.youtube.com/watch?v=z0EOFvlf14U&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=11&t=79s

You can also check out docs for codegen: https://playwright.dev/docs/next/codegen-intro#running-codegen

**Comment by aslushnikov** [comment]
closing this then since there's no action item for Playwright team!
