### ISSUE TITLE
[BUG] Firefox on Appveyor seems flaky

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2086]
Most of the times the CI fails, would be good to know why and better to have it fixed.

Recent builds: https://ci.appveyor.com/project/aslushnikov/playwright/history

- [ ] [1)](https://ci.appveyor.com/project/aslushnikov/playwright/builds/32616285#L142)
```
 [TIMEOUT 30000ms] Firefox Page.Events.Crash should emit crash event when page crashes (page.spec.js:117:3)
```
- [ ] [2)](https://ci.appveyor.com/project/aslushnikov/playwright/builds/32616285#L144)
```
[TIMEOUT 30000ms] Firefox Page.Events.Crash should throw on any action after page crashes (page.spec.js:122:3)
```

- [ ] [3)](https://ci.appveyor.com/project/aslushnikov/playwright/builds/32615373#L158)
```
 [FAIL] Firefox ElementHandle.screenshot should take element screenshot when default viewport is null and restore back (screenshot.spec.js:450:3)
    471 |     const elementHandle = await page.$('div.to-screenshot');
    472 |     const screenshot = await elementHandle.screenshot();
    473 |     expect(screenshot).toBeInstanceOf(Buffer);
    474 |     const sizeAfter = await page.evaluate(() => ({ width: document.body.offsetWidth, height: document.body.offsetHeight }));
    475 |     expect(sizeBefore.width).toBe(sizeAfter.width);
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
    Expected: 1350
    Received: 0
```

**Comment by pavelfeldman** [comment]
Not marking either as v1 blocking since (1) and (2) are injected page renderers and (3) implies persistent profile with user bounds (a non-bot mode)

**Comment by mxschmitt** [comment]
Closed since its removed
