### ISSUE TITLE
[BUG] Extension :: Playwright Test for VSCode :: Type Module

### ISSUE THREAD

**Issue by Hansz** [microsoft/playwright#20860]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 16.14.0
- Visual Studio Code version: 1.75.1
- Playwright for VSCode extension version: 1.0.7
- Browser: Chrome, Firefox
- Extra: type: module

**Code Snippet**

  "name": "@company/nglib",
  "version": "0.0.2",
  "description": "Company Vue3 library",
  "type": "module",              <---------------------------- The culprit
  "main": "dist/library.js",
  "module": "dist/library.mjs",

**Describe the bug**

NO tests being found, nor indicated in the sideline when the project is of type: module. As soon as this is removed, the plugin has no issues whatsoever recognizing and running tests from the IDE.

**Comment by Hansz** [comment]
Additional Info:

I had to rename the "playwright.config.js" to "playwright.config.cjs" to be able to make it work from the commandline (npx run test)

Could it be that this renamed config prevents the extension from finding tests, as it defines the "testDir" that points at the location of the tests.

**Comment by aslushnikov** [comment]
@Hansz any chance you can provide a simple repro that I can run locally to see this behavior for myself? A small github repo with the code would suffice.

**Comment by Hansz** [comment]
@aslushnikov

Hi Andrey,

I prepared this little public repo, I hope it helps: https://github.com/Hansz/playit

Please let me know if you need anything else.

Hans.

**Comment by yury-s** [comment]
Thanks for the repro, I can reproduce it locally, it's a bug.

**Comment by yury-s** [comment]
In ES modules you should use `export default defineConfig({` syntax for declaring the config. module.exports should be used in commonjs modules. Change [this line](https://github.com/Hansz/playit/blob/e5c5a40879362162ddfe47a94254aae70fc87e98/playwright.config.cjs#L13) in your code to  `export default` and rename the file to `playwright.config.js`

**Comment by Hansz** [comment]
Works like a charm. 

Thanks for the effort and the feedback.
