### ISSUE TITLE
[BUG] unexpected value "hidden" for visible element

### ISSUE THREAD

**Issue by joszo** [microsoft/playwright#20862]
**Context:**
- Playwright Version: [1.30]
- Operating System: [Mac]
- Node.js version: [v18.12.1]
- Browser: [All / Chromium]
- Extra: [any specific details about your environment]

**Describe the bug**

Incorrect behaviour for visible element:

In devtools 
```window.getComputedStyle($('[data-tid="refresh-modal"]')).visibility``` -> 'visible'

but in test it is contatly failing 
```
const modal =  page.locator('[data-tid="refresh-modal"]');
await expect(modal).toBeVisible();
```

```
      -   locator resolved to <div effect="fade/zoom" data-tid="refresh-modal" id="…>…</div>
      -   unexpected value "hidden"
```
Of course adding assertion for toBeHidden() + .not.toBeVisible are passing for that element.

I saw that Max mentioned in closed issues https://github.com/microsoft/playwright/issues/19910 that something changed in version 1.30. 

In DOM tree there is no ```display: none```  in the code. 

Any ideas?

**Comment by aslushnikov** [comment]
@joszo any chance you can build a small repro that illustrates this issue? This way we'll be able to debug it.

**Comment by joszo** [comment]
@aslushnikov I'm so sorry, after small debug I found that my element was 0x0 so in fact it is not visible... 

Maybe we should consider better error message, because from my perspective hidden is not necessary equal to 0x0, maybe I'm wrong?

**Comment by aslushnikov** [comment]
We might update error messages in a bit; for now, the visibility is described here: https://playwright.dev/docs/next/actionability#visible
