### ISSUE TITLE
[BUG] Tests seen in test explorer and run properly, but don't from the command line.

### ISSUE THREAD

**Issue by JavontaeH** [microsoft/playwright#20873]
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Node.js version: v18.12.1
- Browser: N/A

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Hard to snip, I can send the codebase but it contains some sensitive data and not sure how to reproduce the bug on a snippet.

**Describe the bug**

When ran from the command line, reporters (custom and otherwise) are saying 0 tests are detected (not an error, just finishes run with 0 tests) even though running from the proper directory and the test explorer can both detect and run those tests as usual.

Add any other details about the problem here.

Running the tests from the command line was working before, and I see no noticeable changes to the code that could effect this unless I'm missing something.

**Comment by JavontaeH** [comment]
![image](https://user-images.githubusercontent.com/61520550/218566956-32b6c70b-a2c8-4797-b496-ec82bb1b8c7c.png)
![image](https://user-images.githubusercontent.com/61520550/218567013-45b29de8-2ec1-489d-a43d-990d75fc17e9.png)
Line reporter returns: 
![image](https://user-images.githubusercontent.com/61520550/218568426-093c818c-8256-4161-ac00-2ec2d89ae3a9.png)

**Comment by aslushnikov** [comment]
This errors looks similar to the previous reports, e.g.:

- https://github.com/microsoft/playwright/issues/16347
- https://github.com/microsoft/playwright/issues/13092

Could it be you're stumbling on something like these?

**Comment by aslushnikov** [comment]
Looks like our discussion has stalled; I'll close this then.

Please do not hesitate to file a new issue if you think we still can be helpful!

**Comment by JavontaeH** [comment]
sorry, meant to say it was related to the directory naming file.
