### ISSUE TITLE
Writing Documentation of Project in HIndi Language

### ISSUE THREAD

**Issue by Bharadwajshivam28** [microsoft/playwright#20875]
Hello Respected sir
   If you like my idea then we can write a Documentation on this project in Hindi Language

Aim of writing Document of Project in  Hindi Language is that Many people understand Hindi language  well in countries like India so one can read the documentation in Hindi language and understand Project well

**Comment by Bharadwajshivam28** [comment]
@aslushnikov

**Comment by aslushnikov** [comment]
As of today, documentation localization is not on our roadmap. However, if you'd like to host your own localized version of Playwright documentation, we'll be happy to refer to it!

**Comment by Bharadwajshivam28** [comment]
ya i like to host my own version of playwright documentation @aslushnikov

**Comment by aslushnikov** [comment]
@Bharadwajshivam28 feel free to file a new issue once its up & running!

**Comment by Bharadwajshivam28** [comment]
ok

**Comment by Bharadwajshivam28** [comment]
is there any community where i can be connected with all these tech @aslushnikov

**Comment by aslushnikov** [comment]
Try https://aka.ms/playwright/discord
