### ISSUE TITLE
[Feature] option to save the trace as a html file

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#20886]
in our CI, we upload the trace files as artifacts. however that means to view them it takes additional steps which is quite annoying:

1. download the trace file
2. navigate to `trace.playwright.dev`
3. manually upload the file

i know you can run `playwright show-trace` with the url of the artifacts, but that doesn't work when if the url requires authentication

if the trace was instead saved as a `.html` file, it would make it much easier

**Comment by KotlinIsland** [comment]
Another option (if possible) would be making the trace.playwright.dev site able to be some how take a zip file programmatically, so a simple button on the artifact page could open the trace.

**Comment by aslushnikov** [comment]
> Another option (if possible) would be making the trace.playwright.dev site able to be some how take a zip file programmatically, so a simple button on the artifact page could open the trace.

@KotlinIsland this is already possible: https://playwright.dev/docs/next/trace-viewer#viewing-remote-traces

**Comment by DetachHead** [comment]
Yeah I think both the site and the cli are doing the best they can when it comes to programmatically opening traces. Unfortunately it doesn't work for our case since the uploaded artifacts require authentication to view (and also CORS)

[robot logs](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#log-file) solve these issues by storing everything in a single html file, I think thats the best approach

**Comment by KotlinIsland** [comment]
> > Another option (if possible) would be making the trace.playwright.dev site able to be some how take a zip file programmatically, so a simple button on the artifact page could open the trace.
> 
> @KotlinIsland this is already possible: https://playwright.dev/docs/next/trace-viewer#viewing-remote-traces

That's for the cli, our use-case is a web extension that could open the trace in a new tab.

**Comment by aslushnikov** [comment]
> That's for the cli, our use-case is a web extension that could open the trace in a new tab.

@KotlinIsland There's a part for the website as well: 

> <img width="869" alt="image" src="https://user-images.githubusercontent.com/746130/219066806-a089d991-9841-4a1f-a071-6f2fc24f5bbf.png">

> Yeah I think both the site and the cli are doing the best they can when it comes to programmatically opening traces. Unfortunately it doesn't work for our case since the uploaded artifacts require authentication to view them (and also CORS)

@DetachHead well yes, this is pretty unfortunate. What's your CI?

**Comment by DetachHead** [comment]
> What's your CI?

We use an internally hosted gitlab instance

**Comment by esther-86** [comment]
I just vibe coded and have something that works for my need. Sharing in case it helps others: https://github.com/esther-86/playwright-trace-helper
