### ISSUE TITLE
Instead of creating new local workplace settings, perhaps keeping settings.json as the local workspace settings file and creating a new shared workplace settings file makes more sense?

### ISSUE THREAD

**Issue by GuilaMonstar** [microsoft/playwright#20884]
Instead of creating new local workplace settings, perhaps keeping settings.json as the local workspace settings file and creating a new shared workplace settings file makes more sense?

That way the extension api #43226 wouldn't need to change and extensions would continue to work as they are currently written.

The only change necessary, I imagine, would be to check to see if .vscode/shared.json (or whatever) existed, load it first, then load .vscode/settings.json.

In my case, the issue is that the python extension writes the python path to settings.json which is different for every developer using virtualenv. The settings I'd like to add to version control and share between devs are files to ignore, unit testing and linting.

_Originally posted by @Aloisius in https://github.com/microsoft/vscode/issues/40233#issuecomment-395883302_

**Comment by GuilaMonstar** [comment]
[Sintaxis de escritura y formato básicos](https://guilamonstar-super-duper-pancake-x6gq49rwv69hvg55.github.dev/) https://github.com/microsoft/playwright/issues/20884#issue-1583591568

**Comment by aslushnikov** [comment]
@GuilaMonstar this seems to be a VSCode issue, so I'm not sure why posting it here.
