### ISSUE TITLE
[BUG] Impossible to use same variable in different test steps #20502

### ISSUE THREAD

**Issue by MehseinJohan** [microsoft/playwright#20887]
Context:

Playwright Version: 6.14.15
Operating System: Windows
Node.js version: 6.14.15
Browser: Chromium

Nota : Bug https://github.com/microsoft/playwright/issues/20502 had been opened successfully but closed without any resolution.

Describe the bug
Hello, I found out that it's not possible to define a variable in a specific test step and use it in another one. Everytime I do so, the variable is set as "undefined".
I've tough tried to use the return function in the test step where I defined it.
I've also tried "let variable" at the beginning of the test step where I call it but unsuccessfully.

Is it a limitation ?

Thank you in advance,

Regards,

Johan

**Comment by aslushnikov** [comment]
@MehseinJohan the following does work for me:

<img width="713" alt="image" src="https://user-images.githubusercontent.com/746130/218774644-22401802-7877-4679-80b1-28658a221130.png">

Try this out yourself:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ }) => {
  let foo;
  await test.step('first', () => {
    foo = 100;
  });
  await test.step('second', () => {
    console.log(foo);
  });
});
```

Let me know if this snippet works for you.

**Comment by MehseinJohan** [comment]
Hello, it's working, thank you.

My error was that I was redefining the variable with keywords such as "var".

Thank you,

Regards,

Johan

**Comment by MehseinJohan** [comment]
Can be closed.
