### ISSUE TITLE
[BUG] Why fill action only writes one letter?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#20896]
While searching on the UI like a manual user, when a letter is typed in the search field, a request is sent to the backend in the background. For example, we will write **_Try123_** in the search field. When I type the letter T, the request goes to the backend and brings the list starting with T. The same request continues until all the other letters are finished. When the last "Try123" is typed, a last request is sent for the last request and brings the searched text. You can see it in the network screenshot below. This is how it works manually.
![image](https://user-images.githubusercontent.com/119929590/218753036-498529ac-d63a-404f-9625-21ccc08596e9.png)

In order to do this with code, I wrote an example code as follows;

```
import { Locator, Page } from "@playwright/test";

export class BasePage {
  page: Page;
  searchTxt: Locator;

  constructor(page: Page) {
    this.page = page;
    this.searchTxt = page.locator("//span[contains(@class,'search-input')]/input");

  }

  async searchText(text: string) {
    await Promise.all([
      this.searchTxt.fill(text),
      this.searchTxt.press("Enter"),
      this.page.waitForResponse(res => res.status() === 200)
    ])
  }

}

```

But above code when I use fill ,it only typed only **T** letter not others.Try 10 times and everytime only writes first letter **T.**I think that it must type all **Try123**.Because of this I tried type method as below;

```
  async searchText(text: string) {
    await Promise.all([
      this.searchTxt.type(text, { delay: 80 }),
      this.page.waitForResponse(res => res.status() === 200)
    ])
  }
```

But this time, when I use the type method, it sometimes writes by deleting 1 letter. For example, it writes words like Try23, ry123, Try2  when I try to write **Try123**. Sometimes some letters are deleted . 

>  Fill -> everytime only writes first letter, 
>  Type -> Sometimes writes deleting one letter

Is this a bug or what could it be from?

**Comment by aslushnikov** [comment]
@YusufOzt how do you call this method? do you pass the whole text, or you call the method repeatedly?

**Comment by YusufOzt** [comment]
@aslushnikov  I m calling like below;
```
   let createdFlowName=`${faker.lorem.word(5)}${faker.datatype.number({ min: 1000, max: 1000000 })}`
   await basePage.searchText(createdFlowName)
```

Calling this method 30 times in different cases when I need to use search. But calling everytime like above

**Comment by aslushnikov** [comment]
So in your first snippet:

```ts
  async searchText(text: string) {
    await Promise.all([
      this.searchTxt.fill(text),
      this.searchTxt.press("Enter"),
      this.page.waitForResponse(res => res.status() === 200)
    ])
  }
```

You hit `press` **simultaneously** with filling in the text. I guess it should be something like the following instead:

```ts
  async searchText(text: string) {
    await this.searchTxt.fill(text);
    await Promise.all([
      this.searchTxt.press("Enter"),
      this.page.waitForResponse(res => res.status() === 200)
    ])
  }
```

You second snippet with `this.searchTxt.type` looks legit to me. I'd assume that your auto-suggest is messing with the input field / input field focus, so things occasionally are not typed in.

It still might be a Playwright bug. But for us to act upon it, we'll need a good repro that we can run & debug locally, including details about your browser & operating system. 

If you believe this is Playwright issue, please file a new issue following the issue template and providing us with a repro. Meanwhile, I'll speculatively close this.

**Comment by YusufOzt** [comment]
@aslushnikov  thanks for response ,if I can not solve ,I will create a new issue with a repro
