### ISSUE TITLE
[Question] waitForSelector default - attached vs visible

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2090]
This is a curiosity thing.

How come `attached` is the default for [waitForSelector](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagewaitforselectorselector-options), and not `visible`?

I would have guessed `visible` would be the most common default to want, but I might be entirely incorrect in that assumption.

**Comment by pavelfeldman** [comment]
We liked the idea.

**Comment by aesyondu** [comment]
Same. I almost always add `waitFor: "visible"` in my `waitForSelectors`
