### ISSUE TITLE
[BUG]Can't listen to copy event

### ISSUE THREAD

**Issue by zhhanging** [microsoft/playwright#20916]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.13.0
- Operating System: [e.g. Windows, Linux or Mac] Mac
- Node.js version: [e.g. 12.22, 14.6] 18.13
- Browser: [e.g. All, Chromium, Firefox, WebKit] Chromium
- Extra: [any specific details about your environment]

I was trying to get the clipboard data after clicking a "Copy Value" button. It needed some time to write the value to clipboard. But there is no `page.on("copy")`, so I tried to do the following instead. But it didn't work. Time out at "await copyPromise". Can someone please help me at this?

```javascript
const copyPromise = page.evaluate(() => {
  return new Promise((resolve) => {
    document.addEventListener("copy", (e) => {
      resolve("copied");
    });
  });
});

await page.getByRole("button", { name: "Copy Value" }).click();

await copyPromise;

// do something about the clipboard data

```

**Comment by aslushnikov** [comment]
@zhhanging the ["copy" event](https://developer.mozilla.org/en-US/docs/Web/API/Element/copy_event) happens whenever the user hits "Cmd-C" to copy selected text; I assume your website doesn't do it, and instead uses something like [`navigator.clipboard.writeText`](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/writeText) API.

You can either:
1. Mock the `navigator.clipboard.write` and `navigator.clipboard.writeText` API's to make sure they're called: https://playwright.dev/docs/mock-browser-apis
2. Or just read the value with `navigator.clipboard.readText()` and make sure that it's as expected.

The second approach would look like this:

```ts
await page.getByRole("button", { name: "Copy Value" }).click();
await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('foobar');
```

Hope this helps!

**Comment by zhhanging** [comment]
Thank you aslushnikov. This is the first time I know that `navigator.clipboard.writeText` doesn't trigger "copy" event. You saved my day.
