### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Schepetkov** [microsoft/playwright#20913]
**Context:**
- Playwright Version: [1.30.0]
- Operating System: [Windows 11]
- NET version: [7.0]
- Browser: [Chromium, Version 110.0.5481.77]

Can't click on item from items list, I try different approach, but driver does click.
**Examples:**

1. await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo" }).ClickAsync();
2. await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo", Exact = true }).ClickAsync();
3. await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo", Exact = true }).ClickAsync();
4. await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo"}).ClickAsync();
5. await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo") }).ClickAsync();

  // Please include a snippet of HTML that shows an example of the content
  //Can't click to:
```
 <span class="a-button-inner"><button id="gc-mini-design-thumb-2" name="B07PCMWTSG" class="a-button-text" type="button">
        <img alt="Amazon Logo" src="https://m.media-amazon.com/images/I/31%2BDgxPWXtL._SR80,60_.jpg" id="gc-mini-picker-design-swatch-image-2" height="60" width="80">
      </button></span>
```
  // Alternatively, if you are testing a public application, include the URL:
https://www.amazon.com/Amazon-eGift-Card-Logo/dp/B07PCMWTSG/ref=sr_1_1?keywords=Gift+Cards&qid=1676448648&sr=8-1
  
But if I try click to `alt="Amazon Logo - Blue Flower`":
```
<span class="a-button-inner"><button id="gc-mini-design-thumb-13" name="B0BRSDM1XK" class="a-button-text" type="button">
        <img alt="Amazon Logo - Blue Flower" src="https://m.media-amazon.com/images/I/41GHGvLgzFL._SR80,60_.jpg" id="gc-mini-picker-design-swatch-image-13" height="60" width="80">
      </button></span>
```
**Like this:**
`await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo - Blue Flower") }).ClickAsync();`

All work well, is this a **bug?**

Also, if I try:
`await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo") }).ClickAsync();`

I get exception (which is logical):

```
Microsoft.Playwright.PlaywrightException: 'Error: strict mode violation: GetByRole(AriaRole.Img, new() { Name = "Amazon Logo" }) resolved to 2 elements:
    1) <img width="80" height="60" alt="Amazon Logo" id="gc-…/> aka GetByRole(AriaRole.Button, new() { Name = "Amazon Logo", Exact = true })
    2) <img width="80" height="60" alt="Amazon Logo - Blue F…/> aka GetByRole(AriaRole.Button, new() { Name = "Amazon Logo - Blue Flower" })
```

![Screenshot_1](https://user-images.githubusercontent.com/29506847/218972594-7d90576a-33a4-4b57-b109-8aaa6140a199.png)

**Comment by aslushnikov** [comment]
@Schepetkov I don't see how this is a bug.

> await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo" }).ClickAsync();
> await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo"}).ClickAsync();

This won't click because it's not strict. Also, `NameString` and `Name` is the same.

> await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo", Exact = true }).ClickAsync();
> await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo", Exact = true }).ClickAsync();

This won't click because this doesn't match any element.

> await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo") }).ClickAsync();

This won't click because there are multiple locators that satisfy the element.

> await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo - Blue Flower") }).ClickAsync();

Finally, this **does click** because it finally matches a single element.

You should also be able to do the following:

```csharp
await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo - Blue Flower" }).ClickAsync();
```

So answering the question - no, this is not a bug! Also, consider using CodeGen to generate good locators for your selectors. See https://www.youtube.com/watch?v=tVSq-0n-TY4&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=2&t=287s

**Comment by Schepetkov** [comment]
> @Schepetkov I don't see how this is a bug.
> 
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo" }).ClickAsync();
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo"}).ClickAsync();
> 
> This won't click because it's not strict. Also, `NameString` and `Name` is the same.
> 
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { NameString = "Amazon Logo", Exact = true }).ClickAsync();
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo", Exact = true }).ClickAsync();
> 
> This won't click because this doesn't match any element.
> 
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo") }).ClickAsync();
> 
> This won't click because there are multiple locators that satisfy the element.
> 
> > await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo - Blue Flower") }).ClickAsync();
> 
> Finally, this **does click** because it finally matches a single element.
> 
> You should also be able to do the following:
> 
> ```cs
> await this.driver.Page.GetByRole(AriaRole.Img, new () { Name = "Amazon Logo - Blue Flower" }).ClickAsync();
> ```
> 
> So answering the question - no, this is not a bug! Also, consider using CodeGen to generate good locators for your selectors. See https://www.youtube.com/watch?v=tVSq-0n-TY4&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=2&t=287s

Hi Andrey, thanks for fast reply.
Yes I know about CodeGen, I try to use, and it gives me this issues:
locator:
`await this.driver.Page.GetByRole(AriaRole.Button, new () { Name = "Amazon Logo" }).ClickAsync();`
Problem after use:
```
Microsoft.Playwright.PlaywrightException: 'Error: strict mode violation: GetByRole(AriaRole.Button, new() { Name = "Amazon Logo" }) resolved to 2 elements:
    1) <button type="button" name="B07PCMWTSG" class="a-button-…>…</button> aka GetByRole(AriaRole.Button, new() { Name = "Amazon Logo", Exact = true })
    2) <button type="button" name="B0BRSDM1XK" class="a-button-…>…</button> aka GetByRole(AriaRole.Button, new() { Name = "Amazon Logo - Blue Flower" })
```
I don't understand, how in situation like this (when two locators have almost same sting), press "Amazon Logo". 
How filer this locator?

By the way, this approach work fine (I didn't say is not work, I just give example.):
`await this.driver.Page.GetByRole(AriaRole.Img, new () { NameRegex = new Regex ("Amazon Logo - Blue Flower") }).ClickAsync();`
You can try yourself.

And thanks for cool tool.
I'm still just learning, and I want to use playwright at work.

**Comment by aslushnikov** [comment]
Hmm, Codegen gave me a different locator:

```
GetByRole(AriaRole.Button, new() { Name = "Amazon Logo", Exact = true })
```

<img width="712" alt="image" src="https://user-images.githubusercontent.com/746130/219283469-bd800f0e-8920-4031-9d03-e1c0534fbe44.png">

**Comment by Schepetkov** [comment]
I visited it through VS, and it generates it like this:
![image](https://user-images.githubusercontent.com/29506847/219285362-0250ccb0-9f0b-4b49-9d67-804054c41829.png)

But when you use your option, it still does not push the button:
![image](https://user-images.githubusercontent.com/29506847/219285237-884ec482-21e4-4db2-b533-bd60e081c3b0.png)
