### ISSUE TITLE
[Question] Is there any way to use Opera and Opera GX with playwright? 

### ISSUE THREAD

**Issue by Rudy123456789** [microsoft/playwright#20915]
Hi all. I have a question. Is there any way to use Opera/Opera GX with playwright to tests aplications. Option chromium.launch with executuinPath don't work for me. Browser start but it crash immidetly. Maybe good option is add Opera and other browser with don't work with BrowserType.launch to playwright.

**Comment by aslushnikov** [comment]
> Hi all. I have a question. Is there any way to use Opera/Opera GX with playwright to tests aplications. Option chromium.launch with executuinPath don't work for me. Browser start but it crash immidetly. Maybe good option is add Opera and other browser with don't work with BrowserType.launch to playwright.

@Rudy123456789 what version of Opera browser are you using?

**Comment by Rudy123456789** [comment]
Last developer version.

**Comment by aslushnikov** [comment]
Does the official stable latest version crash as well with Playwright 1.30?

**Comment by Rudy123456789** [comment]
Yes

**Comment by aslushnikov** [comment]
@Rudy123456789 Ah, it looks like Opera did not implement the `Target.createTarget` DevTools protocol command.

Launching persistent profile works fine:

```ts
import { chromium } from '@playwright/test';

const browser = await chromium.launchPersistentContext('./foo', {
  executablePath: '/Applications/Opera.app/Contents/MacOS/Opera',
  headless: false,
});

const page = browser.pages()[0];
```

So as long as you don't call `context.newPage()` method, it all seems to be working. However, we don't run any of our tests against opera, so no guarantees here.

**Comment by Rudy123456789** [comment]
@aslushnikov  in my code 
`import { test, chromium } from '@playwright/test';

test.describe('test', () => {

  test('got to page', async () => {
    const browser = await chromium.launchPersistentContext('USERDIR\\GX\\profile\\data', {
      headless: false,
      ignoreDefaultArgs: true,
      executablePath:
        'USERDIR\\GX\\opera.exe',
    });
    const page = browser.pages()[0];
    await page.waitForTimeout(10000);
  })

});
`

I have this output 

`browserType.launchPersistentContext: Browser closed.
    ==================== Browser output: ====================
    <launching> C:\Users\pgawlik\Desktop\GXdev\opera.exe
    <launched> pid=7776
    =========================== logs ===========================
    <launching> C:\Users\pgawlik\Desktop\GXdev\opera.exe
    <launched> pid=7776
    ============================================================

      4 |
      5 |   test('got to page', async () => {
    > 6 |     const browser = await chromium.launchPersistentContext('USERDIR\\GX\\profile\\data', {
        |                     ^
      7 |       ignoreDefaultArgs: true,

**Comment by aslushnikov** [comment]
I didn't test with Opera GX; so not sure. However, try removing `ignoreDefaultArgs: true`?

**Comment by Rudy123456789** [comment]
I try it on Opera stable too with the same effect. Without it I have the same output but browser don't start. My major goal it to run Opera GX.

**Comment by aslushnikov** [comment]
@Rudy123456789 It looks like Opera now broke some Chrome DevTools protocol. I'd recommend complaining to Opera maintainers about this; there's nothing we can do about it on our end.

I'm sorry we can't help much here! Feel free to file new issues though if you think we can still be helpful.
