### ISSUE TITLE
[BUG] Cannot validate a text that contains a space in it

### ISSUE THREAD

**Issue by eclipses** [microsoft/playwright#20912]
**Context:**
- Playwright Version: Version 1.30.0
- Operating System: Windows 11
- Node.js version: v18.12.1
- Browser: All

**Code Snippet**
```
<div data-formula="%dummy%*%totale_farina%*%pref%/100" data-name="field_farina_biga" data-precision="0" data-sep-decimal="." data-value-type="number" class="jet-form-builder__calculated-field">
        <input type="hidden" name="field_farina_biga" value="500" class="jet-form-builder__calculated-field-input jet-form-builder__field" data-field-name="field_farina_biga" data-jfb-sync="">
	<div class="jet-form-builder__calculated-field-val">500</div>
	<div class="jet-form-builder__calculated-field-suffix">&nbsp;g</div>
</div>
```

```
import { test, expect } from '@playwright/test';

test('calcolatore biga', async ({ page }) => {
  await page.goto('https://***');
  
  var farina = await page.locator('//*[@data-name="field_farina_biga"]').allInnerTexts();
  await expect(farina[0]).toEqual('500\n g');
});
```

**Describe the bug**
I cannot setup the expect to check a value when it is retrieved from multiple elements and it contains a space in the text.
The allInnerTexts returns only one item instead of two and it contains the the following value "500\n g" in regular expression format. The space is the rendeing of the space in HTML that is converted in a special character not clear.

**Comment by aslushnikov** [comment]
@eclipses You should use the [`expect(locator).toHaveText()`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text) web-first assertion.

The following works for me:

```ts
import { test, expect } from '@playwright/test';

test('should apply referrer', async ({ page }) => {
  await page.setContent(`
    <div data-formula="%dummy%*%totale_farina%*%pref%/100" data-name="field_farina_biga" data-precision="0" data-sep-decimal="." data-value-type="number" class="jet-form-builder__calculated-field">
      <input type="hidden" name="field_farina_biga" value="500" class="jet-form-builder__calculated-field-input jet-form-builder__field" data-field-name="field_farina_biga" data-jfb-sync="">
      <div class="jet-form-builder__calculated-field-val">500</div>
      <div class="jet-form-builder__calculated-field-suffix">&nbsp;g</div>
    </div>
  `);

  await expect(page.locator('//*[@data-name="field_farina_biga"]')).toHaveText('500 g');
});
```

Does this work for you?

**Comment by eclipses** [comment]
@aslushnikov it works like a charm.

Not sure if was correct that allInnerTexts() one item only, if you don't think there is anything strange please proceed closing this issue. 

Thank you

**Comment by aslushnikov** [comment]
> Not sure if was correct that allInnerTexts() returned one item only, if you don't think there is anything strange please proceed closing this issue.

Yeah, your locator matches a single element, so this is expected.
