### ISSUE TITLE
[Feature] Ability to use headless pages

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#2092]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?

Testing extension requires head full mode. But some action like printing requires headless mode. It would be useful to have headless page if possible?

**Comment by pavelfeldman** [comment]
Testing Chromium extension does not require headful mode. And there is no printing testing supported. Could you clarify your use case?

**Comment by shirshak55** [comment]
@pavelfeldman I don't but many extension don't seems to run on headless mode so i always run them over virtual screen and it seems thats upstream issue so nothing can be done. 

And there are something like print pdf which is not supported in headful mode. So it would be easy if we can switch headless to headful in runtime.


https://bugs.chromium.org/p/chromium/issues/detail?id=706008

**Comment by pavelfeldman** [comment]
We are trying to focus on testing only in our v1, do you use pdf for testing or is this a different kind of activity?

**Comment by shirshak55** [comment]
@pavelfeldman we do use print for integration testing just to ensure prints are working properly. But sometime we do enable headful mode just to see if there are any bugs. It would be nice if playwright can switch to headless mode and capture the pdf rather than giving error even tho we originally ran for headful mode?

**Comment by aslushnikov** [comment]
> But some action like printing requires headless mode.

@shirshak55 It looks like the actual bug here is that `page.pdf() does not work in headful. I've filed this separately as #2236 

Fixing PDF generation in headful mode is more realistic than implementing something like "headless page", so please feel free to upvote!
