### ISSUE TITLE
[Feature] Create additional context in test respecting browser options and is closed automatically

### ISSUE THREAD

**Issue by Georgegriff** [microsoft/playwright#20921]
Hey!

I'm looking i'm working with tests with multiple users, where i need to load in storageState, i can see the documentation is fairly good for this but i can see a bit of an issue with it, in terms of having to define newContexts

the documentation recommends doing this:

```ts
 // adminContext and all pages inside, including adminPage, are signed in as "admin".
  const adminContext = await browser.newContext({ storageState: 'playwright/.auth/admin.json' });
  const adminPage = await adminContext.newPage();

  // userContext and all pages inside, including userPage, are signed in as "user".
  const userContext = await browser.newContext({ storageState: 'playwright/.auth/user.json' });
  const userPage = await userContext.newPage();
```

## This mostly works but it brings up a few problems:
- You have to write custom code to ensure that your context is closed when test fails i think? Because browser is shared across tests, avoid potential memory leaks with loads of contexts left open?
- The other issue is that the `context` we are provided with uses a load of default options in the playwright code
Your source code:
![image](https://user-images.githubusercontent.com/9056958/219111307-506e7095-e826-4f05-9245-4f63fb21decc.png)

**Example: Use case**
We need to set a custom http header `extraHTTPHeaders` for our context (i.e. WAF token) and this means we have to maintain some code which ensures we're forwarding on all of the right options onto the new context, i think?
Any other fixture level options also would have to be set as well i think?

 I suspect this is only the case for options set on the fixture though with test.use but its still a bit of a limitation that is not obvious to test writers

[I notice there once was a built in createContext fixture that would have solved this problem,](https://github.com/microsoft/playwright/pull/8109/files) i wonder if by relying on browser.createContext the above functionality of the `test` fixture managing all the browser contexts was lost

 A new createContext default fixture that lets you pass in options or fallsback to fixture and browser defaults might be quite nice to solve this issue. One that handles all the teardown stuff

**Comment by aslushnikov** [comment]
> We need to set a custom http header extraHTTPHeaders for our context (i.e. WAF token) and this means we have to maintain some code which ensures we're forwarding on all of the right options onto the new context, i think?

@Georgegriff This is already done for you, so it should just work. Have you tried? 

Regarding creating contexts for yourself, I'd recommend shaping them as a fixture so that you can easily manage their setup / teardown.

Would it work?

**Comment by Georgegriff** [comment]
That sounds doable then

 I have tried but I think at the time I may have been getting thrown by this bug so my test was failing with a CORs error not Auth being broken...


I just checked yeah that's the case.

This was the big which led me to believe this didn't work 😅

https://github.com/microsoft/playwright/issues/19904

It says Firefox and webkit which is curious as I'm on chrome. Think can close this issue though, and I can watch that bug.

**Comment by philipfong** [comment]
@Georgegriff do you happen to have any input on how to close contexts? I end up having to manually call 'await context.close()` on every single one of my tests and haven't found a way to incorporate that into fixtures or in a afterEach hook
