### ISSUE TITLE
[BUG] API Assertion 'toContainEqual' fails given one/all correct json key-value pair

### ISSUE THREAD

**Issue by carlnoval** [microsoft/playwright#20934]
**Context:**
- Playwright Version: Version 1.30.0
- Operating System: MacOS Ventura Version 13.2 with M1(2020)
- Node.js version: v16.13.1
- Browser: Chromium 110.0.5481.38, FireFox 108.0.2, WebKit 16.4

**Code Snippet**
```typescript
test('unable to fetch an invalid movie', async ({ request, _tmdbV3API, _tmdbV3APIKey }) => {
  // const requestURL = 'https://api.themoviedb.org/3/movie/315162?api_key='
  const invalidID = '9999999999'
  const requestURL = `${_tmdbV3API}movie/${invalidID}?api_key=${_tmdbV3APIKey}` ;
  const movie = await request.get(requestURL);
  expect(movie.status()).toBe(404);
  expect(await movie.json()).toContainEqual(expect.objectContaining({
    status_code: 34,
    status_message: "The resource you requested could not be found.",
    success: false
  }));
});
```

**Error**
```txt
Error: expect(received).toContainEqual(expected) // deep equality

Expected value:  ObjectContaining {"status_code": 34, "status_message": "The resource you requested could not be found.", "success": false}
Received object: {"status_code": 34, "status_message": "The resource you requested could not be found.", "success": false}

  26 |     const movie = await request.get(requestURL);
  27 |     expect(movie.status()).toBe(404);
> 28 |     expect(await movie.json()).toContainEqual(expect.objectContaining({
     |                                ^
  29 |       status_code: 34,
  30 |       status_message: "The resource you requested could not be found.",
  31 |       success: false
```

**Describe the bug**
- **Expected Result**: API assertion should pass given one/all correct json key-value pairs inside `expect.objectContaining`.  
- **Actual Result**: API assertion fails given one/all correct json key-value pairs used inside `expect.objectContaining`. 
- **More info**:
  - The final assertion uses techniques from the [official doc](https://playwright.dev/docs/test-api-testing#writing-tests) where `.toContainEqual(expect.objectContaining` is used.
  - One discord user suggested to use `.toEqual` instead of `toContainEqual`. Using `.toEqual` makes the API assertion pass  given one/all correct json key-value pair.
- Descriptions: `.toEqual` vs `toContainEqual` 
  -  `.toEqual` - Used when you want to check that two **objects** have the same value. This matcher recursively checks the equality of all fields, rather than checking for object identity.
  - `toContainEqual` - Used when you want to check that an item is in a **list**. For testing the items in the list, this matcher recursively checks the equality of all fields, rather than checking for object identity.
 
**Query** 
1. Should the doc be updated to use `.toEqual` instead of `toContainEqual`?

**Comment by aslushnikov** [comment]
@carlnoval can you please provide me with the actual value of the `movie.json()` so that I can try running this locally?

**Comment by carlnoval** [comment]
```typescript
const movieJson = await movie.json();
console.log(movieJson);
```
@aslushnikov  Above code generates below json.
```typescript
{
  success: false,
  status_code: 34,
  status_message: 'The resource you requested could not be found.'
}
```

**Comment by aslushnikov** [comment]
@carlnoval your `movieJson` is not an array; the method [`toContainEqual`](https://jestjs.io/docs/expect#tocontainequalitem) expects it to be an array:

> Use .toContainEqual when you want to check that an item with a specific structure and values is contained in an array.

So, for example, the following works fine for me:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ }) => {
  const array = [{
    success: false,
    status_code: 34,
    status_message: 'The resource you requested could not be found.'
  }];
  expect(array).toContainEqual(expect.objectContaining({
    status_code: 34,
    status_message: "The resource you requested could not be found.",
    success: false
  }));
});
```

> Should the doc be updated to use .toEqual instead of toContainEqual?

In the doc, we actually pull issues - which is an array, so it `toContainEqual` is a proper use there. 

Hope this helps!

**Comment by carlnoval** [comment]
@aslushnikov Got it! Was thinking that `await issues.json()` from [the doc](https://playwright.dev/docs/test-api-testing#writing-tests) resolves to a json.

Thanks!
