### ISSUE TITLE
maxDiffPixels does not work while page comparison, but works fine with element comparion

### ISSUE THREAD

**Issue by Fie-del** [microsoft/playwright#20938]
Hello,

I have 2 functions, 1 is to compare element and 1 is to compare page. defining **maxDiffPixels** within the element compare function or globally in  config file does work for element compare, but does not work for page compare. with page comparison test fails with pixel difference and does not have effect any effect with maxDiffPixels both when defining within function and globally in config file  

Below are my code 

**element compare:**
```
  async screenCompare(fileName,lan) {
    const finalName = fileName+"-"+lan+".png";
    expect(await this.page.screenshot()).toMatchSnapshot(`${finalName}`,{ maxDiffPixels: 5 }) 
```
  }

**Screen compare:**

```
  async elementCompare(element,fileName, lan) {
    const finalName = fileName+"-"+lan+".png";
    const pageElement = this.page.locator(`${element}`)
    expect(await pageElement.screenshot()).toMatchSnapshot(`${finalName}`,{ maxDiffPixels: 5 }) 
```

**Comment by aslushnikov** [comment]
@Fie-del any chance you can provide a simple repro (in a form of a github repo, maybe) that I can run to see that `maxDiffPixels` is ignored?

**Comment by aslushnikov** [comment]
Looks like the discussion has stalled - closing this. 

Please do not hesitate to file a new issue if you still experience this problem and you have a good repro for us to run locally!
