### ISSUE TITLE
[Question] Cannot hover disabled element

### ISSUE THREAD

**Issue by mingyoyo** [microsoft/playwright#20943]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 14.18.0
- Browser: Chromium

**Code Snippet**

```javascript
 await expect(page.locator(`button:disabled :has-text("pass")`)).toBeVisible();
 await page.locator(`button:disabled :has-text("pass")`).hover();
```

**Describe the bug**
locator.hover: Timeout 20000ms exceeded.
```html
Execution log
waiting for locator('button:disabled :has-text("pass")')
locator resolved to <span>pass</span>
attempting hover action
waiting for element to be visible and stable
element is visible and stable
scrolling into view if needed
done scrolling
<span class="sens-tooltip-disabled-compatible-wrapper">…</span> intercepts pointer events
retrying hover action, attempt #1
waiting for element to be visible and stable
element is visible and stable
scrolling into view if needed
done scrolling
...
```

**Comment by yury-s** [comment]
Apparently there is a `<span>` that overlays the button you are trying to hover. By default playwright tries to hover over the middle of an element, you can adjust that by providing custom [position](https://playwright.dev/docs/api/class-locator#locator-hover-option-position) within the element to make sure the mouse hover at a non-occluded area or if you still want to hover while the other span is there you can pass [force](https://playwright.dev/docs/api/class-locator#locator-hover-option-force) option.

Does it work for you? If think it's a playwright bug, please share a minimal repro that we could run locally.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
