### ISSUE TITLE
[Feature] Multi tab support

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#20942]
We have a performance monitoring product, that we inject in html pages.
The testing use case we have would be:
1. open tab in foreground
2. simulate middle click on a link and open a new tab in background
That tab in the background is interesting for us, because we want to test our product how it behaves when pages are loaded in background. We had some issues before with web vitals, timers being throttled etc...
Is there a possibility to test such scenario in playwright?
Or is it possible to create a page from an existing context that would be in the background?

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/3570
