### ISSUE TITLE
[Question] Experimental support for Electron based applications

### ISSUE THREAD

**Issue by rolandtamas** [microsoft/playwright#20951]
Hello,

As I have read from the documentation, Playwright has experimental support for testing Electron apps. What does this involve?
Are future versions of playwright not going to be supported anymore? Or is this a beta version of some sorts?

I would appreciate a clarification on this topic. Thank you!

**Comment by JoelEinbinder** [comment]
The apis might change a bit in the future but otherwise everything is quite usable. I am using it to test my own electron app.

**Comment by aslushnikov** [comment]
Joel gave a pretty accurate summary!

**Comment by rolandtamas** [comment]
But in a production environment is this suitable for testing?

**Comment by aslushnikov** [comment]
@rolandtamas Use your own judgement. We're making sure that our test suite passes with Electron, but the feature is still experimental.
