### ISSUE TITLE
[Feature] Show current step/fixture in list reporter

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#20955]
Some of my tests take a long time to run, and they have a few slow steps and slow fixtures which they instantiate. It would be nice to show the current fixture/step being worked on while the test is running so I can get a sense of how it is doing. I envision this going in gray where the elapsed time eventually appears.

I expect one fixture/step name to be shown. In the case of more than one active, I'd expect the most recently started one to be shown. Maybe add 250ms throttle to avoid too much noise in the terminal for quick tests.

I am happy to implement it if this is something that could land.

**Comment by aslushnikov** [comment]
There's already a "printSteps" option in list reporter!  https://playwright.dev/docs/next/test-reporters#list-reporter


```ts// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: [['list', { printSteps: true }]],
});
```

note for self: update doc

**Comment by JoelEinbinder** [comment]
1. Docs wouldn't have helped me. I didn't know reporters even had options because `npm init playwright` just gave me a string for reporter.

2. Print steps doesn't seem to show fixtures, which is the main place my tests are slow. Consider a `loggedInPage` fixture which loads and logs into the page. I can add steps directly into my fixtures, but that gets ugly pretty quickly. Needs a begin and end step, and all the variables have to be outside the step so that they can be used across steps. Would much rather it be built in.

3. Why not turn printSteps on by default? Who wants it off?

**Comment by aslushnikov** [comment]
Hey Joel!

As per the team meeting discussion:

> Why not turn printSteps on by default? Who wants it off?

We felt uncomfortable to toggle the option on by default.

> Docs wouldn't have helped me. I didn't know reporters even had options because npm init playwright just gave me a string for reporter.

This is still an issue with docs, probably. Debbie is re-working documentation, and it'll be part of her re-work.

With this, closing!

**Comment by acidoxee** [comment]
Hi, as mentioned in #20534 unfortunately the `printSteps` option doesn't seem to work in GitHub Actions. Is there any trick to force it anyway? The lack of display of steps in CI is quite painful for long-lived tests as we don't know what's happening unless we enable debug mode with `DEBUG=pw:api`, which is way too verbose.
