### ISSUE TITLE
[BUG] Chromium doesn't send beacon if page is still loading but redirected

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#20952]
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Node.js version: 16.18
- Browser: Chromium

## System:
 - OS: Windows 10 10.0.22621
 - Memory: 42.43 GB / 63.69 GB
## Binaries:
 - Node: 16.18.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD

**Code Snippet**

If page is redirected during while it did not finish loading, chromium never sends beacons to the server.
Given following test case
```javascript
test.only("incomplete load and page redirected in interactive state", async ({ page }) => {
        page.on("console", (msg) => {
            console.log(msg.text());
        });
        await page.goto(dtPageLocal.NON_INJECTED_HTML_PAGE, { waitUntil: "networkidle" });
});
```

and this html page
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script>
        window.addEventListener("beforeunload", () => {
            console.log("before unload");
            navigator.sendBeacon("https://requestinspector.com/inspect/01gsd336hfdk6cgc9nk75tb3r0")
        });
        window.addEventListener("unload", () => {
            console.log("unload");
            navigator.sendBeacon("https://requestinspector.com/inspect/01gsd336hfdk6cgc9nk75tb3r0")
        });
        window.addEventListener("pagehide", () => {
            console.log("page hide");
            navigator.sendBeacon("https://requestinspector.com/inspect/01gsd336hfdk6cgc9nk75tb3r0")
        });
        document.addEventListener("visibilitychange", () => {
            console.log("visibility change");
            navigator.sendBeacon("https://requestinspector.com/inspect/01gsd336hfdk6cgc9nk75tb3r0")
        });
            location.href= "http://google.com";
    </script>
</head>
<body>
<h1>Never injected</h1>
<img src="https://images.unsplash.com/photo-1675295952455-848b18698574?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=6000&q=80" />
</body>
</html>

````

**Describe the bug**
Firefox and webkit always deliver at least 2 or 3 beacons reliably to the server.
Chromium never sends a beacon.
I have opened this exact same page with real chrome, and it worked as it should, beacons arrived to the server every single time.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
