### ISSUE TITLE
[Question] How to chenge to a new open tab in browser

### ISSUE THREAD

**Issue by WallaceAnalista** [microsoft/playwright#20963]
I open a new tab in the browser and I would like to work in that tab, could someone help me how do I work in that new tab?

**Comment by Nav-2d** [comment]
You don't need to bring the page to front to make it active. You can just go ahead and do actions in the new tab.
https://playwright.dev/docs/pages#multiple-pages

**Comment by aslushnikov** [comment]
Closing as per great answer above.
