### ISSUE TITLE
[Feature] Add a command to automatically generated code to mock all API calls made during a test

### ISSUE THREAD

**Issue by mickael-h** [microsoft/playwright#20977]
Could be a parameter for the test/open command, or an extra command to generate it from a trace archive...
When you want to create an integration test for your front-end (i.e. mocking API calls), you need to copy the URL, method, status and response body of all the requests made during the test, write code to mock the specific URL, method and expected status, and put the response body in a JSON file.
When you have many requests in your tests, it's a very long, very tedious process that developers consider a chore and don't want to do.
It could, and arguably should be automated.

**Comment by aslushnikov** [comment]
There's also a video explaining how replay from har works: https://www.youtube.com/watch?v=NRGOV46P3kU&list=PLQ6Buerc008fTzmUIPkPo3Eis0vjx7ykn&index=6&t=129s

Hope this helps!

**Comment by mickael-h** [comment]
Mind. Blow. Thank you for this!
