### ISSUE TITLE
[QUESTION] Why is there duplicate `console.log()` output in Playwright tests?

### ISSUE THREAD

**Issue by Tenaria** [microsoft/playwright#20972]
**Context**
- Playwright Version: 1.30.0
- Operating System: macOS Monterey (version 12.6.3)
- Node.js version: 16.18.1
- Browser: Chromium - Version 110.0.5481.38 (Developer Build) (arm64)

**Code Snippet**
We have 3 files

bootstrap.spec.js
```
console.log("hello world");
require('./runtest.spec.js');
```

runtest.spec.js
```
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```

playwright.config.js
```
// @ts-check

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
    use: {
      headless: false,
      viewport: { width: 1280, height: 800 },
      ignoreHTTPSErrors: true,
      channel: 'chromium',
    },
  };

module.exports = config;
```

**Describe the bug**
Hi! I'm not sure if this is a bug or if I'm doing something silly but it appears that `console.log` output is duplicated to stdout and I can't seem to figure out why. It seems like Playwright might be doing some parsing/executing before it actually runs the tests and that's causing the `console.log` output to be sent/run twice. The output to stdout is as follows when running the command `npx playwright test bootstrap --config=playwright.config.js` from the terminal.

```
hello world

Running 1 test using 1 worker

hello world
  ✓  1 playwrightTest.spec.js:3:5 › has title (1.1s)

  1 passed (1.7s)
```

**Expected Output**
no duplicate `hello world` output on the first line.

```
Running 1 test using 1 worker

hello world
  ✓  1 playwrightTest.spec.js:3:5 › has title (1.1s)

  1 passed (1.7s)
```

**Comment by JoelEinbinder** [comment]
> It seems like Playwright might be doing some parsing/executing before it actually runs the tests and that's causing the console.log output to be sent/run twice.

This is correct. Playwright first requires all the tests to figure out how many there are and figure out how many worker threads it needs. Then it requires them again in the worker threads. So if you have top level logs outside your tests you will see them run twice. Or potentially more times if your tests require multiple workers per file.

**Comment by aslushnikov** [comment]
Closing as per great answer above!
