### ISSUE TITLE
[Feature] How to test web-application in 'headless = true' mode which uses 'camera' and 'microphone'. 

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#20982]
Hi,

My web-application is similar to Google-Meet / Zoom which uses 'Camera' and 'Microphone'. 

When I want test to be run for 'headless = false' case; I am able to achieve using below code:

`await context.grantPermissions(['camera', 'microphone']); `

But, I want to test the same in 'headless = true' mode in 'Chrome', 'Safari' and 'Firefox' browsers. 

Can you please help me here.

**Comment by aslushnikov** [comment]
@DeeptiSaxena09 I think headless chrome doesn't support this kind of permissions. You might have some success with the new chrome headless mode, see here how to enable it: https://playwright.dev/python/docs/next/chrome-extensions#headless-mode

If this doesn't work as well, then you'll need to file this upstream to chromium maintainers at https://crbug.com/new

Hope this helps!

**Comment by DeeptiSaxena09** [comment]
@aslushnikov Do you know if something is possible through below line of code, to use Camera and Microphones in headless mode?


`--use-fake-ui-for-media-stream - Provide fake media streams. Useful when running on CI servers.
--use-file-for-fake-audio-capture=<filename> - Provide a file to use when capturing audio.
--use-file-for-fake-video-capture=<filename> - Provide a file to use when capturing video.`

**Comment by DeeptiSaxena09** [comment]
Hi @aslushnikov Can you please respond to my previous query.

**Comment by aslushnikov** [comment]
@DeeptiSaxena09  I don't think any of these work in default headless mode. But again, some might work with the new headless mode i referred to.

**Comment by DeeptiSaxena09** [comment]
@aslushnikov Thank you sharing the document of new headless mode in playwright and helping me out here.

Added below the line of code which I found and is woking fine for Chromium browsers to test 'WebRTC' application (Camera and Mic access) in default headless mode.

```
test("test camera and mic in headless mode", async () => {
    const browser = await chromium.launch({
        args:['--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream','--use-file-for-fake-audio-capture=./data/audio.wav','--use-file-for-fake-video-capture=./data/akiyo_cif.y4m'],
    });
    const page = await browser.newPage();
    //perform actions.
    await browser.close();
    });
```
This might help someone else, who gets stuck in similar kind of problem.

Thanks!

**Comment by shubhm2303** [comment]
Hi @DeeptiSaxena09 I am stuck in similar kind of problem. I am trying to work with mic and camera in chrome headless browser.  But for me below lines of code aren't working. Do you find any alternative or more information on this?

```
ChromeOptions options = new ChromeOptions()

options.addArguments("--headless", "--disable-gpu", "--use-fake-ui-for-media-stream","--use-fake-device-for-media-stream")
				
driver = new ChromeDriver(options)
```

**Comment by mirao** [comment]
I can confirm the new headless mode in Chromium really fixes the issue for a camera.
If I test our application using a camera in the old headless mode, the page with camera fails with "Not supported". In the new headless mode camera works as expected.

If anyone wants to get it working in CodeceptJS (with Playwright), just add `--headless=new` to the `args` array of `chromium` in the Playwright helper setting.
