### ISSUE TITLE
[BUG] Cannot find module 'vite/package.json'

### ISSUE THREAD

**Issue by NazarYermolenko** [microsoft/playwright#20980]
**Context:**
- Playwright Version: [@playwright/experimental-ct-react": "^1.30.0, ]
- Operating System: [Linux]
- Node.js version: [16.8, 18.14.1]
(https://stackoverflow.com/questions/73885640/playwright-component-error-cannot-find-module-vite-package-json)]

**Comment by aslushnikov** [comment]
@NazarYermolenko can you please create a small github repo with some code & github action that demonstrates the error?

**Comment by aslushnikov** [comment]
Reading through your logs, your NPM configuration looks busted; we still would need a repro to reproduce this to be able to act upon it.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
