### ISSUE TITLE
I am not able to download browser binaries as my company has firewall and proxy.

### ISSUE THREAD

**Issue by Rizu15** [microsoft/playwright#20984]
I am not able to download browser binaries as my company has firewall and proxy.
I tried with 
I tried with below command 
set HTTPS_PROXY=https://192.0.2.1
mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"

But it didnt work and keeps giving below error 

[INFO] ------------------------< org.example:examples >------------------------
[INFO] Building Playwright Client Examples 0.1-SNAPSHOT
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- exec:3.1.0:java (default-cli) @ examples ---
Failed to install browsers
Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
Error: connect ECONNREFUSED 192.0.2.1:443
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by mark-wiemer** [comment]
Aside from working with your company to make an exception in this case, you can [skip the Chromium download with `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1`](https://playwright.dev/docs/browsers#skip-browser-downloads).

From there, you can [change the `channel` to test against regular browsers](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge)

**Comment by Rizu15** [comment]
I am writing script in JAVA , so how to skip this download ?

**Comment by mxschmitt** [comment]
You can set the environment variable as per above, then browsers don't get downloaded, see [here](https://playwright.dev/java/docs/browsers#skip-browser-downloads).

**Comment by Rizu15** [comment]
if i do that how to launch browser without downloading binaries, what is the solution

**Comment by yury-s** [comment]
One solution is to have a copy of the browsers served from an alternative location in your network as described in [this doc](https://playwright.dev/java/docs/browsers#download-from-artifact-repository).

Another option is download the browsers in a custom PLAYWRIGHT_BROWSERS_PATH  as described [here](https://playwright.dev/java/docs/browsers#managing-browser-binaries) on a machine that is not restricted by the firewall, then copy the directory to the machine where you want to run your tests.

You can also test against preinstalled Chrome and Edge as was suggested above by configuring a [channel](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge).

Does this work for  you?

**Comment by Rizu15** [comment]
I have set the playwrght skip browser downloand and placed copy of browser in ms-playwright folder.
But when i run the script it removes the browser and tries to download again.

[INFO] Running com.qa.dibe.tests.LoginTest
browser name is : chrome
Skipping browsers download because `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` env variable is set

Error after running test it tries to again download does not skip and also removes the places binaries in ms-playwright folder under appdata

browser name is : chrome
Removing unused browser at C:\Users\5488450\AppData\Local\ms-playwright\chromium-978106
Removing unused browser at C:\Users\5488450\AppData\Local\ms-playwright\firefox-1319
Removing unused browser at C:\Users\5488450\AppData\Local\ms-playwright\webkit-1616
Downloading Chromium 104.0.5112.48 (playwright build v1015)...
Downloading Chromium 104.0.5112.48 (playwright build v1015)...
Downloading Chromium 104.0.5112.48 (playwright build v1015)...
Failed to install browsers
Error: Failed to download Chromium 104.0.5112.48 (playwright build v1015), caused by
Error: connect ECONNREFUSED 72.21.81.200:443

Please suggest some quick solution i am stucked from 2 weeks.

**Comment by yury-s** [comment]
Your browser versions don't match playwright version, make sure you use the same playwright version to download the browser as the one which runs the tests. In the log above it should have been `C:\Users\5488450\AppData\Local\ms-playwright\chromium-1015` not `C:\Users\5488450\AppData\Local\ms-playwright\chromium-978106` (which is from some older version of playwright).

**Comment by Rizu15** [comment]
I have put updated C:\Users\5488450\AppData\Local\ms-playwright\chromium-1033 still same issue.
It has removed and then trying to dowload again.
Can you plz suggest , this is ongoing and i am lagging behind my deliverables.

**Comment by yury-s** [comment]
From the log above the chromium build version expected by playwright is 1015:
```
Downloading Chromium 104.0.5112.48 (playwright build v1015)...
```
whereas you added 1033. Which playwright versions did you use for downloading the browsers and which one to run the tests? What does the log say?

**Comment by yury-s** [comment]
I just tried on my mac with  playwright 1.28.0 and the following content of the cache:

```
~/Library/Caches/ms-playwright$ ls -la
total 0
drwxr-xr-x    6 user  staff   192 Feb 27 09:15 .
drwx------+ 113 user  staff  3616 Feb 27 09:15 ..
drwxr-xr-x    4 user  staff   128 Nov  3 16:54 chromium-1033
drwxr-xr-x    5 user  staff   160 Oct 21 12:59 ffmpeg-1008
drwxr-xr-x    4 user  staff   128 Nov  4 12:41 firefox-1364
drwxr-xr-x   16 user  staff   512 Nov  1 10:03 webkit-1735
```
This is the output I got:
```
~/sandbox/playwright-java/examples(main)$ DEBUG=pw:install mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install"
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------------< org.example:examples >------------------------
[INFO] Building Playwright Client Examples 1.30.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.1.0:java (default-cli) @ examples ---
2023-02-27T17:17:19.549Z pw:install created DriverJar: /var/folders/t3/_mbh6z155sz1cr7prkpn9lsh0000gn/T/playwright-java-1984296274065687453
2023-02-27T17:17:19.551Z pw:install initializing driver
2023-02-27T17:17:20.262Z pw:install extracted driver from jar to /var/folders/t3/_mbh6z155sz1cr7prkpn9lsh0000gn/T/playwright-java-1984296274065687453/playwright.sh
2023-02-27T17:17:20.262Z pw:install driver initialized.
  pw:install Chromium 108.0.5359.29 (playwright build v1033) is already downloaded. +0ms
  pw:install FFMPEG playwright build v1008 is already downloaded. +4ms
  pw:install Firefox 106.0 (playwright build v1364) is already downloaded. +1ms
  pw:install Webkit 16.4 (playwright build v1735) is already downloaded. +3ms

```

**Comment by yury-s** [comment]
We need more information to act on this report. If the [advice above](https://github.com/microsoft/playwright/issues/20984#issuecomment-1446713467) doesn't help, please file a new report and link to this issue when you get back to it!
