### ISSUE TITLE
[BUG] Unable to fill stripejs fields wrapped in iframe (firefox)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#20999]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 14
- Browser: Firefox only

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await page
    .locator('#card-number iframe')
    .getByPlaceholder('0000 0000 0000 0000')
    .fill('4242424242424242');
```

**Describe the bug**
Hi, I have been facing an intermittent problem with Stripe payment page in Firefox. I have some automation tests which basically fills in the credit card details but 3 out of 10 times on Firefox, the credit card details are enabled and interactable (I have confirmed this manually). The PW is unable to find the locator for some reason. I have attached the screenshots which shows that the DOM has the same structure as my locator.  Any help or pointers appreciated.

<img width="641" alt="Screen Shot 2023-02-17 at 11 36 28 AM" src="https://user-images.githubusercontent.com/22205721/219783160-12049491-cebc-48fc-b4bf-a00bc9202dd3.png">
<img width="1397" alt="Screen Shot 2023-02-17 at 11 36 15 AM" src="https://user-images.githubusercontent.com/22205721/219783180-8baf7f7e-35cd-43eb-8f18-993331ff9e26.png">

Additional Info:
This is happening for last idk maybe 3+ months and same on other PW versions.
I was able to reproduce this locally using `--debug` as well everytime and with 100% failure rate
Unfortunately not able to share the code but can do screenshare to help debug

Logs using pw:api
```
pw:api <= locator.click succeeded +26ms
  pw:api => locator.fill started +2ms
  pw:api waiting for getByPlaceholder('First and last name') +20ms
  pw:api   locator resolved to <input class="input" id="name-on-card" value="Jenna Fri…/> +17ms
  pw:api elementHandle.fill("Laura Crooks") +1ms
  pw:api   waiting for element to be visible, enabled and editable +4ms
  pw:api   element is visible, enabled and editable +8ms
  pw:api <= locator.fill succeeded +8ms
  pw:api => locator.fill started +1ms
  pw:api waiting for frameLocator('#card-number iframe').getByPlaceholder('0000 0000 0000 0000') +8ms
  pw:api   "networkidle" event fired +406ms
```

**Comment by Nav-2d** [comment]
Hello, any thoughts on this one? I can also send the trace privately if that helps.

**Comment by yury-s** [comment]
Please send traces to the email in my profile. Also, what is the error message, is it just timing out waiting for an element with given placeholder?

**Comment by Nav-2d** [comment]
I sent the trace and a video to your email (gdrive link). It just times out waiting for element with given placeholder.

**Comment by yury-s** [comment]
I tried looked at the trace file you sent but unfortunately the placeholder information is not saved in there (the frame __privateStripeFrame0356 is empty) and we cannot tell much based on the trace. If the log says that the action timed out waiting for the locator, the element is not there (perhaps the page is served with different content once in a while). Did you try using codegen to see what locator it suggests for the element?  We'll need an actual repro to help with this.

**Comment by Nav-2d** [comment]
Thanks for looking into this. Using codegen I get the following locator:

```js
await page.frameLocator('iframe[name="__privateStripeFrame8186"]').getByPlaceholder('0000 0000 0000 0000').click();
await page.frameLocator('iframe[name="__privateStripeFrame8186"]').getByPlaceholder('0000 0000 0000 0000').fill('4242 4424 4242 4242');
```

**Comment by yury-s** [comment]
Looks legit, but it may well be a bug in the codegen or a race condition. Unfortunately we cannot act on this without a repro. Closing this bug, feel free to file a new one with a reproducible example if you can extract one from your code and share with us.
