### ISSUE TITLE
[BUG] [CT] react-resize-detector throws `Identifier 'React' has already been declared`

### ISSUE THREAD

**Issue by cscheffauer** [microsoft/playwright#20990]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.10
- Browser: Chromium

Using the [react-resize-detector](https://www.npmjs.com/package/react-resize-detector) library in Playwright Component Tests (React) throws a `[commonjs] Identifier 'React' has already been declared (2:10)` error.

This might be somehow related to:
https://github.com/microsoft/playwright/issues/15351

**Repro**

https://github.com/cscheffauer/ct-129-resize-detector-repro

Clone the repo
npm ci
npm run test-ct
See the `[commonjs] Identifier 'React' has already been declared (2:10)` error in console

**Comment by sand4rt** [comment]
@cscheffauer it seems to be a problem on their end. It should be resolved then this one is merged:  https://github.com/maslianok/react-resize-detector/pull/232.

**Comment by cscheffauer** [comment]
@sand4rt brilliant! thanks for the hint - it is building now fine 🙏🏻
