### ISSUE TITLE
[Question] How can I extract text from the element?

### ISSUE THREAD

**Issue by Castertroy911** [microsoft/playwright#21007]
Hello everyone
I hsve a question. If I have a tag <h4>Test text</h4>. Is it possible to extract "Test text" with the help of Playwright?

**Comment by sand4rt** [comment]
@Castertroy911 there is a `textContent()` function on `Locator`:

`const text = await component.getByText('Test text').textContent();`

But you probably want to do something like this?:

```typescript
test('boop', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByText('Test text')).toBeVisible();
});
```

**Comment by Castertroy911** [comment]
> @Castertroy911 there is a `textContent()` function on `Locator`:
> 
> `const text = await component.getByText('Test text').textContent();`
> 
> But you probably want to do something like this?:
> 
> ```ts
> test('boop', async ({ page }) => {
>   await page.goto('/');
>   await expect(page.getByText('Test text')).toBeVisible();
> });
> ```

@sand4rt Thank you so much. 
No actually I just want to check is any text cantains in one tag. I tested adding Notes to the documents and I just need to ensure, that it was successfully added

**Comment by yury-s** [comment]
You may find [toHaveText](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text) useful in that case.

Closing per the response above and this one, feel free to open a new issue if it doesn't work.
