### ISSUE TITLE
[BUG] launchPersistentContext doesn't work with Edge default userDataDir

### ISSUE THREAD

**Issue by mark-wiemer** [microsoft/playwright#21019]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Windows
- Node.js version: 18.14.1
- Browser: Edge

<details><summary>Additional context</summary>

`npx envinfo --preset playwright --markdown`:

## System:
 - OS: Windows 10 10.0.22621
 - Memory: 7.81 GB / 15.95 GB
## Binaries:
 - Node: 18.14.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.19 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 9.4.0 - C:\Program Files\nodejs\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE
## npmPackages:
 - playwright: ^1.30.0 => 1.30.0
 
 </details>

**Code Snippet**

```javascript
var import_playwright = require("playwright");
(async () => {
  const context1 = await import_playwright.chromium.launchPersistentContext(
    "C:\\Users\\markw\\AppData\\Local\\Microsoft\\Edge\\User Data",
    {
      args: ["--remote-debugging-port=9222"],
      headless: false,
      userAgent: "TestUser",
      channel: "msedge"
    }
  );
  const pageOne = context1.pages()[0];
  await pageOne.goto("https://example.com");
})();
```

**Describe the bug**

The snippet is supposed to open a new page in Edge that navigates to `example.com`, but instead the page is stuck on `about:blank`. If an existing Edge window is open, it adds a new `about:blank` tab to that window. In any case, closing the browser does not kill the Node process. Vice versa, killing the Node process does not close the new browser.

This snippet works as expected if the first arg of `launchPersistentContext` is the empty string `launchPersistentContext('', ...)`. In that case, Edge opens a new browser and navigation works correctly. Closing the new browser kills the Node process and vice versa.

The snippet also works with the Chrome `userDataDir` (`'C:\\Users\\markw\\AppData\\Local\\Google\\Chrome\\User Data'`).

**Comment by yury-s** [comment]
You most likely have another instance of Edge running which uses the same user data dir. Edge (and other Chromium based browsers) won't allow multiple instances to share same user profile data and will reuse existing browser. Playwright expects that it fully controls the browser. To ensure that, pass a unique user data directory which is guaranteed not to be used by anyone else. Please let us know if it helps.

**Comment by mark-wiemer** [comment]
Yes, thank you. I was careful to close all Edge windows, but of course it still runs in the background. Closing the background processes through Task Manager resolved the issue.

**Comment by jakenuts** [comment]
Any way to allow running as the same user, for a browser automation assistant "take the wheel" sort of thing?

**Comment by mark-wiemer** [comment]
@jakenuts I would create a new issue, maybe linking this one, I doubt maintainers check on closed issues too much. And to address your question, I don't know, but I'd go about it by just opening the browser in Playwright mode from the start and choosing not to run Playwright until certain other commands have been sent. Personally I manage Playwright processes through AutoHotkey.
