### ISSUE TITLE
[Question] Does Playwright Report tool is relevant to Java?

### ISSUE THREAD

**Issue by Dassy-Shtigel** [microsoft/playwright#21015]

**Comment by mxschmitt** [comment]
What do you mean by Playwright Report tool?

**Comment by Dassy-Shtigel** [comment]
yes that what I meant, 
generally, it looks like java is less supported than other languages, why?

**Comment by aslushnikov** [comment]
@Dassy-Shtigel Playwright Library comes for a variety of language ecosystems: Node.js, Java, .NET & Python. In all of these languages, the support for the browser automation is pretty much the same.

In Node.js, however, we also ship Playwright Test - our own test runner, designed specifically for web testing. Reporters are a part of this test runner.

In other language ecosystems, we rely on their test runners. In case of Java, this is JUnit: https://playwright.dev/java/docs/test-runners

Hope this clears some confusion!

**Comment by Dassy-Shtigel** [comment]
ok, thanks
