### ISSUE TITLE
[BUG] How to enable Camera and Microphone when running scripts in headless mode in google-chrome.

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#21025]
Hi Team,

Can you help me with the test scenario where my website uses 'Camera' and 'Microphone' access. To  run the same in headleass mode, how can I achieve it?

https://webrtc.org/getting-started/testing is providing some solution, But I am not sure how to implement the same in Playwright.

Please help here.

**Comment by yury-s** [comment]
Headless chrome doesn't support this kind of permissions. You might have some success with the new chrome headless mode, see here how to enable it: https://playwright.dev/python/docs/next/chrome-extensions#headless-mode

See also comments in the similar issue: https://github.com/microsoft/playwright/issues/20982.

**Comment by MuzammilCareaxiom** [comment]
Check this:
https://stackoverflow.com/questions/71462024/how-to-handle-chromium-microphone-permission-pop-ups-in-playwright
Works for me!
