### ISSUE TITLE
[BUG] Can't seem to have .toHaveURL(...) at the end of a test

### ISSUE THREAD

**Issue by DominicGBauer** [microsoft/playwright#21021]
**Context:**
## System:
 - OS: macOS 13.1
 - Memory: 434.23 MB / 32.00 GB
## Binaries:
 - Node: 16.18.1 - ~/.asdf/installs/nodejs/lts-gallium/bin/node
 - Yarn: 1.22.19 - ~/Desktop/projects/nomanini-dashboard-v4/node_modules/.bin/yarn
 - npm: 8.19.2 - ~/.asdf/plugins/nodejs/shims/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash
## Version
- "@playwright/test": "^1.30.0",

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test, expect } from '@playwright/test'

test('it shows auth screen', async ({ page }) => {
  await page.goto('https://stanbiczm-dev.nomanini.com/auth/login')
  expect(page).toHaveURL(/auth/)
})
```

**Describe the bug**

Results in this error 
```
expect.toHaveURL: Browser has been closed


Failed worker ran 1 test:
[chromium] › e2e/loginAndOut.test.ts:32:5 › it shows auth screen
    at e2e/loginAndOut.test.ts:34:16
```

But when I add something after `.toHaveURL` e.g. 
```javascript
test('it shows auth screen', async ({ page }) => {
  await page.goto('https://stanbiczm-dev.nomanini.com/auth/login')
  expect(page).toHaveURL(/auth/)

  await page.getByLabel('Username').click()
  await page.getByLabel('Username').fill('test')
})
```

Then there is no error

**Comment by MindaugasMateika** [comment]
You're missing an await, `.toHaveURL` is an async assertion

https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-url

**Comment by DominicGBauer** [comment]
@MindaugasMateika oh my word! Thanks so much, sorry about that!
