### ISSUE TITLE
[BUG] API Testing. Large volume of data gives: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by reinhartbuit** [microsoft/playwright#21024]
Context:

Playwright Version: 1.30.0
Operating System: Windows 10
Node.js version: v18.14.1
Browser: None - API Testing
Extra: N/A

Hi,

I am currently doing functional API Testing. I am importing a large data (700,000+ records) set from a .csv file and I am calling the same API for each of the records in the csv file using a for loop.

Unfortunately, when running the tests, I get an error: "RangeError: Maximum call stack size exceeded"
When running it with 100,000 records the tests kicks-off successfully without an issue.

Is there a way I can resolve this issue?
My last resort will be to run the test 100,000 records at a time, but that is not ideal.

Thanks for the assistance

Code Snippet
```
const records = parse(fs.readFileSync(path.join(config.testdata_csv_path)), {
  columns: true,
  // from: 1, //start from row
  // to: 5, //end at row
  skip_empty_lines: true,
});

for (const record of records) {
  //iterate the csv data set
  const username = record.usernames;
  const password = record.password;
  let accesstoken;
  let accountIndexes = [];

  test(`Password Check for : ${record.usernames}`, async ({ request }) => {
    //Fetch Tokens
    await test.step('1. Fetch Access Token', async () => {
      const auth_response = await common.getAuth(request, username, password); //call idp get access token
      expect(auth_response).toBeOK();
      const auth_response_body = await auth_response.json();
      accesstoken = auth_response_body.access_token;

      console.log(accesstoken);
    });
  });
}

```
Error:

![image](https://user-images.githubusercontent.com/3745813/220064371-8fda4a70-f561-4056-830b-af5280e30261.png)

**Comment by yury-s** [comment]
Can it be that the error is thrown from the parse function or somewhere else in the client code?

I don't see any recursion in createTestGroups, also I tried this code and it runs fine:

```js
import { test, expect } from "@playwright/test";

for (let i = 0; i < 1_000_000; i++) {
test(`Password Check #${i}`, async ({ request }) => {
    //Fetch Tokens
    await test.step('1. Fetch Access Token', async () => {
    console.log('step ' + i);
    });
});
} 
```

Any chance you can share a complete repro? If not, can you try reduce the example to something that works with a long loop instead of reading from file?

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one when you get back to it.
