### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lakshbhutani1** [microsoft/playwright#21039]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Mac
- Node.js version: `v16.14.0`
- Browser: Chromium

When using **const browser = await chromium.launch({headless: true});** , in globalSetup file playwright is unable to save cookies in storageState file but with  **const browser = await chromium.launch();** , it is able to save all cookies in storageState. 

Let me know what can be the issue?

**Comment by mxschmitt** [comment]
Usually the website behaves then differently and has e.g. a bot protection. You could enable tracing to find out whats the difference.

**Comment by yury-s** [comment]
Closing per the response above. We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.
