### ISSUE TITLE
access dynamic typing inference through fixtures & custom TestFuntions/TestTypes

### ISSUE THREAD

**Issue by dasdeck** [microsoft/playwright#21041]
edit: 
Forgot to say: I absolutely love playwright! Great software, thanks for creating it!

I'd like to have dynamic types accessible in my test through fixtures to have strong autocompletions for testers inside the test.
Currently, if I use a dynamic type in my `test.use()` clause, the evaluated template dynamic can not carry over to the fixtures in the `test`:

types

```ts
// the dynamic user list
type UserList = {
    [key: string]: string;
}

type Session = {
    user: User;
}

// a list of sessions that should infer from the user list
type SessionList<T> = {
    [key in keyof T]: Session
}


```
type inference behavior I'm after

```ts
const users = {
    user1: 'max',
    user2: 'john'
};

function createSessions<T extends UserList, S extends SessionList<T>>(users: T): S {

    // exemplary mapping, in reality this would be more sophisticated
    const sessions: S = {}
    for (const user in users) {
        sessions[user] = { user: users[user]};
    }
    return sessions as S;
}


const autoCompletingSessions = createSessions(users);
autoCompletingSessions.user1;
// this will autocomplete my available sessions
```

current state of playwright (does not work):

```ts

// the resulting fixture
type Fixture<T extends UserList> = {
    users: T;
    sessions: SessionList<T>;
}

const test = base.extend<Fixture<UserList>>({
    users: [{}, {option: true}],
    sessions: ({users}, use) => {
        use(createSessions(users))
    }
});

test.use({
    users,
});

test('claim a pipette', async ({sessions}) => {

    sessions.
    // this wont autocomplete, I guess since the type is set in test.use(), a complete different call,
    // typescript can not infer the user list for the delivered fixture

});
```

**solution 1**
offer custom TestFunctions/TestTypes 
(this would greatly increase the possibilities to customize test structures)
this could work with `describe` function too (which are AFAIK just TestFunctions?)

```ts
/**
 * this would be the playwright wrapper that makes the function into a TestFunction/TestType
 * @param callback 
 * @returns 
 */
function createCustomTestType<T extends Function>(callback: T): T {
    return callback;
}

// usage:

function myCustomTest<T extends UserList>(setup: Partial<Fixture<T>>, title: string, callback: (props: Fixture<T>) => void): void {
    test.use(setup);
    test(title, callback as any);
};

const myTest = createCustomTestType(myCustomTest);

myTest({ users }, 'test my users', ({sessions}) => {
    sessions.user1
    // sessions can autocomplete, but playwright does not currently recognize custom tests though
});
```

**solution 2**
return a stronger typed test object from the `test.use` function:
from this chaining it should be possible to infer the types 
as you could decrease the type range for the return type of the use function

```ts
test.use({users}).test('claim a pipette', async ({sessions}) => {

    sessions.
    // borken code

});
```

The proposed solutions could fix all kinds of issues not even related to this request.
I might look into it myself, but I'm afraid the code base is a bit over my head at the moment.

**Comment by layerkugou** [comment]
good

**Comment by yury-s** [comment]
There are no plans to support template fixtures, you need to either extend base test with concrete fixture types as you described or do manual cast.

Closing this request as we have no plans to support that.
