### ISSUE TITLE
[BUG] Click leading to navigation uses the non-navigation timeout

### ISSUE THREAD

**Issue by jfp1992** [microsoft/playwright#21047]
**Context:**
- Playwright Version: 1.30
- Operating System: Windows
- Python version: 3.10
- Browser: Any

**Describe the bug**
Given the below settings for timeouts
```
context.set_default_timeout(5000)
context.set_default_navigation_timeout(30000)
```

Using a page.goto(url) will use the 30 second timeout
Clicking an element will use the 5 second timeout

Unless:
Clicking an element that triggers a navigation will timeout if the page takes more than 5 seconds to load instead of 30.

Shouldn't the internal navigation auto wait use the default navigation timeout and not the default timeout?

**Comment by yury-s** [comment]
Navigation is just a part of the action, so the [default timeout](https://playwright.dev/python/docs/api/class-browsercontext#browser-context-set-default-timeout) still applies to the click action. Changing navigation timeout will only affect the maximum timeout for the navigation (even if it's inside an action).
