### ISSUE TITLE
Codegen generates locator that violates strict mode (filter chaining problem?)

### ISSUE THREAD

**Issue by KenjiTakahashi** [microsoft/playwright#21043]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 16.19
- Browser: Chromium (but likely affects other as well)

**Describe the bug**

Here is a result from running a test with codegen generated locators [potentially sensitive details stripped]:
```
    locator.click: Error: strict mode violation: locator('div').filter({ hasText: 'snip1' }).getByRole('link') resolved to 6 elements:
        1) <a href="/">…</a> aka locator('div').filter({ hasText: 'snip2' }).getByRole('link')
        2) <a href="snip3">snip4</a> aka getByRole('link', { name: 'snip4' })
        3) <a href="snip5" class="customiz…>snip6</a> aka getByRole('link', { name: 'snip6' })
        4) <a href="snip7…>…</a> aka locator('div').filter({ hasText: 'snip1' }).getByRole('link')
        5) <a href="snip8…>…</a> aka getByRole('link', { name: 'snip9' })
        6) <a href="snip10…>…</a> aka getByRole('link', { name: 'snip11' })
```

See how the 4th suggestion is actually literally the locator that triggers the error. And it does look reasonable to me (knowing the contents of the page).
So I think it might be something wrong with how the calls are chained together?

**Comment by yury-s** [comment]
Can you share the page where the error happens along with the locator that is causing the trouble? We need to be able to reproduce this locally to act on it.

**Comment by KenjiTakahashi** [comment]
Sorry, the application is internal, cannot share it unfortunately.
The locator is exactly like stated in the error:
```js
await page.locator("div").filter({ hasText: "snip1" }).getByRole("link").click();
```
For now I have worked around it by adding `.nth(3)` at the end, but it shouldn't be necessary (as per the error message suggestion itself).

I'll see if I can create some sample page that causes the error when I got time.

**Comment by yury-s** [comment]
If you don't want to shared it publicly feel free to send it to the email in my profile. If you can share a trace file of the test we can try to reproduce with that.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
