### ISSUE TITLE
Ubuntu 20.04.5 LTS cannot resolve  Host system is missing a few dependencies to run browsers

### ISSUE THREAD

**Issue by davthorne** [microsoft/playwright#21060]
- Playwright Version: ^1.19.0
- Operating System: WSL2 Ubuntu 20.045 LTS
- Node.js version: 18.14.1
- Browser: Chromium,

Running  a node script from my package.json file

 "test": "./node_modules/.bin/cucumber-js --require cucumber.js --require step-definitions/**/*.js ",

npm run test

I get the error:
 Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-dep

Runing the command
sudo npx playwright install-dep

Installing Ubuntu dependencies...
Switching to root user to install dependencies...
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]                     
Hit:3 https://deb.nodesource.com/node_18.x focal InRelease
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Reading package lists... Done
E: Release file for http://archive.ubuntu.com/ubuntu/dists/focal-updates/InRelease is not valid yet (invalid for another 13h 38min 40s). Updates for this repository will not be applied.
E: Release file for http://archive.ubuntu.com/ubuntu/dists/focal-backports/InRelease is not valid yet (invalid for another 11h 35min 37s). Updates for this repository will not be applied.
E: Release file for http://security.ubuntu.com/ubuntu/dists/focal-security/InRelease is not valid yet (invalid for another 11h 32min 51s). Updates for this repository will not be applied.

I re-run 
npm run  test

I see the same error 
 Host system is missing a few dependencies to run browsers. ║
║ Please install them with the following command:            ║
║                                                            ║
║     sudo npx playwright install-dep

Could you please explain why this is happening ?

**Comment by mxschmitt** [comment]
Your system clock is mismatched, make sure the time is configured correctly, hence apt-get update is not working. See e.g. [this](https://www.atlantic.net/vps-hosting/how-to-set-up-time-synchronization-with-ntp-on-ubuntu-18-04/) guide.

**Comment by davthorne** [comment]
Thanks you suggestion seems to have resolved this issue.
