### ISSUE TITLE
codegen not identifying iframe and clicks on iframe elements are not recorded

### ISSUE THREAD

**Issue by HinaSharma16** [microsoft/playwright#21069]
I am on MacOS Monterey.  I have installed Playwright and am trying to record steps through codegen by executing actions on a application. 
Sadly, login to app goes fine, but when I land on a page with iframe the codegen inspector stops recording the clicks and is not able to identify elements in the iframe. 

Question : which setting on my Mac might be causing this?  How do I debug this issue?

**Comment by yury-s** [comment]
It might be a bug in the codegen, you should not need to change any macOS settings to make it work. We cannot tell much why it's not working without seeing the actual example. Please share the site where this happens with the instructions how to reproduce it. If there is any sensitive information that you don't want to share publicly feel free to send it to the email in my profile.

**Comment by HinaSharma16** [comment]
Thanks a lot Yury for the response.
Would it be possible for you to get over a zoom call/webex where I can show
the issue live.

**Comment by jkohlin** [comment]
I got the same problem. Playwright is selecting an iframe using the `[data-test-id="cf-widget-renderer"]` as selector. 
The problem I guess is that all iframes have that same data-attribute and it seems to select the last one.

**Comment by yury-s** [comment]
> Would it be possible for you to get over a zoom call/webex where I can show the issue live.

We don't have bandwidth for live support. Please share a repro, so that we can try it locally.

> I got the same problem. Playwright is selecting an iframe using the [data-test-id="cf-widget-renderer"] as selector.
The problem I guess is that all iframes have that same data-attribute and it seems to select the last one.

We need to be able to reproduce the problem to make this actionable. Could you share a reproducible example?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
