### ISSUE TITLE
Customize html reporter

### ISSUE THREAD

**Issue by Ashasian** [microsoft/playwright#21063]
<img width="1056" alt="image" src="https://user-images.githubusercontent.com/110240656/220382923-ccfac00b-aba4-487e-ae6e-68e4c540b62f.png">

How to customize the keyword "All" here , so that when i run tests which are running inside the test.describe is taken as a single testcase 

```
test.describe
  .serial(`${tag} - Check the login functionality works for a user with a customer role and correct password`, function () {
 
 
  test("Open application", async () => {
    await loginPO.goToLoginScreen();
    expect(
      await loginPO.checkLoginScreenIsDisplayed(),
      "Login screen is displayed"
    ).toBe(true);
  });

  test("Login into the application with a user with customer role", async () => {
    await loginPO.login(user.email, user.pass);
    expect(
      await contractsPO.checkContractsScreenIsDisplayed(),
      "Contracts Screen is displayed"
    ).toBeTruthy;
  });

  test("Logout of the application", async () => {
    await profilePO.logout();
    expect(await loginPO.checkLogoutIsDone(), "Logout is done properly")
      .toBeTruthy;
  });
});
```

Here this should be taken as a single test instead of 3 tests in "All" inside html reporter

**Comment by MindaugasMateika** [comment]
Why not make those as test steps in one test instead? Making 3 tests and then trying to make a single test in report seems counter intuitive.

**Comment by yury-s** [comment]
Closing per the response above. Test case is the basic concept of the reporter and our test runner. If you want combine multiple test cases into a single test and still see them separately in the html reporter the only way to achieve that today is to convert the tests into steps.
