### ISSUE TITLE
https://playwright.dev 404

### ISSUE THREAD

**Issue by grant** [microsoft/playwright#21071]
**Describe the bug**

The website linked in the repo does not work.

https://playwright.dev

<img width="631" alt="Screen Shot 2023-02-21 at 11 42 53" src="https://user-images.githubusercontent.com/744973/220443408-21aaa062-01b1-416c-ba33-5be5f2a6cb9f.png">

<img width="328" alt="Screen Shot 2023-02-21 at 11 46 27" src="https://user-images.githubusercontent.com/744973/220443590-1f98f954-c95b-4da1-aff9-5c08710536d9.png">

**Comment by aslushnikov** [comment]
Sorry for the inconvenience! We're aware and fixing it right now.

**Comment by aslushnikov** [comment]
Seems to be back online. Thank you for the heads-up!

**Comment by grant** [comment]
Verified 👍🏻
