### ISSUE TITLE
[Regression v1.31] Headless Windows shows cascading cmd windows

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#21093]
Bisect range: https://chromium.googlesource.com/chromium/src/+log/1e1ca9b6374e4efd3bbc90a9f4fee2e7719462c3..6717b2ccc50fb0773d15964d8acfb64b160b72a9

Culprit https://chromium.googlesource.com/chromium/src/+/32310f7d99e0b263a7a4d772800add8107929d6e

Reverting to 1047 fixes the issue

https://bugs.chromium.org/p/chromium/issues/detail?id=1418256 - upstream issue

**Comment by ChaosEngine** [comment]
Yup, very nasty experience nevertheless all tests passes
![image](https://user-images.githubusercontent.com/1271428/220606294-ded4f63e-bca9-46f8-8a5c-070ba066a611.png)

**Comment by aslushnikov** [comment]
This is fixed in 1.31.1; I'll keep this open to track upstream fix.

**Comment by aslushnikov** [comment]
This is fixed upstream in Chromium as well. Closing.
