### ISSUE TITLE
Unable to scroll thru the table

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#21098]
I have a table with several rows (300+) and with the scroll bar can you please clarify how to scroll the page using playwright? the table load the records as user scrolls the page, and when the scrolling is done all the way to bottom of the table, it loads all the rows in the table. Is there a way in playwright testing library to scroll down till the end of the table ?

Before scrolling, the table shows only certain number of rows, and all other records are invisible, so when we search for something from invisible rows from the table, it is not able to find, eg: 1234 is the employee no that i want to search , however it is at the bottom of table, so when i run the following code, it says it is unable to find.

Can you please advise whether i should scroll each time and search for the order no if so can you please tell me how i can scroll thru the table using playwright /playwright dom?

and how to make sure in playwright that i scroll thru all the very to bottom of the table?

note: it is infinite scroll where we the table loads certain no of rows as user scroll thru the page . and user can not scroll any further after all rows are loaded.

The table screenshot is attached below.
<img width="1536" alt="Screen Shot 2023-02-22 at 5 16 33 AM" src="https://user-images.githubusercontent.com/113629123/220611225-2ac9a47b-cdfd-4aaa-b2ae-2fe1753ced16.png">
<img width="1536" alt="Screen Shot 2023-02-22 at 5 21 42 AM" src="https://user-images.githubusercontent.com/113629123/220611255-8399a749-86ef-480e-a157-3a0dbf6cefef.png">

**Comment by yury-s** [comment]
> Can you please advise whether i should scroll each time and search for the order no if so can you please tell me how i can scroll thru the table using playwright /playwright dom?

Yes, you can use either window.scroll()/window.scrollBy()/element.scroll()/[element.scrollBy()](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy) or [`mouse.wheel()`](https://playwright.dev/docs/api/class-mouse#mouse-wheel) to make the lazily loaded elements appear in the viewport. 


> and how to make sure in playwright that i scroll thru all the very to bottom of the table?

This code (or similar with scrollBy) should work if you just need to scroll to the very end of the element:

```ts
await page.locator('#yourtable').evaluate(e => e.scrollTop=e.scrollHeight);
```

Unfortunately, there is no universal solution when dealing with lazy viewport elements, so you need to scroll manually and wait for the element to be populated. Does it work for you?

**Comment by InduKrish** [comment]
here in my case, i dont know in advance what is going to be the last element of the table, will the below code still work? what should be locator that I should be using in my case, as i dont know what the last element of the table is going to be.

await page.locator('#yourtable').evaluate(e => e.scrollTop=e.scrollHeight);

**Comment by yury-s** [comment]
> window.scroll() --> do i have to mention viewport dimension like this? window.scroll(0,document.body.scrollHeight) can you please confirm?

Only if the table takes full page. Otherwise you can use `element.scrollHeight` to get current scrollable height of the element and scroll to the very end right away. Note thought that if the list is dynamic it might also change as you scroll. In that case you may need to repeat the step.

> here in my case, i dont know in advance what is going to be the last element of the table, will the below code still work? what should be locator that I should be using in my case, as i dont know what the last element of the table is going to be.

You may need to repeat this step several times until you know that "the last" element is visible in the viewport. It's up to you and your app to define how you determine what is the last element and if it's visible. 

> await page.locator('#yourtable').evaluate(e => e.scrollTop=e.scrollHeight); --> can you please explain what it is doing exactly here, wondering why we are verifying if scrollTop equals scrollHeight.

This is an assignment not comparison. So we basically tell the container to scroll it's content to the very end of its current scrollable height. I recommend you read about the scroll Web APIs as it is not specific to playwright.

If something doesn't work for you please share an example of the page and the code that is not working so that we can run it locally and assist you further.
