### ISSUE TITLE
[Question] Fail to remove an event listener in an external function

### ISSUE THREAD

**Issue by joychester** [microsoft/playwright#21091]
I am wondering if there is any special on the following code, I was trying to understand why it fails to remove the event listener through an imported function (i know it is weird to create extra functions like this, but just want to know why):
```
const { test, expect } = require('@playwright/test');
const { dummyListener_on, dummyListener_off  }  = require('../utils/listener_helper');

test('external listener test', async ({ page }) => {
  // turn on the request event listener
  dummyListener_on(page);

  await page.goto('https://playwright.dev/');
  await expect(page).toHaveTitle(/Playwright/);

  // turn off the request event listener
  dummyListener_off(page);

  console.log("event listener should be removed...hmm, Actually Not");

  await page.waitForTimeout(2000);
  await page.getByRole('link', { name: 'Get started' }).click();
  await expect(page).toHaveURL(/.*intro/);
});
```

in listener_helper.js , just simply define the event listener as following:
```
function dummyListener_on(page) {
    page.on("requestfinished", request => console.log(`Request finished: ${request.url()}`));
}

function dummyListener_off(page) {
    page.off("requestfinished", request => console.log(`Request finished: ${request.url()}`));
}

export {dummyListener_on, dummyListener_off}
```

Please help, Thank you in advance!

**Comment by mxschmitt** [comment]
If you do the following:

```ts
request => console.log(`Request finished: ${request.url()}`)
```

JavaScript will internally always create a new function all the time. (its an arrow function). So when you call page.off it internally tries to remove this reference of the new function, sees that there is none and does nothing else. What you want instead is either define the handler a function outside or as a class property when you are using classes. See the following example:

```ts
function myHandler() {
 ...
}
page.on("requestfinished", myHandler)
....
page.off("requestfinished", myHandler);
```

**Comment by joychester** [comment]
@mxschmitt  => Thank you for your insights! :)
