### ISSUE TITLE
[BUG?] font-feature-settings are overridden on buttons in Chrome 111 (1.31.0)

### ISSUE THREAD

**Issue by SteffenDE** [microsoft/playwright#21102]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Linux
- Node.js version: 16.19.0
- Browser: Chromium
- Extra: works in 1.30.0

```
## System:
 - OS: Linux 5.15 Ubuntu 20.04.5 LTS (Focal Fossa)
 - Memory: 5.42 GB / 7.75 GB
 - Container: Yes
## Binaries:
 - Node: 16.19.0 - /usr/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 8.19.3 - /usr/bin/npm
## Languages:
 - Bash: 5.0.17 - /usr/bin/bash
```

I've got a page that is using a custom `font-feature-settings` css rule that is suddenly overridden in Chromium 111. I'm not sure if that's a Chromium or Playwright issue. See the attached screenshots:

![Pasted Graphic](https://user-images.githubusercontent.com/4116351/220624695-825bc5b6-6da3-407f-ba43-23bea3b1b818.png)
![Pasted Graphic 1](https://user-images.githubusercontent.com/4116351/220624762-98bfa04f-5d64-4f1b-b362-a4745930af36.png)
![Pasted Graphic 2](https://user-images.githubusercontent.com/4116351/220624779-389ffc2b-d499-4d16-9bd2-634e2b66b3ce.png)

This leads to failing screenshot comparisons, as some font settings are rendered differently.
It works as expected using Playwright 1.30.0 (Chromium 110). I looked at the user agent stylesheet in the Chromium main branch, but did not find a rule that would override the font-feature-settings property: https://chromium.googlesource.com/chromium/blink/+/master/Source/core/css/html.css

Can you advise if this is a Chromium or Playwright bug? (Maybe it's also intended behavior, but I don't think so).

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Could you share a reduced reproducible example which we could run locally (both page and the test) ?

**Comment by SteffenDE** [comment]
In a new folder:

`demo.html`:
```html
<html>
<head>
<link rel="preconnect" href="https://rsms.me/">
<link rel="stylesheet" href="https://rsms.me/inter/inter.css">
<style>
:root { font-family: 'Inter', sans-serif; }
@supports (font-variation-settings: normal) {
  :root { font-family: 'Inter var', sans-serif; }
}

html {
    -webkit-font-smoothing: antialiased;
    font-feature-settings: "cpsp", "dlig", "frac", "zero", "cv01", "cv02",
"cv03", "cv04", "cv05", "cv06" 0, "cv07", "cv08", "cv09", "cv10", "calt",
"ccmp", "kern";
  }

button {
font-family: inherit;
}
</style>
</head>
<body>
<button>GI</button>
</body>
</html>
```

Then
```bash
npm install playwright@1.30.0 --save
npx playwright install
```

Serve the HTML, for example by running
```
python3 -m http.server
```
in this folder.

No test needed, just use
```
npx playwright codegen
```
and open `http://127.0.0.1:8000/demo.html`.

In 1.30.0 the button looks like this:
<img width="315" alt="image" src="https://user-images.githubusercontent.com/4116351/220931947-72bb20e0-cb05-4c05-be28-4c0c65f662a8.png">

In 1.31.0:
```
npm install playwright@1.31.1 --save
npx playwright install
npx playwright codegen
```
the button looks like this:
<img width="364" alt="image" src="https://user-images.githubusercontent.com/4116351/220933064-de7ef0b5-439c-449e-8c6c-055f60f1240b.png">

**Comment by yury-s** [comment]
I tried to reproduce it with our docker image (`docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.31.0-focal /bin/bash`) to no avail. Here are the two images I got:

![s-1 30](https://user-images.githubusercontent.com/9798949/221030437-50a21622-f047-4d2b-8500-a5c30b43be06.png)
![s-1 31](https://user-images.githubusercontent.com/9798949/221030441-c6355e2a-4733-4fe7-b55f-10096cadf4ce.png)

Can you try and see if it fails in our 20.04 docker image?

**Comment by yury-s** [comment]
Ok, I can actually reproduce it when I use toHaveScreenshot (apparently a font was still loading when I took the screenshots above).

```js
import { test, expect } from "@playwright/test";


test('has title', async ({ page, playwright }) => {
    await page.setContent(`<html>
    <head>
    <link rel="preconnect" href="https://rsms.me/">
    <link rel="stylesheet" href="https://rsms.me/inter/inter.css">
    <style>
    :root { font-family: 'Inter', sans-serif; }
    @supports (font-variation-settings: normal) {
      :root { font-family: 'Inter var', sans-serif; }
    }
    
    html {
        -webkit-font-smoothing: antialiased;
        font-feature-settings: "cpsp", "dlig", "frac", "zero", "cv01", "cv02",
    "cv03", "cv04", "cv05", "cv06" 0, "cv07", "cv08", "cv09", "cv10", "calt",
    "ccmp", "kern";
      }
    
    button {
    font-family: inherit;
    }
    </style>
    </head>
    <body>
    <button>GI</button>
    </body>
    </html>`);

//    await page.screenshot({ path: '/host/s-1.30.png' });
    await expect(page).toHaveScreenshot();
})
```

**Comment by SteffenDE** [comment]
Glad that you're able to reproduce. I am actually using the official docker image in our CI.

**Comment by yury-s** [comment]
Can it be that it just a timing issue of how fonts referenced from https://rsms.me/inter/inter.css are loaded? And if you wait long enough in 1.30.0, you'll get the same font?

**Comment by SteffenDE** [comment]
I don't think so. When using `npx playwright codegen` the page fully loads and the font is as expected, no change when waiting. Other browsers also render as expected on my Mac (Safari, but also Brave and Google Chrome), although there I only have Chromium 110. I could try getting a non-playwright Chromium 111 build to see if that happens there too, but didn't have the time yet.

**Comment by yury-s** [comment]
It actually fails on mac too, just reproduced it with the same test.

**Comment by yury-s** [comment]
Turns out this is an effect of a recently shipped feature in Chromium. [Here](https://chromium.googlesource.com/chromium/src/+/c4b50748b665c531ab6691b63aa3b7320e653d09) is the offending commit and here is the status of the feature: https://chromestatus.com/feature/5990758601981952 This is how you catch issue like that earlier with playwright 😄

**Comment by SteffenDE** [comment]
Oh interesting. I do not yet understand why this affects my example HTML, as I do not use the "font shorthand" (I assume they mean setting `font:` in CSS. But yeah that seems to explain it, so not a playwright issue then.
I really like that Playwright is ahead with browser releases. It's an awesome project in general!
