### ISSUE TITLE
Analogous to `sessionattached` puppeteer event in playwright

### ISSUE THREAD

**Issue by theadityasam** [microsoft/playwright#21107]
I'm trying to use lighthouse with playwright using the fraggle rock API: [issue reference](https://github.com/GoogleChrome/lighthouse/issues/3837#issuecomment-929875610). Fraggle rock API would allow lighthouse to utilise puppeteer page object for performing the tests. Noticed that internally lighthouse is creating a CDP session and was able to make it work with playwright page object by modifying it slightly.
```
page.target = function () {
    return {
      createCDPSession: async function () {
        const session = await page.context().newCDPSession(page);
        session.connection = () => new events.EventEmitter();
        return session;
      },
    };
};
```
For `session.connection`, need to provide an event emitter that emits the `sessionattached` event on `Target.attachedToTarget`, since lighthouse is using it internally: [link](https://github.com/GoogleChrome/lighthouse/blob/ecee7e8cff7c512acefce85529b2a6ff925da0ed/lighthouse-core/fraggle-rock/gather/session.js#L99).
Is there a way we can do this for playwright?

References:
Puppeteer CDP session API: https://pptr.dev/api/puppeteer.cdpsession
Playwright CDP session API: https://playwright.dev/docs/api/class-cdpsession

**Comment by yury-s** [comment]
From the [CDPSession documentation](https://playwright.dev/docs/api/class-cdpsession): "protocol events can be subscribed to with session.on method." So you can listen do the event via

```js
session.on('Target.attachedToTarget', e => console.log('Animation created!'));
```
See the [type definition](https://github.com/microsoft/playwright/blob/41d8f27d8f856271a4c97754282d3ea1c1117514/packages/playwright-core/types/types.d.ts#L12734-L12753) for other methods.

Is there a strong case for adding another method ?

**Comment by theadityasam** [comment]
Don't think there's any need for adding a `connection` method similar to puppeteer if event listeners can be directly attached to CDPsession.
Wanted to understand how I can make the `sessionattached` event work with lighthouse by mocking its response seem like puppeteer's. Puppeteer emits a `session` object in the `sessionattached` event [code reference](https://github.com/puppeteer/puppeteer/blob/f42336cf83982332829ca7e14ee48d8676e11545/packages/puppeteer-core/src/common/Connection.ts#L148-L160). 
Lighthouse internally listens to these events and uses the `session` object to create `ProtocolSessions` for its uses [code reference](https://github.com/GoogleChrome/lighthouse/blob/ecee7e8cff7c512acefce85529b2a6ff925da0ed/lighthouse-core/fraggle-rock/gather/session.js#L97-L99).
If there's parity between the API of puppeteer and playwright, we might be able to utilise lighthouse testing with playwright as well through CDPSession.
Am open to working on this piece if you feel it aligns with playwright's philosophies.

**Comment by yury-s** [comment]
Compatibility with puppeteer api is not a goal for playwright. It seems that you can already implement all you need based on the existing CDPSession interface. You can implement some adapter objects that would convert playwright events to the format expected by lighthouse.

**Comment by theadityasam** [comment]
Cool will try it out once. Any examples of the `adapter objects` that you are referring to? And any suggestions on how I can implement the session objects that are being returned by puppeteer?

**Comment by yury-s** [comment]
No specific suggestions, you have Plawright API that provides necessary functionality and you just need to merry it with another library that works with a puppeteer interface - it's up to you how to implement the interface.

Closing the issue as the original question was answered and the rest is behind the scope of Playwright. Feel free to open a new issues if you find bugs/need particular functionality to be added.
