### ISSUE TITLE
[Regression v1.31.0 CT] url: expected string, got undefined

### ISSUE THREAD

**Issue by pooledge** [microsoft/playwright#21108]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Mac
- Node.js version: 16.15.0
- Browser: All
- Framework: SvelteKit

**Describe the bug**

Each component test (even an empty one) fails within the first line:
`test('any name', async ({ mount, page }) => {` => `url: expected string, got undefined`

Did I miss a breaking?

**Comment by yury-s** [comment]
Could you share a reproducible example which we could run locally?

**Comment by yury-s** [comment]
> Did I miss a breaking?

Make sure you call `defineConfig` in your configuration file as described in the breaking change section in our [release notes](https://github.com/microsoft/playwright/releases/tag/v1.31.0).

**Comment by pooledge** [comment]
> Make sure you call `defineConfig` in your configuration file as described in the breaking change section in our [release notes](https://github.com/microsoft/playwright/releases/tag/v1.31.0).

That was it, thanks a lot!
