### ISSUE TITLE
[BUG] Error serializing `page.evaluate` return value if `URL` is overridden on the page

### ISSUE THREAD

**Issue by simonychoy** [microsoft/playwright#21109]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Mac
- Node.js version: 14.20.0
- Browser: All

**Code Snippet**

I created [this repo](https://github.com/simonychoy/url-override-issue) to reproduce this issue, but the code to reproduce this is shown below:

```javascript
import { test, expect } from "@playwright/test";

const simpleHtmlDataUrl = `data:text/html,<html><script type="application/javascript">URL = 'this is a string value and not a URL';</script><body><h1>Test page</h1></body></html>`;

test("Evaluate script on page where URL is overridden", async ({ page }) => {
  await page.goto(simpleHtmlDataUrl);

  const data = { text: "some data", value: 1 };

  const result = await page.evaluate((data) => {
    const { text } = data;
    return { myTextData: text };
  }, data);
  expect(result).toEqual({ myTextData: "some data" });
});
```

**Describe the bug**

If a site overrides `URL` with a string value, attempting to evaluate a script on a page that returns an object will return `undefined` due to the [isUrl](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/isomorphic/utilityScriptSerializers.ts#L46) check throwing an error during serialization. Perhaps the check should be similar to the [isError](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/isomorphic/utilityScriptSerializers.ts#L49) check where the check is wrapped in a try/catch? (I know you shouldn’t override the URL property, but I can’t control the target website).

I am willing to open a PR to fix this if you'd like.

**Comment by simonychoy** [comment]
Thank you @yury-s! Should I close this issue or leave it open? (I noticed you had reopened it)

**Comment by yury-s** [comment]
I reopened it as the new test doesn't pass in Firefox, we want it work in all browsers.
