### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ZTKeim** [microsoft/playwright#21115]
**Context:**
- Playwright Version: 1.31 downloaded a week ago
- Operating System: Windows
- Node.js version: 18.14.2
- Browser: Chromium
- Extra: Running in VS code

**Code Snippet**

```ts
class CustomFld{
    Value:Locator;
    Override:Locator;
    constructor(page:Page, customId:string, groupName:string, index:number = 0)
    {
        this.Value = page.locator(`.customfield[customid='${customId}'][groupname='${groupName}']`).nth(index);
        this.Override = page.locator(`.locktoggle[customid='${customId}_override'][groupname='${groupName}']`).nth(index);
    }
}
class HolePattern {
  page: Page;
  Description: CustomFld;
  constructor(page: Page, index:number = 0) {
    this.page = page;
    this.Description = new CustomFld(page, "Description", "HolePattern", index);
}
}
 const HP = new HolePattern(RC.page, 0);
await expect(HP.Description.Value).toHaveValue(`(6) 13/32" DIAM. DRILLED THRU\n18 9/16" BOLT CIRCLE, EQ. SPACED`);
```

 *****Error******
 Expected string: "(6) 13/32\" DIAM. DRILLED THRU
    18 9/16\" BOLT CIRCLE, EQ. SPACED"
    Received string: ""

********HTML of textarea**********
```html
<textarea style="display: none; height: 0px;" class="customfield    disabled " customid="BoltHolesDescription" type="text" defaultvalue="(6)  13/32&quot; DIAM. DRILLED THRU
 18 9/16&quot; BOLT CIRCLE, EQ. SPACED
" value="(6)  13/32&quot; DIAM. DRILLED THRU
 18 9/16&quot; BOLT CIRCLE, EQ. SPACED
" readonly="readonly" disabled="disabled" groupid="1677097640880" groupname="Core">(6)  13/32" DIAM. DRILLED THRU
 18 9/16" BOLT CIRCLE, EQ. SPACED
</textarea>  
```

**Describe the bug**
This is the first time I have tried to evaluate the value of a textarea element.  Seems to not read textarea correctly.

Also, completely un-related, but I am having to use function .press("Tab"); after every .fill() function I use in order to get it to call the change event on the input elements.

**Comment by yury-s** [comment]
Can you share a complete example where it is failing? I tried with the following and the tests passes just fine:

```ts
test('example', async ({ page }) => {
  await page.setContent(`<textarea style="display: none; height: 0px;" class="customfield    disabled " customid="BoltHolesDescription" type="text" defaultvalue="(6)  13/32&quot; DIAM. DRILLED THRU
  18 9/16&quot; BOLT CIRCLE, EQ. SPACED
 " value="(6)  13/32&quot; DIAM. DRILLED THRU
  18 9/16&quot; BOLT CIRCLE, EQ. SPACED
 " readonly="readonly" disabled="disabled" groupid="1677097640880" groupname="Core">(6)  13/32" DIAM. DRILLED THRU
  18 9/16" BOLT CIRCLE, EQ. SPACED
 </textarea>`);
  await expect(page.locator('textarea')).toHaveValue(`(6)  13/32" DIAM. DRILLED THRU
  18 9/16" BOLT CIRCLE, EQ. SPACED
 `);
});
```

> Also, completely un-related, but I am having to use function .press("Tab"); after every .fill() function I use in order to get it to call the change event on the input elements.

The page may have a special handler for the 'Tab'. If you think it's not the case and there is a bug in playwright please file a separate issue with a reproducible example.

**Comment by ZTKeim** [comment]
I found the issue.  The locator was not finding the field in the HTML.  A bit weird though that the error made it sound like it was found, and had an empty string, when it wasn't.

**Comment by yury-s** [comment]
Closing per the comment above.
