### ISSUE TITLE
Question: How to launch MS Teams App using electron Playwright

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#21129]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Node.js version: 14
- Browser: 
- Extra: 

Add any other details about the problem here.

How can I launch the MS Teams installed locally on my Macbook (assuming it is possible) using Electron PW

I am trying something like this:

```
test('has title', async () => {
  const electronApp = await electron.launch({
    executablePath:
      '.Applications/Microsoft Teams.app/Contents/MacOS/Teams', 
  });

  const appPath = await electronApp.evaluate(async ({ app }) => {
    return app.getAppPath();
  });
  console.log(appPath);
});
```

Any pointers are appreciated. 

Also, I was reading that ms teams native app might move to WebView2. Wondering if Playwright will be able to help automate that stuff?

**Comment by yury-s** [comment]
> How can I launch the MS Teams installed locally on my Macbook (assuming it is possible) using Electron PW

We don't provide any special support for Teams app, the following snippet seems to launch the app on macos and even intercept a window event.

```ts
import { test, expect, _electron } from '@playwright/test';

test('simple test', async ({ page }) => {
  
  const electronApp = await _electron.launch({
    executablePath: '/Applications/Microsoft Teams.app/Contents/MacOS/Teams'
  });
  electronApp.on('window', w => console.log(w.url()));

  const firstWindow = await electronApp.firstWindow();
  await page.waitForTimeout(10000);
  expect(firstWindow).toBeTruthy();
});
```

With that said, there are no guarantees it will work. You should look at MS Teams docs, contact their community with the question.

> Also, I was reading that ms teams native app might move to WebView2. Wondering if Playwright will be able to help automate that stuff?

WebView2 support is [documented here](https://playwright.dev/docs/webview2) but again there is no guaranteed if it will work with Teams.

Closing this report as we don't provide any specific support for MS Teams app.
