### ISSUE TITLE
[BUG] Trace viewer in html report does not open snapshots in separate window

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#21130]
**Context:**
- Playwright Version: 1.31.0
- Operating System: Mac
- Node.js version: 14
- Browser: All

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await expect(page.getByRole('link', { name: 'Get started' })).toBeVisible();
});
```
**config.js**
```
  reporter: [['html', { open: 'never' }]], 
  use: { trace: 'on' }
```
**Describe the bug**
After running the test, launch the html report and select the trace to open it. Click on any step and click pop out icon for the snapshot. It doesn't open it in a separate window. Same result when we open a trace in https://trace.playwright.dev/

Works fine locally using `npx playwright show-trace <path>`

**Comment by yury-s** [comment]
Each snapshot is opened in a new tab for me on macOS. Are you saying that it doesn't open at all for you or that it doesn't get into a new browser window?

**Comment by Nav-2d** [comment]
I meant doesn't up at all from html report or https://trace.playwright.dev/. Do you have a sample trace that you can share that opens in https://trace.playwright.dev/

**Comment by yury-s** [comment]
Yes, this one works just fine for me: [trace.zip](https://github.com/microsoft/playwright/files/10810911/trace.zip)

**Comment by Nav-2d** [comment]
I was able to open the DOM snapshots. It was due to the AdBlocker. Sorry for the trouble.
