### ISSUE TITLE
[BUG] Logging into application with API token is failing

### ISSUE THREAD

**Issue by aziizpc** [microsoft/playwright#21134]
**Context:**

- Playwright Version: v1.30.0
- Operating System: Windows
- Node.js version: v18.14.1
- Browser: All

**Code Snippet**

```js
const {test, expect, request} = require('@playwright/test')

// Create an account from the application UI --> rahulshettyacademy.com/client

const loginPayload = {userEmail: "YourUsername@gmail.com", userPassword: "YourPassword"};  
let token;

test.beforeAll( async() => {
    const apiContext = await request.newContext();
    const loginResponse = await apiContext.post("https://rahulshettyacademy.com/api/ecom/auth/login",
    {
        data:loginPayload
    });
    expect(loginResponse.ok()).toBeTruthy();
    const loginResponseJson = loginResponse.json();
    token = loginResponseJson.token;
    console.log("Token: " + token);
});

test('Page Playwright test', async ({page}) => {
page.addInitScript(value => {
        window.localStorage.setItem('token', value);
    }, token);
await page.goto("https://rahulshettyacademy.com/client");
});

```

**Describe the bug**

The application is not loading. Getting a white page. Also, console.log(token) giving 'Undefined'.

**Comment by yury-s** [comment]
> Also, console.log(token) giving 'Undefined'.

It seems that authentication fails for some reason, perhaps the credentials did match or the server expects a particular User-Agent string? Did you look at the trace/logs of the script, what else is in the json response, maybe there is an error message? It doesn't seem to be a playwright issue, most likely you provide incomplete data with the login request or it is not structured in a way expected by the server.

**Comment by evapomper** [comment]
const loginResponseJson = **await** loginResponse.json();
**const** token = loginResponseJson.token;

**Comment by yury-s** [comment]
Closing per the response above(good catch @evapomper !), you are missing the await. Feel free to open a new issue if it still doesn't work.

**Comment by aziizpc** [comment]
It worked. Thanks a bunch!
