### ISSUE TITLE
[API] No way to change the DPR when using a persistent context.

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#2113]
I have an automation scenario that runs headful. It uses a persistent context. I want to set the DPR to 2 so that things are not blurry on my laptop. There is no API to do this.

I would be happiest with:
- `context.setViewport`
- `page.setDeviceScaleFactor`
and ok with
- `launchPersistent({noDefaultViewport})`
- `launchPersistent({defaultViewport})`

**Comment by dgozman** [comment]
This was fixed by #2177.

- `launchPersistentContext({viewport: null})` to avoid changing the viewport;
- `launchPersistentContext({deviceScaleFactor: 2})` for DPR emulation.
