### ISSUE TITLE
How to select element from list which is not visible if not scrolled up

### ISSUE THREAD

**Issue by Girija-Joshi** [microsoft/playwright#21137]
I have something like this defined as a dropdown list. I am not able to figure out how to click on the element and scroll up and down the list

`<input type="search" id="serviceType" autocomplete="off" class="fc-select-selection-search-input" role="combobox" aria-haspopup="listbox" aria-owns="serviceType_list" aria-autocomplete="list" aria-controls="serviceType_list" aria-activedescendant="serviceType_list_7" readonly="" unselectable="on" value="" style="opacity: 0;" aria-expanded="false">`

I tried options page.locator, id and couple of other options but not able to fins a way to click on above dropdown

Can anyone help me?

**Comment by yury-s** [comment]
Regular `await page.locator('#serviceType').click();` should work. Can you share the entire example with the drop down and explain what is not working when click with playwright?

**Comment by Girija-Joshi** [comment]
with the above i am getting an error playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
E       =========================== logs ===========================
E       waiting for locator("#serviceType")

I can't share dropdown but parent element is like 
`<div class="fc-select fc-select-in-form-item fc-select--lg  fc-select-single fc-select-show-arrow"><div class="fc-select-selector"><span class="fc-select-selection-search"><input type="search" id="serviceType" autocomplete="off" class="fc-select-selection-search-input" role="combobox" aria-haspopup="listbox" aria-owns="serviceType_list" aria-autocomplete="list" aria-controls="serviceType_list" aria-activedescendant="serviceType_list_6" readonly="" unselectable="on" value="" style="opacity: 0;" aria-expanded="false"></span><span class="fc-select-selection-item" title="C_HazardFromCCS_Copy_2">C_HazardFromCCS_Copy_2</span></div><span class="fc-select-arrow" unselectable="on" aria-hidden="true" style="user-select: none;"><span role="img" aria-label="down" class="anticon anticon-down fc-select-suffix"><svg viewBox="64 64 896 896" focusable="false" data-icon="down" width="1em" height="1em" fill="currentColor" aria-hidden="true"><path d="M884 256h-75c-5.1 0-9.9 2.5-12.9 6.6L512 654.2 227.9 262.6c-3-4.1-7.8-6.6-12.9-6.6h-75c-6.5 0-10.3 7.4-6.5 12.7l352.6 486.1c12.8 17.6 39 17.6 51.7 0l352.6-486.1c3.9-5.3.1-12.7-6.4-12.7z"></path></svg></span></span></div>`

**Comment by Girija-Joshi** [comment]
I not sure what to do and how to select and scroll this component

**Comment by KavitaForProtractor** [comment]
You can use ArrowDown if scrolling down is the only option you have. or you can use tab key

**Comment by yury-s** [comment]
> E waiting for locator("#serviceType")

Can you share full log or better trace file? If you can share code of the test, it would help too. Apparently the element is not there for some, are you able to find it manually when running the test? See our [debugging tips](https://playwright.dev/python/docs/debug#exploring-selectors).

Did you try using codegen to see what code it suggests for your scenario? If it doesn't work, you can try sending raw input events via [mouse](https://playwright.dev/python/docs/api/class-mouse) and [keyboard](https://playwright.dev/python/docs/api/class-keyboard) classes.

The snippet above doesn't render to a dropdown for me. Without seeing the code we can only give a general advise.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
