### ISSUE TITLE
[Feature] Allow reducedMotion to be defined as part of global config.

### ISSUE THREAD

**Issue by kylemh** [microsoft/playwright#21133]
Currently I can define `reducedMotion` `page.emulateMedia()`, `browserType.launchPersistentContext()`, `browser.newContext()`, and `browser.newPage()` ([source](https://playwright.dev/docs/next/release-notes#new-apis-5)). It's going to be very tiresome to have everybody on my team remember to use this in order to prevent animations from causing visual regression diff tests to flake. Having this setting (and others queryable via media query) be something configurable globally is a good idea in my mind!

**Comment by mxschmitt** [comment]
You can do the following as of today, would that work for you?

```ts
      use: {
        browserName: 'firefox',
        contextOptions: {
          reducedMotion: 'reduce',
        }
      },
```

**Comment by kylemh** [comment]
ah. i had no clue! thanks
