### ISSUE TITLE
[BUG] `Open snapshot in a new tab` button overlays timeline preview in trace viewer

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#21147]
**Context:**
- Playwright Version: 1.31

```javascript
<a class="popout-icon " target="_blank" title="Open snapshot in a new tab" 
```

**Describe the bug**

while the timeline is not hovered, the popup icon is fine
![image](https://user-images.githubusercontent.com/7899764/220894684-74ea6c4a-03b5-43c9-9afa-4855a7f3c1c4.png)

but when one hovers, icon must be under preview from timeline
![image](https://user-images.githubusercontent.com/7899764/220894721-b9a51e7c-3576-4835-8caf-2a31e5232b30.png)

**Comment by dgozman** [comment]
This has been fixed by #20965.
