### ISSUE TITLE
[Question] Does WebKit Support 'Tab' Navigation?

### ISSUE THREAD

**Issue by bellindj** [microsoft/playwright#2114]
In my Playwright tests, I am using the below code to navigate focus between my custom elements.
`await page.keyboard.press('Tab');`

This works in FireFix and Chrome but not WebKit. In WebKit it does not tab between my elements. I had a similar issue in Safari when manually pressing tab where it didn't change focus between my web elements, and had to enable a setting in Safari Preferences under Advanced: "Press Tab to highlight each item on a webpage" to make this work. This seems to be a common problem: [https://osxdaily.com/2011/08/14/enable-tab-key-navigation-safari/](https://osxdaily.com/2011/08/14/enable-tab-key-navigation-safari/).

What should the behavior of WebKit in Playwright be? Is there a way to change that setting in WebKit with Playwright so that it will respond to my Tab navigation?

**Comment by pavelfeldman** [comment]
We stick with the browser defaults for testing, so this behavior seems to match our expectations. Would CSS injection that adds outline to focused elements work for you?

**Comment by pavelfeldman** [comment]
I just discovered a bug where we don't dispatch Tab on WebKit, hang on, maybe that's what you want fixed!

**Comment by bellindj** [comment]
Yes that could be the reason!

**Comment by bellindj** [comment]
Works in 1.1, thank you!!

**Comment by muratcorlu** [comment]
We are using a workaround like:

```ts
const tabKey =
        navigator.userAgent.includes('Safari') && !navigator.userAgent.includes('HeadlessChrome')
          ? 'Alt+Tab'
          : 'Tab';

      await sendKeys({
        press: tabKey,
      });
```

Is this the best way? Or can we somehow make this work by configuring webkit in playwright?

**Comment by robertkibet** [comment]
where is this method `sendKeys()`? @muratcorlu is this a custom solution on your end, would love to see this implementation as we're facing the same issue not being able to trigger Tab key 🤔

**Comment by muratcorlu** [comment]
We are using Web Test Runner package. Example: https://github.com/Trendyol/baklava/blob/43b520877e45915bb51a01357ede04846a751f4f/src/components/dropdown/bl-dropdown.test.ts#L238
