### ISSUE TITLE
What is the logic of working timeouts? There should be a bug?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#21155]
Model Name:	MacBook Pro
  Chip:	Apple M1
  Total Number of Cores:	8 (4 performance and 4 efficiency)
  Memory:	16 GB

My test works 13 workers for 80 case.Playwright.config.ts as below;

```
import { devices, type PlaywrightTestConfig } from "@playwright/test";
import { configEnv } from './config/config'

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  globalTeardown: './global-teardown.ts',
  retries: 2,
  workers:20,
  timeout: 150 * 1000,
  expect: {
    timeout: 70 * 1000
  },
  reporter: [['html', { outputFolder: 'report' }]],
  use: {
    headless: false,
    baseURL: configEnv.baseURL,
    storageState: 'fixtures/common/state.json',
    actionTimeout: 70000,
    trace: 'retain-on-failure',
    navigationTimeout:70000,
    ignoreHTTPSErrors: true
  },
  projects: [
    {
      name: "chrome",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],

        },
      },
    },
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],

        },
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices["Desktop Webkit"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],
        },
      },
    },
  ],
};
export default config;
```

When I increase the number of cases, I don't understand why I have to increase expect, navigation and action timeout. For example, while the number of automated cases was 30, they were all 30000ms(expect,navigation and action) and worked good without no timeout error. The number of cases went up to 60, it worked when I made 50000ms all of timeouts(expect,navigation and action). Now the number of automated cases has increased to 80, I have to increase to 70000ms(expect,navigation and action) and worked good without no timeout error, it works in the most correct way. Am I doing something wrong  in the relationship between these timeouts?  This should be a bug or are my timeout configs wrong?

**Comment by yury-s** [comment]
You set `workers: 20` and run it on a machine with 4+4=8 cores. This will normally cause more resource contention and will just slow down the entire test process (hence require longer timeouts) rather that decreasing the test execution time. Most of the time playwright default setting for the number of workers should be optimal and you don't need to adjust it manually. The [default number](https://playwright.dev/docs/api/class-testconfig#test-config-workers) of workers would be around half of the core as playwright has to start browsers in their own processes.

You also say that 'My test works 13 workers for 80 case.' which means that you are not using 20 workers anyway and as you add more tests there maybe more of them that can be parallelized causing even more contention. 

 I'd suggest you simply remove workers from the config and let playwright use the default number which is usually optimal for your hardware.
