### ISSUE TITLE
[Question] Is it possible to specify browser versions?

### ISSUE THREAD

**Issue by bernardobridge** [microsoft/playwright#2115]
I was wondering if it's possible to specify browser versions, or if it's planned on being supported? If we wanted to test retro compatibility with older browser releases, I think it would be useful to be able to specify which browser version we want. I'm guessing right now it's always the latest stable release?

**Comment by pavelfeldman** [comment]
It is more than that, our changes to the browsers are on the bleeding edge. So it is safe to say that Playwright will support Chromium 84+, Firefox 76+, Safari/WebKit  13+.

**Comment by bernardobridge** [comment]
Thank you for answering !

Is there anyway to specify older versions too? Or we are always locked to the newer versions?

**Comment by sdeprez** [comment]
Is this true @pavelfeldman? From what I understand `playwright` directly patches the browsers, so you cannot just use any latest versions of those browsers, you have to use the patched ones provided by `playwright`.

**Comment by pavelfeldman** [comment]
@sdeprez: You are right, Playwright uses stock Chromium, but still patched WebKit & Firefox. The question was about older browsers and my answer should read as `it is safe to say that we will never support anything older than...`. I can see how it could be misread.

**Comment by gullerya** [comment]
Sorry to raise it again, but given @pavelfeldman 's answer, and given that those Chromium 84+, FF 76+ and WK 13+ are good enough to me - how can I specify to `playwright` to download and use those versions and not newer ones?

**Comment by mxschmitt** [comment]
@gullerya thats not possible. Playwright is only compatible with the browser Playwright ships with. Like if you choose Playwright v1.0.0 then its older than 1.8.0

**Comment by gullerya** [comment]
I see, there is a coupling between the playwright version and it's 'bundled' browsers' versions.
Hope that you can guys consider to detach those in some future.
Thanks!

**Comment by mariaceo** [comment]
Any change on this? It would help a lot to be possible to specify older browser versions to run the tests on.

**Comment by valerii15298** [comment]
Also +1 for such feature.

**Comment by mxschmitt** [comment]
Please file new feature requests for it, closed issues don't get monitored.
