### ISSUE TITLE
[BUG] pytest-xdist and Playwright execution performance: very high CPU and memory usage

### ISSUE THREAD

**Issue by TestTheTest7** [microsoft/playwright#21158]
**Context:**
- Playwright Version: **1.28.0**
- Operating System: **Mac OS Monterey (Apple M1, 16GB)**
- Python: **3.9.6**
- Browsers: **All (Chromium, Firefox, WebKit)**
- Extra: 

1. **pytest-xdist==1.29.0** for running tests
2. **pytest fixures** are used
`@pytest.fixture(scope="function")` -> on the scope level browser context and page are created and the page is used through test, at the end of scope(in this case at the end of test) the context and the page are closed (also tried with scope="session" but had too many problems in the case when I have many scenarios(>50))

```
viewport_width = 1800
viewport_height = 900

with sync_playwright() as pw_context:
    browser = pw_context.chromium.launch()
    
    browser_context = browser.new_context(
        viewport=ViewportSize(width=viewport_width, height=viewport_height),
    )

    new_page = browser_context.new_page()

    new_page.goto("https://playwright.dev/python/")

    yield new_page

    browser_context.close()
```

**Describe the bug**

The problem is very high CPU and memory usage while tests running on my local machine (details described above). If I have for example 4 tests and run them with 4 workers, CPU usage becomes 85-90% at some moment which is very high and unacceptable.

**Some facts:** 

- the same behaviour for any number of workers
- the same behaviour for all browser types
- execution times of each test are approx. 25 secs, 50 secs, 80 secs, 60 secs
- please see CPU and memory usage

![Screenshot 2023-02-23 at 16 27 51](https://user-images.githubusercontent.com/126164388/220953894-5dbf172e-57e3-41e2-9b7c-2f00112ab98d.png)

![Screenshot 2023-02-23 at 16 28 29](https://user-images.githubusercontent.com/126164388/220954046-ed2ea649-5aa8-4ae6-8939-34cd49b65c8d.png)

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Could you share a complete test example which we could run locally?

**Comment by yury-s** [comment]
> CPU usage becomes 85-90% at some moment which is very high and unacceptable.

Having a spike of 90% at some point is not unexpected, if there is a steady high utilization like this for each parallel instance of playwright, whether it's expected depends on what the test is doing. We need to see the actual test.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue if you can reduce the test case to a reproducible example that you can share and link it to this one.

**Comment by TestTheTest7** [comment]
Hi, I'm working on it, sorry for waiting. Once I'm done I will create new issue and link with this one if possible. Thank you
