### ISSUE TITLE
[BUG] browser.close()

### ISSUE THREAD

**Issue by Liuyilin-ai** [microsoft/playwright#21159]
**Context:**
- Playwright Version:1.31
- Operating System: [Windows]
- python version: 3.9
- Browser: [Chromium]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
from playwright.sync_api import sync_playwright


def test(playwright):
    chromium = playwright.chromium  # or "firefox" or "webkit".
    browser = chromium.launch(
        headless=False,
        args=[f'--disable-extensions-except={fox}',
              f'--load-extension=${fox}', ]
    )
    page = browser.new_page()
    page.goto("http://example.com")
    # other actions...
    # browser.close()
    page.on("console", lambda msg: print(msg.text))


with sync_playwright() as playwright:
    test(playwright)
```

**Describe the bug**

Add any other details about the problem here.
I have commented close, but when the browser finishes running, it just closes, so it should keep the form

**Comment by yury-s** [comment]
Your python script finishes running and playwright exits and closes the browser automatically. If you want to keep it running you should ensure the python script keeps running (it can be another test or a busy loop etc).

**Comment by Liuyilin-ai** [comment]
I used page.on('consolse') to listen to the event, it should keep running, not close automatically, a task's process switch, wouldn't waste time on this if using loop, it should be up to the user, maybe my mind is still on puppeteer




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yury ***@***.***&gt;; 
发送时间: 2023年2月24日(星期五) 凌晨0:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [microsoft/playwright] [BUG] browser.close() (Issue #21159)





 
您的 python 脚本运行完毕，编剧退出并自动关闭浏览器。如果你想让它保持运行，你应该确保 python 脚本保持运行（它可以是另一个测试或一个繁忙的循环等）。
 
—
直接回复此邮件，在 GitHub 上查看，或取消订阅。
您收到此消息是因为您创作了该线程。消息 ID：<microsoft/playwright/issues/21159/ 1442100601 @github 。com&gt;
