### ISSUE TITLE
Element is found with pick locator but times out when running in automation

### ISSUE THREAD

**Issue by cmo1969** [microsoft/playwright#21167]
I have a webapp input that I can positively identify opening the site in codegen and using Pick locator in the Playwright Inspector, but when using the same selector in an automation script, it times out. I've tried using getByRole and a locator with an ID in a selector to no avail. The element is not in an iFrame. What can be done differently to get Playwright to recognize the element.

![image](https://user-images.githubusercontent.com/126203497/221032122-cb3e985c-dbb0-46c0-8a6e-a575b0955e9b.png)

**Comment by yury-s** [comment]
The selector looks legit but maybe the page is in a different state when you are running your automation script trying to locate the element. We need to see the page for which you generated the selector. Can you share the page and the test which is failing so that we could run and debug it locally?

**Comment by cmo1969** [comment]
The page contains sensitive information, I cannot share the whole page. Is there anything else I can share that would be helpful? The page is fully loaded. I put a pause in there to be sure it was loaded. The pick locator identifies the element while the page is paused, which is why I'm confused the script doesn't do the same.

**Comment by yury-s** [comment]
What's in the error log when the element is not found? Maybe you can share the trace? You can send it to the email in my profile if you don't want to make it public.
