### ISSUE TITLE
page.locator("locator1").click() method hangs

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#21162]
one  page behaves like this, if my mouse hovers over locator1, the page scroll up, and my mouse hovers over locator1 again, the page scrolls down.

page.locator("locator1").click() is used to click the locator to open an expander, I can see the page keeps scrolling up and down forever, but the expander is not opend

why does this happen, any workaround

**Comment by yury-s** [comment]
> one page behaves like this, if my mouse hovers over locator1, the page scroll up, and my mouse hovers over locator1 again, the page scrolls down.

Before clicking an element playwright will ensure that the element is [visible](https://playwright.dev/docs/actionability)  scrolling it into view if necessary. From what you describe the element may scroll out of the viewport once playwright moves the mouse over it. In that case the actionability check may never pass and the click may fail. From your description it seems that a human user would be in the same situation - the element would be moving away from the cursor. What does playwright log say when the action fails?

> page.locator("locator1").click() is used to click the locator to open an expander, I can see the page keeps scrolling up and down forever, but the expander is not opend
>
> why does this happen, any workaround

Can you share the code which we could run locally to reproduce this issue? Without that we can only speculate about what the page is doing.

**Comment by bodycombathuang** [comment]
I resolved by using javascript click , 
        // await locator.click();
          this.page.evaluate(
            (pathObject) => {
                const expander=document.querySelector(pathObject.path);
                (expander as HTMLDivElement).click();
            },
            { path:locatorPath }
if I use locator.click(), mouse will be moved to the object to be clicked, right? and the object will move away, and the mouse will be moved to the object again and again, the the object will always move away, so click() will always move to the object, so the page is scrolling up and down

**Comment by yury-s** [comment]
> if I use locator.click(), mouse will be moved to the object to be clicked, right? and the object will move away, and the mouse will be moved to the object again and again, the the object will always move away, 

Correct. As I mentioned above, the same would happen if a human was trying to click the element - first move the mouse over and then click (and they won't be able to click as the element would move away before click).

Anyway, if you just want to dispatch web click event you can also use more concise [dispatchEvent('click')](https://playwright.dev/docs/api/class-locator#locator-dispatch-event).
