### ISSUE TITLE
[Feature] Add a wait api that to wait until the content of an iframe has been loaded

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#21176]
I the following example an iframe with the src myurl will be injected in the page.
I can find the iframe dom element but without the explicit wait the page.frame function returns null.
I guess this is because page.frame does not wait for the iframe to be loaded.
I did not find an api that allows me to wait until the content of an iframe has been loaded and believe that this would be helpful.

```typescript
await expect(page.locator('iframe')).toHaveCount(1);
await page.waitForTimeout(2000); // explicit wait should be replace by wait api
const frame = page.frame({url: new RegExp('.*/myurl.*', 'i')});
expect(frame).not.toBeNull();
```

**Comment by MindaugasMateika** [comment]
You could try polling or retrying assertion for a period of time to check if frame is loaded or not, see:

https://playwright.dev/docs/test-assertions#polling

**Comment by doberkofler** [comment]
Good idea but it feels more a bit like a workaround for something quite "normal" when working with iframe.

**Comment by MindaugasMateika** [comment]
I don't have much experience with frames but if you can target it with syntax like this `page.locator('iframe')` then you could do `page.locator('iframe').waitFor()` with additional state and timeout parameters for waitFor()

**Comment by doberkofler** [comment]
I have tried a bit, but what event could I wait for?

**Comment by MindaugasMateika** [comment]
It defaults to waiting for `visible` so if you plan to do something with that iframe then it should work. Otherwise, try waiting for `attached`.

**Comment by yury-s** [comment]
@doberkofler can you tell us more about what you want to do with the frame?

`page.frame` returns null because the frame still has different url. You can wait for the frame to navigate to the url first:
```js
    const frame = page.frames()[0];
    await frame.waitForURL(new RegExp('.*/myurl.*', 'i'));
```
or like this:
```js
    const iframeElement = await page.locator('iframe').elementHandle()
    const frame = await iframeElement.contentFrame();
    await frame.waitForURL(new RegExp('.*/myurl.*', 'i'));
```
will that work for you?

**Comment by doberkofler** [comment]
@yury-s  Thank you for your help.
1) Generally speaking the iframe's contain parts of a web application that must be displayed in a dialog or 3rd-party web applications
2) The first option does not seem to work for my use case because i have several iframe's that can only be identified by it's parent element and I see no way to find them in the array of all frames or could I?
3) The second option works very well and solves my problem, but when taking care of all possible return codes and clean typing the result looks a bit complicated.
4) I would imagine that waiting for an iframe to load content is a very typical use case and could benefit from a more intuitive API to do so.

**Comment by jkohlin** [comment]
I couldn't agree more. I have been struggling with this for days now! I'm in a contentful (cms) connector and I have to work in iframes. I had to create a promise wrapper around page.on('frameloaded', callback) to make it work. the event will fire five times and I have to wait for the frame.url to be correct before i resolve the promise. That was complicated!! 😅
Something like this:
```javascript
test('PageConfig', async ({ page }) => {
    await page.goto('https://kohlin.info/iframes');
    const iframe = page.frameLocator('[data-test-id="the-iframe-element"]')
    await iframe.waitForLoadState('domcontentloaded');
    const allItems = iframe.getByTestId('todo-item').all(); // btw, this should not fail if there's only one item, but it does
    expect(allItems).toHaveLength(1); 
    page.close();
});
```

**Comment by yury-s** [comment]
@doberkofler would the approach [above](https://github.com/microsoft/playwright/issues/21176#issuecomment-1450583142) with chained locators work for your use case without explicit `wait`? If not, can you share more details on why you'd prefer to manually wait for the iframe to load?

**Comment by doberkofler** [comment]
@yury-s If I understand you correctly instead of waiting for the iframe to have it's url loaded, you would immediately implicitly wait for some DOM element in the iframe to be available. Correct?
It did not explicitly test this solution, but I guess it would work.
The reason, why I did not go this way, is the fact that this approach would not distinguish between the iframe not to be loaded and something wrong within the iframe itself.
Like on a regular page, I would rather wait until the page url is loaded and the `DOMContentLoaded` event is fired and only then start to test on the content of the page.

**Comment by yury-s** [comment]
> @yury-s If I understand you correctly instead of waiting for the iframe to have it's url loaded, you would immediately implicitly wait for some DOM element in the iframe to be available. Correct?

Yes, exactly. You basically specify what the user visible behavior you want to test and let playwright wait for that automatically - at the end of the day it's not much different than waiting for an element to be added in the DOM tree and become visible. As for the debugging point - you can still see in the trace if the frame didn't load or if it was another issue.

So far all the scenarios where someone needed to wait for an iframe to load were solvable with chaining frame locators and locators and since this is the approach that we recommend, we are hesitant adding API like `frameLocator.waitForURL()`.

**Comment by doberkofler** [comment]
@yury-s I understand that the API should remain as lean as possible but the solutions are (at least) not very intuitive. In the best case scenario `Page.frame` should automatically wait for the `load` event like when using `Page.goto`.
Maybe this could at least be added to the documentation so others might not also get stuck here.

**Comment by yury-s** [comment]
> @yury-s I understand that the API should remain as lean as possible but the solutions are (at least) not very intuitive. In the best case scenario `Page.frame` should automatically wait for the `load` event like when using `Page.goto`. 

`Page.frame` is a synchronous API, we cannot change that without breaking existing clients. `Page.frameLocator` should be preferred and it does auto wait. If one still want to manually wait for the frame navigations there are also events like [`framenavigated`](https://playwright.dev/docs/api/class-page#page-event-frame-navigated) and [`frame.waitForLoadState`](https://playwright.dev/docs/api/class-frame#frame-wait-for-load-state) but as I described above we recommend using locator and rely on auto-waiting functionality as proved to be more resilient.

> Maybe this could at least be added to the documentation so others might not also get stuck here.

Agreed, this is definitely worth documenting and providing some examples.

**Comment by pavelfeldman** [comment]
> Maybe this could at least be added to the documentation so others might not also get stuck here.

That's the first thing you see when you look at our frames doc: https://playwright.dev/docs/next/frames

And if you look at the API docs, we are explaining it there: https://playwright.dev/docs/next/api/class-framelocator

We don't want anyone to use the frame object API when performing actions, it serves different purpose.

**Comment by BatthewZ** [comment]
I had this issue. This is the solution that I built for it. I'm not sure if it'd be considered 'best practice' at all, but it works for me and I hope it works for you:

```
import { Page, Frame } from "@playwright/test";

/**
 *
 * @param {Page | Frame} pageOrFrame
 * @param {string} partialFrameUrlString
 * @returns {Frame | null}
 * @example const frame = await pollForIframe(page, '/my-frame/api');
 */

async function pollForIframe(pageOrFrame, partialFrameUrlString) {
  let frame = null;

  const isPageOrFrame = pageOrFrame.frames
    ? "page"
    : pageOrFrame.childFrames
    ? "frame"
    : null;

  if (!isPageOrFrame) return null;

  for (let i = 0; i < 20; i++) {
    if (isPageOrFrame === "page") {
      frame = pageOrFrame
        .frames()
        .find((f) => f.url().includes(partialFrameUrlString));
    } else if (isPageOrFrame === "frame") {
      frame = pageOrFrame
        .childFrames()
        .find((f) => f.url().includes(partialFrameUrlString));
    }

    if (frame) {
      return frame;
    }

    await pageOrFrame.waitForTimeout(500);
  }

  return null;
}

module.exports = {
  pollForIframe,
};

```
