### ISSUE TITLE
[BUG] npx playwright show-report only show report which vscode plug-in generated, not includes command line

### ISSUE THREAD

**Issue by guscj** [microsoft/playwright#21175]
**Context:**
- playwright/experimental-ct-vue: 1.30.0
- Operating System: Windows
- Node.js version: v14.20.0
- Browser: only try on Chromium

**Describe the bug**

I run "npx playwright test" first in command line and it complete successfully. 
Then I run "npx playwright show-report" in command line. 
But it seems only showed report which vscode plug-in last generated, not the command line one which I expected.

**Comment by yury-s** [comment]
Can you try calling `npx playwright show-report <path to the report>` with explicit path to the report and see what it shows?

Can you share a reproducible example where it happens?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by guscj** [comment]
> Can you try calling `npx playwright show-report <path to the report>` with explicit path to the report and see what it shows?
> 
> Can you share a reproducible example where it happens?

@yury-s 
I tried `npx playwright show-report .\playwright-report\`, it shows this empty report :
![image](https://user-images.githubusercontent.com/52311065/221748926-b5a78ca2-e22c-4f8c-ad49-640342663adb.png)
I checked playwright-report folder，there only has an index.html. If I use vscode plugin to run, it still has only one index.html, but report shows in web fine.
Here is example:
`import { test, expect } from '@playwright/experimental-ct-vue';
import Demo from './Demo.vue';
import { DefaultProps, Props } from './config';

test.describe('prop: label', () => {
  for (let labelVal of Props.label) {
    test(`label equals ${labelVal}`, async ({ mount }) => {
      const myLocator = await mount(<Demo {...DefaultProps} label={labelVal} />);
      
      await myLocator.getByRole('radio').nth(0).click();
      await expect(myLocator.getByRole('radio').nth(0)).toBeChecked();
    });
  };
});`

**Comment by guscj** [comment]
It closed, should I recreate an issue?
