### ISSUE TITLE
[BUG] Browser context closed promise doesn't resolve if chunked request is still active upon test completion on webkit with recordHar

### ISSUE THREAD

**Issue by DerGernTod** [microsoft/playwright#21182]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows
- Node.js version: 16.17.1
- Browser: WebKit

**Code Snippet**
Example playwright test
```javascript
test.only("webkit doesn't resolve .waitForSelector if chunked request is in progress", async ({ page }) => {
    page.on("console", (log) => {
        console.log(log.text());
    });
    await page.goto("http://localhost:8090/ajax/testframework/typescript/tests/modules/webkit-test.jsp", { waitUntil: "load" });
    console.log("goto resolved, waiting for selector...");
    await page.waitForSelector("#pw-finished", { state: "attached", timeout: 15000 });
});
```

Example html
```html
<!DOCTYPE html>
<html>
<head>
    <script type="application/javascript">
        function loadXhr() {
            console.log(performance.now().toFixed(2), "sending xhr...");
            fetch(`chunked-response.jsp`);
            
            setTimeout(function() {
                var div = document.createElement("div");
                div.id = "pw-finished";
                document.body.appendChild(div);
                console.log(performance.now().toFixed(2), "div attached!");
            }, 1000);
        }
    </script>
</head>
<body onload="loadXhr()">
loads some long request onload
</body>
</html>
```

In case you want to verify that element is really attached:
```javascript
var m = new MutationObserver(function () {
    console.log(performance.now().toFixed(2), "mutation happened");
});
m.observe(document.body, {subtree: true, childList: true});
```

An example of how a chunked-response.jsp could look like (it flushes in-between in order to fire progress events):
```jsp
<%--
  responds after 30 seconds, but sends updates every 100ms
--%><%
    for (int i = 0; i < 10; i++) {
        response.getWriter().print(i + " ");
        response.getWriter().flush();
        try {
            Thread.sleep(100);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
    }
    try {
        Thread.sleep(30000);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
%>

```

**Describe the bug**
On webkit, playwright doesn't resolve the `waitForSelector` promise when the respective element shows up, but only when all chunked requests are done. To me these two things are completely independent, and this doesn't happen for other browsers. It also only seems to happen for chunked requests, for normal requests it resolves in time.

In addition to that, even though i have a time limit of 15 seconds, the test succeeds after 30 seconds (so, when the chunked response is done). So it seems playwright recognizes that the element has been added within the first 15 seconds, but it simply doesn't resolve the promise.

I would expect webkit to behave the same way as the other browsers - resolving the `waitForSelector` promise as soon as an element is added to the page matching the respective selector, not 30 seconds later, exceeding its timeout.

**Comment by yury-s** [comment]
I was not able to reproduce this neither on macOS nor on Windows with latest playwright. Can you share trace of the run where it is failing?

**Comment by DerGernTod** [comment]
while building a reproducer, i found that the issue is actually in the har-recorder. that's also the reason why the `waitForSelector` timeout doesn't trigger: `waitForSelector` is actually resolved and the test is complete, but the context cannot be closed.
i built a reproducer here: https://github.com/DerGernTod/playwright-chunked-response

this of course invalidates the issue description. should i create a new issue or edit this one?

**Comment by yury-s** [comment]
Thanks for the repro, I managed to reproduce it locally. Feel free to just edit the title of the issue instead of filing a new one..
