### ISSUE TITLE
[Question]how can i edit script in inspector? for example add log\assert

### ISSUE THREAD

**Issue by keyshike** [microsoft/playwright#21180]
now ,we need to record script in inspector and then copy to some IDE,and add some log\assert 
finally debug it in inspector, it is not good user journey, if we can record ,can debug,why do not we add the edit funcntion ,then we can in inspector do everything.

**Comment by yury-s** [comment]
Editing is not supported in the inspector, we recommend using VS Code extension if you need to edit generated code right away. See [this guide](https://playwright.dev/docs/getting-started-vscode#generating-tests). Will this work for you?

**Comment by keyshike** [comment]
thanks for your feedback, do you have plan to add the edit function , as an UI automated testing user, it really is good thing.

**Comment by yury-s** [comment]
We might implement it in the future, but no plans at the moment. We recommend using VS Code extension for the workflows that require editing sources in addition to codegen and debugging.

**Comment by keyshike** [comment]
OK,thanks very much.
