### ISSUE TITLE
[BUG] Cannot import Svelte components for component testing in sveltekit

### ISSUE THREAD

**Issue by snorresovold** [microsoft/playwright#21184]
**Context:**
- Playwright Version: ["@playwright/experimental-ct-svelte": "^1.31.1", "@playwright/test": "^1.28.1",]
- Operating System: [windows 10]
- Node.js version: [16.17]
- Browser: [All]
- Extra: [using sveltekit + typescript]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```typescript
import { test, expect } from '@playwright/experimental-ct-svelte';
import Button from "$lib/Button.svelte"

test.use({ viewport: { width: 500, height: 500 } });

test('Test Button', async ({ mount }) => {
  const component = await mount(Button);
  await expect(component).toContainText('hello');
});
```

**Describe the bug**
getting error Cannot find module '$lib/Button.svelte' or its corresponding type declarations.

I am also getting an error on the mount(button) function. It seems like playwright isn't excpecting svelte.

I am literraly just copying the tutorial from here https://playwright.dev/docs/test-components

Here is my Button.svelte file

```typescript
<h1>hello</h1>
```

**Comment by ltsuda** [comment]
Regarding the mounting problem, do you think that should be like this?

`const component = await mount(<Button />);`

**Comment by snorresovold** [comment]
Nope that doesn't work. That is how you test for example React components but not Svelte components. There are examples on ways to do it in the link I sent on my first post.

https://playwright.dev/docs/test-components

**Comment by yury-s** [comment]
This is a known issue with Svelte aliasing: https://github.com/microsoft/playwright/issues/19411. Folding this issue into it.
