### ISSUE TITLE
[Feature] Global Chrome Extension Context

### ISSUE THREAD

**Issue by timlanahan** [microsoft/playwright#21193]
It would be great if we could load a chrome extension only once and reuse the same persistent context across multiple tests.  Right now, if I load the chrome extension in `global-setup.js`, I am unable to get the chromium instance that contains the extension.  I need to test communication between a dApp and a browser extension, so the dApp and the extension should share the same browser instance.

Currently, if follow the [docs](https://playwright.dev/docs/chrome-extensions), each time I run a new test, a new chromium instance launches with the persistent context.

I'm trying to test a relatively heavy chrome extension, so I would prefer to load the chrome extension globally and then re-use the context in each of my subsequent tests.

As a hacky work around, I tried to defer a promise like so 

```javascript
// global-setup.js
import { chromium } from '@playwright/test'
import testConfig from './config'

let context

let contextIsResolved
const contextIsLoaded = new Promise(
  (resolve) => (contextIsResolved = resolve)
)

export default async (config) => {
  const pathToExtension = testConfig.browserExtensionPath
  context = await chromium.launchPersistentContext('', {
    headless: false,
    args: [
      `--disable-extensions-except=${pathToExtension}`,
      `--load-extension=${pathToExtension}`,
    ],
  })
  contextIsResolved(context)
  await context.waitForEvent('page')
  // extension is after the blank ghost page
  // see issue https://github.com/microsoft/playwright-python/issues/689
  const extensionPage = context.pages()[1]
}

export const getGlobalContext = async () => {
  await contextIsLoaded
  return context
}

// some-test.spec.js
import { getGlobalContext } from '../global-setup'

test.beforeAll(async ({ context }) => {
  const context = await getGlobalContext() // this just hangs forever
})
```
The issue with the above (which I thought might work) is that the promise never resolves and it hangs indefinitely. Thus, the test suite fails.

I tried all tests in a single file like below

```javascript
// main.spec.js
import { test, expect } from '../fixtures/browser-extension'
import { createPageModelObject } from '../page-object-models/base-page-object-model';

let extensionPage // reference for all the tests

test.describe.configure({ mode: 'serial' });

test.beforeAll(async ({ context }) => {
  extensionPage = context.pages()[1]
})

test.describe('Test 1', () => {
  let page
  test.beforeAll(async ({ context }) => {
    page = createPageModelObject()
  })

  test('should do stuff', async () => {

  })
})

test.describe('Test 2', () => {
  let page
  test.beforeAll(async ({ context }) => {
    page = createPageModelObject()
  })

  test('should do stuff', async () => {
    
  })
})
```
The problem with the above is that my browser tears down and setups up in each new `describe` + `beforeAll` block.  Ideally this wouldn't be the case so that I could reuse a single extension window.

**Comment by yury-s** [comment]
> The issue with the above (which I thought might work) is that the promise never resolves and it hangs indefinitely. Thus, the test suite fails.

This happens because global setup and test scripts run in two different processes, so you cannot access variables initialized in global setup from the test.

Instead of that you can create launch the persistent context with extension in [worker scoped](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) fixture that would be very similar to what is described in [this example](https://playwright.dev/docs/chrome-extensions#testing):

```ts
// ../fixtures/browser-extension.ts
// fixtures.ts
import { test as base, chromium, type BrowserContext, type Page } from '@playwright/test';
import path from 'path';

let _extensionPage: Page | undefined;

export const test = base.extend<{
  context: BrowserContext;
  extensionPage: Page;
}, {
  contextWithExtension: BrowserContext;
}>({
  contextWithExtension: [async ({ }, use) => {
    const pathToExtension = path.join(__dirname, 'my-extension');
    const context = await chromium.launchPersistentContext('', {
      headless: false,
      args: [
        `--disable-extensions-except=${pathToExtension}`,
        `--load-extension=${pathToExtension}`,
      ],
    });

    await context.waitForEvent('page')
    // extension is after the blank ghost page
    // see issue https://github.com/microsoft/playwright-python/issues/689
    _extensionPage = context.pages()[1]

    await use(context);
    await context.close();
  }, { scope: 'worker' }],

  // Override context fixture to reuse same worker scoped context
  context: async ({ contextWithExtension }, use) => {
    await use(contextWithExtension);
  },

  extensionPage: async ({ contextWithExtension }, use) => {
    await use(_extensionPage!);
  },
});
export const expect = test.expect;
```

Then you can use it like this:

```ts
// main.spec.js
import { test, expect } from '../fixtures/browser-extension'
import { createPageModelObject } from '../page-object-models/base-page-object-model';

test.describe('Test 1', () => {
  let page
  // note that only worker scoped fixtures are available in beforeAll
  test.beforeAll(async ({ contextWithExtension, extensionPage }) => {
    page = createPageModelObject()
  })

  test('should do stuff', async ({ context, extensionPage }) => {
  })
})

test.describe('Test 2', () => {
  let page
  test.beforeAll(async ({ contextWithExtension, extensionPage }) => {
    page = createPageModelObject()
  })

  test('should do stuff', async () => {
    
  })
})
```

Will this work for you?

**Comment by timlanahan** [comment]
@yury-s thanks for the fast reply.  Yep that works!  Looks like I maybe raised a duplicate issue as well.  I found a similar suggestion in this issue https://github.com/microsoft/playwright/issues/11108#issuecomment-1001797698

Perhaps this would be worth including in the docs you mentioned above.

Thanks again for the help 💯

**Comment by timlanahan** [comment]
One other thought.  It might be nice, though, to start the extension once in `global-setup.js` so that I could spin off multiple parallel browsers / tests with the preloaded extension.

The method you described works well, but just a thought if someone wanted to run tests (on a bunch of dApps in my case) in parallel but did not want load the extension fresh for each test .

**Comment by yury-s** [comment]
> One other thought. It might be nice, though, to start the extension once in global-setup.js so that I could spin off multiple parallel browsers / tests with the preloaded extension.

Parts external to the browser can be placed into the global setup script or to a [setup project](https://playwright.dev/docs/api/class-testproject#test-project-dependencies) but the extension itself has to be loaded by every new browser instance, we cannot preload it.

Closing this report as the original problem was resolved. Feel free to file a new bug if you need further assistance.
