### ISSUE TITLE
[Feature] Documentation example of n users authenticating via UI in a global setup file

### ISSUE THREAD

**Issue by bsteffensTempus** [microsoft/playwright#21190]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I'm looking for the recommended way to have a setup file generate multiple `state.json` type files. Should the setup file create multiple contexts or browser instances or both?

The use case here is a regression testing type sweet where n roles are tested within the suite. The non default type users are isolated in their own `.spec` files but call the same fixtures as the default user.

Any help is appreciated!

**Comment by yury-s** [comment]
Can you elaborate why the [suggested approach](https://playwright.dev/docs/auth#multiple-signed-in-roles) does not work for your use case?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
