### ISSUE TITLE
[BUG] Error - Element out of the viewport if the application page zoom set to 80%

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#21192]
My application page zoom is set to 80%

```.pageZoom {
  zoom: 80%;
}
```
Playwright throws error `Error - Element out of the viewport` and `page.click` does not work either. After I revert this change and set it to back to 100% then all works fine. 

Is it possible to fix this issue or is there any work around?

**Comment by yury-s** [comment]
I can reproduce this with a simple example:

```ts
test('should click zoomed button, async ({ page }) => {
  await page.setContent(`<style>
  button {
    zoom: 50%
  }
  </style>
  <button>Click target</button>
  `);
  await page.click('button', { timeout: 1000 });
});
```

**Comment by yury-s** [comment]
There was a similar report in the past https://github.com/microsoft/playwright/issues/7642 which was closed due to low demand. Keeping this issue open to collect more feedback and see if there is enough interest in the feature for us to support it.

**Comment by yury-s** [comment]
Since zoom property is [not a standard](https://developer.mozilla.org/en-US/docs/Web/CSS/zoom) and not on any standards tracks we are not planning to support it.

**Comment by amtayal** [comment]
I am having the similar issue at click event and seeing an `Error: locator.click: Element is outside of the viewport`

**Comment by bluedot74** [comment]
`zoom` is now supported by all major browsers: https://developer.mozilla.org/en-US/docs/Web/CSS/zoom

Could we re-open this?

**Comment by kajetanarab** [comment]
@yury-s Is there any possibility to handle zoom in playwright ? Workarounds and hack also are fine. But definitely should be reopened.

**Comment by VadymSavchenko** [comment]
Main thread: #2497
