### ISSUE TITLE
Does Playwright for Java have assertion retries on code block like Playwright for Node.js

### ISSUE THREAD

**Issue by rohit-walia** [microsoft/playwright#21209]
Wondering if there is any Java equivalent for retrying on some code block with assertions like this one: https://playwright.dev/docs/test-assertions#retrying
If so, could you kindly provide an example as i can't find it in the Playwright for Java docs.

**Comment by pavelfeldman** [comment]
Retrying is a feature of the test runner, not the Playwright Library. Since we only port Playwright Library to all the languages and encourage the use of the platform-specific test runners, you should be looking for this feature there.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
