### ISSUE TITLE
[BUG] Unable to view tracer file properly if too many tabs opened

### ISSUE THREAD

**Issue by Gokulnath31** [microsoft/playwright#21215]
**Context:**
- Playwright Version: 1.29.2
- Operating System: Mac
- Node.js version: 16.17.0
- Browser: Chromium

**Unable to view tracer file properly**

Tracer file is not scrollable when there are too many tabs present in that browser session.
Tracer has a config of saving screenshots and snapshots.

I was able to fix it by manually adding a max-height and overflow-y: auto by inspecting.

Sample tracer: https://drive.google.com/file/d/18uSbs2vxn3pKKM0O8eHej2uo-3ThExHs/view?usp=sharing

**Comment by pavelfeldman** [comment]
It looks like you are pushing it, we don't expect test to have more than a handful of tabs in the same context. Could you share your test code?

**Comment by pavelfeldman** [comment]
We need more information to act on this report, please file a new one and link to this issue when you get back to it!
