### ISSUE TITLE
[BUG] getByRole - matching option with regex and extra whitespaces

### ISSUE THREAD

**Issue by ipatalas** [microsoft/playwright#21213]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Mac
- Node.js version: 16.18.1
- Browser: Chromium

**Code Snippet**

Repro:

```javascript
import { Browser, chromium, Page } from 'playwright-chromium';

describe(`Test`, () => {
    let browser: Browser
    let page: Page

    beforeAll(async () => {
        browser = await chromium.launch()
        page = await browser.newPage()
    })
    afterAll(async () => {
        await browser.close()
    })

    it('with regex', async () => {
        await page.setContent(`<select><option>value  with spaces</option></select>`)

        const option = page.getByRole('option', { name: /value  with spaces/ })
        expect(await option.count()).toBe(1)
    })

    it('with regex 2', async () => {
        await page.setContent(`<select><option>value  with spaces</option></select>`)

        const option = page.getByRole('option', { name: /value with spaces/ })
        expect(await option.count()).toBe(1)
    })

    it('without regex', async () => {
        await page.setContent(`<select><option>value  with spaces</option></select>`)

        const option = page.getByRole('option', { name: 'value  with spaces' })
        expect(await option.count()).toBe(1)
    })
})
```

**Describe the bug**

If option contains any extra whitespaces in the middle it's impossible to match it against a regex. Interestingly when I normalize that double space to a single space within a regex then it starts matching (see `with regex 2` test). 
When matching without regular expressions it works as expected. 
Unfortunately I need to use regex in this case because I need `startsWith` instead of `contains` match. I know I can work this around in at least two different ways but using anchored regex is saving us couple of LoC in here.

I'm happy to share more info if needed.

**Comment by pavelfeldman** [comment]
If you put this in a browser URL bar:

```data:text/html,<select><option>value  with spaces</option></select>```

And inspect, you'll see that there is only one space:
<img width="330" alt="Screenshot 2023-02-27 at 8 42 03 AM" src="https://user-images.githubusercontent.com/883973/221625267-b8025b7a-cfab-42c4-85db-d2f00fddf3be.png">

So it looks like Playwright is working as expected. You can always use `\s+` in regex to match and number of spaces too.

Btw, use `@playwright/test` and its web assertions like `await expect(option).toHaveCount(1)`. Otherwise all your tests will be flaky.

**Comment by ipatalas** [comment]
Well, let me disagree for two specific reasons:
- Browser is normalizing those extra spaces before it gets displayed but please double click option label and see what happens then: 
![image](https://user-images.githubusercontent.com/2623329/221633050-c93d4fc9-53a7-4934-86e2-2de5a646f068.png)
- why does non-regex version works fine then? It will only match if the number of spaces is exactly as in the option? that means those two are inconsistent between each other

> Btw, use `@playwright/test` and its web assertions like `await expect(option).toHaveCount(1)`. Otherwise all your tests will be flaky.

I know, it's been just a quick test and I didn't have `@playwright/test` in that project.

**Comment by ipatalas** [comment]
Ok, did some additional digging and it seems like I've got myself an answer.

```ts
import { test, expect } from "@playwright/test";

const testOption = (testName: string, name: string | RegExp) => {
    test(testName, async ({ page }) => {
        const option = page.getByRole('option', { name })
        await expect(option).toHaveCount(1)
    })
}

test.describe(`Double spaces`, () => {
    test.beforeEach(async ({ page }) => {
        await page.setContent(`<select><option>value  with spaces  </option></select>`)
    })

    testOption('regex', /value  with spaces/)
    testOption('regex2', /value with spaces/)
    testOption('string', 'value  with spaces')
    testOption('string2', 'value with spaces')
    testOption('string3', 'value        with     spaces')
})
```

Still only the one with regex fails. This leads me to think that both sides of the equation are normalized. Only RegEx is not because that would be difficult, potentially changing it's meaning so it's just a side effect.

That's not good because the dropdown we're trying to automate in this case does contain double spaces in some cases (and we don't control that) and we need `startsWith` but apparently RegEx is not the best option here as the option to pick from the dropdown is of course dynamic and comes from a runtime argument so that would mean building a regex and normalizing the spaces on our own which will look like magic for people who don't dig into this issue.
I think we need to live with more verbose code then.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by ipatalas** [comment]
> Here is our doc: https://playwright.dev/docs/next/locators#locate-by-text

All right, I missed that, thanks! This kind of applies to `getByText` but I guess it actually applies to all places which match by text like `name` in `getByRole` in my case.
Still, good to know, it wasn't obvious behavior.
