### ISSUE TITLE
[BUG] Button click with window open&close not working for Firefox

### ISSUE THREAD

**Issue by Rom4ig** [microsoft/playwright#21225]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows/docker(linux)
- Node.js version: 18.13.0
- Browser: Firefox

**Code Snippet**

```typescript
import { test } from '@playwright/test';

test.only('should work', async ({ page }) => {
    await page.setContent('<button>clickme1</button>');
    await page.$eval('button', button => button.addEventListener('click', () => {
        window.open('');
    }, false));
    const [popup] = await Promise.all([
        page.waitForEvent('popup'),
        page.locator('button').click(),
    ]);
    await popup.setContent(`<button>clickme2</button>`);
    await popup.$eval('button', body => body.addEventListener('click', () => {
        window.open('');
        window.close();

    }));
    await Promise.all([
        popup.locator('button').click(), 
        popup.waitForEvent('popup'), // throws in Firefox, but not in Chromium
    ]);
});
```
**Console output**
![image](https://user-images.githubusercontent.com/43033763/221556332-6828fe81-363a-4507-a1b9-a3d566ee813a.png)

This click works for **Chrome** and **WebKit** but doesn't work for **Firefox**.

**Comment by Rom4ig** [comment]
similar to
https://github.com/microsoft/playwright/issues/20093

**Comment by yury-s** [comment]
There is a race between closing the opener page and reporting the popup, in Firefox popup event comes a little late when the page has already closed, you can see it with the following code:

```js
  const [, result] = await Promise.all([
    popup.locator('button').click(),
    Promise.race([
      popup.waitForEvent('popup').then(() => 'popup'),
      popup.waitForEvent('close').then(() => 'closed'),
    ])
  ]);
  console.log(result);
```

 You get the error because we don't dispatch events on closed page. To avoid the exception you can wait for 'page' event on the context object:

```js
  const [newPage] = await Promise.all([
    popup.context().waitForEvent('page'),
    popup.locator('button').click()
  ]);
```
Will this work for you?

**Comment by Rom4ig** [comment]
Yes, I understand why this is happening. If it works in chrome, it would be nice if it worked in fox as well. Your method will work without errors.

**Comment by yury-s** [comment]
I agree that it would be nice to align FF with other browsers, but unfortunately there are technical reasons why the initialization may take longer in FF and cause the `popup` event to arrive after `close` event.  Considering cost of a fix, this being an edge case, and existing workaround, we are not planning to address this difference in the behavior. Closing this report.
