### ISSUE TITLE
[Feature] Extending the new Project "Dependencies" Feature

### ISSUE THREAD

**Issue by amitz** [microsoft/playwright#21229]
The new project dependencies feature that got introduced in 1.31 is awesome. End to end tests tend to have a lengthy setup, and the ability in case of a failure to see screenshots/video/trace or even just retry is amazing (which beats tailoring all that by yourself in the "old" global setup). This brings Global-setup closer to the "Test" domain (using fixtures...), as it currently feels very detached. For example: Expect timeout defined in the config file won't apply on Global feature. 

What would be great addition, is ability to do the same with global-teardown. The issue right now, is that dependencies only run in-case of success. Sometimes, tests will fail, and yet - you still want to run the global-teardown for a cleanup. A flag which allow you to control if you want to run the dependency ALL attempts or just in case of the dependency is completely green would be a neat solution for that. 

Also, as of today, the way suggested to share information between global-setup/global tear-down is using environment variables.  Again, this is being a typical workflow (you create Entity with a random name on the Global-setup, and want to remove it during Teardown). If you're using global-setup as a PROJECT now, it means it spin it own worker. Setting environment variables on that worker, won't allow you to access them during tear-down due to separation. What we are doing now is to save the configuration in a file, but perhaps there's a more elegant solution in here. 

Thanks for an awesome job guys!

**Comment by dgozman** [comment]
#22696 addresses this:
- introduces `teardown` property that is equivalent to global setup, but in the deps world;
- makes sure that `process.env` changes from setup are inherited in the teardown.

**Comment by amitz** [comment]
Awesome! Thank you very much. Is there an option for me to test is before `1.34` is being released? Outside of using `yarn` to pull from the repository directly?

**Comment by dgozman** [comment]
@amitz Yep, you can try a [canary release](https://playwright.dev/docs/canary-releases).

**Comment by amitz** [comment]
@dgozman I did some early testing on that, and this is working great! Thank you! Two things I noticed:

1. I'm not sure why, but it seems like order of Projects on the list matters. This work for me:

```
  projects: [
    {
      name: 'global-setup',
      testDir: './',
      testMatch: /global-setup\.js/,
      retries: 0,
    },
    {
      name: 'global-teardown',
      testDir: './',
      testMatch: /global-teardown\.js/,
      retries: 0,
    },
    {
      name: 'chromium',
      dependencies: ['global-setup'],
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1920, height: 1080 },
        storageState: '.auth/user.json',
      },
      teardown: 'global-teardown',
    },
  ],
```

This didn't (moving Global-Teardown to the end): 

```
  projects: [
    {
      name: 'global-setup',
      testDir: './',
      testMatch: /global-setup\.js/,
      retries: 0,
    },
    {
      name: 'chromium',
      dependencies: ['global-setup'],
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1920, height: 1080 },
        storageState: '.auth/user.json',
      },
      teardown: 'global-teardown',
    },
    {
      name: 'global-teardown',
      testDir: './',
      testMatch: /global-teardown\.js/,
      retries: 0,
    },
  ],
```

2. If any of the project dependencies fail, the project won't run. That's something I feel like I want to control. For example, I might have 90 tests that can run in parallel, and 10 that have to be run in order (because they affect the global state of the systems and therefore can't run in parallel). I can't create a Project that runs in parallel, and another project that depends on it (that runs in a serial manner), because if there's a test failure in the parallel project, It will never run the serial project.

**Comment by dgozman** [comment]
> but it seems like order of Projects on the list matters

It should not. When you say "this didn't work" - what happens instead? Any errors? Could you share more details please?

> 90 tests that can run in parallel, and 10 that have to be run in order 

I think you are after some notion of "critical section" or something like that. See #14084 for similar requests. We will solve it separately, `dependencies` feature does not solve it today.

**Comment by amitz** [comment]
> It should not. When you say "this didn't work" - what happens instead? Any errors? Could you share more details please?

The specific Project would just not run. I tried to play around it during the weekend, and I wasn't able to reproduce it. I upgraded to the newest canary release a couple of times in-between, so it could be that, or me doing something wrong. I will try to downgrade the version and check again, and will post if relevant, thanks! :)

> I think you are after some notion of "critical section" or something like that. See https://github.com/microsoft/playwright/issues/14084 for similar requests. We will solve it separately, dependencies feature does not solve it today.

Sounds good! Thank you!
