### ISSUE TITLE
[BUG] [Ubuntu] [WebKit - Safari - Headless] Click misses target due to scrolling events. 

### ISSUE THREAD

**Issue by loxinchi** [microsoft/playwright#21228]
**Context:**
- Playwright Version: `1.31.1`
- Operating System: 

```javascript
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

- Node.js version: `v18.14.2 `, `npm v9.5.0`
- Browser: `WebKit - Safari - headless`

**Test Repository**
[Link](https://github.com/loxinchi/Safari-issue-playwright-1.31.1)

**Describe the bug**
Click misses target due to continuous scrolling events.

**Logs**
```
locator.click: Target closed
=========================== logs ===========================
waiting for locator('text.signatureText')
  locator resolved to <text x="142.272" y="43.5424" font-weight="400" text-a…>…</text>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <rect class="bg" width="284.544" stroke="#33b1dd" stro…></rect> intercepts pointer events
retrying click action, attempt #1
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <rect class="bg" width="284.544" stroke="#33b1dd" stro…></rect> intercepts pointer events
retrying click action, attempt #2
  waiting 20ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <rect class="bg" width="284.544" stroke="#33b1dd" stro…></rect> intercepts pointer events
retrying click action, attempt #3
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="headline___YJCLC">…</div> from <div data-test="headline" class="stickySection___15We…>…</div> subtree intercepts pointer events
retrying click action, attempt #4
  waiting 100ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <div class="headline___YJCLC">…</div> from <div data-test="headline" class="stickySection___15We…>…</div> subtree intercepts pointer events
retrying click action, attempt #5
  waiting 500ms
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  <rect class="bg" width="284.544" stroke="#33b1dd" stro…></rect> intercepts pointer events
```

**Comment by pavelfeldman** [comment]
Safari brings me to a login screen when I try it locally, so I can't debug the issue.

**Comment by loxinchi** [comment]
@pavelfeldman 
The URL is correct. 
Could you please try to clear browser cache cookies(`Privacy->Manage Website Data->Remove all`) and try again.
It should work.

**Comment by pavelfeldman** [comment]
No luck, when I run `npx playwright wk https://staging.scrive.com/new/sign/9221714692412794047/9221932570717035733`, it opens the sign in page.

**Comment by loxinchi** [comment]
Thanks for the information.

Not sure if you are awarded that the URL in the code is: `https://staging.scrive.com/s/9221714692412794047/9221932570717035733/5df4b27308550043`
once you access it, 
you will be redirected to the URL in your previous comment.

Is it difficult to debug in this case?

**Comment by pavelfeldman** [comment]
Yeah, I guess I copied the URL after redirect. I can repro!

**Comment by loxinchi** [comment]
> Yeah, I guess I copied the URL after redirect. I can repro!

Great!! Thank you so much for checking @pavelfeldman !

**Comment by dgozman** [comment]
@loxinchi I was able to reproduce the issue, and there is indeed `<rect class="bg" width="284.544" stroke="#33b1dd" stro…></rect>` that stays right on top of the `text.signatureText`. Therefore, playwright complains that clicking on the `text` is not going to actually click on the text, but rather on the overlaying `rect`, and includes this in the error message.

You should either use `force: true` option, or click on the `rect`, not `text`. Let me know if that helps.

**Comment by dgozman** [comment]
Upon further inspection, the problem is that `text` is rendered in Safari in a different place than in `Chrome`/`Firefox`. At the same time, the actual `Click to sign` text is rendered in the same place in all browsers.

I'd recommend to replace
```ts
  await page.locator("text.signatureText").click();
```
with
```ts
  await page.getByText("Click to sign").click();
```

This makes things work for me locally. Overall, we do not recommend to use CSS selectors that are tied to your DOM, and instead recommend to stick with user-visible attributes like text. [See docs](https://playwright.dev/docs/locators#locate-by-css-or-xpath) for more details.

**Comment by loxinchi** [comment]
Thank you @dgozman so much.
The issue is fixed by the suggestions!!
