### ISSUE TITLE
How to run specific(selected) test case to run on specific browser like chrome

### ISSUE THREAD

**Issue by ferozali690** [microsoft/playwright#21233]
**Context:**
- Playwright Version: [1.27.1]
- Operating System: [Mac]
- Node.js version: [18.14.1]
- Browser: [All, Chromium, Firefox, WebKit]

**Code Snippet**

I have many playwright test cases, but I want some of the selected test cases to only run on chrome, now if I want the "test 1 "case to run only on chrome and the rest of them by default should run on every browser, how can that be achieved?

```
test('test 1', async () => {
   
  });

 test('test 2', async () => {
   
  });

 test('test 3', async () => {
   
  });
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
