### ISSUE TITLE
[ Question ] Dynamically loading external script into playwright testing DOM ?

### ISSUE THREAD

**Issue by divyanshu-rawat** [microsoft/playwright#21236]
Hi, 

I am doing component testing using Playwright the test-component I am mounting uses a hook `useAnalytics()` that is responsible for loading the analytics script into the React DOM dynamically.

Normally it works fine, when I run my react app I can see it in my HTML DOM, but in the test environment the script gets loaded but I can’t see it as a part of my HTML DOM when I inspect using dev tools.

```js
import { useAnalytics } from '@hooks/useAnalytics';

export const MyComponent = () => {
  const { shareEvent } = useAnalytics();

  return (
    <>
      <button onClick={() => shareEvent("PDP")}>shareEvent</button>
    </>
  );
};
```
When I manually add it to the index.html that playwright provides for the testing DOM then it works.

SUMMARY: If a react hook dynamically loads a external script then how to add that script to the playwright testing DOM, is there any playwright offers to add script dynamically to it DOM that are being loaded by a hook that we are using for component testing.

**Comment by pavelfeldman** [comment]
I'm not sure I understand the question well. Could you share a minimal reproduction of the issue along with your expectations and actual behavior?

**Comment by pavelfeldman** [comment]
You can also call:
```js
await page.addScriptTag({ url: 'https://tags.tiqcdn.com/utag/adidas/adidasglobal/prod/utag.js' });
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
