### ISSUE TITLE
[BUG] Playwright Codegen windows appear transparent

### ISSUE THREAD

**Issue by lamaqdahodwala** [microsoft/playwright#21237]
**Context:**
- Playwright Version: Playwright/Test 1.31.1
- Operating System: WSL
- Node.js version: 18.12.1
- Browser: N/A
- Extra: Used with pnpm

**Code Snippet**
![image](https://user-images.githubusercontent.com/74932012/221717894-120f1d3f-db47-4429-aa39-cc5f08662524.png)

**Describe the bug**

Whenever I try running `playwright codegen`, I always receive a transparent window. However, the page still manages to check if the server is up, throwing an error if it isn't. You can see that the playwright inspector and the browser window are both blank.

**Comment by pavelfeldman** [comment]
I have no idea what is happening, we need to reproduce it to be able to fix it and given that you are using older Playwright on WSL it is unlikely we are going to be able to re-create this scenario.

**Comment by pavelfeldman** [comment]
Unfortunately, there is nothing we can do w/o ability to repro, closing as non-actionable

**Comment by vgaicuks** [comment]
Hello, @lamaqdahodwala did you fix the issue with blank-transparent windows? Could you please give an advice how to handle with this? Thank you in advance.

**Comment by ahernd2** [comment]
Seeing same issue. Anyone know a fix for this?

**Comment by vgaicuks** [comment]
@ahernd2  use `gpuSupport=false` at wsl config. Look at [this issue](https://github.com/microsoft/playwright/issues/21813#issuecomment-1494357275)

**Comment by ahernd2** [comment]
@vgaicuks That works. Thanks a million!
