### ISSUE TITLE
[Feature] export Devices from playwright-core/types/types.d.ts

### ISSUE THREAD

**Issue by muuvmuuv** [microsoft/playwright#21247]
So, I have a use-case where I want to loop over a list of devices to generate app screenshots for Apple, Android and MS Store. I saw that playwright has `devices` exported with a list of devices, but this is an object, so I can't type guard my object.

This is what I would ideally like to have. The benefit is that I can always make sure I use supported devices and catch errors early.

<img width="675" alt="Bildschirm­foto 2023-02-28 um 08 07 52" src="https://user-images.githubusercontent.com/11534760/221779693-e2611135-68de-4db1-93c6-4edc7cff2553.png">

**Comment by mxschmitt** [comment]
You can do:

```ts
type DeviceDescriptors = typeof import('@playwright/test').devices;
type Device = DeviceDescriptors[keyof DeviceDescriptors];
```

would that work for you? DeviceDescriptors is the whole map which should be also enough for your use-case.

**Comment by muuvmuuv** [comment]
Hm, no, unfortunately `keyof DeviceDescriptors` does not work. And I don't need the descriptor, just the list of device names.

**Comment by muuvmuuv** [comment]
<img width="708" alt="Bildschirm­foto 2023-02-28 um 09 39 03" src="https://user-images.githubusercontent.com/11534760/221798911-846d7231-5ba4-4142-9d74-3493573f13bf.png">
<img width="540" alt="Bildschirm­foto 2023-02-28 um 09 38 46" src="https://user-images.githubusercontent.com/11534760/221798917-1faeb6d1-6999-4f14-94da-bfb2566dcb79.png">

Really strange. Seems like typescript can do that if a type is converted to const and back?

**Comment by pavelfeldman** [comment]
This works for me:

```js
import { devices } from '@playwright/test';
type DeviceDescriptor = typeof devices['Desktop Chrome'];
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by muuvmuuv** [comment]
Hm no. I think you missunderstand but that is ok. I am using plain strings now. Which works..
I dont want the value typed but all keys.
