### ISSUE TITLE
[Feature] https://playwright.dev/ should have a link to GitHub

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2124]
I've been so accustomed to using github to view API docs, but now that https://playwright.dev/ exists, it would be nice to actually have a link there to point back to GitHub.

**Comment by mxschmitt** [comment]
[Stackoverflow](https://stackoverflow.com/questions/tagged/playwright)  and Slack would also be useful.

**Comment by mxschmitt** [comment]
In the footer there are links for Stackoverflow, GitHub and Slack now.
