### ISSUE TITLE
Error: Playwright page not initialized, it must be done by using {page} in the test function parameter.

### ISSUE THREAD

**Issue by JeevanHB** [microsoft/playwright#21246]
Error: Playwright page not initialized, it must be done by using {page} in the test function parameter.

   at ..\..\playwright-utils.ts:11

   9 | export function getPage(): Page {
  10 |  if (!currentPage) {
> 11 |          throw new Error('Playwright page not initialized, it must be done by using {page} in the test function parameter.');
     |                ^
  12 |  }
  13 |  return currentPage;
  14 | }

We are observing this issue, Please let us to resolve this issue.
![image](https://user-images.githubusercontent.com/52357464/221776110-ab7b3636-7e26-476f-b76d-1e4d11298ed1.png)

We have import all the required utils from playwright but still we are facing issue.
![image](https://user-images.githubusercontent.com/52357464/221776791-48551d18-5d60-4c87-af70-096f4985bba9.png)

**Comment by mxschmitt** [comment]
Can you provide us a reproduction which we can run locally? This does not look like any code by us or code which we recommend. Getting the page is only supported via fixtures, see the official docs for that: https://playwright.dev/docs/writing-tests

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
