### ISSUE TITLE
[BUG]Handling new browser context window does not work as expected in headless mode in playwright

### ISSUE THREAD

**Issue by MrudullaAnand** [microsoft/playwright#21256]
**Context:**
- Playwright Version: 1.29.1
- Operating System: Linux
- Node.js version: v18.12.1
- Browser:  Chromium
- Extra: Running in headless mode

**Code Snippet**

test("Clicking on any of the table row opens its respective report in defined file format", async ({
  context,
  page,
}) => {
  //On clicking of any of the row in the webtable, respective report is opened in new window in defined file format
  const poManager = await selectPatientAndToolIcon(
    props.get("reportManagerPatientIdentifer").replaceAll('"', "").toString(),
    page
  const listOfReports = await poManager.getListOfReportsPage();
  await listOfReports.verifyReportManagerToolSelected();
  await listOfReports.verifyViewingOfReport(context, expectedFileTypes);
  );
  

 async verifyViewingOfReport(context, expectedFileTypes) {
    for (let i = 0; i < (await expectedFileTypes.length) - 1; i++) {
      await this.fileTypeFilteringIcon.click();
      await this.dropdownValues.nth(0).click();

      const [newPage] = await Promise.all([
        context.waitForEvent("page"),
        await this.reportTypeColumnValues.nth(0).click(),
      ]);
      console.log("URL is ", newPage.url());
      await newPage.waitForLoadState("networkidle");
   
      if (expectedFileTypes[i] == "pdf") {
        await expect(newPage.locator(this.pdfFileLocator)).toBeVisible();
      } else {
        await expect(newPage.locator(this.textFileLocator)).toBeVisible();
      }
    }
  }

**Describe the bug**
When clicked on a table row, it opens a file in pdf or text format in a new browser window. The files are in azure blob storage container, clicking on table row, retrives the files from blob container and opens the files in new browser window.
The automation for above scenario is working fine when ran in headed mode. But in headless mode, when clicked on table row it is unable to load new browser window and display the file in it 

**Getting below error
page.waitForLoadState: Navigation failed because page was closed!
=========================== logs ===========================
  "networkidle" event fired
============================================================**

   at ../page-objects/UI/report-manager/listOfReports.js:877

  875 |       ]);
  876 |       console.log("URL is ", newPage.url());
> 877 |       await newPage.waitForLoadState();
      |                     ^
  878 |       if (expectedFileTypes[i] == "pdf") {
  879 |         await expect(newPage.locator(this.pdfFileLocator)).toBeVisible();
  880 |       } else {

    at ListOfReports.verifyViewingOfReport (/opt/atlassian/pipelines/agent/build/page-objects/UI/report-manager/listOfReports.js:877:21)
    at /opt/atlassian/pipelines/agent/build/tests/UI/report-manager/reportManagerWebTable/reportManagerWebTable.spec.js:411:3

Add any other details about the problem here.

**Comment by pavelfeldman** [comment]
Please provide self-contained snippet that demonstrates the bug that we can run locally. Otherwise we can't act on the issue.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
