### ISSUE TITLE
[BUG] trace on - causing Test timeout tearing down playwright configuration.

### ISSUE THREAD

**Issue by mwhebert** [microsoft/playwright#21259]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Windows
- Node.js version: 18.14.2 - also 14.18.1
- Browser:  All
- Extra: just turning on (trace: "on" in playwright.config.json)

## System:
 - OS: Windows 10 10.0.22621
 - Memory: 9.79 GB / 31.81 GB
## Binaries:
 - Node: 18.14.2 - ~\AppData\Local\nvs\node\18.14.2\x64\node.EXE
 - npm: 9.5.0 - ~\AppData\Local\nvs\node\18.14.2\x64\npm.CMD
## Languages:
 - Bash: 4.4.23 - C:\Program Files\Git\usr\bin\bash.EXE

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test } from "@playwright/test";

test("with trace", async ({ page }) => {
  // trace: on in playwright.config.json
  await page.goto("https://playwright.dev/");
  await page.getByRole("link", { name: "API", exact: true }).click();
  for (let i = 0; i < 20; i++) {
    await page.getByRole("button", { name: "Search" }).click();
    await page.getByPlaceholder("Search docs").fill("console");
    await page
      .getByRole("option", { name: "ConsoleMessage", exact: true })
      .getByRole("link", { name: "ConsoleMessage" })
      .click();
    await page.getByRole("button", { name: "Search" }).click();
    await page.getByPlaceholder("Search docs").fill("Logger");
    await page
      .getByRole("option", { name: "Logger", exact: true })
      .getByRole("link", { name: "Logger" })
      .click();
    await page.getByRole("button", { name: "Search" }).click();
    await page.getByPlaceholder("Search docs").fill("Coverage");
    await page.getByPlaceholder("Search docs").press("Enter");
  }
  console.log("Got Here - out of loop");
});
```

The test runs fine with trace "off" or "on-first-retry".  Trace "on" or "retain-on-failure" exceeds time out (even if timeout extended in config).  Looping fewer times does work, so I assume the time to generate the trace is causing the timeout, but I would not expect the "test" maximum timeout to include the trace generation.  Maybe there needs to be a separate timeout for that since generating the trace is required for diagnostics.

Zip of project included

[trace-fail-project.zip](https://github.com/microsoft/playwright/files/10850643/trace-fail-project.zip)

**Comment by dgozman** [comment]
Error message idea:
`Test ran within the given timeout budget. But tearing down the test ran out of time. Please allow more time for your test, since teardown is attributed towards the test timeout budget.`

**Comment by mwhebert** [comment]
Does the trace.zip take that long to generate?  In some of my other cases it was well over 2 minutes after increasing the timeout.

**Comment by dgozman** [comment]
@mwhebert If you could share a repro where trace is taking too much time, we would be happy to look into it.

**Comment by mwhebert** [comment]
@dgozman - I can reproduce the issue with the zipped project that is attached to this issue.  Changing the timeout in the playwright.config.json (timeout: 3 * 60 * 1000) still fails.

**Comment by mwhebert** [comment]
@dgozman - So after increasing the timeout and adding to the test (test.slow()) it did generate the report and included it into the html report.  I did take quite some time for the test to complete.  I change the trace to retain-on-failure instead, since the test does not actually fail I was expecting to to run faster since there is no need to complete the trace file.  To my surprise it still took quite some time aven though the trace is not included in the html report.  Is this expected?

**Comment by mwhebert** [comment]
@dgozman - So I got by my issue by increasing the timeout and setting trace to 'on-first-retry' which may be what I should have done in the first place.  

I guess I still would not expect the "timeout" value to include the time it takes to create the trace though.  I want the timeout to be the "expected" time it should take a test to run only, so that if it exceeds that the test fails.  It seems like there should be a separate timeout for the time it takes to generate the trace so that every test timeout does not have to be large just to accommodate the trace generation time.

Is there a way to do this?  Am I missing how the setting work?

Thanks in advance!

**Comment by dgozman** [comment]
@mwhebert 

- I tried your repro locally, and it takes less than a second to record the trace. Could you please attach the trace file here? One idea is that it waits for some network response that hangs, or something like that. Seeing the actual trace file might help us to diagnose the issue.

- For the timeout issue, there is currently no way to have a separate timeout for the test vs trace recording. Sorry for the inconvenience.

**Comment by dgozman** [comment]
@mwhebert Thank you for the trace, I looked inside. It seems like writing screenshots to disk is slow. Do you have an antivirus active?

As a workaround, you can disable screenshots in the trace. You will still get everything else, so it should not be a big deal. Replace `trace: "on"` with `trace: { mode: 'on', screenshots: false }` in your config. Let me know if this helps.

**Comment by mwhebert** [comment]
@dgozman - Changing the setting cut down the time to 2.5 minutes.  I can't turn off the Anti-virus because of corporate rules.  Does playwright only use the local folder to write files?  Or does it also use a "temp" area?  I ask because it might be possible to exclude folders.

Thanks again for all the information.

**Comment by dgozman** [comment]
@mwhebert Playwright creates a temporary directory to write trace files. You can find out where by running the following command:

```sh
node -p "require('os').tmpdir()"
```

**Comment by dgozman** [comment]
We've updated the timeout message to make it clear what's happening, and continue to bring tracing improvements across the board. There is nothing specific in this issue that we can tackle, so I am closing it. If you still encounter specific problems, please file a new issue with a repro that we can run locally.

**Comment by Nisim761** [comment]
I am encountering this issue too.
mac os sonoma 14.3.1,  node 20.10.0, npm 10.2.3, playwright/test ^1.41.2.
A few of my tests started randomly fail with this error. I don't have any trace, simply this error message. The tests are using the same functions and resources as other tests, which work fine without any issues.
