### ISSUE TITLE
[Feature] Objects in custom annotations & html report

### ISSUE THREAD

**Issue by gbasto** [microsoft/playwright#21253]
**Issue**
Currently only strings are accepted as custom annotations' description. If an object is set as description the html report won't even render. Being able to pass other types than string to annotations would be helpful. Some examples:
* when a single test covers more than one issue, we could set an array of affected issues
* when E2E testing, we could save an object containing the current context

**Proposed solution**
On html reporter, before rendering the annotation description, check if the value is an object and if so stringify it. [Implementation example](https://github.com/microsoft/playwright/compare/main...gbasto:playwright:html-reporter-annotations).

Result:
![image](https://user-images.githubusercontent.com/1653045/221831595-4702e8b6-b73e-4264-9c54-8b618c84e73e.png)

**Comment by pavelfeldman** [comment]
Annotations are strings by nature, but you can use `test.info().attach()` to attach any textual or binary data to your test case.

**Comment by pavelfeldman** [comment]
Keeping it open for us to render multiple annotations with the same type as a list.

**Comment by gbasto** [comment]
@pavelfeldman let me know if you want me to pick up this issue, I'd be happy to help.
