### ISSUE TITLE
Incorrect line number shown in console for failed test scenario

### ISSUE THREAD

**Issue by priteshmd** [microsoft/playwright#21250]
The method name is correctly shown where issue occured but the line number displayed in logs and report is incorrect and points to some where else in the same file.
Using cucumber with playwright
PW version 1.29
Repo: https://github.com/Tallyb/cucumber-playwright
![image](https://user-images.githubusercontent.com/25026718/221814542-e2af4cb5-94f7-4db2-9f75-bbf79456e7e0.png)

**Comment by pavelfeldman** [comment]
This does not look like the result of the Playwright Test runner, did you use some other runner? Please provide the exact steps to follow.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
