### ISSUE TITLE
Question: Use case for test.step vs test.serial

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#21268]
Hi, I have long term scenario which is interdependent and I am currently using the following structure.
```js
test.describe.serial('create / modify / destroy', () => {
  test('setup', async () => {
     .......
  });
  test('modify', async () => {
     .......
  });
  test('destroy', async () => {
     .......
  });
});
```

I was wondering if I move the above test to the following structure, does it impact the interdependency in any way (retries enabled)? Also, I guess I am trying to understand when I would use `.serial` vs `.step`?

```js
test('create / modify / destroy', () => {
  await test.step('setup', async () => {
     .......
  });
  await test.step('modify', async () => {
     .......
  });
});
```

**Comment by pavelfeldman** [comment]
They are mostly interchangable. You have a trace-per-test, so that'll be different. In the report they'll look a bit differently (steps inside a single report for a test). Otherwise, in terms of retries, it'll be pretty much the same.

**Comment by Nav-2d** [comment]
Thanks for the answer. Closing the issue.
