### ISSUE TITLE
[BUG] TypeError: Cannot read properties of undefined (reading 'fullName')

### ISSUE THREAD

**Issue by akmaluddin** [microsoft/playwright#21269]
### System info
- Playwright Version: [v1.30.0]
- Operating System: [macOS 13.2, focal-1.31.0]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]
Its happening quite recently, I am getting this very cryptic error
TypeError: Cannot read properties of undefined (reading 'fullName')

It works well on my machine but does not run when in the docker container as outlined by the documentation for visual regression

I have exhaustively searched my codebase and cant identify where `fullName` is being used

**Actual**

[Describe actual behavior]

**Comment by pavelfeldman** [comment]
Please fill out the blanks in the issue template so that we could reproduce your issue.

**Comment by akmaluddin** [comment]
Closing this, for those who stumble on the same problem the issue lies the `testInfo.snapshotSuffix`

```jsx
test('should render dismiss button accordingly', async ({
    mount,
}, testinfo // And this ) => {
    testinfo.snapshotSuffix = ''; // Remove this
    const component = await mount(
        <div style={{ padding: '20px' }}>
            <Pill isDismissable handleDismiss={() => {}}>
                Some-text
            </Pill>
        </div>,
    );
    await expect(component).toHaveScreenshot();
});
```
