### ISSUE TITLE
[BUG] PlayWright Database connection issue 

### ISSUE THREAD

**Issue by gauravsharma28041982** [microsoft/playwright#21261]
I'm trying to check connectivity between playwright and database .. followed below step ,

Can anyone please help me to resolve this issue ? 

In DataConnection. js file ,

const sql = require('mssql');

const sqlConfig = {
  user: '',
  password: '',
  server: '', 
  database: '', // name of database
  options: {
    encrypt: true,
    trustServerCertificate: true,
  },
};

exports.DB = class DB {
  async connectDb(query) {
    try {
      await sql.connect(sqlConfig);
      await sql.query(query);
    } catch (err) {
      console.log(err);
    }
  }
};

And In test file :

import { test, expect } from '@playwright/test';
import { Int } from 'mssql';
const { DB }  = require('../tests/DataConnect') ;

const db = new DB() ;

test('test', async ({ page }) => {

     await db.connectDb ("select job_status_id  from dev_allocation.job_status_dim jsd  where job_status_id =2") ;
  
    
   await expect(page).toequal(2);

});

 Output 

    Expected: 0
    Received: {"_guid": "page@234b43c2423d0c3e480082b9b10481fc", "_type": "Page"}

**Comment by gauravsharma28041982** [comment]
@mxschmitt Can you please help me  ..https://github.com/mxschmitt

**Comment by pavelfeldman** [comment]
This looks unrelated to Playwright.

**Comment by mxschmitt** [comment]
Playwright is just Node.js so this is unlikely an issue with Playwright. We recommend trying it out in a normal Node.js script, to see if your database connection works, then it also works with Playwright.
