### ISSUE TITLE
[BUG] "Error: Element is not an <input>, <textarea> or [contenteditable] element" on div with contenteditable="true"

### ISSUE THREAD

**Issue by martin-mindflow** [microsoft/playwright#21265]
## System:
 - OS: macOS 13.2.1
 - Memory: 203.23 MB / 16.00 GB
## Binaries:
 - Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.19.0/bin/yarn
 - npm: 8.19.3 - ~/.nvm/versions/node/v16.19.0/bin/npm
## Languages:
 - Bash: 3.2.57 - /bin/bash

**Code Snippet**

```typescript
import { Page, Locator, expect } from "@playwright/test"

export class Page {
  private readonly canvas: Locator

  public constructor(page: Page) {
    this.page = page
    this.canvas = this.page.getByTestId("canvas")
  }

  public async goto(): Promise<void> {
    await this.page.goto(`/...`)
  }

  private async createStep(stepType: string): Promise<void> {
    // ...
    await this.canvas.getByText(stepType).fill("some text")
  }
}
```

Relevant dom:

```
<div class="css-5h0m38">
    <div placeholder="Add a title" class="css-uhav34-TextEditable" role="textbox" tabindex="0" contenteditable="true">
        some text.....
    </div>
</div>
```

The error:

```
locator.fill: Error: Element is not an <input>, <textarea> or [contenteditable] element
=========================== logs ===========================
waiting for getByTestId('canvas').getByText('.....')
  locator resolved to <div tabindex="0" role="textbox" contenteditable="tru…>....</div>
elementHandle.fill("some text")
  waiting for element to be visible, enabled and editable
  Element is not an <input>, <textarea> or [contenteditable] element
============================================================
  48 |
> 49 |     await this.canvas.getByText(stepType).fill("some text")
     |                                           ^
  50 |   }
  51 | }
  52 |
```

**Describe the bug**

The div I'm typing into clearly looks editable, at least in the browser inspector and even in the error report. Maybe I'm missing something tho ? It's worth noting that the div is made editable programatically during the test run

Thanks a lot :)

**Comment by pavelfeldman** [comment]
> It's worth noting that the div is made editable programatically during the test run

Could you share a self-contained repro that we can try locally? Could it be that there is a race condition between when it is edited and is made editable? Are you editing the root content editable element or a subelement?
