### ISSUE TITLE
[BUG]Trace snapshot don't show CSS and images. 

### ISSUE THREAD

**Issue by MaksimKravchuk** [microsoft/playwright#21263]
**Context:**
- Playwright Version: 1.31.0
- Operating System: debian:bullseye-slim
- Python version: 3.10
- Browser: Chromium
- Extra:
We run our tests in a python3.10-slim container in Github Actions.

**Code Snippet**
```python
@pytest.fixture(scope="function")
async def context(
    browser: Browser, base_url, cookies, request, log_path
) -> AsyncGenerator[BrowserContext, None]:
    context = await browser.new_context(
        locale="en-NL",
        timezone_id="Europe/Amsterdam",
        base_url=base_url,
        viewport=None,
    )
    await context.tracing.start(screenshots=True, snapshots=True, sources=True)
    yield context
    ...
    await context.tracing.stop(path=f"{log_path}/trace-{trace_name}.zip")
    await context.close()
```

**Describe the bug**
Here is an example of a broken trace archive. 
[trace.zip](https://github.com/microsoft/playwright-python/files/10849481/trace.zip)

I want to provide more info, but I don't understand what can be useful

**Comment by dgozman** [comment]
@MaksimKravchuk I can reproduce the issue when using `trace.playwright.dev`, but not when using `npx playwright show-trace`. As a workaround for now, open your trace with `npx playwright show-trace`.

---

The issues is that `trace.playwright.dev` is served over https, so when showing the `http://` snapshots, Chrome forces https for subresources, presumably to avoid mixed-content. Let us see whether we can do something.

**Comment by mmn0o7** [comment]
I have the same issue with version 1.44 :( 
[Uploading trace (2).zip…]()
