### ISSUE TITLE
[REGRESSION]: Firefox is not returning the url of object tags

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#21277]
**Context:**
- GOOD Playwright Version: 1.30
- BAD Playwright Version: 1.31.1
- Operating System: Any

**Code Snippet**

```javascript
import { test, expect } from '@playwright/test';

test('switch to object', async ({ page }) => {
  await page.goto(
    "file:///Users/dario/Code/local/playwright-playwround/index.html"
  );
  const locator = page.mainFrame().childFrames()[0];
  expect(locator.url()).toContain("object_one.html");
});
```
[Pages attached](https://github.com/microsoft/playwright/files/10854749/pages.zip)

**Describe the bug**

I was able to get the URL of an `object` element loading an HTML page on firefox using PW 1.30. That stopped working on 1.31.1. This works on Chromium on 1.31.1.

**Comment by pavelfeldman** [comment]
Please follow the issue template so that we could reproduce your use case!
