### ISSUE TITLE
[BUG] All tests getting skipped on using setup in dependencies for shared auth states.

### ISSUE THREAD

**Issue by gauravkrp** [microsoft/playwright#21270]
### System info
- Playwright Version: [1.31.1]
- Operating System: [macOS 13.2]
- Browser: [Google Chrome]

### Screenshots of config file and terminal
<img width="553" alt="Screenshot 2023-03-01 at 12 24 38 AM" src="https://user-images.githubusercontent.com/12250556/221951699-069a2c91-2623-4e6e-af2a-9586ed550262.png">

<img width="412" alt="Screenshot 2023-03-01 at 12 25 28 AM" src="https://user-images.githubusercontent.com/12250556/221951904-268e88af-d496-4c8b-a97e-59958bb298a2.png">

<img width="758" alt="Screenshot 2023-03-01 at 12 30 44 AM" src="https://user-images.githubusercontent.com/12250556/221953023-4d363b2e-770a-41c8-8080-783c2b8cec67.png">

**Expected**

Tests should run. I am using different roles, so authStates are being called and used in each file. (3rd screenshot)

**Actual**

Tests not running, all getting skipped. Tests run when I comment the dependencies option in config file under project setup.

**Comment by pavelfeldman** [comment]
Please follow the issue template and provide something we can run locally to be able to reproduce your issue!

**Comment by gauravkrp** [comment]
> Please follow the issue template and provide something we can run locally to be able to reproduce your issue!

Please check here - https://codesandbox.io/p/sandbox/blissful-hill-z45yst?file=%2Fe2e%2Findex.spec.ts
I've reproduced the new `setup` features in the latest version but it is not working!

**Comment by gauravkrp** [comment]
> Please follow the issue template and provide something we can run locally to be able to reproduce your issue!

Also, see this video I just created  - https://www.loom.com/share/b49fce3899d649138830000dc609bba5

(It's another fact the browsers are not installed for online IDEs but what matters is that tests are running when setup is commented and not running when setup is set in the dependencies array !!)

**Comment by ThePerryR** [comment]
I just had this exact issue. Basically, the setup file wasn't getting matches. The `testMatch` value is relative to your `test` directory. So I had to move my auth.setup.ts file to my test folder, and it worked.

**Comment by pavelfeldman** [comment]
@gauravkrp: the problem is you `import { adminFile } from "./auth.setup";` in the test file. They way import works in Node.js is that it runs all the code inside that file. So when we import your test file, it imports the setup file and declares all the setup tests again. It confuses playwright. We will work on a better error message for this. For now, declare your constants in a separate file or in the config, basically in the files that do not run code and have no side-effects.
