### ISSUE TITLE
[Feature] Using different roles for a test can be good

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#21273]
Using different roles in a test can be good.For example;

```
import { Selector } from 'testcafe';
test('test with two users', async t => {
    await t
        .useRole(regularUser)
        .click('#delete-button')
        .useRole(administrator)
        .click('#delete-button');
});
```

Searched for using different storageStates for only using one test but didn t found. Is there any alternative like above code in Playwright?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/next/auth#multiple-signed-in-roles
