### ISSUE TITLE
[BUG] Failing the test inside response event handler disposes connection

### ISSUE THREAD

**Issue by bostjanvizintin** [microsoft/playwright#21285]
### System info
- Playwright Version: v1.30.0
- Operating System: Windows 11
- Browser: All

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/bostjanvizintin/TestExample

**Code**

```c#
using Microsoft.Playwright.NUnit;

namespace TestExample;

public class Tests : PageTest
{
    [Test]
    [Order(1)]
    public async Task Test()
    {
        Page.Response += (o, response) =>
        {
            if(response.Status == 400)
                Assert.Fail();
        };

        await Page.GotoAsync(http://httpstat.us/200);
    }

    [Test]
    [Order(2)]
    public async Task Test1()
    {
        Page.Response += (o, response) =>
        {
            if (response.Status == 400)
                Assert.Fail();
        };

        var res = await Page.GotoAsync(http://httpstat.us/400);
    }


    [Test]
    [Order(3)]
    public async Task Test2()
    {
        await Page.GotoAsync(http://httpstat.us/500);

        Assert.That(true, Is.EqualTo(true));
    }
}
```

**Steps**
- Run the tests

**Goal**

I am testing an application and i would like to add an even handler on page or context that would fail any test in which there is a response that meets certain criteria (example Status 500).

**Expected**

I am expecting first and third test (Test and Test2) to be successful and second test (Test1) to fail.

**Actual**

Failing the test (Test1) inside event handler causes connection to be disposed, causing the third test (Test2) to throw an exception Microsoft.Playwright.PlaywrightException : Connection disposed.

**Comment by pavelfeldman** [comment]
```cs
        Page.Response += (o, response) =>
        {
            if (response.Status == 400)
                Assert.Fail();
        };

        var res = await Page.GotoAsync(http://httpstat.us/400);
```

In this snippet, you are throwing from the async event handler. This event is dispatched in the async code, and as a result, entire system crashes. Follow the best practices to avoid that: https://stackoverflow.com/questions/12314410/catch-unhandled-exceptions-from-async. In this case, you should add the response into an array and after the Page.GotoAsync() call you should check the response status and assert in the main test flow.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
