### ISSUE TITLE
[BUG] Playwright controlled browser not always loading the debugger

### ISSUE THREAD

**Issue by mrenrich84** [microsoft/playwright#21288]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Mac Ventura 13.0 M1
- Node.js version: 16.15.0
- Visual Studio Code version: 16.15.0
- Playwright for VSCode extension version: 1.0.7
- Browser: tried with Chromium and Firefox
- Extra: NextJS 13

**Code Snippet**
Sorry a bit hard to reproduce, please consider this screenshot:
<img width="1576" alt="image" src="https://user-images.githubusercontent.com/14198729/222008583-494a6e55-b8fb-4498-beb7-918fde89faff.png">

**Describe the bug**
If the Playwright test is run by the VS Code extension with the Show Browser ticked on and no Playwright-controlled browser open,  the browser will never launch the debugger - although the console messages are visible in the browser consoles.
If the Playwright test is run with the Playwright-controlled browser already open, the browser will sometimes load the debugger - although the pattern seems totally random to me.

I cannot find any Playwright output in VSC, so I can't provide logs or anymore context unfortunately.

**Comment by pavelfeldman** [comment]
Could you explain what "the browser will never launch the debugger" means? You mean DevTools window won't be opened? We don't open it, only you do. Please provide the source code and exact steps to follow so that we could reproduce it. Steps can lead us through the actions we need to perform in VS Code.

**Comment by mrenrich84** [comment]
It is a fair question, sorry for that.

```
AS A dev,
I WANT TO hang the execution and debug inside the browser,
SO THAT I can toy around with my code and the data it is managing
```

Have a look at the screenshot, left pane, line 13, the `debugger;` statement inside the Signin component.

```
GIVEN the `Show browser` is ticked on in the Playwright VSC extension 
WHEN I ran the Playwright test from VSC
AND the browser renders the app,
THEN the browser will not hang while rendering the Signin component 
```

I can confirm that the component is rendering client side by looking at the log statement in line 12 left pane.
This is not the expected behaviour - I would expected the browser to hang on the debugger statement at line 13 left pane.

```
GIVEN I keep the Playwright browser open
WHEN I re ran the test
THEN the browser will hang on the debugger statement at line 13 left pane.
``` 

This is the expected behaviour.

I will try to come up with an example repo in the next few days if this is not sufficient.

**Comment by pavelfeldman** [comment]
What do you mean by "browser will hang" and "browser will not hang"? Playwright does not stop browser, so it won't be hanging.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
