### ISSUE TITLE
[REGRESSION]: Device Emulation does not work correctly

### ISSUE THREAD

**Issue by wernerwernerwerner888** [microsoft/playwright#2129]
Hello, 

first of all, i want to say that this is a very promising project. I have a problem with the mobile device emulation. I required the const devices and added the iphone, my code is very basic, as im testing, if playwright is useful for my needs or not. The problem is, that my useragent shows correctly the Useragent for the iphone, but if i make a canvas test, it shows me still that im on windows and the same canvas fingerprint as on my normal browser. 

Is that normal or a bug?

Here my code:

```js
const { chromium, devices } = require("playwright");
const iPhone11 = devices["iPhone 11 Pro"];

async function start() {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext({
    ...iPhone11,
    geolocation: { longitude: 52.520008, latitude: 13.404954 },
    permissions: ["geolocation"],
  });
  const page = await browser.newPage();
  await page.goto("https://browserleaks.com/canvas");
}

start();
```

**Comment by mxschmitt** [comment]
It might be, that you are you using the browser to create a new page and not the context. So 
```
const page = await context.newPage();
```
should work.
