### ISSUE TITLE
[Question]: Share code among 2 different test cases involving intercepting network request.

### ISSUE THREAD

**Issue by divyanshu-rawat** [microsoft/playwright#21299]
**Context:**

Playwright Version: "@playwright/experimental-ct-react": "^1.31.0",
Operating System: [ Mac]
Node.js version: v16.18.0
Browser: [e.g. All, Chromium]

I am intercepting network request while doing my playwright component testing, I have to write more test cases involving intercepting network request in that case test is taking more time to execute and sometimes get time out, as repeating the same code of network interception in all test cases.

Let me explain by providing a code example.

```js
test('A', async ({ page }) => {
  const btnOne = '[data-auto-id="btnOne"]';
  const btnOneLocater = page.locator(btnOne);
  let param: string | null = '';
  await page.route('**', (route) => {
    const requestURL = route.request().url();
    if (requestURL.includes('c25')) {
      param = new URLSearchParams(requestURL).get('c25');
    }
    route.continue();
  });
  await page.waitForLoadState('networkidle');
  await btnOneLocater.click();
  expect(param).toEqual('SHARE VENT');
});

test('B', async ({ page }) => {
  const btnTwo = '[data-auto-id="btnTwo"]';
  const btnTwoLocator = page.locator(btnTwo);

  let param: string | null = '';
  await page.route('**', (route) => {
    const requestURL = route.request().url();
    if (requestURL.includes('c25')) {
      param = new URLSearchParams(requestURL).get('c25');
    }
    route.continue();
  });
  await page.waitForLoadState('networkidle');
  await btnTwo.click();
  expect(param).toEqual('SIZE CHANGE');
});
```

here if you can see, both the test cases are firing network request in button click and then intercepting it, storing the request url and extracting a query param out of it and comparing it with a value. Below part of code is common in both test-cases and getting executed in every test-case.

```js
  let param: string | null = '';
  await page.route('**', (route) => {
    const requestURL = route.request().url();
    if (requestURL.includes('c25')) {
      param = new URLSearchParams(requestURL).get('c25');
    }
    route.continue();
  });
  await page.waitForLoadState('networkidle');
```

Is it possible to share this code in both the test cases without writing it for every test case, maybe something like putting it in 
`test.beforeAll(async ({ page, mount }) => {});` but I am not sure how to achieve the same in that case I also have to make sure the param variable here is shared among both the test cases.

**Comment by pavelfeldman** [comment]
If you have code that you'd like to execute before each test, you can put it into `test.beforeEach`, because you are running it before each test. You can also introduce a fixture (read our [docs](https://playwright.dev/docs/next/test-fixtures#creating-a-fixture)) that you can share among files. In terms of performance and timeouts, your code takes 0 time, so it can't be responsible for any performance penalty.

**Comment by divyanshu-rawat** [comment]
I am able to resolve the the issue marking it as closed.
