### ISSUE TITLE
how to pass parameter from npx command to playright.config.js file

### ISSUE THREAD

**Issue by sameera-gayendri** [microsoft/playwright#21294]
i have this axios report in playwright.config.js file 
reporter: [['junit', { outputFile: 'results.xml' }],['./aio-reporter.js']],

now I want to pass a parameter to the report when I'm running the test from the command line 
ex:
reporter: [['junit', { outputFile: 'results.xml' }],['./aio-reporter.js'], let testcycle],

npx playwright test --testcycle=TC-TY-2

**Comment by pavelfeldman** [comment]
Using environment variable will be the only way:

```sh
# win
set TESTCYCLE=TC-TY-2
npx playwright test
# Linux / macOS
TESTCYCLE=TC-TY-2 npx playwright test
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
