### ISSUE TITLE
page.mouse.down() shows failure on report but appears to function

### ISSUE THREAD

**Issue by MitchMcCoy502** [microsoft/playwright#21306]
See image below - the test is taking a screenshot of a button in the clicked state. adding `await` to the` page.mouse.down()` results in test timeout and failure. In the configuration below, the test shows pass in the console. 

![image](https://user-images.githubusercontent.com/88807661/222193042-4c8222b6-3e09-4835-a7d4-9c7caea887e7.png)

**Comment by pavelfeldman** [comment]
Please follow an issue template so that we could reproduce the issue. It is likely that there is a bug in the user code.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
