### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LeeeJoe** [microsoft/playwright#21304]
**Context:**
- Playwright Version: [1.30.0, 1.31.1]
- Windows, Linux
- .NET version: [NET 7.0]
- Browser: [Firefox 109]

**Code Snippet**
Simply try www.twitter.com start page

**Describe the bug**
Starting with version 1.30.0, when viewportsize is larger than the physical dimensions of a computer display, visual elements are active, available, stable, but it is not possible to perform clicks. In version 1.29.0 everything worked.
Please try.
Thank you.

**Comment by pavelfeldman** [comment]
Please provide exact steps along with the code that we can follow in order to reproduce your issue.

**Comment by LeeeJoe** [comment]
Hi.
For example.

In my Linux system display resolution is 1280x666.
Page ViewPortSize is 1920x1080.
Url: https://twitter.com

var locator = ***@***.***='Sign in with Google ***@***.***='close']");
or
var locator = ***@***.***='login']").Locator("visible=true");

Thank you.
Best regards.
LeeeJoe

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by LeeeJoe** [comment]
`var playwright = await Playwright.CreateAsync();
 IBrowserType browsertype = playwright.Firefox;
 var browser = await browsertype.LaunchAsync();
 var contextOptions = new BrowserNewContextOptions
 {
        ViewportSize = new() { Width = 1920, Height = 1080 },
 };
var context = await browser.NewContextAsync(contextOptions);
var page = await context.NewPageAsync();
await page.GotoAsync("https://twitter.com/", new() { WaitUntil = WaitUntilState.Load });
var locator = page.FrameLocator("//iframe[@title='Sign in with Google Dialog']").Locator("//div[@id='close']");
await locator.ClickAsync();
`

**Comment by pavelfeldman** [comment]
Please follow the issue template when filing so that we could reproduce the issue, understand actual and expected results.
