### ISSUE TITLE
[Question] unable to run from RouteFromHAR response to an rest API requests with the dynamic values.

### ISSUE THREAD

**Issue by isherkhan** [microsoft/playwright#21319]
Playwright Version: 1.31.0
Operating System: Windows
Node.js version: 16.14.0
Browser: Chromium
playwright Node.js version

Hello team. I'm trying to use playwright to test UI from HAR file recorded. The problem is my website call an API with dynamic value that is generated through the code for example tokens in a page. But in HAR file recorded by route From HAR didn't have the newly generated key in it. So the responses does not match with the recorded version and result in the test failure. IS there a way to use regex so that it returns the cached the data.

**Comment by pavelfeldman** [comment]
There is no such feature, routeFromHAR currently performs strict matching. We were thinking about using a har extension that would allow regex-based matching, but wanted to wait for a greater adoption of the method first.

**Comment by isherkhan** [comment]
> There is no such feature, routeFromHAR currently performs strict matching. We were thinking about using a har extension that would allow regex-based matching, but wanted to wait for a greater adoption of the method first.

Thanks For the Reply. Is there any time line  by when this will be implemented.( we really find this method adding value to our test suites.)With regex based matching it will even more optimizes the test suites.

**Comment by pavelfeldman** [comment]
There is no timeline and it is unlikely going to happen soon. Unless you contribute it yourself in a PR!

**Comment by jamiemac87** [comment]
We would also appreciate a regex based matching. We are just starting our journey with playwright and had really high hopes for capturing network activity via HAR but it seems to be a bit too restrictive. We had a situation where a change was made on the frontend that added a new query param to an api request. The api request is performed in a lot of the tests so the majority of the tests needed to have the HAR re-recorded even though the added query param would not have resulted in those tests failing. We are now considering reverting to using json mocks via the `route`.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
