### ISSUE TITLE
[Question] Socks5 Support

### ISSUE THREAD

**Issue by wernerwernerwerner888** [microsoft/playwright#2131]
Hello, 

i would like to add some socks 5 for new page or newcontext and tried to do it the same way as i did in puppeteer, buts not working. 

I tried to do this on both (Launch and Context, but nothing worked). Any idea how i can add an socks5?

Here is my code:

async function start() {
  const browser = await firefox.launch({
    headless: false,
  });
  const context = await browser.newContext({
    args: ["--proxy-server=socks5://127.0.0.1:9955"],

**Comment by pavelfeldman** [comment]
Move the `args: ["--proxy-server=socks5://127.0.0.1:9955"]` int o the launch parameters next to headless: false!

**Comment by wernerwernerwerner888** [comment]
> Move the `args: ["--proxy-server=socks5://127.0.0.1:9955"]` into the launch parameters next to headless: false!

Thanks for your reply...thats what i tried before, also not working...on puppeteer it works. 

Here my code in the launch.

async function start() {
  const browser = await webkit.launch({
    headless: false,
    args: ["--proxy-server=socks5://127.0.0.1:9955"],
  });

**Comment by aslushnikov** [comment]
The first-class proxy support should address this! It's coming in the https://github.com/microsoft/playwright/issues/1914

**Comment by wernerwernerwerner888** [comment]
> The first-class proxy support should address this! It's coming in the #1914

thanks, thats good to hear. Is there an estimated time when the first class proxy support with be available?

**Comment by ordimans** [comment]
Can we use this with playwright ?

https://github.com/Cuadrix/puppeteer-page-proxy

**Comment by shirshak55** [comment]
@ordimans yes you can use it but it uses interceptor meaning you cannot block request anymore etc..

**Comment by pavelfeldman** [comment]
New API for using proxy, including SOKCS5 has added in 1.1: [doc](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy)
