### ISSUE TITLE
Unable to run playwright example tests in the Azure pipeline with the provided ubuntu yml and image  

### ISSUE THREAD

**Issue by generalzachbar** [microsoft/playwright#21313]
Hello,

I have been trying to run the playwright azure pipelines integration and am experiencing errors.  I have copied the sample code from here using the ubuntu image, and have setup an azure pipeline:
https://playwright.dev/docs/ci#azure-pipelines

When I try to run the example tests the are provided with the playwright install, I am receiving errors.  The same tests, when run locally, run without error.  I am thinking it is due to a configuration in the ubuntu image.  Not too sure how to proceed.  I re-ran with the debug enabled ( DEBUG=pw:browser*), and I am seeing this as part of the output that is different than local:

Running 26 tests using 1 worker
  pw:browser <launching> /home/vsts/.cache/ms-playwright/firefox-1378/firefox/firefox -no-remote -headless -profile /tmp/playwright_firefoxdev_profile-5pnzmp -juggler-pipe -silent +0ms
  pw:browser <launched> pid=4339 +4ms
  pw:browser [pid=4339][err] *** You are running in headless mode. +37ms
  pw:browser [pid=4339][out] Crash Annotation GraphicsCriticalError: |[0][GFX1-]: glxtest: Unable to open a connection to the X server (t=0.355023) [GFX1-]: glxtest: Unable to open a connection to the X server +319ms
  pw:browser [pid=4339][out]  +73ms

  ...

All the test fail after this.   

Im wondering if there needs to be further configuration of the container image in order for the tests to run in Azure.  Do you have any success in running the example tests in Azure?  Can you verify the yml example runs found at this url?
https://playwright.dev/docs/ci#azure-pipelines

This is the code I am running as found on the above link (I slightly adjusted as the indentation on the "env" was failing the azure yml validations  :

Thanks for your help!

```
trigger: none
jobs:
    - deployment: Run_E2E_Tests
      pool:
        vmImage: ubuntu-20.04
      container: mcr.microsoft.com/playwright:v1.31.0-focal
      environment: testing
      strategy:
        runOnce:
          deploy:
            steps:
            - checkout: self
            - task: Bash@3
              displayName: 'Run Playwright tests'
              inputs:                
                targetType: 'inline'
                failOnStderr: true
                script: |
                  npm ci
                  DEBUG=pw:browser* npx playwright test example
              env:
                CI: true

**Comment by generalzachbar** [comment]
here is the example tests i am trying to run btw:

```import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
    await page.goto('https://playwright.dev/');

    // Expect a title "to contain" a substring.
    await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
    await page.goto('https://playwright.dev/');

    // Click the get started link.
    await page.getByRole('link', { name: 'Get started' }).click();

    // Expects the URL to contain intro.
    await expect(page).toHaveURL(/.*intro/);
});

**Comment by pavelfeldman** [comment]
> All the test fail after this.

Could you elaborate on how they fail? Reports browser closed?

The crash messages are concerning. We've heard from the users that Azure can set bogus values to the DISPLAY property, could you try removing it from the environment (setting to empty value under env:)?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
