### ISSUE TITLE
[BUG] Element is outside of the viewport despite visible, enabled and stabled

### ISSUE THREAD

**Issue by kashifali00** [microsoft/playwright#21310]
The button I'm trying to click is appeared on modal 

### System info
- Playwright Version: [v1.1.30.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

 retrying click action, attempt #49
      waiting 500ms
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      element is outside of the viewport

await pageObjectManager.getEditContactInformationPage().getSaveChangesButton().click({timeout:6000})
Save changes button locator:
this.saveChangesButton = this.page.getByText("Save Changes")

test trace is attached

[trace.zip](https://github.com/microsoft/playwright/files/10864015/trace.zip)

**Config file**

**Expected**

Since is button is visible, enabled and stable so playwright should be successfully able to click it

**Actual**
Playwright is not able to click the button despite visible, enabled and stable instead throws an error "element is outside of the viewport"

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
