### ISSUE TITLE
[BUG] Running all tests together not working

### ISSUE THREAD

**Issue by ahmedmukhtar1133** [microsoft/playwright#21314]
Facing an issue when running all tests together using `playwright test`. If I execute tests file one by one then everything works fine. I believe issue is with app closing, sometimes app doesn't get closed on test case completion (before executing the next) that's why other tests get fails randomly.

### System info
- Playwright Version: [v1.18.1]
- Operating System: macOS 13.2
- Browser: Electron
- Other info: Node 14

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const path = require('path')
require('dotenv').config({ path: path.resolve(process.cwd(), 'app', 'test', '.env.test') })

const config = {
  testDir: '../e2e',
  globalTimeout: 600000, // Maximum time the whole test suite can run,
  timeout: 200000, // Timeout for each test
  retries: 1,
  workers: 1,
  expect: {
    toMatchSnapshot: { threshold: 0.2 }
  },
  use: {
    screenshot: 'only-on-failure',
    trace: 'on'
  }
}

module.exports = config

```
**Close electron app**
```
  await electronApp.evaluate(async ({ Menu, BrowserWindow }) => {
    const mainWindow = BrowserWindow.getAllWindows().filter(w => w.getTitle() === 'Repeato')
    await mainWindow?.webContents.send('app-close')
  })
```

**Steps**
- playwright test

**Expected**

- All tests should working fine

**Actual**

- Some tests get failed because in some cases electron app doesn't get closed properly.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
