### ISSUE TITLE
[Question] carlo alternative based on playwright-core

### ISSUE THREAD

**Issue by andriyor** [microsoft/playwright#2132]
What do you think about creating [carlo](https://github.com/GoogleChromeLabs/carlo) alternative based on playwright-core

**Comment by pavelfeldman** [comment]
Carlo is outside of the scope of the Playwright project, but it'd be nice to see people experimenting with it. Also, which engine would you pick for it? Carlo would not need to be cross-browser, so would default to Chromium.
