### ISSUE TITLE
Locator:click Error is thrown incorrectly

### ISSUE THREAD

**Issue by davthorne** [microsoft/playwright#21330]
### System info
- Playwright Version: 1.31.1
- Operating System:  Windows 11,
- Browser: Chromium

I have two buttons in my page both of which are coreUI [components](https://coreui.io/) with the text "Save".  One is in a modal ( with class = 'modal' ) , which displayed when a user takes an action and the other in the page itself.

Using the following
    await page.waitForSelector(".modal");
    await page.getByRole("dialog").getByText(t"Save").click();

I would expect the "Save" button within the modal to be clicked as I specify     '.getByRole("dialog")'

However I see this error

`   locator.click: Error: strict mode violation: locator('button:text("Save")') resolved to 2 elements:
           1) <button type="submit" data-test="save" data-v-5d30a5db="…> Save </button> aka locator('[data-test="save"]')
           2) <button type="button" data-v-055d7028="" class="btn btn-…>Save</button> aka getByRole('dialog').getByRole('button', { name: 'Save' })`

Note:
I am using coreUI so I cannot add a attributes to the component.

Thanks for any comments

**Comment by pavelfeldman** [comment]
The information you provide does not seem to be consistent. You say:

```js
await page.getByRole("dialog").getByText(t"Save").click();
```

but it has a syntax error. And then the error refers to

```js
locator('button:text("Save")')
```

Please follow the new issue template to provide us with something we can reproduce, otherwise, it looks like things work as expected.

**Comment by davthorne** [comment]
Yes I apologise for my poor question.  I mean't await page.getByRole("dialog").getByText(t"Save").click();
However I have resolved my issue. Thanks for your time
