### ISSUE TITLE
[Question] (feature?) Extension with UI for non-developers to use Playwright. Continue our work?

### ISSUE THREAD

**Issue by ufst-ask** [microsoft/playwright#21331]
We developed an (MVP) extension to Playwright which makes i much easier for non-developers to generate tests.
It's "powerpoint UI meets playwright".
Now I would like to know if anyone is up for picking up on this if we put out there as an open source project?
![image](https://user-images.githubusercontent.com/77072723/222427662-12fc97fc-171f-4463-9e12-82a6bab8f6ce.png)

I work as a software engineer at The IT and Development Agency of the Danish Ministry of Taxation.
It would be very valuable to us if our non-developer employees could automate 80%-100% of a test flow. Then let the developers finish it of if needed.
Our idea were to use the codegen (or similar) along with a powerpoint-style UI to let users generate tests.
They add a test step, one by one, and then they can view them in the list and in the detailed view on the right.

Unfortunately it's no longer prioritized to continue working on this project. So my hope is that some of you people see the value in it and want to continue working on it. And maybe, just maybe, it would help me get it prioritized again :)

All reactions are welcome, tips, feedback, questions etc.

**Comment by pavelfeldman** [comment]
This seems to fall outside of the scope for Playwright. Happy hacking!
