### ISSUE TITLE
[Question] [BUG?] same command for Installing chrome and edge browser in Playwright documentation 

### ISSUE THREAD

**Issue by Mshumaman** [microsoft/playwright#21334]
Hi to all,
I think the section should specify both commands to install chrome or msedge? Now it's just the same command
![image](https://user-images.githubusercontent.com/69470134/222443577-8dc3a14f-6faf-4ad8-bdd1-cff81ad48e70.png)

https://playwright.dev/docs/browsers#installing-google-chrome--microsoft-edge

**Comment by mxschmitt** [comment]
This is fixed in the beta version of the docs: https://playwright.dev/docs/next/browsers#installing-google-chrome--microsoft-edge
