### ISSUE TITLE
[Feature] page.setDeviceScaleFactor

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#2134]
I would like to set the DPI of a page, in order to simulate zooming in / changing monitors. It also want to be able to set the DPI to the system default so that things aren't blurry for headful scenarios.

Should setting the device scale factor keep the number of device pixels fixed, and zoom in on the page? Or should it keep the number of CSS pixels fixed, and scale the page?

**Comment by pavelfeldman** [comment]
I don't think we want to support dynamic changes to DPI, but we probably should support Zoom In/Out. Let's repurpose this to zoom?

**Comment by aslushnikov** [comment]
Is zoom web-observable?

**Comment by JoelEinbinder** [comment]
Page Zoom is somewhat web-observable. Browsers fire a resize event, because the window width changes. They change window.devicePixelRatio at the same time. 

Pinch zoom is another thing, and has somewhat recently (Safari 13) become observable through the [VisualViewport](https://developer.mozilla.org/en-US/docs/Web/API/VisualViewport) api.

**Comment by pavelfeldman** [comment]
Closing as per no signals from the users.
