### ISSUE TITLE
[REGRESSION]: Firefox fails when navigating from a local file to about:blank

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#21348]
**Context:**
- GOOD Playwright Version: 1.30
- BAD Playwright Version: 1.31
- Operating System: Mac
- Extra: Firefox browser

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. 

```javascript
import { test } from '@playwright/test';
import * as https from "https";
import * as fs from "fs";
import path from "path";

function downloadFile(url: string, fileName: string): Promise<void> {
  return new Promise((resolve, reject) => {
    const fileStream = fs.createWriteStream(path.join(__dirname, fileName));

    https
      .get(url, (response) => {
        response.pipe(fileStream);

        fileStream.on("finish", () => {
          fileStream.close();
          resolve();
        });
      })
      .on("error", (error) => {
        reject(error);
      });
  });
}

test('fail', async ({ page }) => {
  await downloadFile(
    "https://storage.googleapis.com/public-dev-test-lab/downloads/downloads.html",
    "downloads.html"
  );

  // Create an URL object with the file:// protocol
  const fileUrl = new URL(`file://${__dirname}/downloads.html`);
  await page.goto(fileUrl.toString());
  await page.goto("about:blank");
});
```

**Describe the bug**

I think the problem is when we navigate from a `file://` url to `about:blank`. I tried to reproduce it with a hosted page. But it worked.

This is the error:
```
page.goto: Navigation interrupted by another one
=========================== logs ===========================
navigating to "about:blank", waiting until "load"
============================================================
```
The `downloadFile` boilerplate is just to make this test self-contained. But it was failing with any local HTML page.
This test is passing in `chromium` and `webkit`.

**Comment by kblok** [comment]
@aslushnikov You know that I'm a few versions behind in Playwright because of this issue. Do you know what would be the risk of upgrading without this fix? What is the issue behind this bug?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
