### ISSUE TITLE
"Couldn't Load XPCOM" Popup Revealed to Developer | Firefox Regression

### ISSUE THREAD

**Issue by hawenger** [microsoft/playwright#21362]
#### Filed per request of #mxschmitt  from discord conversation 👇 
["Couldn't Load XPCOM" - Firefox](https://discord.com/channels/807756831384403968/1078772720810082415)

### System info
- Playwright Version: [v1.27.0] & [v1.30.0]
- Operating System: Window 10 Pro | Version 21H2 | OS 19044.2673 
- Browser: Firefox
-Dev Dependencies:_ "@playwright/test", "playwright", dotenv": "^16.0.0","npx": "^10.2.2",     "typescript": "4.3.5", "webpack-bundle-analyzer": "4.4.2"
- Rate of Occurrence: 100% Consistent until updates to playwright browsers right situation (npx playwright install)

### Source code
Provided is an example global-setup, .env.config.ts and scripts in the package.json - identical to the organization code where the bug was first encountered _(excluding variables & certain imports)_
The mock global-setup, .env/config.ts and package.json exist only in the main branch of the sample repository and are not configured for run.
The develop branch needs to be updated with global-setup .env.config and scripts in package.json.
Both branches need for the global set-up to be configured for run.

[Firefox Regression Repo](https://github.com/hawenger/firefoxregression)

CASE |  "**Steps**"
1.  A developer installs Playwright on a branch | v1.27.0
npm i @playwright/test@1.27 & npx playwright install

2.  Developer creates a new branch (weeks later)

3.  Developer uninstalls Playwright on the new branch 
npm uninstall @playwright/test 

4. Developer installs Playwright on new branch | v1.30.0
npm i @playwright/test@1.30 & npx playwright install

5. All tests pass on new branch running v1.30.0

6. Developer switches back to branch running v1.27.0 and runs tests

**Expected**
When a user has an incompatible browser version, tests will fail on run.

**Actual**
When a user has an incompatible browser version and is using a global-setup flow, the popup "Couldn't Load XPCOM" appears" when tests are run in firefox

**Important Notes**
*Main and Develop Branches run when "npm run tests:all" is called*

*Develop Branch runs [v1.30.0]*
*Main Branch runs [v1.27.0]*

Thank you!

<img width="564" alt="firefox" src="https://user-images.githubusercontent.com/63066634/222775575-406751e6-3021-4b86-a5f7-d7e617e2cec5.PNG">

**Comment by aslushnikov** [comment]
> 5. All tests pass on new branch running v1.30.0
> 6. Developer switches back to branch running v1.27.0 and runs tests

@hawenger in step 6, does the developer run `npm ci` to install up-to-date `node_modules/` before running tests with Playwright 1.27?
