### ISSUE TITLE
[BUG]Cannot open trace files

### ISSUE THREAD

**Issue by lxy2222** [microsoft/playwright#21365]
### System info
- Playwright Version: v 1.30
- Operating System: Windows
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

Hi all， when we try to add a trace file to check the details of cases, 
we found sometimes the trace file can not record the tests, it happens in opening 2 chromiums in the one case
the trace file is in the attachment, we tried remotely opening it or locally, but both didn't work
and when opening it, it looks like the below, but when debugging cases, all things worked. Could you please help check if is there something potential reasons?
![image](https://user-images.githubusercontent.com/12553152/222642075-11f6b160-fe56-4d97-90b9-65d4e1db081c.png)

[trace-1.zip](https://github.com/microsoft/playwright/files/10878563/trace-1.zip)

**Comment by pavelfeldman** [comment]
We need exact steps we can follow to reproduce the issue, otherwise it is not actionable on our side.

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.

**Comment by lxy2222** [comment]
I am so curious are you even taking a look at the questions?
And it's weekend in our timezone so I didn't respond quickly,
OK fine, it's your right to close this ticket @pavellfelldman, I am very disappointed at your behaviour, fine, thanks
