### ISSUE TITLE
[BUG] Only 1 browser context is available when connected over CDP

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#21360]
### System info
- Playwright Version: v1.31.2
- Operating System: macos 13.2.1
- Browser: Chrome
- Other info:

### Source code

**Test file (self-contained)**

```js
const { chromium } = require("playwright-core");

(async () => {
  const browser = await chromium.connectOverCDP(`http://localhost:12345`);
  const contexts = browser.contexts();
  // BUG: I expect more than 1 if I have more than 1 chrome profiles open
  console.log(`contexts`, contexts.length);
})();
```

- [X] I provided exact source code that allows reproducing the issue locally.

**Steps**
- Ensure that your chrome is launched with CDP port enabled at 12345
- There are more than 1 chrome profiles open
- Run the code above

**Expected**

- Log should print the number of open chrome profiles

**Actual**

- Log always prints 1

**Comment by pavelfeldman** [comment]
This is working as expected.
