### ISSUE TITLE
Can I use alias or a nick name for a test block so I can use it in test.afterAll() for cleanup ?

### ISSUE THREAD

**Issue by Pri-yam** [microsoft/playwright#21366]
I am running a test.describe block over a test data and then there are 3 test blocks inside the describe block which are basically for these three purpose-
1. Post API to create some data on QA env using test data
2. Get API call
3. Delete API to clean whatever was implemented in point 1

One of our senior Architects have asked us to create an AfterAll block so we can cleanup anything what has been created using POST API in case someone in team deliberately skips Delete API call (point 3).
I am not able to find anything which can be useful. Would appreciate suggestions.

**Comment by pavelfeldman** [comment]
I'm not sure I understand the question, what do you mean by 'alias or a nick name for a test block'?

**Comment by Pri-yam** [comment]
Can I name a test case? like test-1 or test-2 so I can just execute the test by simply calling it with a name.

**Comment by pavelfeldman** [comment]
No, there is no such feature. But you can create function and call it from the test and also from some other location. Tests are a JavaScript program.
