### ISSUE TITLE
[BUG] Test failures log is not displayed in terminal when custom reports are used

### ISSUE THREAD

**Issue by Keertiraj-Malik** [microsoft/playwright#21373]
### System info
- Playwright Version: v1.30.0
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
reporter: [
    [
      "allure-playwright",
      {
        detail: true,
        outputFolder: "my-allure-results",
        suiteTitle: false,
      },
    ],
  ],
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test, expect } from "@playwright/test";

export const TODO_ITEMS = ["buy some cheese", "feed the cat", "book a doctors appointment"];

test("basic test", async ({ page }, testInfo) => {
  await test.step("Visit todolist page", async () => {
    await page.goto("https://demo.playwright.dev/");
  });

  await test.step("Create 1st todo.", async () => {
    await page.locator(".new-todo").fill(TODO_ITEMS[0]);
    await page.locator(".new-todo").press("Enter");
  });

  await expect(
    page.locator(".view label"),
    "Make sure the list only has one todo item.",
  ).toHaveText([TODO_ITEMS[0]]);
});
```

**Steps**
- Run the test using the command `
- Fail the test by providing some random failing value
- Check the logs in the terminal

**Expected**
Logs displayed related to the failure caused by the invalid input provided

**Actual**
No logs displayed related to the failure only this is shown:
```

> playwright-ts@1.0.0 test
> npx playwright test

```

**Comment by MindaugasMateika** [comment]
Given that you're only using an allure reported then it seems expected. Try adding list and/or line reporters, https://playwright.dev/docs/test-reporters#built-in-reporters

**Comment by pavelfeldman** [comment]
Yep, you chose a reporter that does not produce any output, so now you see no output. Closing as per above, please feel free to open a new issue if this does not cover your use case.
