### ISSUE TITLE
[REGRESSION]: page.waitForSelector fails on certain form elements

### ISSUE THREAD

**Issue by alexduhanov** [microsoft/playwright#2137]
**Context:**
- GOOD Playwright Version: 0.16
- BAD Playwright Version: 0.17+
- Operating System: MacOS 10.15.4

**Code Snippet**

Page
```html
<body>
    <p>Hello World</p>
    <form action="http://www.example.com" target="someTarget" method="GET">
        <input name="Something" type="hidden" value="test">
    </form>
</body>
```

Test
```javascript
await page.goto('localhost:3000/test.html');

await page.waitForSelector('"Hello World"');

const form = await page.$('form');

expect(form).not.toBe(null);

await page.waitForSelector('form');
```

**Describe the bug**

As of 0.17 onwards, waitForSelector('form') is failing for me for the type of form I have on my page. The $ selector is able to find the element.

This seems to affect all three browser engines.

Repro: https://github.com/alexduhanov/playwright-test/tree/form-selector

**Comment by pavelfeldman** [comment]
We broke the `waitForSelector` defaults to expect visibility. Since your form is not visible, you should do `waitForSelector('form', { state: 'attached' })`

**Comment by alexduhanov** [comment]
Thank you - sorry for the spam, I missed that detail in the release notes.

**Comment by pavelfeldman** [comment]
No worries - it was very subtle, thank you for your report, @alexduhanov !
