### ISSUE TITLE
Kendo Angular- Strict mode violation 

### ISSUE THREAD

**Issue by Aowek955** [microsoft/playwright#21370]
Hi everyone, 
Upcoming automation engineer here :D slowly grinding it.

I am automating a web app it uses Kendo UI. I copied the locators via Codegen. 

locator.fill: Error: strict mode violation: locator('kendo-formfield').filter({ hasText: 'Password *' }).getByRole('textbox') resolved to 2 elements:
        
1) <input title="" tabindex="0" type="password" class="k-i…/> aka locator('kendo-formfield').filter({ hasText: 'Password *' 
           }).getByRole('textbox')
       
 2) <input title="" tabindex="0" type="password" class="k-i…/> aka locator('kendo-formfield').filter({ hasText: 'Confirm Password *' }).getByRole('textbox')
        
        This is the error I get. 
        
         await page.locator('kendo-formfield').filter({ hasText: 'Password *' }).getByRole('textbox').fill('!Tester123');  
         await page.locator('kendo-formfield').filter({ hasText: 'Confirm Password *' }).getByRole('textbox').fill('!Tester123');
         
         These are the lines of code I have the problem with. 
         
         How can I get past this error, I tried using Xpath but then I come across another problem that locator cannot be located.
         
         Thanks for anyone willing to help out.

**Comment by pavelfeldman** [comment]
I'm not sure what your question is, but you can read about the locators here: https://playwright.dev/docs/next/locators. Maybe you want `hasText: /Password \*/` to make sure it is not a substring.
