### ISSUE TITLE
[BUG] waitForInteractable is missing

### ISSUE THREAD

**Issue by Hulkmaster** [microsoft/playwright#21371]
option was added in https://github.com/microsoft/playwright/pull/934/files

but seems to be missing in current version and i cannot find anything related to why it is missing

also cannot find anything alike in documentation

**Comment by pavelfeldman** [comment]
There is no such method in our API, you are referring to an internal change. Playwright will perform the actionability checks itself. See https://playwright.dev/docs/next/actionability#assertions

**Comment by Hulkmaster** [comment]
I was looking for a way to "await" for an element to be "uncovered" by other elements before doing action

and that API sounded perfect for me
