### ISSUE TITLE
[BUG] Electron windows open with `playwright-core/lib/server/electron/loader.js` as argument

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#21387]
### System info
- Playwright Version: v1.31.2
- Operating System: All
- Browser: All
- Other info:

### Source code

We use `playwright._electron.launch` and `electron.firstWindow()` to smoke test VS Code. We noticed that with the latest version, a file `playwright-core/lib/server/electron/loader.js` opens, so we assume it is being added to the path when launching VS Code.

This breaks all our smoke tests that assume no file would open. 

//cc @mxschmitt

**Comment by pavelfeldman** [comment]
@bpasero :wave: 

> we assume it is being added to the pat

Do you mean added to the list of the arguments? Everything is fine according to our tests. I just added another one: . How to you check raw argv: https://github.com/microsoft/playwright/pull/21388/files#diff-25a018cac50f8f5e3a9f2a7691a61391be2e5995e74d9cc03a058be43163a795R54

How do you access your args?

**Comment by bpasero** [comment]
We actually use `minimist` 3rd party module for the args parsing and it will put arguments without `-` or `--` prefix in an array that we consider for paths to open.

Btw I had talked with Max before and he indicated he knows what this is...

**Comment by pavelfeldman** [comment]
`minimist` is just a parser, but I assume you feed `process.argv` to it and `process.argv` is good in our tests. Any chance for a repro?

> Btw I had talked with Max before and he indicated he knows what this is and suggested to file an issue.

I doubt he has additional insight into this one, I was the last one touching this code.

**Comment by bpasero** [comment]
I can try to come up with something. To reproduce in VS Code:
* I have a branch https://github.com/microsoft/vscode/tree/ben/update-playwright where you just need to `yarn`
* then run `yarn smoketest --build <path to Code - Insiders.app in Applications folder>`
* notice how the first window that opens has `loader.js` opened

**Comment by pavelfeldman** [comment]
Actually, I can see how this can be a bug on our side. We run your app as follows:

```js
electron(.exe) loader.js yourapp.js
```

We assume that executable path points to electron executable and your app is passed as an argument. For the deployed app this is not the case though and you probable point us to code.exe, which means that you start getting the silly loader. We need that loader to serialized some internal events that race between Node and the browser, so we should probably do something different or opt out of this mode for the deployed apps, we have not seen that race manifest itself there yet.

**Comment by bpasero** [comment]
Yes, that is the bug.

**Comment by dgozman** [comment]
Fixed by #21577.
