### ISSUE TITLE
[Question] How to return to main page and open a new tab

### ISSUE THREAD

**Issue by WallaceAnalista** [microsoft/playwright#21390]
I'm opening a new tab,  through my main screen inspecting a field and using .click({ button: 'middle' }); To open a new tab.

Steps executed:

1 - Open main screen
2 - Click on an element with the button (middle)
3 - Focus on that new tab that was opened.
4 - Close the new tab that was opened.
5 - Return to the main page.

Below code used:

   //Accessing new tab
    const pagePromise = context.waitForEvent('page');         
    await page.locator('[data-name="Group 635"]').click({ button: 'middle' });             
    const newPage = await pagePromise;
    await newPage.waitForLoadState();
    await newPage.bringToFront();     
    await newPage.close();

My doubt is. In main page again, how do I open a new tab, click on another field and redo all the previous steps.
Please, could someone help me?

**Comment by pavelfeldman** [comment]
You do it exactly the same way you did it the first time?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by WallaceAnalista** [comment]
yes, it was done exactly like the first time.
