### ISSUE TITLE
[BUG] Wrong file name in the output of the "playwright test --list" cmd

### ISSUE THREAD

**Issue by DOrlov77** [microsoft/playwright#21404]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [All]
- Browser: [not relevant]

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
...
    testDir: "tests",
    testMatch: "**/*.spec.ts",
...
});
```

**Test file (self-contained)**

```ts
// test.utl.ts
import { expect, test } from "@playwright/test";

export function sharedTest() {
    return test("The Shared Test", () => expect(true, "the smart shared test").toBeTruthy());
}
```

```ts
// suiteN.spec.ts
...
test.describe.serial("Suite N", () => {
    test("Test A", () => {...});

    sharedTest();

    test("Test B", () => {...});
});
```

**Steps**
```
playwright test --list
```

**Expected**

The output contains the filenames and suites according to the `*.spec.ts` mask only.

**Actual**

The output contains also the permutations of  `test.utl.ts > Suite N The Shared Test` instead of `suiteN.spec.ts > Suite N The Shared Test`

**Workaround**

Not found.
Trying to set config property `testIgnore: "**/test.utl.ts"` doesn't effect.

**Comment by pavelfeldman** [comment]
We show the location of the test where it is defined, test.utl.ts in this case, so this is working as expected.

**Comment by DOrlov77** [comment]
That is exactly THE bug, if you are running such a suite - the report will show the correct data and the shared test case will be displayed inside the relevant spec file and suite!

**Comment by Tal-D** [comment]
@pavelfeldman, @mxschmitt  I had also encountered the same issue. Could you please reopen the issue?
