### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AIPythoner** [microsoft/playwright#21407]
### System info
- Playwright Version: [v1.18.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

I manually opened a new tab page and couldn't load the page directly,
 it was blank, and some websites couldn't jump after logging in

**Comment by mxschmitt** [comment]
Closing since we need clear reproduction steps and you didn't follow our bug template. Please re-file with more information so we can act on it.
