### ISSUE TITLE
[Question] Is there a way to get style attribute's inner properties value?

### ISSUE THREAD

**Issue by 2017867924** [microsoft/playwright#21406]
Hi !every body.
I want to get the value of property color and  the result is "rgb(220, 190, 10)" in  those codes:
`<p  class="hello-color" style="color: rgb(220, 190, 10);"></p>.`

please help ,how can I code with JAVA?
thx!

**Comment by mxschmitt** [comment]
You can do: `string value = page.locator("...").evaluate("element => getComputedStyle(element)['color']`) which should work for that.

**Comment by mxschmitt** [comment]
Closing as per triage process, feel free to re-file for further questions.
