### ISSUE TITLE
[Feature] It will be very nice if Playwright naturally support swipe action for mobile devices

### ISSUE THREAD

**Issue by nnson0310** [microsoft/playwright#21419]
I tried with below code to try to stimulate the swipe action of mobile devices but it does not works. I also try dragAndDrop feature with some hope but it is the same.

```js
test("Verify carousel block by right swipe", async ({page}) => {

   await test.step("", async () => {
      await MethodHelper.sleepInSeconds(1);
      const bb = await page.locator("div.carousel-hero-block").boundingBox();
      console.log(bb.x);
      console.log(bb.width);
      console.log(bb.y);
      console.log(bb.height);
      await page.mouse.move(bb.x + bb.width / 2, bb.y + bb.height / 2)
      await page.mouse.down();
      await page.mouse.move(bb.x + 200, bb.y);
      await page.mouse.up();
      await MethodHelper.sleepInSeconds(1);
   })
})
```
I also do some research and found out that there is a feature request [https://github.com/microsoft/playwright/issues/2903](url) to support native gestures for mobile devices. But this request is lying there from 2020 and it seems no progress at all. It will be really helpful and appreciate if Playwright can support these features in future releases. Or at least we can get some news because we are heavily depend on Playwright now for our mobile automation testing project. Thank you.

**Comment by mxschmitt** [comment]
There was not a lot of interest in the linked issue, hence we didn't implement it yet. (We priorities based on upvotes)

Folding into https://github.com/microsoft/playwright/issues/2903

**Comment by IPRIT** [comment]
Any news?

**Comment by MNovy101** [comment]
Any updates on this issue?  We are still experiencing this on our team.

**Comment by rerurk** [comment]
so...Any news about it?

**Comment by inasribrahim** [comment]
Hello 👋  any updates for implementation swipe ?
