### ISSUE TITLE
[BUG] cannot save api authenticate

### ISSUE THREAD

**Issue by wekuang** [microsoft/playwright#21416]
I tried to use the api to login to my app according to the steps of the API Doc and the login was successful, but the value was empty after the auth file was created
https://playwright.dev/docs/auth#authenticate-with-api-request
```js
{
   "cookies": [],
   "origins": []
}
```
### System info
- Playwright Version: [v1.31]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- Other info: API request

### Source code
https://playwright.dev/docs/auth#authenticate-with-api-request

```js
// playwright.config.ts
import { test as setup, expect } from '@playwright/test';

const authFile = 'playwright/.auth/user.json';

setup('authenticate', async ({ request }) => {
  // Send authentication request. Replace with your own.
  let res = await request.post('https://my_app', {
        headers: {
            'Content-Type': 'application/json;charset=UTF-8',
            'Accept': 'application/json',
        },
        data: {
            'email': 'my_user',
            'password': 'my_password'
        }
  });

    expect(await res.ok()).toBeTruthy(); //pass
    console.log('##### res.body: ' + await res.body()) //login ok

  await request.storageState({ path: authFile });
});
```

**Comment by mxschmitt** [comment]
Maybe your app does not use cookie based login or the frontend does manually save the cookie? Or saves it to localstorage?

I'd check the response body and response headers of the HTTP request to see if the endpoint is sending some token etc.

**Comment by mxschmitt** [comment]
Closing as per triage process, feel free to re-file for further questions.

**Comment by jfbn** [comment]
> Maybe your app does not use cookie based login or the frontend does manually save the cookie? Or saves it to localstorage?
> 
> I'd check the response body and response headers of the HTTP request to see if the endpoint is sending some token etc.

Our auth service does not use cookie based authentication but header based authentication. 

When running our setup script:

```js
setup('authenticate as a regular user', async ({ request }) => {
  await request.post(
    'https://secret-auth-domain.com/login/email/password',
    {
      data: {
        email: 'some@email.com,
        password: 'secretPassword',
      },
    }
  )

  await request.storageState({ path: serviceAdvisorFile })
})
```

The POST request will receive a token in the payload of the response - that's the token we wish to use to authenticate future requests.

How can this be achieved? All working examples I find assume a cookie based approach.

**Comment by LinhDo-LGG** [comment]
I guess you can set the authorization header after making the post request.
![image](https://github.com/microsoft/playwright/assets/87288723/7458a15d-3301-479c-896f-2905a2aad372)

**Comment by ViktorMacib** [comment]
**wekuang**, can you please, explain how you solved this issue?

**Comment by henbf** [comment]
Here is my solution for saving the token to localStorage:
```
import path from "node:path";
import { test as setup } from "@playwright/test";

setup('auth setup', async ({ browser, request }) => {
  const { token } = await request.post(`/api/login`, {
    data: {
      'username': 'username',
      'password': 'password'
    }
  }).then(r => r.json());

  const fileName = path.resolve(setup.info().config.rootDir, `.auth/auth.json`);
  const context = await browser.newContext({
    storageState: {
      cookies: [],
      origins: [{ origin: '', localStorage: [{ name: 'token', value: token }] }]
    }
  });
  await context.storageState({ path: fileName });
});
```
