### ISSUE TITLE
Iterating over a list of elements and .click()-to-remove each. This is what worked for me

### ISSUE THREAD

**Issue by jkohlin** [microsoft/playwright#21410]
I realized it wasn't possible to do a `for await (item of await listItemLocator.all())` to click each item in the list, when the purpose is to delete the item.
The reason for this is that Playwright internally uses nth(0), nth(1)... to click elements. And if the button deletes the element at nth(0) then nth(1), if there are two elements, will not be there. 
So a recursive function is the solution:

```typescript
async function removePills(pills: Locator) {
    const pillButtons = await pills.all();
    if (pillButtons.length > 0) {
        await pillButtons[0].click();
        await removePills(pills);
    }
}
await removePills(
    this.iframe.getByTestId("pw-provider-pill").getByRole("button")
);
```

_Originally posted by @jkohlin in https://github.com/microsoft/playwright/issues/2034#issuecomment-1451479774_

**Comment by mxschmitt** [comment]
Since there is no question in this issue and its no bug report, we can't act on it. Closing by that.

**Comment by sufiyangorgias** [comment]
Recursive function to delete the row seems to be working for me as well.
