### ISSUE TITLE
[Feature] Update `npx playwright show-report` for yarn & pnpm users

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#21425]
The code prints the following message: https://github.com/microsoft/playwright/blob/e222874445f69af4ff389f29e322d0a98e2d8c20/packages/playwright-test/src/reporters/html.ts#L128

For yarn & pnpm, you can just use `yarn playwright show-report` & `pnpm playwright show-report`, which is more correct. It would be nice to update this message for such users depending on the used package manager.

**Comment by mxschmitt** [comment]
We could do something like done in create-playwright: [the place where the package manager gets determined](https://github.com/microsoft/create-playwright/blob/f6087f59b04c3b000e326d9edc9ddd28687ce919/src/packageManager.ts#L99-L108).

Happy to get a PR for it.

**Comment by segevfiner** [comment]
This actually might also appear in other messages, so we likely want to fix those as well, I guess a grep on `npx` might reveal those.
