### ISSUE TITLE
[Feature] Wait for URL

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#2142]
Hey team. Congrats on the 1.0 release! 🎉  Great stuff.

I often find myself using this pattern.

```js
await page.click('.e2e-get-started-button');
await page.waitForSelector('.e2e-welcome-header');
expect(page.url()).toMatch('/start');
```

The reason for this is that my client-side router doesn't immediately change the URL after clicking on the button that triggers the navigation. I wonder if you'd be open to a new method on `Page` that looks something like this.

```js
await page.click('.e2e-get-started-button');
await page.waitForURL('/start');
```

Not entirely sure about the API - in my example it's not 1:1 since I'm doing match vs. equality. But I'm curious what you think of the idea in general of waiting for a URL.

Thanks!

**Comment by dgozman** [comment]
`page.waitForNavigation()` accepts a `url` option - would that work for you?

**Comment by celeryclub** [comment]
Yeah I think it would. :) Sorry I missed that. Thanks!
