### ISSUE TITLE
[BUG] testInfo.snapshotDir didn't work

### ISSUE THREAD

**Issue by minhphong306** [microsoft/playwright#21426]
### System info
- Playwright Version: 1.31.1
- Operating System: All
- Browser: Chromium
- Other info:
  - I've used Playwright version `1.21.1` before. When run below code, if snapshot doesn't exist, a folder named `${__filename}-snapshots-local` will be created at the same folder of running test file.
  - After update to version `1.31.1`, below code not work any more. It doesn't create folder `${__filename}-snapshots-local`, it create folder with default name ``${__filename}-snapshots` only.

### Source code
`tests/demo.spec.ts`
```typescript
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ }, testInfo) => {
  testInfo.snapshotSuffix = "";
  testInfo.snapshotDir = `${__filename}-snapshots-local`;
});

test('example test', async ({ page }) => {
  await page.goto('https://playwright.dev');
  expect
    .soft(await page.locator('html').screenshot())
    .toMatchSnapshot('test.png',
      { maxDiffPixelRatio: 0.005 }
    );
});
```

**Steps**
- [Run the test]: 
```
npx playwright test  tests/demo.spec.ts
```

**Expected**

Folder `demo-snapshots-local` created inside `tests/` folder.

**Actual**
Folder `demo-snapshots` created inside `tests/` folder.

**Comment by dgozman** [comment]
@minhphong306 This is not supposed to work, because test runner assumes that `TestInfo.snapshotDir` is a readonly property. If you would like more control over snapshots location, take a look at [`snapshotPathTemplate`](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template).
