### ISSUE TITLE
[BUG] Tip of the day: use lint rule for no dangling promises

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#21436]

**Comment by mxschmitt** [comment]
https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-floating-promises.md

**Comment by segevfiner** [comment]
Just note that this requires configuring type checking in ESLint correctly, which is often beneficial, but not all projects do so, and it can be a bit of a struggle in more complicated projects.
