### ISSUE TITLE
toBeInViewport throws Unknown expect matcher: to.be.in.viewport

### ISSUE THREAD

**Issue by jwickens** [microsoft/playwright#21434]
### System info
- Playwright Version: v1.31.2
- Operating System: Windows 11 WSL
- Browser: Chromium
- Other info:

### Source code

```js
it('should be in the viewport', async ({ page }) => {
    const button = page.getByRole('button').first();
    await expect(button).toBeVisible();
    await expect(button).toBeInViewport();
});
```

**Expected**

The test passes, using the toBeInViewport function described here https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-in-viewport

**Actual**
We get past the `toBeVisible` expectation but not the `toBeInViewport`
```
expect.toBeInViewport: Error: Unknown expect matcher: to.be.in.viewport
    at button.spec.js

Execution log

expect.toBeInViewport with timeout 5000ms
waiting for getByRole('button').first()
```

**Comment by jwickens** [comment]
@dgozman LMK if you can't reproduce...

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

**Comment by jwickens** [comment]
This was due to a bad installation, sorry for the distraction and thanks for the response.
