### ISSUE TITLE
[Question] How can I get multiple html reports using npm concurrent?

### ISSUE THREAD

**Issue by kLjubomir** [microsoft/playwright#21431]
Hello,
I am using Playwright in JavaScript and due to project requirements, the parallelization is done by grouping and using npm concurrent (to avoid double user sessions, can't control test data)

Locally when I run the suite I get served two reports but at the end have only one index.html in my playwright-report, but when this is run on Jenkins, the htmlpublisher plugin serves everything within playwright-report and it only contains the last report, as the new index.html overrides the old one.

So I am looking to generate separate reports per concurrent script run.

I've been researching this a lot today and can't seem to find a solution:
tried using just the CLI parameters --output="reports-uk" and in the other npm script --output="reports-de" -> what happens is the webm files usually located in test-results are generated in these new folders, but then the report is still one index.html from playwright-report

I tried using `outputPath` in my configs reporter property as: process.env.OUTPUT_PATH || 'playwright-local/report.html',
Then in my scripts I have: 
```
  "scripts": {
    "test": "cross-env test_env=staging npx playwright test",
    "run-de": "cross-env test_env=%environment_name% OUTPUT_PATH=playwright-report/de npx playwright test --project=de %scope%",
    "run-uk": "cross-env test_env=%environment_name% OUTPUT_PATH=playwright-report/uk npx playwright test --project=uk %scope%",
    "execute-all": "concurrently %runCountries%"
  },  
```

But I still only get one report named index.html at playwright-report folder.

Since documentation is a little bit scarce on the html reporter, is there a way for me to make the 2 reports have different names over CLI and have them in one folder? Whatever I do I always end up with index.html somehow.
If not, how could I specify two folders for reports that would each have one of index.html so as not to override the reports?

**Comment by mxschmitt** [comment]
You need to customise the output directory for the [HTML Reporter](https://playwright.dev/docs/test-reporters#html-reporter). You can do this by setting the `PLAYWRIGHT_HTML_REPORT` environment variable to something different.

**Comment by mxschmitt** [comment]
You need to set this environment variable per project and not system wide.

Something like this would work:

```ts
// config file
const EnvName = process.env.ENV_NAME || 'local';

export default defineConfig({
  outputDir: `test-results-${EnvName}`,
  reporter: [['html', {
    outputFolder: `playwright-report-${EnvName}`,
  }]],
// ...
```

```json
{
  "scripts": {
    "test": "playwright test",
    "test-parallel": "concurrently \"cross-env ENV_NAME=QA playwright test --workers=2\" \"cross-env ENV_NAME=test playwright test --workers=2\""
  },
}
```

Generally speaking we don't recommend it, we recommend concurrency done with Playwright instead.

**Comment by kLjubomir** [comment]
Playwright does not have an option to do concurrent runs, it can currently only execute parallel runs, the difference being "the ability to run multiple projects at the same time using one worker per project". there is a feature request (according to my understanding) which is in state[ P3-collecting-feedback](https://github.com/microsoft/playwright/issues/18950) so to achieve concurrency I have to use npm concurrent.

Furthermore, configuring env inside config file will not help me as I can not specify a reporter per project but it is config-wide, meaning if I wanted to have 2 reports using 2 concurrent pipelines, I'd have to duplicate playwright.config.js and inside every specific playwright.config.js for an instance of concurrency therein specify reporter folder and file name.

If we could consider this issue a feature request it would read:
As a user of Playwright, I would like to be able to specify custom reporter properties from within a "projects" so that in concurrent runs I could get a html report foreach project that has finished executing. a.k.a` (property) Config<PlaywrightTestOptions, PlaywrightWorkerOptions>.projects?: Project<PlaywrightTestOptions, PlaywrightWorkerOptions>[] | undefined`

**Comment by mxschmitt** [comment]
Does https://github.com/microsoft/playwright/issues/21431#issuecomment-1457831207 work for you?

**Comment by kLjubomir** [comment]
No, the proposed solution does not work for me.
My code:
playwright config:

```
// @ts-check
const { devices } = require('@playwright/test')
const ukVehicles = require('./ssm/test_data/ukVehicles.json');
const ukSearchByModelData = require("./ssm/test_data/ukSearchByModel.json");
const EnvName = process.env.ENV_NAME ||'local';

/**
 * @see https://playwright.dev/docs/test-configuration
 * @type {import('@playwright/test').PlaywrightTestConfig}
 */
const config = {
  testDir: './ssm',
  outputDir: `test-results-${EnvName}`,
  /* Maximum time one test can run for. */
  timeout: 75 * 1000,
  workers: 1,
  //Can set url: param here
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(lofcator).toHaveText();`
     */
    timeout: 5000
  },
  reporter: [
    ['html', {
      open: 'always',
      outputFolder: `playwright-report-${EnvName}`
    }]
  ],
  retries: 2,
  projects: [
    {
      name: 'de',
      grep: /@de/,
      use: {
        baseURL: process.env.BASE_URL,
        browserName: 'chromium',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',
        headless: true,
        viewport: { width: 1920, height: 1080 },
        trace: 'retain-on-failure',
        launchOptions: {
          args: ['--start-maximized'],
          //executablePath: '/root/.cache/ms-playwright/chromium-1045/chrome-linux/chrome'
        }
      }
    },
    {
      name: 'uk',
      grep: /@uk/,
      use: {
        baseURL: process.env.BASE_URL,
        browserName: 'chromium',
        screenshot: 'only-on-failure',
        video: 'retain-on-failure',
        headless: true,
        viewport: { width: 1920, height: 1080 },
        trace: 'retain-on-failure',
        launchOptions: {
          args: ['--start-maximized'],
          //executablePath: '/root/.cache/ms-playwright/chromium-1045/chrome-linux/chrome'
        },
        // @ts-ignore
        vehicles: ukVehicles,
        searchByModelData: ukSearchByModelData
      }
    }
  ],
  globalSetup: 'ssm/test_configuration/globalSetup.js'

}
module.exports = config

```
Inside my package.json I have these scripts:
```
  "scripts": {
    "test": "cross-env test_env=staging npx playwright test",
    "run-de": "cross-env test_env=%environment_name% ENV_NAME=QA npx playwright test --project=de %scope%",
    "run-uk": "cross-env test_env=%environment_name% ENV_NAME=UK npx playwright test --project=uk %scope%",
    "execute-all": "concurrently %runCountries%"
  },  

```
The bash script basically appends environment first, then scope (by tag smoke test or regression), then if uk param is true appends \"npm:run-uk\" to the runCountries, if de is true appends that, if both are false just adds a generic regex to run all \"npm:run-*\"
The dotenv maps staging base url into the environment name in this example below
When I run bash runtest.sh staging smoke_test true true
What happens is: I get test-result-QA and test-result-UK but the index.html is not even generated... the tests run correctly though, am I doing something wrong?

**Comment by kLjubomir** [comment]
I apologize, the proposed solution does appear to work.

It did not work at first because I had set the environment variable in my PC for PLAYWRIGHT_HTML_REPORT to a different destination.
