### ISSUE TITLE
[BUG] Facing with `net::ERR_ABORTED` while trying `route.abort()` 

### ISSUE THREAD

**Issue by storenth** [microsoft/playwright#21451]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Mac
- Python version: 3.11
- Browser: Chromium

**Code Snippet**
```python
# conftest.py
@pytest.fixture
def page(page: Page):
    page.route(
        "https://mc.yandex.ru/*",
        lambda route: route.abort()
    )
    yield page
```

**Describe the bug**
I need abort specific requests to speed up my tests, so I rewrite `page` and enable aborting but facing the next issue 
as soon as the first unwanted request occurs:
```bash
playwright._impl._api_types.Error: net::ERR_ABORTED
```
Unexpected behavior because few `goto` methods  side by side I guess:
<img width="566" alt="test-snipped" src="https://user-images.githubusercontent.com/18244131/222138404-edf92dcc-0f10-4891-97cf-c6b22a5c12b0.png">
<img width="898" alt="exception" src="https://user-images.githubusercontent.com/18244131/222138462-59d3d8c1-66b7-42e6-8c13-7baddbd09252.png">
<img width="1329" alt="err" src="https://user-images.githubusercontent.com/18244131/222138497-2d91abc6-4de9-4bd6-b903-da985eb999c5.png">

Worked as expected if I use only one `goto`.

**Comment by yury-s** [comment]
Your page starts navigation by assigning a new url to `window.location` (the seems to be `https://auth.dreap.idacloud.ru/realms/...`) and that interferes with `page.goto`. Only one of the two navigations will be committed and if it is the one triggered by the page the error is thrown from page.goto. You should use [waitForURL](https://playwright.dev/docs/api/class-frame#frame-wait-for-url) for the page to finish the redirects to avoid the race condition:

```js
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.context().tracing.start({ snapshots: true });
  await page.route('https://rs.mail.ru/*', route => route.abort());

  await page.goto('https://business-stage.samoletx.com/', { waitUntil: 'domcontentloaded' });
  await page.locator('[id="loader"]').waitFor({ state: 'hidden', timeout: 15000 });
  // Wait for the redirects:
  await page.waitForURL('https://auth.dreap.idacloud.ru/**');
  await page.goto('https://business-stage.samoletx.com/');
  // Wait for the redirects:
  await page.waitForURL('https://auth.dreap.idacloud.ru/**');

  await page.goto('https://business-stage.samoletx.com/');
  await page.context().close();
  await browser.close();
})();
```

**Comment by akshaysarode31** [comment]
I am facing somewhat similar issues on my project. can someone help me with this issue? I have been facing this for a while and I am stuck now

Below is the link to my project
https://github.com/akshaysarode31/PlaywrightFramework
