### ISSUE TITLE
Tests show they are debugging but nothing happens.

### ISSUE THREAD

**Issue by Andyandhisboard** [microsoft/playwright#21465]
Hello,

I was debugging tests fine this morning, had a forced reboot, and now all of a sudden when trying to debug nothing appears to be happen (even though it looks like it's debugging).  This has happened before, but always seems to resolve itself, with no luck so far this time.

I'm able to debug in a different repo just fine.  I've uninstalled and reinstalled Playwright Test for VSCode multiple times with no luck.  Any help would be appreciated.  See screenshots for the "appearance of debugging", but nothing happening.

The only outputs I can find that may be helpful are:
Angular Language Service:
        [Error - 8:23:08 AM] No config file for "file path here" (This is the file containing the test I'm trying to run).

       I have a feeling it has something to do with this since it's an error, but I've changed nothing to any configs since it was debugging fine this morning.  I'm also unaware of any configs for this (and other) test file(s) specifically besides the default playwright config.

Git (This is outputting about every 1-2 seconds):
        2023-03-07 08:34:34.020 [info] > git rev-parse --show-toplevel [1097ms]        

![image](https://user-images.githubusercontent.com/67791240/223436082-fe483a93-b9a3-4dc1-9393-00dd5f8f8833.png)

![image](https://user-images.githubusercontent.com/67791240/223436412-66c2f6cc-c92f-4b10-8704-2cd7f0b798ec.png)

![image](https://user-images.githubusercontent.com/67791240/223436511-75629bdb-939d-4c68-afc8-b038453b996c.png)

**Comment by mxschmitt** [comment]
Have you tried to entirely stop VS Code and start it again? Which operating system are you using?

**Comment by Andyandhisboard** [comment]
> Have you tried to entirely stop VS Code and start it again? Which operating system are you using?

Yes I've tried rebooting multiple times, restarting VS Code multiple times.  I even completely deleted the repo locally and cloned it back down locally and forced a reinstall of playwright.  I've noticed that both debugging, or "show browser" causes the same problem where it appears to be running, but nothing really happens.  I'm running Playwright Test for VS Code v1.0.8, and here is VS Code info:

Version: 1.76.0 (system setup)
Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
Date: 2023-03-01T10:22:44.506Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No


This sounds a lot similar to this bug: https://github.com/microsoft/playwright/issues/18424 however from what I can tell this was fixed with a new version of Playwright Test for VS Code.  I don't know if that's the problem since mine was working fine until a forced reboot, and I've also installed the previous version of the extension with the same results.

When I reinstalled playwright, it installed a newer version of chromium which I was hopeful per some of the responses in that other bug, but still no luck.  Any other ideas would be greatly appreciated!

Thanks,
Andy

**Comment by MAFleetGO** [comment]
I had the same issue when I updated the extension to 1.08 today. The GUI was stuck on 'running tests' just like OP mentions. Reinstalling the extension and rebooting VS Code didn't help fix it, but reverting to 1.07 did. These are the steps I took to get it to work again. 

- Uninstall the playwright extension.
- Install the latest version (1.08) of the playwright extension.
- Reboot VS Code and try to start a test in debug mode (GUI was still stuck on 'running tests')
- Install 1.07 of the playwright extension
- Reboot VS Code
- Running tests in debug mode now worked again.

**Comment by mxschmitt** [comment]
Which Playwright version are you using?

**Comment by MAFleetGO** [comment]
> 

I'm using 1.27.1

**Comment by mxschmitt** [comment]
Try upgrading, then the extension should work!

**Comment by MAFleetGO** [comment]
Can confirm this works on my end, thank you!

**Comment by mxschmitt** [comment]
cool! Just released a new VSCode version which contains a fix for it (shows a warning that you need to upgrade Playwright to make the extension work).

**Comment by KennySporck** [comment]
Issue present again in 1.1.1 backrolled to 1.0.22 and issue is resolved.

**Comment by mxschmitt** [comment]
Please file a new issue, thanks!
