### ISSUE TITLE
[BUG] Screenshot - scroll into view is always used

### ISSUE THREAD

**Issue by rdark100** [microsoft/playwright#21469]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info: Element - scroll into view is always used, it should be

**Expected**

Screenshot of element - scroll into view is always used, so if you use hover the element, it scrolled and hover is sometimes lost (highcharts.js). It would be great to have options if you want scroll or not.  - There is a workaround to get screenshot of whole page and then crop it

**Actual**

Scroll into view is always used and sometimes it is not requested behavior

**Comment by mxschmitt** [comment]
I tried the following but was not able to reproduce it, could you help me creating a reproducible?

```ts
it('should not scroll into view when making a screenshot (make sure hover does not blur)', async ({ page }) => {
  await page.setContent(`
    <style>
    body {
      margin: 0;
    }
    #button {
      position: absolute;
      top: 0;
      left: 0;
      width: 100px;
      height: 100px;
      background: blue;
    }
    #button:hover {
      background: red;
    }
    </style>
    <button id="button">Click me</button>
  `);
  await page.hover('#button');
  await expect(page.locator('#button')).toHaveScreenshot('screenshot.png');
});
```

**Comment by rdark100** [comment]
Today I can't reproduce it anymore. I restarted selenium grid and it works smoothly. I apologize :)
