### ISSUE TITLE
[BUG] 'use' function in automatic fixtures still expects an argument 

### ISSUE THREAD

**Issue by dd-jonas** [microsoft/playwright#21463]
### System info
- Playwright Version: v1.31
- Operating System: All
- Browser: All

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

**Test file (self-contained)**

```js
import { test as base } from '@playwright/test';

export const test = base.extend<{ foo: never }>({
  foo: [
    async ({}, use) => {
      // Some stuff here

      await use(); // TS error: Expected 1 arguments, but got 0.

      // Other stuff here
    },
    { auto: true }
  ],
});
```

**Expected**

Allowing `use` to be called without arguments, as demonstrated in the docs under [Automatic Fixtures](https://playwright.dev/docs/test-fixtures#automatic-fixtures).

**Actual**

`Expected 1 arguments, but got 0.`

**Comment by mxschmitt** [comment]
This is as designed, you need to specify an empty object instead, see https://github.com/microsoft/playwright/issues/8798 where it was previously filed.

**Comment by mxschmitt** [comment]
You can pass `void` to `foo` instead of `never`. Would that work for you?

**Comment by dd-jonas** [comment]
Didn't consider that, thanks. Looks like a clean solution to me!
