### ISSUE TITLE
[BUG] CreateProcess error=5, 拒绝访问。

### ISSUE THREAD

**Issue by hyjlmj** [microsoft/playwright#21475]
### System info
- Playwright Version:  1.31.0
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:  

### Source code
![image](https://user-images.githubusercontent.com/40550411/223601619-70dbdf73-72a8-4db7-864c-a59fd38cec75.png)

![image](https://user-images.githubusercontent.com/40550411/223601685-aa7eeb36-089d-49e3-a7a5-879d856412ec.png)

java run error

![image](https://user-images.githubusercontent.com/40550411/223602223-b7fa7578-b585-4574-9150-47db86add0bf.png)

playwright  folder

C:\Users\think\AppData\Local\ms-playwright
![image](https://user-images.githubusercontent.com/40550411/223601839-d284cd0b-f21a-4cc0-a282-f270b3c07f66.png)

Who can help me solve the problem？

**Comment by mxschmitt** [comment]
Do you have any special security software, anti virus or company policies on your system which prevent you from launching an executable which is in the Temp folder? Error 5 means usually that since its coming from OS.

**Comment by mxschmitt** [comment]
Closing as per triage process, feel free to re-file for further questions.

**Comment by xvjialing** [comment]
Is there a solution to this problem, I also encountered this problem
