### ISSUE TITLE
IsVisible/innerText is not working.

### ISSUE THREAD

**Issue by JeevanHB** [microsoft/playwright#21479]
locator.isVisible(xpath=//workspace[@ng-model="workspace.name"]/a)— ../../../workspaces/page/workspacesPage.js:112
  111 |             // var text = getPage().locator(this.locator);
  112 |             console.log("Text is "+ await getPage().locator(this.workspaceNameInListingLoc).isVisible())
      |                                                                                             ^
  113 |             return await getPage().locator(this.workspaceNameInListingLoc).innerText();

Please guide us what is the syntax we r missing in above code, Isvisble/innerText is not working in our script.
![image](https://user-images.githubusercontent.com/52357464/223654236-77a33af5-be4c-4175-b9e3-d7f440ea1360.png)

![image](https://user-images.githubusercontent.com/52357464/223651423-f333c219-0053-4944-84ad-cb33f1d48d35.png)

**Comment by nnson0310** [comment]
It seems your locator does violate strict mode of Playwright. Strict mode means your locator should and must resolve to only one web element. In stack trace, it resolves to 15 elements.

**Comment by mxschmitt** [comment]
As per above, a strict mode violation is if a locator resolves to multiple elements. To solve this you can do e.g.

- [nth](https://playwright.dev/docs/api/class-locator#locator-nth)
- [first](https://playwright.dev/docs/api/class-locator#locator-first)
- [last](https://playwright.dev/docs/api/class-locator#locator-last)

to target a specific element. You can also call `.locator('more specific')` on your existing locator to make it more specific.

**Comment by JeevanHB** [comment]
Thanks
