### ISSUE TITLE
How to make playwright only open the browser for testing but not close the browser

### ISSUE THREAD

**Issue by lixijia2009** [microsoft/playwright#21477]
I want to use playwright to develop a tool to open various common websites.
How to make playwright only open the browser for testing but not close the browser？

**Comment by mxschmitt** [comment]
If this is about end-to-end testing you can use the VSCode extension to run your tests, and then the browser stays open when the "Show browser" checkbox is checked.

Since the question is not clear, could you elaborate what you are trying to do?

**Comment by mxschmitt** [comment]
Closing as per above, please re-file for more questions.
