### ISSUE TITLE
[BUG] Webkit doesn't fire all XMLHttpRequest upload events

### ISSUE THREAD

**Issue by DerGernTod** [microsoft/playwright#21489]
### System info
- Playwright Version: v1.31.2
- Operating System: Windows 11
- Browser: WebKit

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```js
var x = new XMLHttpRequest();
x.upload.addEventListener("loadstart", () => console.log("upload loadstart"));
x.upload.addEventListener("progress", () => console.log("upload progress"));
x.upload.addEventListener("load", () => console.log("upload load"));
x.upload.addEventListener("loadend", () => console.log("upload loadend"));
x.open("POST", location.href);
x.send("foo".repeat(1000));
```

**Steps**
- Run WebKit using Playwright
- Execute code above in WebKit devtools

**Expected**

Logs in order:
* upload loadstart
* upload progress
* upload load
* upload loadend

**Actual**
Logs only "upload loadstart".

Webkit only fires the "loadstart" event when registering listeners on an XMLHttpRequest upload instance, and simply doesn't fire progress, load and loadend events. This works fine in a real Safari.

**Comment by fujii** [comment]
WebKit bug: https://webkit.org/b/253631

**Comment by mxschmitt** [comment]
Thanks @fujii!
