### ISSUE TITLE
[BUG] getByRole with customelement slots behaves differently in webkit

### ISSUE THREAD

**Issue by lucaelin** [microsoft/playwright#21487]
### System info
- Playwright Version: 1.31.2
- Operating System: Ubuntu 22.04
- Browser: WebKit

### Source code

```typescript
import { test } from '@playwright/test';

test('getByRole behaviour', async ({ page }) => {
  await page.setContent(`
    <html>
      <body>
        <my-dialog>
          <button>dont click me</button>
        </my-dialog>
        <button>click me instead</button>
        <script type="module">
        class MyDialog extends HTMLElement {
          connectedCallback() {
            this.attachShadow({mode: 'open'});
            this.shadowRoot.innerHTML = 'we dont add a slot here so the light dom is not visible'
          }
        }
        customElements.define('my-dialog', MyDialog);
        </script>
      </body>
    </html>
  `);

  // chrome finds 1 element, because only one is actually available to the user
  // webkit finds 2 elements, so strict validation fails only in webkit
  await page.getByRole('button').click(); 

  // finds 2 elements, because there are two elements in the dom
  // strict validation fails in all browsers, as expected
  // await page.locator('button').click();  
});
```

Config file is the default npm init playwright@latest, strict mode enabled.

**Steps**
- Run the test in chrome and firefox, it works
- Run the test in webkit and the click fails strict validation

**Expected**
All browsers behave the same, ideally the test should pass for all browsers.

**Actual**
WebKit seems to keep light-dom elements in the accessibility tree, even if they have no slot in the corresponding shadow-root. This causes getByRole to find more than one element to click on the page.

I am really not sure if this is a playwright issue, a playwright-webkit issues, or a webkit issue. I'd be perfectly happy with filing the issue somewhere else if we find this to be the wrong place.

Edit: Whoops, my copy pasta had an accidential display: none on the button, I removed that with an edit

**Comment by lucaelin** [comment]
Some additional findings:
In this screenshot below you can see the webkit inspector, showing no accessibility node for the button in light-dom
![grafik](https://user-images.githubusercontent.com/8896438/223723760-eec5eae2-1548-44a1-9aa2-1e6c2ae44d8b.png)

To compare here is the second button that is directly attached to the body
![grafik](https://user-images.githubusercontent.com/8896438/223723843-f87c777b-bea8-46cd-9bfe-ecf4671190a4.png)

And here is the body element, showing only one child node in the accessibility pane
![grafik](https://user-images.githubusercontent.com/8896438/223724394-5665881e-3651-4319-a554-6a1febf437af.png)

To me this looks like webkit's accessibility tree aligns with firefox and chrome and makes me even less sure about the origin of this discrepancy

**Comment by mxschmitt** [comment]
Investigation note:

https://github.com/microsoft/playwright/blob/a2490a8fc8413db5a86fe38dff2a05d5cb5f2b16/packages/playwright-core/src/server/injected/domUtils.ts#L75C7-L78

does not work in this case and the workaround returns `true` so we think its visible. I'll assign it accordingly so we'll take a look in the next release.
