### ISSUE TITLE
[Question]how to do paralle test with project module

### ISSUE THREAD

**Issue by AllenLuosong** [microsoft/playwright#21480]
Hi there
I have 2 UI test demo module in my project as below.
And I want to run it with  parallel way in order to speed up the overall execution time of my test suite.
I used the pytest-xdist plugin, and I found it will disorder my test case  but I want to run case in order.
It there any idea I can do.

![image](https://user-images.githubusercontent.com/57619311/223660539-6282e13b-3a03-4998-9389-76ef15fb2234.png)

this is the screenshot of run case without parallel
![image](https://user-images.githubusercontent.com/57619311/223663098-82c5eb49-4c4b-4ac8-af7c-68fac77fd06b.png)

**Comment by mxschmitt** [comment]
You can use https://pypi.org/project/pytest-parallel/ instead, which will keep the order of your tests.

**Comment by mxschmitt** [comment]
Closing as per triage process, feel free to re-file for further questions.
