### ISSUE TITLE
[BUG] When I run the test file and open a page, the process for accessing the page is chrome helper, not chromium. Why?puppeteer The process that visits the page is the chromium

### ISSUE THREAD

**Issue by Dengzygx** [microsoft/playwright#21482]
When I run the test file and open a page, the process for accessing the page is chrome helper, not chromium. Why?puppeteer The process that visits the page is the chromium

**Comment by mxschmitt** [comment]
This is not enough information to act on, could you provide us more details like how your config looks like, how your script looks like, the process tree and a full repro?
