### ISSUE TITLE
[Question] : Not able to find screenpath in custom report

### ISSUE THREAD

**Issue by sankarkec** [microsoft/playwright#21481]
I am trying to create my own custom report in playwright. when i take screenshot shot in onStepEnd? method i saw 'pw:api' object returned. But this object not having screenshot path where it is stored. Below is the response i got in onStepEnd method after taking screenshot. Please let me know how to get the path so i can attach the screenshot in customized report

```txt
 title: 'page.screenshot',
  titlePath: [Function: titlePath],     
  parent: {
    title: 'testReport => Step 1',      
    titlePath: [Function: titlePath],   
    parent: undefined,
    category: 'test.step',
    startTime: 2023-03-08T09:11:09.722Z,
    duration: -1,
    steps: [ [Object], [Circular *1] ],
    location: {
      file: '\\testReportValidation\\testReport.ts',
      line: 14,
      column: 24
    }
  },
  category: 'pw:api',
  startTime: 2023-03-08T09:11:09.772Z,
  duration: 286,
  steps: [],
  location: {
    file: '\\testReportValidation\\testReport.ts',
    line: 16,
    column: 45
  }
}
```

**Comment by mxschmitt** [comment]
Instead of using onStepEnd we recommend using `onEnd` and then looping over the suites, test cases and it's [attachments](https://playwright.dev/docs/api/class-testresult#test-result-attachments), see e.g. [here](https://cs.github.com/microsoft/playwright/blob/a2490a8fc8413db5a86fe38dff2a05d5cb5f2b16/packages/playwright-test/src/reporters/junit.ts?q=path%3A%2F%5Epackages%5C%2Fplaywright-test%5C%2Fsrc%5C%2Freporters%2F+attachments#L191) how the junit reporter does it.

**Comment by sankarkec** [comment]
Thanks for the solution. But whether we have any plans in future to add this at onStepEnd level so it will be easy to attach the screenshot at step level instead of test level

**Comment by mxschmitt** [comment]
There are no plans to add that since test steps are not designed for that. The solution above is the recommended approach.

**Comment by changan1111** [comment]
i am using TestInfo to attach the screenshot for each step..  the path is undefined and body is like this <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 05 00 00 00 02 d0 08 06 00 00 00 cf 7d dd 56 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 20 00 ... 107296 more bytes>. the inbuilt report has the proper name of the screenshot and attaching that. I am looking the same screenshot in customerReport.. How to get that
