### ISSUE TITLE
[Question] How can we handle SSL 42 Error  in Playwright API tests

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#21494]
Could any one assist me how can we handle the SSL certificates inorder to get the response from the server ?

**Comment by mxschmitt** [comment]
Can you provide us the full error message and/or a repro which we can run locally?

Otherwise we are not able to act on it without seeing the full error / knowing what you are trying to do.

**Comment by mridiniveni** [comment]
GET https://endpointurl
  user-agent: Playwright/1.31.1 (x64; macOS 13.2) java/11
  accept: */*
  accept-encoding: gzip,deflate,br
  charset: UTF-8
  ignorehttpserrors:  true
  content-type: application/json
============================================================
  name='Error
  stack='Error: write EPROTO C052FB0702000000:error:0A000412:SSL routines:ssl3_read_bytes:sslv3 alert bad certificate:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1600:SSL alert number 42

=========================== logs ===========================

**Comment by mridiniveni** [comment]
Here is my sample code: Playwright playwright;
        //APIRequestContext apiRequestContext;

        playwright=Playwright.create();
        Map<String,String> headers= new HashMap<>();
        headers.put("Content-Type","application/json");
        headers.put("charset","UTF-8");
        headers.put("ignoreHTTPSErrors"," true");
        headers.put("NODE_TLS_REJECT_UNAUTHORIZED","0");
headers.put("NODE_EXTRA_CA_CERTS",System.getenv("NODE_EXTRA_CA_CERTS"));
 apiRequestContext=playwright.request().newContext(new APIRequest.NewContextOptions()
                .setBaseURL("https://baseurl")
                                       .setIgnoreHTTPSErrors(true)
                                  //      .setProxy(System.getenv("no_proxy"))
                                .setProxy(proxy)

                .setExtraHTTPHeaders(headers)
                );


       APIResponse apiResponse = apiRequestContext.get("/v6/xxxx");
       System.out.println("responsecode"+apiResponse.body());

**Comment by mxschmitt** [comment]
`NODE_EXTRA_CA_CERTS` should not be a header, it should be an environment variable before you call Playwright.create().

If your endpoint requires authentication via certificates then this is not possible yet, see https://github.com/microsoft/playwright/issues/13426.

**Comment by mridiniveni** [comment]
Can we add multiple .cer and .key files to NODE_EXTRA_CA_CERTS ?

**Comment by mxschmitt** [comment]
> The file should consist of one or more trusted certificates in PEM format.

See https://nodejs.org/api/cli.html#node_extra_ca_certsfile
