### ISSUE TITLE
[BUG] Can't install Microsoft Edge channel in Windows Docker container

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#21495]
### System info
- Playwright Version: 1.27.1
- Operating System: Windows
- Browser:  MS Edge
- Other info: CI/CD on the GitLab platform using windows image containers

### Source code

**Config file**

```js
// playwright.config.ts
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
    timeout: 240000,
    globalTimeout: 18000000,
    projects: [
        {
            name: "Esro",
            testDir: "./Tests/Esro",
            timeout: 300001,
            use:{
                viewport: {width: 1870, height: 1030},
                video: {
                    mode: "retain-on-failure",
                    size: {
                        width: 1870,
                        height: 1030,
                    },
                },
            }
        },
        {
            name: "Tsro",
            testDir: "./Tests/Tsro",
            timeout: 180000,
        },
        {
            name: 'Unify',
            testDir: "./Tests/Unify",
        },

        {
            name: "IntegrationsUI",
            testDir: "./Tests/IntegrationsUI",
        },

        {
            name: "Validation",
            testMatch: 'Tests/Unify/Validation/test.list.ts',
            timeout: 360000,
            use: {
                actionTimeout: 320000,
            }
        },
        {
            name: "Production",
            testMatch: 'Tests/Unify/production.test.list.ts',
            timeout: 360000,
            use: {
                actionTimeout: 320000,
            }
        },

    ],
    reporter: [
        ["./my-reporter.ts"],
        ["list"],
        ["junit", { outputFile: "reports/test-results.xml" }],
        ["allure-playwright"],
        ["json", { outputFile: "reports/test-results.json" }],
        ["html", { open: "never" }],
    ],
    use: {
        baseURL: process.env.BASE_URL ? process.env.BASE_URL : process.env.LOCAL_HOST,
        browserName: "chromium",
        actionTimeout: 30000,
        trace: "off",
        screenshot: "on",
        viewport: { width: 1400, height: 900 }, //UNIFY Recommended Resolution
        video: {
            mode: "retain-on-failure",
            size: {
                width: 1400,
                height: 900,
            },
        },
        contextOptions: {
            ignoreHTTPSErrors: true,
        },
        // Browser options
        launchOptions: {
            channel: "msedge",
            //    headless: process.env.CI ? true : false,
            slowMo: 200,
            args: [
                "--no-sandbox",
                "--ignore-certificate-errors",
                "--ignore-certificate-errors-skip-list",
            ],
        },
    },
};

export default config;

```

**Test file (self-contained)**

```js
import test from "@playwright/test";

test.describe("Login Test Feature", () => {
    let basePage: BasePage;
    let unifyLoginPage: UnifyLoginPage;
    let mainPage: UnifyBasePage;

    test.beforeEach(async ({page}) => {
        basePage = new BasePage(page);
        unifyLoginPage = new UnifyLoginPage(page);
        mainPage = new UnifyBasePage(page);

        await basePage.loadApplication(ApplicationUrl.UNIFY);
        
    });

    test.afterEach(async ({context}) => {
        await context.clearCookies();
    });

    test("Login with wrong credentials", async () => {
        await unifyLoginPage.loginToUnify("x", "x", Credentials.INCORRECT);
    });

    test("Login with correct credentials @warmup", async () => {
        await unifyLoginPage.loginToUnify();
    });
});

```

**Steps**

- Changing the channel to the `msedge`
- Adding the step of `install msedge`
- Attempting to run the tests

**Expected**

- MSEdge browser should be installed and work
- The tests should work as well using the MSEdge browser
- 

**Actual**

The issue presented like the following:

```js
// The issue as it presented inside the pipeline:

npx playwright install --force msedge

[36mcore-ui-playwright-server_1  |[0m   Downloading Microsoft Edge

[36mcore-ui-playwright-server_1  |[0m   Installing Microsoft Edge

[36mcore-ui-playwright-server_1  |[0m   ERROR: failed to install Microsoft Edge

[36mcore-ui-playwright-server_1  |[0m   Failed to install browsers

[36mcore-ui-playwright-server_1  |[0m   Error: Failed to install msedge


// The issue as it presented inside the pipeline, during an attempt to execute tests:

[36mcore-ui-playwright-server_1  |[0m   [31m  1) [Esro] ??? Tests\Esro\EsroLoginTest.spec.ts:28:5 ??? Esro Login Tests ??? Login to eSRO with correct credentials @tSRO_AND_eSRO_APPLICATION @warmup [39m

[36mcore-ui-playwright-server_1  |[0m   

[36mcore-ui-playwright-server_1  |[0m       browserType.launch: Chromium distribution 'msedge' is not found at C:\Users\ContainerAdministrator\AppData\Local\Microsoft\Edge\Application\msedge.exe

[36mcore-ui-playwright-server_1  |[0m       Run "npx playwright install msedge"

[36mcore-ui-playwright-server_1  |[0m   

[36mcore-ui-playwright-server_1  |[0m       [90m   at [39mnode_modules\@playwright\test\lib\index.js:198

[36mcore-ui-playwright-server_1  |[0m   

[36mcore-ui-playwright-server_1  |[0m         196 |   }, use) => {

[36mcore-ui-playwright-server_1  |[0m         197 |     if (!['chromium', 'firefox', 'webkit'].includes(browserName)) throw new Error(`Unexpected browserName "${browserName}", must be one of "chromium", "firefox" or "webkit"`);

[36mcore-ui-playwright-server_1  |[0m       > 198 |     const browser = await playwright[browserName].launch();

[36mcore-ui-playwright-server_1  |[0m             |                                                   ^

[36mcore-ui-playwright-server_1  |[0m         199 |     await use(browser);

[36mcore-ui-playwright-server_1  |[0m         200 |     await browser.close();

[36mcore-ui-playwright-server_1  |[0m         201 |   }, {


});
```

Looks like we download the browser itself, but there is an issue with the installation,
In the case of using the Chrome channel - it downloaded and executed as well.

Also, the local installation works as well.

**Comment by mxschmitt** [comment]
Which Windows base image are you using?

**Comment by mxschmitt** [comment]
I tried the following, which was working only with `mcr.microsoft.com/dotnet/framework/sdk:4.8-20211012-windowsservercore-ltsc2022` and not with `mcr.microsoft.com/dotnet/framework/sdk:4.8-20211012-windowsservercore-ltsc2019`:

```txt
# Make fonts available:
curl -O https://raw.githubusercontent.com/gantrior/docker-chrome-windows/master/Files/FontsToAdd.tar
tar -xvf FontsToAdd.tar
powershell .\Add-Font.ps1 .\Fonts\

# Install Node.js
curl -O https://nodejs.org/dist/v18.15.0/node-v18.15.0-x86.msi
msiexec /i node-v18.15.0-x86.msi /qn
set PATH=%PATH%;C:\Program Files (x86)\nodejs

# Might take a few seconds since msiexec is non blocking, so Node.js will install in the background

# Create a new Playwright project (you can skip browser install here)
npm init playwright pwtest
cd pwtest
npx playwright install msedge

npx playwright screenshot --channel msedge http://example.com foo.png
```

I would recommend upgrading the Docker image to the one above. If upgrading is not possible, I can try following up with the Edge team about that issue. Would upgrading work for you?

Keep in mind that running it inside a minimal Docker image has a few downsides, like e.g. the fonts issue which I worked around above, also in Firefox/WebKit don't have access to SSL certificates inside the Docker container if its a minimal one.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks a lot for your attempts to reproduce the issue.

I'll try to check the possibility of upgrading the image, but it will require some time to work on it (it should go through the chaining of infra engineers from the relevant department), but I'll try.

If you have the option to handle this issue with the Edge team - it can be great!

Just to clarify - did you try to install with the image that we use and also got the issue with the Edge installation?

**Comment by mxschmitt** [comment]
> Just to clarify - did you try to install with the image that we use and also got the issue with the Edge installation?

Exactly. With mcr.microsoft.com/dotnet/framework/sdk:4.8-20211012-windowsservercore-ltsc2022 it was working but with mcr.microsoft.com/dotnet/framework/sdk:4.8-20211012-windowsservercore-ltsc2019 it was not.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks again for your investment in the investigation and attempts. 

Is it possible to check with the Edge team regarding this issue? Maybe they will have some idea about handling this issue and fixing it?

**Comment by mxschmitt** [comment]
> @mxschmitt 
> 
> Thanks again for your investment in the investigation and attempts. 
> 
> 
> 
> Is it possible to check with the Edge team regarding this issue? Maybe they will have some idea about handling this issue and fixing it? 

I pinged them internally about it.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks a lot! 
What we should do meantime? Besides waiting for the Edge team's response...

**Comment by mxschmitt** [comment]
You can try upgrading the Windows container image to 2022 instead of 2019.

**Comment by AlexKomanov** [comment]
@mxschmitt 
Thanks!
Will try to do it in our environment.

A question regarding the new labeling. 

Do you have some improvements for version 1.33 that will affect our issue?

**Comment by mxschmitt** [comment]
No but I assigned it to me and 1.33 is basically my current backlog since I'll take care of this issue.

**Comment by mxschmitt** [comment]
Edge teams response:

> Our guidance is usually to run Edge on a full Windows image, not a server core or nano image. It seems that the browser relies on certain win32 API calls that are not available on the core or nano images. I've also seen cases where it matters whether the administrator or a regular user is running the installer. 

Since this is not an issue on Playwright side and there is an easy to apply workaround available (upgrade the Windows Docker base image), I'm closing it for now.

**Comment by parameswaranj** [comment]
Thanks a lot  @mxschmitt !  Could you please share  if there is a github page for msedge browser ? We too face the same issue and would like to report it as a bug. Not sure if updating OS just for a browser install is a good resolution.
