### ISSUE TITLE
[BUG] I am trying to implement 'Multiple signed in roles' in my test suite but getting 'Error: ENOENT: no such file or directory, open 'playwright/.auth/teacher.json' error.

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#21513]
Problem Statement:

I have two users in my test cases and want to run e2e test cases without writing login steps in each tests using different user accounts.  So I followed 'https://playwright.dev/docs/auth#multiple-signed-in-roles' documentation but error mentioned below. 

Can anyone please help me with this?

### Source code

**Setup File:** 
```
auth.setup.ts:

import { test as setup} from '@playwright/test';

const teacherFile = 'playwright/.auth/teacher.json';

setup('authenticate as admin', async ({ page }) => {
  // Perform authentication steps. Replace these actions with your own.
  await page.goto('https://github.com/login');
  await page.getByLabel('Username or email address').fill('admin');
  await page.getByLabel('Password').fill('password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  // End of authentication steps.
  // End of authentication steps.

  await page.context().storageState({ path: teacherFile });
});

const studentFile = 'playwright/.auth/student.json';

setup('authenticate as user', async ({ page }) => {
  // Perform authentication steps. Replace these actions with your own.
  await page.goto('https://github.com/login');
  await page.getByLabel('Username or email address').fill('user');
  await page.getByLabel('Password').fill('password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  // End of authentication steps.

  await page.context().storageState({ path: studentFile });
});
```
**Test Case:** 
```
test.spec.ts:

import { test } from '@playwright/test';

test.use ({storageState:'playwright/.auth/teacher.json'})

test("expect to login into teacher account", async ({ page }) => {
    await page.locator("#setting").click();
    await page.locator("#curriculum").click();  
  });
  
   test.describe(() => {
    test.use({ storageState: 'playwright/.auth/student.json' });
  
    test('student test', async ({ page }) => {
      await page.locator(".sc-AxheI sc-pCOPB qSFrr").click();
    });
  });
```

**Error:**

```
Running 2 tests using 2 workers
  1) [chromium] › createapi.spec.js:13:5 › student test ============================================

    Error: ENOENT: no such file or directory, open 'playwright/.auth/student.json'



  2) [chromium] › createapi.spec.js:5:1 › expect to login into teacher account ================

    Error: ENOENT: no such file or directory, open 'playwright/.auth/teacher.json'
```

**Comment by DeeptiSaxena09** [comment]
Note: I have created 'auth.setup.ts' file inside 'tests' folder in my framework.

**Comment by mxschmitt** [comment]
How does your Playwright config look like? Most likely you don't include the auth setup there.

**Comment by DeeptiSaxena09** [comment]
@mxschmitt Below is the playwright.config.js file:

`// @ts-check
import { devices } from '@playwright/test';

export const config = {
  testDir: './tests',
  timeout: 50 * 1000, // 30 sec is the global timeout 
  expect: {
      timeout: 5000  //5sec is the assertion timeout.
    },
  fullyParallel: true,
  reporter: 'html',
  video: 'on',
  
  use: {
    //actionTimeout: 0,
    trace: 'on-first-retry',
    screenshot: 'on',
    headless: false,
    
    },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
};

export default config;
`

Could you please help me with adding auth setup in config?

**Comment by mxschmitt** [comment]
You need to have it like that:

```
projects: [
    {
      name: 'setup',
      testMatch: /auth.setup\.ts/,
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
      dependencies: ['setup'],
    },
  ],
```

see https://playwright.dev/docs/api/class-testproject#test-project-dependencies.

**Comment by DeeptiSaxena09** [comment]
@mxschmitt I have updated `playwright.config.js` file as per above code but after running my test, page is not loading with the signed state using cookies. 

`Playwright Config File: 

import { devices } from '@playwright/test';

export const config = {

  testDir: './tests',
  timeout: 50 * 1000, // 30 sec is the global timeout 
  expect: {
      timeout: 5000  //5sec is the assertion timeout.
    },
  fullyParallel: true,
  reporter: 'html',
  video: 'on',
  
  use: {
    //actionTimeout: 0,
    trace: 'on-first-retry',
    screenshot: 'on',
    headless: false,
    
    },

  projects: [
    { 
      name: 'setup', 
      testMatch: /auth.setup\.ts/,
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
      dependencies: ['setup'],
    },
  ],
};

export default config;
`


`test.spec.ts:

import { test } from '@playwright/test';


test("expect to login into teacher account", async ({ page }) => {
    await page.goto('https://leap-teacher.cuemath.com');
    await page.locator("#setting").click();
    await page.locator("#curriculum").click();  
  });
  `

**Comment by mxschmitt** [comment]
Is auth.setup.ts inside the tests directory? Having a repository would be helpful since having the configuration slightly misconfigured makes it not work.

**Comment by DeeptiSaxena09** [comment]
Also, I have tried by puting auth.setup.ts file inside 'tests' directory too and getting same error ('Error: ENOENT: no such file or directory, open 'playwright/.auth/teacher.json') and same behaviour when puting auth.setup.ts in the root directory as well. 

@mxschmitt

**Comment by DeeptiSaxena09** [comment]
Current location of auth.setup.auth is '/Users/deeptisaxena/Playwrightautomation/auth.setup.ts'.

**Comment by mxschmitt** [comment]
So the `auth.setup.ts` needs to be inside the tests directly otherwise it won't work.

Can you try the following instead?

```ts
    { 
      name: 'setup', 
      testMatch: /auth\.setup\.ts/,
    },
```
(dot is escaped differently there)

**Comment by DeeptiSaxena09** [comment]
@mxschmitt So updated and tried below:

Intially added ' playwright/.auth'  directory by:

```
mkdir -p playwright/.auth
echo "\nplaywright/.auth" >> .gitignore
```


Then added 'auth.setup.ts' file to 'tests' folder which is containing below code:

```
// auth.setup.ts: 
import { test as setup} from '@playwright/test';

const teacherFile = 'playwright/.auth/teacher.json';

setup('authenticate as teacher', async ({ page }) => {
 await page.goto('https://github.com/login');
  await page.getByLabel('Username or email address').fill('admin');
  await page.getByLabel('Password').fill('password');
  await page.getByRole('button', { name: 'Sign in' }).click();
  await page.context().storageState({ path: teacherFile });
});
```

Then updated 'playwright.config.ts' with below code:

```
//playwright.config.js:
import { devices } from '@playwright/test';

export const config = {

  testDir: './tests',
  timeout: 50 * 1000, // 30 sec is the global timeout 
  expect: {
      timeout: 5000  //5sec is the assertion timeout.
    },
  fullyParallel: true,
  reporter: 'html',
  video: 'on',
  
  use: {
    trace: 'on-first-retry',
    screenshot: 'on',
    headless: false,
    
    },

  projects: [
    { 
      name: 'setup', 
      testMatch: /auth\.setup\.ts/,
    },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
      dependencies: ['setup'],
    },
  ],
};

export default config;
```
And run the below test file:

```
// test.spec.ts:
import { test } from '@playwright/test';
test.use ({storageState: 'playwright/.auth/teacher.json' });
test("expect to login into teacher account", async ({ page }) => {
 await page.goto('https://github.com/login');
  });
  
```

And got the same error message:

**Comment by mxschmitt** [comment]
Can you provide us your code in a small Git repo? This would help a ton!

**Comment by DeeptiSaxena09** [comment]
@mxschmitt Please refer to https://github.com/Deepti-Saxena09/e2e repo as per your request.

Currently two workers are running firstly as per 'auth.setup.ts' and storing the 'cookies' and 'origins' in the respective '.json' files and then 'login.spec.ts' tests are running. 

But, those 2 tests which are under 'logintest.spec.ts' file are not using the saved storage as per 'auth.setup.ts', i.e they are navigating to page where user needs to signin.

**Comment by DeeptiSaxena09** [comment]
Hi @mxschmitt any update?

**Comment by DeeptiSaxena09** [comment]
Any Update?

**Comment by DeeptiSaxena09** [comment]
@mxschmitt

**Comment by mxschmitt** [comment]
GitHub usually asks for two-factor authentication by email or SMS, thats most likely whats happening in your case. This happened for me. You can verify that by running the tests via `npx playwright test --trace=on` and then `npx playwright show-report` click on your setup file, open the trace and verify that you were not fully logged in.

Could you try that to ensure you are / or not logged in?

You also might have to wait for an element if they login is more of an async operation and not just clicking the button.

**Comment by DeeptiSaxena09** [comment]
@mxschitt  The issue in my repo was with the 'timeout', When i added 1 sec delay in 'setup.auth.ts' file before storing 'storageState' in the dedicated '.json' file, then 'auth.json' file was having all the required set of cookies into the same and hence it used all the required cookies in the browser context.

I will implement 'npx playwright test --trace=on' to check I am not fully logged in. 

Thanks Max for the constant support, quick replies and complete help to get this test done, really appreciate this. Major learning for me. 

FYI, Closing this ticket.

**Comment by amarose** [comment]
Hi,
I faced a similar problem and the issue was that I put auth.setup.ts in the root path. The documentation does not mention that it has to be under the tests folder. My little request - please update it, as it can save a lot of debugging time :D
