### ISSUE TITLE
[Feature] [Docs] Documentation of comparison with Selenium, Cypress, etc.

### ISSUE THREAD

**Issue by sachinjoseph** [microsoft/playwright#2151]
Documenting this will help users choose the right framework more easily.

**Comment by celeryclub** [comment]
In the meantime, this exists. https://github.com/software-platform/web_test_infra

**Comment by pavelfeldman** [comment]
If @Writhe will keep it up-to-date, link above would work. Couple of notes though:
- It seems like it is based on an early snapshot of Playwright and today we have [v1.0](https://www.npmjs.com/package/playwright), with the [docs](https://playwright.dev), Yarn works, etc etc.

- It does not actually list capabilities today. Playwright has much, much more capabilities than the rest of the bunch. We'd like to make sure comparison is unbiased though and does not come from us. I'm happy to provide / edit the list of capabilities if someone starts it. Things like
  - real handling of downloads,
  - web workers
  - http routing across pages and popups
  - out-of-process iframes where you can log into real google auth
  - cross-process navigations in all browsers
  - context-wide emulation
  - built-in shadow dom piercing
  - ... this list can go on and on, nothing comes close to this list.

**Comment by bootstraponline** [comment]
I am happy to accept pull requests to the web_test_infra repo. 🙂

**Comment by aslushnikov** [comment]
> Documenting this will help users choose the right framework more easily.

@sachinjoseph Fair, but all comparisons here would be inherently biased, so we'd rather avoid them.

**Comment by sachinjoseph** [comment]
IMHO, that's not a good reason not to document a comparison of key capabilities/architectural differences/design choices. Also, even if it starts biased, it doesn't have to remain biased, and that's one of the great things I love about open source: the community can help us be lesser and lesser biased as time progresses. :-)
