### ISSUE TITLE
Looping is not working inside recursive function

### ISSUE THREAD

**Issue by JeevanHB** [microsoft/playwright#21514]
//Function to wait for invisibility jivaspace lock banner in import screen
        this.waitForJivaspaceLockToBeInvisibleImportScreen = async function () {
            // jivaTesting.logTestStep('Wait for invisibility of jivaspace lock banner');
            var jivaspaceLockCounter = 0;
            // var EC = protractor.ExpectedConditions;
            var jivasapceLockImportScreenLoc = this.jivasapceLockImportScreenLoc;
            (async function checkForJivaspaceLockInvisibility() {
               await getPage().locator(jivasapceLockImportScreenLoc).isVisible().then(async function (present) {
                                    if (present) {
                                        
                      console.log("lock result " +jivaspaceLockCounter)
                                        await getPage().waitForTimeout(1000);
                                        jivaspaceLockCounter++;
                                        await checkForJivaspaceLockInvisibility();
                                    }
                                    else {
                                        console.log("Exported in " + jivaspaceLockCounter + " Seconds");
                                        return;
                                    }
                                },
                                    function (err) {
                                        console.log("Jivaspace is not locked");
                                    });
            }());
        };
Observing issue while using recursive loop in a function.
We written above function in page file. calling it in main test file,
Once "await getPage().locator(jivasapceLockImportScreenLoc).isVisible().then(async function (present)" this line execute it is not going to if loop. It is executing next line preset in main test file. Then it is coming to if loop.
Please guide us to resolve this issue.

Refer below screen shots
![loopingPlaywright](https://user-images.githubusercontent.com/52357464/223975461-97ee32c3-25f1-4a44-a46a-891c351e5d81.png)

![image](https://user-images.githubusercontent.com/52357464/223959788-e574c1e1-6233-4f10-9c28-7c5890524f48.png)

What function we can use to wait until page to load in browser?
Any other function except page.selectlocator() funtion, waitfortimeout

**Comment by mxschmitt** [comment]
Please re-file with a minimal reproducible and follow the bug template. Most likely this is an issue in your code. I see e.g. the getPage() method which is against Playwright's best practices that a test should not have global state.
