### ISSUE TITLE
[BUG] Typescript error when using parameterized projects

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#21519]
### System info
- Playwright Version: [v1.31.2]

### Source code
I am having trouble with TS errors when trying to use parameterized projects following the the [official documentation](https://playwright.dev/docs/test-parameterize#parameterized-projects)

**Config file**

```js
import type { defineConfig } from '@playwright/test';
import { TestOptions } from './my-test';

export default defineConfig({
    projects: [
        {
            name: 'alice',
            use: { person: 'Alice' },
        }
    ]
});
```

**Test file (self-contained)**

```js
// my-test.ts
import { test as base } from '@playwright/test';

export type TestOptions = {
  person: string;
};

export const test = base.extend<TestOptions>({
  // Define an option and provide a default value.
  // We can later override it in the config.
  person: ['John', { option: true }],
});
```

```js
// example.spec.ts
import { test } from './my-test';

test('test 1', async ({ person }) => {
console.log(person)
});
```

**Steps**

1. Open `playwright.config.ts`  and  notice the TypeScript error on `defineConfig` :
`TS1361: 'defineConfig' cannot be used as a value because it was imported using 'import type'.`

2. Run the test and notice the following error:
`ReferenceError: defineConfig is not defined`

3. Looking at other examples of Playwright documentation, it seems like that using the keyword `type` in the imports in `playwright.config.ts` is not necessary, so I remove that.
4. Now there is another TS error in `playwright.config.ts` on `person: 'Alice'`:
```
No overload matches this call.
  Overload 1 of 3, '(config: PlaywrightTestConfig<{}, {}>): PlaywrightTestConfig<{}, {}>', gave the following error.
    Type '{ person: string; }' is not assignable to type 'UseOptions<PlaywrightTestOptions & CustomProperties<{}>, PlaywrightWorkerOptions & CustomProperties<{}>>'.
      Object literal may only specify known properties, and 'person' does not exist in type 'UseOptions<PlaywrightTestOptions & CustomProperties<{}>, PlaywrightWorkerOptions & CustomProperties<{}>>'.
  Overload 2 of 3, '(config: PlaywrightTestConfig<unknown, {}>): PlaywrightTestConfig<unknown, {}>', gave the following error.
    Type '{ person: string; }' is not assignable to type 'UseOptions<PlaywrightTestOptions & CustomProperties<unknown>, PlaywrightWorkerOptions & CustomProperties<{}>>'.
      Object literal may only specify known properties, and 'person' does not exist in type 'UseOptions<PlaywrightTestOptions & CustomProperties<unknown>, PlaywrightWorkerOptions & CustomProperties<{}>>'.
  Overload 3 of 3, '(config: PlaywrightTestConfig<unknown, unknown>): PlaywrightTestConfig<unknown, unknown>', gave the following error.
    Type '{ person: string; }' is not assignable to type 'UseOptions<PlaywrightTestOptions & CustomProperties<unknown>, PlaywrightWorkerOptions & CustomProperties<unknown>>'.

```
5. Try running the test again and notice that the parameterization is working, despite error in step 4.

**Comment by mxschmitt** [comment]
`import type { defineConfig } from '@playwright/test';`
should be:
`import { defineConfig } from '@playwright/test';`

and
`export default defineConfig({`
should be
`export default defineConfig<TestOptions>({`

I created https://github.com/microsoft/playwright/pull/21523 to address this.

**Comment by irharrier2** [comment]
Yeah, that solved it. 

Maybe it is worth to add an example for primary types like this as well 
`export default defineConfig<{myString: string}>
`

**Comment by mxschmitt** [comment]
👍 I fixed the broken snippets which should make it more clear.
