### ISSUE TITLE
In Playwright Sinle Page App wouldn't rendered correctly

### ISSUE THREAD

**Issue by Petroglyphe** [microsoft/playwright#21516]
I test a single page app with Playwright. Now I have Playwright updated to version 1.31.2. After that the View of the app wouldn't rendered correctly. The inner views are shifted down. I have tested many view and context options. But nothing works for me. Can anyone help? Thank you.
![singlepage](https://user-images.githubusercontent.com/127383635/223971499-4ef28863-405a-4238-93fe-0fb407763029.JPG)

**Comment by mxschmitt** [comment]
Which browser is this? Can you share a reproduction which we can run locally to reproduce it? In which Playwright version did it start happening?

**Comment by Petroglyphe** [comment]
I can't share a reproduction. The Application is a Product of my company and underlies obligation of confidential futhermore I have no request to the source code.
With playwright version 1.27.1 it works. After update to 1.31.2 this failure appear. I've tried it with Chrome and Edge
Versions:
playwright 1.32.2
Chrome   111.0.5563.65
Edge   110..0.1587.63
Node   16.13.0

**Comment by Petroglyphe** [comment]
In playwright version 1.29.2 I had the the same failure. The  I made a workaround und set the viewport to null. This is in 1.31.2 not possible.
this.context=await this.browser.newContext({
               viewport:null
            })

**Comment by mxschmitt** [comment]
If you are not able to share a reproduction we cannot act on it unfortunately!

**Comment by Petroglyphe** [comment]
Today I have used webkit and it works.
Tomorrow I will contact the development and ask for little application with the same behavior.

**Comment by Petroglyphe** [comment]
I think it's a failure in chromium browser binary.
I stop testing with playwright

**Comment by Petroglyphe** [comment]
Hallo Herr Schmitt,


da ich inzwischen festgestellt habe, dass Sie deutsch verstehen, wechsele ich nun auch zu dieser Sprache.
Zuerst einmal vielen Dank für Ihre Bemühungen. 
Leider kann ich keinen Sourcecode weitergeben. Wir verwenden hier ein ganzes, eigenes Framework das ich nicht weitergeben darf.
Dieses Framework verwendet ExtJS 3. Davon habe ich keine Ahnung und so kann ich auch keinen eigenen Code schreiben.
Zum Abschluss noch eine Sache die feststellen konnte.
Wird Chromium verwendet, bricht die Videoaufzeichnung nach dem Klick auf den Anmeldebutton ab. Mit Webkit, kann der ganze Test aufgezeichnet werden. Möglicherweise wird hier ein Ereignis nicht abgefangen.


Trotz allem


Vielen Dank und Viele Grüße,






---

Manfred Schneider
Test

 

Tribe Technologies GmbH
Lurgiallee 12
60439 Frankfurt am Main

 

Tel.:      +49 (69) 24
 750 56 - 701
Fax:      +49 (69) 24 750 56 - 100









***@***.***






www.tribetech.de

Unsere Hinweise zum Datenschutz finden Sie hier: www.tribetech.de/datenschutz

 

Sitz und Amtsgericht: Frankfurt am Main, HRB 47890
Geschäftsführer: Dirk Bunar, Axel Reddehase






Von: Max Schmitt ***@***.***>
Gesendet: Sonntag, 12. März 2023 10:27:44
An: microsoft/playwright
Cc: Schneider, Manfred; Comment
Betreff: Re: [microsoft/playwright] In Playwright Sinle Page App wouldn't rendered correctly (Issue #21516)
 



If you are not able to share a reproduction we cannot act on it unfortunately!
—
Reply to this email directly, 
view it on GitHub, or 
unsubscribe.
You are receiving this because you commented.Message
 ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/microsoft/playwright/issues/21516#issuecomment-1465137746",
"url": "https://github.com/microsoft/playwright/issues/21516#issuecomment-1465137746",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
