### ISSUE TITLE
[BUG]: Playwright execution performance - high CPU usage

### ISSUE THREAD

**Issue by TestTheTest7** [microsoft/playwright#21530]
**Context:**
- Playwright Version: **1.28.0**
- Operating System: **Mac OS Monterey (Apple M1, 16GB)**
- Python: **3.9.6**
- Browsers: **All (Chromium, Firefox, WebKit)**
- Extra: 

1. **pytest-xdist==1.29.0** for running tests
2. **pytest fixures** are used
`@pytest.fixture(scope="function")` -> on the scope level browser context and page are created and the page is used through test, at the end of scope(in this case at the end of test) the context and the browser are closed (also tried with scope="`session`" but had too many problems in the case when I have many scenarios(>50))

**Describe the bug**

The problem is high CPU usage while tests running on my local machine (details described above). If I have for example 2 tests and run them with 2 workers, CPU usage becomes high (up to 50-70%) at some moment which is very high and unacceptable if we take into account that execution times are not too long and also these tests are some of the simpler ones I have.

### Source code
https://github.com/TestTheTest7/pw_project 

**Some facts:** 

- the same behaviour for any number of workers (>1)
- the same behaviour for all browser types
- please see CPU usage
<img width="1113" alt="Screenshot 2023-03-09 at 15 32 54 png 2023-03-09 15-33-50" src="https://user-images.githubusercontent.com/126164388/224056856-70381db8-ff2f-43f6-914b-f5b045c9edb6.png">

**Notes**:
- this project is a prototype of a big project, some things in this project don't make sense e.g. here I have some methods that override playwright's methods cause in the original project they are extended and they contain other things
- here I have two tests (playwright_test_1.py and playwright_test_2.py) with the same steps for CPU testing purposes
-  these tests are some of the simpler ones I have in the original project

**Comment by mxschmitt** [comment]
Without running the code locally I saw that you create a Playwright instance for each test which is a very expensive operation. That would explain it. So you should only create a Playwright instance (`with sync_playwright()`) once, a browser once and create a context per each test (which is fast!).

Our official Pytest plugin does this out of the box for you see [here](https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py) and [here](https://playwright.dev/python/docs/test-runners) for docs. Otherwise we recommend to get inspired by the [fixtures it has](https://github.com/microsoft/playwright-pytest/blob/main/pytest_playwright/pytest_playwright.py) and copy / adjust them for your needs.

**Comment by TestTheTest7** [comment]
Thank for the tips, will fix this and come back with results, can the label stay in 'triaging' until I change it please?

**Comment by TestTheTest7** [comment]
I just added changes -> https://github.com/TestTheTest7/pw_project/pull/1/files
My conftest now (I create pw instance and browser on `session` level, then context and page on `function` level):
```
import pytest
from page.webpage import WebPage
from playwright.sync_api import ViewportSize
from browser import Browser, Browsers
from playwright.sync_api import (
    Browser as PW_Browser,
    BrowserContext,
    Playwright,
    sync_playwright,
)

# pylint: disable=redefined-outer-name


@pytest.fixture(scope="session")
def playwright():
    pw = sync_playwright().start()
    yield pw
    pw.stop()


@pytest.fixture(scope="session")
def browser(playwright: Playwright):
    browser_config = Browser("chrome")
    browser_name = browser_config.capabilities["browserName"]

    if browser_name == Browsers.CHROME:
        browser = playwright.chromium.launch(headless=False)
    elif browser_name == Browsers.FIREFOX:
        browser = playwright.firefox.launch()
    elif browser_name == Browsers.SAFARI:
        browser = playwright.webkit.launch()
    else:
        browser = None

    yield browser

    browser.close()


@pytest.fixture(scope="function")
def browser_context(browser: PW_Browser):
    browser_config = Browser("chrome")
    viewport_width = browser_config.screen_width
    viewport_height = browser_config.screen_height

    # Get browser context
    # Should add user agent explicitly cause without defining page cannot be fully loaded in Chrome headless
    browser_context = browser.new_context(
        viewport=ViewportSize(width=viewport_width, height=viewport_height),
        user_agent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36",
        )

    yield browser_context

    browser_context.close()


@pytest.fixture(scope="function")
def page(browser_context: BrowserContext):
    page = browser_context.new_page()

    playwright_page = WebPage(page._impl_obj)
    playwright_page.navigate("https://www.kiwi.com/en/")

    yield playwright_page


@pytest.fixture(autouse=True)
def test_wrapper(page: WebPage):

    # CALL TEST SCENARIO
    yield
```

Behaviour: after few running high CPU usage is still there
<img width="1109" alt="Screenshot 2023-03-10 at 12 41 39 png 2023-03-10 13-37-02" src="https://user-images.githubusercontent.com/126164388/224319572-6338a822-0ccc-405b-9bac-c53d33616a38.png">

**Comment by TestTheTest7** [comment]
Which behaviour(cpu and memory usage) is acceptable for you, also did the changes as you did (https://github.com/TestTheTest7/pw_project/pull/1/commits/94fcc0d17ed2393ac23d2660a6ccbbc4d1350d19) and could you please take a look on https://recordit.co/QYChODfHjU

**Comment by mxschmitt** [comment]
Maybe you can try upgrading Python? I use 3.11 and had in average a CPU usage on the Python process of 2%, peak was 4% on my M1 Mac. What is acceptable for you?

**Comment by mxschmitt** [comment]
I also see that you are running "Intel Python" and not AppleSilicon Python on your machine. This means the Python gets emulated via Rosetta which makes it always more CPU intense.

So action item on your side is to uninstall Python and install a more recent Python version which ships universal binaries by default.

**Comment by TestTheTest7** [comment]
Does it make a difference to completely uninstalling and installing a more recent Python from using pyenv (just asking)? I changed version to 3.11.1 by using pyenv and I'm noticing it behaves better but sometimes my peak is 36%

**Comment by TestTheTest7** [comment]
In case when mentioned peak happens, it always happens at the end

**Comment by mxschmitt** [comment]
It should not make a difference, 3.11.1 is much likely Apple Silicon now instead of Intel. You can verify it in the Activity Monitor:

<img width="908" alt="image" src="https://user-images.githubusercontent.com/17984549/224995062-bfccdb57-6973-4220-af3a-6f0e485e9d31.png">

Much better! That looks expected now, if e.g. your site does a lot of network requests that could totally end up in a short peak of 30%. Launching browsers is an expensive operation.

**Comment by TestTheTest7** [comment]
It looks like [this](https://recordit.co/bzHKE12lcf) now, hope many scenarios (I have approx. 60 tests per run on GCP) will work fine in this way cause I'm concerned how these will behave

**Comment by mxschmitt** [comment]
You still have the wrong Python version installed btw. It should be Apple and not Intel. If you have many tests, this won't change much, since you have a static amount of concurrency configured, e.g. 2 or 4 in parallel.

I'm closing it for now since from our side this looks not like an issue with Playwright and more like its expected.

**Comment by TestTheTest7** [comment]
one more question if possible @mxschmitt

when you wrote 'since you have a static amount of concurrency configured, e.g. 2 or 4 in parallel.' I'm wondering what's about 8 in parallel, should be there the same behaviour or I can expect some discrepancies?

**Comment by maxrexfax** [comment]
![ksnip_20231226-171413](https://github.com/microsoft/playwright/assets/27776358/06d5dbce-504b-47d6-8571-ce3911a407dd)
![ksnip_20231226-171353](https://github.com/microsoft/playwright/assets/27776358/d762f82a-74a8-472a-9523-60ea8da65a37)
Every start of playwright tests causes 100% CPU load. Is it fault of some media on target site or something else?
