### ISSUE TITLE
[Feature] Add a waitForResponse with a string | RegExp predicate parameter as well as Response one

### ISSUE THREAD

**Issue by TomasHubelbauer** [microsoft/playwright#21539]
Hi, currently, we have `waitForResponse` which can easily be used with a URL string or a regex like so:

```typescript
await page.waitForResponse(/\/rest\/v1\/template\?select=/);
```

This method has an overload which also allows matching values of the fields on the `Response` object directly allowing to check for stuff that's outside of the URL, such as the request method:

```typescript
await page.waitForResponse(
  (response) =>
    response.request().method() === 'GET' &&
    /\/rest\/v1\/template\?select=/.test(response.url())
);
```

I think it would be beneficial to add a new overload which accepts either a string or a `RegExp` instance that operates on the URL of the response, like the first overload I already mentioned in this issue, but then accepts another predicate which operates on the `Response` object itself.

It could be used to check for a very common (IMO) case of testing whether a POST call to a certain UR has finished yet without getting a false positive from a GET call to the same URL finishing during that window.

This can happen whenever in a CRUD area of the app being tested, a form exists to create or update an entity via a POST call, but there is also a background refresh process which refreshes some list by GETting the same URL.

Just checking the URL in that case is not enough, because there is a race condition where the test might incorrectly pass the `waitForResponse` step through the background refresh call not the form submission call and the remainder of the test logic runs prematurely since the POST is not finished yet so stuff like "does the list now contain the new item" won't work since the list is still showing the previous items and the new item has not been created yet.

The new overload could look something like this:

```typescript
await page.waitForResponse(/\/rest\/v1\/template\?select=/, response => response.request().method() === 'GET');
```

WDYT?

**Comment by mxschmitt** [comment]
Since there is a workaround which is more readable and easier to follow in my opinion, I think that fits for your needs! If you still want such a method, we recommend extracting it into a small re-usable function.
