### ISSUE TITLE
[BUG] Webkit Browser Cannot Load Azure B2C Login Page

### ISSUE THREAD

**Issue by racbcsv** [microsoft/playwright#21534]
### System info
- Playwright Version:    "@playwright/test": "^1.31.2"
- Operating System: [Windows 10.]
- Browser: [WebKit]

### Source code

- [X ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// browser.test.ts
import { test } from "@playwright/test";

test("test browser", async ({ page }) => {
  // point this to wherever you want
  await page.goto("http://localhost:4200/");

  // keep browser open
  await page.pause();
});

```

```

**Steps**
- Run command: npx playwright test --headed --browser=webkit
- [...]

**Expected**

[Describe expected behavior]

**Actual**
![image](https://user-images.githubusercontent.com/108359768/224100947-6b557ef0-d1a1-4c20-8567-76edef5343fd.png)

[Describe actual behavior]

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally? Otherwise we are not able to act on it. Maybe there are errors in the JavaScript console?

**Comment by mxschmitt** [comment]
Closing as part of the triage process, feel free to re-file with more information and a reproduction.
