### ISSUE TITLE
UI mode feedback

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#21541]
- [x] starting all tests and then stopping them right away results in a **stuck spinning ui**
- [x] open/close starts tests
- [x] filter visible test list is wrong
- [x] add padding to xterm
- [x] horizontal line with timestamp
- [x] filter "failed only"
- [x] inline expect error into actions list
- [x] invisible line number on the current line in source
- [x] show me some progress indicator when I run 3000 tests
- [ ] ~clicking in the dock opens a new browser window~
- [x] when testing has started, should reset test indicators to "enqueued"
- [ ] xterm is very slow
- [ ] ~xterm should align to bottom, not top (see by resizing the drawer)~
- [x] xterm buffer is capped?
- [x] skipped test is rendered as failed
- [ ] ~when I edit filters, my currently selected item is not scrolled into view~
- [x] status bar always shows "Running", even when finished
- [x] explicitly watch files / tests
- [x] reveal first failure after test run
- [x] show snapshot from the previous action, when one is not available, e.g. in expect.toBe

**Comment by Calyhre** [comment]
> ~~[ ] clicking in the dock opens a new browser window~~

Hey folks 👋 Any idea why this one was not done? I have the issue constantly when going back to Playwright from the Dock
