### ISSUE TITLE
[BUG] Why I need the increase timeouts?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#21540]
Model Name:	MacBook Pro
  Chip:	Apple M1
  Total Number of Cores:8 (4 performance and 4 efficiency)
  Memory:	16 GB

npm script;
`"pw:stage": "npx playwright test --project=chrome",`

My test works with 4 workers for 120 case.Playwright.config.ts as below;

```
import { devices, type PlaywrightTestConfig } from "@playwright/test";
import { configEnv } from './config/config'

const config: PlaywrightTestConfig = {
  globalTeardown: './global-teardown.ts',
  retries: 2,
  timeout: 60 * 1000,
  expect: {
    timeout: 20 * 1000
  },
  reporter: [['html', { outputFolder: 'report' }]],
  use: {
    headless: true,
    baseURL: configEnv.baseURL,
    actionTimeout: 20 * 1000,
    trace: 'retain-on-failure',
    navigationTimeout: 20 * 1000,
    ignoreHTTPSErrors: true
  },
  projects: [
    {
      name: 'setup',
      testMatch: /setup\.ts/,
    },
    {
      
      name: "chrome",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],

        },
      },
      dependencies: ['setup'],
    },
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],

        },
      },
    },
    {
      name: 'webkit',
      use: {
        ...devices["Desktop Webkit"],
        launchOptions: {
          args: ["--disable-web-security", "--window-position=0,0"],
        },
      },
    },
  ],
};
export default config;

```

I don't understand the logic of timeouts, especially the expect timeout. Even 20 seconds is a very long time for each test case to be expected separately. Because it already expects in 20 seconds. If it fails to expect, it waits for 20 seconds and throws an error. Actually, I don't think it waits for the duration of expect in parallel for all test cases separately.

According to document, I understood that the expect timeout works for each test case.Am I right? But when I use above config generally taking 5 failed case in the report .But if I increase the **timeout** and **expect timeout** higher as below I don t take any error;

```
  timeout: 10 * 60 * 1000,
  expect: {
    timeout: 60 * 1000
  },
```

But these timeouts is very high. How they working according to workers in parallel.Is there any problem with my config or is there a bug?

I use expect in many places in the project. Especially when checking whether some elements are visible or not. To give an example, the following example summarizes the expects I use in the general project.

 **await expect(page.locator(".alert-success")).toBeVisible()**

**Comment by mxschmitt** [comment]
I recommend removing `actionTimeout`, it has a default of `0` which is the recommended value. Since test timeout will cancel pending Playwright calls anyways. Thats most likely the reason why its miss-behaving in your scenario.

Having an expect timeout of 20 seconds and a reasonable much higher test timeout (aka. just `timeout`) sounds good. And regarding expect timeout, its per each expect() statement. So we recommend there something between 5 and 20 seconds.

**Comment by YusufOzt** [comment]
Same error goes @mxschmitt  low timeout give error ,upper timeouts pass the test. Do you have an extra suggestion ?

**Comment by mxschmitt** [comment]
These `["--disable-web-security", "--window-position=0,0"],` args have no affect on Firefox and WebKit since they don't support these arguments, this is not related most likely.

Can you provide us the error you are getting? This helps us to understand which timeout does exceed in the first place.

**Comment by YusufOzt** [comment]
@mxschmitt thanks for response . I m not on the PC , writing on mobile.  But each error related to expect timeout exceed. Today I will try to use soft expect, maybe something can be change

**Comment by mxschmitt** [comment]
Why is increasing the expect timeout an issue for you? Needing a higher expect timeout can be required due to numerous reasons. Depending on the customers needs, we recommend increasing it. To name a few, your tests interact with elements which take a long time to appear or the hardware you are running on has low specs and browsers need a long time to render.

**Comment by YusufOzt** [comment]
@mxschmitt it is not problem increasing timeout . But sometimes some tests is being flaky and test total being about 12 minute for 120 case . Because of this I want to learn that maybe I m doing something wrong in config . I guess there is no problem except actiontimeout

**Comment by mxschmitt** [comment]
Since we don't have access to your repo, its hard to reason about it. Generally speaking, make sure to not use video, screenshot or trace with 'on' setting, and have trace only with 'on-first-retry' enabled. Also you can use trace to see timing information about a test, which expect takes long, etc.

**Comment by YusufOzt** [comment]
@mxschmitt Thank you very much, it was very useful information.Closing

**Comment by YusufOzt** [comment]
@mxschmitt Apart from what we talked about, there is something else I want to know, I forgot to ask. If I use soft assertion in the project, does the soft assertion wait for all the expect timeout when a test flaky or does it just throw an error without waiting? Because if it gives an error without waiting for the whole expect timeout, I will prefer to use soft assertion in the all project

**Comment by YusufOzt** [comment]
@mxschmitt thanks understood
