### ISSUE TITLE
[Feature] Programmatic retries via testInfo.retry()

### ISSUE THREAD

**Issue by echenley** [microsoft/playwright#21548]
### Issue

In our test suite, we collect coverage using a modified version of https://github.com/mxschmitt/playwright-test-coverage. However, we sometimes experience test flake due to browser memory overflow or other unforseen errors. In these cases, it would be nice if we could catch the error and programmatically queue up a retry for that specific test, without having to add retries to all other tests. This would enable us to keep test runs lean and performant while handling errors in a responsible way.

### Proposal

Add a `retry()` method to `testInfo`, which queues up a retry for that test regardless of the `retries` setting in playwright.config.js.

**Comment by mxschmitt** [comment]
Are you sure its a browser memory issue and not a Node.js memory issue? We recently fixed an issue which was about Node.js memory leak in evaluate, you can test in [Canary](https://playwright.dev/docs/canary-releases).

**Comment by mxschmitt** [comment]
Closing for now, please re-file with a repro.
