### ISSUE TITLE
[BUG] screenshot：The picture cut by scrolling is missing elements

### ISSUE THREAD

**Issue by Teresajw** [microsoft/playwright#21553]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

**Code**
 page.screenshot(path=Path.cwd().parent / f"images/{page.title()}_screenshot.png", full_page=True)
**Sence**
![image](https://user-images.githubusercontent.com/39899297/224211306-37e7cdc2-10c0-4cca-9241-15178abc0664.png)

[Describe expected behavior]
When I use the scrolling screenshot to take a screenshot of a long page, the page contains pictures. After the screenshot is completed, the relevant pictures in the page are missing, and the circle pattern being loaded is displayed. I try to set the waiting time, but it doesn't work. I want to ask whether there is a way to wait for the page elements to be loaded completely before scrolling the screenshot？

**Comment by mxschmitt** [comment]
Its not possible to wait until all the pictures are loaded, if they are lazily loaded, then you could scroll to the end and then wait for networkidle which might work. If you are able to share a repro we can take a look and find a solution for your use-case.

**Comment by Teresajw** [comment]
> 不可能等到所有图片都加载完毕，如果它们是延迟加载的，那么您可以滚动到末尾，然后等待 networkidle，这可能会起作用。如果您能够共享复制品，我们可以查看并找到适合您的用例的解决方案。

**Code:**
async def shot_by_bytes_async(url, full_page=True):
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()
        await page.goto(url, wait_until="networkidle")
        await page.mouse.wheel(0, 10000)
        screenshot_bytes = await page.screenshot(full_page=full_page)
        await browser.close()
        return screenshot_bytes

**Question:**
Thank you for your reply! The picture of the page is delayed loading. Only when you scroll to the picture position can you request to load the picture

But I have two questions to ask you:

1. This method page. mouse. wheel() directly clicks the mouse to scroll to a certain position. There is still a sliding process. It seems that I haven't found a sliding method, or there can be a method to change the rolling speed

2. page. screenshot (full_page=True). This method is the meaning of the screenshot of the whole page. What is its logic and the way of scrolling

**Comment by mxschmitt** [comment]
Can you share a repro of your site which you are trying to make a screenshot of? Then we can help you creating a script. Without knowing to the site this is unfortunately not possible.

**Comment by Teresajw** [comment]
> Can you share a repro of your site which you are trying to make a screenshot of? Then we can help you creating a script. Without knowing to the site this is unfortunately not possible.

Hello! You can use this url,thank you.

https://mp.weixin.qq.com/s?__biz=MzIwNDkyNzY2NQ==&mid=2247507764&idx=2&sn=e903a498d02cc2066dfbe170ec97dc4f&chksm=973a38eaa04db1fc3cb405d22b066c81ff809f9b54b11abc535528b405a5cc926cb3a46f5ba9#rd

**Comment by mxschmitt** [comment]
So I'd probably recommend to [loop over all the images on the page](https://playwright.dev/docs/locators#rare-use-cases), call [scroll into view](https://playwright.dev/docs/api/class-locator#locator-scroll-into-view-if-needed), make sure that they are [loaded](https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/complete) or wait for the `load` event on the img element to fire and in the end take the screenshot.

Since this is not an end-to-end testing feature request / bug report, I have to close this issue for now.

**Comment by Teresajw** [comment]
thank you, i'll try
