### ISSUE TITLE
[BUG] Playwright No Tests Found in VS Code - Windows 11

### ISSUE THREAD

**Issue by TheGrimler** [microsoft/playwright#21555]
Checked for duplicate but all other issues with this error have been closed with no resolution. 
Whenever I attempt to run a test using "npx playwright test .\practiceTests\FirstTest.js"  an error is given that no tests are found. 
The test directory and file location have been verified and is correct. The file doesn't even appear in the testing folder, however when looking in my C drive files, the files exist. 
If I attempt to create a test file with "xxx.spec.js" it still doesn't find it. If the ".spec" is added, it at least appears in the testing menu with the play buttons and I can run from there, but the tests fail immediately with a browser closed error. 

### System info
- Playwright Version: v. 1.6.2
- Operating System: Windows 11
- Browser: All
- Other info:
new installation of playwright

### Source code
Code used
![image](https://user-images.githubusercontent.com/44308197/224229811-d3d89c1a-5867-40ed-8b41-1748796c225d.png)

Correct testDir in config file
![image](https://user-images.githubusercontent.com/44308197/224230453-a8b282e2-bf7b-40a6-8441-0697a9adf3c9.png)

Error:
![image](https://user-images.githubusercontent.com/44308197/224230512-8925ab78-4409-4214-be3c-eb594bf98b2d.png)

Test only appears in Testing section of VS code if the ".spec" is added to the file name
![image](https://user-images.githubusercontent.com/44308197/224232098-f1dc706e-ef1f-4c6f-b000-04c21aee01e8.png)

**Expected**

The files are in the correct location, the correct file path is being used so the tests should be found. 

**Actual**

Error given that no test files found

**Comment by dd-jonas** [comment]
Can't help you with everything, but I can tell you at least that the `spec.ts` extension is necessary as the docs state: "By default, Playwright Test runs .*(test|spec)\.(js|ts|mjs) files." (`testMatch` option).

**Comment by Avol-V** [comment]
Playwright Tests extension for VS Code has lost tests and does not find me either. On Linux, before that, the tests were found normally.
`node -e 'try { const pwtIndex = require.resolve("@playwright/test"); const version = require("@playwright/test/package.json").version; console.log(JSON.stringify({ pwtIndex, version})); } catch { console.log("undefined"); }'`
Works:
`{"pwtIndex":"/some/path/tests/node_modules/@playwright/test/index.js","version":"1.29.1"}`

**Comment by mxschmitt** [comment]
So I see a few things which might cause it,

- as per above, you need to call them e.g. foobar.spec.js or foobar.spec.ts only then Playwright Test (and vscode) will pick them up
- since you are on Windows you need to double escape slashes when executing it via the CLI: `npx playwright test .\\practiseTests\\FirstTest.spec.js`
- You are missing an `await` before page.goto, not a huge deal but later on you'll run into issues by that.

You can also try to execute `npx playwright test` without any parameters to see if it will run the tests at all.


@Avol-V try upgrading Playwright

**Comment by denkorz** [comment]
In my case it often happens that after some changes in test file I'm trying to run the test in debug mode from test explorer, see the issue Running 0 tests using 0 workers, click reload button in test explorer and run test one more time.

But about several weeks ago I started facing an issue, when after reloading of test explorer, test name changes to test file name and the only available option is to Go to test, not to run. To fix that, I need to restart the VSCode. Or I can also run test from the VS terminal, it triggers update of Test Explorer and test appears without any changes in code.

**Comment by TheGrimler** [comment]
@dd-jonas Thanks for the info. Can you let me know which docs you're looking at? I am working off https://playwright.dev/docs and don't see that mentioned in the getting started guide. I'm hoping wherever you see that can help me with more details I am likely missing. 

@dd-jonas @mxschmitt Thanks for the help. Adding the ".spec" to the file name and using double slashes worked. Not having the "await" does cause problems but those are unrelated, the file is at least being found. 

I appreciate you guys.

**Comment by dd-jonas** [comment]
@TheGirmler I found it on the [configuration page here](https://playwright.dev/docs/test-configuration#testing-options), the option `testMatch`
