### ISSUE TITLE
[Feature] Option to open debugger on failed test

### ISSUE THREAD

**Issue by ErikBrendel** [microsoft/playwright#21563]
# Use Case:

I (developer) just made code changes, and want to re-run the whole test suite to verify everything still works. Should a test fail, I want to start debugging this test immediately, to inspect (and quickly fix) the page state / test logic.
If no test fails, I want the test suite to run to completion without any interaction needed.

# Current workaround:

```typescript
const autoDebugFailedTests = process.env.CI !== "true" && process.argv.includes("--headed");
/**
 * Utility function for calling page.pause() in case of a test failure
 */
async function wrapTry(page: Page, logic: () => Promise<void>) {
    if (!autoDebugFailedTests) {
        return logic();
    }
    try {
        await logic();
    } catch (e) {
        page.on('dialog', (_) => void 0);
        await Promise.all([
            page.evaluate((e) => alert(e), e),
            page.pause(),
        ]);
        throw e;
    }
}

// all "test" calls then need to be modified like this:
test('My test', ({page}) => wrapTry(page, async () => {
    // test logic here
}));
```

This workaround is ok, but not pretty _(e.g. showing the error as an alert instead of the within the playwright debugger)_, and needs to be applied to each "test" definition by hand.

# Proposed Solution

Instead, it would be nice if an option like `--autoDebugFailedTests` could be passed to the playwright CLI, which enables the described behavior.

**Comment by mxschmitt** [comment]
We recommend using the [Visual Studio Code extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright), when you run a test there, you see which step it is currently performing and when you debug a test, it will automatically break when an expect is failing. It also will re-use the browser and the browser stays open so you can debug it.

**Comment by ErikBrendel** [comment]
Thank you for the answer!

Given that the Playwright VS Code Plugin has this capability, then maybe this feature could be made available to other IDEs as well? Implementing such a CLI flag might make Playwright Debugging more accessible to people using other editing tools (e.g. WebStorm, Sublime, Notepad, ...)

**Comment by mxschmitt** [comment]
As of today its not planned to release an extension for other IDEs. There is a feature request for Web storm: https://github.com/microsoft/playwright/issues/14247

Folding into that.

(We strongly recommend the VSCode extension, because you are missing out on a ton of features!)

**Comment by dylan-chong** [comment]
hello, i don't use vscode. are there any plans to have this feature implemented from the cli?
