### ISSUE TITLE
[BUG]Process.env variables lost from project dependencies

### ISSUE THREAD

**Issue by gstepien82** [microsoft/playwright#21565]
### System info
- Playwright Version: [v1.31]
- Operating System: [Windows 11]
- Browser: [All]
- Other info: Code in TS

### Source code
- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const defaultConfiguration: any = {
  actionTimeout: process.env.DEBUG ? 30_000 : 60_000,
  navigationTimeout: process.env.DEBUG ? 30_000 : 60_000,
  headless: process.env.CI === 'true' ? true : false,
  locale: 'en-US',
  viewport: { width: 1920, height: 1080 },
  ignoreHTTPSErrors: true,
  baseURL: Global.getBaseUrl(),
  launchOptions: {
    args: ['--incognito'],
    slowMo: 100,
  },
  screenshot: {
    mode: 'only-on-failure',
    fullPage: true,
  },
  trace: 'retain-on-failure',
  video: 'retain-on-failure',
};

const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'UI_TESTS_SETUP',
      testDir: './tests/ui',
      testMatch: '*global.ts',
      use: defaultConfiguration,
      expect: {
        timeout: process.env.DEBUG ? 30_000 : 60_000,
      },
    },
    {
      name: 'UI_SESSIONS',
      testDir: './tests/ui',
      testMatch: '*envcheck.test.ts',
      use: defaultConfiguration,
      expect: {
        timeout: process.env.DEBUG ? 30_000 : 60_000,
      },
      dependencies: ['UI_TESTS_SETUP'],
    },
```

**Test file (self-contained)**
2 files: setup & test
setup:
import test from '@playwright/test';
import { logger } from '../../logger';
test.describe('Setup', async () => {
  test('SM-SETUP/STEP-1 venue setup', async () => {
    logger.info('UI setup started');
    process.env['A'] = 'TEST';
    logger.info(`Setup->reading process.env["A"]=${process.env['A']}`);
  });
});
test:
import test from '@playwright/test';
import { logger } from '../../logger';

test.describe.only('test', async () => {
  test(`test`, async () => {
    logger.info(`Project Y->reading process.env["A"]=${process.env['A']}`);
  });
});

**Steps**
Run the tests

**Expected**
Process.env vars propagated between projects if there is dependency

**Actual**
Process.env vars not propagated between projects if there is dependency

INFO
**Setup->reading process.env["A"]=TEST**

INFO
**Project Y->reading process.env["A"]=undefined**

**Comment by mxschmitt** [comment]
This is expected, since if you run tests in parallel or if they are run in a new worker, they are in a new isolated world aka. a worker, see [here](https://playwright.dev/docs/test-parallel). We recommend to not sharing values with your tests, or if you do some "pre-work" then putting it into global setup and storing it on the file-system for now and reading it later on.

We are currently experimenting with a custom Storage which you can use to get and set values into per worker.

**Comment by loxinchi** [comment]
@gstepien82
I had the same problem after implemented project dependencies.
I took off the `process.env` part from global-setup, and put them in a `fixture`.
