### ISSUE TITLE
[QUESTION] Social Auth using Facebook - on some Android device emulators I'm getting unexpected Confirm dialog.

### ISSUE THREAD

**Issue by Joker131313** [microsoft/playwright#21576]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- Other info: Playwright default mobile devices: Pixel 5, Pixel 4a (5G).

I'm creating Playwright tests using default mobile devices.

Test scenario: Login to the app under test using "Sign In with Facebook" option (valid Facebook account has been previously created).

If I run the test using either "iPhone 13", "Galaxy Tab S4" or "Nexus 10" device - I'm getting second Incognito tab opened with Facebook login fields. After typing in credentials and click Login button I'm getting automatically redirected to my app under test.
If I run the same test using either "Pixel 5", "Pixel 4" or "Pixel 4a (5G)" device - I'm getting another dialog on top "You previously logged in to <app name> with Facebook. Would you like to continue?", which is confusing. 
I should not probably getting such dialog for Pixel devices or should I get it on all devices?

<img width="616" alt="Second dialog" src="https://user-images.githubusercontent.com/23156662/224420645-e8297bed-ac3b-4963-84d2-dce5a565428b.png">

My config file:
  ```
projects: [
    {
      name: 'mobile',
      use: {
        ...devices['iPhone 13'],
        screenshot: 'only-on-failure',
        headless: true
      },
    },
    {
      name: 'mobile',
      use: {
        ...devices['Pixel 5'],
        screenshot: 'only-on-failure',
        headless: true
      },
    },
  ]

```
Tests steps are very basic and standard like these for Facebook Login popup:
```
   await newPage.locator('#m_login_email').fill(email);
   await newPage.locator('#m_login_password').fill(password);
   await newPage.locator('[name="login"]').click();
```

**Comment by mxschmitt** [comment]
Looks like an issue on the Facebook site, I recommend reaching out to them or looking for a workaround.
