### ISSUE TITLE
[BUG] Firefox reader mode doesn't work

### ISSUE THREAD

**Issue by nmain** [microsoft/playwright#2157]
**Context:**
- Playwright Version: 1.0.1
- Operating System: Windows 10
- Node version: 13.8.0
- Browser: Firefox

**Code Snippet**

When I try to navigate to an `about:reader` url, the response is null.  In a real Firefox instance, pasting the same url into the address bar works.

```javascript
const { firefox } = require("playwright");

(async () => {
	const browser = await firefox.launch();
	const context = await browser.newContext();
	const page = await context.newPage();
	const response = await page.goto("about:reader?url=https://www.mozilla.org/firefox");
	console.log(response == null); // true
	await page.close();
	await context.close();
	await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
I can see that we track it all the way to the addon navigation `.cache/ms-playwright/firefox-1093/firefox/omni.ja!/chrome/toolkit/content/global/reader/aboutReader.html` at which point, latter takes over. You can still interact with the page though. I pass `headless: false` and don't close the browser for you to see the result:

```js
const { firefox } = require("playwright");

(async () => {
        const browser = await firefox.launch({ headless: false});
        const context = await browser.newContext();
        const page = await context.newPage();
        const response = await page.goto("about:reader?url=https://www.mozilla.org/firefox");
        // This is ugly since we have no insight into the addon business :(
        await page.waitForTimeout(2000);
        console.log('URL: ', page.url());
        console.log('Title: ', await page.title());
        await page.screenshot({ path: 'reader.png' });
})();
```

**Comment by nmain** [comment]
Thanks for the response!  Following your lead, I am able to interact with the page.  Leaving this issue open because exactly how long to wait is a bit hacky or flaky, as well as detecting if the page failed to load.

**Comment by pavelfeldman** [comment]
You can wait for the given selector or poll page for updates. There is a predefined dom structure in the reader, so when it changes / goes away, you know that it has loaded content.

It is unlikely that we prioritize this issue since addons are outside of the "web" scope. But if fond an easy solution, happy to help.

**Comment by aslushnikov** [comment]
Let's close this for now. We can always re-open this if there's enough demand.

**Comment by akramsystems** [comment]
i value this
