### ISSUE TITLE
[BUG] Firefox asserts navigating to Youtube

### ISSUE THREAD

**Issue by nmain** [microsoft/playwright#2158]
**Context:**
- Playwright Version: 1.0.1
- Operating System: Windows 10
- Node version: 13.8.0
- Browser: Firefox

**Code Snippet**

When trying to simply navigate to a Youtube video in Firefox, an unhandled rejection occurs, but it's not for any promise returned by the API.

```javascript
const { firefox } = require("playwright");

(async () => {
	try {
		const browser = await firefox.launch();
		const context = await browser.newContext();
		const page = await context.newPage();
		await page.goto("https://www.youtube.com/watch?v=qgdzo-7HYQI"); // Exact url not relevant; any youtube video seems to work.
		await page.close();
		await context.close();
		await browser.close();
	} catch(e) {
		console.log("Caught exception/rejection: ", e); // this is never printed
	}
})();
```

Node's output:
```
(node:16004) UnhandledPromiseRejectionWarning: Error
    at Object.assert (<redacted>\node_modules\playwright-core\lib\helper.js:288:15)
    at FrameManager.frameCommittedNewDocumentNavigation (<redacted>\node_modules\playwright-core\lib\frames.js:120:18)
    at FFPage._onNavigationCommitted (<redacted>\node_modules\playwright-core\lib\firefox\ffPage.js:134:34)
    at FFSession.emit (events.js:321:20)
    at <redacted>\node_modules\playwright-core\lib\firefox\ffConnection.js:152:47
```

**Comment by pavelfeldman** [comment]
I can repro this on 1.0.1, but not on the latest master, so I guess Firefox roll fixes it. We'll publish an update with the fix.

**Comment by pavelfeldman** [comment]
@nmain: you don't need to wait for an update, you can use the tip of the tree npm via `npm i playwright@next` to verify that it works.

**Comment by nmain** [comment]
Works for me on `1.0.0-next.1588957470515`, and I can stick with that version.  Thank you for the very prompt response!
