### ISSUE TITLE
[BUG] waitForSelector not timing out as expected

### ISSUE THREAD

**Issue by RobinClowers** [microsoft/playwright#21581]
### System info
- Playwright Version: 1.31.2
- Operating System: MacOS 13.2.1
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig } from "@playwright/test";

export default defineConfig({
  timeout: 15 * 60 * 1000, // 15 minutes
  use: {
    acceptDownloads: true,
    actionTimeout: 5 * 1000, // 5 seconds
    trace: "retain-on-failure",
  },
  workers: 5,
  fullyParallel: true,
});

```

**Test file (self-contained)**

```js
it('should timeout after 3 seconds', async ({ page }) => {
  page.goto("http://localhost:3000/");
  page.setDefaultTimeout(3 * 1000); // 3 seconds
  await page.waitForSelector('text="something not in the dom"')
});
```

**Steps**
- Run the test
- Observe that it waits until the global test timeout of 15 minutes elapses

**Expected**
According to the docs, the `page.setDefaultTimeout` value of 3 seconds should kick in here.
Also, according to this issue: https://github.com/microsoft/playwright/issues/13723, the actionTimeout of 5 seconds should also apply.

**Actual**

The only way I've been able to get this to timeout as expected is by passing the option directly to `waitForSelector`.

**Comment by mxschmitt** [comment]
<img width="544" alt="image" src="https://user-images.githubusercontent.com/17984549/224472875-244feccc-f11b-4950-b4e3-1def24975e98.png">

works for me! When I remove the page.setDefaultTimeout it ends up at 5 seconds:

<img width="557" alt="image" src="https://user-images.githubusercontent.com/17984549/224472924-e35cc265-848d-4362-8957-65f266a84827.png">

I see that you have a missing await at page.goto, thats probably not causing it but also not recommended.

How do you run your tests? There are certain scenarios where we disable the timeout. If I remember correctly e.g. --debug, when a debugger is attached, vscode debugging terminal, Playwright vscode extension when you debug a test etc.

**Comment by RobinClowers** [comment]
Oh, maybe that's the issue, I'm running with `DEBUG=pw:api` if I remember correct (I'm not in front of my work laptop ATM). I'll removing that and see if it fixes the issue, thanks!

**Comment by RobinClowers** [comment]
Small update here, I was testing locally with `PWDEBUG=1`, `DEBUG=pw:api` does *not* ignore timeouts, which is great, because that information is super useful in CI!
