### ISSUE TITLE
docs(fixtures): Missing todo-page.js & settings-page.js

### ISSUE THREAD

**Issue by anishkny** [microsoft/playwright#21597]
Doc page: https://playwright.dev/docs/test-fixtures#creating-a-fixture

It says:

> Below we create two fixtures `todoPage` and `settingsPage` that follow the [Page Object Model](https://playwright.dev/docs/pom) pattern.

```js
const { TodoPage } = require('./todo-page');
const { SettingsPage } = require('./settings-page');
```

But neither `todo-page.js` nor `settings-page.js` are present.

**Comment by ltsuda** [comment]
From "Below we create two **fixtures** `todoPage` and `settingsPage`", they are creating **fixtures** for those POM classes and the fixtures are there. They are not showing how to create the POM classes itself, I hope I made a little bit clear.

```javascript
export const test = base.extend<MyFixtures>({
  todoPage: async ({ page }, use) => {     // todoPage fixture
    // Set up the fixture.
    const todoPage = new TodoPage(page);
    await todoPage.goto();
    await todoPage.addToDo('item1');
    await todoPage.addToDo('item2');

    // Use the fixture value in the test.
    await use(todoPage);

    // Clean up the fixture.
    await todoPage.removeAll();
  },
 
  settingsPage: async ({ page }, use) => {     // settingsPage fixture
    await use(new SettingsPage(page));
  },
});
```

**Comment by dgozman** [comment]
I think we should improve both POM and fixtures docs.

**Comment by anishkny** [comment]
> From "Below we create two **fixtures** `todoPage` and `settingsPage`", they are creating **fixtures** for those POM classes and the fixtures are there. They are not showing how to create the POM classes itself, I hope I made a little bit clear.

@ltsuda  Sure. But it feels incomplete to me. It would definitely help (at least me) to see how `TodoPage` and `SettingsPage` are actually implemented.
