### ISSUE TITLE
[Feature] hasFocus method on element

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#2159]
I didn't see this in the docs, but I may not have looked in the right place. Is it possible to check if an element has focus?

**Comment by mxschmitt** [comment]
You could do something like that: 

```js
const foo1Isfocused = await page.$eval("#foo1", (el) => el === document.activeElement)
```

Interactive example: https://try.playwright.tech/?s=dkcpx

**Comment by celeryclub** [comment]
Thanks for that @mxschmitt. That's super helpful. I changed this to be a feature request for a native method to support this functionality, but this is perfect in the meantime.

**Comment by aslushnikov** [comment]
@celeryclub Testing focus feels like a rare'ish usecase, so let's live with [the workaround](https://github.com/microsoft/playwright/issues/2159#issuecomment-625883641) for now. If there's a lot of demand for this kind of functionality, we'll add it later on.

Thanks for filing!

**Comment by chundhau** [comment]
@aslushnikov I disagree that testing focus is "rare'ish." If we want to test a keyboard interface (common when testing for accessibility), we need to determine if the proper element gains keyboard focus after a certain user action. This is the "bread and butter" of accessbility testing and should be supported as soon as possible by PlayWright. Thanks!

**Comment by WestonThayer** [comment]
I think this has been implemented in [toBeFocused()](https://playwright.dev/docs/test-assertions#expectlocatortobefocused) since https://github.com/microsoft/playwright/pull/7873

```js
const btn = page.locator("#my-button");
await btn.focus();
await expect(btn).toBeFocused();
```

Also works fine when focus is moved another way, via `await page.keyboard.press("Tab")`.

**Comment by Stachys** [comment]
@aslushnikov I agree with the above that focus testing is essential in terms of testing for accessibility. It's great to see that it was added in [Assertions](https://playwright.dev/docs/test-assertions#expectlocatortobefocusedoptions). 
Unfortunately, this solution works only with Playwright test runner, but it would be very useful to have a solution in Playwright Library itself. Thanks!

**Comment by WestonThayer** [comment]
@Stachys you don't need the test runner, right? `toBeFocused()` is just a convenience wrapper for

```js
const button = page.locator("#my-button");
const hasFocus = await button.evaluate(node => document.activeElement === node);
```

**Comment by mxschmitt** [comment]
`toBeFocus` via `expect` gives you auto-retries with a specific timeout. So its different and more feature-rich.

Which test-runner are you using currently and why does the Playwright test-runner not work for you? Just curious.

**Comment by kevinansfield** [comment]
> Which test-runner are you using currently and why does the Playwright test-runner not work for you? Just curious.

I've just run into the same issue. In our case we're using the `vitest` runner so we can have e2e and unit tests run together along with test watching ability (eagerly awaiting https://github.com/microsoft/playwright/issues/7035 if it ever becomes a reality)

**Comment by jensakejohansson** [comment]
I also think the that there should be a convenience method on the 'element' to check if it has focus. Just liks there is IsChecked, IsEnabled, etc, there should be an IsFocused method. Yes, you can run a JS yourself, but that could be the answer to almost everything....

I use the dotnet library and I'm not using Playwrights test runner wrappers or the built in expect methods since they don't fit my usecase. I have a comprehensive test framework built on an other runner and assertion libraries I only use Playwright as a _driver_.

**Comment by RunOrVeith** [comment]
```const hasFocus = await button.evaluate(node => document.activeElement === node);``` also does not work if the node is inside an iframe or shadow dom, so there is more to be done here

**Comment by bschlenk** [comment]
I agree a `hasFocus` method would be nice. I would like to locate an element, and then loop pressing Tab until that element is focused.
