### ISSUE TITLE
[BUG] Launching chrome extension is blocked on docker container page.goto: net::ERR_BLOCKED_BY_CLIENT at chrome-extension://

### ISSUE THREAD

**Issue by hemche** [microsoft/playwright#21600]
I have used [this](https://playwright.dev/docs/chrome-extensions#testing)  guide to launch my extension and run e2e locally on mac.
But, when i run the same setup in the Playwright Microsoft image [mcr.microsoft.com/playwright:v1.30.0-focal](https://hub.docker.com/_/microsoft-playwright) I keep getting 
`page.goto: net::ERR_BLOCKED_BY_CLIENT at chrome-extension://sdfsdfdfd/xxxx.html#/xxx` error.

### System info
- Playwright Version: [v1.31.2]
- Operating System: [Ubuntu.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- Please follow the repo here https://github.com/hemche/playwright

**Expected**

Run should pass in ubuntu docker image as well

**Actual**

Tests fail due to blocked chrome extension while they pass locally.

**Comment by dgozman** [comment]
@hemche Unfortunately, you did not provide a repro, so we are unable to help without ability to run it locally. Could you please provide a repro?

**Comment by hemche** [comment]
@dgozman Please find the repo to reproduce the issue. All steps are mentioned in the README.

https://github.com/hemche/playwright

**Comment by hemche** [comment]
@dogzman and @mxschmitt  Issue got resolved now. It was because, the chrome extension id was unique to every machine it was being run on as we didn't have a static `key` for the extension. It started working once we fixed our extension id calculation function. Thanks for your time. Appreciate your work.
