### ISSUE TITLE
[BUG] Provisional headers are shown error when the site is running at playwright chrome

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#21607]
![a4cdc43a15646a97ac6022ba44d7802](https://user-images.githubusercontent.com/9427959/224603930-9ab27422-2f1a-4e0a-8084-c0e0996bd524.png)

**Comment by dgozman** [comment]
This does not look like a bug report or a feature request for Playwright. If you have encountered a bug, please file a new issue using the "Bug Report" template. For feature requests, use the "Feature request" template.
