### ISSUE TITLE
[BUG] pago.goto  can not open some url

### ISSUE THREAD

**Issue by viponedream** [microsoft/playwright#21612]
https://goerlifaucet.com/
i can open this url in private mode, but in playwright,  the url  was banned.

**Comment by jeroenvermunt** [comment]
I don't think this has anything to do with playwright, but more with how the website recognizes the user. Did you try launching playwright with the some user agent as your browser in private mode?

**Comment by dgozman** [comment]
As @jeroenvermunt said - this seems to kick in some Cloudflare protection mechanism, not related to Playwright.
