### ISSUE TITLE
[REGRESSION]: RegExp changed, in work with hasText

### ISSUE THREAD

**Issue by SirCmX** [microsoft/playwright#21610]
**Context:**
- GOOD Playwright Version: 1.27.1
- BAD Playwright Version: 1.31.2
- Operating System: Ubuntu 20.04.5 LTS

**Does not work anymore:**

-- value_in_Dataset is = cargo
    let dataset = await page.locator('tr', {hasText : new RegExp('^' + value_in_Dataset , 'g')}).locator('button[id*="editButton"]')

    await dataset.waitFor({state: "attached"})
    await dataset.click()

**Does now work:**

-- value_in_Dataset is = cargo
    let dataset = await page.locator('td', {hasText : new RegExp('^' + value_in_Dataset , 'g')}).locator('..').locator('button[id*="editButton"]')

    await dataset.waitFor({state: "attached"})
    await dataset.click()

**tr  = 1.5511.44/39 | cargo-deliver | date | cargo** 

I recently updated Playwright from 1.27.1 to 1.31.2 and discovered a possible bug.
Probably the ^ in RegExp does not work anymore with hasText.
Playwright now finds two values in the tabelrow instead of one, when i search for cargo in a tablerow mentioned above.

**Comment by dgozman** [comment]
@SirCmX We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
