### ISSUE TITLE
[Question]How to use part of a string in playwright

### ISSUE THREAD

**Issue by WallaceAnalista** [microsoft/playwright#21623]
I'm going through a doubt and would like to know if someone could help me.

I need to read an element, the element would be the title of an email, I have to take the last 6 characters and save it in a variable to be used later, because it is a token and I need to copy and paste it later.

Text example: Follows token 123456

What I need to get is the “123456” attribute and be able to use it later

**Comment by dgozman** [comment]
@WallaceAnalista You should probably look into [`Locator.textContent`](https://playwright.dev/docs/api/class-locator#locator-text-content) to get the text, and then manipulate it with some JavaScript. I'd recommend reading some docs about string manipulation in JavaScript.

**Comment by Mone71** [comment]
Thanks
