### ISSUE TITLE
[Feature] Open and interact with browser devtools

### ISSUE THREAD

**Issue by kuba-orlik** [microsoft/playwright#21625]
We're creating a browser automation script that helps to prepare screenshots of network requests initiated by a given website. Due to formal requirements, the screenshots have to include an opened network inspector panel, with the request list scrolled down to some particular requests. The way I'm doing this now is by wonky and not future-proof xdotool scripts. If Playwright supported interacting with devtools, it would simplify and strengthen our codebase a lot.

**Comment by dgozman** [comment]
@kuba-orlik Thank you for the issue! I don't think Playwright will be focusing on this. You can probably set `PW_CHROMIUM_ATTACH_TO_OTHER` environment variable, somehow open DevTools, and get a `Page` for it. Note this is not guaranteed to work in the future, so I wouldn't build anything serious around it.
