### ISSUE TITLE
[Question] Websocket intercept

### ISSUE THREAD

**Issue by kv-gits** [microsoft/playwright#2162]
Is it possible to catch websocket events on the page of context? Looked in issues. Seems there was such feature but later deprecated. Would like to clarify about it.

**Comment by pavelfeldman** [comment]
Events about web sockets were trimmed from the v1, but we will definitely get back to them. But those were events, not interception. Would you like to mock / intercept web sockets or sniffing the websocket frames would suffice?

**Comment by kv-gits** [comment]
More control over websockets is better of course, but sniffing websocket frames would suffice. Thanks for info!
