### ISSUE TITLE
[Question] Company internal docker build

### ISSUE THREAD

**Issue by tepmehatop** [microsoft/playwright#21622]
Hello everybody!
There is a need to build a docker image with Playwright, but inside the company, without using external dependencies.

Dependencies, including playwright itself, will be taken from the internal repository.

Based on: https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.focal

- Playwright version: 1.29.2
- Ubuntu base image version: ubuntu:22.10
- Node: 18

### Questions:
1. **playwright-core.tar.gz** is generated by simply calling, inside your project:
`node ./pack_package.js ./../packages/playwright-core/ ./playwright-core.tar.gz `
is there nothing else needed?

2. Step: 
`npx playwright install --with-deps && rm -rf /var/lib/apt/lists/* && \`

At this step, I have a problem installing Playwright and browsers for it.
If I run:` PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright install --with-deps && rm -rf /var/lib/apt/lists/*`
and then I just **copy** the browser binaries myself to /ms-playwright (`COPY ./ms-playwright /ms-playwright`)
Then when I run autotests, I get the following message:
"**_Looks like Playwright Test or Playwright was just installed or updated_**"

I saw the option "Download from artifact repository": https://playwright.dev/docs/browsers
But unfortunately I do not have an artifact repository in which they will store the browser :(

How is it possible to install Playwright from the local repository and at the same time slip the browser manually. Do you have any other ideas/suggestions?

5. When I run the command in a separate run via echo `RUN echo $(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=true npx playwright install --with-deps && rm -rf /var/lib/apt/lists/*)`

I see this message in the logs:
**_npm WARN exec The following package was not found and will be installed: playwright@1.19.2_**

Why trying to install **1.19.2**? if the version I need is **1.29.2**? I also took your repository from Github 1.29.2 to generate playwright-core.tar.gz.

Thanks in advance for any help 🤝,
Mark.

**Comment by mxschmitt** [comment]
1. You need to build the project before `npm run build` and then pack yes.
2. You most likely either copy the browsers with the wrong version or with the wrong OS / architecture.

If you get `npm WARN exec The following package was not found and will be installed: playwright@1.19.2` it means you need to create a project first, install the @playwright/test version in it, and then npx will work. Thats what we do [here](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy#L34) with npm init and npm i. 

Why does running the [`./utils/docker/build.sh --amd64 jammy playwright:localbuild-jammy`](https://github.com/microsoft/playwright/blob/main/utils/docker/build.sh) not work for you?

**Comment by tepmehatop** [comment]
@mxschmitt Hi, Thank's a lot for your answer, and sorry for my late answer.

with playwright-core.tar.gz solved, everything is ok.

> Why does running the [`./utils/docker/build.sh --amd64 jammy playwright:localbuild-jammy`](https://github.com/microsoft/playwright/blob/main/utils/docker/build.sh) not work for you?

Because this script, as well as the scripts inside "playwright-core.tar.gz", are sent to the Internet to download browsers.

Now I have just the main problem with downloading browsers, more precisely, NOT! need to download. 
I solved all the other problems.

As I said earlier, I need to build a docker container inside a company that has its own internal repository and no Internet access.

Right now I'm stacking browsers by copying them into a docker container at build time.
somthing like: `COPY ./ms-playwright /root/ms-playwright`

 Then I just run test by setting browsers location: 
`PLAYWRIGHT_BROWSERS_PATH=$HOME/ms-playwright npx playwright test`
And everything works.

But, this is a crutch method that I don't like, it's like a temporary solution.
The problem is that, I try to download the project dependencies, but when I run `npm install` i see an error about trying to download a browser from the internet.

**LOG:**
<details><summary>Details</summary>
<p>

Step 40/44 : RUN npm init playwright -y --no-browsers &&     npm i /tmp/playwright-core.tar.gz &&     rm -rf /var/lib/apt/lists/*
 ---> Running in 56a64eb1306e
[33mGetting started with writing [1mend-to-end[22m tests with [1mPlaywright[22m:[39m
Initializing project in '.'
[?25l[36m?[39m [1mDo you want to use TypeScript or JavaScript?[22m [2m…[22m 
[36m▸[39m [36m[4mTypeScript[24m[39m
  JavaScript[2A[50G[?25h[91mnpm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
[0m[91mnpm WARN [0m[91mdeprecated experimental-allure-playwright@0.0.3: This package is now officially maintained by Allure. Please update your playwright.config.{ts,js} and package.json to 'allure-playwright' instead of using this NPM package.
[0m[91mnpm notice 
npm notice New minor version of npm available! 9.5.1 -> 9.6.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.6.1>
npm notice Run `npm install -g npm@9.6.1` to update!
npm [0m[91mnotice 
[0m[91mnpm ERR! code 1
[0m[91mnpm ERR! path /ms-playwright-agent/node_modules/playwright
[0m[91mnpm ERR![0m[91m command failed
[0m[91mnpm ERR! command sh -c node install.js
[0m[91mnpm ERR! Downloading Chromium 111.0.5563.19 (playwright build v1048)[2m from [https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip[22m](https://playwright.azureedge.net/builds/chromium/1048/chromium-linux.zip%1B[22m)
npm ERR![0m[91m Downloading Chromium 111.0.5563.19 (playwright build v1048)[2m from [https://playwright-akamai.azureedge.net/builds/chromium/1048/chromium-linux.zip[22m](https://playwright-akamai.azureedge.net/builds/chromium/1048/chromium-linux.zip%1B[22m)
npm [0m[91mERR! Downloading Chromium 111.0.5563.19 (playwright build v1048)[2m from [https://playwright-verizon.azureedge.net/builds/chromium/1048/chromium-linux.zip[22m](https://playwright-verizon.azureedge.net/builds/chromium/1048/chromium-linux.zip%1B[22m)
[0m[91mnpm ERR! Error: connect EAFNOSUPPORT 2620:1ec:4f:1::45:443 - Local (undefined:undefined)

</p>
</details> 

Here is my Dockerfile:
`## === BAKE BROWSERS INTO IMAGE ===
ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
COPY ./playwright-core.tar.gz /tmp/playwright-core.tar.gz
COPY ./ms-playwright /root/ms-playwright

## 2. Bake in Playwright Agent.
RUN npm init playwright -y --no-browsers && \
    npm i /tmp/playwright-core.tar.gz && \
    rm -rf /var/lib/apt/lists/*

#RUN echo $(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npm i playwright@1.29.2 --with-deps)
RUN echo $(pwd)
RUN echo $(npm install)
RUN echo $(PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright@1.29.2 install --with-deps)
`

That's mean **--no-browsers** option is not working? how to init/npm install project without downloading a browser?
On a local machine where there is Internet, of course everything works and there are no problems with this.
That is, the Dockerfile is working.


Thanks in advance for any help 🤝,
Mark.

**Comment by mxschmitt** [comment]
Since its solved, I'm closing it for now. `npm init playwright` is not intended to be run inside a Docker image or CI environment. Its a tool to scaffold new projects. You can manually do `mkdir foo && cd foo && npm init -y && npm install @playwright/test && npx playwright install` like we do inside your Docker image to download the browsers.

Since you install the `playwright` package, its [expected](https://playwright.dev/docs/library#key-differences) that it installs the browsers, if you want no browsers, install `@playwright/test` instead.
