### ISSUE TITLE
[Feature] Please add the parent method for finding the parent by the child

### ISSUE THREAD

**Issue by DavitV-yan** [microsoft/playwright#21633]
Here is the example of what I want to see
async getLocator(){
    const parentLocator = await this.page.parentLocator("#parent").locaotor("#child")
    parentLocator.locaotor("#child_2");
  }
  
here is the example, why I needed this method, because sometimes impossible to interact with the dynamic locator
 <div id="parent">
    <a class='child_1'></a>
    <a class='34iurgr834g'></a>
</div>

**Comment by dgozman** [comment]
Take a look at [this doc](https://playwright.dev/docs/locators#filter-by-another-locator) and [this doc](https://playwright.dev/docs/other-locators#parent-element-locator).

**Comment by DavitV-yan** [comment]
> 

I will try it thanks

**Comment by dgozman** [comment]
Closing per above. If you still encounter problems, please file a new issue and link to this one.
