### ISSUE TITLE
[Feature] Please add the possibility to retry whole tests in the test file not only the failed test

### ISSUE THREAD

**Issue by DavitV-yan** [microsoft/playwright#21634]
In some cases, the second test fails because something went wrong in the first test, and retrying the second test will return the same result

**Comment by Nav-2d** [comment]
If your second test is dependent on first one then you can use `.serial` mode. Although it is suggested to make your tests isolated if possible
Ref: https://playwright.dev/docs/test-retries#serial-mode

**Comment by dgozman** [comment]
Closing per above.
