### ISSUE TITLE
Playwright Test don't populate in Test Explorer for Playwright Test Code for VsCode

### ISSUE THREAD

**Issue by rmecwan** [microsoft/playwright#21639]
**Context:**
Hello,

I have enabled Playwright Test Code for VsCode, and I don't see the tests populating in the Text explorer even though Playwright tests are selected (they used to appear, and not anymore). Can someone please help with this? Thanks.
- Playwright Version: ^1.30.0
- Operating System: [e.g. Windows, Linux or Mac] Windows
- Node.js version: 16.17.0
- Visual Studio Code version: 1.76.1
- Playwright for VSCode extension version: 1.0.9
- Browser: All
- Extra: I have Typescript Playwright Tests
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

Add any other details about the problem here.

**Comment by dgozman** [comment]
@rmecwan We have to reproduce this issue locally to be able to debug it. Could you please file a new issue by following the "Bug report" template and provide a repro that we can run locally?
