### ISSUE TITLE
[Feature] Overriding html report attachment paths

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#21636]
Hello,

In CI, once report is generated, I upload all artifacts (images, videos, traces) from `data/` to external source for storage, and thus, I would like to update paths in the actual index.html report to use `https://someurl.com/filename.png` instead of `data/filename.png`.

I though about doing just replace like `htmlAsString.replace(/src="data\//g, 'src="my-url"')` but that does not seem to work.

Could you suggest any way I could replace attachment paths?

**Comment by cenfun** [comment]
there is an option that could customize attachment path if you have a chance to use monocart-reporter
```js
// playwright.config.js
module.exports = {
    reporter: [
        ['list'],
        ['monocart-reporter', {  
            name: "My Test Report",
            outputFile: './test-results/report.html',
            attachmentPath: (relativePath) => `https://someurl.com/${relativePath}`
        }]
    ]
};
```

**Comment by dgozman** [comment]
@MindaugasMateika We can probably introduce a `attachmentsBaseURL` option for the html reporter for this. Would you like to contribute a PR?

**Comment by MindaugasMateika** [comment]
> @MindaugasMateika We can probably introduce a `attachmentsBaseURL` option for the html reporter for this. Would you like to contribute a PR?

Sure, I'll give it a shot
