### ISSUE TITLE
[Feature] allow to use non-incognito mode window in browserType.connect

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#21650]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I want to use non-incognito in connect method.

Normally, I can use non-incognito in launchPersistentContext. But sometimes, I needs https://playwright.dev/docs/api/class-browsertype#browser-type-connect to create browser, I need some methods to create non-incognito windows. Because all cloud platform like browserstack or lambatest use connect to create browser.

**Comment by dgozman** [comment]
Merging into #1523.
