### ISSUE TITLE
[Issue] Database testing in playwright

### ISSUE THREAD

**Issue by gauravsharma28041982** [microsoft/playwright#21651]
Hi All,

Can anyone please help me to perform database testing with playwright.

I am able to fetch data from database from below code .

**Node.js file :** 

const {
    createPool
     } = require('mysql') ;

const pool =createPool(
    {
        host: 'test', 
        user: 'gauravs',
        password: 'test',
        database: 'test' ,
        connectionLimit : 10 

    }
)

pool.query ('select job_status_id  from test.job_status_dim jsd where job_status_id =2' ,(error ,result) =>
{
  if (error )
  {
    return console.log(error) ;
  }

  return console.log(JSON.stringify(result).charAt(18)) ;
t
})

can anyone please help me to fetch above data in playwright file ?

**Comment by dgozman** [comment]
This does not look like a bug report or a feature request for Playwright. I'd recommend to ask this question in the `mysql` project, or look for some other npm package to help you access the database.
