### ISSUE TITLE
Single Page App runs in headed mode not correctly for chromium and firefox

### ISSUE THREAD

**Issue by Petroglyphe** [microsoft/playwright#21655]
### System info
- Playwright Version: [1.31.2]
- Operating System: [Windows 11]
- Browser: [Chromium, Firefox,]
- node.js versions [16.14.2, 18.11.0, 19.7.0]

### Source code

I can't share source code. It is an subject of confidantial.

My tests runs until playwright version 1.28.2. In version 1.29.1 I hat to set the viewport in configuration to null. In version 1.31.2 this is not possible.

this.context=await this.browser.newContext({
               viewport:null
            })

With webkit my tests run in all playwright versions. In chromium und firefox they dosn't run headed  correctly.
In attached files you can see the difference between webkit and chromium. It contains config-files for webkit and chromium, a video for webkit and chromium and a screenshot for chromium. 
[BugReport.zip](https://github.com/microsoft/playwright/files/10967411/BugReport.zip)

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. Could you please file a new issue filling in the "Bug Report" template and provide a repro we can run locally?

**Comment by Petroglyphe** [comment]
I CAN'T SHARE SURCE CODE. I'am no developer and have no access to source-code of th app. With the Information I have given It should be possible to recognize  wich changes are made since playwright-version 1.28.2.  and maybe produce thie failure.
