### ISSUE TITLE
[BUG] Multiple keys with the keyboard.press API not working

### ISSUE THREAD

**Issue by marimeireles** [microsoft/playwright#21661]
**Context:**
- Playwright Version:
playwright                1.30.0                   pypi_0    pypi
pytest-playwright         0.3.0                    pypi_0    pypi
- Operating System: osx
- Python version:
python                    3.10.9          h3ba56d0_0_cpython    conda-forge
- Browser: all

**Code Snippet**

```python
# on windows and linux
page.keyboard.press("Control+A")
```

**Describe the bug**

It seems like playwright can't reproduce any two keys combination?
I'm following the [docs](https://playwright.dev/python/docs/api/class-keyboard) exactly but nothing happens. Can't see any errors in consoles, etc.

I appreciate any pointers here. Thanks!

**Comment by dgozman** [comment]
@marimeireles This should work, according to our tests. We need more information to act on this issue. Could you please provide a repro that we can run locally, including the page you are testing this on?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue with it, and link to this one.
