### ISSUE TITLE
[BUG] Misleading expect timeout in reports

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#21664]
**Context:**

- Playwright Version: 1.31.2
- Operating System: Windows 11
- Node.js version: v18.14.1
- Browser: Chromium
- Extra: Base on default project after running `npm init playwright@latest`

**Test**
Configuration:
```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 5 * 1000,
  expect: {
    timeout: 3000
  },
  fullyParallel: true,
  reporter: 'html',

  use: {
    actionTimeout: 0,
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

Sample test:
```
import { test, expect } from '@playwright/test'

test.describe('has title', () => {
    test.only('create item', async ({ page }) => {
        await page.goto('https://playwright.dev/')
        await expect(page).toHaveTitle(/Playwright/)
        // Below line triggers wrong error message about expected timeout in HTLM report
        await expect.soft(page.getByRole('link', { name: 'Get started BUG' })).toBeEnabled({timeout: 7*1000}); 
    })
})
```

**Describe the bug**
In report there is info about timeout 7000ms during waiting for element, while there was timeout after 5000ms (taken from test timeout from config):
![image_2023_03_14T14_41_44_801Z](https://user-images.githubusercontent.com/72373858/225039692-43661cca-12b0-486f-83e9-7be5c81a4139.png)

**Expected**
Information that test failed after test timeout, not after expect timeout (that was set in test to greater value than test timeout).

**Comment by dgozman** [comment]
@jaktestowac I see the message "Test timeout of 5000ms exceeded" on your screenshot. Do you expect something else?

**Comment by jaktestowac** [comment]
@dgozman in the case of first line the output is correct. Next lines contains incorrect info. 
`Error: Timed out 7000ms waiting for expect(received).toBeEnabled()`
`- expect.toBeEnabled with timeout 7000ms`
Is not possible that wait for expect last more than test timeout (5000ms). And that information about expect timeout is presented twice (timeout 7000ms) what lead to confusion.
