### ISSUE TITLE
running headed test on dockerized ubuntu with gui

### ISSUE THREAD

**Issue by eshk12** [microsoft/playwright#21673]
Hello,
I am trying to run a test with headed mode on ubuntu with GUI on docker container.

I have created an image that's creating a docker image with GUI + VNC so i will able to watch it.

Dockerfile:

```
# Pull base image.
FROM ubuntu

RUN apt-get update

#Install Node.js & npm

ENV NODE_VERSION=16.13.0
RUN apt install -y curl
RUN curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
ENV NVM_DIR=/root/.nvm
RUN . "$NVM_DIR/nvm.sh" && nvm install ${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm use v${NODE_VERSION}
RUN . "$NVM_DIR/nvm.sh" && nvm alias default v${NODE_VERSION}
ENV PATH="/root/.nvm/versions/node/v${NODE_VERSION}/bin/:${PATH}"
RUN node --version
RUN npm --version

# Install LXDE and VNC server.
RUN apt-get install -y xvfb
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y lxde-core lxterminal tightvncserver
RUN apt-get install -y xfce4
RUN rm -rf /var/lib/apt/lists/*
RUN touch /root/.Xresources
COPY xstartup /root/.vnc/xstartup
RUN chmod +x /root/.vnc/xstartup

# Define working directory.
WORKDIR /data

COPY * /data

# Install Playwright dependencies
RUN npm install
# # # Install dependencies.
RUN npx @playwright/test install


# Expose ports.
EXPOSE 5901
```

I am initiating this container using this command:

`docker run -it --rm -v /data:/data -p 5901:5901 -e USER=root ubuntudsktp  bash -c "vncserver :1 -geometry 1280x800 -depth 24 && tail -F /root/.vnc/*.log"
`

I am able to log in to the container through VNC successfully, but when I am trying to execute some tests by using this command:

`xvfb-run npx playwright test test.spec.js --headed`

I can see the test is executed successfully but the browser is not opening in the VNC session.

![image](https://user-images.githubusercontent.com/20819854/225125991-fa2469c6-e004-408b-9384-f5aa527e0c88.png)

What am I missing here?
How can make the test to open the browser?

### System info
- Playwright Version: [v1.30]
- Operating System: [Ubuntu 20.4]
- Browser: [All]

**Comment by aslushnikov** [comment]
@eshk12 I'm not sure what's the contents of the `xstartup` file, but bach in the days, when we were playing with this, we had the following lines in the docker startup script:

```sh
# Launch x11
nohup /usr/bin/xvfb-run --server-num=$DISPLAY_NUM \
     --listen-tcp \
     --server-args="-screen 0 "$GEOMETRY" -fbdir /var/tmp -dpi "$SCREEN_DPI" -listen tcp -noreset -ac +extension RANDR" \
     /usr/bin/fluxbox -display "$DISPLAY" >/dev/null 2>&1 &

# Launch x11vnc
nohup x11vnc -noprimary -nosetprimary -forever -shared -rfbport 5900 -rfbportv6 5900 -display "$DISPLAY" >/dev/null 2>&1 &
```

The core idea here is that first XVFB is launched, and then VNC is pointing to the XVFB's display.

Overall, you can take inspiration from the work that has been done in Selenium docker files:

https://github.com/SeleniumHQ/docker-selenium/tree/f4c04357786093eea9eb5195a0fd4aac65327f62/NodeBase

Hope this helps!
