### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by archit1601** [microsoft/playwright#21680]
![Screenshot at 2023-03-15 12-05-00](https://user-images.githubusercontent.com/113963331/225227086-61f90d63-85a8-40aa-84ce-858fc8de11c8.png)

### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

while running the testscripts in two different test.decribe it should run both test.describe block .

**Actual**

[Describe actual behavior]
in actual running it is skipping the next test.describe block , anything wrong i am doing so that it does run as we wanted

**Comment by dgozman** [comment]
@archit1601 We need more information to act on this issue. Could you please file a new issue and fill in the "Bug Report" template to include a repro that we can run locally? Thank you!
