### ISSUE TITLE
Does playwright have the capability of recording multiple videos of a single session? 

### ISSUE THREAD

**Issue by ShameemAkhtar111** [microsoft/playwright#21687]
Note : I'm using playwright with python. Playwright version 1.31.1 and python version 3.10.0

Below is the example code

from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context(record_video_dir="videos")
    page = context.new_page()
    ######## **Start 1st recording** ##################
    page.goto("https://www.google.com")
    page.get_by_role("combobox", name="Search").fill("iphone")
    page.get_by_role("combobox", name="Search").press("Enter")
    ######## **End 1st recording** ####################
    ######## **Start 2nd recording** ##################
    page.get_by_role("link", name="iPhone - Apple (IN) Apple https://www.apple.com › iphone").click()
    page.get_by_role("link", name="iPhone 14 Pro New").click()
    ######## **End 2nd recording** ####################
    ######## **Start 3rd recording** ##################
    page.get_by_role("group", name="iPhone 14 Pro design gallery with colour picker and features").get_by_role("link", name="Buy iPhone 14 Pro").click()
    page.locator("label").filter(has_text="iPhone 14 Pro Max 17.0 cm (6.7-inch) display¹ From ₹23317.00/mo.Per Month with N").click()
    page.get_by_role("listitem").filter(has_text="Deep Purple").locator("img").click()
    page.locator("label").filter(has_text="256GBFootnote ² From ₹24983.00/mo.Per Month with No Cost EMI with selected banks").click()
    ######## **End 3rd recording** ####################
    # ---------------------
    context.close()
    browser.close()

with sync_playwright() as playwright:
    run(playwright)

**Comment by dgozman** [comment]
@ShameemAkhtar111 This is not possible. Playwright produce a video file per page, from the moment the page was opened to the moment it was closed. Sorry for inconvenience.
