### ISSUE TITLE
[Feature] Using locks between workers

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#21706]
Some API calls in our test solution work like that:

- pull some list
- update it by appending the required value
- push updated list

In this case, it's possible to lose data, when 2 tests do it simultaneously.
Like we have 'a, b, c'.
   one test updates the value to have 'a,b,c,d'
   another test updates the value to have 'a,b,c,e' 
And the final value will be wrong anyway as the correct value is 'a,b,c,d,e'

Is there a way to use some kind of lock mechanism there?

_Originally posted by @denkorz in https://github.com/microsoft/playwright/discussions/20652_

**Comment by dgozman** [comment]
Merging into #14084.
