### ISSUE TITLE
[BUG] locator.all() doesn't work. Throw TypeError: page.locator(...).all is not a function

### ISSUE THREAD

**Issue by rliu-tibco** [microsoft/playwright#21700]
### System info
- Playwright Version: [v1.31]
- Operating System: [macOS Pro]
- Browser: [Chrome]
- Other info:

I want to get all the table rows. 
I use page.locator('tbody tr'). And this locator point to multiple table rows.
Then I use await page.locator('tbody tr').all()
I got
TypeError: page.locator(...).all is not a function

**Comment by rliu-tibco** [comment]
close this one

**Comment by rliu-tibco** [comment]
Re-open as i close it by mistake. Issue still exist

**Comment by dgozman** [comment]
@rliu-tibco  We need more information to act on this issue. Could you please file a new issue and fill in the "Bug Report" template, including a repro that we can run locally?

**Comment by MarcosIgnacioo** [comment]
wep im having this issue while deploying on firebase
