### ISSUE TITLE
[BUG] Component needs to be wrapped in a tag for test to work

### ISSUE THREAD

**Issue by codewithbugs01** [microsoft/playwright#21719]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
```javascript
export function Textarea(props: TextareaProps) {
  const { required, ...rest } = props;

  const [value, setValue] = React.useState(props.value || '');

  return (
    <>
      <textarea
        value={value}
        onChange={(event) => setValue(event.target.value)}
        className="block w-full rounded-md border-0 text-gray-900 shadow-sm ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 px-3 py-1.5 text-base sm:leading-6"
        {...rest}
      />
    </>
  );
}
```
- [ x ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
test('should input a value', async ({ mount }) => {
  const component = await mount(
    <div>
      <Textarea value="Hello World!" />
    </div>
  );

  const textbox = component.getByRole('textbox');

  await expect(textbox).toContainText('Hello World!');
});

test('should input a value - fail', async ({ mount }) => {
  const component = await mount(
      <Textarea value="Hello World!" />
  );

  const textbox = component.getByRole('textbox');

  await expect(textbox).toContainText('Hello World!');
});
```

**Steps**
- [Run the test]
- [...]

**Expected**
- Fill the textbox without <div> tags surrounding the component

[Describe expected behavior]

**Actual**
- Unable to fill the textbox without <div> tags surrounding the component
- ` waiting for locator('#root').locator('internal:control=component').getByRole('textbox')`
[Describe actual behavior]

**Comment by sand4rt** [comment]
Seems like intended behavior to me. I think there are only two options to access your root component:

```tsx
test('option 1', async ({ mount }) => {
  const component = await mount(
      <Textarea value="Hello World!" />
  );

  await expect(component).toContainText('Hello World!');
});
```

Or

```tsx
test('option 2', async ({ mount, page }) => {
  await mount(
      <Textarea value="Hello World!" />
  );

  const textbox = page.getByRole('textbox');

  await expect(textbox).toContainText('Hello World!');
});
```

**Comment by dgozman** [comment]
As @sand4rt said, using `component` instead of `component.getByRole('textbox')` should work.

This is because `component` points to the root of the component, which in your case is a `<textarea>`. At the same time, `component.getByRole('textbox')` will search **inside** the component, and will not find another textbox inside the textarea.

Let me know if that helps.

**Comment by codewithbugs01** [comment]
Thanks for the quick reply!  Thanks helps.
