### ISSUE TITLE
[REGRESSION]: Performance downgrade -> related case #21485

### ISSUE THREAD

**Issue by MattEarth** [microsoft/playwright#21713]
Context:

GOOD Playwright Version: 1.28
BAD Playwright Version: 1.31
Operating System: Ubuntu 20.04, Windows
Extra: jest runner
Describe the bug
Reference: https://github.com/microsoft/playwright/issues/21485

Not sure, if this is proper type of "issue". However, I experienced downgrade of performance in the test execution. Between the version 1.28 and 1.31, speed of execution has been decreased almost 3 times. Not only for the workers, but also for a single run.

And here is the repo which is showing the difference. Same code, different versions... 

https://github.com/MattEarth/pwiframeexample.git

You can also take a look on "Action" which are directly showing the differences.

**Comment by dgozman** [comment]
@MattEarth The culprit is the `slowMo` option [set here](https://github.com/MattEarth/pwiframeexample/blob/main/1.31/jest.config.js#L12). Change `500` to `0` and enjoy 😄 Let me know if that works for you.

Not sure why it worked differently in 1.28. Given that `jest` and `jest-playwright-preset` is involved, I'd rather not dig in.

**Comment by MattEarth** [comment]
Hi,
sloMo is not the root cause. Take a look on configs (one below 1.28, second below 1.31 directory), please. The same code in both directories... the only difference is PW version. And the execution time are very different: 
* 1.31 -> https://github.com/MattEarth/pwiframeexample/actions/runs/4438127536/jobs/7788755775
* 1.28 -> https://github.com/MattEarth/pwiframeexample/actions/runs/4438127530/jobs/7788755754

**Comment by MattEarth** [comment]
OK. I removed sloMo and indeed, the run is much faster (at least in the single case). However, that's really weird, that between the versions it started working differently. I hope this will also work for the whole project. 
Anyway, thanks!

**Comment by MattEarth** [comment]
FYI. It seems for the bigger project it doesn't work at all... Removing sloMo is speeding up the test run indeed, but the tests become very flaky. :(
So, I'm afraid, I stuck with version 1.28.

**Comment by dgozman** [comment]
@MattEarth `slowMo` is not a good solution for flakiness. It just adds some timeouts during tests, and is meant for debugging only. You should look into your flaky tests and add a few explicit waits. Usually, something like:
- `await page.getByText('last item that appears').waitFor()` to wait for something to load and appear on the screen;
- `await page.getByText('loading').waitFor({ state: 'hidden' })` to wait for some "loading" indicator to disappear.

**Comment by MattEarth** [comment]
I was thinking that debug mode is for debugging, and sloMo is rather for simulating more 'human' interaction (if you know what I mean)... But OK, I'll try your suggestion. 
However, I'm a bit disappointed, that you're ignoring the fact that working of sloMo between the versions is different (and probably not intended).

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
