### ISSUE TITLE
[Feature] Chrome/Firefox Extensions in headless mode

### ISSUE THREAD

**Issue by wernerwernerwerner888** [microsoft/playwright#2172]
Hello, 

i figured out that it would be still nice to test the functionality of extension in the headless mode. Is there a possibility that this is realistic? 

I know its not possible with puppeteer, but its possible wwith headful mode. Maybe there is a way to implement that in headless as well?

**Comment by aslushnikov** [comment]
>  Is there a possibility that this is realistic?

@wernerwernerwerner888 Unfortunately, this is a fundamental architectural limitation of chrome headless. Changing this is an enormous engineering effort, and there is not enough demand for this to happen.

**Comment by digitarald** [comment]
@aslushnikov can we help to determine if this is possible in Firefox or would you refrain from supporting this use case in Puppeteer when only one browser supports it?
