### ISSUE TITLE
[Question] How to get token with SSO?

### ISSUE THREAD

**Issue by Symbitic** [microsoft/playwright#21724]
I'm a Microsoft employee. Our team's application uses MSAL.js for authentication. We use SSO only, so it calls `msalInstance.acquireTokenRedirect` as soon as the page is opened. We don’t even have a login button because username/password auth isn’t used.

That means none of the existing Playwright examples work. I thought my best bet would be to use `msalInstance.acquireTokenInteractive`, but that gives me this error:

```
invalid_request: 9002327 - [2023-03-16 18:32:38Z]: AADSTS9002327: Tokens issued for the 'Single-Page Application' client-type may only be redeemed via cross-origin requests.
```

Any ideas? I am aware of https://AzureAD/microsoft-authentication-library-for-js/issues/2482 but it doesn't specify *how* to set the Origin header.

**Comment by dgozman** [comment]
@Symbitic Unfortunately, I do not understand the issue fully. However, it seems like you are trying to obtain some token from MSAL library and it does not work for some reason. Unfortunately, Playwright could not help with that. I'd recommend asking MSAL project for an advice about testing setup.

In the case I misunderstood the issue, and there is a bug/uncertainty somewhere in Playwright-related code, could you please file a new issue and fill in the "Bug Report" template with the repro that we can run locally?

Thank you, closing this one.
