### ISSUE TITLE
Handle alert accept

### ISSUE THREAD

**Issue by JeevanHB** [microsoft/playwright#21739]
![image](https://user-images.githubusercontent.com/52357464/225852225-fbeeb3c5-847a-47d6-b226-bf3f9cbfbf77.png)

I have written below code, It is not working.

this.isAlertPresentAccept = async function () {            
      getPage().on('dialog', async (dialog) => {
        expect(dialog.message()).toEqual('Do you want to logout from this session?')
        await dialog.accept()
      })
      await getPage().locator('text=Click for logout from this session?').click()
        };

Can anyone please write function for above alert to accept.

**Comment by dgozman** [comment]
@JeevanHB We need more information to act on this issue. Could you please file a new issue by filling in the "Bug Report" template and providing a repro that we can run locally?
