### ISSUE TITLE
How to use getByTestId to do css contains condition?

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#21755]
I want to use `getByTestId` to find all elements that contain the following css selector:
```
[data-qa*="something"]
```
I can do this `page.locator('[data-qa*="something"]')`. But is there a way to use `getByTestId`?

**Comment by pstrh** [comment]
You can define a custom testId-Attribute: https://playwright.dev/docs/locators#locate-by-test-id

**Comment by dgozman** [comment]
@quldude This is not possible. With `getByTestId()` you can only search for string/regex value, not the variable test id attribute. Your css selector is a good workaround.
