### ISSUE TITLE
[BUG] Playwright extension shows run test icon for each written step

### ISSUE THREAD

**Issue by DavitV-yan** [microsoft/playwright#21754]
https://drive.google.com/file/d/14OxKfnTwAH5DWCAvoPX1a8cphemRfkOP/view?usp=sharing
https://drive.google.com/file/d/1jDJVjwDDNDm8LP2KED9SY0tWPhoPX8MJ/view?usp=sharing

**Comment by dgozman** [comment]
@DavitV-yan We need more information to act on this issue. Could you please file a new issue by filling in the "Bug Report" template and providing a repro that we can run locally?
