### ISSUE TITLE
[BUG] ERR_SOCKS_CONNECTION_FAILED when debugging Playwright component tests

### ISSUE THREAD

**Issue by jm-mailosaur** [microsoft/playwright#21762]
**Context:**
- Playwright Version: 1.31.2
- Operating System: Mac (on Apple silicon)
- Node.js version: 18.15.0 (and 18.14.1, 18.13.0) [*changing version impacts results](https://github.com/microsoft/playwright/issues/21762#issuecomment-1477914705)
- Visual Studio Code version: 1.76.2
- Playwright for VSCode extension version: 1.0.9 [*changing version impacts results](https://github.com/microsoft/playwright/issues/21762#issuecomment-1477914705)
- Browser: Chromium
- Extra: N/A

**Code Snippet**

I'm using this [this completely barebone repo](https://github.com/jm-mailosaur/pw-issue) to reproduce this. I've created this to negate any chance of it being the code in my own repo.

**Describe the bug**

Using the repo above:

1. Open in VS Code
2. Click the 'play' button next to the test to run it normally. It passes.
3. Right click the 'play' button and click "Debug Test" and the following error occurs (`net::ERR_SOCKS_CONNECTION_FAILED at http://localhost:3100/`)...

<img width="1125" alt="Screenshot 2023-03-17 at 17 32 38" src="https://user-images.githubusercontent.com/29382899/225977281-d887034c-e89e-4898-8606-e0d8da649524.png">

**Comment by dgozman** [comment]
@jm-mailosaur I just cloned your repo, and it works for me. I wonder why would you get anything SOCKS-related at all? Do you have any special environment variables set up? Maybe a proxy, firewall, or some other network interceptor?

**Comment by jm-mailosaur** [comment]
@dgozman I'm just on a regular Mac with nothing special installed and no third-party firewall. I do have the built-in Apple firewall enabled, but again this isn't set into an overly agressive state, etc.

**Comment by dgozman** [comment]
@jm-mailosaur Could you try the following things:
- Open your regular Chrome browser, not through Playwright, navigate to `localhost:3000` and see whether it works.
- Set [`channel: 'chrome'` in your playwright config](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) and run the test and see whether it works.

So far, we have no better ideas than some local proxy on your computer that Chromium picks up.

**Comment by jm-mailosaur** [comment]
@dgozman Setting `channel: 'chrome'` made no difference (tests run fine, but as soon as I try and debug the Chromium window still flashes up, and immediately disappears with the same error as above).

Regarding navigating to the URL, I'm assuming you mean `locahost:3100` (as my `ctPort` is set to `3100`). If I go in Chrome when nothing is running there is nothing there and the following is returned by a curl request:

```sh
$ curl -X GET http://localhost:3100 -i
curl: (7) Failed to connect to localhost port 3100 after 6 ms: Couldn't connect to server
```

Same is true for port `3000`:

```sh
$ curl -X GET http://localhost:3000 -i
curl: (7) Failed to connect to localhost port 3000 after 12 ms: Couldn't connect to server
```

There is also nothing listening on either of those ports (nor on `8080` which is where I'd expect to see any local proxy):

```sh
$ netstat -lan | grep LISTEN | grep '3000\|3100\|8080' 
```

**Comment by jm-mailosaur** [comment]
@dgozman I noticed in my original write up I didn't make it clear that what I'm seeing when debugging is:

* Vite compiles everything
* Then, at the point a debug session would normally start, I see the Chromium window "flash" up on screen and immediately disappear
* Immediately after that I get the `net::ERR_SOCKS_CONNECTION_FAILED` error

So I'm wondering if the actual problem here is whatever is causing the browser to immediately close. Is there anyway I can get verbose logs from the browser session itself to see if I can get a reason for it closing straight away?

**Comment by TasosVellis** [comment]
What worked for me when facing similar issue was to deactivate ipv6. Just run this command in terminal

networksetup -setv6off Wi-Fi
