### ISSUE TITLE
[BUG] Tests not showing up in test explorer

### ISSUE THREAD

**Issue by hmajid2301** [microsoft/playwright#21788]
**Context:**
- Playwright Version: 1.31.2
- Operating System: Linux
- Node.js version: v19.8.1
- Visual Studio Code version: 1.76.2
- Playwright for VSCode extension version: v1.0.9
- Browser:  N/A
- Extra: N/A

I have the following ``playwright.config.ts`

```
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
	webServer: {
		command: "pnpm run build && pnpm run preview",
		port: 4173,
		timeout: 240000
	},
	testDir: "tests",
	use: {
		trace: "retain-on-failure",
		video: "retain-on-failure"
	},
	projects: [
		{ name: "setup", testMatch: /.*\.setup\.ts/ },
		// {
		// 	name: "chromium",
		// 	use: {
		// 		...devices["Desktop Chrome"],
		//    storageState: "tests/auth/user.json"
		// 	},
		// 	dependencies: ["setup"]
		// },
		{
			name: "firefox",
			use: {
				...devices["Desktop Firefox"],
				storageState: "tests/auth/user.json"
			},
			dependencies: ["setup"]
		}
	]
});

````

**Describe the bug**

I can run my tests using the CLI command. In my case I run `pnpm run test`

I don't see my tests in the VSCode Test Explorer.

![Screenshot from 2023-03-19 21-04-20](https://user-images.githubusercontent.com/998807/226208862-e71a3008-9d3d-4200-9f3a-bc297b0c42ef.png)

Link to my repo: https://gitlab.com/bookmarkey/gui

Any help would be greatly appreciated Thanks!

**Comment by mxschmitt** [comment]
I cloned it, installed the dependencies and it was working for me. How did you install VSCode? Looks like our extension is not able to find your Node.js installation. You could try to start `code .` from the terminal, so it inherits the environment variables. Is it flatmak or snap maybe?

**Comment by guido-visser** [comment]
@hmajid2301 What exactly did you do to fix this? I'm having the same issue.

**Comment by hmajid2301** [comment]
My fix involved a fish plugin (my shell) for managing nvm.

**Comment by charlesprescottcollins** [comment]
For mise users: Activate mise using both `mise activate` in your .zshrc AND add a mise shim to your `PATH` in `.zprofile`

From [2a](https://mise.jdx.dev/getting-started.html#_2a-activate-mise) and [2b](https://mise.jdx.dev/getting-started.html#_2b-alternative-add-mise-shims-to-path) in the instructions:
echo 'eval "$(~/.local/bin/mise activate zsh)"' >> ~/.zshrc
echo 'export PATH="$HOME/.local/share/mise/shims:$PATH"' >> ~/.zprofile
