### ISSUE TITLE
Support WebGL with Firefox Headless [Feature]

### ISSUE THREAD

**Issue by AnthonyPhan** [microsoft/playwright#21783]
Hi, It would be beneficial if WebGL was supported when running playwright in firefox headless to test components that require this. In our use case, we have a drawing canvas that requires webGL. 

I have found similar issues raised for this:
https://github.com/microsoft/playwright/issues/7889
https://github.com/microsoft/playwright/issues/1032

**Comment by aslushnikov** [comment]
There's an upstream issue filed in Firefox for this: https://bugzilla.mozilla.org/show_bug.cgi?id=1375585#c27
I'd recommend pinging folks in that issue to see if there are any updates.
