### ISSUE TITLE
[Question]: 'Provisional headers are shown' in chrome DevTools Request Headers

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#21791]
playwright version: v1.31.1
playwright chrome version: 111.0.5563.33
os : windows 11 64bits
language: python

action steps:
After logging in to the site, simply refreshing the browser will most likely result in the error Provisional headers are shown, then the page is stuck。
![image](https://user-images.githubusercontent.com/9427959/226241735-95c78062-a3d0-439d-b7d1-ee1a7cc19b71.png)

**Comment by aslushnikov** [comment]
@god-pane so what do I do to reproduce this? any steps I can follow? What exactly doesn't work?
