### ISSUE TITLE
[Question] Is there possibility to screenshot on failure in C#

### ISSUE THREAD

**Issue by MWRAUTO** [microsoft/playwright#21797]
![image](https://user-images.githubusercontent.com/128363781/226292512-92f12816-8a82-4ace-bb7e-d686de663fbc.png)

as i noticed, example is in TS/JS, I didn't noticed any example in C#. Is there also such possibility?

**Comment by mxschmitt** [comment]
Not as of today. Folding into https://github.com/microsoft/playwright-dotnet/issues/2214.
