### ISSUE TITLE
[Question]:  'Provisional headers are shown' in chrome DevTools Request Headers

### ISSUE THREAD

**Issue by god-pane** [microsoft/playwright#21795]
### Your question

playwright version: v1.31.1
playwright chrome version:  111.0.5563.33 
os : windows 11  64bits

action steps:  
After logging in to the site, simply refreshing the browser will most likely result in the error Provisional headers are shown
![image](https://user-images.githubusercontent.com/9427959/226232040-21bc0031-4151-48d9-84d0-ea57aab23118.png)

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/21791. Please don't file multiple issues the future.
