### ISSUE TITLE
How to create a generic method to wait for new tab to open?

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#21801]
I would like to make a generic method that opens and waits for a new tab based on the example shown [here](https://playwright.dev/docs/pages#handling-new-pages) (Handling new pages). The method should take in a trigger function like button click. Do you have an example for that or know how i can achieve it?

**Comment by aslushnikov** [comment]
@quldude this sounds more like a general programming question rather than a Playwright question; I'd recommend asking this kind of questions on stackoverflow or on our discord: https://aka.ms/playwright/discord
