### ISSUE TITLE
[Question] Security & Compliance

### ISSUE THREAD

**Issue by o0lp** [microsoft/playwright#21815]
I have not been able to find any documentation or details around Security & Compliance around void use of PII, PHI, or other types of protected information

**Comment by cpolera** [comment]
Not sure what you are looking for, but something to get you started might be here: https://playwright.dev/docs/api/class-locator#locator-blur and here: https://playwright.dev/docs/api/class-page#page-evaluate

You could identify where your PII, etc. is and have the page blur them on load.

**Comment by o0lp** [comment]
Sure, I would like to use Playwright to test my application that has protected information. I wanted to make sure that none of that data is sent or stored anywhere. I was trying to find any documentation around security and compliance that ensures that playwright will not store any data. 

The only mention of something close to what I was looking for is on the trace page "Playwright Trace Viewer is a Progressive Web App, it does not send your trace anywhere, it opens it locally." - But I was looking more for a global guidelines of what Playwright is able to access / store / anything related to protected data. For example, when comparing products such as cypress, they have this page https://www.cypress.io/security/

**Comment by pavelfeldman** [comment]
Playwright is an open source client library, it does not have a cloud component that it would be sending any information to, hence no comprehensive docs on the topic. We'll use to this issue as a request to add a documentation page that would cover this aspect though.

Having said that, it is important to remember that there are multiple components in the web testing story and not all of them are hermetic:
- When you are testing a web page, say evil.com, requests are sent to the evil.com server. So you can choose to send sensitive information and Playwright won't stop you from doing so.
- When you are using modern browsers, these web browsers will collect statistics that will be shared with the respective browser vendors.
- When you install Playwright and its browsers, information about the UserAgent  (OS, version, etc) will reach the servers (NPM, CDN) that you install Playwright from.

But I guess you are asking if we are collecting and/or processing any of the user data while you are using Playwright and are storing it and/or sending it to the cloud and the answer is no.

**Comment by o0lp** [comment]
Thank you. Makes total sense to me.

“We'll use to this issue as a request to add a documentation page that would cover this aspect though.” - thanks for doing so. It would be awesome for our team to reference that document in the future if we get asked that question again. Any time we look into new tooling, that is the first thing we need cleared.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
