### ISSUE TITLE
[QUESTION] collectIstanbulCoverage error `page.evaluate: Error: eval is disabled`

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#21836]
I am using `baseFixture` class to collect the code coverage but `eval` is disabled on my application pages. Is there any other alternative to this line `await page.evaluate(() = (window).collectIstanbulCoverage(JSON.stringify((window).__coverage__)))`

```
const test = baseTest.extend({
    context: async function ({ context }, use) {
        await context.addInitScript(() =>
            window.addEventListener('beforeunload', () =>
                (window).collectIstanbulCoverage(JSON.stringify((window).__coverage__))
            ),
        );
        await fs.promises.mkdir(istanbulCLIOutput, { recursive: true });
        await context.exposeFunction('collectIstanbulCoverage', function (coverageJSON) {
            if (coverageJSON)
                fs.writeFileSync(path.join(istanbulCLIOutput, `playwright_coverage_${generateUUID()}.json`), coverageJSON);
        });
        await use(context);
        for (const page of context.pages()) {
            await page.evaluate(() => (window).collectIstanbulCoverage(JSON.stringify((window).__coverage__)))
        }
    }
});
```

**Comment by gauravgandhi1315** [comment]
@mxschmitt Would you be able to help here?

**Comment by aslushnikov** [comment]
> I am using baseFixture class to collect the code coverage but eval is disabled on my application pages. Is there any other alternative

@gauravgandhi1315 The best option would be to use the [`bypassCSP`](https://playwright.dev/docs/api/class-testoptions#test-options-bypass-csp) option to disable content-security policies. Would it help?

**Comment by gauravgandhi1315** [comment]
@aslushnikov I have tried that already and it is not working. `eval` is strictly disabled on my application. Is there any other alternative to the last line?

**Comment by aslushnikov** [comment]
>  Is there any other alternative to the last line?

@gauravgandhi1315 I'm not aware of any. The best approach would be disabling CSP checks on your staging environment to make it more testing-friendly.
