### ISSUE TITLE
[REGRESSION]: getByLabel() resolves to 2 elements, including hidden menu

### ISSUE THREAD

**Issue by IanVS** [microsoft/playwright#21833]
**Context:**
- GOOD Playwright Version: 1.28.1
- BAD Playwright Version: 1.29.0
- Operating System: Mac
- Extra: 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://fg88kq.csb.app/');
  await page.getByLabel('Choose an element:').click();
  await page.getByRole('option', { name: 'Neptunium' }).click();
});

```

Note, you may need to run several times, or use debug mode.  Maybe there's a better way to use playwright with codesandbox, but this was the only way I could think of.

**Describe the bug**

I get a failure:

```
    locator.click: Error: strict mode violation: getByLabel('Choose an element:') resolved to 2 elements:
        1) <div tabindex="0" role="combobox" aria-expanded="fals…>Elements</div> aka getByRole('combobox', { name: 'Choose an element:' })
        2) <ul role="listbox" id="downshift-0-menu" aria-labell…></ul> aka getByRole('listbox', { name: 'Choose an element:' })
```

It seems like I can work around this by using `page.getByRole('combobox', {name: 'Choose an element:'})`, but it does not seem like the hidden menu should be considered as a target for the selector, if only because it's not even shown, so should be failing the actionability checks, right?

**Comment by IanVS** [comment]
Thanks for taking a look at this!  I do have one question: shouldn't the actionability checks exclude the hidden menu from being a possible click target?

**Comment by aslushnikov** [comment]
> shouldn't the actionability checks exclude the hidden menu from being a possible click target?

@IanVS Only [`page.getByRole()`](https://playwright.dev/docs/api/class-framelocator#frame-locator-get-by-role) defaults to visible elements; other locators traverse all elements. You can narrow them down though using `locator.filter` and [visibility pseudoclass](https://playwright.dev/docs/other-locators#id-data-testid-data-test-id-data-test-selectors)

Hope this helps!

**Comment by IanVS** [comment]
Ah ok, thanks.  I suppose this is a difference from testing-library, which I am more familiar with, and I assumed the new similar PW selectors worked the same.  Thanks for clearing it up for me.
