### ISSUE TITLE
[BUG] VS Code extension hangs on second test when running a folder of tests with "Show browser" enabled

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#21831]
**Context:**
- Playwright Version: 1.31.2
- Operating System: macOS 13.2.1
- Node.js version: 16.19.1
- Visual Studio Code version: 1.76.2
- Playwright for VSCode extension version: v1.0.9
- Browser: Chromium
- Extra: monorepo, tests are in a specific package in the monorepo

**Code Snippet**

Any test suite with multiple tests.

**Describe the bug**

1. Enable "Show Browser".
2. Open the test explorer.
3. Click the "Play"/"Run" button on a folder of Playwright tests.
4. Playwright hangs on starting the second test, finishing the first one. Without "Show browser" it runs them all successfully.

**Comment by segevfiner** [comment]
I will try and see if I can create a standalone reproduction. The project I encountered this on is proprietary and doesn't do anything too special with Playwright.

**Comment by aslushnikov** [comment]
@segevfiner I'll close this issue for now so that we don't accumulate stale issues. If you do manage to create a standalone repro, please do not hesitate to file a new issue!
