### ISSUE TITLE
[BUG] `timeout: 0` option is not respected as documented

### ISSUE THREAD

**Issue by bpasero** [microsoft/playwright#21846]
### System info
- Playwright Version: 1.27.1
- Operating System: macOS
- Browser: Electron
- Other info:

We are starting Electron in our CI with this:

```ts
const electron = await playwright._electron.launch({
	executablePath: configuration.electronPath,
	args: configuration.args,
	env: configuration.env as { [key: string]: string },
	timeout: 0
});

const window = await electron.firstWindow();
```

The `timeout: 0` option was only added recently to address timeout errors we would hit where the log shows:

```
[2023-03-21T13:16:29.991Z] Finished operation 'launch playwright (electron)' with error TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window" after 31298ms
```

So it seems to me `timeout: 0` is not disabling the timeout. We still see a timeout after 30 seconds.

**Comment by aslushnikov** [comment]
@bpasero the `timeout: 0` in the `electron.launch()` method is for the application launch; not for the first window to appear.

The `firstWindow()` method is actually throwing the error; it has a default timeout of 30 seconds that can't be configured as of today.

You can workaround this for now like this:

```ts
const electron = await playwright._electron.launch({
	executablePath: configuration.electronPath,
	args: configuration.args,
	env: configuration.env as { [key: string]: string },
	timeout: 0
});

let window = electron.windows()[0];
if (!window)
  window = await electron.waitForEvent('window',  { timeout: 0 });
```

**Comment by bpasero** [comment]
Great thanks for the workaround, will try that.
