### ISSUE TITLE
[BUG] Error thrown when loading PDF urls

### ISSUE THREAD

**Issue by chris-arrakis** [microsoft/playwright#21841]
**Context:**
- Playwright Version: 1.31.1
- Operating System: Mac (reproducible on Linux as well)
- Python version: 3.11.2 (also 3.10.10)
- Browser: Chromium
- Extra: None

**Code Snippet**

```python
url = 'https://www.africau.edu/images/default/sample.pdf' # Random PDF page from Google, with correct content-type

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page(
    response = page.goto(url)
    browser.close()
```

**Describe the bug**
I expect to be able to load the page, but it throws an error:
```
Error: net::ERR_ABORTED at https://www.africau.edu/images/default/sample.pdf
```

This has occurred with every PDF url I've tried. I was hoping to load and save the PDF for further processing, but can't get past this error when loading it.

**Comment by aslushnikov** [comment]
@chris-arrakis As you navigate to the PDF page:
- the navigation is aborted since it can't display PDF content
- Instead, a download is created.

So to work-around, you should:
- capture exception from the `page.goto`
- Use the [downloads api](https://playwright.dev/python/docs/downloads) to handle the browser download

Hope this helps!

**Comment by clemlesne** [comment]
For everyone, this seems to work:

```python
# Launch a new page
try:
    cached_res = await page.goto(
        timeout=1000 * 60,  # 1 minute
        url=url_clean,
        wait_until="load",  # Wait for "load" event, compatible with PWA apps
    )

# Try to download the PDF
except PlaywrightError as e:
    # Raise if no PDF in the URL
    if ".pdf" not in str(e):
        raise e

    # Download PDF
    full_content = await _handle_pdf(url_clean)

# Parse the DOM
else:
    full_content = await _handle_page(
        page=page,
        res=cached_res,
        url=url,
    )
```
