### ISSUE TITLE
[Question] How to use logical OR (||) with expect page.toHaveURL assertion (TS)

### ISSUE THREAD

**Issue by AdmiralHall** [microsoft/playwright#21858]
What's the best way to pass a logical "or" in an expect page `.toHaveURL` or `.toContain` param?  I need to ensure the page that the user is taken to is one of multiple possible urls (I'm using regex, but I could use a string if needed).

I've tried:
```await expect(this.page).toHaveURL("/tacos/" || "/pizza/");```
and 
```await expect(this.page).toHaveURL(("/tacos/") || await expect(this.page).toHaveURL("/pizza/"));```

But I keep failing here:
```            61 |         this.page.waitForURL;
    > 62 |         await expect(this.page).toHaveURL("/tacos/" || "/pizza/");
         |                                 ^
      63 |     }
      64 | }```

**Comment by aslushnikov** [comment]
@AdmiralHall just use the regex syntax:

```js
await expect(this.page).toHaveURL(/tacos|pizza/);
```

Hope this helps!
