### ISSUE TITLE
[Feature] Add api for manually start and stop video recording

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#21852]
Hi!
Could you add apis for manually start and stop video recording? We use the "single page pattern" with POMs and the video recording is not possible in that case. The api could look similar to the tracing api.

//Marcus

**Comment by aslushnikov** [comment]
This has been filed before as https://github.com/microsoft/playwright/issues/14258 - and is folded into https://github.com/microsoft/playwright/issues/4821

Please upvote https://github.com/microsoft/playwright/issues/4821 to bump its priority!
