### ISSUE TITLE
[BUG] returns empty while iterating

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#21851]
Checking for updates
Version 111.0.5563.64 (Official Build) (x86_64)

```javascript
for (const row of await page.getByTestId('dp-field-bid').locator('div').all())
   console.log("@@@@@@" + await row.textContent()); ---> it prints the value as expected.
```

```javascript
  for (const row of await page.getByTestId('dp-field-bid').locator('div').all()) {
            console.log("%%%%%%%%" + await row.textContent()); --> returns empty row here
        
            await page.locator('.react-select__value-container').click();
            await page.getByText('39 (3/20 at 10:41)', {exact: true}).click();
            await page.getByText(await row.textContent().toString(), {exact: true}).click();

            console.log("text:" + text)

            console.log("text1:" + text)
        }
```

Can you please explain why the second loop is returning empty record?

**Comment by ltsuda** [comment]
I'm not sure if this is the problem but do you think at least one `await page.getByTestId('dp-field-bid').locator('div')` is present or is always empty?

As from the comment below, `.all()` returns all elements present at the time it runs, so maybe it is a timing issue.
https://github.com/microsoft/playwright/issues/21628#issuecomment-1467087112

Or multiple `%` symbols are escaping something in the string?

**Comment by aslushnikov** [comment]
@InduKrish At the very least, we would need a minimal repro that we can run locally to reproduce this issue.

Could you please re-file following issue template? Thanks!
