### ISSUE TITLE
[BUG] playwright-chromium will not run if Travis caches node_modules

### ISSUE THREAD

**Issue by adroitwhiz** [microsoft/playwright#2186]
**Context:**
- Playwright Version: `playwright-chromium` 1.0.1
- Operating System: Linux
- Node version: 10.20.1
- Browser: Chromium
- Extra: Running in a Travis environment with npm caching enabled

**Code Snippet**

```javascript
const {chromium} = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch();
  // ... 
})();
```
And in `.travis.yml`:
```yaml
cache:
  directories:
    - node_modules
```

**Describe the bug**
The postinstall script for `playwright-chromium` (possibly `playwright` as well) saves Chromium to `~/.cache/ms-playwright`.

Because Travis caches `node_modules` [by default](https://docs.travis-ci.com/user/caching/#npm-cache) but *not* `.cache/ms-playwright`, the postinstall script is not run as `playwright-chromium` is already present in `node_modules`, but the Chromium binary does not exist as it was never cached, so it fails to launch with an `ENOENT` error.

[Here's a build log of this occurring.](https://travis-ci.org/github/LLK/scratch-render/jobs/685737870)

If the intended solution is to add `~/.cache/ms-playwright` to Travis' cached directories, that should be documented somewhere, but that solution strikes me as rather brittle considering you have to clear the Travis cache after installing Playwright for the first time and then hope the downloaded Chromium binary happens to stay in the cache.

**Comment by adroitwhiz** [comment]
I closed this because the [documentation](https://github.com/microsoft/playwright/blob/master/docs/ci.md) does mention caching, but upon reflection I don't think it's very clear.

It says at the very bottom that browser binaries will not be cached, but never indicates anywhere that this will cause Playwright to outright fail to run. To me it implies that the browser will simply be redownloaded every time. The example `.travis.yml` also does not include a working cache configuration.

**Comment by arjun27** [comment]
Thanks for calling this out, @adroitwhiz 

I tried replicating the Travis config [here](https://github.com/arjun27/pw-travis/blob/8e14f340d912726ae0d32b608485ca9c9eb82a6d/.travis.yml) ([build here](https://travis-ci.org/github/arjun27/pw-travis/builds/685821571)), and set `PLAYWRIGHT_BROWSERS_PATH=0` as an env variable to use the hermetic installation (which installs browser binaries inside `node_modules`). Link to [installation docs for reference](https://github.com/microsoft/playwright/blob/master/docs/installation.md#managing-browser-binaries).

```yml
language: node_js
dist: trusty
node_js:
  - 10
env:
  # install browser binaries in node_modules
  - NODE_ENV=production PLAYWRIGHT_BROWSERS_PATH=0
install:
- npm --production=false install
cache:
  directories:
    - node_modules
```

It seems that Travis caches one of `node_modules` or `$HOME/.npm` depending on repo structure ([docs](https://docs.travis-ci.com/user/caching/#npm-cache)), and that would influence whether the postinstall script are executed. I'll update the CI docs to work with both. Thanks again for the report.

**Comment by arjun27** [comment]
On further investigation, it seems that the behavior is happening due to a combination of factors
1. Travis auto-caches `node_modules` because it does not find package-lock.json in the repo. If the lockfile is available, Travis uses `$HOME/.npm`, which is the npm cache directory.
2. Running `npm install` (instead of `npm ci`) sees the node_modules dir, and does not run the postinstall step, causing the browser binary to not be available.

Thanks again for reporting this. I've opened #2192 to fix our docs and suggestions to fix this.
