### ISSUE TITLE
[Feature] add a trace option in the playwright conf to trace on all retries

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#21860]
Hi!
Today we use the option 'retain-on-failure' to get traces on all of our retries (actually all of the failing runs) but this also mean that we are tracing the whole time and this consumes resources. We run our tests in a pipeline with limited resources. In these cases it would be very handy with an option that only enables retries on retries but also traces in all the retries. 'on-first-retry' and 'retry-with-trace' only do tracing in the first retry. It would be ideal if 'retry-with-trace' did trace all the retries. Also since it's not mentioned here:
https://playwright.dev/docs/test-configuration#record-test-trace
I feel I can't file a bug for it.

I hope to see this anytime soon.

Cheers!
// Marcus

**Comment by aslushnikov** [comment]
We're open to a new `on-all-retries` option if you want to contribute a patch!

**Comment by marcusNumminen** [comment]
I can try :)

**Comment by marcusNumminen** [comment]
@aslushnikov I think I have a fix for this now but how can I build and pack (using npm pack) playwright so can test it in my local test project?

**Comment by aslushnikov** [comment]
@marcusNumminen if you have modern npm (e.g. v8+), you can simply install from our checkout:

```sh
# Create a new dummy npm package
mkdir tmp && cd tmp && npm init -y
# Assuming your playwright checkout is at $HOME/code/playwright, you can simply install playwright-test like this:
npm i ~/code/playwright/packages/playwright-test
```

Alternatively, you can package tgz files of playwright-core and playwright-test like this:

```sh
node utils/pack_package.js playwright-core pwc.tgz
node utils/pack_package.js playwright-test pwt.tgz
```
