### ISSUE TITLE
[Question] Change default context (or existing context) options 

### ISSUE THREAD

**Issue by zeekrey** [microsoft/playwright#21867]
Hey there 👋🏻

Is it possible to change the options of an existing context? I use the following code to connect via CDP and use the existing context:

```typescript
const browser = await chromium.connectOverCDP(process.env.URL || url || 'http://localhost:9222');
const context = browser.contexts()[0];
const page = context.pages()[0];
```

Now I want to:

1. Set `hasTouch` to `true`
2. Set `slowMo`

Does somebody know how to do this?

**Comment by mxschmitt** [comment]
This is not supported as of today. This is out of the scope for Playwright.

**Comment by mchudie** [comment]
I have encountered the same requirement where, when the page connected via CDP is in mobile mode, there is an issue with the inability to click.
