### ISSUE TITLE
[BUG] baseURL gets stripped if contains something more than domain

### ISSUE THREAD

**Issue by drabikowy** [microsoft/playwright#21864]
I have a multi-store shop, and each store view has it's store code in the url, like "https://mydomain.net/de", "https://mydomain.net/fr"
I would like to be able to test each store view, by providing different baseURL for the specific tests in a file. I'm using test.use({baseURL}) for that purpose. 

However, it seems like it does not work, and even if i change the baseURL in global config to contain my store code, it considers only the domain part, not full path. So page.goto('/') resolves always to `https://mydomain.net/` instead of `https://mydomain.net/{storeCode}/`

I read about possibilities about changing the baseURL when creating context, but it seems like an overkill for my purpose, where I just want to have different baseURLs for my stores.

### System info
- Playwright Version: [v1.31.2]
- Operating System: [macOS 13.2]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Reproduction

In playwright.config.ts try to use baseUrl

```
...
 use: {
            ...
            baseURL: https://my-domain.net/de,
            ...
        },
...
```
Then in any test, `page.goto('/')` navigation resolves to `https://my-domain.net/` instead what I expect - `https://my-domain.net/de/`

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
     ...
     use: {
            baseURL: "https://my-domain.net/de",
      },
    ...
});
```

**Test file**

```js
import { test, expect } from '@playwright/test';

test('should redirect to proper baseURL', async ({ page, baseURL }) => {
    console.log(baseURL); // shows proper base url "https://mydomain.net/de"
    await page.goto('/'); // we land at "https://mydomain.net/"
    await expect(page).toHaveURL('https://mydomain.net/de'); // Fails
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

full baseURL string should be treated as a baseURL

**Comment by JonMarbach** [comment]
I just started using Playwright and I was struggling with something similar, so I don't know if this will help... but try putting a slash at the end of your baseURL. Ultimately, I found that playing with the URL constructor in a browser console window let me experiment with different permutations of the baseURL and the goto URL.

**Comment by ltsuda** [comment]
@drabikowy, this is expected, as far as I know, as the `/de` is a `pathname` and not a part of the `hostname` url. So, the baseURL ends at `.net`

Please see the following comment to more details.
https://github.com/microsoft/playwright/issues/20637#issuecomment-1418805101

**Comment by drabikowy** [comment]
Hello, thx for your responses. 
I ended up with creating my Navigation class, which takes baseURL as an argument (since it's being passed correctly ¯\_(ツ)_/¯ )
```
export class NavigationActions {
    page: Page;
    baseURL: string;

    constructor(page: Page, baseURL: string) {
        this.page = page;
        this.baseURL = baseURL
    }

    async goTo(path) {
        await this.page.goto(`${this.baseURL}${path}`);
    }
}

```

Then I'm using it instead the page.goto() and I'm able to set this baseURL before each store-view tests, like

```
test.use({baseURL: "https://mydomain.net/de"}
test('Dummy', ({page, baseURL}) => {
    const navigationActions = new NavigationActions(page, baseURL);
    await navigationActions.goTo('/'); 
})
```
For now it does what I need. 
If I have more troubles, I'll try @JonMarbach ideas. 

But all in all, I'm not sure if this is expected behaviour or at least it's not documented well, since it's written 
 "// Base URL to use in actions like `await page.goto('/')`."
 
I would expect it to build url from what I pass there. (I'm migrating from cypress, there it works as intended).
So I'm keeping it open, and let the team close it if it does not make sense for them.

**Comment by mxschmitt** [comment]
This works as expected, since its following the [new URL constructor](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), see [here](https://playwright.dev/docs/api/class-testoptions#test-options-base-url). Closing by that.

**Comment by kmturley** [comment]
baseURL != rootURL

Base just means where do you want to start from.

GitHub pages do not start at the root url e.g.
https://username.github.io/my-site/

Also it is generally common to not include the trailing slash on urls:
https://username.github.io/my-site

**Comment by rkrisztian** [comment]
The behavior of `.goto()` closely resembles that of the JavaScript `new URL(path, base)` constructor. To ensure consistent results, it is recommended that the `baseURL` ends with a trailing slash.

For example, if you want to navigate to `http://testing.host.com/app/login`:

| `baseURL` | `goto` path | Actual URL |
| -- | -- | -- |
| `http://testing.host.com/app` | `login` | `http://testing.host.com/login` |
| `http://testing.host.com/app/` | `login` | `http://testing.host.com/app/login` |
| `http://testing.host.com/app` | `/login` | `http://testing.host.com/login` |
| `http://testing.host.com/app/` | `/login` | `http://testing.host.com/login` |
| `http://testing.host.com/app` | `./login` | `http://testing.host.com/login` | 
| `http://testing.host.com/app/` | `./login` | `http://testing.host.com/app/login` |
