### ISSUE TITLE
Additional Playwright Documentation For Async API Calls

### ISSUE THREAD

**Issue by zcabkle** [microsoft/playwright#21873]
I have already written up the issue and have been instructed to post the link here.

Access it here:
- https://github.com/microsoft/studentambassadors issue 177.
- Please see this issue https://github.com/microsoft/studentambassadors/issues/177 :)

**Comment by mxschmitt** [comment]
Hey! We unfortunately need more information to act on it. Can you provide us a small code snippets or preferable whole repository of whats not working with expected and actual outcome? This would help us a ton to understand more what you are trying to accomplish.

**Comment by aslushnikov** [comment]
@zcabkle I responded in the https://github.com/microsoft/studentambassadors/issues/177.
