### ISSUE TITLE
[BUG] Some playwright config values do not work

### ISSUE THREAD

**Issue by Derrbal** [microsoft/playwright#21878]
### System info
- Playwright Version: v1.31.2
- Operating System: Ubuntu 22.04
- Browser: Chromium

### Source code

**[Link to the GitHub repository with the repro](https://github.com/Derrbal/New-Folder)**

**Description**
In `playwright.config.ts` we have set custom viewport size and userAgent. However, in our tests when we check them, they are not being applied as expected. In the [Playwright documentation](https://playwright.dev/docs/test-configuration#explicit-context-creation-and-option-inheritance) it shows that global config should be applied for both tests. And we have enabled capturing video in both cases, but video is recorded only for "using fixture context" test.

`test/example.spec.ts`

```typescript
import { test, expect } from '@playwright/test';

test('using fixture context', async ({ page }) => {
  await page.goto('http://localhost:3030/login?pageSize=10');
  expect(await page.evaluate(() => window.innerWidth)).toBe(100);
  expect(await page.evaluate(() => navigator.userAgent)).toBe('some custom ua');
  await expect(page).toHaveURL('http://localhost:3030/login?pageSize=10');
});

test('manually created context', async ({ browser }) => {
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('http://localhost:3030/login?pageSize=10');
  expect(await page.evaluate(() => window.innerWidth)).toBe(100);
  expect(await page.evaluate(() => navigator.userAgent)).toBe('some custom ua');
  await expect(page).toHaveURL('http://localhost:3030/login?pageSize=10');
});
```
`playwright.config.ts`

```typescript
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 60 * 1000,
  expect: {
    timeout: 10000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    actionTimeout: 0,
    userAgent: 'some custom ua',
    viewport: { width: 100, height: 100 },
    trace: 'on',
    screenshot: 'on',
    video: 'on',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

**Steps**
- Run the tests

**Expected**
Tests are passing 
Video is created for both tests

**Actual**
Tests are failing
Video is created only for "using fixture context" test

**Comment by aslushnikov** [comment]
Closing as per Max's response. Please feel free to file more issues if you think we can be helpful!
