### ISSUE TITLE
[Question]: Custom test id attr

### ISSUE THREAD

**Issue by mturoci** [microsoft/playwright#21877]
### Your question

I would like to configure custom date test attribute, but the [docs](https://playwright.dev/python/docs/locators#set-a-custom-test-id-attribute) seem to confuse me a bit. It shall be possible to specify via a test config (not able to find anything related to this, a hyperlink would solve this) or via `playwright.selectors.set_test_id_attribute` which is also not clear where it's coming from.

After a bit of digging, I found out the `playwright` obj is a fixture so maybe something that could be better described in the docs as well?

**Comment by mxschmitt** [comment]
Yes, the docs are currently wrong for the language ports. In Python you can use e.g. the `playwright` fixture and use it to call `playwright.selectors.set_test_id_attribute("...")`. The easiest is to do it inside a `session` fixture with `auto=true` so its only done once when you are using pytest-playwright.

**Comment by mxschmitt** [comment]
We have a feature request for it here: https://github.com/microsoft/playwright-pytest/issues/69

**Comment by aslushnikov** [comment]
Merging into https://github.com/microsoft/playwright-pytest/issues/69
