### ISSUE TITLE
how do I wait for the entire locator to load?

### ISSUE THREAD

**Issue by alexeyKoshelevJava** [microsoft/playwright#21871]
by one selector I get a lot of elements. how do I wait for all the elements related to the locator to load? Thanks!

**Comment by mxschmitt** [comment]
Waiting for one locator: [`await locator.waitFor()`](https://playwright.dev/docs/api/class-locator#locator-wait-for).

Waiting for multiple locators by count: [`await expect(locator).toHaveCount(42)`](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-count).

There is no thing like "elements related to the locator to load" so above would be the right way to do, to be specific.
