### ISSUE TITLE
[BUG] getBytext and click by Index is not working.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#21874]
Checking for updates
Version 111.0.5563.64 (Official Build) (x86_64)

1.  It is not working, can you please let me know how to get this working, not sure how i can use escape character here? Please advise?
```javascript
 await page.locator('.react-select__value-container').click();
 await page.getByText('39 (03/20 at 10:41)', { exact: true }).click();  
```

2. I tried clicking on the option using the index, and it is not working either, Please advise.
```javascript
 await page.locator('.react-select__value-container').click();
 await page.getByTestId('dp-field-bid').locator('div').nth(0).click(); 
```

if i execute all the elements, it prints all the records like below, however when i execute getByText() or by Index it is not working.
```javascript
 await page.locator('.react-select__value-container').click();
  for (const row of await page.getByTestId('dp-field-bid').locator('div').all())
            console.log("@@@@@@" + await row.textContent());
```

@@@@@@40 MOST RECENT
@@@@@@39 (03/20 at 10:41)
@@@@@@38 (03/20 at 10:26)
@@@@@@37 (03/20 at 10:26)
@@@@@@36 (03/20 at 10:26)
@@@@@@35 (03/20 at 10:26)

![image](https://user-images.githubusercontent.com/113629123/226927954-b2a0107b-4f73-47ee-8477-c992b7e5f5b8.png)
![image](https://user-images.githubusercontent.com/113629123/226928027-20cc424d-0cd4-4fc9-a9c8-40bfaaa26739.png)

**Comment by aslushnikov** [comment]
@InduKrish thank you for filing, however, the report is missing the most important bit: a small code snippet / github repo that we can run locally to reproduce and debug this issue.

Could you please re-file following the issue template? Thanks!
