### ISSUE TITLE
[BUG] Extensions Used by CDP-Browser dont work on new_page

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#21872]
### System info
- Playwright Version: 1.31.1
- Operating System: Windows
- Browser: CDP-Spawned Chrome
- Python version: 3.10

### Source code

```py
from playwright.sync_api import sync_playwright
import tempfile
import subprocess

cdp_port = "9222"
executable_path = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
extension_path = r"C:\Users\Admin\Documents\GitHub\WebRTC-Leak-Shield"
temp_user_data_dir = tempfile.mkdtemp()
flags = [f"--disable-extensions-except={extension_path}", f"--load-extension={extension_path}"]

subprocess.Popen([executable_path, f"--remote-debugging-port={cdp_port}", f"--user-data-dir={temp_user_data_dir}", *flags])

playwright = sync_playwright().start()
main_browser = playwright.chromium.connect_over_cdp(f"http://localhost:{cdp_port}")

page = main_browser.new_page()
page.goto("https://webbrowsertools.com/test-webrtc-leak/") # Extension doesnt load/work on this New Page
page.wait_for_timeout(10000)
```

**Steps**
- Run the Test

**Expected**

The Extension (in this case a WebRTC Defender) should load and work on new pages spawned under the browser.

**Actual**

The Extension doesnt load/work.

**Comment by aslushnikov** [comment]
@Vinyzu is this specific to the extension? Can you please re-file with a small github repo that I can clone and reproduce the issue locally? 

Thanks!

**Comment by Vinyzu** [comment]
@aslushnikov Notify me when i can delete the repo again (to keep my github clean :D)

https://github.com/Vinyzu/extension-test-repo
Using https://chrome.google.com/webstore/detail/return-youtube-dislike/gebbhagfogifgggkldgodflihgfeippi?hl=de
