### ISSUE TITLE
[Question] Loading Chrome Extension always or via Codegen

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#21888]
1. Is there any CLI command for Chromium load a certain extension via codegen?
2. Can I load an extension by changing something in the config so that codegen always loads it?
3. Where is codegen picking up the config from?

I can only create scripts with the extension loaded. I am not able to load the extension with the launched Chromium because for some reason Settings > Extensions is disabled.

Also, I will have to resort to xapth if I can't get this working :(

I would be happy with any solution that would help me out.

**Comment by aslushnikov** [comment]
> Is there any CLI command for Chromium load a certain extension via codegen?

@siddharth2023 you cannot launch codegen with the extension. 

> Can I load an extension by changing something in the config so that codegen always loads it?

This is not possible also.

You best bet would be to do a snippet that loads extension, following the https://playwright.dev/docs/chrome-extensions, and then launch this snippet with `PWDEBUG=1` env variable to open inspector.

Hope this helps!

**Comment by siddharth2023** [comment]
I was able to achieve this with the latest version of PW with the flag --ui. :) Thanks though.

**Comment by sghsri** [comment]
@siddharth2023 can you describe in more detail what you did to get this working? Thanks!
