### ISSUE TITLE
[BUG] pnpm exec playwright codegen --browser firefox doesn't wrok

### ISSUE THREAD

**Issue by annymosse** [microsoft/playwright#21883]
### System info
- Playwright Version: [v1.31.2]
- Operating System: [Ubuntu 22, NixOS 22.11]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  timeout: 30 * 1000,
  expect:
    timeout: 5000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    actionTimeout: 0,
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**
basic test example provided by playwright (fresh project with fresh installation).

**Steps**
create a fresh new project.
```json
{
  "package.json":"👇",
  "name": "pwtest",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.31.2"
  }
}
```

```
pnpm exec playwright codegen --browser ff
```

**Expected**
expecting the firefox browser to open.

**Actual**

[Describe actual behavior]
it opens chromium.

**Comment by aslushnikov** [comment]
@annymosse works for me like a charm. It looks like the `--browser ff` is not propagated to the `playwright codegen` command.

Could you try the following:

```sh
$ mkdir tmp && cd tmp && npm init -y && npm i @playwright/test
$ cat <<'EOF' >a.spec.ts
import { test, expect } from '@playwright/test';

test('shoudl work', async ({ page }) => {
  console.log(await page.evaluate(() => navigator.userAgent));
});
EOF
$ pnpm exec playwright test --browser firefox
```

Does this work for you?

**Comment by annymosse** [comment]
@aslushnikov it works well , I the issue is related to my pnpm cache after removing it and use npm instead of pnpm such as you mentioned.
thanks for your help.
