### ISSUE TITLE
[QUESTION]: User and App Context on Component Testing

### ISSUE THREAD

**Issue by imartinflores** [microsoft/playwright#21882]
Hi guys! I have some components in the App that are rendered with UserContext and AppContext using react testing library, I'd like to do the same with Playwright Component but I am struggling with it. This is what I am trying to replicate:

React-Test:

```
function renderWithContext() {
        return render(
            <AppContext.Provider value={{}}>
                <UserContext.Provider value={{}}>
                    <TestForm content={content} dropdownItems={[{ code: 'Test' }]} />
                </UserContext.Provider>
            </AppContext.Provider>,
        );
    }
```
How should I do that?
I have tried with mount() but it seems like I can't, I get "Maximum call stack size exceeded". If I only try to render the TestForm , I need to define useContext() as it is used for that component. Is there anyway to replicate this using mount() in Pw ?
Any help will be appreciated, thanks!

**Comment by aslushnikov** [comment]
@imartinflores I'm not sure exactly I follow the issue here since I'm not very familiar with `renderWithContext()`, but if your component requires some pre-setup global state, than you should put it in the `playwright/index.ts`: https://playwright.dev/docs/next/test-components#playwrightindexts

Would it help?

**Comment by imartinflores** [comment]
hey @aslushnikov  ! sorry, my bad, should've explained more.
The renderWithContext() is nothing else that a function to call the render(), so it is used in the react tests as:

`var component = renderWithContext();`

When I try to replicate that in Playwright using mount():

```
var component = mount(<AppContext.Provider value={{}}>
                <UserContext.Provider value={{}}>
                    <TestForm content={content} dropdownItems={[{ code: 'Test' }]} />
                </UserContext.Provider>
            </AppContext.Provider>
          );
```
          
It throws that error  "Maximum call stack size exceeded".

If I try mounting only the TestForm component it throws another error saying "Cannot destructure property ... because UserContext is undefined".

So seems like I need to pass or create that User and App Contexts and that's what I am trying to find out, I am not very experienced with it.

I assume it is because the component is using this:

`const { appInsights } = useContext(AppContext);`

Is there any way to replicate something like this in PW Component?

Thanks a lot!

**Comment by aslushnikov** [comment]
@imartinflores  Ah, it looks like you need the `beforeMount` hook.

Check out how it's done here: https://github.com/microsoft/playwright/issues/21602

**Comment by imartinflores** [comment]
Thanks @aslushnikov , I will take a look at that, we can close this if you prefer, if I find a real issue will file it :) - thanks for pointing me to that example!

**Comment by aslushnikov** [comment]
Closing then!
