### ISSUE TITLE
[Feature] Ability to define and change the page title or id that is recorded into a har file

### ISSUE THREAD

**Issue by damies13** [microsoft/playwright#21899]
Referring to the documentation for [browser.new_page()](https://playwright.dev/python/docs/api/class-browser#browser-new-page) and the arguments related to har files (e.g. record_har_path) I don't see any option to influence the page title or id  I believe playwright just uses the HTML title tag for the title and generated the id? 

From my experiments is seems that playwright uses:
- the change of HTML title to identify a new page in the har file
-  or closing a page and opening a new one (browser window/tab) within a browser context to identify a new page in the har file

The problem for me is when dealing with applications where the title remains the same on all screens of the application, as a tester we can't control the application design especially with vendor supplied applications.

I would like to be able to do something like the following:
- open a new page with the `record_har_path` option set
- _tell playwright to start a new page with the title or id of "login screen"_
- open the login screen
- _tell playwright to start a new page with the title or id of "application login"_
- enter username, password and click login (form submit)
- wait for login to finish and confirm the main application screen has loaded
- _tell playwright to start a new page with the title or id of "hr module"_
- click the link to the hr module
- _tell playwright to start a new page with the title or id of "new employee"_
- click the link to create employee
- _tell playwright to start a new page with the title or id of "create new employee"_
- enter employee details, name, dob, etc and click create button (form submit)
- _tell playwright to start a new page with the title or id of "navigate home"_
- click link to the main application screen
- _tell playwright to start a new page with the title or id of "logout"_
- click link to logout of the application

At the moment when I do this it is all being recorded into the same page, so it's very difficult to know which requests belong to which part of the business process. I can't simply close the page and open a new page as it will break the process and I can't do the form submits.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by damies13** [comment]
I thought I had clearly explained why it was needed, no clarification was sought? I would have been happy to answer any questions asked,

I just thought the delay in action on this request was normal for a open source project with limited resources which is why I have not been pushing for a quick resolution, I don't want to be disrespectful.

Dave.
