### ISSUE TITLE
[BUG] trace viewer crashes when trace contains an invalid selector

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#21894]
### System info
- Playwright Version: 1.30.0
- Operating System: windows 10
- Browser: firefox, chromium

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```ts
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test'

const config: PlaywrightTestConfig = {
    use: {
        trace: 'on'
    },
}

export default config

```

**Test file (self-contained)**

```ts
import { test } from '@playwright/test'

test('page loads', async ({ page }) => {
    await page.goto('https://google.com')
    await page.waitForSelector('/')
})
```

**Steps**
- run test
- run `playwright show-trace` with the path to the trace file or upload it to trace.playwright.dev

**Expected**

trace file loads, with some sort of handling on the step with the invalid selector

**Actual**

blank screen with errors in the console:
![image](https://user-images.githubusercontent.com/57028336/227069246-cd09e978-0675-4c73-9f23-40a7c7688fb2.png)
```
Uncaught (in promise) Error: Unexpected token "/" while parsing selector "/"
```

**Comment by Nav-2d** [comment]
Maybe related: https://github.com/microsoft/playwright/issues/21832

**Comment by DetachHead** [comment]
looks like the same issue, closing this as a duplicate
