### ISSUE TITLE
[BUG] `--ui` fails to open with error reading mainFrame from an undefined `this._page`

### ISSUE THREAD

**Issue by skvale** [microsoft/playwright#21897]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- node: v18.12.1

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/skvale/playwright-repro

or

**Config file**

```js
// playwright.config.ts
/** @type {import('@playwright/test').Config} */
const config = {
  updateSnapshots: 'missing',
  timeout: 20000,
  webServer: {
    command: 'pnpm build && pnpm serve',
    url: 'http://localhost:3003/',
    reuseExistingServer: false,
    timeout: 20000,
  },
  workers: 8,
  retries: process.env.CI ? 5 : 0,
  projects: [
    {
      name: 'test',
      use: {
        javaScriptEnabled: true,
      },
    },
  ],
  use: {
    baseURL: 'http://localhost:3003/',
    screenshot: 'only-on-failure',
    trace: 'retain-on-failure',
    launchOptions: {
      ignoreDefaultArgs: ['--hide-scrollbars'],
    },
  },
};
export default config;
```

**Test file (self-contained)**

```js
import {expect, test} from '@playwright/test';

test.describe.parallel('Site', () => {
  test('shows home content', async ({page}) => {
    await page.goto('/');
    await expect(page.getByText('@2023 All rights reserved')).toBeVisible();
  });
});
```

**Steps**
- pnpm install
- pnpm test

**Expected**

`playwright test test.playwright.test.ts --ui` loads Playwright in UI mode

**Actual**

```
> playwright test test.playwright.test.ts "--ui"

/Users/me/project/node_modules/.pnpm/@playwright+test@1.32.0/node_modules/@playwright/test/lib/runner/uiMode.js:159
    this._page.mainFrame().evaluateExpression(dispatchFuncSource, true, message).catch(e => this._originalStderr(String(e)));
               ^

TypeError: Cannot read properties of undefined (reading 'mainFrame')
    at UIMode._dispatchEvent (/Users/me/project/node_modules/.pnpm/@playwright+test@1.32.0/node_modules/@playwright/test/lib/runner/uiMode.js:159:16)
    at Timeout._onTimeout (/Users/me/project/node_modules/.pnpm/@playwright+test@1.32.0/node_modules/@playwright/test/lib/runner/uiMode.js:69:14)
    at listOnTimeout (node:internal/timers:564:17)
    at processTimers (node:internal/timers:507:7)
```

### Additional info:

Link to the line that was failing
https://github.com/microsoft/playwright/blob/d10fac4f6a0dfeb3577eec6cdff7ec3bdc843c01/packages/playwright-test/src/runner/uiMode.ts#L152

Wrapping it in an `if (this._page)` seems to work

Message looks like this `{ message: { method: 'listChanged' } }`, perhaps the output from the build command is triggering events before the page is initialized

**Comment by bojanbass** [comment]
I'm experiencing exactly the same issue.

**Comment by azadnsu** [comment]
I am experiencing the same issue!

**Comment by mxschmitt** [comment]
Internal: investigation note: Issue is that the global setup modifies files, file watcher kicks in but global setup didn't finish yet. Will open a PR with a fix for it.
