### ISSUE TITLE
[BUG] UI mode doesn't show live trace when beforeEach is used to make an API call

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#21895]
### System info
- Playwright Version: 1.32
- Operating System: macOS
- Browser: Chromium
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ request }) => {
  const test = await request.get(`https://catfact.ninja/fact`);
  expect(test.ok()).toBeTruthy();
});

test('some steps', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.waitForTimeout(5000)
  await expect(page).toHaveTitle(/Playwright/);
});
```

**Steps**
- Run the test using UI watch mode and observe the live trace

**Expected**
The live trace is rendered as the test runs

**Actual**
The live trace is not rendered as the test runs.

In our framework implementation, we make api call to create a new workspace (in beforeEach block) in every test

**Comment by aditya-sriram** [comment]
Hello. I am a student in EECS 481 at the university of Michigan and I have an assignment to contribute to an open source project on GitHub. I have programming experience in typescript and JavaScript. I have read the issue closely, familiarized myself with the codebase and read the contribution guidelines. I would like to work on this issue.
