### ISSUE TITLE
[BUG] Webkit does not initiate download for `download` anchors with `data` or `blob` `href` schemes

### ISSUE THREAD

**Issue by flakey-bit** [microsoft/playwright#21892]
### System info
- Playwright Version: [v1.28.0]
- Operating System: Windows 10
- Browser: Webkit (Windows)

### How to reproduce

1. Open the Playwright webkit browser `Playwright.exe` (for me it was in `%LOCALAPPDATA%\ms-playwright\webkit-1735`
2. Open the inspector
3. Paste the following into the <body> element

```html
<a download="SomeFile.txt" href="data:text/plain;charset=utf8;,hello world">Download!</a>
```

![image](https://user-images.githubusercontent.com/4413825/227056839-a868037d-10b5-4acc-b3e3-ef425b8b76e4.png)

4. Click on the link within the PlayWright browser. Nothing happens.

![image](https://user-images.githubusercontent.com/4413825/227056946-59fa4a2b-179a-42c3-b0a6-eb169472ac81.png)

**Expected**

File download is initiated

**Actual**

No observable behaviour

**Comment by aslushnikov** [comment]
@flakey-bit There's no visual indication of the download, but it actually happens.

Here's the snippet:

```ts
import { webkit } from 'playwright';

const browser = await webkit.launch({ headless: false });
const page = await browser.newPage();
await page.setContent(`
  <a download="SomeFile.txt" href="data:text/plain;charset=utf8;,hello world">Download!</a>
`);
page.on('download', () => {
  console.log('Download started!');
});
```

Once you run the snippet, click "Download" link with your mouse, and you'll see the `Download started!` in the console.

**Comment by flakey-bit** [comment]
@aslushnikov 

Thanks so much for taking a look at this (and so quickly!). 

Our _actual_ 
test looks like this:

```typescript
  // Arrange
  const downloadLink = page.getByRole("link").filter({ hasText: "Download!" });

  // Act
  const [download] = await Promise.all([
    page.waitForEvent("download"),
    downloadLink.click()
  ]);

  // Assert
  expect(download.suggestedFilename()).toBe("SomeFile.txt");
```

When running against Webkit we see the following:

```
    Test timeout of 30000ms exceeded.

    page.waitForEvent: Page closed
    =========================== logs ===========================
    waiting for event "download"
    ============================================================

      706 |           // Act
      707 |           const [download] = await Promise.all([
    > 708 |             page.waitForEvent("download"),
          |                  ^
      709 |             downloadLink.click()
      710 |           ]);
      711 |
```

other browsers (Chromium / FireFox) are **fine**.

Note that if we register an event listener for `download` before the promise stuff

```typescript
  // Arrange
  const downloadLink = page.getByRole("link").filter({ hasText: "Download!" });

  // NEW EVENT LISTENER ADDED
  page.on('download', () => {
    throw new Error("We hit the download listener");
  });

  // Act
  const [download] = await Promise.all([
    page.waitForEvent("download"),
    downloadLink.click()
  ]);
```

we don't see the expected exception - it still times out waiting for event "download". 

Compare with the output for Firefox / Chromium:

```
    Error: We hit the download listener

      684 |
      685 |           page.on('download', () => {
    > 686 |             throw new Error("We hit the download listener");
          |                   ^
      687 |           });
      688 |
      689 |           // Act
```

It makes no difference whether throwing an exception or using `console.log`.

I suspect the problem may be that `page.waitForEvent("download")` is running **synchronously** (rather than returning a promise)?

**Comment by flakey-bit** [comment]
This might be related to https://github.com/microsoft/playwright/issues/19939

**Comment by flakey-bit** [comment]
@aslushnikov I've tested under latest (1.32.1) and can confirm the bug is still present 😢

**Comment by aslushnikov** [comment]
@flakey-bit  ok, so we will need a repro. Any chance you can create a small code snippet / github repository that reproduces the issue? This way we'll be able to debug & fix it.

**Comment by flakey-bit** [comment]
@aslushnikov if you mean a failing Playwright test, I'm happy to - the pieces are all there in this issue anyway.

Do you by any chance have a repo I can fork (in which to add the failing test)?

**Comment by flakey-bit** [comment]
Hey 

@aslushnikov 

I've opened a repo for reproducing this issue: https://github.com/flakey-bit/playwright-21892

![image](https://user-images.githubusercontent.com/4413825/228085087-c0ea22e0-a8f2-4ee3-8090-af74402121b7.png)

```
PS C:\eddie\playwright-21892> yarn playwright test
yarn run v1.22.5
$ C:\eddie\playwright-21892\node_modules\.bin\playwright test

Running 3 tests using 3 workers
  1) [webkit] › example.spec.ts:3:5 › GH-21892 ─────────────────────────────────────────────────────

    Test timeout of 30000ms exceeded.

    Error: page.waitForEvent: Page closed
    =========================== logs ===========================
    waiting for event "download"
    ============================================================

       9 |   // Act
      10 |   const [download] = await Promise.all([
    > 11 |     page.waitForEvent("download"),
         |          ^
      12 |     downloadLink.click()
      13 |   ]);
      14 |

        at C:\eddie\playwright-21892\tests\example.spec.ts:11:10

  1 failed
    [webkit] › example.spec.ts:3:5 › GH-21892 ──────────────────────────────────────────────────────
  2 passed (32.2s)

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.
```

Please let me know if you need further info.

**Comment by aslushnikov** [comment]
Thank you, I can reproduce this on Windows Github Actions workflow: https://github.com/aslushnikov/playwright-21892/actions/runs/4548535301/jobs/8019664128

Over to Yury
