### ISSUE TITLE
[Feature] Allow more fine grained control over the PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD functionality

### ISSUE THREAD

**Issue by nils-christian** [microsoft/playwright#21908]
Hi,

In playwright there is currently the environment variable _PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD_ to skip the browser download. In our use case we are using Testcontainers to run the UI tests via _connectOverCDP_. This means that we do not need the browsers. However, we still want to record videos which requires _FFmpeg_ to be downloaded. Both aspects cannot be seperated. 

It would be nice to have separate environment variables to block the download of browsers and to block the download of _FFmpeg_.

If we take this a step further, it would maybe even useful if one could allow only the download of specific browsers. For instance, if we want to run our UI tests with chrome - why should playwright download Firefox etc. as well?

Thank you and best regards,

  Nils

**Comment by nils-christian** [comment]
Hi @mxschmitt,

I should have mentioned: We are working with Java, so we have only the playwright Maven module.

**Comment by yury-s** [comment]
You can combine PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD env variable and installing ffmpeg via command line interface:

```bash
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install ffmpeg"
```
will that work for you?

**Comment by nils-christian** [comment]
Well, this might work, but this is (frankly speaking) an unly workaround. I would rather see this as a missing feature, as the behaviour of the flag is rather weird in my opinion. Is there a chance to contribute such a thing or is too deep in the playwright core?

**Comment by aslushnikov** [comment]
@nils-christian we don't want to introduce more environment variables unless there's a very strong push from the community. I'd recommend sticking with Yury's workaround for now; that's what we recommend in all the languages.
