### ISSUE TITLE
[Question : File Watcher Automation using Playwright]

### ISSUE THREAD

**Issue by ravipratap8** [microsoft/playwright#21904]
Hi There,

Hope You are doing well.
I have one quick about the Automation of file watcher using Playwright-TypeScript
like opening a network Drive, copying a file from the source, and placing it back in the destination
can you please give some clue

**Comment by mxschmitt** [comment]
Does does not look web or end-to-end testing specific, could you elaborate more what you are trying to do?

**Comment by aslushnikov** [comment]
I agree with Max, this doesn't look like an issue with Playwright and doesn't require any action from the Playwright team.

I'd recommend asking this kind of questions on https://aka.ms/playwright/discord
