### ISSUE TITLE
[devops] Travis CI caching improvements

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2191]
While investigating #2186, I noticed that our Travis configuration is not working as intended. Since this configuration is a part of the docs for users, this impacts more than just this repo. Documenting learnings to be sure I'm not missing something.

Current config:
```yml
install:
- npm ci

cache:
  directories:
  - node_modules
```

What is going on right now:
1. The custom caching config (shown above) restores the node_modules directory before executing build steps.
1. This custom logic overrides the default behavior of Travis - which is to auto-cache the `$HOME/.npm` directory ([Travis docs](https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#caching-with-npm)).
1. `npm ci` deletes the `node_modules` directory before running (see `npm WARN prepare removing existing node_modules/ before installation` in build logs), which means that the custom caching is not helpful.
1. `npm ci` runs the post-install hooks, and downloads the browser binaries.

Suggested improvements:
1. Remove `node_modules` caching in travis yml since it's not used, and let Travis run default NPM caching.
2. Add caching for browser directories (different for Linux and OS X) to prevent new browser downloads. However, Travis docs suggest that "files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source" ([source](https://docs.travis-ci.com/user/caching#things-not-to-cache)). This suggests browser caching might only be a minor win.

**Comment by aslushnikov** [comment]
> Remove node_modules caching in travis yml since it's not used, and let Travis run default NPM caching.

Fair. #2215

> Add caching for browser directories (different for Linux and OS X) to prevent new browser downloads. However, Travis docs suggest that "files that are quick to install but slow to download do not benefit from caching, as they take as long to download from the cache as from the original source" (source). This suggests browser caching might only be a minor win.

Interesting. Looks like their downloading from their own S3, it might be that our CDN is even faster. The only thing that we currently do sub-optimally is downloading one-browser-at-a-time; once we switch to parallel download (#2216), we might be even faster. 

So let's start with removing travis caching.
