### ISSUE TITLE
[BUG]: UI Mode light mode showing check boxes in dark color

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#21917]
### System info
- Playwright Version: 1.32
- Operating System: Mac
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ x ] I provided exact source code that allows reproducing the issue locally.

test('checkboxes should be nicer in light mode when system is set to dark', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});

**Steps**
- set system to dark mode
- Open UI mode
- Toggle light and dark mode

**Expected**

check boxes should not be dark when in light mode

**Actual**

<img width="308" alt="Screenshot 2023-03-23 at 13 58 17" src="https://user-images.githubusercontent.com/13063165/227211523-e9743476-701c-4e64-b582-f7c6747b0b25.png">

**Comment by mxschmitt** [comment]
Similar topic is about the window header, that its not controlled by the Playwright dark mode setting and its controlled instead of the system dark mode setting.

**Comment by pavelfeldman** [comment]
Not sure there is anything I can do about it w/o re-rendering the native controls.
