### ISSUE TITLE
[BUG] Initialised process.env var is not visible in globalTeardown using project dependency

### ISSUE THREAD

**Issue by MichalFidor** [microsoft/playwright#21914]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2.1] (but I assume on all system is the same)
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/MichalFidor/playwright-bug

**Steps**
- Execute the tests by `npx playwright test`

**Expected**
We should be able to have access to the all `process.env` in `globalTeardown` which were created in the first test project. 

**Actual**
At the moment the `process.env` are not accessible in the `globalTeardown` step
![bug](https://user-images.githubusercontent.com/42964298/227182393-c3d1f184-8449-4a4c-b2ae-e9c510c705dc.png)

**Comment by dgozman** [comment]
After some discussion, we decided that mixing up `deps` and `globalSetup`/`globalTeardown` is the wrong thing to do. For now, the right fix seems to be a "teardown" project that will teardown the "setup" project at the end. Details are not finalized yet.

**Comment by dgozman** [comment]
@MichalFidor Well, this will not work quite as you expect, because "Teardown project" is not going to run if you filter your tests somehow. But we are thinking for an API addition, somewhere along these lines.

**Comment by MichalFidor** [comment]
@dgozman Ok, thank you for the info! So I'll need to wait. At the moment I'm using the `globalSetup` but with this solution, there are different issues to solve.

**Comment by Abhirocks889** [comment]
Hello @MichalFidor were you able to resolve this issue ? Thanks
