### ISSUE TITLE
[Question]How can i use explicit wait for more the 45seconds in Playwright with Java

### ISSUE THREAD

**Issue by Snehaveeranna** [microsoft/playwright#21913]
Also, it is not identifying elements even with 30sec of autowait. Any suggestion or workaround

**Comment by aslushnikov** [comment]
> How can i use explicit wait for more the 45seconds in Playwright with Java 

@Snehaveeranna You can configure timeout with the [`setDefaultTimeout`](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-set-default-timeout) method. 

> Also, it is not identifying elements even with 30sec of autowait. Any suggestion or workaround

Most likely this is a bug in your code. Try asking out for help on StackOverflow or on https://aka.ms/playwright/discord

If you do think that's a playwright issue, please re-file with a repro that we can run & debug locally.
