### ISSUE TITLE
[BUG] `window.open` with `javascript:` scheme never fires `popup` event

### ISSUE THREAD

**Issue by 53n4d89** [microsoft/playwright#21912]
Hi there, this is a simple python function:
```py
import asyncio
from playwright.async_api import async_playwright


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        
        # Navigate to the page with the XSS payload
        async def handle_popup(popup):
            #page.on("dialog", lambda dialog: dialog.accept())
            print(popup)

        page.on("popup", handle_popup)
        
        url_with_payload = "https://public-firing-range.appspot.com/urldom/location/hash/window.open#javascript:alert('XSS')"
        await page.goto(url_with_payload)
        href = await page.evaluate('() => window.location.href')        
        print(href)
        
        # Close the browser
        await browser.close()

asyncio.run(main())
```
So, if you run this code, you will see that page.goto(url_with_payload) will open the url, because xss payload is already attached to it, it will open popup as a new tab with xss alert. The problem here is detecting that alert. Somehow i should be able to close that alert, and than to close the popup with some info.. i tried it with: page.on("dialog", lambda dialog: dialog.accept()) inside handle_popup function, and many other ways, but i was unable to close that alert.. 

I'm not sure does this already exist or not, but i would be so grateful if it already exist to give me some hints, or to explain somehow how to do it. 

Thanks in advance..

**Comment by aslushnikov** [comment]
NOTE: this reproduces on all browsers. 
Javascript version:

```ts
import { chromium, firefox, webkit } from '@playwright/test';

const browser = await chromium.launch({ headless: false });
const page = await browser.newPage();
// subscribe to all kinds of events
page.on('popup', () => { console.log('page popup'); });
page.context().on('popup', () => { console.log('context popup'); });
page.on('dialog', () => { console.log('page dialog'); });

const url = `https://public-firing-range.appspot.com/urldom/location/hash/window.open#javascript:alert('XSS')`;
await page.goto(url);
```

The reason seems to be that page's javascript dialog stalls page's event loop, so Playwright initialization calls stall.

This is technically a bug, but one with a very narrow scope. Marking as P3.

**Comment by 53n4d89** [comment]
Fixing this would be very helpful, not only for creating dast tools, but also for web shops and similar industries.. If there's just an option to detect, than accept this dialog, dismiss it or simulating click or enter.. that would solve the problem..

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
