### ISSUE TITLE
[Question] Proxy bypass not working?

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright#21916]
Hi there i have a question about the "Proxy" object.

proxy: {
      server: "url:port",
      bypass: ".domain.org, .com, .domain.subdomain.com",
      username: "username",
      password: "password",
    },

The bypass is not working and i get a timeout. In your documentation there is this information:
Optional comma-separated domains to bypass proxy, for example ".com, chromium.org, .domain.com".

But it dont works behind my company proxy. Did i miss something?

In Postman when I'm setting the proxy bypass with
*.domain.com
*.domain.subdomain.com

it works perfectly but in playwright i get a timeout when using the request fixture and set the proxy in the playwright.config.ts file.

Is it because of the fixture not using the config?

**Comment by aslushnikov** [comment]
@Kranael the `page.request` is using the proxy settings that you set up in config. If you're using just the `request` fixture, than it doesn't use the `proxy` settings in the config.

Which one do you use?

You can always try creating your own `APIRequestContext` with proper proxy settings and see if it works: https://playwright.dev/docs/next/api/class-apirequest#api-request-new-context-option-proxy

**Comment by Kranael** [comment]
@aslushnikov thank you very much for confirmation and the information.

I have a question now -> Is there a reason to let the request fixture not use global config?

So now i know why it works when we set up a context but not with the fixture. I know i can modify or even create a new fixture but i thought that the config is always used from your default fixtures baked in the framework. Why not the "request" fixture?

**Comment by aslushnikov** [comment]
@Kranael actually, which version of Playwright do you use? It turns out we actually use proxy settings from config for the `request` fixture in 1.32. 

Can you try with Playwright 1.32?

**Comment by Kranael** [comment]
├── @playwright/test@1.32.1
├── @types/node@18.15.3
└── dotenv@16.0.3

I was on 1.31 and updatet to 1.32 but same effect. Timeout after 30sec so the request dont use the proxy bypass.

We called the requestContext and filled the proxy settings without the config and it works.

**Comment by aslushnikov** [comment]
@Kranael  can you please show your config and an example test how you issue the API request?

**Comment by Kranael** [comment]
@aslushnikov

![29-03-2023_14-58-33](https://user-images.githubusercontent.com/55143610/228543742-7a5cdb9e-21bb-4444-8adf-32446cd1e44d.png)

This test works as expected because we define here the proxy and use request.newContext without the fixture

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/55143610/228544692-c8502a7e-0513-4332-9ec2-a6ef74294eb6.png)

This is a test using the fixture "request" and it dont respect the proxy settings in the playwright config
so it timeouted at line 2 because it dont bypass the proxy here.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/55143610/228546289-dfcd6921-d1db-4a4c-9d8f-892b6e0289a8.png)

any clue why?

Best regards and thank you for your help!

**Comment by gottschd** [comment]
I also have this issue after the upgrade of playwright from v1.30.0 to v1.32.3.
A rollback to v1.31.2 solved it.

I use a dedicated request context without any explicit proxy config:
`
      const context = await request.newContext({
        ignoreHTTPSErrors: true,
        baseURL: 'https://example.host.internal.net,
      });
`
However, in the playwright config the proxy object for each browser looks like:
`
name: "chromium",
use:
   ...
    proxy: {
      bypass: ".internal.net", // note the dot at the beginning
      server: "<our proxy>",
    },
   ... 
`
As i said, this works in v1.31.2 but not in v1.32.3.

**Comment by pavelfeldman** [comment]
Proxy bypass is not implemented for the API requests.

@gottschd I could not reproduce your issue. Please file a separate issue following the template so that we could reproduce your issue.
