### ISSUE TITLE
[BUG]: UI mode doesn't close browser instance when closing UI

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#21919]
### System info
- Playwright Version: 1.32
- Operating System: Mac
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- npx playwright test --ui
- close ui from the ui

**Expected**

Playwright should close all instances of browser once UI is closed

**Actual**

Stays open in your dock and the more you open the UI the more browser instances it stores

<img width="134" alt="Screenshot 2023-03-23 at 14 12 06" src="https://user-images.githubusercontent.com/13063165/227214901-9c1bf04e-8997-4b4f-9ab6-7277a0942d54.png">

**Comment by pavelfeldman** [comment]
I can't repro this one :/

**Comment by aslushnikov** [comment]
@debs-obrien I can't repro as well. Debbie, if this still reproes for you, could you please re-file with a video maybe? Looks like we're missing some important step.
