### ISSUE TITLE
[Feature] How to call the playwright "expect" from other class?

### ISSUE THREAD

**Issue by mandeepmm1** [microsoft/playwright#21923]
I am following POM framework, where i am storing all locators in one class and performing action on other class.

But now in my case, I created a form successfully by storing all locators and methods in one class and calling methods in test.spec class.
But now in 2nd test case; while editing the form, i want to perform assertions for checking if the value exists or not. But again re-writing those locators in test file class is not worthy. 

Please suggest me how can i reuse the locators in test file for performing assertions; Below is my code snippet

**login.js**
```
class create_form {
  constructor(page){
   this.page=page;
   this.name= page.locator("");
}

async login(){
await this.name.type(' ');
}
}
```

**login.spec.js**
```
test('Create login form', async ({ page }) => {
        await createForm.login();
    });
```

```
test('Edit login form', async ({ page }) => {
        
    });
```

**Comment by mxschmitt** [comment]
See [here](https://playwright.dev/docs/pom) our POM guide and [here](https://playwright.dev/docs/test-fixtures#with-fixtures) how you can use your POMs easily without having to re-create them inside every test.

Or do you mean you want to re-use the page instance in another test?

**Comment by aslushnikov** [comment]
Closing as per Max's response. I'd also recommend asking these kind of questions on our discord: https://aka.ms/playwright/discord
