### ISSUE TITLE
[Question] page.waitForFunction doesn't exit on truthy value and leaves execution hanging. How to make it exit?

### ISSUE THREAD

**Issue by AntShkliarov** [microsoft/playwright#21921]
I'm using `page.waitForFunction` to poll and reload the page until an element disappears.  When the predicate resolves to `true`  the execution halts like it's waiting for some promise to resolve and the waitForFunction doesn't exit. Here's a snippet of my code. 
How can I make `waitForFunction` exit?

### System info
- Playwright Version: [v1.28]
- Operating System: [macOS 12.5]
- Browser: [Chrome]

### Source code

```js
const reloadIfNoResults = (messageSelector: string) => {
        document.querySelectorAll('iframe').forEach(frame => {
          const src = frame.attributes.getNamedItem('src');
            if (src && src.nodeValue.includes('blabla')) {
              const msg =
                frame.contentWindow.document.querySelector(messageSelector);
              if (msg) {
                location.reload();
              }
              return !msg;
            }
          });
      };
      await this.page.waitForFunction(
        reloadIfNoResults,
        noResultsMessageSelector,
        {
          polling: 2000,
        }
      );
```

**Comment by aslushnikov** [comment]
@AntShkliarov your `waitForFunction` always returns `undefined`; you should return some value from the function itself.

**Comment by AntShkliarov** [comment]
Got it. @aslushnikov what's the best way to debug the predicate and see what's going on when the watForFunction executes it in the browser? 
I've tried to add console.log() inside, however haven't got any output both in browser and ide.

**Comment by aslushnikov** [comment]
@AntShkliarov I'd recommend adding `debugger;` statement inside the function, then running browser in headed mode, and open devtools there.

Once DevTools are open, the predicate execution will be paused at the debugger statement, so you'll be able to debug easily.
