### ISSUE TITLE
[BUG] Page.mouse.move: Cannot read property of undefined (reading 'move')

### ISSUE THREAD

**Issue by jo-finndian** [microsoft/playwright#21937]
Heya, I've been trying to get any of the Page.mouse methods to work, but they all return the same error. I'm only using Page.mouse because neither .dragTo() nor .dragAndDrop() were working like some other users have posted about.

### System info
- Playwright Version: 1.8
- Operating System:  macOS 13.2
- Browser: Chromium

**Config file**

```
export default {
  browser: "chromium",
  contextOptions: {
    ignoreHTTPSErrors: true,
    viewport: {
      width: 1440,
      height: 900,
    },
  },
  launchOptions: {
    headless: process.env.CI ? true : false,
    devtools: false,
    args: process.env.CI ? ciArgs : localArgs,
  },
};
```

**Code**

``` 
public async expandBottomPane(): Promise<void> {
    await this.page.waitForSelector('.scheduleForecastRowLabels');

    const verticalDivider = this.page.locator('.verticalDivider');
    const dayLine = this.page.locator('.scheduleHeader .dayLine');
    const toDragBox = await verticalDivider.boundingBox();
    
    await this.page.mouse.move(toDragBox!.x, toDragBox!.y)
}

**Comment by jo-finndian** [comment]
Having the same issue with page.keyboard

**Comment by mxschmitt** [comment]
Can you share repro steps, maybe a small script or repository which we can run locally?

**Comment by aslushnikov** [comment]
It looks like the issue has stalled; closing this to not accumulate stale issues.

Please, do not hesitate to file new issue if this still bothers you and you have a repro that we can use to run & debug things locally!

Thanks!
