### ISSUE TITLE
[BUG] .wsdl files causing fileChooser to yield wrong path

### ISSUE THREAD

**Issue by CalvinThai** [microsoft/playwright#21936]
### System info
- Playwright Version: [v1.31.1]
- Operating System: macOS 13.0
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

``` 
 const fileToUpload = path.join(
    __dirname,
    `../e2e/__shared__/fixtures/samples/${wsdlRestApi}.wsdl`
  )

//fileToUpload yields:  /Users/calvin/Github/ui/e2e/__shared__/fixtures/samples/weather.wsdl

  const fileChooserPromise = page.waitForEvent('filechooser')
  await page
    .getByRole('button', {
      name: 'Drag and drop files here or click to upload (json/wsdl/xml/xsd/yml/yaml/zip)',
    })
    .click()
  const fileChooser = await fileChooserPromise
  await fileChooser.setFiles(fileToUpload)

```

<img width="813" alt="image" src="https://user-images.githubusercontent.com/19965265/227322811-dbbf00ba-a6a2-4768-bb33-3dc65b5a1f0a.png">

This seems to only be happening for .wsdl files, as similar code was used for .yaml files and didn't seem to come up with this path error.

**Expected**
Filechooser should select the path that fileToUpload yields, but cuts out the folders in the directory ```/e2e/__shared__/fixtures/samples/```

**Actual**
Filechooser is choosing  `/Users/calvin/Github/ui/weather.wsdl` instead of `/Users/calvin/Github/ui/e2e/__shared__/fixtures/samples/weather.wsdl`

[Describe actual behavior]

**Comment by aslushnikov** [comment]
@CalvinThai I just tried and it works just fine with `.wsdl` files. It looks like there's some issue with path resolution, but it's hard to say unless you provide an actual self-contained snippet that I can easily run on my machine to validate this behavior.

So can you actually share a repro that I can run locally and that reproduces the issue?

**Comment by CalvinThai** [comment]
It's probably something to do with our filechoosers then, we have one for .yamls, zips, etc, but we have a separate one for wsdl. Just tried to target the .wsdl file using the one designed for yamls, zips, etc, and it is able to target the .wsdl properly. Thank you for the help/
