### ISSUE TITLE
[BUG] Opening UI mode from macOS dock opens chromium browser as well

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#21948]
### System info
- Playwright Version: 1.32.0
- Operating System: macOS 13.2

**Steps**
- Launch UI mode, `npx playwright test --ui`
- Click on opened UI mode in macOS dock
- UI mode appears but chromium browser is launched as well

**Expected**

Expectation that only the UI mode would appear. It's pretty annoying when you're switching between windows, then you want to open UI mode running in background and but you get UI mode and chromium browser.

**Comment by aslushnikov** [comment]
@MindaugasMateika Thanks, I can repro.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/9434
