### ISSUE TITLE
[BUG] Set "viewport: null" made Playwright can not get attribute of element in headless mode

### ISSUE THREAD

**Issue by nnson0310** [microsoft/playwright#21958]
### System info
- Playwright Version: 1.32
- Operating System: Windows 10 latest
- Browser: All browsers (Chromium, Firefox, Webkit)
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { 
        browserName: 'chromium',
        viewport: null,
      },
    },
});
```

**Test file (self-contained)**

```js
  await page.goto('https://www.ericsson.com/en');
  const link = await page.locator('a[title="Link to pdf document"]').getAttribute('href');
  console.log(link);
```

**Steps**
- Run above test

**Expected**

Can get href attribute without problem

**Actual**

Can only get href attribute in headfull mode. Not work in headless mode. After a while, timeout exception will be thrown [](url)

**Comment by aslushnikov** [comment]
@nnson0310 it looks like website has bot-evasion techniques and refuses to render the page in headless mode. Bot-evasion falls outside of the scope of the project, so I'll have to close this.
