### ISSUE TITLE
[BUG]: Playwright UI does not list Actions / not show browser preview when running tests

### ISSUE THREAD

**Issue by lukaskoeller** [microsoft/playwright#21950]
### System info
- Playwright Version: v1.32.0
- Operating System: macOS 13.0
- Browser: Chromium
- Reference Discord Thread: https://discord.com/channels/807756831384403968/1088760461471776888

<img width="1512" alt="Screenshot 2023-03-24 at 10 44 29" src="https://user-images.githubusercontent.com/10390627/227490636-4ac4d734-3cfb-4e46-a535-5cbae1ae9a59.png">

### Reproduction

[github:playwright-ui-reproduction](https://github.com/lukaskoeller/playwright-ui-reproduction)

### Source code

**Config file**

`@quirion/playwright-config`
```ts
import { PlaywrightTestConfig, devices } from '@playwright/test';

export const PlaywrightConfig: PlaywrightTestConfig = {
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  use: {
    headless: true,
    video: 'on-first-retry',
    trace: 'on',
    launchOptions: {
      // devtools: true,
      logger: {
        isEnabled: (name, severity) => name === 'browser',
        log: (name, severity, message, args) => console.log(`${name} ${message}`)
      }
    },
  },
  projects: [
    {
      name: 'chromium',
      testDir: './tests/',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      testDir: './tests/',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      testDir: './tests/',
      use: { ...devices['Desktop Safari'] },
    },
  ],
  reporter: [
    ['html', { outputFolder: './reports/playwright-report' }],
    ['junit', { outputFile: './reports/results.xml' }]
  ],
};
```

`playwright.config.ts`
```ts
import { PlaywrightConfig } from "@quirion/playwright-config";
import { devices, PlaywrightTestConfig } from "@playwright/test";
import { BANKING_URL } from "@quirion/fe-tests"; // 'http://127.0.0.1:3000'
// eslint-disable-next-line import/no-extraneous-dependencies
import dotenv from 'dotenv';

dotenv.config();

const config: PlaywrightTestConfig = {
  ...PlaywrightConfig,
  use: {
    ...PlaywrightConfig.use,
    baseURL: process.env.CI_ENVIRONMENT_URL || BANKING_URL,
  },
  projects: [
    {
      name: 'chromium',
      testDir: './tests/',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
};
export default config;
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- In the monorepo route from the root to the package's root
- Run `pnpm dlx playwright test --ui`
- Playwright UI opens
- Pick any test & click on the run icon
- Test runs through and shows checkmark (success)
- In the `Actions` tab no actions were listed
- The browser remains on `about:blank`

**Expected**

Playwright Actions lists all actions of the test and the browser previews what the test is doing.

**Actual**

The test runs, but no actions or browser actions are visible.

**Comment by aslushnikov** [comment]
@lukaskoeller how do we reproduce this? Any chance you can create a small repo that mimics your monorepo structure and demonstrates the issue?

**Comment by aslushnikov** [comment]
@lukaskoeller it looks like the `test-results/` folder is created in some unexpected place. Can you share it's location with us as well?

**Comment by lukaskoeller** [comment]
> @lukaskoeller it looks like the `test-results/` folder is created in some unexpected place. Can you share it's location with us as well?

Sure! It is in the root of the package of the monorepo. So same directory where `playwright.config.ts` lives. The package itself from the monorepo has the following path: `[root]/src/mf/[nameOfPackage/packageRoot]`

> @lukaskoeller how do we reproduce this? Any chance you can create a small repo that mimics your monorepo structure and demonstrates the issue?

I'll give my best to link a reproduction anytime soon

**Comment by lukaskoeller** [comment]
Okay, might this just be my mistake and Actions and Preview is only provided for single tests, not test suites? Because when I play the test on the lowest level everything is shown correctly. Without further thinking, I expected this to work for every level but wouldn't make sense / wouldn't be possible for parallel runs 😬

**Comment by aslushnikov** [comment]
@lukaskoeller oh yes, actions are only shown once the test is selected. Thank you for the feedback though!

**Comment by bmaupin** [comment]
I just came here with the same issue, wondering why the Actions and the browser weren't updating when running tests in the UI.

I'm coming from Cypress, so maybe that is colouring my expectations, but I wonder if there is a possible UX/DX improvement here to be made to make it clear that this is expected behaviour.

Thanks!

**Comment by AndreasSchieferbein** [comment]
I have the same issue, my actions bar is gone and i dont know why. So i am facing the situation that i could not debug proper in the ui mode. 

Is there any shortcut to hide/display those bars in the ui mode? 
Or can i reset the ui to default settings somewhere?

**Comment by tanvirrb** [comment]
Facing the same issue. The preview browser doesn't do anything.

**Comment by LucasPadovanPeek** [comment]
Facing some similar issues, there is little information in the UI about what's being asserted or awaited. For example the `waitForResponse` and `expect.toBe`
![image](https://github.com/microsoft/playwright/assets/108287353/6448189f-fa5c-4c0d-b957-6f8a97754220)
![image](https://github.com/microsoft/playwright/assets/108287353/11e51f79-b758-4c37-a8c2-2acd3a9a58c8)

**Comment by greilberger13** [comment]
<img width="1913" height="1148" alt="Image" src="https://github.com/user-attachments/assets/020bcec9-87f1-452e-bd48-b798532e935c" />

Hei everyone.
Since I've updated Playwright to the latest version (1.60.0), I am not able to see anything as shown in the picture.
Does anyonne have an idea, if I am doing something wrong. Or is this a bug?
I am obviously on the lowest level, but still cannot see anything.

**Comment by snoozbuster** [comment]
> Hei everyone. Since I've updated Playwright to the latest version (1.60.0), I am not able to see anything as shown in the picture. Does anyonne have an idea, if I am doing something wrong. Or is this a bug? I am obviously on the lowest level, but still cannot see anything.

Same issue for me. was working fine on 1.57.0. don't have any custom page setup in this test.

**Comment by mikesell-push** [comment]
> <img alt="Image" width="1913" height="1148" src="https://private-user-images.githubusercontent.com/131961597/596011924-020bcec9-87f1-452e-bd48-b798532e935c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODAzNTMxMjQsIm5iZiI6MTc4MDM1MjgyNCwicGF0aCI6Ii8xMzE5NjE1OTcvNTk2MDExOTI0LTAyMGJjZWM5LTg3ZjEtNDUyZS1iZDQ4LWI3OTg1MzJlOTM1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYwMVQyMjI3MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzhmZWRlYmZmM2U1YTAwMzQ0NzE0YTA2YmYwYzUwMDFlYmJjNjA1MzYzYzc2MDdkOTZhMzQ0OGRhOWQ3NWE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.9W_8J8iL6O6kmuXHle--_poo5fiWEHBFEPi3ZWK3HlA">
> Hei everyone. Since I've updated Playwright to the latest version (1.60.0), I am not able to see anything as shown in the picture. Does anyonne have an idea, if I am doing something wrong. Or is this a bug? I am obviously on the lowest level, but still cannot see anything.

I am now experiencing the same issue after upgrading, and I think this is a bug

**Comment by Alex-Bou** [comment]
> <img alt="Image" width="1913" height="1148" src="https://private-user-images.githubusercontent.com/131961597/596011924-020bcec9-87f1-452e-bd48-b798532e935c.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODA5ODY4NjcsIm5iZiI6MTc4MDk4NjU2NywicGF0aCI6Ii8xMzE5NjE1OTcvNTk2MDExOTI0LTAyMGJjZWM5LTg3ZjEtNDUyZS1iZDQ4LWI3OTg1MzJlOTM1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDYwOVQwNjI5MjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTdlYmZjOTNkY2QxZmQ5YzVhODA5MjI0YmY3YWM4ZWUzZmU0ZTM3NTg1MGYxMzE4OTZkYzI2ODA5N2YwZmRiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.izaWb_0jiCUDWTE7N0bcLB8k7rKPbZVS0p_5QTN2Erc">
> 
> Hei everyone. Since I've updated Playwright to the latest version (1.60.0), I am not able to see anything as shown in the picture. Does anyonne have an idea, if I am doing something wrong. Or is this a bug? I am obviously on the lowest level, but still cannot see anything.

Exact same issue, worked fine before 1.60.0. After upgrading version, nothing shows in Actions, Error, Logs, etc. the UI mode only show PASSED or FAIL without any explication

**Comment by fravl** [comment]
I have the same issue and downgrading to 1.57.0 from 1.60.0 resolved the issue.

Edit: 1.59.0 works as well
Edit 2: Turns out, upgrading to 1.61.0 did the trick as well

**Comment by greilberger13** [comment]
> I have the same issue and downgrading to 1.57.0 from 1.60. resolved the issue.

That might be true, but then I guess you will find a bug in the code generation tool. The toolbar can not be used, if you have a cdk-overlay.

**Comment by Hypenate** [comment]
In my case it was an isue with the project.json file.
I swapped this
```
  "targets": {
    "e2e-ui": {
      "executor": "nx:run-commands",
      "cache": false,
      "options": {
        "command": "pnpm exec playwright test --ui",
        "cwd": "libs/editor/feature-design-pw-e2e"
      }
    },
```
to this
```
  "targets": {
    "e2e-ui": {
      "executor": "nx:run-commands",
      "cache": false,
      "options": {
        "command": "pnpm exec playwright test --ui -c libs//editor/feature-design-pw-e2e/playwright.config.ts"
      }
    },
```
