### ISSUE TITLE
Fonts rendering changed after updating playwright version to 1.31.0 from 1.22.0[BUG]

### ISSUE THREAD

**Issue by badigerpramod** [microsoft/playwright#21959]
### System info
- Playwright Version: [v1.31.0]
- Operating System: [All]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I am doing visual regression test with @web/test-runner and playwright library, after the playwright upgrade to 1.31.0 from 1.22.0 then screenshots started breaking due to fonts rendering change and screenshot width and height change, most of the issues are in firefox and webkit

**Comment by pavelfeldman** [comment]
That's expected! Every time the browser changes, font metrics can be affected, so you need to rebaseline your images.

**Comment by aslushnikov** [comment]
@badigerpramod Closing as per Pavel's response. Feel free to file a new issue if you think we still can be helpful.

**Comment by badigerpramod** [comment]
> That's expected! Every time the browser changes, font metrics can be affected, so you need to rebaseline your images.

Yes, you are right but when i test same font in same version of normal safari browser fonts looks fine, but on playwright webkit it squeezes 2px, what could be the issue?
