### ISSUE TITLE
[BUG] UI mode shows only test file with global setup when I use projects dependencies instead of all my tests

### ISSUE THREAD

**Issue by arkjel** [microsoft/playwright#21952]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [macOS 13.2.1]
- Browser: [All]

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
 testDir: "./tests",
 testMatch: "*.spec.ts", 
 use: {
   baseURL: "https://www.saucedemo.com",
 },
 projects: [
 {
   name: "setup",
   testMatch: "global.setup.spec.ts",
 },
 {
   name: "chromium",
   use: devices["Desktop Chrome"],
   dependencies: ["setup"],
 },
 {
   name: "firefox",
   use: devices["Desktop Firefox"],
   dependencies: ["setup"],
 },
 {
  name: "webkit",
  use: devices["Desktop Safari"],
  dependencies: ["setup"],
 },
 ],
});
```

**Test file (self-contained)**

```js
// global.setup.spec.ts
import { test as setup, expect } from "@playwright/test";

setup("should do some setup", async ({ page }) => {
   await page.goto("");
   await expect(page).toHaveURL("https://www.saucedemo.com");
});
});
```

**Steps**
1. Create some test files e.g. `login-page.spec.ts` and `inventory-page.spc.ts` and put them into `tests` directory

<img width="303" alt="obraz" src="https://user-images.githubusercontent.com/13696203/227499407-e119612e-8661-4582-bd87-4fab5ee7910c.png">

2. Copy the config file from this issue
3. Run th tests using: `npx playwright test --ui` command

**Actual**
I see only the `global.setup.spec.ts` file and I can run it

<img width="245" alt="obraz" src="https://user-images.githubusercontent.com/13696203/227498923-6ca6df4a-582a-4f8a-820d-9c30164de04d.png">

**Expected**
There are all of my tests which can I run and play with them because I set the `testMatch` global property as `testMatch: "*.spec.ts",` in my config file

<img width="245" alt="obraz" src="https://user-images.githubusercontent.com/13696203/227499095-9318ee0e-c3c6-4326-a487-f14b01e8b815.png">

**Comment by aslushnikov** [comment]
@arkjel by default, UI mode selects only the first project and shows tests from the first project. You can run `globalSetup` once, and then click on the `project` filter to select other projects:

<img width="500px" src="https://user-images.githubusercontent.com/746130/227628559-e157dd6f-09be-4f27-b14e-361de6f62d0a.png">

**Comment by arkjel** [comment]
@aslushnikov what do you think to show all of the projects by default? I think it would be better user experience for that feature. I think in UI mode people want to run some tests from various projects. I guess some of the people can be confused of that behaviour.

<img width="248" alt="obraz" src="https://user-images.githubusercontent.com/13696203/227629932-4b5fcf03-c2e7-4a7c-b7df-6984a4ada57b.png">

**Comment by aslushnikov** [comment]
> what do you think to show all of the projects by default?

@arkjel we discussed this with team, and we might change the defaults later. Let us gather more feedback regarding this.

Do note though that your selected projects are actually saved in preferences, so when you restart the UI Mode, your selected projects are retained. 

I'll close this for now, but thank you for the feedback! Please do not hesitate to file more issues with feedback!

**Comment by narutosstudent** [comment]
Ye, it was mad confusing for me too. 😅

**Comment by SSmietana** [comment]
Yeah this was confusing as a new user

>by default, UI mode selects only the first project and shows tests from the first project

@aslushnikov there seems to be an exception when there are dependencies, ex this will select 'cleanup db'
```js
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      teardown: 'cleanup db',
    },
    {
      name: 'cleanup db',
      testMatch: /global\.teardown\.ts/,
    },
  ]
```

**Comment by Mayyas6** [comment]
took us a couple of minutes in the team to figure this one out as well.. def confusing for new users

**Comment by bigcakes** [comment]
Definitely threw me off, would make a lot of sense to start without any filters enabled

**Comment by stoverp** [comment]
we (Asana engineers) also ran into this, and would love if it could be fixed

**Comment by vpapanchev** [comment]
I also found this confusing. Selecting all projects by default sound much more natural to me.
