### ISSUE TITLE
[BUG] context.setHTTPCredentials(null); does not clear credentials

### ISSUE THREAD

**Issue by basarat** [microsoft/playwright#2196]
**Context:**
- Playwright Version:1.0.1
- Operating System: Mac
- Node version: v13.13.0
- Browser: Chromium

**Code Snippet**

```ts
import * as playwright from 'playwright';

async function main() {
  const browserType = playwright.chromium;

  // Launch browser
  const browser = await browserType.launch();
  // Create a context
  const context = await browser.newContext();
  // Create a page
  const page = await context.newPage();

  // Provide http credentials
  await context.setHTTPCredentials({
    username: 'username',
    password: 'password'
  });

  // Carry out actions
  await page.goto('http://localhost:3000/auth');
  await page.screenshot({ path: 'output/auth.png' });

  // Clear the credentials
  await context.setHTTPCredentials(null);

  // Carry out actions
  await page.goto('http://localhost:3000/auth');
  await page.screenshot({ path: 'output/unauth.png' });

  // Close the browser
  await browser.close();
}
main();
```

**Describe the bug**

If I remove both calls to `setHTTPCredentials` I see a page that says `unauthenticated`. But if I have the call that sets the credentials   `await context.setHTTPCredentials({    username: 'username',   password: 'password'  });` then the call `await context.setHTTPCredentials(null);` has no effect an the page always says `authenticated`

**Comment by pavelfeldman** [comment]
Thanks for the report!

This looks like a default Chrome behavior - it'll cache the basic auth for the given origin `localhost:3000` until the end of the session. `context.setHTTPCredentials(null)` clears it in the context for the new origins, but this original origin sticks with the cached value. There are some details on it here: `https://stackoverflow.com/questions/5957822/how-to-clear-basic-authentication-details-in-chrome`.

I wonder if creating a new context would do the trick for you: you would specify credentials in one context and not specify them in the other. That's basically what browser contexts are for.

But I agree this behavior is confusing, so we should make sure this is clear from the documentation.
