### ISSUE TITLE
[BUG]  Error: test file "src\tests\<testFileName>.spec.ts" should not import test file "src\app\utils\test.extend.ts" in "@playwright/test": "1.32.X"

### ISSUE THREAD

**Issue by mikicymulate** [microsoft/playwright#21979]
### System info
- Playwright Version: 1.32.1 / 1.32.0
- Operating System:  Windows 11
- Browser: All

since version **1.32.X** I can't run all of my tests that ran in the up to last version **1.31.2** .
I get the following error message in the console
`Error: test file "src\tests\<testFileName>.spec.ts" should not import test file "src\app\utils\test.extend.ts"`
for all my test files.
I'm using `const test = base.extend<TestFixtures>` to create Fixtures
I tried to run using: 
npx playwright test  / playwright test  

playwright.config.ts : 
```
import {PlaywrightTestConfig, devices} from "@playwright/test";
const config: PlaywrightTestConfig = {
    workers: 4,
    timeout: 1000 * 60  * 10,
    reporter: [
        ["allure-playwright", {outputFolder: "./allure-results/"}],
        ["line"],
    ],
    use: {
        trace: "retain-on-failure",
        headless: false,
        screenshot: {
            mode: "only-on-failure",
            fullPage: true,
        }
    },
    projects: [
        {
            name: "XXXXX",
            use: {
                channel: "chrome",
                ...devices["Desktop Chrome"],
                acceptDownloads:true,
                viewport: {width: 1920, height: 937}
            },
        }
    ]
};
export default config;
```
```
tsconfig.json : 
`{
  "compilerOptions": {
    "module": "commonjs",
    "target": "ES2021",
    "sourceMap": true,
    "resolveJsonModule" : true,
    "allowSyntheticDefaultImports": true
  },
  "exclude": [
    "node_modules"
  ]
}
```
please help !

**Comment by mikicymulate** [comment]
I was able to fix it by changing the fine name from : "test.extend.ts"  to : "myTest.extend.ts"
Still looks like a **bug** or a change we haven't updated on.

**Comment by ritz078** [comment]
This looks like a regression and I had to move those utilities into a separate utils folder to fix this issue.

**Comment by dgozman** [comment]
This is because `test.extend.ts` is matched as a test file by default. We'll fix this.
