### ISSUE TITLE
[Question] Access the HTML Snapshot from Trace.zip

### ISSUE THREAD

**Issue by 3wweiweiwu** [microsoft/playwright#21977]
Hello,

I am trying to create a reporter for playwright. And I would like to have access to html snapshot from reporter. Is it possible?

Best,

![image](https://user-images.githubusercontent.com/14018114/227683580-1879743a-8497-49a7-b3d1-66b24f4977b6.png)

**Comment by yury-s** [comment]
The snapshots are in trace.trace file inside the trace.zip. Look for frame-snapshot events. The format is an implementation detail and we don't publish any documentation nor guarantee that it will not change in the future so you are on your own. With that said, all the implementation is open source so you can modify it to your liking.
