### ISSUE TITLE
[internal] Docker WebKit does not get shown on the flakiness dashboard

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#21982]
<img width="658" alt="image" src="https://user-images.githubusercontent.com/17984549/227725431-bf8a772f-cd58-44e1-b41f-dbc14749f606.png">

**Comment by aslushnikov** [comment]
As of today, works as expected: https://devops.playwright.dev/flakiness.html#test_parameter_filters=%5B%5B%22docker%22%2C%5B%5Btrue%2C%22include%22%5D%5D%5D%2C%5B%22browserName%22%2C%5B%5B%22webkit%22%2C%22include%22%5D%5D%5D%5D&filter_spec=%40smoke&timestamp=1680049085041

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/746130/228395019-aa5d63be-286f-4296-abd3-f7565ff722e1.png">

**Comment by mxschmitt** [comment]
Can confirm that its fine now.
