### ISSUE TITLE
[BUG] Extensions Used by CDP-Browser dont work on new_page

### ISSUE THREAD

**Issue by Vinyzu** [microsoft/playwright#21989]
Refile of https://github.com/microsoft/playwright/issues/21872

### System info
- Playwright Version: 1.31.1
- Operating System: Windows
- Browser: CDP-Spawned Chrome
- Python version: 3.10

### Source code
[Vinyzu/extension-test-repo](https://github.com/Vinyzu/extension-test-repo)
Using [Return Youtube Dislike](https://chrome.google.com/webstore/detail/return-youtube-dislike/gebbhagfogifgggkldgodflihgfeippi?hl=de)

Expected

The Extension (in this case ReturnYoutubeDislike) should load and work on new pages spawned under the browser.

Actual

The Extension doesnt load/work.

**Comment by yury-s** [comment]
As noted at the very beginning of [this page](https://playwright.dev/python/docs/chrome-extensions) extensions only work in persistent context. [`main_browser.new_page()`](https://playwright.dev/python/docs/api/class-browser#browser-new-page) is equivalent to creating a new (ephemeral) context and then a page in it. You can change your test to create a new page in the default (persistent) context like this:

```py
default_context = main_browser.contexts[0]
page = default_context.new_page()
page.goto("https://www.youtube.com/watch?v=YbJOTdZBX1g")
```
