### ISSUE TITLE
Using `test.use` inside for loop always set the fixture to the last value of iteration

### ISSUE THREAD

**Issue by EtienneDG** [microsoft/playwright#21998]
### System info
- Playwright Version: 1.30.0
- Operating System: Linux (Ubuntu 22.10)
- Node.js version: 14.21.3
- Visual Studio Code version: 1.76.2
- Playwright for VSCode extension version: 1.0.9
- Browser: Chromium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Here is a minimal reproducible example :

**Config file**

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
    /* Configure projects for major browsers */
    projects: [
        {
            name: 'Desktop Chrome',
            use: {
                ...devices['Desktop Chrome']
            }
        }
    ]
};

export default config;
```

**Test file (self-contained)**

```ts
import { test as base, expect } from '@playwright/test';

const keywords = ['foo', 'bar', 'playwright'];

const test = base.extend<{ keyword: string }>({
    keyword: 'foo'
});

test.describe(`Test suite`, () => {
    for (const kw of keywords) {
        test.use({ keyword: kw });
        test(`Test for : ${kw}`, async ({ keyword }) => {
            await expect(kw).toBe(keyword);
        });
    }
});
```

**Steps**
- Run the test suite

**Expected**

Expect to have the fixture correctly set for each test inside the for loop.

**Actual**

When I run this test suite, the first two tests fail and the last one succeeds. For all of them `keyword` fixture is equal to `playwright`. Here is the resulting log : 
```
Running 3 tests using 1 worker
  1) [Desktop Chrome] › specs/simpler-test.spec.ts:12:9 › Test suite › Test for : foo ==============

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "playwright"
    Received: "foo"

      11 |         test.use({ keyword: kw });
      12 |         test(`Test for : ${kw}`, async ({ keyword }) => {
    > 13 |             await expect(kw).toBe(keyword);
         |                              ^
      14 |         });
      15 |     }
      16 | });


  2) [Desktop Chrome] › specs/simpler-test.spec.ts:12:9 › Test suite › Test for : bar ==============

    Error: expect(received).toBe(expected) // Object.is equality

    Expected: "playwright"
    Received: "bar"

      11 |         test.use({ keyword: kw });
      12 |         test(`Test for : ${kw}`, async ({ keyword }) => {
    > 13 |             await expect(kw).toBe(keyword);
         |                              ^
      14 |         });
      15 |     }
      16 | });


  2 failed
    [Desktop Chrome] › specs/simpler-test.spec.ts:12:9 › Test suite › Test for : foo ===============
    [Desktop Chrome] › specs/simpler-test.spec.ts:12:9 › Test suite › Test for : bar ===============
  1 passed (1.5s)
```

**Notes**

My actual use case has  a page object used as a fixture, depending on a "constant fixture" that is updated in a for loop with `test.use`. Also I use the constant fixture to pick various values from a test data set. If there is another way to achieve this than a for loop and `test.use`, glad to switch to it.

**Comment by yury-s** [comment]
This is working is intended. The last call of `test.use` within the same scope (file or test.describe) overwrites previously set values, so you can only have one option per scope. To overcome this in your scenario use different test.describe scopes for different parameter values:

```ts
for (const kw of keywords) {
  test.describe(`Test suite ${kw}`, () => {
          test.use({ keyword: kw });
          test(`test`, async ({ keyword }) => {
              await expect(kw).toBe(keyword);
          });
  });
}
```
will that work for you?

**Comment by EtienneDG** [comment]
Thanks for the reply @yury-s , I understand. I missed that detail on configuration scopes. 
Anyway, using one `test.describe` per test will be just fine in my case, I'm closing the issue.

**Comment by Aleksandr-Zharkov** [comment]
> This is working is intended. The last call of `test.use` within the same scope (file or test.describe) overwrites previously set values, so you can only have one option per scope. To overcome this in your scenario use different test.describe scopes for different parameter values:
> 
> ```ts
> for (const kw of keywords) {
>   test.describe(`Test suite ${kw}`, () => {
>           test.use({ keyword: kw });
>           test(`test`, async ({ keyword }) => {
>               await expect(kw).toBe(keyword);
>           });
>   });
> }
> ```
> 
> will that work for you?

Cool! I was looking for an adequate example of conducting multiple e2e tests via loops, and your answer will be my last stop as there is not much info in the official docs or other blogs. Thanks!

**Comment by toduyemi** [comment]
thank you this issue was a godsend!

**Comment by tawago** [comment]
I was spending hours to figure out why my fixture was not updating with `test.use`.  I was very puzzled by `{scope: 'test'}` failing to set back to the default value after a `test()`.  

And this issue finally got me to the resolution. I think the doc needs to clearly mention about this implicit scoping "(file or test.describe)"

Can I draft a PR to add more information in the doc?
