### ISSUE TITLE
[BUG] Playwright trace should format console messages with % sequences properly

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#22002]
### System info
- Playwright Version: 1.31.2
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  use: {
    trace: 'on',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.evaluate(() => {
    console.log('%s', 'Hello, World!');
  });
});
```

**Steps**
- Run the test 
- Open the trace and check the console tab.

**Expected**

The message is formatted like displayed in the browser dev tools: "Hello, World!"

**Actual**

You get "%s    Hello, World!" instead.

**Comment by aditya-sriram** [comment]
Hello. I am a student in EECS 481 at the university of Michigan and I have an assignment to contribute to an open source project on GitHub. I have programming experience in typescript and JavaScript. I have read the issue closely, familiarized myself with the codebase and read the contribution guidelines. I would like to work on this issue.

**Comment by pavelfeldman** [comment]
Should be fixed
