### ISSUE TITLE
[Feature] Add support for loading devtools extensions in @playwright/test config

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#22001]
Needing to load devtools extensions like the Vue Devtools to debug tests in a headed Playwright test run is quite a common need. Currently you have to do something like:

```ts
const vueDevtools =
  '/Users/segevfiner/Library/Application Support/Google/Chrome/Default/Extensions/nhdogjmejiglipccpnnnanhbledajbpd/6.5.0_0';

export const test = base.extend({
  context: async ({ contextOptions }, use) => {
    const context = await chromium.launchPersistentContext('', {
      ...contextOptions,
      args: [`--disable-extensions-except=${vueDevtools}`, `--load-extension=${vueDevtools}`],
    });
    await use(context);
    await context.close();
  },
});
```

But this cumbersome as you have to figure out the path for the extension, override the context fixture, which likely modifies quite a bunch of Playwright behaviors, and possibly has unintended side effects, especially due to the persistent context, for example messing with the way the VS Code extension works with the context and browsers for reuse.

It would be nice if it was supported better. First it needs the ability to configure the context to be persistent instead of incognito so extensions are supported, and then we need something to figure out the path of the extension or better, download it, and cache it and so on, like https://github.com/MarshallOfSound/electron-devtools-installer.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/11833

**Comment by segevfiner** [comment]
@yury-s Are you sure? It does depend on #11833, but here I'm also asking for something in the style of `electron-devtools-installer` which will make it easy to also load devtools into such a browser context. That's a separate feature.

**Comment by alectrocute** [comment]
Please re-open this. This is for TDD, not browser extension testing.
