### ISSUE TITLE
Auto-Display HTML Report on CI

### ISSUE THREAD

**Issue by SriQA1** [microsoft/playwright#22009]
Hello guys, I was trying to execute some tests on jenkins pipeline, and noticed that the HTML Report "Show" was executed automatically and immediately after the tests run, if something fails, that makes that job to hang, as the report is being generated on the server. I am setting the html reporter setting to never in playwright config.ts but it does not seem to respect that setting. 

My job hangs at this step until I manually abort the Job.
17:47:32    Serving HTML report at http://localhost:9323/. Press Ctrl+C to quit.

**Comment by yury-s** [comment]
Please share the project where it happens so that we can reproduce the issue locally.

**Comment by SriQA1** [comment]
I am afraid I cannot do that, since that is private project.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue if you can reduce the test case to a reproducible example that you can share.
