### ISSUE TITLE
[Feature] Make Vue component mount props less restrictive

### ISSUE THREAD

**Issue by dospunk** [microsoft/playwright#22003]
Moving discussion from #21400 

right now, the `mount` fixture for Vue components only allows a props object of type JsonObject to be passed. This does not match the actual behavior of Vue, which allows anything to be passed as props. The current typing prevents passing functions, objects containing functions (for example, instances of a class), BigInts, Symbols, or objects containing any of those from being passed to the Vue component, as well as objects with non-string keys.

**Comment by sand4rt** [comment]
related to: https://github.com/microsoft/playwright/issues/18346, https://github.com/microsoft/playwright/issues/15620, https://github.com/microsoft/playwright/issues/19151, https://github.com/microsoft/playwright/issues/19320

**Comment by pavelfeldman** [comment]
@sand4rt could you help me understand what the action items are for this issue?

**Comment by sand4rt** [comment]
@dospunk correct me if i'm wrong, but i think this one can be closed.

The prop ts type is now less strict and there is type checking at runtime.

The props still need to be JSON serializable, but that's all what's needed in almost all cases. There are already outstanding issues for the cases where non-JSON serializable props are desired.
