### ISSUE TITLE
[Question] Proper/easiest way of determining correct AndroidSelectors for experimental support

### ISSUE THREAD

**Issue by wahreChrist** [microsoft/playwright#22018]
Context:

Playwright Version: 1.28.1
Operating System: Android 13.0
Node.js version: 16.17.1
Browser: Chrome 111.0.5563.57

Continuation of #21685

Is there any reliable way to determine the proper AndroidSelector?
From what I have read in Android documentation there are a couple of tools that help you do it, like uiautomatorviewer and appium, they show the resource_id of an element when inspected, which is what Im looking for if I understood correctly (`await device.press({ res: 'org.chromium.webview_shell:id/url_field' }, 'Enter');`). But the problem with resource_ids is that web elements don't have it usually, so I`m not really sure currently what would be the best way to find out a proper AndroidSelector for touch PW methods

**Comment by yury-s** [comment]
It is unclear whether the element you are trying to automate is an html element or android widget. You can run the page with device [emulation](https://playwright.dev/docs/emulation#devices) and use code generator to try and pickup a locator. Will that work for you? Note though that [swipe](https://playwright.dev/docs/api/class-androiddevice#android-device-swipe) action is not available for web elements.

**Comment by wahreChrist** [comment]
@yury-s we have some touch-based logic in our web application(like zoom, pinch, swipe, etc.), it's not a native Android app, but we haven`t been able to automate them with standard playwright methods (bounding box, evaluate, basic mouse operators, etc.), so I wanted to make it work through experimental Android support since it has those methods built-in. Didn't realize right away that they work only on the application level and won't work inside a browser. Thanks for clarifying, regardless.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/2903 which tracks request for better support of touch events.
