### ISSUE TITLE
[Feature] Support toggling page focus

### ISSUE THREAD

**Issue by harry-gocity** [microsoft/playwright#22021]
We have window focus listeners that are used to refetch some data and display to the user. We'd like a way to check in Playwright these are fired.

The use case is for a customer in an e-commerce site; they are mid checkout flow with the product page for the site open in another tab. They switch back to the product tab, and add another to their basket. When they switch back to the checkout tab, the checkout updates through refetching the basket due to having `window.addEventListener('focus', () => {...})`. The E2E test should capture this behaviour and assert the basket summary has updated.

This could be achieved by a simple toggle focus command, if browser behaviour is a concern, or dedicated page focus and unfocus utils that can be called. The goal is to trigger a window `focus` event.

**Comment by yury-s** [comment]
As a workaround you can manually dispatch `focus` event via [`dispatchEvent`](https://playwright.dev/docs/api/class-locator#locator-dispatch-event) or even `page.evaluate()`:
```ts
  await page.dispatchEvent('body', 'focus');
```

Folding this into https://github.com/microsoft/playwright/issues/3570
