### ISSUE TITLE
[BUG] How to used a specific value of a key from json file which is getting created as a storage state. 

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#22023]
I want to hit an api that needs to use a certain value of key from .json file into test. This json file is getting created via decencies added in project level. The dependency has to run before start running any test.  

So, I am storing few cookies as a before hook and then reusing the same in my tests.

Now for a case, I have to hit an api which used a value in its end point and that value is getting stored through session storage.

Can anyone help me with this case?

**Comment by DeeptiSaxena09** [comment]
How can I pass that specifc  value from the .json file with api request.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
