### ISSUE TITLE
[BUG] tests made with WebKit and toMatchSnapshot fail irregularly

### ISSUE THREAD

**Issue by ta834n** [microsoft/playwright#22026]
### System info
- Playwright Version: v1.30.0
- Operating System: Ubuntu 20
- Browser: WebKit

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/ta834n/playwright-webkit-demo

**Steps**
- check out the repository
- `npm install`
- `npx playwright install`
- `npx playwright test` // this will create the initial screenshots
- `npx playwright test` // this will compare the screenshots
- repeat the last step (1 out of 5 times the tests will fail)

**Expected**

I expect all tests made with `toMatchSnapshot` to pass no matter how often I execute them.

**Actual**

- tests made with `toMatchSnapshot` fail irregularly
- tests made with `toHaveScreenshot` pass all the time

**Comment by yury-s** [comment]
The diff is just in the shortcut indicator in the search box. It seems to be loading later sometimes depending on the page's logic. Do you have an self-contained page that would indicate that there is a bug in playwright?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
