### ISSUE TITLE
[Feature] configure test.describe

### ISSUE THREAD

**Issue by dipesh17** [microsoft/playwright#22038]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Is it possible to provide a capability where we can configure our describe block as per our need.

We have a requirement to add the followings tags

e.g

```
it('Verify home page login link is present', { tags: ['case_id:169999', 'smoke', 'ci'] }, () => {
...
...
...
    })
```

here the case_id is mapping with our test rail case id
smoke is type of testing
ci or jenkins

**Comment by dipesh17** [comment]
many thanks for your quick reply.
The objective of these meta data is insert those data in the bigquery for running google data studio report.
also extract case_id and inject test run in the test rail.
I am currently using result.xml (junit reporter) when i check after adding data using annotations, I am not seeing those data in result.xml file. 
is that anyway to see the below test level data in the results.xml file?

```
test.info().annotations.push({ 'type': 'case_id', description: '169999' }, 
                                 { 'type': 'smoke' }, 
                                 { 'type': 'ci' })
```

**Comment by yury-s** [comment]
Have you tried setting `embedAnnotationsAsProperties: true` ? See [this page](https://playwright.dev/docs/test-reporters#junit-reporter) for more config options for junit reporter.

**Comment by yury-s** [comment]
Closing per the [response](https://github.com/microsoft/playwright/issues/22038#issuecomment-1487629375) above, feel free to open a new issue if it doesn't work.
