### ISSUE TITLE
[Feature] Extending `PageAssertions` with custom type-safe matchers

### ISSUE THREAD

**Issue by jonas-jonas** [microsoft/playwright#22031]
I am trying to extend the default `PageAssertion` type with some custom matchers (such as `toHaveSession` with some custom session checking logic, etc.). Unfortunately, I was only able to define a global matcher using `expect.extend` and the global types, but that is also available for e.g. a string type. I'd prefer having type safety here (similar to how `toHaveURL` is only available on `expect(page)` calls), to avoid misuse and having to check the type of the receiver inside the matcher itself. Is that somehow possible?

**Comment by sngidamzn** [comment]
@yury-s to clarify, does this mean that the [current example in the docs for extending](https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend) can't be made type-safe at the moment? For non `Locator`/`Page` received values, I'm able to make them type-safe by following guidance in https://github.com/microsoft/playwright/issues/12264#issuecomment-1046891699 but as @jonas-jonas mentioned, this doesn't seem to be possible with what's exported right now for `Page` as well as `Locator` type values.

Can something like `Matchers<R, T>` be provided for these use cases as well? If a new issue is needed for this, can open one.
