### ISSUE TITLE
[BUG][experimental-ct-react]: `build.commonjsOptions` doesn't work properly when we import common JS file to TS file

### ISSUE THREAD

**Issue by inomdzhon** [microsoft/playwright#22032]
### System info
- Playwright Version: v1.32.1
- Operating System: macOS 13.2.1
- NodeJS: v16.4.2
- Yarn: v1.21.1

#### ✅ `vite-react-ts` template – `build.commonjsOptions` works properly

Link to Codesandbox https://codesandbox.io/p/sandbox/issue22032-vite-react-ts

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/228282396-3a6b7597-1d51-4a0a-952d-04af166a93f8.png">

**Picture 1.** It is failing when we import common JS file to TS file

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/228283189-de16f87c-5070-4807-9fe9-c7be64e9f8a3.png">

**Picture 2.** It is fixing with override `build.commonjsOptions.include`.

#### ❌ `@playwright/experimental-ct-react` template – `build.commonjsOptions` doesn't work properly

Link to Codesandbox https://codesandbox.io/p/sandbox/issue22032-playwright-experimental-ct-react-10zc5j

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/228283752-41adddd6-a964-41ac-9089-d7e07daadca3.png">

**Picture 3.** It is failing with override `build.commonjsOptions.include`.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/5850354/228283968-f32c36b5-2f70-4d1b-9da2-43e007a1392a.png">

**Picture 4.** It is fixing with provide `use.ctViteConfig.plugins: [commonjs()]`

**Steps**

- Create project with this guide https://playwright.dev/docs/test-components
- Create TS file (ex. `src/App.ts`)
- Create JS file with commonJS exports and export something (ex, `src/shared.js` with `module.exports.TEST = 'Test'`)
- Import `src/shared.js` file to `src/App.ts` file (ex, `import { TEST } from './shared'`)
- Set `use.ctViteConfig.build.commonjsOptions.include` to `undefined` on `playwright-ct.config.ts` config.

**Expected**

`TEST` imported.

**Actual**

```sh
RollupError: "TEST" is not exported by "src/shared.js", imported by "src/App.ts".
```

**Comment by sand4rt** [comment]
Hi @inomdzhon, this is resolved in https://github.com/microsoft/playwright/pull/22063.

**Comment by inomdzhon** [comment]
Hi, @sand4rt

Thanks for fix 🙏 

In what version will the fix be released?

**Comment by sand4rt** [comment]
> Hi, @sand4rt
> 
> 
> 
> Thanks for fix 🙏 
> 
> 
> 
> In what version will the fix be released?

Not sure, perhaps @pavelfeldman could tell?
