### ISSUE TITLE
[Feature] UI mode doesn't respect test dependencies

### ISSUE THREAD

**Issue by joshmccure** [microsoft/playwright#22045]
Running playwright test with a test that have a dependency. For example the below snippet will run the `setup` dependency when running `npx playwright test`. In UI mode I would reasonably expect the same - in that when running a test that has a dependency it would run the dependency first and then run the test. This is currently not the case.

```{
      name: 'loggedIn',
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATE,
      },
      testIgnore: ['**/*login.spec.ts', '**/*.setup.ts'],
      dependencies: ['setup'],
    },```

**Comment by pavelfeldman** [comment]
This is by design. We assume that you manually run your 'setup' project once and then repeatedly run your test project, while reusing the login credentials. We can make it configurable though, so I'll leave it open to collect the feedback.

**Comment by Exelord** [comment]
I think we should at least take dependencies into account while using `Run all` button. In this case I would expect they would run in defined order.

**Comment by joshmccure** [comment]
I personally don't think it's intuitive to manually have to run the dependencies. I'm also not clear on the reasoning why there would be different expectations for `playwright test tests/<spec>` and `playwright test --ui` and selecting a test. Is there particular use cases here you're thinking about?

Agree at the least a config option would be useful but I think it's worth hearing from others. 

Thanks for your awesome work on this as always!

**Comment by amitasil** [comment]
If I run a specific test (just one using a tag) having dependency in my project on auth.setup.ts it runs fine and console logs say running 2 tests (one auth setup and the other my dependant test).

I expect similar behaviour in the UI Mode (with flag --ui). The test defined in auth.setup.ts does not even appear in the UI Mode to run explicitly even if I want to.

**Comment by elliotwestlake** [comment]
> If I run a specific test (just one using a tag) having dependency in my project on auth.setup.ts it runs fine and console logs say running 2 tests (one auth setup and the other my dependant test).
> 
> I expect similar behaviour in the UI Mode (with flag --ui). The test defined in auth.setup.ts does not even appear in the UI Mode to run explicitly even if I want to.

I would also expect this behaviour

**Comment by luniki** [comment]
> I expect similar behaviour in the UI Mode (with flag --ui). The test defined in auth.setup.ts does not even appear in the UI Mode to run explicitly even if I want to.

Is there any way to run the test defined in auth.setup.ts in the UI?

**Comment by Tsuyoshi84** [comment]
I find it confusing since dependencies are run when I use the VS Code Playwright extension to run individual tests. Although I understand that this is intentional, it would be helpful to have the ability to choose whether to run them or not.

**Comment by AmitRawatMetcash** [comment]
Both v1.33 and v1.34 labels were removed from this issue. Are we targeting this in some later release now?

**Comment by IrfanSyed-PSC** [comment]
Any update on this feature. I have made code changes in Prod to use dependencies and I would like to use the UI feature to develop the code.

**Comment by jaktestowac** [comment]
The biggest disadvantage of not handling project dependencies in UI mode are:
- inconsistency: runner vs UI mode. Behavior when triggering i.e. single test is different.
- remembering how my dependencies are structured to be able use UI mode. 

New user can be confused and wasting lot of time figuring out why tests works in one tool and fail in other.

**Comment by sarah-gelt** [comment]
I always need to run the setup dependency first. My setup routine deletes data from previous runs so that the test user's account is in a clean state before the test(s) run. If this doesn't happen, many of my tests fail as they don't find the expected state.

That said, I can see that not all users would want/need their dependencies to run first. Having a checkbox option in UI mode to choose whether dependencies run or not would be ideal then everyone can use it in their preferred way.

**Comment by Exelord** [comment]
@sarah-gelt you can try the new project teardown feature :) Not a solution to this issue, but might help with productivity.

**Comment by sarah-gelt** [comment]
> @sarah-gelt you can try the new project teardown feature :) Not a solution to this issue, but might help with productivity.

I already have, thanks. We used to run setup and teardown using the old method, but switched to setup-only using project dependencies as the benefits of running it as a project outweighed the lack of teardown for us. Now teardown can be done as a project dependency as well, we are running it at both ends again.

**Comment by reinierkaper-carewell** [comment]
To add to this: global setup and teardown also _don't_ run in the UI, which is a requirement for some of us that do things like DB seeding. It would be good to be able to (selectively) run those as well.

Certainly globalSetup should run because it's, well, a global setup :)

**Comment by ValorHeart** [comment]
In my case, it seems that the project dependent is running, but there is no indication in the UI mode for it.
even not in the 'Toggle output' part

**Comment by mikelhamer** [comment]
Would really love if this could be changed! I understand the idea that we should manually run our setup so that it only runs once, but as a new user of Playwright, I just wasted half a day trying to figure out what I was doing wrong and why my global setup dependency wasn't running first. Following [this tutorial](https://playwright.dev/docs/test-global-setup-teardown) for how to create a global setup, there is zero mention of this. At the very least it should be documented.

**Comment by blessanm86** [comment]
Got bit by this today. I don't use VSCode. Playwright only became viable for me when UI mode was introduced. As mentioned in earlier comments, the discrepancies between UI mode and the runner mode can be very confusing.

I don't really understand the design choice but would suggest a flag for the cli like `--with-deps`.
Atm this is a blocker for non VSCode users.

**Comment by lattebread** [comment]
It would be **very good** if this was configurable. 

Thank you!

**Comment by nopitown** [comment]
I would love this to be configurable as well.

**Comment by nikitaeverywhere** [comment]
Same. Having the dependencies run in UI mode by default is very much an expected behaviour. For those who don't need it, you could keep the flag to avoid running deps.

**Comment by ValorHeart** [comment]
There are more comments than upvotes, if you wish that capability to get considered, please upvote (thumbs up icon) on the first post

**Comment by StephanSchmidt** [comment]
This has cost my several hours - I would never have expected that UI runs completely different from console.

**Comment by m12lrpv** [comment]
How is this closed as fixed when the dependency still has to be manually included and thus is not respected. And worse the vs code plugin is now broken in the same way.

**Comment by tommeldrum1** [comment]
Yes, surely this could be reopened due to demand?

**Comment by Luc45** [comment]
This is also a big blocker for me, as I generate projects at runtime depending on what is being tested, and the user has to execute the projects in the right order in UI mode, whereas in terminal mode the order of dependencies is respected.

Would it be possible to have a "Run all" projects (that don't require checking all the boxes manually) that respects the order of dependencies/teardown? (cc @pavelfeldman, pinging you as the solution to this problem doesn't seem to be fully satisfying to all users, if you could please share your thoughts if this can be reopened?)

**Comment by abdullahzameek** [comment]
> This has cost my several hours - I would never have expected that UI runs completely different from console.

Ditto over here - would be great if this is re-opened. My team has faced the exact same issue and its confusing that the UI and CLI behave drastically differently

**Comment by justasdev** [comment]
Demand is obvious. Please add this feature. Just wasted an hour figuring out what is wrong with my setup, just to find out that it doesn't work in UI mode. And it is not even mentioned in the official docs..

**Comment by PKHDK** [comment]
Yeah I also wasted quite some time until I discovered this! I agree that dependencies and global setups should also run in the UI (or at least be shown as an option)

**Comment by danon** [comment]
> This is by design. We assume that you manually run your 'setup' project once and then repeatedly run your test project, while reusing the login credentials. We can make it configurable though, so I'll leave it open to collect the feedback.


Please, notice that we automate tests purely so that we don't make mistakes with manual testing.

Manual actions during testing are error-prone, because humans make mistake, skip stuff, forget stuff. Having playwright run the same configuration in normal mode and ui mode would mitigate that error.

**Comment by daaain** [comment]
This was really non-obvious, the UI should at least pop up a warning or something!

Would be great if there was a CLI / env var option so it can be set up for team mates to work OOTB.

I just want to click on an individual test and have it run properly...
