### ISSUE TITLE
[Feature] Unable to connect to a terminal to run the docker batches

### ISSUE THREAD

**Issue by as2r9** [microsoft/playwright#22055]
I am building a testing automation framework using playwright. While working on this i am unable to connect to my my terminal and then run the docker batches to execute and validate the data that has been generated from the website. This connection is required as part of my automation process.

Any kind of help is appreciated.
Thanks.

**Comment by mxschmitt** [comment]
This snippet does not mention Playwright. Playwright is just a Node.js script, so you can run any Node.js in it. Since this is not related to Playwright, closing by that.

**Comment by as2r9** [comment]
Can I connect to the terminal using playwright and proceed with the execution of the docker batches through that
