### ISSUE TITLE
[BUG] Unable to generate PDF using Firefox and WebKit in a Docker container

### ISSUE THREAD

**Issue by m0t0r** [microsoft/playwright#2206]
**Context:**
- Playwright Version: 1.0.1
- Operating System: Linux (ubuntu:bionic docker image)
- Node version: v12.16.3
- Browser: Firefox, WebKit
- Extra: using the official [dockerfile](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) to run a container

**Code Snippet**

```javascript
const { firefox } = require('playwright');
const fs  = require('fs');
const fsPromises = fs.promises;


(async () => {
  const browser = await firefox.launch();
  const page = await browser.newPage();
  await page.goto('https://google.com');
  const pdfDoc = await page.pdf({ format: 'A4' });
  await fsPromises.writeFile(__dirname, pdfDoc);
  await browser.close();
})();
```

**Describe the bug**

After not having any luck with Chromium to generate a PDF (mentioned in #2205) I've decided to use alternative browsers but did get any luck with them either. I am using same official docker image to run code but getting this error when trying to run script using Firefox and WebKit.

```
(node:1016) UnhandledPromiseRejectionWarning: TypeError: page.pdf is not a function
    at /home/script.js:11:29
```
I am running Docker container like this:

```
docker container run -it --rm --ipc=host playwright:debug-4 /bin/bash
```

**Comment by mxschmitt** [comment]
Hey, the creation of a PDF is only supported in Chromium Headless, ref: https://playwright.dev/#version=v1.0.1&path=docs%2Fapi.md&q=pagepdfoptions

**Comment by m0t0r** [comment]
Okay, thank you. Closing this issue.

**Comment by m0t0r** [comment]
@mxschmitt @arjun27 maybe there can be a better error message for anyone who tries to call `page.pdf` using Firefox/WebKit ;) perhaps as on the docs page:

```
Generating a pdf is currently only supported in Chromium headless.
```
