### ISSUE TITLE
[BUG] Playwright is validating SSO in Incognito mode. While it should ask for user login in Incognito mode

### ISSUE THREAD

**Issue by vikassahnimca1** [microsoft/playwright#22060]
### System info
- Playwright Version: [v1.31.2]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
NA

or

**Playwright.config.ts file** - Set the launchOptions

```
    {
      name: 'Google Chrome',
      use: {
       channel: 'chromium',
        headless: false,
        launchOptions: {
          executablePath: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
          args: ['--auth-server-whitelist="_"'],
        },
      },
    },
```

**Test file (self-contained)** - Launch the Application URL using below test

```login.spec.ts
test.describe("@Smoke Login", () => {
 test('Login TC', async ({page}) => {
    await page.goto("Application URL"));
  });
});
```

**Steps**
- Set the Config file using lauchoptions.
- Run the command to execute test --> npx playwright test login.spec.ts

**Expected**
Application should be launched in Incognito mode and login page should be displayed. 

**Actual**
Application login is automatically getting validated using SSO by playwright. While in incognito mode login screen should be displayed always. Playwright is automatically considering SSO. Which is stopping us to validate login using multiple credentials.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

**Comment by imartinflores** [comment]
@vikassahnimca1 did you manage to fix this ? I am facing a similar issue where Chrome/Chromium automatically logs in with my credentials..

**Comment by yeungxh** [comment]
I'm facing the same issue, the SSO still automatically login, meanwhile, if I use Chrome incognito mode, it will not login directly.

**Comment by Thor07** [comment]
@vikassahnimca1 were you able to resolve this? 
I am facing same as have to login with different credentials on incognito mode.

**Comment by Thor07** [comment]
> It can be that you have a chrome policy that forces the behavior, see [this page](https://playwright.dev/docs/troubleshooting#incompatible-microsoft-edge--google-chrome-policy-settings). Does behave differently if you launch "C:\Program Files\Google\Chrome\Application\chrome.exe" with the same args manually and navigate to the page in incognito window? Does it have the same issue if you run with the bundled Chromium build instead of Google Chrome?
> 
> If you think this is a playwright bug we need a full example including the web app that we can run locally to reproduce the issue.

@yury-s Your [this page] link is not referenced anymore. Could you point me to similar doc which would help me resolve this issue. Although, I am on macos but would help to read about the setting to enable the Basic auth popup on incognito mode.

**Comment by Waqqars987** [comment]
Facing the same issue with playwright v1.47.2. Has anyone found a workaround to this?

**Comment by luaroncrew** [comment]
facing the same issue with the today's latest version. Using both python 3.11 sdk and directly in codegen cli tool
