### ISSUE TITLE
[Feature] Ability to disable progress output from install

### ISSUE THREAD

**Issue by MattIPv4** [microsoft/playwright#22074]
👋 We call `npx playwright install` in CI quite a bit, and it spams the logs quite a bit with progress bars. It'd be nice if there was a `--no-progress` flag or similar like many other dependency installation commands that suppresses the progress bar printing, allowing for cleaner logs. Cheers.

**Comment by mastrzyz** [comment]
Working on this, testing it out and writing documentation :) https://github.com/microsoft/playwright/pull/24352

**Comment by mastrzyz** [comment]
@MattIPv4 can you help me with an example? please see this message ->

https://github.com/microsoft/playwright/pull/24352

```
To make sure we are on the same page, we have two versions of the download progress reporting: getBasicDownloadProgress and animated getAnimatedDownloadProgress. The idea is that we use animated one whenever we detect TTY so that it was nice and interactive. And for the other cases (CI), we use the basic one.

I read you request as getBasicDownloadProgress is still too noisy, I want it to be more concise. Is that correct assessment? If so, the changes should be localized to getBasicDownloadProgress.
``` - Pavel

**Comment by MattIPv4** [comment]
I am using this in a CI environment (GitHub Actions), so I imagine it is using the basic progress loader, which still spams the console with a unicode progress bar every 10% or so.

**Comment by gustawdaniel** [comment]
Interesting. I am running

```
pnpm dlx playwright install
```

I want to see see progress bars but there is only

```
 pnpm dlx playwright install
.../share/pnpm/store/v3/tmp/dlx-9040     |   +2 +
.../share/pnpm/store/v3/tmp/dlx-9040     | Progress: resolved 2, reused 2, downloaded 0, added 2, done
../../.local/share/pnpm/store/v3/tmp/dlx-9040/node_modules/.pnpm/playwright@1.37.0/node_modules/playwright: Running install script, done in 1m 6.3s
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build.
```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
