### ISSUE TITLE
Chaining two API request in Playwright , passing stored value in the query params not working..Kindly suggest

### ISSUE THREAD

**Issue by moumita30** [microsoft/playwright#22072]
### System info
- Playwright Version: [1.31.2]
- Operating System: [Windows 11.]
- Browser: [NA]
- Other info: API testing Using Playwright

```ts
test("GET: Fetch Document Type Groups", async({request, baseURL})=>{

    const response = await request.get(`${baseURL}/document-capture/document-type-groups`);
    expect(response.status()).toBe(200);
    const responsebody = await response.json();
    const employeeDocuments = responsebody.data[1].id;
    console.log(employeeDocuments);
    **request.storageState.employeeDocuments = employeeDocuments;**
})
test("GET: Fetch Document Types for a DocumentTypeGroup", async({request,baseURL})=>{
    
    
    const response = await request.get(`${baseURL}/document-capture/document-types`,{
        params:{
            **'documentTypeGroupId': request.storageState.employeeDocuments** 
        }
    });
    expect(response.status()).toBe(200);
    const responsebody = await response.json();
   const offerLetterDocTypeID = responsebody.data[2].id;
   request.storageState.offerLetterDocTypeID =offerLetterDocTypeID;
   const newHireCheckListDocTypeID = responsebody.data[1].id;
   request.storageState.newHireCheckListDocTypeID  = newHireCheckListDocTypeID;
})

```

**Expected**
IT should fetch the value from the previous request that is getting stored in the first call

**Actual**
I was trying to chain this two request by fetching a data from the response and storing in the storagestate (request.storageState.employeeDocuments = employeeDocuments;) , but when i am passing this in the query params of the second request, it is gettng passed as undefined

**Comment by yury-s** [comment]
Playwright create new instance of test fixtures for every test, so `request` object you get in the two tests is different. You can instead store the value in a global variable if you want to pass it between tests, see [this example](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests). Also note that you'll need to make the tests run in [serial mode](https://playwright.dev/docs/test-retries#serial-mode). Alternatively, you can convert interdependent tests in [steps](https://playwright.dev/docs/api/class-test#test-step). Will that work for you?

**Comment by moumita30** [comment]
Hi Yury-s, thanks for your prompt reply. But the thing is , It is working fine when I am sending a stored value as a path parameter, like I did above. Infact, it also worked when I passed it as form data in one my post call request.These were all interdependent tests. I will try storing in the global variable. The examply is shown for page, however I hope it works for request fixture as well.I was running all the tests in serial mode.

**Comment by moumita30** [comment]
![playwrightapitest](https://user-images.githubusercontent.com/57482730/228748242-7e587489-50af-4448-892b-4afb081a6067.PNG)
![2](https://user-images.githubusercontent.com/57482730/228748253-8c5d7313-9ee1-4f69-9bf6-c6d5cc864a40.PNG)

**Comment by yury-s** [comment]
> But the thing is , It is working fine when I am sending a stored value as a path parameter, like I did above. Infact, it also worked when I passed it as form data in one my post call request.

It actually works when assigning fields to `request.storageState` because even though we recreate `request` fixture for every test `storageState` function currently stays the same, but I would not recommend relying on that and use a global (or a local to test.describe scope) variable to pass values between tests.

> And also it is getting passed a query param now 

Ok, closing for now. Please file a new issue with a full repro if it happens again.
