### ISSUE TITLE
[BUG] The element coordinates I calculated using bounding_box are different from the coordinates calculated by my local browser

### ISSUE THREAD

**Issue by sunxiaoyu124** [microsoft/playwright#22085]
use js in local Chrome: x: 445.94146728515625, y: 326.2350158691406, width: 37.486846923828125, height: 37.48681640625;
chromium: x: 416.3625183105469, y: 304.57879638671875, width: 34.998722076416016, height: 34.998695373535156

I'm confused.

**Comment by sunxiaoyu124** [comment]
screen size is 100%

**Comment by sunxiaoyu124** [comment]
local Chrome version is 111.0.5563.110;
chromium version is: 112.0.5615.29

**Comment by sunxiaoyu124** [comment]
playwright version is 1.32.0

**Comment by sunxiaoyu124** [comment]
I am sry. I cannot do so due to company security policy. Do you have any other information to help you locate the problem？

**Comment by sunxiaoyu124** [comment]
I've worked it out , but there's one problem , I think I need to address.
HTML code : <div style="overflow: visible; height: 0px; width: 0px;"><div id="screen-content-node" style="width: 1213.1px; height: 760px; position: relative; margin: auto; zoom: 1.03289;">
The HTML code has a "zoom" attribute,  causing the page to zoom, but the bounding_box()  in the playwight frame does not take this property into account, resulting in a deviation between the coordinates and the actual coordinates.

**Comment by mxschmitt** [comment]
Might be similar to https://github.com/microsoft/playwright/issues/21192 and https://github.com/microsoft/playwright/issues/7642. Is this about that clicks are not working?

**Comment by sunxiaoyu124** [comment]
page.mouse.click() is not working

**Comment by sunxiaoyu124** [comment]
> Might be similar to #21192 and #7642. Is this about that clicks are not working?
I read the two questions, and they should be the same question.

**Comment by yury-s** [comment]
Closing for the same reason as described in https://github.com/microsoft/playwright/issues/21192#issuecomment-1450565495 We don't have any plans to support non-standard zoom property, sorry.
