### ISSUE TITLE
[REGRESSION]: Tests failing with "Error: tracing.stopChunk"

### ISSUE THREAD

**Issue by icbita** [microsoft/playwright#22089]
**Context:**
- GOOD Playwright Version: **1.31.2**
- BAD Playwright Version: **1.32.1**
- Operating System: Mac(CI - Linux)
- Extra: Node.js app, and scripts in typescript using POM, Chromium 

**Describe the bug**

during execution getting this   Error: tracing.stopChunk: file data stream has unexpected number of bytes

no other stack trace. if I can get more log please let me know

**Comment by mxschmitt** [comment]
Can you provide us reproduction steps? So we can reproduce it locally?

**Comment by icbita** [comment]
having 1 worker have 2 tests that are using 2 browsers. 
I have 2 Applications that are interacting to each other and I need to perform some steps in App2 then something in App2 and again App1... App2. 

at the end of the test in `afterAll()` method 
the pages of these Apps are closed 

 ```
 test.afterAll(async () => {
    await homeownerPage.context().close()
    await advisorPage.context().close()
  })
```

**Comment by datguychen** [comment]
I have the same exact issue, except this happens on Windows 10. I am using two different webContexts in a single test for notifications verification between two accounts on our project. It crashes ALMOST every time with an error written below. Also, in test steps the only failed step is "After Hooks"

"Error: tracing.stopChunk: EBUSY: resource busy or locked, copyfile 'D:\[REDACTED]\[REDACTED]\test-results\.playwright-artifacts-0\traces\5cb6e803b6acf2665f31-0bf56939d5e43b2762ab-1.network' -> 'D:\[REDACTED]\[REDACTED]\test-results\.playwright-artifacts-0\traces\5cb6e803b6acf2665f31-0bf56939d5e43b2762ab-1-1.network'"

the "[REDACTED]" are folder names but censored :P

PlayWright: 1.32.1
Node: 18.15.0
![image](https://user-images.githubusercontent.com/105912315/228809412-2a024ebb-8d7d-4fbb-a929-59a46e5d8749.png)

**Comment by yury-s** [comment]
@icbita can you share full project that we can run to reproduce the issue locally? Unfortunately, we cannot take any action on this without a repro.

**Comment by yury-s** [comment]
@KeionneDerousselle any chance you can extract the repro in a self contain project that we could run locally?

**Comment by KeionneDerousselle** [comment]
@yury-s I can't share the source code. It's for a company in a private repo. I can try to reproduce it in an isolated project

**Comment by yury-s** [comment]
> I can try to reproduce it in an isolated project

That would be very helpful as we haven't been able to get the error locally so far.

**Comment by icbita** [comment]
hey @yury-s 

I manage to get more insights what is causing the issue

it seems that `trace: "retain-on-failure"` is making my tests to fail

Created this [repo](https://github.com/icbita/playwright-tracing-issue)

In this small project the `tracing.stopChunk `is not happening but the execution is hanging, same thing noticed also sometimes on my work project and I think the hanging and `tracing.stopChunk ` issue are related

please check and let me know

**Comment by KeionneDerousselle** [comment]
I also have `trace: "retain-on-failure"` set in my playwright config.

**Comment by icbita** [comment]
@dgozman what version can I use to retest locally?
