### ISSUE TITLE
[Feature] Is there a way I can set storage quota 

### ISSUE THREAD

**Issue by itsjustzaid** [microsoft/playwright#22092]
Working on a feature that makes a request and caches the response and then returns the response back I want to test that this feature works even if the storage isn't available i.e we get a `QuotaExceededError` but still get the response. Is there a way to emulate this scenario which is `QuotaExceededError`?

**Comment by yury-s** [comment]
Can you clarify which storage you are talking about localStorage/sessionStorage/indexedDB?

Playwright doesn't have an API for setting storage quota. As a workaround you might be able to change the quota by sending [Storage.overrideQuotaForOrigin](https://chromedevtools.github.io/devtools-protocol/tot/Storage/#method-overrideQuotaForOrigin) CDP command via [CDPSession](https://playwright.dev/docs/api/class-cdpsession).

**Comment by itsjustzaid** [comment]
Thanks this works
