### ISSUE TITLE
[Feature] Add ability of snapshot string data to be stored as hashes within a single file.

### ISSUE THREAD

**Issue by brochington** [microsoft/playwright#22107]
Currently the project I am working on uses snapshots to compare DOM strings over generations. In order to help keep the repo size manageable, we first create an MD5 hash of the DOM string, and then use that to `toMatchSnapshot()`.

Currently we have ~400 of these snapshot files all nested within a folder, and this works, but presents a couple of challenges, namely whenever we need to regenerate snapshots, the PR becomes __massive__.

We would like to have the functionality within Playwright to create and manage a single file containing these hashes.

**Comment by yury-s** [comment]
To make sure I understand your request correctly, you do something like 
```ts
expect(md5(await page.innerHTML('body'))).toMatchSnapshot();
```
and you'd like the expected value to be written in a file shared between multiple tests rather than into a separate file for each expectation? Can you share a code snippet from your project to help us better understand the use case?

If you anyway compare md5 hashes why not use expect().toBe()
```js
expect(md5(await page.innerHTML('body'))).toBe(expectedHash(test.info()));
```
where expectedHash would load the expectation?

**Comment by yury-s** [comment]
Even though it doesn't help with putting expectations into one file, you might find [snapshotPathTemplate](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template) useful for organizing the snapshots.

**Comment by brochington** [comment]
> To make sure I understand your request correctly, you do something like
> 
> ```ts
> expect(md5(await page.innerHTML('body'))).toMatchSnapshot();
> ```

Yes, in essence. 

> 
> and you'd like the expected value to be written in a file shared between multiple tests rather than into a separate file for each expectation? Can you share a code snippet from your project to help us better understand the use case?
> 

```ts
import { test, expect, Page } from '@playwright/test';
import crypto from 'crypto';

import { extractSanitizedDOMString } from 'someplace/special';

async function getDOMcontent(page: Page, selector: string): Promise<string> {
  return page.evaluate(async (s) => {
    const el = document.querySelector(s);

    // For our needs, it's necessary to remove certain attributes from the DOM
    return extractSanitizedDOMString(el);
  }, selector);
}

export async function compareContentsToSnapshot(
  contents: string,
  snapshotPath: string[]
) {
  // Right now this creates a lot of individual files. Its a tradeoff between
  // having a lot of files, or reimplementing the snapshot testing logic.
  const hash = crypto.createHash('md5').update(contents).digest('hex');

  await expect(hash).toMatchSnapshot(snapshotPath);
}

test('test', async ({ page }) => {
  const content = await getDOMcontent(page, 'selector');

  await compareContentsToSnapshot(content, ['test.txt']);
});
```


> If you anyway compare md5 hashes why not use expect().toBe()
> 
> ```js
> expect(md5(await page.innerHTML('body'))).toBe(expectedHash(test.info()));
> ```
> 
> where expectedHash would load the expectation?

Because then we would need to replicate the save/compare logic that is already present in snapshots.

**Comment by brochington** [comment]
> Even though it doesn't help with putting expectations into one file, you might find [snapshotPathTemplate](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template) useful for organizing the snapshots.

We do use `snapshotPathTemplate`, and it is indeed super useful!

**Comment by yury-s** [comment]
> Because then we would need to replicate the save/compare logic that is already present in snapshots.

toMatchSnapshot's diff will be no more useful than that of expect.toBe as the hashes will differ a lot even for small DOM differences. As far as I understand the main benefit is leveraging update snapshot functionality, but with some modifications compareContentsToSnapshot can also work in a mode where it updates or checks expectations based on e.g. an environment variable. Given how niche the use case is we are unlikely to implement this. I'll keep the bug open for now to see if there is more interest in the feature.

**Comment by brochington** [comment]
> toMatchSnapshot's diff will be no more useful than that of expect.toBe as the hashes will differ a lot even for small DOM differences. 

Sure, this is why we do a decent amount of cleaning of the DOM, but for our cases (data vis library comparing many svg elements) it is good means of detecting changes.

For our use, the snapshot is stringified DOM, but it might as well be a large body of text, e.g. blog articles. Hashing the content would still be helpful in this case, but this is something that could still be done by the developer. It's not the main "ask", which is being able to find a path that is built into Playwright that avoids linear growth of file count to snapshots taken.

> As far as I understand the main benefit is leveraging update snapshot functionality, but with some modifications compareContentsToSnapshot can also work in a mode where it updates or checks expectations based on e.g. an environment variable.

Yes, `compareContentsToSnapsot` could be modified to access a file that is manually created, containing keys corresponding to the snapshot values, but there is a decent amount of logic to that, some of which is essentially duplication of snapshot functionality. 

If I may back up a bit, I would offer the feature of adding a flag in the config, maybe something like `manageSnapshotsInSingleFile`, that would write all snapshots in a single file. What is being snapshot'ed can then be the responsibility of the dev.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
