### ISSUE TITLE
Test lists

### ISSUE THREAD

**Issue by solomon23** [microsoft/playwright#22109]
This plugin doesn't seem to work friendly with test lists as described in the docs here - https://playwright.dev/docs/next/test-parallel#use-a-test-list-file

I'll got the run icons 
<img width="650" alt="image" src="https://user-images.githubusercontent.com/857744/229001681-a7a88b8b-3f8b-49f1-86e8-1673e955c0ea.png">

but clicking them does this

<img width="454" alt="image" src="https://user-images.githubusercontent.com/857744/229001729-fc220a9a-6338-44e2-a621-9d23211b399d.png">

and in the list file weirdly i'm only able to run the first one

<img width="569" alt="image" src="https://user-images.githubusercontent.com/857744/229003082-dfb996c7-b0b4-47f4-8fe5-39c2123ba936.png">

**Comment by yury-s** [comment]
Playwright supports cases with tests lists in a best effort manner and may not work correctly from vs code extension and in some scenarios with tracing. We are not planning to change that.

**Comment by spartacruz** [comment]
Hi @yury-s 
Just curious, is there any specific reason why Playwright team dont want to deal with this issue? My thoughts, this feature will be useful.

**Comment by berengamble** [comment]
I would also like to know why this is not supported fully.
