### ISSUE TITLE
[BUG] BaseUrl does not work in the .env file when using the UI Mode

### ISSUE THREAD

**Issue by suprunchuk** [microsoft/playwright#22113]
I use a dynamic baseUrl that I write in the file .gitlab-ci.yml. For example, when tests are run on each subdomain from the repository branch. But when opening the UI mod, this feature does not work.

### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code
**playwright.config.ts**
```js
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';
import dotenv from 'dotenv';
dotenv.config();

const config: PlaywrightTestConfig = {
  testDir: './tests',
  timeout: 30 * 1000,
  expect: {
    timeout: 5000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    actionTimeout: 0,
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    // {
    //   name: 'firefox',
    //   use: {
    //     ...devices['Desktop Firefox'],
    //   },
    // },

    // {
    //   name: 'webkit',
    //   use: {
    //     ...devices['Desktop Safari'],
    //   },
    // },

  ],
};

export default config;
```

**example.spec.ts**

```js
import { test, expect } from '@playwright/test';

test.use({
  baseURL: process.env.BASEURL
});

test('has title', async ({ page }) => {
  await page.goto('/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});
```

**package.json**
```js
{
  "name": "playwright",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.32.1"
  },
  "dependencies": {
    "dotenv": "^16.0.3"
  }
}
```

**.env**
```
BASEURL=https://playwright.dev
```

**Steps**
- Engage with a new flag `--ui`

`npx playwright test --ui`

**Expected**

The test should be successful, the base url should work from the .env file

**Actual**

`Protocol error (Page.navigate): Cannot navigate to invalid URL`

![1](https://user-images.githubusercontent.com/57152612/229120964-3508685f-f526-4b46-b92d-50c19d325dfe.png)

**Comment by ltsuda** [comment]
You have to set the baseURL in the config file

https://playwright.dev/docs/test-parameterize#env-files

**Comment by yury-s** [comment]
I cannot reproduce it locally with playwrighg 1.32.1, can it be that someone overrides  process.env.BASEURL? Try logging `process.env.BASEURL` from the config right after `dotenv.config();` to make sure it is loaded correctly.

**Comment by suprunchuk** [comment]
> I cannot reproduce it locally with playwrighg 1.32.1, can it be that someone overrides process.env.BASEURL? Try logging `process.env.BASEURL` from the config right after `dotenv.config();` to make sure it is loaded correctly.

I added the base URL to the config, and everything worked. But what about without a configuration file? I don't use it, I just write baseUrl in test.use and nothing works.

**Comment by suprunchuk** [comment]
> I cannot reproduce it locally with playwrighg 1.32.1, can it be that someone overrides process.env.BASEURL? Try logging `process.env.BASEURL` from the config right after `dotenv.config();` to make sure it is loaded correctly.

Can you try to reproduce it? Here is the [repository ](https://github.com/suprunchuk/repro_playwright) with the code

**Comment by yury-s** [comment]
I can't reproduce it either with the repro you shared. Make sure you don't have BASEURL in your environment.
