### ISSUE TITLE
[BUG] vscode extenstion - browserType.launch: Timeout 180000ms exceeded

### ISSUE THREAD

**Issue by boldt** [microsoft/playwright#22117]
### System info
- Playwright Version: 1.31.2
- vscode extension 1.0.9
- Operating System: Windows 10
- Browser: Chromium

**Steps / Actual**

I can run my test in the console with `npx playwright@1.31.2 test`, they finish with the result:

```
11 passed (3.7m)
```

If I run the same tests with the [vscode extension](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright), with the "show browser" checkbox  **not selected**, I get:

```
11 passed (3.6m)
```

If I run the same with with the "show browser" checkbox **selected**, I get:

```
browserType.launch: Timeout 180000ms exceeded
```

**Expected**

The timeout should not happen with the vscode extension, when I run my tests with the checkbox selected.

**Comment by yury-s** [comment]
Can you share a sample project where this happens so that we can reproduce this locally? Also please try to run it with latest playwright (1.32.1) to see if it still reproduces there.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro when you get back to this.
