### ISSUE TITLE
[BUG] Cannot navigate to URL with "www" prefix

### ISSUE THREAD

**Issue by 666f78** [microsoft/playwright#22110]
### System info
- Playwright Version: v1.32.0
- Operating System: All
- Browser: All

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    trace: 'on-first-retry',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});

```

**Test file (self-contained)**

```js
import { test } from "@playwright/test";

test("BUG", async ({ page }) => {
	await page.goto("https://www.demo.playwright.dev/todomvc");
});

test("BUG2", async ({ page }) => {
	await page.goto("www.demo.playwright.dev/todomvc");
});
```

**Steps**
- Run the test

**Expected**

Browser is open with URL

**Actual**

An issue with navigation `Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL`

**Comment by mxschmitt** [comment]
This is expected, you need to add http or https protocol before it.

**Comment by mxschmitt** [comment]
This is also expected, since we don't serve the demo site on `https://www.demo.playwright.dev/todomvc` only on `https://demo.playwright.dev/todomvc`. In technical terms, we only service it on the demo subdomain.

**Comment by mxschmitt** [comment]
I see two errors:

```

Running 2 tests using 2 workers
  1) [chromium] › example.spec.js:9:1 › BUG2 ───────────────────────────────────────────────────────

    Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
    =========================== logs ===========================
    navigating to "www.demo.playwright.dev/todomvc", waiting until "load"
    ============================================================

       8 |
       9 | test("BUG2", async ({ page }) => {
    > 10 | 	await page.goto("www.demo.playwright.dev/todomvc");
         | 	           ^
      11 |   console.log(await page.url())
      12 | });
      13 |

        at /tmp/webkit-salt-file/tests/example.spec.js:10:13

  2) [chromium] › example.spec.js:5:1 › BUG ────────────────────────────────────────────────────────

    Error: page.goto: net::ERR_NAME_NOT_RESOLVED at https://www.demo.playwright.dev/todomvc
    =========================== logs ===========================
    navigating to "https://www.demo.playwright.dev/todomvc", waiting until "load"
    ============================================================

      4 |
      5 | test("BUG", async ({ page }) => {
    > 6 | 	await page.goto("https://www.demo.playwright.dev/todomvc");
        | 	           ^
      7 | });
      8 |
      9 | test("BUG2", async ({ page }) => {

        at /tmp/webkit-salt-file/tests/example.spec.js:6:13

  2 failed
    [chromium] › example.spec.js:5:1 › BUG ─────────────────────────────────────────────────────────
    [chromium] › example.spec.js:9:1 › BUG2 ────────────────────────────────────────────────────────
```

First is an error from Playwright that the URL you are passing is invalid and the second is basically that the site is not reachable (DNS resolving error).

What do you expect to happen differently?

**Comment by 666f78** [comment]
> I see two errors:
> 
> ```
> 
> Running 2 tests using 2 workers
>   1) [chromium] › example.spec.js:9:1 › BUG2 ───────────────────────────────────────────────────────
> 
>     Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
>     =========================== logs ===========================
>     navigating to "www.demo.playwright.dev/todomvc", waiting until "load"
>     ============================================================
> 
>        8 |
>        9 | test("BUG2", async ({ page }) => {
>     > 10 | 	await page.goto("www.demo.playwright.dev/todomvc");
>          | 	           ^
>       11 |   console.log(await page.url())
>       12 | });
>       13 |
> 
>         at /tmp/webkit-salt-file/tests/example.spec.js:10:13
> 
>   2) [chromium] › example.spec.js:5:1 › BUG ────────────────────────────────────────────────────────
> 
>     Error: page.goto: net::ERR_NAME_NOT_RESOLVED at https://www.demo.playwright.dev/todomvc
>     =========================== logs ===========================
>     navigating to "https://www.demo.playwright.dev/todomvc", waiting until "load"
>     ============================================================
> 
>       4 |
>       5 | test("BUG", async ({ page }) => {
>     > 6 | 	await page.goto("https://www.demo.playwright.dev/todomvc");
>         | 	           ^
>       7 | });
>       8 |
>       9 | test("BUG2", async ({ page }) => {
> 
>         at /tmp/webkit-salt-file/tests/example.spec.js:6:13
> 
>   2 failed
>     [chromium] › example.spec.js:5:1 › BUG ─────────────────────────────────────────────────────────
>     [chromium] › example.spec.js:9:1 › BUG2 ────────────────────────────────────────────────────────
> ```
> 
> First is an error from Playwright that the URL you are passing is invalid and the second is basically that the site is not reachable (DNS resolving error).
> 
> What do you expect to happen differently?

As example, in chrome when we put a www.site.com, they cut the link and add protocol automatically

**Comment by geromegrignon** [comment]
In my opinion, Playwright should not be responsible for interpreting the URL: that's a testing tool. It should strictly test what you provide.
