### ISSUE TITLE
[BUG] Error: test file "tests/fixture-test.spec.ts" should not import test file "fixtures/test.ts"

### ISSUE THREAD

**Issue by notmessenger** [microsoft/playwright#22114]
### System info
- Playwright Version: Version 1.32.0
- Operating System: OS X Ventura 13.2.1
- Browser: Chrome

This is the same issue as reported in https://github.com/microsoft/playwright/issues/21979 except that my path structure is _applications/kb-articles/tests/e2e/fixtures/test.ts_ and I have to rename _test.ts_ to any other name for this work without throwing the error.

**The fixture**
```
// @ts-check
import { test as base } from '@playwright/test';

exports.test = base.extend({
  page: async ({ page, playwright }, use, testInfo) => {
    ...
  },
});
```

**Using it**
`import { test } from '../fixtures/test';`

**Comment by yury-s** [comment]
This is working as expected, `test.ts` is considered a test file by default. Please rename it to avoid the error.

**Comment by shairez** [comment]
thanks @yury-s !

I tried to expose a util function from one spec file to be used by another (not depending on specific tests, just that function), and I wanted to avoid creating an extra file.

So I'd like to understand - what's the reason behind this limitation? is it not possible? or just a best practice?

thanks

**Comment by yury-s** [comment]
After a long debate it [was changed](https://github.com/microsoft/playwright/pull/22440) to not count `test.ts` as a test file by default.

**Comment by shairez** [comment]
Thanks @yury-s !

My question is more general about tests not being able to import from other tests files

I'd like to import a test driver from one test and use it in another, but with this limitation I have to create a separate file.

So just to reason about this, I wondered what are the limitations which led you to decide to not allow it

Thanks! 🙏
