### ISSUE TITLE
[BUG] - playwright UI feature runs global-setup.ts before opening the UI

### ISSUE THREAD

**Issue by IrfanSyed-PSC** [microsoft/playwright#22134]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

**Add global-setup.ts to playwright.config.ts**

```ts
// playwright.config.ts
export default defineConfig({
  testDir: './tests',
  globalSetup: require.resolve('./global-setup'),
});
```

**global-setup.ts file**

```ts
import { expect,chromium, FullConfig } from '@playwright/test';
import { request } from '@playwright/test';

async function globalSetup(config: FullConfig) {

  const browser = await chromium.launch();
  const page = await browser.newPage();

  await page.goto('https://idonotexistIthinkwhatdoyousay');
  await browser.close();

}

export default globalSetup;
```

Is global-setup.ts still a recommended way or is there a better option ?

**Comment by pavelfeldman** [comment]
UI will run global setup on start and global teardown on exit. That way you don't need to repeat expensive environment setup on watch. There is a better alternative to the global setup, which is project dependencies. Will definitely work better for your use case, but it won't help with the UI, dependencies are also not ran, for the same reason.

**Comment by IrfanSyed-PSC** [comment]
I tried dependencies and I was able to load the UI, but I have problems with displaying the tests. My tests were in a folder named "tests" and the UI did not display the tests and only showed the dependency file.

**Comment by pavelfeldman** [comment]
You need to select the projects.

**Comment by IrfanSyed-PSC** [comment]
I see it now. As you said I cant use this as a the UI is not running this file either while running the test. it is just running the test. So this option also does not work.

**Comment by pavelfeldman** [comment]
Could you be more specific in providing exact steps to perform, actual results and expectations? Otherwise I'm not sure what you are referring to.

**Comment by IrfanSyed-PSC** [comment]
The expectation is when you run any tests from the UI, it should also execute the dependencies from the UI but it doesnt. Here is an example of executed test

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/4980960/230392886-6e6f78b1-d80c-4960-b5eb-a06768977921.png">


```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'login',
      testMatch: '**/*.setup.ts',
    },
    {
      name: 'tests',
      testDir: './tests',
      dependencies: ['login'],
      use: {
        ...devices['Desktop Chrome'],
      },
    }
  ],

});

```

```ts

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/22045
