### ISSUE TITLE
[BUG] component testing configuration cannot be overridden 

### ISSUE THREAD

**Issue by phungleson** [microsoft/playwright#22136]
Hi,

I wanted to overwrite some vite configuration when doing component testing.

From the definition:

https://github.com/microsoft/playwright/blob/main/packages/playwright-ct-react/index.d.ts#L33

<img width="791" alt="image" src="https://user-images.githubusercontent.com/93457/229267255-1c113c2e-9756-43e9-9cc8-5d05ffadb79a.png">

It looks like I can do it at top level, something like this: 

<img width="517" alt="image" src="https://user-images.githubusercontent.com/93457/229267293-0ae03c05-7802-42ae-895c-a7238d0bb7b9.png">

But it does not work.

I looked into the code the actually the configuration need to be at the first project.

https://github.com/microsoft/playwright/blob/main/packages/playwright-test/src/plugins/vitePlugin.ts#L61

<img width="556" alt="image" src="https://user-images.githubusercontent.com/93457/229267404-38f81c59-d9e2-44ab-8ac3-b37de53b70f1.png">

I moved the configuration to that area then it works.

I am not sure which way it should be going forward?

At first glance, the configuration should be at top level, in that case we should fix `vitePlugin.ts`

If we want to keep in first project, then we should fix the type definition to make it less misleading.

### System info
- Playwright Version: v1.32.1
- Operating System: N/A
- Browser: N/A
- Other info:

### Source code

N/A

**Link to the GitHub repository with the repro**

N/A

or

**Config file**

N/A

**Test file (self-contained)**

N/A

**Steps**

N/A

**Expected**

N/A

**Actual**

N/A

**Comment by sand4rt** [comment]
Hi @phungleson, do you have an example GitHub repo i could take a look at?

**Comment by phungleson** [comment]
Hi @sand4rt

It turns out not an issue of playwright, but me having double `use` (one generated by playwright cli which I wasn't aware) in my config.

Thanks for looking into this, cheers!
