### ISSUE TITLE
[Feature] - New UI, please add autofocus to running tests

### ISSUE THREAD

**Issue by DavitV-yan** [microsoft/playwright#22140]
Now when you run the few tests, you should click on the next test to see the timeline and the test steps
https://drive.google.com/file/d/1PJy-hWc4eJeuDZqWiEYBLr7tPSoHRuHW/view?usp=sharing

**Comment by pavelfeldman** [comment]
How would you suggest this works when 5 tests are running concurrently?

**Comment by DavitV-yan** [comment]
It should work for the test file, autofocus should be on the running test in the test file, so here is not important how many tests are running

**Comment by pavelfeldman** [comment]
What if two tests in the same file are running at the same time?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
