### ISSUE TITLE
[BUG] HTML reporter is listing tests in wrong order

### ISSUE THREAD

**Issue by msorens** [microsoft/playwright#22143]
While my tests are executing in the correct sequence the HTML reporter is reporting them in the wrong order.
After a little digging I figured out why:
the HTML reporter is sorting by line numbers (highlighted below) but _**without**_ accounting for the presence of multiple files.
Notice in the illustration that I have circled all the line numbers. All these tests, and a dozen or so more omitted for brevity, are in strictly monotonically increasing order. That is WRONG.
If they were all in the same file, sorting by line number would always be correct. But because they are in different files, the test order is essentially randomized by sorting only by line number.
<img width="582" alt="image" src="https://user-images.githubusercontent.com/6817500/229327586-c9eed2e8-a0b8-4b7b-a18c-90fd97be6bc0.png">

The correct order for the steps shown is:
```
k8s > create cluster > kind create cluster
k8s > 1. initialize system > add new system
k8s > 1. initialize system > install system
k8s > 2. verify mutating policies > mutating json patch: Add
k8s > 3. verify validating and mutating policies > validating policy
k8s > 4. verify context aware policies > validating policy
```

### System info
- Playwright Version: v1.32
- Operating System: macOS 12.6
- Browser: Chromium
- Other info: NA

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
export default defineConfig({
  testDir: 'tests',
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      }
    }
  ]
})
```

**Test files (self-contained)**

Test file: main.spec.js
```js
import firstTest from '.first.js'
import secondTest from '.second.js'

import {test} from '#test'

test.describe('main', () => {
  test.describe('should run first', firstTest)
  test.describe('should run second', secondTest)
})
```

Test file: first.js
```js
import {expect, test} from '#test'

// comments simply to push the definition of the test to start at a higher line number
// comment
// comment
// comment
// comment
export default function () {
  test('test in first.js', async () => {
    expect(5).toBeTruthy()
  })
}
```

Test file: second.js
```js
import {expect, test} from '#test'

export default function () {
  test('test in second.js', async () => {
    expect(5).toBeTruthy()
  })
}
```

**Steps**
- `npx playwright test`
- `npx playwright show-report`

**Expected**

```
  ✓  1 [chromium] › k8s/first.js:9:3 › main › should run first › test in first.js (5ms)
  ✓  2 [chromium] › k8s/second.js:4:3 › main › should run second › test in second.js (1ms)
```
Then in the report view:
<img width="401" alt="image" src="https://user-images.githubusercontent.com/6817500/229328020-193cd212-893d-4e17-bfb8-3d299c72b703.png">

**Actual**

```
  ✓  1 [chromium] › k8s/first.js:9:3 › main › should run first › test in first.js (5ms)
  ✓  2 [chromium] › k8s/second.js:4:3 › main › should run second › test in second.js (1ms)
```
Then in the report view:
<img width="385" alt="image" src="https://user-images.githubusercontent.com/6817500/229327941-70f30921-346a-49f8-b134-37d629a5a0f8.png">

**Comment by msorens** [comment]
Not sure that applies, @pavelfeldman ...? the tests are already being run in the correct order; it is simply the reporting that is wrong.

**Comment by Georgegriff** [comment]
I see the suggestion to use projects, it's not a huge deal but i think projects have the same issue.

I took a look at the generated report.json file the html-reporter code uses the project order neither matches the order defined in projects array source OR a logical order based on dependencies. Not a big deal but would be nice if projects in the report were ordered based on what actually ran first. 

If this is a separate issue i can try to provide a replication case?

**Comment by dgozman** [comment]
@Georgegriff You can attach a repro here, or file a new issue. I hope that the fix would be the same, but just to make sure we cover your case as well, a repro would be great.

**Comment by Georgegriff** [comment]
@dgozman Here's a repro

<img width="1485" alt="image" src="https://user-images.githubusercontent.com/9056958/230719388-83f1eaba-5f11-41c4-8c0b-15aa1e16da6e.png">

Can see based on dependencies the projects run in the order `data-setup`, `user-setup` `chromium` but the order in the report is slightly off. Like i say its not a big deal, just nice to have i suppose.

Code:

playwright.config.js
```ts
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  reporter: [["html", { open: "always" }]],
  projects: [
    {
      name: "data-setup",
      testMatch: "**/data.setup.ts",
    },
    {
      name: "user-setup",
      testMatch: "**/users.setup.ts",
      dependencies: ["data-setup"],
    },
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
      testMatch: "**/*.spec.ts",
      dependencies: ["user-setup"],
    },
  ],
});

``` 

Doesn't really matter what the test files do, so I've omitted them but here's a screen shot of the runner output.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/9056958/230719459-d860c1da-a5fc-469a-86a1-931fe55bf613.png">


P.S. the projects addition with dependencies was a stroke of genius, thank you playwright 💯  can coordinate complex setup code using it
