### ISSUE TITLE
[Feature] Support for headless=new in Chrome 112+

### ISSUE THREAD

**Issue by doliere** [microsoft/playwright#22148]
Chrome 112+ supports the [new headless mode](https://developer.chrome.com/articles/new-headless/)
Puppeteer already supports it. Would it be possible to have it added to Playwright for Chromium as well

**Comment by mxschmitt** [comment]
See https://github.com/microsoft/playwright/issues/21194#issuecomment-1444276676 how to set it but be aware that its much slower: https://github.com/microsoft/playwright/issues/21216#issuecomment-1446678795

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
