### ISSUE TITLE
[Feature] Add equivalent method to await elementHandle.ownerFrame() for the Locator class

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#22157]
Hello team!

Following your recommendation - most of us use the Locator class instead of the ElementHandle. 

In several of our tests, we use the following API:
`await elementHandle.ownerFrame()` 

This API can be used only with ElementHandle elements, which is not recommended. 

Is it possible to add something equivalent for the Locator class APIs?

**Comment by pavelfeldman** [comment]
You would not typically need owner frame if you are using the frame locators: https://playwright.dev/docs/next/release-notes#frame-locators. Could you tell us more about your use case?

**Comment by AlexKomanov** [comment]
@pavelfeldman 
Basically it is some old tests that we just translate to the Locator API instead of ElementHandle.

I'll check the option you mentioned with FrameLocator.

**Comment by AlexKomanov** [comment]
Thanks @pavelfeldman  - it helps. I close this one.
