### ISSUE TITLE
[BUG] Webkit giving "Unacceptable TLS certificate" error in github actions when opening iframe with https content

### ISSUE THREAD

**Issue by diginikkari** [microsoft/playwright#22154]
### System info
- Playwright Version: v1.32.1
- Operating System: Ubuntu (Github action runner no docker)
- Browser: WebKit
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```jsx
            <iframe
                title="Walls.io"
                allowFullScreen
                id="wallsio-iframe"
                src={`//my.walls.io/j4z3r?nobackground=1&amp;show_header=0`}
                style={{
                    border: 0,
                    height: '800px',
                    width: '600px',
                }}
                loading="lazy"
            ></iframe>
```

**Link to the GitHub repository with the repro**

[https://github.com/diginikkari/webkit-issue](https://github.com/diginikkari/webkit-issue)

**Test file (self-contained)**

```js
test('has title', async ({ page }) => {
    await page.goto('http://127.0.0.1:5173/');

    // Expect a title "to contain" a substring.
    await page.frameLocator('#wallsio-iframe').getByText('j4z3r').click();
});

```

**Steps**
- [Run the test]
- [...]

**Expected**

Test should pass.

**Actual**

Test is failing in webkit when runned in github actions with **ubuntu-latest** -runner. In trace it is showing: `Failed to load resource: Unacceptable TLS certificate` error. 

Tests are working fine in MacOs. Tests are also working when using Docker image: `mcr.microsoft.com/playwright:v1.32.0-focal`. This could be related to #15410.

**Comment by mxschmitt** [comment]
I can reproduce on our Docker container as well. Minimal repro:

```ts
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://my.walls.io/j4z3r?nobackground=1&amp;show_header=0');
});
```

Expected: Works
Actual: Throws `Unacceptable TLS certificate`

Abstract: WebKit does not like the SSL certificate of my.walls.io while Firefox and Chromium accepts it.

**Comment by pavelfeldman** [comment]
Unlike Chromium, WebKit is using the network stack either belonging to the underlying operating system (macOS) or via the open source network stack library (libsoup on Linux and libcurl on Windows). These libraries use their own means to manage TLS and the trusted authorities and the way they consult them can vary. You can probably observe the same result if you are using an Epiphany browser on Linux.

**Comment by mxschmitt** [comment]
I pinged the folks at walls.io. We cannot do anything here from our side, since this is caused most likely by a configuration issue of their webserver which ends up that libsoup -> WebKit Linux networking stack -> e.g. Epiphany browser or our WebKit on Linux to not like their SSL certificate.

Potentially also a bug in libsoup, so we could try filing it here: https://gitlab.gnome.org/GNOME/libsoup/-/issues maybe they instantly know whats going wrong.

**Comment by v2p** [comment]
Hi! Developer from walls.io is here :) We saw your support request, and my colleagues did the job. Feel free to try again!

**Comment by diginikkari** [comment]
@v2p Thanks! Can confirm, my test is now working. Thanks @mxschmitt and @pavelfeldman for your investigation. This was a nasty one for me. Lost a lot of time because I was not able to figure out what was the real reason 🙏

**Comment by v2p** [comment]
Thanks everyone for taking care of it!

**Comment by mxschmitt** [comment]
Thanks @v2p amazing!
