### ISSUE TITLE
Accessing Selenium Grid SessionId (and logs in general?)

### ISSUE THREAD

**Issue by kelmelzer** [microsoft/playwright#22167]
I've implemented Playwright alongside Selenium in a test automation framework, and we instantiate all of our browsers through Selenium Grid (if possible). I have a requirement to save the session id in case I needed to later kill the automation by session id during the run.

I poked around in the typescript and saw Playwright does log the session id in the _launchWithSeleniumHub method in chromium.ts, so I was wondering if the that is something that can be more easily exposed?

Also, is there a way I can access the Playwright logs stream in general (outside of errors) via C#?

**Comment by pavelfeldman** [comment]
It looks like your question is largely outside of the scope for Playwright, so you are mostly on your own with this request / question.

**Comment by kelmelzer** [comment]
> It looks like your question is largely outside of the scope for Playwright, so you are mostly on your own with this request / question.

Yeah, I could understand that from the base playwright perspective. I'm not sure why it was migrated out of the dotnet project...

It looks like the Playwright.CreateAsync() method and StdIOTransport object could be extended to access the console logs, like it already is doing for the error stream. I might try on my own with the source code and see what I can do.

**Comment by pavelfeldman** [comment]
stdout is used as a pipe transport between the two, so I don't think your plan will work. It would be best to describe your use case from a client point of view, so that we understood exactly what you want to achieve. I.e. provide the snippet of the code, where and how you want to get the id, etc.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
