### ISSUE TITLE
[BUG] Element found but cannot perform action

### ISSUE THREAD

**Issue by jocastaneda17** [microsoft/playwright#22165]
### System info
- Playwright Version: [1.28.0]
- Operating System: [Windows 11.]
- Browser: [ Firefox, Chrome]
- Other info:

### Source code

    await this.page.locator('[id="cShoppingCartNote"]').fill('Test New Application')
    await this.page.locator('[id="cApplicationOrigin"]').selectOption('direct')
    await this.page.locator('[id="iActivitySourceID"]').selectOption('3')

**Expected**

Elements are Visible so should be able to do action Click(), fill(), selectOption()

**Actual**

Although elements are visible but the function is not executed (waiting for locator tests does not proceed)

![2023-04-03_23h47_38](https://user-images.githubusercontent.com/51143602/229562607-4fc92ea2-0dde-448c-97bc-084853a035ca.png)

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we can reproduce. It is likely that something is wrong with the selector you are using, but we can't know for sure without being able to run it locally.

**Comment by jocastaneda17** [comment]
Here are some of the files to run the test.
https://github.com/jocastaneda17/playwright_project

please run this test execution command
npm run env:acceptance 002-emportal-new-application.spec.ts

**Comment by pavelfeldman** [comment]
I can't access this repo.

**Comment by jocastaneda17** [comment]
My apology im quite new with playwright and this github. Hope you can help me with my playwright issue not sure why its not usually working I have written quite a number of tests in playwright it just so happen i encountered this elements in our site that i cannot seem to automate.

I have made my repository public please try again hope you can replicate the issue thanks!

**Comment by pavelfeldman** [comment]
I can't extract this rar archive, sorry. We typically require users to follow the issue template and provide detailed explanation of the Playwright bug along with the steps we can perform to reproduce it locally. Otherwise we can't act on the bug.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
