### ISSUE TITLE
[BUG] Browser Context closing runs out of time when tests are launched inside a Docker container

### ISSUE THREAD

**Issue by DvDream** [microsoft/playwright#22166]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I am running a NodeJs application inside a Docker container and within the application I launch a spawn process through an endpoint which can run all my playwright tests whenever I want in this way:

```const pw_test = spawn('npx', ['playwright', 'test', `--config=tests_config_${date}.json`], { env: process.env , shell: true, detached: detach_child_process });```

 The Docker image is built through a Jenkins Job and the Cointainer is launched/updated with Portainer.

Everything went well for months but as the number of test grew, I thought to a way to speed up my test run. I solved by launching a Persistent Context which I can configure without any problems anymore (see this [issue](https://github.com/microsoft/playwright/issues/21750) to have an idea of what I am talking about). 

What I am experiencing right now is that when I launch my Docker Container in my local machine the tests run and the browser Context close within seconds (or, really, few minutes..) without any problem. Instead, launching tests inside the Container in remote lead the test run to be reeeally slow in execution and the Browser Context takes too long to close. I even get these kind of messages in my reports: 

![Immagine 2023-04-03 174528](https://user-images.githubusercontent.com/45291289/229560763-ec9b65b6-7537-4aff-97c5-6018b8d5beb9.png)

As you can see, I needed to increase the test timeout to 5 minutes but even with this "workaround" the problem still persists..
I also want to add that I checked that during the Chromium instance running there weren't any plug-ins active. 

**Steps**
- [Navigate to the URL where my remote Node Application is running]
- [Run the test through spawn process]
- [Wait for the test to finish]

**Expected**

The test finish (can fail, success, break) within seconds or 1/2 minutes max (depending on how the test is big)

**Actual**

The test remains stuck and the browser Context is too slow when closing, running out of time. Consequently, videos are not even recorded (but this is normal, is just to give another proof that the context is not normally close). 

Unfortunately I cannot provide any repro for this problem since there are different parts of program that are taking parts here..hope that you guys have any idea of how I can solve this problem..thank you!

**Comment by pavelfeldman** [comment]
Persistent context is largely incompatible with postmortem analysis such as tracing and videos. It runs for two long and accumulates too much data to be analysed / persisted. Hence the slow-down. You should also never use it because it allows leaking information between tests, it removed the isolation and tests start depending on one another. Consider using parallelism instead of this optimization. It'll make your tests run fast and won't create problems like this one.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
