### ISSUE TITLE
[Feature] Support TypeScript's `--moduleResolution bundler`

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#22169]
Copying from https://github.com/microsoft/playwright/issues/19710#issuecomment-1454132730 by @danieldiekmeier:

---

In TypeScript 5.0, there (probably) will be a new module resolution option: `--moduleResolution bundler`: https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler

I installed the TypeScript 5.0 Beta because I also want to use imports without extensions in Playwright. Sadly, it still does not seem to work. Are there plans to update Playwright to also support `--moduleResolution bundler`?

**Comment by kristojorg** [comment]
In general it would be nice to have more of the transpiler exposed to users to change as needed.

**Comment by TrungSofistic** [comment]
Just want an update on this feature. Is this feature release? 
Is the current v1.54 support moduleResolution='bundler'?
I'm on Playwright v1.54 and having issue with importing interfaces from a private shared package that uses moduleResolution='bundler'
