### ISSUE TITLE
Incognito mode

### ISSUE THREAD

**Issue by epsilonr** [microsoft/playwright#22175]
I must open multiple browsers and I am using a extension to prevent webrtc leaks. My problem is I can't load extensions in incognito mode. I can't use launch persistent context because I must open multiple browsers at the same time. in non-headless mode I can do it with going chrome://extensions and enabling it with page.evalueate(...) but this doesn't work either in headless mode. What can I do?
how to disable incognito mode with normal launch.

**Comment by pavelfeldman** [comment]
This falls outside of the scope for Playwright.

**Comment by epsilonr** [comment]
Then is there anyway to load an extension while in incognito mode?

**Comment by pavelfeldman** [comment]
> I can't use launch persistent context because I must open multiple browsers at the same time.

You can do that if you point them to different user data dirs.
