### ISSUE TITLE
[BUG] Browser closes unexpectedly when a test fails during Playwright Test execution

### ISSUE THREAD

**Issue by hardeepCDX** [microsoft/playwright#22181]
### System info
- Playwright Version: [1.32.2]
- Operating System: [Windows 11]
- Browser: [Chrome]
- Other info: I haven't tested on other browsers and I can see this issue with versions above 1.30.0 

**Title:** Browser closes unexpectedly when a test fails during Playwright Test execution

**Description:** When running Playwright Test using the VSCode extension and executing a test suite with two spec.ts files in the same folder, the browser unexpectedly closes and relaunches when the first test fails. This behavior is not expected, as the browser should continue to remain open even if a test fails within the suite.

**Steps to Reproduce:**
1. Open VSCode and install the Playwright Test extension.
2. Create a test suite with two spec.ts files in the same folder.
3. Add at least one test to each spec file.
4. Execute the test suite using the "Run Test" option on the folder.
5. Observe the behavior of the browser during the execution of the tests.

**Expected Results:**
The browser should remain open throughout the entire execution of the test suite, regardless of whether any individual test fails.

**Actual Results:**
When the first test fails during the execution of the test suite, the browser unexpectedly closes and then relaunches before the next test is executed.

**Comment by pavelfeldman** [comment]
When I repeat these steps I don't see the browser window at all (it runs headlessly). Is something missing in your steps?

**Comment by hardeepCDX** [comment]
I have noticed that when the first test suite is finished and I manually initiate the second test suite, the browser is relaunched as well. FYI @pavelfeldman

**Comment by pavelfeldman** [comment]
Should be fixed in a patch release, please update!
