### ISSUE TITLE
[BUG] Playwright does not detect running webserver because webserver responds with 302 instead of 200

### ISSUE THREAD

**Issue by 54b7hr707h** [microsoft/playwright#22196]
**Expected**

I expect playwright to accept the webserver as running when it responds with a well-formed HTTP response, even if it is not a 200. 

If not the above, I would instead expect a way to configure the healthcheck, either to use a different path than /, or to broaden what status codes are considered healthy. 

**Actual**

Playwright is not accepting a 302 status code as a valid response to indicate the server as being UP. It continues to poll, never succeeding until the deadline is exceeded and it exits.

**Comment by mxschmitt** [comment]
Hey!

There is actually a bug inside the webServer implementation which we are working on fixing for the next release. (it is about not following the redirects correctly)

Regarding your use-case: would it be fine for you if the webServer would follow the URLs correctly and then wait for a 2XX at the final request?

Are you passing a `"url"` or `"port"` to the `"webServer"`?

**Comment by 54b7hr707h** [comment]
@mxschmitt 

Yes, if it followed until reaching a 200 that would work for me. 

I am passing it a url, which includes the port.. could I also include a path in the url option?

**Comment by 54b7hr707h** [comment]
@mxschmitt adding a path worked! thank you. For me, this is resolved given I can config with the url option like that
