### ISSUE TITLE
[question]how to wait until a table has no busy indicator

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#22192]
I have a table element, it has an "add" button, if I add a row to the table , before the new row appears
the table is "busy"
I use     
const tableHandle = await this.tableLocator.elementHandle();
    await tableHandle?.waitForElementState('stable');

then I use page.locator to find the new row, waitForElementState does not work, it turns out the new row cannot be found, because at this time the new  row has not appeared on the table. I do not want to use sleep command 

is there any other method that I can use to wait until the table is not busy to find the new row

**Comment by pavelfeldman** [comment]
The use of element handles is discouraged. If you use locators you won't need to wait for anything, just perform actions one after another.

**Comment by bodycombathuang** [comment]
any method to wait until the table is completely loaded with new rows?
