### ISSUE TITLE
[BUG] Extension doesn't work, but terminal commands do

### ISSUE THREAD

**Issue by VaarunNarang** [microsoft/playwright#22193]
**Context:**
- Playwright Version: Version 1.31.1
- Operating System:  Mac 13.1
- Node.js version: v16.14.2
- Visual Studio Code version: 1.77.0
- Playwright for VSCode extension version: v1.0.10
- Browser: Any
- Extra: This repo is using NX to organize the dependencies and modulize the project 

**Describe the bug**
All of my playwright commands work in the terminal, but the extension doesn't work for showing the tests, running, debugging, recording, etc. I am able to use the extension on other repos so I think it isn't my VSCode.

**Comment by pavelfeldman** [comment]
Please follow the issue template and provide us with the steps we can perform in order to reproduce this problem locally. Extension works for others, so there is something specific to your setup that prevents it from working for you.
