### ISSUE TITLE
Set typescript esModuleInterop

### ISSUE THREAD

**Issue by testerez** [microsoft/playwright#22203]
Hello,
I'm trying to import my project's code into my playwright tests. I'm getting errors because my project is using `esModuleInterop`. But when importing from playwright, it looks like `esModuleInterop` is not enabled (I get `{ default: ... }` as result of some imports).
Would it be possible to follow the setting from project's `tsconfig.json`?

**Comment by pavelfeldman** [comment]
Could you provide a self-contained example in a form of a repo or a couple of snippets so that we could reproduce it locally. Your request is nuanced and I'd like to make sure we are fixing what you consider is broken.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
