### ISSUE TITLE
[Feature] Download progression

### ISSUE THREAD

**Issue by Yokutto** [microsoft/playwright#2220]
Hi,
I have an use case that I can need to test a download of 1Gi file. In this test I don't need the full archive to test to complete, I just need a few bytes of it to actually pass as "success task".

Saying that, I need something to give me a feedback of download progression in NodeJS, and It will be nice to have an event that fires when download progression is being made.

I see something similar in current DevTools Procotol ([link here](https://chromedevtools.github.io/devtools-protocol/tot/Page/#event-downloadProgress)).
However, I can't get the current the progression feedback with code below
```javascript
let client = await page.context().newCDPSession(page);
client.on('Page.downloadProgress', (result) => console.log(result));
```
I didn't see much of playwright source code, but I think that internally the playwright uses a CDPSession different from what is created, so I can't get the progress of the download even using the event from DevToolsClient

**Comment by pavelfeldman** [comment]
You get the `download` event after the HTTP response has been received, so technically you've already got few bytes. Or are you interested in fetching few bytes of an actual body and reading them? With the payload of that size, I can imagine that you would want to interrupt the actual download?

**Comment by Yokutto** [comment]
Yes, I need to cancel the download after something like 100Mb of 1Gi filesize. Maybe I can workaroud this total data transfered trough [setDataSizeLimitsForTest](https://chromedevtools.github.io/devtools-protocol/tot/Network/#method-setDataSizeLimitsForTest) in CDP, but this will affect global network, not only the downloaded file.

For cancelling a download, I think I can abort the connection trough page.route, but this sounds more like a 'hack' than a actual solution

I think having an event to get download progression is more useful for playwright users than using a CDPSession to workaround that

**Comment by pavelfeldman** [comment]
`Network.setDataSizeLimitsForTest` does not apply to downloads and `route` can't be aborted once allowed. So I don't think `CDPSession` helps in any way here. Closing the context might do the trick, I would check that. Otherwise, you need a proper cancel command even in Chromium. In others you need progress as well.

**Comment by pavelfeldman** [comment]
Thank you for reporting this issue and providing comments to those that might be facing a similar problem. I am now closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.

**Comment by vincerubinetti** [comment]
In my case I'm writing a Node script to scrape webpages, and it includes downloading a big CSV file for which it'd be nice to show the download progress on.

It looks like download progress is not actually a stable part of the Chrome Devtools Protocol yet, which may be an upstream blocker to implement this in Playwright?

https://chromedevtools.github.io/devtools-protocol/tot/Browser/#event-downloadProgress
