### ISSUE TITLE
[BUG] Assertion error

### ISSUE THREAD

**Issue by VadymLepishko** [microsoft/playwright#22208]
### System info
- Playwright Version: 1.32.1
- Operating System: Linux
- Python version: 3.7
- Browser: Firefox

### Source code
```
if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Assertion error
    at assert (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/utils/debug.js:29:21)
    at FrameManager.frameAttached (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/frames.js:103:25)
    at FFPage._onFrameAttached (/usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/firefox/ffPage.js:174:30)
    at FFSession.emit (node:events:513:28)
    at /usr/local/lib/python3.7/dist-packages/playwright/driver/package/lib/server/firefox/ffConnection.js:204:41

Node.js v18.15.0
```

### Describe the bug
I'm running a task in Celery using playwright (Firefox). And sometimes this error appears. What could be the problem?

**Comment by mxschmitt** [comment]
We need a clear reproduction to act on it. Please re-file with a reproduction script which surfaces the issue.

**Comment by Liftu** [comment]
I get the exact same assertion with python 3.9 and Firefox.
This seems to happen randomly so I can't give you a reproduction script for now.

**Comment by erdguez** [comment]
randomly having same problem; following this..

**Comment by 56wpc** [comment]
Same here, Python/Firefox. There's no way to handle this exception

**Comment by erdguez** [comment]
yes, did not find a way to handle this exception, python is not catching it.

**Comment by mxschmitt** [comment]
I'm going to lock this issue for now since +1 comments don't help debugging this issue further. For future users who run into it, please file a new issue with a reproduction, thanks!
