### ISSUE TITLE
[Feature]: tag support for beforeAll, afterAll, beforeEach afterEach hook

### ISSUE THREAD

**Issue by shashwatahalder01** [microsoft/playwright#22202]
I have tests with tags: @lite @pro, both tests are in one describe hook and also required beforeall hook. 
I need separate beforeAll hook for @lite  tagged tests and @pro tagged tests.

**Comment by pavelfeldman** [comment]
If preconditions are different for different tests, you should not use hooks and should rather use fixtures: https://playwright.dev/docs/next/test-fixtures. They allow preparing for each of your tests differently.
