### ISSUE TITLE
[BUG] Tests failing in toPass often marked as passed

### ISSUE THREAD

**Issue by max-te** [microsoft/playwright#22215]
### System info
- Playwright Version: [v1.32.2] (also observed on 1.31)
- Operating System: [Official Playwright Docker container] (also on my dev machine running Linux EndeavourOS)
- Browser: [All]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  fullyParallel: true,
  retries: 1,
  workers: undefined,
  reporter: "html",
  use: {
    trace: "retain-on-failure",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
      },
    },
  ],
});

```

**Test file (self-contained)**

```js
import { test, expect } from "@playwright/test";

test("do not pass", async ({ page }) => {
  await expect(async () => {
    await page.waitForTimeout(100);
    expect(1).toBeGreaterThan(2);
  }).toPass({ timeout: 0 });
});
```

**Steps**
- Run the test
- See the test pass or be flaky. (If it happens to actually fail rerun it once or twice.)

**Expected**

The test always fails with a test timeout.

**Actual**

The test passes about 50% of the times, most often on the retry. The report then looks like this

![grafik](https://user-images.githubusercontent.com/870074/230081256-a679f890-e827-41fa-985c-6834c87961f5.png)

**Comment by pavelfeldman** [comment]
This does not reproduce for me locally, I tried your config + test multiple times, then I reduced the timeout to 3000 and ran it with 10 retries. All the tests failed as expected. Sounds like you are running something different. Do you mind sharing it as a github repo?

**Comment by max-te** [comment]
I have a reproduction repo set up on my work machine, I'll try to put it up tomorrow

**Comment by max-te** [comment]
Here is the repro code from which I also got the screenshot above:
https://github.com/max-te/pw-issue-22215

**Comment by max-te** [comment]
Here is the repro code which I also used to get the screenshot above: https://github.com/max-te/pw-issue-22215

**Comment by max-te** [comment]
And here is output of that code passing on my machine:
```
$ docker run -it --rm -v $PWD:/repro --ipc=host mcr.microsoft.com/playwright:v1.32.2-focal /bin/bash
root@fc4d0a6812ef:/# cd /repro/
root@fc4d0a6812ef:/repro# npm test

> expect-repro@1.0.0 test
> playwright test


Running 2 tests using 2 workers
   2 passed (31.6s)

To open last HTML report run:

  npx playwright show-report

root@fc4d0a6812ef:/repro#
```

**Comment by max-te** [comment]
I managed to reproduce this in Github Actions: https://github.com/max-te/pw-issue-22215/actions/runs/4627505713/jobs/8185499316
Don't mind that I didn't get Firefox working there, but you can see the chromium test has passed
