### ISSUE TITLE
[Feature] better report for expect

### ISSUE THREAD

**Issue by Diokuz** [microsoft/playwright#22213]
We have a test:

```ts
test('Foo bar', async ({ }) => {
  expect('foo').toBe('bar')
});
```

and we have a report (html, allure, any other):

```
expect.toBe
```

Thats it)

<img width="221" alt="Screenshot 2023-04-05 at 13 39 12" src="https://user-images.githubusercontent.com/2929442/230057306-75cfc71e-d966-4adf-b89b-d396326995cc.png">

Allure version:

![image](https://user-images.githubusercontent.com/2929442/230057533-686b4214-bd68-4c6d-80a0-0aca35173ade.png)

At the same time we have a good log:

```
Error: expect(received).toBe(expected) // Object.is equality

    Expected: "bar"
    Received: "foo"
```

What do you think about improving report text to, say

```
expected 'foo' to be 'bar'
```

?

**Comment by pavelfeldman** [comment]
This is what my report looks like:

<img width="986" alt="Screenshot 2023-04-05 at 8 48 54 AM" src="https://user-images.githubusercontent.com/883973/230134659-79f7163a-ddd4-4957-aeeb-840c7c874cc7.png">

So are you saying you don't want to expand "expect" or that you are missing a large error above?

**Comment by pavelfeldman** [comment]
Please file this against allure project, they have all the same input as html report, so they should be able to make it work.
