### ISSUE TITLE
[BUG] Unable to download chrome - Running npx playwright install chrome

### ISSUE THREAD

**Issue by kieran1993** [microsoft/playwright#22216]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:
Command `npx playwright install chrome`
Log from Terminal:
```
Downloading Google Chrome
Installing Google Chrome
ERROR: failed to install Google Chrome
Failed to install browsers     
Error: Failed to install chrome
```

Chrome is installed on my machine.

Unable to run tests on Chrome Browser.

**Comment by pavelfeldman** [comment]
The error is probably due to the fact that the browser is already installed. Why are you running `npx playwright install chrome`, could you explain what your objective is along with the expectations of Playwright behavior?

**Comment by kieran1993** [comment]
Objective: Run my tests on Chrome Browser. 

In my config -> I have specified Chrome Browser, then when running tests using `--headed`, I get the error `Error: browserType.connect: Chromium distribution 'chrome' is not found`. Which then prompts me to run: `Run "npx playwright install chrome"`

**Comment by pavelfeldman** [comment]
It sounds like Playwright can't locate Chrome at its default location and it lacks permissions to install one at the default location. Where is it installed on your system? Playwright will attempt to install it at

Google\Chrome\Application\chrome.exe under following locations:

%LOCALAPPDATA%
%PROGRAMFILES%
%PROGRAMFILES(X86)%

It Chrome available in one of those locations?

Btw, I assume you know that you don't have to use chrome as Playwright will fetch and use Chromium by default.

**Comment by kieran1993** [comment]
Chrome installed within: PROGRAMFILES

Have ran my tests successfully with Chromium/Firefox, my aim here it run my tests on additional browsers.

Changing my config from:
`{
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'] , channel: 'chrome'},
    },`

To the following, has made it work: 
`{
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome']},
    }`

This solution was found [here](https://github.com/microsoft/playwright/issues/10541#issuecomment-1218196895)

**Comment by pavelfeldman** [comment]
Those are different modes, you either want Google Chrome or not, usually you opt into channel chrome when you need it specifically. Not sure why you had it, but closing as per above.
