### ISSUE TITLE
page.ReloadAsync() is causing the Firefox browser to crash

### ISSUE THREAD

**Issue by HK834** [microsoft/playwright#22214]
### System info
- Playwright Version: 1.32.2
- Operating System: Windows
- Browser: Firefox
- Other info: C# .Net

On the earlier playwright version (1.30), page.ReloadAsync() is working fine. It is reloading the Firefox browser. But on updating to the latest version(1.32.2) version, the same command is causing a timeout or failure.

**Please refer to the logs:**
Exception in method to refresh the page. Ex:Protocol error (Page.reload): ERROR: failed to call method 'Page.reload' with parameters { "frameId": "mainframe-11" } Found property ".frameId" - "mainframe-11" which is not described in this scheme _dispatch@chrome://juggler/content/protocol/Dispatcher.js:67:15 receiveMessage@chrome://juggler/content/components/Juggler.js:118:20 =========================== logs =========================== waiting for navigation until "load" ============================================================

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally to reproduce this bug?

**Comment by HK834** [comment]
@mxschmitt, 
Thanks for responding. This seems to be an issue from my side. After updating the playwright, I have not updated the browsers. 
Once I ran "npx playwright install" command then this issue is resolved. We can close this issue. Thanks.
