### ISSUE TITLE
[BUG] HTML report does not display retained traces on test failure

### ISSUE THREAD

**Issue by hardeepCDX** [microsoft/playwright#22225]
### System info
- Playwright Version: [1.32.2]
- Operating System: [Windows 11]
- Browser: [Chrome]
- Other info:

**Description:** HTML report does not display retained traces on test failure when configured in playwright.config.ts

**Steps to reproduce:**

1. Set Trace to 'retain-on-failure' in the playwright.config.ts file
2. Execute a test that fails an assertion
3. Open the HTML report generated by the test run

**Expected behavior:**
The HTML report should contain the retained trace information for the failed test, as configured in the playwright.config.ts file.

**Actual behavior:**
The HTML report does not display the retained trace information for the failed test, despite the 'retain-on-failure' configuration being set.

**Comment by pavelfeldman** [comment]
Works perfectly for me. Please follow the issue template to provide a reproducible scenario.

**Comment by hardeepCDX** [comment]
@pavelfeldman, When I execute the test, which fails an assertion, using the VS Code playwright extension, I am not able to find any traces in the HTML report. Nonetheless, the test functions smoothly when run via the CLI. I anticipate that this clarification will aid in reproducing the problem.
