### ISSUE TITLE
Playwright test cases work well in debug mode, but fails otherwise

### ISSUE THREAD

**Issue by as9996** [microsoft/playwright#22228]
Hi

I'm trying to migrate from Protractor to Playwright.
Tried to automate few test cases in my project and they worked well in debug mode.

But when I try to run them normally, they fail.

I'm using Angular of version 15.x, Node JS of version 14.x and Playwright of version 1.32.1.

It is failing to set some input values given in one modal dialog to it's consecutive modal dialog.

Can someone help me here.

**Comment by pavelfeldman** [comment]
You can ask questions like this on our discord!
