### ISSUE TITLE
Snapshot in Trace Viewer doesn't show scrolling in elements

### ISSUE THREAD

**Issue by gold-chris** [microsoft/playwright#22236]
The `click()` action scrolls within parent elements to bring the located element into view.  This is reflected correctly when you hover over the timeline at the top of Trace Viewer.
![plawright_truth](https://user-images.githubusercontent.com/90855585/230393700-6e26cc06-2031-4fc1-bbb6-ad6d4feaa06c.png)

However, if you select the `click()` action in the lower view, it shows a snapshot in which the parent element doesn't appear to have scrolled.  Because of this, the red dot appears in the right position, but over the wrong element.
![playwright_lies](https://user-images.githubusercontent.com/90855585/230393778-67797a7f-fb86-4a64-a886-19af5b1f6c98.png)

This occurs both in Trace Viewer and in the new UI mode

Version 1.32.2

**Comment by pavelfeldman** [comment]
Could you share a trace file so that we could look at it? Note that the trace can include sensitive information, so you should not share it publicly. You can try pinging us at Discord and send it via DM.

**Comment by aslushnikov** [comment]
Closing this since the discussion has stalled; please file a new issue if you think we still can be helpful, or better ping us on Discord!
