### ISSUE TITLE
[BUG] Running specific test in debug mode will also run dependency projects in debug mode

### ISSUE THREAD

**Issue by jfpimentel** [microsoft/playwright#22246]
Let's say we have the following config:
```
  projects: [
    {
      name: 'setup',
      testMatch: /global-setup\.ts/,
    },
    {
      name: 'suite',
      dependencies: ['setup'],
    },
  ],
```

If I run `yarn playwright test --debug specs/whatever.spec.ts`, it runs every test from the spec file in debug mode as expected, but it also runs the tests from the setup project in debug mode.

**Is it possible to run only the specified tests in debug mode?** 

**Expected**

Running `yarn playwright test --debug specs/whatever.spec.ts` should:
1. run tests from setup project **not in debug mode**
2. run tests from `specs/whatever.spec.ts` in debug mode

**Actual**

Running `yarn playwright test --debug specs/whatever.spec.ts` is:
1. running tests from setup project **in debug mode**
2. running tests from `specs/whatever.spec.ts` in debug mode

**Comment by pavelfeldman** [comment]
There is no feature like that, --debug enters the debug mode globally, it does not relate to the filters you pass.
If your setup is idempotent, you can add --nodeps. That way your setup is not called at all. Assuming you have already set up your system once, it might work for you. You can also use UI mode (--ui) instead of debug or use our VS Code integration w/ breakpoints.

**Comment by jfpimentel** [comment]
> There is no feature like that, --debug enters the debug mode globally, it does not relate to the filters you pass. If your setup is idempotent, you can add --nodeps. That way your setup is not called at all. Assuming you have already set up your system once, it might work for you. You can also use UI mode (--ui) instead of debug or use our VS Code integration w/ breakpoints.

@pavelfeldman  passing `--no-deps` along with `--debug` does exactly what I wanted, thanks for the suggestion 😉 

I would add it to the list of options on this page:
https://playwright.dev/docs/test-cli
