### ISSUE TITLE
[BUG] error when piping to process.stdout in --ui mode

### ISSUE THREAD

**Issue by Janpot** [microsoft/playwright#22265]
### System info
- Playwright Version: 1.32.2
- Operating System: maxOs 13.2.1
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally

**Config file**

```js
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  testDir: "./tests",
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test } from "@playwright/test";
import { PassThrough } from "stream";

test("pipe to stdout", async ({ page }) => {
  const writable = new PassThrough();
  writable.pipe(process.stdout);
  writable.write("hello");
});
```

**Steps**
- `yarn playwright test --ui`
- Run the test in the UI

**Expected**

No error in the console 

**Actual**

```
Error: ReferenceError: Buffer is not defined
    at Be._onStdIO (http://localhost:62118/trace/watch.575ca3b3.js:1:4187)
    at Be.dispatch (http://localhost:62118/trace/watch.575ca3b3.js:1:2309)
    at window.dispatch (http://localhost:62118/trace/watch.575ca3b3.js:3:296)
    at eval (eval at evaluate (:195:30), <anonymous>:2:10)
    at UtilityScript.evaluate (<anonymous>:197:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

Additionally, no output to be seen anywhere from tests

**Comment by pavelfeldman** [comment]
I can see the error, but I can see the output as well (toggle the console button in the toolbar).

**Comment by Janpot** [comment]
@pavelfeldman Oh wow, it took me way too long to find that console. Can confirm this works in 1.33, thank you!

Just a few unsolicited suggestions around the console:

* I'd love to be able to have this console visible as a panel next to the rest of the UI.
* I tried to copy `npx playwright install` out of it and it resulted in `^[[200~npx playwright install^[[201~` when pasting in my terminal.
* It would be nice if the ui could detect that browsers need to be downloaded and offer a button for it.
