### ISSUE TITLE
[BUG] "beforeAll" hook timeout due to browser.newPage can't be created

### ISSUE THREAD

**Issue by mdemenko** [microsoft/playwright#22266]
Context:

Playwright Version: [1.32.2]
Operating System: [Windows 10]
Node.js version: [18.12.1]
Browser: [Chromium]

Description:
Test specs start to failing with "beforeAll hook timeout exceeded" due to "Error: browser.newPage: Browser closed.". Hooks just failed on new browser page creation. It's also reproducible for some afterAll hooks (but not for all specs):

- issue is intermittent (each time for different spec)
- issue doesn't depend on workers amount (I've tried with 8,6,4 workers)

![Before All hook](https://user-images.githubusercontent.com/8157779/230618789-b6a5a483-8967-4015-9d81-b2e8e1a09611.png)
C:\Users\test\AppData\Local\ms-playwright\chromium-1055\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=C:\Users\test\AppData\Local\Temp\playwright_chromiumdev_profile-kAgOwg --remote-debugging-pipe --no-startup-window
pid=63540
[pid=63540][err] [63540:59736:0407/135115.472:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
[pid=63540]

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we can reproduce locally. Your scenario is working for millions of Playwright installs, so there is probably something specific to your environment.
