### ISSUE TITLE
[Question] Understanding the 'count' Property in Playwright's Coverage Data and Differences from Puppeteer's Coverage Data

### ISSUE THREAD

**Issue by ibrocodes7** [microsoft/playwright#22268]
I have noticed that the coverage data produced by Playwright is slightly different from that of Puppeteer. In particular, I am trying to understand the meaning of the "count" property in Playwright's coverage data. Here is an example of Playwright's coverage data:

```JSON
{
  "url": "https://xxx.js/",
  "scriptId": "5339",
  "source": "import e from"https://cdn.skypack.dev/pin/react",
  "functions": [
    {
      "functionName": "",
      "isBlockCoverage": true,
      "ranges": [
        { "startOffset": 0, "endOffset": 4612, "count": 1 }
      ]
    },
    {
      "functionName": "B",
      "isBlockCoverage": false,
      "ranges": [
        { "startOffset": 1379, "endOffset": 2136, "count": 0 }
      ]
    },
    {
      "functionName": "T",
      "isBlockCoverage": false,
      "ranges": [
        { "startOffset": 3944, "endOffset": 4536, "count": 0 }
      ]
    }
  ]
}
```

And here is an example of Puppeteer's coverage data:
```JSON
{
  "url": "https://github.githubassets.com/assets/code-menu-89d93a449480.js",
  "ranges": [
    { "startOffset": 3944, "endOffset": 4536 },
    { "startOffset": 1379, "endOffset": 2136 }
  ],
  "text": "\"use strict etc\";"
}
```

I could not find much documentation on what the coverage data means. Therefore, I would greatly appreciate it if someone could explain all the properties for me or point me to a detailed documentation. Specifically, I would like to understand the meaning of the "count" property in Playwright's coverage data and how it differs from Puppeteer's coverage data. 

Also, I noticed that the "isBlockCoverage" property is only available in Playwright's coverage response, and not in Puppeteer's coverage response. Does this mean that the ranges in Puppeteer's coverage response were only for function coverage? 

My goal is to get the range offset that have been touched by my tests. I use this information to perform a reverse mapping and identify the impacted tests to run for a commit, similar to the technique demonstrated in this resource: https://learn.microsoft.com/en-us/azure/devops/pipelines/test/test-impact-analysis?view=azure-devops.

Regarding the 'count' property in Playwright's coverage data, does a value of 0 signify that the lines specified in the corresponding 'ranges' property were not touched at all? I am trying to determine if it would be appropriate to ignore these ranges in this case.

Any clarification on this would be greatly appreciated. Thank you.

**Comment by pavelfeldman** [comment]
Playwright uses the raw v8 format for coverage. You can convert it to Istanbul using their utilities https://github.com/istanbuljs/v8-to-istanbul. In Puppeteer we post-processed v8 report into its own format, but then rejected the idea and decided to stick with v8 to reduce the number of standards in the pipeline.

**Comment by ibrocodes7** [comment]
Please excuse me if my question is naive as I am new to this. I have downloaded the coverage JSON from the Chrome coverage tab, and the format looks similar to the one used by Puppeteer. Could you clarify whether converting it to Istanbul format would result in the same format as Puppeteer's? 
<img width="1118" alt="Screenshot 2023-04-07 at 21 23 39" src="https://user-images.githubusercontent.com/65076139/230638780-03d7dec1-7a8c-4e25-b198-6d7e566988c8.png">

**Comment by pavelfeldman** [comment]
No, both Puppeteer and DevTools post-process v8 format and create intermediate representation. Playwright uses raw v8 format. Both can be converted into Istanbul as this is the tool that you are most likely interested in if you are analyzing the coverage.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by ibrocodes7** [comment]
Thank you for your input.

However, my original question was regarding the count property in Playwright's coverage data, and I did not receive a response on that matter. Could you please provide some clarification on what the count property represents in playwright's coverage data? 

**Does a count of 0 indicate that these lines have not been touched at all? I'm trying to determine whether I should ignore those ranges in that case.**

```
{
  "url": "https://xxx.js/",
  "scriptId": "5339",
  "source": "import e from"https://cdn.skypack.dev/pin/react",
  "functions": [
    {
      "functionName": "",
      "isBlockCoverage": true,
      "ranges": [
        { "startOffset": 0, "endOffset": 4612, "count": 1 }
      ]
    },
    {
      "functionName": "B",
      "isBlockCoverage": false,
      "ranges": [
        { "startOffset": 1379, "endOffset": 2136, "count": 0 }
      ]
    },
    {
      "functionName": "T",
      "isBlockCoverage": false,
      "ranges": [
        { "startOffset": 3944, "endOffset": 4536, "count": 0 }
      ]
    }
  ]
}
```

I haven't attempted to convert the coverage data because my focus is on the raw data, which allows me to identify the lines touched by my tests. I use this information to perform a reverse mapping and identify the impacted tests to run, similar to the technique demonstrated in this resource: https://learn.microsoft.com/en-us/azure/devops/pipelines/test/test-impact-analysis?view=azure-devops

This information would be helpful in understanding the coverage report and how to use it effectively.

**Comment by ibrocodes7** [comment]
> No, both Puppeteer and DevTools post-process v8 format and create intermediate representation. 

@pavelfeldman , is it possible for me to achieve this using the coverage data I receive from Playwright? Are there any examples that I could use? If you take a look at the example for Puppeteer and playwright range- The range provided by Puppeteer starts from 0 to 61 and 65 to 237, whereas Playwright's range starts from 61 to 65, which seems to be unexecuted according to Puppeteer. This can be quite confusing. These two formats are quite different from each other.

Playwright: 
```
{"url":"https://github.githubassets.com/assets/chunk-app_components_primer_experimental_toggle-switch-element_ts-c749d10d53a7.js","scriptId":"51","source":"\"use strict\";(globalThis.webpackChunk=globalThis.webpackChunk||[]).push([[\"app_components_primer_experimental_toggle-switch-element_ts\"],{11772:(e,t,i)=>{i.r(t);var s=i(76006),r=function(e,t,i,s){var r,c=arguments.length,h=c<3?t:null===s?s=Object.getOwnPropertyDescriptor(t,i):s;if(\"object\"==typeof Reflect&&\"function\"==typeof Reflect.decorate)h=Reflect.decorate(e,t,i,s);else for(var l=e.length-1;l>=0;l--)(r=e[l])&&(h=(c<3?r(h):c>3?r(t,i,h):r(t,i))||h);return c>3&&h&&Object.defineProperty(t,i,h),h};let c=class ToggleSwitchElement extends HTMLElement{toggle(){this.isOn()?this.turnOff():this.turnOn()}turnOn(){this.isDisabled()||(this.switch.setAttribute(\"aria-checked\",\"true\"),this.classList.add(\"ToggleSwitch--checked\"))}turnOff(){this.isDisabled()||(this.switch.setAttribute(\"aria-checked\",\"false\"),this.classList.remove(\"ToggleSwitch--checked\"))}isOn(){return\"true\"===this.switch.getAttribute(\"aria-checked\")}isDisabled(){return\"true\"===this.switch.getAttribute(\"aria-disabled\")}};r([s.fA],c.prototype,\"switch\",void 0),c=r([s.Ih],c)}}]);\n//# sourceMappingURL=app_components_primer_experimental_toggle-switch-element_ts-9462b0c7f1cc.js.map","functions":[{"functionName":"","isBlockCoverage":true,"ranges":[{"startOffset":0,"endOffset":1145,"count":1},{"startOffset":61,"endOffset":65,"count":0}]},{"functionName":"11772","isBlockCoverage":true,"ranges":[{"startOffset":144,"endOffset":1040,"count":1}]},{"functionName":"r","isBlockCoverage":true,"ranges":[{"startOffset":178,"endOffset":501,"count":2},{"startOffset":226,"endOffset":278,"count":1},{"startOffset":237,"endOffset":276,"count":0},{"startOffset":344,"endOffset":372,"count":0},{"startOffset":424,"endOffset":449,"count":1},{"startOffset":442,"endOffset":449,"count":0},{"startOffset":465,"endOffset":468,"count":1},{"startOffset":468,"endOffset":498,"count":0}]},{"functionName":"toggle","isBlockCoverage":false,"ranges":[{"startOffset":554,"endOffset":604,"count":0}]},{"functionName":"turnOn","isBlockCoverage":false,"ranges":[{"startOffset":604,"endOffset":726,"count":0}]},{"functionName":"turnOff","isBlockCoverage":false,"ranges":[{"startOffset":726,"endOffset":853,"count":0}]},{"functionName":"isOn","isBlockCoverage":false,"ranges":[{"startOffset":853,"endOffset":916,"count":0}]},{"functionName":"isDisabled","isBlockCoverage":false,"ranges":[{"startOffset":916,"endOffset":986,"count":0}]}]}
```

Pupeteer:
```
{"url":"https://github.githubassets.com/assets/chunk-app_components_primer_experimental_toggle-switch-element_ts-c749d10d53a7.js","ranges":[{"start":0,"end":61},{"start":65,"end":237},{"start":276,"end":344},{"start":372,"end":442},{"start":449,"end":468},{"start":498,"end":554},{"start":986,"end":1145}],"text":"\"use strict\";(globalThis.webpackChunk=globalThis.webpackChunk||[]).push([[\"app_components_primer_experimental_toggle-switch-element_ts\"],{11772:(e,t,i)=>{i.r(t);var s=i(76006),r=function(e,t,i,s){var r,c=arguments.length,h=c<3?t:null===s?s=Object.getOwnPropertyDescriptor(t,i):s;if(\"object\"==typeof Reflect&&\"function\"==typeof Reflect.decorate)h=Reflect.decorate(e,t,i,s);else for(var l=e.length-1;l>=0;l--)(r=e[l])&&(h=(c<3?r(h):c>3?r(t,i,h):r(t,i))||h);return c>3&&h&&Object.defineProperty(t,i,h),h};let c=class ToggleSwitchElement extends HTMLElement{toggle(){this.isOn()?this.turnOff():this.turnOn()}turnOn(){this.isDisabled()||(this.switch.setAttribute(\"aria-checked\",\"true\"),this.classList.add(\"ToggleSwitch--checked\"))}turnOff(){this.isDisabled()||(this.switch.setAttribute(\"aria-checked\",\"false\"),this.classList.remove(\"ToggleSwitch--checked\"))}isOn(){return\"true\"===this.switch.getAttribute(\"aria-checked\")}isDisabled(){return\"true\"===this.switch.getAttribute(\"aria-disabled\")}};r([s.fA],c.prototype,\"switch\",void 0),c=r([s.Ih],c)}}]);\n//# sourceMappingURL=app_components_primer_experimental_toggle-switch-element_ts-9462b0c7f1cc.js.map"}
```
