### ISSUE TITLE
Webkit is stalling if an dialogue/alert popup

### ISSUE THREAD

**Issue by HK834** [microsoft/playwright#22271]
### System info
- Playwright Version: 1.32
- Operating System: Windows 10
- Browser: WebKit
- Other info: C# dotnet

We have automation scripts which are running fine on chromium and Firefox.  But when we execute the same script on Webkit, it is stalling for some time when an dialogue/alert popup.

**Comment by pavelfeldman** [comment]
Please follow the issue template so that we could reproduce your issue.
