### ISSUE TITLE
[BUG] webkit.launchPersistentContext using old webkit version 13.x.x and launch using latest 16.4

### ISSUE THREAD

**Issue by blank0537** [microsoft/playwright#22274]
### System info
- Playwright Version: [v1.32.2]
- Operating System: [macOS 13.3]
- Browser: [WebKit]
- Other info:

### Source code

**main.js file**

```js
const { webkit } = require('playwright');

const test = async () => {
    const context = await webkit.launchPersistentContext('path_for_user_dir', {headless: false});
    const page = await context.newPage();
    await page.goto('https://www.abc.com');
}
test();
```

**package.json**

```json
{
    "name": "testcafe",
    "version": "1.0.0",
    "description": "",
    "main": "main.js",
    "scripts": {
      "start": "node main.js"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "dependencies": {
      "testcafe": "^2.0.0"
    },
    "devDependencies": {
      "@playwright/test": "^1.32.2",
      "playwright": "^1.32.2"
    }
  }
```

**Steps**
- npm start

**Expected**

It should open webkit browser with latest version (saw in doc and npm package link that it supports 16.4).

**Actual**

When I use launchPersistentContext method it opens old webkit browser 13.x.x (checked in user agent of browesr and other online sites) and when I use launch method it opens up in new version of webkit which is 16.4. 

I don't know if I'm missing something.

**Comment by pavelfeldman** [comment]
It is the same browser, but it looks like persistent context is advertising itself as an older version.

**Comment by yury-s** [comment]
Can reproduce this on macOS but not linux.
