### ISSUE TITLE
[Feature] ignoreOrder option for toHaveText

### ISSUE THREAD

**Issue by hormr1** [microsoft/playwright#22275]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I would like to be able to assert with a locator that returns a list and not care about the order
`await expect(locator).toHaveText([1, 3, 2], ignoreOrder: true)`

**Comment by hormr1** [comment]
Using toContainText instead along with a length check on the list.   Thanks @mxschmitt

**Comment by zgrybus** [comment]
@pavelfeldman Any news on that? How may we test that list contains text without order?

**Comment by Jardo-51** [comment]
I also ran into a need for this recently.

**Comment by R3JONATHAN** [comment]
This would be a useful feature.
