### ISSUE TITLE
Setting up environment variables and using it with the extension

### ISSUE THREAD

**Issue by testPlaywright** [microsoft/playwright#22289]
Hi,

I currently pass my environment variables externally via a command line and use the command npx playwright test to run my tests.
If I want to use this extension for vscode how do I do that??

**Comment by aslushnikov** [comment]
@testPlaywright you should add them in the `"env"` section of `launch.json`: https://stackoverflow.com/a/45426595/314883

**Comment by skuid-chad** [comment]
Would adding env variables in the launch.json affect the "Testing" VS Code extension?

**Comment by stefanonardo** [comment]
This should be opened again. I don't see how the @aslushnikov's answer solves OP's issue.

**Comment by Adverbly** [comment]
In settings.json:

```
  "playwright.env": {
    "FOO": "bar"
  }
```
