### ISSUE TITLE
[BUG] `bypassCSP` doesn’t work for ESM on `file:` URLs in Chromium and WebKit

### ISSUE THREAD

**Issue by remcohaszing** [microsoft/playwright#22292]
### System info
- Playwright Version: 1.32.2
- Operating System: Pop!_OS 22.04
- Browser: Chromium and WebKit (Firefox is ok)
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

N/A

**Test file (self-contained)**

```js
// script.mjs
import { chromium } from 'playwright-core'
// import { firefox as chromium } from 'playwright-core'
// import { webkit as chromium } from 'playwright-core'

const module = String(new URL('module.js', import.meta.url))

const browser = await chromium.launch({ headless: false })
const page = await browser.newPage({ bypassCSP: true })
// await page.goto(String(new URL('index.html', import.meta.url)))
await page.addScriptTag({ type: 'module', url: module })
```

```js
// module.js
console.log('hello')
```

**Steps**
- node script.mjs

**Expected**

`hello` is logged to the browser console.

**Actual**

In Chrome and WebKit, the script fails due to an error. Inspecting the network tab in the browser reveals this is a CSP error, despite `bypassCSP` being true.

Likewise, a dynamic import inside `page.evaluate()` causes a CSP error.

Creating an `index.html` file to navigate to doesn’t work either.

**Comment by aslushnikov** [comment]
@remcohaszing the idea of CSP is to control web site policies, not to control sand box. So this behavior is expected. No web content is allowed to load local files. You should serve your modules via HTTP/s
