### ISSUE TITLE
[BUG]将命令行playwright codegen 录制的脚步拷贝到pycharm运行  卡在with sync_playwright() as playwright 位置 没如期打开浏览器执行后续步骤

### ISSUE THREAD

**Issue by Blackstone1204** [microsoft/playwright#22293]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
from playwright.sync_api import Playwright, sync_playwright, expect

def run(playwright: Playwright) -> None:
    print("position 2")
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()

    # ---------------------
    context.close()
    browser.close()

print("position 1")
with sync_playwright() as playwright:#卡在这里？ 没法往下走
    run(playwright)

- [ ] I provided exact source code that allows reproducing the issue locally.
结果输出：
E:\pythonProject\playwightdemo\venv\Scripts\python.exe E:/pythonProject/playwightdemo/main.py 
position 1

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by Blackstone1204** [comment]
i try my next win10 computer today,    all is ok.   so is win11 is not supported?

**Comment by aslushnikov** [comment]
@Blackstone1204 hey, win11 is supported just fine. However, I'm not sure what exactly the issue is - could you please re-file it in english?

Thanks!

**Comment by Blackstone1204** [comment]
@aslushnikov   hey ,I find the reason .  my  cmd window  show  Active code page: 65001  before .  _transport.py  run method has a 
  var  bufffer 。it is  b've code page: 65001\r\n\x80\x00\x00\x00{"guid":"","method":"__create__","params..
