### ISSUE TITLE
Multiple assertions check

### ISSUE THREAD

**Issue by Vissu0901** [microsoft/playwright#22299]
While using assertion I'm able to pass only one single text to check. If Playwright allows multiple text conditions for user to check the assertions like below example:

await expect('locator').toContain(['text1','text2','text3'];

As per above expect Playwright should check text1 if fails text2 vice versa until text3. If all texts fails then test case should fail.

**Comment by pavelfeldman** [comment]
This is slightly different, here you expect locator point to a list (think li or any other kind of list of elements) that contains elements with the given text. What you are trying to do can be achieved with 

await expect('locator').toHaveText(/(text1)|(text2)|(text3)/);

**Comment by aslushnikov** [comment]
Closing as per Pavel's response; feel free to open a new issue if you think we can still be helpful!
