### ISSUE TITLE
[Idea] Alternative architecture for component testing

### ISSUE THREAD

**Issue by kevin940726** [microsoft/playwright#22302]
I recently tried integrating component testing into a project but some of the current limitations are deal breakers for me from pushing it to my team. Namely, the inability to declare test components directly inside the test files, and we are forced to declare them inside another file and import them. This feels awkward ergonomically and it's difficult to explain to regular testers why their code doesn't work.

Related issues: https://github.com/microsoft/playwright/issues/18758, https://github.com/microsoft/playwright/issues/15620, https://github.com/microsoft/playwright/issues/18057.

## The current architecture

I'm not familiar with the underlying code, but AFAIK, the current architecture of the experimental react component testing looks like:

1. Playwright scans the project and finds the imported files from the test files defined in `testMatch`.
2. It then uses `vite` to export members that look like components to a metadata file and host the bundled components in a server.
3. JSX inside the test files are transformed into presentational serialized objects.
4. The `mount` fixture passes the objects to the client, the client then reconstructs the React tree based on the objects and the metadata file.
5. Finally, the client mounts the app and the backend continues the test.

I think the main issue here is that it's difficult to know which part of the test runs on the backend and which part runs on the client.

## Proposed architecture

Instead of running the tests on the server, I propose we just mount the test files directly in the browsers. Here's what I would imagine how this works:

1. Playwright uses `vite` to bundle all test files into an app and host it on the server.
2. We can mock some Node.js-specific modules using something like [`modern-node-polyfills`](https://github.com/Aslemammad/modern-node-polyfills) to support `expect` and other features.
3. We want each test case to be run in an isolated context, so instead of executing the test suite on the browser right away, we mock `test` and spawn a thrown-away context to just _collect_ the test cases into some variable. We then send the collected tests list to the backend and instruct the test runner to execute them in isolated contexts.
4. The built-in fixtures won't work in this case, so we mock them as well in the browser with _proxy_ objects. For instance, `page` will be a proxy object on the browser, and calling `page.click()` sends an instruction to the backend with the serialized arguments to perform the actual task. Some methods might not be supported, especially for those which accept unserialized arguments or synchronously return the value. However, since the test runs directly in the browser, some APIs won't be needed or could be re-implemented in the browser context. For instance, `page.evaluate` isn't needed anymore and we can just write regular JavaScript to _evaluate_ it.
5. Snapshot testing can theoretically still work by injecting the snapshot files into the browser before running the tests. Custom fixtures will also have to be run in the browser context, so there might be some limitations there.
6. Once the tests are completed in the browser, Playwright then sends the results to the backend and picks up the rest (reporter, tracing, screenshots, etc).

This proposal takes advantage of the fact that most Playwright APIs are promise-based and can be proxied in the browser context. It also assumes that the test files are _pure_, in the sense that they don't produce side effects when running multiple times concurrently.

**Pros:**
1. We can declare test components directly inside the test files. (Fixes https://github.com/microsoft/playwright/issues/18057)
2. We can test render props/slots without having to create intermediate components in a different file (Fixes https://github.com/microsoft/playwright/issues/18758)
3. We can test anything now really, including but limited to React hooks, Preact components, Web components, any other frontend framework, or any arbitrary functions. We can run unit tests in real browsers.
4. We can use any existing testing framework (`@testing-library/react`) or just use the official API from frontend frameworks.
5. Because of that, we don't have to create separate packages for each frontend framework either and can just release a single `component-testing` or `browser-testing` package.
6. We can still provide the `mount` fixture for convenience, but it can just be a regular function that calls the framework API under the hood. Because of that, we probably don't need the special `beforeMount` and `afterMount` hooks either. They can be implemented by wrapping the `mount` fixture and `afterEach`.
7. It will obviously be a breaking change, but since that component testing is still experimental, we don't have to worry too much about backward compatibility.
8. Clearer separation of context. Everything runs in the browser by default.

**Cons:**
1. Not trivial to implement, lots of gotchas have to be carefully handled to make this work.
2. Since tests now run on the browser, we can't use some of the Node.js modules in tests anymore. We might want to expose an API as an escape hatch to evaluate backend code in the browser. Like the opposite of `page.evaluate()`, or via a setting in the config.
3. Some APIs like `page.exposeFunction` might be impossible to implement, or have some limitations. We'll have to find a way to document them clearly.
4. This is likely Node.js only, and probably will never work for other runtimes like Java or Python.

## Prior arts:

- [Vitest browser mode](https://vitest.dev/guide/browser.html)
- [Web Test Runner](https://modern-web.dev/docs/test-runner/browser-launchers/playwright/)

Vitest currently uses webdriverio but can be easily switched to Playwright under the hood. However, both frameworks currently don't support running test cases in the same test suite in isolated contexts, which IMO is where Playwright test runner really shines.

## Thoughts?

I'm sure that the maintainers have thought of something like this before, but I'm curious about the trade-offs we made when we reached to this decision. Is the current architecture still the preferred trade-off? What are some of the difficulties and blockers? In retrospect, do we want to rethink the component testing architecture? Or is it not the primary focus right now? Thanks for making it here!</div>

**Comment by aslushnikov** [comment]
@kevin940726 First of all, thank you for filing and sharing your thoughts! 

> I'm sure that the maintainers have thought of something like this before, but I'm curious about the trade-offs we made when we reached to this decision.

We've considered with this approach; however, it requires plenty of engineering investment, so we ended up with our current approach to test waters and explore component testing necessities & limitations. 

> In retrospect, do we want to rethink the component testing architecture?

While this might happen, there's no plan to do so in the near future. As of today, we're focusing on end-to-end testing.

**Comment by kevin940726** [comment]
Thanks for the context! I appreciate the explanation! ❤️ 

Feel free to close it then, we can re-open it when there is more feedback collected.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
