### ISSUE TITLE
Paste from Clipboard (Command+V) acts like Undo (Command+Z) on Docker images running Linux

### ISSUE THREAD

**Issue by Mortai21** [microsoft/playwright#22304]
There is a way that in Playwright version 1.32, Paste from Clipboard (Command+V) acts like Undo (Command+Z) on Docker images running Linux?

### Scenario:
1. Copy to the Clipboard
2. Write something inside a text area
3. Delete the text I just wrote
4. Paste from the Clipboard (Command+V)

Expected: Clicking Command+V should paste the text copied from the Clipboard.
Actual: The text was deleted returned (Step 2) - Feels like an Undo command (Command+Z)

- I mentioned that in the Local Environment (MacOS), it does not happen. Otherwise, it does happen in Docker images running on Linux.

- It does not happen in Playwright versions 1.31, 1.30, 1.29.

**Comment by aslushnikov** [comment]
@Mortai21 I just tried and it works fine. How do you establish a headed session into docker image? Which browser do you use?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since this issue looks stale. Please re-file with more details and a clear repro. Thanks!
