### ISSUE TITLE
[Feature] VSCode - Add option to start UI mode from vscode playwright extension

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#22309]
Hello,

is it possible to add an option that starts the UI mode from within the test explorer (VS Code extention)?

![image](https://user-images.githubusercontent.com/94455079/230947939-a5e4ceed-016d-409a-b000-73b17c0c50c0.png)

**Comment by mxschmitt** [comment]
We implemented it as "Show Trace" in the VSCode extension and allow Codespace users to use UI Mode there as well see [here](https://playwright.dev/docs/test-ui-mode#docker--github-codespaces).
