### ISSUE TITLE
[BUG]When I use addInitScript ,did not see anything on the page

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#22307]
S**ystem Info:**
Browser:Chrome (Version 112.0.5615.49 (Official Build) (arm64))
PC:Apple M1

**Problem:**
I have a chatbot embed script and I want to inject below script in a page on the new tab .After that when chatbot loaded on the page I will test it.

When I used **addInitScript** don t see any chatbot icon in the page.Should there be a bug or am I doing something wrong?

**Note**:Changed src url in the script here if you try may not work.But this script works in my locale when try on the console.

`<script> !function(a,c,s,a,n,o){p.PisanoObject=s;p[s]|| (p[s]=function(){ (p[s].q=p[s].q||[]).push(arguments)});p[s].l=+new Date;n=i.createElement(a); o=i.getElementsByTagName(a)[0];n.src='https://stage.test.com/scripts/widget/widget.js'; o.parentNode.insertBefore(n,o)}(window,document,'test','script'); User('boot', 'test-62r4dio'); </script>`

```
const newPage = await page.context().newPage()
await newPage.goto("feedback")
await page.addInitScript(`!function(a,c,s,a,n,o){p.PisanoObject=s;p[s]|| (p[s]=function(){ (p[s].q=p[s].q||[]).push(arguments)});p[s].l=+new Date;n=i.createElement(a); o=i.getElementsByTagName(a)[0];n.src='https://stage.test.com/scripts/widget/widget.js'; o.parentNode.insertBefore(n,o)}(window,document,'test','script'); User('boot', 'test-62r4dio'); `)
```

**Comment by aslushnikov** [comment]
@YusufOzt so this doesn't look like a Playwright question to me; the `page.addInitScript` just inserts the script in question; it's outside of the scope of the project if the script is misbehaving somehow.

Could you please file this question to StackOverflow or to discord instead? Thanks!
