### ISSUE TITLE
Question about best practice when combining fixture and POM (new tab creation)

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#22319]
I have following fixtures that follow POM pattern:

```
//my-test.ts
type Fixtures = {
  projectRoomPage: ProjectRoomPage;
  teamsCallPage: TeamsCallPage;
};

export const test = base.extend<Fixtures>({
  projectRoomPage: async ({ page }, use) => {
    await use(new ProjectRoomPage(page));
  },
  teamsCallPage: async ({ page }, use) => {
    await use(new TeamsCallPage(page));
  },
});
```

In my test I make a call to teamsCallPage which needs access to a new tab that is created upon a click

```js
// TeamsCallPage.ts
export class TeamsCallPage {
  readonly page: Page;

  constructor(page: Page) {
    this.page = page;
}
```

```js
// actual test
test('join teams call from dashboard', async ({ projectRoomPage, teamsCallPage
    const roomName = faker.random.word();
    await projectRoomPage.switchToProjectRoomTab();
    // ...some actions

    // Clicking joinRoom opens an new tab
    const newMeetingPromise = projectRoomPage.page.waitForEvent('popup');
    await projectRoomPage.joinRoom();
    const newMeetingPage = await newMeetingPromise;

    await teamsCallPage.setupCall();
}) 
```

How can I make the teamsCallPage.setupCall() use the `newMeetingPage`? The teamsCallPage is being setup in my fixture where I simply do `new TeamsCallPage(page)`.

I am aware that I can import TeamsCallsPage and do `teamsCallPage = new TeamsCallPage(newMeetingPage);` or use setter for page `teamsCallPage._page = newMeetingPage;` but was wondering if there was a better to handle it so I avoid the POM structure within my test itself.

Thank you!

**Comment by mxschmitt** [comment]
We would recommend creating a new instance of a ProjectRoomPage for that. Aka.

```ts
    // Clicking joinRoom opens an new tab
    const newMeetingPromise = projectRoomPage.page.waitForEvent('popup');
    await projectRoomPage.joinRoom();
    const newMeetingPage = await newMeetingPromise;
    const newMeetingProjectRoomPage = new ProjectRoomPage(newMeetingPage);
```

**Comment by Nav-2d** [comment]
@mxschmitt - Thanks for looking into this. Did you mean creating a new instance of TeamsCallPage?

```
    const newMeetingPage = await newMeetingPromise;
    const newTeamsCallPage = new TeamsCallPage(newMeetingPage);
```

Upon join room click a new tab open for joining teams call (and not a new project room)

**Comment by mxschmitt** [comment]
Yes exactly.
