### ISSUE TITLE
[BUG] browser gets closed automatically when we use POM methods in test 

### ISSUE THREAD

**Issue by deepti-patro** [microsoft/playwright#22329]
### System info
- Playwright Version: 1.32.3-beta-1681174265000
- Operating System:  Windows 11
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: 

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
{
      name: 'android.chrome',
      use: {
        ...devices['Pixel 5'],    
      },
    }, 

 {
      name: 'ipad.safari',
      use: {
         ...devices['iPad (gen 6)'],
      },
   }
});
```mdc.login.page.ts
import { expect, Locator, Page } from '@playwright/test';

const baseURL =  String(process.env.URL);
const username = String(process.env.userid);
console.log(username);
const password = String(process.env.password);
const Title = String(process.env.Title);


export  class mdcloginPage {
 
    readonly page: Page;
    readonly username_field : Locator;
    readonly password_field : Locator;
    readonly login_button : Locator;
    
    // Locators

    constructor(page: Page) {
        this.page = page;
        this.username_field = page.locator('input[name="username"]');
        this.password_field = page.locator('input[name="password"]');
         this.login_button = page.getByRole('button', { name: 'Login' });
    }
       
    //Actions
    public async logintomdc() {
        await this.page.goto(baseURL);
        
       await expect((this.page),'checking page title').toHaveTitle(Title);
        await this.page.screenshot({path: 'screenshot/title.png'});
        /*await this.username_field.waitFor({state: "visible"});*/
        await this.username_field.type(username);
        await this.password_field.fill(password);
        await this.login_button.click();   

    }
**Test file (self-contained)**

```MDC.spec.ts
import { test, expect } from "@playwright/test";
import {mdcloginPage} from "./mdc/mdc.login.page";



test.describe('MDC Regression', async() => {  
    
    
  test('mdc tc1', async ({ page }) => {    
    const mdclogin = new mdcloginPage(page);
    mdclogin.logintomdc();  
  });
})
```

**Steps**
 

**Expected**

Navigate to url and fill username, password 
click on login button.

**Actual**

it's closing the browser before it's loaded properly with below error

before hooks
page goto(url)
after hooks
Test finished within timeout of 30000ms, but tearing down "context" ran out of time.
Please allow more time for the test, since teardown is attributed towards the test timeout budget.

**But when not following pom and I write the script in main test it's working fine**
MDC.spec.ts
import { test, expect } from "@playwright/test";
import {mdcloginPage} from "./mdc/mdc.login.page";

test.describe('MDC Regression', async() => {     
    
  test('mdc tc1', async ({ page }) => {  
   
    
  const baseURL = String(process.env.URL);
        const username1 = String(process.env.userid);
        const password = String(process.env.password);
        const Title = String(process.env.Title);

        await page.goto(baseURL) ;     
     
    // Expect a title "to contain" a substring.
         await expect((page),'checking page title').toHaveTitle(Title);
        await page.screenshot({path: 'screenshot/title.png'})

       
        await page.locator('input[name="username"]').fill(username1);
        await page.locator('input[name="username"]').press('Tab');
        await page.locator('input[name="password"]').fill(password);
        await page.getByRole('button', { name: 'Login' }).click();

   
  });
})

Above case it's working as expected 

before Hooks 
login to page 
after Hooks

**Comment by JonahKK** [comment]
`logintomdc()` method is async. That means you have to await it in your code to ensure that it executes before test finishes. That should help:
```
test('mdc tc1', async ({ page }) => {    
    const mdclogin = new mdcloginPage(page);
    await mdclogin.logintomdc();  
  });
  ```

**Comment by deepti-patro** [comment]
it worked . thanks

**Comment by deepti-patro** [comment]
thanks
