### ISSUE TITLE
[Feature] Allow debugging in Chromium

### ISSUE THREAD

**Issue by timbicker** [microsoft/playwright#22326]
Hi,
It seems that it's not possible to set break points in chromium. I am trying to achieve the following:
I can set a break point in my test file and run playwright in headed mode. It then stops at the given break point as expected and the opened Chromium window is also in that state.
What I am now trying to achieve is that I can set a break point in Chromium and continue my test. But when I go to the sources tab in the developer console, I am not able to add any break points.

Imagine I have a bug in my E2E test and I want to debug it. Let's say I have an idea of what causes the bug. This way I could simply add a break point in chromium and immediately inspect my code.

--- 
Another feature idea built on top of that would be that I can hook up my VS Code debugger to the chromium window and debug the application from inside VS code. This would come in pretty handy also for the experimental component tests. Because right now I see a big advantage in playwright that I can see my component/integration tests in the browser. Competing libraries like react-testing-library can't do that. But with these libraries I can simply set a break point somewhere in my application and inspect my code because they run in a node.js environment. Currently, I don't see myself using playwright for integration/component tests if I am not able to debug this way. Because how should I debug my test then?

So, if playwright would allow me to debug the application from within my IDE, I can hardly see a reason to use a library like react-testing-library anymore because playwright would allow me the same DX but with more features (browser inspection).

**Comment by yury-s** [comment]
Sounds like the same request as https://github.com/microsoft/playwright/issues/22007

**Comment by mxschmitt** [comment]
Folding into it.
