### ISSUE TITLE
[BUG] Executable doesn't exist at /root/.cache/ms-playwright/chromium-1055/chrome-linux/chrome

### ISSUE THREAD

**Issue by eshk12** [microsoft/playwright#22333]
### System info
- Playwright Version: latest
- Operating System:  Ubuntu

Hello guys, I am trying to run Playwright on a docker container with gui using `dorowu/ubuntu-desktop-lxde-vnc` image.

I have created this Dockerfile:

```
FROM dorowu/ubuntu-desktop-lxde-vnc:latest
WORKDIR /tests

RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 4EB27DB2A3B88B8B

#Install Node.js & npm
RUN apt-get update
RUN apt-get install -y curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get install -y nodejs

COPY . .

# Install Playwright dependencies
RUN npm install
# Install browsers
RUN npx playwright install
# Install test
RUN npx @playwright/test install
```

When I am running this docker container I am giving a volume that is already holding Playwright installation and if I try to run it from the parent machine it's running.

But when I am running it from the container itself I am getting this error:

> browserType.launch: Executable doesn't exist at /root/.cache/ms-playwright/chromium-1055/chrome-linux/chrome

And it's asking me to re-run `npx playwright install` and I have already run this command on the Dockerfile.

What am I missing here? how can I solve it?

**Comment by eshk12** [comment]
Hello, Thanks for yours quick response.

Here is the `package.json`:
```
{
  "devDependencies": {
    "@playwright/test": "^1.29.2"
  }
}
```
I've also tried to run the image build without `RUN npx @playwright/test install` and the results remain

**Comment by eshk12** [comment]
Yes there is output from this line:

> Version 1.32.3

My Node.js version is: V16.19.1
My NPM version is: 8.19.3

**Comment by mxschmitt** [comment]
Does it mean its working now after you set the env var?

It seems like the Docker image messes a bit around with Linux user accounts. It has some special user called `ubuntu`. And `root`'s home directory is /home/ubuntu which seems against any Linux best practise.

**Comment by eshk12** [comment]
Thanks @mxschmitt, indeed, when I changed the user to ubuntu its worked.

**Comment by ramonaZmole** [comment]
```
FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

ARG ENV
ENV Environment=$ENV

WORKDIR "/tests/src/test/functional/FunctionalTests/FunctionalTests"

COPY ["FunctionalTests.csproj", "FunctionalTests/FunctionalTests/"]
COPY . .

        
#Install powershell to playwright scripts
RUN apt-get update -yq \
    && apt-get install wget -yq \
    && wget -q https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && apt-get update -yq \
    && apt-get install powershell -yq


#Build .csproj
RUN dotnet build "FunctionalTests.csproj" \
  -c Release \
  -o /app/build


WORKDIR "/app/build"

# Install playwright dependencies
RUN pwsh ./playwright.ps1 install
RUN pwsh ./playwright.ps1 install chromium
RUN pwsh ./playwright.ps1 install-deps chromium


#Run API tests
WORKDIR "/tests/src/test/functional/FunctionalTests/FunctionalTests"

RUN dotnet test "FunctionalTests.csproj" \
    -c Release \
    -o /app/report
```

this is how I solved the problem
