### ISSUE TITLE
[BUG]: MS Teams call originating from MS call queue is instantly terminated.

### ISSUE THREAD

**Issue by melkorinos** [microsoft/playwright#22330]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:  Node v16.15.0 
1. It's possible I need to file this bug to MS Teams instead of playwright. Please let me know if I should do so.
2. I believe this is best reproduced with `npx playwright codegen` as the only action is to login to teams. 
3. Call is answered properly if it is a direct call to the agent's email address. The bug occurs specifically for MS [call queue](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info) in combination with playwright.

### Source code

- [X] I provided exact source code that allows reproducing the issue locally. You can also reproduce this with `npx playwright codegen`.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
    timeout: 40000,
    expect: {
        timeout: 5000,
    },
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
            },
        },
    ],
};
export default config;
```

**Test file (self-contained)**

```js
it('launch MS teams', async ({ page }) => {
const browser = await chromium.launch({
            headless: false,
            args: ['--use-fake-ui-for-media-stream', '--use-fake-device-for-media-stream'], //needed for mic/camera
        });
const context = await browser.newContext();
const page = await context.newPage();

await page.goto('https://teams.microsoft.com/go#'); 
await page.getByPlaceholder('Email, phone, or Skype').fill(YOUR_USERNAME);
await page.getByRole('button', { name: 'Next' }).click();
await page.getByPlaceholder('Password').click();
await page.getByPlaceholder('Password').fill(YOUR_PASSWORD);
await page.getByRole('button', { name: 'Sign in' }).click();
await page.getByRole('button', { name: 'No' }).click();


});
```

**Steps**
- [Run the test to open an MS Teams instance]
- [Configure your MS Teams address to receive a call from an MS [call queue](https://learn.microsoft.com/en-us/microsoftteams/create-a-phone-system-call-queue?tabs=general-info) ]
- [Call the call queue number. This should result in an incoming call on your chromium teams window]
- [Manually click the answer button on MS Teams]

**Expected**
[The call establishes and there is an active teams conversation conversation in the Chromium MS Teams tab.]
**Actual**
[Observe that the call establishes for a brief moment and is immediately being terminated]

**Comment by mxschmitt** [comment]
What are you trying to achieve by automating the call queue?

**Comment by melkorinos** [comment]
I work for a company that has integrated solutions with MS Teams. I am not automating the call queue. 

For example a very simple test case would be :
1. Launch our software
2. Initiate a call that will be routed to us using call queues.
3. Answer the call on teams
4. Ensure "our software" is displaying that there is an established call in the UI

My issue is that I am unable to complete step 3 due to the bug mentioned in the title.
I am calling a "general" phone number. The general phone number routes the call to my test user.
Hope this helps.

We have also forwarded this internally to a MS employee that we have as a business contact person.

**Comment by mxschmitt** [comment]
I unfortunately don't have access to the call queue feature nor do I have access to a Teams testing environment. So either your business contact can ping me internally (or he can figure it out) or we unfortunately can't act on it.

So we basically need to find the reason why it does not work, most likely caused some of our CLI args which we pass, you can try to ignore some of them. See [here](https://github.com/microsoft/playwright/blob/0c3c6ed6833086e83d444b9027ca48173653dfa9/packages/playwright-core/src/server/chromium/chromiumSwitches.ts#L20) for a full list.

**Comment by mxschmitt** [comment]
You could also try it using the [Google Chrome channel](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge), which includes more video codecs, which might be the bottle neck.

For now since we unfortunately can't act from our side, I'll close it and recommend that someone from the MS Team can help you there what exactly goes wrong, thanks for your understanding!
