### ISSUE TITLE
[BUG] context.route() can make the rendering flaky

### ISSUE THREAD

**Issue by sbellone** [microsoft/playwright#22338]
Hi, we've noticed that `context.route()` can alter the rendering for some websites, e.g. https://www.wm.com/ca/en/support/faqs/how-do-i-handle-medical-waste-or-sharps-disposal

Would you know what can cause that, and how to debug it?

### System info
- Playwright Version: v1.32.3 (Node v18.15)
- Operating System: Debian 11
- Browser: Chromium, Firefox
- Other info: A bit more reliable with Firefox

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch();

  let success;
  let attempt = 1;
  do {
    console.log(`attempt ${attempt}...`);
    const context = await browser.newContext();

    // This will make the rendering fail after a few attempts some point
    // When commented out, all 100 attempts succeed.
    await context.route('**/*', async route => {
      await route.continue();
    });

    const page = await context.newPage();
    await page.goto(
      'https://www.wm.com/ca/en/support/faqs/how-do-i-handle-medical-waste-or-sharps-disposal',
      { waitUntil: 'networkidle' }
    );
    const element = page.locator('h1');
    success = (await element.count()) > 0;
    if (!success) {
      console.log('FAILED!');
      await page.screenshot({ path: 'rendering_fail.png' });
      break;
    }

    await page.close();
    await context.close();
    ++attempt;
  } while (attempt <= 100);

  await browser.close();
})();
```

**Steps**
- `node repro_script.js`

**Expected**

- Rendering never fails (100 successful attempts).

**Actual**

- After a few rendering attempts, you will see a `FAILED!` log and a `rendering_fail.png` image is generated, showing that the content of the page wasn't correctly loaded.

Note: it never fails if the `await context.route('**/*'` hook is commented out.

**Comment by sbellone** [comment]
Thank you for your answer. Indeed, networkidle is not 100% reliable, but it doesn't seem to be a matter of waiting time here.
On my side doing a `await page.locator('h1').waitFor()` timeouts without finding the element after a few attempts.
Actually, I've even tried to put a `await setTimetout(60000);` after the `page.goto()`. It seems to help as a bit more attempts are successful, but eventually the page stays empty. Something definitely behaves differently and doesn't trigger the rendering.

Next thing will be to have the developers of the website looking at the rendering code, but first I was wondering if something around `context.route` feature could explain that behaviour.

![image](https://user-images.githubusercontent.com/2042109/231821043-20433029-9f69-4253-b0e6-f24734f10c26.png)

**Comment by mxschmitt** [comment]
I can reproduce it, looks like something going on with the rendering of the website rather than with Playwright networking. The `https://www.wm.com/content/wm/servlets/support?locale=en_CA` resource gets loaded from what I can tell. I used the [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) to look into it. Probably some issue with the JavaScript on the site, especially the logic after the data has been fetched should be debugged.

Since we are not familiar with this site, someone of your developers would have to take a look at it. I'll keep it open for a few days, but since this looks not caused by Playwright, we can't act on it for now.

**Comment by sbellone** [comment]
I understand, thank you for taking the time to have a look :pray:
