### ISSUE TITLE
[REGRESSION] Probable memory leak when using debug mode starting in Playwright v1.32.0

### ISSUE THREAD

**Issue by brk9394** [microsoft/playwright#22348]
### System info
- Playwright Version: `v1.32.0`
  - Confirmed the issue **_does not exist_** in `v1.31.2`
  - Confirmed the issue **_exists_** in `v1.32.0` thru `v1.32.3`
- Operating System: Windows 10, 22H2
- Browser: Tested with Chromium and Firefox
- Other info:
  - Node: v18.15.0
  - PowerShell: v7.3.3
  - Terminal: 1.16.10261.0

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  use: {
    trace: 'on-first-retry',
  },
});
```

**Test file (self-contained)**

```js
// memory-leak-example.spec.ts
import { test, expect, Locator, TestInfo } from '@playwright/test';
test.afterAll(async ({ page }) => await page.pause());

test('Example test showing a probable memory leak after updating from Playwright v1.31.2 to v1.32.0', async ({ page }, testInfo: TestInfo) => {
    const isPwDebug = !!process.env.PWDEBUG;
    const pwVersion = testInfo.config.version;
    const timerTotalTime = `\nTotal test time for PW v${pwVersion} (debug: ${isPwDebug})`;
    console.log(`Playwright v${pwVersion}\ndebug: ${isPwDebug}\n`);
    console.log('round #, link #, rssMB, heapTotalMB, heapUsedMB, externalKB, arrayBuffersKB');
    const bytesToKB = (bytes: number): string => (bytes / 1024).toFixed(3);
    const bytesToMB = (bytes: number): string => (bytes / 1024 / 1024).toFixed(3);

    console.time(timerTotalTime);
    const url = 'https://playwright.dev/docs/intro';
    await page.goto(url, { waitUntil: 'networkidle' });

    const links: Locator = page.getByRole('navigation', { name: 'Docs sidebar' })
        .locator('li[class^="theme-doc-sidebar-item-link theme-doc-sidebar-item-link-level-2"]');
    const linksCount = await links.count(); // 55 links

    const maxRounds = 2;
    for (let i = 1; (i <= maxRounds); i++) {
        const maxLinksToClick = 99;
        for (let j = 0; (j < linksCount && j <= maxLinksToClick); j++) {
            const link = links.nth(j);
            await link.click();
            const linkText = await link.textContent() as string;
            const heading: Locator = page.getByRole('heading', { name: linkText, exact: true });
            await expect(heading).toHaveText(linkText);

            const rssMB = bytesToMB(process.memoryUsage().rss);
            const heapTotalMB = bytesToMB(process.memoryUsage().heapTotal);
            const heapUsedMB = bytesToMB(process.memoryUsage().heapUsed);
            const externalKB = bytesToKB(process.memoryUsage().external);
            const arrayBuffersKB = bytesToKB(process.memoryUsage().arrayBuffers);
            console.log(`${i}, ${j}, ${rssMB}, ${heapTotalMB}, ${heapUsedMB}, ${externalKB}, ${arrayBuffersKB}`);
        }
    }
    console.timeEnd(timerTotalTime);
});
```

**Steps**
- Run the sample test in PW `v1.32.3` in debug mode using the following command:
  `npx playwright test memory-leak-example --debug`

**Expected**

- The sample test should take < 25 seconds to complete, as it does in PW `v1.31.2`

**Actual**

- The sample test takes > 3m 30s to complete
- In my private repo e2e tests, the test goes about 1/3 of the way, then the browser hangs and the test fails
- I am unable to use PW `v1.32.0+` for my e2e tests due to performance and/or hung browser while in debug mode

**Comment by mxschmitt** [comment]
I can reproduce, without debug mode its fine, with debug modes there is a huge delay between the actions after some time. Might be related to the playwright.dev detached dom nodes leak.

**Comment by mxschmitt** [comment]
@brk9394 were you able to reproduce this on a site which is not playwright? Its a known issue that playwright.dev current leaks JavaScript heap when clicking through all the pages. This is most likely the reason why the performance gets worse over time.

**Comment by mxschmitt** [comment]
```txt
bad 1.32.0-alpha-mar-11-2023 
good 1.32.0-alpha-mar-10-2023 Total test time for PW v1.32.0-alpha-mar-10-2023 (debug: true): 14.288s
```

Range: https://github.com/microsoft/playwright/compare/908c0462d56586c28faccbce076899b652986be6...e45a4968506de882d78be65f2fb2cf9a09e47a7a

**Comment by brk9394** [comment]
Total test time for PW v1.31.2 (debug: true): 26.821s -- good
Total test time for PW v1.33.0 (debug: true): 22.477s -- even better!

Also confirmed 1.33.0 works in my private repo.
Thanks Playwright team!
