### ISSUE TITLE
[BUG] Using custom fixtures in beforeAll in a specific way

### ISSUE THREAD

**Issue by dkondakov** [microsoft/playwright#22340]
### System info
- Playwright Version: [v1.32, v1.30]
- Operating System: [Windows 10]
- Browser: [Chromium]

### Source code

I created a new file for base fixtures:

```ts
//baseFixtures.ts
import { PlaywrightTestArgs, test as base } from '@playwright/test';

export const test = base.extend<PlaywrightTestArgs>({

	page: async ({ browser }, use) => {
		const context = await browser.newContext();
		const page = await context.newPage();
		await use(page);
		await context.close();
		await page.close();
	}
});
```

then it was imported in my custom fixture:

```ts
//customFixtures.ts
import { Page } from '@playwright/test';
import { test as base } from 'baseFixtures';

type CustomFixtures = {
	someParameter: SomeType;

export const test = base.extend<LoginFixtures>({
fixture: async ({ page, someParameter}, use) => {
		const functionsClass= new FunctionsClass(page);
		await functionsClass.someMethod(someParameter);
		await use(page);
	}
});

```

and then I can use it in beforeAll hook as a fixture in parameters:

```ts
// test.ts
import { test } from 'customFixtures';

test.describe('Some description', () => {
	test.use({ someParameter: { key: 'value' } });
	test.beforeAll(async ({ fixture }) => { 
		await fixture.doSmth();
 });

```
It works as expected.
However, I'm just wondering if this approach is fine for using it in order to have the ability to use fixtures in the beforeAll() hook and has no hidden issues?

**Comment by mxschmitt** [comment]
I think its not behaving how you want to have it behave, do you expect to have the same page instance across your tests inside the describe block? If so, then we recommend [this](https://playwright.dev/docs/test-retries#reuse-single-page-between-tests) instead.

**Comment by dkondakov** [comment]
Thank you, Max, for the answer!

The main intention was to be able to use page and custom fixtures in beforeAll() hook to do some preconditions with test environment before the test starts.
I saw the article about reusing a single page. And it's about working in serial mode only and still no ability to use fixtures in beforeAll() hook. So, it doesn't fit me.

If everything works fine using such approach I described in this issue, and opening a new page per each test is also ok for me, can we consider it (approach) valid and use it for my tests?

And another question is how can we determine in which scope (test or worker) the overridden page is opening? I tend to think about test one, but I'm not completely sure.

**Comment by eveltman-twinfield** [comment]
Hi @mxschmitt, what we are looking for is to set up some expensive shared (spec-wide) backend state in the test.beforeAll.
In our case each spec file runs with a different test user, and against a different test company.
That user and company are what we want to set up in the beforeAll.
We have too many specs (and test users and test companies) to create all of them in a globalSetup or in a setup project.

Our dream solution would be if we could use page, context, etc. in the test.beforeAll as if the beforeAll is a test by itself.
So each test still starting with a fresh page and context, not re-using the one from the test.beforeAll.

**Comment by mxschmitt** [comment]
Gotcha, did you already see that we have [project dependencies](https://playwright.dev/docs/test-global-setup-teardown#project-dependencies) since a few releases? That might fit perfectly for your scenario. this is designed for longer lasting and more complex setting up operations.

If you just want to have access to "some page" inside your beforeAll, I'd recommend to just create a new context/page there, instead of doing this page override, since the page override will most likely break things and we would not recommend doing that. So in code something like that:

```ts
test.describe('Assets Details report', () => {
	test.use({ someParameter: { key: 'value' } });
	test.beforeAll(async ({ browser }) => { 
		 const context = browser.newContext();
                 const page = await context.newPage();
                 await page...
                 await context.close();
 });
```

Generally speaking you have access to fixtures inside beforeAll, but just the worker fixtures. And context/page is a test fixture which does created per each test. Worker fixtures like browser are for the whole worker lifetime. See [here](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) about worker fixtures.

**Comment by dkondakov** [comment]
What if I want to have an access to some custom fixtures in beforeAll? 
```ts
test.describe('Assets Details report', () => {
	test.use({ someParameter: { key: 'value' } });
	test.beforeAll(async ({ browser, customFixture }) => { 
	...
```
Is there some way to do that?

**Comment by mxschmitt** [comment]
Yes as long as they are worker fixtures, you can do that: https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures
