### ISSUE TITLE
[Feature]: Define tags as JS/TS decorators

### ISSUE THREAD

**Issue by vitalets** [microsoft/playwright#22357]
Currently tags are defined inside test title. It has some downsides (see https://github.com/microsoft/playwright/issues/17375).
With new JS [decorators](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators) it seems we can have very neat syntax for tags. For example:
```ts
import { createTag } from '@playwright/test';

const fast = createTag('fast');

@fast
test('Test login page', async ({ page }) => {
  // ...
});
```
What do you think?

**Comment by AlexKomanov** [comment]
Agree and upvote!

**Comment by MindaugasMateika** [comment]
Do they work on standalone functions like Playwright's `test`? From what minimally read and tried, I only managed to get it work on class methods.

**Comment by pavelfeldman** [comment]
As per above, there are no free standing function decorators in JS/TS and the proposal for ones is in the early stage w/o much support.

**Comment by vitalets** [comment]
Ok! Sorry for didn't check it deeper. 
Btw, maybe introduce some api for adding tags?
For example:
```ts
test.tags('@fast', '@mobile');
test('Test login page', async ({ page }) => {
  // ...
});
```
@pavelfeldman What do you think?

**Comment by IPRIT** [comment]
Hi! We need a better tag management! Please make an api on top of `testInfo` similar to `testInfo.annotations`. For example:
```ts
test('Test login page', async ({ page }, testInfo) => {
  testInfo.tags.push({name: "smoke", description: "Some text inside flag's tooltip"})
});
```

**Comment by vitalets** [comment]
> Hi! We need a better tag management! Please make an api on top of `testInfo` similar to `testInfo.annotations`. For example:
> 
> ```ts
> test('Test login page', async ({ page }, testInfo) => {
>   testInfo.tags.push({name: "smoke", description: "Some text inside flag's tooltip"})
> });
> ```

I think tags management should be static to allow filtering tests by tags before run. Have a look on this https://github.com/microsoft/playwright/issues/23180
