### ISSUE TITLE
[BUG] playwright run error  , delete my all files

### ISSUE THREAD

**Issue by liusheng-zhainanya** [microsoft/playwright#22352]
- info
playwright run error  , delete my all files,  It happened twice.

- img
![image](https://user-images.githubusercontent.com/56863304/231394185-98ce5e8e-32f8-4b8a-848b-0a1f5e0f3d1d.png)
![image](https://user-images.githubusercontent.com/56863304/231394364-068986e5-f2f9-4a9f-8d36-079dccec2bdc.png)
![image](https://user-images.githubusercontent.com/56863304/231394971-b8c4514d-3339-4e44-afbb-2d4b15715124.png)

-code
![image](https://user-images.githubusercontent.com/56863304/231394544-069adfd1-0e2d-45de-a2c8-6350519a041c.png)

**Comment by mxschmitt** [comment]
This is very likely not caused by us. (other extensions on your vscode or software might cause it). Please re-file following the [bug issue template](https://github.com/microsoft/playwright/issues/new?assignees=&labels=&template=bug.md&title=%5BBUG%5D) so we can reproduce, otherwise we can't act on it.

**Comment by liusheng-zhainanya** [comment]
info:
I used  'Playwright Test for VSCode' in VScode,At that time, I was indeed operating the plugin. 
I'm not sure why the file was deleted.

img:
![image](https://user-images.githubusercontent.com/56863304/231398744-cffb3f0b-8a89-4976-b8fb-b59c9daac042.png)
![image](https://user-images.githubusercontent.com/56863304/231398830-0a28e2ef-1ad8-459f-afe0-50d3e8a7ba6d.png)

**Comment by liusheng-zhainanya** [comment]
**Context:**
- Playwright Version:  ^1.32.3
- Operating System: Mac
- Node.js version: v16.13.1
- Visual Studio Code version: 1.77.2
- Playwright for VSCode extension version: v1.0.10
- Browser: Chromium

**Comment by liusheng-zhainanya** [comment]
**Code Snippet**

playrwright.config.ts
``` ts
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests', // 测试目录
  expect: {
    /**
     * expect（）应等待满足条件的最长时间
     * 例如，在'await expect（locator）.toHaveText（）'
     */
    timeout: 5000,
  },
  timeout: 30 * 1000, // 每个测试用例超时
  globalTimeout: 60 * 1000, // 总超时
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  // reporter: 'html',
  reporter: [['html', { outputFolder: './', open: 'always' }]], // 测试报告
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    // trace: 'on-first-retry',
    launchOptions: {
      headless: false, // 不是无头模式
    },
    contextOptions: {
      viewport: {
        // 窗口视野大小
        width: 1400,
        height: 900,
      },
    },
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

```
**Describe the bug**
This configuration will delete the local files, but the default settings will not delete

**Comment by liusheng-zhainanya** [comment]
as a result of: reporter: [["html", { outputFolder: "./", open: "always" }]]

**Comment by mxschmitt** [comment]
The output folder of the HTML reporter should never be ".". It should be always a own separate directory, since it gets regenerated every time.
