### ISSUE TITLE
[Feature] Add Prometheus reporter

### ISSUE THREAD

**Issue by oijkn** [microsoft/playwright#22359]
Currently, there is no built-in way to export metrics tests for **Prometheus** when calling endpoint `/metrics`. It would be helpful to have this feature in order to **monitor and analyze** the performance of Playwright tests using Prometheus.

The feature should allow users to export metrics tests in Prometheus format, including metrics such as test duration, success rate, and error rate etc... Users should also be able to configure the frequency and destination of the exported metrics, such as sending them to a Prometheus Pushgateway server or storing them in a file.

Having this feature would enable Playwright users to gain valuable insights into the performance of their tests and identify any potential issues or bottlenecks. This would help improve the overall quality and reliability of Playwright tests.

**Comment by pavelfeldman** [comment]
This falls outside of the scope for Playwright, so we leave it to the third party. We believe we have enough reporter API exposed, please file individual requests for what is missing in the API.
