### ISSUE TITLE
[BUG] textContent() shows incorrect data without timeout

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#22367]
### System info
- Playwright Version:  "playwright": "^1.28.1",
- Operating System: MAC OS
- Browser: Chromium
- Other info:

I do have a list box with the list of options, Attached is the screenshot, in order to pick the item in the listbox, first I am trying to click on the listbox itself based on the text that it has , eg: DAL, then chose the available option from the list box eg:BWI and then expand the listbox again by clicking on the previously selected value -BWI, then choose the next available option ,and goes on...

eg:When a user click on DAL, locator('.react-select__single-value') will be set to DAL, and the list box shows the available other options in the list and when user selects BWI, then ('.react-select__single-value') should be set now to BWI, in order to click the listbox, need to capture the value that was previously selected in the listbox, that way the user knows which element (eg: DAL,BWI etc) to click on to further click and  expand the list box

```javascript
await page.getByTestId('search-field-wrapper-base').locator('div').filter({ hasText: 'DAL' }).nth(3).click();
// await page.waitForTimeout(1000)
const station = await page.getByTestId('search-field-wrapper-base').locator('.react-select__single-value').textContent();
 console.log("station" + station)
await page.getByText('BWI', { exact: true }).click();
 //await page.waitForTimeout(1000)
 const station1 = await page.getByTestId('search-field-wrapper-base').locator('.react-select__single-value').textContent();
console.log("station1" + station1)
 await page.getByTestId('search-field-wrapper-base').locator('div').filter({ hasText: station1 }).nth(3).click();
 // await page.waitForTimeout(1000)
  await page.getByText('HOU', { exact: true }).click();
```

WITH TIME OUT:
station DAL
station1 BWI

WITHOUT TIMEOUT:
station DAL
station1 DAL

looks like locator('.react-select__single-value') is taking a while to update with the value that user selects, when i add timeout it works fine, but without timeout it fails with the error.
```
locator.click: Error: strict mode violation: getByText('DAL', { exact: true }) resolved to 2 elements:
    1) <div class="react-select__single-value css-15g31vs-si…>DAL</div> aka getByText('DAL').first()
    2) <div tabindex="-1" aria-disabled="false" id="react-se…>DAL</div> aka locator('#react-select-2-option-3')
```

Can you please advise how i can assert if the class value locator('.react-select__single-value') is updated with the base -BWI , DAL(for eg) after user selects the value?  (verify if a class locator matches the text)
or automatically wait for the locator value to get updated with the new value after user selects the option in 
not sure if waitForSelector is useful here.. please advise.

<img width="1639" alt="Screen Shot 2023-04-12 at 3 04 37 PM" src="https://user-images.githubusercontent.com/113629123/231578048-271dc84c-6dc8-41e7-a7b3-226573c5a87d.png">

**other observation:**

if i hard code the hasText:DAL or BWI , it works without timeout,  but is there a way to dynamically read the updated text from the locator class --> ('.react-select__single-value') and use it for filter({ hasText: 'DAL' }), instead of remembering or hard coding every time the value that was previously selected... 

is there a way  to make class locator to wait for the new value to update, instead of using page.waitForTimeout(), and a way to dynamically verify the value in the class locator instead of hard coding using  hasText: 'BWI'..

await page.getByTestId('search-field-wrapper-base').locator('div').filter({ hasText: 'DAL' }).nth(3).click();
        const station = await page.getByTestId('search-field-wrapper-base').locator('.react-select__single-value').textContent();
        console.log("station" + station)
        await page.getByText('BWI', { exact: true }).click();
        await page.getByTestId('search-field-wrapper-base').locator('div').filter({ hasText: 'BWI' }).nth(3).click();
        const station1 = await page.getByTestId('search-field-wrapper-base').locator('.react-select__single-value').textContent();
        console.log("station1" + station1)

looking forward to your reply. Thank you!
            
without timeout 
station DAL
station1 BWI

**Comment by mxschmitt** [comment]
We don't see your full code, but I guess that you are getting the textContent to either make conditional statements or to do manual assertions. We strongly discourage both, and recommend to use [our Playwright assertions](https://playwright.dev/docs/test-assertions) instead, since they will automatically retry until a certain condition is met.

In your case toHaveCount, toHaveText or toHaveValue seem like what you need.

Most likely the reason why you get unexpected results without waitForTimeout, is that the select element is fetching data from the backend (takes time), and while its loading it gives the old or not complete results.

**Comment by InduKrish** [comment]
ok, thank you. Much appreciated!

and i tried to click on the listbox so it expands, i can select by index.. I tried all three options, but it did not click on the listbox for it to expand. the html is attached above.. can you please advise,

```javascript
await page.getByTestId('search-field-wrapper-base').locator('.react-select__control').click(); - unable to click on the listbox to expand
await page.getByTestId('search-field-wrapper-base').locator('.react-select__value-container').click(); - unable to click on the listbox to expand
await page.getByTestId('search-field-wrapper-base').locator('.react-select-container').click(); - unable to click on the listbox to expand
 await page.getByTestId('search-field-wrapper-base').locator('.react-select__menu').locator('div').nth(1).click();

await page.getByTestId('search-field-wrapper-base').locator('.react-select__control').click();
await page.getByTestId('search-field-wrapper-base').locator('.react-select__menu').locator('div').nth(2).click();
```

**Comment by mxschmitt** [comment]
I'll close it for now as part of the triaging process, please re-file for follow-up questions or bugs.
