### ISSUE TITLE
display filename in Junit reports for each testSuite tag

### ISSUE THREAD

**Issue by kp-abhishek-agrawal** [microsoft/playwright#22374]
Hi, 

I'm using CircleCI to run my tests and trying to split tests based on timing data. To do this, I need JUnit output, and CircleCI needs to know the filename for each test in order to know how to run them. I haven't found any cleaner solution yet to display `filename` on testSuite level in xml file. Do you know if there is any way?

I think, this is quite important feature because split by time on circleCI really reduce lot of ideal time (much better than sharding) & other frameworks like cypress supports it in much cleaner way.

**Comment by mxschmitt** [comment]
Splitting based on old timing data is not supported yet. Implementing a CI provider specific solution is outside of the scope for Playwright. A generic CI provider feature request is filed as https://github.com/microsoft/playwright/issues/17969 already, folding into it, by that.
