### ISSUE TITLE
[BUG] Pirates Require hooks didn't return anything from it's handler - Cannot read properties of undefined (reading 'isNative')

### ISSUE THREAD

**Issue by kLjubomir** [microsoft/playwright#22381]
### System info
- Playwright Version: [v1.30]
- Operating System: [ Jenkins CI, Docker, Ubuntu 20]
- Browser: [Chromium]
- Other info:

### Source code
**Link to the GitHub repository with the repro**

https://github.com/kLjubomir/playwright_reproducible

Additional information on Jenkins and Dockerization:
**dockerfile content**
```
#
# Dockerfile Description
#
FROM ubuntu

MAINTAINER Paul Brown

RUN apt-get update -y && apt-get install -y \ 
    curl 
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash -
RUN apt-get -y install nodejs
RUN npm install -g playwright 
```

**Playwright Setup - Jenkins**

A Jenkinsfile is used, with this stage to run the tests inside a docker container and not the Jenkins host.

```
stage('Running Tests') {
            agent {
                docker {
                    image “url to docker image”  (dockerfile to generate is attached)                                                        
                    registryUrl “docker registry url”
                    registryCredentialsId XXXXXXXXXXX
                    args "-u root --shm-size=4gb -v $WORKSPACE/$tests_Dir:/tmp/tests"
                    reuseNode true
                }
            }
            steps {
                script {
                    String testsDir = "/tmp/tests"
                    RunBrowserTests(friendlyAppName, Target_URL, Test_Specs_GLOB, NPM_Script, testsDir, "", Target_Environment, Secret_Data_Path, Technology_Stack, "", "", Extra_Switches, "", "$WORKSPACE", CheckBooleanParam(Use_Script), Script_Config)
                }
            }
        }

```

RunBrowserTests does the following….

Runs the bash script here : https://bitbucket.org/eurotaxglass1/av-automatron/src/master/runtests.sh 
E.g : bash /tmp/tests/runtests.sh staging Regression true true

**Steps**
Run the tests over Jenkins repeatedly.

**Expected**
Tests are initiated concurrently, one param "de" runs with a project and grep of "de" and the other param "uk" runs with project and grep "uk", each run produces its own report, one in the "DE" and one in the "UK" folder of the playwright-report folder.

**Actual**
If running these tests on repeat, there will eventually within 10-20 runs be an error on Jenkins CI containing the Pirates dependency description, and when that occurs one of the concurrent runs will not execute or produce results, while the other concurrent run will. This happens with production code a lot more (every 2-4 runs) than with the boilerplate obscured code I have provided in the issue.

**Comment by kLjubomir** [comment]
> How do you run them concurrently? Do you run npx playwright test on the same host multiple times in parallel.
> 
> I tried to run `bash runtests.sh staging Regression true true` and was not able to reproduce it.

Hello,

The tests are run concurrently by just executing the script, runtests.sh has the following:
`npm run execute-all`

and package.json contains the following:
```
  "scripts": {
    "test": "cross-env test_env=staging npx playwright test",
    "run-de": "cross-env test_env=${environment_name} ENV_NAME=DE npx playwright test --project=de ${scope}",
    "run-uk": "cross-env test_env=${environment_name} ENV_NAME=UK npx playwright test --project=uk ${scope}",
    "execute-all": "concurrently ${runCountries}"
  },
```

**Comment by mxschmitt** [comment]
Then this is the issue. Running Playwright tests concurrently is not supported, since the cache will end up being conflicting with other caches. We recommend using multiple [Playwright projects](https://playwright.dev/docs/test-projects) for this instead, there you can also [parameterise it](https://playwright.dev/docs/test-parameterize).

Since running npx playwright test on the same directory concurrently won't be supported, I'm closing this for now.

**Comment by kLjubomir** [comment]
So, this would mean that either the entire framework needs to be run using one worker and would double the execution time in my case, unless workers could be specified in the project scope of the config, such as this issue suggest? https://github.com/microsoft/playwright/issues/21970

We used concurrency because we can't control test data and need a project to run with one test data and the other project with different test data, parallelization would cause double sessions and break the tests.

**Comment by mxschmitt** [comment]
You are right, this is a blocker for that, if each project require to run with a single worker.

So for now we unfortunately then only have double the execution time or spawn two docker containers.

**Comment by pavelfeldman** [comment]
@kLjubomir please upvore the workers-for-project feature.
