### ISSUE TITLE
[Feature] Hide file pickers if they will be emulated

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2238]
It would be cool to either hide file pickers by default or hide them if `setInputFiles` was used before. It has no downsides except they are there and needs to be closed manually.

**Comment by pavelfeldman** [comment]
Ouch :) We hide it when there is a `'filechooser'` listener registered, but I can see how that is not enough.

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.
