### ISSUE TITLE
[Question] Getting RGB instead on expected RGBA

### ISSUE THREAD

**Issue by KBarterDev** [microsoft/playwright#22387]
So the problem I'm seeing is I'm getting a RGB value back when I should be getting back RGBA for the background color. 

Here is an example of what I'm getting back.

`Expected: "rgba(255, 255, 255, 1)"`
`Received: "rgb(255, 255, 255)"`

For the test I am using window.getComputedStyle to get the background color. Any insight why I might be seeing this difference in Playwright would be greatly appreciated.

**Comment by mxschmitt** [comment]
Since this is not related to Playwright and more generic to the Web APIs, I recommend looking on StackOverflow or asking it on Discord. See e.g.:

- https://stackoverflow.com/questions/40869244/how-to-return-rgba-value-from-window-getcomputedstyle-or-other-function
- https://gist.github.com/binarymax/0c12f01056c1ab947216c7d49ba58d72

**Comment by KBarterDev** [comment]
Even though in Selenium I'm getting back the correct expected value of `rgba(255, 255, 255, 1)` and in Playwright getting the result of `rgb(255, 255, 255)`

**Comment by mxschmitt** [comment]
Oh interesting! You do getComputedStyle on both sides?

**Comment by KBarterDev** [comment]
No, just on Playwright's side.

**Comment by mxschmitt** [comment]
What do you do in Selenium then?

**Comment by KBarterDev** [comment]
In Selenium, this gives the RGBA `elementInstance.getCssValue(attribute);`

**Comment by mxschmitt** [comment]
Just for future reference: getCssValue always returns it as rgba as per above. See [here](https://github.com/SeleniumHQ/selenium/blob/395a92669255cbf8d2f4efb5bcffa359b1507b3c/javascript/atoms/color.js#L38) in their internal implementation.

You'd have to manually convert it to rgba if you want to use that.
