### ISSUE TITLE
[BUG] "export type *" causes unexpected token error with Typescript

### ISSUE THREAD

**Issue by mattjennings** [microsoft/playwright#22388]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All]
- Browser: [All]
- Other info: Typescript version is ^5.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/mattjennings/playwright-ts-export-type-bug

**Steps**
- Run `npm install`
- Run `npm run typecheck` and note that there are no errors
- Run `npm run test`

**Expected**

Test runs with no compile errors

**Actual**

`playwright test` errors with:

```
Error: /Users/mattjennings/tmp/tspw/tests/utils/index.ts: Unexpected token (1:12)

> 1 | export type * from './types'
    |             ^
  2 | export { something } from './types'

   at example.spec.ts:2

  1 | import { test, expect } from '@playwright/test';
> 2 | import { something } from './utils'
    | ^
  3 |
  4 | test('has title', async ({ page }) => {
  5 |   something()
```

This syntax is supported as of [Typescript 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#support-for-export-type), and Playwright seems to be using Typescript ^5.0.0, so I'm unsure why this error is thrown.

**Comment by mxschmitt** [comment]
Should be fixed in our next release, can you try again with our Canary version? https://playwright.dev/docs/canary-releases

**Comment by mattjennings** [comment]
@mxschmitt oh awesome - yes, it is fixed in Canary

**Comment by mxschmitt** [comment]
Cool then closing by that!
