### ISSUE TITLE
[BUG] `trace.playwright.dev` does not load on firefox in private browsing

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#22399]
### System info
- Playwright Version: n/a
- Operating System: windows 10
- Browser: firefox

### Source code
N/A

**Steps**
1. open a private browing window with `ctrl+shift+P`
2. navigate to https://trace.playwright.dev

**Expected**

site loads

**Actual**
blank screen with the following error in the console:
```
Uncaught (in promise) TypeError: can't access property "register", navigator.serviceWorker is undefined
```
![image](https://user-images.githubusercontent.com/57028336/231981087-f94dc32a-793d-4ab6-95f7-2cadf16e4a77.png)

**Comment by mxschmitt** [comment]
Firefox private tab does not support service workers, see https://bugzilla.mozilla.org/show_bug.cgi?id=1320796. I created https://github.com/microsoft/playwright/pull/22402 to have a better error message for it.

**Comment by pavelfeldman** [comment]
https://caniuse.com/serviceworkers now has a "Known issue" for this use case, suggesting that Firefox private browsing is not going to run PWAs. I'd close this is a "known issue" here as well.
