### ISSUE TITLE
[Question] Expect and Received value not coming in readable format

### ISSUE THREAD

**Issue by sankarkec** [microsoft/playwright#22395]
I am developing my own custom report. I have written simple code to validate like expect.soft(36, "Checks 36 equals - 23").toBe(23);
In step.error.message i am getting the value in different format which is not readable like 'Expected: [32m23[39m Received: [31m36[39m'. How to convert value into readable format. In playwright do we have any flags to change the format ?

**Comment by MindaugasMateika** [comment]
I think this is just ansi symbols to display colorized text in the reporters. You can try to set process.env.FORCE_COLOR = 'false' but I believe you'll lose colors in other reporters or strip ansi using regex:
```
/[\u001B\u009B][[\]()#;?]*(?:(?:(?:[a-zA-Z\d]*(?:;[-a-zA-Z\d\/#&.:=?%@~_]*)*)?\u0007)|(?:(?:\d{1,4}(?:;\d{0,4})*)?[\dA-PR-TZcf-ntqry=><~]))/g
```
