### ISSUE TITLE
[BUG] grep-invert not working as expected when using project dependencies

### ISSUE THREAD

**Issue by lasseklovstad** [microsoft/playwright#22405]
### System info
- Playwright Version: [v1.32.3]
- Operating System: Windows 10
- Browser: All
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
```typescript
// globalSetup.ts
test("Login admin @setup", () => {
    // Login code
});

// test.spec.ts
test("Test something", () => {
    // Some test code
});
```

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    { name: "setup", testMatch: "globalSetup.ts" },
    { name: "tests", testMatch: "test.spec.ts", dependencies: ["setup"] }
  ],
});
```

**Steps**
Run this command:
``npx playwright test --grep-invert=@setup --list``

**Expected**
I would excepect all tests tagged with @setup would not be run.

Ouput:
[tests] > Test something

**Actual**
Ouput:
[setup] > Login admin @setup
[tests] > Test something

[Describe actual behavior]

**Comment by mxschmitt** [comment]
**Investigation notes**: [cliTitleMatcher](https://github.com/microsoft/playwright/blob/635a2dac161fabc153186cfbcaabe8b434112716/packages/playwright-test/src/runner/loadUtils.ts#L132) does not get used for [prepended project dependencies](https://github.com/microsoft/playwright/blob/635a2dac161fabc153186cfbcaabe8b434112716/packages/playwright-test/src/runner/loadUtils.ts#L180).

**Comment by pavelfeldman** [comment]
This is as designed, please see the [docs](https://playwright.dev/docs/next/test-global-setup-teardown#project-dependencies). Test "Test something" needs the project "setup" to run (as defined in the config). So when running the test, entire setup project runs.
