### ISSUE TITLE
[BUG] Playwright doesn't wait for table to load

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#22408]
### System info
Playwright Version: "playwright": "^1.28.1",
Operating System: MAC OS
Browser: Chromium
- Other info:

here the user selects round in the dropdown, then the corresponding table row gets loaded. but when i run the test, after selecting the value in the dropdown, playwright doesn't wait for the table row to load after user selects the value in the dropdown, it shows previous table row(incorrect data).. 

can you please advise what the other better way that i can accommodate other than using static timeout await page.waitForTimeout(1000) ?

```javascript
//fetches all table rows
let reportingTable = await actor.attemptsTo(FetchAllRowsByTable.byId('paged-table-IFVacationCrewReportsAwardsAlphaAwards')
await page.getByTestId('search-field-wrapper-round').locator('.react-select__value-container').click();
//selecting the value from the dropdown that matches text 1.
await page.getByTestId('search-field-wrapper-round').locator('.react-select__menu').locator('.react-select__option').filter({ hasText: "1" }).click();  
await page.waitForTimeout(1000) --> **i have to manually wait for the table rows to load, 
is there a better way instead of using waitforTimeout(1000)**, without waitforTimout , it loads incorrect table row.
const empId =await reportingTable.within().queryByTestId(/td-IFVacationCrewReportsAwardsAlphaAwards-employeeId/).textContent();
console.log("empId" + empId)
const dates =await reportingTable.within().queryByTestId(/td-IFVacationCrewReportsAwardsAlphaAwards-dates/).textContent();
 console.log("dates" + dates)
          
```

**output: (without Timeout)** without timeout , it shows the value for text matching 3, although i query for text 1.
empId 5050
dates Jan 15—21 

**with Timeout**
empId 5050
dates Dec 15—28, Jul 1—7. (This is the output i expect to see), but it works only when i add waitforTimeout.

<img width="1309" alt="Screen Shot 2023-04-14 at 10 37 01 AM" src="https://user-images.githubusercontent.com/113629123/232090631-c49ffaf1-5027-4a8e-9d6e-0b597ccaa1e5.png">

<img width="1278" alt="Screen Shot 2023-04-14 at 11 27 38 AM" src="https://user-images.githubusercontent.com/113629123/232102173-2eae16f8-b6d9-453a-add1-7bd4b7a0d136.png">

not sure if waitForLoadState is something that i can use,
await page.waitForLoadState("domcontentloaded"); --> i tried using instead of  waitForTimeout, it still shows Jan 15—21 (incorrect table data)

 can you please advise?

**Comment by ozyx** [comment]
Instead of `waitForTimeout` or `waitForLoadState`, you could try waiting on the visibility of a certain DOM node using a [toBeVisible()](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-visible) (or similar) assertion.

**Comment by InduKrish** [comment]
ok,meanwhile Can you please advise when waitForLoadState will be appropriate to use? Can you please give me an example?

**Comment by ozyx** [comment]
> ok,meanwhile Can you please advise when waitForLoadState will be appropriate to use? Can you please give me an example?

There are a couple good examples and an explanation [here](https://playwright.dev/docs/api/class-page#page-wait-for-load-state).

**Comment by mxschmitt** [comment]
waitForLoadState is not correct here. You should use [waitFor](https://playwright.dev/docs/api/class-locator#locator-wait-for) which waits for elements to be visible. Since this issue does not contain any source code which we can run locally, we unfortunately can't act on it. So please re-file with reproduction steps.
