### ISSUE TITLE
[BUG] Sometimes expect() is shown as 2 actions within UI mode

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#22416]
### System info
- Playwright Version: [v1.32.3] 
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

**Steps**
- Have a UI test with multiple assertions/expects in it (toHaveTitle, toBeVisible, etc.)
- Run that test from UI mode

**Expected**

I assume for a single line expect() to have only one action within the Actions panel in UI mode

**Actual**

I see two actions for a single like expect() that I have in my code.

![image](https://user-images.githubusercontent.com/94455079/232154464-177a5b0c-818d-4b7e-a00a-9ee3b0fa7f11.png)

![image](https://user-images.githubusercontent.com/94455079/232154566-18a5649f-3db4-4c48-920a-ab7b01eb1484.png)

**Comment by mxschmitt** [comment]
I can't reproduce, do you mind sharing a test with us which ends up in such a behaviour?

I tried the following:

```ts
import { test, expect } from '@playwright/test';

test('has title', async ({ context }) => {
  const page = await context.newPage();
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Comment by mxschmitt** [comment]
Please re-file with more details and a repro, thanks!
