### ISSUE TITLE
[BUG]After updating Playwright version to 1.32.0, getting an error "browser.newPage: Target closed"

### ISSUE THREAD

**Issue by devmasonn** [microsoft/playwright#22415]
**Context:**
Playwright Version: 1.29.2
Operating System: Mac OS version 12.0.1 Monterey
Node.js version: v17.0.1
Browser: WebKit
Extra: NA

**Code snippet:**

**SignIn.test.ts:**

test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();
        await page.goto("https://www.google.com");
        const loginPage = new LoginPage(page);
})

I was using Playwright version 1.29 and after updating to 1.32.0 I am seeing this error : **browser.newPage: Target closed** . While checking gitHub issues I saw at one place saying you need to update macOS version. Here is the link for the same for reference: https://github.com/microsoft/playwright/issues/20576

**It is giving an error at -** 
test.beforeAll(async ({ browser }) => {
        page = await browser.newPage();        

Could you please help to fix this issue? Is it a mandate to update macOS version after updating Playwright version to 1.32.0 ?

**Comment by mxschmitt** [comment]
Most likely your macOS version 12.0.1 needs to be updated to a more recent version e.g. 12.6.5 which is the latest macOS 12 version which is caused due to upstream WebKit constrains. Upgrading macOS from 12.0 to 12.6 should not cause much troubles and it includes a lot of security fixes from Apple!

**Comment by devmasonn** [comment]
> Most likely your macOS version 12.0.1 needs to be updated to a more recent version e.g. 12.6.5 which is the latest macOS 12 version which is caused due to upstream WebKit constrains. Upgrading macOS from 12.0 to 12.6 should not cause much troubles and it includes a lot of security fixes from Apple!

Thank you for your reply @mxschmitt , meaning to work with newer Playwright version we don't have any other option than updating macOS version ? Could you please suggest any other possible solution to fix this issue ?

**Comment by mxschmitt** [comment]
Yes, there is no other solution than updating macOS. Your macOS version does not include the latest minor security fixes.

Closing as per above, since we only guarantee to work on the OS with the latest minor updates installed.
