### ISSUE TITLE
[Feature] test.step to implicitly expect.toPass

### ISSUE THREAD

**Issue by kumarchandresh** [microsoft/playwright#22428]
Instead of doing,
```js
test('Login test', async ({ page }) => {
  await test.step('Enter User ID', () => expect(async () => {
    await userID.fill('ADMIN');
    await expect(userID).toHaveValue('ADMIN');
  }).toPass());
});
```

---

I would like to have,
```js
test('Login test', async ({ page }) => {
  await test.step('Enter User ID', async () => {
    await userID.fill('ADMIN');
    await expect(userID).toHaveValue('ADMIN');
  }); // toPass is implicit here
});
```

And a config,
```js
{
  expectStepToPass: true
}
```

**Comment by pavelfeldman** [comment]
`test.step` and `expect.toPass` are two of many building blocks that you use when creating a test. While this combination is sensible, providing the combinations like this make API surface overly complicated. You can always extract a utility function that does it for you in the userland.
