### ISSUE TITLE
[Feature] Implement a new execution mode - "normal"

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#22422]
**Google:**
Playwright how to execute the `beforeAll` hook only once to setup test data

# Background:

Introduce a new execution mode - "normal" (or whatever else you want to call it).  This mode is very much similar to `.serial` but **it will not execute tests in order**

## Requirements:
- `simple.spec.ts` will be executed using 1 single worker process
- `beforeAll` hook should **only be executed once**
- `beforeEach, afterEach, afterAll` hook should be a behave as normal
- tests within the `simple.spec.ts` can run in any order
- a single test will be executed at a time
- when a retry is triggered, the `beforeAll` and `beforeEach` hooks should be executed again, only the tests that failed should be re-executed

# Snippet

*`simple.spec.ts`*
```typescript
import { test } from '@playwright/test';

test.describe.configure({ mode: 'normal' });
let testData;

test.beforeAll(async () => { 
  testData = await setupTimeConsumingResourceIntensiveTestData();
 });

test('test A', async ({ page }) => { 
  console.log(testData);
 });

test('test B', async ({ page }) => {   
  console.log(testData);
});
```

## Desired behavior:
> `simple.spec.ts` will be executed using 1 single worker process, test A and test B can run in any order.  Both test A and B will output the same `testData` value since the `beforeAll` hook is only executed once.

# Why not use `test.describe.serial` mode?
Serial mode is terrible, it promotes bad practices and is very troublesome whenever a `retry` event is triggered.  It makes it very time consuming to run a single targeted test within a test suite since tests execution are intermingled with the previous test(s)

# Why not use the `globalSetup` to do the test data setup?
No.  This is not a solution.  Each spec file may have its own unique test data setup requirements. The `globalSetup` is a one size fits all solution.  It is not flexible enough to handle the unique requirements of each spec file.

# Bonus points:
For those unlucky enough to have implemented a majority of their test suites using the `serial` mode.  We should make it very easy to refactor their suites to use this new mode.

e.g. Replace  `test.describe.configure({ mode: 'serial' })` with `test.describe.configure({ mode: 'normal' })`

**Comment by pavelfeldman** [comment]
How is it different from the existing default mode?

**Comment by ryanrosello-og** [comment]
The existing "**normal**" mode executes the `beforeAll` hook multiple times depending on the worker/sharding configuration specified.

The example shows the `beforeAll` hook being executed twice.

> **simple.spec.ts**

```typescript
import { test } from '@playwright/test';


let testData;

test.beforeAll(async () => {
  testData = await setupTimeConsumingResourceIntensiveTestData();
 });

test('test A', async ({ page }) => {
  console.log(testData);
 });

test('test B', async ({ page }) => {
  console.log(testData);
});

async function setupTimeConsumingResourceIntensiveTestData() {
  return new Date();
}
```

**Output:**

![image](https://user-images.githubusercontent.com/50574915/232272278-67cea1d1-34d4-4b2c-9bc3-bdbd4fa3bf4b.png)

**Comment by pavelfeldman** [comment]
That is because you specified `fullyParallel` in your config. It is equivalent of specifying mode `parallel` in every file.

**Comment by ryanrosello-og** [comment]
Thanks @pavelfeldman , that was exactly my problem 🤦 I had `fullyParallel: true`, setting it false now executes the `beforeAll` only once 🎉 even when #workers configured is greater than 1.

**Comment by mxschmitt** [comment]
Sounds like we then close this feature request?

**Comment by ryanrosello-og** [comment]
Yup go ahead and close @mxschmitt
