### ISSUE TITLE
[Feature] Add "slider" diff to UI mode and Trace viewer / snapshots / screenshot comparison

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#22425]
Hello PW team,

would it be possible to add the image missmatch section (slider diff), that we have in the html report, to the UI Mode/Traceviewer.

Maybe we could have the 'Diff', 'Actual' and 'Expected' tabs after the 'After' tab when we use the expect.toHaveScreenshot

![image](https://user-images.githubusercontent.com/94455079/232315885-cafd638b-894d-499b-b45a-4e31eef8afeb.png)

Currentlly we have only the error printed, so I need to close UI mode and open html report to see the difference between the images.

**Comment by wederer** [comment]
Just wanted to create a similar ticket. We use `toHaveScreenshot` in most tests and ui mode does not really provide a big benefit over just checking the report.

**Comment by mxschmitt** [comment]
This was implemented in 1.34.
