### ISSUE TITLE
is FullConfig Interface used in the configuring the global setup file only supported for ts? As per the playwright documentation . it should support both js and ts

### ISSUE THREAD

**Issue by moumita30** [microsoft/playwright#22438]
### System info
- Playwright Version: 1.31.2
- Operating System:  Windows 11
- Browser: All, Chromium, Firefox, WebKit
- Other info:

### Source code

![image](https://user-images.githubusercontent.com/57482730/232571195-9882edfd-edbd-4a91-84e7-e2c8ea570ebc.png)

**Comment by dgozman** [comment]
@moumita30 Type annotations like in this screenshot are a part of the TypeScript language and are not present in the JavaScript language. The `config` is still available, you should remove the type annotations though. [Learn more about TypeScript](https://www.typescriptlang.org/).

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
