### ISSUE TITLE
[BUG][Experimental CT React][Firefox] Mouse sometimes have incorrect position

### ISSUE THREAD

**Issue by inomdzhon** [microsoft/playwright#22432]
### System info
- Playwright Version: v1.32.3
- Operating System: Ubuntu 20
- Browser: Firefox
- Other info: I use `mcr.microsoft.com/playwright:v1.32.3-focal` image

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Component [packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx](https://github.com/VKCOM/VKUI/blob/117227b6f196abb7ed2c25e58a3032d69e5e1674/packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx)

My config [packages/vkui/playwright-ct.config.ts](https://github.com/VKCOM/VKUI/blob/117227b6f196abb7ed2c25e58a3032d69e5e1674/packages/vkui/playwright-ct.config.ts)

**Link to the GitHub repository with the repro**

https://github.com/VKCOM/VKUI/

**Steps**

- Install Docker before
- Remove this workaround [packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx#L13](https://github.com/VKCOM/VKUI/blob/117227b6f196abb7ed2c25e58a3032d69e5e1674/packages/vkui/src/components/SegmentedControl/SegmentedControl.e2e.tsx#L13)

(you can run next commands from root directory or `package/vkui`)

- Run `yarn install`
- Run `yarn test:e2e`

> Additionally, u can use `.env` file for set projects and test match
> ```
> cp packages/vkui/.env.developent.local packages/vkui/.env
> ```

**Expected**

SegmentedControl.e2e.tsx and all another tests are passed.

**Actual**

Sometimes `SegmentedControl.e2e.tsx` is failing.

BUT! If we run only `SegmentedControl.e2e.tsx` test this is passing 🤔 

#### Workaround

I reset for `SegmentedControl.e2e.tsx` test mouse position.

```ts
await page.hover('body', { position: { x: 0, y: 0 } });
```

**Comment by dgozman** [comment]
@inomdzhon Is there a small subset of tests that exhibit this behavior, so that we can look closely and debug? Does the mouse stay in a position left from the previous test? Could you share a failure example - I assume it's a screenshot diff?

Overall, if you require specific mouse position, it is usually a good practice to set it up in the test, e.g. by calling `await page.mouse.move(x, y)`. Relying on the default mouse position could be flaky indeed, especially if you ever run your tests headed, if only to debug.

**Comment by inomdzhon** [comment]
Hi, @dgzoman

Thanks for response 🙏 

> Is there a small subset of tests that exhibit this behavior, so that we can look closely and debug? 

Before I want to try describe interesting moment when I'm playing with Playwright settings. There are settings on the `packages/vkui/.env` that I'm using for research this problem.

✅ All test "always" pass (_`PLAYWRIGHT_WORKERS` could be **1** or **3** too_)
```
PLAYWRIGHT_FORCE_PROJECTS = '[
  "vkcom (firefox) • light",
  "vkcom (firefox) • dark"
]'
PLAYWRIGHT_WORKERS = 2
```

❌  Usually `SegmentedControl.e2e.tsx` test failed (_sometimes test pass_)
```
PLAYWRIGHT_FORCE_PROJECTS = '[
  "vkcom (firefox) • light",
  "vkcom (firefox) • dark"
]'
PLAYWRIGHT_WORKERS = 4
```

✅ All test "always" pass (_`PLAYWRIGHT_FORCE_PROJECTS` could be every another projects, but not same_)
```
PLAYWRIGHT_FORCE_PROJECTS = '[
  "vkcom (firefox) • light",
  "vkcom (chromium) • dark" <-- different browser
]'
PLAYWRIGHT_WORKERS = 4
```

Our projects list here [packages/vkui/playwright-ct.config.ts#L128-L176](https://github.com/VKCOM/VKUI/blob/519e67a49ec369d2026c49c2adceeed4b144c3e2/packages/vkui/playwright-ct.config.ts#L128-L176).

---

> Does the mouse stay in a position left from the previous test?

Yesterday, I thought about this too. I remembered that we have this test [packages/vkui/src/components/HorizontalScroll/HorizontalScroll.e2e.tsx#L48-L91](https://github.com/VKCOM/VKUI/blob/519e67a49ec369d2026c49c2adceeed4b144c3e2/packages/vkui/src/components/HorizontalScroll/HorizontalScroll.e2e.tsx#L48-L91). If you could see we use `page.hover` on element (see snapshot below).

<img width="600" src="https://user-images.githubusercontent.com/5850354/232721730-37824661-2b45-45d2-89fc-07bdfd3374c1.png" />

**Picture 1.** _`item 9` have hover state_

---

> Could you share a failure example - I assume it's a screenshot diff?

Sure, there is CSS selector of a `SegmentedControlOption` – the `SegmentedControl` use them inside for render items.

```css
.SegmentedControlOption:not(.SegmentedControlOption--checked):hover {
  opacity: 0; /* For test I decrease value to zero. Previous value is 0.5 */
}
```

<img width="320" alt="Снимок экрана 2023-04-13 в 12 02 33" src="https://user-images.githubusercontent.com/5850354/231713057-df1c334f-4fd1-4ebd-92c7-2b18e24a50a3.png"> <img width="320" alt="Снимок экрана 2023-04-13 в 12 02 44" src="https://user-images.githubusercontent.com/5850354/231713105-3e00d89c-8cac-45bc-9069-36545b89b193.png">

**Picture 2.** In actual snapshot "Ok" is disappeared.

---

> Overall, if you require specific mouse position, it is usually a good practice to set it up in the test, e.g. by calling await page.mouse.move(x, y). Relying on the default mouse position could be flaky indeed, especially if you ever run your tests headed, if only to debug.

Hmmm I got it. Could I set `page.mouse.move(0, 0)` for before start every tests in common place? In `test.extend` for example. I don't prefer use `test.beforeAll` for every test file 😣

**Comment by dgozman** [comment]
Thank you for your answers, we'll see what we can do to help you.

> Hmmm I got it. Could I set page.mouse.move(0, 0) in common place? Before start every tests, I mean. In test.extend for example. I don't prefer use test.beforeAll for every test file 😣

Take a look at [overriding page fixture](https://playwright.dev/docs/test-fixtures#overriding-fixtures) - you can call `page.mouse.move(0, 0)` right there.

**Comment by inomdzhon** [comment]
> Thank you for your answers, we'll see what we can do to help you.

🙏 

> > Hmmm I got it. Could I set page.mouse.move(0, 0) in common place? Before start every tests, I mean. In test.extend for example. I don't prefer use test.beforeAll for every test file 😣
> 
> Take a look at [overriding page fixture](https://playwright.dev/docs/test-fixtures#overriding-fixtures) - you can call `page.mouse.move(0, 0)` right there.

Hm, thanks, I will try to use this.

Could you help me to know about default page fixture looks like? I don't want to break current behavior of page fixture.

**Comment by dgozman** [comment]
> Could you help me to know about default page fixture looks like? I don't want to break current behavior of page fixture.

The idea of overriding fixtures is that you can use the default `page` implementation, and just add your own tweaks. There is no need to replicate the original fixture. Take a look at the example in the guide, it uses an existing `page` to navigate it.

**Comment by inomdzhon** [comment]
I move workaround from `SegmentedControl.e2e.tsx` to common place [packages/vkui/src/testing/e2e/index.playwright.ts#L42-L47](https://github.com/VKCOM/VKUI/blob/38ebe0d89e7aa118e0ab1b9cb82bc9a05c4c7437/packages/vkui/src/testing/e2e/index.playwright.ts#L42-L47).

Thank you very much 🙏🙏🙏 

Now this issue not actual for me 🎉  Could I close it?

**Comment by dgozman** [comment]
> Now this issue not actual for me 🎉 Could I close it?

Please keep it open - we will probably make a Firefox-specific fix for the next release.
