### ISSUE TITLE
[Feature] waitForPaintIdle (or similar) to wait for the browser to finish painting

### ISSUE THREAD

**Issue by rkennedy-mode** [microsoft/playwright#22439]
This may be more of a feature request for microsoft/playwright, but we use the Java bindings so I thought I would start here.

We have some interactions that are performed on a page, after which we generate screenshots. We are finding in some situations that the generated screenshots are mostly/entirely blank. We believe this is because one of the page interactions that we perform (resizing an iframe) causes Chromium to "re-paint" the page contents.

There's presently no way to wait for any in-progress painting to complete, which makes it difficult for us to do much more than:

1. Add a sleep of some amount of time (static or dependent on an attribute of the page, e.g. the size)
2. Take and compare consecutive screenshots to see if we can observe changes that would imply that the browser is still painting

One of the reasons that we suspect we're encountering a [re-]painting delay issue is that PDFs seem to be unaffected by our interaction model. Our PDFs always seem to come out fully formed, which (I'm guessing) has to do with the pipeline for converting HTML to PDF and doesn't rely on what's physically "painted" in the browser UI to determine what goes into the PDF.

I wonder if there might be a way to expose a method like waitForPaintIdle (or similarly named) on the Page object, which would allow the client to tap into whatever telemetry the browsers provide to wait for any queued/in-flight painting operations to complete. I am not steeped in browser internals and I accept that it may be that what I'm asking for is impractical or impossible.

**Comment by dgozman** [comment]
@rkennedy-mode There could be multiple reasons for things to be blank, so sharing a repro that we can play with would be very helpful.  See also #4055 for similar request with animations.

**Comment by rkennedy-mode** [comment]
> so sharing a repro that we can play with would be very helpful

Heh, yeah…capturing a repro that I can view would be similarly helpful. 😆 As mentioned above, we **believe** this is happening in response to a resize event. Add on top that this is happening in a production application, where we have multiple "captures" occurring simultaneously. So periodic load spikes on the machine by noisy neighbor browser instances could be exacerbating/triggering the problem. It's very difficult to catch it in the act locally, but we will continue trying.

We've been wanting to periodically [trace](https://playwright.dev/java/docs/api/class-tracing) our captures and have those traces available for subsequent debugging. We're currently awaiting an infrastructure change on our end to give us a place to store the traces where our developers can retrieve them later. If we were to generate a trace file for one of these, would that be sufficient for your needs?

**Comment by dgozman** [comment]
> If we were to generate a trace file for one of these, would that be sufficient for your needs?

That would be better than nothing, but I don't have high hopes.

**Comment by rkennedy-mode** [comment]
What would the perfect reproduction be? If I provided a Java file that could reproduce the problem 100% of the time, would that be it? JavaScript? Something other than Playwright-executing code?

**Comment by pavelfeldman** [comment]
> I wonder if there might be a way to expose a method like waitForPaintIdle (or similarly named) on the Page object, which would allow the client to tap into whatever telemetry the browsers provide to wait for any queued/in-flight painting operations to complete. I am not steeped in browser internals and I accept that it may be that what I'm asking for is impractical or impossible.

Even on the lowest level, figuring out when compositor picks up all the rasterization workers results is nearly impossible. The only way to achieve that would be comparing the actual raster (taking the consecutive screenshots). And in that case our implementation will be no better than yours in the user land. So I guess this falls out of scope for Playwright as a library.

**Comment by rkennedy-mode** [comment]
> The only way to achieve that would be comparing the actual raster (taking the consecutive screenshots). And in that case our implementation will be no better than yours in the user land.

Yeah, this is basically what I'm considering doing in our app. It's not going to be very accurate, however. Just because two screenshots are identical doesn't mean things are "done". It could just be that no progress was made in the time between screenshots.

I was hoping that maybe there was some rendering queue or similar inside of Chromium (or other browsers) that Playwright might have access to and be able to expose the state of that queue (e.g. "it's not empty…there are pending render tasks").

> So I guess this falls out of scope for Playwright as a library.

I figured that was the likeliest outcome, but I thought I'd ask.

**Comment by dgozman** [comment]
Closing as per above, since there is no action item.
