### ISSUE TITLE
[Question]: default quality for jpeg in screenshot method 

### ISSUE THREAD

**Issue by algot** [microsoft/playwright#22436]
### Your question

I use the screenshot method with the default quality parameter (I'm not specifying the parameter in the screenshot method call).

And I found out that the screenshots of the same pages are different in all different versions of Playwright. The difference is about 2 times.

I have a question - what is the default value of the quality parameter for the latest version of Playwright?

**Comment by dgozman** [comment]
@algot Looking at the source, the default value depends on the browser: 80 for Chromium, 50 for Webkit, 92 for Firefox. I don't think it changed over time, so the difference between Playwright versions is probably related to different browser versions included in Playwright itself.

**Comment by dgozman** [comment]
Let's default to 80 everywhere.
