### ISSUE TITLE
[BUG] Throwing unhandled rejection errors when Firefox navigates to neterr page

### ISSUE THREAD

**Issue by JoelEinbinder** [microsoft/playwright#2244]
Sometimes Firefox wants to navigate to an internal `aboutNetError.xhtml`. We have an assert than fails in this case, because the new documentId is empty string and doesn't match the pending document id.

**Comment by aslushnikov** [comment]
@joelEinbinder any chance you can add a test for this?

**Comment by pavelfeldman** [comment]
No reports from the users so far.
