### ISSUE TITLE
[Question]: Playwright cannot trigger the shortcut keys set by chrome extension settings through `keyboard.press`

### ISSUE THREAD

**Issue by wordhui** [microsoft/playwright#22447]
### Test situation
* Test two plug -ins, such as the Ctrl+Shift+K of the `omni`,Unable to trigger plug -in shortcut keys
   *  `page.keyboard.press("Control+ShiftLeft+K")`
   *  At the same time, the `Alt+ J` shortcut key of another plug-in cannot be triggered properly.
* Use `pyautogui` to open the extension normally
  * `pyautogui.hotkey('ctrl','shift', 'k')` 

### So I would like to ask if this belongs to the BUG or chromium restrictions?
*  chrome://extensions/shortcuts 

![image](https://user-images.githubusercontent.com/19604635/232657069-84f6ac35-2049-4ee2-acaa-7cb166e78d79.png)

### System info
- Playwright Version: `playwright==1.32.1`
- Operating System: Ubuntu 20
- Browser: Chromium
- Other info:

**Comment by dgozman** [comment]
@wordhui Playwright can only automate web content, but not the browser UI. If extension creates a shortcut for the browser UI functionality, it will not work. If you are trying to trigger the web content shortcut and it does not work, please file a new issue by filling in the "But report" template and providing a repro.
