### ISSUE TITLE
[BUG] In Macos , Safari app launch with executablePath timeout, but app already launched 

### ISSUE THREAD

**Issue by ssk512** [microsoft/playwright#22457]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS Monterey 12.5.1]
- Browser: [ WebKit]
- Node.js version: 16.16.0

Code Snippet

```

const {webkit} = require('playwright')

let browser = webkit.launch({headless: false, executablePath: '/Applications/Safari.app/Contents/Mac0s/Safari})
```

**Steps**
Please copy and paste the above and run the test

**Expected**

Should launch the safari browser without timeout

**Actual**

Launch safari browser with timeout

**Comment by dgozman** [comment]
Playwright does not launch pre-installed Safari browser, it works with a WebKit build. See [this guide](https://playwright.dev/docs/browsers#webkit) about supported browsers.
