### ISSUE TITLE
Not able to launch safari browser

### ISSUE THREAD

**Issue by ssk512** [microsoft/playwright#22452]
I trying to lunch safari browser with  executable path, not able to launch 

const {webkit} = require('playwright')

let browser = webkit.launch({headless: false,  executablePath: '/Applications/Safari.app/Contents/Mac0s/Safari})

**Comment by dgozman** [comment]
Playwright does not launch pre-installed Safari browser, it works with a WebKit build. See [this guide](https://playwright.dev/docs/browsers#webkit) about supported browsers.
