### ISSUE TITLE
[BUG] Locator.waitFor is leaking DOM nodes

### ISSUE THREAD

**Issue by dolezel** [microsoft/playwright#22458]
### System info
- Playwright Version: v1.31
- Operating System: Windows 11
- Browser: Edge/WebView2
- Other info: It is probably for all system and browsers, but checked only in this one

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (pseudocode)**

```js
it('should check element is not leaking', async ({ page }) => {
  await Promise.all([
    () => page.locator('//*[@id="should_not_leak'div"]').waitFor({ state: 'attached' }), 
    () => page.setContent(`<div id='should_not_leak'div></div>`) 
  ])
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

There is no detached div element at the end of the test

**Actual**

Playwright leaks element(s) found by locators, if there is `waitFor` called on them, due to internally used Handles and not disposing them.

**Comment by pavelfeldman** [comment]
This regressed in https://github.com/microsoft/playwright/pull/19715

**Comment by pavelfeldman** [comment]
@dolezel since this is a regression, let me land a proper fix instead. Appreciate the PR though!
