### ISSUE TITLE
[Feature] add option to webServer to show logs

### ISSUE THREAD

**Issue by kentcdodds** [microsoft/playwright#22454]
Continued from https://discord.com/channels/807756831384403968/1096822303653900368

Something like:

```ts
// ...
	webServer: {
		command: process.env.CI
			? `cross-env PORT=${PORT} npm run start:mocks`
			: `cross-env PORT=${PORT} npm run dev`,
		port: Number(PORT),
		reuseExistingServer: true,
		showLogs: true, // <-- that
	},
// ...
```

Using `DEBUG=pw:webserver` sorta works. For some reason it only logged the startup logs for my server, but didn't log anything after that. In any case, that environment variable is often overloaded for other things as well and it definitely falls short of the DX we've come to expect from Playwright.

**Comment by stdedos** [comment]
@mxschmitt Would you consider realtime-piping the output?

Waiting on a timeout of 60000ms is kinda sad.
(I am aware of the possible workarounds)

**Comment by mxschmitt** [comment]
> @mxschmitt Would you consider realtime-piping the output?
> 
> 
> 
> Waiting on a timeout of 60000ms is kinda sad.
> 
> (I am aware of the possible workarounds)

Yes please file a bug

**Comment by stdedos** [comment]
https://github.com/microsoft/playwright/issues/23313 ^^
