### ISSUE TITLE
[Question] WebKit 13.1+ Support

### ISSUE THREAD

**Issue by mangs** [microsoft/playwright#2245]
Hi,
Excited fan here. Is WebKit 13.1+ support planned? If so, is there a roadmap to follow? I don't see it mentioned in any issue or pull request. Thanks.

**Comment by pavelfeldman** [comment]
Using Safari terminology for WebKit is tricky, but we are literally on the tip of the tree of WebKit, so you are getting the latest WebKit possible. Playwright 1.0.2 is based on WebKit@a9043a6b, which is April 23rd. Tip of the tree Playwright is based on WebKit@eb65ecfa, which is May 7th.

**Comment by pavelfeldman** [comment]
Hang on,

**Comment by mangs** [comment]
Thank you!
