### ISSUE TITLE
[Feature] Missing API to get collection of the class attributes of the element.

### ISSUE THREAD

**Issue by doberkofler** [microsoft/playwright#22469]
The DOM provides the `classList` property to get a collection of the class attributes of the element.

Unfortunately Playwright does not have a dedicated API to get the `classList` and it must be manually implemented with something like this:

```
export const getClassList = (locator: Locator): Promise<string[]> =>
  locator.evaluate(el => [...el.classList]);
```

I guess, that a lot of Playwright users will have to implement this again and again  and think this would be a small but important addition.

**Comment by pavelfeldman** [comment]
I would probably use ```(await locator.getAttribute('class')).split(' ')``` instead.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by doberkofler** [comment]
Sorry to hear that this little feature request will not even be considered.
