### ISSUE TITLE
[BUG] serializedArgs.map is not a function when calling exposed function

### ISSUE THREAD

**Issue by eliassorensen** [microsoft/playwright#22460]
I have noticed on several websites, that exposed functions are not working. Below is a working example of this issue on one URL. If you need more URLs where this occurs, just comment and I'll provide.

### System info
- Playwright Version: Version 1.32.3
- Operating System: Tested on Ubuntu 22.04
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

```js
// repro.js
const { chromium } = require('playwright');

(async () => {
  function testInitScript(){
    if(window !== window.top) {
       return; // only run init script on root
    }

    setTimeout(function(){
        window.TestExposedFunction('This is a test');
    }, 2000);

  }
  const browser = await chromium.launch({ headless: false });
  const page = await browser.newPage();
  await page.exposeFunction("TestExposedFunction", (text) => console.log('TestExposedFunction', text));
  await page.addInitScript(testInitScript);

  await page.goto("https://essen.vienna.at/"); // ⬅️ This will cause an exception in the browser when calling the TestExposedFunction
  //await page.goto("https://www.google.com/"); // ⬅️ This will work just fine, and console.log the TestExposedFunction text

  await new Promise(resolve => setTimeout(resolve, 10000)); // Poor man's way of being able to wait a bit with the browser open
  
  await browser.close();
})();
```

**Steps**
- Run the repro.js (`node repro.js`) with each page.goto()

**Expected**

- Both URLs should give the same result (logging 'TestExposedFunction' with the text)

**Actual**

- essen.vienna.at does not console.log, but instead throw below exception:
![image](https://user-images.githubusercontent.com/1552175/232809385-36cfa090-9600-4293-8e96-a12cfd7196e1.png)

- google.com correctly outputs: `TestExposedFunction This is a test`

**Comment by dgozman** [comment]
`https://essen.vienna.at/` deletes the `Array.map` function. I'll see what we can do to workaround that.

**Comment by eliassorensen** [comment]
> `https://essen.vienna.at/` deletes the `Array.map` function. I'll see what we can do to workaround that.

Good catch, I didn't even think of that.

Looks like it's an old `prototype.js` version causing this, which makes it clear why I'm seeing this issue on multiple sites.

Is it fixable on your end to not rely directly on it (and being prone to websites overriding it)?
