### ISSUE TITLE
[BUG] Remote Debugging with Screencast breaks actions

### ISSUE THREAD

**Issue by kolodny** [microsoft/playwright#22464]
### System info
- Playwright Version: 1.32.3
- Operating System: Mac
- Browser: Chromium
- Other info:

It seems that having a screencasted chrome instance of a remote debugging process breaks all actions on the page. In the example below you can change the `FIXED` variable to `true` which will disable screencasting on the remote page and the script will run successfully.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**index.js**

```js
const playwright = require('playwright');

const FIXED = false;
const PORT = 9299;
const REMOTE = `http://localhost:${PORT}`;

(async () => {
  const browser = await playwright.chromium.launch({
    // headless: false,
    args: [
      `--remote-debugging-port=${PORT}`,
      `--remote-allow-origins=${REMOTE}`,
    ],
  });
  const page = await browser.newPage();
  await page.goto(`${REMOTE}/json`);
  const list = await page.evaluate(() => JSON.parse(document.body.innerText));

  const debugPage = await browser.newPage();
  await debugPage.goto(`${REMOTE}${list[0].devtoolsFrontendUrl}`);
  await debugPage.locator('canvas').waitFor();
  if (FIXED) {
    await debugPage.getByTitle('Toggle screencast').click();
  }

  await page.locator('body').click({ timeout: 3000 });
  await browser.close();
  console.log('done');
})();

```

**Steps**
- Run `node index.js`

**Expected**
The script should run to completion

**Actual**

The script errors with

```
locator.click: Timeout 3000ms exceeded.
=========================== logs ===========================
waiting for locator('body')
  locator resolved to <body>…</body>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
```

This happens in headless and headful chrome, I suspect that playwright isn't sharing the debug websocket correctly. Note that you can open multiple debug pages on the same page and there's no issue. For example the same `${REMOTE}${list[0].devtoolsFrontendUrl}` url can be opened in multiple tabs/windows and the casting and debugging still works as expected. It's only Playwright actions (such as `.click()` in the snippet above) that appear to break

**Comment by dgozman** [comment]
@kolodny This is because enabling screencast in DevTools also enables emulating touch events in the page, and this makes mouse events sent by Playwright to never be processed. I don't think we should do anything about this issue. Let me know what you think.

**Comment by kolodny** [comment]
Hmm, is there any way to disable emulating touch events? It would be nice to be able to see what's happening on the page without the script completely breaking

**Comment by kolodny** [comment]
@dgozman, if you run the snippet above you'll see that the link is clicked, I think it's just playwright that doesn't realized that the click event was successful. You can change uncomment the `headless: false` line to see it in action

**Comment by kolodny** [comment]
Understood, thanks for the quick response and explanation
