### ISSUE TITLE
[BUG] Playwright browser instance clicking behaves differently to Chrome's own instance of a web app running.  

### ISSUE THREAD

**Issue by ATARARHRB** [microsoft/playwright#22463]
**Context:**
- Playwright Version: 1.30.0
- Operating System: Microsoft Windows 11 Pro 10.0.22621 Build 22621
- Node.js version: v17.0.1
- Visual Studio Code version: 1.77.3
- Playwright for VSCode extension version: v1.0.10
- Browser: Chromium
- Extra: 

**Code Snippet**

N/A

**Describe the bug**

Locally when I click between two elements on a web app I am running it is able to click between the two without any issue. However, on Playwright's instance of the browser ("Show Browser" checked and then just playing around in the instance by hand -- not programmatically) a context menu being on top of another element causes it to behave erratically. 

In the first video attached you can see clicking between two elements causes the context menu to pop up without any issue between the two

https://user-images.githubusercontent.com/131192142/232855258-77265331-1d7c-4930-85d4-df751424b744.mp4

In the second video, however, you can see erratic behaviour begin when the same clicking is done. 

https://user-images.githubusercontent.com/131192142/232855455-7e42f479-9c6c-45af-accb-61844b4778a6.mp4

I guess my question is, what is different about the setups and the way content is loaded between the live chromium instance and the independent instance that playwright opens besides not having access to local data such as cookies? It might narrow down why it is behaving differently as I would always expect playwright to at minimum reflect the same behaviour that the browser does on its own.

**Comment by dgozman** [comment]
@ATARARHRB This looks like a relayout, maybe caused by the Playwright's pink highlight. You could try with `npx playwright codegen` on that same site, to see whether it's the codegen functionality or the "Show Browser" feature. However, without a repro it's unlikely we'll be able to fix the issue.

**Comment by ATARARHRB** [comment]
It happens in codegen too, so I don't think it is "Show Browser" specific 

https://user-images.githubusercontent.com/131192142/232877111-aae9a3c5-035c-4005-b716-fc71ba0bb37c.mp4

Clicking on this button that otherwise (vanilla chrome) clicks without issue causes the browser to spasm in codegen. 

https://user-images.githubusercontent.com/131192142/232877666-0ae001cb-56c3-4846-bc1f-2f6c15715b53.mp4

However, one thing I'll note from the 2nd video above is that it does seem to depend on the size of the element it is working with, on the 'shorter' elements (these are made with a combination of svg and divs -- only divs for the shorter one -- taller pieces have svg components rendered) it clicks every time without any issue, the taller ones cause it to spasm, so it is definitely caused in part by the height of the elements we are rendering combined with the pink highlight. Is there any way to run it without the pink highlight that maybe I can test out?

**Comment by dgozman** [comment]
> Is there any way to run it without the pink highlight that maybe I can test out?

No such way, sorry. There must be something specific about your CSS that triggers this behavior. If you could share a repro (maybe save a DOM snapshot), that would be very helpful.

**Comment by ATARARHRB** [comment]
I don't think I have enough detail to reproduce this on your end yet, I'm going to close it out and if I find a better way to reproduce the behaviour I'll reopen the issue. I've added other attributes to get around it for now so I will investigate and hopefully return with more conclusive details.
