### ISSUE TITLE
[Feature] Be able to execute some login in CustomReporter after suite

### ISSUE THREAD

**Issue by anastasiia-petrenko** [microsoft/playwright#22479]
Version: 1.30

I have a use case: tests are organized in spec files and Azure DevOps Test Runs are used for reporting.

In order to have immediate feedback from the test runner and reduce the risk of result absence (if something happens during execution), I want to generate JUnit reports after each spec file, which then I can save in separate storage for further use.

Initial idea is to create a custom reporter that would also include the logic of sending generated reports to a 3rd-part place

According to the current implementation, the Reporter has only methods onEnd (after all tests) or onTestEnd (after each test). It would be great to have a method that is executed on the suite/file end.

`Suite` interface has the following structure: [https://playwright.dev/docs/api/class-suite](https://playwright.dev/docs/api/class-suite) and seems to track the file suite. I saw that something has been implemented in older versions and then were deprecated.

The case is closely related to another Feature request https://github.com/microsoft/playwright/issues/22478

**Comment by dgozman** [comment]
@anastasiia-petrenko You can run something at the end of the suite from `onTestEnd`:

```js
onTestEnd(test) {
  const suite = test.parent;
  const tests = suite.allTests();
  const allTestsFinished = tests.every(t => t.results.length > 0);
  if (allTestsFinished) {
    // handle suite finish
  }
}
```

Let me know if that helps.

**Comment by anastasiia-petrenko** [comment]
@dgozman thank you very much for this tip. This seems to work for me. No further assistance is needed
