### ISSUE TITLE
[BUG] In webkit fake media works default and not connecting with microphone and camera

### ISSUE THREAD

**Issue by ssk512** [microsoft/playwright#22477]
### System info

    Playwright Version: [v1.32]
    Operating System: [macOS Monterey 12.5.1]
    Browser: [ WebKit]
    Node.js version: 16.16.0

Code Snippet

```
const {webkit} = require('playwright')

let browser = webkit.launch({headless: false})
```
Steps:

Please copy and paste the above and run the test

**Expected**

It should show real media(microphone and video)

**Actual**

shows fake media

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please fill in the "Bug report" template and provide a repro that we can run locally? Please also be more descriptive in your expectations.
