### ISSUE TITLE
Quick selection of a new reference screenshot

### ISSUE THREAD

**Issue by ivanqa2022** [microsoft/playwright#22489]
We have huge volumes of runs in visual comparison. We often face the problem that it is necessary to assign a new screenshot as a reference. It will be very convenient to have a button in the report for reassigning a screenshot.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/116289351/233119333-2144dc98-0668-4fac-840f-10f8bae5a817.png">

**Comment by dgozman** [comment]
Duplicate of #14883.
