### ISSUE TITLE
Separating page actions and locators in different classes for POM implementation.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#22487]
This [link](https://playwright.dev/docs/pom#implementation) talks about POM implementation where both page locator and method/action definitions are in the same class. Is it better to have methods defined in a separate class instead which can make use of multiple POMs (contains only locator definitions) and tests can call those methods? POMs can grow overtime with new locator and/or method definitions. Or, the flow for the POM method could change for eg: a new pop up was introduced when clicking on login button. Now all tests (could be 100 or 1000s) calling the login method from login POM need to handle that popup or the login POM needs to have a reference to that pop up POM.

**Comment by quldude** [comment]
We have some folks thinking what's defined in that link for POMs is the right and only way. So wanted to see what your thoughts were to be more flexible.

**Comment by dgozman** [comment]
Thank you for the issue! Closing.
