### ISSUE TITLE
Selenium GRID in distributed mode vs Playwright

### ISSUE THREAD

**Issue by LubikR** [microsoft/playwright#22488]
I have deployed Selenium GRID in distributed mode about two years ago. Actually on version 4.8.3. Selenium server runs on swarm manager node on IP 10.42.132.147. About 40 chrome browsers, 10 firefox browsers runs on worker nodes. I have created "Selenium network" on overlay driver, so Selenium server sees all selenium nodes on workers trhrough this network. Workres have internal IPs from range192.168.2.0/24.

If I run test from local I got:

 Error: browserType.launch: WebSocket error: connect ECONNREFUSED 192.168.2.4:4444
    =========================== logs ===========================
    <selenium> connecting to http://10.42.132.147:14444/
    <selenium> connected to sessionId=c6d499f68bad442b5c3a7e7b86a3732b
    <selenium> using selenium v4
    <selenium> retrieved endpoint ws://192.168.2.4:4444/session/c6d499f68bad442b5c3a7e7b86a3732b/se/cdp for sessionId=c6d499f68bad442b5c3a7e7b86a3732b
    <ws connecting> ws://192.168.2.4:4444/session/c6d499f68bad442b5c3a7e7b86a3732b/se/cdp
    <ws error> ws://192.168.2.4:4444/session/c6d499f68bad442b5c3a7e7b86a3732b/se/cdp error connect ECONNREFUSED 192.168.2.4:4444
    <ws connect error> ws://192.168.2.4:4444/session/c6d499f68bad442b5c3a7e7b86a3732b/se/cdp connect ECONNREFUSED 192.168.2.4:4444
    <ws disconnected> ws://192.168.2.4:4444/session/c6d499f68bad442b5c3a7e7b86a3732b/se/cdp code=1006 reason=
    <selenium> disconnecting from sessionId=c6d499f68bad442b5c3a7e7b86a3732b
    <selenium> disconnected from sessionId=c6d499f68bad442b5c3a7e7b86a3732b

It seems that playwright got internal IP from selenium sever and try to connect to browser ip 192.168.2.4, but this address is not reachable, it is internal "docker" ip. 

We have about 200 tests in Java vs Grid and Java always calls server IP. The question is why playwright calls internal IP (according to my understanding of the log)

**Comment by dgozman** [comment]
Perhaps you need to configure Selenium so that it advertises nodes with the right IP. We recommend setting `SE_NODE_GRID_URL` to make sure the right address is used. Take a look at #11692 for discussion, and also at [this guide](https://playwright.dev/docs/selenium-grid#hub-and-nodes-mode).

**Comment by LubikR** [comment]
Thanks for advice. Yes, if I set the **SE_NODE_GRID_URL** variable correctly, the error disappears, but the test ends with the open "empty" browser and nothing else happens, i.e. behaviour is the same as described in #11692

**Comment by dgozman** [comment]
@LubikR Perhaps you are hitting #18892 now, take a look at the discussion there. [This comment](https://github.com/microsoft/playwright/issues/18892#issuecomment-1435486455) seems to have a workaround for now. Let me know if that helps.

**Comment by LubikR** [comment]
Set JAVA_OPTS=-Djdk.httpclient.websocket.intermediateBufferSize=3000000 helped and the playwright tests are now working in GRID. Thank you for your help! At first glance, I am very surprised by the speed of execution of our tests in GRID. I expected a slowdown in the test execution, but it seems to be very small. We will do more tests. This issue should be closed.
