### ISSUE TITLE
Running tests in parallel and updating a variable 

### ISSUE THREAD

**Issue by mshre001** [microsoft/playwright#22497]
Hello,
I had a question but wasn't sure if this is the right place - 
I have a test in a for loop that runs about 200 tests  in parallel - after each test run I would like to push the UI values that I see into an array.  I am adding that step in an afterEach hook . This seems to work fine when the tests run in a single worker but when there's multiple workers running in parallel, they seem to overwrite each others data and I am not able to figure out how I can set it up so that the tests can run in parallel mode at the same time retain all the ui Values in an array. 
Hope my question makes sense, appreciate any help! Thanks,
below is what my spec structure looks like

const data = <data I'm using for test> 
  test.describe(``, async () => {
    let arr = []
    for (let item of data) {
      test.afterEach(async ({}) => {
        arr.push(await uiValue)
      })
      test(``, async () => {
   test code here, save uiValue here
      })
    }
  })

**Comment by dgozman** [comment]
@mshre001 Since parallel tests are running in completely separate OS processes, there is no way to put values in the same array.

I'd recommend writing every value to a separate file at well-known location, and then collecting values from these files in `globalTeardown`.

**Comment by dgozman** [comment]
Alternatively, let each test [add an annotation](https://playwright.dev/docs/test-annotations#custom-annotations) and post-process them in a [custom reporter](https://playwright.dev/docs/test-reporters#custom-reporters).

**Comment by mshre001** [comment]
I see, got it thanks for your help! I will try the separate file method you suggested.
