### ISSUE TITLE
[QUESTION] How to wait for enabled ?

### ISSUE THREAD

**Issue by yogeshgadge** [microsoft/playwright#22507]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]

I am coming over to this project from webdriverio to evaluate this.

In Selenium and webdriverio  we would just call waitForEnabled() or waitForEnabled({ reverse: true }) but I see only 
```
waitFor("attached"|"detached"|"visible"|"hidden")
```

I see that isEnabled has timeout option but that does not work for me to really know when it will be.  Is there a polling or something that we can tap into and if so how would one go about ?

**Comment by ltsuda** [comment]
Playwright recommends using Web First Assertions instead of `waitFor`, please see if the following helps:

https://playwright.dev/docs/best-practices#use-web-first-assertions
https://playwright.dev/docs/test-assertions

**Comment by dgozman** [comment]
To expand on @ltsuda's comment:

```js
await expect(page.getByRole('button')).toBeEnabled();
```
