### ISSUE TITLE
[Feature] Locator for type attribute

### ISSUE THREAD

**Issue by sarink** [microsoft/playwright#22502]
When filling out forms, Playwright seems to be nudging users in the direction of `getByRole('button', { hasText: 'Submit' })`, which is good, and definitely useful. But more often, when automating filling out forms, I find myself writing `waitForSelector('button[type="submit"]')`, because sometimes the button text changes (maybe it's even dynamic), but its type never does (and generally we want to ensure the button to submit the form is actually of type=submit anyway).

First-class support for something like this would be really convenient. Perhaps, add `type` to the `getByRole` options? eg, `getByRole('button', { type: 'submit' })` ?

Thanks!

**Comment by dgozman** [comment]
@sarink `type` is not defined in ARIA spec, so adding it to `getByRole` would be confusing. Also, not every element with `button` role is a native html button, so they might not have `type` at all.

If you think that using `type` is better for your tests, `page.locator('button[type=submit]')` is a great locator. Not sure it's worth a separate method though. Let me know what you think.
