### ISSUE TITLE
[QUESTION] Where the information is stored during the work inside UI-Mode

### ISSUE THREAD

**Issue by AlexKomanov** [microsoft/playwright#22516]
Hi all,

UI-Mode includes the trace inside it.

Trace files have some weight due to stored snapshots and other provided information.

So the question is:
How does it work inside the UI-Mode? Where the information is stored during the work inside UI-Mode? Does it require some additional space to a work with it?

**Comment by dgozman** [comment]
Traces are stored in the [`outputDir` directory](https://playwright.dev/docs/api/class-testproject#test-project-output-dir), which is `test-results` by default.

There should be negligible overhead compared to just running `npx playwright test` without ui mode - mostly related to showing the UI window.

**Comment by dgozman** [comment]
Closing as per above. If you have more questions, please file a new issue and link to this one.
