### ISSUE TITLE
[BUG] Traceviewer: Open snapshot in new tab --> 404

### ISSUE THREAD

**Issue by LisBerndt** [microsoft/playwright#22515]
### System info
- Playwright Version: v1.31
- Operating System: Windows 11
- Other info:

Opening snapshot in new tab gives 
![image](https://user-images.githubusercontent.com/43057926/233270799-b925e24f-e45f-4232-8799-d53d17e531f5.png)

**Comment by dgozman** [comment]
@LisBerndt Could you please share your `trace.zip` file? How do you open the trace: from html reporter, cli tool, ui mode, etc? Perhaps you hit Ctrl+C in your terminal before opening a snapshot? Not sure how to help without a repro.

**Comment by LisBerndt** [comment]
> @LisBerndt Could you please share your `trace.zip` file? How do you open the trace: from html reporter, cli tool, ui mode, etc? Perhaps you hit Ctrl+C in your terminal before opening a snapshot? Not sure how to help without a repro.

I would not like to publish the trace due to business policy.  

I can tell that the trace is opened by the html reporter which is executed after running the npx test command by cmd in headless mode.

If this info is not sufficient I'll try to reproduce it by my self by testing a public site and share that trace.

**Comment by dgozman** [comment]
> If this info is not sufficient I'll try to reproduce it by my self by testing a public site and share that trace.

Having a repro would be great! I think the problem is either:
- in the trace viewer that serves on localhost - for this we need exact instructions on what specific commands do you run and what happens;
- or in your local setup where something strange happens to the server - in this case we won't be able to help unfortunately.
