### ISSUE TITLE
[BUG?] Data fixture destroyed unexpectedly  

### ISSUE THREAD

**Issue by alex-vungle** [microsoft/playwright#22518]
Hi All, 

I have a data fixture, this fixture targets to be reused in different tests so that I don't need to recreate it for each test. I initialized this fixture in test.beforeAll(), however, when the playwright runs the second test, it always fails for missing test data, and I finally found out that the Playwright test runner destroys the data fixture unexpectedly once it finishes the first test case. I am not sure if this is a bug or not because I assume the data fixture appStoreInfo should be teared down after running all test cases, but actual behavior is it's destroyed after each test. 

Pls help look into it and correct me if I am using it incorrectly, thanks! 

BTW, in my test code, in test.beforeAll(), I also created a page fixture, the page fixture can be shared in each tests, only the data fixture can't be shared and destroyed immediately after each test.

### System info
- Playwright Version: v1.31.1
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

```js
// fixtures.ts
......
  testAppData: async ({ appName, appPlatform, appStoreInfo, }, use) => {
    if (appName === undefined) {
      appName = `app-${randomString(7)}`;
    }
    const appData = await createApplication(appName, appPlatform, true, appStoreInfo);
    const appId = appData['id'];

    await use(appData);

    await dal.collections.applications.deleteMany({ "_id": new ObjectId(appId) });
  },
......

```

**Test file (self-contained)**

```js
test.describe('XXXXXXXXX', () => {

    let appUpdatePage: AppUpdatePage;
    let appId: string;

    test.use({ appName: "OpenAI", appPlatform: Platform.iOS, appStoreInfo: { "id": "644594434", "category": "Productivity" } })

    test.beforeAll(async ({ page, testAppData }) => {
        appId = testAppData["id"];
        appUpdatePage = new AppUpdatePage(page);
        await appUpdatePage.load(appId)
    });

    test("Update XXXX", async () => {
        const appName: string = "OpenAI Pro";
        await appUpdatePage.setAppName(appName);
        await appUpdatePage.clickSaveButton();

        //UI Verification
        await appUpdatePage.verifyNotfication("App Settings Saved");
 });


    test("Update XXX", async () => {

        await appUpdatePage.setAppStatus(AppStatus.Inactive);
        await appUpdatePage.verifyModalWindowPresent("Switching App Mode");

        await appUpdatePage.clickModalButton("OK");

        await appUpdatePage.clickSaveButton();

        //UI Verification
        await appUpdatePage.verifyNotfication("App Settings Saved");
    });
```

**Comment by dgozman** [comment]
>  test runner destroys the data fixture unexpectedly once it finishes the first test case

This is expected, because `testAppData` is declared as a test-scoped fixture, and will be teared down after the test. If you'd like to reuse some data between tests, you probably need a [worker-scoped fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures).

>  in test.beforeAll(), I also created a page fixture, the page fixture can be shared in each tests

Hmm... Built-in `page` fixture is not allowed in the `beforeAll` and should throw an error. Are you overriding it yourself? Also note that `page` fixture is test-scoped, so it will be similarly teared down between tests, and initialized again for the second test if it uses `page`.

**Comment by alex-vungle** [comment]
Hi @dgozman , thanks for your quick reply on this, I have changed my test fixture **testAppData** to worker-scoped fixture, it works, but as you see, in my fixture **testAppData**, I add some other fixtures which act as parameters, by doing this, I can provide different arguments to make the fixture configurable, currently, if I use worker-scope fixture, when I run the test, I will a few errors like below:

`worker fixture "testAppData" cannot depend on a test fixture "appName" defined in tests/selfserve/apps/create/create.apps.spec.ts:146:10.

   at ../fixtures.ts:24
`
Do you know how I can change those test fixtures like "appName" to worker level? I know turning the fixture **testAppData** into a function can solve the problem.

BTW, in terms of the page fixture, as you doubt, I override the default one. 😊

**Comment by dgozman** [comment]
> Do you know how I can change those test fixtures like "appName" to worker level?

It's the same syntax, pass `scope: 'worker'` when defining it. However, if you make it worker-scoped, you can only `test.use()` it on the top-level, not inside any `describe`, because it must be the same for the whole worker.

**Comment by alex-vungle** [comment]
Sorry, I'm a newbie to Typescript and Playwright, could you pls give me an sample on how to pass **scope: 'worker'** to the 
"appName" fixture which is defined in a string type? 

I went through the doc but only see how to specify worker-scoped fixture on an arrow function.

**Comment by dgozman** [comment]
@alex-vungle Something like this. Take a look at [fixture options](https://playwright.dev/docs/test-fixtures#fixtures-options) as well - you can specify those in the config in addition to `test.use()`.

```ts
const test = base.extend({
  appName: ['default app', { option: true, scope: 'worker' }],
});
```

**Comment by aidenstern** [comment]
Sorry to revive an old thread. This works for my use case and runs, but I get some TS errors. I understand it to mean I shouldn't be able to assign a fixture option to have a worker scope, only test scope.

![Screenshot 2024-03-20 at 1 48 45 PM](https://github.com/microsoft/playwright/assets/54781286/9b2a19d2-6305-4e22-bd0b-5787478acc99)

Here is the full code:

```ts
import { Page, test as base, expect } from '@playwright/test';

const test = base.extend<{
    defaultItem: string,
    testFixture: Page,
    workerFixture: Page,
}>({
  defaultItem: ['Something nice', { option: true, scope: 'worker' }],
  workerFixture: [async ({ browser, defaultItem }, use) => {
    // workerFixture setup...
    console.log("before use workerFixture");
    console.log("fixtureOption: " + defaultItem);
    await use(await browser.newPage());
    console.log("after use workerFixture");
    // workerFixture teardown...
  }, { scope: 'worker' }],
  testFixture: [async ({ workerFixture }, use) => {
    // testFixture setup...
    console.log("before use testFixture");
    await use(workerFixture);
    console.log("after use testFixture");
    // testFixture teardown...
  }, { scope: 'test' }],
});

export { test, expect };
```

Like I said it still runs and works great for my use case but wasn't sure if this typing is intended or not or if maybe I'm doing something wrong
