### ISSUE TITLE
[Feature] Playwright-cucumber-preprocessor

### ISSUE THREAD

**Issue by igorkiselev93** [microsoft/playwright#22521]
Currently it's problematic to use Cucumber with Playwright because:
1) you can't use --ui mode
2) you can't use Selenium grid for parallelization
3) etc...

For example Cypress has plugin for that (see https://github.com/badeball/cypress-cucumber-preprocessor).
Cucumber is very popular BDD framework and I see many questions regarding Cucumber with Playwright (example of question https://stackoverflow.com/questions/76035903/using-playwright-ui-mode-with-cucumber)

So maybe it's possible to have similar plugin to use Cucumber js + Playwright js

**Comment by ltsuda** [comment]
Currently, there is this issue collecting feedback.

https://github.com/microsoft/playwright/issues/11975

And from there, exists 2 community projects that allows BDD with Playwright:

https://github.com/Tallyb/cucumber-playwright
https://github.com/vitalets/playwright-bdd

**Comment by igorkiselev93** [comment]
Closed as duplicate of https://github.com/microsoft/playwright/issues/11975
