### ISSUE TITLE
[BUG]Error while downloading firefox .

### ISSUE THREAD

**Issue by anandhakrishnanr** [microsoft/playwright#22546]
It is successfully downloading the rest of all browser such as chromium .Using executable path/ blocking the auto download also works since the browser has already got downloaded in cdrive. When it comes to execution in remote VMs , the auto download happens and fails while downloading firefox.

Downloading Chromium 112.0.5615.29 (playwright build v1055) from https://playwright.azureedge.net/builds/chromium/1055/chromium-win64.zip
|                                                                                |   0% of 113 Mb
|■■■■■■■■                                                                        |  10% of 113 Mb
|■■■■■■■■■■■■■■■■                                                                |  20% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 113 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 113 Mb
Chromium 112.0.5615.29 (playwright build v1055) downloaded to C:\Users\A0842231\AppData\Local\ms-playwright\chromium-1055
Downloading FFMPEG playwright build v1008 from https://playwright.azureedge.net/builds/ffmpeg/1008/ffmpeg-win64.zip
|                                                                                |   0% of 1.4 Mb
|■■■■■■■■                                                                        |  10% of 1.4 Mb
|■■■■■■■■■■■■■■■■                                                                |  20% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 1.4 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 1.4 Mb
FFMPEG playwright build v1008 downloaded to C:\Users\A0842231\AppData\Local\ms-playwright\ffmpeg-1008
Downloading Firefox 111.0 (playwright build v1391) from https://playwright.azureedge.net/builds/firefox/1391/firefox-win64.zip
|                                                                                |   0% of 79.7 Mb
|■■■■■■■■                                                                        |  10% of 79.7 Mb
|■■■■■■■■■■■■■■■■                                                                |  20% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 79.7 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 79.7 Mb
Error: read ECONNRESET
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
  errno: -4077,
  code: 'ECONNRESET',
  syscall: 'read'
}

Even If I try downloading manually from https://playwright.azureedge.net/builds/firefox/1391/firefox-win64.zip, it fails to download the complete file

Please help me out on this.

**Comment by dgozman** [comment]
@anandhakrishnanr Everything works from our side. Perhaps there was an intermittent network issue on your end?

**Comment by dgozman** [comment]
Closing as per above.

**Comment by anandhakrishnanr** [comment]
Yeah after adding the proxy ,it works
thanks @dgozman
