### ISSUE TITLE
[BUG] Running multiple Electron tests fails

### ISSUE THREAD

**Issue by IhsenBouallegue** [microsoft/playwright#22557]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

I used a template with electron, vite and playwright set up. Running one test passes no problems, but running multiple ones fails with this error ` Error: electron.launch: Process failed to launch!`. I prepared a simple repo which has the same test duplicated. 
Here is a test snippet:
```js
import { test, expect, _electron as electron } from "@playwright/test";

test("homepage has title and links to intro page", async () => {
  const app = await electron.launch({ args: [".", "--no-sandbox"] });
  const page = await app.firstWindow();
  expect(await page.title()).toBe("Electron + Vite + React");
  await page.screenshot({ path: "e2e/screenshots/example.png" });
  await app.close();
});
```
**Link to the GitHub repository with the repro**
https://github.com/IhsenBouallegue/electron-pw

**Steps**
- yarn install
- yarn e2e

**Expected**

All tests run and pass

**Actual**

A test is failing because of electron.launch()

**Comment by aslushnikov** [comment]
@IhsenBouallegue it looks like your application is written in such a way that two instances cannot be launched simultaneously.

Try running `npx electron .` in one terminal, and then follow with another `npx electron .` in the other and observe the application to instantly close.

So works as expected!

**Comment by cc-julmer** [comment]
I am having this same issue. I can only run the first test and the second fails unless i wait a while between tests. I keep finding threads like these with this question and they are always closed before a real answer is given.
