### ISSUE TITLE
[Feature] Do not fail test run if snapshot doesn't exist

### ISSUE THREAD

**Issue by kostaskriaridis** [microsoft/playwright#22553]
Hello, dear Playwright contributors, thanks for an amazing tool.

### Current behaviour
Let's imagine basic flow of writing tests for developer
* Create component
* Write tests
* Run tests
* Test fails with an error:
```
Error: A snapshot doesn't exist at <PATH>, writing actual.
```
* That means that developer should run the test at least 2 times to be sure that everything passes

### Expected behaviour
* Test should not fail, it should pass and new snapshot should be created

### Feature request
Is it possible to add a special flag like `--fail-on-snapshot-absence` which defaults to `true` ?

**Comment by dgozman** [comment]
@kostaskriaridis You can run with `--update-snapshots` flag to force-update and force-pass.

That said, if the only error is the missing snapshot, you don't have to rerun the test again - it will definitely pass.

**Comment by kostaskriaridis** [comment]
@dgozman, thank you so much for your response 🙏 
We can close the issue now :-)
