### ISSUE TITLE
[BUG] Devtools taking screenshot closes browser

### ISSUE THREAD

**Issue by surfmuggle** [microsoft/playwright#22551]
### System info
- Playwright Version: [v 1.31.2]
- Operating System: [Microsoft Windows 10 Enterprise Version	10.0.19042 Build 19042]
- Browser: [Playwright codegen]
- Other info:
If i take a screenshot with the devtools playwright is closed after the screenshot.

### Steps to reproduce

1. in `cmd.exe` enter `npx playwright codegen https://playwright.dev/docs/debug-selectors#using-devtools`
2. on `https://playwright.dev/docs/debug-selectors` change the theme to dark by manually clicking one of the buttons  `document.querySelectorAll("button.toggleButton_gllP")` 
3. open the devtools of the browser
4. To run a command either press <kbd>CTRL+SHIFT+P</kbd> or click the three bullets
5. Type `screenshot` in the run input field and select `Capture full size screenshot`
6. Expected Result: screenshot is taken, stored and playwright stays open
7. Actual Result: playwright is closed, possibly the screenshot is not stored

### Screenshots of step 4 and 5 

<img width="1280" alt="Playwright_take_screenshot_devtools_01" src="https://user-images.githubusercontent.com/1271555/233570752-96b44076-2e0d-45ba-9d4f-6e1ef51f4ea3.png">
<img width="1269" alt="Playwright_take_screenshot_devtools_02" src="https://user-images.githubusercontent.com/1271555/233570768-ac3a2953-475e-4402-be3a-9174d49cb85e.png">

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by dgozman** [comment]
I can repro. Console shows this error:
```
<path>/playwright/packages/playwright-core/lib/utils/debug.js:29
  if (!value) throw new Error(message || 'Assertion error');
                    ^

Error: Download started in unknown page: {"frameId":"866230B92E5D8BEA1E30AEA76378C567","guid":"68c39f69-0a45-4c80-96c1-80ca175e3986","url":"blob:devtools://devtools/c2fe8358-1456-4478-905a-cf8ae4171221","suggestedFilename":"playwright.dev_docs_debug.png"}
    at assert (<path>/playwright/packages/playwright-core/src/utils/debug.ts:21:11)
    at CRBrowser._onDownloadWillBegin (<path>/playwright/packages/playwright-core/src/server/chromium/crBrowser.ts:246:11)
    at CRSession.emit (node:events:513:28)
    at <path>/playwright/packages/playwright-core/src/server/chromium/crConnection.ts:200:14
```
