### ISSUE TITLE
[Feature] Allow parallel execution of multiple instances of the same test file (Playwright Test)

### ISSUE THREAD

**Issue by klhex** [microsoft/playwright#22550]
We are using Playwright Test also for doing some rather simple load testing by making Playwright execute in parallel the same content of a test file multiple times (e.g. several thousand times). The test file contains an e2e test (typical customer journey in our application), i.e. that the tests inside the test file are executed serially.

Currently, I need to create several thousand copies of the concerned test file (each with a slightly different file name) and then let Playwright execute all of them in parallel. This creates needless I/O overhead because obviously Playwright needs to load several thousand files from the file system. Also, having several thousand test files in your git repo kind of cloaks it.

Therefore, for such scenarios, it would be great if there was an option in Playwright Test that would allow us to make PW Test load and execute in parallel <x> instances of the same physical test file.

**Comment by MindaugasMateika** [comment]
Perhaps configuration like `npx playwright test --repeat-each 2 --workers 2` would work for you? It will repeat same test in parallel.

**Comment by imartinflores** [comment]
Not sure if I am understanding correctly, but the above solution should work or also if you wrap the tests in that file in a loop and has the fullyParallel option set to true.

**Comment by dgozman** [comment]
A [loop inside the test file](https://playwright.dev/docs/test-parameterize#parameterized-tests) that declares your tests 1000 times, along with a parallel mode should work:

```js
test.describe.configure({ mode: 'parallel' });
for (let i = 0; i < 1000; i++) {
  test.describe('suite ' + i, () => {
    test.describe.configure({ mode: 'serial' });
    test('load test 1', async () => {});
    test('load test 2', async () => {});
  });
}
```

**Comment by klhex** [comment]
@dgozman Didn't get around testing your suggestion until now. Result: It works wonderfully well -- many, many thanks for that one! 🎉 👍
