### ISSUE TITLE
[Feature] Define 'After' hook for particular test.

### ISSUE THREAD

**Issue by forelock7** [microsoft/playwright#22559]
Is it possible to define 'After' hook for particular test in test suite.
It's needed when each test have different bunch of functions that should be executed after test

**Comment by dgozman** [comment]
@forelock7 Why don't you just put that code inside the test itself?

Alternatively, wrap that single test in a describe:

```js
test.describe(() => {
  test.afterEach(async () => {
    // ...
  });
  test('a special test that needs the hook', async () => {
  });
});
```

**Comment by forelock7** [comment]
> 

1. If I put that code inside the test, it isn't executed in case test fails.
2. A lot of wrappers... It's not readable. Especially when we gonna have thousands of tests

**Comment by forelock7** [comment]
Use case:
1. Test can create different types of assents. Assents are related and unrelated to each other (more than 20)
2. Assets could be created by different users with different roles (6 roles + possibility of isolated tenants inside one system)
3. Some configuration of system can be changed during the test (hundreds of features)
So it's hard to do one after hook for all cases.

**Comment by forelock7** [comment]
@dgozman Thanks. I'll try the last one.
