### ISSUE TITLE
setGeolocation doesn't seem to change the location as seen from the internet

### ISSUE THREAD

**Issue by tdehollain** [microsoft/playwright#22554]
Don't know if I'm doing something wrong, but running the following code on [https://try.playwright.tech/](https://try.playwright.tech/) shows the location is not London as it should be, but a place in Virginia (I guess that's where the app runs from).

```js
const playwright = require('playwright');
(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext({
    geolocation: { longitude: 51.5072, latitude: -0.118092},
    permissions: ['geolocation']
  });
  const page = await context.newPage();
  await page.goto('https://mylocation.org/');
  await page.screenshot({ path: 'example.png' });
  await browser.close();
})();
```

**Comment by mxschmitt** [comment]
This is because Playwright emulates the [Geolocation API](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API) and not the IP address.

**Comment by DanielStoica85** [comment]
That's not great. Any chance of adding an "emulate IP address" feature?

**Comment by mxschmitt** [comment]
IP address can only be emulated on the network level - so you'd have to use a proxy or VPN for that. It's not possible to mock this inside Playwright or a browser in general.

**Comment by DanielStoica85** [comment]
Got it. Thank you.
