### ISSUE TITLE
[BUG] Chrome fails to launch after the CLI args are added by Playwright

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#22560]
### System info
- Playwright Version: 1.31.2
- Operating System: Android 13
- Browser: Chrome 112
  -  "Enable command line on non-rooted devices" is enabled in `chrome://flags`.
- Phone: Pixel 7 pro

### Source code

**Server script**

```js
async function launchAndroidServer() {
  const browserServer = await _android.launchServer({
    port: 5555,
    wsPath: "ws",
  });

  const wsEndpoint = browserServer.wsEndpoint();
  console.log("wsEndpoint:: ", wsEndpoint);
}

launchAndroidServer();
```

Client Script
```js
const { _android } = require('playwright');

(async () => {
  const device = await _android.connect(
      'ws://127.0.0.1:5555/ws'
  );

  console.log(`Model :: ${device.model()}, serial:: ${device.serial()}`)

  await device.shell('am force-stop com.android.chrome');
  const context = await device.launchBrowser();

  const page = await context.newPage();
  await page.goto('https://playwright.dev/');

  await page.close();
  await context.close();
})();

```

**Steps**
- Run the server script
- Run the client script

**Expected**
The script should open chrome browser and perform the steps.

**Actual**
Chrome gets crashed. This behaviour isn't observed when I tried with Pixel 4 Android 12 emulator.
The following args are added into the file at `/data/local/tmp/chrome-command-line`
```
--disable-fre --no-default-browser-check --remote-debugging-socket-name=playwright-ed2eee3a7c8af55941c198437a6148a4 --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf
```

The chrome gets crashed when I start the test. Also after stopping the client and server script, chrome gets crashed when opened. Chrome starts working after I remove chrome args added to `/data/local/tmp/chrome-command-line`.

**Comment by dgozman** [comment]
@ankur-lt Can you share the crash message and stack trace? Perhaps if you run with `DEBUG=pw:browser*` you'll see something.

**Comment by ankur-lt** [comment]
Client logs: [client.log](https://github.com/microsoft/playwright/files/11297648/client.log)
Server logs: [server.log](https://github.com/microsoft/playwright/files/11297649/server.log)


@dgozman , these are the client and server logs.

**Comment by dgozman** [comment]
@ankur-lt Unfortunately, there is not much in these logs. Can you go to `chrome://crashes` to see past crashes?

**Comment by ankur-lt** [comment]
Checking for the crash reports. Meanwhile, I checked for Chrome 108 and 109. The script executes as expected for these versions and it starts crashing from Chrome 110. @dgozman

**Comment by gskierk** [comment]
I have the same problem with Huawei P Smart 2019 (Android 12, Chrome 112) and Lenovo Tab M7 (Android 11, Chrome 112). On the other hand, my code runs correctly on BrowserStack (Samsung Galaxy S22, Android 12).

**Comment by ankur-lt** [comment]
@dgozman , chrome 112 launches correctly after removing `--disable-sync`. However, just adding the `--disable-sync` arg and removing others isn't crashing it. It could be happening because of a combination of flags.

**Comment by dgozman** [comment]
@ankur-lt Nice investigation! If you figure out the exact flags combination and/or crash id/stack, we can file an issue against Chromium.

**Comment by pranavj1001** [comment]
Hey @dgozman, a fix [PR](https://github.com/microsoft/playwright/pull/22583) for this exact issue was raised earlier. You can check the conversation going over there as well.

**Comment by mxschmitt** [comment]
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1439737
