### ISSUE TITLE
[Feature] Include Fixture steps into test timeline

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#22565]
We would want to have all fixtures used in a test to be included in the test report/tracing file.

This helps pinpoint more closely what failed and gives us performance data for the test infrastructure to track regressions in test execution duration or even unreliability issues in one of the fixtures.

Currently : 
![image](https://user-images.githubusercontent.com/37447884/233725661-fe607ce8-ea5a-41f7-ac67-d6230bcfee8b.png)

Expected : 
![image](https://user-images.githubusercontent.com/37447884/233725580-c79e2f62-5781-482f-8240-abad6939cef6.png)

the above I emulated with 
```ts
  download: [
    async ({ projectConfig }, use) => {
      test.step("Download desktop", () => {});
      ...
    },
    { scope: "worker", auto: true },
  ],
  install: [
    async ({ download }, use) => {
      test.step("Install desktop", () => {});
      ...
    },
    { scope: "worker", auto: true },
  ],
```

But it's not ideal to have to remember to add `test.step` and doesn't feel right?

**Comment by juniorerico** [comment]
Is there a way to disable this? This made our test report really ugly as we have a lot of fixtures.
By looking at the code I saw that the only way is by adding a `_` at the fixture name or use scope as 'worker', but the TestFixtures cannot have argument as far as I know.

Not sure if this the right place to comment

**Comment by dgozman** [comment]
@juniorerico All the fixtures should be hidden under `Before Hooks` in the report. Is that not the case? Could you file a separate issue by filling in the "Bug Report" template? Attaching a screenshot would be great!

**Comment by juniorerico** [comment]
@dgozman I've created the issue with the steps to reproduce. It is pretty easy tho.
#23835
