### ISSUE TITLE
[QUESTION] Do we have params variable in playwright similar to protractor to pass the data at test level

### ISSUE THREAD

**Issue by sankarkec** [microsoft/playwright#22561]
I am currently working on migration from protractor scripts to playwright. 
In protractor we have params variable at browser level. I used to set the data in config file like below 

exports.config = {
    params: {
        portNo: Prod,
        isDevLocal: true,
    },
}

I can able to access this this variable at anywhere in the test using below code

browser.params.isDevLocal

Do we have similar kind of feature in playwright to set the data at test level and can able to access that data globally any where in test case ?

**Comment by dgozman** [comment]
Take a look at [this guide](https://playwright.dev/docs/test-parameterize).

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
