### ISSUE TITLE
[BUG] WebKit on Linux includes Content-Length: 0 on GET requests (libsoup3)

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#22569]
### System info
- Playwright Version: v1.32.0
- Operating System: Ubuntu
- Browser: WebKit
- Other info: `mcr.microsoft.com/playwright:v1.32.0-focal` docker image

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.launch({ headless:false, devtools: true });
  const page = await browser.newPage();

  page.on('request', data => {
    data.allHeaders().then(headers => {
      console.log("content-length", headers['content-length']);
    });
  });

  await page.evaluate(() => {
    fetch("http://httpbin.org/get", {
      // this header will cause WebKit Linux to include a request header with Content-Length: 0
      "headers": { "Content-Type": "application/json" },
      "method": "GET"
    });
  });
})();
```

**Steps**
- Run the script on Linux and Mac
- Compare the logs
- See on Linux it logs `0` (unexpected) vs Mac it logs `undefined` (expected).

**Expected**

On Linux WebKit, the content-length header should not be included for GET requests -- the same way it works on Mac WebKit. 

This would align with [rfc 7230](https://datatracker.ietf.org/doc/html/rfc7230#section-3.3.2)
<img width="720" alt="Screenshot 2023-04-21 at 5 43 21 PM" src="https://user-images.githubusercontent.com/1136652/233752688-26dea165-6cfb-421b-9407-6ab8849e5147.png">

**Actual**

Only on Linux WebKit, a content-length 0 request header is included. This causes requests on websites to fail when accessing websites that protect against [HTTP Request Smuggling](https://en.wikipedia.org/wiki/HTTP_request_smuggling) attacks.

For example, any AWS ALB that has "Desync mitigation mode" set to `Strictest` will reject requests.

<img width="1140" alt="Screenshot 2023-04-21 at 6 56 10 PM" src="https://user-images.githubusercontent.com/1136652/233755769-5df8519d-e431-4e92-a75e-1dea41b33a4a.png">

**Comment by mxschmitt** [comment]
Looks like a libsoup bug to me:

```c
// Compile using:
// gcc test.c -o test `pkg-config --cflags --libs libsoup-2.4`
#include <libsoup/soup.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
    SoupSession *session;
    SoupMessage *msg;
    SoupURI *uri;
    const char *url;
    GError *error = NULL;

    url = "https://httpbin.org/headers";

    session = soup_session_new();
    msg = soup_message_new("GET", url);
    uri = soup_uri_new(url);

	soup_message_headers_append (msg->request_headers, "Content-Type", "kektus");

    soup_message_set_flags(msg, SOUP_MESSAGE_NO_REDIRECT);
    soup_message_set_uri(msg, uri);

    if (!soup_session_send_message(session, msg)) {
        fprintf(stderr, "Error sending request: %s\n", error->message);
        g_clear_error(&error);
        return 1;
    }

    printf("Status code: %d\n", msg->status_code);
    printf("%s", msg->response_body->data);

    soup_uri_free(uri);

    return 0;
}
```

which ends up in

```
Status code: 200
{
  "headers": {
    "Accept-Encoding": "gzip, deflate", 
    "Content-Length": "0", 
    "Content-Type": "kektus", 
    "Host": "httpbin.org", 
    "X-Amzn-Trace-Id": "Root=1-64440e2d-43565cee4f9bc7233912ae54"
  }
}
```

**Comment by mxschmitt** [comment]
We should evaluate if it makes sense for us to move to soup3 instead of soup2. They upstream use completely soup3 [already since 2 years](https://github.com/WebKit/WebKit/commit/869e5fe336d79311609f7036d6aa90ebd1b92698). We could use libsoup2 on Ubuntu20 and libsoup3 on Ubuntu22.

**Comment by mxschmitt** [comment]
Update: We decided to migrate to libsoup3 where its possible. For Ubuntu22+Debian11 this would mean libsoup3. This issue will keep track the progress of the migration.

**Comment by sylhero** [comment]
is libsoup3 migration done in v.137? https://github.com/microsoft/playwright/issues/23259 is still not working

**Comment by jperl** [comment]
I wish I could contribute a fix but my coding abilities are rusty. I contributed towards a [$2,000 bounty](https://gitpay.me/#/task/685) in case that could be helpful.
