### ISSUE TITLE
[BUG] page.close() never finished on Firefox persistent context.

### ISSUE THREAD

**Issue by meotimdihia** [microsoft/playwright#2256]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Windows
- Node version: 12.14
- Browser: Firefox

**Code Snippet**

```javascript
export {}
require('dotenv').config()
const playwright = require('playwright');

(async () => {
  for (const browserType of ['firefox']) {
    // const browser = await playwright[browserType].launch({'headless': false});
    const context = await  playwright[browserType].launchPersistentContext("C:\\Users\\meoti\\AppData\\Local\\Temp\\firefoxguest");
    const page = await context.newPage();
    await page.goto('https://google.com');
    await page.close() // wait forever at this line 
    console.log('test') 
  }
})();
```

**Describe the bug**
await page.close() run forever

**Comment by aslushnikov** [comment]
> await page.close() run forever

@meotimdihia it does work for me on Windows. Can you try running with `DEBUG` env variable set to `*`?

E.g. in cmd:

```
$ set DEBUG=*
$ node script.js
```

**Comment by meotimdihia** [comment]
I don't know but now its work for me too.
And I tried to open Firefox browser before running the script and get this error: 

![WindowsTerminal_2020-05-28_14-30-01](https://user-images.githubusercontent.com/300961/83112241-11d52d00-a0f0-11ea-9c22-a4101c3e089f.png)

**Comment by aslushnikov** [comment]
> And I tried to open Firefox browser before running the script and get this error:

@meotimdihia This happens because you try to re-use the same profile folder between current-running firefox process and the one in your script. Firefox doesn't support this mode, unfortunately!

> I don't know why but now its work for me too. 😃

Nice :)

> Firefox has too much bug for me. I tried to run headless Ubuntu but often has seen strange bugs.

Did you try it under WSL? I wouldn't recommend running browsers under WSL!

**Comment by meotimdihia** [comment]
> Did you try it under WSL? I wouldn't recommend running browsers under WSL!

I run it on the new Ubuntu machines that were created from cloud. But its another issue. I will report it later. 
Currently, we can close this issue. 😅
