### ISSUE TITLE
[BUG] The HTML reporter does not support domain name or reverse proxy access

### ISSUE THREAD

**Issue by HEJIN2016** [microsoft/playwright#22573]
### System info
- Playwright Version: [v1.32.2]
- Operating System: [macOS BigSur]
- Browser: [Chrome 112.0.5615.121]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

```
export default defineConfig({
  testDir: './tests',
  /* Maximum time one test can run for. */
  timeout: 600 * 1000,
  globalTimeout: 1000 * 60 * 30,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 10000,
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html', { open: 'always', port: process.env.NODE_SERVICE_PORT || '9103', host: 'local.webullbroker.com' }]],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium',
      testMatch: 'List.spec.ts',
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/user.json',
      },
      dependencies: ['setup'],
    },
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  // outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
})
```

**Steps**
- [Run the test]
- [Click Traces Image]

**Expected**

[html reporter success open]

**Actual**
![image](https://user-images.githubusercontent.com/25821307/233818469-627e9f45-c4a4-4179-b985-613fde5cfafa.png)
![image](https://user-images.githubusercontent.com/25821307/233818482-480db917-ed5b-4600-9316-6f47e89cb23a.png)
![image](https://user-images.githubusercontent.com/25821307/233818489-65433d32-7bc4-4643-8e74-be5e81b3c1d2.png)

It cannot be accessed by domain name or reverse proxy, but it can be accessed by localhost or 127.0.0.1
![image](https://user-images.githubusercontent.com/25821307/233818566-943496e7-799b-4543-abc5-b4519391209b.png)

Error：
```
caught (in promise) TypeError: Cannot read properties of undefined (reading 'register')
    at index.a18c30b0.js:1:3355
    at index.a18c30b0.js:1:3586
(anonymous) @ index.a18c30b0.js:1
(anonymous) @ index.a18c30b0.js:1
```

**Comment by mxschmitt** [comment]
The issue you're encountering is due to your HTML report not being served from a secure (HTTPS) origin. Service Workers necessitate a secure connection to serve a trace file, and this requirement is only exempted for localhost or 127.0.0.1.

**Comment by aslushnikov** [comment]
@HEJIN2016 In other words, as long as you serve from HTTPS, it should all work! Seems to be working as intended.

**Comment by HEJIN2016** [comment]
> The issue you're encountering is due to your HTML report not being served from a secure (HTTPS) origin. Service Workers necessitate a secure connection to serve a trace file, and this requirement is only exempted for localhost or 127.0.0.1.

OK,thanks
