### ISSUE TITLE
[BUG] Error: No named projects are specified in the configuration file

### ISSUE THREAD

**Issue by loynoir** [microsoft/playwright#22579]
### Reproduce
Day 1 on playwright, with 

- package.json `"type": "module"`
- copy paste playwright config using `require`, thus, `playwright.config.cjs`

```
Error: No named projects are specified in the configuration file
```

### Debug

Caused by `./node_modules/@playwright/test/lib/runner/projectUtils.js`

When no error
```
{
  projects: [
    {
      _internal: [Object],
      grep: /.*/,
      grepInvert: null,
      outputDir: '/path/to/project/test-results',
      repeatEach: 1,
      retries: 0,
      metadata: undefined,
      name: 'chromium',
```

When error
- package.json `"type": "module"`
- copy paste playwright config using `require`, thus, `playwright.config.cjs`

```
{
  projects: [
    {
      _internal: [Object],
      grep: /.*/,
      grepInvert: null,
      outputDir: '/path/to/project/test-results',
      repeatEach: 1,
      retries: 0,
      metadata: undefined,
      name: '',
```

### Workaround
- Convert copy paste CJS config to ESM `playwright.config.mjs`
- Convert `tests/example.spec.js` to ESM

Now 

```sh
$ npm exec -- playwright test --project=firefox
... 2 passed
```

**Comment by aslushnikov** [comment]
@loynoir I'm not sure I follow what's going on here. Could you please create a small github repo that illustrates the issue?

**Comment by loynoir** [comment]
@aslushnikov  

https://github.com/loynoir/reproduce-playwright-22579

**Comment by aslushnikov** [comment]
@loynoir looks like the `template` folder is missing in the repo?

**Comment by loynoir** [comment]
```sh
$ npm init -y playwright template
```

Generated by `create-playwright` or something.

**Comment by yury-s** [comment]
Since you switched to es6 modules by setting `type: "module"`, you have to use ecmascript import/export syntax and put the files into *.mjs/*.js:

`playwright.config.mjs`:
```js
import { defineConfig, devices } from '@playwright/test';
...
export default defineConfig({
...
```

**Comment by loynoir** [comment]
> Since you switched to es6 modules by setting type: "module", you have to use ecmascript import/export syntax and put the files into .mjs/.js

Not **have to**.

Any `XXX.cjs` is require-able within a `type: "module"` project.

And in this case, although there is workaround, it is still a bug.
