### ISSUE TITLE
[Feature] Use C/C++ package manager like `microsoft/vcpkg` to manage C/C++ dependency

### ISSUE THREAD

**Issue by loynoir** [microsoft/playwright#22577]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

**Feat**
Use C/C++ package manager like `microsoft/vcpkg` to manage C/C++ dependency

**BUG**
```
$ sudo npx playwright install-deps
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
sh: line 1: apt-get: command not found
Failed to install browser dependencies
Error: Installation process exited with code: 127
$ npm exec -- playwright test
...
    Error: browserType.launch: 
     ...
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:    
...
```

**Link**

https://playwright.dev/docs/troubleshooting#linux

> Linux
> Depending on your Linux distribution, you might need to install additional dependencies to run the browsers.
> note
> Only Debian 11, Ubuntu 20.04 and 22.04 are officially supported.

**Related**

- https://github.com/microsoft/playwright/issues/8100
- https://github.com/microsoft/playwright/pull/21336
- https://github.com/microsoft/playwright/issues/11122
- https://github.com/microsoft/playwright/issues/19458
- https://github.com/microsoft/playwright/issues/14736

**Comment by loynoir** [comment]
ArchLinux user day 1 on playwright

```sh
$ sudo pacman -S gtk3 alsa-lib libxcomposite libxdamage libxrandr fontconfig pango at-spi2-core cairo gdk-pixbuf2 dbus-glib libxcursor 
$ npm exec -- playwright test --project=firefox

Running 2 tests using 2 workers
  2 passed (13.9s)

To open last HTML report run:

  npx playwright show-report
```

Seems working.

**Comment by aslushnikov** [comment]
@loynoir I'm sorry, but ArchLinux is not currently supported by Playwright. The demand for the OS is tracked in the https://github.com/microsoft/playwright/issues/8100 - please, upvote that bug to bump it's priority. I'll close this one instead of the earlier one.
