### ISSUE TITLE
[BUG] expect(someLocator).toHaveScreenshot ignores global and direct timout, falls to default 1000ms

### ISSUE THREAD

**Issue by lucasbit** [microsoft/playwright#22575]
### System info
- Playwright Version: 1.32.3 but also reproduced on 1.30.2
- Operating System:Windows
- Browser: Chrome
- Other info: Node: 18.12.1

### Source code

```ts
await this.page.waitForLoadState("load", { timeout: 10 * 1000 });
      await expect(this.projectCard).toHaveScreenshot({
        mask: [
          this.projectNameInput,
          this.footerRegisterLabel,
          this.projectTabNumberInput,
        ],
        maxDiffPixelRatio: 0.01,
        timeout: 5 * 1000,
```

**Config file**

```ts
const config: PlaywrightTestConfig = {
  testDir: "./tests",
  /* Maximum time one test can run for. */
  timeout: 5 * 60 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000,
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  // retries: process.env.CI ? 2 : 0,
  // /* Opt out of parallel tests on CI. */
  // workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ["list"],
    ["html", { outputFolder: "./outputs", open: "never" }],
    ["junit", { outputFile: "./outputs/results.xml" }],
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 10 * 1000,
    headless: true,
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    viewport: { width: 1920, height: 1080 },
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://localhost:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "retain-on-failure",
  },

```

**Expected**
I expect to "expect(someLocator).toHaveScreenshot" to retry assertion for fail/success until it timeout is reached. 

**Actual**
Both global timeout (set in config), but also direct set as toHaveScreenshot(timeout: //will be ignored) are ignored as assertion fails < 1000ms
Plase checkout that picture. It is clear that 5000 as timeout has been passed, but also visible that assertion has failed after only 900ms
![image](https://user-images.githubusercontent.com/29520131/233837386-54ec879d-5185-4fec-8c25-89df49939c4b.png)

**Comment by aslushnikov** [comment]
> I expect to "expect(someLocator).toHaveScreenshot" to retry assertion for fail/success until it timeout is reached.

@lucasbit This is not how it works. According to [the documentation](https://playwright.dev/docs/next/api/class-pageassertions#page-assertions-to-have-screenshot-2):

> This function will wait until two consecutive page screenshots yield the same result, and then compare the last screenshot with the expectation.

More detailed explanation: https://youtu.be/keV2CIgtBlg?t=321

The behavior you're describing is requested here: https://github.com/microsoft/playwright/issues/20987

I'll close this in favor of that request. Please upvote that issue to bump it's priority!
