### ISSUE TITLE
[Feature] Share the default playwright config path throughout configuration docs

### ISSUE THREAD

**Issue by cefn** [microsoft/playwright#22588]
The documentation at https://playwright.dev/docs/test-configuration#global-setup-and-teardown shows some very useful looking options, but most of the examples don't describe the path to the config file.

Could the standard path to the file be documented there? According to https://playwright.dev/docs/test-cli it defaults to `playwright.config.ts` 

The example at https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend is good and uses a comment to suggest the likely path to the file shown. Ideally this would be the same for all examples.

**Comment by pavelfeldman** [comment]
Could you elaborate on what you mean by 'sharing default config path throughout the configuration'?

**Comment by cefn** [comment]
The subject line was...

> throughout the configuration **docs**

Below shows the first reference in the whole documentation page to the name of the configuration file used by playwright, which is likely the primary thing the reader of this documentation page needs to know. 

Note how far down the page this occurs and without any description.

![Screenshot_20230425-074307](https://user-images.githubusercontent.com/159819/234195463-f1d5f9f4-3738-4f28-a016-be225af12362.png)

The proposal is to describe somewhere near the top what the name of the config file is, or at least to ensure that **every** example config throughout the page has the same commenting.

**Comment by debs-obrien** [comment]
this pr will add the config path to all  config examples: https://github.com/microsoft/playwright/pull/22910
