### ISSUE TITLE
[BUG] page.waitForLoadState('networkidle') fails with nested cross origin iframes

### ISSUE THREAD

**Issue by k15a** [microsoft/playwright#2258]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Mac
- Node version: v12.16.3
- Browser: Chromium

**Code Snippet**

Reproduction is here: https://github.com/k15a/pw-site-isolation-wait-for-bug

**Describe the bug**

If there are two nested iframes that run on different origins (e.g. `index.html` loads an iframe with src `https://domain1.com/iframe.html` which loads an iframe with src `https://domain2.com/iframe.html`) then using `page.waitForLoadState('networkidle')` doesn't work unless you turn off `IsolateOrigins` and `site-per-process`.

It looks like the two requests to the `iframe.html` files never finish.

![Kapture 2020-05-15 at 13 29 31](https://user-images.githubusercontent.com/20357450/82045932-3bce2e80-96b0-11ea-9436-ad9aa519a290.gif)

**Comment by dgozman** [comment]
I can repro this, thank you for filing!

**Comment by dgozman** [comment]
Should be fixed in the 1.1 release.

**Comment by scottadamsmith** [comment]
Do you know when the 1.1 version will be available? I am only seeing 1.0.2 when installing latest from NPM. Thanks!

**Comment by k15a** [comment]
@scottadamsmith You can use `@next` to install a pre-release.
