### ISSUE TITLE
[BUG] Performance degragation in headful mode in 1.32

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#22598]
This is the same test (cucumber + PW) running with PW 1.31 & PW 1.32 in headful mode. Machine was in the same condition.
There are no differences when running in headless mode. (this was reported by multiple team members)

![Screenshot 2023-04-24 at 19 47 05](https://user-images.githubusercontent.com/7386255/234063500-d00509ef-c264-4540-9fe6-0738998ab260.png)

### System info
MacOS 13.3.1
Chromium

- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

Please let me know what to provide in order to reproduce. 

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by pavelfeldman** [comment]
:wave: Tally :wave: 

Anything we can reproduce locally? Logs? Traces? Can you spot from the API logs what is now slower?

**Comment by aslushnikov** [comment]
@Tallyb Could you please try with 1.33? This might be related to https://github.com/microsoft/playwright/issues/22348

**Comment by Tallyb** [comment]
Indeed fixed it! Thanks a lot.
