### ISSUE TITLE
[BUG] playwright-core can end up importing the wrong `@playwright/test` version due to missing peer dependency

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#22599]
### System info
- Playwright Version: v1.32.3
- Operating System: macOS 13.3.1
- Browser: All
- Other info: pnpm v7 as package manager on Node v16

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/segevfiner/playwright-core-version-conflict

**Steps**
- Run `pnpm install`
- Try running `pnpm playwright test` in the `apps/a` and `apps/b` directories.
- On of them will fail with an error message of this sort:

```
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Playwright Test integrity check failed:                                                                     ║
║ You have @playwright/test version '1.32.3' and 'playwright-core' version '1.32.2' installed!                ║
║ You probably added 'playwright-core' into your package.json by accident, remove it and re-run 'npm install' ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
```

**Expected**

For the tests of both packages the work.

**Actual**

A Playwright test integrity check failed error.

### Analysis
This is caused by the way pnpm hoists dependencies. Since `playwright-core` doesn't declare that `@playwright/test` as a peer dependency, pnpm isn't going to create separate trees for it in the virtual store with the actual `@playwright/test` version that is required by each package, rather there will only be one `playwright-core` used by both, which then when importing `@playwright/test` will get an arbitrary version of `@playwright/test` that happens to be the one that was hoisted.

I suggested a fix here https://github.com/microsoft/playwright/pull/22595, but it was rejected by @pavelfeldman, which requested I open an issue instead.

Note that the behavior with dependencies, peer dependencies, and CLI's (AKA `bin`) is very subtle, as it stands both `playwright-core` and `@playwright/test` declare the `bin`, which means one of them wins arbitrary and will be what gets invoked by the package manager. Also note that `@playwright/experimental-ct-vue` and the like also do the same. So just moving the CLI to one of those packages might not be as trivial as they will fight each other.

**Comment by pavelfeldman** [comment]
Could you share more about your setup? As I understand, you have a monorepo and its projects depend on different versions of @playwright/test. How do you use CLI? Do you use it from the project folders or from the workspace folder?

**Comment by segevfiner** [comment]
From the project folders. Each project has a separate playwright test setup with its own separate config. I included a reproduction repository which shows this.
