### ISSUE TITLE
[BUG] Firefox 105.0.1 and up crashes on internal assert due to what seems an browser navigation

### ISSUE THREAD

**Issue by alex-kog** [microsoft/playwright#22590]
### System info

- Playwright Version: v1.27.0 and up
- Operating System: Ubuntu 20, macOS 13.2
- Browser: Firefox 105.0.1 and up

### Source code

Example to reproduce this issue: https://gist.github.com/alex-kog/450942ec0b068d2a501cea31ff60ef6f

**Steps**
- Create Wix credentials
- Set the credentials to the code attached
- Run the test
- if captcha appears, set it manually and press "Login"

**Expected**

Successful login and test finishes gracefully

**Actual**

Browser crashes

`/private/var/folders/1r/kymrx_bj4n90wwhh433cgxch0000gn/T/playwright-java-6888553227513803295/package/lib/utils/index.js:100
  if (!value) throw new Error(message || 'Assertion error');
                    ^
Error: Assertion error
    at assert (/private/var/folders/1r/kymrx_bj4n90wwhh433cgxch0000gn/T/playwright-java-6888553227513803295/package/lib/utils/index.js:100:21)
    at FrameManager.frameAttached (/private/var/folders/1r/kymrx_bj4n90wwhh433cgxch0000gn/T/playwright-java-6888553227513803295/package/lib/server/frames.js:133:25)
    at FFPage._onFrameAttached (/private/var/folders/1r/kymrx_bj4n90wwhh433cgxch0000gn/T/playwright-java-6888553227513803295/package/lib/server/firefox/ffPage.js:220:30)
    at FFSession.emit (node:events:513:28)
    at /private/var/folders/1r/kymrx_bj4n90wwhh433cgxch0000gn/T/playwright-java-6888553227513803295/package/lib/server/firefox/ffConnection.js:248:41`

**Additional Info**

For same Playwright version chromium browser works correctly, seems that the issue started on any Playwright that uses firefox 105.0.1 and up.
It only happens when the login was successful.

**Comment by aslushnikov** [comment]
@alex-kog thank you for the repro, I can repro with the following js snippet:

```js
import { firefox } from '@playwright/test';

const browser = await firefox.launch({
  headless: false,
});

const page = await browser.newPage();
await page.goto('https://manage.wix.com/account');
await page.fill("[autocomplete=\"email\"]", process.env.USERNAME);
await page.click("button[name=\"submit\"]");

await page.fill("[autocomplete=\"current-password\"]", process.env.PASSWORD);
await page.click("button[name=\"submit\"]");
```
