### ISSUE TITLE
[BUG] Xray-Report: Tests within a skipped test group unnecessarily create new Xray test issues

### ISSUE THREAD

**Issue by theokoester** [microsoft/playwright#22596]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All]
- Other info: GitLab pipeline

### Source code

For importing the results from my GitLab pipeline I use the extended Junit reporter which was fine so far.
All tests do have an test_key annotation with an already existing Test-Issue in Xray. 

Config according to [docs](https://playwright.dev/docs/test-reporters#junit-reporter)
```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

const xrayOptions = {
    textContentAnnotations: ['test_description'],
    outputFile: './xray-report.xml'
};

export default defineConfig({
    reporter: [['junit', xrayOptions]]
});
```

**Test file**

```js
test.describe.skip('ui tests @gui', () => {
    test('Some test', async ({ page }) => {
        test.info().annotations.push({ type: 'test_key', description: 'ABCD-166' })
        // ..test code
    })
})
```

**Expected**

When the group is being skipped, all the contained tests are transferred with status ToDo to an Xray execution and no new test issues are created. No creation because of the existing test_key annotation and already existing corresponding test issues in Xray is the expected [flow](https://docs.getxray.app/display/XRAY/Working+with+Automated+Tests)

**Actual**

All the tests within an skipped test.describe() group unnecessarily generate **new** test issues in Xray and an execution with run status ToDo. The existing test issues are being ignored instead of using them for attaching and linking the execution results, in this case *ToDo*.

**Comment by pavelfeldman** [comment]
We don't really support XRay. If you have reasons to believe JUnit that we generate is invalid, please file a specific bug!

**Comment by aslushnikov** [comment]
Closing this for now; given the discussion in https://github.com/microsoft/playwright/pull/22624, a dedicated xray support might be added sometime in future.
