### ISSUE TITLE
[BUG] baseURL loses the "path" part of the URL

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#22592]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [macOS 13.3.1]
- Browser: [All]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  baseURL: 'https://example.com/path', // 👈
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page, baseURL }) => {
  console.log(baseURL); // 👈  you'll see correct URL here
  await page.goto('test');
  await expect(page.url()).toBe('https://example.com/path/test'); // 👈 "path" part will be lost here
});
```

**Steps**
- [Run the test]

**Expected**

The path should remain; otherwise, it's impossible to test sites deployed to some "prefix folder" without hardcoding that prefix.

**Actual**

The "path" part is removed when the URL is created for navigation, like `page.goto()`.

**Comment by ltsuda** [comment]
I think in your case you can try:

```
baseURL: 'https://example.com/path/',  # notice the forward slash at the end
```
then

```
await page.goto('./test')
or
await page.goto('test') // this I'm not sure
```

more details :
https://playwright.dev/docs/api/class-testoptions#test-options-base-url
https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by e-oz** [comment]
thanks, @ltsuda , you are right - with the trailing slash and a dot it works.

For me, it means that we need to replace every navigation path in the tests to be able to run them against a deployed website... 🤦

I will not close this issue in case the team sees this as an opportunity for improvement.

**Comment by pavelfeldman** [comment]
We are following the spec: https://developer.mozilla.org/en-US/docs/Web/API/URL/URL

**Comment by rmarinsky** [comment]
@pavelfeldman as I see URL implementation that you have referenced it's possible to make baseURL with included /path for the "website" and for API requests 
that would be great to have such an implementation
