### ISSUE TITLE
[Feature] Access to component instance in component testing

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#22606]
It can be useful to have access to the component instance created by `mount` (`wrapper.vm` in `@vue/test-utils`). For example, to be able to test exposed values on the component, which can include functions that you might want to call (And not only data, that you might be better off testing the rendered DOM for).

**Comment by pavelfeldman** [comment]
I believe this has been discussed: https://github.com/microsoft/playwright/issues/16889
