### ISSUE TITLE
[internal] test `library/emulation-focus.spec.ts:104 - should not affect screenshots` fails on Headed WebKit Win

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#22616]
This started after https://github.com/microsoft/playwright/commit/eed6c332831bb1affc1f39583a6afa3d377e0a24

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/746130/234157933-9759302c-c31b-45fa-afe5-7339f69f6dd1.png">

Permalink: https://devops.playwright.dev/flakiness.html#timestamp=1682387654798

**Comment by mxschmitt** [comment]
Good: 1835
Bad: 1836

Upstream range: https://github.com/webkit/webkit/compare/c778044f0f66301348edea64fba9f0c7b96c59c3...ed632b1748c2fe7403fe6d780df66db97ca73b7e

**Comment by mxschmitt** [comment]
Moving to 1.34 due to the low risk of breakage.
