### ISSUE TITLE
[internal] test `library/video.spec.ts:712 - should capture full viewport on hidpi` is failing on headed WebKit Ubuntu

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#22617]
Started failing since: https://github.com/microsoft/playwright/commit/d95268ffc02f9f983ed22c918e43a7637ad6b61e

<img width="1490" alt="image" src="https://user-images.githubusercontent.com/746130/234159686-ff0af2f4-a98d-4012-8da2-68807bb43727.png">

Permalink: https://devops.playwright.dev/flakiness.html#commits=20&timestamp=1682389440266

**Comment by aslushnikov** [comment]
(looks like has nothing to do with Pavel's change)

**Comment by mxschmitt** [comment]
Relates to https://github.com/microsoft/playwright/issues/22411

**Comment by yury-s** [comment]
The test regressed after the roll https://github.com/microsoft/playwright-browsers/pull/375

**Comment by yury-s** [comment]
Maybe I was too quick with the conclusion, today the test is passing in 1835 and failing in 1836.

**Comment by aslushnikov** [comment]
Let's close if it doesn't work on headed only.

**Comment by yury-s** [comment]
Turns out the test passes in headed without xvfb but fails when running under xvfb-run.
