### ISSUE TITLE
[BUG] fill is removing the text content that is entered in the txet box

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#22610]
### System info
- Playwright Version: "@playwright/test": "^1.22.1",
- Operating System: MAC
- Browser: All
- Other info:

Try 1:
after entering value in the textbox, the value is getting removed, can you please explain why?
```javascript
await page.getByPlaceholder("Search All Bases by Employee ID").fill("5050");
await page.mouse.move(500, 500);
await page.keyboard.press("Enter");
```
it works only sometimes, after entering emp id, i want to press enter anywhere on the screen 

Try 2
```javascript
 await page.getByRole('textbox').fill("5050")
await page.keyboard.press("Enter");
```

Try 3- it didnt remove the text content, however enter is not working sometimes, and the table shows all records instead a single record that matches 5050.
```javascript
 await page.getByRole('textbox').fill("5050")
await page.getByRole('textbox').press('Enter')
```

Both the approach work sometimes, and fail occasionally..

<img width="885" alt="Screen Shot 2023-04-24 at 5 03 13 PM" src="https://user-images.githubusercontent.com/113629123/234126524-01040908-61f7-4cd1-aa46-4ab82d94daff.png">

**Comment by pavelfeldman** [comment]
Most likely, your page is clearing the input field lazily, after the value has been filled by Playwright. It is probably also adding keyboard listeners too late, after Enter has been pressed. This is a typical problem with hibernation. Make sure controls that are not yet listened to are disabled.

**Comment by InduKrish** [comment]
Sorry, I am trying to understand what i should fix in my playwright test code..

> Make sure controls that are not yet listened to are disabled.
Can you please explain the above statement and how i should be incorporating that in my test?

**Comment by aslushnikov** [comment]
> even when i manually try to hit enter and do a mouse click on the web page when the script is stuck , enter /click is not working. and the script is failing, as it doesn't filter for emp 5050 record in the table.

@InduKrish  It looks like the website is broken; I'm not sure there's much from the Playwright team to do here.

I'd recommend reaching out to the website devteam and asking them if this is a desired behavior.
