### ISSUE TITLE
[BUG] Codegen: cannot place the cursor in the middle of a sentence

### ISSUE THREAD

**Issue by leo-shao07** [microsoft/playwright#22623]
### System info
- Playwright Version: v1.32.3
- Operating System: windows11
- Browser: Chromium

<img width="461" alt="image" src="https://user-images.githubusercontent.com/78466501/234311738-9c99c50b-ad1b-45d7-94ab-92e22b55404d.png">

This happen when I use the codegen to generate script. Like the upon image, for example, I found I has a typo on the word "too", but I can't put the cursor in the middle of the sentence, the cursor can only start from the end of the line. Is there any solution on this situation?

**Comment by aslushnikov** [comment]
No, there's no solution. We have no API to control the cursor position in the text field.

The best workaround would be to start over if you did a typo.
hope this helps!
