### ISSUE TITLE
[Question] How playwright monitors recording through code?

### ISSUE THREAD

**Issue by jiankafei** [microsoft/playwright#22638]
Playwright supports codegen to listen to user actions and generate code, but my requirement is to be able to listen to user actions from a code level, such as the following:

```js
// Create a new recorder
const recoder = browser.newRecoder();

// Adding Events to the Recorder
recoder.addEventListener('record', (result) => {
    // Result is the JSON data generated by user operations, similar to the data generated in codegen
    // This event is triggered every time the user operates
    // My requirement is to retrieve this data through events in the code, rather than copying it in the codegen
    console.log(result)
})

// start recoder
recoder.start()
```

**Comment by aslushnikov** [comment]
This is not supported and there are no plans to support this kind of behavior.

**Comment by jiankafei** [comment]
> This is not supported and there are no plans to support this kind of behavior.

@aslushnikov 
Can you explain why this feature is not supported?
