### ISSUE TITLE
[BUG] testInfo.status is passed instead of failed 

### ISSUE THREAD

**Issue by publicmays** [microsoft/playwright#22635]
### System info
- Playwright Version: [v1.33.0-alpha-apr-20-2023]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

We identified in a previous version testInfo.status was not correct: https://github.com/microsoft/playwright/issues/22215 

We downloaded an updated version in Section A, however we are still finding that doing anything of the following in Section D is causing testInfo.status to evaluate as "passed" in Section C. Can you help us understand why? Our team wants to assert that testInfo.status is always "failed" on any thrown error or expect in the test or fixture.
# File Structure 

Section A:
/packages/tests/tests-playwright/package.json
```json
{
  "name": "@msteams/utilities-test-playwright",
  },
  "dependencies": {
    "@playwright/test": "1.33.0-alpha-apr-20-2023",
  },
}
```

Section B:
/packages/tests/tests-playwright/playwright.config.ts

```
 reporter: [
    [
      "html",
      {
        outputFolder: `playwright-report/reportTests`,
        open: isServerBuild() ? "never" : "on-failure",
      },
    ],
    ["junit", { outputFile: "playwright-report/reportTests/results.xml" }],
    ["list"],
  ],
export default defineConfig(config);

```

Section C:
Fixtures: /packages/tests/tests-playwright/fixtures/fixtures.ts
```ts
export const test = base.extend<
  testFixtures,
  projectFixtures & projectOptions
>({
  // Worker scoped fixtures
  projectConfig: [config, { scope: "worker", option: true }],
  launch: [
      await launch();
      await use(launch);
    },
    { auto: true },
  ],
  doThing1: async ({  }, use, testInfo) => {
     
    use(doThing1);

    // This is passed, when it should be failed.
    console.log(`testInfo.status: ${testInfo.status}`);

  },
});

export { expect } from "@playwright/test";

```

Section D:
/packages/tests/tests-playwright/feature/tests/my-test.spec.ts
```ts
import { test, expect } from "../../fixtures/fixtures";

test("x", async ({}) => {
    // Either below give testInfo.status to be passed
  throw new Error();
  expect(0).toBe(2);
});
```

**Steps**
- [Run the test]
- throw an error

**Expected**

// This is passed, when it should be failed.
    console.log(`testInfo.status: ${testInfo.status}`); // failed

**Actual**

// This is passed, when it should be failed.
    console.log(`testInfo.status: ${testInfo.status}`); // passed

**Comment by klepik1990** [comment]
Did you try to log this status in the afterEach hook?
`Actual status for the currently running test. Available after the test has finished in [test.afterEach()](https://playwright.dev/docs/api/class-test#test-after-each) hook and fixtures.`

**Comment by aslushnikov** [comment]
@publicmays you should await the `use()` in your fixture. Hope this helps!
