### ISSUE TITLE
[Feature] Codegen - Change "Record" button to "Recording" to indicate that the recording process is in progress, rather than indicating that the user needs to click to begin recording.

### ISSUE THREAD

**Issue by AClerbois** [microsoft/playwright#22647]
Currently, the "Record" button in Playwright is used to start the process of recording a user's actions on a web page. However, some users may be confused by the label "Record" and assume that they need to click the button to initiate recording, when in fact the recording process starts automatically once the button is clicked. To alleviate this confusion, we propose changing the label of the button to "Recording" to indicate that the recording process is already in progress.

By changing the label to "Recording", users will be more aware of the fact that their actions are being recorded as they navigate the website. This can help to prevent any confusion or misunderstandings about when the recording process actually starts. Additionally, it can make the process of recording feel more seamless and integrated into the user's workflow, since they will no longer need to manually click the button to begin recording.

Overall, we believe that changing the "Record" button to "Recording" is a small but impactful change that can improve the usability and clarity of Playwright's recording feature.

**Comment by aslushnikov** [comment]
We wouldn't want buttons to change their locations; this is considered to be a bad practice. 

We discussed, and decided to keep it as-is for now.

Thank you for suggesting though!
