### ISSUE TITLE
[BUG] page.goto: net::ERR_SOCKS_CONNECTION_FAILED when using connectOption and exposeNetwork

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright#22646]
### System info
- Playwright Version: 1.32.3
- Operating System: [All]
- Browser: [All]
- Other info: Using remote mode with port forwarding

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/puagarwa/playwrightExampleLocalhost]

**Steps**
- Github action with failure https://github.com/puagarwa/playwrightExampleLocalhost/actions/runs/4806619379/jobs/8554357473
- Above workflow have input param hostname which is by default empty 
- to repro the issue, we should run the workflow with value 'localhost'

We can run it locally as well
- clone repo
- npm run pw_server_start
- set LOCALlHTTPSERVERURL=localhost
- npx playwright test

**Expected**
test should pass
**Actual**
test fail with Error: page.goto: net::ERR_SOCKS_CONNECTION_FAILED at http://localhost:3000/

**Comment by dgozman** [comment]
It looks like version `v1.32.3` changes `localhost` to `127.0.0.1` on the client side, due to some old Node-specific logic. However, that was removed in #21847, so should work with `v1.33` already.

**Comment by puagarwa** [comment]
verified it with 1.33 and it works fine. thanks.
