### ISSUE TITLE
[BUG] Node 20: Performance tanks after a certain number of tests

### ISSUE THREAD

**Issue by gtm-nayan** [microsoft/playwright#22643]
### System info
- Playwright Version: v1.32.3
- Operating System: Ubuntu 22
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

https://github.com/gtm-nayan/playwright-speed

**Steps**
- Run the test on Node 20

**Expected**
All tests pass like on node 18 or node 19.9.0

**Actual**

After about test 20 or so, (on my machine at least) each test will get progressively slower until it triggers #22641, exiting the test without an error message and leaking the webserver process

**Comment by aslushnikov** [comment]
looks like this is caused by the node regression; merging to the https://github.com/microsoft/playwright/issues/22641 for now
