### ISSUE TITLE
[BUG] Problem with defining test-id attribute in code generation mode

### ISSUE THREAD

**Issue by personaljs** [microsoft/playwright#22653]
Hello. Thank you very much for this tool. I have an issue that I would like to share.

In code generation mode, there is no way to define the test-id attribute for tests.

However, in --debug mode, when running the test, it is pulled from the config and it works.

### System info
- Playwright Version: [v1.31]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

**Comment by aslushnikov** [comment]
@personaljs hey, thanks for filing!

This has been raised before in https://github.com/microsoft/playwright/issues/18888 The workaround would be to use VSCode extension to launch codegeneration - this way the value will be picked up from the config.

Hope this helps!

**Comment by personaljs** [comment]
Thank you for your response, Andrey) But what if I don't use vscode and use a different editor or just run it in the console? How can I solve the problem without using this workaround?
