### ISSUE TITLE
[Question] Importing static assets (.png) in component tests

### ISSUE THREAD

**Issue by ysulyma** [microsoft/playwright#22657]
### System info
- Playwright Version: 1.32.3
- Operating System: All
- Browser: All
- Other info:

### Source code

I'm using `@playwright/experimental-ct-react` to test components. Some of these take images as props. In tests, importing static assets, e.g.
```ts
import thumbnail from "../assets/thumbnail.png";
```
gives the error `SyntaxError: Invalid or unexpected token` on the import line. I believe Vite handles these imports with no config, so I'm not sure what to add to `ctViteConfig`.

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import {defineConfig, devices} from "@playwright/experimental-ct-react";

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: "./ct",
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: "./__snapshots__",
  /* Maximum time one test can run for. */
  timeout: 1 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: "html",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "chromium",
      use: {...devices["Desktop Chrome"]},
    },
    {
      name: "firefox",
      use: {...devices["Desktop Firefox"]},
    },
    {
      name: "webkit",
      use: {...devices["Desktop Safari"]},
    },
  ],
});
```

**Test file (self-contained)**

```js
import {test} from "@playwright/experimental-ct-react";

import thumbnail from "../assets/thumbnail.png";

test.use({viewport: {width: 500, height: 500}});

test("should work", async ({mount}) => {
  await mount(<img src={thumbnail} />);
});
```

**Steps**
- Run the test

**Expected**

Playwright should render the thumbnail

**Actual**

```
SyntaxError: Invalid or unexpected token

   at App.spec.tsx:3
```

**Comment by guillaumebrunerie** [comment]
Does it work if you add `?url` at the end of the import? That should force Vite to treat it as a static asset.
Otherwise, does it change something if you convert the project into a Javascript project (no Typescript)?

I'm having a similar issue myself trying to import SVG files as React components using svgr, it seems like svgr is just being ignored and that the svg file is parsed by a JS/TS parser instead. My feeling is that Playwright is somehow using Typescript to bundle the files instead of using Vite (I have some path mapping config and it's using those from my `tsconfig.json` instead of those in `ctViteConfig`). So if that's the case, I guess it's not particular surprising that Typescript cannot handle static imports by itself.

**Comment by apdrsn** [comment]
Hi @ysulyma 👋
Did you find a solution to this? I am having the same issue

**Comment by SetupCoding** [comment]
Same issue here using CRA and svg import like:

`import { ReactComponent as SomeSVGIcon } from './icons/some.svg';`

**Comment by cassus** [comment]
Still in issue in version `1.39.0`.

Last version without this issue is `1.33.0-alpha-mar-31-2023`. This issue blocks me from upgrading since than

**Comment by colin-c6** [comment]
This is still an issue in `1.40.0`

Has anyone found a solution to this?

**Comment by cassus** [comment]
Works for me on `1.40.1`

importing assets as such:
`import MarkedQuestionsBgImageUri from "../../assets/marked_questions_bg.png"`

The image even shows up in UI mode

**Comment by lorenzo-del-rosario** [comment]
I can still reproduce the same issue importing SVGs in `1.42.1`.
In a Remix project:
```
import favicon from '~/../public/favicon.svg';
...
export const links: LinksFunction = () => {
  return [
    {rel: 'icon', type: 'image/svg+xml', href: favicon},
   ...
  ];
};
```

```
import footerFlowerSvg from '../../public/footer-flower.svg';
...
<img src={footerFlowerSvg} alt="Logo" />
```

**Comment by garabedium** [comment]
I can reproduce in `1.43.1` as well.

**Comment by vogon** [comment]
I can also reproduce, in versions `1.32.3` (the version before the one where @cassus reported breakage), `1.43.1`, and `1.44.0`.

**Comment by cassus** [comment]
@pavelfeldman would you reopen this issue? Or should we create a new one?

**Comment by tp6gw94** [comment]
my solution install `vite-plugin-svgr`

```ts
ctViteConfig: async () => {
  const {default: svgr} = await import('vite-plugin-svgr')
  return {
    plugins: [svgr()]
  }
}
```
