### ISSUE TITLE
npm install / yarn add playwright takes forever

### ISSUE THREAD

**Issue by nojvek** [microsoft/playwright#2265]
I spent at-least 30 mins waiting for the spinner. This seems like a massive dependency. How do I speed it up? I already have chrome, firefox and safari on my machine.

How do I make playwright use existing versions?

**Comment by mxschmitt** [comment]
The recent Playwright versions will reuse the versions. Which operating system are you - using? And which Playwright version?

**Comment by nojvek** [comment]
I just did yarn add so whatever is latest published version. 

Using Mac on Catalina. It took 45 mins but seemed to work now. 

Having the getting started script work out of the box was a massive revelation. Wow! This is indeed a fantastic library.

**Comment by pavelfeldman** [comment]
First time Playwright is installed it fetches the browsers off CDNs (~450Mb). Could be the CDN outage or CDN throttling on your side...

**Comment by aslushnikov** [comment]
> How do I make playwright use existing versions?

@nojvek as of today (May 2020), Playwright has to download browsers from CDN since we distribute our own builds of webkit and firefox.

> Using Mac on Catalina. It took 45 mins but seemed to work now.

That's crazy! Looks like an occasional internet problem to me. It usually takes <30 seconds for me to download browsers. 

That said, Playwright caches downloaded browsers on your machine, so you'll need to do it only once.

**Comment by nojvek** [comment]
I know this is closed and thanks to responding to me at owl o’ clock. 

One thing that could make the install user experience nicer is printing something to the console e.g downloading <cdn url> of the browser do user just doesn’t see spinner for >30s.

**Comment by arjun27** [comment]
Thanks for pointing this out @nojvek. It seems that `yarn add` suppresses stdout/stderr output from postinstall scripts, causing the install progress to be hidden ([relevant issue](https://github.com/yarnpkg/yarn/issues/5476)). 

![Screen Shot 2020-05-17 at 10 54 48 AM](https://user-images.githubusercontent.com/284612/82155903-e5d2c580-982c-11ea-9b9c-ff8041230619.png)
