### ISSUE TITLE
[BUG] TypeScript's `baseUrl` is not honoured

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#22663]
### System info
- Playwright Version: 1.32.3
- Operating System: macOS 13.3.1
- Browser: N/A
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/OliverJAsh/playwright-ts-paths-issues/tree/base-url-ignored

**Test file (self-contained)**

```js
import * as Foo from "Foo";
console.log(Foo);
```

`tsconfig.json`:
```json
    "baseUrl": ".",
    "paths": {
      "shared/*": ["./shared/*"]
    }
```

**Steps**
```console
$ yarn
$ rm -rf .cache && tsc
$ rm -rf .cache && playwright test
```

**Expected**

`playwright test` should resolve all modules correctly, as per the behaviour of `tsc`.

**Actual**

`playwright test` results in the following error:

```
Error: Cannot find module 'Foo'
Require stack:
- /Users/oliverash/Development/playwright-ts-paths-issues/tests/example.spec.ts
```

**Workaround**

```diff
diff --git a/tsconfig.json b/tsconfig.json
index 0eaedd8..89c2a6f 100644
--- a/tsconfig.json
+++ b/tsconfig.json
@@ -5,6 +5,7 @@
     "rootDir": ".",
     "baseUrl": ".",
     "paths": {
+      "*": ["./*"],
       "shared/*": ["./shared/*"]
     }
   },

```

This shouldn't be necessary because Playwright should use the `baseUrl` to resolve the import specifier.

**Comment by aslushnikov** [comment]
@OliverJAsh This works as expected, according to the TypeScript documentation: https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping

**Comment by OliverJAsh** [comment]
@aslushnikov I don't believe so. The import works fine with `tsc`, so Playwright's behaviour doesn't match that of TypeScript.

https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url

[From the code](https://github.com/microsoft/playwright/blob/e9373dfb6e0a081878e47348be4ba328d72e5464/packages/playwright-test/src/common/transform.ts#L80) it appears that Playwright only uses `baseUrl` when matching a path, but TypeScript allows `baseUrl` to be used independent of `paths`.

**Comment by dgozman** [comment]
@OliverJAsh You are right, Playwright does not respect `baseUrl` without `paths`, but `tsc` does.
