### ISSUE TITLE
[Question] DomContentLoaded / Page load event never gets fired occasionally - Times out

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#22676]
### Problem 

I have a continuously running PW script inside a `docker environment` which is occasionally running in to timeout issues on navigation `page.goto` . Its happening once in a while and its not something wrong with the website as well as its pretty much a static website.
I have seen several people report some similar issues https://github.com/microsoft/playwright/issues/12182 and there is a high chance it could be happening because of the underlying site being down and such. But I dont think thats the case for my test as this is kinda weird and happening even for web pages with 5 requests, there is clearly something wrong and I have started debugging this with enabling some of the trace network events .

Attached complete events - https://gist.github.com/vigneshshanmugam/c478bc19e4492084d99002b4b9c8e413

Some things that are of interest
* Some of the network requests don't get responseFinished/responseFailed  event
* loadEvent  is never fired which is why page.goto  times out
* even tried collecting trace events and they showcase similar pattern.

I am not sure if there is a known chrome issue, Any help is much appreciated. 

Tried some workarounds like 
* Disabling share memory `--disable-dev-shm-usage` -  did not help
* Tried other 
* Increasing the memory size of the container - Memory usage is already very low so not really an issue

**Note: Only thing that helps a little but does not eliminate the issue completely is disabling custom network emulation**

**Comment by vigneshshanmugam** [comment]
Log that just contains the network events - https://gist.github.com/vigneshshanmugam/c478bc19e4492084d99002b4b9c8e413#file-network-events-txt

**Comment by vigneshshanmugam** [comment]
Adding the launch Options if that helps narrow down anything
```
pw:browser <launching> /usr/share/home/.cache/ms-playwright/chromium-1055/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --disable-gpu --user-data-dir=/tmp/playwright_chromiumdev_profile-33rqjd --remote-debugging-pipe --no-startup-window
pw:browser <launched> pid=1606
pw:browser [pid=1606][err] [0428/051240.068158:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
pw:browser [pid=1606][err] [0428/051240.071795:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
pw:browser [pid=1606][err] [0428/051240.071905:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
pw:browser [pid=1606][err] [0428/051240.074340:WARNING:bluez_dbus_manager.cc(247)] Floss manager not present, cannot set Floss enable/disable.
pw:browser [pid=1606][err] [0428/051240.084962:WARNING:sandbox_linux.cc(393)] InitializeSandbox() called with multiple threads in process gpu-process.
```

Does it ring any bell? Thanks.

**Comment by vigneshshanmugam** [comment]
@dgozman @aslushnikov Sorry for the direct messaging, But do you have any ideas here? No luck so far.

**Comment by aslushnikov** [comment]
@vigneshshanmugam technically, `DOMContentLoaded` or `load` event might never be fired, e.g. if the document response body is never fully received. So unless there's a good repro that points to the browser misbehavior, I'd assume that it's the server's fault.

**Comment by vigneshshanmugam** [comment]
@aslushnikov Yeah thats totally true, But the interesting thing it does not happen on WebPageTest and the website under test is just a static website hosted on Cloudflare. 

```ts
await page.goto('https://simonhearne.com/');
```

The reason why I was thinking it could be a PW or browser issue is mainly because the occasional timeouts goes away if the throttling settings are disabled. So either the `loadingFinished` is missing a condition in PW code or browser bug. I have tried with different docker/chrome level flags since my tests are running inside docker environment. 

I really do not have a good repro ATM other than failing out of nowhere.

**Comment by aslushnikov** [comment]
> the occasional timeouts goes away if the throttling settings are disabled. 

@vigneshshanmugam What throttling are we talking about?

**Comment by vigneshshanmugam** [comment]
@aslushnikov Emulating the chrome network conditions. This is from the log I posted here. 
```
pw:protocol SEND ► {"id":28,"method":"Network.emulateNetworkConditions","params":{"downloadThroughput":655360,"uploadThroughput":393216,"latency":20,"offline":false},"sessionId":"79496901EBDBB407DC7B40F451C57BDE"}"""

pw:protocol ◀ RECV {"id":28,"result":{},"sessionId":"79496901EBDBB407DC7B40F451C57BDE"}"""
```

**Comment by aslushnikov** [comment]
@vigneshshanmugam can you reproduce the same behavior with Chrome DevTools opened that emulate network conditions?

**Comment by vigneshshanmugam** [comment]
@aslushnikov I have tried before and cannot as this happens pretty rarely and the test was executed every 1 minute to check if the website is up and running simulated with the above network conditions.

**Comment by aslushnikov** [comment]
@vigneshshanmugam I see, so I guess you used it directly via CDP session. In this case, we can't help much: most likely, the issue is somewhere in the `Network.emulateNetworkConditions` CDP call or its interop with other CDP methods. These fall outside of our scope.

I'd recommend either digging further or filing upstream to chromium folks.

Finally, do note that `Network.emulateNetworkConditions` is lacking in different areas and at the very least [doesn't support websockets](https://bugs.chromium.org/p/chromium/issues/detail?id=1139824). I'd recommend against using it and using some proper network shaping tools instead.

**Comment by vigneshshanmugam** [comment]
Thanks @aslushnikov for the help. Yeah its pretty odd issue and I am not sure if anyone else is seeing this problem. I will keep digging and post if I find anything. 

Thanks for mentioning about the lack of Web sockets support on chrome network emulation. I remember reading about them from the [Lighthouse throttling docs](https://github.com/GoogleChrome/lighthouse/blob/main/docs/throttling.md)
