### ISSUE TITLE
[BUG] Types don't work in WebStorm ("Unresolved function or method")

### ISSUE THREAD

**Issue by davidgilbertson** [microsoft/playwright#2268]
**Context:**
- Playwright Version: 1.0.2
- IDE: WebStorm 2020.1

This isn't really a bug in Playwright, but the TypeScript types aren't picked up in WebStorm because they're in a different package (`playwright-core`).

![image](https://user-images.githubusercontent.com/4443482/82132171-355ec480-9820-11ea-8c8e-f1e49587fe78.png)

Although it's not the 'fault' of Playwright, I've never seen any other package do this, so Playwright will be one of the few packages where types don't work for WebStorm users.

I've logged this as an issue with JetBrains: https://youtrack.jetbrains.com/issue/WEB-45571, but it's not considered a bug so isn't going to change.

For WebStorm users finding this, the workaround is to either add `playwright-core` to your `package.json` or mark `node_modules/playwright-core` as 'Not excluded' in the IDE:
![image](https://user-images.githubusercontent.com/4443482/82132221-c2a21900-9820-11ea-977c-9ffb5d6dd87f.png)

Then all is well:
![image](https://user-images.githubusercontent.com/4443482/82132256-29273700-9821-11ea-8493-ebf5544b0228.png)

If this could be resolved that'd be great, but otherwise maybe note this in the getting started?

**Comment by davidgilbertson** [comment]
Great stuff @aslushnikov!

**Comment by acronym191** [comment]
> Great stuff [@aslushnikov](https://github.com/aslushnikov)!





https://twitter-streaming-api59.github.io/backdrop24/
