### ISSUE TITLE
[BUG] [WebServer] Syntax error: Unterminated quoted string

### ISSUE THREAD

**Issue by khmyznikov** [microsoft/playwright#22687]
### System info
- Playwright Version: [1.33]
- Operating System: [Github actions]
- Browser: [WebKit]
- Other info: Trying to test Azure Node Functions project

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

[github action](https://github.com/pwa-builder/pwabuilder-api-v2/actions/runs/4820917937/jobs/8586063801)
[repository](https://github.com/pwa-builder/pwabuilder-api-v2/tree/dev-non-container-try)
[config](https://github.com/pwa-builder/pwabuilder-api-v2/blob/dev-non-container-try/playwright.config.ts)

**Steps**
- [Github action triggers]

**Expected**

[tests success]

**Actual**

```
Run npx playwright test
  npx playwright test
  shell: /usr/bin/bash -e {0}

Running 0 tests using 0 workers
[WebServer] /home/runner/work/pwabuilder-api-v[2](https://github.com/pwa-builder/pwabuilder-api-v2/actions/runs/4820917937/jobs/8586063801#step:8:2)/pwabuilder-api-v2/node_modules/azure-functions-core-tools/bin/func: 2: [WebServer] Syntax error: Unterminated quoted string[WebServer] 

Error: Process from config.webServer was not able to start. Exit code: 2



Error: Process completed with exit code 1.
```

**Comment by aslushnikov** [comment]
@khmyznikov I just tried the following and it worked fine on my ubuntu 22:

```
$ node --version
v16.13.2
$ npm --version
8.1.2
$ cd && git clone --branch dev-non-container-try https://github.com/pwa-builder/pwabuilder-api-v2 tmp
$ cd tmp
$ npm ci
$ npm i azure-functions-core-tools@4 --unsafe-perm true
$ npx tsc
$ npx playwright test
```

So maybe the azure functions npm package got updated or something? Can you try re-starting the workflow?

**Comment by khmyznikov** [comment]
@aslushnikov Thanks for checking! Yes it is, just relaunched and all works! 🎉
![image](https://user-images.githubusercontent.com/6115884/235643631-a4e0da70-ed67-44fe-900b-6f3aa75e4b63.png)
