### ISSUE TITLE
In Windows playwright "Error: Not found tests" without cross-env before playwright in command line [BUG]

### ISSUE THREAD

**Issue by sytolk** [microsoft/playwright#22681]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [Windows]
- Browser: [All]
- Other info: I don't have this issue on Mac OS this is Windows only!
in .gitignore tests dir is ignored but with exclusions: https://github.com/tagspaces/tagspaces/blob/execute-playwright-without-jest/.gitignore#L94

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
- clone tagspaces repo: git clone https://github.com/tagspaces/tagspaces
- npm install && npm run build-e2e
- You can repeat this issue removing 'cross-env' from this command line: 
https://github.com/tagspaces/tagspaces/blob/execute-playwright-without-jest/package.json#L122
 and run `npm run test-playwright`

**Expected**

Playwright to find tests in testing dir defined in config:
 https://github.com/tagspaces/tagspaces/blob/execute-playwright-without-jest/playwright.config.js#L13

**Actual**

[Describe actual behavior]

https://github.com/tagspaces/tagspaces/actions/runs/4809491601/jobs/8560812420

No tests found error in github actions

**Comment by aslushnikov** [comment]
@sytolk my I ask you to reduce the repro so that there's less code?

**Comment by sytolk** [comment]
@aslushnikov with ideally environment single test and so on.. I'm sure that this issue cannot be reproduced :) but feels free to fork the source code and reduce the tests. This issue is very strange for me and the question is why it's happening in exactly this environment?

**Comment by aslushnikov** [comment]
> This issue is very strange for me and the question is why it's happening in exactly this environment?

@sytolk it usually happens due to some unfortunate interop with some other packages installed alongside. As a result, these kind of issues are getting fixed downstream, not in Playwright, and thus do not benefit other Playwright users. So I'm reluctant to spend time debugging this.

I encourage you to drive this investigation on your own, and re-file once you narrowed this down to some Playwright misbehavior.

**Comment by finnhvman** [comment]
For me upgrading `@playwright/test` from `1.32.3` to `1.33.0` makes playwright produce the following message upon trying to run tests. Tried specifying the exact test file, same result.
```
[WebServer] 
Error: No tests found
```

**Comment by finnhvman** [comment]
Got it working by

1. Running `npx playwright install` (gets new browser binaries, might not have been necessary)
2. Renaming my dummy test `test.ts` to `index.test.ts`

Probably something with the default test matchers, didn't bother to figure it out.
