### ISSUE TITLE
[Feature] Support ES module syntax

### ISSUE THREAD

**Issue by davidgilbertson** [microsoft/playwright#2269]
I'm using ES modules with Node 14. I can import Playwright like this:

```js
import playwright from 'playwright';

const { webkit } = playwright;
```

But not like this:
```js
import { webkit } from 'playwright';
```

This is because the build is CommonJS format, with no ES module variant. Which I guess is because you're using Webpack. For this feature request, you'd need to either switch to Rollup (IMO a better fit for npm packages) or wait for Webpack to support it ([it's in the works for V5](https://webpack.js.org/configuration/experiments/#experiments)).

**Comment by GeorgeWL** [comment]
Doesn't the esModuleInterop flag in webpack also allow that stole of import?

**Comment by davidgilbertson** [comment]
@GeorgeWL could you elaborate? Are you referring to Webpack in the build of Playwright? Or are you proposing that users of Playwright use Webpack to transpile their code?
