### ISSUE TITLE
[Question] WebKit download event when fulfilling route with PDF

### ISSUE THREAD

**Issue by vgcpaulino** [microsoft/playwright#22691]
### Problem

I’m having some problems with WebKit when I combine `page.waitForEvent(‘download’)`, where this download comes from a route that was fulfilled. For both Chrome and Firefox, it works fine, but the WebKit returns a timeout. 

`TimeoutError: page.waitForEvent: Timeout 10000ms exceeded while waiting for event "download"`.

I also tried to record the HAR with a complete environment using the applications and reuse it but without success.

Note: When using an express server to return the PDF, instead of using the route to fulfill the request the test passes.

### System info
- Playwright Version: 1.32.3
- Operating System: macOS 13.0.1
- Browser: WebKit

### Source code
[Gist Example](https://gist.github.com/vgcpaulino/9220806e3c31e6aef3f0e81acff930ac)

**Comment by mxschmitt** [comment]
Looks like the same as this fixme: https://github.com/microsoft/playwright/blob/1fecc20238f0a1a5d942726f246decf6fdfab8de/tests/library/download.spec.ts#L613

**Comment by aslushnikov** [comment]
Exactly; this test was added as part of https://github.com/microsoft/playwright/issues/7822 - merging there as a dupe.
