### ISSUE TITLE
copy to clipboard having issues with firefox and webkit 

### ISSUE THREAD

**Issue by aravindhalahalli** [microsoft/playwright#22708]
Hello, I'm having trouble copying content to the clipboard in the Firefox and Webkit browsers, however it works properly in Chrome because to a permission setting in the Playwright configuration.

**Comment by aslushnikov** [comment]
@aravindhalahalli could you please re-file this, following the issue template? Most important would be a short snippet that we would be able to run locally and that demonstrates that things work in Chromium and don't work in other browsers.
