### ISSUE TITLE
[Feature] Add Playwright to DevDocs.io

### ISSUE THREAD

**Issue by davidgilbertson** [microsoft/playwright#2270]
I use https://devdocs.io for accessing most docs/APIs, it would be great to have Playwright in there too (FWIW, Cypress and Puppeteer are in there).

Instructions for adding your docs: https://github.com/freeCodeCamp/devdocs/blob/master/docs/adding-docs.md

**Comment by pavelfeldman** [comment]
While we are doing that check out `https://playwright.dev` - it has a nice search.

**Comment by aslushnikov** [comment]
We'd be happy if community picks up it and maintains our documentation on devdocs.io; meanwhile, we're investing in [`playwright.dev`](https://playwright.dev) that gives us all flexibility we need.
