### ISSUE TITLE
[BUG] Header not persisted on request

### ISSUE THREAD

**Issue by pipi1007** [microsoft/playwright#2272]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Windows
- Node version: [e.g. 10.12, 10.14]
- Browser: Chrome
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

page.route('**', (route: Route, request: Request) => {
                const headers = request.headers();
                headers['customHeader'] = new Date().toISOString();
                route.continue({ headers });
        });

page.on('response', (response: Response) => {
            const latency =
                new Date().getTime() - new Date(response.request().headers()['customHeader']).getTime();
**Describe the bug**
}

latency is NaN because the customHeader info set in route override is lost on response handler.

**Comment by pavelfeldman** [comment]
Request interception does not modify the original request headers by design - in your code you obtain and modify the copy of the headers and continue the route with it.

In your concrete scenario, you could simply put a symbol on a request with the request time. Would you mind sharing more about your use case? We were considering exposing timing info on requests and responses and it is important for us to know what you are after.

**Comment by pipi1007** [comment]
We are trying to setup a probe to monitor our service and we'd like to measure latencies on each request. Intercepted headers are persisted on request by puppeteer. It'd be nice if playwright can also persist intercepted headers so I can tag the request and do stuff like measuring latency.

Could you please elaborate on how to put a symbol on the request?

**Comment by pavelfeldman** [comment]
I mean a simple property on request:

```js
request['requestTime'] = new Date().toISOString();
```

or a symbol, which is better in a sense that it won't clash with internal properties:

```js
const requestTime = Symbol('requestTime');
request[requestTime] = ...
```

and then you simply read it off the same request object. Would that work for you?

**Comment by pipi1007** [comment]
Just gave it a try and it is working, thanks for the suggestion.
