### ISSUE TITLE
[Question] is it possible to use 1 reporter on CI and different reporter locally?

### ISSUE THREAD

**Issue by Mshumaman** [microsoft/playwright#22728]
Hi, 
I want to know if it it possible to use 1 reporter on CI and different reporter locally. In CI we use Allure reporter but locally across the teams not all of them installed allure. Is it possible to configurate specific reporter for CI and another for local run?

Currently we run the tests with npx playwright test --reporter=html but it open the reporter automatically if the test failed. Is it possible to generate HTML report locally that will not open automatically and on CI use Allure?

**Comment by Nav-2d** [comment]
You can follow this to have a different on CI vs locally: https://playwright.dev/docs/test-reporters#reporters-on-ci

You can set open to never for html reporter so that it doesn't open automatically: https://playwright.dev/docs/test-reporters#html-reporter

**Comment by aslushnikov** [comment]
Closing as per response above.

**Comment by Mshumaman** [comment]
Hi,
It didn't work. Here is the playwright.config.ts
import { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
    timeout: 240000,
    globalTimeout: 18000000,
    projects: [
        {
            name: "Esro",
            testDir: "./Tests/Esro",
            timeout: 300001,
            use:{
                viewport: {width: 1870, height: 1030},
                video: {
                    mode: "retain-on-failure",
                    size: {
                        width: 1870,
                        height: 1030,
                    },
                },
            }
        },
        {
            name: "Tsro",
            testDir: "./Tests/Tsro",
            timeout: 180000,
        },
        {
            name: 'Unify',
            testDir: "./Tests/Unify",
        },

        {
            name: "IntegrationsUI",
            testDir: "./Tests/IntegrationsUI",
        },

        {
            name: "Validation",
            testMatch: 'Tests/Validation/test.list.ts',
            timeout: 360000,
            use: {
                actionTimeout: 320000,
            }
        },
        {
            name: "Production",
            testMatch: 'Tests/Unify/production.test.list.ts',
            timeout: 360000,
            use: {
                actionTimeout: 320000,
            }
        },

    ],
    reporter: [

        [process.env.CI ? "allure-playwright" : 'html', { open: 'never' }],
        // ['dot'],
        // ["allure-playwright"],
        ["junit", { outputFile: "reports/test-results.xml" }],
        ["json", { outputFile: "reports/test-results.json" }],
    ],
    use: {
        baseURL: process.env.BASE_URL ? process.env.BASE_URL : process.env.LOCAL_HOST,
        browserName: "chromium",
        actionTimeout: 30000,
        trace: "off",
        screenshot: "on",
        viewport: { width: 1400, height: 900 }, //UNIFY Recommended Resolution
        video: {
            mode: "retain-on-failure",
            size: {
                width: 1400,
                height: 900,
            },
        },
        contextOptions: {
            ignoreHTTPSErrors: true,
        },
        // Browser options
        launchOptions: {
            channel: "chrome",
            //    headless: process.env.CI ? true : false,
            slowMo: 50,
            args: [
                "--no-sandbox",
                "--ignore-certificate-errors",
                "--ignore-certificate-errors-skip-list",
            ],
        },
    },
};

export default config;

and in the CI
![image](https://user-images.githubusercontent.com/69470134/235592718-4395bdc4-84b8-4db8-900c-3b35d479a00f.png)


any thoughts what went wrong?

**Comment by AlexKomanov** [comment]
@Nav-2d @aslushnikov 
Should we need to define the `process.env.CI` before?
Maybe it is not defined automatically?

**Comment by alekseyp555** [comment]
> setting CI=true

hello please advice how to set this setting in the ci?
