### ISSUE TITLE
How to create an actually incognito browser

### ISSUE THREAD

**Issue by VeryFunnyXD** [microsoft/playwright#22723]
Hi, I want to create an incognito browser using "--incognito" but cant, playwright still create for me a Incognito but it doesnt same as chrome (playwright incognito is while color while chrome is black)

**Comment by aslushnikov** [comment]
> (playwright incognito is while color while chrome is black)

@VeryFunnyXD There's no way to create an incognito mode that is looking dark with Playwright. Doing so also falls outside of the project since this has nothing to do with web testing. 

Sorry!
