### ISSUE TITLE
[Question] Video is not being loaded even on stable chrome

### ISSUE THREAD

**Issue by charuSharma7** [microsoft/playwright#22727]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code

video tag 
<video 
width=“100%” height = “100%” 
src= “blob:https://XXXXX”

</video>

or

**Config file**

{ name: 'chrome',
      use: {
      channel: 'chrome',
      launchOptions: {
          executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
      },   
    }
  },

The video is loaded perfectly fine when loaded in chrome browser, but when accessed through Playwright, ”Digital Rights Error” error is thrown. I am trying the run it on stable chrome instead of chromium, but still no success. 

Widevine Content Decryption Module - Version: 4.10.2557.0
Status - Component already up to date

Any idea what it could be? and how could I fix it?

**Comment by aslushnikov** [comment]
@charuSharma7 looks like there are some flags that Playwright passes to Chrome that result in this error. Try running with [`ignoreDefaultArgs`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch) option and see if it works.

**Comment by charuSharma7** [comment]
> @charuSharma7 looks like there are some flags that Playwright passes to Chrome that result in this error. Try running with [`ignoreDefaultArgs`](https://playwright.dev/docs/next/api/class-browsertype#browser-type-launch) option and see if it works.


Is this how you're suggesting ? Apologies, if this is a basic question, I am new to this

{ name: 'chrome',
      use: {
      channel: 'chrome',
      launchOptions: {
          executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',
          args: [
            '--ignoreDefaultArgs']
      },
      
    }
  },

**Comment by aslushnikov** [comment]
@charuSharma7 the easiest would be to create an `a.mjs` file with the following content:

```ts
// a.mjs
import { chromium } from '@playwright/test';

const browser = await chromium.launch({
  channel: 'chrome',
  ignoreDefaultArgs: true,
  headless: false,
});
const page = await browser.newPage();
// navigate to URL and make sure things work
await page.goto('...');
```

Then try to run it with `node a.mjs` and see if you still get the same error.

**Comment by charuSharma7** [comment]
with **ignoreDefaultArgs** set to true, test is failing before navigating to the application i.e. await page.goto('') is not executed

node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^

browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
<launched> pid=91722
[pid=91722][out] Opening in existing browser session.
=========================== logs ===========================
<launching> /Applications/Google Chrome.app/Contents/MacOS/Google Chrome 
<launched> pid=91722
[pid=91722][out] Opening in existing browser session.

**Comment by charuSharma7** [comment]
this issue is also replicable on amazon prime video

**Comment by charuSharma7** [comment]
@aslushnikov any suggestion?

**Comment by aslushnikov** [comment]
@charuSharma7 you have to close the stable chrome browser before running the script.

**Comment by aslushnikov** [comment]
@charuSharma7 overall, this looks like something specific to your website and environment. I'd recommend asking this on https://aka.ms/playwright/discord
