### ISSUE TITLE
[BUG] Unable to disable chromium download in this step Playwright.create()

### ISSUE THREAD

**Issue by syedshaheazali** [microsoft/playwright#22732]
### System info
- Playwright Version: [build v1055]
- Operating System: [All, Windows 11etc.]
- Browser: [Chromium]
- Other info: I want to manually download chromium and stop playwright from auto downloads at this step 
- "Playwright.create()"

### Source code

        public static void main(String[] args) {
            try (Playwright playwright = Playwright.create()) {
                        BrowserType chromium = playwright.chromium();
                        Browser browser = chromium.launch();
                        Page page = browser.newPage();
                        page.onRequest(request -> System.out.println(">> " + request.method() + " " + request.url()));
                        page.onResponse(response -> System.out.println("<<" + response.status() + " " + response.url()));
                        page.navigate("https://example.com");
                        browser.close();
                    }
                }

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

or

**Config file**

**Steps**
- [Run the test]
- [...]

**Expected**
It should not try to download chromium again 

[Describe expected behavior]

**Actual**
Error: getaddrinfo EAI_AGAIN playwright.azureedge.net
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:95:17) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright.azureedge.net'
}

[Describe actual behavior]
As I am using it behind the firewall , so I am not allowed to access outside network for my project

**Comment by syedshaheazali** [comment]
I got it disabled by adding env variable like this  but i am still trying some options like config update 

  Map<String,String> env = new HashMap<>();
            env.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1");
            try (Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(env))) {
                        BrowserType chromium = playwright.chromium();
                        Browser browser = chromium.launch();
                        Page page = browser.newPage();
                        page.onRequest(request -> System.out.println(">> " + request.method() + " " + request.url()));
                        page.onResponse(response -> System.out.println("<<" + response.status() + " " + response.url()));
                        page.navigate("https://example.com");
                        browser.close();
                    }
                }

**Comment by aslushnikov** [comment]
@syedshaheazali looks like you got a workaround; closing then!
