### ISSUE TITLE
[BUG] Playwright's WebKit version seems to not support native image loading

### ISSUE THREAD

**Issue by tkadlec** [microsoft/playwright#22738]
### System info
- Playwright Version: v1.32+
- Operating System: Mac 13.3
- Browser: WebKit
- Other info:

### Source code
- [x] I provided exact source code that allows reproducing the issue locally.

```js
import { webkit } from 'playwright'; 

(async () => {
  const browser = await webkit.launch({headless: false});
  const page = await browser.newPage();
  await page.goto('https://mathiasbynens.be/demo/img-loading-lazy');
  await browser.close();
})();
```

**Steps**
- Run the script above (`node minimal.js`)

**Expected**

When the page is loaded in Webkit, we should see that the loading element is supported.

Example from native Safari:

![Screenshot 2023-05-01 at 1 56 34 PM](https://user-images.githubusercontent.com/66536/235511087-5c7cee9c-caa9-499a-a320-220dcada5126.jpg)

**Actual**

The loading attribute is not detected.
![Screenshot 2023-05-01 at 1 57 04 PM](https://user-images.githubusercontent.com/66536/235511168-6f357335-a6dd-49a2-a3aa-5bd805e7b0c3.jpg)

**Comment by yury-s** [comment]
This is a regression introduced in this webkit roll: https://github.com/microsoft/playwright-browsers/pull/181

**Comment by yury-s** [comment]
@dpino , FYI
