### ISSUE TITLE
[BUG] Assertions never resolve on prerendered pages

### ISSUE THREAD

**Issue by josephwynn-sc** [microsoft/playwright#22733]
**⚠️ Important:** This issue is referring to [prerender2](https://chromestatus.com/feature/5197044678393856), a feature in Chromium. It is **not** referring to the technique of rendering JS-heavy pages as static HTML. More information in this [Chrome Developers blog post](https://developer.chrome.com/blog/prerender-pages/).

### System info

- Playwright Version: 1.33.0
- Operating System: macOS 13.3.1
- Browser: Chromium
- Other info: Prerender2 is only enabled in headed mode or with the `--headless=new` Chromium flag.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";

export default defineConfig({
  timeout: 10000,
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from "@playwright/test";
import { chromium } from "playwright";

let browser;

test.beforeAll(async () => {
  browser = await chromium.launch({
    // Run in headed mode so that you can see the test image is visible.
    headless: false,

    // If you run this test headless, you must run with --headless=new to enable prerender2.
    // args: ["--headless=new"],
  });
});

test("Assertions work when the browser navigates directly to the page", async () => {
  // This test just proves that the toBeVisible assertion should work on the timer.html page.
  const page = await browser.newPage();
  await page.goto("https://prerender2-specrules.glitch.me/timer.html");
  await expect(page.locator("img")).toBeVisible();
});

test("Assertions work when the browser navigates to a prerendered page", async () => {
  const page = await browser.newPage();
  await page.goto("https://prerender2-specrules.glitch.me/");

  // This adds prerender speculation rules to the page, causing the next page to be prerendered.
  await page.locator("#specRules").click();

  // This clicks the link to the next page, which loads the prerendered version.
  await page.getByText("timer.html", { exact: true }).click();

  // This assertion never resolves, and the test times out.
  await expect(page.locator("img")).toBeVisible();
});
```

**Steps**
- Run the test, prefereably in headed mode
- Observe that the timer.html page opens, and the image renders
- Observe that the `toBeVisible` assertion never resolves

**Expected**

The `toBeVisible` assertion should pass in the second test.

**Actual**

The `toBeVisible` assertion in the second test never passes, and the test times out.

**Comment by josephwynn-sc** [comment]
This seems to be an issue with prerendering in general. With protocol logs on, I can see that the prerendered page triggers `Page.frameScheduledNavigation` and `Page.frameRequestedNavigation` events, but never receives any `Network.responseReceived` or similar. I'm guessing this is because Chromium does the prerender in a parallel FrameTree, rather than inside the current context.

Are there any Chromium folk lurking around who can weigh in on whether it will be possible for Playwright to attach to the prerender frame?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by domenic** [comment]
> Are there any Chromium folk lurking around who can weigh in on whether it will be possible for Playwright to attach to the prerender frame? I would hope this is possible, since we get a `Runtime.executionContextCreated` event with the `frameId` for the prerender frame.

It should be possible. Here are some examples of code in Chromium itself that gets access to the prerender frame and communicates with it using the DevTools Protocol:

- https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/web_tests/http/tests/inspector-protocol/tracing/prerender.js;l=13-27;drc=4902584d33fd17af107fa197f9818cb299c8f917

- https://source.chromium.org/chromium/chromium/src/+/refs/tags/124.0.6315.0:third_party/blink/web_tests/http/tests/inspector-protocol/resources/inspector-protocol-test.js;l=548-594;drc=3288ac2808b18ca1a671bdb4235684767813abfb
