### ISSUE TITLE
[BUG] api mock/intercept causes page and all requests to hang

### ISSUE THREAD

**Issue by almiller9** [microsoft/playwright#22740]
I have used this on other applications and have not had issues. For some reason this page hangs and never loads when I try and intercept the api that loads data on to the page. If I remove this it will load just fine, just not with the data I want. Is there something I am doing wrong that would cause this? Its not just the mocked endpoint either. All requests never finish.

### System info
- Playwright Version: 1.32.3
- Operating System: [Windows 10,]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

await this.page.route('**/api/jobs/kickoff/', route => route.fulfill({ status: 200, body: JSON.stringify(mockedBody)             }))

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by yury-s** [comment]
Please follow the issue template and provide a self-contained code example so that we can reproduce the problem locally, otherwise it's impossible to guess what your test is doing and what is specific about the web app.
