### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by abhinavraj100** [microsoft/playwright#22743]
### System info
- Playwright Version: [1.32.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chrome]
- Other info: Selenium grid v4.3.0

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

// c# playwright
var pw = await Playwright.CreateAsync();
                var browser = await pw.Chromium.LaunchAsync(new BrowserTypeLaunchOptions
                {
                    Headless = headlessChrome
                });
```
```

**Steps**
- [Run the test]
- [...]

**Expected**
Playwright test should work fine as it does locally

**Actual**

Session timeout occurs on selenium grid with error -  pw:browser <selenium> disconnecting from sessionId=763eb6fba16f584c69e9a6c7da64ce63; pw:browser <ws disconnected>
code=1005 reason=

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/20162
