### ISSUE TITLE
[REGRESSION]: Screenshots different in Firefox on 1.33 due to mouse position

### ISSUE THREAD

**Issue by thewilkybarkid** [microsoft/playwright#22755]
**Context:**
- GOOD Playwright Version: 1.32.3
- BAD Playwright Version: 1.33.0
- Operating System: Docker image
- Extra: Mac Host

We have a bunch of screenshot comparisons starting to fail in 1.33.0 only in Firefox; an example is:

- [code](https://github.com/PREreview/prereview.org/blob/a27a491c40888281e082944c7c4510498480215e/integration/publishing-a-prereview.spec.ts#L1873-L1913)
- [trace.zip](https://github.com/microsoft/playwright/files/11371857/trace.zip)
- [video.webm](https://user-images.githubusercontent.com/1784740/235634323-3459c564-7b43-4f19-88b3-1ce9a2125fdc.webm)

When it gets through to the "Sorry, we're having problems" page, the "Privacy Policy" link in the footer has an extra thick underline: this is the hover style on links, which is unexpected.

It seems that the position of the mouse has remained unchanged from clicking on the "Start now" button (the log-in form is completed entirely using the keyboard), and it happens that the "Privacy Policy" link is in the same place in the viewport. This didn't happen previously in Firefox, and doesn't happen in the other browers.

If I add a `await page.mouse.move(0, 0)` before taking the screenshot, the link is not hovered and the test passes as expected.

**Comment by thewilkybarkid** [comment]
I've just taken a trace with it passing on 1.32.3:

[trace.zip](https://github.com/microsoft/playwright/files/11372082/trace.zip)
[video.webm](https://user-images.githubusercontent.com/1784740/235639983-3186b5ff-b1b4-40f9-91d0-353eefa82336.webm)

There is a difference with clicking the "Start now" button: it scrolls before doing so. This means the link is in a different place. I will try to confirm if there is a behaviour change or if Firefox was always doing this (and this happens to be the first time I've triggered it).

**Comment by thewilkybarkid** [comment]
I've confirmed that this isn't a regression: Firefox in 1.32.3 was doing the same.

I've fiddled the page to contain lots of links and see the hover appearing:

[trace.zip](https://github.com/microsoft/playwright/files/11372214/trace.zip)
[video.webm](https://user-images.githubusercontent.com/1784740/235644070-6c196884-2241-4413-8e86-097273db3e46.webm)

FWIW, this is the trace from Chrome (where it doesn't hover):

[trace.zip](https://github.com/microsoft/playwright/files/11372217/trace.zip)
[video.webm](https://user-images.githubusercontent.com/1784740/235644112-d5343766-00cf-483a-aa98-26eadb3bff65.webm)

After using `Locator.click()`, what is the expectation around the mouse's position?

**Comment by yury-s** [comment]
Can you extract the failing test in a standalone example which we could run locally?

**Comment by aslushnikov** [comment]
@thewilkybarkid ah yes, in 1.33 we fixed a bug when we were always scrolling in Firefox before clicking, even when there was no need to.

Now, in firefox we also have a very trustworthy mouse emulation; so when the page navigates, the mouse stays in place, triggering underlying hover effects. Let us see what we can do here

**Comment by aslushnikov** [comment]
We discussed this, and since this is how the stable firefox works, we decided to keep this as-is. So the workaround would be to move the mouse in this particular test to remove the hover (or to re-baseline with the hover).

Sorry for the inconvenience!
