### ISSUE TITLE
[Question] Unable to modify PUT data

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#22758]
According to the documents we should be able to listen and modify the postData of a request. Im still relatively new to Playwright (loving it so far!) but I cannot figure out what I am doing wrong.

Right now my `page.route` function looks like this:

 ```
await page.route('**/api/users/', (route, request) => {
    console.log(request.postData())
    const postData = "name=intercept&email=tester@gmail.com"
    console.log("This is being called")
    route.continue({postData});
  });
  //This click triggers the actual PUT request
  await page.getByRole("button", { name: "Save" }).click();
```
This is a super simple example, but im essentially updating a form with a PUT request. an trying to override the formdata that's being passed in the request.

I can see the postData and that it's being called, and I am passing it in the `route.continue` without errors.....but I don't actually see it happening on the actual web application.

Can we not actually modify PUT requests? Or am I doing something wrong.

Note: It works fine when I change headers, but postData doesn't seem to change at all.

**Comment by msmith1114** [comment]
So I think maybe I am seeing the issue:

1. The website isn't responsive so the "Updated" payload doesn't show unless I manually refresh it.
2. Chrome Dev tools does NOT show the updated/intercepted postData. Is this intentional?

**Comment by yury-s** [comment]
> Can we not actually modify PUT requests? Or am I doing something wrong.

Put requests can be modified and the code looks legit.

Can you follow the bug template and provide a self-contained example which we could run locally?

> The website isn't responsive so the "Updated" payload doesn't show unless I manually refresh it.

May well be the case, we don't know what your web site does.

> Chrome Dev tools does NOT show the updated/intercepted postData. Is this intentional?

This is a question to DevTools team. As far as I can see at least for `fetch` requests they only show original postData, even thought the server receives overridden one.

**Comment by msmith1114** [comment]
@yury-s I think the code is working, but the real issue was that Chrome was not showing the updated postData. I think this question can probably be closed (as it was working, but wasn't showing updated results on the browser).

Although I guess that does bring up the question of debugging. I may post an issue to chrome dev tools team as I imagine we should be able to see overridden data.
