### ISSUE TITLE
Playwright hangs with 'msedge' or 'chrome' channel browsers in headed mode

### ISSUE THREAD

**Issue by thomas-phillips-nz** [microsoft/playwright#22776]
When running a playwright test with a 'msedge' or 'chrome' channel chromium browser in headed mode, after the test has finished and the browser closed, Playwright will hang for around 30 seconds before finishing.
If running several tests, it will hang for 30 seconds in between each test.
Turning off the "Continue running background extensions and apps" option in both browsers has no effect

Chrome version(s) tested:
- Version 112.0.5615.138
- Version 113.0.5672.64

Edge version(s) tested:
- Version 112.0.1722.64
- Version 112.0.1722.68

Chromium version tested:
- Version 113.0.5672.53 

Playwright version 1.33.0, Windows 11

Here is a small code snippet to reproduce the code:
```
import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://google.co.nz');
});
```

Here is my projects variable in my config file:
```
  projects: [
    {
      name: 'Edge',
      use: {
        ...devices['Desktop Edge'],
        channel: 'msedge',
      },
    },
  ]
```

Here is the command I am using to invoke playwright:
`npx playwright test test-1.spec.ts --workers 1 --headed`

**Comment by yury-s** [comment]
> Turning off the "Continue running background extensions and apps" option in both browsers has no effect

Do you run the tests with extensions?

Please share a project that we could run locally to reproduce this problem (including extensions if they affect the behavior).

Does the problem reproduce when running Chromium without specifying a `channel`? What about other browsers?

Do you have video enabled in the playwright config?

**Comment by thomas-phillips-nz** [comment]
Ah, looks our organisation installs the Smartbear Test Extension in Google Chrome and Microsoft Edge.
Extension for chrome: https://chrome.google.com/webstore/detail/smartbear-test-extension/gmhjclgpamdccpomoomknemhmmialaae
Extension for Microsoft Edge: https://microsoftedge.microsoft.com/addons/detail/smartbear-test-extension/dnboadgmjeggdengfhphcmlclboenlco
I am unable to test without this extension, my organisation forces it to be enabled.
Attached is a project you can run locally:
[playwright-browser-bug.zip](https://github.com/microsoft/playwright/files/11392195/playwright-browser-bug.zip)

I do not have video enabled.

**Comment by yury-s** [comment]
Unfortunately this is a known issue mentioned as a warning on [this page](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) and we can't do much about misbehaving extensions and the enterprise policies in a generic way.
