### ISSUE TITLE
[REGRESSION]: Accessible name combination of label and button no longer found

### ISSUE THREAD

**Issue by Basti098765** [microsoft/playwright#22779]
**Context:**
- GOOD Playwright Version: 1.32.3
- BAD Playwright Version: 1.33.0
- Operating System: Ubuntu

**Code Snippet**

Impl Code
```typescript
<div id="labelTest-labelSelf">
    <label id="widget-1-label" for="widget-1-control">Test</label>
    <button type="button" id="widget-1-control" aria-labelledby="widget-1-label widget-1-control">Button</button>
</div>
```
Test Code
``` typescript
test('label directives for self+label', async ({ page }) => {
  await page.goto(pageUrl);
  await expect(page.locator('#labelTest-labelSelf').locator('role=button[name="Test Button"]')).toBeVisible();
});
```

**Describe the bug**
The tests times out because it is unable to locate the button in 1.33.0. The test is used to check the accessible name of the Element and if the combination works as expected. 

If I inspect the Button in the browser it shows up as expected with the accessible name being "Test Button". Until 1.32.3 that also worked for the playwright locators. And the Visibility check for the above test code succeeded. I also tried to update this test to use the newer `getByRole("button" { name: "Test Button" }` but the results stay the same.

**Comment by yury-s** [comment]
Can reproduce this with the following code in 1.33.0 and it works fine in 1.32.0:

```js
import { test, expect } from '@playwright/test';

test('label directives for self+label', async ({ page }) => {
  await page.setContent(`<div id="labelTest-labelSelf">
      <label id="widget-1-label" for="widget-1-control">Test</label>
      <button type="button" id="widget-1-control" aria-labelledby="widget-1-label widget-1-control">Button</button>
    </div>`);
  await expect(page.locator('#labelTest-labelSelf').locator('role=button[name="Test Button"]')).toBeVisible();
});
``
