### ISSUE TITLE
[Feature] support scoped tag

### ISSUE THREAD

**Issue by guiyomh** [microsoft/playwright#22777]
I run the same scenario several times on different environments. And I generate a tag to differentiate them in the test report. 

But today, playwright does not seem to support scoped tags. I do something like this: 

```ts
const environments: Environment[] = ['stg', 'int']; 

for (const environment of environments) {
  test(`login @env:${environment}`, async ({ page }) => {
    // ...
  }
}
```
But I get this in the report:
![Capture d’écran 2023-05-03 à 09 04 17](https://user-images.githubusercontent.com/363162/235851165-b56f1cf5-c996-4d27-bd21-67585b83061c.png)

Alors que j'aurais aimer quelques chose comme ceci.
![Capture d’écran 2023-05-03 à 09 06 32](https://user-images.githubusercontent.com/363162/235851511-169c0b77-d302-46b2-a87c-b96c045b8697.png)

I was hoping for a behavior like gitlab -> https://docs.gitlab.com/ee/user/project/labels.html#scoped-labels

**Comment by yury-s** [comment]
You can filter the tests that you want to run by providing [`grep`](https://playwright.dev/docs/api/class-testproject#test-project-grep) option in a project configuration or via command line:

```sh
npx playwright test --grep @env:stg
```

Alternatively, you can generate the tests based on an environment variable:

```ts
test(`login @env:${process.env.MY_ENV}`, async ({ page }) => {
    // ...
});
```
And then pass it when starting the tests:
```sh
MY_ENV=stg npx playwright test 
```

Would this work for you?
