### ISSUE TITLE
[BUG] broken link in docs

### ISSUE THREAD

**Issue by davidgilbertson** [microsoft/playwright#2278]
On this page https://playwright.dev/#version=v1.0.2&path=docs%2Fci.md&q=github-actions there is the text "We run **our tests** on GitHub Actions".

In the [markdown](https://raw.githubusercontent.com/microsoft/playwright/master/docs/ci.md), "our tests" is the link: `/.github/workflows/tests.yml` - but this isn't being converted correctly when the website builds, so the link becomes https://github.com/.github/workflows/tests.yml - which is a 404

**Comment by aslushnikov** [comment]
Should be fixed on the website right now (if it doesn't, reload a few times - service worker takes time to update).
