### ISSUE TITLE
how to add useragent in launch_persistent_context or args in playwright python ? [BUG]

### ISSUE THREAD

**Issue by RSKAPOOR** [microsoft/playwright#22787]

**Comment by yury-s** [comment]
User Agent is configured per context, see [this doc](https://playwright.dev/python/docs/emulation#user-agent) for persistent context you can pass it as an [user_agent](https://playwright.dev/python/docs/api/class-browsertype#browser-type-launch-persistent-context-option-user-agent) option to `launch_persistent_context`.
