### ISSUE TITLE
[BUG] Type checks are failing in component tests (Solid).

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#22795]
Error: src/App.tsx(9,8): error TS2739: Type '{ src: string; alt: string; width: number; height: number; }' is missing the following properties from type 'ImgHTMLAttributes<HTMLImageElement>': elementtiming, fetchpriority
  ✘  12 tests/components/test-all.spec.js:17:5 › ct-solid › typecheck (4.8s)

**Comment by pavelfeldman** [comment]
// @sand4rt

**Comment by mxschmitt** [comment]
Seems fixed.
