### ISSUE TITLE
[BUG] trace.playwright.dev breaks some chrome extensions

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#22807]
i'm developing a chrome extension and noticed that content scripts that use `chrome.runtime.getURL` do not work on https://trace.playwright.dev. there seems to be something on the page blocking the requests or something

### System info
- Playwright Version: n/a
- Operating System: windows 10
- Browser: chromium

**Steps**
1. install a chrome extension that uses dynamic imports using `chrome.runtime.getURL` (such as https://github.com/SAP/ui5-inspector)
2. go to https://trace.playwright.dev/
3. open devtools
4. click ui5 tab

**Expected**
![image](https://user-images.githubusercontent.com/57028336/236098111-7156c388-d949-467f-9125-111eede87e63.png)

**Actual**
![image](https://user-images.githubusercontent.com/57028336/236098146-d44e00ef-8aaa-4692-8d26-83b1fdd3fb30.png)

**Comment by yury-s** [comment]
https://trace.playwright.dev/ is just a web page, it looks like the extension you mentioned doesn't work properly with it. It's possible that the extension itself may not be functioning correctly on other web pages as well. In any case, this is not a bug in the Playwright, you can ask the question on the extension's support forum.

**Comment by DetachHead** [comment]
@yury-s It happens with my own extension that I'm developing too, that extension was just an example.

There's definitely something up with the trace viewer that causes this, because every extension I've tried has the same issue
