### ISSUE TITLE
[QUESTION] Waiting for Single-page application to load (React/Angular) best practice

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#22809]
According to the docs: https://playwright.dev/docs/api/class-page#page-wait-for-load-state
waitForLoadState='networkidle' is DISCOURAGED

While the page loads, both 'load' and 'domcontentloaded' events are fired before all the components has been fully rendered, the only option that I found helpful so far is 'networkidle'.

I saw that the recommendation is to rely on web assertions to assess readiness instead, but in my case, I supply a navigation fixture that isn't aware of any elements.

what is the best practice to ensure a single-page application is fully loaded?

**Comment by yury-s** [comment]
There is no universal solution. How does human understand if the app is loaded? Usually there is an element in the UI that should appear and you can use web assertions. In some cases you can wait until some javascript condition [evaluates](https://playwright.dev/docs/api/class-page#page-wait-for-url) to true in the page to check if the page is fully loaded.

**Comment by yury-s** [comment]
> I saw that the recommendation is to rely on web assertions to assess readiness instead, but in my case, I supply a navigation fixture that isn't aware of any elements.

The web assertions should automatically wait for corresponding conditions regardless of which navigation fixture you use. Closing this issue as there is no universal solution, feel free to open a new report if you have problems with particulars use cases.
