### ISSUE TITLE
[BUG] : Cannot find parent object when `beforeunload` is used

### ISSUE THREAD

**Issue by pastelsky** [microsoft/playwright#22803]
### System info
- Playwright Version: v1.33
- Operating System: Mac
- Browser: Chrome

### Source code

See https://github.com/pastelsky/playwright-bug-context-close for reproduction. 
This repository is essentially forked version of https://github.com/mxschmitt/playwright-test-coverage with coverage reporting enabled for component testing.

The problem is caused by this code —

```ts
import { test as baseTest } from '@playwright/experimental-ct-react';

export const test = baseTest.extend({
  context: async ({ context }, use) => {
  await context.addInitScript(() =>
      // Doesn't like beforeunload
      window.addEventListener('beforeunload', () =>
        (window as any).collectIstanbulCoverage(JSON.stringify((window as any).__coverage__))
      ),
    );
})
```

To Repro, locally, run — 

```
yarn install
yarn test-ct --debug
```

**Expected**
All tests run as usual, and the coverage fixture does its job

**Actual**
An error is thrown — 

```
Error: Cannot find parent object browser-context@2d67d578b2ae472a340c75c689f8ca3b to create frame@49e95606ebb9dab3a292250bf68d8607
```

Note, this is only a minimal repro, which seems to error out consistently with the `--debug` flag. However, in my codebase, I see the same error even when running without `--debug`.

Interestingly, setting — 
```
use: {
        video: 'on',
}
```

in the playwright config also fixes this error. It seems like some sort of a race condition that is fixed by enabling this option.

**Comment by xiamingwei** [comment]
I also encountered this issue. I am using functions and have identified that this piece of code is causing the problem. When I use the VS Code plugin Playwright for VS Code, after running the test for the first time and the browser is still open, if I click to run the test again, the following tests will fail immediately with the same error. How can I solve this problem?
