### ISSUE TITLE
[BUG] libevent-2.1-7 install-deps error with Ubuntu 22.10

### ISSUE THREAD

**Issue by apmcodes** [microsoft/playwright#22811]
### System info
- Playwright Version: ^1.32.1
- Operating System: DISTRIB_RELEASE=22.10 5.19.0-23-generic  x86_64 x86_64 x86_64 GNU/Linux
- Browser: Chromium
- Other info:

**Steps**
running the npx playwright install-deps gives the following error. 

```
Package libevent-2.1-7 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libevent-2.1-7a

E: Unable to locate package libicu70
E: Unable to locate package libffi7
E: Unable to locate package libx264-163
E: Package 'libevent-2.1-7' has no installation candidate
Failed to install browser dependencies
Error: Installation process exited with code: 100

```

Have tried installing the below, but didn't help
```
apt install libevent-dev libevent-2.1-7a
```

**Comment by apmcodes** [comment]
Rebuild OS with Ubuntu 22.04 and had no problem with install-deps

**Comment by yury-s** [comment]
We only officially support LTS Ubuntu releases. With that said, you might be able to manually install missing [dependencies](https://github.com/microsoft/playwright/blob/7e3f0118247c9e4799f2d9ff9243955f2d7d6d82/packages/playwright-core/src/server/registry/nativeDeps.ts#L466-L523) on 22.10.
