### ISSUE TITLE
[QUESTION] Using new context on an existing pages

### ISSUE THREAD

**Issue by EmiliaZorin** [microsoft/playwright#22823]
### System info
- Playwright Version: [V1.32.3]
- Operating System: [Windows 11]
- Browser: [Chrome]

```
await expect(planningPage.assignmentNotificationList).toBeVisible();
const [newPage] = await Promise.all([
    page.waitForEvent('popup'),
    await page.locator(selectorsOfPlanningPage.notificationItem,{hasText:elementsData.scriptAssignment}).first().click()
]);
await newPage.locator(selectorsOfInspectorPage.inspectorTitle,{hasText:elementsData.cardName}).first();
await newPage.locator(selectorsOfScriptEditor.scriptEditorHeader).nth(1);
await newPage.locator(selectorsOfScriptEditor.scriptEditorTable);
await newPage.locator(selectorsOfScriptEditor.scriptEditorContainer);
// await scriptEditorPage.assertScriptEditorOpen(elementsData.cardName);
```

- [ ] I provided exact source code that allows reproducing the issue locally.

Hi!
I am writing a test that runs in one tab and then opens another one.
I was wondering if there is a way to use the methods that I made in a certain class with the new tab referance <newPage>.
I have assertScriptEditorOpen method that is written in scripteditorPage class and I want to use it in the new Tab. 
Something like : await newPage.scriptEditorPage.assertScriptEditorOpen().

Is there any thing similar to it?
using scriptEditorPage.assertScriptEditorOpen() does not work after the new tab opens.

Thanks in advance!

**Comment by yury-s** [comment]
Assuming you POM class accepts Page in the constructor you can do it like this:

```js
const newScriptEditor = new ScriptEditor(newPage);
await newScriptEditor.assertScriptEditorOpen(elementsData.cardName);
```
it all depends on how you construct scriptEditorPage and pass `Page` objects to its methods. 

This is not a playwright bug, so closing this report.
