### ISSUE TITLE
[Question]: How to provide fallback proxy to chromium?

### ISSUE THREAD

**Issue by sohaib17** [microsoft/playwright#22839]
### Your question

Chrome documentation states that in case of bad proxies, given a comma separated list of proxies, Chrome can fallback to secondary proxies. According to Playwright docs, proxy is a dict, not an array. So how can we pass multiple proxies to this dict?

[Chrome documentation](https://chromium.googlesource.com/chromium/src/+/HEAD/net/docs/proxy.md#manual-proxy-settings):

> With the above configuration, if the proxy server was unreachable all requests would fail with ERR_PROXY_CONNECTION_FAILED. To address this we could add a fallback to DIRECT by launching using --proxy-server="http://foo:8080,direct://" (note the comma separated list). 

> If instead we wanted to proxy only http:// URLs through the HTTPS proxy https://foo:443, and have everything else use the SOCKSv5 proxy socks5://mysocks:1080 we could launch Chrome with --proxy-server="http=https://foo:443;socks=socks5://mysocks:1080". 

If PW does not support this, is there any way this can be done by using `args`? And can we still provide `proxy.bypass` list via PW while providing proxy through `args`?

OS: AlmaLinux 8
PW: playwright==1.32.1 (python 3.8)

**Comment by yury-s** [comment]
Playwright's proxy API does not support such use case, but you can try passing all the proxy configurations as additional command line args (both --proxy-server and --proxy-bypass-list) and not use proxy option at all. Will that work for you?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
