### ISSUE TITLE
[BUG] issue with waitForSelector

### ISSUE THREAD

**Issue by saurabhxkapoor** [microsoft/playwright#2283]
- Playwright Version: 1.0.2
- Operating System: Mac
- Node version: 10.15.2
- Browser: chrome (tried chrome only)

I am migrating tests from Puppeteer to use Playwright.

![image](https://user-images.githubusercontent.com/8683732/82240680-d5901880-9908-11ea-8b3a-a14011aed30b.png)

```javascript
waitUntilAppears: async function (selector, timeoutTime) {
        let timeout_updated = await (typeof timeoutTime === 'undefined' ? TIMEOUT : timeoutTime);
        console.log(selector);
        console.log(timeout_updated);
        await page.waitForSelector(selector, {
                timeout: timeout_updated * 1000,
                state: 'visible'
            });
    },
```

When this method is called, it waits for `waiting for selector "[visible] .arc-tree-node"`. Seems like the selector needs to be only `.arc-tree-node` and not prefixed with [visible]. Because, if i searc the selector in chrome console - `[visible] .arc-tree-node`, i dont find anything.

Any pointers ?

**Comment by pavelfeldman** [comment]
What it failed at finding is `.arc-tree-node`, is the the error message that is confusing. It was trying to fine `.arc-tree-node` that would have non-empty bounding rect and failed...
