### ISSUE TITLE
[Feature] Add label to HTML-report from test.describe for test filtering

### ISSUE THREAD

**Issue by PaulMEdwards** [microsoft/playwright#22830]
As a follow-up to #14487, it would be nice to also parse `test.describe` text for tags to add as labels. The screenshot below shows an example use case which is currently unsupported.

<img width="996" alt="Screenshot 2023-05-04 at 2 06 35 PM" src="https://user-images.githubusercontent.com/153847/236295275-fa0e12d1-ed37-4e9d-bf47-6ee83cfb4e2f.png">

**Comment by yury-s** [comment]
@alexneo2003 would you like to take a look at this?

**Comment by shwarcu** [comment]
Is this issue still relevant? I think it could be closed because of https://github.com/microsoft/playwright/pull/22870
