### ISSUE TITLE
Generate Auth token using API + client certificate with password

### ISSUE THREAD

**Issue by rahul045054** [microsoft/playwright#22845]
I have an API that will generate Auth token for us and for this we are sending client certificate with password. So, anyone having an idea how to do this setup in playwright. 

Need help Asap!!!!!!

**Comment by yury-s** [comment]
Please follow this guide: https://playwright.dev/docs/auth There is open [issue](https://github.com/microsoft/playwright/issues/17881) regarding NTLM authentication. If Playwright lacks some APIs that you need feel free to open a feature request with detailed description of your use case. Closing this report as it is not about a bug in Playwright.

**Comment by rahul045054** [comment]
not getting any solution for this
