### ISSUE TITLE
[Feature] Add tags parameters for grep function

### ISSUE THREAD

**Issue by DzmitryMaretski** [microsoft/playwright#22849]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Currently `--grep` function looks into test title. 
I would prefer to use additional parameter in tests like as `tags`
Currently:
`test('smoke [test] here is title', () => {})`

Proposal:
`test('[test] here is title', () => {}, { tags: ['smoke', 'regression', etc] })`

It means that tags will have their place instead of place near title

**Comment by yury-s** [comment]
We considered different ways of adding tags to the tests and opted for just the convention of [@tag](https://playwright.dev/docs/test-annotations#tag-tests) and --grep mostly for its simplicity. Can you elaborate on why current approach doesn't work for you and how would you use the tags in conjunction with --grep?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
