### ISSUE TITLE
[BUG] Incorrect number of tests per shard

### ISSUE THREAD

**Issue by DzmitryMaretski** [microsoft/playwright#22848]
### System info
- Playwright Version: [1.31.2]
- Additional info:
I have added experimental decorators. Due to this functionality i have added `tsc --incremental -p ./tsconfig.json` 
Number of tests: 360 tests in 211 files

**Steps**
- Prepare list of tests
- Run with the following command:
npm test -- --config=./tests-out/rp.playwright.config.js --grep-invert=<grep_value> --shard=x/20
where x - dynamic value

**Expected**

All shards have pretty the same number of tests. Only 20 shard can have a bit lower than other shards

**Actual**

All shards have too different number of tests.
For example:

| Shard # | Number of tests |
|---------|-----------------|
|       1 |        21       |
|       2 |        17       |
|       3 |        16       |
|       4 |        25       |
|       5 |        20       |
|       6 |        29       |
|       7 |        14       |
|       8 |        13       |
|       9 |        19       |
|      10 |        27       |
|      11 |        32       |
|      12 |        20       |
|      13 |        23       |
|      14 |        11       |
|      15 |        8        |
|      16 |        10       |
|      17 |        10       |
|      18 |        10       |
|      19 |        11       |
|      20 |        17       |

You can see that some of those have more than 30 items, but some of them - only 8. 
It means that shard with 32 test can run too long when tests start to fail

**Comment by Nav-2d** [comment]
A thread that can be helpful: https://github.com/microsoft/playwright/issues/21497
