### ISSUE TITLE
In a Web table, if i do the horizontal scroll then only i can able identify the element hidden columns and all columns will get loaded

### ISSUE THREAD

**Issue by Jav5552** [microsoft/playwright#22842]
in our case, we have a web table with 13 column. if the website is launched we can able to see the 7 column. If I want to see the other columns I have to scroll  horizontal using horizontal scroll bar. Then we have to scroll right. we can able to see the other cloumns..
if i try to get columns names also i will be able to get only 7 column names.
Do we have any method for this?
i have  tried with below code it didn't scroll.
await page.locator("text=Value").scrollIntoViewIfNeeded();

do we have any method to achieve above mentioned scenario..?

**Comment by yury-s** [comment]
Sounds like your table is lazily populated when a column gets visible in the viewport. scrollIntoViewIfNeeded will not work unless element is already in the DOM. You can either call [`page.mouse.wheel()`](https://playwright.dev/docs/api/class-mouse#mouse-wheel) after focusing the table or call [scrollBy](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollBy) on the element that contains the columns (via [`Locator.evaluate()`](https://playwright.dev/docs/api/class-locator#locator-evaluate) to make the columns visible. If you think there is a bug in playwright please open a new issue and fill out the template including a self contained repro that we could run to reproduce the problem.
