### ISSUE TITLE
[BUG] Testing react components. Strange reaction to comments

### ISSUE THREAD

**Issue by mikeogi** [microsoft/playwright#22846]
### System info
- Playwright Version: `"@playwright/experimental-ct-react" - 1.33.0`
- Operating System: macOS 13.3.1 ventura

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Button.spec.tsx**
Failed case
```ts
import { test, expect } from '@playwright/experimental-ct-react';

import Button from './Button.component';

test('render the base button', async ({ mount }) => {
  const component = await mount(<Button>click me</Button>);
  await expect(component).toHaveScreenshot();
});

test.use({ viewport: { width: 1000, height: 900 } });

test('render the full width button', async ({ mount }) => {
  const component = await mount(<Button fullWidth>click me</Button>);
  await expect(component).toHaveScreenshot();
});

// test('test text', async ({ mount }) => {
//   const component = await mount(<span>click me</span>);
//   await expect(component).toContainText('click me');
// });
```

**Button.spec.tsx**
Success case
```ts
import { test, expect } from '@playwright/experimental-ct-react';

import Button from './Button.component';

test('render the base button', async ({ mount }) => {
  const component = await mount(<Button>click me</Button>);
  await expect(component).toHaveScreenshot();
});

test.use({ viewport: { width: 1000, height: 900 } });

test('render the full width button', async ({ mount }) => {
  const component = await mount(<Button fullWidth>click me</Button>);
  await expect(component).toHaveScreenshot();
});

```

**Steps**
- write the test
- add commented test below

**Expected**
the comment does not affect the work

**Actual**
```bash
Error: Cannot find module '/Users/mikeglyc/job/wallet/ui-kit/src/components/Button/Button.component' imported from /Users/mikeglyc/job/wallet/ui-kit/src/components/Button/Button.spec.tsx
```

**Comment by yury-s** [comment]
Can you share full project so that we can debug it locally?

**Comment by yury-s** [comment]
@mikeogi note also, that `test.use({ viewport: { width: 1000, height: 900 } });` between the tests will affect __all__ tests in the file, not only those that defined after the call. You can either call [setViewportSize](https://playwright.dev/docs/api/class-page#page-set-viewport-size) inside the tests or wrap tests with the same viewport into `test.describe` blocks, if you want viewport to vary from test to test.

**Comment by sand4rt** [comment]
Hey @mikeogi, thank you for submitting the issue! As @yury-s mentioned, an example project where the problem can be reproduced is needed to investigate this further.
 
Cool didn't know about `page.setViewportSize`!
