### ISSUE TITLE
[BUG] fullyParallel config setting not working

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#22853]
### System info
- Playwright Version: [v1.33]
- Operating System: Mac
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  fullyParallel: true,
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

// test.describe.configure({ mode: 'parallel' });

test.describe('basic test', () => {
  test('first', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Playwright/);
  });

  test('second', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Playwright/);
  });
});
```

**Steps**
- npx playwright test

**Expected**

According to the doc, I can set `fullyParallel: true` to run all tests within a single file in parallel without having `test.describe.configure({ mode: 'parallel' });` in each file.

**Actual**

Currently, using `fullyParallel: true` doesn't run them tests within a single file in parallel. I have use `test.describe.configure({ mode: 'parallel' });` to make it work

**Comment by yury-s** [comment]
I cannot reproduce it, here is the output:

```
$ npx playwright test

Running 2 tests using 2 workers

  ✓  1 tests/example.spec.ts:11:7 › basic test › second (1.3s)
  ✓  2 tests/example.spec.ts:6:7 › basic test › first (1.2s)

  2 passed (1.9s)
```

Do you pass `--workers 1` by any chance?

**Comment by Nav-2d** [comment]
I don't pass workers param at all meaning it should pick up my workers automatically which is 4 usually. Let me create a github repo and paste it here. Thanks!

**Comment by yury-s** [comment]
This is what I ran: https://github.com/yury-s/bug-22853

**Comment by Nav-2d** [comment]
Ok I figured the issue with my setup. My config was within the `tests` folder instead of the root level so it wasn't reading it. Sorry for the trouble. Closing this one!
