### ISSUE TITLE
Question: How to increase apiRequestContext time to avoid Error: apiRequestContext.get: Request timed out after 30000ms

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#22866]
**Question**: How to increase apiRequestContext time to avoid **Error: apiRequestContext.get: Request timed out after 30000ms**
I am getting the above-mentioned error for my TC which is calling the API Function to delete the data after theTest Case execution is done.
I want to increase the apiRequestContext timeout. How can we increase that?

**Comment by pavelfeldman** [comment]
Did you try https://playwright.dev/docs/next/api/class-apirequestcontext#api-request-context-get-option-timeout ?

**Comment by AkkyLohana90** [comment]
Hello pavelfeldman,
Yes, I one through the above shared solution but not getting where we have to pass 0 - to disable timeout.
Could you please give an example?

**Comment by pavelfeldman** [comment]
```js
await apiRequestContext.head(url, { timeout: 0 });
```
