### ISSUE TITLE
[BUG] Error splitting fixtures into multiple files

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#22867]
I am reporting as a bug, although it might be my bad code, but could not figure it out... Might be useful for future searches. 

I am trying to split my fixtures into multiple files. 
I get an error pointing to the base.extend 
Error: test.extend() accepts fixtures object, not a test object.
Did you mean to call test._extendTest()?

### System info
- Playwright Version: [v1.33]
- Operating System: [ macOS 13.3]
- Browser: [ Chromium]
- Other info:

### Source code
```
//fake-time.fixtures.ts
import { test as base } from '@playwright/test';

export type FakeTimeFixtures = {
  useFakeTime: (dateTime: string) => Promise<void>
};

export const fakeTimeFixtures = base.extend<FakeTimeFixtures>({
  useFakeTime: async ({ page }, use) => {
    const addFakeTimeScript = async (dateTime: string): Promise<void> => {
      const fakeNow = new Date(dateTime).valueOf();
//implementation code
      }`);  
    };
    await use(addFakeTimeScript);
  }
});

//fixtures.ts

import { test as base } from '@playwright/test';
import { fakeTimeFixtures, FakeTimeFixtures } from './fake-time.fixtures.ts';

type MyFixtures = {
  someFixture: (component: Locator) => Promise<string>;
};

export const test = base.extend<FakeTimeFixtures & MyFixtures> ({
...fakeTimeFixtures
someFixture: // implementation of the fixture
});

export { expect } from '@playwright/test';
```

I am not even sure if it is a TS or a PW error. Any idea?

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/Tallyb/pw-fixtures-error ]

**Steps**
- npx playwright test

**Expected**
Tests should run

**Actual**
error message as above

**Comment by Tallyb** [comment]
Response given by @mxschmitt on discord: 

You cannot put the return value of extend into extend again. You need to do this instead:

The following line: 
```
export const fakeTimeFixtures = base.extend<FakeTimeFixtures>({
```
should be: 
```
export const fakeTimeFixtures: Parameters<typeof base.extend<FakeTimeFixtures>>[0] = ({
 ``` 

So the full export for easy copy & paste: 

```
export const fakeTimeFixtures: Parameters<typeof base.extend<FakeTimeFixtures>>[0] = ({
  useFakeTime: async ({ page }, use) => {
    const addFakeTimeScript = async (dateTime: string): Promise<void> => {
   // implementation goes here
  };
    await use(addFakeTimeScript);
  }
});
```

**Comment by LayZeeDK** [comment]
It's now possible to extend merged tests so they can be composed as we see fit 😊
