### ISSUE TITLE
[BUG][Firefox] The CAD Model cannot be loaded in playwright firefox.

### ISSUE THREAD

**Issue by hejing10** [microsoft/playwright#22861]
### System info
- Playwright Version: [v1.33]
- Operating System: [Windows 10]
- Browser: [Firefox]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

```js
// playwright.config.ts
  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        browserName: 'chromium',
        viewport: { width: 1280, height: 720 }
      }
    },
    {
      name: 'edge',
      use: {
        browserName: 'chromium',
        channel: 'msedge'
      }
    },
    {
      name: 'webkit',
      use: {
        browserName: 'webkit'
      }
    },
    {
      name: 'firefox',
      use: {
        browserName: 'firefox'
      }
    }
  ],
```

**Steps**
When I launch the Firefox that installed in my computer (the installation package is downloaded from the Firefox official website) and manually test the CAD model loaded in Firefox, the CAD can be loaded successfully. 
Then I try to run the automated test using playwright firefox, it is observed that the  CAD model cannot be loaded.
In Playwright Chromium, the CAD can be loaded.
In Playwright Webkit on Mac OS , the CAD also can be loaded.

**Expected**

The CAD model should be loaded successfully.
![image](https://user-images.githubusercontent.com/131326377/236600502-7726955e-2468-483d-b5b8-a17292ffa960.png)

**Actual**

In playwright firefox, the CAD model cannot be loaded. And the console report this error. 
![image](https://user-images.githubusercontent.com/131326377/236600474-0682edb4-4e78-4030-be4d-02b7508f5bf2.png)

**Comment by pavelfeldman** [comment]
Are you using some native plugins to render CAD in Firefox? Playwright does not support those.
