### ISSUE TITLE
[Feature] routeFromHar should also apply to apiRequestContext

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#22869]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Currently for [routeFromHar](https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har) 
If we turn on the option `update` , it will record all the requests in side browserContext including apiRequestContext into har file. 

However, when we turn off, it intercepts all the requests except apiRequestContext.

It is not symmetrical and makes trouble for teams which need fully simulation on the network in both browser side and node side.

Did some investigation:
when recording har, this PR https://github.com/microsoft/playwright/pull/11502 added the apiRequestContext into trace
when replaying har, Playwright is done by the [`Fetch`](https://chromedevtools.github.io/devtools-protocol/tot/Fetch) domain of chrome devtool protocol, but apiRequestContext is implemented by native `http(s)` module of nodejs, which obviously cannot be mainipulated by CDP events.

**Comment by thomasrepnik** [comment]
We have actually the same problem, which makes playwright unusuable for certain tests. 
We need to make some PUT call prior to the test, which needs to be recorded and replayed. The recording works, but the request is never replayed. 

```
//This request is getting recorded but never replayed
const putResponse= await page.request.put('http://some.url/v1/testdata', {
        data: {
            isManager: false
        }
    })

const putResponseBody= await putResponse.json();

//Here we need the ID of the recorded request in order to proceed with the test
await page.goto(`http://localhost:3000#my-location=%2Fusermanagement%2F${putResponseBody.userId}`);

```

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
