### ISSUE TITLE
[BUG] UI Mode No tests found but TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by MarlezePotgieter** [microsoft/playwright#22876]
### System info
- Playwright Version: 1.33.0
- Operating System: Mac OS Ventura 13.1 
- Browser: All
- Other info: Updated from 1.29.x Playwright version to 1.33.0 

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```
import type { PlaywrightTestConfig } from '@playwright/test';
// import { devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// eslint-disable-next-line @typescript-eslint/no-var-requires
require('dotenv').config({ path: './.env.local' });

console.log('BASE_URL', process.env.BASE_URL);
console.log('CI', process.env.CI);
console.log('process.env.BUILD_ENVIRONMENT', process.env.BUILD_ENVIRONMENT);

const config: PlaywrightTestConfig = {
  testDir: './tests/functional',
  /* ignore SIT (kitchen sink) tests if running against prod env */
  testIgnore: process.env.BUILD_ENVIRONMENT === 'prod' ? 'SIT/*' : '',
  /* Maximum time one test can run for. */
  timeout: 30 * 1000,
  expect: {
    timeout: 5000
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html', { open: 'never' }]],
  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'yarn dev',
    port: 3000,
    reuseExistingServer: true
  },
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:3000',
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    httpCredentials: {
      username: process.env.BASIC_AUTH_USER as string,
      password: process.env.BASIC_AUTH_PASSWORD as string
    }
  },
  /* Configure projects for major browsers */
  // TODO: determine appropriate strategy for envs
  projects: [
    // {
    //   name: 'chromium',
    //   use: {
    //     ...devices['Desktop Chrome']
    //   }
    // },
    // {
    //   name: 'firefox',
    //   use: {
    //     ...devices['Desktop Firefox']
    //   }
    // },
    // {
    //   name: 'webkit',
    //   use: {
    //     ...devices['Desktop Safari']
    //   }
    // },
    // /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5']
    //   }
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 13']
    //   }
    // },
    // {
    //   name: 'Mobile Safari Pro Max',
    //   use: {
    //     ...devices['iPhone 13 Pro Max']
    //   }
    // },
    // {
    //   name: 'Mobile Safari ipad portrait',
    //   use: {
    //     ...devices['iPad (gen 7)']
    //   }
    // },
    // /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: {
    //     channel: 'msedge'
    //   }
    // },
    {
      name: 'Google Chrome',
      use: {
        channel: 'chrome'
      }
    }
  ],
  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  outputDir: 'test-results/'
};

export default config;

```

**Test file (self-contained)**

```
import { Locator, Page } from '@playwright/test';

export class NotFoundPage {
  readonly page: Page;
  readonly pageGridDiv: Locator;
  readonly pageHeading: Locator;
  readonly pageParagraph: Locator;
  readonly pageButton: Locator;

  constructor(page: Page) {
    this.page = page;
    this.pageGridDiv = page.locator('[data-testid="404PageGrid"]');
    this.pageHeading = page.getByTestId('404heading');
    this.pageParagraph = page.getByTestId('404paragraph');
    this.pageButton = page.getByTestId('404returnHome');
  }
  async goto() {
    await this.page.goto('http://localhost:3000/null/');
  }
}

//seperate file test file: 

import { test, expect } from '@playwright/test';
import { NotFoundPage } from './model/NoFoundPage';

test('Verify 404 page components are visible', async ({ page }) => {
  const notFoundPage = new NotFoundPage(page);
  await notFoundPage.goto();
  await expect(notFoundPage.pageGridDiv).toBeVisible();
  await expect(notFoundPage.pageHeading).toBeVisible();
  await expect(notFoundPage.pageParagraph).toBeVisible();
});

test('Verify Go back home button return"', async ({ page }) => {
  const notFoundPage = new NotFoundPage(page);
  await notFoundPage.goto();
  const returnHomePromise = page.waitForEvent('requestfinished');
  await notFoundPage.pageButton.click();
  await expect(page).toHaveURL('http://localhost:3000/');
  await returnHomePromise;
});

```

**Steps**
- [Updated playwright from 1.29.x. to 1.33.0]
- [npx playwright test --ui]

**Expected**

[Expecting UI mode to open and show my tests]

**Actual**

[UI Mode opens fine, but I can't see any of my tests -> displays "no tests".  However if I run the tests using Visual studio Test Explorer (using the play button), they run fine & all expected tests are identified.  
Also when I run our command yarn test:functional all tests are run fine as well.
Error in terminal:
➜ website git:(dev) npx playwright test --ui
BASE_URL https://sit.org.au/
CI undefined
process.env.BUILD_ENVIRONMENT sit

BASE_URL https://sit.org.au/
CI undefined
process.env.BUILD_ENVIRONMENT sit
Error: TypeError: Cannot read properties of undefined (reading 'source')
    at http://localhost:54477/trace/uiMode.79da54b1.js:1:7954
    at Array.map (<anonymous>)
    at Y (http://localhost:54477/trace/uiMode.79da54b1.js:1:7924)
    at Pe._parseProject (http://localhost:54477/trace/uiMode.79da54b1.js:1:5251)
    at Pe._onBegin (http://localhost:54477/trace/uiMode.79da54b1.js:1:2836)
    at Pe.dispatch (http://localhost:54477/trace/uiMode.79da54b1.js:1:2003)
    at window.dispatch (http://localhost:54477/trace/uiMode.79da54b1.js:3:354)
    at eval (eval at evaluate (:197:30), <anonymous>:2:10)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)Error: TypeError: Cannot read properties of undefined (reading 'configFile')
    at te (http://localhost:54477/trace/uiMode.79da54b1.js:1:10800)
    at re (http://localhost:54477/trace/uiMode.79da54b1.js:2:4912)
    at X (http://localhost:54477/trace/uiMode.79da54b1.js:2:5004)
    at Object.onEnd (http://localhost:54477/trace/uiMode.79da54b1.js:2:5226)
    at Pe._onEnd (http://localhost:54477/trace/uiMode.79da54b1.js:1:4856)
    at Pe.dispatch (http://localhost:54477/trace/uiMode.79da54b1.js:1:2472)
    at window.dispatch (http://localhost:54477/trace/uiMode.79da54b1.js:3:354)
    at eval (eval at evaluate (:197:30), <anonymous>:2:10)
    at UtilityScript.evaluate (<anonymous>:199:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)]

**Comment by pavelfeldman** [comment]
Are you running --ui in the same folder where your config file is? Or do you pass -c <path_to_config>? Having something we could run locally would help identifying the issue.

**Comment by MarlezePotgieter** [comment]
Hi, I am running the --ui in the same folder so not passing any -c along with it.  I have asked if we can share the repo but this will include our whole product repo as well, I will chat with the devs to see if we can pull some parts out into a seperate repo.  Alternatively I could maybe make a video, would that help you?

**Comment by pavelfeldman** [comment]
I don't think the video will help much. Could you try bisecting it in a way that you remove sources half after half and see which one triggers it? Same goes for config, remove the options and re-add them until you find the one that makes it appear?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
