### ISSUE TITLE
[Feature] Support enable property on webserver

### ISSUE THREAD

**Issue by coryhouse** [microsoft/playwright#22871]
I'd like to be able to enable/disable the webserver for different types of tests.

## Example use case
- I don't need the webserver when running Playwright against a deployed site.
- I need the webserver when running Playwright locally.

## I'd like to do this

```js
  webServer: {
    command: 'npm run start',
    url: 'http://127.0.0.1:3000',
    enable: process.env.ENABLE_PLAYWRIGHT_WEBSERVER === Y,
  },
```

It would also be nice to be able to enable/disable the webserver via a command line flag.

```
npx playwright test --enable-webserver Y

**Comment by pavelfeldman** [comment]
@coryhouse :wave: 

Config is JavaScript, will this work for you?

```js
webServer: process.env.ENABLE_PLAYWRIGHT_WEBSERVER ? {
    command: 'npm run start',
    url: 'http://127.0.0.1:3000',
} : undefined,

**Comment by coryhouse** [comment]
Ah! Great idea. I should've thought of that. Thanks!

**Comment by samuelstein** [comment]
great workaround but it won't work with multiple webservers, right?
