### ISSUE TITLE
[BUG] Video traces not working since 1.30.0

### ISSUE THREAD

**Issue by R4cOOn** [microsoft/playwright#22881]
### System info
- Playwright Version: 1.30.0 and newer
- Operating System: Windows 11, Official Playwright Jammy image
- Browser: Chromium
- Other info: Problem happens locally on Wndows 11 and on the CI on a GitLab runner running the offical Playwright Jammy image

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      reporter: [
        ["html"]
      ],
      use: {
        headless: false, //Running this headless decreases the speed of the tests by 5-6x
        viewport: { width: 1280, height: 720 },
        video: "on",
        screenshot: "on",
        trace: "on",
      },
},
    },
});
```

**Steps**

Running a simple test on v1.29.2 creates a snapshot, a trace and a video.  
Since version 1.30.0 the exact same code won't create the video anymore.  
The latest version 1.33.0 still won't create a video.

**Expected**

Video is created on version 1.30.0 and later

**Actual**

No video since version 1.29.2 (latest version where it's working).

**Comment by pavelfeldman** [comment]
Our video tests pass, please follow the issue template to file something we can reproduce. Also, it is not recommended to have all three enabled, you should only use trace: on in the modern setting, it is better than the rest.
