### ISSUE TITLE
[BUG] Negative assertion not working

### ISSUE THREAD

**Issue by LisBerndt** [microsoft/playwright#22882]
### System info
- Playwright Version: v1.33
- Operating System: Windows 10
- Browser: Chromium

While for this 
![image](https://user-images.githubusercontent.com/43057926/236813135-84e363e4-5755-4b95-ba57-40c2ce40d692.png)
this
```ts
import { expect } from "@playwright/test";
import { config } from "dotenv";
import { multiContextTest as test } from "fixtures/base";

...
test.describe("foo", () => {
 test.beforeAll(async ({ adminPage }) => {
...
})
test("bar", async ({ clientPage }) => {
await expect(
      clientPage.locator("xpath=(//P)[2]")
    ).toContainText('Keine Datn vorhanden');
})})

```
works:  
![image](https://user-images.githubusercontent.com/43057926/236813376-62c5fe1c-6071-43e2-9b8f-4f07b3a48f45.png)

this 

```ts
   await expect(
      clientPage.locator("xpath=(//P)[2]")
    ).not.toContainText('Keine Daten vorhanden');
```
does not work as expected; test success.

**Comment by pavelfeldman** [comment]
That's because at some point in time, this selector did not have that text content (was empty) and assertion passed immediately. If you have a repro scenario where assertion fails, please follow the issue template and file something we can reproduce locally.
