### ISSUE TITLE
[REGRESSION]: DRM videos not playing anymore after 1.28 version

### ISSUE THREAD

**Issue by aferrante72** [microsoft/playwright#22894]
**Context:**
- GOOD Playwright Version: 1.27
- BAD Playwright Version: 1.28 or older
- Operating System: Windows 10 and Mac OS Ventura 13.3.1
- Extra: 

**Code Snippet**

```javascript
// example.spec.ts
import { test, expect } from '@playwright/test';

test('Demo DRM', async ({ page })=>{
    await page.goto('https://bitmovin.com/demos/drm')
    await expect(page.locator('#available-drm-systems')).not.toHaveText('No DRM')
    # wait just to allow user to visually check
    await page.waitForTimeout(5000)
  });

//playwright.config.ts or playwright.config.js
...
{
      name: 'Google Chrome',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        headless: false
      },    
    },
...
```

**Describe the bug**

Using playwright 1.27 the DRM content plays successfully using stock chrome and with --headed option. After 1.28 release this does not work anymore, both on windows and mac. 
Same problem happens with robotframework-browser library, newer version (which contains newer playwright version) is not working anymore. Sorry I do not have a ready example for robot, as I tried in this case within customer project code.
Tried on two company laptops (windows 10 and Macbook Pro OS Ventura 13.3.1) and one personal PC desktop with Windows 10. 
Chrome version is 113.0.5672.63.
The above snippet is a simple test to check whether widevine support is detected or not on browser. Manually opening the browser and going to the url works always in both Operating Systems. Playwright works with 1.27 but shows no DRM in 1.28.

**Comment by pavelfeldman** [comment]
It looks like Chrome no longer allows DRM unless it can update its components automatically on startup. It probably wants DRM system to always be fresh. You can work around it via passing the following option in your playwright config (or launch call):

```js
  launchOptions: {
    ...
    ignoreDefaultArgs: ['--disable-component-update'],
    ...
  },
```

Your docker version probably works because the Chrome that is installed there is old.

**Comment by aferrante72** [comment]
Thanks it works, i actually thought about trying that ignoreDeafaultComponents, but there were so many and did not know which one :).

**Comment by aferrante72** [comment]
I guess same is with robotframework browser, just passing the ignoreDefaultArgs=['--disable-component-update'] to the New Browser keyword

**Comment by sky-ricardotavares** [comment]
Has anyone managed to test with **headed** mode?

**Comment by zotune** [comment]
Just a note on this that using official chrome browser solves this (needs to be installed):
`use: {
    channel: 'chrome',
  },`
