### ISSUE TITLE
[Feature] page.on('beforeload')

### ISSUE THREAD

**Issue by xsjcTony** [microsoft/playwright#22892]
Let me explain my use case. I'm using `Redux` to manage my global state, however, I need to inject some data into the initial state before the page loads for testing.

Here's how my store looks like:
```ts
// redux store
// this `initialState` will be used as the default state
const initialState: StoreState = (window.PLAYWRIGHT && window.initialStoreState) ||
  {
    data: { /* data here is required to stay on the page */ }
  };
```

However, when I'm trying to inject it using `page.evaluate`, it seems not working since the lifecycle of visiting a page. Let me explain through.

**Below code is in a `page model`**, hence `this.page` will be used

---
## Attempt 1
run `page.evaluate()` before `page.goto()`
```ts
const reduxState = { data: { /* mock data */ } };

await this.page.addInitScript('window.PLAYWRIGHT = true;');

await this.page.evaluate(
  (reduxState) => { window.initialStoreState = reduxState; },
  reduxState
);

await this.page.goto( '/test');
```
But unfortunately `window.initialStoreState` is wiped out after URL changed by `page.goto()`

---
## Attempt 2
run `page.evaluate()` when `page.on('domcontentloaded')`
```ts
const reduxState = { data: { /* mock data */ } };

await this.page.addInitScript('window.PLAYWRIGHT = true;');

this.page.on('domcontentloaded', (page) => {
  await page.evaluate(
    (reduxState) => { window.initialStoreState = reduxState; },
    reduxState
  );
});

await this.page.goto( '/test');
```
This won't work either since redux store seems to be loading the `initialStoreState` before this `evaluate` fires, as a result, it doesn't work.

---

## Current workaround
Currently I have to stingify the object in `page.addInitScript()`, which is less ideal
```ts
const reduxState = { data: { /* mock data */ } };

await this.page.addInitScript(
  (reduxState) => {
    window.PLAYWRIGHT = true;
    window.initialStoreState= reduxState;
  },
  reduxState
);
```
This temporarily resolves my need, but it's definitely the wrong way to do so.

---

# Feature Request
We should have a `page.on('beforeload')` to let us do something before page loads, like:
```ts
this.page.on('beforeload', (page) => { /* do something ... */ });
```

In `Cypress` (I just migrated to `Playwright` these days), I can easily achieve things like this:
```ts
const reduxState = { data: { /* mock data */ } };

cy.visit('/eligibility', {
  onBeforeLoad: (window) => {
    window.initialStoreState = reduxState;
  }
);

**Comment by xsjcTony** [comment]
Correct me if it's the right way to do so, since in the documentation, there's no function version of usage for `page.addInitScript()`, so I'm not sure if `page.addInitScript()` is equivalent to my idea `page.on('beforeload')`

**Comment by pavelfeldman** [comment]
> Correct me if it's the right way to do so, since in the documentation, there's no function version of usage for page.addInitScript(), so I'm not sure if page.addInitScript() is equivalent to my idea page.on('beforeload')

It pretty much is.

> This temporarily resolves my need, but it's definitely the wrong way to do so.

It is actually what we recommend, the body of the `addInitScript` callback will be called with the parameter you passed every time new document is created (after the navigation commits, but before anything on that page runs).

**Comment by xsjcTony** [comment]
Great. I'll leave the implementation like that then.

To be said, the documentation seems need to be updated for `page.addInitScript()`. It only showed the string version and then I thought it may have some limitation that it's string only instead of can be used like `page.evaluate()`. It took me some time to actually find it out (by `dts` file)🤣

**Comment by pavelfeldman** [comment]
I'll add a snippet to the docs...
