### ISSUE TITLE
[BUG] VS Code extension: debugger doesn't pause at breakpoints 

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#22901]
**Context:**
- Playwright Version: 1.33.0
- Operating System: macOS
- Node.js version: 16.3.0
- Visual Studio Code version: 1.77.3
- Playwright for VSCode extension version: 1.0.10
- Browser: N/A
- Extra:

**Code Snippet**

I've just created a brand new Playwright project using `yarn create playwright`. When I add a breakpoint and run "Debug Test", the debugger does not pause at my breakpoint:

https://github.com/microsoft/playwright/assets/921609/f28ecc51-07b3-4f04-9c9c-a9dfa29ee435

**Comment by pavelfeldman** [comment]
I can't reproduce this, not sure what's going on here. Does regular debugging work in this VS Code instance?

**Comment by OliverJAsh** [comment]
I just tested and regular debugging seems to work fine.

How can I debug this? Presumably it's an issue with source maps.

**Comment by pavelfeldman** [comment]
I assume the `debugger;` statement works? If this is a source maps issue, debugger statement will reveal the compiled code instead of this one. We would to repro this to make progress on it - the use case is so simple that we would have seen it reported by now if it reproduced for others...

**Comment by OliverJAsh** [comment]
`debugger` works fine:


https://github.com/microsoft/playwright/assets/921609/5e637622-66c4-4d97-9c7f-d597117dcdb2


But as soon as I remove it, breakpoints stop working:

https://github.com/microsoft/playwright/assets/921609/29228cad-f262-423e-8eac-aac051f4d7b0



I totally appreciate you need a reduced test case to reproduce and debug this but I'm not sure what else I can do to reduce this further, given this is happening on the barebones test file created by `yarn create playwright`.

**Comment by pavelfeldman** [comment]
The first video did not attach unfortunately.

> given this is happening on the barebones test file created by yarn create playwright

Exactly, there isn't much we can ask from you... You could try installing code-insiders side by side with code to see if this could be related to some global debugging settings of your vscode...

**Comment by OliverJAsh** [comment]
> The first video did not attach unfortunately.

I've tried re-uploading it. How about now?

> You could try installing code-insiders side by side with code to see if this could be related to some global debugging settings of your vscode...

I ran the following commands to create a fresh instance of VS Code, with no user/workspace settings and no other extensions:

```console
$ code --user-data-dir ~/Desktop/vscode-data-dir --extensions-dir ~/Desktop/vscode-extensions-dir --install-extension ms-playwright.playwright
$ code --user-data-dir ~/Desktop/vscode-data-dir --extensions-dir ~/Desktop/vscode-extensions-dir .
```

I was still able to reproduce the issue when doing so.

**Comment by pavelfeldman** [comment]
I tried your code on macOS 13.3 and Ubuntu 22 (both with the latest 1.78.1, Node 16) and it stops on the breakpoints just fine for me. I have no idea about why this is happening.

According to your video, debugging session starts successfully, `debugger;` statement resolves to your file, which means that event source maps are working. So for some reason in a valid debugging session with proper sources breakpoints are not resolved. This is VS Code core functionality, not even Playwright. This might happen if your breakpoint is set in a file under `node_modules` or is git ignored. VS Code is going to save resources and not resolve source-mapped breakpoints in the files under those locations.

**Comment by OliverJAsh** [comment]
🤦  I just noticed this in the console:

https://github.com/microsoft/vscode-js-debug/issues/1017

> Some breakpoints might not work in your version of Node.js. We recommend upgrading for the latest bug, performance, and security fixes. Details: https://aka.ms/AAcsvqm

<img width="1136" alt="image" src="https://github.com/microsoft/playwright/assets/921609/f897ce67-1ce5-4dab-8da3-91203c531f39">
