### ISSUE TITLE
[BUG] Global setup file doesn't use testIdAttribute from the config

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#22918]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**
```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  globalSetup: require.resolve('./global-setup'),
  use: {
    testIdAttribute: 'data-test-id',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
// global-setup.ts
import { chromium, expect } from '@playwright/test';

async function globalSetup() {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();
  try {
    await context.tracing.start({ screenshots: true, snapshots: true });
    await page.setContent(
      `<input id='checkbox' data-test-id="test" type='checkbox'></input>`
    );
    await expect(page.getByTestId('test')).toBeVisible(); //unable to find it
    await context.tracing.stop({
      path: './test-results/setup-trace.zip',
    });
    await browser.close();
  } catch (error) {
    await context.tracing.stop({
      path: './test-results/failed-setup-trace.zip',
    });
    await browser.close();
    throw error;
  }
}

export default globalSetup;

```

**Steps**
- [Run the test]
- [...]

**Expected**

The global setup should respect the testIdAttribute set in the config file.

**Actual**

The global setup does not pick up the testIdAttribute set in the config file.

**Comment by pavelfeldman** [comment]
:wave: @Nav-2d while we are looking at it, did you think about migrating from the legacy global setup to the setup project? It'll give you traces, data-testid, all for free...

**Comment by Nav-2d** [comment]
Hi @pavelfeldman - Thanks for looking into this. Few things:

1. Upon further thinking I realized that I actually need `globalTeardown` instead of `globalSetup`. My usecase is that after a test run sometimes when there are failures then few records are left over which I want to clean up. So, in my case, globalTeardown would be a right choice and I assume data-test-id issue will still persist there.

2. I am actually making use of new project dependencies i.e. setup project to login into different account and storing the states in json files. So for the time being I can rely on it to clean up the records in the same file. Thanks for your suggestion.

Ideally I would like to move to globalTeardown but I do have a workaround for the time being using new setup project as your mentioned.

**Comment by pavelfeldman** [comment]
1.34 will have the reverse dependencies (teardown projects), which should work for you even better.

**Comment by Nav-2d** [comment]
Perfect timing. I can wait for 1.34 then. 

Please feel free to close this issue then if you think fixing the issue for legacy global setup and teardown is not necessary/it will be deprecated.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
