### ISSUE TITLE
[REGRESSION]: getByLabel doesn't work anymore in some cases

### ISSUE THREAD

**Issue by gvillenave** [microsoft/playwright#22915]
**Context:**
- GOOD Playwright Version: 1.29.2
- BAD Playwright Version: 1.33.0
- Operating System: Mac
- Extra: 

**Code Snippet**

```html
<div>
    <div>
        <label for="foo">Foo Label</label>
    </div>
    <div>
        <span>
            <input type="text" id="foo" name="bar" />
        </span>
    </div>
</div>
```

```javascript
await expect(page.getByLabel("Foo Label")).toBeVisible();
```

**Describe the bug**

The example above used to work in 1.29 but doesn't after upgrading to 1.33. I'm not sure if it's due to the fact that the input is not nested in the label element, or that there's no aria-label? Unfortunately we don't control the form code, so we can't fix it but it does fail our automation. Switching to use ID based locator works, but it's not ideal long term.

**Comment by pavelfeldman** [comment]
This works for me on 1.33:

```js
import { test, expect } from '@playwright/test';

test('issue 22915', async ({ page }) => {
  await page.setContent(`
    <div>
      <div>
          <label for="foo">Foo Label</label>
      </div>
      <div>
          <span>
              <input type="text" id="foo" name="bar" />
          </span>
      </div>
    </div>
  `);
  await expect(page.getByLabel('Foo Label')).toBeVisible();
});
```

**Comment by gvillenave** [comment]
@pavelfeldman I think I found the issue. The form we're testing against as an `aria-label` attribute on the input element with no value. When I run this repro without the `aria-label` attribute present it passes, but if I add it as below it fails.

```
import { test, expect } from "@playwright/test";

test("issue 22915", async ({ page }) => {
  await page.setContent(`
    <div>
      <div>
          <label for="foo">Foo Label</label>
      </div>
      <div>
          <span>
              <input type="text" aria-label id="foo" name="bar" />
          </span>
      </div>
    </div>
  `);
  await expect(page.getByLabel("Foo Label")).toBeVisible();
});
```

**Comment by pavelfeldman** [comment]
I can repro this, but that is also an invalid aria-label. I started codegen on your page and it generated this for me:

```js
await expect(page.getByRole('textbox', { name: 'Foo Label' })).toBeVisible();
```

would it work for you as a workaround?

**Comment by gvillenave** [comment]
Yeah unfortunately the HTML comes from a third-party so we can't control it. As a workaround, would you say it's more robust to use the `textbox` role as you suggested above, or do this:
```javascript
await expect(page.locator('id=foo')).toBeVisible();
```

For the long term, should Playwright follow the previous behavior and ignore invalid `aria-label` attributes?
Thanks!

**Comment by pavelfeldman** [comment]
We will check if ignoring it is Ok. `getByRole` is preferred over `id=foo`, especially if you don't control the page. Developer can change id under your feet, but they are unlikely to change this from being input to something else.
