### ISSUE TITLE
[BUG] google openID login fails in headless mode .NET

### ISSUE THREAD

**Issue by fomnus** [microsoft/playwright#22929]
### System info
- Playwright Version: [v1.33]
- Operating System: [Windows 10]
- Browser: [Chrome]
- Other info:

### Source code

```
await Page.GetByRole(AriaRole.Textbox, new() { Name = "Email or phone" }).ClickAsync();
        **await Page.GetByRole(AriaRole.Textbox, new() { Name = "Email or phone" }).FillAsync(_config.GoogleUser);**
        await Page.GetByRole(AriaRole.Button, new() { Name = "Next" }).ClickAsync();
        await Page.GetByRole(AriaRole.Textbox, new() { Name = "Enter your password" }).ClickAsync();
        await Page.GetByRole(AriaRole.Textbox, new() { Name = "Enter your password" }).FillAsync(_config.GooglePassword);
        await Page.GetByRole(AriaRole.Button, new() { Name = "Next" }).ClickAsync();

```

**Steps**
- [Run the test]

**Expected**

the test logs in via google openID

**Actual**

gets stuck on the ** line with a timeout
```
 System.TimeoutException : Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for GetByRole(AriaRole.Textbox, new() { Name = "Email or phone" })
============================================================
```

**Comment by ValorHeart** [comment]
What is shown in the screenshot? Is the page rendered fully like in headed mode? you might have a CORS error in the console?

**Comment by fomnus** [comment]
ah so it seems the login page used in headless mode is different to the page in headed mode
**Headed mode**
"https://accounts.google.com/v3/signin/

**Headless mode**
https://accounts.google.com/InteractiveLogin?

**Comment by fomnus** [comment]
apologies not sure how that would be implemented, the browser options in my runsettings file looks like this

```
<Playwright>
		<BrowserName>chromium</BrowserName>
		<ExpectTimeout>5000</ExpectTimeout>
		<LaunchOptions>
			<Headless>true</Headless>
			<Channel>chrome</Channel>
		</LaunchOptions>
	</Playwright>
```

**Comment by ValorHeart** [comment]
Unfortunately i haven't used Playwright with C#, so I can't assist with that

**Comment by pavelfeldman** [comment]
Google will not let you log in using automated software: https://support.google.com/accounts/answer/7675428?hl=en
