### ISSUE TITLE
Running Playwright tests by Docker can't find the urls[BUG]

### ISSUE THREAD

**Issue by CsillaCsipak** [microsoft/playwright#22926]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:
In local, perfectly working, but if Docker runs my code, it fails at this point, where the urls have to use, which are defined in config files, what can I do? I do not want to hardcode the url everywhere, because I also have got a custom testconfig.ts with different environments: (export const testconfig = { qa: , dev:}) I have copied the necessary files by Docker.
### Source code

```
`Tests/Login.test.ts:4:5 › @Navigate to Login form an login › Open browser ─────────────────────

   Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL
  =========================== logs ===========================
  navigating to "/", waiting until "load"
============================================================
      await page.goto('/');
               });`
```

Same in another test, where I use storagestate to login already and go immediately to the specific url:

```
     await test.step(`Open browser`, async () => {
  await page.goto('/app/#/checkout/step-my-profile');
 });
```

**Config file**
playwright.config.ts
```
const ENV = process.env.ENV;

if (!ENV || ![`qa`, `dev`, `qaApi`, `devApi`].includes(ENV)) {
  console.log(`Please provide a correct environment value`);
  process.exit();

projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        baseURL: testconfig[process.env.ENV],
```

tsconfig.json
```
"compilerOptions": {
      "baseUrl": ".",
```

testconfig.ts
```
export const testconfig = {
    qa: `https://amazon.com/`,
    dev: ``,
```

**Comment by pavelfeldman** [comment]
If you print `testconfig[process.env.ENV]` you'll see that it is empty.

**Comment by CsillaCsipak** [comment]
Do you have solution idea?

**Comment by pavelfeldman** [comment]
You need to make sure you pass the required environment when you run Playwright.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by InduKrish** [comment]
I do face the same issue,

**Comment by natalygoloborodko** [comment]
I'm facing the same issue.
The fun fact is that I've added the logging of Baseurl right before the line with "page.goto", so that I see that env variable is passed, has correct value, etc., but I still receive the same error message: "Error: page.goto: Protocol error (Page.navigate): Cannot navigate to invalid URL"
