### ISSUE TITLE
VS Code extension: allow configuration of the Playwright command

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#22932]
Full reduced test case: https://github.com/OliverJAsh/playwright-vs-code-extension-dotenv-issue

We invoke `playwright test` via [`just`](https://github.com/casey/just). Before `just` runs Playwright, it will load the `.env` file into the environment.

```justfile
set dotenv-load := true

e2e:
    playwright test
```

However, when we run Playwright via the VS Code extension, Playwright is invoked directly as opposed to via `just`, so the `.env` file will not be loaded.

For this reason I would like to propose a new setting to allow configuration of the Playwright command, similar to how the [Jest extension provides a `jestCommandLine` setting](https://github.com/jest-community/vscode-jest/tree/c2958df8e728f48e6c0bd4dd97cf607d529fa07e#jestcommandline). With this setting we would be able to do something like this:

```json
  "playwright.command": "just e2e"
```

**Comment by pavelfeldman** [comment]
- We need to pass command line arguments to playwright. I'm not sure we'll figure out a way that would be universal (some wrappers require -- as a command line arguments separator, others do not).
- We need this intermediate command to form the right process tree so that we could kill the processes gracefully w/o zombies
- We would want to be able to open pipes to the Playwright process through this intermediate runner

I don't think we can expect any wrapper to conform to ^^, so I'd suggest that you have a `playwright.dev.config.ts` that uses dotenv to load the environment and then re-exports the original config.

**Comment by mxschmitt** [comment]
See also here on how to leverage dotenv with Playwright: https://playwright.dev/docs/test-parameterize#env-files

**Comment by samhh** [comment]
That necessitates adding a project dependency that's otherwise unneeded to support a specific editor / development style. I don't believe that's a good precedence for tooling to set if at all possible.

**Comment by pavelfeldman** [comment]
Closing as per my message above as not feasible.

**Comment by OliverJAsh** [comment]
Another reason why we might want to consider this is if you're running Playwright inside of a Docker container for deterministic screenshot snapshots across different environments. Currently it's not possible to use the VS Code extension in this setup, to the best of my knowledge.

**Comment by awydler** [comment]
> Another reason why we might want to consider this is if you're running Playwright inside of a Docker container for deterministic screenshot snapshots across different environments. Currently it's not possible to use the VS Code extension in this setup, to the best of my knowledge.

That's actually exactly the reason I bumped into this issue. Whats the recommended way here, or is this just not supported? Thx

**Comment by alexstroukov** [comment]
Another reason to support this feature to allow better integration with emulators. Anyone using localstack or google/firebase emulators would likely have a test script which spins up the emulators, then runs the e2e tests, then tears it down. e.g.

```
firebase emulators:exec 'playwright test'
```
or 

```
localstack start & localstack wait && playwright test
```

without the ability to change the playwright command im forced to spin up the emulators in a different terminal window and manually clear them after each execution with the debugger.
