### ISSUE TITLE
[Question]: Is ClickASync too fast, or the project too slow? False positive tests

### ISSUE THREAD

**Issue by Philip-DeLuca** [microsoft/playwright#22938]
- Playwright Version:  Playwright.NUnit 1.32.0
- Operating System:  Windows
- .NET version:  .NET 6.0
- Browser:  Chromium
- Programming Language: C#
- Visual Studio 2022

I'm not sure if this warrants for a bug, or perhaps it's just pointing out a flaw in either Playwright or the project I'm working on.

When I'm clicking an element on the page, the element transforms to something different after clicking on it once.  I'm clicking on a AriaRole Link, and used ILocator GetByRole to find it - I used the options to identify the Name of the AriaRole.Link, 

{ Name = "Deposit Date", Exact = true }

After clicking once on this element, the front-end changes the name of this element, by adding an arrow to the end of it.  This changes the name of the element, and therefore should not allow me to click on it again if I'm using the same exact ILocator to try to interact with said element.  The name of the element is now "Deposit Date ", according to the Playwright code generator.

When I run the test with no SloMo, meaning as fast as it could run, I have in the test to click on the element, { Name = "Deposit Date", Exact = true }, twice in a row.  As a result, my test passes.  However, if I run the test with SloMo = 400, the test does not pass.  I'm thinking this is because Playwright executes this ClickAsync method so fast that it will try to click the element twice in the span of less than a second.  As a result, it clicks the second time, and ends up clicking on the element that does not match the ILocator that I have written in the code.  When I have SloMo turned on, it does not recognize the element now, since it had time to change into the name with an arrow at the end of it, and my test then fails.

Now I could add just a WaitForTimeoutAsync method in between these clicks and it should be fine, for this particular instance.

But I am wondering if this type of issue is a bug in Playwright, or is it due to the project loading slower than the execution of code and as a result is giving faulty tests.  

And I am also wondering now at what other points in time are the tests giving false positives like this example.  I may be overthinking the issue at hand though.

If anyone has any tips for this type of scenario, that would be much appreciated.  I don't know Playwright 100% and I'm still learning, so it's possible I may just be misunderstanding something.

Thank you in advance!

**Comment by pavelfeldman** [comment]
Could you provide a snippet of the code so that I could understand it better? Why are you clicking the same locator twice? If you do that, Playwright will click it twice really fast.

**Comment by Philip-DeLuca** [comment]
The element I'm clicking on is the label of a column in a table, and the label itself will change on the Front End after clicking on it once.  Once clicked, it will arrange the data in the table based on that column, in a descending order.  Clicking on it again will change it to an ascending order.  Clicking on it again will no longer arrange the data by that column.  Each time the element is clicked, it will add an arrow pointing upward, or an arrow pointing downward, or have no arrow next to it.  It is representing whether the filter is active, and whether is descending or ascending.

So I noticed that once the element is clicked once, then the label of the column changes because it adds an arrow.  This makes the existing locator not work, or atleast, in theory, should not work.  But if I click on the same locator twice, Playwright will click on that element twice, even though after the first time, it should not technically click on it because the label itself changed, and I had the code set to find the Exact Name.   i.e.:

private ILocator Filter_Table_DepositDate => 
_page.GetByRole(AriaRole.Link, new () { Name = "Deposit Date", Exact = true });

Then the clicking method in the Task I set up later in the code:

await Filter_Table_DepositDate.ClickAsync();

So when I run my test, I wanted the data to be in ascending order, and I'm trying to click on a specific row after arranging the data in ascending order based on the column Deposit Date in the table.  With that said, I need to click on the title of the column twice.

So if I use the previously stated locator, twice, it actually works if there is no SloMo to my test.   Which, for quality assurance, is a little misleading, because it actually clicks it twice so fast that it does not require a new ILocator to locate the new element on the Front End, which is now "Deposit Date ", according to the Playwright code generator, because the element changed by adding an arrow to it to show that the filter is active and in descending order.

When I use SloMo, the test fails if I use that same ILocator twice, because now Playwright doesn't see the Exact Name of "Deposit Date" because the element changed in time before Playwright decided to click right there again.

I guess you kind of answered my question though by saying Playwright will click on the element extremely fast.  My conclusion is that it's almost too fast because it gave me a false test in the sense that I thought using the same ILocator twice would suffice, but when SloMo was turned on (which mimics an actual end-user speed), the test failed.  And I think what was the eye-opener moment for me was when I ran the test in Headed mode, and I clicked the same ILocator twice, and I can visibly see the moment that the element changes, twice, even though the ILocator should technically not work.  It looks deceiving when you see it happen in Headed mode because you can visibly see a Click happen on the element initially (as it should), and then again you see a Click happen on the element but after it changes from the first click (which shouldn't be possible).

This may just be something I have to keep an eye out for in the future.  I appreciate your comment!

**Comment by pavelfeldman** [comment]
I'm sorry, that's too much information for us to process, could you provide a repro (standalone repo with single test file and a short working snippet demonstrating the behavior). Please refer to the BUG template for instructions on how to file those!
