### ISSUE TITLE
[Feature] Add settings to record video only in `headless` mode

### ISSUE THREAD

**Issue by xsjcTony** [microsoft/playwright#22948]
Currently users are only allowed to turn video recording on or off globally, but It will be good to let user has an option whether to record based on test running mode, either in `headless` mode only or `headed` mode only

**Comment by pavelfeldman** [comment]
Playwright config is a JavaScript file, so you can use conditions when you are specifying the values. You can do:

`video: process.env.VIDEO ? 'on' : 'off'`

and then

`VIDEO=1 npx playwright test`

Btw, don't use `video`, only use `trace` - it is strictly better.

**Comment by xsjcTony** [comment]
I definitely agree with you, but since it's a requirement from business...🤣 I had to work around it

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
