### ISSUE TITLE
test.setTimeout() is not working for a test.

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#22954]
### System info
- Playwright Version: [v1.32]
- Operating System: [macOS 13.2.1.]
- Browser: [Chromium]
- Other info:

### Source code

**Test Case:** 

test.only("Test Summary 10", async() =>{
  test.setTimeout(15 * 60 * 1000);
  const browser = await chromium.launch();      
  const context = await browser.newContext();
  const page = await context.newPage();
  const admin = new adminPage(page);
  const system = new systemPage(page);
           
  await admin.goto();
  await page.waitForTimeout(2000);
            
  await system.clickStartCTA();
  await system.clickOnGotItCTA();
  

  await admin.checkNoShowMessage();
  await expect(classroompage.NoShowMessage).toContainText("ABC");

  await system.checkCancelledMessage();
  await expect(system.CancelledMessage).toContainText("abc");

  await system.clickOnCancelledCTA();
  await page.waitForSelector(".sc-jbKcbu.sc-dNLxif.fhBIrT");

});

**Config.ts**

import  {defineConfig}  from '@playwright/test';

export default defineConfig({
  /*
    Timeout for the whole test run in milliseconds
    Sanity tests should be quick and concise
  */
  globalTimeout: process.env.SANITY ? 10 * 60 * 1000 : 30 * 60 * 1000,

  /* Maximum time one test can run for in milliseconds */
  timeout: 45 * 1000,

  /* Failing tests will be retried multiple times until they pass, or until the maximum number of retries is reached */
  retries: 1,

  use: {
    /* Record video only when retrying a test for the first time */
    video: 'on-first-retry',
    /* Headless browser true for CI/CD pipelines */
    headless: process.env.CICD ? true: false,
    /* browserName values =  chromium/firefox/webkit */
    browserName: 'chromium',
  },
  
  projects: [
    {
      name: 'website',
      testDir: './website',
    },
   
  /* Generate html and xml reports */
  reporter: [['html', { open: 'never' }], ['junit', { outputFile: 'playwright-report/test-report.xml' }]],
     
});

**Expected**

The test should wait for total of 15 minute to execute.

**Actual**

But they are getting failed and not waiting for 15 minuites.

Can anyone please help me here. 

Thanks.

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we can reproduce. Your report does not even include the error message, so it is impossible to diagnose!

**Comment by DeeptiSaxena09** [comment]
Okay @pavelfeldman Will follow the template.
