### ISSUE TITLE
[Question] Modifier key results in duplicate key input

### ISSUE THREAD

**Issue by mypchas6fans** [microsoft/playwright#22955]
### System info
- Playwright Version: [v1.33 and v1.32]
- Operating System: [Windows 11, Ubuntu 20]
- Browser: [Chromium]
- Other info:

### Source code

```js
import { test, expect } from '@playwright/test';

test('keyboard', async ({ page }) => {
  // await page.goto('https://www.keyboardtester.com/tester.html');
  // await page.goto('https://keyboard-test.space/');
  // await page.goto('https://en.key-test.ru/');
  // await page.goto('https://www.onlinemictest.com/keyboard-test/');

  await page.goto('https://www.rapidtables.com/tools/notepad.html');
  // await page.goto('https://www.memonotepad.com/');
  // await page.goto('https://justnotepad.com/');
  // await page.goto('https://www.online-notepad.net/');

  await page.waitForLoadState();
  await page.keyboard.press('Shift+r');

  await page.screenshot({ path: 'screenshot1.png' })
  
});


```

I'm not sure if this is a valid bug. Hopefully someone could shed your light on it. Thank you.

We are now testing an internal map tool on web with canvas element, with lots of keyboard shortcut for users.
Unfortunately exposure is not allowed so difficult for reproduction.

The symptom is that when we press Shift plus a character(let's say 'r'), it always triggers Shift+r and then r.

 - Reproducible on Windows 11 desktop, Ubuntu 20 container and Playwright v1.33/1.32(earlier version not tested).
 - NOT reproducible for human user, and step over debug mode. So I guess it's related to keyboard timing.

I tried above sample code on some keyboard test and notepad sites.
 - All the keyboard test sites recorded both Shift key and r key.
 - But all notepad sites only recorded 'r'. This seems related to my scenario. Should they record 'R'?

Thank you.

**Comment by pavelfeldman** [comment]
For that we need a repro scenario please! I.e. a snippet we'll be able to run locally to verify.

**Comment by pavelfeldman** [comment]
```js
test('keyboard', async ({ page }) => {
  await page.goto('https://www.rapidtables.com/tools/notepad.html');
  await page.getByText('I understand').click();
  await page.locator('#area').click();
  await page.locator('#area').press('Shift+R');
  await new Promise(() => {});
});
```

works for me. The page takes very long time to load, but it works as expected.

**Comment by mypchas6fans** [comment]
Thanks but my original description seems somewhat misleading. Now I realized that my issue is kind of shortcut conflict, combined with the nature that Playwright key combo probably brings a small time diff during which only 'r' is down.

I will try to implement a demo page with 'Shift+r' and 'r' does something differently to reproduce this issue.
But close it for now.

**Comment by cheese0409** [comment]
I am facing the same issue, like our page supports both key 'r' and 'shift+r' for different purpose but now 'shift+r' functionality is broken when tested using playwright because it always fires 'r' as well. How did you solve this issue?

> Thanks but my original description seems somewhat misleading. Now I realized that my issue is kind of shortcut conflict, combined with the nature that Playwright key combo probably brings a small time diff during which only 'r' is down.
> 
> I will try to implement a demo page with 'Shift+r' and 'r' does something differently to reproduce this issue. This could be valid but a rare case. Close it for now.
