### ISSUE TITLE
Add ability to calculate code coverage for component tests

### ISSUE THREAD

**Issue by Genial937** [microsoft/playwright#22953]
Is there any package or feature to calculate code coverage for playwright experimental? Most packages I have come across are for normal playwright tests and not experimental.

**Comment by pavelfeldman** [comment]
What do you mean by `playwright experimental`?

**Comment by sand4rt** [comment]
Seems like a duplicate ticket: https://github.com/microsoft/playwright/issues/14511

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/14511.
