### ISSUE TITLE
[BUG] finding locators in Inspector ignores locator options param

### ISSUE THREAD

**Issue by bee-anchor** [microsoft/playwright#22965]
### System info
- Playwright Version: [v1.33.0]
- Operating System: macOS 13.3.1
- Browser: Chromium

### Steps to reproduce

1. Run `npx playwright codegen playwright.dev`
2. Click 'Record' button in Inspector to stop recording
3. In the `Pick locator` box, enter `locator('.navbar__item', {hasText: 'API'})`, notice it does not highlight any elements
4. Now enter `locator('.navbar__item').filter({hasText: 'API'})`, notice it highlights the nav bar 'API' link

**Expected**

Both locators should find an element, and the same element, as they should be equivalent.

**Actual**

The first locator does not find any elements

**Comment by dgozman** [comment]
Fixed by #23034.
