### ISSUE TITLE
[Question]: Are there any alternatives to Selenium Grid for Playwright?

### ISSUE THREAD

**Issue by akrbout** [microsoft/playwright#22961]
### Hello!
According to the [documentation](https://playwright.dev/docs/selenium-grid), Playwright knows how to work with Selenium Grid. In some places Selenium doesn't work for me and I want to find a decent free alternative that I can use with Playwright. Has anyone had a case like this?

**Comment by akrbout** [comment]
I use Python to write tests, what should I do in this case? I have no desire to run tests on GitHub. I would like a solution similar to Selenium Grid, as free and open source. Of course, there's also the Moon project that has the same functionality, but it has a number of limitations in the free version that makes it inappropriate for me.

**Comment by pavelfeldman** [comment]
Got it. This is currently out of scope for Playwright.

**Comment by akrbout** [comment]
> hi @akrbout , I hope there isn't any alternatives till date. if you found anything please post it, thanks

Hi @MananAmin! I found nothing better than just porting my projects from Playwright to Selenium :) my code became faster with Selenium Grid (and in principle everything became better), apparently because it uses json wire protocol and bidi

**Comment by MananAmin** [comment]
ohh, this is scary, we're migrating from selenium to playwright (around 40k + testcases), this is bit scary. and there is good progress on webdriver-bidi. Not sure how much stable it will be in early releases. but looks like google and Mozilla guys actively developing it.
looks like we need to rethink about migration.

**Comment by Sam-H101** [comment]
If there is anyone still looking for a solution for this, I’ll push my latest changes soon, but I have a full grid solution for this that almost perfectly mirrors the selenium grid. In the last 2 years I have made some improvements, but it has 0 issues running 90 web tests concurrently 24/7 

https://github.com/Sam-H101/playwright-remote-orchestrator
