### ISSUE TITLE
[Question]How to enter text in div tag in playwright test tool?

### ISSUE THREAD

**Issue by maheshpatnam** [microsoft/playwright#2297]
I am getting error( Error: Element is not an <input>, <textarea> or [contenteditable] element.) when i try to enter text in div tag 
Here is code.

```js
await page.mainFrame().waitForSelector(sendMesssageBoxSelector);
const sendMessageBox = await page.$(sendMesssageBoxSelector);
await sendMessageBox.click();
await sendMessageBox.fill('hello');
```

**Comment by celeryclub** [comment]
Can you provide an example of what your app code looks like using https://codesandbox.io/ or something similar? Otherwise it's impossible to say why this isn't working.

**Comment by pavelfeldman** [comment]
`page.fill` implies that the element you fill is an `input`, `textarea` or `contentEditable`. It needs to receive and process `input` events in order to be filled. If you'd like to send characters to a non-editable `<div>`, you can say `page.type('hello')`.

**Comment by maheshpatnam** [comment]
Thanks @pavelfeldman @celeryclub  It is working when i use page.type('hello').

**Comment by kachkaev** [comment]
> If you'd like to send characters to a non-editable `<div>`, you can say `page.type('hello')`.

Hmm this does not seem to work in Playwright 1.17. The signature of `page.type(selector, text)` requires at least two arguments. I have used `page.type('body', 'hello')` and it seems to work, but I’m not sure if this is the 100% right way.

**Comment by colemars** [comment]
I would think to use `await page.keyboard.type('Hello')` now.
https://playwright.dev/docs/api/class-keyboard#keyboard-type
