### ISSUE TITLE
[Question] Should cookies work for subdomains?

### ISSUE THREAD

**Issue by winstontsai** [microsoft/playwright#22977]
Playwright: Version 1.33.0

If I set a cookie in the the global Playwright config using domain + path, and the domain does not begin with a leading dot, should that cookie apply to subdomains?

For example, if I have the following in my config:
```javascript
storageState: {cookies: [{name: "abc", value: "true", domain: "mozilla.org", path: "/"}], origins: []}
```
then it seems the browser does not apply the cookie to https://developer.mozilla.org/en-US/, whereas if I set domain to `.mozilla.org` then the browser does apply the cookie. Is this expected?

To be clear, the the cookie is returned by `page.context().cookies()` either way, but the browser does not apply the cookie without a leading dot to the subdomain.

I was under the impression that a leading dot should no longer have an effect, according to [this post](https://stackoverflow.com/questions/9618217/what-does-the-dot-prefix-in-the-cookie-domain-mean). Not sure if this is Playwright behavior or just browser behavior. Maybe someone knows more about this.

Thank you.

**Comment by pavelfeldman** [comment]
This is a bit nuanced. When `Set-Cookie` header has no domain specified, this cookie should only apply to the exact domain match. And if `Set-Cookie` has a domain, no matter if it has a leading `.` or not, it'll apply to the subdomains.

When browsers store cookies, they need to differentiate between those cases. And they use leading `.` for that.

So if your server is saying:

```
Set-Cookie:a=b;domain=foo.com,c=d
```

The cookie store will have the following value:

```js
[
  {
    name: 'c',
    value: 'd',
    domain: 'foo.com',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false,
    sameSite: 'None'
  },
  {
    name: 'a',
    value: 'b',
    domain: '.foo.com',
    path: '/',
    expires: -1,
    httpOnly: false,
    secure: false,
    sameSite: 'None'
  }
]
```

Luckily, this is consistent across the browsers.

**Comment by winstontsai** [comment]
So is the current Playwright behavior around cookies with/without a leading dot in the domain expected then? If so, it might be helpful to add this to the documentation somewhere.
