### ISSUE TITLE
[BUG] Locator.type is flaky

### ISSUE THREAD

**Issue by wingardl** [microsoft/playwright#22970]
### System info
- Playwright Version: 1.23.0
- Operating System:  Windows 11
- Browser: All
- Other info: link to trace of a test run exhibiting this behavior: [trace](https://microsoft-my.sharepoint-df.com/:u:/p/lucywingard/EdvxraY8LPBHm7ifeH-uYzQBACdppMkwAK-BWiXFay7kVw?e=rL9exH)

Example of trying to type "Second paragraph" but only "S" is typed
![image](https://github.com/microsoft/playwright/assets/44914634/d39c1389-664d-4e56-b41c-4a98de01b5ff)

### Source code
Any instance of typing in the browser on a locator object: 
`locator.type("text");`

Not giving a test file because our tests are hard to repro, but we've seen this behavior when trying to type on multiple different locators on different websites. 

**Steps**
- [Run the test]

**Expected**
Text passed to `type` is typed on the locator

**Actual**
Sometimes only a portion of the text passed is actually typed.

**Comment by pavelfeldman** [comment]
It is hard to tell without a repro case, but my guess would be that the app has a bug that does not allow it to process fast typing - the entire string is typed within 250ms, that is 60 characters per second.

**Comment by wingardl** [comment]
mm thanks for the response, I'll try adding a delay and see if we encounter this anymore
