### ISSUE TITLE
[BUG] Address high-severity vulnerabilities in the mcr.microsoft.com/playwright:v1.33.0 docker image

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#22979]
### System info
- Playwright Version: [v1.33]
- Other info: Docker Image `mcr.microsoft.com/playwright:v1.33.0 docker image`

**Steps**
- Pull down the latest docker image by running this command `docker pull mcr.microsoft.com/playwright:v1.33.0`
- Open Docker Desktop
- Click on the Image

**Expected**

The docker image should not have any High-severity vulnerabilities

**Actual**

Docker desktop app reports multiple High-severity vulnerabilities
![2023-05-12_11-06-55](https://github.com/microsoft/playwright/assets/50574915/be1c32d1-c92d-4f59-ad4e-0c18e672c182)

![2023-05-12_11-15-15](https://github.com/microsoft/playwright/assets/50574915/824ada7c-4aba-45a4-9427-cb5b24999cca)

**Comment by pavelfeldman** [comment]
Playwright's docker images are not intended to be used in production, they are only intended to be used in the trusted development environment. They contain tools and utilities that are useful to the developer, including the Playwright itself, that should never be exposed the the potential attacker.
