### ISSUE TITLE
[Feature] Wrap actions in trace viewer/ui mode to a step

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#22980]
I love the trace viewer and in especially in the new UI mode to faster debug the tests. However, the list of actions feel a bit overwhelming if the test has a bunch of actions it could be nightmare to know that action is on which step. So I think it could be better and faster for us to debug if all the actions can be wrapped in their test.step(). Also if test.step() is in the actions list we can click to see the source code in spec.ts too

**Comment by pavelfeldman** [comment]
Great news, this has already been implemented and you'll see it in v1.34 in about a week!
