### ISSUE TITLE
[BUG] docker image playwright/python:v1.33.0 cannot set timezone properly

### ISSUE THREAD

**Issue by s0urcelab** [microsoft/playwright#22981]
### System info
- Playwright Version: v1.33.0
- Operating System: docker image
- Browser: Firefox
- Other info:

**Steps**
- create a dockerfile that base on mcr.microsoft.com/playwright/python:v1.33.0 [example dockerfile](https://github.com/s0urcelab/bili-dynamic-uploader/blob/57af6bf924a82a74b91f243d6fc918a56504be01/Dockerfile)
- set ENV=Asia/Shanghai
- build new image

**Expected**

inside docker container, excute `date`, it should give `Fri May 12 11:50:00 CST 2023` 

**Actual**

excute `date`, it return `Fri May 12 03:50:00 Asia 2023`, i don't think `Asia` is a correct timezone and `03:50:00` is not local time.

**Comment by pavelfeldman** [comment]
Your request in unrelated to Playwright. You also seem to be setting the timezone the wrong way - you probably want something like 
```
ENV TZ=Asia/Shanghai
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

See https://stackoverflow.com/questions/57607381/how-do-i-change-timezone-in-a-docker-container for details.
