### ISSUE TITLE
[QUESTION]: How to pass custom arguments from command line in playwright

### ISSUE THREAD

**Issue by sankarkec** [microsoft/playwright#22986]
### System info
- Playwright Version: 1.32.3
- Operating System: Windows 10

I want to pass my own custom arguments in command line '--suiteName="sanity"' like npx playwright test --config=playwright.config.ts --suiteName="sanity"

Expecting to read using 'process.argv' but when i pass custom arguments i am getting 'error: unknown option '--suiteName=sanity'

How to handle custom arguments from command line in playwright. I have multiple custom arguments which needs to be passed dynamically

**Comment by pavelfeldman** [comment]
We recommend using environment variables to pass parameters to your config and your tests.
