### ISSUE TITLE
[BUG]  nth(0) is not selecting the first element

### ISSUE THREAD

**Issue by ch4r-ch4r** [microsoft/playwright#22990]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [Windows 11, macOS 13.2]
- Browser: [Chromium]
- Other info:

### Source code
``` typescript
import { test } from "@playwright/test";

test("test", async ({ page }) => {
    await page.goto("https://letcode.in/table");

    // This does not locate the first row
    page.getByRole("row").nth(0);

    // Only this locates the first row
    page.getByRole("row").first();
});
```

**Expected**

`page.getByRole("row").nth(0);` shoud locate the first row. 

<img width="1518" alt="image" src="https://github.com/microsoft/playwright/assets/78950093/44d0e892-d499-4a5f-a1ca-c593149d3168">

**Actual**

`page.getByRole("row").nth(0);` does not locate the first row. Only `page.getByRole("row").first();` locates the first row.

<img width="1522" alt="image" src="https://github.com/microsoft/playwright/assets/78950093/6f8b93cb-cb01-49bb-a98a-12ee53945e31">

**Comment by ltsuda** [comment]
`.locator.nth(0)` is `async` so you need to use:

```javascript
const firstRow = await page.getByRole("row").nth(0);
```

https://playwright.dev/docs/api/class-locator#locator-nth

**Comment by pavelfeldman** [comment]
@ltsuda it is actually sync. But it does not do anything without an action.

@ch4r-ch4r you need to perform some action on it (click, assertion, anything), otherwise you just declared a locator.

**Comment by ltsuda** [comment]
@pavelfeldman that's right, I was kind of confused too why I thought one was `async` and the other `sync`.

This is the example of `.nth` in the [documentation](https://playwright.dev/docs/api/class-locator#locator-nth)
```javascript
const banana = await page.getByRole('listitem').nth(2);
```

**Comment by ch4r-ch4r** [comment]
Ahh you're right, `nth(0)` does work. Just confirmed by asserting the text in the header row.

It just threw me off because `nth(1)` actually highlights the element in the browser, while `nth(0)` doesn't highlight the element.

**Comment by pavelfeldman** [comment]
We already have a similar bug about nth(0) not highlighted, closing this.
