### ISSUE TITLE
[Feature] CDPSessions for Web Workers

### ISSUE THREAD

**Issue by iustinpericica** [microsoft/playwright#22992]
I need to create CDP Sessions to Web Workers available in a page. I've seen that you currently support only instances of Page and Frames.

I've seen you already collect Web Workers using `Target.attachedToTarget` https://github.com/microsoft/playwright/blob/e6d8cf9693668e4eb82360551953bda35096aab5/packages/playwright-core/src/server/chromium/crPage.ts#L744 

that returns the sessionId needed to send CDP requests to a specific target.

https://github.com/microsoft/playwright/blob/e6d8cf9693668e4eb82360551953bda35096aab5/packages/playwright-core/src/server/chromium/crConnection.ts#L175

Do you consider adding support for CDP Connection to Web Workers? 
If not, is there a way to send from client raw commands to CDP ( sessionId, method, params ) so maybe I can collect sessionIds separetly and then make use of existing CDP Connection of Playwright.

Thanks!

**Comment by pavelfeldman** [comment]
There are no such plans. What is your use case?

**Comment by pavelfeldman** [comment]
I'll close it as out of scope for Playwright.
