### ISSUE TITLE
[BUG] I am following the Article https://playwright.dev/docs/test-fixtures#overriding-fixtures

### ISSUE THREAD

**Issue by nssidhu** [microsoft/playwright#23001]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**fixture  (self-contained)**

```js

import { test as base, expect } from '@playwright/test';

exports.expect = expect;

export const test = base.extend({

   WebApp: async ({page}, use) => {

        
        await page.waitForURL(baseURL);
        await expect(page).toHaveTitle(/XXXXXX/);
        await page.locator('input:has-text("Login")').click();
        await expect(page).toHaveURL(baseURL + 'LoginOrSignUp',{ timeout: (1000 * 1000) });
        
        //Find Tab(with css = e-tab-text) with text = Login click it
        await page.locator('div[role="toolbar"] >> text=Login').click();
               
        await page.fill("#logInEmail",userName);
        await page.fill('#loginInPassword', password);
        await page.locator('#loginSignIn').click();

        await page.waitForURL("https://XXXXXXXX/")

        await use(WebApp)
   },

});
```

**Steps**
- [Run the test]
- [...]

**Expected**

Should compile, i want to supply the value from test 

test.use({ 
      geolocation : {latitude:67.74959, longitude: -52.19903},
      permissions :['geolocation'],
      project: 'Mobile Chrome',
      userName : 'abced@ghij.com',
      password : 'jgjgkjgkkj',
      baseURL : "XXXXXX"
    });
  

what is the right way of configuring the fixture with variable that will can be overriden from test ?
**Actual**

compiler error

**Comment by pavelfeldman** [comment]
> await use(WebApp)

This line does not sound right, not sure what you want to pass as a result of your fixture, but it is unlikely that you want to pass the fixture definition itself.

**Comment by nssidhu** [comment]
I made the correction and changed it to await use(page), but still running into problem.
ReferenceError: baseURL is not defined
    at Object.WebApp (c:\Users\dev\source\repos\nssidhu\PlaywrightTest\tests\Login.ts:13:31)

**Comment by nssidhu** [comment]
also getting 'cannot find userName' and 'cannot find password' as design time compiler error
