### ISSUE TITLE
[BUG]Playwright  _electron.launch  fails to load browser

### ISSUE THREAD

**Issue by donPab** [microsoft/playwright#23006]
### System info
VSCode Version: 1.78.0 (system setup)
Date: 2023-05-03T20:09:00.748Z
Electron: 22.4.8
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: Yes
playwright --version   Debugger attached.  Version 1.32.1

### Source code
Steps to recreate--
Create a fresh new directory 		(eg: PlaywrightDemo) in VSCode
Clone the Pencil repository-- 	 	https://github.com/evolus/pencil 
     Make sure you are using nodejs 5+ (Pencil development only needs npm for package management.)
Switch to the development branch:  	$ git switch development     to get  3.1.2   (old syntax is checkout)
Install Pencil dependencies:		$ npm install
     Verify prebuilt version of Electron	$ npm start
Patch Pencil\app\   index.js  ~line 94  make DevTools unconditional
    //psg if (devEnable) mainWindow.webContents.openDevTools();
    mainWindow.webContents.openDevTools();
Patch Pencil\app\package.json  scripts  for Windows, change  /  to \\  on "start":  and  "start:dev":

Create  Pencil\app\.tests\play21launch.test.ts -- paste in from attachment 

Install Playwright			$env:PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1   (App uses Electron)
$ npm install --save-dev playwright
$ npm install --save-dev @playwright/test

**Config file**   playwright.config.ts
import { defineConfig, devices } from '@playwright/test';
/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();
/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  timeout: 5 * 60 * 1000,
  testDir: './.tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'list',  //'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
  /* Configure projects for major browsers */
  projects: [
    {
     name: 'chromium',
     use: { ...devices['Desktop Chrome'] },
    },
  ],
});

**Test file (self-contained)**   .tests\play21launch.test.ts
import { test, expect } from '@playwright/test';
import { _electron } from 'playwright';

test('App launches', async ({ page }) => {
    
    console.log("psg-play21launch-b4");
    const app = await _electron.launch({
      args: ['C:\\H_Paul\\Pencil\\pencil-312-05myDev\\pencil\\app\\index.js', '--enable-dev --enable-transparent-visuals'],
      cwd: 'C:\\H_Paul\\Pencil\\pencil-312-05myDev\\pencil\\app\\'
    });
    console.log("psg-play21launch-af");
    await page.pause();

    const window = await app.  firstWindow();
    await expect(await window.title()).toContain('Pencil');
    await app.waitForEvent('window', { timeout: 4 * 59 * 1000 });   // ~~ 4 minutes
    console.log("psg-play21launch-next" + window.title());

    await expect(await window.title()).toContain('PENCIL');

    const count = await  page.getByAltText('menu').count();
    console.log("psg-play21-count"+count);

    const xx = await page.pause();
    await page.screenshot({ path: 'play21launch.png' })  
    await app.close();
});

**Steps**
Run	without Playwright		in package.json, select  Debug  "start":  or  "start:dev":

Run	with Playwright			$npx  playwright  test   play21launch.test.ts
(this gets only blinking-P [for Pencil]   on screen, and never completes)

What is causing Playwright to have these problems?
A)	Main problem is that _electron.launch fails to load the browser and return the app screen.
B)	console.log(‘xxx’);  debugging statements are bypassed or never printed.
C)	electron.asar  Invalid Package
D)	EyeDropper is not defined
When run from package.json ‘scripts’ without Playwright,  none of the above are problems.

**Expected**
but without any of the 3 example drawings which are not included
![Screenshot-ExpectedResults](https://github.com/microsoft/playwright/assets/977056/107b76f4-f018-430c-8aca-35b838713c6b)
[DevTools-without-Playwright.txt](https://github.com/microsoft/playwright/files/11468422/DevTools-without-Playwright.txt)

**Actual**
blinking-P  [Pencil] screen
![Screenshot-ActualResults](https://github.com/microsoft/playwright/assets/977056/16ee8cf8-31f1-4d1c-94c1-00ed4a029f80)
[DevTools-with-Playwright--failing.txt](https://github.com/microsoft/playwright/files/11468425/DevTools-with-Playwright--failing.txt)

**Comment by pavelfeldman** [comment]
Following these steps will take a lot of time from us. If you'd like us to try your repo, please share a link to the branch that we can simply run. Otherwise please provide a reduced test case with a reproducible scenario!

**Comment by donPab** [comment]
Hi Pavel,

Thanks for the initial look-see.  I know it’s a lot.

I am new to GIT.  My repo is only on my laptop.  I do not own https://github.com/evolus/pencil and only read it.

Could you share a link that explains what to do next?

Tkx, Paul

**Comment by pavelfeldman** [comment]
Try searching using public engines and AI chats, they should explain how to fork a repo, create a branch, make a change, etc.! Come back when you have it and we'll take a look!
