### ISSUE TITLE
[Question] How to use a reusable page in a test fixture?

### ISSUE THREAD

**Issue by aoj2** [microsoft/playwright#23014]
Hi, in our test specs we are setting up the Page object in the `beforeAll` hooks, I would like to access that page in an automatic test fixture, but not sure how to achieve that...?  (Note: If using the `page` fixture in the test it works, but that's unfortunately not a viable solution for us atm).

In the example below two separate pages will be created...

Thanks in advance!

```js
// test.spec.js
let page;

  test.beforeAll(async ({ browser }) => {
    page = await browser.newPage();
  });

  test.afterAll(async () => {
    await page.close();
  });

 test("Navigate to page", async () => {
    await page.goto(“/“);
)};
```

```js
// test.fixture.js

exports.test = base.test.extend({
  testFixture: [
    async ({ page }, use, testInfo) => {
      console.log(testInfo.title);
      console.log("Before Each");

      await use();
 
      console.log("After Each");
      await page.evaluate(() => {});
    },
    { scope: "test", auto: true },
  ],
});
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
