### ISSUE TITLE
[BUG] Awaited event listeners do not block script execution

### ISSUE THREAD

**Issue by gskierk** [microsoft/playwright#23018]
### System info
- Playwright Version: v1.33, All?

### Source code

- [x] I provided the exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
// repro.mjs

import { chromium } from '@playwright/test'

const browser = await chromium.launch({
  headless: false
})

const context = await browser.newContext()
const page = await context.newPage()

page.once('load', async page => {
  await page.waitForTimeout(10000)

  console.log('after 10 sec!')
})

await page.goto('https://google.com/')

await page.locator('#L2AGLb').click()
await page.locator('textarea#APjFqb').first().type('Playwright')

await page.locator('.FPdoLc input.gNO89b[name="btnK"]').click()

await page.pause()

```

**Steps**
- `npm install @playwright/test`
- `npx playwright install --with-deps`
- `node repro.mjs`

**Expected**

I expected that the callback in the event listener would block executing the rest of the script for 10 seconds.

**Actual**

The script is executed without waiting for the callback to be fulfilled (a Google search is done first, and a message is logged to the console later).

**Comment**

I wasn't sure if it should be reported as a bug or maybe a feature request, so please adjust the issue. If an actual implementation has to stay untouched, then I believe putting information in the docs for that scenario could be helpful for others. Providing me with a workaround to achieve my goal is also very welcome here.

**Comment by dgozman** [comment]
@gskierk This is an expected behavior. Event listeners do not block any other async processing, that's how JavaScript works.

I'd recommend writing a linear scenario without event listeners in this case. For example:

```ts
await page.goto('https://google.com/')

await page.waitForLoadState('load')
await page.waitForTimeout(10000)

await page.locator('#L2AGLb').click()
```

Also note:
- Waiting for timeout in tests is not recommended, because it's inherently flaky.
- Calling `page.goto()` automatically waits for the `'load'` event, so you don't have to wait for it manually.

Let me know whether this helps.

**Comment by gskierk** [comment]
So we can close the ticket :).
