### ISSUE TITLE
Unable to find 'input'

### ISSUE THREAD

**Issue by jalvespinto** [microsoft/playwright#23029]
I am trying to locate the input bellow, but I cannot manage to do it. 
```
<div id="divChave" class="alinhamentoLinha">
                <div style="float: left; margin-left: 40px; padding-top: 6px; padding-right: 10px; height: auto;">
                    <span class="TituloCampo">Chave de Acesso:</span>
                </div>
                <input name="ctl00$conteudo$txtChaveAcesso" type="text" id="conteudo_txtChaveAcesso" class="input_esquerda" input-mask="ChaveAcesso" style="width:365px;">
            </div>
```
Not even by id ('page.locator("#conteudo_txtChaveAcesso")') I can make it to work. How should I do it?

**Comment by suprunchuk** [comment]
Try attaching more files to this report. It would be nice if you added your code that you are writing. Or created a demo project.

**Comment by jalvespinto** [comment]
@suprunchuk there is not much more than that for now. I just have this html code and I am trying to locate the input.
```
async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        await page.goto(<html_file_path>)
        # trying to locate 'ctl00$conteudo$txtChaveAcesso' input here.
        await browser.close()
```

**Comment by dgozman** [comment]
@jalvespinto Open [test generator](https://playwright.dev/docs/codegen-intro) and try to click on that input. Generator should be able to help with the locator. Let me know if that helps.

**Comment by jalvespinto** [comment]
I am sorry. 'page.locator("#conteudo_txtChaveAcesso")' was finding it.
