### ISSUE TITLE
[Feature] Get report folder from playwright config file.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#23026]
Need a way to get the folder specified in playwright config file. Eg:

```
// playwright config ts file
reporter: [['html', { open: 'never', outputFolder: 'reports/playwright' }]],
```

Folder name extracted would be `reports/playwright`.

**Comment by dgozman** [comment]
@quldude There is no special API for this, but you can always import your config and read values from it. Let me know if that helps.

```ts
const value = await import('./playwright.config').reporter[0][1].outputFolder;
```

**Comment by quldude** [comment]
I found another way:
```
onBegin(config: FullConfig, suite: Suite): void {
      for (const [name, options] of config.reporter) {
        if (name === 'html' && options) {
          this.reportFolder = options.outputFolder;
          break;
        }
      }
...
```

**Comment by dgozman** [comment]
> do you know if I use the environment variable PLAYWRIGHT_HTML_REPORT, will that override the folder mentioned in config file?

`PLAYWRIGHT_HTML_REPORT` will be used instead of the config, but value in the config itself will not be replaced.

**Comment by luqy** [comment]
Same question, if I want to get the name of the project for judgment, how do I get this configuration

**Comment by dgozman** [comment]
@luqy In your custom reporter, call [`suite.project()`](https://playwright.dev/docs/api/class-suite#suite-project). Inside a test, use [`test.info().project`](https://playwright.dev/docs/api/class-testinfo#test-info-project).
