### ISSUE TITLE
[Question]: Is it possible to "record" without clicking the record button when doing codegen?

### ISSUE THREAD

**Issue by grahamannett** [microsoft/playwright#23039]
### Your question

Following https://playwright.dev/python/docs/codegen#record-using-custom-setup it seems like you have to click the record button if using this setup.  
I understand I can exit it early with some coroutine task like
```python
line = await aioconsole.ainput("press a key to exit")
status = await page.evaluate("""() => {playwright.resume()}""")
```

but is it possible to start the recording as soon as the playwright codegen controls start?  It seems like it should be possible given that https://playwright.dev/python/docs/codegen#running-codegen starts recording immediately but I can't seem to figure out how.

Was hoping to avoid having to understand how the `cli.js` works since it seems like I want something akin to this to happen:

```js
async function codegen(options, url, language, outputFile) {
  const {
    context,
    launchOptions,
    contextOptions
  } = await launchContext(options, !!process.env.PWTEST_CLI_HEADLESS, process.env.PWTEST_CLI_EXECUTABLE_PATH);
  await context._enableRecorder({
    language,
    launchOptions,
    contextOptions,
    device: options.device,
    saveStorage: options.saveStorage,
    mode: 'recording',
    outputFile: outputFile ? _path.default.resolve(outputFile) : undefined,
    handleSIGINT: false
  });
  await openPage(context, url);
}
```

**Comment by dgozman** [comment]
@grahamannett This is not possible today. What is your usecase? Please provide more details.

**Comment by grahamannett** [comment]
@dgozman i was hoping to have the browser pop up in some state and then record the next action/step or two and then close it.  It seems possible with the ts/js interface?

**Comment by dgozman** [comment]
> i was hoping to have the browser pop up in some state and then record the next action/step or two and then close it.

This seems clear. However, pressing a "Record" button once does not seem to be a big deal. That means, you have a strong reason to avoid the "Record" button, and I would like to understand it better. Perhaps it would be generally useful to everyone?

> It seems possible with the ts/js interface?

There is no API exposed for this right now, sorry.

**Comment by grahamannett** [comment]
> This seems clear. However, pressing a "Record" button once does not seem to be a big deal.
It's definitely not a huge deal, but I am using playwright as it allows me to create trajectories of some task.  What I am doing at this point is quite a bit different from https://github.com/aidangomez/weblm but the scope is similar and part of my phd research.

I created a web interface to view these trajectories which is similar to the playwright trace viewer but I want to be able to look at the step and say "this is wrong" and then playwright pops up with the state at that step and I click the next correct action and then playwright closes.
Here is the rough app I have so far that I can show a sequence of actions that originally come from playwright (and the screenshot is from playwright) if its helpful to see what I mean (perhaps it clicked the wrong number of people and I want to fix that action): 
![ex1](https://github.com/microsoft/playwright/assets/7343667/823b242e-2bdb-4a8c-b533-07a1b931f006)

I completely understand that this usage is out of scope of playwright but its just an incredibly useful tool and not sure how else I could go about doing this (it is for academic research), if you have any suggestions I am all ears.

> There is no API exposed for this right now, sorry.

Maybe not through the API but seems like the cli.js file already has this ability in some way and I would just need to understand how `context._enableRecorder` from https://github.com/microsoft/playwright/blob/2d3ab74d22c7c9354056c74b631c9720df284454/packages/playwright-core/src/cli/program.ts#L531-L547 works to get something similar?  But avoiding that route would be ideal as having to use js/ts would add a lot of complexity to this compared to just clicking a button.

Any input would be great, and thanks so much!

**Comment by dgozman** [comment]
@grahamannett Thank you for the explanation! Unfortunately, there is no way without calling some private methods in JavaScript like you point out. That said, if you are using playwright for python, I don't think it's possible to make JavaScript calls directly. I'd recommend to click that "Record" button 😄 Sorry for not being of much help!
