### ISSUE TITLE
[Feature] Playwright tracks should collect requests that are still pending when the browser is closed

### ISSUE THREAD

**Issue by CHHome** [microsoft/playwright#23045]
I use playwright traces to  collect requests on website.
`
await context.tracing.start({ screenshots: true, snapshots: true });

//  Other codes

await context.tracing.stop({ path: 'trace.zip' });
`

and  My automation script uses the following code: 
`
     try {
        await page.waitForLoadState('networkidle', {
          timeout: 8000,
        })
      } catch (eroor) {
        browser?.close()
      }
`
However, when the request exceeds 10 seconds and is still in a pending state, my automation script catches an exception and closes the browser

After the script was executed, I checked the playwright traces and did not record any requests that were still pending when the browser was closed
There is no record in the **trace.network** file of requests that were still pending when the browser was closed

I think as long as a request is initiated, Playwright tracks should have a record of the request, regardless of whether it is still pending before the browser is closed, to analyze problems caused by the network

Perhaps this is a bug

More detailed code links：
https://github.com/IDuxFE/wetest/blob/fdd7033a3df74d2d35529a1ae337baf8c52787e7/packages/engine/src/runner.ts#L230

![1684236979377](https://github.com/microsoft/playwright/assets/27943919/536fc35f-7d2e-43e2-89eb-824cc50cf65b)

**Comment by dgozman** [comment]
@CHHome `trace.network` follows the [HAR format](https://en.wikipedia.org/wiki/HAR_(file_format)), so we can only add a single entry when request finishes/fails.

I would recommend to call `context.close()` or even `page.close()` instead of `browser.close()`, so that all unfinished requests are aborted and properly end up in the trace.

**Comment by CHHome** [comment]
But，context will be destroyed when I call context.close()，I can not call context.tracing.stop.This is a conflict.Please tell me what to do, thank you

**Comment by CHHome** [comment]
> @CHHome `trace.network` follows the [HAR format](https://en.wikipedia.org/wiki/HAR_(file_format)), so we can only add a single entry when request finishes/fails.
> 
> I would recommend to call `context.close()` or even `page.close()` instead of `browser.close()`, so that all unfinished requests are aborted and properly end up in the trace.

But，context will be destroyed when I call context.close()，I can not call context.tracing.stop.This is a conflict.Please tell me what to do, thank you

**Comment by dgozman** [comment]
@CHHome Here is an example that closes all pages, so all network request should be aborted, and then saves the trace:

```ts
for (const page of context.pages())
  await page.close();
await context.tracing.stop({ path: 'trace.zip' });
await context.close();
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
