### ISSUE TITLE
I am trying to add a JSDoc to my fixture, Here is an example code that doesn't work for me. Looks like that JSDoc doesn't 'propagate' any further than my test extension.

### ISSUE THREAD

**Issue by Taythugga55** [microsoft/playwright#23053]
I am trying to add a JSDoc to my fixture, Here is an example code that doesn't work for me. Looks like that JSDoc doesn't 'propagate' any further than my test extension.
My JSDoc is only shown when VSCode gives me hint when I type the fixture in the test params, after I'm done typing JSDoc is gone.
Is there a way to fix this?

https://user-images.githubusercontent.com/58426925/218966541-c84dfa95-e09b-4c23-9b7f-ececb7a74baf.mov

```ts
import { expect, test as base, Response } from '@playwright/test';

export const test = base.extend<{
  /**
   * Open myPage and wait for a resource. I would like to see this JSDoc when hovering at fixture in the test
   * @param param0
   * @param use
   */
  openAndWaitForResource: () => Promise<Response>;
}>({
  openAndWaitForResource: async ({ page }, use) => {
    await use(async () => {
      await page.goto('/myPage');
      const response = await page.waitForResponse(/\/api\/resource/g);

      return response;
    });
  },
});

export { expect };

```

_Originally posted by @shwarcu in https://github.com/microsoft/playwright/discussions/20911_

**Comment by dgozman** [comment]
@Taythugga55 This behavior depends on your TypeScript and VSCode combination. On my setup, I can always see the description ("Open myPage and wait for..." in your example), but not the parameters. In your video, it is shown in some cases, but not the others. Unfortunately, we cannot do much about this. I'd recommend asking or filing an issue in vscode instead.
