### ISSUE TITLE
[BUG] Playwright version 1.28 required

### ISSUE THREAD

**Issue by gl-aagostino** [microsoft/playwright#23054]
**Context:**
- Playwright Version: [1.32]
- Operating System: [Ubuntu on WSL]
- Node.js version: [14.6]
- Visual Studio Code version: [1.78.2]
- Playwright for VSCode extension version: [1.0.11]
- Browser: [Chromium]
- Extra: [Windows but using WSL]

**Describe the bug**

For months, seemingly at a random point in time (maybe a VS update..) my playwright stopped working for a specific folder. Every time I opened the extension it said "Playwright version 1.28 or newer required" or something equivalent. I reinstalled everything 100s of times to no avail. 

Finally maybe out of frustration, I literally deleted the entire folder that contained all the playwright tests. I then undid this and, voila. Order was restored. 

So there's something there, maybe in VS code or this extension, that was maybe keeping a cached version value of what was installed. None of the folder contents changed, I literally just deleted it and restored it.

**Comment by dgozman** [comment]
@gl-aagostino Could it be that you had a stale `package-lock.json` that was recreated upon restoring the folder? Unfortunately, we won't be able to diagnose the issue without a reproduction, sorry. If the problems happens again, please file an issue by filling in the "Bug Report" template with a repro, and we'll happily take a look.

**Comment by gl-aagostino** [comment]
@dgozman Nope - literally I deleted the folder and then restored it. I did not reinstall anything (I tried that a million times with no luck). This seems to be more of an extension or VS code issue itself. I don't mind that there's no way for me to reproduce it as I mostly opened this ticket for the sake of other people who may encounter this error. Try deleting/restoring your folders!
