### ISSUE TITLE
[BUG] Element is not clickable in headless mode of Mobile Safari Version

### ISSUE THREAD

**Issue by harshith-aimyth** [microsoft/playwright#23055]
When running my playwright tests in headless mode (Mobile Safari) some of the elements are not clickable and it throws an error saying "Element is outside of the Viewport".

The same code works fine in headed mode.

Can this bug be fixed?

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. Please file a new issue by filling the "Bug Report" template with a repro, and we will happily take a look.
