### ISSUE TITLE
[Feature] Disable pause() when running playwright tests on remote browsers

### ISSUE THREAD

**Issue by vvs11** [microsoft/playwright#23051]
Let us know what functionality you'd like to see in Playwright and what your use case is.

Sometimes 'pause()' is left unintentionally in the code. When the tests are run on remote browser, they don't get executed. 
If tests  are run on remote browser, automatically disable pause()

Do you think others might benefit from this as well?
Yes

**Comment by amalsgit** [comment]
Looking forward to `forbidPause`. This will save a lot of time in the CI.

**Comment by daniavander** [comment]
i use 1.37.1 version but mi azure ci stop when reach pause()

**Comment by daniavander** [comment]
sorry i ised in a pge fil
await this.page.pause() command
and my ci stopped due to this
