### ISSUE TITLE
Function to validate a specific column of a table has only specific values i wish to validate also to include specific row count validation as well

### ISSUE THREAD

**Issue by eashaarap** [microsoft/playwright#23056]
Hello i need help in writing a dynamic function which i can reuse for any standard table to do the following

- validate specific has only the string wanted ( eg in this table i want to validate Type column only has 'master filing' fields listed
- validate there are 20 rows only on the page
<img width="1317" alt="Screen Shot 2023-05-16 at 9 12 54 AM" src="https://github.com/microsoft/playwright/assets/71307221/91f0aa2b-b569-43ff-aca3-7700851599d4">

**Comment by dgozman** [comment]
> validate specific has only the string wanted ( eg in this table i want to validate Type column only has 'master filing' fields listed

Use `await expect(page.locator(...)).toHaveText('Master Filing')`

> validate there are 20 rows only on the page

Use `await expect(page.locator(...)).toHaveCount(20)`

---

To generate locators, I'd recommend [test generator](https://playwright.dev/docs/codegen-intro).
For general advice, ask [community](https://playwright.dev/community/welcome) for help.
