### ISSUE TITLE
[Feature] Page Model Object level configuration for `testIdAttribute`.

### ISSUE THREAD

**Issue by sh977218** [microsoft/playwright#23058]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Feature: Having a page model object level override configuration for `testIdAttribute`.
Why: The published library of those page model object uses `testIdAttribute` is differently than the consumer's `testIdAttribute`.

**Comment by dgozman** [comment]
@sh977218 `testIdAttribute` is configured globally today. I guess each POM can set it to their own value before performing some actions that use `getByTestId()`. Is there something else you'd like to propose?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue.
