### ISSUE TITLE
[Question] Is it possible to "Record test" with extensions enabled

### ISSUE THREAD

**Issue by TomYeoman** [microsoft/playwright#23066]
I followed this guide to run playwright with my chrome extension I'm building https://playwright.dev/docs/chrome-extensions, and would really like to use the "record new" test option found in https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright

It seems however the "default" browser is always used, is it possible to use one with extensions setup?

**Comment by dgozman** [comment]
@TomYeoman I think this is not possible with "record new" option from the VSCode extension. However, you can engage test recorder from an arbitrary point of your script/test/setup, see [this guide](https://playwright.dev/docs/codegen#record-using-custom-setup). Let me know if this helps.

**Comment by TomYeoman** [comment]
Works like a charm, thanks @dgozman!
