### ISSUE TITLE
[Feature] npx playwright uninstall

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#23072]
Based on our customers feedback (https://github.com/microsoft/playwright/issues/15049#issuecomment-1163980204) we should make it easy to uninstall the Playwright browsers from the system.

**Comment by mxschmitt** [comment]
Outcome:

- `npx playwright uninstall`
- removes the backlink to the current folder
- runs prune
- if more browsers are there, print message and run with `--all`

**Comment by uncaught** [comment]
This doesn't remove all the system dependencies, does it?

What about `npx playwright uninstall --with-deps` ?

**Comment by orzcode** [comment]
> This doesn't remove all the system dependencies, does it?
> 
> What about `npx playwright uninstall --with-deps` ?

We still need an answer to this - how do you remove the deps? 

The several hundred megabytes/gigabyte worth of extra stuff installed by `npx playwright install deps` ??
