### ISSUE TITLE
[Question] How to handle discarded tabs?

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2308]
The promise for `browserContext.pages()` never resolves if one of the pages in browser context is discarded. You can check discarded pages at `chrome://discards`.

How should this be handled? Shouldn't this be resolved from the API side of things? My assumption is that we get targets first and then get the pages for those targets. But since there's no page for that target, we fail to get the actual page and wait for it to be ready.

Any suggestions?

**Comment by rwoll** [comment]
@VikramTiwari Do you have an example bit of code that can be pasted in this issue to help demonstrate the issue? I added a test case in https://github.com/microsoft/playwright/pull/2340, but I'm not sure if that captures the problem you're reporting here.

**Comment by JoelEinbinder** [comment]
Can you provide steps to repro this? I think we should prevent any pages from being discarded instead of trying to handle discarded pages gracefully.

**Comment by VikramTiwari** [comment]
Hey @rwoll That test captures the problem. Though if it's passing then maybe I am seeing some other problem.

@JoelEinbinder Here are the steps to reproduce:
- Launch chromium with playwright and go to a few urls (so that there are tabs in background)
- Quit the app from process manager so that next time it launches, it prompts user to restore tabs
- On restore, only the visible tab completely restores, all other tabs do not restore properly (I think, this might depend on website as well)
- Ask for all the pages and the command hangs.

Same issue has been mentioned on puppeteer here: https://github.com/puppeteer/puppeteer/issues/5633

**Comment by pavelfeldman** [comment]
First of all, thank you for filing this issue. We appreciate your input, in many ways Playwright is based on it. This particular feature request didn't get enough stars for us to prioritize the work on it and hence is being closed. We are a relatively small team and we need to prioritize aggressively to deliver support and new features to you.
