### ISSUE TITLE
[Feature] Run dependencies based on tag in test name

### ISSUE THREAD

**Issue by leesangb** [microsoft/playwright#23080]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Feature:

I want to run dependencies based on tag in test name.

Currently, I can use dependencies array to run some "setup" before running my tests
Here is an example:
```ts
// playwright.config.ts
export default defineConfig({
  // ...
  projects: [
    {
      name: 'setup',
      testMatch: 'setup/global.setup.ts'
      // ...
    },
    {
      name: 'some test',
      testMatch: 'tests/with-global-setup/*.test.ts',
      dependencies: ['setup'],
      // ...
    }
  ],
});
```

This approach works well when there are only a few dependencies like above. However, when I want multiple dependencies, it becomes a bit challenging to structure the project. I have to create another folder depth or add some custom naming convention in my test file in order to combine `dependencies` + `testMatch` + `grep`

Use case: 

I want to skip some dependencies even if the test matches the pattern in the configuration without creating another project configuration. This becomes necessary when there are too many combinations of dependencies. For example, if I want to run different setups for mobile/desktop, dark/light mode, user/guest/admin, and other variations.
+ It may be useful when you want to combine setups conditionally. 

Proposal:

```ts
// playwright.config.ts
export default defineConfig({
  // ...
  projects: [
    {
      name: 'setupA',
      testMatch: 'setup/global.setup.ts'
      // ...
    },
    {
      name: 'setupB',
      testMatch: 'setup/global.setup.ts'
      // ...
    },
    {
      name: 'setupC',
      testMatch: 'setup/global.setup.ts'
      // ...
    },
    {
      name: 'some test',
      testMatch: 'tests/with-setups/*.test.ts',
      dependencies: ['setupA', 'setupB', 'setupC'],
      // ...
    }
  ],
});
```

```ts
// tests/with-setups/something.test.ts

test('test something with @setupA @setupC', async () => {
  // run setupA then setupC (setupB is skipped) then do stuff
});

test('test something with @setupB @setupA', async () => {
  // run setupB then setupA then do stuff
});
```

**Comment by dgozman** [comment]
@leesangb Thank you for the issue! This suggestion is nice, but looks very niche, so it's unlikely we are going to prioritize it. 

However, you can probably achieve the same with [fixtures](https://playwright.dev/docs/test-fixtures), depending on what you are doing in your setups. Feel free to ask any specific questions.

**Comment by leesangb** [comment]
@dgozman Thank you, I just realized that I can define some "scenarios" in my fixture and call them inside my tests to achieve what I described 😅

**Comment by BatoulSarvi** [comment]
Hi @leesangb ,
I have a situation same as what you described above. Would you please explain how you solved it with **"Fixture"** feature?
