### ISSUE TITLE
[test] `connect-to-selenium.spec.ts:20 - connect to selenium` is failing

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#23110]
<img width="1101" alt="image" src="https://github.com/microsoft/playwright/assets/746130/b942c302-45c0-4a58-a437-19005d331238">

permalink: https://devops.playwright.dev/flakiness.html#timestamp=1684366172774

**Comment by mxschmitt** [comment]
Caused by https://github.com/microsoft/playwright/pull/23028
