### ISSUE TITLE
--update-snapshots flag doesn't work in Playwright Component Testing

### ISSUE THREAD

**Issue by bonchuk** [microsoft/playwright#23133]
I am currently working on writing tests for React components using Playwright Component Testing. 
However, I have encountered an issue when trying to update snapshots using the "--update-snapshots"
flag. Instead, I have found that I need to include the "updateSnapshots: 'all'" option in the
"playwright-ct.config.ts" file every time to perform the update.

Therefore, I kindly request that you consider incorporating this flag into Playwright CT as well.
Doing so would greatly improve the consistency and convenience of updating snapshots in both the regular Playwright library and Playwright CT.
Thank you for your attention to this matter, and I appreciate your efforts in continuously enhancing the Playwright
ecosystem.

**Comment by dgozman** [comment]
@bonchuk I just tried running component tests with `--update-snapshots` and everything worked as expected. Could you please file a new issue by filling in the "Bug Report" template and providing a self-contained repro that we can run locally? This way we'll be able to help you.

**Comment by bonchuk** [comment]
sorry I missed that I need to use "--" twice like this: 
npm run test:playwright -- --ui
and all works
