### ISSUE TITLE
[BUG] VS code playwright extention is running wrong dependancy project

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#23142]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Extention version: 1.0.10 (latest)

### Source code
Unfortunatelly, because of company policy I am not able to share code.

**Steps**
- Have multiple setup projects
- Have test projects that depends on that setup projects 

For example this is the part of the config file that the extention is not able to follow:

![image](https://github.com/microsoft/playwright/assets/94455079/be820050-6828-4d3d-8473-e2cc50cdedbc)

**Actual**

In my case I have dependancy on the file with name "login.sg.int.ts, but when running the "ServerGrid test' it starts the project with file "login.int.ts"

If I run from terminal with "npx playwright test --project "ServerGrid" the correct dependacy project is being started.

So it behaives differentlly between terminal and test explorer run from the vs code extention.

**Expected**

Expected dependency project file "login.sg.int.ts' should be started when running "ServerGrid test' from within the playwright vscode extention.

**Comment by dgozman** [comment]
@NikkTod I tried to replicate your setup as close as possible, and I cannot reproduce the issue. Could you please prepare a sample repository that demonstrates the problem? We don't need to see your actual tests, so you can make them all empty.
