### ISSUE TITLE
[BUG] Requests don't preserve the HTTP method on redirects

### ISSUE THREAD

**Issue by gskierk** [microsoft/playwright#23159]
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Server**

```js
// server.js

const express = require('express')

const app = express()

app.post('/test', (request, response) => {
  if (request.get('host').includes('localhost')) { // or any other condition...
    response.redirect('http://127.0.0.1:3000/test')
  } else {
    response.json({ method: 'post' })
  }
})

app.get('/test', (_, response) => {
  response.json({ method: 'get' })
})

app.listen(3000, () => {
  console.log('Server is listening...')
})
```

**Client**

```js
// client.mjs

import { request } from '@playwright/test'

const requestContext = await request.newContext()
const response = await requestContext.post('http://localhost:3000/test')

const json = await response.json()

console.log({ json })

```

**Steps**
- Start the demo server `node server.js`.
- When the server is running, start the client `node client.mjs`.

**Expected**

`{ json: { method: 'post' } }` should be printed to the console.

**Actual**

`{ json: { method: 'get' } }` is being printed to the console.

**Comment**

This particular case could be handled by the client automatically or an additional option could be added. For example, Postman has `Follow original HTTP Method` option in settings.

**Comment by dgozman** [comment]
@gskierk `APIRequestContext` follows the [fetch spec, step 12](https://fetch.spec.whatwg.org/#http-redirect-fetch). I'd recommend to pass [`maxRedirects: 0`](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch-option-max-redirects), and then follow the redirect manually.

**Comment by gskierk** [comment]
@dgozman It sounds reasonable enough to me. Also, I can confirm that handling it manually works without any issues.
