### ISSUE TITLE
[Feature] :  please add a loading time across the framework similar like action time out and navigation timeout

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#23155]
Add loading time option in playwrightconfig.ts under USE module and that time should share across the tests while execution 

in this case we no need to use any other functions like waitforloadState and we can simply share the defined time across the framework depends upon application

**Comment by dgozman** [comment]
@ajaygoutham1995 Unfortunately, I didn't really understand this feature request. What would the "loading time option" control? Could you please share an example test and explain how the new proposed option changes the behavior?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue.
