### ISSUE TITLE
Update test title using test.extend.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#23160]
Is there a way to override the test tile to add a tag using test.extend? For eg instead of writing `test('test title @tag', ...)`, I would like to extend test function to auto add that `@tag`.

**Comment by quldude** [comment]
I want to add the same tag to a custom test function automatically and be able to execute playwright command using `--grep @tag`. For eg: if I have a custom test function `customTest('test title', ...)`, `customTest` should automatically append the tag `@tag` to the title.

**Comment by gskierk** [comment]
Does this solution satisfy you?

```js
const customTest = function(title, callback) {
  return test(`${title} @tag`, callback)
}

customTest.fixme = function(title, callback) {
  return test.fixme(`${title} @tag`, callback)
}

// etc.
```

**Comment by quldude** [comment]
Doesnt work. When running tests, get an error `Error: No tests found`.

**Comment by gskierk** [comment]
```js
import { test } from '@playwright/test'

const customTest = function(title, callback) {
  return test(`${title} @tag`, callback)
}

customTest('title', async ({ page }) => {
  await page.goto('https://playwright.dev')
})

```

```
✓  1 [desktop] › test.spec.ts:3:43 › title @tag (1.3s)
```
