### ISSUE TITLE
[Question] how to get values from XML File (XML File in Browser)

### ISSUE THREAD

**Issue by WallaceAnalista** [microsoft/playwright#23161]
Hi Team,

I would like to ask, how to loop through tag ans:origem, and get the values inside the tag ans:origem (CNPJ)

![file xml](https://github.com/microsoft/playwright/assets/109562915/57f54bde-de9c-4677-a2e0-3872b8ba45db)

**Comment by dgozman** [comment]
@WallaceAnalista Working with xml files is out of scope of Playwright project. As discussed in #23097, download the xml file and parse it with any xml library of your choice.
