### ISSUE TITLE
playwright tests running very slow in one of the three test environments

### ISSUE THREAD

**Issue by vlokesh09** [microsoft/playwright#23189]
I have three test environments, urls go like this:
https://digitaltest1.company.com
https://digitaltest2.company.com
https://digitaltest3.company.com

I am running my first playwright test. I can run the tests fine in the first two environments. The third environment takes 2 mins to perform any action.

One main difference in the third environment is it is bootstrapped in hybrid mode with angular and angular JS.
Any help is appreciated to resolve the issue ?

**Comment by dgozman** [comment]
@vlokesh09 Playwright should not affect the performance of your page.

> One main difference in the third environment is it is bootstrapped in hybrid mode with angular and angular JS.

I guess this is the reason? Not sure how we can help you.

**Comment by vlokesh09** [comment]
> @vlokesh09 Playwright should not affect the performance of your page.
> 
> > One main difference in the third environment is it is bootstrapped in hybrid mode with angular and angular JS.
> 
> I guess this is the reason? Not sure how we can help you.

Does that mean , playwright does not work in this kind of setup

**Comment by dgozman** [comment]
> Does that mean , playwright does not work in this kind of setup

It does, it's probably that your page in one of the environments is slow. If you believe there is an bug in Playwright, please file a new issue by filling in the "Bug Report" template and providing a repro that we can run locally.
