### ISSUE TITLE
[BUG] Video are not generated with fixture

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright#23184]
### System info
- Playwright Version: 1.34
- Operating System: All
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/apis3445/playwright-sample/tree/master

**Test file (self-contained)**

https://github.com/apis3445/playwright-sample/blob/master/tests/demoRealWorld/article.spec.ts

**Steps**
- [Run the test "Create an article Error"]
- [Check the HTML report]

**Expected**

Add the video due to the config being set to add video in failure. The video is in other tests without a fixture

**Actual**

Video is missing if the test is with a fixture
![image](https://github.com/microsoft/playwright/assets/7475390/59a20628-324b-406e-9b8e-19317b9d5ddf)

**Comment by dgozman** [comment]
That's because you manually [close the page](https://github.com/apis3445/playwright-sample/blob/master/tests/demoRealWorld/article.spec.ts#L42). Remove this line, and video should appear. Let me know whether that helps.

**Comment by apis3445** [comment]
I updated the code to remove the close from the page, and it's the same as not adding the video in the article.spec.ts. Is using a fixture

**Comment by dgozman** [comment]
I see, you are overriding the [`page` fixture here](https://github.com/apis3445/playwright-sample/blob/master/fixtures/pomFixture.ts#L55). Yes, in this case the automatic video will not be recorded. This is tracked in the issue #14813, so merging into it.

**Comment by apis3445** [comment]
why is closed if the issue is not fixed? do you have a estimated date for the fix?
