### ISSUE TITLE
[BUG] codegen throws "TypeError: cache.has is not a function" in loop in a specific web page

### ISSUE THREAD

**Issue by blikblum** [microsoft/playwright#23192]
### System info
- Playwright Version: [v1.34 / latest]
- Operating System: [Windows 10]
- Browser: [ Chromium]
- Other info: codegen only

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

** Shell command **

`npx playwright@latest codegen https://saw.trixti.com.br/saw`

**Steps**
- `npx playwright@latest codegen https://saw.trixti.com.br/saw` or `npx playwright codegen https://saw.trixti.com.br/saw`

**Expected**

I could use codegen features (record, pick locator etc)

**Actual**

Codegen is unusable. The site triggers alerts with text  "TypeError: cache.has is not a function (Page: - Line: 399)"  in loop: i click ok a new alert appears

**More Info**

Its specific for codegen . Using the playwright library/automation or directly in browser works without issues

The page has the following DOCTYPE:
`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">`

Looking at call stack, the error is triggered by a function of the Recorder. Yesterday when i first spotted the error i could inspect the callstack. Today the callstack is not show in the devtools

**Comment by aslushnikov** [comment]
@blikblum I can repro on both 1.33 and 1.34. It looks like the `Map` class is substituted by the page. 

<img width="1394" alt="image" src="https://github.com/microsoft/playwright/assets/746130/d0ff7463-3807-461b-8015-8c9aaf9292d0">

**Comment by dgozman** [comment]
Unfortunately, this is out of scope for Playwright. Codegen relies on the built-in `Map` class to work. When the page overrides `Map` and makes it unusable, it is expected to not work.
