### ISSUE TITLE
[Feature] expect.toHaveCountGreaterThan() and expect.toHaveCountLowerThan()

### ISSUE THREAD

**Issue by gskierk** [microsoft/playwright#23196]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I consider it worthwhile to introduce new kinds of matchers to expect the number of elements that `locator.count()` returns.

```js
const locator = page.locator('.selector')

await expect(locator).toHaveCount(2) // already implemented
await expect(locator).toHaveCountGreaterThan(5)
await expect(locator).toHaveCountLowerThan(10)
```

For consistency, there could also be added `.toHaveLengthGreaterThan()` and `.toHaveLengthLowerThan()`.

**Comment by ltsuda** [comment]
duplicated?
https://github.com/microsoft/playwright/issues/19381

**Comment by gskierk** [comment]
Yep, so closing.
