### ISSUE TITLE
[BUG] Chromium won't install via automated script

### ISSUE THREAD

**Issue by michaelcheers** [microsoft/playwright#23204]
### System info
- Playwright Version: 1.33.0
- Operating System: Windows 11
- Browser: Chromium
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Steps**
1. Add Playwright to your .NET 6 project.
2. Run this code:
```cs
using Microsoft.Playwright;

using var playwright = await Playwright.CreateAsync();
await using var browser = await playwright.Chromium.LaunchAsync();
```
3. Open Terminal as an administrator at your project and run:
```
Set-ExecutionPolicy -ExecutionPolicy Bypass
powershell bin/Debug/net6.0/playwright.ps1 install
```

**Expected**

Should install browser

**Actual**

```
Downloading Chromium 113.0.5672.53 (playwright build v1060) from https://playwright.azureedge.net/builds/chromium/1060/chromium-win64.zip
113.5 Mb [=================== ] 97% 2.7sFailed to install browsers
Error: Failed to download Chromium 113.0.5672.53 (playwright build v1060), caused by
Error: end of central directory record signature not found
    at your-project\bin\Debug\net6.0\.playwright\package\lib\zipBundleImpl.js:1:24033
    at your-project\bin\Debug\net6.0\.playwright\package\lib\zipBundleImpl.js:1:31712
    at your-project\bin\Debug\net6.0\.playwright\package\lib\zipBundleImpl.js:1:17288
    at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
```

**Comment by michaelcheers** [comment]
As a workaround, I manually downloaded from the link (https://playwright.azureedge.net/builds/chromium/1060/chromium-win64.zip) and extracted it manually to `%appdata%\Local\ms-playwright\chromium-1060`

**Comment by dgozman** [comment]
@michaelcheers Most likely that was a network issue during download - looks like downloaded zip was corrupted. Could you try again?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
