### ISSUE TITLE
[Feature] Add webdriver-like method add_experimental_option for Chromium

### ISSUE THREAD

**Issue by V4n1sh** [microsoft/playwright#23217]
Let us know what functionality you'd like to see in Playwright and what your use case is.

In selenium-python, one can set experimental option for chrome browser by `Options().add_experimental_option()`, among the `detach: True` is the most used to keep browser open after script execution done.

I've read the documentation and found nothing helpful about keeping browser open after script done. However it could be easily done in selenium-python by adding `{"detach": True}` in experimental option.

Would it be possible that playwright-python adding this functionality?

Do you think others might benefit from this as well?

Yes, there must be such scenarios for us to keep a detached browser.

**Comment by dgozman** [comment]
@V4n1sh What is your usecase? I'd recommend to just leave your python script running, for example call `page.wait_for_timeout(10000000)`.

**Comment by V4n1sh** [comment]
Thanks for your reply.

In my cases, there are some scenarios I need to keep browser open for further manually checking after testcases done. Because no matter how complex and ingenious the code is, there are still certain things that need to be kept for manual inspection and testing.

`page.wait_for_timeout` works well if I want to pause the browser in some cases, but that associated with the running of the script. The blocked processes cause peculiar problems in random time.

hope playwright will have this functionality, thanks so much

**Comment by dgozman** [comment]
@V4n1sh Playwright is very strict about closing the browsers it opened, to avoid hanging processes. I don't think we are going to change that.

If you'd like to keep the browser open, keep your Playwright script running.

Alternatively, you can launch Chromium separately without Playwright, and connect to it from Playwright by calling [`chromium.connect_over_cdp`](https://playwright.dev/python/docs/api/class-browsertype#browser-type-connect-over-cdp). This way you can disconnect whenever you'd like and it gives you the full control over the browser lifetime.
