### ISSUE TITLE
[Question] Is it possible to wrap test.step() into typescript decorator?

### ISSUE THREAD

**Issue by klepik1990** [microsoft/playwright#23226]
Hi Team! Is it possible to wrap test.step() into decorator in typescript? I tried many implementations but I still failed on it. Similar code works good with AllureStep and I thought it will works with test.step() too:)

**Comment by dgozman** [comment]
You can do something similar to what we do internally: [`@step` defintion](https://github.com/microsoft/playwright/blob/main/tests/config/baseTest.ts#L42-L53), [`@step` usage](https://github.com/microsoft/playwright/blob/main/tests/config/traceViewerFixtures.ts#L100). Let me know whether this helps.

**Comment by klepik1990** [comment]
unfortunately it doesn't help, I tried many different implementations but it still fails:(

**Comment by klepik1990** [comment]
My idea was to use something like that
`@step('Step description')
async someMethod(params){
//some stuff here
}
}`

but i can't catch its descriptor inside the decorator, it's already undefined

**Comment by OlehSikorskyi** [comment]
TypeScript 5.0 decorators should help to achieve this:
`function step(message: string) {
    return function actualDecorator(originalMethod: any, context: ClassMethodDecoratorContext) {
        async function replacementMethod(this: any, ...args: any[]) {
            await test.step(`STEP: ${message}`, async () => {
                return originalMethod.call(this, ...args);
            });
        }
        return replacementMethod;
    }
}`

And use: 
`    @step("Login to the application")
    async login(type: Users) {
    }`

**Comment by OlehSikorskyi** [comment]
> My idea was to use something like that `@step('Step description') async someMethod(params){ //some stuff here } }`
> 
> but i can't catch its descriptor inside the decorator, it's already undefined

TypeScript 5.0 decorators should help to achieve this:
`function step(message: string) {
    return function actualDecorator(originalMethod: any, context: ClassMethodDecoratorContext) {
        async function replacementMethod(this: any, ...args: any[]) {
            await test.step(`STEP: ${message}`, async () => {
                return originalMethod.call(this, ...args);
            });
        }
        return replacementMethod;
    }
}`

And use: 
`    @step("Login to the application")
    async login(type: Users) {
    }`
