### ISSUE TITLE
[Feature] Test video element (play, pause, end)

### ISSUE THREAD

**Issue by lisaweilguni** [microsoft/playwright#23223]
## Context
We are currently migrating the E2E test suite of a React Native app from Cypress to Playwright. We would like to test a video element that has _play_, _pause_ and _ended_ events. In Cypress we managed to achieve this with the following assertions:

```
    cy.get('video').should('have.prop', 'paused', false);
    cy.findByTestId('element').should('not.exist');
    cy.get('video', {timeout: 10_000}).and('have.prop', 'ended', true);
    cy.findByTestId('element').should('be.visible');
```

## Problem
We have not found a way to achieve this with Playwright and the docs don't seem to include any information about it.

## Solution
Adding assertions for the _loaded_, _playing_, _paused_, and _ended_ statuses of a video element. In doing so, we can ensure a comprehensive evaluation of video elements when using Playwright. 

Thanks in advance for your help!

**Comment by aslushnikov** [comment]
@lisaweilguni Playwright has an [`toHaveJSProperty`](https://playwright.dev/docs/next/api/class-locatorassertions#locator-assertions-to-have-js-property) assertion. Translating your snippet 

```ts
const videoLocator = page.locator('video'); 
const elementLocator = page.getByTestId('element');
await expect(videoLocator).toHaveJSProperty('paused', false);
await expect(elementLocator).not.toBeVisible();
await expect(videoLocator).toHaveJSProperty('ended', true);
await expect(elementLocator).toBeVisible();
```

Also, note: there's a https://demo.playwright.dev/cy2pw/ tool that would've suggested you the same code.
