### ISSUE TITLE
[Feature] Expose UI Mode via a HTTP server instead of only locally

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#23224]
the ref site:
https://github.com/codeceptjs/ui

**Comment by dgozman** [comment]
@chensce Are you proposing a feature? Could you please be more descriptive?

**Comment by chensce** [comment]
npx playwright test --ui
npx playwright test --server
server mode，we can visit the page the same as ui mode by http://localhost:4003/

**Comment by chensce** [comment]
server mode is the web, and ui mode is the app; the server mode can been visited in anywhere by browser.

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/22309 and https://github.com/microsoft/playwright/issues/23372.

**Comment by mxschmitt** [comment]
This is done, see here: https://playwright.dev/docs/test-ui-mode#docker--github-codespaces
