### ISSUE TITLE
[BUG] "npx playwright" in vanilla v1.34.1/v1.33.0 container asks to install playwright@1.34.1

### ISSUE THREAD

**Issue by bamarch** [microsoft/playwright#23234]
### System info
- Playwright Version: `v1.34.1, v1.33.0`
- Operating System: `Ubuntu Jammy`
- Browser: `All`
- Other info: This is a bug that affects the Docker image `mcr.microsoft.com/playwright:v1.33.0`

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
- Run this to download the image and get a shell

      docker run -it --rm --ipc=host mcr.microsoft.com/playwright:v1.33.0 /bin/bash
    
- Try a simple playwright command inside the docker container

      npx playwright --version
    
**Expected**

It prints `Version 1.33.0` to stdout

i.e. do what the `mcr.microsoft.com/playwright:v1.34.0` container does

![image](https://github.com/microsoft/playwright/assets/24650490/bc1c3723-5799-4e15-83a7-d25b032704d7)

**Actual**

It asks to install playwright@1.34.1

    Need to install the following packages:
      playwright@1.34.1
    Ok to proceed? (y)
    
![image](https://github.com/microsoft/playwright/assets/24650490/6548fc11-3cd9-4772-8d3f-58d67dcc57ff)

**Comment by bamarch** [comment]
Updated because this bug also affects the `v1.34.1` container

![image](https://github.com/microsoft/playwright/assets/24650490/848cf474-da1a-4f3d-9291-1ed72975dd2e)

**Comment by dgozman** [comment]
@bamarch This is actually how it's supposed to work. Playwright's docker images do not have Playwright package pre-installed. Usually, you would checkout your project inside, and playwright will be installed as a part of `npm install` command. Then `npx playwright --version` and other commands will start working.

However, in the docker image `v1.34.0` there was a bug, where playwright accidentally got into npx cache folder, and so `npx playwright --version` unexpectedly worked. Sorry for confusion!
