### ISSUE TITLE
Additional iframe from playwright (only in one environment)

### ISSUE THREAD

**Issue by agataDeviniti** [microsoft/playwright#23230]
I have strange issues in one of my environments. When I try to click on one element it doesn't happen. As I have checked it is caused by an additional iframe from the playwright.
When I search for locator in 'top', it does not find the element:
<img width="706" alt="Zrzut ekranu 2023-05-23 o 12 07 01" src="https://github.com/microsoft/playwright/assets/93976627/acb92739-0968-4824-ab08-93d34ec99288">

When I search for a locator in an iframe, it returns the correct element:
<img width="710" alt="Zrzut ekranu 2023-05-23 o 12 09 02" src="https://github.com/microsoft/playwright/assets/93976627/25f34bf6-e25b-4e87-a079-00a76c8da0c2">

Details about iframe element:
`<iframe __playwright_src__="/snapshot/frame@8e43e5ddde2bfee64f9aa9f7c9b8034f" class="IFramestyle__StyledIFrame-iixo8s-0 jAVhLT" id="iframe_content" src="[http://127.0.0.1:9323/trace/snapshot/frame@8e43e5ddde2bfee64f9aa9f7c9b8034f?trace=http%3A%2F%2F127.0.0.1%3A9323%2Fdata%2F5a611e590ce0f4b170e428e4665dc98d7b477a87.zip&amp;name=after%40call%4024](http://127.0.0.1:9323/trace/snapshot/frame@8e43e5ddde2bfee64f9aa9f7c9b8034f?trace=http%3A%2F%2F127.0.0.1%3A9323%2Fdata%2F5a611e590ce0f4b170e428e4665dc98d7b477a87.zip&name=after%40call%4024)"></iframe>`

It is strange, that it only happens in one of my environments. Do you have any ideas why it happens?

**Comment by dgozman** [comment]
@agataDeviniti  Are you looking at the trace? If so, click "Open snapshot in a new tab" button to the top-right of the snapshot. There it will be rendered without the trace around it, and there will be no confusion about iframes. Let me know if that helps.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
