### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by asulemanbci** [microsoft/playwright#23237]
**Context:**
- Playwright Version: 1.34.1
- Operating System: Windows
- Node.js version: 18.16.0
- Visual Studio Code version: 1.78.2
- Playwright for VSCode extension version: 1.0.11
- Browser: All, Chromium, Firefox, WebKit
- Extra: None

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

Test Runner is not displaying playwright tests
![image](https://github.com/microsoft/playwright/assets/134241531/76707c2a-e017-4aaa-955d-01cd11f87397)

![image](https://github.com/microsoft/playwright/assets/134241531/ba5f78ce-546b-4c4b-806a-f4e59af3fbd4)

![image](https://github.com/microsoft/playwright/assets/134241531/43b390a7-ebba-4e19-8b19-3d6731256927)

**Comment by dgozman** [comment]
@asulemanbci This was fixed in `v1.34.2`, see #23225.

**Comment by asulemanbci** [comment]
@dgozman - Thanks for the update!
