### ISSUE TITLE
[Feature] It should give assertion failed message when test get failed. 

### ISSUE THREAD

**Issue by Palash9088** [microsoft/playwright#23235]
Let us know what functionality you'd like to see in Playwright and what your use case is.
When we use any assertion in playwright so the message we give should come up when the test case get failed like it happen in testng but playwright thinks that it is name of the assertion & it shows that as well in the report doesn't matter it gets passed or failed. 
Do you think others might benefit from this as well?
yes, people are moving from selenium playwright so it should be similar to the things they are using so people will feel more confident to use playwright.

![Screenshot 2023-05-23 175549](https://github.com/microsoft/playwright/assets/44397045/6aea2009-623d-41d4-9cf1-766bfd8395d3)

**Comment by dgozman** [comment]
@Palash9088 I did not understand the issue. Could you please be more specific? Provide steps that you do, what you expect and what happens instead. From what I see, your provided a custom `expect` message and it was shown in the report, which looks good to me.

**Comment by Palash9088** [comment]
I mean to say that in testng when we use assertion -> 
Assert.assertEquals("playwright", "playwright", "Title not matched");
Assert.Method( actual, expected, String)
so in the string we give some text & it comes when that particular assertion get failed. 
In playwright the assertion string text becomes the test title even if it get passed or failed it shows the same message

![image](https://github.com/microsoft/playwright/assets/44397045/a5e2e89e-2d55-47f9-91f7-f4e89413a53c)
![image](https://github.com/microsoft/playwright/assets/44397045/2d4be288-64c3-408b-aabd-edb8ed682b28)
![image](https://github.com/microsoft/playwright/assets/44397045/66ddb68d-39d9-4832-8c00-ca997a414ace)

by the above image I think you would understand & message should be displayed when that particular expect get failed it should not become the title of the expect

**Comment by Palash9088** [comment]
@dgozman  It get closed mistakenly.

**Comment by dgozman** [comment]
@Palash9088 Thank you for the clarification. What would you like to see in the report when assertion has passed, instead of the custom message?

**Comment by Palash9088** [comment]
simply what assertion we have used should be displayed in that
![image](https://github.com/microsoft/playwright/assets/44397045/d47ea972-ba01-4167-a64e-de58b2ac7721)
like in the above image, & when it get failed then the custom message should be appear.

**Comment by kasperkow** [comment]
I think it works correctly. You expect that "vwo keyboard isn't visible" and it's true so you see a tick. It's logic. When you are looking at the report, it's easier to verify business logic. In the first example, it's just changed to "The count is greater than zero"

**Comment by Palash9088** [comment]
@kasperkow thankyou for clarification.

I have raised one bug kindly look into this as well
https://github.com/microsoft/playwright/issues/23282

Closing this one.
