### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by devmasonn** [microsoft/playwright#23249]
### System info

Playwright Version: 1.32
Operating System: Mac
Node.js version: v17.0.1
Browser: WebKit
Extra: NA

### Source code

**testClientCert.ts:**

```
async testCert(browser:Browser) {
          const homedir = require('os').homedir();
          const request = require('request');
        
        const ctx = await browser.newContext();
        await ctx.route( url, (route) => {
      
        const options = {
        uri: url,
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: payload,
        timeout: 10000,
        followRedirect: false,
        agentOptions: {
            ca: fs.readFileSync(homedir+'/test-cert.pem'),
            pfx: fs.readFileSync(homedir+'/test-key.pem'),
            passphrase: password
        },
        };
        let firstTry = true;
            const handler = function handler(err: any, resp: any, data: any) {
                if (err) {
                    /* Strange random connection error on first request, do one re-try */
                    if (firstTry) {
                        firstTry = false
                        return request(options, handler)
                    }
                    console.error(`Unable to call ${options.uri}`, err.code, err)
                    return route.abort();
                } else {
                    return route.fulfill({
                        status: resp.statusCode,
                        headers: resp.headers,
                        body: data,
                    })
                }
            }
            return request(options, handler)
        });
    }
```

**Test file (self-contained)**

```
let testBrowser: Browser;
test.describe("Test client cert in HTTP call", () => {

 test.beforeAll(async ({ browser}) => {
        testBrowser = browser;
 });
 
 test('Client cert', async () => {
         await testCert(testBrowser);
 });
 
})
```

**Steps**
1. Run test file.

**Expected**

1. testCert function should be executed.
2. Function call should go inside function handler() and execute it.

**Actual**

- When I am calling testCert() method from my test file, it is going inside it but is is never executing function handler(). To double check I have put loggers at multiple places inside function handler() and I am not getting any of those loggers printed or function handler() executed. And still I am seeing **Test Result: passed**. 

- Could you please here to figure out how to execute HTTP calls with client certificate from Playwright ?

**Comment by dgozman** [comment]
@devmasonn I don't see where you trigger any network requests in your code. You did setup a route handler with `ctx.route()`, but never actually load anything in the context. Perhaps create a new page and call `page.goto()`?

**Comment by devmasonn** [comment]
> @devmasonn I don't see where you trigger any network requests in your code. You did setup a route handler with `ctx.route()`, but never actually load anything in the context. Perhaps create a new page and call `page.goto()`?

- I have tried the solution you are saying by giving page.goto. But it is not working means it is not executing function handler().

test('Client cert', async () => {
         page = await testBrowser.newPage();
         await page.goto(URL);
         await testCert(testBrowser);
 });

**Another solution:**
I have tried another solution  - **test('Client cert')** and doing my API call in separate file(certAuth.ts).

**certAuth.ts:**

export const testCert = base.extend({
    context: async ({ context }, use) => {

       // I use the context that is created using my base config here, just adding the route, but you could also create
       // a context first if you needed even more customizability.

       const homedir = require('os').homedir();
       const request = require('request');
       
       await context.route('/test/endpoint', (route) => {
       
       const options = {
       uri: URL,
       method: 'POST',
       headers: { 'Content-Type': 'application/json' },
       body: payload,
       timeout: 10000,
       followRedirect: false,
       agentOptions: {
           ca: fs.readFileSync(homedir+'/test-cert.pem'),
            pfx: fs.readFileSync(homedir+'/test-key.pem'),
            passphrase: password
       },ignoreHTTPSErrors: true
       };
       let firstTry = true;
       
           const handler = function handler(err: any, resp: any, data: any) {
               
               if (err) {
                   /* Strange random connection error on first request, do one re-try */
                   if (firstTry) {
                       firstTry = false
                       return request(options, handler)
                   }
                   console.error(`Unable to call ${options.uri}`, err.code, err)
                   return route.abort()
               } else {
                   logger.info("Data",route.fulfill({
                       status: resp.statusCode,
                       headers: resp.headers,
                       body: data,
                   }));
                   return route.fulfill({
                       status: resp.statusCode,
                       headers: resp.headers,
                       body: data,
                   })
               }
           }
           
           return request(options, handler)
       })
        use(context)
    },
})

**testFile.ts:**

let page: Page;
let testBrowser: Browser;

 test.beforeAll(async ({ browser}) => {
        testBrowser = browser;
        page = await testBrowser.newPage();
 });

 testCert('Client cert', async ({ page, context }) => {
        await page.goto(URL);
});

Following this link from one of the gitHub issues: [https://github.com/microsoft/playwright/issues/1799#issuecomment-959011162]. But in my case, I don't have url up on the UI side. It is available just in API call. And so  ctx.route() is executing but giving this error:

Test case error message: page.goto: Blocked by Web Inspector
=========================== logs ===========================
navigating to **URL**, waiting until "load"

**Comment by dgozman** [comment]
@devmasonn You should first setup your route with `testCert(browser)`, and only then navigate the page with `page.goto()`.

This does not seem like  a bug in Playwright, so I'll close the issue. I'd recommend to read some docs about [Playwright](https://playwright.dev/docs/intro) and [network routing](https://playwright.dev/docs/network#handle-requests). Feel free to [ask community](https://playwright.dev/community/welcome) for help.
