### ISSUE TITLE
[Feature] 'toHaveScreenshot' should have ability to capture full page.

### ISSUE THREAD

**Issue by KunalOjha** [microsoft/playwright#23243]
I have created a feature request for the ability of PlayWright's Visual Comparison flow to allow users the ability to capture full page screenshots for comparisons. I don't believe there is a way to configure this using the toHaveScreenShot method as outlined in the [docs](https://playwright.dev/docs/test-snapshots) 

Currently this is the way Playwright recommends to perform snapshot comparisons: 

```
import { test, expect } from '@playwright/test';

test('example test', async ({ page }) => {
  await page.goto('https://playwright.dev');
  await page.screenshot({ path: 'screenshot.png', fullPage: true });
  await expect(page).toHaveScreenshot();
});
```

**Comment by dgozman** [comment]
@KunalOjha You can pass `fullPage` option, [see here](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-full-page).

**Comment by 627668410** [comment]
> @KunalOjha You can pass `fullPage` option, [see here](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1-option-full-page).

version：1.34.3，chromium
My configuration is as follows, but it is not working.
`await expect(page).toHaveScreenshot({fullPage: true});`

**Comment by dgozman** [comment]
> Can ‘Element screenshot’ capture a screenshot with scrollbars like fullPage does?

Do you mean "full contents of the element, including scrolled out content"? If so, that's not possible. Element screenshot captures the visible contents of a single element, including scrollbars if the element has them.

**Comment by 627668410** [comment]
> 

Yes, that's what I meant, as my page includes a fixed header and only the content below it scrolls.

**Comment by mxschmitt** [comment]
Have you tried: ` await expect(page).toHaveScreenshot({ fullPage: true });`?

**Comment by aslushnikov** [comment]
The original request by @KunalOjha is solved by `fullPage` option - so closing this.

@627668410 please file a separate issue to not fork the discussion here.
