### ISSUE TITLE
[BUG] scrollIntoViewIfNeeded for a locator is not working in Firefox (same for element screenshots)

### ISSUE THREAD

**Issue by ata1704** [microsoft/playwright#23253]
**System info**

- Playwright Version: v1.34.0
- Operating System: All
- Browser: Firefox
- Other info: This is a bug that also affects the Docker image mcr.microsoft.com/playwright:v1.34.0-jammy

**Repro Steps:**

1. Taking an element screenshot is not scrolling the element into view.
2. Calling `scrollIntoViewIfNeeded` on the element locator also has no effect.
3. Tried it in Chromium and both are working as expected.

**Expected**

- Element should scroll into view when I take a locator screenshot or call the method `scrollIntoViewIfNeeded`.

**Actual**

- Nothing happened in Firefox.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
