### ISSUE TITLE
[BUG] HTML disappears using Pick locator with background color using Next.js/Sass

### ISSUE THREAD

**Issue by ProchaLu** [microsoft/playwright#23275]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [macOS 13.0.1]
- Browser: [Chromium]
- Other info:     [Node 18.15.0, pnpm 8.5.0]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/ProchaLu/next-js-playwright

or

**Config file**

```ts
import { devices, PlaywrightTestConfig } from '@playwright/test';

// config file reference - https://playwright.dev/docs/test-configuration
const config: PlaywrightTestConfig = {
  webServer: {
    command: 'pnpm start',
    port: 3000,
    reuseExistingServer: !process.env.CI,
  },
  testIgnore: '**/util/__tests__/**',
  retries: process.env.CI ? 2 : 0,
  reporter: process.env.CI
    ? 'list'
    : [['html', { outputFolder: 'playwright/report/' }]],
  outputDir: 'playwright/test-results/',

  use: {
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
    testIdAttribute: 'data-test-id',
  },

  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
};

export default config;

```

**Test file (self-contained)**

```js
test('has title', async ({ page }) => {
  await page.goto('http://localhost:3000');
  await expect(page.getByRole('heading', { name: 'test' })).toBeVisible();
```

**Steps**
- Clone the repository
- Install project dependencies with `pnpm install`
- Start the development server with `pnpm dev`
- Open Playwright UI or debug mode
  - Playwright UI: pnpm playwright test --ui
  - Debug mode: pnpm playwright test --debug
- Click on the Pick Locator tool within the Playwright UI or debug mode

**Description**

I have encountered a bug while using Playwright UI and debug mode in combination with a Next.js project that incorporates Sass styling. This issue has been observed on Next.js versions v13.4.3 and v13.4.4-canary.0.

The bug manifests when opening the Playwright UI or debug mode and utilizing the Pick Locator feature. At that point, the entire page disappears, leaving only the background color specified in the globals.scss file visible. The background color is applied using the following selector:
```css
* {
  background-color: yellow;
}
```

When using inline-CSS with the following code snippet:
```
<body style={{ background: 'red' }}>
```
The Pick Locator works without encountering any issues.

Additionally, it is worth noting some edge cases. When applying a background color using the `background` property, the issue is still there. 

Interestingly, the bug does not affect the Pick Locator when a background color is applied to other elements, such as an `<h1>` tag.

**Expected**

When opening the debug mode or Playwright UI, the Pick Locator feature should not cause the HTML content to disappear, even when a background color is present. As the screenshots show, without a background color, everything is working as expected.
<img width="1025" alt="Screenshot 2023-05-25 at 11 46 00" src="https://github.com/microsoft/playwright/assets/80746311/983f6ced-ecbc-4ad4-bfb9-3ba5c7336650">
<img width="1025" alt="Screenshot 2023-05-25 at 11 46 09" src="https://github.com/microsoft/playwright/assets/80746311/e2a660dc-0795-417d-9820-adf39a304c4d">

**Actual**

When using the Pick Locator tool in debug mode or Playwright UI, while a background color is defined, the HTML content vanishes, leaving only the background color visible. As the screenshots show, with a background color, the HTML disappears when using the Pick Locator.
<img width="1025" alt="Screenshot 2023-05-25 at 11 45 14" src="https://github.com/microsoft/playwright/assets/80746311/f2dd906b-bd4d-4b08-99d9-9e52d6bd3158">
<img width="1025" alt="Screenshot 2023-05-25 at 11 45 22" src="https://github.com/microsoft/playwright/assets/80746311/06d67fca-2312-45aa-9ea8-d564f0f9445b">

**Comment by mxschmitt** [comment]
I can reproduce. Fur further investigation, the trace.zip: 
[trace.zip](https://github.com/microsoft/playwright/files/11598008/trace.zip)
