### ISSUE TITLE
[Feature] Global Configuration for Test Tags to Fail Pipeline if Tag is Missing

### ISSUE THREAD

**Issue by Mshumaman** [microsoft/playwright#23274]
In our large-scale product, we have organized our tests into modules, and we rely on test tags to trigger specific modules during GitLab jobs. However, we have recently discovered that if we overlook adding a tag during code review, the corresponding tests won't run in the pipeline.

To clarify, if a new test is added to the `@Sales_Module`, but the developer forgets to include the `@Sales_Module` tag, the test will not be executed when using the command `npx playwright test --grep @Sales_Module`.

Considering we have a substantial number of tests, totaling over 1800, it becomes quite challenging to manually ensure that no tags are missing. To address this issue, it would be highly beneficial to have the ability to configure this behavior in the `playwright.config` file. Specifically, in our team's case, it would be ideal if the pipeline failed when a test was missing the required tag.

Having the option to configure this in the `playwright.config` file would greatly improve our testing workflow. Additionally, it opens up the potential for other useful options, such as skipping tests based on certain tags. These configurations would provide a more robust and automated approach, ensuring that all tests are appropriately categorized and executed in our pipeline.

**Comment by dgozman** [comment]
> I believe it also can be missed and the test will not be a part of the suite.

If this is the case, any tooling inside `npx playwright test` will also miss the test, because it could only look at the tests that are matched by some of your test projects. To guard against this, you'll need some custom tooling outside of Playwright.

I will close this issue, since it's unlikely there is an action item for Playwright project here. Thank you for filiing!

**Comment by millerick** [comment]
I'm also looking into ways to effectively type check that each test has at least one tag from a predefined set of tags associated with it.
