### ISSUE TITLE
Cannot wait to an existing, non-visible element

### ISSUE THREAD

**Issue by vemv** [microsoft/playwright#23290]
Per https://playwright.dev/java/docs/api/class-page#page-wait-for-selector:

> Returns when element specified by selector satisfies state option. **Returns null if waiting for hidden or detached.**

Given this API, I'm not able to distinguish these two cases:

* nothing at all was found
* something was found, it's hidden
  * for instance, this should be the case for a `<meta>` tag.

This particular case seems a bad API because it conflates those two aspects, making certain queries impossible (at least under that API).

Have you considered that nuance?

Perhaps there could be an extra option, `alwaysReturnFound`? Which would not return null if an element matching the query was found.

Thanks - V

**Comment by np-code2** [comment]
https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-be-attached

This should be what you need.

**Comment by mxschmitt** [comment]
You should never use page.waitForSelector as the docs say that its discouraged.

You should always rely on the web-first assertions, does [isAttached](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-be-attached) work for your use-case?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
