### ISSUE TITLE
[Feature] Allow the app under test to have the "real" focus of the browser.

### ISSUE THREAD

**Issue by spaniardmaximus** [microsoft/playwright#23305]
Hi, @spaniardmaximus here, big fan.

I'm in a bit of a situation with an E2E test that I'm trying to finalise. My app interacts with a desktop card reader which, upon reading a card, sends the token back to the app. 

While the browser and context, etc may be under Playwright control, the focus of any and all my tests is on the url, i.e. the url is highlighted. What it means to me is that the token read by the reader overwrites the url at the top of the browser instead of being recognised by my app.

My automated test totally works if, after logging in, I take the mouse and click somewhere in the app (so that's the automation gone :) ). I've tried a number of things to gain focus without success. I wonder if there could be a feature allowing this to happen for those apps interacting with the outside world through these sort of devices.

**Comment by aslushnikov** [comment]
> My automated test totally works if, after logging in, I take the mouse and click somewhere in the app (so that's the automation gone :) ). I've tried a number of things to gain focus without success. 

@spaniardmaximus First of all, i've never seen this personally. Any chance you can share a small video so that we can educate ourselves on what it looks like?

> I wonder if there could be a feature allowing this to happen for those apps interacting with the outside world through these sort of devices.

This is unlikely though, since sounds like a very niche usecase for Playwright. I'd recommend trying out some OS-specific automation software to do the OS click / window activation.

**Comment by aslushnikov** [comment]
I'll close this then since there's no action from the team required on this one. Do not hesitate to open new issues if you think we still can be helpful though.
