### ISSUE TITLE
[BUG] Buggy thumbnail layout in trace viewer and UI mode

### ISSUE THREAD

**Issue by scitech** [microsoft/playwright#23304]
### System info
- Playwright Version: v1.34.3
- Operating System: macOS
- Browser: All
- Other info:

### Source code

Unable to share a reproducer but I can work on it if needed.

**Steps**
- `playwright test --ui`

**Expected**

Thumbnails are laid out in a single horizontal row.

**Actual**

Thumbnails are in a staggered layout which makes the other panels unusable:
<img width="800" alt="image" src="https://github.com/microsoft/playwright/assets/4130722/1c27223b-351e-42c2-95b5-ca623a8ec05e">

**Comment by aslushnikov** [comment]
@scitech i've never seen this personally, and can't repro. You mentioned that you can work out a repro; could you please re-file with a repro then? 

Thanks!

**Comment by scitech** [comment]
> @scitech i've never seen this personally, and can't repro. You mentioned that you can work out a repro; could you please re-file with a repro then?
> 
> Thanks!

I was able to reproduce this in #23490 and found it was caused by tests that open multiple pages in a context. I opened a PR to address it, too, if you wouldn't mind taking a look at #23493. Thanks for your time.
