### ISSUE TITLE
[BUG]When using split screens, the vscode error message will be synchronized across all files

### ISSUE THREAD

**Issue by a16su** [microsoft/playwright#23319]
**Context:**
- Playwright Version: v1.34.3
- Operating System: Windows11
- Node.js version: v18.14.1
- Visual Studio Code version: 1.78.2
- Playwright for VSCode extension version: 1.0.11
- Browser: 
- Extra: 

**Describe the bug**
Open the file `conftest.ts`, write some error code, open the file `test.a.spec.ts` by splitting the screen, write the correct code, then the file `test.a.spec.ts` will have the same error message as `conftest.ts` in the same location
![image](https://github.com/microsoft/playwright/assets/33782391/62020e42-581c-4633-97f1-27e2ad1d52e7)
Disable playwright extension, `test.a.spec.ts` error message disappears
![image](https://github.com/microsoft/playwright/assets/33782391/f80f60fc-910b-44db-8ca8-06ee9cc39d7e)

**Comment by aslushnikov** [comment]
@a16su hey sorry, we had a long weekend here. 

I don't follow the exact issue here; can you build a small repo that i can clone & open in vscode to see it? Or maybe a video?

**Comment by a16su** [comment]
@aslushnikov
try this repo: https://github.com/a16su/for_issue23319
and a video is include in repo

**Comment by mxschmitt** [comment]
Have you tried to reproduce this without the Playwright for VSCode extension? This looks like a VSCode bug to me, which should be filed here: https://github.com/microsoft/vscode

**Comment by aslushnikov** [comment]
Indeed looks like a VSCode bug. @a16su could you please file upstream to VSCode instead? Thanks!
