### ISSUE TITLE
[BUG] Getting `Please install @playwright/test package to use Playwright Test.` when I updated to latest version 1.34.3

### ISSUE THREAD

**Issue by thekp** [microsoft/playwright#23312]
### System info
- Playwright Version: [1.34.3]
- Operating System: [MacOS Ventura - Version 13.4]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: 
```
$ node -v
v19.4.0

$ yarn -v
1.22.19

$ yarn list --pattern @playwright/test
yarn list v1.22.19
└─ @playwright/test@1.34.3
```

###  Additional notes:

I get this problem when I created a new playwright project with `yarn create playwright`

**Comment by aslushnikov** [comment]
Let me close this in favor of https://github.com/microsoft/playwright/issues/23314 since that one has a repro
