### ISSUE TITLE
[Feature] Improve multiple project support in extension

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#23329]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I am having a project were all the Playwright tests are contained for all targets tob e tested. For example, a bunch of API tests, webapp1, webapp2 and webapp3 tests. Each of these projects have a custom `playwright.config.ts` file with a unique name, e.g. `api.playwright.config.ts` or `webapp2.playwright.config.ts` etc. I think it would be amazing if all these projects get listed in the Visual Studio Code extension. I think allowing to search for `*playwright.config.(ts|js)` files and then source them in the extension.

**Comment by aslushnikov** [comment]
Thank you for filing! Let's collect more upvotes on this one to see if more folks need this.

**Comment by weyert** [comment]
@aslushnikov Okay! If you are able to give me pointers what kind of changes would be necessary. I could try to make the changes myself but I have no clue where to start and whether this would require only changes to the vscode extension

**Comment by mxschmitt** [comment]
This should be implemented. Please re-file if you the current extension doesn't work for you.
