### ISSUE TITLE
[Doc] List all possible DEBUG values in the doc

### ISSUE THREAD

**Issue by CyriacBr** [microsoft/playwright#23330]
The doc only mention about `DEBUG=pw:api` and `DEBUG=pw:browser*` but there seems to be more values the `DEBUG` en variable can take, but this is not listed anywhere.

**Comment by mxschmitt** [comment]
We prefer only listing the relevant ones which are as of today as you said pw:api, pw:browser and pw:webserver.

In which ones are you interested in?

There is also pw:install, pw:android, pw:adb or pw:protocol but those are not used very often from a user perspective.

**Comment by CyriacBr** [comment]
> We prefer only listing the relevant ones which are as of today as you said pw:api, pw:browser and pw:webserver.

In that case it'd be nice to list them in the "Debugging Tests" page and explain a bit what they did. I personally didn't understand what `pw:api` was supposed to log before trying it.

I'm trying to debug a hanging test that happens only in CI so I was looking for a way to display all kinds of logs so that I can pinpoint what's wrong.

> There is also pw:install, pw:android, pw:adb or pw:protocol but those are not used very often from a user perspective.

Is there a way to enable all logs?

**Comment by CyriacBr** [comment]
Also, what does the `*` next to `pw:browser` mean? 
Also how do you combine multiple logging "scopes"?

**Comment by mxschmitt** [comment]
If something is hanging we actually prefer using [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) rather than any DEBUG value. DEBUG is just using the [DEBUG package](https://www.npmjs.com/package/debug) under the hood which is commonly used in the Node.js ecosystem to provide debug logs. Trace Viewer makes it much easier to debug any Playwright issues with your end-to-end test.

* is just a wildcard glob pattern. You can combine using a comma.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale and answered. Please create a new issue with a detailed reproducible or feature request if you still face issues.

**Comment by sparrowt** [comment]
@CyriacBr did you ever get round to this? I'm still seeing only a few scattered around the docs (`pw:api`/`pw:browser`/`pw:webserver`) but having a list/table would be great.

EDIT: I've just found [this list](https://github.com/microsoft/playwright/blob/607ad44561178cea18b269f73a28193870d4f5d4/packages/playwright-core/src/server/utils/debugLogger.ts#L21-L35) which _might_ be relevant? Though interestingly `webserver` is not in the list, but perhaps it just doesn't get colourised?
