### ISSUE TITLE
[Question] is there any way to make beforeall and afterall is only executed once even if a test block fails

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#23331]
I have a test spec file where there is a beforeall block and a afterall block and many test blocks (test1,test2, test3), I run test with only one worker
if there is no failure, the execution sequence is beforeall->test1->test2->test3->afterall

but if test2 fails, the execution sequence is 
beforeall->test1->test2->afterall->beforeall->test3->afterall

I saw a description in doc (Note that worker process is restarted on test failures, and beforeAll hook runs again in the new worker) 

is there any way to make beforeall and afterall hooks always run 1 time (will not run again) even in case of failures?

**Comment by aslushnikov** [comment]
@bodycombathuang you can use the new [project dependencies](https://playwright.dev/docs/next/test-global-setup-teardown#project-dependencies) and [project teardown](https://playwright.dev/docs/next/api/class-testproject#test-project-teardown) features.

We discussed them in our release videos:
- project dependencies: https://youtu.be/PI50YAPTAs4?t=286
- project teardown: https://youtu.be/JeFD6rqDbBo?t=266

Hope these help!

**Comment by philipfong** [comment]
I too also find the beforeAll and afterAll hooks a little counterintuitive. You would expect these blocks to run _only_ once regardless of whatever tests fail within the describe block. Seems like the existing behavior should be designated for some other test function like `test.onFailure` or something like that. There are going to be times where you want to perform some type of cleanup in the test that is focused on the specific feature you're writing tests for, and not so applicable on a 'global' teardown level.
