### ISSUE TITLE
[BUG] VSCode "Test Explorer" can't find any tests

### ISSUE THREAD

**Issue by miktap** [microsoft/playwright#23340]
**Context:**
- Playwright Version: 1.34.4
- Operating System: Mac
- Node.js version: 16.16.0
- Visual Studio Code version: 1.78.2
- Playwright for VSCode extension version: 1.0.11
- Browser: All

I recently installed Playwright (with VSCode extension) and created few tests for my app. All was fine and I was able to run those tests through VSCode "Test Explorer" on all browsers. Few days later, after opening VSCode project again, the "Test Explorer" was not able to find my tests anymore. Restarting VSCode did not help. However disabling Playwright VSCode extension and the re-enabling it again did help. 

So currently I can see my tests in "Test Explorer". Not sure how to reproduce the problem as at least now VSCode restart does not cause any problems.

**Comment by NikkTod** [comment]
I had the same problem, uninstalling and installing again the vs code extention did the trick for me.

**Comment by aslushnikov** [comment]
@miktap thank you for filing this issue! We keep an eye on VSCode extension compatibility; unfortunately, this particular issue is impossible to act upon without a repro, so I'll have to close this for now.

Feel free to file new issues if you think we can be helpful though!
