### ISSUE TITLE
[BUG] 'Pick locator' does not show frameLocator

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#23349]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [All]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

**Steps**
1. Run ->  npx playwright codegen https://www.w3schools.com/html/html_iframe.asp
2. Record a click for an element within the iframe
3. Stop recording and select 'Pick locator'
4. Try to get the locator for that same element within the iframe

**Actual**
2. When recording the whole element is shown ->  

 `await page.frameLocator('iframe[title="W3Schools HTML Tutorial"]').getByRole('link', { name: 'HTML', exact: true }).click();`

4. But if I try to pick an element locator it does not show the frameLocator 

`getByRole('link', { name: 'HTML', exact: true })`

**Expected**
4. I expect the Pick locator to show me also the frameLocator 

`frameLocator('iframe[title="W3Schools HTML Tutorial"]').getByRole('link', { name: 'HTML', exact: true })`

If it does not show that the element is inside an iframe, user will lose time in debugging and thinking what is wrong with his locator.

**Comment by NikkTod** [comment]
Hey Max @mxschmitt, is this one marked as a feature, for me is more like a bug. Not showing the full locator path including the the iframe will mislead the user. 
We have this 'Pick locator' on UI mode, on Trace viewer and on Codegen, so if the seached locator is under an iframe it will not work.

**Comment by mxschmitt** [comment]
Its a bug under the feature codegen. So its definitely something we want to fix!

**Comment by dijitali** [comment]
New to Playwright so spent a long time trying to figure out where I'd gone wrong here.  In the end, I gave the problem to the phind.com language model to troubleshoot and it generated this that pointed me in the right direction.  

Perhaps something along these lines could be added as an advisory note to the [VSCode extension docs](https://playwright.dev/docs/getting-started-vscode#picking-a-locator) until this issue is fixed?

> If the element is inside an iframe, Playwright cannot access it directly. You'll need to switch to the iframe first before locating the element. You can use `page.frame()` to get access to the iframe, and then use the `frame.locator()` method to locate the element within the iframe.
> 
> ```ts
> const frame = await page.frame({ name: 'your-iframe-name' });
> const peopleResultsLocator = frame.locator('.heading-value');
> ```

**Comment by NikkTod** [comment]
Hey @mxschmitt, any timeline for fixing this bug? The app we test have a lot of iframes, so this one makes our lives a bit harder.
