### ISSUE TITLE
[BUG] Documentation missing defaults for some BrowserContext options

### ISSUE THREAD

**Issue by tonybaloney** [microsoft/playwright#23355]
The following applies to the API docs for all languages.

For new Browser Context options, many of the options don't have documented defaults or the behaviour is not clear:

- Base URL 
- Bypass CSP
- Extra HTTP headers (defaults to None)
- Locale
- No viewport
- Permissions
- Proxy
- Record HAR URL filter
- Strict selectors
- Timezone ID
- User agent

Some of the formatting is inconsistent, for example in Python the message for `ignore_https_errors` is "defaults to `false`" and for `has_touch` is "defaults to false". Neither are valid as the type in Python is `False`.
There is inconsistency in the use of quotes for string literal defaults in the Python API. e.g., in `record_har_content` the default is "`full`" and in `forced_colors` it is `'none'`

**Comment by aslushnikov** [comment]
> For new Browser Context options, many of the options don't have documented defaults or the behavior is not clear:

Thanks, I've updated the docs with the default values.
