### ISSUE TITLE
[BUG] Setting an explicit timeout for locator.evaluate doesn't work. It still timeouts based on playwright config value.

### ISSUE THREAD

**Issue by perezdev** [microsoft/playwright#23352]
### System info
- Playwright Version: [v1.27]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

### Source code

```
const computedStyle = await locator.evaluate((element) => {
	return window.getComputedStyle(element);
}, { timeout: 100 });

```

**Steps**
- [Run the test]

**Expected**

Timeout value should be respected in a positive or negative scenario.

**Actual**

If `evaluate` can pass, the timeout value isn't respected. Putting the timeout a 1 ms when the test takes 50ms doesn't timeout the evaluate. If the locator is bad and takes longer than the timeout, the timeout is not respected, but the test eventually times out from the playwirght config value.

**Comment by aslushnikov** [comment]
@perezdev the second argument in `locator.evaluate()` is an argument for the `pageFunction`; you should pass in a third parameter instead.

```ts
const computedStyle = await locator.evaluate((element) => {
  return window.getComputedStyle(element);
}, undefined, { timeout: 100 });
```

hope this helps!

**Comment by perezdev** [comment]
@aslushnikov perfect! thanks!

**Comment by ivan-kleshnin** [comment]
@aslushnikov I see that `evaluate` does support 3rd argument but `evaluateAll` does not 😞 

```ts
await myLocator.evaluate(node => {
          ...
}, undefined, {timeout: 500})

// FINE
```

```ts
await myLocator.evaluateAll(node => {
          ...
}, undefined, {timeout: 500})

// TS2554: Expected 1-2 arguments, but got 3.
```
