### ISSUE TITLE
[Feature] please help add zoom in and zoom out feature in beforeAll and beforeEach hook 

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#23357]
[Feature] please help add zoom in and zoom out feature in beforeAll and beforeEach hook 

Observation : as per the observation at this point of time we could able to zoom in and out on particular page but i could not find any option to set the zoom level of browser in before hooks, if possible please help provide the option 

it would be more helpful

**Comment by aslushnikov** [comment]
Dupe of https://github.com/microsoft/playwright/issues/2497

**Comment by ajaygoutham1995** [comment]
HI @aslushnikov 
any update on this feature request like when this can be done ?

**Comment by aslushnikov** [comment]
@ajaygoutham1995 there's no ETA on it, and it's not in the works currently.
