### ISSUE TITLE
Require individual test level reports to be created for each test method

### ISSUE THREAD

**Issue by saikiran40cs** [microsoft/playwright#23358]
The idea is to have individual test reports created for each test method calls.

We are trying to integrate with the Test management tools and it requires for each test result to be mapped to each test case.
When we tried using the default reporters it is not possible to seperate out the individual test cases as all the reports are in one report.

We cannot attach the same report for all test cases which defeats the idea of the test evidences.

Can we please have this feature enabled in the reports.

![image](https://github.com/microsoft/playwright/assets/6228048/bb03b25f-116e-48f6-b450-cad5174fbece)

**Comment by gskierk** [comment]
You can create you own reporter. Then you will have access to every single test and its corresponding result.

**Comment by aslushnikov** [comment]
@saikiran40cs the solution would be to either write your own [custom reporter](https://playwright.dev/docs/next/test-reporters#custom-reporters), or to use & post-process the JSON report. 

Hope this helps!
