### ISSUE TITLE
[BUG] new UI mode setInputFiles not working

### ISSUE THREAD

**Issue by Nerijus123** [microsoft/playwright#23366]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [Windows 11]
- Browser: [Chrome]

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'Chrome',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
  ],
});
```

**Test file (self-contained)**

```js
test('user should upload too big file and expect error appears successfully', async ({ page }) => {
    await page.getByTestId('upload-file-input').setInputFiles('./Assets/11mbphoto.jpg')
    await expect(page.getByText('Error: file size is too big')).toBeVisible()
    await expect(page.locator('div').filter({ hasText: /^Next step$/ })).not.toBeVisible()
  })
```

[Describe actual behavior]

if you run this test with setInputFiles in new ui mode test will fail, becouze file not uploaded. 
![image](https://github.com/microsoft/playwright/assets/29463426/90a9710a-807a-4ff2-afa0-a6409d6827c2)

if you run same test in vs code headless mode it pass 
![image](https://github.com/microsoft/playwright/assets/29463426/d8c3e9b4-a8b0-4ff8-ace6-174a704745f9)

**Comment by aslushnikov** [comment]
@Nerijus123 i tried creating a new project, installing `@playwright/test` there, and the following snippet worked just fine:

```ts
import { test, expect } from '@playwright/test';

test('s', async ({ page }) => {
  await page.setContent(`
    <input type=file>
    <script>
      document.querySelector('input').addEventListener('change', e => {
        const h1 = document.createElement('h1');
        h1.textContent = 'FILE SELECTED';
        document.body.append(h1);
      }, false);
    </script>
  `);
  await page.setInputFiles('input', __filename),
  await expect(page.locator('h1')).toBeVisible();
});
```

Can you try running this? Does it work for you? Can you also provide us with a similar repro that demonstrates the issue?

**Comment by Nerijus123** [comment]
hey @aslushnikov thank you for answer me and sorry for delay. The code you provide me works fine in both mods npx playwright test --ui and vs code. I thought the problem is with the file being too heavy, try to upload file witch is 10mb+. im trying with this. 
![image](https://github.com/microsoft/playwright/assets/29463426/e894beae-a487-4b67-a60b-36b4d0aad0a6)
Maybe its too havevy file size for ui mode?  when I change to another file working fine.
