### ISSUE TITLE
[BUG] In component testing - wrong api remote calls always return 200

### ISSUE THREAD

**Issue by shairez** [microsoft/playwright#23364]
In component testing mode, every route redirects back to `index.html`, meaning that wrong or unmocked API calls don't return 500 but **always** return 200

This makes it hard to spot bugs or missing mocks.

### System info
- Playwright Version: v1.34.3
- Operating System: Windows 10
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/shairez/playwright-ct-remote-issue

**Steps**

1. Run `pnpm install`
2. Run `pnpm test-ct`
3. See it fails

**Expected**

[Describe expected behavior]

I expect the wrong api call to return status 500 (just like in e2e mode)

**Actual**

[Describe actual behavior]

Every wrong api call returns 200

**Comment by mxschmitt** [comment]
As a workaround you can do the following while I'll find out if we want to change defaults here:

```
diff --git a/playwright-ct.config.ts b/playwright-ct.config.ts
index a2c94b7..4350b73 100644
--- a/playwright-ct.config.ts
+++ b/playwright-ct.config.ts
@@ -26,6 +26,9 @@ export default defineConfig({
 
     /* Port to use for Playwright component endpoint. */
     ctPort: 3100,
+    ctViteConfig: {
+      appType: 'mpa',
+    }
   },
 
   /* Configure projects for major browsers */
```

**Comment by shairez** [comment]
That's amazing! thanks very much for the quick response and fix @mxschmitt ! 🙏
