### ISSUE TITLE
[Question] Toggle offline state mid-test?

### ISSUE THREAD

**Issue by zsbrown97** [microsoft/playwright#23367]
I'm currently trying to write tests for my app to cover offline functionality. The idea is that the user flow being tested will be slightly different if the user disconnects from the internet but reconnects later, but I only want this to apply for a specific test file.

I tried adding `test.use({ offline: true })` to the file in question, but whenever I run the test I have it instantly throws
```
Error: page.goto: net::ERR_INTERNET_DISCONNECTED at http://localhost:3000/
```

For starters, is this something that can even be done? I would assume that, even if there's no internet, if the program is still run locally, it should still be able to access localhost, but maybe I'm misunderstanding how things work under the hood.

Secondly (and honestly probably the question I should be asking), is there a way to toggle an "offline" state with tests? For this particular instance, I'd like to run the test normally, but then at some point switch the app to be offline, run through more of the test, and then switch back online before the test ends.

**Comment by aslushnikov** [comment]
@zsbrown97 You can just use the [`browserContext.setOffline()`](https://playwright.dev/docs/next/api/class-browsercontext#browser-context-set-offline) method to toggle the offline mode in tests. Is this what you're looking for?

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale. Please create a new issue with a detailed reproducible or feature request if you still face issues.
