### ISSUE TITLE
[BUG] tracing.stop() fails due to missing network file

### ISSUE THREAD

**Issue by mook-as** [microsoft/playwright#23379]
### System info
- Playwright Version: `@playwright/teset@1.34.3`
- Operating System: OpenSUSE Leap 15.4
- Browser: Electron
- Other info:

https://github.com/microsoft/playwright/blob/6db64985656b5a536b9aa8f1405356380dbc5d58/packages/playwright-core/src/server/trace/recorder/tracing.ts#L176
That line needs an `await`.

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

Unfortunately, I am having difficulty producing a minimal test case.
I am seeing errors along the lines of:
> tracing.stop: ENOENT: no such file or directory, open '/tmp/playwright-artifacts-GZT396/0ff296554d68f4361c8d9ce7c529610f-pwnetcopy-1.network'

This happens when there's a test failure, and on per-describe `afterAll` I'm calling  (effectively) `_electron.launch().context().tracing.stop()`.  This also produces truncated trace zip files (which are unusable).  Manually hacking the installed `playwright-core` to add an `await` at the indicated position fixes the issue.

While my repository is at https://github.com/mook-as/rd/ I doubt that will be useful in reproducing the bug.

**Steps**
- Run the test (`npm run test:e2e e2e/preferences.spec.ts` in my repo).
- When it fails, try to use the produced trace file (`e2e/reports/*.zip` in my case) at https://trace.playwright.dev/

**Expected**

The trace zip file works correctly.

**Actual**

The trace zip file is truncated, because an exception was thrown in the middle of writing it.

**Additional Information**

I'm not certain I can deal with the CLA, so I'm not producing a PR directly. Sorry about that.

**Comment by aslushnikov** [comment]
So unfortunately this is hard to act upon without a repro that we can reproduce. I'll have to close this now, but please do not hesitate to file a new issue once you have a repro!
