### ISSUE TITLE
[Feature] Watch mode inside Visual Studio Code

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#23372]
Would be great to have a watch mode in vscode similar to the one in `--ui` mode:

<img width="1091" alt="watch-mode-vscode" src="https://github.com/microsoft/playwright/assets/17591696/4e63f3b9-bb81-4e8e-8b15-0beb080d86f6">

Related to: https://github.com/microsoft/playwright/issues/21960 and https://github.com/microsoft/playwright/issues/7035

**Comment by pavelfeldman** [comment]
Blocked by https://github.com/microsoft/vscode/issues/183993

**Comment by sand4rt** [comment]
Watch mode in VSCode is currently in prerelease stage😄: https://www.youtube.com/watch?v=ySBp6Kj0PVc&t=848s

**Comment by mxschmitt** [comment]
This is done.
