### ISSUE TITLE
[Feature] use the new headless mode for chromium

### ISSUE THREAD

**Issue by joerg1985** [microsoft/playwright#23389]
For newer chromium (and edge) versions the new headless mode should be used.
https://developer.chrome.com/articles/new-headless/

The [current flags](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/chromium/chromium.ts#L299) will start the old headless mode.

**Comment by mxschmitt** [comment]
Playwright also supports it. See https://github.com/microsoft/playwright/issues/21194#issuecomment-1444276676 how to set it, but be aware that its much slower: https://github.com/microsoft/playwright/issues/21216#issuecomment-1446678795

**Comment by joerg1985** [comment]
@mxschmitt how about updating the inline documentation of the LaunchOptions how to use the new mode and the downside of it?

**Comment by mxschmitt** [comment]
We have it here for Chrome Extensions: https://playwright.dev/docs/chrome-extensions#headless-mode

For other use-cases we still suggest the normal old headless mode. Since we don't run any tests with it, we can't recommend it as of today to our customers. What is your use-case?

**Comment by mirao** [comment]
https://developer.chrome.com/docs/chromium/headless mentions this
> Note: We intend to remove the old Headless from the Chrome binary and stop supporting this mode in Puppeteer in 2024. Simultaneously, we'll make old Headless mode available as a standalone binary for users who can't upgrade yet.

Not sure how this info is related to the Playwright's Chromium binary. Just FYI.

**Comment by joerg1985** [comment]
Looks like the old mode is gone in v132 

https://developer.chrome.com/blog/removing-headless-old-from-chrome

**Comment by mirao** [comment]
The new headless mode works for us since Playwright 1.49 where the support is provided officially (https://github.com/microsoft/playwright/releases/tag/v1.49.0). More info in https://github.com/microsoft/playwright/issues/33960#issuecomment-2556462258.
