### ISSUE TITLE
[Feature] Automatically transform special characters in test name to avoid file overwrite in results folder (e.g. video recording)

### ISSUE THREAD

**Issue by xsjcTony** [microsoft/playwright#23386]
Consider the following test

```ts
test.describe('this is a test suite', () => {
  // these are all `**-a-b-**` ❌
  test('a > b', async () => { expect(1).toBe(1); });
  test('a = b', async () => { expect(1).toBe(1); });
  test('a < b', async () => { expect(1).toBe(1); });
  test('a + b', async () => { expect(1).toBe(1); });
  test('a # b', async () => { expect(1).toBe(1); });

  // this will result in `**-a---b-**` ✅
  test('a - b', async () => { expect(1).toBe(1); });

  // this will result in `**-a-test-b-**` ✅
  test('a test b', async () => { expect(1).toBe(1); });
)}
```

For the first 5 tests, the video recorded for earlier ones will be overwritten by the latest one, since the folder name all resolves to `**-a-b-**` that those special characters got ignored. I don't think it's developer's responsibility to make test name `fs.safe`, since it makes sense to use special characters like `>` or `<` to replace `greater than` or `smaller than`, etc.

![image](https://github.com/microsoft/playwright/assets/45784210/7f4f4622-c6e3-42df-972d-b0505f8109d5)

![image](https://github.com/microsoft/playwright/assets/45784210/ed3ac584-e5b1-4ddd-8b55-3c9773a05baf)

**Comment by pavelfeldman** [comment]
Unfortunately fixing this will break existing users.

**Comment by xsjcTony** [comment]
:( Fine, it makes sense. But I think it could be better if this could be mentioned explicitly in the doc so others won't fall into the trap
