### ISSUE TITLE
[BUG] Webkit browsers running in the docker container do not apply cookies correctly on context.request.*

### ISSUE THREAD

**Issue by PaulWild** [microsoft/playwright#23390]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [mcr.microsoft.com/playwright:v1.34.3-jammy]
- Browser: [WebKit]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[Github repo](https://github.com/PaulWild/playwright-example) This repo has two endpoints `set-cookies` that adds two cookies to the document `__cookie.0` and `__cookie.1`. A second endpoint `check-cookies` checks that these cookies are in the same order as they were added. if not that endpoint returns a 400 response.  There is a test that calls both endpoints and asserts that the endpoints return a 200 response. 

**Steps**
- Build the docker container
- This will run the example test in the repo

**Expected**

All browsers pass

**Actual**

Webkit Browsers Fail.

Why this is an issue: We use [next-auth](https://next-auth.js.org/) in our project. When the cookies used by next auth are too big they get chunked eg `__cookie.0` & `__cookie.1` and the library relies on the cookies being in the same order as they were placed on the document. 

When running the tests using a webkit browser in the container these cookies are in a different order meaning that the authorisation calls fail.

**Comment by mxschmitt** [comment]
I can reproduce. Note: Tested that this is not libsoup3 vs. libsoup2 related.

**Comment by yury-s** [comment]
Fixed by https://github.com/microsoft/playwright/pull/24211
