### ISSUE TITLE
[Feature] Add path and query params | feature -> acceptable? PR

### ISSUE THREAD

**Issue by Kranael** [microsoft/playwright#23404]
I will reference here -> https://github.com/microsoft/playwright/issues/19839

**Let us know what functionality you'd like to see in Playwright and what your use case is.**
and use it:
```
const capitalResponse = await request.get('https://restcountries.com/v3.1/name/{name}', {
        pathParams: {
            'name': 'denmark'
        },
        queryParams: {
            'fields': 'capital,languages',
        }
    });
```

I would also just add here pathParams {} and queryParams {} and not replace params {} itself or touch it. So there is not breaking change here. Ofc there would be 2 params that will do the exact thing "queryParams" and "params" but for the improvement for now it could stay that.

Also the pathParams would be dynamic so as described in 19839 it would be string interpolation used to achieve that dynamic.

path params in this way are used by many frameworks in many languages ->
Fast-API https://fastapi.tiangolo.com/tutorial/path-params/
SpringBoot https://www.baeldung.com/spring-requestparam-vs-pathvariable
Gin https://gin-gonic.com/docs/examples/param-in-path/

also testtools use it like postman -> https://learning.postman.com/docs/sending-requests/requests/

**Do you think others might benefit from this as well?**
currently params is only for query parameter but params as a word do not specify this clearly. Some could think there must be a option for path parameter because its a common practice in rest and a standard. So splitting this up without touching params itself and just adding queryParams and pathParams should clearly be understandable and also better maintainable in future.

finally it would have this 2 new objects:
```
pathParams: {
            'name': 'denmark'
        },
        queryParams: {
            'fields': 'capital,languages',
        }`
```

**What I want to know here is:**

- **Would you be open for a pull request for that feature or not?**

Because I really love your framework but in API testing what is what i daily do it is lacking features. Yes I could use Java and RestAssured but then i need all that bloated java ecosystem. I need maven/gradle, I need to compile, I need that OOP in testing classes and that annotations and the method chaining for some simple strings and so on. I would like to avoid that so that's the reason we use playwright instead of restAssured.

->
I think i would need to touch .\tests\library\browsercontext-fetch.spec.ts correct me if I'm wrong because there is the export abstract class APIRequestContext correct?

**Comment by Smrtnyk** [comment]
why so complicated and added complexity when you can use URL constructor to set query params elegantly?
as for pathname params that just looks like a bloat to me

just my opinion as playwright community member and advanced user
(advanced because we use heavily playwright for testing with over 2k tests)

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/19839
