### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by rmkranack** [microsoft/playwright#23415]
We are in the process of converting our tests from TestCafe to Playwright. We have a test the uses an api to get a password rest email. The response is an html page for the password reset. The api works properly in TestCafe and Postman but returns <Buffer 5b 5d> in Playwright. I tried .body(), .text(), .json() for the response and no luck with any. 

### System info
- Playwright Version: [v1.34.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
<img width="931" alt="image" src="https://github.com/microsoft/playwright/assets/7255854/5cb647a4-f9a3-48a3-81d5-8a82d7a65fd2">

    const getApiForgotPasswordEmail = await this.apiContext.get(process.env.MAILTRAP_API+'/messages/'+resetEmailId+'/body.html',
      {
        headers:{
          'Accept': 'text/html, application/json',
          'Authorization': process.env.MAILTRAP_TOKEN,
          },
      })

      expect(getApiForgotPasswordEmail.ok()).toBeTruthy();
      const forgotPasswordEmailResponseCode = await getApiForgotPasswordEmail.status();
      console.log(forgotPasswordEmailResponseCode);
      const forgotPasswordEmailBody = await getApiForgotPasswordEmail.body();
      console.log('email body:');
      console.log(forgotPasswordEmailBody);

- [X ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```
await apiUtils.getForgotPasswordEmail(newPatientNumber);
```

**Steps**
- [Run the test]

**Expected**

The html for an email will be returned. 

This is an example what is returned when the test is ran with TestCafe
<img width="606" alt="image" src="https://github.com/microsoft/playwright/assets/7255854/be718df4-5a58-45ef-900a-1e245aee86b1">

**Actual**

Receive  the response <Buffer 5b 5d>

**Comment by mxschmitt** [comment]
`body()` will return the content as a Buffer. If you want to get the text, you can just do: `await getApiForgotPasswordEmail.text()`

**Comment by rmkranack** [comment]
.text() comes back empty
<img width="932" alt="image" src="https://github.com/microsoft/playwright/assets/7255854/f176f580-4626-4114-8c03-c9d5bfcdb580">

**Comment by mxschmitt** [comment]
You could set the `DEBUG=pw:api` env var to find more out on how the response looked like. But this most likely means that your server did return some unexpected response, e.g. due to wrong request headers.

**Comment by rmkranack** [comment]
Thanks for the logging tip. That helped to see what the issue was. It was a problem with the headers. Thanks for the help!
