### ISSUE TITLE
[REGRESSION] Trace has only 1 browser in timeline/snapshots

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#23421]
This issue makes it impossible to use trace in cases with more than 1 browser when need to debug what happened in another browser as info is missing

### System info
- Playwright Version: [v1.34.4]
- Operating System: [ macOS 13.24  ]
- Browser: [ Chromium]
- Other info: it was ok in 1.33

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
    trace: 'on',
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
test('has title', async ({browser, page}) => {
    const page2 = await (await browser.newContext()).newPage()
    await page.goto('https://playwright.dev/');
    page2.goto("https://google.com")
    await expect(page).toHaveTitle(/Playwrighty/);
    await page2.context().close()
});

```

**Steps**
- [Run the test]
- [Open trace]

**Expected**

2 browsers are shown in trace

**Actual**

only 1st browser is there

![Screenshot 2023-06-01 at 09 32 38](https://github.com/microsoft/playwright/assets/7899764/4aaa0aee-1b8f-4e6b-ac0c-92697ca71b8a)
[be984cadb2f0845412b9392460292ffed8396e33.zip](https://github.com/microsoft/playwright/files/11621855/be984cadb2f0845412b9392460292ffed8396e33.zip)

**Comment by mxschmitt** [comment]
Was able to reproduce.

Bad: 1.34.0-alpha-may-6-2023
Good: 1.34.0-alpha-may-1-2023

the stuff in between had missing steps.

diff: https://github.com/microsoft/playwright/compare/1168525c07dcc96fb47b5464b9f6d4d9a6b4616f...03616e976ef9ecdeeba10a748a2a75f71a20df71

**Comment by pavelfeldman** [comment]
It has been fixed on @next.

**Comment by mxschmitt** [comment]
Can confirm things are fixed on @next: https://playwright.dev/docs/canary-releases

**Comment by dimkin-eu** [comment]
this means 1.34.4 or 1.35 ?

**Comment by mxschmitt** [comment]
(1.35)
