### ISSUE TITLE
[Feature] Add getByURL Locator Method

### ISSUE THREAD

**Issue by RyanJeavo** [microsoft/playwright#23427]
I recently found myself needing to interact with some of the hyperlinks on our front end. 

It would be great to have a simple and concise way to:
- Check my hyperlink is visible
- Check that the URL is as I expect
- Ensure the hyperlink is within viewport of our customers
- Click the link 

The current method I'm using to handle this requirement is:
```
const URL: Locator = this.page.getByRole('link', { name: linkText });
expect(await URL.getAttribute('href')).toContain(hyperlinkURL);
```

It would be a handy little addition to have the following:
```
await expect(page.getByURL(urlVariableHere)).toBeVisible();
```

or 

```
const myURL: Locator = this.page.getByURL(urlVariableHere)

expect(this.myURL).toHaveText(hyperLinkTextHere);
expect(this.myURL).toBeVisible();
await this.myURL.click()
```

**Comment by mxschmitt** [comment]
sounds like a good workaround which you have! You can also always do: 

```ts
const myLink = page.locator('a[href="/account/login"]');
await expect(myLink).toBeInViewport()
await expect(myLink).toHaveText('foobar')
```

**Comment by mxschmitt** [comment]
Actually we recommend:

```ts
const myLink = this.page.getByRole('link', { name: linkText });
await expect(myLink).toHaveAttribute('href', '/foobar');
await expect(myLink).toBeInViewport()
```

since selecting by what the user will see is already performing an accessibility check as a drive-by and the error reporting will be more pretty when the element is not there etc.

Closing as per above, hope it helps!
