### ISSUE TITLE
more flaky tests when workers count is increased also Authentication issue

### ISSUE THREAD

**Issue by chaitraAshu** [microsoft/playwright#23436]
Hello Team,

I have this piece of code to login to application by entering username, password, org ID then click on login. To verify successful login checking visibility of a locator LOC_USERNAME_MENU.

From CI/CD Jenkins pipeline:
When I run using one worker things goes well. however  increasing workers to 5 I see more flaky tests. most of them are failed during LOC_USERNAME_MENU visibility check after successful login. 
From screenshot I see "you are not Authorized to authenticate" error message on the page.

I'm using retries option too. But not helped. In all the tries Its failed at the same login flow.
Locally I can't re produce this. 
Code :
```
await this.enterUsername(userRole.username);
      await this.enterOrganization(userRole.org);
      await this.enterPassword(userRole.password);
      await this.clickOnLogin();
const userName = webActions.page.locator(this.LOC_USERNAME_MENU);
    await expect(userName).toBeVisible({ timeout: ConstUtils.SIXTY_SEC });
    console.log('User successfully logged in.');
```
I'm Using POM. this code is kept in signin page class and called inside spec file. I have different users to login for each tests.
From Spec :
```
import * as login from '../../../common/users.json';
import test from '../../../common/fixtures/base-page';

test('Example Spec', async ({
  landingPage,
  HomePage,
  webActions,
  commonFunctionsPage
}) => {
  await test.step('Navigating to the Portal', async () => await landingPage.navigateToPortal());

  await test.step('Login to the portal with user ', async () => {
    await landingPage.loginToPortal(login.user);
    await HomePage.checkURL();
  });
```
Please help me to solve this problem.

**Comment by chaitraAshu** [comment]
> This sounds like that your CI system is overloaded, see [here](https://playwright.dev/docs/ci#workers) for more information about that. So its recommended to have less workers on CI systems.
> 
---with one worker  tests run time is increases. do you think sharding will help ?

> You can re-use your login, so its only done once, see [here](https://playwright.dev/docs/auth) - or are you doing it already?
-- I can't re use login because I have to use different users in tests.

**Comment by mxschmitt** [comment]
closing as per above.
