### ISSUE TITLE
[Feature] Chromium does not show file chooser dialog

### ISSUE THREAD

**Issue by anonymousaccn** [microsoft/playwright#2344]
I would love to see Playwright to support custom executable path for browser. The main reason is in the latest ( at the time I write this message ) version, chromium doesn't support file chooser ( no dialog is opened ) however stable chrome works just fine.

**Comment by yury-s** [comment]
You can pass custom `executablePath` as one of the launch [options](https://github.com/microsoft/playwright/blob/master/docs/api.md#browsertypelaunchoptions), doe it not work for some reason?

**Comment by anonymousaccn** [comment]
Thanks for pointing out, I will try that out.

**Comment by dgozman** [comment]
Note that Playwright is not guaranteed to work correctly with custom browser executable. However, most of the times things should be ok.

**Comment by pavelfeldman** [comment]
@anonymousaccn : please don't point to the older Chromium, things won't work there. When you say file chooser is not opened you mean you don't see it in the `headless: false` mode? That's the new behaviour for Chromium and if you'd like it changed, please let us know. What is your scenario?

**Comment by anonymousaccn** [comment]
@pavelfeldman The problem I have with latest playwright if when I use Chromium I got an error called "Failed to fetch ... " 
And for Firefox, I got an error regarding network ... 
I will post full error when I get home. 

And for webkit on windows, file upload dialog is not opened at all, it works on Mac.

**Comment by anonymousaccn** [comment]
> Note that Playwright is not guaranteed to work correctly with custom browser executable. However, most of the times things should be ok.

Yes, I can see this possible.

**Comment by pavelfeldman** [comment]
@anonymousaccn: please let us know what you find - we have all the file chooser tests passing, so it'd be interesting to learn what went wrong. Let me rename the issue.

**Comment by aslushnikov** [comment]
Looks like the discussion here stalled, so closing this.

@anonymousaccn feel free to follow up here or file a new issue, if necessary!
