### ISSUE TITLE
[BUG] [Jest] Cannot find 'core-js/modules/es.array.fill'

### ISSUE THREAD

**Issue by mconnol6** [microsoft/playwright#2345]
**Context:**
- Playwright Version: 0.14.0
- Operating System: Windows
- Node version: 12.16.3
- Browser: Chromium
- Extra: Using Jest testing framework

**Code Snippet**

```javascript
import playwright from 'playwright';

describe(`UI Tests with Playwright`, () => {

    test(`Should load page`, async () => {
        let browser = null;
        let page = null;    

        browser = await playwright.chromium.launch({headless:false});
        page = await browser.newPage();
        await page.goto('https://github.com/microsoft/playwright/tree/master/docs', {
            waitUntil: 'networkidle0',
        });
        await page.fill('input.header-search-input', 'search term');
        await browser.close();
    });
});
```

**Describe the bug**

I am receiving this error: 
Cannot find module 'core-js/modules/es.array.fill' from 'spec/test.ts'
at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:308:11)
at Object.<anonymous> (spec/test.ts:5:1)

I am only receiving an error when I use the 'fill' function. I'm able to use other functions, such as click, waitForSelector, screenshot, etc.

Any ideas? Is this an issue or conflict with Jest?

**Comment by pavelfeldman** [comment]
Looks like your transpiler converts `page.fill` into `Array.fill`.

**Comment by pavelfeldman** [comment]
Maybe Maxes know. ^^ @mmarkelov, @mxschmitt

**Comment by mxschmitt** [comment]
Hi @mconnol6 would be awesome if you could share us your Jest configuration so we have more insights how your environemnt looks like. Do you run your tests using the `jest` command?

**Comment by mconnol6** [comment]
Here is the jest config:

`module.exports = {
    verbose: true,
    resetMocks: true,
    resetModules: true,
    restoreMocks: true,
    moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
    setupFilesAfterEnv: [path.resolve(__dirname, './test/setupTests.ts')],
    reporters: ['default', ['jest-junit', { outputDirectory: 'coverage' }]],
    coverageReporters: ['json', 'lcov', 'text', 'clover', 'cobertura', 'html'],
    moduleNameMapper: {
        '.(scss|jpg|png)$': path.resolve(__dirname, './test/empty-module.ts'),
    },
    // tell babel to travel to the root for babel.config.js
    transform: { '^.+\\.[t|j]sx?$': [ 'babel-jest'] },
    roots: ['<rootDir>/spec/'],
    testTimeout: 60000,
};`

Here is the babel config:

`module.exports = function(api) {
    api.cache(true);

    return {
        presets: [
            [
                '@babel/preset-env',
                {
                    useBuiltIns: 'usage',
                    corejs: 3,
                    targets: {
                        browsers: ['> 0.1%', 'last 3 versions', 'ie 11'],
                    },
                },
            ],
            '@babel/react',
            '@babel/preset-typescript',
        ],
        plugins: [
            '@babel/transform-runtime',
            '@babel/plugin-transform-typescript',
            '@babel/plugin-proposal-class-properties',
        ],
    };
};`

I'm using yarn to run the tests:

`yarn test`

I'm using ...
yarn v 1.22.4 
jest v 26.0.1
babel-jest v 26.0.1

Anything else that would be helpful?

**Comment by mmarkelov** [comment]
@mcb0035 youp! Seems like a bug in **babel** or **babel-jest**, I just don't have experience with **babel-jest** maybe there is some ways to skip this converting. This is not **playwright** bug

**Comment by pavelfeldman** [comment]
@JoelEinbinder : could this be a babel transpilation bug?

**Comment by mconnol6** [comment]
Thanks for your help! I will open a bug with Babel instead.

**Comment by pavelfeldman** [comment]
Looks like resolved w/ changes to babel setup.
