### ISSUE TITLE
[QUESTION] Can't run Profile with signin account edge

### ISSUE THREAD

**Issue by nguyenthanhtien** [microsoft/playwright#23458]
### System info
- Playwright Version: 1.34.3
- Operating System: Windows 11
- Browser: Edge
- Other info:

### Source code

I want run profile Edge already login on Edge with playwright, but when i try run it, we can't start that profile with user already sign-in. 

**Test file (self-contained)**

```js
  let browser = await chromium.launchPersistentContext('C:\\Users\\nguye\\AppData\\Local\\Microsoft\\Edge\\User Data\\' + profileName, {
    headless: false,
    channel: 'msedge',
    executablePath: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
    args: [
      '--no-sandbox',
      '--disable-gpu',
      '--enable-webgl',
      '--profile-directory=' + profileName,
    ]
  });

  let page = await browser.newPage();

```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
This works for me, could you try to adjust this to your needs?

```ts
import { chromium } from 'playwright';

(async () => {
  // Setup
  const context = await chromium.launchPersistentContext('/Users/maxschmitt/Library/Application Support/Microsoft Edge/', {
    channel: 'msedge',
    headless: false,
    args: ['--profile-directory=Default']
  });
  const page = await context.newPage();

  await page.pause();
  await context.close();
})();
```

You don't need to specify executablePath if you set the channel already.

**Comment by nguyenthanhtien** [comment]
But it still not work

**Comment by mxschmitt** [comment]
I tried the following on my Windows machine, which works as well:

```ts
import { chromium } from '@playwright/test';

(async () => {
  // Setup
  const context = await chromium.launchPersistentContext('C:\\Users\\maxschmitt\\AppData\\Local\\Microsoft\\Edge\\User Data', {
    channel: 'msedge',
    headless: false,
    args: ['--profile-directory=Default']
  });
  const page = await context.newPage();

  await page.pause();
  await context.close();
})();
```

Make sure that you close all instances of Microsoft Edge before running it. (Check the task manager)

**Comment by nguyenthanhtien** [comment]
Step reproduce:
1-Create new Profile.
2-Login microsoft account with new Profile (Profile 2)
3-Using Playwright open "Profile 2".

**Comment by aslushnikov** [comment]
Issues with certain browser behaviors triggered by a combination of browser switches fall outside of the scope of the Playwright project, so I'll have to close this.
