### ISSUE TITLE
[BUG] Tracing snapshots not preserving scrollTop

### ISSUE THREAD

**Issue by issacgerges** [microsoft/playwright#23455]
### System info
- Playwright Version: [v1.34]
- Operating System: [All]
- Browser: [All]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**
```html
<!DOCTYPE html>
<html>
  <head>
    <style>
      #list {
        width: 200px;
        height: 300px;
        overflow: auto;
      }
      .item {
        height: 20px;
      }
    </style>
  </head>
  <body>
    <button id="button">Scroll to Halfway</button>
    <div id="list"></div>

    <script>
      // Create list of 100 numbered items
      var list = document.getElementById("list");
      for (var i = 1; i <= 100; i++) {
        var listItem = document.createElement("div");
        listItem.className = "item";
        listItem.textContent = "Item " + i;
        list.appendChild(listItem);
      }

      document.getElementById("button").addEventListener("click", function () {
        var listItemHeight = document.querySelector(".item").offsetHeight;
        list.scrollTop = listItemHeight * 50;
      });
    </script>
  </body>
</html>
```

```js
test('has a scrolling container', async ({ page, context }) => {
  await context.tracing.start({ screenshots: true, snapshots: true });
  await page.goto('file:///<path>/example.html');
  await page.click('#button');
  await page.waitForTimeout(1000);

  // attempt to force __paywright_target by interacting directly with the element
  await expect(page.locator('#list')).toBeAttached();

  await context.tracing.stop({ path: 'trace.zip' });
});
```

**Steps**
- Run the test
- Open the trace

**Expected**

The snapshot and screenshots should both show a scrolled container

**Actual**

The container is not scrolled in the snapshots, but is in the screenshots

### Notes
In our actual app, we render lists that are pinned initially to the bottom. This is done by rendering content, then immediately setting `scrollTop`. In our snapshots (and in the example above) `scrollTop` is not preserved/restored. From reading the code, an [interacted](https://github.com/microsoft/playwright/blob/0a6fe3fac5b05a8c65c46f3c548d8b2c1bfa6664/packages/playwright-core/src/server/frames.ts#L1412) element should be noted as a `__playwright_target__` and its scroll position [should be preserved](https://github.com/microsoft/playwright/blob/0a6fe3fac5b05a8c65c46f3c548d8b2c1bfa6664/packages/playwright-core/src/server/trace/recorder/snapshotterInjected.ts#L322). That doesn't seem to work and even if it did work, ideally we wouldn't need to interact with the element. 

Please let me know if there is another way to hint to playwright that we want these values preserved

**Comment by mxschmitt** [comment]
Good findings! I can confirm after reverting https://github.com/microsoft/playwright/pull/14114 it works as expected.

**Comment by pmattj** [comment]
Thanks Issac and mxschmitt! 👏
