### ISSUE TITLE
[REGRESSION]: beforeEach/All fixtures behave different in v1.34.x from earlier versions

### ISSUE THREAD

**Issue by fspinillo** [microsoft/playwright#23453]
**Context:**

- GOOD Playwright Version: v1.33.x and earlier
- BAD Playwright Version: v1.34.x
- Operating System: Mac/Linux

**Code Snippet**
Fixture File:
```javascript
import type { Page} from '@playwright/test';
import { test as base } from '@playwright/test';

export interface MyFixtures {
  fixturePage: Page;
}

export const test = base.extend<MyFixtures>({
  fixturePage: async ({ browser }, use) => {
    const context = await browser.newContext()
    const newPage = await context.newPage()
    const fixturePage = newPage;
    await fixturePage.goto('https://playwright.dev/')

    await use(fixturePage);
    await fixturePage.goto('https://playwright.dev/docs/intro')
  },

});
export { expect } from '@playwright/test';
```

Test File:

```javascript
import { test } from '../../fixtures/fixtureTest';


test.describe('My test Describe', async () => {
  test.beforeAll(async ({ fixturePage}) => {
    await fixturePage.goto('https://playwright.dev/docs/api/class-playwright')
  } )
  test('My Test', async ({ page }) => {
    await page.goto('https://playwright.dev/community/welcome')
  })
})
```

**Describe the bug**

*Note*: Our fixture generates a new context so that we can leverage it in before calls, so the example above is an extremely simplified version of what is happening.

We recently bumped our Playwright version from v1.32.3to v1.34.3 and noticed tests using fixtures in `beforeAll` started to behave differently from our tests using fixtures in `beforeEach`. 

If you have v1.34.x installed and run the above test with `beforeAll`, Playwright will execute the fixture correctly but then it performs the steps after `await use(fixturePage)` immediately. It does not wait for the `My Test` to complete before it calls `await use(fixturePage)`.

If you change it to `beforeEach`, it will wait for `My Test` to fully finish before it calls `await use(fixturePage)`.

If you revert back to v1.33.x and re-rerun the tests with beforeEach/All they both perform the same way.

As I understand it when using a fixture anything that comes after `use` is a sort of clean up step and is meant to execute when the actual test finishes. Is this not what happens? I've looked through the Changelogs and reviewed all the documentation again on hooks, but I'm not seeing anything that was different from when we first made our fixtures.

**Comment by dgozman** [comment]
This was intentionally changed in #22746.

Previously, playwright had a bug where fixtures (like `fixturePage`) were not teared down at the end of `beforeAll`. Since `beforeAll` runs once before multiple tests execute, and each test has its own copy of fixtures, `beforeAll` cannot share fixtures with any of the tests.

As you observed, `beforeEach` runs before each test, and so shares fixtures with the corresponding test. If you would like to share a fixture and run some code for each test, use `beforeEach`. If you need a once-per-multiple-tests setup, use `beforeAll`.

I hope this makes it clear. Let me see if I can update the documentation.

**Comment by fspinillo** [comment]
This makes sense, thanks for clarifying the change.

**Comment by mxschmitt** [comment]
Closing by that, thanks you both!

**Comment by dgozman** [comment]
Turned out, this is already described in https://playwright.dev/docs/test-fixtures#execution-order.
