### ISSUE TITLE
[BUG] How to pass a variable in page.on method? Is there should be a bug?

### ISSUE THREAD

**Issue by YusufOzt** [microsoft/playwright#23468]
I click a button before the page.on method. After clicking the button, a url is returned in the network request. When I add console.log into the getGenerateLinkResponse method, I can see the correct link in the console.log. My problem here is that when I call **process.env.LINK** inside the page.goto method in my **test.ts** file, I get an error because process.env.LINK returns undifened. While channels.ts is also returning correctly, I can't pass it into my test.ts file properly. I've tried many things and it didn't work. Could there be a bug here? If it is not bug,how can pass a variable into page.on to my test file?

channels.ts(page object model )
```
import { expect, Locator, Page } from "@playwright/test";
import { ChannelsState } from "playwright/tests/channels/channels.state";

export class ChannelPage {
  page: Page
  downloadGeneratedLinksBtn: Locator

  constructor(page: Page) {
    this.page = page;
    this.downloadGeneratedLinksBtn = page.locator(".export-btn-box>button")

  }

  
  async getGenerateLinkResponse() {
    this.page.on('requestfinished', async (request: any) => {
      if (request.url().match(/batch_shorten/)) {
        var res = await request.postDataJSON();
       process.env.LINK= await res.urls[0]
      }
    })
  }

}

```

test.ts

```
import { test } from "@playwright/test";
import { ChannelPage } from "./channels";

let channelsPage: ChannelPage;
test.beforeEach(async ({ page }) => {
    channelsPage = new ChannelPage(page)
});

test('has title', async ({ page }) => {
    await channelsPage.downloadGeneratedLinksBtn.click()
    await channelsPage.getGenerateLinkResponse()
    await page.goto(process.env.LINK)
  });
```

**Comment by mxschmitt** [comment]
I recommend to add a console.log before you set the value, my guess is that it gets overridden.

**Comment by YusufOzt** [comment]
@mxschmitt I added console.log in channels.ts before setting variable ir returns perfect. But did not pass it to outside the Page.on via setting variable

**Comment by mxschmitt** [comment]
Please don't cross-post issues, since it was also answered [on Discord](https://discord.com/channels/807756831384403968/1114178552519196672/1114214925376696400).

At least put a cross-reference there. Since you most likely want to wait instead of using .on(, see here: https://playwright.dev/docs/network#network-events

**Comment by YusufOzt** [comment]
@mxschmitt thanks for response ,Discord response also did not worked but found a way to pass variable. Thanks ,closing
