### ISSUE TITLE
[REGRESSION]: afterAll method in version 1.34 is closing browser after last test

### ISSUE THREAD

**Issue by greeyk** [microsoft/playwright#23465]
**Context:**
- GOOD Playwright Version: 1.30 - 1.33
- BAD Playwright Version: 1.34
- Operating System: Ubuntu 20.04.6 LTS

**Describe the bug**

Hello, after update playwright to 1.34 in my main repo i noticed that _afterAll_ method is failing my test cases. I used this hook to cleanup my test space. So far, the _afterAll_ method executes after the last test (probably in same browser as last test), in previous versions everything worked fine locally and on CI/CD. In version 1.34, I get an error about closing the browser/context/page after the last test, as a result, the test failing. I have prepared a minimal repository below with this error to reproduce. 

`  1) [chromium] › example.spec.ts:19:7 › has title › get started link ──────────────────────────────

    Error: page.goto: Target page, context or browser has been closed

       at page-object.ts:17

      15 |
      16 |   async visit() {
    > 17 |     await this.page.goto("https://playwright.dev/");
         |                     ^
      18 |   }
      19 |
      20 |   async clickGetStarted() {`

**Code Snippet**
*example.spec.ts*
```
import { test, expect } from "@playwright/test";
import TestClass from "./page-object";

test.describe("has title", async () => {
  let testClass: TestClass;

  test.beforeEach(async ({ page }) => {
    testClass = new TestClass(page);
    await testClass.visit();
  });

  test.afterAll(async () => {
    await testClass.visit();
    await testClass.clickCommunityLink();
    await testClass.docsLink.click();

  });

  test("get started link", async ({ page }) => {
    // Click the get started link.
    await testClass.clickGetStarted();
    await testClass.clickCommunityLink();
    await testClass.docsLink.click();
    // Expects the URL to contain intro.
    await expect(page).toHaveURL(/.*intro/);
  });
});
```

*page-object.ts*
```
import { Page, Locator } from "@playwright/test";

class TestClass {
  readonly page: Page;
  readonly getStartedButton: Locator;
  readonly communityLink: Locator;
  readonly docsLink: Locator;

  constructor(page: Page) {
    this.page = page;
    this.getStartedButton = page.getByRole("link", { name: "Get started" });
    this.communityLink = page.getByRole("link", { name: "Community" });
    this.docsLink = page.getByRole("link", { name: "Docs" });
  }

  async visit() {
    await this.page.goto("https://playwright.dev/");
  }

  async clickGetStarted() {
    await this.getStartedButton.click();
  }

  async clickCommunityLink() {
    await this.communityLink.click();
  }
}

export default TestClass;
```

**Comment by dgozman** [comment]
@greeyk Thank you for the issue. This was intentionally changed in #22746.

In this example, `page` fixture is opened and closed for each test. Since `afterAll` runs once after multiple tests execute, and each test has its own `page`, `afterAll` cannot share the `page` with any of the tests. Therefore, when `afterAll` tries to call `page.goto()` on it,  the page is already closed.

Previously, playwright had a bug where `page` was not closed after the last test, but it was fixed.

If you'd like to use the page from the last test, you have a few options:
- Put code from `afterAll` to the last test.
- Put code from `afterAll` to `afterEach` and run it after each test.
- Create a new `page` in the `afterAll` hook and leave code as is.

Let me know whether this helps.

**Comment by greeyk** [comment]
@dgozman Thanks for response. I created new page variable in afterAll method like below and now evertyhing works fine:
```
test.afterAll(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  testClass = new TestClass(page);
  await testClass.visit();
  await testClass.clickCommunityLink();
  await testClass.docsLink.click();
});
```

**Comment by mxschmitt** [comment]
Thanks!
