### ISSUE TITLE
[Question]re-try command

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2347]
> Auto-wait for elements to be ready before executing actions

we know some http request maybe failure, we often just refresh the browser ,if we automate browser command, the playwright implies re-try in auto-wait ?

**Comment by pavelfeldman** [comment]
Playwright will retry locating the button and clicking it, it won't reload the page. If http request that is needed to perform the click did not arrive, that's considered a bug.

**Comment by roughsoft** [comment]
@pavelfeldman 
I'm sure, you are facing random failure during an automated test run.So retry logic is must
. These failures might not necessarily be because of product bugs. 

These failure can be because of following reasons:

+Random browser issues 
+Browser becoming unresponsive
+Random machine issues
+Server issues like unexpected delay in the response from server
+Application not responding properly
+Application is very slow
+Network is very slow, hence app is very slow
+Ajax Component could not be loaded properly
+HTML DOM is slow

**Comment by pavelfeldman** [comment]
My take on this is that all of these are important signals that should be registered as test failures. Either as the failures or as the timeouts. You then apply the most-mortem filter to them to see if that is a blocker.

But in either case, retrying the failed test is up to your test runner harness, higher up the stack than the Playwright driver.

**Comment by roughsoft** [comment]
ok, thank you!
