### ISSUE TITLE
Documentation: globalTeardown config example is incorrect

### ISSUE THREAD

**Issue by reinierkaper-carewell** [microsoft/playwright#23482]
The docs for globalSetup/globalTeardown have this property located within the `use` property, which is incorrect (it should be in the root of the config): https://playwright.dev/docs/test-global-setup-teardown#configure-globalsetup-and-globalteardown

**Comment by mxschmitt** [comment]
Already fixed on next, gets live with the next release: https://playwright.dev/docs/next/test-global-setup-teardown#configure-globalsetup-and-globalteardown

Thanks for reporting tho!

**Comment by reinierkaper-carewell** [comment]
Apologies, I didn't realize that, thanks!
