### ISSUE TITLE
[Feature]Experimental Component Testing in Playwright + Python 

### ISSUE THREAD

**Issue by writetomaha** [microsoft/playwright#23497]
Hi All, 

we would like to see the experimental component testing in Playwright + Python. 
As i see most of web application build on js, currently experimental component testing supported by Playwright with Javascript.

**Comment by mxschmitt** [comment]
Component tests are in JS/TS because you can directly import the components which are written in JS/TS{x}. How would you like to use it in Python? Is there a specific Python framework you want to test against? Or React?

**Comment by writetomaha** [comment]
I would like to import the react components on the Pytest framework (rendering UI components), mock the API's, Interact with the component and verify output.

Integration Test or E2E i would like to do in Python.

**Comment by mxschmitt** [comment]
That’s unfortunately out of scope for the Playwright project. Component tests should be written in the same language as the components are written in.

For end-to-end tests you can get started in Python with Pytest today: https://playwright.dev/python/docs/intro
