### ISSUE TITLE
[BUG] Request payload always null

### ISSUE THREAD

**Issue by paradox37** [microsoft/playwright#23496]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium, Firefox]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```
import { test } from '@playwright/test';

test.describe('verify', async () => {
  test('test Case Name', async ({ page }) => {
    page.on('request', (request) => {
      if (request.method() === 'POST') {
        console.log(request.method());
        console.log(request.url());
        console.log(request.postData());
        console.log(request.postDataJSON());
        console.log(request.postDataBuffer());
      }
    });
    await page.goto('https://google.com');
    const inputs = await page.locator('[type="submit"]').all();
    await inputs[3].click();
  });
});
```

**Steps**
- [Run the test]

**Expected**
`postData` to return payload
`postDataJSON` to return payload
`postDataBuffer` to return payload

**Actual**
returns null

The test above returns null for `postDataJSON()` and for `postDataBuffer()` and for `postData()`. I also tried using page.WaitForRequest() to get the payload, but the same result, `null` instead of payload. I tried both Chromium and Firefox.

**Comment by mxschmitt** [comment]
Looks like https://github.com/microsoft/playwright/issues/6479

**Comment by igorMondu** [comment]
Yeah, it is, just found it after posting here. I am using RTK Toolkit in my project which is using request.clone(), and Chromium still didn't fix that issue.

**Comment by paradox37** [comment]
Yeah, it is, just found it after posting here. I am using RTK Toolkit in my project which is using request.clone(), and Chromium still didn't fix that issue.
