### ISSUE TITLE
[BUG] Unable to import types

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#2349]
**Context:**
- Playwright Version: v1.0.0-next.1590217523735
- Operating System: macOS
- Node version: 12.16.3
- Browser: Chromium

**Code Snippet**

```javascript
import { Page } from 'playwright-chromium';
```

**Describe the bug**

Hey team. After upgrading to the latest `@next` version today, I'm unable to import Playwright types into my code anymore. I'm guessing this is related to https://github.com/microsoft/playwright/pull/2318. Is there a different way to do this now or is this a bug in Playwright?

**Comment by pavelfeldman** [comment]
Thanks for the heads up! @aslushnikov ^^
