### ISSUE TITLE
[REGRESSION]: Execution Errors not Displayed at Point of Method Call in Spec File in VSCode

### ISSUE THREAD

**Issue by ch4r-ch4r** [microsoft/playwright#23506]
**Context:**
- GOOD Playwright Version: 1.33.0
- BAD Playwright Version: 1.34.3
- Operating System: Mac/Windows
- Extra: Using Playwright Test with VSCode and the Playwright VSCode extension,  Page Object Model (POM) approach.

**Code Snippet**
Here's the repo used for the bug report: [https://github.com/ch4r-ch4r/saucedemo](url)
Just toggle between Playwright versions and you will be able to see the difference in error highlighting.

```typescript
// loginPage.page.ts
import { Locator, Page } from "@playwright/test";

class LoginPage {
  private page: Page;
  private usernameInput: Locator;
  private passwordInput: Locator;
  private loginButton: Locator;

  constructor(page: Page) {
    this.page = page;
    this.usernameInput = this.page.locator('[data-test="username"]');
    this.passwordInput = this.page.locator('[data-test="password"]');
    // Deliberately changed the locator to "loginh" to force the failure
    this.loginButton = this.page.locator('[data-test="loginh-button"]');
  }

  async login(username: string, password: string) {
    await this.usernameInput.fill(username);
    await this.passwordInput.fill(password);
    await this.loginButton.click();
  }
}

// test.spec.ts
import { expect, test } from "../pages/basePage";

test("should login successfully", async ({ loginPage, page }) => {
  await loginPage.login("standard_user", "secret_sauce");
  await expect(page.getByText("Swag Labs")).toBeVisible();
});
```

**Describe the bug**

In Playwright version 1.33.0, when a test failed due to an error in a method from a POM class, the error was highlighted at the point of the method call in the test spec file.
<img width="1975" alt="SCR-20230604-dofv" src="https://github.com/microsoft/playwright/assets/78950093/f7f4572d-ca45-434c-9785-bbe89072b801">

However, in Playwright version 1.34.3, when the test fails, the POM file containing the method opens, and the error is displayed on the line of code within the method itself. The error is not displayed at the point of the method call in the test spec file.
<img width="1990" alt="SCR-20230604-dpgy" src="https://github.com/microsoft/playwright/assets/78950093/6da23694-bbe6-42ac-b4c7-ac86f0e67760">

This change in error reporting makes it more difficult to quickly identify the source of a test failure when using the POM approach. It would be preferable for the error to be highlighted at the point of the method call in the test spec file, as was the case in version 1.33.0.

**Comment by aslushnikov** [comment]
Hey @ch4r-ch4r, the new behavior is the intended one; this way you can see actual Playwright faulty step.
