### ISSUE TITLE
[REGRESSION]: Inconsistent Display of Execution Time in VSCode with Playwright Extension

### ISSUE THREAD

**Issue by ch4r-ch4r** [microsoft/playwright#23504]
### Context:
- GOOD Playwright Version: 1.33.0
- BAD Playwright Version: 1.34.3
- Operating System: Mac/Windows
- Extra: N/A

### **Describe the bug**

After upgrading to Playwright version 1.34.3, I noticed that the execution times for each line of code are not consistently displayed when running tests in VSCode with the Playwright extension. This was not the case in version 1.33, where execution times were shown for each line.

Version 1.33.0
![SCR-20230604-cvtp](https://github.com/microsoft/playwright/assets/78950093/3e57fd1b-d0b8-4950-beeb-150350193399)

Version 1.34.3
<img width="1813" alt="SCR-20230604-cuxq" src="https://github.com/microsoft/playwright/assets/78950093/9fe9fef6-4adf-4f11-a4a2-93366e602f50">

**Expected Behavior:**

Every line of code in the test should display its execution time in milliseconds, similar to the behavior in version 1.33.
The line being executed displays the `⏳Waiting...` legend.

**Actual Behavior:**

The execution time is not displayed for all lines of code in the test.
No `⏳Waiting...` legend.

----
### Code Snippet

You can use the default init playwright code to repro:

```typescript
import { expect, test } from "@playwright/test";

test("has title", async ({ page }) => {
    await page.goto("https://playwright.dev/");

    // Expect a title "to contain" a substring.
    await expect(page).toHaveTitle(/Playwright/);
});

test("get started link", async ({ page }) => {
    await page.goto("https://playwright.dev/");

    // Click the get started link.
    await page.getByRole("link", { name: "Get started" }).click();

    // Expects the URL to contain intro.
    await expect(page).toHaveURL(/.*intro/);
});

```

**Comment by mxschmitt** [comment]
I also experienced this as part of creating a new project and running the default tests in the tests/ folder.
