### ISSUE TITLE
[BUG] VS Code extension broken for component testing since some recent Playwright update

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#23505]
### System info
- Playwright Version: v1.34.3
- Operating System: macOS 13.4
- Browser: Chromium
- Other info: VS Code 1.78.2, extension version v1.0.11

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/segevfiner/playwright-ct-vscode-issue

**Steps**
- `pnpm i`
- Open `HelloWorld.pw.ts` in VS Code.

**Expected**

It works and I can run the tests via the VS Code extension.

**Actual**

The extension gives an error:
```json
[{
	"resource": "/Users/segevfiner/junk/playwright-ct-issue/src/components/__tests__/HelloWorld.pw.ts",
	"owner": "pw.diagnostics",
	"severity": 8,
	"message": "Unexpected token '<'",
	"source": "playwright",
	"startLineNumber": 2,
	"startColumn": 1,
	"endLineNumber": 3,
	"endColumn": 1
}]
```

The tests do work when run from the CLI, and it used to work in previous Playwright versions.

**Comment by mxschmitt** [comment]
I can reproduce.

`npx playwright test --config playwright-ct.config.ts --list` shows errors while `npx playwright test --config playwright-ct.config.ts` does not.

**Comment by mxschmitt** [comment]
I can verify that this is fixed on tip-of-tree. Currently tho blocked by https://github.com/microsoft/playwright/pull/23507 and then https://playwright.dev/docs/canary-releases should work for you.
