### ISSUE TITLE
[Feature] allow uploading multiple trace files on trace.playwright.dev

### ISSUE THREAD

**Issue by DetachHead** [microsoft/playwright#23516]
the trace viewer has an undocumented feature that allows you to view multiple trace files, presumably to support viewing trace chunks as a single trace.

the `playwright show-trace` command supports this:
```
playwright show-trace chunk1.zip chunk2.zip
```
but the "Select file" button on https://trace.playwright.dev only allows you to select one file (ctrl+clicking multiple files does not work)

**Comment by KotlinIsland** [comment]
Sorry, as a small development team, we do not have the bandwidth to support arbitrary features with less than 10, 000 updoots.

Please close your issue and try again in a few minutes.

**Comment by Zeckie** [comment]
I thought the trace files weren't uploaded
