### ISSUE TITLE
[Question] selecting radio in javascript file  calling from typescript

### ISSUE THREAD

**Issue by kdevineni** [microsoft/playwright#2351]
When I wrote the page.check code in javascript, didn't use typescript.

await page.check('input[name=duty]','option1');

This works fine when I run using "node jsfilename"

----------------

When I tried the same in type script, I get the following error
Type '"option1"' has no properties in common with type 'PageCheckOptions'.ts(2559)

Not able to create PageCheckOptions object in typescript. 
please advice on creating PageCheckOptions object

---------------------------
I wanted todo in typescript, but doing in javascript and calling from typescript.

await page.check('input[name=duty]','option1'); >> this always checks the first option, even  the second option value is given.

I worked around by using the focus followed by click commands like this.
        await page.focus('input[name=duty]');
        await page.click('text="option1"');
However this doesn't seems to be a solution for me,

Can I get the page.check option working in single statement.

**Comment by arjun27** [comment]
> please advice on creating PageCheckOptions object

The `page.check` method takes `selector` and `options` as arguments, and you can refer to the [API documentation](https://github.com/microsoft/playwright/blob/master/docs/api.md#pagecheckselector-options) for what options looks like. The `selector` refers to the actual element you'd like to select.

Do you have a selector to point to the specific options? You could also explore combining selectors – see [selector docs](https://github.com/microsoft/playwright/blob/master/docs/selectors.md). This could look like:

```js
await page.check('input[name=duty] >> text=option1');
```

If you can share the DOM structure of the radio button, we could explore other alternatives.

**Comment by kdevineni** [comment]
Tried that didn't work , it just keep waiting and timesout

Here is my radio button html code


> <div class="row">
			<div class="col">
				<label>
					<input id="duty1" name="duty" data-show="1" class="with-gap" type="radio" value="On Duty"/>
					<span>On Duty</span>
				</label>
			</div>
			<div class="col">
				<label>
					<input id="duty2" name="duty" data-hide="1" class="with-gap" type="radio" value="Off Duty"/>
					<span>Off Duty</span>
				</label>
			</div>
</div>

**Comment by arjun27** [comment]
Thanks! Yes, my example will not work for this case. You can use the value/id fields to disambiguate the options. Would this work for your needs? Try here: https://try.playwright.tech/?s=4p4pj

```js
await page.check('input[value="Off Duty"]');
```

**Comment by kdevineni** [comment]
That worked thanks.
There can be multiple radio buttons with just Yes/no or True/false options on the same page, how can we distinguish between them if we are using value attribute....I have the same situation now.

**Comment by arjun27** [comment]
Can you use selectors to find the relevant parts of the page? It is possible to use the `>>` combinator to specify the final elements within a subtree. For example, if you want to select the `Yes` value within `#section1`, you can use the following.

```
await page.check('#section1 >> input[value="Yes"]');
```

Some teams also prefer using `data-test-id` attributes to specify the precise elements directly. Let me know if these options work for you.

**Comment by kdevineni** [comment]
Selectors would be same for the both radio button options, only thing that can be distinguished is the id attribute.
If I need to go with the id attribute, have to evaluate the "Yes/No" option each time there is radio button and use right selector based on the id attribute.

selecting with name attribute would be ideal.

`<input id="duty1" name="duty" ....
<input id="duty2" name="duty" ....`

**Comment by arjun27** [comment]
The CSS selector supports concatenation of multiple attributes. Try here: https://try.playwright.tech/?s=8938y

```js
await page.check('input[name="duty"][value="Off Duty"]');
```

**Comment by kdevineni** [comment]
Thanks a lot that worked ...
