### ISSUE TITLE
[BUG] Viewport setting in playwright config is ignored

### ISSUE THREAD

**Issue by kumarchandresh** [microsoft/playwright#23529]
### System info
- Playwright Version: v1.34.3
- Operating System: Windows 10
- Browser: All

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[kumarchandresh/playwright-viewport-issue](https://github.com/kumarchandresh/playwright-viewport-issue)

or

**Config file**

```js
// playwright.config.tsimport { defineConfig, devices } from '@playwright/test';

export default defineConfig({
	testDir: './tests',
	reporter: 'list',
	use: {
		viewport: { width: 1920, height: 1080 },
	},
	expect: {
		timeout: 5000,
	},
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] },
		},
	],
});

```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

const fullHD = { width: 1920, height: 1080 };

test('viewport config', async ({ viewport }) => {
	expect(viewport).toEqual(fullHD);
});

test('page viewport', async ({ page }) => {
	expect(page.viewportSize()).toEqual(fullHD);
});

```

**Steps**
- Run the test

**Expected**

- Tests should pass

**Actual**

- Both tests fails

**Comment by pavelfeldman** [comment]
> use: { ...devices['Desktop Chrome'] },

This is where you override it.

**Comment by kumarchandresh** [comment]
Thanks! It works now. Docs may be improved so that no one else get confused on this.

![image](https://github.com/microsoft/playwright/assets/12244518/e31e6cb1-c9ba-438e-a8c9-0f71526afb7c)
