### ISSUE TITLE
[BUG] page.emulateMedia colorScheme has no effect in firefox without reload

### ISSUE THREAD

**Issue by Calvin-LL** [microsoft/playwright#2352]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Mac
- Node version: v14.2.0
- Browser: Firefox

**Code Snippet**

```javascript
const {chromium, webkit, firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch({ headless: false });
  const page = await browser.newPage();

  await page.goto("https://duckduckgo.com/");

  await page.emulateMedia({ colorScheme: "dark" });
  // page still appears light
  await page.reload();
  // page appears dark
})();
```

**Describe the bug**

For both webkit and chromium, `page.emulateMedia({ colorScheme: "dark" })` immediately turns page dark. Firefox doesn't change without `page.reload()`.

**Comment by dgozman** [comment]
This was fixed a while ago.
