### ISSUE TITLE
[BUG] `$attrs` doesn't include event handlers in pass through component in Playwright component testing in Vue 3

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#23526]
### System info
- Playwright Version: v1.34.3
- Operating System: macOS 13.4
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/segevfiner/playwright-ct-vue-on-issue

**Steps**
- Run `pnpm i`
- Run `pnpm test:unit`, it passes, there is an `onFoo` property in `$attrs`
- Run `pnpm test-ct`, it fails, there is no `onFoo` property in `$attrs`, and it doesn't format the `console.log` message as the browser does (Handles `%o` and so on), just prints the arguments verbatim.

**Expected**

For event handlers specified in component testing and propagated via `$attrs` to work.

**Actual**

They don't work. (But they do in vitest)

**Comment by sand4rt** [comment]
@aslushnikov I can reproduce the issue. Will dive into it deeper later on.
