### ISSUE TITLE
[BUG] - VSCode plugin doesn't see tests in folder called "integration"

### ISSUE THREAD

**Issue by reinierkaper-carewell** [microsoft/playwright#23520]
**Context:**
- Playwright Version: Latest (npx version)
- Operating System: Mac
- Node.js version: 18.16.0
- Visual Studio Code version: 1.78.2
- Playwright for VSCode extension version: 1.0.11
- Browser: N/A

**Code Snippet**

I have a couple of folders under `__tests__`, including `/e2e`, `/smoke`, `/integration` and `/.auth`. ll include `*.spec.ts` files.
Here's a snippet of my config:
```js
import { defineConfig, devices } from '@playwright/test'

const BASE_FOLDER = './__tests__'

export default defineConfig({
  testDir: BASE_FOLDER,
  outputDir: `${BASE_FOLDER}/test-results`,
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [['html', { outputFolder: `${BASE_FOLDER}/test-report` }]],
  use: {
    baseURL: 'https://www.[some-domain].com',
    trace: 'on-first-retry',
  },

  globalTeardown: `${BASE_FOLDER}/globalTeardown`,

  projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },

    {
      name: 'chromium',
      testMatch: /integration\/.*.spec.ts/,
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'chromium',
      testMatch: /e2e\/.*.spec.ts/,
      use: { ...devices['Desktop Chrome'], storageState: '__tests__/.auth/user.json' },
      dependencies: ['setup'],
    },

    {
      name: 'Smoke',
      testMatch: /.*smoke.spec.ts/,
      retries: 0,
    },
})

```

**Describe the bug**

All tests are seen by the plugin, except tests in the `integration` subfolder. Even `/.auth` is seen, but the `/integration` folder, for some reason is never picked up. I tried restarting VSCode as well, to no avail. Refreshing also doesn't work.

They **do** show up in playwright UI though!

**Comment by reinierkaper-carewell** [comment]
Interestingly, if I switch the matchers for `e2e` and `integration` around, it picks up `integration` but not `e2e` anymore. There must be some regex issue going on?

**Comment by aslushnikov** [comment]
@reinierkaper-carewell  would you mind creating a simple stripped-down repo that reproduces the issue? 

I tried the following minimal repro:

```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test'

const BASE_FOLDER = './__tests__'

export default defineConfig({
  testDir: BASE_FOLDER,
  outputDir: `${BASE_FOLDER}/test-results`,
  projects: [
    {
      name: 'chromium',
      testMatch: /integration\/.*.spec.ts/,
    },
    {
      name: 'chromium',
      testMatch: /e2e\/.*.spec.ts/,
    },
  ],
})
```

```ts
// __tests__/integration/a.spec.ts
import { test, expect } from "@playwright/test";

test('integration test', async () => {});
```

```ts
// __tests__/e2e/b.spec.ts
import { test, expect } from "@playwright/test";

test('e2e test', async () => {});
```

Running these yields the following:

```bash
aslushnikov:~/tmp$ npx playwright test

Running 2 tests using 2 workers

  ✓  1 [chromium] › e2e/b.spec.ts:3:5 › e2e test (11ms)
  ✓  2 [chromium] › integration/a.spec.ts:3:5 › integration test (11ms)

  2 passed (204ms)
```

So it does discover tests properly. Can you try this? Does it work for you?

**Comment by reinierkaper-carewell** [comment]
Thanks for the minimal repo, but the issue isn't that the tests don't run from the CLI (they do), it's that the VSCode plugin doesn't show the tests in the tree view.

**Comment by aslushnikov** [comment]
@reinierkaper-carewell oops sorry! I can repro this indeed with my repro.

**Comment by pavelfeldman** [comment]
I can repro it, two projects have the same name there. CLI tolerates it, but the VS Code extension fails to load the config with clashing project names.

**Comment by reinierkaper-carewell** [comment]
> I can repro it, two projects have the same name there. CLI tolerates it, but the VS Code extension fails to load the config with clashing project names.

I didn't even realize that! I will change the names for sure though, that seems reasonable at the very least. Thanks!
