### ISSUE TITLE
[Feature] expose isClickable(`selector`)

### ISSUE THREAD

**Issue by idoros** [microsoft/playwright#2353]
I would like to have the ability to test that parts of my page / components are **not accessible**. The specific use case that I'm testing is that a modal backdrop is actually preventing access to background elements.

The functionality already exist through all the mouse actions, but I prefer to try and avoid testing for negative (error in action), and instead specifically check access. 

It could even be better if such a feature could select specific access issues (default to all):
- out of screen / not reachable by scroll
- covered
- invisible
- not accepting pointer events
- inert

**Comment by dgozman** [comment]
With #3501, version 1.4 will provide the following api that waits for stable and visible. It does not yet check for pointer events, because that requires scroll and precise click point. I'll keep thinking about it.

```js
await handle.waitForElementState('stable');
```

**Comment by idoros** [comment]
What I ended up doing is wrapping the `click` method with `tryClick` that returns a boolean indicating if the click succeed, expecting false for my non-clickable element.

From what I understand, this is better because it will return success or throw an error without clicking when using a combination of `stable` and `enabled`.

However I need the opposite of `enabled` in order to keep my code clean of try/catch. Any chance of adding `disabled` to the api?

**Comment by dgozman** [comment]
Makes sense - I'll add `disabled` as well.

**Comment by idoros** [comment]
tried it now and `disabled` is not the definition I needed. It checks for disabled input and not "unclickable". placing a blocking element above the checked element doesn't make it `disabled`, Perhaps another status might work,  maybe `pointer-blocked`?

**Comment by dgozman** [comment]
The problem with "clickable" is that it's much more dynamic and depends on the specific location to click. It's harder to come up with the great API here.

**Comment by idoros** [comment]
When `Page.click` is called on an element that is covered it throws, so there is some code that checks if the targeted element is exposed

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
