### ISSUE TITLE
[BUG] WebServer stdout and stderr "pipe" does not stream output

### ISSUE THREAD

**Issue by andrewmclagan** [microsoft/playwright#23539]
[BUG] WebServer stdout and stderr "pipe" does not stream output as per the documentation which makes debugging impossible.

### System info
- Playwright Version: 1.34.3
- Operating System: osx
- Browser: All
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

https://github.com/andrewmclagan/playwright-std-out

```
pnpm test:e2e
```

You will notice output is only displayed _**after**_ the web-server's URL is reachable and is not streamed/piped to `stdout` as per the configuration setting. This makes it very difficult to debug when the web-server has a possible long startup, or there are errors. Forcing the developer to wait for the `webServer.timeout`

**Comment by aslushnikov** [comment]
@andrewmclagan Indeed, great repro! Thank you.

A simplified repro:

```js
// server.js
console.log('[stdout] before server is reachable');
console.error('[stderr] before server is reachable');

// Make the process hang.
setTimeout(() => {}, 100000);
```

```ts
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  webServer: {
    command: 'node ./server.js',
    port: 1234,
    stdout: 'pipe',
  },
});
```

```ts
// a.spec.ts
import { test } from "@playwright/test";
test("Error", () => {});
```

**Comment by andrewmclagan** [comment]
Much simpler.

**Comment by mxschmitt** [comment]
Investigation note: Issue is that we defer the stdout/stderr events until onBegin was fired: https://github.com/microsoft/playwright/blob/dd9a49690b2d93da2a068a53ea891896810caafb/packages/playwright-test/src/reporters/internalReporter.ts#L47-L61

**Comment by andrewmclagan** [comment]
Okay that makes sense.

**Side Note** Would it also be possible to prefix `stdout` and `stderr` with a property of the `config.webServer[]` otherwise when starting multiple processes the output is ambiguous. I guess this would require an optional `config.webServer[].name: string` perhaps defaulting to `config.webServer[].index: number`.

**Comment by adueck** [comment]
I'm still running into this issue. I can't get the `stdout` from my webserver.  Here's a [repo example](https://github.com/adueck/haskell-mailer/tree/8eff8ef0b3c9c6a0131083d10386c7ccb62350c6)
 Nothing comes out from the `stdout` from my webserver. The only `stdout` that shows up is when I run an `execSync` to call some command in the test.
