### ISSUE TITLE
[REGRESSION]: Incorrect wrapping steps

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright#23538]
**Context:**
- GOOD Playwright Version: 1.32.0
- BAD Playwright Version: >1.33.0 
- Operating System: Any
- Extra: None

**Code Snippet**

```typescript
   await test.step("Description", async () => {
            await this.page.route('**/api/articles?limit=10&offset=0', async route => {
                const response = await route.fetch();
                await route.fulfill({
                    status: 200,
                    contentType: 'application/json',
                    headers: response.headers(),
                    body: JSON.stringify(
                        articles
                    )
                });
            });
        });
```

**Describe the bug**

Incorrect wrapping in test steps. In version 1.32 I can wrap correctly test steps to add one step for the mock, but after 1.33 and 1.34 the wrapping is incorrect for the HTML report

Version 1.32

![image](https://github.com/microsoft/playwright/assets/7475390/09cd9937-7ec9-4b45-8ab9-68b3e697ffed)

Version >=1.33
![image](https://github.com/microsoft/playwright/assets/7475390/00c2f4c7-1934-45df-9097-a32e78e8cfa6)

Too last version is adding step:
tracing.stopChunk

Link with public repo:
https://github.com/apis3445/playwright-errors

Due to multiple failures with playwright you need to run the test https://github.com/apis3445/playwright-errors/blob/main/tests/mock.spec.ts

Github pages with the error:
https://apis3445.github.io/playwright-errors/#?testId=0ac535d5492e1392b78c-b8589b8c593de725f976

![image](https://github.com/microsoft/playwright/assets/7475390/40c83370-0a77-4c1b-9ce6-147b20999cef)

**Comment by aslushnikov** [comment]
Hey @apis3445, thank you for re-filing.

For the `tracing.stopChunk`, I don't see these using the latest playwright. Could you please try installing `@playwright/test@next`, and see if the `stopChunk` is still there?

For the `route.fulfill()` - that's expected; the application is hitting the URL you mocked with the `page.route()` waay after the test execution, so you see it as expected.

**Comment by apis3445** [comment]
In the previous version was wrapped, how I can add some custom step only to that part?

**Comment by aslushnikov** [comment]
@apis3445 What do you mean by "wrapped"? The HTML report looks good to my eye. Could you please highlight what exactly is wrong in the new version?

**Comment by apis3445** [comment]
In previous version the step is only: 
This step includes all code
`  const stepDescription = 'Modify the articles with fixed data';
        await test.step(stepDescription, async () => {
            await this.page.route('**/api/articles?limit=10&offset=0', async route => {
                const response = await route.fetch();
                await route.fulfill({
                    status: 200,
                    contentType: 'application/json',
                    headers: response.headers(),
                    body: JSON.stringify(
                        articles
                    )
                });
            });
        });`
inside the step: 'Modify the articles with fixed data'
In version 1.32 you only see this step.
In version >=1.33 you see an extra step:
route.fullfill that in theory is inside in the test.step.

If is a breaking change I don't want to see step: route.fullfill

**Comment by aslushnikov** [comment]
@apis3445 to the best of my knowledge, we were never able to attribute the `route.fulltill()` call to your outer `test.step()` call; the reason you don't see it in your previous test run is probably due to the fact that it was never triggered.

The behavior that you observe in 1.33+ is consistent with our expectations. If you think that there was some other behavior in some other version, I'd appreciate a tiny reproduction that demonstrates the differences between playwright versions.

**Comment by apis3445** [comment]
I shared the sample is the same repo. You only need to update package.json. I updated to 1.32 and this is the result
![image](https://github.com/microsoft/playwright/assets/7475390/22b88505-01d9-419b-b1de-c6540450fcc1)
This is the link of live html report
https://apis3445.github.io/playwright-errors/#?testId=0ac535d5492e1392b78c-b8589b8c593de725f976

**Comment by apis3445** [comment]
It can be a feature request? I want a user-friendly steps route.fulfill is not easy to understand
