### ISSUE TITLE
[Question] Custom/global actionability checks

### ISSUE THREAD

**Issue by jm-mfin** [microsoft/playwright#23533]
I'm testing a vendor's web application, so I don't have access to the code. This application shows a loading bar at various times, including between page loads, but sometimes even after selecting menu options or checking boxes.

I've found that performing actions while this loading bar is present can cause unexpected problems. I've been waiting for the loading bar to disappear after every action that triggers loading, but my test script is quickly filling up with waitForLoadingBar functions.

This is the code I use to wait:
```
const waitForLoadingBar = async (page, expect) => {
  await expect(page.locator('#loading-bar')).toHaveCount(0, {timeout: 30000});
};
```
Can I set this function to run globally after every action? Is it possible to add a custom actionability check, or modify the click() and check() functions to wait for this element to disappear?

**Comment by aslushnikov** [comment]
> Can I set this function to run globally after every action? 

@jm-mfin No, there's no such functionality.

> Is it possible to add a custom actionability check, or modify the click() and check() functions to wait for this element to disappear?

The common approach here would be creating a [POM](https://playwright.dev/docs/next/auth#testing-multiple-roles-with-pom-fixtures), for example `pageWithLoadingBar` class, that provides simple actions like `click` and `check` that also use your helper function.

Would this work?

**Comment by aslushnikov** [comment]
Closing this since the discussion has stalled. Feel free to file a new issue if you think we can still be helpful.
