### ISSUE TITLE
[BUG] VS Code extension loads incorrect config file and silently fails

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#23542]
### System info
- Playwright Version: 1.34.4
- Operating System: macOS 13.4
- Browser: N/A
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/OliverJAsh/playwright-vs-code-extension-list-files-issue

This is a brand new Playwright project created using `yarn create playwright`. The only changes on top of this are:

- [Use `dotenv`](https://github.com/OliverJAsh/playwright-vs-code-extension-list-files-issue/commit/d884ab90be92199401cf173c278d098cd1a26711)
- [Add `tsconfig.json`](https://github.com/OliverJAsh/playwright-vs-code-extension-list-files-issue/commit/43d5c5ee6c7c5749d4565e9af4e7bfe030d0d8ff)

**Steps**
1. Clone the project
1. ```console
   $ yarn
   $ tsc
   ```
1. Open VS Code

**Expected**

The tests load, or if the tests fail to load, an error message should appear.

**Actual**

The tests never load, nor is there an error message to indicate an error occurred.

<img width="444" alt="image" src="https://github.com/microsoft/playwright/assets/921609/d8286032-32d3-402a-90fa-06c381e62694">

**Notes**

This issue started when I upgraded from 1.33.0 to 1.34.4.

I spent some time trying to debug this. In developer tools we can see this error message: `e.projects is not iterable`.

![image](https://github.com/microsoft/playwright/assets/921609/b1a6c814-b3ee-44ef-acfb-e45d5a4ded45)

I modified the extension to log the value of `e`:

<img width="788" alt="image" src="https://github.com/microsoft/playwright/assets/921609/5522ac2f-c1dc-451a-9b00-f35cc562b8eb">

It appears that when the config file is loaded via `listFiles` ([code](https://github.com/microsoft/playwright-vscode/blob/be9ad1e93fff6b7bba9ab44d42c648b91b85608f/src/playwrightTest.ts#L97)), the `FOO` environment variable does not exist. This suggests that `dotenv` is not working.

To debug this further I added a console log inside `listFiles` to see the value of the `configFolder` argument we pass to `runNode`:

<img width="786" alt="image" src="https://github.com/microsoft/playwright/assets/921609/e35f8900-8751-4f63-b0bd-bba48f5a4d3d">

As you can see, the extension is trying to load `.cache/typescript/playwright.config.js` (generated by `tsc`) instead of `playwright.config.ts` in the project root.

This means that `dotenv` isn't able to find `.env` (which also lives in the project root).

A few thoughts:

- Could we improve error handling inside the extension? If there is an error, this should be displayed to the user (as opposed to the infinite loading state that's currently shown).
- How can I instruct the extension to ignore `.cache/typescript/playwright.config.js`? We only want it to use `playwright.config.ts` in the project root.

**Comment by aslushnikov** [comment]
@OliverJAsh first and foremost, there's no need to compile `playwright.config.ts`. I understand this is a synthetic repro; any reason why you do this in a real-world scenario?

**Comment by OliverJAsh** [comment]
We have a TS project for all of our test files and the test config so we can run `tsc` during CI to check for type errors.

We could add `noEmit` to the TS config. That would solve this problem. However, I think my point about error handling above still applies.

**Comment by aslushnikov** [comment]
@OliverJAsh fair. So to summarize: 

> Could we improve error handling inside the extension? If there is an error, this should be displayed to the user (as opposed to the infinite loading state that's currently shown).

I can repro this and this is a bug. VS Code extension hangs with 2 playwright configs, when one of them is broken.
Repro:

```ts
// playwright.config.ts
export default {}
```

```ts
// playwright.config.JS
throw new Error('oh no');
```

> How can I instruct the extension to ignore .cache/typescript/playwright.config.js? We only want it to use playwright.config.ts in the project root.

For this, I'd recommend using `noEmit` for TS config.
