### ISSUE TITLE
[Feature] Please log when Playwright proactively closes browser connections

### ISSUE THREAD

**Issue by vemv** [microsoft/playwright#23566]
I'm fairly certain that under certain circumstances, Playwright can proactively close the websocket that, for instance, may back a `connectOverCDP` session.

I know this because I have a CDP proxy, and see in that Playwright is sending me a websocket message with opCode 8 (`%x8 denotes a connection close`, https://datatracker.ietf.org/doc/html/rfc6455#section-5.2)

I also believe to have found the specific culprit code:

https://github.com/microsoft/playwright/blob/7d2201561f743da83899ffda366f803fc1020b47/packages/playwright-core/src/server/transport.ts#L126-L135

Allow me to say, this code isn't exactly friendly, because it doesn't perform any logging as for:

* the fact that the websocket was proactively terminated by Playwright
* the problematic non-JSON-parseable string that triggered the decision.

I believe that this websocket closing can later cascade into failures like:

```
=========================== logs ===========================
<ws preparing> retrieving websocket url from http://localhost:3001/api/proxy
<ws connecting> ws://localhost:3001/api/proxy/devtools/browser/e25a6248-6375-4337-8989-032d6b171c80
<ws connected> ws://localhost:3001/api/proxy/devtools/browser/e25a6248-6375-4337-8989-032d6b171c80
<ws disconnected> ws://localhost:3001/api/proxy/devtools/browser/e25a6248-6375-4337-8989-032d6b171c80 code=1000 reason=
============================================================
  name='Error
  stack='Error: Browser closed.
```

That was very hard to debug, because it gives the impression that it's the browser (or proxy) that is closing, while the reality was the opposite.

Thanks - V

**Comment by aslushnikov** [comment]
Hey @vemv,

First of all, I'm sorry you spent a lot of time debugging this. 

Next, who and why is sending a broken JSON over the transport? Could you clarify your usecase?

**Comment by aslushnikov** [comment]
@vemv this is outside of the scope of the project; however, feel free to send a PR.
