### ISSUE TITLE
[Question] How to fail test run after some test retry (in allowed attempt range, test marked as flaky)?

### ISSUE THREAD

**Issue by pbarhyl** [microsoft/playwright#23567]
I wish combine: allowing retries and still having ability to fail tests run if any retry happened (even in allowed attempt range).
Having this setting: `retries: process.env.CI ? 3 : 0,`
Scenario: When running Playwright test on GH Actions I wish to `fail` the job when some of test is retried even once (so I keep retry, and flaky test logging and know that situation occurred).  
Is any simple solution for this scenario?

**Comment by aslushnikov** [comment]
@pbarhyl why's the `retries: process.env.CI ? 3 : 0` setting not sufficient?

**Comment by Exoow** [comment]
If you want to fail the pipeline when a test fails, AND you want tracing for the failed tests, set your test configuration to:
`trace: 'retain-on-failure'`
Then you can disable the retries and you have all the info needed.

**Comment by pbarhyl** [comment]
@aslushnikov with setting `retries: process.env.CI ? 3 : 0`, after **one retry** test pass and my Actions pipeline **pass**. 
I need to **fail pipeline** when flaky test appear (but keep ability to retry).

**Comment by aslushnikov** [comment]
> I need to fail pipeline when flaky test appear

@pbarhyl I see now. There's no such option in Playwright, and unless it's widely requested by the community, it's unlikely to appear any time soon. 

I'd recommend to use a JSON reporter, and write a small script that analyses the JSON report to figure out if there's a flaky test. This snippet can then fail pipeline if it finds a flaky run.

Would this work for you?

**Comment by pbarhyl** [comment]
Parsing JSON report was my idea at first. Thanks, will go this way.

Can we leave this issue as feature request?

**Comment by aslushnikov** [comment]
@pbarhyl so far we consider this usecase to be fully addressable in the user-land; we can re-open if this will be re-filed repeatedly.

Thanks for filing!
