### ISSUE TITLE
[BUG] waitForSelector > doesn't find visible text

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2356]
**Context:**
- Playwright Version: 0.17.0+ (also 1.0.2)
- Operating System: macOS
- Node version: 14
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

```javascript
const playwright = require("playwright-chromium");

 (async () => {
    const browser = await playwright.chromium.launch({
      headless: false
    })
    const page = await browser.newPage()
    await page.goto("https://github.com");
    await page.type('input[name="q"]', "Playwright");
    await page.press('input[name="q"]', "Enter");
    await page.click(".repo-list-item:nth-child(1) a");

    await page.waitForSelector("text=Playwright", {
      timeout: 2 * 1000,
      state: "visible"
    })
    await browser.close()
  })()
```

**Describe the bug**

Since the default state was changed to `visible` for `waitForSelector` the text selector does not find the needed text on the page anymore in my mind.

See the attached example, which does not work. After changing the state of the `waitForSelector` call to `attached` it does find the text.

Is this expected? Since in the page (https://github.com/microsoft/playwright) there is quite a lot of text with the text `Playwright`.

I have discovered this issue here after bumping Playwright: https://github.com/playwright-community/playwright-jest-examples/pull/3

**Comment by dgozman** [comment]
Thank you for the issue, Max.

I tried this locally, and `text=Playwright` resolves to the `<title>` element. Since title never becomes "visible" in our terms, `waitForSelector` never resolves. I see where the confusion comes from - we don't provide enough information when `waitForSelector` fails.

We'll work on improving the error. If you'd see in the error message that `text=Playwright` has resolved to the `<title>` and it never became visible, would you have any questions about `waitForSelector` behavior?

Does the above address your concerns?

**Comment by mxschmitt** [comment]
So the issue is that the element has not changed the CSS visibility from something to visible?

Maybe then we should add something like `page.waitForVisibleElement("#foo") which will just check if there is a visible element and then resolves or otherwise it waits.

Probably the error would be definitely better but still a bit confusing since we it does not resolve if the element is already visible.

**Comment by dgozman** [comment]
I have a proposal in #2370 for something along these lines. Could you please check whether that would work for you? Any comments are welcome!

**Comment by mxschmitt** [comment]
@dgozman I can confirm that #2413 has fixed the issue.
