### ISSUE TITLE
following test working fine in debugging mode. but while running  test stucks

### ISSUE THREAD

**Issue by Serah1234** [microsoft/playwright#23565]
let count1=0,count2=0;

    for (let i=1; i<= 3; i++)
    
    {

        page.waitForTimeout(5000);
        await page.locator("xpath=/html/body/div[6]/div[1]/div/div/section/div/div[2]/div[3]/div[2]/div[2]/div/div/div/table/thead/tr[4]/td["+i+"]/span").click();
         page.waitForTimeout(5000);
        count1=await page.locator("xpath=/html/body/div[1]/div/div/div/div/div[4]/div[2]/div[5]/div/div/div[4]/div/button").count();

          if(count1==1)
    {
        page.waitForTimeout(5000);
         await page.locator("xpath=/html/body/div[1]/div/div/div/div/div[4]/div[4]/div/button[3]").click();
         await page.locator("xpath=/html/body/div[1]/div/div/div/div[2]/button[1]").click();
       //  continue;
   
    }
 else
            {
                page.waitForTimeout(5000);
    count2=await page.locator("xpath=/html/body/div[1]/div/div/div/div[1]/div/div/div/p").count();
    if(count2>=1)
    {
        await page.locator("xpath=/html/body/div[1]/div/div/div/div[2]/button").click();
        //continue;
    }
    
}
}

**Comment by aslushnikov** [comment]
@Serah1234 could you please re-file, following the issue template, and providing a repro that we can run locally to reproduce the issue?
