### ISSUE TITLE
[Feature]playwright IDE(playwright studio)

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#23570]
If we can merge all the tools into one ,it would be great, we can name it playwright IDE(playwright studio).
playwright IDE will be ui mode; will be web mode, the same as the trace view in v1.35.
playwright IDE will include trace view, recorder ,locator inspector, ui mode.
through playwright IDE ,we can author test script(by recorder),dry run or schedule run the test suite ;
we can debug the test script, we can see running the test case through live mode ;
after finishing running, we can view the report and the trace .

**Comment by aslushnikov** [comment]
@chenshuichao thank you for sharing your thoughts!

Overall, the Playwright VSCode extension is pretty close to what you describe. Please give VSCode extension a try!
