### ISSUE TITLE
[BUG] Page.goto does not resolve in WebKit / load event does not fire

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#23574]
```ts
import { webkit } from 'playwright';

(async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  await page.goto('https://reachmd.com/');
  await browser.close();
})();
```
Expected: works
Actual: page.goto hangs

Changing waitFor from load to commit then it works. So the load event is not fired in some frame.

Extracted from https://github.com/microsoft/playwright-python/issues/1950.

**Comment by mxschmitt** [comment]
Turns out the site is now throwing a load event:

```
window.addEventListener("load", (event) => {
  console.log("page is fully loaded");
});
```

also not in Safari. This is then no bug on our side.

**Comment by RomanLeca** [comment]
Thank you, Max!

**Comment by RomanLeca** [comment]
@kblok , I have not created the bug yet. I was trying to rule out with the team why the load event fails for webkit, but I haven't received any feedback yet.
