### ISSUE TITLE
[REGRESSION]: 1.34 trace does not show console/network output

### ISSUE THREAD

**Issue by rssfrncs** [microsoft/playwright#23591]
**Context:**
- GOOD Playwright Version: 1.33
- BAD Playwright Version: 1.34
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

None of our code samples work from a basic load a web page and log to console.

**Describe the bug**

Add any other details about the problem here.

**Comment by aslushnikov** [comment]
@rssfrncs I just tried and everything works for me. Please share a repro!

**Comment by aslushnikov** [comment]
I'll close this; please feel free to re-file with a repro.
