### ISSUE TITLE
Google catch the automation as robot. My App using Gmail id authentication via microsoftonline. 

### ISSUE THREAD

**Issue by Kumaravel09** [microsoft/playwright#23601]
Playwright Version: [1.33.0]
Operating System: [Windows]
Python version: [3.11]
pip: [23.1.2]
PY Charm editor

Problem Description:
My application uses the gmail id authentication vis microsoftonline. If I try to login with my gmail credentials. I'm got caught on google's robot detection. What should I do to escape from that? I used User agent, stealth plugin. But still I'm getting the same issue. PFA for more details.

![image](https://github.com/microsoft/playwright-python/assets/53257563/72770977-52f6-4dcb-ac39-ed0650c63e68)

![image](https://github.com/microsoft/playwright-python/assets/53257563/fb169321-95ea-4296-b2f1-31b8efb570a2)

**Comment by aslushnikov** [comment]
Bot evasion techniques fall outside of the scope of Playwright project.
