### ISSUE TITLE
[Question]: Playwright Operation Chromium78 Version Application

### ISSUE THREAD

**Issue by TtBJSH** [microsoft/playwright#23615]
### Your question

"Hello, which version of Playwright can be used for automation with software built on Electron using Chromium version 78.0.3904.130? I have tried using newer versions but cannot perform any actions. Even the lowest version supported by Python 3.8, which is 1.9.0, cannot start the application."

**Comment by aslushnikov** [comment]
@TtBJSH unfortunately there's no Playwright version that works with Chromium 78.

**Comment by TtBJSH** [comment]
Thank you for your reply

**Comment by TtBJSH** [comment]
> @TtBJSH不幸的是，没有适用于 Chromium 78 的 Playwright 版本。

Thank you for your reply
