### ISSUE TITLE
[BUG] Error: Unknown scheme for Event: Page.console after updating Playwright version

### ISSUE THREAD

**Issue by zuzanna-maria** [microsoft/playwright#23616]
I'm trying to upgrade my Playwright version from v1.33 to v1.35, but this causes tests to crash and error out.

### System info
- Playwright Version: Upgrade attempt -- v1.33 to v1.35
- Operating System: macOS 12.6.3
- Browser: N/A

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: 
    [{
      name: 'playwright-firefox@latest:OSX Mojave',
      use: {
        connectOptions: { wsEndpoint: getCdpEndpoint('playwright-firefox@latest:OSX Mojave') }
      },
    }],
});
```

**Steps**
- Upgrade Playwright using `npm install @playwright/test@latest`
- Upgrade Playwright browsers using `npx playwright install`
- Check Playwright version to see if upgrade successful
- Run tests using `npx playwright test --headed --retries=1`

**Expected**

Upgrade Playwright version from 1.33 to 1.35 successfully and be able to run tests as previously. 

**Actual**

The new Playwright version seems to install correctly, as do browsers, as indicated by installation console logs and verifying the new installation via `npx @playwright/test --version`. However, When I try to run the test after installation, I get an error which never appeared previously:

`[playwright-firefox@latest:OSX Mojave] › genericfile.spec.js:28:3 › anon - slide - store - delete
locator.waitFor: Error: Unknown scheme for Event: Page.console
    at /Users/zuzanna/Desktop/playwright-tests/e2e-tests/genericfile.spec.js:35:59
[playwright-firefox@latest:OSX Mojave] › genericfile.spec.js:98:3 › anon - slide - change title
locator.click: Error: Unknown scheme for Event: Page.console
    at /Users/zuzanna/Desktop/playwright-tests/e2e-tests/genericfile.spec.js:104:59`

The error messages point to waitFor() and click() commands which were working fine up until the update.

**Comment by aslushnikov** [comment]
@zuzanna-maria any chance you can also show us a snippet of code that triggers this issue?

**Comment by aslushnikov** [comment]
@zuzanna-maria so you're connecting to an endpoint that uses old Playwright version; please either upgrade your end point or downgrade your playwright to the endpoint version.

As a general rule, Playwright versions on the both sides should be the same.

**Comment by zuzanna-maria** [comment]
Thanks for your reply!

I am using Playwright integrated with Browserstack so yes it's actually related to the BS endpoint. However, I have tried to update my endpoint and the version upgrade still causes an issue. This is my browserstack.config.js:

```
const caps = {
  browser: 'chrome',
  os: 'osx',
  os_version: 'catalina',
  name: 'cp-playwright-test',
  build: 'cp-playwright-build9',
  'browserstack.username': process.env.BROWSERSTACK_USERNAME || 'YOUR_USERNAME_HERE',
  'browserstack.accessKey': process.env.BROWSERSTACK_ACCESS_KEY || 'YOUR_KEY_HERE',
  'browserstack.local': process.env.BROWSERSTACK_LOCAL || true, 
  'browserstack.playwrightVersion': '1.35.0',
  'client.playwrightVersion': '1.35.0',
};
```

Setting the BS and client Playwright versions to '1.33.0' when that is the version I have installed locally runs fine. However, when I install 1.35 and set both variables accordingly, the issue persists. Is there another way to update the BS endpoint for Playwright?

**Comment by aslushnikov** [comment]
> Is there another way to update the BS endpoint for Playwright?

@zuzanna-maria I'd recommend asking these kind of questions on the Browserstack support channels.
