### ISSUE TITLE
[Feature] Run tests in beforeEach after hitting record from cursor

### ISSUE THREAD

**Issue by cdcasey** [microsoft/playwright#23625]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Let's say I have a `test.beforeEach` block and two `test` blocks. Now I want to add a third `test` block. As far as I understand, I have to somehow open up the browser and get to the point in my app that I want to test before clicking inside my new test block and hitting "record from cursor". Instead I would like to be able to
1) open VS code
2) create a new `test` block
3) hit "record from cursor", and have playwright open up a browser and run at least through the portion that's in the `test.beforeEach` block. That way I can just focus on recording the part of the app that I want to test

I think everyone would benefit from this :)

**Comment by aslushnikov** [comment]
@cdcasey the way I do it is:

1. open VS code
2. create a new `test` block
3. hit the green ▶️ button next to the test; this will run it's before hooks
4. hit the `record from cursor` button while positioned inside the test block.

Would this work for you?

**Comment by cdcasey** [comment]
@aslushnikov that does, in fact, work. The idea of "Record at cursor" working the way I imagine it just feels more intuitive, but I think you've given me a solution I can get used to.

Thanks for the response and suggestion.

**Comment by kacan98** [comment]
> @aslushnikov that does, in fact, work. The idea of "Record at cursor" working the way I imagine it just feels more intuitive, but I think you've given me a solution I can get used to.
> 
> Thanks for the response and suggestion.

Took me a while to figure this out but you have to have the "✅Show browser" ticked before this works :)
![image](https://github.com/user-attachments/assets/196f3862-bdb4-43b2-b400-c7ca59e41837)
