### ISSUE TITLE
[BUG] (Node.js) "@playwright/test" runner scripts conflict with "playwright" (without @ symbol) causing problems

### ISSUE THREAD

**Issue by yilmazdurmaz** [microsoft/playwright#23624]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [Windows 10, possibly All]
- Browser: [Edge, possibly All]
- Other info: node v20.2.0, npm 9.6.6

### Source code
No source is needed. It is clear after using "npm install"

- [x ] I provided exact source code that allows reproducing the issue locally.

**Steps**

I am new to both versions and have no idea how they differ (except the former won't need me to install any browser, latter download all major ones upon installation)

I stumbled upon the issue because I was trying to convert some python code to javascript and it imports "playwright", now "@playwright/test". 

But using "npm init playwright" initializes with a base test suite using "@playwright/test", not "playwright".

With a naive approach, I did "npm install playwright" to continue my conversion. But it seems these two packages, however both the latest, are not playing along fine about which one will use the name.

Both packages add "playwright-core" scripts into the binary folder, and both insist on using the same "playwright" script name for themselves; one points to `$basedir/../@playwright/test/cli.js` and the other points to `$basedir/../playwright/cli.js"`

The main issue here also has many other occurrences associated with this message: `Please install @playwright/test package before running`. This happens because installing "playwright" overrides the scripts for "@playwright/test".

They both work fine if they are used only as imports since both packages have their own unique directories. the problem arises when one tries to use scripts from the command line as `npx playwright ...`

**Expected**

Both packages are at "1.35.00" version. In this case, I would expect "@playwright/test" to use another script name, or both packages to use a unified script to suit them both.

**Actual**

Installation order determines which one will use the "playwright" name for the scripts to run from terminal.
Also causes this problem: `Please install @playwright/test package before running`

**Comment by aslushnikov** [comment]
@yilmazdurmaz if you're into web testing, then `@playwright/test` is the way to go. You can install it either with `npm i @playwright/test`, or with `npm init playwright`. 

The `playwright` package is the web-automation library; the `@playwright/test` package includes all of the `playwright` and adds a test runner with smart assertions. `playwright` cannot be installed together with `@playwright/test`. 

In general, just always use `@playwright/test` instead of `playwright`.

I hope this helps!

**Comment by yilmazdurmaz** [comment]
> @yilmazdurmaz if you're into web testing, then `@playwright/test` is the way to go. You can install it either with `npm i @playwright/test`, or with `npm init playwright`.
> 
> The `playwright` package is the web-automation library; the `@playwright/test` package includes all of the `playwright` and adds a test runner with smart assertions. `playwright` cannot be installed together with `@playwright/test`.
> 
> In general, just always use `@playwright/test` instead of `playwright`.
> 
> I hope this helps!

Hi @aslushnikov 

this problem repeats itself from time to time: `Please install @playwright/test package before running`, that is because of the lack of this info you shared. (besides both are developed parallel)

Can you please include this explanation at the top of npm pages of these packages? (those README files really needs a bit more info)
https://www.npmjs.com/package/playwright
https://www.npmjs.com/package/@playwright/test

Also having it as a warning in the docs would be nice.
https://playwright.dev/docs/intro

**Comment by yilmazdurmaz** [comment]
````js
const playwright = require('@playwright/test');
````

Also this would be good to have if a dev do not use init method.

**Comment by thewilkybarkid** [comment]
@aslushnikov I have a project that uses `@playwright/test` and `@web/test-runner-playwright`. The latter depends on `playwright`, so both are being installed. This leads to problems whenever there's a new Playwright version as Dependabot updates one but not the other, so I have to manually update the local version of `playwright` to remove the multiple versions of `playwright-core` that are installed. (I also have to update the Docker image version in 2 places, but that's a different issue. 😅)

I've opened https://github.com/modernweb-dev/web/pull/2307 to reduce the dependency there to just `playwright-core`, but this library isn't documented. (The separation between `@playwright/test` and `playwright` isn't particularly documented either.)

It works, but when just using `@web/test-runner-playwright` there's only a `playwright-core` binary installed (not a `playwright` one). This is different to the error messages:

```
╔═════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright Test or Playwright was just installed or updated. ║
║ Please run the following command to download new browsers:              ║
║                                                                         ║
║     npx playwright install                                              ║
║                                                                         ║
║ <3 Playwright Team                                                      ║
╚═════════════════════════════════════════════════════════════════════════╝
```

Running the command leads to:

```
npx playwright install
Need to install the following packages:
  playwright@1.36.0
Ok to proceed? (y) 
```

which may install a different version of `playwright`.

I'm now seen your comment that

> `playwright` cannot be installed together with `@playwright/test`.

While I can continue to resolve the version problem every time there's an update, it was confusing to unravel (and is a chore).

I'm unsure what the solution should be if it's unsupported to have both installed.

Should anything other than `@playwright/test` or `playwright` use `playwright-core`? As it's undocumented I'm guessing not.

Should `@playwright/test` and `playwright` have a loser constraint on `playwright-core`? And have it as a peer dependency too?

Are there other options?

**Comment by aslushnikov** [comment]
@thewilkybarkid so in general, we advise everybody to install `@playwright/test` instead of Playwright. Those who currently install Playwright, should migrate to `@playwright/test` like this:

```ts
import { chromium, firefox, webkit } from '@playwright/test';

// ...
```

According the this, the `@web/test-runner-playwright` should switch from using Playwright to `@playwright/test`.

As a side note, I'd recommend filing new issues rather than commenting on old issues in this repository; we have a process to look at all freshly filed issues, and we don't have any process to check out comments on old issues. 

Thanks!
