### ISSUE TITLE
[Question] Do Generic assertions return Promises? 

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#23623]
So I am a bit confused on Playwright assertions, specifically Generic Assertions: https://playwright.dev/docs/api/class-genericassertions

In general Playwright states it's Locator and Page assertions do an auto-retry of 5 seconds by default: https://playwright.dev/docs/api/class-locatorassertions these also have an `await` in front of them so I assume they return some sort of promise? (The docs do not state a return type like other areas in the Playwright documentation which state a return type of `Promise<null|void>`) However I assume they do in fact return a promise as they are async matcher.

However the Generic assertions page has the first example as:
```
import { test, expect } from '@playwright/test';

test('assert a value', async ({ page }) => {
  const value = 1;
  await expect(value).toBe(2);
});
```
However the rest of the generic assertions do NOT contain `await` so I assume there is no auto-retrying. So this leads me to ask a couple of questions.

1. Do the async matchers for Locator/Page (such as `expect(page).toHaveTitle`) return Promises? or something else. Does this Promise have a type if so?
2. Do Generic assertions return a Promise? or should we never need `await` despite the first example using `await`?

Thanks!

**Comment by aslushnikov** [comment]
> Do the async matchers for Locator/Page (such as expect(page).toHaveTitle) return Promises? or something else. Does this Promise have a type if so?

@msmith1114 They do; that's the `Promise<void>`. You should be able to see the type in VSCode.

> Do Generic assertions return a Promise? or should we never need await despite the first example using await?

Generic assertions do not return a promise, so `await`'ing them is not necessary, but would be a noop if you add an `await` in front.

**Comment by aslushnikov** [comment]
Seems like this is answered, so closing.

Feel free to file new issues if you think we can be helpful!
