### ISSUE TITLE
[Feature]support more actions when codegening

### ISSUE THREAD

**Issue by chenshuichao** [microsoft/playwright#23634]
Now codegening tool can record these actions:(ClickAction | CheckAction | ClosesPageAction | OpenPageAction | UncheckAction | FillAction | NavigateAction | PressAction | SelectAction | SetInputFilesAction);
as we know these are only some actions in many interactions, if we want to author the test script more accuracy  ,we must 
support more actions when codegening,for example:
mousedownAction,mouseupAction,mousemoveAction,draganddropAction,slideAction

**Comment by chenshuichao** [comment]
the ref script is here:
https://github.com/rrweb-io/rrweb/blob/master/packages/rrweb/src/record/observer.ts

**Comment by aslushnikov** [comment]
@chenshuichao thanks for filing!

This has been requested before; linking to the related bugs:
- The drag-and-drop bug is here: https://github.com/microsoft/playwright/issues/19892
- The moseup/down/move actions recording is filed here: https://github.com/microsoft/playwright/issues/7472

Please upvote these bugs to bump their priority. Closing this in favor of separate bugs!
