### ISSUE TITLE
[Feature] Pass timeout in the BrowserContextOptions for newContext

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#2363]
It would ease up the usage especially in `jest-playwright` or other Playwright wrappers if we could pass the timeout for Playwright via the options. Maybe two timeouts, one for navigation and the other general one.
The original issue which this would ease up to solve is that the Jest timeout needs to be greater than the Playwright timeout. Otherwise Jest just stops the execution and no good error reporting will be generated out of that (which function call / Promise was not resolved).

As a workaround `context.setDefaultTimeout()` or `context.setDefaultNavigationTimeout` can be used.

**Comment by aslushnikov** [comment]
@mxschmitt looks like workaround is pretty decent and not painful. Let's keep it like this for now - we can always add these if there's an urge.
