### ISSUE TITLE
[BUG] Webkit never fires a network event for navigator.sendBeacon in pagehide

### ISSUE THREAD

**Issue by Smrtnyk** [microsoft/playwright#23635]
### System info
- Playwright Version: [v1.35]
- Operating System: [Windows 11, Ubuntu 22]
- Browser: [WebKit]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
import {
    expect,
    test
} from "@playwright/test";

test.describe("network events", () => {
    test("fires network events", async ({ page }) => {
        const caughtEvents = [];
        await page.route("**/*", (route, req) => {
            if (req.url().includes("beacon")) {
                return route.fulfill({
                    status: 200
                });
            }
            if (req.isNavigationRequest() && req.resourceType() === "document") {
                return route.fulfill({
                    body: `
                       <!DOCTYPE html>
                        <html>
                            <head>
                                <title>Hi</title>
                                <script>
                                    window.addEventListener("pagehide", () => {
                                        window.navigator.sendBeacon("/beacon", "");
                                    });
                                </script>
                            </head>
                            <body>
                            </body>
                        </html>
                    `,
                    contentType: "text/html"
                });
            }
            route.continue();
        });

        page.on("requestfinished", (request) => {
            if (request.url().includes("beacon")) {
                caughtEvents.push("requestfinished");
            }
        });

        page.on("response", (response) => {
            if (response.url().includes("beacon")) {
                caughtEvents.push("response");
            }
        });

        page.on("requestfailed", (request) => {
            if (request.url().includes("beacon")) {
                caughtEvents.push("requestfailed");
            }
        });

        page.on("request", (request) => {
            if (request.url().includes("beacon")) {
                caughtEvents.push("request");
            }
        });

        await page.goto("http://test.local/page.html");
        expect(await page.title()).toBe("Hi");

        await page.evaluate(() => {
            window.location.href = "http://www.google.com";
        });

        await page.waitForTimeout(1000);

        expect(caughtEvents).toStrictEqual(["request", "response", "requestfinished"]);
    });
});

```

**Steps**
- Run the test

**Expected**
Webkit should fire at least one network event, looking at "request" at least

**Actual**

Firefox fully passes the test, chromium only fires "request" event, but webkit fires no events.
Array at the end of the test is always empty.
I would expect that at least "request" event is fired like on chromium.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by cthae** [comment]
This seems to be happening in other browsers too, but still happens in webkit.

**Comment by williazz** [comment]
Hey this seems to be happening to us as well, linked above. Would be great if we could reopen the issue and have proper investigation of these limitations, if any.
