### ISSUE TITLE
[BUG] Firefox launchPersistentContext: Protocol error failed to call method 'Browser.enable' with parameters

### ISSUE THREAD

**Issue by funnydevdotvn** [microsoft/playwright#23641]
### System info
- Playwright Version: [v1.33.0 -> v1.35.0]
- Operating System: [Windows 10 x64 H2]
- Browser: [Firefox v112 - v113]
- Other info: playwright.firefox.launchPersistentContext with special executable path.

### Source code

- node: v18.12.1
- npm: 8.19.2

- [x] I provided exact source code that allows reproducing the issue locally.

```js
const playwright = require('playwright');

let profile_path = '...';
let option = {
    headless: false,
    timeout: 0,
    executablePath: '...', // Sure this is right path and was the official binary from Playwright installation server
    // firefoxUserPrefs: {} // Tried to pass this key and value to the option to fix but still not pass through
}
let browser = await playwright.firefox.launchPersistentContext(option);
```
**Expected**

[Describe expected behavior]

The browser show up and shut down right then with this error:
```
launchPersistentContext: Protocol error (Browser.enable): ERROR: failed to call method 'Browser.enable' with parameters {
  "attachToDefaultContext": true,
  "userPrefs": []
}
Found property "<root>.userPrefs" - [] which is not described in this scheme _dispatch@chrome://juggler/content/protocol/Dispatcher.js:67:15
receiveMessage@chrome://juggler/content/components/Juggler.js:118:20
```
[Describe actual behavior]

I have just temporary fixed this error by editing file ...node_modules/playwright-core/lib/server/firefox/ffBrowser.js from line 44 like this:

- The official:
- ```
const promises = [connection.send('Browser.enable', {
      attachToDefaultContext: !!options.persistent,
      userPrefs: Object.entries(firefoxUserPrefs).map(([name, value]) => ({
        name,
        value
      }))
    }), browser._initVersion()];
- The changed (remove userPrefs key and value):
const promises = [connection.send('Browser.enable', {
      attachToDefaultContext: !!options.persistent
    }), browser._initVersion()];
```

I realize that the problem may stem from:

- Playwright v1.34 and up can't not be used with Firefox bellow than v133.
- Playwright v1.33 and down can't not be used with Firefox v133 and up.

**Comment by aslushnikov** [comment]
@funnydevdotvn you're using an old firefox binary from Playwright 1.33 with Playwright 1.35.

Please make sure to use latest-and-greatest Firefox binary that comes with Playwright 1.35 instead. 

Hope this helps.
