### ISSUE TITLE
[BUG] traces zip files are not saved in the specified tracesDir

### ISSUE THREAD

**Issue by talkohavy** [microsoft/playwright#23645]
### System info
- Playwright Version: [v1.34.3]
- Operating System: macOS 13.2
- Browser: Chromium

### Source code

**Config file**

```
import { defineConfig, devices } from '@playwright/test';

const config = defineConfig({
  testDir: './src/__tests__',
  outputDir: './__artifacts__',
  fullyParallel: true,
  retries: 1,
  testMatch: '*.test.js',
  reporter: [['html', { outputFolder: './__report__', open: 'on-failure' }]],
  use: {
    headless: false,
    baseURL: 'http://localhost:3000',
    testIdAttribute: 'data-test-id',
    trace: 'on-first-retry',
    launchOptions: {
      tracesDir: '__traces__',
    },
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        launchOptions: {
          tracesDir: '__traces__',
        },
      },
    },
  ],
});

export default config;
```

**Test file (self-contained)**

```js
// @ts-check
import { expect, test } from '@playwright/test';

test('this test will fail', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Play1wright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*int1ro/);
});
```

**Steps**
- Simply run the test, it should fail. A retry would kick in. Which is good, because it is in compliance with `trace: 'on-first-retry',`.

**Expected**
The trace.zip file should have been stored within the _**tracesDir**_.

**Actual**

The trace.zip file is stored within the _**outputDir**_ instead.

**Comment by aslushnikov** [comment]
@talkohavy traces are stored in the `outputDir` by the test runner by default; there's no way to configure it to be a separate directory.

Why would you want to do that?

**Comment by talkohavy** [comment]
Well, it's not a matter of "why would I want to do that", it's a matter of "We've given you an option that doesn't work".

If you say "tracesDir", and then give a description that says "If specified, traces are saved into this directory.", then yes, I would expect it to work as mentioned.
Here's the type description:
![Screenshot 2023-06-13 at 10 25 59](https://github.com/microsoft/playwright/assets/51020442/bbba4b8c-3f1e-4070-a6d0-0d8bc86eef15)

**Comment by yury-s** [comment]
You are right, `tracesDir`documentation is misleading, Playwright will indeed store the traces in `tracesDir` when you use playwright library and launch the browser manually by calling e.g. `chromium.launch({tracesDir})`. In case of Playwright Test `outputDir` takes precedence and the traces are stored into that directory instead for the browsers created by Playwright fixtures.
