### ISSUE TITLE
Rendering determinism

### ISSUE THREAD

**Issue by sijakret** [microsoft/playwright#23654]
Hello Everyone,

On the topic of rendering determinism in playwright...
I know this has already been discussed here https://github.com/microsoft/playwright/issues/22620, here https://github.com/microsoft/playwright/issues/13873 and here https://github.com/microsoft/playwright/issues/14168 (there are likely more threads on this already).

It is known that external factors like hardware or os (font rendering, drivers, libs) lead to different rendering results of the exact same HTML in the browsers wrapped by playwright. Many of the aforementioned discussions lead back to these type of effects.

A key question that is still open in my mind is the following:

> _Given the **exact same environment** (i.e. same machine, same software versions, same hardware, same os, same drivers) - can we expect the rendering to be deterministic*?_
*deterministic meaning 100% pixel perfect reproduction.

Edit:
To clarify: Between different browsers there can, of course, be minor variations.
What I am wondering about is reproducibility when the selected browser and external factors are kept constant/are locked.

I am aware that given the complexity of modern browser render stacks this question is not trivial to answer (the answer might even be _yes_ for one browser backend and _no_ for another).
In particular, a necessary condition for reproducibility in playwright is of course reproducibility in the respective browser backends. If that is not the case, reproducibility might not be achievable at all..
/Edit

So in a way the question is also: 

> _Is the rendering even **intended** to be deterministic_.

Background:
We are using playwright in an enterprise project for visual regression testing at scale.
So this is a reoccurring topic when we have unexpected differences.
So far, however, I cannot recall any instance where the issue was not eventually tracked down to non-determinism (like timing issues) in OUR code.
So, in a way, I am also looking for info to maybe put these discussions to rest :)

Thanks in advance for any insights!

**Comment by aslushnikov** [comment]
@sijakret in general, chromium rendering is not guaranteed to be deterministic, see https://bugs.chromium.org/p/chromium/issues/detail?id=919955 for the discussion.

This means, that some minor differences **might** be happening. Hope this sheds some light onto the discussion!

**Comment by sijakret** [comment]
Thanks for the link!

My understanding is now the following:
The rendering is *intended* to be deterministic but (currently, and for some time apparently) has bugs that make it non deterministic in some cases.
My arguments for this conclusion:
1) There exit design docs describing significant efforts to make the rendering deterministic (https://docs.google.com/document/d/1PppegrpXhOzKKAuNlP6XOEnviXFGUiX2hop00Cxcv4o/edit)
2) There is the, amongst others, a ```--deterministic-mode``` meta flag that tries to make headless rendering deterministic
3) This is filed as a bug https://bugs.chromium.org/p/chromium/issues/detail?id=919955 and not as a feature request (i do not understand why it is closed, the link in the closing comment takes me nowhere)
