### ISSUE TITLE
[Feature] Expose Request Initiator Chain of Network Calls

### ISSUE THREAD

**Issue by manoj-raghavendran** [microsoft/playwright#23658]
I would love to have a feature that allows you to extract the Request Initiator Chain as seen in the Network Tab in Chrome Dev Tools (see image below). Is this something that is being considered as a potential feature to be added? If so, is there any timeline on its implementation?

<img width="1044" alt="image" src="https://github.com/microsoft/playwright-java/assets/51096931/3a731ede-245f-4f80-8c05-987c37ca060f">

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/23660
