### ISSUE TITLE
[BUG]Unable to pass array as process.env arg to testMatch property in npx playwright command

### ISSUE THREAD

**Issue by badigerpramod** [microsoft/playwright#23655]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: i have many test files but i am interested to run specific test files so i am running below command
- **testMatch='[ngAccordion.automation.ts, ngcheckbox.automation.ts]' npx playwright test --project=chromium**

I get Error: No tests found

I tried adjusting above command with quotes and passing array to testMatch is not working, if i set same array directly in the configs then it works. can you point out me where i am making mistake in the command while setting testMatch

**Comment by MindaugasMateika** [comment]
You can't set testMatch directly from command line as far as I know. Also environment variables are strings no matter what, you need to parse them if you need other type. You're better of passing it without [] - `testMatch='ngAccordion.automation.ts, ngcheckbox.automation.ts'` and then split and make an array out of it -  `process.env.testMatch.split(', ')` in config file.

**Comment by badigerpramod** [comment]
Yes it worked, thank you @MindaugasMateika
