### ISSUE TITLE
[Feature] Developer documentation for starting UI mode as a contributor

### ISSUE THREAD

**Issue by Azim-Palmer** [microsoft/playwright#23669]
Tonight I wanted to sit down and look at options for improving the UI view. I can't see anything in the readme, contributing or other docs on how to start it up and point to a project containing tests.

If the don't already exist I suggest adding instructions for launching UI mode, I suspect they do I've just missed them.

Asked on the discord but nobody is around right now : https://discord.com/channels/807756831384403968/1117917121305915533

**Comment by yury-s** [comment]
All instructions we have are in [CONTRIBUTING.md](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md), you can also have a look at our [workflow](https://github.com/microsoft/playwright/tree/main/.github/workflows) files to see how CI works to get an idea of how the build process works. As for launching the UI mode view you can simply run it with playwright's own tests, e.g. this command in the root of playwright checkout:

```bash
npm run ctest -- --ui page-check.spec.ts
```

Hope this helps.
