### ISSUE TITLE
[Feature] UI Mode doesn't show the test that's running

### ISSUE THREAD

**Issue by BryantUng-at** [microsoft/playwright#23668]
This is a mix between a feature and a bug.  When running a test in UI Mode, the test only shows running if you go all the way down to the test block.  This can be super confusing for developers who click on the folder or file to run and nothing shows up on the UI. Others can benefit because the UX would be a lot better.

Expected: 
By default, the test that's currently running should be showing in the UI.  Alternatively, having a button you can click that will take you to the current test case would be nice.

https://github.com/microsoft/playwright/assets/85197799/d9816423-3b40-4f45-b935-a7a5a33a2382

Playwright Test Version 1.35.0

**Comment by pavelfeldman** [comment]
There is more than one test running at a time (as many tests as there are workers), so I don't think what you are asking is feasible.

**Comment by BryantUng-at** [comment]
What if there's only 1 test running?

**Comment by pavelfeldman** [comment]
In that case, it would be feasible. But I would not want to special-case the slow 1-worker mode.

**Comment by pavelfeldman** [comment]
Closing as won't fix, see above for the rationale!
