### ISSUE TITLE
[Feature] Allow PDF to be returned as a stream.

### ISSUE THREAD

**Issue by j** [microsoft/playwright#2366]
Instead of loading a PDF into memory, I'd like to be able to either return it as a stream or stream an upload to a remote then return it's stream, etc.

Is this possible with chromium's streams?

**Comment by mxschmitt** [comment]
Is a Buffer also enough for you?
It seems like if you specify a path, a Buffer with the PDF will be returned. Makes probably more sense, that the Buffer will also be returned if there is no path specified.

Example:

```js
// @ts-check
const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto("https://github.com");
  const x = await page.pdf({
    path: "foo.pdf"
  })
  console.log(x.length)
  await browser.close();
})();

```

**Comment by j** [comment]
@mxschmitt Yes, I'm using buffers right now.  Just holding a large screen shot in memory (2mb+) is pretty limiting.  I'd like to just stream the result directly into remote storage.

**Comment by aslushnikov** [comment]
There are no plans for this at the moment, so I'll close this for now. We can always revisit later.
