### ISSUE TITLE
[Feature] Expose Request Initiator Chain For Intercepted Network Requests

### ISSUE THREAD

**Issue by manoj-raghavendran** [microsoft/playwright#23660]
I would love to have a feature that allows you to extract the Request Initiator Chain as seen in the Network Tab in Chrome Dev Tools (see image below). Is this something that is being considered as a potential feature to be added? If so, is there any timeline on its implementation?

<img width="1044" alt="image" src="https://github.com/microsoft/playwright-java/assets/51096931/bf500a88-2ff5-43e8-b3ee-4155fde77687">

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
