### ISSUE TITLE
[Feature]Screen capture in case of failure  (Python)

### ISSUE THREAD

**Issue by KobyD1** [microsoft/playwright#23679]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
Hi 
I am using Playwright over Python , is there any option to screen capture in  case of failure ? 
the following flag **screenshot: 'only-on-failure'** should be defined at the configuration file - but I did not find any example /instructions on how to create such a file in the case of Python 

Thanks in advanced 
Koby

**Comment by ltsuda** [comment]
You probably want to use the pytest/playwright (https://playwright.dev/python/docs/test-runners) and configure pytest using a configuration file or use the pytest CLI.

Example of using `pyproject.toml`. Take a look at the `addopts` line, you can add playwright's pytest configuration there.

```bash
[tool.pytest.ini_options]
minversion = "6.2.5"
addopts = "-rA --disable-warnings --browser=chromium --tracing=on --output=test-results"
testpaths = ["tests"]
python_files = ["test_*.py"]
```

**Comment by yury-s** [comment]
> I am using Playwright over Python , is there any option to screen capture in case of failure ?

It is a feature of playwright test runner which is only available for node.js, in python you need to implement it manually.

> the following flag **screenshot: 'only-on-failure'** should be defined at the configuration file - but I did not find any example /instructions on how to create such a file in the case of Python

This is Node.js specific, if you choose Python in the language select of playwright.dev you won't see the option.
