### ISSUE TITLE
[BUG] Playwright for VSCode  - No Playwright tests found.

### ISSUE THREAD

**Issue by yogeshgadge** [microsoft/playwright#23684]
**Context:**

"No Playwright tests found."
In the Testing - Test Explorer

vscode version: 1.79
Playwright Test for VSCode v1.0.13

This morning suddenly after the updates Playwright test are not showing up.

Developer Tools console is showing the error saying node not found.
It is found from bash/zsh shell as it is in the path

```
 ERR [Extension Host] Error: not found: node
at li (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:9:1936)
	at ui (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:9:2673)
	at async V (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:14:966)
	at async Oe._runNode (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:14:7618)
	at async Oe.getPlaywrightInfo (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:14:3484)
	at async Ve._rebuildModel (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:91:5625)
	at async Ve.activate (/Users/REDACTED/.vscode/extensions/ms-playwright.playwright-1.0.13/out/extension.js:91:4834)
```
![image](https://github.com/microsoft/playwright/assets/2423608/c7794119-e04c-4430-b5b3-82f0ad533a76)

- Playwright Version: 1.34.3
- Operating System: mac
- Node.js version: 18.16.0
- Visual Studio Code version: 1.79
- Playwright for VSCode extension version: v1.0.13
- Browser: Chromium
- Extra: my playwright.config.ts is located in <project>/projects/foo-app/src/e2e/playwright.config.ts

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

Add any other details about the problem here.

**Comment by yogeshgadge** [comment]
I believe this is same as https://github.com/microsoft/playwright/issues/20332 I am using nvm and vscode can't find node ?

**Comment by mxschmitt** [comment]
Could you try to completely close vscode and start it again?

**Comment by yogeshgadge** [comment]
Yes I tried that. Also installed node using brew.

**Comment by mxschmitt** [comment]
Just to double check, did you before right click on the vscode icon in the dock and clicked on "Quit"?

**Comment by yogeshgadge** [comment]
I clicked "Quit Visual Studio Code". But I had even restarted my machine.

**Comment by yury-s** [comment]
> Here is what worked - instead of clicking VSCode from Dock navigate to your project folder from open a bash and the open code `code .` and the errors are gone.

When you launch VSCode from terminal it inherits its environment including PATH variable. When launching from dock the PATH is likely different for some reason and `node` binary is not there.  Try following the VSCode troubleshooting guide: https://code.visualstudio.com/docs/supporting/faq#_resolving-shell-environment-fails

There is also some relevant discussions in https://github.com/microsoft/vscode/issues/21655 and https://stackoverflow.com/questions/66162058/vscode-complains-that-resolving-my-environment-takes-too-long

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by Neurovert** [comment]
> Here is what worked - instead of clicking VSCode from Dock navigate to your project folder from open a bash and the open code `code .` and the errors are gone.

best response - works, thank you!

**Comment by jshtawayHR** [comment]
> Here is what worked - instead of clicking VSCode from Dock navigate to your project folder from open a bash and the open code `code .` and the errors are gone.

This did not work for me.

**Comment by yogeshgadge** [comment]
Curious why does playwright need access to the shell? I am assuming that
when vs code is started via a shell it's pkigins gets access to it
