### ISSUE TITLE
[BUG] Browser closes 2 minutes late when test is complete !

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#23681]
### System info
- Playwright Version: [1.24.0]
- Operating System: [Windows 10 Pro]
- Browser: [Chromium]
- Playwright/test Version:[1.33.0]

**Bug Description**
In the test I wrote, the browser stays open for about 2 minutes after the test is completed. There is no such problem in the other tests I wrote. While working on my teammates' computers, the test closes normally. Only on my computer and after only 1 test is completed, browser closes late. What could be the reason for this? Thanks you for your help.

**Expected**

browser closing after test is complete

**Actual**

Test ends, browser closes after 2 minutes.

**Comment by yury-s** [comment]
Does the test run with video recording enabled? Can you share the test/trace of the slow test?

**Comment by MuharremBicici** [comment]
I didn't send trace because when trace is set to all, my browser also closes in case of success and failure, no problem. But when I set trace to failure only, my browser closes too late when the test is successful. I don't experience this situation when failure.

**Comment by yury-s** [comment]
> Does the test run with video recording enabled?

What about this question? ^^

I'm afraid we can't help you without being able to reproduce problem, especially given that doesn't reproduce on another machine. What I can think of is some anti-malware / corp policies getting in the way.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
