### ISSUE TITLE
[Feature] Utilize Chrome for Testing

### ISSUE THREAD

**Issue by KotlinIsland** [microsoft/playwright#23694]
Chrome has a new distro for automated testing, Playwright should use it instead of Chromium.

https://developer.chrome.com/blog/chrome-for-testing/

**Comment by edelreal** [comment]
I like the Chrome-for-Testing approach approach Puppeteer is taking to reduce feature gaps between Chrome and Chromium. Hoping the Chrome-for-Testing works out well and can be integrated into Playwright.

**Comment by DetachHead** [comment]
this issue should be re-opened imo. there are features such as the self XSS warning that are annoying when debugging tests in chromium, which chrome for testing fixes: https://github.com/microsoft/playwright/issues/30425#issuecomment-2067922172

**Comment by ivancuric** [comment]
Can we reopen this issue?

**Comment by sandstrom** [comment]
A big problem with Chrome for testing is that it [doesn't support ARM](https://github.com/GoogleChromeLabs/chrome-for-testing/issues/1), closed as 'not planned' currently.

**Comment by case** [comment]
This shipped in 1.57, fwiw: https://playwright.dev/docs/release-notes#version-157

> Starting with this release, Playwright switches from Chromium, to using [Chrome for Testing](https://developer.chrome.com/blog/chrome-for-testing/) builds. Both headed and headless browsers are subject to this. Your tests should still be passing after upgrading to Playwright 1.57.
> 
> We're expecting no functional changes to come from this switch. The biggest change is the new icon and title in your toolbar.
