### ISSUE TITLE
[Feature] .preceding-sibling() for css why not?

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#23696]
So we had .and() and .or() I like the simplicity of css while finding selectors. However, there're some cases we need to find the preceding-sibling element to verify and css can't help this for a long long time. Hence, it would be very helpful to give css the missing part it needed much appreciated.
P/s: The case here for example is verify the position of some elements between, preceding is on the left or top something like that.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/23718
