### ISSUE TITLE
[Feature] make text-based snapshots cross-platform friendly

### ISSUE THREAD

**Issue by spcoder** [microsoft/playwright#23690]
`toMatchSnapshot` fails to compare successfully on Windows machines when snapshots have been created on *NIX operating systems due to newline inequalities.

**Comment by yury-s** [comment]
Can you share some details about the scenario where this is an issue?

**Comment by aslushnikov** [comment]
I assume this happens due to GIT checkout normalization?

In our case, we solved this with git attributes: https://github.com/microsoft/playwright/blob/51b8f609fbe8d9bbde7765ec627ea25efb7d97d7/.gitattributes#L2

**Comment by spcoder** [comment]
> Can you share some details about the scenario where this is an issue?

yes, sorry. i think the case we're seeing on my team is that our snapshots have been created from macOS and use `\n` newline characters. our Windows developer runs the test suite and it fails due to snapshot differences. the diff display doesn't show any visible differences, and i suspect it's because it's comparing text content generated on Windows with `\r\n` newlines against the saved snapshot which has `\n` newline characters.

**Comment by aslushnikov** [comment]
@spcoder the way to go is usually to normalize git checkout across operating systems, like here: https://github.com/microsoft/playwright/issues/23690#issuecomment-1590081626

Let me know if this helps.

**Comment by spcoder** [comment]
@aslushnikov i'll get with our Windows developer to try the `.gitattributes` fix, and then update here.

**Comment by spcoder** [comment]
@aslushnikov bingo! that did the trick once we re-pulled. thanks for your help!
