### ISSUE TITLE
API request could not be intercepted/modified with page.route()/browser.context()?

### ISSUE THREAD

**Issue by anastasiia-petrenko** [microsoft/playwright#23705]
### Discussed in https://github.com/microsoft/playwright/discussions/23677

<div type='discussions-op-text'>

<sup>Originally posted by **anastasiia-petrenko** June 13, 2023</sup>
I want to cover the API test, which sends a request to real endpoint and if everything is fine return the 303 HTTP code with the link to another endpoint. Due to how 303 is implemented tools notice that HTTP status code and make an automatic redirect and return response from the 2nd endpoint. However, for the sake of clarity, I want to send 2 separate requests. I have discover that `page.route()` can be used to intercept the requests. 

Unfortunately, I didn't manage to go into the `page.route()` method while debugging. Maybe I am missing something?

I have found in one of GitHub issues that [it would just roundtrip it anyways, like a noop](https://github.com/microsoft/playwright/issues/20776#issuecomment-1437025463). 
There is also a separate discussion [how to handle redirects](https://github.com/microsoft/playwright/issues/20501)

If that's true, then only page.goto() can intercept requests, right? 

I am out of options on how the test can be automated in a proper way. Any advice would be valuable

Playwright: 1.35
Language: Typescript

This is my test:
```
test('Intercept redirect', async ({page}) => {
	const route = 'requestPath';

	await page.route(route, async (route, request) => {
		// Wait for the response
		const response = await route.fetch({ maxRedirects: 0 });

		// Check the response status
		if (response.status() === 303) {
			console.log('First endpoint returned a 303 status');
			const locationHeader = response.headers()['location'];
			console.log('Redirect location:', locationHeader);
		} else {
			console.error('Unexpected response status:', response.status());
		}

		route.fulfill({
			status: response.status(),
			headers: response.headers()
		});
	});

	const responseStatus = await page.request.get(route);
});
```

</div>

**Comment by yury-s** [comment]
> I want to cover the API test, which sends a request to real endpoint and if everything is fine return the 303 HTTP code with the link to another endpoint. Due to how 303 is implemented tools notice that HTTP status code and make an automatic redirect and return response from the 2nd endpoint. However, for the sake of clarity, I want to send 2 separate requests. I have discover that `page.route()` can be used to intercept the requests.
> 
> Unfortunately, I didn't manage to go into the `page.route()` method while debugging. Maybe I am missing something?
> 

Requests made with `APIRequestContext` are not interceptable by `page.route()`, `page.route` only intercepts requests sent from the browser.

In your case you can simply check the 303 response and then fetch actual response from the second end-point:

```js
test('Intercept redirect', async ({page}) => {
  	// Wait for the response
    const response = await page.request.get('first endpoint', { maxRedirects: 0 });

		// Check the response status
		if (response.status() === 303) {
			console.log('First endpoint returned a 303 status');
			const locationHeader = response.headers()['location'];
			console.log('Redirect location:', locationHeader);
		} else {
			console.error('Unexpected response status:', response.status());
		}


    // Send request to second endpoint and check its result
    const response2 = await page.request.get('second endpoint', { maxRedirects: 0 });
});

```

Can you clarify why you want to intercept the request which your own test is sending from Node?

**Comment by anastasiia-petrenko** [comment]
The matter of the fact is I want to disable redirect and check first response. 
I have just found out that I can use maxRedirect option for get/fetch request [https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-get-option-max-redirects]()

The interesting thing is when I added that option, it doesn't help much
`const myResponse = await page.request.fetch(route, { method: 'GET', headers: headers, maxRedirects: 0 });`
cause I don't see location header in the responseHeaders, and the response status is 200. However I expect to receive 303.
If I send the same request from console fetch() I see 2 requests with 303 and 200 responses correspondingly.

Looking at the APIResponse methods output (headers, status, json), it seems that myResponse returns json from the initial request, and other interested properties (headers, status) from the endpoint where redirect leads to.

I have checked that file [https://github.com/microsoft/playwright/blob/main/tests/library/global-fetch.spec.ts#L395]() on maxRedirects, and for Playwright 1.35 it should work as expected. Am I missing something?

**Comment by yury-s** [comment]
> cause I don't see location header in the responseHeaders, and the response status is 200. However I expect to receive 303.
If I send the same request from console fetch() I see 2 requests with 303 and 200 responses correspondingly.

Looks like your server just returns different response (200 instead of 303) when you send request using APIRequestContext vs. from browser. It is likely because the request is slightly different too like missing a header or has a different user agent. You can record trace and see which requests were sent or run with `DEBUG=pw:api` in the console.

If you can provide a self-contained repro which we can look into that.

**Comment by anastasiia-petrenko** [comment]
@yury-s
The issue was resolved. I was unable to receive the correct response because the response is time-related and there should be some time in-between to process the input data.
Actually, playwright and the application are both working as expected. I have added expect().toPass() assertion to wait for the correct response.
Thank you very much for your help
