### ISSUE TITLE
[BUG] TypeScript: passing promise to expect should be a type error

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#23715]
### System info
- Playwright Version: 1.34.3
- Operating System: N/A
- Browser: N/A
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

N/A

**Test file (self-contained)**

```ts
test('has the correct title', async ({ page }) => {
  expect(
    // ❌ Oops, we forgot to `await`! This should be a type error.
    page.title(),
  ).toMatch(/foo/);
});
```

**Expected**

A type error.

**Actual**

There is no type error.

---

One way to fix this would be to change the type of the `Expect` signature as follows:

```diff
 export type Expect = {
-  <T = unknown>(actual: T, messageOrOptions?: string | { message?: string }): MakeMatchers<void, T>;
+  <T = unknown>(actual: T extends Promise<any> ? never : T, messageOrOptions?: string | { message?: string }): MakeMatchers<void, T>;
```

I'm not sure if this has other implications though.

**Comment by yury-s** [comment]
We cannot do just that because expect supports promises as actual values, e.g. you can write:

```js
await expect(Promise.resolve(1)).resolves.toBe(1);
```
and changing the type will break such code.

**Comment by OliverJAsh** [comment]
Ah, fair enough. Thanks for the quick response!
