### ISSUE TITLE
[BUG] Issue with css locators in Playwright 1.0.2

### ISSUE THREAD

**Issue by RatnakarShetty** [microsoft/playwright#2372]
**Context:**
- Playwright Version: [1.0.2]
- Operating System: [Windows]
- Browser: [Chromium]

**Code Snippet**
```
const { chromium, firefox, webkit } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });  // Or 'firefox' or 'webkit'.
  const page = await browser.newPage();
  await page.goto('https://www.tutorialspoint.com/index.htm');
  // await page.click(".mui-top-qa > a[title*='Job']") // working fine in both the versions
  // await page.click(".mui-top-qa > a[title*='Job'],div.navbar a") // There is a space in the second locator so not working in 1.0.2 but worked fine in 0.12.1  
  // await page.click(".mui-top-qa > a[title*='Job'],div.navbar") // removed space from the above locator and working in both the version 
  await page.click(".mui-top-qa > a[title*='Job' i]") // due to the presence of "i" not working in 1.0.2 but worked fine in 0.12.1 
   
  //   await browser.close();
})();
```

**Describe the bug**

1.If the css locator having the "i" is not working in playwrite version 1.0.2 but works fine in 0.12.1
ex: **await page.click(".mui-top-qa > a[title*='Job' i]")**
if the css locator having the space in the second locator is not working in playwrite version 1.0.2 but works fine in 0.12.1.
ex: **await page.click(".mui-top-qa > a[title*='Job'],div.navbar a")**

**Comment by dgozman** [comment]
This should be fixed in the v1.1 release. Thank you for filing!

**Comment by RatnakarShetty** [comment]
Hi ,
When can i expect the v1.1 release ?

**Comment by mxschmitt** [comment]
> Hi ,
> Can you please tell me When can i expect the v1.1 release ? Bcz we have written so many locators with space and "i" in it.
> 
> if release is taking more time means we need to rewrite the locators thats why .
> 
> Thanks

As a workaround you can use the master version by installing `npm install playwright@next`
