### ISSUE TITLE
[BUG] Browsers do not download 

### ISSUE THREAD

**Issue by simon-greatrix** [microsoft/playwright#23729]
This is a follow-on from https://github.com/microsoft/playwright/issues/23569 which has been closed.

As requested in issue 23569, here is the debug output from attempting an install:

```
Removing unused browser at /Users/simongreatrix/Library/Caches/ms-playwright/chromium-1067
  pw:install downloading Chromium 115.0.5790.24 (playwright build v1067) - attempt #1 +0ms
Downloading Chromium 115.0.5790.24 (playwright build v1067) from https://playwright.azureedge.net/builds/chromium/1067/chromium-mac.zip
  pw:install running download: +207ms
  pw:install -- from url: https://playwright.azureedge.net/builds/chromium/1067/chromium-mac.zip +0ms
  pw:install -- to location: /var/folders/fn/rj2mq_9947q0v4bbywbrgslh0000gr/T/playwright-download-chromium-mac13-1067.zip +0ms
  pw:install -- response status code: 200 +247ms
  pw:install -- total bytes: 136140840 +0ms
129.8 Mb [====================] 98% 0.5s  pw:install SUCCESS downloading Chromium 115.0.5790.24 (playwright build v1067) +22s
  pw:install extracting archive +1ms
  pw:install -- zip: /var/folders/fn/rj2mq_9947q0v4bbywbrgslh0000gr/T/playwright-download-chromium-mac13-1067.zip +0ms
  pw:install -- location: /Users/simongreatrix/Library/Caches/ms-playwright/chromium-1067 +0ms
  pw:install FAILED installation Chromium 115.0.5790.24 (playwright build v1067) with error: Error: end of central directory record signature not found +7ms
Failed to install browsers
Error: Failed to download Chromium 115.0.5790.24 (playwright build v1067), caused by
Error: end of central directory record signature not found
    at /Users/simongreatrix/tmp/node_modules/playwright-core/lib/zipBundleImpl.js:1:24033
    at /Users/simongreatrix/tmp/node_modules/playwright-core/lib/zipBundleImpl.js:1:31712
    at /Users/simongreatrix/tmp/node_modules/playwright-core/lib/zipBundleImpl.js:1:17288
    at FSReqCallback.wrapper [as oncomplete] (node:fs:682:5)
```

By editing the `browserFetch.js` to remove the clean-up I was able to check the file contents. In each case the file was too short. The bytes in the file were correct, there were just too few of them.

Over 8 downloads the actual file size on disk was:

1) 132595712 (0x7E74000)
2) 133447680 (0x7F44000)
3) 129974272 (0x7BF4000)
4) 133316608 (0x7F24000)
5) 131006464 (0x7CF0000)
6) 130777088 (0x7CB8000)
7) 134053888 (0x7FD8000)
8) SUCCESS! But then it failed on Firefox.

I note that all the file sizes are exact multiples of 16Kb. Could the `oopDownloadMain.js` process be terminating before the disk is flushed?

The expected behaviour would be for the download to work first time, and in a continuous integration environment it is quite important that it does.

**Comment by mxschmitt** [comment]
@simon-greatrix, just to confirm, this is canary like described in https://github.com/microsoft/playwright/issues/23569#issuecomment-1591350874?

**Comment by simon-greatrix** [comment]
Yes - this is canary installed with npm install -D @playwright/test@next as in the comment

**Comment by mxschmitt** [comment]
Thanks! We have a new idea about working around this issue and will most likely implement it in Canary the next few days. Will ping you then, thanks!

**Comment by mxschmitt** [comment]
@simon-greatrix a new version with a potential fix is on the way, you can try it out by updating your @next build like explained in https://github.com/microsoft/playwright/issues/23569#issuecomment-1591350874.

Thanks!

**Comment by mxschmitt** [comment]
I'll close it for now since _we think_ the new workaround should fix this issue. Thanks for testing out and don't hesitate to come back with more logs.

It gets released as part of 1.36 or [via canary](https://playwright.dev/docs/canary-releases) as of today.

**Comment by aswatsankar** [comment]
`INSTALLATION_COMPLETE` does not exist stops the browsers from downloading. 
![image](https://github.com/microsoft/playwright/assets/24888082/7d170b03-7704-4211-88f3-18be34e3b8ab)

**Comment by JuniorTour** [comment]
I got simillar error:
``` js
Downloading Chromium 115.0.5790.75 (playwright build v1071) from https://playwright.azureedge.net/builds/chromium/1071/chromium-linux.zip                                                                 lds/chromium/1071/chromi
Downloading Chromium 115.0.5790.75 (playwright build v1071) from https://playwright-akamai.azureedge.net/builds/chromium/1071/chromium-linux.zip                                                          net/builds/chromium/1071
Downloading Chromium 115.0.5790.75 (playwright build v1071) from https://playwright-verizon.azureedge.net/builds/chromium/1071/chromium-linux.zip                                                         .net/builds/chromium/107
Failed to install browsers
Error: Failed to download Chromium 115.0.5790.75 (playwright build v1071), caused by
Error: Download failure, /home/junior/.cache/ms-playwright/chromium-1071/INSTALLATION_COMPLETE does not exist                                                                                             ot exist
    at ChildProcess.<anonymous> (/mnt/c/Users/nn/Desktop/Programing/my-projest/node_modules/playwriapp/node_modules/playwright-core/lib/server/registry/browserFetcher.js:93:14)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```

It may be related to:
- Windows ubuntu sub system
- Install behind proxy and failed
