### ISSUE TITLE
[Feature] Keep only artifacts (screenshot, video, trace) of lastest failure

### ISSUE THREAD

**Issue by nnson0310** [microsoft/playwright#23723]
When config Playwright to retry up to 2 times and config in "playwright.config.ts" as below:
`
 trace: 'retain-on-failure',
 video: 'retain-on-failure',
screenshot: 'only-on-failure',
`
Even with 5~6 test cases failed, the artifact published to AzureDevOps pipeline easily exceeds ~ 150MB. Sometimes I wish there is a way to only keep the artifacts of latest retry (if test cases fail and need to be retried)
In my case, I only want to keep the artifacts of the second running. Because in most cases, the reason made test cases failed are always the same and I only need the artifact of the lastest one.

**Comment by yury-s** [comment]
Sounds like 'on-first-retry' does what you want already except that it persists trace/video of the first retry rather than the last one, but that should not matter according to your description. Will it work for you?

**Comment by nnson0310** [comment]
Yeah, it worked but not exactly as my expectation. It retains only artifacts of the first retry. But I want to keep the artifacts of lastest retry (if the retry time is more than one, I need the second one). It seems that Playwright does not support this option yet. Anyways, thanks for your response
