### ISSUE TITLE
[BUG] Unable to check url when previewing pdf files

### ISSUE THREAD

**Issue by Skipi0007** [microsoft/playwright#23726]
- Playwright Version: 1.33
- Operating System: macOS 13.2.1
- Browser: WebKit

When i'm trying to check url in new tab with pdf file, checks will be failed in headless mode only.

Source code

test('test title', async ({ classicPage }) => {
			const newPage = await Promise.all([
			classicPage.page.waitForEvent('popup'),
			classicPage.openOriginPdfFile.click(),
		])
await expect(async () => { await expect(newPage.url()).toMatch(url) }).toPass({ timeout: 10000 })
		})

actual: tests will be failed on first step
expected: successfully asserted

**Comment by yury-s** [comment]
Please share full self-contained reproducible example which we could run locally.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one.

**Comment by kurtsansom** [comment]
I am having this same issue on chromium with recent playwright version.
