### ISSUE TITLE
[Question] how to use APIRequestContext to download a file

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#23727]
I have a url , if I enter the url in browser and press Enter, the file will be downloaded , response content type is application/octstream
if I use APIRequestContext.get(...) method, the return type is APIResponse, it has no method to download the file

I can only use APIResponse.text() to get its content , how to download the file?

**Comment by yury-s** [comment]
[APIResponse.body](https://playwright.dev/docs/api/class-apiresponse#api-response-body) or .text() as you mentioned, it will wait until response body is received completely. Alternatively you can us [downloads api](https://playwright.dev/docs/downloads) in the browser. If it doesn't work in some case cases for you please file a bug with self-contained repro.
