### ISSUE TITLE
[General Query] Console log being called 20k+ times

### ISSUE THREAD

**Issue by elementarymindscape** [microsoft/playwright#23730]
Hi, 

```ts
export default async function checkIfElementNotPresent(
  page: Page,
  testInfo: any
) {
  // check if maple null devo content shows up
  // take full page ss and skip test if present
  await skipIfElementHasNullContent(page, testInfo);
  let i = 1;
  do {
    const isElementPresent: boolean = await page
      .locator(CONSTANTS.Element_XPATH)
      .isVisible();
    if (isElementPresent === true) {
      console.clear();
      console.log(`Element FOUND at Reload ${i - 1}`);
      return;
    } else if (isElementPresent === false) {
      if (i == 6) {
        console.clear();
        console.log(`Element NOT FOUND AFTER 5 RELOADS`);
        test.fail();
      } else {
        i++;
        await page.reload({ waitUntil: CONSTANTS.DOM_CONTENT_LOADED });
      }
    }
  } while (i <= 6);
}

async function skipIfElementHasNullContent(page: Page, testInfo: any) {
  const isNullElementContentPresent: boolean = await page
    .getByText('null devo content')
    .isVisible();
  if (isNullElementContentPresent === true) {
    console.clear();
    console.log(`Element NULL CONTENT`);
    const ss = await page.screenshot({ fullPage: true });
    await testInfo.attach('Element null content', {
      body: ss,
      contentType: 'image/png',
    });
    test.skip();
  }
}
```
I have this piece of code and it checks if an element is present on the page or not and reloads (max 5 times) in case if it is not found  and if it is not found after 5 reloads it logs saying that the element was not found after 5 reloads and fails the test.

But in the console logs I am seeing Banner not found multiple times, when I copy pasted the logs in VS Code, I found that it was being logged 20k+ times, I tried clearing console in case it was persisting values from the previous console logs in case of flaky tests, but the result is the same having 20k+ logs.

Any help on this is appreciated.

**Comment by yury-s** [comment]
`tes.fail()` does not fail the test, it just [Unconditionally marks a test as "should fail"](https://playwright.dev/docs/api/class-test#test-fail-1), in other words it changes expected outcome of the test. Moreover once i === 6 your code will get stuck in an infinite loop:

```js
  do {
...
      if (i == 6) {
        console.clear();
        console.log(`Element NOT FOUND AFTER 5 RELOADS`);
        test.fail();
      } 
...
  } while (i <= 6);
}
```
if you want to fail the test you can simply throw an error:

```js
      if (i == 6) {
        console.clear();
        throw new Error(`Element NOT FOUND AFTER 5 RELOADS`);
      } else {
```
Also we recommend using web assertion toBeVisible instead of isVisible as the former will wait for the element to become visible.
