### ISSUE TITLE
pass functions and variable to test in globalSetup[Feature]

### ISSUE THREAD

**Issue by william-spec** [microsoft/playwright#23747]
hi, I want to create a Websocket when process start, and I want it to be create only once, so I new a Websocket in globalSetup, but now I want to send messages in test, so how I get the websocket instance in a test? 
when it's testing with workers, it seems every worker is dependent and can not share the same websocket

globalSetup.ts
```
const globalSetup = async () => {
  const ws = new Websocket();
};

export default globalSetup;
```

```
test.beforeEach(async () => {
 ws.send('')
});

test.afterEach(async ({}, testInfo) => {
  ws.send('')
});

test('my test', ...)
```

**Comment by yury-s** [comment]
Test workers are independent worker process, see [this doc](https://playwright.dev/docs/test-parallel#worker-processes) so you cannot reuse object instances between them. Moreover the legacy globalSetup script runs in the test runner process, in the new tests we recommend you use [project dependencies](https://playwright.dev/docs/test-global-setup-teardown) for global setup. For the shared websocket you best bet is [test.beforeAll](https://playwright.dev/docs/api/class-test#test-before-all) where you can create a websocket which will be reused by all tests in that process.
