### ISSUE TITLE
[BUG] Blank page after page.goto (in CI only)

### ISSUE THREAD

**Issue by tkowalski-exxeta** [microsoft/playwright#23751]
### System info
- Playwright Version: [v1.33, v1.34, v1.35]
- Operating System: [Linux]
- Browser: [Chromium]
- Other info: Teamcity CI, Docker Wrapper via Node.js-Task

**Description**
Nearly all tests fail with in CI most of the time (running docker image playwright:v1.35.0-jammy, tried as well with 1.34 and 1.33). 
The Traces show a blank screen after 'page.goto' and the subsequent locator fails to find anything and times out.
Sometimes (rarely) tests succeed on initial run or on the second or third retry.

Testsuite is running perfectly fine locally in Windows via VSCode or in Docker (using the same image and parameters as the CI does). 

Unfortunately I was not able to reproduce the issue locally. Do you have on suggestions on how I could proceed to pinpoint the issue a little bit better?.

**Expected**
Runs in Docker using the same docker-image and -parameters should work the same no matter whether they are run on a laptop or a build agent.

**Actual**
Nearly all tests fail with in CI most of the time and Traces show a blank screen after 'page.goto' with subsequent locator fails to find anything.

## Possible relevant runtime information
docker.server.osType	linux
docker.server.version	20.10.23
docker.version	20.10.23
teamcity.agent.hardware.cpuCount	4
teamcity.agent.hardware.memorySizeMb	6949
teamcity.agent.jvm.os.arch	amd64
teamcity.agent.jvm.os.name	Linux
teamcity.agent.jvm.os.version	5.4.0-147-generic
system.teamcity.version	2022.10.3 (build 117072)

**script**
npm install
npx playwright test --update-snapshots

**docker-images used**
playwright:v1.33.0-jammy
playwright:v1.34.0-jammy
playwright:v1.35.0-jammy

**additional docker parameter**
--env DEBUG=pw:browser*,pw:api --network host -v %teamcity.build.checkoutDir%/zimdbvwgui:/work/ -w /work/

[build-output.log](https://github.com/microsoft/playwright/files/11768862/build-output.log)

**Comment by yury-s** [comment]
Did you run with the same env variable locally as on CI? E.g. it may be that some config options are different depending on whether you hava `CI=1` in you env. Unfortunately we can't help much without a repro. 

This line in the log
```
[08:42:24]W:	 [Step 1/1]    [30;1mpw:browser  [0m[pid=2038][err] [0616/064224.929895:ERROR:cert_issuer_source_aia.cc(134)] AiaRequest::OnFetchCompleted got error -301  [30m+107ms [0m
```
suggests (just a wild guess) that you might have an issue with certificates in that env.

**Comment by yury-s** [comment]
We need more information to act on this report. Without being able to reproduce it locally there is not much we can do as it is like a problem with the CI config.

**Comment by tkowalski-exxeta** [comment]
@yury-s Thanks for you effort. As it turned out, the problem was not related to Playwright in any way. Our CI has no internet-access and our code was not prepared for that. Sorry for the trouble cause by that.
