### ISSUE TITLE
[BUG] Response body missing for some responses

### ISSUE THREAD

**Issue by smckee-r7** [microsoft/playwright#23750]
### System info
- Playwright Version: 1.35.1
- Operating System: macOS 13.3
- Browser: Chromium

### Code Snippet
```javascript
const { chromium, firefox } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });
  const context = await browser.newContext();
  const page = await context.newPage();

  const cdp = await context.newCDPSession(page);
  await cdp.send('Fetch.enable', {
    patterns: [{ urlPattern: '*', requestStage: 'Response' }]
  });
  let track = {}

  // CDP intercept response
  cdp.on('Fetch.requestPaused', async ({ requestId, request: { url }, responseStatusCode }) => {
    if (responseStatusCode !== 302 && responseStatusCode !== 301 && responseStatusCode !== 204) {
      try {
        // Get CDP response body
        const res = (await cdp.send('Fetch.getResponseBody', { requestId }));

        // decode response body if encoded
        let body = res.body;
        if (res?.base64Encoded) {
          body = Buffer.from(res.body, 'base64').toString('ascii');
        }

        // add body to object to track
        track[url] = body;
      } catch (error) {
        console.log('ERROR: Failed to get CDP body -', url, '\n')
      }
    }
    // continue response with no modifciation
    return cdp.send('Fetch.continueResponse', { requestId });
  })

  page.on('requestfinished', async (request) => {
    const url = request.url();
    const response = await request.response();
    await response.finished();

    try {
      if (response.ok()) {
        // convert body buffer to ascci string to compare
        const buffer = await response.body();
        const body = buffer.toString('ascii');

        // if playwright body is empty and it doesn't match the CDP body then log the results
        if (buffer.length === 0 && track[url]?.length && body?.length !== track[url]?.length) {
          console.log(url, request.method());
          console.log('CDP body length:', track[url]?.length);
          console.log('Playwright body length:', body?.length, '\n');
        }
      }
    } catch (error) {
      console.log('ERROR: Failed to get body -', url, '\n');
    }
  });

  await page.goto('https://booking.com/');
})();
```

### Description
Playwrights `response.body()` incorrectly returns an empty buffer for some sub-requests. These response bodies when viewed in devtools or intercepted using CDP contain valid content and the pages load fine, but playwrights `response.body()` for these requests are empty. Tested in FireFox without the CDP code and `response.body()` worked as expected; returning the body content as a buffer.

The URLs that have this behaviour can be seen by running the snippet above, but for reference here are the URLs I'm seeing with empty bodies in playwright:
 - https://cf.bstatic.com/static/css/searchresults_cloudfront_sd.iq_ltr/e05becd48d87b8c5889ea9c42927584f3ffb7cca.css
 - https://cf.bstatic.com/static/js/searchresults_cloudfront_sd/2d4f8629b81d9f64d5cf3ea62e07493cd57118f0.js
 - https://cf.bstatic.com/static/js/atlas_cloudfront_sd/19f3caf45683339908eb5c67a2339275f1e20e50.js
 - https://cf.bstatic.com/static/js/atlas_cst_cloudfront_sd/91c34589b58a67bcd2f5314c65a840b0b7ef40dc.js
 - https://cf.bstatic.com/static/js/calendar2_cloudfront_sd/06071dd1c4e89fbe99e5ad6e21584a6bf9585e84.js
 - https://cf.bstatic.com/static/js/searchresults_slick_cloudfront_sd/528359eb9f21194adf8c26f81e07c6eb21a2cc89.js

This is the 2nd site I have found with this issue and have tested 20 or so random sites. In both cases this issue happened with only css and js files.

**Comment by yury-s** [comment]
I can reproduce it, the response body is indeed missing in some of the responses.

> These response bodies when viewed in devtools or intercepted using CDP contain valid content

I see "Failed to load response data:..." message in DevTools for all those requests.
