### ISSUE TITLE
[BUG] 301 permanent redirect to trace id causes ui mode to get stuck 

### ISSUE THREAD

**Issue by Machiel-B** [microsoft/playwright#23752]
### System info
- Playwright Version: 1.36.0-next
- Operating System: Ubuntu 22.04 
- Browser: All
- Other info: running the latest docker image mcr.microsoft.com/playwright:v1.36.0-alpha-jun-16-2023, but it also happens in other environments

### Source code

Default example suite can be used.

**Steps**
- run the tests in ui mode with a host + port  provided e.g. `npx playwright test --ui --ui-host=127.0.0.1 --ui-port=8007`
- using Chrome or firefox browser visit the host + port e.g. http://127.0.0.1:8007 to access the web ui
- the path gets redirected to a to the trace view, with a randomly generated hahs identifier in the url. I.e. `/trace/uiMode.html?ws=<random hash id>`
- restart the server
- visit the root path `/` again in the browser 

**Expected**

The web ui should load the (example) tests

**Actual**

The ui doesn't load and some errors are thrown in the console. 

I pinned this down to the redirect [here](https://github.com/microsoft/playwright/blob/main/packages/playwright-core/src/server/trace/viewer/traceViewer.ts#L128) using a 301 status code. 

This means the browser will cache the redirect indefinitely. 

The effect is that the browser will now keep redirecting to the trace id of the initial run. Which in turn causes an error when the app tries to connect to the ws interface using that stale identifier.

Current workaround is to use the browser devtools and disable caching in the network tab, but that is not ideal.

Proposed solution is to use a 307 redirect, which would not be cached indefinitely.

**Comment by mxschmitt** [comment]
Great investigation! I think 302 fits better, would you be open for a contribution?

**Comment by Machiel-B** [comment]
@mxschmitt I've made a pull-request. Do I need to jump through any hoops before it can accepted?

**Comment by mxschmitt** [comment]
This should be enough, thanks!

**Comment by Machiel-B** [comment]
Great, thanks for helping out!
