### ISSUE TITLE
[BUG] Ubuntu Jammy 22.04 might have issue with Control+C/Control+V hotkeys

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#23767]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [Ubuntu 22.04]
- Browser: Chromium
- Other info:

So I'm write a function to copy and paste a string for me from one block to another. It worked find in my local machine using Windows, worked on the old playwright docker image too. But After upgraded to the latest (jammy 22.04) the test failed and trace shows that the copy and paste step not work as expected.

### Source code

**Steps**
- Highlight and Copy text by key.press("Control+C")
- Paste text to other field by key.press("Control+V")

**Expected**

Pasted successfully 

**Actual**

There's nothing new pasted on the field

**Comment by Dinh246** [comment]
Addtional Info: 
It might relate to the [contenteditable] issue because I copy from one to another. It still worked with input

**Comment by yury-s** [comment]
We need to be able to reproduce the problem to make this report actionable. Could you share a reproducible example which we could run locally?

Also see related [feature request](https://github.com/microsoft/playwright/issues/15860).

**Comment by Dinh246** [comment]
@yury-s  You can try these steps in Ubuntu (still work fine in window)
1. Copy text from a [contenteditable] element by pressing ctrl+C
2. Paste text to another [contenteditable] element by pressing ctrl+V
And repeat above steps with input element and it should work fine in Ubuntu

**Comment by dgozman** [comment]
@Dinh246 It would be great if you could provide the script that we can run, including the `[contenteditable]` markup and your keyboard API calls. This way we'll be able to efficiently debug the issue instead of trying to figure out the exact scenario that does not work for you.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
