### ISSUE TITLE
[BUG] HTML test result is displaying Internal error: unknown test(s) in worker

### ISSUE THREAD

**Issue by xyngfei** [microsoft/playwright#23779]
### System info
- Playwright Version: [v1.35.1]
- Operating System: macOS 13.2.1 (22D68)
- Browser: All
- Other info:

### Source code

```js
import { expect, test } from "@playwright/test";

test.describe("Test", () => {
  [
    {
      textInput: "123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
    {
      textInput: "0.123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
    {
      textInput: "-123".padEnd(10, Math.round(Math.random() * 10000).toString()),
    },
  ].forEach((testCase) => {
    test(`@haha verify input behavior with value "${testCase.textInput}"`, async () => {
      // assume we make some action with given value
      // locator.fill(testCase.textInput);
      expect(true).toBe(true);
    });
  });
});
```

**Steps**
- Refer to the existing [issue](https://github.com/microsoft/playwright/issues/13892), it has been fixed. However, the default rest result still displays Internal error: unknown test(s) in worker:
- 

**Expected**

It should not display Internal error issue

**Actual**

![image](https://github.com/microsoft/playwright/assets/17619539/4f17b06e-92a1-4277-9a5b-de39fd9a9976)

**Comment by xyngfei** [comment]
@dgozman curious, I don't understand how ur commit can resolve an unknown test issue. Does it mean pw 1.35.1 will not support random test titles?

**Comment by dgozman** [comment]
@xyngfei Playwright has never supported random test titles, and will not in the future. I have just made the error message friendlier. Please use stable test titles than do not change over time.
