### ISSUE TITLE
[BUG] Download path is not honored when sending Browser.setDownloadBehavior CDP method with default behavior

### ISSUE THREAD

**Issue by borfig** [microsoft/playwright#23776]
### System info
- Playwright Version: v1.35.1
- Operating System: macOS 13.4
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```typescript
import { mkdtemp, rm } from "fs/promises";
import { tmpdir } from "os";
import path from "path";
import { test as base, chromium, BrowserContext } from "@playwright/test";

const test = base.extend<{
  downloadsPath: string;
  context: BrowserContext;
}>({
  downloadsPath: async ({}, use) => {
    const downloadsPath = await mkdtemp(path.join(tmpdir(), "playwright-downloads-path-"));
    await use(downloadsPath);
    await rm(downloadsPath, { recursive: true });
  },
  context: async ({ channel, downloadsPath }, use) => {
    const context = await chromium.launchPersistentContext("", {
      headless: false,
      args: [
        "--headless=new",
      ],
      downloadsPath,
      channel,
    });
    await use(context);
    await context.close();
  }
});

test("click to download", async ({ context, downloadsPath }) => {
  const page = await context.newPage();
  await page.goto("https://www.example.com/");
  await page.setContent(`
    <a href="https://github.com/microsoft/playwright/archive/refs/tags/v1.35.1.tar.gz">open</a>
  `);
  const cdpSession = await context.newCDPSession(page);
  await cdpSession.send("Browser.setDownloadBehavior", {
    behavior: "default",
    downloadPath: downloadsPath,
    eventsEnabled: true,
  });
  await cdpSession.detach();

  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.click("a"),
  ]);
  test.expect(await download.path()).toContain(downloadsPath);
  await download.saveAs("tarball.tar.gz");
});
```

**Steps**
- Run the test

**Expected**

The test to pass

**Actual**

`saveAs` fails because the file is actually downloaded to the real user's Download folder.

**Notes**
- I use `Browser.setDownloadBehavior` with `default` behavior to work around #19885

**Comment by dgozman** [comment]
@borfig Unfortunately, working correctly in these circumstances is out of scope of Playwright. When you make CDP calls, there are no guarantees that every Playwright API will continue to work. In fact, it is easy to mess up with CDP and break Playwright operations.

I'd recommend focusing on #19885 instead.

Alternatively, you can file an issue against Chromium, so that `downloadPath` in your `Browser.setDownloadBehavior` method is not ignored when passing `behavior: 'default'` and see how it goes. That could make your workaround actually work.

Sorry for not being of much help!
