### ISSUE TITLE
[Feature] Expose Request Initiator Chain For Intercepted Network Requests

### ISSUE THREAD

**Issue by manoj-raghavendran** [microsoft/playwright#23778]
[[Reposting issue along with use cases]](https://github.com/microsoft/playwright/issues/23660) I would love to have a feature that allows you to extract the Request Initiator Chain as seen in the Network Tab in Chrome Dev Tools (see image below). Is this something that is being considered as a potential feature to be added? If so, is there any timeline on its implementation?
![image](https://github.com/microsoft/playwright/assets/51096931/3724e4a9-f93a-4131-85cf-0f10baae3af9)

Here are some popular use cases mentioned in the request for the same feature in Puppeteer:

- "assuming you use it to analyze a website which includes 3rd-party code like social sharing buttons. You may want to know which requests were initiated by your own 1st-party code and which requests were initiated by 3rd-party code. This could help you spot performance problems like 3rd-party widgets that cause a lot of subsequent requests."
- "We want to build request maps to vizualise which request was called from where. So we can check, where are performance/memory leaks at 3rd party includes. This could be very helpful to point out, which scripts or iframes initate a waste amount of requests/cookies/trackers. We have all information to build this, except of the initiator of the request."
- "I need this to track malvertising"

Personally, I need access to the request initiator so that I can extract the tracking pixels that are dropped in my web application and build the initiator chain mapping to identify which 3rd-party is using that tracking pixel.

**Comment by dgozman** [comment]
@manoj-raghavendran Thank you for the issue and usecases. All of them seem valid, but also to the side of the end-to-end testing that Playwright focuses on. I am also not sure whether initiator information is easily available in all browsers.

I'll keep the issue open for prioritization, but given the above it's unlikely to be implemented soon.

**Comment by manoj-raghavendran** [comment]
@dgozmanI I understand. Thank you for the quick response. I can actually get this initiator info from the Network.Initiator object through a CDP session in Playwright, but only in Node.js, Python and .NET. The CDP session feature is not available in _Playwright for Java_ as of yet. If the CDP session feature is made available in _Playwright for Java_, that in itself would be sufficient. Do you have any idea why this feature is not available in the Java version? Any possibility that it could be implemented in the near future?

**Comment by dgozman** [comment]
@manoj-raghavendran see https://github.com/microsoft/playwright-java/issues/823.

**Comment by manoj-raghavendran** [comment]
@dgozman I'd actually commented there a couple of weeks back, but I couldn't find any info on the timeline for implementing this feature. So I wanted to know if you had any idea.

**Comment by BennyAlex** [comment]
Please add this feature.
I dont want to have to switch to puppeteer for this one feature.

**Comment by ifduyue** [comment]
There is now [Browser.startTracing](https://playwright.dev/docs/api/class-browser#browser-start-tracing), together with  [Browser.recordHar](https://playwright.dev/docs/api/class-browser#browser-new-context-option-record-har), maybe we can piece together all the fragments and get request and its callFrames (I haven't validate this idea yet).

However, it's nice to include initiator info in har files and in request/requestfinished/requestfailed event data.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
