### ISSUE TITLE
[Feature] Running playwright tests with multiple projects

### ISSUE THREAD

**Issue by Tal-D** [microsoft/playwright#23770]
In the current version the user can add the 'project' flag the test execution command in order to run tests with a single project. If this flag is not added to the command, then playwright run all of the projects by default: https://playwright.dev/docs/test-projects#run-projects.

For every project we can define running browser and tests directory. If we define in the configuration file multiple projects with the same browser, it will be helpful if the command will enable multiple project flags or a single project flag that also accepts a regex, or matching projects names by the flag value.

For example, in the following configuration file we defined multiple projects that test three applications with Chrome and Firefox.

```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  ...

  projects: [
    {
      name: 'chrome - first application',
      testDir: 'tests/firstApp',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'chrome - second application',
      testDir: 'tests/secondApp',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'chrome - third application',
      testDir: 'tests/thirdApp',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox - second application',
      testDir: 'tests/secondApp',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'firefox - third application',
      testDir: 'tests/thirdApp',
      use: { ...devices['Desktop Firefox'] },
    },
  ],

  ...
});
```

We want to test only project that run with Chrome. Currently we need to run the command multiple times, or use the default option (run without the project flag) and get additional results - in the example, Firefox projects results.

According to the suggestion, we can use one of the following variations to run multiple Chrome projects:

- Multiple flag occurrences in the command:
playwright test --project 'chrome - first application' --project 'chrome - second application' --project 'chrome - third application'

- Project flag that support regex:
playwright test --project '^chrome'

- Matching projects names by partial match to flag value (might require an additional flag):
playwright test --project 'third application'
(In this example the command will run tests for projects 'chrome - third application' and 'firefox - third application'.)

**Comment by dgozman** [comment]
Thank you for the issue!

> ```playwright test --project 'chrome - first application' --project 'chrome - second application' --project 'chrome - third application'```

I believe this already works.

> Project flag that support regex:
> Matching projects names by partial match to flag value

See #15128 for the similar request. I'll close this issue in favor of #15128, please continue discussion there.

**Comment by kyleruscigno** [comment]
Adding functionality to run projects based on a regex would also be helpful for CI contexts such as github actions, making it easier to run multiple projects based on an input configuration, rather than having to run them separately

`jobs:
  run_e2e_tests:
    name: Run end-to-end tests on demand
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test --project ${{ inputs.project }} --grep '${{ inputs.runOnlyMatching }}' --workers ${{ inputs.workers }}
`
