### ISSUE TITLE
[BUG] full_page flag not work on python

### ISSUE THREAD

**Issue by jayhyuk** [microsoft/playwright#23777]
### System info
- Playwright Version: [v1.28.0]
- Operating System: [Ubuntu 20]
- Browser: [ Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```python
// playwright.py
from playwright.sync_api import sync_playwright
import time


def capture_image(url,height,width):
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(device_scale_factor=1,viewport={"height":height,"width":width} )
        page = context.new_page()
        page.goto(url, wait_until="networkidle")
        page.screenshot(path="screenshot.png",full_page=True)
        page.close()
        browser.close()
```

**Test file (self-contained)**

```python 
from playwright import capture_image
capture_image('long screen url',2400,1200)
```

**Steps**
- [Run the test]
- [...]

**Expected**

capture full screen 

**Actual**

it capture only some part , like it trust the heigh that put in view port

**Comment by dgozman** [comment]
@jayhyuk We need a full repro that we can run locally, including your page url, expected screenshot and the actual screenshot that you got. Without that, we won't be able to fix the issue.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
