### ISSUE TITLE
[BUG] Chromium screen orientation angle is incorrect

### ISSUE THREAD

**Issue by zhengjitf** [microsoft/playwright#23772]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [macOS 13.2]
- Browser: [Chromium]
- Other info:

**Description**
I used `MobileDatePicker`, a component from [MUI](https://mui.com/x/react-date-pickers/date-picker/), in a desktop website. It displays differently in local Chrome and in Playwright Chromium (use `Desktop Chrome`, and `viewport = { width: 1200, height: 800 }`).

**Expected**
It is the same in Playwright Chromium as in the local Chrome, as below:

![image](https://github.com/microsoft/playwright/assets/17249775/9f7aef15-eba5-4506-a664-29df3ad692ef)

**Actual**
It displays in Playwright Chromium as below:

![image](https://github.com/microsoft/playwright/assets/17249775/af515c92-e810-490a-b3f5-7ec8d7449d44)

**Investigate**
`MobileDatePicker` displays differently according to `screen.orientation.angle`, and Playwright Chromium set the incorrect angle:

https://github.com/microsoft/playwright/blob/e171194c86a8c86a598e86a7f04abc0c3e786d34/packages/playwright-core/src/server/chromium/crPage.ts#L1011-L1021

According to [Screen Orientation API Spec](https://w3c.github.io/screen-orientation/#the-current-screen-orientation-type-and-angle), the angle is also associated with the [natural](https://w3c.github.io/screen-orientation/#dfn-natural) orientation.

![image](https://github.com/microsoft/playwright/assets/17249775/a9237904-5429-48c7-8d1f-b57aae881604)

![image](https://github.com/microsoft/playwright/assets/17249775/b39e0705-bfc3-4761-ac62-b3b964a5debb)

Besides, in my understanding, `isLandscape` depends on screen size, not viewport size, is it right? 🤔

Refer to the solution for Webkit, the `screenOrientation` should be always `{ angle: 0, type: 'landscapePrimary' }` for not mobile devices, but the logic for mobile devices is similar as below:

https://github.com/microsoft/playwright/blob/e171194c86a8c86a598e86a7f04abc0c3e786d34/packages/playwright-core/src/server/webkit/wkPage.ts#L718-L721

If you think it makes sense, I'd like to submit a PR to apply it.

**Comment by dgozman** [comment]
> Besides, in my understanding, isLandscape depends on screen size, not viewport size, is it right?

Correct. IIRC, screen size could be missing and we should fallback to viewport size in that case.

> If you think it makes sense, I'd like to submit a PR to apply it.

Yep, great analysis! We'd love to review a PR for this 😄
