### ISSUE TITLE
[BUG] Chrome won't launch in v1.35.1 in a docker container

### ISSUE THREAD

**Issue by lkaisers** [microsoft/playwright#23784]
My host machine is a MacBook Pro with an Apple M1 Pro CPU running Ventura 13.4. We want to use docker to have consistent screenshot comparison results in our playwright tests. Unfortunately, chrome won't launch and throws an error (see below). You can try it with any test but the result is that the test fails immediately. I added `RUN npx playwright install --with-deps chrome` to the Dockerfile since chrome isn't installed by default.

### System info
- Playwright Version: 1.35.1
- Operating System: Ubuntu 22.04.2 LTS
- Browser: Chrome
- Other info: Running a docker container

### Source code

**Dockerfile**
```go
# Use the official Playwright Docker image
FROM mcr.microsoft.com/playwright:v1.35.1-jammy

# Create a directory for the app
WORKDIR /tests

# Copy package.json
COPY package.json /tests

# Copy the playwright configuration file
COPY playwright.config.js /tests

# Install dependencies
RUN npm install
RUN npx playwright install --with-deps
RUN npx playwright install --with-deps chrome
```

**playwright.config.js (excerpt)**
```js
projects: [
	{
		name: 'Chromium',
		use: {
			...devices['Desktop Chrome'],
			channel: 'chrome',
		},
	},
	{
		name: 'Safari',
		use: {
			...devices['Desktop Safari'],
		},
	},
	{
		name: 'Mobile',
		use: {
			...devices['iPhone 12'],
		},
	},
],
```

**Steps**
- Run `docker build -t playwright-docker .` to build the image
- Run a container via `docker run -it --rm playwright-docker /bin/bash`
- Create any test and run it via `npx playwright test`

**Expected**

Any test runs on Chrome.

**Actual**

Tests run fine on any browser except chrome / chromium.

Log:
Error: browserType.launch: Browser closed.
    ==================== Browser output: ====================
    <launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-P5OBkO --remote-debugging-pipe --no-startup-window
    <launched> pid=5679
    [pid=5679][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=5679][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=5679][err] [0619/105921.892798:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=5679][err] [0619/105921.981486:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
    [pid=5679][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)
    =========================== logs ===========================
    <launching> /opt/google/chrome/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-P5OBkO --remote-debugging-pipe --no-startup-window
    <launched> pid=5679
    [pid=5679][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=5679][err] qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
    [pid=5679][err] [0619/105921.892798:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=5679][err] [0619/105921.981486:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Function not implemented (38)
    [pid=5679][err] Assertion failed: p_rcu_reader->depth != 0 (/qemu/include/qemu/rcu.h: rcu_read_unlock: 101)

**Comment by mxschmitt** [comment]
The issue is that Google Chrome is not available for linux/am64 and you are emulating amd64 with Docker what Google Chrome does not like, see https://github.com/microsoft/playwright/issues/17395#issuecomment-1250830493.

**Comment by lkaisers** [comment]
Thank you, @mxschmitt. But even if I omit the channel property nothing chanes. What is your recommended way to use Chromium then?

**Comment by mxschmitt** [comment]
You can run your Docker container like this, and then it should work:

```
docker run -it --platform linux/arm64 --rm playwright-docker /bin/bash
```

**Comment by lkaisers** [comment]
Thank you!
