### ISSUE TITLE
[BUG] Another Font kerning issue in WebKit

### ISSUE THREAD

**Issue by edumserrano** [microsoft/playwright#23789]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Ubuntu 20]
- Browser: [WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

I have not provided a sample repro for this as it's not something I can reproduce easily. It would probably be harder for me to try to create a smaller version of the code where I'm having this problem and then still be able to replicate it. 
The app I'm working on is small and although I'm not comfortable exposing it as a public repo I would be open to creating a private repo and give access to the required people that would investigate this. 

Alternatively, I'm open to getting on a discord call and demo the problem and provide any further information.

### Problem description

When I run the tests I get a similar problem to what is reported in #20203. See the images below where the spacing between `m` and `i` in the word  `academic` is not deterministic will sometimes make tests fail.

Diff:
![image](https://github.com/microsoft/playwright/assets/15857357/d21fa0f2-45c2-4aba-8c3b-80e7d4c15ebf)

Actual:
![image](https://github.com/microsoft/playwright/assets/15857357/89c4de18-4f76-4357-855a-3580fb4764d2)

Expected:
![image](https://github.com/microsoft/playwright/assets/15857357/707eaa28-d959-49cd-ace4-918d7af96667)

I've tried the workaround proposed in #20203 but it didn't work for my case. 
So far, the only workaround I found that seems reliably work is to do `await page.waitForTimeout(1500);` before I do `await expect(page).toHaveScreenshot();`. On my PC, I've tried 500ms and 1s and those always fail but the 1.5s seems to always be successful so far.

Any suggestions?

### Notes

- Initially this test would sometimes pass and sometimes fail. The way I got it to always fail when running locally was to run with `workers: 1` instead of `workers: undefined`.
- When running locally, I'm on a `Windows 10` OS and I run the test via the docker image `mcr.microsoft.com/playwright:v1.35.1-jammy`.
- When running this test on the CI server, the CI server uses an Ubuntu distro and it almost never fails. In the times where it fails, the fact that I have `retries` set to `2` in the playwright config when it's running on CI was enough to avoid a flaky pipeline.

**Comment by dgozman** [comment]
@edumserrano Have you tried to wait for the [fonts to be loaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/fonts#doing_operation_after_all_fonts_are_loaded), before making a screenshot?

```
await page.evaluate(() => document.fonts.ready);
```

**Comment by edumserrano** [comment]
When I said:
> I've tried the workaround proposed in #20203 but it didn't work for my case.

The workaround is the code you've linked and it does not solve my issue.

**Comment by dgozman** [comment]
@edumserrano Unfortunately, we cannot even start fixing this without a repro. There seems to be something racy and complicated, and guessing without any information will not yield results.

As you've noticed, `retries` is probably the workaround for now. If/when you can come up with a repro that we can run locally and see the problem, even in 10% of runs, please file a new issue and we'll happily take a look.

**Comment by edumserrano** [comment]
Is repro the only way forward for this? Isn't there any kind of tracing or whatever that I can provide to help debug? Alternatively, as I've said, I'm not comfortable with creating a public repo for this project but I could provide a private repo and give access to people of your team to help debug?  Would this be ok?

**Comment by dgozman** [comment]
> Is repro the only way forward for this? Isn't there any kind of tracing or whatever that I can provide to help debug?

That's unlikely. Tracing would be too high-level to figure out the issue.

> I could provide a private repo and give access to people of your team to help debug

Well, you can invite @dgozman and @yury-s to a private repo. That said, fixing this issue seems to be high-effort and low-impact, so I don't think we'll prioritize it in the near future. Sorry for not being of much help.

**Comment by edumserrano** [comment]
Ok, I'll try to get a private repo setup and if/when I do I'll leave a note here and ask you to re-open so this can be in your backlog to look at when possible.

**Comment by cooper667** [comment]
We've intermittently seen this too fwiw. Will try to narrow down and replicate! 

(Currently 'solving' by setting retries in CI)
