### ISSUE TITLE
[BUG] Error: Invalid product: msedge. Valid product types: chromium, firefox, webkit

### ISSUE THREAD

**Issue by trusktr** [microsoft/playwright#23783]
### System info
- Playwright Version: 8.19.3
- Operating System: Ubuntu 22.04.2, macOS 13.4 (EDIT: and also latest Windows (in GitHub Actions))
- Browser: n/a
- Other info:

### Source code

Failed GitHub Actions:

https://github.com/bytescript/bytescript/actions/runs/5310143531/jobs/9611726634

**Link to the GitHub repository with the repro**

https://github.com/bytescript/bytescript on this branch: https://github.com/bytescript/bytescript/pull/27

or

**Config file**

I run the `playwright install` command as part of automation on GitHub Actions, like this:

https://github.com/bytescript/bytescript/pull/27/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R30-R31

```sh
                  npx playwright install --with-deps chromium firefox webkit msedge
                  npm test
```

**Test file (self-contained)**

n/a

**Steps**

- Run in macOS
- it will say that msedge is not a valid product.

**Expected**

msedge should be a valid produt to test against.

**Actual**

It says it doesn't exist, even after running `playwright install --with-deps`.

**Comment by trusktr** [comment]
I get `Invalid product: msedge` even in `windows-latest` of GitHub actions.

**Comment by dgozman** [comment]
Looking at the [stack trace here](https://github.com/bytescript/bytescript/actions/runs/5310143531/jobs/9611726634):

```
Error: Invalid product: msedge. Valid product types: chromium, firefox, webkit
    at playwrightLauncher (/Users/runner/work/bytescript/bytescript/node_modules/@web/test-runner-playwright/dist/index.js:37:15)
    at file:///Users/runner/work/bytescript/bytescript/web-test-runner.config.mjs:8:3
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)
```

It seems that you are using some third-party test runner (`@web/test-runner-playwright`) that throws this error. I guess you should file an issue against it.

**Comment by trusktr** [comment]
Ah, thanks. Opened issue over there: https://github.com/modernweb-dev/web/issues/2309
