### ISSUE TITLE
[Feature] please add cross env to a playwrightconfig.ts

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#23785]
it would be more helpful if we have a option to handle multiple environments in playwright configuration itself instead of using third party libs like cross-env, env.

Expected : 
in playwrightconfig.ts like base URL, provide a other options like below 

Base URL : test env 
Stage URL : stage env
Prod URL : produnction env

while running a script allow user to run a command along with url flag like below
npx playwright test testname prod - "this command will hit the prod env with the same script"

Note: though this we can achieve with the other libs it would be more helpful to the users while handling the multiple env's kind of a life hack.

**Comment by dgozman** [comment]
We recommend using `.env` files instead, [see this guide](https://playwright.dev/docs/test-parameterize#env-files).
