### ISSUE TITLE
[Feature] Projects level custom variables

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#23807]
Hello, I am in the process of migrating from a competing framework - and have run into a wall, something I could easily configure here is complicated and not clear.
I really miss the ability to configure variables on in the configuration file. 
Within project I would like to add some variables that I would like to use within a project/profile (in example customVar as a variable):

```
  projects: [
    {
      name: 'chrome-dev',
      use: { ...devices['Desktop Chrome'],    
      baseURL: ''},
      testMatch: '**/*.spec.ts',
      customVar: 'test'
    },
```

And after run it from spec files by:
```
test("test", async ({
    page, customVar
  }) => {
    console.log(customVar)
```

I noticed documentation about something familiar https://playwright.dev/docs/test-parameterize#parameterized-projects. But the approach itself does not suit me too much complicates the tests themselves.

**Comment by dgozman** [comment]
@OSnuszka The documentation page you've linked to explains exactly this situation. Unfortunately, you cannot make it easier than stated in the documentation:
- Declare your custom variable and it's type
- Specify value in the config
- Use variable in the test

If you have any specific questions, let us know.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
