### ISSUE TITLE
Storage State affects page created from browser.newContext() -> newContext.newPage()

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright#23816]
### Discussed in https://github.com/microsoft/playwright/discussions/23815

<div type='discussions-op-text'>

<sup>Originally posted by **AndyGleed** June 20, 2023</sup>
I now have Storage State saved and working so my admin user only ever logs in through the UI once using the log in form.

Now, using the admin user, I am creating a new user for my test.  Then using `browser` in my test fixture, I create a new browser context  and then open a new page from that browser context.

I then want to use that new page to log in as my new user.

The problem I am having is that my new browserContext and page are still under the influence of my  Storage State which stops my new user from logging in through the UI.  In fact, it loads straight into my app and is logged is as 'admin'.

Is there anyway I can get a new browserContext and page to be FULLY isolated so that it is not affected by the existing Storage State?</div>

**Comment by dgozman** [comment]
@AndyGleed Have you tried following [this section of the auth guide](https://playwright.dev/docs/auth#testing-multiple-roles-together)? Does that work for you? If not, why?

Alternatively, you can always ensure there is no storage state active when calling `newContext`:

```ts
const context = await browser.newContext({ storageState: undefined });
```

**Comment by AndyGleed** [comment]
@dgozman Thank you very much for your help, passing storageState: undefined worked as I wanted it to.

I had not seen that part of the documentation before so have book marked it.  I was following the setup/teardown and then tried to get it to work for my test setup.

All good now, thanks again :)

**Comment by AndyGleed** [comment]
@dgozman Thank you very much for your help, passing storageState: undefined worked as I wanted it to.

I had not seen that part of the documentation before so have book marked it.  I was following the setup/teardown and then tried to get it to work for my test setup.
