### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by gregherve** [microsoft/playwright#23811]
It would be extremely useful to have a way to store the content of the Web Table into a Java Object that could be used for baseline and comparison purposes.

If we could record the content of the Web Table in an excel type format with column and rows and save this as a baseline, use it to check for differences and highlight them.

Similar to what was implemented by IBM in the Rational Functional Tester tool, the validation points offers the capability to select 1 cell / 1 row / 1 column or the full table to test as baseline (expected) vs actual values.

The scope functionality is quite good but still means interacting/traversing the table.

Or perhaps something similar to the Visual Testing available in Node.js but for the Java Playwright?

Cheers.

**Comment by dgozman** [comment]
@gregherve Could you please be more specific? What is "Web Table"? Do you want to extract/expect some values from a table? I'd recommend to use[test generator](https://playwright.dev/java/docs/codegen-intro) to generate some locators and then use [`hasText`](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-text) or [`textContent`](https://playwright.dev/java/docs/api/class-locator#locator-text-content).

If you have more detailed suggestions in mind, please share.

**Comment by dgozman** [comment]
@gregherve Thank you for the info. I assume you are able to extract the data using the locators, which could be as easy as [`page.locator('table tr').allTextContents()`](https://playwright.dev/java/docs/api/class-locator#locator-all-text-contents).

Therefore, the question is mostly about storing the expectation and comparing it. Unfortunately, this is very much specific to your test runner, for example junit, so there's not much we can help with. Writing to a file and manually asserting that extracted text equals to file contents looks like the easiest way. In typescript we have our own test runner, so we can provide things like [`toMatchSnapshot()`](https://playwright.dev/docs/api/class-snapshotassertions#snapshot-assertions-to-match-snapshot-2). Unfortunately, situation in Java is different.

**Comment by dgozman** [comment]
Closing as per above.
