### ISSUE TITLE
want to manually install Firefox for playwright 1.34.0 can someone please provide the link

### ISSUE THREAD

**Issue by vishnuport** [microsoft/playwright#23821]
### System info
- Playwright Version: 1.34.0
- Operating System: windows 10
- Browser: firefox 113
- Other info:

please provide the link to manually install firefox113.0 for playwright automation 
the playwright version is 1.34.0

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
You can do `npx playwright install --dry-run` to get the download URLs/paths.

**Comment by aslushnikov** [comment]
@vishnuport once you downloaded the binary manually and extracted it to any location on your HDD, you can just point to the executable later on with the [`setExecutablePath`](https://playwright.dev/java/docs/next/api/class-browsertype#browser-type-launch-option-executable-path).

Hope this helps!
