### ISSUE TITLE
[BUG] npm init failure

### ISSUE THREAD

**Issue by FernandoRApud** [microsoft/playwright#23824]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Windows 10]
- Browser: [Chrome]
- Other info: Windows Terminal

**Steps**
- [Run npm init playwright]
- [Error]

**Expected**

Configuration to initialize Playwright

**Actual**

Error: 

npm ERR! code ENOLOCAL
npm ERR! Could not install from "Apud\AppData\Roaming\npm-cache\_npx\17028" as it does not contain a package.json file.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Fernando R. Apud\AppData\Roaming\npm-cache\_logs\2023-06-20T23_23_00_727Z-debug.log
La instalación de [ 'create-playwright@latest' ] fracasó con código 1

Log:
[2023-06-20T23_23_00_727Z-debug.log](https://github.com/microsoft/playwright/files/11808972/2023-06-20T23_23_00_727Z-debug.log)

**Comment by dgozman** [comment]
@FernandoRApud This looks like an npm failure, not sure what we can do. Please try again - perhaps it will succeed now?

**Comment by dgozman** [comment]
Closing as per above.
