### ISSUE TITLE
[Feature] Access Fixtures from test.step

### ISSUE THREAD

**Issue by bitwisebro** [microsoft/playwright#23829]
So I'm trying to use test.step with function. e.g. follwing:

```
async clickSignIn(stepDescription: string): Promise<void> {

        await test.step(stepDescription, async ({login}) => {

            await this.signInBtn.click();
            await login.verifyLogin();

        });
    }
```

my fixture file looks like:

```
import { test as base } from "@playwright/test";
import IndexPage from "../pages/index.page";
import ProductsPage from "../pages/products.page";
import LoginPage from "../pages/login.page";

type pages = {
    login: LoginPage;
    index: IndexPage;
    products: ProductsPage;
}

const pageObjects = base.extend<pages>({
    login: async ({ page }, use) => {
        await use(new LoginPage(page));
    },
    index: async ({ page }, use) => {
        await use(new IndexPage(page));
    },
    products: async ({ page }, use) => {
        await use(new ProductsPage(page));
    },
})
```

But login fixture is not available to test.step. It is available in test block! and the above mentioned code is placed in my page(component) class.

I came around a workaround by creating object of login page from the constructor:

```
import LoginPage from "./login.page";

export default class Account {
    readonly logoutLink: Locator = this.page.locator("//a[contains(@href,'logout')]");
    readonly accountLabel: Locator = this.page.locator(`//h1[text()='Account']`);
    
    readonly login:LoginPage;
    constructor(public page: Page) { 
        this.login = new LoginPage(this.page);
    }

```
But I think the accessing the existing fixtures via test.step will be much useful!

**Comment by dgozman** [comment]
@bitwisebro Thank you for the issue! This indeed would be helpful in some cases. Unfortunately, it is not possible, because Playwright has to know all the fixtures that will be used in the test before running it, and `test.step()` calls are only known during test execution. Your workaround is the way to go.

**Comment by gorpapyan** [comment]
Please add new functionality for using fixtures from test steps directly it will be beneficial
