### ISSUE TITLE
[BUG] TestInfo provides confusing / incorrect context in beforeAll block

### ISSUE THREAD

**Issue by jimcward** [microsoft/playwright#23833]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [Windows 10]
- Browser: [All]
- Other info: Testing APIs directly (non-UI testing)

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'main',
      testDir: './tests',
    },
});
```

**Test file (self-contained)**

```js
import { test } from '@playwright/test';

test.describe('My test block', async () => {

  test.beforeAll(async ({}, testInfo) => {
     console.log('beforeAll', testInfo.testId, testInfo.title, testInfo.line);
  });

  test('My actual test 1', async({}, testInfo) => {
     console.log('test1', testInfo.testId, testInfo.title, testInfo.line);
  });  

  test('My actual test 2', async({}, testInfo) => {
     console.log('test2', testInfo.testId, testInfo.title, testInfo.line);
  });  
});
```

**Steps**
- [Run the test]

**Expected**

I would expect there would be some way to distinguish between the testInfo presented in the beforeAll block and within the main test logic - I would like to inject testInfo into a fixture for logging that adds context so I can correlate them to the associated test or beforeAll block

**Actual**

Unfortunately the output makes it look like the first test is being executed first - the testInfo makes it look like the beforeAll execution is associated with test 1 - sample output:

```
  ✓  1 [main] › tests\example.spec.ts:9:7 › My test block › My actual test 1 (32ms)
beforeAll a30a6eba6312f6b87ea5-44f8c2a4b6070bd5bcba My actual test 1 9
test1 a30a6eba6312f6b87ea5-44f8c2a4b6070bd5bcba My actual test 1 9
  ✓  2 [main] › tests\example.spec.ts:13:7 › My test block › My actual test 2 (22ms)
test2 a30a6eba6312f6b87ea5-a60607f0bdb7c737928d My actual test 2 13
```

If a fixture is used and logged in the beforeAll block I would like to know that the context is that block rather than it seemingly like it is the execution of test1 which hasn't occurred yet. Is there any other way of getting at this kind of information if not from TestInfo? Thanks!

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
