### ISSUE TITLE
[BUG] Images in the trace file timeline are off center if the test is run in Playwright's Docker image using Safari

### ISSUE THREAD

**Issue by eatonjl** [microsoft/playwright#23839]
### System info
- Playwright Version: 1.35.1
- Operating System: Docker image
- Browser: WebKit
- Other info: Trace file issue

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Steps**
I can provide example code if needed, but I believe this occurs with any test. When tests are run using the WebKit project in the Playwright Docker image, the trace file's timeline images have issues. The image is pushed Doen and to the left so only the top right corner of the image is visible. Trace files created when tests are run locally are unaffected. This was reported on Playwright's Discord (images included) and it was suggested I make a bug report here. https://discord.com/channels/807756831384403968/1121081687716155412/1121081687716155412

**Expected**

Images in the trace file timeline should not be off center

**Actual**

Images in the trace file timeline are off center

**Comment by eatonjl** [comment]
@dgozman Is there a good way to attach files? I have only seen ways to attach links. The Discord link has screenshots.

**Comment by dgozman** [comment]
> @dgozman Is there a good way to attach files? I have only seen ways to attach links.

I think you can drag&drop a file into the reply box here on GitHub.

> The Discord link has screenshots.

Thanks, I can see them.

**Comment by eatonjl** [comment]
[trace.zip](https://github.com/microsoft/playwright/files/11834449/trace.zip)

**Comment by eatonjl** [comment]
I attached a file. Here are the screenshots. Thanks for the tip!
<img width="1728" alt="Screenshot 2023-06-21 at 10 09 49" src="https://github.com/microsoft/playwright/assets/37457599/3a106f66-dc56-4058-b8bd-6dcbd100c285">

**Comment by eatonjl** [comment]
On a side note, I also note that selecting the action line times on the left does not always successfully load the associated screenshot with it.

**Comment by mxschmitt** [comment]
I can see the broken snapshots in the trace. I was able to reproduce on GitHub Codespaces jammy container with our default example tests and tracing enabled. See here:

![image](https://github.com/microsoft/playwright/assets/17984549/6428a104-db6d-4882-b49b-cbe2e944e354)

No more action required from your side, thanks for reporting!

**Comment by eatonjl** [comment]
@yury-s Do you have any update on the status of this issue?

**Comment by yury-s** [comment]
I cannot reproduce it with latest playwright (1.37.1) but can with 1.36.1. Can you try your example with 1.37 and see if it still not working?

**Comment by eatonjl** [comment]
It does seem to be working now. Thank you!

**Comment by nbaldzhiev** [comment]
I am noticing this issue on `1.38.0` with the following metadata (as copied from the trace viewer):

```
BROWSER
engine: webkit
platform: linux
user agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Safari/605.1.15
```

![Screenshot 2023-09-21 at 17 36 59](https://github.com/microsoft/playwright/assets/19264892/ede71178-3c9d-4ab7-9d44-0afb884e1ed3)

I can't attach the trace as it contains sensitive info.

Is the team aware of this @yury-s @dgozman @mxschmitt ?
