### ISSUE TITLE
[Feature] Add size/contentLength to Download

### ISSUE THREAD

**Issue by hstanford** [microsoft/playwright#23832]
The Download object (https://playwright.dev/docs/api/class-download) is really useful - the ability to intercept a download in a headless browser and stream its data out is one of the key reasons I migrated from puppeteer.

One pain point is that the length of the expected data is not exposed, so currently any downloaded files need to be buffered in memory or saved to a temp file in order to get a Content-Length for downstream use, somewhat defeating the purpose of the streaming interface. I assume the Content-Length header is typically available on the network request that's being intercepted? It would be extremely useful to have this exposed in the Download interface. Thanks!

**Comment by dgozman** [comment]
@hstanford As of today, downloads are not streamed. Instead, browser downloads a file, writes it to disk, and then Playwright can `saveAs()` or `createReadStream()` for it. Although we should be able to expose the expected length, it would not be guaranteed to be the actual download length, and would not help with streaming.

See #2220 for a similar download streaming feature request.

**Comment by hstanford** [comment]
Thank you for responding so swiftly! I hadn't realised the file is always saved and createReadStream is called on the file from disk. If it's persisted to disk already, would the size not be accessible via fstat? I would expect that to be even more reliable than a content length header. Under what circumstances might that not be the actual download length?

**Comment by dgozman** [comment]
> Under what circumstances might that not be the actual download length?
> Edit: I suppose I can fstat it myself using the output of download.path()?

Yeah, that should work, and it would be 100% the file size. I was talking more about getting the size in advance for streaming, thus the confusion.

**Comment by hstanford** [comment]
Great, I'm happy with that solution. It'd be cool if someday the download event could hijack the network request and we could stream the data out directly, but that sounds like a significantly larger change! I appreciate the help 🙏
