### ISSUE TITLE
[Question] How to get status of your upstream patches?

### ISSUE THREAD

**Issue by denis-domanskii** [microsoft/playwright#2385]
Hi Playwright folks, I'm very impressed by your framework, but the only thing that concerns me - you Firefox and Safari patches. So could you please share your plans about merging this patches to upstreams? Maybe there is a place where everyone can track it (ticket, PR, forum thread?).

**Comment by pavelfeldman** [comment]
We don't have a process for that, so I created an md with the [WebKit patches](https://github.com/microsoft/playwright/blob/master/browser_patches/webkit/upstream_status.md). When we have enough patches in Firefox upstream, we will add a status page for it as well.
