### ISSUE TITLE
[Feature] After all tests are completed, run specific tests

### ISSUE THREAD

**Issue by Mortsadok10** [microsoft/playwright#23855]
Hi,
I have 10 spec.ts files that every test inside the spec is an independent test (they run in parallel).
I have 1 more spec.ts file that is a serial test.

As of now, I am running my tests with five workers.
Would it be possible for the Serial test to run after all of the parallel tests have been completed?

Thanks.

**Comment by tom2drum** [comment]
I believe you can split you tests into separate project and then use first one as a dependency for the second - https://playwright.dev/docs/test-projects#dependencies

**Comment by dgozman** [comment]
Merging into #16876.
