### ISSUE TITLE
Listen to DOM events and take a screenshot

### ISSUE THREAD

**Issue by AsjadMahmood** [microsoft/playwright#23862]
I was hoping that i can achieve this with page.evaluate because in the docs i read "page.evaluate() API can run a JavaScript function in the context of the web page and bring results back to the Playwright environment".
Below is my attempt which gives "TypeError: listener is not a function"

`const listener =  await page.evaluate(()=>{
        return document.body.addEventListener;
});

listener('click',()=>{
    //here i plan to call page.screenshot method
})`

Any idea if i am doing wrong or how to achieve this ?

**Comment by dgozman** [comment]
@AsjadMahmood You cannot pass functions between the page and the test, see [this guide](https://playwright.dev/docs/evaluating).

You can [expose a function](https://playwright.dev/docs/api/class-page#page-expose-function) that will be called in the test, and register a listener in the page that calls it.

```ts
// Expose a function that will be called from the page.
await page.exposeFunction('screenshotMe', async () => {
  // take a screenshot
});

// Setup a listener that notifies the test.
await page.evaluate(() => {
  document.body.addEventListener('click', () => window.screenshotMe());
});
```

Let me know whether this helps.

**Comment by Hienphamthe** [comment]
> @AsjadMahmood You cannot pass functions between the page and the test, see [this guide](https://playwright.dev/docs/evaluating).
> 
> You can [expose a function](https://playwright.dev/docs/api/class-page#page-expose-function) that will be called in the test, and register a listener in the page that calls it.
> 
> ```ts
> // Expose a function that will be called from the page.
> await page.exposeFunction('screenshotMe', async () => {
>   // take a screenshot
> });
> 
> // Setup a listener that notifies the test.
> await page.evaluate(() => {
>   document.body.addEventListener('click', () => window.screenshotMe());
> });
> ```
> 
> Let me know whether this helps.

this solution works for me, thank you so much
