### ISSUE TITLE
Real mobile devices support

### ISSUE THREAD

**Issue by Redinbox** [microsoft/playwright#23869]
Hello,

After I did explore on framework I found playwright one of the best fit for UI test automation.
my requirement is like wanted to covet test automation on desktop browser[real browsers] , mobile browsers ,mobile app on android and iOS, is there any support for this requirement ?
I know it support browser level emulation only. if I missed please help me.

**Comment by ltsuda** [comment]
Please, see the links in this comment

https://github.com/microsoft/playwright/discussions/23848#discussioncomment-6247829

**Comment by dgozman** [comment]
Duplicate of #1122.
