### ISSUE TITLE
[BUG] Microsoft Business Central ends up in loop after authentication - working for 2,5 years but not after update to version 22.X of Business Central

### ISSUE THREAD

**Issue by PoulLindorf** [microsoft/playwright#23861]
Hi,

We have had a setup using Playwright that accesses Business central for more than 2 years running smoothly. 4 different processes running several time a day and each proces runs +45 times.

Since update to version 22.X of Business central the process stalls just after business central has logged in (can see login in the AD).
Business central is stalled at 'Getting Ready...' seems to go into loop. We await next step and have tried to expand the wait significantly but Business central never continues.

Have tried Microsoft business central support but without luck - they say that this is not supported by them. Tech guy helping me has been really helpful but think he was 'closed down' as the Business Central Group does not see it as being their issue.....no changes til Business Central will happen to mitigate around this.

We have tried many things - and we have different documentation and can also create further documentation if it can help.

We have a Business Central version 21 running and the process runs successfully as they have done for over 2 years - related to this we have Playwright trace files and HAR files

We have a Business Central version 22.X running and the process stalls every time and we have tried hundreds of times - related to this we have Playwright trace files and HAR files also

Have tried both of the above with a dedicated VPN also - no difference.

Is there anybody out there who could help us in any way??
Does anybody know how to interpretate the files?
This has been down since 4. June now so if anybody knows anything that they believe could help we would really appreciate!

### System info
- Playwright Version: [v1.XX] - latest
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, **Chromium**, Firefox, WebKit]
- Other info: Executing using PlayWright

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by dgozman** [comment]
@PoulLindorf If you could share your scripts so that we can run them locally, we might be able to take a look. Otherwise, not sure how to help you.

**Comment by PoulLindorf** [comment]
> @PoulLindorf If you could share your scripts so that we can run them locally, we might be able to take a look. Otherwise, not sure how to help you.

HI @dgozman I understand what you are asking.
 But the issue is that we have taken the code and placed in locally on our PC to execute it and let it run like it does on our existing placement and there Business Central acts differently and continue in the process.......
 
 It is only when we have it running on/from firebase that the v22.X stalls and the v21.X works.

As i write I have different logs and traces I can share if anybody thinks it can give som guidance. I can also share the code for it to run locally but not sure it will give anything as it is when it is run from were it hase been running on firebase the last year that it simply stalls.

Only thing I can think about is that in the new version of Business Central they have input something that if it comes from the existing placement TYPE it will stop

**Comment by dgozman** [comment]
@PoulLindorf Well, attach the traces/logs here, and we can try looking at it.

**Comment by mxschmitt** [comment]
Closing as part of the triage process since it seemed stale or did not get enough upvotes in the past. Please create a new issue with a detailed reproducible or feature request if you still face issues.
