### ISSUE TITLE
[BUG] webkit with proxies not working on Windows

### ISSUE THREAD

**Issue by Archish27** [microsoft/playwright#23874]
With playwright-webkit with proxy on Windows 10, 11 URL is not opening causing `Unable to connect the host`. The same is working on macOS. Past reference issues - #23617 #21954 

### System info
- Playwright Version: v1.30.0 v1.31.1
- Operating System: Windows 10, Windows 11
- Browser: Webkit
- Other info: [BrowserMob Proxy 2.1.4](https://github.com/lightbody/browsermob-proxy/releases/tag/browsermob-proxy-2.1.4)

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Scripts**

**server.js**
```js
'use strict';
const { webkit } = require('playwright');
(async () => {
  const browserServer = await webkit.launchServer({
    args: ['--ignore-certificate-errors'],
    proxy: {
      server: "http://127.0.0.1:8081"
    },
    headless: false,
    ignoreHTTPSErrors: true,
    logger: {
      isEnabled: () => true,
      log: (name, severity, message, args) => console.log(`${name} ${message}`),
    },
  });
  const wsEndpoint = browserServer.wsEndpoint();
  console.log(wsEndpoint);
})();

```
client.js
```js
const { webkit } = require('playwright');

(async () => {
  const browser = await webkit.connect({
    wsEndpoint: `wss://<url>`,
  });
  const page = await browser.newPage();
  await page.goto('https://www.google.com');
  await browser.close();
})();
```

**Steps**
- Download the [BrowserMob Proxy](https://github.com/lightbody/browsermob-proxy/releases/download/browsermob-proxy-2.1.4/browsermob-proxy-2.1.4-bin.zip)
- Run BrowserMob Proxy - `browsermob-proxy.bat`
- Create a Proxy `curl -X POST http://localhost:8080/proxy`
- Create a HAR Request `curl -X PUT http://localhost:8080/proxy/8081/har`
- Run playwright server `node server.js`
- Copy the URL from the console & paste into the client script in wsEndpoint.
- Run the client script - `node client.js` 

**Expected**

URL should open.

**Actual**

`Unable to connect the host`

**Comment by aslushnikov** [comment]
@Archish27 could you please try with Playwright 1.35.1? Does it still repro?

**Comment by Archish27** [comment]
@aslushnikov With `1.35.1` works. Above specified version doesn't seem to work with proxy in between.

**Comment by aslushnikov** [comment]
Sweet. We don't backport these kind of changes though, so please update to the newest version!
