### ISSUE TITLE
[Question]: waiting for element to be visible, enabled and stable

### ISSUE THREAD

**Issue by yangislet** [microsoft/playwright#23886]
### Your question

The element of the web page is clearly visible, but the playwright prompt waits for the element to be visible, enabled and stable. this problem confuse me. the same issue is [https://stackoverflow.com/questions/66854247/click-on-a-link-is-not-working-in-playwright](url)

my trouble is that:  i try to check the checkbox in element-ui table , however playwright always show the element is not visible.
i don't know how to deal with this trouble, event i add the sleep() to wait dom, it not work. my code in sync mode  like this:

```
        self.print_node(table)
        for item in index:
            self.sleep(0.2)
            checkbox = table.locator(f"tbody tr:nth-child({item}) td:first-child input")
            checkbox.wait_for(timeout=10)
            if not checkbox.is_checked():
                checkbox.check()
```

**Comment by aslushnikov** [comment]
@yangislet I'll have to close this since there's no repro and the discussion has stalled; please feel free to re-file with a repro!
