### ISSUE TITLE
[BUG] Slow execution speed M2 Pro CPU when using Chrome with `channel: 'chrome'`

### ISSUE THREAD

**Issue by CoreyGahafer** [microsoft/playwright#23881]
### System info
- Playwright Version: [v1.35.1]
- Operating System: macOS 13.4
- Browser: Chrome
- Other info: Macbook Pro w/ Apple M2 Pro CPU

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'Chrome',
      use: {
        ...devices['Desktop Chrome'],
        channel: 'chrome',
      },
    },
});
```

**Test file (self-contained)**

```js
import { expect, test } from '@playwright/test';

test('should visit google and search playwright', async ({ page }) => {
  await page.goto('https://www.google.com');
  await page.getByRole('combobox', { name: 'Search' }).fill('playwright');
  await page.getByRole('combobox', { name: 'Search' }).press('Enter');
  await expect(
    page.getByRole('link', {
      name: 'Playwright: Fast and reliable end-to-end testing for modern ... Playwright https://playwright.dev',
    })
  ).toBeVisible();
});
```

**Steps**
- `npx playwright test path/to/spec`
- Comment out `channel: 'chrome'`
- `npx playwright test path/to/spec`

**Expected**

Test should run nearly as fast regardless of the channel being set to `chrome` or not.

**Actual**

Tests run significantly slower when using `channel: 'chrome'` than not.

- **Channel: chrome**: [Chrome] › test.spec.ts:3:5 › should visit google and search playwright (14.9s)
- **Channel commented out:** [Chrome] › test.spec.ts:3:5 › should visit google and search playwright (3.7s)

**Comment by dgozman** [comment]
@CoreyGahafer Most likely, that's Rosetta kicking in. See [this comment](https://github.com/microsoft/playwright/issues/23099#issuecomment-1557580235) for more details. Let me know whether that helps.

**Comment by CoreyGahafer** [comment]
@dgozman this looks to have been the issue and does look to have resolved it from the command line, thank you! I am still seeing the original slowness with the VSCode extension though. Is there a way to check what version it's using?

**Comment by CoreyGahafer** [comment]
@dgozman After looking into the node processes that VSCode was leveraging, it looks like it was using a version that was x86. I've fixed this and everything is running as expected now. Thank you very much for pointing me to this so that I could resolve my issue!
