### ISSUE TITLE
[BUG] Show trace viewer in v1.35 is not showing live trace

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#23885]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [ Windows 11]
- Browser: [Chromium]
- Other info:

**Steps**
- [Tick Show trace viewer]
- [Check the trace viewer]
- [Click run the test] (the green button)

**Expected**

It should show step by step of actions in test file while running just like UI Mode

**Actual**

Show trace viewer but tell me "Select test to see the trace" while running. After finish the test, the results finally appear.
![image](https://github.com/microsoft/playwright/assets/71114633/7c959d85-a966-412b-b7d7-28801d22a33b)

**Comment by mxschmitt** [comment]
I tried to reproduce but was unfortunately not able to. Could you check the console errors of the trace viewer, if there are any? You can do this by doing a right click in the window, Inspect and then under the Console tab.
