### ISSUE TITLE
[Feature]Cloudflare Turnstile Bypass

### ISSUE THREAD

**Issue by zone559** [microsoft/playwright#23884]
I am looking for a feature request for Playwright that would allow it to bypass Cloudflare Turnstile (https://www.cloudflare.com/products/turnstile/). Currently, Selenium has a Python package that can bypass it, and I am hoping that Playwright will also provide a similar option for both Firefox and Chrome.

Cloudflare Turnstile is used to prevent bot detection, and one existing solution for bypassing it is the "undetected-chromedriver" package (https://github.com/ultrafunkamsterdam/undetected-chromedriver). It would be beneficial if Playwright could incorporate a similar mechanism to overcome this obstacle.

**Comment by mxschmitt** [comment]
Playwright is an end-to-end testing framework, where we expect you test on your own environments. Bypassing any form of bot protection is not something we can act on. Thanks for your understanding.
