### ISSUE TITLE
[Feature] Non-incognito run option

### ISSUE THREAD

**Issue by naluconcepcion** [microsoft/playwright#23894]
Hello! I'm interested in using Playwright to test an application which has MFA enabled for an Azure AD application. However, my application requires that I am also authenticated to my Edge profile in order to obtain a token, which thus means that I would like to run Playwright without using InPrivate mode. I understand that the idea of Playwright is that every incognito session is meant to support a clean "end-to-end" test scenario, but it would be extremely helpful to be able to toggle between private and non-private sessions as appropriate. 

I have been following the support ticket [#11833](https://github.com/microsoft/playwright/issues/11833), and it seems that this functionality is (still?) not yet directly supported. First: thank you to the Playwright team for all you've already done! And secondly, I'd love some support on addressing my scenario if possible. :) This is an awesome library, and I look forward to seeing what else the tool and the team are capable of achieving!

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11833 and assigned it to the next release.
