### ISSUE TITLE
[BUG]set maximised did not function over Python

### ISSUE THREAD

**Issue by KobyD1** [microsoft/playwright#23892]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [Ubuntu 20]
- Browser: [ Chromium]
- Other info:

- Hi 
I am trying to work at maximized mode  according to the following example- it did not function 
in addition, I am looking for  set browser size solution 

Thanks 
Koby 
### Source code
       browser = playwright.chromium.launch(headless=is_headless,args=["--start-maximised"])
        page = browser.new_page(no_viewport=True)

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
If you want to maximise, you can do the following, be aware that this only works in Chromium:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(args=["--start-maximized"], headless=False)
    context = browser.new_context(no_viewport=True)
    page = context.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```

For setting a fixed viewport size, do the following:

```py
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context(viewport={"width": 100, "height": 100})
    page = context.new_page()
    page.goto("http://playwright.dev")
    print(page.title())
    browser.close()
```
