### ISSUE TITLE
[Feature] Providing `id` for `TestStep` and `Suite`

### ISSUE THREAD

**Issue by Bam6ycha** [microsoft/playwright#23891]
Good day.
I am developing and maintaining a custom reporter that is used by a large number of our clients.
And I ran into the following problem.
While processing suites, steps, we need to have a unique identifier for these entities for their correct processing. Now, we use what the `titlePath()` method returns, and based on that we generate these unique identifiers. But, this approach has a number of disadvantages. If the parent and child have the same titles, we have a name collision problem. We tried to find some other, more reliable way to solve this problem, but all solutions are not guaranteed to work in 100% of cases.
Is it possible to add `id` to `TestStep` and `Suite` so that each entity can be easily identified?

**Comment by mxschmitt** [comment]
What we do internally is suite.titlePath().join('\x1e') and for steps we internally just count. Would that work for you?

We also expose a re-usable [test.id](https://playwright.dev/docs/api/class-testcase#test-case-id) inside the reporter.

**Comment by Bam6ycha** [comment]
@mxschmitt Thanks for your reply.
Looks like we can not just count steps.
Because, how we can distinguish one step from another in a case when both of them have the same `titlePath`, f.e. they have the same `step.parent` and `title`?
In our reporter, we start step in `onStepBegin` and save information about it to our store, and in `onStepEnd` we finish step.
To save and get information from the store, we generate unique identifiers for every step, to have the ability to get access to this information f.e. in `onStepBegin`

**Comment by pavelfeldman** [comment]
I'll close this as won't fix. If steps have the same title, we consider them indistinguishable.
