### ISSUE TITLE
[BUG] Missing dot in default playwright.config.ts created by Install Playwright 

### ISSUE THREAD

**Issue by gemiusz** [microsoft/playwright#23908]
Context:

Playwright Version: 1.35.1
Operating System: Windows
Node.js version: 20.3.0
Visual Studio Code version: 1.79.2
Playwright for VSCode extension version: 1.0.13
Browser: Installed only Chrome
Extra: Not downloaded/installed other browsers

**Code Snippet**

```TypeScript
  /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
    // },
```

**Describe the bug**

When install playwright by Extension
![image](https://github.com/microsoft/playwright/assets/30750006/6c232bae-87e5-4d47-8ee0-2598d643f9a9)

 is created `playwright.config.ts` but have missing "." (dot) at  line 71:
 ```TypeScript
     //   use: { ..devices['Desktop Chrome'], channel: 'chrome' },
 ```

should be:

 ```TypeScript
     //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
 ```

**Comment by mxschmitt** [comment]
See https://github.com/microsoft/create-playwright/releases/tag/v1.17.128 which should be live soon.
