### ISSUE TITLE
Allow toHaveText to accept multiple strings [Feature]

### ISSUE THREAD

**Issue by sydlynnmiller** [microsoft/playwright#23901]
For example something like:
`await expect(locator.toHaveText('Active' || 'Inactive');`

**Comment by mxschmitt** [comment]
You can pass a regex, would that work for you?

```ts
const locator = page.locator('.title');
await expect(locator).toHaveText(/(Active|Inactive)/);
```

See here: https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-text

**Comment by aslushnikov** [comment]
Closing as per above answer!
