### ISSUE TITLE
[Feature] Adding iPad Pro (5 gen) device descriptor 

### ISSUE THREAD

**Issue by martamedovova-ext91522** [microsoft/playwright#23915]
Hello, would be possible to add to the deviceDescriptorsSource the device iPad Pro (5 gen)
Is it too old for adding?

Thank you.

MM

**Comment by mxschmitt** [comment]
If you are interested in adding it, we would be open for receiving a contribution for [it](https://en.wikipedia.org/wiki/IPad_Pro_(5th_generation)). The source file for it is [packages/playwright-core/src/server/deviceDescriptorsSource.json](https://github.com/microsoft/playwright/blob/2808f3700ac946c59d3fb954b3ceb5640c5a71ed/packages/playwright-core/src/server/deviceDescriptorsSource.json#L200-L210).

As you can see, a device has not a lot of properties. So you can specify the options also directly inside your playwright.config's use section.

**Comment by martamedovova-ext91522** [comment]
Ok. How do you wish to me to contribute?
Via new branch (made it from which one, please - just in case) and pull request to you?

**Comment by mxschmitt** [comment]
Yes, creating a fork, creating a new branch from the main branch, and creating a PR. See [here](https://docs.github.com/en/get-started/quickstart/contributing-to-projects).

**Comment by mastrzyz** [comment]
@martamedovova-ext91522  added this in the PR ^ https://github.com/microsoft/playwright/pull/24355

**Comment by martamedovova-ext91522** [comment]
Hello, thank you for adding the iPad Pro 5! :-)
I was going to try to add by myself but did not manage because of time. I do apologize for this.
