### ISSUE TITLE
[Feature] Unable to connect to a server when running in loop.

### ISSUE THREAD

**Issue by as2r9** [microsoft/playwright#23918]
Getting the Error: page.goto: net::ERR_TUNNEL_CONNECTION_FAILED
This is happening when i try to run the code in a loop for multiple credentials. The code i wrote gets connected to a proxy and then works. When the loop is run for the first time the output is as required but as it proceeds to the next iteration i face this issue.

**Comment by mxschmitt** [comment]
This issue isn't following our bug template and does not contain any reproduction steps, so I unfortunately have to close it. We can only act on bug reports with clear reproduction steps. Thanks for your understanding.

Feel free to re-file with more details.
