### ISSUE TITLE
[REGRESSION]: Component testing unstable (not waiting to be rendered and stable)

### ISSUE THREAD

**Issue by hklsiteimprove** [microsoft/playwright#23927]
**Context:**
- GOOD Playwright Version: 1.34.3
- BAD Playwright Version: 1.35.x
- Operating System: Linux

**Describe the bug**
There seem to be a regression in how `mount` waits for the render to be stable, all browsers.
We have been running a lot of component tests using a react stack. Its been pretty stable.
It seems like updating past 1.34.x caused some form of regression in when the promise resolves from the `mount` function in the tests.
Since the upgrade we have experienced a lot of flakyness in our tests. Eventually forcing us to downgrade to 1.34.3, which is fully stable.

Its hard to provide a repro, as its mainly flakyness, which should have shown up in playwrights own component test CI pipeline.

Hope this is enough information to go of, otherwise feel free to reach out.

**Comment by mxschmitt** [comment]
What is the error you are getting? Usually clicks, assertions etc. are waiting for the element to have a certain state and they retry.

Having a reproduction and clear error logs would help a lot, thanks!

I went over the commit range but didn't find something obvious. https://github.com/microsoft/playwright/compare/v1.34.0...v1.35.0
cc @sand4rt

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem. Could you help us with that?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
