### ISSUE TITLE
[Feature] Print elements selectors in Playwright logs

### ISSUE THREAD

**Issue by prisma-new-user** [microsoft/playwright#23938]
I'm writing all playwright logs using logger sink as described [here](https://playwright.dev/docs/api/class-logger?_highlight=log#loggerisenabledname-severity) into a log file. Went something went wrong in the test, like clicking on element that is not visible, all I see in playwright logs is `api info <= page.click failed`.Is it possible to print also on which element we tried to click?
Is it possible to print the selector as well?
I know that I can see it on the exception that printed to the terminal but I need it to be also on the log file.
OR  maybe is it possible somehow to take the logs from the terminal and copy them to my log file?

**Comment by mxschmitt** [comment]
The Logger sink is actually not something we recommend for debugging tests. Its still there from the early days. Nowadays we strongly recommend [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro), which gives you all these information, including DOM snapshots, action steps, logs per action, networking information, console logs, time travel debugging etc. out of the box. 

Would that work for you?

**Comment by prisma-new-user** [comment]
I'm familiar with the trace viewer but it won't help me.
My use case: I run 30 tests hourly via Jenkins job and send Slack notification to a dedicated Slack channel when tests failed.
As part of the Slack message I want to attach the reason for the failure, something like: "Text X fail: Failed to click on Y button"
In order to achieve that I need somehow to write to a log file what exactly was the reason for the failure (unable to click, expect failed, etc.).
Once I'll have a log file with the error it will be easy for me to send it to my Slack channel.

I'll really appreciate any help/advice

**Comment by prisma-new-user** [comment]
Thanks a lot I'll check it out.
I'm using Winston for my reports.
