### ISSUE TITLE
[Feature] Custom messages when running in UI mode

### ISSUE THREAD

**Issue by Voltgit** [microsoft/playwright#23939]
Our setup:
Front -> Proxy -> Back
To mock requests properly, we can't use Playwright tools for mocking.
We are using [MSW](https://mswjs.io/) which work just fine.
But there is one problem, it's hard to report detected unmocked requests in to the test.
To solve this, we sent messages through:
`testInfo.annotations.push( { 
type: '❌ Found unhandled request'} ,
description: 'some request',
)`
But this doesn't work in UI mode.

Can we have custom messages in Actions tab when using UI mode?
<img width="418" alt="image" src="https://github.com/microsoft/playwright/assets/62586883/0196347b-9f27-46a1-bcac-4866610c0395">

**Comment by mxschmitt** [comment]
> To mock requests properly, we can't use Playwright tools for mocking. 

Why is this the case? Are you testing an application with server rendered components which does data fetching in the backend? (we are currently reworking our network mocking docs and any limitations / user scenarios are super helpful there to know and might make sense to surface)

As of today you can add [custom steps](https://playwright.dev/docs/api/class-test#test-step) which then get surfaced in the trace viewer by using a test step:

```
  await test.step('set cookies', async () => {);
```
<img width="251" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/a243bc81-8cf8-4bce-b1bd-cafe03442d36">

```ts
  await test.step('set cookies', async () => {
    expect.soft(true, 'abc').toBeFalsy();
  });
```

You can add a fake soft assertion which fails inside then its also red: 

<img width="135" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/7f71eb26-3b3a-4a4c-b8a6-f48cbb154d6a">

or a normal expect which then fails the test immediately.

Would that work for you?

**Comment by Voltgit** [comment]
> Would that work for you?

I need to check request handling for every test and do it asynchronously.
We can't just add test.step to afterEach. It won't work when test fails (probably because of unhandled request).

The case:
>start

>browser starts render some components

>browser sends some requests

>one of the requests fails

>that causes incorrect render of the component

>test fails

>afterEach dosen't do anything (or just UI mode no longer watches for new changes)

What would be nice:

>tests start

>>Mock server starts
(and has async access to the Actions stream)

>browser starts render some components

>browser sends some requests

>>found some unhandled request

>>Actions.push('some message')

>test fails

>We have useful logs in the UI mode :)

----

>Why is this the case? Are you testing an application with server rendered components which does data fetching in the backend?

I will be back with feedback on this soon. I think we have a bunch of user scenarios that we would like to share with you :D

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
