### ISSUE TITLE
[Feature] Setup default timeout to expect.toPass assertion

### ISSUE THREAD

**Issue by danielsobon** [microsoft/playwright#23937]
Hey, is it possible to setup default timeout for expect.toPass assertions?
In case of usage `expect.toPass` without defining timeout in assertion the step will wait till the test timeout is exceed.

```
test('Expect toPass @desktop', async () => {
    await expect(() => {
      expect(1).toBe(2);
    }).toPass();
  });
``` 

Can we use here default expect config value?
`config = { expect: { timeout: 10000 } }`
Or add the new parameter into PlaywrightTestConfig

**Comment by mxschmitt** [comment]
> Can we use here default expect config value?

This was intentionally made, we can add a new parameter to `toPass: { timeout?: number }` to the config and expect.configure as part of this feature request.

**Comment by danielsobon** [comment]
looks great, thx @mxschmitt

**Comment by gskierk** [comment]
It's super confusing right now to me... It's natural to think that the default expect timeout should be applied to all its features until the specific timeout is passed directly to the assertion.

**Comment by AdamOakman** [comment]
@mxschmitt I also got confused when I first found out that expect.toPass does not respect default expect timeout set in config - there are many expect.toPass assertions in our project and it would be good to be able to set the default timeout once

**Comment by injae-kim** [comment]
> there are many expect.toPass assertions in our project and it would be good to be able to set the default timeout once

Hi @mxschmitt! as you can check on above comment by @AdamOakman , I also need some way to set timeout on overall `expect.toPass()` on my project.

@dev-jonghoonpark made awesome PR #28231 to solve this problem. can you review this PR? thanks! 🙇

**Comment by uiii** [comment]
Is there at least a way how to access the default expect timeout from config? I am using `toPass` inside custom matcher and it is really confusing that this matcher doesn't respect default timeout.

**Comment by injae-kim** [comment]
> - I also got confused when I first found out that expect.toPass does not respect default expect timeout,
> - it is really confusing that this matcher doesn't respect default timeout.

For @uiii and who that confusing about `expect.toPass's` default timeout doesn't respect `expect's` timeout (I also got confused at first but now understand it)

> https://playwright.dev/docs/test-assertions#expecttopass

```
You can retry blocks of code until they are passing successfully.

await expect(async () => {
  const response = await page.request.get('https://api.example.com');
  expect(response.status()).toBe(200);
}).toPass();
```
As you can see on above `toPass doc`, toPass basically **retry N times until expect are passing successfully.**

So If `toPass` use same default timeout with expect, it can't retry! cause toPass is timeout right after expect is timeout.
- e.g. If expect timeout is `100ms` and toPass timeout is `100ms`, toPass can't retry
- e.g. If expect timeout is `100ms` and toPass timeout is `500ms`, toPass can retry 4 times

> https://github.com/microsoft/playwright/blob/main/packages/playwright/src/matchers/matchers.ts#L370

```
export async function toPass(
  this: ExpectMatcherContext,
  callback: () => any,
  options: {
    intervals?: number[];
    timeout?: number,
  } = {},
) {
  // here! toPass default timeout is 0 (it respect test timeout)
  const timeout = options.timeout !== undefined ? options.timeout : 0;
```

So as you can check on above code, `toPass` uses default timeout as `0`, not uses expect's timeout (it means toPass retry until this test is timeout)

And by PR https://github.com/microsoft/playwright/pull/28231, you can manually set some default timeout on toPass~!

After checking this, I think maybe it's better to add this description on doc#toPass#timeout 🤔
(it's easily confuse about this cause there's not enough description about toPass#timeout)

**Comment by uiii** [comment]
Hi @injae-kim

> So If `toPass` use same default timeout with expect, it can't retry! cause toPass is timeout right after expect is timeout.

This is not fully true, it depends what type of `expect` assertions you use. There are two types, [auto-retrying](https://playwright.dev/docs/test-assertions#auto-retrying-assertions) and [non-retrying](https://playwright.dev/docs/test-assertions#non-retrying-assertions). 

As you wrote that `toPass` basically retry N times until expect are passing successfully, it is the same behaviour for all the *auto-retrying* assertions. Additionally `toPass` has `intervals` option to delay following retries. 

So if you use auto-retrying assertions in `toPass` it might be a problem if the timeout is the same, but it is not the case of the example you provided. 

The reason why I use `toPass` is to create custom matcher combining multiple assertions and behaving like auto-retrying assertions. It checks if the table has the expected values:

```ts
export async function toHaveTableData(locator: Locator, expected: string[][], options?: { timeout?: number }) {
	try {
		await expect(async () => {
			const rows = locator.locator("> tbody > tr");
			const rowCount = await rows.count();

			expect(rowCount, "Table has unexpected number of rows").toBe(expected.length);

			for (let i = 0; i < rowCount; ++i) {
				const rowData = await rows.nth(i).locator("> td").allInnerTexts();
				expect(rowData, `Row number ${i + 1} has unexpected data`).toEqual(expected[i]);
			}
		}).toPass(options);

		return {
			message: () => "Tables data are equal",
			pass: true
		};
	} catch (e) {
		return {
			...e.matcherResult,
			message: () => e.matcherResult.message,
		};
	}
}
```

So if someone use it is really confusing as it uses different timeout:

```ts
const table = page.getByTestId("table");

await expect(table).toBeVisible(); // <--- this uses default expect timeout (5s)
await expect(table).toHaveTableData(tableData /* string[][] */); // <---- this uses test timeout by default (60s)
```

--------

So I'd like to configure the `toPass` in my matcher to use the default expect timeout. How, should I get it from `playwright.config.ts` directly?

Or, is there another way how to combine multiple expects in a custom matcher? Using auto-retrying assertions there, is even more problematic as they should share one timeout (passed to custom matcher), but there is no obvious way how to split it among multiple assertions.

**Comment by uiii** [comment]
@injae-kim Unfortunately `currentExpectTimeout` is either not exported or is not included in Typescript typings.

**Comment by injae-kim** [comment]
@uiii aha 😢 then I think we should use expect timeout directly on `playwright.config.ts`.

Hmm.. is it worth to export `currentExpectTimeout()`? waiting maintainers answer~

**Comment by uiii** [comment]
> then I think we should use expect timeout directly on `playwright.config.ts`.

Yeah, I did this as a workaround.
