### ISSUE TITLE
toBeInViewport() method doesn't work for running on Iphone 12 emulator

### ISSUE THREAD

**Issue by lampie1973** [microsoft/playwright#23944]
### System info
- Playwright Version: 1.35.1
- Operating System: Windows 11
- Browser: Iphone 12 emulator (which seems to be Webkit)
- Other info:

### Description
I have some code that clicks on a menu item. On that moment a new tab is opened and I want to verify if a certain text is showing in the viewport. On a normal browser this works fine but when I select my project 'Iphone 12' it always fails with the error: Error: expect.toBeInViewport: Browser has been closed.

The funny thing is that after the first click 2 windows are open but on both windows I get this error. 
Another strange thing is that I can click on items on the page so the browser is correct, open and can be interacted with. So this seems to be a bug within this method.

The code (not sure if it helps)

    await page.getByRole('button', { name: 'Meer' }).click();
    const page1Promise = page.waitForEvent('popup');
    await page.getByTestId('action-panel-faq-btn').click(); // this click opens the new tab
    const page1 = await page1Promise;
    await page1.getByRole('heading', { name: 'FAQ }).click();
    expect(page1.getByRole('heading', { name: 'FAQ' })).toBeInViewport();

**Comment by mxschmitt** [comment]
You need to await the statement:
```
await expect(page1.getByRole('heading', { name: 'FAQ' })).toBeInViewport();
```

**Comment by lampie1973** [comment]
Thanks, that was indeed the problem!  Stupid that I didn't see that myself but I got confused because this actually does run fine for all other browsers.
