### ISSUE TITLE
how to do visual regression testing between two envrionment which is hosted in cloud

### ISSUE THREAD

**Issue by saravananpb** [microsoft/playwright#23948]
I heard that there is a option in playwright we can do visual regression testing by screenshot, I am just checking Is there any possibility to do the visual regression testing by comparing two website which are hosted in cloud.

Basically I want to run the regression test between two envrionment UAT and Production which need to compare Page layout, text drop down option, checkbox, textbox, position,tooltip againts the other environment.

my page structure is similar to https://playwright.dev/docs/running-tests will have left navigation with list of different section and right side, it will open up the respective content and responsive question.

Is it possible to compare two different envrionment page layout and all other stuff using playwright on the cloud?

suggest if you have any other option

**Comment by mxschmitt** [comment]
There is no out of the box solution, but you could create it easily yourself. It would work like that:

- Generate a list of all the pages you want to compare, this works most likely by looking at the sidebar.
- For each of the pages make a screenshot and then navigate to the other website with the same path and make another screenshot
- Then you can call toMatchSnapshot to compare the images: https://playwright.dev/docs/api/class-snapshotassertions#snapshot-assertions-to-match-snapshot-1

To organise it well with the Playwright test-runner, you could fetch all the URLs inside a globalSetup hoook, store it in a local json file and then load this JSON file inside your test so you can create a test case [for each of your](https://playwright.dev/docs/test-parameterize) pages.

**Comment by saravananpb** [comment]
Hi mxschmitt,

thanks for the answer, It will be helpful for initial start, do we have any capabilities in playwrite which is take screenshot of all the text fields, drop down answers, some questions are displaying based on the previous questions selection, so i need to take screen shot of each of the scenario which is somewhat time taking task for us. there are lot of logical scenario which will drive many questions,helptext, tooltip etc... 

do you have any idea how to acheive this without taking screenshot of each scenario?

Thanks
Saravanan

**Comment by aslushnikov** [comment]
> do you have any idea how to acheive this without taking screenshot of each scenario?

There's nothing this specific in Playwright API to address this; you can use the [`locator.screenshot()`](https://playwright.dev/docs/api/class-locator#locator-screenshot) to take screenshots of individual elements though.

**Comment by RicardoRien** [comment]
Hey @saravananpb I'm looking for the same thing as you. Let me know if you find a way to do it. Thanks in advance.
