### ISSUE TITLE
[BUG] Webkit: Using PrimeVue with localised messages causes Webkit tests to fail

### ISSUE THREAD

**Issue by VeronikaHillebrand** [microsoft/playwright#23943]
### System info
- Playwright Version: [v1.35]
- Operating System: [All]
- Browser: [WebKit]
- Other info:

### Source code

**Link to the GitHub repository with the repro**

https://github.com/VeronikaHillebrand/bug-report-playwright-webkit

As you can see, Chromium and Firefox tests pass, Webkit fails:

https://github.com/VeronikaHillebrand/bug-report-playwright-webkit/actions/runs/5401042799/jobs/9810308767

The last version of Playwright which worked correctly was 1.34

The error showing in the console is "TypeError: Attempting to define property on object that is not extensible."

<img width="1249" alt="image" src="https://github.com/microsoft/playwright/assets/128626672/f8d32a9f-e71e-4943-a4a9-04a7274d2a42">

PS: The app works fine in Safari.

**Comment by mxschmitt** [comment]
Looks like it was an upstream WebKit regression and they already fixed it. I was not able to reproduce it in our Canary builds: https://playwright.dev/docs/canary-releases

**Comment by VeronikaHillebrand** [comment]
I can confirm that the next version of Playwright fixes my example repo. Thanks for your help.
