### ISSUE TITLE
[Feature] Improve Playwright Installation Process for Non-Ubuntu Linux Distributions by Adding Dynamic Package Manager Detection and Support

### ISSUE THREAD

**Issue by luisKisters** [microsoft/playwright#23949]
Currently, Playwright only supports Ubuntu (as far as I know) for automatically installing operating system dependencies using the command `npx playwright install-deps`. However, when running this command on other Linux distributions, such as mine, I encounter an error that prevents successful installation. The error message indicates that the fallback method of installing dependencies for Ubuntu fails because the apt-get command is not found on my system.

# Error Message:
```
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
Switching to root user to install dependencies...
sh: line 1: apt-get: command not found
Failed to install browsers
Error: Installation process exited with code: 127
Error: Command failed: npx playwright install --with-deps
```
# Expected Behavior:
I suggest enhancing Playwright's installation process to detect the package manager used by the user's Linux distribution and dynamically select the appropriate command for installing operating system dependencies. This would ensure compatibility with a wider range of Linux systems and prevent errors like the one mentioned above.

# Steps to Reproduce:

Attempt to run `npx playwright install-deps` on a Linux distribution other than Ubuntu.
Observe the error message and the failure to install dependencies.

# Additional Information:

Operating System: EndeavourOS Linux x86_64
Playwright version: 1.35.1
Package manager used by my Linux distribution: [pacman, yay]

Thank you for considering this feature request. It would greatly improve the usability of Playwright on various Linux distros and provide a smoother installation experience for users.

**Comment by mxschmitt** [comment]
Supporting a new operating system is not only about installing more linux dependencies. In the case of WebKit we need to compile the browser for the new operating system, for multiple architectures and run the tests on it. So a generic solution to just make it work with other os package managers won't work.

We can change this to a feature request for supporting EndeavourOS if thats fine for you.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by luisKisters** [comment]
@matheussilvasantos yes afaik but having it automated would have been nicer

**Comment by unnati-solanki-git** [comment]
Hi @luisKisters Is there any impact of this? Does that mean playwright browser installation isn't supported for non-ubuntu OS? 

I'm curious to know if there is any workaround to this as I'm getting the same error right now.
