### ISSUE TITLE
[Feature] Edit the format of screenshots on failure

### ISSUE THREAD

**Issue by nukhtarov** [microsoft/playwright#23950]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

When the tests fail, screenshots are created in .png format, I would like to be able to choose a format such as .jpg, because they weigh less and therefore the report will also weigh less

**Comment by mxschmitt** [comment]
Do you mean this screenshot option? https://playwright.dev/docs/api/class-testoptions#test-options-screenshot

We actually recommend Trace Viewer which has a much better debugging experience. Also PNG is preferred since its a lossless format which is much better for comparing images.

How many screenshots are you creating and how large are they?

**Comment by nukhtarov** [comment]
> Do you mean this screenshot option? https://playwright.dev/docs/api/class-testoptions#test-options-screenshot

Yes.

> We actually recommend Trace Viewer which has a much better debugging experience. Also PNG is preferred since its a lossless format which is much better for comparing images.

Yes, it's good, we use it when the allure report is not quite clear what happened

For example, if more than 100 tests are crashed or broken, the allure report may weigh 500mb, because of this the report may not upload to the server. Accordingly, if there are 100 tests, then there are also a lot of retries

Screenshots weigh from 100KB to 500KB.

**Comment by mxschmitt** [comment]
Sounds more like you are interested in [maxFailures](https://playwright.dev/docs/api/class-testconfig#test-config-max-failures) to e.g. 20 to handle the case if most of your tests are broken. Would that fit for your needs?

**Comment by nukhtarov** [comment]
It was 50, just reduced it to 20. I'll look at it then, and if I need to, I'll write. Thanks

**Comment by aslushnikov** [comment]
Closing this as per discussion above; feel free to file a new issue if you think we still can be helpful to you.
