### ISSUE TITLE
[BUG] Click with flag "force: true" waits for availability of element in frame. Docker+Jenkins

### ISSUE THREAD

**Issue by TheCPAKA** [microsoft/playwright#23958]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [macOS 13.4 (22F66)]
- Browser: [Chrome-headless]
- Other info: Docker image v1.34.0-jammy

### Issue:
Hello, folks! Thank you for the great framework!

I'm faced with strange issue: I'm trying to click frame by coordinates with flag **force: true**, but it somehow waits for element to be stable and test fails due timeout after that. It waits for 15-20 sec to perform a click, also tried with flag **noWaitAfter: true**. Not reproduces locally, but reproduces on Jenkins job. Locally in docker works as expected.

I cant provide code or source where it reproduces, but i can share log screen:

![image](https://github.com/microsoft/playwright/assets/53820607/cd2ab888-84c5-4290-a127-9e1b614dd9a4)

On the log tab I see a list of availability checks. 
- waiting for frameLocator('main iframe').locator('html')
- locator resolved to <html class="desktop">…</html>
- attempting click action
- waiting for element to be visible, enabled and stable
- forcing action
- element is visible, enabled and stable
- scrolling into view if needed
- done scrolling
- performing click action
- click action done
- waiting for scheduled navigations to finish
- navigations have finished

Should they be displayed at all if **force: true**? 

Best regards,
Serhii K.

**Comment by pavelfeldman** [comment]
force: true can't force the click on the element that is not there, so yes, they should. force: true will bypass enabled / occluded checks, but it still needs to see something it clicks.

**Comment by pavelfeldman** [comment]
You can set the timeout to the individual click call.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
