### ISSUE TITLE
[General Query] 2 greps for same project with logical OR operation

### ISSUE THREAD

**Issue by elementarymindscape** [microsoft/playwright#23961]
Hi Team,

I wanted to ask a general query

```
... rest of config
projects: [
{
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      grep: /mobile/,
},
{
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'], channel: 'chrome' },
      grep: /desktop/,
},
]
... rest of config
```

this is how we define greps for our projects by defining them a grep in the projects array.

I wanted to ask if it is possible to add 2 greps to one projects, for example, for Mobile chrome project, I want to add 2 greps mobile and app using OR condition, something like grep: /mobile/ or /app/ so that if in the test case we either have @mobile or @app then it should use the same Mobile Chrome project instead of defining 2 projects differently for mobile and app grep.

Please tell me if this is possible or is there any alternative approach to the above problem. Any help on this topic is appreciated.

I want something like 
```
projects: [
{
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
      grep: /mobile/ or /app/,
},
{
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'], channel: 'chrome' },
      grep: /desktop/,
},
]
... rest of config
```

Thanks,
Vivek.

**Comment by pavelfeldman** [comment]
You can use grep syntax to express 'or' in one value.
