### ISSUE TITLE
[BUG] HTML Trace Report seems broken

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#23963]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Issue

Why is the trace in my html report looking like this now? I can't even scroll. I have to zoom out to make it anything barely usable. 

<img width="1492" alt="Screenshot 2023-06-29 at 12 33 13 PM" src="https://github.com/microsoft/playwright/assets/122398930/9b9b83e9-d9cf-450c-8911-861a6fd1b6b9">

For most of my other tests, the timeline part covers around 50% of the page. Earlier it was 1 row per tab, so at max 3 to 4 rows would still be under 40% of the page and much more usable. I started noticing this after 1.35.1 I guess, or after 1.35, not sure.

**Comment by mxschmitt** [comment]
It looks like your test is creating a lot of pages per test, thats why trace viewer is confused. Are you using axe playwright by any chance? Since they create a internal page for every time you call them and this ends up in such a state.

**Comment by siddharth2023** [comment]
No, I am not using axe Playwright.

Anyway I can debug what is causing this?

**Comment by siddharth2023** [comment]
It would be good if I could collapse that section. Could I change this to a feature request?
