### ISSUE TITLE
[BUG] `new Intl.ListFormat` throws in webkit

### ISSUE THREAD

**Issue by chernodub** [microsoft/playwright#23978]
### Description

`Intl.ListFormat` is [available from Safari 14.1](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/ListFormat). I tested it in Safari 15.6, 16.4 and it works fine. But, when testing in playwright's webkit 16.4, it throws an error.

### System info
- Playwright Version: **v1.35.1**
- Operating System: **macOS 12.5.1**
- Browser: **WebKit**

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/chernodub/playwright-repro

**Failing scenario**

```html
<!DOCTYPE html>
<html lang="en">
  <body>
    Using <code>new Intl.ListFormat</code>!

    <div data-testid="list-container" class="container"></div>

    <script>
      const data = ["first", "second", "third"];

      // this seems to be failing in playwright's webkit
      const listFormat = new Intl.ListFormat("en", {
        type: "disjunction",
        style: "short",
      });

      document.querySelector(".container").textContent =
        listFormat.format(data);
    </script>
  </body>
</html>
```

**Steps**
- Use `new Intl.ListFormat` API in the browser
- Run the test in webkit

**Expected**

It does not fail and formats the list correctly.

**Actual**

It throws:

```
TypeError: undefined is not a constructor (evaluating 'new Intl.ListFormat("en", {
  type: "disjunction",
  style: "short",
})')
```

**Comment by philwolstenholme** [comment]
I think I'm running into this too, when using the popular React Aria package: https://github.com/adobe/react-spectrum/discussions/5417

Using Playwright `1.39.0`

**Comment by philwolstenholme** [comment]
There was a CVE for a Webkit issue when using `new Intl.ListFormat` - I wonder if that is related? Maybe the functionality was removed or affected as part of dealing with the CVE?

https://ssd-disclosure.com/ssd-advisory-apple-safari-icu-out-of-bounds-write

**Comment by philwolstenholme** [comment]
@yury-s is this issue closed because you've added a test that proves it's not a Webkit/Playwright issue? That's fine, but I just wanted to confirm as the issue was closed without an explanation.

**Comment by yury-s** [comment]
Sorry, here is the context. The issue is fixed in the webkit that is used in tip-of-tree playwright and the fix will be available when v1.40 is published (next week or so).

**Comment by philwolstenholme** [comment]
> Sorry, here is the context. The issue is fixed in the webkit that is used in tip-of-tree playwright and the fix will be available when v1.40 is published (next week or so).

Ah, that's great news - thank you!

**Comment by philwolstenholme** [comment]
Confirming that this works great on 1.40 :)

**Comment by vmohir** [comment]
We're still running into this issue in 1.56 and 1.58.
