### ISSUE TITLE
[Feature] Add support for asserting on selected option label(s)

### ISSUE THREAD

**Issue by mrokitka** [microsoft/playwright#23970]
Assertions exist for select type locators for both value and values (for multiselect), but there is no assertion for selected labels. It is unusual that you can select a value by label, but cannot perform an assertion based on the label.

Relevant docs:
https://playwright.dev/java/docs/input#select-options
https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-value
https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-values

I would propose that the following select assertions are added:

assertThat(locator).hasLabel()
assertThat(locator).hasLabels() - for multi-selects

**Comment by mxschmitt** [comment]
Would the `locator` then be a specific `option` element and you want to ensure that it has any label text?

Do you want to make sure it has a certain specific label text or only its existence?

**Comment by mrokitka** [comment]
I think the locator would refer to the select element and the assertion would be used similar to ​[To have values](​​https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-values) , except we would specify the label(s) of the desired selected option elements rather then the values.  This would be useful in scenarios where the label is a more user friendly text string and the value is machine generated, such as a UUID or surrogate key.

**Comment by mxschmitt** [comment]
The following works for me already:

```ts
  await page.setContent(`
    <select>
      <option value="1">One</option>
      <option value="2">Two</option>
      <option value="3">Three</option>
    </select>
  `);
  await expect(page.locator('option[value="1"]')).toHaveText('One');
```

Should then also work in Java with [hasText](https://playwright.dev/java/docs/api/class-locatorassertions#locator-assertions-to-have-text). Would that work for you?

**Comment by mxschmitt** [comment]
Closing as per above. Since we don't monitor closed issues, please re-file for further questions.

**Comment by mxschmitt** [comment]
Merging into https://github.com/microsoft/playwright/issues/27146.
