### ISSUE TITLE
[Feature] Codegen against WebView2

### ISSUE THREAD

**Issue by martinvaner** [microsoft/playwright#23975]
Hello, I would appreciate it if playwright codegen would work against WebView2. In my company we are developing a MAUI app and want to do UI tests. We have a pretty rich UI and it gets tedious to locate elements.
Testing with Playwright works perfectly - we are connecting to the app via CDP, but actually writing test code gets frustrating. I think more people that are working on desktop applications would appreciate this feature to speed up the development process.

Thank you.
Martin

**Comment by mxschmitt** [comment]
When you have a Page instance, you can call [Page.PauseAsync()](https://playwright.dev/dotnet/docs/api/class-page#page-pause) which will give you Inspector where you can start Codegen. Would that work for you? See also [here](https://playwright.dev/dotnet/docs/codegen#record-using-custom-setup).

**Comment by martinvaner** [comment]
That totally works, thank you very much.
