### ISSUE TITLE
[Question] Integration with Graphql

### ISSUE THREAD

**Issue by ShagaIZ** [microsoft/playwright#23973]
Hello, i got stuck with automation API based on Graphql. So is it possible to implement integration Playwright with Graphql ? I'll appreciate for this.

**Comment by pavelfeldman** [comment]
There are plenty of examples of intercepting graphql requests and testing these apis, could you be more specific?

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
