### ISSUE TITLE
[BUG] PDF generation stops working with chromium 115 (1067) after a while.

### ISSUE THREAD

**Issue by sofiageo** [microsoft/playwright#23988]
**Context:**
- Playwright Version: 1.35.0
- Operating System: Ubuntu Linux
- .NET version: 8 preview  5
- Browser: Chromium 115 (1067)

**Describe the bug**

PDF generation stops working with stable chromium version after a while. Probably related to: https://bugs.chromium.org/p/chromium/issues/detail?id=1451760

I resorted to use `chromium-tip-of-the-tree` build and rename the directory so playwright can use it. It looks to be working without issues for the past 2+ hours. I think the fix should also be available for 115.0.5790.34 build.

Since I'm using playwright in a service, I have to restart the service after it stops working (giving a null pointer exception). I'm not sure if this is something that should be fixed in the library. 

I mostly made this issue to make aware that there is a problem with the last version of playwright and a workaround. Maybe no action is needed if it's caused by a chromium regression.

**Comment by sofiageo** [comment]
update: it still stopped working with chromium-tip-of-the-tree build. It lasted about 16 hours, or 43 calls.

**Comment by sofiageo** [comment]
I had a better look and according to the comments in the chromium issue, this should be working for 116.0.5829.0, but not for 116.0.5817.0. playwright is currently using 116.0.5805.0

so probably there is no solution yet for playwright and we have to wait for a more recent version.

**Comment by pavelfeldman** [comment]
I don't think it is actionable on the Playwright side, closing.

**Comment by sofiageo** [comment]
Well playwright is only using broken chromiums at the moment, so i consider that a regression. But anyway
