### ISSUE TITLE
[BUG] press('Enter') function not work with fullyParallel = true

### ISSUE THREAD

**Issue by ngocdd** [microsoft/playwright#23989]
here my code: 
```
    async searchBook(bookName: string) {
        await this.txtSearchBox.focus();
        await this.txtSearchBox.fill(bookName);
        await this.txtSearchBox.focus();
        await this.txtSearchBox.press('Enter');
        await this.mnuBookName(bookName).click();
    }
```
    
   I always get failed at `press('Enter')` when running tests with config `fullyParallel: true,` but it works well with `fullyParallel: false,`  seem when we have many browsers opening at the same time we got problems with focusing so Keyboard's functions it does not work as expected. please help to check it. Thanks team!

**Comment by ngocdd** [comment]
I tried with `headless:true or false` but both still do not work

**Comment by pavelfeldman** [comment]
Could you follow the issue template and file something we can reproduce? What browser is that?

**Comment by ngocdd** [comment]
After rechecking, I found that the browser is missing focus on the textbox at the time browser performs the press Enter actions, so I will close this. Thanks
