### ISSUE TITLE
[Feature] toHaveScreenshot More control over the ability to name a image pattern

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#23980]
At the moment, the screen name consists of a piece of text that we defined when calling the method but the second part is generated based on the profile name from the configuration file used system. For specific configurations, such as a dedicated profile for each environment, the number of screenshots increases.

`.toHaveScreenshot(test.png)
`
file name:

`test-chrome-dev-linux.png`
`test-chrome-test-linux.png`

part of config.ts
```
  projects: [
    {
      name: 'chrome-dev',
      [...]
      baseURL_GB: "www.dev.gb"
    },
      {
      name: 'chrome-test',
      [...]
      baseURL_GB: "www.test.gb"
    },
```
In below case I will have 2 screenshots for one test - for each env, one of them is redundant (I expect similar visual output on each renv) . About my config.ts construction - is already designed to handle multiple configuration - I don't want to change approach in my configuration.

Is there any way to make the latter part of the name overwritable? Or extracted as an additional parameter in projects?

**Comment by mxschmitt** [comment]
In version 1.28 we added [`testProject.snapshotPathTemplate`](https://playwright.dev/docs/api/class-testproject#test-project-snapshot-path-template) and [`testConfig.snapshotPathTemplate`](https://playwright.dev/docs/api/class-testconfig#test-config-snapshot-path-template) to configure a template controlling location of snapshots generated by [`expect(page).toHaveScreenshot(name[, options])`](https://playwright.dev/docs/test-assertions#page-assertions-to-have-screenshot-1) and [`expect(screenshot).toMatchSnapshot(name[, options])`](https://playwright.dev/docs/test-assertions#screenshot-assertions-to-match-snapshot-1).

  ```js
  // playwright.config.ts
  import type { PlaywrightTestConfig } from '@playwright/test';

  const config: PlaywrightTestConfig = {
    testDir: './tests',
    snapshotPathTemplate: '{testDir}/__screenshots__/{testFilePath}/{arg}{ext}',
  };

  export default config;
  ```

Would that work for you? This should give you fine graded control on config and project level where screenshots get passed.

**Comment by OSnuszka** [comment]
Looks like exactly a fix for my problem - I will try it on Monday, once I will start work  Thank you Max.
