### ISSUE TITLE
[Feature] Ability to stub functions similar to cy.stub in Cypress

### ISSUE THREAD

**Issue by BryantUng-at** [microsoft/playwright#23986]
I want the ability to stub a method, similar to how you can do this in cypress with [cy.stub](https://docs.cypress.io/api/commands/stub).
We're moving from Cypress -> Playwright and were curious how can one do the equivalent in playwright?

I looked at docs for [mocking API](https://playwright.dev/docs/mock-browser-apis#creating-mocks) and couldn't figure out how I can provide the object and method I'm stubbing. 

Example in Cypress helper function:

```ts
import * as Radio from './radio';

export function stubChannelCount(){
       cy.stub(Radio, 'getChannelCount').returns(20);
}
```

**Comment by pavelfeldman** [comment]
What is radio in your example, what are you trying to mock in your page? You are looking at the right docs page.

**Comment by BryantUng-at** [comment]
the above is not a real example but in the real example it's a file with a bunch of function exports say:

radio.tsx
```tsx

export function getChannelCount(){
 /// Some logic to calculate getChannelCount and returns channel count
}

```
It would be nice to be able to use sinon.js to spy, stub, and mock in the browser.

**Comment by pavelfeldman** [comment]
You can use sinon in the browser. There are a bunch of examples for it in https://github.com/microsoft/playwright/issues/6347

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by zyasir** [comment]
@pavelfeldman #6347 doesn't show how to stub/spy on a function in a npm module or one of the projects own files. I don't think that's possible, so this issue should probably be reopened.
