### ISSUE TITLE
[BUG] Selector ``name: new RegExp(`\b${escapeRegExp(skill)}\b`` doesn't compile correctly

### ISSUE THREAD

**Issue by stdedos** [microsoft/playwright#23996]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

![image](https://github.com/microsoft/playwright/assets/133706/8cc661bf-b20d-4e0a-9161-b08781a51fc3)

```ts
        await this.page
          .getByRole('row', {
            name: new RegExp(`\b${escapeRegExp(skill)}\b`, 'u'),
          })
          .locator('span')
          .click()
```

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

Selector `getByRole('row', { name: /cabce/u }).locator('span')` works

[Describe expected behavior]

**Actual**

Selector `getByRole('row', { name: /cabce/u }).locator('span')` doesn't work, but `getByRole('row', { name: /\bcabce\b/u }).locator('span')` does work.

one of the `playwright` generated:

```console
> playwright.generateLocator($0)
< getByRole('row', { name: 'Ca# cabce ' }).locator('label')
```

_So my code looks correct_

[Describe actual behavior]

**Comment by pavelfeldman** [comment]
We don't know what your escapeRegExp(skill) does, so we can reproduce this issue. Please follow the issue template and provide the exact steps we can perform to reproduce it locally!

**Comment by stdedos** [comment]
> We don't know what your escapeRegExp(skill) does, so we can reproduce this issue

`escapeRegExp` is borrowed from here: https://stackoverflow.com/a/3561711/2309247

```ts
function escapeRegex(string) {
    return string.replace(/[/\-\\^$*+?.()|[\]{}]/g, '\\$&');
}
```

> Please follow the issue template and provide the exact steps we can perform to reproduce it locally!

Your issue template is bloated, un-generate-able, and anyway, you could not replicate my case locally - as the website I am testing is behind authentication. Moreover, it is private information - so I cannot exactly share much.
