### ISSUE TITLE
[BUG] Locator.setChecked() works in reverse for 'toggle' element

### ISSUE THREAD

**Issue by Sysqwerty** [microsoft/playwright#23997]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code

In our application we have toggle button that looks like this:
![image](https://github.com/microsoft/playwright/assets/13851264/6bf5fa79-b9b3-4e42-b498-20b7aa0d21a9)

```
<div class="custom-togglebtn>
    <label class="custom-togglebtn__label">
        <input class="custom-togglebtn__input>
        <span class="custom-togglebtn__icon"></span>
    </label>
</div>
```

I see in docs that Locator.setChecked() should be used only for 'checkbox or a radio element' but in common toggle element is a checkbox.
When I use `Locator.setChecked()` method to 'check' or 'uncheck' the toggle (page.locator('div.custom-togglebtn')) -> **it works in reverse**.
What I mean:
- setChecked(true) disables the toggle
- setChecked(false) enables the toggle

**Steps**
Try to enable a toggle element using Locator.setChecked(true)

**Expected**

Toggle is enabled

**Actual**

Toggle is disabled

**Comment by pavelfeldman** [comment]
Looking at the DOM of your page, we have no way of knowing when your custom toggle button is toggled and when it is not toggled.

**Comment by Sysqwerty** [comment]
@pavelfeldman, I use `Locator.check()` on input element inside the toggle button node to get its state (BTW it also works in reverse somewhy)

**Comment by Sysqwerty** [comment]
I've checked same UI element via selenium method `isSelected()` and it returns correct state of element ("true" when the toggle button is ON)

**Comment by Sysqwerty** [comment]
@pavelfeldman closed this as [completed]
Could you please describe: was this fixed or skipped? If was, in which version I can see the fix?
