### ISSUE TITLE
[Question] Efficiently scrape data from tables using playwright

### ISSUE THREAD

**Issue by PrinceT078** [microsoft/playwright#23995]
I need to scrape some tables, so want to check whats the most efficient way of scraping the large data from tables:

- Is it by locating the table with locator and looping through all rows and columns?
- Or is it possible to get all the html content of table at once and then get the data from it? if yes, what would be the most efficient way?
- Or any other suggested approach? 

Note: some cells contain anchor tags so will need to get the href values as well.
TIA.

**Comment by pavelfeldman** [comment]
Try asking your question on our discord!
