### ISSUE TITLE
[BUG] error.location is not added to the error message if no stacktrace is present

### ISSUE THREAD

**Issue by joerg1985** [microsoft/playwright#23999]
I just had https://github.com/microsoft/playwright/issues/23387 while running locally, this showed the error message is logged at https://github.com/microsoft/playwright/blob/7e310f79af8732d40e41042d437623f632610509/packages/playwright-test/src/reporters/base.ts#L241

So i had a look at the `formatFailure` code to build the error message logged.
https://github.com/microsoft/playwright/blob/7e310f79af8732d40e41042d437623f632610509/packages/playwright-test/src/reporters/base.ts#L442-L445

If there is no `parsedStack` present, the code should check if there is a `error.location` and add it to the error message.
This might help to locate error where no stack is present, but the location might be present.

### System info
- Playwright Version: 1.35.1
- Operating System: All
- Browser: All
- Other info: N/A

**Expected**

The location (file/line/column) of an error is inside the log message of the console if no stack is present.

**Actual**

The location (file/line/column) an error might get dropped when no stack is present.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/23387
