### ISSUE TITLE
[BUG] HTML Reporter does not show stdout/stderr in the "Attachments" tab

### ISSUE THREAD

**Issue by csr632** [microsoft/playwright#23993]
![image](https://github.com/microsoft/playwright/assets/18747423/f2de380d-5c29-47d0-9ec9-fd856e8052c8)
Only one of the "stdout" file is shown. I can not see the other stdout/stderr. They are only links like `http://localhost:9323/data/xxxxxx.bin`.

### System info
- Playwright Version: [v1.35.1]
- Operating System: [All, Ubuntu 20]
- Browser: [All, Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

My playwright config:
https://github.com/vitejs/vite-plugin-react-pages/blob/fix/md-hmr/test-setup/playwright.config.ts

**Steps**
- Download the test report `chromium-ubuntu-20.04-playwright-report` in https://github.com/vitejs/vite-plugin-react-pages/actions/runs/5435572598
- Open the report locally
- Go to the first error test. Checkout its `Attachments` tab. You can't see stdout/stderr.

**Expected**

I want to view all stdout/stderr in the report's `Attachments` tab.

**Actual**

stdout/stderr is not shown in the report's `Attachments` tab.

**Comment by pavelfeldman** [comment]
My guess would be that your output was considered to be binary. That happens when you are writing a buffer and not a string into console.log or process.stdout.write. How do I reproduce this?

**Comment by csr632** [comment]
Thank you for the info! I have fixed the issue thanks to it.

How to reproduce the problem:
- checkout this branch https://github.com/vitejs/vite-plugin-react-pages/tree/fix/md-hmr
- go to https://github.com/vitejs/vite-plugin-react-pages/blob/b3b7f70f1f8edb47a3be4596656e04cc7ebc626e/test-setup/utils/startServer.ts#L77 and **comment out** the two `setEncoding('utf-8')` lines (this two lines fix the issue).
- pnpm run install-test-deps
- pnpm run test-serve -- hmr
- pnpm exec playwright show-report

So here is why the issue happened: I use [subprocess](https://github.com/vitejs/vite-plugin-react-pages/blob/b3b7f70f1f8edb47a3be4596656e04cc7ebc626e/test-setup/utils/startServer.ts#L65) to spawn a subprocess to run dev server. I pipe stdout/stderr into the current process. But apparently the `subprocess.stdout` is a **binary** stream by default. So playwright cannot recognize them. By adding this two lines:
```ts
subprocess.stdout.setEncoding('utf-8')
subprocess.stderr.setEncoding('utf-8')
```
playwright can now correctly collect the stdout/stderr!

**Comment by pavelfeldman** [comment]
It looks like it is working as designed then. Are you Ok with me closing this issue?

**Comment by csr632** [comment]
Yes. Let me close it.
