### ISSUE TITLE
[BUG] launchPersistentContext is not saved if context is closed

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#24007]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 10]
- Browser: [ Chromium]

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

**Test file (self-contained)**

```js
sync getText(): Promise<string> {
const context = await chromium.launchPersistentContext('C:\\temp\\playwright-cache', {headless: false, channel: 'chrome' });
const page = context.pages()[0];
await page.goto("url behind SSO");
//here user login to the SSO manually for the first time
const text= await page.locator('cssSelector').innerHTML({timeout: 60*1000});
await page.close();
return text
}
```

**Steps**

1. Playwright opens a browser with persistent context
2. Playwright navigates to a URL with behind SSO
3. User enters credentials and logins
4. Playwright grabs the text and we return it
5. Function is run for second time

**Expected**
SSO not to be shown as user has already logged in once.

**Actual**
SSO page is shown every time as session is not saved.

**Workaround**
If `await page.close();` is removed, session is correctly saved at the end of the test run and SSO page is no longer shown. However, the browser that was used to get the text required for other tests (that run in an non-persistent browser) remains open through out the test suite running and that is not ideal.

**Comment by pavelfeldman** [comment]
> If await page.close(); is removed, session is correctly saved at the end of the test run and SSO page is no longer shown.
This suggests that you are closing your page too soon? Also you don't need to use persistent contexts to implement auth reuse, follow the docs https://playwright.dev/docs/next/auth
