### ISSUE TITLE
[BUG] Playwright Test for VSCode -> Debug feature is not reading the env variables

### ISSUE THREAD

**Issue by ArCiGo** [microsoft/playwright#24006]
**Context:**
- Playwright Version: 1.34.0
- Operating System: Mac
- Node.js version: v20.0.0
- Visual Studio Code version: v1.79.2 (Universal)
- Playwright for VSCode extension version: v1.0.13
- Browser: All
- Extra: -

**Describe the bug**

I've set in my project multiple **.env** files. When I attempt to debug my tests, the debugger complains because can't read the env variables I have.

I followed this [tutorial](https://youtu.be/GQStVI5qbLI) in order to have multiple environment files. Maybe can help.

TIA!

**Comment by pavelfeldman** [comment]
You should reach out to the tutorial author - it does not seem to be official. It is also about .net, while I think you are using Node.js? We recommend using the `dotenv` package for the environment management in the Node.js.

**Comment by ArCiGo** [comment]
> You should reach out to the tutorial author - it does not seem to be official. It is also about .net, while I think you are using Node.js? We recommend using the `dotenv` package for the environment management in the Node.js.

No, it's not .NET, and I'm using **dotenv**. Before having multiple **.env** file, the debugger worked properly.

**Comment by capndave** [comment]
@pavelfeldman I don't think this should have been closed! I'm observing the same behavior, using node to run playwright on a React app
