### ISSUE TITLE
APIRequestContext class doesn't have OPTIONS request, 

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#24000]
How to use APIRequestContext for OPTIONS request call?

![image](https://github.com/microsoft/playwright/assets/21674533/c853f5a4-f7e8-4c65-85da-12a68317e782)

**Comment by iburahim786** [comment]
do we have any workaround to handle this request?

**Comment by iburahim786** [comment]
Do we have any update on the above api request addition?

**Comment by dgozman** [comment]
To make an `OPTIONS` request, use the [`APIRequestContext.fetch()`](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch) method:

```ts
await request.fetch('https://example.com/api/options', { method: 'OPTIONS' });
```
