### ISSUE TITLE
[Feature]  Configurable location for test results from an environment variable

### ISSUE THREAD

**Issue by ZooDoo4U** [microsoft/playwright#24004]
I was wondering if it would be possible to configure the report output folder based on and environment variable.    The main thought it for running withing a CI/CD pipeline where the test pipeline will configure a permanent folder for the test output to be written, and the CI/CD pipeline will set an environment variable and the PW just writes to the output folder.   Even better thinking of some of the edge cases, if something times out the log will be captured in the output folder, and when needing to investigate as much of the debug log is there...   Also would help minimizes the bandwidth needed as the test results don't need to be copied once the test completes... 

One more related thought is when using multiple reporters,  just not sure where the fix-up paths may need to go, but seems the { outputFile : 'xxx'} might need to be fix up to support this as well the config file's  "testConfig.outputDir".

**Comment by StasGrishaevTutu** [comment]
[outputDir](https://playwright.dev/docs/api/class-testconfig#test-config-output-dir) is just a sting, you can easily pass new value from env. variable, smth like 

```
import { defineConfig } from '@playwright/test';

export default defineConfig({
  outputDir: process.env.OUTPUT_DIR,
});
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
