### ISSUE TITLE
[BUG] Browsers cannot be installed with the latest version 

### ISSUE THREAD

**Issue by aswatsankar** [microsoft/playwright#24001]
#23569 similar to the issue mentioned  about browser download issue. 

### System info
- Playwright Version: [v135 or canary version]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

Followed the steps mentioned in #23569 for both V135.1 and canary version 
1. Get or [Canary version](https://playwright.dev/docs/canary-releases) via npm install -D @playwright/test@next
2. Download browsers there like that with debug logs turned on: DEBUG=pw:install npx playwright install

Expected: System to download the browsers as expected. 
Actual: System throws the following exception. 

  pw:install downloading Chromium 115.0.5790.40 (playwright build v1069) - attempt #3 +0ms
Downloading Chromium 115.0.5790.40 (playwright build v1069) from https://playwright-verizon.azureedge.net/builds/chromium/1069/chromium-win64.zip
  pw:install running download: +255ms
  pw:install -- from url: https://playwright-verizon.azureedge.net/builds/chromium/1069/chromium-win64.zip +1ms
  pw:install -- to location: C:\Users\SANKAR~1.NAR\AppData\Local\Temp\playwright-download-chromium-win64-1069.zip +1ms
  pw:install -- response status code: 200 +2s
  pw:install -- total bytes: 119909790 +1ms
114.4 Mb [====================] 99% 0.3s  pw:install attempt #3 - ERROR: Download failure, C:\Users\sankara.narayanan\AppData\Local\ms-playwright\chromium-1069\INSTALLATION_COMPLETE does not exist +30s
  pw:install FAILED installation Chromium 115.0.5790.40 (playwright build v1069) with error: Error: Download failure, C:\Users\sankara.narayanan\AppData\Local\ms-playwright\chromium-1069\INSTALLATION_COMPLETE does not exist +1ms
Failed to install browsers
Error: Failed to download Chromium 115.0.5790.40 (playwright build v1069), caused by
Error: Download failure, C:\Users\sankara.narayanan\AppData\Local\ms-playwright\chromium-1069\INSTALLATION_COMPLETE does not exist      
    at ChildProcess.<anonymous> (C:\Frameworks\Playwright\Typescript\PropertyEdge_Playwright\node_modules\playwright-core\lib\server\registry\browserFetcher.js:93:14)
    at ChildProcess.emit (node:events:512:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
![PlaywrightIssue](https://github.com/microsoft/playwright/assets/24888082/d7242a06-9758-4be2-967d-8f0128c07b11)

**Comment by mxschmitt** [comment]
Closing as per above since we can't repro. We don't monitor closed issues, please re-file for further questions.
