### ISSUE TITLE
[Feature] MAUI - interact with dialogs

### ISSUE THREAD

**Issue by martinvaner** [microsoft/playwright#24005]
Hello, in my company, we are developing MAUI desktop app for windows and we are having troubles with interacting with dialogs. 
To delete some row, we want user to confirm this action with dialog, we are using `Window.Page.DisplayAlert` method. The problem is, that we cannot UI test this functionality, because we cannot accept the dialog. I have tried to use `Dialog` event (and probably every other event) with no luck.
Is there some way to catch these dialogs from MAUI app? If not, would you consider to add this feature to your backlog?
Thank you.
Martin

**Comment by pavelfeldman** [comment]
Could you be more specific about how you are using Playwright for MAUI? Playwright is for testing web UIs only.

**Comment by martinvaner** [comment]
We are using WebView2 to connect to our app via CDP.

**Comment by pavelfeldman** [comment]
If this is a webview2 application, it could be that the dialog is implemented natively in your system, so there is no way for Playwright to handle it. Playwright is intended to be used with web properties only.
