### ISSUE TITLE
[Feature] Continue on failure in isolated tests

### ISSUE THREAD

**Issue by cdcasey** [microsoft/playwright#24009]
Currently I have 16 tests across 5 files. Each file has its own page object and fixture. Each test block uses its corresponding page fixture. The page fixture runs through the login process, so each test block includes a fresh login. I assume this makes the tests isolated from each other. Yet if any one of the tests fails, the rest are skipped. 

We're using one worker, but the order of the tests doesn't matter. So if the second test that's run fails, the results of the suite are
passed: 1
failed: 1
skipped: 14 

Can it be made to run so that it doesn't skip the other 14 tests, and instead reports individually on their success or failure? That's how I'm used to jest doing it, anyway. I would expect only test blocks that have `.skip` appended to be reported as skipped if all of the tests are isolated from each other.

Update: some people suggested I try `fullyParallel: true` in the config or `expect.soft` for the test assertions. Neither changed the results.

**Comment by pavelfeldman** [comment]
It is hard to figure it out w/o seeing the code. You probably opted into the 'serial' mode that makes tests inter-dependent which is an anti-pattern and now are fighting the implications of going off the recommended path. Could this be the case?

**Comment by cdcasey** [comment]
@pavelfeldman I don't think so. I haven't specified a mode anywhere. I do have `workers: 1` set. Would that force it into serial mode? We only have 0.5 CPU on our CI workers.

**Comment by cdcasey** [comment]
Update: specifying 3 workers with `fullyParallel: true` doesn't help. I just now have `1 interrupted` as well.

**Comment by pavelfeldman** [comment]
I'm not familiar with nx-playwright. In either case, we can't help without the repro. Playwright has complete test isolation, so if you are observing something different, please file an issue following the BUG template. It'll ask for a repro and we'll be able to address it!

**Comment by cdcasey** [comment]
Thanks. I'm working on a repro and will create a new issue if I can get it working. It may indeed be an issue with the plugin.

**Comment by cdcasey** [comment]
@pavelfeldman I'm not going to create a new bug unless this is actually a bug. But I think what I realized is that I was using fixtures wrong and that my tests weren't actually isolated.

Reproduction repo here: https://github.com/cdcasey/skip-test-repro
