### ISSUE TITLE
[Feature]merge playwright inspector and trace view into UI mode

### ISSUE THREAD

**Issue by chensce** [microsoft/playwright#24018]
Why not merge playwright inspector and trace view into UI mode？
If we do it, we can authoring test, recording test,debuging test, running test,viewing the test result in one place

**Comment by chensce** [comment]
The same as cypress ,usertrace,accelq,qawolf,and so on.

**Comment by pavelfeldman** [comment]
If you are looking for an IDE that would be able to generate, edit, debug and trace the tests, we suggest using VS Code + Playwright extension. It offers a superset of the capabilities that you describe. Standalone UI won't be able to compare to an IDE when it comes to the source code management.
