### ISSUE TITLE
[BUG]page.on('response') won't intercept all the network requests with proxy on Python

### ISSUE THREAD

**Issue by icew4y** [microsoft/playwright#24012]
### System info
- Playwright Version: [v1.35]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```python

import time
import re
import asyncio
from playwright.async_api import async_playwright

def handle_request(req, ):
    global code
    url_regex = re.compile(r"xfinitydigitalhome://auth\?")
    try:
        url = req.headers['location']
        print('response url:' + req.url)
        if url_regex.search(url):
            print("Request URL:", url)

            regexp_1 = r'&code=(.*)'
            match_2 = re.search(regexp_1, url)
            code = match_2.group(1)
            print("code")
            print(code)
            return code
    except:
        pass

async def main():
        async with async_playwright() as pw:
        url = 'https://xerxes-sub.xerxessecure.com/xerxes-ctrl/oauth/authorize?redirect_uri=xfinitydigitalhome%3A%2F%2Fauth&client_id=xfinity-digital-home&response_type=code&prompt=select_account&state=pcmI1pOdQC-sF-b2XSyNhg&code_challenge=plBIQIkEAuywK76tE4uTPI7yGIU0OTOjuvQHnlB7c3Q&code_challenge_method=S256&rm_hint=true&partner_id=comcast&mso_partner_hint=true'

        browser = await pw.chromium.launch(headless=False)
        context = await browser.new_context(
          proxy={
              'server': 'http://sample.com:port',  # replace with your proxy server and port
              'username': 'username',  # replace with your username
              'password': 'passwd'
          }, ignore_https_errors=True)
        page = await context.new_page()
        page.set_default_navigation_timeout(0)
        page.on("response", handle_request)
        print('goto: ' + url)
        await page.goto(url,
                        timeout=0, wait_until="networkidle")
        await page.wait_for_selector('#user', timeout=30000)
        await page.type('#user', username)
        print('type username')
        await page.click('#sign_in')
        time.sleep(60)
        await browser.close()

asyncio.get_event_loop().run_until_complete(main())
```

**Expected**

All the network responses should be intercepted in `handle_request`

**Actual**

I set a proxy to playwright as the code that I have listed above, it works, but not all the response are intercepted, some of the requests just weren't shown, I have also tried using `page.route`, it has the same issue too. I have no idea why, it works fine without a proxy.

I am %100 sure some of the requests are sent by the browser, I checked the network tab of Chromium, I saw the requests, but not intercepted by playwright.

**Comment by pavelfeldman** [comment]
Your code does not seem to be designed to handle all the requests. You are clicking the sign in and immediately close the browser. `time.sleep(60)` has no effect here - you can't use time.sleep in the async python context, you should await asyncio timer instead.

**Comment by icew4y** [comment]
> Your code does not seem to be designed to handle all the requests. You are clicking the sign in and immediately close the browser. `time.sleep(60)` has no effect here - you can't use time.sleep in the async python context, you should await asyncio timer instead.

I thought that was the issue, I tried using `await page.wait_for_timeout(666666)`, still the same.

**Comment by pavelfeldman** [comment]
We won't be able to act on this w/o knowing what your proxy does to the requests. If you are saying everything works fine w/o proxy, it suggests that the proxy is deferring some of the responses or does something that manifests in the behavior you observe.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
