### ISSUE TITLE
[BUG] Unable to perform keyboard events in iFrame

### ISSUE THREAD

**Issue by vipinphogat91** [microsoft/playwright#24010]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Windows 10]
- Browser: [Chromium]

### Source code

I am using playwright with javascript. In my framework I am passing the page instance to a method (lets call it frameHandler()) which is outside test method. In frameHandler() method when I am trying to perform keyboard press event I am getting an error saying TypeError: Cannot read properties of undefined (reading 'press')

**Below is the source code**

![image](https://github.com/microsoft/playwright/assets/65117374/fa5efb15-e018-46d5-8dcf-720bcc9f6820)

![image](https://github.com/microsoft/playwright/assets/65117374/1612ae41-e765-4201-8ae5-2b867379078f)

**Comment by pavelfeldman** [comment]
The line 11 is assigning page variable to an iframe value. Iframes don't have keyboard property. If you use @playwright/test + Typescript, this error would be highlighted in your source code.

**Comment by vipinphogat91** [comment]
> The line 11 is assigning page variable to an iframe value. Iframes don't have keyboard property. If you use @playwright/test + Typescript, this error would be highlighted in your source code.

@pavelfeldman  then how can I perform keyboard press events on a frame? I want to send tab key after entering the text in a text box present inside the frame
