### ISSUE TITLE
[BUG] Can't click() or set_input_files() into <input> element with Webkit engine

### ISSUE THREAD

**Issue by ntrieuvi97** [microsoft/playwright#24023]
### System info
- Playwright Version: playwright-0.3.3
- Operating System: Windows 11
- Browser: WebKit
- Other info: I try to upload images to <input> with webkit engine, but it doesn't work. As debuging the test, I see <input> is a shadow element. It's fine with Chromium and Firefox.

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
page.locator("//input[@type='file']").set_input_files(["image1.png", "image2.jpg"])
```
or
```js
page.locator("//input[@type='file']").click()
```

**Steps**
- [Run the test]
- [...]

**Expected**
Input images files successfully or open dialog 

**Actual**
Can't input files or open dialog.

**Comment by pavelfeldman** [comment]
Please follow the issue template so that we could reproduce it locally.
