### ISSUE TITLE
[BUG] launchPersistentContext is not saved if context is closed 

### ISSUE THREAD

**Issue by irharrier2** [microsoft/playwright#24021]
### System info
- Playwright Version: [v1.32.1]
- Operating System: [Windows 10]
- Browser: [ Chromium]

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

**Test file (self-contained)**

```js
sync getText(): Promise<string> {
const context = await chromium.launchPersistentContext('C:\\temp\\playwright-cache', {headless: false, channel: 'chrome' });
const page = context.pages()[0];
await page.goto("url behind SSO");
//here user login to the SSO manually for the first time
const text= await page.locator('cssSelector').innerHTML({timeout: 60*1000});
await page.close();
return text
}
```

**Steps**

1. Playwright opens a browser with persistent context
2. Playwright navigates to a URL with behind SSO
3. User enters credentials and logins
4. Playwright grabs the text and we return it
5. Function is run for second time

**Expected**
SSO not to be shown as user has already logged in once.

**Actual**
SSO page is shown every time as session is not saved.

**Workaround**
If `await page.close();` is removed, session is correctly saved at the end of the test run and SSO page is no longer shown. However, the browser that was used to get the text required for other tests (that run in an non-persistent browser) remains open through out the test suite running and that is not ideal.

It was mentioned in [this issue](https://github.com/microsoft/playwright/issues/24007) that page is being closed too early and it is causing the session not to be persisted.  
However, adding some explicit timeout to try this theory did not proof useful:
`await page.waitForTimeout(30000); `
it seem like that as long as the page closed via `page.close()`, it is not saving the session.

Note:
- Due to compliance and other technical decisions, this is the only way that I am able to save session instead of using storageState. 
- I already raised this issue  [this issue](https://github.com/microsoft/playwright/issues/24007), however, it was closed without an answer that works. So I am not sure if I should leave a comment there or create a new issue. Please advice.

**Comment by pavelfeldman** [comment]
Unfortunately there is no "answer". We don't know how your page works, different web properties work differently. They can use one of many ways of storing the persistent state for subsequent login. They can also defer saving those credentials and/or do that upon some stray signal. So there is no universal answer to your question. You should figure out what you should wait for or how to force the page to store credentials and then close the context gracefully. Unfortunately, even then it is likely to be prone to the internal browser race conditions. If you are doing testing, using context's storageState is the only reliable solution we are offering.

**Comment by irharrier2** [comment]
Given that the adding explicit wait time doesn't solve the issue and Playwright closing it will always solve the issue, I am sure is not a race condition or  a problem with "stray" signals. I believe it has to do with how the session tokens are handled.

Closing Chrome manually will not cause the tokens sessions to expire. That is why your average SSO session doesn't expire until you have restarted your computer even though the tokens are assigned per session.

It seems like that doing a page.close() causes the session tokens to expire but Playwright cleanup doesn't cause the session token to expire.  

Do you have any idea here?

**Comment by VersionIT95** [comment]
Very well written! I’ve been looking for career-oriented courses, and **[Playwright Training in Hyderabad](https://versionit.co.in/playwright-training-in-hyderabad/)** sounds like a great choice after reading this.
