### ISSUE TITLE
[BUG]- Context.addInitScript not executed

### ISSUE THREAD

**Issue by marianolopezcortes** [microsoft/playwright#24029]
I don't know why but context-level scripts injected by `addInitScript` are not executed. But page-level scripts do. They should be equivalent, shouldn't they?

### System info
- Playwright Version: 1.35.1
- Operating System: Windows 10
- Browser: Chromium

### Source code

```js
import { chromium } from '@playwright/test';

(async () => {
	const browser = await chromium.launch({ headless: false });

	const context = await browser.newContext();

	await context.addInitScript(() => {
		window.addEventListener(
			'click',
			() => {
				console.log('Click on context scope');
			},
			true
		);
	});

	const page = await browser.newPage();
	await page.addInitScript(() => {
		window.addEventListener(
			'click',
			() => {
				console.log('Click on page scope');
			},
			true
		);
	});

	await page.goto('https://playwright.dev/docs/api/class-page#page-add-init-script');

	await page.waitForTimeout(1000 * 60 * 10);
	await browser.close();
})();
```

**Steps**
- [Run the test]

**Expected**
Context-level script should be executed

**Actual**
Only page-level script is executed

**Comment by pavelfeldman** [comment]
> const page = await browser.newPage();

As per docs, this call creates a new context and a page inside that context. You wanted to say

`const page = await context.newPage();`
