### ISSUE TITLE
Connection closed while reading from the driver

### ISSUE THREAD

**Issue by 2849232wy** [microsoft/playwright#24024]
When I deploy the project on linxu, an error will be reported

### Source code

  async def run(self):
            playwright = await async_playwright().start() …
            chromium = playwright.chromium
            browser = await chromium.launch(
                headless=True)
                # proxy={"server": "http://127.0.0.1:19180"})
            context = await browser.new_context(storage_state=f"{BASE_DIR}/login_data_facebook.json", viewport={"width": 1080, "height": 1920})
            await self.screenshot(context)

**Comment by pavelfeldman** [comment]
Please follow the issue template so that we could reproduce it locally.

**Comment by xjtupy** [comment]
Hi，have you solved this problem?

**Comment by kennard520** [comment]
Hi，have you solved this problem?

**Comment by 2849232wy** [comment]
> Hi，have you solved this problem?

My issue occurs in a Linux environment; it works fine on Windows.

**Comment by kennard520** [comment]
> > Hi，have you solved this problem?
> 
> My issue occurs in a Linux environment; it works fine on Windows.

OK， My issue occurs on windows
