### ISSUE TITLE
Can we compare 2 .csv files in Playwright using javaScript.

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#24022]
**Can we compare 2 .csv files in Playwright using javaScript.**
**File1** - is the Playwright generated file by running test case.
**File2** - is our sample file which we already have (to compare with File1).

Wanted to verify that all the data in both the files is same or not. 
Also, if there is difference in data on any row/column need to identify that respective row/column and print it.

It would be great if someone can help me.

Thanks!

**Comment by cenfun** [comment]
try `toMatchSnapshot` 
https://playwright.dev/docs/api/class-snapshotassertions

**Comment by AkkyLohana90** [comment]
Hello [cenfun],

Thanks!
Will try it.

**Comment by pavelfeldman** [comment]
Closing as per above. Event if that does not work for you, JavaScript is powerful enough to parse / compare cvs.
