### ISSUE TITLE
How can we abort testcase explicitly before timeout?

### ISSUE THREAD

**Issue by rphacker1618** [microsoft/playwright#24037]
How can we abort testcase explicitly before timeout?

### System info
Playwright Version: 1.31.2
Operating System: Windows
Browser: Chrome/Chromium

**Comment by pavelfeldman** [comment]
Could you elaborate on your request and provide an example?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
