### ISSUE TITLE
[BUG] - Context.addInitScript not executed on rich-text editor iframe

### ISSUE THREAD

**Issue by marianolopezcortes** [microsoft/playwright#24038]
In this example, context-level script is not executed for rich-text iframe. Only frameattached script is executed. But, according to doc, context-level script should be executed on frame attaching, shouldn't it? Thanks!!

In the following example that works fine: 
https://the-internet.herokuapp.com/nested_frames

### System info
- Playwright Version: 1.35.1
- Operating System: Windows 10
- Browser: Chromium

### Source code

```js
import { Frame, chromium } from '@playwright/test';
declare const window: any;

(async () => {
	const browser = await chromium.launch({ headless: false });

	const context = await browser.newContext();

	await context.addInitScript(() => {
		window.addEventListener(
			'click',
			() => {
				console.log('Click on context scope');
			},
			true
		);
	});

	const page = await context.newPage();

	page.on('frameattached', async (frame: Frame) => {
		await frame.evaluate(() => window.addEventListener(
			'click',
			() => {
				console.log('Click on frameattached');
			},
			true);
	});

	await page.goto('https://the-internet.herokuapp.com/iframe');
	await page.waitForTimeout(1000 * 60 * 10);
	await browser.close();
})();
```

**Steps**
- [Run the test]

**Expected**
Context-level script should be executed inside iframe

**Actual**
Only frameattached script is executed

**Comment by pavelfeldman** [comment]
If you add console.log into your `await context.addInitScript(() ` you will see that this code is executed in the iframe. The document of that iframe is probably getting rewritten using `document.open` later on and that removes all the listeners you installed.

Also note that you have an async event listener:

`page.on('frameattached', async (frame: Frame) => {`

which is not a thing. It could be that you close the page before this listener finishes and it'll result in unhandled exceptions.

**Comment by marianolopezcortes** [comment]
Ok. I see. But I don't fully understand why listeners added with frameattached works fine. They should be overwritten also. Timing issue maybe?
Thanks!!

**Comment by pavelfeldman** [comment]
> They should be overwritten also. Timing issue maybe?

Most likely. The frame is created and then (probably synchronously) written to. When the frame is created, init script is executed. The frameattached event is asynchronous, so your evaluate hits the frame after it has been overwritten.
