### ISSUE TITLE
[BUG] Locator.setChecked() and Locator.checked() works in reverse for toggle element

### ISSUE THREAD

**Issue by Sysqwerty** [microsoft/playwright#24030]
### System info
- Playwright Version: [v1.35.0]
- Operating System: [Al]
- Browser: [All]
- Other info:

### Source code

He, Team.
There is a toggle element (DOM node) that contains "input" element
When I'm trying to set it on/off or get input element state - both methods work in reverse -> return opposite value
Methods I use:
Locator.setChecked()
Locator.checked()

Same works as expected in JAVA (selenium) for same elements.

**Steps**
Try to turn on/off toggle button via `Locator.setChecked()`
Try to get toggle button state via `Locator.checked()`

**Expected**
Works as expected

**Actual**
Works in reverse

**Comment by pavelfeldman** [comment]
Please follow the issue template and file something we can reproduce locally. We have many checkbox tests and they all pass, so it must be some edge case or a bug on your side.

**Comment by Sysqwerty** [comment]
@pavelfeldman   We have many checkbox tests and they all pass...
The issue title is about Toggle element (not checkbox). If you just don't wanna fix it - OK
