### ISSUE TITLE
[Feature] "Notes"/ named actions

### ISSUE THREAD

**Issue by Diggsey** [microsoft/playwright#24033]
There are a few possible solutions, so I'll first explain the problem I would like to solve:

I have some tests which correspond to specific "demo flows" through the product. The tests correspond 1:1 with the script a person will follow to demonstrate some aspect of the product. I would like to be able to have some way to correlate between the playwright test and the script.

At the moment, I have done this by `console.log`-ing the "talking points" from the script at the equivalent points in the test, but this doesn't really work because in the UI these logs don't go anywhere useful, and in the terminal it interferes with the playwright output.

One solution I can envisage would be a new tab in the playwright UI for "notes", which can be written to by a test as it progresses, and you would be able to see the notes "as they were" at a particular moment in time when you click on an action.

Alternatively, there could be some kind of "named action group" that would allow you to group a set of actions in the list under a human readable name.

**Comment by pavelfeldman** [comment]
I think https://playwright.dev/docs/next/api/class-test#test-step is what you are looking for.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
