### ISSUE TITLE
Support Queries submitted via route other than Github

### ISSUE THREAD

**Issue by lynnafisher** [microsoft/playwright#24032]
I work for a large firm and use playwright for my test automation however we are not allowed access to Github. I want to continue using playwright and wondered if there was any other email/contact method for requesting support? It is impossible for me to login in to my girhub account from work but I have many support queries that I cant submit apart from typing out all my code on my iphone which is not efficient and very time consuming. Is github the only route for support?

**Comment by pavelfeldman** [comment]
Playwright is an open source project and does not have any official support channels. You can ask questions on the Playwright Discord though, community is quite large there and eager to help others.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
