### ISSUE TITLE
How to add screenshot within each test.step()

### ISSUE THREAD

**Issue by rphacker1618** [microsoft/playwright#24036]
Hello Team,

How can we attach screenshot within each test.step() inside test()?

### System info
- Playwright Version: 1.31.2
- Operating System: Windows
- Browser: Chrome/Chromium

### Source code
test('Google Test',async()=>{
await test.step('Navigate to google',async()=>{
await page.goto("https://www.google.com/");
})
})

**Expected**
Want to attach screenshot at test.step() in html/allure report

**Comment by pavelfeldman** [comment]
It is currently not feasible. I'll leave this open if someone wants to contribute this capability.

**Comment by aidenstern** [comment]
I am open to contributing this, just wondering what the ideal updated interface would be for test.step to capture screenshots for page(s) in the step

**Comment by aidenstern** [comment]
I've played around with implementing this a bit, thinking the ideal interface might be something like
```ts
test.step('do stuff', step => {
  step.screenshot(page1, 'page1 evidence')
  step.screenshot(page2, 'page2 evidence', { fullPage: true })
});
```
This seems most natural and can take multiple screenshots per step of pages or locators

**Comment by rphacker1618** [comment]
@aidenstern I tried implementing the above pseudo code but it is giving me below error.

![IMG_20230714_115919_2](https://github.com/microsoft/playwright/assets/91132774/9c52e9e7-b66f-41a7-9468-670b723cc1a8)

Apart from this within test.step() there are multiple async call happening, so how do I handle within this step.

**Comment by rphacker1618** [comment]
Any update on this??

**Comment by aidenstern** [comment]
> @aidenstern I tried implementing the above pseudo code but it is giving me below error.
> 
> ![IMG_20230714_115919_2](https://user-images.githubusercontent.com/91132774/253495684-9c52e9e7-b66f-41a7-9468-670b723cc1a8.jpg)
> 
> Apart from this within test.step() there are multiple async call happening, so how do I handle within this step.

Hey first of all take a screenshot with your PC it is 2023

Second of all I meant that I'd be open to implementing this functionality in the repo. The code your referencing is how I envision it should be implemented, but want to hear if others agree

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
