### ISSUE TITLE
[BUG]Connection closed while reading from the driver

### ISSUE THREAD

**Issue by 2849232wy** [microsoft/playwright#24034]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [ubuntu22]
- Browser: [Chromium]
- Other info:

### Source code

import asyncio

from playwright.async_api import async_playwright

async def run():
    async with async_playwright() as playwright:
        chromium = playwright.chromium  # or "firefox" or "webkit".
        browser = await chromium.launch(
            headless=False)
        context = await browser.new_context()
        page = await context.new_page()
        await page.goto("https://www.baidu.com")
        role = page.get_by_role(role="article")
        print(role)
        await browser.close()

asyncio.run(run())

**Config file**

```python
// playwright.tests.py
import asyncio

from playwright.async_api import async_playwright


import logging
from playwright.async_api import async_playwright, expect

logger = logging.getLogger(__name__)
from AutoTestCode.settings import BASE_DIR
import queue


class AutoScreenshot():
    main_page = "https://www.facebook.com"

    def __init__(self, code):
        self.code = code
        self.results = []

    async def login(self, context, account: dict):
        page = await context.new_page()
        await page.goto(self.main_page)
        await page.fill("#email", account.get("username"))
        await page.fill("#pass", account.get("password"))
        await page.click("//button[@name='login']")
        await expect(page.get_by_label("首页")).to_be_visible(timeout=20000)
        await page.close()
        return context.cookies()

    async def screenshot(self, context):
        page = await context.new_page()
        await page.goto(f'https://www.facebook.com/search/top/?q={self.code}', wait_until="domcontentloaded")
        if await page.get_by_text("展开").count() > 0:
            zankai = await page.get_by_text("展开").all()
            for i in zankai:
                try:
                    await i.click()
                except:
                    pass
        while await page.locator("a", has_text="了解更多").is_visible(timeout=3000) is False:
            await page.mouse.wheel(0, 500)
            if await page.get_by_text("展开").count() > 0:
                zankai = await page.get_by_text("展开").all()
                for i in zankai:
                    try:
                        await i.click(timeout=3000)
                    except:
                        pass
        need_to_screenshot = await page.get_by_role(role="article").filter(has_text=re.compile(f".*{self.code}.*")).all()
        for i in need_to_screenshot:

            screenshot_bytes = await i.screenshot()
            self.results.append(base64.b64encode(screenshot_bytes).decode("utf-8"))
        await page.close()

    async def run(self):
        async with async_playwright() as playwright:
            chromium = playwright.chromium
            browser = await chromium.launch(
                headless=True)
            context = await browser.new_context(storage_state=f"{BASE_DIR}/login_data_facebook.json", viewport={"width": 1080, "height": 1920})
            await self.screenshot(context)
            await context.close()
            await browser.close()
            return self.results
```

**Test file (self-contained)**

```python
from django.http import JsonResponse, HttpResponse
from rest_framework.views import APIView

from FacebookScreenshot.facebookplaywright import AutoScreenshot
import asyncio

class Facebook(APIView):


    def post(self, request):
        code = request.data.get("code")
        if not code:
            return JsonResponse({"code": 400, "message": "参数传递异常"}, json_dumps_params={"ensure_ascii": False})
        screen_shot = AutoScreenshot(code=code)
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)
        results = loop.run_until_complete(screen_shot.run())
        if not results:
            return JsonResponse({"code": 400, "message": "折扣码无效"})
        return JsonResponse({"code": 200, "message":"成功", "data": [i for i in results]}, json_dumps_params={"ensure_ascii": False})
```

**Steps**
- [start server python manage.py runserver 0.0.0.0:7000]
- [Accessing the django interface]

**Expected**
open the baidu main page and close

**Actual**

encountered an error：Connection closed while reading from the driver

**Comment by 2849232wy** [comment]
<html>
<body>
<ul class="traceback" style="padding: 0px; margin: 0px; list-style-type: none; color: rgb(34, 34, 34); font-family: sans-serif; font-size: small; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(238, 238, 238); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><li class="frame user" style="padding: 0px 0px 1em; margin: 0px; color: rgb(0, 0, 0); background-color: rgb(224, 224, 224);"><details style="padding: 0px; margin: 0px;"><summary class="commands" style="padding: 0px; margin: 0px 0px 0px 40px; cursor: pointer; color: rgb(85, 85, 85); text-decoration: none;">Local vars</summary><slot id="details-content" style="content-visibility: hidden; display: block;">

  |  
-- | --
  |  

</slot></details></li><li class="frame user" style="padding: 0px 0px 1em; margin: 0px; color: rgb(0, 0, 0); background-color: rgb(224, 224, 224);"><code class="fname" style="padding: 0px; margin: 0px; font-size: 10.5625px; white-space: pre-wrap; word-break: break-word; user-select: all;">/home/forge/default/venv/lib/python3.10/site-packages/playwright/async_api/_context_manager.py</code>, line 47, in __aenter__<div class="context" id="c140505841827264" style="padding: 10px 0px; margin: 0px; overflow: hidden;"><ol start="40" class="pre-context" id="pre140505841827264" style="padding: 0px 0px 0px 30px; margin: 0px 10px; list-style-position: inside;"><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;"></pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        done, _ = await asyncio.wait(</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">            {self._connection._transport.on_error_future, playwright_future},</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">            return_when=asyncio.FIRST_COMPLETED,</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        )</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        if not playwright_future.done():</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">            playwright_future.cancel()</pre></li></ol><ol start="47" class="context-line" style="padding: 0px 0px 0px 30px; margin: 0px 10px; list-style-position: inside;"><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 3px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(0, 0, 0); cursor: pointer; background-color: rgb(187, 187, 187);"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        playwright = AsyncPlaywright(next(iter(done)).result())</pre> <span style="padding: 0px; margin: 0px; position: absolute; right: 32px;">…</span></li></ol><ol start="48" class="post-context" id="post140505841827264" style="padding: 0px 0px 0px 30px; margin: 0px 10px; list-style-position: inside;"><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        playwright.stop = self.__aexit__  # type: ignore</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        return playwright</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;"></pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">    async def start(self) -&gt; AsyncPlaywright:</pre></li><li onclick="toggle('pre140505841827264', 'post140505841827264')" style="padding: 0px 0px 0px 2px; margin: 0px; font-family: monospace; white-space: pre; color: rgb(102, 102, 102); cursor: pointer;"><pre style="padding: 0px; margin: 0px; font-size: 10px; white-space: pre-wrap; word-break: break-word; display: inline;">        return await self.__aenter__()</pre></li></ol></div></li></ul>
</body>
</html>

**Comment by 2849232wy** [comment]
Please handle it for me as soon as possible

**Comment by 2849232wy** [comment]
The same code works fine on windows

**Comment by pavelfeldman** [comment]
I think you are making too many actions within the same context and Playwright does not like this. We are a testing tool, not a scraping too.

**Comment by farahats9** [comment]
@pavelfeldman I have the same issue and I am not making too many actions in the same context, I close contexts after few actions and spawn another one. Is it possible that I need to close the browser and spawn another one?

I don't think the use case has any relevance, this is still a problem.

**Comment by emelillan** [comment]
I have the same issue running my script in a GCP Cloud Function. 
Because the CF uses Flask, there could be some issues related to the async pool between both. 
The same code locally works fine, I will deploy it in a VM without the flask wrapper and see if that solves the issue.
