### ISSUE TITLE
[BUG] Official extension "Playwright Test for VSCode" doesn't see test cases in own sandbox project

### ISSUE THREAD

**Issue by DmytroYeremieiev** [microsoft/playwright#24041]
### System info
- Playwright Version: [v^1.35.1]
- Operating System: [macOS 13.3.1]

**Steps**
- Set up sandbox project following the https://playwright.dev/docs/getting-started-vscode 
- Observe VS Code interactive window: "Testing/Testing Explorer"

**Expected**

All tests were found: 

<img width="250" alt="image" src="https://github.com/microsoft/playwright/assets/19588441/3263fe4b-5c95-4075-84ea-5255237f289f">

**Actual**

Neither test case was found: 

<img width="432" alt="image" src="https://github.com/microsoft/playwright/assets/19588441/b2441e24-5e51-439e-a225-351a4ab1cd53">

**Comment by debs-obrien** [comment]
Hi @DmytroYeremieiev. I just did a fresh install following the docs and it works perfect my end with latest version. Can you please make sure you have latest version of the VS Code extension and try again. If it's still an issue please try to create a video so we can see exactly whats happening as I can't reproduce at all.

**Comment by DmytroYeremieiev** [comment]
Hello, full VS code reload has helped to resolve the issue. Not the action "Reload Window".
