### ISSUE TITLE
[BUG] With a teardown project dependency, UI mode from VSCode shows only the teardown after test run

### ISSUE THREAD

**Issue by sarah-gelt** [microsoft/playwright#24045]
### System info
- Playwright Version: [v1.35]
- Operating System: [macOS 13.4]
- Browser: [All]
- Other info: VSCode 1.79.2

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";

/**
 * See https://playwright.dev/docs/test-configuration.
 */

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
dotenv.config();

export default defineConfig({
  testDir: "./tests",
  projects: [
    { name: "setup", testMatch: ["**/*.setup.ts"], teardown: "teardown" },
    { name: "teardown", testMatch: ["**/*.setup.ts"] },
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        viewport: { width: 1280, height: 768 }
      },
      testMatch: ["**/*.spec.ts"],
      dependencies: ["setup"]
    },
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        viewport: { width: 1280, height: 768 }
      },
      testMatch: ["**/*.spec.ts"],
      dependencies: ["setup"]
    },
    {
      name: "webkit",
      use: {
        ...devices["Desktop Safari"],
        viewport: { width: 1280, height: 768 }
      },
      testMatch: ["**/*.spec.ts"],
      dependencies: ["setup"]
    }
  ],
  /* Shared settings for all projects. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.BASE_URL,
    trace: "retain-on-failure",
    headless: true
    /*launchOptions: {
      slowMo: 100 //Slow test execution down by 100ms, helpful for debugging
    }*/
  },
  /* Maximum time one test can run for. */
  timeout: 2 * 60 * 1000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000
  },
  maxFailures: process.env.CI ? 16 : undefined,
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 3 : 1,
  /* Use 3 works locally. Use workers equal to 50% of available cores on CI - UNTESTED */
  workers: process.env.CI ? "50%" : 3,
  /* Reporters to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ["html", { open: "never" }],
    ["./reporters/resultChecker"], //This outputs a file with the current branch and overall run result, to be consumed by GitHub Actions
    ["./reporters/failed-test-reporter.ts"], //This outputs a log of which tests have failed the last time they were executed, so just the failures can be rerun while debugging
    ["./reporters/better-dot-reporter.ts"]
  ]
});
```

**Steps**
- Configure projects such that a global setup and global teardown are run via project dependencies (see above config)
- Check the "Show trace viewer" option in VSCode
- Run a test from the VSCode tests UI
- Wait for the test to finish

**Expected**

UI / trace viewer shows the output of the test for analysis

**Actual**

UI / trace viewer shows only the global teardown output. If the test fails, you can't go back to see where in the trace viewer so you can't investigate why. Even if the test passes, there can be benefit to being able to see the trace to see what happened.

Ideally I would want to see top-level sections in the Actions panel with setup, test and teardown so the output of each can be examined.

**Comment by pavelfeldman** [comment]
> UI / trace viewer shows only the global teardown output. If the test fails, you can't go back to see where in the trace viewer so you can't investigate why. Even if the test passes, there can be benefit to being able to see the trace to see what happened.

You should be able to select any test that you ran and see the trace viewer for it. Just select the test in the tests sidebar.

**Comment by sarah-gelt** [comment]
> > UI / trace viewer shows only the global teardown output. If the test fails, you can't go back to see where in the trace viewer so you can't investigate why. Even if the test passes, there can be benefit to being able to see the trace to see what happened.
> 
> You should be able to select any test that you ran and see the trace viewer for it. Just select the test in the tests sidebar.

Only if I run UI mode from the command line. If I open UI mode by running a test via the VSCode interface then there is no test selector.
<img width="355" alt="image" src="https://github.com/microsoft/playwright/assets/107568761/27ee3b7a-447a-42be-bb53-bf2dfeb4cb93">

<img width="893" alt="image" src="https://github.com/microsoft/playwright/assets/107568761/b228b4d3-143d-47b5-90f0-4a581e4f2803">

<img width="393" alt="image" src="https://github.com/microsoft/playwright/assets/107568761/9874b5a2-d2a4-4a8c-b137-2bee3b8bb54b">

**Comment by pavelfeldman** [comment]
There is a "Test explorer" in VS Code if you open the "Testing" perspective (Flask icon). That's where you can select your tests.

**Comment by pavelfeldman** [comment]
I'm trying to reproduce this and it works for me:

```js
projects: [
  {
    name: 'setup',
    teardown: 'teardown',
    testMatch: 'setup.ts',
  },
  {
    name: 'project',
    testMatch: 'test.ts',
    dependencies: ['setup']
  },
  {
    name: 'teardown',
    testMatch: 'teardown.ts',
  },
],
```

**Comment by pavelfeldman** [comment]
Is there a chance we can get more data on the repro case? Do you only run tests in the chromium project while working in VS Code?

**Comment by sarah-gelt** [comment]
@pavelfeldman I've narrowed it down to just the tests in one suite which have an `afterAll` hook. If I comment out the hook or tests in any other suite without an `afterAll` then it works correctly. Strangely these are also the tests which are affected here so perhaps related?
https://github.com/microsoft/playwright/issues/24071

**Comment by pavelfeldman** [comment]
@sarah-gelt I can see it in your recording, but I can't reproduce it locally. Is there a chance you could create a small standalone project with a reduced test case that I could run? Could be just a config + a test file, or maybe just the test file even.

**Comment by sarah-gelt** [comment]
I found a workaround in our repo for the issue with this class, which resolved both the hanging test runner (here https://github.com/microsoft/playwright/issues/24071) and this issue with UI mode. I will close for now, thanks!
