### ISSUE TITLE
[Feature] Maybe update docs to not recommend assertions in POM?

### ISSUE THREAD

**Issue by jeremy-daley-kr** [microsoft/playwright#24051]
Maybe someone else can answer if this seems like a good practice or not, but I was taught the POM shouldn't include assertions in a page object:

* https://www.selenium.dev/documentation/test_practices/encouraged/page_object_models/#assertions-in-page-objects
* https://stackoverflow.com/questions/11126806/page-object-model-why-not-include-assertions-in-page-methods

...but this documentation includes an `expect` in one: https://playwright.dev/docs/pom

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
