### ISSUE TITLE
[Feature] Rerun only failed tests on Azure pipeline,

### ISSUE THREAD

**Issue by python012** [microsoft/playwright#24058]
Hi, I have a large number of tests run on Azure pipeline as a test stage, sometimes a few tests are flaky, which would fail, and whole test stage would be marked as fail in Azure pipeline.

I'd like to have a feature to only re-run the failed the tests in the test stage of my Azure pipeline, instead of clicking `Re-run failed job` to launch the whole tests set again.

**Comment by pavelfeldman** [comment]
That's what we recommend doing by default:

```js
// playwright.config.ts
retries: process.env.CI ? 2 : 0,
```

It means that on CI (and only on CI) failings tests are retried twice to detect flakiness.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
