### ISSUE TITLE
[BUG]Unable to interrupt ConsoleMessage when manually reload page by click the reload page button

### ISSUE THREAD

**Issue by sjlucn** [microsoft/playwright#24059]
`
Page page = context.newPage();

page.onConsoleMessage(consoleMessage -> {
System.out.println("consoleMessage.text() = " + consoleMessage.text());
});

page.navigate("https://www.google.com");
`

if i click the reload page button manually, it can't trigger the onConsoleMessage function

**Comment by pavelfeldman** [comment]
Could that be because your program has already ended? You are using Java, which is a blocking sync API. Try adding page.waitForTimeout(1000000) after your page.navigate call to prevent script from ending.
