### ISSUE TITLE
[BUG] WSL2 / VSCode extension: 'Record new' button in VScode does not open browser with viewport specified in config

### ISSUE THREAD

**Issue by luffy-taro** [microsoft/playwright#24062]
**Context:**
- Playwright Version: ^1.35.1
- Operating System: Windows 11 (WSL2/Ubuntu 20.04)
- Node.js version: v19.6.0
- Visual Studio Code version: 1.80-insider
- Playwright for VSCode extension version: 1.0.13
- Browser: Chromium

**Code Snippet**

```
//....
export default defineConfig({
  testDir: './tests',
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:3000',
    viewport: { width: 1920, height: 1080 },
  },
//....
```

**Describe the bug**

Clicking "Record new" button starts Chrome in the default viewport in WSL2, maximizing the browser window does not change the viewport. See attachment. 

Alternatively, using codegen from command line works fine.

`npx playwright codegen --viewport-size "1920,1080"`

![image](https://github.com/microsoft/playwright/assets/68524694/1afbb0c1-a61b-4c05-bba3-100f305ae321)

**Comment by pavelfeldman** [comment]
`npx playwright codegen` is a standalone tool, it knows nothing about @playwright/test and its config.

**Comment by luffy-taro** [comment]
> `npx playwright codegen` is a standalone tool, it knows nothing about @playwright/test and its config.

@pavelfeldman Didn't know this.

But this is still a bug since "Run" button (along with 'Show browsers' check) in VS code respects viewport specified in global config but the "Record New" function doesn't.
