### ISSUE TITLE
[REGRESSION]: load extension on edge

### ISSUE THREAD

**Issue by sam-playwright123** [microsoft/playwright#24063]
**Context:**
- GOOD Playwright Version: 1.23.0
- Operating System: Windows
- Extra: Enterprise environment

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```java
List chromeargs= new Arraylist<>
chromeargs.add("--load-extension=path\\sample.crx
Browser browser=playwright chromium().launch(new BrowserType.LaunchOptions().setChannel("msedge").setHeadless(false).setArgs(chromeargs));
BrowserContext bc=browser.newContext();
Page pg=bc.newPage();
pg.navigate(url);

```

**Describe the bug**
I am adding the extension to browser using --loadextension but the browser is opening without adding extension.

**Comment by sam-playwright123** [comment]
I am getting manifest file is missing or unreadable for the crx file

**Comment by pavelfeldman** [comment]
Looks like your way of loading extensions is incompatible with msedge. In either case, adding launch arguments is at your own risk, we don't guarantee Playwright functionality when passing args.
