### ISSUE TITLE
[Question] Disabling Auto-Fixtures during Global-Setup?

### ISSUE THREAD

**Issue by amitz** [microsoft/playwright#24078]
Is there an option to disable "Auto Fixtures" from running in a selective manner?

Now that Global-Setup is basically a test, it also invokes all our `auto: true` fixtures. A specific fixture we use, adds annotations to each test (environment name, username being used, etc).  During Global-Setup, this information is not yet ready (because Global-Setup sort of set it up). This fails this fixture.

An option would be importing `test` directly from `'@playwright/test'`, skipping our fixture from loading. But we do want to use SOME fixtures (for example, our logger fixture). It means we need to have multiple fixtures "setups". One that includes all our fixtures, and one that includes only some of the fixtures (is there even a way to use multiple fixtures files?). This is somehow clanky. I also tried querying testInfo for the location of the test file, and using if/else in the fixture, skip or invoke it. But some fixtures use other fixtures, and this is getting very boilerplatey and strange very fast. 

 Is there perhaps a better way around that?

Thanks!

**Comment by pavelfeldman** [comment]
> This is somehow clanky.

That's what we do - we have a bunch of fixture sets and we combine different combinations of those for different test suites:

```js
export const setup = baseTest
    .extend<CommonFixtures, CommonWorkerFixtures>(commonFixtures)

export const test = baseTest
    .extend<CommonFixtures, CommonWorkerFixtures>(commonFixtures)
    .extend<ServerFixtures, ServerWorkerOptions>(serverFixtures);
```

**Comment by amitz** [comment]
> That's what we do
In that case, I will follow up the example :-)
Out of curiosity - as I mentioned I'm playing on doing so because I want to exclude that specific `auto: true` fixture from the global-setup. Why would you guys want to have two sets of fixtures? For the sake of separation of concern? (like, using multiple fixtures files)? or perhaps there some performance impact on loading multiple fixtures all at once?

Thank you for the quick help! (feel free to close it, unless you have future plans to address it somehow differently).

**Comment by pavelfeldman** [comment]
We like to keep our fixture sets minimal and only give the tests what they need, separation of concerns essentially!
