### ISSUE TITLE
[How to compare div counts of same class on different env's]

### ISSUE THREAD

**Issue by ajaykhobragade** [microsoft/playwright#2407]
I have a test scenario where i have to get div counts of same class and compare it on dev and prod env. I could able to get div counts on dev & prod url separately but stuck on how to compare them and get somehow a match/not match in console log.

Following is to get div counts>>
const divsCounts = await page.$$eval('.dfp-ad-container', (divs) => divs.length);

Any ideas or suggestions on how to compare them, in playwright?

**Comment by ajaykhobragade** [comment]
Sure, I can try but if you have ready to go kinda code snippet to share, that would be great.

**Comment by ajaykhobragade** [comment]
Thanks @pavelfeldman , with help of your inputs and #1605, i could able to compare it successfully.

**Comment by pavelfeldman** [comment]
Awesome!
