### ISSUE TITLE
[BUG]: setArgs(--disable-notifications) does not work if headless(false) in case of location notification, same works in headless(true) mode

### ISSUE THREAD

**Issue by tiyalucky** [microsoft/playwright#24074]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

browser = playwright.chromium().launch
(new BrowserType.LaunchOptions().setArgs(Arrays.asList("--disable-notifications")).setHeadless(false));

Actual: Location notification still displayed in headless(false) mode but in headless(true) mode

**Comment by pavelfeldman** [comment]
Launching the browser with the command line flags is at your own risk, we don't make any guarantees about the Playwright functionality if launched with args.
