### ISSUE TITLE
Run Commond Error: Test: Install playwright222

### ISSUE THREAD

**Issue by smallnine9** [microsoft/playwright#24088]
node version:v18.16.1
npm version: 9.8.0

➜ npm init playwright@latest --yes -- --quiet --browser=chromium --browser=firefox --browser=webkit --gha
Getting started with writing end-to-end tests with Playwright:
Initializing project in '.'
Installing Playwright Test (npm install --save-dev @playwright/test)…
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*

npm ERR! A complete log of this run can be found in: /Users/yulujiang/.npm/_logs/2023-07-06T13_53_24_785Z-debug-0.log
Error: Command failed: npm install --save-dev @playwright/test
    at checkExecSyncError (node:child_process:885:11)
    at execSync (node:child_process:957:15)
    at executeCommands (/Users/yulujiang/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/Users/yulujiang/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4679:5)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/yulujiang/.npm/_npx/d352e76cc6b4974c/node_modules/create-playwright/lib/index.js:4950:3 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 67138,
  stdout: null,
  stderr: null
}
npm ERR! code 1
npm ERR! path /Users/yulujiang/gp/smallnine/blocksuite
npm ERR! command failed
npm ERR! command sh -c create-playwright --quiet --browser=chromium --browser=firefox --browser=webkit --gha

npm ERR! A complete log of this run can be found in: /Users/yulujiang/.npm/_logs/2023-07-06T13_53_22_268Z-debug-0.log

**Comment by pavelfeldman** [comment]
Please file an issue using the bug template to file something we can reproduce
