### ISSUE TITLE
[Question] Is there a way to auto-tag an annotation to all tests?

### ISSUE THREAD

**Issue by sambenison66** [microsoft/playwright#24089]
Is there a way to set up an auto-tag for all tests, so that we don't have to mention it in every test in every file exclusively?

Ideally, I would like to write a helper function that can take each test title and add an annotation.

For example,  If I have a test like this
```
test('Sample Test', ({}) => {
  // My test
})
```

I would like it to automatically infer it as:
```
test('Sample Test @newtest', ({}) => {
  // My test
})
```

So that, I can run the tests like this:

npx playwright test --grep @newtest

I would like to apply the annotation to all tests, so that I don't have to repeat it every time.

I tried fixture to update it, but it was not recognized by 'grep' command.

Also, tried using Proxy, but the `test.describe`, `test.skip`, etc are not working properly if I mess with the test instance using proxy.

Anybody have any thoughts on achieving this use case? Please advise.

Thanks.

**Comment by pavelfeldman** [comment]
No such capability in Playwright.
