### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by bluepioupiou** [microsoft/playwright#24096]
### System info
- Playwright Version: [v1.35]
- Operating System: [Windows]
- Browser: [Edge]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
A code that display an image sourced from a server and not in the front

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
       name: 'Microsoft Edge',
       use: { ...devices['Desktop Edge'], channel: 'msedge', baseURL: 'http://localhost:4200/' },
    }
});
```

**Test file (self-contained)**

```js
await page.route(`/api/web/produits/*/medias/*`, async route => {
    await route.fulfill({
      status: 200,
      path: "../fixtures/images/screenshot.png",
    });
  });
```

**Steps**
- [Run the test]
- [...]

**Expected**
The image is mocked and screenshot.png is displayed on the interface

**Actual**
The image is not displayed on my interface, without any error message and the interface doesn't display anymore

**Comment by pavelfeldman** [comment]
Please follow the bug template to file something we can reproduce. Title for the bug would also be nice!

**Comment by break7533** [comment]
anything new on this? It seems that it was closed even after the update of the initial description

**Comment by takeshi-yanagita** [comment]
This method worked for me:
```
await page.route("**/api/img/url/*", async (route) => {
        await route.fulfill({ contentType: "img", path: "local/path/img.png" });
     });
```

Using 1.36.1
