### ISSUE TITLE
[REGRESSION]: load extension on edge

### ISSUE THREAD

**Issue by sam-playwright123** [microsoft/playwright#24095]
**Context:**
- GOOD Playwright Version: 1.30.0
- BAD Playwright Version: 
- Operating System: Windows 
- 

**Code Snippet**
```java
Path paths=Paths.get("c:\\userdir)
List chromeargs=new ArrayList
chromeargs.add("--disable-extension-except="+paths)
chromeargs.add("--load-extension="+path)
BrowserType.LaunchPersistentContextOptions cp= new BrowserType.LaunchPersistentContextOptions
cp.args=chromeargs
BrowserContext bc=playwright chromium.launchPersistentContext(paths,cp);
Page pg=bc.newPage();
Pg.navigate(url)
```

**Describe the bug**
I am using the above code to load extension but I am getting error manifest file missing or non readable.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/24063
