### ISSUE TITLE
[BUG] pyinstaller --noconsole not work

### ISSUE THREAD

**Issue by hsk20011** [microsoft/playwright#24093]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [All, Windows 11]
- Browser:  Chromium
- Other info:

### Source code
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch()
    page = browser.new_page()
    page.goto("https://playwright.dev/")
    page.screenshot(path="example.png")
    browser.close()

------- pyinstaller spec file------
block_cipher = None
a = Analysis(
    ['plyTest.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='plyTest',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

---- pyinstaller command ----
pyinstaller -F  plyTest.py --noconsole

----- PROBLEM-----
plyTest.exe show console window

**Comment by pavelfeldman** [comment]
Playwright is not compatible with pyinstaller.
