### ISSUE TITLE
[Feature] Option to fail test without retry

### ISSUE THREAD

**Issue by AndreasHae** [microsoft/playwright#24097]
## Context

In our test suite, I'm implementing preconditions that need to be met in the system under test for the test case to function correctly. If those preconditions are not met, I want the test to fail so that I know that the test case could not be executed. I also do not want it to be retried because the preconditions don't change by themselves so retrying doesn't make sense.

## Feature request

Add an option to mark a test as failed and prevent retrying the test. This could be an option added to `test.fail`, or maybe as a separate API so that the `test.*` method signatures remain consistent. Open to suggestions here.

## Other options considered

I considered using `test.fixme(condition)` because in the [docs](https://playwright.dev/docs/next/test-annotations) it says:

> [test.fixme()](https://playwright.dev/docs/api/class-test#test-fixme-1) marks the test as failing. Playwright Test will not run this test, as opposed to the fail annotation. Use fixme when running the test is slow or crashes.

This is inaccurate as I found out because the test is simply skipped and not marked as failing.

**Comment by pavelfeldman** [comment]
No such feature in Playwright - failed tests are always retried.

**Comment by marty30** [comment]
For everyone coming here through google, https://github.com/microsoft/playwright/issues/24084#issuecomment-1648677854 mentions this same feature request. This issue could be seen als a duplicate.
