### ISSUE TITLE
Add a way to list tests in a machine-readable format from command line [Feature]

### ISSUE THREAD

**Issue by mbork** [microsoft/playwright#24100]
AFAIK, the only way to list all tests from CLI is to say `npx playwright test --list`. The format used is rather brittle – one test per line, with project name in brackets, using two or three `›` characters (Unicode 0x203A, `SINGLE RIGHT-POINTING ANGLE QUOTATION MARK`), depending on whether the "describe name" is empty or not. (These `›` characters are not even escaped in any way if the test name contains them!) It would be much more robust for scripts to be able to get this list as e.g. JSON.

**Comment by pavelfeldman** [comment]
You can use `npm run ctest -- --reporter json --list` or any other [reporter](https://playwright.dev/docs/next/test-reporters) (including your own custom reporter) when listing tests.
