### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vaibhavagrawal2912** [microsoft/playwright#24112]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I have injected custom javascript using browserContext.addInitScript method and implemented visibilitychange API inside the same.
For some reason, this API does not work and I cannot access the specific items from DOM due to this limitation. Is there any way or chrome args or any configuration change that I can do so that this event starts triggering?

Also, I cannot get the currently active Tab from the playwright, is there any specific way how can I get the active tab?

**Comment by pavelfeldman** [comment]
Please follow the bug template to file something we can reproduce
