### ISSUE TITLE
Add ability to transform curl from browser network tab into respective Playwright request

### ISSUE THREAD

**Issue by maxsudik** [microsoft/playwright#24120]
This feature is available in Postman and Thunderclinet for VS Code for multiple languages and frameworks.
So, could you add this functionality to your framework to streamline API testing?
This is from Postman
![image](https://github.com/microsoft/playwright/assets/40281293/7fc395ca-2bfa-40c1-ae02-9ca236f8aa6a)
This is from Thunderclinet
![image](https://github.com/microsoft/playwright/assets/40281293/4bbfed74-7bda-4a70-b85d-983fed4255ad)
![image](https://github.com/microsoft/playwright/assets/40281293/d20de67b-8bbb-4c65-a4cc-7e95c915729e)

**Comment by mxschmitt** [comment]
This is outside of the scope for Playwright. I recommend reaching out to Postman or Thunder Client, that they add this to their code generator.
