### ISSUE TITLE
[Feature] Use `micromatch` or better for faster file matching

### ISSUE THREAD

**Issue by pastelsky** [microsoft/playwright#24122]
This isn't really a feature, but I wasn't sure I should file this as a bug.

Currently, playwright depends on a very old version of `minimatch` (v3) for file matching. 

The file matching operation is done a few times during playwright startup. 
`micromatch` [performs significantly better](https://www.npmjs.com/package/micromatch#running-benchmarks) in glob matching, and this can have a small but noticeable impact on startup times for large projects that use playwright.

I was about to send across a PR for this when I noticed that playwright [uses some API bits](https://github.com/microsoft/playwright/blob/b4ffb848de1b00e9a0abad6dacdccce60cce9bed/packages/playwright-test/src/runner/projectUtils.ts#L171-L192) from `minimatch` that aren't compatible with `micromatch`. e.g. Parsing comments in patterns.

Overall, this might _technically_ be a breaking change since there are a few esoteric features like comments in globs that `micromatch` doesn't support (does anyone really use them?), but it is otherwise largely a self-stated replacement for minimatch.
A 3-10x performance jump might justify such a change.

**Comment by mxschmitt** [comment]
Do you have numbers how much it would improve?

**Comment by pastelsky** [comment]
On a very large project that I work with, supplying a `glob` pattern in `testPattern` (which causes playwright to use `minimatch`) results in the `collectFiles` playwright test function to take 21 seconds.

The same decrease to 8.5 seconds if we supply a regex to `testPattern` instead (which uses native JS regex `test`).

Now the repo is quite large and we have multiple playwright projects, so the difference is very stark, however, I'd expect the % difference to be nearly the same for normal repos as well.

**Comment by mxschmitt** [comment]
About how many files are we talking about? We are curious about your project structure, or better if we could have a repro.

**Comment by pastelsky** [comment]
About 100k files in our monorepo, and 7 different projects.

I don't think the usage for gitignore is problematic. Its perhaps the file matcher here —
https://github.com/microsoft/playwright/blob/v1.36.0/packages/playwright-test/src/util.ts#L108-L143

which is used by a bunch of different other functions

**Comment by pastelsky** [comment]
I'm not sure how I can share a repro, however I did manage to capture a `pprof` profile for a hello world test startup — 

```
Time: Jul 11, 2023 at 11:27pm (IST)
Duration: 28.43s, Total samples = 20932.41ms (73.64%)
Showing nodes accounting for 20932.41ms, 100% of 20932.41ms total
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context 	 	 
----------------------------------------------------------+-------------
                                        10108.76ms   100% |   Ye /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:13
                8421.83ms 40.23% 40.23% 10108.76ms 48.29% | Ue.match /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:14
                                         1276.13ms 12.62% |   Ue.matchOne /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:15
                                          305.16ms  3.02% |   RegExp: \/+ :14
                                           52.28ms  0.52% |   get length :14
                                              16ms  0.16% |   Ue.matchOne /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:14
                                            6.40ms 0.063% |   module2.exports /home/ubuntu/redacted/prettier/index.js:1607
                                            5.33ms 0.053% |   module2.exports /home/ubuntu/redacted/prettier/index.js:1602
                                            4.27ms 0.042% |   Ue.debug /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:13
                                            4.27ms 0.042% |   module2.exports /home/ubuntu/redacted/prettier/index.js:1609
                                            3.20ms 0.032% |   Ue.matchOne /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:16
                                            3.20ms 0.032% |   module2.exports /home/ubuntu/redacted/prettier/index.js:1611
----------------------------------------------------------+-------------
                                         3827.33ms 99.69% |   Vp /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:13
                                           11.74ms  0.31% |   (anonymous) /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:1
                2714.45ms 12.97% 53.20%  3839.07ms 18.34% | (anonymous) /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:13
                                          479.08ms 12.48% |   zp /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:13
                                          467.35ms 12.17% |   zp /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:14
                                          126.97ms  3.31% |   RegExp: \/+ :13
                                           10.67ms  0.28% |   (anonymous) /home/ubuntu/redacted/node_modules/playwright-core/lib/utilsBundleImpl.js:1
                                            8.54ms  0.22% |   get length :13
                                            6.40ms  0.17% |   module2.exports /home/ubuntu/redacted/prettier/index.js:1607
```

**Comment by pastelsky** [comment]
The performance difference between `minimatch` and `micromatch` is relatively well known as well, with other tools such as Jest making a move —
https://github.com/jestjs/jest/pull/2338
a while back now.

**Comment by mxschmitt** [comment]
We would be happy to accept a contribution for it, if you want to take over this change, feel free to file a PR, thanks!
