### ISSUE TITLE
[Feature] How to make the the test error message to be more informative

### ISSUE THREAD

**Issue by prisma-new-user** [microsoft/playwright#24137]
I'm using screenplay pattern for our test framework implementation and I wonder what is the best way to make the test failure error on the test report to be more informative.

For example, I have the following test:

```
test('Verify that users list is visible', async ({ actor }) => {
    // note: actor is a fixture that holds a reference to the playwright `page` object
    
    // first section of the test: open users modal
    await actor.attemptsTo(Click.on('btnA'));
    await actor.attemptsTo(Click.on('btnB')); // after this line the modal is opened
    
    // second section of the test: click on button in the modal that makes user list to be visible
    await actor.attemptsTo(Click.on('btnC'));
    const isUsersListVisible = await actor.askingFor(IsVisible.element('userListXpath'));
    expect(isUsersListVisible).toBeTruthy();
});
```

What I want to achieve is that if we failed to click on btnA or on btnB then the error will be informative and will contain the context, something like: "Failed to open users modal"
And if we failed to click on btnC the error will be: "Failed to open users list in users modal"

I'm trying to avoid using try-catch for each section in the test.

Does playwright have a clean solution for it?

**Comment by prisma-new-user** [comment]
Yes I know:)
But what if I failed to click or failed to set text? I guess there is no convenient solution to that

**Comment by mxschmitt** [comment]
You could wrap it inside a [test.step](https://playwright.dev/docs/api/class-test#test-step), then it will show up inside the trace viewer, and also if its failing etc. would that work for you?

**Comment by prisma-new-user** [comment]
Yes!
I already have error reporter like [this](https://playwright.dev/docs/api/class-reporter) so I just need to listen to `onStepEnd` event and act accordingly.

Thank you very much

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions.
