### ISSUE TITLE
[BUG] click button which jump to new tab, the page visibilitychange event is not triggered.

### ISSUE THREAD

**Issue by xiaoxiaocaiiao** [microsoft/playwright#24130]
**Context:**
- Playwright Version:  1.33.0
- Operating System: windows 10
- Python version: 3.9
- Browser: All

**Describe the bug**
prepare:
a html page who has an event "visibilitychange" and one button (click can jump to new tab)
Reproduce step
 when click the button, it jumps to new tab,  the visibilitychange is not triggered.
expect：
 the visibilitychange should be triggered.

**Comment by xiaoxiaocaiiao** [comment]
> Playwright opens all the pages in a new window semantically. This is by design. You can manually dispatch the event see [#2286 (comment)](https://github.com/microsoft/playwright/issues/2286#issuecomment-1442368623).
> 
> Folding into #2286.


why it is by design, manually?  if it is by desgin, all user function on this event will be lose. not use call the funtion "hideTab", we need trigger by auto when click the tab. maybe puppeteer not have this issue, please learn from puppeteer not just a by design

**Comment by pirate** [comment]
FYI CDP now has support for getting tab foreground / focus state, tab ordering, tab pinning, and tab grouping (as of Chrome >= v150).

More info:

- https://chromium-review.googlesource.com/c/chromium/src/+/7787097
- https://www.browserbase.com/blog/cdp-foreground-tab-tracking
