### ISSUE TITLE
Quick hot fix for "Memory increases when use in same context is used" issue

### ISSUE THREAD

**Issue by vonkoff** [microsoft/playwright#24138]
We have all the feedback we need for this issue and it is currently pending due to prioritization. I'll disable the comments since they no longer add actionable details to the issue.

_Originally posted by @pavelfeldman in https://github.com/microsoft/playwright/issues/6319#issuecomment-1627432053_

Hey, 
I'm sorry if this is not the right way to do this, but I think it would really helpful to put this as a workaround for this issue. **I know you closed the comment section down because it became heated, but I would like people to still use playwright for their projects.**

```ts
const browserServer = await chromium.launchServer(launchOptions);
console.log('Browser PID:', browserServer.process().pid);

const wsEndpoint = browserServer.wsEndpoint();
const browser = await chromium.connect({ wsEndpoint });

// ... Your code ...

await browser.close();
await browserServer.close();
```

I used to recommend using `pkill -f chromium` to kill any instances of chromium that were left open. But, that didn't work with the code and it was very duct tape solution.

But, launching a browser server that client can connect to is a workaround for this. Running my program I am able to correctly close the server down. No chromium browser is left open when running `ps -e`.

**Comment by pavelfeldman** [comment]
I don't think this workaround is helpful as it does not address the problem of the growing memory when using the same context for multiple page operations. Could you elaborate on why you think it is relevant?

**Comment by mxschmitt** [comment]
Might also be related to https://playwright.dev/docs/ci#docker so you don't have an init manager if you are running inside Docker. This then by definition ends up in Chrome zombies.

**Comment by mxschmitt** [comment]
Closing as per above. Since we don't monitor closed issues, please re-file for further questions.
