### ISSUE TITLE
[BUG] 'should change document URL after redirected navigation'  is flaky in firefox

### ISSUE THREAD

**Issue by yury-s** [microsoft/playwright#24132]
[should change document URL after redirected navigation](https://github.com/microsoft/playwright/blob/19474bef78ac07f90007705fb0a6c189a3bf0a44/tests/library/browsercontext-har.spec.ts#L144) is flaky across platforms in firefox:

https://devops.playwright.dev/flakiness.html#filter_spec=should+change+document+URL+after+redirected+navigation

**Comment by aslushnikov** [comment]
Reopening since this didn't fix the flake.
