### ISSUE TITLE
[BUG] vs code extension won't launch tests

### ISSUE THREAD

**Issue by Aetet** [microsoft/playwright#24133]
**Context:**
- Playwright Version: 1.35.1
- Operating System: Linux, WSL (Windows)
- Node.js version: v16.15.1
- Visual Studio Code version: 1.73.1
- Playwright for VSCode extension version: 1.0.13
- Browser: All

**Describe the bug**
If I add one dependency in package.json - launch from vs code is not working.

Reproduce is here - just to comment https://github.com/Aetet/playwright-vscode-extension-issue/blob/master/tests/example.spec.ts#L6
And launch will work, uncomment - it'll work

If I open playwright UI then I have error:
```
require() of ES Module /home/aetetic/work/playwrightus/node_modules/typed-inject/dist/src/index.js from /home/aetetic/work/playwrightus/tests/rari-runner.ts not supported.
Instead change the require of index.js in /home/aetetic/work/playwrightus/tests/rari-runner.ts to a dynamic import() which is available in all CommonJS modules.
```

**Comment by mxschmitt** [comment]
`typed-inject` is a pure ESM package, see here: https://github.com/nicojs/typed-inject/blob/b865c8433c9ec101c1f51e16921519dd14cc7446/CHANGELOG.md?plain=1#L6

So if you change it to `type: "module"` in your package.json then it will work as expected.

**Comment by mxschmitt** [comment]
Have you tried to restart VSCode afterwards? For me it was working then.

**Comment by Aetet** [comment]
Nope. Restart won't help. Are there any logs that I could provide?

**Comment by mxschmitt** [comment]
Are you using Yarn PNP mode by any chance? I tried to install the dependencies using NPM.

So just to recap, npx playwright test --ui works, npx playwright test works, just the VSCode extension does not?

And you have [the official one](https://marketplace.visualstudio.com/items?itemName=ms-playwright.playwright) installed?

**Comment by Aetet** [comment]
If I enable "type": "module" I cannot see the green arrow to launch tests.
![image](https://github.com/microsoft/playwright/assets/3372058/11840c94-86b0-4db7-acf0-09376d476240)
Even if I disable all my code with `typed-inject`

Yes. I use the official one without any modifications.
I tried to bisect to prevent other vs code extensions interfere - no luck. 

I use yarn, but without pnp.
```
yarn --version
1.22.19
```

**Comment by mxschmitt** [comment]
My repro steps are the following:

```
git clone https://github.com/Aetet/playwright-vscode-extension-issue
cd playwright-vscode-extension-issue
rm yarn.lock
npm i
npx playwright test
// this fails
```

Then I apply this diff:

```diff
diff --git a/package.json b/package.json
index 3163bcc..7cae553 100644
--- a/package.json
+++ b/package.json
@@ -2,6 +2,7 @@
   "name": "playwrightus",
   "version": "1.0.0",
   "main": "index.js",
+  "type": "module",
   "license": "MIT",
   "devDependencies": {
     "@playwright/test": "^1.35.1"
```

And then it works. Could you try to confirm you are doing the same?

**Comment by Aetet** [comment]
Strange. it works after installing from scratch. 
Maybe you could help with some verbose mode in case that issue will repeat in the future?
