### ISSUE TITLE
[BUG] `first().waitFor()` not working with OR locators

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#24141]
### System info
- Playwright Version: v1.35.0
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

```js
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch({
    headless: false,
  });
  let page = await browser.newPage();

  await page.goto("https://playwright.dev/", { waitUntil: "load" });

  const locator = page.locator("h1").or(page.locator("button"));
  await locator.first().waitFor({ timeout: 30000 });

  await browser.close();
})();
```

**Expected**

It should wait for the first element matching `h1` or `button`.

**Actual**

It timeouts.

If I remove `.or(page.locator("button"))` it resolves to the first `h1`.

**Comment by mxschmitt** [comment]
Minimal reproducible:

```ts
import { chromium } from 'playwright';

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await page.setContent(`
    <button style="display: none;" type="button">
      Hello
    </button>
    <h1>Example Domain</h1>
  `);

  const locator = page.locator('h1').or(page.locator('button'));
  await locator.first().waitFor({ timeout: 30000 });

  await browser.close();
})();
```

**Comment by mxschmitt** [comment]
This is expected, you can do e.g. this to workaround it. First in this case refers to your button which is not visible.

```
 await locator.first().waitFor({ timeout: 30000, state: 'attached' });
```

**Comment by kblok** [comment]
@mxschmitt do you think this is expected? How do I wait for any `h1` `or` a `button` to show up on a page? 
And `or` locator should be the answer.

**Comment by mxschmitt** [comment]
We recommend then `const locator = page.locator('h1:visible').or(page.locator('button:visible'));`

**Comment by kblok** [comment]
That's pretty. Thank you @mxschmitt :)
