### ISSUE TITLE
[REGRESSION]: Snapshot styles in trace-viwer aren't loaded

### ISSUE THREAD

**Issue by fadezak100** [microsoft/playwright#24144]
**Context:**
- GOOD Playwright Version: 1.35.0
- BAD Playwright Version: 1.36.0-next
- Operating System: Tested on both Windows and MacOs

**Code Snippet**
I was running a local version of trace-viewer. I had earlier generated some `trace.zip` reports from a playwright test.  After loading the tests on the trace-viewer, I noticed that in most of the reports, snapshot styles were missing.

**Describe the bug**

When loading a `trace.zip` into the local trace-viewer package some of the snapshot styles resources aren't loaded. When inspecting the network requests I found out that all of the CSS files were returned but some of them were empty.

![missedupstyles](https://github.com/microsoft/playwright/assets/43090330/1f90e7ae-749d-4125-b3d6-932696c10feb)

The live trace viewer which is still on 1.35.0 I believe:
<img width="1509" alt="Screen Shot 2023-07-11 at 2 17 02 AM" src="https://github.com/microsoft/playwright/assets/43090330/55f0ec5d-a0f7-4f14-81e1-1eb8d3d5486e">

**Comment by dgozman** [comment]
@fadezak100 Any chance for a repro we can run locally, or a trace.zip that exhibits this issue?

**Comment by fadezak100** [comment]
@dgozman Sure the one I have right now has a LinkedIn account credentials I will try to generate one for you. Or if I can send the one I already have privately?

**Comment by dgozman** [comment]
@fadezak100 You can send it to dgozman [at] microsoft [dot] com

**Comment by fadezak100** [comment]
@dgozman sent.

**Comment by dgozman** [comment]
@fadezak100 Could you please try `@playwright/test@next` and check that trace works for you now?
