### ISSUE TITLE
[BUG] after one test fails, subsequent tests are skipped

### ISSUE THREAD

**Issue by cdcasey** [microsoft/playwright#24148]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Ubuntu 20, macOS 13.4]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/cdcasey/skip-test-repro](https://github.com/cdcasey/skip-test-repro)

Currently I have 16 tests across 5 files. Each file has its own page object and fixture. Each test block uses its corresponding page fixture. The page fixture runs through the login process, so each test block includes a fresh login. I assume this makes the tests isolated from each other. Yet if any one of the tests fails, the rest are skipped.

We're using one worker, but the order of the tests doesn't matter. So if the second test that's run fails, the results of the suite are
passed: 1
failed: 1
skipped: 14

Expected output:
passed: 15
failed: 1
skipped: 0

Update: some people suggested I try fullyParallel: true in the config or expect.soft for the test assertions. Neither changed the results.

To be sure, I'm not sure if this is a bug or if I'm misusing fixtures.

**Comment by Nav-2d** [comment]
You config has `maxFailures: 2` which means when the test is failing and then it is retried thrice then the maxFailure is triggered and subsequent tests are skipped. Removing the maxFailures will fix the issue.

https://github.com/cdcasey/skip-test-repro/blob/main/playwright.config.ts#L7

Note: maxFailures take into account the retries as well

**Comment by cdcasey** [comment]
Interesting, thanks!

Will it still retry a test in the case of a timeout?

**Comment by Nav-2d** [comment]
Yes even if you remove maxFailures setting, it will still retry a test three times.

**Comment by mxschmitt** [comment]
Thank you @Nav-2d! 🚀

**Comment by IvayloStoychev** [comment]
@Nav-2d I have very the same issue with my tests.
We have 150+ tests in 20+ test suites.
We're using 5 workers with 3 retries for failures. If some of the tests of the bottom failed on every retry no one of the tests below it its not executed and its marked as skipped.
Some example of the current and expected results is here:

Actual:
passed: 0
failed: 1
skipped: 14

Expected output:
passed: 14
failed: 1
skipped: 0

Initially we dont have `maxFailures` setup in our config, however I tried with `maxFailures: 999` but the results are the same.
Any suggestions ?
