### ISSUE TITLE
[BUG] Playwright hangs between projects with --debug flag

### ISSUE THREAD

**Issue by cameron-burris** [microsoft/playwright#24155]
### System info
- Playwright Version: 1.35.1
- Operating System: MacOS 13.4
- Browser: All

### Source 

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[Repo](https://github.com/cameron-burris/playwright-issue)

**Steps**
- Run `pnpm playwright test --debug`

**Expected**

All projects should run and pass.

**Actual**

`setup` project runs but playwright seems to hang and not proceed to next projects. This issue happens inconsistently for me, sometimes it hangs, sometimes it proceeds to the next project as expected.

When I run the command, I see the debug browser and console show up and then go away as the test passes. Then Playwright gets stuck and never proceeds to the next project. I see this in the terminal:

![image](https://github.com/microsoft/playwright/assets/118749237/016fbea3-3623-4eeb-8865-5f2c51c6993c)

If I run the command ` DEBUG=pw:api pnpm playwright test --debug` I get this output before Playwright seems to hang:
![image](https://github.com/microsoft/playwright/assets/118749237/7b71f9bf-aeb6-47a9-890f-381ddc2077dd)

If I run without the `--debug` flag, the tests seem to always work.

**Comment by mxschmitt** [comment]
I can repro.

**Comment by dgozman** [comment]
Fixed by #24376.
