### ISSUE TITLE
[BUG] TypeError: browserType.connect: Invalid character in header content ["x-playwright-launch-options"]

### ISSUE THREAD

**Issue by polozokvy** [microsoft/playwright#24157]
**Steps**
- Install playwright
- Open the Testing tab in the VSCode
- Open the Playwright menu
- Chose "Show browser" item
- Run the "example" spec

**Expected**
The browser is open and the tests are green

**Actual**

TypeError: browserType.connect: Invalid character in header content ["x-playwright-launch-options"]

![example spec ts - Untitled (Workspace) - Visual St](https://github.com/microsoft/playwright/assets/17764579/46d31462-51c8-46eb-b805-911477d3c88e)

If I run tests in the 'Show trace viewer' mode - the tests are green:
![example spec ts - Untitled (Workspace) - Visual St1](https://github.com/microsoft/playwright/assets/17764579/9aafb43e-bf2f-403b-96db-85a77cb87efe)

If I run tests in the 'headless' mode - the tests are green:
![example spec ts - Untitled (Workspace) - Visual St2](https://github.com/microsoft/playwright/assets/17764579/da932563-83dd-44b5-9247-e85da1d2ce06)

**Comment by mxschmitt** [comment]
How does your playwright.config.ts look like?

**Comment by polozokvy** [comment]
> How does your playwright.config.ts look like?

I changed nothing after installation:

import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

**Comment by polozokvy** [comment]
> Could you modify the `node_modules/playwright-core/lib/client/browserType.js` file and around line 79 where _connectInsteadOfLaunching is defined add the following?
> 
> ```ts
>     throw new Error(JSON.stringify({
>       ...this._defaultLaunchOptions,
>       ...launchOptions
>     }));
> ```
> 
> and in `node_modules/@playwright/test/lib/index.js` around line 175 put
> 
> ```ts
>   throw new Error(JSON.stringify(_browserOptions))
> ```
> 
> this should give us a clue how the header value looks like in your case which should help us to reason about the cause of it.

Here?
![Screenshot 2023-07-11 234146](https://github.com/microsoft/playwright/assets/17764579/51393260-6ee9-49aa-9775-cfa38e2612d4)
![Screenshot 2023-07-11 233957](https://github.com/microsoft/playwright/assets/17764579/435a7c21-bde3-40cf-a85a-5a6c90285968)

**Comment by mxschmitt** [comment]
In line 174,5 in the first file and line 80,5 in the second file.

**Comment by polozokvy** [comment]
![Screenshot 2023-07-12 000950](https://github.com/microsoft/playwright/assets/17764579/427c8005-fa23-47af-b023-60ab2408e07c)
![Screenshot 2023-07-12 001018](https://github.com/microsoft/playwright/assets/17764579/fdde23d6-bc5c-4c07-8dfd-11b80ad704e6)
![example spec ts - Untitled (Workspace) - Visual St](https://github.com/microsoft/playwright/assets/17764579/64c4e19c-5811-40d8-a3d7-a62ef2cda9dd)

**Comment by mxschmitt** [comment]
Thanks very helpful! We now know what the reason is, will assign it to the next release.

No further information needed from your side, thanks!

**Comment by polozokvy** [comment]
You are welcome. Could you please tell me, when the next release with the fix will be?

**Comment by polozokvy** [comment]
Thanks
