### ISSUE TITLE
[BUG] Playwright component test doesn't allow passing `null` in props (`null` is valid in JSON)

### ISSUE THREAD

**Issue by segevfiner** [microsoft/playwright#24153]
### System info
- Playwright Version: v.1.35.1
- Operating System: macOS 13.4.1
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/segevfiner/playwright-ct-null-issue

**Steps**
- Run `pnpm i`
- Run `pnpm test-ct`

**Expected**

The tests works.

**Actual**

```
  1) [chromium] › components/__tests__/HelloWorld.spec.ts:4:5 › HelloWorld ─────────────────────────

    Error: The mount function props are not JSON serializable.

      3 |
      4 | test('HelloWorld', async ({ mount }) => {
    > 5 |   const component = await mount(HelloWorld, {
        |                           ^
      6 |     props: {
      7 |       msg: null
      8 |     }

        at mount (/Users/segevfiner/junk/playwright-ct-null-issue/node_modules/.pnpm/@playwright+experimental-ct-core@1.35.1_@types+node@18.16.19/node_modules/@playwright/experimental-ct-core/lib/mount.js:49:100)
        at /Users/segevfiner/junk/playwright-ct-null-issue/src/components/__tests__/HelloWorld.spec.ts:5:27
```

Due to the `null` in the props. Although `null` is valid JSON.

**Comment by zhengjitf** [comment]
Correct me If I'm wrong.

It should be related to line 85, line 87, and line 92.

https://github.com/microsoft/playwright/blob/aeba083da0d8da9591e2a72c571477691a095d74/packages/playwright-ct-core/src/mount.ts#L81-L97

`typeof null` results in `"object"`, not `"null"`.
