### ISSUE TITLE
[Feature] Create storageState json file if it doesn't exist

### ISSUE THREAD

**Issue by bradbyte** [microsoft/playwright#24164]
I have an app that is testing multiple user roles, each storing their cookies into separate named json files for testing. I am not checking these files into git, so it seems unnecessary to create empty json files to store the data during the tests.

Here is the current behavior...
```ts
// loginAsAdmin.setup.ts

// actions to log in a user in the browser
await page.context().storageState({ path: "playwright/.auth/admin.json" });

// this will error if `playwright/.auth/admin.json` does not exist.
```

It would be nice if it could create the json file by default, or optionally add a flag that creates the file for you.

I'd be happy to create a PR for this if the functionality is approved.

Thoughts? Thank you!

-Brad

**Comment by mxschmitt** [comment]
```ts
await page.context().storageState({ path: "playwright/.auth/admin.json" });
```

This won't apply a certain storage state, it will instead write the context's storage state to disk. 

I think what you want instead to modify the place where you are loading the storage state to only add it when the file exists in your scenario. Either you do it inside your playwright.config, inside a test.use or when you do newPage/newContext. Something like e.g.:

```ts
use: {
    storageState: fs.existsSync('playwright/.auth/admin.json') ? 'playwright/.auth/admin.json' : undefined,
}
```

Would that work for you?

**Comment by mxschmitt** [comment]
> The issue is that I do not have an admin.json file before running the test so I had to manually create one before I could save the state.

What confuses me here is why do you need a admin.json file before saving it? If there is none there, it just gets created when you save.

Do you have stack traces to the error which you are getting? Maybe you do a manual newContext somewhere and need my conditional logic from above there as well.

Keep in mind, only `storageState()`  saves, passing `storageState: '...'` somewhere, does load.

**Comment by bradbyte** [comment]
I'll try and make a MRE and follow up with my findings.

**Comment by aslushnikov** [comment]
I'll close this for now, but please do not hesitate to file a new issue if/when you create a reproduction.

**Comment by mxschmitt** [comment]
This is expected, since **using** an assertion (when passed in use) will throw when there is no storage state rather than **writing** a storage state using `browserContext.storageState()` function.

**Comment by tmantis01** [comment]
What I observed is that if the _storageState_ is configured in the "global" use then, if file doesn't exist, it throws the error, **BUT** if the _storageState_ is configured in the per project then the file is  created without any problem.
I am using playwright version 1.42.1.

For example, the below will throw an error (if the file does not exist):

```
use: {
    baseURL: process.env.URL,
    storageState: STORAGE_STATE_PATH,
   }
```
   

while this will create the file if it doesn't exist:
   
``` 
projects: [
    {
      name: "chromium",
      use: { 
        ...devices["Desktop Chrome"], viewport: { width: 1920, height: 1080 },
        storageState: STORAGE_STATE_PATH,
      },
     },
```
   
In the test I am using the same line of code in both executions:

`await page.context().storageState({ path: STORAGE_STATE_PATH });`
   
   I am not sure if this is by design though.

**Comment by AlexJukes** [comment]
Just to add to this, I'm also seeing an issue where if I don't explicitly create an empty `state.json` file then my tests fail with the following error:

```
Error: Error reading storage state from state.json:
ENOENT: no such file or directory, open 'state.json'
```

If I create my own empty `state.json` file, the tests run as expected. 

The same error occurs even when I specify the file within `projects`, `use.storageState`, unlike @tmantis01 

I'm running playwright `1.42.1`

**Comment by macadamios** [comment]
Also when creating an empty `state.json` it does not work.

```
SyntaxError: browser._wrapApiCall: Error reading storage state from state.json:
Unexpected end of JSON input
```

Playwright `Version 1.56.1`
