### ISSUE TITLE
[Bug] Trace Viewer and UI mode snapshots doesn't load correctly #88451

### ISSUE THREAD

**Issue by BryantUng-at** [microsoft/playwright#24161]
### System info
- Playwright Version: [v1.35.1, I've tested on versions as old as 1.32.2 and saw this as well]
- Operating System: [macOS 13.2]
- Browser: [Chromium]
- Other info:

### Source code
I'm not able to provide exact source code, but looks related to the following bugs:
https://github.com/microsoft/playwright/issues/23709
https://github.com/microsoft/playwright/issues/24144

**Steps**
- Run a playwright test with trace set to on in the config.
- view the trace with `npx playwright show-trace trace.zip`

**Expected**
When you go back to a snapshot, it should render the page how it looks when the test was ran or what is shown in the timeline.

**Actual**
The snapshot looks broken. 
This is what the timeline view shows:
![image](https://github.com/microsoft/playwright/assets/85197799/fb704972-de9f-48aa-a360-cf38673e814d)

This is what is shown as the snapshot:
![image](https://github.com/microsoft/playwright/assets/85197799/9477cc02-0330-4fcd-b9ad-afc7b69d9c4c)

I see the following results for snapshots for both trace viewer and UI Mode.

**Comment by mxschmitt** [comment]
We unfortunately need a reproducible in order to be able to assist here. Without a reproducible, we are not able able to assist. Please re-file and follow the bug template. Thanks for your understanding!

**Comment by BryantUng-at** [comment]
@mxschmitt, can I send you a trace.zip file?  I'm not able to share our code.

**Comment by mxschmitt** [comment]
Yes this would most likely also be helpful already: maxschmitt `@` microsoft`.`com

**Comment by BryantUng-at** [comment]
@mxschmitt I actually just pulled 1.36.0 and this is fixed on that version! Closing this now!
