### ISSUE TITLE
We are not able to perform any operation in web pdf

### ISSUE THREAD

**Issue by FWDQK** [microsoft/playwright#24209]
we trying to download pdf from web but unable to perform any keyboard action  and download action on web to download or save the opened pdf

**Comment by mxschmitt** [comment]
Do you mind sharing a reproducible what you are trying to archive? Testing the PDF Viewer of a browser is not in scope for Playwright.

**Comment by FWDQK** [comment]
any other  solution two handle browser pdf  it in playwright  framework

**Comment by mxschmitt** [comment]
I guess we can fold it into https://github.com/microsoft/playwright/issues/7822, there is nothing specific for PDF testing and nothing for asserting inside them. See https://github.com/microsoft/playwright/issues/7822.
