### ISSUE TITLE
[BUG] = Error: page.goto: net::ERR_NAME_NOT_RESOLVED at https://playwright.dev/

### ISSUE THREAD

**Issue by Pooja-Goudshelwar** [microsoft/playwright#24202]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```ts
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Steps**
- I have installed Playwright and haven't changed anything, I am just trying to run the sample tests provided by Playwright.
- I installed Playwright yesterday , yesterday it was working fine, 
- Today when I am trying to run the test by using the command " npx playwright test " , I am getting issue for all major browsers. 
- I am getting error at the below line,
  await page.goto('https://playwright.dev/');
- Error: page.goto: net::ERR_NAME_NOT_RESOLVED at https://playwright.dev/
- There is an issue with page.goto , I have also tried with other examples. I am getting the same error.
- Please help to fix this as soon as possible.
- Please let me know if you need more information. Below I have attached a screen shot of the error that I am facing.

**Expected**

[It should run the tests successfully. I tried it yesterday and everything was working fine]

**Actual**

[Please view below the attached screen-shot for the error]
<img width="428" alt="image" src="https://github.com/microsoft/playwright/assets/89217750/e37200c4-c152-49e9-89ff-3fe1d9137675">

**Comment by mxschmitt** [comment]
This is a DNS issue on your side, I recommend to change your DNS server to e.g. [Google](https://developers.google.com/speed/public-dns) or [Cloudflare](https://1.1.1.1/).

**Comment by Pooja-Goudshelwar** [comment]
While working at my home network it's working fine, Thank you!
