### ISSUE TITLE
[REGRESSION]: screenshots not found due to hashcode in name?

### ISSUE THREAD

**Issue by Exoow** [microsoft/playwright#24203]
**Context:**
- GOOD Playwright Version: 1.35.1
- BAD Playwright Version: 1.36.0

**Describe the bug**

All our tests with screenshots are failing because the test now seems to search for screenshot files containing a code.
Previously this wasn't the case.

You can see here the existing image, and the new image generated by the failing test.

![image](https://github.com/microsoft/playwright/assets/18096566/0a91d9d9-63f7-452e-9e49-4a30143c926f)

**Comment by stevebaxter** [comment]
See also #24184

**Comment by Exoow** [comment]
Ah, missed that one. Duplicate, my bad.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/24184
