### ISSUE TITLE
[BUG] request.newContext is undefined when it wasn't previously

### ISSUE THREAD

**Issue by perezdev** [microsoft/playwright#24208]
This was working previously and no changes were made, as far as I am aware. Is there some configuration or anything that could affect this? I also updated to the latest playwright, just in case.

<img width="551" alt="Screenshot 2023-07-12 162024" src="https://github.com/microsoft/playwright/assets/3408775/01032ed5-95ae-49cd-a0ed-786fb9195105">

### System info
- Playwright Version: [v1.36]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

### Source code

```
public async SendFormAsync(endpoint: string, form): Promise<APIResponse> {
	const ctx = await request.newContext({ baseURL: this.apiUrl });
	const headers = {
		"Content-Type": "application/x-www-form-urlencoded"
	};
	const response = await ctx.post(endpoint, { headers: headers, form: form });

	return response;
}
```

**Steps**
- [Run the test]

**Expected**

For newContext to not be undefined

**Actual**

newContext is undefined

**Comment by mxschmitt** [comment]
Do you mind sharing a full reproducible with us? Otherwise we can't act on it, thanks for your understanding!

**Comment by perezdev** [comment]
I'm using the latest version. I just put the wrong value. I'll see if I can put together an example.

**Comment by perezdev** [comment]
@mxschmitt here is a zip with the test. I set up a demo project with nothing but the default values and you can see that **newContext** is undefined.
![image](https://github.com/microsoft/playwright/assets/3408775/ae3b721e-c701-4124-a9b5-9874c81c684f)

[newRequestTest.zip](https://github.com/microsoft/playwright/files/12044720/newRequestTest.zip)

**Comment by mxschmitt** [comment]
Thanks for your repro! I was unfortunately not able to repro. What I did was the following. Download your zip file, deleted node_modules (for security reasons), npm i again, open VSCode, debug the test.

Which Node.js version are you using? Does it only happen when you debug, does a console.log(request) and npx playwright test also surface this issue?

**Comment by perezdev** [comment]
Thank you for your assistance. Looks like it was due to my node version. I'm pretty sure, at least. I updated to the latest version from 16 and it worked suddenly. Thanks again.
