### ISSUE TITLE
[Feature] Support for PaymentRequest dialog interactions

### ISSUE THREAD

**Issue by BDQ** [microsoft/playwright#2420]
I've been trying to automate the PaymentRequest API dialog (see below), while using PersistentContext I can launch Chromium with the data needed to get the dialog to appear, but actually interacting with the dialog appears to be impossible.

I've tried listening for `dialog` events, and digging through the debug logs to see if there's anything I can uncover to no avail. Happy to make a contribution here if this is likely something that Playwright can support?

![image](https://user-images.githubusercontent.com/22470/83330943-8643d380-a28a-11ea-9c1f-5d36e6e06755.png)

Thanks for an amazing project!

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
