### ISSUE TITLE
[Feature] Add iPhone 14 family

### ISSUE THREAD

**Issue by JonahKK** [microsoft/playwright#24214]
I'd love to add iPhone 14 family to devices. I was already looking at `packages/playwright-core/src/server/deviceDescriptorsSource.json`, but I have a question. In the internet you can find `viewport` which is labeled as `screen` in the JSON.
So my questions are where I can get the viewport and why there is a difference?

**Comment by mxschmitt** [comment]
Usually we created the specific device via the Xcode device emulator and went to e.g. https://whatismyviewport.com or just used the WebKit developer tools to evaluate `window.screen`.
