### ISSUE TITLE
[Question] How are Playwright commands enqueued?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#24228]
So I was curious on how Playwright commands are actually queued up. Obviously most (or all?) Playwright commands are async but they run in a synchronous fashion. I know Cypress sort of "wraps" up all the commands to be queued in order (Like one big Promise.all or something?) but I am curious if this is how Playwright works too.

What actually is the mechanism for how all these async tasks run synchronously? Also I assume if we put some sort of synchronous command (Like a simple `console.log`) will it run first?

Thanks!

**Comment by mxschmitt** [comment]
They are not _enqueued_ like in other solutions. Playwright is a regular JavaScript program, it works with Promises async/await like a normal JavaScript/Node.js program behaves.
