### ISSUE TITLE
[Feature] New GenericAssertions - toBeOneOf and toContainOneOf

### ISSUE THREAD

**Issue by mjeruzal427** [microsoft/playwright#24232]
Hello, could you please introduce more assertions to make it easier to compare two arrays or data against array. I was thinking about comparison methods similar to .oneOf() and .contains.oneOf() known from Chai assertions library.

It could look like this:

### toBeOneOf

Compares if the value is a member of an `expected` array.

**Usage**
```
const value = 2;

expect(value).toBeOf([1, 2, 3]);
```

**Arguments**
- `expected` Array - the expected array to match against.

### toContainOneOf

Compares if the array contains at least one of the members of `expected` array.

**Usage**
```
const value = [2, 3, 4, 5];

expect(value).toContainOneOf([1, 2]);
```

**Arguments**
- `expected` Array - the expected array to match agains

**Comment by mxschmitt** [comment]
You can do this as of today: `expect([1, 2, 3]).toContain(1);` since Playwright uses Expect's matchers see [here](https://playwright.dev/docs/api/class-genericassertions#generic-assertions-to-contain-2).

For the second use case you could do the following for now:

```ts
  for (const valueToCheck of [1, 2])
    expect([1, 2, 3]).toContain(valueToCheck);
```

Would that work for you?

**Comment by mjeruzal427** [comment]
Hi @mxschmitt, 

As for the first example, `expect([1, 2, 3]).toContain(1)` is what I use now as a workaround, but it's not ideal as we switch places of actual and expected data. In case of any assertion failures the errors may be confusing because of that.

Regarding second example, that does not work for me. In your case we expect that array contain both 1 AND 2, but in my case I expect array should contain either 1 OR 2.

**Comment by helgefredheim** [comment]
@mjeruzal427 Did you find a solution to this? I have the same issue: I have a text string that I expect to contain either `"foo"` or `"bar"`.

**Comment by mjeruzal427** [comment]
@helgefredheim if I understood your problem correctly, for string assertions you can use stringMatch/toMatch method with a valid regular expression:

```
test('foo or bar', async () => {
    const s1 = 'The elephant\'s footprint was enormous.';
    const s2 = 'The bartender served a refreshing cocktail';

    // using stringMatching() - https://playwright.dev/docs/api/class-genericassertions#generic-assertions-string-matching
    expect(s1).toEqual(expect.stringMatching(/.*(foo|bar).*/));
		
    // or shorter, using toMatch() - https://playwright.dev/docs/api/class-genericassertions#generic-assertions-to-match
    expect(s2).toMatch(/.*(foo|bar).*/);
});
```

**Comment by helgefredheim** [comment]
thanks @mjeruzal427, I will try this!

**Comment by jim-meyer** [comment]
I second the need for something like, `toBeOneOf()` or `toContainOneOf()`. Relying on regexes for this functionality can turn otherwise simple assertions into complex and indecipherable regexes that are hard to produce much less maintain.
An example:
```
const URL1 = 'https://mysite.com/loginLandingPage?someContext=blahblahblah';
const URL2 = 'https://<<<some Auth0 application ID>>>.us.auth0.com/';
...
expect(page.url()).toBeOneOf([URL1, URL2]);
```
Trying to do that with regex is... well honestly, I don't know how one could do that with regex. Even if it *can* be done it is not going to be as succinct and maintainable as `toBeOneOf()` or `toContainOneOf()`.

**Comment by wendys-cats** [comment]
I would like to add that this feature would be a game changer for tests with requests where one of two values (f.e. string or null, etc) can be expected in the response.

**Comment by zahmed-mdsol** [comment]
Would like this as well, helps when asserting response status codes, when they can be either 200 or 201

**Comment by Skn0tt** [comment]
We discussed this in our team meeting. We thought about existing ways you can achieve this without much hassle:

- Instead of `expect(value).toBeOf([1, 2, 3]);`, do `expect([1, 2, 3]).toContain(value);`
- Instead of `expect(value).toContainOneOf([1, 2]);`, do `expect(value.find(i => [1, 2].includes(i))).not.toBeUndefined()`

We're mindful of not overloading Playwright's API surface, so we'd prefer not adding new assertions here if easy workarounds exist. Closing, thanks for your understanding!

**Comment by mgladdish** [comment]
Disappointed to see this de-scoped.

I'm new to Playwright and pretty much the first thing I needed to do is check whether a value in a promise is one of two values. Switching the expected and actual is really icky - knowing which is the value I actually get vs the value I expect to get is about the most fundamental thing to a test, and the recommended approach is to muddle the two.

Something else I'd expect to see would be a way of combining assertions - would that be a more acceptable approach? E.g. 
```expect(myLocator).toContainText('expectedValue').or(anotherLocator).toContainText('otherExpectedValue')```

**Comment by JimBarrisGSC** [comment]
If it's useful to anyone still following the thread, here's a couple things I have made use of to work around the absence of those assertions.
For "beOneOf" type checks:
objectName.forEach((obj) => { expect([123, 456, 789]).toContain(obj.keyName); });

For "containOneOf" type checks:
objectName.forEach((obj) => { expect(['valueA', 'valueB'].some((item) => obj.keyName.includes(item))).toBe(true);  });

Again, don't know if anyone is still looking at solutions for this, but maybe these help someone :)

**Comment by ladiza** [comment]
I am sorry, but this is not how the assertion should read in the report? The workarounds are suboptimal.

<img width="1180" height="362" alt="Image" src="https://github.com/user-attachments/assets/a5850913-65ac-4a26-b836-5a271c934c8a" />
