### ISSUE TITLE
Playwright not able to find tests in subfolders.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#24233]
### System info
- Playwright Version: 1.36.0
- Operating System: Windows 11
- Browser: All
- Other info: Installed playwright extension for vs code.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: `${process.env.PWD}/tests`,
  testMatch: [/.*\.(e2e|spec|test)\.(js|ts)/],
...
```

**Steps**
- Have test files in folder path `tests/folder1`. Eg: `tests/folder1/testfile.spec.ts`
- Run tests with `npx playwright test`.

**Expected**

To run tests in `folder1`.

**Actual**

No tests found. If I move the file under `tests` folder then they are run. Is it not possible for playwright to find files within subfolders?

**Comment by ltsuda** [comment]
https://playwright.dev/docs/api/class-testproject#test-project-test-match

Could you try:

```javascript
testMatch: [/**/*\.(e2e|spec|test)\.(js|ts)/]
```
or something like this, but maybe I did it wrong.

**Comment by quldude** [comment]
> 

that didnt work.

**Comment by mxschmitt** [comment]
`process.env.PWD` is not defined on Windows since its not a standardised env var. You can either use `path.join(process.cwd(), 'tests')` or what we usually prefer just passing `tests/` which then is relative to your configuration file. Thats most likely the reason no tests get found.

Could you try that?

**Comment by charlotte-hayes** [comment]
@mxschmitt I had the same issue and your solution worked for me.

**Comment by quldude** [comment]
doesn't work for me.

playwright config file update:
```
testDir: "tests/",
```

folder structure:
```
playwright.config.ts
tests/folder1/testfile.spec.ts
```

**Comment by quldude** [comment]
Finally found the cause. It looks like if the folder path is using OneDrive, tests in subfolders are not found.

Eg: if path is `C:\Users\jsmith\OneDrive\Desktop\project\tests\folder1\testfile.spec.ts` then tests in subfolders not listed. If path is `C:\Users\jsmith\project\tests\folder1\testfile.spec.ts` then tests are found.

this ticket can be closed if this is a known issue.

**Comment by aslushnikov** [comment]
@quldude it looks like OneDrive has special permissions that don't allow programmatic traversal of the file system, thus the behavior.

Thank you for documenting your finding here; it'll be helpful for others.
