### ISSUE TITLE
[REGRESSION]: No Test Found #16982

### ISSUE THREAD

**Issue by sshadmand** [microsoft/playwright#24244]
**Context:**
Same situation as https://github.com/microsoft/playwright/issues/16982
- Installed Extension
- Installed Playwright
- Using created template generated from install I am able to run manual tests via console. 

**Describe the bug**

- No play button to run code inline
- No tests fond message
- Record new from extension panel does not resolve in toast

![Screenshot 2023-07-14 at 5 12 38 PM](https://github.com/microsoft/playwright/assets/68735/f74db14d-9c10-4622-8869-6986b370de9b)
![Screenshot 2023-07-14 at 5 11 24 PM](https://github.com/microsoft/playwright/assets/68735/7e26b96e-f4b9-40ec-a596-0163b6d92785)

Per the OP of the other ticket, I disabled all my extensions except for Playwright, and have updated Playwright and VS code to the latest version as of today. I have also restarted VSCode several times throughout. 

VCode Version: 1.80.1 (Universal)
Node v16.16.0
```
  "devDependencies": {
    "@playwright/test": "^1.36.1"
  }
```
MacOS M1: 13.4.1

**Comment by aslushnikov** [comment]
@sshadmand what is your VSCode Playwright extension version?

**Comment by aslushnikov** [comment]
@sshadmand this is not actionable unless we can reproduce this, so I'll have to close this. However, do not hesitate to file a new issue if you think we still can be helpful!
