### ISSUE TITLE
[BUG] Browser.CloseAsync takes 30 seconds for Chromium

### ISSUE THREAD

**Issue by hakito** [microsoft/playwright#24240]
**Context:**
- Playwright Version: 1.35.0
- Operating System: Windows 10 Pro 22H2
- .NET version: 4.8
- Browser: Chromium

**Code Snippet**

```cs
using System;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.Playwright;

namespace PlaywrightBrowserCloseBug
{
    internal class Program
    {
        public async static Task Main(string[] args)
        {
            var sw = Stopwatch.StartNew();
            var pw = await Playwright.CreateAsync();
            Console.WriteLine($"Playwright started within {sw.Elapsed.TotalSeconds:N0} seconds");
            sw.Restart();
            var chromium = await pw.Chromium.LaunchAsync(new BrowserTypeLaunchOptions() {Headless = false});
            Console.WriteLine($"Chromium started within {sw.Elapsed.TotalSeconds:N0} seconds");
            sw.Restart();
            await chromium.CloseAsync();
            Console.WriteLine($"Chromium closed within {sw.Elapsed.TotalSeconds:N0} seconds");
        }
    }
}
```

**Output**
> Playwright started within 1 seconds
> Chromium started within 0 seconds
> Chromium closed within 30 seconds

**Describe the bug**

Closing a chromium browser takes 30 seconds. I can also see that the process remain for 30 seconds. When I do the same with Microsoft Edge it immediatly closes the browser.

**Comment by aslushnikov** [comment]
It looks like the discussion has stalled, so I'll close this.

Please feel free to re-file a new issue if you think we still can be helpful!

**Comment by hakito** [comment]
Closed after 4 days? 

I made a survey in my company. No issues in Win 11. only on win 10 machines.

**Comment by hakito** [comment]
@mxschmitt Here is a list of Tests I did in my company (and outside):

Win 11 Home 22H2 (22621.1992) unmanaged: 1s
Win 11 Pro 21H2 (22000.1817) Domain managed: 1s
Win 11 Pro 22H2 (22621.1992) Domain managed: 1s
Win 10 Pro 22H2 (19045.3208) Domain managed: 30s
Win 10 Pro 22H2 (19045.3208) unmanaged: 30s

No 3rd party virus scan (only Microsoft Defender). No special security policies.

**Comment by aslushnikov** [comment]
@hakito I'm sorry for your experience, but it doesn't look like we can do much here. Playwright doesn't depend anywhere on any Windows APIs.

The best I can suggest is reporting this behavior upstream to https://crbug.com/new.

**Comment by hakito** [comment]
Well the hint, that it's probably not caused by Playwright pointed me to the right direction.

I simply tried running the chrome.exe without playwright at and the processes also didn't close. 

We are also using another test automation tool _Ranorex_. I noticed that there was a subprocess _Ranorex.Plugin.ChromeMsgHost.exe_. It seems that this prevented the chromium instances from exiting.
