### ISSUE TITLE
[BUG] "Decorators must be placed after the 'export' keyword"

### ISSUE THREAD

**Issue by matthiasferch** [microsoft/playwright#24248]
### System info
- Playwright Version: 1.36.0
- Operating System: Windows
- Browser: All

I wrote a test to verify that my Angular routes are loaded properly.

### Source code

**components.ts**
```ts
@Component({
  selector: 'app-access-denied',
  templateUrl: './access-denied.component.html',
  styleUrls: ['./access-denied.component.scss']
})
export class AccessDeniedComponent {
  /**/
}

@Component({
  selector: 'app-not-found',
  templateUrl: './not-found.component.html',
  styleUrls: ['./not-found.component.scss']
})
export class NotFoundComponent{
  /**/
}
```

**routes.ts**
```ts
export const platformRoutes: Routes = [
  {
    // access denied
    path: 'access-denied',
    component: AccessDeniedComponent
  },
  {
    //not found
    path: 'not-found',
    component: NotFoundComponent
  },
  /**/
];
```

`playwright.config.ts` is unchanged from installation.

**Test file (self-contained)**

```js
platformRoutes.forEach(async (route) => {
  let url = route.path;

  test(`Navigate to ${url}`, async ({ page }) => {
    await page.goto(url);

    // make sure we navigated to requested url
    await expect(page).toHaveURL(new RegExp(url));

    const pageContent = page.locator('.platform-content');

    // make sure content is present
    expect(pageContent).toHaveCount(1);

    // make sure there's content besides the router outlet
    const childElementCount = await pageContent.evaluate((el: HTMLElement) => {
      return el.childElementCount;
    });

    expect(childElementCount).toBeGreaterThan(1);
  });
});
```

When running the test, I receive the following error message:

```
[...]\not-found-page\not-found-page.component.ts: Decorators must be placed *after* the 'export' keyword. Remove the 'decoratorsBeforeExport: false' option to use the '@decorator export class {}' syntax.
```

It seems that Playwright doesn't know how to handle Angular's `@Component` decorator. I tried moving the `export` keyword before the decorator - that eliminates the error message but then the test isn't listed in the Playwright UI at all.

From what I understand, `decoratorsBeforeExport` is a Babel config setting. Is it possible to adjust those on a project basis?

**Comment by aslushnikov** [comment]
@matthiasferch Indeed, Playwright doesn't know how to handle Angular's `@component` decorator. Why do you import it in your tests, though? This seems to be a part of your web site, while your test looks like an end-to-end test.

**Comment by matthiasferch** [comment]
> Why do you import it in your tests, though? 

I was trying to fetch the route definitions directly from Angular so that every route I define is automatically tested.

**Comment by aslushnikov** [comment]
>  Or will I have to redefine the routes in a separate, decorator-free file?

@matthiasferch this would be the simplest way to make it work.

**Comment by aslushnikov** [comment]
Closing this as per above. Please do not hesitate to file new issues if you think we still can be helpful!

**Comment by Gennadiii** [comment]
@aslushnikov have the same issue. But I wanna use decorators in my tests source code. I assume I'm the only one and no one is gonna look into it?

**Comment by leggomuhgreggo** [comment]
I am also seeing this.

**Comment by j-sawtooth** [comment]
allowing decorators would also help us. We're referencing some components with decorators and redefining things in a separate, decorator-free structure for the tests could be a pain.

**Comment by Deohgu** [comment]
> Or will I have to redefine the routes in a separate, decorator-free file?

This does work. Though, I'd consider this more of a workaround which reduces the priority of this bug being fixed.  
But would still rather to be able to access the file with the decorator.  

In my use case, I am was defining a constant as a static attribute in a component class, which I prefer as said attribute is specific to said class.  
Ended up defining the constant in the model files of said class component, `foobar.component.model.ts`. Which still feels correct.
