### ISSUE TITLE
[BUG] [VSCODE] Jump to code from test results by Ctrl+Click doesn't work

### ISSUE THREAD

**Issue by longmaxx** [microsoft/playwright#24253]
### System info
- Playwright Version: [v1.36.0]
- Operating System: [Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: VSCode 1.80.1, 1.81.0-insider, plugin playwright test for VSCode 1.0.14

**Steps**
- [Run the test throwing error]
- Open test results viewer in vs code (see picture)
- Try Ctrl+Click on call stack for the error
**Expected**

We jump to source code line

**Actual**
Nothing hapened.
It stopped to work ~ a week ago, I guess. But used to work in  vs code insider build.
But today is stopped to work in the insider build too. (monday, 17.07.2023)

![image](https://github.com/microsoft/playwright/assets/11839300/4d52aa92-1cde-4c74-b021-ce106268bce8)

**Comment by mxschmitt** [comment]
Does it work in VSCode stable? Then I recommend filing it at https://github.com/microsoft/vscode

**Comment by longmaxx** [comment]
Doesn't work on latest VSCode stable too (1.80.1) But work on downgraded version (1.79.2).
Will create an issue in vscode repo.

**Comment by mxschmitt** [comment]
Closing this here then.
