### ISSUE TITLE
[REGRESSION]: "Show browser" on WSL2

### ISSUE THREAD

**Issue by pixilation** [microsoft/playwright#24254]
**Context:**
- GOOD Playwright Version: playwright-vscode v1.0.13
- BAD Playwright Version: playwright-vscode v1.0.14
- Operating System: Windows 11 using WSL2 with Ubuntu 22.04
- Extra: [any specific details about your environment]

**Describe the bug**

When using the Playwright plugin for VSCode it used to allow the "Show browser" option and everything just seemed to work. The browser window that opened was styled by WSL2, but these things worked:

- ✅ "Pick locator" functioned perfectly
- ✅ If the cursor was on a locator in VSCode then matching elements were highlighted in the browser window
- ✅ The browser window remained open after tests were run, allowing test development to continue

Now in v1.0.14 I get the alert "Show browser mode does not work in remote vscode", and all the above functionality is gone:

- ❌ "Pick locator" functioned perfectly
- ❌ If the cursor was on a locator in VSCode then matching elements were highlighted in the browser window
- ❌ The browser window remained open after tests were run, allowing test development to continue

I can still see the same browser window that Playwright opens, but VSCode no longer has any integration with it.

This appears to be caused by https://github.com/microsoft/playwright-vscode/commit/d6881ef874f94f499a2be8f70e2d978e0babc847.

**Comment by fabioParis75** [comment]
I got the same :(

![image](https://github.com/microsoft/playwright/assets/139774823/ffabec00-4283-4dbf-87c2-a27c1c2e35e1)

**Comment by gage22171** [comment]
Yep, I'm trying to run in a Docker container. I get the error above.

**Comment by gl-aagostino** [comment]
Yes, this used to work just fine if you used GWSL..

**Comment by Taskle** [comment]
Same, this was a hugely useful feature, really painful if it is being disabled...

**Comment by pixilation** [comment]
Here's a workaround so people can keep working while this gets fixed:

 * Open VSCode extensions (Ctrl+Shift+X)
 * Search for "Playwright Test for VSCode"
 * Right click "Playwright Test for VSCode" or click the gear icon
 * Select "Install Another Version..."
 * Select 1.0.13

**Comment by yugawara** [comment]
> * 1.0.13

Or in my case, I have just modified the devcontainer.json like :
    "customizations": {
        "vscode": {
            "extensions": [
                "ms-playwright.playwright",

**Comment by yugawara** [comment]
I think you meant 1.0.15 - thank you so much!!! :-)
