### ISSUE TITLE
[Feature] Support Socks5 with auth

### ISSUE THREAD

**Issue by ordimans** [microsoft/playwright#2425]
Let us know what functionality you'd like to see in Playwright and what is your use case.
Do you think others might benefit from this as well?

Hello,

It's possible to use Socks 5 with authentification in the future with playwright.
And without auth ?
With puppeteer, with puppeteer-page-proxy is possible.

Thanks you

**Comment by pavelfeldman** [comment]
I am currently working on the proxy support across the browsers. I don't think Chromium itself supports socks5 w/ auth, so we'll only support http(s) w/ auth and noauth socks5. I have it working pretty much across the board.

It should be relatively easy to proxy socks5 and apply auth on top of it with a small man in the middle program, so we'll either do it or leave it as an exercise for the reader. Could you share more about your use case? I.e. which kind of proxy you need and why?

It should also be very easy to make `puppeteer-page-proxy` work in Playwright - we have all the capabilities for it, but my recollection is that it is based on the request interception, so it won't really work for web sockets, streams, etc. So I'd wait for the real proxy support.

**Comment by ordimans** [comment]
Need it to change IP during the playing game, because it's address limited.

You are right, about request interception, is not the best.
But maybe i can try with external proxy on the machine, who change the socks5 proxy every minutes.
Don't know if possible.

And if auth is not supported, maybe can use a gateway to make a socks proxy without auth in the local machine, and use auth on the final proxy.
nodeJs >> socks5 proxy without auth on local machine who use a socks5 with auth.

**Comment by shirshak55** [comment]
@ordimans What i did was wrote a rust program that works like this


Chrome  ----  Rust based Proxy  --------- Socks Proxy


And chrome or client connects to rust proxy and rust proxy connects to socks proxy. As this feature may take long time to land i guess it would be best for you. 


If you want you can check it. It should be cover your use case. 
https://github.com/shirshak55/http-to-socks

**Comment by ordimans** [comment]
@shirshak55 
Thanks you, it's the solution which i would like to try with a gateway...

I will check your link, i think it can be resolve my problem.
Need rotate between socks5 proxy with auth.

**Comment by shirshak55** [comment]
@ordimans  you don't need to run rust because they are binaries just like normal programs.

Regarding rotation you should have multiple ips and if they are different/same auth also it doesn't matter. 

if you need more help instead of discussing here we can discuss on email. (Its on github.)

**Comment by ordimans** [comment]
> I am currently working on the proxy support across the browsers. I don't think Chromium itself supports socks5 w/ auth, so we'll only support http(s) w/ auth and noauth socks5. I have it working pretty much across the board.
> 
> It should be relatively easy to proxy socks5 and apply auth on top of it with a small man in the middle program, so we'll either do it or leave it as an exercise for the reader. Could you share more about your use case? I.e. which kind of proxy you need and why?
> 
> It should also be very easy to make `puppeteer-page-proxy` work in Playwright - we have all the capabilities for it, but my recollection is that it is based on the request interception, so it won't really work for web sockets, streams, etc. So I'd wait for the real proxy support.

You didn't answer some weeks ago with the new release which support proxy ?
I didn't find the answer....
Did i dream ?

**Comment by shirshak55** [comment]
@ordimans  latest release does support socks proxy with username and password. see docs.

**Comment by dgozman** [comment]
See `proxy` option [in the docs](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=browsernewcontextoptions--options-proxy).

**Comment by zdm** [comment]
@dgozman 
Hmm, you wrote here, that it is supports socks5 with auth now, but in fact this is not works.
And in this issue https://github.com/microsoft/playwright/issues/5325 you tells, that socks5 auth is not directly supported.
Could you clarify, please?

**Comment by dgozman** [comment]
@zdm Sorry for confusion.

- socks5 with authentication is not supported by our browsers.
- socks4 does not support authentication at all.
- http/https proxies are supported with and without authentication.
