### ISSUE TITLE
[BUG] UI Mode: page inside the snapshot tab doesn't load styles

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#24255]
### System info
- Playwright Version: [v1.36.0, v1.36.1]
- Operating System: [macOS]

 **It works fine in v1.35.1**  

## Starting from v1.36.0 it looks like this in the snapshot tab:

<img width="1025" alt="Screenshot 2023-07-17 at 12 10 15" src="https://github.com/microsoft/playwright/assets/526352/71a74267-a70b-4e46-971f-adb5dbd5e355">

## And looks ok in the timeline view:

<img width="981" alt="Screenshot 2023-07-17 at 12 10 05" src="https://github.com/microsoft/playwright/assets/526352/86998c3d-cef7-4c7f-9b31-9a2eabf08785">

**Comment by e-oz** [comment]
It’s not related to any test, so there is no need for repro. The only possible thing about configuration - the server runs on localhost.

**Comment by aslushnikov** [comment]
@e-oz could you please share a trace file with us? This way we'll have a chance to debug what's going on.

**Comment by e-oz** [comment]
@aslushnikov I've shared it using this repo: https://github.com/e-oz/tmp-pw-trace/ (just one file there)

**Comment by aslushnikov** [comment]
Isolated reproduction: https://gist.github.com/aslushnikov/e4840dde104f8111e85bf60be8320f56

**Comment by e-oz** [comment]
Thanks a lot!
