### ISSUE TITLE
[BUG] Gatsby/ localhost webServer ECONNREFUSED error 

### ISSUE THREAD

**Issue by carinaluise** [microsoft/playwright#24256]
### System info
- Playwright Version: [v1.XX] "@playwright/test": "^1.36.1",
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]   MacOS 13.4.1
- Browser: [All, Chromium, Firefox, WebKit] Chromium
- Other info:

Currently trying to set up the webServer so that I can run the tests on localhost (Gatsby project), but getting the following error:

```
  pw:webserver HTTP GET: https://localhost:8000/ +1s
  pw:webserver Error while checking if https://localhost:8000/ is available: connect ECONNREFUSED 127.0.0.1:8000 +302ms
```

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const { defineConfig, devices } = require('@playwright/test');

module.exports = defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://127.0.0.1:8000',
    trace: 'on-first-retry',
  },
  timeout: 100000,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  webServer: {
    command: 'yarn start',
    url: 'https://localhost:8000',
    reuseExistingServer: !process.env.CI,
  },
});

```

Also tried without the `reuseExistingServer: !process.env.CI,`

Package.JSON scripts object:

```
 "scripts": {
    "develop": "gatsby develop",
    "start": "gatsby develop",
    "build": "gatsby build",
    "serve": "gatsby serve"
}
```

**Expected**

[Describe expected behavior]

To successfully run localhost8000 and run test against the localhost.

**Actual**

```
  pw:webserver HTTP GET: https://localhost:8000/ +1s
  pw:webserver Error while checking if https://localhost:8000/ is available: connect ECONNREFUSED 127.0.0.1:8000 +302ms
```

**Comment by hect1c** [comment]
I'm having the same issue for Nextjs and wondering how you solved this?
