### ISSUE TITLE
[BUG] - Element is Unstable even after long wait. 

### ISSUE THREAD

**Issue by msabya** [microsoft/playwright#24262]
Error Description - Screen is keep moving up and down. Following error is thrown

Detail Error from the logs
waiting for getByTestId('actions-7').getByTestId('button-anchor')

locator resolved to <button type="button" id="button-anchor" class="css-16nx…>…</button>

attempting click action

waiting for element to be visible, enabled and stable

forcing action

element is visible, enabled and stable

scrolling into view if needed

done scrolling

performing click action

click action done

waiting for scheduled navigations to finish

navigations have finished

### System info
- Playwright Version: [v1.XX] "@playwright/test": "^1.35.1"
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]MacOS
- Browser: [All, Chromium, Firefox, WebKit]chrome
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
table contain a set of rows. Each row has a modal dialogue box. by clicking on the modal dialogue box a menu should appear with label as "Re-award base". Since there are many rows scrolling has been implemented.
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

Expected the row element should be clicked and open the modal dialogue box.
But actually the screen keep moving up and down saying the element is unstable

**Comment by aslushnikov** [comment]
Hey @msabya,

This is not actionable without a reproduction that we can run locally to debug this behavior. Please, file a new issue with a repro!
