### ISSUE TITLE
[Question] How can we touch a button on screen ?

### ISSUE THREAD

**Issue by ordimans** [microsoft/playwright#2426]
Hello

I have a mobile website, with a tap button, and with puppeeter i used :

`await page.touchscreen.tap(300,720)`

But on Playwright, i don't know how can i do ?

With click on element is not working, with page.click and position, nothing....

Thanks you in advance

**Comment by roune** [comment]
I am also interested in this feature because it is essential on my project. It worked perfectly on Puppeteer but I do not know how difficult it would be to import on Playwright.

**Comment by dgozman** [comment]
Playwright v1.6 introduced [`page.tap`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=pagetapselector-options) and [`page.touchscreen`](https://playwright.dev/#version=v1.6.2&path=docs%2Fapi.md&q=pagetouchscreen).
