### ISSUE TITLE
[QUESTION] How to open a link in a new tab?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#24260]
I have a link on a page, how to open it in a new tab?

**Comment by ltsuda** [comment]
See if this helps https://playwright.dev/docs/pages#handling-new-pages

**Comment by gauravgandhi1315** [comment]
@ltsuda It does not say how to open a link in a new tab

**Comment by gskierk** [comment]
https://playwright.dev/docs/api/class-locator#locator-click

```js
await locator.click({ button: 'middle' })
```

**Comment by aslushnikov** [comment]
@gauravgandhi1315 you can also get link's URL and then use `newPage()` method together with subsequent `page.goto()` to the desired URL. 

Hope this helps!
