### ISSUE TITLE
[Question] Dynamic test parametrisation 

### ISSUE THREAD

**Issue by unickq** [microsoft/playwright#24273]
### System info
- Playwright Version: [v1.36.1]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

https://playwright.dev/docs/test-parameterize#create-tests-via-a-csv-file

Example with reading CSV file and generating tests out of it works perfectly fine

```typescript
import { test } from "@playwright/test";
import * as fs from "fs";
import { parse } from "csv-parse/sync";

const records = parse(fs.readFileSync("input.csv"), {
  columns: true,
  skip_empty_lines: true,
});

for (const record of records) {
  test(`foo: ${record.test_case}`, async () => {
    console.log(record.test_case);
  });
}
```
with a result 
```
Running 4 tests using 1 worker

  ✓  1 debug.spec.ts:12:7 › foo: value 1 (9ms)
value 1
  ✓  2 debug.spec.ts:12:7 › foo: value 2 (6ms)
value 2
  ✓  3 debug.spec.ts:12:7 › foo: value 3 (4ms)
value 3
  ✓  4 debug.spec.ts:12:7 › foo: value 4 (2ms)
value 4

  4 passed (184ms)
```

But when I do the same with sync fetch 

```typescript
import { test } from "@playwright/test";
import _fetch from "sync-fetch";

const json = _fetch("https://random-data-api.com/api/v2/users?size=2&is_xml=true").json();
for (const data of json) {
  test(`bar: ${data.uid}`, async () => {
    console.log(data.uid);
  });
}
```
it comes to
```bash
Running 2 tests using 1 worker


  ✘  1 debug.spec.ts:6:7 › bar: 440fe159-3301-4985-ad8e-a9026bcd49af (0ms)
  -  2 debug.spec.ts:6:7 › bar: 81921e9c-2ef9-4999-bf9d-d1ef0f83ee31


  1) debug.spec.ts:6:7 › bar: 440fe159-3301-4985-ad8e-a9026bcd49af ─────────────────────────────────

    Test(s) not found in the worker process. Make sure test titles do not change:
     > debug.spec.ts > bar: 440fe159-3301-4985-ad8e-a9026bcd49af
     > debug.spec.ts > bar: 81921e9c-2ef9-4999-bf9d-d1ef0f83ee31

  1 failed
    debug.spec.ts:6:7 › bar: 440fe159-3301-4985-ad8e-a9026bcd49af ──────────────────────────────────
  1 skipped
```

What is wrong here? Why is the test title error thrown in this case and not in the previous one?

**Comment by aslushnikov** [comment]
@unickq Playwright will run this `fetch` at least twice:

- once when we're reading all the tests
- second time when the worker is actually running the test in a new process

So it looks like your fetch request returns different data when called multiple times. Could it be the case?

**Comment by unickq** [comment]
> So it looks like your fetch request returns different data when called multiple times. Could it be the case?

Yep, the data on that API is different on every call. That explains everything, thanks @aslushnikov
