### ISSUE TITLE
[REGRESSION]: Test runner does not finish on AzDo pipeline

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#24274]
**Context:**

When running in AzDo pipeline the test runner never completes and the pipeline times out.

I've tried package versions 1.35.1 and 1.36.1 with and without the corresponding containers and behavior is still the same.
I have also tried windows-latest and ubuntu-latest vms.
The pipeline code is pretty much as ye have provided [here](https://playwright.dev/docs/ci#azure-pipelines-containerized).

Last line from the pipeline test has me suspicious:

`Serving HTML report at http://localhost:9323./ Press Ctrl+C to quit.
`

Could it be waiting for a Ctrl-C in the pipeline?

**Comment by mxschmitt** [comment]
Looks like AzDo does not set CI=1: https://github.com/MicrosoftDocs/azure-devops-docs/issues/1949

**Comment by dmcweeney** [comment]
@mxschmitt thanks for the pointer....

I guess the docs need to be updated to pass the CI env down to the runner...

Thanks

Donal

**Comment by mxschmitt** [comment]
Could you try setting this env var to validate this theory?

**Comment by dmcweeney** [comment]
@mxschmitt pipeline running as we type!

**Comment by dmcweeney** [comment]
@mxschmitt passing the env through to the test runner script task fixes the problem:

```
    env:
      #DEBUG: 'pw:api'
      CI: 'true'

```

Thanks, 
Donal
