### ISSUE TITLE
Question: Can we increase the time limit for afterEach hook for a specific test case?

### ISSUE THREAD

**Issue by AkkyLohana90** [microsoft/playwright#24285]
Question: Can we increase the time limit for afterEach hook for a specific test case?
As currently I am calling a API function to delete some ids in one of the test case of my test suite, and the deletion of ids through api is taking some time as there are 80+ ids, 
**I need to increase the afterEach hook time for the specific test case only and not for other test cases of that test suite.**
Please suggest any solution.

Currently I am using afterEach hook as follows:

**test.afterEach(async ({ browser }, testInfo) => {
            apiUtility = new ApiUtility(apiContext);
            testInfo.setTimeout(testInfo.timeout + 840000);
        
// afterEach hook code logic

      });**
-
Thanks!

**Comment by aslushnikov** [comment]
> Currently I am using afterEach hook as follows:

@AkkyLohana90 the way you use it should do the trick. Doesn't it work for you?

**Comment by AkkyLohana90** [comment]
Hi [aslushnikov],

It is working but I have to increase the timeout limit for a specific test case.
I cannot add manual wait also in afterEach hook, as it will be applicable for all TCs then.

**Comment by aslushnikov** [comment]
@AkkyLohana90 execution of `afterEach`/`beforeEach` is counted as part of the test, so in your specific test case, you can adjust timeout and make it larger if you expect a long `afterEach` tear down.

Would this work then?

**Comment by AkkyLohana90** [comment]
Could you please give some examples how to adjust(increase) afterEach / beforeEach hooks time for specific test case. 
Sorry, but I am not able to find any.

**Comment by AkkyLohana90** [comment]
Sure, will try.
Thanks!

**Comment by AkkyLohana90** [comment]
I tried the above approach, but not working exactly as expected.

**Comment by AkkyLohana90** [comment]
Hi [aslushnikov],

After executing the test case irrespective of the test case execution status(pass/fail), 
I want to delete 100 ids which got created on the first step of test case after login.
So, for that I am calling a api function which delete the ids.
And to delete the ids system is taking around 4 to 5 mins.

**Now, at the end of afterEach hook, if I add manual wait of 5 mins(instead of 5 secs) then it is working fine.** 

But that added wait is getting applicable for all the test case of the test suite which is wasting my execution time. 
So, I wan't to wait 5 mins only for 1 test case in which 100 ids are generated and not for all test cases.

test.afterEach(async ({ browser }, testInfo) => {
            apiUtility = new ApiUtility(apiContext);
            testInfo.setTimeout(testInfo.timeout + 840000);
            
		// afterEach block logic to delete ids by api which are generated during Test case execution
			
                  await page.waitForTimeout(5000);
               //await page.waitForTimeout(300000);
      });
	  
	  
	  test.only('Test Case Title', async () => {
                     test.setTimeout(8400000); 
           
			//Login code
			
			//Test Case logic code which generates 100 ids and performs some operations on them
			
			//Logout code

      });

**Comment by aslushnikov** [comment]
> So, I wan't to wait 5 mins only for 1 test case in which 100 ids are generated and not for all test cases.

@AkkyLohana90 So again, you can do exactly what you say:

```ts
import { test } from '@playwright/test';

test('this test creates a ton of IDs', async () => {
  test.setTimeout(5 * 60 * 1000);  // 5 minutes timeout
  // Create a ton of IDs and clean them up later
});

test.afterEach(async () => {
  // clean up all the IDs that we created before
});
```

**Comment by AkkyLohana90** [comment]
Will try, Thanks!
Closing the ticket.
