### ISSUE TITLE
[BUG] UI doesn't show all .spec.js files

### ISSUE THREAD

**Issue by vadimpopa** [microsoft/playwright#24293]
Hi,

I'm getting started with Playwright and I'm having a weird issue with the UI. It shows even the js files and ignores some spec files. Note that `npx playwright list-files` works as expected.

### System info
- Playwright Version: 1.36.1
- Operating System: macOS 13.4.1
- Other info:

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './src',
  // Glob patterns or regular expressions that match test files.
  testMatch: /^.*\.spec\.js$/,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Expected**

Should see only spec files in UI, as in `npx playwright list-files` - which works.

**Actual**

UI doesn't show all spec files, and even shows .js files. See screenshot.
<img width="501" alt="Screenshot 2023-07-19 at 09 13 14" src="https://github.com/microsoft/playwright/assets/3592131/94948022-eecd-47df-8e0c-8f50028b93dc">

**Comment by aslushnikov** [comment]
@vadimpopa It does look wrong, however, it's hard to say why. Could you please build a small repo that we can run locally to reproduce the issue?

**Comment by aslushnikov** [comment]
@vadimpopa  this is not actionable without a repro, so closing this. Please do not hesitate to file a new issue if you do find a repro or you think we can be otherwise helpful to you.
