### ISSUE TITLE
[BUG] run-workers not working with docker container

### ISSUE THREAD

**Issue by KarthikP1306** [microsoft/playwright#2429]
**Context:**
- Playwright Version: [what Playwright version do you use?] : 1.0.2
- Node version: [e.g. 10.12, 10.14] : 14.3.0
- Browser: [e.g. All, Chromium, Firefox, WebKit] : Chromium

----------------------------------------------------------------------------------------------

**Describe the bug**

**Positive Scenario**
In local (i.e without docker) we are able to run the workers without any issue

npx codeceptjs run-workers 3 --grep "@tag1" 

**Negative Scenario**
a) In docker container, when we are running with multiple(i.e 3 in this case) workers, parallel execution by workers is not working.

docker run --net=host -it -v $PWD:/tests --name container-name image-name --entrypoint npx codeceptjs run-workers 3 --grep "@tag1"

b) In docker container, when we are running with single worker, parallel execution by workers is woking fine.

docker run --net=host -it -v $PWD:/tests --name container-name image-name --entrypoint npx codeceptjs run-workers 1 --grep "@tag1"

Could you please help us in resolving this issue?

**Comment by pavelfeldman** [comment]
Should it be filed against codeceptjs? Your description does not mention Playwright, so I am not sure we can address it.
