### ISSUE TITLE
[BUG] Glue42: ElectronApplication.Close() Hangs

### ISSUE THREAD

**Issue by charlotte-hayes** [microsoft/playwright#24294]
This is a follow on from issue #24247

### System info
- Playwright Version:  "@playwright/test": "^1.36.0", "@types/node": "^18.7.15"
- Operating System: Windows 11
- Browser: Chromium
- Other info: Application under test is a Electron app using Glue 42. 
- Link to docs where close() is defined: https://playwright.dev/docs/api/class-electronapplication#electron-application-close

### Source code

Example fixture:
```export const test = base.extend({
    electronApp: async ({ }, use) => {
        const electronApp = await electron.launch({
            executablePath: envConfig.gdExePath,
            cwd: envConfig.gdDir,
        })
       
        await use(electronApp)

       await electronApp.close();
    },```


```
  **Playwright.config.ts:**
```
const config: PlaywrightTestConfig = {
  testDir: 'tests/',
  timeout:50000,
  reporter: [['junit', { outputFile: 'results.xml' }]],
  retries: 1,
  workers: 1
};
```

**Test file (self-contained)**

```
test('open a layout from the launchpad and confirm it opens the correct apps', async ({ electronApp }) => {
  const launcher = await waitForAppToLoad("glue42-launchpad", electronApp);
  await launcher.waitForSelector('.form-control')
  await launcher.type(`.form-control`, `TestLayout`);
  await launcher.locator(`data-testid=app-title`).click();
  await launcher.locator(`data-testid=rendered-app >> nth=0 `).click();
  await launcher.waitForLoadState();

  // Waits for ABC APP and DEF APP to launch and verifies their titles are as expected. 
  const abcApp= await waitForAppToLoad('abcApp', electronApp);
  const appNameABC = await abcApp.title();
  expect(appNameABC).toBe('ABC');
  const defApp = await waitForAppToLoad('defApp', electronApp);
  const appNamedefApp = await defApp.title();
  expect(appNamedefApp).toBe('ABC');
 
```

**Steps**
- Attempt to run multiple tests in succession using the above fixture. 
- Note that I have had to anonymise the code but all the tests were launching an electron application in Glue 42, asserting some objects on the page using the same fixture. 

**Expected**

- The close() should close the electron application successfully. Ideally, it should poll until all electron processes conclude before continuing execution. 
- Should this fail then a helpful error message should be displayed.

**Actual**

- The close() hangs because a dialog is displayed which asks the user "are you sure you want to close app XXXX?" and the test times out.
- Subsequent tests fail due to the Electron application failing to launch. 

I really hope I have included enough information but please feel free to reach out and I will do my best to supply any additional information you need. Thank you :)

**Comment by mxschmitt** [comment]
Can you share a minimal reproducible which we can run locally to replicate this issue? A small Git repository would help a ton! We are also not familiar with Glue42, so something with just pure Electron would be the best.

**Comment by aslushnikov** [comment]
@charlotte-hayes this is not actionable without a repro, so I'll close this. Please do not hesitate to file another issue if you do find a repro though!
