### ISSUE TITLE
Firefox version 113.0.1 in UPSTERAM_CONFIG.sh, but current firefox binary built by playwright is 115.0.2

### ISSUE THREAD

**Issue by barbolo** [microsoft/playwright#24306]
In [UPSTREAM_CONFIG.sh](https://github.com/microsoft/playwright/blob/1fdd7541e05dc2a33edb7213d8b6e9836c82d132/browser_patches/firefox/UPSTREAM_CONFIG.sh#L3C1-L3C57):

```bash
BASE_REVISION="7177c1fee2d0ae258241aa9f0f332aae8daf87e7"
```

This revision relates to [firefox 113.0.1](https://github.com/mozilla/gecko-dev/blob/7177c1fee2d0ae258241aa9f0f332aae8daf87e7/browser/config/version.txt). When I try to apply current patches (`browser_patches/firefox/patches/`) to firefox in revision `46b83fe1d54c30f300558a7666eb826f750ec6b5` (115.0.2), I get the following errors:

```bash
error: patch failed: devtools/server/socket/websocket-server.js:190
error: devtools/server/socket/websocket-server.js: patch does not apply
error: patch failed: dom/media/systemservices/video_engine/desktop_capture_impl.cc:436
error: dom/media/systemservices/video_engine/desktop_capture_impl.cc: patch does not apply
error: patch failed: dom/media/systemservices/video_engine/desktop_capture_impl.h:204
error: dom/media/systemservices/video_engine/desktop_capture_impl.h: patch does not apply
error: patch failed: layout/style/nsMediaFeatures.cpp:277
error: layout/style/nsMediaFeatures.cpp: patch does not apply
error: services/settings/Utils.jsm: does not exist in index
error: patch failed: taskcluster/ci/toolchain/macos-sdk.yml:43
error: taskcluster/ci/toolchain/macos-sdk.yml: patch does not apply
```

Do you build binaries with different patches?

**Comment by barbolo** [comment]
Related issue:
https://github.com/microsoft/playwright/issues/17556

It's great that playwright is releasing browser binaries frequently. It would be nice if the patches were also following the binary releases.

Is there a reason for releasing the binaries but not the patches?

**Comment by barbolo** [comment]
I've spent the day trying to properly build Firefox for playwright with no success. I'm not a specialist at Firefox neither at Playwright.

FF versions `114`/`115` won't build because the current patches in this repo cannot be applied.

FF version `113` won't build because some build scripts/tools from mozilla seem deprecated/unavailable/broken. When running firefox bootstrap scripts it warns that the source version is old and bootstrap might fail. I fixed some of the problems, but more problems just keep happening.

I'm considering the following options:

1. Give up building firefox
2. Fix patches by myself (what bothers me with this options is that you have already done this, so it feels like I'm doing an unnecessary work).
3. Receiving the current patches from you and get back to the track I need to follow regarding firefox + playwright.

Can you help me (and probably others) by updating patches regularly?

**Comment by barbolo** [comment]
I've naively updated patches ([patches/bootstrap.diff](https://gist.github.com/barbolo/0c1b6df0310996e462b9990da9d18bec)) so it could be applied to firefox version `115.0.2`.

Firefox can be built if `firefox/juggler/screencast` is skipped.

Before building in macOS it's necessary to install dependencies. Something like this:

```bash
# xcode
sudo xcode-select --install

# LLVM
brew install llvm

# WASI
git clone https://github.com/WebAssembly/wasi-libc.git
cd wasi-libc
export PATH="/opt/homebrew/opt/llvm/bin:$PATH"
sudo make install

# libclang_rt.builtins-wasm32.a
mkdir -p /opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/lib/wasi/
cd /opt/homebrew/Cellar/llvm/16.0.6/lib/clang/16/lib/wasi/
curl -LO https://github.com/jedisct1/libclang_rt.builtins-wasm32.a/raw/master/precompiled/libclang_rt.builtins-wasm32.a
```

The script I'm using to build firefox on macOS (Intel) is below (it runs in a directory that has a folder `patches` with `bootstrap.diff`):

```bash
#!/bin/bash
set -e # Exit immediately if a simple command exits with a non-zero status.
set -x # Print commands and their arguments as they are executed.

trap "cd $(pwd -P)" EXIT # when script exits, change directory back to original directory

SCRIPT_DIR=$(cd "$(dirname $0)" && pwd -P)
FIREFOX_DIR="$SCRIPT_DIR/firefox"
PLAYWRIGHT_DIR="$SCRIPT_DIR/playwright"
OBJ_FOLDER="obj-build-playwright-macos-intel"
OBJ_DIR="$FIREFOX_DIR/$OBJ_FOLDER"

if [ -d $PLAYWRIGHT_DIR ]; then
  cd $PLAYWRIGHT_DIR && git pull
else
  git clone --single-branch --branch main https://github.com/microsoft/playwright.git $PLAYWRIGHT_DIR
fi
source "$PLAYWRIGHT_DIR/browser_patches/firefox/UPSTREAM_CONFIG.sh"
BASE_REVISION=e0ccf0a049acc6e0911465c9679d9cae1e026ba2 # 115.0.2

# include llvm in paths
PATH="/opt/homebrew/opt/llvm/bin:$PATH"
LDFLAGS="-L/opt/homebrew/opt/llvm/lib"
CPPFLAGS="-I/opt/homebrew/opt/llvm/include"

# checkout firefox path in the expected revision
if [ -d $FIREFOX_DIR ]; then
  cd $FIREFOX_DIR && git fetch --shallow-since="3 months"
else
  git clone --single-branch --shallow-since="3 months" --branch $BASE_BRANCH $REMOTE_URL $FIREFOX_DIR
fi
cd $FIREFOX_DIR
git reset --hard $BASE_REVISION # use head of release to avoid errors with old revisions, since playwright revisions are old.

# apply playwright patches
git apply --index --whitespace=nowarn "$SCRIPT_DIR"/patches/*

# add playwright's juggler
rm -rf "$FIREFOX_DIR/juggler"
cp -r "$PLAYWRIGHT_DIR/browser_patches/firefox/juggler" "$FIREFOX_DIR/juggler"

# prepare build options
rm -rf .mozconfig
# echo "ac_add_options --without-wasm-sandboxed-libraries" >> .mozconfig
echo "mk_add_options MOZ_OBJDIR=@TOPSRCDIR@/${OBJ_FOLDER}" >> .mozconfig
echo "ac_add_options --disable-crashreporter" >> .mozconfig
echo "ac_add_options --disable-backgroundtasks" >> .mozconfig
echo "ac_add_options --enable-release" >> .mozconfig
echo "ac_add_options --enable-bootstrap" >> .mozconfig
echo "ac_add_options --disable-update-agent" >> .mozconfig
# echo "ac_add_options --target=aarch64-linux-gnu" >> .mozconfig # https://firefox-source-docs.mozilla.org/build/buildsystem/cross-compile.html

# build firefox
./mach --no-interactive bootstrap --application-choice=browser
./mach build
./mach package

# copy preferences to firefox app
cp "$PLAYWRIGHT_DIR"/browser_patches/firefox/preferences/playwright.cfg "$OBJ_DIR"/dist/firefox/Nightly.app/Contents/Resources/
cp "$PLAYWRIGHT_DIR"/browser_patches/firefox/preferences/00-playwright-prefs.js "$OBJ_DIR"/dist/firefox/Nightly.app/Contents/Resources/defaults/pref/

# ./mach run

# zip firefox
cd "$OBJ_DIR"/dist
zip -r firefox-macos-intel.zip firefox
```

I've tried running tests from with `npm run ftest` but all of them fail. 💩 
I'll try to run some simple playwright scripts to see what happens.

**Comment by barbolo** [comment]
The version I've built with instructions in the previous message is failing badly, it's a waste of time.

@aslushnikov is it intentional that developers outside microsoft aren't able to patch current versions of supported browsers? You do a great work with playwright, but your current workflow makes it really difficult (impossible for developers like me) to build their own firefox binary. This is also a lack of transparency, since it's impossible to know which patches are being applied in the released binaries.

**Comment by aslushnikov** [comment]
Hey @barbolo,

Are you able to build Firefox 113 without our patches? If not, I'd suggest reaching out to Firefox folks in their Matrix chat.

**Comment by barbolo** [comment]
Hi, @aslushnikov. I'm not able to build Firefox 113 without your patches. I'm able to build 114 and 115 without patches.

113 is ~ 2 months old and I understand some links/dependencies are not available anymore.

Why can't you release patches that you are using to build newer versions of Firefox?

**Comment by aslushnikov** [comment]
> I'm not able to build Firefox 113 without your patches. I'm able to build 114 and 115 without patches.
113 is ~ 2 months old and I understand some links/dependencies are not available anymore.

@barbolo again, please reach out to Firefox folks. Build reproducibility is essential for browsers; they should be able to help.

> Why can't you release patches that you are using to build newer versions of Firefox?

We have an established process regarding patches; they update every release. You can wait until 1.37 for them to be updated.

**Comment by aslushnikov** [comment]
Closing as per above.
