### ISSUE TITLE
[BUG] Playwright skipping tests throws error

### ISSUE THREAD

**Issue by timngomsft** [microsoft/playwright#24308]
### System info
- Playwright Version: [v1.XX]
- Operating System: [Windows 11]
- Browser: [All, Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { test, BrowserContext, Page, expect } from '@playwright/test';

test.describe.configure({ mode: 'serial', timeout: 180000 });

let context: BrowserContext;
let page: Page;

test.beforeEach(async ({ playwright, browserName }, testInfo) => {
  try {
    context = await playwright[browserName].launchPersistentContext('', {
      headless: false,
      channel: "msedge"
    });
    page = context.pages()[0];
    test.skip();
  } catch(e) {
    console.log(e)
  }

});

test('Dummy test', async ({ }) => {
  try {
    await page.waitForLoadState('networkidle');
    await page.goto('https://www.example.com');
    expect(page).toHaveTitle('Example Domain');
  } catch (e) {
    throw e;
  }
});
```

**Steps**
- [Run the test]
- [...]
Run test in VSCode

**Expected**

Test should be skipped without any error messages.

**Actual**
Test is skipped but throws an error: Error: No tests found 

[Describe actual behavior]

**Comment by aslushnikov** [comment]
@timngomsft you should have the `test.skip()` method outside of the `try-catch` block.

The following works fine for me:

```ts
import { test, BrowserContext, Page, expect } from '@playwright/test';

test.describe.configure({ mode: 'serial', timeout: 180000 });

let context: BrowserContext;
let page: Page;

test.beforeEach(async ({ playwright, browserName }, testInfo) => {
  try {
    context = await playwright[browserName].launchPersistentContext('', {
      headless: false,
      channel: "msedge"
    });
    page = context.pages()[0];
  } catch(e) {
    console.log(e)
  }
  test.skip();
});

test('Dummy test', async ({ }) => {
  try {
    await page.waitForLoadState('networkidle');
    await page.goto('https://www.example.com');
    expect(page).toHaveTitle('Example Domain');
  } catch (e) {
    throw e;
  }
});
```

Hope this helps!

**Comment by timngomsft** [comment]
Hi @aslushnikov, I tried moving the test.skip outside try-catch but it is throwing an error, Error: No tests found. I can share our test repo through @MSFT email and can help you run our tests

**Comment by msftreigstad** [comment]
I am seeing this as well, but my error looks like this:
Error: FAIL: 18:43:36 UTC. <Test Name Here>

Moving the test.skip did not work for me either.  I moved it into the test, as a step of the test, outside any try/catch, and other configurations, but always ran into this error being thrown and the test counted as failed.
