### ISSUE TITLE
[BUG] `Requiring @playwright/test second time` using yarn workspaces

### ISSUE THREAD

**Issue by Liran-Palo** [microsoft/playwright#24300]
### System info
- Playwright Version: 1.36
- Operating System: macOS 13.4.1
- Browser: Chromium

I've looked into https://github.com/microsoft/playwright/issues/15819 & https://github.com/microsoft/playwright/issues/15349 but didn't find a solution for my problem.

### Bug description
I have a monorepo that utilizes yarn workspaces, in this project, I have a package for the Playwright framework and another project that uses this package as a local dependency.
Both package and the test project have their own `@playwright/test` dependency inside the `package.json` and both have `playwright.config.ts`.
The test project imports files from the framework package, such as fixtures and other utilities. The test project holds the tests and the POMs to serve the tests.
When running tests from the test project I'm getting the following error:
```
Error: Requiring @playwright/test second time, 
First:
Error: 
```

**Comment by aslushnikov** [comment]
> The test project imports files from the framework package, such as fixtures and other utilities. 

@Liran-Palo it seems to be that these fixtures and utilities require the `@playwright/test` from the framework package, whereas your test project requires it's own `@playwright/test`.

You'd need to re-organize code in such a way that only one `@playwright/test` instance is used. You can either:
- make sure that there's a single version of `@playwright/test` in the workspace that everybody is requiring
- re-organize utilities so that they accept instance of `playwright` dynamically rather then import it unconditionally.

To illustrate the last point:

```ts
// utility.ts
// BEFORE
import { test } from '@playwright/test';

const newTest = test.extend(...);
```

```ts
// utility.ts
// AFTER
function createNewTest(test) {
  const newTest = test.extend(...);
  return newTest;
}
```

Let me know if this helps.

**Comment by aslushnikov** [comment]
Closing this as per above. Feel free to file new issues if you think we can be helpful!

**Comment by v5zz** [comment]
when i use lerna，i had the same problem.
i have a package of playwright-config,then other package devDependencies playwright-config

**Comment by hex0cter** [comment]
@aslushnikov I have been stuck with exactly the same problem for a while. Could you please elaborate a bit on how to achieve the point below?

> 1. make sure that there's a single version of @playwright/test in the workspace that everybody is requiring

My setup: a mono repo with multiple npm packages. Each has its own playwright configurations. One package wants to import the other and reuse the page objects from it. 

I don't have much experience with npm/yarn workspaces. Any help will be appreciated. 🙏

**Comment by hex0cter** [comment]
I figured it out. Just writing down in case anyone else has the same question.

1. In the root directory of mono repo, add `workspaces` in `package.json` with the paths of each npm package (subfolders of the monorepo)
2. Remove `@playwright/test` from the `package.json` file of each npm package
3. Add `@playwright/test` in `package.json` in the root directory.

Now there is only one copy of `@playwright/test` in the entire mono repo. In every other npm package in this monorepo, you can call `import { test } from "@playright/test"` as before.
