### ISSUE TITLE
[BUG] Playwright enters password in the username text box field sometimes.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24305]
### System info
- Playwright Version: 1.35.1
- Operating System: All
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

Sometimes, when UI is launched, instead of typing password in the password text field, playwright is typing password in the username field and login fails, intermittent issue, Can you please advise?

### Source code

```javascript
await page.goto('url')
await page.locator('#username').type("g3434);
await page.locator('##password').type("password");
```
<img width="466" alt="Screen Shot 2023-07-19 at 9 23 10 AM" src="https://github.com/microsoft/playwright/assets/113629123/8a49b8b1-bb75-4bdc-98a0-fe99fec7e1b9">

**Comment by aslushnikov** [comment]
@InduKrish this happens when page accidentally shifts focus from one element to another. The same would happen to your website user.

To workaround, you can use [`locator.fill()`](https://playwright.dev/java/docs/api/class-locator#locator-fill) instead of `locator.type()`.

Hope this help!
