### ISSUE TITLE
Is there a recommended way to configure running @mobile tests on specific envs?

### ISSUE THREAD

**Issue by suhi13** [microsoft/playwright#24318]
I'm looking for an optimal way to configure running @mobile tests only on the specific (int, stg ) environments?
At the moment we use test skips based on env variable like test.skip(envHandler.env === Environment.FTR, 'reason'), but I'm not satisfied with this solution.
Thank you in advance.

**Comment by Exoow** [comment]
If you define the "testMatch" or "testSkip" property in your testproject configuration, you only need to check the environment flag once. Depending on the flag you can skip or match only testfiles that contain "mobile" for example.

https://playwright.dev/docs/api/class-testproject#test-project-test-match

**Comment by aslushnikov** [comment]
Closing as per above.
