### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by SeidChr** [microsoft/playwright#24324]
We are testing websites which automatically play audio, and need to control the audio output of the browser (mute it)
Basically we need this feature: #8730
As it was declined in 2021, which is 2 years ago, is there a way to achieve this now?
When there is no way through playwright itself, are there any Tipps for a workaround?
Can I somehow get information about the chrome process through playwright, so I can turn down the system volume for that process?

**Comment by aslushnikov** [comment]
> As it was declined in 2021, which is 2 years ago, is there a way to achieve this now?

@SeidChr There's no way to achieve this as of today.

> When there is no way through playwright itself, are there any Tipps for a workaround?

You can use the `--mute-audio` flag in Chromium to mute all sounds. Would it work?

**Comment by SeidChr** [comment]
@aslushnikov 
Is there a way of passing this through playwright?

**Comment by aslushnikov** [comment]
Yes, you can use `launchOptions`: https://playwright.dev/docs/next/api/class-testoptions#test-options-launch-options

**Comment by SeidChr** [comment]
![image](https://github.com/microsoft/playwright/assets/1927076/651c40ce-475a-4b08-9e4f-a2d7800a7c1f)
this seems to have dont the job, thx!

still would love to see it by tab, but for now its fine :)
