### ISSUE TITLE
[Feature] Add "Stop all tests" to the actions menu in vs code

### ISSUE THREAD

**Issue by shairez** [microsoft/playwright#24328]
Sometimes the tests hang in VS Code and there's no clear reason why.

It took me a while to find where to stop them by getting to this issue #22444

But the first place I looked for is CTRL+SHIFT+P and search for "Stop Playwright Tests" or something alike... 

Maybe would be easier for those who can't find the stop button immediately

**Comment by aslushnikov** [comment]
@shairez Testing capabilities in VSCode are extensible, so the idea is that there's a single "stop" and "start" commands that is a VSCode capability.

So you should probably file this to a VSCode repo so that they add it. Thanks for filing though!

**Comment by shairez** [comment]
OK I will
Thanks!
