### ISSUE TITLE
[Question]: Hard timeouts for browser context

### ISSUE THREAD

**Issue by Umzario** [microsoft/playwright#24332]
### Your question

Hey team, I wanted to know if there's a way to set a hard timeout for browser contexts? For example, if the timeout is set to 30 seconds, a `TimeoutError` (or something else) will be thrown after that time. I looked through the documentation and saw `browser_context.set_default_timeout(timeout)`/`browser_context.set_default_navigation_timeout(timeout)`, however, if I understand correctly, what these seem to do is set the default timeout for any wait event. So I wanted to know if there's a timeout option to set execution time to X seconds. 

Hope that made sense. Thank you and I await your response :)

**Comment by aslushnikov** [comment]
Hey @Umzario,

No, there's no such functionality, but it should be easily implementable yourself: just set a timer for the desired timeout, and throw an error when it ends. Would it work?

**Comment by aslushnikov** [comment]
I'll close this as per above. Feel free to ask more question if you think we can be helpful!
