### ISSUE TITLE
[Feature] page.goto optional props

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#24346]
Can `page.goto` props be made optional?

If the app runs in a subfolder:

```typescript
export default defineConfig({
  use: {
    baseURL: 'https://website.dev/SUBFOLDER/',
  },
});
```

Then the API looks like this when i want to navigate to `https://website.dev/SUBFOLDER/`: 

`await page.goto('')` or `await page.goto('.')` instead of `await page.goto()` or perhaps `await page.goto('/')`

**Comment by pavelfeldman** [comment]
Here is how I test what works and what does not:

```js
console.log(new URL('', 'https://website.dev/SUBFOLDER/').toString())
console.log(new URL('.', 'https://website.dev/SUBFOLDER/').toString())
console.log(new URL('/', 'https://website.dev/SUBFOLDER/').toString())
```

**Comment by pavelfeldman** [comment]
It is unfortunate that the API is not too friendly in terms of the resolution, but we inherited it from the spec to be on the safe side. I don't think we'll be introducing the param-less version.
