### ISSUE TITLE
The openssl path that playwright is referencing. I got an openssl error on route.fetch.

### ISSUE THREAD

**Issue by kyounoii** [microsoft/playwright#24359]
I did var response = await route.FetchAsync();
but got the following error.
write EPROTO DC680000: error: 0A000152: SSL routines: final_renegotiate: unsafe legacy renegotiation disabled: c:\ws\deps\openssl\openssl\ssl\statem\extensions.c:922:

Can this be worked around by changing the openssl config file?
If so, please tell me where to find that config file.

**Comment by pavelfeldman** [comment]
I'm not sure what happens here and why. Please file an issue using the 'BUG' template so that we could reproduce and investigate it. We need to know the browser type, the endpoint you are filing the request against, etc.

**Comment by kyounoii** [comment]
It takes time to organize the steps to reproduce the problem.
Before I do that, could you please tell me the openssl path that playwright is referring to?
I would like to know for windows11 and ubuntu respectively.

**Comment by pavelfeldman** [comment]
Playwright does not refer to any openssl.

**Comment by pavelfeldman** [comment]
Closing as non-actionable
