### ISSUE TITLE
[Feature] Support Typescript 5+ Decorators

### ISSUE THREAD

**Issue by rony-arnac** [microsoft/playwright#24358]
Hi,

Given that [typescript 5 supports decorators](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#decorators) OOB without using the legacy flag in tsconfig, why can't we use decorators in playwright tests without adding a tsconfig file?

Thanks

**Comment by pavelfeldman** [comment]
Thank you for filing the feature request. It should work out of the box today, if your use case does not work, please file an BUG issue with the steps to reproduce.
