### ISSUE TITLE
[Feature] Expose Request Identifier (Request ID) to Track Responses

### ISSUE THREAD

**Issue by aniket-kulkarni** [microsoft/playwright#24364]
I am maintaining a list of network requests and storing their responses upon receiving the onResponseFinished event. However, I've encountered a scenario where two requests have the same URL. In this situation, I am unable to uniquely identify which request has received a successful response. This is a blocker for me.

I believe that providing a unique request identifier, such as a Request ID or GUID, would greatly enhance the ability to track responses and associate them with their corresponding requests in such scenarios.

Therefore, I kindly request the Playwright team to consider adding a Request ID or similar unique identifier to each request object. This Request ID would be exposed as a property of the request object and can be utilized to track responses effectively, even when multiple requests share the same URL.

Thank you for considering this feature request, and I'm looking forward to the continuous improvement of Playwright.

**Comment by aslushnikov** [comment]
>  In this situation, I am unable to uniquely identify which request has received a successful response. This is a blocker for me.

@aniket-kulkarni Each response has a [`response.request()`](https://playwright.dev/docs/api/class-response#response-request) that you can use to identify a matching request.

> I believe that providing a unique request identifier, such as a Request ID or GUID, would greatly enhance the ability to track responses and associate them with their corresponding requests in such scenarios.

Requests and responses are already represented by unique objects, so you should have no problem tying one to another.

**Comment by pavelfeldman** [comment]
You can solve your problem with a `Map` or a `Symbol` type + guid generator.

**Comment by Mattwmaster58** [comment]
> Each response has a [response.request()](https://playwright.dev/docs/api/class-response#response-request) that you can use to identify a matching request.

Correct me if I'm wrong, but I don't think this covers all cases. For example, consider a case with 2 identical requests. When a response is received, how would you determine which request this was in response to?

_____

We have a use case where we have to use heuristics to determine if a page is loaded "enough". We deal with 1000's of different sites. The `networkidle` event isn't flexible enough for us, so we track in flight requests ourselves. Duplicate requests (based on URL) is something we've seen. In our particular implementation, it just so happens we can keep of list of inflight URLs  and only remove one at a time as they succeed or fail - but including an ID by which we can track the request by would make our implementation easier to reason about
