### ISSUE TITLE
[BUG] Playwright emulation is inconsistent

### ISSUE THREAD

**Issue by JustScreaMy** [microsoft/playwright#24369]
**Context:**
- Playwright Version: 1.36.0
- Operating System: Ubuntu 22.04.2 LTS (mcr.microsoft.com/playwright/python:jammy)
- Python version: 3.10.6
- Browser: Chromium (Chrome)

**Code Snippet**
```python
import time
from contextlib import contextmanager

from playwright.sync_api import sync_playwright, Playwright, Browser, Page


@contextmanager
def setup_browser(playwright: Playwright) -> Page:
    browser: Browser = playwright.chromium.launch(channel="chrome", headless=False)
    context = browser.new_context(
        **playwright.devices["Pixel 2"]
    )
    ctx_page = context.new_page()
    ctx_page.set_default_timeout(60000)
    try:
        yield ctx_page
    finally:
        browser.close()


with sync_playwright() as pw:
    with setup_browser(pw) as page:
        page.goto("https://mp.cz/")
        time.sleep(15) # This is so i can try to test things myself 
```

**Describe the bug**
The viewport on the emulated device is quite inconsistent. As you can see, the left two browsers are locally installed browsers with their "Responsive Design Mode" emulation enabled on the "Pixel 2" settings. It seems like the playwright emulated device just cuts out some of the bottom of the page, because manual scrolling does nothing.

![image](https://github.com/microsoft/playwright-python/assets/43576992/d5df5a63-1060-46a7-9cd2-4dabeb92c84a)

Running device using `playwright cr --channel chrome --device "Pixel 2"` though, allows resizing the window and fixes this whole problem. But this fix isnt applicable in CI environments

![image](https://github.com/microsoft/playwright-python/assets/43576992/21cf0408-813d-46d3-8b1e-c98475f6436e)

**Comment by pavelfeldman** [comment]
> As you can see, the left two browsers are locally installed browsers with their "Responsive Design Mode" emulation enabled on the "Pixel 2" settings. It seems like the playwright emulated device just cuts out some of the bottom of the page, because manual scrolling does nothing.

What I see is that the browser windows of the first two are larger - if you resize all the windows to be the same size, you'll see the content.

**Comment by JustScreaMy** [comment]
I mean yeah, but I can't image resizing the window in headless browser running on some CI runner. I think that this might be the issue why my e2e test cant click on the element that is cut out,

**Comment by pavelfeldman** [comment]
There is no window when it runs headless, so there is nothing to resize. And no, it can't be the reason clicks son't work in that area. In both headless and headed area the actual viewport size is the same and is correct.

**Comment by JustScreaMy** [comment]
Well, this issue doesn't seem to show on webkit. So it is something.

**Comment by pavelfeldman** [comment]
> Well, this issue doesn't seem to show on webkit.

That's because the emulation code is browser and os-specific. In WebView, higher-level API is used to set the size of the window, while in Chromium there is a way to unbind the logical size from the physical size, which we do.

> And i thought that the locator tries to find if the element is visible before clicking it.

That's not the case, the check is done against the logical viewport, think about the headless mode where there is no window at all.

**Comment by IsmailSAly** [comment]
Did you ever figure out a fix for this issue?
I am having the same problem with Chromium as well. Problem doesn't exist when using webkit. However i need to use chromium now since i want to utilize the CDP session support.
