### ISSUE TITLE
[REGRESSION]:  Error: EBUSY: resource busy or locked opening network trace

### ISSUE THREAD

**Issue by stalkerz379** [microsoft/playwright#24375]
**Context:**
- GOOD Playwright Version: [1.34 and below]
- BAD Playwright Version: [1.35 and above]
- Operating System: [Windows 10]
- Extra: [Node version 16.17.0]

**Code Snippet**

```javascript
//playwright.config.js
// global use
use: {
trace: 'retain-on-failure',
baseURL: 'https://bing.com'
}

// dummy.spec.js
const { expect, request, test } = require('@playwright/test');

class Search {

    /**
     * @param {import('@playwright/test').APIRequestContext} api 
     */
    constructor(api) {
        this.api = api;
        this._request = request.newContext({
            baseURL: 'https://google.com'
        }); // pay attention to this separate context
    }

    async google() {
        const resp = await (await this._request).get('/');
        return resp
    }

    async bing() {
        const resp = await this.api.get('/');
        return resp
    }
}

// tests itself

test.describe('top describe with setup', () => {

    test.beforeAll(async ({ request }) => {
        const response = await request.get('/');
        console.log('first request, ', response.status());
        const search = new Search(request);
        const bingResponse = await search.bing();
        console.log('second bing response', bingResponse.status());
    });

    test.describe('2nd describe with setup', () => {

        test.beforeAll(async ({ request }) => {
            const response = await request.get('/');
            console.log('2nd setup call', response.status());
        });

        test('run dummy test', async ({}) => {
            console.log('Dummy test');
            expect(1).toBe(1);
        })
    });
});

// run the tests via the command line, e.g. "npx playwright test dummy.spec.js"

```

**Describe the bug**

**STR**

1. Copy the code from the snippet below
2. run the tests via the command line, e.g. "npx playwright test dummy.spec.js"

**Actual result**
The tests are not run as expected. Error:
`Error: EBUSY: resource busy or locked, open 'C:\Users\MY_USER\MY_PROJECT\test-results\.playwright-artifacts-0\traces\334486b451870f2d0289-636e0057f55a328eba11-1.network'`

Console outcome:
`first request,  200
second bing response 200
`

**Note:** if tracing is disabled at all in the config 'playwright.config.js' then the issue is not reproducible.
Depending on the structure inside the top test describe (e.g. if the second setup call is missing) then the issue is not reproducible as well.

**Comment by aslushnikov** [comment]
Unfortunately this is not actionable without a good repro. We landed a few fixes to the tip-of-tree, and we hope they fix this. 

The fixes will be available in 1.37. Please, give it a try once it out!

If things still don't work for you, please file a new issue with a good repro that we can run locally to reproduce.
Thanks!
