### ISSUE TITLE
[BUG] some launchOptions that playwright completely ignores when it is running headless

### ISSUE THREAD

**Issue by javierpaez** [microsoft/playwright#24374]
there are some launchOptions that playwright completely ignores, even in headed mode, like --show-fps-counter
and then even for the ones it honors (like --credits and --version ). 
We discovered this problem when we were adding this configuration:
`
projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                launchOptions: {
                    args: [
                        '--disable-blink-features=AutomationControlled', // needed for gsl so google doesn't flag it as not secure
                    ],
                },
            },
        },
`
seems like this configuration is only working on headed mode, in headless mode it is not working

### System info
- Playwright Version: [v1.35.1]
- Operating System: [MacOS ventura 13.4.1]
- Browser: [Chromium] (didn't test on others)
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

private repository

or

**Config file**

```
projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
                launchOptions: {
                    args: [
                        '--disable-blink-features=AutomationControlled', // needed for gsl so google doesn't flag it as not secure
                    ],
                },
            },
        },
```

**Steps**
- [Run the test headless mode]
- [the lauchOption are not taking as part of the tests]

**Expected**

the lauchOptions in headed or headless mode should be the same

**Actual**

the launchOptions are only working in headed mode and also some flags are not working in both

**Comment by pavelfeldman** [comment]
Google's policy is to not allow authentication from the automated browsers, including automated by Playwright.

**Comment by dwbruhn** [comment]
Hi @pavelfeldman, thanks for the response! What we're finding is that in **headed** mode we can indeed successfully authenticate with Google, simply by passing `--disable-blink-features=AutomationControlled` in `launchOptions`.

But in **headless** mode, it's not working:

![image](https://github.com/microsoft/playwright/assets/8230981/8ec5055e-b580-4be5-bb2b-324af047c457)

Our first suspicion was that Playwright is not honoring the `--disable-blink-features=AutomationControlled`  launchOption in headless mode, since we've found that there are other launchOptions that work in headed but not headless mode (like `--credits` and `--version`).

Is that the case?

**Comment by DyloG783** [comment]
Hi @dwbruhn , this doesn't seem to be working as of today, my config is very similar to the above

`name: 'chromium',
      dependencies: ['setup'],
      use: {
        ...devices['Desktop Chrome'],
        storageState: 'playwright/.auth/user.json',
        launchOptions: {
          args: [
            '--disable-blink-features=AutomationControlled',
          ],
        },
      },`

Does this approach still work?

**Comment by dwbruhn** [comment]
Here's a configuration we found that works for logging into Google:

```ts
test.use({
    bypassCSP: true,
    launchOptions: {
        args: ['--disable-features=IsolateOrigins,site-per-process', '--disable-blink-features=AutomationControlled'],
        slowMo: 1000,
        env: {},
        channel: '',
    },
    userAgent:
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML. like Gecko) Chrome/94.0.4606.61 Safari/537.36',
});
```

**Comment by DyloG783** [comment]
Thanks for sharing this, I was so wild over trying to hack this together, I ended up ditching NextAuth for Clerk so I could have simple login credentials flow which will work much better with Playwright
