### ISSUE TITLE
[BUG] Playwright doesnt load table with the filtered row.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24372]
### System info
- Playwright Version: 1.32.2
- Operating System: Mac
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

 I do have a search field to search for the employee id, and the table should filter the row that matches the employee id and display only that record,  the test is flaky, sometimes it filters and displays the row matches the id, and sometimes, it just doesn’t filer and test fails.

```javascript
//option 1
await page.locator('#search-employeeId').fill('50000'); -- fill the employee id in the text field.
await page.getByTestId('button-text-search-icon-search-employeeId').click();  --> clicking on search icon here


//option 2
await page.getByTestId('search-employeeId').type("50000). --> use type to type employee id in the search field.
await page.keyboard.press("Enter"). --> performed keyboard
```

both the above cases are flaky, and sometimes it fails (and sometime it works)
Below is the screenshot, even after typing the employee id in the text field and hit search icon, playwright didnt filter the single row that matches employee id, I expected to see a single row that matches employee id  50000.. the test fails as table still rows all the records instead of showing the filtered single row. can you please advise (edited) 

<img width="891" alt="Screen Shot 2023-07-24 at 10 05 18 AM" src="https://github.com/microsoft/playwright/assets/113629123/2630685e-fb40-459e-966c-e776e25fe17f">

<img width="1313" alt="Screen Shot 2023-07-24 at 9 37 27 AM" src="https://github.com/microsoft/playwright/assets/113629123/3f7916f0-3881-4275-8c68-05838c3fb221">

**Comment by pavelfeldman** [comment]
It is likely that your app has a racy hydration problem where if text is entered too fast (before the listeners are installed), it won't react to them. Use Slow 3G emulation in Chrome DevTools and type real fast to confirm the issue.

**Comment by InduKrish** [comment]
so should developer fix the issue with the application? Can you please confirm? and Can you please help me with the link of the articles/documentation on Slow 3G emulation to follow the steps ,in order to replicate the issue ?

**Comment by pavelfeldman** [comment]
https://playwright.dev/docs/navigations#hydration

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
