### ISSUE TITLE
[Feature] - modify error message to be more helpful - Error: Object with guid was not bound in the connection

### ISSUE THREAD

**Issue by dman777** [microsoft/playwright#24370]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I was getting this error message which was cryptic ` Error: Object with guid response@ccf0fb6d34926d7b5dac1cc0dc76b689 was not bound in the connection`; 

Turns out, I forgot the `await` for `page.goto(/foo)`. It was confusing also because the first test would pass but not the second. I think maybe this error message could mention checking for a missing await?

**Comment by pavelfeldman** [comment]
Missing await changes the whole course of your program execution. You can use eslint that checks for missing awaits to catch this error in Playwright and non-Playwright code.
