### ISSUE TITLE
[BUG] The official Docker image doesn't work with non root user

### ISSUE THREAD

**Issue by haikyuu** [microsoft/playwright#2437]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.0.2
- Operating System: [e.g. Windows, Linux or Mac] Linux Debian 10
- Node version: [e.g. 10.12, 10.14] 12
- Browser: [e.g. All, Chromium, Firefox, WebKit] All
- Extra: [any specific details about your environment] Docker
I am running playwright in Docker using the exact docker image from your github repo
Error
```
VError: a BeforeAll hook errored, process exiting: features/support/playwright.js:14: Failed to launch browser: Error: spawn /home/pwuser/.cache/ms-playwright/firefox-1089/firefox/firefox ENOENT
```
I think the problem comes from installing The browsers to `/root` folder: `/root/.cache/ms-playwright/chromium-764964` and the user not being able to access them when running playwright.

```
> node install.js
chromium v764964 downloaded to /root/.cache/ms-playwright/chromium-764964

firefox v1089 downloaded to /root/.cache/ms-playwright/firefox-1089

webkit v1219 downloaded to /root/.cache/ms-playwright/webkit-1219
```
**Code Snippet**

```javascript
  global.browser = await pw.chromium.launch({ headless: process.env.HEADLESS !== "false" });
```

**Describe the bug**

Note that the same happens with chrome

**Comment by haikyuu** [comment]
In order for things to work properly, i had to:
- shell into the container using the root user `sudo docker run -u root -it <id> bash -li`
- There is no `/root/.cache` directory even though it appeared in the logs. -> Another issue i guess. It should throw an error if it cannot write there
- When i `rm -rf node_modules && npm i`, it works fine.

**Comment by haikyuu** [comment]
It worked when i used root in the `Dockerfile`

**Comment by arjun27** [comment]
Thanks @haikyuu, this is not the expected experience - apologies for that. When I run `npm i playwright`, the download locations are different than the ones you have listed in your first comment. This is on using the docker image as-is (ran it with `docker container run -it --rm --ipc=host --security-opt seccomp=chrome.json aslushnikov/playwright:bionic /bin/bash`).

```
pwuser@0cf9d059e16e:~/try$ npm i playwright

> playwright@1.0.2 install /home/pwuser/try/node_modules/playwright
> node install.js

Downloading chromium v764964 - 125.3 Mb [====================] 100% 0.0s 
chromium v764964 downloaded to /home/pwuser/.cache/ms-playwright/chromium-764964
Downloading firefox v1089 - 67.4 Mb [====================] 100% 0.0s 
firefox v1089 downloaded to /home/pwuser/.cache/ms-playwright/firefox-1089
Downloading webkit v1219 - 112.3 Mb [====================] 100% 0.0s 
webkit v1219 downloaded to /home/pwuser/.cache/ms-playwright/webkit-1219
```

Can you tell me how you installed the dependencies the first time?

**Comment by arjun27** [comment]
I suspect this happens when the playwright npm package is installed in the dockerfile, and executed with the `RUN` command during a Docker build. Is that how it's setup?

**Comment by haikyuu** [comment]
Thanks @arjun27 i will get back to you soon

**Comment by haikyuu** [comment]
> I suspect this happens when the playwright npm package is installed in the dockerfile, and executed with the `RUN` command during a Docker build. Is that how it's setup?

No, here is what i added after the image:
```
COPY . /home/root/project
WORKDIR /home/root/project/e2e

RUN npm install
USER pwuser

RUN npm run e2e
```

The difference is that the base image is `edgedb/edgedb` which in turn is based on `debian:buster-slim`.

What i ended up doing was to run my tests in Firefox using the root user.

**Comment by yury-s** [comment]
@haikyuu is there a reason you want to copy everything and install under root rather than non-privileged user the tests are running under? Basically rearranging your docker file like this:

```
USER pwuser

COPY --chown=pwuser:pwuser . /home/pwuser/project
WORKDIR /home/pwuser/project/e2e
RUN npm install

RUN npm run e2e
```
This way the browsers should go into `pwuser` home dir and the user should have permissions to access everything installed this way.

**Comment by haikyuu** [comment]
Thanks @yury-s 

Now, i get this error
![image](https://user-images.githubusercontent.com/8558836/83943276-a0356700-a7f2-11ea-84e7-ed4e94e3865f.png)
```
Error: Protocol error (Target.setAutoAttach): Target closed
```
Firefox works fine. But i want to use chromium in order to use [this library](https://github.com/qawolf/playwright-video) to record videos.

**Comment by yury-s** [comment]
Looks like Chromium is not starting for some reason. Can you run you script with `DEBUG=pw:browser*` and see what error it prints out? Also seeing your Docker file would be helpful for debugging this, do you mind sharing it?

**Comment by haikyuu** [comment]
Sure, here is the dockerfile
```
# Copied from :https://github.com/microsoft/playwright/blob/v1.0.2/docs/docker/Dockerfile.bionic
FROM ubuntu:bionic

# 1. Install node12
RUN apt-get update && apt-get install -y curl && \
    curl -sL https://deb.nodesource.com/setup_12.x | bash - && \
    apt-get install -y nodejs

# 2. Install WebKit dependencies
RUN apt-get install -y libwoff1 \
                       libopus0 \
                       libwebp6 \
                       libwebpdemux2 \
                       libenchant1c2a \
                       libgudev-1.0-0 \
                       libsecret-1-0 \
                       libhyphen0 \
                       libgdk-pixbuf2.0-0 \
                       libegl1 \
                       libnotify4 \
                       libxslt1.1 \
                       libevent-2.1-6 \
                       libgles2 \
                       libvpx5

# 3. Install Chromium dependencies

RUN apt-get install -y libnss3 \
                       libxss1 \
                       libasound2

# 4. Install Firefox dependencies

RUN apt-get install -y libdbus-glib-1-2 \
                       libxt6

# 5. Install ffmpeg to bring in audio and video codecs necessary for playing videos in Firefox.

RUN apt-get install -y ffmpeg

# 6. Add user so we don't need --no-sandbox in Chromium
RUN groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser \
    && mkdir -p /home/pwuser/Downloads \
    && chown -R pwuser:pwuser /home/pwuser

# 7. (Optional) Install XVFB if there's a need to run browsers in headful mode
RUN apt-get install -y xvfb

# Run everything after as non-privileged user.
USER pwuser

# Install yarn as outlined in (https://yarnpkg.com/lang/en/docs/install/#alternatives-stable)
RUN curl -o- -L https://yarnpkg.com/install.sh | bash
# Make available in the current terminal
RUN export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"

WORKDIR /home/project
COPY .. /home/project

RUN cd e2e && yarn done
```

**Comment by yury-s** [comment]
I don't think you can use `..` in `COPY` as all the files that are copied into the image must be in the docker build context, can it be the case?

**Comment by haikyuu** [comment]
@yury-s Yes indeed. I posted an outdated file

Nevertheless, I was able to replicate the issue using repl `node` and `pw.chromium.launch().then(console.log)`

**Comment by yury-s** [comment]
> @yury-s Yes indeed. I posted an outdated file
> 

Can you post the exact one where you see the failure, otherwise it's hard to tell what's broken?


> Nevertheless, I was able to replicate the issue using repl `node` and `pw.chromium.launch().then(console.log)`

Did you figure out what was the problem?

**Comment by haikyuu** [comment]
Sure, here is the exact Dockerfile
```
FROM node:12-buster
# Copied from :https://github.com/microsoft/playwright/blob/v1.0.2/docs/docker/Dockerfile.bionic

# FROM ubuntu:bionic
# COPY --from=0 /schoolibri/ /schoolibri

RUN apt-get update
# 2. Install WebKit dependencies
RUN apt-get install -y libwoff1 \
                       libopus0 \
                       libwebp6 \
                       libwebpdemux2 \
                       libenchant1c2a \
                       libgudev-1.0-0 \
                       libsecret-1-0 \
                       libhyphen0 \
                       libgdk-pixbuf2.0-0 \
                       libegl1 \
                       libnotify4 \
                       libxslt1.1 \
                       libevent-2.1-6 \
                       libgles2 \
                       libvpx5

# 3. Install Chromium dependencies

RUN apt-get install -y libnss3 \
                       libxss1 \
                       libasound2

# 4. Install Firefox dependencies

RUN apt-get install -y libdbus-glib-1-2 \
                       libxt6

# 5. Install ffmpeg to bring in audio and video codecs necessary for playing videos in Firefox.

RUN apt-get install -y ffmpeg

# 6. Add user so we don't need --no-sandbox in Chromium
RUN groupadd -r pwuser && useradd -r -g pwuser -G audio,video pwuser \
    && mkdir -p /home/pwuser/Downloads \
    && chown -R pwuser:pwuser /home/pwuser


# 7. (Optional) Install XVFB if there's a need to run browsers in headful mode
RUN apt-get install -y xvfb

# Run everything after as non-privileged user.
USER node
RUN mkdir /home/node/repo
WORKDIR /home/node/repo
RUN npm init --yes
RUN npm install playwright 
```

I don't know what's the problem. But i suspect it's about the base image, since you're using `bionic` and i'm using `buster`.

I would happily switch, but there is no `bionic` official image for node. And manually installing node in  popped up a lot of `EACCESS` issues and was incompatible with our setup.

Here is the command to use to run the docker container `docker run --rm -it <id> bash -il`

Here is the last lines of the logs
```
tep 12/13 : RUN npm init --yes
 ---> Running in cda43e5ef8eb
Wrote to /home/node/repo/package.json:

{
  "name": "repo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


Removing intermediate container cda43e5ef8eb
 ---> b60453270f3a
Step 13/13 : RUN npm install playwright
 ---> Running in 4dd65bbc6735

> playwright@1.0.2 install /home/node/repo/node_modules/playwright
> node install.js


chromium v764964 downloaded to /home/node/.cache/ms-playwright/chromium-764964

firefox v1089 downloaded to /home/node/.cache/ms-playwright/firefox-1089

webkit v1219 downloaded to /home/node/.cache/ms-playwright/webkit-1219
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN repo@1.0.0 No description
npm WARN repo@1.0.0 No repository field.

+ playwright@1.0.2
added 38 packages from 82 contributors and audited 38 packages in 70.54s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

 Removing intermediate container 4dd65bbc6735
 ---> fcf7f12dcdf9
Successfully built fcf7f12dcdf9
admin@ip-172-16-1-171:~/mono$ docker run --rm -it fcf7f12dcdf9 bash -il
node@860b28f649ab:~/repo$ ls
node_modules  package-lock.json  package.json
node@860b28f649ab:~/repo$ node
Welcome to Node.js v12.18.0.
Type ".help" for more information.
> require("playwright").chromium.launch().then(console.log)
Promise { <pending> }
> (node:11) UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setAutoAttach): Target closed.
    at /home/node/repo/node_modules/playwright-core/lib/chromium/crConnection.js:130:63
    at new Promise (<anonymous>)
    at CRSession.send (/home/node/repo/node_modules/playwright-core/lib/chromium/crConnection.js:129:16)
    at CRSession.<anonymous> (/home/node/repo/node_modules/playwright-core/lib/helper.js:64:31)
    at Function.connect (/home/node/repo/node_modules/playwright-core/lib/chromium/crBrowser.js:63:27)
    at Chromium.launch (/home/node/repo/node_modules/playwright-core/lib/server/chromium.js:41:53)
(node:11) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:11) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by yury-s** [comment]
> I don't know what's the problem. But i suspect it's about the base image, since you're using `bionic` and i'm using `buster`.
>

It can be the case I don't know what is included in debian:buster image but I suspect it's missing some of the desktop libraries required to launch the browsers (which are available in the base bionic image). Launching with `DEBUG=pw:browser*` should make it clear what is missing. I'll try to build the image later too.

 
> I would happily switch, but there is no `bionic` official image for node. And manually installing node in popped up a lot of `EACCESS` issues and was incompatible with our setup.
> 

Can you elaborate on this? Was it `EACCESS` errors somewhere in playwright code or in your project? This may well be caused by some files copied with wrong permissions. Since we managed to run node code in the image built from the docker file in our docs I'd expect the node installation to be working fine, I'd be very curious to learn where it breaks for you.


> Here is the last lines of the logs
> 

Can you run node again with `DEBUG=pw:browser*` to see why the browser is not starting?

**Comment by tajo** [comment]
This is my output for buster and webkit:

```sh
pw:browser <launching> /root/.cache/ms-playwright/webkit-1219/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
--
  | pw:browser <launched> pid=65 +6ms
  | pw:browser:err /root/.cache/ms-playwright/webkit-1219/minibrowser-wpe/MiniBrowser: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory +0ms
  | pw:browser <process did exit 127, null> +9ms
  | (node:54) UnhandledPromiseRejectionWarning: Error: Protocol error (Playwright.createContext): Browser has been closed.
```

**Comment by yury-s** [comment]
> I tried to install `libjpeg-dev` but doesn't help.

Looks like Debian doesn't have a separate package for libjpeg turbo (libjpeg-turbo8 in Ubuntu) and instead ships only libjpeg62-turbo which at the first glance should have different ABI and won't work out of the box with our WebKit build, so it might require building WebKit from source on Buster.

**Comment by yury-s** [comment]
@tajo as @arjun27 pointed out you can build missing libjpeg from source, something like this should work:

```
FROM node:12-buster
....
# Build libjpeg from source
RUN cd /tmp && wget http://www.ijg.org/files/jpegsrc.v8d.tar.gz && tar zxvf jpegsrc.v8d.tar.gz && cd jpeg-8d && ./configure && make && make install

# Run everything after as non-privileged user.
USER node

# Add manually built libraries to the search path
ENV LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH
...
```
This is not exactly libjpeg-turbo8 we are using but it should fix the missing dependency issue.

**Comment by yury-s** [comment]
Closing the issue, feel free to reopen if you have more questions.

**Comment by tajo** [comment]
> @tajo as @arjun27 pointed out you can build missing libjpeg from source, something like this should work.

This works. You guys are great. Thanks!

**Comment by ahmad2smile** [comment]
For me installation of `npm` packages was done in `root` for `pwuser` dir `/home/pwuser/.cache/` it wasn't installed.
