### ISSUE TITLE
[BUG] Unable to see the browser while running the tests in docker

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24384]
### System info
- Playwright Version: 1.32.2
- Operating System: MAC
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

docker image used: FROM mcr.microsoft.com/playwright:latest

xvfb-run npx playwright test.  --> using this command to run playwright tests, tests are running, however i dont see the browser. Can you please advise how to see the browser while running the tests in docker container?

followed the advise from this link - https://github.com/microsoft/playwright/issues/18224
Sill i don't see the browser.

**Comment by pavelfeldman** [comment]
There are various techniques of "Seeing" what happens inside docker display. Search them on the internet or ask someone in Discord. This is a generic Docker topic, outside of the scope for Playwright though.
