### ISSUE TITLE
[BUG] Docker playwright tests returns invalid URL, although the url is valid , also the same tests works fine in local

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24387]
### System info
- Playwright Version: 1.32.2
- Operating System: MAC
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

when i print process.env.TOKEN_URL--> it prints the right value and verified the same inside trace zip file as well.
although it reads the URL right, why it is complaining saying invalid URL? and this happens only when i run the tests in docker, and tests in local works fine. Screenshot is attached below that displays the actual valid URL.

i use FROM mcr.microsoft.com/playwright:latest and playwright version is 1.32.2. Can you please confirm if playwright latest image is compatible with 1.32.2 playwright version?

Please advise how to fix the issue and what is causing it? Also please advise what the latest docker playwright image i can use which is compatible with 1.32.2 playwright version?

This is the command i use to docker image.

docker run -e TEST_ENV=dev -e TOKEN_URL="https://testurl.com" Imagename
(Passing token url as an env variable in the command line)

```javascript
 TypeError: apiRequestContext.post: Invalid URL
```
<img width="1417" alt="Screen Shot 2023-07-24 at 5 51 24 PM" src="https://github.com/microsoft/playwright/assets/113629123/3efb4b48-ece9-48e7-a558-de3df7c08475">

**Comment by pavelfeldman** [comment]
When things are working locally and do not work with Docker, we always assume the error on the configuration side. Try printing the environment within Docker and check that the values you are passing are passed correctly.

**Comment by InduKrish** [comment]
I printed the URL and it returns the valid URL in the console., not sure what is causing docker to return 'invalid url' error?

Can you please explain what usually causes it?

**Comment by pavelfeldman** [comment]
> Can you please explain what usually causes it?

Not really, we have not seen anything like that. Being able to reproduce would help, otherwise, we can't really act on the issue.

**Comment by InduKrish** [comment]
Our organization uses certs , am wondering if i have to install certs inside docker container to avoid the issue, not sure if docker is blocked to access the URL that is secured within our organization, any thoughts please?

**Comment by pavelfeldman** [comment]
That would certainly explain it

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
