### ISSUE TITLE
[BUG] "no test found" error when extending the 'test' function

### ISSUE THREAD

**Issue by Samuel29** [microsoft/playwright#24395]
**Context:**
- Playwright Version: `1.36.2`
- Operating System: Macos
- Node.js version: `v18.16.0`
- Visual Studio Code version: `1.80.1`
- Playwright for VSCode extension version: `1.0.15`
- Browser: All

**Code Snippet**

Hi !
Based on the "playwright init" example (using Chromium alone), I  extend the "test" function with the following

```ts
import { Page, TestInfo, test as testBase } from "@playwright/test"

const BASE_URL_PREFIX = "https://playwright.dev"

interface MyFixture {
  page: Page
}

export const test = function( title: string, testFunction: (fixtures: MyFixture, testInfo: TestInfo) => void) {
  // This closure allows us to create a 'database' for every test (enforcing test isolation)
  const db: MyDatabase = {
    userMocker: new UserMocker(),
    cfgMocker: new CfgMocker(),
    // ( .... same for all our entities )
  }
  return testBase.extend({
    page: async ({page}, use) =>{
      await page.route(/.*/, (route, request) => {
        const method: string = request.method()
        const url: string = request.url()

        // add warning for requests on different domains
        if (request.url()?.startsWith(BASE_URL_PREFIX) === false) {
          console.log(`EXTERNAL: ${method} ${url}`)
        }
        
        if (url.includes("api/user")) {
          return db.userMocker.route(route, request)
        }
        if (url.includes("api/cfg")) {
          return db.cfgMocker.route(route, request)
        }
        // (... same stuff for all entities / API endpoints ...)
        
        return route.continue()
      })
      await use(page)
    },
  }).call(this, title, testFunction)
}

```

then, in the `tests/exemple.spec.ts` file, I import it (instead of playwright's one)
```
import { test } from '../test-util/extend-test'
import { expect } from '@playwright/test';

(no change below)
```

**Describe the bug**

once the change above is saved and tests are refresh in Vscode:
- in example.spec.ts tab: the green triangle icons disappear from the gutter. 
<img width="543" alt="image" src="https://github.com/microsoft/playwright/assets/1901769/a05fe511-9b41-430d-b26b-85dfaecefd15">

- The green triangle now appears on the line of the `call(this, title, testFunction)`
<img width="615" alt="image" src="https://github.com/microsoft/playwright/assets/1901769/b912441d-95b5-4ad8-8793-958efee6b3ae">

- when right clicking on it, all the tests are shown together in the dropdown menu
- in the Testing sidebar: trying to run one single test in the tree-view  causes an error "no tests found" 
<img width="430" alt="image" src="https://github.com/microsoft/playwright/assets/1901769/947abcbd-39ab-472c-815c-90a8985aadf2">

- On the other hand: clicking on the parent file works well.
<img width="395" alt="image" src="https://github.com/microsoft/playwright/assets/1901769/9813cc6d-a72c-4f91-92d8-4ac06f8848f5">
- Same from terminal (control)

```sh
$ npx playwright test 

Running 2 tests using 2 workers
[chromium] › ../test-util/extend-test.ts:24:6 › get started link
EXTERNAL: GET https://playwright-analytics.azurewebsites.net/api/impression?hash=&path=%2F&language=node
[chromium] › ../test-util/extend-test.ts:24:6 › has title
EXTERNAL: GET https://playwright-analytics.azurewebsites.net/api/impression?hash=&path=%2F&language=node
[chromium] › ../test-util/extend-test.ts:24:6 › get started link
EXTERNAL: GET https://playwright-analytics.azurewebsites.net/api/impression?hash=&path=%2Fdocs%2Fintro&language=node
  2 passed (3.9s)
```
- as I was typing this message, I checked the output of `test --list` : 

```sh
$ npx playwright test --list
Listing tests:
  [chromium] › ../test-util/extend-test.ts:24:6 › has title
  [chromium] › ../test-util/extend-test.ts:24:6 › get started link
Total: 2 tests in 1 file
```

So. Playwright Fixtures work well in terminal or CI, but UX is degraded :
they're not correctly reported by playwright to the vscode extension

Any thought ?

**Comment by pavelfeldman** [comment]
Your wrapper is not equivalent to `test = testBase.extend(...)`, so it does not work.

**Comment by Samuel29** [comment]
Hi @pavelfeldman thanks for your feedback

The example above is an oversimplified version of our actual fixtures. I'll update it to better reflect our current code.
we have a "pseudo-database" to mock all our API backend, with an instance for each of our models
by using that closure we're sure that every single test uses a fresh new set of "database" instances.
we tried without using the closure: we have more flaky tests. test isolation doesn't look to be guaranteed...

**Comment by pavelfeldman** [comment]
You should keep it simple:

```js
export const test = testBase.extend({
  page: async ({page}, use) =>{
    const db: MyDatabase = {
      userMocker: new UserMocker(),
      cfgMocker: new CfgMocker(),
      // ( .... same for all our entities )
    };

    await page.route(/.*/, (route, request) => {
    ...
    await use(page);
  }
});
```

This way each test gets a page with its own database.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
