### ISSUE TITLE
[Feature] Support HTML reporter options when creating the report from blob

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#24390]
If I understand merged documentation correctly then merging blobs and creating other reports will only be possible via CLI. But CLI does not support all reporter options like `attachmentsBaseURL` https://playwright.dev/docs/test-reporters#html-reporter

Would be nice to set those options for creating reports from blob.

**Comment by pavelfeldman** [comment]
You can point to the config using -c and the reporter settings from that config will be used. This can be a separate config that only contains the reporter section, you don't need anything else there. Does it work for you?

**Comment by MindaugasMateika** [comment]
Yeap, that works. Wasn't aware that passing config was an option, it might be worth it to mention in docs on release.
