### ISSUE TITLE
[Feature] How to verify the background text of an element in typesciprt.

### ISSUE THREAD

**Issue by DeeptiSaxena09** [microsoft/playwright#24396]
I am trying to compare the background text of an element with the expected value using below code:

```
const button = page.locator(".sc-gtXRHa.sc-fYAFcb.bXcVqj").first();
  const color = await button.evaluate((el) => {
    return window.getComputedStyle(el).getPropertyValue('background-color');
  });
  
  expect(color).toBe("rgb(250 124 145)");
```
  
But getting below error on 'Window' :

`Cannot find name 'window'.`

Playwright version is ''1.32".

Can anyone please help here?

**Comment by pavelfeldman** [comment]
You should use https://playwright.dev/docs/next/api/class-locatorassertions#locator-assertions-to-have-css for that.
