### ISSUE TITLE
[BUG] Playwright locator.isVisible() returns true even when the attribute aria-hidden = true

### ISSUE THREAD

**Issue by MinoEclairs** [microsoft/playwright#24394]
### System info
- Playwright Version: [v1.33.0]
- Operating System: [Linux, windows 10]
- Browser: [ Chromium ]
- Other info:

### Source code

Playwright Code:

it('should click on date if the visible', async ({ page }) => {
    
  if (await page.locator("[aria-label="August 8, 2023"]").isVisible())
  {
     await page.locator("[aria-label="August 8, 2023"]").click();
  }

});

DOM of the element

![image](https://github.com/microsoft/playwright/assets/64079927/1f011396-9d45-40f8-8ada-36735cd4d24f)

**Steps**
- Go to site and open calender control
- check if the date is visible the click it.
- 
**Expected**
Doesn't click the date as it in the DOM but NOT visible on the screen

**Actual**

Click the date despite it being not visible on the screen

Note: My application is on react  using fluent ui

**Comment by pavelfeldman** [comment]
aria-hidden=true does not mean much as far as the rendering goes, so we don't consider it when assessing visibility. Try opening `data:text/html,<button aria-hidden=true>Submit</button>` in the browser. You can click it, tab focus into it, trigger it from the keyboard.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
