### ISSUE TITLE
[BUG] firefox does not pick up proxy settings in docker

### ISSUE THREAD

**Issue by sajTempler** [microsoft/playwright#2440]
**Context:**
- Playwright Version: [what Playwright version do you use?] 1.0.2
- Operating System: [e.g. Windows, Linux or Mac] Mac (running on official Docker image)
- Node version: [e.g. 10.12, 10.14] 12
- Browser: [e.g. All, Chromium, Firefox, WebKit] Firefox
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {firefox} = require('playwright-firefox');

(async () => {
  let browser;
  try {
    browser = await firefox.launch({
      headless: false,
      slowMo: 56,
    });
  } catch (e) {
    throw new Error(`Cant launch ${e.message}`);
  }
  const page = await browser.newPage();
  try {
    await page.goto("https://check.torproject.org/");
  } catch (e) {
    await browser.close();
    throw new Error("Cant navigate " + e.message);
  }
  const htmlOverview = await page.content();
  console.log("All done!", htmlOverview);
  await browser.close();
})();
```

**Describe the bug**
I run docker with socks proxy with env vars set
```
ENV http_proxy socks5://127.0.0.1:9060
ENV https_proxy socks5://127.0.0.1:9060
```

but Firefox does not pick up any proxy configuration

I tried manually setting `00-playwright-prefs.js` but configuration wasn't pick up either

When I `curl` inside container I can verify that proxy config (from env vars) is working correctly it's just that Firefox does not pick it up

it should be possible:
https://github.com/jlesage/docker-firefox/issues/11

**Comment by pavelfeldman** [comment]
Hang on, complete proxy support is a matter of a few days!

**Comment by sajTempler** [comment]
@pavelfeldman the PR looks promising

I just want to note that I tried to put those variables for firefox in _profile_ file but it wasn't picked up

**Comment by sajTempler** [comment]
verified with version 1.1.0 - this is fine now
