### ISSUE TITLE
[BUG] webkit waits for elements until timeout

### ISSUE THREAD

**Issue by valkum** [microsoft/playwright#24403]
### System info
- Playwright Version: v1.36.1
- Operating System: Docker Container x64/aarch64
- Browser: WebKit
- Other info:

### Source code

We are not able to create a minimal example. The application is a next.js application and when we take the subset of components and replace backend calls by timeouts, the webkit tests pass.

I can provide a repository which has a fitting Dockerfile, and tests that hit our staging env in private as well as traces from our CI.

**Steps**
- Run the test locally
- Run the test inside a docker container with CI=true

**Expected**

The tests ran in docker should yield the same result as locally.

**Actual**

Safari is very flaky. When run inside the playwright docker container, it is waiting endlessly for buttons that are clearly there and seem stable per traces.
The test works fine in Chrome and Firefox.

Desktop Safari seems to fail more often than the mobile version.
For the Desktop version, the generated Video does not cover the whole browser, which might be a hint.

Attached is the output from one of the Desktop Safari runs:
```
    Test timeout of 30000ms exceeded.
Error: locator.click: Target closed
=========================== logs ===========================
waiting for getByRole('button', { name: 'Edit' })
============================================================

   5 |   await page.getByRole("button", { name: "Create a demo" }).click();
   6 |   await expect(page).toHaveURL(/\.[0-9a-z\-_]+/);
>  7 |   await page.getByRole("button", { name: "Edit" }).click();
     |                                                    ^
   8 |   const description = page.getByPlaceholder("Description");
   9 |   await description.click();
  10 |   await description.type("This is only a test!", { delay: 50 });

    at /app/e2e/basic.spec.ts:7:52
Pending operations:
  - locator.click at e2e/basic.spec.ts:7:52


    Retry #1 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 30000ms exceeded.
Error: locator.click: Target closed
=========================== logs ===========================
waiting for getByRole('button', { name: 'Edit' })
============================================================

   5 |   await page.getByRole("button", { name: "Create a demo" }).click();
   6 |   await expect(page).toHaveURL(/\.[0-9a-z\-_]+/);
>  7 |   await page.getByRole("button", { name: "Edit" }).click();
     |                                                    ^
   8 |   const description = page.getByPlaceholder("Description");
   9 |   await description.click();
  10 |   await description.type("This is only a test!", { delay: 50 });

    at /app/e2e/basic.spec.ts:7:52
Pending operations:
  - locator.click at e2e/basic.spec.ts:7:52


    Retry #2 ───────────────────────────────────────────────────────────────────────────────────────

    Test timeout of 30000ms exceeded.
Error: locator.click: Target closed
=========================== logs ===========================
waiting for getByRole('button', { name: 'Edit' })
============================================================

   5 |   await page.getByRole("button", { name: "Create a demo" }).click();
   6 |   await expect(page).toHaveURL(/\.[0-9a-z\-_]+/);
>  7 |   await page.getByRole("button", { name: "Edit" }).click();
     |                                                    ^
   8 |   const description = page.getByPlaceholder("Description");
   9 |   await description.click();
  10 |   await description.type("This is only a test!", { delay: 50 });

    at /app/e2e/basic.spec.ts:7:52
Pending operations:
  - locator.click at e2e/basic.spec.ts:7:52
```

**Comment by valkum** [comment]
I will try to run the test with `--repeat-each=100` outside of docker on a VM with linux tomorrow. Even with `--repeat-each=100` I cannot get the tests to fail on MacOS. However, I am able to get them to fail consistently inside Docker (with Docker on Mac and with Docker on Linux).

As I said, I can send you the testfile, but I want to avoid posting it here as it contains the URL of our staging env which is not indexed.

**Comment by pavelfeldman** [comment]
The test file is of no use to me as long as it is not self-contained and is not reduced to a minimal repro...

**Comment by valkum** [comment]
Too bad. I tried to pinpoint the issue nevertheless.
I went ahead and ran the tests in a Linux VM with `headless: false`. Somehow, sometimes, the whole webkit render process got into a weird state where it rendered only a white background.
I saw some errors related to video rendering, which I ignored previously because I thought this might be normal for a headless run. I then thought maybe the video we use as a background might be a problem and added a `route.abort` for video files.
This way, I was able to get 100/100 successful runs. 
With the video request not blocked, I got 4 successful runs and 8 failed ones before the whole test run broke (resultless test runs in the report).

Looking at old traces, the video file has one failed request (but with HTTP 200 OK, the trace shows 0 as the top level status) and then a couple more requests. The respective file is 4MB in size.

**Comment by pavelfeldman** [comment]
Is there a way to share a page with that media file with us? If browser is crashing on that media, we should fix it.

**Comment by valkum** [comment]
I have a static export with the main outbound requests patched to noops now. This shows the same behavior. I can send you an archive of the reproducible case. The zip file is 8MB.

**Comment by pavelfeldman** [comment]
> I have a static export with the main outbound requests patched to noops now. This shows the same behavior. I can send you an archive of the reproducible case. The zip file is 8MB.

Could you DM it to me via Discord?

**Comment by pavelfeldman** [comment]
I have a project and a trace in hand. It is reported that WebKit in Docker crashes on certain media file.

**Comment by pavelfeldman** [comment]
@valkum your page has a [hydration](https://playwright.dev/docs/next/navigations#hydration) bug. If you open your page in Slow 3G mode and click "Create the demo" button, nothing will happen.

**Comment by pavelfeldman** [comment]
(btw, replace your `.type` with `.fill` - type is for testing autocomplete, etc.

**Comment by valkum** [comment]
We explicitly use type here because we hide some parts when the user focuses an input field. Using `fill` without any waits in between would be racy. This is more human like.

I will talk with our team if there is anything we can do about the hydration bug.

**Comment by dgozman** [comment]
It looks like there is no action item from Playwright side, so closing this issue. If you believe there is a bug to be fixed, please file a new issue with a repro using the "Bug Report" template and link to this one.

**Comment by ctacquet** [comment]
Hello, I'm getting exactly the same problem.
All my tests are passing but on Mobile Safari (with iPhone 12 or 14 device configured) I'm getting timeout.
On my mac all tests are going, even with `--repeat-each=100`, but on CI (with Linux) some tests are going to timeout.
Did you just removed Mobile Safari or did you find something ?

Thanks for the report by the way !

**Comment by lilezek** [comment]
Not sure if this is the same thing, but in Safari, I also get a timeout. I'm running this inside an ubuntu container in a github action. 

The video of the test shows some "resolution shaking", which I don't know if it has anything to do. This doesn't happen in any other environment
[video.webm](https://github.com/microsoft/playwright/assets/2767229/d25cf5da-0425-4fa9-9814-897c70cab82a)

**Comment by dseeto** [comment]
Running into a similar issue within a ubuntu-22.04 runner in a github action. Have a test which finds an enabled button, but times out when clicking it specifically for iphone14, but not other desktop/mobile android browers. When ran locally, this test for iphone14 also passes.

@dgozman Seems like there's now 3 reports since closing. Are you able to follow-up/reopen? Thanks!

**Comment by harleyharl** [comment]
Same issues here. Running playwright 1.48 in my Gitlab pipeline with Chromium, Firefox and WebKit with mcr.microsoft.com/playwright:v1.48.0-jammy. WebKit is very flaky with timeouts occuring. The others always pass. The output videos show the test completing in 10s on Chromium and Firefox and on Webkit they almost finish but time out at 30 seconds. 

Does anyone know why WebKit is so slow in Playwright? I'm not seeing slow loading times on Safari on MacOS

**Comment by cguinard-fbx** [comment]
same for me here, running 1.48 in my Gitlab pipeline with Chromium, Firefox and WebKit with mcr.microsoft.com/playwright:v1.48.0-jammy. WebKit is very flaky with timeouts occuring. The others always pass!

**Comment by bbchuoo** [comment]
I have the same issue with Playwright 1.48.1. Both Chromium and Firefox complete within seconds. I modified the timeout to prevent WebKit from failing, but it still takes a very long time. Due to personal reasons, I can't provide the code. I would appreciate it if anyone with the same problem could provide a sample to the official team. Thank you very much.

**Comment by MartinPaulo** [comment]
I have this problem as well. However, in my case changing the version of yarn in use seems to fix it. With Yarn 3.7.0 I get timeouts on webkit `getByRole` calls. If, however, I drop back to Yarn 1.2.2 those selfsame tests pass.
