### ISSUE TITLE
[Question] Page hangs after navigation. DOM exception is thrown only in playwright.

### ISSUE THREAD

**Issue by yabols** [microsoft/playwright#24400]
Hi, 

I'm using playwright .net, and I hit a weird problem, on the page I have something like survey, some questions contains audio.
When I start this survey, there is some "middle page" with loader and setup data, at least this is my assumption as this page is unfortunately black box for me. 

Issue is when I start survey  in playwright on chrome I get this error
`Uncaught (in promise) DOMException: Failed to execute 'decodeAudioData' on 'BaseAudioContext': Unable to decode audio data` and everything hangs.
I added listener to page.PageError  but information is similar that I get from console, only thing more is that something is invoked few times 
`
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error : undefined
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
Error DOMException: Failed to execute "decodeAudioData" on "BaseAudioContext": Unable to decode audio data
`

When I'm using normal browser( I tried edge,firefox, opera, safari) everything seems to work. 

Is there any setting that can allow ignoring this error(I don't need audio)  or any place I could look for what is wrong? 

Regards 
Lukasz

**Comment by pavelfeldman** [comment]
This does not look like a feature request or a bug report, please try asking on Playwright Discord instead.
