### ISSUE TITLE
i need a help to store and use session storage in playwright sync

### ISSUE THREAD

**Issue by KKCODER777** [microsoft/playwright#24419]
i need a help to store and use session storage in playwright sync and can you give me some options to make the code undetectable.

**Comment by pavelfeldman** [comment]
This does not look like a feature request or a bug report, closing

**Comment by barbolo** [comment]
A user session might be composed of several things, but `cookies` and `localStorage` is usually what a website uses to keep track of the "session" of a user. Sometimes `sessionStorage` might also be used, but this storage is different for each browser tab so it probably doesn't make much sense to reuse it across multiple executions.

This is how you get the state (`cookies` and `localStorage`) after using a `context` with playwright:

```javascript
const storageState = await context.storageState();
```

And this is how you start a new context with the same state:

```javascript
const context = await browser.newContext({storageState: storageState});
```

**Comment by Semensemenu4** [comment]
Hi all! In my project we use only session storage. Can you help and tell me where to find information on how to work with a sessionstorage (get and use) from playwright? Thnx
