### ISSUE TITLE
[BUG] API Test expect failed even it's matched 

### ISSUE THREAD

**Issue by shane51** [microsoft/playwright#24417]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [Windows 11,]
- Browser: [chrome 113.0.5672.127]
- Other info:

### Source code

```ts
    expect(response.ok()).toBeTruthy;
    expect(await response.json()).toContainEqual(
      // expect.objectContaining(
        {
        "success":true,
        "code":0,
        "message":null,
        "payload":"CN"
      }
      // )
      );

```

**Steps**
- [Run the test]

I get:

```shell
 Error: expect(received).toContainEqual(expected) // deep equality

    Expected value:  {"code": 0, "message": null, "payload": "CN", "success": true}
    Received object: {"code": 0, "message": null, "payload": "CN", "success": true}

      30 |     const response = await apiContext.get('some url');
      31 |     expect(response.ok()).toBeTruthy;
    > 32 |     expect(await response.json()).toContainEqual(
         |                                   ^
      33 |       // expect.objectContaining(
      34 |         {
      35 |         "success":true,

```

**Expected**

[Describe expected behavior]
it should pass, however, it tells it's different.  I did't see any difference.

**Actual**

[Describe actual behavior]
![image](https://github.com/microsoft/playwright/assets/4371504/aec40cf1-9bba-468c-9aeb-2e13e64be506)

**Comment by shane51** [comment]
After some investigation, the correct syntax should be 
```ts
      expect(await response.json()).toEqual(
      expect.objectContaining({
        "success":true,
        "code":0,
        "message":null,
        "payload":"CN"
      }));
```

Would you mind add more doc for playwright API testing?

**Comment by aslushnikov** [comment]
We landed new docs to address the `objectContaining` usage; the docs will go live with 1.37 release.
