### ISSUE TITLE
[BUG] installation does not work (with node LTS and current version)

### ISSUE THREAD

**Issue by plehnen** [microsoft/playwright#24418]
### System info
- Operating System: Windows 11

### Source code

I was just about to give playwright a try and run `yarn create playwright`.
But t fails with this error:

```
error @achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module.
Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "18.16.0"
```
I've got "18.16.0" installed
LTS is "18.17.0"
Current is "20.5.0"

**Comment by pavelfeldman** [comment]
Playwright does not use node-ipc, looks like the folder you are running yarn in contains a broken project?

**Comment by plehnen** [comment]
Playwright itself maybe doesnt, but the "create" thingy does apparently. 
I tried it via "npm" and that worked eventually. 

to be clear: our existing project does not use "node-ipc" (also no peer dependency. no entry in yarn.lock).
All I did was executing what's written in the documentation: `yarn create playwright` - running directly into that error.

**Comment by plehnen** [comment]
Cool - at least after calling `yarn global remove @vue/cli` I was able to successfully run `yarn create playwright` now.
So I guess this will solve the issue, if anyone else are running into the same problem. Thanks for the advice!
