### ISSUE TITLE
[BUG] Playwright retuns eturns net::ERR_HTTP_RESPONSE_CODE_FAILURE. while running the tests in the pipeline.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24425]
### System info
- Playwright Version: 1.32.2
- Operating System: MAC
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

While running the tests in the pipeline, it returns net::ERR_HTTP_RESPONSE_CODE_FAILURE. tests work in local, 

and i do have contextOptions : {ignoreHTTPSErrors: true}, in playwright config file, can you please advise how to fix the issue?

**Comment by pavelfeldman** [comment]
Something is wrong with your pipeline setup, it can't open the urls you are trying to visit.

**Comment by dheeman00** [comment]
"ERR_HTTP_RESPONSE_CODE_FAILURE" Is it possible to share some explanation related to this error? Then there can be a possibility to rectify this error.

**Comment by humayunmiah657** [comment]
Pay Money My Bank Account Humayun Miah Bank of America A/C 483115401687 & 483115401690 
Routing Number 031000322, 
9053 Sutphin Blvd Jamaica New York 11435
Phone Number 3475922940
Email ID abuse@bofa.com
https//www.bankofamerica.com

**Comment by humayunmiah657** [comment]
[personal-schedule-fees.pdf](https://github.com/user-attachments/files/31529220/personal-schedule-fees.pdf)

[us-online-privacy-notice-es.pdf](https://github.com/user-attachments/files/31529222/us-online-privacy-notice-es.pdf)

[Samsung Privacy Policy.html](https://github.com/user-attachments/files/31529234/Samsung.Privacy.Policy.html)

**Comment by humayunmiah657** [comment]
<img width="2560" height="2560" alt="Image" src="https://github.com/user-attachments/assets/6e54ac40-cd83-41fc-b1b8-405d2e532395" />

abuse@bofa.com
www.bankofamerica.com 
Humayun Miah 
Email ID mr.humayunbd@gmail.com
