### ISSUE TITLE
[Feature] VSCode extension, ability to stop tests

### ISSUE THREAD

**Issue by jaakidup** [microsoft/playwright#24423]
Playwright is a great tool. Thanks for the development of it 👍🏻
It is making testing so much easier. 

The feature I'm looking for is in the VSCode extension specifically. 
It's great to see the different tests and the ability to run them individually. 

It would be great to have a way to Stop a test as well in the Test Explorer. 

It has happened that as a test is running, a file can be changed, which would cause the test run continuously, 
showing the spinning wheel, but no feedback in the code. 
There is now no way to stop the stuck test. 

I'd gladly ticket this as a bug if needed. 

<img width="564" alt="Pllaywright_feature" src="https://github.com/microsoft/playwright/assets/25294710/16f3dff8-fb97-4869-a9da-da2a6ddbdc54">

**Comment by pavelfeldman** [comment]
I'm running the test and then I'm editing it while it is running, but I can't get it into the spinning state. Could you provide the steps I can follow to reproduce?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by jaakidup** [comment]
Yes sure, I will do that. 
As I've been keeping an eye on the tests to reproduce it, I've noticed a number of similar issues with hanging states in indicators. 
So I want to rule out the possibility that it could be anything to do with my own machine first. 

I'll get back to you with a full report 👍🏻
