### ISSUE TITLE
[BUG]Same test element hovering is different on Safari

### ISSUE THREAD

**Issue by ValorHeart** [microsoft/playwright#24429]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [macOS 13.2]
- Browser: [WebKit]

**Description**
Unfortunately, I haven't been able to reproduce it on the TodoMVC app so far.

The test is hovering over a chart X Axis label.
On **Chrome** & **Firefox**, it works flawlessly, on **Safari**, it fails.
In the attached images from the Tracer, we can see how the red dot on Chrome and Safari are in different locations.

Is there any type of way to export debug information so I could investigate it further, or assist more in providing useful information?

**Expected: Chrome/Firefox**
<img width="2149" alt="image" src="https://github.com/microsoft/playwright/assets/61405630/f35fe6e5-6703-4218-a0a7-ea888a1ea07e">

**Actual: Safari**
![image](https://github.com/microsoft/playwright/assets/61405630/1a3e6abd-69ea-436d-94a7-494a54b6277b)

**Comment by pavelfeldman** [comment]
I would just debug it step by step in Safari and see why it resolves to a different element. I can already see that you are forcing the click and are clicking with the negative offset (outside of the element). So I guess something went wrong even earlier?

**Comment by ValorHeart** [comment]
I'm not clicking at all, I'm hovering with `await axis.locator.hover({ force: true, position: { x: 0, y: -15 } });`

I'm forcing the hover because I want to hover above the x-axis label; only then will it pop up a tooltip inside the chart. If I do not force, the hover will fail on actionability.

As you can see in both screenshots, it resolved to the same element with the exact location (Y=216, X=131), and yet, Safatri still hovers in a different area.

For Debugging purposes, I've removed the 'force' and the negative offset and the same issue still occurs; see screenshots:

**Chrome/Firefox**
![image](https://github.com/microsoft/playwright/assets/61405630/dca3fffc-8e6d-4e2d-9bfa-2e8bb34087c5)

**Safari**
<img width="1896" alt="image" src="https://github.com/microsoft/playwright/assets/61405630/5f9df71a-6624-4f5b-9b65-1edd69ad3af2">

**Comment by pavelfeldman** [comment]
Is there a chance you share the trace with us? It should have a DOM snapshot and maybe opening it in Safari will give us a better idea on what is going on.

**Comment by ValorHeart** [comment]
Attached, Find the issue from here:
<img width="261" alt="image" src="https://github.com/microsoft/playwright/assets/61405630/207387ca-b7bb-4e60-8e77-2a1ad272080a">
[safari_trace_issue.zip](https://github.com/microsoft/playwright/files/12191302/safari_trace_issue.zip)
[chrome_trace.zip](https://github.com/microsoft/playwright/files/12191307/chrome_trace.zip)

**Comment by pavelfeldman** [comment]
Safari is broken in terms of locating `<text>` inside `<svg>`. When I highlight that `<text>` element in Web Inspector, I see it at this wrong location.

<img width="415" alt="Screenshot 2023-07-28 at 4 53 22 PM" src="https://github.com/microsoft/playwright/assets/883973/f24b0a8a-a2e5-4368-9f17-2085a859fc25">

**Comment by ValorHeart** [comment]
Thank you so much, Pavel; it's so embarrassing it didn't up to my mind it would be a bug in Safari...🫢
