### ISSUE TITLE
[Question]: A combination of playwright and selenium grid(hub-node)

### ISSUE THREAD

**Issue by gcil125** [microsoft/playwright#24427]
### Your question

import sys

import pytest
from playwright.sync_api import sync_playwright

def test_demo():
    with sync_playwright() as pw:
        browser = pw.chromium.launch(env={"SELENIUM_REMOTE_URL":"http://selenium-hub-ip:4444"})
        # browser = pw.chromium.launch()
        page = browser.new_page()
        page.goto("https://www.baidu.com")
        page.wait_for_timeout(1000)

if __name__ == '__main__':
    pytest.main([
        "./test_demo.py"
    ])

Seem not to have
However, cmd`SELENIUM_REMOTE_URL=http://selenium-hub-ip:4444 pytest./case/test_demo.py `is available

**Comment by pavelfeldman** [comment]
Does not look like a feature request or a bug report, closing!
