### ISSUE TITLE
[BUG] Test finished within timeout of 180000ms, but tearing down "page" ran out of time.

### ISSUE THREAD

**Issue by aarroyave-deloitte** [microsoft/playwright#24430]
### System info
- Playwright Version: v1.36.2
- Operating System: Windows
- Browser: Chromium
- Other info:

### Source code
***ConfigFile***
```js
export default defineConfig({
  testDir: 'src',
  retries: 1,
  use: {
    headless: false,
    trace: 'off',
  },
  projects: [
    {
      name: 'setup',
      testMatch: /global.setup/,
    },
    {
      name: 'initial-setup',
      testMatch: /.initial-setup.spec/,
      dependencies: ['setup'],
      use: {
        storageState: 'owner-storage-state.json',
      },
    },
    {
      name: 'all-test-suite',
      testIgnore: /.initial-setup.spec/,
      fullyParallel: true,
      dependencies: ['setup'],
      use: {
        storageState: 'owner-storage-state.json',
      },
    },
  ],
});
```

**Global setup**

```js
import { test as setup } from './core'; // custom fixture

setup('Login', async ({ page, logger }) => {
  logger.logInfo('Starting execution of Login.');
  await login(page, logger);
  logger.logInfo('Finish execution of Login.');
});
```

I don't add the code of the test as the issue happens before even reaching the first test. See below.

**Steps**
- The code is working fine in Playwright v1.31.2. It starts running the global setup, then it runs the project's tests. 
- After upgrading to 1.36.2 (Latest version as of now) I run the test, so it ran the global setup successfully (it logs the "finish login" message) but the browser never closes. After a while I get this error 
`Test finished within timeout of 180000ms, but tearing down "page" ran out of time.
  Please allow more time for the test, since teardown is attributed towards the test timeout budget.`
  
  - Playwright v1.36.1 had the same error but slightly different. After the global setup ended, it keep the browser open, but started running the project tests. When the error arise both browser shat down and the result of the test being executed was "interrupted".

I've seen similar error but regarding to "context" rather than "page". I did what provided in other solutions (use `await` in `expect ` https://github.com/microsoft/playwright/issues/17869, turn off traces https://github.com/microsoft/playwright/issues/24210 (which is more like a workaround than a solution)). Nothing works.

Please review.

**Comment by pavelfeldman** [comment]
We need to be able to reproduce the error in order to fix it. For some reason, page can't be close, but we have no way of knowing whether this is Playwright itself or your fixture overrides to blame.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
