### ISSUE TITLE
"isEnabled" throws exception if element disabled.

### ISSUE THREAD

**Issue by quldude** [microsoft/playwright#24434]
I have the following code:
```
const enabled = await element.isEnabled({ timeout: 3000 });
```

This is throwing an error when element is disabled. But I'm expecting a true or false. What is the best way to avoid an exception being thrown?

**Comment by pavelfeldman** [comment]
Please follow the bug template when filing the issue so that we could reproduce it. `isEnabled` is not throwing in our tests.
