### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by chandnaBR** [microsoft/playwright#24438]
Getting error - Error: browserType.launch: spawn UNKNOWN when I try to execute example.spec.ts
I've the latest version of playwright and chrome browser
playwright version - 1.36.1
chrome version - 115.0.5790.110

### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by tejaswikommineni** [comment]
Hi,

getting the  Error: browserType.launch: spawn UNKNOWN.while running the basic eamples.spec.ts file,iam getting the error.could any one help me with the issue
