### ISSUE TITLE
[BUG] Importing local module in test file results in "Invalid or unexpected token"

### ISSUE THREAD

**Issue by bensampaio** [microsoft/playwright#24459]
### System info
- Playwright Version: 1.36.2
- Operating System: macOS 13.3
- Browser: Chrome

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**TypeScript config**
```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "allowJs": true,
    "allowSyntheticDefaultImports": true,
    "jsx": "preserve",
    "removeComments": false,
    "preserveConstEnums": true,
    "sourceMap": true,
    "skipLibCheck": true,
    "baseUrl": ".",
    "typeRoots": ["./node_modules/@types"],
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve"
  },
  "exclude": [
    "node_modules",
    "**/*.spec.ts",
    "**/*.spec.tsx",
    "**/*.test.ts",
    "**/*.test.tsx"
  ],
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"]
}
```

**Config file**
```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  testMatch: '*.pw.ts',
  use: {
    baseURL: 'http://localhost:1234',
    trace: 'on-first-retry',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

import { entityMock } from 'src/pages/SomePage/__mocks__/entity';

const reference = 'somereference';

test.beforeEach(async ({ context, page }) => {
  await context.addCookies([
    {
      name: 'user_id',
      value: 'sometoken',
      domain: 'localhost',
      path: '/',
    },
  ]);

  await page.route(
    `/some/path/${reference}`,
    async (route) => {
      await route.fulfill({ json: entityMock });
    }
  );

  await page.goto(`/en/some/path/${reference}`);
});

test('has title', async ({ page }) => {
  await expect(page).toHaveTitle(`Entity ${reference}`);
});
```

**Steps**
- Create module `src/pages/SomePage/__mocks__/entity` exporting an object called `entity`.
- Run the test with `PW_EXPERIMENTAL_TS_ESM=1 yarn playwright test`.
- Test run fails with error "Invalid or unexpected token" on line 3 of test file.

**Expected**

Import statements are resolved correctly and test runs successfully.

**Actual**

Import syntax seems to be considered invalid only for local modules because it works for `@playwright/test`.

I have a lot of utilities for mocks and generating URLs that I **need** to use in tests. This is possible with Cypress but I don't seem to find a way to do this with Playwright. How can this issue be fixed?

**Comment by bensampaio** [comment]
Somehow after a few restarts the above issue got fixed. The import is being resolved correctly. But now I come across another transpilation issue. In my project, I use some internal libraries which are written in TypeScript and are installed via yarn. Somehow Playwright is skipping the translation of files inside the `node_modules` folder and then gives me an error for `export` statements: "Unexpected token 'export'". Any ideas on what might be missing?

**Comment by pavelfeldman** [comment]
We need to be able to run your code in order to tell what is wrong. Note that PW_EXPERIMENTAL_TS_ESM has been since removed, esm support is official for quite some time.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
