### ISSUE TITLE
[BUG] Executable doesn't exist on remote build for Linux Azure Functions

### ISSUE THREAD

**Issue by falkon13** [microsoft/playwright#24455]
Hi,
We have been having issues with using Playwright Test usings in TypeScript in our Azure Function App on a Linux Consumption Plan. The issue is that the browser cannot be found and we get the error

{"message":"Stage 'Stage 2 - Start Browser' failed: Error: browserType.launch: Executable doesn't exist at /home/site/wwwroot/node_modules/playwright-core/.local-browsers/chromium-1071/chrome-linux/chrome\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║                                                                         ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝","stack":"Error: Stage 'Stage 2 - Start Browser' failed: Error: browserType.launch: Executable doesn't exist at /home/site/wwwroot/node_modules/playwright-core/.local-browsers/chromium-1071/chrome-linux/chrome\n╔═════════════════════════════════════════════════════════════════════════╗\n║ Looks like Playwright Test or Playwright was just installed or updated. ║\n║ Please run the following command to download new browsers:              ║\n║                                                                         ║\n║     npx playwright install                                              ║\n║                                                                         ║\n║ <3 Playwright Team                                                      ║\n╚═════════════════════════════════════════════════════════════════════════╝\n    at Stage2StartBrowser.<anonymous> (/home/site/wwwroot/src/Models/Stage.ts:36:13)\n    at Generator.throw (<anonymous>)\n    at rejected (/home/site/wwwroot/dist/src/Models/Stage.js:6:65)"}

 It seems like the node modules folder doesn't seem to output the correct structure when performing a remote build hence why it can't find the browser.
In the past we have used the "playwright-chromium" package which builds a correct node_modules output and the Function App can find and run the browser and as such we can use the browser there, however the reduced selector support makes it unusable for our latest project so we are trying ti use Playwright Test

### System info
- Playwright Version: [v^1.36.2]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info: Works perfectly fine when our usings are from "playwright-chromium" 1.3.0

**Steps**
1) In Azure created a Linux & Node.js Azure Function App on a Consumption Plan
2) Create a function app in VS Code using a headless browser
3) Build using func azure functionapp publish [FUNC_APP_NAME] --build remote --javascript
4) Navigate to generate URL to run function app and get the error

**Expected**
This is the file structure that gets outputted to our Function App when use a remote build when using "playwright-chromium" usings in TypeScript
![image](https://github.com/microsoft/playwright/assets/6588035/df270f13-5db4-459f-9b01-bb562bf446a4)

This structure has the .local-browsers folder which contains the executuable that my Function App can run.

**Actual**
This is the file structure that gets outputted to our Function App when use a remote build when using @playwright/test usings in TypeScript
![image](https://github.com/microsoft/playwright/assets/6588035/5e6b58e3-c7f7-40c9-8af1-564da2094e44)
This structure does not have the .local-browsers folder so the Funcion App fails as it can't find the browser

**Comment by pavelfeldman** [comment]
Looks like you are passing `PLAYWRIGHT_BROWSERS_PATH=0` when running tests, but not when installing the browsers? You should use consistent environment between the installation and the runtime.

**Comment by falkon13** [comment]
I can't see that being passed in anywhere, the only place I have it located is as an app setting on my Function App.

That being said I've figured out why this is failing for @playwright/test and not playwright-chromium and it's not a bug so I guess this can be closed

**Comment by domleggio** [comment]
@falkon13 I am having the same issue. What ended up solving it for you?

**Comment by MatthewIreti** [comment]
@falkon13 I am having the same issue. What ended up solving it for you?

**Comment by alfredbirk** [comment]
![SCR-20240226-jwrf](https://github.com/microsoft/playwright/assets/11172530/930791c9-a008-4093-aa1e-be604d606495)

**Comment by ecancil** [comment]
@falkon13  Thanks for sharing with the class
