### ISSUE TITLE
[BUG] Webkit headed mode automatically zooms in, unable to scale the site to fit the browser

### ISSUE THREAD

**Issue by symisz** [microsoft/playwright#24457]
**Context:**
- Operating System: Windows 11
- Node.js version: v18.15.0
- Visual Studio Code version: 1.80.1
- Playwright for VSCode extension version: v1.0.15
- Browser: WebKit
- Extra: WSL version: 1.3.14.0
Kernel version: 5.15.90.3-1
WSLg version: 1.0.55
MSRDC version: 1.2.4419
Direct3D version: 1.608.2-61064218
DXCore version: 10.0.25880.1000-230602-1350.main
Windows version: 10.0.22631.2115

**Code Snippet**

```json
"test:all": "npx playwright test mytest.spec.ts --headed",
```

```js
import { test } from '@playwright/test';

test('test browser', async ({ page }) => {
  // point this to wherever you want
  await page.goto('https://playwright.dev/')

  // keep browser open
  await page.pause()
  
});
```

**Describe the bug**

I'm using the Playwright VScode extension on WSL2.
And Webkit headed mode automatically zooms in, unable to scale the site to fit the browser.
Firefox and Chromium don't have this problem.

The bug occurs immediately when inspecting the code with dev tools. 

As seen below this how the website will scale and while it might look okay initially, when you click on links on the site, it will eventually bug out, scaling the website like this. And there is no way to scale it back.

![Screenshot 2023-07-26 171652](https://github.com/microsoft/playwright/assets/32195791/86e1f305-f11e-4e71-b3ca-3b9821369f33)

**Comment by symisz** [comment]
I see, so the default value is set to simulate the Apple Retina display, that makes sense.  Thank you, that piece of information solved the scaling and I share this on Discord for others to find it? I have no problems inspecting with dev tools anymore.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by Arebi-Proficom** [comment]
Hi everyone, 
unfortunately setting the scale to (deviceScaleFactor: 1) did not solve the problem for me. 
Any other suggestions? 

BR.
