### ISSUE TITLE
[Feature] toHaveScreenshot  can capture  the full contents of the element, including scrolled out content

### ISSUE THREAD

**Issue by 627668410** [microsoft/playwright#24458]
My page features a fixed header, and the scrollbar is limited to the content section, which fails to trigger  the fullPage configuration option. Additionally, there are some uncertain elements on the page, and I wish to save screenshots only for specific, identifiable elements rather than capturing the entire page. Therefore, I hope to overlay the screenshot of the scrollbar onto the elements.

**Comment by pavelfeldman** [comment]
What happens if you take a screenshot today? Could you provide repro steps (code) along with the screenshot examples and the expectations?

**Comment by 627668410** [comment]
> What happens if you take a screenshot today? Could you provide repro steps (code) along with the screenshot examples and the expectations?

I have a large form on my page, and its content triggers a scrollbar. I want to ensure the form is being saved correctly by comparing screenshots. However, due to the presence of a fixed header on my page and the fact that the scrollbar is within the content section, I am unable to trigger the fullPage option. As a result, I can only capture the visible portion of the form and cannot obtain a screenshot of the entire form.

**Comment by pavelfeldman** [comment]
That makes sense. The way element screenshot works is that it resizes the viewport to fit element and moves element to 0,0 of the viewport that it captures. I can see how fixed toolbar is going to be a problem. Detecting it would be tricky for us, so I'd say it is Playwright limitation.

**Comment by pavelfeldman** [comment]
Closing as not feasible.
