### ISSUE TITLE
Keyboard shortcuts for chrome browser extension not supporting in playwright scripts

### ISSUE THREAD

**Issue by Sneha-Jayakumar** [microsoft/playwright#24462]
I generated a script using playwright fixtures and a test file for automating chrome extension under development(manifest V3), and the Chrome extensions html page appeared, however, I am unable to interact with the extension via keyboard shortcuts on my new tab page. could you please help

**await page.keyboard.press("Shift+Alt+Comma");**

**Comment by pavelfeldman** [comment]
This does not look like a feature request or a bug report, please ask your question on Playwright Discord!

**Comment by prathithacb** [comment]
I am also facing similar issue with keyboard shortcuts and mouse events in the chrome browser extension while trying to automate the extension functionality through Playwright.
