### ISSUE TITLE
[Feature] Generic assertion to check Object against structure (keys name and theirs type)

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#24460]
By investigate: https://playwright.dev/docs/api/class-genericassertions#generic-assertions-to-match-object

I tried every single assertion but I can't assert 2 object against only structure (I mean theirs keys and type). The closes to my expectation is `toMatchObject` but this function also check detailed value of key.

Below example of my problem:

```
let receivedObject = {
name:'Andrew',
age: 15
 };
 
let templateObject =  {
name: 'Jack',
age: 21
};

expect(receivedObject).toMatchObject(templateObject) // False
```
I would like to be able to call an assertion that will check the **types of keys** (string -> string, number -> number) and their **names** - that is, in the above case, return true.
Problem I can solve by using additional `chai` library, but do not want to install additional node package.

The only thing I managed is to bring the comparison by key names only, but this is not a full test in my case. By using empty object as a keys values in `templateObject`:

```
let receivedObject = {
name:'Andrew',
age: 15
 };
 
let templateObject =  
{ 
name: {},
age: {}
};

expect(receivedObject).toMatchObject(templateObject) // True
```

**Comment by OSnuszka** [comment]
@pavelfeldman it's working, thanks. 
But the dream is using dedicated function. In my tests cases I've huge JSON files with 200 - 300 keys to compare (declaring `expect.any` for each of them may be time consuming.

**Comment by aslushnikov** [comment]
@dgozman: docs todo:
- `s/popular/auto-retrying/` assertions
- let's add `await` to the list of the auto-retrying assertions
