### ISSUE TITLE
[Feature] Expose browserContext.on('pageerror') for capturing exceptions

### ISSUE THREAD

**Issue by vigneshshanmugam** [microsoft/playwright#24466]
Currently when page issues requests, we can use the `pageerror` event on the page to capture the unhandled exceptions that happen on that given page. But if the page opens a new popup or window, we would have to manually listen to these `pageerror` on those next set of pages to be able to capture these exceptions. 

In an ideal scenario, It would be better to expose this information via the BrowserContext which would hold all the Unhandled exceptions that happen on the pages that are created within this context. 

```ts
const context = await browser.newContext();

context.on("pageerror", (error, page?) => {
   // error -> unhandled exception
});
```

It also sync with other API's like the `context.on("error", (error) => {})` where we can log all the error's that happen on all the pages created by this context.

**Comment by pavelfeldman** [comment]
I'm supportive of the idea, will look at the patch, thanks!
