### ISSUE TITLE
[Documentation] Inconsistency between docs and the actual code

### ISSUE THREAD

**Issue by alexkuc** [microsoft/playwright#24469]
### System info
- Playwright Version: 1.36.1
- Operating System: Ubuntu LTS
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```ts
import { test } from '@playwright/test';

test('', async(fixtures, testInfo) => {
	fixtures;
});
```

According to [docs](https://playwright.dev/docs/api/class-test#test-call), 1st argument of `testFunction` is [Fixtures](https://playwright.dev/docs/api/class-fixtures). However, when actually writing code, I am seeing _properties_ of fixtures in addition to fixtures:

![image](https://github.com/microsoft/playwright/assets/3331946/90e247d8-257e-473e-96f4-89fc4167ca7d)

This doesn't really make sense from the documentation point of since [built-in fixtures](https://playwright.dev/docs/test-fixtures#built-in-fixtures) only list 6 fixtures. Further more, in [Auth guide](https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker) we are shown that we can override `storageState` "fixture". However, `storageState` is really property of [Context fixture](https://playwright.dev/docs/api/class-browsercontext#browser-context-storage-state) and not a standalone fixture.

I guess for newcomers it's a bit confusing since fixtures and their properties are used interchangeably. For example, you can override the entire `Page` class or just `storageState`. Also, it is not really stated that `testFunction` splats fixtures where you can also access properties of the fixtures. It's really confusing when you expect 6 fixtures but instead presented with a list of dozens and not really sure (initially) where those come from.

**Comment by pavelfeldman** [comment]
What you are seeing are fixtures. We are manually creating fixtures for some of the popular properties for convenience. You can use and override those fixtures to define corresponding properties.

**Comment by alexkuc** [comment]
> We are manually creating fixtures for some of the popular properties for convenience.

Perhaps, it would be helpful for others if it was also part of the docs?
