### ISSUE TITLE
[Feature] Add a 'find timeout'

### ISSUE THREAD

**Issue by takeshi-yanagita** [microsoft/playwright#24479]
Currently there's only 2 kinds of timeouts Test timeout and Expect timeout.

However, I've felt that there needs to be a 3rd kind of timeout for when an element was not found.

If an element is not found, the test needs to run for the whole duration of the Test timeout before a failure is returned.  This feels really bad since test timeout is usually set to something like 2 minutes to allow for all tests to run within the time.  That means for each time an element is not found, the test needs to run for much longer than it usually would had it found the element.

Therefore, it would be nice to have a 'find timeout' that allows you to define how long the application will wait before failing, thus saving much execution time.

**Comment by Nav-2d** [comment]
Are you looking for actionTimeout? https://playwright.dev/docs/test-timeouts#advanced-low-level-timeouts

**Comment by takeshi-yanagita** [comment]
@Nav-2d oh my gosh that's the one.
How did I not see the advanced section at the bottom.
I've looked through that page a dozen times...
