### ISSUE TITLE
[Question] View PDFs using WebKit

### ISSUE THREAD

**Issue by dornelas-hw** [microsoft/playwright#24474]
### **Is there a way to view PDFs using Webkit and without downloading if possible?**
Here is a simplified test to show what I'm trying to do:
        public async Task ViewPdfWithWebkit()
        {
            var playwright = await Playwright.CreateAsync();
            var browser = await playwright.Webkit.LaunchAsync();
            var browserContext = await browser.NewContextAsync();
            var Page = await browserContext.NewPageAsync();
            await Page.GotoAsync("https://www.africau.edu/images/default/sample.pdf");
        }

**I keep getting this exception:**
ViewPdfWithWebkit threw exception: 
Microsoft.Playwright.PlaywrightException: Download is starting
navigating to "https://www.africau.edu/images/default/sample.pdf", waiting until "load"

Stack Trace: 
Connection.InnerSendMessageToServerAsync[T](String guid, String method, Dictionary`2 dictionary, Boolean keepNulls) line 192
Connection.WrapApiCallAsync[T](Func`1 action, Boolean isInternal)
Frame.GotoAsync(String url, FrameGotoOptions options) line 617
ViewPdfWithWebkit() line 96

I've tried various playwright versions from 1.30+ and am using Windows 11.

**Comment by pavelfeldman** [comment]
PDFViewer is not a part of the web platform, it is a plugin that embedders include in the browsers for users' convenience.
