### ISSUE TITLE
[BUG] Playwright doesn't run tests in the pipeline and doesnt show log messages. and Gitlab timed out after an hour.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24476]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

Tests work fine in local. but in gitlab it is not. 

playwright.config.js

 /* Maximum time one test can run for. */
timeout: 600 * 1000,  --> what this timeout for? is it going to not stop execution for defined timeout, although there are errors in the test?
  
expect: {
    timeout: 120000
  },

I have timeout defined this way in playwright config way and running the tests in the pipeline inside docker.

it says it is Running 4 tests, however it doesn't not log console messages that i add in the test (i usually see console messages when i run the test in the command line in local),  and it shows progress bar forever , Looks like no test started running .

neither erroring out not logging any test console messages..

finally after an hour, gitlab threw an error:
ERROR: Job failed: execution took longer than 1h0m0s seconds

**Comment by pavelfeldman** [comment]
You can learn timeouts that Playwright has here: https://playwright.dev/docs/next/test-timeouts. As to the no output, it is likely that your Docker is misconfigured.
