### ISSUE TITLE
[BUG] WebKit browser crashes on new page/context on Ubuntu

### ISSUE THREAD

**Issue by laurentpayot** [microsoft/playwright#2447]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Ubuntu 20.04 LTS
- Node version: 12.17.0
- Browser: WebKit
- Extra: 
  - I installed the same WebKit dependencies as the [Ubuntu bionic docker file](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) except for `libevent-2.1-6` that was replaced by `libevent-2.1-7` and `libvpx5` that was replaced by `libvpx6` on Ubuntu apt servers.
  - I have [Epiphany](https://wiki.gnome.org/Apps/Web), a WebKit-based browser, working fine on my machine.

**Code Snippet**

```javascript
// debug.js
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch();
    const page = await browser.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example.png` });
    await browser.close();
})();
```

**Describe the bug**
```
 % node ./debug.js
(node:19443) UnhandledPromiseRejectionWarning: Error: Protocol error (Playwright.createContext): Browser has been closed.
    at /home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkConnection.js:102:63
    at new Promise (<anonymous>)
    at WKSession.send (/home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkConnection.js:101:16)
    at WKBrowser.newContext (/home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkBrowser.js:65:65)
    at WKBrowser.<anonymous> (/home/laurent/projects/myproject/node_modules/playwright-core/lib/helper.js:64:31)
    at WKBrowser.newPage (/home/laurent/projects/myproject/node_modules/playwright-core/lib/browser.js:30:36)
    at /home/laurent/projects/myproject/debug/debug.js:5:32
(node:19443) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:19443) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The code snippet is working fine with `chromium` and `firefox` browsers.

**Comment by yury-s** [comment]
Thanks for your report! Can you run it with browser output printed to the terminal like this`DEBUG=pw:browser* node ./debug.js` and post the output here?

**Comment by laurentpayot** [comment]
@yury-s sure:
```
% DEBUG=pw:browser* node ./debug.js
  pw:browser <launching> /home/laurent/.cache/ms-playwright/webkit-1219/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
  pw:browser <launched> pid=75575 +8ms
  pw:browser:err /home/laurent/.cache/ms-playwright/webkit-1219/minibrowser-wpe/MiniBrowser: error while loading shared libraries: libvpx.so.5: cannot open shared object file: No such file or directory +0ms
  pw:browser <process did exit 127, null> +15ms
(node:75564) UnhandledPromiseRejectionWarning: Error: Protocol error (Playwright.createContext): Browser has been closed.
    at /home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkConnection.js:102:63
    at new Promise (<anonymous>)
    at WKSession.send (/home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkConnection.js:101:16)
    at WKBrowser.newContext (/home/laurent/projects/myproject/node_modules/playwright-core/lib/webkit/wkBrowser.js:65:65)
    at WKBrowser.<anonymous> (/home/laurent/projects/myproject/node_modules/playwright-core/lib/helper.js:64:31)
    at WKBrowser.newPage (/home/laurent/projects/myproject/node_modules/playwright-core/lib/browser.js:30:36)
    at /home/laurent/projects/myproject/debug/debug.js:5:32
(node:75564) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:75564) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by laurentpayot** [comment]
Seems that `libvpx5` is missing :facepalm:  Will try to find a way to install it manually. 
Is it possible to upgrade playwright's webkit so it uses `libvpx6`?

**Comment by laurentpayot** [comment]
It's working now after a manual install of `libvpx5` downloaded from https://packages.debian.org/buster/libvpx5
Thanks a lot!

PS: Is it possible to upgrade playwright reference Ubuntu docker target to 20.04 LTS and its nice libvpx6 package?

**Comment by yury-s** [comment]
If we switch to libvpx6 it will break Ubuntu 18.04 as that one comes with libvpx5 only. We'll probably bundle required version of libvpx with our browser archive or link it statically into the webkit binary. Let's keep this issue open for now as we want playwright to work out of the box on Ubuntu 20.04 without you having to manually install packages from previous Ubuntun releases.

**Comment by jonas-meng** [comment]
> If we switch to libvpx6 it will break Ubuntu 18.04 as that one comes with libvpx5 only. We'll probably bundle required version of libvpx with our browser archive or link it statically into the webkit binary. Let's keep this issue open for now as we want playwright to work out of the box on Ubuntu 20.04 without you having to manually install packages from previous Ubuntun releases.

Hi,
Sorry to bother you.
But I encountered an odd issue that I am passing all the following options to webkit :
--inspector-pipe --headless --no-startup-window --no-sandbox --disable-setuid-sandbox --disable-infobars --window-position=0,0 --ignore-certifcate-errors --ignore-certifcate-errors-spki-list --user-agent=Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1

It works fine on my PC but it complains about cannot parse thses arguments on server.
Any idea why?
Is it a problem of dependency?
BTW, I am using Ubuntu 18.04 and I've installed all dependency on the dockerfile.

**Comment by laurentpayot** [comment]
@jonas-meng I'm not sure your issue is related to this thread but did you try to put your user agent string (which contains spaces) between double quotes like so: `--user-agent="Mozilla/5.0 (iPhone; CPU iPhone OS 11_0 like Mac OS X) AppleWebKit/604.1.38 (KHTML, like Gecko) Version/11.0 Mobile/15A372 Safari/604.1"`?
