### ISSUE TITLE
[BUG] Global Setup with starting the server

### ISSUE THREAD

**Issue by nikolainechaev** [microsoft/playwright#24470]
### System info
- "@playwright/test": "^1.34.3"
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info: 

I have several spec.js files with tests and I need to automatically run the server before running my tests. I used to have beforeAll hooks, where I spin up the server in each spec.js files (it worked fine) and now I need to avoid the usage of beforeAll hooks. I was trying to implement global setup instead. In my case I only need to spin up the server and no auth needed. Below you can find the structure and an error I receive when I run tests with global setup.

### Source code

Structure:
```
test-suites
        |
        |____playwright-tests
        |               |
        |               |____ui-tests
        |               |           |
        |               |           |____tests1.spec.js
        |               |           |____tests2.spec.js
        |               |           |____tests3.spec.js
        |               |____api-tests
        |                           |
        |                           |____tests1.spec.js
        |                           |____tests2.spec.js
        |                           |____tests3.spec.js
        |____global.setup.js
        |
        |____playwright.config.js
```

// playwright.config.js
```
module.exports = defineConfig({
  globalSetup: require.resolve('./global.setup'),
  projects: [
    {
      name: 'setup',
      testMatch: /global.setup\.js/,
    },
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
      dependencies: ['setup']
    },
})
```

//global.setup.js
```
import { test as setup } from '@playwright/test'
import { spawn } from 'child_process'

setup('start server', async ({}) => {
  const serverDirectory = 'C:/User/123/projects/123/test/test-server'
  process.chdir(serverDirectory)
  spawn('npm run start', {shell: true})
})
```
**Expected**
I expect my server to run, but seems like playwright doesn't see my global.setup.js file.

**Actual**
My tests fail with an error:
```
    Error: page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:8080/app 
    =========================== logs ===========================
    navigating to "http://localhost:8080/app", waiting until "load"
    ==========================================================
```
I would really appreciate any help!

**Comment by pavelfeldman** [comment]
You should remove `globalSetup: require.resolve('./global.setup'),` since you have a setup project. Also, you should probably use built-in support for your use case: https://playwright.dev/docs/next/test-webserver#configuring-a-web-server

**Comment by nikolainechaev** [comment]
Thank you @pavelfeldman for quick response! 

1) Nothing has been changed when I removed `globalSetup: require.resolve('./global.setup')` from config file. Please let me know if I can provide you more information.

2) I also have tried built-in support. In my scenario there is a need to spin up server from specific location in project. I have used `process.chdir('C:/User/123/projects/123/test/test-server')` to cd into the server folder and after that I used `spawn('npm run start', {shell: true})` to spin it up. Is there any chance we can do something like this:
```
  webServer: {
    command: 'npm run start',
    url: 'http://localhost:8080/',
    **serverLocation: ('C:/User/123/projects/123/test/test-server')**
  },
```
I couldn't find this property in documentation.

3) `webserver` option launch a local server, but in our case we are testing our in-house server. Can you suggest the best way of doing that?

4) When I was going over forum looking for solutions, I noticed that most of the people are using typescript and documentation for` global setup and teardown` also written on ts. Might be a silly question, but can we still use js?

**Comment by pavelfeldman** [comment]
> I also have tried built-in support. In my scenario there is a need to spin up server from specific location in project. 

You can pass `cwd` to specify the current working directory. When you are doing spawn manually you are creating dangling and zombie processes, don't do that.

> webserver option launch a local server, but in our case we are testing our in-house server

It does not matter which one it is, webserver starts what you have in a process that it manages

> but can we still use js?

Sure thing, but you can't do spawn('npm run start', {shell: true}), process management for an interactive tool is much more complex than that.

**Comment by nikolainechaev** [comment]
@pavelfeldman thank you for clarification! 

1. I passed `cwd` property to my `webServer` conf. Double checked it is correct directory and correct command.
2. Ensured that the port '8080' is not being used by another process.
3. Manually started the server, works as expected, manually turned it off.
4. Added some wait time to my tests to let server some time to spin up.

Still getting same issue. Do you have any recommendations or maybe I can provide more info on smth else?

**Comment by nikolainechaev** [comment]
@pavelfeldman we solved this issue, let me know your opinion on that solution please:

1) In package.json we made several scripts that cd into the folders and run specific commands:
```
  "scripts": {
    "test-server": "cd %TEST_SERVER_LOCATION% && npm run start",
    "playwright": "cd %TEST_PLAYWRIGHT_LOCATION% && npx playwright test --headed --workers=1",
  }
```
2) Server started successfully, but playwright script faced a wall as test-server script was running at this moment. We had to find something that will let those scripts run separately. `concurrently.js` was a good solution, because it let you create parent script that will run child scripts. In addition to that, you can kill those processes with flag  --kill-others.
```
  "scripts": {
    "test-server": "cd %TEST_SERVER_LOCATION% && npm run start",
    "playwright": "cd %TEST_PLAYWRIGHT_LOCATION% && npx playwright test --headed --workers=1",
    "all-scripts": "concurrently --kill-others \"npm run test-server\" \"npm run playwright\" "
  }
```
3) As a result we now have stopped server at the end of each run. 

![1](https://github.com/microsoft/playwright/assets/40309434/5061a851-8552-4571-97ef-d211e612377f)
