### ISSUE TITLE
[BUG] innerText function - getting page.innerText is not a function

### ISSUE THREAD

**Issue by hananmalka** [microsoft/playwright#2448]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Mac
- Node version: 12.16.1
- Browser: All

**Code Snippet**

```javascript
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto("https://www.google.com");
    await page.waitForSelector("a[data-pid='23']");    //Gmail link
    const elementText = await page.innerText("a[data-pid='23']");
    console.log(elementText);
```

**Describe the bug**

**Getting: TypeError: page.innerText is not a function**

I can't understand what am I doing wrong. 
According to API documentation - https://github.com/microsoft/playwright/blob/master/docs/api.md#pageinnertextselector-options,

I can provide a selector as a parameter to the innerText method and getting the text value, but I'm just getting: **TypeError: page.innerText is not a function**

Same with innerHTML. 

Can someone help me to resolve it? 
Thanks

**Comment by mxschmitt** [comment]
`Page.innerText` etc. will be included in the next release. A list of the current API you can find here: https://playwright.dev/#version=v1.0.2

**Comment by hananmalka** [comment]
Thanks @mxschmitt 
Closing the issue.
Just wondering why it is published in the API if not supported yet. https://github.com/microsoft/playwright/blob/master/docs/api.md#pageinnertextselector-options

**Comment by yury-s** [comment]
The link points to the most recent API (tip-of-tree source code) which is only available in `playwright@next` or if you build from source. For 1.0.2 documentation you can look at [playwright.dev](https://playwright.dev/#version=v1.0.2)
