### ISSUE TITLE
[BUG] The locator is not finding in the Selenium Grid docker setup(AWS cloud machine)

### ISSUE THREAD

**Issue by ashwithpoojary98** [microsoft/playwright#24489]
### System info
- Playwright Version: [v1.1.36.0]
- Operating System: [Linux amd64]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
   playwright Java and TestNg framework

Hi team,
Playwright failed to find the locator in the Selenium grid docker setup. It works fine till navigation after it throws 

com.microsoft.playwright.TimeoutError: 
Error {
  message='Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//input[@id='UserName']")
============================================================
  name='TimeoutError
  stack='TimeoutError: Timeout 60000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//input[@id='UserName']")
============================================================
    at ProgressController.run (/tmp/playwright-java-11238511618491153829/package/lib/server/progress.js:88:26)
    at Frame.fill (/tmp/playwright-java-11238511618491153829/package/lib/server/frames.js:1047:23)
    at FrameDispatcher.fill (/tmp/playwright-java-11238511618491153829/package/lib/server/dispatchers/frameDispatcher.js:163:30)
    at DispatcherConnection.dispatch (/tmp/playwright-java-11238511618491153829/package/lib/server/dispatchers/dispatcher.js:312:46)
}

It works fine in local and local selenium grid setups.
Page load and waits are used.

**Comment by pavelfeldman** [comment]
Sounds like your grid is either slow or not working - you ended up waiting for a minute and then the test timed out.

**Comment by ashwithpoojary98** [comment]
Selenium Grid is up and running. Till navigation, it works fine and we can retrieve the title and content of the page. But the locator not finding!!
