### ISSUE TITLE
Microsoft Edge is failing to launch with `launchPersistentContext`

### ISSUE THREAD

**Issue by linichacko** [microsoft/playwright#24488]
Details of the error:

> (node:992) UnhandledPromiseRejectionWarning: Error: Page closed
>     at CRSession.<anonymous> (C:\Users\Administrator\ABC\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crPage.js:445:54)
>   at Object.onceWrapper (events.js:482:28)
>     at CRSession.emit (events.js:388:22)
>     at C:\Users\Administrator\ABC\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crConnection.js:253:39
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> (node:992) UnhandledPromiseRejectionWarning: browserType.launchPersistentContext: Browser closed.
> ==================== Browser output: ====================
> <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-dev-shm-usage --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\Administrator/AppData/Local/Google/Chrome/User Data/test-edge --remote-debugging-pipe about:blank
> <launched> pid=2028
> [pid=2028][err] [2028:3536:0725/144509.811:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
> [pid=2028][err] [2028:3536:0725/144509.822:ERROR:assistance_home_client.cc(32)] File path C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\test-edge\Default
> [pid=2028][err] [2028:3536:0725/144509.936:ERROR:edge_auth_errors.cc(487)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:
> [pid=2028][err]
> =========================== logs ===========================
> <launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-dev-shm-usage --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\Administrator/AppData/Local/Google/Chrome/User Data/test-edge --remote-debugging-pipe about:blank
> <launched> pid=2028
> [pid=2028][err] [2028:3536:0725/144509.811:ERROR:chrome_browser_cloud_management_controller.cc(162)] Cloud management controller initialization aborted as CBCM is not enabled.
> [pid=2028][err] [2028:3536:0725/144509.822:ERROR:assistance_home_client.cc(32)] File path C:\Users\Administrator\AppData\Local\Google\Chrome\User Data\test-edge\Default
> [pid=2028][err] [2028:3536:0725/144509.936:ERROR:edge_auth_errors.cc(487)] EDGE_IDENTITY: Get Default OS Account failed: Error: Primary Error: kImplicitSignInFailure, Secondary Error: kAccountProviderFetchError, Platform error: 0, Error string:
> [pid=2028][err]
> ============================================================
>     at Proxy.launchPersistentContext (C:\Users\Administrator\ABC\node_modules\playwright-extra\dist\index.cjs.js:703:71)
>     at async C:\Users\Administrator\ABC\manual-setup\test-edge.js:12:19
> (node:992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)

**Comment by pavelfeldman** [comment]
Please follow the issue template to file something we could reproduce.
