### ISSUE TITLE
[BUG] Code example for using sessionStorage in auth does not make a lot of sense

### ISSUE THREAD

**Issue by dagda1** [microsoft/playwright#24485]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

The playwright docs have [this](https://playwright.dev/docs/auth#session-storage) section about using `sessionStorage` to store authentication details so you don't have to log in before every test.

It provides the following snippet as an example:

```ts
// Get session storage and store as env variable
const sessionStorage = await page.evaluate(() => JSON.stringify(sessionStorage));
fs.writeFileSync('playwright/.auth/session.json', JSON.stringify(sessionStorage), 'utf-8');

// Set session storage in a new context
const sessionStorage = JSON.parse(fs.readFileSync('playwright/.auth/session.json', 'utf-8'));
await context.addInitScript(storage => {
  if (window.location.hostname === 'example.com') {
    for (const [key, value] of Object.entries(storage))
      window.sessionStorage.setItem(key, value);
  }
}, sessionStorage);
```

This line especially makes no sense

```ts
const sessionStorage = await page.evaluate(() => JSON.stringify(sessionStorage));
```

It is assigning a var called sessionStorage and stringifying the same name.

It is also very unclear how this should be used and I think these are 2 snippets for 2 separate locations and if I try and access sessionStorage in a test, `sessionStorage` will be undefined so I'm not sure where this code should live and the docs do not give any indication where this should be.

**Comment by dagda1** [comment]
I figured it out but it is confusing to say the least

**Comment by victorzw895** [comment]
Nooooo, please don't close!
I don't get it, can you help explain please?

**Comment by klippx** [comment]
Same here, struggling a lot with sessionStorage. Neither test examples or docs seem to work or give much help.
