### ISSUE TITLE
[Feature] Auto wait required in second or third iframes generated dynamically within page

### ISSUE THREAD

**Issue by Goldyfinger** [microsoft/playwright#24492]
Hi, I have a web application that initially has one iframe and later after some actions in first iframe, second iframe is dynamically created and added to the same page as a second tab under the same url. I have no issues interacting with elements in first iframe, but problem starts when second iframe is created and I have to carry on some actions in it i.e. in the second iframe Playwright doesn't wait for elements to load, instead it tries to click and immediately fails if element not found. So I had to explicit wait to check for visibility of element with isVisible() method to overcome the problem. All actions in the first iframe worked fine with auto-wait by the framework itself and didn't need explicit isVisible() check.

I didnt have to use below do-While for interacting with first iframe

    boolean elementVisible = false;
        do {
            System.out.println("\n"+"elementVisible: "+elementVisible+"\n");
            elementVisible = page.frameLocator("#iframeId").getByText("Myname").nth(1).isVisible();
        } while (elementVisible);
    
    page.frameLocator("#iframeId").getByText("Myname").nth(1).click();

- Playwright Version: [v1.28]
- Operating System: [Windows 11]
- Browser: [Chromium]
This seems somewhat related to https://github.com/microsoft/playwright/issues/21176

**Comment by pavelfeldman** [comment]
It is likely to have nothing to do with iframe, probably to the page content itself. Could you share repro steps?

**Comment by Goldyfinger** [comment]
I logon to web app via Chromium with Playwright
I create an INV (1st iframe) case and fill in details and proceed till I see a navigation link
I click navigation link and it opens a new tab under same page with TAX (second iframe) case.
I try to fill some info in the TAX case and it fails with reason : 'waiting for frameLocator("#PegaGadget1Ifr").getByText("whatever on iframe 2")'

**Comment by Goldyfinger** [comment]
Hi, I have one update:
This issue is resolved after inserting the dreaded `Thread.sleep(3000)` at every load period on the web page. I hoped this wouldn't be needed anymore in Playwright as compared to older frameworks but apparently not. Hence for now we can say issue is resolved, thanks for looking into it.

**Comment by BatthewZ** [comment]
I ended up creating a poll loop to wait for new frames to be mounted onto the page, I posted the code for it over here:

https://github.com/microsoft/playwright/issues/21176#issuecomment-1983222212

I hope that's helpful for anyone looking to do similar
