### ISSUE TITLE
[BUG]:  trace viewer gives different results each time we run example test

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#24490]
**Context:**
- Playwright Version: 1.36.2
- Operating System: Mac
- Node.js version: 20.2
- Visual Studio Code version: 1.80.1
- Playwright for VSCode extension version: 1.0.15
- Browser: chrome
- Extra: [any specific details about your environment]

1. Run the example test with show trace viewer checked

```js
test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

<img width="727" alt="Screenshot 2023-07-28 at 15 49 32" src="https://github.com/microsoft/playwright/assets/13063165/feab6e4b-dabe-410d-bba2-dff5f2690531">

2. Run the test a second time

<img width="677" alt="Screenshot 2023-07-28 at 15 46 46" src="https://github.com/microsoft/playwright/assets/13063165/bb41ceb9-02a7-40b2-b12d-c51475912e15">

**Describe the bug**

Page does not show the intro page in the trace yet shows the intro URL when running the test a second time. Closing VS Code and reopening it and then running the test again will work but it means we have to close VS Code every time we want to see the correct results, installation page for expect to have URL and screenshots which differ when running test various times

**Comment by pavelfeldman** [comment]
I think things work fine, but the target is off:

[trace.zip](https://github.com/microsoft/playwright/files/12196607/trace.zip)

**Comment by pavelfeldman** [comment]
Folding the target-is-off into https://github.com/microsoft/playwright/issues/24532
