### ISSUE TITLE
[BUG] sanitizeForFilePath removes underscores from file name

### ISSUE THREAD

**Issue by johnharringt0n** [microsoft/playwright#24497]
### System info
- Playwright Version: @playwright/test: 1.35.1
- Operating System: Ubuntu 22.04.2 LTS (Jammy Jellyfish)
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  snapshotPathTemplate: '{testDir}/__snapshots__/{arg}{ext}',
});
```

**Test file (self-contained)**

```js
it('should respect underscores in screenshot file name', async ({ page }) => {
  await expect(page.getByTestId('foo')).toHaveScreenshot('foo_example.png');
});
```

**Steps**
- Run the test

**Expected**

It should output the screenshot file at `testDir/__snapshots__/foo_example.png`

**Actual**

It outputs screenshot file at `testDir/__snapshots__/foo-example.png`

---

This is because of [sanitizeForFilePath](https://github.com/microsoft/playwright/blob/947637d19f31d79fa2ee8dd9ad9d643d044db4c3/packages/playwright-test/src/util.ts#L198-L200) from https://github.com/microsoft/playwright/pull/23414.

Our application is migrating to Playwright and has many existing snapshot/screenshot files with underscores. We now aren't able to match against those existing images because Playwright overwrites the provided safe filename.

**Comment by pavelfeldman** [comment]
The change you point to was introduced in 1.36 and then reverted. Our paths are sanitized using `s.replace(/[\x00-\x2C\x2E-\x2F\x3A-\x40\x5B-\x60\x7B-\x7F]+/g, '-')` and unfortunately changing now would break existing users.

**Comment by aslushnikov** [comment]
Closing this as per above.
