### ISSUE TITLE
[Feature] Add Mouse functionality on selectors

### ISSUE THREAD

**Issue by ciradu2204** [microsoft/playwright#24493]
**Let us know what functionality you'd like to see in Playwright and what your use case is.**

I am currently developing a test to resize a specific column in a table. But the mouse functionality only works on the page. So it would be good to have a mouse functionality on selectors as well. 

https://github.com/microsoft/playwright/assets/37863089/4f7ac709-3cd0-41e2-9584-2bf2cc59c0c8

**Do you think others might benefit from this as well?**
Yes it will benefit others especially when using tables.

**Comment by pavelfeldman** [comment]
It is unclear what you are saying, you can automate this resize with Playwright.

**Comment by ciradu2204** [comment]
Hi Pavel,

I wanted to use the mouse feature. But it only works on a page not on a
specific selector. For example page.mouse.move(x, y) instead
selector.mouse.move(x, y)

Please let me know if there is any other feature that could help achieve
the resizing.

Thanks

**Comment by pavelfeldman** [comment]
You can use `locator.boundingBox` do figure out where to click and then use `page.mouse`.

**Comment by pavelfeldman** [comment]
Closing as the requested feature exists, you can ask community for help with using it on Discord.
