### ISSUE TITLE
[BUG] Navigation actions not recorded after some actions

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#24499]
### System info
- Playwright Version: v1.36.1
- Operating System: Windows 11
- Browser: Chromium
- Other info:

Some navigation actions are not recorded. For instance, if I start filling an input field and then enter a new URL in the navigation bar, it won't record the navigation action. I provide a video and a test (it needs to run with `inspectorTest` fixtures).

https://github.com/microsoft/playwright/assets/1374559/bd0eb261-4dda-4f04-a821-8c31dd477c62

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/ruifigueira/playwright-crx/pull/new/bug/navigation-not-recorded

**Steps**
- Run:

```
npm run ctest -- tests/library/inspector/recorder.spec.ts
```

**Expected**

```
Array [
  "  const page = await context.newPage();",
  "  await page.goto('http://localhost:8907/input/textarea.html');",
  "  await page.locator('textarea').fill('hello world');",
  "  await page.goto('http://localhost:8907/input/button.html');",
  "  await page.getByRole('button', { name: 'Click target' }).click();",
]
```

**Actual**

Navigation to `http://localhost:8907/input/button.html` is lost:

```
Array [
  "  const page = await context.newPage();",
  "  await page.goto('http://localhost:8907/input/textarea.html');",
  "  await page.locator('textarea').fill('hello world');",
  "  await page.getByRole('button', { name: 'Click target' }).click();",
]
```

**Comment by pavelfeldman** [comment]
See the comment in the PR for the reason behind closing.
