### ISSUE TITLE
[Issue] Feature flags with playwright tests

### ISSUE THREAD

**Issue by sridasari531** [microsoft/playwright#24495]
Hi Team  - Does playwright support Launch Darkly feature flags? 

Basically, based on the feature flags, need playwright to look for different  page elements.

Thank you

**Comment by pavelfeldman** [comment]
I am not sure what you mean, could you elaborate?

**Comment by sridasari531** [comment]
We are using Launch Darkly for feature flags in nextJS app. these flags are set at build time.

Is there are way to support feature flags in playwright tests. 
based on the feature flags (on/off), need playwright to execute the flow.

**Comment by pavelfeldman** [comment]
I still need more information. Could you explain what you'd like to see in Playwright terms? I am not familiar with Launch Darkly.

**Comment by sridasari531** [comment]
For example, lets say user registration form with 3 steps

1. user first name, user last name
2. email/phone number
3. address


using a Feature flag, lets we want to collect either email or phone number from the user from step 2.


When we do playwright tests, how does playwright know what to look for on the page( email or phone number)?

Hope i explained well.

**Comment by pavelfeldman** [comment]
Sorry, it did not help. Need exact steps along with the expected results.

**Comment by OS-stanislavivanov** [comment]
If you're using Feature Flags -> you can defy then in metadata section and based on this metadata, for each project, in dependency project do what ever you want, according to your feature flag.
@sridasari531

**Comment by dgozman** [comment]
Perhaps [this guide](https://playwright.dev/docs/test-parameterize#parameterized-projects) would also be helpful?

Looks like there is no action item for Playwright, so closing the issue.
