### ISSUE TITLE
[Feature] [codegen] Automatically generate testid

### ISSUE THREAD

**Issue by yibuyisheng** [microsoft/playwright#24508]
In codegen scene, we tend to use the testid to locate elements, so we want Playwright to generate the testid suggestion too. Think about the generated codes:
```js
test('should generate the comments.', ({ page }) => {
  await page.goto('http://www.xxx.com');
  // Add the testid[54d178a5-2151-43aa-8a2f-5b129e2c22b5] to the source code: /path/to/file.tsx[20,25].
  await page.getByRole('button', { name: 'xxx' }).click();
});
```  

Or is there a better way to generate testids？

**Comment by yury-s** [comment]
What would be added value of the codegen compared to just adding `data-testid="your-own-id"` to the code of the element that you like to locate?

**Comment by dgozman** [comment]
@yibuyisheng Unfortunately, Playwright does not know about your source code and cannot recommend any modifications. Closing as not feasible.
