### ISSUE TITLE
[BUG] PlayAudit() function closes the browser after first Lighthouse scan

### ISSUE THREAD

**Issue by geeky4u** [microsoft/playwright#24505]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

We are trying to perform Lighthouse analysis on a web application by using Playwright-lighthouse library as a utility by calling it in multiple stages within a single test.

Sample:

Before all { browser initiation }

test {

goto(url); 
await playaudit{} 
locator().click(); 
await playaudit{}

};

Problem is once the URL is opened and playaudit() function is called, the browser is automatically closing leading to which the locator().click() is throwing Error: locator.click: Target page, context or browser has been closed error.

I'm currently using downgraded version of lightHouse & playwright-lighthouse due to existing import issue in latest versions. **"@playwright/test": "^1.35.1", "lighthouse": "^9.6.8", "playwright-lighthouse": "^2.2.2"**,

Can PlayAudit() be called multiple times within a single test? If not possible by design, are there any workarounds possible ?

Thanks!

Expectation: PlayAudit() function can be called multiple times within a single Playwright test without browser/page getting closed.

**Comment by yury-s** [comment]
Please file this report in `Playwright-lighthouse` repository (or whichever module provides `playaudit`) instead. `playaudit` is not a part of playwright.
