### ISSUE TITLE
[BUG] Page.setContent() removes comments at the beginning of inserted HTML code

### ISSUE THREAD

**Issue by fczbkk** [microsoft/playwright#24503]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [macOS 13.4.1]
- Browser: [Chromium]

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] }
    }
  ]
})
```

**Test file (self-contained)**

```typescript
import { expect, test } from '@playwright/test'

test('Page.setContent() should not remove a comments from the beginning of inserted HTML', async ({ page }) => {
  // this works fine
  await page.setContent('<div></div><!-- my comment -->')
  await expect(await page.content()).toContain('my comment')

  // this removes the comment
  await page.setContent('<!-- my comment --><div></div>')
  await expect(await page.content()).toContain('my comment')
})

```

**Steps**
- [Run the test]

**Expected**

All HTML code should be inserted into the page, including all the comments.

**Actual**

When inserted HTML code begins with a comment, this comment is removed. All other comments (inside HTML elements or at the end of inserted code) are preserved.

**Comment by yury-s** [comment]
This a peculiarity of how `document.write()` (that Playwright uses under the hood) works. The comment gets inserted before automatically added <html> node:

<img width="159" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/2e1fcfe8-9b1f-4da3-9e6f-881599fb587f">

As a workaround you can explicitly wrap the html snippet into `<body>...</body>`:

```ts
  await page.setContent('<body><!-- my comment --><div></div></body>');
  await expect(await page.content()).toContain('my comment');
```

Would that work for you?

**Comment by fczbkk** [comment]
Thanks for the explanation @yury-s. It makes sense now. I think that the workaround is straightforward once I understand what precisely the `setContent()` method does. Maybe this could be addressed in the documentation. But I'm not sure if it is worth it for such an edge-case scenario like this.
