### ISSUE TITLE
Microsoft Edge is failing to launch with launchPersistentContext

### ISSUE THREAD

**Issue by linichacko** [microsoft/playwright#24517]
### System info
- Playwright Version: [v1.36]
- Operating System: [ Windows 2019 Server]
- Browser: [Chromium - Edge]
- Other info: This issue happens recently, but only for edge not for chrome. We use playwright library.

### Source code
```ts
(async () => {
  const userDataDir = `${os.homedir()}${config.get('userDataDirectoryPath.windowsEdge')}`;
  const context = await chromium.launchPersistentContext(userDataDir, {
    channel: 'msedge',
    headless: false,
  });
  const page = context.pages()[0];
  await page.goto(config.get('loginUrl'));
})();
```

**Steps**
- [Run the above test]

**Expected**

[The edge browser should launch with the specified url and we should be able to enter the login details]

**Actual**
```
[The edge browser just launched and then crashing by throwing error:
(node:992) UnhandledPromiseRejectionWarning: Error: Page closed
    at CRSession.<anonymous> (C:\Users\Administrator\EMV-Test\webmail\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crPage.js:445:54)
    at Object.onceWrapper (events.js:482:28)
    at CRSession.emit (events.js:388:22)
    at C:\Users\Administrator\Repo\node_modules\playwright\node_modules\playwright-core\lib\server\chromium\crConnection.js:253:39
(Use `node --trace-warnings ...` to show where the warning was created)
(node:992) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:992) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:992) UnhandledPromiseRejectionWarning: browserType.launchPersistentContext: Browser closed.
==================== Browser output: ====================
<launching> C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-dev-shm-usage --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,AcceptCHFrame,AutoExpandDetailsElement --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --no-sandbox --disable-blink-features=AutomationControlled --user-data-dir=C:\Users\Administrator/AppData/Local/Google/Chrome/User Data/test-edge --remote-debugging-pipe about:blank]
```

**Comment by yury-s** [comment]
Are you sharing the same user data directory between Chrome and Edge? Does it fail if you point `userDataDir` to an empty directory?

**Comment by linichacko** [comment]
Yes it fails with same error, if we use an empty directory. This issue happens only to edge.

**Comment by dgozman** [comment]
@linichacko There's not much we can do here. Something does not work when you launch Edge. I find the user data dir somewhat suspicious - it points to Google Chrome and mixes different path separators.

```
--user-data-dir=C:\Users\Administrator/AppData/Local/Google/Chrome/User Data/test-edge
```

I'd recommend running the last line from the logs manually, dropping the `--remote-debugging-pipe` flag, and see whether the browser works. If that does not help to resolve the issue, I'll have to close it as non-actionable.

**Comment by linichacko** [comment]
The browser launches when the `--remote-debugging-pipe` flag is dropped whereas the edge browser is not launching when that flag is given. Is there any option in playwright to hide this flag when the browser opens. Please note that we are able to manually click on the edge icon and launch it. Also the playwright code works well with msedge-beta and msedge-dev.

**Comment by dgozman** [comment]
@linichacko Maybe try running with `DEBUG=pw:browser` environment variable and we'll get some more logs/stacks from the browser itself? I am running out of troubleshooting ideas 😄 

> Also the playwright code works well with msedge-beta and msedge-dev.

This is a good sign. Perhaps msedge stable had a bug that was fixed in the newer version?
