### ISSUE TITLE
Running node execSync not working in Playwright 

### ISSUE THREAD

**Issue by alexbjorlig** [microsoft/playwright#24516]
### System info
- Playwright Version: 1.36.2
- Operating System: macOS 13.5
- Browser: [All]
- Other info:

### Source code

Here is the [repo](https://github.com/21RISK/playwright-issue)

[https://github.com/your_profile/playwright_issue_title]

**Steps**
- Download repo and run tests with `npx playwright test`

**Expected**

I would expect "bente" in the console

**Actual**

The fixture halts at line 15, `console.log(execSync('node ./test-js-file.js').toString());` - and never continues...

**comments**

Please notice that the project has configured `type: "module"` in the root package.json. With this removed, it actually does work - so I think it has something to do with cjs/mjs, but I'm a bit unsure.

Running `node ./test-js-file.js` from the cmd line works without issues.

**Comment by mxschmitt** [comment]
Your repository link is not public: https://github.com/21RISK/playwright-issue

**Comment by mxschmitt** [comment]
Thanks! The issue is that it hangs here: https://github.com/microsoft/playwright/blob/96b2247e28bee4f96241ec8f4e92e79b00ce3328/packages/playwright-test/src/transform/esmLoader.ts#L60

You can workaround it like that while we implement a solution:

```
console.log(execSync('node ./test-js-file.js', {  env: { ...process.env, NODE_OPTIONS: undefined}}).toString());
```

**Comment by alexbjorlig** [comment]
> Thanks! The issue is that it hangs here:
> 
> https://github.com/microsoft/playwright/blob/96b2247e28bee4f96241ec8f4e92e79b00ce3328/packages/playwright-test/src/transform/esmLoader.ts#L60
> 
> You can workaround it like that while we implement a solution:
> 
> ```
> console.log(execSync('node ./test-js-file.js', {  env: { ...process.env, NODE_OPTIONS: undefined}}).toString());
> ```

Thanks 🙏

To be 100% transparent, I did actually use most of my day debugging this 🤓 Took me a loooong time before I started to suspect it could be something with Playwright 😅 But thanks!
