### ISSUE TITLE
Ability to install exact node version in the docker image

### ISSUE THREAD

**Issue by jbojcic1** [microsoft/playwright#24519]
At the moment if you use this [dockerfile](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.focal) it will install the latest release of docker 18, but some projects have docker pinned to the exact version so would be nice if we could specify the exact version of the node

**Comment by yury-s** [comment]
You can copy the file and edit it to point to a specific Node version. Would that work for you or what do you suggest instead?

We publish the image with the Node version that is the current one at the time the image is built.

**Comment by dgozman** [comment]
Closing as per above.
