### ISSUE TITLE
[BUG] Windows + Webkit test fails with 'SSL peer certificate or SSH remote key was not OK'

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright#24512]
Playwright example tests failed for webkit project when ran on azure windows VM with SSL error
Few points 
- Test do pass on my local windows laptop
- Also i can set ignoreHTTPSErrors to true to ignore the issue
- I tried with some more test endpoint and it sems like it fail for some endpoints 
 

### System info
- Playwright Version: [v1.36]
- Operating System: [Windows Server 2022]
- Browser: [WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'], },
    },
});
```

**Test file (self-contained)**

```js

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects the URL to contain intro.
  await expect(page).toHaveURL(/.*intro/);
});
```

**Steps**
- Create azure VM with windows 2022 server
- install node and npm
- npm init playwright 
- npx playwirght test

**Expected**
Test should pass

**Actual**
Webkit Tests failed with SSL error
Error: page.goto: SSL peer certificate or SSH remote key was not OK
 navigating to "https://playwright.dev/", waiting until "load"

**Comment by mxschmitt** [comment]
Looks like a workaround running this file, thats why we didn't experience it on GitHub Actions: https://github.com/actions/runner-images/blob/4ec9fdae13222a0b2b278ae1ddcdc9e8b44901ed/images/win/scripts/Installers/Install-RootCA.ps1 

@puagarwa could you try doing that?

**Comment by puagarwa** [comment]
Sure, i will give a try.

**Comment by puagarwa** [comment]
@mxschmitt workaround works for us but I assume you will still followup upstream for root cause.

**Comment by mxschmitt** [comment]
Amazing, we discussed it in the team meeting and will wait for more users who run into it before we proceed with making changes to the current implementation.

**Comment by mxschmitt** [comment]
Closing for now as working as intended, for other customers who run into it, please re-file. Thanks!

**Workaround if you are facing this issue:**

1. **Open PowerShell as an Administrator**: Right-click on the Start button, search for PowerShell, right-click on it, and select "Run as administrator."

1. **Allow Script Execution**: By default, PowerShell restricts the execution of scripts. You can allow the execution of scripts by running the following command:
   
   ```powershell
   Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
   ```

   Answer 'Y' or 'A' when prompted. 

2. **Download the Script**: You can use the `Invoke-WebRequest` cmdlet to download the script:

   ```powershell
   Invoke-WebRequest -Uri "https://raw.githubusercontent.com/actions/runner-images/4ec9fdae13222a0b2b278ae1ddcdc9e8b44901ed/images/win/scripts/Installers/Install-RootCA.ps1" -OutFile "Install-RootCA.ps1"
   ```

3. **Run the Script**: If everything looks good, you can execute the script by running:

   ```powershell
   .\Install-RootCA.ps1
   ```

**Comment by rstarkov** [comment]
If you're going to run this workaround script on your dev machine, be aware that it disables the root certificate auto-update mechanism in your Windows install. In other words, it's a fairly invasive workaround. To be fair it also _manually_ updates the root certificate store from Windows Update on every run.

I think I'd rather just skip webkit entirely when running tests interactively, and only run those tests in CI.

**Comment by Stan-Stani** [comment]
> If you're going to run this workaround script on your dev machine, be aware that it disables the root certificate auto-update mechanism in your Windows install. In other words, it's a fairly invasive workaround. To be fair it also _manually_ updates the root certificate store from Windows Update on every run.
> 
> I think I'd rather just skip webkit entirely when running tests interactively, and only run those tests in CI.

Any ideas of a less invasive workaround?

**Comment by MarcRosewarne** [comment]
@Stan-Stani Can we have more context of the code sample please?
We are having the SSL/SSH webkit faliures also (Playwright UI & CI)
Where is the code sample used? eg: beforeAll / beforeEach / within the test

**Comment by poojagowda91** [comment]
has anyone been actually able to fix this ? for me webkit works with "http" fails for "https" and chromium,chrome all do not seem to launch at all in docker windows container.

**Comment by mxschmitt** [comment]
@poojagowda91 have you tried that? https://github.com/microsoft/playwright/issues/24512#issuecomment-1684188796

**Comment by poojagowda91** [comment]
Yes i did.I dont seem to be able to access anything which has secure network like "https" whereas "http" works fine.
