### ISSUE TITLE
[BUG].  playwright.chromium.connect(' ws://127.0.0.1:56555/devtools/xxxxx').;   Test timeout of 30000ms exceeded.

### ISSUE THREAD

**Issue by SUNslm** [microsoft/playwright#24514]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [macOS 13.2]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

** start  file**

```js
// run.ts
import playwright  from 'playwright';
const browser = await playwright.Chromium.connect('ws://127.0.0.1:9222/xxxxxx', options );  
//  Test timeout of 30000ms exceeded.

```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]
 
**Actual**
 Test timeout of 30000ms exceeded.
[Describe actual behavior]
 Test timeout of 30000ms exceeded.

**Comment by mxschmitt** [comment]
This is expected, [connect()](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) is Playwright's protocol, while connectOverCDP is what you want: https://playwright.dev/docs/api/class-browsertype#browser-type-connect-over-cdp

**Comment by yury-s** [comment]
Closing per above. If you think it's a bug in playwright please open a new issue and provide  a self-contained repro that we can run locally.
