### ISSUE TITLE
[Feature][Discussion] Expose TestFixtureValue (or equivalent) as typing

### ISSUE THREAD

**Issue by ffluk3** [microsoft/playwright#24526]
Hello! I am a member of a platform team at my company who is looking to effectively build a set of fixtures for the rest of our company to consume. To ensure they are durable, we want to write tests for these fixtures that are equivalently of the form:

```
GIVEN a test fixture
WHEN provided a set of test fixture dependencies, and TestInfo
THEN /* ... */
```

I was more or less able to make this work via the following (somewhat hacky) typing:

```ts
// ../test-types.ts
type TestFixturesT = { /* ... my custom fixtures ... */ }

type ArgumentTypes<F extends Function> = F extends (
    ...args: infer A
  ) => any
  ? A
  : never;

// gives us the type of the functions used to set up the playwright fixtures.
export type TestExtendFixturesT = ArgumentTypes<typeof test.extend<TestFixturesT, WorkerScopedTestFixturesT>>[0]

// fixture-test-runner.ts
import type { TestFixture, TestInfo } from '@playwright/test';
import { stubInterface } from 'ts-sinon';
import type { TestExtendFixturesT, TestFixturesT } from '../test-types';

/**
 * Allows us to generate a mocked test info type for usage within fixture testing
 */
export const createTestInfo = (
  overrides: Partial<TestInfo> = {},
): TestInfo => ({
  ...stubInterface<TestInfo>(),
  ...overrides,
});

/**
 * Mimics
 */
type TestFixtureValue<R, F extends Record<string, any>> =
  | Exclude<R, Function>
  | TestFixture<R, F>;

const isFixtureTuple = <R, F extends Record<string, any>>(
  f: any,
): f is [TestFixture<R, F>, any] =>
  Array.isArray(f) && 'fixtureDependencies' in f[0];

const isCallableFixture = <R, F extends Record<string, any>>(
  f: any,
): f is TestFixture<R, F> => typeof f === 'function';

interface FixtureTestOptions<R, F extends Record<string, any>> {
  /** Supplied fixture to assert against */
  fixture: TestFixtureValue<R, F> | [TestFixtureValue<R, F>, any] | undefined;
  /** any dependencies to test against */
  fixtureDependencies: Partial<TestExtendFixturesT>;
  /** Optionally provided test information. A default mock will be used otherwise */
  testInfo?: TestInfo;
  /** Callback that returns the fixture value for testing */
  runAssertions: (fixtureValue: R) => Promise<void>;
}

/**
 * Execute a fixture test against
 */
export const runTestForFixture = async <R>({
  fixture,
  fixtureDependencies,
  testInfo,
  runAssertions,
}: FixtureTestOptions<R, any>): Promise<void> => {
  const callable = isFixtureTuple(fixture) ? fixture[0] : fixture;

  // If the fixture is not callable, it is a static attribute and should be tested as such
  if (isCallableFixture<R, TestFixturesT>(callable)) {
    return callable(
      fixtureDependencies as TestFixturesT,
      runAssertions,
      testInfo ?? createTestInfo(),
    );
  }

  return runAssertions(callable as R);
};
```

The key difficulty I am running into is though I can specify a set of `Fixtures`, and also try to lock in a `TestFixture`, the actual returned value of the `Fixtures` type must be generated mysefl. In addition, I have to perform some type guards around figuring out if the fixture is a value, a function, or a tuple, which allows us to safely call the generation function.

Is this a use case y'all have run into yet? One possible value add would be to simply expose the `TestFixtureValue`, if that is not too much abstraction leak. Open to the team's thoughts there!

**Comment by yury-s** [comment]
Can you say a bit more about how these type constructs and the function are supposed to be used? It's not clear how others would benefit from exposing it in Playwright API, it seems to be very specific to your use case.

**Comment by ffluk3** [comment]
It is possible that this is more specific, but I thought that exposing it helps a lot Do you think it is a valid use case to test the logic of a fixture in isolation? 

Without exposing the type, we could test individual fixtures by setting up all of the data within the test and calling it directly, like:

```ts
const dependencies = getFixtureDependencies()
const use = async (value) => { /* run assertions on the returned value */ }
const testInfo = createTestInfo()

await fixtures.myFixtures(dependencies, use, testInfo)
```

What I wanted to do is abstract the setup of this test to a function, which is what necessitated a way to express the value of a given fixture within the test. 

For what it's worth, I am proposing we provide the type constructs alone, not the runner. I think the `TestFixtureValue` is a useful type for end-users writing this type of test, and the usage above is more specific to my reason for needing the type.

**Comment by yury-s** [comment]
> It is possible that this is more specific, but I thought that exposing it helps a lot Do you think it is a valid use case to test the logic of a fixture in isolation?

If your goal is to test behavior of individual fixtures and in the environment where such a fixture has all of its dependencies resolved, why not write tests like this:

```ts
test('some feature of fixture1', async ({ fixture1 }) => {
  // Your test here.
  expect(fixture1).toBeTruthy();
});

test('some feature of fixture2', async ({ fixture2 }) => {
  // Your test here.
  expect(fixture2).toBeTruthy();
});

test('some feature of fixture2 that depends on fixture1', async ({ fixture1, fixture2 }) => {
  // Your test here.
});
```

In this case Playwright will instantiate all the fixture dependencies automatically and you get all the necessary types already.

**Comment by ffluk3** [comment]
I can see how that would fit better in some ways with the existing API. Our use case would be to be able to mock a subset of fixtures to be able to assert on how they can be used, all without needing a browser context or playwright dependencies stood up to run the assertions. We were looking for more of a unit test approach of the fixtures directly, but that could be too fine-grained.

**Comment by yury-s** [comment]
> Our use case would be to be able to mock a subset of fixtures to be able to assert on how they can be used,

You can easily achieve that by [overriding](https://playwright.dev/docs/test-fixtures#overriding-fixtures) some of the fixture dependencies.

> all without needing a browser context or playwright dependencies stood up to run the assertions.  We were looking for more of a unit test approach of the fixtures directly, but that could be too fine-grained.

Unless you use browser/context/page fixture in your tests Playwright won't launch any browsers, so it will work exactly as a unit test instantiating only transitive closure of the fixtures that your test depends upon. There should be no extra overhead from unused fixtures.

Considering what have been said and that there are other solutions, exposing extra type machinery just for fixture testing is out of scope for Playwright at this point.
