### ISSUE TITLE
[BUG] Mismatch with snapshots taken in headed mode on HiDPI & non-HiDPI screens for an iframe pdf

### ISSUE THREAD

**Issue by chowed** [microsoft/playwright#24534]
Ideally this test would be screen-agnostic so that regardless of the screen setup, the test would pass.

### System info
- Playwright Version: v1.35.1
- Operating System: macOS 13.4.1(c)
- Browser: Chromium

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
import { expect, test } from "@playwright/test";

// Headed mode
test.use({ headless: false });

it('should render PDF in iframe', async ({ page }) => {
    // Renders the smallest pdf: https://github.com/mathiasbynens/small/blob/master/pdf.pdf
    await page.setContent(`<iframe id="pdf" src="data:application/pdf;base64,JVBERi0xLgoxIDAgb2JqPDwvUGFnZXMgMiAwIFI+PmVuZG9iagoyIDAgb2JqPDwvS2lkc1szIDAgUl0vQ291bnQgMT4+ZW5kb2JqCjMgMCBvYmo8PC9QYXJlbnQgMiAwIFI+PmVuZG9iagp0cmFpbGVyIDw8L1Jvb3QgMSAwIFI+Pg=="/>`);

    // Time to drag browser into another display
    await page.waitForTimeout(5000);

    expect(await page.locator("#pdf").screenshot({ scale: "css" })).toMatchSnapshot("pdf.png");
});
```

**Steps**
- Run the test with the headed browser taking a snapshot of the PDF on a HiDPI screen e.g. MacBook
- Repeat the above with a non-HiDPI screen

**Expected**

I am expecting the test to pass regardless of whether the snapshot was taken on a HiDPI screen or not, given that the device has remained unchanged and that scale is set to "css".

**Actual**
The test is failing, saying `The result for this "15207 pixels (ratio 0.33 of all image pixels) are different."`

**Documentation inconsistency**
Another thing I noticed was the inconsistency in documentation for the screenshot option `scale` under `types.d.ts` and the website, with the former saying it [defaults to `device`](https://github.com/microsoft/playwright/blob/77b1ec4a53425ae638d3b8ade1d0998d273db51f/packages/playwright-core/types/types.d.ts#L9877) and the latter saying it [defaults to `css`](https://github.com/microsoft/playwright/blob/77b1ec4a53425ae638d3b8ade1d0998d273db51f/packages/playwright-core/types/types.d.ts#L9877). It looks like it defaults to `device`, so the website documentation needs updating?

**Comment by yury-s** [comment]
> The test is failing, saying The result for this "15207 pixels (ratio 0.33 of all image pixels) are different."

It seems that the test is failing on the same screen too.

> Another thing I noticed was the inconsistency in documentation for the screenshot option scale under types.d.ts and the website, with the former saying it [defaults to device](https://github.com/microsoft/playwright/blob/77b1ec4a53425ae638d3b8ade1d0998d273db51f/packages/playwright-core/types/types.d.ts#L9877) and the latter saying it [defaults to css](https://github.com/microsoft/playwright/blob/77b1ec4a53425ae638d3b8ade1d0998d273db51f/packages/playwright-core/types/types.d.ts#L9877). It looks like it defaults to device, so the website documentation needs updating?

`page.screenshot` and `expect(page).toHaveScreenshot` do have different defaults, the documentation is correct.

**Comment by yury-s** [comment]
It looks like you are trying to test pdf rendering and that falls outside of scope of Playwright as we focus on Web. You can use something like PDF.js to render PDF and then test it as a regular website. Would that work?

**Comment by chowed** [comment]
Hi @yury-s , thank you for your investigation. If this is outside the scope of Playwright, I'm happy to close the issue.

And regarding the documentation - you are correct, my apologies.
