### ISSUE TITLE
[BUG] Headless vs headed chromium layout mismatch on Linux

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#24532]
### Headed
![screenshot](https://github.com/microsoft/playwright/assets/883973/91eecdf2-07d7-4508-ac5a-d62882a97c79)
---
### Headless
![screenshot-h](https://github.com/microsoft/playwright/assets/883973/0d931385-f3e6-4774-aaf6-70e773117180)

**Comment by pavelfeldman** [comment]
Steps to repro:

1. Install
```sh
npm init playwright@latest
```

2. Accept all defaults
3. Replace `tests/example.spec.ts` with
```js
import { test } from '@playwright/test';

test.use({ headless: false });

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  console.log(await page.getByRole('link', { name: 'Get started' }).boundingBox());
});
```

4. Run tests
```sh
npx playwright test --project chromium
```

**Comment by chenshuichao** [comment]
test.use({ headless: new });

**Comment by aslushnikov** [comment]
Meeting notes:
- move red dot to the target element instead of absolute coordinates
