### ISSUE TITLE
[BUG] Text selector not found in open shadow root

### ISSUE THREAD

**Issue by thernstig** [microsoft/playwright#2453]
**Context:**
- Playwright Version: 1.0.1
- Operating System:Linux
- Node version: 12.15.0
- Browser: Chromium

**Code Snippet**

`await page.waitForSelector('text=Details');` never finds the below. I can only share the JSPath since it is a private project.

`document.querySelector("body > container").shadowRoot.querySelector("#container > container-layout-holder").shadowRoot.querySelector("#LayoutHolder-app-content > app-content").shadowRoot.querySelector("#AppContent-inner > user-management").shadowRoot.querySelector("#details").shadowRoot.querySelector("div > div.tile__header > div.tile__header__left > div.tile__header__left__title")`

This is the text as seen in chrome dev tools:

![example](https://user-images.githubusercontent.com/30827238/83655515-cf639280-a5be-11ea-98d5-c835c6bea512.png)

**Comment by thernstig** [comment]
Here is another one that does not work with the text selector:

`await page.click('#confirm-delete >> text=Delete');`

This is how it looks:
![test](https://user-images.githubusercontent.com/30827238/83725704-a71d7780-a642-11ea-980e-2d12e9c4f9ca.png)

The `#confirm-delete` works fine to find, and also using `#confirm-delete > base-v0-button`

**Comment by dgozman** [comment]
I am trying to repro this and so far had no luck. Any kind of repro would be greatly appreciated!

Could it be that the element is not "visible"? For example, on the second screenshot it seems like "Delete" text is not in the shadow root, maybe it is not distributed to any slot?

**Comment by thernstig** [comment]
Sorry for getting back so late on this. Unfortunately I cannot share the code, and creating a repro would quite hard as it contains a ton of nested Web Components with a custom framework that compiles it all. Trying to think of ways I can help here hmm.

**Comment by dgozman** [comment]
Let me close this for now. Please reopen if you have a repro script.
