### ISSUE TITLE
Is it possible to disable the CORS process for extraHTTPHeaders?

### ISSUE THREAD

**Issue by landg-lance** [microsoft/playwright#24537]
According to this issue: https://github.com/microsoft/playwright/issues/21811 trying to use the extraHTTPHeaders will automatically include a CORS pre-flight request.  I'd like to know if I can disable this functionality; I'd just like to be able to send extra headers on the initial request, and skip the OPTIONS request.

I think the CORS functionality should be an option to turn on, but I don't really use Playwright in anger in situations that require CORS, so I understand if it's the default.  There should then be an option to turn it off if your project doesn't require it.  Or maybe there already is this option, I just can't find it in the docs!

**Comment by yury-s** [comment]
This is not currently possible. Folding this request into https://github.com/microsoft/playwright/issues/19904
