### ISSUE TITLE
[Question] By default when is a new "Browser" created (With Playwright Test)

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#24547]
So by default when using Playwright test the "Isolation" page tells us that each test by default creates a new "BrowserContext" and "Page": https://playwright.dev/docs/browser-contexts

However im curious to know: How often is a new "Browser" created? 

I assume based off the https://playwright.dev/docs/test-parallel guide that each worker is what handles a new "Browser" session and keeps using that within the same worker to save time. But the isolation page doesn't specifically state that. I am more just curious as I've never needed to directly interact with creating a new browser but I assume by default with "fullyParallel" set to true this is how it's done?

Thanks!

**Comment by yury-s** [comment]
> However im curious to know: How often is a new "Browser" created?

The browser is a [worker-scoped fixture](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) meaning that it is created once per worker process, see [this page](https://playwright.dev/docs/api/class-fixtures#fixtures-browser) for more details.

> I assume based off the https://playwright.dev/docs/test-parallel guide that each worker is what handles a new "Browser" session and keeps using that within the same worker to save time. But the isolation page doesn't specifically state that. I am more just curious as I've never needed to directly interact with creating a new browser but I assume by default with "fullyParallel" set to true this is how it's done?

`fullyParallel` essentially changes wether the tests from same file may run in parallel or will be run in one worker (default behavior). Once the max number of parallel workers is reached playwright will try to reuse existing workers once next test is finished. Depending on wether the worker process is reused, either the same browser is reused or a new one is created (in the new worker process).
