### ISSUE TITLE
[BUG] APIRequest POST fails without erroring on specific endpoints

### ISSUE THREAD

**Issue by perezdev** [microsoft/playwright#24545]
**this error is can't be reproduced with a public API for testing. I can't produce a test project.**

### System info
- Playwright Version: v1.36
- Operating System: Windows 10
- Browser: Chromium
- Other info:

### Source code

This is the code that is used to end a POST to the endpoint:

```
public async Send(endpoint: string, payload: any | null = null, includeHeaders = true): Promise<APIResponse> {
	try {
		const headers = this.AuthClient.GetAuthHeader(this.apiType, "application/json");
		const options = {};
		if (includeHeaders) {
			options["headers"] = headers;
		}
		if (payload) {
			options["data"] = payload;
		}
		const ctx = await request.newContext({ baseURL: this.apiUrl });
		const response = await ctx.post(endpoint, options);
		return response;
	}
	catch (error) {
		console.error("Error occurred:", error);
		throw error;
	}
}
```

**Steps**

I ran this against two endpoints that accept the same type of payload. Here is an example:

{
  "displayName": "test1",
  "email": "test1@test.com",
  "sendInvitation": true,
  "roleIds": [
    1,
    2,
    3
  ]
}

**Expected**

The first endpoint works as expected and produces a full log:

![image](https://github.com/microsoft/playwright/assets/3408775/fa87c638-b53d-43a4-a293-8fd0310dbce9)

**Actual**

But if I run it on the "bad" endpoint, it fails at `request.newContext`. But it doesn't produce an error and doesn't actually fail. No error is thrown. The entire test just stops and Playwright shows the test as passing.

![image](https://github.com/microsoft/playwright/assets/3408775/731813fa-2f1a-4a30-a9e4-84c3828e28b3)

Any ideas on what could be going on?

**Comment by yury-s** [comment]
We need a self-contained reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one, we cannot help without a repro as there is no way to tell what exactly your code does and what's the difference between the endpoits.
