### ISSUE TITLE
[BUG] Video is not generated when 'browser' is used in fixtures

### ISSUE THREAD

**Issue by ibrocodes7** [microsoft/playwright#24542]
### System info
- Playwright Version: [v1.24], and checked with latest as well.
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

## Fixture file

```ts 
import { Page, test as testBase } from '@playwright/test';
import { pageObject } from 'pages';

let contextPage: Page = null;

export const test = testBase.extend<{
  pageObject: PageObject;
}>({
  page: async ({browser}, use) => {
    contextPage = await browser.newPage();
    await use(contextPage);
  },
  pageObject: async ({ page }, use) => {
    await use(new PageObject(page));
  },
});

export const expect = test.expect;
```

or

**Config file**

```js
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';
import config from './config';
import { utils } from './src/utils';

const config: PlaywrightTestConfig = {
  globalSetup: './global-setup',
  globalTeardown: './global-teardown',
  args: ['--disable-features=IsolateOrigins,site-per-process'],
  headless: false,

  use: {
    // Artifacts
    baseURL: config.BASE_URL,
    headless: config.HEADLESS,
    viewport: { width: config.BROWSER_WIDTH, height: config.BROWSER_HEIGHT },
    ignoreHTTPSErrors: true,
    screenshot: 'on',
    video: 'on',
    trace: 'on',
    storageState: utils.getStateJsonFileName(),
    actionTimeout: config.ACTION_TIMEOUT * 1000,
    navigationTimeout: config.NAVIGATION_TIMEOUT * 1000,
    browserName: config.BROWSER,
  },
  timeout: config.TEST_TIMEOUT * 60 * 1000,

  expect: { timeout: 15 * 1000 }, 

  retries: config.RETRIES,

  workers: config.WORKERS,

  repeatEach: config.REPEAT_EACH,


  testDir: 'tests',

  reporter: [
    ['list'],
    [
      'allure-playwright',
    ],
    ['json', { outputFile: 'test-results.json' }],
    ['junit', { outputFile: 'test-results.xml' }],
    ['html', { open: 'never' }],
  ],
};

export default config;

```

**Test file (self-contained)**

```ts

test.beforeAll(async ({ basePage }) => {
  await basePage.setUrlFlag('flag', 'true');
});

it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
-Update the fixture file as I shared above with 'browser'.
-Run the test and wait for the test-results to be generated.
-Once the test is complete, a video-webm file is not generated as expected in the test-results folder.
-Now, if you modify the fixture from 'browser' to 'context' and run the test again:
      ```ts
      import { Page, test as testBase } from '@playwright/test';
      import { pageObject } from 'pages';
      
      let contextPage: Page = null;
      
      export const test = testBase.extend<{
        pageObject: PageObject;
      }>({
        page: async ({context}, use) => {
          contextPage = await context.newPage();
          await use(contextPage);
        },
        pageObject: async ({ page }, use) => {
          await use(new PageObject(page));
        },
      });
      
      export const expect = test.expect;
     ```
-You will notice that the video-webm file gets generated.
-However, the downside here is that I lose access to the 'beforeAll' hook when using 'context'.

**Actual**

The problem is that the video webm file isn't being generated in test-results when running the test with this code. It's quite puzzling because the video generation seems to work fine if I remove the 'page' part from the 'test' configuration. I'd really appreciate it if someone could shed some light on why this happens and if there's a solution to get the video webm file to generate even with the 'page' included. 

It appears to be generating video correctly when using 'context' instead of 'browser': The 'recordVideo' option appear to be missing when I console.log the 'browser.page' object.

Unfortunately, switching from 'browser' to 'context' prevents me from using the 'beforeAll' hook. Error: 
Error: "context" and "page" fixtures are not supported in beforeAll. Use browser.newContext() instead.
...  is there a way to fix it so that I can still use the same configuration?

Thanks in advance for any help! 

```ts
import { Page, test as testBase } from '@playwright/test';
import { pageObject } from 'pages';

let contextPage: Page = null;
export const test = testBase.extend<{
  pageObject: PageObject;
}>({
  page: async ({ context }, use) => {
    contextPage = await context.newPage();
    await use(contextPage);
  },
  pageObject: async ({ page }, use) => {
    await use(new PageObject(page));
  },
});

export const expect = test.expect;
```

**Comment by yury-s** [comment]
This is the same problem as described in https://github.com/microsoft/playwright/issues/14813 and more recently https://github.com/microsoft/playwright/issues/24502. Currently the videos are generated only for the pages in the context that was create with the built-in [context](https://playwright.dev/docs/api/class-fixtures#fixtures-context) fixture.

Folding this into https://github.com/microsoft/playwright/issues/14813, please upvote that issue instead.
