### ISSUE TITLE
[BUG] Error: tracing.stopChunk: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#24555]
### System info
- Playwright Version:   

-  "playwright": "^1.32.2",

 "devDependencies": {
    "@playwright/test": "^1.35.1",
    "allure-playwright": "^2.0.0-beta.16",
    "cross-env": "^7.0.3",
  }

- Operating System: All
- Browser: All
- Other info:

### Source code

    Error: tracing.stopChunk: ENOENT: no such file or directory, open '/Users/test-ui/playwright/test-results/.playwright-artifacts-0/traces/8032a828622df5d17c8e-d6742c2daf0cb4f09899.trace'

although the test is done executed, the test marked failed with the error above. Can you please explain?

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/23387, should be fixed in 1.37. If the problem persists with 1.37 please file a new issue with a repro that we could run locally.

**Comment by AdrianNeatu** [comment]
@yury-s I'm still able to reproduce the issue with "1.37.0". It happens when I trigger multiple playwright commands. I trigger playwright from a node.js app using express via child_process.spawn. This only happens when trace is on.

**Comment by yuanhuaqu** [comment]
I ran into similar error with latest version 1.37, turning trace off temporarily to bypass this error before this get fixed. I would love to turn it on again to test the fix when it is available. Thanks.
