### ISSUE TITLE
[Feature] Support for associating specific test script to test case in Azure DevOps Test Plan 

### ISSUE THREAD

**Issue by eltonmkw** [microsoft/playwright#24550]
Dear Playwright team,

I would like to request for tester ability to associate Playwright Test scripts with Azure DevOps Test Cases.
The most relevant documentations related to Azure DevOps test case association, you may refer [link ](https://learn.microsoft.com/en-us/azure/devops/test/associate-automated-test-with-test-case?view=azure-devops) here.

Thank you,
Elton M.

**Comment by yury-s** [comment]
You can add [custom annotations](https://playwright.dev/docs/test-annotations#custom-annotations) to the tests but that's probably not what you are looking for.

Folding this into https://github.com/microsoft/playwright/issues/14839 which tracks integration with Azure DevOps Test Plans. Please upvote that issue instead.

**Comment by eltonmkw** [comment]
Thanks @yury-s , that's really helpful.
