### ISSUE TITLE
[BUG] playwright.higlight(selector) is not working in console mode!

### ISSUE THREAD

**Issue by AlexanderMortimer** [microsoft/playwright#24562]
When I use playwright.higlight(selector) I receive below error in console:
 Uncaught TypeError: playwright.highlight is not a function
    at <anonymous>:1:12

**Comment by mxschmitt** [comment]
What is the console mode? I tried the following and it was working for me:

```py


from playwright.sync_api import sync_playwright

with sync_playwright() as playwright:
    browser = playwright.chromium.launch()
    page = browser.new_page()
    page.goto('http://playwright.dev')
    page.locator("body").highlight()
    page.wait_for_timeout(5000)
    page.close()
    browser.close()
```

**Comment by AlexanderMortimer** [comment]
I mean in dev tools(F12) console tab, write playwright.highlight("selector").as explained in documents.not in code.
@mxschmitt

**Comment by mxschmitt** [comment]
I see, when running `PWDEBUG=1 npx playwright open https://playwright.dev` according to [docs](https://playwright.dev/docs/debug#playwrighthighlightselector) we expose `playwright.highlight(selector)` while we don't actually do it.
