### ISSUE TITLE
[BUG] The callback of PerformanceObserver never be called by calling evaluate and addScriptTag

### ISSUE THREAD

**Issue by asdiver** [microsoft/playwright#24565]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [ macOS 11.5 ]
- Browser: [Chromium, Firefox, WebKit]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/asdiver/mini-frontend-monitor](https://github.com/asdiver/mini-frontend-monitor)

**Steps**
- clone repository, use branch:main
- install & pnpm run test

**Expected**
The callback of PerformanceObserver be called to trigger report event
```js
console.log('this callback never be called');
const firstPaintObserver = new window.PerformanceObserver((list) => {
  console.log(list);
  const custom = new CustomEvent('report', { detail: list });
  window.dispatchEvent(custom);
});
```

**Actual**
The callback of PerformanceObserver never be called by calling evaluate and addScriptTag
UI Mode OUTPUT can prove that

**Comment by yury-s** [comment]
By the time you [add ](https://github.com/asdiver/mini-frontend-monitor/blob/5a057beb40e782b579c0c2efe24de755e30af7e1/tests/first-paint.spec.ts#L10)the event listener paint event has already fired. You can see that by changing the code to use addInitScript instead of addScriptTag and counting the events using a global variable:

```js
// bug-example.js
console.log('this callback never be called in addScriptTag');
window.eventCount = 0;
const firstPaintObserver = new window.PerformanceObserver((list) => {
  ++eventCount;
  const custom = new CustomEvent('report', { detail: list });
  window.dispatchEvent(custom);
});
```

and then in the test:
```ts
// first-paint.spec.ts
test('first-paint', async ({ page }) => {
  await page.addInitScript({ path: './tests/bug-example.js' });
  await page.goto('https://cn.vitest.dev');

  // paint all
  page.on('console', msg => {console.log(msg)});

  const update = page.evaluate(() => {
    let resultProxy: Content[];

    window.addEventListener('report', (e) => {
      const contents = (e as CustomEvent<Content[]>).detail;
      resultProxy.push(...contents);
    });

    return new Promise((resolve) => {
      resultProxy = new Proxy<Content[]>([], {
        set: (target, p, newValue) => {
          target[p] = newValue;
          resolve(1);
          return true;
        },
      });
    });
  });
  
  console.log('this callback never be called in evaluate');
  page.evaluate(() => {
    const firstPaintObserver = new window.PerformanceObserver((list) => {
      console.log(list);
      const custom = new CustomEvent('report', { detail: list });
      window.dispatchEvent(custom);
    });
  })
  
  expect(await page.evaluate(() => window.eventCount)).toBe(0);

  await update;
  expect(true).toBeTruthy();
});
```
You can see that eventCount is already 1 as the page finished painting. You can create the Promise that collects event details inside the same init script and then simply get it using `page.evaluate(() => window.resultPromise);`

Will that work?

**Comment by asdiver** [comment]
Thank you @yury-s  for quick response!

- Based on your ideas, I replaced the addScriptTag with addInitScript, then it work. however, [report event](https://github.com/asdiver/mini-frontend-monitor/blob/5a057beb40e782b579c0c2efe24de755e30af7e1/tests/bug-example.js#L5) before registering for [event listening](https://github.com/asdiver/mini-frontend-monitor/blob/5a057beb40e782b579c0c2efe24de755e30af7e1/tests/first-paint.spec.ts#L10) will be ignored. That's also why I used addscript before, I will find new ways to replace window event
- I'm curious why addScriptTag is invalid, I'm trying to simulate addScriptTag like   
```
// html
<body>
  <script>
    const script = document.createElement("script")
    script.innerHTML = `
        // listen
    window.addEventListener('report', (e) => {
      console.log('Event report triggered:', e.detail);
    });

        // trigger
    const contents = [1, 2, 3];
    const custom = new CustomEvent('report', { detail: contents });
    window.dispatchEvent(custom);    
    `
    setTimeout(()=>{
      document.body.appendChild(script)
    },4000)
  </script>
</body>
```
but it can normal log.

**Comment by dgozman** [comment]
@asdiver You can also use [`page.exposeBinding`](https://playwright.dev/docs/api/class-page#page-expose-binding) instead of a custom event to report things from the page to your test. This should help with missing initial events.

**Comment by asdiver** [comment]
@dgozman Although I've found an alternative solution, exposeBinding indeed seems like a good option. thank you for your suggestion. I'm a beginner, Should I consider this issue reasonably closed now? Even though I'm still unsure why page.evaluate is causing the loss of the PerformanceObserver callback.

**Comment by dgozman** [comment]
> why page.evaluate is causing the loss of the PerformanceObserver callback

Since you call `page.evaluate()` after `page.goto()`, it might be missing some events happening before the `page.evaluate()` call.

> Should I consider this issue reasonably closed now?

I think so, since you have found a solution that works for you.
