### ISSUE TITLE
[Feature]Additional types

### ISSUE THREAD

**Issue by pdyulgerov** [microsoft/playwright#24561]
There are some playwright methods parameter or return type without specifically defined type. For example the `storageState` returns:

```
Promise<{
  cookies: Array<{
    name: string;
    value: string;
    domain: string;
    path: string;
    expires: number;
    httpOnly: boolean;
    secure: boolean;
    sameSite: 'Strict' | 'Lax' | 'None';
  }>;

  origins: Array<{
    origin: string;
    localStorage: Array<{
      name: string;
      value: string;
    }>;
  }>;
}>;
```
The same case is with `waitFor` and the `state` parameter: `state?: "attached"|"detached"|"visible"|"hidden";`

**Comment by pdyulgerov** [comment]
In fact it is not causing any problems. It would just be useful to be able to use playwright types when defining methods with arguments of the same type. For example the case with the `storageState` - if you save it in a json file it could be parsed as
```
type StorgeState = {
cookies: Cookies,
origin: Origin
}
```

**Comment by yury-s** [comment]
For StorageState in particular we'd like to make it an opaque type similar to how we did it in java port, but we can't do it at this point without breaking existing clients.

Also you can already reference return types of API methods using typescript [utility types](https://www.typescriptlang.org/docs/handbook/utility-types.html), e.g.:
```ts
import { type BrowserContext } from '@playwright/test';

  const t: Awaited<ReturnType<BrowserContext['storageState']>> = {
    cookies: [],
    origins: [],
  };
```

Closing this request as we are not planning to add named types.
