### ISSUE TITLE
[BUG] Mocking GQL calls does not work - route.request().PostData(), route,fetch() not working for chromium

### ISSUE THREAD

**Issue by devnigam24** [microsoft/playwright#24572]
### System info
- Playwright Version: 1.32.0
- Operating System: Node 14
- Browser: Chromium
- Other info: Firefox works

### Source code
Just trying to do as simple as mocking all Graph QL calls so that I can identify which one is mine and mock that. 

```
await page.route(**/graphql', async (route) => {
    console.log({postData:JSON.parse(route.request().postData() as string)}) => null 
    console.log({postDataJSON:route.request().postDataJSON()}) => null

    const response = await route.fetch(); => 400 error
    console.log({response});
    const json = await response.json();
    console.log({json});

    await route.fulfill({ response, json });
  });
```

In Firefox it all works like a charm. 

Found some [other issues](https://github.com/microsoft/playwright/issues?q=is%3Aissue+is%3Aopen+postData) related to this
Looks like still related to
[Chromium Bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1019710)

### If its still indeed a chromium issue, is there a workaround for identifying one graphQL call and mocking that one, and continuing the rest untouched?

Thanks

**Comment by yury-s** [comment]
Merging the report into https://github.com/microsoft/playwright/issues/6479, please upvote that one instead.
