### ISSUE TITLE
[Feature]  Flag -x respects --retries

### ISSUE THREAD

**Issue by cgetzen** [microsoft/playwright#24576]
I would like to be able to stop playwright after the first failure that has been retried to completion.

Right now, we cannot use `-x` and `--retries` together, as it will never have the opportunity to retry after the first failure.

This feature would be advantageous for cost-saving in CI.

**Comment by yury-s** [comment]
`-x` is intended to be used for development workflows where you make a change and want to stop on the first failing test and fix it.

For the CI scenario that you mentioned we recommend [`--max-failures`](https://playwright.dev/docs/api/class-testconfig#test-config-max-failures) flag. The idea of that one is exactly for "cost-saving in CI" when the code is fundamentally broken and you'd like to avoid wasting resources on running tests when too many of them are failing. With that said, we'd like to have a flexibility when the tests are retried when you pass `--retries` parameter - after running full suite or right away (see https://github.com/microsoft/playwright/issues/23462 and https://github.com/microsoft/playwright/issues/23354 which are related).

**Comment by cgetzen** [comment]
Hi @yury-s , I don't think --max-failures works with --retries in a similar way: if a test fails, retries and succeeds, max-failures will still count the failure.

In CI, I want to stop after the first test failure that retries to completion and still fails.
