### ISSUE TITLE
[Question] How to test web cam and mic using playwright?

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#24589]
Here's a link to the video test in [My test repo](https://github.com/siddharth2023/playwrightProjects/blob/main/tests/video.spec.ts)

I want to test webcam and mic on my web app so I am launching a context with the below flags. However I am not able to see the video. Also how do I add audio to my test so my web app can detect what's being said in the audio?

`tests/testFixture.ts`

```JS
context = await chromium.launchPersistentContext("", {
      headless: false,
      args: [
        "--auto-accept-camera-and-microphone-capture",
        "-use-fake-device-for-media-stream",
        // "--use-fake-ui-for-media-stream",
        "--use-file-for-fake-video-capture=sample_video.y4m",
      ],
    });
```

Also, is y4m the only accepted video format for testing?

**Comment by uchagani** [comment]
have you tried https://playwright.dev/dotnet/docs/api/class-browsercontext#browser-context-grant-permissions

**Comment by dgozman** [comment]
Folding into #2973.

**Comment by liedOliveira** [comment]
@siddharth2023 Were you able to enable the camera and microphone?
