### ISSUE TITLE
[Feature] Ability to import css files within @playwright/test and make them noop

### ISSUE THREAD

**Issue by Meemaw** [microsoft/playwright#24580]
Trying to write some visual tests using `@playwright/test`. We try to render our stories and take screenshoots. To do that, we import the stories to get the references.

The code might look something like this:

```jsx
import * as stories from './Button.stories';
import { getStoryId, loadStory } from '@/tests/story';
import { test } from '@playwright/test';

test('Button light', async ({ page }) => {
  await loadStory(page, getStoryId(stories, 'AllVariants'), 'light');
  await expect(page).toHaveScreenshot();
});

test('Button dark', async ({ page }) => {
  await loadStory(page, getStoryId(stories, 'AllVariants'), 'dark');
  await expect(page).toHaveScreenshot();
});
```

Importing stories also results in importing the components. If those components use css modules, Playwright will crash with an error failing to process those modules;

Something like this:
```sh
SyntaxError: Invalid or unexpected token

   at design-system/Loader/Loader.react.tsx:3

  1 | import React, { forwardRef } from 'react';
  2 | import { entries } from '../../lib/helpers/object';
> 3 | import loaderClassNames from './Loader.module.css';
```

Is there any workaround for this? For example, in `jest` its possible to make those imports a noop, with `moduleNameMapper`.

```js
moduleNameMapper: {
  "^.+\\.(css|less|scss)$": "identity-obj-proxy",
}
```

**Comment by Meemaw** [comment]
Its really just importing CSS files/modules within Playwright. Something as simple as this:

```js
import { test } from '@playwright/test';
import './index.css';

test('import css', async ({ page }) => {
  await page.goto('https://google.com');
});
```

I would expect this code to work, and the CSS imports to be ignored, because they do not influence Playwright execution at all.

**Comment by thednp** [comment]
Is this supported or not?

I'm working on webdriverio for browser non-headless tests via vitest and playwright for headless, where CSS isn't processed even if I set `test.css: true` in my *vitest.config.ts*.

What happens is that tests work fine on webdriverio because CSS is loaded and fail with playwright because CSS isn't loaded or not processed.

What's the solution here?
