### ISSUE TITLE
Network throttling to test streams

### ISSUE THREAD

**Issue by joacopaz** [microsoft/playwright#24590]
The ability to degrade the connection would be really useful, since we're building a videocall app and we have to handle a fallback were the video turns off in the case of a publisher's connection being slow. If we could throttle the connection, we would be able to mock and test that fallback handler.

We're using Playwright in Javascript.

**Comment by king-of-poppk** [comment]
Given #8622 was closed for housekeeping reasons explicitly recommending to open a new issue instead of re-opening I do not think it is appropriate to close the present issue.
