### ISSUE TITLE
[BUG] Wrong behaviour for Playwright grep regex

### ISSUE THREAD

**Issue by EldoradoEU** [microsoft/playwright#24604]
### System info
- Playwright Version: [v1.36.1]
- Operating System: Windows 10
- Browser: MS Edge
- Other info:

I have 3 test cases with names:
Testt, Test, TTest

command:
npx playwright test --grep "^Test$" should execute only test case "Test"

**Expected**

Playwright should run single test "Test"

**Actual**

Playwright run "TTest" and "Test" it looks like problem with sign "^" for --grep regex

**Comment by mxschmitt** [comment]
Playwright matches against the titlePath() not only the test title. We describe it [here](https://playwright.dev/docs/api/class-testproject#test-project-grep) but not [here](https://playwright.dev/docs/api/class-testconfig#test-config-grep) and [here](https://playwright.dev/docs/test-cli#reference). We should make it more clear.

**Comment by EldoradoEU** [comment]
I think it's still not clear, for example:

Our file has name first-test.spec.ts, so we can run only "Test" with:

npx playwright test -g "first-test.spec.ts.Test$".

Could explain how can I add next patterns for this grep regex? I'm searching OR, because I want send list of patterns with unique names. 

This is incorrect :
npx playwright test -g "first-test.spec.ts.Test$|first-test.spec.ts.TTest$"
