### ISSUE TITLE
[BUG] PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD does not have effect

### ISSUE THREAD

**Issue by klntsky** [microsoft/playwright#24607]
### System info

- Playwright Version: v1.36.2
- Operating System: Ubuntu 20
- Browser: Chromium
- Other info:

### Source code

This shell command results in browser download (copied from [the docs](https://playwright.dev/docs/browsers#skip-browser-downloads)) :

```bash
$ PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 npx playwright install
Downloading Chromium 115.0.5790.75 (playwright build v1071) from https://playwright.azureedge.net/builds/chromium/1071/chromium-linux.zip
146.4 Mb [==========          ] 51% 116.6s
```

- [x] I provided exact source code that allows reproducing the issue locally.

**Comment by stefan123t** [comment]
Just an idea, did you try this with `export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1` too ?

**Comment by khaled** [comment]
@stefan123t I've tried both "inline" and with an export.  Same result.

**Comment by najrei** [comment]
If you use the comand `npm init playwright` it lets you skip the browser download.

**Comment by michal-kralik** [comment]
I confirm I experience the same issue

**Comment by dgozman** [comment]
@klntsky We discussed this and decided that an explicit `npx playwright install` command should install browsers, even when `PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD` is set. Therefore I have adjusted the docs to not contain the erroneous command.

**Comment by klntsky** [comment]
How can I install without the browsers?
