### ISSUE TITLE
[BUG] playwright does not use the existing page when extending the test's context

### ISSUE THREAD

**Issue by azmy60** [microsoft/playwright#24600]
I followed the documentation for [chrome extensions](https://playwright.dev/docs/chrome-extensions). As soon as I unpack the page prop from the `test` second parameter, it creates a new page, so the browser contains two pages instead of one. I provided the simplified reproduction below instead of the full one from the docs.

### System info
- Package: @playwright/test
- Playwright Version: 1.36.2
- Operating System: Windows 11 (wsl)
- Browser: Chromium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```ts
import { test as base, chromium } from '@playwright/test'

export const test = base.extend({
    context: async ({}, use) => {
        const context = await chromium.launchPersistentContext('')
        console.log(context.pages().length) // 1 page
        await use(context)
        await context.close()
    },
})

test('example', async ({ context, page }) => {
    console.log(context.pages().length) // 2 pages
    await page.goto('http://example.com') // looks like this is using the new page
})
```

**Steps**
- Run the test without config
- See the console.log

**Expected**

I should see only one page and be able to use the default page from the context.

**Actual**

I see two pages though I didn't intentionally create a new page.

**Note**

I could easily fix this by extending the page fixture with something like this:

```ts
import { test as base, chromium } from '@playwright/test'

export const test = base.extend({
    context: async ({}, use) => {
        const context = await chromium.launchPersistentContext('')
        console.log(context.pages().length) // 1 page
        await use(context)
        await context.close()
    },
    page: async ({ context }, use) => {
        await use(context.pages()[0]!) // or pick the blank page if the context has devtools
    },
})

test('example', async ({ context, page }) => {
    console.log(context.pages().length) // 1 page
    await page.goto('http://example.com') // using the existing page
})
```

I think it would probably be nice if playwright can handle this automatically. The bug becomes obvious when you run this in headed mode.

**Comment by yury-s** [comment]
This is how default `page` fixture works, you can rewrite your test to not use it and only depend on the context or override the `page` fixture as you did. Alternatively, you can place the persistent page creation into the page fixture:

```ts
import { test as base, chromium } from '@playwright/test'

export const test = base.extend({
    page: async ({}, use) => {
        const context = await chromium.launchPersistentContext('')
        console.log(context.pages().length) // 1 page
        await use(context.pages()[0]!)
        await context.close()
    },
})

test('example', async ({ page }) => {
    await page.goto('http://example.com') // looks like this is using the new page
})
```
