### ISSUE TITLE
[Feature] is there any way to use allure with out java home setup ?

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#24606]
I have added all the commands which require to run allure report for playwright but no luck even the allure-command line throwing error like java home path is missing 
 
 Below is the command
allure generate ./allure-results --clean 

ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation.

**Comment by mxschmitt** [comment]
[Allure ](https://docs.qameta.io/allure/)is Java based, so this is not possible. We reaching out to [Allure](https://github.com/allure-framework/allure-java) for more questions.

**Comment by ajaygoutham1995** [comment]
> [Allure ](https://docs.qameta.io/allure/)is Java based, so this is not possible. We reaching out to [Allure](https://github.com/allure-framework/allure-java) for more questions.

Hi mxschmitt,
Any update form allure team for above request, that helps.

**Comment by mxschmitt** [comment]
I actually had a typo in my message above. I recommend reaching out to the Allure bug tracker.
