### ISSUE TITLE
[internal] Make sure nobody misuses `type()` instead of `fill()`

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#24614]

**Comment by dgozman** [comment]
- deprecate `type()`
- introduce `pressMultiple()` or something like that

**Comment by niranjan94** [comment]
Hi @dgozman :) 

I was using the `ElementHandle.type` now I see that is deprecated. But `pressSequentially` is only available on `Locator` and there is no good alternative available on `ElementHandle`. Could I request for `pressSequentially` to be made available on `ElementHandle` too ? 

My specific use-case requires me to use `ElementHandle` and not `Locator` as I specifically want to perform operations on a single element reference and do not want Locator's ability look up the element from the DOM on every usage.
