### ISSUE TITLE
[DOC Bug]   Help clarify deprecated methods in help.

### ISSUE THREAD

**Issue by DanoUnicity** [microsoft/playwright#24672]
Helping someone in the discord, seems someone was using deprecated functions.   Was thinking why or how...  Looking at the page might suggest methods under "Deprecated"  have some visual distinction?  Depending on the screen height consider the image below..  For context, in the image below i'm on the Page Api reference page and viewing within the  "waitForSelector"  but also scrolled the right side bar down to show methods that have been deprecated.   And here if someone isn't paying really close attention could easily use a method under the deprecated method. 

Just not sure  how, possibly a strike through font on the deprecated methods or a light grey font, something other than "BRIGHT WHITE" in order to make them stand out.  And/or a red boarder around the specific method's reference in the middle section...

Might see: 
![image](https://github.com/microsoft/playwright/assets/121905960/ea8026ef-d4b6-4817-8419-86d8330f7341)

**Comment by dgozman** [comment]
@DanoUnicity Thank you for the issue! There is a large banner about `page.waitForSelector` being discouraged, a bit higher up than the "Arguments" you are pointing at, which is the main indication of the method being deprecated.

We tried changing the sidebar, but that did not turn out as nice, so I don't think we'll be making changes in the short term.

<img width="844" alt="Screenshot 2023-08-07 at 9 26 56 AM" src="https://github.com/microsoft/playwright/assets/9881434/56100c2a-951c-4f72-a284-43b1e2790034">

**Comment by DanoUnicity** [comment]
Would agree the disclaimer is there on the page, but if deprecated might be better to not even show the depreciated methods on the side bar.  Or remove the item from the side bar, or just have one entry saying "Deprecated" then on the main section where the main help topic would appear, thus it would be removed from the right side bar,  even better might be to remove say page.click() or anything else deprecated from the help index/search...  

The only other issue would be say i'm using 1.35 where say a given method is available in 1.30 (or any previous)  then, as much of a pain it might be for a user,  make them have to select 1.30, i would have issue for anyone using any version see all things available for all version.  If it is deprecated, then remove it from the newest release... Make sense?
