### ISSUE TITLE
[Question] Plugin Support?

### ISSUE THREAD

**Issue by authrequest** [microsoft/playwright#2469]
I am currently trying to create a project with playwright and the project requires the ability to utilize plugins. Does playwright support the ability to use plugins? If not, will this feature be added in a future release?

**Comment by arjun27** [comment]
Thanks @authrequest. What plugins are these? Can you elaborate on your scenario(s)?

**Comment by authrequest** [comment]
So my thought was to be able to scrape JS enabled sites. And something similar to puppeteer-extra-plugin-stealth. Puppeteer is really heavy and using playwright I noticed that it is significantly lightweight compared to puppeteer. I would love to move to playwright for webscraping.

**Comment by arjun27** [comment]
Thanks. Something similar to puppeteer-extra can be created for playwright, but it is outside the scope of this project. We'd be happy to provide support for implementation focused questions/issues.
