### ISSUE TITLE
[Feature] securityDetails on Response object

### ISSUE THREAD

**Issue by StephenFluin** [microsoft/playwright#2474]
I'd love to see a feature to see the securityDetails of a Response object, including whether or not the response was served over a secure connection.

My use case is that when I load a site, I'm making a report showing that all of the requests are coming back using HTTPS, but I don't want to error or stop if a Response isn't using HTTPS.

**Comment by pavelfeldman** [comment]
You can already listen to all the requests and check their protocols for being HTTPS. Browsers will also issue console warnings upon mixed content.

Which other parts of the security details are essential to you? We would need to return them consistently from all the browsers.

**Comment by StephenFluin** [comment]
I'm not seeing protocol as being available anywhere on the Request object
(maybe I'm missing it?)
https://github.com/microsoft/playwright/blob/master/docs/api.md#class-request
.

For my app, I don't really need the other security details or information
about the certificate. I could see a use where I could report on the
TLS/SSL level or report of a site is using a deprecated encryption stack.

**Comment by pavelfeldman** [comment]
`request.url()` would tell you if that was https. Do you need more than that?

**Comment by abhishekdubey1** [comment]
Would love to have this functionality in playwright. Either Security details object similar to CDP or ability to access SSL certificate

**Comment by mxschmitt** [comment]
Closing since it was implemented in https://github.com/microsoft/playwright/pull/7150.
