### ISSUE TITLE
[Question] Regarding CDP Session.

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#2484]
I am converting all my puppeteer code which used to look like this.

https://github.com/shirshak55/scrapper-tools/blob/master/src/fastPage/index.ts#L113
```
const session = await page.target().createCDPSession()
  await session.send("Page.enable")
  await session.send("Page.setWebLifecycleState", {
    state: "active",
  })
```

So we went to docs and saw this
```
const client = await page.context().newCDPSession(page);
```

But now i am seeing error on typescript like this

`Property newCDPSession doesn't exists on type BrowserContext`

**Comment by pavelfeldman** [comment]
^^ @JoelEinbinder a ts types doc?

**Comment by JoelEinbinder** [comment]
`page.context()` needs to be casted to `ChromiumBrowserContext` in order to use `CDPSession`

**Comment by shirshak55** [comment]
@JoelEinbinder yep thanks I wrote 
```
const session = await (page.context() as ChromiumBrowserContext).newCDPSession(page)
``` 
and it works but can you let me know why it requires page argument when it is already given  page.context() ? I am asking because puppeteer doesn't use to require page argument?

**Comment by Niek** [comment]
The page parameter is strange indeed, as is the requirement to cast to `ChromiumBrowserContext`. Since all 3 supported browsers use CDP, it's unclear to me why the `newCDPSession()` method is not available in e.g `FFBrowserContext`.

**Comment by shirshak55** [comment]
@Niek Yea casting is not ergonomic. And the api to launch persistent and non persistent is so different i was so shocked :(

See this https://github.com/shirshak55/scrapper-tools/blob/5c216cd7b0894f16f2d07128b20812523e3afb1a/src/fastPage/index.ts#L137

**Comment by aslushnikov** [comment]
> Since all 3 supported browsers use CDP

@Niek this is not actually the case.
- In Chromium we rely on CDP
- In WebKit we rely on "Web Inspector Remote Debugging Protocol"
- In Firefox we rely on "Juggler" protocol

**Comment by Niek** [comment]
> * Juggler



> > Since all 3 supported browsers use CDP
> 
> @Niek this is not actually the case.
> 
> * In Chromium we rely on CDP
> * In WebKit we rely on "Web Inspector Remote Debugging Protocol"
> * In Firefox we rely on "Juggler" protocol

Apologies, I assumed Playwright (just like Puppeteer) used CDP for FF now that it's built-in (and enabled in at least the nightly builds). But reading https://github.com/microsoft/playwright/issues/1765#issuecomment-613178363 that's not the case until the CDP support in FF is more mature.
