### ISSUE TITLE
[Question] Changing download Directory?

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#2492]
Is there anyway to change download directory. In past i used to do 

```
  await cdpSession.send("Browser.setDownloadBehavior", { behavior: "allow", downloadPath: downloadDir }) // Probably new  but unstable 
  await cdpSession.send("Page.setDownloadBehavior", { behavior: "allow", downloadPath: downloadDir }) // Deprecated and doesn't work on latest chrome?
```

Currently i see playwright has api to handle downloads https://github.com/microsoft/playwright/blob/master/docs/api.md#class-download but I don't see ability to change directory . 

Is it possible to change download dir?

**Comment by yury-s** [comment]
There is no API for changing downloads folder. The files are saved into a temp directory and you can get full path of the file via [`download.path()`](https://playwright.dev/#version=v1.0.2&path=docs%2Fapi.md&q=downloadpath) or read its content via [`download.createReadStream()`](https://playwright.dev/#version=v1.0.2&path=docs%2Fapi.md&q=downloadcreatereadstream).

For more details see [Handle file downloads](https://playwright.dev/#version=v1.0.2&path=docs%2Fnetwork.md&q=handle-file-downloads) section.

**Comment by shirshak55** [comment]
@yury-s no i think you are confusing with launch and launchPersistentContext . When u run with launchPersistentContext download goes to download folder at least in osx. And even there is bug like some downloads that are initiated by Javascript are not even caught by page.on('download',()=>{})

**Comment by yury-s** [comment]
> @yury-s no i think you are confusing with launch and launchPersistentContext . When u run with launchPersistentContext download goes to download folder at least in osx.

Yes, I'm talking about ephemeral contexts. Downloads are fully supported in non-persistent contexts as of today. Is the feature not working for you in ephemeral context and you decided to use persistent context because of that or do you have to use persistent context for some other reason?


> And even there is bug like some downloads that are initiated by Javascript are not even caught by page.on('download',()=>{...})
>
This might be a separate bug, can you please share steps to reproduce it so that we can debug?
 

> And this is even blocked by #2493

This is a known limitation, let's discuss it separately in that report to keep this discussion focused.

**Comment by shirshak55** [comment]
@yury-s As a library author i need to support both ephemeral and non ephemeral context. But not being able to change a simple download folder is abit limitation. Sure I can move the file to wherever I like in  ephemeral context but what about non ephemeral context. 

Its not like I don't want to use `ephemeral context` but they have their own limitation like unable to save session, cookie and many other thing . I want to write tests like logging out, closing browser like as close to user do.  I think we will need ability to change download folder just like real chrome gives.

**Comment by pavelfeldman** [comment]
https://github.com/microsoft/playwright/pull/2503 -- does this work for you?

We'll get there with the storage persistence though. You can already capture and restore the cookies. What other aspects do you need to restore? Browser contexts are much faster than `launchPersistentContext`.

**Comment by shirshak55** [comment]
@pavelfeldman  thanks the PR #2503  should solves this issue (will test once i reach home).  
Yea the problem will be caching images etc in  ephemeral context right?  Regarding cookie the benefit with launchPersistentContext is browser automatically save cookie so i don't need to manually do (Doing manually has problem like i need to catch signals and errors so need to save cookie in such cases). it would be nice if we can specify file in non launchPersistentContext that automatically does this job.
