### ISSUE TITLE
[Question] Duplicate of property "value" 

### ISSUE THREAD

**Issue by laghim** [microsoft/playwright#2500]
Hi, in _browser_patches/firefox/juggler/protocol/Protocol.js_  there is  a duplicate of the property "value".

![image](https://user-images.githubusercontent.com/22259701/84069718-a59dd780-a9d3-11ea-8b32-a832ddfd87c1.png)

I believe that is redundant, is it correct? Thanks!

**Comment by pavelfeldman** [comment]
Sure is, I'll remove it in a drive-by
