### ISSUE TITLE
[BUG] html report filter query is not in sync with the url

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#25015]
1. Generate html report for tagged tests:
    ```ts
    import { test } from '@playwright/test';
    test('test1 @tag1 @tag2', () => {});
    test('test1 @tag1 @tag3', () => {});
    ```

2. Click on `tag2`. Note both url and filter input update.
3. Click on "clear" button in the filter input. Note that filter updates, but url does not.
4. Click on `tag3`. Note that filter and url now update to include both `tag2` and `tag3`.

**Comment by alexneo2003** [comment]
I will try to fix this
