### ISSUE TITLE
[Question] How to run Chrome browser instead of Chromium using playwright ?

### ISSUE THREAD

**Issue by grajesh690** [microsoft/playwright#2509]
I could see the executable path for providing path to browser. But it supports only installed version of chromium only. Any work around for running chrome browser ?

**Comment by yury-s** [comment]
You'd need to install Chrome separately and then specify path to it, there is no special support for that. Please reopen if you have further questions.

**Comment by atwright147** [comment]
How do you specify that path?

**Comment by yury-s** [comment]
There is [`executablePath`](https://playwright.dev/#version=v1.2.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-executablepath) option in `browserType.launch()`.
