### ISSUE TITLE
[Feature] how to simulate a paste event

### ISSUE THREAD

**Issue by Oloompa** [microsoft/playwright#2511]
Hi,

I tried the following code to trigger a paste event

```javascript
    const browser = await chromium.launch(options);
    const context = await browser.newContext();
    await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    const page = await context.newPage();
    await page.goto('http://example.com/');
    await page.evaluate(async (text) => {
        await navigator.clipboard.writeText(text);
        document.execCommand("paste");
    }, "123");
    await page.screenshot({ path: `example.png` });
```

But i got a rejection

```
(node:29654) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: __awaiter is not defined
    at __playwright_evaluation_script__:1:20
    at CRExecutionContext.evaluate (/home/project/node_modules/playwright-core/lib/chromium/crExecutionContext.js:82:23)
    at FrameManager.waitForSignalsCreatedBy (/home/project/node_modules/playwright-core/lib/frames.js:81:28)
    at FrameExecutionContext._doEvaluateInternal (/home/project/node_modules/playwright-core/lib/dom.js:42:16)
  -- ASYNC --
    at Frame.<anonymous> (/home/project/node_modules/playwright-core/lib/helper.js:63:23)
    at Page.evaluate (/home/project/node_modules/playwright-core/lib/page.js:257:33)
    at Page.<anonymous> (/home/project/node_modules/playwright-core/lib/helper.js:64:31)
    at /home/project/test/end2end/plop.spec.ts:16:16
    at step (/home/project/test/end2end/plop.spec.ts:33:23)
    at Object.next (/home/project/test/end2end/plop.spec.ts:14:53)
    at fulfilled (/home/project/test/end2end/plop.spec.ts:5:58)
```

I am not sure if it is an issue or if i am doing something wrong

**Comment by pavelfeldman** [comment]
A couple of issues here:
- `navigator.clipboard` is only available to content from the secure origins, replace url with `https://example.com` and it'll be there.
- document.execCommand("paste") will trigger the paste event, but won't trigger the default behavior.
- note that you are operating with the system clipboard, so other apps will have access to it and you can't run tests like this simultaneously. We are working on resolving this last item and isolating clipboards of the browser contexts.

```js
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({ headless: false });
    const context = await browser.newContext();
    await context.grantPermissions(["clipboard-read", "clipboard-write"]);
    const page = await context.newPage();
    await page.goto('https://chromium.org');
    await page.evaluate(async (text) => {
        await navigator.clipboard.writeText(text);
        const clipText = await navigator.clipboard.readText();
        document.querySelector('#jot-ui-searchInput').value = clipText;
    }, "123");
    await page.screenshot({ path: `example.png` });
})();
```

**Comment by pavelfeldman** [comment]
Updated the snipped above to actually trigger the paste event ^^. Note that it is platform-specific, Mac needs different shortcut. I'll leave this issue open for us to implement isolated clipboards and helper methods.

**Comment by Oloompa** [comment]
Clipboard support is quite low. I didn't notice it before. Paste event is not fired for most browsers using [Synchronous Clipboard API](https://caniuse.com/#search=clipboard).

**Comment by romadrobishevski** [comment]
Hello. Any news on implementing isolated clipboards and helpers? Would be nice to have them. Thanks.

**Comment by dgozman** [comment]
@romadrobishevski No exciting news just yet, but this issue is on our radar.

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by fzembow** [comment]
In case this helps anyone, I was able to emulate a text paste event using `evaluate`:

```ts
await page.locator('form').evaluate((formEl) => {
  const text = `Text to paste`;
  const clipboardData = new DataTransfer();
  clipboardData.setData('text/plain', text);
  const clipboardEvent = new ClipboardEvent('paste', {
    clipboardData
  });
  formEl.dispatchEvent(clipboardEvent);
});
```

**Comment by TomasHubelbauer** [comment]
FWIW this would be useful for cases where `waitForResponse` is used to notice that list was filtered down based on an input being typed into. Normal `.type` triggers multiple requests and responses (depending on the site's/app's debouncing) and it can cause false positives with `.waitForResponse` whereas a Playwright built-in `.paste('text')` would ensure only a single pair of request-response would appear and would make this scenario more reliable. I too would like to see this built in if there's ever time to address issues with fewer thumbs up like this one.

**Comment by eric-burel** [comment]
@fzembow solution works well to test the reaction of an element to a paste event. You can also change the data type to test pasting HTML for instance. You may probably get the content from the `navigator.clipboard` API to generate the event too. A bit convoluted but works.

**Comment by ritz078** [comment]
@fzembow Did the code snippet you shared work on firefox ?

**Comment by juliomelo** [comment]
Firefox works adding "dataType" and "data" attributes.

```js
await page.locator('form').evaluate((formEl) => {
  const data = `Text to paste`;
  const clipboardData = new DataTransfer();
  const dataType = 'text/plain';
  clipboardData.setData(dataType, data);
  const clipboardEvent = new ClipboardEvent('paste', {
    clipboardData,
    dataType,
    data
  });
  formEl.dispatchEvent(clipboardEvent);
});
```

**Comment by VGervasio** [comment]
> Firefox works adding "dataType" and "data" attributes.
> 
> await page.locator('form').evaluate((formEl) => {
>   const data = `Text to paste`;
>   const clipboardData = new DataTransfer();
>   const dataType = 'text/plain';
>   clipboardData.setData(dataType, data);
>   const clipboardEvent = new ClipboardEvent('paste', {
>     clipboardData,
>     dataType,
>     data
>   });
>   formEl.dispatchEvent(clipboardEvent);
> });

This did not work for me.
