### ISSUE TITLE
[Question] download file deleted while copying

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [microsoft/playwright#2523]
Downloaded files are getting deleted after test execution. How to solve this?

And also how to download file with actual file name?

**Comment by mxschmitt** [comment]
> Downloaded files are getting deleted after test execution. How to solve this?

Either copy the file from the `download.path()` location or use readableStream to handle storing of the file yourself.

> And also how to download file with actual file name?

You can use the `suggestedFilename()` function to get the original file name from the server. Ref: https://playwright.dev/#version=v1.1.0&path=docs%2Fapi.md&q=downloadsuggestedfilename

**Comment by Bharath-Kumar-S** [comment]
```
   const [download] = await Promise.all([
                page.waitForEvent('download'), // wait for download to start
                page.click(down)
            ]);
            const path = await download.path();
            console.log(path);
            const fs = require('fs');
            // destination will be created or overwritten by default.
            fs.copyFile(path, './', (err) => {
                if (err) throw err;
                console.log('File was copied to destination');
            });
```

I have tried already @mxschmitt. I am getting error that downloaded file does not exist.

![image](https://user-images.githubusercontent.com/26269665/84262678-a5205080-ab3b-11ea-98a9-069422432258.png)


I am using  `download.path();` to get the file location

**Comment by mxschmitt** [comment]
Did you set the acceptDownloas property to true?
https://playwright.dev/#version=v1.1.0&path=docs%2Fapi.md&q=browsernewcontextoptions--options-acceptdownloads

**Comment by Bharath-Kumar-S** [comment]
Yes, I am able to see that file is downloading

await browser.newContext({ acceptDownloads: true });

**Comment by rwoll** [comment]
@pavelfeldman If you haven't already started working on this, I'd be happy to add a `download.saveAs(path)` implementation and tests this week. Please let me know either way. Thanks!

**Comment by paulohenrique001** [comment]
Solução do problema
---------------------------------
const { chromium } = require('playwright');
const shell = require('node-powershell');
const fs = require('fs');

//console
var powershell = new Shell({
    executionPolicy: 'Bypass',
    noProfile: true
});

// Autamatização inicio
const browser2 = await chromium.launch({
    headless: false,
    downloadsPath: './downloads'
});

// Solução para download
const [download] = await Promise.all([
    await page.waitForEvent('download')
]);

const path = await download.path();

fs.rename(path, '${path}.xml', function(err) {
    if (err) console.log('ERROR: ' + err);
});

await powershell.addCommand("Unblock-File -Path .\\downloads\\*");
await powershell.invoke();
-------------------------------------------------

Acredito que o erro acontece por conta dos arquivos baixados pelo Playwright vem com a propriedade de outro computador, bloqueando assim algumas coisas, para burla isso, renomeei os arquivos e depôs usei uma biblioteca que me permite usar comando powershell direto pelo script e então executei o 'Unblock-File -Path' na pasta do meus arquivos para desbloquear os arquivos baixados.


Aqui está alguns links uteis:
[fs](https://nodejs.org/api/fs.html)
[Unblock-File Doc](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/unblock-file?view=powershell-7.1)
