### ISSUE TITLE
[BUG]Waitforselector fail to read the element in execution but works when debugging.

### ISSUE THREAD

**Issue by vrknetha** [microsoft/playwright#2527]
**Context:**
- Playwright Version: [1.0.2]
- Operating System: [Windows]
- Node version: [12]
- Browser: [Chromium]
- Extra: [Jest]
**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
await page.waitForSelector('[data-target="#addRemoveModal"]');
```

**Describe the bug**

The selector works when I put on a breakpoint before executing this step but fails in execution.

`<a _ngcontent-blu-c7="" class="btn btn-link" data-target="#addRemoveModal" data-toggle="modal" href="javascript:" xpath="1">Assign/Remove groups </a>`

`  pw:api     waiting for scheduled navigations to finish +1ms
  pw:api     navigations have finished +3ms
  pw:api <= page.click succeeded +6ms
  pw:api => page.waitForSelector started +2ms
  pw:api   waiting for selector "[data-target="#addRemoveModal"]" to be visible +1ms
  pw:api <= page.waitForSelector failed +30s`

**Comment by pavelfeldman** [comment]
Assuming the suggestion above was the case.
