### ISSUE TITLE
[Question] - How can you obtain the current HTML content of the page you are on?

### ISSUE THREAD

**Issue by jaequery** [microsoft/playwright#2528]
Hi, so let's say I have the crawler go to this page and that page, now, I want to extract the full HTML source code of that page.

How can I do that? I don't see any page.* methods for that to work.

Can anyone help?

**Comment by dgozman** [comment]
Thank you @osmenia, `page.content()` should do it.

Closing for now, please reopen/comment if `page.content()` does not work.

**Comment by pohlt** [comment]
I had the same question (how to get page's source code), searched through the API docs for "source", couldn't find it, and finally came here.
Maybe you can sneak in the words "source code" in the content() documentation.

**Comment by gabriel-cantanhede** [comment]
> Hi, so let's say I have the crawler go to this page and that page, now, I want to extract the full HTML source code of that page.
> 
> How can I do that? I don't see any page.* methods for that to work.
> 
> Can anyone help?

There's two possibilities: 1 - Getting the unresolved (no javascript rendering) content, and 2 - Getting the HTML content.

For the first: 
`
# first go to the page, which will get you a response
response = await page.goto('page_url')

# Then get the response's content as text
print(await response.text())

`
For the secont (which was what I was looking for when I stumbled here): 

`
# first go to the page, which will get you a response
await page.goto('page_url')

# Select the element you want from the page by using a Locator. Eg: A 'section' tag with the class 'content'
test = page.locator('section.content') # If you're getting more than one element, try filtering by adding ".filter(has=page.locator('selector for inner element')"

# Then just get the HTML content by using inner_html
print(await test.inner_html())
`
