### ISSUE TITLE
[BUG] Firefox doesn't install when using a installler made with electron-builder.

### ISSUE THREAD

**Issue by SentoxAIO** [microsoft/playwright#2539]
**Context:**
- Playwright Version: ^1.1.0-next.1591850160480
- Operating System: Window
- Node version: v14.1.0.
- Browser: Firefox
- Extra: Compiled Electron App/Installer made with electron-builder

**Describe the bug**
Playwright works perfectly if it isn't compiled but once I package the app with electron-builder and run the installer on a different device I get a error when running the playwright.
Thats the error:
![image](https://user-images.githubusercontent.com/57367608/84405400-5a203f00-ac08-11ea-8ad3-7c475fbb9328.png)

Seems like playwright's firefox browser  is execluded by the installer.

**Comment by dgozman** [comment]
Thank you for filing an issue. Could you please provide more details? Ideally, it would be some repro steps like "clone this, run this, deploy here, see this error".

Without a repro, I have a number of questions:
- Are you using playwright-electron to automate electron?
- How is Firefox related to the compiled electron app? I cannot find any mentions of Firefox with electron-builder.
- It seems like you miss the downloaded Firefox binary. Did you run npm install? Were there any errors?

**Comment by SentoxAIO** [comment]
Are you using playwright-electron to automate electron?
- No, playwright has no influence on electron, its just used to run a script.

How is Firefox related to the compiled electron app? I cannot find any mentions of Firefox with electron-builder.
- What I meant by that was that when I run it on my computere where I have globally installed playwright it all works perfectly. But once I buildt he electron app with all the modules, playwright should normally also should be completly included since its in the package.json. But once a user runs the installer on their device it seems not to install everything from playwright since the error says that firefox is missing. The install I build is only 68 MB big which is another proof that it the browsers didnt got packed.

It seems like you miss the downloaded Firefox binary. Did you run npm install? Were there any errors?
- As I said I dont have the error on my computer since I ran npm install but normally the installer should do the same but it doesnt.

I hope you can now understand my issue a bit better.

**Comment by dgozman** [comment]
Thanks, this helps.

So, if I understand correctly, the electron-builder should run `npm install` for playwright, and when it does so, the browsers are downloaded in the shared location that is not bundled.

You can try to run the bundler with `PLAYWRIGHT_BROWSERS_PATH=0` to download browsers inside the node_modules folder. However, the end user will have to use `PLAYWRIGHT_BROWSERS_PATH=0` when running the playwright script, so that Playwright uses browsers from the node_modules. Would this work?

**Comment by SentoxAIO** [comment]
"electron-builder should run npm install for playwright"
- I'm not sure if thats the right to say. Electron builder just packs all the packages and code but it doesn't pack the browsers into the installers. Thats basically the issue

"to use PLAYWRIGHT_BROWSERS_PATH=0 when running the playwright script"
- The users wont have access to the code so thats not a option

**Comment by dgozman** [comment]
> "electron-builder should run npm install for playwright"
> 
> * I'm not sure if thats the right thing to say. Electron builder just packs all the packages and code but it doesn't pack the browsers into the installers. Thats basically the issue

Well, someone has to run `npm install`, otherwise Playwright won't be able to download browsers. I'd suggest to figure out who is supposed to run playwright's install script. It might as well be the end user, if there is a way to run [this file](https://github.com/microsoft/playwright/blob/master/packages/playwright/install.js) on their machine.

**Comment by SentoxAIO** [comment]
I know what you mean by that but why did it work for puppeteer then?

**Comment by dgozman** [comment]
> I know what you mean by that but why did it work for puppeteer then?

Most likely, puppeteer does not download to the shared location, but uses node_modules instead. That's what `PLAYWRIGHT_BROWSERS_PATH=0` should do. However, this is just my speculation.

**Comment by SentoxAIO** [comment]
I think I get what you mean now. This might sound dumb know but how can I install with PLAYWRIGHT_BROWSERS_PATH=0? Is there a doc for it?

**Comment by dgozman** [comment]
That's right. Look at our [docs](https://playwright.dev/#version=master&path=docs%2Finstallation.md&q=managing-browser-binaries) for more information.

**Comment by SentoxAIO** [comment]
Weird cuz that doesnt work for me 
![image](https://user-images.githubusercontent.com/57367608/84546529-cd59ac00-ad01-11ea-9845-bee485d97980.png)

**Comment by arjun27** [comment]
@SentoxAIO, to set the env var in windows, you can run

```
set PLAYWRIGHT_BROWSERS_PATH=0
npm install playwright-firefox
```

I'm updating the docs to work across platforms. Sorry for the confusion.

**Comment by SentoxAIO** [comment]
All good, thank you guys very much

**Comment by SentoxAIO** [comment]
So I have now playwright and firefox installed in the node_modules and firefox now also appears in the  installer, but I still have the same error so it seems like firefox doesn't get launched properly on packaged code (on an exe).

Do you guys have any idea why that is?

**Comment by SentoxAIO** [comment]
Update: 
![image](https://user-images.githubusercontent.com/57367608/84602214-06228e00-ae86-11ea-9bd1-1979dd74efd7.png) 
Firefox is actually installed

but I still get this error: 
![image](https://user-images.githubusercontent.com/57367608/84602224-1aff2180-ae86-11ea-98b8-669656446d4b.png)

**Comment by dgozman** [comment]
@SentoxAIO I see you closed this one. Does that mean everything worked out?

>So I have now playwright and firefox installed in the node_modules and firefox now also appears in the installer, but I still have the same error so it seems like firefox doesn't get launched properly on packaged code (on an exe).
>
> Do you guys have any idea why that is?

You'll have to also pass `PLAYWRIGHT_BROWSERS_PATH=0` when running the playwright script (from the packaged app).

**Comment by SentoxAIO** [comment]
Yeah I got it working now. Thx for your help. Appreciate it a lot

**Comment by mattduffield** [comment]
@SentoxAIO what did you end up doing for your end users? I am wanting to achieve the same thing. My end users are not at all technical so trying to force them to install dependencies is not an option. Also, they aren't part of a company that could do it for them via a group policy. Just curious how you ended up solving the problem.

**Comment by isaacaddis** [comment]
+1 @matt, I'm having the same issue
