### ISSUE TITLE
[BUG] unable to launch firefox on virtual box windows

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2547]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows 10 build 1809 (running on Virtualbox)
- Node version: 12.8
- Browser: Firefox

**Code Snippet**

```javascript
const {firefox} = require('playwright');

(async () => {
  const browser = await firefox.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await browser.close();
})();
```

**Describe the bug**

Firefox does not launch, in headless/headful modes.

![Screen Shot 2020-06-11 at 1 11 45 PM](https://user-images.githubusercontent.com/284612/84434589-2b44a180-abe5-11ea-9029-ef76ace391ef.png)

**Comment by arjun27** [comment]
Running firefox directly gives me the missing dll
![IMAGE 2020-06-11 15:00:25](https://user-images.githubusercontent.com/284612/84443349-4834a100-abf4-11ea-970a-6af84729b5b2.jpg)

**Comment by pavelfeldman** [comment]
Firefox now requires `msvcp140.dll` and `vcruntime140.dll`. Let's bundle the same list of dlls that we bundle for WebKit for firefox.

**Comment by yury-s** [comment]
Launch doctor will now print an instruction to install Visual Studio C Runtime redistributable from Microsoft web site if these libraries are missing. Please reopen if you think we still want to bundle them with Firefox.
