### ISSUE TITLE
[BUG] unable to launch webkit on virtual box windows

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2548]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows 10 build 1809 (running on Virtualbox)
- Node version: 12.8
- Browser: WebKit

**Code Snippet**

```javascript
const {webkit} = require('playwright');

(async () => {
  const browser = await webkit.launch({ headless: false });
  const page = await browser.newPage();
  await page.goto('https://example.com');
  await browser.close();
})();
```

**Describe the bug**

WebKit does not launch, in headless/headful modes. I can see the PlaywrightLibrary.dll file in the right directory though - unclear what the error message is referring to

![Screen Shot 2020-06-11 at 1 06 45 PM](https://user-images.githubusercontent.com/284612/84434733-6b0b8900-abe5-11ea-9a88-634f0337e85f.png)

![Screen Shot 2020-06-11 at 1 13 52 PM](https://user-images.githubusercontent.com/284612/84434724-67780200-abe5-11ea-8576-fa5eb648aed9.png)

**Comment by pavelfeldman** [comment]
Works for me out of the box on a fresh Win10 install

**Comment by niksimms** [comment]
I get the same issue Window 2012 R2
Testing:
const playwright = require('playwright');

(async () => {
  for (const browserType of ['chromium', 'firefox', 'webkit']) {
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto('http://whatsmyuseragent.org/');
    await page.screenshot({ path: `example-${browserType}.png` });
    await browser.close();
  }
})();

Chromium and Firefox output correctly.

**Comment by fujii** [comment]
Can you try Dependency Walker to find out what is the missing DLL for PlaywrightLib.dll.
![dw](https://user-images.githubusercontent.com/36109/84950316-aea44c80-b129-11ea-8895-f8e76c3bfd78.PNG)

**Comment by arjun27** [comment]
That was helpful, @fujii! I realized I was on Windows 10 N that was missing a host of api-ms-win-core-* dlls. I installed [Media Feature Pack](https://www.microsoft.com/en-us/software-download/mediafeaturepack) and now I can run WebKit 🎉

@niksimms - can you try running [Dependency Walker](https://www.dependencywalker.com/)?

**Comment by fujii** [comment]
Ah, it's my fault. I assumed no one is using Windows 10 N.
I filed a WebKit bugzilla ticket.

Bug 213330 – [WinCairo][MediaFoundation] Use /DELAYLOAD for mf.dll
https://bugs.webkit.org/show_bug.cgi?id=213330

If you are willing to contribute a patch, I'd be glad to review the patch.

**Comment by fawazahmed0** [comment]
I got the same error, I am on windows 7
Other browsers seems to work fine, except webkit

**Comment by fujii** [comment]
I believe upstream WebKit WinCairo port fiexed the issue. https://trac.webkit.org/r264188

**Comment by yury-s** [comment]
Closing as the should be fixed in recent builds and we now also have launch doctor functionality which should help debugging such issues.
