### ISSUE TITLE
[Question] Running WebKit GTK on Ubuntu 20.04

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2559]
WebKit GTK (headful) requires libffi.so.6 which is not available on Ubuntu 20.04 ([list of available packages](https://packages.ubuntu.com/focal/allpackages)).

![Screen Shot 2020-06-12 at 12 06 12 PM](https://user-images.githubusercontent.com/284612/84537691-1d565580-aca5-11ea-8ad1-abd6e368f430.png)

The closest match is libffi7, and my workaround is to symlink it as libffi.so.6:

```
$ find /usr/lib -name "libffi.so*"
/usr/lib/x86_64-linux-gnu/libffi.so.7

$ sudo ln -s /usr/lib/x86_64-linux-gnu/libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
``` 

Filing this for others that might run into it, and to verify if this is the best way.

**Comment by aslushnikov** [comment]
This is fixed now!
