### ISSUE TITLE
[Question] Succint list of pro and cons versus Cypress 

### ISSUE THREAD

**Issue by LifeIsStrange** [microsoft/playwright#2560]
It seems that playwright is an alternative to [Cypress](https://www.cypress.io) right?

If so you should communicate how do they compare in order to reach users. 
A strength that I see is that you supports Firefox for example. In what other ways would playwright be better? And in what other ways does it has to catch up?

**Comment by pavelfeldman** [comment]
I would not want the comparison to originate from the Playwright team, I'd rather trust third party to perform this analysis! We would do our best at describing our features, but we won't be issuing a checkbox matrix where we have more checks than the others!

**Comment by LifeIsStrange** [comment]
*but we won't be issuing a checkbox matrix where we have more checks than the others!*
I understand the basic Idea of not wanting to be perceived as a competitor or to not want to be perceived as doing oppressive or unfair marketing against cypress or competitor X. 
But If you do the comparison matrix based on objective presence or absence of features (without the need of quantifying how useful the feature is) and that you accept pull requests from anybody (and from cypress) that would objectively correct a presence or an absence then I don't see any inconvenient to create such a feature matrix. But I do see an inconvenient of not having such a matrix.
If you wait for third parties, you better link them in your Readme, otherwise they would be not get visibility. 
Also, I doubt third parties would actually benevolently create for you a feature matrix, they wouldn't even have the expertise that only you have. They would better write a lower quality medium blog post that would be far less objective than the ability to quickly see absence and presence of said features.

Anyway do whatever you want but you might want to reconsider. 
Currently as a user I don't know why I would use your lib and if nothing happen, in a month or two I will mostly forget about its existence despite it being able to potentially improve my integration testing experience.
