### ISSUE TITLE
[Question] How to access Print dialog?

### ISSUE THREAD

**Issue by jaequery** [microsoft/playwright#2563]
Hi, I want to automate where you can click to activate javascript Print dialog, which then asks you to save as PDF and return the PDF file.
Is this possible to do?

**Comment by arjun27** [comment]
You can use the `page.pdf` API to generate a pdf of the page in Chromium: https://github.com/microsoft/playwright/blob/master/docs/api.md#pagepdfoptions

**Comment by jaequery** [comment]
Thanks

**Comment by tobiasfeil** [comment]
Can you update the link please, it's dead.

**Comment by yury-s** [comment]
Done, the new link is https://playwright.dev/docs/api/class-page?_highlight=page.pdf#pagepdfoptions

**Comment by WooriPbg** [comment]
page.pdf API new link: https://playwright.dev/docs/api/class-page#page-pdf
