### ISSUE TITLE
How to accept cookie of any webpage using automation?

### ISSUE THREAD

**Issue by kunal0810** [microsoft/playwright#2566]
0

I am working on project where i am taking the screenshot of various web pages. i have used the playwright nodejs package to take screenshot. when i navigate to the required url. web page loaded along with dialog box of accepting cookies in centre . I want to accept the cookies than takes screenshot.

**Comment by pavelfeldman** [comment]
There is no generic solution to this since those dialogs are all different, implemented using different frameworks using different people. Playwright is an automation library, so it leaves this problem to the third parties.

**Comment by Distil62** [comment]
Hello ! 
I want give a solution for this issue.
The best way to dismiss all EU cookie with playwright is follow this guide 
https://github.com/aslushnikov/demo-playwright-with-firefox-web-extension

And use this extension https://addons.mozilla.org/fr/firefox/addon/i-dont-care-about-cookies/
and use this extension for get the sources https://addons.mozilla.org/fr/firefox/addon/crxviewer/

Available only for firefox.

**Comment by WannabeDoctor** [comment]
Just copy the xpath of the accept button and use"page.select(path)"

**Comment by fynn-grab** [comment]
I had the same problem and built [ai-dont-care-about-cookies](https://github.com/fynn-grab/AI-Dont-Care-About-Cookies) to solve it. One function call before your screenshots, works across all websites:

```js
const { blockCookieDialogs } = require('ai-dont-care-about-cookies');
await blockCookieDialogs(page);
await page.goto('https://www.spiegel.de');
await page.screenshot({ path: 'clean.png' }); // no cookie banner
```

Uses 15,000+ domain rules, survives navigations, works in headless. Also on [npm](https://www.npmjs.com/package/ai-dont-care-about-cookies) and [PyPI](https://pypi.org/project/ai-dont-care-about-cookies/).
