### ISSUE TITLE
waitForSelector('//select/option') is not working 

### ISSUE THREAD

**Issue by yassinevic** [microsoft/playwright#2569]
**Context:**
- Playwright Version: ^1.1.0
- Operating System: Windows 10
- Node version: 14
- Browser: Chromium

**Code Snippet**

Hello.
Playwright can not resolve the element bellow:

`<select class="browser-default" id="codeBureauEnregistrement" name="codeBureauEnregistrement">
	<option value="11000">11000</option>
	<option value="12000">12000</option>
	<option value="13000">13000</option>
	<option value="14000">14000</option>
	<option value="15000">15000</option>
</select>
`

```javascript
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
await this.page.waitForSelector(`//select[@id='codeBureauEnregistrement']/option[@value='12000']`);
})();
```

**Describe the bug**
I tested the xpath expression, it works with native javascript. but not with Playwright .

**Comment by pavelfeldman** [comment]
`waitForSelector` waits for the element to be [visible](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=pagewaitforselectorselector-options--options-state), which never occurs for the option in the drop down. You can set `state: "attached"` to wait for it to be in the DOM, or you can wait for the select element instead - there isn't much use in the option element handle anyways.

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.setContent(`
    <select class="browser-default" id="codeBureauEnregistrement" name="codeBureauEnregistrement">
      <option value="11000">11000</option>
      <option value="12000">12000</option
      <option value="13000">13000</option>
      <option value="14000">14000</option>
      <option value="15000">15000</option>
    </select>`)
  await page.waitForSelector(
      `//select[@id='codeBureauEnregistrement']/option[@value='12000']`,
      { state: 'attached' });
  await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
Please feel free to reopen if there are more questions / requests.
