### ISSUE TITLE
How to intercept websocket communication?

### ISSUE THREAD

**Issue by theskhan** [microsoft/playwright#2572]
I did not find any example/api using which I could intercept websocket communication.  

I have a website connecting to remote server through websocket, I want to intercept and listen to the communication, how do I achieve that?

**Comment by pavelfeldman** [comment]
Do you need to listen only or to intercept as well? I had web socket instrumentation in works, but was waiting for the customer.

**Comment by theskhan** [comment]
Actually both.  
Would be great if you could share that ?

**Comment by pavelfeldman** [comment]
I only had API for web socket frame inspection, not interception. If that would be helpful - I'll go back to it and finish my implementation for WebKit (I already had it working for Chromium and Firefox). But if you anyways need to mock responses, that's something that would be very hard to do in Chromium, so achieving it could be simpler via mocking the web socket API in the user land instead.

**Comment by theskhan** [comment]
hmm..

My need was to intercept the websocket communication, take action when specific message received, send the message back to the server through the same websocket.. something like man in the middle without disturbing the normal communication.

I looked into Selenium, but there was no easy way to do this. The only way I found is to monkey patch the low level networking APIs.

Something like this:
https://stackoverflow.com/questions/57893407/capturing-websocket-messages-from-network-tab
https://chromedevtools.github.io/devtools-protocol/tot/Network/#event-webSocketClosed

It would have been better if browser autmation frameworks provide this as built in feature with simpler APIs.

**Comment by pavelfeldman** [comment]
DevRools protocol you point at does not have web socket interception, just sniffing, so you can't do man in the middle. But you can totally do it in the userland via calling `page.addInitScript` and replacing WebSocket with your own.

**Comment by theskhan** [comment]
Ok, thanks for clarifying. I think what you mention should work. I will try that.  Thanks!

**Comment by TobiasPfeifer** [comment]
@pavelfeldman I've found the pull request you mentioned #542 which is displayed as merged into master. However browsing master I cannot find the docs.

Being able to inspect websocket messages would be great for my use case

**Comment by aslushnikov** [comment]
To sum up the issue:
- the websocket feature is discussed here: https://github.com/microsoft/playwright/issues/2695
- there's also a [neat workaround](https://github.com/microsoft/playwright/issues/2572#issuecomment-645516059) for those who are interested

Let's continue discussion in #2695.
