### ISSUE TITLE
Property 'setRequestInterception' does not exist on type 'Page'

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2574]
I'm facing an issue when calling `page.setRequestInterception(true)`, it works well on puppeteer, so do we have a plan to support this method?

**Comment by pavelfeldman** [comment]
We have it, but in a different shape:

https://playwright.dev/#version=v1.1.1&path=docs%2Fnetwork.md&q=handle-requests

**Comment by pavelfeldman** [comment]
Please feel free to reopen if there are more questions / requests.

**Comment by TomasHubelbauer** [comment]
Hi, that link is broken now. I was able to get it to work using this code:
```javascript
async function block3rdPartyNetworking(/** @type {playwright.Page} */ page) {
  await page.route('**/*', async route => {
    const { hostname } = new URL(route.request().url());
    if (!allowedHostnames.includes(hostname)) {
      await route.abort();
    } else {
      await route.continue();
    }
  });
}
```
