### ISSUE TITLE
[Question] how to use DEBUG=pw:api?

### ISSUE THREAD

**Issue by osmenia** [microsoft/playwright#2575]
Hi Team,

Sorry, but i could not find in docs how to use DEBUG=pw:api.

How can i run script with the DEBUG=pw:api? (pls give me example)

is it possible to save output in File?

tnx a lot

**Comment by pavelfeldman** [comment]
```sh
# Windows..
set DEBUG=pw:api
node test.js

# MacOS, Linux
DEBUG=pw:api node test.js
```

**Comment by pavelfeldman** [comment]
@arjun27 let's add this to https://playwright.dev/#version=v1.1.1&path=docs%2Fintro.md&q=debugging-scripts

**Comment by pavelfeldman** [comment]
Actually, it will close with the docs.
