### ISSUE TITLE
[BUG] checked attribute returns falsy value

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2583]
**Context:**
- Playwright Version: 1.1.0-next.1591924870952
- Operating System: Mac
- Browser: Chromium

**Code Snippet**

When a radio button/checkbox has the `checked` attribute, it should return a truthy value.

```javascript
const {chromium, webkit} = require('playwright');
const assert = require('assert');

(async() => {
  const browser = await chromium.launch({headless: false, slowMo: 10});
  const page = await browser.newPage();
  await page.setContent(`
  <div>
    <input type="radio" name="my-input" id="yes" checked>
    <label for="yes">Yes</label>

    <input type="radio" name="my-input" id="no">
    <label for="no">No</label>
  </div>
  `);
  const q = await page.getAttribute('#yes', 'checked');
  assert(q);
  await browser.close();
})();
```

`q` is returned as an empty string, which is a falsy value, and the assertion fails. Should this return `true`?

**Comment by pavelfeldman** [comment]
It works the same way as `element.getAttribute('checked')` that returns `""`. We could add `hasAttribute` for clarity. For now, `assert(q !== null)` should do the trick.

**Comment by arjun27** [comment]
ah fair, I didn't realized `element.getAttribute` returns the same value. closing.

**Comment by pavelfeldman** [comment]
Another option: `page.$eval('#yes', e => e.checked)`
