### ISSUE TITLE
How can I call an external function in class inside  page.evaluateHandle(...) context

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2587]
I have a context:
```
export class Example extends ParentExample {
	get pageFunc() {
		return this.pageFn
	}

	async find(page: Page) {
		const args = any
                console.log(this.pageFunc) 
		const handle = await page
			.evaluateHandle(() => this.pageFunc, JSON.stringify(args))
                .....
	}
}
```
I'm facing an issue that the `find` function does not work because in `evaluateHandle` context, `this.pageFunc` is undefined, but the console log show it does not. When I try to replace directly code of the `pageFunc` likes
```
const handle = await page
			.evaluateHandle((args: any) => { console.log(args) }, JSON.stringify(args))
```
then it works. So anyone can help me to have a look at this.

**Comment by shirshak55** [comment]
`page.evaluateHandle` will run inside browser. You cannot pass this.pageFn directly inside evaluateHandle because only string representation of this.pageFn will be passed inside evaluateHandle. So the other state and properties related will not be passed. 


What u can do is pass whole class and make object from that class. This is not playwright limitation tho.

**Comment by pavelfeldman** [comment]
[exposeBinding](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=pageexposebindingname-playwrightbinding) might help here.

**Comment by phileba** [comment]
@pavelfeldman so you mean it will work
```
await page.exposeBinding('pageFn', () => this.pageFunc)
const handle = await page.evaluateHandle('() => window.pageFn', JSON.stringify(args))
```

**Comment by erwinheitzman** [comment]
I'm interested in this as well 👍

**Comment by phileba** [comment]
I can work around by this following
```
await page.evaluateHandle(
	mArgs => {
		const [fn, ...args] = mArgs
		return eval(fn)(...args)
	},
	[this.pageFunc.toString(), ...args]
)
```

**Comment by pavelfeldman** [comment]
@erwinheitzman @phileba 

[`page.exposeBinding`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=pageexposebindingname-playwrightbinding) places a function on the global object of your web page (`window`), and whenever you call it, it invokes the handler on the Node side. For example:

```js
const { chromium } = require('playwright');

(async () => {
  const browser = await chromium.launch({ headless: false });

  const page = await browser.newPage();
  // Expose function `myFunction` on window object
  await page.exposeBinding('myFunction', ({ page }, question) => {
    console.log('Web page is asking: ' + question);
    return 42;
  });

  // Load a simple page that calls this `handleClick`
  await page.setContent(`
    <script>
      async function onClick() {
        // Call into Node
        const result = await myFunction('What is the ...?');
        alert(result);
      }
    </script>
    <button onclick="onClick()">What is the ...?</button>
  `);
})();
```
