### ISSUE TITLE
[Feature] Scale viewport to fit on screen

### ISSUE THREAD

**Issue by celeryclub** [microsoft/playwright#2589]
Hey team. Got a question for you here about viewport scaling. Let's say I'm trying to test how a website behaves on a very large display. I can set a ridiculously large viewport in my config, but I won't be able to see it all if I'm running this headed. It appears that screenshots still work correctly in this scenario, but it's difficult to see what's going on as it's happening. Is there any way to scale the viewport down so that it's all visible on my (smallish) screen, while still having the website behave as if it's in a large viewport?

```js
const { chromium } = require('playwright-chromium');

(async () => {
  const browser = await chromium.launch({
    headless: false,
  });

  const context = await browser.newContext({
    viewport: {
      width: 5000,
      height: 2000,
    },
  });

  const page = await context.newPage();
  await page.goto('https://www.google.com/', { waitUntil: 'networkidle' });
  await page.screenshot({ path: 'google.png' });
  await browser.close();
})();
```

**Comment by pavelfeldman** [comment]
We can probably do that for Chromium, @dgozman implemented it specifically for DevTools' 'Fit in window' feature. But we lack it in other browsers and implementing it is... painful.

**Comment by celeryclub** [comment]
Understood. Even having it work for chromium would be great!

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
