### ISSUE TITLE
[BUG] Electron empty clipboard object from the evaluate function

### ISSUE THREAD

**Issue by atali** [microsoft/playwright#2598]
I got the following error when trying to access the writeText function from the clipboard object.

```
clipboardRef.writeText is not a function
```

My test is the following:
```
  describe('electron api', () => {

    it('should have a clipboard instance', async () => {

      const clipboardRef = await application.evaluate( async ({clipboard}) => clipboard);
      expect(clipboardRef).toBeTruthy();

      const clipboardContentToWrite = 'Hello from Playwright';
      clipboardRef.writeText(clipboardContentToWrite);
      const clipboardContentRead = await clipboardRef.readText();
      await expect(clipboardContentRead).toEqual(clipboardContentToWrite);
    });
  })
```
While debugging the object clipboardRef seems to be empty.
@pavelfeldman  Do you have any idea what is going wrong ?

**Comment by pavelfeldman** [comment]
Playwright test is running in a different environment from the actual electron page. That's why we have this `application.evaluate` indirection. In your snippet, you could have done the following:

```js
    // Get a handle on the clipboard object
    const clipboardRef = await application.evaluateHandle(async ({clipboard}) => clipboard);
    const clipboardContentToWrite = 'Hello from Playwright';
    // Evaluate on this handle to actually write text
    await clipboardRef.evaluate((clipboard, text) => clipboard.writeText(text), clipboardContentToWrite);
    // Evaluate on this handle to read clip
    const clipboardContentRead =
        await clipboardRef.evaluate(clipboard => clipboard.readText());
    await expect(clipboardContentRead).toEqual(clipboardContentToWrite);
```

but you don't really need it since {clipboard} is available in `application.evaluate`:

```js
    const clipboardContentToWrite = 'Hello from Playwright';
    await application.evaluate(async ({clipboard}, text) => clipboard.writeText(text), clipboardContentToWrite);
    const clipboardContentRead = await application.evaluate(async ({clipboard}) => clipboard.readText());
    await expect(clipboardContentRead).toEqual(clipboardContentToWrite);
```

**Comment by pavelfeldman** [comment]
Having said all that, I was thinking about a mode where the test would run _inside_ electron main process and would simply have `clipboard` available via requiring `electron`, as inside your app. I lack customers for the Electron testing to validate which approach would be preferred though, out-of-process that we have or in-process.

**Comment by atali** [comment]
It works very well ! thanks a lot for your help.

what will be the advantage of running the test in-process vs out-of-process ? 

We will be glad to test if you need some users feedback. I tried Spectron but it was flaky, I switched yesterday to playwright and I was amazed by how fast it runs and the stability .

I am still having another issue about running playwright in docker with headless mode , I am going to create a github issue .
