### ISSUE TITLE
[Feature] Browser.version()

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#2604]
Hello.
I would like to log browser version that is used for testing.
In puppeteer there was a function:
`browser.version()`
But I was not able to find similar func in Playwright.

Is there any other way to get browser version?

**Comment by mxschmitt** [comment]
A chromium specific way would be currently something like that. This is the same what Puppeteer was doing:
```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const session = await browser.newBrowserCDPSession();
  const version = await session.send('Browser.getVersion');
  console.log(version.product);
  // HeadlessChrome/85.0.4165.0
  await session.detach();
})();
```

Currently there is no way to get he browser versions for all of the browser except a User-Agent is enough for you:

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  // Try to add 'firefox' to the list ↓
  for (const browserType of ['chromium', 'webkit', 'firefox']) {
    /** @type {import('playwright').Browser} */
    const browser = await playwright[browserType].launch();
    const context = await browser.newContext();
    const page = await context.newPage();
    console.log(await page.evaluate(() => navigator.userAgent));
    await browser.close();
  }
})();
```

This would lead to that:

```
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/85.0.4165.0 Safari/537.36
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.2 Safari/605.1.15
Mozilla/5.0 (X11; Linux x86_64; rv:77.0) Gecko/20100101 Firefox/77.0
```

It would be nice to have the `browser.version()` function across all browsers.

**Comment by DJ-Glock** [comment]
@mxschmitt thanks a lot!

For my case it's enough. But it would be really nice to have browser.version) for all browsers.
Can this issue be transformed to Feature Request?

**Comment by amartyushov** [comment]
Team,  
Please correct me if I am wrong but   
- Google Chrome Protocol has such method [Browser.getVersion](https://chromedevtools.github.io/devtools-protocol/tot/Browser/#method-getVersion)  
- [Firefox remote debugging protocol](https://firefox-source-docs.mozilla.org/devtools/backend/protocol.html) does not have such method. [Search link](https://developer.mozilla.org/en-US/search?q=version)
- For Safari it is also challenging to find

**Comment by pavelfeldman** [comment]
@amartyushov : confirming for CDT, we don't use FF's RDP, confirming for WebKit remote protocol.
