### ISSUE TITLE
[Question] Passing parameters of different types to Page.evaluate function. TypeScript

### ISSUE THREAD

**Issue by DJ-Glock** [microsoft/playwright#2605]
**Context:**
- Playwright Version: playwright-chromium@1.1.1
- Operating System: Windows 10
- Node version: v12.16.2
- Extra: 
    {
    "@types/btoa": "^1.2.3",
    "@types/chai": "^4.2.11",
    "@types/chai-as-promised": "^7.1.0",
    "@types/dotenv": "^8.2.0",
    "@types/extract-zip": "^1.6.2",
    "@types/mocha": "^7.0.2",
    "@types/node-fetch": "^2.5.6",
    "@types/pixelmatch": "^5.1.0",
    "@types/pngjs": "^3.4.2",
    "@types/uuid": "^7.0.2",
    "@types/yargs": "^15.0.4",
    "allure-commandline": "^2.9.0",
    "btoa": "^1.2.1",
    "chai": "^4.2.0",
    "chai-as-promised": "^7.1.1",
    "csv-parser": "^2.3.2",
    "dotenv": "^8.2.0",
    "eslint": "^6.8.0",
    "eslint-plugin-no-null": "^1.0.2",
    "extract-zip": "^2.0.0",
    "lighthouse": "^5.2.0",
    "looks-same": "^7.2.1",
    "mocha": "^7.1.1",
    "mocha-allure-reporter": "^1.4.0",
    "mocha-parallel-tests": "^2.3.0",
    "mocha-teamcity-reporter": "^3.0.0",
    "node-fetch": "^2.6.0",
    "pixelmatch": "^5.2.0",
    "playwright-chromium": "^1.1.1",
    "pngjs": "^5.0.0",
    "prettier": "^2.0.5",
    "prettier-eslint": "^9.0.1",
    "start-server-and-test": "^1.11.0",
    **"ts-node": "^8.9.0",**
    "tslib": "^1.11.1",
    **"typescript": "^3.8.3",**
    "uuid": "^7.0.3",
    "yargs": "^15.3.1"
  }

I'm working on migration from Puppeteer to Playwright. My tests and supporting functions are written in TypeScript.

I faced the following issue with passing parameters of different types to page.evaluate function.
Issue can be reproduced with an example from playwright [documentation](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=pageevaluatepagefunction-arg). I just added if and changed formatting
```
const bodyHandle = await this.currentPage.$('body');
if (bodyHandle) {
  const html = await this.currentPage.evaluate(([body, suffix]) => body.innerHTML + suffix, [
   bodyHandle,
   'hello',
  ]);
  await bodyHandle.dispose();
};
```

There is an error: Property 'innerHTML' does not exist on type 'string | HTMLBodyElement':
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/26511191/84906131-318dbe80-b0ba-11ea-83a6-0ba06aabd735.png">

In the same time it looks fine when types of both variables are the same:
<img width="608" alt="image" src="https://user-images.githubusercontent.com/26511191/84906581-d01a1f80-b0ba-11ea-8a5d-c2390f74f433.png">

It looks like a bug. Critical for TypeScript :(

**Comment by pavelfeldman** [comment]
Answering from phone with a guess: putting args into array `[body, suffix]` made it array of element|string. Use object destructuring instead? `{ body, suffix }`?

**Comment by pavelfeldman** [comment]
Answering from phone with a guess: putting args into array `[body, suffix]` made it array of element|string. Use object destructuring instead? `{ body, suffix }`? Don't forget the call site as well.

**Comment by DJ-Glock** [comment]
@pavelfeldman 
Thanks a lot. It was my knowledge gap :(

Anyway it would be great if some TS examples can be added to documentation.
Corrected TS code:

```
    const bodyHandle = await this.currentPage.$('body');
    if (bodyHandle) {
      const html = await this.currentPage.evaluate(
        ({ body, suffix }) => body.innerHTML + suffix,

        { body: bodyHandle, suffix: 'hello' }
      );
      await bodyHandle.dispose();
    }
```
