### ISSUE TITLE
[BUG] Target crashed exception is thrown with event handler attached

### ISSUE THREAD

**Issue by pipi1007** [microsoft/playwright#2615]
**Context:**
- Playwright Version: 1.1.1
- Operating System: ubuntu:bionic
- Node version: 12.x
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

        page.on('crash', () => {
            logger.logError('page crashed');
        });

    process.on('unhandledRejection', (error) => {
        logger.logError('unhandled rejection:{0}', error);
    });

**Describe the bug**

When page crashes, I see the 'page crashed' error getting logged, but 'Target crashed' error is thrown from the promise which is caught by unhandledRejection handler. Below error is also logged: unhandled rejection:Error: Target crashed.

I expect no exception to be thrown when I have a handler to handle this event.

**Comment by pavelfeldman** [comment]
To make sure I understand, you call `await page.click()` that leads to a page crash. And in case there is a `crash` event handler, you don't want it to throw? That might be unexpected - click was not performed, we can't continue execution.

**Comment by pipi1007** [comment]
I open a page using Playwright. The page crashes few seconds after it is loaded. I want my code catch and report that crash and then close the browser. What I found is there is an exception thrown which leads to the unhandled rejection of the promise and my application exits before I am able to report the crash. Why is the exception thrown which requires me to catch and handle it, when I already setup a handler for the event.

**Comment by pavelfeldman** [comment]
Could you paste this unhandled exception here?

**Comment by pipi1007** [comment]
The error captured is Error: Target crashed. It is an error thrown from playwright code.

**Comment by pavelfeldman** [comment]
Oh, no stack - that's unfortunate. We throw this error only when the client attempts to do something with the page after it has crashed. I was hoping to see the stack pointing at the call site. In this case, it is unhandled, so someone is doing something to a closed page from an asynchronous event handler or something similar.

I can see you are a member of the Microsoft organization. Maybe you could get in touch with me locally so that I could help you debugging this use case.

**Comment by pipi1007** [comment]
I see, looks like a mistake on my side because I tried to do something with the page object after it crashed. Unfortunately the call stack wasn’t caught and the crash has stopped so it is hard to debug now. But with what you have said, I think I know how to avoid it. Just to clarify, what type of operations can cause the exception to throw? Can I call page.close()?

**Comment by dgozman** [comment]
Once the page has crashed, you are not supposed to call any methods on it, even `page.close()`. This is definitely not clear from the docs. Also, let me look whether we can make things a bit better.

**Comment by dgozman** [comment]
With improved documentation, I think there is nothing else to address here for now. Please comment/reopen if that's not the case.
