### ISSUE TITLE
[Feature]replay support in debug mode

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2619]
Through the cli we can records the actions，can will replay the script we recording？

**Comment by pavelfeldman** [comment]
The purpose of the recorder is to help user create rough scripts. It does not aim at a self-contained record/replay story. The expectations are that you copy and paste it into your script, adjust if necessary and then run it as a Node program.

**Comment by roughsoft** [comment]
OK，thank you！

**Comment by roughsoft** [comment]
@pavelfeldman ，the recorder can support iframe？

**Comment by pavelfeldman** [comment]
Yes, there is basic support for iframes there.
