### ISSUE TITLE
[Question] When running two or more browser instance for running test cases, all the test cases fails with in Docker 

### ISSUE THREAD

**Issue by raju-singh** [microsoft/playwright#2624]
When running two or more browser instance for running test cases, all the test cases fails with timeout error inside docker container

**Comment by mxschmitt** [comment]
Could you give us more insights into your environment? Which browser, Playwright version, testing setup and which Docker file would be really helpful. If possible, also a small reproducible in a repository.

I tried this one in the official Docker image, which works:

```js
// @ts-check
const playwright = require("playwright");

const createPages = async (browserType) => {
  /** @type {import('playwright').Browser} */
  const browser = await playwright[browserType].launch();
  const page1 = await browser.newPage();
  await page1.goto("https://try.playwright.tech")
  await page1.screenshot({ path: `example-${browserType}-1.png` });

  const page2 = await browser.newPage();
  await page2.goto("https://google.com")
  await page2.screenshot({ path: `example-${browserType}-2.png` });
  return browser
}

(async () => {
  for (const browserType of ['chromium', 'webkit', 'firefox']) {
    const browser1 = await createPages(browserType)
    const browser2 = await createPages(browserType)

    await browser1.close();
    await browser2.close();
  }
})();
```

[Here](https://try.playwright.tech/?s=utf80) also interactively (only multiple pages), which is based on the official [Docker image](https://github.com/microsoft/playwright/blob/02704e08c8aca3b9724e502b94f4c8d3b09a2b97/docs/docker/Dockerfile.bionic).
