### ISSUE TITLE
[Question]can I expose an angular component to playwright

### ISSUE THREAD

**Issue by vrknetha** [microsoft/playwright#2625]
I have a use case where I need a fetch a url from the element but it is not shown in the href but given the angular component on runtime. Is there a way to view that component as a window object in runtime?

**Comment by arjun27** [comment]
Thanks @vrknetha. You can run custom JS in the page context with Playwright: https://playwright.dev/#version=v1.1.1&path=docs%2Fcore-concepts.md&q=nodejs-and-browser-execution-contexts

The exact JS to execute will depend on your application and how the JS objects can be accessed. You could consider attaching a JS object to the `window` global (e.g., `window.component = component`) to access it inside a `page.evaluate` API call. Feel free to reopen if you have more questions!
