### ISSUE TITLE
[Question] --remote-debugging-pipe by default?

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2627]
From [code](https://github.com/microsoft/playwright/blob/c220fc7f46c6f2a921296a19c628d2309b065c07/src/server/chromium.ts#L93) it seems like if no debugging port is passed, then playwright launches with the flag `--remote-debugging-pipe` by default.

Is that the intended behavior? Also, what is the reason to use pipes vs websocket port? Any docs on that would be helpful.

**Comment by pavelfeldman** [comment]
Yes, this is intended behavior. Pipes don't require binding a port and can't be accessed from outside Playwright process.

**Comment by VikramTiwari** [comment]
That makes sense! 

@pavelfeldman I ran into an issue where if I click on the mic icon on google home page, then browser crashes. Should I open this as a new bug?

**Comment by pavelfeldman** [comment]
Absolutely!

**Comment by VikramTiwari** [comment]
Fantastic! Here's the bug: https://github.com/microsoft/playwright/issues/2647
