### ISSUE TITLE
[BUG] page.context().storageState() takes too long to accomplish

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#26315]
I am not sure if it is normal that the action takes almost half one minute:
### System info
- Playwright Version: v1.32.2
- Operating System: Windows 11
- Browser: Chrome
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.
```ts
const state = await page.context().storageState();
```

**Steps**
- [Run the test]
- [...]

**Expected**
It will complete within seconds

[Describe expected behavior]

**Actual**
From trace.zip:
<img width="571" alt="image" src="https://github.com/microsoft/playwright/assets/5887203/086e6005-4d72-499c-ac3f-de867466d5f5">
[Describe actual behavior]

**Comment by dgozman** [comment]
@stkevintan This sounds like a bug. However, we need more information to act. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
