### ISSUE TITLE
When using Playwright’s Java API to invoke the Firefox client, it works fine for the initial few executions. However, after multiple executions, the following error occurs:

### ISSUE THREAD

**Issue by stringutils** [microsoft/playwright#26319]
### System info
- Playwright Version: [v1.27.0]
- Operating System: Ubuntu 20]
- Browser: [Firefox]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
```
Map<String, String> mapEnv = new HashMap<>();
        mapEnv.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1");
        mapEnv.put("PLAYWRIGHT_BROWSERS_PATH", "/myPath");
        try (Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(mapEnv))) {
            Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(true).setSlowMo(1000L));
            BrowserContext context = browser.newContext();
            com.microsoft.playwright.Page page = context.newPage();
            page.setViewportSize(1680,1050);
            page.onResponse(item->{
                log.info("update-onResponse,url={},status={},statusText={}",item.url(),item.status(),item.statusText());
            });
            page.onRequest(item->{
                log.info("update-onRequest,url={},status={},responseStatus={}",item.url(),item.response().status(),item.response().statusText());
            });
            page.navigate("127.0.0.1:8080/test");
            log.info("success");
        }catch (Exception e) {
           e.printStackTrace();
        }
```

**Config file**

**Test file (self-contained)**

```js
Map<String, String> mapEnv = new HashMap<>();
        mapEnv.put("PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD","1");
        mapEnv.put("PLAYWRIGHT_BROWSERS_PATH", "/myPath");
        try (Playwright playwright = Playwright.create(new Playwright.CreateOptions().setEnv(mapEnv))) {
            Browser browser = playwright.firefox().launch(new BrowserType.LaunchOptions().setHeadless(true).setSlowMo(1000L));
            BrowserContext context = browser.newContext();
            com.microsoft.playwright.Page page = context.newPage();
            page.setViewportSize(1680,1050);
            page.onResponse(item->{
                log.info("update-onResponse,url={},status={},statusText={}",item.url(),item.status(),item.statusText());
            });
            page.onRequest(item->{
                log.info("update-onRequest,url={},status={},responseStatus={}",item.url(),item.response().status(),item.response().statusText());
            });
            page.navigate("127.0.0.1:8080/test");
            log.info("ok");
        }catch (Exception e) {
           e.printStackTrace();
        }
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]
success
**Actual**

[Describe actual behavior]
When using Playwright’s Java API to invoke the Firefox client, it works fine for the initial few executions. However, after multiple executions;What can be confirmed now is that the “[libnspr4.so](http://libnspr4.so/)” file exists and has executable permissions,the following error occurs:

![image](https://github.com/microsoft/playwright/assets/35484811/ecb93ab2-6fc1-43be-9393-df45ea19b2f1)

**Comment by dgozman** [comment]
@stringutils It looks like your Firefox installation is sometimes corrupted. It looks like you are downloading browser yourself, don't you? Perhaps you should double check that. Not sure how we can help in this case.

**Comment by stringutils** [comment]
> @stringutils It looks like your Firefox installation is sometimes corrupted. It looks like you are downloading browser yourself, don't you? Perhaps you should double check that. Not sure how we can help in this case.

because our server cannot connect to the internet, we need to download it in advance. and  the installed Playwright I use is  download by  Playwright’s automatic download mode to download this Firefox while being connected to the internet. Additionally, every time there is an issue, if I replace the problematic browser with a newly downloaded one, the error will not occur. But after using it for some time, the aforementioned error still appears. Does it have any relation to not executing context.close() and page.close() methods in my program?

**Comment by stringutils** [comment]
> > Does it have any relation to not executing context.close() and page.close() methods in my program?
> 
> Maybe you have to call `browser.close()` to prevent this? We haven't seen such an issue before, and it only reproduces for you, so try to experiment. It could be anything: corrupted HDD, another process removing this file, Firefox misbehaving, Playwright bug or anything inbetween.

The reason has not been identified yet. Currently, when this issue occurs, my solution is to re-download a new Firefox browser.

**Comment by mxschmitt** [comment]
I see that you are using a very old Playwright version, a lot has changed since then, a lot of bugs etc. have been fixed. I'd strongly recommend to upgrade, which might resolve it.

Nowadays there is also a way to access the specific browser download URL, so you have access to the matching firefox version for a specific playwright release: 

    mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --dry-run"

Also make sure to have all the operating system dependencies installed which explain missing libraries / object errors:

    mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"

**Comment by stringutils** [comment]
> I see that you are using a very old Playwright version, a lot has changed since then, a lot of bugs etc. have been fixed. I'd strongly recommend to upgrade, which might resolve it.
> 
> Nowadays there is also a way to access the specific browser download URL, so you have access to the matching firefox version for a specific playwright release:
> 
> ```
> mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --dry-run"
> ```
> 
> Also make sure to have all the operating system dependencies installed which explain missing libraries / object errors:
> 
> ```
> mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install --with-deps"
> ```

if i want to build an image with the required browser and libraries ,is there any completed exmples

**Comment by yury-s** [comment]
> Additionally, every time there is an issue, if I replace the problematic browser with a newly downloaded one, the error will not occur. But after using it for some time, the aforementioned error still appears. Does it have any relation to not executing context.close() and page.close() methods in my program?

Something is changing in your environment between the runs. Normally, it shouldn't matter if you called browser.close() before, the browser should start (as you are using ephemeral profile, nothing is persisted between the sessions). However, you may call browser.close() explicitly to ensure that firefox shuts down gracefully and doesn't break any of its internal files. From the description though, it sounds more like something is changing on the machine. Without a repro we cannot tell what it is.

> if i want to build an image with the required browser and libraries ,is there any completed exmples

If you are talking about docker image, you can download one that [we provide](https://playwright.dev/java/docs/docker). Here is the [source file](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy).

Closing this bug as we cannot act on it without a self-contained repro.
