### ISSUE TITLE
[Feature] Playwright support for Mariner Linux Distro aka Azure Linux

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright#26312]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Microsoft has open source linux distribution known as [Mariner](https://github.com/microsoft/CBL-Mariner) aka [Azure Linux](https://learn.microsoft.com/en-in/azure/azure-linux/intro-azure-linux), I tried to run playwright test but failed to install dependency required to run these tests. 
Do you think others might benefit from this as well?
Yes, its useful for all customers using AKS and other azure containers. 

Error I see when trying to run tests
`Host system is missing dependencies to run browsers.` - with list of libraries

**Comment by pavelfeldman** [comment]
Mariner does not seem suited as a base for the e2e or acceptance testing of the software that runs on the client machines, it is built for the cloud.

As per the description

'''
By focusing the features in the core image to just what is needed for our internal cloud customers there are fewer services to load, and fewer attack vectors.
'''

The 50Mb image would need to grow to 2Gb to support the user scenarios of Playwright, which goes agains the whole idea of Mariner.
