### ISSUE TITLE
[Feature] Allow to pass multiple projects to --project cli flag

### ISSUE THREAD

**Issue by Xotabu4** [microsoft/playwright#26325]
I have multiple projects defined in playwright config file, and i want some of them to be groupped within one run, so there will be single HTML report generated for 3 projects out of my total of 7.

Currently --project accepts only 1 project. Would be nice to have possibility to specify multiple projects e.g. `--project=functional,group-calls,browser-lang-codes`

**Comment by dgozman** [comment]
@Xotabu4 You can pass `--project` multiple times:
```sh
npx playwright test --project=functional --project=group-calls
```

**Comment by MindaugasMateika** [comment]
it does accept multiple projects within a single `--project` flag as well,

```
npx playwright test --project functional group-calls
```

**Comment by Xotabu4** [comment]
Wow, i had to try before creating!
