### ISSUE TITLE
[Feature] Can we have a good example showing how to work with the Electron menu.

### ISSUE THREAD

**Issue by patgiass** [microsoft/playwright#2632]
Hi.
I'm giving a try to PlayWright to drive my Electron application in my E2E tests.
I'm trying hard to find a way to handle the menu of my Electron application to open what should be a configuration popup window. But actually I can't manage to access and click the menu item to eventually access the configuration dialog window this menu is opening.

I've try something like this...
```
    it('should have access to the menu', async () => {
      await appElectron.evaluate( async ({Menu}) => {
        const menu = Menu.getApplicationMenu();
        console.log('menu items count:', menu.items.length);
        const configMenu = menu.items[6].click();
        configMenu.click();
        const userConfigMenu = configMenu.getMenuItemById('User Config');
        userConfigMenu.click();
      });

      const popup = await appElectron.evaluateHandle((async ({BrowserWindow}) => {
        return BrowserWindow.getFocusedWindow();
      }));

      const title = await popup.evaluateHandle((configPopup) => {
        return configPopup.getTitle();
      });
      console.log('Popup title:', title);
      expect(title).toBeTruthy();
    });
```
... but this doesn't work.

**Comment by pavelfeldman** [comment]
I don't think Electron allows showing menus programmatically. There are some hints that could be relevant here though: https://github.com/electron-userland/spectron/issues/21#issuecomment-373982282

**Comment by pavelfeldman** [comment]
Let me actually bake it into Playwright - it looks useful...

**Comment by atali** [comment]
I was able to achieve by doing the following :

```
            id: 'File',
            label: 'File',
            submenu: [
                {
                    id: 'Save',
                    label: 'Save',
                    click: () => {
                        this.Save();
                    }
                },
```
The test file:
```
        await app.evaluate(async ({app, Menu}) => {
            const fileMenuItem = app.applicationMenu.getMenuItemById('File');
            const saveMenuItem = fileMenuItem.submenu.getMenuItemById('Save');

            saveMenuItem.click()
        });
```

**Comment by Himani33** [comment]
@atali Thanks your example helped me to implement Electron app Menu tests by using playwright. Thanks!
Another question Do you know how to open Devtool in Electron.launch() method?

**Comment by Nokel81** [comment]
Any update on this, I tried what @atali wrote (and even tried the `evaluteHandle` from @pavelfeldman 's PR but I couldn't get the menu action to actually run. (It is supposed to trigger a navigation).

**Comment by udondan** [comment]
@Nokel81 I just tested @atali's example and it works. Make sure your menu items really have IDs. These are not the labels.

**Comment by Nokel81** [comment]
@udondan Thanks, yes I got it to work too. I still would like https://github.com/microsoft/playwright/issues/8004 so that I could use the Menu's accelerators as part of the test workflow but this works for the time being.

**Comment by udondan** [comment]
Thanks for pointing me to that issue. I was trying to add a test for a menu accelerator for quite some time.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

We are prioritizing the features based on the upvotes, recency and activity in the issue thread. It looks like this issue only has a handful of upvotes, has not been touched recently and/or we lack sufficient feedback to act on it. We are closing issues like this one to keep our bug database maintainable. Please feel free to open a new issue and link this one to it if you think this is a mistake.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
