### ISSUE TITLE
[BUG] Playwright runs all the tests files if the file you  run (test1.spec.js) have same name at last in some other file at end  ( *****test1.spec.js )

### ISSUE THREAD

**Issue by sumitgithub007** [microsoft/playwright#26320]
### System info
- Playwright Version: [1.36.2]
- Operating System: [All, Windows 10]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

 https://github.com/sumitgithub007/PlaywrightBug.git

or

**// @ts-check
const { defineConfig, devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  timeout:30*100000,  
  
  expect: {
    timeout:5000

  },
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  //forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  //retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
 // workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { headless:false,...devices['Desktop Chrome'] },
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[ In the github repo I have two files ABC.spec.js and C.spec.js
When I run npx playwright test C.spec.js only that particular file should run ]
**Actual**
[When I run cmd: npx playwright test C.spec.js ,it runs both files ABC.spec.js(**not expecting it to run**)  and C.spec.js ]
I checked it only happens when C is at last in ABC file,its working fine if File name  is CAB.spec.js or ACB.spec.js 
  
![image](https://github.com/microsoft/playwright/assets/66677424/a46ecd02-86c9-429b-8e98-344eaa107fdc)

![image](https://github.com/microsoft/playwright/assets/66677424/aa6286a2-059d-4aad-a363-fadefc7588e4)

**Comment by dgozman** [comment]
@sumitgithub007 That's because running `npx playwright test C.spec.js` runs all test files that have `C.spec.js` as a substring, which includes `ABC.spec.js`. You can be more precise by either using regular expression or a prefix:
```sh
npx playwright test "tests\C.spec.js"
```

**Comment by sumitgithub007** [comment]
[dgozman](https://github.com/dgozman)  Thanks I edited it

**Comment by sumitgithub007** [comment]
[dgozman](https://github.com/dgozman)  Hi Have you tried running is it a feature or bug >?? or fixed

**Comment by dgozman** [comment]
@sumitgithub007 It is a feature, working as expected.
