### ISSUE TITLE
[Feature/Question?] One worker when running test with same authenticated user

### ISSUE THREAD

**Issue by bshostak** [microsoft/playwright#26330]
Scenario:

I'm running a test that fills out an address form for a logged in user that I setup via the global-setup. The problem is that when this test runs it passes fine in Chrome but in Firefox and Safari it fails because it's "stepping on toes" sine they are all running in parallel with each other. For example, Chrome is clicking save on the address form and at the same time Firefox is trying to save but because Chrome has already saved it "faster' than Firefox, Firefox fails because the address is already there.

To get this to work i have to limit test runs to Chrome only. Can we get a feature, or does playwright have a feature/solution already that can limit certain spec files to a single worker so that it runs serially through each browser to avoid "stepping on toes". 

Thank you

**Comment by dgozman** [comment]
@bshostak Your scenario is clear, folding into #14084. The workaround today is to put such tests into a separate project, and not run that project in parallel on multiple browsers.
