### ISSUE TITLE
[BUG] login page username and password field are empty after filling.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26331]
### System info
- Playwright Version: 1.36.2
- Operating System: Mac
- Browser: All
- Other info:

### Source code

```javascript
        const page = actor.states('page');
        await actor.attemptsTo(Navigate.to(this.url));
        await page.waitForTimeout(1000);  ---> tried waiting, didn't help
        console.log("Login page")
        await page.locator('#username').click();
        await page.locator('#username').fill(actor.states('username'));
        await page.locator('#password').click();
        await page.locator('#password').fill(actor.states('password'));
        console.log("Done entering credentials")
        await actor.attemptsTo(Click.on().textName('Submit'));  
        console.log("hit submit") ---> it prints in the console, so looks like it clicked on submit button, but i still see login page with blank username and password.
```

In the login page, looks like after entering username and password , and hit login page,it works sometimes, and sometimes, apparently after entering username and password, i don't see username and password that are entered using locator.fill() , it looks like it hit submit, but nothing happened, it still shows login page with blank username and password field.  not sure whats causing it?

<img width="615" alt="Screen Shot 2023-08-07 at 5 23 19 PM" src="https://github.com/microsoft/playwright/assets/113629123/fd72c6d3-e30f-43ec-a030-72b9c997be9a">

**Can you please confirm if it is related to hydration issue or any other rootcause?**
the article explains the fix ----> 
**The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional.** 
Can you please confirm what it means by disabling interactive controls until after the hydration? is this something the developer should handle in the application or should be fixed in the playwright test to disable interactive controls by page.waitforTimeout() or something? can you please confirm?

Mainly login page 

Hi,  https://playwright.dev/docs/navigations#hydration , dropdown click is not working, and it doesn't load the filtered row after a value is selected in the dropdown.

can you please tell me how i can fix the hydration issue in the playwright test. As per the article. it says. The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional. Does it mean the developers have to make the fix in the app or is there anything that can be done to disable interactive controls until page becomes functional? can you please clarify?
Hydration
[At some point in time, you’ll stumble upon a use case where Playwright performs an action, but nothing seemingly happens. Or you enter some text into the input field and will disappear. The most probable reason behind that is a poor page ](https://playwright.dev/docs/navigations#hydration)[hydration](https://en.wikipedia.org/wiki/Hydration_(web_development)).
When page is hydrated, first, a static version of the page is sent to the browser. Then the dynamic part is sent and the page becomes “live”. As a very fast user, Playwright will start interacting with the page the moment it sees it. And if the button on a page is enabled, but the listeners have not yet been added, Playwright will do its job, but the click won’t have any effect.
A simple way to verify if your page suffers from a poor hydration is to open Chrome DevTools, pick “Slow 3G” network emulation in the Network panel and reload the page. Once you see the element of interest, interact with it. You’ll see that the button clicks will be ignored and the entered text will be reset by the subsequent page load code. The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional. (edited)

**Comment by dgozman** [comment]
@InduKrish This does indeed look like a hydration issue. The proper fix would be not in Playwright tests, but rather in the application.

You can probably work around this in a test, by waiting for some signal, e.g. a network response, but we cannot recommend anything generic that would work for all cases.

**Comment by angelo-loria** [comment]
@InduKrish have you tried using `type` with a delay option specified instead of `fill`? this would slow down the input, which has helped me in situations like this 

https://playwright.dev/docs/api/class-locator#locator-type

**Comment by dgozman** [comment]
There does not seems to be any action item for Playwright here. If you still think there is a bug in Playwright, please file a new issue with a self-contained repro by filling in the "Bug Report" template.
