### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by starlordgit007** [microsoft/playwright#26339]
### System info
- Playwright Version: [v1.36.0]
- Operating System: [Windows, WSL]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

        BrowserTypeLaunchOptions lobjBrowserLaunchOptions = new BrowserTypeLaunchOptions()
        {
            Channel = "chromium",
            Headless = true,
        };
        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Chromium.LaunchAsync(lobjBrowserLaunchOptions);
        await using var context = await browser.NewContextAsync();

        var page = await context.NewPageAsync();
        await page.GotoAsync("https://playwright.dev/dotnet");
        await page.ScreenshotAsync(new() { Path = "screenshotsdfsafsdfssfd1.png" });

After launching project using WSL I am getting below error :
**Microsoft.Playwright.PlaywrightException: 'Navigation failed because page crashed!**

**Comment by starlordgit007** [comment]
Thanks for quick response.

I was able to solve the issue by upgrading to WSL2 version.
**wsl --set-version Ubuntu-22.04  2**

Thank You!

**Comment by Ganesh1174** [comment]
Before this Bug appears, the test failed with the below error.

![image](https://github.com/microsoft/playwright/assets/133853877/aff4555d-9b7e-4ad7-9652-aee668a3132b)

**Comment by seemab-yamin** [comment]
Thanks, [starlordgit007](https://github.com/starlordgit007). It helped 💯
