### ISSUE TITLE
[BUG] Test Results tab in VS Code keep popping up even if closed after each test run

### ISSUE THREAD

**Issue by maxsudik** [microsoft/playwright#26338]
**Context:**
- Playwright Version:1.36.2
- Operating System: Mac
- Node.js version: v20.4.0
- Visual Studio Code version: Version: 1.81.0
Commit: 6445d93c81ebe42c4cbd7a60712e0b17d9463e97
Date: 2023-08-02T12:38:28.722Z
Electron: 22.3.18
ElectronBuildId: 22689846
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Darwin arm64 22.6.0
- Playwright for VSCode extension version: v1.0.15

When running a test - the tab with Test Results always pops-up.
This started happening with recent VS Code update. No matter what I do - it keeps popping-up. Before it was never showed up if not on demand.
![image](https://github.com/microsoft/playwright/assets/40281293/7fcd439f-c1c7-43ed-947b-22ec167379a4)

**Comment by mxschmitt** [comment]
Sounds like a change in VSCode rather than a change in the Playwright extension. I recommend filing it against https://github.com/microsoft/vscode.

**Comment by maxsudik** [comment]
https://github.com/microsoft/vscode/issues/189943

**Comment by dgozman** [comment]
Closing in favor of VSCode issue.
