### ISSUE TITLE
[Feature] Playwright should save file with name and extension while downloading file

### ISSUE THREAD

**Issue by rphacker1618** [microsoft/playwright#26341]
As of now when we automate download functionality scenario, then file is getting save with some GUID number without any extension. So as a result if we wanted to verify the content of downloaded file we can't do it . 

We have also tried implementing steps giving under  url https://playwright.dev/docs/downloads recommended by many post , but with no success 

There are many open issue for this bug few on them I am listing #24048 #18139. 

Adding this feature will be beneficial for download functionality scenario and verifying its content.

Let me know if you needed more input

**Comment by dgozman** [comment]
We should improve documentation to explain this scenario.

**Comment by rphacker1618** [comment]
@dgozman please let me know what all points are needed , so that I can post it here
