### ISSUE TITLE
[BUG] Playwright enters password in the username field during login

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26349]
System info
Playwright Version: 1.36.2
Operating System: All
Browser: [All, Chromium, Firefox, WebKit]

Other info:
Sometimes, when UI is launched, instead of typing password in the password text field, playwright is typing password in the username field and login fails, intermittent issue, Can you please advise?

```javascript
await page.goto('url')
await page.locator('#username').fill("g3434);
await page.locator('##password').fill("password");
```
locator.fill() and locator.type() - both intermittently fills password in the username field.  Can you please confirm if it is the issue in the playwright test or the issue in the application?

Also please advise if i have to add wait for timeout as a workaround, or any other wait other than wait for timeout as a workaround?
```javascript
        await page.goTo(url));
        await page.waitForTimeout(2000);
        await page.locator('#username').fill(actor.states('username'));
        await page.waitForTimeout(2000);
        await page.locator('#password').fill(actor.states('password'));
        await actor.attemptsTo(Click.on().textName('Submit'));
```

<img width="862" alt="Screen Shot 2023-08-08 at 9 52 50 AM" src="https://github.com/microsoft/playwright/assets/113629123/cd1a6157-9981-448d-b933-ea5ef52ef04e">

**Comment by dgozman** [comment]
> locator.fill() and locator.type() - both intermittently fills password in the username field. Can you please confirm if it is the issue in the playwright test or the issue in the application?

Unfortunately, we do not know. Since you did not share a repro with us, we cannot check it ourselves. I'd recommend to share a repro we can run locally, otherwise it's unlikely we'll be able to help.

Usually, the issue is somewhere in the test or the web page, but occasionally there are bugs in Playwright as well. Perhaps this is a symptom of a [hydration flakiness](https://playwright.dev/docs/navigations#hydration)?

> Also please advise if i have to add wait for timeout as a workaround, or any other wait other than wait for timeout as a workaround?

Waiting for timeout is rarely the right solution.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
