### ISSUE TITLE
[BUG] Trace viewer https://trace.playwright.dev not loading hosted files

### ISSUE THREAD

**Issue by taaha** [microsoft/playwright#26345]
### System info
- Playwright Version: [v1.36.0]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info:

**Steps**
I have a trace file trace.zip served on my local server http://192.168.10.4:80

I cant access it by going to following address in the browser
https://trace.playwright.dev/?trace=http://192.168.10.4:80/trace.zip

**Comment by MindaugasMateika** [comment]
Is cors header for your local sever set to `Access-Control-Allow-Origin: https://trace.playwright.dev`?

**Comment by taaha** [comment]
yes that was the solution. Thankyou so much you have saved me hours of searching
