### ISSUE TITLE
[BUG] Javascript Click Event handler is not triggered when Playwright click is made

### ISSUE THREAD

**Issue by vaibhavrmore1** [microsoft/playwright#26340]
### System info
- Playwright Version: v1.36
- Operating System:  Windows 11
- Browser: Chromium
- Other info: Python

### Source code

I provided the exact source code that allows reproducing the issue locally.

**This is a workaround code as not able to find documentation in Playwight to capture all Click (Or even Fill) events directly.**
Suggest if any other solution is available as well.

```python
    import asyncio
    import time
    from playwright.async_api import async_playwright  
    async def main():
        playwright = await async_playwright().start()
        browser = await playwright.chromium.launch(headless=False)
        page = await browser.new_page(viewport={"width": 1880, "height": 900})
        client = await page.context.new_cdp_session(page)
        print("successfully opened browser")
        url = 'https://www.cricbuzz.com/'
        await page.goto(url=url if "://" in url else "http://" + url)
        time.sleep(3)
        ### Code goes here ###
        js = """
        clickEvent = null;
        console.log("Adding Click handler")
        window.addEventListener('click', (e) => { 
            console.log("Click handler called "+e.clientX+"||"+e.clientY); 
            console.log(e); 
            clickEvent=e;});
        let startTime = new Date();
        while(clickEvent==null){
            let endTime = new Date();
            if(endTime - startTime>10000)
            break;
        };
        """
        window_handle = page.evaluate_handle(js)
        await page.mouse.click(100, 100)
    
        clickCompleted = await window_handle
    
        clickEventObjectDirect = await page.evaluate("clickEvent")
        print(clickEventObjectDirect)
        clickEventObject = page.evaluate_handle("clickEvent")
        clickEventObjectTemp = await clickEventObject
        clickEventObjectJSON = await clickEventObjectTemp.json_value()
        print(clickEventObjectJSON)
    
        print("Waiting")
    
    
    if __name__ == '__main__':
        asyncio.run(main())
```

**Steps**
- Run the test

**Expected**

The playwright page mouse click event should have been triggered and should have been handled by the event handler added.
Which sets clickEvent variable to the actual event value.

**Actual**

When the playwright mouse page click is made, it doesn't call the JS event handler added. It should have triggered the click event.

**Comment by dgozman** [comment]
@vaibhavrmore1 Your snippet is very much timing-related. I suspect there is some asynchronous change on the page that might invalidate window listeners.

Removing the following block prints "5" in the line `print(clickEventObjectDirect)`:

```
let startTime = new Date();
        while(clickEvent==null){
            let endTime = new Date();
            if(endTime - startTime>10000)
            break;
        };
```

Adding `await page.wait_for_timeout(3000)` before `page.evaluate_handle(js)` makes it work 100% of the time for me.

Overall, this does not seem to be a Playwright issue - it's just the page is very dynamic.

**Comment by vaibhavrmore1** [comment]
The code provided was work around tried to capture Click event triggered through Playwright and while loop was used for timeout.
Objective is to capture the click performed on any element in a page and check click point(X,Y) falls in bounding box of the desired element. (Direct element click can not be used as click could be performed on any element overlapping with same element). If this is possible through Playwright, workaround is not required.

**Comment by dgozman** [comment]
> Objective is to capture the click performed on any element in a page and check click point(X,Y) falls in bounding box of the desired element

That's definitely possible. I'd recommend [`page.expose_binding`](https://playwright.dev/python/docs/api/class-page#page-expose-binding) that would notify your Playwright script about events, and then `page.evaluate()` something like your snippet:

```py
def on_event(x, y):
    print(x, y)

await page.expose_function("on_event", on_event)

await page.evaluate("""
  window.addEventListener('click', e => window.on_event(e.clientX, e.clientY));
""")

await page.goto(...)
# click here
```

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions.
