### ISSUE TITLE
[BUG]: Unable to Locate the `<summary />` Element by Its Implicit `button` Role

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/playwright#26354]
### System info
- Playwright Version: `@playwright/test@1.36.2`,
- Operating System:  MacOS 12.6
- Browser: Chromium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

#### Config File

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
	projects: [
		{
			name: 'chromium',
			use: { ...devices['Desktop Chrome'] },
		},
	],
})
```

#### Test File
```ts
test.describe('Accessible Elements', () => {
	test('Finding `summary` Button', async ({ page }) => {
		await page.goto('PATH_TO_HTML_FILE_BELOW')
		const list = page.getByRole('list', { name: /my-list/i })
		expect(await list.count()).toBe(1)

		const button = page.getByRole('button', { name: /expander/i })
		expect(await button.count()).toBe(1)

		const summary = page.getByRole('button', { name: /summary/i })
		expect(await summary.count()).toBe(1) // Fails Here
	})
})
```

#### Test Page

```html
<!-- Basic Markup for Reproducing Bug -->
<!DOCTYPE html>
<html>
	<head>
		<title>This is a raw HTML File</title>
	</head>

	<body>
		<ul aria-label="my-list">
			<li>1</li>
			<li>2</li>
			<li>3</li>
		</ul>

		<button>
			<h1>My Element <span>Expander</span></h1>
		</button>

		<details>
			<summary>Summary</summary>
			Some Details
		</details>
	</body>
</html>
```

### Steps
- Create a [details](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) element in any browser environemnt
- Look for the [summary](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary) element via the `button` role.
- Discover that the `summary` element is not discoverable. :sob:

These steps are executed in the test file above.

### Expected Behavior

According to the [summary element specifications](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#technical_summary), the element should be discoverable under the `button` role.

### Actual

`Locator.getByRole()` is not able to find `summary` elements by the `button` role.

**Comment by ITenthusiasm** [comment]
I accidentally hit `CMD + Enter`. :confused: Still editing this.

**Comment by dgozman** [comment]
According to the spec https://w3c.github.io/html-aam/#html-element-role-mappings, section `summary`:

```
[wai-aria-1.2]
  No corresponding role

Computed Role
  If the element is the first child of its type within a parent details element: html-summary
  Otherwise, if it is not the first child of its type of a parent details element, or it is not a child of a details element: generic role
```

That said, there is no `summary` or `html-summary` role in the list of roles: https://w3c.github.io/aria/#role_definitions, nor in the role mapping list: https://w3c.github.io/core-aam/#mapping_role.

Browsers also think differently:
- Chromium: `DisclosureTriangle`
- Firefox: `summary`
- Safari: no role

**Comment by ITenthusiasm** [comment]
Interesting. MDN is usually right, but I guess their information was a little off this time. According to https://w3c.github.io/html-aria/#el-summary, it seems that there are user agents that expose `summary` as a `button`, but not all of them necessarily do that. The Testing Library Family currently defaults to `button` for `summary`s as well.

Is there a recommended approach for `summary` elements, then? The point of the `getByRole` selector is to help developers make sure their application is accessible. To that extent, searching for a `summary` by a CSS selector is not as reliable -- especially if you're trying to get something by its accessible name.

**Comment by dgozman** [comment]
@ITenthusiasm Perhaps it makes sense to expose `summary` as a `button`. We'll see in time for 1.38 release.

**Comment by ITenthusiasm** [comment]
@dgozman Sounds good! Thanks for considering!

**Comment by ITenthusiasm** [comment]
Minor update/correction. It seems that the Testing Library Family doesn't currently expose a role for the `summary` element -- though it may just be that this hasn't been brought to their attention yet. I'll ask. (What I thought was the `summary` element earlier was a `<button />` belonging to some Accordion component.)

However, it still holds that many user agents use `button` for `summary`s, as the earlier link mentions. And we'll still need an accessible way to access `<summary />` elements at some point. But in case that piece of information changes things, I figured it was worth mentioning.

**Comment by dgozman** [comment]
@ITenthusiasm 

> It seems that the Testing Library Family doesn't currently expose a role for the summary element -- though it may just be that this hasn't been brought to their attention yet. I'll ask.

Did you have a chance to raise this issue with Testing Library?

> However, it still holds that many user agents use `button` for `summary`s, as the earlier link mentions.

Well, even though the link claims this, my manual checks in three browser engines show that none of them does that. So I'd like to be careful instead of inventing our own ideas about the accessible role of `summary` elements.

I hope that `getByText()` works for now, even if that's not always ideal.

**Comment by ITenthusiasm** [comment]
For Reference: testing-library/dom-testing-library#1252

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
