### ISSUE TITLE
[BUG] Extract text from first result retrieved from "or" locator

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright#26361]
Originally posted [on StackOverflow](https://stackoverflow.com/q/76860260/9971404) without resolution. I think this is either a bug or **very surprising behaviour** which should be fully documented.

### System info
- Playwright Version: 1.36.0
- Operating System: ubuntu 22
- Browser: chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

I can have one of two html structures, and I won't know which one beforehand.

Either:
```html
<p class="foo">
	hello
</p>
```

Or
```html
<p class="foo">
	<span class="bar">hello</span>
	<span class="baz">world</span>
</p>
```

I want the `"hello"` text (which is dynamic, so I can't search for that specific example).

I use the "or" locator:
```cs
await page.Locator(".foo >.bar").Or(page.Locator(".foo")).First.InnerTextAsync()
```

**Expected**
Assuming the first html structure exists: everything works.

Assuming the second html structure exists: since I'm specifying `First`, my expectation is that it would return `"hello"`, but it actually returns `"hello\nworld"`.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
