### ISSUE TITLE
[Question] - snapshot diff does not return difference for scrollbar

### ISSUE THREAD

**Issue by ChrystianC** [microsoft/playwright#26373]
When taking headless browser screenshots, our team chooses to include scrollbars. This is because we have had bugs in the past where components renders not intentionally 
We occurred an error or intentional action, does playwright snapshot comparison not see scrollbar length difference. Mentioned difference
![image](https://github.com/microsoft/playwright/assets/91797794/30780571-35cf-4e31-841f-707306762f53)
Snapshot diff returns no pixels are different 
![image](https://github.com/microsoft/playwright/assets/91797794/9b2658c8-d9ca-4de0-9920-e76b8cac4bec)
playwright configuration
![image](https://github.com/microsoft/playwright/assets/91797794/be3bcc23-2432-4c65-8a5f-1be0fb360d0f)
![image](https://github.com/microsoft/playwright/assets/91797794/e23a2e96-0fe2-4da3-8b7b-445e7646023f)

In puppeteer snapshot comparison returns difference scrollbar lengths
![image](https://github.com/microsoft/playwright/assets/91797794/6a818ab5-8bcd-4806-bc47-2e8009b3c3ff)
puppeteer config
![image](https://github.com/microsoft/playwright/assets/91797794/8f077aeb-93c4-4bb0-9559-e873a90e8dae)

**Comment by dgozman** [comment]
@aslushnikov Could this be a comparator thinking scrollbar is an antialiasing artifact?

**Comment by aslushnikov** [comment]
@ChrystianC could you please these images (the one with longer scroll bar and the other one with a shorter one) separately?

**Comment by ChrystianC** [comment]
Shorter one
![items croped shorted](https://github.com/microsoft/playwright/assets/91797794/5f836d1a-b9e0-48e0-a572-1a899f1bda0a)
Longer one
![items croped](https://github.com/microsoft/playwright/assets/91797794/878bd1cd-feaa-48d9-84cd-f743dbd7ea07)

**Comment by ChrystianC** [comment]
I find solvation for this issue Decrease in acceptable perceived color difference by add option `{threshold: 0.1}`
