### ISSUE TITLE
[BUG] storageState cannot be disabled using test.use()

### ISSUE THREAD

**Issue by JonahKK** [microsoft/playwright#26374]
### System info
- Playwright Version: [v1.35.1]
- Operating System: macOS 13.4.1
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], storageState: 'auth.json'},
    },
});
```

**Test file (self-contained)**

```js
test.use({ storageState: undefined });

it('should not use storage state', async ({ page }) => {
  page.goto();
  ...
});
```

**Steps**
- Run the test
- See if user was authorised.

**Expected**

Since storageState was set to `undefined` it should not be logged in.

**Actual**

User is logged in the test. As a workaround I have to point to empty json in `test.use()`

**Comment by dgozman** [comment]
This is a known issue, see https://github.com/microsoft/playwright/issues/17396#issuecomment-1251691951 for a workaround. Sorry for the inconvenience!

**Comment by dgozman** [comment]
@JonahKK Great idea! Which guide have you read before creating the issue? Asking because there are many many places where we can put this information.

**Comment by JonahKK** [comment]
I started with [Auth](https://playwright.dev/docs/auth) and when I’ve experienced issues I looked at [StorageState](https://playwright.dev/docs/api/class-testoptions#test-options-storage-state)
