### ISSUE TITLE
[BUG] playwright crashes when run with NodeJS 16

### ISSUE THREAD

**Issue by barbogast** [microsoft/playwright#26371]
**Edit by maintainers**

You can fix this by upgrading to latest Node.js 16.x which contains a critical bugfix. Upgrading to more recent 18.X will work as well.

---

### System info
- Playwright Version: 1.36.2
- Operating System: macOS 13.4.1 (c)
- Browser: All
- Other info: NodeJS 16

Playwright crashes when used with NodeJS 16 (see also https://github.com/microsoft/playwright/discussions/26314):

```
$ npx playwright test --ui
/Users/naresh.bhatia/projects/vite-demo/node_modules/@playwright/test/lib/transform/esmLoader.js:70
  transport = new _portTransport.PortTransport(context.port, async (method, params) => {
                                                       ^

TypeError: Cannot read properties of undefined (reading 'port')
    at globalPreload (/Users/naresh.bhatia/projects/vite-demo/node_modules/@playwright/test/lib/transform/esmLoader.js:70:56)
    at ESMLoader.preload (node:internal/modules/esm/loader:362:48)
    at ESMLoader.addCustomLoaders (node:internal/modules/esm/loader:194:10)
    at initializeLoader (node:internal/process/esm_loader:82:19)
    at loadESM (node:internal/process/esm_loader:87:5)
    at handleMainPromise (node:internal/modules/run_main:65:12)
```

Upgrading to NodeJS 18 fixes the issue. Is NodeJS 16 still supported?

**Comment by barbogast** [comment]
Right now I'm not able to reproduce the issue with a clean install. I'm still trying to figure out why... 

Meanwhile, I've managed to reproduce the issue in the project I'm working on by using node@16.13.2. If I use node@16.14.2 or later the issue is gone.

Also I'm using yarn 3.6.0.

I'll continue to investigate after lunch.

**Comment by mxschmitt** [comment]
Thank you for your investigation.

We unfortunately only support the latest 16.X release, so we strongly suggest upgrading to 16.20.1 (which is latest as of today).

**Comment by barbogast** [comment]
Makes sense. Would it make sense to reflect that in [package.json](https://github.com/microsoft/playwright/blob/main/package.json#L9)? Right now it requires version `16`, which mislead me to think that all 16.x versions are supported.

**Comment by mxschmitt** [comment]
Node.js 16 is EOL, we recommend 20.

**Comment by nechiforc** [comment]
nvm set the default node version 20
