### ISSUE TITLE
[Feature] Record video with steps (for better CI debugging)

### ISSUE THREAD

**Issue by yang** [microsoft/playwright#26396]
One nice thing about Cypress is that it always shows the steps being executed, even when running in CI, so recorded videos show exactly what's happening and where it's failing.

Is there a similar way to record a video that also captures the steps in Playwright? I know Playwright UI and the inspector support showing the currently executed step, but that's a separate window from what's recorded AFAICT.

Thank you!

**Comment by dgozman** [comment]
@yang There is no such feature, and it's unlikely it will be implemented in the future. We recommend to [record a trace](https://playwright.dev/docs/trace-viewer-intro) instead of a video. It gives you steps, snapshots and so much more.

**Comment by mxschmitt** [comment]
Closing as per above.
