### ISSUE TITLE
Incognito Browser behaves differently between Playwright and Windows Machine

### ISSUE THREAD

**Issue by christophMW** [microsoft/playwright#26398]
I am facing the exactly same problems like described in issue https://github.com/microsoft/playwright/issues/9068

Also I found a lot of other Issues dealing with the same challenge.  Some found a solution like using chromium or setting the whitelist but they don't work out for me.
https://github.com/microsoft/playwright/issues/22060
https://github.com/microsoft/playwright/issues/15367
https://github.com/microsoft/playwright/issues/10824
https://github.com/microsoft/playwright/issues/20036

Also on your Discord Server People are facing this issue (https://discord.com/channels/807756831384403968/1137749836435828778)

Do you have any information that could help us? Unfortunately, I can't provide you with the source code or screenshots of the application for privacy reasons. I still hope that you have some ideas.

**Comment by dgozman** [comment]
@christophMW We need a self-contained repro to be able to help with this and similar issues, and so far we unfortunantely haven't got one. If you could share something with us, that would be helpful. Otherwise this issue is not actionable, and I'll have to merge it into #9068 and close.

> Do you have any information that could help us?

Not really. We have to understand the problem before recommending a solution.

**Comment by christophMW** [comment]
@dgozman Due to security reasons I can't share the repository and SUT (it is the system of a customer). What I can offer you is a web meeting where I can show you this behavior if that would help you. What do you think?

**Comment by dgozman** [comment]
> What I can offer you is a web meeting where I can show you this behavior if that would help you.

Thank you, but that's not really effective, so we don't do that.

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file if you have a self-contained example.

**Comment by alunyaka** [comment]
@christophMW I've been fighting with this issue for this whole week until recently I found out something: the argument for Chromium is called --auth-server-**allow**list [⊗](https://peter.sh/experiments/chromium-command-line-switches/#auth-server-allowlist)  not, not **white**list.

Apparently this option was deprecated https://admx.help/?Category=Chrome&Policy=Google.Policies.Chrome::AuthServerWhitelist 

After changing that I have finally been able to use a different username on my resource.

**Comment by christophMW** [comment]
Thank you for your help @alunyaka ! Works perfect!

**Comment by marcvergara2** [comment]
Thanks @alunyaka! it worked!

**Comment by bxrt** [comment]
Confirming @alunyaka's solution for JavaScript/TypeScript, adding the Chromium launchOption `--auth-server-allow-list="_"` to playwright.config.ts as shown below solved the issue for us:

```TypeScript
[...]
 use: {
[...]
	launchOptions: {
		args: ["--auth-server-allowlist=\"_\""],
	},
  },
[...]
```
