### ISSUE TITLE
[BUG]Auto wait and wait_for_selector does not behave as expected

### ISSUE THREAD

**Issue by livos** [microsoft/playwright#26401]
- Playwright Version: v1.36.0
- Operating System: Windows 11
- Browser: Firefox

Of what I understand Playwright auto wait feature should wait for an element to be fully loaded, there is also `page.wait_for_selector()` that is I think supposed to do something similar but explicitly. Both does not work. 

I come from selenium, I expect Playwright to behave the same as Selenium and implicit wait (auto wait feature of Playwright) or explicit wait with `wait_for_selector()` (similar behavior as [WebDriverWait ](https://www.selenium.dev/documentation/webdriver/waits/) with Selenium). Note that my code is working since everything works fine If I just add a `time.sleep()` before my `page.query_selector()`.

How to add an explicit wait that behave like Selenium WebDriverWait ?

**Comment by dgozman** [comment]
@livos We need more information to act on this issue. Could you please provide a self-contained repro that we can run locally? Otherwise, it's impossible to help you.

**Comment by mxschmitt** [comment]
Closing as per above, please re-file.
