### ISSUE TITLE
BUG - To run multiple script at a time

### ISSUE THREAD

**Issue by Rabave3** [microsoft/playwright#26408]
Package.json

"scripts": {
    "AdminPortal-UI": "npx playwright test --config adminportal.config.js --workers=1",
    "AdminPortal-API": "npx playwright test --grep @API --config adminportal.config.js --workers=1",
    "Extension": "npx playwright test --config extension.config.js --workers=1"
}

My script is like the above, I need to run all the scripts sequentially in one command with one worker and if AdminPortal-UI gets failed it should continue with the other scripts. I tried running multiple ways like below I mentioned but it's not working. Can anyone help to solve this issue?

1. npm run AdminPortal-UI && npm run AdminPortal-API && npm run Extension
2. npm run AdminPortal-UI || npm run AdminPortal-API || npm run Extension
3. npm run AdminPortal-UI ; npm run AdminPortal-API ; npm run Extension

**Comment by dgozman** [comment]
@Rabave3 Look into [projects](https://playwright.dev/docs/test-projects). You can have a number of projects with various configurations including `grep`, `testMatch`, etc., and as long as you set `workers: 1` in the config, they should run sequentially.

Let me know if you have more questions.

**Comment by Rabave3** [comment]
Working fine thanks for your support.
