### ISSUE TITLE
[Docs] Improve sharding command on Github actions

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#26402]
Improve the docs to use job total on sharding. 
In the sharding example here: 
https://github.com/microsoft/playwright/blob/main/docs/src/ci.md#on-pushpull_request-sharded

You can replace this shard with more robust code:  
instead of shard: [1/10, 2/10, 3/10, 4/10, 5/10, 6/10, 7/10, 8/10, 9/10, 10/10]

Define the shard as: [1,2,3,4,5,6,7,8,9,10]
And then in the command use: 
run: npx playwright test --project=${{ matrix.project }} --shard=${{ matrix.shard }}/${{strategy.job-total}}

(would be great if GH will add shard: [1..10])

**Comment by dgozman** [comment]
@Tallyb We consider `${{strategy.job-total}}` to be a footgun, because as soon as you add another matrix dimension like OS or browser, you start missing some tests. Therefore we have arrived to the current notation.

**Comment by mxschmitt** [comment]
Closing as per above.
