### ISSUE TITLE
[BUG] Get by test id without an assertion always passes

### ISSUE THREAD

**Issue by andersr** [microsoft/playwright#26416]
According to [the docs](https://playwright.dev/docs/locators#locate-by-test-id), an element can be located with a test id.
I am assuming (incorrectly?) that if no element with this test id exists, that the test should fail. However, unless an assertion is appended to the locator, the test passes regardless of if the test id is present. 

## An example

```javascript
import { test } from '@playwright/test';

test('get by test id', async ({ page }) => {
  await page.goto('http://localhost:3000/');

  await page.getByTestId('foo');
});
```

The above passes for me regardless of if a matching test id is present.

### System info
- Playwright Version: 1.36.2
- Operating System: macOS 13.4.1
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

[github repo with a reproduction of the issue](https://github.com/andersr/playwright-findybtestid-repro)

**Steps**
- Start the dev server in one terminal with `npm run dev`
- In a second terminal run the one test with `npx playwright test`

**Expected**

Test should fail because there is no element with test id "foo"

**Actual**

Test passes

**Comment by Nav-2d** [comment]
you need to perform some action on this maybe? like an assertion or click and it will fail.

await page.getByTestId('foo');

**Comment by dgozman** [comment]
@andersr [Locators](https://playwright.dev/docs/locators) tell Playwright **how** to locate an element, but they don't actually **do** anything. You usually use locator to perform an action or to make an assertion. In your case, you probably mean "this element should be visible on the page":

```ts
await expect(page.getByTestId('foo')).toBeVisible();
```

**Comment by andersr** [comment]
@dgozman thanks for the clarification.  However, should `page.getByTestId('foo')` then not result in a test failure or an error or a warning of some kind?  If an action and assertion are required for a valid test, then the absence of these should not result in a passing test.

Additionally, it's worth noting that in, in Cypress, the equivalent code does what I would expect: `cy.get('[data-test-id="foo"]')` is both a locator and an assertion.  If no element with that test id is found, the test will fail.

**Comment by dgozman** [comment]
@andersr Test in Playwright is a just a regular javascript function. Calling `page.getByTestId('foo')` is valid javascript, and so it does not result in a test failure.

We do not think that merely creating a locator should be treated as an assertion. For example, you can store your locator in a variable and reuse it for multiple actions/assertions:

```ts
const checkbox = page.getByRole('checkbox');

await expect(checkbox).not.toBeChecked();
await checkbox.check();
await expect(checkbox).toBeChecked();
```
