### ISSUE TITLE
[BUG]  Playwright+Cucumber - SoftAssertion is not working.

### ISSUE THREAD

**Issue by varshanharshank** [microsoft/playwright#26412]
Soft assertion is not working for Playwright+Cucumber combination. 

### System info
- Playwright Version: 1.36.2
- Operating System:Mac os 13.5
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
It is private project and unable to share project

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Test file (self-contained)**

**Steps**
1. Created Playwright + Cucumber function
2.  Try to include the below step one of the feature step definition
 expect.soft(true).toEqual(false)
3. Run the script using **npx cucumber-js test --tags '@smoke1'**

//package.json
```
{
  "name": "devportalautomation",
  "version": "1.0.0",
  "description": "devPortalAutomation",
  "main": "index.js",
  "scripts": {
    "pretest": "rm -rf reports && rm -rf allure-results",
    "test": "npx cucumber-js test --tags '@smoke1'",
    "report": "npx ts-node src/helper/report/cucumberReport.ts",
    "allure": "npx allure generate reports/allure-results --clean -o reports/allure-report && npx allure open reports/allure-report",
    "lint": "node_modules/.bin/eslint . --ext .ts"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@cucumber/cucumber": "^9.3.0",
    "@playwright/test": "1.36.2",
    "@types/ssh2": "^1.11.13",
    "@types/ssh2-sftp-client": "^9.0.0",
    "@typescript-eslint/eslint-plugin": "^6.2.0",
    "@typescript-eslint/parser": "^6.2.0",
    "allure-commandline": "^2.23.1",
    "allure-cucumberjs": "^2.4.0",
    "allure-js-commons": "^2.4.0",
    "eslint": "^8.46.0",
    "fs-extra": "^11.1.1",
    "moment": "^2.29.4",
    "multiple-cucumber-html-reporter": "^3.4.0",
    "prettier": "^3.0.0",
    "ts-node": "^10.9.1",
    "typescript": "^5.1.6",
    "ssh2": "^1.14.0"
  }
}```

//cucumber.json
```{
  "default": {
    "paths": ["src/test/features"],
    "require": ["src/test/stepDefinitions/*.ts", "src/hooks/hooks.ts"],
    "requireModule": ["ts-node/register"],
    "publishQuiet": true,
    "format": [
      "progress-bar",
      "./src/helper/report/allureReport.ts:./output.txt",
      "html:reports/cucumberReport/cucumber-report.html",
      "json:reports/cucumberReport/cucumber-report.json"
    ],
    "parallel": 1
  }
}```

**Expected**
script should not stop in the middle
[Describe expected behavior]

**Actual**
script is failing in the above mentioned step and not proceeding further

[Describe actual behavior]

**Comment by dgozman** [comment]
@varshanharshank Soft assertions require integration with a test runner, because they do not just throw an error, but rather record all failed assertions somewhere in the test runner. Since you are not using Playwright test runner, but rather `npx cucumber-js test`, soft assertions do not work.

I'd recommend looking for some kind of soft assertions in the cucumber test runner instead.

**Comment by mxschmitt** [comment]
Closing as per above.
