### ISSUE TITLE
CDPSession seems does not work

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2642]
I just write an example code which follows to https://github.com/microsoft/playwright/blob/master/docs/api.md#class-cdpsession:
// cdpTestFile.ts
```ts
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({headless: false})
  const page = await browser.newPage()
  const client = await page.context().newCDPSession(page);
  await client.send('Animation.enable');
  client.on('Animation.animationCreated', () => console.log('Animation created!'));
  await page.goto('https://www.google.com.vn')
})();
```
running `node cdpTestFile.ts` - the browser launch and navigate to google but nothing print out, I've tried this one on puppeteer and it works

**Comment by pavelfeldman** [comment]
If you set the `DEBUG=pw:protocol` environment variable, you will see that the session is indeed operational. And if you open DevTools on that page, there will be no animations, so you get no logs. Not sure why you see something in Puppeteer!

**Comment by phileba** [comment]
yep in the puppeteer, when the page navigates to Google, I see the console log `Animation created!` on the terminal, the DevTools was not open.

**Comment by pavelfeldman** [comment]
But there are no animations, I am using DevTools to confirm it. I can see events if I for example issue `Runtime.enable`. What version of Puppeteer are you using?

**Comment by phileba** [comment]
@pavelfeldman  I'm using puppeteer 2.1.1

**Comment by aslushnikov** [comment]
> yep in the puppeteer, when the page navigates to Google, I see the console log Animation created! on the terminal,

@phileba Puppeteer @2.1.1 comes with an **old chromium** version. Google.com behaves differently on that browser version wrt the modern one. If you use modern Puppeteer version @4.0.0 that comes with **modern chromium**, you won't see any animations; this is what you observe in the modern Playwright @1.1.1 as well.

This doesn't mean CDPSession is not working; it very much does. If you try using some animation-heavy website, e.g. 
https://animista.net/play/basic/rotate, you'll see logs in the console.

For the record, here are the scripts I tried:

## Playwright

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({headless: false})
  const page = await browser.newPage()
  const client = await page.context().newCDPSession(page);
  await client.send('Animation.enable');
  client.on('Animation.animationCreated', () => console.log('Animation created!'));
  await page.goto('https://www.google.com.vn')
})();
```

## Puppeteer

```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({headless: false})
  const page = await browser.newPage()
  const client = await page.target().createCDPSession();
  await client.send('Animation.enable');
  client.on('Animation.animationCreated', () => console.log('Animation created!'));
  await page.goto('https://www.google.com.vn')
})();
```
