### ISSUE TITLE
[BUG] Jenkins logs are polluted because Playwright sets FORCE_COLOR to true

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#26430]
### System info
- Playwright Version: 1.37.0
- Operating System: Jenkins
- Browser: All
- Other info:

[From 1.37 Playwright sets `FORCE_COLOR` env variable](https://github.com/microsoft/playwright/pull/24619/files#diff-80c1d8a3c2bdb499b3c345cd165934c8b991d2c58dc56fd2ad37a670583aaf25R43). 

However, Jenkins (I think by default) sets NO_COLOR variable for console logs.

The result is that whenever you do `console.log` in tests to output something to console logs you also get this accompanying message in Jenkins console logs:
```
15:26:12  (node:678) Warning: The 'NO_COLOR' env is ignored due to the 'FORCE_COLOR' env being set.
```

This may not be a bug but rather weird behavior and not an easy one to understand. Whether you'll act on this or not, I hope this issue will help someone trying to figure this out.

Fixed this by adding `if (process.env.CI) process.env.FORCE_COLOR = '0'` in playwright.config.ts

**Comment by dgozman** [comment]
@MindaugasMateika Are you sure this is a regression? I think we are forcing colors in test workers for a long time. The change you've linked to only affects the `webServer` config option.

I've tried running the following test with `NO_COLOR=1` and I don't see any warnings.

```ts
test('a test', async () => {
  for (let i = 0; i < 10; i++)
    console.log('hey');
});
```

Could you please share a repro that we can run locally?

**Comment by MindaugasMateika** [comment]
Kind of regression. Apparently, both these environment variables are set in both 1.35 and 1.37 but only with 1.37 these warnings appear in Jenkins logs. I'm unable to provide repro which includes Jenkins, closing.
