### ISSUE TITLE
[BUG] Typing - Type of `pageFunction` arg of `Locator.evaluateHandle` is not inferred

### ISSUE THREAD

**Issue by JuroOravec** [microsoft/playwright#26449]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

N/A - Playwright is provided via [Apify / Crawlee library](https://crawlee.dev/docs/quick-start#playwrightcrawler)

**Test file (self-contained)**

```js
it('test', async ({ page }) => {
  const loc = await page.locator('selector');
  // The typing of loc.evaluateHandle doesn't infer the types
  // `el` should be of type `HTMElement` or similar, but is `any`
  // `arg` should be of type `string`, but is `any`
  await loc.evaluateHandle((el, arg) => {
    // ...
  }, 'abc');
});
```

**Steps**
- Create a project in VSCode (aka some IDE with support for TS)
- Write the test above
- See the inferred types of `el` and `arg`.

**Expected**

`el` should be of type `HTMElement` or similar, but is `any`.
`arg` should be of type `string`, but is `any`.

Compare the type definitions for:
- Page (uses `PageFunction` type)
   
     <img width="716" alt="Screenshot 2023-08-13 at 09 02 27" src="https://github.com/microsoft/playwright/assets/25986782/ad75ded3-0926-416f-9b91-64f43fe4308d">

- Locator (uses `Function` type)

    <img width="665" alt="Screenshot 2023-08-13 at 09 01 39" src="https://github.com/microsoft/playwright/assets/25986782/1c364297-e54a-4fd5-aa12-d11eb6354964">

**Actual**

The function args are not typed (AKA they are `any`).

<img width="760" alt="Screenshot 2023-08-13 at 09 35 36" src="https://github.com/microsoft/playwright/assets/25986782/06309e1c-a54f-4cda-8895-8922a15c0a60">

**Comment by JuroOravec** [comment]
Hi @mxschmitt, thanks for the quick fix!

**Comment by mxschmitt** [comment]
Thank you for the great bug report!
