### ISSUE TITLE
[BUG] Webkit SVG CSS filter

### ISSUE THREAD

**Issue by liamcarter111** [microsoft/playwright#26447]
### System info
- Playwright Version: [v1.36.2]
- Operating System: [macOS 13.4.1]
- Browser: [WebKit]
- Other info:
  - Apple M2

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

I thought that rendered content between Safari and the Webkit browser was supposed to be the same (when running on a Mac). There are some differences between SVG rendering. Does this means that the WebKit browser is not a stable substitute for Safari for SVG based applications?

The issue is specifically linked to the `filter` CSS.

**Example HTML**

`test.html`
```html
<html>
  <head>
    <style>
      body {
        background: linear-gradient(to left, black 50%, white 50%);
      }
      svg {
        position: absolute;
        top: 50%;
        left: 50%;
        width: 100px;
        height: 100px;
        transform: translate(-50%, -50%);
        /* filter: drop-shadow(2px 2px 0px white); */
        filter: blur(4px);
      }
    </style>
  </head>
  <body>
    <svg width="100" height="100">
      <g>
        <circle
          cx="50"
          cy="50"
          r="45"
          stroke="black"
          stroke-width="3"
          fill="red"
        />
      </g>
    </svg>
  </body>
</html>
```

**Steps**
- Open the HTML example in the webkit browser
```bash
npx playwright open -b webkit test.html
```

**Expected**

Should render the same as Safari.

[Safari Browser]
<img width="1179" alt="Screenshot 2023-08-13 at 02 14 19" src="https://github.com/microsoft/playwright/assets/7712589/82b571d5-e97a-48aa-9646-4d10bec79d40">

**Actual**

Does not render the same as Safari.

[Webkit Browser]
<img width="1288" alt="Screenshot 2023-08-13 at 02 13 48" src="https://github.com/microsoft/playwright/assets/7712589/751429a2-4970-48ea-b51c-ef252eac76bc">

**Comment by yury-s** [comment]
This is a WebKit bug, filed upstream https://bugs.webkit.org/show_bug.cgi?id=260152. It works fine in current stable release of Safari but is broken on tip-of-tree WebKit.

**Comment by mxschmitt** [comment]
Seems fixed in ToT, should be available in Canary in 1-2 days: https://playwright.dev/docs/canary-releases
