### ISSUE TITLE
[BUG]Once test execution is completed, error in closing chromium browser

### ISSUE THREAD

**Issue by vrknetha** [microsoft/playwright#2645]
**Context:**
- Playwright Version: 1.0.2
- Operating System: Windows
- Node version: v12.16.3
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

[Error: EPERM: operation not permitted, unlink 'C:\**\**\AppData\Local\Temp\playwright_chromiumdev_profile-K5r8aA\CrashpadMetrics-active.pma'] {
  errno: -4048,
  code: 'EPERM',
  syscall: 'unlink',
  path: 'C:\\**\**\\AppData\\Local\\Temp\\playwright_chromiumdev_profile-K5r8aA\\CrashpadMetrics-active.pma'
}

**Describe the bug**

If we are using more pages for tests, once the execution is completed. chromium won't close by itself. We need to close manually from task manager.

**Comment by mxschmitt** [comment]
Could we get a minimal Javascript reproducible how the error occurs? Are you using Jest?
Keep in mind, that you have to close the browser with `await browser.close()` at the end of your tests. Also when they are failing, e.g. with a try catch.

**Comment by aslushnikov** [comment]
@vrknetha I don't think this is actionable unless we can debug it :(

Can you please share a script for us to try?

**Comment by vrknetha** [comment]
Ok, I will create a new repo and share it here.

**Comment by aslushnikov** [comment]
This is not actionable without a repro - closing this for now.
