### ISSUE TITLE
[Feature] UI mode network filtering

### ISSUE THREAD

**Issue by olivierbeaulieu** [microsoft/playwright#26453]
I love using UI mode to debug my tests. However I often run playwright against my vite dev server, so the unbundled development environment causes _a lot_ of requests to happen.

<img width="573" alt="image" src="https://github.com/microsoft/playwright/assets/1663018/fc7c8bd7-6950-4c2f-9625-0c4055342c68">

Finding what I'm looking for in this tab is not the most enjoyable experience. I think there's a simple but very impactful improvement to be made by adding some basic filtering. The chrome devtools serve as a very good example to emulate:

<img width="1242" alt="image" src="https://github.com/microsoft/playwright/assets/1663018/0443dbd8-68c1-45b0-89b4-9de03a7807bb">

Basic text search and filtering by request type (xhr/js/css/etc.) would go a long way!

**Comment by Nickheythatsme** [comment]
+1

**Comment by bkuzma** [comment]
Big +1 for this. I'm sifting through hundreds of lines in my network tab right now 😅

**Comment by yannickbuntsma** [comment]
I could really use this as well. Doesn't have to be fancy (for me at least). If there would be a search field that would match on the URL, I think a big chunk of use cases would be covered.

**Comment by 403-html** [comment]
Same from us, +1, needed feature for bulky app's tests with many requests

**Comment by tobmaster** [comment]
What are the plans for this issue? Is it open for PRs or are there bigger plans?

**Comment by mxschmitt** [comment]
This seems done in https://github.com/microsoft/playwright/pull/31956:

<img width="871" alt="image" src="https://github.com/user-attachments/assets/79171a0d-ba66-4310-a1e9-be6ff71749d6">

Thanks to @kubajanik!
