### ISSUE TITLE
[Feature] Global Setup for codegen

### ISSUE THREAD

**Issue by religiones** [microsoft/playwright#26460]
Hello, Is there any way to pre-execute a script before Codegen recording? just like the global setup. I used global setup to save the cookie in storage state before testing. But when I wanted to use the same method to avoid repeated login while recording, I found that there was no "global setup" to configure codegen. 
I know that Codegen can use `--save-storage` to save cookies, but I want to use a script to fetch cookie information instead of the user performing a login operation to save cookies before recording.

So, is there any way to configure the codegen before recording?

**Comment by religiones** [comment]
I know that Codegen can use save-state to save cookies, but I want to use a script to fetch cookie information instead of the user performing a login operation to save cookies before recording.

**Comment by mxschmitt** [comment]
Do you invoke Codegen via VSCode or via the Terminal (npx playwright codegen)?

If you invoke it via VSCode, the session of the last running test gets used. If you prefer to run custom code before running Codegen, you can call `page.pause()` in a script see [here](https://playwright.dev/docs/api/class-page#page-pause). Like this:

```ts
import { chromium, devices } from 'playwright';

(async () => {
  const browser = await chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  // ...
  await page.pause();

  await context.close();
  await browser.close();
})();
```

Would that work for you?

**Comment by religiones** [comment]
@ [mxschmitt](https://github.com/mxschmitt) thanks for your response. I tried this to pre-execute the login script before launching codegen, and it worked. But I find that it doesn't seem to automatically save the test case code. 

Fortunately, I've written the pre-login and record operations `npx playwright codegen` into a pipeline using shell scripts. It solved my problem. 😊

But I still have a question, **why doesn't Playwright provide a configuration file for CodeGen?** Having a separate codegen configuration file or incorporating it into (playwright.config.ts) may makes it easy to help developers predefine some of the recording features, just like the global setup I need.

**Comment by mxschmitt** [comment]
> why doesn't Playwright provide a configuration file for CodeGen?

So far there were not enough use-cases for it, that's why there is none.

Inside VSCode if you use Codegen, we usually expect the user to be in a "good working state" from e.g. previous test run in his Playwright browser when he is using the "Show Browser" functionality.

Happy to hear that you have a workaround for your use-case!

**Comment by asmyshlyaev177** [comment]
> > why doesn't Playwright provide a configuration file for CodeGen?
> 
> So far there were not enough use-cases for it, that's why there is none.
> 
> Inside VSCode if you use Codegen, we usually expect the user to be in a "good working state" from e.g. previous test run in his Playwright browser when he is using the "Show Browser" functionality.
> 
> Happy to hear that you have a workaround for your use-case!

When need to set some cookie/localStorage, and be authenticated as some user.

**Comment by yuriteixeira** [comment]
It would be super useful to be able to at least pass a `--project my-project-name-with-configs` to it, so I would be able to enjoy all the flexibility provided by configs, specially passing params to the browsers so problems like DRM media playback could be solved (by passing the `--disable-component-update` argument, see this [issue's comment](https://github.com/microsoft/playwright/issues/29151#issuecomment-1911739572) for reference)
