### ISSUE TITLE
how to add Temporary Addon on playwright firefox

### ISSUE THREAD

**Issue by gabbelitoV2** [microsoft/playwright#26477]
how to add Temporary Addon on playwright firefox?

**Comment by mxschmitt** [comment]
See on https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/ under "Using the command line".

You can also use e.g. https://github.com/ueokande/playwright-webextext or https://github.com/microsoft/playwright/issues/7297#issuecomment-1201240331.

Folding into https://github.com/microsoft/playwright/issues/7297.
