### ISSUE TITLE
[BUG] Unable to run tests in parallel in VS Code extension if `Show browser` option is enabled

### ISSUE THREAD

**Issue by maxsudik** [microsoft/playwright#26471]
**Context:**
- Playwright Version: 1.35.0
- Operating System: Mac
- Node.js version: v20.4.0
- Visual Studio Code version: Version: 1.81.1
- Playwright for VSCode extension version: v1.0.15
- Browser: All

Steps to reproduce:

1. Install a new Playwrigfht project
2. Move `tests/demo-todo-app.spec.ts` to `tests` package
3. In playwright.config.ts configure `fullyParallel: true`, and `workers: 5`,
4. In VS code plugin run tests with enabled `Show browser` option
Expected result: Tests should be run in parallel
Actual result: Tests are running in sequential mode
5. In VS code plugin run tests with disabled `Show browser` option
Expected result: Tests should be run in parallel
Actual result: Tests are running in parallel mode

**Comment by thomas-phillips-nz** [comment]
You need to make sure you select all the profiles in VSCode:
![image](https://github.com/microsoft/playwright/assets/25220956/13a5e4ab-e01c-4bb8-8f83-0d2a3ab4eb3f)

![image](https://github.com/microsoft/playwright/assets/25220956/4855fdef-e0d8-4ab3-aebc-1623fbf1d450)
And do the same for debug

**Comment by maxsudik** [comment]
@thomas-phillips-nz what profiles have to do with the parallel execution of test files?
here is how it's described in the doc:
https://playwright.dev/docs/test-parallel

>  By default, test files are run in parallel

**Comment by mxschmitt** [comment]
This is expected, if you enable "Show Browser", we have a single browser window which means you can't run the tests in parallel, since they would otherwise infer with each-other.

We recommend disabling this option if you want to run e.g. your whole test-suite.

Would that work for you?

**Comment by maxsudik** [comment]
@mxschmitt when you say infer, what exactly do you mean?

**Comment by thadd-simpson-unison** [comment]
If you disable "Show Browser -- one worker" in the VS Code Playwright Test extension, and add the following snippet, you can run multiple chrome browser tests at the same time:

`//playwright.config.ts`
`export default defineConfig({`
`  fullyParallel: true,`
`  // default was 1, I just picked 2 for example`
`  workers: process.env.CI ? 2 : undefined,`
`  use: {`
`    headless: false,`
`  },`
`});`

Just adding this here because I haven't seen it mentioned anywhere else.
