### ISSUE TITLE
[BUG] page.mouse.click works locator.click(point) does not work

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#26479]
### System info
- Playwright Version: [v1.36.1, v1.37]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info: node.js

### Description

I'm trying to test against a Power Platform Slider control (MscrmControls.Slider.LinearSliderControl) and noticed some funny behavior's on locator.click.

If I call `locator.click()` without xy position, the control is clicked in the center of the control and the control's slider bar changes to reflect the new value (50%).

However I want to set a specific value on the slider so I calculate the position of the clock as follows:

```
    const sliderBarBoundingBox = await sliderBar.boundingBox();
    if (sliderBarBoundingBox === null) {
      throw new Error('Unable to determine boundingBox for slider');
    }

    const endPointX = sliderBarBoundingBox.x + sliderBarBoundingBox.width * (value / 100);
    const endPointY = sliderBarBoundingBox.y + sliderBarBoundingBox.height / 2;
```

if I call `sliderBar.click({ position: { x: endPointX, y: endPointY } })` the click action fails with a timeout.

if I call `sliderBar.click({ position: { x: endPointX, y: endPointY }, force: true })` the click action completes with the following in the call log:

```
attempting click action
waiting for element to be visible, enabled and stable
forcing action
element is visible, enabled and stable
scrolling into view if needed
done scrolling
performing click action
click action done
waiting for scheduled navigations to finish
navigations have finished
```

However the control has not changed value.

If I call `page.mouse.click(endPointX, endPointY)` using the same xy position, the control is clicked and the control's slider bar is changed to reflect the new value. (Correct behaviour)

So should `page.mouse.click(endPointX, endPointY)` the same as `locator.click({ position: { x: endPointX, y: endPointY } })` ?

### Source code

This control's code is part of the Power Platform UI and I cant really separate out into a standalone repro,

**Comment by mxschmitt** [comment]
locator.click does actionability checks while page.mouse.click does not: https://playwright.dev/docs/actionability

**Comment by basickarl** [comment]
This might be related to locator.click not moving the mouse as mouse.click does.
