### ISSUE TITLE
[TIP] Run Playwright Tests on unsupported Linux distributions

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#26482]
To run Playwright on unsupported Linux distribution, you run run Playwright server in Docker while keeping your tests running on the host system:

### Run Playwright Server in Docker
```bash
docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"
```

It will output following when ready
```
Listening on ws://127.0.0.1:3000/
```

###  Point Playwright client to the server on Docker

If running @playwright/test, use environment variable, no other changes are needed.

```bash
PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test
```

Alternatively, for other applications and language ports, use [browserType.connect](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) API to use remote Playwright.

```js
const browser = await playwright['chromium'].connect('ws://127.0.0.1:3000/');
```

### Network

Make sure that the host network is available in your Docker container if you are testing local servers:

```sh
docker run --add-host=hostmachine:host-gateway
```

This will make `hostmachine` point to the host's localhost. Note that all the tests would also need to use `hostmachine` in the URLs to access servers on the host. Alternatively, you can follow unconventional route and do `docker run --add-host=localhost:host-gateway` at your own risk.

**Comment by dezoito** [comment]
@pavelfeldman , could you clarify the section that says:

> Make sure that the host network is available in your Docker container if you are testing local servers:
> `docker run --add-host=hostmachine:host-gateway`

Should the `add-host` part be added to the playwright container, the container that runs the tests, or all of them?

**Comment by mhchaudhry** [comment]
This is great, exactly what we needed, but the first thing that happens when you start the playwright server is that it goes out to npmjs to install the `playwright-core` dependency. Which doesn't work in say a CI/CD env with no outbound internet access. 

Ideally, the container should be self-contained. Why not install that dependency when creating the container so that it is fully self-contained and works in an offline environment?

**Comment by akoidan** [comment]
Hm, I wonder if it's possible to specify playwright host somehow

```bash
playwright@1.37.0 run-server --port 3000
```

Since atm, playwright always listens 127.0.0.1, and it's possible to specify `network_mode: host` only on Linux distros.

```bash
: yarn playwright run-server --help
yarn run v1.22.19
$ node_modules/.bin/playwright run-server --help
Usage: yarn playwright run-server [options]

Options:
  --port <port>               Server port
  --path <path>               Endpoint Path (default: "/")
  --max-clients <maxClients>  Maximum clients
  --mode <mode>               Server mode, either "default" or "extension"
  -h, --help                  display help for command
```

**Comment by atollk** [comment]
Unfortunately, the container doesn't work at all for me.
I have a fresh setup of Playwright with `npm init playwright@latest` and followed the instructions above. The container starts fine (`Listening on ws://127.0.0.1:3000/`) but the tests are just stuck.
```
>  PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test       
Running 6 tests using 6 workers
[6/6] [chromium] › example.spec.ts:10:5 › get started link
```

When running `npx playwright test` by itself, the command finishes almost immediately and has 4 of 6 passing tests (webkit failing due to missing dependencies).

**Comment by kencloudbeds** [comment]
Hello, I have an odd issue. I tried using the docker image inside Rocky Linux and it worked perfectly, webkit passed no problem. What I noticed is that if after running it on a specific port, if I reboot the server, it will no longer work on the same port. I actually have to change the port to get it to work again. If I reboot again, now the new port I used won't work, but if I switch back to the original port, now that will work again. The error I get is as follows:

` Error: browserType.connect: WebSocket error: connect EHOSTUNREACH 127.0.0.1:10700
    =========================== logs ===========================
    <ws connecting> ws://127.0.0.1:10700/
    <ws error> ws://127.0.0.1:10700/ error connect EHOSTUNREACH 127.0.0.1:10700
    <ws connect error> ws://127.0.0.1:10700/ connect EHOSTUNREACH 127.0.0.1:10700
    <ws disconnected> ws://127.0.0.1:10700/ code=1006 reason=
    ============================================================
`

The command I use is :

`docker run -p 10700:10700 --rm --init -it mcr.microsoft.com/playwright:v1.39.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.39.0 run-server --port 10700"`

So, every time I reboot, I have to keep switching back and forth between two ports 10700 and 10600. Do you have any idea why this would be happening?

Even if I redownload the docker image it will not work the previous port used prior to reboot.

Seems like some sort of cache issue.

Any help is appreciated.

**Comment by k1w1m8** [comment]
I have CentOS 7, unfortunately.

Tried using 1.40 and playwright-java with this approach.

Before you can call browserType.connect, you need a Playwright instance. To get that, you can Playwright.create(), but this creates a temporary node instance using /tmp and that doesn't work on unsupported CentOS 7.

```
/tmp/playwright-java-7742446124117836956/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/playwright-java-7742446124117836956/node)
```

So unless I missed something, these instructions only work for javascript version of playwright.

Seems the playwright-java needs improved client API to support connection to remote Playwright instance without "bouncing" off a local node.

**Comment by jericirenej** [comment]
I have the same issue as https://github.com/microsoft/playwright/issues/26482#issuecomment-1796970328. Tests are stuck. I'm specifying the service inside a `docker-compose` file, as I also need other containers running. I'm using port 5000 and specifying `localhost` in the `extra_hosts` property of the service. I hope everything is setup correctly:
```
playwright:
    image: mcr.microsoft.com/playwright:v1.37.0-jammy
    restart: always
    ports:
      - '5000:5000'
    container_name: "playwright-e2e"
    command:
      [
        "/bin/sh",
        -c,
        "cd /home/pwuser && npx -y playwright@1.37.0 run-server --port 5000"
      ]
    extra_hosts:
      - "localhost:host-gateway"
```

I run ` PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:5000/ npx playwright test`. The test setup starts fine (database seed), but then the tests hang indefinitely on all browsers. UI mode opens, but when I run an individual test, it hangs on `browserType.connect`.

If I use the `hostmachine` for the `extra_host` option, the situation is worse, since then the database seeding doesn't work at all. Tests don't use localhost in their URL's since they are always poinitng to specific endpoints ("/", etc.).

Shutting down the docker containers also takes 10 seconds due to the playwright service taking a long time to exit. 

I'm using Fedora 39, but this shouldn't really be a factor here. A workaround to install needed system dependencies for the distro would be much preferred, although having a Docker image is also a welcome step. 

Also, if the Docker image documentation will be expanded, I would suggest also including a docker-compose scenario, as this is probably a common use-case.

**Comment by Luc45** [comment]
> ```shell
> --add-host=hostmachine:host-gateway
> ```

It works, but can you please update it to 1.41 and add `--add-host=hostmachine:host-gateway` by default? It only worked for me like this.

1. `docker run --add-host=hostmachine:host-gateway -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000"`
2. `PW_TEST_CONNECT_WS_ENDPOINT=ws://localhost:3000/ npx playwright test`

**Comment by Luc45** [comment]
This only runs the Playwright [Webserver](https://playwright.dev/docs/test-webserver) in a dockerized environment, but the actual test execution, and therefore, the [browser dependencies](https://github.com/microsoft/playwright/issues/11122), still runs in the host, correct?

To run Playwright with dockerized browsers, one could run this inside their PW tests directory:

```
docker run \
--add-host=hostmachine:host-gateway \
--rm \
--init \
-it \
-v $(pwd):/home/pwuser/tests \
mcr.microsoft.com/playwright:v1.41.0-jammy \
/bin/sh -c "cd /home/pwuser && npm install @playwright/test@1.41.0 playwright@1.41.0 && npx playwright install && npx playwright test"
```

Only caveat with dockerized browser approach is that you can only run it headless. You loose out on many cool Playwright features such as `--headed`, or `--ui`.

Ideally, Playwright should be able to install the browsers and dependencies in Linux to run the test natively so that we can have headed runs.

**Comment by jfrantzius** [comment]
Hi @pavelfeldman , 
do you per chance know whether `PW_TEST_CONNECT_WS_ENDPOINT` is also supported in the Java client?

**Comment by mxschmitt** [comment]
@jfrantzius for Java you can just use [BrowserType.connect()](https://playwright.dev/java/docs/api/class-browsertype#browser-type-connect).

The link above shows connectOverCDP which is about CDP and Chrome only while this issue is about connect() which supports all the browser types Playwright supports.

**Comment by jfrantzius** [comment]
Thx @mxschmitt !

**Comment by nicholasgriffintn** [comment]
For everyone else using this script, I had problems with WebSocket errors, had to add a few lines to wait for the server to be ready in the Docker script before finishing:

```bash
#! /bin/bash

if ! curl --output /dev/null --silent --head --fail http://localhost:9009/status
then
  echo "Starting PlayWright Server"
  docker run \
    -d -p 9009:9009 \
    --add-host=hostmachine:host-gateway \
    --rm --init -it \
    mcr.microsoft.com/playwright:v1.41.1-jammy \
    /bin/bash -c "cd /home/pwuser && npx -y playwright@1.41.1 run-server --port 9009"

  # Wait for server to start
  while ! curl --output /dev/null --silent --head --fail http://localhost:9009/status; do
    sleep 0.2
  done
fi
```

**Comment by Lesik** [comment]
@Luc45

> You loose out on many cool Playwright features such as --headed, or --ui.

If you run Playwright with `--ui-host=0.0.0.0` as described [here](https://playwright.dev/docs/test-ui-mode#docker--github-codespaces), you can simply access the Playwright UI in a regular browser running on your host.

**Comment by Luc45** [comment]
> If you run Playwright with --ui-host=0.0.0.0 as described [here](https://playwright.dev/docs/test-ui-mode#docker--github-codespaces), you can simply access the Playwright UI in a regular browser running on your host.

You're right, this is awesome and addresses my concern with Dockerized runs.

The only thing I'm still trying to do is `npx playwright codegen` in a dockerized run, as it doesn't seem to have `--ui-host` parameter like `npx playwright test` does.

**Comment by liquidcms** [comment]
Trying to piece together a working solution together from the posts here (I am running on Alma).

the original post - it is not correct, is it? it states to set host to 0.0.0.0 and then says it will respond with listening on 127.0.0.1, which of course it does not say, it says listening on 0.0.0.0. And then it runs: "PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test" which seems wrong as well, as it is not listening on 127.0.0.1

regardless, if i do what is posted or "fix it" to run on 0.0.0.0, same result. it just hangs and no report is created.

The same happens for the solution posted by Luc45 on Jan 19 (why hasn't github figured out numbering comments??). It just hangs, nothing created.

If i dont run docker and just run: npx playwright test, i get output saying all tests failed and a playwright-reports/index.html with a nicely formatted report; saying all tests failed. which would seem to indicate pw runs on alma, but possibly the tests are not configured correctly?

**Comment by jericirenej** [comment]
> Trying to piece together a working solution together from the posts here (I am running on Alma).
> 
> the original post - it is not correct, is it? it states to set host to 0.0.0.0 and then says it will respond with listening on 127.0.0.1, which of course it does not say, it says listening on 0.0.0.0. And then it runs: "PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test" which seems wrong as well, as it is not listening on 127.0.0.1
> 
> regardless, if i do what is posted or "fix it" to run on 0.0.0.0, same result. it just hangs and no report is created.
> 
> The same happens for the solution posted by Luc45 on Jan 19 (why hasn't github figured out numbering comments??). It just hangs, nothing created.
> 
> If i dont run docker and just run: npx playwright test, i get output saying all tests failed and a playwright-reports/index.html with a nicely formatted report; saying all tests failed. which would seem to indicate pw runs on alma, but possibly the tests are not configured correctly?

Playwright will run, but I think the system dependencies that are needed and the browsers won't be installed  which is also why tests are probably failing?

For me, the following compose configuration works (similar to configuration from my post on 31 Dec 2023)
```
 SERVICE_NAME:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    restart: always
    container_name: "CONTAINER_NAME"
    init: true
    ipc: host
    command:
      [
        "/bin/sh",
        -c,
        "cd /home/pwuser && npx -y playwright@1.40.0 run-server --port PORT_NUMBER"
      ]
    network_mode: host
```

Then you can run it with `PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:PORT_NUMBER/ npx playwright `test`

**Comment by liquidcms** [comment]
Thanks for the quick reply. From what you wrote i put together the newbie version:

- install docker-compose
- create a docker-compose.yml with the following:

```
services:
 playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    restart: always
    container_name: "playwright"
    init: true
    ipc: host
    command:
      [
        "/bin/sh",
        -c,
        "cd /home/pwuser && npx -y playwright@1.40.0 run-server --port 3000"
      ]
    network_mode: host
```

- run docker-composer up
- PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test

after all that, same result as before. this outputs nothing.

**Comment by jericirenej** [comment]
The docker compose up command seems to be working correctly as it outputs the "Listening on..." message. However, are you inputting the command directly in the same terminal as the one that you've ran the docker compose command on? 

If that is so, the command will not work, as the docker process is running in the foreground and you do not have access to the shell as such. Either try running the command in a separate terminal or run the docker compose command with the `-d` flag so that the docker compose will run in detached mode and release the shell back to you.

If that still does not work, you can try running the Playwrighht in UI mode
`"PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:5000/ npx playwright test --ui-port=SOME_OTHER_PORT`
Then open the browser at localhost:SOME_OTHER_PORT and see if the Playwright's UI is showing and if it recognizes your tests.


Then open your browser at localhost:SOME_OTHER_PORT

**Comment by liquidcms** [comment]
woke up this morning and that dawned on me... this is run as a service and i need to execute npx in a different window. duh. Tried that and then could see a client/server pw version mismatch; not sure why but changed the version in docker.compose.. and it is working now.

thanks for getting back to me.

**Comment by Kinfe123** [comment]
hey theere i am still facing an issue of 
`
Error: page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:5173/
Call log:
  - navigating to "http://localhost:5173/", waiting until "load"
`
my vite app is running at 5173 , how can i solve this , the app is running locally fine

**Comment by Luc45** [comment]
@Kinfe123 try to use network:host on your docker command (look it up for exact syntax)

**Comment by MarineLHexIT** [comment]
Hello!

I’m currently trying to make Playwright work in Docker so I can test on unsupported browsers.
I’ve been reading this page for hours, trying multiple things. I’m not proficient with Docker.

My application runs on http://localhost:3000 and works fine on my browser

Here are the conf I’m using, and the output / issue

The docker-compose.yml
```
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.41.0-jammy
    restart: always
    container_name: "playwright"
    init: true
    ipc: host
    ports:
      - '5000:5000'
    command:
      [
        "/bin/sh",
        -c,
        "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 5000"
      ]
#    network_mode: host
    extra_hosts:
      - "localhost:host-gateway"
```

The command I run : 
` PW_TEST_CONNECT_WS_ENDPOINT=ws://localhost:5000/ npx playwright test`

The output I got : 

> Error: page.goto: net::ERR_CONNECTION_REFUSED at http://127.0.0.1:3000/auth/signin
>     Call log:
>       - navigating to "http://127.0.0.1:3000/auth/signin", waiting until "load"

I can go on localhost:5000, it says "running"

If I remove the commentary and set the network_mode to host, I got the following output:

> Error: browserType.connect: WebSocket error: connect ECONNREFUSED ::1:5000

localhost:5000 does not reply in this configuration

Maybe @Kinfe123 or @Luc45 have an idea, as it seems to be the same issue from the last posts?

**Comment by jericirenej** [comment]
If you set network_mode to host, do you also comment out the extra_hosts line? 

In my case, I only have the network_mode se tot host and no extra hosts specified. I have the base url specified in the Playwright config.  

Also, try using a newer image, like  mcr.microsoft.com/playwright:v1.43.0-jammy (I'm not sure why the Docker hub entry still specifies the 1.40 version).  In that case you should also update the playwright dependency in your package.json

**Comment by MarineLHexIT** [comment]
Thank @jericirenej, I updated the image, but I still have the WebSocket Error 
> Error: browserType.connect: WebSocket error: connect ECONNREFUSED ::1:5000

My docker-compose :
```
services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.43.0-jammy
    restart: always
    container_name: "playwright"
    init: true
    ipc: host
    ports:
      - '5000:5000'
    command:
      [
        "/bin/sh",
        -c,
        "cd /home/pwuser && npx -y playwright@1.43.0 run-server --port 5000"
      ]
    network_mode: host
#    extra_hosts:
#      - "localhost:host-gateway"
```

My playwright-config.ts
```
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'yarn dev',
    url: 'http://127.0.0.1:3000',
    reuseExistingServer: !process.env.CI,
  },
});
```

I have commented next to every browser so I could  write tests and it works outside of Docker (but I can’t test Safari or Edge)

The command i use
`PW_TEST_CONNECT_WS_ENDPOINT=ws://localhost:5000/ npx playwright test`

**Comment by jericirenej** [comment]
What if you replace the 127.0.0.1 with localhost?
On my machine, if I use the exact this address, the tests hangs, but with localhost it runs fine

**Comment by ben-hamel** [comment]
Should I be able to generate Visual snapshots using this method? when running I just get a white page with "Running" 
<img width="1204" alt="Screenshot 2024-08-15 at 11 35 39 AM" src="https://github.com/user-attachments/assets/88b51f90-6aa4-4ad6-b6db-7a844093b094">

**Comment by barambulka** [comment]
> To run Playwright on unsupported Linux distribution, you run run Playwright server in Docker while keeping your tests running on the host system:
> 
> ### Run Playwright Server in Docker
> ```shell
> docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"
> ```
> 
> It will output following when ready
> 
> ```
> Listening on ws://127.0.0.1:3000/
> ```
> 
> ### Point Playwright client to the server on Docker
> If running @playwright/test, use environment variable, no other changes are needed.
> 
> ```shell
> PW_TEST_CONNECT_WS_ENDPOINT=ws://127.0.0.1:3000/ npx playwright test
> ```
> 
> Alternatively, for other applications and language ports, use [browserType.connect](https://playwright.dev/docs/api/class-browsertype#browser-type-connect) API to use remote Playwright.
> 
> ```js
> const browser = await playwright['chromium'].connect('ws://127.0.0.1:3000/');
> ```
> 
> ### Network
> Make sure that the host network is available in your Docker container if you are testing local servers:
> 
> ```shell
> docker run --add-host=hostmachine:host-gateway
> ```
> 
> This will make `hostmachine` point to the host's localhost. Note that all the tests would also need to use `hostmachine` in the URLs to access servers on the host. Alternatively, you can follow unconventional route and do `docker run --add-host=localhost:host-gateway` at your own risk.

Does this mean the tests need to be run on the same machine where the PW Docker container is running?

**Comment by barambulka** [comment]
I tried to run Java tests with the code as in the https://github.com/microsoft/playwright/issues/26482#issuecomment-1869288427 but I'm getting an error running `gradle test`:

```
LoginTest > initializationError FAILED
    com.microsoft.playwright.PlaywrightException at LoginTest.java:37
        Caused by: com.microsoft.playwright.impl.DriverException at LoginTest.java:37
```
The row 37 is` Browser browser = playwright.chromium().connect("ws://127.0.0.1:3000/");`

Also I'm not sure if I'm using a correct image as here:
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
vs 
`mcr.microsoft.com/playwright/**java**:v1.41.0-jammy`
 But the 
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright/java:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
complains on `/bin/sh: 1: npx: not found`

Any help is much appreciated.

**Comment by barambulka** [comment]
I tried to run Java tests with the code as in the https://github.com/microsoft/playwright/issues/26482#issuecomment-1869288427 but I'm getting an error running `gradle test`:

```
LoginTest > initializationError FAILED
    com.microsoft.playwright.PlaywrightException at LoginTest.java:37
        Caused by: com.microsoft.playwright.impl.DriverException at LoginTest.java:37
```
The row 37 is` Browser browser = playwright.chromium().connect("ws://127.0.0.1:3000/");`

Also I'm not sure if I'm using a correct image as here:
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
vs 
`mcr.microsoft.com/playwright/**java**:v1.41.0-jammy`
 But the 
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright/java:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
complains on `/bin/sh: 1: npx: not found`

Any help is much appreciated.

**Comment by barambulka** [comment]
I tried to run Java tests with the code as in the https://github.com/microsoft/playwright/issues/26482#issuecomment-1869288427 but I'm getting an error running `gradle test`:

```
LoginTest > initializationError FAILED
    com.microsoft.playwright.PlaywrightException at LoginTest.java:37
        Caused by: com.microsoft.playwright.impl.DriverException at LoginTest.java:37
```
The row 37 is` Browser browser = playwright.chromium().connect("ws://127.0.0.1:3000/");`

Also I'm not sure if I'm using a correct image as here:
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
vs 
`mcr.microsoft.com/playwright/**java**:v1.41.0-jammy`
 But the 
`docker run -p 3000:3000 --rm --init -it mcr.microsoft.com/playwright/java:v1.41.0-jammy /bin/sh -c "cd /home/pwuser && npx -y playwright@1.41.0 run-server --port 3000 --host 0.0.0.0"`
complains on `/bin/sh: 1: npx: not found`

Any help is much appreciated.

**Comment by cconrad** [comment]
FWIW, I am running Fedora 41 and `playwright install` outputs the following warnings, but it seems to work anyway...

```
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
You are using a frozen webkit browser which does not receive updates anymore on ubuntu20.04-x64. Please update to the latest version of your operating system to test up-to-date browsers.
BEWARE: your OS is not officially supported by Playwright; downloading fallback build for ubuntu20.04-x64.
Playwright Host validation warning: 
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libicudata.so.66                                 ║
║     libicui18n.so.66                                 ║
║     libicuuc.so.66                                   ║
║     libjpeg.so.8                                     ║
║     libwebp.so.6                                     ║
║     libffi.so.7                                      ║
║     libx264.so                                       ║
╚══════════════════════════════════════════════════════╝
    at validateDependenciesLinux (/home/claus/Sites/.venv/lib/python3.13/site-packages/playwright/driver/package/lib/server/registry/dependencies.js:216:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async Registry._validateHostRequirements (/home/claus/Sites/.venv/lib/python3.13/site-packages/playwright/driver/package/lib/server/registry/index.js:753:43)
    at async Registry._validateHostRequirementsForExecutableIfNeeded (/home/claus/Sites/.venv/lib/python3.13/site-packages/playwright/driver/package/lib/server/registry/index.js:851:7)
    at async Registry.validateHostRequirementsForExecutablesIfNeeded (/home/claus/Sites/.venv/lib/python3.13/site-packages/playwright/driver/package/lib/server/registry/index.js:840:43)
    at async t.<anonymous> (/home/claus/Sites/.venv/lib/python3.13/site-packages/playwright/driver/package/lib/cli/program.js:137:7)
```

**Comment by samsternatretool** [comment]
Thanks to tips provided by others, we are successfully running Playwright on Amazon Linux 2 (via vitest):

```shell
# Install deps
sudo yum install -y alsa-lib at-spi2-atk at-spi2-core atk bash cairo cups-libs dbus-libs expat flac-libs gdk-pixbuf2 glib2 glibc gtk3 libX11 libXcomposite libXdamage libXext libXfixes libXrandr libXtst libcanberra-gtk3 libdrm libgcc libstdc++ libxcb libxkbcommon libxshmfence libxslt mesa-libgbm nspr nss nss-util pango policycoreutils policycoreutils-python-utils zlib

# Install playwright
pnpm exec playwright install --only-shell chromium

# Run tests
vitest run --browser.headless
```

**Comment by danrohtbart** [comment]
> This only runs the Playwright [Webserver](https://playwright.dev/docs/test-webserver) in a dockerized environment, but the actual test execution, and therefore, the [browser dependencies](https://github.com/microsoft/playwright/issues/11122), still runs in the host, correct?
> 
> To run Playwright with dockerized browsers, one could run this inside their PW tests directory:
> ... 

I had this exact problem, trying to run Playwright tests in Webkit on Amazon Linux 2023, as part of an Amplify project. 

So I made one small tweak to your command, so `npx playwright test` picks up all the config and tests from my project. Run this from the root of your project, instead of the test directory: 
```
docker run --add-host=hostmachine:host-gateway --rm --init -it -v $(pwd):/home/pwuser mcr.microsoft.com/playwright:v1.49.1-jammy /bin/sh -c "cd /home/pwuser && npm install @playwright/test@1.49.1 && npx playwright install && npx playwright test" 
```

Here it is in an amplify.yml: 
```
version: 1
frontend:
  phases:
    preBuild:
      commands:
        - npm install
    build:
      commands:
        - npm run build
  artifacts:
    baseDirectory: .next
    files:
      - '**/*'
  cache:
    paths:
      - node_modules/**/*
test:
  phases: 
    preTest:
      commands:
        - npm ci
        - npm install -g wait-on
        - npm install -g pm2
        - sudo dnf install -y docker 
        - sudo dockerd &
        - wait-on -t 15000 file:/var/run/docker.sock
        - npx pm2 start npm -- start
        - wait-on http://localhost:3000
    test:
      commands:
        - ls -la reports
        - sudo docker run --add-host=hostmachine:host-gateway --rm --init -v $(pwd):/home/pwuser mcr.microsoft.com/playwright:v1.49.1-jammy /bin/sh -c "cd /home/pwuser && npm install @playwright/test@1.49.1 && npx playwright install && npx playwright test" 
        - ls -la reports
    postTest:
      commands:
        - npx pm2 kill
  artifacts:
    baseDirectory: 'reports'
    files:
      - '**/*'
```     

My playwright.config.js is slightly modified: 
```
reporter: [
              ['json', { outputFile: 'reports/results.json' }],
              ['list'],
  ]
```
