### ISSUE TITLE
[Question] How to get in console.log a specific text message, from console within devtools

### ISSUE THREAD

**Issue by ajaykhobragade** [microsoft/playwright#2648]
Hi, I am trying to get specific text message to appear in console.log, which existed in console within devtool (when i add "&debug=true" at the end of url), i am trying following but msg.args prints out all kind of messages. is there a better way to handle\streamline the args?

const page = await browser.newPage();
await page.goto('URL&debug=true');

page.on('console', msg => {
    for (let i = 0; i < msg.args().length; ++i)
      console.log(`${i}: ${msg.args()[i]}`);
  });

**Comment by pavelfeldman** [comment]
You can do `page.on('console', console.log)`, print `msg.text()` or print values of individual args via calling `await msg args[i].jsonValue()` on them.

**Comment by ajaykhobragade** [comment]
ok cool, what if it's the numeric value? how can i cast it to an integer?

**Comment by pavelfeldman** [comment]
`console.log(42, 'hello', true);`
```js
await msg.args[0].jsonValue() // will give you 42
await msg.args[1].jsonValue() // will give you 'hello'
```
etc.

**Comment by aslushnikov** [comment]
I'll complement this with a snippet:

```js
const {webkit} = require('playwright');

(async () => {
  const browser = await webkit.launch();
  const page = await browser.newPage();
  const [msg] = await Promise.all([
    page.waitForEvent('console'),
    page.evaluate(() => {
      // Issue console.log statements inside the page.
      console.log('hello, world', 42, {foo: 'bar'});
    }),
  ]);

  // serialize and print all console.log arguments one-by-one.
  for (const arg of msg.args())
    console.log(await arg.jsonValue());
  await browser.close();
})();
```

**Comment by ajaykhobragade** [comment]
Awesome, that was helpful. Thanks a lot.

**Comment by nguyenquangtay** [comment]
Hello,
How can we store the logs in a list?
I'm on Python with the code below but it always returns []
`def get_console_logs(self) -> list:
        logs: list = []
        self.page.on("console", lambda msg: logs.append(msg.text))
        return logs`
Note: the print(msg.text) works fine! 
Thank you all!
