### ISSUE TITLE
Blob report custom output directory

### ISSUE THREAD

**Issue by pknupper** [microsoft/playwright#26481]
With the latest addition of the report merger I was trying to switch to blob reports and then merge those.

Unfortunately we need to store those reports in a custom directory.

Is it possible to configure the output directory for blob reports like HTML reports?

**Comment by pknupper** [comment]
Thanks a lot that worked for me.

**Comment by none0nfg** [comment]
> `reporter: [["blob", { outputDir: "./blob-dir/"}]]` works to create `report.zip` in a directory called `blob-dir`. I don't think this is documented anywhere yet but it's an[ option in the blob reporter code](https://github.com/microsoft/playwright/blob/576608b69d31b922d356fed6b3efa802e3c42481/packages/playwright-test/src/reporters/blob.ts).
> 
> You can also change the default report name from `report.zip` to whatever else by setting an env variable `PWTEST_BLOB_REPORT_NAME`

i've faced a problem with blob renaming. In gitlab CI it doesn't work. But locally does. Have you any idea, why it works like that.
I tried to rename by ENV - `PWTEST_BLOB_REPORT_NAME`

**Comment by pascalknupper** [comment]
@none0nfg  if you´re on <=1.41.0 you can use fileName property in blob reporter

```
reporter: [['blob', { outputDir: 'my-report', fileName: `dummy123.zip` }]]
```

**Comment by sufiyangorgias** [comment]
How to acheive this in command line I want blob report from different test file to different test folder example: 
╰─ yarn playwright test src/tests/flows/flows-chat-conditions.spec.ts --project=chromium --reporter=[["blob", { outputDir: "./blob-dir/"}]]
