### ISSUE TITLE
[Feature] Add a flag to ignore webSockets when using `waitForLoadState('networkidle')`

### ISSUE THREAD

**Issue by olivierbeaulieu** [microsoft/playwright#26487]
Hi!

I would like to raise the same issue that can be found [on the Pupeteer project](https://github.com/puppeteer/puppeteer/issues/1090). 

It appears that `waitForLoadState('networkidle')` will wait forever if there are open websocket connections. Can playwright either ignore them as pupeteer is doing, or offer an option to ignore them?

Thanks

**Comment by olivierbeaulieu** [comment]
Thank you for looking in to this. I did experience issues where I am (was?) fairly confident this was the problem - however your simple scenario looks good to me as well.

I'm seeing this happen in a rather complex test case. I will slim the issue down to a shareable reproduction.

**Comment by yury-s** [comment]
We need a reproducible example that we could run locally to make this report actionable. Please file a new issue with a repro and link it to this one when you get back to it!
