### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ajssd** [microsoft/playwright#26485]
### System info
- Playwright Version: 1.37.0
- Operating System: Oracle Enterprise Linux 7
- Browser: Chromium
- Other info:

### Issue

Upgrading from playwright 1.36.1 to 1.37.0, no other changes.  This apparently bumps from Chromium 114.0.5735.35 (1064) to Chromium 116.0.5845.82 (1076).

In doing so, we're hitting this error:
```
/lib64/libc.so.6: version `GLIBC_2.18' not found (required by .../ms-playwright/chromium-1076/chrome-linux/chrome)
```
Is it possible for 1.37.x to maintain compatibility with the same platforms as 1.36.x?  The [release notes for 1.37.0](https://github.com/microsoft/playwright/releases/tag/v1.37.0) do not mention anything about dropping support for Linux installs without GLIBC_2.18.

**Comment by mxschmitt** [comment]
This Oracle Enterprise Linux 7 is not supported, we only support these linux distributions, se we don't consider it a breaking change: https://playwright.dev/docs/intro#system-requirements

You could try our experimental way of running it on any linux distribution, see here: https://github.com/microsoft/playwright/issues/26482
