### ISSUE TITLE
[BUG] "Looks like you launched a headed browser without having a XServer running." even when headless is true.

### ISSUE THREAD

**Issue by Kuba-Sikora** [microsoft/playwright#26497]
I'm trying to run the test job in my gitlab CI/CD pipeline and I only want it to run in headless mode because there is no need for headed since its a pipeline. `headless: true` is supposed to be the default but even when i set it explicitly to true it still seems to be trying to launch the browser in headed mode. I've tried this with several tests, nothing seems to work. As soon as the test uses the page fixture it breaks.

I'm using the official docker image which should have all the dependencies installed

### System info
- Playwright Version: v1.37.0
- Operating System: Ubuntu 22
- Browser: Chromium, Firefox, Safari

### Source code

.gitlab-ci.yml
```yml
Run tests:
    image: mcr.microsoft.com/playwright:v1.37.0-jammy
    stage: test
    script:
        - npm i
        - DEBUG=pw:browser npx playwright test --debug
    retry:
        max: 1
        when:
        - script_failure
        - unknown_failure

```

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test'
import { LOCAL_PORT } from './build.config' // 1234

export default defineConfig({
  testDir: './tests',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'html',
  use: {
    baseURL: 'http://localhost:' + LOCAL_PORT,
    trace: 'on-first-retry',
    headless: true
  },

  // elongate timeouts
  expect: {
    timeout: 1 * 60 * 1000,
  },

  timeout: 2 * 60 * 1000,

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium-parallel',
      use: {
        ...devices['Desktop Chrome'],
      },
      testDir: './tests/parallel',
    },
    {
      name: 'firefox-parallel',
      use: {
        ...devices['Desktop Firefox'],
      },
      testDir: './tests/parallel',
    },
    {
      name: 'webkit-parallel',
      use: {
        ...devices['Desktop Safari'],
      },
      testDir: './tests/parallel',
    },
  ],

  /* Run your local dev server before starting the tests */
  webServer: {
    command: 'npm run start:playwright', // runs `webpack serve` with the open option set to false
    url: 'http://localhost:' + LOCAL_PORT,
    reuseExistingServer: !process.env.CI,
  },
})
```

**Steps**
- Trigger the pipeline test job

**Expected**

The job should succeed

**Actual**

Fails with this message:
```
pw:browser <launching> /ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-DawwcJ --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=270 +2ms
  pw:browser [pid=270][err] [270:284:0816/123258.678506:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory +60ms
  pw:browser [pid=270][err] [270:270:0816/123258.707194:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY +28ms
  pw:browser [pid=270][err] [270:270:0816/123258.707208:ERROR:env.cc(255)] The platform failed to initialize.  Exiting. +0ms
  pw:browser [pid=270] <gracefully close start> +16ms
  pw:browser [pid=270] <kill> +1ms
  pw:browser [pid=270] <will force kill> +0ms
  pw:browser [pid=270] <process did exit: exitCode=1, signal=null> +0ms
  pw:browser [pid=270] starting temporary directories cleanup +1ms
  pw:browser [pid=270] finished temporary directories cleanup +1ms
  pw:browser [pid=270] <gracefully close end> +0ms
×
  1) [chromium-parallel] › parallel/account.spec.ts:13:7 › account › account redirect ──────────────
    Error: browserType.launch: 
    ╔════════════════════════════════════════════════════════════════════════════════════════════════╗
    ║ Looks like you launched a headed browser without having a XServer running.                     ║
    ║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
    ║                                                                                                ║
    ║ <3 Playwright Team                                                                             ║
    ╚════════════════════════════════════════════════════════════════════════════════════════════════╝
    =========================== logs ===========================
    <launching> /ms-playwright/chromium-1076/chrome-linux/chrome --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=/tmp/playwright_chromiumdev_profile-DawwcJ --remote-debugging-pipe --no-startup-window
    <launched> pid=270
    [pid=270][err] [270:284:0816/123258.678506:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
    [pid=270][err] [270:270:0816/123258.707194:ERROR:ozone_platform_x11.cc(240)] Missing X server or $DISPLAY
    [pid=270][err] [270:270:0816/123258.707208:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
    ============================================================
  1 failed
    [chromium-parallel] › parallel/account.spec.ts:13:7 › account › account redirect ───────────────
  188 skipped
Cleaning up project directory and file based variables 00:00
ERROR: Job failed: exit code 1
```

**Comment by mxschmitt** [comment]
`--debug` will launch the browser in headed mode, see [here](https://playwright.dev/docs/debug#run-in-debug-mode-1). It's not intended to be used in CI etc. only locally where its helpful.

If you want to debug CI, we recommend HTML report with Traces enabled: https://playwright.dev/docs/trace-viewer-intro#opening-the-html-report

**Comment by Kuba-Sikora** [comment]
Thank you very much! This has been messing with my head for over 2 days.

**Comment by soupra04** [comment]
hello @mxschmitt  I am having the same issue but I am using bitbucket pipeline, let me show you the .yml file
bitbucket-pipelines.yml
pipelines:
  custom:

    runPlayWrightWithTestSelection: # PlayWright JS tests with TEST case selection
      import : ci-automation:master:runPlayWrightTests

    runPlayWrightWithTagSelection: # PlayWright JS tests with TAG selection
      import : ci-automation:master:runPlayWrightTests

    runPlayWrightWithFailedTests: # Rerun failed test case
      import : ci-automation:master:runPlayWrightTests
import 'dotenv/config';
import { defineConfig, devices } from '@playwright/test';
import path from 'path';
import { libs } from './libs/lib';

// Create timestamped report folder for HTML reports
const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
const reportDir = path.join('reports/playwright-report', `report-${timestamp}`);

// Ensure Zephyr report folder exists
const zephyrDir = path.resolve(__dirname, 'reports', 'zephyr'); // absolute folder
// if (!fs.existsSync(zephyrDir)) {
//   fs.mkdirSync(zephyrDir, { recursive: true });
// }
const zephyrReportPath = path.join(zephyrDir, 'zephyr-results.json'); // absolute file path

// --------------------
// REPORTERS (only logic added)
// --------------------
const reporters: any[] = [
  //['list'],
  //['json', { outputFile: 'result.json' }],
  ['html', { open: 'always', outputFolder: reportDir }],
  ['allure-playwright'],
];

if (process.env.ENABLE_ZEPHYR === 'true') {   // need to add ENABLE_ZEPHYR field in .env file
  reporters.push([
    'playwright-zephyr/lib/src/cloud',
    {
      projectKey: 'PQW',
      authorizationToken:
        "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjb250ZXh0Ijp7ImJhc2VVcmwiOiJodHRwczovL3N0cmF0YXZhci5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI1ZDRlZjY3YjJjMGZlYTBkMDdjYTNjMWQiLCJ0b2tlbklkIjoiZTY2YWM1MWItZDljNi00MmU5LTg4NWEtMjEwOGViYWZjMWY5In19LCJpc3MiOiJjb20ua2Fub2FoLnRlc3QtbWFuYWdlciIsInN1YiI6ImppcmE6ZGRiOTU1OWMtNGNlZi00ZWY2LTk4ZjYtN2FiNTdkODgzZmU0IiwiZXhwIjoxNzg1MDY2MDU1LCJpYXQiOjE3NTM1MzAwNTV9.qnLG-ewUbnpegiIvI_OXjicqYkNGb9P6W05rXrgtCSA",
      reportPath: zephyrReportPath, // use full path
    },
  ]);
}

// --------------------
// EXISTING CONFIG (unchanged)
// --------------------
export default defineConfig({
  timeout: 500000,
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : 1,

  reporter: reporters,

  globalSetup: './integration/sf/globalSetup',

  use: {
    storageState: 'state.chromium.json',
    baseURL: process.env.SF_INSTANCE_URL,
    //headless: !!process.env.CI,
      headless: true,

    trace: 'off',
    video: { mode: 'off' },
    screenshot: { mode: 'off' },
    // launchOptions: process.env.CI
    //   ? {}
    //   : { args: ['--start-maximized'] },
    
    viewport: null,
    

  },

  projects: [
    { name: 'chromium', use: { ...devices['Desktop Chrome'] } },
    // { name: 'firefox', use: { ...devices['Desktop Firefox'] } },
    // { name: 'webkit', use: { ...devices['Desktop Safari'] } },
  ],
});



issue is same 

Looks like you launched a headed browser without having a XServer running.                     ║
║ Set either 'headless: true' or use 'xvfb-run <your-playwright-app>' before running Playwright. ║
║                                                                                                ║
║ <3 Playwright Team
