### ISSUE TITLE
[BUG][pid=113728][err] ../../base/allocator/partition_allocator/partition_root.cc(863) Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14))

### ISSUE THREAD

**Issue by wq1229362515** [microsoft/playwright#26491]
### System info
- Playwright Version: [v1.34.3]
- Operating System: [CentOS Linux release 7.9.2009 (AltArch)]
- Browser: [Chromium]
- Other info:
Linux version 4.18.0-348.20.1.el7.aarch64 
I want run playwright in arm64, so first i install browser, and then run test command, the error occur：
[pid=113728][err] ../../base/allocator/partition_allocator/partition_root.cc(863) Check failed: (internal::SystemPageSize() == (size_t{1} << 12)) || (internal::SystemPageSize() == (size_t{1} << 14))
1.npx playwright  install chromium
2.npx playwright  test 

### Source code

- I think not need the source code, may be is Environmental issues?

**Steps**
- [Run the test]

**Expected**

In x86 my test is normal

**Actual**

The issue has occur.

**Comment by mxschmitt** [comment]
CentOS is not supported, see the list of officially supported operating systems here: https://playwright.dev/docs/intro#system-requirements
