### ISSUE TITLE
[REGRESSION]: webServer stdout always printed

### ISSUE THREAD

**Issue by svetlalev** [microsoft/playwright#26496]
**Context:**
- GOOD Playwright Version: 1.36.1
- BAD Playwright Version: 1.37.0
- Operating System: Mac

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
webServer: {
    command: 'my server setup command',
    url: 'http://127.0.0.1:3001',
    reuseExistingServer: !process.env.CI,
    timeout: 60000
  }
```

**Describe the bug**

I tried updating to 1.37, but with this version if I use webServer in defineConfig it started printing all stdouts for the server.
I tried setting `stdout` to `'ignore'` (even though this should be the default value), but the result is the same. Also tried setting `stderr` to `'ignore'` - same thing.

**Comment by mxschmitt** [comment]
Fixed by https://github.com/microsoft/playwright/pull/26503.
