### ISSUE TITLE
Experimental Playwright grid future

### ISSUE THREAD

**Issue by MindaugasMateika** [microsoft/playwright#26498]
https://github.com/microsoft/playwright/pull/26484

Does that revert mean you will not be pursuing this feature any further? I was planning to play around it by deploying to k8s but noticed that's it is gone in main branch.

**Comment by pavelfeldman** [comment]
It is taking a little more effort than I anticipated, also I figured that I'd rather re-do it in a way where workers are regular playwright server instances, which I now think is not great for k8s application. What's your interest in it, would you like to use it locally or in the cloud? We don't have a clear signal from the community that they want a Playwright Grid in a form of a k8s cluster. It'd be great to see it in a form of a upvoted issue to justify the investment.

**Comment by MindaugasMateika** [comment]
I'd like to use it in the cloud. We have limited resources on CI but much more resources in k8s so I always had an idea to have a lightweight CI job and just use Playwright workers in k8s. I'll create a feature request/issue, let's see if there will be any interest.
