### ISSUE TITLE
[Feature] - Need method to create Page with NewPageOptions from BrowserContext object

### ISSUE THREAD

**Issue by kishorethiru** [microsoft/playwright#26501]
Currently in Playwright, We can create Page object from BrowserContext object but not with PageOptions.
Adding a overloading method would help here

**Comment by mxschmitt** [comment]
There is not such a thing as PageOptions, see [here](https://playwright.dev/docs/api/class-browsercontext#browser-context-new-page) when creating a page, there are no options.

Could you elaborate?

**Comment by kishorethiru** [comment]
While creating object under launch(Browser Object), NewPage with NewPageOptions method is available as below
![image](https://github.com/microsoft/playwright/assets/55927973/f3625522-a383-4275-8e35-c9e78253db89)

Samething if we do it under newContext object NewPage with NewPageOptions method is not available as below
![image](https://github.com/microsoft/playwright/assets/55927973/dcd67082-a1b8-4985-a003-c8db399ccbdf)

I have a scenario where i need to create a context with NewContextOptions and Then create a page with NewPageOptions

**Comment by mxschmitt** [comment]
There is a big difference between [BrowserContext.newPage](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-new-page) and [Browser.newPage](https://playwright.dev/java/docs/api/class-browser#browser-new-page).

See the documentation:

> Creates a new page in a new browser context. Closing this page will close the context as well.

> This is a convenience API that should only be used for the single-page scenarios and short snippets. Production code and testing frameworks should explicitly create [Browser.newContext()](https://playwright.dev/java/docs/api/class-browser#browser-new-context) followed by the [BrowserContext.newPage()](https://playwright.dev/java/docs/api/class-browsercontext#browser-context-new-page) to control their exact life times.

Thats why the BrowserContext options are not available in BrowserContext.newPage.

**Comment by kishorethiru** [comment]
Is there anyway i can load a NewPageOptions while creating page via context  or Just a way to maximize the browser(Currently i m using NewPageOptions to maximize the window alone )?

**Comment by mxschmitt** [comment]
as I said above:

Browser.newPage:
- creates a context
- and then a page with that context

BrowserContext.newPage
- creates a page on that existing context

There is no way to pass the options again, since the context already exists. You either need to pass it earlier when creating the context or re-create the context if you need different options.

Could you maybe try to elaborate a bit more on what you are trying to achieve?

**Comment by kishorethiru** [comment]
` Browser chromium = Playwright.create().chromium().launch(new BrowserType.LaunchOptions()
                .setArgs(List.of("--start-maximized")));

       Browser.NewContextOptions newContext = new Browser.NewContextOptions().setIgnoreHTTPSErrors(true)
                        .setRecordVideoDir(Paths.get("./videos/"));
       BrowserContext context = chromium.newContext(new Browser.NewContextOptions());
       Browser.NewPageOptions pageOptions =  new Browser.NewPageOptions().setViewportSize(null);`

Above is my usage, where i m using LaunchOptions while creating Browser Object and also using NewContextOptions for loading context. 

Now if i want to use the NewPageOptions, there is no way i can pass it via context.newPage();

**Comment by mxschmitt** [comment]
Closing as per above since there are no page options.
