### ISSUE TITLE
[Question] Set Firefox browser window size

### ISSUE THREAD

**Issue by Sneaky-Bot-Dev-Team** [microsoft/playwright#2651]
Could someone please help me set the firefox browser's window size please ?

**Comment by mxschmitt** [comment]
Does this fit for your needs?
https://playwright.dev/#version=v1.1.1&path=docs%2Femulation.md&q=viewport-color-scheme

You can pass it then on each page.

**Comment by Sneaky-Bot-Dev-Team** [comment]
No, I didn't mean to change the viewport/page size but the actual browser window size.

**Comment by pavelfeldman** [comment]
You can pass `{ args: ['-width=1000', '-height=500'] }` to launch. See the [args](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-args) docs.
