### ISSUE TITLE
In @playwright/experimental-ct-svelte, is it possible to pass a Context to a component?

### ISSUE THREAD

**Issue by kno-raziel** [microsoft/playwright#26529]
## Brief intro

I have been playing with _Svelte_ lately, right now I'm exploring how to do testing, I have tried `Vitest` with `@testing-library/svelte` and was able to do some basic stuff but then had some issues when the components that I was testing includes svg and those svg are animated using the _Svelte_ transitions API, the reason seems to be that _JSDOM_ doesn’t support SVG since they don’t implement them. 

So looking at the[ _Playwright_ documentation](https://playwright.dev/docs/test-components) I found this experimental feature which seems promising compared to `Vitest` and `@testing-library/svelte` by the fact that the code runs directly in an browser engine.

## Issue

I did some test and seems promising, but then I found it lacks the support for passing Context to the component. Since in _Svelte_ we cant create components in same file like in _React_, I had to use the workaround of creating a dummy wrapper component were I have defined the Context. Example:

```svelte
<!-- DummyParentWithContext -->
<script lang="ts">
  import Example from '$lib/components/Example/Example.svelte';
  import { setContext } from 'svelte';

  setContext('contextName', { contextProp: 'contextPropValue' });
</script>

<Example />
```

And then in the test use this dummy wrapper instead of testing the component directly.

```ts
// Example.test.ts
import { test, expect } from '@playwright/experimental-ct-svelte';
import DummyParentWithContext from './DummyParentWithContext.svelte';

test.use({ viewport: { width: 500, height: 500 } });

test('Testing Context', async ({ mount }) => {
  const component = await mount(DummyParentWithContext);
  await expect(component).not.toBeEmpty();
});
```

I cant imaging doing this in a library or project that use context heavily 😖

## Requested Feature

My understanding is that the [Svelte API support passing context](https://svelte.dev/docs/client-side-component-api#creating-a-component) and is actually being used by [@testing-library/svelte](https://testing-library.com/docs/svelte-testing-library/api#render) and here is a code example of how is being use by them:

```ts
// Example.test.ts
import { render } from '@testing-library/svelte';
import { describe, expect, it } from 'vitest';
import Example from './Example.svelte';

describe('Example', async () => {
  it('should render', async () => {
    const { container } = render(Example, {
      // Example of passing context to component
      context: new Map(Object.entries({ contextName: { contextProp: 'contextPropValue' } })),
      // know issue with the types of testing library https://github.com/testing-library/svelte-testing-library/issues/212
    } as any);

    expect(container).toBeDefined();
  });
});
```

From what I saw in the types file, the mount options are this and it seems right now context is not supported.

<img width="803" alt="image" src="https://github.com/microsoft/playwright/assets/8211946/e37a2f0a-c833-4575-87c0-58699b564ddb">

 **It is possible to pass context to component?** 🤞

**Comment by sand4rt** [comment]
React, Vue and Solid has support for this trough the `hooksConfig` and the `beforeMount()`: https://playwright.dev/docs/test-components#hooks. It is possible to do something similar for Svelte.
