### ISSUE TITLE
VS Code extension: issues with current working directory and relative paths

### ISSUE THREAD

**Issue by OliverJAsh** [microsoft/playwright#26536]
**Context:**
- Playwright Version: latest
- Operating System: latest macOS
- Node.js version: latest Node stable
- Visual Studio Code version: latest
- Playwright for VSCode extension version: latest
- Browser: All
- Extra:

**Code Snippet**

Full reduced test case: https://github.com/OliverJAsh/playwright-vscode-cwd-issue

The config file lives inside a folder (`./tests`), and we have the following test:

```ts
import { test } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto(
    `data:text/html;charset=utf-8,${encodeURIComponent(
      '<input type="file" />'
    )}`
  );

  const fileChooserPromise = page.waitForEvent('filechooser');

  await page.getByRole('textbox').click();

  const fileChooser = await fileChooserPromise;
  await fileChooser.setFiles('./assets/spacer.gif');
});

```

**Describe the bug**

To run the tests from the command line, we can run this command from the project root:

```sh
yarn playwright test --config tests/playwright.config.ts
```

When we do this, the test succeeds. However, if we try to run the same test from the VS Code extension, the test fails:

```
Running 1 test using 1 worker
  1) [chromium] › example.spec.ts:3:5 › has title ──────────────────────────────────────────────────

    Error: ENOENT: no such file or directory, stat './assets/spacer.gif'
```

The relative path `./assets/spacer.gif` is resolved according to the current working directory. When we invoke Playwright from the command line, the current working directory is the project root, so the relative path is resolved correctly. However, when we invoke Playwright from the VS Code extension, the current working directory is the folder where the config file resides (`./tests` in this example), as per this code:

https://github.com/microsoft/playwright-vscode/blob/1279d218a73a01ffe214f043cabc3a7569e91b6d/src/playwrightTest.ts#L184-L185

Currently the only option I can see is to move my config file to the project root. Ideally Playwright would not mandate the location of the config file.

Perhaps a better solution would be to change the current working directory used by the extension to the workspace folder instead of the config folder?

**Comment by mxschmitt** [comment]
We strongly discourage using relative file paths, instead we recommend absolute ones based on your source file location. See this example:

```ts
await fileChooser.setFiles(path.join(__dirname, './assets/spacer.gif'));
```

**Comment by OliverJAsh** [comment]
Thanks, that's much better. Perhaps the docs should mention this? I looked [here](https://playwright.dev/docs/api/class-filechooser#file-chooser-set-files) but didn't see anything.
