### ISSUE TITLE
[Feature] create a function like select option where even the dropdown is a select or div drop down the user should able to select the values from dropdown

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#26534]
Hi team,
Regarding Dropdown Issue
in some conditions the web elements are changing to select to div and div to select and xpath's structure also changing in this scenario we could not able to utilize the select option because each time some changes happened in the BE the code could not able to detect the dropdowns due to DOM changes could you help enhance the drop down function.

Note : the above scenario we can handle by using code by putting some conditions but the problem is we are unable to predict the changes coming in the DOM to match for exact web elements, any alternative would be more helpful.

Thank You.

**Comment by mxschmitt** [comment]
Since this issue has not a clear action criteria / bug / feature request in it, we can't act on it. For open ended questions, we recommend Discord: https://aka.ms/playwright/discord.
