### ISSUE TITLE
[Feature] Hope the Python version and the Node version could share the same browser

### ISSUE THREAD

**Issue by AuroraTea** [microsoft/playwright#26556]
I'm using the node version first, and when `pnpm add playwright` it download browsers. Then I switched to Python, and it still reminds me to run `playwright install` to download browsers. Single computer.

**Comment by mxschmitt** [comment]
If you use the same versions, then the'll re-use the downloaded browsers.

**Comment by AuroraTea** [comment]
> If you use the same versions, then the'll re-use the downloaded browsers.

Does the same version here mean the language version or the dependency version or the browser version? Are the browsers themselves different for Node and Python? (My idea is that the common parts can be reused, and the parts that are used to operate the browser can be downloaded separately)

**Comment by mxschmitt** [comment]
> Are the browsers themselves different for Node and Python? 

They are the same.

> Does the same version here mean the language version or the dependency version or the browser version?

the Playwright version.

    pip install playwright==1.37.0
    npm install @playwright/test@1.37.1

All minor versions use usually the same browser versions, you can always check the release notes to make sure.

**Comment by AuroraTea** [comment]
> the Playwright version.

Thanks!
After I upgraded Node's dependencies to the same version as Python's, Python works with the browser too.

But I find it strange that I didn't have to relaunch the browser, and that I didn't have to change the Python dependencies. Why does Python go from not working to working? 😂🤣

```Powershell
pnpm update playwright
 WARN  deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
 WARN  deprecated har-validator@5.1.5: this library is no longer supported
 WARN  deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
 WARN  deprecated @npmcli/move-file@1.1.2: This functionality has been moved to @npmcli/fs
Packages: +2 -2
++--
Progress: resolved 266, reused 264, downloaded 2, added 2, done
node_modules/.pnpm/registry.npmmirror.com+playwright@1.37.1/node_modules/playwright: Running install script, done in 16.7s

dependencies:
- playwright 1.32.2
+ playwright 1.37.1
```
