### ISSUE TITLE
[Feature] Expand the playwright trace viewer to highlight browser navigation actions like refresh/goback/gofrward

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#26550]
The trace-viewer currently highlights UI Actions like click/type but does not highlight Page Navigation actions like Go back / Forward

<img width="1528" alt="image" src="https://github.com/microsoft/playwright/assets/37447884/89288c0b-c535-4579-9197-297aed0c0b74">

Would it be possible for the trace viewer to have a second row like the browser has for navigation buttons?

<img width="114" alt="image" src="https://github.com/microsoft/playwright/assets/37447884/66590870-5185-401f-bf22-0ef66ea73461">

This row would highlight any of the navigation buttons if they are used?

<img width="1004" alt="image" src="https://github.com/microsoft/playwright/assets/37447884/6eb90b69-ca88-487d-a5db-c44eaeb661a4">

Happy to work on this if seems good!

**Comment by yury-s** [comment]
Trace viewer shows you a _snapshot_ of the web page around the time when the action was performed. There is not much point in go back / forward from that perspective as those actions would diverge you from the recorded control flow. If you want to explore what would happen on the page if you took another action, pushed go-back you can use [codegen](https://playwright.dev/docs/codegen-intro) or [debug](https://playwright.dev/docs/running-tests#debugging-tests) the test and take manual control at some point.
