### ISSUE TITLE
[REGRESSION]: Trace viewer in version 1.37.1 does not group Console and Network by each action

### ISSUE THREAD

**Issue by abz-aleksey-qa** [microsoft/playwright#26578]
**Context:**
- GOOD Playwright Version: 1.36.2
- BAD Playwright Version: 1.37.1
- Operating System: Linux and Mac

**Describe the bug**

In version 1.36.2  Network and Console in Trace were grouped by each test action. In the latest version, the entire Network and Console for the full test is displayed.

I wanted to clarify whether it was so conceived and whether it is possible to return the previous display?

1.37.1 version
![image](https://github.com/microsoft/playwright/assets/71260728/ba3ebe3e-1413-4f8e-ab78-75f684842558)

1.36.2 version
![image](https://github.com/microsoft/playwright/assets/71260728/8bb1b3c2-5091-4c81-89e0-8ec1f82e2f93)

**Comment by pavelfeldman** [comment]
Network items belonging to the selected action are highlighted when you select the action.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
