### ISSUE TITLE
[Question] How to exclude an autoTestFixture when executing a specific test file using Playwright/Typescript?

### ISSUE THREAD

**Issue by trytoautomate** [microsoft/playwright#26574]
I'm currently using Playwright Test for my automation testing needs and have come across a situation where I need to exclude an autoTestFixture from being executed when running a specific test case involving GraphQL requests.

In my test suite, I have an autoTestFixture that sets up the test environment by navigating to the base URL. However, I have a particular test case that performs GraphQL requests using the gqlServices.sendGqlRequestWithVars function. Since this test case doesn't require the autoTestFixture, I want to exclude it from being executed in this scenario.

Fixture: 
```js
const test = baseTest.extend<
  {
    snapShotSuffix: void;
    env: void;
    autoTestFixture: string;
    gqlServices: GqlServices;
    gqlQueries: GqlQueries;
  }
>({

  autoTestFixture: [
    async ({ page }, use) => {
      await page.goto(env.BASE_URL);
      await use("autoTestFixture");
    },
    { scope: "test", auto: true },
  ]
```
 
Could someone please guide me on how to exclude the autoTestFixture from being executed when running the specific test case involving GraphQL requests? Your help will be greatly appreciated!

Thank you in advance for your assistance.

**Comment by yury-s** [comment]
You can have a separate extension of the baseTest without the auto-fixture:

```js
const testWithoutAutoFixture = baseTest.extend<
  {
    snapShotSuffix: void;
    env: void;
    gqlServices: GqlServices;
    gqlQueries: GqlQueries;
  }
>({ ... });

const testWithAutoFixture = testWithoutAutoFixture.extend<
  {
    autoTestFixture: string;
  }
>({ ... });

  autoTestFixture: [
    async ({ page }, use) => {
      await page.goto(env.BASE_URL);
      await use("autoTestFixture");
    },
    { scope: "test", auto: true },
  ]
```

After that you can use either `testWithAutoFixture` or `testWithoutAutoFixture` to declare your tests. Would that work for you?

**Comment by trytoautomate** [comment]
Yes, it works! Much appreciated
