### ISSUE TITLE
[Feature] Consider adding Browser Server to the Core Concepts docs

### ISSUE THREAD

**Issue by kblok** [microsoft/playwright#2657]
I think it would be helpful to talk about the browser server here https://github.com/microsoft/playwright/blob/master/docs/core-concepts.md

**Comment by aslushnikov** [comment]
@kblok It doesn't feel like a core concept - not many clients actually need it. More like an "advanced" stuff.

I do agree that API description is very concise - maybe enhancing it would help. But it's also pretty self-descriptive, and  so far we haven't seen many questions regarding it. 

I'll close this for now, but we'll appreciate if you can add documentation to cover any confusion you had here!
