### ISSUE TITLE
[BUG] TURNSTILE IFRAME NOT FOUND IN FIREFOX 

### ISSUE THREAD

**Issue by Terminal1337** [microsoft/playwright#26579]
### System info
- Playwright Version: 1.37.0
- Operating System: Windows 10
- Browser: Chromium, Firefox
- Other info: Works with Chrome and not with firefox

### Source code
```python
import asyncio
from playwright.async_api import async_playwright
import time

async def main():
    async with async_playwright() as p:

        browser = await p.firefox.launch(headless=False)
        page = await browser.new_page()
        await page.goto('https://captcha.transfer.wiki',wait_until='networkidle'
                        )
        print(f"PAGE LOADED")
        time.sleep(5)
        print("finding frame")
        for frame in page.frames:
            print(frame.url)
        time.sleep(1000)
        await browser.close()


asyncio.run(main())
```

**Steps**
- When I iterate through page.frames the turnstile frame is not found when firefox is used. However the same thing works for chrome.
- Please Check the Screenshots I have attached for actual output

**Expected**
- Turnstile Iframe url in firefox

**Actual**
![image](https://github.com/microsoft/playwright/assets/95563109/a96fa721-528a-43d9-8c5b-3d88324c4e29)

![image](https://github.com/microsoft/playwright/assets/95563109/eeb7c6c0-0d54-4fba-ac21-18af91aa54d0)

**Comment by yury-s** [comment]
Sounds like the page behavior varies between browsers and the frame which is present in one of them is not served to the other. If you think there is a bug in playwright please file a new report and attach a self-contained example which we could run locally (including the source of the page where it fails).
