### ISSUE TITLE
missing browser libraries for v1.37.0 on Linux(RedHat/Centos8)

### ISSUE THREAD

**Issue by jonasz9** [microsoft/playwright#26585]
Hi,
I'm try to run tests on VM with Centos8 for technology-stack like below:
[Maven]Playwright-Java with Cucumber - Locally tests run perfectly (from IDE or Maven command line).
I get dependencies from Maven:
https://mvnrepository.com/artifact/com.microsoft.playwright/playwright/1.37.0

I get a JAR file with dependencies and deploy it on my VM and install all dependencies successfully.
Then I try to run my tests with i.e. command:
mvn test -D"cucumber.filter.tags=@SingleTest"
Test start, but immediately failing with below errors:
For "chromium" browser:
libraries: libgbm.so.1 libdrm.so.2
![image](https://github.com/microsoft/playwright/assets/29436378/b9d1990d-5f30-47a3-922e-290401ceb524)

And for "firefox":
library: libX11-xcb.so.1
![image](https://github.com/microsoft/playwright/assets/29436378/a996c4e5-01e6-4a1d-9c3a-139d7f7d1d44)

I have two questions, related with this issue:
1. It's possible to include those libraries in playwright main library (for Maven) in near future?
2. If not, then how to install missing dependencies manually:
    - I tried install missing libraries with yum command like below:
        sudo yum install -y libgbm.so.1 libdrm.so.2 libX11-xcb.so.1
      It finished install packages successfully, but result was still the same... Probably, because my maven dependencies are in some 
      tmp/ directory, not default dir/ for yum packages.
      It's possible to install all those missing packages with yum and then copy somehow those missing libraries/packages to maven 
      dependencies? (or this is pointless? and how to do that?) 
    - It's possible to fix dependencies for Maven like with npm/npx:
          npx playwright install-deps
          on Linux?

**Comment by mxschmitt** [comment]
CentOS is not supported, only the Linux distributions listed [here](https://playwright.dev/java/docs/intro#system-requirements) are supported. Closing by that.
