### ISSUE TITLE
[Feature] UI Mode tab title enhancements

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#26581]
Idea:

![telegram-cloud-photo-size-2-5407082896604385184-y](https://github.com/microsoft/playwright/assets/17984549/de5005d3-6ca2-4c97-b61b-8eb72f0ab7e6)

- add the number of console messages
- network messages to these components
- hide attachments tab if there are no attachments

**Comment by mastrzyz** [comment]
Taking a look :)

**Comment by mastrzyz** [comment]
slowly taking a look, React JS noob so if anyone else wants to pick it up I'm fine.

https://github.com/microsoft/playwright/pull/26710

**Comment by pavelfeldman** [comment]
Sorry, not the fan of the UX here!
