### ISSUE TITLE
[Feature] Allow installing browsers from UI mode after update

### ISSUE THREAD

**Issue by pavelfeldman** [microsoft/playwright#26580]

**Comment by NikkTod** [comment]
Is it possible to also add the posibility to perform a version update from UI mode?

**Comment by pavelfeldman** [comment]
> Is it possible to also add the posibility to perform a version update from UI mode?

Let's file it separately - it would change files in the project, so we should handle it with care.

**Comment by pavelfeldman** [comment]
Closed by https://github.com/microsoft/playwright/commit/46e33cd384b48e62889b7cf2cc7ff10951ae9967
