### ISSUE TITLE
Is it possible to make playwright into webassembly?

### ISSUE THREAD

**Issue by kesavkolla** [microsoft/playwright#2658]
I would like to use playwright from other programming language (Python). Is it possible to generate wasm binary from playwright?

**Comment by mxschmitt** [comment]
It's not possible to use WebAssembly for something like that. There are plans, to improve cross-language support of Playwright in the future. Especially with Python, but there is no eta yet.
How would your testing setup / use-case look like?
Would you use pytest for it?

**Comment by pavelfeldman** [comment]
I'm experimenting with the Python3 client, will let you know. Out of curiosity, how does wasm binary help achieving Python? Typically engines that can run wasm can also run JS, which Playwright is compiled into.

**Comment by kesavkolla** [comment]
> It's not possible to use WebAssembly for something like that. There are plans, to improve cross-language support of Playwright in the future. Especially with Python, but there is no eta yet.
> How would your testing setup / use-case look like?
> Would you use pytest for it?

Our usecases mostly include automation. We use web automation for business purpose. We use python as our programming language so would love to see playwright to work with cross programming languages.

**Comment by kesavkolla** [comment]
> I'm experimenting with the Python3 client, will let you know. Out of curiosity, how does wasm binary help achieving Python? Typically engines that can run wasm can also run JS, which Playwright is compiled into.

I was thinking of loading wasm into python and execute it's available methods. I'm seeing more and more uses of wasm as a cross programming language solutions. Recently envoy proxy added support for custom plugins using wasm so we can write custom plugins to envoy using any programming language. Similarly if playwright is available as wasm then any programming language that has ability to load wasm can benefit from it.  It's thought inspired by https://wasmer.io/

**Comment by aslushnikov** [comment]
> It's thought inspired by https://wasmer.io/

@kesavkolla thanks for sharing this! I didn't know about these efforts.

To sum up the discussion: no, we don't compile to WASM, but there's some experimentation with python bindings.
