### ISSUE TITLE
[BUG] Jenkins Windows Agent : Javascript disabled on Jenkins. 

### ISSUE THREAD

**Issue by shakeebatme** [microsoft/playwright#26584]
Trying to run our E2E test case in Jenkins windows agent, when I login to windows machine execute e2e from command prompt the test runs fine. On the same machine when I try to execute on Jenkins I am getting javascript disabled. Please let me know what I am missing.

Reason for this approach: As we don't have sudo access in master node jenkins on container, we had to setup a windows node where we can install chrome, edge, webkit via playwright.

### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 10]
- Browser: [Chromium, Edge, WebKit]
- Other info: Jenkins[2.401.3] 

```js
// playwright.config.ts
export default defineConfig({
  testDir: 'e2e',
  fullyParallel: true,
  forbidOnly: !!process.env['CI'],
  retries: process.env['CI'] ? 0 : 0,
  workers: process.env['CI'] ? 1 : undefined,
  reporter: 'html',

  use: {
    baseURL:
      process.env['ENVIRONMENT'] === '1'
        ? process.env['BASE_URL']
        : 'https://localhost:4200',
    trace: 'retain-on-failure',
    ignoreHTTPSErrors: true,
    video: 'on',
    screenshot: {
      mode: 'only-on-failure',
      fullPage: true,
    },
    javaScriptEnabled: true,
    headless: true,
    testIdAttribute: 'row-id',
  },
  projects: [
    {
      name: 'AuthSetup',
      testDir: 'e2e',
      testMatch: '/auth/auth.setup.ts',
    },
    {
      name: 'Chrome',
      dependencies: ['AuthSetup'],
      use: {
        browserName: 'chromium',
        ...devices['Desktop Chrome'],
        channel: 'chrome',
        storageState: 'e2e/auth/authuser.json',
        launchOptions: {
          args: [
            '--auth-server-allowlist="_"',
            '--disable-web-security',
            '--no-sandbox',
          ],
          chromiumSandbox: false,
        },
      },
    },
    {
      name: 'Edge',
      dependencies: ['AuthSetup'],
      use: {
        browserName: 'chromium',
        ...devices['Desktop Edge'],
        channel: 'msedge',
        storageState: 'e2e/auth/authuser.json',
      },
    },
    {
      name: 'Webkit',
      dependencies: ['AuthSetup'],
      use: {
        ...devices['Desktop Safari'],
        storageState: 'e2e/auth/authuser.json',
      },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test as setup, expect } from '@playwright/test';

const username: string = process.env['USER_NAME'] ?? '';
const password: string = process.env['USER_PASSWORD'] ?? '';
const authFile = 'e2e/auth/authuser.json';

setup('Authenticate User', async ({ page }) => {
  console.log('Running Authenticate User');

  await page.goto('/');
  await page.waitForTimeout(3000);

  if (await page.getByPlaceholder('[yourCDSID]').isVisible()) {
    await page.locator('#userNameInput').fill(username);
    await page.locator('#passwordInput').fill(password);
    await page.locator('#submitButton').click();

    await expect(page.locator('#headerUsername')).toHaveText('XXXX, G');

    await page.context().storageState({ path: authFile });
    console.log('Successfully saved User session');
  } else {
   //For WIA system
    await page.context().storageState({ path: authFile });
    console.log('Successfully saved User session');
    console.log('Could not locate userId and password fields to login');
  }

  await page.waitForTimeout(1000);
  await page.screenshot({ path: 'screenshots/auth_screenshot.png' });
});
```

```

```

**Steps**
- [Run the test]
```
npx playwright test home.spec.ts --project=chrome
```
**Expected**

Successful test execution. 

**Actual**

<img width="547" alt="Screenshot 2023-08-21 at 1 06 53 PM" src="https://github.com/microsoft/playwright/assets/10790497/d52d1a88-d5ba-4938-a2c9-9fe07b82ceb2">

**Comment by yury-s** [comment]
It looks like some enterprise policy kicks in and disables javascript in the browser when you use 'Chrome' channel. See [this note](https://playwright.dev/docs/browsers#enterprise-policy) for more details. Try running with the bundled chromium instead and see if it works?

**Comment by shakeebatme** [comment]
> It looks like some enterprise policy kicks in and disables javascript in the browser when you use 'Chrome' channel. See [this note](https://playwright.dev/docs/browsers#enterprise-policy) for more details. Try running with the bundled chromium instead and see if it works?

please look into attached logs and let me know if I am missing any step.
[jenkins.log](https://github.com/microsoft/playwright/files/12399679/jenkins.log)

**Comment by yury-s** [comment]
The log looks fine, one of the assertions fails for the page:

```
...
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for locator('#headerUsername')
   ...
 ```
As the test passes when you run it manually the failure must have something to do with the environment.

I still see that you use 'chrome' channel to run actual test: `C:\Users\XXXXXX51\AppData\Local\Google\Chrome\Application\chrome.exe` and that is likely constrained by browser policies. Try removing 'channel' option from that flag and see if it helps. Playwright cannot override browser policies set by your company, if you want to avoid the error and keep running with `Google Chrome` rather than bundled `Chromium`, try running on a machine that is free of the corp policies.

**Comment by shakeebatme** [comment]
Thanks for the direction.
