### ISSUE TITLE
[Question]: Unable to detect 'Add Extension' dialog in chrome web store using playwright tools

### ISSUE THREAD

**Issue by LironHaroni** [microsoft/playwright#26582]
Hey all,
I'm trying to download an extension via chrome web store using playwright.
After navigating to the extension download link and clicking on the "Add to Chrome", a dialog/popup shows UP in the page (which is not part of the DOM) that I need to click on in order to allow the download. However I can't seem to interact with this dialog like object using playwright tools, as it is not part of the DOM (I assume).
I tried doing it with expect popup/dialog - but nothing works. 
Can anyone help? 
Thanks!

**Comment by yury-s** [comment]
Playwright does not natively support interactions with browser-level dialogs like the one you encounter when adding extensions via the Chrome Web Store. Such dialogs are outside the web page's DOM and hence can't be interacted with using typical Playwright methods. Playwright focuses on the automation of the web content of the page and this is out of the scope.
