### ISSUE TITLE
[Feature] Support for Flutter/Dart

### ISSUE THREAD

**Issue by andrespd99** [microsoft/playwright#26587]
Is there a possibility to add support to Flutter? Given that it is a pretty popular Framework as of 2023, it'd be interesting if you support it.

**Comment by yury-s** [comment]
Can you explain in more details on what functionality you are looking for?

If you're building a web application using Flutter, you may automate it as any other web app. Playwright focuses primarily on web environments. As such, it doesn't support automating native UI elements which are core to Flutter when it comes to mobile application development.

**Comment by yury-s** [comment]
Closing per the response above, we are not planning to work extended flutter support at this point.

**Comment by josiahsrc** [comment]
Sorry to reopen, but +1 on flutter support. Flutter's built-in integration test system is slow, unreliable, and fairly limited. Having playwright on the flutter toolbelt would be a huge win. Not sure on feasibility, since flutter mostly uses canvas as far as I know :/

**Comment by lsaudon** [comment]
> Sorry to reopen, but +1 on flutter support. Flutter's built-in integration test system is slow, unreliable, and fairly limited. Having playwright on the flutter toolbelt would be a huge win. Not sure on feasibility, since flutter mostly uses canvas as far as I know :/

Check https://maestro.mobile.dev/

**Comment by n0krashy** [comment]
Having playwright supporting flutter will be huge! it is considered the most advanced development tool in 2024 and playwright is as well for web test automation, so would be great if it happened

**Comment by vitalyizak** [comment]
+ 1

**Comment by Jobians** [comment]
No updates?
