### ISSUE TITLE
[BUG] Intermittent failures during Microsoft Edge and Google Chrome installation on Windows Server

### ISSUE THREAD

**Issue by Sid200026** [microsoft/playwright#26591]
### System info
- Playwright Version: [v1.37.0]
- Operating System: [Windows Server 2022 LTSC]
- Browser: [Google Chrome, Microsoft Edge]

### Source code

**Dockerfile**
```dockerfile
FROM mcr.microsoft.com/windows/server:ltsc2022

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';$ProgressPreference='silentlyContinue';"]
USER ContainerAdministrator
ENV NODE_VERSION 18.14.2

WORKDIR /usr/src/app

RUN Invoke-WebRequest $('https://nodejs.org/dist/v{0}/node-v{0}-win-x64.zip' -f $env:NODE_VERSION) -OutFile 'node.zip' -UseBasicParsing ; \
    Expand-Archive node.zip -DestinationPath C:\ ; \
    Rename-Item -Path $('C:\node-v{0}-win-x64' -f $env:NODE_VERSION) -NewName 'C:\nodejs'
RUN [Environment]::SetEnvironmentVariable('Path', $env:Path + ';C:\nodejs', 'Machine')

RUN Set-ExecutionPolicy -ExecutionPolicy Unrestricted

COPY package.json .

RUN npm install
RUN npx playwright install
RUN npx playwright install-deps

CMD npm run install-browser
```

**package.json**
```json
{
  "name": "windows-browser-installation-failures",
  "scripts": {
    "install-browser": "npx playwright install chrome && npx playwright install msedge"
  },
  "dependencies": {
    "@playwright/test": "1.37"
  }
}
```

**Steps**
- `docker build -t oss-windows-installation -f .\Dockerfile .`
- `docker run oss-windows-installation`
- Run the docker image multiple times

**Expected**

Google Chrome should be installed while edge installation should fail since it's already installed on windows server 2022.

```
> install-browser
> npx playwright install chrome && npx playwright install msedge

Downloading Google Chrome
Installing Google Chrome

ProductVersion   FileVersion      FileName                                     
--------------   -----------      --------                                     
116.0.5845.97    116.0.5845.97    C:\Program Files\Google\Chrome\Application...


Failed to install browsers
Error: 
╔═════════════════════════════════════════════════════════════════╗
║ ATTENTION: "msedge" is already installed on the system!         ║
║                                                                 ║
║ "msedge" installation is not hermetic; installing newer version ║
║ requires *removal* of a current installation first.             ║
║                                                                 ║
║ To *uninstall* current version and re-install latest "msedge":  ║
║                                                                 ║
║ - Close all running instances of "msedge", if any               ║
║ - Use "--force" to install browser:                             ║
║                                                                 ║
║     npx playwright install --force msedge                       ║
║                                                                 ║
║ <3 Playwright Team                                              ║
╚═════════════════════════════════════════════════════════════════╝
```

**Actual**

For approximately 30-40% of the cases (After 300 runs), installation fails for either chrome or edge without any proper error.

```
> install-browser
> npx playwright install chrome && npx playwright install msedge

Downloading Google Chrome
Installing Google Chrome
ERROR: failed to install Google Chrome
Failed to install browsers
Error: Failed to install chrome
```

If we switch the order of installation i.e. `npx playwright install msedge && npx playwright install chrome`, we get the following error intermittently.

```
> install-browser
> npx playwright install msedge && npx playwright install chrome

Downloading Microsoft Edge
Installing Microsoft Edge
ERROR: failed to install Microsoft Edge
Failed to install browsers
Error: Failed to install msedge
```

**Comment by mxschmitt** [comment]
I tried to reproduce it by spawning a new container and installing Google Chrome 100 times, unfortunately I was not able to reproduce it.

Do you install Google Chrome always when the container gets started or when you build the Container?

Since your repro shows it happens when running the container rather than during the build process.

**Comment by aslushnikov** [comment]
@Sid200026 without any logs we can't do much. Any chance you can provide us with logs so that we know what's the error?

**Comment by aslushnikov** [comment]
> What should be the value of the env variable temp?

@Sid200026 This yields the configured temporary location on your system. It should be already defined on your system, so feel free to just run the script and check for errors. 

> There's a scope to move branded browser installation to docker build step if it's safe to say playwright can support latest stable chrome and edge release for the recent playwright versions.

Each playwright release is being tested against the current stable Chrome & Edge versions.

**Comment by Sid200026** [comment]
> Each playwright release is being tested against the current stable Chrome & Edge versions.

When a new stable version of edge or chrome is released, what happens to the installation process for older playwright versions. I don't see the chrome or edge version being pinned during installation. So wouldn't older playwright versions start downloading new stable releases which they aren't tested against?

`$url = 'https://dl.google.com/tag/s/dl/chrome/install/googlechromestandaloneenterprise.msi';`
