### ISSUE TITLE
[Question] TypeScript can't compile

### ISSUE THREAD

**Issue by luka-dev** [microsoft/playwright#2659]
Hi, i am making 'task' server, based on playwright and using TypeScript in my project.

Problem is - when i add any import from playwright, 'tsc' command start pulling into me alot of errors.

> \> tsc
> node_modules / playwright / types / types.d.ts: 41: 33 - error TS2304: Cannot find name 'Node'.
> 41 type SmartHandle <T> = T extends Node? ElementHandle <T>: JSHandle <T>;
>                                    ~~~~
> 
> node_modules / playwright / types / types.d.ts: 42: 42 - error TS2304: Cannot find name 'HTMLElementTagNameMap'.
> 
> 42 type ElementHandleForTag <K extends keyof HTMLElementTagNameMap> = ElementHandle <HTMLElementTagNameMap [K]>;
>                                             ~~~~~~~~~~~~~~~~~~~~ ~
> 
> node_modules / playwright / types / types.d.ts: 42: 81 - error TS2304: Cannot find name 'HTMLElementTagNameMap'.
> 
> 42 type ElementHandleForTag <K extends keyof HTMLElementTagNameMap> = ElementHandle <HTMLElementTagNameMap [K]>;
>                                                                                    ~~~~~~~~~~~~~~~~~~~~ ~

And, much more lines .....
May some body know, what is happend? And how to fix it.

**Comment by mxschmitt** [comment]
Which TypeScript and Playwright version are you using? And the `tsconfig` would be very helpful, probably you have the `compilerOptions.lib` option set.

**Comment by luka-dev** [comment]
TypeScript - 3.8.3
playwright - 1.1.1
compilerOptions.lib - "es6"

**Comment by mxschmitt** [comment]
Try to set it it `["es6", "dom"]` which should fix it. (If not, try to also add `"DOM.Iterable"`)

**Comment by luka-dev** [comment]
Yeah, adding `"dom"` helped me! Thank you

**Comment by vity455771** [comment]
[]()
