### ISSUE TITLE
[BUG] Browser downloads are very slow

### ISSUE THREAD

**Issue by michal-kralik** [microsoft/playwright#26607]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Ubuntu 22.04]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

package.json
```
{
  "devDependencies": {
    "@typescript-eslint/parser": "^6.3.0",
    "dotenv": "^16.1.4",
    "eslint": "^8.47.0",
    "eslint-config-airbnb-base": "^15.0.0",
    "eslint-config-airbnb-typescript": "^17.1.0",
    "eslint-plugin-playwright": "^0.15.3"
  },
  "dependencies": {
    "@playwright/test": "^1.37.0",
    "shelljs": "^0.8.5"
  }
}
```

**Steps**
- Run `npm ci` with the provided package.json

**Expected**

Download of the browser binaries is fast

**Actual**

The download of binaries is very slow.
The connection is 1gbps, yet the download of each binary takes about 120-150 seconds
Here are the links used for reference

https://playwright.azureedge.net/builds/chromium/1076/chromium-linux.zip
https://playwright.azureedge.net/builds/firefox/1422/firefox-ubuntu-22.04.zip
https://playwright.azureedge.net/builds/webkit/1883/webkit-ubuntu-22.04.zip

We see this behavior consistently.
During download fast.com shows 700-800mbps speed.

**Comment by yury-s** [comment]
We could probably adjust CDN parameter to make it faster.

**Comment by lgarron** [comment]
I'm seeing the same thing:

```shell
> time npx playwright install --with-deps
Removing unused browser at /Users/lgarron/Library/Caches/ms-playwright/chromium-1048
Removing unused browser at /Users/lgarron/Library/Caches/ms-playwright/ffmpeg-1008
Removing unused browser at /Users/lgarron/Library/Caches/ms-playwright/firefox-1378
Removing unused browser at /Users/lgarron/Library/Caches/ms-playwright/webkit-1792
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
128.1 Mb [====================] 100% 0.0s
Chromium 117.0.5938.62 (playwright build v1080) downloaded to /Users/lgarron/Library/Caches/ms-playwright/chromium-1080
Downloading Firefox 117.0 (playwright build v1424) from https://playwright.azureedge.net/builds/firefox/1424/firefox-mac-13-arm64.zip
71.1 Mb [====================] 100% 0.0s
Firefox 117.0 (playwright build v1424) downloaded to /Users/lgarron/Library/Caches/ms-playwright/firefox-1424
Downloading Webkit 17.0 (playwright build v1908) from https://playwright.azureedge.net/builds/webkit/1908/webkit-mac-13-arm64.zip
60.7 Mb [====================] 100% 0.0s
Webkit 17.0 (playwright build v1908) downloaded to /Users/lgarron/Library/Caches/ms-playwright/webkit-1908

________________________________________________________
Executed in  162.21 secs    fish           external
   usr time   10.39 secs   55.00 micros   10.39 secs
   sys time    6.64 secs  937.00 micros    6.64 secs
```

I'm currently on WiFi in a location where I reliably get 300Mbps download, but these downloads averaged out to only ≈50Mbps.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by rahnas** [comment]
This issue still exists as of now. 6k seconds and still only at 60%. Slowest download im doing since years now.

**Comment by GengJulian** [comment]
This issue is still exists.

**Comment by vinhqdang** [comment]
This issue still exists - it is very slow, more than 2 hours in my 1GBps Ethernet connection

**Comment by Bitnagar** [comment]
Really slow downloads! 

<img width="1506" height="272" alt="Image" src="https://github.com/user-attachments/assets/6219ff0e-27f8-45d8-87d2-d92783436bf9" />

**Comment by klepikovd** [comment]
+

**Comment by harsh-mishra-fravity** [comment]
What would you expect from microslop.....

**Comment by harsh-mishra-fravity** [comment]
Microslop is it part of Winblows 69
