### ISSUE TITLE
[internal] make every package depend on `playwright`

### ISSUE THREAD

**Issue by dgozman** [microsoft/playwright#26614]
- [x] (v1.38) Introduce `@playwright/browser-chromium`, `@playwright/browser-webkit`, `@playwright/browser-firefox`.
- [x] (v1.38) Make `playwright` not install browsers.
- [x] (v1.38) Create migration writeup for `playwright` package.
- [x] (v1.38) Move code from `playwright-test` to `playwright`, make `@playwright/test` reexport everything from `playwright` - https://github.com/microsoft/playwright/pull/26946
- [x] (v1.38) Make `playwright-ct-core` depend on `playwright` instead of `@playwright/test`

**Comment by aslushnikov** [comment]
For the record: add a plan of action for this.

**Comment by dgozman** [comment]
### Installation changes in `playwright` package

Note: these changes only affect the `playwright` package and do not affect `@playwright/test` or any other packages.

**v1.37 and earlier**

`playwright` package was downloading browsers during `npm install`.

**v1.38 and later**

`playwright` package does not download browsers during `npm install`, now aligned with `@playwright/test`.

**Migration option 1**

Run `npx playwright install` to download browsers after `npm install`. For example, in your CI configuration:

```yml
- run: npm ci
- run: npx playwright install --with-deps
```

**Migration option 2**

Add `@playwright/browser-chromium`, `@playwright/browser-firefox` and `@playwright/browser-webkit` as a dependency. These packages download respective browsers during `npm install`. Make sure you keep the version of all playwright packages in sync:

```json
// package.json
{
  "devDependencies": {
    "playwright": "1.38.0",
    "@playwright/browser-chromium": "1.38.0",
    "@playwright/browser-firefox": "1.38.0",
    "@playwright/browser-webkit": "1.38.0"
  }
}
```
