### ISSUE TITLE
`--disable-web-security` seems does not work

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2661]
I have a context
```
const browser = await playwright['chromium'].launch({
    args: [
    '--disable-web-security', //Don't enforce the same-origin policy. (Used by people testing their sites - https://peter.sh/experiments/chromium-command-line-switches)
    ],
    headless: false
  });
  const page = await browser.newPage()
  await page.goto('https://host.com/frames.html')
```
iframes.html
```
<html>
    <head>
        <title>Frames</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    </head>
    <frameset cols="50%, 50%">
        <frame src="https://anotherhost.com"/>
    </frameset>
</html>
```
=> the `https://anotherhost.com` does not load in the frame, do you have any idea?

**Comment by aslushnikov** [comment]
@phileba the `--disable-web-security` worked for me just fine with playwright 1.1.1. Here's my snippet:

```js
const {chromium} = require('playwright');

(async () => {
  const browser = await chromium.launch({
    args: [
       '--disable-web-security',
    ],
  });

  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://example.com');
  console.log(await page.evaluate(() => fetch('https://bing.com').then(r => r.status).catch(e => "FAILED - NO CORS")));
  await browser.close();
})();
```

Note: with `--disable-web-security`, i'm able to fetch `https://bing.com`, and I can't do this without the flag.
So what doesn't work for you? Can you share your snippet so that we can look into it?

**Comment by phileba** [comment]
@aslushnikov my code snippet is on my question

**Comment by aslushnikov** [comment]
@phileba Ah, this is actually a chromium bug: `--disable-web-security` no longer disables checks for `x-frame-options`.

See https://crbug.com/857032; closing this in favor of upstream bug.

**Comment by yusoof-pret** [comment]
How to set this in the playwright.config.ts to disable the web security when browser launch

**Comment by rohithbb433** [comment]
> How to set this in the playwright.config.ts to disable the web security when browser launch

Even I have this doubt. Can someone suggest how we can disable it in playwright.config.ts file

**Comment by jake-b-story** [comment]
@yusoof-pret and @rohithbb433 

To set this within the playwright.config.ts file, I believe it will look like:
```node
const config: PlaywrightTestConfig = {
  projects: [
    {
      name: 'chromium',
      use: {
        launchOptions: {
          args: ['--disable-web-security'],
        }
      },
    }
  ]
}
```
