### ISSUE TITLE
[BUG] Can we use Mutation observer to use in our test to detect DOM mutation, need to ensure that the rendering has settled somehow

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26618]
### System info
- Playwright Version: ^1.36.2
- Operating System: Mac
- Browser: All
- Other info:

### Source code

When we perform asynchronous actions that will result in content being added to or removed from the DOM (network request, ui event, etc.), we need to wait for the asynchronous action to settle before we can assert that the resulting DOM content is what we expect. That might lead one to think they need to wait for network calls to resolve, or for certain callbacks to fire before they can query the DOM and assert that their view is as expected, however this approach would discount the rendering time between when the new data or state is received and when the DOM gets updated with new the new content (think SPA-like environments). 

A more complete approach would be to perform the action, **wait for the expected network call or callback or whatever to fire, and also listen for a resulting DOM mutation to occur on some sub-tree of the DOM before asserting that our action had its intended effect.** 

This method ensures that don’t query the DOM too early before our app has had time to render its output. It might be tempting to just ask the user to query the DOM for the expected output on some timeout, however in some testing scenarios the exact output is unknown. For example, we may have a test that checks that the result of a query is a view with a table of data at least n elements long, however the test can’t rely on the exact number of rows or exact content of the cells to be stable. Because those pieces are unknown, it’s possible that this new table has the exact same shape and/ or cell content as a previously rendered table. In this case, we need some way aside from querying the DOM to determine that we’re looking at a fresh render before we make our assertions. 

Wait for network calls - using page.waitForResponse or page.route()
and Can you please advise how to detect DOM mutation before asserting?

or how playwright is handling this specific scenario? is this something that playwright already handles?

Would it make sense in a post-fetch/ajax/SPA/MutationObserver world to build a playwright API around this sort of app behavior? Or is this just something we should hand-roll ourselves? 

If so do you know of any good examples of this kind of thing in the wild?

**Comment by yury-s** [comment]
You can use `MutationObserver` inside the page to get notified about certain changes:

```js
await page.getByTestId('my-element').evaluate((div) => {
  return new Promise(resolve => {
    new window.MutationObserver((mutationsList, observer) => {
      // use your condition here
      if (div.childElementCount >= 2)
        resolve();
    }).observe(div, { childList: true });
  });
});
```

Alternatively, you can call [waitForFunction()](https://playwright.dev/docs/api/class-page#page-wait-for-function) to wait until a certain condition is met within the page.

Would that work for you?

**Comment by pavelfeldman** [comment]
You should [web assertions](https://playwright.dev/docs/test-assertions#auto-retrying-assertions) instead. Instead of waiting for DOM to settle, you specify your expectations and Playwright waits until your expectations are met automatically.

**Comment by InduKrish** [comment]
Sometimes our testing output is dynamic, and we cant specify expectations.

In some testing scenarios the exact output is unknown. For example, we may have a test that checks that the result of a query is a view with a table of data at least n elements long, however the test can’t rely on the exact number of rows or exact content of the cells to be stable. Because those pieces are unknown and dynamic, it’s possible that this new table has the exact same shape and/ or cell content as a previously rendered table. In this case, we need some way aside from querying the DOM to determine that we’re looking at a fresh render before we make our assertions.

in this case, we want to make sure that DOM is settled as we don't know in advance the data for performing web assertions.., Can you please advise?


I am trying use page.route() to capture network logs before making assertion, and after waiting for network calls, also want to make sure that DOM is updated with the network response, that is when we want to wait/listen for a DOM mutation,  Please advise your thoughts.

**Comment by yury-s** [comment]
> in this case, we want to make sure that DOM is settled as we don't know in advance the data for performing web assertions.., Can you please advise?
> 
> I am trying use page.route() to capture network logs before making assertion, 

If you know that a request is going to be sent and the response will contain the able data, you can use the server response  to construct web assertion (as you should be able to learn table size from the response). Alternatively, you can get the server to return a more predictable data for the testing purposes. There is no one-size-fits-all solution.

> and after waiting for network calls, also want to make sure that DOM is updated with the network response, that is when we want to wait/listen for a DOM mutation, Please advise your thoughts.

You can do something like in [the comment above.](https://github.com/microsoft/playwright/issues/26618#issuecomment-1688984161).

Closing as there is no action to be done on the playwright side.
