### ISSUE TITLE
APIResponse.json - is incorrectly defined

### ISSUE THREAD

**Issue by szagi3891** [microsoft/playwright#26625]
```
APIResponse.json(): Promise<any>
```

It would be better if this function was defined like this:

```
APIResponse.json(): Promise<unknown>
```

Could you please change the definition of this type ? 
Using any in a project, as you know leads to hidden errors that TypeScript cannot detect

**Comment by yury-s** [comment]
Agreed that it would be more appropriate to have `unknown` as the return type here but that ship has sailed and at this point we cannot just change the type to a more restrictive one as it would break existing clients. We can make this change if/when we bump major version of the API. Closing this request for now as we are not planning to do it in v1.*

**Comment by szagi3891** [comment]
Well that's a weak situation. It doesn't make sense any in typescript, because now every library developer hides behind the fact that they can't introduce unknown in their interfaces because it will break compatibility. 

We must be brave in changes to improve typing
