### ISSUE TITLE
Do we have method `page.authenticate(authOptions)`

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2662]
Do we support a method `page.authenticate(authOptions)`?

**Comment by mxschmitt** [comment]
You can set http credentials for direct browser auth popups (basic auth, digest auth) on context level: https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsernewcontextoptions--options-httpcredentials

**Comment by bvanderneut** [comment]
I guess the link is outdated and I think this is the new url:
[https://playwright.dev/docs/network#http-authentication](https://playwright.dev/docs/network#http-authentication)
