### ISSUE TITLE
[BUG] Getting Error: Protocol error (Target.setAutoAttach): Target closed.

### ISSUE THREAD

**Issue by manisshaa** [microsoft/playwright#2663]
Getting Error: Protocol error (Target.setAutoAttach): Target closed.

- Playwright Version: [1.0.1]
- Operating System: [Linux]
- Node version: [e.g. 10.12, 10.14]
- Browser: [Chromium]
- Extra: [I'm running the framework on a container using rancher-pipeline]

The code is as follows:

     let is_headless =  process.env.headless_testing && process.env.headless_testing.toLowerCase() == "yes"
        ? true
        : false;

    let test_browser = process.env.test_browser
      ? process.env.test_browser.toLowerCase()
      : "chromium";

    let browser = await playwright[test_browser].launch({headless: is_headless, args: []});
    let context = await browser.newContext({
      viewport: null, 
      ignoreHTTPSErrors: true,
      httpCredentials:{
        username: username,
        password: password,
      }
    });
    let page = await context.newPage();

When I'm running my code on kubernetes environment, I'm getting the following error: Error: Protocol error (Target.setAutoAttach): Target closed.

The same code works fine when I run it on  my local windows machine both on headless and headful mode

**Comment by mxschmitt** [comment]
Which Docker base image are you using? Could you try to use [this](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) (official) as a base image until there will be the official one on Docker Hub?

**Comment by manisshaa** [comment]
I'm using https://hub.docker.com/r/qawolf/playwright-ci as of now. I'll try the official image.Thanks :)

**Comment by manisshaa** [comment]
> Which Docker base image are you using? Could you try to use [this](https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic) (official) as a base image until there will be the official one on Docker Hub?
> 
> Usually this error means, that not all needed dependencies are installed.

I created a new image from the official docker file, but still getting the same issue.

**Comment by arjun27** [comment]
Hi @manisshaa – can you run the script with `DEBUG=pw:*` as the environment variable?
