### ISSUE TITLE
[BUG] Selected Test is outside the default profile but only when running individual tests

### ISSUE THREAD

**Issue by AlexDavies8** [microsoft/playwright#26649]
**Context:**
- Playwright Version: 1.37.1
- Operating System: Windows
- Node.js version: v16.20.1
- Visual Studio Code version: 1.81.1
- Playwright for VSCode extension version: v1.0.15
- Browser: All / n/a

**Describe the bug**

I have created a wrapper function around Playwright's test so that it can be run multiple times with different data easily. This all works perfectly, except when using the VSCode extension and attempting to run a single test from within a test file. If I run all tests, it works as expected, but if I run individual tests, I receive the following warning: `Selected test is outside of the Default Profile (config). Please make sure you select relevant Playwright projects in the "Select Configuration…" drop down located next to Run / Debug Tests toolbar buttons.`

![image](https://github.com/microsoft/playwright/assets/52012013/29b57460-6bad-46cf-815d-2f50affdec01)

Clearly, this isn't a configuration issue, as the tests run fine if I run the whole file.
Note that the actual place that playwright's test function is called is in a separate `dynamic-data.ts` file, so that might be part of what's causing it to do this.

Interestingly, the UI mode accessible via `npx playwright test --ui` works fine, with the small annoyance that the code/test preview shows to `dynamic-data.ts` file instead of the call to my wrapper, but I would expect that to be the case anyway.

**Code Snippet**
Here is an excerpt from `dynamic-data.ts` so that you can see how I'm wrapping the function (I don't think that `beforeEach` hooks can run the same test multiple times, so I think I'm forced to do some of this ugliness to wrap the function):
```typescript
import { test as base } from '@playwright/test';

export const registerData = (generators, data, baseTest = base) => {
    let instanceData = {};

    const test = (title: string, testFunction, limitData) => {
        // Don't include data that's not required for this specific test
        const filteredData = Object.fromEntries(Object.entries(data).filter(([key]) => !!limitData?.includes(key)));
        if (!limitData || !limitData.length) return baseTest(title, testFunction); //Run once if no data
        // Get all required permutations of test data
        const permutations = getTestData(filteredData, generators);
        let variation = 0;
        baseTest.beforeEach(async ({ }) => { // Assign values to data object
            const permutation = permutations[variation];
            permutation.forEach(({ key, value }) => permutation[key] = value);
            variation++;
        });
        baseTest.describe(title, () => {
            for (let i = 0; i < permutations.length; i++) {
                baseTest(`Variation ${i + 1}`, testFunction); // Playwright's test function is called here
            }
        });
    }
    Object.assign(test, baseTest); // Copy over methods such as test.fixme and test.describe

    return {
        data: instanceData,
        test: test
    };
}
```
It is then used as follows:
```typescript
// Inside main.spec.ts
const { test, data } = registerData(baseDataTypes, {
    postText: "paragraph",
    commentText: "paragraph"
}, baseTest);

test("Create Post", ({ page }) => {
    // Do something with data.postText
}, ["postText"]]); // Only use postText for this test
```

**Comment by yury-s** [comment]
Please attach a full self-contained demo that we could run locally.

**Comment by AlexDavies8** [comment]
Not sure what the standard way of sharing this would be, but here is a github repo containing an example with reproduction instructions: https://github.com/AlexDavies8/playwright-demo
It sometimes gives a different error (`No Tests Found`), but has the same end result of not being able to run individual tests. I think it switches from an error to a warning after you've run all tests at least once.

**Comment by AlexDavies8** [comment]
It appears that the warning appears because of `_narrowDownProjectsAndLocations` inside `extension.ts` inside of the vscode extension. Currently, it only checks if the current file is part of the project's test files, but it should probably check if any parents are as well. The following edit to the code seems to fix this.
```typescript
// src/extension.ts replace lines 452-459
const projectsWithFile = projects.filter(project => {
  for (const file of project.files.keys()) {
    let currentItem: vscodeTypes.TestItem | undefined = item;
    while (currentItem) {
      if (file.startsWith(currentItem.uri!.fsPath))
        return true;
      currentItem = currentItem.parent;
    }
  }
  return false;
});
```
However, this doesn't fix the root of the problem. It appears that Playwright itself is throwing `Error: No tests found` from within `packages\playwright-test\src\runner\tasks.ts` anyways. I can only assume that the vscode extension is running the tests differently to how it would be done via the command line, as `npx playwright test -g "Test Name"` works fine.

**Comment by yury-s** [comment]
Wrapping `test` function is not supported by the VS Code extension. Please use UI mode which has better support for it.

There are no plans to change that in the near future, so closing this issue.
