### ISSUE TITLE
[Question]Can I run playwright in a react app?

### ISSUE THREAD

**Issue by NareshMurthy** [microsoft/playwright#2664]
I am trying to run playwright in my react app whenever there is a button click.
This is the error I get when I import playwright.<br>
```./node_modules/playwright/lib/server/processLauncher.js
Module not found: Can't resolve 'readline' in '/Users/xxxx/node_modules/playwright/lib/server'```

**Comment by mxschmitt** [comment]
Playwright needs access to the host system with Node.js to start the browsers. React on the other hand will be usually bundled with Webpack which runs in the browser, which can't work. So you either need an API for that with e.g. an Express webserver or you use something like Next.js and their serverless functions/getServerSideProps to execute it on the backend.

**Comment by NareshMurthy** [comment]
Thanks @mxschmitt
I'll give it a try with Next

**Comment by mxschmitt** [comment]
> Thanks @mxschmitt
> I'll give it a try with Next

I can recommend [this](https://github.com/JupiterOne/playwright-aws-lambda) if you want to use it with a Serveless function, did it myself a few weeks ago.
