### ISSUE TITLE
[BUG] Playwright 1.37 & Debian 12 - Using libsoup2 and libsoup3 in the same process is not supported

### ISSUE THREAD

**Issue by gabriel-pq** [microsoft/playwright#26653]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Debian 12]
- Browser: [Safari]
- **Important info:** With 1.37.1 + Debian 11 everything was great!

**Steps**
The scenario is super simple.
**Where do I run the tests?**
I have a custom Node18 Docker container where I execute `pnpm exec playwright install --with-deps`, then I run a few visual regression tests against all browsers[Chrome, Firefox, Edge and Safari] with the most basic config.

**Expected**
The test against Safari should pass.

**Actual**

```
Error: browserType.launch: Browser closed.
 120.6482s       ==================== Browser output: ====================
 120.6482s        <launching> /usr/playwright-browser-cache/webkit-1883/pw_run.sh --inspector-pipe --headless --no-startup-window
 120.6483s       <launched> pid=8740
 120.6483s      [pid=8740][err] 
 120.6483s      [pid=8740][err] (MiniBrowser:8745): GStreamer-WARNING **: 12:53:48.965: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
 120.6483s       [pid=8740][err] 
 120.6483s       [pid=8740][err] (MiniBrowser:8745): libsoup-ERROR **: 12:53:49.268: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
 120.6483s      [pid=8740][err] /usr/playwright-browser-cache/webkit-1883/pw_run.sh: line 21:  8745 Trace/breakpoint trap   (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"
 120.6483s    =========================== logs ===========================
 120.6483s      <launching> /usr/playwright-browser-cache/webkit-1883/pw_run.sh --inspector-pipe --headless --no-startup-window
 120.6483s    <launched> pid=8740
 120.6484s      [pid=8740][err] 
 120.6484s      [pid=8740][err] (MiniBrowser:8745): GStreamer-WARNING **: 12:53:48.965: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
 120.6484s      [pid=8740][err] 
 120.6484s      [pid=8740][err] (MiniBrowser:8745): libsoup-ERROR **: 12:53:49.268: libsoup2 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
 120.6484s     [pid=8740][err] /usr/playwright-browser-cache/webkit-1883/pw_run.sh: line 21:  8745 Trace/breakpoint trap   (core dumped) WEBKIT_FORCE_COMPLEX_TEXT="1" "$MINIBROWSER" "$@"

**Comment by gabriel-pq** [comment]
Sure, that's absolutely fine with me! Give me a shout and will do the test 🚀 

But if I got your message right Debian 12 could be safe by inclusion? (as you sort out a fix for Debian 11)

**Comment by mxschmitt** [comment]
I actually had a typo, fixed it above.

The new version is now available in Canary, would be amazing if you could test it, thanks!

https://playwright.dev/docs/canary-releases

**Comment by gabriel-pq** [comment]
**System info**

> Playwright Version: [v1.38.0-alpha-aug-29-2023]
> Operating System: [Debian 12]
> Browser: [Safari]

<img width="762" alt="image" src="https://github.com/microsoft/playwright/assets/85311517/2988e191-524e-479b-8e1a-8757cd750245">

@mxschmitt it worked like a charm!

Browsers were downloaded successfully 🟢 
Dependencies were downloaded successfully 🟢 
Tests ran without impediments 🟢

**Comment by mxschmitt** [comment]
Amazing news, closing then and thanks for reporting and testing!
