### ISSUE TITLE
[BUG] --grep-invert isnt working for avoiding multiple test files

### ISSUE THREAD

**Issue by SalmaAssem2020** [microsoft/playwright#26651]
Hello,

Um trying to use --grep-invert in the running command to prevent test files to run:
Ex: npx playwright test --grep-invert"Test File" 

its working as expected, but i cant find a way to add multiple test files names to grep-invert?
Any one advise please?

**Comment by yury-s** [comment]
Use pipe `|` for or condition:

```sh
npx playwright test --grep-invert='(should not uncheck)|(box smoke)'
```
