### ISSUE TITLE
[BUG] beforeAll and afterAll hooks ignore conditional test skip based on a custom parameter added through a fixture

### ISSUE THREAD

**Issue by pavel-casparov** [microsoft/playwright#26667]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [macOS 13.2]
- Browser: [All, Chromium, Firefox, WebKit]

**Link to the GitHub repository with the repro**
https://github.com/pavel-casparov/playwright-not-skipping-hooks-example

**Description**
I've added a custom flag to the fixture which I want to use as a condition to skip tests expecting it will take affect on beforeAll and afterAll hooks, however reality shows that this expected behavior doesn't happen, however if conditionally skipping tests based on OOTB parameters such us browserName, both beforeAll and afterAll hooks aren't triggered, which looks like a proper behaviour.

I tried to create as simple repro example as possible, please take a look, there are 2 spec files, one implementing skipping on a parameter called skipTestCondition and another one on browserName

**Steps**
- npm i
- npx playwright install
- npm run test

**Expected**

no beforeAll() and afterAll() hooks are triggered when the test is skipped conditionally based on skipTestCondition parameter from the fixture

**Actual**
beforeAll() and afterAll() hooks are triggered

```npm run test

> playwright-example@1.0.0 test
> npx playwright test


Running 4 tests using 1 worker
….spec.ts:15:11 › Skip based on custom parameter › Level 2 › Level 3 › has title
================= I'm beforeAll() =================
================= I'm afterAll() =================
  4 skipped

**Comment by yury-s** [comment]
`browserName` is a [worker scoped](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) fixture, whereas `skipTestCondition` is test scoped. Changing your fixture definition as below will align their behavior:

```js
export const test = base.extend<{}, TestOptions>({
    skipTestCondition: [true, { scope: 'worker', option: true }]
});
```
Will that work for you?

**Comment by pavel-casparov** [comment]
this way it is working, thank you for explanation. However now I require all other custom things within my fixture to be defined for `scope: `worker``

```typescript
import { test as base } from '@playwright/test';

export type TestOptions = {
  skipTestCondition: boolean;
  anotherOne: string;
}

export const test = base.extend<{key:string, value:any},TestOptions>({
    skipTestCondition: [true, { scope: 'worker', option: true }],
    anotherOne: ['', { scope: 'test', option: true }] // error here on scope : `test`
});

export const expect = test.expect;
```

The error: 
```Type '"test"' is not assignable to type '"worker"'
test.d.ts(3379, 57): The expected type comes from property 'scope' which is declared here on type '{ scope: "worker"; auto?: boolean | undefined; option?: boolean | undefined; timeout?: number | undefined; }'
(property) scope: "worker"

Is there a way to mix it in any way?

**Comment by pavel-casparov** [comment]
Managed to get over it. Please check https://github.com/pavel-casparov/playwright-not-skipping-hooks-example/tree/working-example-with-worker-and-test-fixtures for a working example.
