### ISSUE TITLE
[BUG] Can't install playwright on ubuntu

### ISSUE THREAD

**Issue by manisshaa** [microsoft/playwright#2666]
**Context:**
- Playwright Version: [1.1.1]
- Operating System: [Linux]

I'm getting the following error when simply doing npm install playwright

> playwright@1.1.1 install /home/cloud_user/manisha/node_modules/playwright
> node install.js

internal/util.js:209
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at promisify (internal/util.js:209:11)

**Comment by mxschmitt** [comment]
Which Node.js version do you have? 10.15+ is required.

**Comment by pavelfeldman** [comment]
Looks like old Node, closing!
