### ISSUE TITLE
[BUG] In headless mode launchOptions (Disable SSO) are not working

### ISSUE THREAD

**Issue by ramam-v** [microsoft/playwright#26668]
### System info
- Playwright Version: [v1.37.1]
- Operating System: Windows 10
- Browser: Chromium  (Channel: Edge)
- Other info: AUT uses SSO to login

**Config file**
```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './test',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    headless: true,
    // viewport:{'width':1920,'height':1080},
    screenshot: 'on',
    bypassCSP: true,
    acceptDownloads: true,
    video: 'on',
    trace: 'retain-on-failure',
    actionTimeout: 0,
    permissions: ['clipboard-read'],
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'local',
      use: {
        channel: 'msedge',
        locale: 'en-AU',
        timezoneId: 'Australia/Melbourne',
        launchOptions: {
          args: ['--auth-server-allowlist="_"'],
        },
      },
    },

  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});







**Test file (self-contained)**

```ts
 const url = '';
  test(`SSO Login`, async ({ page }) => {
 
    await page.goto(url);
 // Application should display login screen and should not log you in based on your current Windows User Account


    await web.captureScreenClip(`Login Screen with Username and Password fields`);

  });


```

**Steps**
I have an Application Uder Test which uses OKTA SSO for login. Currently I am running the test locally and not in a pipeline. In my launch options I have defined that local Edge browser should launch with SSO disabled. So during test execution when playwright launches a browser and navigates to the AUT login URL. Then it should show the login screen with login prompt. But I am automatically logged in with the current windows user account when I run my script in headless mode.  My code works fine when I run my test in headed mode and fails in headless mode.

**Expected**
 npx playwright test SSO Login --project=local --headed    
 npx playwright test SSO Login --project=local

Test should run successfully in both headed and headless modes

**Actual**
 npx playwright test SSO Login --project=local --headed    
 npx playwright test SSO Login --project=local
Test is only passing when ran in headed mode

**Comment by yury-s** [comment]
Does it reproduce with Chrome or only in edge? It looks like `--auth-server-allowlist` indeed behaves differently in headless vs headed modes. As this is a browser flag it's likely an upstream browser issue and you may need to file it in the corresponding browser repository. If you think this is a bug in Playwright, please provide a minimal self-contained project (along with the detailed steps how to setup the environment) that we could run locally to reproduce the problem.

**Comment by ramam-v** [comment]
Its working in Chrome headless and headed mode. So issue is just restricted to Edge. So should this issue be raised against Edge repo?

**Comment by yury-s** [comment]
Yes, that would be appropriate.

**Comment by ramam-v** [comment]
Thanks Yury. As I cannot get you a sample project and I have a path forward with Chrome browser.   I will close the ticket. 

Regards,
Bhaskar
