### ISSUE TITLE
[BUG]Test run stops abruptly when a test case times out and when the node thread is manually killed, the test run starts again.

### ISSUE THREAD

**Issue by JasKirk70** [microsoft/playwright#26671]
[BUG]Test run stops abruptly when a test case times out and when the node thread is manually killed, the test run starts again.

### System info
- Playwright Version: [v1.37/ v1.34]
- Operating System: [macOS 13.5.1]
- Browser: [WebKit]
- Other info:

I see the logs as below in the console and the browser closes . When I go to activity monitor and manually kill a node thread, I see the browser start again and the test run continues

we are setting the test time out for every test file separately with below command
test.setTimeout(300000);

Below are the logs after which the browser closes and the test run gets hung
2023-08-24 03:14:40.418  SILLY [console src/utils/customreport/CustomReporter.ts:20  CustomReporter.onTestEnd] Test case error message: Test timeout of 300000ms exceeded. 
2023-08-24 03:14:40.418  SILLY [console src/utils/customreport/CustomReporter.ts:21  CustomReporter.onTestEnd] Test Result: timedOut 

This is happening since Tuesday 22nd August and it was happening on v1.34. So I ended up upgrading the version of playwright to 1.37, node to 18.7.1 and Mac OS to Ventura 13.5.1
But the issue persists. Please help resolve this issue

**Comment by yury-s** [comment]
We need a repro to act on this report. Please file a new one and link to this issue when you get back to it!
