### ISSUE TITLE
[Feature] In Playwright Java why we are not having page.coverage.StartCoverage and StopCoverage

### ISSUE THREAD

**Issue by Suresh81484** [microsoft/playwright#26679]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
[Feature] In Playwright Java why we are not having page.coverage.StartCoverage and StopCoverage

Is there any idea to include that in future

**Comment by yury-s** [comment]
No current plans to implement this in language ports other than node.js.
