### ISSUE TITLE
[BUG]Failed to install Webkit in visual studio for c#

### ISSUE THREAD

**Issue by Vijay2871** [microsoft/playwright#26676]
Error attached

```
Downloading Chromium 116.0.5845.82 (playwright build v1076) from https://playwright-verizon.azureedge.net/builds/chromium/1076/chromium-win64.zip
Error: getaddrinfo EAI_AGAIN playwright-verizon.azureedge.net
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:96:17) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright-verizon.azureedge.net'
}
Failed to install browsers
Error: Failed to download Chromium 116.0.5845.82 (playwright build v1076), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (C:\Users\**\source\repos\SpecFlowPlaywright\SpecFlowPlaywright\bin\Debug\net6.0\.playwright\package\lib\server\registry\browserFetcher.js:88:16)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)}
Downloading Chromium 116.0.5845.82 (playwright build v1076) from https://playwright-verizon.azureedge.net/builds/chromium/1076/chromium-win64.zip
Error: getaddrinfo EAI_AGAIN playwright-verizon.azureedge.net
    at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:internal/dns/promises:96:17) {
  errno: -3001,
  code: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'playwright-verizon.azureedge.net'
}
Failed to install browsers
Error: Failed to download Chromium 116.0.5845.82 (playwright build v1076), caused by
Error: Download failure, code=1
    at ChildProcess.<anonymous> (C:\Users\***\source\repos\SpecFlowPlaywright\SpecFlowPlaywright\bin\Debug\net6.0\.playwright\package\lib\server\registry\browserFetcher.js:88:16)
    at ChildProcess.emit (node:events:514:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)

```

**Comment by yury-s** [comment]
Can be a transient network issue. Is it happening if you go to the url (https://playwright-verizon.azureedge.net/builds/chromium/1076/chromium-win64.zip) manually ?

**Comment by yury-s** [comment]
EAI_AGAIN suggests that you might either have misconfigured DNS on your machine or you are getting throttled by the DNS server.

**Comment by Vijay2871** [comment]
is this an issue with proxy? as I 'm working in my vm as we have restrictions??

**Comment by yury-s** [comment]
May well be a problem with the proxy and it may limit access to some addresses.

**Comment by Vijay2871** [comment]
when i tried with this i'm getting this , i have tried updating  using powershell


PS C:\Users\**\source\repos\SpecFlowPlaywright> pwsh bin\Debug\net6\playwright.ps1 install
The argument 'bin\Debug\net6\playwright.ps1' is not recognized as the name of a script file. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

Usage: pwsh[.exe] [-Login] [[-File] <filePath> [args]]
                  [-Command { - | <script-block> [-args <arg-array>]
                                | <string> [<CommandParameters>] } ]
                  [-ConfigurationName <string>] [-ConfigurationFile <filePath>]
                  [-CustomPipeName <string>] [-EncodedCommand <Base64EncodedCommand>]
                  [-ExecutionPolicy <ExecutionPolicy>] [-InputFormat {Text | XML}]
                  [-Interactive] [-MTA] [-NoExit] [-NoLogo] [-NonInteractive] [-NoProfile]
                  [-NoProfileLoadTime] [-OutputFormat {Text | XML}]
                  [-SettingsFile <filePath>] [-SSHServerMode] [-STA]
                  [-Version] [-WindowStyle <style>]
                  [-WorkingDirectory <directoryPath>]

       pwsh[.exe] -h | -Help | -? | /?

PowerShell Online Help https://aka.ms/powershell-docs

**Comment by yury-s** [comment]
Well, it looks like you are running it from a wrong folder or playwright is not installed, or the installation is broken. As I mentioned above try accessing https://playwright-verizon.azureedge.net/builds/chromium/1076/chromium-win64.zip or playwright-verizon.azureedge.net without playwright, e.g. by typing the url in a browser's address bar. You'll likely get the same problem.

There is not much we can do on playwright end as this is a problem with the configuration of the vm, so I'm closing this report. Feel free to open a new one if you find there is a bug in playwright and can provide a repro.
