### ISSUE TITLE
[BUG] chromium --remote-debugging-port arg does not work

### ISSUE THREAD

**Issue by jperl** [microsoft/playwright#2667]
**Context:**
- Playwright Version: v1.1.1
- Operating System: Mac
- Node version: v12.16.3
- Browser: Chromium

**Code Snippet**

```javascript
const http = require("http");

const { chromium } = require("playwright");

(async () => {
  const browser = await chromium.launch({
    args: ["--remote-debugging-port=9999"],
    headless: false,
  });

  const page = await browser.newPage();

  http.get("http://localhost:9999");
})();
```

**Describe the bug**

This script throws `Error: connect ECONNREFUSED 127.0.0.1:9999`.

I see [there is a test](https://github.com/microsoft/playwright/blob/481643409eab07323109cb7851ccc5efd4298fc8/test/chromium/launcher.spec.js#L29) that it does not throw an error, but not one for connecting to the port. Is this argument not supported?

**Comment by aslushnikov** [comment]
> Is this argument not supported?

@jperl the flag itself is ignored. Why would you need one?

**Comment by jperl** [comment]
I was trying to attach the vscode chrome debugger. It's not that important, was just curious if this was a supported scenario.

**Comment by pavelfeldman** [comment]
We can allow it for debugging purposes. Patches are welcome!

**Comment by aslushnikov** [comment]
@jperl To aid VSCODE, you can pass `PLAYWRIGHT_CHROMIUM_DEBUG_PORT=9999` env variable. It [was added](https://github.com/microsoft/playwright/pull/2246) awhile ago specifically for this purpose!

Does it help?

**Comment by jperl** [comment]
I just saw that when I was investigating the source code to make a PR for this. That works, thanks!
