### ISSUE TITLE
[BUG] Unable to capture Alert in Screenshots and Video Recording

### ISSUE THREAD

**Issue by vipinphogat91** [microsoft/playwright#26685]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

In my test case I am clicking on a button which triggers a JavaScript alert. Though I am able to see and interact with the alert during execution but the same is not getting captured in:
1. Screenshot - IN the screenshot only the page responsible for triggering the alert is displayed
2. Video - In video, only the actions (like click on button) responsible for triggering the alert is displayed
3. Trace - Steps for handling the alert is captured but no screenshots are displayed

### Source code

Application URL  - https://www.lambdatest.com/selenium-playground/javascript-alert-box-demo

Button XPath - (//button[text()="Click Me"])[1]

Steps for handling alert:

` page.on('dialog', async (alert) => {
 let alertMsg = alert.message()

  await alert.accept()
})

await element.click()`

**Comment by yury-s** [comment]
Alert and dialogs in general are not a part of the web content of the page and as such are not captured on the video/screenshots. This is the same as https://github.com/microsoft/playwright/issues/17639
