### ISSUE TITLE
[BUG] - /lib64/libc.so.6: version `GLIBC_2.18' not found on linux agent docker-kitchensink-slave

### ISSUE THREAD

**Issue by vikassahnimca** [microsoft/playwright#26686]
### System info
- Playwright Version: [v1.35.1]
- Operating System: [linux docker]
- Browser: [Chromium]
- Other info:

### Source code
global-setup.ts file (Remove .txt extension and update .ts extension)
BrowserActions.ts file (Remove .txt extension and update .ts extension)
Jenkins file (Remove .txt extension)
playwright.config.ts file (Remove .txt extension and update .ts extension)

**Link to the GitHub repository with the repro**
Files are attached
[Jenkinsfile.txt](https://github.com/microsoft/playwright/files/12430902/Jenkinsfile.txt)
[BrowserActions.txt](https://github.com/microsoft/playwright/files/12430903/BrowserActions.txt)
[global-setup.txt](https://github.com/microsoft/playwright/files/12430904/global-setup.txt)
[playwright.config.txt](https://github.com/microsoft/playwright/files/12430905/playwright.config.txt)

// playwright.config.ts
Playwright config file is attached

**Test file (self-contained)**
File is attached. globalsetup and browseractions

**Steps**
Execute the Code using jenkin file on agent docker-kitchensink-slave

**Expected**
Earlier it was workign fine but now it is not working.

**Actual**
It is not working and giving error message.
 [pid=883][err] /home/jenkins/.cache/ms-playwright/chromium-1076/chrome-linux/chrome: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jenkins/.cache/ms-playwright/chromium-1076/chrome-linux/chrome)
[Jenkin_error.txt](https://github.com/microsoft/playwright/files/12430933/Jenkin_error.txt)

**Comment by vikassahnimca** [comment]
Earlier same files and code was working fine. Now it suddenly stopped working. and giving this error message.
Error: browserType.launch: Browser closed.
[pid=883][err] /home/jenkins/.cache/ms-playwright/chromium-1076/chrome-linux/chrome: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by /home/jenkins/.cache/ms-playwright/chromium-1076/chrome-linux/chrome)

**Comment by yury-s** [comment]
> Earlier same files and code was working fine. Now it suddenly stopped working. and giving this error message.

Sounds like an issue with the CI machine rather than playwright. You can try the same steps with our official docker image https://playwright.dev/python/docs/docker

If you think there it is a playwright bug, please file a new bug and provide a self-contained project that we can run locally, e.g. docker file with a complete test project in this case.
