### ISSUE TITLE
[Feature] Enhanced Playwright Integration in Azure Pipelines Test Results

### ISSUE THREAD

**Issue by Shanmuktej** [microsoft/playwright#26682]
### Summary:
Requesting the Playwright team to improve test case attachment in the Work Items tab of Test Results in Azure Pipeline runs.
![image](https://github.com/microsoft/playwright/assets/62170837/73dafe1b-24a2-447a-b6ab-b258f893abcd)
![image](https://github.com/microsoft/playwright/assets/62170837/063d4c88-cf5d-4d88-93cf-21048252f827)

### Description:
We need streamlined functionality to attach Playwright test cases to corresponding Work Items in Azure Pipeline's Test Results tab. This will enhance traceability and reporting.

### Proposed Enhancement:
1. **_Automated Association_**: Enable automatic linking of Playwright tests and Work Items based on naming or annotations.
2. **_Custom Metadata_**: Allow embedding references in Playwright scripts for accurate mapping.
3. **_API Integration_**: Provide API endpoints for programmatic linkage with test management tools.

### Benefits:
1. Improved traceability and reporting.
4. Enhanced collaboration and audit trail.
5. We appreciate your consideration for a more seamless Playwright-Azure Pipelines integration.

Thank you,
**_Anem Shanmuka Chandra Teja_**

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/11143, please upvote that request instead.
