### ISSUE TITLE
[BUG] page.route -test is stuck with page.route() just shows the blank screen

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26689]
### System info
- Playwright Version:  1.36.2
- Operating System: MAC
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

Hi, Will page.route() and page.waitForResponse() always capture the very first response right after clicking the button?

will page.route() and page.waitForResponse not help here if i want to capture the third/fourth url right after clicking the button? Can you please advise?

it is stuck at this point, and not proceeding further, just showing the blank page and just loading. can you please advise

i tried to capture the very first URL right after clicking the button, the test flow is still stuck even when i try to capture the very first URL...

/order-accruals is the very first url after the button click...

```javascript
await page.getByText('Update').click();
await page.route('**/order-accruals', async route => {
  
    const response = await route.fetch();
    const json = await response.json();
    await route.continue();
});
```

**Comment by yury-s** [comment]
> Hi, Will page.route() and page.waitForResponse() always capture the very first response right after clicking the button?

Yes, but you have to ensure that you setup route handler before clicking:

```js
await page.getByText('Update').click();
await page.route('**/order-accruals', async route => {
  
    const response = await route.fetch();
    const json = await response.json();
    await route.continue();
});
```

> it is stuck at this point, and not proceeding further, just showing the blank page and just loading. can you please advise

I'm not sure I understand what you mean. If you think there is a bug in playwright, please attach a self-contained reproducible example that we could run locally to see the bug.

**Comment by InduKrish** [comment]
> Yes, but you have to ensure that you setup route handler before clicking:
> 
> ```js
> await page.getByText('Update').click();
> await page.route('**/order-accruals', async route => {
>   
>     const response = await route.fetch();
>     const json = await response.json();
>     await route.continue();
> });
> ```


Can you please tell me what you mean by setting up route handler before clicking:, can you please help me with an example and how to get that working?

and what if i want to capture the third and fourth URL after clicking the button? Can page.route() or page.waitForResponse not be used in this case? if so, how to capture the response of the network calls (third or fourth network call) after the  click,

**Comment by yury-s** [comment]
> should be the way mentioned below?

Yes, this. Sorry, I copied the snippet but did not update it. It should be:

```js
await page.route('**/order-accruals', async route => {  
    const response = await route.fetch();
    const json = await response.json();
    await route.continue();
});
await page.getByText('Update').click();
```

> and what if i want to capture the third and fourth URL after clicking the button? Can page.route() or page.waitForResponse not be used in this case?

The handler will be called for each of the subsequent matching requests, until it is removed with [page.unroute](https://playwright.dev/docs/api/class-page#page-unroute).

>  if so, how to capture the response of the network calls (third or fourth network call) after the click,

`page.waitForResponse()` will wait for one (first) response only. If you want to listen to multiple requests and do not need to modify them, you could use [page.on('response')](https://playwright.dev/docs/api/class-page#page-event-response)

```js
  page.on('response', async response => {  
    if (!/.*order-accruals/.test(response.url()))
      return;
    const json = await response.json();
    console.log(json);
  });
  await page.getByText('Update').click();
```

Would that work for you?

**Comment by InduKrish** [comment]
page.waitforResponse worked and it retrieved respose, but page.route still didnt work,

page.waitforResponse()

```javascript
        const responsePromise = page.waitForResponse('**/base-auctions/base-options');
        await crewIFPlannerActor.attemptsTo(Click.on().button('Accruals'))
        const response = await responsePromise;
        const auctionResult = JSON.stringify(await response.json())
        console.log(" Test Response 2: " + JSON.stringify(response));
        console.log(" Actual Result: " + JSON.stringify(auctionResult));
```


page.route() is not working, and the test is stuck,
```javascript
await page.route('**/crew-member-accruals',   async route => {
            const response = await route.fetch();
            const json = await response.json();
            console.log("Response:" + JSON.stringify(json));


            const station = JSON.parse(json).$[0].value;
            console.log("Station value:" + station);
            await route.continue();
        });
```
<img width="1203" alt="Screen Shot 2023-08-24 at 3 53 27 PM" src="https://github.com/microsoft/playwright/assets/113629123/b890e797-4f2d-40b1-bef9-6c68c621d7b9">

**Comment by yury-s** [comment]
> page.route() is not working,

Do you mean page.route is not called or what exactly is not working?

> and the test is stuck,

Well, it may be that the page relies on the order of the responses and with interception slowing down some of them the assumption fails. You can also try fulfilling the request with fetched data instead of just resuming it like this:

```js
  await page.route('**/crew-member-accruals',   async route => {
    const response = await route.fetch();
    const json = await response.json();
    console.log("Response:" + JSON.stringify(json));
    await route.fulfill({response});
  });
```

If you think there is a bug in playwright please share a minimal repro that we could run locally to reproduce the problem. The snippet you showed works fine for me on a simple test.

**Comment by InduKrish** [comment]
> Do you mean page.route is not called or what exactly is not working?
> 
>  i placed route handler before click, and the page shows only blank page and doesnt load the UI, when i use page.route(), but if i try with page.waitForResponse, page loads fine.



> ```js
> await page.route('**/crew-member-accruals',   async route => {
>     const response = await route.fetch();
>     const json = await response.json();
>     console.log("Response:" + JSON.stringify(json));
>     await route.fulfill({response});
>   });
> ```


```javascript
await page.route('**/crew-member-accruals',   async route => {
            const response = await route.fetch();
            const json = await response.json();
            console.log("Response:" + JSON.stringify(json));
            await route.fulfill({response});
        });

  await crewIFPlannerActor.attemptsTo(Click.on().button('Accruals'))
```
I tried the code snippet above, and i still see the same problem, 
Attaching the screenshot.
<img width="1507" alt="Screen Shot 2023-08-25 at 9 01 57 AM" src="https://github.com/microsoft/playwright/assets/113629123/811328a1-11be-47c3-91da-3a983db99d9c">


and also , i placed button click before route handler, just to see if api /crew-member-accruals is logged to the console.and i  see that the request is logged, not sure what is causing the flow to be blocked. why page.route() is unable to capture the response and proceed with the flow?

placing click before handler(just for logging the response) 
```javascript
  await crewIFPlannerActor.attemptsTo(Click.on().button('Accruals'))
 await page.route('**/crew-member-accruals',   async route => {
            const response = await route.fetch();
            const json = await response.json();
            console.log("Response:" + JSON.stringify(json));
            await route.fulfill({response});
        });

 ```
<img width="1507" alt="Screen Shot 2023-08-25 at 9 02 21 AM" src="https://github.com/microsoft/playwright/assets/113629123/e51fc0f8-3ff8-44d7-82c7-a44d5c12d0ba">

**Comment by yury-s** [comment]
> I found a bug related to page.route(), Can you please confirm if it is related to the issue whose link is mentioned below? #12148

Yes, the symptoms are very similar, we can tell for sure if you share a repro that we can run locally. You can try workarounds from that report.

**Comment by InduKrish** [comment]
/reports/awards-alpha?base=DAL&round=1&revision=1&origBase=DAL&origRound=5

in page.route , Is it possible to use, just part of the URL instead of the complete URL?
for eg:
await page.route('**/reports/awards-alpha?base=DAL&**', route => {
  
    route.continue();
});

Can you please advise if page.route() accepts partial URL String?

**Comment by yury-s** [comment]
> Can you please advise if page.route() accepts partial URL String?

Yes, the [url](https://playwright.dev/docs/api/class-page#page-route-option-url) can be a glob pattern.

> and route.continue() - Can you please confirm if route.continue() us to continue the flow after the route match is found?

Yes, see the docs, the request will continue to be sent from the browser.

> also ,in one of the tests, i see that I defined route handler after click, but the test still works, wondering how it is working without having route handler before click

It may work in some cases but may result in a racy behavior, so it's better to add the handler strictly before the page sends a request.

> Is there a way to capture the request URL and pass inside route like below? 

You can do this but it will not capture original request as it was already sent. If there is another request with the same URL and you want to intercept it, you have to be careful to ensure that it has not been sent yet by the time you call `page.route`.

**Comment by yury-s** [comment]
We diverged from the original problem. Merging this report into https://github.com/microsoft/playwright/issues/12148 as it seems to be caused by the same issue. Feel free to open a new bug if you have a repro that demonstrates this is a different issue.
