### ISSUE TITLE
[Question] afterAll hooks and test failures

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#26683]
So I took a look at https://playwright.dev/docs/test-retries and based off what I am seeing an `afterAll` hook will run on retries and `beforeAll` hooks run on retry. But will an `afterAll` hook run if the test failed period?

IE: If I have 1 test, and there is a singular `afterAll` after that test and lets say the test was set at 3 retries but failed twice. How many times would the `afterAll` hook actually run? My guess is it runs regardless, but i've used other frameworks where the test would fail and the hook wouldn't run because it failed.

Thanks

**Comment by yury-s** [comment]
> But will an `afterAll` hook run if the test failed period?

Yes, it will.

> IE: If I have 1 test, and there is a singular afterAll after that test and lets say the test was set at 3 retries but failed twice. How many times would the afterAll hook actually run? My guess is it runs regardless, but i've used other frameworks where the test would fail and the hook wouldn't run because it failed.

Your understanding is correct, it will run after each attempt of the test. 3 times overall - 2 times after test failures and 1 more after the successful run.
