### ISSUE TITLE
[Question] toHaveProperty vs objectContaining

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#26704]
Is there any functional difference between the two? They both seem to do the same thing with different syntax. Specifically in this test case scenario I just want to ensure an object includes a specific key/value pair. There is also toMatchObject which looks similar.

The only real difference I am seeing is that toHaveProperty the "value" is optional.

Is there a specific one that works best?

**Comment by yury-s** [comment]
`objectContaining` is a more generic version that enables you to specify multiple properties at the same with more complex condition on their values. `toHaveProperty` will just check on property and has a more concise syntax for that.
