### ISSUE TITLE
[BUG]: Running Android automation permanently prevents Chrome Remote Debugging from working

### ISSUE THREAD

**Issue by Slapbox** [microsoft/playwright#26721]
### System info
- Playwright Version: 1.37.1
- Operating System: Ubuntu 23.04
- Browser: Chrome for Android
- Other info: This occurs immediately, even if the automation fails with: _"Please install Android driver apk using `npx playwright install android`"_

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const config = {
  testMatch: /.*\.playwright-test\.js/,
  fullyParallel: true,
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
};
export default config;

```

**Test file (self-contained)**

```js
const { _android: android } = require('playwright');

(async () => {
  const [device] = await android.devices();
  // await device.shell('am force-stop com.android.chrome'); // This line does not prevent the problem
  const context = await device.launchBrowser(); // THIS IS THE LINE THAT BREAKS THE EMULATOR FOR GOOD
})();
```

**Steps**

**Warning: This process will effectively damage your emulator, rendering it unable to connect to Chrome Remote Debugging _ever again._**

1. Create test file (eg `android.js`) 
2. Confirm emulator is connected to Chrome's remote debugging via `chrome://inspect/#devices`
3. Run `node android.js`
4. Almost instantly you will see the remote debugging disappear. _Nothing can save this device once this occurs_

**Expected**
Remote debugging is not disrupted, or at least, not permanently prevented

**Actual**
Remote debugging for the emulator will _never_ work again, persisting through app data clearing, reboots, reinstalls, cold boots, most of the advice on StackOverflow, _everything_.

I confirmed this on two different emulators, one for API 31 and the other for API 33. Both suffer the same irreversible problem.

It presents as this device without anything under it, even though it had been connected to the device and showing its tabs immediately prior to running Playwright:
![image](https://github.com/microsoft/playwright/assets/6835891/7b377683-34c6-4ab6-b741-13eb7facc2bc)

**Comment by pavelfeldman** [comment]
> Almost instantly you will see the remote debugging disappear. Nothing can save this device once this occurs

Could you explain what you mean by this? Playwright communicates to Android via ADB interface, independently from Chrome Devtools. When you say nothing can save it, do you mean that you can still start the browser, but chrome:inspect won't be able to see it?

As a guess, could you adb shell into that device and remove the file `/data/local/tmp/chrome-command-line` from it?

**Comment by Slapbox** [comment]
Thanks for your reply @pavelfeldman. Indeed you can still start and use Chrome on Android but nothing actually works.

Interestingly I realized that I don't even have Chrome Command Line enabled on this emulator currently (although in the past I did before rolling back my VM snapshot and the issue occurred just the same)

So that makes it especially curious that `adb shell rm /data/local/tmp/chrome-command-line` and then restarting Chrome for Android resolves the issue immediately.

Thanks very much for the tip @pavelfeldman and let me know if I can be any more help in resolving this issue for everyone.

**Comment by pavelfeldman** [comment]
> So that makes it especially curious that adb shell rm /data/local/tmp/chrome-command-line and then restarting Chrome for Android resolves the issue immediately.

Thanks for confirming it, I'll see what I can do to make sure we generate unix named pipe names that chrome picks up.
