### ISSUE TITLE
Wrong line numbers in playwright inspector with cucumber.js

### ISSUE THREAD

**Issue by gnuechtel** [microsoft/playwright#26727]
This is the repro for #19944:

- fork [cucumber-playwright](https://github.com/Tallyb/cucumber-playwright) from @Tallyb -> I did it here: https://github.com/gnuechtel/cucumber-playwright
- add `page.pause()` to `playwright.steps` -> I did it in [my fork](https://github.com/gnuechtel/cucumber-playwright/tree/wrong-line-number)
- and voila the line number is wrong, when we execute `npm run debug`:

![image](https://github.com/microsoft/playwright/assets/3738251/804a6cf7-565a-41fd-be89-00d6d67da24d)

Now when we change the playwright version in `package.json` to `1.21.1` everything works as expected:

![image](https://github.com/microsoft/playwright/assets/3738251/8de571f4-abed-408b-9bde-bf545815c9a9)

_Originally posted by @gnuechtel in https://github.com/microsoft/playwright/issues/19944#issuecomment-1694219385_

**Comment by gnuechtel** [comment]
As suggested by @aslushnikov I have opened another issue with a repro for #19944

**Comment by mxschmitt** [comment]
Bisected to

Good 1.22.0-alpha-apr-19-2022 ed0dcdabc9ffa447e0577ce620445140fd5d8653
Bad 1.22.0-alpha-apr-20-2022 bd79accb6f7d07ea90b5faa1b9c75ed17347a633

Range https://github.com/microsoft/playwright/compare/ed0dcdabc9ffa447e0577ce620445140fd5d8653...bd79accb6f7d07ea90b5faa1b9c75ed17347a633

**Comment by mxschmitt** [comment]
Looks like this is already fixed by https://github.com/microsoft/playwright/issues/26346. Do you mind testing on [Canary](https://playwright.dev/docs/canary-releases)?

**Comment by gnuechtel** [comment]
I also tested it with the current canary version (`1.38.0-alpha-aug-30-2023`), and I can happily confirm that line numbers with cucumber.js are correct again. So I close this ticket and keep an eye on the 1.38 release.
