### ISSUE TITLE
[Feature] WebView Trace File viewer should allow selection of locator language

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright#26736]
So when i send a trace file that was recorded running playwright Dotnet version to the web version of the trace file (https://trace.playwright.dev/) viewer it would be nice to be able to use the pick locator and produce a dotnet version of the selector. this would save the need to translate the locator or try to add in the new() keywords etc

How that's solved i am not sure, if you make a dotnet version of the URL
https://trace.playwright.dev/dotnet/
or allow a selector / language  choice within the trace viewer

Example
![image](https://github.com/microsoft/playwright-dotnet/assets/9976197/ef0e2b01-5d94-4a42-9af6-713ecfaa63f9)

But the actual dotnet version of the selector is

```
GetByText("Add new page").First;
```

**Comment by mxschmitt** [comment]
Should be fixed tomorrow and be available at https://trace.playwright.dev/next/
