### ISSUE TITLE
Whether a playwright can be used to generate a form template

### ISSUE THREAD

**Issue by yangdashan** [microsoft/playwright#26731]
Can I generate a form template through playwright, and next time I only need to replace the form keyword in the script generated by playwright to replace the script, which can achieve some purposes of automatic form submission

**Comment by yangdashan** [comment]
Yes, I've tried to do that.  But hopefully not for a specific form. I can only handle some simple components, such as input and select, but some treeSelect and Timepickers cannot be initialized with the given input.  And the types of selectors in codeGen generated scripts change for different types of forms

So for these situations, I don't have a stable rule to replace him, maybe only through the ability of Ai to replace it

**Comment by mxschmitt** [comment]
If you encounter situations where codegen is not able to handle a specific element, please file a separate issue with a reproduction.

These treeSelect and Timepicker components are most likely non-standard, but we'd definitely be interested in looking at them to make them work with codegen and your site.

> And the types of selectors in codeGen generated scripts change for different types of forms

This is unfortunately outside of our control.

**Comment by aslushnikov** [comment]
Closing as per above.
