### ISSUE TITLE
[Question]When opening the specified directory browser, all Chrome plugins were reset.

### ISSUE THREAD

**Issue by adolyb** [microsoft/playwright#26734]
```ts
import { chromium } from "@playwright/test";

(async () => {
  const userDataDir = 'D:/metachrome/1';
  
  const browser = await chromium.launchPersistentContext(userDataDir, {
    headless: false, 
    slowMo: 50 
  });
  
  const page = await browser.newPage();
  await page.goto('https://www.example.com');
  
//   await browser.close();
})();
```

When I opened the specified directory, I found that all my Chrome plugins had been deleted. However, after reinstalling the plugins, the original data was still there.

At the same time,When I open Chrome setting Chrome will show: "Chrome has detected that some of your settings have been tampered with by other programs, so these settings have been reset to their original default settings."

 How can this problem be resolved?

**Comment by aslushnikov** [comment]
@adolyb Chromium and Chrome are different browsers; if you want to open your Chrome's extension and your Chrome's user directory, you should use `channel: "chrome"`. 

See our documentation: https://playwright.dev/docs/next/browsers#defaults
