### ISSUE TITLE
[Question] Running on GitLab leads to WebSocket error: connect ECONNRESET 127.0.0.1:42495

### ISSUE THREAD

**Issue by volekerb** [microsoft/playwright#2674]
Still struggling a bit with running Playwright tests on GitLab.

GitLab: 12.9.2-ee
.gitlab-ci.yml
```
stages:
  - test

cache:
  paths:
    - node_modules/
#    - ~/.cache/ms-playwright

test:
  stage: test
  image: node:13
  script:
    - npm i
    - DEBUG=pw:api npm run test
  artifacts:
    paths:
      - screenshots
    expire_in: 15 days
  only:
    - master
  allow_failure: false
  when: manual
```

using jest-playwright.config.js:
```
module.exports = {
    launchOptions: {
        args: [
            `--no-sandbox`,
            '--disable-dev-shm-usage',
            '--ipc=host',
            '--disable-setuid-sandbox'
        ]
    }
}
```

Run leads to:
```
$ DEBUG=pw:api npm run test
 > @ test /builds/online/mvp/online-mvp-qa
 > jest
 2020-06-23T08:05:40.260Z pw:api => chromium.launchServer started
 2020-06-23T08:05:40.272Z pw:api <= chromium.launchServer succeeded
 2020-06-23T08:05:40.333Z pw:api => chromium.connect started
 2020-06-23T08:05:40.346Z pw:api <= chromium.connect failed
 FAIL browser: chromium __tests__/smoke.spec.ts
   ● Test suite failed to run
     WebSocket error: connect ECONNRESET 127.0.0.1:42495
     ================== chromium.connect logs ==================
     <ws connecting> ws://127.0.0.1:42495/650495df1a372b4495e61a682fad5c1d
     <ws connect error> ws://127.0.0.1:42495/650495df1a372b4495e61a682fad5c1d connect ECONNRESET 127.0.0.1:42495
     <ws disconnected> ws://127.0.0.1:42495/650495df1a372b4495e61a682fad5c1d
     ============================================================
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
       at WebSocket.<anonymous> (node_modules/playwright/lib/transport.js:119:24)
       at WebSocket.onError (node_modules/playwright/node_modules/ws/lib/event-target.js:128:16)
       at ClientRequest.<anonymous> (node_modules/playwright/node_modules/ws/lib/websocket.js:568:15)
```

Not quite sure where to dig. Can you please assist here?

**Comment by mxschmitt** [comment]
Could you share with us the content of the `chromium __tests__/smoke.spec.ts`? Feel free to remove any sensitive information there.

**Comment by volekerb** [comment]
Sure,
and thanks for such quick replies!
```
describe('User can login to live.jugru.org with different browsers and devices', () => {
    const host = 'http://live.jugru.org/';
    const user = 'someUser';
    const password = 'somePWD';

    it('[Chromium] Login to live.jugru.org through LK', async () => {
        const browserType = 'chromium';
        const browser = await playwright[browserType].launch();
        const context = await browser.newContext();
        const page = await context.newPage();
        await openMainPage(page, host, browserType);
        await login(page, browserType, user, password);
        await openBroadcast(page, browserType);
        await openExhibition(page, browserType);
        await browser.close();
    });
```

**Comment by mxschmitt** [comment]
If you are using jest-playwright-preset in your Jest configuration as a Jest environment, then you don't need to launch the browser, page or context manually in your tests. For each test there will be a global page variable available.

**Comment by volekerb** [comment]
Okay got it!
So I tried 2 ways:
1. without jest-playwright-preset I have:

```
<launching> /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-ohT07e --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --no-sandbox --disable-dev-shm-usage --ipc=host --disable-setuid-sandbox --no-startup-window
     <launched> pid=123
     /root/.cache/ms-playwright/chromium-775089/chrome-linux/chrome: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
     <process did exit: exitCode=127, signal=null>
     ============================================================
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error:
       40 |     it('[Chromium] Login to live.jugru.org through LK', async () => {
       41 |         const browserType = 'chromium';
     > 42 |         const browser = await playwright[browserType].launch({
          |                         ^
       43 |             'args': [
       44 |                 `--no-sandbox`,
       45 |                 '--disable-dev-shm-usage',
       at node_modules/playwright/lib/chromium/crConnection.js:132:63
```
smoke.spec.ts:
```
    it('[Chromium] Login to live.jugru.org through LK', async () => {
        const browserType = 'chromium';
        const browser = await playwright[browserType].launch({
            'args': [
                `--no-sandbox`,
                '--disable-dev-shm-usage',
                '--ipc=host',
                '--disable-setuid-sandbox'
            ]
        });
        const context = await browser.newContext();
        const page = await context.newPage();
        await openMainPage(page, host, browserType);
        await login(page, browserType, user, password);
        await openBroadcast(page, browserType);
        await openExhibition(page, browserType);
        await browser.close();
```
package.json:
```
{
  "private": true,
  "scripts": {
    "test": "jest"
  },
...
```

2. With jest-playwright-preset
Changed to

smoke.spec.ts:
```
    it('[Chromium] Login to live.jugru.org through LK', async () => {
        const browserType = 'chromium';
        // const browser = await playwright[browserType].launch({
        //     'args': [
        //         `--no-sandbox`,
        //         '--disable-dev-shm-usage',
        //         '--ipc=host',
        //         '--disable-setuid-sandbox'
        //     ]
        // });
        // const context = await browser.newContext();
        // const page = await context.newPage();
        await openMainPage(page, host, browserType);
        await login(page, browserType, user, password);
        await openBroadcast(page, browserType);
        await openExhibition(page, browserType);
        // await browser.close();
```
jest-playwright.config.js:
```
module.exports = {
    launchOptions: {
        args: [
            `--no-sandbox`,
            '--disable-dev-shm-usage',
            '--ipc=host',
            '--disable-setuid-sandbox'
        ]
    },
    // setupFilesAfterEnv: ["jest-allure/dist/setup"]
}
```

package.json:
```
{
  "private": true,
  "scripts": {
    "test": "jest"
  },
  "jest": {
    "preset": "jest-playwright-preset"
  },
...
```

and have:
```
   ● Test suite failed to run
     WebSocket error: connect ECONNRESET 127.0.0.1:43731
     ================== chromium.connect logs ==================
     <ws connecting> ws://127.0.0.1:43731/10649d2b4706bab32678fd1f8ccb47e3
     <ws connect error> ws://127.0.0.1:43731/10649d2b4706bab32678fd1f8ccb47e3 connect ECONNRESET 127.0.0.1:43731
     <ws disconnected> ws://127.0.0.1:43731/10649d2b4706bab32678fd1f8ccb47e3
```

BTW both cases locally running smooth. heh..

**Comment by mxschmitt** [comment]
Try to install the dependencies which are required: https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic

Probably in your case only for Chromium.

**Comment by volekerb** [comment]
Was able to run with baked docker image: `aslushnikov/playwright:bionic`
If there would be any chance to build official microsoft/playwright:bionic with latest changes it would be really cool and I believe it could simplify documentation.

.gitlab-ci.yml:
```
test:
  stage: test
  image: aslushnikov/playwright:bionic
  script:
    - npm install
    - npm run test
  artifacts:
    paths:
      - screenshots
    expire_in: 15 days
  only:
    - master
  allow_failure: false
  when: manual
```

**Comment by volekerb** [comment]
Thank you for all suggestions and such quick answers!

**Comment by mxschmitt** [comment]
Thanks for confirming, that it works. Docker Hub image will be tracked here: #1482

**Comment by volekerb** [comment]
what is really weird that without jest-playwright plugin tests on github can't run..
```
 Failed to launch browser: Error: spawn /home/pwuser/.cache/ms-playwright/chromium-775089/chrome-linux/chrome ENOENT
     =================== chromium.launch logs ===================
     <launching> /home/pwuser/.cache/ms-playwright/chromium-775089/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/tmp/playwright_chromiumdev_profile-RPDqHR --remote-debugging-pipe --headless --hide-scrollbars --mute-audio --no-sandbox --disable-dev-shm-usage --ipc=host --disable-setuid-sandbox --no-startup-window
     ============================================================
     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
       at ChildProcess.<anonymous> (node_modules/playwright/lib/server/processLauncher.js:51:20)
```

But locally it's fine..

```
const browserType = 'webkit';
        const browser = await playwright[browserType].launch({
            'args': [
                `--no-sandbox`,
                '--disable-dev-shm-usage',
                '--ipc=host',
                '--disable-setuid-sandbox'
            ]
        });
        const context = await browser.newContext();
        const page = await context.newPage();
```

can't use playwright-jest since need to have control over some browsers and particular tests

**Comment by Simonwep** [comment]
@volekerb Did you find any other solution to it? I'm having the [same issue](https://github.com/Simonwep/nanopop/runs/808668528) but in my case it's webkit (firefox and chromium work just fine) 😅

> Error:
```
PASS browser: chromium tests/container.test.js
PASS browser: firefox tests/container.test.js
FAIL browser: webkit tests/container.test.js
  ● Test suite failed to run

    WebSocket error: connect ECONNREFUSED 127.0.0.1:35507
    =================== webkit.connect logs ===================
    <ws connecting> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51
    <ws connect error> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51 connect ECONNREFUSED 127.0.0.1:35507
    <ws disconnected> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51
    ============================================================
    Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.

      at WebSocket.<anonymous> (node_modules/playwright-webkit/lib/transport.js:119:24)
      at WebSocket.onError (node_modules/playwright-webkit/node_modules/ws/lib/event-target.js:128:16)
      at ClientRequest.<anonymous> (node_modules/playwright-webkit/node_modules/ws/lib/websocket.js:568:15)
```

> `jest-playwright.config.js`, `launchOptions` and `contextOptions` both get passed to playwright - see [jest-playwright](https://github.com/playwright-community/jest-playwright)
```js
module.exports = {
    browsers: ['chromium', 'firefox', 'webkit'],
    launchOptions: {
        headless: true
    },
    contextOptions: {
        deviceScaleFactor: 1,
        viewport: {
            width: 750,
            height: 750
        }
    },
    serverOptions: {
        command: 'serve .',
        port: 5000
    }
};
``` 
I'm not calling any playwright functions directly, I only use the global `page` object... The setup is quite small, [this is the tree](https://github.com/Simonwep/nanopop/tree/beca1ff4e7ef2b736f81c10a1e3b0f5624153589) of which the build fails - could this be a problem with [jest-playwright](https://github.com/playwright-community/jest-playwright)?

I'm using GitHub actions with [this workflow](https://github.com/Simonwep/nanopop/actions/runs/147828381/workflow), since you had this issue 2 days ago I guess it's rather new?! Is it just luck that, in my case, ubuntu-latest (Ubuntu 18.04.4 LTS) ships with most dependencies or is this a "bug" @mxschmitt? Or is using a docker-image the way to go, if so maybe that should be added to the docs that it's recommend / necessary to install dependencies _or_ to use the provided(?!) docker image in CI.

**Comment by mxschmitt** [comment]
> @volekerb Did you find any other solution to it? I'm having the [same issue](https://github.com/Simonwep/nanopop/runs/808668528) but in my case it's webkit (firefox and chromium work just fine) 😅
> 
> > Error:
> ```
> PASS browser: chromium tests/container.test.js
> PASS browser: firefox tests/container.test.js
> FAIL browser: webkit tests/container.test.js
>   ● Test suite failed to run
> 
>     WebSocket error: connect ECONNREFUSED 127.0.0.1:35507
>     =================== webkit.connect logs ===================
>     <ws connecting> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51
>     <ws connect error> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51 connect ECONNREFUSED 127.0.0.1:35507
>     <ws disconnected> ws://127.0.0.1:35507/e41876ea27e030a59eb786d5e3fc8f51
>     ============================================================
>     Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
> 
>       at WebSocket.<anonymous> (node_modules/playwright-webkit/lib/transport.js:119:24)
>       at WebSocket.onError (node_modules/playwright-webkit/node_modules/ws/lib/event-target.js:128:16)
>       at ClientRequest.<anonymous> (node_modules/playwright-webkit/node_modules/ws/lib/websocket.js:568:15)
> ```
> 
> > `jest-playwright.config.js`, `launchOptions` and `contextOptions` both get passed to playwright - see [jest-playwright](https://github.com/playwright-community/jest-playwright)
> ```js
> module.exports = {
>     browsers: ['chromium', 'firefox', 'webkit'],
>     launchOptions: {
>         headless: true
>     },
>     contextOptions: {
>         deviceScaleFactor: 1,
>         viewport: {
>             width: 750,
>             height: 750
>         }
>     },
>     serverOptions: {
>         command: 'serve .',
>         port: 5000
>     }
> };
> ``` 
> I'm not calling any playwright functions directly, I only use the global `page` object... The setup is quite small, [this is the tree](https://github.com/Simonwep/nanopop/tree/beca1ff4e7ef2b736f81c10a1e3b0f5624153589) of which the build fails - could this be a problem with [jest-playwright](https://github.com/playwright-community/jest-playwright)?
> 
> I'm using GitHub actions with [this workflow](https://github.com/Simonwep/nanopop/actions/runs/147828381/workflow), since you had this issue 2 days ago I guess it's rather new?! Is it just luck that, in my case, ubuntu-latest (Ubuntu 18.04.4 LTS) ships with most dependencies or is this a "bug" @mxschmitt? Or is using a docker-image the way to go, if so maybe that should be added to the docs that it's recommend / necessary to install dependencies _or_ to use the provided(?!) docker image in CI.

Could you try to use this official GitHub Action which installs all the needed dependencies?
https://github.com/microsoft/playwright-github-action

**Comment by Simonwep** [comment]
Can confirm that it [works](https://github.com/Simonwep/nanopop/runs/810863933) (just the tests are now broken on webkit but I guess I can figure that one out by myself) - thanks a lot :)
Is there any note about using the image in CI situations that I missed, because it works flawlessly with it! :D

**Comment by volekerb** [comment]
@Simonwep In my case I figured out that I have to add `- npm i -D playwright` even with using `image: aslushnikov/playwright:bionic`. Looks like runner couldn't find installed browser that's why I had such issue.

So, I've got such config:
`.gitlab-ci.yml`
```
stages:
  - test

cache:
  paths:
    - node_modules/

test-prod:
  stage: test
  image: aslushnikov/playwright:bionic
  script:
    - npm install
    - npm i -D playwright
    - DEBUG=pw:api npm run test-prod
  artifacts:
    paths:
      - screenshots
    expire_in: 15 days
  only:
    - master
  allow_failure: false
  when: manual
```
I'm using several environments so have in
`psckage.json`
```
{
  "private": true,
  "scripts": {
    "test-prod": "jest --config=jest.prod.config.js",
    "test-dev": "jest --config=jest.dev.config.js",
    "test-test": "jest --config=jest.test.config.js"
  },
...
```
And in each config have some global vars (related to each staging env) and
```
module.exports = {
    preset: "jest-playwright-preset",
}
```

**Comment by arjun27** [comment]
Thanks @volekerb. I believe you had to add the additional step to install playwright again because of the caching behavior. We've documented this [here](https://playwright.dev/#version=master&path=docs%2Fci.md&q=caching-browsers), but perhaps there's a better way.
