### ISSUE TITLE
[Implementation of BDD feature in playwright/test runner file ]

### ISSUE THREAD

**Issue by RogerDat1** [microsoft/playwright#26742]
playwright test runner should start supporting for BDD framework . We are missing out the potential and benefit of running playwright through playwright.config.ts(playwright runner file ) rather we have to use cucumber-js .
Because of this we are missing out parallel execution , integrating reporting portal io with our framework .
using cucumber runner file and playwright as a tool is not making our framework scalable .

Playwright team ... please integrate BDD with playwright and make it native to playwright . so that we can use playwright test runner to its full potential .

**Comment by yury-s** [comment]
Merging into https://github.com/microsoft/playwright/issues/11975, please upvote that issue instead.
