### ISSUE TITLE
[BUG] Driver Node version not upgrading for playwright

### ISSUE THREAD

**Issue by lijoabraham** [microsoft/playwright#26753]
### System info
- Playwright Version: [1.37.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium]
- Other info:

**Expected**

I have installed Playwright using the below command.
`poetry add playwright@latest`

playwright version is upgraded to latest version, but the node version is still v18.17.0. As per the CWE, fix has been implemented in 19.x  node versions.

**Actual**

Getting this vulnerabilty error.

The use of   'module.constructor.createRequire()' can bypass the policy mechanism and   require modules outside of the policy.json definition for a given   module.  This vulnerability affects all   users using the experimental policy mechanism in all active release lines:   16.x, 18.x, and, 20.x.  Please note   that at the time this CVE was issued, the policy is an experimental feature   of Node.js.

The use of 'Module._load()' can bypass   the policy mechanism and require modules outside of the policy.json   definition for a given module.  This   vulnerability affects all users using the experimental policy mechanism in   all active release lines: 16.x, 18.x and, 20.x.  Please note that at the time this CVE was   issued, the policy is an experimental feature of Node.js.

Running the version commands give other version results.

Step 10/18 : RUN playwright --version
Version 1.37.0

Step 11/18 : RUN /usr/local/lib/python3.11/site-packages/playwright/driver/node --version
v18.17.0

How to upgrade the node driver version from 18.x to 19.x ?

**Comment by aslushnikov** [comment]
@lijoabraham the upcoming version of Playwright (1.38) will have an updated driver version with the fixed vulnerability. Hope this helps!

**Comment by lijoabraham** [comment]
Still the node version is 18 only even after the playwright version is upgraded.

<img width="360" alt="image" src="https://github.com/microsoft/playwright/assets/119271231/85eabd7d-6b99-4d03-8afc-29f00505d16e">
