### ISSUE TITLE
[Feature] browserType to distinct mobile and desktop instance

### ISSUE THREAD

**Issue by styurenkov-b2broker** [microsoft/playwright#26765]
browserType to distinct mobile and desktop instance

it is possible to set mobile browsers in config, but its not possible to get the browserType and separate logic for mobile and desktop browsers tests?

Update: 
Actually I found a workaround through workerInfo.project.name

**Comment by StasGrishaevTutu** [comment]
If you are looking for detecting browser type in test (mobile/desktop) - check this one - https://github.com/microsoft/playwright/discussions/11686#discussioncomment-2060273

**Comment by mxschmitt** [comment]
As per above, just a bit more verbose: We recommend the [`isMobile` fixture](https://playwright.dev/docs/api/class-testoptions#test-options-is-mobile) for that, its already set if you use Playwrights built-in mobile devices and you can read it inside your test e.g. like that:

```ts
import { test, expect } from '@playwright/test';

test('...', async ({ page, isMobile }) => {
  // ...
});
```

**Comment by aslushnikov** [comment]
Closing as per above.

**Comment by styurenkov-b2broker** [comment]
maybe it should be described on that page: https://playwright.dev/docs/api/class-fixtures
or linked to. I was reading about fixtures, but didn't that this fixture is available.
