### ISSUE TITLE
[Question] - Assertion against optional key in JSON, it is possible?

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#26768]
In Playwright, I prepare API tests that compare JSON with Response. For example: 

```
[...]
let dataSchema = {  "1": {
  "name": "Adam",
  "surname": expect.any(String),
  "access":  expect.any(String),
  },
  "2": {
    "name": "Jack",
    "surname": expect.any(String),
  },
  "3": {
    "name": "Anna",
    "surname": expect.any(String),
  }}
expect(await jsonData).toEqual(dataSchema);
```
Problematic for me are the keys that can be optional in above case "access" key, which one might appears/ is optional in every ID.
I wish do something like similar to Python Schema library:

```
[...]
  Optional('access'): str,
```

**Comment by aslushnikov** [comment]
@OSnuszka You can use [`objectContaining`](https://playwright.dev/docs/next/api/class-genericassertions#generic-assertions-object-containing) for this.

The following works for me:

```ts
import { test, expect } from '@playwright/test';

test('should work', async ({ }) => {
  const schema = {
    name: expect.any(String),
  };
  const data = {
    name: 'foo',
    age: 89,
  };
  expect(data).toEqual(expect.objectContaining(schema));
});
```
