### ISSUE TITLE
[REGRESSION]: Trace network and console tabs are not focused on the current step

### ISSUE THREAD

**Issue by romihemo1** [microsoft/playwright#26773]
**Context:**
- GOOD Playwright Version: 1.36.0
- BAD Playwright Version: 1.37.0-1.37.1
- Operating System: Mac
- Extra: Node v16.15.1

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
trace: "retain-on-failure"
```

**Describe the bug**

In the trace, we used to see the network requests and logs that were only relevant to the step we clicked on.
Since the new update, we see all the logs and network requests and responses in the whole run no matter which step we clicked on.
This used to be amazing for debugging what happened in a specific step!
Hope there is a chance you can bring it back

Old trace example:
![image](https://github.com/microsoft/playwright/assets/89925567/c64791fd-7df5-4cfa-9c0a-ba26fba26b42)
New trace example:
![image](https://github.com/microsoft/playwright/assets/89925567/2b4d4639-530b-4176-81f5-f82b799a3891)

**Comment by StasGrishaevTutu** [comment]
also noticed this problem +1

**Comment by esterspector** [comment]
Saw this, too +1

**Comment by dgozman** [comment]
In v1.38, you will be able to double-click on an action in the action list, which will select a timeframe the respective action took, and filter Console and Network tabs according to the timeframe.
