### ISSUE TITLE
[BUG] `UI Mode` not working with launching browser with `beforeAll` hook

### ISSUE THREAD

**Issue by JinCoreana** [microsoft/playwright#26774]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [macOS.13.4.1]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: "playwright",
 //I don't use globalSetup as I want to pass various log-in details as prop in beforeAll hook
  globalTeardown: "playwright/global-teardown.ts",
  projects: [
   {
      name: "chrome",
      use: {
        ...devices["Desktop Chrome"],
        baseURL: process.env.BASE_URL,
        screenshot: "only-on-failure",
        headless: process.env.HEADLESS === "true",
      },
    },
});
```

**Test file (self-contained)**

```js
test.describe("Test 1", () => {
  let page: Page;

  test.use({
    storageState: "playwright/.auth/email.json",
  });

  test.beforeAll(async ({ browser }) => {
  // I open a browser in this function and log-in. 
// Then it creates email.json file with the credential passed as props and return the `page` to be used in the below tests.
    page = await log_in({ browser, email: "xx@gmail.com", password: "password" });
  });

  test.afterAll(async () => {
    await page.close();
  });
  test("Test detail", async () => {
    await expect(page.locator(LOGO)).toBeVisible();
  });
});
```

**global-teardown**

```js
const globalTeardown = () => {
  const folderPath = "playwright/.auth";
//reset all json files upon finishing all tests
  fs.readdirSync(folderPath).forEach((file) => {
    const filePath = path.join(folderPath, file);
    fs.writeFileSync(filePath, JSON.stringify([]));
  });
};
export default globalTeardown;
```

**Steps**
- [Run the test in `UI Mode`]

**Expected**
- [At the end of all tests, `global-teardown` should be triggered to reset auth.json]

**Actual**
*Please note, the below works fine when not using UI Mode*
- [`global-teardown` setting is not triggered. ]

I'm not sure whether this issue is a bug or if I've misconfigured something. The primary concern is my intention to use multiple credentials by passing them as props in `beforeAll` hook. Consequently, I'm unable to use the `global setup`, and instead, I require the use of  `global teardown` to clear stored sessions once all tests are complete. This setting works perfectly in headed or headless testing but only UI mode is out of sync. Any guidance on how to address this issue would be greatly helpful. Thank you!

**Comment by aslushnikov** [comment]
@JinCoreana UI mode runs global setup once at startup, and runs global teardown once when it's shutting down.

Why don't you use `afterAll` hook to cleanup the files?

**Comment by JinCoreana** [comment]
> @JinCoreana UI mode runs global setup once at startup, and runs global teardown once when it's shutting down.
> 
> Why don't you use `afterAll` hook to cleanup the files?

Hi @aslushnikov,
Yes that's what I wanted with `global teardown`.
Since `afterAll` hook runs per test file, I needed something that triggers after the completion of all test files to reset the stored session.

So the first test file stores the logged-in session then that json file is used through the rest of the test files to skip log-in page. Then once all tests are complete, `global teardown` resets the json file by replacing its contents with` []`. This ensures that in the next test run, a fresh session is newly stored.

I wonder if `UI mode` is not supported unless `global-setup` is used?

**Comment by JinCoreana** [comment]
Hi @aslushnikov,
My bad!
`UI mode` works okay. I missed https://playwright.dev/docs/test-ui-mode#viewing-test-traces from your doc.
So it shows the traces when drilling down to the details.

However still don't know why `global teardown` does not work in UI mode.

**Comment by aslushnikov** [comment]
> I understood it should be triggered when closing the UI mode....

@JinCoreana yes, this is exactly the behavior we have today: we run `global teardown` once you close the UI moce window. Doesn't it work for you?

**Comment by JinCoreana** [comment]
> > I understood it should be triggered when closing the UI mode....
> 
> @JinCoreana yes, this is exactly the behavior we have today: we run `global teardown` once you close the UI moce window. Doesn't it work for you?

Hi @aslushnikov,
No, it doesn't function like that in my current configuration, even though the same codes work perfectly within the `global-setup` upon initiating the UI mode. If you require additional information, please let me know. Thank you :)

**Comment by aslushnikov** [comment]
@JinCoreana I'm confused - so far everything you described looks legit to me, and works as designed. So what exactly doesn't work?

**Comment by JinCoreana** [comment]
`global-teardown` does not know on closing UI mode
```
const globalTeardown = () => {
  const folderPath = "playwright/.auth";
//reset all json files upon finishing all tests
  fs.readdirSync(folderPath).forEach((file) => {
    const filePath = path.join(folderPath, file);
    fs.writeFileSync(filePath, JSON.stringify([]));
  });
};
export default globalTeardown;
```

**Comment by aslushnikov** [comment]
> global-teardown does not get triggered on closing UI mode

This behavior doesn't reproduce for me, unfortunately. And without a reproduction, there's not much we can do.
