### ISSUE TITLE
What are the plans for component testing?

### ISSUE THREAD

**Issue by arequejo** [microsoft/playwright#26778]
Originally posted as a discussion, posting here as suggested.

Hello! The company I work for is currently evaluating alternatives to jest for components testing with React, we know that Playwright's is in an experimental mode but we have loved doing E2E tests with it for quite some time already.

Upon our research, we stumbled upon #19536 so it definitely felt a bit discouraging compared to something like Cypress (no judgement intended). Have those plans changed in the last few months? Is it recommended to rely on third-party libs for things such as mocks/spy and such? Is there a public roadmap for component testing? Is there an estimated date for the non-experimental release?

Thank you so much for all the hard work, Playwright is such a joy to work with.

**Comment by aslushnikov** [comment]
> Is it recommended to rely on third-party libs for things such as mocks/spy and such?

@arequejo as of Aug 2023, this is the recommended approach.

>  Is there a public roadmap for component testing?

There's no public roadmap for component testing or any other feature. Playwright evolves according to the user feedback with a monthly cadence.

> Is there an estimated date for the non-experimental release?

There's no estimated date as well, but we will appreciate if you give it a try and share your feedback [here](https://github.com/microsoft/playwright/issues/7148). Knowing what worked well and didn't work well will help us to evaluate experiment.
