### ISSUE TITLE
[BUG] page.route() is not waiting until network response due to which web assertion fails -with the value undefined 

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#26788]
### System info
- Playwright Version: 1.36.2
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

I would like to parse the response to derive finalRound then use that value for web assertion toHaveText()
I see it pirnt finalRound undefined in the console., 

```javascript
let finalRound;
 await page.route('**/reports/banner/base/DAL/round/**', async route => {
                const response = await route.fetch();
                const json = await response.json();
                const result = JSON.stringify(json)
                console.log("Response:" + JSON.stringify(json));
                const round = JSON.parse(result).banner.description;
                console.log('Bid Round: ' + round);
                finalRound = await round.split('Awards for Round ')[1].trim().split('are final')[0]
                await route.continue();
            }, 1);

await page.getByTestId('orders).click();
console.log("finalRound:" + await finalRound)
//web assertion
await expect(this.page.getByTestId('round').locator(.react-select__single-value)).toHaveText(await finalRound)
```

and I don't see the problem when i use page.waitForResponse instead of page.route(), why only page.waitForResponse waits for the response, but page.route() doesn't?

**output:** 
finalRound: undefined
Response:  it printed actual response
Bid Round: 5

and the test fails that toHaveText should have an argument either string or reg expression,  as the text value is undefined when it does web assertion.

wondering why page.route() is not parsing the response and proceeding to perform web assertion - toHaveText()?

**Comment by aslushnikov** [comment]
@InduKrish This is more of a JavaScript question rather than a Playwright question. You should have `finalRound` as a promise, and resolve it later on.

Here's an example:

```ts
let finalRoundCallback;
const finalRoundPromise = new Promise(x => finalRoundCallback = x);
await page.route('**/reports/banner/base/DAL/round/**', async route => {
    const response = await route.fetch();
    const json = await response.json();
    const result = JSON.stringify(json)
    console.log("Response:" + JSON.stringify(json));
    const round = JSON.parse(result).banner.description;
    console.log('Bid Round: ' + round);
    finalRoundCallback(await round.split('Awards for Round ')[1].trim().split('are final')[0]);
    await route.continue();
}, { times: 1 });

await page.getByTestId('orders').click();
console.log("finalRound:" + await finalRoundPromise)
//web assertion
await expect(this.page.getByTestId('round').locator(.react-select__single-value)).toHaveText(await finalRoundPromise)
```

Hope this helps!
