### ISSUE TITLE
[Question] Issue with Passing and Retrieving Variables in Playwright Tests for globalTeardown.ts

### ISSUE THREAD

**Issue by samsuthen** [microsoft/playwright#26784]
I'm encountering a problem with passing and retrieving variables within my Playwright tests. I'm trying to maintain a count of passed and failed tests, and I'm using environment variables to store these counts throughout my test suite. However, I'm facing challenges when trying to access and update these variables within teardown.

The issue seems to be related to how I'm setting and accessing the environment variables. I've tried different approaches, including using the process.env object to store and retrieve the counts, as well as using a helper class to manage the counts. However, none of these approaches have yielded the expected results.

`let passCount = 0;
let failCount = 0;

test.afterEach(async ({ helper }, testInfo) => {
  if (testInfo.status !== "passed") {
    helper.sendFailureNofitication(process.env.app_job_notify_http_failure, currRecord.dashboard_name, "Error Message");
    helper.writeFailedRecordToRetryCSV(currRecord)
    failCount++;
    process.env.app_fail_count = failCount.toString(); 
  } else {
    passCount++;
    process.env.app_pass_count = passCount.toString();
  }
});`

globalTeardown.ts

`import logger from "./src/app.qualys.utils/logger";

async function globalTeardown() { 
  const passCount = process.env.app_pass_count; 
  const failCount = process.env.app_fail_count; 
  logger.info(`Total passes: ${passCount} Total failure: ${failCount}`)
}

export default globalTeardown;`

environment variables:
`app_pass_count = ""
app_fail_count = ""`

I expect the passCount and failCount to be updated and correctly retrieved in the teardown file. However, the counts appear to be "empty" even though some tests have passed.
```[tasklist]
### Tasks
```

**Comment by MindaugasMateika** [comment]
I would suggest to look into custom reporters - https://playwright.dev/docs/test-reporters#custom-reporters. Instead of this rather complex logic of updating env variables you could simply calculate passed/failed/etc in custom reporter and achieve the same thing with much simpler implementation.

**Comment by trytoautomate** [comment]
Thank you for the response! 

The reporter implementation is effective in producing the desired results. However, I'm interested in extracting the dashboard name from my test in order to push the Teams notification about the failure of a specific dashboard. Is there a method to achieve this?"

Code:

`import type { FullConfig, FullResult, Reporter, Suite, TestCase, TestResult, } from "@playwright/test/reporter";
import Helper from "./helper";
import logger from "./logger";

let passCount = 0
let failCount = 0

class myReporter implements Reporter {

    onTestEnd(test: TestCase, result: TestResult): void {
        if(result.status !== 'passed'){
            failCount++
        } else {
            passCount++
        }
        logger.info(`test total pass: ${passCount} total fail: ${failCount}`)
    }

    onEnd(result: FullResult): void | Promise<void> {
        const helper = new Helper()
        helper.sendSummaryNotification(process.env.app_job_notify_http_summary, passCount, failCount)
        logger.info(`Final total pass ${passCount} total fail ${failCount}`)
    }
}

export default myReporter;`


Test file is:

`const records = parse(fs.readFileSync(path.join(process.cwd(), process.env.app_qualys_filename)),
  { columns: true, skip_empty_lines: true }
);

for (const record of records) {
  test(`Qualys dashboard: ${record.dashboard_name}`, async ({ page, loginPage, logoutPage, baseFunctions, mailer, dashboard, }) => {
  });
}`

**Comment by MindaugasMateika** [comment]
<I'm interested in extracting the dashboard name from my test

Is dashboard name in test title? Where did you get dashboard name in your previous approach?

**Comment by samsuthen** [comment]
I used to get it from the record. 

const records = parse(fs.readFileSync(path.join(process.cwd(), process.env.app_qualys_filename)),
{ columns: true, skip_empty_lines: true }
);

for (const record of records) {
test(Qualys dashboard: ${record.dashboard_name}, async ({ page, loginPage, logoutPage, baseFunctions, mailer, dashboard, }) => {
});
}

**Comment by MindaugasMateika** [comment]
Assuming all your tests follow the pattern of `Qualys dashboard: ${record.dashboard_name}` then you could extract dashboard name using regex

```
onTestEnd(test: TestCase, result: TestResult): void {
  const regex = /Qualys dashboard: (.*)/
  const match = testTitle.match(regex)

  if (match && match[1])  console.log(`Dashboard name is: ${match[1]}`)
}
````

Alternatively, you could also read your records file in the custom reporter and do more precise extracting dashboard name from test file using dashboard values from file.

**Comment by samsuthen** [comment]
Thank you! much appreciated.
