### ISSUE TITLE
[BUG] Playwright doesn't add cookies after loading the page

### ISSUE THREAD

**Issue by EASidorov** [microsoft/playwright#26786]
Hello all, i am trying to authorize via access token cookie, after loading, cookies are empty and i am not authorized.
I take valid access token from devtools/application or via http request. If i add cookie after neo_page.goto(URL) i can see cookies in devtools after i do neo_page.reload() cookies delete also

### System info
- Playwright Version: [v1.37.0]
- Operating System: [macOS 13.5.1]
- Browser: [All]
- Other info: python 3.11

### Source code
```
ACCESS_TOKEN = '-irc7Z6l8Jb-PBTzG2gUrcYOvmvXlvSaxhNIPHQkzcI'
ACCESS_TOKEN_END_TIME = '2324538708715'
REFRESH_TOKEN = '1aakPGAPZaHkbhQu9PTs6J96MWGIuvjcWQJ8Rw5aQD4'
URL = "http://***.net"
print(r1.json())

pw = sync_playwright().start()
browser = pw.chromium.launch(headless=False, slow_mo=100)
new_context = browser.new_context()


new_context.add_cookies([{'name': 'ACCESS_TOKEN', 'value': ACCESS_TOKEN, 'url': URL},
                     {'name': 'ACCESS_TOKEN_END_TIME', 'value': ACCESS_TOKEN_END_TIME, 'url': URL}])

neo_page = new_context.new_page()
print(neo_page.context.cookies())

neo_page.goto(URL)

print(neo_page.context.cookies())
time.sleep(30)
```

Terminal output
```
{'accessToken': 'gc_i7Qzlxr44XgUWx4fNlq-FqRbfVDxtawZBcwBFk', 'accessTokenLifetime': 631152000, 'refreshToken': 'Iu6hNF72EYpYSg2IXXtHUvM5I6vnFDOqQjc-NSo_VsQ', 'signingToken': None, 'signingStatus': 5, 'mfaList': []}
[{'name': 'ACCESS_TOKEN', 'value': 'gc_i7Qzlxr44XgUWx4fNlq-FqRbfVDxtawZBcwBFk', 'domain': '***.net', 'path': '/', 'expires': -1, 'httpOnly': False, 'secure': True, 'sameSite': 'Lax'}, {'name': 'ACCESS_TOKEN_END_TIME', 'value': '631152000', 'domain': '***.net', 'path': '/', 'expires': -1, 'httpOnly': False, 'secure': True, 'sameSite': 'Lax'}]
[]
```

**Steps**
- [Run the test]

**Expected**

Opens url with authorized user, cookies accessible

**Actual**

Opens url unauthorized, no cookies in browser

**Comment by aslushnikov** [comment]
@EASidorov this could happen if the page is actually removing cookies itself. I'm afraid there's not much we can do in this case.

If you do believe this is a Playwright issue, please re-file with a repro that we can run & debug locally!
