### ISSUE TITLE
[Feature] add the ability to queue up test in Playwright Test for VSCode

### ISSUE THREAD

**Issue by rufi0h** [microsoft/playwright#26789]
The Playwright Test for VSCode extension only allows for you to queue up one test file at a time or a folder at a time.
 I think it would be a time saver If while running a test you could queue up other test to run after that one is done. 

example
Folder 
-test 1
-test 2
-test 3
Folder2
-test 4
-test 5
-test 6

there are some scenarios where I would just like to run the test 1, test 2 , test 4, and test 5 and as of right now you can only queue up one of those at a time or the whole folder. If I could start test 1, then queue the rest of them to be run afterwards it would save time

**Comment by aslushnikov** [comment]
@rufi0h this seems to be a feature for the VSCode since Playwright extension uses VSCode testing integration. Could you please file it to VSCode folks instead?

**Comment by rufi0h** [comment]
No problem, thanks for pointing me in the right direction
