### ISSUE TITLE
[BUG] Built-in rest client is causing performance problems on our database

### ISSUE THREAD

**Issue by philipfong** [microsoft/playwright#26795]
Hi all. I apologize in advance if this specific issue becomes difficult to reproduce, but I wanted to highlight a potential problem as I've sunk quite a bit of time in trying to understand why our very modestly sized Playwright test suite was causing problems for our AWS Aurora MySQL database.

In our UI tests, we interact quite a bit with some rest endpoints in order to provision some test data. This pattern allows us to write succinct CRUD tests and presents the UI with a new entity for Playwright to interact with.

So our pattern might look like "give me a payload and uri", then send it off using Playwright ApiRequestContext. We'll parse the response body with `response.json()` to perhaps retrieve an ID, then call a `page.goto()` using that ID.

We abstract away the rest request types to some helpers which I will post below.

Long story short, we're finding that when we send a series of POST requests, our database CPU continues to climb until our web app is no longer accessible. Endpoints begin to fail, and even unrelated endpoints like `/auth` will fail as well.

The strange thing is that we have a pipeline of a few hundred API tests that use Jest & Supertest and those pass just fine. I decided to plug in Supertest in order to handle our rest requests and responses, and we no longer suffer from the database issues we were seeing with Playwright's implementation of their rest client.

I will share our "request helper" file here in case anything seems fishy with it. As you can see, this helper is simply designed to accept a url and payload and send it off via rest. Our API test suite that lives in a different repo also follows this same type of abstraction.

When I inspect the failures in the trace viewer, I don't see anything out of the ordinary. The headers are sending a content type and bearer token. And the jsonData sent is exactly as I expect it. I do see a new apiRequestContext with each request, but that seems expected.

Perhaps the Playwright rest client is not designed to be used in the way I've described? Or perhaps there is something wrong with the way I've abstracted these request types? Or maybe there is just something very wrong in our web app.

Thanks for reading.

```ts
import { test, expect, request, type Page, type Response } from '@playwright/test'
import { generateToken } from './tokenHelper'

const baseURL = `https://api.${process.env.TEST_ENV}.mytestwebsite.com`

const sendRequest = async (method: string, uri: string, role: string, payload?: any) => {
  const context: { [key: string]: any } = await request.newContext({ baseURL, ignoreHTTPSErrors: true })

  const headers: { [key: string]: string } = {
    'Content-Type': 'application/json',
  }

  if (role !== 'public') {
    const token = generateToken(role)
    headers['Authorization'] = token
  }

  const options = {
    headers: headers,
    data: payload,
  }

  const response = await (context[method] as (uri: string, options: any) => Promise<any>)(uri, options)
  return response
}

export const post = async (uri: string, payload: any, role = 'admin') => {
  return sendRequest('post', uri, role, payload)
}

export const postNoAuth = async (uri: string, payload: any, role = 'public') => {
  return sendRequest('post', uri, role, payload)
}

export const patch = async (uri: string, payload: any, role = 'admin') => {
  return sendRequest('patch', uri, role, payload)
}

export const get = async (uri: string, role = 'admin') => {
  return sendRequest('get', uri, role)
}

export const del = async (uri: string, role = 'admin') => {
  return sendRequest('delete', uri, role)
}

... some other unrelated helpers here below

```

**Comment by aslushnikov** [comment]
@philipfong it looks like your DB doesn't close connection after responding. To fix this, could you please try [disposing](https://playwright.dev/docs/next/api/class-apirequestcontext#api-request-context-dispose) the `APIRequestContext` after you send the request?

**Comment by aslushnikov** [comment]
@philipfong another thought: does your DB respond with streams? In this case, it will keep connection, consume CPU, and so on.

I'm surprised this would work with supertest though - unless they don't support streams as responses and close connection right away.

**Comment by philipfong** [comment]
I'm having some difficulty reproducing the issue originally described. I'll close this. Thanks for the input.
