### ISSUE TITLE
[BUG]The configuration of toMatchSnapshot cannot override the global configuration

### ISSUE THREAD

**Issue by gongshun** [microsoft/playwright#26804]
### System info
- Playwright Version: [v1.1.35.1]
- Operating System: [macOS 13.4]
- Browser: [All]
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  expect: {
    toMatchSnapshot: {
        maxDiffPixels: 1
    },
  },
});
```

**Test file (self-contained)**

```js
it('', async ({ page }) => {
  const design = await page.$('.data-menu-design');
  const designImg = await (design as ElementHandle).screenshot({ type: 'jpeg' });
  await expect(designImg).toMatchSnapshot({
    name: 'design.jpg',
    maxDiffPixelRatio: 0.05,
  });
});
```

**Steps**
- [Run the test]

**Expected**

test passed.

I guess it is because the `maxDiffPixelRatio` configured by `toMatchSnapshot` can only override the global `maxDiffPixelRatio`, but not `maxDiffPixels`

Is this a bug, or is my usage wrong. What should I do so that he is not affected by the global configuration?

**Actual**

![image](https://github.com/microsoft/playwright/assets/29347231/31df7bfb-42df-4e65-9656-91f0dc623248)

**Comment by pkirkovsky** [comment]
I tried to repro this, and it seems that both can be overridden but `maxDiffPixels` takes priority over `maxDiffPixelRatio` both in the config and in the test itself.

**Comment by dgozman** [comment]
@gongshun If you would like to only take `maxDiffPixelRatio` into account, reset `maxDiffPixels` explicitly:

```js
await expect(designImg).toMatchSnapshot({
    name: 'design.jpg',
    maxDiffPixelRatio: 0.05,
    maxDiffPixels: Infinity,
});
```

However, I'd recommend using [`toHaveScreenshot`](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1) instead:

```js
await expect(page.locator('.data-menu-design')).toHaveScreenshot('design.png', {
  maxDiffPixelRatio: 0.05,
  maxDiffPixels: Infinity,
});
```
