### ISSUE TITLE
[BUG] Android page.close() or context.close() accumulate tabs

### ISSUE THREAD

**Issue by Slapbox** [microsoft/playwright#26800]
### System info
- Playwright Version: [v1.37]
- Operating System: Ubuntu 23.04
- Browser: Chrome on Android
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
const config = {
  testMatch: /.*\.playwright-test\.js/,
  fullyParallel: true,
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
  },
};
export default config;
```

**Test file (self-contained)**

```js
const { _android: android } = require('playwright');

(async () => {
  const [device] = await android.devices();
  const context = await device.launchBrowser();
  const page = await context.newPage(); // Using something like ` const [page] = context.pages` yields same problem

  await context.close(); // Tried closing both items in both orders, and adding 1 second delays between, but no help
  await page.close();
})();
```

**Steps**
- Count open tabs
- Run the repro code
- Count open tabs

**Expected**

Tab count does not increase on each run

**Actual**

Tabs increase endlessly for each run

**Comment by aslushnikov** [comment]
@Slapbox that's a GUI artifact; in reality, these pages do not exist, so it should not affect the behavior in any way.

Actually, if you change lines the following way, then the page counter would not grow:

```ts
const { _android: android } = require('playwright');

(async () => {
  const [device] = await android.devices();
  const context = await device.launchBrowser();
  const [page] = context.pages()

  await page.close();
  await context.close();
  await device.close()
})();
```

**Comment by Slapbox** [comment]
Thanks for your reply @aslushnikov. I can confirm that works, and actually it works even with just `await page.close()` and nothing else. I must have made some mistake in testing all the possible combinations.

Notably this will not work it you use `const page = context.newPage()` though, and that seems to me to be a bug; albeit rather trivial.

I'll leave if to you whether this issue should remain open or not since there technical is a tiny bug. Thank you again!

**Comment by Slapbox** [comment]
Actually, it also seems that skipped tests continue to accumulate pages even so, but this could be a quirk of our testing setup. This is probably why I thought the issue occurred in the first place.

**Comment by aslushnikov** [comment]
@Slapbox sweet, we'll close this since Android Chrome GUI is outside of our control.
