### ISSUE TITLE
Can I exclude console.log information when checking TC information?

### ISSUE THREAD

**Issue by jsjji89** [microsoft/playwright#26801]
I am checking the test information with the command below.
npx playwright test --workers=1 src/--list --reporter=json

Console.log from hooks such as test() and beforeEach doesn't seem to be output, but console.log from upper level test.describe() or global console.log values  seems to be in json data.

In the code below, the '1st test' and '2nd test' values ​​are output.
Can I also exclude console.logs declared in these locations?

Of course, I don't have to use console.log, but this is different for each user, so I'm asking because I think it can cause problems.

example code

const { test, expect} from '@playwright/test';
console.log('1st test');

test.describe('test', async() => {
  console.log('2nd test');
  test.beforeAll(async() => { console.log('3rd test') });
  test('test 1', async() => { console.log('last test') })
})

**Comment by aslushnikov** [comment]
@jsjji89 I assume you don't like `console.log` statements output since they corrupt the JSON output. To fight this, you can specify JSON output file using the ENV variable: https://playwright.dev/docs/next/test-reporters#json-reporter

Would this fix your issue?

**Comment by jsjji89** [comment]
@aslushnikov Oh, It works!!
Thanks!!
