### ISSUE TITLE
[Feature] cleanup methods

### ISSUE THREAD

**Issue by e-oz** [microsoft/playwright#26821]
Please provide cleanup methods, that would run similar after each test and after all tests, but, unlike `afterAll()` and `afterEach()`, they would be executed even if there are failures.

For example:

```ts
test.setupAll(async ({ channel, browser }) => {
  //
});

test.setupEach(async ({ channel, page }) => {
  //
});

test.teardownEach(async ({ channel, page }) => {
  //
});

test.teardownAll(async ({ channel, browser }) => {
  //
});

```

They would run in this order:

`setupAll()` [1]
`setupEach` [N]
`teardownEach` [N] 
`teardownAll` [1]

---

As an alternative, please consider adding an option to the config, that would run `afterEach()` and `afterAll()` even in case of test failures.

**Comment by MindaugasMateika** [comment]
Works for me with 1.37.1, hooks are executed after failure

```
import { test, expect } from '@playwright/test';

test('fail', async ({ page }) => {
  console.log('test run')
  expect(false).toBeTruthy()
});

test.afterEach(async () => {
  console.log('after each')
})

test.afterAll(async () => {
  console.log('after all')
})
```

Output:

```
Running 1 test using 1 worker
[chromium] › example.spec.ts:3:5 › fail
test run
after each
after all
```

I would suggest to file a bug issue with reproducible code.

**Comment by e-oz** [comment]
Maybe you should file a bug because the documentation says that nothing will be executed after a failure: https://playwright.dev/docs/test-retries#failures

**Comment by aslushnikov** [comment]
@e-oz aftereach/afterall hooks run even if test fails - this is by design. I enhanced documentation to make it less confusing.
