### ISSUE TITLE
[REGRESSION]: Can't use Playwright with for loop to scrape mutlipltiple websites array

### ISSUE THREAD

**Issue by MOSTAFAEZZAT** [microsoft/playwright#26820]
**Context:**
- GOOD Playwright Version: [what Playwright version worked nicely?]
- BAD Playwright Version: [what Playwright version doesn't work any more?]
- Operating System: [e.g. Windows, Linux or Mac]
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**the code scrape only one link and stops doesn't loop**
```javascript
const {playwright} = require('playwright');

const scrapeCrunchbaseWebsite = (async () => {

  var crunchbaseData = await getCrunchbaseLink();
  console.log(crunchbaseData);

  for (i = 4; i < 10; i++) {

    const browser = await playwright.firefox.launch({
      headless: true,
    });
    const context = await browser.newContext();
    var crunchbaseOrgName = crunchbaseData[i];
    var crunchbaseOrgLink = crunchbaseData[i + 1];
    console.log(crunchbaseOrgLink);
    const page = await context.newPage();
    await page.goto(
      crunchbaseOrgLink
    );
    const html = await page.evaluate(() => document.body.innerHTML); // Save the page's HTML to a variable

    // console.log(html);
    const $ = cheerio.load(html); // Use Cheerio to load the page's HTML code
    // Continue writing your scraper using Cheerio's jQuery syntax

    await structureCrunchbaseSummaryData($);

    // finanicalValues.indexOf("Acquisitions");

    i = i + 2;
    await browser.close();
    sleep(1000);

  }


})();
```

**Describe the bug**

Add any other details about the problem here.

**Comment by aslushnikov** [comment]
@MOSTAFAEZZAT your code snippet is not runnable; and there's no error, no details, no playwright version, no OS - there's no way we can be helpful here.

Please, file a new issue, filling in the issue template properly so that we have at least some information to work with.

Thanks!

**Comment by MOSTAFAEZZAT** [comment]
@aslushnikov  Thanks I just submitted a new issue with all consider points you mentioned.
