### ISSUE TITLE
[Feature] Being able to set the poll interval of web-first assertions

### ISSUE THREAD

**Issue by nbaldzhiev** [microsoft/playwright#26837]
The use case is that there is a HTML element which appears for a very short period of time, on average for around 200 ms. I am noticing that web-first assertions, such as `await expect(locator).toBeVisible()` or `await expect(locator).toHaveText() are not able to catch the existence of that element. My explanation is that the poll interval for web-first assertions is bigger and, as a result, Playwright is almost never able to see this element.

My idea with this feature request is to be able to specify the poll interval in those assertions, so that I can pass a very low value such as 50 - 100 ms.

I am attaching a GIF showcasing how long the HTML element is visible for. The element contains the text `Updated` and then for a short period of time `Autosaving map...` appears, which is what Playwright is not able to catch. The latter appears as a result of some actions by the user within that page, i.e. moving, clicking stuff, then the map "autosaves".

[GIF](https://s11.gifyu.com/images/SgaRD.gif)

**Comment by pavelfeldman** [comment]
It is unlikely that your use case can be tested reliably even with the lowest polling intervals. Playwright and browser are both async, so you'll be missing the temporary message sometimes.

Your only workaround is to run a mutation observer in the page itself that will check DOM modifications after every browser task:

```js
// Start the autosaving observer
const autosavingPromise = page.locator('#element-that-will-contain-message').evaluate(container => {
  return new Promise(resolve => {
    const observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type !== 'childList' && mutation.type !== 'characterData')
          continue;
        const targetNode = mutation.target;
        if (targetNode.textContent.includes('Autosaving map')) {
          observer.disconnect();
          resolve();
        }
      }
    });
    observer.observe(container, { childList: true, subtree: true, characterData: true });
  });
});

// Trigger autosave
await page.click(...);

// Wait for autosave to finish
await autosavingPromise;
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by aroman** [comment]
> Closing as per above, please feel free to open a new issue if this does not cover your use case.

@pavelfeldman running into the same issue here. is there any way to adapt the mutation observer workaround you provided above to support searching for arbitrary text content (e.g. a locator) without knowing a specific locator ahead of time?

e.g. something like:

`await waitUntilVisible('some text')`

or even more generically;

`this.page.getByRole('button', { name: 'some button' }).waitUntilVisible();`

i find it a bit confusing that playwright doesn't even seem to document what the auto-retry intervals _are_, though I understand they aren't necessarily reliable due to the nature of asynchronous communication between playwright and the browser

**Comment by aroman** [comment]
here's what i ended up doing...

```ts
async function waitUntilVisible(
  page: Page,
  textToSearchFor: string,
  { ignoreCase } = { ignoreCase: true }
) {
  return page.evaluate(
    ({ textToSearchFor, ignoreCase }) => {
      const regex = new RegExp(textToSearchFor, ignoreCase ? 'i' : undefined);
      const bodyText = document.body.textContent;
      if (bodyText && regex.test(bodyText)) {
        return Promise.resolve();
      }
      return new Promise<void>((resolve) => {
        const observer = new MutationObserver((mutations) => {
          for (const mutation of mutations) {
            if (
              mutation.type !== 'childList' &&
              mutation.type !== 'characterData'
            )
              continue;

            const targetText = mutation.target.textContent;
            if (targetText && regex.test(targetText)) {
              observer.disconnect();
              resolve();
            }
          }
        });

        observer.observe(document.body, {
          childList: true,
          subtree: true,
          characterData: true,
        });
      });
    },
    { textToSearchFor, ignoreCase }
  );
}
```
