### ISSUE TITLE
[REGRESSION]: Can't use Playwright with for loop to scrape mutlipltiple websites in one run

### ISSUE THREAD

**Issue by MOSTAFAEZZAT** [microsoft/playwright#26847]
**Context:**
- GOOD Playwright Version: latest Playwright Library (not @test/Playwright)
- BAD Playwright Version: Probably  @test/Playwright latest one couldn't get any data from Crunchbase unlike Playwright Library Node.JS.
- Operating System: Windows 
- Extra: the scraping with multiple inputs websites links doesn't work or it seems isn't supported? I just have multiple websites links for Crunchbase so I want to make Playwright go in a loop but it stops after scraping one link. 

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
const {playwright} = require('playwright');

const scrapeCrunchbaseWebsite = (async () => {
  /* here's an array of 2 values but the real one is about 1000 link so it gets Oracle or any first link
   when it goes to the second one it stops
*/   
var crunchbaseData = ["https://www.crunchbase.com/organization/oracle", "https://www.crunchbase.com/organization/textura"]
 
  for (i = 0; i < 2; i++) {

    const browser = await playwright.firefox.launch({
      headless: true,
    });
    const context = await browser.newContext();
    var crunchbaseOrgLink = crunchbaseData[i];
 
    const page = await context.newPage();
    await page.goto(
      crunchbaseOrgLink
    );
    const html = await page.evaluate(() => document.body.innerHTML); // Save the page's HTML to a variable

    // console.log(html);
    const $ = cheerio.load(html); // Use Cheerio to load the page's HTML code
    // Continue writing your scraper using Cheerio's jQuery syntax
     // await structureCrunchbaseSummaryData($);

    // finanicalValues.indexOf("Acquisitions");

    await browser.close();
  }
})();
```

**Describe the bug**

the scraping with multiple inputs websites links doesn't work or it seems isn't supported? I just have multiple websites links for Crunchbase so I want to make Playwright go in a loop but it stops after scraping one link, also why must the function runs to be self-invoked? by the way I also used @test/Playwright it didn't work so I don't mind use any of them as long as it's gonna serve my purpose but @test/Playwright didn't get any data at all, I'm also not familiar with @test/Playwright as much as Playwright the Node.js library.

**Comment by lutsykvad** [comment]
@MOSTAFAEZZAT Launching a new browser for each URL can be inefficient. Try launching once and open new pages for each URL. Might solve your stopping issue.

```
const { test } = require('@playwright/test');
const cheerio = require('cheerio');

const crunchbaseData = ["https://www.crunchbase.com/organization/oracle", "https://www.crunchbase.com/organization/textura"];

for (const link of crunchbaseData) {
  test(`Scrape ${link}`, async ({ page }) => {
    await page.goto(link);
    const html = await page.evaluate(() => document.body.innerHTML);
    const $ = cheerio.load(html);
    // your scraping logic here.
  });
}
```

**Comment by pavelfeldman** [comment]
It is unclear what you are referring to as to a bug or regression.

**Comment by MOSTAFAEZZAT** [comment]
@pavelfeldman  @lutsykvad  Thanks guys the problem solved there was a return statement in one of the sub-nested-functions which stops the main scraping function, however why am I not allowed to use Playwright library as a function that I can invoke anytime but in all of Playwright I think it **must** be self-invoked with `(async ()  => {})();`, right?

Also Playwright the library gets the data of most of websites that overcome @test/Playwright and other like Puppeteer which website like Crunchbase and LinkedIn @test/Playwright for example doesn't get of it (Not sure if I'm not using Playwright Test correctly but maybe). 

But overall this's a Regression not a Bug
