### ISSUE TITLE
[BUG] LocatorAssertion not working with using locator.or

### ISSUE THREAD

**Issue by dpreindl** [microsoft/playwright#26842]
When trying to use `locator.or` in combination with `expect` an error is thrown - According to the documentation this should be possible.

### System info
- Playwright Version: [v1.38.0-alpha-sep-1-2023] & Version running on try.playwright.tech
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code
The issue can be reproduced using following link: https://try.playwright.tech/?l=playwright-test&s=96c0s01

OR

```js
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  const l1 = page.locator('.navbar__item').nth(0);
  await expect(l1.or(title)).toBeVisible();
});
```

**Expected**
According to [https://playwright.dev/docs/api/class-locator#locator-or](https://playwright.dev/docs/api/class-locator#locator-or ) using `expect` in combiniation with `locator.or` should work. - See the example:
```js
const newEmail = page.getByRole('button', { name: 'New' });
const dialog = page.getByText('Confirm security settings');
await expect(newEmail.or(dialog)).toBeVisible();
if (await dialog.isVisible())
  await page.getByRole('button', { name: 'Dismiss' }).click();
await newEmail.click();
```

**Actual**
The test throws an error
```
Error: expect.toBeVisible: Error: strict mode violation: locator('.navbar__item').first().or(locator('.navbar__inner .navbar__title')) resolved to 2 elements:
1) <b class="navbar__title text--truncate">Playwright</b> aka getByRole('link', { name: 'Playwright logo Playwright' })
2) <a href="/docs/intro" class="navbar__item navbar__l…>Docs</a> aka getByRole('link', { name: 'Docs' })

=========================== logs ===========================
expect.toBeVisible with timeout 5000ms
waiting for locator('.navbar__item').first().or(locator('.navbar__inner .navbar__title'))
============================================================
```

**Comment by pavelfeldman** [comment]
Locators in Playwright are strict. It means that it expects exactly one locator to resolve to a visible element when it expects it to match condition (isVisible). In your case, you should move nth(0) to after all to tell it that you are interested in any (first) match:

```js
import { test, expect } from '@playwright/test';

test('basic test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  const title = page.locator('.navbar__inner .navbar__title');
  const l1 = page.locator('.navbar__item');
  await expect(l1.or(title).nth(0)).toBeVisible();
});
```

**Comment by dgozman** [comment]
Action item: update docs to mention `first()` in `toBeVisible()`.
