### ISSUE TITLE
[BUG] No console output in Rust native module

### ISSUE THREAD

**Issue by samrg472** [microsoft/playwright#26859]
### System info
- Playwright Version:1.37.1
- Operating System: Windows 11
- Browser: None
- Other info:
May have an effect on all operating systems.
The Rust toolchain is required.

### Source code

**Link to the GitHub repository with the repro**

https://github.com/samrg472/playwright-bug-26859

**Steps**

See the GitHub repository for reproducing.

**Expected**

I expect the the `no console output` test to have output. The provided `has console output` test is an example workaround by executing JS from Rust.

**Actual**

The `no console output` test has no console output.

**Comment by pavelfeldman** [comment]
Does it appear if you run it from a simple Node JS program? Which stream does it print to?

**Comment by samrg472** [comment]
> Does it appear if you run it from a simple Node JS program? Which stream does it print to?

Yes, and it prints to standard output. The issue still occurs when using the error output stream.
