### ISSUE TITLE
[Feature]: Add ability to skip test after launch

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#26858]
Hello. We have a service that collects information about test runs in database and before each test run we check if it is disabled or not. This service can not only disable tests, but also mute temporarily unstable tests. Reasons why we use mutes:
- do not fail build in CI if flaky test fails. Just mute it (skip after run) and paint job to green
- sometimes tests fail for a while, but then they start to pass successfully (linked service/cdn/s3/et is broken). So there is no reason to skip them and waste developer time on fixing it. Moreover we mute only a certain number of tests from the total in order to not mute all tests
- testers checking the release of the service often need the results of running some muted tests (they can pass successfully on some retry)

So can we add ability to skip test after launch. Currently I get and error:
```
    Error: Test is skipped:

       6 |             await use();
       7 |
    >  8 |             test.skip();
         |                  ^
       9 |         },
      10 |         { scope: "test", auto: true }
      11 |     ],
```

When running code:
```
import { test as base, expect, TestInfo } from '@playwright/test';

const test = base.extend<{some: void}>({
    some: [
        async function({}, use) {
            await use();

            test.skip();
        },
        { scope: "test", auto: true }
    ],
});

test.only('test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
});

```

**Comment by pavelfeldman** [comment]
It sounds to me that you want to override the exit code of Playwright after examining the test results. Would returning exit code from a custom reporter work for you?

**Comment by DudaGod** [comment]
> It sounds to me that you want to override the exit code of Playwright after examining the test results. Would returning exit code from a custom reporter work for you?

Yes, it looks like that would solve our problem.

**Comment by DudaGod** [comment]
@pavelfeldman I unexpectedly found an opportunity to change result status on `Reporter.onTestEnd` method:
```
onTestEnd(test: TestCase, result: TestResult): void {
  if (shouldMute(result)) {
    result.status = 'skipped';
  }
}
```

In this case playwright not fails if I mark failed test as skipped. Is it expected behaviour? Can I use it in my fixture?
