### ISSUE TITLE
[Feature] Provide native window handle

### ISSUE THREAD

**Issue by greuelpirat** [microsoft/playwright#26852]
We have a special case where we would need the native window handle on Windows as `IntPtr`. Any chance to get it?

**Comment by pavelfeldman** [comment]
There is no notion of native windows is Playwright testing, so this would not be possible.

**Comment by pirate** [comment]
can this be reconsidered? CDP provides windowId as a native concept, and it is useful to be able to figure out what window tabs are in when driving a headful browser.
