### ISSUE TITLE
[Feature] Sequentially run two groups of scripts, and executing scripts of each group concurrently

### ISSUE THREAD

**Issue by deathdayss** [microsoft/playwright#26866]
Let's say I have one group of test scripts tagged with "@preparation" and another group of test scripts tagged with "@functionality". And I also have 4 workers to run all the scripts. 

I want to run all the scripts of "@preparation" using those 4 workers concurrently. After this is finished, the test scripts of "@functionality" need to be run concurrently by those 4 workers.  All scripts are in different files. For example:
@preparation:
p1.spec.ts, p2.spec.ts, p3.spec.ts, p4.spec.ts
@functionality:
f1.spec.ts, f2.spec.ts, f3.spec.ts, f4.spec.ts

The 4 files "p1.spec.ts, p2.spec.ts, p3.spec.ts, p4.spec.ts" need to be executed first. And after that, "f1.spec.ts, f2.spec.ts, f3.spec.ts, f4.spec.ts" need to be executed

 I'm looking for guidance on how to achieve this using the Playwright command-line tool, or if there are alternative methods to accomplish this goal.

The motivation behind this is to prevent potential interference between the '@preparation' and '@functionality' scripts, as running all '@preparation' scripts first may impact the execution of the '@functionality' scripts, which is undesirable.

**Comment by pavelfeldman** [comment]
You can try putting them into different projects and make one depend on the other. I.e. you put preparation into 'setup' project and functionality into test project. See https://playwright.dev/docs/test-global-setup-teardown#project-dependencies for details. Note though that since it is a dependency, if preparation does not pass, functionality is not tested.

**Comment by deathdayss** [comment]
> You can try putting them into different projects and make one depend on the other. I.e. you put preparation into 'setup' project and functionality into test project. See https://playwright.dev/docs/test-global-setup-teardown#project-dependencies for details. Note though that since it is a dependency, if preparation does not pass, functionality is not tested.

Can we find a way to make the "functionality" scripts still run even if some scripts of "preparation" fail?

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/26854
