### ISSUE TITLE
Error: Cannot find module '@playwright/test/jsx-runtime'

### ISSUE THREAD

**Issue by rubber-duck-software** [microsoft/playwright#26863]
**Context:**
- Playwright Version: 1.37.1
- Operating System: Mac
- Node.js version: v16.20.0
- Visual Studio Code version: 1.81.1
- Playwright for VSCode extension version: v1.0.15
- Browser: All

**Code Snippet**

See example repo https://github.com/rubber-duck-software/playwright-typescript-monorepo-tsx

**Describe the bug**

When attempting to run a test in a pnpm monorepo, I get error 
```
Error: Cannot find module '@playwright/test/jsx-runtime'
```

This is because the playwright component testing is using its own import source for the JSX transform. See 
https://github.com/microsoft/playwright/blob/94c1b749b2ce8057c3f117ca2dbbcc713d4d2511/packages/playwright-test/bundles/babel/src/babelBundleImpl.ts#L65-L69

While changing the import source may be desired behavior for component testing, this has far reaching consequences in a monorepo. Imagine some backend package uses https://react.email or https://react-pdf.org . Changing the import source for all jsx (even indirectly) imported in a playwright test could cause a variety of issues.

**Comment by pavelfeldman** [comment]
When Playwright transpiles test files on the fly, it has no knowledge of the JSX mode needed and/or the associated behavior the bundler may generate for those JSX constructs. The idea is that e2e tests would handle JSX in a best-effort manner, for example when some constants are defined in shared JSX files. If you have a specific semantics for your JSX and you'd like to test it, instead of pointing to the source code with JSX, e2e tests should refer to the actual bundled code. That way you are doing true e2e testing of your system rather than relying on fragments of code interpreted in a best effort manner.

**Comment by pavelfeldman** [comment]
I'll close this as out of scope for Playwright e2e.

**Comment by rubber-duck-software** [comment]
Hi @pavelfeldman! Thank you for your quick response :) I appreciate your engaging on this issue. I want to provide a little background information on the issue and advocate for a change in playwright.

The Playwright docs say  (https://playwright.dev/docs/test-typescript)
> Playwright supports TypeScript out of the box. You just write tests in TypeScript, and Playwright will read them, transform to JavaScript and run.

So how does Playwright  transform my Typescript tests to Javascript? 
Currently the answer is something like “Playwright transforms your Typescript tests to Javascript without respecting the compiler options in your tsconfig.”

But TypeScript is a configurable language! The compilerOptions given to TypeScript can change the meaning of the code you wrote in dramatic ways!

TypeScript gives the user options like `jsx` and `jsxImportSource` . I want to advocate that Playwright adds support for these options. 

So, we agree that the root cause of the issue is that
> When Playwright transpiles test files on the fly, it has no knowledge of the JSX mode needed

But I don’t believe supporting these tsconfig options ought to be considered out of scope. It falls under the banner of “Supporting TypeScript out of the box”. 

With this in mind, would you consider a PR adding support for these JSX options?

**Comment by rubber-duck-software** [comment]
See #26884 for my suggested changes
