### ISSUE TITLE
[Feature] Ability to introspect javascriptEnabled

### ISSUE THREAD

**Issue by luixo** [microsoft/playwright#26864]
Hello,
I have a multiple of test suites to run, and for every page I want to add tests with JS disabled.
For js-enabled tests I use a custom hook that renders an element after React is done with hydration hence I'm ready to run the main part of the test.
I cannot run this for js-disabled environment though.

I'd like to have something like that in my `openPage` fixture:
```ts
openPage: async ({ page, browser }, use) => {
  await use(async (url) => {
    await page.goto(url);
    if (!browser.javascriptEnabled) {
      await page.locator("ready").waitFor({ state: "attached" });
    }
    await page.evaluate(() => document.fonts.ready);
  });
},
```

Currently, I had to implement a pretty unreliable solution:
```ts
openPage: async ({ page }, use, testInfo) => {
  await use(async (url) => {
    await page.goto(url);
    if (!testInfo.titlePath.includes("No JS")) {
      await page.locator("ready").waitFor({ state: "attached" });
    }
    await page.evaluate(() => document.fonts.ready);
  });
},
```

I believe there are several places the `javascriptEnabled: false` can get into the final config - `playwright.config.ts`, top-level test file statement and statement inside `descrbe` fn.
Probably, there's a merged config somewhere in the internals, can we expose at least some parts of it for introspection?

**Comment by pavelfeldman** [comment]
that would be `async ({ page, javaScriptEnabled }, use, testInfo)`.
