### ISSUE TITLE
[Feature] ability to set max failures relative to the total number of tests

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#26861]
Hello.

To my mind specify `maxFailures` as a percentage of the total number of tests is much more convenient than constantly maintaining a static value as the number of tests grows.

For example I have a small project with 100 tests and `maxFailures: 30` in the config. After some time the number of tests will increase to 300 and I will need to remember to change the value of `maxFailures` to `100` (1/3).

But if I able to set `maxFailures: 0.3` (percentage of the total number of tests) then it will always work correctly. It means I will not need to keep this value up to date as the number of tests grows.

**Comment by pavelfeldman** [comment]
Out of curiosity, with the larger test numbers, why would you bump maxFailures from 30 to 60 when the number of tests jumps 100 to 200. Isn't 30 still a good indicator of a bad run?

**Comment by DudaGod** [comment]
> Out of curiosity, with the larger test numbers, why would you bump maxFailures from 30 to 60 when the number of tests jumps 100 to 200. Isn't 30 still a good indicator of a bad run? Or are you mitigating potential retries due to flakiness?

To my mind there are few problems:
- service add new browser to an existing project -> the number of tests increases greatly
- the number of tests increases and stability decreases slightly (point which you mentioned)
- developers in our services sometimes check their changes in CI (we use browsers from cloud) and the number of tests may fall much more than 30. For example with diff in screenshots. Then the developer downloads result of run from the CI and accept screenshots locally

**Comment by pavelfeldman** [comment]
Sounds good, do you want to contribute a patch?

**Comment by DudaGod** [comment]
> Sounds good, do you want to contribute a patch?

Ok. I'll try to implement it soon.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
