### ISSUE TITLE
[Question] Can you specify executablePath when launching Firefox browser

### ISSUE THREAD

**Issue by Sneaky-Bot-Dev-Team** [microsoft/playwright#2687]
Is it possible to specify Firefox `executablePath` when launching a firefox browser with playwright ?

**Comment by mxschmitt** [comment]
Yes it is. But Firefox and WebKit only works with the Playwright specific bundled version. See here for a more detailed answer: https://github.com/microsoft/playwright/issues/2623#issuecomment-646051077

**Comment by Sneaky-Bot-Dev-Team** [comment]
Where can we find this specific versions to download ?

**Comment by Sneaky-Bot-Dev-Team** [comment]
I tried installing the latest Firefox version and the following path : /Applications/Firefox.app/Contents/MacOS/firefox but it didn't seem to work.

**Comment by mxschmitt** [comment]
Yep, as I mentioned, they won't work. Why do you want to specify the path?

You could potentially build the download URLs yourself see [here](https://playwright.azureedge.net/builds/firefox/1116/firefox-linux.zip) and the latest [revisions](https://unpkg.com/playwright@1.1.1/browsers.json). Example:
https://playwright.azureedge.net/builds/firefox/1116/firefox-linux.zip

**Comment by Sneaky-Bot-Dev-Team** [comment]
I need to download it separately as I use Playwright inside of an Electron app that I package using electron-builder. Unfortunately, Firefox don't get packaged and I get this error when running the packaged app : 

```
DevTools listening on ws://127.0.0.1:51668/devtools/browser/d1c49d93-46fd-45e6-a3d4-041c0a270bb4
(node:4495) UnhandledPromiseRejectionWarning: Error: Failed to launch browser: Error: spawn /Users/leonard/Library/Caches/ms-playwright/firefox-1106/firefox/Nightly.app/Contents/MacOS/firefox ENOENT
```

**Comment by Sneaky-Bot-Dev-Team** [comment]
I downloaded the folder you sent and set the executable path to : /Users/myname/Downloads/firefox/firefox

Unfortunately I got this error : 
```

[1] TypeError: Cannot read property 'message' of undefined
[1]     at ProgressController.run (myprojectpath/node_modules/playwright/lib/progress.js:85:51)
[1]     at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

**Comment by mxschmitt** [comment]
Gotcha, then you probably have to include either the browser binaries into your electron app or implement / use this download handling manually: https://github.com/microsoft/playwright/blob/4af8c6831e5c1966343777960c546a11960202c3/src/install/browserFetcher.The install methods are also getting [bundled](https://unpkg.com/browse/playwright@1.1.1/lib/install/browserFetcher.js) into the official playwright NPM package, but there are no types etc. because its nothing which would be officially supported. 

For mac it would be: https://playwright.azureedge.net/builds/firefox/1116/firefox-mac.zip

**Comment by Sneaky-Bot-Dev-Team** [comment]
Great ! Thanks for the quick reply !

**Comment by Sneaky-Bot-Dev-Team** [comment]
What would be the download link for windows (https://playwright.azureedge.net/builds/firefox/1116/firefox-win.zip and https://playwright.azureedge.net/builds/firefox/1116/firefox-windows.zip don't work) ?

**Comment by Sneaky-Bot-Dev-Team** [comment]
Just figured it out actually, it is :       

- win32  : https://playwright.azureedge.net/builds/firefox/1116/firefox-win32.zip

- win64 :  https://playwright.azureedge.net/builds/firefox/1116/firefox-win64.zip

**Comment by Sneaky-Bot-Dev-Team** [comment]
Do you know where I can get similar download links but for webkit ?

**Comment by mxschmitt** [comment]
See here how the paths are generated: https://github.com/microsoft/playwright/blob/master/src/install/browserFetcher.ts#L53

**Comment by Sneaky-Bot-Dev-Team** [comment]
Cool, thanks a lot for your precious help !
