### ISSUE TITLE
[BUG]: locator picker not working in iframe in UI mode

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#26878]
### System info
- Playwright Version: [^1.38.0-alpha-sep-4-2023]
- Operating System: [Mac]
- Browser: [Chromium]
- Other info:

### Source code

- [yes ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://stackblitz.com/');
  await page.getByRole('button', { name: 'Vite' }).click();
  await page.getByRole('link', { name: 'vanilla Vite' }).click();
  const iframe = page.frameLocator('iframe[title="Preview page"]')
  await iframe.getByRole('button', { name: 'count is 0' }).click();
  await expect(iframe.getByRole('button', { name: 'count is 1' })).toBeVisible();
});
```

**Steps**
- [Run the test]
- [Open UI mode]
- [try to use locator picker to get the button with count is 1]

**Expected**
It should give me the locator when I use the pick locator option

**Actual**

it just acts like a webpage rather than giving me a locator

**Comment by NikkTod** [comment]
Thank you playwright team @debs-obrien, @pavelfeldman, I was also able to reproduce this on our side.

I have created a similar iframe issue to that one within the locator picker on Codegen (https://github.com/microsoft/playwright/issues/23349), would be very helpful if you can fix both problems, as in our project we have to deal with a lot of iframes.
