### ISSUE TITLE
[Feature] Support validating PWA installation

### ISSUE THREAD

**Issue by NotWoods** [microsoft/playwright#26875]
I'd like to test installing a PWA and checking that it succeeds. Essentially, I want playwright to go through the browser menu and hit "Install <appname>" then check that a new shortcut is created.

Related: 
- https://github.com/microsoft/playwright/issues/19677 (about service workers, not PWA install)
- https://github.com/microsoft/playwright/issues/26853 (requires opening an installed PWA)

**Comment by pavelfeldman** [comment]
Installed PWA experience is not a part of the web platform. Browsers will do what they find necessary to implement the 'installed' behavior. There is no way for Playwright to test that.
