### ISSUE TITLE
Screen recording and screenshots are not getting attached in playwright HTML report

### ISSUE THREAD

**Issue by Tushar7337** [microsoft/playwright#26873]
### System info
- Operating System: [ Windows ]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code

import { test, expect } from '@playwright/test';

test('Admin Login', async ({ page }) => {

  await page.goto('http://127.0.0.1:5173/auth/login');
  await page.setViewportSize({ width: 1920, height: 1080 });

  const now = new Date();
  const formattedDate = `${now.getDate()}${now.getMonth() + 1}${now.getFullYear() % 100}`;  // Generate a date string in the format "DDMMYY"

  const formattedTime = `${String(now.getHours()).padStart(2, '0')}${String(now.getMinutes()).padStart(2, '0')}`;  // Generate a time string in the format "HHMM"

  const fileName = `${formattedDate}_${formattedTime}`.replace(/\\/g, '_');         // Combine date and time for the filename and replace backslashes with underscores

  const folderName = fileName;
  const fs = require('fs');
  try {
    if (!fs.existsSync("D:\\" + folderName)) {
      fs.mkdirSync("D:\\" + folderName);
    }
  }
  catch (err) { console.error(err); }

  const screenshotPath = `D:\\${folderName}\\${fileName}`;                         // Giving path to save the screenshots

  await page.screenshot({ path: `${screenshotPath}-login_screen.png` });
  //await page.screenshot({ path: `${fileName}-login_screen.png` });                 // Capture a screenshot with the formatted date and time in the filename

  //await page.screenshot ({path : Date.now() + 'screenshot1.png'})
  await page.getByPlaceholder('Email').click();
  await page.getByPlaceholder('Email').fill('admin@gmail.com');

  await page.getByPlaceholder('Password').click();
  await page.getByPlaceholder('Password').fill('Pass1234');

  await page.getByRole('button').first().click();
  await page.getByRole('button', { name: 'Sign In' }).click();

  await page.screenshot({ path: `${screenshotPath}-Dashboard.png` });
  await page.getByText('Logout').click();

  await page.getByRole('button', { name: 'Yes, Log me Out' }).click();

});

or

**Config file**
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    **trace: 'on-first-retry',
    video:'on',
    screenshot:'on'**
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome']},
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
```

**Test file (self-contained)**


**Expected**

After running the above test screenshot should get attached in HTML report
Also screen recording for test also get attached

**Actual**

Screenshot and video recording are not getting attached in HTML report

https://app.screencast.com/w5C6nXhKdu8oH

https://app.screencast.com/Tcc3Y0ISTy7mQ

**Comment by pavelfeldman** [comment]
Please follow the issue template so that we could reproduce and fix your issue.
