### ISSUE TITLE
[Feature Request] Require support to run a group of spec files in single browser Instance

### ISSUE THREAD

**Issue by YashaswiniGowri** [microsoft/playwright#26870]
Hello, 
Please check my feature request below:

**Case**: I have a group of spec files which need to be run sequentially in a single browser instance. But Playwright is opening new browser instance for each spec file sequentially one after the other.
As each browser closes its own session I have to login again and again in each browser. 
I do not want to use Browser context here because I want to test session in sequential run on single browser instance.

Please let me know If this can be done in Playwright as of now. if not please implement the feature as this is very important in sequential run testing in bigger test suites.

**Comment by pavelfeldman** [comment]
Your use case follows discouraged practice of a long sequence of inter-dependent tests, that is why it is not supported well in Playwright. At your own risk, you can place your tests in helper files and then include them all in one spec file. That way Playwright would think they all belong to that spec file. Note though that UI mode and VS Code extension will be slightly confused with this setup, so tooling support will not work at its full power.

As for supporting it in Playwright as is, we would not want to add support for a discouraged practice and as such, we would default to this best-effort support via helper files.
