### ISSUE TITLE
Getting error as Expected String got Object

### ISSUE THREAD

**Issue by PujaP4** [microsoft/playwright#26874]
I m using Page Object model and got this error
![image](https://github.com/microsoft/playwright/assets/144147474/9f778246-b09f-4ffa-9a53-3c119e819ae5)

TestFile
![image](https://github.com/microsoft/playwright/assets/144147474/4ef6d27d-da6d-4c50-af76-5ace45c78bec)

pageObjectClass:
![image](https://github.com/microsoft/playwright/assets/144147474/ac3d74c2-1490-49de-be9a-7f91c4516ad0)

How can I handle this error?

**Comment by pavelfeldman** [comment]
It is hard to reproduce the screenshots, you also didn't provide source of testMethods.ts where the actual error is. Please follow the issue template to file something we can reproduce and look at.
