### ISSUE TITLE
[BUG]After packaging with pyinstaller, the address of the element located by the pick locator in the inspector changes from "_" to uppercase and lowercase

### ISSUE THREAD

**Issue by qu-niao** [microsoft/playwright#26889]
After packaging with pyinstaller, the address of the element located by the pick locator in the inspector changes from "_" to uppercase and lowercase，The inspector opened by the `page. pause ()` command:
![image](https://github.com/microsoft/playwright/assets/126561001/daac252a-b30a-46e4-9a6a-f349d325b565)

version:1.37.0

**Comment by qu-niao** [comment]
The inspector opened by the `page. pause ()` command

**Comment by pavelfeldman** [comment]
Playwright does not support pyinstaller.
