### ISSUE TITLE
[BUG]Using firefox in Windows to report an error Full list of missing libraries: msvcp90.dll  msvcr90.dll

### ISSUE THREAD

**Issue by yuanhuihui1203** [microsoft/playwright#26887]
I encountered an error while executing firefox through the playwright library in Golang

firefox version: 1408

I was able to start the playwright installer for the first time after executing it, but communication was blocked, making it impossible to manipulate page elements

On the second attempt, the firefox browser was unable to start and the following error was reported

![err](https://github.com/microsoft/playwright/assets/68732096/6b8efea3-8f0e-48b5-8223-7d67d73115cb)

According to the error prompt, I attempted to download these two. dll files

According to the error prompt, I attempted to download these multiple. dll files and tried placing them in multiple locations, but all failed with the same error reported

C:\Windows\System32
C:\Users\Administrator\AppData\Local\ms-playwright\firefox-1408\firefox
C:\Users\Administrator\AppData\Local

I am currently unable to solve this problem. I am not sure if any outstanding leaders can give me some suggestions or solutions that can solve the problem
Thank you

**Comment by pavelfeldman** [comment]
There is no official Playwright library in golang, please refer to where you installed it from.

**Comment by mxschmitt** [comment]
@yuanhuihui1203 try to install the missing libs as written here: https://github.com/python-greenlet/greenlet/issues/346#issuecomment-1548873043

no need to put them somewhere, just install the official Microsoft Visual C++ Redistributable
