### ISSUE TITLE
[Feature] freely Create fixture outside of test callback

### ISSUE THREAD

**Issue by stkevintan** [microsoft/playwright#26896]
Hi @aslushnikov   
This is a further question of #26808 , sorry for the slow response
The previous demo is too simple so construct the `Helper` class manually would be a good choice.

However, I am a deep user of fixtures. I really like it and use it widely as a solution of dependency injection.
So here I created a big complex dependencies graph among the fixtures, like:
```ts
import {test as baseTest} from '@playwright/test'
interface Helpers {
   helper1: Helper1;
   helper2: Helper2;
   helper3: Helper3;
   helper4: Helper4;
   helper5: Helper5;
   ....
}
const test = baseTest.extend<Helpers>({
    helper1: async ({ page }, use) => {
       await use(new Helper1(page));
   }),
    helper2: async ({ page, helper1 }, use) => {
       await use(new Helper2(page, helper1));
   }),
    helper3: async ({ page, helper2 }, use) => {
       await use(new Helper3(page, helper2));
   }),
    helper4: async ({ page, helper1, helper2 }, use) => {
       await use(new Helper4(page, helper1, helper2));
   }),
    helper5: async ({ page, helper3, helper2 }, use) => {
       await use(new Helper5(page, helper3, helper2));
   }),
   ...
});
```

There are two main purpose of integrating them to fixture:
1. Playwright can help us create each helper instance without creating and maintaining their dependencies manually
   ```ts
   const helper1 = new Helper1(page);
   const helper2 = new Helper2(page, helper1);
   // We only want helper4, but we have to create helper1 and helper2  
   const helper4 = new Helper4(page, helper1, helper2);  


2. Allow developers to override one or more fixtures according to their scenario
  ```ts
  // productB/test.ts
  import { test as productATest } from '../productA/test';
  export const test = productATest.extend({
      // override helper2 with ProductBHelper2
     helper2: async ({ page, helper1, productBConfig }, use) => {
          await use(new ProductBHelper2(page, helper1, productBConfig));
     }
  });
```

## Question
I just wonder how to resolve helper instances for another page instance, for example:

```ts
test('open external page', async ({ page, helper1 }) => {
    // click that jump button, will open a new browser tab:
    await helper1.jumpButton.click();
    const newPage = page.context().waitForEvent('page');
   // how to get helperX based on the newPage here?
   ???
});


```
To be a little further: can we implement a function like that:
```ts
function resolveInstance(page: Page, test: TestType): HelperX {
    // do something
}
```

**Comment by pavelfeldman** [comment]
You can already do (2) today, what would you like to see added?

**Comment by stkevintan** [comment]
> You can already do (2) today, what would you like to see added?

Yes, I can do it!, I am very appreaciate to provide such amazing features. 
however, I just wonder how to resolve helper instances for another page instance (more general: outside of the test callback), for example:

```ts
test('open exernal page', async ({ page, helper1 }) => {
    // click that jump button, will open a new browser tab:
    await helper1.jumpButton.click();
    const newPage = page.context().waitForEvent('page');
   // how to get helperX based on the newPage here?
   ???
});


```

**Comment by pavelfeldman** [comment]
I don't think that would be feasible as it requires implementing fixture runners with proper dependency management, setup and teardown for the fixtures. Test scope defines the fixture setup / teardown scope and is noticeably missing in your case, making the implementation impossible.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
