### ISSUE TITLE
[BUG] Browser fails to launch when integrating Playwright with Browserstack (Error: browserType.launch: Browser has been closed)

### ISSUE THREAD

**Issue by zuzanna-maria** [microsoft/playwright#26892]
### System info
- Playwright Version: 1.37.1
- Operating System: macOS 12.6.3
- Browser: all
- Other info: n/a

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.js
const { defineConfig, devices } = require('@playwright/test');
const { getCdpEndpoint } = require('./browserstack.config.js')

module.exports = defineConfig({
  testDir: './e2e-tests',
  projects: 
  //[{
    //name: 'chromium',
    //use: { 
      //...devices['Desktop Chrome'],
      //permissions: ["clipboard-read", "clipboard-write", "notifications"],
    //},
  //}],
    [{
      name: 'chrome@latest:OSX Ventura',
      use: {
        permissions: ["clipboard-read", "clipboard-write", "notifications"],
        connectOptions: { wsEndpoint: getCdpEndpoint('chrome@latest:OSX Ventura') },
        viewport: {width: 1440, height: 764}
      },
    }],
})
```

**Test file (self-contained)**
//test.spec.js
```js

const { test, expect } = require('@playwright/test');

test.beforeEach(async ({ page }, testInfo) => {
    await page.goto(`https://google.com`)
});

test('title', async ({ page }) => { 
    await expect(page).toHaveTitle('Google')
})


```

**Steps**
- Using `npx playwright test test.spec.js` to run the test.

**Expected**/**Actual**

I am having an issue wherein I have integrated my Playwright tests with Browserstack as in the example code snippet above. About 98% of the time it works correctly, and I am able to see the test runs on my Browserstack Automate dashboard. However, occasionally (seemingly at random) I run into an issue where while running the tests using the Browserstack integration, the browser fails to launch. The error I get is `Error: browserType.launch: Browser has been closed` and the line which throws is the error is `test.beforeEach`. The tests run correctly if I switch my `projects` settings back to Playwright only (ie. the commented out section of `config.js` above). It can also usually be resolved by restarting my computer, which is obviously not ideal. What could be causing this error and how can I fix it?

**Comment by pavelfeldman** [comment]
> What could be causing this error and how can I fix it?

That would be a bug in the browserstack backend. You should report it to them.

**Comment by sopansagorkar** [comment]
@pavelfeldman and @zuzanna-maria Is this issue resolved? I am still facing this issue for each run.
