### ISSUE TITLE
[K8S]Generate HTML report in multiple environments 

### ISSUE THREAD

**Issue by amireretz** [microsoft/playwright#26891]
I have K8S cluster with couple of namespaces, Both NS are similar in their components.

I created test service based on Playwright – it should run tests on each NS and know in which NS it lives.

I’m using CM to declare the environment variables and can’t use “.env” files.

I’m trying to find a way to generate the HTML report in each environment separately because at the moment the HTML report is created at the Build phase and it doesn’t the current environment variables.

 Thanks

**Comment by pavelfeldman** [comment]
I'm not sure I understand the request. Playwright is just a program that you run. It'll use the environment you run it in.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
