### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by RobinClowers** [microsoft/playwright#26897]
The application I'm testing with Playwright polls an endpoint, which initially returns a 204 with an empty body, but playwright logs this in the network tab as `Aborted: 204 No Content`, and there are no response headers listed. 

I was on 1.32.3, but I just updated to 1.37.1 and tested this, and the message is now `net::ERR_ABORT` but response header are listed (so clearly the response was received). 

### System info
- Playwright Version: 1.37.1
- Operating System: macOS 13.5.1 
- Browser: Chromium, WebKit

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

I don't have a self contained repro, it requires making a fetch request to an api that returns a 204 with an empty body.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices, PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = defineConfig({
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ],
  testDir: "e2e-tests",
  // Per test timeout
  timeout: 30 * 1000, // 30 seconds
  use: {
    acceptDownloads: true,
    // Actions such as clicks, also waitForSelector calls
    actionTimeout: 5 * 1000, // 3 seconds
    trace: "on",
  },
  workers: 5,
  fullyParallel: true,
});

export default config;

```

**Steps**
- Run the test
- Observe the network tab of the playwright UI

**Expected**

- The api call should be listed as `204 GET /api`

**Actual**

- The api call is listed as `net::ERR_ABORT GET /api`

**Comment by pavelfeldman** [comment]
> Run the test

Which test should I run?

**Comment by RobinClowers** [comment]
I think it should reproduce with any call that returns a 204, something like this:

```js
await fetch('https://httpbin.org/status/204');
```

**Comment by pavelfeldman** [comment]
Please follow the issue template with clear steps to reproduce, expected and actual behavior. I'm not sure what I should do with the line above and where.

**Comment by RobinClowers** [comment]
@pavelfeldman apologies, I've updated the description will a full repo, can you take another look? Just clone https://github.com/RobinClowers/playwright-204-aborted and `npm test`.
