### ISSUE TITLE
[BUG] Videocapture doesnt work in version 1.37 on FireFox . 

### ISSUE THREAD

**Issue by ATDickinson** [microsoft/playwright#26898]
### System info
- Playwright Version: [v1.37]
- Operating System: [macOS 13.2]
- Browser: [Firefox]
- 
- Other info:
- [ ] BrowserContext context = browser.newContext(new Browser.NewContextOptions().setRecordVideoDir(path));

Using the method above video capture doesn't work using the FireFox Browser.

Have checked back with different versions of Playwright, and last working version was v1.35 which created a webm file.

**Comment by pavelfeldman** [comment]
Please file an issue following the template so that we could reproduce and fix it.
