### ISSUE TITLE
[BUG] Intermittent Issues with Playwright API Calls on onTestEnd for Sending Notifications to Teams Channel

### ISSUE THREAD

**Issue by samsuthen** [microsoft/playwright#26902]
### System info
- Playwright Version: [v1.37]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]

### Source code
**helper.ts**

```
public async sendFailureNofitication(webhookUrl: string, dashboardName: string, exceptionMessage: string) {
    const api = await request.newContext()
    const date = new Date();
    const formatter = new Intl.DateTimeFormat("en-US", {
      weekday: "short",
      day: "numeric",
      month: "short",
      year: "numeric",
      hour: "numeric",
      minute: "numeric",
      second: "numeric",
      timeZone: "Asia/Bahrain",
    });

    const payload = {
      "@type": "MessageCard",
      "@context": "http://schema.org/extensions",
      themeColor: "0076D7",
      summary: dashboardName,
      sections: [
        {
          activityTitle: dashboardName,
          activitySubtitle: "Dashboard report status",
          activityImage:
            "https://icon-library.com/images/notifications-icon-png/notifications-icon-png-6.jpg",
          facts: [
            {
              name: "Executed date",
              value: formatter.format(date),
            },
            {
              name: "Status",
              value: "Exception",
            },
            {
              name: "Exception",
              value: exceptionMessage,
            },
          ],
          markdown: true,
        },
      ],
    };

    try {
      const response = await api.post(webhookUrl, { data: payload });
      expect(response.ok()).toBeTruthy()
      logger.info("Failure notification sent to Teams channel.");
    } catch (error) {
      logger.error("Failed to send failure notification:", error);
    }
  }
 ```

**myReporter**

```
class myReporter implements Reporter {

    private helper: Helper;

    constructor(){
        this.helper = new Helper();
    }

    onTestEnd(test: TestCase, result: TestResult): void {
        if (result.status !== 'passed') {
            this.helper.sendFailureNofitication(process.env.app_job_notify_http_failure, test.title, "Failure")
            failCount++
        } else {
            passCount++
        }
    }
}
export default myReporter;
```

**The Scenario**:
In my current project, I'm utilizing Playwright to send notifications to a Teams channel whenever a test case fails during test execution. To streamline this process, I've created a custom reporter (myReporter.ts) that interacts with my helper functions in a separate file (helper.ts). This approach allows me to notify my team promptly whenever a test fails.

**The Issue**:
While the basic functionality works as expected, I've been facing intermittent issues with this notification system. Sometimes, the notifications are sent successfully to the Teams channel, but on other occasions, they aren't delivered at all. This inconsistency has left me scratching my head, and I'm eager to get to the bottom of it.

**Further Complexity:**
To add to the complexity of this issue, I've noticed an unusual behavior. When the notification is sent successfully or not, the code after the api.post call is completely skipped.

The notifications work reliably when implemented in onTestBegin, but they are inconsistent when placed in onTestEnd. 

**Expected**
Notifications are expected to be sent consistently every time the script is executed.

**Actual**
Notifications are being sent inconsistently. Sometimes they are sent as expected, but other times they are not.

**Comment by pavelfeldman** [comment]
The problem is that you are running an async function from a sync callback. It is likely that the tests finish and test program exits before your async notification is sent. You should add the result of the call into array of promises and await them in `onEnd` using `await Promise.all`.

**Comment by samsuthen** [comment]
Thank you for your guidance! Your explanation makes perfect sense, and your suggestion to use await Promise.all in the onEnd callback has significantly improved the reliability of our notification system. We greatly appreciate your assistance in resolving this issue

here is the updated code. 

```
class myReporter implements Reporter {

    private helper: Helper;
    private notifications: Promise<void>[] = [];

    constructor() {
        this.helper = new Helper();
    }

    onTestEnd(test: TestCase, result: TestResult): void {
        if (result.status !== 'passed') {
            this.notifications.push(this.helper.sendFailureNofitication(process.env.app_job_notify_http_failure, test.title, "Failure"))
            failCount++
        } else {
            passCount++
        }
    }

    async onEnd(result: FullResult): Promise<void> {
        logger.info(`Execution summary pass: ${passCount}, fail: ${failCount}`);
        this.notifications.push(this.helper.sendSummaryNotification(process.env.app_job_notify_http_summary, passCount, failCount));
        await Promise.all(this.notifications);
    }
}

export default myReporter;
```
