### ISSUE TITLE
[BUG] drag and drop is  not working with li tags (playwright)

### ISSUE THREAD

**Issue by VipinThksys** [microsoft/playwright#26907]
### System info
- Playwright Version: [1.37.1]
- Operating System: [macOS 13.2]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
- Node Version: 18
package.json:
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.37.1",
    "allure-playwright": "^2.6.0"
  }
}

### Source code

test.describe('sample test cases for Drag Drop', () => {

    test('ID: 1 , automation testing site', async ({ page }) => {
        test.setTimeout(120000)
        await page.goto('https://demo.automationtesting.in/Static.html', { timeout: 50000 });
        await page.locator('[id=angular]').dragTo(page.locator('[id=droparea]'))
        await page.waitForTimeout(3000)
    });

    test('ID: 2, droppable', async ({ page }) => {
        test.setTimeout(120000)
        await page.goto('https://demoqa.com/droppable/', { timeout: 50000 });
        await page.locator('[id=draggable]').dragTo(page.locator('[id=simpleDropContainer]>div[id=droppable]'))
        await page.waitForTimeout(3000)
    });

    test('ID:3, dragand drop', async ({ page }) => {
        test.setTimeout(120000)
        await page.goto('https://www.globalsqa.com/demo-site/draganddrop/', { timeout: 50000 });
        await page.locator('[id=gallery]>li:nth-child(1)').dragTo(page.locator('[id=trash]'))
        await page.waitForTimeout(3000)
    });

})

**Config file**

// @ts-check
const { defineConfig, devices } = require('@playwright/test');

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: false,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,

  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    ['html'],
    ['allure-playwright']
  ],

  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'https://app.phonism.com',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on',

    // Capture screenshot after each test failure.
    screenshot: 'only-on-failure',
    // Capture screenshot after each test failure.
    video: "on",

    // Run browser in headless mode.
    headless: false,

    // timeout: 60000,
    // actionTimeout: 10 * 2000,
    // navigationTimeout: 30 * 2000,
    // launchOptions: {
    //   slowMo: 2500
    // }
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        //viewport: { width: 1440, height: 680 },
        //launchOptions: { slowMo: 1000 }
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
        //launchOptions: { slowMo: 1500 }
      },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
using vs code to execute code 

**Expected**

drag and drop should be working fine with all the drag and drop functionality

**Actual**

I have created three test cases where I observed with "div" tags drag and drop is working fine but with "li" tag it is not working.
 please reply with a solution.
Sample code I attached.

**Comment by pavelfeldman** [comment]
First two examples work for me just fine, and the third example seems to have wrong locator.

**Comment by VipinThksys** [comment]
If there is no specific ID so I can't directly point out to a particular locator then at that time we have to give the path, already double checked the locator
