### ISSUE TITLE
[While trying to access clipboard we are getting a string] 

### ISSUE THREAD

**Issue by abhishek305** [microsoft/playwright#26901]
### System info
- Playwright Version: [v1.28.1]
- Operating System: [macOS 13.5, etc.]
- Browser: [Chromium latest]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// This handler copies a JSON on a click & we are trying to read the JSON
async copyManifestJsonFromClipboard(){
    await this.page.locator(elements.editorIconCopy).click();
    await this.page.waitForTimeout(1000);
    const textClipBoard= await this.page.evaluate(()=>navigator.clipboard.readText());
    // console.log("clipBoard...", textClipBoard); // Here I am getting --> "JSON stringify"
    return textClipBoard
  }
```

**Expected**

[It should return the copied JSON from the clipboard in textClipBoard variable]

**Actual**

[Getting a string]

**Comment by pavelfeldman** [comment]
> It should return the copied JSON from the clipboard in textClipBoard variable

That's not what I see here: https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText
