### ISSUE TITLE
[Feature] add option to .check() method to bypass object state change verification.

### ISSUE THREAD

**Issue by chrzaszw** [microsoft/playwright#26908]
Use case:
Upon click on radiobutton other component is opened (but radiobutton _checked_ property remains false per design).
Using .check() or .setChecked() methods throws PlaywrightExpection: "Clicking the checkbox did not change its state"

Proposed solution: add new method to Locator.CheckOptions which allows to skip object state verification after performing click action.

**Comment by pavelfeldman** [comment]
Closing as per above.

**Comment by chrzaszw** [comment]
`click()` did not work. I have also tried JS click, `.evaluate("element=>element.click")`, press mouse or keyboard button.
