### ISSUE TITLE
[question] how to set test run order

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#26905]
I have many test blocks with tag "@tag1"  in many files of many folders: 

When I run npx playwright test --grep tag1 --headed --project=chrome

is there any way that I want a specific test block (block1) to be run before all othe test blocks, and (block2) to be run right after block1

the default order is "alphabetical order based on path?"

**Comment by pavelfeldman** [comment]
There is no way to control the order of the test execution. But there is a project dependencies feature that allows putting all the tests with tag1 into first project and making second project depend on the first project. I'll fold this issue into https://github.com/microsoft/playwright/issues/26854 that generalizes dependencies in a way that they can control the test execution order.
