### ISSUE TITLE
[Question/Potential Bug(?)] - waitForVisible, does not wait full timeout for the component "hidden" state to change

### ISSUE THREAD

**Issue by OSnuszka** [microsoft/playwright#26928]
Playwright in case a component changes its state from hidden to visible while the page is loading, it does not wait as the component has changed its state. 
It just immediately states that the component is not visible, even though it has a long timeout set.
This causes a lot of test instability, it seems to me that `waitForVisibility`, should wait a full timeout while waiting for the component to change state.
As a workaround, I added an expectation of visibility for this element (but not as an assertion) before visiblity assertion.

`(await page.waitForSelector(someLocator)).isVisible();`

I attach the screen below on which you can see that in the log it supposedly puts information about the minute timeout, while the function itself was executed in less than a second.
![image](https://github.com/microsoft/playwright/assets/78599192/2c0743ed-f8e1-4856-8c80-fa5bc498b164)

I'm wondering if this is a bug, or if I should now add a function that waits for component visibility before each assertion.

**Comment by OSnuszka** [comment]
**Prerequisites**
A page component with `hidden` attribute, which loses this attribute as the page loads. (It's case in my project).

**Html example:**
```<button id="testBtn" hidden></button>```

but once page will be fully loaded, it will looks like:
```<button id="testBtn"></button>```

**Example of test scenario code*

```await page.goto('https://example.com');
   await expect(page.locator(`#testBtn:visible`)).toBeVisible({timeout: 30000});
```

```await page.goto('https://example.com');
   await expect(page.locator(`#testBtn`)).toBeVisible({timeout: 30000});
```

**Current status:**
 The test is unstable because the assertion does not wait the full 30 seconds, but fails **immediately** due to the hidden attribute. And this one changes as the page loads. (according to attached screenshot in first post)

**Expected result:** 
Assertion wait full timeout. once element will be visible.

**Comment by pavelfeldman** [comment]
Unfortunately I can't repro this with my local script. Please follow the issue template and provide steps to perform for us to see the bug.

**Comment by OSnuszka** [comment]
Ok thank you for investigation,  I would give you more details, but I couldn't - it's very project specific topic (to give an example). 
As a anwer I use function 
`(await page.waitForSelector(someLocator)).isVisible();`
 instead 
 `expect(locator).toBeVisible()`
 
 In case of instability with specific components.

**Comment by ata1704** [comment]
Same here. The assertion immediately throws an error if "hidden" is set. I increased the timeout to 30 seconds but it throws immediately.

**Comment by bubafinder** [comment]
Same problem on my side. But putting an additional wait before the locator didn't help.
