### ISSUE TITLE
[Feature] Annotate function as an assertion to hide its implementation details.

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#26929]
I want to write a new expect method which will wrap `toHaveScreenshot` with some custom logic before it. Currently I don't see a way how to do this. I can only add global matchers using `expect.extend`.

Moreover type with `toHaveScreenshot` options is not exported.

**Comment by pavelfeldman** [comment]
I don't think expect allows reusing user-facing assertions when implementing your own assertions, would it make sense for your to wrap it as a JS call? We can try to annotate your user-land assertion so that the failure was shown on the call site rather than in this utility method. Would that work for you?

**Comment by DudaGod** [comment]
> I don't think expect allows reusing user-facing assertions when implementing your own assertions

Hmm, I thought this was possible in expect. But I just wrote a piece of code and was convinced that no (it doesn't work). 

> would it make sense for your to wrap it as a JS call?

If there are no other options, then yes we will implement js method which will call the necessary methods from expect.

> We can try to annotate your user-land assertion so that the failure was shown on the call site rather than in this utility method. Would that work for you?

I think yes.

**Comment by pavelfeldman** [comment]
Do you want to try implementing it?

**Comment by DudaGod** [comment]
> Do you want to try implementing it?

I can do it if you can tell me which piece of code I need to pay attention to implement this feature.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/15951

**Comment by luixo** [comment]
Hello,
Just stumbled upon this PR and I don't get how it's closed as completed, it seems like [connected PR](https://github.com/microsoft/playwright/pull/27262) adds chaining docs, but doesn't provide a way to extend page assertions.
