### ISSUE TITLE
What is the proper way of handling tests with more that one tab?

### ISSUE THREAD

**Issue by shishkin17** [microsoft/playwright#2692]
I am testing a form that submits with target="_blank" so it opens a new tab in the middle of the test.
I found a solution in "issues" on how to handle second tab with playwright (which is not trivial at all) with context.on("page"...).

This helped me to continue working with the second tab, but after I'm done with it (and close it for example) the first tab still waits for something without ability to manipulate it and fails on timeout. I assume it waits for Promise resolve but I don't know how to use it with context.on("page"...). 
Here is the example code:

```javascript

const playwright = require('playwright');
const { devices } = require('playwright');
const chai = require('chai');
const expect = chai.expect;

let page, browser, context;

describe('Some test', function() {

    before(async function() {
        browser = await playwright['webkit'].launch({ headless: false });
        const device = devices['iPhone 7'];
        context = await browser.newContext({ ...device });
        page = await context.newPage();

        await page.goto("http://example.com");
    });

    after(async function() {
        await browser.close();
    });


    it('should work', async function() {

        await context.on("page", async newPage => {
            console.log("newPage", await newPage.title());
            expect(1+2).to.equal(3);
            await newPage.close();
        });

        console.log('here');
        await page.click('form input[name="submitButton"]'); // opens new tab

        await page.click('#menuIcon'); //no click
        console.log('not here????'); // no log
        await page.close(); // doesn't close
    });
});

```

Update:

It seems to work if I close newPage and page inside context.on("page"):

```javascript
await context.on("page", async newPage => {
            console.log("newPage", await newPage.title());
            expect(1+2).to.equal(3);

            await newPage.close(); //this helped
            await page.close(); // this helped
        });
```

**Comment by arjun27** [comment]
Since you know when the new page will be opened, I would recommend the following pattern. This will help your code be more linear. Let me know if this works better for you.

```js
const [newPage] = await Promise.all([
  context.waitForEvent('page'),
  // Replace this with submitting the form
  page.evaluate(() => window.open('https://google.com', '_blank'))
])
console.log(await newPage.title());
// More steps with newPage
```

**Comment by shirshak55** [comment]
@arjun27 but this may race and create weird bugs?

**Comment by arjun27** [comment]
`await Promise.all` will ensure that there are no races between the action that opens the new tab and getting the event. Is there something I'm missing?

**Comment by shirshak55** [comment]
what happens if somehow other page was created like popup etc just after context.waitForEvent('page') and just before page.evaluate(() => window.open('https://google.com', '_blank')) . And some people may be using promises concurrently so chance of opening new window is not that less.

**Comment by shishkin17** [comment]
> Since you know when the new page will be opened, I would recommend the following pattern. This will help your code be more linear. Let me know if this works better for you.
> 
> ```js
> const [newPage] = await Promise.all([
>   context.waitForEvent('page'),
>   // Replace this with submitting the form
>   page.evaluate(() => window.open('https://google.com', '_blank'))
> ])
> console.log(await newPage.title());
> // More steps with newPage
> ```

If I write code this way, all actions with newPage after that block do not work.
This is not working as well:

> ```js
it('should work', async function() {
        const [newPage] = await Promise.all([
            context.waitForEvent('page'),
            await page.click('form[name="matrix"] input[name="submitButton"]')
        ]);
        await newPage.click('#menuIcon'); // not working
        console.log(await newPage.url()); // only after timeout fail

        await page.click('#menuIcon'); //no click
        console.log('not here????'); // no log
        await page.close(); // doesn't close
    });
> ```

**Comment by shirshak55** [comment]
@shishkin17 

are u 100% sure   await page.click('form[name="matrix"] input[name="submitButton"]') will create a new tab(called page)?

and when newPage is open u may need to wait it to be navigated full so i recommend u to waitForSelector first.

**Comment by shishkin17** [comment]
> @shishkin17
> 
> are u 100% sure await page.click('form[name="matrix"] input[name="submitButton"]') will create a new tab(called page)?
> 
> and when newPage is open u may need to wait it to be navigated full so i recommend u to waitForSelector first.

Yes, it opens a new tab because the form has target="_blank".
If the problem was with waiting there would be a corresponding error, but there were no such errors.

**Comment by shirshak55** [comment]
show us error message.

**Comment by pavelfeldman** [comment]
@shishkin17 based on the symptoms, either of these is true:
- Playwright has a bug
- the form submit does not happen
- form submits, but does not create a page

If you see the new page when you launch in Playwright with `headless: false` flag, then Playwright bugs is likely. In either case, timeout should have happened and Playwright should have shown you where it got stuck after 30 seconds. Did you wait that much to see the error?

**Comment by shishkin17** [comment]
I'm tired of struggling with that, so I just removed target="_blank" in my form to test it without opening a new tab.

**Comment by rinogo** [comment]
Unless you're specifically testing the "opens in a new tab/window" functionality, I'd suggest just eliminating that complexity entirely. You can simplify your code greatly by removing any `target` attributes.

Here's a quick function to make this happen - hope it helps!

```
//If links/forms open in a new tab, we have to do all sorts of fancy work in Playwright to connect to the new tab. Instead of doing that, we can just remove all targets.
async removeTargets() {
	await this.page.$$eval("css=[target]", nodes => nodes.forEach(n => n.removeAttribute("target")));
}
```
