### ISSUE TITLE
Play wright tests are failing when running test cases through ado pipeline with no error

### ISSUE THREAD

**Issue by DhanashriChavan125** [microsoft/playwright#26924]
**System info**
Playwright Version: [1.34.3]
Operating System: [Windows]
Browser: [Chromium]
Other info:

**Issue**
When I am running the play wright test through an ado pipeline test cases inside the test suite are failing randomly. 
As there are no failure messages in the logs, it is difficult to find the actual cause.
Test is filing before reaching to config file.

**Error log**

D:\data\CHT\7aff1f2e\JWD_43cb9217>cd D:\data\CHT\7aff1f2e 

D:\data\CHT\7aff1f2e>cmd /c ""C:\Program Files\Git\bin\bash.exe" -- .\_1js_powerpoint_online_edittextonslide_e2e_test_ts.sh" 
+ node 'D:\data\CHT\7aff1f2e/cloudtest-tools/dist/index.js' test-runner --workingDirectory ooui --artifactFolder --packageName @1js/powerpoint-online --hash a2d7a134e0238a005b043968d74c88fddf227cab --command ''\''EditTextOnSlide.e2e.test.ts'\'''
new test file in test runner: D:\data\CHT\7aff1f2e\NewFiles.json
Args -  @1js/powerpoint-online EditTextOnSlide.e2e.test.ts D:\data\CHT\7aff1f2e\src\ooui
Running: yarn e2e EditTextOnSlide.e2e.test.ts
This is stdout:
 yarn run v1.23.33
$ yarn playwright test EditTextOnSlide.e2e.test.ts
$ D:\data\CHT\7aff1f2e\src\ooui\apps\powerpoint-online\node_modules\.bin\playwright test EditTextOnSlide.e2e.test.ts
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

Test command status: 1

**Comment by pavelfeldman** [comment]
Please use the BUG template to file something we can reproduce.

**Comment by DhanashriChavan125** [comment]
@pavelfeldman, from where i can get bug template?
