### ISSUE TITLE
[BUG]: captured screenshot on 15px pixels less then specified in remote browser

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#26927]
### System info
- Playwright Version: v1.37.1
- Operating System: MacOS 12.3
- Browser: Chromium

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

process.env.SELENIUM_REMOTE_URL = "http://localhost:4444/wd/hub";
process.env.SELENIUM_REMOTE_CAPABILITIES = JSON.stringify({
  browserName: "chrome",
  browserVersion: "112.0"
});

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('change viewport', async ({ page }) => {
    await page.setViewportSize({
        width: 1280,
        height: 1024,
    });

    await page.goto('https://playwright.dev/');

    await expect(page.locator('body')).toHaveScreenshot('screen.png');
});
```

**Steps**
- run selenium/selenoid/etc
- run the test

**Expected**

Screen captured with size 1280x1024 as specified in the test.

**Actual**

Screen captured with size 1265x1024 (on 15px pixels less by width). Looks like it is a scrollbar. Is this the expected behaviour?

There is no such problem when using a local browser.

**Comment by pavelfeldman** [comment]
Are you running selenium hub locally?

**Comment by DudaGod** [comment]
> Are you running selenium hub locally?

Yes. I noticed that the problem only reproduces if I use `headless: false`. If I set `headless: true` everything works fine (correct size of the captured image).

**Comment by pavelfeldman** [comment]
So those are scrollbars and that is a known issue. It should not happen on a macOS though, so I'm not sure where this is coming from. Could you confirm that your localhost:4444 runs macOS 12.3 as in the report header?

**Comment by DudaGod** [comment]
> Could you confirm that your localhost:4444 runs macOS 12.3 as in the report header?

Sorry I forgot that I was running the selenoid that time which run in docker with Linux OS. If I run selenium in my local machine with MacOs that everything works fine.

> So those are scrollbars and that is a known issue.

Is there a link to this problem? Or this problem is not related to the playwright and more related to the browser itself on Linux?

**Comment by dgozman** [comment]
@DudaGod Screenshots across different platforms never match. Most of the time, headless vs headed screenshots also do not match. We recommend taking screenshots in the exact same configuration every time.

> Is there a link to this problem?

[Here is a decent summary](https://github.com/microsoft/playwright/issues/12683#issuecomment-1068749075), and the issue overall captures many headless vs headed aspects.

**Comment by DudaGod** [comment]
> Screenshots across different platforms never match. Most of the time, headless vs headed screenshots also do not match. We recommend taking screenshots in the exact same configuration every time.

I know it, it's obvious. My question is why the screenshot size is 15 pixels smaller in width when running chrome on linux? I expected to see a screenshot of the size specified in the `setViewportSize`. We found out that this is a scrollbar. And now I want to understand if we can do something about it.

**Comment by dgozman** [comment]
@DudaGod I guess I don't understand the issue then. Screenshots are 15px less because scrollbars were not included. I believe that's how Chromium takes screenshots, although there is a small chance there is a bug somewhere.

However, the most important part of screenshots is their consistency. As long as it's always 15px less, I am not sure why would you want to do anything about it. Could you please explain what's the problem with that?

**Comment by DudaGod** [comment]
> However, the most important part of screenshots is their consistency. As long as it's always 15px less, I am not sure why would you want to do anything about it. Could you please explain what's the problem with that?

It's strange that this problem only occurs on Linux OS.

> However, the most important part of screenshots is their consistency. As long as it's always 15px less, I am not sure why would you want to do anything about it. Could you please explain what's the problem with that?

I'm not saying that the problem is critical, but at the moment the behavior is not obvious. I specify `setViewportSize({width: 1280, ...})`, but see screenshot with width 1265px. It turns out if I want to get a screenshot 1280 pixels wide I must specify 1295px.

**Comment by aslushnikov** [comment]
> I'm not saying that the problem is critical, but at the moment the behavior is not obvious. I specify setViewportSize({width: 1280, ...}), but see screenshot with width 1265px. It turns out if I want to get a screenshot 1280 pixels wide I must specify 1295px.

@DudaGod This looks like a chromium issue, so I'd recommend filling this upstream to the https://crbug.com/new. I'll close this for now since there's no action planned on this by the Playwright team.
