### ISSUE TITLE
[Feature] Opening DevTools on Webkit

### ISSUE THREAD

**Issue by Sreejithw** [microsoft/playwright#2693]
Is there any way to automatically open DevTools/Inspect Element on Webkit browser when i run the test?

**Comment by pavelfeldman** [comment]
Unfortunately, opening Web Inspector currently terminates the connection Playwright uses to automate the browser. The reason is that Playwright uses the same protocol endpoint Web Inspector uses and there can only be one client over it.

**Comment by Sreejithw** [comment]
The issue was rasied mainly because i am unable to run tests on any sapui5 application in the webkit browser since the web application doesn't load.

**Comment by pavelfeldman** [comment]
You can set `headless` to false and then open Web Inspector using context menu?

**Comment by geoff-nixon** [comment]
This is kinda crappy. Is it not possible to at least do something like instantiate a Service Worker(+client?) (and/or WebExtension?) where Playwright can "retreat to" out-of-band and hibernate if the remote execution handle needs to be used by another process (if told to be in an "submissive" mode)? And then resume control after the other tool relinquishes?

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.

**Comment by mbUSC** [comment]
+1
