### ISSUE TITLE
[Feature] soft assertion fails do not mark this test failed in UI mode.

### ISSUE THREAD

**Issue by zheeeng** [microsoft/playwright#26945]
When I test in UI mode, there is some soft assertions fails, I expect showing that I have passed  this test in UI mode.

![image](https://github.com/microsoft/playwright/assets/1303154/3f60d657-cba3-4382-b10e-7f3006dba6ab)

**Comment by pavelfeldman** [comment]
When you fail soft assertions, the test fails, so this is working as expected.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
