### ISSUE TITLE
[BUG] Not able to play DRM content on bundled Webkit from tests

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#26948]
### System info
- Playwright Version: 1.37.1
- Operating System: MacOS Ventura
- Browser: Webkit
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```js
const { webkit } = require('playwright');

(async () => {
    const browser = await webkit.launch({
        headless: false,
    });

    const context = await browser.newContext();
    const page = await context.newPage();

    await page.goto('https://bitmovin.com/demos/drm');
    await page.waitForTimeout(15000);
    await page.screenshot({ path: 'screenshots/localDRM.png', fullPage: true });

    await context.close();
    await browser.close();
})();

```

**Steps**
- Run the test
- After navigation to https://bitmovin.com/demos/drm, we can see that Fairplay is not supported in webkit. For Safari, Fairplay is supported. 
- But if I navigate to `~/Library/Caches/ms-playwright/webkit-1883` and run `./pw_run.sh` which opens the corresponding webkit browser for Playwright version 1.37.1 and navigate to https://bitmovin.com/demos/drm, DRM content is supported with Fiarplay plugin.

**Expected**
Fairplay plugin should be supported while running webkit via Playwright tests too.

**Actual**
For me, running Playwright tests with webkit is showing that the fairplay plugin is not supported when checked on https://bitmovin.com/demos/drm. When I manually open the corresponding browser via navigating to `~/Library/Caches/ms-playwright/webkit-1883` and running `./pw_run.sh`, fairplay plugin is being shown as supported.

**Comment by pavelfeldman** [comment]
DRM is not supported on browser engines, only on branded browsers.

**Comment by ankur-lt** [comment]
@pavelfeldman , if it's not supported in the browser engine, how's that working for me when I launch the webkit manually?
I have added the steps I have performed above.

**Comment by ankur-lt** [comment]
@pavelfeldman , @mxschmitt , can you clarify on this?

**Comment by ankur-lt** [comment]
@pave

> @pavelfeldman , if it's not supported in the browser engine, how's that working for me when I launch the webkit manually? I have added the steps I have performed above.

@pavelfeldman , @mxschmitt , if DRM is not supported on browser engines, then why does it work as expected when I launch playwright webkit manually?

**Comment by mxschmitt** [comment]
The reason is that we do internally:

```ts
    scripts.push('if (!window.safari) window.safari = {};');
```

when launched via Playwright, this breaks their feature detection most likely.
