### ISSUE TITLE
[Feature]: extension service worker reactivation 

### ISSUE THREAD

**Issue by LironHaroni** [microsoft/playwright#26958]
Hi guys,
I'm using python playwright to test an extension, but I'm having trouble with making the extension's service worker to go inactive and than active again (like a real extension). Is there a way of doing it? 
Thank you !

**Comment by pavelfeldman** [comment]
There is no such feature and it is unlikely that we prioritize it in near future.

**Comment by avishail** [comment]
@pavelfeldman, I wonder why you are calling it a feature? it is part of chromium and should be the default behavior...

going inactive is a **core** behavior of background service worker in manifest v3 (which is mandatory by google chrome store) and not having it creating a huge blind spot when testing extension that has a service worker.
