### ISSUE TITLE
[Documentation] Document the schema of the Json reporter

### ISSUE THREAD

**Issue by RunOrVeith** [microsoft/playwright#26954]
Currently, the [documentation for the Json reporter](https://playwright.dev/docs/test-reporters#json-reporter) is relatively sparse.
When trying to parse the resulting json file programmatically, it is a lot of trial and error to understand how the schema works.

It would be great if the documentation could include the output schema of the Json reporter (e.g. as a zod schema, or json schema).
You can kind of piece it together using the [suites](https://playwright.dev/docs/api/class-suite) and related docs, but it is still a bit of a pain. 
For example, it is not clear what the "specs" field contains inside the report.

**Comment by pavelfeldman** [comment]
```js
import { JSONReport } from '@playwright/test/reporter';
```

will give you those.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by RunOrVeith** [comment]
I would suggest to add this comment to the documentation, since you can not find this information anywhere at the moment (except this issue now).
