### ISSUE TITLE
[BUG] Project Teardown run out of order

### ISSUE THREAD

**Issue by weyert** [microsoft/playwright#26955]
### System info
- Playwright Version: v1.37.1
- Operating System: macOS 13.5.2
- Browser: Chromium
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/weyert/playwright-setup-teardown](https://github.com/weyert/playwright-setup-teardown)

**Steps**
- [Run the test]

**Expected**

If I am running the tests I would expect that project dependencies will run before the tests and that configured teardown project will run after the project has finished.

```
seed the database with some data
[web-app] setup() SEED_DATABASE: ["item1"]

Running 1 test using 1 worker

  ✓  1 [Web App] › tests/web-app/dummy.test.ts:4:3 › Web App › should be okay (12ms)
[web-app:test] SEED_DATABASE: ["item1"]
[web-app] teardown() SEED_DATABASE: []
delete the data from the database
```

**Actual**

If I am running the tests the teardown gets run before the tests:
```
seed the database with some data
delete the data from the database
[web-app] setup() SEED_DATABASE: []
[web-app] teardown() SEED_DATABASE: []

Running 1 test using 1 worker

  ✓  1 [Web App] › tests/web-app/dummy.test.ts:4:3 › Web App › should be okay (12ms)
[web-app:test] SEED_DATABASE: []
```

**Comment by pavelfeldman** [comment]
That's not how projects work - all the code needs to be in the form of the tests, otherwise we might not run anything at all. Checkout the docs for how setup using project deps should be organized.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
