### ISSUE TITLE
[BUG] when ever I work with UI mode the terminal of vscode is went to inprogress 

### ISSUE THREAD

**Issue by ajaygoutham1995** [microsoft/playwright#26951]
Hi Team,

when ever I work with UI mode the terminal of vscode is went to inprogress due to this behavior I could not able to generate the report of individual tests which I ran in UI mode, could you please help check.

as per my observation whenever we ran a test that is one individual task, and the task should be completed once the test got passed or failed even in the UI mode, in this way user can debug more easily and he can feel more handy.

**Comment by pavelfeldman** [comment]
You should either use UI mode or VS Code, not both at a time.
