### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by jbdoster** [microsoft/playwright#26963]
**Let us know what functionality you'd like to see in Playwright and what your use case is.**
It would be cool if the CLI accepted a `.env` file path parameter to inject environment variables into the process.

**Do you think others might benefit from this as well?**
I believe so, because we won't have to add another dotenv library and extra code.

**Comment by pavelfeldman** [comment]
We recommend using dotenv for this use case. You can control the env file that config will used via env:

```
MODE=prod npx playwright test
```

and then in the config file, load env from the env file that corresponds to the mode.
