### ISSUE TITLE
"Target closed" when a Page is destroyed before a scraped response is written

### ISSUE THREAD

**Issue by blordpluto** [microsoft/playwright#26962]
Hi. I'm scraping my own project's network responses in order to be able to run tests faster, offline, and with a high degree of determinism.

I have an `@scrape` tag attached to certain tests. These test only run in a special "scrape" mode. The scraped network responses, written to disk, get used in an ordinary test run.

The code looks something like this:

```typescript
/**
 * For every response on a page, if that server is in our scrape-list, we take its JSON response and
 * save that as a file.
 */
export const attachScraper = (page: Page) => {
  page.on('response', async (response) => {
    const url = new URL(response.url());
    const method = response.request().method();

    if (!response.ok()) {
      return;
    }

    try {
      // Write the response to the file system
      await scrapeResponse(urlBase, method.toLowerCase(), response);
    } catch (error: unknown) {
        // Log some stuff
        throw error;
    }
  });
};
```

The problem is that intermittently, a test will finish and close before some response callbacks are completed. This surfaces at the CLI as a `Target closed` error.

Strangely, if I write the callback out manually as a non-`async` function that returns a promise _that never fulfills_, then the problem disappears. My understanding is that by default, when a Page is closed, its accompanying Context gets closed immediately as well, and all of the request/response objects are lost. I intuitively dislike this pattern, though, because it's basically defeating the garbage collector, and keeping all of the Pages alive indefinitely. I don't want to share data between lots of pages across a single Context, but I need to keep the Context around just a little bit longer.

What I think I would like is for the context to stay alive until all of the event callbacks (if any) have resolved, so that the Page object can be cleaned up without losing the request/response object data that's possibly still being processed.

(I can provide more code if it's helpful. I don't think this is version or platform specific.)

Any guidance greatly appreciated.

**Comment by pavelfeldman** [comment]
It looks like you are implementing a built-in capability: https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har. Check out its `update` option that can capture the necessary traffic prior to replay. Or maybe you can capture har beforehand, plenty of built-in options here.

What you have in your source code works as expected. You are running an async function in a sync callback. By the time scapeResponse is finished, the test could have completed already. You should collect all the promises that are results of scrapeResponse and await them all using Promise.all when in the end of your test (or after navigation).

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
