### ISSUE TITLE
[BUG] attachments tab in UI mode

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#26966]
### System info
- Playwright Version: [^1.38.0-alpha-sep-8-2023]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ yes] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test.beforeEach(async ({ page }) => {
  await test.step('navigate', async () => {
    await page.goto('https://playwright.dev/');
  });
});

test('should take screenshot', async ({ page }) => {
  // programmatically remove the button for this example
  await page.getByText('Get Started').evaluate((el) => el.remove());

  await expect(page).toHaveScreenshot();
});
```

**Steps**
- [Run the test in ui mode or trace viewer]
- [run again]

**Expected**

should show me different screenshots so I can compare

**Actual**

Tells me there are no screenshots

**Comment by dgozman** [comment]
Merging into #26991.
