### ISSUE TITLE
[BUG] 'Pick Locator' in UI mode does not work with iframes

### ISSUE THREAD

**Issue by taber-hust** [microsoft/playwright#26967]
### Description

The "Pick locator" feature in Playwright UI does not work within iframes. It only recommends locators for the original document, and won't dive into the iframe to recommend locators for the embedded document.

This issue is limited to just the UI mode, the VS Code extension seems to work fine. However, for reasons I won't get into, my team is limited to just using the UI mode at the moment.

### System info

- Playwright Version: [v1.37]
- Operating System: [All]
- Browser: [All]
- Other info: Specific to UI mode (VS Code extension works fine)

### Source code

-[Simple demonstration with http-server and playwright ui](https://github.com/taber-hust/playwright-ui-pick-locator-iframes)

**Instructions in README

**Steps**
- Run `npm install`
- Run `npm run e2e:ui`
- Execute the test *has iframe title* in the UI (which should be running on localhost:8082)
- Select step *expect.toBeVisible frameLocator* to load the trace viewer for that step
- Click "Pick locator"
- Highlight over the text "Simple iframe"

**Expected**

The locator for the hovered element within the iframe is recommended (i.e. `getByText('Simple iframe')`) or even more preferrably a combo locator including the frameLocator (i.e. `frameLocator('#test-frame').getByText('Simple iframe')`)

**Actual**

The locator recommends either...

1. The frameLocator itself (i.e. `locator('#test-frame')`) but nothing deeper

2. The last locator that was recommended prior to hovering over the iframe window

**Comment by pavelfeldman** [comment]
That's already fixed and will be released as a part of 1.38 shortly.

**Comment by taber-hust** [comment]
Thanks @pavelfeldman! I guess I overlooked that one when looking for duplicates. Looking forward to this fix being released!
