### ISSUE TITLE
[BUG] Chromium headless on Windows does not launch without --disable-gpu

### ISSUE THREAD

**Issue by arjunattam** [microsoft/playwright#2698]
I'm seeing a few internal MS customers run into issues with launching Chromium headless on Windows. These users are able to use Chromium with the `--disable-gpu` flag. Should we make this a default for Windows? What would be the downside?

Related chromium upstream issue: https://bugs.chromium.org/p/chromium/issues/detail?id=737678

**Comment by pavelfeldman** [comment]
@arjun27  Could you share a stack trace from launch? (try DEBUG=pw:browser if it is missing)?

Chromium is supposed to either use machine GPU or fall back to CPU-based compositing if that GPU is blocklisted. Visiting `about:gpu` on the computer where the issue persists from a regular Chrome / Edge and pasting the details here might also give us a hint on what is happening.

**Comment by arjun27** [comment]
Attached logs from about:gpu

[gpu.html.zip](https://github.com/microsoft/playwright/files/4862031/gpu.html.zip)

**Comment by pavelfeldman** [comment]
Closing as a part of triage. Please feel free to re-file with additional details in case it is still an issue.
