### ISSUE TITLE
[Feature Request]Add Support for Adding Extensions to Firefox Browser in Playwright

### ISSUE THREAD

**Issue by EymenTakak** [microsoft/playwright#26995]
### Description:

I kindly request the addition of a new feature to the Playwright Python library that allows users to seamlessly add extensions to the Firefox browser instance.

### Background:

Currently, Playwright Python offers excellent automation capabilities for web testing across multiple browsers, including Firefox and Chrome. However, achieving desired testing results in Chrome can sometimes be challenging due to the sophisticated bot detection systems implemented by websites. These systems often hinder automated testing and lead to false positives or undesirable behavior.

In contrast, Firefox has demonstrated greater stability and resilience to these bot detection mechanisms, making it an attractive choice for web automation tasks.

### Requested Feature:

The proposed feature should enable users to load and manage extensions/add-ons in the Firefox browser through Playwright Python. This capability would empower developers and testers to perform a wider range of automated tasks, taking full advantage of the robustness of Firefox.

### Benefits:

Improved testing capabilities: Adding extensions to Firefox via Playwright Python would enhance the tool's versatility, allowing testers to work around bot detection mechanisms and access a broader range of testing scenarios.

Cross-browser compatibility: Playwright Python's cross-browser support ensures that the same code can be used seamlessly with both Chrome and Firefox, giving users flexibility in selecting the most suitable browser for their testing needs.

### Conclusion:

The addition of the requested feature would make Playwright Python an even more powerful tool for web automation, catering to users who value Firefox's stability and reliability in their testing workflows. We believe this enhancement would greatly benefit the Playwright community by expanding its capabilities and making it a preferred choice for web automation across different browser environments.

Thank you for considering this feature request, and we look forward to seeing it implemented in future releases of Playwright Python. If you require further information or clarification, please do not hesitate to reach out.

**Comment by dgozman** [comment]
Merging into #7297.
