### ISSUE TITLE
[Feature] Add attachments info for successfully passed screenshot tests

### ISSUE THREAD

**Issue by shadowusr** [microsoft/playwright#26991]
### Current behaviour
- Playwright adds information about screenshots to the attachments field for test results of tests that have failed screenshot asserts
- Playwright doesn't add any info about screenshots for tests that are passed

### Requested behaviour
- Playwright adds info about screenshots to the attachments field regardless of whether the test has passed or not

### Why?
- It's very useful to see reference images of successful tests in the final report
- I'd expect any resources that are used during test to appear in the attachments field, including reference screenshots

**Comment by dgozman** [comment]
@shadowusr Including all screenshots into every report could easily get out of hand, especially if you have thousands of images. Are you using HTML report or UI mode? Tell us more about your usecase - when/why do you look at the successful screenshots?

**Comment by shadowusr** [comment]
@dgozman 
> Are you using HTML report or UI mode?

I am building a custom reporter. Even if you think including successful screenshots into every report is not a good idea, I think it would be really useful to give freedom of choice on the matter to custom report devs. I'm talking about the `attachments` field in test result. Now I have no choice but to come up with some complicated fixtures to add the info I need to the test result

> when/why do you look at the successful screenshots?

We're using a different testing framework and have tens of thousands of screenshots in each report and it works well for us. Visual comparisons are a major part of our tests. Now we are trying to migrate to playwright and discovered that this feature is missing.

As for why/when we look at successful screenshots, besides a fact that it's useful to see what a successfully passed test looks like, it's particularly handy when running tests in multiple browsers: for instance, in one browser the test has fallen or doesn't have a ref yet, so we want to see what reference image looks like in another browser.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
