### ISSUE TITLE
[BUG] Dangling context menu after right-click on WebKit headless Windows

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2699]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Windows (works on Mac)
- Node version: 12.18
- Browser: Webkit

**Code Snippet**

```js
const {webkit} = require('playwright');

(async () => {
    const browser = await webkit.launch({headless: true});
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto("https://www.bing.com");
    await page.click("//*[@id='b_logo']", {button: 'right'});
    await browser.close();
})();
```

Since the execution is headless, no UI should be shown

![Screen Shot 2020-06-24 at 7 13 07 PM](https://user-images.githubusercontent.com/284612/85645488-be9ebd80-b64e-11ea-831e-ee51567c10ad.png)

**Comment by JoelEinbinder** [comment]
This example has headless: false, but the bug implies that is headless:true yes?

**Comment by arjun27** [comment]
That's right. Sorry for the confusion.

**Comment by arjun27** [comment]
Just tested this on 1.2 and it's been fixed
