### ISSUE TITLE
[Feature] Could we please implement possibility to change timezon inside test

### ISSUE THREAD

**Issue by LiutskoOlga** [microsoft/playwright#26996]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

We need to test functionality related to timezone, when person in one timezone create data and user from another timezone change the date
Unfortunately, 
 - set time zone via config use this value globally for test  
 -  use Intl.DateTimeFormat().resolvedOptions().timeZone = 'timezone' is not applied too.

**Comment by dgozman** [comment]
@LiutskoOlga Take a look [at this guide](https://playwright.dev/docs/emulation#locale--timezone). You can set a timezone for a single file or describe block like this:

```js
test.use({
  timezoneId: 'Europe/Berlin',
});
```

If you would like to have two users from different timezones in a single test, you should [create two browser contexts](https://playwright.dev/docs/browser-contexts#multiple-contexts-in-a-single-test) and pass different `timezoneId` options to them.

```js
const user1Context = await browser.newContext({ timezoneId: 'Europe/Berlin' });
const user2Context = await browser.newContext({ timezoneId: 'Europe/Paris' });
```

Let me know whether this helps.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
