### ISSUE TITLE
[BUG] Crashes in docker on M1 Mac

### ISSUE THREAD

**Issue by SergyBud** [microsoft/playwright#26993]
**Context**:

Playwright Version: [what Playwright version do you use?] playwright==1.33.0
Operating System: [e.g. Windows, Linux or Mac] MacOS Ventura 13.4.1 (22F82)
Node.js version: [e.g. 12.22, 14.6] ? python 3.8
Browser: All
Extra: M1 Mac / Apple Silicon

I read BUGS #9435, #7723, #7655

**Report about error**:

> launch_browser = <function launch_browser.<locals>.launch at 0x4009f179a0>

    @pytest.fixture(scope="session")
    def browser(launch_browser: Callable[[], Browser]) -> Generator[Browser, None, None]:
>       browser = launch_browser()

        else:
>           page = browser.new_context().new_page()

```
browser    = <Browser type=<BrowserType name=chromium executable_path=/ms-playwright/chromium-1060/chrome-linux/chrome> version=113.0.5672.53>

E       playwright._impl._api_types.Error: Target page, context or browser has been closed 
```

Adding --platform linux/amd64 doesn't seem to change anything:

On my Linux machine, it runs without issue:

**docker commands**:
docker buildx build --platform=linux/amd64 -f Dockerfile -t playwright-python-test .
docker run -it --platform=linux/amd64 -e STAND=.... -e AUTH_MSISDN=+......... -e AUTH_PASSWORD=......... -e TEST_PAGE_STORAGE=......  --rm playwright-python-test /bin/bash

**Describe the bug**
We have ~30 playwright tests that get parameterized to run in both Firefox and Chromium
local run is normal
run in docker in linux also good

I read all of there articles about this topik, but don't how can i solve this problem
if u need more info, i can give it

**Comment by mxschmitt** [comment]
If you run on m1 mac, you need to use `--platform=linux/arm64` otherwise it won't work.

**Comment by StasGrishaevTutu** [comment]
@SergyBud Is there any specific reason to manually specify the `platform` flag when running docker build/run?
I also work on MB Pro with an M1 PRO processor, I DO NOT specify the `platform` flag, everything works fine :)
I'm using Docker Desktop 4.22.1

**Comment by mxschmitt** [comment]
Could you try setting the `DEBUG=pw:browser` env var? This might yield more helpful output.

Which base image are you using? Are you using the official one? https://playwright.dev/python/docs/docker

Do you install the [OS dependencies](https://playwright.dev/python/docs/browsers#install-system-dependencies)?

**Comment by aslushnikov** [comment]
I'll close this since the discussion has stalled.

If you think we still can be helpful, then please file a new issue!
