### ISSUE TITLE
[BUG] browser.close does not resolve after right-click on Webkit headful

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2700]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Tested on Windows and Mac
- Browser: Webkit

**Code Snippet**

Similar to #2699. When running Webkit in headful mode, the browser.close does not resolve because it leaves a dangling context menu. Pressing escape or clicking on a menu item resolves browser.close.

```javascript
const {webkit} = require('playwright');

(async () => {
    const browser = await webkit.launch({headless: false});
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto("https://www.bing.com");
    await page.click("//*[@id='b_logo']", {button: 'right'});
    await browser.close();
})();
```

**Comment by aslushnikov** [comment]
Oops too early to close! This requires a test and a roll.

**Comment by aslushnikov** [comment]
Turns out Chromium is also susceptible to this!

**Comment by aslushnikov** [comment]
Upstream chromium patch: https://chromium-review.googlesource.com/c/chromium/src/+/2285520
