### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by gycvoice** [microsoft/playwright#27009]
**Context:**
- Playwright Version: 1.37.1
- Operating System: Mac
- Node.js version: v20.6.0
- Visual Studio Code version: 1.81.1
- Playwright for VSCode extension version: v1.0.15
- Browser: Chromium
- Extra: This happens when I try to use 'dev container'. If I don't use 'dev container', it can see tests.  This happens also if I tried to run `npm init playwright@latest --yes -- --quiet --browser=chromium --install-deps` with created 
`playwright.config.ts.
e2e/example.spec.ts.
tests-examples/demo-todo-app.spec.ts.
package.json.`

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

**Describe the bug**

The extension can not find any tests. And in 'Runtime status', there are two errors after I refreshed in the extension.
```
Cannot read properties of undefined (reading 'config')
Cannot read properties of null (reading 'Symbol(traceUrl)')
```
The activation event is: `workspaceContains:**/*playwright*.config.{ts,js,mjs}`

**Comment by gycvoice** [comment]
It also happens with `Visual Studio Code version: 1.82.0`

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by kkogovsek** [comment]
We have the same thing happening (but only people who updated their VS code in the past few days).

**Comment by dgozman** [comment]
@gycvoice It could be that VSCode did not find the `node` executable. We recommend to fully terminate VSCode (e.g. right-click in Dock and choose "Quit") and restart it from the terminal with `code /path/to/your/project`.

**Comment by gycvoice** [comment]
> We have the same thing happening (but only people who updated their VS code in the past few days). Everything works when downgrading to VS Code July 2023 (version 1.81)

I tried with different version of VS Code (1.80, 1.81), both did not work. :-(

**Comment by gycvoice** [comment]
> @gycvoice It could be that VSCode did not find the `node` executable. We recommend to fully terminate VSCode (e.g. right-click in Dock and choose "Quit") and restart it from the terminal with `code /path/to/your/project`.

Tried with your suggestion, but still it does not work.

**Comment by gycvoice** [comment]
> We need more information to act on this issue. Could you please provide a repro that we can run locally?

Sorry, it was a company's repo, and I can not share.

**Comment by dgozman** [comment]
@gycvoice Unfortunately, we are out of guesses at this point. If someone could share a repro so that we can debug the issue, that would be great. Otherwise, it's unlikely we'll be able to help.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
