### ISSUE TITLE
[Feature] Run from a certain step when in UI mode

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#27001]
There have been times when I had to change the locator, but I need to run the test from the beginning instead of which it would be much better for me to run a test from a desired step.

Eg script:

```
Enter user name
Enter password
Click loginnn // here my locator has a typo, or has changed
Click and elemental login
Click log out
```

When I fix the typo for login, then I need to restart the test from the beginning. A big deal if my script is on the 5th page and when you do it over and over again, it adds up the time instead if I could change the typo and run from a desired step that would be wonderful. More like hot reload of the code.

I said desired step and not resume from the same step because sometimes the UI state changes and the previous step is not valid anymore.

**Comment by dgozman** [comment]
@siddharth2023 I don't think this is feasible. There is no way to bring the page to the state it should be before a particular action without replaying all actions from the start.
