### ISSUE TITLE
How to maintain local snapshot state to be used in custom matchers?

### ISSUE THREAD

**Issue by Swappea** [microsoft/playwright#27018]
I am creating a custom matcher which is used to compare image snapshots and save them. Now each image I create I assign a custom name for those images that is based on `describe` and `test` name, so it combines them.

Now the issue is a single test can call that matcher multiple times so multiple screenshots are possible, so I thought let's add a counter. Now the issue I am facing is maintaining a state for counter. I am not sure where to save it so it is available within that test environment so I can properly increase counter. I tried setting it up in `.this` but that didn't work. I don't see anything in test.info().

I think jest has something called `snapshotState`, is there something equivalent over here?

Let me know if separate issue type is needed as I created a blank one.

```[tasklist]
### Tasks
```

**Comment by dgozman** [comment]
@Swappea You can put the counter on `TestInfo`, for example with a symbol:

```js
const counterSymbol = Symbol('counter');
// ...
let counter = testInfo[counterSymbol] || 0;
counter++;
// use counter
testInfo[counterSymbol] = counter;
```

**Comment by Swappea** [comment]
@dgozman I tried this out but it doesn't seem to be working. There is no count property for each instance whenever that matcher is called, so it always returns undefined. It's not persisting the count variable.

Am I correct, here `testInfo` means `test.info()`.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
