### ISSUE TITLE
Playwright scripts automated in java  with MFA login  on selenium grid 4 is not working

### ISSUE THREAD

**Issue by mridiniveni** [microsoft/playwright#27019]
### System info
- Playwright Version: [1.34.0]
- Operating System: [Linux]
- Browser: [chromium]
- Other info: Running on  selenium remote url 

### Source code
protected Browser browser = null;
public void setUp(){
 playWright = Playwright.create();
        BrowserType chromium = playWright.chromium();
        BrowserType.LaunchOptions launchOptions = new BrowserType.LaunchOptions();
        launchOptions.setArgs(Arrays.asList("--start-maximized", "--auth-server-whitelist='_'"));
        launchOptions.setHeadless(false);
        browser = chromium.launch(launchOptions);
}

 case "testuser":
                browserContext = browser.newContext(
                        new Browser.NewContextOptions()
                                .setIgnoreHTTPSErrors(true)
                                .setHttpCredentials(
                                        props.read("USERNAME"),
                                        props.read("PASSWORD")
                                ).setScreenSize(1728, 942)

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**bash file where we set the environment variables **

`export PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1
export NODE_TLS_REJECT_UNAUTHORIZED=0
export SELENIUM_REMOTE_CAPABILITIES={"platformName":"LINUX","browserVersion":"111","browserName":"chrome"}
export SELENIUM_REMOTE_URL="https://remote-url/wd/hub"

java -cp *.jar org.junit.runner.JUnitCore testrunner.RunTests

[Describe actual behavior]
  When i  run the pipeline i noticed MFA/SSO  login is not working on selenium grid . Locally its working could you help us what we need to pass to execute our scripts on selenium grid

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by mridiniveni** [comment]
we cant share our repo , Do i need to set any environment variable to run on selenium grid ? especially MFA login

**Comment by dgozman** [comment]
> we cant share our repo 

This makes it unlikely that the issue will be fixed.

> Do i need to set any environment variable to run on selenium grid ? especially MFA login

There are no special environment variables in Playwright apart from `SELENIUM_REMOTE_URL` and `SELENIUM_REMOTE_CAPABILITIES` that might affect things when running with selenium grid.

**Comment by mridiniveni** [comment]
what capabilities do i need to pass for chromium in SELENIUM_REMOTE_CAPABILITIES ?

**Comment by dgozman** [comment]
@mridiniveni Unfortunately, we won't be able to help without a repro and access to your grid.

> what capabilities do i need to pass for chromium in SELENIUM_REMOTE_CAPABILITIES ?

This is entirely up to your grid setup. Playwright just passes them along in the `desiredCapabilities` property, and your grid should interpret them.

**Comment by aslushnikov** [comment]
I'll close this issue since the discussion here has stalled. If you think we still can be helpful, please file a separate issue!
