### ISSUE TITLE
[BUG] Using `Locator.check()` fail with an error "Clicking the checkbox did not change its state"

### ISSUE THREAD

**Issue by tui95** [microsoft/playwright#27016]
I am using a UI library called [NG-ZORRO](https://ng.ant.design/docs/introduce/en) and came across this bug when using Playwright to test a radio button in a form.

This might be a duplicate of https://github.com/microsoft/playwright/issues/20893 and https://github.com/microsoft/playwright/issues/17559

### System info
- Playwright Version: [v1.37.1]
- Operating System: [macOS 12.6.8]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
import { test } from "@playwright/test";

test('radio', async ({ page }) => {
  await page.goto("https://ng.ant.design/components/radio/en");
  await page.getByRole("radio", { name: "Radio" }).check();
});
```

**Steps**
- [Run the test]

**Expected**

The test should succeed since the radio is checked.

**Actual**

The test failed with an error message
```shell
Running 1 test using 1 worker
  1) radio.spec.ts:3:5 › radio ─────────────────────────────────────────────────────────────────────

    Error: locator.check: Clicking the checkbox did not change its state
    =========================== logs ===========================
    waiting for getByRole('radio', { name: 'Radio' })
      locator resolved to <input type="radio" class="ant-radio-input"/>
    attempting click action
      waiting for element to be visible, enabled and stable
      element is visible, enabled and stable
      scrolling into view if needed
      done scrolling
      performing click action
      click action done
      waiting for scheduled navigations to finish
      navigations have finished
    ============================================================

      3 | test('radio', async ({ page}) => {
      4 |     await page.goto("https://ng.ant.design/components/radio/en")
    > 5 |     await page.getByRole("radio", { name: "Radio" }).check()
        |                                                      ^
      6 | })

        at /private/tmp/playwright-radio/tests/radio.spec.ts:5:54
```
[trace.zip](https://github.com/microsoft/playwright/files/12585642/trace.zip)

**Comment by dgozman** [comment]
@tui95 Playwright thinks that checkbox was not checked, because `<input>`'s `checked` property was not set to `true`. The library you are using should probably update the property to make sure browsers and accessibility tools understand that checkbox is actually checked.

You can work around the issue by passing the `force` option, or calling `click()` instead:
```js
await page.getByRole("radio", { name: "Radio" }).check({ force: true });
// ---- or ----
await page.getByRole("radio", { name: "Radio" }).click();
```

**Comment by tui95** [comment]
I see. Thank you for explaining. I'll close this issue since it isn't actually a bug.
