### ISSUE TITLE
Test fails only in webkit

### ISSUE THREAD

**Issue by pmenika** [microsoft/playwright#27013]
Hi,

I just created a playwright project using `npm init playwright@latest` and then I ran the command `npx playwright test`. The example test only fails in Webkit.
I am seeing below error

<img width="1122" alt="image" src="https://github.com/microsoft/playwright/assets/44428058/9a923974-9e92-4ceb-b488-7c4dbe0119f9">

**Comment by mxschmitt** [comment]
Which macOS version are you using? Only latest 12.x an 13.x are supported.

**Comment by pmenika** [comment]
> Which macOS version are you using? Only latest 12.x an 13.x are supported.

Hi, I am using 12.2.1

<img width="514" alt="image" src="https://github.com/microsoft/playwright/assets/44428058/1e9abcdb-d49e-4ac3-99ac-eb03e58f7b83">

**Comment by mxschmitt** [comment]
Yeah we strongly recommend updating to 12.6 which should fix that issue.

**Comment by pmenika** [comment]
> Yeah we strongly recommend updating to 12.6 which should fix that issue.

Thanks I will check
