### ISSUE TITLE
[BUG] Extension service worker never becomes inactive in manifest V3

### ISSUE THREAD

**Issue by avishail** [microsoft/playwright#27015]
According to [this issue](https://github.com/microsoft/playwright/issues/26958), service worker can't become inactive and it was flagged as a feature. 

In manifest V3, which is **mandatory** by google, there is only a background service worker. The nature of service worker is that it becomes inactive and goes down if there is no relevant activity and later will become active when relevant activity happens. (relevant = events the service worker listens to)

When service worker becomes active after it was inactive, its memory becomes clean and it will have to restore its state which is a very critical and not trivial phase. Not having this creates huge blindspot compared to the real world.

I was wondering if this is something worth fixing in the near future?

Thanks!

**Comment by dgozman** [comment]
@avishail Playwright does not affect Chromium browser behavior in this area. #26958 implied that Playwright also does not have any special feature to force activate or deactivate the service worker, or to monitor its state changes.

IIUC, you suggest that Playwright does actually affect the browser behavior. That's something we can look at, as long as you provide a repro that we can run locally and explain how do you verify the activation/deactivation behavior. Let me know what you think.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
