### ISSUE TITLE
[BUG] Firefox does not open new TABs only new Browser windows

### ISSUE THREAD

**Issue by christerhamberg** [microsoft/playwright#27023]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Windows 11]
- Browser: [Firefox]
- Other info:

### Source code

[TestClass]
public class UnitTest1
{

    [TestMethod]
    public async Task MainPage()
    {

        using var playwright = await Playwright.CreateAsync();
        await using var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions()
            {
                Headless = false

            }
        );

        var contxt = await browser.NewContextAsync(new BrowserNewContextOptions()
        {

        });

        // open Browser Window 1
        var page = await contxt.NewPageAsync();

        // Open Tab 2
        var page1 = await contxt.NewPageAsync();

        // Open Tab 3
        var page2 = await contxt.NewPageAsync();

        // Open Tab 4
        var page3 = await contxt.NewPageAsync();

        await page.GotoAsync("https://playwright.dev");
        await page1.GotoAsync("https://playwright.dev");
        await page2.GotoAsync("https://playwright.dev");

        //String title = await page.TitleAsync();
        //Assert.AreEqual(pageTitle, title);

       // await page.ScreenshotAsync(new() { Path = "theverge.png" });

        Thread.Sleep(10000);

    }
}

**Link to the GitHub repository with the repro**

**Config file**

**Test file (self-contained)**

**Steps**
- [Run the test]
With firefox 4 separate windows are opened
Replace line  await using var browser = await playwright.Firefox.LaunchAsync(new BrowserTypeLaunchOptions() with CHROMIUM instead i.e.         await using var browser = await playwright.Chromium.LaunchAsync(new BrowserTypeLaunchOptions()
One window with 4 tabs is opened

**Expected**

In Firefox a tab should be opened and not a new browser window

**Actual**

In Firefox a browser window is always opened

**Comment by mxschmitt** [comment]
https://github.com/microsoft/playwright/issues/3696

**Comment by dgozman** [comment]
Merging into #3696.
