### ISSUE TITLE
[BUG] Webkit clears on page.type – Chromium/Firefox don't

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2702]
**Context:**
- Playwright Version: 1.1.1 and next
- Operating System: Windows and Mac
- Browser: Webkit

**Code Snippet**

```javascript
const {webkit} = require('playwright');

(async () => {
    const browser = await webkit.launch({headless: false, slowMo: 100});
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.setContent(`<input type="text" id="example" value="default" />`);
    await page.type('#example', 'text');
    await browser.close();
})();
```

Browser behaviors for input value:
* Chromium: textdefault
* Firefox: textdefault
* Webkit: text

Should they behave consistently? Is webkit a bug?

**Comment by yury-s** [comment]
I'd expect `page.fill()` to clear the old value, i.e. every browser behave like webkit does today.

**Comment by arjun27** [comment]
@yury-s: I meant to share the snippet with `page.type` (not `fill`), which is behaving differently on webkit. Apologies for the confusion!

**Comment by JoelEinbinder** [comment]
I'll take a look.

**Comment by JoelEinbinder** [comment]
So there is some real difference in the browser behavior here. In webkit, `HTMLInputElement.focus()` causes all of text to be selected. In Firefox and Chromium, it puts the cursor at the start of if the input field. However, all of the browsers are consistent when tabbing into an element. They select all of the text.

Right now our typing is implement as
```
type(element, text):
   focus(element)
   keyboard.type(text)
```

Maybe we should make our focus behave like keyboard focus, selecting the text. Maybe we are doing the correct thing, and users should expect/want this behavior to be different.

The [spec](https://html.spec.whatwg.org/multipage/interaction.html#focus-update-steps) unhelpfully says that this behavior is platform specific:

> Apply any relevant platform-specific conventions for focusing new focus target. (For example, some platforms select the contents of a text control when that control is focused.)

**Comment by pavelfeldman** [comment]
I'd say consistency is what is important. And since it is probably easier to select all the text than unselect it, I'd do that.
