### ISSUE TITLE
[BUG] pnpm create playwright with TypeScript doesn't install type definitions for node

### ISSUE THREAD

**Issue by GeorgeXCV** [microsoft/playwright#27037]
### System info
- Playwright Version: v1.37.1
- Operating System:  Mac 13.5.2 (22G91)
- Browser: N/A
- Other info:

### Source code

`pnpm create playwright`

**Steps**
- Run `pnpm create playwright`
- Check `playwright.config.ts`

**Expected**

No type errors in the config file.

**Actual**

Cannot find name 'process'. Do you need to install type definitions for node? Try `npm i --save-dev @types/node`.ts(2580)

**Comment by dgozman** [comment]
This has been recently fixed by https://github.com/microsoft/create-playwright/pull/99.
