### ISSUE TITLE
"Page Closed" after goBack() in headless mode

### ISSUE THREAD

**Issue by lutuvarka** [microsoft/playwright#27032]
`await expect(createAccountPage.email).toBeVisible(); // This passes fine`
`await createAccountPage.selectNext(); // This clicks a button that navigates away`
`await createAccountPage.goBack(); // This is the standard issue PlayWright method`
`await expect(createAccountPage.email).toBeVisible(); // This times out aftet 5000ms...`

When I debug this with Edge - works fine.
First thought was "timing" but I tried all sorts of waits... Even ended up trying `await new Promise(f => setTimeout(f, 10000));` - to no avail.

Please, any ideas of what to try or where to look?
Can't make sense of this.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
