### ISSUE TITLE
[BUG] blank canvas in UI mode

### ISSUE THREAD

**Issue by sebakerckhof** [microsoft/playwright#27043]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [Ubuntu 22.04]
- Browser: [All]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('canvas test', async ({ page }) => {
  await page.goto('https://openlayers.org/en/latest/examples/simple.html');
});
```

**Steps**
- [Run the test in ui mode]

**Expected**

The canvas should show a map

**Actual**

![image](https://github.com/microsoft/playwright/assets/88471/35084970-cde2-49ae-9924-19ebd7ad3271)

The screenshots in the timeline and taken by the test do contain the contents. Just used this openlayers example to show the issue, but this is true for any canvas I've tried

**Comment by dgozman** [comment]
Merging into #23964.
