### ISSUE TITLE
[BUG] Playwright hangs after running tests

### ISSUE THREAD

**Issue by MikeFear** [microsoft/playwright#27048]
We ran into the issue that Playwright very often gets stuck after running the tests. This started happening after we upgraded to Playwright 1.35.0 and now prevents us from upgrading. We didn't dispose the created contexts for the API calls in the beginning and I thought this could be the issue but it still happens even after disposing the contexts. I boiled down our test code to a minimal reproducible example. There are multiple factors which are necessary to trigger it:
- New context and page must be created in a nested describe block
- You need to navigate at least once
- At least 2 API contexts need to be created

After it gets stuck you see a process of **process.js** getting stuck with 100-200% CPU usage which never exits:
<img width="1850" alt="image" src="https://github.com/microsoft/playwright/assets/34158371/85762481-4d3d-49b4-b4d0-40dcc451fd71">

We occasionally also saw it happening on GitHub Actions with Ubuntu but couldn't reliably reproduce it.
There is already a similar issue to this: https://github.com/microsoft/playwright/issues/24071

### System info
- Playwright Version: v1.35.0 - v1.37.1
- Operating System: macOS 13.5.2
- Browser: All
- Other info: Node.js 18.17.1

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/MikeFear/playwright-repro/tree/main

**Steps**
- Run test with `npm test` multiple times until it fails (sometimes it doesn't fail on the first try)
- Adjust afterAll() hook and remove the disposal of the API contexts. Now you get a different error.
- Switch to branch **1.34.3** and run `npm test` again. In this version there seems to be no issues.

**Expected**

Test runs and exits without any problems.

**Actual**

Test runs very often in a timeout and logs errors like this:
### With disposing API contexts:
```
Running 1 test using 1 worker
  1) [chromium] › example.spec.ts:35:9 › Example › inner tests › test ──────────────────────────────

    "afterAll" hook timeout of 10000ms exceeded.

      16 |   });
      17 |
    > 18 |   test.afterAll(async () => {
         |        ^
      19 |     await firstApiClient.dispose();
      20 |     await secondApiClient.dispose();
      21 |   });

        at /Users/michael/Projekte/playwright-repro/tests/example.spec.ts:18:8

    Error: ENOENT: no such file or directory, open '/Users/michael/Projekte/playwright-repro/test-results/.playwright-artifacts-0/19eec201de852ab3e050b299e474a359.zip'
```

### Without disposing API contexts:
```
Running 1 test using 1 worker
  1) [chromium] › example.spec.ts:35:9 › Example › inner tests › test ──────────────────────────────

    "afterAll" hook timeout of 10000ms exceeded.

      16 |   });
      17 |
    > 18 |   test.afterAll(async () => {
         |        ^
      19 |     //await firstApiClient.dispose();
      20 |     //await secondApiClient.dispose();
      21 |   });

        at /Users/michael/Projekte/playwright-repro/tests/example.spec.ts:18:8

    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results/example-Example-inner-tests-test-chromium/trace.zip
    Usage:

        npx playwright show-trace test-results/example-Example-inner-tests-test-chromium/trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

Worker teardown timeout of 10000ms exceeded while tearing down "trace recording".

Failed worker ran 1 test:
[chromium] › tests/example.spec.ts:35:9 › Example › inner tests › test
```

**Comment by dgozman** [comment]
I can repro. Switching trace off fixes the issue. I think the problem is that trace name is clashing between multiple contexts. This has probably regressed in #22746.

**Comment by MikeFear** [comment]
@dgozman Tested the latest canary release and it works now! Thanks a lot! :)

**Comment by Doug-Bowen** [comment]
This is still happening for me.  I'm on playwright 1.41.2.

When utilizing globalSetup with tracing, Playwright hangs. 

Disabling tracing allows Playwright to finish. 
Disabling global setup allows Playwright to finish. 
Enabling them both but setting retries to 0, allows Playwright to finish. 

Unsure how to fix this.

**Comment by jlowndes-chwy** [comment]
@dgozman
This is also still happening for myself. I am running playwright 1.42.
I experienced the same as Doug-Bowen mentioned above, and resolved by disabling tracing.

**Comment by dgozman** [comment]
@jlowndes-chwy @Doug-Bowen Could you please file a new issue by filling in the "Bug Report" template and providing a repro? We would love to look at it!
