### ISSUE TITLE
[BUG] Getting this Error Error: page.goto: Page crashed in Adobe Cloud Manager CI CD Pipeline

### ISSUE THREAD

**Issue by ramk7799** [microsoft/playwright#27056]
### System info
- Playwright Version: [v1.XX]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
const { defineConfig, devices } = require('@playwright/test');
// Define default values for environment variables
const reportsPath = process.env.REPORTS_PATH || './reports/';
const authorURL = process.env.AEM_AUTHOR_URL || 'http://localhost:4502';
const authorName = process.env.AEM_AUTHOR_USERNAME || 'admin';
const authorPass = process.env.AEM_AUTHOR_PASSWORD || 'admin';
const publishURL = process.env.AEM_PUBLISH_URL || 'http://localhost:4503';
const publishName = process.env.AEM_PUBLISH_USERNAME || 'admin';
const publishPass = process.env.AEM_PUBLISH_PASSWORD || 'admin';

module.exports = defineConfig({
  testDir: './tests',
  //sets timeout for each test case
  timeout: 120000,
  expect: {
    timeout: 5000
  },
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  //Reporters
  reporter:[
    ['html', { open: 'never', outputFolder: reportsPath }], // Updated outputFolder
    ["junit", { outputFile: `${reportsPath}/results.xml` }], // Updated outputFile for JUnit
    ["json", { outputFile: `${reportsPath}/results.json` }]],
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'https://***.***.dev/components/',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    // Add environment variables to the use section
    REPORTS_PATH: reportsPath,
    AEM_AUTHOR_URL: authorURL,
    AEM_AUTHOR_USERNAME: authorName,
    AEM_AUTHOR_PASSWORD: authorPass,
    AEM_PUBLISH_URL: publishURL,
    AEM_PUBLISH_USERNAME: publishName,
    AEM_PUBLISH_PASSWORD: publishPass,
    viewport: { width: 1280, height: 720 },
    headless: true,
    launchOptions: {
      slowMo: 1000,
    },
    video:"on"
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },

    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },

    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ]
});

```

**Test file (self-contained)**

```js
// @ts-check
const { test, expect } = require('@playwright/test');

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});

```

**Steps**
- [Run the test]
- [...]
# Use the official Playwright image
FROM mcr.microsoft.com/playwright:v1.37.0-jammy

# Set environment variables
ENV APP_PATH /usr/src/app
ENV REPORTS_PATH reports

# Set the working directory
WORKDIR ${APP_PATH}

# Copy the Playwright test files into the container
COPY ./test-module ./

# Install project dependencies
RUN npm install

# Get the needed libraries to run Playwright
RUN apt-get update && apt-get -y install libnss3 libatk-bridge2.0-0 libdrm-dev libxkbcommon-dev libgbm-dev libasound-dev libatspi2.0-0 libxshmfence-dev

# Install browsers and their dependencies
RUN npx playwright install

RUN npm run test

"scripts": {
    "test": "npx playwright test --headed --project=chromium"
}

**Expected**

Tests are failing in Adobe Cloud Manager Pipeline but not in local with this error Getting this Error Error: page.goto: Page crashed

**Actual**

All the tests should pass with out any error.

**Comment by dgozman** [comment]
@ramk7799 The browser page crashes - this usually happens because it runs out of memory. However, this might also be a browser bug. You can try running with `DEBUG=pw:browser*` environment variable - perhaps browser prints a stack trace for this crash and we can report/fix it in Chromium.

**Comment by dgozman** [comment]
Closing as per above, since we cannot do anything without a stack trace. If you manage to get native stack trace from Chromium, please file a new issue by filling in the "Bug Report" template.
