### ISSUE TITLE
[Question] Should Playwright kill the browser process on TimeoutError?

### ISSUE THREAD

**Issue by arjun27** [microsoft/playwright#2705]
```js
const {chromium} = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    context.setDefaultTimeout(3000);
    const page = await context.newPage();
    await page.goto('https://bing.com');
    await page.click('#fictional-selector');
    await browser.close();
})();
```

Currently, this script will fail with a `UnhandledPromiseRejectionWarning: TimeoutError`. That will lead to the Node and browser processes being stuck and unusable. I could add catch the error, but who uses try-catch anyway?

Even if I do add a try-catch, I would be tempted to wrap the whole snippet and not handle the catch.

```js
const {chromium} = require('playwright');

(async () => {
    try {
        const browser = await chromium.launch();
        const context = await browser.newContext();
        context.setDefaultTimeout(3000);
        const page = await context.newPage();
        await page.goto('https://bing.com');
        await page.click('#fictional-selector');
        await browser.close();
    } catch (e) {
        //
    }
})();
```

But this seems to hang indefinitely, and does not print anything to stdout. 

I could focus the try-catch to the line I know fails, but is it fair to assume that I know which line will fail? Doing so will fix the hanging processes.

```js
const {chromium} = require('playwright');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    context.setDefaultTimeout(3000);
    const page = await context.newPage();
    await page.goto('https://bing.com');
    try {
        await page.click('#fictional-selector');
    } catch (e) {
        //
    }
    await browser.close();
})();
```

I know I'm taking many shortcuts, but only trying to represent what I see in the wild :)

**Comment by pavelfeldman** [comment]
Typically, you would have a test that accepts the browser, context or page object. That entire test will be called from a code that catches exception. That exception handler is responsible for the cleanup. It'll close page, context or browser respectively, also in a local sildent try/catch block.

**Comment by pavelfeldman** [comment]
A single timeout in a single action on a certain page is definitely not a reason to close the browser. Close a page or context - maybe, but why closing the browser?

**Comment by dgozman** [comment]
> That will lead to the Node and browser processes being stuck and unusable.

I guess this is the main issue? Why not Ctrl+C the node process? Also, if the browser is running headful, it should still be usable.

**Comment by arjun27** [comment]
Yes, you're right. The question was to check if we can have a better dev experience than Ctrl+C. But I agree that there's value in leaving the headful browser usable. It is also common for the test runner to handle such cases and count it as a failed test. I'm closing this issue as we are doing what we can in the context of playwright.
