### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by Udjain** [microsoft/playwright#27064]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
Hi Team,

I am trying to achieve automated updating of work items, test cases in ADO via RESP API. One of the API I came across require content-type as "application/json-patch+json". I am have written below code to send the headers & body however I am getting an error as : "You must pass a valid patch document in the body of the request."

I believe the body provided in "data" is auto read as json object & I am not able to find a way to pass patch document through the data object. I tried with string but that also is not working for me. Not sure if the feature is not available or I am not able to figure it out.

This will benefit in automation with ADO rest API's.

code:
```
const response = await this.request.patch(baseURL, {
                headers:{
                    'Accept': '*/*',
                    'Authorization': basicAuth,
                    'Content-Type' : 'application/json-patch+json'
                },
                data: {
                    op: "add",
                    path: "/relations/-",
                    value: {
                        rel: "ArtifactLink",
                        url: "vstfs:///Build/Build/"+ process.env.buildid,
                        attributes: {
                            name: "Build"
                        }
                    }
                }
        })
```

**Comment by dgozman** [comment]
@Udjain I believe this should work - it sends correct `Content-Type` header and json-serialized `data` object. I'd recommend checking what's actually expected from the API.

```
→ PATCH http://example.com/ +4ms
   user-agent: Playwright/1.39.0-next (arm64; macOS 13.5) node/16.17 +0ms
   accept: */* +0ms
   accept-encoding: gzip,deflate,br +0ms
   Authorization: basic +0ms
   Content-Type: application/json-patch+json +0ms
   content-length: 134 +0ms
   BODY: {"op":"add","path":"/relations/-","value":{"rel":"ArtifactLink","url":"vstfs:///Build/Build/undefined","attributes":{"name":"Build"}}}
```

Alternatively, you can provide a repro that we can run locally and describe what would you expect to happen in this case.

**Comment by Udjain** [comment]
@dgozman I tried this API on postman and it worked fine however through playwright I am getting error saying "You must pass a valid patch document in the body of the request.". 
Just thinking out loud, is it possible that when I provide data, that is getting converted to json string as mentioned in document however the patch format is little different which is starting with square brackets.

In order to reproduce:
Pre-requisite-> you need to create a work item (user story in my case) in ADO & a build ID from any pipeline run
Basic auth using your PAT

Use base URL: https://dev.azure.com/{organization}/{project}/_apis/wit/workitems/{id}?api-version=7.0 and then run below code:

const response = await this.request.patch(baseURL, {
                headers:{
                    'Accept': '*/*',
                    'Authorization': {basicauth},
                    'Content-Type' : 'application/json-patch+json'
                },
                data: {
                    op: "add",
                    path: "/relations/-",
                    value: {
                        rel: "ArtifactLink",
                        url: "vstfs:///Build/Build/"+ {buildid},
                        attributes: {
                            name: "Build"
                        }
                    }
                }
        })

You can also refer this link for details:
https://learn.microsoft.com/en-us/rest/api/azure/devops/wit/work-items/update?view=azure-devops-rest-7.0&tabs=HTTP

Thank you for looking through it!

**Comment by dgozman** [comment]
@Udjain Well, if the API wants an array, you should pass an array (note the square brackets around data):

```ts
const response = await this.request.patch(baseURL, {
                headers:{
                    'Accept': '*/*',
                    'Authorization': basicAuth,
                    'Content-Type' : 'application/json-patch+json'
                },
                data: [{
                    op: "add",
                    path: "/relations/-",
                    value: {
                        rel: "ArtifactLink",
                        url: "vstfs:///Build/Build/"+ process.env.buildid,
                        attributes: {
                            name: "Build"
                        }
                    }
                }]
        })
```

Playwright just passes whatever json you put into `data` directly to the request body.

**Comment by Udjain** [comment]
@dgozman Thank you very much for checking. This worked! :)

Didn't thought of such a small thing I was missing, appreciated quick turnaround on this. This helped increased my knowledge & confidence with the tool.

Have a great day!
