### ISSUE TITLE
expect(value).toMatchSnapshot() deprecation announcement on V1.38

### ISSUE THREAD

**Issue by ofirpardo-artlist** [microsoft/playwright#27071]
Just saw this deprecation announcement on V1.38:
https://playwright.dev/docs/release-notes#deprecations

- The method [expect(value).toMatchSnapshot()](https://playwright.dev/docs/api/class-snapshotassertions#snapshot-assertions-to-match-snapshot-1) is deprecated in favor of [expect(page).toHaveScreenshot()](https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1) and [expect(locator).toHaveScreenshot()](https://playwright.dev/docs/api/class-locatorassertions#locator-assertions-to-have-screenshot-1).

I don't understand the reasoning behind this, not sure if you're aware of this but this method can be used for any snapshot required and not only screenshots, therefore for my use case I cannot replace toMatchSnapshot with toHaveScreenshot since I don't verify a screenshot but a buffer.
I know many others that use this in a similar way, and I know that deprecation doesn't mean it's removed, but I want to raise it now before it could be removed in the future.

The fact that this method can be replaced with toHaveScreenshot for some cases doesn't mean it should be and having it as deprecated, or worse removing it is an incorrect lose of useful functionality.
Please reconsider this. Thanks.

**Comment by pavelfeldman** [comment]
Release notes are wrong, they should say "for images". toMatchSnapshot for strings and buffers is still there and is not marked as deprecated in api and in the docs. Thanks for spotting it.

**Comment by aslushnikov** [comment]
@ofirpardo-artlist our of curiosity, what kind of data do you have in your buffers? Are these not images?

**Comment by joshualoehr-smar** [comment]
@aslushnikov not OP but I just recently wrote a test that uses `.toMatchSnapshot` to verify a downloaded PNG that is generated client side. It's an image but not one that comes from screenshotting the page.

**Comment by jacobrask** [comment]
FWIW, we use `toMatchSnapshot` to match HTML snapshots, to make sure markup changes to widely used components don't go unnoticed.

**Comment by aslushnikov** [comment]
Thank you folks for the input! The deprecation has been reverted in 1.38.1.
