### ISSUE TITLE
[Feature] Expose GUID

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#27075]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

We are using `_guid` in playwright-node, in playwright-python is is not accessible even though it is available in the code (https://github.com/microsoft/playwright-python/blob/0e92fbc2cceba0551305f2e36f75f9b71f5d5b6e/playwright/_impl/_frame.py#L75C50-L75C50).

We want to use the `_guid` to attribute to which frame(chain) certain responses belong in complex scenarios with various frames.

**Comment by dgozman** [comment]
@JannisBush Could you please explain your usecase in more details? Ideally, with an example snippet that illustrates the usage of `_guid` in playwright for Node.js. This would help us prioritize the feature.

**Comment by JannisBush** [comment]
We are using playwright for web measurement studies. 
We are collecting all kind of data such as IFrame and JavaScript inclusions on a page. For each inclusions we want to know which Frame it belongs to such that we can attribute the inclusion to it and decide whether it is third-party or not and whether it is a direct inclusion or a nested one (and if yes how many nested hops there are). 
Using exposed attributes such as `url` is not reliable as some pages include the same URL in several frames (at different nesting levels). 

Here is some code where we save the frameId and it's parent for each new frame:
```js
page.on('frameattached', async (framedata: any) => {
    let title: string = "";
    try {
        title = await framedata.title();
    } catch (err: any) {
        title = "";
    }
    var frame: any = {
        frameSrc: framedata.url(),
        endUrl: framedata.url(),
        frameId: framedata._guid,
        parentFrameId: framedata.parentFrame() ? framedata.parentFrame()._guid : "",
        title: title,
        requests: [],
        findings: [],
        main: false,
        storage: []
    }
    this.frames.push(frame);
});
```

**Comment by dgozman** [comment]
@JannisBush I'd recommend using an external id in this case: either a `Map<Frame, string>` or put it on `Frame` with a symbol. Let me know whether that helps.

```ts
const frameIdSymbol = Symbol('frameId');
let lastFrameId = 0;
function getFrameId(frame) {
  let id = frame[frameIdSymbol];
  if (!id) {
    id = ++lastFrameId;
    frame[frameIdSymbol] = id;
  }
  return id;
}
```

**Comment by aslushnikov** [comment]
Closing as per above!
