### ISSUE TITLE
[Question] Unable to load website on Webkit

### ISSUE THREAD

**Issue by Sreejithw** [microsoft/playwright#2707]
I am currently trying to run a test on my local machine VS Code to generate screenshots for webkit browser.
My Code is shown below:

<img width="426" alt="Capture" src="https://user-images.githubusercontent.com/11564859/85655487-eb0c1580-b6f2-11ea-8e2d-82b260ae8c38.PNG">

The test is successful on any other site other than a sapui5 web application.

**Comment by mxschmitt** [comment]
See my answer on StackOverflow already: https://stackoverflow.com/a/62552901/6512681

The issue is, that SAP UI5, the web framework where the website is based on, is not fast enough and not using the DOMContentLoaded events e.g. to signal that the web page has finished with loading and rendering.

**Comment by Sreejithw** [comment]
I apologize haha, i was the one who posted the question. I actually wanted to follow up because i couldn't understand two things. If the SAPUI5 web application is too slow and not using the DOMContentLoaded events, then how is it possible that i can generate screenshots for webkit if i use playwright's testing playground online? Also, how come SAPUI5 applications can open with both chromium and firefox?

**Comment by mxschmitt** [comment]
Hm, it seemed to be some temporary issue on their side. I retried a bit, locally and on [Try Playwright](https://try.playwright.tech/?s=4gef3). On both environments around 5 times and all of them were successfully.

**Comment by Sreejithw** [comment]
Hmm that's interesting, it still seems to be not working for me locally. It might be my machine. Are you using windows by any chance??

**Comment by pavelfeldman** [comment]
@Sreejithw could you follow a new bug template and specify your environment?
