### ISSUE TITLE
[BUG] RangeError: Invalid time value

### ISSUE THREAD

**Issue by jiadesen** [microsoft/playwright#27073]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS 13.5.2]
- Browser: [WebKit]
- Other info: use fixtures like [worker-scoped-fixtures](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures)

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  use: {
      browserName: "webkit",
      launchOptions: {
          slowMo: 100,
      },
      navigationTimeout: 60 * 1000,
      hasTouch: true,
      isMobile: true,
      trace: "retain-on-failure",
      video: "on",
      screenshot: "only-on-failure",
      ignoreHTTPSErrors: true,
      headless: false,
      viewport: { width: 375, height: 667 },
    },
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://playwright.dev/');
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

Test Crash!!!

**Comment by StasGrishaevTutu** [comment]
@dgozman alright, I understand that this looks super weird, but this problem only occurs on one site for me. I made a micro [repository](https://github.com/StasGrishaevTutu/pw-time-issue) where I catch this problem in a test with `await page.goto('https://id.tutu.ru');`
could you please check, will you be able to reproduce it?
just clone repo and run `npm i && npx playwright install && npx playwright test --reporter=line`

**Comment by StasGrishaevTutu** [comment]
so, guys, I think I understand - if you remove or comment out the config line `trace: "retain-on-failure"` - the error goes away.
Apparently, this is somehow connected with the updated timeline in the UI mode (which, as I understand it, also affects and traces)

**Comment by dgozman** [comment]
@StasGrishaevTutu The problem is that your web page responds with `Set-Cookie` header that has an invalid `Expires` value: `Expires=Sat Sep 14 01:02:27 MSK 2024`.

I'll make sure that Playwright can handle this, but you might want to look into this from your side as well.

**Comment by samSam-0** [comment]
This issue is still occurring. Especially on ci/cd runs.

System info

    Playwright Version: [v1.38.0]
    Operating System: [macOS 13.5.2]
    Browser: [Chrome]


Config file

// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  use: {
      browserName: "chromium",
      launchOptions: {
          slowMo: 1000,
      },
      trace: "on",
      video: "on",
      screenshot: "only-on-failure",
      ignoreHTTPSErrors: true,
      headless: false,
      viewport: { width: 1850, height: 950 },
    },
});

**Comment by StasGrishaevTutu** [comment]
@samSam-0 this should be in 1.38.1 release, I guess. Or you can get this now by `npm install -D @playwright/test@next`

**Comment by samSam-0** [comment]
> @samSam-0 this should be in 1.38.1 release, I guess. Or you can get this now by `npm install -D @playwright/test@next`

it worked thanks

**Comment by rapattonimusic** [comment]
> so, guys, I think I understand - if you remove or comment out the config line `trace: "retain-on-failure"` - the error goes away. Apparently, this is somehow connected with the updated timeline in the UI mode in 1.38.0 (which, as I understand it, also affects and traces)

Oh wow. THANK YOU! Setting `trace: 'off'` completely resolved the issue. I was only experiencing it when running tests on Webkit by the way. Thanks again!
