### ISSUE TITLE
[BUG] PWT trace viewer fails to load trace and throws TypeError

### ISSUE THREAD

**Issue by miliberlin** [microsoft/playwright#27072]
### System info
- Playwright Test Version: v1.32.3
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

We are currently experiencing the issue of not being able to view traces in the web preview with the following error in some cases:

<img width="1507" alt="Screenshot 2023-09-14 at 11 43 15" src="https://github.com/microsoft/playwright/assets/54396648/3c8323e7-634c-480a-9c84-1922ea270d5b">

**Comment by dgozman** [comment]
@miliberlin Could you please share the trace file that cannot be loaded? We need it to be able to debug the issue.

**Comment by uchagani** [comment]
I'm seeing the same thing.  I've attached a sample file
[fooTest.zip](https://github.com/microsoft/playwright/files/12611249/fooTest.zip)

**Comment by miliberlin** [comment]
@dgozman thank you for tackling this issue but we are still encountering the error. Could I send the file via email? I can not share it publicly.

**Comment by dgozman** [comment]
@miliberlin The fix will be in v1.38.1, which should be soon.
