### ISSUE TITLE
[Feature] Add option to change toMatchSnapshot animation option globally

### ISSUE THREAD

**Issue by cunhabruno** [microsoft/playwright#27082]
Would it be possible to add the ability to set the toMatchSnapshot animation option in the config file or somewhere else?

In my code I have to disable screenshot animation in every screenshot step like this:

>         const authorizedDialogScreenshot = await manageConnectionDialog.main.screenshot({ animations: 'disabled' });
>         expect(authorizedDialogScreenshot).toMatchSnapshot();

**Comment by dgozman** [comment]
@cunhabruno This is already possible via [`config.expect` property](https://playwright.dev/docs/api/class-testconfig#test-config-expect). Let me know whether this helps.

**Comment by cunhabruno** [comment]
@dgozman I have tried this one but that did not work, it changes for the `toHaveScreenshot` method, and it does not seem that  `toMatchSnapshot` has `animation` option in the config file property.

**Comment by cunhabruno** [comment]
Okay, understood, I didn't know I could use `toHaveScreenshot` with locators as well, I thought it was just for pages, and that solved my issue! Thanks!
