### ISSUE TITLE
[BUG] look into Map/Set refs handling when serializing

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#27084]

**Comment by Tallyb** [comment]
I get an error when trying to get an angular component using evaluate function as follow: 
```
      const ngCmp = await locator.evaluate((c) => {
        const comp = window['ng'].getComponent(c);
        return comp;
      });
```
This is a regression from PW 1.37.1. 
1.3.71 - angular component object returned. 
1.38.0 - getting undefined. 

(FFIW: if I am trying to get an attribute on the component as follow it works.  
```
        const value = window['ng'].getComponent(c)[att];
        return value;
```
)
Do you think this is related?

**Comment by mxschmitt** [comment]
Unrelated to your comment Tally. We don't plan to implement this issue.

Re your comment, looks like a regression, please file separately.

**Comment by Tallyb** [comment]
Curious to know @mxshcmitt, as it seems related to the fixed bug, no? 
https://github.com/microsoft/playwright/issues/27181
