### ISSUE TITLE
[Feature] Looking for roadmap of node.js features to be available for java/.net 

### ISSUE THREAD

**Issue by Udjain** [microsoft/playwright#27088]
Hi Team,

Do you have any roadmap to have playwright test runner for java/.net so to utilize features like parallelization mechanism, screenshot assertions, html reporter, automatic tracing etc.?

Note: This is like the query not feature request but not getting any other option for raising it.

**Comment by pavelfeldman** [comment]
There is no roadmap for these features. But please file a separate feature request so that we could track the demand for respective language features, even though you are only querying.

**Comment by dgozman** [comment]
Closing as per above. Please file separate issues for things you are missing in java/.net.
