### ISSUE TITLE
wants to extract the all link from webppage.

### ISSUE THREAD

**Issue by kunal0810** [microsoft/playwright#2708]
I have to implemented this function.

var hyperlinks = await page.evaluate( () => {
    return document.links;
});

web page has about 287 links but  this function is returning a array of 287 element but every 287 element is empty not able to href of those element.

**Comment by osmenia** [comment]
Try this with your CSS selector:

const [podURL] = 
       await page.evaluate(() => {
      let podcasts = document.querySelectorAll("Your "A" selector");

      let podURL = [];

      podcasts.forEach((elem) => {
        podURL.push(elem.querySelector("a[href]").href);
      });

      return [podURL];
    });

**Comment by mxschmitt** [comment]
Thats a script which I wrote a while ago, maybe it helps:

```js
// @ts-check
const playwright = require('playwright')
;(async () => {
  const browser = await playwright.chromium.launch()
  const page = await browser.newPage()
  const seenURLs = new Set()
  const crawl = async (url) => {
    if (seenURLs.has(url)) {
      return
    }
    seenURLs.add(url)
    if (!url.startsWith('https://playwright.dev')) {
      return
    }
    console.log(`Visiting ${url}`)
    await page.goto(url)
    await page.waitForSelector('.view-body>*')
    const urls = await page.$$eval('a', (elements) =>
      elements.map((el) => el.href),
    )
    for await (const u of urls) {
      await crawl(u)
    }
  }
  await crawl('https://playwright.dev')
  console.log(`Checked ${seenURLs.size} URLs`)
  await browser.close()
})()
```

**Comment by arjun27** [comment]
@kunal0810 - The result of the function inside `page.evaluate` needs to be serializable – so that it can be transported over the wire from the browser to Nodejs. You can modify your snippet to fix that:

```js
const hrefs = await page.evaluate(() => Array.from(document.links).map(item => item.href));
```
