### ISSUE TITLE
[REGRESSION] recordVideo not working anymore after update

### ISSUE THREAD

**Issue by vogler** [microsoft/playwright#27086]
### System info
- Playwright Version: [v1.38.0]
- Operating System: macOS 13.5.1
- Browser: Firefox
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Minimal example following https://playwright.dev/docs/videos:

```js
import { firefox } from 'playwright-firefox';
import { datetime } from './util.js';
import { cfg } from './config.js';

const options = {
  headless: cfg.headless,
  viewport: { width: cfg.width, height: cfg.height },
  recordVideo: cfg.record ? { dir: 'data/record/', size: { width: cfg.width, height: cfg.height } } : undefined, // will record a .webm video for each page navigated; without size, video would be scaled down to fit 800x800
  recordHar: cfg.record ? { path: `data/record/eg-${datetime()}.har` } : undefined, // will record a HAR file with network requests and responses; can be imported in Chrome devtools
};
console.log(options);
const context = await firefox.launchPersistentContext(cfg.dir.browser, options);

const page = context.pages().length ? context.pages()[0] : await context.newPage(); // should always exist
await page.goto('https://playwright.dev');
await page.waitForTimeout(3000);
await context.close();
```

**Steps**

```console
SHOW=1 node recordVideo.js
{
  headless: false,
  viewport: { width: 1920, height: 1080 },
  recordVideo: { dir: 'data/record/', size: { width: 1920, height: 1080 } },
  recordHar: { path: 'data/record/eg-2023-09-14 17:23:32.955.har' }
}
```

**Expected**

Generate both a .har and .webm file in `data/record`.

**Actual**

Only a .har file is saved:
![image](https://github.com/microsoft/playwright/assets/493741/5d0ddcc2-3cfe-47f5-a485-ae75edc5a612)

As you can see, this still worked on Aug 23rd.
I didn't change any of my code.

Playwright update ^1.31.0  →  ^1.37.1 seems to have broken it: https://github.com/vogler/free-games-claimer/commit/6a7cca31a4b87ecbe08387c1c5da966cc163056d

**Comment by dgozman** [comment]
I can repro. This regressed between v1.35 and v1.36. Works in Chromium and WebKit, but not Firefox.
