### ISSUE TITLE
[Feature] Set open to never for HTML report when using merge-reports

### ISSUE THREAD

**Issue by DustinBest** [microsoft/playwright#27090]
Is there any way to set the config field {open: 'never'} for merge-reports.  Right now when merging reports, if there is a failed test, it opens the report which when running in CI can be a problem. I tried adding the -c playwright.config.ts that I have the HTML report setup in but doesn't seem to pick up on the different config options assigned to that. 

Command: npx playwright merge-reports --reporter html ./playwright/test-results/blob-reports -c playwright.config.ts

Results: opens HTML report when there is a failed test

Desired: set the config to never open on failed test

HTML Config: ['html', { open: 'never', outputFolder: './playwright/test-results/html' }]

**Comment by pavelfeldman** [comment]
You can pass separate config to the merger and specify all the options. See https://playwright.dev/docs/test-sharding#merge-reports-cli.

**Comment by pavelfeldman** [comment]
Try passing -c option with the value before the path to the blob reports.

**Comment by DustinBest** [comment]
> You can pass separate config to the merger and specify all the options. See https://playwright.dev/docs/test-sharding#merge-reports-cli.

I have tried this command in a variety of orders, however, each has the same result.  Even with config specifying open: 'never' it will open the report when there is a failed test.

**Comment by pavelfeldman** [comment]
Your command line should be:
```sh
npx playwright merge-reports -c playwright.config.ts ./playwright/test-results/blob-reports 
```

**Comment by DustinBest** [comment]
> Your command line should be:
> 
> ```shell
> npx playwright merge-reports -c playwright.config.ts ./playwright/test-results/blob-reports 
> ```

Okay removing the --reporter html seems to solve it. I was under the impression after reading the documentation that I needed that in the command line to define the report type being created from the blob reports.

**Comment by jared-christensen** [comment]
I ran into the same issue with `--reporter HTML` starting a server and causing problems in CI. It would be great if there was an option to merge reports without starting the server, so we wouldn’t have to create a config file just to work around it.

**Comment by TusharAnandTR** [comment]
This is my reporter in playwright.config.ts file:

```
reporter: [
    ['list'],
    ['allure-playwright',
      {
        detail: false,
        outputFolder: './.allure-report-data/allure-results',
        suiteTitle: false,
        open: 'never',
      },
    ],
    ['html',
      {
        open: 'never',
        outputFolder: './.html-report-data'
      }
    ],
    ['blob', 
      {
        open: 'never', 
        outputDir: './.session-blob-reports' 
      }
    ],
    ['./reporter.config.ts',
      {
        open: 'never',
        customOption: process.env.ENV
      }
    ]
  ],
```

Need to have all of these.
However, I only am merging the blob file to HTML report.

Having a separate merge.config.ts really helps, but merge is failing when config is pointed to playwright.config.ts

I wanted to not to have merge.config.ts file as it only has 3 lines of script. Any suggestions?

**merge.config.ts:**
```
export default {
    reporter: [['html', { open: 'never' }]],
  };
```
