### ISSUE TITLE
"Control+any key" step in the test does not work in the headless mode

### ISSUE THREAD

**Issue by DhanashriChavan125** [microsoft/playwright#27108]
System info
Playwright Version: [1.34.3]
Operating System: [Windows]
Browser: [Chromium]

Issue:
**await keyboard.press(keyEvents)** function is not working in headless browser.
Tried with ctrl+c, ctrl+v, ctrl+d, ctrl+f options, but none of them is working in hedless mode

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by DhanashriChavan125** [comment]
In my code i am performing copy and paste operation using below code line
await keyboard.press("Control+c");
await keyboard.press("Control+v");

this code is working fine headed browser, but same code is not working in headless.

also i tried with 
**await keyboard.press("Control+f");** for find operation.
this code is working fine headed browser, but same code is not working in headless.

**Comment by aslushnikov** [comment]
@DhanashriChavan125  the `control-c` and `control-v` are supposed to work - we even have tests for these. So please, file a new issue with a short code snippet that illustrates that these shortcuts don't work!

The `control-f` shortcut that triggers browser text search is not part of the web platform, so there are no guarantees that it will work somewhere.
