### ISSUE TITLE
[QUESTION] How to use Playwright Extension for VSCode with custom configs

### ISSUE THREAD

**Issue by KrzysztofVivun** [microsoft/playwright#27109]
Hi, 
I have base config file `playwright.config.ts` and some other files extending it for example `dev.config.ts`. When im trying to run tests using PW Extension in VSCode it runs based on `playwright.config.ts`. From cli i can pass config parameter using `-c config/dev.config.ts` and it works. But i would love to have a possibility to run this config from extension so i can easily debug tests, grab locators etc. Is it possible? Or maybe there is another way to set things up. The reason behind current approach is to have possibility to run projects against different environments. Adding projects for them in one file will not work well as there are many projects with different configs and all have to be run on couple of environments.

**Comment by dgozman** [comment]
@KrzysztofVivun VSCode extension recognizes configs that match the following glob: `**/*playwright*.config.{ts,js,mjs}`, so you should rename `dev.config.ts` into `dev.playwright.config.ts`. Let me know whether that helps.

**Comment by KrzysztofVivun** [comment]
Hi @dgozman . Thanks for prompt reply. Yes it is working well. To add for future lurkers, if there is more than one additional config, user can select run profile in Tests Extension using Down Arrow 
![image](https://github.com/microsoft/playwright/assets/111743088/de580d87-49cb-45c9-bf68-8d86eadacf9a)
and selecting correct one.
