### ISSUE TITLE
[Feature] support `excludeArgs` in LaunchOptions to define patterns to exclude specific preset arguments

### ISSUE THREAD

**Issue by link89** [microsoft/playwright#27104]
I find that playwright will add a bunch of preset arguments when starting a browser. For example: https://github.com/microsoft/playwright/blob/699e790f69b60adc5494195e9199914b42291666/packages/playwright-core/src/server/chromium/chromium.ts#L291-L349

But there are cases that users may want to gain more control of setting arguments. For example, `--disable-extensions` should not be set if user want to test websites with specific extensions. 

Now the LaunchOptions has an `args`  option that allow user to append arguments list. I think we need to have another options, `excludeArgs`, to exlucde options they don't want.  It should allow user to match the options they don't want with glob patterns. 

For example,

```typescript

const launchOpts = {
  channel: 'msedge',
  excludeArgs: [
    "--disable-*",
    "--enable-automation",
  ],
  args: [
   "--disable-background-timer-throttling",
  ],
}
```
which will exclude all the options that match the pattern `--disable-*` and `--enable-automation`.

Related issues:
* https://stackoverflow.com/questions/77104921/how-to-customize-msedges-command-line-options-with-playwright-python

**Comment by dgozman** [comment]
@link89 There is already an [`ignoreDefaultArgs` option](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-ignore-default-args) that does strict comparison. Does that work for you?

```js
await chromium.launch({ ignoreDefaultArgs: ['--disable-extensions', '--enable-automation'] })
```
