### ISSUE TITLE
[BUG]? 'npx playwright install' fails to recognize macOS inside docker container

### ISSUE THREAD

**Issue by Az8th** [microsoft/playwright#27118]
Hello,

I ran into what seems to be a misbehaviour from npx playwright install.
Given I have to do tests on multiple OS in a CI, I use the sickcodes/docker-osx:ventura macOS docker image.
But while installing dependancies, I got an error reporting that the distribution is not officially supported, despite the documentation says otherwise.

When trying to run tests anyway, I get a message listing the missing dependances.

Is this expected behaviour or a bug (from playwright or the docker image itself) ?

### System info
- Playwright Version: latest (1.38)
- Operating System: macOS 13 (Ventura)
- Browser: All
- Other info: Docker image: sickcodes/docker-osx:ventura

### Source code
**Config file**
Default example
**Test file**
Default example

**Steps**
using latest sickcodes/docker-osx:ventura
install node & playwright
`npx ci`
`npx playwright install --with-deps`

**Expected**
Browsers and their respectives dependances are installed using brew

**Actual**
Getting warning for unsupported distribution and tries to install with apt-get

**Comment by dgozman** [comment]
@Az8th Unfortunately, supporting macOS docker containers is out of scope for Playwright project.
