### ISSUE TITLE
[Question] How to see better error stacktrace?

### ISSUE THREAD

**Issue by ClaudiuDan** [microsoft/playwright#27111]
I keep getting quite a few of this type of error:  `Error('net::ERR_FAILED at (...) navigating to (...), waiting until "domcontentloaded"`

Is there a way to better debug this type of errors?

**Comment by dgozman** [comment]
I'd recommend [recording a trace](https://playwright.dev/docs/trace-viewer-intro) and exploring network requests in the Network panel.

**Comment by aslushnikov** [comment]
Closing as per above. Please feel free to file a new issue if you think we can be helpful!
