### ISSUE TITLE
[BUG] Errors in Webkit-1883 Binary on Storybook 6.5

### ISSUE THREAD

**Issue by procload** [microsoft/playwright#27129]
### System info
- Playwright Version: v1.33.0
- Operating System: macOS 13.5.2
- Browser: WebKit
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

NA

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'], },
    },
  ]
});
```

**Steps**
- Install Playwright 1.33.0 and ensure the Webkit-1883 binary is downloaded.
- Run a test suite in Webkit on Mac that uses Storybook 6.5 or launch the Webkit-1883 binary and navigate to a Storybook 6.5 site

**Expected**

Tests should not time out and should run successfully in Webkit.

**Actual**

Tests time out when trying to load iFrame in Storybook 6.5 when using Webkit webkit-1883 binary. However, tests do not time out when using Webkit webkit-1908 binary.

**Screenshot of error**:
![4911271e-3d83-435c-b055-becf6e8ac8e2](https://github.com/microsoft/playwright/assets/49389/2a8648f0-1652-4a61-a882-7132de1aafeb)
![a0528d64-fcd8-4298-bfac-866cd3f6a444](https://github.com/microsoft/playwright/assets/49389/400a8b10-2f5f-4f5e-8e5b-c8bbc4b79921)

**Comment by dgozman** [comment]
@procload This is most likely a Storybook issue, but I cannot be sure without a repro that we can run locally. Could you please share a sample repository on github with all the necessary dependencies and instructions about running it?

**Comment by procload** [comment]
If you can launch `webkit-1883` you can visit a Storybook 6.5 site. Try https://web-components.fluentui.dev/?path=/docs/concepts-introduction--page

**Comment by dgozman** [comment]
@procload Playwright v1.33.0 uses `webkit-1837`, so you probably mean v1.37 which comes with `webkit-1883`? I can reproduce the issue with v1.37. However, the url above successfully loads with v1.38, so I'd recommend updating. Let me know whether that helps.

**Comment by procload** [comment]
Got it. This helps. Just a weird moment-in-time issue that arose with Storybook 6.5 and 1.37. Thanks, we can close this.
