### ISSUE TITLE
[Feature] Compatibility with `bun`

### ISSUE THREAD

**Issue by lgarron** [microsoft/playwright#27139]
https://github.com/microsoft/playwright/pull/26454#issuecomment-1685131076 states:

> Let's wait for the users to request interop with bun.

I'm a user, and I am requesting interop with `bun`! 🙋😄

I've just switched my largest project to `bun` (now that `bun` 1.0 [has been released](https://bun.sh/blog/bun-v1.0)), and everything works perfectly except running tests in Playwright.

A *lot* of packages run in `bun` without issue, but both `bun` and Playwright have difficult jobs, so it's not surprising that there would be challenges. Like `npx playwright`, Bun supports TypeScript and running tests directly — so I think it's fair to say that a developer who likes the ergonomics of either would be a good candidate for interest in the other.

https://github.com/oven-sh/bun/issues/2492 documents many folks trying to use Playwright from `bun`, although I don't understand the situation well enough to help fix it. But if there is anything Playwright can do to help be more compatible in `bun`, I'd be glad to be able to use that as soon as possible.

**Comment by mxschmitt** [comment]
As of today Bun is not Node.js compatible, a lot of things are still missing or behaving different. This is not something we can act on/can improve.

Once they are Node.js compatible and have the missing Node.js APIs implemented, we might reconsider putting a `bun` section into our docs.

**Comment by joshua-bn** [comment]
> As of today Bun is not Node.js compatible, a lot of things are still missing or behaving different. This is not something we can act on/can improve.
> 
> Once they are Node.js compatible and have the missing Node.js APIs implemented, we might reconsider putting a `bun` section into our docs.

Do you have a list of APIs that are missing for Playwright? 

There appears to be quite a bit of logic that checks Node version. That's probably a show stopper to start. Not only will it not work with bun, it doesn't appear that it will work with Deno or alternative runtimes.

**Comment by vitalics** [comment]
@joshua-bn You can use bun with the playwright. It is already described in my blog post [here](https://blog-vitaliharadkou.vercel.app/blog/10-bun-v1). Despite "hello world" run I have a few tests on my current project and Buns does not give a big performance for playwright tests, since the playwright bottleneck performance - is sending commands in your browser via Chrome remote CDP API, which executes your code.

**Comment by milosworks** [comment]
> [@joshua-bn](https://github.com/joshua-bn) You can use bun with the playwright. It is already described in my blog post [here](https://blog-vitaliharadkou.vercel.app/blog/10-bun-v1). Despite "hello world" run I have a few tests on my current project and Buns does not give a big performance for playwright tests, since the playwright bottleneck performance - is sending commands in your browser via Chrome remote CDP API, which executes your code.

For anyone also looking into this, currently when you try and run test with playwright bun will use node, if you even try to use --bun to force playwright to use buns runtime this wouldnt work.

**Comment by javi-cardenas-ke** [comment]
> As of today Bun is not Node.js compatible, a lot of things are still missing or behaving different. This is not something we can act on/can improve.
> 
> Once they are Node.js compatible and have the missing Node.js APIs implemented, we might reconsider putting a `bun` section into our docs.

From the maintainers of bun:

**If a package works in Node.js but doesn't work in Bun, we consider it a bug in Bun. Please [open an issue](https://bun.com/issues) and we'll fix it.**

https://bun.sh/docs/runtime/nodejs-apis

**Comment by MBanucu** [comment]
> For anyone also looking into this, currently when you try and run test with playwright bun will use node, if you even try to use --bun to force playwright to use buns runtime this wouldnt work.

[https://github.com/microsoft/playwright/issues/27139#issuecomment-2952858973](https://github.com/microsoft/playwright/issues/27139#issuecomment-2952858973)

playwright version 1.58 seems to work with bun 1.3.6. See also [https://github.com/MBanucu/bun-playwright-nix](https://github.com/MBanucu/bun-playwright-nix)

**Comment by mirao** [comment]
Found this note: https://bun.com/blog/bun-v1.4#playwright
BTW I'm running [CodeceptJS 4.1](https://codecept.io/) + Playwright 1.62.1, with Bun 1.4.2. Everything works well.
