### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Crismon96** [microsoft/playwright#27137]
### System info
- Playwright Version: [v1.XX]
- "@playwright/experimental-ct-react": "1.37.0",
-  "@playwright/test": "1.37.0",
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Ubuntu 20
- Browser: [All, Chromium, Firefox, WebKit]
- All
- Other info:
- Using the playwright component test feature

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Running any kind of react component tests successfully. When I add a global fixture I get:
`Error: Failed to resolve entry for package "tty". The package may have incorrect main/module/exports specified in its package.json.`
which is expected since because we use `test` from `@playwright/experimental-ct-react`. When I extend and use that `test` I get: `ReferenceError: test is not defined`

I am following the basic docs on how to use test fixtures so my fixture looks like this:

```
import { test as base } from '@playwright/experimental-ct-react';

export const test = base.extend<{ testHook: void }>({
  testHook: [
    async ({}, use) => {
      console.log('BEFORE EACH HOOK FROM FIXTURE');
      // Any code here will be run as a before each hook

      await use();

      console.log('AFTER EACH HOOK FROM FIXTURE');
      // Put any code you want run automatically after each test here
    },
    { auto: true },
  ],
});
```

I want to say that I see a huge need for something like playwright component testing and it would be so great to have it stable in the future. Is there any mistake I am making in registering the fixture? I want to execute some code in a global beforeAll, afterAll and beforeEach hook and fixtures are still the recommended approach for that I think.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
export default defineConfig({
  // TODO: Hardcode it for now into one directoy because it clashes with the unit tests.
  testDir: './app/components/tests',
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: './__snapshots__',
  /* Maximum time one test can run for. */
  timeout: 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [['html', { outputFolder: 'playwright-report-integration' }]],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,

    viewport: {
      height: 500,
      width: 500,
    },
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**

```ts
import { expect } from '@playwright/experimental-ct-react';
import Assets from '../Features/Assets/Assets';
import { IntegrationWrapper, test } from './test-utils';

test('should render Assets', async ({ mount }) => {
  const component = await mount(
    <IntegrationWrapper>
      <Assets />
    </IntegrationWrapper>,
  );

  await expect(component).toContainText('Learn React');
});

```

**Steps**
- Have running React component test
- Add a test fixture to run a global hook

**Expected**
Should work like with @playwright/test to execute the fixture.

**Actual**
Dependency error (when extending normal test) or reference error (when extending ct test). Tests dont run.

**Comment by pavelfeldman** [comment]
Sorry for dropping your request on the floor, it should have been triaged in a timely manner. Could you elaborate on what you are trying to do exactly? Do you want some code to run before and after your test? Your logging `BEFORE EACH HOOK FROM FIXTURE` is not correct, this code is not running before each hook, it runs before each test.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
