### ISSUE TITLE
[BUG] Visual Comparison Files Due to Black Line.

### ISSUE THREAD

**Issue by sirganya** [microsoft/playwright#27140]
### System info
- Playwright Version:  1.35.1
- Operating System: MacOs 13.5.1
- Browser:  Chromium
- Other info:

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";


export default defineConfig({
  testDir: "./e2e",
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  use: {
    baseURL: "http://127.0.0.1:3001",
    trace: "on-first-retry",
  },

  expect: {
    toHaveScreenshot: { animations: "disabled", omitBackground: true },
  },

  projects: [
    {
      name: "chromium",

      use: {
        ...devices["Desktop Chrome"],
        headless: true,
        launchOptions: {
          slowMo: 0,
        },
      },
    },
    {
      name: "Mobile Chrome",
      use: { ...devices["Pixel 5"] },
    },
  ],
  webServer: {
    command: "yarn start",
    url: "http://127.0.0.1:3001",
    reuseExistingServer: !process.env.CI,
  },
});

```

**Test file (self-contained)**

```js
test("FRAME-8: Image resize", async ({ page }) => {
  await page.goto("localhost:3001/tkn/test/8");
  const title = await page.getByTestId("title:0");
  await expect(title).toHaveCSS("opacity", "1");
  await expect(title).toContainText("FRAME-8");
  await page.waitForTimeout(200);
  await expect(page).toHaveScreenshot({ omitBackground: true });
});
```

**Steps**
- yarn playwright test --reporter=html

**Expected**

Images should match

**Actual**

A black line appears on either side of the page.

<img width="1097" alt="Screenshot 2023-09-17 at 12 11 45" src="https://github.com/microsoft/playwright/assets/551096/1787a11b-6f86-4d4d-8433-19ccde97f044">

<img width="1095" alt="Screenshot 2023-09-17 at 12 11 56" src="https://github.com/microsoft/playwright/assets/551096/ba522c31-1449-46c0-b60f-8b79fdfbeb7b">

The images being compared do not appear to have any differences

Actual: 

![FRAME-8-Image-resize-1-actual](https://github.com/microsoft/playwright/assets/551096/659cdd46-faf0-4f3f-b531-4e0e2ecc4b8a)

Expected: 
![FRAME-8-Image-resize-1-expected](https://github.com/microsoft/playwright/assets/551096/cf3e4135-3a60-4c8f-8b2a-180cdb93bea8)

Diff: 
![FRAME-8-Image-resize-1-diff](https://github.com/microsoft/playwright/assets/551096/fdb6114e-4937-4f1e-9f81-c2f934b0fda9)

**Comment by mxschmitt** [comment]
Can you provide a small html file which reproduces this issue? Does this also reproduce on headed?
