### ISSUE TITLE
[BUG] Docker tag "focal" not updated for arm64

### ISSUE THREAD

**Issue by pstrh** [microsoft/playwright#27149]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS 13.5]

**Steps**
Run the following command to get the playwright version from the latest focal docker image:
`docker run --rm --platform=linux/arm64 mcr.microsoft.com/playwright:focal /bin/bash -c "cat /ms-playwright/.docker-info"`

**Expected**
The docker image for tag `focal` on platform `linux/arm64` should be the same as for `linux/amd64` - which is currently 1.38.0
`docker run --rm --platform=linux/amd64 mcr.microsoft.com/playwright:focal /bin/bash -c "cat /ms-playwright/.docker-info"`
Prints:
```
{
  "driverVersion": "1.38.0",
  "dockerImageName": "mcr.microsoft.com/playwright:v1.38.0-focal"
}
```

**Actual**
The focal tag on platform `linux/arm64` is outdated - seems freezed on 1.33.0.
`docker run --rm --platform=linux/arm64 mcr.microsoft.com/playwright:focal /bin/bash -c "cat /ms-playwright/.docker-info"`
Prints:
```
{
  "driverVersion": "1.33.0",
  "dockerImageName": "mcr.microsoft.com/playwright:v1.33.0-focal"
}
```

**Comment by mxschmitt** [comment]
Most likely its cached for you, thats why its printing an old version? We strongly recommend pinning your Docker tag to match a [specific Docker version](https://playwright.dev/docs/docker).

<img width="906" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/5e37b998-9ff3-4c9f-a605-d10fbbfb245f">

**Comment by pstrh** [comment]
Aarrrggg... you're right. Thank you!
