### ISSUE TITLE
[Feature] Support `Symbol.asyncDispose` method (the `using` keyword) in addition to `close()`

### ISSUE THREAD

**Issue by dtinth** [microsoft/playwright#27141]
This allows us to write this:

```ts
await using context = await browser.newContext()
// Code
```

which is more concise than:

```ts
const context = await browser.newContext()
try {
  // Code
} finally {
  await context.close();
}
```

**Comment by mxschmitt** [comment]
There scope for this issue is to:

a) support it on all our objects which have a `close()` method.
b) Make it possible to use the using keyword inside our test runner.

If I forgot something, let us know!
