### ISSUE TITLE
[BUG]can not display trace

### ISSUE THREAD

**Issue by ldy12347** [microsoft/playwright#27144]
When I open trace, the page is blank
<img width="1908" alt="image" src="https://github.com/microsoft/playwright/assets/32159351/954d3a7d-9a02-4736-8047-4123595c1324">

**Comment by mxschmitt** [comment]
Should be fixed now. Might take 3-10 minutes to update the cache.

**Comment by ldy12347** [comment]
> Should be fixed now. Might take 3-10 minutes to update the cache.

no，It has not been open since last Friday, and there is an error on the console

**Comment by ldy12347** [comment]
> Should be fixed now. Might take 3-10 minutes to update the cache.
I don't know if the playwright changed anything? The same link could have been opened before

**Comment by mxschmitt** [comment]
You are right, I apologise! I can repro with [trace.zip](https://github.com/microsoft/playwright/files/12646369/trace.zip) after https://github.com/microsoft/playwright/pull/27095.

**Comment by abz-aleksey-qa** [comment]
Hi!

@mxschmitt 

I have the same problem with displaying the trace.
If you remove hidden from pseudo elements, then everything is displayed as it should.
(by the way, in the preview on the trace page all pages are displayed)

![image](https://github.com/microsoft/playwright/assets/71260728/f522b3ab-d33a-4b7f-9d1b-abb0a1b75f37)

![image](https://github.com/microsoft/playwright/assets/71260728/395834ab-97e2-4448-8066-b8d36efaaee1)

**Comment by mxschmitt** [comment]
@abz-aleksey-qa your issue looks different, I recommend to file separately with a reproduction.

**Comment by ldy12347** [comment]
> You are right, I apologise! I can repro with [trace.zip](https://github.com/microsoft/playwright/files/12646369/trace.zip) after #27095.
Do you have any plans to fix it? Or is there a way to fix it?
