### ISSUE TITLE
[Feature] Open Telemetry Tracing

### ISSUE THREAD

**Issue by uptickmetachu** [microsoft/playwright#27147]
It would be amazing if playwright testing could implement opentelemetry tracing.

E2E tests can be slow at times and it is valuable to find which tests are slow and/or which elements of the tests are slow.

We are currently visualising our git hub actions with OTEL tracing in grafana. Being able to trace into the our E2E tests would allow us to optimize slow tests, find flaky/slow tests/steps.

<img width="786" alt="image" src="https://github.com/microsoft/playwright-python/assets/67882333/4aaa7779-bf16-4196-b2c7-3c18e245ec7e">

**Comment by mxschmitt** [comment]
We recommend creating a custom reporter where you can get all the test and step data to create your custom analytics from: https://playwright.dev/docs/test-reporters#custom-reporters

Having this inside the Playwright project is outside of the scope for Playwright.

**Comment by bgroupe** [comment]
> We recommend creating a custom reporter where you can get all the test and step data to create your custom analytics from: https://playwright.dev/docs/test-reporters#custom-reporters
> 
> Having this inside the Playwright project is outside of the scope for Playwright.

@mxschmitt As I have the same use case I am interpreting this original question to mean to supplement existing trace functionality with OTEL SDK compatible functionality for pushing traces to observability platforms. AFAIK the reporter APIs don't offer trace data. Do you have a recommendation for how that could be achieved?
