### ISSUE TITLE
[Feature] Lazy execution of init script arguments

### ISSUE THREAD

**Issue by oeed** [microsoft/playwright#27157]
My tests involve using mock timers/lock via sinon (using the method described here: https://github.com/microsoft/playwright/issues/6347#issuecomment-1521548699) and a web page that has code running in both the top frame and an iframe. It's important that the time remains synced between these two pages and that time is monotonic across refreshes/navigation.

I am setting up the fake timer in a fixture as such (having previously loaded sinon.js):
```ts
const baseClock = createClock(0)
...
await context.addInitScript((now) => window.__clock = sinon.useFakeTimers({ now }), baseClock.now)
```

This works in setting up the fake timers, but the problem is if I refresh a page the page's timer will then initialise from 0.

What I'd ideally like is a way to pass a callback to `addInitScript` that'd get called each time the script is executed. For example: 

```ts
await context.addInitScript((now) => window.__clock = sinon.useFakeTimers({ now }), () => baseClock.now)
```

---

If this isn't possible/in the meantime, are there any alternative ways to solve this? I've tried exposing it via `context.exposeFunction`, but the exposed function is a promise (so it doesn't setup the fake clock fast enough). I've tried listening to `domcontentloaded` & `frameattached` events, but they seem to also be triggered too late.

**Comment by aslushnikov** [comment]
@oeed Can you please share a bit more details about your use case? Who's triggering page's reload, and why would you want the timer not to be 0 in this case?

**Comment by aslushnikov** [comment]
> The refresh is triggered by the test purely to cause a new view.

@oeed  Well, in this case you can also add a new `addInitScript` before reload to make sure to update the timer to a new value. Would this work?

**Comment by aslushnikov** [comment]
@oeed i see. It would work in practice, as long as you use the same method, i.e. `page.addInitScript()` followed by another one `page.addInitScript()`.

You can also add a microtask to postpone timer initializations so that the actual timestamp is always initialized before timers, regarding of their order.

**Comment by pavelfeldman** [comment]
> This works in setting up the fake timers, but the problem is if I refresh a page the page's timer will then initialise from 0.

Taking over on triaging this. This does not sound right. When I do this:

```js
  await page.addInitScript((now) => {
    (window as any).__clock = now;
    console.log(window as any);
  }, Date.now());
```

I'm getting the same __clock no matter how many frames or reloads I make. Could you elaborate on what makes your use case different?

**Comment by oeed** [comment]
Sorry I probably worded that poorly, the fake timer starts at `0` (i.e. when `addInitScript` is called `baseClock.now === 0`). Thus each time you refresh it'll go back to that original value, so it is equivalent to your example above.

**Comment by pavelfeldman** [comment]
Confused, what is your goal then?

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!

**Comment by MillerSvt** [comment]
@oeed I think my approach will help you:

```
        await page.exposeBinding('pwCurrentDate', () => new Date().valueOf());
        await page.addInitScript(async () => {
            window.clock = sinon.useFakeTimers({ // mock timers first, before bootstrap the application
                now: 0,
            });
            window.clock.setSystemTime(await pwCurrentDate()); // then set correct time
        });
```
