### ISSUE TITLE
[BUG]  --grep Command Requires Additional Space Character for Proper Functioning When Using Pipe (|) Character

### ISSUE THREAD

**Issue by Kristoffer88** [microsoft/playwright#27154]
### System info
- Playwright Version: 1.38.0
- Operating System: Windows
- Browser: All
- Other info:

Default project settings when using npm init playwright@latest

**Steps**
Use the command: npx playwright test --grep "link|title"
Observe the error or incorrect behavior
Use the command: npx playwright test --grep "link|title|empty statement"
Observe the correct behavior

**Expected**

Both commands should filter the tests correctly and execute the specified tests.

**Actual**

The first command npx playwright test --grep "link|title" does not work as expected. Adding an empty statement with a space character fixes the issue, which shouldn't be necessary.

**Comment by mxschmitt** [comment]
this is most likely related to how the Command Prompt or PowerShell escapes, see here how you can workaround it: https://playwright.dev/docs/test-annotations#tag-tests

**Comment by Kristoffer88** [comment]
Thanks. I will be taking a look at that.

**Comment by Kristoffer88** [comment]
Thanks. I will be taking a look at that.
