### ISSUE TITLE
[BUG] Race Condition: 'Save' Button Not Enabling During Automated Testing Despite Custom Wait Strategies

### ISSUE THREAD

**Issue by nasti01** [microsoft/playwright#27152]
### System info
- Playwright Version: [v1.33]
- Operating System: [macOS 13.2]
- Browser: [Chromium]

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```java
 public ProductionPage clickOnSaveButton() {
    page.waitForFunction("() => !document.querySelector('[data-test-phase-form-save]').disabled");
    page.click("[data-test-phase-form-save]");
    return this;
  }
```

**Steps**
- [Run the test]
- [Insert value in an input]
- [Save button becomes enabled]
- [Click on save button]

**Expected**

When interacting with a webpage containing input fields, I expect that when I modify any of these input fields, the 'Save' button should transition to an enabled state. The test script should wait until the 'Save' button is enabled and then perform a click action on it.

**Actual**
Despite implementing a wait mechanism, the 'Save' button remains in a disabled state and never transitions to an enabled state during test execution. Strangely, when I use the 'Thread.sleep' method, the button becomes enabled and the test proceeds as expected. Notably, this issue does not occur when interacting with the page manually; it only arises during automated testing. I've exhaustively experimented with various custom wait strategies, but none seem to activate the button. Could this behavior be indicative of browser-related flakiness?"

**Comment by aslushnikov** [comment]
@nasti01 it's hard to say what exactly is going on here. Would you mind providing us with a repro that we can run locally to actually observe the behavior?

**Comment by aslushnikov** [comment]
It looks like the discussion has stalled, so I'll close this.

If you still think we can be helpful, please do not hesitate to file a new issue. Also, feel free to ask questions on https://aka.ms/playwright/discord - the community is very active and helpful there!
