### ISSUE TITLE
[BUG] The page snapshot  in trace does not display content

### ISSUE THREAD

**Issue by jstbing** [microsoft/playwright#27150]
### System info
- Playwright Version: ^1.37.1

The page snapshot  in trace does not display content

For each test step where snapshot display is available, the page content is not displayed.
(in screenshots when hovering, the page is displayed correctly)

[example.trace.zip](https://github.com/microsoft/playwright/files/12646880/trace.zip)

trace issue
![image](https://github.com/microsoft/playwright/assets/69080688/ef4ee4cf-fccf-4e9b-82ce-2f1ea396d591)

with visibility "hidden"
![image](https://github.com/microsoft/playwright/assets/69080688/ad531d23-120f-4d8f-adac-a5061bdbb91c)

with disabled visibility "hidden"
![image](https://github.com/microsoft/playwright/assets/69080688/3ccf1c92-e889-4405-b0e5-3b0c1528d0d3)

**Comment by aslushnikov** [comment]
@jstbing in the trace you attached, I can see the snapshot properly starting from the `locator.fill` method:

<img width="1496" alt="image" src="https://github.com/microsoft/playwright/assets/746130/6dfbc46d-9585-481e-9a43-d80b31d880ff">


Isn't it the expected behavior?

**Comment by jstbing** [comment]
@aslushnikov 

Yes, this is expected behavior
But starting from the weekend, almost all traces are displayed in the same way as I described in the problem
Today I'm seeing the same problem again with hidden pseudo ::before and ::after elements 

<img width="2033" alt="image" src="https://github.com/microsoft/playwright/assets/69080688/a3740c97-f5fd-407d-b76e-d37fe906a4ed">

**Comment by aslushnikov** [comment]
@jstbing so how do I reproduce this?

**Comment by jstbing** [comment]
@aslushnikov 

I found that everything works fine only if I update playwright to version 1.38.1

Is this normal or should the updated trace viewer support older versions?

**Comment by aslushnikov** [comment]
@jstbing there was compatibility issue with trace viewer and old versions, but it was fixed. Hope it works well now! If not, please file a new issue so that we can repro & debug it. 

Thanks!
