### ISSUE TITLE
[BUG] [Dependency] Update `https-proxy-agent`

### ISSUE THREAD

**Issue by lukeed** [microsoft/playwright#2715]
**Context:**
- Playwright Version: 1.1.1
- Operating System: N/A
- Node version: N/A
- Browser: N/A
- Extra: N/A

**Describe the bug**

Looking at `playwright`'s [dependency graph](https://npm.anvaka.com/#!/view/2d/playwright) I noticed that it's relying on an outdated `https-proxy-agent` version. Because of this, there are two versions of `debug` installed per every install of `playwright`. Luckily, it's your only duplicate.

While seemingly minor, you're still relying on outdated deps.

`https-proxy-agent@5.x` exists – it still supports Node >= 10 and [shares your `debug` link](https://npm.anvaka.com/#!/view/2d/https-proxy-agent/5.0.0)

**Comment by pavelfeldman** [comment]
@lukeed: thanks! would you be open to sending a PR that fixes it?

**Comment by lukeed** [comment]
Sure 👍

**Comment by aslushnikov** [comment]
Closed by #2777.
