### ISSUE TITLE
[Question] How to get title from description in test? 

### ISSUE THREAD

**Issue by petarku** [microsoft/playwright#27151]
Is it possible to get title of group of tests "describeTitle"  
test.describe.serial('describeTitle', () => {

I know i can use testInfo.title for individual test titles , but i was wondering if i can read somewhere describe title during runtime ? 

thanks in advance

**Comment by mxschmitt** [comment]
[`testInfo.titlePath()`](https://playwright.dev/docs/api/class-testcase#test-case-title-path) gives you that.

**Comment by petarku** [comment]
thanks @mxschmitt , closing this
