### ISSUE TITLE
[Feature]Page Object Design to handle dynamic locators for cross browser testing or internationalization testing like WebdriverIO

### ISSUE THREAD

**Issue by krishna01012002** [microsoft/playwright#27178]
Constructor approach might work for static locators and in situations where developers don't add identifiers, for example dynamic lists or tables or dropdown values, such cases I believe we should follow the right page object model like selenium, webdriverio and cypress

Ref: https://webdriver.io/docs/pageobjects/

In some cases, we write locators based on input (random data or API calls). For example, capturing amount values based on input

Even though text and currencies keep changing during internationalization testing, we can still keep it in the constructor?

Another example, since you say we can use locators in constructors? At my opinion we should not think just happy paths while designing page objects.

What if we don't have a common locator for cross browser testing, so I want to differentiate based on the name of the browser? Can the constructor be suggested in this case?

A locator differs for iPhone, iPad, Android phone, and tablet in the case of mobile automation

My Sample Code:
public emailBypassWarningText(emailBypassMessage: string): WebdriverIO.Element {
if (deviceName.includes("iPhone") || deviceName.includes("iPad")) {
return $(//XCUIElementTypeStaticText[@name='${emailBypassMessage}']);
} else if (deviceName.startsWith("phone") || deviceName.startsWith("tablet")) {
return $(android=new UiSelector().text("Email provided cannot be verified, you may bypass"). className("android.widget.TextView"));
}
}

I would appreciate if you could provide examples of internationalization testing or dynamic locator page objects

A constructor is a special method in object-oriented programming (OOP) that is responsible for initializing and setting up the initial state of an object when it is created. Constructors are typically defined within a class and are automatically called when an instance of that class is instantiated or created.

**Comment by MindaugasMateika** [comment]
```
import { expect, type Locator, type Page } from '@playwright/test'

export class PlaywrightDevPage {
  readonly page: Page
  readonly isMobile: boolean
  readonly someLocator: (text: string) => Locator
  readonly anotherLocator: Locator

  constructor(page: Page, isMobile: boolean) {
    this.page = page
    this.isMobile = isMobile
    // dynamic locator based on variable
    this.someLocator = (text: string) => page.getByText(text)
    // locator based on isMobile option/fixture https://playwright.dev/docs/api/class-testoptions#test-options-is-mobile
    this.anotherLocator = this.isMobile
      ? page.locator('some-mobile-locator')
      : page.locator('some-desktop-locator')
  }

  async doSmth() {
    // get text from API or i18n to create locator dynamically and click it
    await this.someLocator('whatever').click()
  }
}
```

Pretty much whatever you can code in node, you can do in Playwright. There is also i18n library https://www.npmjs.com/package/playwright-i18next-fixture. It all depends on implementation and where you'll be getting your texts or whatever else you need in your tests.

**Comment by MindaugasMateika** [comment]
If you think that WebdriverIO helps with testing internatiolisation in a way that Playwright doesn't then I would suggest to update your feature request with the functionality that you're missing. Your current example does not show that.

**Comment by krishna01012002** [comment]
Thanks @MindaugasMateika    The issue here is organizing page locators within the constructor rather than creating separate pages 

Even with playwight we can organize page objects well,  like https://webdriver.io/docs/pageobjects/

 Kindly suggest, Is there  anything wrong if we organize page objects like below , I tested below code working fine with PlaywrightJs

export class LoginPageObject {
constructor(page){
this.page = page;
}

get userSignInButton() {
    return this.page.locator("//a[@title='Sign in']");
}

get userNameInput() {
    return this.page.locator('#user_email_login');
}

get submitButton(){
   return this.page.locator('#user_submit');
}

get passwordInput() {
    return this.page.locator('#user_password');
}
}

**Comment by MindaugasMateika** [comment]
There's nothing wrong but unusual. If you want a cleaner look you could do this in Typescript and define locators at top of the class while leaving constructor empty.

```
import { expect, type Page } from '@playwright/test'

export default class ClassName {
  readonly someLocator = this.page.locator('')
  readonly anotherLocator = this.page.locator('')

  constructor(readonly page: Page) {}

  async doSmth() {
    await this.someLocator.click()
  }
}
```

**Comment by krishna01012002** [comment]
Thank you @MindaugasMateika
