### ISSUE TITLE
[BUG] "Show trace viewer" broken in WSL2

### ISSUE THREAD

**Issue by pixilation** [microsoft/playwright#27172]
Context:

Playwright Version: 1.38
Operating System: Windows + WSL2
Node.js version: 16.16.0
Visual Studio Code version: 1.82.2
Playwright for VSCode extension version: 1.0.15 (and 1.0.14)
Browser: Chromium
Extra: [any specific details about your environment]

**Describe the bug**

The "Show trace viewer" feature is broken. When running a test it attempts to start the trace viewer, but it just opens a browser tab at `0.0.0.0:<random-port>` that has "ERR_ADDRESS_INVALID".

This appears to have worked in Playwright for VSCode 1.0.13 and appears to have been broken in 1.0.14.

I tried editing the extension (v1.0.15 tag) and this change fixed it for me. It appears the `if` condition is the culprit.
![image](https://github.com/microsoft/playwright/assets/3043077/ebb6effc-fd38-43e7-a256-83b9b8550ae1)

I'll try going back to v1.0.13 as a workaround. Failing that I can run my modified development version of the extension.

**Comment by fabioParis75** [comment]
Same issue for me.
We should use localhost instead of 0.0.0.0

**Comment by mxschmitt** [comment]
This should be fixed, we still listen on `0.0.0.0` but open the browser window now on `localhost`.
