### ISSUE TITLE
[BUG] reuseBrowser/showTrace in .code-workspace overrides checkboxes

### ISSUE THREAD

**Issue by pixilation** [microsoft/playwright#27171]
**Context:**
- Playwright Version: 1.38
- Operating System: Windows + WSL2
- Node.js version: 16.16.0
- Visual Studio Code version: 1.82.2
- Playwright for VSCode extension version: 1.0.15
- Browser: Chromium
- Extra: [any specific details about your environment]

**Code Snippet**

Code like this broke my "Show browser" button.

my-project.code-workspace
```json
{
	"settings": {
		"playwright.env": {
			"some-varaible": "hi"
		},
		"playwright.reuseBrowser": false,
		"playwright.showTrace": true
	}
}
```

**Describe the bug**

The "Show browser" and "Show trace viewer" buttons cease to be mutually exclusive. They can both be enabled together.
They appear to be stuck in the state defined by the VSCode <my-project>.code-workspace file.

I noticed that the "Show browser" button wasn't working and eventually figured out that it had been set to false in my .code-workspace file and this was overriding the checkbox state.

These .code-workspace settings are inserted by VSCode when editing the playwright settings for the workspace.
![image](https://github.com/microsoft/playwright/assets/3043077/ff65768f-2f57-4936-9e3c-7fa708153020)

**Comment by pixilation** [comment]
These .code.workspace settings are inserted by VSCode when editing the playwright settings for the workspace.
![image](https://github.com/microsoft/playwright/assets/3043077/97cc308c-8ad2-4392-ad6e-599155efc6cc)

**Comment by yury-s** [comment]
It looks like the workspace settings file takes precedence over the VS Code UI settings.
