### ISSUE TITLE
[QUESTION] Environment Variables are not loading using PW Extension in VSCode?

### ISSUE THREAD

**Issue by KrzysztofVivun** [microsoft/playwright#27177]
Hi,
This question is somehow related to [this](https://github.com/microsoft/playwright/issues/27109) one. I have different configs in this structure:

```base.playwright.config.ts
   |
   --> dev.playwright.config.ts
   |
   --> staging.playwright.config.ts
```

Inside those configs (excluding base one, which contains common settings) im trying to load ENV Variables for username and password:

```const devConfig = {
    ...base,
    setupEnvVars() {
        process.env['TARGET_ENV'] = 'dev';
        process.env['API_URL'] = 'https://xxx.com';
    },
    use: {
        ...base.use,
        baseURL: 'https://xxx.com',
        httpCredentials: {
            username: process.env.PW_USERNAME,
            password: process.env.PW_PASSWORD
        },
    }
};
devConfig.setupEnvVars();
export default devConfig;
```

Then im trying to run tests from extension using given profile. 
What is happening is that `base` config is used, but `httpCredentials` are undefined. 
When i change credentials part to:
```        httpCredentials: {
            username: process.env.PW_USERNAME? 'one' : 'two',
            password: process.env.PW_PASSWORD? 'three' : 'four'
        },
```

Im getting 'two' and 'four' respectively. It seems that it is evaluated but somehow the env vars are not taken form system.

But when im running tests using CLI or CLI with `--ui` option and providing config with `-c` option, it works fine. What am doing wrong? Or there is some difference with execution order?

**Comment by mxschmitt** [comment]
The VSCode extension does not know which environments you want to use. So we recommend using .env files for https://playwright.dev/docs/test-parameterize#env-files loading env variables.

**Comment by KrzysztofVivun** [comment]
Ok, but i just assumed that process.env will grab values from system ENV variables. (they are set there). So using .env files is only option, right?

**Comment by KrzysztofVivun** [comment]
Ok it seems that its working, i forgot to add `export` in front of my new envs... Shame on me. Thanks for support!

**Comment by aslushnikov** [comment]
@KrzysztofVivun

It does look like your `devConfig.setupEnvVars();` call is **after** you use the env variables in the `use` block. You should switch it around, calling the function first, and then using the env variables.

**Comment by KrzysztofVivun** [comment]
Thanks @aslushnikov but it is working, it looks like the issue was between the chair and the monitor.
