### ISSUE TITLE
[BUG] Typing newline breaks script

### ISSUE THREAD

**Issue by thebuchanan3** [microsoft/playwright#27174]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [Ubuntu 20.04]
- Browser: [Chromium]
- Other info:

### Source code

```python
from playwright.async_api import async_playwright

async with async_playwright() as playwright:
    browser = await playwright.chromium.launch()
    page = await browser.new_page()
    await page.goto("https://duckduckgo.com/", wait_until="domcontentloaded")
    loc = page.locator("//input[@id='searchbox_input']")
    await loc.type("playwright\npython")  # newline in input
    await loc.press("Enter")
    await page.wait_for_load_state("networkidle")

```

**Steps**
- Run the script with an input text containing a newline (`playwright\npython`)

**Expected**

- Script exits without error

**Actual**

- Input is truncated to anything before the newline
- Input is sent (`loc.press("Enter")`), but playwright times out waiting for the previous locator again as if the script started from the beginning

```
pw:api navigating to "https://duckduckgo.com/", waiting until "domcontentloaded" +0ms
  pw:api   "commit" event fired +562ms
  pw:api   navigated to "https://duckduckgo.com/" +0ms
  pw:api   navigated to "https://duckduckgo.com/" +1s
  pw:api   navigated to "https://duckduckgo.com/" +1ms
  pw:api   "domcontentloaded" event fired +0ms
  pw:api waiting for locator("xpath=//input[@id='searchbox_input']") +3ms
  pw:api   locator resolved to <input name="q" value="" type="text" required="" minlen…/> +49ms
  pw:api elementHandle.type("playwright
  pw:api python") +1ms
  pw:api   "commit" event fired +345ms
  pw:api   navigated to "https://duckduckgo.com/?t=h_&q=playwright" +0ms
  pw:api   navigated to "https://duckduckgo.com/?t=h_&q=playwright" +0ms
  pw:api waiting for locator("xpath=//input[@id='searchbox_input']") +3ms
  pw:api   navigated to "https://duckduckgo.com/?t=h_&q=playwright" +502ms
  pw:api   "domcontentloaded" event fired +93ms
  pw:api   navigated to "https://duckduckgo.com/post3.html" +13ms
  pw:api   "load" event fired +225ms
  pw:api   navigated to "https://duckduckgo.com/?t=h_&q=playwright" +6ms
  pw:api   navigated to "https://duckduckgo.com/?t=h_&q=playwright&ia=web" +10ms
  pw:api   "networkidle" event fired +736ms

...

playwright._impl._api_types.TimeoutError: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for locator("xpath=//input[@id='searchbox_input']")
============================================================
```

-> the script works as expected with text not containing a newline

**Comment by aslushnikov** [comment]
@thebuchanan3 first of all, why do you use "type" instead of "fill"? The [`locator.type`](https://playwright.dev/python/docs/api/class-locator#locator-type) is deprecated, see docs: https://playwright.dev/python/docs/api/class-locator#locator-type

Secondly, i tried to repro this in node.js, but it worked as expected for me. Could it be location-dependent?

```ts
// test.spec.ts
import { test, expect } from "./fixtures"

test('should work', async ({ page }) => {
  await page.goto("https://duckduckgo.com/");
  const loc = page.locator("//input[@id='searchbox_input']");
  await loc.type("playwright\npython");
  await loc.press("Enter");
});
```

**Comment by thebuchanan3** [comment]
> @thebuchanan3 first of all, why do you use "type" instead of "fill"? The [`locator.type`](https://playwright.dev/python/docs/api/class-locator#locator-type) is deprecated, see docs: https://playwright.dev/python/docs/api/class-locator#locator-type
> 
> Secondly, i tried to repro this in node.js, but it worked as expected for me. Could it be location-dependent?
> 
> ```ts
> // test.spec.ts
> import { test, expect } from "./fixtures"
> 
> test('should work', async ({ page }) => {
>   await page.goto("https://duckduckgo.com/");
>   const loc = page.locator("//input[@id='searchbox_input']");
>   await loc.type("playwright\npython");
>   await loc.press("Enter");
> });
> ```

because I did not know, thanks for hint :+1:

**Comment by aslushnikov** [comment]
Does it work reliably for you with the `locator.fill`?

**Comment by aslushnikov** [comment]
Closing this then!
