### ISSUE TITLE
[REGRESSION]: JSON report no longer includes total run time

### ISSUE THREAD

**Issue by daun** [microsoft/playwright#27183]
**Context:**

- GOOD Playwright Version: 1.37.1
- BAD Playwright Version: 1.38.0
- Operating System: Linux, Mac, GitHub Actions

**Code Snippet**

```javascript
import { defineConfig, devices } from '@playwright/test'

export default defineConfig({
  reporter: 'json'
})

```

**Describe the bug**

Before `1.38.0`, the JSON report would include the total run time under `config.metadata.totalTime`. It's now empty, unfortunately. This was useful for [creating custom PR comments inside GitHub Actions](https://github.com/daun/playwright-report-summary).

**Comment by aslushnikov** [comment]
@daun sorry for the inconvenience!

As a workaround, you can iterate over tests in the JSON report, pick the smallest start time as the start time, and the latest `startTime + duration` for the end time. This will yield the same result.

**Comment by daun** [comment]
@aslushnikov Thanks for the workaround! I'll try that out.
