### ISSUE TITLE
Bug/Question - controlling test order?

### ISSUE THREAD

**Issue by dmcweeney** [microsoft/playwright#27185]
### System info
- Playwright Version: [v1.38]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

**Expected**

In the documentation [here](https://playwright.dev/docs/next/test-parallel#control-test-order) it says - Playwright Test runs tests from **a single file in the order of declaration**, unless you parallelize tests in a single file.

Also first paragraph [here](https://playwright.dev/docs/test-parallel) it says - By default, test files are run in parallel. **Tests in a single file are run in order**, in the same worker process

**Actual**

However when I run the tests in the runner using headed mode the tests in the single file are ran in parallel. The only way I could get tests to run in a single file in the order of declaration is to explicitly define the test as serial as per the docs [here](https://playwright.dev/docs/test-parallel#serial-mode). 

Is this a documentation bug or an actual bug?

**Comment by aslushnikov** [comment]
@dmcweeney you might have [`fullyParallel`](https://playwright.dev/docs/api/class-testproject#test-project-fully-parallel) set in your config; turning it off will make playwright to run tests consecutively on a file-per-file basis.

Does it help?

**Comment by dmcweeney** [comment]
@aslushnikov yes it is turned on in the config - but that is what I want - all tests to run in parallel by default. 
I guess the docs sections above could have the clarification added.

**Comment by aslushnikov** [comment]
I'm happy it works! 

I'm not sure what docs section can be updated, but please do not hesitate to file a PR if you think some wording could be improved!
