### ISSUE TITLE
[BUG]Screenshots for failed tests

### ISSUE THREAD

**Issue by n6ly** [microsoft/playwright#27186]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit, Microsoft Edge]
- Other info:

### Source code

- [ yes] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: process.env.CI ? process.env.testEnv : "https://www.startpage.com",
    baseURL: process.env.baseURL,
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry", 
    /* Screenshot on failure. See https://playwright.dev/docs/screenshots */
    screenshot: "only-on-failure",
  }
```

**Steps**
- [Run the test]
- [If irrelevant screenshots do not appear, run again until it shows]

**Expected**
When Playwright test runs fail, the report should only show the relevant screenshot.
<img width="661" alt="Screen Shot 2023-09-19 at 1 51 42 PM" src="https://github.com/microsoft/playwright/assets/144157865/1de5a87d-2d32-454e-8c0c-2090bfd138e2">

**Actual**
When Playwright test runs fail, the report for a specific test on the "Run" tab contains a lot of screenshots that aren't relevant to the particular test. 
<img width="420" alt="Screen Shot 2023-09-19 at 1 53 57 PM" src="https://github.com/microsoft/playwright/assets/144157865/a17f6a37-8872-4348-868c-3dad840f6c93">
<img width="437" alt="Screen Shot 2023-09-19 at 1 54 07 PM" src="https://github.com/microsoft/playwright/assets/144157865/86851e78-5053-47a5-b59e-e0709485beb0">

**Comment by aslushnikov** [comment]
@n6ly do you have multiple pages open during the test? Is there a repro you can share with us?

I tried the following and it worked just fine for me:

```ts
// playwright.config.ts
import { defineConfig } from '@playwright/test';

export default defineConfig({
  reporter: 'html',
  use: {
    screenshot: "only-on-failure",
  },
});
```

```ts
// test.spec.ts
import { test, expect } from '@playwright/test';

test('should work', async ({ page }) => {
  await page.goto('https://example.com');
  expect(1).toBe(2);
});
```

Which yields a perfect HTML report with a single screenshot.

**Comment by n6ly** [comment]
@aslushnikov Thanks for looking at it! The repo is private, so unfortunately I'm unable to share them - but your reply reminds me that if we need to force close the page every test finish then maybe that's the reason since if there are other tests failing but the page isn't closed properly, when a new test fails and takes a screenshot, the old page might be included? I will change it to test this and post the results here.

If you have any other idea, please let me know. Thanks!

**Comment by aslushnikov** [comment]
@n6ly I'll have to close this then since I have no more ideas, and there's not much we can do without a repro.

If you do think we would be helpful to you, please do not hesitate to file a new issue!
