### ISSUE TITLE
[Question] Intercepting multiple requests

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#27194]
So I have a scenario, and im not sure if/how playwright can handle it.

Essentially I have a "report" page with multiple sections/cards that I am testing against. Each card is a separate request (there is usually around 7-8 of them).

the kicker is the request is to the same URL (a POST request fwiw) however the payload is slightly different (based on the payload to the URL endpoint I receive a different data back).

Since there are multiple pages that use this endpoint and multiple reports/data to handle, mocking the response makes the most sense since trying to keep data/state the same to check would be difficult.

That being said, how can I intercept/mock a request if I have multiple requests happening that all point to the same request URL/endpoint?

Would it have to happen one at a time? Is this even possible? (Or would it come in as a request array?). Curious how to handle this in this situation.

Thanks!

**Comment by msmith1114** [comment]
Is it maybe possible in this case to set up multiple route listeners? 

In my case the differentiator between the different requests is in the payload that's sent. So lets pretend the page sends out 6 requests (not in order necessarily, as they come in a random order as they finish) I could do something like:

`await page.route('/api/**', route => {
  if (route.request().postData().includes('some-report-id-1'))
    route.fulfill({ body: 'mocked-data' });
  else
    route.continue();
});`

`await page.route('/api/**', route => {
  if (route.request().postData().includes('some-report-id-2'))
    route.fulfill({ body: 'mocked-data-2' });
  else
    route.continue();
});`

etc...

Im not sure if that will work though, and it feels super ugly to do.

**Comment by aslushnikov** [comment]
@msmith1114 you can actually just set up a single route handler that does the mocking based on the `postData()` value.

```ts
await page.route('/api/**', route => {
  if (route.request().postData().includes('some-report-id-1')) {
    route.fulfill({ body: 'mocked-data' });
  } else if (route.request().postData().includes('some-report-id-2')) {
    route.fulfill({ body: 'mocked-data-2' });
  } else {
    route.continue();
  }
});
```

Hope this helps!

**Comment by msmith1114** [comment]
> @msmith1114 you can actually just set up a single route handler that does the mocking based on the `postData()` value.
> 
> ```ts
> await page.route('/api/**', route => {
>   if (route.request().postData().includes('some-report-id-1')) {
>     route.fulfill({ body: 'mocked-data' });
>   } else if (route.request().postData().includes('some-report-id-2')) {
>     route.fulfill({ body: 'mocked-data-2' });
>   } else {
>     route.continue();
>   }
> });
> ```
> 
> Hope this helps!

Quick question: Since multiple of these requests are happening at the same time (or random times) will this "listener" (It acts as a listener I assume right?) block the other ones until whichever first request is in the queue (and decided to be fulfilled our continued/etc...)

I guess im wondering what's going to happen if request 1 comes in as is being handled in the above code meanwhile request 2 has already fired as well. Can route handle parallel requests? Or does it just queue them up?
