### ISSUE TITLE
How NOT to run afterAll on failure?

### ISSUE THREAD

**Issue by Rommel-GitHome** [microsoft/playwright#27197]
### Discussed in https://github.com/microsoft/playwright/discussions/27070

<div type='discussions-op-text'>

<sup>Originally posted by **Rommel-GitHome** September 14, 2023</sup>
Hi playwright guru,

Consider below sample test. My goal is to call `afterAll` only after the last test is run. If all tests are passed, `afterAll` is called which is fine. However, if between the tests fail, `afterAll` is still called, `test 2` for example will fail, By the way, `afterAll` will delete all the data used in the test. I understand that `afterAll` will be called after all the tests are run and on failure per worker. Is there any way that we could ignore `afterAll` on failure? It will only delete all my test data and my tests are not yet completed.

```ts
import { test } from '@playwright/test';

test.beforeEach(async ({ page }) => {
     await page.goto('http://www.somepage.com');
});
test.afterAll(async ({ page }) => {
     // Delete test data
     await helper.deleteTestData();
});

test('test 1', async ({ page }) => {
     await expect(page.getByText('Sign in')).toBeVisible();
});

test('test 2', async ({ page }) => {
      await expect(page.getByText('Sign in')).toBeHidden();
});

test('final test', async ({ page }) => {
      await expect(page.getByText('Sign in')).toBeVisible();
});
```
If this is not possible, is there any way to detect the last test currently being executed? I could use this condition in the `afterAll` hook.

Thank you for your help.</div>

**Comment by aslushnikov** [comment]
Hey @Rommel-GitHome,

You can (ab)use project dependencies for this: the dependent project will only run if the previous project finished successfully. Would this work?

**Comment by Rommel-GitHome** [comment]
@aslushnikov, thank you for your comment.

Sorry, I don't totally get you. Am I going to set this up in the playwright.config? Can I also do this within a single test file? How? Can you please provide me with sample snippet?

The above test is just 1 of the many modules we have. And each test module should have a clean up of test data every after test.

**Comment by t0r0X** [comment]
@Rommel-GitHome You could try the "stone age" method... ;-) By using [test.afterEach()](https://playwright.dev/docs/api/class-test#test-after-each) to set a flag queried in `test.afterAll()`, and `test.info().title` to retrieve the failing title, all your requirements should be fulfiled.

Disclaimer: I'm a Typescript n00b, code might not run.

E.g.:

```typescript
import { test } from '@playwright/test';

let allTestsOk = true;

test.beforeEach(async ({ page }) => {
     await page.goto('http://www.somepage.com');
});

test.afterEach(async ({ page }) => {
     if (test.info().status !== test.info().expectedStatus) {
          allTestsOk = false;
          console.log('Test failed: ' + test.info().title);
     }
});

test.afterAll(async ({ page }) => {
     // Delete test data
     if (allTestsOk) {
          await helper.deleteTestData();
     }
});

test('test 1', async ({ page }) => {
     await expect(page.getByText('Sign in')).toBeVisible();
});

// .... Tests
```
