### ISSUE TITLE
[BUG] Authentication via API is returning empty storagestate

### ISSUE THREAD

**Issue by jevarghe** [microsoft/playwright#27199]
### System info
- Playwright Version: [v1.28]
- Operating System: [All]
- Browser: [All]
- API Request

### Source code/Test

```ts
import { test } from "@playwright/test";
const loginpayLoad = {
  DisplayName: "testuser@example.com",
  Password: "TestPassword",
};
const header = {
  "ocp-apim-subscription-key": "value",
};

test("should be able to Login Via API and save storagestate", async ({ request }) => {
  let response;

  await test.step("Post request with JSON data", async () => {
    response = await request.post(
      "https://api-endpoint/login",
      {
        headers: header,
        data: loginpayLoad,
      }
    );
    await request.storageState({ path: "storagestate.json" });
    console.log(await response.json());
  });
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

Tried to check multiple forums and not many answers in the context of API authentication

Expecting to use this test in a setup project which will be dependencies for other projects.
Unfortunately, the test is not producing the storage state via API

Expectation : Storage state is retrieved and saved

**Actual**

Empty Storage State with the following content

{
  "cookies": [],
  "origins": []
}

**Comment by jevarghe** [comment]
To add, the post request is success (200) with valid response body. However, the sessionstorage is empty

**Comment by yury-s** [comment]
It looks like the server does not set any cookies in the response. Try recording [a trace ](https://playwright.dev/docs/trace-viewer-intro) and see if the response actually contains a set-cookie header.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue with a repro if it doesn't work and you believe this is a bug in playwright.
