### ISSUE TITLE
[BUG] scrollIntoViewIfNeeded doesn't work on an iframe

### ISSUE THREAD

**Issue by gersanco** [microsoft/playwright#27196]
### System info
- Playwright Version: v1.38.0
- Operating System: macOS Ventura 13.5.2
- Browser: All

I'm using the [react Paypal js](https://www.npmjs.com/package/@paypal/react-paypal-js) which sets the buttons on an iframe. When I try to click on a PayPal button which is. at the bottom of the page, I tried using 

`
frameLocator(
      'iframe[name^="__zoid__paypal_buttons"]'
    ).getByRole('link', { name: 'PayPal' }).scrollIntoViewIfNeeded()
`

But I get a timeout. Then, I tried with another element outside the iFrame and it works
`.getByRole('heading', { name: 'Payment' })
      .scrollIntoViewIfNeeded();`

**Comment by gersanco** [comment]
> @gersanco a small repro would go a long way. Could you please build a simple webpage that illustrates the issue?

Good Morning, here you are, I made it with a YT iFrame.

https://github.com/gersanco/playwright-iframe

Tell me if you need something else.

**Comment by yury-s** [comment]
The iframe does not fire `requestAnimationFrame` callbacks until it gets into the page's viewport, Playwright relies on the functionality when waiting for an element state and because of that the action fails. As a workaround, you can add 
```js
await page.locator('iframe[title="YouTube video player"]').scrollIntoViewIfNeeded();
```
to scroll the iframe into viewport before the following code:
```js
  await expect(
    page
      .frameLocator('iframe[title="YouTube video player"]')
      .getByLabel('Play', { exact: true })
  ).toBeVisible();
...
```
