### ISSUE TITLE
[Feature] JSX frameworks should create /playwright/index.tsx instead of /playwright/index.ts

### ISSUE THREAD

**Issue by sand4rt** [microsoft/playwright#27201]
The following frameworks should create a `playwright/index.tsx` instead of `playwright/index.ts`:

- [x] solid
- [x] react18
- [x] react17

I added this in https://github.com/microsoft/create-playwright/pull/75 but apparently this has been reversed?

**Comment by pavelfeldman** [comment]
@sand4rt I don't think it was, maybe it was not yet released to npm

**Comment by pavelfeldman** [comment]
@sand4rt ping!

**Comment by sand4rt** [comment]
@pavelfeldman It turned out that only react17 did not generate a `playwright/index.tsx`. Created a pull request for this: https://github.com/microsoft/create-playwright/pull/104
