### ISSUE TITLE
[Feature] Ability to clear authentication details for a test

### ISSUE THREAD

**Issue by sydlynnmiller** [microsoft/playwright#27211]
I use to be able to do this using:

` test.use({storageState: {cookies: [], origins: []}});`

This no longer works but it use to. I have a global setup that authenticates as an authorized user and saves this storage state to 'state.json'. I have one test where I would like to attempt to login as an unauthorized user and verify the application does not log in/ unauthorized message displays. For this one test I added the above code to use a separate storageState than the one used for all other tests and attempt to login as the unauthorized user. My tests is still logging me in as the authorized user (types in info for unauthorized -> clicks login -> loads application but audit log shows it is actually logging in as the previous authorized user which means my storageState for the test was never actually cleared)

Here is the code:

```ts
     test.describe('Clear cached username/password from setup ', async () => {
        test.use({storageState: {cookies: [], origins: []}});

        let page;

        test.beforeAll(async ({browser}) => {
            page = await browser.newPage();
        });
        test('Unauthorized attempt will not load the application landing page ', async () => {
            let encryptedUsername = Crypt.credentials.NotAuthorizedUserName;
            let encryptedPassword = Crypt.credentials.NotAuthorizedPassword;
            let decryptedUsername = EncryptCredentials.decryptor(encryptedUsername);
            let decryptedPassword = EncryptCredentials.decryptor(encryptedPassword);
            await page.goto(''); //base url saved in config file
            let ssoPage = new SingleSignOnPage(page);
            await ssoPage.loginBtn.click();
            await ssoPage.emailInput.fill(decryptedUsername);
            await ssoPage.nextBtn.click();
            await expect(ssoPage.passwordInput).toBeVisible();
            await ssoPage.passwordInput.fill(decryptedPassword);
            await ssoPage.signInBtn.click();
            await expect(ssoPage.approveSignInRequest).toBeVisible();
            await expect(ssoPage.doNotShowCheckbox).toBeVisible();
            await ssoPage.noBtn.click();
            await expect(ssoPage.loginBtn).toBeVisible();
            await ssoPage.loginBtn.click();
            await expect(ssoPage.unauthorizedMsg).toBeVisible();  //expect fails here because application logs in instead kicking back to login page
        });

    });
```

I tried the same scenario manually. Our application does not allow an unauthorized user to log in in any way. Are there any other ways to clear the storageState or make sure it is clear before starting my test?

**Comment by yury-s** [comment]
I cannot reproduce it with the following project: https://github.com/yury-s/bug-27211 Which Playwright version are you using? Can you share full repro so that we could run it locally?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!

**Comment by kishoreGleniseOfficial** [comment]
@sydlynnmiller , I am facing the same issue now. I too want a particular test be not using the storage state. But unfortunately the test is authorized using the storage state. In the documentation they have mentioned to use ` test.use({storageState: {cookies: [], origins: []}});`, But still I couldn't clear the storage state. Did you solve it?
