### ISSUE TITLE
[BUG/QUESTION]: teardownScope in workerMain causes fixture function below 'use' command to run in beforeAll

### ISSUE THREAD

**Issue by esokol-d2l** [microsoft/playwright#27229]
### System info
- Playwright Version: [v1.34]
- Operating System: [All]
- Browser: [All]
- Other info: I'm unsure if I've been misusing the fixtures for over a year; that's why this is more a question than anything

### Problem
When building fixture functions, we expect that the part of the function below the use command runs after the test flow. Thus, we leverage the part below use to clean the test artifacts. For instance, we create a test user in beforeAll using the fixture function, run the test, and the user gets deleted after the test due to the code below use in the fixture function.
Starting from PW version 1.34.0, this has stopped happening. Now, the order of actions is as follows: the code above the use command, then it runs the finally block here:
https://github.com/microsoft/playwright/blob/9f3c73b425051b222e53697efc6f961857cb5d24/packages/playwright/src/worker/workerMain.ts#L546
after that it performs the code below use, and then goes the test flow.

### Source code

**Config file**
I'm using the config as recommended in v1.34

**Fixture function**

```js
const test = base.test.extend({

	createUser: async({}, use) => {
		await use(async userData => {
			for (const newUser of userData) {
				const createdUser = await users.createUser(
					newUser.userName,
					newUser.firstName,
					newUser.lastName,
					newUser.roleId,
					newUser.password,
					options
				);
				userList.push(createdUser);
			}
		});

		for (let i = userList.length - 1; i >= 0; i--) {
			const userToDelete = userList[i];
			if (userToDelete.deleteUser) {
				await users.deleteUser(userToDelete, options);
				userList.splice(userList.indexOf(userToDelete), 1);
			}
		}
	},
});

```

**Test**
```js
test.describe('Test fixture', () => {
	const admin = data.adminDataGen();

	test.beforeAll(async({ createUser }) => {
		await createUser([ admin ]);
	});

	test('Verify user can open the page', async({ page, context }) => {
		const MyPage = new UIMapMyPage(page);
		await context.addCookies(admin.cookies);
		await MyPage.openMyPage();
```

**Steps**
- run the test
- view/debug the order of actions

**Expected**

It should create the test admin user, open the page and then delete the user (till v.1.33.0).

**Actual**

It creates the test admin user, deletes that user and then attempts to open the page (starting from v.1.34.0).

**Comment by yury-s** [comment]
There likely was a bug with the tear down which was fixed 1.34. `beforeAll` has its own scope and test-scoped fixtures are torn down after beforeAll runs, which is what you observe. For the following code:

```ts
// fixtures.ts
import { test as base } from '@playwright/test';

type MyFixtures = {
  createUser: (list:string[]) => Promise<void>;
};

export const test = base.extend<MyFixtures>({
  createUser: async({}, use) => {
    console.log('before createUser');
		await use(async userData => {
      console.log('in createUser ', userData);
		});
    console.log('after createUser');

	},
});
export { expect } from '@playwright/test';

// example.spec.ts
import { test, expect } from './fixtures';

test.beforeAll(async({ createUser }) => {
  await createUser([ 'admin' ]);
});

test('my test', async ({ page }) => {
  console.log('inside test');
});

```

The output will be:
```
before createUser
in createUser  [ 'admin' ]
after createUser
inside test
```

> When building fixture functions, we expect that the part of the function below the use command runs after the test flow.

If you want the fixture to be called for each test and torn down after each test you can just change beforeAll to beforeEach and it will produce this:

```
before createUser
in createUser  [ 'admin' ]
inside test
after createUser
```
Alternatively, you can mark the fixture as [auto fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures) or pass it as an explicit argument to the tests.

Will that solve your problem?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by esokol-d2l** [comment]
Sorry, forgot to respond to this.
It's so unfortunate that we've been leveraging the defective behavior for a year and a half, since the earliest PW versions. We'll need to re-build lots of test suites to update to 1.34 and higher.
Thanks for the explanations though!
