### ISSUE TITLE
[BUG] VSCode extension does not work when the config file is located in a subdirectory

### ISSUE THREAD

**Issue by mohsen1** [microsoft/playwright#27224]
**Context:**
- Playwright Version: `"@playwright/test": "^1.37.0",`
- Operating System: macOS
- Node.js version: 16
- Visual Studio Code version: 1.82
- Playwright for VSCode extension version: v1.0.15

**Code Snippet**

We run playwright by specifying the config file location via the `--config` flag. The config file is located in a subdirectory. Assume `frontend/playwright/config/index.ts`.

```
npx playwright test --config=frontend/playwright/config/index.ts
```

**Describe the bug**

The VSCode Extension does not show any of the UIs for running the test
<img width="706" alt="Screenshot 2023-09-21 at 11 09 15 AM" src="https://github.com/microsoft/playwright/assets/543633/cd021890-6113-4893-a8dc-364e61fcf805">

**Comment by yury-s** [comment]
The extension discovers playwright config by looking for files that match the following glob pattern: `**/*playwright*.config.{ts,js,mjs}`. `index.ts` does not match it, you need to rename it to something like `playwright.config.ts` and then the extension will be able to find it. Will that work for you?

**Comment by mohsen1** [comment]
@yury-s Thank you for your help. That makes sense. I renamed the file but I'm still getting the same results. Note that our repo is very large and it might take any sort of glob matching up to 10 minutes to find a file with that pattern on my machine. 

It would be ideal if we can explicitly tell the plugin where the config is at so it doesn't have to search for a file matching a glob pattern.

**Comment by yury-s** [comment]
> That makes sense. I renamed the file but I'm still getting the same results. Note that our repo is very large and it might take any sort of glob matching up to 10 minutes to find a file with that pattern on my machine.

Can you share a reduced repro? I'm curious how large the repository is and where it may take 10 minutes to match globs?

**Comment by mohsen1** [comment]
Hi @yury-s I can't share the entire repo but I'm making some changes on how we do configurations. Maybe that fixes this issue. I'll report the results back in here.

**Comment by yury-s** [comment]
Closing as part of the triage process. We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
