### ISSUE TITLE
[BUG] vscode no tests/no error

### ISSUE THREAD

**Issue by yogeshgadge** [microsoft/playwright#27221]
### System info
- Playwright Version: [v1.38]
- Playwright for vscode [1.0.15]
- Operating System: [macOS 13.5]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [X ] I provided exact source code that allows reproducing the issue locally.

```
/* eslint-disable @typescript-eslint/no-restricted-imports */
import type { PlaywrightTestConfig } from '@playwright/test';
import { defineConfig } from '@playwright/test';
import * as inspector from 'node:inspector';
import { join } from 'node:path';

const isDebug = !!inspector.url();
const config: PlaywrightTestConfig = defineConfig({
  use: {
    channel: 'chromium',
    browserName: 'chromium',
    headless: true,
    baseURL: 'http://localhost:4200',
    launchOptions: {
      args: ['--no-sandbox', '--window-size=1440,1200']
    }
  },
  fullyParallel: false,
  workers: 3,
  testDir: join(__dirname, 'src/specs'),
  testMatch: '**/*.e2e-spec.ts',

  timeout: isDebug ? 1000000000 : undefined,
  reporter: [['list', { printSteps: false }]]
});

export default config;
```

[Describe expected behavior]

List of tests in Test Explorer.
OR
Some error saying something went wrong.

[Describe actual behavior]

Error "No Playwright tests found."

**Comment by aslushnikov** [comment]
@yogeshgadge could you please create a repository that illustrates the issue?

**Comment by MarianS06** [comment]
@yogeshgadge check test-results.json -> errors section, you might find out some extra details there.

**Comment by yogeshgadge** [comment]
@aslushnikov reproduction https://github.com/yogeshgadge/pw-repo

I mention 2 issues in the  [readme](https://github.com/yogeshgadge/pw-repo#readme) That second issue is unrelated but it is a pain.

**Comment by yogeshgadge** [comment]
Also tried combining so that at the <root> I can have single `playwright.config.ts` but this looks like `Object.assign` as I see only app2 test cases.

```
import { defineConfig } from "@playwright/test";
import { pwAppConfig as pwC1 } from "./projects/ui-app1/e2e/playwright.config";
import { pwAppConfig as pwC2 } from "./projects/ui-app2/e2e/playwright.config";

export default defineConfig(pwC1, pwC2);

```

The following works but then it will apply test config 2 to all test cases 

```
import { defineConfig } from "@playwright/test";
import { pwAppConfig as pwC1 } from "./projects/ui-app1/e2e/playwright.config";
import { pwAppConfig as pwC2 } from "./projects/ui-app2/e2e/playwright.config";

export default defineConfig(pwC1, pwC2, { testDir: "./" });
```

# Why can't Playwright for vscode scan the <root> for certain file patterns and organize the tests by the config ?

**Comment by yogeshgadge** [comment]
After adding the <root>/playwright.config.ts as below it is able to figure out the tests. So this is one workaround I will go with.

```
import { defineConfig } from "@playwright/test";

export default defineConfig({ testDir: "./" });
```
 
Also now I can see choose
![image](https://github.com/microsoft/playwright/assets/2423608/6cb65761-98d5-42d7-b754-1b301146f6b0)

Notice it picks up one of the config randomly and if I click in the Play/Run all button it fails with `Error: No tests found`.

It works only if I pick the <root>/playwright.config.ts

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/27236, please don't file multiple issues for the same problem.
