### ISSUE TITLE
[BUG] Button shown as enabled, although it is not

### ISSUE THREAD

**Issue by NikkTod** [microsoft/playwright#27232]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [All]
- Browser: [Chromium]
- Other info:

### Source code

I have the element "Prev" button, which is in disabled state 

![image](https://github.com/microsoft/playwright/assets/94455079/95f5ddd0-d665-454d-88d9-8bbf000e7b5e)

```
<li data-scope="pagination" data-part="list-item" style="list-style-type: none; display: inline; margin-right: 1rem;">
<button type="button" class="chakra-button css-yox62n" id="pagination::r13::prev" data-scope="pagination" data-part="prev-page-trigger" data-disabled="" aria-label="previous page" value="Prev">Prev</button>
</li>
```

The codegen pick locator is showing me that I can find it by -> `GetByLabel("previous page")`

I also tried `GetByRole(AriaRole.Button, new() { Name = "Prev" })` , but with same result.

I want to check that the element is disabled and I am using the following:

`await Assertions.Expect(Page.GetByLabel(labelText)).ToBeDisabledAsync();`

Test fails with below error:

```
 Microsoft.Playwright.PlaywrightException : Locator expected to be disabled 
Call log:
LocatorAssertions.ToBeDisabledAsync with timeout 5000ms
waiting for GetByLabel("Prev")
  locator resolved to <button value="Prev" type="button" data-disabled="" data…>Prev</button>
  unexpected value "enabled"
```

Is it possible to catch the correct state of such kind of elements/buttons/labels?

**Comment by aslushnikov** [comment]
@NikkTod The button you're getting is rendered in a bleak color, but it is not "disabled".
As per the [`toBeDisabledAsync`](https://playwright.dev/dotnet/docs/api/class-locatorassertions#locator-assertions-to-be-disabled) documentation:

> Note that only native control elements such as HTML button, input, select, textarea, option, optgroup can be disabled by setting "disabled" attribute.

The button 

```html
<button type="button" class="chakra-button css-yox62n" id="pagination::r13::prev" data-scope="pagination" data-part="prev-page-trigger" data-disabled="" aria-label="previous page" value="Prev">Prev</button>
```

does not have any `disabled` attribute, so things work as expected. 

So you'd need to check some other condition. Ideally, the webpage authors mark the button as disabled - this will improve website accessibility, and your test would work as expected.

If this is not possible, then you'll have to fallback to some other methods, e.g. checking the actual color of the button.

Hope this helps!
