### ISSUE TITLE
[BUG/QUESTION] After updating v1.38 environment variables assigned in setup step are undefined during the test

### ISSUE THREAD

**Issue by sefaltay** [microsoft/playwright#27247]
### System info
- Playwright Version: [v1.38]
- Operating System: [Local: macOS 13.3.1 (Node v18.1), CI: mcr.microsoft.com/playwright:v1.38.0-focal]
- Browser: [Chromium]

### Other info
After updating playwright to v1.38, environment variables assigned in setup step are not accessible(_undefined_) in test files. It was working fine in v1.37 && v1.33. Not sure if this issue is directly related with playwright version, could be related with its dependencies. However, it works in CI, not in local (see OS info above).

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'api-setup',
      testMatch: 'auth.setup.ts',
    },
    {
      name: 'api',
      testDir: './playwright/tests/api',
      dependencies: ['api-setup'],
    },
  ],
});
```

**Test file (self-contained)**

```js
// auth.setup.ts
import { test as setup } from '@playwright/test';
import api from '../utils/api';

setup('Authenticate with API', async () => {
  const sessionDataAdmin = await api.login("admin", "pwd");
  const sessionDataUser = await api.login("user", "pwd");

  process.env.ADMIN_TOKEN = sessionDataAdmin.token;
  process.env.USER_TOKEN = sessionDataUser.token;
});

// test.step.ts
  test('Test environment variable', async ({ request }) => {
    expect(process.env.USER_TOKEN).toBeTruthy(); // returns undefined locally, works in playwright docker image
    expect(process.env.ADMIN_TOKEN).toBeTruthy(); // returns undefined locally, works in playwright docker image
   // ... continues with an api request which uses those tokens in header
  });
```

**Steps**
- Run any test which uses `USER_TOKEN` & `ADMIN_TOKEN` environment variables
- Verify if `USER_TOKEN` & `ADMIN_TOKEN` environment variables assigned

**Expected**

`USER_TOKEN` & `ADMIN_TOKEN` env variables should be assigned in `api-setup` step and should not be `undefined` in the tests that access those variables

**Actual**
`USER_TOKEN` & `ADMIN_TOKEN` env variables assigned successfully in `api-setup` step; however, they return as `undefined` in test files

**Comment by yury-s** [comment]
Can you share complete project where this happens? I tried with https://github.com/yury-s/bug-27247 and it is working fine.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue with a repro if it doesn't work.
