### ISSUE TITLE
[BUG] VS Code does not send selenium headers

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#27252]
### System info
- Playwright Version: v1.38.1
- Playwright VS Code: v1.0.15
- Operating System: macOS 12.3
- Browser: Chromium

### Source code

```
// .vscode/settings.json
{
  "playwright.env": {
    "SELENIUM_REMOTE_URL": "http://remote-url:4444/wd/hub",
    "SELENIUM_REMOTE_CAPABILITIES": {
      "browserName": "chrome",
      "browserVersion": "114.0"
    },
    "SELENIUM_REMOTE_HEADERS": {
      "Authorization": "OAuth token"
    }
  }
}
```

**Test file (self-contained)**

```js
it('fail', async ({ page }) => {
  await page.goto('about:blank');

  await expect(page).toHaveURL('foo');
});
```

**Steps**
- Run remote hub in docker container for example (I use selenoid)
- Run the test from vscode 

**Expected**

Pwt send oauth header to hub and everything works fine.

**Actual**

Pwt doesn't send oauth header and test fails with `Error connecting to Selenium at http://remote-url:4444/wd/hub/session: OAuth authorization is required`.

It works correctly without vscode.

**Comment by aslushnikov** [comment]
@DudaGod shouldn't this be reported to VSCode repository then?

**Comment by DudaGod** [comment]
> @DudaGod shouldn't this be reported to VSCode repository then?

I was going to create issue in the repository [playwright-vscode](https://github.com/microsoft/playwright-vscode). But found issue - https://github.com/microsoft/playwright-vscode/issues/233 which says that all issues must be create in this repository.

**Comment by yury-s** [comment]
The variable names should be strings (result of JSON.stringify), try running with:

```js
{
  "playwright.env": {
    "SELENIUM_REMOTE_URL": "http://remote-url:4444/wd/hub",
    "SELENIUM_REMOTE_CAPABILITIES": "{\"browserName\":\"chrome\",\"browserVersion\":\"114.0\"}",
    "SELENIUM_REMOTE_HEADERS": "{\"Authorization\":\"OAuth token\"}"
  }
}
```
will that work?

**Comment by DudaGod** [comment]
> will that work?

Yes, thank you. Is it expected behaviour?

**Comment by yury-s** [comment]
From Playwright's perspective it is. This is a configuration of environment variables, which are always string name -> string value. It's jut VSCode UI lets you write arbitrary json as the values.

**Comment by DudaGod** [comment]
> From Playwright's perspective it is. This is a configuration of environment variables, which are always string name -> string value. It's jut VSCode UI lets you write arbitrary json as the values.

I get it, but it's not very convenient to my mind. 

In general, it would be convenient if pwt will use selenium environment variables from the config when running the test using vscode extension. In our project we set these selenium environment variables in fixture. And everything works fine when run test from cli. But when run the test from the vscode plugin, the browser starts locally.

Is it expected behaviour?

**Comment by yury-s** [comment]
Yes, we can support this in the extension.

**Comment by DudaGod** [comment]
@dgozman in this PR - https://github.com/microsoft/playwright-vscode/pull/380/files you just stringify environment variables from `.vscode/settings.json` file.

But in this [comment](https://github.com/microsoft/playwright/issues/27252#issuecomment-1740597618) I describe another problem: vscode extension don't use envs from pwt config/fixture/etc. This means that the behavior changes depending on the launch from cli or from vscode plugin.

Should I create another issue about it?

**Comment by dgozman** [comment]
@DudaGod I missed that other comment, thanks for pointing it out.

> In general, it would be convenient if pwt will use selenium environment variables from the config when running the test using vscode extension. In our project we set these selenium environment variables in fixture. And everything works fine when run test from cli. But when run the test from the vscode plugin, the browser starts locally.

How do you set env variables in the config? I believe there should be no difference here between VSCode extension and cli.

**Comment by DudaGod** [comment]
> How do you set env variables in the config? I believe there should be no difference here between VSCode extension and cli.

I use simple config:
```
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";

process.env.DEBUG = "pw:browser";
process.env.SELENIUM_REMOTE_URL = "http://localhost:4444/wd/hub";
process.env.SELENIUM_REMOTE_CAPABILITIES = JSON.stringify({
    browserName: "chrome",
});

export default defineConfig({
    projects: [
        {
            name: "chromium",
            use: {...devices["Desktop Chrome"]},
        },
    ],
});
```

And test code:
```
// test.spec.ts
import { test } from '@playwright/test';

test('test', async ({page}) => {
    await page.goto('https://playwright.dev/');
});
```

How to reproduce:
- run test using vs code extension
- test runs in local browser

At the same time I see browser logs in the `test results` tab. It means that `process.env.DEBUG` was used. But selenium envs didn't.

**Comment by dgozman** [comment]
@DudaGod Do you have the "Show Browser" checkbox on? That would explain the behavior, because it forces local browser to be shown.

**Comment by DudaGod** [comment]
> @DudaGod Do you have the "Show Browser" checkbox on? That would explain the behavior, because it forces local browser to be shown.

Yes you're right, thanks. Looks like I set it up a long time ago and forgot to turn it off.
