### ISSUE TITLE
[Feature] Add Test Steps When Listing Tests

### ISSUE THREAD

**Issue by danrealednb** [microsoft/playwright#27259]
To generate a list of tests, you would run this command: `npx playwright test --list`

I would like another argument `--steps` to be added that can be an optional parameter that could list out the steps for each test or not.

An example output would be something like the following:

```
tests/test1.spec.ts (spec)
should run test 1 (test name)
   Step 1: do this (step)
   Step 2: do that
   Step 3: then do this
should run test 2
   Step 1: do this
should run test 3
   Step 1: do this
   Step 2: do that
```
We use test steps in our test cases since it keeps our code organized and readable without having to use something over the top like cucumber. This satisfies that need. It's great to have the steps in the reporters, but it seems to be missing when listing out the tests.
We would find this beneficial for being able to list out our test plans in greater detail for non technical users by including test steps. Plenty of people want to see what we're up to and it's much easier to copy pasta to confluence than point them to the code base. We could then share with other stakeholders.

**Comment by aslushnikov** [comment]
@danrealednb Unfortunately, it is impossible to list tests without running your tests since test steps are not declarative.

And if you run your tests, then you can get the test steps with the JSON reporter. Would this work for you?

**Comment by danrealednb** [comment]
@aslushnikov that would work. I guess I was just looking for an easy way to do a "dry run" without execution and document the steps in the test case. It sounds like there's not an option to do that. Thanks for looking into it!
