### ISSUE TITLE
[BUG] Missing dependency in Ubuntu for Webkit

### ISSUE THREAD

**Issue by tiagodaraujo** [microsoft/playwright#27255]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [Ubuntu 20]
- Browser: [WebKit]
- Other info: Also happens on the latest v1.38.1

### Source code

**Config file**

```shell
npm install -g @playwright/test@1.38.0
playwright install webkit --with-deps
```

```js
const playwright = require('@playwright/test');
(async () => {
    const browser = await playwright.webkit.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await browser.close();
})();
```

**Steps**
- Create a ubuntu base docker image
- Install webkit --with-deps
- Try to launch the webkit browser

**Expected**

I hope the browser opens and runs the test

**Actual**

On `playwright.webkit.launch()` this logged the following message

```
╔══════════════════════════════════════════════════════╗
║ Host system is missing dependencies to run browsers. ║
║ Missing libraries:                                   ║
║     libnghttp2.so.14                                 ║
╚══════════════════════════════════════════════════════╝
```

**Comment by aslushnikov** [comment]
@tiagodaraujo I wasn't able to repro.

Here's what I did:

```bash
docker run --rm -it ubuntu:20.04 /bin/bash
# Install node.js inside ubuntu
apt-get update
apt-get install -y curl wget gpg
curl -sL https://deb.nodesource.com/setup_18.x | bash - 
apt-get install -y nodejs
# dummy repo
cd && npm init -y && npm i @playwright/test@1.38
npx playwright install --with-deps webkit
cat <<EOF >a.js
const playwright = require('@playwright/test');
(async () => {
    const browser = await playwright.webkit.launch();
    const page = await browser.newPage();
    await page.goto('https://example.com');
    await browser.close();
})();
EOF
node a.js
```

This worked just fine. Could you please run these steps and see if they work for you?

**Comment by tiagodaraujo** [comment]
Hi @aslushnikov, Thank you for your help

In fact, running your script I can't replicate it. I am using custom base images and not the public ones and I was able to replicate the issue with your script on them (custom images).

In my case, I am using an Ubuntu image with nodejs already installed and for some reason, my image does not have this dependency installed (libnghttp2).

It seems to me like a dependency that appeared for Webkit in version 1.38.0, since I had no problems with version 1.37.1.

It seems to me that it would be useful to keep an updated list of all Webkit dependencies, not assuming that they are installed by default, what do you think?

Thank you

**Comment by tiagodaraujo** [comment]
Going into a deeper investigation, I realized nodejs image that I'm using installs node and its dependencies with the `--no-install-recommends` parameter. `apt-get install -y --no-install-recommends nodejs_18.16.deb`.

Therefore this package is just recommended and not required for nodejs.

Adding the command to the script `apt-get install libnghttp2-14`, I can now run the Webkit with no issues.

I remember that this started with version 1.38.0, before that this dependency was not necessary for the webkit.

Thank you

**Comment by aslushnikov** [comment]
> Going into a deeper investigation, I realized nodejs image that I'm using installs node and its dependencies with the --no-install-recommends parameter. apt-get install -y --no-install-recommends nodejs_18.16.deb.

@tiagodaraujo thank you for debugging this. I still don't see the `libnghttp2-14` as a WebKit dependency anywhere on Ubuntu 20.04. What's the base image for your custom docker container?

**Comment by aslushnikov** [comment]
> Going into a deeper investigation, I realized nodejs image that I'm using installs node and its dependencies with the --no-install-recommends parameter. apt-get install -y --no-install-recommends nodejs_18.16.deb.

@tiagodaraujo thank you for debugging this. I still don't see the `libnghttp2-14` as a WebKit dependency anywhere on Ubuntu 20.04. What's the base image for your custom docker container?

**Comment by yury-s** [comment]
It is apparently required by libsoup3, I can see that the dependency is required:

```sh
root@455db2225531:~# mv  /usr/lib/x86_64-linux-gnu/libnghttp2.so.14.19.0 /tmp/
root@455db2225531:~# /ms-playwright/webkit-1908/pw_run.sh --headless
/ms-playwright/webkit-1908/minibrowser-wpe/bin/MiniBrowser: error while loading shared libraries: libnghttp2.so.14: cannot open shared object file: No such file or directory
```

**Comment by yury-s** [comment]
Debugging notes on ubuntu 20: `bin/WPENetworkProcess` depends on `libsoup-3.0.so.0` which in turn depends on `libnghttp2.so.14`. From what I can tell those libraries are supposed to be linked statically on Ubuntu 20 but instead we are looking for them on the host.

**Comment by yury-s** [comment]
It is `curl` and more precisely `libcurl4` that depends on `libnghttp2` and brings it into our docker image first.
