### ISSUE TITLE
[BUG] Tap version output in console when running tests with suites(describes)

### ISSUE THREAD

**Issue by olexandr13** [microsoft/playwright#27251]
### System info
- Playwright Version: v1.38.1
- Operating System: macOS 13.5
- Browser: Chromium
- Other info:

### Source code

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';
import config from './src/env-config';
import { authStorage } from './src/env-constants';

export default defineConfig({
  expect: {
    timeout: 5000,
  },
  testDir: './src/tests',
  fullyParallel: false,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : 1,
  reporter: [
    ['list'],
    ['junit', { outputFile: './report.xml' }],
    ['html', { open: 'never', outputFolder: 'pw-report-partner-' + config.partnerId }],
  ],
  reportSlowTests: { max: 5, threshold: 30000 },
  use: {
    actionTimeout: 9000,
    baseURL: config.bebopUrl,
    headless: !!process.env.CI,
  },
  projects: [
    {
      name: 'auth',
      testMatch: /.*auth.login\.ts/,
      use: { baseURL: config.rocksteadyUrl },
    },
    {
      name: 'ui',
      dependencies: ['auth'],
      testMatch: /ui\/.*\.test\.ts/,
      timeout: 35000,
      use: {
        baseURL: `${config.bebopUrl}/${config.partnerId}`,
        ...devices['Desktop Chrome'],
        channel: 'chromium',
        screenshot: 'only-on-failure',
        storageState: authStorage,
        video: 'on-first-retry',
        trace: process.env.CI ? 'on-first-retry' : 'retain-on-failure',
      },
    },
  ],

```

**Steps**
- [Run the test] npx playwright test ...

**Expected**
No Tap output

**Actual**
Strange tap output appears
![telegram-cloud-photo-size-2-5217440664348903897-y](https://github.com/microsoft/playwright/assets/16742970/7c876a39-ac47-4cf1-b59a-fe6a8da84287)

**Comment by aslushnikov** [comment]
@olexandr13 we do not have TAP reporter built in - it looks like you have some dependency that yields this output. Could it be the case?

**Comment by olexandr13** [comment]
@aslushnikov for sure it could, but I have already checked everything that comes into my mind, but did not find the reason.
But thank you for your answer, that was what I needed. I will investigate further...

**Comment by olexandr13** [comment]
It disappears after updating the node from 18 to 20... Oh. Closing and thank for answer one more time.

**Comment by olivaalbert1** [comment]
@aslushnikov it happends again in 22 node version. Should we assume it's a problem with Node?

"@types/node": "^22.15.18"
