### ISSUE TITLE
Whitescreen at the start of the WEBM Video recording

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27253]
When recording test executions, there is a white screen at the start of every video before the actual test video begins. What is this white screen? Can it be avoided or replaced with something else?

![image](https://github.com/microsoft/playwright/assets/5722603/1be36e7c-4224-431e-9b64-cefb7136284a)

**Comment by aslushnikov** [comment]
@sramasub this is the `about:blank` page before it started navigating. Why does it bother you?

**Comment by sramasub** [comment]
The reason is, we would like to submit these videos as test proofs to business. These videos may also be used for training needs. Hence making it start from the sign-on page is preferred.

**Comment by aslushnikov** [comment]
@sramasub I'm afraid you will have to post-process them then. Sorry for the inconvenience!
