### ISSUE TITLE
[Question] Allow cross-site tracking or change your browser

### ISSUE THREAD

**Issue by ordimans** [microsoft/playwright#2726]
Hello

I coded a thing to registre on a website, login is working perfectly.
But register i have this error immediately :
please allow cross-site tracking or change your browser

Do you have an idea ?

I am using like that :

```
const { webkit, chromium, firefox, devices } = require('playwright');
const iPhone11 = devices['iPhone 11 Pro'];
(async () => {
  const browser = await webkit.launch({headless: false});
  const context = await browser.newContext({
    ...iPhone11
  });
  const page = await context.newPage();

```

**Comment by pavelfeldman** [comment]
The site that you point to is probably using login fingerprinting that Safari now blocks. It means this site will no longer work with the modern Safari, so it is telling you to switch the browser.

https://www.theverge.com/2020/3/24/21192830/apple-safari-intelligent-tracking-privacy-full-third-party-cookie-blocking

https://webkit.org/blog/10218/full-third-party-cookie-blocking-and-more/
