### ISSUE TITLE
Highlight Actions done on the webpage

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27268]
Is there a way to highlight the element where the action is performed currently? For e.g., highlighting the element when it is clicked, when a data is entered etc.? Sometimes it is tough to find out from the test video what was the action performed if a user looks at it as the action gets carried out quickly.

**Comment by yury-s** [comment]
> Is there a way to highlight the element where the action is performed currently? For e.g., highlighting the element when it is clicked, when a data is entered etc.?

[Locator.highlight](https://playwright.dev/docs/api/class-locator#locator-highlight) does this. You can use that for debugging purposes. Alternatively, you can run the test in [debug mode](https://playwright.dev/docs/running-tests#debugging-tests) or use [VSCode extension](https://playwright.dev/docs/getting-started-vscode).

> Sometimes it is tough to find out from the test video what was the action performed if a user looks at it as the action gets carried out quickly.

Use [tracing](https://playwright.dev/docs/trace-viewer-intro) instead, it will highlight the cursor at the position where the action was performed and has more other features useful for debugging.
