### ISSUE TITLE
Way to test assertions on the web page before applying it to the test function

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27269]
Is there a way to test the assertion statement on the web page first before we apply it to the test function so that we don't have to execute the function every time to ensure the statement works?

**Comment by yury-s** [comment]
There is no way to run an assertion directly, but you can use [`codegen`](https://playwright.dev/docs/getting-started-vscode#generating-tests) to pick a good locator which is usually the most tricky part and then change it into an assertion.
