### ISSUE TITLE
[BUG] Selenium Grid desiredcapabilities

### ISSUE THREAD

**Issue by wodyjowski** [microsoft/playwright#27276]
### System info
- Playwright Version: v1.38.1
- Operating System: All
- Browser: Chromium
- Other info: Selenium Grid

### Issue

DesiredCapabilites field was used by Selenium 3.
It was recently removed (with no mention in their changelog, I love Java developers).
Playwright stopped working with Selenium Grid > 4.8.2.
I've checked the traffic from genuine Selenium driver with wireshark and they just send `{ capabilities: { alwaysMatch...`.
Created a PR: https://github.com/microsoft/playwright/pull/27275

**Comment by luki530** [comment]
Guys can you bump a priority on this? Looks like exactly this is also blocking me from upgrade.

**Comment by DamWar** [comment]
up

**Comment by MarcinZS** [comment]
That's exactly what I need. Up!

**Comment by pitrzu** [comment]
Up

**Comment by mstokowy** [comment]
Up

**Comment by MateuszLin** [comment]
Up

**Comment by Matheovi** [comment]
Up

**Comment by lukiop7** [comment]
up

**Comment by Shareza** [comment]
up

**Comment by piechockidaniel** [comment]
up
