### ISSUE TITLE
Test doesn't fail inside context.on("page") when it should in Mocha

### ISSUE THREAD

**Issue by shishkin17** [microsoft/playwright#2727]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Mac
- Node version: 10.15.2
- Browser: Chromium
- Test runner: Mocha

```javascript
const playwright = require('playwright');
const { devices } = require('playwright');
const chai = require('chai');
const expect = chai.expect;

let page, browser, context;

describe('Some test', function() {

    before(async function() {
        browser = await playwright['webkit'].launch({ headless: false });
        const device = devices['iPhone 7'];
        context = await browser.newContext({ ...device });
        page = await context.newPage();

        await page.goto("http://example.com");
    });

    after(async function() {
        await browser.close();
    });


    it('should work', async function() {

        await context.on("page", async newPage => {
            console.log("newPage", await newPage.title());
            expect(true).to.be.false; // should fail
            await newPage.close();
            await page.close()
        });

        await page.click('form input[name="submitButton"]'); // opens new tab
    });
});
```

**Description**

I am using playwright with mocha to run e2e tests.
If I am asserting second tab in context.on("page") and assertion fails, the test doesn't fail with that info - it shows warning like this "UnhandledPromiseRejectionWarning: AssertionError: expected true to be false" and fails later on timeout.
Maybe that "context.on("page")" is not the best solution, but I don't know any other that works.

**Comment by mxschmitt** [comment]
The way how you are using async/await for the new Page does not lead to the behaviour which you are trying to accomplish. Basically the callback won't run inside the actual test, it could potentially run once the test is already finished.

If you want to work with the newPage and assert there some properties, you can do it like that:

```js
// @ts-check
const playwright = require("playwright");

(async () => {
  const browser = await playwright.chromium.launch();
  const context = await browser.newContext();
  const page = await context.newPage();

  const newPagePromise = new Promise(resolve => context.on("page", resolve))
  await page.evaluate(() => window.open("https://google.com", "_blank"))

  const newPage = await newPagePromise
  console.log("newPage", await newPage.title())

  await browser.close();
})();
```

Interactive: https://try.playwright.tech/?s=26ku5

**Comment by shishkin17** [comment]
> The way how you are using async/await for the new Page does not lead to the behaviour which you are trying to accomplish. Basically the callback won't run inside the actual test, it could potentially run once the test is already finished.
> 
> If you want to work with the newPage and assert there some properties, you can do it like that:
> 
> ```js
> // @ts-check
> const playwright = require("playwright");
> 
> (async () => {
>   const browser = await playwright.chromium.launch();
>   const context = await browser.newContext();
>   const page = await context.newPage();
> 
>   const newPagePromise = new Promise(resolve => context.on("page", resolve))
>   await page.evaluate(() => window.open("https://google.com", "_blank"))
> 
>   const newPage = await newPagePromise
>   console.log("newPage", await newPage.title())
> 
>   await browser.close();
> })();
> ```
> 
> Interactive: https://try.playwright.tech/?s=26ku5

That syntax doesn't work in Mocha:
```js
const newPagePromise = new Promise(resolve => context.on("page", resolve))
  await page.evaluate(() => window.open("https://google.com", "_blank"))
  const newPage = await newPagePromise
```

**Comment by dgozman** [comment]
I'd suggest to follow [this guide](https://playwright.dev/#version=v1.1.1&path=docs%2Fverification.md&q=popup---handle-popup-windows):

```js
const [popup] = await Promise.all([
  page.waitForEvent('popup'),
  page.click('form input[name="submitButton"]')
]);
```

**Comment by shishkin17** [comment]
I see that asserting in event is wrong. But the code with promise sometimes doesn't work. It works on some plain example site, but it doesn't on my real one. I just don't want to spend time on that anymore. It is easier not to deal with 2 tabs.
