### ISSUE TITLE
[BUG]Locator not found by Firefox but other browsers

### ISSUE THREAD

**Issue by lilipilon** [microsoft/playwright#27274]
So, we have this sticky on our website

<img width="958" alt="image" src="https://github.com/microsoft/playwright/assets/145915774/f7eedddb-1a0d-480f-a0fe-8672aaff1775">

the url : https://www.etam.com/culottes-et-bas-tangas/tanga-en-dentelle-654217805.html

So we would like that there is a boucle in order to click on the first available size and click on the add to cart button : 
```
  await page.click("#stickyAddToCartBtn");
        await page.isVisible("#productSizeDropdown > div.dropdownBloc.shadow1.js-dropdownBlock");
      const availableSizes = await page.$$("div.hideMobile > div.productSizeDropdown > div.dropdownBloc.shadow1.js-dropdownBlock > div > div:nth-child(1) > div");
      let clicked = false;
      for (const size of availableSizes) {
        const isAvailable = await size.isVisible();
       if (isAvailable && !clicked) {
        await size.click();
        clicked = true;
        break;
      }
      }
      await page.click("#stickyAddToCartBtn");
      }
```
This code works fine on Desktop Chromium and Desktop toolkit but not on firefox and we don't why.
So, if you could help us...

**Comment by yury-s** [comment]
Probably the server returns a different page for Firefox where an element with such locator does not exist. Try using [codegen](https://playwright.dev/docs/codegen-intro#running-codegen) with firefox to pick locator there? If you think it is a bug in playwright, please file a new issue with a repro that demonstrates the problem.
