### ISSUE TITLE
[Feature]: Need Drag and drop support in codegen

### ISSUE THREAD

**Issue by Anirudhv19** [microsoft/playwright#27287]
Current Playwright feature:
The below working sample is sample that contains treeview component which support Drag and Drop feature. But while using codegen for test purpose, the drag and drop feature doesn't work.

Local Browser:

https://github.com/microsoft/playwright/assets/145647783/6179b786-92b1-4853-9178-fc1206e21aab

Chromium browser:

https://github.com/microsoft/playwright/assets/145647783/9a147a38-4ba4-4fb1-bfdf-3b2e6fcdca1b

**Comment by Anirudhv19** [comment]
Hi, any update on this feature request?

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/19892.
