### ISSUE TITLE
[BUG] Error: EPERM or EBUSY related to traces when run all the tests

### ISSUE THREAD

**Issue by denkorz** [microsoft/playwright#27286]
### System info
- Playwright Version: [v1.38.1]
- Operating System: Windows 10
- Browser: Chromium

**Config file**

```js
// playwright.config.ts
.......
 {
      name: 'local-chromium',
      use: {
        ...devices['Desktop Chrome'],
        trace: 'on',
      },
    },
.......
```

**Steps**
- Update playwright to the latest version,
- Run all the tests (around 103 with UI, API) using the following command:
npx playwright test --workers 1 --project=local-chromium

**Expected**
failed tests are marked as failed, passed as passed

**Actual**
Some tests are failing with the following issues in afterAll (but with no specific issue place in logs) without any visible reasons

`Error: tracing.stopChunk: EBUSY: resource busy or locked, copyfile 'C:\PW\test-results\.playwright-artifacts-2\traces\f36fdf6c8429426f1a7f-da1a60ab78e80e3d8045-context8.network' -> 'C:\PW\test-results\.playwright-artifacts-2\traces\f36fdf6c8429426f1a7f-da1a60ab78e80e3d8045-context9.network'`

or

`Error: EPERM: operation not permitted, rename C:\PW\test-results\test-name-local-chromium\trace.zip' -> 'C:\PW\test-results\test-name-local-chromium\trace.zip.tmp'`

**Comment by yury-s** [comment]
Do you have an antivirus software on the machine? If so, it most likely opens the file for scanning and breaks the rename operation. You can try and add an exception for the playwright folder. If there is no antivirus, there is someone else holding an open handle to the file, you can try to use [handle.exe](https://learn.microsoft.com/en-us/sysinternals/downloads/handle) to print all programs that has the file open

```cmd
handle.exe 'C:\PW\test-results\test-name-local-chromium\trace.zip'
```

but it will only work if the other program keeps the file open. It's hard to tell who exactly breaks tampers with the filesystem operations without a repro.

**Comment by denkorz** [comment]
> Do you have an antivirus software on the machine? If so, it most likely opens the file for scanning and breaks the rename operation. You can try and add an exception for the playwright folder. If there is no antivirus, there is someone else holding an open handle to the file, you can try to use [handle.exe](https://learn.microsoft.com/en-us/sysinternals/downloads/handle) to print all programs that has the file open
> 
> ```batchfile
> handle.exe 'C:\PW\test-results\test-name-local-chromium\trace.zip'
> ```
> 
> but it will only work if the other program keeps the file open. It's hard to tell who exactly breaks tampers with the filesystem operations without a repro.

handle.exe doesn't work, it returns No matching handles found. after some delay. 
Anti virus is default windows defender. Previous version of Playwright (1.37) worked well. Test is green if I run it in debug mode via VSCode, but red if I run it using command mpx playwright test -g 'name' --project=local-chromium or in UI mode.

**Comment by denkorz** [comment]
@yury-s is there a DEBUG env var key (Like this one) which could give more info about this issue?
![image](https://github.com/microsoft/playwright/assets/39763254/8d134cf2-a573-4071-9d5f-6e197b190c40)

**Comment by denkorz** [comment]
Now I can grab only the following info:
```
Running 1 test using 1 worker

-> onBegin:
     1 [local-chromium] › myTest.spec.ts:42:7 › myTestDesc › myTestName
  ✘  1 [local-chromium] › myTest.spec.ts:42:7 › myTestDesc › myTestName (1.7s)
--> onTestEnd: "myTestName": failed, ==> TestError:
    value: undefined
    message: EPERM: operation not permitted, rename 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip' -> 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip.tmp'
    location: undefined, (undefined:undefined)
    snippet:
undefined
    stack:
Error: EPERM: operation not permitted, rename 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip' -> 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip.tmp'




  1) [local-chromium] › myTestFolder/myTest.spec.ts:42:7 › myTestDesc › MyTestName────────────────────

    Error: EPERM: operation not permitted, rename 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip' -> 'C:\PW\test-results\myTestExtendedName-local-chromium\trace.zip.tmp'




    attachment #1: trace (application/zip) ─────────────────────────────────────────────────────────
    test-results\myTestExtendedName-local-chromium\trace.zip
    Usage:

        npx playwright show-trace test-results\myTestExtendedName-local-chromium\trace.zip

    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 failed
    [local-chromium] › myTestFolder/myTest.spec.ts:42:7 › myTestDesc › MyTestName────────────────────
-> onEnd: failed

To open last HTML report run:

  npx playwright show-report

-> onExit
```

**Comment by yury-s** [comment]
> @yury-s is there a DEBUG env var key (Like this one for browser) which could give more info logs related to reporting?

Yes, there is a bunch of debug logging. vars which let you debug playwright internals but in this case it is a problem with a trace file on windows filesystem and there is no logging for that in playwright.

> Anti virus is default windows defender. 

Can you try disabling it and see if the problem persists?

**Comment by denkorz** [comment]
Disabling of these features doesn't help and the result would be different I believe. This issue is reproducible each time with some tests and not reproducible with other. In case of issues related to Windows it would be floating issue I believe..

**Comment by yury-s** [comment]
We need a repro to help you with this, it seems that there is something specific to your environment that causes the problem.

**Comment by david-granqvist-olink** [comment]
I get the error when I try do do multiple cleanups with multiple test.afterAll. 

Here is a testcase that gives me the error.
I think it is connected the use of page.goto in 'Cleanup: 1'

```typescript
import { test } from '@playwright/test';

test.describe.serial('Some testing', () => {
  test('A test', async ({ page }) => {
    await page.goto('/');
  });

  test.afterAll('Cleanup: 1', async ({ browser }) => {
    const page = await browser.newPage();
    await page.goto('/');
  });

  test.afterAll('Cleanup: 2', async () => {
    // Get the error here when running. "playwright test --ui"
    // EPERM: operation not permitted, rename '...\trace.zip' -> '...\trace.zip.tmp'
    // If we remove the page.goto in "Cleanup: 1" I get no error message.
  });

  test.afterAll('Cleanup: 3', async () => {
    // Since the error dissappears quickly. I added this to be able to see the error message
    await new Promise((resolve) => { setTimeout(resolve, 20000); });
  });
});

```

**Comment by nzacca** [comment]
I can confirm that this is fixed for our use cases in the alpha release: [1.40.0-alpha-oct-20-2023](https://www.npmjs.com/package/@playwright/test/v/1.40.0-alpha-oct-20-2023) .

Thanks everyone!

**Comment by daniavander** [comment]
i updated the latest version, but i get this EPERM error message continue

**Comment by mayurbojappa** [comment]
Is this issue fixed in latest release or will be fixed on the next release? I am still getting this error on 1.39

**Comment by nzacca** [comment]
@mayurbojappa The commit that fixes this is not released yet. You can try updating to the prerelease version I mentioned above to test if that fixes your scenario while we wait for the next release. 

https://www.npmjs.com/package/@playwright/test/v/1.40.0-alpha-oct-20-2023
