### ISSUE TITLE
Is it possible to launch playwright browser "headless:false" in a docker container.

### ISSUE THREAD

**Issue by kunal0810** [microsoft/playwright#2728]
I am running the playwright in a docker container where i am trying to take screenshot .
I tried to run the code locally it run fine. when i run it inside docker it is not  running.
Argument i passed inside browser.launch() is "headless:false". as the website is not supporting headless browser.

**Comment by yury-s** [comment]
There is no display in docker container so if you run headful browser you should use `xvfb-run`, something like `xvfb-run node <your script>`

> the website is not supporting headless browser.

Can you elaborate on what you mean by this? You should be able to run it in headless mode (especially in a container) and take a screenshot just fine, if it doesn't work we should fix it. Btw, which browser is this?

**Comment by atali** [comment]
You should check that issue https://github.com/microsoft/playwright/issues/2609

**Comment by aslushnikov** [comment]
I'd also recommend using `xvfb-run --auto-servernum` to run command with a random display number:

```sh
xvfb-run --auto-servernum npm run test
```
