### ISSUE TITLE
[Feature] Mask or obscure sensitive data (e.g. passwords) in Playwright's html report

### ISSUE THREAD

**Issue by stephenmee** [microsoft/playwright#27282]
I would like the html report to mask sensitive information. Perhaps there could be an option when using the 'fill' command to ensure that the values used are not displayed in the report. This would be a best practice for hiding passwords and other sensitive data in the reports. Cypress currently offer this option. I think it would be of benefit to the Playwright community in general.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/19992
