### ISSUE TITLE
[BUG] Cannot find module 'playwright/jsx-runtime' when running tests through vscode extension

### ISSUE THREAD

**Issue by woahitsraj** [microsoft/playwright#27285]
**Context:**
- Playwright Version: 1.38.
- Operating System: MacOS
- Node.js version:  18
- Visual Studio Code version: 1.82.2
- Playwright for VSCode extension version: v1.0.15
- Browser: All
- Extra:  I am importing some JSX components

**Code Snippet**

```
Error: Cannot find module 'playwright/jsx-runtime'
Require stack:
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/snackBar/billySnackBar.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/SnackbarHandler/SnackbarAlertContainer.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/SnackbarHandler/SnackbarHandler.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/error/BillyErrorSnackbarDisplay.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/ErrorHandler/ErrorHandler.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/components/data/billyUrql.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/src/generated/graphql.tsx
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/pageObjectModels/playwright-authApi.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/fixtures/base.fixture.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/playwright/local/customFields.spec.ts
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/transform/transform.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/common/config.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/reporters/json.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/reporters/html.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/runner/reporters.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/runner/runner.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/lib/cli.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/[playwright@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/playwright/cli.js
- /Users/rsingh/Projects/subskribe/billy-ui-ng/node_modules/.pnpm/@[playwright+test@1.38.1](vscode-file://vscode-app/Applications/Visual%20Studio%20Code.app/Contents/Resources/app/out/vs/code/electron-sandbox/workbench/workbench.html)/node_modules/@playwright/test/cli.js
```

I get a `Error: Cannot find module 'playwright/jsx-runtime'` when importing a `tsx` component  however it's quite far down the stack. However it doesn't show up when I run playwright from the CLI

**Comment by yury-s** [comment]
Can you share a repro that we could run locally to see the problem (there is probably something peculiar in your config or project structure)?

**Comment by woahitsraj** [comment]
Sure I'll try to put together a simple reproduction repo, I'll have it ready soon

**Comment by woahitsraj** [comment]
Okay... very strangely while creating a reproduction repository the issue magically fixed itself. I simply unimported and then reimported the first jsx component in the stack trace which I was grabbing typescript types from. I'm not at all sure how the vscode Playwright runner is handling the dependency tree but perhaps it could be because it was going from tsx => ts => tsx again in the component tree? You can clearly see that the tests all of  a sudden start passing and are even able to be run. Very strange.

I'll close this for now.

<img width="1203" alt="CleanShot 2023-09-25 at 23 21 14@2x" src="https://github.com/microsoft/playwright/assets/700308/70bb7427-e4ae-4857-bd6e-b6496060daf3">

**Comment by woahitsraj** [comment]
Hello,

I've managed to create a minimal reproduction of this issue inside this repository:

https://github.com/woahitsraj/Playwright-failing-vscode-example

Steps:

1. Run `pnpm i`
2. Run `npx playwright test`
3. Observe tests run fine with no issue
4. Open vscode
5. Open "Testing" tab in Playwright for Vscode Extension
6. Try to run tests
7. Receive error
```
Error: Cannot find module 'playwright/jsx-runtime'
```

**Comment by woahitsraj** [comment]
Seems to be caused by `pnpm` since running `npm i` results in a similar issue

**Comment by woahitsraj** [comment]
Thanks so much for answering and taking a look at this issue. 

When you say install the `playwright` package manually what do you mean? Would it be installing a global version using `pnpm` or `npm` to keep the version used by vscode the same as the one used by my local test runner?

**Comment by mxschmitt** [comment]
> Thanks so much for answering and taking a look at this issue. 
> 
> 
> 
> When you say install the `playwright` package manually what do you mean? Would it be installing a global version using `pnpm` or `npm` to keep the version used by vscode the same as the one used by my local test runner?

pnpm install playwright should make it work.

To keep the version in sync in your local package.json/lock.

**Comment by dgozman** [comment]
The fix would be to use absolute path for `jsx-runtime` here: https://github.com/microsoft/playwright/blob/main/packages/playwright/bundles/babel/src/babelBundleImpl.ts#L68

```ts
require('path').dirname(require.resolve("playwright"))
```
