### ISSUE TITLE
[BUG] wait for more than one responses after clicking a button.

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#27298]
### System info
- Playwright Version: 1.36.2
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

can you please advise if there is a way to wait for 2 responses like this in a single line?

Code not working: also ,will regex be supported in the below snippet? not sure why it regex is not working when i wait for both the responses in a single line?
```javascript
//not working
const responsePromise = page.waitForResponse(response =>
    response.url() === '**/order?base='' && response.url() === '**/product/base'
);
await page.getByText('trigger response').click();
const response = await responsePromise;

//or
//not working
const responsePromise = page.waitForResponse(response =>
    response.url().includes(**/order) && response.url().includes('**/product')
);
await page.getByText('trigger response').click();
const response = await responsePromise;

```

below code is working, however i wanted to see if there is way to club and wait for both the responses after clicking the button, in playwright, in a single line.
```javascript
           const crewMemberAccrualPromisePage1 = page.waitForResponse('**/order');
            const crewMemberAccrualPromisePage2 = page.waitForResponse('**/product');
            await page.getByText('trigger response').click();
            await crewMemberAccrualPromisePage1;
            await crewMemberAccrualPromisePage2;
```

**Comment by yury-s** [comment]
You are using `&&` which is `and` while you need `or`, i.e. `response.url().includes(**/order) || response.url().includes('**/product')` would do what you want. But `waitForRequest` will still wait for the first matching request only. The solution that you have is good as it makes it clear that you are waiting for 2 requests. You can also use `Promise.all` to wait for both of them: `await Promise.all(crewMemberAccrualPromisePage1, crewMemberAccrualPromisePage2);`.
