### ISSUE TITLE
[BUG] Fonts do not applied in Chromium if use page.route() before mount()

### ISSUE THREAD

**Issue by RiceWithMeat** [microsoft/playwright#27294]
### System info
- Playwright Version: [v1.38]
- Operating System: [macOS 13.2.1]
- Browser: [Chromium]

If use page.route() before component mount(), fonts will not load in Chromium. Other CSS applied correctly.
I ran same test in Safari and all CSS works fine.

**Link to the GitHub repository with the repro**

https://github.com/RiceWithMeat/playwright-ct-fonts-bug

**Expected**

Montserrat font used for h1

**Actual**

Times New Roman used for h1

**Comment by yury-s** [comment]
Debugging notes: this is another manifestation of https://bugs.chromium.org/p/chromium/issues/detail?id=1279953. We receive two `Fetch.requestPaused` for the same request id and resume it only once.
