### ISSUE TITLE
[Feature/Bug] retain-on-failure for fixtures 'after test' not saved

### ISSUE THREAD

**Issue by ofirpardo-artlist** [microsoft/playwright#27303]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [macOS]
- Browser: [Chromium]

### Source code
**Config file**

```js
// playwright.config.ts
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    video: "retain-on-failure",
    trace: "retain-on-failure",
  },
```

**Test file (self-contained)**

```js
import { test as base } from "@playwright/test";

const test = base.extend<{ fixture: void }>({
  fixture: [
    async ({}, use) => {
      await use();
      test.fail();
    },
    { auto: true },
  ],
});

test("example", async ({ page }) => {});
```

**Steps**
- [Run the test]

I hoped the trace/video to be attached since the test failed eventually. I understand why it doesn't show it, as the test itself actually passed and only failed in the fixture after the test is finished, not sure if it's a bug or a feature request, but it would be useful to be able to have traces for such cases.

I hoped as a workaround to manually modify the status in `testInfoImpl` but the code that checks if artifacts should be saved is running before the fixture 'after test', so I can't modify it there.

Regardless if this is a bug or a feature request, is there any possible workaround meanwhile?
Thanks!

**Comment by dgozman** [comment]
Investigation notes: by the time we call `didFinishTest` that determines whether we should keep trace or not, the previous fixture failure has not been registered in `TestInfoImpl` yet and the test is not considered failed yet. This is due to `teardownScope` implementation with `try/catch` inside a loop.

**Comment by veliakiner** [comment]
> ### System info
> 
>     * Playwright Version: [v1.38.1]
> 
>     * Operating System: [macOS]
> 
>     * Browser: [Chromium]
> 
> 
> ### Source code
> 
> **Config file**
> 
> ```js
> // playwright.config.ts
>   use: {
>     /* Base URL to use in actions like `await page.goto('/')`. */
>     // baseURL: 'http://127.0.0.1:3000',
>     /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
>     video: "retain-on-failure",
>     trace: "retain-on-failure",
>   },
> ```
> 
> **Test file (self-contained)**
> 
> ```js
> import { test as base } from "@playwright/test";
> 
> const test = base.extend<{ fixture: void }>({
>   fixture: [
>     async ({}, use) => {
>       await use();
>       test.fail();
>     },
>     { auto: true },
>   ],
> });
> 
> test("example", async ({ page }) => {});
> ```
> 
> **Steps**
> 
>     * [Run the test]
> 
> 
> I hoped the trace/video to be attached since the test failed eventually. I understand why it doesn't show it, as the test itself actually passed and only failed in the fixture after the test is finished, not sure if it's a bug or a feature request, but it would be useful to be able to have traces for such cases.
> 
> I hoped as a workaround to manually modify the status in `testInfoImpl` but the code that checks if artifacts should be saved is running before the fixture 'after test', so I can't modify it there.
> 
> Regardless if this is a bug or a feature request, is there any possible workaround meanwhile? Thanks!

As a workaround you can try catching the error, then setting `testInfo.status = "failed"` and throwing the error back:
`
    try {
       // Your code fails here
    } catch (e) {
      testInfo.status = "failed";
      throw e;
    }
`

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.

**Comment by sravanth-space** [comment]
I am having the same issue can you reopen this
