### ISSUE TITLE
[BUG] The playwright UI doesn't display test timeout errors

### ISSUE THREAD

**Issue by ilmarspenneo** [microsoft/playwright#27304]
### System info
- Playwright Version: v1.38.1
- Operating System: Arch Linux
- Browser: Chromuim
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
  timeout: 1000,
});
```

**Test file (self-contained)**

```js
import { test } from '@playwright/test';
test('test', async ({ page }) => {
  await page.waitForSelector('.never-exists');
});

test('test two', async ({ page }) => {
  await page.waitForTimeout(400);
  await page.waitForTimeout(400);
  await page.waitForTimeout(400);
});

test('test three', async ({ page }) => {
  await page.waitForTimeout(1100);
});
```

**Steps**
- Open playwright UI
- Run the testcases

**Expected**

The tests fail and display an error which indicates that the maximum execution time has been reached, like when executing from the commandline
![image](https://github.com/microsoft/playwright/assets/132436248/0827b66e-9a07-43ed-b204-24655b2b763f)

**Actual**

The tests fail, but none of them show a useful error. some of them don't even show that there was an error, they just fail!:
![image](https://github.com/microsoft/playwright/assets/132436248/dba482ce-a7e9-4862-b77d-05d70c18f58d)
![image](https://github.com/microsoft/playwright/assets/132436248/42de27cb-3747-4d3e-a5b8-c4bb97f2947c)
![image](https://github.com/microsoft/playwright/assets/132436248/0ba65d50-477d-441f-85c0-bcf80f214449)

**Comment by pavelfeldman** [comment]
New error message:

![timed_out](https://github.com/microsoft/playwright/assets/883973/14433932-30d0-42b7-9e4b-618daa91dda6)
