### ISSUE TITLE
Is Playwright Node.js less flaky than Playwright Python? 

### ISSUE THREAD

**Issue by sramasub** [microsoft/playwright#27314]
We are moving away from Selenium precisely for the fact that tests in selenium are flaky. We have been trying some tests using Playwright and find that tests executed in playwright python also experience flakiness. Is Node.js better in providing stable tests?

Also what are some of the addn. features in Node.js that are not available in other bindings? For e.g., I find features like visual comparison, retries etc. not available in python but are available in Node.js. Should we go with Node.js over python?

**Comment by yury-s** [comment]
> Is Node.js better in providing stable tests?

All language ports including Python use the same core implementation of playwright (we call it driver), so most library features are the same across languages.

> Also what are some of the addn. features in Node.js that are not available in other bindings? For e.g., I find features like visual comparison, retries etc. not available in python but are available in Node.js.

[Playwright library](https://playwright.dev/docs/library) is ported to other languages while Playwright Test is only available in Node.js. It comes with a bunch of nice features implemented in the test runner and not available in Python where we recommend pytest.

> Should we go with Node.js over python?

Playwright Test does provide many unique capabilities but it is up to your team to decide whether they are worth migrating from python. If you were starting from scratch we'd recommend Node.js version of Playwright but we don't know all the constraints and limitation of your project.
