### ISSUE TITLE
[BUG] toHaveScreenshot fullPage has no effect in some websites

### ISSUE THREAD

**Issue by grybykm** [microsoft/playwright#27325]
### System info
- Playwright Version: 1.38.1
- Operating System: Ubuntu jammy
- Browser: chromium

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

1. Open a page with scroll like here https://www.fundinginstitutional.com/
2. run `expect(page).toHaveScreenshot('screenshot.png', { fullPage: true })`

**Test file (self-contained)**

```js
it('should capture full page screenshot', async ({ page }) => {
  await page.goto('https://www.fundinginstitutional.com/');
  await expect(page).toHaveScreenshot('screenshot.png', { threshold: 0.17, fullPage: true });
});
```

**Steps**
- [Run the test]
- see screenshot

**Expected**

full page screenshot

**Actual**

only viewport is in screenshot

**Comment by yury-s** [comment]
This is working as intended, the content of the page is set to take 100% of the viewport starting from `<main/>` tag and then at some point its scrollable inside the div selected on the screenshot:

<img width="986" alt="image" src="https://github.com/microsoft/playwright/assets/9798949/2f6a2041-1718-4ff1-bc88-f0ccea833bfe">

**Comment by grybykm** [comment]
@yury-s is it somehow possible to capture full screen screenshot taking into account this limitation of playwright?
What are the options to workaround the issue?

**Comment by yury-s** [comment]
You can tamper with the page styles to make the elements take more space but the will likely change the page's layout.
