### ISSUE TITLE
[Question] Child_process using to run Python script in Playwright test

### ISSUE THREAD

**Issue by EldoradoEU** [microsoft/playwright#27323]
### System info
- Playwright Version: v1.38
- Operating System:Windows 11
- Browser: All
- Other info:

Do we have any option to use "child_process.spawn" in Playwright test? I want use it to run python script and wait for the response.

**Comment by yury-s** [comment]
Playwright is just a Node.js program and all standard Node.js APIs including `child_process` are available in your tests, so you can use the as in any other node program.
