### ISSUE TITLE
[BUG] Many flaky tests on Webkit browser on Linux - WebKit encountered an internal error

### ISSUE THREAD

**Issue by javo2222** [microsoft/playwright#27337]
### System info
- Playwright Version: v1.38.1
- Operating System: Ubuntu 20
- Browser: WebKit
- Other info: Doesn't affect when running locally on MacosX. The issue is there after upgrading from 1.37.x to 1.38.x ... We use the tests in our AWS CodeBuild Project and it is running on Linux STANDARD_7_0. We increased the memory but without success. This doesn't seem to be the problem.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
   {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    }
  ]
});
```

**Test file (self-contained)**

```js
it('should visit microsoft', async ({ page }) => {
  await page.goto("https://microsoft.com");
});
```

**Steps**
- Run the test (e.g. in CI)

**Expected**

The test is running successfully without flakyness

**Actual**

The test is failing most of the time. I activated the debugging mode and the log is looking the following:

```
[1A  pw:browser <launching> /root/.cache/ms-playwright/webkit-1908/pw_run.sh --inspector-pipe --headless --no-startup-window +0ms
[1A  pw:browser <launched> pid=15488 +6ms
[1A  pw:browser [pid=15488][err] EGLDisplay Initialization failed: EGL_NOT_INITIALIZED +114ms
[1A  pw:browser [pid=15488][err] Could not determine the accessibility bus address +1ms
[1A  pw:browser [pid=15488][err]  +2s
[1A  pw:browser [pid=15488][err] (MiniBrowser:15493): GLib-GIO-CRITICAL **: 05:56:16.010: g_application_quit: assertion 'G_IS_APPLICATION (application)' failed +0ms
[1A  pw:browser [pid=15488] <gracefully close start> +113ms
[1A  pw:browser [pid=15488] <process did exit: exitCode=0, signal=null> +5ms
[1A  pw:browser [pid=15488] starting temporary directories cleanup +0ms
[1A  pw:browser [pid=15488] finished temporary directories cleanup +1ms
[1A  pw:browser [pid=15488] <gracefully close end> +0ms
[1A  5) [webkit] › my.test.ts:123:13 › test › title › shows things 

  Error: page.goto: WebKit encountered an internal error
  =========================== logs ===========================
  navigating to "https://myurl.com/", waiting until "load"
  ============================================================

     at ../mypath/helper.ts:7

7 |     await page.goto(url);

```

**Comment by chimurai** [comment]
Got the same Webkit issue on github-actions using:

`FROM mcr.microsoft.com/playwright:v1.38.1`

Tests with Firefox and Chromium are running fine.

**Comment by yury-s** [comment]
@javo2222 are you able to reproduce it in our docker image mcr.microsoft.com/playwright:v1.38.1?

**Comment by ValorHeart** [comment]
Hello, Webkit 1908 stopped loading ag-grid at our systems with the following errors:
<img width="984" alt="image" src="https://github.com/microsoft/playwright/assets/61405630/f803e275-1342-4c48-bce8-439387635492">
the ag-grid loads correctly in previous build, as well as no issues found regarding Safari in ag-grid github

**Comment by yury-s** [comment]
@ValorHeart, this seems unrelated, please file a separate issue with the steps how to reproduce it.

**Comment by yury-s** [comment]
@javo2222 @chimurai  We need to be able to reproduce the problem to make this report actionable. Feel free to file a new issue with a reproducible example which we could run locally.

**Comment by danielmicko** [comment]
Hello,

I want to reopen this issue. My Webkit tests are failing when run on GitLab. It is happening while using image mcr.microsoft.com/playwright:v1.38.1-jammy.

The error it logs is following:

`Error: browserType.launch: Browser closed.
    ==================== Browser output: ====================
    <launching> /ms-playwright/webkit-1908/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=1161
    [pid=1161][err] 
    [pid=1161][err] (MiniBrowser:1166): GStreamer-WARNING **: 13:43:49.997: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
    [pid=1161][err] 
    [pid=1161][err] (MiniBrowser:1166): libsoup-ERROR **: 13:43:50.095: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
    [pid=1161][err] /ms-playwright/webkit-1908/pw_run.sh: line 21:  1166 Trace/breakpoint trap   (core dumped) "$MINIBROWSER" "$@"
    [pid=1161] <process did exit: exitCode=133, signal=null>
    [pid=1161] starting temporary directories cleanup
    =========================== logs ===========================
    <launching> /ms-playwright/webkit-1908/pw_run.sh --inspector-pipe --headless --no-startup-window
    <launched> pid=1161
    [pid=1161][err] 
    [pid=1161][err] (MiniBrowser:1166): GStreamer-WARNING **: 13:43:[49](https://git.efabrica.sk/nova/voyo-playwright/-/jobs/1855321#L49).997: External plugin loader failed. This most likely means that the plugin loader helper binary was not found or could not be run. You might need to set the GST_PLUGIN_SCANNER environment variable if your setup is unusual. This should normally not be required though.
    [pid=1161][err] 
    [pid=1161][err] (MiniBrowser:1166): libsoup-ERROR **: 13:43:[50](https://git.efabrica.sk/nova/voyo-playwright/-/jobs/1855321#L50).095: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
    [pid=1161][err] /ms-playwright/webkit-1908/pw_run.sh: line 21:  1166 Trace/breakpoint trap   (core dumped) "$MINIBROWSER" "$@"
    [pid=1161] <process did exit: exitCode=133, signal=null>
    [pid=1161] starting temporary directories cleanup
    ============================================================`

Is there a way you could help me resolve this? Thanks.

**Comment by yury-s** [comment]
> Is there a way you could help me resolve this? Thanks.

This is another issue and it is tracked in https://github.com/microsoft/playwright/issues/27313

**Comment by ahmed-at-mabl** [comment]
@javo2222 Did you find a resolution to this? I'm seeing the same behavior in my environment and it only occurs on upgrade to Playwright 1.38.0, but I'm unable to reproduce it consistently with only Playwright code and an Ubuntu docker image or in Github actions.

**Comment by gkorland** [comment]
I get the error on every run of the examples test

```
$ npx playwright test

Running 6 tests using 4 workers
  1) [webkit] › example.spec.ts:3:5 › has title ────────────────────────────────────────────────────

    Error: page.goto: WebKit encountered an internal error
    Call log:
      - navigating to "https://playwright.dev/", waiting until "load"


      2 |
      3 | test('has title', async ({ page }) => {
    > 4 |   await page.goto('https://playwright.dev/');
        |              ^
      5 |
      6 |   // Expect a title "to contain" a substring.
      7 |   await expect(page).toHaveTitle(/Playwright/);

        at /home/guy/workspace/myproject/tests/example.spec.ts:4:14

  2) [webkit] › example.spec.ts:10:5 › get started link ────────────────────────────────────────────

    Error: page.goto: WebKit encountered an internal error
    Call log:
      - navigating to "https://playwright.dev/", waiting until "load"


       9 |
      10 | test('get started link', async ({ page }) => {
    > 11 |   await page.goto('https://playwright.dev/');
         |              ^
      12 |
      13 |   // Click the get started link.
      14 |   await page.getByRole('link', { name: 'Get started' }).click();

        at /home/guy/workspace/myproject/tests/example.spec.ts:11:14

  2 failed
    [webkit] › example.spec.ts:3:5 › has title ─────────────────────────────────────────────────────
    [webkit] › example.spec.ts:10:5 › get started link ─────────────────────────────────────────────
  4 passed (8.9s)

```

**Comment by ahmed-at-mabl** [comment]
I still haven't found a reproduction outside my specific environment, but I tested on the Playwright 1.38 alpha releases on npm, and found that it was still working with the September 12th release. I think the commit which broke it is [this commit which bumped the Webkit version and added libsoup3 as a dependency run with install-deps](https://github.com/microsoft/playwright/pull/27049/files), but I'm not clear on why.

In the Playwright logs, the first sign something's gone wrong after the `frame.goto` begins is this error message

```
2023-11-15T17:40:34.424Z pw:protocol ◀ RECV {"method":"Target.dispatchMessageFromTarget","params":{"targetId":"page-11","message":"{\"method\":\"Network.loadingFailed\",\"params\":{\"requestId\":\"12.412\",\"timestamp\":14.26676899999984,\"errorText\":\"Load request cancelled\",\"canceled\":true}}"},"browserContextId":"0000000000000002","pageProxyId":"10"}
```

So I think something in libsoup isn't working properly when it attempts to make the HTTP request.

**Comment by MiaInturi** [comment]
@javo2222 @chimurai @ahmed-at-mabl have you found any solution to this problem? I faced this problem too

**Comment by BatthewZ** [comment]
I'm also facing this issue.  Running webkit inside a Debian container, WSL2.  The issues I get typically specifically happens with "Desktop Safari". Chromium and Firefox are fine, Mobile Safari is fine, Mobile Android is fine.

**Comment by programmer24601** [comment]
I'm experiencing the exact same issue as @gkorland on Ubuntu 22.04.4 & VSCode 1.89.0, with default playwright installation options. Interestingly, if I run in debug mode, I get the error message:
```
[pid=24959][err] /home/me/.cache/ms-playwright/webkit-2003/minibrowser-gtk/bin/MiniBrowser: symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE
```
Which led me to [this SO post](https://github.com/ros2/ros2/issues/1406) suggesting it's an issue with vscode. Following the suggestion to run playwright from my OS CLI gets the tests passing.

**Comment by chimurai** [comment]
Solved the issue by following the CI docs: https://playwright.dev/docs/ci

Docs for Playwright Github Actions setup: https://playwright.dev/docs/ci-intro#setting-up-github-actions

1.  using github workflow with Docker image: `mcr.microsoft.com/playwright:v1.44.1-jammy` 
2. `npm ci`
3. `npx playwright install --with-deps `

Upgraded from 1.37 to 1.41.2 successfully with these 3 steps
Have been upgrading every release after 1.41.2 without Webkit issues

---

Maybe good to read the **Breaking Changes** in **1.38.0** if you are migrating from an earlier version.

https://github.com/microsoft/playwright/releases/tag/v1.38.0
