### ISSUE TITLE
[Feature]: Allow a `toHaveAttribute` Overload Where Only the Attribute Is Provided

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/playwright#27341]
There are times where we need to test that an element (or a Custom Web Component) has (or lacks) an attribute, but we don't care about the value of that attribute. Typically, these are "boolean attributes" like `required` or `disabled`. These attributes trigger certain behaviors in the DOM as long as they are present; their values are irrelevant.

Playwright can try to handle these concerns with `toBe*`. For example, it has `toBeDisabled`. However, there _are_ matchers that Playwright will inevitably miss in the interim. (See #19194 and [JestDom.toBeRequired](https://github.com/testing-library/jest-dom#toberequired)). Even if Playwright does add these missing matchers, it _cannot_ account for [Web Components](https://developer.mozilla.org/en-US/docs/Web/API/Web_components). Currently, if a Web Component exposes a _custom_ boolean attribute that drives its functionality, Playwright has no (proper) way to test this use case.

This makes it important to have a `toHaveAttribute` overload that allows the attribute name to be supplied on its own. The `toHaveAttribute` matcher is already supported in [Jest DOM](https://github.com/testing-library/jest-dom#tohaveattribute). [Cypress](https://docs.cypress.io/api/commands/should#Assert-the-anchor-element-has-href-attribute) also supports this use case.

**Comment by yury-s** [comment]
You can already pass either empty string or `/.*/` regex to match this:

```js
test('should work for boolean attributes', async ({ page }) => {
  await page.setContent(`<input id='checkbox' required type='checkbox'></input>`);
  await expect(page.locator('input')).toHaveAttribute('required', '');
  await expect(page.locator('input')).toHaveAttribute('required', /.*/);
});
```

does that work for you?

**Comment by ITenthusiasm** [comment]
@yury-s Unfortunately, not quite. It does work for the positive case, yes. But it doesn't work for the negative case. In the negative case, the test is not that the attribute is not `""`. Rather, the test is that the attribute doesn't appear on the element at all. This is where the requirement for the second argument breaks down because proving that `required` is not `""` doesn't prove that the attribute is not present. So the following becomes necessary:

```ts
await expect(page.getByRole("checkbox")).not.toHaveAttribute("required");
```
---
For clarity, although `toBeRequired` matches Jest DOM Testing Library and resolves #19194, it's not the solution to this problem because that won't fix Web Components. My current problem is related to Web Components, and a boolean attribute that's not related to `required`.

**Comment by yury-s** [comment]
The regex parameter will work for negative conditions and will check that there is not such attribute regardless of its value:

```js
 await expect(page.locator('input')).not.toHaveAttribute('required', /.*/);
```
is it what you're looking for?

**Comment by ITenthusiasm** [comment]
It seems to work in my test, but I'm admittedly a little skeptical. :sweat_smile: Are you 100% sure that this assertion will guarantee that the attribute isn't present under any circumstance? Does this cause `.hasAttribute()` to be checked under the hood? Or is it still looking at the underlying value?

The approach doesn't seem as intuitive from a DX perspective, though it sounds doable. If this is truly the recommended, idiomatic approach, it should probably be documented.

**Comment by yury-s** [comment]
> Are you 100% sure that this assertion will guarantee that the attribute isn't present under any circumstance?

Yes.

> Does this cause .hasAttribute() to be checked under the hood? Or is it still looking at the underlying value?

It is looking at the underlying value.

> If this is truly the recommended, idiomatic approach, it should probably be documented.

Yes, agreed.

There was an attempt to support toHaveAttribute without value in the PRs linked from https://github.com/microsoft/playwright/issues/16517 but it was later reverted, maybe we should reconsider that.

**Comment by ITenthusiasm** [comment]
Okay, that's helpful. If the cleaner syntax was supported, then that would be awesome. But in the meantime, thanks a ton for the existing workaround/solution.

**Comment by ITenthusiasm** [comment]
Thank you @yury-s!
