### ISSUE TITLE
How Can I Open The Browser Full Screen(Macos,Linux,Windows)

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#27343]
Some filter buttons appear in full screen on the frontend of our project. But they do not appear when the screen size is reduced. In order to run my tests, my tests must run in full screen. How can I open the browser in full screen for Macos, Linux and Windows?

### System info
- Playwright Version: [v1.36.0]
- Operating System: [Macos,Linux,Windows]
- Browser: [Chromium(v117.0.5938.92)]

**Comment by yury-s** [comment]
> But they do not appear when the screen size is reduced. In order to run my tests, my tests must run in full screen.

How do they determine if the page is in fullscreen mode or not? If they rely on [requestFullScreen](https://developer.mozilla.org/en-US/docs/Web/API/Element/requestFullscreen) method, you can override it same way as described on [this page](https://playwright.dev/docs/mock-browser-apis#creating-mocks). There is also an open request that is relevant: https://github.com/microsoft/playwright/issues/4046 and

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by MuharremBicici** [comment]
Hello @yury-s  i tried args: ["--start-maximized"], actually it works on windows but it did not work on macos. I could not get why i tried "--window-position=0,0" too, it did not work too. Is there a solve of this problem for all (Macos,Linux,Windows)
