### ISSUE TITLE
PW Test UI does not use project configured EoL but OS EoL

### ISSUE THREAD

**Issue by silentchaostheory** [microsoft/playwright#27342]
### System info
- Playwright Version: [1.37.1]
- Operating System: [Windows 10 Pro 19045.3448]
- Browser: [All]
- Other info: VS Code info
```
Version: 1.82.2 (user setup)
Commit: abd2f3db4bdb28f9e95536dfa84d8479f1eb312d
Date: 2023-09-14T05:55:25.390Z
Electron: 25.8.1
ElectronBuildId: 23779380
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
import type { PlaywrightTestConfig } from '@playwright/test'
import { devices} from '@playwright/test'
import dotenv from 'dotenv'
import { test } from 'node:test'
/*
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */

dotenv.config()

/**
 * See https://playwright.dev/docs/test-configuration.
 */
const config: PlaywrightTestConfig = {
 // globalSetup: require.resolve('./utils/global-setup.ts'),

  
  /* Maximum time one test can run for. */
  timeout: 20 * 5000,
  expect: {
    /**
     * Maximum time expect() should wait for the condition to be met.
     * For example in `await expect(locator).toHaveText();`
     */
    timeout: 5000,
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : 1,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
  //  ['html'],
   // ['json', { outputFile: './playwright-report/test-results.json' }],
    ['dot'],
    ['junit', { outputFile: './playwright-report/results.xml' }],
    ['allure-playwright',{suiteTitle: false}]
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: process.env.QA_URL,

    /*Viewport used for all pages in the context. Nurocor minimum 1366, 786*/
    viewport:{width:1366,height:786},

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    ignoreHTTPSErrors: true,
    /*Populates context with given storage state*/
  //  storageState: './storageStates/storageState_Default.json',

    /*Playwright Test capture screenshots*/
    screenshot: 'only-on-failure',
  },

  /* Configure projects for major browsers */
  
  projects: [
    {
      name: 'setup',
      testMatch: 'playwright/setup/*.setup.ts',
    },
    {
      name: 'teardown',
      testMatch: 'playwright/teardown/*.teardown.ts',
    },
    {
      name: 'allure',
      testMatch: 'playwright/allure/allure.*.ts',
    },
    {
      name: 'chromium',
      dependencies: ['setup'],
      testDir: './tests',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'firefox',
      dependencies: ['setup'],
      testDir: './tests',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      dependencies: ['setup'],
      testDir: './tests',
      use: {
        ...devices['Desktop Safari'],
      },
    },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: {
    //     ...devices['Pixel 5'],
    //   },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: {
    //     ...devices['iPhone 12'],
    //   },
    // },

    /* Test against branded browsers. */
    {
      name: 'Microsoft Edge',
      dependencies: ['setup'],
      testDir: './tests',
      use: {
        channel: 'msedge',
      },
    },
    // {
    //   name: 'Google Chrome',
    //   use: {
    //     channel: 'chrome',
    //   },
    // },

    /* CICD Projects */
    {
      name: 'chromiumCICD',
      testDir: './tests',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'firefoxCICD',
      testDir: './tests',
      use: {
        ...devices['Desktop Firefox'],
      },
    },
    {
      name: 'webkitCICD',
      testDir: './tests',
      use: {
        ...devices['Desktop Safari'],
      },
    },
    {
      name: 'Microsoft EdgeCICD',
      testDir: './tests',
      use: {
        channel: 'msedge',
      },
    },
    
  ],

  /* Folder for test artifacts such as screenshots, videos, traces, etc. */
  outputDir: 'test-results/',

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   port: 3000,
  // },
}

export default config

```

**Test file (self-contained)**

```
//user.setup.ts
import { userInfo } from '../../utils/userInfo'
//...
setup.beforeAll(async ({ browser }) => {
  context = await browser.newContext()
  page = await context.newPage()
  // login form filled with text values here.
})
setup("Verify User's roles", async () => {
  await Promise.all(userInfo.map((task) => // do something with task here ))
})
setup.afterAll(async () => {
  await context.close()
})
```
```
//userInfo.ts
export const userInfo = [
  {
    username:  'username',
    password: 'password',
    // other stuff as needed.
  }]
```

**Steps**
- Setup project files with EoL of LF and VSCode set Files: EoL configures to LF 
- Add tests to run after setup, simple assertions should be enough
- Start Playwright test UI from the project's root directory using Powershell: 
example: PS C:\Users\...\git-workspace\playwright-e2e> npx playwright test --ui'
- Observe the OUTPUT section of the Playwright Test UI
For Comparison:
- Install the Playwright Test for VSCode extension and run the same test script or setup

**Expected**
The EoL configure for VSCode, or any IDE, and its terminal should be used for the EoL of the Playwright UI **OR** a configuration options should be added to the playwright.config.ts properties for End of Line. This is the behavior observed for the VSCode extension.

**Actual**
The System default EoL, CRLF, is expected, resulting in the files with LF-only appearing to have no end when parsed. This makes development teams with a mixture of OS's vulnerable to erroneous test failure due to mixed file EoL behavior.

**Comment by silentchaostheory** [comment]
——————————————————————————————————————————————————————————————————  [1:57:15 PM]
Running 4 tests using 1 worker
F···

  1) [setup] › playwright\setup\auth.setup.ts:8:6 › Authenticate with different user roles ─────────

    Error: file data stream has unexpected number of bytes

      43 |     })
      44 |     .toBeTruthy()
    > 45 |   await context.close()
         |                 ^
      46 | }
      47 |

        at login (C:\Users\Ariel\git-workspace\playwright-e2e\playwright\setup\auth.setup.ts:45:17)
        at C:\Users\Ariel\git-workspace\playwright-e2e\playwright\setup\auth.setup.ts:13:9
        at C:\Users\Ariel\git-workspace\playwright-e2e\playwright\setup\auth.setup.ts:10:3

    attachment #1: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results\playwright-setup-auth.setup.ts-Authenticate-with-different-user-roles-setup\test-failed-1.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #2: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results\playwright-setup-auth.setup.ts-Authenticate-with-different-user-roles-setup\test-failed-4.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #3: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results\playwright-setup-auth.setup.ts-Authenticate-with-different-user-roles-setup\test-failed-2.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #4: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results\playwright-setup-auth.setup.ts-Authenticate-with-different-user-roles-setup\test-failed-5.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

    attachment #5: screenshot (image/png) ──────────────────────────────────────────────────────────
    test-results\playwright-setup-auth.setup.ts-Authenticate-with-different-user-roles-setup\test-failed-3.png
    ────────────────────────────────────────────────────────────────────────────────────────────────

  1 failed
    [setup] › playwright\setup\auth.setup.ts:8:6 › Authenticate with different user roles ──────────
  3 passed (1.6m)

**Comment by yury-s** [comment]
You may be able to solve it with [git setting](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#global-settings-for-line-endings) `core.autocrlf`, was that considered?

If it does not help, can you attach relevant data and code that fail?

**Comment by silentchaostheory** [comment]
I tried adding the configuration setting, Is there a debug option for the UI Mode? Maybe it can echo the configured EoL being set on startup.

**Comment by silentchaostheory** [comment]
I updated NodeJS to 18.18.0, ran npm ci, and reinstalled all browsers. That seemed to resolved the issue. I don't know if it is because the node modules rebuilt or a file stream handler was closed by changing the Node version. If I see the issue again, I will provide more information.
