### ISSUE TITLE
[Feature] Timeout multiplier 

### ISSUE THREAD

**Issue by mohsen1** [microsoft/playwright#27347]
In many places we rather increase or decrease the timeout _relative_ to the timeout in the configuration. For instance if our timeout is configured to `60_000`, we do `test.describe.configure({timeout: 90_000 })` or `test.setTimeout(120_000)`.

It would be more ideal if we could say "make the timeout for this configure section use 1.5x of the configuration timeout":

```ts
test.describe.configure({ timeout: { multiplier: 1.5 } })
 ```

This is just one suggestion for how the API can look like. There are many other ways this can be designed. 

--- 
This is essentially an API sugar for:

```ts
test.describe.configure({timeout: test.info().timeout * 2})
```

**Comment by yury-s** [comment]
There is [`test.slow()`](https://playwright.dev/docs/api/class-test#test-slow-1) method which lets you give 3x time to the tests. For a more fine-grained control over the timeouts you can define a bunch of interdependent constants and use them in the config and test files that need to override the default timeout.

Closing this issue as we're not planning to implement this as existing API covers common cases and there is an existing solution for more rare scenarios.
