### ISSUE TITLE
[Feature] WebSocket messages in Trace Files

### ISSUE THREAD

**Issue by infinitejest69** [microsoft/playwright#27346]
Hi i can output the WebSocket's and message frames currently to a separate log file but it would be really useful if i could see them in the timeline within a trace file. sometimes tracing a failure requires seeing the websocket message that might contain an ID to something with App insights. 
Current process is a bit slow to match timestamps from logs with tests that run in parallels to get the ID or
re-running with devtools open, hoping the failure is not transient and pausing to capture the websocket message from browser or log file at the right time. having it in trace files saves me all of this as i can grab the trace from pipeline artifacts and get the ID or pass trace file into the bug and developers can look at it.

Hopefully i am not being dumb and there is not already a way to push these events into a trace file ?

**Comment by yury-s** [comment]
This is not possible today. I'll keep the request open to collect more feedback.

**Comment by dimkin-eu** [comment]
please-please-please implement it :)
for now we added an ugly console log, but it would be so nice to add it to the timeline ( there is same for `framereceived` )

```js
export const attachOutgoingWSLogging = (page: Page, matcher = "", marker = "user"): void => {
    page.on("websocket", (ws) => {
        ws.on("framesent", (d) => {
            try {
                const messageType = JSON.parse(d.payload as string)._t as string
                if (messageType.match(matcher)) {
                    console.log(`\n${marker} sent ${new Date(Date.now()).toISOString()} \n${d.payload}`)
                }
            } catch (e: unknown) {
                console.log("Shouldn`t happen while sending ws")
            }
        })
    })
}
```

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/10996
