### ISSUE TITLE
[BUG] blob reporter does  apply the `outputFolder` setting when used

### ISSUE THREAD

**Issue by chrisshaddad** [microsoft/playwright#27357]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS 13.3.1]
- Browser: [Chromium]
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
...
  reporter: [
    [
      'html',
      {
        open: 'never',
        outputFolder: path.join(__dirname, 'e2e/playwright-report'),
      },
    ],
    ['line'],
    [
      'blob',
      {
        open: 'never',
        outputFolder: path.join(__dirname, 'e2e/playwright-report-blob'),
      },
    ],
  ],
...
```

**Steps**
Run any test case using the above provided config

**Expected**

Expect the blob report to be created in the `e2e/playwright-report-blob` folder.

**Actual**

The blob reporter folder gets created in the same folder as `playwright.config.ts` inside a folder called `blob-report`.

**Comment by yury-s** [comment]
The option is called `outputDir` in [blob reporter](https://playwright.dev/docs/test-reporters#blob-reporter), so it should be:

```js
    [
      'blob',
      {
        open: 'never',
        outputDir: path.join(__dirname, 'e2e/playwright-report-blob'),
      },
    ],
```
