### ISSUE TITLE
[BUG] playwright errors out upon yarn installation via github actions

### ISSUE THREAD

**Issue by avijaywargiya-ces** [microsoft/playwright#27355]
### System info
- Playwright Version: [v1.29.2]
- Operating System: [Ubuntu 20]

### Issue

We have a next.js project which uses playwright to run the storybook tests. The project build is built using github actions. The first step to it is installing the dependencies using yarn install. Everything was fine until yesterday (28 Sep), but today, the build step began failing, with the following error

<img width="963" alt="Screenshot 2023-09-29 at 11 59 48 AM" src="https://github.com/microsoft/playwright/assets/128119536/c59c02c6-9ef1-41e6-a8fe-f891449d96e8">

To debug further, I performed installation with --verbose to end up finding this.

<img width="1440" alt="Screenshot 2023-09-29 at 12 02 09 PM" src="https://github.com/microsoft/playwright/assets/128119536/1af93b66-e0eb-4c8b-87bb-606d594b2fcc">

Any help on resolving the issue would be greatly appreciated.

**Comment by yury-s** [comment]
Can you share a reproducible example and steps which we could try locally?

**Comment by avijaywargiya-ces** [comment]
@yury-s, the issue isn't reproducible on local. It is only failing on github actions CI.

**Comment by yury-s** [comment]
We need a repro to take an action on this. The stack trace on the screenshot doesn't tell us much. If it's happening reliably on CI it should be possible to repro in a docker environment.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
