### ISSUE TITLE
[BUG] Using Firefox creates shortcut `Nightly Private Browsing` in Start Menu

### ISSUE THREAD

**Issue by anthonyvdotbe** [microsoft/playwright#27359]
### System info
- Playwright Version: 1.38.1
- Operating System: Windows 11
- Browser: Firefox
- Other info: n/a

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  projects: [
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    }
  ]
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Expect a title "to contain" a substring.
  await expect(page).toHaveTitle(/Playwright/);
});

test('get started link', async ({ page }) => {
  await page.goto('https://playwright.dev/');

  // Click the get started link.
  await page.getByRole('link', { name: 'Get started' }).click();

  // Expects page to have a heading with the name of Installation.
  await expect(page.getByRole('heading', { name: 'Installation' })).toBeVisible();
});
```

**Steps**
- [Run the test]

**Expected**

No shortcuts are created in the Windows Start Menu.

**Actual**

A shortcut is created at `C:\Users\...\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Nightly Private Browsing.lnk`.
Its target is `C:\Users\...\AppData\Local\ms-playwright\firefox-1424\firefox\private_browsing.exe`

**Comment by yury-s** [comment]
This is how Firefox does it, regardless of Playwright. There is probably a pref in Firefox that disables this behavior.

**Comment by anthonyvdotbe** [comment]
@yury-s I've created a PR
