### ISSUE TITLE
[BUG] Playwright does not split shard evenly when using sharding

### ISSUE THREAD

**Issue by chrisshaddad** [microsoft/playwright#27356]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS 13.3.1]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

or

**Config file**

```js
// playwright.config.ts
export default defineConfig({
  projects: [
    {
      name: 'setup',
      testMatch: /global.setup\.ts/,
      teardown: 'cleanup',
    },

    {
      name: 'cleanup',
      testMatch: /global.teardown\.ts/,
    },

    {
      name: 'logged in chromium',
      use: {
        ...devices['Desktop Chrome'],
        storageState: STORAGE_STATE,
        permissions: ['clipboard-read', 'clipboard-write'],
      },
      testMatch: '**/loggedin/*.spec.ts',
      dependencies: ['setup'],
    },

    {
      name: 'logged out chromium',
      use: {
        ...devices['Desktop Chrome'],
        permissions: ['clipboard-read', 'clipboard-write'],
      },
      testMatch: ['**/loggedout/*.spec.ts'],
    },
  ]
});
```

**Steps**
Run `npx playwright test --shard=1/4`

**Expected**

Expect the test shards to be evenly split the total number of tests or provide some clarity on how sharding is determined, or possibly provide more control over sharding, for more effective test splits.

**Actual**

Currently I have tests unevenly split between different files based on context in the project, for example, a test file for books specifically `loggedin/books.spec.ts` handles a ton of tests (book creation, update, delete, tagging etc...), another for the landing page `loggedout/landing.spec.ts` that verifies some content on that page that has only a couple of test.

When I shard my tests, I'm getting the tests unevenly split between shards, one shard is getting 7 tests, while another gets 42, playing around with the number of shards I also got an instance where I didn't get any tests on a shard.

I also tried splitting the tests suites from the `loggedin/books.spec.ts` file into another one `loggedin/books2.spec.ts` and that seemed to have changed the test shard split into something more even.

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/17969
