### ISSUE TITLE
[BUG] Playwright 1.36 overides jest expect globals unintentionally

### ISSUE THREAD

**Issue by mastrzyz** [microsoft/playwright#27361]
### System info
- Playwright Version: 1.36.2 ( Does not repro on 1.35 )
- Operating System: Windows 11
- Browser: All
- Other info:

#### Package.json 
```json
{
  "name": "playwright_sandbox",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {},
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "@playwright/test": "^1.36.2",
    "@types/jest": "^29.5.5",
    "@types/node": "^20.7.1",
    "jest": "^28.1.3"
  }
}
```

#### Subject under test : 

```ts
const { chromium } = require("@playwright/test");
async function sum(a, b) {
  return a + b;
}
module.exports = sum;
```

#### Jest Test

```
const regression = require("./regression");

test("adds 1 + 2 to equal 3", async () => {
  const result = await regression(1, 2);
  expect(result).not.toEqual({"foo":2});
});
```

**Steps**
- Run the jest test
- `yarn jest`

**Expected**

I expect the test to work correctly and to just return a simple pass

**Actual**
```
 FAIL  ./regression.test.ts
  ● adds 1 + 2 to equal 3

    TypeError: this.customTesters is not iterable

      3 | test("adds 1 + 2 to equal 3", async () => {
      4 |   const result = await regression(1, 2);
    > 5 |   expect(result).not.toEqual({"foo":2});
        |                      ^
      6 | });
      7 |

      at Object.toEqual (regression.test.ts:5:22)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        0.971 s, estimated 1 s

```

Upon further digging I See for some reason some of the jest globals have the expect library overriden with the Playwright library
![image](https://github.com/microsoft/playwright/assets/37447884/dc9ebac8-404f-4ced-896a-3194dd3cb47d)

Does not repro with Jest 29.

**Comment by pavelfeldman** [comment]
I can repro. Our support for @playwright/test matchers in Jest environment has a subtle limitation: underlying versions of expect should match. Expect + jest integration relies on implementation detail of each other, so when older Jest and newer Expect are used, things fall apart.

**Comment by bharat7gupta** [comment]
> underlying versions of expect should match.

@pavelfeldman  Does this mean we would need to upgrade jest as well if we are upgrading playwright. I am currently upgrading to playwright version 1.41 and facing this issue with error message `TypeError: this.customTesters is not iterable`

> Our support for @playwright/test matchers in Jest environment has a subtle limitation

Curious to understand why we have such limitation and the best way to resolve this.
