### ISSUE TITLE
[Feature] VSCode extension: start UI Mode form PLAYWRIGHT menu and minor enhancements

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#27368]
Just for usability I wish to be able run UI Mode from this extension.

Enhancements:
- We have both in TEST EXPLORER and PLAYWRIGHT menu option `Show output` | `Reveal test output option`  is that not redundant? 
![obraz](https://github.com/microsoft/playwright/assets/72373858/c084f6e7-adb9-4ea6-b7bb-8f5b005fbdea)

- It would be nice to have Show Report in PLAYWRIGHT menu.
- Showing Trace Viewer while debug https://github.com/microsoft/playwright/issues/23870

**Comment by yury-s** [comment]
This is already possible with 'Show trace viewer' option, folding this into https://github.com/microsoft/playwright/issues/22309.

As for the show report - VSCode already shows test run results in the "Test explorer".
