### ISSUE TITLE
[Feature] Restart button for UI Mode

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#27367]
When playwright.config.ts is edited while running UI Mode, UI Mode needs restart to load changes in config (see https://github.com/microsoft/playwright/issues/27366)
Restarting UI Mode means closing UI Mode and running again command to start UI Mode. 
User need to remember about this when editing config because UI Mode keeps old config while is able to recognize tests changes.

To allow user quickly restart UI Mode dedicated button, menu action will be nice enhancement.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/27366
