### ISSUE TITLE
[Feature] Add an error code for "Execution context was destroyed, most likely because of a navigation"

### ISSUE THREAD

**Issue by nikitaeverywhere** [microsoft/playwright#27374]
[Here's the error message](https://github.com/search?q=repo%3Amicrosoft%2Fplaywright+%22most+likely+because+of+a+navigation%22&type=code) that happens when JavaScript execution on a page (in my case, using `page.evaluate`) fails due to a page navigation event.

```txt
page.evaluate: Execution context was destroyed, most likely because of a navigation.
```

Right now, it appears to be constructed as a [simple JavaScript Error()](https://github.com/microsoft/playwright/blob/ac9d1ec421b572d6ac23f1dd169f292a1108e102/packages/playwright-core/src/server/chromium/crExecutionContext.ts#L124), while it would be nice to distinct this error from others.

My use-case is: I'm building a prerendering engine, which needs to also execute arbitrary async init JavaScript on the page. Whenever the navigation event happens and hence JS errors, I want to handle that specific case [and execute init JavaScript again but in a new context]. The key is, **I need to distinct this specific "context destroyed" error from any other possible JS errors**.

I'd suggest to extend [errors namespace](https://github.com/microsoft/playwright/blob/ac9d1ec421b572d6ac23f1dd169f292a1108e102/utils/generate_types/overrides.d.ts#L202) with one more "JS context destroyed" error so it can be distinguished. For example (impl is up to you):

```ts
import { errors } from "playwright-chromium";

// 

let result: any = null;
try {
  result = await page.evaluate(async () => { /* ... */ });
} catch (e) {
  if (e instanceof errors.JsContextDestroyedError) { // For instance
    // Handle a page redirect (in my case, keep invoking JavaScript in a new page context)
  } else {
    // Handle a normal JavaScript error
  }
}
```

Right now the workaround for me is to **parse the javascript error message** to detect that it's exactly this error, which could have been replaced with a nice custom error check. I.e. the ugly

```ts
let initialUrl = page.url();
try {
  result = await page.evaluate(async () => { /* ... */ });
} catch (e: any) {
  if (e.message.includes('because of a navigation')) {
    // Handle
  }
}
```

P.S. Comparing the `page.url()` in the `catch` clause to the previous URL may fail (`&& page.url() !== initialUrl` etc), as the page may not be redirected yet while the context is already destroyed.

**Comment by yury-s** [comment]
If you want to distinguish your errors from playwright errors you can wrap your code in a try/catch:

```js
try {
  const { result, error } = await page.evaluate(async () => { 
    try {
      ...
      return { result: ... };
    } catch (e) {
       return { error: e };
    }
  });
  if (error) {
    // Handle a normal JavaScript error
  }
} catch (e) {
    // Handle a page redirect (in my case, keep invoking JavaScript in a new page context)
}
```

will that work?

**Comment by nikitaeverywhere** [comment]
@yury-s smart move, haha. In my case, likely yes. But this fix won't survive the non-breaking extension of `page.evaluate` that may ever happen, it it errors with something else. For example, if you will finally add a timeout to `page.evaluate` #13253.

**Comment by yury-s** [comment]
I'd argue that even with timeout option it would be a playwright error rather than user error. In any case, there are no plans to extend the evaluate API and the workaround seems to do the job, so closing this issue.

**Comment by nikitaeverywhere** [comment]
I meant that you still won’t be able to distinguish a timeout and a page
navigation error without parsing the error message.
