### ISSUE TITLE
[BUG] Cannot read property 'message' of undefined - When launching browser

### ISSUE THREAD

**Issue by skreeeeee** [microsoft/playwright#2738]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Linux (Ubuntu 16.04.6 LTS)
- Node version: 12.15.1
- Browser: Firefox
- Extra: -

**Code Snippet**

```javascript
const { firefox } = require('playwright');

// ...
const browser = await firefox.launchPersistentContext(`./.data/${clientName}/`, _.merge(this.config, configurations));
const page = await browser.newPage({
	userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36',
});
page.setDefaultTimeout(timeout);
await page.route('**/*', route => {
	if(route.request().resourceType() == 'stylesheet' || route.request().resourceType() == 'font' || route.request().resourceType() == 'image') {
		route.abort();
	}
	else {
		route.continue();
	}
});
// ...
```

**Describe the bug**

Here's the error I got:
```
5|bri      | TypeError: Cannot read property 'message' of undefined
5|bri      |     at ProgressController.run (/mime/workspace/project/node_modules/playwright/lib/progress.js:85:51)
5|bri      |     at processTicksAndRejections (internal/process/task_queues.js:94:5)
```

**Comment by WENFZ** [comment]
could you please tell how you solve the issue finally?

**Comment by arjun27** [comment]
@wenfz, can you share more about the OS you're using? Firefox requires Ubuntu 18.04 and above.

**Comment by WENFZ** [comment]
> @WENFZ, can you share more about the OS you're using? Firefox requires Ubuntu 18.04 and above.
CentOS Linux release 7.3.1611 (Core)

**Comment by arjun27** [comment]
thanks. I'm afraid we haven't tested running on CentOS. I would recommend following this to debug the issue with browser launches: https://playwright.dev/#version=master&path=docs%2Fci.md&q=debugging-browser-launches

**Comment by WENFZ** [comment]
thank you for your reply,maybe i should switch to other browsers.
