### ISSUE TITLE
[Question] Implementing custom reporter, Suite title is undefined

### ISSUE THREAD

**Issue by ZhouZhengCarlos** [microsoft/playwright#27389]
Hi, currently Im trying to implement a custom-reporter and I found that my suite title is giving an undefined title

test.spec.js:

```
test.describe("describe title", () => {
...tests
})
```

custom-reporter.ts:

    onBegin(config: FullConfig, suite: Suite) {
      console.log('============== Suites executed ==============');
      suite.suites.forEach( suite=> console.log(suite.title));
   

title from suite.suites are giving me an undefined value, I was expecting to see the describe title there

Am I missing something?

Thanks!

**Comment by pavelfeldman** [comment]
That's because the suites are nested. Call `.suites` on your file suites.
