### ISSUE TITLE
[Feature] Change host for components tests

### ISSUE THREAD

**Issue by oskarkivra** [microsoft/playwright#27382]
> **TL;DR;** I would like to set a custom host for components tests to be able to run the browser on a different host.

## Background and Reasoning

We utilize component testing with Playwright for capturing visual snapshots. Currently, we execute Playwright within a Docker container to ensure consistent snapshots. However, this approach is cumbersome and time-consuming. Hence, we are exploring alternative methods for test execution. One possibility is to run only the browser in a container, such as with [browserless.io](https://www.browserless.io/). This approach could also be beneficial for services like Browserstack or Sauce Labs.

However, given that the browser runs in a Docker container or another host while Vite runs on our host, we need a mechanism to instruct Playwright to use a hostname other than "localhost." Additionally, we need to inform Vite to accept hosts other than "localhost" during component tests. This is not an issue for "normal" tests.

## Proposed Solution

Introduce a new configuration option that allows specifying the host for component tests. One approach could be to make `@playwright/experimental-ct-*` respect [`use.baseURL`](https://playwright.dev/docs/api/class-testoptions#test-options-base-url) or add a new value under `ctViteConfig`.

```ts
import { defineConfig } from '@playwright/experimental-ct-react';

export default defineConfig({
  use: {
    ctViteConfig: {
      host: 'host.docker.internal' // or any ip
      // ...
    },
  },
});
```

When `use.ctViteConfig.host` is defined, Playwright would set that value as [`server.host`](https://vitejs.dev/config/server-options.html#server-host) for Vite. Playwright would then run the tests against `http://{use.ctViteConfig.host}:{use.ctViteConfig.ctPort}`.

Would this make sense? I can create a PR.

Thanks.

**Comment by sand4rt** [comment]
Hi @oskarkivra, this was recently added: https://github.com/microsoft/playwright/pull/27295

**Comment by oskarkivra** [comment]
@sand4rt Wow. Thanks. I hope it will be a new release soon so I can take part of this.

**Comment by sand4rt** [comment]
@oskarkivra you should be able to use one of the alpha releases if you need this right away:

https://www.npmjs.com/package/@playwright/experimental-ct-react?activeTab=versions

**Comment by oskarkivra** [comment]
Thanks! Didn't know there was alpha releases. 
It isn't needed right away but would be fun to try
