### ISSUE TITLE
[BUG] Tests from different folder are not reflecting in playwright test UI mode

### ISSUE THREAD

**Issue by Saikrishna-zebra** [microsoft/playwright#27402]
### System info
- Playwright Version: [v1.38]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: I have 2 folders in project under tests api and UI when I execute the command npx playwright test --ui, it is loading tests only from the API folder and not loading the tests from UI folder
- 
![image](https://github.com/microsoft/playwright/assets/89917207/e59d5308-6afc-492c-a066-254860a3c767)

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by debs-obrien** [comment]
was not able to reproduce. works fine my end. Have a check in your config file under projects as in UI mode it is filtered by untitled so that could be the issue.

**Comment by Saikrishna-zebra** [comment]
> was not able to reproduce. works fine my end. Have a check in your config file under projects as in UI mode it is filtered by untitled so that could be the issue.

Thank you, It works even for me now. I have not done anything specifically, just removed the directory and the same back.
![image](https://github.com/microsoft/playwright/assets/89917207/d1a621ea-f964-48e4-9e13-6cbed76bf0b5)
 
![image](https://github.com/microsoft/playwright/assets/89917207/0c860521-c506-4983-a5ec-8925039df203)

Please close the bug. Thank you for the quick response.
