### ISSUE TITLE
[BUG] Aw Snap  status_breakpoint When using selectOption on chrome

### ISSUE THREAD

**Issue by mikicymulate** [microsoft/playwright#27405]
### System info
- Playwright Version: [1.38.0 + 1.38.1 + 1.39.0-alpha-oct-2-2023]
- Operating System: [Windows 11,Windows 10]
- Browser: [ Chromium]
- Other info:

Aw Snap  status_breakpoint when using selectOption on chrome

as a continuation from bug :  https://github.com/microsoft/playwright/issues/27363

![image](https://github.com/microsoft/playwright/assets/106581694/0aa572d3-8f2c-47d7-8129-0f181ee410f9)
![image](https://github.com/microsoft/playwright/assets/106581694/be2eee89-26db-4728-9539-5fbc824040e9)

DEBUG=pw:browser

`
"C:\Program Files\nodejs\npm.cmd" run test:eksstg

> e2e-automation@1.0.0 test:eksstg
> set DEBUG=pw:browser && cross-env NODE_ENV=eksstg npx playwright test ***.spec.ts

Running 1 test using 1 worker
… ****
  pw:browser <launching> C:\Users\MichaelBehnam\AppData\Local\ms-playwright\chromium_with_symbols-1080\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkSer
viceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-
pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowse
rClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ip
c-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --user-data-dir=C:\Users\MICHAE~1\AppData\Local\Temp\playwright_chromiumdev_profile-JgRDij --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=31108 +6ms                                                                                                                                                                                               
  pw:browser [pid=31108][err] [31108:16044:1003/140606.303:ERROR:policy_logger.cc(154)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled. +253ms
  pw:browser [pid=31108][err] [31108:12236:1003/140609.969:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER): +4s
  pw:browser [pid=31108][err] ERROR: Couldn't read tbsCertificate as SEQUENCE +1ms                                                                                                                                                   
  pw:browser [pid=31108][err] ERROR: Failed parsing Certificate +0ms                                                                                                                                                                 
  pw:browser [pid=31108][err]  +0ms                                                                                                                                                                                                  
Test name: FULL_KILL_CHAIN_SCENARIOS_05 run email with link attack on Service @Apt101_team_sanity @sanityForAllModules @aptScenarios @jenkins_aptScenarios @jenkins_Attacks @smokeTestAgent

  pw:browser [pid=31108][err] [31108:12236:1003/140621.221:ERROR:cert_issuer_source_aia.cc(36)] Error parsing cert retrieved from AIA (as DER): +11s
  pw:browser [pid=31108][err] ERROR: Couldn't read tbsCertificate as SEQUENCE +0ms                                                                                                                                                   
  pw:browser [pid=31108][err] ERROR: Failed parsing Certificate +1ms                                                                                                                                                                 
  pw:browser [pid=31108][err]  +0ms                                                                                                                                                                                                  
  pw:browser [pid=31108][err] [31108:16044:1003/140630.706:ERROR:device_event_log_impl.cc(225)] [14:06:30.705] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2) +9s
  pw:browser [pid=31108][err] [31108:16044:1003/140630.710:ERROR:usb_descriptors.cc(141)] Failed to read length for configuration 1. +4ms                                                                                            
  pw:browser [pid=31108][err] [31108:16044:1003/140630.710:ERROR:usb_descriptors.cc(100)] Failed to read all configuration descriptors. Expected 2, got 1. +0ms                                                                      
  pw:browser [pid=31108][err] [31108:16044:1003/140630.710:ERROR:device_event_log_impl.cc(225)] [14:06:30.710] USB: usb_device_win.cc:95 Failed to read descriptors from \\?\usb#vid_0bda&pid_8153#001000001#{a5dcbf10-6530-11d2-901f-00c04fb951ed}. +1ms
  pw:browser [pid=31108][err]  +42s
  pw:browser [pid=31108][err]  +0ms                                                                                                                                                                                                  
  pw:browser [pid=31108][err] # +0ms                                                                                                                                                                                                 
  pw:browser [pid=31108][err] # Fatal error in , line 0 +0ms                                                                                                                                                                         
  pw:browser [pid=31108][err] # Check failed: handler. +0ms                                                                                                                                                                          
  pw:browser [pid=31108][err] # +0ms                                                                                                                                                                                                 
  pw:browser [pid=31108][err] # +2ms                                                                                                                                                                                                 
  pw:browser [pid=31108][err] # +0ms                                                                                                                                                                                                 
  pw:browser [pid=31108][err] #FailureMessage Object: 00000036CF3FC800  IsSandboxedProcess [0x00007FFEA812BB02+1122690] +15ms                                                                                                        
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA81359D2+1163346] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA8A14C57+10466007] +1ms                                                                                                                                                
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA88AE70D+8998285] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA61838AF+355103] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAE298D85+78741077] +0ms                                                                                                                                               
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAE39D0B0+79806848] +0ms                                                                                                                                               
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAE2C2594+78911076] +0ms                                                                                                                                               
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAE294C1B+78724331] +0ms                                                                                                                                               
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA59F3F43+20197027] +0ms                                                                                                                                                        
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA59F4B85+20200165] +0ms                                                                                                                                                        
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA59F4DE3+20200771] +0ms                                                                                                                                                        
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA5A20D51+20380849] +0ms                                                                                                                                                        
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA5A20B93+20380403] +0ms                                                                                                                                                        
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA61CC6EC+653660] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA61CBE6A+651482] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA6173913+289667] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA61E882B+768667] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA61C39E0+617552] +0ms                                                                                                                         
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAAB4E76B+20764731] +1ms                                                                                                                                               
  pw:browser [pid=31108][err]   sqlite3_dbdata_init [0x00007FFEAAB4E5C6+20764310] +0ms                                                                                                                                               
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA76BF4E5+22619989] +0ms                                                                                                                       
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA83BAACE+3805518] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FFEA929D8D2+1759362] +0ms                                                                                                                                                  
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA83BC189+3811337] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA84B86CD+4844877] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA83BDAD8+3817816] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA81598D0+1310544] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FFEA910C6AB+116315] +0ms                                                                                                                                                   
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FFEA910C034+114660] +0ms                                                                                                                                                   
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FFEA911D295+184901] +0ms                                                                                                                                                   
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FFEA910D1B4+119140] +0ms                                                                                                                                                   
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA8178D6B+1438699] +0ms                                                                                                                                                 
  pw:browser [pid=31108][err]   IsSandboxedProcess [0x00007FFEA8EC7252+15390930] +0ms                                                                                                                                                
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA7A24BA5+26181141] +0ms                                                                                                                       
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA7A25905+26184565] +0ms                                                                                                                       
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA7A24159+26178505] +0ms                                                                                                                       
  pw:browser [pid=31108][err]   CrashForExceptionInNonABICompliantCodeRange [0x00007FFEA7A243F4+26179172] +0ms                                                                                                                       
  pw:browser [pid=31108][err]   ChromeMain [0x00007FFEA46B137E+734] +0ms                                                                                                                                                             
  pw:browser [pid=31108][err]   GetPakFileHashes [0x00007FF69D402993+6547] +4ms                                                                                                                                                      
  pw:browser [pid=31108][err]   GetPakFileHashes [0x00007FF69D401A83+2691] +0ms                                                                                                                                                      
  pw:browser [pid=31108][err]   GetHandleVerifier [0x00007FF69D57BB12+964962] +0ms                                                                                                                                                   
  pw:browser [pid=31108][err]   BaseThreadInitThunk [0x00007FFF9AE7257D+29] +6ms                                                                                                                                                     
  pw:browser [pid=31108][err]   RtlUserThreadStart [0x00007FFF9C0EAA68+40] +12ms
  pw:browser [pid=31108] <gracefully close start> +14s
  pw:browser [pid=31108] <process did exit: exitCode=0, signal=null> +124ms
  pw:browser [pid=31108] starting temporary directories cleanup +0ms                                                                                                                                                                 
  pw:browser [pid=31108] finished temporary directories cleanup +23ms
  pw:browser [pid=31108] <gracefully close end> +0ms                                                                                                                                                                                 
  
    Error: locator.selectOption: Target crashed
    =========================== logs ===========================
    waiting for locator('xpath=//option[text()=\'Select Target\']/parent::select')
      locator resolved to <select class="form-control attack-select-box apt">…</select>
      selecting specified option(s)
    element was detached from the DOM, retrying
    ============================================================

Process finished with exit code 1

`

The same code works in firefox

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
   {
            name: "e2e_automation",
            use: {
                channel: "chromium-with-symbols",
                ...devices["Desktop Chrome"],
                acceptDownloads: true,
                viewport: {width: 1920, height: 937},
                launchOptions: {
                    chromiumSandbox: true,
                    devtools: false
                }
            }
        }
  ]
});
```

**Test file (self-contained)**

```js
await mainSelect.selectOption({index: i});```

**Comment by mikicymulate** [comment]
@yury-s

**Comment by nitzanshuker** [comment]
Also ran into this issue lately

**Comment by mreouven** [comment]
also

**Comment by subabu-cmc** [comment]
Same issue for me. Trace file attached.
[2c7c7cce5abfb74be3d2ef570db1ec8b0c206b8c.zip](https://github.com/microsoft/playwright/files/12793034/2c7c7cce5abfb74be3d2ef570db1ec8b0c206b8c.zip)

**Comment by pavelfeldman** [comment]
Could everyone please submit their:
- Version of Playwright
- OS
- Headless vs headed
- Any additional flags they pass to chromium? (like channel, sandbox, etc)

**Comment by mikicymulate** [comment]
@pavelfeldman 
Version of Playwright - **1.38.0 + 1.38.1 + 1.39.0-alpha-oct-2-2023**
OS - **Windows 11,Windows 10**
Headless vs headed - **headed** 
Any additional flags  -              **use: {
                channel: "chromium-with-symbols",  /  channel: "chrome",
                ...devices["Desktop Chrome"],
                acceptDownloads: true,
                viewport: {width: 1920, height: 937},
                launchOptions: {
                    chromiumSandbox: true,
                    devtools: false
                }
            }**

**Comment by subabu-cmc** [comment]
@pavelfeldman
Version of Playwright - 1.38.0 
OS - Windows 10 Enterprise
Headless vs headed - Headless 
Any additional flags -   use: {
    actionTimeout: 30 * 1000,
    channel: "chrome",
    screenshot: {
      mode: "only-on-failure",
      fullPage: true,
    },
    trace: "on-first-retry",
    userAgent:
      "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36",
  },

**Comment by akawebstrom1** [comment]
Encountered this issue multiple times!!

**Comment by pavelfeldman** [comment]
@mikicymulate @subabu-cmc can I ask you to go to `chrome://crashes` in your Chrome, make sure those crash reports are submitted and paste crash ids here so that we could coordinate it with the Chrome team?

**Comment by mikicymulate** [comment]
@pavelfeldman 
chrome - 117.0.5938.132 
"@playwright/test": "1.38.1"

![image](https://github.com/microsoft/playwright/assets/106581694/546bfe1a-6bde-48b6-9423-cbd2491c8751)


<html>
<body>
<h3 class="capture-time" style="margin: 0.75em 0px; font-size: 12px; color: rgb(160, 160, 160); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Crash from Thursday, October 5, 2023 at 8:03:36 AM</h3>

Status: | Not uploaded
-- | --
Local Crash Context: | d848c723-325d-4465-be2d-aee88a48d6da


</body>
</html>

**Comment by mikicymulate** [comment]
@pavelfeldman 

chrome : Version 117.0.5938.132 (Official Build) (64-bit)
"@playwright/test": "1.38.1"

![image](https://github.com/microsoft/playwright/assets/106581694/0eb544ad-6870-4cd7-b242-ae748e29a2dd)
Crash from Thursday, October 5, 2023 at 8:44:23 AM
Status:	Uploaded
Uploaded Crash Report ID:	cf6d8f14be304ebd
Upload Time:	Thursday, October 5, 2023 at 8:44:27 AM

Crash from Thursday, October 5, 2023 at 8:45:08 AM
Status:	Uploaded
Uploaded Crash Report ID:	abee5720c06900f0
Upload Time:	Thursday, October 5, 2023 at 8:45:10 AM
Local Crash Context:	9fd6a7bc-f068-4402-9a1e-c993fef91010

**Comment by subabu-cmc** [comment]
Hi @pavelfeldman 
Chrome Version 117.0.5938.150 (Official Build) (64-bit)
"@playwright/test": "1.38.1"
<html>
<body>
<h3 class="capture-time" style="margin: 0.75em 0px; font-size: 12px; color: rgb(0, 0, 0); font-family: &quot;Segoe UI&quot;, Tahoma, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Crash from Thursday, 5 October 2023 at 10:14:28</h3>

Status: | Uploaded
-- | --
Uploaded crash report ID: | 3a5223929e0e5c33
Upload time: | Thursday, 5 October 2023 at 10:14:29
Local crash context: | cef8638d-963d-4248-85ee-6e734cb1d79f


</body>
</html>

**Comment by mikicymulate** [comment]
Crash from Thursday, October 5, 2023 at 12:20:11 PM
Status:	Uploaded
Uploaded Crash Report ID:	b95c520a9b353b47
Upload Time:	Thursday, October 5, 2023 at 12:20:14 PM
Local Crash Context:	639c7482-49c2-44ac-8224-f2cdab284d07


`12:19:46     <launching> C:\Program Files\Google\Chrome\Application\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --user-data-dir=C:\Users\cymulate.MY\AppData\Local\Temp\playwright_chromiumdev_profile-iJQOSX --remote-debugging-pipe --no-startup-window
12:19:46     <launched> pid=7760
12:19:46     [pid=7760][err] [7760:2496:1005/121908.789:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121908.976:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121908.977:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121913.968:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121913.968:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121913.968:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121914.079:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121914.079:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121914.079:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121919.525:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121919.525:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121919.526:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121919.771:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121919.771:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121919.771:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121919.913:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121919.913:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121919.913:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost
12:19:46     [pid=7760][err] [7760:2496:1005/121919.982:ERROR:validation_errors.cc(117)] Invalid message: VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD
12:19:46     [pid=7760][err] [7760:2496:1005/121919.982:ERROR:browser_child_process_host_impl.cc(750)] Terminating child process for bad message: Received bad user message: Validation failed for content.mojom.ChildProcessHost [VALIDATION_ERROR_MESSAGE_HEADER_UNKNOWN_METHOD]
12:19:46     [pid=7760][err] [7760:2496:1005/121919.982:ERROR:interface_endpoint_client.cc(702)] Message 1168968505 rejected by interface content.mojom.ChildProcessHost`

**Comment by pavelfeldman** [comment]
Could you please verify that things work fine with:

`channel: "chrome-beta"`?

You might need to run `npx playwright install chrome-beta`.

---

Chrome crash stack:
```
0x00007ff92823d5d3 (chrome.dll -injected-script.cc:177)  static void v8_inspector::InjectedScript::ProtocolPromiseHandler::thenCallback(const class v8::FunctionCallbackInfo<v8::Value> & const)
0x00007ff926d29744 (chrome.dll + 0x0000000005449744)  Builtins_CallApiCallbackGeneric
0x000002540183df60   
0x00007ff926e2baf3 (chrome.dll + 0x000000000554baf3)  Builtins_PromiseFulfillReactionJob
```

Related bugs: [crbug.com/1470645](https://crbug.com/1470645), [crbug.com/1482564](https://crbug.com/1482564)
V8 fix: https://chromium-review.googlesource.com/c/v8/v8/+/4753431

**Comment by subabu-cmc** [comment]
Hi @pavelfeldman
with chrome beta every thing work perfectly. Thanks a lot for your help.

**Comment by pavelfeldman** [comment]
This was a bug in Chrome, that got fixed in Chrome Beta and in the Chromium that Playwright uses. Please use chrome-beta until the next stable is available to work around the issue.
