### ISSUE TITLE
[BUG] TypeError: new_page() got an unexpected keyword argument 'http_credentials'

### ISSUE THREAD

**Issue by mandras73** [microsoft/playwright#27404]
### System info
- Playwright Version: 1.31.1
- Operating System: Windows 11
- Browser: Chromium

### Source code

`new_page = Browser.running_chromium.context().new_page(http_credentials={"username": user_name, "password": password})`

**Steps**
Run the test

**Expected**
Argument http_credentials are valid

new_page has an argument http_credentials, according to the docs
https://playwright.dev/python/docs/api/class-browser#browser-new-page

**Actual**
`TypeError: new_page() got an unexpected keyword argument 'http_credentials'`

**Comment by pavelfeldman** [comment]
You are referring to the doc for browser.new_page, but use [browser_context.new_page.](https://playwright.dev/python/docs/next/api/class-browsercontext#browser-context-new-page)

**Comment by mandras73** [comment]
Thanks Pavel, but in this case, the documentation contains the argument on the wrong section...
_browser-new-page_ instead of _browser-context-new-page_
Should be moved...
