### ISSUE TITLE
[BUG] install --with-deps chromium not working with pnpx package execution

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright#27407]
### System info
- Playwright Version: [v1.37.0+]
- Operating System: [Windows 11, Ubuntu 20]
- Other info:
We are using pnpm as our package manager and in our Azure CI pipeline, we want to install playwright with chromium only.

Our step in the pipeline is this:
`- script: pnpx playwright@1.37.0 install --with-deps chromium`

That executes but installs all browsers, not just chromium.

I have tested this with `npx` and that works just fine.  Should this work with `pnpx`?

**Comment by pavelfeldman** [comment]
My understanding is that `pnpx` has different purpose than `npx`, you can't use them interchangeably. `npx` is more like a [pnpm exec](https://pnpm.io/cli/exec) in this case.

**Comment by pavelfeldman** [comment]
I would run `playwright --install-deps` and `playwright install chromium` as two separate commands. Same thing.

**Comment by AndyGleed** [comment]
I still can't get that to work...I must be doing something wrong.

If I call `pnpx playwright@1.37.0 install --with-deps` first, that will stukk install **all** browsers regardless of If I then call `pnpx playwright@1.37.0 install chromium`

Maybe I miss understood your comment though :)

**Comment by pavelfeldman** [comment]
Do not do `install --with-deps`, to `install-deps`.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
