### ISSUE TITLE
[BUG] Component Testing Fails on Some Browsers

### ISSUE THREAD

**Issue by fadi-george** [microsoft/playwright#27419]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [macOS 13.6 (22G120)]
- Browser: [Firefox]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**
[Repo](https://github.com/fadi-george/playwright_1.38.1_ct_bug)

**Steps**
- Run `npm run test-ct`

**Expected**
- Simple component test should pass for all browsers

**Actual**
For Node 16 (v16.18.1), Firefox succeeds but others error out:
<img width="1020" alt="Screenshot 2023-10-03 at 5 52 32 PM" src="https://github.com/microsoft/playwright/assets/6709400/e5d8fa6d-c42d-45d9-9b5e-04ddd6177ecb">

For Node 18 (v18.18.0), Firefox fails but others work:
<img width="1000" alt="Screenshot 2023-10-03 at 5 54 08 PM" src="https://github.com/microsoft/playwright/assets/6709400/9a821dca-bc39-4f5c-90df-500b5e1d4c3f">
<img width="1003" alt="Screenshot 2023-10-03 at 5 54 18 PM" src="https://github.com/microsoft/playwright/assets/6709400/57637c05-a7ab-4477-bd76-305cf0f28727">

I also noticed the VSCode extension doesn't work well with component testing? 
<img width="503" alt="Screenshot 2023-10-03 at 5 55 38 PM" src="https://github.com/microsoft/playwright/assets/6709400/ce0ae894-b06e-4bda-a8ea-ac74f0fed8e4">
<img width="1045" alt="Screenshot 2023-10-03 at 5 56 15 PM" src="https://github.com/microsoft/playwright/assets/6709400/8936624e-32bd-430c-a950-e35831b9beaa">
<img width="1615" alt="Screenshot 2023-10-03 at 6 00 58 PM" src="https://github.com/microsoft/playwright/assets/6709400/42235c4f-9ad0-4a4a-a085-12bbc4e3b929">

It just shows 404 in the trace viewer or browser.
Some old vides seem to show the browser opening on /playwright/index.html but that seems 404 too.
<img width="1045" alt="Screenshot 2023-10-03 at 5 58 47 PM" src="https://github.com/microsoft/playwright/assets/6709400/dfc6277a-fc75-4a0a-baca-e89e80797d96">

**Comment by pavelfeldman** [comment]
Things work fine for me:

```js
~/tmp/playwright_1.38.1_ct_bug$ npm run test-ct

> playwright-ct-bug@1.0.0 test-ct
> playwright test -c playwright-ct.config.ts

playwright component

Running 3 tests using 3 workers
playwright component
playwright component
playwright component
  3 passed (4.7s)

To open last HTML report run:

  npx playwright show-report
```

What happens when you run them in headed mode?

```sh
npm run test-ct -- --project=firefox --headed
```

**Comment by fadi-george** [comment]
Hmm yeah not sure not sure how it happened, deleted everything again including the playwright cache, reinstalled, seems to be working now.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
