### ISSUE TITLE
[Question] Navigator Webdriver

### ISSUE THREAD

**Issue by imstefan13** [microsoft/playwright#2742]
Hey. I am trying to launch multiple chromium browsers on a specific website. The Navigator webdriver test is coming up as present. Is there a way I can turn this off. With puppeteer I would just use this function in order to bypass this problem. Any ideas?

`async webdriverTest(page) { //This function passes the web driver test
        await page.evaluateOnNewDocument(() => {
          Object.defineProperty(navigator, 'webdriver', {
            get: () => false,
          });
        });
      }`

This is my surrounding code.

`class yeezy {
    async webdriverTest() { //This function passes the web driver test
        console.log("hey") //Insert the code here to pass webdriverTest
      }
      
    async launchNewTab(url,proxies) { //This function launches a new browser
      //Launches a browser
      const browser = await chromium.launch({
        args: ['--no-sandbox',
        '--proxy-server=' + proxies], //
        headless: false, //So you can see and interact with the tabs
      });
      const page = await browser.newPage()

      await this.webdriverTest(); //Passes the webdriver test on the new browser

      // Navigate to Yeezy Supply
      await page.goto(url);
    }
      
    async start() {
        //Variables user needs to input
        var url = 'https://intoli.com/blog/not-possible-to-block-chrome-headless/chrome-headless-test.html' //https://www.yeezysupply.com/
        var tasks = 2 //Amount of browsers you want to open
        var proxies = [
        '173.46.67.172:58517',
        '34.91.135.38:80'
        ]

        //If valid number of tasks, tasks start.
        if (tasks > 0 && tasks <= 20 && tasks <= proxies.length) {
            console.log("Tasks Are Beginning to Run")
            for (let count = 0; count < tasks; count++) {
                console.log("Task launching with this proxy, " + proxies[count])
                await this.launchNewTab(url, proxies[count])
            }
        } else {
            console.log("Please enter a valid number of tasks between 1-20.")
            console.log("Make sure the number of tasks is less then the number of proxies.")
            console.log("Also make sure your proxies are formatted right.")
            process.exit()
        }
    }  
}`

**Comment by imstefan13** [comment]
Basically to summarize, I am looking for how to use puppeteer's page.evaluateOnNewDocument in playwright.

**Comment by pavelfeldman** [comment]
`page.addInitScript`

**Comment by suqibu** [comment]
dear imstefan13:
could you share your webdriverTest() code please? Thank you!

I has add this code in addInitScript(),  but it still could not pass the test of intoli.com:
'''
() =>{ 
                const newProto = navigator.__proto__;
                delete newProto.webdriver;  
                navigator.__proto__ = newProto;
}
'''

(when I use pyppeteer, it was work)
