### ISSUE TITLE
Looks like Playwright Test or Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers:              ║ ║                                                                         ║ ║     yarn playwright install 

### ISSUE THREAD

**Issue by DhanashriChavan125** [microsoft/playwright#27421]
### Error
Error: browserType.launch: Executable doesn't exist at C:\Users\cloudtest\AppData\Local\ms-playwright\chromium-1080\chrome-win\chrome.exe

Looks like Playwright Test or Playwright was just installed or updated. ║ ║ Please run the following command to download new browsers:              ║ ║                                                                         ║ ║     yarn playwright install 

### System info
- Playwright Version: 1.38.1
- Operating System: Windows 11

I added ** yarn playwright install ** command in package.json file, still i am getting same error

**Comment by pavelfeldman** [comment]
> I added ** yarn playwright install ** command in package.json file, still i am getting same error

It does not mean that you ran it though. Did you?

**Comment by DhanashriChavan125** [comment]
Cmd got executed, i can see it in logs

**Comment by pavelfeldman** [comment]
Do you see the browser in C:\Users\cloudtest\AppData\Local\ms-playwright\chromium-1080\chrome-win\chrome.exe ?
If you run this command manually, do you see the browser downloaded?

**Comment by sunilsurana** [comment]
The issue with your case @DhanashriChavan125  is you are using option playwright install --force chrome.
This downloads chrome in program files instead of AppData and when playwright tries to run test it tries to find in AppData
Just doing playwright install works fine

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
