### ISSUE TITLE
[BUG] Browser shuts down when DevTools are opened on Edge 117

### ISSUE THREAD

**Issue by tchudobova-cen69317** [microsoft/playwright#27425]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [Windows 10]
- Browser: [Chromium]
- Other info: Microsoft Edge 117.0.2045.43; Node.js 16.16.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({
        executablePath: 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe',
        headless: false
      });
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto('https://www.csas.cz/');      // we've originally used internal website to avoid proxy settings
  await page.waitForTimeout(300000);
  await browser.close();
})();
```

**Steps**
- Run the test (`node script.js`)
- While waiting, open DevTools manually

**Expected**

DevTools are opened and page's elements can be inspected.

**Actual**

The active browser window shuts down before DevTools are opened.

**Further note**
We've came across the problem while using Robot Framework and Browser Library, which runs on Playwright. The issue occured when upgrading MS Edge 116 to 117 (non-negotiable company's policy), no matter which Browser Library/Playwright version is used. Then we tried to test the Playwright itself, hence pardon our noob-ish code as we are not so familiar with the framework.

**Error in playwright-log.txt (Robot Framework)**
```
{"level":30,"time":"2023-10-04T11:17:18.017Z","pid":25524,"hostname":"NP45500","msg":"Removed page=9880ad72-1964-4d0a-9b87-bd4c7aa3e083 from context=b58d020c-6cb3-4c87-a08a-832f4c7b4106 page stack"}
```

**Comment by pavelfeldman** [comment]
I can repro this, does not happen with raw --remote-debugging-port, would need to bisect to a protocol call that breaks it.

**Comment by pavelfeldman** [comment]
Edge Crash ID:
```js
{
  "Local ID": "c686f541-111e-431b-b715-84cbbfa6386b",
  "Upload ID": "c686f541-111e-431b-b715-84cbbfa6386b",
  "Bucket ID": "399d93beb9d2727d2db6118bde603b5f",
  "Cab ID": "",
  "Capture Time": "Wednesday, October 4, 2023 at 3:31:10 PM",
  "Upload Time": "Wednesday, October 4, 2023 at 3:34:06 PM",
  "State": "Reported",
  "P1": "Microsoft_Edge",
  "P2": "117.0.2045.55",
  "P3": "Unknown",
  "P4": "0.0.0.0",
  "P5": "0",
  "P6": "browser",
  "P7": "0x1",
  "P8": "0"
}
```

**Comment by kunalnovice** [comment]
faced a similar issue on c# binary when Edge browser versioned 117.0.2045.31 closed unexpectedly in an attempt to access the dev tools option within the context menu.

behavior was replicated on 117.0.2045.55 as well on different PC

**Comment by XingXiaoWu** [comment]
same question,Edge 117.0.2045.55

**Comment by pavelfeldman** [comment]
Fixed in Microsoft Edge 118.
