### ISSUE TITLE
Unknown engine "internal:chain" while parsing selector

### ISSUE THREAD

**Issue by adamwoods1vitalitycouk** [microsoft/playwright#27422]
### System info
- Playwright Version: [v1.38]
- Operating System: [ Windows 10]
- Browser: [Chromium]
- Other info: Breaking change commit https://github.com/microsoft/playwright/commit/97d55e275dd26317651763128975b7b708475030

### Source code
```
private ILocator CashbackTableRows => _page.GetByRole(AriaRole.Dialog).Filter(new LocatorFilterOptions { HasText = "Cashback Bank Details" }).Locator("tbody tr");
private ILocator EditCashbackRowButton => _page.Locator("lightning-button button[title = Edit]");

await CashbackTableRows.Nth(0).Locator(EditCashbackRowButton).ClickAsync();
```

**Steps**
Add the two locators to your project
Chain the locators together such as performing a click

**Expected**
The locator to be found using its previous route of
internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> lightning-button button[title = Edit]

**Actual**
An "Internal:Chain" command is added to the selector, as documented in the above commit. The "Internal:Chain" should not trigger when chaining basic locators together.
[[Describe actual behavior]](internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> **internal:chain**="lightning-button button[title = Edit]")

An error message is generated because of this
Microsoft.Playwright.PlaywrightException : Unknown engine "internal:chain" while parsing selector .slds-tabs_card >> internal:role=tabpanel >> **internal:chain**=".uiOutputRichText.forceOutputRichText"

**Comment by pavelfeldman** [comment]
This looks like a valid locator representation:

`internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> internal:chain="lightning-button button[title = Edit]"`

> The "Internal:Chain" should not trigger when chaining basic locators together.

It is always used when you are chaining locators using Locator() method.

> An error message is generated because of this.

This error seems to be from a different locator:

`.slds-tabs_card >> internal:role=tabpanel >> internal:chain=".uiOutputRichText.forceOutputRichText"`

Could you share the relevant code, what and where exactly throws?

**Comment by adamwoods1vitalitycouk** [comment]
The error message was taken from another test which is suffering the same result after updating to the latest versions of Playwright. But the same message is conveyed. The error message specific to the above selectors is
`Microsoft.Playwright.PlaywrightException : Unknown engine "internal:chain" while parsing selector internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> internal:chain="lightning-button button[title = Edit]"`
Hope that helps, apologies for the confusion.

When you say, "It is always used when you are chaining locators using Locator() method." It is always used now. But was not previously. A few versions ago, this was not the outputted selector that Playwright built. Here are two comparisons of the exact same selector generated but run in version 32 of Playwright and the other in the latest.

OLD
internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> lightning-button button[title = Edit]

 NEW
internal:role=dialog >> internal:has-text=Cashback Bank Details >> tbody tr >> nth=0 >> internal:chain="lightning-button button[title = Edit]"

As you can see, Playwright is now adding "internal:chain" where it previously did not. This breaks many tests which have previously chained locators together

**Comment by pavelfeldman** [comment]
The transition to internal:chain was intentional, and as I mentioned, anything that does Locator() should produce it. The error message that you show `Unknown engine "internal:chain" while parsing selector` suggests that you are using two different version of Playwright at the same time that are not compatible. Are you using Connect? Could you share a self-contained example that is affected by this issue?

**Comment by pavelfeldman** [comment]
Also, @mxschmitt is saying that after updating Playwright, you might need to do a clean build of .Net solution. Could you give it a try and tell us if that helped? `dotnet clean`. If that helps, we have a bug!

**Comment by adamwoods1vitalitycouk** [comment]
Hi @pavelfeldman 

Looks like you hit the nail on the head. I hit the error in two ways.

1.
Our tests run through BrowserStack over night. I updated to the latest version .38 in all projects but despite this, BrowserStack only supports up to .36 for now. Meaning that there is a mix match of Playwright versions when running through BrowserStack. This then triggered the error above, which now makes sense.
![image](https://github.com/microsoft/playwright/assets/137996986/1038f507-3110-4aee-9667-a43e8b63ea62)
https://www.browserstack.com/docs/automate/playwright/browsers-and-os

2. Locally I saw the problem when updating from .32 to .38 too. After reading your last comment, I did see some old project folders in my solution which after removing those, running a clean and rebuild, the issue seems to have gone away. I am not sure if it was the old projects or the clean and rebuild that did the trick.

Either way, I can only replicate the problem when there is indeed a misalignment of versions, whether caused by BrowserStack being slow to update on their side and forcing a downgrade during runtime, or a mix match of versions stuck in uncleaned folders locally.

Either way, my issue is resolved and I thank you for your support and quick replies. So after reading this, feel free to close if you're happy.

Kind Regards
Adam

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
