### ISSUE TITLE
[Feature] Support dry run mode

### ISSUE THREAD

**Issue by AdamOakman** [microsoft/playwright#27431]
Allow to run playwright tests in dry run mode without real execution of tests content:

```sh
npx playwright test --dry-run
```

This kind of run would be useful in a couple of cases:
* for testing more complex greps
* for quick verification in PR pipeline if there is no test.only left in the code before merge - should fail when test.only is left in the code with co-existence of forbidOnly: true in the playwright config
* for testing the overall structure of HTML report (and potentially other reporters including custom ones) - it should generate dummy HTML report with all describe, test titles, steps data present in tests

And maybe even more I am not aware of.

**Comment by pavelfeldman** [comment]
It looks like you are describing the `npx playwright test --list` option.

**Comment by AdamOakman** [comment]
This actually covers my needs! Thanks!
