### ISSUE TITLE
[BUG] ssl_client_socket_impl  handshake failed; returned -1, SSL error code 1, net_error -201

### ISSUE THREAD

**Issue by MaximF39** [microsoft/playwright#27448]
### System info
mcr.microsoft.com/playwright:v1.20.0-focal
- Playwright Version: [v1.20.0]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: Chromium
- Other info:
It works like this: the client makes a request to the server, the server opens the playwright browser and works with it. 1 request = 1 browser. After the request, the browser closes. But due to an error, it always says to me that the browser, context or pages are closed, although I did not close them. There is a full log, but it takes up 5 GB, this is the most important part that I sent

Log file: [exception.txt](https://github.com/microsoft/playwright/files/12817252/exception.txt)

Dockerfile:
```docker
FROM mcr.microsoft.com/playwright:v1.20.0-focal
RUN apt-get update && apt-get install python3 python3-pip
COPY requirements.txt /requirements.txt
RUN pip3 install -r /requirements.txt
RUN playwright install chromium
COPY . /app
WORKDIR /app
RUN python3 setup.py develop
ENTRYPOINT ["/usr/local/bin/playwright_server"]
```

### Source code

Python:
browser:
`p.chromium.launch(headless=True, proxy={"server": 'per-context'})`
context:
`async with new_context(get_browser(req), proxy=proxy, ignore_https_errors=True) as context:`

**Steps**
- No info

**Expected**
Information log about reason raise Error

**Actual**
raise Error

**Comment by pavelfeldman** [comment]
It looks like your scenario is using legacy Playwright on python for scraping. We don't support scraping / bad actor scenarios.

**Comment by MaximF39** [comment]
Who is doing this? Who can I contact about this problem?
