### ISSUE TITLE
[BUG] --app args is not launching browser in application mode

### ISSUE THREAD

**Issue by rahulDW123** [microsoft/playwright#27442]
### System info
- Playwright Version: [v1.38.0]
- Operating System: [macOS13]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

use playwright config like below:

projects: [{
    name: "chromium-desktop-pwa",
    use: {
        ...devices["Desktop Chrome"],
        channel: "chrome",
        headless: false,
        launchOptions: {
            args: ["--app=https://www.facebook.com"]
        }
    },
}]

Expected:
<img width="1200" alt="Screenshot 2023-10-05 at 2 10 07 PM" src="https://github.com/microsoft/playwright/assets/107615052/73b0b48f-3c9e-4378-8e44-7d25a1210374">

Actual: Normal browser mode is getting launched

**Comment by pavelfeldman** [comment]
`--app` arg is not supported by Playwright.
