### ISSUE TITLE
Spacebar does not work in testing

### ISSUE THREAD

**Issue by Ildar1981** [microsoft/playwright#27441]
Context:

Playwright Version: "^1.30.0"
Operating System: Windows 10
Node.js version: v16.17.0
Browser: Chromium
Extra: -

the key doesn't click

 await page.keyboard.press(`SpaceBar`)
 await page.keyboard.press(`Space`)

**Comment by Ildar1981** [comment]
![image](https://github.com/microsoft/playwright/assets/80287182/e80cd3c1-ce7d-4eae-aca0-e3d764f46bf3)

  const inputFieldInterpretation = await page.locator(`.el-select__tags`)
        await inputFieldInterpretation.click()
        await page.waitForTimeout(2000)
        await page.keyboard.press(`ArrowDown`)
        await page.keyboard.type(' ')  //there is no pressing
        await page.keyboard.press('Space') //there is no pressing
        await page.keyboard.press(' ') // there is no pressing

**Comment by Ildar1981** [comment]
const inputFieldInterpretation = await page.locator(`.el-select__tags`)
        await inputFieldInterpretation.click()
        await page.waitForTimeout(2000)
        await page.keyboard.press(`ArrowDown`)
        await page.keyboard.type(' ')  //there is no pressing
        await page.keyboard.press('Space') //there is no pressing
        await page.keyboard.press(' ') // there is no pressing

**Comment by Ildar1981** [comment]
page.keyboard.press('Space')
works only on the input field 
but not for choice

**Comment by priya-acko** [comment]
how we can press spacebar in playwright
