### ISSUE TITLE
[BUG] Downloads binaries for the wrong architecture

### ISSUE THREAD

**Issue by jleedev** [microsoft/playwright#27453]
### System info
- Playwright Version: v1.38.1
- Operating System: Raspbian GNU/Linux 12 (bookworm)
- Browser: All
- Other info: process.arch === 'arm'

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Steps**

```
yarn create playwright
yarn playwright install
yarn playwright test
```

**Expected**

[Describe expected behavior]

Really, any of these would be reasonable:

- A browser that runs on my machine is downloaded
- An error says "Sorry, we only have binaries for "x64" and "arm64", not "arm"
- Instructions for adjusting launchOptions.executablePath are shown
- The website at https://playwright.dev/docs/intro#system-requirements gives the correct system requirements

**Actual**

[Describe actual behavior]

1. We get a message, "BEWARE: your OS is not officially supported by Playwright; downloading fallback build." As it happens, Raspbian's /etc/os-release contains `ID=raspbian`; changing this to `ID=debian` silences the warning, but the exact same build of chromium is downloaded anyway, so this is a red herring.
2. The downloader inspects os.arch(), sees that it is not arm64, and unpacks 956 MiB of browsers for x64 into ~/.cache/ms-playwright
3. The tests fail, loudly:
   ```
    [pid=15359][err] /home/josh/.cache/ms-playwright/chromium-1080/chrome-linux/chrome: 3: Syntax error: Unterminated quoted string
    [pid=15676][err] /home/josh/.cache/ms-playwright/firefox-1424/firefox/firefox: 4: ������
                                                                                            ��
                                                                                              ��
                                                                                                ��6�

    [pid=15676][err]

    [pid=15676][err]
                     @���DD��
                             ��
                               ��
                                 : not found
    ╔══════════════════════════════════════════════════════╗
    ║ Host system is missing dependencies to run browsers. ║
    ║ Missing libraries:                                   ║
    ║     libGLESv2.so.2                                   ║
    ╚══════════════════════════════════════════════════════╝
    ```
4. An empty file named `"\001\300\335@\230\005\f@8\f@\035\034\006\004@@@\240\002\240\002\b\003\004\340\002\340\002\340\002\034\034\001\001\004\330\301\330\301\020\001\005\320\320\320\375j" appears in my project. For all I know this recklessness is the fault of nodejs or libuv — child_process.execFile seems to ignore { shell: false } — but it's definitely garbage in, garbage out.

**Comment by pavelfeldman** [comment]
Would you be interested in contributing a fix? We are not prioritizing unsupported OS scenarios.

**Comment by jleedev** [comment]
Yes, it is not clear what constitutes "unsupported OS scenarios" except that it does not work correctly.

**Comment by pavelfeldman** [comment]
> Yes, it is not clear what constitutes "unsupported OS scenarios" except that it does not work correctly.

We list supported environments here: https://playwright.dev/docs/next/intro#system-requirements

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by jleedev** [comment]
I read that page, linked to it in my report, explained that it does not list supported architectures, and opened a pull request to add a few words there.
