### ISSUE TITLE
[BUG] qr loading

### ISSUE THREAD

**Issue by amiruldev20** [microsoft/playwright#27451]
I tried to code the open page web.whatsapp.com with playwright webkit browser. But why does the QR on the URL page keep loading, the QR image doesn't appear?
![Screenshot_20231005-225114.png](https://github.com/microsoft/playwright/assets/73012169/0c81cd0a-bbd3-4a8b-b87e-26362c241e40)

**Comment by pavelfeldman** [comment]
> But why does the QR on the URL page keep loading, the QR image doesn't appear?

I have no idea. Please follow the BUG issue template when filing.

**Comment by VakhrameevAnton** [comment]
@techwiz37 any workaround? I have the same problem and can't understand the reason. If checkbox "Do not sign out in this browser" is active, it's impossible to wait qr code loading.
