### ISSUE TITLE
[BUG] DEBUG log to file override logs for each worker session 

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright#27476]
### System info
- Playwright Version: [v1.38]
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

Set Env variable
DEBUG=pw*
DEBUG_FILE=log.log

**Steps**
- [Set above en variable]
- [Run the test]

**Expected**
Logs for all workers captured in log.log file

**Actual**
We only get logs for last worker session

**Comment by pavelfeldman** [comment]
I would guess that each worker will open this file and the last worker will win. I don't think we'll be fixing this.
