### ISSUE TITLE
[BUG] DEBUG_FILE log doesnt show time taken for operation

### ISSUE THREAD

**Issue by puagarwa** [microsoft/playwright#27477]
### System info
- Playwright Version: [v1.38]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

When we use DEBUG_FILE env variable to push logs into file, logs doesnt show time spent, whereas it shows when not using file redirection.
DEBUG=pw:api*
DEBUG_FILE=log.log

**Steps**
- [Set ENV variable]
- [Run the test]

**Expected**

pw:api => selectors.setTestIdAttribute started **+0ms**
  pw:api => browserType.launch started **+7ms**   

**Actual**

pw:api => selectors.setTestIdAttribute started
  pw:api => browserType.launch started

**Comment by pavelfeldman** [comment]
We are using the [debug](https://www.npmjs.com/package/debug) module for our logs, so this request should go to their issue tracker.
