### ISSUE TITLE
[Feature] Highlight element in the browser

### ISSUE THREAD

**Issue by phileba** [microsoft/playwright#2747]
As the user, I want to have a method to highlight and reveal in devtools if those are opened, something like:
```
const element = page.$(selector)
await element.inspect()
```

**Comment by Snooz82** [comment]
So how shall it behave? 

```
page.inspect('#elem1')   //highlights element 1

page.inspect('#elem2')   //switches highlight from element 1 to element 2
```
? 

IMO it would be nice to have the css that highlights as an option.
Like `page.inspect(selector[, style])`
`page.inspect('#element', '{border: 4px dotted blue;}')`

regards

**Comment by phileba** [comment]
Hi guys, any updates?

**Comment by phileba** [comment]
Hi guys, any updates?

**Comment by pavelfeldman** [comment]
A combination of PWDEBUG and playwright.$ is very similar to this request. See https://playwright.dev/docs/inspector for more details. Please open new bugs for missing features in the inspector!
