### ISSUE TITLE
[BUG] [webkit] tests relying on selection are flaky when running in parallel in linux and headed mode

### ISSUE THREAD

**Issue by gurschitz** [microsoft/playwright#27475]
Hey there! We are observing flaky tests in our CI when running tests relying on selection state in linux with `--headed` flag in parallel.

### System info
- Playwright Version: v1.38.1
- Operating System: Ubuntu 22
- Browser: WebKit
- Other info: I tested this in docker with the latest official docker image `mcr.microsoft.com/playwright:v1.38.1` 

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```ts
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  workers: 2,
  projects: [
    {
      name: "webkit",
      use: { ...devices["Desktop Safari"] },
    },
  ]
});
```

**Test file (self-contained)**

```ts
test("keeps the selection", async ({ page }) => {
  await page.setContent('<div id="container">lorem ipsum dolor sit amet</div>');

  await page.evaluate(() => {
    const element = document.getElementById("container") as HTMLDivElement;
    const textNode = element.firstChild as Text;

    const range = textNode.ownerDocument.createRange();
    range.setStart(textNode, 6);
    range.setEnd(textNode, 11);

    const selection = textNode.ownerDocument.defaultView?.getSelection();
    selection?.removeAllRanges();
    selection?.addRange(range);
  });

  // the selection should stay the same even after 1 second passed
  await page.waitForTimeout(1000);

  const range = await page.evaluate(() => {
    const selection = document.getSelection();
    const range = selection?.getRangeAt(0);
    return {
      rangeCount: selection?.rangeCount,
      startOffset: range?.startOffset,
      endOffset: range?.endOffset,
    };
  });

  expect(range).toEqual({ rangeCount: 1, startOffset: 6, endOffset: 11 });
});
```

**Steps**
- Start the docker container `docker run --rm --network host -v $(pwd):/work/ -w /work/ -it mcr.microsoft.com/playwright:v1.38.1 /bin/bash`
- Run `xvfb-run npx playwright test --headed --repeat-each 10`

**Expected**
- Tests relying on the selection state are not flaky when running them with multiple workers on linux in webkit.

**Actual**
Running the above, you will see that the test runs are flaky.

<img width="693" alt="Screenshot 2023-10-06 at 10 19 17" src="https://github.com/microsoft/playwright/assets/4624537/b4e9acd4-eb6f-479f-9053-7e56bb3a97fc">

Running the tests in `headless` mode doesn't result in this issue, as well as running them with `--headed` on MacOS. Further, running the tests with only 1 worker also doesn't cause this issue. So it seems that the selection is somehow influenced by other tests running at the same time but only on linux.

Note that this does not happen in chrome or firefox with the same setup. So it must be something specific to webkit on linux but it's not clear to me if there is something that can be done on playwright side or if this is an upstream issue.

We have to run those tests with `--headed` because we are relying in some tests on the clipboard, and that doesn't work in headless mode on linux because [the permission is automatically denied](https://webkitgtk.org/reference/webkit2gtk/stable/class.ClipboardPermissionRequest.html#:~:text=When%20a%20WebKitClipboardPermissionRequest%20is%20not%20handled%20by%20the%20user%2C%20it%20is%20denied%20by%C2%A0default.).

Please let me know if you need more info and thanks for the awesome work on Playwright. 🙏

**Comment by gurschitz** [comment]
Thanks for the quick reply!

> You mentioned that you test clipboard, that one would need serial mode due to system clipboard being used. Is that acceptable?

Yeah that's acceptable to us as we currently lock access to clipboard anyways for that reason. It'd be great if we could use that in headless mode too on linux so that we can switch to headless in CI.

**Comment by pavelfeldman** [comment]
Which clipboard methods are you using? Those on navigator? Could you attach a snippet?

**Comment by gurschitz** [comment]
Yes, we use the ones on navigator but currently only `navigator.clipboard.write` and `navigator.clipboard.writeText`. We also have some fallback logic in place because [we ran into this issue before](https://github.com/microsoft/playwright/issues/18901). We encapsulate all of that in a [fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures) and put a lock around that.
