### ISSUE TITLE
[BUG] qr loading

### ISSUE THREAD

**Issue by amiruldev20** [microsoft/playwright#27471]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [Windows 10, Ubuntu 20]
- Browser: [Webkit]
I want to make a scrape to take the WhatsApp web QR but the QR doesn't appear
mycode:
import playwr from 'playwright'

const browser = await playwr.webkit.launch({
    headless: false
})
const context = await browser.newContext({
    ignoreHTTPSErrors: true,
  });
const page = await context.newPage()
await page.goto
('https://web.whatsapp.com')

![Screenshot (1)](https://github.com/microsoft/playwright/assets/73012169/4510eacc-35bf-4a63-ade3-62d6e634d262)

**Comment by pavelfeldman** [comment]
Your scenario looks like a scraper / bad actor one, we are not satisfying the requests like this.
