### ISSUE TITLE
[Feature] Support JS Property Path Lookups for `toHaveJSProperty` Assertion

### ISSUE THREAD

**Issue by ITenthusiasm** [microsoft/playwright#27487]
## The Problem

Currently, `Playwright` doesn't have a great way to deal with complex objects. This seems to be due to its need for `JSON.stringify` when communicating back and forth between the Playwright Tests and the Browser/Page. Right now, I'm working on a Web Component that [acts as a form control](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/attachInternals). The component exposes its [validity state](https://developer.mozilla.org/en-US/docs/Web/API/ElementInternals/validity) through a `validity` getter accessor. Playwright is able to find this just fine, but it _can't_ find the other properties on the `ValidityState` object because those properties are also accessors of some kind. This means that I can't do

```ts
await expect(combobox).toHaveJSProperty(
  "validity",
  expect.objectContaining({ valueMissing: false, valid: true }),
);
```
or
```ts
expect(
  await page.evaluate(() => document.querySelector<ComboboxField>("[role='combobox']")?.validity),
).toEqual(expect.objectContaining({ valueMissing: false, valid: true }));
```
because `JSON.stringify(field.validity)` becomes `"{}"`.

Instead, I have to do
```ts
expect(
  await page.evaluate(() => document.querySelector<ComboboxField>("[role='combobox']")?.validity.valid),
).toBe(true);

expect(
  await page.evaluate(
    () => document.querySelector<ComboboxField>("[role='combobox']")?.validity.valueMissing,
  ),
).toBe(false);
```

Notice the verbosity and the formatter headache. (And my `Prettier` configuration allows _120 characters_ -- much larger than normal.) Unfortunately, this is a lot of LOC just to run a simple assertion on a single object. As more assertions on the `ValidityState` become necessary, the readability/maintainability of the code decreases. I imagine there are other situations where developers will have this issue while performing assertions on elements (and especially custom elements).

## The Solution

One possible solution to this problem is to enable `toHaveJSProperty` to follow a [`string` path](https://stackoverflow.com/questions/6491463/accessing-nested-javascript-objects-and-arrays-by-string-path) of properties to access nested object values. (The solution would need to support `getter` accessors and regular properties.) This would enable me to write code like this:

```ts
await expect(combobox).toHaveJSProperty("validity.valid", true);
await expect(combobox).toHaveJSProperty("validity.valueMissing", false);
```

which is _much_ smaller and _much_ more readable.

Ideally, I would just be able to check the object. But in lieu of that possibility, this is a reasonable alternative that prevents the code for tests from getting out of hand.

One of Playwright's greatest drawbacks compared to Cypress is this issue of working with complex objects (like functions or objects with getters). So having compensations that provide a "good enough" developer experience is important here.

There might be other alternatives that provide a sufficient DX as well. But I'm not sure.

**Comment by pavelfeldman** [comment]
> which is much smaller and much more readable.

Sadly it is also breaking. While we are considering it, here is another workaround for your consideration:

```js
await expect.poll(() => combobox.evaluate((e: any) => ({
  valid: e.validity.missing,
  valueMissing: e.validity.valueMissing,
}))).toEqual({
  valid: true,
  valueMissing: true,
});
```

Although it is even uglier, it allows assessing multiple 'paths' at a time, and also auto-retries until the condition is met, which will match the other web assertions behavior (toHaveJSProperty).

> One of Playwright's greatest drawbacks compared to Cypress is this issue of working with complex objects (like functions or objects with getters). So having compensations that provide a "good enough" developer experience is important here.

As a side note, we are now suggesting to use a Storybook-alike methodology where when testing complex components you wrap them with stories that 'simplify' the types.

**Comment by ITenthusiasm** [comment]
> Sadly it is also breaking.

Is it truly a breaking change? :thinking: I would think that this change would allow developers to keep accessing regular properties while also enabling them to access nested properties, no?

> here is another workaround for your consideration

I wasn't aware that `evaluate` could also be called on `Locator`s. I guess that's an alternative for now. The `poll`ing does look pretty wild, but if the properties are accessed individually it gets us closer to the example in the OP.

```ts
expect(await combobox.evaluate((node: ComboboxField) => node.validity.valid)).toBe(true);
expect(await combobox.evaluate((node: ComboboxField) => node.validity.valueMissing)).toBe(false);
```

I don't know if that has an impact on performance. I'm not sure of Playwright's inner workings there. In any case, that tidbit is really helpful, so thank you (again).

> As a side note, we are now suggesting to use a Storybook-alike methodology where when testing complex components you wrap them with stories that 'simplify' the types.

I'm not fully sure what this means. Does this mean having a whole `export` system like StoryBook or just creating functions that help with testing/asserting?

**Comment by pavelfeldman** [comment]
> Is it truly a breaking change? 🤔 I would think that this change would allow developers to keep accessing regular properties while also enabling them to access nested properties, no?

```js
{
  'a.b': 1,
  a: { b: 2 }
}
```

> I'm not fully sure what this means. Does this mean having a whole export system like StoryBook or just creating functions that help with testing/asserting?

I meant to include the link: https://playwright.dev/docs/next/test-components#test-stories
