### ISSUE TITLE
[BUG] Test flakiness getting `locator.selectOption: Target closed` and browser `UniversalExceptionRaise` error

### ISSUE THREAD

**Issue by casey-lemon** [microsoft/playwright#27489]
### System info
- Playwright Version: [v1.37.1, 1.38.1]
- Operating System: [Ubuntu 20, macOS 13.6]
- Browser: [Chromium]
- Other info:
    - Project config uses `devices['Desktop Chrome']` and specifies `channel: 'chrome'`

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

Reproduced the issue in a private repo, can provide access upon request.

I also have zipped traces from using v1.37.1 and after attempting to upgrade to v1.38.1 to see if latest would fix the issue, can provide those as well if needed.

**Steps**
- Run the test in the reproduction repo

**Expected**

Test passes using all major browser configurations with no flakiness or randomly failing tests.

**Actual**

Test passes consistently when using `devices['Desktop Safari']`, `devices['Desktop Firefox']`, and `devices['Pixel 5']` from `import { devices } from '@playwright/test'`

However, on when using `use {...devices['Desktop Chrome'], channel: 'chrome'}` project configuration for chrome testing, the test is very flaky and when it does fail it is because of the test timeout. When running an affected test 20 times back to back, it fails anywhere from 4-10 times out of 20.

When `DEBUG=pw:api,pw:browser` flags are enabled I get the following when the test fails.

```
  pw:api waiting for getByTestId('dropdown-0') +2ms
  pw:api   locator resolved to <select name="" class="sc-kTLmzF lOzfu" data-testid="dro…>…</select> +1ms
  pw:api   selecting specified option(s) +2ms
  pw:api => route.fulfill started +15ms
  pw:api     selected specified option(s) +1ms
  pw:api <= route.fulfill succeeded +4ms
  pw:api <= page.waitForResponse succeeded +6ms
  pw:api <= locator.selectOption succeeded +10ms
  pw:api => locator.selectOption started +0ms
  pw:api waiting for getByTestId('dropdown-1') +2ms
  pw:api   locator resolved to <select name="" class="sc-kTLmzF lOzfu" data-testid="dro…>…</select> +2ms
  pw:api   selecting specified option(s) +2ms
```

Please let me know what other information might be needed.

**Comment by pavelfeldman** [comment]
Folding into https://github.com/microsoft/playwright/issues/27405

Google Chrome is broken, use `chrome-beta`.
