### ISSUE TITLE
[Feature] make Playwright version more visible

### ISSUE THREAD

**Issue by debs-obrien** [microsoft/playwright#27482]
As a user of Playwright I know I need to update my version. However I don't always remember to do it. How can I know when to update? Am I dependant on watching the youtube video or reading the release notes of the docs. There has to be a better way to show our users that there is a newer version so it makes their lives easier so they update more frequently. 

Suggestions:

- something in UI mode that tells them there is a newer version
- something in terminal if version is outdated and they run a test
- something in VS Code if we detect they are on an old version

**Comment by mxschmitt** [comment]
Using `%%VERSION%%` should work out of the box in our docs, like we use in the Docker [doc](https://github.com/microsoft/playwright/blob/main/docs/src/docker.md).
