### ISSUE TITLE
[Feature] Allow saving all test run information for any test run to be viewable at anytime after.

### ISSUE THREAD

**Issue by DanoUnicity** [microsoft/playwright#27490]
It would be great to  have some way to be able to look at a given test run after a test run and the machine is at an idle state.   As we, say i'm using VS Code run my tests in the terminal will see:

  Serving HTML report at http://localhost:9323. Press Ctrl+C to quit.

While that appears to only work before pressing Ctrl+C and exiting.  Trying to then run:

npx playright show-report

Nothing except for "There are no test results to show.." 

This is the current behavior and seems like a rather poor user experience.   Hard drive space is cheap, and for the benefit it give me, would like to be able to go back as needed to view all one is possible when viewing the "show-report",   screen shots, video, everything..

**Comment by pavelfeldman** [comment]
`npx playright show-report` will work as long as playwright-report folder exists. When is it getting removed for you?

**Comment by pavelfeldman** [comment]
We would need exact steps to follow in order to address this. It includes the code snippet that we can run locally to demonstrate the problem.

**Comment by DanoUnicity** [comment]
I run from VS Code, will see the prompt after runningin VS Code "Open in browser" or click ong "http://localhost:port  or press Ctrl-C..."  If i press Ctrl-C. all is gone.  From my project folder in VS code if i then try  "npx playwright show-report"  will then get "no report to show" or something like that...   In the playwright.config.ts, thought i have all settings to keep the report, so if i'm missing something great not really clear in the docs...
