### ISSUE TITLE
[BUG] need to periodically refresh page until the text is updated on the page

### ISSUE THREAD

**Issue by InduKrish** [microsoft/playwright#27494]
### System info
- Playwright Version: 1.36.2
- Operating System: All
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

have to refresh the page, after a definite timeout to validate if the text is updated on the page. 

```javascript
if ((await round.textContent()).toString() === this.roundNo.toString()) {
                  await expect(await status).toHaveText(this.validStatus, { timeout: 600000 });
                console.log("****Status value:****" + await status.textContent())

            }
```

referred the link https://github.com/microsoft/playwright/issues/11703, please advise if there is something closer to the answer provided in the link given above.
```javascript
await page.waitForCondition(async () => {
  await page.reload();
  return page.locator('some locator').isVisible()
},  { timeout: 60 * 1000 })
```

please advise how i can refresh/reload  the page after a certain timeout before validating the text using expect.

**Comment by pavelfeldman** [comment]
Playwright scripts are a JavaScript program, you can do everything there, load pages, reload pages, check text, wait for time. Looks like you have a JavaScript programming question which is outside of the scope for Playwright.
