### ISSUE TITLE
[BUG] performance.measureUserAgentSpecificMemory not working when running Playwright test

### ISSUE THREAD

**Issue by daniel-ji** [microsoft/playwright#27499]
### System info
- Playwright Version: v1.38.1
- Operating System: Ubuntu 20
- Browser: Chromium
- Other info:

### Source code
Github Repo reproducing the issue:
https://github.com/daniel-ji/playwright-measureUserAgentSpecificMemory-bug

**Steps**
```
git clone https://github.com/daniel-ji/playwright-measureUserAgentSpecificMemory-bug.git
cd playwright-measureUserAgentSpecificMemory-bug
npm install
npx playwright test
```

The console.log's that get redirected to Playwright from `index.html` log `Cross-Origin-Isolated` and `measureUserAgentSpecificMemory supported` (from the conditions `window.crossOriginIsolated` and `performance.measureUserAgentSpecificMemory`), but when the function is called, it gives the following error: 
```
Error:  DOMException: Failed to execute 'measureUserAgentSpecificMemory' on 'Performance': performance.measureUserAgentSpecificMemory is not available.
    at http://localhost:8080/:29:16
```

**Comment by daniel-ji** [comment]
Sorry, I figured it out - inside `playwright.config.js`, I just needed to configure `projects` as so:

```
{
	name: 'chromium',
	use: {
		launchOptions: {
			ignoreDefaultArgs: ['--headless'],
			args: ['--headless=new']
		}
	},
},
```

**Comment by GermanJablo** [comment]
Can you explain to me exactly how you solved it? I'm having the same problem, and I don't see that in your repro you are using `performance.measureUserAgentSpecificMemory`.

I've opened an issue here with a minimal repro: https://github.com/microsoft/playwright/issues/34163

**Comment by daniel-ji** [comment]
Sure! I've my repo that has the issue here: https://github.com/daniel-ji/playwright-measureUserAgentSpecificMemory-bug/commit/d864eef0ec98a3ae8e21f6e107103b2daf13661e

**Comment by GermanJablo** [comment]
I tried that (the `launchOptions` thing) and it didn't work.

As for using it in the current js site, that's what I'm doing with page.evaluate in theory.

In the issue I opened I was told that I need to do a `page.goto` to localhost. I've updated my repo with that but it still doesn't work.

> If you need further help (I see in your repo you're trying to call performance.measureUserAgentSpecificMemory in the playwright test itself), I can give a go on your repo and try to fix it there.


That would be great! I really appreciate the help!

**Comment by daniel-ji** [comment]
I think something worth noting is `measureUserAgentSpecificMemory` is still quite experimental and something like this used for benchmarking should be taken with a grain of salt. Note that even with this working solution below, the memory usage value fluctuates across different environments / calls quite widely (at least what I would believe with my limited testing). The test below reports the site using ~0.9MB of memory, but actually running a local deployment of the site and calling `performance.measureUserAgentSpecificMemory` gives me a value around ~3MB. 

To fix, a couple things have to be done:

1. playwright version 1.49 breaks some things and results in `measureUserAgentSpecificMemory` timing out (in my limited experience trying to use it). I downgraded to 1.48.2 and things worked fine. 

2. To make this work on localhost, a service worker has to be added to enable cross-origin isolation (COI): https://github.com/gzuidhof/coi-serviceworker.

3. Your `playwright.config.ts` must contain the following `launchOptions`:

```js
    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
        launchOptions: {
          ignoreDefaultArgs: ["--headless", "--headless=old"],
          args: ["--headless=new"],
        },
      },
```

4. In your test, because of the forced refresh due to the COI service worker getting registered, you may have to wait before running checks in your test (note the `await page.waitForTimeout(2000);`)


```js
import { expect, test } from '@playwright/test';

test('has title', async ({ page }) => {
  await page.goto('http://localhost:5173');
  await page.waitForTimeout(2000);
  expect(await page.title()).toBe('Vite + TS');
  await page.evaluate("performance.measureUserAgentSpecificMemory()");
});
```


See a working solution here (a forked & modified version of your repo): https://github.com/daniel-ji/measureUserAgentSpecificMemory


You should get an output of something like


```
> vite-project@0.0.0 test /home/daniel/research/measureUserAgentSpecificMemory
> playwright test


Running 1 test using 1 worker

  ✓  1 [chromium] › example.spec.ts:3:1 › has title (17.4s)
Memory: 928421 bytes

  Slow test file: [chromium] › example.spec.ts (17.4s)
  Consider splitting slow test files to speed up parallel execution
  1 passed (19.1s)
```


Best of luck!

**Comment by GermanJablo** [comment]
Wow, thanks so much for the help!
I really appreciate it!

If there is a problem with 1.49 then maybe some bug was introduced there! CC: @Skn0tt
