### ISSUE TITLE
[Feature] Add Test Summary Statistics to Suite interface and the json output result

### ISSUE THREAD

**Issue by ryanrosello-og** [microsoft/playwright#27498]
Hello 👋 
I'm currently having to [man-handle aggregation of the test results stats](https://github.com/microsoft/playwright/blob/e70b10ac2ec4fd405c89ad4a3589fbc1164837b1/packages/playwright/types/testReporter.d.ts#L41) and this has been problematic for me (caused several bugs because of incorrect stats).  Rather that having clients do this computation, it would be really nice if Playwright provided this info upfront because you guys will already have it.

https://github.com/microsoft/playwright/blob/e70b10ac2ec4fd405c89ad4a3589fbc1164837b1/packages/playwright/types/testReporter.d.ts#L41

**Expose the follow so that custom reporters can consume it ...**
```typescript
  suitesSummary: {
    passed: number;
    failed: number;
    retried: number;
    flaky: number;
    skipped: number;
    total: number;
    startTime: Date;
    duration: number;
  }
```

**Include the stats in JSON result would look like something this:**
```json
  "suites": [...],
  "suitesSummary":{
    "passed": 90,
    "failed": 3,
    "retried": 3,
    "flaky": 0,
    "skipped": 0,
    "total": 3,
    "startTime": "2023-10-07T20:22:50.297Z",
    "duration": 3333333
  },
  "errors": []
```

**Comment by ryanrosello-og** [comment]
@dgozman 
>Are you interested in the total stats for the whole run, or separate per-suite stats? 

The entire test run encompassing all test suites would be nice

>We are hesitant adding that to the reporter API though, because that would be redundant

How would people know how many test failed/passed/retried etc without digging deep into the result? Is there some other way of finding out this info without need to write custom code to trawl through the results object and add up failures/passes/retries/skipped etc?

**Comment by dgozman** [comment]
> How would people know how many test failed/passed/retried etc without digging deep into the result?

Here is a short snippet:

```ts
const stats = { expected: 0, skipped: 0, unexpected: 0, flaky: 0 };
for (const test of suite.allTests())
  ++stats[test.outcome()];
```

**Comment by ryanrosello-og** [comment]
thanks @dgozman , would your snippet above also handle retries?  Retries has been very troublesome for me to quantify.

**Comment by dgozman** [comment]
@ryanrosello-og Yep, the `test.outcome()` method takes care of retries.
