### ISSUE TITLE
[Question] Download in Juggler 

### ISSUE THREAD

**Issue by shirshak55** [microsoft/playwright#2750]
1. And I expect Juggler to behave just like normal firefox so it should have created 1GB.zip   
When i download it from juggler `http://ipv4.download.thinkbroadband.com/1GB.zip`.  it should have created 1GB.part file when download is incomplete and after it is complete the there should be only 1GB.zip  (these can be used to detect incompleted download)

~~2. However current behavior is it deletes the file after downloading. And the file name are like hashes :( The 1GB.zip was named `85be717b-e174-8544-a143-3c0e2c510945`~~

~~Download are supposed to not be temporary like even if we download file from incognito mode they are not deleted.~~ Update it deletes only if we haven't created a directory

3. about:downloads page is empty

Is there anyway to make file download permanent and use name that user normally see?

**Comment by mxschmitt** [comment]
There is [suggestedFileName](download.suggestedFilename()), which you can use to get the original file name like what the browser would normally suggest.

After each download you can copy the file either or use the streamline from [createReadStream](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=downloadcreatereadstream), probably copying is better.

**Comment by shirshak55** [comment]
@mxschmitt hmm the problem is i wouldn't know how many file will be downloaded and createReadStream is not good for GB file?

**Comment by pavelfeldman** [comment]
> Is there anyway to make file download permanent and use name that user normally see?

No, files are named using guids to allow repeated downloads with the same suggested name.

**Comment by shirshak55** [comment]
@pavelfeldman downloads are repeated in firefox they add suffix like 

```
file.png
file(1).png
file(2).png
```

**Comment by pavelfeldman** [comment]
I don't think what you are suggesting is a good idea. And I hope we are deleting the downloads on non-persistent context closure.

**Comment by shirshak55** [comment]
Alright thanks. I guess i will use use createReadStream and copy files.
