### ISSUE TITLE
Create/Intercept WebSocket within Playwright?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#27528]
So im not super familiar with websockets, but currently to test websockets for a specific product we have to post something like this in the browser console:

```
var webSocket = new WebSocket('wss://rt.<a long url with a bunch of parameters>');
webSocket.onmessage = function(data) { console.log(data); }
```

I can then see the `MessageEvent` with details and it seems to poll and keep posting `MessageEvent`. We then hit another endpoint with a normal API request and can verify those `MessageEvent` details change.

So in my head I could technically wrap the above code in a `page.evaluate` function correct? (I think we use this because the actual trigger for the websocket is complex to do, so this is a workaround right?)

However I don't know of a way to read the MessageEvents? From what I can see in examples there is no `page.on('message')` so is this even possible?

**Comment by imartinflores** [comment]
Have you tried 'framesent' ?

**Comment by dgozman** [comment]
@msmith1114

> So in my head I could technically wrap the above code in a page.evaluate function correct? (I think we use this because the actual trigger for the websocket is complex to do, so this is a workaround right?)

Yep, you can evaluate to create your websocket, although we advise to trigger the behavior through user actions instead.

> However I don't know of a way to read the MessageEvents? 

First, you need to get a `WebSocket` object in the test by listening to the [`'websocket'` event](https://playwright.dev/docs/api/class-page#page-event-web-socket). From there, listen to the [`'framereceived'` event](https://playwright.dev/docs/api/class-websocket#web-socket-event-frame-received).

**Comment by msmith1114** [comment]
This ended up working:

  ```
    let value;
    page.on("websocket", (ws) => {
      ws.on("framereceived", (event) => (value = event.payload));
    });
    await page.evaluate(
      `var webSocket = new WebSocket('wss://<websocket_url>')`,
    );
```

It feels kinda messy to use the `page.evaulate` so I tried using the npm websocket package itself. Doing something simple like:

```
const ws = new WebSocket('ws://websocket_url');
ws.on('message', function message(data) {
  console.log('received: %s', data);
});
```

Problem was it runs synchronously and I couldn't exactly `await` the data since the test would just continue. Although perhaps if I make a request later that awaits then the websocket should fire and store a value into data.

If that works is there any advantage or disadvantage to using the websocket library itself? I mean I assume `page.evaulate` is just calling javascripts/browser native websocket library vs using the node one?

**Comment by dgozman** [comment]
> If that works is there any advantage or disadvantage to using the websocket library itself? I mean I assume page.evaulate is just calling javascripts/browser native websocket library vs using the node one? It would be nice if there was some way to await the data from ws.on

I am not sure what's your goal is. If you'd like to use the Node.js websocket library, what are you actually testing? I can tell you right away that websocket library works 😄

I thought you needed to trigger some websocket code inside your actual web page, and then something else would happen on the page that you'd like to test. In this case, it's essential to `page.evaluate()`.

However, if you'd like to test your server's websocket, like make a connection and then send/receive messages from it, then Node.js websocket library is the way to go. This does not have much to do with Playwright though.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
