### ISSUE TITLE
[Feature] - Allow attaching links to Test Reports

### ISSUE THREAD

**Issue by ObaidUr-Rahmaan** [microsoft/playwright#27529]
One use-case we have is to be able to attach links to the generated Test Report.

We want folks to be able to click on the attached links (e.g. to relevant logs etc.)

How feasible is this?

Currently I'm just falling back on something like:

```js
testInfo.attachments.push({
    name: `${group} Logs`,
    contentType: 'text/plain',
    body: Buffer.from(url)
})
```

but that just shows the plain text ofc:

<img width="1022" alt="image" src="https://github.com/microsoft/playwright/assets/33055080/3b15d416-772d-4b06-b75c-926cc636db4b">

**Comment by ObaidUr-Rahmaan** [comment]
Maybe there's already a way to do this? - I've had a check in the docs and can't see anything :/

**Comment by dgozman** [comment]
This is what we do in our own tests to get a clickable link in the report:

```ts
test.info().annotations.push({ type: 'issue', description: 'https://github.com/microsoft/playwright/issues/27529' });
```

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
