### ISSUE TITLE
[Feature] Labels for  the actions performed by the tool

### ISSUE THREAD

**Issue by rabindraqa** [microsoft/playwright#27531]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?
Can we have a feature like where we can get the labels for the actions performed by automation in the trace file.
For example 
If i click on the button it  should click the button also it should return what action it did.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
