### ISSUE TITLE
[Question] Document alternatives

### ISSUE THREAD

**Issue by umaar** [microsoft/playwright#2753]
I imagine a number of people are going to arrive to this repo searching for alternatives like webdriver, and other popular browser automation solutions, trying to understand when they should use Playwright.

Maybe the readme/docs could touch upon this? Comparison tables, or a "When to use Playwright" section could be helpful.

I think this can be done, even without singling out an alternative in particular.

**Comment by mxschmitt** [comment]
I fully agree, that a comparison to Cypress/Selenium etc. would be worth it, so that other folks directly see which solution would be the best for their use cases. Relates to #2560 and #2151.

**Comment by umaar** [comment]
Thanks for agreeing but it looks like the authors haven't raised some points [against](https://github.com/microsoft/playwright/issues/2560#issuecomment-650811257) doing this - as you helpfully pointed out. Will close for now
