### ISSUE TITLE
Automatic event monitoring. Random modal click.

### ISSUE THREAD

**Issue by lingdonge** [microsoft/playwright#27541]
The pop-up prompt below randomly appears when accessing the page. 

![image](https://github.com/microsoft/playwright-python/assets/3203693/f4164b76-bcfe-4da7-86f6-8f1c7ccf2554)

Because of randomly appears,i dont know how to handle this modal div tips alert.

How can i effectively determine and click the "Continue" button in the middle to allow the program to proceed automatically?

I wonder if anyone can provide good suggestions.

Currently, I have no way of handling it, and every now and then, the automated program exits because of this. I can only restart the code execution.

It is not possible to add conditional code before every operation step.

Hope someone can help me.

**Comment by MindaugasMateika** [comment]
Not really a suggestion but rather an observation - tests should be deterministic and environment should be testable. Yours aren't. This issue should be fixed from an environment side like not showing this modal in tests based on user agent, some header or something else you can set and control from tests side.

**Comment by dgozman** [comment]
What @MindaugasMateika said - ideally, you should disable the session expiration, or maybe renew the session at the start of your test, or do something else that prevents this issue.

See also #6480 for a similar issue. Let me know whether this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
