### ISSUE TITLE
[BUG] type error when extending a fixture which extends a fixture

### ISSUE THREAD

**Issue by WickyNilliams** [microsoft/playwright#27544]
### System info
- Playwright Version: 1.38.1
- Operating System: macOS 13.4
- Browser: n/a
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```ts
import { test as base } from '@playwright/test'

type MyFixture = {
  user: { firstName: string; lastName: string }
}

const myFixture = base.extend<MyFixture>({
  user: {
    firstName: 'A',
    lastName: 'B',
  },
})

const myOtherFixture = myFixture.extend({
   // Type '{ firstName: string; lastName: string; }' is not assignable to type 'undefined'
  user: {
    firstName: 'C',
    lastName: 'D',
  }
})
```

**Steps**
- typecheck the above test file

Since this is a typescript issue, here's a link to the [typescript playground](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzjApgZ3gQzXARtlOAXzgDMoIQ4ByAATABtMBPAdymAHMALGAelQZqAKGExmYQgFlmAMWAAPGAFcohALyJhcOMrQooALkRlgUDADlMIFMYwcAdpwDccJpeu2494E+LCiUQBjCAcMOBA5RRU1OE18fQA6FCUUBwATAB4ZeSVVFAA+AAoEbV19Iy0dHVIzDxtjagBBagAaMp13GCsGmgAhER0idqIASmDQ8MiAeRhuA1yYjQiovLVk1IySsr4+OAAVCUJqJFrzbs87GEcXN2wL3p8nVyJqOGAcBwgsNDQuB0wuAYhBgEGQRxoygyKFqDhQ6UG5QMxlK1VM5x6XmoAGE2h07vUsQARPFDALjYS7OBBTAOOCsaAAa0wFCh6WQ83ev2UhFwzDgKUYwCCwBgDH5YGwfz8cxBEMlUGs7SpuGU8DmHy5cC+8AguAAbsAIHo4JxgPq0hzCAYKFAIug0JhOChhCEwvAZrKoIt8gB1Jks40ZOIrH3rFKoDLZVZLYqopGVeM1OoPLG49porqYxoksqBMZAA)

**Expected**

This should not cause a type error. If this is not possible due to limits of typescript, then the type parameter should be mandatory.

**Actual**

Causes a type error:

```
Type '{ firstName: string; lastName: string; }' is not assignable to type 'undefined'
```

This can be worked around by explicitly passing a type param (see TS playground), but this is not obvious given the error message.

**Comment by dgozman** [comment]
@WickyNilliams Indeed, this does not compile unless you explicitly use `{}` in the second `extend()` call:

```ts
const myOtherFixture = myFixture.extend<{}>({
   // Type '{ firstName: string; lastName: string; }' is not assignable to type 'undefined'
  user: {
    firstName: 'C',
    lastName: 'D',
  }
})
```

Alternatively, you can skip the shortcut version and specify the full fixture function:

```ts
const myOtherFixture = myFixture.extend({
  user: ({}, use) => use({
    firstName: 'C',
    lastName: 'D',
  }),
})
```

Unfortunately, that's how TS infers the type here. I am not sure we can easily change it to improve the situation, but I'll leave the issue open for now.

**Comment by WickyNilliams** [comment]
thanks for the info @dgozman, i didn't realise there was a longhand for extension also. 

i'm curious what does the `{}` type param signify in the workaround you gave? does it have some semantic meaning in terms of its effect on the types? or is it purely something to get the compiler to play nice?

**Comment by dgozman** [comment]
> i'm curious what does the {} type param signify in the workaround you gave?

It means you are not adding any new fixtures. Otherwise, I think, TypeScript tries to infer you are adding the same `user` fixture from the `extend()` call and something goes wrong.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
