### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by pgarbocz** [microsoft/playwright#27547]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [Ubuntu Latest]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
...
reporter: [
    ['list', {}],
    ['html', { open: 'never' }]
  ],
  use: {
    browserName: 'chromium',
    locale: 'en-GB',
    actionTimeout: 15000,
    baseURL: process.env.FRONTEND_URL,
    trace: 'off',
    video: { mode: process.env.CI ? 'retain-on-failure' : 'on' },
    screenshot: { mode: 'only-on-failure', fullPage: true },
    viewport: { width: 1366, height: 768 }
  }
...
```

**Steps**
- Have a Storage Account configured on Azure.
- Have an Azure Pipeline that runs the tests and copies the HTML report together with the attachments to the Azure Storage
```
...
- script: |
	npm ci
	npm list
	npx playwright install --with-deps chromium
  displayName: 'Install dependencies and browser'
  condition: in(variables['Agent.JobStatus'], 'Succeeded')
  continueOnError: true
- script: |
    CI=true npx playwright test ${{ parameters.additionalRunTestParameters }}
  displayName: 'Run tests'
  condition: in(variables['Agent.JobStatus'], 'Succeeded')
  continueOnError: true
- task: AzureCLI@1
  displayName: 'Copy test report to Azure Storage'
  continueOnError: true
  inputs:
    azureSubscription: '${{ variables.connectedServiceName }}'
    scriptLocation: inlineScript
  inlineScript: |
	az storage blob upload-batch \
	  --account-name ${{ variables.storageAccountName }} \
	  --destination \$web/$(Build.DefinitionName)_$(Build.BuildId) \
	  --source './playwright-report/' \
	  --auth-mode login
```
- On Azure Pipeline run some test that produces video or screenshot which will be attached to the HTML report.
During the copy step in the pipeline, similar logs should be visible:
```
1/4: "index.html"[####################################################]  100.0000%
2/4: "data/b5a1f2197b54d19e3cec58ada5ab88dffab64135.webm"[############]  100.0000%
3/4: "data/f6aa9785bc9c7b8fd40c3f6ede6f59112a939527.png"[#############]  100.0000%
4/4: "data/17b4d1e8ab46c024b910d94ad5ab634a73578b9b.webm"[############]  100.0000%
Finished[#############################################################]  100.0000%
[
  {
    "Blob": "[https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/index.html",](https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/index.html%22,)
    "Last Modified": "2023-10-11T13:33:02+00:00",
    "Type": "text/html",
    "eTag": "\"0x8DBCA5E980BDDE0\""
  },
  {
    "Blob": "[https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/b5a1f2197b54d19e3cec58ada5ab88dffab64135.webm",](https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/b5a1f2197b54d19e3cec58ada5ab88dffab64135.webm%22,)
    "Last Modified": "2023-10-11T13:33:03+00:00",
    "Type": "video/webm",
    "eTag": "\"0x8DBCA5E98115B4F\""
  },
  {
    "Blob": "[https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/f6aa9785bc9c7b8fd40c3f6ede6f59112a939527.png",](https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/f6aa9785bc9c7b8fd40c3f6ede6f59112a939527.png%22,)
    "Last Modified": "2023-10-11T13:33:03+00:00",
    "Type": "image/png",
    "eTag": "\"0x8DBCA5E9816D8C0\""
  },
  {
    "Blob": "[https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/17b4d1e8ab46c024b910d94ad5ab634a73578b9b.webm",](https://storageaccountname.blob.core.windows.net/%24web/e2e-test_111423/data/17b4d1e8ab46c024b910d94ad5ab634a73578b9b.webm%22,)
    "Last Modified": "2023-10-11T13:33:03+00:00",
    "Type": "video/webm",
    "eTag": "\"0x8DBCA5E981D8E87\""
  }
]
```
- Open the HTML report using the URL from the Azure Storage.
- In the report try to open the attached video/screenshot for the test.

**Expected**
The attachments URLs contain the root directory (or the whole path if there are more subdirectories) in which the index.html is stored.

**FYI, all URLs below are not available outside my company, they're here just to show the problem.**

So the attachments from my example should have following URLs in the HTML report:
https://storageaccountname.z6.web.core.windows.net/e2e-test_111423/data/f6aa9785bc9c7b8fd40c3f6ede6f59112a939527.png
https://storageaccountname.z6.web.core.windows.net/e2e-test_111423/data/17b4d1e8ab46c024b910d94ad5ab634a73578b9b.webm

**Actual**
The report is accessible under the address and it opens correctly:
https://storageaccountname.z6.web.core.windows.net/e2e-test_111423

But the attachments have incorrect URL missing the root directory - e2e-test_111423, so they cannot be opened directly in the report:
https://storageaccountname.z6.web.core.windows.net/data/f6aa9785bc9c7b8fd40c3f6ede6f59112a939527.png
https://storageaccountname.z6.web.core.windows.net/data/17b4d1e8ab46c024b910d94ad5ab634a73578b9b.webm

**Comment by dgozman** [comment]
@pgarbocz This exact scenario works for Playwright's own tests. I am not sure what's different with your setup. Could you share the html report file that is uploaded to the storage? That would probably help diagnose the issue.

See also #21636 for a related, but different issue.

**Comment by pgarbocz** [comment]
Ok, I found the issue on my side. My link should be: https://storageaccountname.z6.web.core.windows.net/e2e-test_111423/index.html, not https://storageaccountname.z6.web.core.windows.net/e2e-test_111423

The index.html at the end is the key.
