### ISSUE TITLE
[REGRESSION]: Protocol error (Page.navigate): Invalid url when opening page in custom test fixture

### ISSUE THREAD

**Issue by birtles** [microsoft/playwright#27557]
**Context:**
- GOOD Playwright Version: 1.38
- BAD Playwright Version: 1.39
- Operating System: Linux
- Extra: n/a

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
import { expect, test as base, Page } from '@playwright/test';

export type EditTestFixtures = {
  editPage: EditPage;
};

declare let window: TestEditWindow;

export const test = base.extend<EditTestFixtures, { recycledPage: Page }>({
  recycledPage: [
    async ({ browser, browserName }, use) => {
      const page = await browser.newPage();
      // await page.addInitScript(extendWindow);
      await page.goto('/cards/new');

      await use(page);

      await page.close();
    },
    { scope: 'worker', auto: true },
  ],

  editPage: async ({ recycledPage }, use) => {
    const editPage = new EditPage(recycledPage);
    await use(editPage);

    // `editPage` may disappear if the test is skipped
    if (!editPage) {
      return;
    }

    // Setup
  },
});

export class EditPage {
  constructor(private page: Page) {}
}

export { expect } from '@playwright/test';

// -- Test file

import { test, expect } from './edit-test-fixture';

test.describe('Copying', () => {
  test('Should copy formatted text', async ({ editPage }) => {
    // Do something with editPage
  });
});
```

**Describe the bug**

As of 1.39.0 every test using this fixture fails with:

```
  1) [firefox] › clipboard.test.ts:6:8 › Copying › Should copy formatted text ──────────────────────

    Error: page.goto: Protocol error (Page.navigate): Invalid url: "/cards/new" Page.navigate@chrome://juggler/content/protocol/PageHandler.js:385:13
    dispatch@chrome://juggler/content/protocol/Dispatcher.js:132:39
    _dispatch@chrome://juggler/content/protocol/Dispatcher.js:69:36
    receiveMessage@chrome://juggler/content/components/Juggler.js:117:20

    =========================== logs ===========================
    navigating to "/cards/new", waiting until "load"
    ============================================================

        at page.goto: Protocol error (/home/birtles/project/Page.navigate): Invalid url: "/cards/new" Page.navigate@chrome:/juggler/content/protocol/PageHandler.js:385:13)
        at /home/birtles/project/dispatch@chrome:/juggler/content/protocol/Dispatcher.js:132:39
        at /home/birtles/project/_dispatch@chrome:/juggler/content/protocol/Dispatcher.js:69:36
        at /home/birtles/project/receiveMessage@chrome:/juggler/content/components/Juggler.js:117:20
        at Object.base.extend.recycledPage.scope (/home/birtles/project/tests/edit-test-fixture.ts:24:18)
```

Error occurs with at least chromium and firefox. Loading the same URL directly (i.e. without going via the custom text fixture) works without problem.

**Comment by dgozman** [comment]
@birtles The url `/cards/new` is indeed an invalid url. Do you have `baseURL` set up somewhere? Could you please share your config?

**Comment by dgozman** [comment]
I think has changed in https://github.com/microsoft/playwright/pull/27131.

We do not plan to support things like `baseURL` in the worker-scoped auto fixtures. I'd recommend to remove `auto: true` from your fixture - you don't actually need it automatically, since you explicitly use it in the `editPage` fixture. Let me know whether this helps.

**Comment by birtles** [comment]
Sure, the config is as follows:

```ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './tests',

  // Maximum time one test can run for.
  timeout: 30 * 1000,

  expect: {
    // Maximum time expect() should wait for the condition to be met.
    // For example in `await expect(locator).toHaveText();`
    timeout: 5000,
  },

  // Fail the build on CI if you accidentally left test.only in the source code.
  forbidOnly: !!process.env.CI,

  // Retry on CI only
  retries: process.env.CI ? 2 : 0,

  // Opt out of parallel tests on CI.
  workers: process.env.CI ? 1 : undefined,

  // Reporter to use. See https://playwright.dev/docs/test-reporters
  reporter: process.env.CI ? 'github' : 'list',

  // Shared settings for all the projects below. See
  // https://playwright.dev/docs/api/class-testoptions.
  use: {
    // Maximum time each action such as `click()` can take. Defaults to 0 (no
    // limit).
    actionTimeout: 0,

    // Base URL to use in actions like `await page.goto('/')`.
    baseURL: process.env.CI ? 'http://localhost:3000' : 'http://localhost:8010',

    // Collect trace when retrying the failed test.
    // See https://playwright.dev/docs/trace-viewer
    trace: 'on-first-retry',
  },

  // Configure projects for major browsers
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },

    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    },

    {
      name: 'webkit',
      use: {
        ...devices['Desktop Safari'],
      },
    },
  ],

  // Folder for test artifacts such as screenshots, videos, traces, etc.
  outputDir: 'test-results/',

  // In CI, run local dev server before starting the tests
  webServer: process.env.CI
    ? {
        command: 'yarn start --port 3000 --no-hot --env testApi=true',
        port: 3000,
        timeout: 120 * 1000,
        reuseExistingServer: false,
      }
    : undefined,
};

export default config;
```

> We do not plan to support things like baseURL in the worker-scoped auto fixtures. I'd recommend to remove auto: true from your fixture - you don't actually need it automatically, since you explicitly use it in the editPage fixture. Let me know whether this helps.

Thank you. I'll give that a try later today.

**Comment by birtles** [comment]
> > We do not plan to support things like baseURL in the worker-scoped auto fixtures. I'd recommend to remove auto: true from your fixture - you don't actually need it automatically, since you explicitly use it in the editPage fixture. Let me know whether this helps.
> 
> Thank you. I'll give that a try later today.

Thank you, that appears to do the trick! Regarding this issue, I suppose at least a mention in the release notes would be warranted?

**Comment by dgozman** [comment]
> Thank you, that appears to do the trick!

Wonderful!

> Regarding this issue, I suppose at least a mention in the release notes would be warranted?

This seems to be a rare edge case that's not worth mentioning. This issue will serve as a documentation for anyone stumbling upon, which I do not assume would be many. Thank you for filing!

**Comment by Mocca101** [comment]
For others stumbling onto this, I believe this might also be an issue in the case of overwriting the Storage State fixture. I was building my authentication fixture based on the [Documentation](https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker) however when I tried to use paths relative to the `baseUrl`, I got the same error.

I've worked around that issue, by getting the `baseUrl` from an environment variable, but I'm sure there are better solutions.

My code, most of it is the same as in the documentation, so I've tried highlighting the differences with comments:
```ts
import dotenv from 'dotenv'; // Not in documentation
import { test as baseTest, expect } from '@playwright/test';
import fs from 'fs';
import path from 'path';

export * from '@playwright/test';

dotenv.config({ path: `.env.local`, override: true }); // Get the environment variables for local development

const baseUrl = process.env.TEST_URL ?? `http://localhost:3000`; // Get base URL from env

export const test = baseTest.extend<{}, { workerStorageState: string }>({
  storageState: ({ workerStorageState }, use) => use(workerStorageState),

  workerStorageState: [async ({ browser }, use) => {
    const id = test.info().parallelIndex;
    const fileName = path.resolve(test.info().project.outputDir, `.auth/${id}.json`);

    if (fs.existsSync(fileName) && !process.env.CI) {
      await use(fileName);
      return;
    }

    const page = await browser.newPage({ storageState: undefined });

    const account = {
        // setup the user here
    }

    await page.goto(baseUrl + '/#/login'); // <- works
    // await page.goto( '/#/login'); // <- failed
    
    await page.getByLabel('User').fill(account.username);
    await page.getByLabel('Password').fill(account.password);
    await page.getByRole('button', { name: 'Submit' }).click();

    await expect(page.getByText('successfully logged in')).toBeVisible();

    await page.context().storageState({ path: fileName });
    await page.close();
    await use(fileName);
  }, { scope: 'worker' }],
});
```

**Comment by verticelo** [comment]
>     const page = await browser.newPage({ storageState: undefined });

For others stumbling onto this, you can pass in the baseUrl as an option to the newPage as well so it can be re-used in other helper functions as so:

`
    const page = await browser.newPage({ storageState: undefined, baseUrl: yourObjectHoldingTheBaseUrl.baseUrl });
`

**Comment by genio** [comment]
Is there a way to get this to pass through from evaluatory? Some sitemaps use relative URLs and it just plain doesn't work for playwright

**Comment by MikeDabrowski** [comment]
Also affected by this after upgrading to 1.54.1 (1.53.2 and below are fine). I need `{auto :true}` and `newPage` no longer accepts parameters. I put baseURL to main config and also to `browser.newContext` where I also set `storageState` - didn't help.
