### ISSUE TITLE
[REGRESSION]: deviceDescriptors: expected array, got undefined

### ISSUE THREAD

**Issue by oskarkivra** [microsoft/playwright#27566]
**Context:**
- GOOD Playwright Version: 1.39.0-alpha-oct-2-2023 (and 1.38.1)
- BAD Playwright Version: 1.39.0
- Operating System: Mac
- Extra: -

**Code Snippet**

I am getting the error: `Error: browserType.connect: Error: deviceDescriptors: expected array, got undefined` when using `connectOptions.wsEndpoint`.

```javascript
import { defineConfig } from '@playwright/experimental-ct-react';

export default defineConfig({
  testDir: 'src',
  testMatch: `**/*.spec-ct.tsx`,
  retries: 0,
  use: {
    baseURL: 'some-url',
    connectOptions: {
      wsEndpoint: 'ws://localhost:3000/playwright',
      timeout: 10_000,
    },
  },
});
```

**Describe the bug**

In this case points `ws://localhost:3000/playwright` to a [browserless](https://www.browserless.io/) docker: `docker run -p 3000:3000 browserless/chrome`

When I run `npx playwright test -c playwright-ct.config.ts` I get the following error: `Error: browserType.connect: Error: deviceDescriptors: expected array, got undefined`. But if I downgrade to `1.38.1` or `1.39.0-alpha-oct-2-2023` it works fine.

**EDIT**
It works in 1.39.0-alpha-oct-4-2023 but not in 1.39.0-alpha-oct-5-2023

**Comment by mxschmitt** [comment]
The local Playwright version and the version on the server side of Playwright needs to match, otherwise it results in such errors. Most likely they don't support the latest Playwright version yet as per [here](https://www.browserless.io/docs/versions).

**Comment by oskarkivra** [comment]
@mxschmitt Thanks! I will raise the question at [browserless](https://www.browserless.io/).

It would be nice if Playwright would offer the possibility to only run the browser in a docker container. I should probably open a feature request.
