### ISSUE TITLE
[BUG] Playwright test requests different browser from the one installed

### ISSUE THREAD

**Issue by CEOehis** [microsoft/playwright#27568]
### System info
- Playwright Version: 1.38.1
- Operating System: Ubuntu 22.04.3 LTS (Azure Devops CI)
- Browser: [Chromium]
- Other info:

### Source code

**Actual**
Below is part of the terminal logs during the `npx playwright install --with-deps` step:

```sh
Downloading Chromium 119.0.6045.9 (playwright build v1084) from https://playwright.azureedge.net/builds/chromium/1084/chromium-linux.zip
|                                                                                |   0% of 155.8 Mb
|■■■■■■■■                                                                        |  10% of 155.8 Mb
|■■■■■■■■■■■■■■■■                                                                |  20% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 155.8 Mb
|■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 155.8 Mb
Chromium 119.0.6045.9 (playwright build v1084) downloaded to /home/vsts/.cache/ms-playwright/chromium-1084

```

As you can see it downloaded it to `/home/vsts/.cache/ms-playwright/chromium-1084`.

Afterwards during the actual `playwright test` step, it tries to start the browser from a different path(/home/vsts/.cache/ms-playwright/chromium-1080/):

```sh
    Error: browserType.launch: Executable doesn't exist at /home/vsts/.cache/ms-playwright/chromium-1080/chrome-linux/chrome
    ╔═════════════════════════════════════════════════════════════════════════╗
    ║ Looks like Playwright Test or Playwright was just installed or updated. ║
    ║ Please run the following command to download new browsers:              ║
    ║                                                                         ║
    ║     yarn playwright install                                             ║
    ║                                                                         ║
    ║ <3 Playwright Team                                                      ║
    ╚═════════════════════════════════════════════════════════════════════════╝
```

**Comment by MindaugasMateika** [comment]
What playwright version you're using and do you use yarn or npm in your repository? If you're using yarn then npx will just use global (also latest) package in the internet and install latest browsers even if you're using lower version of Playwright. If you're using yarn then use yarn to install the browsers.

**Comment by greysteil** [comment]
I hit this problem overnight, too. Upgrading to `1.39.0` fixed it.

**Comment by samplehub** [comment]
Hey @MindaugasMateika , 1.39.0  and 1.38.1 didnt work either for us. 
We are using npm install and then npx playwright install --with-deps  commands . 
Can you please let us know what's the correct combination of versions and commands that will work. Thanks

**Comment by CEOehis** [comment]
@MindaugasMateika I use yarn and I have also adapted the install to use `yarn playwright install` for my use case, yet the problem was still there.

Upgrading to `1.39.0` "fixes" it, but there is an underlying problem in how Playwright's releases are set up.

It seems to me that in this case, `npx playwright install --with-deps` (or yarn)  fetched and installed the browsers for the `1.39.0` release (i.e the current latest release) even though I was still on  `@playwright/test` `1.38.1`. Then subsequently when the actual test command needed to start the browser, it looked for the browser executable where it expected to find the browsers for its version - `1.38.1`.

**Comment by MindaugasMateika** [comment]
Dunno wha to say. I'm on 1.38.1 myself and `npx playwright install --with-deps` does nothing for me. Dry run shows that it would download browsers for 1.38.1 if needed. And if I remove downloaded browsers and trigger download again, it downloads browsers for 1.38 and not for 1.39.
```
Downloading Chromium 117.0.5938.62 (playwright build v1080) from https://playwright.azureedge.net/builds/chromium/1080/chromium-mac-arm64.zip
```

**Comment by dgozman** [comment]
@CEOehis Most likely, you have two copies of playwright, of the different version. Try running something like `npm ls @playwright/test` to check.

I also noted that you run `npx playwright install --with-deps`, although playwright detects `yarn` during test execution. Perhaps mixing two package managers could also be the culprit?

If you could share a repro with us, we would be able to take look. Otherwise, it's just guesses.

**Comment by CEOehis** [comment]
I agree.

I eventually figured out the issue with the installation in my project. 

In trying to adapt the `npx playwright install --with-deps` command in the docs with yarn, we had `yarn dlx playwright install --with-deps`. It appears that it `yarn dlx` behaves differently from `npx`. `npx` respects the installed version while yarn installs playwright first (which in this case was fetching the latest version).
