### ISSUE TITLE
[BUG] playwright._impl._api_types.Error: Protocol error (Page.printToPDF): Printing failed

### ISSUE THREAD

**Issue by mlalyko** [microsoft/playwright#27567]
### System info
- Playwright Version: [v1.38]
- Operating System: [Docker container: https://hub.docker.com/r/flyingjoe/uvicorn-gunicorn-fastapi]
- Browser: [Chromium in debian container]

### Source code
```
    async def _generate_pdf(self, html_string: str, playwright: Playwright, browser_url: str) -> None:
        """Generates PDF from html string using playwright (Chromium engine)."""
        browser = await playwright.chromium.connect_over_cdp(browser_url, timeout=10000)
        default_context = browser.contexts[0]
        page = await default_context.new_page()
        await page.set_content(html_string)
        await page.pdf(
            path=self.temp_output_path,
            format=self.request_data.format,
            print_background=self.request_data.print_background,
            landscape=self.request_data.landscape,
            display_header_footer=self.request_data.display_header_footer,
            prefer_css_page_size=self.request_data.prefer_css_page_size,
            margin={
                'top': self.request_data.margin_top,
                'bottom': self.request_data.margin_bottom,
                'left': self.request_data.margin_left,
                'right': self.request_data.margin_right,
            },
            scale=self.request_data.scale,
        )
        await page.close()
```

**Expected**
Generated pdf file.

**Actual**
html-to-pdf-web_1    | 2023-10-12 09:56:48,416 - web_logger - ERROR - Protocol error (Page.printToPDF): Printing failed
html-to-pdf-web_1    | Traceback (most recent call last):
html-to-pdf-web_1    |   File "main.py", line 55, in convert_html_report_to_pdf
html-to-pdf-web_1    |     await html_converter.convert()
html-to-pdf-web_1    |   File "/app/html_to_pdf_converter.py", line 28, in convert
html-to-pdf-web_1    |     await self._generate_pdf(
html-to-pdf-web_1    |   File "/app/html_to_pdf_converter.py", line 60, in _generate_pdf
html-to-pdf-web_1    |     await page.pdf(
html-to-pdf-web_1    |   File "/usr/local/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11948, in pdf
html-to-pdf-web_1    |     await self._impl_obj.pdf(
html-to-pdf-web_1    |   File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 994, in pdf
html-to-pdf-web_1    |     encoded_binary = await self._channel.send("pdf", params)
html-to-pdf-web_1    |   File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 61, in send
html-to-pdf-web_1    |     return await self._connection.wrap_api_call(
html-to-pdf-web_1    |   File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call
html-to-pdf-web_1    |     return await cb()
html-to-pdf-web_1    |   File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 97, in inner_send
html-to-pdf-web_1    |     result = next(iter(done)).result()
html-to-pdf-web_1    | playwright._impl._api_types.Error: Protocol error (Page.printToPDF): Printing failed

**Description**
The problem occurs when i try to convert many htmls with graphic (total weight of result pdf is more than 5mb). If i create smaller pdfs - it works well. Found issue topic in puppeteer: https://github.com/puppeteer/puppeteer/issues/8070. But there is no solution.

**Comment by mlalyko** [comment]
> @mlalyko This seems to be a Chromium limitation.

Maybe you know how to avoid that? I tried to raise docker limits. But it haven't helped me.

**Comment by shankar-narayanan-d** [comment]
> ### System info
> * Playwright Version: [v1.38]
> * Operating System: [Docker container: https://hub.docker.com/r/flyingjoe/uvicorn-gunicorn-fastapi]
> * Browser: [Chromium in debian container]
> 
> ### Source code
> ```
>     async def _generate_pdf(self, html_string: str, playwright: Playwright, browser_url: str) -> None:
>         """Generates PDF from html string using playwright (Chromium engine)."""
>         browser = await playwright.chromium.connect_over_cdp(browser_url, timeout=10000)
>         default_context = browser.contexts[0]
>         page = await default_context.new_page()
>         await page.set_content(html_string)
>         await page.pdf(
>             path=self.temp_output_path,
>             format=self.request_data.format,
>             print_background=self.request_data.print_background,
>             landscape=self.request_data.landscape,
>             display_header_footer=self.request_data.display_header_footer,
>             prefer_css_page_size=self.request_data.prefer_css_page_size,
>             margin={
>                 'top': self.request_data.margin_top,
>                 'bottom': self.request_data.margin_bottom,
>                 'left': self.request_data.margin_left,
>                 'right': self.request_data.margin_right,
>             },
>             scale=self.request_data.scale,
>         )
>         await page.close()
> ```
> 
> **Expected** Generated pdf file.
> 
> **Actual** html-to-pdf-web_1 | 2023-10-12 09:56:48,416 - web_logger - ERROR - Protocol error (Page.printToPDF): Printing failed html-to-pdf-web_1 | Traceback (most recent call last): html-to-pdf-web_1 | File "main.py", line 55, in convert_html_report_to_pdf html-to-pdf-web_1 | await html_converter.convert() html-to-pdf-web_1 | File "/app/html_to_pdf_converter.py", line 28, in convert html-to-pdf-web_1 | await self._generate_pdf( html-to-pdf-web_1 | File "/app/html_to_pdf_converter.py", line 60, in _generate_pdf html-to-pdf-web_1 | await page.pdf( html-to-pdf-web_1 | File "/usr/local/lib/python3.8/site-packages/playwright/async_api/_generated.py", line 11948, in pdf html-to-pdf-web_1 | await self._impl_obj.pdf( html-to-pdf-web_1 | File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_page.py", line 994, in pdf html-to-pdf-web_1 | encoded_binary = await self._channel.send("pdf", params) html-to-pdf-web_1 | File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 61, in send html-to-pdf-web_1 | return await self._connection.wrap_api_call( html-to-pdf-web_1 | File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 482, in wrap_api_call html-to-pdf-web_1 | return await cb() html-to-pdf-web_1 | File "/usr/local/lib/python3.8/site-packages/playwright/_impl/_connection.py", line 97, in inner_send html-to-pdf-web_1 | result = next(iter(done)).result() html-to-pdf-web_1 | playwright._impl._api_types.Error: Protocol error (Page.printToPDF): Printing failed
> 
> **Description** The problem occurs when i try to convert many htmls with graphic (total weight of result pdf is more than 5mb). If i create smaller pdfs - it works well. Found issue topic in puppeteer: [puppeteer/puppeteer#8070](https://github.com/puppeteer/puppeteer/issues/8070). But there is no solution.

Try updating the playwright version to 1.39.0. It worked for me

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
