### ISSUE TITLE
[BUG]When upload a binary file with APIRequestContext,  it will insert some information into the binary file

### ISSUE THREAD

**Issue by Helen109** [microsoft/playwright#27563]
### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
// Open file as a stream and pass it to the request:
const stream = fs.createReadStream('team.csv');
await request.fetch('https://example.com/api/uploadTeamList', {
  method: 'post',
  multipart: {
    fileField: stream
  }
});

**Expected**
Don't add any extra information into the binary file

**Actual**   
Following information added to the top of the binary file:
### 

> ------WebKitFormBoundaryNBy7bTmIQTnCc1ud
> content-disposition: form-data; name="fileField"; filename="Fault_Blocks.bin"
> content-type: application/octet-stream
Following information added to the butom of the binary file:
------WebKitFormBoundaryNBy7bTmIQTnCc1ud

**Comment by dgozman** [comment]
@Helen109 That's how multipart post body works. Here is [an example](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/POST#example). Let me know whether this helps.

**Comment by Helen109** [comment]
hi @dgozman thank you for your feedback.I can update binary .bin file successfully now, but it will add some extra data to the binary bin file like request header like below picture. So how can I remove the extra data or which method will not add these kind of data to the file. Cause I need the original file. Thank you very much.
![Screenshot 2023-10-13 164520](https://github.com/microsoft/playwright/assets/54786701/f01c8479-34fc-44c9-bb26-bb26fd6ab5ac)

**Comment by dgozman** [comment]
@Helen109 Do you need any specific format on the server? I'd recommend consulting with the server expectations or whoever owns the server. Playwright is following HTTP spec here, so if you need any specific HTTP behavior - let us know. However, I think that we cover most usecases.

**Comment by Helen109** [comment]
hi @dgozman, I don't need any specific HTTP behavior. I just want to upload a pure file I mean the original file to server like postman did instead of add some extra information to the file.
May I ask which kind of method can do that with playwright?
