### ISSUE TITLE
[Feature] Playwright-Firebase plugin interest? 

### ISSUE THREAD

**Issue by Ademsk1** [microsoft/playwright#27569]
Hey folks
This isn't much of a feature request, but couldn't see a more appropriate issue-type. I recently worked on and published a plugin for Playwright for automatic Firebase authentication without requiring the username and password to be placed in [here](https://www.npmjs.com/package/@nearform/playwright-firebase). Would be fantastic to get a dev from Playwright to have a look and see whether it's worth it's salt :D. Would you recommend this to your user-base? 

If this is not an appropriate place to ask for this, please direct me in the right place 😄

**Comment by dgozman** [comment]
@Ademsk1 In v1.39, we have just released [a way to merge fixtures](https://github.com/microsoft/playwright/releases/tag/v1.39.0) from "plugins" like yours. I'd recommend trying that out and telling us whether it works for you.

I didn't take a thorough look at the code, but overall you seem to be adding a fixture and that looks good.

Unfortunately, we do not recommend plugins like this officially. However, you can always gather some feedback from [the community](https://playwright.dev/community/welcome), for example by posting at our Discord server.

**Comment by Ademsk1** [comment]
@dgozman thanks a lot! I'll give that a try and see what others think ☺️

**Comment by dgozman** [comment]
Closing this issue, since there is no action item for Playwright here.
