### ISSUE TITLE
[REGRESSION]: firefox headless times out on click

### ISSUE THREAD

**Issue by alexmalev** [microsoft/playwright#27570]
**Context:**
- GOOD Playwright Version: 1.38.1
- BAD Playwright Version: 1.39.0
- Operating System: playwright docker mcr.microsoft.com/playwright:v1.25.0-focal

```javascript
async clickOnUser(): Promise<void> {
    const locator = this.page.locator(`div[data-identifier="${this.loginProperties.email}"]`);
    await expect(locator).toContainText(this.loginProperties.email, { timeout: 5000 });
    await locator.click({ timeout: 20000 });
  }
```

**Describe the bug**

we have tests running on firerfox headless in docker that perform a login in google with a preglogged in user (global setup).
the user session is created succesfully but when we go and click on the user in the list (which is indeed performed) the click action simply times out (regardless of how big is the timeout). this did not happen in version 1.38.1 but happens all the time in version 1.39.0. i've downgraded back and it is working again in 1.38.1.

it trace viewer i see a bunch of webGl related lines but not sure if its related. 
not sure if it is a playwright version problem- or the firefox version that comes with the new playwright version

this is the console output
```
locator.click: Timeout 20000ms exceeded.
=========================== logs ===========================
waiting for locator('div[data-identifier="admin@some-test-domain.com"]')
  locator resolved to <div null="" role="link" tabindex="0" jsname="MBVUVe"…>…</div>
attempting click action
  waiting for element to be visible, enabled and stable
  element is visible, enabled and stable
  scrolling into view if needed
  done scrolling
  performing click action
============================================================
```
the image clearly shows that the element was indeed located and clicked.

![image](https://github.com/microsoft/playwright/assets/12444892/10af9717-89f9-4029-86bc-7a9f0a1c95ff)

some webGl info from trace viewer console logs

```
 JavaScript Warning: "WebGL warning: <Create>: WebglAllowWindowsNativeGl:false restricts context creation on this system." {file: "https://accounts.google.com/o/oauth2/auth?prompt=select_account&response_type=code&redirect_uri=https%3A%2F%2F<redacted>.com%2Flogin%2Fcallback&scope=email%20profile&client_id=redacted line 2 > eval line 7537 > eval line 1 > eval line 1 > eval" line: 1}]
6.8s
auth?prompt=select_account&response_type=code&redirect_uri=https%3A%2F%2F<redacted>.com%2Flogin%2Fcallback&scope=email%20profile&client_id=redacted line 2 > eval line 7537 > eval line 1 > eval line 1 > eval:1
[JavaScript Warning: "Failed to create WebGL context: WebGL creation failed: 
* WebglAllowWindowsNativeGl:false restricts context creation on this system. ()
* Exhausted GL driver options. (FEATURE_FAILURE_WEBGL_EXHAUSTED_DRIVERS)" {file: "https://accounts.google.com/o/oauth2/auth?prompt=select_account&response_type=code&redirect_uri=https%3A%2F%2F<redacted>.com%2Flogin%2Fcallback&scope=email%20profileclient_id=redacted line 2 > eval line 7537 > eval line 1 > eval line 1 > eval" line: 1}]

```

**Comment by dgozman** [comment]
@alexmalev We need more information to act on this issue.
- Could you please provide a repro that we can run locally? 
- Are you using `mcr.microsoft.com/playwright:v1.25.0-focal` with Playwright v1.39? You should keep the two versions in sync.
