### ISSUE TITLE
[REGRESSION]:  deviceDescriptors: expected array, got undefined

### ISSUE THREAD

**Issue by apis3445** [microsoft/playwright#27576]
**Context:**
- GOOD Playwright Version: 1.38.1
- BAD Playwright Version: 1.39.0
- Operating System: Mac
- Extra: Playwright VS Code Extension 

**Code Snippet**

This is my playwright.config.ts

```typescript
import { defineConfig, devices } from '@playwright/test';
import dotenv from 'dotenv';

dotenv.config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({

    testDir: './tests',
    globalSetup: require.resolve('./globalSetup'),
    /* Maximum time one test can run for. */
    timeout: 30 * 1000,

    expect: {
        timeout: 5_000
    },

    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!process.env.CI,

    retries: process.env.RETRY ? +process.env.RETRY : 1,

    /* Opt out of parallel tests on CI. */
    workers: process.env.WORKERS ? +process.env.WORKERS : 1,

    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: [
        ['html', { open: 'never' }],
        ['junit', { outputFile: 'results.xml' }],
    ],

    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {

        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: 5_000,

        /* Base URL to use in actions like `await page.goto('/')`. By default should be test */
        baseURL: process.env.BASE_URL ? process.env.BASE_URL : 'https://google.com,

        acceptDownloads: true,

        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'retain-on-failure',

        // https://playwright.dev/docs/test-configuration#automatic-screenshots //
        screenshot: 'only-on-failure',

        // https://playwright.dev/docs/test-configuration#record-video //
        video: 'retain-on-failure'
    },

    /* Configure projects for major browsers */
    projects: [
        {
            name: 'chromium',
            use: {
                ...devices['Desktop Chrome'],
            },
        },
        {
            name: 'firefox',
            use: {
                ...devices['Desktop Firefox'],
            },
        },
        {
            name: 'webkit',
            use: {
                ...devices['Desktop Safari'],
            },
        },
     
    ]


});

```

**Describe the bug**

I can't debug or un any test  with the playwright VS Code Extension with the Playwright version 1.39.0 I got an error: 
Error: browserType.connect: Error: deviceDescriptors: expected array, got undefined.
Run in terminal with the command 
```
npx playwright test --project=chromium --headed 
```
runs correctly

And if I downgrade to 1.38.1 I can debug or run any test

**Comment by dgozman** [comment]
@apis3445 I think you need to restart the browser that is used by VSCode extension. Could you please uncheck and then check the "Show browser" checkbox? Let me know whether that helps.

**Comment by apis3445** [comment]
I already did that I had to restart the laptop remove node modules reinstall and works

**Comment by dgozman** [comment]
@apis3445 Next time, just restarting VSCode should fix the issue. If it does not, please let us know and we'll try to investigate. Meanwhile, we will improve the error message.

**Comment by amanUrRahman** [comment]
I am getting this same error while my tests run on CI. I don't see any issues running my tests locally, in debug mode, or on the grid from my local.
Only when I run on the grid, this error comes up **Error: browserType.connect: Error: deviceDescriptors: expected array, got undefined**
It is very difficult to debug this issue as well. This is my config file
`import { defineConfig, devices } from '@playwright/test';
import { moonURL, reporterConfig } from './test/smoke/utils/common';
import {
    TEST_TIMEOUT_MILLISECONDS,
    EXPECT_TIMEOUT_MILLISECONDS,
    ACTION_TIMEOUT_MILLISECONDS,
} from './test/smoke/utils/constants';

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
    expect: {
        /**
         * Maximum time expect() should wait for the condition to be met.
         * For example in `await expect(locator).toHaveText();`
         */
        timeout: EXPECT_TIMEOUT_MILLISECONDS,
    },
    /* Fail the build on CI if you accidentally left test.only in the source code. */
    forbidOnly: !!process.env.CI,
    /* Run tests in files in parallel */
    fullyParallel: true,
    /* Folder for test artifacts such as screenshots, videos, traces, etc. */
    outputDir: './test/smoke/output',
    projects: [
        {
            name: 'Desktop',
            use: {
                ...devices['Desktop Firefox'],
                connectOptions: process.env.CI ? { wsEndpoint: moonURL('firefox') } : undefined,
            },
        },
        {
            name: 'Tablet',
            testIgnore: '/ads/*.test.ts',
            use: {
                ...devices['Desktop Firefox'],
                viewport: {
                    width: 768,
                    height: 1024,
                },
                connectOptions: process.env.CI ? { wsEndpoint: moonURL('firefox') } : undefined,
            },
        },
        {
            name: 'Tablet',
            testMatch: '/ads/*.test.ts',
            use: {
                ...devices['iPad Mini'],
                connectOptions: process.env.CI ? { wsEndpoint: moonURL('webkit') } : undefined,
            },
        },
        {
            name: 'Mobile',
            use: {
                ...devices['Moto G4'],
                connectOptions: process.env.CI ? { wsEndpoint: moonURL('chromium') } : undefined,
            },
        },
    ],
    /* Reporter to use. See https://playwright.dev/docs/test-reporters */
    reporter: reporterConfig(),
    /* Retry on CI only */
    retries: process.env.CI ? 1 : 0,
    /* Test directory for the tests */
    testDir: `./test/smoke/tests/${process.env.APP_INSTANCE}`,
    /* Maximum time one test can run for. */
    timeout: TEST_TIMEOUT_MILLISECONDS,
    /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
    use: {
        acceptDownloads: false,
        /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
        actionTimeout: ACTION_TIMEOUT_MILLISECONDS,
        headless: false,
        screenshot: 'only-on-failure',
        /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
        trace: 'on-first-retry',
        /* video size is viewport dimensions * 0.75 to balance keeping video file sizes down vs reasonable recording quality */
        video: {
            mode: 'on-first-retry',
            size: {
                height: 765,
                width: 1320,
            },
        },
    },
    /* Opt out of parallel tests on CI. */
    workers: process.env.CI ? 2 : 1,
});
`

**Comment by dgozman** [comment]
@amanUrRahman That's because you are connecting to the server that runs a different Playwright version. You should make sure that versions match.

```ts
connectOptions: process.env.CI ? { wsEndpoint: moonURL('webkit') } : undefined,
```

**Comment by amanUrRahman** [comment]
Okay, We use Moon for our grid. And does it not consider specifying a version in the URL formation.

This is what we are doing. Does the server running the service also maintain playwright version? Coz in that case, if someone has different repos with different playwright versions, How is that handled? would it not cause a problem?

```
export const moonURL = (browser: string): string => {
    const version = packages.devDependencies['@playwright/test'].replace(/[^\d.]/g, '');
    const browserImage = `playwright/${browser}/playwright-${version}`;
    return `wss://${process.env.MOON_USERNAME}:${process.env.MOON_PASSWORD}@infrastructure-browser-testing-production-v1.9pub.io/${browserImage}`;
};
```

**Comment by dgozman** [comment]
@amanUrRahman I think you should ask Moon about this, not Playwright. We do not know the details about Moon.

**Comment by amanUrRahman** [comment]
I was able to resolve the issue by bumping up the version to 1.38.1
Maybe it was a version mismatch, don't know, but will investigate it. Thanks for the replies.
