### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by pardoman** [microsoft/playwright#27579]
Hello, 

I looked into the documentation and couldn't find anything like this, so I'm making a feature request. If there's already another way to do this, I'd love to know about it.

On to the feature request...

In [Webdriverio](https://webdriver.io/docs/configurationfile/), a developer can provide a `beforeTest` function, which gets executed before each test, globally (for every file). I would like to have something like that in playwright (we have migrated our tests from webdriverio to playwright). Most of our features have been successfully migrated, except for one that relies on this configuration function.

```js
    /**
     * Function to be executed before a test (in Mocha/Jasmine only)
     * @param {object} test    test object
     * @param {object} context scope object the test was executed with
     */
    beforeTest: function (test, context) {
    }
```

The `test` argument is an object that contains attributes:
- `title` string - this is the value passed to the `test` function, ie: for `test("hello", () => {})`, title would be `"hello"`.
- `parent` string - this is the value passed to the `test.describe` function, ie: for `test.describe("stuff", () => {})`, parent would be `"stuff"`.

We use this configuration function to create an overlay over the test, which displays which test is currently being run, so that our automation video recording (ie: automate.browserstack.com) includes that text onscreen.

And while we're at it, adding a matching `afterTest` function would be great.

Thanks

**Comment by dgozman** [comment]
@pardoman Are you looking for an [auto-fixture](https://playwright.dev/docs/test-fixtures#automatic-fixtures)? If you could be more detailed at what you'd like to do in the `beforeTest`, with some code snippet, we'll be able to help better.

**Comment by pardoman** [comment]
@dgozman thanks for your reply.

I've read the documentation for auto-fixtures, and I'm not sure it's exactly what I'm looking for.

The auto-fixtures documentation states that the `test` function will end up receiving an extra parameter, and then in my test I would manually have to make use of the extra parameter. 

ie:
```ts
test("hello, ({ newThing }) => {
   newThing();
  //...
});
```

That's not what I'm trying to achieve. I don't want to have to invoke `newThing()` manually in my tests. I want Playwright to call that function before any-and-all of my tests.

I then tried to setup one of these auto-fixtures in the `globalSetup` script, which is specified in the config file, but failed to make it work. I wasn't able to extend `test` from there, in a way that is global and automatic.

**Comment by dgozman** [comment]
@pardoman Auto fixtures are different from regular fixtures.

 > Automatic fixtures are set up for each test/worker, even when the test does not list them directly.

That's what documentation says. You don't have to list/use them directly, they are automatically executed for each test.

I'd recommend reading [creating a fixture](https://playwright.dev/docs/test-fixtures#creating-a-fixture) and [using a fixture](https://playwright.dev/docs/test-fixtures#using-a-fixture) sections to get familiar with fixtures. Basically, instead of importing `test` from `@playwright/test`, you would create your own `test` in a separate file, and import that. This way, all tests created with this new `test` function will run your automatic fixture without any changes in the test.

Let me know whether this helps. Feel free to share your code with fixtures - I should be able to point at problems.

**Comment by pardoman** [comment]
Gotcha, thanks. I was trying to avoid having to change all my `import { test } from "@playwright/test"` to something else, but it sounds that that's the way to go.

**Comment by dgozman** [comment]
@pardoman Yeah, I don't see a way without changing your imports. On the bright side, you only change imports once and then you can add a lot of features through your own fixtures later on. Please let me know whether you were able to achieve the desired outcome.

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by pardoman** [comment]
@dgozman I'll report back when I have some results. I haven't had time to look at this further. Thanks again.

**Comment by pardoman** [comment]
Alright so in the end our solution is:

```ts
import { test as base } from "@playwright/test";

export const test = base.extend({
  page: async ({ page }, use, testInfo) => {
    await createPageSteps(testInfo, page, use);
  }
});
```

where `createPageSteps` is our custom function for settings things up.

Thanks for the help.
