### ISSUE TITLE
ECONNREFUSED error when connecting to Selenoid

### ISSUE THREAD

**Issue by ShivaPotlapelli** [microsoft/playwright#27589]
=========================== logs ===========================
<selenium> using additional capabilities "{"browserName":"chrome","selenoid:options":{"enableVNC":true,"enableVideo":false,"name":"PW_Selenoid_UI/UX_Suite","sessionTimeout":"30m","labels":{"manual":"true"}},"goog:chromeOptions":{"args":["--test-type","--no-sandbox","--disable-dev-shm-usage"],"prefs":{"profile.content_settings.exceptions.clipboard":{"[.],":{"last_modified":"1576491240619","setting":1}}}}"
<selenium> connecting to http://65.25.56.109:4444/wd/hub/
<selenium> connected to sessionId=d118db2eed15342bc62574b1c13b4a73
<selenium> using selenium v3
<selenium> retrieved endpoint http://127.0.0.1:36303/ for sessionId=d118db2eed15342bc62574b1c13b4a73
<selenium> unable to resolve endpoint ip for sessionId=d118db2eed15342bc62574b1c13b4a73, running in standalone?
<ws preparing> retrieving websocket url from http://127.0.0.1:36303/
selenium> disconnecting from sessionId=d118db2eed15342bc62574b1c13b4a73
<selenium> disconnected from sessionId=d118db2eed15342bc62574b1c13b4a73

**Comment by ShivaPotlapelli** [comment]
@DudaGod can u help me out here if possible as u have done some remote connections to selenoid

**Comment by ShivaPotlapelli** [comment]
Steps to Reproduce:
  Create a Playwright script to connect to Selenoid by passing SELENIUM REMOTE URL and 
  SELENIUM_REMOTE_CAPABILITIES.

**Expected Behavior**
I expected to connect to Selenoid and retrieve the CDP endpoint without errors.

**Actual Behavior**
I received the following ECONNREFUSED error message when running the Playwright script:

**Comment by DudaGod** [comment]
Hello.

There is a message in your log - `using selenium v3` from [this code](https://github.com/microsoft/playwright/blob/f8a30fb726bc35d4058a2d010b2ed5f6ca2409a3/packages/playwright-core/src/server/chromium/chromium.ts#L239).

It means that there is no `se:cdp` capability in response from selenoid. Looks like you use old selenoid version. You should use [latest release](https://github.com/aerokube/selenoid/releases/tag/1.11.0) in which add `se:cdp` capability to be able to connect from playwright.

**Comment by ShivaPotlapelli** [comment]
Yes @DudaGod
I am using Selenoid 1.10.9! will upgrade and check if issue still exsists

**Comment by dgozman** [comment]
It looks like there is no action item from Playwright side. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by ShivaPotlapelli** [comment]
@DudaGod I am seeing this error now...
{
    "value": {
        "error": "session not created",
        "message": "session not created: Chrome failed to start: exited normally.\n  (session not created: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)",
        "stacktrace": "#0 0x00400071f6b3 <unknown>\n#1 0x0040003f51e7 <unknown>\n#2 0x004000428526 <unknown>\n#3 0x00400042469c <unknown>\n#4 0x00400046723a <unknown>\n#5 0x00400045de93 <unknown>\n#6 0x004000430934 <unknown>\n#7 0x00400043171e <unknown>\n#8 0x0040006e4cb8 <unknown>\n#9 0x0040006e8bf0 <unknown>\n#10 0x0040006f319c <unknown>\n#11 0x0040006e9808 <unknown>\n#12 0x0040006b627f <unknown>\n#13 0x00400070de88 <unknown>\n#14 0x00400070e059 <unknown>\n#15 0x00400071e843 <unknown>\n#16 0x004002a7bb43 <unknown>\n"
    }
}
