### ISSUE TITLE
[Question][BUG] Node.js 18 Error: unsafe legacy renegotiation disabled

### ISSUE THREAD

**Issue by Askarov5** [microsoft/playwright#27583]
Node.js 18 doesn't allow legacy TLS renegotiation by default. But some APIs I'm testing needs to bypass otherwise I'm getting the following error:
`apiRequestContext.post: write EPROTO 743D0000:error:0A000152:SSL routines:final_renegotiate:unsafe legacy renegotiation disabled:c:\ws\deps\openssl\openssl\ssl\statem\extensions`

Can we allow legacy renegotiation in the request? Based on this solution: https://johnnyreilly.com/node-18-axios-and-unsafe-legacy-renegotiation-disabled

**Comment by dgozman** [comment]
Perhaps you should follow this [SO question](https://stackoverflow.com/questions/74324019/allow-legacy-renegotiation-for-nodejs/74600467#74600467) and pass `--openssl-config` option. You can do that in the env:
```ts
NODE_OPTIONS="--openssl-config=..." npx playwright test
```

Let me know whether this helps.

**Comment by Askarov5** [comment]
I'm seeing an error: unknown option on the following cases: npx playwright test --openssl-config=./openssl.cnf
This option didn't work for me: SET NODE_OPTIONS=--openssl-legacy-provider && npx playwright test
can you share the full example of the script?

**Comment by dgozman** [comment]
@Askarov5 I cannot share the full example, because I do not have this ssl issue to test with.

Here is another command that might work for you:

```ts
node --openssl-config="..." node_modules/.bin/playwright test
```

**Comment by Askarov5** [comment]
![image](https://github.com/microsoft/playwright/assets/13361800/d50726b9-d47d-4b4f-8bd8-318b8adca11c)

**Comment by dgozman** [comment]
@Askarov5 I guess you are using some other package manager rather than npm. My last suggestion, not sure how else I can help:

```ts
node --openssl-config="..." node_modules/@playwright/test/cli.js test
```

Overall, it seems like openssl config is the way to go. I don't see any action item from the Playwright side here, so I'll close this issue. If you figure out the solution, posting it here would probably benefit others that face the similar issue.

**Comment by Askarov5** [comment]
> @Askarov5 I guess you are using some other package manager rather than npm. My last suggestion, not sure how else I can help:
> 
> ```ts
> node --openssl-config="..." node_modules/@playwright/test/cli.js test
> ```
> 
> Overall, it seems like openssl config is the way to go. I don't see any action item from the Playwright side here, so I'll close this issue. If you figure out the solution, posting it here would probably benefit others that face the similar issue.

This worked. Thank you!

**Comment by baijiu-in-my-cup** [comment]
Hello, I'm currently encountering this issue, but I'm using Python Playwright. Could you please advise how I can resolve it? ┭┮﹏┭┮
