### ISSUE TITLE
[BUG] No access to network details while the test is running

### ISSUE THREAD

**Issue by mgozman-twist** [microsoft/playwright#27584]
### System info
- Playwright Version: [v1.0.16]
- Operating System: [macOS 13.2]
- Browser: []
- Other info: UI Mode

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

Null

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

Not provided.

**Steps**
- Run the test in UI Mode
- Go to the Network Panel
- Try to get the details of any API call

**Expected**

The details of the API call should expand

**Actual**

The details of the API call don't expand

**Important Note**

The bug only occurs only while the test is running. 

https://github.com/microsoft/playwright/assets/117313996/dc63b0fe-01ce-4b4f-9a35-e138ac6cbc6d

**Comment by mgozman-twist** [comment]
@dgozman Is this ticket not valid anymore with a new version of Playwright?

**Comment by dgozman** [comment]
@mgozman-twist Yep, new UI does not have this issue. Thank you for filing!
