### ISSUE TITLE
[Feature] Allow toggling offline mode without relaunching the ElectronApplication

### ISSUE THREAD

**Issue by boutchersj** [microsoft/playwright#27599]
I'm working with an Electron app that requires an internet connection to get from Screen 1 to Screen 2. Screen 2 has a feature that throws a toast with an error message if the user is offline.

Because the user has to launch the app in offline mode in order to go offline, we can't test offline scenarios on Screen 2. We need internet to pass Screen 1, so we can never have offline mode on Screen 2.

I can imagine this would affect any applications that don't have "Remember Me" for their login feature. There are likely other scenarios toggling offline would be useful.

**Comment by dgozman** [comment]
@boutchersj Take a look at [`browserContext.setOffline()`](https://playwright.dev/docs/api/class-browsercontext#browser-context-set-offline) method:

```ts
await electronApplication.context().setOffline(true);
```

Let me know whether this helps.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.
