### ISSUE TITLE
[BUG] clear() method cannot be used even though the tag is [contenteditable] element

### ISSUE THREAD

**Issue by thanhbinhbent** [microsoft/playwright#27593]
Hi team,
I have a problem updating the content on the `[contenteditable]` tag, even though the result is a tag with `contenteditable = "true" `... but I can't use the `clear() `method to clear the content on the tag before typing a new value. You can refer to the attached photo.
Hopefully the problem will be fixed

<img width="973" alt="Screenshot 2023-10-13 at 16 37 26" src="https://github.com/microsoft/playwright/assets/114393099/0e11bbec-b765-4adb-91e9-c81512e8022c">

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
