### ISSUE TITLE
[BUG] pages().length not change after inner page window.open()

### ISSUE THREAD

**Issue by yangguansen** [microsoft/playwright#27595]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [macOS 12.0.1]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://www.baidu.com');
  console.log(page.context().pages().length); // 1
  await page.evaluate(() => {
  window.open('https://www.qq.com', '_blank');
  });
  console.log(page.context().pages().length); //1 
});
```

**Steps**
- I have a js sentence that `window.open(new page)` at my page
- I want to test the new page if can be open, something  like check new page content, url
- But I can not get new page 

**Expected**

[Describe expected behavior]
The second time page.context().pages().length should be 2
**Actual**

[Describe actual behavior]
page.context().pages().length always is 1

**Comment by dgozman** [comment]
@yangguansen You should actually wait for the page to open. Take a look at [this guide](https://playwright.dev/docs/pages#handling-new-pages).

```ts
it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://www.baidu.com');
  console.log(page.context().pages().length); // 1

  // Create a promise.
  const pageOpenedPromise = page.context().waitForEvent('page');

  await page.evaluate(() => {
    window.open('https://www.qq.com', '_blank');
  });

  // Wait for the page.
  await pageOpenedPromise;

  console.log(page.context().pages().length); //1 
});
```

Let me know whether this helps.

**Comment by yangguansen** [comment]
Yes, it works， thank u!
