### ISSUE TITLE
[BUG] Playwright CLI can't find tests with special characters in the test title while using '-g' option

### ISSUE THREAD

**Issue by pradeipp** [microsoft/playwright#27594]
### System info
- Playwright Version: [v1.XX] 1.38.1
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] Windows 11
- Browser: [All, Chromium, Firefox, WebKit] Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```js
test('Test with a+ sign', async ({ page }) => {
  console.log("This should pass with the + sign in the test title but it wont.")
});
```

**Steps**
- run the `npx playwright test -g "Test with a+ sign"`

**Expected**

The cli should find the test and execute it, printing the "This should pass with the + sign in the test title but it wont." message.
**Actual**

The command results in `Error: No tests found`.

**Comment by kacy-weakley** [comment]
The `grep` command line option uses regex to pattern match (https://playwright.dev/docs/api/class-testproject#test-project-grep). The plus symbol is a special regex character, so you'd need to escape it by prefixing it with a \. In other words, `npx playwright test -g "Test with a\+ sign"` should work.

**Comment by dgozman** [comment]
Closing as per above. If you still encounter problems, please file a new issue with a repro and link to this one.

**Comment by pradeipp** [comment]
Hi @kacy-weakley / @dgozman , Yes I did try to escape it(sorry I forgot to mention that in the post). That didnt work either. I'll create a repro and a new issue
