### ISSUE TITLE
Type error when trying to override built-in fixture like Page

### ISSUE THREAD

**Issue by alexkuc** [microsoft/playwright#27601]
I have an issue extending _built-in_ fixtures with TypeScript as it raises a type error. For my own fixtures, I have no such issue. Only when trying to override fixtures like `Page` (to add extra methods).

### System info
- Playwright Version: 1.36.1
- Operating System: Ubuntu 20.04
- Browser: Chromium
- Typescript: 5.2.2

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```typescript
import { test as base, Page } from '@playwright/test';

const it = base.extend<{ page: Page & { getRoute: () => string } }>({
	page: async ({ page }, use) => {
            await use(Object.assign(page, { getRoute: () => 'route-name' }));
	},
});
```

![image](https://github.com/microsoft/playwright/assets/3331946/e07514b6-17c4-4f9a-bc1e-a25d4b005fb2)

**Test file (self-contained)**

```typescript
it('test', async ({ page }) => {
	page.getRoute();
});
```

![image](https://github.com/microsoft/playwright/assets/3331946/e2f1e752-fdcd-4258-8ee8-8a3c30175253)

**Comment by dgozman** [comment]
@alexkuc You are trying to change the type of the existing fixture. This is not supported.

**Comment by dgozman** [comment]
@alexkuc I'd recommend a separate fixture. It's not as flexible, but works for most of the cases.

```ts
import { test as base, type Locator } from '@playwright/test';

const test = base.extend<{ getByExactText: (text: string) => Locator }>({
  getByExactText: async ({ page }, use) => {
    await use(text => page.getByText(text, { exact: true }));
  },
});

test('custom locator', async ({ page, getByExactText }) => {
  await getByExactText('Customer');
});
```

**Comment by alexkuc** [comment]
A bit clunky I guess since one would need to remember all those custom fixtures… unless you create a finite amount of custom fixtures that would always be there? Yeah, I guess that works. Closing since there is a viable workaround.
