### ISSUE TITLE
Playwright API v1: shortcomings

### ISSUE THREAD

**Issue by aslushnikov** [microsoft/playwright#2761]
Here's a list of things we find unfortunate in Playwright API v1 but we can't change since they're part of our stable API.

- `context.setHTTPCredentials()`
  * **discussion:** https://github.com/microsoft/playwright/issues/2196
  * **summary:** The method shouldn't exist. HTTP credentials are cached deep inside browser guts, and resetting them is not easy. We should only be able to set credentials per origin during context creation.

**Comment by sublimator** [comment]
Just kill it 👍
