### ISSUE TITLE
[BUG] toHaveJSProperty does not work with expect.anything()

### ISSUE THREAD

**Issue by Tallyb** [microsoft/playwright#27619]
### System info
- Playwright Version: [v1.39]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [Chromium, ]
- Other info:

### Source code

```
await expect(someLocator).toHaveJSProperty('value', {duedate: {value: expect.anything()}});
```
expected result: pass
Actual result: error
```
Error: Timed out 5000ms waiting for expect(locator).toHaveJSProperty(expected)
Locator: locator('...')
Expected: {"duedate": {"value": Anything}}
Received: {"duedate": {"value": 2023-03-14T00:00:00.640Z}}
```

**Comment by mxschmitt** [comment]
Thanks for filing the bug! You can only use the [Asymmetric Matchers](https://jestjs.io/docs/expect#asymmetric-matchers) on the right hand side of toEqual() as per [docs](https://playwright.dev/docs/api/class-genericassertions#generic-assertions-anything). Closing as a won't fix.

**Comment by Tallyb** [comment]
yes, suspected it. Custom matcher maybe?

**Comment by mxschmitt** [comment]
yes you could create one which supports it!
