### ISSUE TITLE
[BUG] UI Mode Network tab request value folded to unredable form

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#27618]
When I check Network tab for info about used resource I observe very limited (hard to read / find) info in Request column.
![obraz](https://github.com/microsoft/playwright/assets/72373858/4b777d11-9dac-48d6-bf9e-514c07b177fe)
Compare same with Chrome (with Big request rows on)
![obraz](https://github.com/microsoft/playwright/assets/72373858/419e61b0-dc59-4b9c-84ab-5033a11cfdd4)

I know about tooltips but still this look like a bug.

### System info
- Playwright Version: v1.39
- Operating System: All

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
import { expect, test } from "@playwright/test";
test("has exact title", async ({ page }) => {
  const expectedTitle = "6. Dodatkowy front-end do API";

  await page.goto("https://naukaapi.testoneo.com/6/");
  const observedTitle = page.locator("#title");

  await expect(observedTitle).toHaveText(expectedTitle);
});
```

**Steps**
- Open UI Mode 
- Run test
- Navigate to Network tab

**Expected**
I wish to have more info (instead just tooltip) regarding URL path in Request column, see Chrome example 
![obraz](https://github.com/microsoft/playwright/assets/72373858/dad6bcf3-a6b4-4c4e-b76f-2ab3fec65ab7)

**Actual**
Just end of the path after last `/` what ends in many `/` without additional info
![obraz](https://github.com/microsoft/playwright/assets/72373858/4b777d11-9dac-48d6-bf9e-514c07b177fe)

**Comment by mxschmitt** [comment]
I can repro that for resources to e.g `https://foo.bar/api/users/` it will display them as just `/`.

Code pointer: https://github.com/microsoft/playwright/blob/3aa147914c5eafdf5a4ecc61d791e4a7deb920d4/packages/trace-viewer/src/ui/networkTab.tsx#L132
