### ISSUE TITLE
[BUG] web worker not working in playwright

### ISSUE THREAD

**Issue by qiweiii** [microsoft/playwright#27625]
### System info
- Playwright Version: [v1.37.1]
- Operating System: [macOS 13.4]
- Browser: [Chromium, Firefox]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

You can find it on [here](https://github.com/qiweiii/chopsticks/blob/321ec86ca9613b8a49c223758ae2064a3b336e3a/packages/web-test/tests/chopsticks-provider.spec.ts)

**Steps**
- `yarn`
- `cd packages/web-test`
- Run playwright test: `yarn test`

**Expected**

`api.rpc.xxx` are defined

**Actual**

```
1) [chromium] › chopsticks-provider.spec.ts:31:8 › chopsticks provider › chain rpc 

    TypeError: Cannot read properties of undefined (reading 'chain')

      35 |
    > 36 |     expect(await api.rpc.chain.getBlockHash()).toMatch(hashHead)
````

**Note**

You could check out [`index.tsx`](https://github.com/qiweiii/chopsticks/blob/321ec86ca9613b8a49c223758ae2064a3b336e3a/packages/web-test/src/index.tsx) where `api` is assigned to `globalThis`. I guess the cause of this could be that I initiated a web worker in `ChopsticksProvider`. My questions is that does web worker work in playwright? if so what could be the possible fix

**Comment by mxschmitt** [comment]
I tried to run this project but it requires cargo etc. to build. Could you provide us a more minimal example what is not working? Like do you know the underlaying [API](https://github.com/mdn/dom-examples/tree/main/web-workers/simple-web-worker) which is not working? Since we have Worker tests and they are all passing.

**Comment by qiweiii** [comment]
We got it work without creating web worker in tests directly, but I don't have time to dig the root cause for the issue😅. 
Since I don't have this issue anymore, I will close this.
