### ISSUE TITLE
[Feature]Support screenshot comparison in Playwright for Java.

### ISSUE THREAD

**Issue by xdfwqwz** [microsoft/playwright#27629]
In my current project using Java, I have been using Playwright and have noticed its lack of support for screenshot comparison. In contrast, the Node.js version of Playwright supports Visual comparisons. In my scenario, there is a lot of view information that requires the ability to perform data validation using whole image comparison.

Therefore, I would like to request the addition of screenshot comparison capabilities in the Java version of Playwright. This feature would be extremely helpful for me to automate my testing and data validation processes. Thank you for considering my request.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright-java/issues/1040.
