### ISSUE TITLE
[Feature] Force stopping after a certain loading time.

### ISSUE THREAD

**Issue by 1049451037** [microsoft/playwright#27626]
I have a web page that hangs about 20s to load entirely. However, I just want to load for 5s and stop loading, then download the current loaded page content. How to do that?

**Comment by yury-s** [comment]
By default `page.goto` waits for `load` event, you can wait for [`domcontentloaded`](https://playwright.dev/docs/api/class-page#page-goto-option-wait-until) instead:

```js
await page.goto('url', { waitUntil: 'domcontentloaded' });
```

Alternatively, you can just specify 5s timeout and catch the timeout error. To stop loading after that you can eval `window.stop();`:

```js
await page.evaluate(() => window.stop());
```
