### ISSUE TITLE
[BUG]Playwright test extension is not showing up after install in VScode

### ISSUE THREAD

**Issue by rufi0h** [microsoft/playwright#27634]
### System info
- Playwright Version: 1.33.0
- Operating System: Windows 10 Enterprise 22H2
- Browser: [chromium]
- Other info: This is an issue installing the playwright test extension

### Source code
My config file
```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  reporter: [
    ['line'],
    ['junit', { outputFile: 'tests/test-results/playwright-test-results.xml' }]
  ],
  outputDir: 'tests/test-results/',
  workers: 1,
  timeout: 90 * 1000,
  expect: {
    timeout: 10000
  },
  use: {
    actionTimeout: 10000,
    trace: 'on-first-retry',
    video: 'on-first-retry',
    screenshot: 'only-on-failure',

  },
  projects: [
    { name: 'setup', testMatch: /.*\.setup\.ts/ },
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
        viewport: { width: 1920, height: 1080 }
      }
    }
  ],
});
```

my settings.json
```
{
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "git.openRepositoryInParentFolders": "never",
    "files.autoSave": "afterDelay",
    "security.workspace.trust.untrustedFiles": "open",
    "git.confirmSync": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "playwright.showTrace": false,
    "playwright.reuseBrowser": true,
    "playwright.env": {
    


    }
}
```

**Steps**
- install the playwright extension published by Microsoft  through the extension shop in VScode. 
- navigate to the testing tab in VScode
- you should see the playwright extension within testing 

**Expected**
A month ago this was working and it stopped on my PC, Both my co-workers still work as expected. The playwright extension should be loaded in the testing tab of VScode. 

![image](https://github.com/microsoft/playwright-python/assets/40744099/1003ccf3-a2ce-45a3-b510-aff19c4f33cd)

**Actual**
under the shared tab of output i am seeing the following error when trying to install the playwright extension. 

2023-10-16 10:50:32.224 [error] [uncaught exception in sharedProcess]: Error: ENOENT: no such file or directory, stat 'c:\Users\USERNAME\.vscode\extensions\extensions.json.vsctmp': EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, stat 'c:\Users\USERNAME\.vscode\extensions\extensions.json.vsctmp'
    at s.create (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30209)
    at i (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:51:30329)
    at t.fb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:35755)
    at t.stat (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:28201)
    at async w.stat (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:56:15579)
    at async Q.tb (c:\Program Files\Microsoft VS Code\resources\app\out\vs\code\node\sharedProcess\sharedProcessMain.js:109:9514)

![image](https://github.com/microsoft/playwright-python/assets/40744099/7dba55e8-aeaf-447b-ab14-299f0f686bbc)

[Describe actual behavior]
For some reason the playwright extension is not loading. I have no options to enable it through the testing tab.

**Comment by mxschmitt** [comment]
Have you tried to unfold the test tree? The extension seems loaded correctly.

<img width="305" alt="Screenshot 2023-10-18 at 08 36 56" src="https://github.com/microsoft/playwright/assets/17984549/485021cc-dedb-4bf6-b3b2-f8d26512f09a">

**Comment by rufi0h** [comment]
That is a screen shot of what it should look like, with the playwright loaded at the bottom. The second screenshot is what it looks like now, with a copy of the error message I see when trying to install the extension

**Comment by mxschmitt** [comment]
So its not about the test tree which seems to work, its only about the webview at the bottom with the Playwright related options. This means by definition the extension is loaded, can you run tests? Only the webview isn't working.

Which VSCode version are you using?
I see you are using an old Playwright version, it makes definitely sense to update it too!
I guess you have tried to restart VSCode?

Could you invoke DevTools via the command palette:

<img width="367" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/c05ae257-bcb5-4af1-b664-f902a7cce39f">

And see if there is more shown under the `Console` tab?

**Comment by rufi0h** [comment]
The tests are running correctly with no issue there. The only issue is the playwright window and the bottom is no longer loading. I was able to get the browser window to launch and be reused by editing the settings.json "playwright.reuseBrowser": true.
VScode version 
```
Version: 1.83.1 (system setup)
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
```
my settings.json looks like 
```
{
    "terminal.integrated.defaultProfile.windows": "Git Bash",
    "git.openRepositoryInParentFolders": "never",
    "files.autoSave": "afterDelay",
    "security.workspace.trust.untrustedFiles": "open",
    "git.confirmSync": false,
    "explorer.confirmDelete": false,
    "explorer.confirmDragAndDrop": false,
    "typescript.updateImportsOnFileMove.enabled": "always",
    "playwright.showTrace": false,
    "playwright.reuseBrowser": true,
    "playwright.env": {
    
    }
}
```


I opened the developers console and there was no extra information in the console. The only warning I get is found i the output tab of the vscode console. 
![image](https://github.com/microsoft/playwright/assets/40744099/72c3bf77-6d9b-42d9-8947-1143f387be15)

**Comment by mxschmitt** [comment]
Could you check if Playwright might be hidden?

<img width="538" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/a85a48a3-1544-4c8e-82c1-aae9af165ccb">

Or this might help:

<img width="929" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/dd01b830-8e14-429f-b386-84e65f6b9120">

**Comment by rufi0h** [comment]
That fixed it!!!
Thanks so much!
![image](https://github.com/microsoft/playwright/assets/40744099/7eb69c2a-46e8-4634-84e7-e38c62cc1b45)
