### ISSUE TITLE
Correct value for no header on requests?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#27637]
Hi,
Im creating a wrapper for the APIRequestContext that handles adding headers/auth/etc..., by default im adding our normal headers in but I also want the optional case of no header being sent.

Right now im checking that the header value has no keys (so it's empty) and sending an empty header object along with the request. (IE: `headers: {}`

Is this valid or the correct way of sending an empty header? Should I be using `null` or something else? or is it fine to use an empty object?

Thanks

**Comment by yury-s** [comment]
Setting `headers: {}` is the same as not passing `headers` option at all or passing `headers: undefined`, there is no difference. Note, that playwright will add some headers unconditionally (e.g. 'user-agent', 'accept', 'accept-encoding'), if you want full control over all headers this will not work.

**Comment by msmith1114** [comment]
@yury-s Ok that works, so out of curiosity if I pass a `{}` for a header playwright adds those correct? What if I add my own headers? (like auth tokens and such) will Playwright still pass the "default" headers?

My use case is basically sometimes I need to pass an invalid header auth for negative testing, and in the abstracted client function I needed to be able to either default to the "good" headers or pass a `{}` and use no headers (Which will fail, which is expected)

**Comment by mxschmitt** [comment]
> so out of curiosity if I pass a {} for a header playwright adds those correct? 

Yes.

> What if I add my own headers? (like auth tokens and such) will Playwright still pass the "default" headers?

Yes

---

As of today there is no way of not sending the User-Agent/Accept headers. Why does the following not work for you?

a) don't pass an Auth header
b) don't pass an invalid Auth header
c) pass a valid Auth header

**Comment by msmith1114** [comment]
It does, I just wanted to make sure that I understand on when Playwright adds those. Thanks! I mainly wanted to clarify that an empty object `{}` was considered the same as not passing headers, but it looks like it doesn't really matter in the end since some headers are passed anyways (Either way it works for me 👍 )
