### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dreams-oneindia** [microsoft/playwright#27649]
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11]
- Browser: [Firefox]
- Other info:

### Source code

- [x] I provided the exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// @ts-check
const { defineConfig, devices } = require('@playwright/test');

/**
 * @see https://playwright.dev/docs/test-configuration
 */
module.exports = defineConfig({
  testDir: './tests',
  //Max timeout that one test can wait for before marking it fail
  timeout: 30 * 1000,
  //timeout for assertions
  expect: {
    timeout: 5000
  },
  reporter: 'html',
  use: {
    browserName: 'firefox',
    headless: false,
    trace: 'on'//retain-on-failure
  }
});
```

**Test file (self-contained)**

```js
test('Fetch all values from array', async ({browser}) =>
{
    const context = await browser.newContext();
    const page = await context.newPage();
    await page.goto("https://rahulshettyacademy.com/angularpractice/shop");
    const devices = page.locator(".card-body a");
    console.log(await page.title());
    const allDeviceNames = await devices.allTextContents();
    console.log("The devices listed are:\n" + allDeviceNames);
});

OR

test('Fetch all values from array', async ({page}) =>
{
    await page.goto("https://rahulshettyacademy.com/angularpractice/shop");
    const devices = page.locator(".card-body a");
    console.log(await page.title());
    const allDeviceNames = await devices.allTextContents();
    console.log("The devices listed are:\n" + allDeviceNames);
});
```

**Steps**
- [Run the test: npx playwright test tests/ClientApp.spec.js --config playwright.firefoxconfig.js]
- [...]

**Expected**

The test case would proceed with FireFox browser. 

**Actual**

There is a crash at firefox page :  TypeError: browserContext.newPage: Cannot read properties of undefined (reading 'pageOrError')

![image](https://github.com/microsoft/playwright/assets/119049958/05a08035-e7ec-4ae8-8c86-ed2d571c5aa6)

**Comment by dreams-oneindia** [comment]
![Untitled video - Made with Clipchamp](https://github.com/microsoft/playwright/assets/119049958/65afa55e-01fb-43bc-936e-1deae3873d54)

**Comment by mxschmitt** [comment]
I tried to reproduce on v1.39.0 on Windows 11 with both of your code snippets but in both cases it was passing for me.

Could you try to set `DEBUG=pw:browser` env var and provide us the output of it?

Also `DEBUG=pw:protocol` would probably be useful, but its a lot of output, so we recommend a [Gist](https://gist.github.com/) for it.

**Comment by dreams-oneindia** [comment]
Hi Max,

Then initial email is missing. Is it feasible for you to also forward me my
initial email?

**Comment by mxschmitt** [comment]
If the script is not too long yes: `maxschmitt`@`microsoft.com`

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
