### ISSUE TITLE
[Feature] Prefix output lines with which test they came from

### ISSUE THREAD

**Issue by zxti** [microsoft/playwright#27645]
Currently it is hard to understand the output from a `playwright test` run. You see all the test output intermingled, esp. if they run concurrently.

It would be great to be able to annotate

I thought at first this could be solved using fixtures, but it doesn't seem to be working (reliably). For instance, next tests can start before the previous test ends:

```
import { test as base } from "@playwright/test";

export const test = base.extend<{ saveLogs: void }>({
  saveLogs: [
    async ({}, use, testInfo) => {
      const origConsoleLog = console.log;
      console.log = (...args) => {
        origConsoleLog(
          `[${process.pid} ${testInfo.titlePath[0]}:${testInfo.line}]`,
          ...args
        );
      };
      console.log("STARTING", testInfo.titlePath.join(" > "));
      await use();
      console.log("ENDING", testInfo.titlePath.join(" > "));

      // console.log = origConsoleLog;

      // We can't simply use the above restoration because the following very bizarre ordering can happen:
      // [78 alpha.spec.ts:32] ENDING alpha.spec.ts > AA > BB > CC
      // [XX 78 alpha.spec.ts:32] [78 beta.spec.ts:32] STARTING beta.spec.ts > AA > ...
      // Somehow, although the previous test's ENDING is printed after the next test's STARTING (as expected),
      // the next test is actually starting before the previous test ends/restores console.log,
      // and thus the next test's origConsoleLog is the prev test's console.log!
      console.log = (...args) => {
        origConsoleLog(
          `[XX ${process.pid} ${testInfo.titlePath[0]}:${testInfo.line}]`,
          ...args
        );
      };
    },
    { auto: true },
  ],
});
```

**Comment by mxschmitt** [comment]
Sounds like something which can be implemented using a [custom reporter](https://playwright.dev/docs/api/class-reporter#reporter-on-std-out).

I marked it as a feature request for now.

**Comment by zxti** [comment]
Thanks - would you have a pointer on how to implement this using a custom reporter? Does onStdOut offer any way to suppress the original console.log line?

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
