### ISSUE TITLE
[BUG] UI mode fails to log in into JIRA app while it works fine in headed or headless mode

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#27643]
### System info
- Playwright Version: [1.39.0]
- Operating System: [Windows 10 Pro]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: UI mode only

When I visit my JIRA login page and try to login I am not successfully logged in. This is only in UI mode, it works fine with headed or headless mode, 
Instead I have an error in chromium: 
```
Cannot read properties of undefined (reading 'cookieValue')
TypeError: Cannot read properties of undefined (reading 'cookieValue')
    at Object.success (https://jira.mycompany.com/s/85253c07f9390f728f7c8cc0ec1f902b-CDN/-x0kq1q/900003/algceg/026c70a2eb5e0fbf2d51563e06821d9b/_/download/contextbatch/js/atl.general,jira.global,-_super/batch.js?agile_global_admin_condition=true&jag=true&locale=en-US:627:547)  
```
And in Webkit it says: 
`Failed to load resource: SSL peer certificate or SSH remote key was not OK`

**Expected**

I would expect the UI mode to behave the same as the headed and headless mode

**Actual**
UI mode fails, while headed and headless modes are able to login to the JIRA app.

**Comment by mxschmitt** [comment]
We unfortunately need a reproducible in order to look into such issues. The error you are surfacing looks like you need to ignore HTTPS errors: https://playwright.dev/docs/api/class-testoptions#test-options-ignore-https-errors

**Comment by mxschmitt** [comment]
Closing since its stale. Please re-file with a reproduction since we don't monitor closed issues, thanks!
