### ISSUE TITLE
[Electron] TimeOut on firstWindow

### ISSUE THREAD

**Issue by FomerMay** [microsoft/playwright#27658]
Hi,
- playwright version 1.39.0 (but we had the issuse also with previous version and it might have gone worse then better)
- electron 25.1.1

we have some issues at the beginning of the test. We basically call launch() and firstWindow(), and get a timeout at firstWindow(). 

`async firstWindow(options) {
    if (this._windows.size) return this._windows.values().next().value;
    return this.waitForEvent('window', options);
  }`

The problem is that `this._windows.size` is sometime (often) "0" but the window-Event never comes or (i assume) is long gone.

While trying to debug where exactly we could wait for a few seconds or if the window appreas after a while i figured out that during launch() the varible app is initialized 

`const app = ElectronApplication.from((await this._channel.launch(params)).electronApplication);`

and depending if after that `app._windows.size` is 0 or 1 the test fails or runs normally.

Some code example how we start the app

`electronApp = await _electron.launch({
        executablePath: "C:\\Path\\to\\App\\app.exe",
        timeout: 30000,
        env,
    });`

env is just a config file an a path to something like a "HOME"-directory

`const window = await global.electronApp.firstWindow({ timeout: 30000 });`

Has anybody any idea what we are doing wrong? Or if this is a bug in playwright? I probably won't be able to provide a test repo to reproduce the bug. But if i can do anything to create more logs or information i would appreciate the support!

Thanks!

**Comment by mxschmitt** [comment]
We unfortunately need a reproducible in order to triage this further. Does this also occur with a minimal new Electron application on your machine?

**Comment by mxschmitt** [comment]
We need a reproducible in order to look into such bugs. Please re-file with a Git repository attached which we can run locally. Thanks for your understanding!
