### ISSUE TITLE
No Error Message Appearing When Test Fails In Debug Mode[BUG]

### ISSUE THREAD

**Issue by eseverson7** [microsoft/playwright#27659]
### System info
- Playwright Version: 1.36.1
- Operating System: Windows 10
- Browser: All
- Other info:  

1. Using VS Code version 1.83.1 (this has been an issue with many different version of VS Code)
2. 3 out of 4 team members are encountering this. 
3. This did not used to happen to any of our team. 
4. We have tried upgrading versions of Playwright and NPM to latest and we are still seeing this issue.

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

> import type { PlaywrightTestConfig } from '@playwright/test';
> import { devices } from '@playwright/test';
> import dotenv from 'dotenv';
> 
> if (process.env.test_env) {
>   dotenv.config({
>     path: `.env.qa`,
>     override: true
>   })
> } else {
>   dotenv.config({
>     path: `.env.qa`,
>     override: true
>   })
> }
> 
> 
> const config: PlaywrightTestConfig = {
> 
>   testDir: './tests/.',
>   retries: 1,
>   //workers: 4,
>   timeout: 600000,
>   expect: {
>     timeout: 50000
>   },
> 
>   reporter: [['html'], [`allure-playwright`]],
>   use: {
>     /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
>     actionTimeout: 60000,
>     viewport: { width: 1920, height: 1080 },
>     screenshot: 'on',
>     // video: 'retain-on-failure',
>     trace: 'on-first-retry',
>     launchOptions: {
>       slowMo: 200,
>     },
>     baseURL: process.env.baseURL,
>   },
>   projects: [
>     {
>       name: 'GoogleChrome',
>       use: {
>         headless: true,
>         channel: 'chrome',
>         baseURL: process.env.baseURL,
>         video: 'retain-on-failure',
>         screenshot: 'only-on-failure'
>       },
>     }
> ],
> 
>   globalSetup: "Utils/globalSetup.ts"
> };
> 
> export default config;

**Test file (self-contained)**

***Test file does not pertain to issue***

**Steps**
- Debug the test
- Test fails

**Expected**

Specific Error to show up in test file when it fails in Debug mode

**Actual**

No error shows when test fails in Debug mode.

**Comment by eseverson7** [comment]
We created a simple test file that demonstrates the issue that 3 of our 4 team members are experiencing. The 4th one is getting error messages upon Debugging.

Errors like this:

![image](https://github.com/microsoft/playwright/assets/22645568/4f4a9dc7-20d2-41bf-9f14-0b542de4053b)

^^^ the above image is what appears when we Run the test. When we Debug (below) the test it gives no error message nor updates the Test Results section with pass or fail.

![image](https://github.com/microsoft/playwright/assets/22645568/35e21b4d-144d-4f6f-b97d-661f066d2dfa)


Here is the test file mentioned above, it is set to fail on line 7:

import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/');
  await page.frameLocator('iframe[name="callout"]').getByLabel('Not now').click();
  await page.getByRole('link', { name: 'Store' }).click();
  await expect(page).toHaveURL('www.bookface.com');
});

**Comment by mxschmitt** [comment]
I was able to reproduce on Windows.

**Comment by eseverson7** [comment]
Does that label mean it will be addressed in the 1.40 release?

**Comment by mxschmitt** [comment]
Yes, its addressed in the next release of the VSCode issue, or you use a dev version as per [here](https://github.com/microsoft/playwright-vscode/wiki).
