### ISSUE TITLE
[Feature] Add a way of initializing localStorage for certain tests

### ISSUE THREAD

**Issue by sjarmero** [microsoft/playwright#27654]
At the moment, both cookies and local storage are set through the BrowserContext. However, utilities like `addCookies` are provided only for cookies, and not for the local storage.

As a first step to start adding methods for managing the local storage, I would like to request a feature which allows to add items to the local storage when a page initializes. This is very useful for apps that heavily rely on local storage, since it would make it easier to setup the state of the app for each different test.

A proposal to implement this is available here: https://github.com/microsoft/playwright/pull/27616

**Comment by yury-s** [comment]
Can you just run the logic that populates the storage for certain tests into [`addInitScript`](https://playwright.dev/docs/api/class-page#page-add-init-script)?

**Comment by pavelfeldman** [comment]
... or initialize local storage as a part of the storageState where it would be per origin?

**Comment by yury-s** [comment]
Closing per the comments above, feel free to open a new issue if it doesn't work.
