### ISSUE TITLE
[BUG] trace viewer (html report) not working in jenkins pipeline

### ISSUE THREAD

**Issue by hschn** [microsoft/playwright#27655]
System info
Playwright Version: [1.39.0]
Operating System: [Ubuntu 22.04.3 LTS]
Browser: [All, Chromium, Firefox, WebKit]

**Steps:**
- open the report in Jenkins
- trying to click the thumbnail to reach the trace-viewer

**Expected**

- the trace viewer openes, like when executing tests locally

current issue:
- a JS error in the dev console appears
```js
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can escape its sandboxing.
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'register')
  at index.38834ec3.js:1:3775
  at index.38834ec3.js:1:4006
```

**Config file**

```js
// playwright.config.ts
[...]
 reporter: [['html'], ['junit', { outputFile: 'results.xml' }]],
[...]
```

**jenkins pipeline reporting**

```js
always {
      publishHTML target: [
        allowMissing         : false,
        alwaysLinkToLastBuild: false,
        keepAll              : true,
        reportDir            : 'playwright-report',
        reportFiles          : 'index.html',
        reportName       : 'my tests report',
        traceFiles           : 'playwright-report/data/**/*.zip'
      ]
      junit testResults: "myProject/results.xml", allowEmptyResults: false
    }
```

![image](https://github.com/microsoft/playwright/assets/11842149/92f0df91-c322-4a4f-af8f-ef055173a1fc)

**Comment by mxschmitt** [comment]
In order to use trace viewer inside html report you need to serve it via a secure domain, otherwise Service Workers are not working, see [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API.

Whats the URL you are serving the HTML report from?

**Comment by bnesteruk** [comment]
Getting the same error on Jenkins running on AWS EC2 box, as the protocol is http. And I have no ability to switch to https there.
Is using https the only way to make it working?

**Comment by mxschmitt** [comment]
> Is using https the only way to make it working?

Yes, this is unfortunately a limitation not given by us, the specification allows Service Workers which we use only only on secure (https) websites.
