### ISSUE TITLE
[Feature] Allow marking tests as flaky, still running them but not failing on them

### ISSUE THREAD

**Issue by annervisser** [microsoft/playwright#27653]
When dealing with flaky tests, you want to mark them as such as quickly as possible to prevent a lot of churn in your CI flow. The .fixme() function works great for this, but also means the tests will not be ran at all. This means that possible problems detected by the test (it hopefully exists for a reason) will go unnoticed.

I propose a way to mark a test as broken, without skipping it entirely.
This could be a new marker: something like `.flaky()` or `.optional()`
or a new option for `.fixme()`: something like `test.fixme({tryRunning: true}})`

Playwright would then proceed to run the test as normal, but treat the result differently:
- success: counted as success
- flaky (retry succeeded): counted as flaky
- failure: counted as flaky

**Comment by yury-s** [comment]
You can already mark the test as failing with [`test.fail()`](https://playwright.dev/docs/api/class-test#test-fail-1). So you have an option for always failing and for always passing tests. We considered `test.flaky` marker[ before](https://github.com/microsoft/playwright/issues/9905) and decided not to add it. Closing this report as there are no plans to implement this.

**Comment by ImLunaHey** [comment]
since users disagree can this be reopened?

**Comment by jprinaldi** [comment]
And if not, at least mark it as "not planned"... "completed" is very misleading.

**Comment by dzmitry-kankalovich** [comment]
in the age of un-deterministic LLMs I wish I had this option.

**Comment by gaspar09** [comment]
Sharing a workaround: 

```ts
import { test as base } from '@playwright/test'

/**
 * A test fixture that automatically skips on retry to avoid blocking CI.
 *
 * Tests using this fixture will:
 * 1. Run normally on first attempt
 * 2. If they fail, the retry automatically skips instead of failing
 *
 * Usage:
 * ```typescript
 * import { testFlaky } from '../../lib/flaky-test'
 *
 * testFlaky.describe('My flaky tests', () => {
 *   testFlaky.describe.configure({ retries: 1, timeout: 60000 })
 *
 *   testFlaky('test name', async ({ page }) => {
 *     // test code
 *   })
 * })
 * ```
 */
export const testFlaky = base.extend<{ _autoSkipOnRetry: void }>({
  _autoSkipOnRetry: [
    async ({}, use, testInfo) => {
      if (testInfo.retry > 0) {
        base.skip(true, 'Flaky test - skipping retry to not block CI')
      }
      await use()
    },
    { auto: true },
  ],
})

```

**Comment by Tanmay000111** [comment]
The fixture approach @gaspar09 shared is a clean workaround for keeping CI green without skipping entirely. The harder problem it doesn't solve is ownership. Once you have 10 or 15 tests running through that fixture, you lose track of which ones are actually stabilizing versus quietly getting worse over time. test.fail() has the same issue. The marker tells Playwright how to handle the result but nothing tracks whether that test failed 3 times last week and 8 times this week. That drift is usually invisible until someone asks why CI feels slower than it used to.
