### ISSUE TITLE
No Tests Found While Ruining Any Tests 

### ISSUE THREAD

**Issue by ymostafa011** [microsoft/playwright#27656]
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11 ]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:
- Node Js Version ( 18.18.0)
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

const {test, expect} = require ('@playwright/test');

test('google test', async ({page})=> {
await page.goto('https://www.google.com/');
await expect(page).toHaveURL('https://www.google.com/')

});

**Config file**

const { defineConfig, devices } = require('@playwright/test');

const config = {

    testDir:'tests',

    timeout:500000,

    fullyParallel: true,

    workers: process.env.CI ? 2 : 3,

    use:{

        baseURL: "https://opensource-demo.orangehrmlive.com",

        headless: false,

        trace:'retain-on-failure',

        screenshot:'only-on-failure',

        video:'on',

        launchOptions:{

        slowMo:300

        }

    },

    reporter : 'html',

 

    projects: [

        {

          name: 'chromium',

          use: { ...devices['Desktop Chrome'] },

        },

   

        {

          name: 'firefox',

          use: { ...devices['Desktop Firefox'] },

        },

   

        {

          name: 'webkit',

          use: { ...devices['Desktop Safari'] },

        },

    ]    

};

export default config;
**Preconditions:**
1. No Example Files Exist
**Steps**
1. Run The Command "npx playwright test"
**Expected**

[Run The Test Case (Open Google Chrome & Redirect To www.google.com]

**Actual**

Error: No tests found

**Comment by MindaugasMateika** [comment]
How is your test file named?

**Comment by mxschmitt** [comment]
Is your test located inside the 'tests' directory? Whats the name of the test file? It needs to match the default [testMatch](https://playwright.dev/docs/api/class-testproject#test-project-test-match).

**Comment by ymostafa011** [comment]
> How is your test file named?

The File's Name "google.spec.js"

**Comment by ymostafa011** [comment]
> Is your test located inside the 'tests' directory? Whats the name of the test file? It needs to match the default [testMatch](https://playwright.dev/docs/api/class-testproject#test-project-test-match).

yes Already exist in tests directory . the name is "google.spec.js"

**Comment by ymostafa011** [comment]
I'm getting this failure so I shared with you may be help in fixing 
![321](https://github.com/microsoft/playwright/assets/101115964/9975ab73-ef32-40b9-a66d-840f493ec8df)

**Comment by mxschmitt** [comment]
This looks like an issue of your system in combination with VSCode which fails to activate the shell see https://github.com/microsoft/vscode/issues/179529#issuecomment-1500908637.

Do you have a custom Shell configured? Which PowerShell version are you using?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
