### ISSUE TITLE
[BUG] waitForFunction maybe exists development defect

### ISSUE THREAD

**Issue by TenshGU** [microsoft/playwright#27651]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ √ ] I provided exact source code that allows reproducing the issue locally.

**Source file**

```typescript
// Line 55-56 of utils/generate_types/overrides.d.ts
// Page.waitForFunction(...)
waitForFunction<R, Arg>(pageFunction: PageFunction<Arg, R>, arg: Arg, options?: PageWaitForFunctionOptions): Promise<SmartHandle<R>>;

waitForFunction<R>(pageFunction: PageFunction<void, R>, arg?: any, options?: PageWaitForFunctionOptions): Promise<SmartHandle<R>>;

```

**Example code**
```typescript
await page.waitForFunction(() => {
    const element = document.querySelector('div')
    return element && element.textContent === 'xxx'
}, {timeout: 10000})

```

**Steps**
- [Run example code]

**Expected**

When the text inside my div element is xxx, the function execution is successful, otherwise, the wait times out

**Actual**

When I want to not pass in the parameter **arg**, I only want to pass **options**.
At this point, my options will be defined as arg, causing the waitForFunction to fail execution.

**Comment by yury-s** [comment]
This is working as intended, `{timeout: 10000}` is passed as an argument to the function. If you wan to pass options, they have to be 3rd argument, i.e.:

```js
await page.waitForFunction(() => {
    const element = document.querySelector('div')
    return element && element.textContent === 'xxx'
}, undefined, {timeout: 10000});
```
