### ISSUE TITLE
[Internal] Monitor HttpsUpgrades Chromium flag

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#27666]
Monitor if it gets reverted, if not, we should use the correct response instead of the fake redirected response internally.

https://chromium-review.googlesource.com/c/chromium/src/+/4922641

https://source.chromium.org/chromium/chromium/src/+/main:chrome/common/chrome_features.cc;l=759?q=chrome%2Fcommon%2Fchrome_features.cc&ss=chromium%2Fchromium%2Fsrc

https://github.com/microsoft/playwright/pull/27605

**Comment by mxschmitt** [comment]
Still enabled as per Oct. 27

**Comment by dgozman** [comment]
For the record: decided to keep the feature disabled.
- For localhost servers it does not matter.
- For https properties it does not matter.
- For http properties users probably want it disabled (similarly to chrome://flags entry).
- Headed and headless have different defaults for this feature, which would be surprising to our users.
