### ISSUE TITLE
[BUG] PWA Trace viewer is unable to open trace file with console errors about set properties of undefined for afterSnapshot

### ISSUE THREAD

**Issue by kelvien-microsoft** [microsoft/playwright#27661]
### System info
- Playwright Version: [v1.35]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.
On my beforeEach hook, I added:
`await browser.contexts[0].tracing.start({ snapshots: false, screenshots: false });`
And on my afterEach hook, I added:
`await browser.contexts[0].tracing.stop({ path: 'tracetest.zip' });`

**Test file (self-contained)**
We use a framework tool that encapsulates Playwright APIs

**Steps**
- Run test
- Test passes
- AfterEach hook is successfully ran

**Expected**

Trace file can be viewed in trace.playwright.com

**Actual**
![image](https://github.com/microsoft/playwright/assets/114680245/18fa8b5d-62c8-4c93-99b1-232db9640ab9)

**Comment by mxschmitt** [comment]
Discussed offline/investigation: The trace contained an event which only had an "after" event but no "before" event. Such fixes need to happen on the client side (of the library which creates the trace file).

So we recommend upgrading Playwright for now.
