### ISSUE TITLE
[Feature] Ability to add testInfo annotation with text for junit report

### ISSUE THREAD

**Issue by jgreffe** [microsoft/playwright#27668]
Currently, we can push additional annotations for them to be processed by junit reporter as a property:

```
testInfo.annotations.push({
  type: 'something',
  description: 'some value'
});
```

the junit XML report is then something like:
```
<property name="something" value="some value">
</property>
```

Anyway, if we want more complex values, with some line breaks, it's currently not possible.
If we could provide the node inner text, with something like:
```
testInfo.annotations.push({
  type: 'something',
  text: 'my text\nwith another line'
});
```
which would generate:
```
<property name="something">
my text
with another line
</property>
```

Seems the relevant code is here:
https://github.com/microsoft/playwright/blob/d4296dbff45d80b210f97a6718051800b5d846f2/packages/playwright/src/reporters/junit.ts#L159-L164

**Comment by yury-s** [comment]
I can see some examples where the content of a property is wrapped as `<![CDATA[....]]>`. Do you have an example of a tool that supports plain text content of `<property>` tag?

**Comment by yury-s** [comment]
As my colleagues pointed out, we actually supported this in the past but then removed it as it was non-standard for JUnit format, see https://github.com/microsoft/playwright/pull/22624. The idea is to put all XRay-specific code into a dedicated reporter that could employ all XRay format extensions, while keeping the core JUnit reporter non controversial.
