### ISSUE TITLE
[BUG] Playwright component tests fail to trigger Fluent tooltip

### ISSUE THREAD

**Issue by AlienLifeForm-UMA** [microsoft/playwright#27660]
### System info
- Playwright Version:"@playwright/experimental-ct-react": "^1.39.0"
- Operating System: [Ubuntu 20]
- Browser: [Chromium,Firefox]
- Other info: I am only using component testing in this case

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.
https://github.com/redReno/playwright-ct-pnp

It uses pnp so you need to run 
```
yarn dlx @yarnpkg/sdks vscode
```
and select the workspace typescript for anything to work properly. It is based on a Vite + SWC starter project but with yarn 3 pnp. 

The failing test example is in src/Info.spec.tsx.

I have create a simple React Fluent component with this tooltip, let's call it Info:

```
export const Info: FC<Props> = ({ title, tooltip }) => {
  return (
    <Content>
      <Tooltip
        relationship="description"
        withArrow
        content={{
          style: { maxWidth: undefined },
          children: tooltip,
        }}
      >
        <Button
          appearance="transparent"
          data-testid="infoTooltip"
          icon={<InfoRegular />}
          tabIndex={-1}
        />
      </Tooltip>
    </Content>
  )
}

 ```

**Config file**
Default component test configuration

**Test file (self-contained)**

```js
test.only('Show info tooltip', async ({ mount }) => {
  const component = await mount(<Info title="Example Title" tooltip="Example Tooltip" />)
  const tooltip = component.getByTestId('infoTooltip')
  await expect(tooltip).toBeVisible()
  await tooltip.hover()
  await expect(component.getByRole('tooltip')).toBeVisible()
})
```

**Expected**
It should hover the icon and then locate the tooltip that should appear.

**Actual**
Playwright ct hovers over the tooltip icon but nothing appears.
After timeout the test fails, but when I run the test in the PW UI, the tooltip pops up the moment the test fails.
It is only the last step that fails.

This is how it looks after the test fails.
![image](https://github.com/microsoft/playwright/assets/90031837/2e55e2d7-b360-4560-afa4-1e5307c3216b)

If I run in debug mode I see how the mouse icon hovers over the icon but the tooltip never appears.
The tooltip does work if I test it manually, both in production and while running ct tests in debug mode.

![image](https://github.com/microsoft/playwright/assets/90031837/ea9062a9-6068-4579-b517-c61da96392f4)

**Comment by mxschmitt** [comment]
Can you share a reproducible which we can run locally?

**Comment by AlienLifeForm-UMA** [comment]
> Can you share a reproducible which we can run locally? This would be essential for us in order to debug it further.

I will need to create a separate repo for it, but I will try, thanks.

**Comment by redReno** [comment]
@mxschmitt  [Here you go](https://github.com/redReno/playwright-ct-pnp)
It uses pnp so you need to run 
```
yarn dlx @yarnpkg/sdks vscode
```
and select the workspace typescript for anything to work properly. It is based on a Vite + SWC starter project but with yarn 3 pnp. 

The failing test example is in src/Info.spec.tsx. I will update the first comment.

**Comment by AlienLifeForm-UMA** [comment]
@mxschmitt  I have updated the first comment with a link.

**Comment by mxschmitt** [comment]
Thanks for your repro! So the issue is that you are creating the locators relative to the mounted component. `component.*` which is strictly speaking the right thing to do. But for portals which fluentui in this case mounts outside, probably directly underneath the body element, this won't work. (It won't find the element). To fix this, you can just use page instead of the relative component locator.

```ts
test('verify tooltip works', async ({ mount, page }) => {
  const component = await mount(<Info title="Example Title" tooltip="Example Tooltip" />)
  const tooltip = component.getByTestId('infoTooltip')

  await expect(tooltip).toBeVisible()
  await tooltip.hover()
  await expect(page.getByRole('tooltip')).toBeVisible()
});
```

this worked for me!

**Comment by AlienLifeForm-UMA** [comment]
Thanks, that works! I had a feeling the issue was related to how fluentui handles things, but didn't know page is still usable during component testing. That's handy to know. Thanks for the help! This will make things a lot easier. Do you know why I couldn't see the text in Playwright UI/debug even though hover works as intended? Do the screenshots only update after the next step has passed/failed?

**Comment by mxschmitt** [comment]
Yup screemshots get occasionally sent from the browser to us.
