### ISSUE TITLE
[Feature] Support for manifest v3 Browser Extensions

### ISSUE THREAD

**Issue by myersgm** [microsoft/playwright#27670]
In the docs, I only see support for manifest v2 extensions: https://playwright.dev/docs/chrome-extensions

Since manfiest v2 is being phased out, it would be very helpful to support manifest v3 extensions.

In addition, I think many developers would find value in adding tests for extension popups as well. 

For my use case, I need to develop tests within the background service worker and UI tests in the popup.

Thanks!

**Comment by yury-s** [comment]
Is there anything specific that does not work today apart from the documentation mentioning only v2 manifest? Can you access the service worker via [context.serviceWorkers()](https://playwright.dev/docs/api/class-browsercontext#browser-context-service-workers)? For the popups, can you try the workaround [described here](https://github.com/microsoft/playwright/issues/26693#issuecomment-1693631758) and see if it works?

**Comment by myersgm** [comment]
> Is there anything specific that does not work today apart from the documentation mentioning only v2 manifest? Can you access the service worker via [context.serviceWorkers()](https://playwright.dev/docs/api/class-browsercontext#browser-context-service-workers)? For the popups, can you try the workaround [described here](https://github.com/microsoft/playwright/issues/26693#issuecomment-1693631758) and see if it works?

Thanks for the info. I'll try this and report back. May take some time.

**Comment by mxschmitt** [comment]
Closing in the meantime then, if you have a reproduction with manifest v3 which doesn't work, please re-file then with a repro, thanks!
