### ISSUE TITLE
[Feature] Launch Chrome browser with specific user profile

### ISSUE THREAD

**Issue by python012** [microsoft/playwright#27674]
Hi, does Playwright support launching Chrome browser with specific user profile? I did some research but didn't find the answer.

The sample code with Selenium solution would be 

```
from selenium import webdriver

options = webdriver.ChromeOptions()
options.add_argument(r"--user-data-dir=D:\my_chrome_user_profile")
options.add_argument(r'--profile-directory=Profile 1')
driver = webdriver.Chrome(options=options)
driver.get('https://www.google.com/)
```

**Comment by yury-s** [comment]
[launchPersistentContext](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) does that.
