### ISSUE TITLE
[ISSUE] Fail to firefox config via firefoxUserPrefs 

### ISSUE THREAD

**Issue by icesmartjuan** [microsoft/playwright#27678]
### System info
- Playwright Version: [v1.32.3]
- Operating System: [macOS Ventura 13.5.2]
- Browser: [Firefox]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Repro code**

```js
const context = await playwright.firefox.launchPersistentContext('',{
            headless: false,
            ignoreHTTPSErrors: true,
            bypassCSP: true,
            firefoxUserPrefs: {
                "network.cookie.cookieBehavior": 1,
                "browser.tabs.remote.useCrossOriginOpenerPolicy":false
            }
        });
```

**Steps**
- [Run the code]
- [With Firefox Nightly, go to about:config, accept the risks, enter "browser.tabs.remote.useCrossOriginOpenerPolicy" , will see it's the default `true` value instead of our setting value `false`
<img width="1261" alt="image" src="https://github.com/microsoft/playwright/assets/37887450/fa5a4627-701b-4057-b810-6e16e8de9667">

**Expected**

[With Firefox Nightly, go to about:config, accept the risks, enter "browser.tabs.remote.useCrossOriginOpenerPolicy" , should see its value is  `false` ]

**Actual**

 [With Firefox Nightly, go to about:config, accept the risks, enter "browser.tabs.remote.useCrossOriginOpenerPolicy" , will see it's the default `true` value instead of our expected setting value `false`

**Comment by mxschmitt** [comment]
We recommend putting `user.js` into your user data dir as per https://github.com/microsoft/playwright/issues/17442#issuecomment-1251562044, we'll update our docs accordingly.

What is your use-case for launchPersistentContext? (just curious)

**Comment by mxschmitt** [comment]
This is actually not supported, as per our docs and types:

<img width="586" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/13f22892-69e3-4d20-baab-772052411ecc">

We recommend [@ts-check](https://www.typescriptlang.org/docs/handbook/intro-to-js-ts.html#ts-check), then your editor like VSCode should show it in red.

**Comment by mxschmitt** [comment]
Starting from v1.40 you can set firefox prefs in persistent context.
