### ISSUE TITLE
[Question] Is it possible to define host resolution rules per browser instance?

### ISSUE THREAD

**Issue by southp** [microsoft/playwright#2767]
In my daily work, I often have to tweak the `/etc/hosts` file for routing production site URLs to the development sites for testing.
Is it possible to launch a browser instance with a set of customized host resolution rules? For example, 

```
const browser = await chromium.launch( {
    hosts: {
        'example.com': '127.0.0.1',  // all the request to example.com will then be routed to my local machine.
    }
} );
```

I believe it's possible by dockerizing my playwright testing program, but would like to see if there is a lightweight solution for this. 

Thanks :)

**Comment by shirshak55** [comment]
i think it is better if u edit manually or use proxies?

**Comment by pavelfeldman** [comment]
No way to do this for all the browsers atm. Let's open it to collecting feedback.

You can pass host rules via `args` to Chromium, but other browsers don't support it:

https://stackoverflow.com/questions/14605636/host-rules-google-chrome-adding-configuration

**Comment by pavelfeldman** [comment]
Posting an investigation note for myself, `network.dns.forceResolve` does most of the job for Firefox, so can be passed using `firefoxUserPrefs`. Discussion: https://bugzilla.mozilla.org/show_bug.cgi?id=1523367

**Comment by southp** [comment]
Thanks for finding those, @pavelfeldman . I haven't been able to make it work since I don't have enough time today, but it indeed looks promising. 

Even though it's not yet supported by all the browsers, my two cents go to abstract it to the Playwright level, e.g.
```
browser.launch( {
    hostResolutionRules: [ ... ],
} );
```
or
```
browser.addHostResolutionRules( '...' );
```

If the browser instance being used doesn't support it, throwing an exception to terminate further attempts could be a good first step.

I'll circle back after I've done more testing.

**Comment by Quo0** [comment]
> No way to do this for all the browsers atm. Let's open it to collecting feedback.
> 
> You can pass host rules via `args` to Chromium, but other browsers don't support it:
> 
> https://stackoverflow.com/questions/14605636/host-rules-google-chrome-adding-configuration


Hi Pavel!
Looks like Chrome headless doesn't see local etc/hosts.

I keep getting 404 at page navigation when headless but don't have any issues when run script headfull.
The most bizarre thing is that if I will debug headless by using --remote-debugging-port 
and navigate manually through the chrome://inspect to the desired URL 
I will not get any errors!

Can you recommend something? 

My hosts file is
127.0.0.1 dev.mysite

```
const browserOptions = {
  ignoreHTTPSErrors: true,

  args: [
    '--no-sandbox',
    '--remote-debugging-port=9222',
    '--host-rules="MAP 127.0.0.1 dev.mysite'
  ],
}
```

**Comment by southp** [comment]
I am experiencing the same as @Quo0 described above, but am not sure if it's a Chromium issue or a Playwright one. Fwiw, according to [the latest command line list](https://peter.sh/experiments/chromium-command-line-switches/), `--host-rules` should be replaced by `--host-resolver-rules`.

**Comment by Quo0** [comment]
Tried both variants, but still an issue with Chrome:
```
args: [
    // '--host-rules="MAP 127.0.0.1 dev.smthg'
    '--host-resolver-rules="MAP 127.0.0.1 dev.smthg'
]
```
I have Github Actions workflow and inside it I'm updating the etc/hosts file manually.
Firefox is working fine, but looks like Chrome doesn't see this file at all...
The same happens locally with Windows 10

**Comment by Quo0** [comment]
Sorry, @southp , did you overcome this issue with this additional args ???

**Comment by Quo0** [comment]
Found this Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=798793

**Comment by Gotterbild** [comment]
Same bug in Puppeteer: https://github.com/puppeteer/puppeteer/issues/1701

**Comment by southp** [comment]
@Quo0 Hey, sorry for the late response. After rerunning my test code, I can confirm that the issue is still there. I thought I had seen the additional flag work for me previously, but can't confirm if it was just me being mistaken or it really had worked once.

**Comment by pavelfeldman** [comment]
Now that Playwright supports proxies, we consider this being outside of the Playwright scope. Closing this as a part of the triage, please feel free to file a new issue with additional details. Given the limited resource and a lot of requests, we need to fulfill most popular requests and at the same time keep our issue database manageable.

**Comment by PiotrCzapla** [comment]
> Tried both variants, but still an issue with Chrome:
> 
> ```
> args: [
>     // '--host-rules="MAP 127.0.0.1 dev.smthg'
>     '--host-resolver-rules="MAP 127.0.0.1 dev.smthg'
> ]
> ```
> 
> I have Github Actions workflow and inside it I'm updating the etc/hosts file manually.
> Firefox is working fine, but looks like Chrome doesn't see this file at all...
> The same happens locally with Windows 10

I think the code doesn't work due to  additional quote inside of the rule.
```
 args: [ '--host-resolver-rules="MAP 127.0.0.1 dev.smthg"' ]  // the double quote cause the issue
```
This argument should looks as follows in playwright:
 ```
 args: [ '--host-resolver-rules=MAP 127.0.0.1 dev.smthg' ]
```

**Comment by GHkmmm** [comment]
Is there a solution to this problem now?

**Comment by philsch** [comment]
```js
const browser = await chromium.launch({
  args: [ '--host-resolver-rules=MAP * 127.0.0.1' ]
});
```

Worked for me to direct all domains to be resolved by my local machine.

For example this loaded the content from my local running webserver:

```js 
const page = await browser.newPage();
const response = await page.goto('http://test.server.local/');
const text = await response.text();
expect(text).toContain('...')
```

**Comment by Hoppjerka** [comment]
### Windows Hostfile
Imagine the following hostfile record:

```txt
// C:\Windows\System32\drivers\etc\hostfile

192.168.0.1    the.hostname.com
```
### Google Chrome
You can achieve the same, without manipulating the hostfile, by passing `--host-resolver-rules` in google chrome. 
With powershell as an example:

```powershell
& "C:\Program Files\Google\Chrome\Application\chrome.exe" --incognito --host-resolver-rules="MAP the.hostname.com 192.168.0.1:80"
```

> Starting Chrome with --host-resolver-rules="MAP the.hostname.com [dead::beef]" where the.hostname.com is the hostname to allow resolving and dead::beef is the IPv6 address to resolve it to. net::MappedHostResolver acts at a level before IPv6 connectivity checks, and if a hostname is remapped to an IP literal, connectivity checks do not apply.
> Souce: https://chromium.googlesource.com/chromium/src/+/main/net/dns/README.md

### Playwright
And then in Playwright (as described by others above) you can pass the same argument:

```typescript
test('Host resolver in chrome', async ({ }) => {

    const browser = await chromium.launch({
        args: ['--host-resolver-rules=MAP the.hostname.com 192.168.0.1:80'] 
    });

    const page = await browser.newPage();

    await page.goto('https://the.hostname.com/some/path/')
    await page.screenshot({ path: 'screenshot.png', fullPage: true }); // Take a screenshot in case you just want a visual verification.
});
```
