### ISSUE TITLE
[BUG] Race condition when trying to click on element while its location changes

### ISSUE THREAD

**Issue by jhyot** [microsoft/playwright#27681]
### System info
- Playwright Version: 1.39.0 (Java)
- Operating System: All (reproduced with macOS and Linux, only tested headless)
- Browser: All? (reproduced with Chromium and Firefox)
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

This is reproduced with playwright-java 1.39.0, but IMO should have nothing to do with Java, so I opened this bug in your main GItHub project.
I feel you will be easily able to port the test case to Node if you wish.

There is no additional config besides what you see in the Java main class, which is run via Maven.
Java 17 required for the test code.

**Test file (self-contained)**

```java
import static com.microsoft.playwright.assertions.PlaywrightAssertions.assertThat;

import com.microsoft.playwright.Browser;
import com.microsoft.playwright.Page;
import com.microsoft.playwright.Playwright;
import com.microsoft.playwright.options.AriaRole;

public class App {

  public static void main(String[] args) {
    try (Playwright playwright = Playwright.create()) {
      Browser browser = playwright.chromium().launch();
      Page page = browser.newPage();
      page.navigate("https://gistpreview.github.io/?0677096549bd8be1af8ceeed927a0091/playwright.html");

      // program will finish with error if assert fails; otherwise continue indefinitely
      var expectedCounter = 0;
      while (true) {
        if (expectedCounter % 100 == 0) {
          System.out.println("iteration " + expectedCounter);
        }
        page.getByRole(AriaRole.BUTTON, new Page.GetByRoleOptions().setName("Click"))
            .click();

        assertThat(page.locator("#counter")).hasText(String.valueOf(++expectedCounter));
      }
    }
  }
}
```

**Link to Gist with the repro webpage**

https://gist.github.com/jhyot/0677096549bd8be1af8ceeed927a0091

As seen in the above test runner code, I just use an external service to serve the Gist as HTML for simplicity:

https://gistpreview.github.io/?0677096549bd8be1af8ceeed927a0091/playwright.html

**Steps**
- Serve the repro webpage somewhere, or use the gistpreview.
- Edit the `page.navigate` link in the test runner code if necessary
- Run the test

The test page has a button that the runner clicks, and then asserts that the click has happened (the `onclick` handler on the website will increment a counter, which provides the "proof" that the button was clicked).

There is a div which is randomly displayed or hidden, which consequently moves the button vertically. Apparently it can happen that Playwright finds the button and selects the coordinates to click on the page, but before managing to click, the changing `div` moves the button away.

There is no error from Playwright in that case, it just seems to click into empty space.

**Expected**

Test will run indefinitely if the runner is able to click the button every time

**Actual**

Test will fail at some point because of a race condition. As an example, last time on my laptop it failed around iteration 2600.

Note this has happened to us on a real Angular SPA seldomly but regularly. This is an artificial repro to force the issue.

**Comment by mxschmitt** [comment]
How does this surface with an Angular SPA application? Does Angular hydrate in a way which is similar to that? We are curious in learning more about this issue if it accept real world scenarios.

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
