### ISSUE TITLE
[BUG] Click doesn't work properly if page is zoomed in

### ISSUE THREAD

**Issue by VikramTiwari** [microsoft/playwright#2768]
**Context:**
- Playwright Version: 1.1.1
- Operating System: Mac
- Node version: 12
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require("playwright");

(async () => {
	const browser = await chromium.launchPersistentContext("./udd", {
		headless: false,
	});
	const page = await browser.newPage();
	await page.goto("http://google.com/");
	await page.mouse.click(884, 277);
})();
```

**Describe the bug**
- Run the recipe, and close the dialog for mic permissions
- go back to google.com and zoom into the page to 150%
- run the code again and the click on mic icon won't work

The use case is related to this: https://github.com/microsoft/playwright/issues/2497

**Comment by JoelEinbinder** [comment]
The test doesn't quite work, because the coordinates change once the page is zoomed. But I can repro that we still can't click the element at the proper coordinates. Suspecting an upstream bug in chromium. No test because we don't have zoom support yet.

**Comment by dgozman** [comment]
Closing in favor of #2497.
