### ISSUE TITLE
[BUG] Locator.or() doesn't work with composite locators

### ISSUE THREAD

**Issue by Nav-2d** [microsoft/playwright#27688]
### System info
- Playwright Version: 1.39.0
- Operating System: Mac
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
test('is a test', async ({ page }) => {
  await page.goto('http://the-internet.herokuapp.com/iframe');

  const first = page.getByRole('menuitem', { name: 'File' });
  const second = page.frameLocator('iframe').locator('p').first();
  await expect(first.or(second)).toBeVisible();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

The tests passes with locator.or assertion

**Actual**

An error is displayed: `Error: expect.toBeVisible: Frame locators are not allowed inside composite locators`

P.S. maybe it is working as expected and we can't use composite locators with .or()

**Comment by ltsuda** [comment]
As `.frameLocator().locator().first()` returns another `frameLocator` and `.or()` expects a `Locator class`, that's why is not working.

https://playwright.dev/docs/api/class-framelocator#frame-locator-first
https://playwright.dev/docs/api/class-locator#locator-or

Maybe this can be a feature request. If you could filter `.locator('p', <some-filter-option>)` to select an unique locator to avoid using the `.first()` from `frameLocator` or instead of `.first()`, use some of the `.getBy()`, then it could work as a workaround.

**Comment by mxschmitt** [comment]
This is expected as of today, you can do it with the following workaround:

```ts
test('is a test', async ({ page }) => {
  await page.goto('http://the-internet.herokuapp.com/iframe');

  const first = page.getByRole('menuitem', { name: 'File' }).first();
  const second = page.frameLocator('iframe').locator('p').first();
  await Promise.race([
    first.waitFor({ state: 'visible' }).catch(() => {}),
    second.waitFor({ state: 'visible' }).catch(() => {}),
  ]);
  await expect(first.or(second)).toBeVisible();
});
```

**Comment by ENEMBI** [comment]
Hi, facing the same issue on the Zoom web app. 
Currently, if you start a meeting from Zoom web app all content gonna be inside an iframe, but if you just open the meeting link its not.

       ```
 this.frame = this.page.frameLocator("#webclient");
        this.btnJoinAudioByComputer = this.page.locator("#voip-tab button").or(this.frame.locator("#voip-tab button"));
```
        
: locator.click: Frame locators are not allowed inside composite locators, while querying "locator('#voip-tab button').or(frameLocator('#webclient').locator('#voip-tab button'))

**Comment by mxschmitt** [comment]
@ENEMBI this is expected as per https://github.com/microsoft/playwright/issues/27688#issuecomment-1771403495. Or does not work as of today with Locators on different Frames.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
