### ISSUE TITLE
[BUG]  Timeout 10000ms exceeded while waiting for event "download" Webkit CICD

### ISSUE THREAD

**Issue by Bohdan-Hevlich** [microsoft/playwright#27684]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [All]
- Browser: [ WebKit]
- Other info: CICD: Buildkite, docker#v5.8.0: image: mcr.microsoft.com/playwright:v1.38.1-focal

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'Webkit',
      use: { ...devices['Desktop Safari'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('Should download file', async ({ page }) => {
const downloadDocumentButton = await.page.locator(a[href="https://example/link/download"][target="_blank"]")
    const downloadPromise = page.waitForEvent("download");
    await downloadDocumentButton.click();
    const download = await downloadPromise;
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

Download should be as expected

**Actual**

Timeout happens cause download event doesnt happen

**Comment by Bohdan-Hevlich** [comment]
Hey, sorry for bad bug report, first time doing it with this template. Can I get help here because I can`t test download events on CICD while localy it works on safari browser. While trying to test it manually I see new screen that pops`up in new window after click, might it be the reason while tests are failing on cicd? 
<img width="1432" alt="Screenshot 2023-10-18 at 18 29 45" src="https://github.com/microsoft/playwright/assets/109958217/e5bcf237-ef4c-4ed2-a47c-6bdf737a856f">

**Comment by mxschmitt** [comment]
Hi, I think without a self contained repro we are unable to triage this issue further. We have various of tests covering [target=blank downloads](https://github.com/microsoft/playwright/blob/main/tests/library/download.spec.ts#L332), so we are very curious why it does not work with your site. Code wise it looks good on your side. Thanks!

**Comment by Bohdan-Hevlich** [comment]
@mxschmitt Hey, could the reason be in the logic how our download works? It opens a new tab and there starts a download, maybe playwright is waiting download event on the page with button, not on the new opened tab? But still I dont understand why it passes localy and fails on cicd....

**Comment by mxschmitt** [comment]
> Hey, could the reason be in the logic how our download works?

Yes. But [this test](https://github.com/microsoft/playwright/blob/main/tests/library/download.spec.ts#L332) looks like its covering your use-case.

Can you share a reproduction? Have you tried to use [tracing](https://playwright.dev/docs/trace-viewer-intro) to debug this issue further? Maybe this yields to more helpful debug output!

**Comment by Bohdan-Hevlich** [comment]
@mxschmitt I can`t send you a reproduction code but I have found the solution for me that works on cicd and on local machines in webkit - using direct file download :
const https = require("https");
const fs = require("fs");
const file = fs.createWriteStream(fileName);
const href = await this.page.$eval(fileLink, (el) => el.href);
    https.get(href, function (response) {
      response.pipe(file);
    });
    
    So I think we can close this task, just added this comment if someone will face same issue as me
