### ISSUE TITLE
[BUG] Problems with mock: status code -1  

### ISSUE THREAD

**Issue by mrrimlin** [microsoft/playwright#27698]
### System info
- Playwright Version: 1.38.1
- Operating System: macOS 12.6
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

```ts
// mock example
import type { BrowserContext } from '@playwright/test'

export async function mockActiveElementList(context: BrowserContext, path: string): Promise<void> {
 await context.route('**/v1/elements?page=1&pageSize=10&hasError=false&isArchived=false*', (route) => {
  route.fulfill({
   status: 200,
   path: path,
   headers: {
    'Connection': 'keep-alive',
    'Content-Type': 'application/json',
   },
  })
 })
}
```

```ts
//test example
test.describe.parallel('Test elements ', () => {
 test.use({
  storageState: AuthStorage.ADMIN,
 })

 let mainPage: MainPage
 let testPage: TestPage

 test.beforeEach(async ({ page, context }) => {
  mainPage = new MainPage(page)
  testPage = new TestPage(page)

  await Promise.all([
   await mockActiveElementList(context, 'e2e/mocks/data/mockActiveElementList.json'),
   await mockElement(context, 'e2e/mocks/data/mockElement.json'),
   await mockItems(context),
  ])
 })

 test('1st test elements', async () => {
  await mainPage.open()

  await mainPage.openElements(1) // jst click on 1st element on list
  await compPage.checkTestPage()
 })
```

My test getting flakky. I use mock requests, and getting -1 on response. 

**Steps**
- Run the tests, all test passed and all mocks work correctly
- Run tests again

**Expected**

expect the same - all test passed and mocks work :)
![tg_image_2008124029](https://github.com/microsoft/playwright/assets/12170925/58ab6a69-3912-45c3-b33a-cdb1da57da00)

**Actual**

Mock response code -1 
![tg_image_2978399097](https://github.com/microsoft/playwright/assets/12170925/7adacc13-b042-4b39-a87c-62f27e2d56e3)

**Comment by mxschmitt** [comment]
Can you share a full reproduction which we can run locally? The snippet is not enough for us in order to reproduce this.

Please re-file with a full repro we can run locally, thanks for your understanding!
