### ISSUE TITLE
[BUG] Error "Uncaught Object with guid handle@<hash> was not bound in the connection" when searching text in big amount of drop down items

### ISSUE THREAD

**Issue by mirao** [microsoft/playwright#27704]
It's a **regression** in Playwright 1.39. I'm able to reproduce it with Chromium and WebKit.
If I test it with Chromium or WebKit in Playwright 1.38.1, it works fine.

Unfortunately I'm able to reproduce it in our product (private) pages only, in Playwright integrated into CodeceptJS.

### System info
- Playwright Version: v1.39
- Operating System: Ubuntu 22.04
- Browser: Chromium, WebKit
- Other info: CodeceptJS 3.5.3

**Test file (self-contained)**

CodeceptJS part of code
```js
I.see(`${school}${schoolDelimiter}${schoolCourse}`, schoolCourseItem);
```

**Steps**

- There are about 3000 elements `schoolCourseItem` in a drop down menu on a page (the source of the element is in the stack, see below).
- Call the CodeceptJS method `I.see(text, schoolCourseItem)`

**Expected**

Success

**Actual**

It fails.

Stack:
```
1) AcceptRejectItem
           Create a MiP from the template:
         Uncaught Object with guid handle@98fe32e262edc9bb5e661ce034d5e861 was not bound in the connection
          at Connection._tChannelImplFromWire (/home/mirao/workspace/codeceptjs/node_modules/.pnpm/playwright-core@1.39.0/node_modules/playwright-core/lib/client/connection.js:207:26)
          at /home/mirao/workspace/codeceptjs/node_modules/.pnpm/playwright-core@1.39.0/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:129:20
          at /home/mirao/workspace/codeceptjs/node_modules/.pnpm/playwright-core@1.39.0/node_modules/playwright-core/lib/protocol/validatorPrimitives.js:98:34
    
      Scenario Steps:
      - I.see("ATSchool330193079741829
      ATSC 670498110758440", {xpath: .//*[contains(concat(' ', normalize-space(./@class), ' '), ' item ')][ancestor::*[(contains(concat(' ', normalize-space(./@class), ' '), ' visible ') and contains(concat(' ', normalize-space(./@class), ' '), ' menu '))]]}) at Object.createMiP (./pages/iPlanners.ts:177:11)
      - I.waitForElement({xpath: .//*[contains(concat(' ', normalize-space(./@class), ' '), ' item ')][ancestor::*[(contains(concat(' ', normalize-space(./@class), ' '), ' visible ') and contains(concat(' ', normalize-space(./@class), ' '), ' menu '))]]}) at Object.createMiP (./pages/iPlanners.ts:173:11)
      ...
```
Note that if I test it for a drop down menu where e.g. only one item exists, the test passes.

**Comment by mxschmitt** [comment]
We unfortunately need a reproducible to be able to act on it. I recommend reducing your test suite over and over again to end up at a small project which surfaces this issue.

**Comment by mirao** [comment]
I'm afraid reducing doesn't help unless I'm able to reproduce with a public data/page which isn't our case (it seems to be reproducible with big amount of data only and I can't share the data/page).
Feel free to close it. Maybe someone appends other instructions.

**Comment by harshmaur** [comment]
I will create a reproducible example for this. started noticing it, will post soon.
