### ISSUE TITLE
[Feature] Run playwright interactively from the command line

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#27710]
Hi!
It would have been very nice with a interactively/repl command line command similar to **wdio repl** command (https://webdriver.io/docs/testrunner/#wdio-repl) in playwright. I know that similar have been discussed before here: https://github.com/microsoft/playwright/issues/21881 but it's closed now. The repl.js suggestion in the closed request is very handy but becomes a bit stiff when I would like use some playwright command line args like --load-storageState, --project and so on. 
This could be very useful when we would like to try out stuff. 
An example could be like this:

npx playwright repl --load.storageState=storageState/myStorageState.json
_const browser = await chromium.launch({ headless: false })
const page = await browser.newPage()
await page.goto('https://my-fancy-page.com')_
[ Do some manual browser interaction ]
_await page.getByText('Fancy stuff').count()
-> 5_

this would allow me to start playwright from command line and interactive with in both from the command line with code and manually do stuff in the browser.
There could be some sort of helper implements as well to utilize the build in fixtures:
_const page = getFixture('page')_ or _const request = getFixture('request');_

It should support similar command line args as codegen and of course this could be integrated to codegen and to VS code. It would have been amzing to be able to set a break point in the test code or add page.pause() the debug the test and when it halts we could run playwright commands from a connected terminal in VS code

**Comment by denkorz** [comment]
+1

**Comment by mxschmitt** [comment]
This is out of scope for the Playwright project. We might reconsider it in the future, as of today you can use Node.js REPL which works with async/await:

<img width="652" alt="Screenshot 2023-10-19 at 16 38 57" src="https://github.com/microsoft/playwright/assets/17984549/5e43306a-3b40-4ff6-b0a2-24d29a008490">

**Comment by marcusNumminen** [comment]
Ok, I hope that you some day reconsider it, since it would have been relay nice to have this in codegen and in the VS code extension

**Comment by marcusNumminen** [comment]
I found this: https://gist.github.com/AutoSponge/5e2fc3eb65a9e010937766e581f2ee06
that I could modify to my needs. This would still be nice if we could have a REPL option in codegen

**Comment by marcusNumminen** [comment]
I created a REPL server program to run playwright from the command line using typescript:
https://github.com/marcusNumminen/playwrepl.ts

I use it quite often when I can't use codegen to get good locators. Also its nice when you just want to try out different things.

**Comment by sudharsan-selvaraj** [comment]
@marcusNumminen If you’re looking for a more visual way to write, run, and debug your Playwright tests, you might want to check out **Playcraft**.

It’s a new open-source tool I’ve been working on—a visual IDE for Playwright with a built-in code editor, live browser preview, real-time test execution, and even an element inspector & test recorder (just like codegen).

Github: [https://github.com/sudharsan-selvaraj/playcraft](https://github.com/sudharsan-selvaraj/playcraft)

<img width="3096" height="2100" alt="Image" src="https://github.com/user-attachments/assets/2ab90a67-bf7c-4cea-9128-3173701c7c93" />
