### ISSUE TITLE
[BUG] Cannot click inside OOPIF with non-zero padding

### ISSUE THREAD

**Issue by nadiaquraishi** [microsoft/playwright#27713]
### System info
- Playwright Version: 1.39
- Operating System: Windows 11
- Browser: Chromium
- Other info: This is ONLY happening on Chromium browsers, I tried it on Firefox and my script was successful.

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

Background: We are starting to implement an automated regression suite on our company's websites. I started automating the transaction process-- our process is a little more complex and involves the use of a transaction iframe, though I was able to get past this and continue testing. I reached a blocker when I tried to check our checkbox that reads "I agree to the terms of service." This is the error that I got:

![image](https://github.com/microsoft/playwright-python/assets/147441883/5e78ba6f-99a4-425f-a939-5ac364a65c86)

Playwright on Chromium has no problem finding the checkbox, but can't click it because it views the element as being 'blocked' by the highlighted fieldset:

![image](https://github.com/microsoft/playwright-python/assets/147441883/cf836f94-0af3-483e-a58d-583e65493f91)

Here is a sample script for repro:

```
import asyncio
from playwright.async_api import async_playwright

async def test_transaction():
    async with async_playwright() as playwright:

        browser = await playwright.chromium.launch(headless=False)
        context = await browser.new_context()

        page = await context.new_page()
        await page.goto("https://www.myfoodandbevtraining.com/products/food-handler/texas")
        await asyncio.sleep(3)

        await page.get_by_role("button", name="ENROLL NOW  $12.00").click()
        await asyncio.sleep(3)

        iframes = await page.query_selector_all('iframe')
        iframe = iframes[0]
        frame = await iframe.content_frame()
        await asyncio.sleep(5)

        await frame.get_by_role("checkbox", name="I agree to the terms of service.").check()

asyncio.run(test_transaction())

```

**Test file (self-contained)**

**Steps**
- [Run the test]
- [...]

**Expected**

Playwright is able to check agreement box and proceed with transaction.

**Actual**

Playwright is unable to check agreement box.

**Comment by dgozman** [comment]
Investigation notes:
- This page has an OOPIF that has `padding: 20px` style.
- When trying to click the checkbox, Playwright calls `DOM.getContentQuads` and receives quads relative to the `html` element inside the iframe (technically, relative to the local frame root viewport).
- Then Playwright adds iframe's position to get the actual content quads.
- However, there is a 20px padding that is between the iframe's position and the "viewport root" inside that iframe.
- Therefore, the point is 20px off in both coordinates.

---

Possible workaround - replace `padding: 20px;` on the iframe with `border: 20px solid transparent; box-sizing: content-box;`. This should achieve the same visual outcome, but hopefully not mess with the coordinates.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.
