### ISSUE TITLE
[Feature] Option to specify intersect/every in the command line args for running files that match grep

### ISSUE THREAD

**Issue by rob4629** [microsoft/playwright#27714]
I was looking at a way to further filter my automated tests from the [Test CLI](https://playwright.dev/docs/test-cli#introduction). My tests are broken up into different areas/pages of my website and I'd like a way of running type `X` tests (e.g `@smoke`) that are also type `Y` tests (e.g. `@payments`).

The current implementation of the command line acts like a "_union_" i.e. **ANY** test that has either `X` or `Y` in the test name is executed. So I'd like a way to add a flag to make this more like  an "_intersect_" where tests need to have both, instead of **ANY**.

```sh
npx playwright test X Y                     # Current behaviour unchanged
npx playwright test --grep-all "X,Y"        # Will run only tests that match both/all inputs
```

I would likely use this more to run Smoke tests for a particular page, rather than combining 2 types of tests. i.e. all Smoke tests within a particular test directory or file

```sh
npx playwright test X src/tests/directory_a/*  # Currently would run all tests with X in the filepath, and all tests under 'directory_a'
npx playwright test X src/tests/directory_a/* --some-new-command  # Would only run X tests _within_ 'directory_a'
```

**Comment by mxschmitt** [comment]
Would the following work for you?

```
npx playwright test src/tests/directory_a/.*/X
```

The arguments after "test" are interpreted as a regular expression.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by rob4629** [comment]
I missed your replies! I'll take a look at using RegEx in the command line and will open a more specific issue if it doesn't meet my needs. Thanks

**Comment by rob4629** [comment]
> Would the following work for you?
> 
> ```
> npx playwright test "src/tests/directory_a/.*/X"
> ```
> 
> The arguments after "test" are interpreted as a regular expression.

I was able to make use of this regex option alongside the `-g`/`--grep` flag, to find a solution for my problem 🙂 
```
yarn playwright test "X Y" -g "smoke"
```

This triggers all files that include `X` or `Y` in their file name, and filters the tests to only include those with the `smoke` flag. Thanks for helping
