### ISSUE TITLE
locateOnScreen for true Visual testing [Feature]

### ISSUE THREAD

**Issue by symon-skelly1991** [microsoft/playwright#27729]
WebGL Web Applications are becoming more and more popular for enhancing the user experience, but it comes at a cost for us Automation Engineers, as there is but 1 DOM element that can be accessed when working with a WEBGL Component:

The Canvas.

**The Problem:**
Extensive work would be required from development teams to incorprate complex solutions for 2D / 3D Graphical objects to be converted into a playwright-readable (read DOM) format, or to use flaky-at best, pain-inducing at wost hardcoded x/y co-ordinates of where the 2D / 3D Objects *Should* be located in the canvas at any given time. 

**The Solution:**
A locateOnScreen feature.

Input: 
Any supported image file format (.png, jpg, etc)

Feature Function:
Scan the current page for the matching image(s) that match the input image

Output:
boundingBox co-ordinates of the matching image(s) that were found on the page

This feature would allow any web page that has non-DOM-elements to be:
1. Interactable with
2. Assertable on

I believe the  toHaveScreenshot() and playwright comparator module has most of the functionality contained within already, we just need a way to tie it all together into a neat little, but robust feature for the up-and-coming new web experiences.

**Comment by yury-s** [comment]
The bounding box will be still inside a Canvas element and to interact with that you'd still need to use [raw input](https://playwright.dev/docs/api/class-mouse) methods. How is the resulting box expected to be used?

**Comment by symon-skelly1991** [comment]
There is no issue with needing to use raw input to interact with the resulting bounding box, the problem at the moment is that there is currently no way to reliably get that bounding box in the first place.

Example:

Inside the canvas I have a blue cube and a red triangle, I want to click on the center of each of these and then validate that they have each turned yellow once clicked.

By having the locateOnScreen yield the xy coordinates of each corner of a rectangular bounding box, we can:
A. Calculate the center xy coordinate of the found object for interaction.
B. Use this bounding box as the location for the toHaveScreenshot function that will only validate what's inside the box.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
