### ISSUE TITLE
[BUG] msedge-beta is not installing

### ISSUE THREAD

**Issue by timka-123** [microsoft/playwright#27726]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 11 22H2]
- Browser: [Microsoft Edge Beta]
- Other info:

### Source code

No code because it is an error while installing driver

**Steps**
- Create a Python project, install Playwright and try to install Microsoft Edge Beta browser and run the command down
```
(venv) PS C:\Users\user\pythonProject> playwright install msedge-beta
```

You recieve this traceback:
```
Downloading Microsoft Edge Beta
Downloading Microsoft Edge Beta
Installing Microsoft Edge Beta
ERROR: failed to install Microsoft Edge
Failed to install browsers
Error: Failed to install msedge-beta
```

**Expected**

Microsoft Edge Beta driver need to successfully installed

**Actual**

Microsoft Edge Beta driver is not installed

**Comment by timka-123** [comment]
no, it does not raising any errors

**Comment by timka-123** [comment]
![image](https://github.com/microsoft/playwright/assets/71185420/0df87d6d-392d-4871-a072-8f616e367266)

**Comment by mxschmitt** [comment]
Could you try running it in an administrator Terminal? Since the browser is now installed, it should now also work for you!

**Comment by timka-123** [comment]
> Could you try running it in an administrator Terminal? Since the browser is now installed, it should now also work for you!

playwright detected ms edge beta installed manually

**Comment by yury-s** [comment]
> > Could you try running it in an administrator Terminal? Since the browser is now installed, it should now also work for you!
> 
> playwright detected ms edge beta installed manually

Just to clarify, under administrator it is working as expected (playwright detects existing msedge beta installation and proceeds without errors), so we can close this bug?

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
