### ISSUE TITLE
afterAll hooks and cleaning up data

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#27728]
When using hooks to clean up data I run into an issue whenever I run a single file (Which by default runs it parallel). I understand what's happening but im not sure of an appropriate away to fix it.

In my example im usually doing something like this (In my example Widget is simply a client library that handles GET/POST/PATCH/DELETE requests for that resource):

```
test.describe.("/widgets", async () => {
  let widget: Widget;
  let widgetId
  test.beforeEach(async ({ request }) => {
    widget= new Widget(request);
  });
  test.afterAll(async ({ request }) => {
    //We also need to clean up our data when we are done
    const res = await widget.deleteWidget(widgetId)
    expect(res.status()).toBe(200)
  });
  test("Returns a status of 200", async ({
    request,
  }) => {
    const res = await widget.addWidget()
    const json = await res.json();
    widgetId= json.id;
    //do some assertions
  });
  test("....more tests", async ({
    request,
  }) => {
  //other tests
  });
});
```

So this works fine when ran as normal parallel (so one worker per file) but if you run the single file this will obviously fail because the widgetId is only getting filled in one test (and another worker won't be able to see it).

So the solutions seem to be:

1. Set the Test to serial
2. Set a beforeEach where the widget is created and a new id is set? (However if this is the case will each worker have it's own `let widgetId` within the describe block?)

Curious at the proper pattern for this.

**Comment by yury-s** [comment]
You can also mark this particular file as run in 'default' [mode](https://playwright.dev/docs/test-parallel#parallelize-tests-in-a-single-file) while everything else could still run in fully parallel mode:

```js
test.describe.configure({ mode: 'default' });

test.describe.("/widgets", async () => {
...
});
```

will that work for you?

**Comment by msmith1114** [comment]
@yury-y Yes that should work. I guess I could also mark it as serial but what would the be the "right" way to fix this issue? I guess putting everything in a beforeEach? Problem would be having access to the variables that the other test blocks need (like id's and such). 
However im not sure if ran parallel if each worker would have it's own "file level" id/variables

**Comment by yury-s** [comment]
> I guess I could also mark it as serial but what would the be the "right" way to fix this issue? I guess putting everything in a beforeEach? Problem would be having access to the variables that the other test blocks need (like id's and such).

This approach addresses your requirement of running tests from one file on one worker at a time and does it with standard mechanisms, so I'd say it is the "right" way. 

> Also in this case how exactly is default mode different from serial? Based on the docs they sound the same?

In serial mode if one of the tests fails the entire group will be retried from the beginning, whereas in default mode passed tests will not run again.

Closing this issue as there is a working solution and no planned actions on Playwright end.
