### ISSUE TITLE
[BUG] APIRequestContext.post reorders Multipart data

### ISSUE THREAD

**Issue by cserby** [microsoft/playwright#27720]
### System info
- Playwright Version: [v1.39] - TS/JS
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

The type of `APIRequestContext.post`'s `options` parameter's `multipart` attribute is `Record<string, ...>` (see `playwright-core/types/types.d.ts`).

```

    /**
     * Provides an object that will be serialized as html form using `multipart/form-data` encoding and sent as this
     * request body. If this parameter is specified `content-type` header will be set to `multipart/form-data` unless
     * explicitly provided. File values can be passed either as
     * [`fs.ReadStream`](https://nodejs.org/api/fs.html#fs_class_fs_readstream) or as file-like object containing file
     * name, mime-type and its content.
     */
    multipart?: { [key: string]: string|number|boolean|ReadStream|{
      /**
       * File name
       */
      name: string;

      /**
       * File type
       */
      mimeType: string;

      /**
       * File content
       */
      buffer: Buffer;
    }; };
```

This is incompatible with the `FormData` ([MDN/FormData](https://developer.mozilla.org/en-US/docs/Web/API/FormData)) shape that's used by `fetch` to represent this same data, as Playwright's one doesn't retain ordering, while `FormData` does.

**Expected**

Playwright API should allow specifying multipart form data in a specific order, and retain that order in the resulting API request.

**Actual**

The `serializePostData` function in `playwright-core/lib/server/fetch.js` iterates over the multipart data using
```
    for (const field of params.multipartData) {
```
which takes the Object's attributes in a non-defined order.

This causes a problem for me, as I'm trying to interact with a server using [graphql-upload](https://www.npmjs.com/package/graphql-upload) which in turn relies on the multipart data to be in a specific order.

**Comment by mxschmitt** [comment]
Could you share a reproduction with us? I tried the following which worked for me:

```ts
it('should support multipart/form-data and keep the order', async function({ context, page, asset, server }) {
  const given = {
    firstName: 'John',
    lastName: 'Doe',
    age: 27,
  };
  given['foo']  = 'bar';
  const givenKeys = Object.keys(given);
  const formReceived = new Promise<{error: any, fields: formidable.Fields}>(resolve => {
    server.setRoute('/empty.html', async (serverRequest, res) => {
      const form = new formidable.IncomingForm();
      form.parse(serverRequest, (error, fields, files) => {
        server.serveFile(serverRequest, res);
        resolve({ error, fields });
      });
    });
  });
  const [{ error, fields }, response] = await Promise.all([
    formReceived,
    context.request.post(server.EMPTY_PAGE, {
      multipart: given,
    })
  ]);
  expect(error).toBeFalsy();
  const actualKeys = Object.keys(fields);
  expect(actualKeys).toEqual(givenKeys);
  expect(response.status()).toBe(200);
});
```

in `tests/library/browsercontext-fetch.spec.ts` with `npm run ctest fetch:956`.

Are you using connect/connectOptions by any chance?

**Comment by cserby** [comment]
My investigation leads me to believe the error report from `graphql-upload` was caused by something else (`filename` attribute and `Content-Type` header being present inside the form part), not the incorrect ordering of the parts.

There seems to be nothing wrong with Playwright's implementation.

Thank you for looking into this.

**Comment by cserby** [comment]
@mxshmitt I'd like to reopen this issue, as I managed to provide a minimal reproduction in #30630
