### ISSUE TITLE
[BUG] TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"

### ISSUE THREAD

**Issue by abhijan1234** [microsoft/playwright#27739]
### System info
- Playwright Version: [v1.31.1]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info: Node V18.18.0

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[None]

**Steps**
- [Run the test]
- [...]

**Expected**
Expected scenario is to open the electron application

**Actual**
TimeoutError: electronApplication.firstWindow: Timeout 30000ms exceeded while waiting for event "window"
   at Utils.tsx:52

  50 |       console.log(`Coming herweeeee ${electronApp}`);
  51 |     // CleanUp local storage before running ITSYN.
> 52 |     (await electronApp.firstWindow()).evaluate(() => {
     |                        ^
  53 |       localStorage.clear();
  54 |     });

**Comment by mxschmitt** [comment]
We need a reproducible in order to look into such bugs. Please re-file with a Git repository attached which we can run locally.
