### ISSUE TITLE
[BUG] Element text from a table sometimes not fetched while processing in a for loop

### ISSUE THREAD

**Issue by mareru** [microsoft/playwright#27735]
### System info
- Playwright Version: 1.39.0
- Operating System: [Windows 10 Pro]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

```Typescript
  for (const entry of dayHoursMap.entries()) {
    const dayJIRA = entry[0];
    const dailyHoursJIRA = entry[1];

    console.log(entry[0], entry[1]); //"Mon" 8 "Tue" 0

    const child = await page.locator(".weekpicker-desktop-container");
    const parent = await child.locator("xpath=..");
    const secondDiv = await parent.locator(" > div").nth(1);

    const dayTableEntryUPWORK = await secondDiv
      .locator(".up-table")
      .getByRole("row")
      .filter({ hasText: dayJIRA });

    await dayTableEntryUPWORK.locator(".hours-cell").waitFor();
    const loggedHoursUPWORK = await dayTableEntryUPWORK
      .locator(".hours-cell")
      .textContent();

    console.log("Logged Hours UPWORK " + loggedHoursUPWORK?.trim());
  }
```

**Steps**
When running the code above, I have Logged Hours UPWORK fetched only for last days in a week usually, not for all the days in a week. 
This is the one of the outputs I get:
```
Mon 8h
Logged Hours UPWORK 
Tue 1h 30m
Logged Hours UPWORK 
Wed 8h
Logged Hours UPWORK 
Thu 8h
Logged Hours UPWORK 
Fri 9h
Logged Hours UPWORK 
Sat 0h
Logged Hours UPWORK 0:00 hrs
Sun 0h
Logged Hours UPWORK 0:00 hrs
```
It varies, sometimes I have last 4 days in a week to have the UPWORK hours value.
When I debug it, it all prints fine (for each day I have Logged Hours UPWORK entry)

**Expected**

I would get the same result regardless if I debug it or run the test

**Actual**

Works only when debugging the test

**Comment by yury-s** [comment]
Under debugger the test runs slower and the page likely has more time to load/populate the table with rows and you get more results in that case. It's impossible to tell from the provided snippet what is not working. If you think there is a bug in playwright we need a repro that we could run to reproduce the issue.

**Comment by mareru** [comment]
@yury-s Thanks for the reply!
I managed to solve it by waiting for the API, which fetches the data, to return 200.
So all good now. Sorry for the confusion, it is not the Playwright bug it is more of my code logic issue.
Thanks anyways for reaching out! ;D
