### ISSUE TITLE
Auth: One account per parallel worker

### ISSUE THREAD

**Issue by pavelkostyurin** [microsoft/playwright#27749]
### System info
- Playwright Version: v1.39.0
- Operating System: Ubuntu 22
- Browser: All
- Other info:

Is One account per parralel worker feature working? https://playwright.dev/docs/auth#moderate-one-account-per-parallel-worker

I copied code from there, but it seems like the code in this file is never get called.
For this line
```
 storageState: ({ workerStorageState }, use) => use(workerStorageState),
 ```
vsCode is telling me, that `Functions that return promises must be async.`

Also, do I need to implement acquireAccount(id) on my own? 

And in my playwright config I don't need to mention any storateState?

**Comment by pavelkostyurin** [comment]
My mistake, it's working as intended

**Comment by craitose** [comment]
> My mistake, it's working as intended

@pavelkostyurin  how did you acquireAccount(id) to resolve?  I am in the same boat and the documentation is not clear on this or about where the users are to be stored.
