### ISSUE TITLE
[Feature] Include annotations on skipped tests

### ISSUE THREAD

**Issue by costa-collibra** [microsoft/playwright#27748]
Hi

In our use case we have 18 teams all adding tests to a single Playwright repo. To ensure we only contact the right team when a test has failed each scenario is linked to the team owner using the annotations.

However it appears that if a test is skipped then it does not get this annotation maybe because the fixture is also skipped.

Here is our code example:

BASE FIXTURE

```typescript
setOwner: async ({}, use) => {
    const setOwner = async (teamName: TeamNames): Promise<void> => {
      const team = findTeamByName(teamName);
      test.info().annotations.push({ type: 'owner', description: team!.teamName });
      test.info().annotations.push({ type: 'channel', description: team!.channel });
    };
    await use(setOwner);
  },
```

TEAM FIXTURE

```typescript
owner: [
    async ({ setOwner }, use) => {
      await setOwner(TeamNames.PRIVACY);
      await use();
    },
    { auto: true },
  ],
```

TEST FILE

```typescript
test.fixme(
    'User syncs ADLS file system and validates sync results modal',
    async ({ assetPage, synchronizationStartedAlert, basicAdlsFileSystem }) => {
      await test.step('User clicks on sync button for the created ADLS file system', async () => {
        await assetPage.assetTabNavigationComponent.configurationMenu.click();
        await expect(assetPage.configurationComponent.crawlersComponent.syncButton).toBeEnabled();
        await assetPage.configurationComponent.crawlersComponent.syncButton.click();
      });

      await test.step('User validates the sync start notification alert', async () => {
        await expect(assetPage.commonPage.alert).toHaveText(
          synchronizationStartedAlert.title +
            synchronizationStartedAlert.description.replace('assetName', basicAdlsFileSystem.name!),
        );
        await assetPage.commonPage.alert.getByText(synchronizationStartedAlert.title).click();
      });
    },
  );
```

And in our HTML reports we can distinguish ownership very nicely.

<img width="1014" alt="image" src="https://github.com/microsoft/playwright/assets/118260471/bde81b9d-4e13-41bf-89eb-bd9f77ae49d6">

We also send these logs off to Kibana and use it to create some Grafana dashboards. One metric I am struggling to get is number of skipped tests by team owner so we can track this trend over time and offer support. However it looks like the data of the owner simply isnt there.

<img width="1702" alt="image" src="https://github.com/microsoft/playwright/assets/118260471/63018e70-c8c3-43c0-b4c8-f3fc07f5b716">

I verified this by looking at the logs in Kibana and I see there are no results with team owner

<img width="855" alt="image" src="https://github.com/microsoft/playwright/assets/118260471/24f76b13-ef8f-4f59-9595-1b86afeb695b">

But 36 results when team owner is removed and this matches the HTML report.

<img width="581" alt="image" src="https://github.com/microsoft/playwright/assets/118260471/4e4d9741-7cf6-414b-993f-50a6146e3020">

Could this functionality be added or is there something I can do differently?

Thanks
Costa

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/23180
