### ISSUE TITLE
[Feature] add official angular component testing support

### ISSUE THREAD

**Issue by yjaaidi** [microsoft/playwright#27753]
I am opening a new issue as the previous one (cf. https://github.com/microsoft/playwright/issues/19380) was closed by expiration.

The idea is to merge our [initial efforts](https://github.com/jscutlery/devkit/tree/main/packages/playwright-ct-angular) with @sand4rt's [initiative](https://github.com/sand4rt/playwright-ct-angular) and build an official package.

IMO, a large part of @sand4rt's work could be integrated as-is. We just have to discuss here whether analog's vite plugin should be a dependency or peer dependency _(as it couples the package to a specific version of Angular)_

_There is also another topic that deserves a dedicated issue but let's talk about here first.
What do people think of spies for handling outputs/events (for other fmwks/libs too of course)?
What about a community initiative like `experimental-ct-extensions` that helps with that on https://github.com/playwright-community?_

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/14153

If you want to transfer it to the playwright-community org or want to create a repository there, I'm more than happy to create a repo / give access there! Feel free to ping me either here or on Discord.
