### ISSUE TITLE
[BUG]"Debug Test" option in VS Code's Test Explorer fails with the following error message: "Error: ENOENT: no such file or directory"

### ISSUE THREAD

**Issue by ChuhengH** [microsoft/playwright#27756]
**Context:**
- Playwright Version: 1.39.0
- Operating System: macOS Monterey 12.2.1 (21D62)
- Node.js version: 18.15.0
- Visual Studio Code version:  1.82.3
- Playwright for VSCode extension version: 1.0.16
- Browser: Chromium

**Describe the bug**
When running a test case in VS Code's Test Explorer, the "Run Test" function operates successfully. However, the "Debug Test" option fails with the following error message: "Error: ENOENT: no such file or directory, open '/var/folders/1d/_fr2jlfx05v_g4lbbrv2fr500000gn/T/playwright-transform-cache-501/68/methods_68f5b7760f416bfd09b7e6392d5b6ed0aff70e4e.js'."

Note that when running the same test case via the command-line interface (CLI), both "npx playwright test --headed --debug" and "npx playwright test --headed" commands work as expected.

**Comment by mxschmitt** [comment]
This should be fixed in the next version, could you try @next? https://playwright.dev/docs/canary-releases

(don't forget to restart VSCode after installing it)

**Comment by yury-s** [comment]
Closing as it should be fixed by https://github.com/microsoft/playwright/pull/27607. The fix is already available in @next and will be released in 1.40. Feel free to file another issue if it does not work.

**Comment by karpikpl** [comment]
I'm seeing a similar issue but I'm already on `1.40.1` and it's about `/bin/sh` on linux and `cmd` on windows
![image](https://github.com/microsoft/playwright/assets/3539908/ed3746ac-c38f-4952-b8ee-259ba54b4565)

is this the same issue?
