### ISSUE TITLE
Handling hydration-related errors when Playwright executes interactions before event handlers are bound

### ISSUE THREAD

**Issue by kcrwfrd** [microsoft/playwright#27759]
We recently began experiencing severe flakiness in our tests, with things like button clicks not firing their event handlers, or form inputs that are supposed to be filled out are empty. We think that _part_ of the problem may be due to Playwright executing interactions before hydration has completed (components mounted, event handlers bound), as described here: https://playwright.dev/docs/navigations#hydration

The fix advised by those docs:

> The right fix for this issue is to make sure that all the interactive controls are disabled until after the hydration, when the page is fully functional.

Do you mean to say that buttons and inputs should be implemented along these lines?

```tsx
export const Button = ({
  children,
  disabled,
  ...props
}: HTMLProps<HTMLButtonElement>) => {
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
  }, [])

  return (
    <button disabled={!isMounted || disabled} {...props}>
      {children}
    </button>
  )
}
```

This seems particularly onerous for application developers...is this really the best recommendation? Are there any better alternatives?

Would something like this work?

```ts
if (typeof window !== 'undefined') {
  const mounted = new Promise((resolve, reject) => {
    mounted.resolve = resolve
  })

  window.mounted = mounted
}

const App = () => {
  useEffect(() => {
    window.mounted.resolve(true)
  }, [])
}

test.beforeEach(async ({ page, context }) => {
  await page.evaluate(async () => {
    await window.mounted
  })
})
```

**Comment by yury-s** [comment]
> Do you mean to say that buttons and inputs should be implemented along these lines?

Yes, something like that may work if you can setMounted once everything is hydrated.

> Would something like this work?

Yes, waiting for a state of JS in the page will also work but this in that case it only prevents the automation framework from interacting with the page too early, whereas a regular user can still click on the element before it's ready (e.g. the slow 3G network case from the docs). In general, we recommend writing tests in terms of user-observable behavior, i.e. playwright should use the same actionability criteria as a human user (such as element is disabled on the screen).

**Comment by kcrwfrd** [comment]
Ah, I was just kind of white-boarding ideas, I think there was an error in my code. Maybe something like this would work

```ts
const mounted = {}

mounted.promise = new Promise((resolve) => {
  mounted.resolve = resolve
})

window.mounted = mounted
```

and then in your Playwright tests, use [evaluate](https://playwright.dev/docs/evaluating):

```ts
await page.evaluate(async () => await window.mounted.promise)
```

I haven't tested this so not 100% if it would work.

You might also be able to emit a custom event... or await [waitForFunction](https://playwright.dev/docs/api/class-frame#frame-wait-for-function)... or perhaps even most simply, toggle a CSS class on `body` element, and await a selector/locator for it: https://playwright.dev/docs/api/class-locator#locator-wait-for

Hope this helps.

**Comment by manacy-keyvalue** [comment]
Why is this issue closed ?
My project is using next 14.0.4. I'm also facing the same issue. Tests become flaky and automation tests are not predictable and I suspect that playwright is performing actions before hydration has completed (before the listeners are attached).

Is there any straight forward solutions to this issue instead for shortcuts ?
A lot of developers could be facing the same issue and might also be wasting their time debugging it, without realising what is happening.

**Comment by kcrwfrd** [comment]
@manacy-keyvalue the ticket is closed because it's expected behavior, and they won't be making any changes to address it.

We ended up creating a base `Button` component like this

```tsx
const Button = ({ disabled, onClick, ...restProps }) => {
  const [isMounted, setIsMounted] = useState(false)

  useEffect(() => {
    setIsMounted(true)
  }, [])

  const isDisabled = disabled || (onClick && !isMounted)

  return (
    <button disabled={isDisabled} onClick={onClick} {...restProps} />
  )
}
```

I think this is the best solution because as explained in the docs, the tests are really surfacing a problem that occurs in real world situations on slow connections, where the button may be rendered before the onClick handler is bound during hydration, leading to frustrating clicks that don't do anything (the test failures).

When the button is rendered as disabled, and then becomes enabled on hydration, this at least clues the user in that they can now click and it will work.

**Comment by matewka** [comment]
@kcrwfrd thank you for this thread and the proposed solution.

While reading it, it occurred to me that hydration is really a serious problem in the SSR architecture.

I've been struggling with flaky tests and really weird errors occurring only in Playwright runtime, pretty much from the beginning of my project. It's based on Remix, but I had similar problems in another project in Next.

Anyway,
I just wanted to point out in this thread, how nicely Remix's architecture can solve the button issue with their "oldschool" forms approach that works even with Javascript disabled (I know, who would do that in their browser, but here we are with 3G networks). If you don't know what I'm talking about, you can refer to [Remix docs](https://remix.run/docs/en/main/discussion/data-flow).

**Comment by SorooshGb** [comment]
I'm just going to add in these key phrases to help people find this issue and the possible solution when searching google, because I struggled to understand the issue and find anything about it online until I realized it was because of hydration.

- Input field being cleared after calling `.fill()` on it after doing `await page.goto()`
- Playwright test fails because it skips filling the first input field (React, Next.js)
- The issue doesn't happen if I first do a click on the input or do something before filling the input
- The rest of the inputs actually do get filled

---

Well, you can see Playwright docs talking about this here:  
👉 [https://playwright.dev/docs/navigations#hydration](https://playwright.dev/docs/navigations#hydration)

My solution for now is writing this custom hook:

```ts
import { useEffect, useState } from 'react';

export function useIsMounted() {
  const [isMounted, setIsMounted] = useState(false);

  useEffect(() => {
    setIsMounted(true);
  }, []);

  return isMounted;
}
```

And using it wherever there are forms that render initially on a page and need to be hydrated before being able to actually interact with them.

This also solves the problem, and I agree with OP:  
👉 [https://github.com/microsoft/playwright/issues/27759#issuecomment-1989637738](https://github.com/microsoft/playwright/issues/27759#issuecomment-1989637738)
It's actually good that Playwright causes flakiness here, because that just shows what will happen if people with slow connections try to interact with forms before hydration finishes.
