### ISSUE TITLE
[Feature] Be able to distinguish a `Page` from a `MountResult`

### ISSUE THREAD

**Issue by opack** [microsoft/playwright#27751]
Hello!
I am using Playwright both for component testing and end-to-end testing. I would love to be able to reuse the POMs I created during component testing to simplify my e2e tests.

However it is not very easy, because although `Page` and `MountResult` share the same `getBy*` methods, there is no easy way (that I know of 😅) to distinguish them when we need specific process.

For example, I have a POM for some form component. In this POM, I have a `signUp` method that waits for an API to be called. Here is a simplified version of this POM:
```typescript
export class SignupFormPOM {
	public readonly page: Page

	constructor(
		public readonly component: MountResult
	) {
		this.page = component.page()
		this.email = component.getByLabel('Email')
		this.password = component.getByLabel('Password')
		this.username = component.getByLabel('Username')
		this.submit = component.getByRole('button', { name: 'Sign up' })
	}

	public signUp = async (email: string, username: string, password: string): Promise<void> => {
		await this.email.fill(values.email)
		await this.username.fill(values.username)
		await this.password.fill(values.password)

		const responsePromise = this.page.waitForResponse('*/**/accounts:signUp?*')
		await this.submit.click()
		await responsePromise
	}
}
```
In my component tests, I have a fixture that creates this POM and makes it available to all tests:
```typescript
const test = base.extend<{ pom: SignupFormPOM }>({
	pom: async ({ mount }, use) => {
		const pom = new SignupFormPOM(await mount(SignupPage))
		await use(pom)
	}
})
```
To be able to reuse this POM in the e2e part, I want to do something similar, but passing the `Page` directly:
```typescript
const test = base.extend<{ signUpFormPOM: SignupFormPOM }>({
	signUpFormPOM: async ({ page }, use) => {
		const signUpFormPOM = new SignupFormPOM(page)
		await use(signUpFormPOM)
	}
})
```
So, I have to adjust my POM. At this point, I am a bit sad that there is no common type between `MountResult` and `Page`, but I can use a union type. So my POM becomes:
```typescript
type PlaywrightContainer = Page | MountResult
...
	constructor(
		public readonly component: PlaywrightContainer 
	) {
```
And here comes the ugly part I would love to remove: next thing I was doing in the constructor was retrieving the `page` so that I can later use it. Problem is that the only way to know what kind of "Playwright container" I receive is by trying to access the `page()` method and assume that if it throws an error, then it means that I already have a `Page`:
```typescript
		try {
			this.page = (container as MountResult).page()
		} catch (error) {
			this.page = container as Page
		}
...
```

I would love to be able to access some "kind" attribute. I know that `Page` has a `_type` attribute with value `Page`, but it is not public, and `MountResult` does not have such attribute.

Is it possible to implement such attribute? Or is there something I am missing (in this case: sorry for the issue 🤐)?

Thanks in advance for considering it!

**Comment by yury-s** [comment]
You can pass the page explicitly as the constructor parameter:

```js
constructor(
  public readonly component: PlaywrightContainer,
  public readonly page: Page
) {

//
const test = base.extend<{ pom: SignupFormPOM }>({
	pom: async ({ mount }, use) => {
                const mountResult = await mount(SignupPage);
		const pom = new SignupFormPOM(mountResult, mountResult.page())
		await use(pom)
	}
})

//..
const test = base.extend<{ signUpFormPOM: SignupFormPOM }>({
	signUpFormPOM: async ({ page }, use) => {
		const signUpFormPOM = new SignupFormPOM(page, page)
		await use(signUpFormPOM)
	}
})

```

Alternatively, you can get the page like this: `this.page = (component as Awaited<ReturnType<typeof mount>>).page?.() || (component as Page);`

Would that work?

**Comment by opack** [comment]
Thanks for the leads :-) Indeed, it could pass it to the constructor, and I thought about it, but this did not please me as I think this should be transparent (my POM should be able to retrieve the current page by itself).

Regarding your other proposal, I admit I am not good enough with TypeScript generics to be able to come to such solution by myself, so thank you 😊

I just had to adjust it a bit because in fact I externalized this "get page from a Playwright 'container'" into another function, where there is no `mount`.

So, for the posterity (and future readers), here is what my function looked like before:
```typescript
export const getPage = (container: Container): Page => {
	try {
		return (container as MountResult).page()
	} catch (error) {
		return container as Page
	}
}
```
And here is the full final file (in case someone passing by needs it):
```typescript
// container.type.ts
import type { Page } from '@playwright/test'
import type { MountFunction, MountResult } from './mount-result.type'

export type Container = Page | MountResult

/**
 * There is no easy way to distinguish a `MountResult` from a `Page`. So, the only
 * way to retrieve the `Page` in both cases is to try to access the `page()` method
 * (which only exists in `MountResult`) and assume that we already have a `Page` if
 * this method does not exist.
 *
 * @param container The container whose `Page` instance we want.
 * @returns `Page` instance, either from `MountResult.page()` or the container itself
 * @see https://github.com/microsoft/playwright/issues/27751
 */
export const getPage = (container: Container): Page =>
	(container as Awaited<ReturnType<MountFunction>>).page?.() || (container as Page)
```
And the referenced `mount-result.type`:
```typescript
// mount-result.type
import type { test } from '@playwright/experimental-ct-svelte'
export type MountResult = Awaited<ReturnType<Parameters<Parameters<typeof test>[1]>[0]['mount']>>
export type MountFunction = Awaited<Parameters<Parameters<typeof test>[1]>[0]['mount']>
```

Just to be clear: many thanks for this solution, which works and helps me continuing my dev ;-) That being said, I still think this could be great to be able to easily distinguish those two types :-)

**Comment by yury-s** [comment]
Closing for now as there is a workaround and we are not planning to add specific support for such differentiation at the moment but we'll keep the use case in mind.
