### ISSUE TITLE
[Electron] ability to disconnect from debugger without closing the app

### ISSUE THREAD

**Issue by atali** [microsoft/playwright#2775]
We have a use case where we are testing the close of the app but in our afterEach will call app.close() because there is other tests that need to be closed as well.

The app is already closed during the test, when we call app.close(), we have an exception.

Can you provide a method that expose the disconnect method:

```
  async disconnect() {
    this._nodeConnection.close();
  }
```

or maybe a *close()* method that will check if the app is already closed  and it will just disconnect from the debugger
```
  async close() {
   try {
        await this.evaluate(({ app }) => app.quit());
    } catch(error) {}
    this._nodeConnection.close();
  }
```

**Comment by pavelfeldman** [comment]
I'll close this as a part of the bug triaging process. We have hundreds of bugs and feature requests with dozens and even hundreds of upvotes, while this one only has a few thumbs up. Please feel free to open a new bug and link this one if you'd like to see it addressed.
