### ISSUE TITLE
[BUG] Cannot set indeterminate = true on checkbox

### ISSUE THREAD

**Issue by Estegar** [microsoft/playwright#27757]
### System info
- Playwright Version: v1.39.0
- Operating System: Windows 11
- Browser: Google Chrome
- Other info: In Playwright UI

### Source code
Here's dummy site that will allow to reproduce the problem:
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Checkbox Example</title>
</head>
<body>
    <h1>Checkbox Example</h1>
    <input type="checkbox" id="checkbox1" checked>
    <label for="checkbox1">Checkbox 1</label><br>
    <input type="checkbox" id="checkbox2" checked>
    <label for="checkbox2">Checkbox 2</label><br>
    <input type="checkbox" id="checkbox3" checked>
    <label for="checkbox3">Checkbox 3</label><br>
    <input type="checkbox" id="checkbox4" checked>
    <label for="checkbox4">Checkbox 4</label><br>

    <script>
        const checkboxes = document.querySelectorAll('input[type="checkbox"]');
        checkboxes.forEach((checkbox, index) => {
            checkbox.addEventListener('click', () => {
                if (index > 0) {
                    checkboxes[0].indeterminate = true;
					console.log("Fired indeterminate!")
                }
            });
        });
    </script>
</body>
</html>
```

If you click manually any checkbox except checkbox 1 then checkbox 1 becomes indeterminate = true.

**Steps**
await page.goto(`file://location/index.html`)
await page.locator("#checkbox2").uncheck()/.click()
await expect(page.locator("#checkbox1")).toHaveAttribute("indeterminate", "true")

This test will fail on the last step even though manually everything is working fine.

**Expected**
Checkbox should be checked as indeterminate

**Actual**
Checkbox stays checked and indeterminate is still false even though it is set in javascript code on the site.
I also have a site where checkbox unchecks instead of indeterminate = true but i cannot provide example

**Comment by yury-s** [comment]
`indeterminate` is [a JS property](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes) and not a DOM attribute. When you set it on the checkbox its html element does not get indeterminate attribute, so you need to check for its presence via `toHaveJSProperty` rather than `toHaveAttribute`:

```js
  await page.locator("#checkbox2").click()
  await expect(page.locator("#checkbox1")).toHaveJSProperty("indeterminate", true)
```

**Comment by Estegar** [comment]
Ok, but the problem is still there, the checkbox doesn't change to indeterminate state. It stays unchecked and you can see it in the Playwright UI. If you try it manually then everything is fine.
The problem is not that i cannot properly assert this input, the problem is that input does not change at all. I looked at html, at properties and it stays the same when i use Playwright.

**Comment by Estegar** [comment]
Nevermind, it seems like a visual bug. I tried your solution and it works fine, the only thing that is not working is checkbox visuals, it stays unchecked, but it is a minor problem.
