### ISSUE TITLE
[BUG] Chrome Beta install fails on macOS

### ISSUE THREAD

**Issue by alextreppass** [microsoft/playwright#27764]
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 14.0 Sonoma (23A344)
- Browser: Chromium
- Other info: https://bugs.chromium.org/p/chromium/issues/detail?id=1487920&q=sonoma%20timezone&can=2

### Source code

N/A

**Steps**

Playwright 1.39.0 installs Chromium 119.0.6045.9 (Developer Build) (arm64), which suffers from the above Chromium bug.

Launch a playwright test and in the Chromium developer console, on OSX Sonoma, run: 

```js
new Intl.DateTimeFormat().resolvedOptions().timeZone
```

**Expected**

This should not be `undefined`.

**Actual**

It is `undefined`.

From the Chromium issue above, it appears to have been fixed in the normal _Chrome_ browser as of version `118.0.5993.96`.

However, the version of Chromium pulled down by Playwright (119.0.6045.9) appears to be unfixed still. Is it possible for Playwright to bump your Chromium version? Or for us to specify a bleeding-edge version to get around this?

Thanks

**Comment by yury-s** [comment]
> Is it possible for Playwright to bump your Chromium version?

We update browser versions with each minor release, so in next (1.40) it will be bumped to Chromium 120.

> Or for us to specify a bleeding-edge version to get around this?

Yes, you can test against official Google Chrome `stable` or `beta` [channels](https://playwright.dev/docs/api/class-testoptions#test-options-channel). See [this page](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge) for more information.

**Comment by alextreppass** [comment]
Thanks for the prompt response @yury-s.

I couldn't get that working, am leaving steps in case any other developer is in the same boat.

Things I tried:
Adding a web/playwright.config.ts with the following:
```ts
import { defineConfig, devices } from '@playwright/test';

console.log('file being read');

export default defineConfig({
  projects: [
    {
      name: 'Google Chrome',
      use: { ...devices['Desktop Chrome'], channel: 'chrome-beta' },
    },
  ],
});
```

We also had a `hooks.ts` with a `BeforeAll`, which I changed as follows:
```ts
BeforeAll(async function () {
  browser = await chromium.launch({
    headless: !!process.env.HEADLESS,
    channel: 'chrome-beta',
  });
});
```

Our playwright command then prompted me to install chrome-beta, via `yarn playwright install chrome-beta`

Unfortunately, it downloads a universal .dmg file but then OSX Sonoma complains about the file:
![Screenshot 2023-10-24 at 1 17 11 pm](https://github.com/microsoft/playwright/assets/154376/bb009bcb-bd31-4ced-a248-b8703585626c)

I can't tell if this is a Google distribution issue, or a Playwright issue, or something else

**Comment by mxschmitt** [comment]
Same for me on macOS 14. As a workaround for now you can install it manually via https://dl.google.com/chrome/mac/universal/beta/googlechromebeta.dmg.

**Comment by alextreppass** [comment]
Hello, can confirm that switching to chrome-beta fixes the timezone issue: 
```js
new Intl.DateTimeFormat().resolvedOptions().timeZone
``` is defined

**Comment by mxschmitt** [comment]
Awesome! We still take this bug as an opportunity to look into why the installation was not working. No action needed from your side anymore since we can repro, thanks!
