### ISSUE TITLE
[Feature] Support for Typescript `using` keyword

### ISSUE THREAD

**Issue by plushdohn** [microsoft/playwright#27761]
I think supporting Typescript's new [explicit resource management](https://devblogs.microsoft.com/typescript/announcing-typescript-5-2/#using-declarations-and-explicit-resource-management) syntax out of the box would be a huge win for Playwright.

In full-stack apps that use Prisma or other ORMs it's very common to create temporary DB entries and removing them at the end of each test. This usually requires wrapping the whole test in a `try/finally` block, which is one of the main use-cases for `using` in TypeScript.

Here's a demo:

```ts
test('my test', async ({ page }) => {
  // Create a temporary DB entry just to set up the environment
  const post = await myDb.posts.create(/* */);

  try {
    // Test-related code
  } finally {
    // Delete entry at end of test
    await myDb.posts.delete(post.id);
  }
}
```

This would become:

```ts
test('my test', async ({ page }) => {
  await using post = await getTemporaryPost();
  
  // Test-related code

  // No need for cleaning up `using` takes care of it at the end of the scope
});
```

I would be happy to open a PR if you approve the feature!

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/27141. Please upvote it there!
