### ISSUE TITLE
Add Google Cloud Build to CI Docs

### ISSUE THREAD

**Issue by hemang-rajyaguru** [microsoft/playwright#27769]
Hi,

I have integrated Playwright using Google Cloud Build and NodeJS and I want to update the docs: https://github.com/microsoft/playwright/blob/main/docs/src/ci.md to add in a Google Cloud Build section so people can also use Google Cloud Build to run Playwright tests.

I read the guide asking to raise an issue before starting any work. Is that OK for me to do?

**Comment by yury-s** [comment]
>  Is that OK for me to do?

Yes, feel free to open a PR. We can decide if it's worth adding to the docs during code review.
