### ISSUE TITLE
[BUG] docker file node 16 m1

### ISSUE THREAD

**Issue by vitaly87** [microsoft/playwright#27779]
Hi all, I am looking for docker image that base on node 16 and M1 chip, I want to run codeceptjs in this docker and the issue that I need to have node 16 in order to run visual regression, any can link what docker image should I use ?

thanks !

**Comment by yury-s** [comment]
Node 16 reached End Of Life on 2023-09-11, see https://nodejs.dev/en/about/releases/ and we support it as best effort only. With that said, you can build your own docker image with Node16 e.g. by modifying [our dockerfile](https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy) but I'd recommend you update your code to work with Node 18+ instead.

**Comment by mxschmitt** [comment]
Feel also free to use our Docker image as a base image: https://playwright.dev/docs/docker which is always based on the latest LTS.
