### ISSUE TITLE
[BUG] URL doesn't update when redirect passes through route.fetch() + route.fulfill()

### ISSUE THREAD

**Issue by gofr** [microsoft/playwright#27776]
### System info
- Playwright Version: v1.39
- Operating System: Ubuntu 20
- Browser: All
- Other info:

### Source code

For some tests I'm writing I need to use `route.fetch()` + `route.fulfill()` because I need to propagate a header through redirects, as mentioned here: https://playwright.dev/docs/api/class-route#route-continue. But when I do that, I can no longer access the URL of the page I'm redirected to:

```typescript
import { test, expect } from '@playwright/test';

test('Pass Twitter redirect through route.continue', async ({ page }) => {
  page.route('https://x.com', async (route) => {
    route.continue();
  });
  await page.goto('https://x.com');
  expect(page.url()).toEqual('https://twitter.com/') // Passes
});

test('Pass Twitter redirect through route.fetch + route.fulfill', async ({ page }) => {
  page.route('https://x.com', async (route) => {
    const response = await route.fetch();
    await route.fulfill({ response });
  });
  await page.goto('https://x.com');
  expect(page.url()).toEqual('https://twitter.com/') // Fails. URL is still https://x.com
});
```

**Expected**

Both tests pass.

**Actual**

When using fetch + fulfill, the page URL doesn't update to the redirect target.

**Comment by yury-s** [comment]
This is working as intended, the browser doesn't know anything about the other URL when you fulfill the request. It stays on the original URL. In Chromium and Firefox you can fulfill with a redirect response to change the URL:
```js
    await route.fulfill({
      status: 301,
      headers: {
        'location': 'https://twitter.com/',
      }
    });
```
but in that case you won't be able to provide the final response body. A workaround in this case would be to make the page navigate directly to the final URL. Would that work?

**Comment by gofr** [comment]
Oh, I understand, thanks! I was imagining `fetch` and `fulfill` to be more magical than they are, that all the requests were still going through the browser, but modified.

I'm not sure if that workaround will work in my case. I might need a few different approaches. But I should be able to come up with something now. :)

**Comment by jjshao-ms** [comment]
> This is working as intended, the browser doesn't know anything about the other URL when you fulfill the request. It stays on the original URL. In Chromium and Firefox you can fulfill with a redirect response to change the URL:
> 
> ```js
>     await route.fulfill({
>       status: 301,
>       headers: {
>         'location': 'https://twitter.com/',
>       }
>     });
> ```
> 
> but in that case you won't be able to provide the final response body. A workaround in this case would be to make the page navigate directly to the final URL. Would that work?

Seems in this method, the new request target to the redirected location could not be caught by the `page.route`. Is that also intended?

**Comment by younes-zeboudj** [comment]
You can limit the number of redirectes to be followed as a workaround:

`           const response= await route.fetch({
                    maxRedirects: 0,
                }).catch(e=>{
                    console.log(e)
                })

                return route.fulfill({response})
                `
