### ISSUE TITLE
Native App testing capability for IOS & Andriod  

### ISSUE THREAD

**Issue by dipanjan-it** [microsoft/playwright#27778]
We are deligted to see the capabilities of playwright thus far, and want to adopt this as our standard tool for micro frond-end automations. Our use cases includes

1. paralle execution in various browsers/cross browser executions 
2. native app for Android (a majority is taken care through BrowserStack)
3. native app for IOS (a majority is taken care through BrowserStack)

Wondering if there is any plan to support the #2 & #3 capabilities in near fututre? This will help us in taking informed decision about this tool. Thanks!

**Comment by yury-s** [comment]
Playwright provides experimental support for Android automation, see [this page](https://playwright.dev/docs/api/class-android). There are no immediate plans for extending this functionality/adding similar support for iOS.

**Comment by omnarayan** [comment]
For anyone landing here looking for a way to drive native iOS/Android apps from Playwright today:

[DeviceDeck](https://github.com/devicelab-dev/DeviceDeck) serves an iOS Simulator or Android emulator as a web page whose DOM mirrors the app's accessibility tree:

- accessibility IDs → `data-testid`
- element types → ARIA roles

So stock Playwright can drive it with `getByRole` / `getByTestId`, with no changes to Playwright needed.

Example spec: https://github.com/devicelab-dev/DeviceDeck/tree/main/examples/playwright

**Limitations:** simulators/emulators only, macOS host.

*Disclosure: I'm the author.*
