### ISSUE TITLE
[Question] Global setup code not able to access from different folder

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27770]
![image](https://github.com/microsoft/playwright/assets/21674533/c3c7d695-d29d-4511-8768-346eaf20cca6)

The commented line works fine, I am trying globalsetup code from other file not working. Kindly suggest how to handle the globalsetup file in playwright config

**Comment by yury-s** [comment]
Can you share more details about your project structure, which exact file is not matched by the expression? Would be best if you shared the project that is not working.

**Comment by iburahim786** [comment]
sure, let me create some dummy project in github and share

**Comment by yury-s** [comment]
From what I see you playwright.config.ts is in the top level folder, so the globalSetup.ts is under src/ui/config/globalSetup.ts which would not be matched by the filter from the first screenshot. (`../config/globalSetup.ts`).

> I hope the below helps you to find the project structure, If still want me to create a dummy project, I will do that.

Please do. I'll close this bug to make it easier for the next bug triager to follow, so far all the information points to a misconfiguration. If you find it not be the case, create a new issue and attach your repro there, we'll have a look.

> And one more question, Why aren't able to ignore the jsonReports folder into git commit, Do we have any specific settings added in config files? If no dependencies, can we possibly ignore them?

Adding them to .gitignore should work. This is a question to you git setup though, playwright should not affect that. If you think it does, please provide a repro project.
