### ISSUE TITLE
[Feature] ability to add own browser implementation

### ISSUE THREAD

**Issue by DudaGod** [microsoft/playwright#27781]
In my project I run tests not only in CDP browsers, but also in browsers that only support w3c protocol (chrome/custom apps on android emulator, safari on ios simulator, etc). It means that I can't use playwright for w3c browsers and should have multiple tools to run e2e tests. I know that you don't want to support this protocol, so it would be great if there was some kind of API that allows users to add their own browser implementation. It is obvious that in addition to implementing the browser, users will also need to write commands (or overwrite existing ones using fixture) to work with it. And of course, some of the functionality will not work in it (traces and other features), but I think it's still worth the effort.

What do you think about this? I'm currently researching how I can make Playwright work with w3c and would be glad for any help or advice.

> Do you think others might benefit from this as well?

It looks like in [this issue](https://github.com/microsoft/playwright/issues/1122) many users are waiting for such an opportunity

**Comment by pavelfeldman** [comment]
Think about it this way: present browsers expose capabilities of the basic Calculator that can add, subtract, multiply. Playwright requires capabilities of a Scientific Calculator that can do trigonometry, exponential calculus, etc. You can't point Playwright to a basic protocol and expect things to work, so your request is a non-starter.
