### ISSUE TITLE
[Question] Running some tests with different projects

### ISSUE THREAD

**Issue by mustafasdet** [microsoft/playwright#27784]
I have multiple projects in my playwright with typescript framework and different tests to run with one of these projects. For example, there are projectA, projectB, projectC. I want to run 3 tests with projectA, 4 tests with projectB, 2 tests with projectC.
How can I achieve to run these tests with one command?
Thanks.

**Comment by yury-s** [comment]
You can specify project names and test filters separately, so if the same test appears in several projects it will run in each of them. You can probably achieve certain success with a combination of [tags](https://playwright.dev/docs/test-annotations#tag-tests). You can also workaround that by creating a separate project that matches only that tests which you want to run with corresponding project:
```js

const projectA = {
  name: 'projectA',
  use: { ...devices['Desktop Chrome'] },
};
const projectB = {...};
const projectC = {...};

export default defineConfig({
  testDir: './tests',
  projects: [
    {
      ...projectA,
      name: 'projectAWith3Tests',
      testMatch: '**/example.spec.ts',
    },
    {
      ...projectB,
      name: 'projectBWith4Tests',
      testMatch: '**/another.spec.ts',
    },
    {
      ...projectB,
      name: 'projectCWith2Tests',
      testMatch: '**/different.spec.ts',
    },
  ],
});

```

And then just pass corresponding project names.

**Comment by mustafasdet** [comment]
@yury-s 
I like the approach about specifying projects and test filters separately.
I have thought another workaround by using testDir. I will collect related tests in the corresponding folder:
```
projects : [
name: 'projectA',
testDir: ./tests/folderA,..]}
```
I will use both options for optimization.
Thanks a lot.

**Comment by mustafasdet** [comment]
@yury-s one question for 
> And then just pass corresponding project names.
We should use ```name: 'projectAWith3Tests'```
