### ISSUE TITLE
[BUG] (node:77811) [DEP0160] DeprecationWarning: The multipleResolves event has been deprecated.

### ISSUE THREAD

**Issue by dylang** [microsoft/playwright#27780]
### System info
- Playwright Version: v1.39.0
- Operating System: MacOS 14
- Browser: Chrome
- Other info: Node 18, Node 20

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

Add this to the top of any test file or config:

```ts
const process = require("node:process");
process.on("multipleResolves", (type, promise, reason) => {
  console.log("CAUGHT MULTIPLE RESOLVES");
  console.log("type", type);
  console.log("promise", promise);
  console.log("reason", reason);
  process.exit(1);
});
```

**Link to the GitHub repository with the repro**

It can be reproduced with any test I've tried, including https://github.com/microsoft/playwright/blob/main/examples/todomvc/tests/integration.spec.ts using the above snippet.

**Test file (self-contained)**

```ts
const process = require("node:process");
process.on("multipleResolves", (type, promise, reason) => {
  console.log("CAUGHT MULTIPLE RESOLVES");
  console.log("type", type);
  console.log("promise", promise);
  console.log("reason", reason);
  process.exit(1);
});

it('should check the box using setChecked', async ({ page }) => {
  await page.goto('https://demo.playwright.dev/todomvc');
   await expect(page.getByTestId('todo-title')).toHaveText([
      'Not this text'
    ]);
});
```

**Steps**

- Run the test

**Expected**

Just show the errors.

**Actual**

After every error or browser close:

```
CAUGHT MULTIPLE RESOLVES
type resolve
promise Promise { undefined }
reason undefined

CAUGHT MULTIPLE RESOLVES
type resolve
promise Promise { undefined }
reason { unexpectedly: true, code: 1, signal: null }
```

This one is harder for me to create a reproduction for, but we get this without the above `multipleResolves` catching code.

```
(node:77760) [DEP0160] DeprecationWarning: The multipleResolves event has been deprecated.
    at node:internal/process/promises:139:7
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
```

I've spent hours trying to figure out where this is happening in Playwright's code with no luck.

**Comment by yury-s** [comment]
Can you be more specific what exactly is not working as expected? You have `process.exit(1);` in an event handler which terminates the processes.

**Comment by yury-s** [comment]
`multipleResolves` has been [deprecated](https://nodejs.org/api/process.html#event-multipleresolves) in Node.js since v16. According to the same document: "However, the occurrence of this event does not necessarily indicate an error. For example, [Promise.race()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) can trigger a 'multipleResolves' event.", we have quite a few legit use cases for Promise.race like that. This is working as intended.
