### ISSUE TITLE
[Feature] Case insensitive assertion in ILocatorAssertions.ToHaveAttributeAsync() method

### ISSUE THREAD

**Issue by MarianKrkosMews** [microsoft/playwright#27795]
Method ILocatorAssertions.ToHaveAttributeAsync() should be extended, so it supports case insensitive assertions. In many cases, we don't care about upper vs lower case characters and we either have to use Regex or go for string.Compare() method that allows case insensitive comparison, but of course no waiting.

As for Regex, it's strong tool but in most cases, we're using Enums for test data and Enums don't allow special characters needed for regular expressions.

If extended, it would also add consistency into your assertion methods, because it would line the method, and its options parameter, with ToHaveTextAsync() and ToContainTextAsync() methods that also compare text and support case insensitive comparison.

**Comment by dgozman** [comment]
Indeed, we can add `ignoreCase` option similar to `ToHaveText` and other assertions.
