### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ahmednkhan24** [microsoft/playwright#27799]
**Context:**
- Playwright Version: 1.34.3
- Operating System: Windows 11
- Node.js version: 18.13.0
- Visual Studio Code version: 1.77.2
- Playwright for VSCode extension version: 1.0.16
- Browser: Chrome 118.0.5993.89
- Extra: Powershell 5.1.22621.2428

Our Playwright tests grab environment variables at runtime through Node's `process.env` syntax.
For example, we'll get overrides by doing something like this:
```javascript
const appEnv = process.env?.APP_ENV;
const url = `https://${appEnv === 'prod' ? '' : `${appEnv}.`}helloworld.com`;
await page.goto(url);
```
to navigate to our test env or our production environment:
production: https://helloworld.com.
test: https://test.helloworld.com.

I'll set these variables in my Powershell shell by doing something like this:
```powershell
Set-Item -Path Env:APP_ENV -Value "test"
```
and then run my tests by doing
```node
npx playwright test
```

I am looking for a way to pass these custom shell environment variables to the Playwright for VSCode extension. 
When i click the "play" button using the runner, it opens a browser to `https://undefined.helloworld.com`.

This prevents our team from utilizing the test runner extension which we really would like to use.

**Comment by mxschmitt** [comment]
We also recommend .env files, which would make it work out of the box: https://playwright.dev/docs/test-parameterize#env-files

also make sure to update Playwright: https://playwright.dev/docs/best-practices#keep-your-playwright-dependency-up-to-date
