### ISSUE TITLE
[Question] How can I use a slider to change value

### ISSUE THREAD

**Issue by nesrineabdmouleh** [microsoft/playwright#27797]
I have a scenario to filter by price by dragging the bar. Could anyone help me with the logic here as shown in the screenshot below.

![Capture d’écran de 2023-10-25 12-17-23](https://github.com/microsoft/playwright/assets/24647495/231a7f2f-33eb-4efb-92cc-baeb8fb078bf)

Thank you!

**Comment by StasGrishaevTutu** [comment]
check this one - https://github.com/microsoft/playwright/issues/20032
the main idea is to use `page.mouse.down();` and `page.mouse.move(startPoint.x, startPoint.y);` on your slider element

**Comment by nesrineabdmouleh** [comment]
Thank you for your response! but how can I drag the bar from the end to decrease the max value of the price ?

Please check my code, here i can only increase the price

 ```
    const sliderTrack = await page.locator('.ui-slider-horizontal');
    const sliderOffsetWidth = await sliderTrack.evaluate(el => {
      return el.getBoundingClientRect().width;
    });

    await sliderTrack.hover({force: true, position: {x: 25, y: 0}});
    await page.mouse.down();
    await sliderTrack.hover({force: true, position: {x: sliderOffsetWidth, y: 0}});
    await page.mouse.up();
```

**Comment by StasGrishaevTutu** [comment]
@nesrineabdmouleh
Sorry, I haven’t used these functions myself, so I can’t give you a more precise answer, maybe someone else can :)

**Comment by yury-s** [comment]
You can move it from left to right or from right to left (to decrease), should be mostly the same, something like this should work:

```js
  const box = await page.locator('.ui-slider-horizontal').boundingBox();
  await page.mouse.down(box.x + box.width / 2, box.y + box.height / 2);
  // Move 100px left.
  await page.mouse.move(box.x + box.width / 2 - 100, box.y + box.height / 2, { steps: 10 });
  await page.mouse.up(box.x + box.width / 2 - 100, box.y + box.height / 2);
```
