### ISSUE TITLE
[Feature] Extends actions to custom the OOTB behaviour

### ISSUE THREAD

**Issue by jesusfj710** [microsoft/playwright#27803]
At this moment, I don't see any way to extend the out of the box actions in Playwright. Im our team we would like to custom the click actions to be able to perform some additional waitings (this is something that depends on our particular case).

Now, with [1.39](https://github.com/microsoft/playwright/releases/tag/v1.39.0) we have the ability to extend the expect to be able to create our own ones, but I dont see anything similar with actions.

Is this planned or realy not planned at all?

Our workaround would be a wrapper to use this kind of actions, but its not really needed if we can just extend the actions and pass some optional arguments to meet our needs.

**Comment by yury-s** [comment]
> Is this planned or realy not planned at all?

No plans  for that. You can use POM which implements more complex actions on top of Page API.

> Our workaround would be a wrapper to use this kind of actions, but its not really needed if we can just extend the actions and pass some optional arguments to meet our needs.

This is the recommended way, you can introduce your own helpers in the form of utility functions or page object models.
