### ISSUE TITLE
[BUG] Error: ENOENT: no such file...

### ISSUE THREAD

**Issue by ricsimps** [microsoft/playwright#27806]
### System info
- Playwright Version: the latest
- Operating System: macOS 12.6.9
- Browser: All
- Other info:

**Steps**
- In terminal, run npx playwright test tests/ccm* --ui

**Expected**
The tests in the ccm* spec run in the test runner, like they did the day before.  No changes were made to the spec file, or my system set up.

**Actual**
The test runner launches but the test instantly fails before anything happens.  The error I found is: Error: ENOENT: no such file or directory, open '/var/folders/vn/gqf1jgvx3pz9qfr85h3x1n1c0000gq/T/playwright-transform-cache-503/25/playwrightconfig_2516168da95ec8e27bba4358826f59787125a31a.js'.  I look in my LFS and there is no such file in that location.  There is however a file called:  playwrightconfig_2516168da95ec8e27bba4358826f59787125a31a.map

I have no idea what that file is about.  My test is real simple, I'm just learning about playwright.  It worked yesterday perfectly fine.  I knocked off yesterday and left everything open.  I came back today tried to run it and now have this error.  I tried restarting everything.  Still the same problem.  Is there some way around this?

**Comment by yury-s** [comment]
This is the same as https://github.com/microsoft/playwright/issues/27592 which is fixed in upcoming 1.40. You can already give it a try by installing @next version.

**Comment by ilopezro** [comment]
I was faced with the same issue and a laptop restart did the trick!

**Comment by michal-weglarz** [comment]
I was having the same issue and installing @next version helped me.

**Comment by FezVrasta** [comment]
FYI using `1.45.3` this still happens 🤷‍♂️
