### ISSUE TITLE
[REGRESSION]: Test setup through fixtures won't work anymore

### ISSUE THREAD

**Issue by ibrocodes7** [microsoft/playwright#27800]
**Context:**
- GOOD Playwright Version: 1.24.0
- BAD Playwright Version: 1.39.0
- Operating System: Linux and Mac
- Extra: Node: v18.17.1, NPM: 9.6.7, NVM: 0.38.0

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

Fixtures.ts:
```typescript
import { testSetup } from './test-setup';

import {
loginPage...etc} from 'src/page-object.ts';

let testPage: Page = null;
export const test = base.extend<{
  loginPage: LoginPage;
}>({
  page: async ({ browser }, use) => {
    if (testPage === null) {
      testPage = await browser.newPage();
    }

    await use(testPage);
  },
  loginPage: async ({ page }, use) => {
    await use(new LoginPage(page));
  },

testSetup(test);
export const expect = test.expect;
```

```typescript
export const testSetup = (test) => {
  test.beforeAll(async () => {
    // login & store sessions
  });

  test.beforeEach(async () => {
    // other steps to capture test information for an internal portal
  });
};
```

**Describe the bug**

After upgrading Playwright to latest versions, I've encountered the following issue. In our fixture, we've set up these blocks, but with the latest Playwright versions, it seems that using them is no longer allowed.

The error message I'm getting is: "Error: Playwright Test did not expect test.beforeAll() to be called here. The most common reasons for this error include:

Calling test.beforeAll() in a configuration file.
Calling test.beforeAll() in a file that is imported by the configuration file.
Having two different versions of @playwright/test. This usually happens when one of the dependencies in your package.json depends on @playwright/test."
```[tasklist]
### Tasks
```

EDIT: 

After delving deeper into the issue, I discovered that the error doesn't occur when I omit an import from another file. 

Here's the global-setup code snippet:

```typescript
import { createUsers, createGroups } from './src/global-methods';

async function globalSetup() {
  login();
  saveSession();
  // The following imports are commented out, and the error no longer occurs.
  // createUsers();
  // createGroups();
}

export default globalSetup;
```

global-methods.ts:
```typescript
import from utils;
import statements from src/page-object.ts;

export async function createUsers() {
// steps
}

export async function createGroups() {
// steps
}
```

It appears that the issue has been temporarily resolved by commenting out the import from the 'src/page-object.ts' in global-methods.ts. Can anyone provide some insights to help me better understand what's happening here?

**Comment by yury-s** [comment]
> The error message I'm getting is: "Error: Playwright Test did not expect test.beforeAll() to be called here.

This is triggered by `testSetup(test);` call in your fixtures file. This will only call beforeAll, beforeEach  in the file where it is called and only once, whereas you want them to be called in every file. See more detailed explanation here: https://github.com/microsoft/playwright/issues/27058#issuecomment-1718039082 You need to call `testSetup(test);` in each test file where you need before* hooks. But since you already define custom fixtures, you'd be better off converting those hooks into [automatic fixtures](https://playwright.dev/docs/test-fixtures#automatic-fixtures).

Closing as this was an intentional change in the behavior about a year ago.
