### ISSUE TITLE
[Question]why not migrate to jest？

### ISSUE THREAD

**Issue by roughsoft** [microsoft/playwright#2780]
why not migrate to jest for playwright test infrastructure？
It is easting dog food for playwright+jest.

**Comment by aslushnikov** [comment]
We're experimenting with different approaches to test running, including jest, jest-playwright, and [playwright-runner](https://github.com/microsoft/playwright-runner). This helps us explore the space with an ultimate hope to make life of Playwright users much better.

Stay tuned!

**Comment by roughsoft** [comment]
awesome！
