### ISSUE TITLE
[FEATURE/BUG] codegen fails at capturing precise (x, y) clicks on svg elements

### ISSUE THREAD

**Issue by gasse** [microsoft/playwright#27804]
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 13.2
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Steps**
 - run codegen on the following Miniwob task
```python
from playwright.sync_api import sync_playwright

with sync_playwright() as p:
    browser = p.chromium.launch(headless=False)
    context = browser.new_context() # Pass any options
    page = context.new_page()

    page.goto("https://miniwob.farama.org/demos/miniwob/bisect-angle.html")
    page.get_by_text("START").click()
    
    page.pause()
```
Then press record, and try to solve the task (click in-between the two extreme points)

**Expected**

I would like the click action to be performed and recorded with the precise location of the mouse event.

**Actual**

Codegen captures the event, and then performs and records a click in the middle of the SVG element disregarding the actual click location
```python
page.locator("#svg-grid").click()
```

Ideally, it would be nice if codegen had an option would record the precise (x,y) position of click events whichever the element being clicked on underneath.

**Comment by yury-s** [comment]
Folding this request into https://github.com/microsoft/playwright/issues/21504, please upvote it instead.
