### ISSUE TITLE
[Feature] Expose locators for reuse across different frameworks

### ISSUE THREAD

**Issue by asvny** [microsoft/playwright#27818]
Storybook has a brillant feature called `Interaction tests` where you have `play` function to test the respective story. This is great because you can have a lot of things in a single place instead of switching across windows. Storybook can be used for component docs, explorer, tests etc.., Currently the components can be tested using `Testing library` queries in the browser and can be tested using their test runner (uses playwright under the hood). It works by instrumenting the apis of `testing-library` and `jest` to catch the errors and to report them in the UI. There is a lot of work done here so it can work in the browser (helps while developing) and also command line (useful in CI mode).

- https://storybook.js.org/docs/react/writing-tests/interaction-testing
_Example_
```tsx
export const Submitted: Story = {
  play: async ({ args, canvasElement, step }) => {
    const canvas = within(canvasElement);

    await step('Enter email and password', async () => {
      await userEvent.type(canvas.getByTestId('email'), 'hi@example.com');
      await userEvent.type(canvas.getByTestId('password'), 'supersecret');
    });

    await step('Submit form', async () => {
      await userEvent.click(canvas.getByRole('button'));
    });
  },
};
```

It would be great if we can use `playwright` locators instead of `RTL`. This will reduce the amount of work done in `test-runner` so it works in both browser and command-line

**Comment by yury-s** [comment]
This should be a feature request to Storybook/Testing library that provide the functionality/APIs. Please file in the corresponding repository instead.

**Comment by asvny** [comment]
I believe it is not currently possible because playwright doesn't expose locators from `playwright/core` and that might be the reason why they didn't go with playwright locators. I am opened this issue because I am currently implementing something similar like `storybook/interactions` addon for Ladle https://ladle.dev/.

I strongly believe exposing playwright locators for asserting interactions instead of `RTL` will make it 10x easier.
