### ISSUE TITLE
[Feature] expose shardIndex in TestRunner API

### ISSUE THREAD

**Issue by stephengaudet** [microsoft/playwright#27819]
It is documented how to [generate unique accounts using the workerInfo.workerIndex](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures) that is exposed through the TestRunner API. 

As a test author, I would like to create unique accounts using a concatenation of workerIndex + shardIndex, so that I can generate unique accounts with tests that are run on my workstation using 5 workers and no sharding, as well in a CI/CD context where the test uses 1 worker and N shards. 

To alter the example using workerIndex above:
`const username = 'user_' + workerInfo.workerIndex + '_' + testInfo.shardIndex`

This way, the same fixture will continue generating unique values when the test is run in CI/CD with 1 worker and N shards.

**Comment by yury-s** [comment]
You can already get the shard index from the config:

```js
test.info().config.shard?.current
```
