### ISSUE TITLE
[Question] Converting FrameLocator to Locator

### ISSUE THREAD

**Issue by Coada** [microsoft/playwright#27816]
Hello,

I have a `FrameLocator` which is being passed to my class from a caller. I use this locator to further locate elements inside it. I would now like to get the bounding box of it, but it seems it is only available on `Locator`.

In the [documentation](https://playwright.dev/docs/api/class-framelocator) it says that you can convert a `Locator` to a `FrameLocator`, but how can I do it the other way?
Alternatively, is there a way to call `boundingBox()` on a `FrameLocator` without converting it?

**Comment by yury-s** [comment]
Discussed this in the meeting today. Similar to web APIs for we don't want to allow exiting frame boundaries, only entering subframes. In your use case as a workaround you can pass `Locator` instead and cast it to `FrameLocator` if needed. The documentation link above explains how to do that. We'll probably make the conversion Locator->FrameLocator easier by allowing to call `locator.frameLocator()` without parameters.

**Comment by Coada** [comment]
I see, thanks Yury for the quick response. I will approach my issue then by altering it to favor passing Locators over passing FrameLocators.

Appreciate what you're doing with Playwright!

For additional context of future readers of this - `frameLocator.locator(':scope').boundingBox()` did not work for me here because this assumes that the content inside the frame has a viewport height of 100% which it unfortunately doesn't.
