### ISSUE TITLE
[BUG] Dockerfile.jammy uses old Node version

### ISSUE THREAD

**Issue by borisyordanov** [microsoft/playwright#27812]
### System info
- Playwright Version: [v1.39.0]

### Source code
https://github.com/microsoft/playwright/blob/main/utils/docker/Dockerfile.jammy#L10
- [x] I provided exact source code that allows reproducing the issue locally.

**Expected**

The docker image installs the latest Node LTS (20.9.0) 
**Actual**

The docker image installs an outdated Node version (18.17.0)

**Comment by mxschmitt** [comment]
Node.js 20 was promoted to LTS 2 days ago, the next Playwright release will contain the new updated Node.js LTS version.
