### ISSUE TITLE
[REGRESSION]: "Unknown file extension .ts" when using type:module and a config file with extension `.cjs`

### ISSUE THREAD

**Issue by anomiex** [microsoft/playwright#27827]
**Context:**
- GOOD Playwright Version: 1.34.0-alpha-may-11-2023
- BAD Playwright Version: 1.34.0-alpha-may-12-2023
- Operating System: Linux
- Extra: None

**Code Snippet**

* Unzip the code in this file: [test.zip](https://github.com/microsoft/playwright/files/13183636/test.zip)
* Run `npm install`
* Run `npm run test:cjs`

**Describe the bug**

With an affected version, running the test:cjs script produces
```
> test@1.0.0 test:cjs
> playwright test -c playwright.config.cjs
TypeError: Unknown file extension ".ts" for /tmp/test/tests/example.spec.ts
```

With earlier versions, or with test:mjs, the tests in example.spec.ts are run.

Removing `"type": "module"` from package.json also makes it work. But renaming the test file to example.spec.mts gives the error even without `"type": "module"`.

`example.spec.js` and `example.spec.mjs` are _not_ similarly affected.

**Notes**

The change to `packages/playwright-test/src/util.ts` in 44a934c160460121c6bf16f81ffcd5ffa228113c seems to have somehow been the trigger for this. Removing the `return false` line makes it able to run the test again. For that matter, having it return true for the config file specifically makes it able to run the test again.

A workaround, of course, is to rename the config file to `.js` or `.mjs`. Even a file with only something like `export { default } from './playwright.config.cjs';` works.

**Comment by yury-s** [comment]
Folding this into https://github.com/microsoft/playwright/issues/23662

You should not be using commonjs file in esm package (type: module). It might have worked in the past accidentally but is not a use case we want to support.
