### ISSUE TITLE
[Question]How to set multi baseurl in one project

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#27829]
Hi. I'm using Playwright(nodejs) to write  test cases.
The test project contains 2 websites. 2 sites depend on each other 
Some cases,I should go to A to do something, then go to B to do something to assert the function.
How to set 2 different baseURL in one project？

**Comment by yury-s** [comment]
Playwright only allows to set one baseURL. You can modify it per test via `test.use()`:
```js
test.use({
  baseURL: 'https://playwright.dev'
});
```
but with single test you can have only one base URL. For the second base you'll need to specify full URL explicitly, you can wrap it in a utility function.

**Comment by enriqu3l** [comment]
Thanks for the explanation @yury-s. Besides doing it per file, I also noticed that you can set different urls per project like this:

    {
      name: 'project 1',
      use: {
            ...devices['Desktop Firefox'],
            baseURL: 'https://site1.com'
        },
    },

    {
      name: 'project 2',
      use: {
            ...devices['Desktop Firefox'],
            baseURL: 'https://site2.com'
        },
    },

**Comment by OlegsHanins** [comment]
We have many baseUrl but we have custom fixture what creates new BrowserContext. So instead of built in "page" we have several ours fixtures "pageFoo", "pageBar" etc. It very simple you just need to get idea how to use fixtures. I was going to write an article.
