### ISSUE TITLE
[BUG] timeout is not working in expect.poll.

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27823]
### System info
- Playwright Version: latest versionb
- Operating System: [All]
- Browser: [All]
- Other info:

![image](https://github.com/microsoft/playwright/assets/21674533/f5f5fc5e-bbbc-4bbf-8acc-b08bf6ce6858)

Explicit timeout is not able to overwrite with global timeout. 

Expected state: Ideally expect.poll should wait till 600000 ms instead of 60000.

Expect.poll Method:
```
 async getClusterStatus(idpIPAddress: string, expectedMessage: string) {
        await expect.poll(async () => {
            await this.page.locator("span.ias-icon.ias-icon-reload_refresh_thick").click();
            const text = await this.page
                .locator("div", { has: this.page.locator(`text=${idpIPAddress}`) })
                .locator("div>i").first().getAttribute("title");
            return text;
        }, {
            message: 'Cluster health yet to be turned as GREEN',
            intervals: [1000, 2000, 10000],
            timeout: 600000,
        }).toBe(expectedMessage);
    }
```

**Comment by yury-s** [comment]
You can call [`test.setTimeout()`](https://playwright.dev/docs/api/class-testinfo#test-info-set-timeout) to increase timeout for a particular test if you don't want to override the timeout for all tests.

**Comment by iburahim786** [comment]
@yury-s Okay, now my question is when the user can use expect.poll timeout or when should work?
