### ISSUE TITLE
[Question] Custom error message when fixture timeout exceeded during setup happens

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#27821]
Is there a way to add custom error messages when timeout happens? In my case, for a fixture.

One of the use case is that some connections happen over VPN and it is not turned on at times but a better custom error message would be helpful.

**Comment by yury-s** [comment]
There is no specific timeout for fixtures. Can you pass custom timeout to the connect function?

```js
  chromium.connect('ws://localhost:4444/abc', {timeout: 10_000})
```

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
