### ISSUE TITLE
[BUG] Invisible calls in the network tab of the UI mode

### ISSUE THREAD

**Issue by nam-edi** [microsoft/playwright#27822]
### System info
- Playwright Version: [v1.39]
- Operating System: macOS 14]
- Browser: [Chromium]

**Steps**
- have a class that takes "request" (APIRequestContext) as an argument
- have an asynchronous function in the class that makes a request (post, get, ...)
- in the test file, make a call to this class in a beforeAll, to use the function 
- run the test in UI mode

**Expected**
we see the call in the network tab, and all the other calls in the test

**Actual**
we see the call in the network tab, but all the other calls made in the test do not appear in the tab. If I remove the code from the before and put it in the test, all the calls are visible

**Comment by yury-s** [comment]
I cannot reproduce it with the following code:

```js
import { test, APIRequestContext } from '@playwright/test';

class Wrapper {
  constructor(public request: APIRequestContext) { }
  async sendRequest(url: string) {
    return await this.request.get(url);
  }
}

test.beforeAll(async ({ request }) => {
  const wrapper = new Wrapper(request);
  await wrapper.sendRequest('https://playwright.dev');
});

test('test', async ({ request }) => {
  const wrapper = new Wrapper(request);
  await wrapper.sendRequest('https://playwright.dev');
});
```
Here is [trace.zip](https://github.com/microsoft/playwright/files/13181909/trace.zip), you can see both requests there.

Can you share complete example which we could try locally?

**Comment by nam-edi** [comment]
here's my code:

```
export class Order {
    readonly request: APIRequestContext;
    readonly testInfo: TestInfo;
    readonly dataEnv: Record<string, string>;

    constructor(request: APIRequestContext, testInfo: TestInfo) {
        this.request = request;
        this.testInfo = testInfo;
        this.dataEnv = testInfo.project.use["data"];
    }
    
async postOrder(
        token: string,
        body: Record<string, string>,
        x_api_version = this.dataEnv.x_api_version,
        status = 201
    ) {
        const orderResponse = await this.request.post(`${this.dataEnv.ret}/orders`, {
            headers: {
                Authorization: `Bearer ${token}`,
                "X-API-VERSION": x_api_version,
            },
            data: body,
        });
        expect(orderResponse.status(), "Status code").toBe(status);
        try {
            const order = await orderResponse.json();
            return order;
        } catch (error) {
            return null;
        }
    }
    ```
    
    and
    
    ```
    test.beforeAll(async ({ request }, testInfo) => {
        e1 = testInfo.project.use["data"].retailers.e1;
        token = await new Token(request, testInfo).ret(e1);
        orderApi = new Order(request, testInfo);
        badToken = testInfo.project.use["data"].badToken;
    });

    test("Test - 201 @smoke", async () => {
        const body = getBody();
        body.storeId = e1.stores.m2.externalStoreId;

        await orderApi.postOrder(token, body, x_api_version);
        const response = await orderApi.getOrder(token, body.orderId);
        })
        
      ```
      
      I have a post in Token and one in orderApi, if I declare orderApi in my test, everything works, if I do it as above, I only have the token call in the network tab.

**Comment by yury-s** [comment]
I see, the problem is that [`request`](https://playwright.dev/docs/api/class-fixtures#fixtures-request) is a test scoped fixture  (as opposed to [worker-scoped](https://playwright.dev/docs/test-fixtures#worker-scoped-fixtures)) and it is destroyed after `beforeAll` finishes. We should probably make Playwright throw when the request used after it has been disposed. If you want to use the same instance of the APIRequestContext in beforeAll and in the tests you can create them manually or create your own worker-scoped fixture that will dispose it after all tests finished. Would that work?

```ts
import { test, APIRequestContext, request } from '@playwright/test';

class Wrapper {
  constructor(public request: APIRequestContext) { }
  async sendRequest(url: string) {
    return await this.request.get(url);
  }
}

let wrapper;
let globalRequest;
test.beforeAll(async ({ }) => {
  globalRequest = await request.newContext();
  wrapper = new Wrapper(globalRequest);
  await wrapper.sendRequest('https://playwright.dev');
});

test('test', async ({ request, page }) => {
  await wrapper.sendRequest('https://playwright.dev');
});
```

**Comment by pedchenkoroman** [comment]
Hi Yury,

I'm encountering the same issue where my API requests from a fixture are invisible when using the { auto: true } option. In my team, we use these types of fixtures for polling. Essentially, under the hood, the fixture relies on expect.poll to retrieve data before proceeding. As you can probably guess, it doesn’t return anything, which is why it’s set to auto.

Any thoughts on this?
