### ISSUE TITLE
[Feature] FFMPEG only uses 1 CPU core

### ISSUE THREAD

**Issue by martinalderson** [microsoft/playwright#27836]
Let us know what functionality you'd like to see in Playwright and what your use case is.

It seems that FFMPEG only uses 1 cpu core for exporting videos. I can't actually see how playwright dotnet uses threads, but I do see this in the playwright js code (if it leverages that?):

    const args = `-loglevel error -f image2pipe -avioflags direct -fpsprobesize 0 -probesize 32 -analyzeduration 0 -c:v mjpeg -i - -y -an -r ${fps} -c:v vp8 -qmin 0 -qmax 50 -crf 8 -deadline realtime -speed 8 -b:v 1M -threads 1 -vf pad=${w}:${h}:0:0:gray,crop=${w}:${h}:0:0`.split(' ');

It seems this is set due to the comment above to not overbook the cpu, but this is a poor solution imo. It could use the `nice `command on linux at least to set a lower cpu priority than everything else (for example). 

Anyway, it would be nice to at least be able to configure this easily in dotnet. We have servers with many cpu cores and the ffmpeg process takes a significant amount of time; which could be massively lower if it used more cores. 

Do you think others might benefit from this as well?

Yes, it would allow anyone using ffmpeg with multiple cpu cores to have dramatically faster video recording.

**Comment by yury-s** [comment]
You can run playwright with more workers in parallel, that way you can better utilize available cores by running more playwright tests and browsers instead of optimizing just ffmpeg performance.

**Comment by martinalderson** [comment]
@yury-s the issue is we want to show our users the test video as fast as possible. The ffmpeg stage takes a long time. It's not a case of 'use all available cores to run more tests' its 'optimize the speed of test runs'.
