### ISSUE TITLE
[Feature] Update base snapshot in UI Mode

### ISSUE THREAD

**Issue by azaeng04** [microsoft/playwright#27833]
Perhaps there is a feature request for this, but it would be great to be able to update the base snapshot in UI Mode.

**Comment by StasGrishaevTutu** [comment]
looks like https://github.com/microsoft/playwright/issues/24310
but PR is umerged and closed there.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/24310, please upvote it instead.
