### ISSUE TITLE
[Feature] Allow mocking of module imports in component testing

### ISSUE THREAD

**Issue by tusharnaresh** [microsoft/playwright#27830]
Feature Request
While writing component tests for  components in a microfrontend architecture, there can be cases in which there is a requirement to mock methods that are imported in the component which is being tested. Few example of this use case can be as follows:

- The component being tested gets the data from indexed db through wrapper methods which are imported in the component.  Instead of initializing and populating the indexed db for each component test, it will be much easier if we are able to mock the imported method in the component to get the desired data.
<img width="911" alt="Playwright mock" src="https://github.com/microsoft/playwright/assets/89134825/cc462ed2-8f2b-402f-a5df-615be2231485">

-  There can be a service which is used across microfrontends that returns data asynchronously. Internally it may or may not make a network request depending on the data being requested. In this scenario, it will be helpful if we are able to mock the imported methods of the service in the component being tested.
Do you think others might benefit from this as well? Yes

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/14572, please upvote that one instead.

**Comment by klarstrup** [comment]
@yury-s can we unfold it from #14572 as of https://github.com/microsoft/playwright/issues/14572#issuecomment-2515577263 ?
