### ISSUE TITLE
[Feature] Migrate to GitHub Form Templates for issue creation

### ISSUE THREAD

**Issue by ludovicobesana** [microsoft/playwright#27847]
**Is your feature request related to a problem? Please describe.**
Yes, the current classic GitHub issue templates can be a bit limiting. They rely on users editing Markdown directly, which can sometimes result in inconsistent or incomplete issue submissions.

I suggest migrating to [GitHub Form Templates](https://leonardomontini.dev/github-issue-form-template/). They offer a more interactive way for users to submit issues, using structured fields and dropdowns, ensuring more consistency and completeness in the issues reported.

**Comment by pavelfeldman** [comment]
We like the flexibility of markdown, it is the opposite of limiting!

**Comment by ludovicobesana** [comment]
I appreciate the swift feedback, @pavelfeldman. I understand the flexibility that Markdown provides. However, in my opinion, the structured approach of GitHub Form Templates can help in achieving a more uniform and detailed submission of issues, making it easier for maintainers to understand and act upon them. 
I appreciate the swift feedback, Pavel. I understand the flexibility that Markdown provides. However, in my opinion, the structured approach of GitHub Form Templates can help in achieving a more uniform and detailed submission of issues, making it easier for maintainers to understand and act upon them.

**Comment by pavelfeldman** [comment]
> However, in my opinion, the structured approach of GitHub Form Templates can help in achieving a more uniform and detailed submission of issues, making it easier for maintainers to understand and act upon them.

We arrived at a state we are after experimenting with many things, including templates. As maintainers, we prefer it the way it settled.
