### ISSUE TITLE
[BUG] The playwright recorder double clicks (on single click) when interacting with a BabylonJS canvas. 

### ISSUE THREAD

**Issue by AnshPatel15** [microsoft/playwright#27856]
### System info
- Playwright Version: [1.38.1]
- Operating System: [Windows 10, macOS 14.0]
- Browser: [Chromium, Firefox]
- Other info:

### Source code

- [❌] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
module.exports = defineConfig({
  testDir: "./tests",
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: "html",
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
  },
  timeout: 100000,

  /* Configure projects for major browsers */
  projects: [
    {
      name: "Draw Tests",
      use: { ...devices["Desktop Chrome"] },
      //testMatch : 'test data/draw',
      retries: 2,
      testDir: "src/tests/draw",
    },
    {
      name: "Edit Tests",
      use: { ...devices["Desktop Chrome"] },

      retries: 2,
      testDir: "src/tests/edit",
    },
    {
      name: "Indicator Tests",
      use: { ...devices["Desktop Chrome"] },

      retries: 2,
      testDir: "src/tests/indicators",
    },
  ],
```

**Steps to recreate the issue*

- Go to "https://3d.nih.gov/", My application isn't available to the public yet so I can't share my app. But if you need access, I could ask for access to one user for bug testing and fixing purposes. The provided website is a public website I found that also uses babylonJS among a few others where this issue was replicated similarly to my application. 

- interact with canvas, in this case, interact with the virus, it has two mouse events, click and drag and double click to the default position. 

- when recording using Playwright, the canvas takes a single canvas click event as two canvas click events. 2 each for pointer up and pointer down.

- I shall attach a video explaining the issue in my application as well.

Video: https://www.loom.com/share/f559f233b6544e5abd944bf5667db9e8

**Expected**

The expected behaviour is that when recording on a babylonJS canvas, Playwright should not attach extra click events so that I can reliably record test cases. Right now I'm having to add a debounce to my local repo and record tests in localhost and then run those on the deployed app, adding complexity and the need to add a debounce to every single mouse event is not ideal. 

**Actual**

The interaction with the application should match with and without the recorder being turned on. These extra mouse events should not be added to the application while recording.

**Comment by pavelfeldman** [comment]
We would only be able to act on this issue if it is reduced to a minimal repro that we can run locally. I'll close this issue as non-actionable, but please follow up with something we can clone and try locally.

**Comment by AnshPatel15** [comment]
it is reproducable locally, watch my video. You just have to start recording on any babylonjs canvas and you will see what im talking about. since it is a recorder specific issue there is no code to provide in this instance.

**Comment by AnshPatel15** [comment]
please ask me if theres something missing in my above issue submission, to my knowledge you should be able to reproduce this locally quite easily by following the steps above. Just open the website and interact with the babylon canvas, then open it on playwright recorder and see the difference. Playwright is adding unnecessary mouse events that hinder the recording process.

**Comment by AnshPatel15** [comment]
shall I provide another video that goes through the steps to reproduce this bug??
