### ISSUE TITLE
[Feature] Possibility to add custom HTML code to the report (e.g. with annotations)

### ISSUE THREAD

**Issue by Nirostar** [microsoft/playwright#27857]
It would be really nice to have the possibility to inject custom HTML content into the report e.g. links, images, issue tracker widgets etc.. This doesn't seem too hard to do and would open up a lot of possibilities to customize the report.

**Comment by pavelfeldman** [comment]
You can add links and images using the attachments and annotations (`test.attach`). Embedding iframe widgets is out of scope of the Playwright report.

**Comment by Nirostar** [comment]
Thanks! I missed that feature.
