### ISSUE TITLE
[Question]: My Testes are not running Parallelly In CI/CD pipeline, but its running fine locally.

### ISSUE THREAD

**Issue by biswasritu6** [microsoft/playwright#27852]
**I have a "test" folder and multiple test files inside it.**
EG: Refer photo 1.
![Photo1](https://github.com/microsoft/playwright/assets/86822634/1d465d9b-0b55-4aac-8603-d60b35fd1104)

And my package.json looks like Photo 2,
![Screenshot (324)](https://github.com/microsoft/playwright/assets/86822634/607ca765-10df-4d4b-871b-5b197a9b7d81)

 where I have specified all the test spec files name with environment , region etc and all the configuration has been done inside playwright.config file and i am running all the apps in terminal using command - npm run all_apps_prod .
 while running locally all the apps are running parallelly and sequiencially using 4 workers, but while running in CI/CD its not running parallelly and some apps are failing, and taking more time as usual. 
 even after specifying the workers in command its not working and some apps are failing in pipeline. but on single run those are passing.
 can anyone guide me how we can run all the apps parallelly and smoothly in Pipeline? or how we can divide our test cases in 2 different folders and how we can run both the folders at the same time using cmd commands parallelly?

**Comment by pavelfeldman** [comment]
Try asking this question on discord. If your tests run fine locally and fail on CI, it suggests that the tests are racy. Refer to the best practices of using web assertions to prevent flakiness.
