### ISSUE TITLE
[Feature] Support nested selectors for React locator

### ISSUE THREAD

**Issue by delijah** [microsoft/playwright#27854]
At the moment it is not possible to use nested selectors when using React locator. Example:

Now
```await page.locator('_react=BookItem').click();```

After
```await page.locator('_react=ColumnTwo BookItem').click();```

Why would this be useful? Sometimes we use the same component several times on the same page. In order to make it easier to find the desired component it would be great, to be able to use nested selectors (hope this is the right term).

Do you think others might benefit from this as well?
Definetly

I've tried to find the related code in your github repo, to see if i could create a PR, but failed :)

**Comment by pavelfeldman** [comment]
Did you try `await page.locator('_react=ColumnTwo').locator('_react=BookItem').click();` ?

**Comment by delijah** [comment]
Aaaah. Yeah we assume that would work 🤔 Thanks a lot for the input 👍 It's just a bit much of boilerplate if we want to select like 6 different components. Separating them by name would be way easier and people are already used to it by css selectors 🤔

**Comment by pavelfeldman** [comment]
That's all I can offer, sorry!
