### ISSUE TITLE
[Feature] Add possibility to use default expects inside the custom matchers

### ISSUE THREAD

**Issue by tsusstar** [microsoft/playwright#27862]
Hello.
I'm trying to extend the default matchers to use them with my components.

For example, I have my custom `Table extends BaseComponent` component and to use the `expect` I need to write this:
`await expect(table.locator).toBeVisible()`
I'm trying to figure out how to extend the toBeVisible() matcher to use it like this:
`await expect(table).toBeVisible()`

It would be great to have something like this:
```
export const expect = baseExpect.extend({
  async toBeVisible(component: BaseComponent | Locator, timeout = WaitTimeout.MS_15000) {
   const locator = component instanceof BaseComponent ? component.locator : component

   // somehow call the default toBeVisible() and store the result as a boolean in the isVisible variable

   return {
     pass: isVisible,
     message: () => (isVisible ? 'Element is visible.' : 'Expected the element to be visible, but it is not.'),
   }
 },
})
```
Is this even possible?

Thanks in advance,
Taras Sus

**Comment by pavelfeldman** [comment]
That's documented here: https://playwright.dev/docs/test-configuration#add-custom-matchers-using-expectextend
