### ISSUE TITLE
[Feature] docs for how to use docker container

### ISSUE THREAD

**Issue by rayjlinden** [microsoft/playwright#27869]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I want to use playwright "outside" of our web repo to do end ti end testing.  Rather than setting up a node like repo to run "nix playwright" I wanted to use the docker container.

However, I'm not sure if I can do that.  Indeed, I can't find and documentation around how to use the docker container.  Can better docs on how to use the docker container be added?

**Comment by pavelfeldman** [comment]
Playwright is a just a program that can run on Linux inside the docker container. You might need to learn more about the docker itself to fulfill your goals.
