### ISSUE TITLE
[BUG] Types no longer exported from @playwright/test

### ISSUE THREAD

**Issue by ericmatthys** [microsoft/playwright#27860]
### System info
- Playwright Version: 1.39.0
- Operating System: All
- Browser: All
- Other info:

### Source code

```tsx
import type { TestInfo } from '@playwright/test';
```

```tsx
import type { PlaywrightTestConfig } from '@playwright/test';
```

**Expected**

With 1.37.1, these imports are valid.

**Actual**

`TS2614: Module  "@playwright/test"  has no exported member  TestInfo .`
`TS2614: Module  "@playwright/test"  has no exported member  PlaywrightTestConfig .`

I didn't see anything in the release notes that indicates that this is an expected breaking change.

**Comment by pavelfeldman** [comment]
I can't repro this. Please follow the BUG template to provide exact steps I can follow to reproduce this, starting with `npm init playwright@latest`

**Comment by alexkuc** [comment]
@ericmatthys Check your local paths. Playwright have internally renamed some packages (#26946) and if you have the same folders/files as Playwright's, TypeScript might erroneously resolve those against your _local_ packages instead of node_module's ones.

**Comment by alexkuc** [comment]
@ericmatthys Check your local paths. Playwright have internally renamed some packages (#26946) and if you have the same folders/files as Playwright's, TypeScript might erroneously resolve those against your _local_ packages instead of node_module's ones.

Edit: 

Simple way to reproduce the issue:

- navigate to `node_modules/@playwright/test/index.d.ts`
- control/command click on the namespaces i.e. `'playwright/test'`:

```typescript
export * from 'playwright/test';
export { default } from 'playwright/test';
```

In my case, I actually have a _local_ file `playwright/test.ts` and when I click on those namespaces (red arrows), my IDE opens my _local_ file, not Playwright's types

**Comment by ericmatthys** [comment]
It seems to be an issue with how pnpm is installing dependencies. Adding `playwright` as an explicit dependency as well as `@playwright/test` fixes the TS errors, despite `playwright` already being a dependency of `@playwright/test`. I'll take a closer look at what is happening there.

**Comment by ericmatthys** [comment]
More context: https://github.com/orgs/pnpm/discussions/5535

Adding `public-hoist-pattern[]=playwright` to `.npmrc` is another way of fixing the issue

**Comment by alexkuc** [comment]
My solution to this is to use [paths](https://www.typescriptlang.org/tsconfig#paths) in `tsconfig.json`:

```json
"paths": {
    "playwright/test": ["node_modules/playwright/test"]
}
```
since I am not using pnpm

**Comment by garrappachc** [comment]
> More context: https://github.com/orgs/pnpm/discussions/5535
> 
> Adding `public-hoist-pattern[]=playwright` to `.npmrc` is another way of fixing the issue

Stumbled upon this issue recently, I'm using pnpm. For me, the fix was to actually put
```
public-hoist-pattern[]=playwright*
```
in the .npmrc. The `playwright-core` package needs to be present as well.
