### ISSUE TITLE
[Feature] Having retry cycles at suite level and repopulating data between these runs.

### ISSUE THREAD

**Issue by shraysharmaphrase** [microsoft/playwright#27876]
Hey guys, i love how playwright can handle retries and reduce flakiness, it brings immense value to us.
As per my understanding when a test fails the subsequent tests are not run rather a new worker process is started where the failed test is run and if it passes, we run the next ones.

yes if its serial then the next ones will be skipped. 

But, the issue is that , we have a DB script which inserts test data into the DB. which can be called using a shell script that is not a problem.
The problem is :
1. The retries happen at test level and not at suite level . so, assuming two test files are running and one has a failing test.
there is a  before each statement with the shell script to repopulate the data before the retry. but while it tries to repopulate the data, the other test file is still using the data from DB and there are chances that it tries to fetch data while the repopulation of data is going on and fails as the the data might not be there.

what would solve this issue?
if we could rerun the  failing tests after the whole pack is done. 

2. we define the repopulation of script at test level using before each.it would be nice to have it at a suite level and integrate it with the above problem where we gather all the fail tests , run the repopulation of data and then run the failed tests.

maybe i missed something but i could not find something around these lines.

i did find a resource from butch https://playwrightsolutions.com/whats-the-easiest-way-to-only-re-run-failures-after-the-playwright-test-is-finished/

but it does not integrate the retry results with the actual report from playwright. 

**Note : this would apply only when we are using more than one worker.**

**Comment by pavelfeldman** [comment]
>  but while it tries to repopulate the data, the other test file is still using the data from DB and there are chances that it tries to fetch data while the repopulation of data is going on and fails as the the data might not be there.

This is where the actual problem is - you can't run concurrent tests against the same data set in different workers, you should isolate the data by worker. Use the workerIndex when running your shell script to populate as many database instances as your have workers. You can do that from the [worker fixtures](https://playwright.dev/docs/next/test-fixtures#worker-scoped-fixtures) as well.
