### ISSUE TITLE
[BUG] TestCase.location incorrect/different when merging reports

### ISSUE THREAD

**Issue by swissspidy** [microsoft/playwright#27877]
### System info
- Playwright Version: 1.39.0
- Operating System: macOS 14.1
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './specs',
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('Run test', async ({ page }) => {
  // Do nothing
});
```

**Test reporter**
```ts
class CustomReporter implements Reporter {
	onTestEnd( test: TestCase, result: TestResult ) {
		console.log( 'onTestEnd', test.location.file);
	}
}
```

**Steps**

My project is in `/full/path/to/my/project` and specs are in `/full/path/to/my/project/specs`

- Run tests with `--reporter path/to/custom-reporter.ts`
- Get console output such as `onTestEnd /full/path/to/my/project/specs/frontend.spec.ts`
- Run tests with `--shard=1/2 --reporter=blob` followed by `npx playwright merge-reports --reporter path/to/custom-reporter.ts ./blob-report`
- Get console output such as `onTestEnd /full/path/to/my/project/frontend.spec.ts`

**Expected**

I'd expect `test.location.file` to be the same when running tests normally and when merging reports.

**Actual**

The `/specs` path segment is missing when merging reports

**Comment by yury-s** [comment]
Currently, blob reports preserves test name relative to `config.testsDir` and when you created report for `/full/path/to/my/project/specs/foo/frontend.spec.ts` and later cal `merge-reports` in `/merge/dir/cwd`, the test path will be resolved relative to that directory to`/merge/dir/cwd/foo/frontend.spec.ts`.

Can you please clarify, what is your expectation regarding the location in such scenario?

**Comment by swissspidy** [comment]
Ah, that's good to know! Is that documented somewhere and I just missed it?

It's definitely counter-intuitive as the test path won't be a relative path but a "made up" path that doesn't actually exist.

I expected the file location to not change and to be the actual location of the file on disk, if that makes sense.

**Comment by yury-s** [comment]
The rationale for resolving it when running `merge-rerports` command is that it may be running in a completely different directory and the original directory with the tests may not even exist on that machine, also original paths won't make sense when merging on an OS different from where blob report was produced.
