### ISSUE TITLE
We cant go to our page with using our baseurl [BUG]

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#27874]
### System info
Playwright Version: [v1.36.0]
Operating System: [Macos,Linux,Windows]
Browser: [Chromium(v117.0.5938.92)]

We set our baseurl like this : https://devapp163.aka.sm/engage
and we want to go this page : https://devapp163.aka.sm/engage/web
so in test we use this code : await page.goto("/web") but in this way we cant go to our page.What did we do wrong ? Thanks for your supports..

**Comment by lucasdonato** [comment]
I also have the same problem, it seems that when the baseUrl has / the page.goto does not work as expected to remove what is before the /

**Comment by pavelfeldman** [comment]
You can learn how URLs are resolved relative to the base URLs in the URL spec: https://developer.mozilla.org/en-US/docs/Web/API/URL#usage_notes
