### ISSUE TITLE
How to test mobile devices in Firefox?

### ISSUE THREAD

**Issue by Pooort** [microsoft/playwright#2787]
When I'm trying to use mobile device with Firefox I get:

`Error: options.isMobile is not supported in Firefox`

How can I test mobile devices in Firefox?

Thanks.

**Comment by pavelfeldman** [comment]
Could you share more about your user story? 

Playwright expects you to match the mobile device to the browser engine atm. You would pick WebKit for iOS devices and Chromium for Android devices most of the time.

Firefox + isMobile implies you'd like to test Firefox for Android that is less than 0.5% of the users, is that your intention?

**Comment by Pooort** [comment]
Thanks for info, @pavelfeldman.
