### ISSUE TITLE
Locator returns element, but clicking or asserting fails.

### ISSUE THREAD

**Issue by gvocale** [microsoft/playwright#27889]
I have two buttons with text `Edit` on a page. I am using Playwright Python.

Why does this work:
```py
(Pdb) self.page.get_by_role("button", name="Edit").locator('nth=2')
<Locator frame=<Frame name= url='http://frontend:3000'> selector='internal:role=button[name="Edit"i] >> nth=2'>
```

While clicking `.click()` or asserting `expect(...).to_be_visible()` doesn't work?
```py
(Pdb) self.page.get_by_role("button", name="Edit").locator('nth=2').click()
*** playwright._impl._api_types.TimeoutError: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for get_by_role("button", name="Edit").nth(2)
============================================================
(Pdb)
```
What am I doing wrong?

**Comment by pavelfeldman** [comment]
Because the element is not in dom or is not visible. Your first expression does nothing - it creates a locator. Your second expression uses this locator to check actionability and click.

**Comment by gvocale** [comment]
I see.. so `<Locator...` doesn't mean it found anything in the DOM?

**Comment by gvocale** [comment]
Say I have the following DOM element:
```html
<button>hello</button>
```

Doing `page.get_by_role` will return me a `<Locator/>`, which doesn't necessarily mean the locator has located an actual element
```py
(Pbd) page.get_by_role("button", name="hello")
<Locator frame=<Frame name= url='http://localhost'> selector='internal:role=button[name="hello"i]'>

(Pbd) page.get_by_role("button", name="not existing")
<Locator frame=<Frame name= url='http://localhost'> selector='internal:role=button[name="not existing"i]'>
```

I found this behavior a bit confusing. If I was using testing library, I'd get an error if the locator can't find an element. What's a good way then to see if the locator had found an element?
