### ISSUE TITLE
[Question] Waiting for second Websocket message?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#27885]
So I took a look at https://github.com/microsoft/playwright/issues/22417 and it was very helpful at my getting my Playwright websocket test going. However I am running into a slight issue. First of all here is (basically) what my code looks like:

```
   let value;
    page.on("websocket", (ws) => {
      ws.on("framereceived", (event) => (value = event.payload));
    });
    const webSocketPromise = page.waitForEvent("websocket");
    await page.evaluate(
      `var webSocket = new WebSocket('wss://websocket.url.net/widgets')`,
    );
    const webSocket = await webSocketPromise;
    const waitForIncomingMessage = webSocket.waitForEvent("framereceived", { predicate: ev => ev.payload.length < 500 });
    /* API Request that triggers Websocket message (again) */
    await waitForIncomingMessage;
    const parsedVal = JSON.parse(value);
```

So the problem I am running into is essentially when the websocket is created an "initial" message is sent, it contains a large amount of data only a portion of which I am looking at, more importantly this test is making sure that the API request I do causes another message (Which contains only a portion of Updated data that I want to check)

Initially I thought "Ok i'll do the `webSocket.waitForEvent("framereceived")` AFTER the request is made and create the promise before the request".

However what I found is that the payload value is still from the first initial websocket message. The only way I could figure out a good wait was to using the hacky `webSocket.waitForEvent` above (Since the first payload message always has a length over 500 and the second one is much smaller since it's only a fraction of the data)

Is there a better way to do this? I thought by doing a `waitForEvent` after the request was made would make it work, but I figure the timing is probably not synched so the `waitForEvent` is still triggering off the delayed message from making the Websocket.

Could I make two waitForEvents perhaps? So it only ever gets the second message after the API request is made? (Apologies if this question is confusing i'll clarify anything that doesn't make sense)

One alternative is using a predicate on the waitForEvent (which i've done above) however I can't think of a good predicate function that would work for my situation. Since I assume the payload is a string correct? I would need to do some pretty complicated string manipulation to check (Since the correct "object" is technically in both payloads, but I only need the second "updated" one)

**Comment by pavelfeldman** [comment]
You should do something like this:

```js
const frames = [];
page.on("websocket", (ws) => {
  ws.on("framereceived", (event) => frames.push(event.payload));
});
...
await expect.poll(() => frames.length).toBeGreaterThan(1);
const secondMessage = ... frames[1];
```

then you won't miss any frames.

**Comment by msmith1114** [comment]
Wow I don't know why I didn't think about that but this makes a lot more sense. I honestly always forget about the expect.poll() function.
I guess I could also put the something like `frames.length >1` in the waitForEvent call maybe as well would perhaps be an alternative way? (not saying it's better, im more just curious if that would work)
