### ISSUE TITLE
[BUG] Running browser instance with additional argument like test-third-party-cookie-phaseout or test-third-party-cookie-phaseout does not change it state

### ISSUE THREAD

**Issue by OlegRomaniuck** [microsoft/playwright#27886]
### System info
- Playwright Version: [v1.38.1]
- Operating System: [ macOS 12.6]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

**Config file**

```js
// playwright.config.ts
const { chromium } = require('@playwright/test');
const context = await chromium.launchPersistentContext('', {
            viewport: { width: 1280, height: 720 },
            headless: false,
            args: [
                '--test-third-party-cookie-phaseout',
            ],
        });
const page = await context.newPage();
await page.goto('chrome://flags', { timeout: 60000 });
```

**Steps**
- Launch a browser instance with args and navigate to the URL ( chrome://flags). I tried using different arguments, here is a list of the arguments I tried, one at a time of course: -enabled--test- Third-party-cookie-phaseout, --test- Third-party-cookie-phaseout=true, --test - third-party-cookie-phaseout=enable, --test-third-party-cookie-phaseout=enabled].
-  Find a flag 'test-third-party-cookie-phaseout' in web page.
- The same also for flag 'third-party-storage-partitioning'

**Expected**

[Should have state enabled]

**Actual**

[Display disabled every time]

**Comment by pavelfeldman** [comment]
Running browsers with extra arguments comes with no guarantee and at your own risk.

**Comment by Slessi** [comment]
@pavelfeldman I understand that if the browser doesn't work as a result of an argument, it would be our own risk, but shouldn't playwright guarantee that the flag is at least sent to the browser?

I too am trying to use `--test-third-party-cookie-phaseout`, and like the OP, it doesn't work. By that I mean, chromium does not seem to receive the flag at all.

When checking logs from:

```
DEBUG=pw:test:protocol npx playwright test
```

I see many commands to launch chromium browsers, but only one has the flag I specified. That does not seem right.
