### ISSUE TITLE
[BUG] Running a single test file runs all test files that contain that file name

### ISSUE THREAD

**Issue by nemanjajeremic** [microsoft/playwright#27882]
### System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11]
- Browser: [All]
- Other info:

### Source code

Easily reproducible on any repo

**Steps**

1. Create a test file with a name **example.spec.ts**
2. Create another test file containing the file name of the first one (eg. backend-**example.spec.ts**)
3. Run `npx playwright test example.spec.ts`

**Expected**

Test file **example.spec.ts** runs.

**Actual**

Both test files are run as they contain the same string (**example.spec.ts**).

This is easily reproducible in any scenario.

**Comment by pavelfeldman** [comment]
That is working as intended, you can use path separator to limit it to example.spec.ts.
