### ISSUE TITLE
[Feature] Add support for DeviceOrientationEvent in dispatchEvent

### ISSUE THREAD

**Issue by mattiasw** [microsoft/playwright#27887]
I'm building a web app that uses device orientation events. For testing, it would be handy to be able to dispatch this event type to see that the app reacts as it should.

It didn't look like such a big change so I tried to add the new event type to `dispatchEvent` and `eventType` in `packages/playwright-core/src/server/injected/injectedScript.ts` but when I try it out in my app's tests it gives this error:

```
locator.dispatchEvent: ReferenceError: DeviceOrientationEvent is not defined
    at InjectedScript.dispatchEvent (<anonymous>:5484:9)
    at eval (eval at eval (:4712:24), <anonymous>:2:22)
    at eval (eval at evaluate (:208:30), <anonymous>:18:20)
    at UtilityScript.evaluate (<anonymous>:210:17)
    at UtilityScript.<anonymous> (<anonymous>:1:44)
```

Using this line:

```
await this.page.locator('html').dispatchEvent('deviceorientation', {alpha: 10, beta: 20});
```

It does work fine in the unit tests I wrote, both Chromium and Firefox (in `tests/page/page-dispatchevent.spec.ts`), only not when I try to use the updated code in my own tests.

I'm running this only in Chromium right now, on Ubuntu Linux. I noticed that Firefox and Webkit has some extra code regarding events but I haven't found that for Chromium.

I would be willing to work on this if I could get some pointers on what I'm missing.

**Comment by pavelfeldman** [comment]
So you modified Playwright code and now it throws a reference error :smile: ? Could you provide your expectations and actual behavior on unmodified Playwright for us to be able to look into it?

**Comment by mattiasw** [comment]
It's a regular feature request. As the title and the first paragraph says I would like to be able to dispatch a DeviceOrientationEvent. The current behavior on unmodified Playwright does not pass on DeviceOrientationEvent-specific properties to the event handler.

The rest of the post was just a description of my own futile attempt to try to make a PR. I was thinking it would be as small a change as this one for WheelEvent: https://github.com/microsoft/playwright/pull/15593

But then I got that DeviceOrientationEvent is not defined in the context it's used so my assumption of simplicity was obviously wrong.

**Comment by pavelfeldman** [comment]
Knowing which properties you need to include in a dispatched even and an example of a generic error with these properties not working would help.
