### ISSUE TITLE
[BUG]page.screenshot: Timeout 30000ms exceeded.

### ISSUE THREAD

**Issue by hashimoto-AJ** [microsoft/playwright#27893]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [ Ubuntu22(docker) on the Windws11]
- Browser: [Chromium]
- Node.js: [v18.18.1]
- npm: [npm]
- Docker version: 
~~~
Client:
 Cloud integration: v1.0.35-desktop+001
 Version:           24.0.5
 API version:       1.43
 Go version:        go1.20.6
 Git commit:        ced0996
 Built:             Fri Jul 21 20:36:24 2023
 OS/Arch:           windows/amd64
 Context:           default

Server: Docker Desktop 4.22.1 (118664)
 Engine:
  Version:          24.0.5
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.6
  Git commit:       a61e2b4
  Built:            Fri Jul 21 20:35:45 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.21
  GitCommit:        3dce8eb055cbb6872793272b4f20ed16117344f8
 runc:
  Version:          1.1.7
  GitCommit:        v1.1.7-0-g860f061
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
~~~
### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

~~~ js
// screenshot.js
const { chromium } = require('playwright');
const URL = 'https://www.fmnorth.co.jp';
(async () => {
  const browser = await chromium.launch({ headless: true});
  const context = await browser.newContext();
  const page = await context.newPage();
  await page.goto(URL,{waitUntil: "load"});
  await page.screenshot({path: 'screenshot.png', fullPage: true});
  await context.close();
  await browser.close();
})();
~~~

**Steps**
- node screenshot.js

**Expected**

Creating a screenshot file

**Actual**

~~~
$ node screenshot.js

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.screenshot: Timeout 30000ms exceeded.
Call log:
  - taking page screenshot

    at /{My Project path}/screenshot.js:8:14

Node.js v18.18.1
~~~

There are problems on a particular site, and other sites are no problem:
ex) `google.com`, `amazon.com` etc.

**Comment by dgozman** [comment]
This page contains a 85000-pixels wide element, and so `document.body.scrollWidth` is more than 73000.

```html
<div class="slick-track" style="opacity: 1; width: 85000px; transform: translate3d(-11117px, 0px, 0px);" role="listbox">
...
</div>
```

When Playwright calculates the size for the `fullPage` screenshot (for the record, this logic was introduced in #164 and stayed intact for four years so far), it tries to take a very large screenshot and that takes a lot of time.

**Comment by hashimoto-AJ** [comment]
Setting the timeout value to `page.screenshot()`,the problem was resolved. thank you!!

**Comment by ETreskovskis** [comment]
@hashimoto-AJ by setting the timeout value of `page.screenshot()` you have increased the timeout or disabled it by setting to `0`?
