### ISSUE TITLE
[BUG] Playwright UI Mode screen doesn't show test steps and other details during test case run

### ISSUE THREAD

**Issue by vipinphogat91** [microsoft/playwright#27894]
### System info
- Playwright Version: [v1.39]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Details

I am launching the playwright ui in chrome using "npx playwright test --ui-host=localhost --ui-port=8080" command.

While running the test cases the steps, timeline view, browser view, network ,logs etc are not displayed and UI remains blank through out the execution. These details are only displayed once the test case execution is over.

![UiMode](https://github.com/microsoft/playwright/assets/65117374/46f375c4-2935-4fab-805f-6e99c7c2c698)

Can anyone please let me know what is wrong here?

**Comment by mxschmitt** [comment]
How does your test file look like?

**Comment by vipinphogat91** [comment]
Below is my test file:

`const { test, chromium } = require('@playwright/test')
require('dotenv').config()
const currentPath = require('path').resolve('./')
const Base = require('./../packages/package_base/base')
const dp = require('./../packages/package_util/excelUtil')
const iDriver = require('./../packages/package_util/webDriver')
const controller = require('./../packages/package_copilot/controller')
const { logger } = require('./../packages/package_util/testUtils')
const { throwException } = require('./../packages/package_exceptions/exceptions')
const fs = require('fs')
const gc = require('../packages/package_base/bin')
const { DataCarrierUtils } = require('./../packages/package_util/testUtils')

const testUtils = require('./../packages/package_util/testUtils')

const getPort = require('get-port')
const path = require('path')

let config = null
let tcCount
let tcList
let browserContext
let testCaseInfo
let tcVideoPaths = []
let port
let profilePath = `${currentPath}${process.env.PROFILE_PATH}`

//Desctiption - reading the config file and prepare the environment for test run.
//The function is invoking setup() defined in Base class before starting the execution

const configInstance = new Base()

config = configInstance.setup()

//Description - test.describr.config function is used to implement the config params at test level druing runtime.

//Documentation - https://playwright.dev/docs/api/class-test#test-describe-configure
test.describe.configure({
  timeout: config.timeout,
  retries: config.retries,
})

// Description - Below code is responsible for reading the testuite tab of test suite file.
//The file path is being fetched from .env file

const testData = new dp(config.dataPath, config.suiteTab)
const testCasePack = testData.testSuiteProvider()
tcList = Object.keys(testCasePack)
tcCount = tcList.length

for (let i in testCasePack) {
  const tcName = testCasePack[i].tcName
  const executionFlag = testCasePack[i].exeFlag
  const browserName = testCasePack[i].browser
  const headlessMode = config.headless

  if (executionFlag === 'Y') {
    logger.info(`Initiating test case: ${tcName}, Execution Flag - ${executionFlag}`)
  } else {
    logger.warn(`Skipping test case: ${tcName}, Execution Flag - ${executionFlag}`)
  }
  test.describe(testCasePack[i].category, () => {
    test.beforeAll(async () => {
      
    })
    //=Description - setting up the environment for next test case
    test.beforeEach(async () => {
      port = await getPort()
      // await lic.connectDB()
      if (executionFlag === 'Y') {
        //=Initiating browser operations
        const driver = new iDriver()
        browserContext = await driver.getBrowserType(browserName, headlessMode, config.options, port)

        tcVideoPaths.length = 0
      }
    })

    //Description - tearing down the environment for next test case
    test.afterEach(async ({}, testInfo) => {
      if (executionFlag === 'Y') {
        try {
          //!get remaining vidoes from all pages which are not opened with goto
          //! but internally opened by application
          let allPages = browserContext.pages()
          for (let page of allPages) {
            let temp = await page.video().path()
            if (!tcVideoPaths.includes(temp)) tcVideoPaths[tcVideoPaths.length] = await page.video().path()
          }

          await browserContext.close()
          console.log('Closing the context')
          //= Deleting the profile created for test execution
          //=this.deleteDirectory(`${currentPath}${process.env.PROFILE_PATH}`)
          testUtils.deleteProfileDirectory(profilePath)

          for (let i = 0; i < tcVideoPaths.length; i++) {
            await testUtils.attachVideo(testInfo, tcVideoPaths[i])
          }
        } catch (err) {}
      }
    })

    test.afterAll(async () => {
      globalTeardownFunction = async () => {
        let dataCarrierUtilsObj = new DataCarrierUtils()
        dataCarrierUtilsObj.createExcelFromJsonDataCarrier()
        console.log('Teardown executed')
      }

      await globalTeardownFunction()
    })

    //=Description - test method
    test(`${tcName}`, async ({ request }, testInfo) => {
      test.skip(executionFlag !== 'Y') //= Skipping the test case based on Execution flag
      let page
      await test.step(`Launching ${browserName} browser and navigating to URL : ${config.baseURL}`, async () => {
        const pages = await browserContext.pages()
        page = pages[0]
        logger.info(`Launching URL: ${config.baseURL}`)
        await page.goto(`${config.baseURL}`)
        tcVideoPaths[tcVideoPaths.length] = await page.video().path()
      })

      //= Starting the execution by reading the object Repository and data sheet
      let executableEntities = {
        transaction: testCasePack[i].transactions,
        pageInstance: page, //=> Current Page instance
        contextInstance: browserContext,
        testCaseName: tcName,
        tcInfo: testInfo,
        pageType: 'page',
        parentPage: page, //=> Parent instance - this will always be a page and never going to change
        videoPaths: tcVideoPaths,
        configSetupInstance: config,
        browser: browserName,
        apiReq: request,
        executionPort: port,
        set contInst(instance) {
          this.contextInstance = instance
        },
        get constInst() {
          return this.contextInstance
        },
      }
      const control = new controller(executableEntities)
      await control.getTransactionArray()
      browserContext = await executableEntities.constInst
    })
  })
}
`

**Comment by mxschmitt** [comment]
Why do you have so much complexity around creating your own browser, context, and page? If you create all yourself, it will not end up in UI Mode, this is expected.

We strongly recommend sticking with the [default fixtures](https://playwright.dev/docs/writing-tests#test-isolation) to get a page instance. You get benefits out of it like tracing/video will work out of the box, you don't need to take care of creating and closing it etc.

**Comment by vipinphogat91** [comment]
The UI mode was working with fine earlier but it stopped working after v1.38

**Comment by vipinphogat91** [comment]
@mxschmitt
I just removed the before all and after all hooks and now its working fine. 

Now when i am running the test cases through UI somehow the playwright-report folder is not getting updated. I mean html reports of the execution are not getting generated.

**Comment by pavelfeldman** [comment]
Looks like original issue was resolved, please file new issues for new problems.

**Comment by fazulk** [comment]
I just installed playwright for the first time ever, and first test runs fine, and then i am stuck with the same about:blank page as above. This is with no custom tests

**Comment by cheuni02** [comment]
This is happening to me as well on playwright@1.41.1
![image](https://github.com/microsoft/playwright/assets/9280368/a4db31b8-466f-43dc-9fa3-36859a9dfa54)

**Comment by tubbytoey** [comment]
I've the same issue here, I can't see any step of the test

**Comment by gutakk** [comment]
I can see the actions and test steps following https://github.com/microsoft/playwright/issues/21950#issuecomment-1485271688. Hope this help
