### ISSUE TITLE
[BUG] If preserveOutput is set to 'failures-only', the spinner of after hooks will not stop in ui mode.

### ISSUE THREAD

**Issue by kdeun1** [microsoft/playwright#27892]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [macOS 13.5]
- Browser: [Chromium]
- Other info:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ],
  // ...
  preserveOutput: 'failures-only', // this line
});
```

**Steps**
- [Run the test]
  npx playwright test --ui

**Expected**
![image](https://github.com/microsoft/playwright/assets/10824092/9cf01210-863e-4b2a-9779-c2f622986a02)
After Hooks is end. Spinner disappeared.

**Actual**
![image](https://github.com/microsoft/playwright/assets/10824092/5db43c3e-12a3-45d5-aaf5-fcd6da7aae69)
Spinner appeared at after hooks. infinite loop.

**Comment by pavelfeldman** [comment]
FYI: we are likely to deprecate and remove `preserveOutput` altogether, it'll be `always`.
