### ISSUE TITLE
[BUG] Installation on RPM-based Linux distribution not supported

### ISSUE THREAD

**Issue by harmin-parra** [microsoft/playwright#27890]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Fedora]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Problem

When installing the dependencies
`sudo npx playwright install-deps`

I get this error:
```
BEWARE: your OS is not officially supported by Playwright; installing dependencies for Ubuntu as a fallback.
Installing dependencies...
sh: line 1: apt-get: command not found
Failed to install browser dependencies
Error: Installation process exited with code: 127
```

RPM-based linux distributions aren't supported by playwright

The website https://playwright.dev/ clearly says:

Any browser • Any platform • One API
Cross-platform. Test on Windows, Linux, and macOS, locally or on CI, headless or headed.

**Comment by pavelfeldman** [comment]
We only support Ubuntu and Debian, Fedora is out of scope for Playwright.

**Comment by ani-shk** [comment]
@pavelfeldman Then maybe it should not say **Any Platform** on the homepage. 
![Screenshot 2023-11-07 at 10 30 45](https://github.com/microsoft/playwright/assets/88327487/8d88552f-944f-410b-afd6-ec404131f1d8)

**Comment by GoodVincentTu** [comment]
Hope it's not too late, so here's my solution
instead of installing the package using this command `npx playwright install`, try the following command:
```shell
sudo dnf install atk at-spi2-atk cups-libs libdrm at-spi2-core libX11 libXcomposite libXdamage libXext libXfixes libXrandr libgbm libxcb libxkbcommon pango cairo alsa-lib
```

I use the `1.42.1` for the playwright and fedora server as well, after executing the above command, the library works fine now. I hope it helps.
