### ISSUE TITLE
[Feature] macOS Big Sur support

### ISSUE THREAD

**Issue by p0x6** [microsoft/playwright#2789]
Let us know what functionality you'd like to see in Playwright and what is your use case.
With the looming release of macOS Big Sur, playwright should support it.

Do you think others might benefit from this as well?
There could be lots of people upgrading when the time comes.

**Comment by shirshak55** [comment]
why do you think playwright doesn't work on macOS Big Sur?

**Comment by imWildCat** [comment]
Any update on this?

**Comment by mxschmitt** [comment]
@imWildCat opened a PR #4149 yesterday can be merged soon I think.

**Comment by imWildCat** [comment]
@mxschmitt cool! Thanks for your work!
