### ISSUE TITLE
[BUG] Non HTML reports generated into directory playwright-report are cleared by HTML reporter 

### ISSUE THREAD

**Issue by jaktestowac** [microsoft/playwright#27895]
### Description
Directory `./playwright-report` is cleared by HTML reporter.
Reports from current run, if their output directory is `./playwright-report`, will be deleted if HTML reporter is not set as first in config (please see code below).

### System info
- Playwright Version: 1.39.0
- Operating System: Windows 10
- Browser: All

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  workers: 1,
  reporter: [
    ['junit', { outputFile: './playwright-report/results.xml' }], 
    ['json', {  outputFile: './playwright-report/test-results.json' }],
    ['html', { open: 'never' }]
  ],
  use: {
    // baseURL: 'http://127.0.0.1:3000',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('test 1', async ({ page }) => {
  expect(true).toBe(true);
});

test('test 2', async ({ page }) => {
  expect(true).toBe(false);
});
```

**Steps**
- Run the tests
- Wait for tests to finish
- Check directory `./playwright-report/`

**Expected**

All selected reports are generated into `./playwright-report/`

**Actual**

❌ Only HTML report is present inside `./playwright-report/`.
Previous reports from current run (JSON, XML) were cleared before generation of HTML.

![obraz](https://github.com/microsoft/playwright/assets/72373858/3c7df86f-15a4-4307-b994-2b4e51558ac8)

**Workaround**

HTML reporter must be set as first on the list:
```js
  reporter: [
    ['html', { open: 'never' }],
    ['junit', { outputFile: './playwright-report/results.xml' }], 
    ['json', {  outputFile: './playwright-report/test-results.json' }]
  ],
```

![obraz](https://github.com/microsoft/playwright/assets/72373858/336f20de-77ba-49e6-bcd3-86a6c50ae16a)

**Proposed solution**
- Directory `./playwright-report/` is cleared only once at the beginning of test run before generating any reports.
- Being able to have reports in one directory managed by Playwright will increase project's manageability and transparency.

**Comment by pavelfeldman** [comment]
`playwright-report` is the default location where HTML reporter outputs files. It owns this folder, it will create and delete it at its own will. When other reporters are pointed to location under `playwright-report`, they'll be intermittently deleted. Think about `playwright-report` folder as a binary file belonging to the HTML reporter.
