### ISSUE TITLE
[BUG] UI Mode - HTML reports are not generated when execution is done using Playwright UI launched in browser

### ISSUE THREAD

**Issue by vipinphogat91** [microsoft/playwright#27899]
### System info
- Playwright Version: [v1.39]
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Description

I am launching playwright in UI mode using command "npx playwright test --ui-host=localhost --ui-port=8080".

During execution everything works fine on UI and I can see all the details on it but somehow the HTML report is not generated.

I can see that files are getting updated in the test-results folder but same is not updated in playwright-report folder.

This works fine when execution is done from cli using npx playwright test command

Can anyone please let me know if this is how UI works or the HTML report should be generated

**Comment by pavelfeldman** [comment]
Reports are only generated by the CLI version of Playwright, UI Mode disables them because it is running the tests in the interactive mode. For example, when you run just one test in one file, your small report would be overwriting your full report, etc.
