### ISSUE TITLE
[Feature] Custom Messages for actions (.click, .fill, etc.)

### ISSUE THREAD

**Issue by davidjonesdialexa** [microsoft/playwright#27906]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

I use custom expect messages often to make my trace more quickly understandable. I'd like the same functionality for actions as well. This would allow one to quickly see that clicking or filling an element failed without having to interpret the locator.

**Comment by pavelfeldman** [comment]
The workaround for this would be:

```js
await test.step('Enter username', () => page.locator('#username').fill('John'));
```

If we were to add a dedicated API for it, it'll be something like:
```js
await page.locator('#username').fill('John', { alias: 'Enter username' });
```

which does not look that much better and requires patching the entire API surface instead of being layered.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
