### ISSUE TITLE
[BUG] Installer fails when using Yarn Workspaces

### ISSUE THREAD

**Issue by Marviel** [microsoft/playwright#27907]
### System info
- Playwright Version: [v1.17.131] (Based on the version of `create-playwright`)
- Operating System: [macOS]
- Browser: [All]
- Other info: [Yarn version 1.22.19, Node version 3.11.4]

### Source code

Any github repo using Yarn Workspaces.

**Config file**

```js
// Unable to provide, initialization failed
```

**Test file (self-contained)**

```js
// Unable to provide, initialization failed
```

**Steps**
- Run `yarn create playwright`
- Choose directory for tests: `tests`
- Choose to not add a GitHub Actions workflow
- Choose to install Playwright browsers

**Expected**

Successful installation and initialization of Playwright Test.

**Actual**

Installation fails with the error message: `error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).`

**Comment by pavelfeldman** [comment]
You might need to manually install Playwright via `yarn add` in your setting.

**Comment by Marviel** [comment]
> You might need to manually install Playwright via `yarn add` in your setting.

It seems like adding a `-W` flag would make sense for the playwright installer to do though, no?
Or prompting the user to ask if that's okay?

Just failing out doesn't feel like the most elegant approach.

**Comment by ojame** [comment]
I needed to install playwright into the root workspace as well - the easiest way is just to remove the `workspaces` field from your root `package.json` and run the main playwright install command (`yarn create playwright`). Once the install is finished, add the `workspaces` field back in.
