### ISSUE TITLE
[Feature] Ability to test recovery from electron renderer crash

### ISSUE THREAD

**Issue by jtbandes** [microsoft/playwright#27917]
Is there any way to detect whether an electron app can recover from a renderer crash?

I am testing an electron app that listens for `render-process-gone` and automatically loads a crash recovery page. I have a way to simulate a renderer crash for testing purposes using `process.crash()`. I would like to test the crash recovery behavior.

I'm able to detect the crash, but then I can't run any tests against the new page:

```ts
it("recovers from crash", async () => {
  const electronApp = await electron.launch({ ... });
  const electronWindow = await electronApp.firstWindow();
  
  const requestPromise = electronWindow.waitForRequest((req) =>
    req.url().includes("crash-recovery"),
  );
  
  // trigger renderer crash
  
  await electronWindow.waitForEvent("crash"); // works
  await requestPromise; // works

  // fails with "Target crashed" ...well yes...that's what I'm trying to test :)
  await electronWindow.waitForSelector('[data-testid="crash-recovery"]', { state: "visible" });
});
```

I'd expect `waitForSelector` to start working again once the page has been reloaded by the main process.

**Comment by pavelfeldman** [comment]
Support for Electron testing is experimental and renderer crash definitely falls outside of the scope of it.
