### ISSUE TITLE
[FEATURE] Improve multi-root support in VSCode by supporting custom install paths

### ISSUE THREAD

**Issue by fedorareis** [microsoft/playwright#27910]
**Let us know what functionality you'd like to see in Playwright and what your use case is.**

While the VSCode extension for Playwright technically supports multi-root workspaces, it doesn't do it well. As far as I can tell it still expects playwright to live in the node_modules at the root of the workspace and not in one of the other roots. However, in my monorepo the playwright tests are in their own root with it's own package.json. I think the easiest solution to this would to have the ability to point playwright to where the playwright install lives, similar to the `jest.rootPath` provided by the Jest VSCode extension.

**Do you think others might benefit from this as well?**

I think being able to point to a specific install location would be helpful to a lot of people and not just people using a monorepo.

**Comment by pavelfeldman** [comment]
The current logic for finding Playwright is to resolve it from the folder where playwright.config.ts is located. I.e. we require('playwright') from the folder with config and we expect it to bring us to the node_modules w/ the corresponding Playwright installation. This has been done a couple of months ago, so should be working on ToT.
