### ISSUE TITLE
[BUG] Invalid `testInfo.project` type in docs / cannot evaluate `project.expect.timeout`

### ISSUE THREAD

**Issue by luixo** [microsoft/playwright#27915]
### Problem

A fixture function has 3rd argument `testInfo` provided.
According to docs, it is an instance of class [TestInfo](https://playwright.dev/docs/api/class-testinfo) which should have a member `project`.
According to docs, it is an instance of class [TestProject](https://playwright.dev/docs/api/class-testproject) which should have a member `expect` of a type [given](https://playwright.dev/docs/api/class-testproject#test-project-expect) by docs.

In reality, `testInfo.project` is a `FullProject` type which doesn't have `expect` property at all, which is reflected in runtime as well.

Either docs should get fixed or `expected` property should be passed to `FullProject`.

If first is the way - how one might get a default `expect` timeout? I'd like to use in expect-like check that I added manually.

### System info
- Playwright Version: [v1.39.0]
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

A minimal reproduction:
```ts
import { test } from "@playwright/test";

type MyFixture = {
  foo: void;
}

const myTest = test.extend<MyFixture>({
  foo: [async ({}, use, testInfo) => {
    console.log("Expect timeout: ", testInfo.project.expect.timeout);
    await use();
  }, { auto: true }]
})
```

My case (simplified), with a custom fn that requires timeout:
```ts
import { test } from "@playwright/test";

type MyFixture = {
  customAwait: (timeout?: number) => Promise<void>;
}

const myTest = test.extend<MyFixture>({
  customAwait: async ({}, use, testInfo) => {
    await use(async (timeout = testInfo.project.expect.timeout) => {
      await page.evaluate(([timeout]) => {
        return new Promise((resolve, reject) => {
          // custom fn
          window.subscribe(resolve);
          setTimeout(reject, timeout);
        });
      }, [timeout])
    });
  }
})
```

**Steps**
- Use given fixture (the first one, with `foo`)
- Run any test with given fixture

**Expected**

Expect timeout logged.

**Actual**

Error - `expect` property of `testInfo.project` is undefined causing an error.

**Comment by pavelfeldman** [comment]
The action item here is to expose the resolved project/config types and expose expect settings there.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your contribution to our project. This issue has been closed due to its limited upvotes and recent activity, and insufficient feedback for us to effectively act upon. Our priority is to focus on bugs that reflect higher user engagement and have actionable feedback, to ensure our bug database stays manageable.

Should you feel this closure was in error, please create a new issue and reference this one. We're open to revisiting it given increased support or additional clarity. Your understanding and cooperation are greatly appreciated.

**Comment by luixo** [comment]
This is still reproducible in v1.43.1.
Types are still pointing on `FullProject` with no `expect` inside, runtime still does not have `expect` property in `testInfo.project` property.

@pavelfelman it should not be closed.

My setup:
```my.spec.ts
import { test } from "@playwright/test";

type MyFixture = {
  foo: () => void;
};

const myTest = test.extend<MyFixture>({
  foo: [
    async ({}, use, testInfo) => {
      console.log("Expect timeout: ", testInfo.project.expect.timeout);
      await use(() => {});
    },
    { auto: true },
  ],
});

myTest("Validating issue 27915", async ({ foo }) => {
  foo();
});
```

Running:
```sh
> npx playwright test --grep "27915"

Running 1 test using 1 worker
  1) [functional] › functional/my.spec.ts:17:1 › Validating issue 27915 
────────────────────────────

    TypeError: Cannot read properties of undefined (reading 'timeout')

       8 |   foo: [
       9 |     async ({}, use, testInfo) => {
    > 10 |       console.log("Expect timeout: ", testInfo.project.expect.timeout);
         |                                                               ^
      11 |       await use(() => {});
      12 |     },
      13 |     { auto: true },

        at Object._test.test.extend.foo.auto (<redacted>/my.spec.ts:10:63)

  1 failed
    [functional] › functional/my.spec.ts:17:1 › Validating issue 27915
```

Verifying version:
```sh
> npx playwright test --version
Version 1.43.1
```
