### ISSUE TITLE
Playwright refreshes value typed in input field[BUG]

### ISSUE THREAD

**Issue by TomaszMQA** [microsoft/playwright#27924]
### System info
- Playwright Version: 1.30.0
- Operating System: Windows 10 Enterprise
- Browser: Chrome
- Other info:
 When I am filling-in the input field using playwright and clicking submit button, playwright refreshes the filled-in value before submitting button which results in displaying message for updated value instead of message for added value:

### Source code

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';
import * as dotenv from 'dotenv';
dotenv.config({ path: `.env.${process.env.ENV || 'local'}` });

export default defineConfig({
  testDir: './tests',
  timeout: 0,
  expect: {
    timeout: 60 * 1000
  },
  forbidOnly: !!process.env.CI,
  fullyParallel: false,
  retries: process.env.CI ? 1 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI
    ? [
        ['list'],
        ['html', { open: 'never' }],
        ['junit', { outputFile: 'junit-report/results.xml' }],
        ['allure-playwright']
      ]
    : [['list'], ['html', { open: 'never' }]],
  use: {
    headless: true,
    video: 'retain-on-failure',
    screenshot: 'only-on-failure',
    trace: process.env.CI ? 'off' : 'retain-on-failure',
    actionTimeout: 60 * 1000,
    navigationTimeout: 60 * 1000
  },
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome']
      }
    }
  ]
});

```

**Test file (self-contained)**

```testfile.spec.ts
import { TestPage } from 'test-page';

testPage = new TestPage();

test.describe('Test', () => {
  test('should accept correct value', async ({ testPage }) => {
      await testPage.inputValue.type(value);
      await testPage.saveChangesButton.click();
    });
});
```
```test-page.ts

export class TestPage {
  readonly page: Page;
  readonly inputValue: Locator;
  readonly saveChangesButton: Locator;

  constructor(page: Page) {
    this.page = page;
    this.inputValue = page.locator('#id');
    this.saveChangesButton = page.getByRole('button', { name: 'Save changes' });
  }
}
```

**Steps**
- Put value in input field and click the submit button

**Expected**

Value is put in the field and message for added value is being generated

**Actual**

Value is put in the field, updated and message for updated value is being generated

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by whimian** [comment]
I encountered the same problem when using advanced search on a website. The site works well when interacted manually in the browser. But with playwright, `page.click()` on the Search button clears the values filled in the form, resulting in search with no parameters.
