### ISSUE TITLE
[BUG] tsconfig paths without a baseUrl are not supported

### ISSUE THREAD

**Issue by BPScott** [microsoft/playwright#27933]
Quoting https://www.typescriptlang.org/tsconfig#paths

> [paths is] A series of entries which re-map imports to lookup locations relative to the [baseUrl](https://www.typescriptlang.org/tsconfig#baseUrl) if set, or to the tsconfig file itself otherwise. There is a larger coverage of paths in [the handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping).

Typescript supports specifying paths without requiring a baseUrl. This behaviour was added in [typescript 4.1](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-1.html#paths-without-baseurl). For example:

```json
{
  "compilerOptions": {
    "paths": {
      "~/*": ["./app/*"],
    }
  }
}
```

However playwright does not currently support this configuration - it only looks at paths when a baseUrl is not present.

I've opened a PR to fix the basic case where paths are in the source tsconfig file - #27846.
Fixing this when the paths are in an extended file is more complex.

### System info
- Playwright Version: [v1.38]
- Operating System: [All]
- Browser: [All]
- Other info:

### Source code

For basic usage, add the following test to `tests/playwright-test/resolver.spec.ts`

```js
test('should use the location of the tsconfig as the paths root when no baseUrl is specified', async ({ runInlineTest }) => {
  const result = await runInlineTest({
    'foo/bar/util/b.ts': `
      export const foo = 42;
    `,
    'dir2/tsconfig.json': `{
      "compilerOptions": {
        "target": "ES2019",
        "module": "commonjs",
        "lib": ["esnext", "dom", "DOM.Iterable"],
        "paths": {"foo/*": ["../foo/*"]},
      },
    }`,
    'dir2/inner.spec.ts': `
      // This import should pick up ../foo/bar/util/b due to paths.
      import { foo } from 'foo/bar/util/b';
      import { test, expect } from '@playwright/test';
      test('test', ({}, testInfo) => {
        expect(foo).toBe(42);
      });
    `,
  });

  expect(result.exitCode).toBe(0);
  expect(result.passed).toBe(1);
  expect(result.output).not.toContain(`Could not`);
});
```

For advanced usage - adding paths within an extended config, add:

```js
test('should use the location of the extended tsconfig as paths root when no baseUrl is specified', async ({ runInlineTest }) => {
  const result = await runInlineTest({
    'tsconfig.json': `{
      "extends": ["./other/tsconfig.base.json"],
    }`,
    'other/tsconfig.base.json': `{
      "compilerOptions": {
        // paths without a baseUrl should resolve relative to the file they're in, which means
        // the base for these paths should be "other/". However playwright will currently
        // resolve them relative to the top-level tsconfig, not the extended from config
        // Note that adding baseurl:'.', fixes this within playwright but has the undesireable
        // effect of enabling the wildcard matching for additional top-level folders in the
        // "other" directory
        // "baseUrl": ".",
        "paths": {
          "util/*": ["../dir/foo/bar/util/*"],
        },
      },
    }`,
    'a.test.ts': `
      const { foo } = require('util/file');
      import { test, expect } from '@playwright/test';
      test('test', ({}, testInfo) => {
        expect(foo).toBe('foo');
      });
    `,
    'dir/foo/bar/util/file.ts': `
      module.exports = { foo: 'foo' };
    `,
  });

  expect(result.passed).toBe(1);
  expect(result.exitCode).toBe(0);
});
```

**Steps**

Add the above test cases to `tests/playwright-test/resolver.spec.ts` and run playwright's tests

**Expected**

Tests pass

**Actual**

Tests fail, because path is not supported unless a baseUrl is present

**Comment by pavelfeldman** [comment]
> Fixing this when the paths are in an extended file is more complex.

I'd say we deal with it when it gets reported - it does not sounds like a great practice anyways. Closing as fixed in #27846.
