### ISSUE TITLE
[BUG] Unable to launch Playwright electron app via Jenkins, however, same code works fine locally

### ISSUE THREAD

**Issue by crashman4** [microsoft/playwright#27934]
### System info
- Playwright Version: [v1.XX] 1.31
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.] Windows Jenkins agent
- Browser: [All, Chromium, Firefox, WebKit] Desktop app.
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

or

**Config file**

**Test file (self-contained)**

**Steps**
- [Run the test] Via Jenkins
- [...]

**Expected**
It should launch the desktop app (exe file) specified at the gdExePath path via Jenkins, as it works fine while running locally.

**Actual**
Tried both option: headless: true, AND headless: false,

Error:
TimeoutError: electron.launch: Timeout 180000ms exceeded.

      22 |   //Launch 
      23 |   await timeouts.waitForTime(5000);
    > 24 |   electronApp = await electron.launch({
         |                 ^
      25 |   executablePath: gdExePath,
      26 |     cwd: gdDir,
      27 |   });

        at C:\Users\Jenkins\workspace\..\...\...

**Comment by pavelfeldman** [comment]
When something works locally and does not work in CI, we default to suggesting that the environment is not set up properly. Playwright is a framework and if it runs for you locally, it should run for you in CI as well.
