### ISSUE TITLE
[Question] How to handle async function in constructor level. Not able to handle page navigation.

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27935]
I am using Playwright test runner, each test case involved multiple pages. I am initiating each class using page fixture as per the documentation. My each page should navigated to the page before executing any actions. Here I am facing challenges to handle navigation for each page. The constructor not allowed to add the async method, I tried with and without - multiple options in the internet, However no luck. Is there any way to handle to async navigation script in the constructor level or default way execution before executing any method instead of calling navigation every time in the spec/test file?

E.g.) test.ts
```
test.only("tc1 ", async ({page1, page2 }) => {
    await page1.action1(data.name, data.description);
    await page2.action1();
})
```
page1.ts
```
export class page1 extends BaseWrappers {
constructor(page: Page) {
        super(page);
        this.page = page
       <Here how to add async function/ wrapper function>
}
```

page2.ts
```
export class page2 extends BaseWrappers {
constructor(page: Page) {
        super(page);
        this.page = page
       <Here how to add async function/ wrapper function>
}
```

If add the wrapper method in the constructor, always execute the last page class constructor and skip all previous class actions inlcluding the constructor.

Note: I tried it in fixture level as well, but execution in parallel during object creation, so navigation code executing at the time of object creation, but when code start executing the test cases, server is not in the right page i.e. during page1.action execution, control in page2 

pls suggest

**Comment by pavelfeldman** [comment]
You do this in fixtures:

```js
page1: async ({ page }, use) => {
  const page1 = new Page1(page);
  await page1.initialize();
  await use(page1);
  await page1.dispose();
}
```

**Comment by iburahim786** [comment]
I tried without dispose command, Getting the same problem.

Page1 and Page2's class initialze methods are running subsequently (1 after another) but Page1 Methods are not calling from the test/spec file. Page 2 class methods executing. :(

**Comment by pavelfeldman** [comment]
`dispose` was an example of a method you would want to call after your test. The example above demonstrates how you can work around the idea of running async code in the constructor via introducing an async `initialize` method.

**Comment by iburahim786** [comment]
Okay, But I don't have any requirement to run dispose() methods after use, and a set of actions needs to be run from the spec/test file.

I am also expecting a constructor role to be executed here. But currently running like below,

Actual:
Page1 -> Initialize -> Page2 -> Initialize - > Page1.actions1().

Expected:
Page1 -> Initialize -> Page1.action1() -> Page1.actionN() -> Page2 -> Initialize -> Page2.actions1() -> Page2.actionsN()...

**Comment by pavelfeldman** [comment]
Then don't dispose! Anyhow, it looks like this is more of a JavaScript question than Playwright, so closing.
