### ISSUE TITLE
[Question] Is it possible to stop and resume Playwright test ? 

### ISSUE THREAD

**Issue by ZakharDolozhevskiy** [microsoft/playwright#27938]
I'm writing a plugin for internal usage in Playwright tests ( specific to company checks ) 

The idea is that: 

```
test('should do something', async ({ page }) => {
  startChangeWatcher(page)
  // Test usually contains:
  // Interaction with page that leads to DOM change
  // Interaction with links, like click that opens another page or triggers routing
  // Test is out of my control so I can't change anything here
  stopChangeWatcher();
});
```

`startChangeWatcher` - should be called at the first line of the test and:

a) Listen to URL change and perform the task
b) Listen to DOM change and perform the task

Task - is an async operation that checks DOM structure and may take some time to be completed

**Problem**

When the event that triggers task happens there are no way to stop test from further execution, so it leads to issues: 

a) Task can't reach the page because the page already changed ( a new one opened ) 
b) Task can't properly check DOM structure after some change as DOM might be changed again or page might be closed ( due to <a/> element click for example ) 

**Solution**

I want to have a way to call something like "test.pause" then perform check that i need and call "test.resume"
In this case i can be sure that task interacted with proper state of the page.

**Comment by pavelfeldman** [comment]
This looks like a JavaScript problem: you can create a promise and await it in the script, while fulfilling it once your task is done.
