### ISSUE TITLE
[Feature] route server side reuqest

### ISSUE THREAD

**Issue by BY-juun** [microsoft/playwright#27947]
Hello I am currently using nextjs@13 and react server component
I want to route a request from the server component to the server, but it doesn't work
Before nextjs@13, the route did not work the same when sending server side requests within getServerSideProps, getStaticProps

Unable to find relevant information in docs and issues, leave issue
If there are any related functions, please let me know

The code below is for the server side request sent by the server component
``` tsx
const PostPage = async ({ params: { id } }: Props) => {
  const postData = await getPost({ id: Number(id) });

  return (
    ...
  );
};

export default PostPage;

async function getPost({ id }: Pick<PostType, "id">) {
  try {
    // cannot route
    const res = await fetch(`${ServerURL}/post/load/${id}`, {
      cache: "force-cache",
    });

    const postData: PostPageDataType | null = await res.json();

    return postData;
  } catch (err) {
    return null;
  }
}
```

**Comment by pavelfeldman** [comment]
Your server-side requests run in your server that is already built and that Playwright has no control / knowledge of. So it can't route network in a separate application it does not know about.
