### ISSUE TITLE
Issue with importing Swiper bundles causing "SyntaxError: Unexpected token 'export'"

### ISSUE THREAD

**Issue by kabeh2** [microsoft/playwright#27941]
### System info
- Playwright Version: [v1.39]
- Operating System: macOS 14.0
- Browser: Chromium
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

**Reproducible Test Case**:
I can reproduce the issue with the following minimal code example in a Playwright test:

```javascript
import { test } from "@playwright/test";
import "swiper/css/bundle";

test("test", async ({ page }) => {
  await page.goto("https://example.com");
});
```

**Steps**
- Install Playwright (1.39) and the latest swiper (11.0.3) and create a Playwright test file with the code snippet mentioned above.
- Run the test script using Playwright.
- Observe the "SyntaxError: Unexpected token 'export'" error.

**Expected**

The test script should run without any errors, and the Swiper bundle should be imported successfully.. Should be able to import any of the swiper/react and css bundle files without an error.

**Actual**

I encountered an issue when trying to import Swiper bundles in a Playwright test script. This issue results in a "SyntaxError: Unexpected token 'export'" error. 

This issue seems to be related to the import of Swiper bundles. Please advise on how to resolve this issue or if there are any workarounds.

**Comment by pavelfeldman** [comment]
I don't think it makes sense to import swiper in the context of the Playwright test. If I had to guess, you are importing an ESM module that is designed to run in the browser from a CJS context in Node.

**Comment by kabeh2** [comment]
> I don't think it makes sense to import swiper in the context of the Playwright test. If I had to guess, you are importing an ESM module that is designed to run in the browser from a CJS context in Node.

It was more so in regards to importing it in a component that is tested, that uses that css bundle. The code example above was the simplest way to repro. When testing
