### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by adrian771985** [microsoft/playwright#27942]
It would be nice to have an improved debug mode where we can go back to a specific point (similar to how we can stop the test) without having to launch the test from the beginning. In Selenium IDE, for example, we can select "replay from a point". This way it is much faster to run again the point where we need to do more tests until we get the expected behavior. This way we wouldn't have to bring up the browser again, navigate to the page etc.

**Comment by pavelfeldman** [comment]
Could you elaborate a full user story for this? I understand how a feature like this would make sense for Java environment, but in JavaScript w/ VS Code extension, there are way more flexible and fast ways to get to a required state, so I'm not sure what exactly is missing.

**Comment by pavelfeldman** [comment]
We need more information to act on this report. As long as we can't repro it, it is unlikely with can make progress with it. Allow me to close it, but please file a new one and link to this issue when you get back to it!
