### ISSUE TITLE
[Question] Rollup fail to import "workerize-loader!../workers/attribute.worker"

### ISSUE THREAD

**Issue by pyrodalus** [microsoft/playwright#27954]
Hi there is this function declared in global.d.ts which is used by one of my componets. 

```
// global.d.ts
declare module "workerize-loader!*" {
  type AnyFunction = (...args: any[]) => any;
  type Async<F extends AnyFunction> = (...args: Parameters<F>) => Promise<ReturnType<F>>;

  type Workerized<T> = Worker & { [K in keyof T]: T[K] extends AnyFunction ? Async<T[K]> : never };

  function createInstance<T>(): Workerized<T>;
  export = createInstance;
}
```

When running component tests, just importing the component itself result in below error

`vite]: Rollup failed to resolve import "workerize-loader!../workers/attribute.worker"`

Does anyone know how to resolve this?

**Comment by pavelfeldman** [comment]
Seems unrelated to Playwright
