### ISSUE TITLE
[BUG]playwright AndroidDevice webview connection timeout in blink kernel case

### ISSUE THREAD

**Issue by okaychen** [microsoft/playwright#27953]
### System info
- Playwright Version: [1.30.0]
- Browser: [webview，blink]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**main file**

```js
import {_android as android, AndroidDevice} from 'playwright';

let _device: AndroidDevice;

beforeAll(async () => {
    const [device] = await android.devices();
    _device = device;
    console.log(`Model: ${device.model()}`);
    console.log(`Serial: ${device.serial()}`);

    const landingPageScheme = getSchemeLandingPage(NewsNid.ads, NewsCommentId.ads);
    await device.shell(`am start -a android.intent.action.VIEW -d 'xxxscheme' xxxpkg`);
    const webview = await device.webView({pkg: 'xxx'}, {
        timeout: 30000,
    });

    const page = await webview.page();
    await page.waitForURL('**/*');
    console.log(await page.title());
});

it('xxx, async () => {
    xxx
});

afterAll(async (done) => {
    await _device.shell(`am force-stop xxx`);
    await _device.close();
    done();
});

```

![image](https://github.com/microsoft/playwright/assets/32173521/5e8dcac1-9e5b-4b8d-b129-f2139e994a86)

**Comment by pavelfeldman** [comment]
Webview was not created within the test timeout, so you got an exception. We have no way of knowing why this did not happen.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
