### ISSUE TITLE
[Q] Unable to run Globalsetup.ts file from custom folder.

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27955]
@yury-s -s   https://github.com/microsoft/playwright/issues/27770#issuecomment-1785652793 - Continuation 

my understanding is when I am giving the testMatch: /globalSetup\.ts/ and globalSetup.ts present in the test directory - It works which means testMatch always prefers to get files from the test directory.
But My case it is in a different folder, So it's not taking. So I assumed, I was supposed to navigate from the test directory to the current one - So written like "../config/globalSetup.ts"

I tried the way you suggested as well like below,

testMatch: "src/ui/config/globalSetup.ts"
testMatch: "./src/ui/config/globalSetup.ts"
testMatch: "../src/ui/config/globalSetup.ts" (just)

But not working! Now tell me what shall I do?

**Comment by pavelfeldman** [comment]
You should place your global setup files into the testDir folder and make sure testMatch matches them.
