### ISSUE TITLE
[BUG] Intercepting bplist responses in Chromium leads to broken bplists

### ISSUE THREAD

**Issue by lu4p** [microsoft/playwright#27951]
### System info
- Playwright Version: [v1.39.0]
- Operating System:  Tested on Linux, probably others
- Browser: [Chromium]

### Source code

- [x]  I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/lu4p/bplist-issue

**Steps**
```
npm run start
```
**Expected**
When intercepting responses the response should match the actual response received by the Browser over the wire, byte for byte. 

**Actual**

In chromium when intercepting a response that contains arbitrary binary data in it's body, it doesn't match the response body sent by the server. 

It does however match a loosely accurate human readable form in the chromium devtools. This is also the only form the response body can be (easily) accessed from the chromium devtools (maybe this should be also raised upstream). I find this is at least a very weird choice for devtools which should provide accurate feedback. Firefox uses base64 encoding in it's devtools  when there is no sensible human readable form.

This bug can be avoided for the time being by using Firefox instead of chromium, which I ended up doing. I'm writing this bug report anyway, because I don't want anyone to run into a similarly hard to debug mess.

**What I went through to find this bug:**

My bplist parser keeps crashing, with "object limit exceeded" when parsing a response.
1. maybe the object limit of the parser is just set too low 
    -  no that was there for good reasons, crashed my PC

2.  maybe the parser or the response is just broken
    - download the response with Firefox
    - tried another parser in another language  
    - works great, the parser is probably broken
    - one last check that the js parser really can not handle the same file, it can????

3. maybe I'm not passing the response to the parser correctly 
    - this lead to a couple hours of myself questioning my sanity

4. am I even receiving the correct data?
    - looks reasonably bplisty when opening in a normal text editor

5. is this the same response I downloaded earlier?
    - yes looks like it, why doesn't it work then?

6. really the same?
    - no the chromium response is slightly longer and has extra information in some places where Firefox's response doesn't

7. so just uses Firefox instead, or is this a general playwright issue?
    - yes, works immediately
    
8. where does chromium get the extra data from?
    - copies human-readable response from chromium devtools, matches the previous responses 100%

**Comment by pavelfeldman** [comment]
You are doing something unusual in your snippet. If you are doing response interception, you should do something like this:

```js
    context.route('**/uid.bplist', async (route, request) => {
        const resp = await route.fetch()
        const body = await resp.body()
        printFile(body)
        route.continue()
    });
```

If you are interested in the response event, you would do this:

```js
    context.on('response', response => {
      response.body().then(printFile);
    });
```

The reason Chromium is misinterprets the information you send is that you use invalid mime type `application/x-bplist; charset=UTF-8`. You data is binary and you should not pass charset for it. Also your second parameter for `response.end` when used with the buffer is ignored.
