### ISSUE TITLE
[BUG] Unable to install playwright in Ubuntu

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27959]
Unable to install Playwright in Ubuntu box, I searched internet no relevant information is available, Am i missing anything in the Ubuntu server?

**OS: Ubuntu 20.04.5 LTS**

```
globalThis is not defined
{ Error: Command failed: npx playwright install --with-deps
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at executeCommands (/home/nadmin/.npm/_npx/37701/lib/node_modules/create-playwright/lib/index.js:4519:39)
    at Generator.run (/home/nadmin/.npm/_npx/37701/lib/node_modules/create-playwright/lib/index.js:4682:5)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 37754,
  stdout: null,
  stderr: null }
nadmin@nadmin:~/pw$ sudo npx playwright install-deps
globalThis is not defined

```

![image](https://github.com/microsoft/playwright/assets/21674533/22acc31e-5b8c-4488-9b99-de6638fb1acd)

**Comment by Az8th** [comment]
This is not a bug but the awaited behaviour, you should read the warnings : they clearly mentions your version of node is 10.19, while Playwright needs at least 16
Can be also seen in changelogs of v1.34:
![image](https://github.com/microsoft/playwright/assets/24222857/78dd454d-fa57-43c2-a032-7ddea9c263b4)

**Comment by iburahim786** [comment]
oh, my bad. Sorry for unnoticed this. I will close this defect.

**Comment by Az8th** [comment]
No worries, it happens, especially at the end of the week, you should consider giving some rest to your eyes ;)
