### ISSUE TITLE
[BUG] Component testing doesn't run with React 17, because of react-dom changes

### ISSUE THREAD

**Issue by jacobweber** [microsoft/playwright#27964]
### System info
- Playwright Version: [@playwright/experimental-ct-react ^1.39.0]
- Operating System: [MacOS 14.1]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

**Steps**
- Follow the [setup instructions](https://playwright.dev/docs/test-components) on a project with React 17.
- Run `npm run test-ct`

**Expected**

No errors

**Actual**

Received error:
```
> playwright test -c playwright-ct.config.ts

Running 3 tests using 3 workers

vite v4.5.0 building for production...
✓ 3 modules transformed.
✓ built in 79ms
[vite]: Rollup failed to resolve import "react-dom/client" from "/path/to/project/playwright/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```

I can fix this by manually editing `node_modules/@playwright/experimental-ct-react/registerSource.mjs` to use the React 17 method of mounting, e.g.:

```
import ReactDOM from 'react-dom';
  ...
  // const root = __pwCreateRoot(rootElement);
  const root = rootElement;
  __pwRootRegistry.set(rootElement, root);
  // root.render(App());
  ReactDOM.render(App(), root);
```

**Comment by pavelfeldman** [comment]
You should use `@playwright/experimental-ct-react17` for legacy react.
