### ISSUE TITLE
[BUG] When there is a multi dependency project in define config --grep-invert stops working

### ISSUE THREAD

**Issue by BMayhew** [microsoft/playwright#27974]
### System info
- Playwright Version: [v1.39]
- Operating System: [macOS 13.5]
- Browser: [n/a]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/BMayhew/playwright-grep-examples

**Steps**

- Run the tests with the command `npx playwright test --grep-invert @unsatisfactory`
- Make note that `Running 9 tests` were run and view the titles of the tests note that 5 of the tests include the @unsatisfactory tag but yet get run

**Expected**

I would expect that all files would run that do not include the @unsatisfactory tag within my tests.

**Actual**

The --grep-invert is ignored and tests tagged with @unsatisfactory are run

**Additional information**

If I go the the config file and within the projects section, I go in and remove the "specs" value from the teardown project dependencies, and run the suite with the same command `npx playwright test --grep-invert @unsatisfactory` note that only 4 tests are run which is what I would expect.
```
  projects: [
    { name: "setup", testMatch: /test.setup.ts/ },
    {
      name: "specs",
      dependencies: ["setup"],
    },
    {
      name: "teardown",
      dependencies: ["setup", "specs"], //Remove the "specs" value from this line
      testMatch: /completion.teardown.ts/,
    },
  ],
  ```

**Comment by dgozman** [comment]
@BMayhew When you pass `--grep-invert` in this configuration, Playwright assumes it only applies to the "top-level" projects that are not a dependency of any other project. This is the main usecase for `--grep-invert`.

You have the following options:

1. Migrate your `teardown` project to be a proper teardown:
```ts
  projects: [
    { name: "setup", testMatch: /test.setup.ts/, teardown: 'teardown' },  // Note teardown here.
    {
      name: "specs",
      dependencies: ["setup"],
    },
    {
      name: "teardown",
      testMatch: /completion.teardown.ts/,
    },
  ],
```

2. Pass `--no-deps` option. Note that this will break the order guarantees between the dependencies, so you'll probably need to run each project separately:
```sh
npx playwright test --grep-invert @unsatisfactory --no-deps --project=setup
npx playwright test --grep-invert @unsatisfactory --no-deps --project=specs
npx playwright test --grep-invert @unsatisfactory --no-deps --project=teardown
```

---

Let me know whether this helps.

**Comment by BMayhew** [comment]
@dgozman That helps big time! Not sure how I missed this in the docs, but it's clearly there in this example: https://playwright.dev/docs/test-global-setup-teardown#teardown-example

What did confuse me was the --grep @unsatisfactory did what I expected by only running the @unsatisfactory tagged files in the specs project.

That being said, I'll close this ticket, thanks for the detailed response!
