### ISSUE TITLE
[BUG] Test randomly fails when calling the page.goto() API after timeout occurs.

### ISSUE THREAD

**Issue by sonnguyenduc** [microsoft/playwright#27970]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Ubuntu, macOS 13.5]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  testDir: './tests',
  fullyParallel: true,
  forbidOnly: !!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: 'list',
  use: {
    trace: 'retain-on-failure',
    channel: 'chrome',
    actionTimeout: 15_000,
  },
  timeout: 10_000,
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/test';

test('should fail by fill timeout', async ({ page }) => {
  try {
    await page.goto('https://www.facebook.com');
  } catch (error) {
    console.log(error);
    throw error;
  }
  
  await page.fill('[name="user[email]"]', "username", { timeout: 100 });
});

```

**Steps**
- [Run the test] using command: `playwright test --workers 4 --repeat-each=100`

**Expected**

Test failed due to fill API timeout

**Actual**

Test randomly failed due to goto API with error
`Error: page.goto: net::ERR_ABORTED; maybe frame was detached?`
or
`page.goto: Page closed`

![Screenshot 2023-11-04 at 6 55 27 am](https://github.com/microsoft/playwright/assets/127935387/58ae7bb5-50d4-442e-840f-a262c6a990c2)

**Comment by pavelfeldman** [comment]
You are getting throttled by facebook as a spammer.
