### ISSUE TITLE
sharing of storage state is broken in v1.39.0. Works fine in 1.38.0

### ISSUE THREAD

**Issue by bondar-artem** [microsoft/playwright#27977]
### System info
- Playwright Version: v1.39.0
- Operating System: All
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/bondar-artem/playwright-bug

**Steps**
- run apiTest.spec.ts
- test runs the precondition step to use a storage state
- test runs, application opened, session is not authorized

**Expected**

when application opens, user should be already looged in

**Actual**

user is not logged in

When downgrade to Playwright 1.38, the test works as expected and user session is authorized when application opens

**Comment by pavelfeldman** [comment]
Works fine for me. Note that you are using `fs.writeFileSync` with relative path (resolved relative to CWD), so your tests aren't working in the general case. You should always `path.resolve(__dirname, '../auth/user.json')` or `require.resolve('../auth/user.json')` to get consistent path that does not depend on the folder you run your tests from.

**Comment by qu-niao** [comment]
+1

**Comment by bondar-artem** [comment]
@pavelfeldman I don't think that `fs.writeFileSync` it's the case.
You can remove the auth.setup.ts from the project altogether, only leaving the user.json file with a valid token. Then read this file in playwright.config.ts. Like this:

```
export default defineConfig({
  testDir: './tests',
  reporter: 'html',
  use: {
    trace: 'on-first-retry',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], storageState: '.auth/user.json' }
    }
  ]
});
```
And it's reproducible on my end.
With Playwright 1.39 - the storage state is not set
With Playwright 1.38 and earlier versions - it is working fine.

**Comment by dgozman** [comment]
@bondar-artem I can reproduce the issue. Your site behaves differently between Chrome 117.0.5938.62 that comes with Playwright 1.38.1 and Chrome 119.0.6045.9 that comes with Playwright 1.39.0. Setting `localStorage.jwtToken` results in a 401 request in the newer Chrome.

I'd say Playwright has found a bug on your site that breaks with the browser update. Sounds like a success story 🎉  Happy testing!

**Comment by bondar-artem** [comment]
> I'd say Playwright has found a bug on your site that breaks with the browser update. Sounds like a success story 🎉 Happy testing!

@dgozman Could you please let me know how did you get 401?
I have just updated my Chrome to 119.0.6045.9, then manually navigated to the application, clicked Sign In, entered my username and password, and was successfully authorized.

**Comment by dgozman** [comment]
@bondar-artem I evaluated `localStorage.jwtToken = "...."` in DevTools Console with the value from `user.json` and reloaded the page.

**Comment by bondar-artem** [comment]
@dgozman 
I tried it, worked for me just fine in Chrome 119. No errors.
Probably you have 401 because you took the expired token from the repo. Generate a new token with username and password.
![image](https://github.com/microsoft/playwright/assets/21285622/8e6de2e8-6082-40cc-9379-38b0eacffed8)

Local storage:
![image](https://github.com/microsoft/playwright/assets/21285622/9b276544-743c-4cd4-8a3e-22ea1cf0758f)


But if you do the same in the Playwright, you will see that Local storage in the browser remains empty after the execution

**Comment by dgozman** [comment]
@bondar-artem I just tried the following in Chrome 120.0.6099.5

- Open https://angular.realworld.io/ in a new incognito tab
- Sign in with credentials from the repo
- Everything signed in as expected
- I checked that `localStorage.jwtToken` is there
- Reloaded the page (Cmd+R)
- The page is now is signed out state
- DevTools shows the 401 request, and `localStorage.jwtToken` is now empty, cleaned up by the site

I'd say Playwright works the same way as I did manually.

**Comment by bondar-artem** [comment]
@dgozman Thank you!
You are right, the issue is identified on my side
