### ISSUE TITLE
[Feature] Be able to instantiate a locator with any arbitrary JQuery selector statement

### ISSUE THREAD

**Issue by harmin-parra** [microsoft/playwright#27975]
Is it possible to add a new locator, which could be named **get_by_jquery** or **get_by_jquery_selector**, that could take an arbitrary JQuery selector statement ?

In this case, we could be able to use some complex JQuery statements that don't have an equivalent in the Plawright locators API.

It can also come in handy for advanced users who master JQuery.

**Comment by pavelfeldman** [comment]
JQuery is largely thing of the past in the modern web.
