### ISSUE TITLE
[BUG] Test not found if sourceMap present in the compiled js file

### ISSUE THREAD

**Issue by StanislavKharchenko** [microsoft/playwright#27982]
### System info
- Playwright Version: [v1.39]
- Operating System: [macOS 12.7]
- Browser: [Chromium]

We have e2e infrastructure which run selenium-webdriver tests and we wanna to include wrappers to also run tests using playwright runner.
The flow is the next:
- compile typescript code with sourceMap=true (transpiled JS files will be located in the separate .dist folder);
- run transpiled JS test from .dist folder.

I've found similar issue but it was closed as not-reproduced in version 1.33
https://github.com/microsoft/playwright/issues/22123

If remove "//# sourceMappingURL..." from js file then it will work.
But, we need have ability to run js files from VS code debug with sourceMap enabled so breakpoints will stop on TS files

Example of folders structure:
```
.dist/
   tests/
      foo.js
tests/
  foo.ts
package.json
tsconfig.json
playwright.config.ts
```

Example of test is very simple:
```
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
    await page.goto('https://playwright.dev/');

    // Expect a title "to contain" a substring.
    await expect(page).toHaveTitle(/Playwright/);
});
```

The compiled JS test:

```
import { test, expect } from '@playwright/test';

test('has title', async ({ page }) => {
    await page.goto('https://playwright.dev/');
    await expect(page).toHaveTitle(/Playwright/);
});

//# sourceMappingURL=foo.js.map
```

tsconfig.ts 
```
{
  "compilerOptions": {
    "target": "ES2022",
    "esModuleInterop": true,
    "allowUnreachableCode": false,
    "allowSyntheticDefaultImports": true,
    "allowJs": false,
    "module": "ESNext",
    "moduleResolution": "Node",
    "declaration": false,
    "noImplicitAny": false,
    "types": [ "node", "jasmine" ],
    "useDefineForClassFields": false,
    "sourceMap": true,
    "outDir": ".dist",
    "rootDir": ".",
    "baseUrl": ".",
  },
  "include": [
    "./**/*.ts"
  ]
}
```

Playwright conf
```
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
    // Look for test files in the "tests" directory, relative to this configuration file.
    testDir: '.dist/tests',

    // Run all tests in parallel.
    //fullyParallel: true,

    // Fail the build on CI if you accidentally left test.only in the source code.
    forbidOnly: !!process.env.CI,
    testMatch: /.*\.*/,
    // Retry on CI only.
    retries: process.env.CI ? 2 : 0,

    // Opt out of parallel tests on CI.
    workers: process.env.CI ? 1 : undefined,

    // Reporter to use
    reporter: 'html',
    use: {
        headless: false,
    
        // Artifacts
        screenshot: 'on',
        video: 'on',
        contextOptions: {
            locale: 'ja-JP',
        }
    },
    projects: [
        {
            name: 'chromium',
            use: { ...devices['Desktop Chrome'] },
        },
    ]
});
```

Example of VS code launch.json
```
        {
            "env": {
                "NODE_OPTIONS": "--enable-source-maps" 
            },
            "name": "Launch test pl",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/.bin/playwright",
            "args": ["test", ".dist/tests/foo.js"],
            "sourceMaps": true,
            "console": "integratedTerminal",
            "resolveSourceMapLocations": ["**/*"]
        },
```

**Comment by dgozman** [comment]
@StanislavKharchenko When source maps are present, Playwright considers the original source name as the "test file name", and not the compiled file name from the `.dist`. Therefore, you should pass the `.ts` file as an argument:

```json
        {
            "env": {
                "NODE_OPTIONS": "--enable-source-maps" 
            },
            "name": "Launch test pl",
            "type": "node",
            "request": "launch",
            "program": "${workspaceRoot}/node_modules/.bin/playwright",
            "args": ["test", "tests/foo.ts"],
            "sourceMaps": true,
            "console": "integratedTerminal",
            "resolveSourceMapLocations": ["**/*"]
        },
```

Let me know whether this helps.

**Comment by StanislavKharchenko** [comment]
@dgozman I see, but this approach break another flow.
We have typescript imports without '.js' extension to our modules 
E.g.:

```
import module1 from @someModule/md1;
import module2 from @someModule/md2;

test('some test', async ({ page }) => {
       //some code here
});
```

And during project compilation our internal procedure set .js extension to all pathes (and make path resolving as well so all pathes are valid during nodejs runtime). After such actions we have fully compiled JS code which could run using e.g. jasmine/jest runner by the same way as you can execute any nodejs application. And we need the similar approach to run tests using playwright runner.

Without this approach, if we will rely on origin typescript files - we will have issues with file extensions (for esm projects with type "module").

`TypeError: Unknown file extension ".ts" for ****`

So, is it possible to run playwright tests using some another way after compilation typescript sources to JS (and debug them as well)?

**Comment by dgozman** [comment]
@StanislavKharchenko I am not sure that I understood you correctly, but here is how I can interpret your message.

You are worried that using original typescript files with Playwright will be an issue. First of all, Playwright works with TypeScript out of the box, unless you need some additional custom processing, which you might or might not need based on your description.

---

That said, the solution that I suggested that passes `"args": ["test", "tests/foo.ts"]` when launching does not really mean that Playwright is going to read your TypeScript files. Since you specify `testDir: '.dist/tests'` in your config, Playwright will only require your JavaScript files from the `.dist` directory.

However, you need to refer to specific tests by their original source file name as determined by the source map. We found that this compromise usually gives the best user experience, once you get used to always mentioning the source.

Let me know whether this works for you. And if it does not, a self-contained repro with the exact command you run and the error you get would be really helpful!

**Comment by StanislavKharchenko** [comment]
@dgozman Yes, this works. I was confused that in VS code debugger we need to pass origin test as TS file, however in playwright conf - path to JS folder. But, since this works, will close issue.

Thanks for help!
