### ISSUE TITLE
[BUG] Click doesn't work in Iframe from the 1.38.0 version and above

### ISSUE THREAD

**Issue by VAliashkevich** [microsoft/playwright#27987]
### System info
- Playwright Version: [v1.38.0 and above]
- Operating System: [Windows 11]
- Browser: [Chromium]
- Other info:

### Source code

**Iframe class file (self-contained)**

```ts
export class PurchaseAuthentication extends IFrame {
    private nextBtn = new BaseElement(
        this.page,
        'input[value="Next"]',
        'Next Button',
    );

    constructor(page: Page) {
        super(page, 'iframe[id="pa-form"]', 'Purchase Authentication');
    }

    async submitVerification() {
        await this.click(this.nextBtn);
    }
}


export class IFrame {
    protected readonly page: Page;
    protected readonly name: string;
    protected readonly frameLocator: FrameLocator;

    constructor(page: Page, selector: string, name: string) {
        this.page = page;
        this.frameLocator = this.page.frameLocator(selector);
        this.name = `${name} Frame`;
    }

    async click(element: BaseElement) {
        logger.info(`Clicking on ${element.name}`);
        await this.frameLocator.locator(element.getLocator()).click();
    }
}

```

I'm using the Next button click in the test, from version 1.38.0 the click doesn't work, Playwright finds the element and seems to click on it, but nothing happens
[failedTestTrace.zip](https://github.com/microsoft/playwright/files/13266341/failedTest.zip)

From version 1.37.0 and below the same code works correctly
[passedTestTrace.zip](https://github.com/microsoft/playwright/files/13266370/passedTest.zip)

**Comment by dgozman** [comment]
@VAliashkevich Unfortunately, I was not able to figure out the issue by looking at the trace. I guess something went wrong with submitting that form. Note that Playwright comes with fresh browser versions every time, so perhaps your site stopped working on the new Chromium?

We need more information to be able to act on this. Could you please provide a repro that we can run locally?

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
