### ISSUE TITLE
[BUG] Can't blur the window

### ISSUE THREAD

**Issue by dnsbty** [microsoft/playwright#27986]
### System info
- Playwright Version: v1.39.0
- Operating System: macOS 13.5.2
- Browser: Chromium
- Other info: Node v18.16.1

### Description

I manage a service that tokenizes sensitive data so that other applications don't have to handle that data. Those other applications will load an iframe that contains a single form field, and that field will be included in a larger form on the parent page. When the user blurs the frame, it will validate the data, send it to the tokenization backend, and then send the resulting token to the parent window. Here is a simplified example:

```html
<body>
  <form action="/tokenize">
    <input type="text" id="input">
  </form> 
  <script>
    window.addEventListener('blur', () => {
        const input = document.getElementById('input');
        if (typeof input.value === 'string' && input.value.length > 0) {
          const response = await fetch('/tokenize', {
            method: 'POST',
            body: JSON.stringify({
              value: input.value
            })
          });
          const { token } = response.json();
          window.parent.postMessage({ token }, '*');
        }
    })
  </script>
</body>
```

I would expect to be able to test this with something like this:

```js
it('submits the form on blur', async ({ page }) => {
  await page.goto(url);
  await page.locator('#input').click();
  await page.locator('#input').fill('Dennis Beatty');
  const responsePromise = page.waitForResponse('tokenize');
  await page.locator('window').blur();
  const response = await responsePromise;
  expect(response.ok()).toBeTruthy();
});
```

Instead, when the window is blurred, it appears to end the test:

<img width="497" alt="image" src="https://github.com/microsoft/playwright/assets/3421625/3f726dc5-876e-483c-8a2f-bd0d6df812d8">

It appears that this issue has been brought up before in #11645 and #15409 but the use cases outlined there were determined to be cases that Playwright didn't want to support. In this particular instance though, I think we are following the typical web testing use case.

**Comment by dgozman** [comment]
Playwright makes all windows always focused to avoid tabs backgrounding. Folding into #3570 that asks for a way to disable this.
