### ISSUE TITLE
[BUG] trace viewer UI showing blank page on remote host, only works with locally hosted reports

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#27981]
Reports with trace on feature coming properly in locally hosted reports, but when using ```npx playwright show-report **--host 0.0.0.0**```, video and test results worked fine except trace on and it was showing blank page.

Playwright's latest version: 1.39

If it is not a defect, Kindly share with me the guide where I am doing wrong.
![image](https://github.com/microsoft/playwright/assets/21674533/f8d14b16-561f-421d-9ea4-df94f62f405f)

**Comment by dgozman** [comment]
@iburahim786 You are probably accessing the report on non-secure location, like `http://<ip>:9323` which prevents the service worker from being registered, which is essential to the trace viewer. I'd recommend accessing the report at `http://localhost:9323` or `http://127.0.0.1:9323` that are considered secure.

**Comment by iburahim786** [comment]
How do I access the test reports over networks? Actually, here I am accessing the reports of all the pages like video, summary, and everything except trace viewer.  My question is why not give feasibility or enable access to trace viewers also?

You are given the option to see the reports from trace.playwright.dev URL.  Ideally accessing the Trace Viewer page from our local machine is more secure than accessing it from trace.playwright.dev.

If you want to make it more secure, bind all the IP addresses of servers where we are running - Which is also considered to be secure.

And one more thing, I can download Playwright test report files from an Ubuntu box and access them from my local Windows box through http://localhost:9323  - This is quite possible and it should work.  I am not very sure what you meant by secure accessing the trace viewer page via localhost.

Note: I am running automation in one of my Jenkins slave - Ubuntu box and trying to access the reports over the network using --host 0.0.0.0.

**Comment by dgozman** [comment]
@iburahim786 That's just how browsers work. Trace viewer requires registering a service worker, and browser prohibit service workers on "untrusted origins". This includes all http urls except localhost-like. It's not that Playwright is doing anything special here, so I don't think we'll be able to help.

**Comment by iburahim786** [comment]
I am really interested to know more about the trace viewer. If this is browser-specific - can you suggest me a link to know more about this?

**Comment by dgozman** [comment]
@iburahim786 I am not really sure how to help you. We are open source, so you can see the [trace viewer code here](https://github.com/microsoft/playwright/tree/main/packages/trace-viewer). Perhaps the [MDN article about Service Workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API) would be also helpful?

I don't see an action item for Playwright here, so closing the issue. If you encounter any bugs, please file a new issue by following the "Bug Report" template.
