### ISSUE TITLE
Closing as per above, please feel free to open a new issue if this does not cover your use case.

### ISSUE THREAD

**Issue by ayushshrivastava28** [microsoft/playwright#27980]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

_Originally posted by @pavelfeldman in https://github.com/microsoft/playwright/issues/27950#issuecomment-1793859861_

**Comment by ayushshrivastava28** [comment]
But what if we have a legacy code which uses lot of requires and its not possible to change it to import. We do have babel to transpile our es5 code still its unable to find reference for require(). Why don't we add support for es5 on playwright

**Comment by ayushshrivastava28** [comment]
@pavelfeldman can you suggest any other way to fix require issues if can't manually remove the require() from the code. ?

**Comment by mxschmitt** [comment]
Can you provide us a repro which we can run locally?

**Comment by ayushshrivastava28** [comment]
That repo can't be used outside the organisation. 
To recreate the issue you can create a file which has es5 module
you can import that file using require('./path-of-your-es5-module')
Now in whichever file you are running your test using above file and run it as follow
yarn test "path-of-your-test-file"

when you run playwright will create a .cache file inside your playwright folder and you will find error
ReferenceError: require is not defined
One similar issue is this https://github.com/microsoft/playwright/issues/24366 
but you have asked them to change it to import instead of require() 
for us we don' t want to change to import. How can we achieve it now?
Did you understand the issue ?

**Comment by dgozman** [comment]
@ayushshrivastava28 To make progress on this issue, we have to ask for a small repro that we can run locally. Unfortunately, we do not have enough bandwidth to come up with a repro ourselves.

Bugs without a repro are much less likely to be prioritized and fixed, and most likely will be closed as non-actionable.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
