### ISSUE TITLE
[BUG] --disable-web-security is not working as expected for Same Origin Policy - Playwright/Java

### ISSUE THREAD

**Issue by kherath17** [microsoft/playwright#27989]
### System info
- Playwright Version: [1.29.0]
- Operating System: [Windows 11]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
String[] chromiumArgs = new String[]{"--disable-web-security"};
        switch (browserName.toLowerCase()) {
             case "chrome":
                this.browser = ((Playwright)this.playwright.get()).chromium().launch((new BrowserType.LaunchOptions()).setChannel("chrome").setHeadless(PlayWrightConstants.HEADLESS_MODE).**_setArgs(Arrays.asList(chromiumArgs)));_**

**Steps**
Above Code snippet is configured in a wrapper framework I have developed, but it doesnt disable the web security

**Expected**

Should Disable Web Security

**Actual**

![image](https://github.com/microsoft/playwright/assets/54758666/569fa21e-e6ae-4fc0-9d64-1495ee34c7d1)

**Comment by dgozman** [comment]
@kherath17 If you go to `chrome://version`, do you see `--disable-web-security` in the `Command Line:` field?

If so, that means Chrome does not treat it the way you'd like. I don't think Playwright can or should do anything about that.

**Comment by kherath17** [comment]
@dgozman  Following is my command line and it contains `--disable-web-security`, but this seems to work with Python, JS, and TS, the only issue is with Java, the issue has been already discussed on the Playwright-Java but no resolution https://github.com/microsoft/playwright-java/issues/907

Furthermore, tried with `setIgnoreAllDefaultArgs()` as well which runs into a halt and stops working. 

**Command Line :**

"C:\Program Files\Google\Chrome\Application\chrome.exe" --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --disable-web-security --no-sandbox --start-maximized --ignore-certificate-errors --pageloadstrategy.normal --user-data-dir="C:\Users\KASUNH~1\AppData\Local\Temp\playwright_chromiumdev_profile-kbc6cd" --remote-debugging-pipe --no-startup-window --flag-switches-begin --flag-switches-end --disable-nacl

**Comment by dgozman** [comment]
@kherath17 Unfortunately, I don't think we'll be able to help here. It looks like Playwright passes your arguments to the browser as expected. However, we cannot guarantee that browser works with these arguments as you'd like. Debugging this is out of scope of Playwright project, so I'll have to close the issue without a resolution.
