### ISSUE TITLE
[Question] How to validate `301` status using `request.fetch()`?

### ISSUE THREAD

**Issue by CoreyGahafer** [microsoft/playwright#27992]
Currently, I'm trying to figure out how to test for the `301` redirect, but I'm unable to capture the `301` request that occurs when fetching a route that redirects. I can see the `301` occur in the network tab when running the tests with the UI mode, but I haven't been able to figure out how to capture the `301` request that occurs so that I can inspect it.

**UI Mode:**
![image](https://github.com/microsoft/playwright/assets/26581947/012167ca-dcde-4b76-a004-12e66c8adf8a)

**Examples:**
```Javascript
import { test } from '@playwright/test';

test('should redirect to as expected', async ({ context }) => {
  context.on('request', request => console.log('>>', request.method(), request.url()));
  context.on('response', response => console.log('<<', response.status(), response.url()));

  const response = await request.fetch('https://shorturl.at/gmsOR');
  console.log(response);
});

test('should redirect to as expected', async ({ request }) => {
  const response = await request.fetch('https://shorturl.at/gmsOR');
  console.log(response);
});
```

In both of these cases, I get back the following `200` response from the site that the original request is redirected to, but unable to capture any of the other requests prior to this.

```
APIResponse: 200 OK
  Content-Type: text/html; charset=UTF-8
  Strict-Transport-Security: max-age=31536000
  Content-Security-Policy-Report-Only: object-src 'none';base-uri 'self';script-src 'nonce-NFUUXIv37m2sBZfGi33UVQ' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
  P3P: CP="This is not a P3P policy! See g.co/p3phelp for more info."
  Content-Encoding: gzip
  Date: Mon, 06 Nov 2023 16:36:19 GMT
  Server: gws
  Cache-Control: private
  X-XSS-Protection: 0
  X-Frame-Options: SAMEORIGIN
  Expires: Mon, 06 Nov 2023 16:36:19 GMT
  Set-Cookie: 1P_JAR=2023-11-06-16; expires=Wed, 06-Dec-2023 16:36:19 GMT; path=/; domain=.google.com; Secure; SameSite=none
  Set-Cookie: AEC=Ackid1Rfeayg8raPAMnywyJ6RdO9xh-49d6PIWY4xmroQGzIuVdPyRk32w; expires=Sat, 04-May-2024 16:36:19 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
  Set-Cookie: NID=511=YnOdBrF7j2Yw8iLV5BsySDs9cKbkc1QrnAq2CYbD7sesh4vUdpoyWeEiEmFipc1cw55C4Idh5HQpv4kZ2jTGS5A2T3v14ewrF71XHD-7niCREDhFnah13JD0K_9NE1Bgi6x0nlXycbXqk8bavrdnU6rT16IjJfwAB2QoSxSUWRg; expires=Tue, 07-May-2024 16:36:19 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=none
  Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
  Connection: close
  Transfer-Encoding: chunked

**Comment by dgozman** [comment]
@CoreyGahafer Pass [`maxRedirects` option](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch-option-max-redirects):

```ts
const response = await request.fetch('https://shorturl.at/gmsOR', { maxRedirects: 0 });
```

Let me know whether this helps.

**Comment by CoreyGahafer** [comment]
> @CoreyGahafer Pass [`maxRedirects` option](https://playwright.dev/docs/api/class-apirequestcontext#api-request-context-fetch-option-max-redirects):
> 
> ```ts
> const response = await request.fetch('https://shorturl.at/gmsOR', { maxRedirects: 0 });
> ```
> 
> Let me know whether this helps.

@dgozman this was exactly the missing piece I needed, thank you!!
