### ISSUE TITLE
[BUG] Playwright-Java: Getting 'browser.newContext: Target page, context or browser has been closed' error

### ISSUE THREAD

**Issue by sheekha-jain** [microsoft/playwright#27997]
System info
- Playwright Version: [v1.39]
- Operating System: [Windows 11 Pro]
- Browser: [Chrome]
- Other info: [Java (Open JDK)- v11.0.1]

Issue Description:  I am getting  'browser.newContext: Target page, context or browser has been closed' error randomly while executing a simple scenario. I am new to Playwright and while automating below scenario , I am getting this error randomly when new window tab is opened. PFB detailed steps below:

**Steps**
1. Login to serviceNow application.
2. In All-->Type 'portal' in the search box and click OK
3. This will open a new tab for serviceNow portal.

**Expected**
ServiceNow portal UI will be opened in a new tab

**Actual**
Sometimes the page is getting crashed with 'browser.newContext: Target page, context or browser has been closed' error:

**Comment by dgozman** [comment]
@sheekha-jain Most likely, the browser crashes while loading your page. There's not much else I can help with, if you do not provide a repro that we can run locally.

**Comment by mikicymulate** [comment]
Happens to me too
Chrome  Version 119.0.6045.106
"@playwright/test": "^1.40.0-alpha-nov-7-2023" /  "1.39.0"

`  pw:browser <launching> C:\Users\MichaelBehnam\AppData\Local\ms-playwright\chromium-1087\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate,HttpsUpgrades --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --disable-search-engine-choice-screen --user-data-dir=C:\Users\MICHAE~1\AppData\Local\Temp\playwright_chromiumdev_profile-YRmbL0 --remote-debugging-pipe --no-startup-window +0ms
  pw:browser <launched> pid=7244 +11ms
  pw:browser [pid=7244][err] [7244:22376:1107/181113.403:ERROR:policy_logger.cc(157)] :components\enterprise\browser\controller\chrome_browser_cloud_management_controller.cc(163) Cloud management controller initialization aborted as CBCM is not enabled. +327ms
  pw:browser [pid=7244][err] [7244:22264:1107/181117.123:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER): +4s
  pw:browser [pid=7244][err] ERROR: Couldn't read tbsCertificate as SEQUENCE +0ms                                                                                                                                                    
  pw:browser [pid=7244][err] ERROR: Failed parsing Certificate +0ms                                                                                                                                                                  
  pw:browser [pid=7244][err]  +0ms                                                                                                                                                                                                   
  pw:browser [pid=7244][err] [7244:22376:1107/181120.536:ERROR:device_event_log_impl.cc(192)] [18:11:20.536] USB: usb_service_win.cc:415 Could not read device interface GUIDs: The system cannot find the file specified. (0x2) +3s 
  pw:browser [pid=7244][err] [7244:22376:1107/181120.542:ERROR:usb_descriptors.cc(141)] Failed to read length for configuration 1. +6ms                                                                                              
  pw:browser [pid=7244][err] [7244:22376:1107/181120.542:ERROR:usb_descriptors.cc(100)] Failed to read all configuration descriptors. Expected 2, got 1. +0ms                                                                        
  pw:browser [pid=7244][err] [7244:22376:1107/181120.542:ERROR:device_event_log_impl.cc(192)] [18:11:20.542] USB: usb_device_win.cc:95 Failed to read descriptors from \\?\usb#vid_0bda&pid_8153#001000001#{a5dcbf10-6530-11d2-901f-00c04fb951ed}. +0ms
Test name: Test_10 Get advanced scenarios report info, find and compare the info to the findings data: -Finding overview- @Amit_team @sanityForAllModules @jenkins_fast

  pw:browser [pid=7244][err] [7244:22264:1107/181156.348:ERROR:cert_issuer_source_aia.cc(34)] Error parsing cert retrieved from AIA (as DER): +36s
  pw:browser [pid=7244][err] ERROR: Couldn't read tbsCertificate as SEQUENCE +0ms                                                                                                                                                    
  pw:browser [pid=7244][err] ERROR: Failed parsing Certificate +0ms                                                                                                                                                                  
  pw:browser [pid=7244][err]  +0ms                                                                                                                                                                                                   
  pw:browser [pid=7244][err] [11468:43108:1107/181156.602:FATAL:delay_load_failure_support.cc(31)] Check failed: false.  +280ms
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F07B5002+147298] +0ms                                                                                                                                                          
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F52CEBE2+16303314] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44D545A+1649994] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44D6300+1653744] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44EEDD1+1754817] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F33D9675+17752165] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F33D9556+17751878] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8FA8D090C+81530540] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8FA93886C+81956364] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4991F56+6617158] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F6D0916E+18847502] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F5C61412+1382834] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F1114499+9974777] +0ms                                                                                                                                                         
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4D81379+10742889] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4D811E0+10742480] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7697FD7+28870007] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F76979AF+28868431] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7623AE3+28393603] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7625CD5+28402293] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7627CE1+28410497] +1ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F6F28B44+21074148] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F08A4E29+1129865] +0ms                                                                                                                                                         
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F46F058B+3858043] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F37F1+4919521] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F39CA+4919994] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F3A95+4920197] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44894B8+1338792] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F547849F+115487] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5477DBD+113725] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5489125+184229] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5478F64+118244] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44A71AB+1460891] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F522017F+15587951] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D36C22+27571730] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D3799C+27575180] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D361B5+27569061] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D3646A+27569754] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F0791390+752] +0ms                                                                                                                                                             
  pw:browser [pid=7244][err]    GetPakFileHashes [0x00007FF6C0C9293E+6462] +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]    GetPakFileHashes [0x00007FF6C0C91A6F+2671] +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF6C0DF82B2+898034] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    BaseThreadInitThunk [0x00007FF9F7AD257D+29] +0ms                                                                                                                                                     
  pw:browser [pid=7244][err]    RtlUserThreadStart [0x00007FF9F950AA78+40] +0ms                                                                                                                                                      
  pw:browser [pid=7244][err] Task trace: +0ms                                                                                                                                                                                        
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F38ED+4919773] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err] Crash keys: +0ms                                                                                                                                                                                        
  pw:browser [pid=7244][err]   "DelayLoad-ModuleName" = "USER32.dll" +0ms                                                                                                                                                            
  pw:browser [pid=7244][err]   "discardable-memory-free" = "11108352" +0ms                                                                                                                                                           
  pw:browser [pid=7244][err]   "discardable-memory-allocated" = "11390976" +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]   "gpu-generation-intel" = "12" +0ms                                                                                                                                                                    
  pw:browser [pid=7244][err]   "gpu-vsver" = "5.0" +0ms                                                                                                                                                                              
  pw:browser [pid=7244][err]   "gpu-psver" = "5.0" +0ms                                                                                                                                                                              
  pw:browser [pid=7244][err]   "gpu-driver" = "31.0.101.4255" +0ms                                                                                                                                                                   
  pw:browser [pid=7244][err]   "gpu-rev" = "1" +0ms                                                                                                                                                                                  
  pw:browser [pid=7244][err]   "gpu-subid" = "0x22cb17aa" +0ms                                                                                                                                                                       
  pw:browser [pid=7244][err]   "gpu_count" = "2" +0ms                                                                                                                                                                                
  pw:browser [pid=7244][err]   "gpu-devid" = "0x9a49" +0ms                                                                                                                                                                           
  pw:browser [pid=7244][err]   "gpu-venid" = "0x8086" +1ms                                                                                                                                                                           
  pw:browser [pid=7244][err]   "view-count" = "1" +0ms                                                                                                                                                                               
  pw:browser [pid=7244][err]   "loaded-origin-0" = "https://app.cymulate.com" +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]   "web-frame-count" = "6" +0ms                                                                                                                                                                          
  pw:browser [pid=7244][err]   "renderer_foreground" = "true" +0ms                                                                                                                                                                   
  pw:browser [pid=7244][err]   "v8_ro_space_firstpage_address" = "0x30a00000000" +0ms                                                                                                                                                
  pw:browser [pid=7244][err]   "v8_isolate_address" = "0xd980080c000" +0ms                                                                                                                                                           
  pw:browser [pid=7244][err]   "variations" = "5e3a236d-59e286d0," +0ms                                                                                                                                                              
  pw:browser [pid=7244][err]   "num-experiments" = "1" +0ms                                                                                                                                                                          
  pw:browser [pid=7244][err]   "reentry_guard_tls_slot" = "unused" +0ms                                                                                                                                                              
  pw:browser [pid=7244][err]   "switch-19" = "--field-trial-handle=1952,i,14116009138538885456,145930369958662" +0ms                                                                                                                 
  pw:browser [pid=7244][err]   "switch-18" = "--mojo-platform-channel-handle=3756" +0ms                                                                                                                                              
  pw:browser [pid=7244][err]   "switch-17" = "--launch-time-ticks=1077482433883" +0ms                                                                                                                                                
  pw:browser [pid=7244][err]   "switch-16" = "--time-ticks-at-unix-epoch=-1698295991113988" +0ms                                                                                                                                     
  pw:browser [pid=7244][err]   "switch-15" = "--renderer-client-id=5" +0ms                                                                                                                                                           
  pw:browser [pid=7244][err]   "switch-14" = "--enable-main-frame-before-activation" +0ms                                                                                                                                            
  pw:browser [pid=7244][err]   "switch-13" = "--num-raster-threads=4" +0ms                                                                                                                                                           
  pw:browser [pid=7244][err]   "switch-12" = "--device-scale-factor=1" +0ms                                                                                                                                                          
  pw:browser [pid=7244][err]   "switch-11" = "--lang=en-US" +0ms                                                                                                                                                                     
  pw:browser [pid=7244][err]   "switch-10" = "--disable-databases" +0ms                                                                                                                                                              
  pw:browser [pid=7244][err]   "switch-9" = "--allow-pre-commit-input" +0ms                                                                                                                                                          
  pw:browser [pid=7244][err]   "switch-8" = "--remote-debugging-pipe" +0ms                                                                                                                                                           
  pw:browser [pid=7244][err]   "switch-7" = "--force-color-profile=srgb" +0ms                                                                                                                                                        
  pw:browser [pid=7244][err]   "switch-6" = "--file-url-path-alias=/gen=C:\Users\MichaelBehnam\AppData\Local\" +0ms                                                                                                                  
  pw:browser [pid=7244][err]   "switch-5" = "--enable-automation" +0ms                                                                                                                                                               
  pw:browser [pid=7244][err]   "switch-4" = "--disable-breakpad" +0ms                                                                                                                                                                
  pw:browser [pid=7244][err]   "switch-3" = "--disable-background-timer-throttling" +0ms                                                                                                                                             
  pw:browser [pid=7244][err]   "switch-2" = "--disable-back-forward-cache" +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]   "switch-1" = "--user-data-dir=C:\Users\MICHAE~1\AppData\Local\Temp\playwright_" +0ms                                                                                                                  
  pw:browser [pid=7244][err]   "num-switches" = "23" +0ms                                                                                                                                                                            
  pw:browser [pid=7244][err]   "commandline-disabled-feature-12" = "Translate" +0ms                                                                                                                                                  
  pw:browser [pid=7244][err]   "commandline-disabled-feature-11" = "MediaRouter" +0ms                                                                                                                                                
  pw:browser [pid=7244][err]   "commandline-disabled-feature-10" = "LazyFrameLoading" +0ms                                                                                                                                           
  pw:browser [pid=7244][err]   "commandline-disabled-feature-9" = "ImprovedCookieControls" +0ms                                                                                                                                      
  pw:browser [pid=7244][err]   "commandline-disabled-feature-8" = "HttpsUpgrades" +0ms                                                                                                                                               
  pw:browser [pid=7244][err]   "commandline-disabled-feature-7" = "GlobalMediaControls" +0ms                                                                                                                                         
  pw:browser [pid=7244][err]   "commandline-disabled-feature-6" = "DialMediaRouteProvider" +0ms                                                                                                                                      
  pw:browser [pid=7244][err]   "commandline-disabled-feature-5" = "DestroyProfileOnBrowserClose" +0ms                                                                                                                                
  pw:browser [pid=7244][err]   "commandline-disabled-feature-4" = "CertificateTransparencyComponentUpdater" +0ms                                                                                                                     
  pw:browser [pid=7244][err]   "commandline-disabled-feature-3" = "AvoidUnnecessaryBeforeUnloadCheckSync" +0ms                                                                                                                       
  pw:browser [pid=7244][err]   "commandline-disabled-feature-2" = "AutoExpandDetailsElement" +0ms                                                                                                                                    
  pw:browser [pid=7244][err]   "commandline-disabled-feature-1" = "AcceptCHFrame" +0ms                                                                                                                                               
  pw:browser [pid=7244][err]   "commandline-enabled-feature-2" = "NetworkServiceInProcess" +1ms                                                                                                                                      
  pw:browser [pid=7244][err]   "commandline-enabled-feature-1" = "NetworkService" +0ms                                                                                                                                               
  pw:browser [pid=7244][err]  +0ms                                                                                                                                                                                                   
  pw:browser [pid=7244][err] Received fatal exception EXCEPTION_BREAKPOINT +2ms                                                                                                                                                      
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44D5D16+1652230] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44D6300+1653744] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44EEDD1+1754817] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F33D9675+17752165] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F33D9556+17751878] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8FA8D090C+81530540] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8FA93886C+81956364] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4991F56+6617158] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F6D0916E+18847502] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F5C61412+1382834] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F1114499+9974777] +0ms                                                                                                                                                         
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4D81379+10742889] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F4D811E0+10742480] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7697FD7+28870007] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F76979AF+28868431] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7623AE3+28393603] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7625CD5+28402293] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F7627CE1+28410497] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    sqlite3_dbdata_init [0x00007FF8F6F28B44+21074148] +0ms                                                                                                                                               
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F08A4E29+1129865] +0ms                                                                                                                                                         
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F46F058B+3858043] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F37F1+4919521] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F39CA+4919994] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F47F3A95+4920197] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44894B8+1338792] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F547849F+115487] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5477DBD+113725] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5489125+184229] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF8F5478F64+118244] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F44A71AB+1460891] +0ms                                                                                                                                                 
  pw:browser [pid=7244][err]    IsSandboxedProcess [0x00007FF8F522017F+15587951] +0ms                                                                                                                                                
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D36C22+27571730] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D3799C+27575180] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D361B5+27569061] +0ms                                                                                                                       
  pw:browser [pid=7244][err]    CrashForExceptionInNonABICompliantCodeRange [0x00007FF8F3D3646A+27569754] +0ms
  pw:browser [pid=7244][err]    ChromeMain [0x00007FF8F0791390+752] +0ms                                                                                                                                                             
  pw:browser [pid=7244][err]    GetPakFileHashes [0x00007FF6C0C9293E+6462] +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]    GetPakFileHashes [0x00007FF6C0C91A6F+2671] +0ms                                                                                                                                                      
  pw:browser [pid=7244][err]    GetHandleVerifier [0x00007FF6C0DF82B2+898034] +0ms                                                                                                                                                   
  pw:browser [pid=7244][err]    BaseThreadInitThunk [0x00007FF9F7AD257D+29] +0ms                                                                                                                                                     
  pw:browser [pid=7244][err]    RtlUserThreadStart [0x00007FF9F950AA78+40] +0ms                                                                                                                                                      
  pw:browser [pid=7244] <gracefully close start> +3s
  pw:browser [pid=7244] <process did exit: exitCode=0, signal=null> +108ms
  pw:browser [pid=7244] starting temporary directories cleanup +0ms                                                                                                                                                                  
  pw:browser [pid=7244] finished temporary directories cleanup +38ms
  pw:browser [pid=7244] <gracefully close end> +0ms                                                                                                                                                                                  
  1) [e2e_automation] › src\tests\functionality\globalFindings\globalFindings.spec.ts:432:10 › Test suite: Global Findings - IN PARALLEL › Test_10 Get advanced scenarios report info, find and compare the info to the findings data: -Finding overview- @Amit_team @sanityForAllModules @jenkins_fast › Check left side techniques mitre links - Techniques

    Error: ERROR in verifyLocatorExists - did NOT find :  (//div[@data-testid='data-row' and .//*[contains(text(), 'Techniques')]]//button/span)[1]
     Error: page.waitForSelector: Target crashed
    Call log:
      - waiting for locator('xpath=(//div[@data-testid=\'data-row\' and .//*[contains(text(), \'Techniques\')]]//button/span)[1]') to be visible
`

**Comment by dudilugasi** [comment]
+1

**Comment by akawebstrom1** [comment]
I is an issue for me too!! please solve it ASAP

**Comment by MichaelBehnam** [comment]
@dgozman 
+1

**Comment by dgozman** [comment]
Does anyone have a crash id on the `chrome://crashes/` page? If not, could you please run with `channel: "chrome"` (or `setChannel("chrome")` for java) and see whether the issue persists?

**Comment by dgozman** [comment]
Upstream Chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=1500381.

**Comment by mikicymulate** [comment]
@dgozman 

`Status:	Upload requested by user
Crash from Wednesday, November 8, 2023 at 7:38:50 AM
Status:	Uploaded
Uploaded Crash Report ID:	3a517247e19bda42
Upload Time:	Wednesday, November 8, 2023 at 7:38:51 AM
`

**Comment by sheekhajain-TU** [comment]
@dgozman
Crash from Thursday, September 7, 2023 at 1:22:14 PM
Status: | Not uploaded
Local Crash Context: | a99005ef-7748-49d6-897d-07f430959b10

**Comment by mikicymulate** [comment]
@sheekhajain-TU 
You need to upload the crash for them to see

**Status:	Uploaded
Uploaded Crash Report ID: XXXXX**

**Comment by sheekhajain-TU** [comment]
Hi @mikicymulate ,

Its uploaded now.
Crash from Thursday, September 7, 2023 at 1:22:14 PM

Status:  Uploaded
Uploaded Crash Report ID:  7f608a31eb1fad6c
Upload Time:  Wednesday, November 8, 2023 at 11:38:22 AM
Local Crash Context:  a99005ef-7748-49d6-897d-07f430959b10

**Comment by sheekha-jain** [comment]
Hi @mikicymulate ,

Its uploaded now.
Crash from Thursday, September 7, 2023 at 1:22:14 PM

Status: Uploaded
Uploaded Crash Report ID: 7f608a31eb1fad6c
Upload Time: Wednesday, November 8, 2023 at 11:38:22 AM
Local Crash Context: a99005ef-7748-49d6-897d-07f430959b10

**Comment by dgozman** [comment]
@mikicymulate Thank you for confirming the crash id, let's follow https://bugs.chromium.org/p/chromium/issues/detail?id=1500381 for the Chromium fix.

**Comment by sheekha-jain** [comment]
Hi @dgozman ,

Thanks for your help!! 

Do we have any SLA from them for the fix? Or if you can share any workaround to avoid this issue as it is currently impacting my execution due to random page crash.

**Comment by mikicymulate** [comment]
you can use FireFox :
`channel: "firefox",
  ...devices["Desktop Firefox"],`

**Comment by sheekha-jain** [comment]
Hi @mikicymulate,

Unfortunately most of the applications needs to be tested only on chrome version. So, this doesn't really solve my purpose.

**Comment by alisonmaher** [comment]
@sheekha-jain @dgozman [a fix for the bug has landed Canary](https://bugs.chromium.org/p/chromium/issues/detail?id=1500381#c2) - is it possible for someone here to test latest Chrome Canary to see if the playwright scenario is also fixed? If all looks good, we will plan to start the cherry-pick process. Thanks for reporting the issue!

**Comment by dgozman** [comment]
@alisonmaher So far, we did roll the `chromium-tip-of-tree` channel from the `121.0.6117.0` tag. I am not sure whether it has the fix, but tomorrow we will auto-roll `121.0.6118.0`, and anyone experiencing this issue will be able to give it a try.

**Comment by alisonmaher** [comment]
It looks like the fix landed in `121.0.6117.0` (https://chromiumdash.appspot.com/commit/0beb9ed81e28019956b8bd6f6e4f011ea9c39bfd)

**Comment by dgozman** [comment]
@mikicymulate Could you please run `npm install @playwright/test@next`, then `npx playwright install chromium-tip-of-tree` and then run your tests with `use: { channel: 'chromium-tip-of-tree' }`? This will pick up the latest Chromium roll that supposedly contains a fix, and you could tell us whether the problem is fixed. Thank you!

**Comment by sheekha-jain** [comment]
Hi @dgozman,

Could you please let me know similar steps for playwright-java. So that I can validate it at my end as well.
I tried below and getting error:
1. Install chromium-tip-of-tree --> Chromium Version 116.0.5805.0 installed on local
```mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium-tip-of-tree"```
2. Update setChannel to chromium-tip-of-tree
```Browser browser = playwright.chromium().launch(new BrowserType.LaunchOptions()
                    .setChannel("chromium-tip-of-tree")
                    .setHeadless(false));```
3. Run the test

Actual : Below error is thrown:
name='Error
  stack='Error: Executable doesn't exist at *\AppData\Local\ms-playwright\chromium_tip_of_tree-1158\chrome-win\chrome.exe
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║ Looks like Playwright was just installed or updated.                                                                                                    ║
║ Please run the following command to download new browser:                                                                                  ║
║                                                                                                                                                                                       ║
║     mvn exec:java -e -D exec.mainClass=com.microsoft.playwright.CLI -D exec.args="install chromium-tip-of-tree" ║
║                                                                                                                                                                                       ║
║ <3 Playwright Team                                                                                                                                                      ║

Note: chromium_tip_of_tree-1120 is present at following path *\AppData\Local\ms-playwright\

**Comment by dgozman** [comment]
@sheekha-jain We do not have canary releases for playwright-java, so it would not install the new chromium-tip-of-tree build anyway. Sorry.

**Comment by alisonmaher** [comment]
@dgozman does this mean that you won't be able to test the playwright scenario on latest Canary?

**Comment by dgozman** [comment]
@alisonmaher I hope that @mikicymulate will be able to check on their end.

**Comment by mikicymulate** [comment]
@dgozman 
The Chrome browser **didn't crash** as before on :
`chromium-tip-of-tree`  -->  chromium `Version 121.0.6117.0 (Developer Build) (64-bit)`
playwright/test@next  --> `1.40.0-alpha-nov-11-2023`
as you asked me to check.

Does this mean that there will be **no** fix in the next 1.5 months?

**Comment by alisonmaher** [comment]
@mikicymulate thanks for confirming! We will work on cherry picking the fix to at least 120. Will see if this meets the bar for 119.

**Comment by sheekha-jain** [comment]
Hi @dgozman ,

Is there any way through which this issue can be ignored until the fix is delivered? We were planning to move from Selenium to Playwright due to its amazing features but encountered this page crash issue in our initial stage itself. 

Please suggest if anything can be done to temporarily resolve this issue for playwright-java like using any particular chrome version etc.

**Comment by dgozman** [comment]
@sheekha-jain The bug is present in Chromium 119 and later, so the workaround is to use an older Playwright version, for example v1.38, which comes with Chromium 118. Once the Chromium issue is fixed, you should be able to upgrade to a newer Playwright version.

**Comment by sheekha-jain** [comment]
Ok great.

Thanks for the help @dgozman !! I will use older version until the bug is fixed.

**Comment by dgozman** [comment]
This should be fixed in the latest v1.40 release.

**Comment by tanyatech301** [comment]
Still seeing this issue on 1.46 - how can we fix this?

**Comment by ekams1** [comment]
Any solution to it?? I am facing this error. We use v1.28 in company but since I needed CDP so I upgraded to v1.37, v1.40 and v1.41. I get the same error for all of them. Any fix?

**Comment by mr-v-v-v** [comment]
please fix it ASAP)

**Comment by Runhilia** [comment]
Hey, I always have the error when I use playwright with docker without the headless option and I can't get xvfb to work.  Anyone have a fix ?

**Comment by matheusfterra** [comment]
+1 running in docker headless and have this issue

**Comment by LinkerM** [comment]
+I also encountered this problem in the Docker environment

**Comment by mevinbabuc** [comment]
same here

**Comment by princebhatia1996** [comment]
I am getting the same issue. Is there any fix or a workaround for now?

**Comment by lzanchin** [comment]
We're getting the same issue. In one of my investigations, I encountered the issue while running a page.waitForTimeOut, which is kind of ridiculous if you think about it.
It would be nice if we could at least get a confirmation that the issue is being looked at.

**Comment by devendergagra** [comment]
I'm encountering the same issue, which is preventing the job from stopping automatically. I have to manually abort it.

**Comment by rhawiz** [comment]
In my Dockerfile adding these env fixed it for me:

ENV XDG_CONFIG_HOME=/tmp/.chromium
ENV XDG_CACHE_HOME=/tmp/.chromium
