### ISSUE TITLE
[BUG] When using baseUrl, "Rollup failed to resolve import"

### ISSUE THREAD

**Issue by jacobweber** [microsoft/playwright#27993]
### System info
- Playwright Version: [@playwright/experimental-ct-react ^1.39.0]
- Operating System: [macOS 14.1]
- Browser: [Chromium]
- Other info:

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**
[my-vite-app.tar.gz](https://github.com/microsoft/playwright/files/13270108/my-vite-app.tar.gz)

**Steps**
- Create app:
```
nvm use 16
npm create vite@latest my-vite-app -- --template react-ts
cd my-vite-app
npm i
npm init playwright@latest -- --ct
```
- Set `"baseUrl": "./src"` in `tsconfig.json`.
- Add `App.spec.ts`, which includes a `import App from 'App';`
- Run tests with `npm run test-ct`.

**Expected**

Test runs successfully.

**Actual**

Exception:
```
Error: [vite]: Rollup failed to resolve import "App" from "/my-vite-app/playwright/index.tsx".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`

    at viteWarn (/my-vite-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48216:27)
    at onwarn (/my-vite-app/node_modules/@vitejs/plugin-react/dist/index.mjs:249:9)
    at onRollupWarning (/my-vite-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:48245:9)
    at onwarn (/my-vite-app/node_modules/vite/dist/node/chunks/dep-bb8a8339.js:47976:13)
    at /my-vite-app/node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger (/my-vite-app/node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (/my-vite-app/node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at ModuleLoader.resolveDynamicImport (/my-vite-app/node_modules/rollup/dist/es/shared/node-entry.js:24920:58)
    at /my-vite-app/node_modules/rollup/dist/es/shared/node-entry.js:24807:32
```

**Comment by dgozman** [comment]
@jacobweber You have to configure [vite aliases](https://vitejs.dev/config/shared-options.html#resolve-alias) separately from `tsconfig`. Take a look at [this example](https://playwright.dev/docs/test-components#i-have-a-project-that-already-uses-vite-can-i-reuse-the-config). Let me know whether this helps.

**Comment by jacobweber** [comment]
Thanks @dgozman, that does work (if I list all the subdirectories of my base dir as aliases). I was thinking it worked with tsconfig's baseUrl, based on [this](https://playwright.dev/docs/test-typescript#tsconfigjson) (but maybe that doesn't apply to component tests?)

**Comment by dgozman** [comment]
@jacobweber Yeah, this documentation is about e2e tests. We should improve our components documentation for sure!

**Comment by atsolberg** [comment]
Coming from a remix app that aliases the `app` directory to `~` this worked for me:
```js
use: {
  ctViteConfig: {
    resolve: {
      alias: {
        '~': resolve(__dirname, './app'),
      },
    },
  },
},
```

**Comment by SDxBacon** [comment]
> Coming from a remix app that aliases the `app` directory to `~` this worked for me:
> 
> ```js
> use: {
>   ctViteConfig: {
>     resolve: {
>       alias: {
>         '~': resolve(__dirname, './app'),
>       },
>     },
>   },
> },
> ```

@atsolberg Could you please share where you placed these configurations to make Playwright work?

I'm having trouble configuring Playwright in my React project, which is a pure React setup without using any template.
I've organized my project as follows:
```tree
.
├── src
│   ├── views
│   ├── components
│   └── App.spec.js
├── playwright-ct.config.js
├── webpack.config.js
└── jsconfig.json
```

In my project, I will import files that inside `src/components` like:
```js
import SomeComponent from '@/components/SomeComponent';
```
Thus, I create an `vite.config.js` trying to configure playwright 
```js
// vite.config.js
import { resolve } from 'path';
import { defineConfig } from '@playwright/experimental-ct-react';

export default defineConfig({
  use: {
    ctViteConfig: {
      resolve: {
        alias: {
          '@': resolve(__dirname, './src'),
        },
      },
    },
  },
});

```

However, even after executing `yarn run test-ct`, I'm consistently encountering a "failed to resolve import" error. Could someone kindly guide me on where I might be going wrong with these configurations?
![image](https://github.com/microsoft/playwright/assets/10906745/635a79dd-7258-45d7-99e2-e78e7db1c9db)

**Comment by codenimble** [comment]
Regarding your last post @SDxBacon ... a couple of things:

1. Put the **ctViteConfig** configuration in your _playwright-ct.config.js_
2. Make sure all of your '@' _paths_ in the _compilerOptions_ of yout _tsconfig.json_ are all realtive to ./src for the ` '@': resolve(__dirname, './src'),` to work. The resolve trick works if and only if all of your @ definitions in your _tsconfig.json_ are realitive to src. If you have short cuts to deep paths than you need to define them as well. 

e.g. `"@wizard/*": [ "./components/wizard/*"]` in _tsconfig.json_ would need `"@wizard": resolve(__dirname,"./src/components/wizard"),` in the  _playwright-ct.config.js_
