### ISSUE TITLE
With the introduction of x-pw-overlay, x-pw-glass no longer is the last element

### ISSUE THREAD

**Issue by ruifigueira** [microsoft/playwright#28002]
Playwright checks if `Highlight` is installed by checking if it is the last element  `this._glassPaneElement.nextElementSibling` in:

https://github.com/microsoft/playwright/blob/19b0f5ccb38fb0dee6e04b44448a8a2a212ee393/packages/playwright-core/src/server/injected/highlight.ts#L132-L134

That is also referenced here:

https://github.com/microsoft/playwright/blob/19b0f5ccb38fb0dee6e04b44448a8a2a212ee393/packages/playwright-core/src/server/injected/recorder.ts#L922

However, with the introduction of `x-pw-overlay` this is no longer true:

![image](https://github.com/microsoft/playwright/assets/1374559/565260b0-e866-46a4-96b0-8e710cb19c8e)

**Comment by pavelfeldman** [comment]
I don't think we need this check anymore.
