### ISSUE TITLE
[Feature] Cucumber Integration with Playwright.

### ISSUE THREAD

**Issue by Kunal0002** [microsoft/playwright#28000]
Since BDD is widely used in the market we also work with it. We are trying to configure the playwright with Cucumber and for that we have changed our runner from Playwright to Cucumber.js. Due to this we are not able to use many Playwright features like "Trace Viewer" . Could you please help me with this. Can you guide me how can I use various these feature along with Cucumber.

**Comment by mxschmitt** [comment]
Folding into https://github.com/microsoft/playwright/issues/11975.

**Comment by aymanapatel** [comment]
We are also facing the same issue.

@mxschmitt the Github issue that you highlighted does not have trace.

@Kunal0002's issue could be a different one as it is highlighting Trace Viewer not working with Cucumber.js
