### ISSUE TITLE
[Feature] Make `&` an alias for `:scope` in CSS locator selector

### ISSUE THREAD

**Issue by karlhorky** [microsoft/playwright#28008]
Hi, first of all, thanks so much for all of your effort working on the Playwright tooling and ecosystem! It's a breath of fresh air, coming from Cypress' proprietary APIs.

I was trying out some different CSS selectors with the Playwright `.locator()` API, and was pleasantly surprised to find that `'+ <selector>'` and `'~ <selector>'` and also the XPath `'..'` can be requeried later on an existing locator, to allow for selecting siblings and parents 😍

I wanted to also "add" to an existing locator selector using the `&` selector (ampersand), popularized by Sass/Less and [the CSS Nesting API](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_nesting), similar to [the `.add()` Playwright API](https://playwright.dev/docs/api/class-locator#locator-and), but without losing the existing locator.

However, `&` is currently a parsing error for the selector:

```ts
const companiesHeading = page.locator('h1').first();
await expect(companiesHeading).toHaveText('Companies');

const companiesCompanies = companiesHeading.locator('+ div > a'); // ✅ Works
await expect(companiesCompanies).toHaveCount(5);

await companiesCompanies.locator('&[href="/c/upleveled-gmbh"]').click(); // 💥 Unexpected token "&" while parsing selector
```

Full error:

```
locator.click h1 >> nth=0 >> + div > a >> &[href="/c/upleveled-gmbh"]

locator.click: Unexpected token "&" while parsing selector "&[href="/c/upleveled-gmbh"]"
```

To be clear, the chained selector above should be parsed like this:

```
h1 >> nth=0 >> + div > a >> &[href="/c/upleveled-gmbh"]
```

should turn into:

```
h1 >> nth=0 >> + div > a[href="/c/upleveled-gmbh"]
```

In [further discussion in this issue](https://github.com/microsoft/playwright/issues/28008#issuecomment-1799530562), @dgozman made me aware of the `:scope` selector, which works well 🙌 

```ts
await companiesCompanies.locator(':scope[href="/c/upleveled-gmbh"]').click();
```

So maybe `&` could be treated as an alias for `:scope`

**Comment by karlhorky** [comment]
## Workaround

Use the XPath `.locator('..')` and CSS `.locator('> ...')`

```ts
const companiesHeading = page.locator('h1').first();
await expect(companiesHeading).toHaveText('Companies');

const companiesCompanies = companiesHeading.locator('+ div > a'); // ✅ Works
await expect(companiesCompanies).toHaveCount(5);

await companiesCompanies.locator('..').locator('> a[href="/c/upleveled-gmbh"]').click(); // ✅ Works, but longer
```

**Comment by dgozman** [comment]
@karlhorky You can "add" to an existing CSS selectors today with `:scope` instead of `&`:

```ts
const companiesHeading = page.locator('h1').first();
await expect(companiesHeading).toHaveText('Companies');

const companiesCompanies = companiesHeading.locator('+ div > a');
await expect(companiesCompanies).toHaveCount(5);

await companiesCompanies.locator(':scope[href="/c/upleveled-gmbh"]').click();
```

Let me know whether this helps.

**Comment by karlhorky** [comment]
Can confirm that `:scope` works, thanks!

Would it be desirable for Playwright to add `&` as an alias for `:scope`? (if so, I can change the title and description of the issue)

**Comment by dgozman** [comment]
@karlhorky Yep, leaving this as a feature request for prioritization.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
