### ISSUE TITLE
[Feature] mask honor z-index to allow elements on top

### ISSUE THREAD

**Issue by janett-baresel** [microsoft/playwright#28010]
Using a mask to "color" a certain element in a screenshot is very useful. However, if there are other elements (widgets) on top of it, they are also colored. This is problematic in web applications where an element should be masked but not the widgets that overlap with it (left-screenshot without mask, right-screenshot with mask)
![image](https://github.com/microsoft/playwright/assets/11048042/8260ddeb-c554-4653-93f9-45a65e798d3e)

My suggestion would be to either have masked elements honor the z-index on the page, or to introduce a new option for screenshots which would allow masking an element but keeping the overlapping elements visible. 
The desired outcome would look like this (left-screenshot without mask, right-screenshot with "new" mask):
![image](https://github.com/microsoft/playwright/assets/11048042/bbb40d00-7041-4b73-82f1-31ad7f7a62f1)

**Comment by dgozman** [comment]
@janett-baresel Thank you for the issue and detailed screenshots! I'll fold this into #19002, and we can continue discussion and gather feedback there.
