### ISSUE TITLE
Where should it be called to generate test data created from the API? [BUG]

### ISSUE THREAD

**Issue by MuharremBicici** [microsoft/playwright#28017]
Description : Automated tests have many preconditions. I create this pre-condition data from the API. setup methods that create test data. Should I create it in ts files? (These setup files log into the system with different accounts). Or should I trigger it before all? Also, when I write before all to a spec.ts file, it only works for that file. I create separate before all for other files. Where should it be called to generate test data created from the API?

### System info
- Playwright Version: ^1.40.0-alpha-nov-6-2023
- Operating System: [All, Windows 11, Ubuntu 20, macOS 13.2, etc.]
- Browser: [All, Chromium, Firefox, WebKit]

**Comment by dgozman** [comment]
@MuharremBicici Take a look at [this guide](https://playwright.dev/docs/test-global-setup-teardown#option-1-project-dependencies) and let me know whether that helped.

**Comment by MuharremBicici** [comment]
@dgozman As I mentioned, we are already running our tests with 3 account-based setups. It would be good to create this data in setup. I'm asking this before all? Just to get an idea. When I add it to the before all spec file, it only works for tests in that spec.

**Comment by dgozman** [comment]
@MuharremBicici The guide linked above explains how to write a "setup" file that is shared between all tests.

**Comment by dgozman** [comment]
Closing as there is no action item for Playwright. If you still encounter problems, please file a new issue with a repro and link to this one.
