### ISSUE TITLE
Are we planning to provide add feature like we have in cypress?

### ISSUE THREAD

**Issue by gauravgandhi1315** [microsoft/playwright#28022]

**Comment by dgozman** [comment]
@gauravgandhi1315 Could you please be more specific? What exact feature are you looking for? How do you see it working in Playwright? Code examples / screenshots would definitely help.

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
