### ISSUE TITLE
[internal] 'should emit filechooser event for iframe' is flaky on Chromium

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#28023]
Investigation:

- <img width="250" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/a12f0fdb-3fb6-47fe-bcd0-13d1e9d9f482">
- `Page.fileChooserOpened` CDP event does not fire.
- Adding a delay between `setContent` and the `click` makes it work 100/100 times.
  <img width="809" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/847a8e02-943d-4271-8dd5-e894cfb04bd7">

**Comment by mxschmitt** [comment]
Investigation:
- If the iframe is not oop and has the same host, it does not flake.
- When its a different host, it flakes very often, almost every time.
- We seem to be doing the right thing, sending Page.setInterceptFileChooserDialog to the right sessionId

**Comment by yury-s** [comment]
The click didn't work in OOPIF if [`PaintHolding`](https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/common/features.cc;l=1349;drc=33074a84560edea3e92e75425a67430afbc38e35) feature is on.
