### ISSUE TITLE
[BUG] toHaveScreenshot({fullPage:true}) is not working on specific website

### ISSUE THREAD

**Issue by IAM-Kyle** [microsoft/playwright#28027]
### System info
- Playwright Version: [v1.37]
- Operating System: [Windows]
- Browser: [Chromium]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

The code is simple:
```
  await page.goto(<myaccount URL>);
  await expect(page).toHaveScreenshot(<fileName>, { fullPage: true });
```

The generated screenshot doesn't cover the full page. Instead it only covers content visible in the viewport.  
![image](https://github.com/microsoft/playwright/assets/123520759/181475c7-d93c-4640-a795-bed022785854)

I saw a similar issue was rasied earlier: https://github.com/microsoft/playwright/issues/27325. I want to understand if there are specific CSS rules the page needs to follow to make `fullPage:true` work correctly, even if the scrollbar is already there.

To check the CSS settings of our app [My Account](https://myaccount.microsoft.com), you have to use Microsoft employee account to log in. 

**Link to the GitHub repository with the repro**

We cannot expose internal code repository.

or

**Config file**

**Steps**

**Expected**

full page screenshot

**Actual**

only viewport is in screenshot

**Comment by NikkTod** [comment]
I also saw that behavior in the application, where I am working. 

fullPage:true does not work correctly, could it be something connected to iframes?

**Comment by dgozman** [comment]
@IAM-Kyle Playwright does not change the page layout, so if the content you would like to see on the screenshot does not appear below the fold, there is not much we can do. This heavily depends on the page structure, for example `height: 100vh` forces content to be the same size as the visible viewport, so nothing is actually rendered below the fold. Unfortunately, there are not specific rules that would guarantee the behavior in every single case.

As a workaround, I would recommend changing the viewport manually before taking the screenshot, and see whether that helps:

```ts
await page.setViewportSize({ width: 1280, height: 3000 });
await expect(page).toHaveScreenshot();
```

**Comment by dgozman** [comment]
Closing because there is no action item for Playwright. If you still encounter problems, please file a new issue with a repro and link to this one.
