### ISSUE TITLE
How to make 'show-report' accessible on the local network for other computers

### ISSUE THREAD

**Issue by swmachine1401** [microsoft/playwright#28032]
When I run the 'npx playwright show-report' command, I can only access the report through http://localhost:9323/. How can I make it accessible on the local network as well, for example, through http://192.168.10.18:9323/?

**Comment by mxschmitt** [comment]
```
npx playwright show-report --host 0.0.0.0
npx playwright show-report --help
```

**Comment by swmachine1401** [comment]
> ```
> npx playwright show-report --host 0.0.0.0
> npx playwright show-report --help
> ```

Thank you. I can actually open it.But a new problem arose.
I'm opening traces and there's no response.

![image](https://github.com/microsoft/playwright/assets/33212266/a5a2a5db-7257-46c7-a9c2-335af571619a)
![image](https://github.com/microsoft/playwright/assets/33212266/f8b2d81a-7ecb-4e4a-8b05-85bbef5b5590)
![image](https://github.com/microsoft/playwright/assets/33212266/65f1a72c-7dac-48c5-a8ed-22f81a978049)

**Comment by mxschmitt** [comment]
Yes trace viewer needs to be served over https as per [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers?retiredLocale=de), otherwise it won't work.

**Comment by swmachine1401** [comment]
> Trace viewer needs to be served over https as per [here](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers?retiredLocale=de), otherwise it won't work.

Thank you.I deployed it in nginx and it worked fine.
May I ask why https?

**Comment by mxschmitt** [comment]
Unfortunately this is a security limitation not given by us, its given by the Service Worker API specification. From the next version on we'll throw a more readable error.

**Comment by swmachine1401** [comment]
I see.Thank you for your help very much
