### ISSUE TITLE
[BUG] waitforselector inside a frame not working 

### ISSUE THREAD

**Issue by KesabKC** [microsoft/playwright#28033]
Hi , I am trying to wait for selector inside a frame .but it is not working . 
I tried ,
Page.frame('#frameid').waitforSelector('#id');
But it says null

**Comment by dgozman** [comment]
We need more information to act on this issue. Could you please provide a repro that we can run locally?

**Comment by KesabKC** [comment]
Hi , sorry it is a private application and repo. The way to wait for selector inside a frame is .
Page.frame("I'd").waitForSelector("I'd"); right ?
Do we have any other way .this doesn't work for me if I'm not working .

**Comment by dgozman** [comment]
@KesabKC Take a look at [`FrameLocator`](https://playwright.dev/java/docs/api/class-framelocator) and [`Locator.waitFor`](https://playwright.dev/java/docs/api/class-locator#locator-wait-for).

**Comment by dgozman** [comment]
Closing because we lack the information to act on this issue. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
