### ISSUE TITLE
[Feature] Firefox disable `bypassCOOP_COEP.insecure.enabled` again

### ISSUE THREAD

**Issue by JannisBush** [microsoft/playwright#28037]
For studying browsers or investigating how websites behave in real browsers it is of importance that the settings used in the browsers reflect the settings of normal users. The `bypassCOOP_COEP.insecure.enabled` flag hides COOP/COEP issues.

The flag was added after the following report: https://github.com/microsoft/playwright/issues/8178
If I understand it correctly, the flag was necessary as COEP and COOP were deactivated completly.
However, support for COEP and COOP was added: https://github.com/microsoft/playwright/commit/6c5317bd31450d14a6d4ba71c1b4599fae08c346#diff-996ad5f6063afe94256019bee01169f880cef58ecb01e478b68daec783af10d4L12
Thus, it might be possible to remove the insecure flag again?

OT: Is there an overview of the observable changes done for the three browsers or does one have to analyze all the config files and patches manually?

**Comment by dgozman** [comment]
@JannisBush Thank you for bringing our attention to this. I'll see whether we can remove this flag, meaning that all tests should continue to pass.

**Comment by dgozman** [comment]
Should be fixed in the v1.41 release.
