### ISSUE TITLE
When using Playwright-Test, how can I share a cookies?

### ISSUE THREAD

**Issue by swmachine1401** [microsoft/playwright#28034]
For example, many of my tests involve actions after logging in, so I want to use the cookies obtained after logging in and have different tests share these post-login cookies.
`test('login', async ({page}) => {
    // Log in here. get cookies
});

test('order', async ({context}) => {
    // Set post-login cookies
    context.cookies(cookie)
});
`
Or is my approach incorrect, and should each test include a login process?

**Comment by StasGrishaevTutu** [comment]
check this one - https://playwright.dev/docs/auth#basic-shared-account-in-all-tests

**Comment by dgozman** [comment]
It seems like the issue has been resolved. If you still encounter problems, please file a new issue with a repro and link to this one.
