### ISSUE TITLE
how to run playwright using green run icon shown near the test() with env variables

### ISSUE THREAD

**Issue by gunajoker** [microsoft/playwright#28031]
we are using env variables and are currently unable to run the tests using the green icon shown near the test() statement. 

![image](https://github.com/microsoft/playwright/assets/21328905/84c3dafe-ea44-4743-80d3-48e14cbc7b35)

maybe on right click menu, add one more button like run with env variables and let us pass variable and value 
![image](https://github.com/microsoft/playwright/assets/21328905/22de76cf-136c-4247-9774-c9c2d8a5f7c8)

**Comment by dgozman** [comment]
@gunajoker Open settings UI in VSCode, search for "playwright.env" and click "Edit in settings.json". There you can set any environment variables for your tests.

<img width="548" alt="Screenshot 2023-11-08 at 2 27 27 PM" src="https://github.com/microsoft/playwright/assets/9881434/56018b4a-4573-49ac-a8f6-7c8db34de12b">

Let me know whether this helps.

**Comment by gunajoker** [comment]
yes working, thanks
