### ISSUE TITLE
[Feature] Playright -ui - ability to run only failed tests

### ISSUE THREAD

**Issue by wolispace** [microsoft/playwright#28030]
To reduce stress on the server being tested, it would be great if we could run all failed tests only.

Scenario:
We have 15 .spec.js files and each contains multiple tests, each targeting different sites on the same server.
Running all tests results in about 40% failing (timing out) as the server is under so much load.

I manually run each failed test, one by one and they all succeed.

To save me having to sit and click each failed test it would be great to click a 'Re-run all failed tests only'

**Comment by dgozman** [comment]
@wolispace You can click on the "Status: all" text and select "failed" in the list. This should filter the test list to only show failed tests. Click the "Run all" button to run them.

<img width="316" alt="Screenshot 2023-11-08 at 2 30 07 PM" src="https://github.com/microsoft/playwright/assets/9881434/c2377518-4336-4a3c-a437-214db431f49b">

Let me know whether this helps.

**Comment by wolispace** [comment]
Magic!.. exactly what I was looking for.

Slightly hidden but only because I was not looking properly.

Thanks

**Comment by stenon-olivier** [comment]
How to do this from the command line?
