### ISSUE TITLE
Use the 'on' method to listen for dom element changes[Feature]

### ISSUE THREAD

**Issue by KaHuier** [microsoft/playwright#28049]
**Well, I come across a situation in automation where some element doesn't come up every time but I need to deal with it when it does.
I do not have a good way to deal with it, the current way is:**
```
page.goto("https://translate.google.com/")
page.click(...)
try:   
    page.click("//div[@class='close']", timeout=5*1000)
except:
    pass
page.fill(..., ...)
```
**or**
```
page.goto("https://translate.google.com/")
page.evaluate("""
    window.myObserver = new MutationObserver(async function(mutations) {
        for (let mutation of mutations) {
            if (mutation.type == "childList" && mutation.addedNodes.length > 0) {
                let closeButton = document.querySelector("[class='close']");
                if (closeButton) {
                    window.myObserver.disconnect();
                    closeButton.click();
                    window.myObserver=null;
                }
            }
        }
    });
    window.myObserver.observe(document.body, { childList: true, subtree: true });
    """)
page.click(...)
page.fill(..., ...)
page.evaluate("""
            if (window.myObserver){
                window.myObserver.disconnect();
           };
""")
```
**I think the second method is more elegant, because the first method wastes 5 seconds when '//div[@class='close']' is not loaded, or the network loading problem causes 5 seconds to not load at all. Can you add a method to make the second method easier to write?**

**Comment by KaHuier** [comment]
**The second method proposed in the article was written incorrectly and corrected:**
```
window.myObserver = new MutationObserver(function(mutationsList,observer ) {
        for (let mutation of mutationsList) {
            if (mutation.type == "childList" && mutation.addedNodes.length > 0) {
                let closeButton = document.querySelector("[class='close']");
                if (closeButton) {
                    window.myObserver.disconnect();
                    closeButton.click();
                    window.myObserver=null;
                }
            }
        }
    });
    window.myObserver.observe(document.body, { childList: true, subtree: true });
```

**Comment by dgozman** [comment]
@KaHuier I think your workaround is really nice when it works. Unfortunately, we do not think this would be a generally good addition to Playwright:
- Making tests deterministic is the best solution that we recommend everyone to try.
- Calling `closeButton.click()` is not a universal solution to the issue. This heavily depends on the page structure and what you should do with the element that appears non-deterministically.
- There are multiple workarounds like yours above. For example, [using `locator.or_`](https://playwright.dev/python/docs/api/class-locator#locator-or) works in some cases. See also #17068 for a similar question.
