### ISSUE TITLE
docs: toContainText check child elements?

### ISSUE THREAD

**Issue by msmith1114** [microsoft/playwright#28058]
So I did a search for this and surprisingly didn't find anything nor does the documentation state it. When we are asserting a locator has text.....does it also check descendant/child elements?

IE if I have a `<div>` and a `<span>` inside of it and my locator points to the `<div>` and I do `toContainText` on the `<div>` element. Will it still work? (Since it's technically "in" the `<div>` as well). (This is useful since I may have "cards" that are divs that contain text content and that's more obvious of a locator than adding a locator for a singlular `<span>` item or similar within the div card.

My assumption is this works but I figured it was worth asking since I surprisingly didn't see a question about this anywhere else.

**Comment by dgozman** [comment]
@msmith1114 Yes, we consider text inside child elements when performing any text-related operations like `toHaveText`/`toContainText`/`getByText`.

We should update the docs to make this clear. Would you like to contribute a PR?

**Comment by msmith1114** [comment]
@dgozman Yes I would like to. It would be my first PR for something like this but I think it would be a good/easy update to add.

**Comment by dgozman** [comment]
@msmith1114 Wonderful! Take a look at `CONTRIBUTING.md`, especially [this section](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md#writing-documentation). Let me know if you have any questions.

**Comment by geke-scottlogic** [comment]
Hi, I opened a [PR](https://github.com/microsoft/playwright/pull/28623) addressing this for toHaveText and ToContainText. I felt the examples for getByText made this clear and thus did not necessitate clarification.
