### ISSUE TITLE
[BUG] throwing from pageerror callback leads to unpredictable behavior

### ISSUE THREAD

**Issue by bahmutov** [microsoft/playwright#28056]
### System info
- Playwright Version: [v1.39]
- Operating System: [Mac 14.0]
- Browser: [Chromium]
- Other info: UI mode

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

I am trying to fail the test if the page throws any errors. 
```js
page.on('pageerror', (exception) => {
  console.log('page error!')
  throw exception
})
await page.goto('/')
await expect(page.locator('.todo-list li')).toHaveCount(0)
```

The UI test mode shows really unpredictable behavior, see the video below. Every time I click on the run button, it does something differently, and sometimes the results disappear.

https://github.com/microsoft/playwright/assets/2212006/83d08f78-63cf-43cc-9e54-5c2b3b2fcf1f

Even when it does fail due to the `li` element count, it does not retry for 5 seconds, but only for 50-100ms because that's when the exception arrives.

If I try to use `expect` to fail the test if fails the assertion, but proceeds

```js
page.on('pageerror', async (exception) => {
  console.log('page error!')
  expect(false, 'page error').toBeTruthy()
})
await page.goto('/')
await expect(page.locator('.todo-list li')).toHaveCount(0)
```

<img width="826" alt="Screenshot 2023-11-09 at 09 56 44" src="https://github.com/microsoft/playwright/assets/2212006/8c3df305-f081-46e1-9ca0-588b55a4e4a4">

**Expected**

The test fails if the `pageerror` callback throws an error

**Actual**

[Describe actual behavior]

**Comment by marko-simic** [comment]
Perhaps you can consider this approach.
```js
test("Example", async ({ page }) => {
  // Log all uncaught errors to the terminal
  page.on("pageerror", (exception) => {
    expect(exception, exception).not.toBeDefined();
  });

  // Navigate to a page with an exception.
  await page.goto('data:text/html,<script>throw new Error("Test")</script>');
});
```

**Comment by dgozman** [comment]
I can partly reproduce the issue with the following snippet. When running in UI mode, I don't see the "Some error", but instead see the expect's error.

```ts
import { test, expect } from '@playwright/test';

test('a test', async ({ page }) => {
  await page.goto('https://playwright.dev');
  setTimeout(() => { throw new Error('Some error') }, 500);
  await expect(page.locator('.todo-list li')).toHaveCount(10);
});
```

However, I cannot reproduce the "empty result" issue. @bahmutov Could you please share the full repro, with the actual page url, that triggers the empty result? I suspect it is timing-related.

**Comment by bahmutov** [comment]
Sure, here is a standalone repo https://github.com/bahmutov/pw-on-error
It acts very weirdly, showing after hooks run before actions (and clicking on the actions shows nothing) I suspect the thrown exception has the test finish immediately, but the actions running in parallel seem to be not cleaned up

<img width="1274" alt="Screenshot 2023-11-09 at 14 09 07" src="https://github.com/microsoft/playwright/assets/2212006/214528bc-de6c-4d1e-aada-65a8414de914">

**Comment by dgozman** [comment]
@bahmutov Thank you for the repro. I can observe the same: expect actions at the end with an empty log. However, both expects reliably succeed in my case, I guess due to different timing.
