### ISSUE TITLE
[Feature] Timeout should be listenable or be a promise reject

### ISSUE THREAD

**Issue by raymondmeg** [microsoft/playwright#28057]
I'm using playwright 1.39.0 as a library of my Node.js  app.
I was bothered by "Timeout" very much.  I know people will say , you should using " try ... catch ..." to capture the "timeout".  
but think about the following code:

```ts
async function main(){
   await page.goto('xxx');
   const a = await page.locator('xxx');
   await a.click();
   await page.waitForURL('yyy');
   const resp = await  page.waitForResponse('zzz');
   .......
}
```

there's so many opportunities to "Timeout",  and a global  "try...catch..." seems not working well.  believe me , i tried global try...catch...,  some times it's worked ,  some times  not .

and the current behavior of those operations is so strange...WHY NOT just let it return Promise.reject ,but insteda of "throw"..  and  i even can't add an event listener to get the "Timeout"...what is the reason for you guys make this desigh.

**Comment by dgozman** [comment]
@raymondmeg Unfortunately, I don't really understand the issue.

Let me recap how Playwright works.
- Each method has a built-in timeout. When timeout is reached, the method returns a rejected Promise.
- You can control timeout for each method with the `{ timeout: 1234 }` option.
- You can control timeouts in general with [`page.setDefaultTimeout()` method](https://playwright.dev/docs/api/class-page#page-set-default-timeout).
- When you are running a test, action timeouts are disabled, and instead there is a test timeout and expect timeout. See [this guide](https://playwright.dev/docs/test-timeouts) for more details.

If you still have an issue, please explain what exactly does not work for you, and how you would like to see it.

**Comment by raymondmeg** [comment]
" Each method has a built-in timeout. When timeout is reached, the method returns a rejected Promise.  "

**Comment by raymondmeg** [comment]
i tried to write a function to repeat what i met in past few days .  But, it's so amazing ,that  "timeout" can be captured and act exactly as you said -- "a rejected promise".

**Comment by dgozman** [comment]
I'm glad that everything works as expected. I'll close the issue now. If you still encounter problems, please file a new issue with a repro and link to this one.
