### ISSUE TITLE
[Feature] Ability to blacklist attributes or modify attribute preference in Codegen

### ISSUE THREAD

**Issue by minhhai2209** [microsoft/playwright#28059]
The Playwright code generation utility (codegen) is an incredibly useful tool for scripting browser interactions automatically by recording user actions. However, in its current state, the utility does not allow users to customize attribute preferences or blacklist certain attributes during the code generation process. This can lead to generated selectors that are overly specific, fragile, or tied to dynamic attributes that are likely to change.

**Comment by dgozman** [comment]
Thank you for the issue! Folding into #9015.
