### ISSUE TITLE
[question] how to make apiRequestContext.get() to show 401 error instead of 

### ISSUE THREAD

**Issue by bodycombathuang** [microsoft/playwright#28050]
When I run curl command
>curl --insecure http://oneurl, I can get 401 error 

but if I use apiRequestContext.get()  to call the url, I get 302 error, if I set maxRedirects to be 0, then I get 200 error, how can I use apiRequestContext.get to return 401 error for the url?

**Comment by dgozman** [comment]
@bodycombathuang We need more information to act on this issue. Could you please provide a repro that we can run locally, including the actual url?

**Comment by bodycombathuang** [comment]
hi  @dgozman 
if I save the following code in a non-test block, 
  const requestContext = await request.newContext({
    baseURL: "http://oneurl",
    ignoreHTTPSErrors: true,
    timeout: 90000
  });
const response= await requestContext.get("/endpoint");
and run in visual code ,  I can get 401 error
{
  version: 2,
  httpStatusCode: 401,
  errorCode: 401,
  message: 'Full authentication is required to access this resource',
  details: [
    'path: /path/',
    'correlator: 1d1c4dae-3432-43da-8112-d75977d8f8f8'
  ]
}

but if I put the above code in  playwright test block

test('no authentication test @s3', async ({ }) => {
...
}

I cannot get 401 error, I get 302 error,   does playwright.config.ts file or other setting that make the above difference, such as redirects

**Comment by bodycombathuang** [comment]
I tried failOnStatusCode , but it does not work

**Comment by dgozman** [comment]
> does playwright.config.ts file or other setting that make the above difference, such as redirects

That's unlikely. Unfortunately, I cannot help in this case without a repro. I will close the issue as non-actionable unless we can have a snippet that reproduces the problem.

**Comment by dgozman** [comment]
We have to reproduce this issue locally to be able to debug it. If you can provide a full repro, please file a new issue by filling the "Bug Report" template, and link to this one.
