### ISSUE TITLE
[BUG] Fixtures not receiving test.use() override values

### ISSUE THREAD

**Issue by sircody01** [microsoft/playwright#28065]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 10]
- Browser: [All]
- Other info: Node v18.16.0

### Source code

- [X] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[Playwright fixture bug repro](https://github.com/sircody01/PlaywrightFixtureBugRepro)

I am using `test.use()` in my test to provide parameterized values to my test. That looks like this:

```typescript
test.describe("Example test suite", () => {
  for (const country of countries) {
    test.use({
      locale: `${country.language}-${country.country}`,
      countryOption: { language: country.language, country: country.country },
    });
    test(`get started link for ${country.language}-${country.country}`, async ({
      page,
      myPage,
    }) => {
```

I have discovered that the fixtures in my test project do not receive the correct values. Specifically here's what the fixtures actually receive:
- For `locale` the fixtures get whatever value is contained in `playwright.config.ts` e.g. ```export default defineConfig({
  use: {
    locale: 'en-US',
  },```
- For `countryOption` the fixtures get the last value from the `countries` array.

 I expected the fixtures to receive the values that were set by the test.use() call.

**Comment by dgozman** [comment]
@sircody01 [`test.use()`](https://playwright.dev/docs/api/class-test#test-use) modifies the options for the whole describe block. Therefore, if you call it multiple times inside a single describe block, the latest value will be used.

In your scenario, wrap each test with a describe block:

```ts
test.describe("Example test suite", () => {
  for (const country of countries) {
    test.describe(() => {
      test.use({
        locale: `${country.language}-${country.country}`,
        countryOption: { language: country.language, country: country.country },
      });
      test(`get started link for ${country.language}-${country.country}`, async ({
        page,
        myPage,
      }) => {
      });
    });
  }
});
```

Let me know whether this helps.

**Comment by sircody01** [comment]
Thank you very much for your feedback. I can confirm that following your suggestion of surrounding the `test.use()` and the `test()` calls inside another `test.describe()` block does resolve the issue of the fixture not getting the correct `countryOption` value. Unfortunately the fixture is still getting incorrect value for `locale`. It's still getting whatever value is contained in `playwright.config.ts`, not the value set in the `test.use()` call.

I have updated [my repo](https://github.com/sircody01/PlaywrightFixtureBugRepro) with your suggestion. You can repro this behavior by running the test contained in `test\example.spec.ts`, then studying the values received by the `myPage.ts` fixture.

```typescript
import { expect, type Page, type TestInfo } from "@playwright/test";
import { currentCountry } from "./tests/example.spec";

export class MyPage {
  constructor(
    readonly page: Page,
    readonly testInfo: TestInfo,
    readonly locale: string | undefined,
    readonly use: any,
    readonly fixtureCountry: { language: string; country: string }
  ) {
    console.log("myPage constructor. locale is: ", locale);
  }

  verifyLocale() {
    expect  // This is the line that fails
      .soft(this.locale?.toLocaleLowerCase())
      .toBe(
        currentCountry.language.toLocaleLowerCase() +
          "-" +
          currentCountry.country.toLocaleLowerCase()
      );
    expect
      .soft(
        this.fixtureCountry.language.toLocaleLowerCase() +
          "-" +
          this.fixtureCountry.country.toLocaleLowerCase()
      )
      .toBe(
        currentCountry.language.toLocaleLowerCase() +
          "-" +
          currentCountry.country.toLocaleLowerCase()
      );
  }
}
```

**Comment by sircody01** [comment]
@dgozman Thank you very much! Confirmed that fully resolves the issues I was running into. You may close this bug report.
