### ISSUE TITLE
[BUG] Installed dependencies for Linux Mint 21.x are incorrect (Ubuntu 20 vs 22 expected)

### ISSUE THREAD

**Issue by faulpeltz** [microsoft/playwright#28078]
### System info
- Playwright Version: v1.39
- Operating System: Linux Mint 21.2
- Browser: All
- Other info:

**Steps**
- Run install-deps

**Expected**

Playwright installs Ubuntu 22 deps

**Actual**

Playwright tries to install Ubuntu 20 deps, but Mint 21 is based on Ubuntu 22

Mint (distro id "linuxmint") should be added to  ``playwright-core/src/utils/hostPlatform.ts`` (like pop and neon)

/etc/os-release
```
NAME="Linux Mint"
VERSION="21.2 (Victoria)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.2"
VERSION_ID="21.2"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=victoria
UBUNTU_CODENAME=jammy

```

**Comment by dgozman** [comment]
@faulpeltz Would you like to contribute a PR?

**Comment by faulpeltz** [comment]
Yes - is a CLA needed?
