### ISSUE TITLE
Is Enterprise Support available for Playwright?

### ISSUE THREAD

**Issue by sundar-ds** [microsoft/playwright#28079]
We are creating a lot of test automation scripts using Playwright and would like to know the roadmap, planned features and what kind of life we can expect for Playwright? We would also like to know if there's an enterprise version or support available rather than community support.

**Comment by sundar-ds** [comment]
Hello - Any updates to this question?

**Comment by pavelfeldman** [comment]
Playwright is an open source project. There is no dedicated enterprise support for Playwright provided over the OSS channel.
