### ISSUE TITLE
[BUG] Regex fails match with inside backticks

### ISSUE THREAD

**Issue by cd-slash** [microsoft/playwright#28076]
### System info
- Playwright Version: [v1.38]
- Operating System: [macOS 14.0]
- Browser: [Chromium]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

working to match url:
```typescript
const targetUrl = new RegExp(
    /\/@(-?\d{1,3}\.\d{7}),(-?\d{1,3}\.\d{7}),14z\//
)
await expect(page).toHaveURL(targetUrl)
```

not working, on same url:
```typescript
const targetUrl = new RegExp(
    `\/@(-?\d{1,3}\.\d{7}),(-?\d{1,3}\.\d{7}),14z\/`
)
await expect(page).toHaveURL(targetUrl)
```

The only difference is wrapping the regex in backticks, instead of using `/` to define the regex. It is not clear why the match should fail when using the backtick option.

For reference, I want to use backticks so I can include a variable in the regex, which I have used elsewhere without issues.

**Steps**
- Run the test
- Click button that will update URL

**Expected**

Url should match the regex whether it is wrapped in backticks or delimited by slashes.

**Actual**

Url matches when regex is delimited by slashes, but not when wrapped in backticks. No other changes were made.

**Comment by dgozman** [comment]
@cd-slash That's how JavaScript works - regex literal and backtick string have vastly different escaping rules.

You can try this yourself by running Node.js. As you can see, `\d` is either escaped or not.

```sh
$ node
Welcome to Node.js v18.15.0.
Type ".help" for more information.

> new RegExp(/\/@(-?\d{1,3}\.\d{7}),(-?\d{1,3}\.\d{7}),14z\//)
/\/@(-?\d{1,3}\.\d{7}),(-?\d{1,3}\.\d{7}),14z\//

> new RegExp(`\/@(-?\d{1,3}\.\d{7}),(-?\d{1,3}\.\d{7}),14z\/`)
/\/@(-?d{1,3}.d{7}),(-?d{1,3}.d{7}),14z\//
```

**Comment by cd-slash** [comment]
Apologies, you're right - I didn't realise that Javascript was removing the escape characters when using backticks but not with slashes. This is clearly not a Playwright bug.
