### ISSUE TITLE
[Feature] APIRequestContext send multiple files in a single field with a single field name

### ISSUE THREAD

**Issue by dariusnemeiksis** [microsoft/playwright#28070]
Hello, 

Use case: 
Back-end API service accepts multiple files in a single form field with a single field name.

Current behavior:
APIRequestContext in multipart supports sending multiple files with different field names. 
example: `curl -F "docpicture=@dog.gif" -F "catpicture=@cat.gif" $URL`
```
multipart: {
    file: stream1,
    oneFile: {
        name: "file1.jpg",
        mimeType: 'image/jpg',
        buffer: image1,
    }
}
```

Extended behavior:
APIRequestContext in multipart supports sending multiple files in a single field with a single field name.
example: `curl -F "pictures=@dog.gif,cat.gif" $URL`
```
multipart: {
    files: [stream1, stream2],
    multiFiles: [{
        name: "file1.jpg",
        mimeType: 'image/jpg',
        buffer: image1,
    },
    {
        name: "file2.jpg",
        mimeType: 'image/jpg',
        buffer: image2,
    }]
}
```

With this additional APIRequestContext extension, people can use Playwright directly without adding additional packages.

**Comment by NikkTod** [comment]
Hello Playwright team,

we have an email API, that accepts multiple files, but they have to be send with same field name called 'attachment'.

We are not able to test the functionality as the APIRequestContext expects different field name for each attachment.

Would very much appreciate if you can add this feature to the APIRequestContext.  

cc: @dgozman, @pavelfeldman @mxschmitt

**Comment by NikkTod** [comment]
@dgozman thanks for adding this one to the release, we are migrating our API tests to Playwright and need it desperately.
