### ISSUE TITLE
[BUG] opening devtools in non headless mode triggers the browser to switch to user system theme

### ISSUE THREAD

**Issue by AllanOricil** [microsoft/playwright#28088]
### System info
- Playwright Version: 1.39.0
- Operating System: macOS Sonoma 14.1
- Browser: Chromium and Webkit

obs: firefox works as expected.

### Source code

https://github.com/AllanOricil/node-os-theme

**Steps**

- run `index.js`, read the readme and watch the video to understand the issue

**Expected**

I don't think that opening the devtools should trigger this behavior of reading the user system theme. 

**Actual**

system theme is loaded automatically when opening the devtools

**Comment by dgozman** [comment]
@AllanOricil That's just how DevTools work. Most likely they force disable light/dark theme emulation that Playwright sets up, and default to the system one. I don't think Playwright can do anything about this. You can try filing an issue against DevTools to not reset the emulation, but it looks like an issue that will not be highly prioritized.
