### ISSUE TITLE
[Feature] Custom Playwright GPT

### ISSUE THREAD

**Issue by jitterbox** [microsoft/playwright#28084]
I realize it's not a direct Playwright feature, but are there any plans in the roadmap for any team members to work on creating a custom OpenAI GPT (https://openai.com/blog/introducing-gpts) that targets generating Playwright scripts from natural language prompts?

If this is not something that Microsoft or the Playwright team is pursuing directly, is there a large body of internal Playwright test scripts with high coverage of all test types and Playwright functionality (and ideally well-commented) that could be made publicly available for an open source effort to generate such a thing?

**Comment by pavelfeldman** [comment]
I believe we'll get to it at some point, but don't let us hold you back - we've already seen this exact Playwright GPT created by third parties.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by BaseInfinity** [comment]
I know this issue is closed but figured I'd share one of my hacks for a PlaywrightGPT solution:
https://www.youtube.com/watch?v=DH9cIm1qfug

I imagine a future where we can generate code diffs and even self repair tests in CI
