### ISSUE TITLE
[BUG] Chromium preventing process stopping with watch mode on web servers

### ISSUE THREAD

**Issue by p-kuen** [microsoft/playwright#28091]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [macOS 14.1]
- Browser: [Chromium]
- Other info: Node V21.1.0

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
import { chromium } from "playwright";
import { createServer } from "http";

async function start() {
  const browser = await chromium.launch();

  await browser.close();
}

createServer(async (req, res) => {
  await start();
  res.end();
}).listen(3000, "localhost");
```

**Steps**
- Run the code with `node --watch index.js`
- Start a request on the webserver (e.g. `curl localhost:3000`)
- Change the source code (e.g. add a `console.log`

**Expected**

The webserver restarts as expected with the new source code

**Actual**

```
Restarting 'index.js'
Waiting for graceful termination...
```
shows up in the terminal. As soon as you kill the existing `node` process, the restart succeeds. It seems as there is still a playwright process opened.

The error does not occur if you do not launch the playwright browser. I already searched the web for hours but did not find a solution for this problem.

**Comment by mxschmitt** [comment]
Great repro!

The cause is around here: https://github.com/microsoft/playwright/pull/23317#discussion_r1210813881 and that we don't remove the event listeners.

We'll look into it, thanks!

**Comment by dgozman** [comment]
@p-kuen I think you should pass [`handleSIGHUP: false`, `handleSIGINT: false` and `handleSIGTERM: false`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-handle-sighup) when launching the browser, because you probably want more granular control of the signals anyway.

That said, I'll see what we can do.

**Comment by p-kuen** [comment]
It seems like using [`handleSIGHUP: false`, `handleSIGINT: false` and `handleSIGTERM: false`](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-option-handle-sighup) solves the problem. If you don't need to fix anything anymore, you can close this issue.
