### ISSUE TITLE
[Question] Misunderstanding about displaying timings for test.step for API calls

### ISSUE THREAD

**Issue by Aroot42** [microsoft/playwright#28092]
Hello!

I have a misunderstanding about displaying timings for test.step for API calls.
For example, I have a simple method with an API request
![image](https://github.com/microsoft/playwright/assets/100360547/f873ab97-6c9d-4502-a1eb-2f3fc61af2f2)
And when I look at the test trace, I see that the sum for each call to test.step is not equal to the time of the entire test step - **1ms+586ms+0+0!=4.6sec**.
How is this possible and who stole the missing time?
![image](https://github.com/microsoft/playwright/assets/100360547/89ab6254-c9a5-48a5-bec5-663fb9511efa)

**Comment by dgozman** [comment]
@Aroot42 Could it be `await getToken()` that takes time?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
