### ISSUE TITLE
Full page screenshot error | process_memory_range.cc(75)] read out of range

### ISSUE THREAD

**Issue by DheerajN98** [microsoft/playwright#28098]
I am trying to take entire page screenshot of the attached html page. When I am trying with full_page=True, I am getting the below traceback and failing. I am using playwright version 1.39.0. Any help will be appreciated greatly! My code, html page and error traceback are given as attachments.

[Playwright_screenshot_traceback.zip](https://github.com/microsoft/playwright/files/13331287/Playwright_screenshot_traceback.zip)

**Comment by mxschmitt** [comment]
Upstream bug: https://bugs.chromium.org/p/chromium/issues/detail?id=1501784

**Comment by FluffyDietEngine** [comment]
@DheerajN98 The HTML file which is added here is having some loose text which is not inside a valid HTML tag. And the text is in both before and after the HTML content. If I remove it and load to the driver I am able to take the complete screenshot without any errors.

**Comment by mxschmitt** [comment]
Yes its related to the very long loose text at the end. This should not cause Chromium to crash tho in my opinion.

**Comment by mxschmitt** [comment]
Closing by that since we filed it upstream and its not actionable by us.
