### ISSUE TITLE
[BUG] Unable to run mvn test on gitlab CICD pipeline with docker, unable to download chrome driver

### ISSUE THREAD

**Issue by islam0000** [microsoft/playwright#28093]
### System info
- Playwright Version: [1.35.0]
- Operating System: [Mac, Gitlab with docker]
- Browser: [Chromium]
- Other info:

<img width="817" alt="image" src="https://github.com/microsoft/playwright/assets/18109291/ef2179c8-aabe-446e-8fc5-74cf8411d168">

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Steps**
- [Run the test]
- mvn test with docker yml file on gitlab CICD pipeline

**Expected**
*. mvn test should run test cases

**Actual**
Getting error below : 
<img width="817" alt="image" src="https://github.com/microsoft/playwright/assets/18109291/e4ec1e88-c183-4f8f-9e78-dde9ca4fd4a5">

**Comment by dgozman** [comment]
@islam0000 It looks like you are calling `setChannel("chrome")`, but Google Chrome is not available on your CI/CD machine. Read more about [using Google Chrome channel](https://playwright.dev/java/docs/browsers#google-chrome--microsoft-edge).

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions.
