### ISSUE TITLE
[Feature] Network traffic measurement

### ISSUE THREAD

**Issue by lonix1** [microsoft/playwright#28097]
There have been multiple discussions here, in discord and stackoverflow about recording the amount of network traffic ("bandwidth") per page. The best answer I could find was [this](https://github.com/microsoft/playwright/issues/11438#issuecomment-1015413221) which led to this [error](https://github.com/microsoft/playwright-dotnet/issues/2743).

The recommendation is (c# code but same idea for other languages):
```cs
var page = await browserContext.NewPageAsync();
page.Request  += (_, request)  => MeasureBandwidth(request);

// ...

private async void MeasureBandwidth(IRequest request) {
  var sizes = await request.SizesAsync();
  _totalTraffic += sizes.RequestHeadersSize + sizes.RequestBodySize + sizes.ResponseHeadersSize + sizes.ResponseBodySize;
  // exception handling excluded for brevity...
}
```

However that does [not work](https://github.com/microsoft/playwright-dotnet/issues/2743) reliably:
- Those metrics expose the bandwidth consumed for the original request. But if there is AJAX (or whatever background network activity), that will not be included. In the chromium devtools I think that is accumulated in the network tab and shown in the total.
- Various exceptions are thrown such as `PlaywrightException`, `IOException` and `NullReferenceException`, which apparently are due to a request that was in-flight but is now closed. We can ignore the exceptions, but then the results are inaccurate.

So in client-code there is no way to accurately determine network traffic, because we can only measure after the fact in an event handler - and if the page has been changed, then we lose that information.

**Please consider adding a built-in bandwidth measurement, per page?**

It could be a series of `int` like above, but on the page object itself. That would eliminate the race condition and ensure accurate results.

**Comment by mxschmitt** [comment]
What is your intention for generating and collecting these metrics? Playwright might not be the right tool for that, and something on a different layer, like a proxy might fit in better. Since browsers might abort requests etc.

**Comment by pavelfeldman** [comment]
#### Why was this issue closed?

Thank you for your involvement. This issue was closed due to limited engagement (upvotes/activity), lack of recent activity, and insufficient actionability. To maintain a manageable database, we prioritize issues based on these factors.

If you disagree with this closure, please open a new issue and reference this one. More support or clarity on its necessity may prompt a review. Your understanding and cooperation are appreciated.
