### ISSUE TITLE
[BUG] - ui display error when use "afterAll" method

### ISSUE THREAD

**Issue by gantispam** [microsoft/playwright#28109]
### System info
- Playwright Version:[v1.39.0
- Operating System:Windows 11
- Browser: Chromium

### Source code

```ts

for (const key in EntityToTests) {

	if (EntityToTests[key]) {

		test.describe(`my uniq title $ {EntityToTests}`, () => {

			for (const accountType of AccountTypes) {

				test.describe(`my uniq title - ${accountType}`, () => {

					let page: Page;
					let responseCagnotte: Response;

					test.beforeAll(async ({browser}): Promise<void> => {
						page = await browser.newPage();
						await page.goto('http:://myurl.com');
					});

					test(`my uniq title - ${accountType} - my test`, async ({url, uri}): Promise<void> => {
						expect(true).toBeTruthy();
					});

					test.afterAll(async () => {
						await page.close();
					});
				});
			}

		});

	}

}
```
**Steps**
- Run the test ```with npx playwright test --ui```

**Expected**
- Test pass

**Actual**
- Test Fail on UI  (without any errors on logs or debug) but pass with ``````with npx playwright test``````

![image](https://github.com/microsoft/playwright/assets/15685552/d64b7e9f-0dfd-4cdd-b8b7-dcb9dcb5d929)

**Comment by mxschmitt** [comment]
Would it be possible that you provide us a self contained repro which we can run locally? This would help a ton in order to triage this issue, thanks!

**Comment by mxschmitt** [comment]
Closing as per above. We need a reproducible in order to triage this. Once you have that, feel free to re-file.
