### ISSUE TITLE
[Feature] Javascript evaluation context

### ISSUE THREAD

**Issue by T-Fowl** [microsoft/playwright#28102]
Hi - this is sort of both a question and a feature request.

What I am trying to do:

```typescript
// roughly translates from kotlin into typescript so ignore any syntax errors
const frame = page.frame("#id");
const result = frame.evaluate("<script referencing global variable in the frames javascript context>")
```

The problem:
The script is throwing a ReferenceError as the variable is not defined on the top-level Page Javascript context.

Research:
According to the docs on [Evaluating Javascript](https://playwright.dev/docs/evaluating), playwright will run the javascript in the "context of the web page". Is there a way to run the script in the context of a subframe?

I have tried locating the frame and calling evaluate on the Frame handle however [as per the docs](https://playwright.dev/docs/api/class-frame#frame-evaluate) this still takes a "Function to be evaluated in the page context."

Searching through the docs I the only mention of Javascript context is the section on [extending with custom selector engines](https://playwright.dev/java/docs/extensibility).

It seems there is no way to achieve this, hence my feature request of being able to specify which context scripts get run within.

**Comment by mxschmitt** [comment]
Page.frames() or Page.frame() as you are using gives you a [Frame](https://playwright.dev/docs/api/class-page#page-frames) instance. Calling [`.evaluate(`](https://playwright.dev/docs/api/class-frame#frame-evaluate) on it will execute the JavaScript inside the selected frame. Maybe you picked the wrong frame?

Maybe the unofficial Kotlin Playwright library has a bug?

**Comment by T-Fowl** [comment]
Embarrassingly - it turns out I just wasn't properly waiting for the frames content to load and scripts to execute. And all the references to "Page context" throughout the documentation seemed like a confirmation the issue wasn't on my end.

I'll close this issue but let me know if a Bug issue for the documentation would be appropriate (i.e. change "page context" to "frame context" in the documentation for `Frame.evaluate`)

Thank you
