### ISSUE TITLE
[Feature] Page getByRole with aria role 'input'

### ISSUE THREAD

**Issue by tinhuit89** [microsoft/playwright#28101]
![image](https://github.com/microsoft/playwright/assets/7766291/5b6aa009-7ed1-4c1b-8f2a-9ed2889e3b93)

I try getByRole with role 'input' and fill text for it, it's define in role of function
please help me another solution.

**Comment by mxschmitt** [comment]
An input/textarea element has the aria role `textbox`.

Have you tried using [Codegen](https://playwright.dev/docs/codegen-intro) to generate a locator for you?

**Comment by mxschmitt** [comment]
Closing as per above. Please re-file for further questions. `textbox` is the role you are looking for.

**Comment by tinhuit89** [comment]
Thanks very much, i see it can help me resolve this problem.
