### ISSUE TITLE
[Feature] Reporter that includes a flow chart / dependency tree of the tests

### ISSUE THREAD

**Issue by larsheylen** [microsoft/playwright#28105]
It is difficult to build an E2E test suite where all tests are independent of the other tests. Tests often depend on the actions performed in previous tests. To easily see these dependencies it would be nice to have a quick visual overview of the tests included in my test suite, including which tests depend on other tests. 

This would result in some flow chart that visually represents the order the tests are run in (something like the small images shown in https://playwright.dev/docs/test-projects#running-sequence, but then for all tests). Having this flow chart would also allow to quickly see if something is wrong in the structure of the test suite.

This could for example be added to the html reporter where instead of listing all tests and grouping them by the file they are in, the flow chart can be shown and used to indicate failed tests.

**Comment by mxschmitt** [comment]
This seems outside of the scope for Playwright. If you are interested in doing something like that, you can load the playwright.config and generate it based on the config we export there using some graphics library.

**Comment by birdlavv** [comment]
For anyone stumbling on this years later, here's a quick script you can use as a starting point:
https://gist.github.com/birdlavv/c9e889e878229604035bfdf19fe9c47b
