### ISSUE TITLE
[BUG] Double Click Required Instead of Single Click in Playwright Tests

### ISSUE THREAD

**Issue by rickiesystem1** [microsoft/playwright#28114]
### System info
- Playwright Version: [v1.32.0]
- Operating System: [macOS 13.6]
- Browser: [Chromium, WebKit]

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
await page.goto('https://www.mapquest.com/', { waitUntil: "domcontentloaded" });
await page.waitForSelector("#leftbar .class1 .subclass", { state: "visible" }); 
const link = page.locator(`text=string`);
await link.click();
expect(page.url()).toContain(string2);
```

**Steps**
- [Run the test]
- [...]

**Expected**
await link.click(); should click the link.

**Actual**
click() is not  is not clicking the link but dblclick() is clicking

**Comment by mxschmitt** [comment]
This code above is not self contained, closing by that. Please re-file with a self-contained reproduction, thanks for your understanding.

Also make sure to use latest playwright version.
