### ISSUE TITLE
[QUESTION] Number of workers

### ISSUE THREAD

**Issue by nezlobnaya** [microsoft/playwright#28122]
Why are only 4 workers being used by Playwright for running my tests locally, despite my MacBook Pro machine having a 2.4 GHz 8-core Intel Core i9 processor with Hyper-Threading (resulting in 16 logical cores)? The Playwright configuration is set to use '50%' of available cores by default, which should theoretically result in 8 workers. I haven't set the number of workers locally in my configuration, nor are there any environment variables influencing this setting. What could be causing Playwright to utilize only 4 workers instead of the expected 8, given that there are 16 available logical cores and threads on my system?

**Comment by nezlobnaya** [comment]
Yes, this is the machine I have. Yes, I know that snippet. Running tests in DEBUG mode gives the correct number of workers:

My CPU has 8 physical cores. But the confusion is that when I run tests in DEBUG mode, it correctly determines the number of workers 8 based on os.cpus.length 16 (see the first screenshot).  
![Screen Shot 2023-11-14 at 12 44 28](https://github.com/microsoft/playwright/assets/42080781/9e655c94-dafb-49da-997b-90def918c0e8)
However, when I run tests in the terminal Playwright uses 4 workers (see the 2nd screenshot)
![Screen Shot 2023-11-14 at 12 39 58](https://github.com/microsoft/playwright/assets/42080781/d895f490-e98e-41e1-905f-e03a5cf06589)

**Comment by mxschmitt** [comment]
You have only 4 test files, thats why it ends up only in 4 workers. I guess you have fullyParallel: false in your config? If you set it to true, we will spawn more workers.

See https://playwright.dev/docs/test-parallel for more information

**Comment by nezlobnaya** [comment]
I have `fullyParallel` set to `true` in my playwright.config.js. For some reason, Playwright spawns only 4 workers for 4 tests. I do not limit the number of workers anywhere in my codebase or CLI.

**Comment by mxschmitt** [comment]
How many tests do you have in your project? If you have 4 tests, it can't spawn more than 4 workers, since other workers would then idle. Do you have test.serial? We need to see your tests in order to judge why it does not spawn more workers. Happy to look over your project if you are able to share it, thanks!

**Comment by nezlobnaya** [comment]
@mxschmitt The mystery has been revealed. I've found the logic in Playwright that determines the number of actual workers:
https://github.com/microsoft/playwright/blob/b66839b039713382f5b877551f4c6deb35240534/packages/playwright/src/runner/tasks.ts#L253C6-L253C119

**Comment by mxschmitt** [comment]
Closing as per above, if you have 4 tests, we can only run them on 4 workers and not split them up further.
