### ISSUE TITLE
[Feature] include latest failure message when expect.poll fails

### ISSUE THREAD

**Issue by david-bezero** [microsoft/playwright#28129]
When using an expectation like:

```js
await expect.poll(() => page.title()).toEqual('Foo');
// I'm aware of toHaveTitle - this is just a simplified example
```

if it fails, the reported error is:

```
Error: Timeout 5000ms exceeded while waiting on the predicate
```

With no additional details. But the underlying `toEqual` assertion produces more useful output:

```js
expect(await page.title()).toEqual('Foo');
```

reports:

```
    Expected: "Foo"
    Received: "Something else"
```

It would be useful to be able to see this additional detail from the underlying matcher when an `expect.poll` fails.

This can be somewhat hacked with:

```js
try {
  await expect.poll(() => page.title()).toEqual('Foo');
} catch {
  expect(await page.title()).toEqual('Foo');
}
```

but obviously this is inconvenient and error-prone. Having the output built in to `expect.poll` would be much more useful.

**Comment by mxschmitt** [comment]
Your first example fails for me with: `Error: `expect.poll()` accepts only function as a first argument`

Could you provide us another snippet which fails for you?

Which Playwright version are you using?

**Comment by david-bezero** [comment]
@mxschmitt sorry - I fixed the example

This applies to `@playwright/test 1.39.0`, which I believe is the latest version.

**Comment by mxschmitt** [comment]
I can't repro:

<img width="724" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/99e49c15-475c-4321-a28b-61948e40f264">

if I navigate to google.com then I get this, are you maybe not navigating to a page before so the title is empty?

**Comment by david-bezero** [comment]
hmm, I see the same for the simplified example.

I can't share the original code sample, but the slightly-anonymised output (on a CI build) is:

```
  1) [chromium] › my-test.spec.ts:6:5 › thing ────────────────────────────────────────────────────────

    Error: Timeout 5000ms exceeded while waiting on the predicate

      30 |   await expect
      31 |     .poll(() => myPage.getRowNames())
    > 32 |     .toEqual(['item-1', 'item-2']);
         |      ^
      33 |
      34 |   [...]

        at /home/runner/work/.../tests/my-test.spec.ts:32:6
```

With no additional information.

This particular expectation is a few steps in to the test, so the page is definitely loaded. The `getRowNames` implementation is along these lines:

```js
getRowNames() {
  const rows = await this.page.locator('tbody tr').all();
  return Promise.all(rows.map((elem) => elem.locator('td.column-name').innerText()));
}
```

I assume one possible explanation might be if there are no rows at all on the page (in which case presumably even the first poll never returns, so there is no error to print)

I can continue investigating my particular issue, but perhaps this feature request can migrate to: show an explanation if `expect.poll` fails without _any_ attempt resolving, perhaps something like:

```
Error: predicate passed to expect.poll did not return any data

Call Log:
- Timeout 5000ms exceeded while waiting on the predicate
```

**Comment by david-bezero** [comment]
In fact I suspect my particular issue is one of staleness between the two `await`s in `getRowNames`:

```
```

**Comment by mxschmitt** [comment]
I see, new repro: `await expect.poll(() => page.locator('text=nooo').textContent()).toEqual('Foo');`

The issue is indeed that the predicate hangs, because we are waiting for the element to resolve. We should be able to merge both call logs to make the error more clear.

**Comment by mxschmitt** [comment]
I had a chat with our engineers and this is something which is unfortunately not easily implementable from our side.

We recommend to enable [Playwright Tracing](https://playwright.dev/docs/trace-viewer-intro) which will give you a better picture on what was failing in the first place. This will also include the logs for the textContent() call which was hanging.
