### ISSUE TITLE
[Question] How to handle SSH connection request ?

### ISSUE THREAD

**Issue by iburahim786** [microsoft/playwright#28127]
I have to connect to the server to get some information/data from the file and have to pass the information in UI automation. 

Is the playwright allowing/giving any lib suggesting to use for this above use case?

**Comment by mxschmitt** [comment]
Playwright is a Node.js library, any NPM library would work for that which is capable of doing this. I recommend reaching out to our Discord community, since this is a bug tracker for features / bugs.

**Comment by iburahim786** [comment]
Thanks, going forward will raise a question in the community forum.
