### ISSUE TITLE
[BUG] Facing issue while adding a proxy to the playwright Typescript based Framework.

### ISSUE THREAD

**Issue by nitinsagroha7** [microsoft/playwright#28123]
My issue is that i am not able to work any api cases because of proxy, i have tried giving the proxy information at global level , project level and both global and project level. But unable to fix the issue.

My proxy url format is https://username:password@host:port.

Since i cannot copy the code from client system, i tried to manually create in my local system and shared the Test file,Utility class code  &. Config file .

### System info
- Playwright Version: [v1.39.0]
- Operating System: [Windows 11 Pro]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code
**Test File** 

```ts
import { test, expect, Route } from '@playwright/test';
import { util } from '../Util/util.spec';

test.only('Get Api Test', async ({ page }) => {
    const utl=new util();
    const response=await utl.sendGetRequest('https://fakerestapi.azurewebsites.net/api/v1/Activities');
    console.log(response);    
    expect(response.status).toBe(200);
});
```

```
import { Locator, Page, expect, request } from "@playwright/test";
import * as fs from "fs";
import axios from 'axios';
import { AxiosResponse } from 'axios';

class util {

    private request: any;
    private page: any;

    loadRequestPayloadFromJSON(filePath: string): any {
        var rawData: string = "";
        rawData = fs.readFileSync(filePath, "utf-8");
        return JSON.parse(rawData);
    }

    async checkAllAPIStatusCode(apiRequests: any[]) {
        for (const apiRequest of apiRequests) {
            const response = apiRequest.response();
            await expect(response.status).toBeOK();
        }
    }

    async sendGetRequest(url: string, /*authFile: string*/): Promise<any> {
        // var response: any = '';

        // response = await this.request.get(url
        // //     , {
        // //     headers: {
        // //         Accept: '*/*',
        // //         Authorization: authFile,
        // //     },
        // // }
        // );
        // return response;

        try {
            // Use the axios library to make an HTTP GET request
            const response = await axios.get(url);
            return response;
        } catch (error) {
            console.error('Error making GET request:', error);
            throw error; // You can handle the error as needed
        }
    }

    // async sendPutRequest(
    //     url: string,
    //     header: any,
    //     req_filePath: string,
    // ): Promise<any> {
    //     var response: any = '';
    //     const payload = this.loadRequestPayloadFromJSON(req_filePath);

    //     response = await this.request.put(url, {
    //         headers: header,
    //         data: payload,
    //     });
    //     return response;
    // }

    async sendPostRequest(url: string, payload: any, customHeaders: Record<string, string> = {}): Promise<AxiosResponse> {
        try {
            // Define request configuration with custom headers
            const config = {
                headers: {
                    ...customHeaders, // Include any custom headers passed from the test
                },
            };

            // Use axios to make an HTTP POST request with custom headers
            const response = await axios.post(url, payload, config);

            // Return the response object
            return response;
        } catch (error) {
            console.error('Error making POST request:', error);
            throw error; // You can handle the error as needed
        }
    }

    async sendPutRequest(url: string, payload: any, customHeaders: Record<string, string> = {}): Promise<AxiosResponse> {
        try {
            // Define request configuration with custom headers
            const config = {
                headers: {
                    ...customHeaders, // Include any custom headers passed from the test
                },
            };

            // Use axios to make an HTTP PUT request with custom headers
            const response = await axios.put(url, payload, config);

            // Return the response object
            return response;
        } catch (error) {
            console.error('Error making PUT request:', error);
            throw error; // You can handle the error as needed
        }
    }
}

export { util };

```
- [] I provided exact source code that allows reproducing the issue locally.

```
import { defineConfig, devices } from '@playwright/test';

const globalProxy = {
  proxy: {
      server: 'http://per-context', // Placeholder string
  }
};

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
// require('dotenv').config();

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: './tests',
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Base URL to use in actions like `await page.goto('/')`. */
    // baseURL: 'http://127.0.0.1:3000',

    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',
    ...globalProxy,
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] ,
    },
      
       // Other options you might have
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    // },

    // {
    //   name: 'webkit',
    //   use: { ...devices['Desktop Safari'] },
    // },

    /* Test against mobile viewports. */
    // {
    //   name: 'Mobile Chrome',
    //   use: { ...devices['Pixel 5'] },
    // },
    // {
    //   name: 'Mobile Safari',
    //   use: { ...devices['iPhone 12'] },
    // },

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { ...devices['Desktop Edge'], channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { ...devices['Desktop Chrome'], channel: 'chrome' },
    // },
  ],

  /* Run your local dev server before starting the tests */
  // webServer: {
  //   command: 'npm run start',
  //   url: 'http://127.0.0.1:3000',
  //   reuseExistingServer: !process.env.CI,
  // },
});
```

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

[Describe expected behavior]

**Actual**

[Describe actual behavior]

**Comment by mxschmitt** [comment]
This does not look like a Playwright bug since you are using axios. See here for the axios docs: https://axios-http.com/docs/req_config

**Comment by nitinsagroha7** [comment]
Hi,

Issue is not with the axios that i am using , i am able to execute the same code outside in my local system but the issue is client system where proxy applies. I want solution from proxy perspective, how can i execute the playwright typescript API code in systme having proxy like https://username:password@host:port/

I have tried adding proxy at global level by updating config.ts file

const globalProxy = {
  proxy: {
      server: 'http://per-context', // Placeholder string
  }
};


  ...globalProxy,

Than i tried adding at project level , and tried adding at project and global level both. But unable to get any solution.

another apporach i tried if setting up conf file 
export const config = {
    // API endpoint URL
    apiUrl: 'https://api.example.com',
  
    // Proxy settings (optional)
    proxy: {
      server: 'http://your_proxy_host:your_proxy_port',
    },
  
    // Other configurations specific to your API tests
    // ...
  
    // Playwright launch options (only relevant if you need to open a browser)
    playwright: {
      // Specify the browser you want to use (chromium, firefox, webkit)
      browser: 'chromium',
  
      // Add any other Playwright launch options here if needed
      // ...
  
      // Headless mode (set to true if you don't want to see the browser)
      headless: true,
    },
  };
   

and than using this file is test class 

import axios from 'axios';
import { config } from '../api.conf'; 
import { expect, test } from '@playwright/test';

async function runAPITest() {
  const { apiUrl, proxy } = config;

  // Axios instance with proxy settings
  const axiosInstance = axios.create({
    httpAgent: proxy ? new (require('http').Agent)({ proxy: proxy.server }) : undefined,
    httpsAgent: proxy ? new (require('https').Agent)({ proxy: proxy.server }) : undefined,
  });

  try {
    // Make API requests using axiosInstance
    const response = await axiosInstance.get(`${apiUrl}`);
    console.log('API Response:', response.data);
    expect(response.status).toBe(200);
  } catch (error) {
    console.error('Error:', error.message);
  }
}

test.only('Get Api Testq', async ({}) => {
    console.log('before');
    await runAPITest();
    console.log('after');
});

Even after using this i am getting error code 407 which is proxy authentication error.

**Comment by mxschmitt** [comment]
I still see only axios code in your snippet which you provided. The Playwright config has nothing to do with the axios config/s.

**Comment by nitinsagroha7** [comment]
I have shown you couple of approaches i used to handle proxy and Api Request with Playwright and Typescript code.

Here is another approach i tried.

Basically, i need help with How i can handle proxy on client system while writing a API code using Playwright Typescript. I have gone through so many approaches with no luck.

Another approach using Request Fixture.

import { APIActions } from "../Util/APIActions";
import { test } from '@playwright/test';

const apiActions = new APIActions();

**Test File** 
test(`@API getUsers`, async ({ request }) => {
    const response = await request.get(`https://jsonplaceholder.typicode.com/todos/1`);
    await new Promise(resolve => setTimeout(resolve, 5000)); // 5-second delay
    await apiActions.verifyStatusCode(response);
    //console.log(response);

    //* Body Response Params and Body Response Headers are stored in single text file separated by #
    // const responseBodyParams = (await apiActions.readValuesFromTextFile(`getUsers`)).split(`#`)[0];
    // await apiActions.verifyResponseBody(responseBodyParams, await response.json(), `Response Body`);

    // const responseBodyHeaders = (await apiActions.readValuesFromTextFile(`getUsers`)).split(`#`)[1];
    // await apiActions.verifyResponseHeader(responseBodyHeaders, response.headersArray(), `Response Headers`);
});

**Util Class**
import fs from 'fs';
import { APIResponse, expect } from '@playwright/test';

export class APIActions {

    async verifyStatusCode(response: APIResponse): Promise<void> {
        await expect(response, `200 Status code was not displayed.`).toBeOK();
    }

    async verifyResponseBody(expectedResponseBodyParams: string, responsePart: JSON, responseType: string): Promise<void> {
        let status = true;
        let fieldNames = `Parameter`;
        const headers = expectedResponseBodyParams.split("|");
        const responseToString = JSON.stringify(responsePart).trim();
        for (let headerKey of headers) {
            if (!(responseToString.includes(headerKey.trim()))) {
                status = false;
                fieldNames = fieldNames + `, ` + headerKey;
                break;
            }
        }
        expect(status, `${fieldNames} was not present in ${responseType}`).toBe(true);
    }
