### ISSUE TITLE
[question] How to retrieve the testId from the test report?

### ISSUE THREAD

**Issue by swmachine1401** [microsoft/playwright#28126]
After running 'playwright show-report,' I noticed that the testId for each test appears to be random.
such as：http://localhost:9323/#?testId=619e92051c008cb6c223-478e2851c39a4e244f48
I want to retrieve the testId after generating a test report. How can I do that within the test?
`
test('case', async ({page}) => {
    // 
    let testId = ....;
}
`

**Comment by swmachine1401** [comment]
> https://playwright.dev/docs/api/class-testinfo#test-info-test-id
> 
> ```
> test('case', async ({ page }, testInfo) => { //  let testId = testInfo.testId; }
> ```

Thank you very much

**Comment by mxschmitt** [comment]
Closing by that, please re-file for more questions!
