### ISSUE TITLE
[Question]How to runs tests step in parallel?

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#28136]
Hi,I want to make some test step in parallel.For example:
```
test('test ABCD', async ({ page }) => {
  await test.step('A', async () => {
    // ...
  });

  await test.step('B', async () => {
    // ...
  });

  await test.step('C', async () => {
    // ...
  });

  await test.step('D', async () => {
    // ...
  });
});

```
I want A and B to run in parallel(that will save time), then C and D run in serial. How can I achieve this?

**Comment by mxschmitt** [comment]
Running steps in parallel is not recommended, since a user also has no option to do things in parallel, they would race etc. 

Since this is no bug / feature request, I'm going to close it. For further questions, we recommend Discord: aka.ms/playwright/discord.
