### ISSUE TITLE
[Question] Disable Password and remember credit card popups

### ISSUE THREAD

**Issue by siddharth2023** [microsoft/playwright#28140]
To disable the save `Password` popup in Google Chrome within your Selenium Tests you can use the following piece of code block:

https://stackoverflow.com/questions/46595113/how-to-disable-chromes-save-password-popup-in-selenium-webdriver-python

How do I achieve the same in Playwright for:

`Password`
`Remember credit card details`

It isn't affecting my tests but quite annoying when I write/debug scripts and I have to always close them as sometimes they hide elements behind them, mostly header elements.

**Comment by mxschmitt** [comment]
I tried various ways about triggering the wave password dialog but was unable to. How does your website look like? Are you using an persistent context? Could you share us exactly what kind of steps you perform? How does your test/script look like?

**Comment by siddharth2023** [comment]
So here's the test https://github.com/siddharth2023/playwrightProjects/blob/main/tests/Login.spec.ts


I added this `ignoreDefaultArgs: ["--enable-automation"],` in the fixture https://github.com/siddharth2023/playwrightProjects/blob/main/tests/testFixture.ts so that I don't see this info bar.


<img width="448" alt="Screenshot 2023-11-14 at 5 01 51 PM" src="https://github.com/microsoft/playwright/assets/122398930/bd2bdaba-cb1d-49a3-8ab2-b359a4bbf844">


However I started seeing the save login pop up, the energy saver pop and the save credit card pop up. Are there any flags to disable all of these?

<img width="318" alt="Screenshot 2023-11-14 at 5 18 25 PM" src="https://github.com/microsoft/playwright/assets/122398930/7cd5364e-de39-4c2f-ae0d-712db423ebcf">
<img width="464" alt="Screenshot 2023-11-14 at 4 57 10 PM" src="https://github.com/microsoft/playwright/assets/122398930/9dae4b00-07bf-48d5-87c4-d55d4af36fdd">

**Comment by mxschmitt** [comment]
This seems outside of the scope for Playwright then, modifying launch arguments is at own risk and results in such behaviour change.
