### ISSUE TITLE
[Question] Bypassing ERR_CERT_AUTHORITY_INVALID error

### ISSUE THREAD

**Issue by MichaelHof** [microsoft/playwright#2814]
Hi there,

I am new to playwright and have started with following code:
```
const { chromium } = require('playwright');

(async () => {
    const browser = await chromium.launch({ headless: false, slowMo: 50 });
    const context = await browser.newContext({ ignoreHTTPSError: true });
    const page = await context.newPage();

    await page.goto('https://my-dummy-page.test');
    await page.screenshot({ path: 'example.png' });
    await browser.close();
})();
```

Result: Browser shows "This is not a secure connection" page and playwright throws error '(node:20028) UnhandledPromiseRejectionWarning: Error: net::ERR_CERT_AUTHORITY_INVALID at https://my-dummy-page.test'

Am I missing something? Is the test syntax wrong?

**Comment by mxschmitt** [comment]
Hi, you have a typo (forgot the last **s** at the end) in your option for ignoring invalid HTTPS certificates.
`ignoreHTTPSError ` -> `ignoreHTTPSErrors`

We also recommend to either use TypeScript or use `// @ts-check` at the beginning of your JavaScript file. Then your editor like VSCode will check your code for typing issues like incorrect context options. See some examples here: https://try.playwright.tech

**Comment by MichaelHof** [comment]
Oops :see_no_evil: that was an easy fix, thanks
