### ISSUE TITLE
[BUG] Playwright CT does not support ES5 "require is not defined"

### ISSUE THREAD

**Issue by rasmusvhansen** [microsoft/playwright#28151]
### System info
- Playwright Version: [v1.39.0] experimental-ct-react
- Operating System: [Ubuntu, MacOS.]
- Browser: [Chromium]
- Other info: React, Vite, Typescript importing https://www.npmjs.com/package/most ES5 module

### Source code

I have created a minimal repro in Codesandbox

https://codesandbox.io/p/sandbox/aged-leaf-98lcc3?file=%2Fplaywright%2F.cache%2Fassets%2FMyComponent-32fde03c.js%3A1%2C1

**Steps**
- npm run test-ct

**Expected**

Test runs even though it imports ES5 module (most.js)

**Actual**

Test fails to run with error `Error: ReferenceError: require is not defined`.
When looking at the code generated for the component (playwright/.cache/assets folder), it contains a require statement on line 669:
`const getGlobalThis$1 = require('globalthis').getPolyfill;`

**Comment by mxschmitt** [comment]
Looks like their library is weirdly bundled. If you import the following it works:

```ts
import { fromEvent } from "most/dist/most";
```

I can also reproduce it with normal Vite:

1. npm run build
2. npm run preview

<img width="498" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/c835b1a5-9a5f-4295-8a9f-19a46e52398c">

<img width="982" alt="image" src="https://github.com/microsoft/playwright/assets/17984549/85b2e157-4640-49fe-a8dd-f8ff42a9eae9">

Or use the workaround from above. This is unfortunately not actionable for us, I recommend reaching out to their bug tracker.
