### ISSUE TITLE
[Feature] Automatic notification of relevant PR-owners after nightly test run.

### ISSUE THREAD

**Issue by ufst-ask** [microsoft/playwright#28157]
We are about to convert from Selenium to Playwright on a rather big project.
One of the things we want to achieve is to automatically notify developers when their pull request may have resulted in a playwright test failing.
Meaning, for the comprehensive test suites we run each night, not the ones for each pull request.
The entire product is divided into business areas with assigned IDs. When a test which didn't fail on "yesterdays build", now fails on "todays build". Then we want an automatic notification to go out to the code owners and/or authors of the pull requests for that business area.
Thereby achieving automatic relevant alerts for developers to act upon. Hence increasing the chances that they will act swiftly to correct their mistakes.

Is this already possible? I can't find it anywhere. Though I'm gonna go through the list of third party reporting tools to see if they can and ask them.

If I were to develop this "feature" myself, I would probably use playwright as a RPA to go automatically through the latest report and when finding tests failing which didn't fail before. I would ideally have PW find the code owners of pull request affecting that business area. Alternatively email the scrum masters responsible for the given business area.

**Comment by mxschmitt** [comment]
This is outside of the scope for the Playwright project. I recommend creating a [custom reporter](https://playwright.dev/docs/test-reporters), assigning owners as annotations to tests and using some third-party service to notify them once they are failing.

**Comment by ufst-ask** [comment]
Okay thank you for the quick response, I will look into that.
