### ISSUE TITLE
[Feature]Add config option to specify which test/step to expand in UI mode and HTML reports

### ISSUE THREAD

**Issue by Bonjour123** [microsoft/playwright#28159]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Following playwright recommendations, I extensively use "test steps". Before I would use describe blocks but that would be more a workaround than a clean solution.

The problem I have with test steps is that they are not expanded by default in the results and no options seem to allow for that. This is true for the --ui mode, but also for the HTML reporter, and in webstorm [Test Automation plugin](https://plugins.jetbrains.com/plugin/20175-test-automation). In other reporters (non interactive one), they are not shown at all most of the time.

One useful solution could be to provide a config option, either an option 'expand':
 ( (type: "describe"|"test"|"step", title, depth)=>boolean) || boolean ).

Describing the whole testing tree is really a must for these following needs:
- Get an overview of the tests, their complexity and an idea of the current coverage
- Easily spot missing pre-requises or inner steps
- Easily locate a failing test and all the testing steps that have previously succeed in order to better understand the origin of the failure.

Of course, the "expand" option could also apply a level deeper, i.e. up to the assertions level (expect, ...)

**Comment by mxschmitt** [comment]
Since the Webstorm plugin is not maintained by us, I see this as a feature request for HTML report?

I think we should automatically expand HTML report steps if they were failing like we do in trace-viewer.

Would that work for you?

**Comment by Bonjour123** [comment]
Yes, that would be a feature request for the HTML report but more importantly for the --ui mode. I mentioned the Webstorm plugin to highlight I currently don't have working alternative.

About expanding on failing, it is already the case, at least in --ui mode. But in my opinion, that wouldn't fill the two first needs I described earlier:
- Get an overview of the tests, their complexity and an idea of the current coverage
- Easily spot missing pre-requises or inner steps
