### ISSUE TITLE
[Feature] :has-exact-text("text")

### ISSUE THREAD

**Issue by wozprzemek** [microsoft/playwright#28164]
This is esentially a duplicate of issue #14044. The feature was ultimately not implemented, but the issue was closed. 

I also ran into this myself and the solutions provided there, while helpful, didn't fully work for me.

I would be willing to take up the task of implementing the :has-exact-text("text") feature, would it be possible for issue #14044 be reopened, or what would be the appropriate option?

**Comment by mxschmitt** [comment]
How does your DOM look like?

Would `page.getByText('Hello', { exact: true });` work for your use-case?

**Comment by wozprzemek** [comment]
Here is a simplified example, let's say I want to be able to grab the `inner` container which contains the exact text `1` and then locate and click the checkbox (or any other element found there) inside this container. I have not been able to achieve it using your suggestion.

```
<div class="outer">
    <div class="inner">
        <p>1</p>
        <input type="checkbox" />
    </div>
    <div class="inner">
        <p>123</p>
        <input type="checkbox" />
    </div>
</div>
```

In my understanding, something like `outer.locator('.inner:has-exact-text("1")')` would be perfect for such situations.

**Comment by larsheylen** [comment]
In your specific case, I think the following would work:

`page.locator('.inner').filter({has: page.getByText('1', {exact: true})}).locator('input').click();`

**Comment by wozprzemek** [comment]
Thanks, it works for the simple example. However, I still think that such a feature would provide a nice straight forward solution as an alternative version of `has-text`, considering this is the second issue requesting it.

**Comment by mxschmitt** [comment]
We think [this](https://github.com/microsoft/playwright/issues/28164#issuecomment-1814201968) is a great solution for this use-case. If you have another example, let us know with another repro and we can help you finding a matching locator the next time.

> To be clear, I'm willing to implement it myself if possible.

Happy to hear! If you see another Playwright issue which has the open-for-pull-request label, feel free to raise a PR. For other features, it might make sense to ping us beforehand, so we can align on the implementation. Thanks!

**Comment by sergtimosh** [comment]
as I [mentioned](https://github.com/microsoft/playwright/issues/14044#issuecomment-1931960240) in the parent issue, regex is a powerfull instrument to match whatever text configuration one needs. 
exact text matcher is as simple as `/^yourText$/` or `new Regex('^yourText$')`
