### ISSUE TITLE
[BUG] Clicking on a unique element with many other elements on top of it causing scrolling malfunction. 

### ISSUE THREAD

**Issue by ATARARHRB** [microsoft/playwright#28168]
### System info
- Playwright Version: v1.37.1
- Operating System: Windows
- Browser: Chromium
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Expected**

Apologies, I know this isn't a lot of information to go off of. 
We have a calendar for scheduling as part of an internal application. You click on a row, it opens a dialog, it allows you to schedule an event by opening a dialog. The whole week's slot for a particular time is one row that can be clicked (it does not matter where; it is just for opening a dialog) 
```js
await page.locator('[data-time="14:00:00"]').nth(1).click();
```
this works fine when there are no elements already scheduled, events that are scheduled make little blocks on the calendar. You can have as many events at the same time as you want, and even if you click on the event, it should open the dialog. The number of events doesn't matter, since clicking anywhere opens the dialog. 

That said, if there are already a lot of elements on the calendar, then playwright can no longer click that block of time anymore. However, if there are no events, playwright clicks it just fine. I have a feeling it is something to do with the visibility of elements or the calendar entries overlapping each other in a way that playwright does not know how to handle. Since I am using a CSS selector to click it, I thought it should ignore some of the stuff that might be 'on top'.

I know it isn't much to go off of, and I'm not in a position to be posting source code and the only relevant test step I have is the click I posted above. I understand there isn't a good way to reproduce it locally with what I'm given, so my question is geared more to hoping that somebody has seen this in the past and can offer some insight on what is up with the playwright infinite scroll as it attempts to click something issue and how to avoid it. I have attached two videos of what this looks like when I click into the calendar locally vs through playwright in this submission. 

https://github.com/microsoft/playwright/assets/131192142/d1b20305-19f9-44bd-87b4-5aa667904c39

**Actual**

Starts infinite scrolling trying to find elements that are covered by other elements. 

https://github.com/microsoft/playwright/assets/131192142/52f0bc48-b491-4065-af7e-e7f5f2800283

**Comment by mxschmitt** [comment]
I think we unfortunately need a clear reproduction in order to triage this issue further. 

Playwright definitely tries to click but is unable to click, you will see more details when you look e.g. at the trace, set the `DEBUG=pw:api` env var or use the Inspector.

Is your website maybe using the CSS property `zoom` by any chance? Then it might be  related to https://github.com/microsoft/playwright/issues/21192.

**Comment by marko-simic** [comment]
You can try click with ` force: true `
```javascript
await page.locator('[data-time="14:00:00"]').nth(1).click({ force: true });
```

**Comment by ATARARHRB** [comment]
I think `force: true` did the trick. Thank you for the tip. I'll report back or open another issue (hopefully with a better way to reproduce it) if I run into more issues.
