### ISSUE TITLE
[Question] What is the reasoning behind toHaveScreenshot comparison strategy?

### ISSUE THREAD

**Issue by marcusNumminen** [microsoft/playwright#28160]
Hi!
I'm wondering about the reasoning behind toHaveScreenshot comparison strategy? From the doc (https://playwright.dev/docs/api/class-pageassertions#page-assertions-to-have-screenshot-1) we can read:
"This function will wait until two consecutive page screenshots yield the same result, and then compare the last screenshot with the expectation."

Why not take screenshots until we get a match to the golden picture?

In my case we had a situation that a thumbnail generation took a bit time and playwright failed the test since it could take two consecutive picture without the thumbnail and then took the last one of the screenshots and compared that the golden picture (that had the thumbnail). We could see from the trace that right after the test marked as failed we got our thumbnail.

**Comment by mxschmitt** [comment]
Have you tried using waitFor to wait until the thumbnail generation completed?

As a last resort, you can also fallback to waitForEvent('response') if its something what happens on the server side?
