### ISSUE TITLE
[BUG/QUESTIONS] `page.routeFromHAR()` is not properly recording/replaying POST requests that modify server-side state

### ISSUE THREAD

**Issue by JulieMaticJSQ** [microsoft/playwright#28167]
### System info
- Playwright Version: v1.39
- Operating System: macOS 14.1
- Browser: Chromium, Firefox, WebKit (with different symptoms)
- Other info: `page.routeFromHAR()` seems to record/replay most requests properly, but any requests that modify server-side state do not record properly in Chrome and do not replay properly in Firefox/WebKit.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";
import { ARTIFACT_DIRECTORY } from "./fixtures/playwrightConstants";

/**
 * Read environment variables from file.
 * https://github.com/motdotla/dotenv
 */
dotenv.config();

// Output directory for screenshots, videos, traces, and reports
const outputDir = ARTIFACT_DIRECTORY;

/**
 * See https://playwright.dev/docs/test-configuration.
 */
export default defineConfig({
  testDir: "./integration",
  outputDir,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : 3,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: [
    [
      "./report.ts",
      {
        outputJSON: true,
        generateHTML: true,
        outputFileName: "playwrightResults.json",
        reportDir: outputDir,
      },
    ],
  ],
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: "on-first-retry",
    screenshot: "only-on-failure",
    video: "retain-on-failure",
    timezoneId: "America/Los_Angeles",
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: "setup",
      testMatch: /global.setup\.ts/,
    },

    {
      name: "chromium",
      use: {
        ...devices["Desktop Chrome"],
      },
      dependencies: ["setup"],
    },

    // {
    //   name: 'firefox',
    //   use: { ...devices['Desktop Firefox'] },
    //   dependencies: ["setup"],
    // },

    // {
    //  name: 'webkit',
    //  use: { ...devices['Desktop Safari'] },
    //  },
});
```

**Scrubbed test file**

```js
import { test, expect } from "@playwright/test";

test.describe("Test mocking", () => {
  // Close the page context so HAR file gets recorded when running from VSCode
  test.afterEach(async ({ page }) => {
    await page.context().close();
  });

  test("Test mocking", async ({ page }) => {
    // Go to page
    await page.goto(url);

    // Login
    /* Perform login steps */

    // Start mocking
    await page.routeFromHAR("mocks/har.har", {
      // toggle to true to record new HAR file
      update: false,

      // tried with both setting url and capturing all requests
      // url: "**/account/add",

      updateMode: "full",

      // set to abort instead of fallback to see what requests aren't mocking as expected
      notFound: "abort",
    });

    // Add a new account
    await page.waitForURL(url);
    await page.getByRole("button", { name: "New account" }).click();
    await expect(page.getByRole("dialog")).toBeVisible();
    await expect(
      page.locator("[data-cy='modal-title']").getByText("Add a new account"),
    ).toBeVisible();
    await page.getByLabel("Account name").fill("123 Mock");
    await page.locator("[data-cy='modal-button-save']").click();

    // Verify the account was created
    await page.waitForURL("**/account/*");
    const detailsRow = page
      .locator("[data-cy='details-row']")
      .filter({ hasText: "Account name" });
    await expect(detailsRow).toContainText("123 Mock");

    // Sleep 5 seconds to make sure everything is recorded
    await new Promise((f) => setTimeout(f, 5000));
  });
});
``
});
```

**Steps**
- Run test once with `update: true` in call to `page.routeFromHAR()` to record the HAR file
- Run test again with `update: false` in call to `page.routeFromHAR()` to use mocking

**Expected**

All network requests, including POST requests that modify server-side state, should recorded in the HAR file and should be replayed so that tests that modify server-side can run multiple times without being destructive to themself or other tests.

**Actual (Chrome)**
Network requests that do not modify server-side state replay as expected, but POST requests that modify server-side state do not record properly. The request headers and body seem fine, but the response body is not recorded and there is no `_file` listed under `content`. 
```
"response": {
          "status": 200,
          "statusText": "OK",
          "httpVersion": "HTTP/1.1",
          "cookies": [],
          "headers": [
            { "name": "Cache-Control", "value": "max-age=0, must-revalidate, no-cache, no-store" },
            { "name": "Connection", "value": "keep-alive" },
            { "name": "Content-Encoding", "value": "gzip" },
            { "name": "Content-Type", "value": "application/json" },
            { "name": "Date", "value": "Wed, 15 Nov 2023 16:23:40 GMT" },
            { "name": "Expires", "value": "Wed, 15 Nov 2023 16:23:39 GMT" },
            { "name": "Last-Modified", "value": "Wed, 15 Nov 2023 16:23:39 GMT" },
            { "name": "Pragma", "value": "no-cache" },
            { "name": "Server", "value": "nginx/1.23.4" },
            { "name": "Transfer-Encoding", "value": "chunked" },
            { "name": "X-Hostname", "value": "<someID>" },
            { "name": "X-Version", "value": "@" }
          ],
          "content": {
            "size": -1,
            "mimeType": "application/json",
            "compression": 0
          },
          "headersSize": 393,
          "bodySize": 74,
          "redirectURL": "",
          "_transferSize": 467
        },
```
As such, when running the test using mocking, the POST request gets aborted (it is listed in the trace viewer and says aborted).

**Actual (Firefox)**
All of the network requests seem to be recorded as expected, but POST requests that modify server-side state do not replay properly. When the test clicks the save button that would trigger that request, that POST request isn't listed in the trace viewer at all.

**Actual (Safari)**
All of the network requests seem to be recorded as expected, but when running the test against the mock, there is an error:
```
Error: Cannot fulfill with redirect status: 304
```

## Theories/questions
- Is the Chrome recording issue related to this? https://github.com/microsoft/playwright/issues/27845
- For Firefox, could the issue be a random ID in the `Content-Type` header and `mimeType` in `postData`? For example, the `Content-Type` header and `mimeType` both have a value of `multipart/form-data; boundary=----WebKitFormBoundary<randomID>`
- Are redirects supported for HAR recording/replay? Is the error about redirect only an issue with Safari, or should I be getting this error with all 3 browsers?
- Confirmed that for the request that isn't recording/replaying properly that it's the only request that has that `method` and `url`
- Timings for the POST request were: `"timings": { "dns": -1, "connect": -1, "ssl": -1, "send": 0, "wait": 259.028, "receive": 0.041 }`
- Tried adding a delay to make sure the recording finished before the test ended
- **Biggest question**: Is what I'm trying to do supported, or should HAR files only be used to mock network activity that don't modify server-side state?

**Comment by mxschmitt** [comment]
I appreciate the effort you've put into finding and reporting this issue. Unfortunately, we need a clear reproduction of the problem in order to triage it further. Would it be possible for you to provide that?

**Comment by JulieMaticJSQ** [comment]
I can't provide reproduction steps with my company's application/test code, so I've created a repository where I was able to reproduce the issue against trello.com. Please let me know if you need anything else.

### Repository
https://github.com/JulieMaticJSQ/playwrightIssueWithHARMocking/tree/main 

### Set up
1. Clone repository
2. Run `npm install` to install dependencies
3. Run `npm playwright install` to install browsers

### Reproduce mocking issue
Run test "Add a card" in `trello.spec.ts`. The HAR file has already been recorded and committed to the repo, so `update` is set to `false` in `page.routeFromHAR()`

**Expected behavior**: Test should pass without actually saving the Trello card (use case: this is a UI test that is trying to validate what happens in the UI when a card is created)

**Actual behavior**: The card does not get created and the test fails

**Comment by JulieMaticJSQ** [comment]
Update: This might be an OS-specific issue, as someone on the [discord post](https://discord.com/channels/807756831384403968/1174023225726992394/1174428836025344000) I made said they couldn't reproduce my issue on Ubuntu 23.04. However, I'm not sure because we set up a GHA that runs against ubuntu-latest and it still failed. I haven't had a chance to dig into the failure thought to make sure it's failing for the same reason as I see locally.

**Comment by JulieMaticJSQ** [comment]
It's also worth noting that I was able to get a better HAR recording from Chrome locally by switching to the public npm registry, which also updated my Playwright version to 1.40. The test still failed locally when running against the HAR file though.

**Comment by JulieMaticJSQ** [comment]
I've updated the test in the repo again to hopefully make things easier to see without changing code. New steps:
1. Run tests in spec file `trello.spec.ts`
2. Notice: 1st test runs successfully and creates new HAR file
3. Notice: 2nd test runs unsuccessfully. Locally for me, the test fails because the card count isn't correct. In the GHA, the test passes but shouldn't have. You can see in the screenshot of the GHA run that the text was typed into the field, but pressing Enter didn't actually put the card in the list. Link to GHA run: https://github.com/JulieMaticJSQ/playwrightIssueWithHARMocking/actions/runs/6932118896

**Comment by mxschmitt** [comment]
Thanks for your input. The reproduction scenario provided is unfortunately too complex and involves external sites, making it hard to isolate the issue.

Could you please simplify it, so it only involves a website in the same repository? A small or minimal project demonstrating the issue would be ideal.

I'll close it in the meantime. Thanks for understanding and your cooperation and don't hesitate to re-file.

**Comment by JulieMaticJSQ** [comment]
@mxschmitt Can you confirm whether or not this use case is supported? I can try to find a sample project to use, but the sample projects I've found don't do network calls or are very involved to set up. I don't want to spend more time only to find out later that this was never supported. If you can confirm my use case is supported or can point me to a sample project with network calls (maybe 1 that people regularly use when submitting issues), I can spend more time on this.

**Comment by kristjanreinhold** [comment]
Ran into exactly same thing. I was able to migrate from playwright to cypress and it does work easily there.

```
cy.intercept(
      {
        method: 'POST', 
        url: 'api/category/2513?count=30&locale=et&page=1&sorting=ORDER_BY_NAME_ASCENDING'
      },
      { fixture: 'category-ascending.json' }
    ).as('getCategoriesAscending') // and assign an alias
```
