### ISSUE TITLE
I want to deactivate this request 'page.on("request", lambda request: page_on_response(request))' after find my specific request.

### ISSUE THREAD

**Issue by ramprakashyadav** [microsoft/playwright#28186]
I try to find json file with the help of this request 'page.on("request", lambda request: page_on_response(request))'
and here is my code i want to deactivate this request.
def page_on_response(request):
    url = request.url
    if 'graphql/intlCTFlightListSearchPoll' in url and request.method == 'POST':
        if re.search('"flightListSearch"', str(request.response().text())) is not None:
            sc_list.append(request.response().text())
            logger.info(f"printing len of sc_list in oneway, ---{len(sc_list)}---")

**Comment by mxschmitt** [comment]
You can abort network requests, see here: https://playwright.dev/python/docs/network#abort-requests

**Comment by ramprakashyadav** [comment]
Hi @mxschmitt 
I raised a request to find a specific request with page.on it works parallel with code i want to search this request
if 'graphql/intlCTFlightListSearchPoll' in url and request.method == 'POST':
if re.search('"flightListSearch"', str(request.response().text())) is not None:
sc_list.append(request.response().text())
i want after append text on sc_list i want to deactivate page.on request .
we use page.route to block requests if i'm not wrong? but i want to deactivate after find this request all page.on

**Comment by ramprakashyadav** [comment]
page.on('requestfinished')[#](https://www.cuketest.com/playwright/docs/api/class-page/#page-event-request-finished)
type: <[Request](https://www.cuketest.com/playwright/docs/api/class-request)>
Emitted when a request finishes successfully after downloading the response body. For a successful response, the sequence of events is request, response and requestfinished.


This can work?

**Comment by mxschmitt** [comment]
page.on('requestfinished')/page.on('request')/page.on('response') is not usable for aborting requests. You need to use page.route() for it.

You also have access to the `request` object inside `page.route`.

Something like this should work for you:

```python
from playwright.sync_api import Route

def handle_route(route: Route):
    if ...
        route.abort()
    else:
        route._continue()
page.route("**/*", handle_route)
```

You can also change the `**/*` so it only matches on a specific URL. Also inside the `handle_route` you can adjust the condition to your liking. Would that work for you?

**Comment by ramprakashyadav** [comment]
I created function there i call it many times to find a specific request, I try to neglect previous request and want to find new one everytime. 


Here is my code 
```
def page_on_response(route: Route):
    request = route.request
    if 'graphql/intlCTFlightListSearchPoll' in request.url and request.method == 'POST':
        if re.search('"flightListSearch"', str(request.response().text())) is not None:
            sc_list.append(request.response().text())
            logger.info(f"printing len of sc_list in oneway, ---{len(sc_list)}---")
        route.abort()
    else:
        route.continue_()


page.route("**/*", page_on_response)
```

but it doesn't work.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
