### ISSUE TITLE
[internal] Look into WebKit macOS bots

### ISSUE THREAD

**Issue by mxschmitt** [microsoft/playwright#28187]
- Received request to deprovision: The request was cancelled by the remote provider.
  - https://github.com/microsoft/playwright/actions/runs/6886192053
  - https://github.com/microsoft/playwright/actions/runs/6884008401
  - https://github.com/microsoft/playwright/actions/runs/6886186250
- The hosted runner: GitHub Actions 42 lost communication with the server. Anything in your workflow that terminates the runner process, starves it for CPU/Memory, or blocks its network access can cause this error.
  - https://github.com/microsoft/playwright-browsers/actions/runs/6863212712
- The hosted runner encountered an error while running your job. (Error Type: Disconnect).
  - https://github.com/microsoft/playwright-browsers/actions/runs/6865144042
- Runner GitHub Actions 37 did not respond to a cancelation request with 00:05:00. 
  - https://github.com/microsoft/playwright-browsers/actions/runs/6861525221
  
Next steps:

- add proper network/cpu/memory/open ports logging while executing the tests.
  - Similar to https://github.com/microsoft/playwright-browsers/pull/733
- See if we can reproduce it locally, I just saw a lot of prewarmed content processes lying around while running the tests, seemed fine.
  ![telegram-cloud-photo-size-2-5377412446479830778-y](https://github.com/microsoft/playwright/assets/17984549/1a6a6e9b-2bdf-4601-b2e1-bb93e25b862d)
- It seems reproducible on macOS 12/13 so far, I tested on 14, maybe its caused by that. The memory/cpu consumption seemed fine.

**Comment by mxschmitt** [comment]
might be an upstream issue: https://github.com/actions/runner-images/issues/7754#issuecomment-1699344713

**Comment by mxschmitt** [comment]
More:
- https://github.com/microsoft/playwright/actions/runs/7108632159/job/19352256538
- https://github.com/microsoft/playwright/actions/runs/7108717632/job/19352491209
- https://github.com/microsoft/playwright/actions/runs/7108717627/job/19352486018

**Comment by mxschmitt** [comment]
Filed as https://support.github.com/ticket/personal/0/2687930.

**Comment by mxschmitt** [comment]
Update: GitHub forwarded it to the Engineering team.

**Comment by pavelfeldman** [comment]
Max 👀 enough.
