### ISSUE TITLE
[Feature/QUESTION] How to Auto detect API request details and log?

### ISSUE THREAD

**Issue by Askarov5** [microsoft/playwright#28196]
I'm using Playwright for API testing (UI will be added in later stage of dev). While VS Code Playwright extension gave a good control over the steps and debugging, I'm understanding that logs could be improved by auto detecting api request details like `:method :url :status :res[content-length] - :response-time ms`. The logging in express.js with the combination of Morgan + Winston can be a good example for it. Is there any way to auto detect request details and log or add them to report? 
Seeing request details ('`:method :url :status :res[content-length] - :response-time ms`') are enough to understand the mistake/mistype you've made (could be a flag ` --log-details`), rather than re-running each test in debug mode.
Auto detection would've been better than logging manually (and to follow DRY principles):
`test.info().annotations.push({ type: 'Request URL: ', description: url});`

**Comment by mxschmitt** [comment]
Do you want to see quicker what the cause was when a test is failing? Are you using `toBeOK`?

`await expect(response).toBeOK();`

We'd love to understand the use-case first better before adding logging APIs / integrations.

**Comment by Askarov5** [comment]
Yes, I'm using `expect(await response.status()).toBe(200)`. But that's not the point here. Even after I see the response status is 400 (or any other than expected), I need to re-run the test in debug mode to see if I'm sending the right request (URL, method, payload, etc). Seeing more details in logs (even for passing tests), makes LOGS more valuable to save and useful to read, rather than just seeing the exception. 
it would be perfect to see something like the following for API tests:
Request: (`:method :url :status`) + option to log payload
Exception: (as it is now)

When we do integration tests (hit multiple endpoints in the test) or run tests in different environments, would be nice to see what URL or endpoint you're hitting in logs.

**Comment by mxschmitt** [comment]
There is a difference between

    expect(await response.status()).toBe(200)

and

    await expect(response).toBeOK();

the latter will show you all the request and response headers, response body, status code etc. when it fails. This should help significantly for debugging. Could you try that?

**Comment by Askarov5** [comment]
Thank you!!!
