### ISSUE TITLE
[Feature] Trace option to record all actions inside description

### ISSUE THREAD

**Issue by adequatica** [microsoft/playwright#28195]
Hello, a current trace is recorded for a single `test` function.

But trace became quite useless if tests are written in «atomic» style, like:

```javascript
import { test, expect, Page } from '@playwright/test';

let page: Page;

test.beforeAll(async ({ browser }) => {
  page = await browser.newPage();
});

test.describe('Test desctiption', () => {
  test.describe.configure({ mode: 'serial' });

  test.beforeAll(async () => {
    await page.goto('/home');
  });

  test('Atomic test name 1', async () => {
    const pageObject = new PageObject(page);
    const fooBar1 = await pageObject.toDoSmthng1();
    await expect(fooBar1).toBe('smthng');
  });

  test('Atomic test name 2', async () => {
    const pageObject = new PageObject(page);
    const fooBar2 = await pageObject.toDoSmthng2();
    await expect(fooBar2).toBe('smthng');
  });

  test('Atomic test name 3', async () => {
    const pageObject = new PageObject(page);
    const fooBar3 = await pageObject.toDoSmthng3();
    await expect(fooBar3).toBe('smthng');
  });
});
```

Here, each check is executed in a single `test`.

But when a test in the middle fails, its trace will not contain all previous tests.

It will be very handy for debugging to see all the actions that have happened since the start of the test suite — to trace all actions inside the `description`.

It may be possible to record traces for `description`, but I couldn't find instructions for it in the documentation.

So, it will be great to manage the «depth» of trace recording through config: record traces for`test`s or record for a parent `description`s.

**Comment by mxschmitt** [comment]
We strongly advocate against doing this and having your tests isolated so you can benefit from test isolation and running them concurrently. If you want to separate them into parts, we recommend [test steps](https://playwright.dev/docs/api/class-test#test-step) instead which you can also [box](https://playwright.dev/docs/release-notes#hide-implementation-details-box-test-steps) as per the latest release.

**Comment by adequatica** [comment]
Hi, Max. Thanks for the answer and for having a strong Playwright's vision of how things should be made — that traces will be recorded only for `test` functions.

Thanks for test.step suggestion, but on my project, we parallel tests on a file level.
