### ISSUE TITLE
[BUG]trace viewer time-line bar only shows 4 pages because the right scrollbar cannot be scrolled

### ISSUE THREAD

**Issue by jiawen94** [microsoft/playwright#28208]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [All]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**my code here**
6 new pages and each page goto google

```js
import { test, expect } from '@playwright/test';

test('test google search', async ({ context }) => {

  for (let i = 0; i < 6; i++) {
    await test.step('search ' + i + ' times', async () => {
      const page = await context.newPage();
      await page.goto('https://www.google.com/');
      await page.getByLabel('Search', { exact: true }).click();
      await page.getByLabel('Search', { exact: true }).fill('playwright');
      await page.getByLabel('Search', { exact: true }).click();
      await page.close()
    })
  }
})

```

**Actual**
trace viewer time-line bar shows 4 pages, the remaining 2 pages below can't be displayed. 
The right scrollbar cannot be scrolled.

![image](https://github.com/microsoft/playwright/assets/29114225/08a11a74-e37a-4f55-a4c8-44d07880b28a)

**Expected**
1. right scrollbar can be scroll up and down
2. Area 2 in this picture↓ can be adjusted up and down
![image](https://github.com/microsoft/playwright/assets/29114225/7fa529a3-c19b-477a-a0c1-cddecf4b4ecc)

**Comment by mxschmitt** [comment]
I can repro.
