### ISSUE TITLE
[BUG/QUESTION] flaky screenshots

### ISSUE THREAD

**Issue by ellynliu** [microsoft/playwright#28204]
### System info
- Playwright Version: v1.33
- Operating System: Windows - latest Azure devops image
- Browser: Chromium

## Description

We’ve been running into a consistent problem with random blocks of text and images failing to show up in screenshots, leading to inaccuracies in visual testing. Here's an example:

**Expected**
<img src="https://github.com/microsoft/playwright/assets/47698191/99b03dfd-a991-40eb-bb66-9dedb546ba01" width=50% height=50%>

**Actual**
<img src="https://github.com/microsoft/playwright/assets/47698191/9e529bea-3297-4f56-8296-88fac492dc5f" width=50% height=50%>
In the above example, large blocks of text and code have failed to load. 

Here's another example of a screenshot where it appears as if there's a black box obscuring part of the page:
<img src="https://github.com/microsoft/playwright/assets/47698191/c14a1820-1f57-4133-ab4b-04e9670e7eef" width=50% height=50%>

**What we've already tried to fix the problem:**
1. Wait for `page.waitForLoadState('load')` prior to taking a screenshot
2. Animations are turned off by default
3. I tried implementing a scroll functionality as found in this github issue: [Full page screenshot not rendering correctly · Issue #620 · microsoft/playwright (github.com)](https://github.com/microsoft/playwright/issues/620), but this led to the screenshot only capturing the bottom window of the screen, even after I specified a scroll back to the top of the page. Even if scroll were implemented successfully, it would add a considerable amount of time to the tests, as we have **hundreds** of screenshots to get through. 

Here's the code that was used to implement scrolling (this didn't resolve the issue):
```
async function scrollFullPage(page: Page) {
	await page.evaluate(async () => {
		await new Promise(resolve => {
			const totalHeight = document.documentElement.scrollHeight;
			const delta = totalHeight / 4; // scroll down 1/4 of the page at a time
			let scrolledHeight = 0;
			const timer = setInterval(() => {
				window.scrollBy(0, delta);
				scrolledHeight += delta;
				if (scrolledHeight >= totalHeight) {
					window.scrollTo(0, 0); // scroll back to the top
					clearInterval(timer);
					resolve({});
				}
			}, 500); // wait 0.5s between each scroll
		});
	});
}
```
4. I tried adding 2-3 seconds of a timeout before taking a screenshot, but this was still flaky and added too much time to tests. 

Any suggestions on reducing inconsistencies in screenshots? I cannot provide source code but am happy to give more details. Thanks in advance!

**Comment by FlippieCoetser** [comment]
@ellynliu I also had some issues when taking screenshots. For me, adding `await page.waitForNavigation()` before taking the screenshot solved it for me. `page` in this context comes from `this.page = await this.context.newPage()` that is loaded at the start of the test. `waitForNavigation` function name is a bit misleading since it only waits for everything to finish loading. At least that is my understanding.

**Comment by mxschmitt** [comment]
We would recommending trying `await page.evaluate(() => document.fonts.ready);` which might work.

Since there is no repro we unfortunately can't act on it. If you can provide a repro, feel free re-file, thanks for your understanding!
