### ISSUE TITLE
[Feature] Playwright should surface failures due to GraphQL problems

### ISSUE THREAD

**Issue by dep** [microsoft/playwright#28203]
I have a Playwright test suite that runs, however part way through the e2e, there's a GraphQL error from one of the GQL requests:

```
{
    "errors": [
        {
            "message": "Field 'isDeleted' doesn't exist on type 'Comment'",
            "locations": [
                {
                    "line": 33,
                    "column": 9
                }
            ],
            "path": [
                "query GetCommentThreads",
                "commentThreads",
                "nodes",
                "comments",
                "isDeleted"
            ],
            "extensions": {
                "code": "undefinedField",
                "typeName": "Comment",
                "fieldName": "isDeleted"
            }
        }
    ]
}
```

Playwright doesn't fail with a helpful error though. It just sits there for another half hour until the test suite eventually times out.  Since this is happening on an end-to-end environment that's on an internal network that I can't access, we spent several hours trying to figure out _why_ the test job failed.

Is there something I'm missing here, through configuration or otherwise? What would be super awesome is if the Playwright job actually failed and surfaced up the GQL error.  It would've saved everyone a lot of time.

In general, my gripe with Playwright + Buildkite is that the test run itself is a complete "black box" -- it's nigh impossible to see what's going on while it's running and when it fails, how come, etc.  Any tips here? Thanks!

**Comment by mxschmitt** [comment]
Playwright is framework / transport agnostic and does not provide anything specific for GraphQL. Could you help us where it is hanging? Have a shareable test/config would help us a ton in order to triage this issue.

Are you already using our [Trace Viewer](https://playwright.dev/docs/trace-viewer-intro) to debug your tests? Could you provide us your Config, you might have a timeout incorrectly configured which explains why it is hanging.

Thanks!

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
