### ISSUE TITLE
Allow BeforeAll To Be Called Just Once in a Describe

### ISSUE THREAD

**Issue by awhisler** [microsoft/playwright#28201]
I currently do not understand the difference between `beforeEach` and `beforeAll`. I see the documentation says [beforeAll](https://playwright.dev/docs/api/class-test#test-before-all-1) is executed once per worker process before all tests BUT if I have a new worker for each test, it acts exactly as the beforeEach

I would like to be able to have a beforeAll just called ONCE when scoped inside a describe. The benefit of having some code in the beforeAll even though it's only used for one test is that the promise resolves before moving onto the test. If I move it inside the one test that needs it, it sometimes does not resolve before I need to assert on it
![image](https://github.com/microsoft/playwright/assets/2396250/5bef9a40-897b-4ac7-ab5a-f792ab71bd0b)

Currently with the above code, the beforeAll is called before both of those `tests` and that is a problem for me because I dont want more than one

**Comment by MindaugasMateika** [comment]
Disable `fullyParallel` in the configuration and then whole files will run in parallel so tests inside same file will run on the same worker, so if your tests won't fail then beforeAll should run only once. But if some test will fail then new work will spawn and beforeAll will run again, no easy way around this.

**Comment by awhisler** [comment]
Oh awesome. Thank you! It's much slower now haha but it does the job!

So is there a different between beforeEach and beforeAll when you're in full parallel mode?

**Comment by mxschmitt** [comment]
beforeEach will always run for each test. beforeAll can run multiple times, if e.g. a test is failing, you'll get a new worker as per [here](https://playwright.dev/docs/test-parallel#worker-processes).

For fullyParallel beforeEach will also run for each test and beforeAll depends on how many workers your tests will run on. 

So if you run 3 tests with fullyParallel and 3 workers it will run beforeAll 3 times. With 1 worker it would only run it 1 time.

Does this answer your question?

**Comment by mxschmitt** [comment]
Closing as per above. For further questions, feel free to re-file. Thanks!

**Comment by awhisler** [comment]
@mxschmitt It doesn't exactly answer my question (sorry it took me a bit to get back to you)

Im not sure I understand the purpose of beforeAll in playwright. Usually, it scopes to where you call it. So if I called a beforeAll outside of the main describe, it should call ONCE for all tests in the file. If I call it inside a describe, it should run before that set of tests within the describe. For some reason, when it's in fullyParallel mode and 5 workers let's say, and the beforeAll is within a describe (like my screenshot) it is called (in this case) 2 times because I have 2 tests. But I dont think it should as thats the exact use case for beforeEach. BeforeAll should only be called ONCE for the 2 tests even if I have 2 workers. 

Does that make sense?
![image](https://github.com/microsoft/playwright/assets/2396250/0c2d8c91-47a0-4a20-8a70-d001fa239d66)

**Comment by mxschmitt** [comment]
> . For some reason, when it's in fullyParallel mode and 5 workers let's say, and the beforeAll is within a describe (like my screenshot) it is called (in this case) 4 times because I have 4 tests. But I don't think it should as thats the exact use case for beforeEach

This is because you run your 4 tests across 4 workers. Each worker is an isolated JavaScript process so we need to run beforeAll again since these processes can't share any variables and beforeAll will populate some JavaScript variables / call libraries.

If you want to run it only once, you either need to use describe.serial, where we ensure that these tests don't run concurrently. This ensures that beforeAll only runs once. If one test fails, all the other tests get skipped.

Does this make it more clear?

**Comment by awhisler** [comment]
Hi @mxschmitt! Just following up here...

**Comment by ronanshel** [comment]
It would be very useful to be able to have a beforeAll run in its own worker prior to the rest of the tests, and to have a mechanism through which the other workers can read from a global state that is set by the beforeAll.

> This is because you run your 4 tests across 4 workers. Each worker is an isolated JavaScript process so we need to run beforeAll again since these processes can't share any variables and beforeAll will populate some JavaScript variables / call libraries.

**Comment by tbdk** [comment]
Chiming in here as well. 
https://playwright.dev/docs/api/class-test#test-before-all does say under details that: 

```
When multiple beforeAll hooks are added, they will run in the order of their registration.

Note that worker process is restarted on test failures, and beforeAll hook runs again in the new worker. Learn more about [workers and failures](https://playwright.dev/docs/test-retries).

Playwright will continue running all applicable hooks even if some of them have failed.
```

So from that point of view, I understand the behavior of `test.beforeAll`. But I do that it is sort of a misnomer to call it `beforeAll` then, and also inconsistent with how I seem to remember that other testing frameworks does it. 

I would expect a `test.beforeAll` to run _once_ before _all_ tests that are within its 'scope', whether that is communicated by having it inside of a describe group, or some other configuration or overwrite, independent of whether the tests are running in parallel or not. 

I don't believe in the global setup and teardown to provide this functionality, because maybe we want to do it for some tests, but not all. Then you could argue that we have projects and project dependencies to fix that, but that's oddly removed from the tests and into some global configuration file, which seems not right for this particular use case. 

That's my 5 cent at least :slightly_smiling_face:

**Comment by ammoradi** [comment]
Any news about this?

**Comment by siurbele420** [comment]
I agree that the beforeAll hook should be executed only once, especially in a fully parallel environment. After all, the primary purpose of the beforeAll (it's in the name!) hook is to run a setup once per test.describe scope.

**Comment by JimBarrisGSC** [comment]
I would also like an option to have the beforeAll() code executed, **once only**, for a given describe scope.  In my case, it's used to both delete and set some database values, and the process is dynamic based on previous tests.  I can see it being possible that a worker starting even a short time after another (for failure or whatever other reason) will potentially delete rows that were just created and are being relied on for testing by other workers.

**Comment by DerTimonius** [comment]
I also agree, running the `beforeAll` hook once per worker feels extremely counterintuitive to me. as a user I would expect that it only runs once before the actual tests start. 

in my opinion, both hooks `beforeAll` and `beforeEach` should not change their behaviour based on the number of workers that are running the tests in the file.

**Comment by art1es23** [comment]
Also, my 5 cents) I agree with all the examples provided above, about ‘beforeAll’ need to call only one, not for each worker cause, in my opinion, it does not make sense.
For example, I want the 'beforeAll' to create a new entity that will be used in all tests grouped via test.describe in parallel mode. For now, each test calls its beforeAll which creates, in my case, 4 entities, not 1, and it breaks the next tests’ logic.

**Comment by vitalets** [comment]
@awhisler I've posted a [workaround](https://github.com/microsoft/playwright/issues/22520#issuecomment-2391025061) in the related issue, it allows to run beforeAll only once. Maybe it will be helpful, until we get some built-in solution.

**Comment by art1es23** [comment]
@vitalets perhaps u have same solution to 'afterAll'? I mean that we need to know when all parallel tests is finished.

**Comment by vitalets** [comment]
> [@vitalets](https://github.com/vitalets) perhaps u have same solution to 'afterAll'? I mean that we need to know when all parallel tests is finished.

It should work for `afterAll` as well:
```ts
// test.ts
import { isFirstRun } from './isFirstRun';

test.afterAll(async () => {
  if (!await isFirstRun()) return;
  console.log("This will be executed only once during test run");
});
```

**Comment by art1es23** [comment]
> > [@vitalets](https://github.com/vitalets) perhaps u have same solution to 'afterAll'? I mean that we need to know when all parallel tests is finished.
> 
> It should work for `afterAll` as well:
> 
> // test.ts
> import { isFirstRun } from './isFirstRun';
> 
> test.afterAll(async () => {
>   if (!await isFirstRun()) return;
>   console.log("This will be executed only once during test run");
> });
> **UPDATE:** I've realized, that for `afterAll` the logic should be opposite: we need to actually execute code in the last run. Literally, it should be something like this:
> 
> test.afterAll(async () => {
>   if (!await isLastRun()) return;
>   console.log("Cleanup...");
> });
> Still thinking how to achieve that..

I thought if can use for it local db in which we save the data of group tests, for example, I don’t know, Redis (i think it’s a good choice for it) or smth like that.
Because, I think operation with files it's not a good idea. It’s working in any cases, but in special - no.

**Comment by vitalets** [comment]
> For example:
> I have 6 tests on one entity.
> In 'beforeAll' I created entity which want to use in this parallel tests, so I want to share id (or url, etc) with this tests.

My latest workaround uses `process.send()` from worker to host process, so it can potentially handle data sharing in the most reliable way - as host process is single threaded node.js, there should not be any race conditions. Using files is less reliable I totally agree.

Running `afterAll` only once is really tricky, compared to `beforeAll`. We don't know how tests are shared across workers, so it is very difficult to find the last test for suite. I'm thinking about using reporter for that purpose, but I need to check.

**Comment by art1es23** [comment]
> > For example:
> > I have 6 tests on one entity.
> > In 'beforeAll' I created entity which want to use in this parallel tests, so I want to share id (or url, etc) with this tests.
> 
> My latest workaround uses `process.send()` from worker to host process, so it can potentially handle data sharing in the most reliable way - as host process is single threaded node.js, there should not be any race conditions. Using files is less reliable I totally agree.
> 
> Running `afterAll` only once is really tricky, compared to `beforeAll`. We don't know how tests are shared across workers, so it is very difficult to find the last test for suite. I'm thinking about using reporter for that purpose, but I need to check.

If you have any ideas on how to do this for "afterAll", I'd love to hear from you. 
I have one idea how to do this, but I need to test it.
The idea is to somehow calculate the initial number of parallel tests in the group, and after each test is completed, subtract the completed ones until there is one left, which will be the last one. But there is still a problem with counting the number of tests.

**Comment by vitalets** [comment]
Finally, I made a dedicated package that ensures the code in `BeforeAll` hook is executed exactly once. 
It also supports data cleanup: instead of relying on `AfterAll`, it uses the global teardown phase.
More details here: https://github.com/microsoft/playwright/issues/22520#issuecomment-3167474277
