### ISSUE TITLE
[Feature] Availability of browser build scripts

### ISSUE THREAD

**Issue by davidjb** [microsoft/playwright#28209]
> Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Playwright is a very useful project but how the browsers themselves are compiled isn't clear as the build scripts don't appear to be available. From [various hints](https://github.com/search?q=repo%3Amicrosoft%2Fplaywright+microsoft%2Fplaywright-browsers&type=code) in the codebase, it appears the repo is https://github.com/microsoft/playwright-browsers but this isn't publicly visible. 

If this is the repository for the scripts, is there a copy of the repository's contents somewhere openly, or, is it something that could be be made open source so I'm able to review how the compilation takes place?  Otherwise, if this _isn't_ the location of the build scripts, is it somewhere else that's available?

Thanks for your consideration.

**Comment by mxschmitt** [comment]
We use this repository for having access to special set build bots only. We use the same build scripts as the official browser vendors, so we recommend looking at their upstream docs.

https://webkit.org/building-webkit/
https://firefox-source-docs.mozilla.org/setup/linux_build.html
