### ISSUE TITLE
[BUG] Inconsistency in running tests awaiting 'popup' events, namely resulting in destruction of execution context

### ISSUE THREAD

**Issue by cdvillard** [microsoft/playwright#28211]
### Description
I recently inherited work on a global header project based entirely on web components. We're trying to leverage Playwright for e2e testing, and according to the prior maintainer, everything was testing fine. Recently tests have begun to fail irregularly with no changes to source code or the testing scaffold. We reached out [a couple](https://discord.com/channels/807756831384403968/1169831892422492180/1169831892422492180) [of times](https://discord.com/channels/807756831384403968/1087751167162974310) on the Discord channel, but we can't seem to figure out what's caused the sudden irregularity. When running the tests, the results seem extremely inconsistent. Testing through our CI on Github has shown more consistent results after removing a number of snapshot tests. However, re-running these tests multiple times reveals inconsistencies between all tests passing or several failing to due to timeouts or execution context destruction.

### System info
- Playwright Version: v1.35.1, v 1.40.x
- Operating System: All
- Browser: All, Chromium, Firefox, WebKit]
- Other info:

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
import { devices } from '@playwright/test';

const config: PlaywrightTestConfig = {
  /* Testing on local development server */
  webServer: {
    command: 'npm start',
    url: 'http://localhost:5173',
    timeout: 120000,
  },
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 1 : 0,
  /* Opt out of parallel tests on CI. */
  workers: 5,
  /* Reporter to use. */
  reporter: process.env.CI ? 'dot' : [['html', { open: 'never' }]],
  /* Shared settings for all the projects below. */
  use: {
    /* Maximum time each action such as `click()` can take. Defaults to 0 (no limit). */
    actionTimeout: 0,
    /* Base URL to use in actions like `await page.goto('/')`. */
    baseURL: 'http://localhost:5173/public/',
    /* Collect trace when retrying the failed test. */
    trace: 'on-first-retry',
  },
  timeout: 90000,
  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: {
        ...devices['Desktop Chrome'],
      },
    },
    {
      name: 'firefox',
      use: {
        ...devices['Desktop Firefox'],
      },
    }
  ],
  quiet: !!process.env.CI,
};

export default config;
```

**Test file (self-contained)**

```js
// src/menus/help/tests/help-menu.spec.ts
test('help-menu (help tab) - Compute Ops Management - Onboarding 2: Platform', async ({ page }) => {
      await expectPopupUrl({
        page,
        url: 'https://support.hpe.com/hpesc/public/videoDisplay?videoId=vpsg00005088en_us',
        selectorClick: page.getByRole('menuitem', { name: 'Onboarding 2: Platform' }).click(),
        assertFunction: expect,
      });
    });

// src/utils.tsx
export const expectPopupUrl = async ({
  page,
  url,
  selectorClick,
  assertFunction,
}) => {
  const [popup] = await Promise.all([
    page.waitForEvent('popup'),
    selectorClick,
  ]);
  await popup.waitForLoadState('load');
  await assertFunction(popup).toHaveURL(url);
};
```

**Steps**
- Run the test suite several times

**Expected**
- A developer running these tests should expect reliably consistent and predictable passing, failing or flaky tests.
 
**Actual**
- Tests dealing with the `popup` event when run either locally or in our CI environment seem to pass or fail inconsistently, throwing errors blaming the execution context being destroyed, timeouts beyond our custom-configured 90s due to the browser closing, or actual failure of the test. The most common one seems to be the first mentioned of these three.

**Comment by cdvillard** [comment]
Just an update on this, i've also tried using v.1.40 as well and ran into similar issues.

**Comment by tanimaroy2012** [comment]
i am facing this issue with v1.40 as well....works in v.1.39.0

**Comment by mxschmitt** [comment]
This issue unfortunately does not contain a minimal self-contained reproducible, please re-file and follow the bug template. Otherwise we are not able to act on it. Thanks!

**Comment by cdvillard** [comment]
@mxschmitt I understand the requirement, but this is occurring within a suite of tests for a private, internal repo. Moreover, this isn't occurring within any singular test. Is there a way to get support without exposing that code or rebuilding an entire example for public viewing?

**Comment by dbartenstein** [comment]
Hi!

We also seem to run into the problem described. We’re using Playwright 1.54 with Python.

@mxschmitt @tanimaroy2012 @cdvillard have you found any other workarounds? Thanks for sharing! 🙇 

```
======================================================================
ERROR [4.750s]: test_search_popup_url (tests_end2end.tests_changeform.ChangeformReadOnlyTestCase.test_search_popup_url)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/zemtu/zemtu/tests_end2end/tests_changeform.py", line 57, in test_search_popup_url
    choose_object_button.click()
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/sync_api/_generated.py", line 15524, in click
    self._sync(
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/_impl/_sync_base.py", line 115, in _sync
    return task.result()
           ^^^^^^^^^^^^^
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/_impl/_locator.py", line 160, in click
    return await self._frame.click(self._selector, strict=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/_impl/_frame.py", line 549, in click
    await self._channel.send("click", self._timeout, locals_to_params(locals()))
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 69, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/__w/zemtu/zemtu/.venv/lib/python3.12/site-packages/playwright/_impl/_connection.py", line 558, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TargetClosedError: Locator.click: Target page, context or browser has been closed
Call log:
  - waiting for locator("a[data-popup-opener=\"507\"]")
    - locator resolved to <a data-popup-opener="507" class="flex items-center hover:text-primary-500" href="/admin/billing/payer/507/change/?_changelist_filters=q%3DJohn%26_to_field%3Did%26_popup%3D1">…</a>
  - attempting click action
    - waiting for element to be visible, enabled and stable
    - element is visible, enabled and stable
    - scrolling into view if needed
    - done scrolling
    - performing click action
```

**Comment by cdvillard** [comment]
@dbartenstein we effectively had to stop using Playwright to cover those cases. For some, we moved to just ensuring they have the correct target URL, and for others, we covered them using Vitest.
