### ISSUE TITLE
[Question] Wait for response.ok()

### ISSUE THREAD

**Issue by jakobrosenberg** [microsoft/playwright#2821]
I'm not sure if this already exist. I tried `waitForResponse`, but didn't get the desired result.

For my tests I need to run a dev-server, which takes up to 15 seconds to start. It would be great if there was a native way to poll a server for `response.ok()` to be truthy within a set interval.

As a workaround, I'm using the following code
```javascript
const response = await waitForServer(page, url)

...

async function waitForServer(page, url, timeout = 20000) {
  const startTime = Date.now()
  while (Date.now() - startTime < timeout) {
    try {
      const response = await page.goto(url)
      if (response.ok())
        return response
      await new Promise(resolve => setTimeout(resolve, 100))
    } catch (err) { }
  }
  throw new Error('Server never started')
}
```

**Comment by mxschmitt** [comment]
From the first thoughts, it seems that this might be the right feature for you: https://github.com/playwright-community/jest-process-manager

**Comment by jakobrosenberg** [comment]
Thanks @mxschmitt.  In my case I'm working on a new framework. Testing the CLI and dev-server is part of the tests, rather than being the environment for the tests. I hope that makes sense.

Is it possible to check if an address returns status 2xx within a given timeframe with Playwright?

**Comment by mxschmitt** [comment]
> Thanks @mxschmitt.  In my case I'm working on a new framework. Testing the CLI and dev-server is part of the tests, rather than being the environment for the tests. I hope that makes sense.
> 
> Is it possible to check if an address returns status 2xx within a given timeframe with Playwright?

Yes, it supports http/https based applications and will start the Jest tests once a 2xx status test will be returned. Useful for dev servers like create-react-app has.

**Comment by jakobrosenberg** [comment]
How would I do this with Playwright?

**Comment by mxschmitt** [comment]
> How would I do this with Playwright?

See this repo for jest-playwright examples including React: https://github.com/playwright-community/playwright-jest-examples

**Comment by jakobrosenberg** [comment]
I think there might be a misunderstanding.

I'm looking for a Playwright native function like `page.waitForResponse`, which waits for x seconds for a 2xx response.

**Comment by mxschmitt** [comment]
Ah gotcha. If you want to use this feature directly, you can use the [wait-on](https://www.npmjs.com/package/wait-on) package.
If you want that a certain XHR/Fetch request is completed, you can use the [`Page.waitForResponse`](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=pagewaitforresponseurlorpredicate-options) function.

**Comment by jakobrosenberg** [comment]
Thanks, didn't know about the wait-on package. The wrapper is already working, but had hoped for a cleaner solution. I'll have a look at wait-on and see if it's worth replacing the wrapper.

**Comment by aslushnikov** [comment]
> For my tests I need to run a dev-server, which takes up to 15 seconds to start. It would be great if there was a native way to poll a server for response.ok() to be truthy within a set interval.

@jakobrosenberg In ideal world, server would notify clients when it's up and running - but sometimes there's no way to get perfect behavior..

The workaround that you use is not that bad for what it does. Alternatively, I'd consider firing HTTP requests from node.js itself since it's way more lightweight than browser page navigation.
