### ISSUE TITLE
[BUG] ibm_db package causes PrintDeps.exe error when running tests from terminal

### ISSUE THREAD

**Issue by yonides** [microsoft/playwright#28219]
### System info
- Playwright Version: v.1.39.0, TypeScript
- Operating System: Windows 11, Version 10.0.22631 Build 22631
- Browser: All (for example: Chromium version 119.0.6045.9 (Developer Build) (64-bit))
- Node version: v.18.17.1
- **ibm_db** v.3.2.2 (https://www.npmjs.com/package/ibm_db)

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from "@playwright/test";
import dotenv from "dotenv";
import path from "path";
let envFile = process.env.ENV_FILE ? process.env.ENV_FILE : "dev";
dotenv.config({
   path: path.resolve(__dirname, "", `.env/${envFile}.env`),
});

export default defineConfig({
   testDir: "./tests",
   fullyParallel: true,
   forbidOnly: !!process.env.CI,
   retries: process.env.CI ? 2 : 0,
   workers: process.env.CI ? 1 : undefined,
   reporter: "html",
   use: {
      baseURL: `https://google.com`, //any endpoint
      testIdAttribute: "data-rt",
      locale: "sv-SE",
      timezoneId: "Europe/Stockholm",
      trace: "on-first-retry",
   },

   /* Configure projects for major browsers */
   projects: [
      {
         name: "chromium",
         use: {
            ...devices["Desktop Chrome"],
            launchOptions: {
               args: ["--lang=sv_SE"]
            },
         },
      },

      {
         name: "firefox",
         use: {
            ...devices["Desktop Firefox"],
            launchOptions: {
               args: ["--lang=sv_SE"]
            },
         },
      },

      {
        name: 'webkit',
        use: { ...devices['Desktop Safari'] },
      },

      /* Test against mobile viewports. */
      {
         name: "Mobile Chrome",
         use: {
            ...devices["Pixel 5"],
            launchOptions: {
               args: ["--lang=sv_SE"],
            },
         },
      },
   ],
});
```
mf.ts file
```js
const ibmdb = require("ibm_db");
const cn = `DATABASE=${process.env.MF_DATABASE};HOSTNAME=${process.env.MF_HOSTNAME};UID=${process.env.MFUSERNAME};PWD=${process.env.MFPASS};PORT=${process.env.MF_PORT};PROTOCOL=TCPIP;`;
export async function MFExecute(query: string) {
   try {
      var conn = await ibmdb.open(cn);
      var result = await conn.query(query);
      //console.log(result);
      return result;
   } catch (e) {
      console.error("Something went wrong when querying MF data", e);
      throw e;
   } finally {
      await conn.close();
   }
}
```

**Test file (self-contained)**

```js
import { test } from "@playwright/test";
import * as mf from "mf";

test("MF test", async ({ page}) => {
   let test = await mf.MFQuery(`SELECT * FROM ${process.env.MF_TABLE}.TDLSEMA WHERE ID_PERSNR = 'XXXXXX'`);
   console.log(test);
});
```

**Steps**
Run test case from Test explorer with "Show trace viewer" or from terminal, e.g.:
```js
yarn playwright test -g "MF test" --project="chromium" --headed
```
**Expected**

Browser to be launched without errors.

**Actual**

1. Following errors pop up every time I run the test, see screenshots below. After closing the popups, the test continues to run as expected.

2. Running tests from Test explorer with "Show browser" alternative works fine (without errors).

**From what I can see, it seems to be "ibm_db" in combination with PW "page" that causes the issue. Similar test case with MSSQL package works fine.**

![bild](https://github.com/microsoft/playwright/assets/151147916/cf7a600b-45c3-4b7e-840e-a0f5d644160f)

![bild](https://github.com/microsoft/playwright/assets/151147916/b3526dd9-465e-4a8d-b0a0-260dff81a08e)

![bild](https://github.com/microsoft/playwright/assets/151147916/a6aa8d6c-34e0-4379-b816-b3899a1c371e)

![bild](https://github.com/microsoft/playwright/assets/151147916/512b6d81-beba-4e78-aa54-2368cf329214)

![bild](https://github.com/microsoft/playwright/assets/151147916/c1dbfab6-3618-4704-9fef-423db7138c97)

![bild](https://github.com/microsoft/playwright/assets/151147916/c3164cd3-2780-4477-a9f4-c8304d342911)

![bild](https://github.com/microsoft/playwright/assets/151147916/2d177fb6-8a19-4ffc-b4d0-72f1df29df33)

**Comment by mxschmitt** [comment]
We unfortunately have no access to an IBM DB2 and IBM Informix database. Please re-file with reproduction steps which help us setting it inside Windows with Docker. Thanks for your understanding.

**Comment by yonides** [comment]
FYI. If others run into the same issue. I solved it by moving `const ibmdb = require("ibm_db");` into the "MFExecute" function (mf.ts file).

**Comment by mxschmitt** [comment]
Looks like a bug in their library, that they [override the global PATH](https://github.com/ibmdb/node-ibm_db/blob/0e14011fb3cc60157348bf49870352e5eac6dc1e/lib/odbc.js#L30) which messes up our logic, because we try to launch a sub-process which can't be found.

Workaround would be to require inside the test as per https://github.com/microsoft/playwright/issues/28219#issuecomment-1817785164.
