### ISSUE TITLE
[REGRESSION]: component testing -- `children` defaults to empty array instead of undefined if not passed

### ISSUE THREAD

**Issue by ritz078** [microsoft/playwright#28212]
**Context:**
- GOOD Playwright Version: 1.39.x
- BAD Playwright Version: 1.40.0
- Operating System: Mac
- Extra: [any specific details about your environment]

**Code Snippet**

Help us help you! Put down a short code snippet that illustrates your bug and
that we can run and debug locally. For example:

```javascript
// test.tsx

import { Custom } from "./testComponents"

  test("renders", async ({ mount, page }) => {
    const component = await mount(<Custom />);
    await expect(component).toBeVisible();
  });
```

```js
// testComponents.tsx

export const Custom = (args) => {
  console.log(args); // {children: Array(0)}
  return <Custom {...args} />;
};
```

**Describe the bug**

In the above example, as you can see `args` included a children that's an empty array which was not passed from the test file. children should be `undefined` in this case.

**Comment by mxschmitt** [comment]
cc @sand4rt this looks like a regression introduced in https://github.com/microsoft/playwright/pull/27692, do you mind taking a look?
