### ISSUE TITLE
[Question] Can compiled configuration be accessed inside of test.describe?

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/playwright#28223]
I'd like to be able to access the compiled _use_ configuration, inside test.describe.  The only way I can make it work the way I want, is to use an environment variable, but that just feels wrong.  I use environment variables for setting up the config, but after that, everything should be running off of the compiled config.  (I'm saying _compiled_, meaning the inclusion of the overridden values, that may be in the project being used.)

My use case is running parameterized tests, with their driving information located in a JSON file.

```typescript
test.describe('Query Errors', () => {

    let tests: QueryInfo[] = [];

    //*** I don't want to have to do this.  ***/
   // Is there a way to get the compiled use config section inside test.descibe
    let siteType = process.env.siteType;

    if (!siteType) {
        throw new Error('siteType was not specified.');
    }

    let filePath = path.join(__dirname, `../../data/${siteType}/queryErrors.json`);
    let fileJson = fs.readFileSync(filePath, "utf-8");

    tests = JSON.parse(fileJson);

    tests.forEach((queryInfo) => {
        if (queryInfo.skip) {
            test.skip(queryInfo.name, async () => { });
        }
        else {
            test(queryInfo.name, async ({ queryErrorValidations, dataInfo, siteType }) => {
                await queryErrorValidations.runQuery(queryInfo, dataInfo, siteType);
            });
        }
    });
});
```

**Comment by mxschmitt** [comment]
This is possible and we call it [Parameterised Projects](https://playwright.dev/docs/test-parameterize#parameterized-projects). Let us know if it works for you!

**Comment by dsmeltz** [comment]
I'm already doing that. :)  You can see where I'm passing _dataInfo_  and _siteType_ into the _test_ call. Those are values coming from the running project or set in the global _use_ section.
The problem is you can't get to that information inside of test.describe, as test.describe doesn't take any arguments.

**Comment by mxschmitt** [comment]
Sorry I didn't see that. So having access to the fixtures is not possible inside the describe block, this is due to the way how fixtures are getting created and teared down. We recommend this alternative instead:

```ts
for (const siteType of ['sharepoint', 'teams']) {
  test.describe(siteType + 'Query Errors', () => {
    const filePath = path.join(__dirname, `../../data/${siteType}/queryErrors.json`);
    const fileJson = fs.readFileSync(filePath, 'utf-8');

    const tests = JSON.parse(fileJson) as QueryInfo[];

    for (const queryInfo of tests) {
      if (queryInfo.skip) {
        test.skip(queryInfo.name === siteType);
      } else {
        test(queryInfo.name, async ({ queryErrorValidations, dataInfo, siteType }) => {
          await queryErrorValidations.runQuery(queryInfo, dataInfo, siteType);
        });
      }
    };
  });
}
```

So you define all your tests and then skip the ones you don't want. You could also skip the ones which don't match with the current fixture via:

```ts
for (const siteTypeValue of ['sharepoint', 'teams']) {
  test.describe(siteTypeValue + 'Query Errors', () => {
    const filePath = path.join(__dirname, `../../data/${siteTypeValue}/queryErrors.json`);
    const fileJson = fs.readFileSync(filePath, 'utf-8');

    const tests = JSON.parse(fileJson) as QueryInfo[];

    for (const queryInfo of tests) {
      if (queryInfo.skip) {
        test.skip(({siteType}) => siteType === siteTypeValue);
      } else {
        test(queryInfo.name, async ({ queryErrorValidations, dataInfo, siteType }) => {
          await queryErrorValidations.runQuery(queryInfo, dataInfo, siteType);
        });
      }
    };
  });
}
```

Since this issue is about generating test-cases, where we don't provide official support for (tooling will most likely misbehave, like UI Mode etc) I'm going to close it for now.

**Comment by dsmeltz** [comment]
I completely agree with your statement regarding generated test cases misbehaving for UI Mode etc.  I'm using this for API testing and due to this short coming, I have to replicate code, instead of being able to just have _generic_ test runners and defining the available tests as JSON by environment.
