### ISSUE TITLE
[Feature] allow `repeatEach` to be set on a specific `test`

### ISSUE THREAD

**Issue by samijaber** [microsoft/playwright#28220]
Much like how we can set `test.describe.configure({ retries: 10 })`, it would be great if we can have `repeatEach` as part of that `configure` options argument. 

I have certain tests that involve randomness, which is why I'd like to always repeat them X times in my CI. However, I currently cannot do that without repeating the entire test suite, or manually calling that test function X times.

**Comment by mxschmitt** [comment]
RepeatEach is usually a feature designed to spot flakiness inside your test. So you can run a specific test via:

    npx playwright test --repeat-each 100 foo.spec.ts:32

100 times. If you want to do it to involve randomness, then we recommend [parameterised tests](https://playwright.dev/docs/test-parameterize). There you just do e.g. a for loop 5 times and define your test-case 5 times with different kinds of input. In this case you only use the number to have a unique test title:

```ts
for (let i = 0; i < 10; i++) {
  test('test' + i, async ({  }) => {

  });
}
```

Would that work for you?

**Comment by samijaber** [comment]
That's fair, for loops work just fine (and it's what I do for when I need to repeat a test in a permanent fashion). 

However, when I do use `repeatEach` to debug a flaky test, I am usually already inside that particular test file. I currently:
- change it to `test.only`
- go to `playwright.config.ts` and set `repeatEach: 100`

Feels more ergonomic to be able to `test.describeconfigure({repeatEach: 100 })` in the test's file itself. Definitely not a huge deal or a blocker in any way. :)

**Comment by mxschmitt** [comment]
sounds good! closing by that then.
