### ISSUE TITLE
[Feature]Add config option to specify which test/step to expand in UI mode

### ISSUE THREAD

**Issue by Bonjour123** [microsoft/playwright#28233]
Let us know what functionality you'd like to see in Playwright and what your use case is.
Do you think others might benefit from this as well?

Following playwright recommendations, I extensively use "test steps". Before I would use describe blocks but that would be more a workaround than a clean solution.

The problem I have with test steps is doesn't seem possible to control which steps to expand by default (i.e. when a test has finished) in the (UI mode) GUI.

One effective solution could be to provide a config option 'expand':
( (type: "describe"|"test"|"step", title, depth)=>boolean) || boolean ).
This "expand" function provided by the user is a pattern commonly used in json-viewer libs for instance.

Describing the whole testing tree is really a must for these following needs:

- Get an overview of the tests, their complexity and an idea of the current coverage
- Easily spot missing pre-requises or inner steps
- Custom filter steps when focusing on a specific part

Such feature in a reporter would be useful but anyone can make a custom reporter to implement this feature. Which is not the case with the UI mode, plus it brings a  lot more features than a reporter (sources, before/after, snapshots...)
Expanding only on fail is not sufficient, as UI mode is designed to be a debugging tool, not a reporter. In a debugging tool, I think the user should be able to debug and have an easy overview of what he's dealing with. Titles are a great way to have a quick overview. If a test consists of 25 nested steps and the user has to click 25 times to get an overview of the test he is going to run, it decreases a lot the tool's usability.

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/28159
