### ISSUE TITLE
[Feature] Can you provide a feature through that we can pass multiple browser names in C# UI tests for CI/CD?

### ISSUE THREAD

**Issue by heenavasdani** [microsoft/playwright#28237]

**Comment by heenavasdani** [comment]
@mxschmitt , @dgozman Can you please look into it on priority?

**Comment by mxschmitt** [comment]
This is not possible as of today (since we don't have a dedicated test-runner in .NET).

We recommend executing `dotnet test` multiple times as per [here](https://playwright.dev/dotnet/docs/running-tests) or doing it in user-land by creating own base-classes.
