### ISSUE TITLE
[Feature] Export JSONReporter

### ISSUE THREAD

**Issue by joemull** [microsoft/playwright#28232]
## Use case

I'd like to import JSONReporter and overwrite or hook into a few methods to customise the output format to meet a JSON spec I don't control. Would prefer not to have to rewrite or copy the whole JSONReporter class.

## Example
```js
import { JSONReporter } from '@playwright/test/reporter'

export default class MyReporter extends JSONReporter {
  ...
}
```

**Comment by joemull** [comment]
This was briefly mentioned in https://github.com/microsoft/playwright/issues/8475#issuecomment-906642758 -- hoping it would be useful for others as well.

**Comment by MindaugasMateika** [comment]
+1 for export

**Comment by mxschmitt** [comment]
I think this is possible as of today via:

    import type { JSONReport } from 'playwright/types/testReporter';

as per https://github.com/microsoft/playwright/pull/13241.

**Comment by joemull** [comment]
Thanks for pointing that out. I was hoping to use JavaScript for this actually, not TypeScript, since I'm just working on a small project with a team that doesn't know TS. But if JS export is not a priority for you, I understand.

**Comment by joemull** [comment]
> It should work with JSDoc as well. Like:
> 
> ```
> /** @type {import('playwright/types/testReporter').JSONReport} */
> var data;
> ```

Cool, thanks. I don't use JSDoc either, unfortunately. Just looking for a plain old ES6 import. 

For the time being, I am just calling a separate JS script after running my Playwright tests to edit the JSON file, and it is working OK for my use case so far.
