### ISSUE TITLE
[BUG] Incorrect history position when using `history.push` and `goBack.

### ISSUE THREAD

**Issue by AkifumiSato** [microsoft/playwright#28247]
### System info
- Playwright Version: [v1.39.0]
- Operating System: [Ubuntu on github, macOS 12.7.1, etc.]
- Browser: [WebKit]
- Other info: use `history.push` and `page.goBack()`

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

https://github.com/recruit-tech/location-state/blob/main/apps/example-next/playwright/url-list.spec.ts#L25
https://github.com/recruit-tech/location-state/actions/runs/6923975971/job/18832584961

**Config file**

https://github.com/recruit-tech/location-state/blob/main/apps/example-next/playwright.config.ts

**Test file (self-contained)**

https://github.com/recruit-tech/location-state/blob/main/apps/example-next/playwright/url-list.spec.ts#L10-L30

**Steps**

https://github.com/recruit-tech/location-state/blob/main/.github/workflows/playwright.yml#L12-L30

**Expected**

It should transition to the `history.push()` URL with `page.goBack()`.
It worked until 2 week ago.
https://github.com/recruit-tech/location-state/actions/runs/6812383020

**Actual**

The URL will be the one before `history.push()`.

**Comment by yury-s** [comment]
Can you please provide a reduced test case that shows the problem? The linked test depends on a number of frameworks that may have changed behavior or something. I was not able to reproduce the error with the following test:
```
it('should restore state', async ({ page, server }) => {
  await page.goto('https://example.com');
  await page.evaluate(() => history.pushState({}, '', '/checkbox1.html'));
  await page.evaluate(() => history.pushState({}, '', '/checkbox2.html'));
  await page.goBack();
  await expect(page).toHaveURL('https://example.com/checkbox1.html');
});

```

**Comment by yury-s** [comment]
Which browser is this? Maybe related to https://github.com/microsoft/playwright/issues/28264

**Comment by AkifumiSato** [comment]
I am having this problem with safari.
I have investigated to reproduce the problem and found that the following conditions seem to be affecting it.
- Link component of Next.js
- Recent webkit safari

However, even if I implement these conditions, it does not necessarily reproduce the problem.
I will investigate further.

**Comment by AkifumiSato** [comment]
I found out that this is most likely caused by Next.js, so I'm going to close it.
Thanks.
