### ISSUE TITLE
[Feature] Expose frame guids publically

### ISSUE THREAD

**Issue by martinalderson** [microsoft/playwright#28245]
It's really useful for performance testing to be able to store an id of a frame for further analysis. Playwright dotnet does do this with the underlying guid property but it is not exposed and you have to use reflection to get it. 

It would be great if this was public. For example, storing the ids of the frames is really useful for network request analysis (saving a log of requests with the frameid) to then cross reference with various elements on the page.

**Comment by yury-s** [comment]
Frame guid is an internal detail. You can keep a map {Frame -> id} in your code and assign ids that you like that can be used for logging. Will that work?

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if that doesn't work for you!
