### ISSUE TITLE
[Question] How to change the browser window size when conect over CDP?

### ISSUE THREAD

**Issue by jiawei-wang-SH** [microsoft/playwright#28240]
Hi,

We can use this code to connect over the Chrome DevTools Protocol, and my question is how to change the browser windows size in this case? E.g., if the existing browser instance using CDP is not maximized and we want to get it maximized, how to reach that? Thanks.
```
Browser browser = playwright.chromium().connectOverCDP("http://localhost:9222");
BrowserContext defaultContext = browser.contexts().get(0);
Page page = defaultContext.pages().get(0);
```

**Comment by yury-s** [comment]
You can use [setViewportSize](https://playwright.dev/docs/api/class-page#page-set-viewport-size), there is no method for maximizing the window. Folding into https://github.com/microsoft/playwright/issues/4046
