### ISSUE TITLE
[BUG] Blob reports being merged were recorded with different test directories, and merging cannot proceed (Jenkins)

### ISSUE THREAD

**Issue by swetrify** [microsoft/playwright#28242]
### System info
- Playwright Version: v1.40
- Operating System: Windows 11, Linux Fedora 32
- Browser: ---
- Other info:

**Test file (self-contained)**
[blob-report.zip](https://github.com/microsoft/playwright/files/13412017/blob-report.zip)
The file was created by running a test on Jenkins with [sharding](https://playwright.dev/docs/test-sharding). When sharding is ON, Jenkins creates multiple builds on all available nodes. When one node is running more builds of the same name, Jenkins creates a workspace with '@' and a number at the end of the workspace name. For example: 
```
/data/jenkins/workspace/ation-playwright-multibranch_dev@2 on [jenkins01.cz](https://jenkins01.cz/computer/jenkins01.cz)
/data/jenkins/workspace/ation-playwright-multibranch_dev on [jenkins02.cz](https://jenkins02.cz/computer/jenkins02.cz)
/data/jenkins/workspace/ation-playwright-multibranch_dev on [jenkins03.cz](https://jenkins03.cz/computer/jenkins03.cz) 
/data/jenkins/workspace/ation-playwright-multibranch_dev on [jenkins01.cz](https://jenkins01.cz/computer/jenkins01.cz)
```

In blob-report.zip therefore:
report-1.jsonl has rootDir "/data/jenkins/workspace/ation-playwright-multibranch_dev/tests" 
report-2.jsonl has rootDir "/data/jenkins/workspace/ation-playwright-multibranch_dev/tests"
report-3.jsonl has rootDir "/data/jenkins/workspace/ation-playwright-multibranch_dev@2/tests"

This rootDir difference creates a problem when running merge-reports.

**Steps**

- extract blob-report.zip to a new folder
- run ```npm i -D @playwright/test``` in the created folder 
- run ```npx playwright merge-reports blob-report --reporter html```

**Expected**

```
merging reports from C:\Users\sobot\Documents\issue\blob-report
extracting: blob-report\report-1.zip
extracting: blob-report\report-2.zip
extracting: blob-report\report-3.zip
merging events
processing test events
building final report
finished building report

To open last HTML report run:

npx playwright show-report
```

**Actual**

```
merging reports from C:\Users\sobot\Documents\issue\blob-report
extracting: blob-report\report-1.zip
extracting: blob-report\report-2.zip
extracting: blob-report\report-3.zip
merging events
Error: Blob reports being merged were recorded with different test directories, and
merging cannot proceed. This may happen if you are merging reports from
machines with different environments, like different operating systems or
if the tests ran with different playwright configs.

You can force merge by specifying a merge config file with "-c" option. If
you'd like all test paths to be correct, make sure 'testDir' in the merge config
file points to the actual tests location.

Found directories:
/data/jenkins/workspace/ation-playwright-multibranch_dev/tests
/data/jenkins/workspace/ation-playwright-multibranch_dev@2/tests
    at mergeConfigureEvents (C:\Users\sobot\Documents\issue\node_modules\playwright\lib\reporters\merge.js:204:13)
    at mergeEvents (C:\Users\sobot\Documents\issue\node_modules\playwright\lib\reporters\merge.js:175:16)
    at async createMergedReport (C:\Users\sobot\Documents\issue\node_modules\playwright\lib\reporters\merge.js:45:21)
    at async mergeReports (C:\Users\sobot\Documents\issue\node_modules\playwright\lib\cli.js:179:3)
    at async t.<anonymous> (C:\Users\sobot\Documents\issue\node_modules\playwright\lib\cli.js:93:7)
```

In 1.39 it works as expected. It might be consequence of https://github.com/microsoft/playwright/issues/27877.

Creating merge.config.js in Playwright 1.40 looks like a fix / workaround.
```
export default {
    testDir: 'tests',
    reporter: [['html', { open: 'never' }]],
  };
```

**Comment by yury-s** [comment]
> In 1.39 it works as expected. It might be consequence of https://github.com/microsoft/playwright/issues/27877.

You spotted it right, it was a change in the merge behavior in 1.40. If the root dirs in blob reports differ from one another we require explcit config that resolves the ambiguity rather than resolving all paths relative to a `rootDir` of our choice.

> Creating merge.config.js in Playwright 1.40 looks like a fix / workaround.

This is the recommended way to merge reports that have different root directories. Does it work for your?

**Comment by swetrify** [comment]
Alright, thank you. Yes, with merge.config.js it works as expected.

**Comment by CkumarGitHub** [comment]
@swetrify Could you please share your Jenkins pipeline script for sharing?

**Comment by susnux** [comment]
BTW this will also happen if you use self-hosted github runners.
Because self-hosted images contain a different work path than the github ones.
So for everyone encountering this issue because on shard ran on github and one shard on self hosted:
Just create the merge config like mentioned above and pass it to the merge-reports command.
