### ISSUE TITLE
[Feature] Playwright CLI - run only failed tests

### ISSUE THREAD

**Issue by olivier65** [microsoft/playwright#28254]
In a CI context you need is to run all the tests the first time and subsequently, if the job is manually restarted, ideally only those that failed last time. Is there already an easy way to do that?

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/10500, please upvote that issue instead.

**Comment by unlikelyzero** [comment]
@olivier65 this has been implemented https://github.com/microsoft/playwright/issues/30506
