### ISSUE TITLE
[QUESTION] monitor multiple continuation responses with the same URL. I

### ISSUE THREAD

**Issue by tattyola** [microsoft/playwright#28255]
Hi there!
Is there are a way to monitor multiple continuation responses with the same URL. In particular, when my page is open there are multiple api responses (with the same URL) will be received and I need to be able to grab each response json and push it into array of responses.

![Screenshot 2023-11-20 164004](https://github.com/microsoft/playwright/assets/82601614/bfa3562c-34e3-42ea-9376-b78b39e5b710)

All the responses have the same url and using continuation_token.
This is my current code which I suppose has to monitor all the responses while the page is open. However with current code I'm able to receive only the last response.

Please any assistance will be greatly appreciated.

```
import { expect } from '@playwright/test';
import { API_BUILDER } from '../api/apiUtil';
import test from '../support/baseTest';
import { ROLES } from '../utils/constants';
import { urlHelper } from '../utils/helpersUtil';

test.describe('Dashboard Page Asset Locations Tab', () => {
  test.beforeEach(async ({ loginPage }) => {
    // logging in
    await loginPage.navigateTo('/');
    expect(
      await loginPage.isSuccessLogin(ROLES.ORGANIZATION_MANAGER)
    ).toBeTruthy();
    expect(
      await loginPage.isValidateHomePage(ROLES.ORGANIZATION_MANAGER)
    ).toBeTruthy();
  });
  test('@reg - Validate asset locations after filters applied', async ({
    dashboardPage,
  }) => {
    const currentUrl = dashboardPage.getCurrentUrl();
    const orgId = urlHelper.getOrgIdFromUrl(currentUrl);
    const apiRequest = API_BUILDER.organizationMapListApi(orgId);

    dashboardPage.page.on('response', async (response) => {
      const url = response.url();
      if (url.includes(apiRequest)) {
        const responseBody = await response.json();
        console.log(`Received response from ${url}`);
        console.log('Response Body:', responseBody);
      }
    });

    if (await dashboardPage.assetLocationsTab.isVisible()) {
      // navigating to asset locations tab
      await dashboardPage.assetLocationsTab.click();
      await expect(dashboardPage.assetLocationsHeader).toBeVisible();
      await dashboardPage.assetTypeBtn.waitFor();
      await dashboardPage.page.waitForTimeout(10000);

    }
  });
});

```

**Comment by yury-s** [comment]
> Is there are a way to monitor multiple continuation responses with the same URL. 

`page.on('response'` should work just fine. It's hard to tell without access to the actual site/test what's going on there.

We use github issues for bug reports, you can ask for general help on our [discord server](https://playwright.dev/community/welcome#community-discord). If you believe it is a bug in Playwright, please follow the bug template and provide an example that we could run locally to see the problem.

**Comment by tattyola** [comment]
Thank you for getting back to me yury-s.
I will defiantly check discord server you have mentioned above.
I'm afraid I can't share actual link for you guys to run locally (security reasons).
In the main while, Is there a way You might provide a working code snippet for mentioned scenario to use as an example. That would be very helpful.

Here is my code
```
// array where I will keep all the responses
    const allResponses: any = [];
    dashboardPage.page.on('response', async (response) => {
      const url = response.url();
      if (url.includes(apiRequest)) {
        const responseBody = await response.json();
        console.log(`Received response from ${url}`);
        // console.log('Response Body:', responseBody);
        allResponses.push(responseBody);
      }
      console.log(`all the responses ${allResponses}`);
      console.log(`length of my array ${allResponses.length}`);
    });
```
Here I'm receiving Array with only 1 element (response). Is there a way you might navigate me on how do I get an array with all the responses.

Thank you for all your help.

![Screenshot 2023-11-21 102835](https://github.com/microsoft/playwright/assets/82601614/865f3950-dc74-46d1-831d-6b2282477acb)

**Comment by yury-s** [comment]
You code looks fine. Looks like you receive only one response that contains `apiRequest` substring. Try printing all urls and see if that't the case.

**Comment by tattyola** [comment]
Thank you so much. It's working and I'm able to get responses right inside of this scope.
The last little question I have, please.
I'm struggling to console.log allResponses outside of the .page.on('response',...) scope.

Thank you so much yury-s.
```
const allResponses: any = [];
    dashboardPage.page.on('response', async (response) => {
      const url = response.url();
      if (url.includes(apiRequest)) {
        const responseBody = await response.json();
        allResponses.push(responseBody);
      }
    });
console.log(allResponses) // here it is empty
```

**Comment by tattyola** [comment]
In case someone is facing the same issue I will my solution here.
I was able to console.log allResponses and work with the array outside of the .page.on('response',...) scope.
The solution is that test runner has to perform the action first before handling allResponses variable.

```
const allResponses: any = [];
    dashboardPage.page.on('response', async (response) => {
      const url = response.url();
      if (url.includes(apiRequest)) {
        const responseBody = await response.json();
        allResponses.push(responseBody);
      }
    });
await dashboardPage.submitBtn.click();
console.log(allResponses)
```

**Comment by dsmabulage** [comment]
```
 var responseWatcher = _page.WaitForResponseAsync(response =>
     response.Url.Contains("api/users?name=") &&
     response.Request.Method == "GET");

 await _page.GetByLabel("NMI").PressSequentiallyAsync(name, new() { Delay = 500 });

 var modal = _page.Locator("#CDNotificationPopulate");
 await modal.WaitForAsync(new LocatorWaitForOptions
 {
     State = WaitForSelectorState.Visible,
     Timeout = 10000
 });

 var count = responseWatcher.GetAwaiter().GetResult();
 var lastResponse = await responseWatcher;

 var res = await lastResponse.TextAsync();
```

This doesn't work in .net. Can you help me with this? returns only the first API response, not the last
