### ISSUE TITLE
[BUG] List report lost colors after PW image bump 1.39 > 1.40

### ISSUE THREAD

**Issue by dimkin-eu** [microsoft/playwright#28260]
### System info
- good Playwright Version: [v1.39.0] + focal ( + node 18 ? )
- bad Playwright Version: [v1.40.0] + yammy ( + node 20 ? )
- Other info: Gitlab CI

**Config file**

```js
// playwright.config.ts
    reporter: [["list"], ["html", { open: "never" }]],

```

**Steps**
- [Run the test]
- see colored statuses of tests

**Expected**

green / reds
```
FROM mcr.microsoft.com/playwright:v1.39.0-focal
```

![Screenshot 2023-11-21 at 10 32 53](https://github.com/microsoft/playwright/assets/7899764/c938f44f-d74e-4fcb-b575-1ee16d9f05da)

**Actual**

all white
```
FROM mcr.microsoft.com/playwright:v1.40.0-jammy
```

![Screenshot 2023-11-21 at 10 33 25](https://github.com/microsoft/playwright/assets/7899764/c8736956-7175-4784-a87f-37013ff1f867)

**Comment by pavelfeldman** [comment]
There has been a change in Playwright that now correctly detects if your output supports TTY. If it does not, Playwright won't render color. You can always enforce the color output for non-TTY terminals via setting the `FORCE_COLOR: 1` environment variable.

**Comment by dimkin-eu** [comment]
@pavelfeldman `FORCE_COLOR=1` helped indeed. so looks like `Playwright that now correctly detects` does not work correctly, because coloгrs are gone after pw update :(

**Comment by pavelfeldman** [comment]
@dimkin-eu how do you know your terminal supports TTY?

**Comment by dimkin-eu** [comment]
colors were in job logs before, so are you hinting that pw was forcing colors by mistake?

**Comment by pavelfeldman** [comment]
> so are you hinting that pw was forcing colors by mistake?

Exactly, we were forcing colors unconditionally, but the users came back to us and requested that `npx playwright test > log.txt` has no ANSI sequences. So we addressed it.

**Comment by dimkin-eu** [comment]
ok, let's close it then  ( as `FORCE_COLOR=1` could make everyone happy :) )
