### ISSUE TITLE
Got compiler error about Symbol.asyncDispose after updating playwright/test to 1.40

### ISSUE THREAD

**Issue by firstblood** [microsoft/playwright#28262]
- Playwright Version: [v1.40]
- Operating System: Windows 11
- Browser: Chromium
- Other info:

After installing 1.40, I compiled my local project with tsc
![image](https://github.com/microsoft/playwright/assets/727751/6236bf8e-5cce-473f-96b6-c18e831487a0)

I got a bunch of errors complaining about `asyncDispose`. 
![image](https://github.com/microsoft/playwright/assets/727751/bda0956d-2588-4526-8369-a965e25d18bb)

How do I get rid of the errors? (node_modules already excluded)
![image](https://github.com/microsoft/playwright/assets/727751/c6beae07-563b-4bda-be1a-9e059013f5e7)

Here is my list of packages in case I need to update something.
![image](https://github.com/microsoft/playwright/assets/727751/0e719572-7748-4bdb-b52e-c4cac0d6ad1d)

I use tsc to pass my CI build, so I need the build to be passed. The reason why I use it in my CI because it would take more than 40 mins to run all tests, and my build server also has no access to my SUT. Meanwhile, the time is still growing as I'm writing more and more tests. Thx.

**Comment by firstblood** [comment]
> Workaround for me was setting target in tsconfig to ESNext

I tried but nothing changed.

**Comment by dimkin-eu** [comment]
new PW has Node 20 - could be related ?

**Comment by yury-s** [comment]
@firstblood  can you share full project or at least complete tsconfig? Also what is your node version?

**Comment by firstblood** [comment]
> @firstblood can you share full project or at least complete tsconfig? Also what is your node version?

Hi, I can only share my tsconfig

![image](https://github.com/microsoft/playwright/assets/727751/eea38b1e-03b7-4470-b800-0f3ad8baba9d)

**Comment by firstblood** [comment]
I updated typescript to latest 5.3.2 and update tsconfig to 
![image](https://github.com/microsoft/playwright/assets/727751/8061dc86-12ea-466b-ad22-d15a19a3842d)

It solves the issue.
