### ISSUE TITLE
[BUG] Switch to window is blank when opened in storage state

### ISSUE THREAD

**Issue by Rajaneeshkumar** [microsoft/playwright#28265]
### System info
- Playwright Version: 1.32.3
- Operating System:  macOS 13.2.1
- Browser: Chromium

**Config file**

```js
// playwright.config.ts
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  globalSetup: require.resolve('./global-setup'),
  use: {
    baseURL: process.env.IOURL,
    storageState: './storageState.json',
  },
   /* Configure projects for major browsers */
  projects: [
    {
      name: "PLAYWRIGHT",
      use: {
        ...devices["Desktop Chrome"],
        headless: true,
        ignoreHTTPSErrors: true,
        trace: "on-first-retry",
        viewport: { width: 1440, height: 719 },
        baseURL: process.env.IOURL,
        storageState: "./storageState.json",
      }
    },
    {
      name: "firefox",
      use: {
        ...devices["Desktop Firefox"],
        headless: true,
        baseURL: process.env.IOURL
      }
    },

    {
      name: "webkit",
      use: { ...devices["Desktop Safari"], baseURL: process.env.IOURL }
    }

    /* Test against mobile viewports. */
    // {
    //   name: "Mobile Chrome",
    //   use: { ...devices["Pixel 5"], baseURL: process.env.BASE_URL }
    // },
    // {
    //   name: "Mobile Safari",
    //   use: { ...devices["iPhone 12"], baseURL: process.env.BASE_URL }
    // }

    /* Test against branded browsers. */
    // {
    //   name: 'Microsoft Edge',
    //   use: { channel: 'msedge' },
    // },
    // {
    //   name: 'Google Chrome',
    //   use: { channel: 'chrome' },
    // },
  ]
};
export default config;
```
**Global setup file**
```js
// global-setup.ts
import { chromium, FullConfig } from '@playwright/test';

async function globalSetup(config: FullConfig) {
  const { baseURL, storageState } = config.projects[0].use;
  const browser = await chromium.launch();
  const page = await browser.newPage();
  await page.goto(baseURL!);
  await page.fill('input[name="user"]', 'user');
  await page.fill('input[name="password"]', 'password');
  await page.click('text=Sign in');
  await page.context().storageState({ path: storageState as string });
  await browser.close();
}

export default globalSetup;
```
**Test file (self-contained)**

```js
import { test } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('/dummy.com');
  await page.click('[data-test="profile"]')
  // You are signed in!
});
```

**Steps**
-I've successfully implemented the storage state feature in Playwright using the provided configuration.

-The authentication process is carried out in one Chromium window, which is then closed. Following that, a new Chromium window is opened with the storage state seamlessly restored.

-In this new window, I'm performing specific operations. However, when I click a button, which is expected to trigger the opening of another window per the application's behavior, the new window appears blank. This behavior occurs specifically in the Chromium window with the restored storage state, where I am currently working.

**Expected**

-The expected behavior is that a new window should open with a specific URL. When I don't use the storage state feature, this functionality works as intended, and the new window is successfully opened with the correct URL.

**Actual**

-The issue arises when utilizing the storage state, as the new window opens but appears blank.
<img width="1318" alt="blankpage" src="https://github.com/microsoft/playwright/assets/32064716/1be799f0-aca3-4b29-84bf-d943a28b7bd7">

**Comment by Rajaneeshkumar** [comment]
@mxschmitt Could you please help me here

**Comment by yury-s** [comment]
Without knowing what the app does it's hard to tell why it is not working. It might be that it needs some session storage state which is [not persisted](https://playwright.dev/docs/auth#session-storage) or something else (indexeddb state?). If you think this is a bug in Playwright we need a minimal repro that we could run locally.

**Comment by mxschmitt** [comment]
Closing as per above. Feel free to re-file if you can provide a repro. Thanks!
