### ISSUE TITLE
[Feature] test VSCode extensions

### ISSUE THREAD

**Issue by mmkal** [microsoft/playwright#28266]
I'd like to test a VSCode extension I'm building using playwright (actually, an eslint plugin, so it's the eslint extension really). I saw that [electron is (experimentally) supported](https://playwright.dev/docs/api/class-electron), so it might in theory be already possible?

**Comment by mxschmitt** [comment]
You might be interested in [this](https://github.com/microsoft/playwright-vscode/tree/main/tests-integration). We use it to fully end-to-end test our extension in addition to our unit tests. This is is not officially supported from VSCode, so their selectors might break in the future.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.

**Comment by mmkal** [comment]
Haven't tried yet but this looks perfect, thank you!
