### ISSUE TITLE
[BUG]  State data Loss After Invoking page.reload in Firefox Browser

### ISSUE THREAD

**Issue by kirakiray** [microsoft/playwright#28264]
The testing scenario below provides a downloadable example for installation and evaluation.

### System info
- Playwright Version: [v1.40.0]
- Operating System: [macOS 14.0]
- Browser: [Firefox]

<img width="1041" alt="image" src="https://github.com/microsoft/playwright/assets/5945154/982796a2-6c56-4753-bdc5-d45473b9dcce">

### Source code

```html 
<!-- page1.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>page1</title>
  </head>
  <body>
    page1
    <br />
    <br />
    <script>
      const ele = document.createElement("div");
      ele.innerHTML = history.state || "null";
      document.body.append(ele);
      if (location.hash !== "#nopush") {
        history.pushState(["has state"], "", "#nopush");
      }
    </script>
  </body>
</html>
```

```javascript
import { test } from "@playwright/test";

test("In firefox will fail", async ({ page, browserName }) => {
  await page.goto("http://localhost:3348/test-firefox/page1.html");

  await page.getByText("null").click();

  await page.reload();

  await page.getByText("has state").click();
});
```

**Steps**
- [Run the test]

**Expected**

firefox runs successfully

**Actual**

firefox failed after running

**Comment by kirakiray** [comment]
[firefox-issuse.zip](https://github.com/microsoft/playwright/files/13424793/firefox-issuse.zip)

**Comment by yury-s** [comment]
Same happens if I manually reload the page in the bundled firefox, but works fine in official build 120.

**Comment by mxschmitt** [comment]
A workaround which would work in the meantime:

```ts
  await page.evaluate(() => window.location.reload())
```

**Comment by silva96** [comment]
```js
page.evaluate: Execution context was destroyed, most likely because of a navigation
```

this fixes Firefox but breaks Chrome
