### ISSUE TITLE
[Feature] Add link to Screenshots API to docs

### ISSUE THREAD

**Issue by ahayes91** [microsoft/playwright#28275]
Hey folks! This should be a quick one 😁 
On https://playwright.dev/docs/screenshots the Screenshots API is mentioned, but there's no link:

> Screenshots API accepts many parameters for image format, clip area, quality, etc. Make sure to check them out.

More than happy to contribute to update this, I just wanted to confirm where the best link is - is it [this](https://javadoc.io/doc/com.microsoft.playwright/playwright/latest/com/microsoft/playwright/Page.ScreenshotOptions.html) or somewhere else?

**Comment by yury-s** [comment]
https://playwright.dev/docs/api/class-page#page-screenshot would be the right link.
