### ISSUE TITLE
[Feature] Add new Locators (parent, siblings)

### ISSUE THREAD

**Issue by lucasdonato** [microsoft/playwright#28272]
Hi, it would be very interesting to create new locators to capture parent() and sibling() elements, unfortunately I am using xpath to get around this "problem".

Example:
**page.locator('//label[@for="phone"]/following-sibling::*//input')**

it could be:
**page.locator('label[for="phone"]').parents().locator('input')**
**page.locator('label[for="phone"]').siblings().locator('input')**

https://github.com/microsoft/playwright/issues/16155

**Comment by yury-s** [comment]
Folding into https://github.com/microsoft/playwright/issues/23718, please upvote that issue instead.
