### ISSUE TITLE
[BUG] - Multiple calls to launchPersistentContext fail in non-headless mode 

### ISSUE THREAD

**Issue by karthikiyengar** [microsoft/playwright#2828]
**Context:**
- Playwright Version: 1.1.0-next.1593741191701
- Operating System: Linux
- Node version: v10.15.0
- Browser: Chromium

**Code Snippet**

```javascript
const { chromium } = require('playwright')
const path = require('path')

;(async () => {
  const p1 = path.join(__dirname, 'p1')
  const p2 = path.join(__dirname, 'p2')

  console.log('Launching B1')
  const b1 = await chromium.launchPersistentContext(p1, {
    headless: false,
  })
  console.log('Launching B2')
  const b2 = await chromium.launchPersistentContext(p1, {
    headless: false,
  })
  console.log('Done')
})()
```

**Describe the bug**

The code snippet fails with the error:
```
Launching B1
  pw:api => browserContext.waitForEvent started +0ms
  pw:api <= browserContext.waitForEvent succeeded +48ms
  pw:api => page.waitForLoadState started +0ms
  pw:api <= page.waitForLoadState succeeded +1ms
Launching B2
(node:887064) UnhandledPromiseRejectionWarning: Protocol error (Target.setDiscoverTargets): Target closed.
========= browserType.launchPersistentContext logs =========
[browser] <launching> /home/kiyengar/.cache/ms-playwright/chromium-782078/chrome-linux/chrome --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=TranslateUI,BlinkGenPropertyTrees,ImprovedCookieControls,SameSiteByDefaultCookies --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --user-data-dir=/home/kiyengar/development/app/clients/tests/jest-setup/p1 --remote-debugging-pipe about:blank
[browser] <launched> pid=887212
[browser] Opening in existing browser session.
============================================================
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.Error
    at Promise (/home/kiyengar/development/app/clients/node_modules/playwright/lib/chromium/crConnection.js:131:63)
    at new Promise (<anonymous>)
    at CRSession.send (/home/kiyengar/development/app/clients/node_modules/playwright/lib/chromium/crConnection.js:130:16)
    at CRSession.send (/home/kiyengar/development/app/clients/node_modules/playwright/lib/helper.js:79:31)
    at Function.connect (/home/kiyengar/development/app/clients/node_modules/playwright/lib/chromium/crBrowser.js:68:39)
    at Chromium._connectToTransport (/home/kiyengar/development/app/clients/node_modules/playwright/lib/server/chromium.js:51:38)
    at Chromium._innerLaunch (/home/kiyengar/development/app/clients/node_modules/playwright/lib/server/browserType.js:84:36)
(node:887064) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:887064) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
However, it works fine on headless mode, even with the same dataDir path. Note that this error does not occur when you provide distinct paths to `launchPersistentContext` in both modes.

**Comment by mxschmitt** [comment]
What kind of Linux distribution are you using? If you have no gui like kde/xfce, you need to use `xvfb-run`. Something like `xvfb-run node index.js`

**Comment by karthikiyengar** [comment]
@mxschmitt - I'm on Ubuntu 20.04 with XMonad, but I don't think that's relevant to the issue described.

I found https://github.com/puppeteer/puppeteer/issues/3440 that seems to be related. It looks like the official recommendation atleast with puppeteer is to not use the same `userDataDir` for multiple browser instances. A workaround for https://github.com/playwright-community/jest-playwright/issues/188 would be to add a nonce like `Date.now()` to the `persistentDataDir` so that tests can be parallelized. Thoughts?

**Comment by pavelfeldman** [comment]
`"Opening in existing browser session"` is the reason - Chrome will reuse the existing process when you run it twice with the same profile. And since there is new process, Playwright can't connect it.

What's your use case? You seem to be requesting the same persistent browser context twice, why not use the first one? If they indeed use the same persistent profile, they should share cookies, other offline data, etc.

**Comment by pavelfeldman** [comment]
(also, we recommend regular launch over launchPersiatentContext pretty much at all times)

**Comment by karthikiyengar** [comment]
My use case is around testing Chrome extensions using `jest-playwright` and it looks like a persistentContext is necessary for this.

@mxschmitt can confirm, but it looks like `jest-playwright` spawns a new browser instance for each test suite, thus leading to the error in the OP. Related PR linked in my previous post.

**Comment by mxschmitt** [comment]
> My use case is around testing Chrome extensions using `jest-playwright` and it looks like a persistentContext is necessary for this.
> 
> @mxschmitt can confirm, but it looks like `jest-playwright` spawns a new browser instance for each test suite, thus leading to the error in the OP. Related PR linked in my previous post.

`jest-playwright` launches 1 browser per type and for each test file a new context including page. You can use the `jest-playwright` utility methods to launch a new page e.g. for each individual test.

**Comment by karthikiyengar** [comment]
> for each test file a new context including page
 
@mxschmitt - I'm wondering how that'd work out in case we want to launch a persistent context instead, given that it's not possible to have multiple persistent contexts sharing the same directory. I'd be interested on your thoughts on the linked PR and comment [here](https://github.com/microsoft/playwright/issues/2828#issuecomment-653553618).

**Comment by aslushnikov** [comment]
> A workaround for playwright-community/jest-playwright#188 would be to add a nonce like Date.now() to the persistentDataDir so that tests can be parallelized. Thoughts?

@karthikiyengar if you absolutely have to launch with persistent dir, then this might be a decent workaround. 

> I'm wondering how that'd work out in case we want to launch a persistent context instead, given that it's not possible to have multiple persistent contexts sharing the same directory. I'd be interested on your thoughts on the linked PR and comment here.

Looks like this is more a `jest-playwright` discussion then a playwright one. Let's move the discussion in that repo; I'll close this issue for now.
