### ISSUE TITLE
[BUG] outputDir handling: unclear error message and the need to delete it

### ISSUE THREAD

**Issue by alexnb** [microsoft/playwright#28289]
### System info
- Playwright Version: v1.40
- Operating System: 22.04.1-Ubuntu or Docker
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from "@playwright/test";

const config: PlaywrightTestConfig = {
  outputDir: "/root/out",
};
export default config;
```

**Test file (self-contained)**

No test files required.

**package.json**
```json
{
    "name": "test1",
    "private": true,
    "dependencies": {},
    "scripts": {
      "test:e2e-packaged": "playwright test .",
      "test:install": "playwright install firefox"
    },
    "devDependencies": {
      "@playwright/test": "^1.40.0"
    }
}
```

**Steps**
- create a directory which can not be deleted by the user running `playwright`:
 ```bash
sudo mkdir /root/out
```
- call playwright
 ```bash
yarn install && yarn test:install && yarn test:e2e-packaged
```

**Expected**

Clear error message about `outputDir` not being writable.
The best would be when playwright would just delete the contents of the `outputDir` and not the `outputDir` itself. 

**Actual**

```
TypeError: object is not iterable (cannot read property Symbol(Symbol.iterator))
```

It is really hard to understand what is wrong. Also the [documentation](https://playwright.dev/docs/api/class-testproject#test-project-output-dir) says that the `outputDir` will be cleaned (and not deleted).

I noticed this issue in a docker environment, where a docker volume mount point was specified as an `outputDir`. Since a couple of days this does not work anymore, with the above error message. Although the directory specified was `rwx` for the user, playwright failed to run (because it probably tried to delete it and deleting volume mount point does not work withe the message `device busy`)

**Comment by yury-s** [comment]
Playwright will attempt to delete directory and if it fails it will fall back to deleting its content. The error is obscure because ts compilation produces non-equivalent code in playwright:

```ts
export async function removeFolders(dirs: string[]): Promise<Error[]> {
  return await Promise.all(dirs.map((dir: string) =>
    fs.promises.rm(dir, { recursive: true, force: true, maxRetries: 10 }).catch(e => e)
  ));
}
```
is translated to
```js
async function removeFolders(dirs) {
  return await Promise.all(dirs.map(dir => _fs.default.promises.rm(dir, {
    recursive: true,
    force: true,
    maxRetries: 10
  }))).catch(e => e);
}
```
which returns one error rather than array.

**Comment by yury-s** [comment]
Scratch that, turns out it was fixed recently by https://github.com/microsoft/playwright/pull/28239 but the fix is not published yet. It will be released in the next patch release of playwright.
