### ISSUE TITLE
[BUG] ERR_CONNECTION_REFUSED error while browsing localhost URLs on android tests

### ISSUE THREAD

**Issue by ankur-lt** [microsoft/playwright#28282]
### System info
- Playwright Version: 1.39.0, 1.28.0
- Operating System: MacOS Ventura
- Browser: Android chrome
- Other info: Running Playwright android tests with server-client mode

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Server script**

```js
async function launchAndroidServer() {
  const browserServer = await _android.launchServer({
    port: 5555,
    wsPath: "ws",
  });

  const wsEndpoint = browserServer.wsEndpoint();
  console.log("wsEndpoint:: ", wsEndpoint);
}

launchAndroidServer();
```
Client Script
```js
const { _android } = require('playwright');

(async () => {
  const device = await _android.connect(
      'ws://127.0.0.1:5555/ws'
  );

  console.log(`Model :: ${device.model()}, serial:: ${device.serial()}`)

  await device.shell('am force-stop com.android.chrome');
  const context = await device.launchBrowser();

  const page = await context.newPage();
  await page.goto('http://localhost:3002/');

  await page.close();
  await context.close();
})();

```

**Steps**
- Make sure to have an android emulator running
- Run the server script
- Run the client script

**Expected**
- The navigations should happen.

**Actual**
- Getting the following error while navigating to localhost URLs 
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

page.goto: net::ERR_CONNECTION_REFUSED at http://localhost:3002/
=========================== logs ===========================
navigating to "http://localhost:3002/", waiting until "load"
============================================================

```

- The navigation works fine for all other URLs, just fails for `localhost` URLs. I tested this with Playwright version 1.28 and 1.39.
- I tested this with other localhost servers as well, to make sure its not an issue with the server I am starting in my local.

@mxschmitt

**Comment by mxschmitt** [comment]
It's an Android emulator limitation that `localhost` does not work see [here](https://developer.android.com/studio/run/emulator-networking). You can use `10.0.2.2` to reach the localhost of your host.

**Comment by yury-s** [comment]
Closing per the response above, feel free to open a new issue if it doesn't work.
