### ISSUE TITLE
[BUG] expect statement is not accepting custom messages that are >1024 length

### ISSUE THREAD

**Issue by sandeepkandukuri03** [microsoft/playwright#28280]
I have a expect message with something like below
let json = {.....} // Big json object

expect(help.performSchemaValidation(pgxSchema, json), `Json data is as per the schema, json data: ${JSON.stringify(json, null, 2)}`).toBe(true);

I collect all these expect messages, inside onTestEnd method using result.steps , to upload the messages and status of all these expect messages to the Test management tool

Even though the JSON.stringify(json, null, 2) is working as expected, the expect message is not having the entire json ... 

at some point in middle of json, i will see something like this in the middle of JSON. 
  "pati-**8f780**-lineAnnotations"
  
  Is there any other way to collect the big message information in the result.steps ?

**Comment by yury-s** [comment]
We need more information to act on this report. Please file a new one and link to this issue when you get back to it!
