### ISSUE TITLE
[BUG] Failure in beforeAll does not end test when there are multiple beforeAll blocks

### ISSUE THREAD

**Issue by RenanGreca** [microsoft/playwright#28285]
### System info
- Playwright Version: [v1.35.1]
- Operating System: Windows 10
- Browser: All
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Test file (self-contained)**

```js
import { test, expect } from "@playwright/test";

test.beforeAll(() => {
  console.log(`Starting first beforeAll`)
  expect(false, `This should fail`).toBeTruthy()
})

test.beforeAll(() => {
  console.log(`Starting second beforeAll`)
  expect(false, `This should not happen`).toBeTruthy()
})

test(`Do whatever`, async() => {
  ...
})
```

**Steps**
- [Run the test]

**Expected**

The first beforeAll fails and the test execution should end. The second beforeAll should not be executed.

**Actual**

Test second beforeAll block is executed and the message "Starting second beforeAll" is displayed in the log.

**Comment by yury-s** [comment]
This is working as intended. Playwright always runs all beforeAll hooks and then all afterAll hooks even some of the have failures. It will skip tests if before* hooks fail.

**Comment by RenanGreca** [comment]
Thanks for the info @yury-s . Perhaps this behavior should be explained in the documentation? Under [beforeAll](https://playwright.dev/docs/api/class-test#test-before-all-1) or [failures](https://playwright.dev/docs/test-retries).

**Comment by vitalets** [comment]
> This is working as intended. Playwright always runs all beforeAll hooks and then all afterAll hooks even some of the have failures.

@yury-s could you share the reasons of such behavior?

If one of `beforeAll / before` hooks failed, we definitely know that test will not run, why spend time on running other beforeAll hooks?
I've checked a couple of test-runners, how they handle that situation:

* vitest (in [`sequence.hooks=list`](https://vitest.dev/config/#sequence-hooks) mode, that equals to Playwright behavior)
  - `beforeAll` hook fails -> no other `beforeAll` hooks run, but all `afterAll` hooks run
  - `afterAll` hook fails -> no other `afterAll` hooks run
  - `beforeEach` hook fails -> no other `beforeEach` hooks run, all `after / afterAll` hooks run
  - `afterEach` hook fails -> all other `afterEach / afterAll` hooks run
  
* cucumberJS: 
  - `beforeAll` hook fails -> no other hooks run 
  - `afterAll` hook fails -> no other `afterAll` hooks run
  - `before` hook fails -> no other `before` hooks run, all `after / afterAll` hooks run
  - `after` hook fails -> all other `after / afterAll` hooks run

So, none of them continue running `before*` hooks if some of them already failed.
Maybe there could be an option to configure that behavior? 
For example:
```ts
test.describe.configure({ hooksMode: 'fail-fast' });
```
