### ISSUE TITLE
I'm getting the same thing using pnpm, playwright 1.40.0, and Node 16. If I install pnpm with npm the error stops.

### ISSUE THREAD

**Issue by surajsahu8** [microsoft/playwright#28286]
I'm getting the same thing using pnpm, playwright 1.40,0 and Node 16. If I install pnpm with npm the error stops.

<img width="848" alt="Screenshot 2023-11-09 at 10 50 52 PM" src="https://github.com/microsoft/playwright/assets/805554/10acb91e-ef96-4cbd-9307-6828b4ff872d">

_Originally posted by @sturoid in https://github.com/microsoft/playwright/issues/21058#issuecomment-1805139964_

**Comment by yury-s** [comment]
Please follow the bug template and provide the steps to reproduce the problem.
