### ISSUE TITLE
[BUG] --grep / --grep-invert don't work as expected for setup project

### ISSUE THREAD

**Issue by gabriel-pq** [microsoft/playwright#28296]
### System info
- Playwright Version: [v1.40.0]
- Operating System: [macOS 14.1]
- Browser: N/A

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import type { PlaywrightTestConfig } from '@playwright/test';
import {config as baseConfig} from 'playwright-utils';


const localConfig: PlaywrightTestConfig = {
  globalSetup: require.resolve('../global-setup'),
  globalTeardown: require.resolve('../global-teardown'),
  ...baseConfig,
  projects: [
    {
      name: 'Setup',
      testMatch: '**/*.setup.ts',
      use: {
        baseURL: 'myOtherUrl',
      },
    },
    {
      name: 'E2E Tests',
      dependencies: ['Setup'],
      testIgnore: ['**/*.setup.ts'],
      use: {
        baseURL: 'myUrl',
      },
    },
  ],
};

export default localConfig;

```

**Setup file (self-contained)**

```js
test.describe('App1 Setup @app1', () => {
});

test.describe('App2 Setup @app2', () => {
});
```

**The interesting part**
1. IF the tag used in the Setup project **is not used in the E2E Tests project**, the command below **works as expected**!

2. IF the tag **is being used at least one time in the E2E Tests projects**, then **the Setup runs everything**, ignoring the tags BUT the E2E Tests project is selecting the tests fine!

3. IF we use two tags, let's say @app1-setup for the Setup and @app1 for the E2E Tests, we update the command below to include both tags, it does the same(runs everything from Setup and filters the correct tests from E2E Tests)

4. IF we use a tag that only exists for the E2E Tests, then run everything from Setup and filter the correct tests from E2E Tests.  - What should be the behavior here? SKIP Setup & Run the tests? or throw a message saying that there are no tests in the Setup containing the tag and throw an error?

Note: I'm wondering if it's a chain dependency with more than two projects if the tag is ignored until reaches the last project in the chain.

**Steps**
- Execute `pnpm playwright test --config=config/playwright.base.config.ts --grep @app1`

**Expected**

--grep / --grep-invert work as expected

**Actual**

When a tag is used across multiple projects, is ignored from the Setup project and runs everything in it. Or if a tag is used across the dependencies projects but not in the Setup, then the Setup runs everything in it.

**Comment by yury-s** [comment]
This is working as intended: grep/grep-invert filters are only applied to the root projects (those that don't have dependents). Playwright will run all tests from the dependency projects ignoring the filters. The assumption is that you need to run the setup project as a whole to prepare for running the tests. If this is not desirable you can split setup project into smaller ones so that test projects could depend only on the parts they require, in that case only dependencies for the projects with filtered tests will run.

**Comment by gabriel-pq** [comment]
Thanks @yury-s for the explanation & updating the docs 💯 

There is still a problem with how --grep / --grep-invert works: 

You said that:

> Playwright will run all tests from the dependency projects ignoring the filters.

IF I execute `pnpm playwright test --config=config/playwright.base.config.ts --grep @app1` and I have this tag ONLY in the setup, it will filter the tests, which violates what you said.

**Comment by yury-s** [comment]
> IF I execute `pnpm playwright test --config=config/playwright.base.config.ts --grep @app1` and I have this tag ONLY in the setup, it will filter the tests, which violates what you said.

It will filter the tests in `setup` project but run all tests from its dependency projects (if any). I.e. the filter is applied first to find which tests match, then it will take all the projects that contain matching tests and for each of them will add all tests from those project dependencies. So if a project has both a matching test and is a dependency of another project that has a matching tests then all tests from the former project will run. Hope this helps.
