### ISSUE TITLE
Browser no longer stays open in test runner after using persistent context

### ISSUE THREAD

**Issue by Attic0n** [microsoft/playwright#28292]
I've used the documentation here to set up a fixture to launch persistent contexts with Chrome extensions:
https://playwright.dev/docs/chrome-extensions

But now when using the test runner in VS Code with "Show browser" the browser always closes at the end of the test. Which isn't really desired as the purpose of the chrome extension was to help with debugging in the first place.
Any way to keep the browser from closing?

**Comment by yury-s** [comment]
Persistent context is not supported by the test runner yet. Folding into https://github.com/microsoft/playwright/issues/11833
