### ISSUE TITLE
[Feature] Immediate output of failure during test run

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright#28290]
Hi,

Would it be possible to have an option in the list reporter (and any other that it could apply to) to get it to immediately output failure information during the test run?

So right now, we might see a failure like this and then get the full output at the end:
```
✓  1 [setup] › tests\dependencies\setup\setupAdminAuth.spec.ts:5:7
x  2 [chromium] › tests\staging\e2e\cutting.spec.ts:1744:8
✓  3 [chromium] › tests\staging\e2e\copying.spec.ts:1344:8
✓  4 [chromium] › tests\staging\e2e\pasting.spec.ts:1546:8
```

But it would be nice to get some failure output whilst the test suite is running.  The is very useful if you are running manually to test some changes against a long running test suite.  It would give us the ability to immediately debug on another vs code instance and let the suite run:
```
✓  1 [setup] › tests\dependencies\setup\setupAdminAuth.spec.ts:5:7
x  2 [chromium] › tests\staging\e2e\cutting.spec.ts:1744:8
	Error: page.waitForEvent: Target page, context or browser has been closed
    =========================== logs ===========================
    waiting for event "framenavigated"
    ============================================================

       at src\pageObjects\basePage.ts:91

      89 |     }
      90 |
    > 91 |     await this.page.waitForEvent('framenavigated');
         |                     ^
      92 |   }
      93 |
      94 |   /**

        at AddDocumentPage.waitForNavigation (D:\Automation\my-project\src\pageObjects\basePage.ts:91:21)
        at AddDocumentPage.clickUploadDocument (D:\Automation\my-project\src\pageObjects\graphite\addDocumentPage.ts:215:5)
        at AddDocumentPage.addDocument (D:\Automation\my-project\src\pageObjects\graphite\addDocumentPage.ts:71:5)
        at D:\Automation\my-project\tests\staging\e2e\cutting.spec.ts:1793:7
        at D:\Automation\my-project\tests\staging\e2e\cutting.spec.ts:1787:5
✓  3 [chromium] › tests\staging\e2e\copying.spec.ts:1344:8
✓  4 [chromium] › tests\staging\e2e\pasting.spec.ts:1546:8
```

**Comment by yury-s** [comment]
This is not supported in console reporters, you can specify `-x/--max-failures` to terminate the run earlier. Alternatively, you can run the tests in ui mode which will show the error immediately, would that work for you?

> It would give us the ability to immediately debug on another vs code instance and let the suite run:

The failing test name is printed immediately by the list reporter, so you already know what to debug. Or are you saying that the error may be irrelevant?

**Comment by AndyGleed** [comment]
Hi, I am just trying out --ui as that appears to be the best option.  

It would be nice if UI mode would allow selection of which playwright config file to use though :)

**Comment by yury-s** [comment]
You can use the same [`--config`](https://playwright.dev/docs/test-cli#reference) option with UI mode to specify config. If you want some other selector to be added to the UI, please file a separate feature request with explanation.
