### ISSUE TITLE
[BUG] The inspector doesn't open with await page.pause() when running in Javascript Debug Terminal

### ISSUE THREAD

**Issue by raythurnevoid** [microsoft/playwright#28291]
### System info
- Playwright Version: [v1.39.0]
- Operating System: Windows 11
- Browser: All
- Other info:

Is it possible to remove this line? I'm commenting it in my node_modules and It seems working fine.

https://github.com/microsoft/playwright/blame/91c5bac52b2002509933b7df0a062dddf58ae5ef/packages/playwright-core/src/client/page.ts#L692

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
test('test', async ({ page }) => {
  await page.goto('https://playwright.dev/');
  await page.pause();
});
```

**Steps**
- Open Javascript Debug Terminal
- Run the test

**Expected**

To open the playwright inspector

**Actual**

The test ends successfully

**Comment by yury-s** [comment]
What command line do you use to run the test? [Note](https://playwright.dev/docs/api/class-page#page-pause) that the pause only works in headed mode.

**Comment by raythurnevoid** [comment]
> What command line do you use to run the test? [Note](https://playwright.dev/docs/api/class-page#page-pause) that the pause only works in headed mode.

I usually use `npx playwright test --ui`. The problem is that check I've linked in the description, it returns void in case a js inspector is attached and prevent the pw inspector to open.

**Comment by yury-s** [comment]
We recommend using either JavaScript debugger in VSCode with its breakpoints and stepping or UI mode or Playwright inspector. Using any two of them simultaneously is not recommended.
