### ISSUE TITLE
[BUG] Playwright is throwing error

### ISSUE THREAD

**Issue by DipakTated** [microsoft/playwright#28307]
Microsoft.Playwright.PlaywrightException: spawn UNKNOWN
=========================== logs ===========================
<launching> C:\Users\jlindt\AppData\Local\ms-playwright\chromium-1045\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\jlindt\AppData\Local\Temp\playwright_chromiumdev_profile-I3S297 --remote-debugging-pipe --no-startup-window
============================================================
   at async Task<T> Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(string guid, string method, Dictionary<string, object> dictionary)
   at async Task<T> Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(Func<Task<T>> action, bool isInternal)
   at async Task<IBrowser>

**Comment by DipakTated** [comment]
Microsoft.Playwright.PlaywrightException: spawn UNKNOWN
=========================== logs ===========================
<launching> C:\Users\jlindt\AppData\Local\ms-playwright\chromium-1045\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --headless --hide-scrollbars --mute-audio --blink-settings=primaryHoverType=2,availableHoverTypes=2,primaryPointerType=4,availablePointerTypes=4 --no-sandbox --user-data-dir=C:\Users\jlindt\AppData\Local\Temp\playwright_chromiumdev_profile-I3S297 --remote-debugging-pipe --no-startup-window
============================================================
   at async Task<T> Microsoft.Playwright.Transport.Connection.InnerSendMessageToServerAsync<T>(string guid, string method, Dictionary<string, object> dictionary)
   at async Task<T> Microsoft.Playwright.Transport.Connection.WrapApiCallAsync<T>(Func<Task<T>> action, bool isInternal)
   at async Task<IBrowser>

**Comment by mxschmitt** [comment]
Did you [install the browsers](https://playwright.dev/dotnet/docs/browsers#install-browsers) before? 

Could you set the `DEBUG=pw:browser` env var? This might yield more debug output.

We recommend updating Playwright, since you are using a very old version: https://www.nuget.org/packages/Microsoft.Playwright

**Comment by DipakTated** [comment]
I am using 1.38.0 version of playwright

**Comment by mxschmitt** [comment]
You are launching Chromium with revision 1045 which is [version 1.30](https://github.com/microsoft/playwright/blob/release-1.30/packages/playwright-core/browsers.json#L6) of Playwright. We strongly recommend updating.

**Comment by mxschmitt** [comment]
Closing as per above and we need clear repro steps / following the issue template. Please provide that and re-file, thanks.

**Comment by DipakTated** [comment]
How to run DEBUG=pw:browser env variable as am using playwright .Net dll


This is ,my code

 var exitCode = Program.Main(new[] { "install", "--with-deps", "chromium" });
 if (exitCode != 0)
 {
     throw new Exception(
         $"Playwright exited with code {exitCode} on install");
 }
