### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mukuljain102022** [microsoft/playwright#28306]
### System info
- Playwright Version: experimental-ct-react17": "1.34.3"
- Operating System: macOS 13.6.1
- Browser: [Chromium]

### Test code
`test('sample test', async ({ mount, page }) => {
    const component = await mount(<component to test>);
    await expect(component).toHaveScreenshot();
});`

### Issue
For above test, screenshot captured do not show components rendered. It shows a blank screenshot or partially rendered component on screenshot. This behaviour is not persistent. It does work sometime and we do get clear screenshot of the component. Not sure if its an issue with screenshot or the component is not rendered before screenshot kicks in.

**Comment by mxschmitt** [comment]
This issue is not following the issue template. Please re-file with following it and attaching a self-contained repro. Also we recommend to use a up-to-date version of Playwright.
