### ISSUE TITLE
VScode playwright test explorer randomly fails tests with Error: Target page, context or browser has been closed. 

### ISSUE THREAD

**Issue by dgadhia** [microsoft/playwright#28305]
Tests running fine from VScode extention until i did npm install -D @playwright/test@latest (version 40), i am expecting to run many tests from the extension
- Playwright Version: [40]
- Operating System: [Windows]
- Node.js version: [v18.16.0]
- Visual Studio Code version: [1.84.2]
- Playwright for VSCode extension version: [v1.0.18]
- Browser: [Chromium]

When i Run the suite locally it skips some tests, browser remains at about:blank and returns the below message : 

    Error: Target page, context or browser has been closed
    Call log:
      
navigating to "about:blank", waiting until "load"

![vscode test explorer](https://github.com/microsoft/playwright/assets/60907801/8bbc8485-561c-466c-9dc2-236f7c6616b2)

I have tried npm init playwright@latest --yes -- --quiet --browser=chromium --browser=firefox --browser=webkit thinking it was something to do with the browser. 

Please assist :)

**Comment by mxschmitt** [comment]
We need a reproducible in order to triage this further. Please re-file attaching a repository which demonstrates this issue you are running into. Thanks for your understanding.

**Comment by dgadhia** [comment]
Please see this GIF hoping it will elaborate more on the steps. Dont hesitate to message me thanks.
![Code_76pRsNDiIc](https://github.com/microsoft/playwright/assets/60907801/4ef0f248-a66b-4bb3-b7c0-6ddcd81d8779)

**Comment by hardeep-qa** [comment]
@mxschmitt @dgadhia, I'm also facing the same issue. This issue only happens when the 'Show browser' checkbox is checked.

**Comment by zsreech** [comment]
@mxschmitt  I am also facing similar issue.I am using vscode version:1.78.2 (Universal)  and where I try to run/debug a test using the test explorer as shown in the gif above the tests fail to run.
I see the test failing with the error message `Error: response.body: Target closed`

Running the tests via the terminal using yarn works fine. So my test code is fine. Can this be please looked at.

**Comment by younesjallouli** [comment]
Hello guys, 
I confirm that ithis is a bug in the VScode extension. I have the same issue when **Show browser** is enabled on the extension.

On run will pass, but the following run will fail (1/2).

The run that fails gets this 

![image](https://github.com/microsoft/playwright/assets/116430697/d895027e-0443-4b47-a22f-13bfd2965b2c)


![image](https://github.com/microsoft/playwright/assets/116430697/95668669-93af-4c1b-a306-15d5b71ab97b)

**Comment by younesjallouli** [comment]
Why is this issue closed, is there already a fix ?
