### ISSUE TITLE
[REGRESSION]: Version 1.40.0 Produces corrupted traces 

### ISSUE THREAD

**Issue by maxsudik** [microsoft/playwright#28319]
**Context:**
- GOOD Playwright Version: [1.37.1]
- BAD Playwright Version: [1.40.0]
- Operating System: [Windows/Mac]
- Node: [18.16.0/20.4.0]

Steps to reproduce:

1. Create new playwright project https://playwright.dev/docs/intro
2. Update to the latest:
`npm install -D @playwright/test@latest`
`npx playwright install`
`npm install`
4. make sure you have these
```
“devDependencies”: {
    “@playwright/test”: “^1.40.0”,
    “@types/node”: “^20.9.4”
  }
```
in  package.json
5. Enable trace: "on"  in `playwright.config.ts`  in the `export default defineConfig({use:})`  section
6.  Run the below test
```
import { test } from "@playwright/test";
import * as fs from "fs";

test("Test Trace", async ({ browser }) => {
    const auth = "storages/storageState.json";
    if (!fs.existsSync(auth)) {
        fs.writeFileSync(auth, "{}");
    }
    const context = await browser.newContext({ storageState: auth });
    const page = await context.newPage();
    await page.goto("https://demo.playwright.dev/todomvc");
    await page.context().storageState({ path: auth });
});
```
7. Run `npx playwright show-report` and check the attached trace in the report
8. Verify the traces are displayed and functional. Note: if the trace works on the first attempt - try to reload the page

**Expected result:** Traces should be visible and functional.
**Actual result:** Traces are corrupted. Error is displayed: "**Could not load trace from http://localhost:9323/data/6a329ada265b653d117eeb16a2ba7b231cc78086.zip. Make sure a valid Playwright Trace is accessible over this url.**"

![image](https://github.com/microsoft/playwright/assets/40281293/016aa32e-81ff-452c-923c-b4de469fec00)

[corruptedTrace.zip](https://github.com/microsoft/playwright/files/13453050/trace.zip)

Other details:
When comment out this line:
```
await page.context().storageState({ path: auth });
```
the traces is generated as expected.

**Comment by mxschmitt** [comment]
I can repro, thanks for filing.

**Comment by mxschmitt** [comment]
1.40.0-alpha-oct-26-2023 good
1.40.0-alpha-oct-27-2023 bad

RANGE: https://github.com/microsoft/playwright/compare/47733b04fbc3d674d5a629097c72f0667f7eb189...54ebee79f7ab81c25f834f3fb1a7915f64a6294c

**Comment by rahul-sharma-uipath** [comment]
@pavelfeldman when can we expect 1.41.0 to be released with this fix?

**Comment by mxschmitt** [comment]
It will be in 1.40.1 soon. In the meantime we either recommend 1.39 or our [canary releases](https://playwright.dev/docs/canary-releases).
