### ISSUE TITLE
[BUG] When using global-setup tests doesn't appear in UI-Mode only the global-setup appear

### ISSUE THREAD

**Issue by ilorwork** [microsoft/playwright#28318]
### Bug explanation
I've implemented [global-setup](https://playwright.dev/docs/test-global-setup-teardown#setup)
and when I open UI-Mode the test list does not appears, instead the global-setup appears only.

### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 11]
- Browser: [Chromium, Firefox]
- Other info:

### Source code

**playwright.config**
``` typescript
import { defineConfig, devices } from "@playwright/test";
import path from "path";

export const STORAGE_STATE = path.join(__dirname, "playwright/.auth/user.json");

export default defineConfig({
  testDir: "./tests",
  // ...Rest of the configurations

  projects: [
    {
      name: "setup",
      testMatch: /global.setup\.ts/,
    },
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"], storageState: STORAGE_STATE },
      dependencies: ["setup"],
    },

    // FF
  ],
});
```

**global.setup.ts**
``` typescript
import { test as setup } from "@playwright/test";
import { STORAGE_STATE } from "../playwright.config";

setup("do authenticate", async ({ page }) => {
  // ...Some code

  await page.context().storageState({ path: STORAGE_STATE });
});
```

**myTest.spec.ts**
``` typescript
import { test, expect } from "@playwright/test";

test("has title", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveTitle(/title/);
});
```

**Steps**
- execute `npx playwright test --ui`

**Expected**

All the tests should appear. (see screenshot below)
![Expected screenshot](https://github.com/microsoft/playwright/assets/84942383/08c01808-2313-4672-8ff9-abe2e3b3b513)

**Actual**

The global-setup appears as test by itself.
all of the actual tests doesn't appear on the list. (see screenshot below)
![Actual screenshot](https://github.com/microsoft/playwright/assets/84942383/e07c187e-371b-4735-9599-3ae7131ed7bc)

> Note- Executing it doesn't changes anything, neither restarting UI-Mode

**Comment by mxschmitt** [comment]
Have you tried clicking on Projects and selecting your other projects as well? Or are there any other projects to select from?

<img width="306" alt="Screenshot 2023-11-24 at 14 38 30" src="https://github.com/microsoft/playwright/assets/17984549/9f3db21a-6e3f-4586-9c61-0a15a0372094">

**Comment by ilorwork** [comment]
Alright didn't notice this one.
But it's still annoying that every time I launch UI-Mode I have to filter for my project (chromium and FF)
I would be great if my last choice will get saved.
thanks a lot, sorry for bothering you, I tried so many things - somehow I missed the project filter...

**Comment by mxschmitt** [comment]
@ilorwork feel free to file a feature request for it, sounds like a great feature!
