### ISSUE TITLE
[Feature] - Interacting with the chrome extention

### ISSUE THREAD

**Issue by manojvenkatap** [microsoft/playwright#28317]
I have created my own chrome extension. I want to install the chrome extension and open on the browser page in the developer tool. and once the extension is loaded need to interact with extension and browser page content simultaneously.

Note: my extension will work only in the docked mode in the developer toolbar. it will not work when i open in URL await page.goto(`chrome-extension://${extensionId}/_generated_background_page.html`);

happy to share for further more details

**Comment by JobaDiniz** [comment]
Does this help? https://playwright.dev/docs/chrome-extensions

You can get a hold of the `service worker` on your test and send messages to it, as an user would do by clicking menus, etc:


**fixtures.ts**
```typescript
import { test as base, chromium, type BrowserContext, type Worker } from '@playwright/test';
import path from 'path';

export const test = base.extend<{ context: BrowserContext; extensionId: string; worker: Worker }>({
    context: async ({ }, use) => {
        //NOTE: __dirname is the path of the 'tests' folder
        const pathToExtension = path.join(__dirname, '../../', 'build');
        const context = await chromium.launchPersistentContext('', {
            headless: false,
            args: [
                //`--headless=new`,
                `--disable-extensions-except=${pathToExtension}`,
                `--load-extension=${pathToExtension}`,
            ],
        });
        await use(context);
        await context.close();
    },
    extensionId: async ({ context }, use) => {
        let [background] = context.serviceWorkers();
        if (!background)
            background = await context.waitForEvent('serviceworker');

        const extensionId = background.url().split('/')[2];
        await use(extensionId);
    },
    worker: async ({ context }, use) => {
        let [background] = context.serviceWorkers();
        if (!background)
            background = await context.waitForEvent('serviceworker');

        await use(background);
    },
});
export const expect = test.expect;
```

**e2e.spec.ts**
```typescript
import { test, expect } from './fixtures';

test.describe('getElements()', () => {
  test('should work on pages that contain iframes with different origin', async ({ page, worker }) => {
    await page.goto('https://somepage');
    await worker.evaluate(async () => {
      const tab = (await chrome.tabs.query({ active: true, currentWindow: true }))[0];
      const response= await chrome.runtime.sendMessage({type: 'bblabal'});
      expect(response.page.length).toBe(2);
    });
  });
});
```

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.

**Comment by manojvenkatap** [comment]
@pavelfeldman will there be an possibility to use in this way https://github.com/dequelabs/puppeteer-devtools

**Comment by pournima1689** [comment]
@manojvenkatap I am also want to open chrome extension in existing app browser page and not in separate tab. Were you able to resolve this issue ?

**Comment by manojvenkatap** [comment]
@pournima1689 this is working with the  https://github.com/dequelabs/puppeteer-devtools but i am looking to open with using playwright
