### ISSUE TITLE
[Feature] UI Mode - ability to select which playwright config file to run tests with

### ISSUE THREAD

**Issue by AndyGleed** [microsoft/playwright#28328]
We currently have 6 playwright configs which are used to perform certain tests.

It seems in UI Mode, it can only use playwright.config.ts but it would be nice if it could pick up all the other defined configs.  Perhaps if they had to be prefixed with playwright.config, it would know to add them in a drop down for selection?

playwright.config.ts
playwright.config.e2e.ts
playwright.config.api.ts

At the moment I just rename playwright.config.ts to something different and then rename the config I want to use to be playwright.config.ts.

**Comment by mxschmitt** [comment]
You can do `npx playwright test --config playwright.config.e2e.ts --ui` would that work for you?

Usually instead of splitting things like this up in different configs, users tend to split it up into projects inside a single config.
