### ISSUE TITLE
Playwright vs Cypress....maybe now Microsoft supports Bruno vs Postman

### ISSUE THREAD

**Issue by vicentlluis** [microsoft/playwright#28324]
I know that it's not the channel but I don't know how to scale Microsoft that it would be great for the IT community that Microsoft supports this project
https://www.usebruno.com/bru
https://github.com/usebruno/bruno

I think that it is a well thought-out project for api testing and it would be a great opportunity to Microsoft that supports, participates or promotes this project

For example, with Postman, it is impossible to collaborate on API collections because exports collections as giant JSON files, difficult to version control and diff. The solution created by Bruno Bru Markup language, it is saving information about your API requests using plain text files.

Finally also Github could create a template for running projects create by Bruno or creates a runner.

**Comment by mxschmitt** [comment]
Seems like the wrong channel and not related to Playwright. e.g. They are a paid product and we are fully open source.

There are no plans to integrate with this tool as of today.
