### ISSUE TITLE
[BUG] Ambiguous test outcome and status for serial mode

### ISSUE THREAD

**Issue by agoldis** [microsoft/playwright#28321]
### System info
- Playwright Version: `v1.39.0`, `v1.40.0`
- Operating System: All
- Browser: n/a
- Other info:

### Source code

- [x] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

https://github.com/currents-dev/pw-issue-2023-11-23-001

**Steps**

- Checkout  the demo repo, follow README instructions
- Run the test for `1.39`
- Run the test for `1.40`

**Expected**

The following test suite:

```ts
import { expect, test } from "@playwright/test";

test.describe.configure({ mode: "serial", retries: 1 });

test("A", async ({ page }, { retry }) => {
  if (retry === 0) {
    throw new Error("oh!");
  }
  if (retry === 1) {
    expect(true).toBe(true);
  }

});

test("B", async ({ page }, { retry }) => {
  throw new Error("oh!");
});
```

Is supposed to produce the following outcome:
- Test A results status: failed, passed
- Test B results status: skipped, failed

- `onTestBegin` should be invoked for every attempt of every test in a serial group as in `1.39`
- all tests should exhaust all attempts in a serial group

**Actual**

`1.40` runs serial tests group differently and produces different results:
- Test A results status: failed, passed
- Test B results status: failed

- `1.40` doesn't invoke `onTestBegin` for test `B` when `A` fails
- `1.40` doesn't retry test `B` and "swallows" the last retry

**Comment by mxschmitt** [comment]
Bisect NPM:
1.40.0-alpha-oct-25-2023 bad
1.40.0-alpha-oct-24-2023 good

RANGE: https://github.com/microsoft/playwright/compare/fe7847b126ce2059d02fbbbc1f632b04fdae3ef7...0bb9f7cdf7367185c89a24305ca21d0768e5d54f

Looks caused by https://github.com/microsoft/playwright/pull/27762

**Comment by dgozman** [comment]
@agoldis This is an intended change. After A fails, B is not run at all, so we do not produce a "skipped" run. Would you like to still see a skipped run for B? What's the reason? Please provide as much details about your usecase as you can.

**Comment by agoldis** [comment]
Would you like to still see a skipped run for B?

- Yes, if that's possible

What's the reason?

**Comment by dgozman** [comment]
We decided to revert #27762 for now. However, the definition of a flaky test must differentiate between tests skipped with `test.skip()` vs tests skipped because of serial mode failure or any other similar scenario. Otherwise, it does not work in some of the cases. We'll think more about it.

**Comment by agoldis** [comment]
Thanks for the quick turnaround @dgozman!
Exposing something like a skipped cause or a new status would do the job. I would be happy to contribute if you provide a direction.
