### ISSUE TITLE
[Question] Is it possible to run Playwright script with OWASP ZAP Proxy to generate security scan reports

### ISSUE THREAD

**Issue by MageshGit** [microsoft/playwright#28326]
I have configured the playwright browser to route it's requests via proxy by

 const browser = await chromium.launch({
        // Browser proxy option is required for Chromium on Windows.
        proxy: { server: 'per-context' },
        headless :false
      });
      const context = await browser.newContext({
        proxy: { server: 'localhost:8080' }
      });

- Zap proxy is listening to localhost & 8080

- I need to configure the Zap proxy api key.  Where should I configure this setting. Is it possible with playwright to do so. 
- Zap has support to run with selenium - https://www.zaproxy.org/docs/desktop/addons/selenium/

**Comment by mxschmitt** [comment]
If its just a proxy which you plug between the browser and the actual endpoint then it will work out of the box.

I recommend reaching out to zaproxy for further integration questions.
