### ISSUE TITLE
[BUG] Docs: install then test doesn't work without dependencies

### ISSUE THREAD

**Issue by dfberry** [microsoft/playwright#28331]
### System info
- Playwright Version: Version 1.40.0
- Operating System: Max Sonoma 14.1.1
- Other info:

Following instructions on this [install](https://playwright.dev/docs/intro#installing-playwright) page which is:
1. npm init playwright@latest
2. npx playwright test

The tests always fail with an error that dependencies are missing.

Expect: either give me the entire installation in the install doc including dependencies or create beginning tests that don't need the dependencies.

**Comment by mxschmitt** [comment]
> The tests always fail with an error that dependencies are missing.

Could you show us the error you are getting?

> Expect: either give me the entire installation in the install doc including dependencies or create beginning tests that don't need the dependencies.

`npx playwright test` will install the browsers and OS dependencies automatically. On macOS itself there are no OS dependencies required, so we are really curious on why its not working. The error message should give us more details.

**Comment by dfberry** [comment]
@mxschmitt Ok, my repo is incorrect. This is a GitHub Codespaces dev container. I've created a video of the issue. https://youtu.be/x4XZ3yRPPZk 

This is an environment and procedure I would like to use in official documentation. If I've made a mistake in the order of operations, please let me know the correct order for this environment.

**Comment by dfberry** [comment]
@mxschmitt The browsers aren't in the package.json. How does a reinstall know to install those? If I have a samples repo and use playwright, the only thing that would have the browsers is the package-lock.json. Or is there another entry somewhere?

**Comment by mxschmitt** [comment]
This sounds expected, when you were creating a new project, you didn't select "install system dependencies" which is declared as required, otherwise the browsers are not able to launch.

There are browsers which we install for you by default. Whats missing in your case are the system dependencies which are required to launch the browsers.

You either need to select "install system dependencies" or install them manual afterwards via `npx playwright install-deps` as per [here](https://playwright.dev/docs/browsers#install-system-dependencies) and as per the exception in your video.

**Comment by dfberry** [comment]
@mxschmitt - can you validate these are the correct steps to support playwright in an npm monorepo for Node?

1. Add npm to root: npm init -y
2. Add root level workspace in package.json - "workspaces": ["packages/*"]
3. Add root level script in package.json - "test": "npm run test -ws --if-present"
4. Create folder for tests: `mkdir ./packages/e2e-tests`
5. Move into folder: cd ./packages/e2e-tests
6. Init Playwright: npm init playwright@latest (accepting defaults because it is a OSS project that can be installed on any OS)
7. Add postinstall command to the e2e-tests package.json: 
    ```
    "scripts": {
      "test": "npx playwright test",
      "postinstall": "npx playwright install-deps"
    },
    ```
8. In e2e-tests, delete package-lock.json and node_modules
9. Go back to root: cd ../..
10. npm install
11. npm run test - all tests should pass

As show in this [repo](https://github.com/dfberry/cpp)

**Comment by mxschmitt** [comment]
> "postinstall": "npx playwright install-deps"

install-deps requires sudo and modifies the system. We strongly discourage putting commands like this inside `postinstall`. We instead would recommend putting that inside a CONTRIBUTING.md file.

The easiest way is to let the user execute `npx playwright install --with-deps` or you use our [Docker base image](https://playwright.dev/docs/docker) for your Codespace. You can also put the `npx playwright install --with-deps` command inside `postCreateCommand` of your devcontainer config. Make sure that you did `npm ci` before.

**Comment by pavelfeldman** [comment]
Closing as per above, please feel free to open a new issue if this does not cover your use case.
