### ISSUE TITLE
I want to know how to convert frameLocator to frame object

### ISSUE THREAD

**Issue by fancy45daddy** [microsoft/playwright#28334]
I want to know how to convert frameLocator to frame object, the requirement is I want to find an element <a href =...> in the frame, if I can not find the element, reload the frame until I find the element, but I do not find the waitforNavigation in frameLocator, but it exist in frame object. I want to know how to do that?

code sample:

const adframe = ad.locator('iframe#tag)
const adlocator = adframe.frameLocator(':scope').locator('a[href]')
while (!await adlocator.count())
{
    await adframe.evaluateHandle(_ => _.src += '')
   //?? how to convert adframe to frame object
}
const adhref = await adlocator.first().getAttribute('href')

Also I want to how to use css selector in page.frame(), just url and name is allowed is so limited

**Comment by fancy45daddy** [comment]
I can not use page.frame to construct frame object, because there is just an id atrribute in the iframe <iframe id=...> no name no src, I can not use page.frame

**Comment by pavelfeldman** [comment]
I guess I did not understand the question then. To assign new src to an iframe Node, you can do this:

```js
const adframe = ad.locator('iframe#tag');
await adframe.evaluate(e => e.setAttribute('src', 'blah'));
```

That will assign the new location and load it in the frame. Is that your objective?
