### ISSUE TITLE
[Question] Is it possible to launch contexts with different proxies?

### ISSUE THREAD

**Issue by imstefan13** [microsoft/playwright#2833]
Hi. I was wondering if you could launch contexts with different proxies?. If I want to launch a browser with a proxy I just do this.

` const browser = await chromium.launch({
            args: ['--no-sandbox',
            '--proxy-server=' + proxies
        ], 
            headless: false
        });`

Is it possible to launch a browser without setting a proxy, open multiple contexts, and finally set a different proxy in each context? Something like this.

`var browser = await chromium.launch({
        args: ['--no-sandbox'], 
        headless: false
    });
    const context = await browser.newContext({
        viewport: null,
        args: ['--proxy-server=34.91.135.38:80']
    })
    const page = await context.newPage();`

**Comment by pavelfeldman** [comment]
Not at the moment, but we have most of the bits for it. What is your use case? Btw, no need to use args, there are explicit proxy launch [options](https://playwright.dev/#version=v1.1.1&path=docs%2Fapi.md&q=browsertypelaunchoptions--options-proxy) now.

**Comment by imstefan13** [comment]
I am trying to launch multiple contexts to go to one website and do something. If I have 15 tasks all going to that website on the same ip they will realize it is a bot and not a consumer. I can have 15 tasks using proxies, but that would require 15 different browsers. This is memory consuming and it would be much more effective if I could launch multiple contexts with different proxies.

Let me know if you guys add proxy support for contexts. Thanks!

**Comment by jozsi** [comment]
@pavelfeldman - per my Slack discussion with @aslushnikov:
> I need to test a page using different proxies (location detected via GeoIP), so I need to launch a browser for each - doing it within the same browser instance but different contexts would spare some resources. I've seen a couple of issues regarding this. A workaround for it is to run a local proxy server that routes towards the desired proxy (I use different useragent strings for that; wanted to use basic auth but encountered some difficulties back in the puppeteer times)

**Comment by adamramadhan** [comment]
> I am trying to launch multiple contexts to go to one website and do something. If I have 15 tasks all going to that website on the same ip they will realize it is a bot and not a consumer. I can have 15 tasks using proxies, but that would require 15 different browsers. This is memory consuming and it would be much more effective if I could launch multiple contexts with different proxies.
> 
> Let me know if you guys add proxy support for contexts. Thanks!

+1 would be good if have as long as we could detect it closing on the event, rather then closing a browser and launching again it would be better on-page or on context.

**Comment by aslushnikov** [comment]
Let's move all the discussion regarding proxy-per-context to #3534. Please upvote that one to show your interest!
