### ISSUE TITLE
docs: adding information to `CONTRIBUTING.md` that `*.d.ts` files are generated based on markdown (md) files

### ISSUE THREAD

**Issue by dev-jonghoonpark** [microsoft/playwright#28338]
Hello, I recently submitted my first pull request (#28231) regarding toPass timeout configuration.

When I first saw this project, I didn't anticipate that `*.d.ts` files would be generated through markdown(md) files. As a result, it took me more time to analyze the code.

At the top of the `test.d.ts` file, it is mentioned:
`// This file is generated by /utils/generate_types/index.js`
However, since the concept of generating `*.d.ts` files through md files was new to me, I hadn't considered that at all.

Adding information to the contributing document that *.d.ts files are generated based on md files could be helpful for beginners like me.

For example,

> All API classes, methods, and events should have a description in docs/src.
> Type declaration files (e.g. `test.d.ts`, `testReporter.d.`, ...) created during the build process through the docs.

Adding this to the [writing-documentation](https://github.com/microsoft/playwright/blob/main/CONTRIBUTING.md#writing-documentation) section would be appropriate.

To @dgozman , if this improvement direction is acceptable, please comment! I will submit the PR right away.

Thank you.

**Comment by pavelfeldman** [comment]
Thank you for your suggestion. This would explain one of a thousands things that are known to maintainers and not known to the new contributors, so I don't think additional details like this in contributors guide would systematically help.
