### ISSUE TITLE
[BUG] Error compare snapshot fail only show different ratio = 0.01

### ISSUE THREAD

**Issue by Dinh246** [microsoft/playwright#28335]
### System info
- Playwright Version: [v1.39]
- Operating System: [All]
- Browser: [All, Chromium, Firefox, WebKit]
- Other info:

I have a test where I take screenshot of full page with default `maxDiffPixelRatio = 0.005`. When I try to edit the config (adding padding, margin) to change the actual screenshot and test if the test fail or not, surprisingly it passed. 
When I try to lower the maxDiffPixelRatio to 0.002 then it's failed, which is normal, however, the error state that the different ratio is about 0.01 -> this is not true because if it's true my option maxDiffPixelRatio = 0.005 should make the test fail too. So i'm thinking that the minimum ratio on playwright right now is 0.01 and gives me the wrong error.

**Steps**
- Run the test and generate expected screenshot of full page with maxDiffPixelRatio = 0.005
- Try to make a small changes in spacing between elements 
- Run the test again

**Expected**

The error compare snapshot failed should state the right ratio of different pixels like below 0.01

**Actual**

The minimum ratio error that playwright show is only 0.01 but the exact different pixel ratio is about 0.003

**Comment by mxschmitt** [comment]
We unfortunately need a clear reproduction in order to debug issues like this. Please re-file with a self-contained reproduction. Thanks!
