### ISSUE TITLE
[BUG] Playwright Components do not load styles

### ISSUE THREAD

**Issue by Hai-San** [microsoft/playwright#28332]
I'm trying to run visual regression tests with playwright components, but the component styles don't load at all. The component opens, but without styles and without the vue-fontawesome icons.

### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 11 WSL2 Ubuntu 20]
- Browser: [Chromium, Firefox, WebKit]
- Other info: Vue Components

### Source code

- [ ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

[https://github.com/your_profile/playwright_issue_title]

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/experimental-ct-vue2';

import { resolve } from 'path';

/**
 * @see https://playwright.dev/docs/test-configuration
 */
export default defineConfig({
  testDir: './playtests',
  /* The base directory, relative to the config file, for snapshot files created with toMatchSnapshot and toHaveScreenshot. */
  snapshotDir: './__snapshots__',
  /* Maximum time one test can run for. */
  timeout: 10 * 1000,
  /* Run tests in files in parallel */
  fullyParallel: true,
  /* Fail the build on CI if you accidentally left test.only in the source code. */
  forbidOnly: !!process.env.CI,
  /* Retry on CI only */
  retries: process.env.CI ? 2 : 0,
  /* Opt out of parallel tests on CI. */
  workers: process.env.CI ? 1 : undefined,
  /* Reporter to use. See https://playwright.dev/docs/test-reporters */
  reporter: 'html',
  /* Shared settings for all the projects below. See https://playwright.dev/docs/api/class-testoptions. */
  use: {
    /* Collect trace when retrying the failed test. See https://playwright.dev/docs/trace-viewer */
    trace: 'on-first-retry',

    /* Port to use for Playwright component endpoint. */
    ctPort: 3100,
    ctViteConfig: {
      resolve: {
        alias: {
          '@base': resolve(__dirname, './packages/base'),
          '@internal': resolve(__dirname, './packages/base/components/internal'),
          '@mixins': resolve(__dirname, './packages/base/stylesheets/mixins'),
        },
      },
    },
  },

  /* Configure projects for major browsers */
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
  ],
});
```

**Test file (self-contained)**

```js
import { test, expect } from '@playwright/experimental-ct-vue2';
import XAlert from '@base/components/XAlert/XAlert.vue';

test('should work', async ({ mount }) => {
  const component = await mount(XAlert, {
    props: {
      icon: 'lightbulb',
      title: 'Título',
      linkUrl: '#test',
      linkText: 'Link',
    },
    slots: {
      default: 'Slot default',
    },
  });

  await expect(component).toHaveScreenshot('XAlert.png');
});
```

**Steps**
- [Run: pnpm exec playwright test -c playwright-ct.config.js --update-snapshots]
- Also you can run with vsCode extension to open the browser.

**Expected**

![image](https://github.com/microsoft/playwright/assets/15642071/cb068d88-b2ed-4786-8016-5f8ca76db082)

**Actual**

![image](https://github.com/microsoft/playwright/assets/15642071/bc756217-2fb4-4bde-96b4-6f3463e0d718)

**Comment by sand4rt** [comment]
Hey @Hai-San, do you have a repo where i can reproduce the issue? Or could you share the code of `XAlert.vue` ?

**Comment by Hai-San** [comment]
Unfortunately it is a private repository of the company I work for. 

The component uses <script setup> and <style lang="scss" module> (CSS modules). It's vue.js 2, so we use "vue-demi": "0.14.5".

The icon comes from the icon component that uses vue-fontawesome.

I only used the CSS reset for global styles, but apparently it's not working, as each browser is different.

**Comment by sand4rt** [comment]
@Hai-San i cannot help without a repository where i can reproduce the issue. It doesn't have to be your entire private repository.

**Comment by Hai-San** [comment]
@sand4rt It really was global styles. A weekend of rest refreshed my memory.
