### ISSUE TITLE
Issue with Scripts Not Loading in AWS Lambda using Chromium+Playwright-Core, but Working Locally

### ISSUE THREAD

**Issue by vexelgray** [microsoft/playwright#28343]
Hello,

I'm facing a peculiar issue while using Chromium in an AWS Lambda environment for web scraping. The website in question is https://deporsite.centroinsulardedeportesgc.com/reserva-clases. When I try to load this website in the Lambda environment, certain scripts on the page don't seem to load correctly, preventing a critical table on the page from rendering.

**Description of the Problem:**

The specific problem arises when navigating to https://deporsite.centroinsulardedeportesgc.com/reserva-clases using Chromium in AWS Lambda. The expected behavior is to see the page fully loaded with a particular table displayed. However, it seems the scripts responsible for this table's rendering aren't executing as they should, leaving the page in a perpetual "loading" state, and the table never appears.

![screenshot-1700984973380](https://github.com/Sparticuz/chromium/assets/1415826/5fb63370-a682-4287-8cb1-16f3ced508f3)

**Local Environment vs. AWS Lambda:**

Interestingly, when I run the same script locally using Playwright with Chromium, everything loads perfectly without any issues. The page and the table render as expected. This issue seems to be specific to the AWS Lambda environment.

**Steps to Reproduce:**

Set up Chromium in an AWS Lambda environment.
Navigate to https://deporsite.centroinsulardedeportesgc.com/reserva-clases.
Observe the page's loading behavior.

**Expected Behavior:**
The page should load completely, with the table and all other elements rendered correctly (as it does in the local Playwright environment).

<img width="1257" alt="Captura de pantalla 2023-11-26 a las 11 42 12" src="https://github.com/Sparticuz/chromium/assets/1415826/c0e6d7dd-fc04-46aa-9db5-230aff3fd285">

**Actual Behavior in AWS Lambda:**

The page stays in a loading state indefinitely, and the table does not render at all.

Environment:

Chromium version: 119.0
Playwright version: 1.39.0
Local environment OS: MacOS 14.1.1 (23B81)
Additional tools/libraries used: "aws-sdk": "^2.1502.0"

Code:

<img width="680" alt="Captura de pantalla 2023-11-26 a las 11 49 20" src="https://github.com/Sparticuz/chromium/assets/1415826/e9fdd906-16f1-48fd-8fbc-242f054cf8cc">

Thank you in advance for your assistance and expertise.

**Comment by mxschmitt** [comment]
AWS Lambda is not officially supported. I recommend filing an issue at [@sparticuz/chromium](https://www.npmjs.com/package/@sparticuz/chromium).
