### ISSUE TITLE
Playwright Code Gen - Freezing [BUG]

### ISSUE THREAD

**Issue by rafaelgomez-webdevph** [microsoft/playwright#28342]
### System info
- Playwright Version: [v1.40]
- Operating System: [Windows 10]
- Browser: [ Chromium ]
- Other info: Playwright Codegen

![Page](https://github.com/microsoft/playwright/assets/113784023/851a55a6-0c87-4d3a-9e13-f5f0dd3721a8)

### Source code

- [x ] I provided exact source code that allows reproducing the issue locally.

**Link to the GitHub repository with the repro**

![Page](https://github.com/microsoft/playwright/assets/113784023/76655a05-23d3-4e45-97b4-c36d22243c7b)

or

**Config file**

```js
// playwright.config.ts
import { defineConfig, devices } from '@playwright/test';

export default defineConfig({
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'], },
    },
  ]
});
```

**Test file (self-contained)**

```js
it('should check the box using setChecked', async ({ page }) => {
  await page.setContent(`<input id='checkbox' type='checkbox'></input>`);
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('checkbox')).toBeChecked();
});
```

**Steps**
- [Run the test]
- [...]

**Expected**

Using Playwright Codegen should run smoothly after reaching our main page. 

**Actual**

After successful authentication in our page, Playwright freezes as if it's having a hard time identifying page elements. Later on I found out that the page may be rendering unnecessary elements ? Please refer to the uploaded file. This makes me wonder if Playwright CodeGen can exclude reading some page elements or the main problem is the web application that I'm working on how it was structured?

**Comment by mxschmitt** [comment]
This issue is not following the issue template. Please re-file with clear repro steps, thanks!
